### ISSUE TITLE
Missing pywrap_tensorflow

### ISSUE THREAD

**Issue by ss32** [tensorflow/tensorflow#2746]
### Environment info
Operating System: Linux Mint 17 (Ubuntu 14.04)

Installed version of CUDA and cuDNN: 
N/A - running CPU mode only

If installed from binary pip package, provide:

1. Which pip package you installed.
2. The output from `python -c "import tensorflow; print(tensorflow.__version__)"`.

```
$ python -c "import tensorflow; print(tensorflow.__version__)"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "tensorflow/__init__.py", line 23, in <module>
    from tensorflow.python import *
  File "tensorflow/python/__init__.py", line 48, in <module>
    from tensorflow.python import pywrap_tensorflow
ImportError: cannot import name pywrap_tensorflow
```

If installed from sources, provide the commit hash:
```
$ git rev-parse HEAD
b2a812b962f8088a8256d4e6271b9cd425936446
```

### Steps to reproduce
1. In python: import tensorflow
1a. Alternatively in python: import pywraper_tensorflow

### What have you tried?
1. pip install, pip uninstall/reinstall, built from source

**Comment by yaroslavvb** [comment]
I've seen this happen when the build failed for some reason. Do you have
any errors when you do "bazel build"?

Also you could try a sample test to see if anything works at all, ie:
bazel test -c opt //tensorflow/python:graph_util_test

**Comment by ss32** [comment]
It failed, which is odd because the eigenvalue test worked without any issues.  When I installed via pip I was getting the same error message at first, and then reinstalled via pip and got the error message from my first post

`cat /home/user/.cache/bazel/_bazel_user/f1b63f8b8ef5ddbd718e9d3afcdbe12a/tensorflow/bazel-out/local-opt/testlogs/tensorflow/python/graph_util_test/test.log
exec ${PAGER:-/usr/bin/less} "$0" || exit 1
-----------------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/user/.cache/bazel/_bazel_user/f1b63f8b8ef5ddbd718e9d3afcdbe12a/tensorflow/bazel-out/local-opt/bin/tensorflow/python/graph_util_test.runfiles/org_tensorflow/tensorflow/python/client/graph_util_test.py", line 21, in <module>
    import tensorflow as tf
  File "/home/user/.cache/bazel/_bazel_user/f1b63f8b8ef5ddbd718e9d3afcdbe12a/tensorflow/bazel-out/local-opt/bin/tensorflow/python/graph_util_test.runfiles/org_tensorflow/tensorflow/__init__.py", line 23, in <module>
    from tensorflow.python import *
  File "/home/user/.cache/bazel/_bazel_user/f1b63f8b8ef5ddbd718e9d3afcdbe12a/tensorflow/bazel-out/local-opt/bin/tensorflow/python/graph_util_test.runfiles/org_tensorflow/tensorflow/python/__init__.py", line 97, in <module>
    from tensorflow.python.platform import test
  File "/home/user/.cache/bazel/_bazel_user/f1b63f8b8ef5ddbd718e9d3afcdbe12a/tensorflow/bazel-out/local-opt/bin/tensorflow/python/graph_util_test.runfiles/org_tensorflow/tensorflow/python/platform/test.py", line 62, in <module>
    from tensorflow.python.framework import test_util
  File "/home/user/.cache/bazel/_bazel_user/f1b63f8b8ef5ddbd718e9d3afcdbe12a/tensorflow/bazel-out/local-opt/bin/tensorflow/python/graph_util_test.runfiles/org_tensorflow/tensorflow/python/framework/test_util.py", line 41, in <module>
    from tensorflow.python.platform import googletest
  File "/home/user/.cache/bazel/_bazel_user/f1b63f8b8ef5ddbd718e9d3afcdbe12a/tensorflow/bazel-out/local-opt/bin/tensorflow/python/graph_util_test.runfiles/org_tensorflow/tensorflow/python/platform/googletest.py", line 32, in <module>
    from tensorflow.python.platform import benchmark  # pylint: disable=unused-import
  File "/home/user/.cache/bazel/_bazel_user/f1b63f8b8ef5ddbd718e9d3afcdbe12a/tensorflow/bazel-out/local-opt/bin/tensorflow/python/graph_util_test.runfiles/org_tensorflow/tensorflow/python/platform/benchmark.py", line 112, in <module>
    class Benchmark(six.with_metaclass(_BenchmarkRegistrar, object)):
  File "/usr/lib/python2.7/dist-packages/six.py", line 617, in with_metaclass
    return meta("NewBase", bases, {})
  File "/home/user/.cache/bazel/_bazel_user/f1b63f8b8ef5ddbd718e9d3afcdbe12a/tensorflow/bazel-out/local-opt/bin/tensorflow/python/graph_util_test.runfiles/org_tensorflow/tensorflow/python/platform/benchmark.py", line 107, in __new__
    if not newclass.is_abstract():
`

**Comment by girving** [comment]
@ss32 Did I read that right that your build failed?  What was the error?

**Comment by ss32** [comment]
I never got an error when building, but that test failed, yes.  The eigenvalue test worked, though.

**Comment by yaroslavvb** [comment]
@ss32 Your traceback is missing the bottom part with the actual error.

Possibly related -- `pip install` interacts with `bazel test`. In particular, if you do "pip install" to setup TensorFlow for development in _python_build, then `bazel test` will look inside _python_build for dependencies. You can recover the proper behavior by moving _python_build to _python_build.disabled

**Comment by ss32** [comment]
Full output of 

`bazel test -c opt `//tensorflow/python:graph_util_test`

```
WARNING: /home/user/.cache/bazel/_bazel_user/f1b63f8b8ef5ddbd718e9d3afcdbe12a/external/protobuf/WORKSPACE:1: Workspace name in /home/user/.cache/bazel/_bazel_user/f1b63f8b8ef5ddbd718e9d3afcdbe12a/external/protobuf/WORKSPACE (@__main__) does not match the name given in the repository's definition (@protobuf); this will cause a build error in future versions.
WARNING: /home/user/.cache/bazel/_bazel_user/f1b63f8b8ef5ddbd718e9d3afcdbe12a/external/re2/WORKSPACE:1: Workspace name in /home/user/.cache/bazel/_bazel_user/f1b63f8b8ef5ddbd718e9d3afcdbe12a/external/re2/WORKSPACE (@__main__) does not match the name given in the repository's definition (@re2); this will cause a build error in future versions.
WARNING: /home/user/.cache/bazel/_bazel_user/f1b63f8b8ef5ddbd718e9d3afcdbe12a/external/highwayhash/WORKSPACE:1: Workspace name in /home/user/.cache/bazel/_bazel_user/f1b63f8b8ef5ddbd718e9d3afcdbe12a/external/highwayhash/WORKSPACE (@__main__) does not match the name given in the repository's definition (@highwayhash); this will cause a build error in future versions.
WARNING: /home/user/tensorflow/util/python/BUILD:11:16: in includes attribute of cc_library rule //util/python:python_headers: 'python_include' resolves to 'util/python/python_include' not in 'third_party'. This will be an error in the future.
INFO: Found 1 test target...
FAIL: //tensorflow/python:graph_util_test (see /home/user/.cache/bazel/_bazel_user/f1b63f8b8ef5ddbd718e9d3afcdbe12a/tensorflow/bazel-out/local-opt/testlogs/tensorflow/python/graph_util_test/test.log).
Target //tensorflow/python:graph_util_test up-to-date:
  bazel-bin/tensorflow/python/graph_util_test
INFO: Elapsed time: 12.257s, Critical Path: 4.60s
//tensorflow/python:graph_util_test                                      FAILED in 0.6s
  /home/user/.cache/bazel/_bazel_user/f1b63f8b8ef5ddbd718e9d3afcdbe12a/tensorflow/bazel-out/local-opt/testlogs/tensorflow/python/graph_util_test/test.log

```

**Comment by yaroslavvb** [comment]
Sorry, the command should be
bazel test -c opt//tensorflow/python:graph_util_test --test_output=streamed

For reference, I just did installation from head, and it worked, here's the
full sequence of commands I used

# start new GPU TensorFlow build
mkdir /Users/yaroslavvb/tfimmediate_macbook
cd /Users/yaroslavvb/tfimmediate_macbook
git clone https://github.com/tensorflow/tensorflow.git
cd tensorflow

# Remove files that "./configure" touches from index
git update-index --skip-worktree
tensorflow/core/common_runtime/gpu/gpu_device.cc
git update-index --skip-worktree tensorflow/stream_executor/dso_loader.cc
git update-index --skip-worktree
third_party/gpus/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc
git update-index --skip-worktree third_party/gpus/cuda/platform.bzl

./configure
host compiler: default
cuda sdk version: 7.5
location where tool is installed (/usr/local/cuda):
cudnn version: 5
where cudnn is installed:
compute capability: 3.0

bazel build -c opt --config=cuda tensorflow/...

**Comment by yaroslavvb** [comment]
@ss32 what version of Python are you using? `is_abstract` seems like something that Python should provide

**Comment by ss32** [comment]
@yaroslavvb 2.7.3.  There is something broken in my installation for sure.  I spun up a virtual machine and installed tensorflow via pip and it worked on the first try.  I'll have to go through and try to clean up what I've done and see if I can start fresh on my machine.

**Comment by ss32** [comment]
Solved with 

```
sudo pip uninstall six
sudo pip install six --upgrade --target="/usr/lib/python2.7/dist-packages"
```
From: https://github.com/tensorflow/tensorflow/issues/2016#issuecomment-215675850
