### ISSUE TITLE
Shutdown crash while running this script (most times)

### ISSUE THREAD

**Issue by stephenmdicke27** [tensorflow/tensorflow#27474]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
MS WINDOWS 10 x64

- TensorFlow installed from (source or binary):
binary

- TensorFlow version (use command below):
2.0.0-a0

- Python version:
Python 3.7.1

- CUDA/cuDNN version:
cuda_10.1.105_418.96_win10.exe
cudnn-10.1-windows10-x64-v7.5.0.56.zip

- GPU model and memory:
Gforce GTX 1050 Ti (DELL laptop)

You can collect some of this information using our environment capture [script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with
python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"

EXECUTION OF LINE:
C:\Users\steph>python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: module 'tensorflow' has no attribute 'GIT_VERSION'

**Describe the current behavior**
Durring running of this script, the computer shutdown crashes and reboots.

**Describe the expected behavior**
Finish the 100 Epochs of training and save the model *.h5

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

[Python Scripts.zip](https://github.com/tensorflow/tensorflow/files/3040051/Python.Scripts.zip)

The data is from Kaggle dogs-vs-cats.zip (file too big to attach: extract all to same subdirectory)

The crash seems to occur most often during the 100 Epochs (2nd) fit.

**Comment by ymodak** [comment]
I am inclined to think it is power supply issue. TF utilizes max cpu, gpu capabilities and draws high power. Can you please use [google colab](https://colab.sandbox.google.com/notebooks/welcome.ipynb#recent=true) and execute your code snippet? To use gpu computation in google colab select, edit > notebook settings > hardware accelerator. Let me know how it progresses. Thanks!

**Comment by stephenmdicke27** [comment]
Dell thinks the problem is with the OS and wants to reinstall it.

I am now getting another error. Here is the output of:
-------------------------------------------------------

import tensorflow as tf

print(tf.__version__)
print(tf.test.is_gpu_available())

-------------------------------------------------------
C:\Users\steph\PycharmProjects\Image1\TEMP_1\venv\Scripts\python.exe
C:/Users/steph/PycharmProjects/Image1/TEMP_1/mnist_conv2d_1a.py
2.0.0-alpha0
2019-04-12 20:21:26.598567: I
tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports
instructions that this TensorFlow binary was not compiled to use: AVX2
2019-04-12 20:21:26.603555: I
tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully
opened dynamic library nvcuda.dll
2019-04-12 20:21:26.613716: E
tensorflow/stream_executor/cuda/cuda_driver.cc:318] failed call to cuInit:
CUDA_ERROR_UNKNOWN: unknown error
False
2019-04-12 20:21:26.618324: I
tensorflow/stream_executor/cuda/cuda_diagnostics.cc:166] retrieving CUDA
diagnostic information for host: DESKTOP-KNR6M7Q
2019-04-12 20:21:26.618784: I
tensorflow/stream_executor/cuda/cuda_diagnostics.cc:173] hostname:
DESKTOP-KNR6M7Q
-------------------------------------------------------

Stephen Dicke

**Comment by ymodak** [comment]
I think you forgot to paste your new error stack here. However, since its a new error message and not related to original issue reported. Can you please post a new issue explaining it? We would like to keep each issue thread focusing on one problem. Thanks!
