### ISSUE TITLE
Multiclass AUC

### ISSUE THREAD

**Issue by ychervonyi** [tensorflow/tensorflow#27473]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using): 1.13.1.
- Are you willing to contribute it (Yes/No): Yes.

**Describe the feature and the current behavior/state.**
Multi-class AUC is a measure to examine the performance of multi-class classifiers. It is a natural extension of the well known and widely used AUC (Area Under the ROC curve) metric, which is defined for only binary classifiers. This measure was introduced in the paper 'Hand, David J., and Robert J. Till. "A simple generalization of the area under the ROC curve for multiple class classification problems." Machine learning 45, no. 2 (2001): 171-186'. It is widely used as the original paper currently has 1435 citation. Multi-class AUC reduces to the standard AUC in case of two classes.

**Will this change the current api? How?**
No. It will be just an additional function which can be used as a metric.

**Who will benefit with this feature?**
Machine learning practitioners and researchers, especially those in the medical field, for whom class separability and false positives are very important.

**Any Other info.**
I wrote the TensorFlow implementation and will be happy to contribute.

**Comment by pavithrasv** [comment]
This probably should be added to the add ons repo: https://github.com/tensorflow/addons.

**Comment by ychervonyi** [comment]
@pavithrasv  Oh, ok. I can prepare a PR or should I create a feature request there?

**Comment by pavithrasv** [comment]
I think feature request would be best for now, then we can decide whether it would be useful as an addon.
