### ISSUE TITLE
Skflow monitor bug?

### ISSUE THREAD

**Issue by yangmch** [tensorflow/tensorflow#2748]
I tried to use the monitor functionality from the [latest build of tensorflow](http://ci.tensorflow.org/view/Nightly/job/nightly-matrix-cpu/TF_BUILD_CONTAINER_TYPE=CPU,TF_BUILD_IS_OPT=OPT,TF_BUILD_IS_PIP=PIP,TF_BUILD_PYTHON_VERSION=PYTHON2,label=cpu-slave/lastStableBuild/), in order to keep track of validation loss. Here is my code:

`classifier = learn.TensorFlowRNNClassifier(rnn_size=EMBEDDING_SIZE, n_classes=8, cell_type='gru', input_op_fn=input_op_fn, num_layers=3, bidirectional=False, sequence_length=None, batch_size=50, steps=2000, optimizer='Adam', learning_rate=exp_decay, continue_training=False, clip_gradients=5.0)

val_monitor = learn.monitors.ValidationMonitor(X_test, y_test)

classifier.fit(X_train, y_train, val_monitor, logdir='log_rnn')`

Here is the error message:

> Traceback (most recent call last):
  File "/home/yangmch/Documents/FB word2vec/RNN/FB RNN.py", line 38, in <module>
    classifier.fit(X_train, y_train, val_monitor, logdir='log_rnn')
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/learn/python/learn/estimators/base.py", line 160, in fit
    monitors=monitors)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/learn/python/learn/estimators/estimator.py", line 498, in _train_model
    monitors=monitors)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/learn/python/learn/graph_actions.py", line 225, in train
    monitor.begin(max_steps=start_step + steps)
TypeError: unsupported operand type(s) for +: 'int' and 'ValidationMonitor'

**Comment by Anjum48** [comment]
I'm getting the same issue using RNN in Python 3.5 with the current and nightly build. Any ideas?

**Comment by ilblackdragon** [comment]
@yangmch @Anjum48 tf.learn and tensorflow in general is better used with named arguments.
For example in this case you are passing `ValidationMonitor` as number of steps.
If you should be `classifier.fit(x=X_train, y=y_train, steps=100, logdir='/path/', monitors=[ValidationMonitor])`.

Please let me know if this fixes your issue. Also can you point me where you took this usage from? [This example](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/examples/skflow/iris_val_based_early_stopping.py#L47) shows it correctly, so if there is another example somewhere we should fix it.

**Comment by Anjum48** [comment]
Thanks for the reply @ilblackdragon. I'm using the [digits example](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/examples/skflow/digits.py) as a guide for my project, which also recreates the error @yangmch first mentioned.

After changing the code to use named arguments in line 57:
```classifier.fit(x=X_train, y=y_train, monitors=[val_monitor])```

I'm now seeing this error:
```
/usr/bin/python3.5 /home/anjum/Python/test.py
WARNING:tensorflow:Using temporary folder as model directory: /tmp/tmp11b6ov7o
WARNING:tensorflow:learn.ops.conv2d is deprecated. Please use contrib.layers.convolution2d.
Traceback (most recent call last):
  File "/home/anjum/Python/test.py", line 57, in <module>
    classifier.fit(x=X_train, y=y_train, monitors=[val_monitor])
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/learn/python/learn/estimators/base.py", line 161, in fit
    monitors=monitors)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/learn/python/learn/estimators/estimator.py", line 508, in _train_model
    monitors=monitors)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/learn/python/learn/graph_actions.py", line 343, in train
    reraise(*excinfo)
  File "/usr/lib/python3/dist-packages/six.py", line 686, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/learn/python/learn/graph_actions.py", line 272, in train
    session, last_step + 1, [train_op, loss_op], feed_dict, monitors)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/learn/python/learn/graph_actions.py", line 121, in _run_with_monitors
    induce_stop = monitor.step_end(step, outputs)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/learn/python/learn/monitors.py", line 206, in step_end
    to_stop = self.every_n_step_end(step, output)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/learn/python/learn/monitors.py", line 368, in every_n_step_end
    metrics=self.metrics, name=self.name)
TypeError: evaluate() got an unexpected keyword argument 'batch_size'

Process finished with exit code 1
```

**Comment by ckleban** [comment]
I am seeing the "got an unexpected keyword argument 'batch_size'" error as well. I'm trying to set the batch size of the monitor in order to lower the number of CV values to test during each monitor iteration. I'm using tf 0.9 and I'm calling the monitor like so

`
val_monitor = monitors.ValidationMonitor(valid_X, valid_y, every_n_steps=100, batch_size=64)
classifier = learn.TensorFlowEstimator(model_fn=conv_model_v3, n_classes=my_classes,steps=my_steps, learning_rate=my_learning_rate,batch_size=my_batch_size)
classifier.fit(train_X, train_y, monitors=[val_monitor])
        
`

The error I get:
`
Traceback (most recent call last):
  File "/data/BitBucket/distracted-drivers/model3-deeper-cnn-with-gpu.py", line 481, in <module>
    val_monitor = monitors.ValidationMonitor(valid_X, valid_y, every_n_steps=100, batch_size=64)
TypeError: __init__() got an unexpected keyword argument 'batch_size'
`

**Comment by huixutech** [comment]
I've met the same problem when I used Jupyter Notebook environment to implement convolutional networks model with early stoping and custom decay function for learning rate according to [scikit-flow-intro](http://terrytangyuan.github.io/2016/03/14/scikit-flow-intro/).

The error log from Jupyter Notebook environment is here: https://gist.github.com/huixutech/1763c1b992247eecf639c38d5df4fe72

My script is here: https://gist.github.com/huixutech/f0ebd95cf0b1dff9102ca33fe7d58c87

However, when I run the python script in terminal environment, this problem also appears, but it can get a good score result. A little bit strange.

Is there any suggested solution?

**Comment by terrytangyuan** [comment]
@huixutech which version are you using?

**Comment by huixutech** [comment]
@terrytangyuan The TensorFlow commit version number is 10fbaf0581700641fc9b38b1bd722044bfb7c638

**Comment by terrytangyuan** [comment]
@huixutech The examples are out-dated. Estimators starting with `TensorFlow***` are deprecated and will be removed soon. Could you try using the new estimators? Pull requests for fixing those examples are more than welcomed!

**Comment by huixutech** [comment]
@terrytangyuan Sure, I'll try it. Thank you for your suggestion.

**Comment by gunan** [comment]
Automatically closing due to lack of recent activity. Please re-open when more information becomes available.

**Comment by litstrong** [comment]
I have same issue and find that it is because TensorFlowEstimator doesn't match base estimator for evaluate method, although it is going to be deprecated:

https://github.com/tensorflow/tensorflow/commit/a10fae7e2fb7fbe0a4b009e05692ec249cab76e1#diff-368aea0dba09d3a39aa518badc526cdb

**Comment by lmsasu-siemens** [comment]
@terrytangyuan: "The examples are out-dated. Estimators starting with TensorFlow*** are deprecated and will be removed soon. Could you try using the new estimators? " - which one works with monitors?

**Comment by terrytangyuan** [comment]
All other estimators should work
