### ISSUE TITLE
LSTMBlockFusedCell does not support using outputprojectionwrapper

### ISSUE THREAD

**Issue by wangyunxiaa** [tensorflow/tensorflow#27489]
I want to replace LSTMCell to LSTMBlockFusedCell for better performance.
but I have found that the LSTMBlockFusedCell does not have the project operation of the output.
so I add the outputprojectionwrapper to the LSTMBlockFusedCell by `cell = tf.contrib.rnn.OutputProjectionWrapper( tf.contrib.rnn.LSTMBlockFusedCell(config.hidden_size, forget_bias=0.0, cell_clip=config.cell_clip, use_peephole=config.use_peephole), output_size=n_outputs)`, but I got an error `TypeError: The argument 'cell' (<tensorflow.contrib.rnn.python.ops.lstm_ops.LSTMBlockFusedCell object at 0x7f2c08f1eb90>) is not an RNNCell: 'output_size' property is missing, 'state_size' property is missing, 'zero_state' method is missing.`
how to add projection in LSTMBlockFusedCell ?

**System information**
- TensorFlow version (you are using):conda install tensorflow 1.9.0
- Are you willing to contribute it (Yes/No): Yes

**Comment by jvishnuvardhan** [comment]
This is not Build/Installation or Bug/Performance issue. Please post this kind of support questions at [Stackoverflow](https://stackoverflow.com/questions/tagged/tensorflow). There is a big community to support and learn from your questions. GitHub is mainly for addressing bugs in installation and performance. Thanks!

**Comment by wangyunxiaa** [comment]
OK，I am sorry，
but, if I have a LSTMCell with peephole and projections, How could I do to speedup the Inference time?
the cudnnCell and LSTMBlockFusedCell all cannot use directly.

**Comment by jvishnuvardhan** [comment]
I am closing this issue as it is a support questions more suited for Stackoverflow. Thanks!
