### ISSUE TITLE
to build with '-g' option

### ISSUE THREAD

**Issue by guoyejun** [tensorflow/tensorflow#27495]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 16.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): source
- TensorFlow version: 2eebcc63a6cd3aad483bf7c1cb25df2b8780ef67
- Python version: Python 3.5.2
- Installed using virtualenv? pip? conda?:  virtualenv
- Bazel version (if compiling from source): bazel-0.24.0-installer-linux-x86_64.sh
- GCC/Compiler version (if compiling from source): gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.10) 
- CUDA/cuDNN version:
- GPU model and memory:

**Describe the problem**
My purpose is to build tensorflow c library (libtensorflow_framework.so and libtensorflow.so) to be stepped into within gdb via source code.

I tried two methods:
1) add '-g -O0' option during ./configure
![image](https://user-images.githubusercontent.com/10448440/55536831-5bdda100-56ed-11e9-9cb5-7d586981b292.png)

and then run the below commands to build the c libraries:
bazel test -c opt //tensorflow/tools/lib_package:libtensorflow_test
bazel build -c opt //tensorflow/tools/lib_package:libtensorflow

but, gdb shows that it is unable to read the symbols as below:
0x00007fffedea2400  0x00007ffff41f73ef  Yes (*)     /usr/local/lib/libtensorflow.so
0x00007fffe9245bc0  0x00007fffea040ea0  Yes (*)     /usr/local/lib/libtensorflow_framework.so

2) i tried dbg version with:
bazel test -c dbg //tensorflow/tools/lib_package:libtensorflow_test

and it never stops, with:
INFO: Build option --compilation_mode has changed, discarding analysis cache.
INFO: Analysed target //tensorflow/tools/lib_package:libtensorflow_test (0 packages loaded, 15440 targets configured).
INFO: Found 1 test target...
[7,070 / 7,073] Linking tensorflow/libtensorflow.so; 14876s local
^C
Bazel caught interrupt signal; shutting down.

and the build result is weird:
$ file bazel-out/k8-dbg/bin/tensorflow/libtensorflow.so          
bazel-out/k8-dbg/bin/tensorflow/libtensorflow.so: data

btw, my build commands come from https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/lib_package/README.md

**Comment by drpngx** [comment]
I'm not sure what `Yes()` is. It looks wrong.

1. Make sure you do the pip install if you want to use `/usr/local/lib` as above. Otherwise the bazel build will not be used unless you are running with a bazel environment.
2. You can use `nm bazel-out/k8-dbg/bin/tensorflow/libtensorflow.so` to find out what symbols are defined.
3. Use `--linkopt=-Wl,--strip-never` to never strip symbols in your build.
4. You can load symbols separately, by calling the linker command yourself and passing `-Wl,-Map=output.map`. You can load the mapfile from gdb.

I think it's probably that gdb is getting confused with the symbols, so `Yes()` is probably some other function.

**Comment by guoyejun** [comment]
> I'm not sure what `Yes()` is. It looks wrong.
> 
> 1. Make sure you do the pip install if you want to use `/usr/local/lib` as above. Otherwise the bazel build will not be used unless you are running with a bazel environment.

I think it is not a problem, because "bazel test/build -c opt *" successfully build libtensorflow.so and libtensorflow_framework.so.  I then link them into /usr/local/lib, and my application based on tf c lib works, the only issue is that i'm unable to step into the tf source code within gdb.

$ ll /usr/local/lib/libtensorflow*
lrwxrwxrwx 1 root   root          94 4月   4 18:51 /usr/local/lib/libtensorflow_framework.so -> /work/ml/tensorflow_work/tensorflow/bazel-out/k8-opt/bin/tensorflow/libtensorflow_framework.so*
lrwxrwxrwx 1 root   root          84 4月   4 18:51 /usr/local/lib/libtensorflow.so -> /work/ml/tensorflow_work/tensorflow/bazel-out/k8-opt/bin/tensorflow/libtensorflow.so*


> 2. You can use `nm bazel-out/k8-dbg/bin/tensorflow/libtensorflow.so` to find out what symbols are defined.

$ nm bazel-out/k8-dbg/bin/tensorflow/libtensorflow.so
nm: bazel-out/k8-dbg/bin/tensorflow/libtensorflow.so: File format not recognized

it is expected because:
$ file bazel-out/k8-dbg/bin/tensorflow/libtensorflow.so
bazel-out/k8-dbg/bin/tensorflow/libtensorflow.so: **data**

As for opt version,
$ file bazel-out/k8-opt/bin/tensorflow/libtensorflow.so
bazel-out/k8-opt/bin/tensorflow/libtensorflow.so: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=7bf0c37714b11d6ff260961f62facdac858f0966, **not stripped**

$ nm bazel-out/k8-opt/bin/tensorflow/libtensorflow.so | tail    (lots of output, so i use tail)
....
_ZZZZZN10tensorflow12_GLOBAL__N_123GrpcWorkerServiceThread23CompleteInstanceHandlerEPNS_4CallIS1_NS_4grpc13WorkerService12AsyncServiceENS_23CompleteInstanceRequestENS_24CompleteInstanceResponseEEEENKUlvE_clEvENKUlRKNS_6StatusEE0_clESD_ENKUliPKcE_clEiSG_E17vmodule_activated
00000000088fd780 b _ZZZZZN10tensorflow16XlaDeviceContext21CopyDeviceTensorToCPUEPKNS_6TensorEN4absl11string_viewEPNS_6DeviceEPS1_St8functionIFvRKNS_6StatusEEEENKUlSA_E1_clESA_ENKUlvE_clEvENKUliPKcE_clEiSI_E17vmodule_activated

> 3. Use `--linkopt=-Wl,--strip-never` to never strip symbols in your build.

From above, the lib symbols are not stripped.  Anyway, i can try this option, but where can I add it? (I'm not familiar with bazel)

> 4. You can load symbols separately, by calling the linker command yourself and passing `-Wl,-Map=output.map`. You can load the mapfile from gdb.

could you tell me how to pass `-Wl,-Map=output.map` to the linker command? thanks.

i just searched 'gdb mapfile' but could not find a web page to show how to load a mapfile from gdb, could you also please give me a help for the exact command? thanks a lot. ( symbol-file?)

> 
> I think it's probably that gdb is getting confused with the symbols, so `Yes()` is probably some other function.

yes, for 'opt' version, i guess gdb is getting confused with the symbols, and the mapfile might help.

As for 'dbg' option, i changed nothing else, and the build process never stops for hours, i guess there might be an issue within tf.

**Comment by byronyi** [comment]
If you only want to step into a handful of C++ sources, try adding `-g` to the ``--per_file_copt`` in your bazel build command, for example:

```
bazel build -c opt --config=opt --per_file_copt=//tensorflow/core/distributed_runtime/rpc/.*\.cc@-g //tensorflow/tools/pip_package:build_pip_package
```

See [here](https://docs.bazel.build/versions/master/user-manual.html#flag--per_file_copt) for details.

**Comment by drpngx** [comment]
I think your link to `/usr/local/lib` may not work. Not sure. We may be setting the `rpath` to look for the libraries in a different place. Can you try [this](https://github.com/bazelbuild/bazel/issues/6145)? Just create a shell script to run gdb and run the test under that script.

**Comment by guoyejun** [comment]
> If you only want to step into a handful of C++ sources, try adding `-g` to the `--per_file_copt` in your bazel build command, for example:
> 
> ```
> bazel build -c opt --config=opt --per_file_copt=//tensorflow/core/distributed_runtime/rpc/.*\.cc@-g //tensorflow/tools/pip_package:build_pip_package
> ```
> See [here](https://docs.bazel.build/versions/master/user-manual.html#flag--per_file_copt) for details.

thanks, i don't know where are the source files for the build, so I just choose //tensorflow/.*, as following:
bazel test -c opt --per_file_copt=//tensorflow/.*\.cc\.c@-g,-O0,--strip=never //tensorflow/tools/lib_package:libtensorflow_test
bazel test -c dgb --per_file_copt=//tensorflow/.*\.cc\.c@-g,-O0,--strip=never //tensorflow/tools/lib_package:libtensorflow_test

the option '--strip=never' is from the documentation link you just mentioned:
Caveat: If some files are selectively compiled with debug symbols the symbols might be stripped during linking. This can be prevented by setting --strip=never

but there is a build error:
gcc: error: unrecognized command line option '--strip-never'

I also tried with:
bazel test -c opt --per_file_copt=//tensorflow/.*\.cc\.c@-g,-O0,--linkopt=-Wl,--strip-never //tensorflow/tools/lib_package:libtensorflow_test
and still the same issue.

I'm currently trying with below commands from a clean source tree and build tree (rm -rf ~/.cache/):
bazel test -c opt --per_file_copt=//tensorflow/.*\.cc\.c@-g,-O0 //tensorflow/tools/lib_package:libtensorflow_test
bazel build -c opt --per_file_copt=//tensorflow/.*\.cc\.c@-g,-O0 //tensorflow/tools/lib_package:libtensorflow

hours need to get it finished. will report back after build finished.

**Comment by guoyejun** [comment]
> I'm currently trying with below commands from a clean source tree (rm -rf _; git checkout .) and build tree (rm -rf ~/.cache/): bazel test -c opt --per_file_copt=//tensorflow/._.cc.c@-g,-O0 //tensorflow/tools/lib_package:libtensorflow_test
> bazel build -c opt --per_file_copt=//tensorflow/.*.cc.c@-g,-O0 //tensorflow/tools/lib_package:libtensorflow
> 
> hours need to get it finished. will report back after build finished.

with this new command, gdb can read symbols from libtensorflow.so, but still unable to read from libtensorflow_framework.so, see below.  And it still unable to step into tf source code when I press 's' within gdb at the TF_* functions, such as TF_SessionRun, TF_GetCode, TF_GraphImportGraphDef
 
0x00007fffedea2400  0x00007ffff41f792f  Yes         /usr/local/lib/libtensorflow.so
0x00007fffe9245bc0  0x00007fffea040ea0  Yes (*)     /usr/local/lib/libtensorflow_framework.so
(*): Shared library is missing debugging information.

**Comment by guoyejun** [comment]
> I think your link to `/usr/local/lib` may not work. Not sure. We may be setting the `rpath` to look for the libraries in a different place. Can you try [this](https://github.com/bazelbuild/bazel/issues/6145)? Just create a shell script to run gdb and run the test under that script.

thanks, but my application is a stand-alone binary out of the tf source tree, and the below command failed to run:
bazel run --run_under=gdb /path_to_my_binary

ERROR: not a valid absolute pattern (absolute target patterns must start with exactly two slashes):

**Comment by byronyi** [comment]
Perhaps that's because these are compiled from the C sources which are not matched with the `*.cc` regexp. 

Maybe it works with ``--per_file_copt=//tensorflow/.*\.cc@-g,-O0,//tensorflow/.*\.c@-g,-O0``.

**Comment by guoyejun** [comment]
> Perhaps that's because these are compiled from the C sources which are not matched with the `*.cc` regexp.
> 
> Maybe it works with `--per_file_copt=//tensorflow/.*\.cc@-g,-O0,//tensorflow/.*\.c@-g,-O0`.

but my command has considered .c file:
![image](https://user-images.githubusercontent.com/10448440/55774626-7edecb00-5ac8-11e9-9175-2ed7698c46fe.png)

**Comment by guoyejun** [comment]
I tried as #27744 with:
bazel build  --cxxopt='-g' //tensorflow/tools/lib_package:libtensorflow_test

and it stops at the below line for hours:
[7,070 / 7,073] Linking tensorflow/libtensorflow.so; 10322s local

and, libtensorflow.so is there, but as data format.
$ file /work/ml/tensorflow_work/tensorflow/bazel-out/k8-opt/bin/tensorflow/libtensorflow.so
/work/ml/tensorflow_work/tensorflow/bazel-out/k8-opt/bin/tensorflow/libtensorflow.so: data

It is the same when i tried with -c dbg

**Comment by guoyejun** [comment]
i tried again with '-g' option, it takes ~6 hours to finish ...

`INFO: Elapsed time: 24108.686s, Critical Path: 21192.22s`
