### ISSUE TITLE
Where is the BahdanauAttention?

### ISSUE THREAD

**Issue by Yudonggeun** [tensorflow/tensorflow#27498]
tf 1.0: tensorflow.contrib.seq2seq.BahdanauAttention
Where is the BahdanauAttention with tf 2.0???

**Comment by ymodak** [comment]
Starting TF 2.0 contrib won't be a part of TF. However  [tensorflow/addons](https://github.com/tensorflow/addons). You can check [tfa.seq2seq](https://github.com/tensorflow/addons/blob/master/tensorflow_addons/seq2seq/README.md) to know more about your specific use case. Also you may a send PR to addons as well to add additional features.
