### ISSUE TITLE
source build won't accept GPU with compute capability lower than 3.5

### ISSUE THREAD

**Issue by christian-rauch** [tensorflow/tensorflow#27505]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- TensorFlow installed from (source or binary): source
- TensorFlow version: 1.13.1
- Python version: 2.7
- Bazel version (if compiling from source): 0.21.0
- GCC/Compiler version (if compiling from source): 7.3.0
- CUDA/cuDNN version: 10.0
- GPU model and memory: GeForce GTX 970

**Describe the problem**

The set of CUDA compute capabilities (CCC from now on) is set as {3.0, 5.2} during configuration. File `.tf_configure.bazelrc` contains `build --action_env TF_CUDA_COMPUTE_CAPABILITIES="3.0,5.2"` (full file: [tf_configure.bazelrc.txt](https://github.com/tensorflow/tensorflow/files/3043058/tf_configure.bazelrc.txt)). After transfering the resulting pip package to a PC with CCC 3.0, tensorflow will reject a GPU with CCC lower than 3.5.

**Provide the exact sequence of commands / steps that you executed before running into the problem**

1. `./configure` (resulting in [tf_configure.bazelrc.txt](https://github.com/tensorflow/tensorflow/files/3043058/tf_configure.bazelrc.txt))
2. `bazel build --config=opt --config=cuda //tensorflow/tools/pip_package:build_pip_package`
3. `./bazel-bin/tensorflow/tools/pip_package/build_pip_package /tmp/tensorflow_pkg`
4. move `/tmp/tensorflow_pkg/tensorflow-1.13.1-cp27-cp27mu-linux_x86_64.whl` to other PC with CCC 3.0

**Comment by christian-rauch** [comment]
I built the pip package directly on the target system with CCC 3.0 only (`TF_CUDA_COMPUTE_CAPABILITIES="3.0"`) but the pip package still requires CCC 3.5.

Is it actually possible to build TF with a CCC of less than 3.5? If no, this should be stated in the configure script before a user continues with the compilation.

**Comment by christian-rauch** [comment]
I am able to use CCC 3.0 when building version 1.12.0 from source.

**Comment by ymodak** [comment]
Unfortunately you cannot compile TF with CCC 3.0. TF 1.6 and above require CCC 3.5 or higher. We have mentioned it under [hardware requirements](https://www.tensorflow.org/install/gpu#hardware_requirements) section on TF website.

**Comment by christian-rauch** [comment]
Does this also apply to source builds? E.g. I can build TF 1.12 with CCC 3.0 from source.
Can you state in the documentation the minimum CCC version for binary and source builds per TF version?

**Comment by ymodak** [comment]
It does not apply to source builds, however we test tf against cc 3.5 and above. For ccc below 3.5 it may work but requires building from sources as you did. The minimum ccc version is mentioned in ````configure.py``` script. According to [```configure.py```](https://github.com/tensorflow/tensorflow/blob/8dc2d0eedac7760deb65254a8ef89878743299d7/configure.py#L1313) there are other limitations to tf build with ccc less than 3.5 Please take a look if haven't already. Thanks!

**Comment by christian-rauch** [comment]
@ymodak The version check you linked refers to XLA support. It is not a hint that is shown for general builds with CCC < 3.5.
It's still not clear, what the minimum CCC version for source builds for different TF versions is.

**Comment by christian-rauch** [comment]
@ymodak This issue is not solved. In https://github.com/tensorflow/tensorflow/issues/25329 the same issue is reported (i.e. CCC 3.0 works with TF 1.12 but fails with TF 1.13). If you closed this issue because of duplication, could you at least state in the other issue what the official state for CCC version support in source builds is?

**Comment by ymodak** [comment]
@gunan Can you PTAL? Thanks!

**Comment by gunan** [comment]
@chsigg to confirm.
It is actually documented in multiple places that we officially support cuda compute capabilities >= 3.5.
In configure script, it is documented here:
https://github.com/tensorflow/tensorflow/blob/master/configure.py#L999
And in the website it is documented here:
https://www.tensorflow.org/install/gpu#hardware_requirements

So we did push the minimum official support to >=3.5 and it is documented in the website.

**Comment by chsigg** [comment]
Correct, we no longer support compute capability < 3.5, even when building from source.
