### ISSUE TITLE
[Grappler] RemoveIdentityTranspose also removes conjugate

### ISSUE THREAD

**Issue by jheymann85** [tensorflow/tensorflow#27500]
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 18.04
- **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device**: N/A
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: 1.13
- **Python version**: 3.6
- **Bazel version (if compiling from source)**: N/A
- **GCC/Compiler version (if compiling from source)**: N/A
- **CUDA/cuDNN version**: 10.0
- **GPU model and memory**: N/A
- **Exact command to reproduce**: see below

During graph optimization, `RemoveIdentityTranspose` also removes a transpose if it conjugates the input (see [here](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/grappler/optimizers/arithmetic_optimizer.cc#L1092))

Simple example:
```
import tensorflow as tf
with tf.Graph().as_default():
    sess = tf.Session()
    a = tf.placeholder(tf.complex64)
    data = [[1j], [1j]]
    print(sess.run(tf.transpose(a, (0, 1), conjugate=True), {a: data}))  # not optimized
    print(sess.run(tf.transpose(a, (0, 1), conjugate=True) + 1, {a: data}))  # optimized, no conjugate will be applied
    print(sess.run(tf.conj(a) + 1, {a: data}))
```

Output:
```
[[0.-1.j]
 [0.-1.j]]
[[1.+1.j]
 [1.+1.j]]
[[1.-1.j]
 [1.-1.j]]
```

This can happen when using einsum/tensordot and a probably related issue is [#19771](https://github.com/tensorflow/tensorflow/issues/19771)

A possible fix would be to also check for `IsConjugateTranspose` [here](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/grappler/optimizers/arithmetic_optimizer.cc#L1137)

**Comment by mohantym** [comment]
Hi @jheymann85 ! PR [#40223](https://github.com/tensorflow/tensorflow/pull/40223) has fixed this issue. Attaching resolved [gist](https://colab.sandbox.google.com/gist/mohantym/c8f048bd7c6f73d54e9051cd28e70ca5/git_27500.ipynb) for reference. Can we move this issue to closed status now? Thanks!
