### ISSUE TITLE
A result calculated inside of the tf.while_loop is wrong and not raising any error/alert when it occurred by GPU OOM.

### ISSUE THREAD

**Issue by Han-sok** [tensorflow/tensorflow#27502]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): NO
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10 x64 with tensorflow on Spyder IDE
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: No
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below): 1.13.1
- Python version: 3.7
- Bazel version (if compiling from source): Not applicable
- GCC/Compiler version (if compiling from source): Not applicable
- CUDA/cuDNN version: CUDA 10.0 / cuDNN 7.5.0
- GPU model and memory: Titan RTX w/ 24.0GB of mem.

You can collect some of this information using our environment capture [script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with
python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"

**Describe the current behavior**
When we are dealing with huge data that are going to be processed by any tf operations, tf.while_loop does not raise any error/flag/alert when it reaches to the GPU memory limit and thus getting the wrong result. I think you should add some assertion so that people can learn what's the problem.

Here's the output
`WARNING:tensorflow:From C:\Users\SHS\Anaconda3\envs\tf_gpu\lib\site-packages\tensorflow\python\ops\tensor_array_ops.py:162: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.`
Instructions for updating:
Colocations handled automatically by placer.
shapes?  (?, **512**, 16, 16) (?, **512**, 16, 16)
values?  [[0. 0.]
 [0. 0.]] [[0. 0.]
 [0. 0.]] **>> Shouldn't be zeros. Have to be some numbers because I assigned random number and multiplied them.**
iterations?  50
Result? [[ -8.234    0.3125]
 [ -7.92   -10.53  ]]

runfile('C:/Users/SHS/FPGA Project files/Practices/test_for_fl16.py', wdir='C:/Users/SHS/FPGA Project files/Practices')
shapes?  (?, **64**, 16, 16) (?, **64**, 16, 16)
values?  [[-16.64  42.38]
 [ 37.9   34.2 ]] [[  3.514 -10.414]
 [ 20.88   24.62 ]] >> **when I reduce the data size it gives me the right values.**
iterations?  50
Result? [[-3.031   -0.01172]
 [-5.043    2.027  ]]

**Describe the expected behavior**
Output printed should not be zeros, because I assigned some random number.

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.
```python
import tensorflow as tf
import numpy as np
    
sess = tf.InteractiveSession()

a = tf.random.uniform([512, 512, 16, 16], minval=-3, maxval=3, dtype=tf.float16)
b = tf.random.uniform([512, 512, 16, 16], minval=-3, maxval=3, dtype=tf.float16)
c = tf.random.uniform([50, 512, 16, 16], minval=-3, maxval=3, dtype=tf.float16)
d = tf.random.uniform([50, 512, 16, 16], minval=-3, maxval=3, dtype=tf.float16)

i = 0
real = tf.TensorArray(dtype=tf.float16, size=50, name='REAL')
imag = tf.TensorArray(dtype=tf.float16, size=50, name='IMAG')
loop_cond = lambda i, *_: i < 50
def loop_body(i, r_array, i_array):
  r_array = r_array.write(i, tf.subtract(tf.multiply(a,c[i]), tf.multiply(b,d[i])))
  i_array = i_array.write(i, tf.add(tf.multiply(a,d[i]), tf.multiply(b,c[i])))
  i += 1
  return i, r_array, i_array
i, real, imag = tf.while_loop(loop_cond, loop_body, loop_vars=[i, real, imag])

real = real.stack()
imag = imag.stack()
real = tf.reduce_sum(real, axis=2)
imag = tf.reduce_sum(imag, axis=2)
print('shapes? ', real.shape, imag.shape)
print('values? ', sess.run(real[0,0, :2, :2]), imag.eval()[0,0, :2, :2])
print('iterations? ', i.eval())

i = 0
tt = tf.add(tf.multiply(a,c[i]), tf.multiply(b,d[i]))
print('Result?', tt.eval()[0,0,:2,:2])

```
**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by Han-sok** [comment]
Also, I want to ask this question. Is there any way we can avoid OOM(out-of-memory) when we are using tf.while_loop? We have a bunch of data/tensors that needs to be processed and tf.while_loop/tf.map_fn is our only hope to parallelize the code and get some performance. Right now, I am manually adjusting "parallel_iterations=" parameter but it's painful because we have multiples of loops in our codes.

**Comment by sanatmpa1** [comment]
@Han-sok,

I've checked the issue in latest stable version `2.6.0` and as you mentioned, it raises `ResourceExhaustedError: failed to allocate memory [Op:AddV2]` when tf.while_loop is causing OOM. Please take a look at this [gist here](https://colab.research.google.com/gist/sanatmpa1/23f2cbdefde27ce1bf56ca1c27aef345/27502.ipynb). Thanks!
