### ISSUE TITLE
Placeholder removed from tf 2.0

### ISSUE THREAD

**Issue by Mainak431** [tensorflow/tensorflow#27516]
tensorflow placeholder is not found on tf 2.0. I need to create a Tensor with shape = None. But As the placeholder is gone . I am not finding ways to do it the 2.0 way. Please help.

**Comment by Mainak431** [comment]
Placeholder is present at tf.compat.v1.placeholder . And can only be executed in eager mode off. 

#   tf.compat.v1.disable_eager_execution()

If we dont deactivate eager mode, we get this error -

tf.placeholder() is not compatible with eager execution.

Got this.

**Comment by rickrickrickyyy** [comment]
https://www.tensorflow.org/guide/migrate#low-level_variables_operator_execution
