### ISSUE TITLE
segmentation fault using tensorflow debugger

### ISSUE THREAD

**Issue by hugo-boser** [tensorflow/tensorflow#27520]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

When i type run in tfdbg i get a segmentation fault.

**System information**
- Have I written custom code?
yes i have.
- OS Platform and Distribution:
kali linux rolling 2019 (see tf_env)
- Python version:
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
not compiled from source
- CUDA/cuDNN version:
i don't know what CUDA is but i don't have Nvidia GPU i think but radeon amd?
i think tensorflow runs on my cpu?
- GPU model and memory:
 lspci -vnn | grep VGA -A 12
01:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Thames [Radeon HD 7500M/7600M Series] [1002:6840] (prog-if 00 [VGA controller])
	Subsystem: Toshiba America Info Systems Radeon HD 7670M [1179:fb22]
	Flags: bus master, fast devsel, latency 0, IRQ 29
	Memory at b0000000 (64-bit, prefetchable) [size=256M]
	Memory at c0000000 (64-bit, non-prefetchable) [size=128K]
	I/O ports at 3000 [size=256]
	Expansion ROM at 000c0000 [disabled] [size=128K]
	Capabilities: [50] Power Management version 3
	Capabilities: [58] Express Legacy Endpoint, MSI 00
	Capabilities: [a0] MSI: Enable+ Count=1/1 Maskable- 64bit+
	Capabilities: [100] Vendor Specific Information: ID=0001 Rev=1 Len=010 <?>
	Capabilities: [150] Advanced Error Reporting
	Kernel driver in use: radeon

You can collect some of this information using our environment capture [script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
output of tf_env_collect.sh:
[tf_env.txt](https://github.com/tensorflow/tensorflow/files/3045026/tf_env.txt)

You can also obtain the TensorFlow version 
with
python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"
i installed tensorflow in pycharm using pip (my projects uses the system interpreter)
tf.VERSION:
1.13.1
tf.GIT_VERSION:
b'v1.13.0-rc2-5-g6612da8'

**Describe the current behavior**
I first go to a terminal and type the following:
tensorboard --logdir=/root/files/Tensorboard/logs/ --debugger_port=6064
then in another terminal i type:
python3 NeuralNetwork.py --debug
i then see the run-start CLI like this.
![Schermafdruk van 2019-04-04 20-48-05](https://user-images.githubusercontent.com/41961612/55580465-e5f02e80-571a-11e9-9d56-e0ebe3fea6b5.png)

then i type run and i get an segmentation fault.
![Schermafdruk van 2019-04-04 20-50-34](https://user-images.githubusercontent.com/41961612/55580547-13d57300-571b-11e9-9b43-4dc0c2733fc5.png)

**Describe the expected behavior**
the expected behavior i think is that the run command would not crash the debugger.

**Code to reproduce the issue**
[Example.txt](https://github.com/tensorflow/tensorflow/files/3044988/Example.txt)
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by jvishnuvardhan** [comment]
@hugo-boser This is a stale issue. Just checking whether it is still an issue for you? Can you please check recent TF/TB versions and let us know whether the issue was resolved for you. Thanks!
