### ISSUE TITLE
Bug in tf.parallel_stack

### ISSUE THREAD

**Issue by mahmoud-abuzaina** [tensorflow/tensorflow#27521]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below): master branch from 9e0b9b9ff2b01e07c2a71ce0fbbae93a4bba86f9 and onward
- Python version: 2.7
- Bazel version (if compiling from source): 0.23.0
- GCC/Compiler version (if compiling from source): 7.3.0
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

**Describe the current behavior**
tf.parallel_stack is producing incorrect output.
**Describe the expected behavior**
tf.parallel_stack has to have same output as tf.stack or tf.concat
**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

The below reproducer code/test passes with any commit that precedes 9e0b9b9ff2b01e07c2a71ce0fbbae93a4bba86f9
```
import tensorflow as tf
import numpy as np

graph = tf.Graph()
with graph.as_default():
  images = np.random.random_sample((100, 24, 24, 3))
  parallel_stacked_images = tf.parallel_stack(images)
  stacked_images = tf.stack(images)
  concatenated_images = tf.concat(images, 0)

with tf.Session(graph=graph) as sess:
  np_parallel_stacked_images, np_stacked_images, np_concatenated_images = sess.run(
    [parallel_stacked_images, stacked_images, concatenated_images])

if np.array_equal(np_parallel_stacked_images, np_stacked_images):
  print ("Pass: outputs of tf.parallel_stack and tf.stack are equal")
else:
  print ("Fail: outputs of tf.parallel_stack and tf.stack are not equal")

if np.array_equal(np_parallel_stacked_images, np_concatenated_images):
  print ("Pass: outputs of tf.parallel_stack and tf.concat are equal")
else:
  print ("Fail: outputs of tf.parallel_stack and tf.concat are not equal")
```

**Other info / logs**
We have debugged this issue and found that this commit 9e0b9b9ff2b01e07c2a71ce0fbbae93a4bba86f9 actually causes the bug. That commit changes the set of `Edge`s in the graph from std::set (ordered) to gtl::FlatSet (unordered). TF has a graph optimizer pass for parallel_stack (or parallel_concat) that replaces ParallelConcat node with several _ParallelConcatUpdate nodes. But it seems that it assumes all in_edges are ordered which is not the case with gtl::FlatSet. Therefore, there is a problem in updating the output buffer that is using the incremental index (the `loc` attribute) which does not correspond to the right input_edge. In particular, I am talking about this code: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/common_runtime/parallel_concat_optimizer.cc#L83

**Comment by rmlarsen** [comment]
Thanks you so much for root causing this! We should probably move that graph rewrite to Grappler.

**Comment by mahmoud-abuzaina** [comment]
@rmlarsen We have a simple fix for this until it is moved to Grappler. Will submit a PR for that. It will be great if you can take a look at it.

**Comment by rmlarsen** [comment]
Sounds great!

**Comment by mahmoud-abuzaina** [comment]
@rmlarsen Here is the PR #27554 . Thanks!

**Comment by jvishnuvardhan** [comment]
This was resolved already with the PR https://github.com/tensorflow/tensorflow/pull/27554 as it was already merged. 

```
# Output
Pass: outputs of tf.parallel_stack and tf.stack are equal
Pass: outputs of tf.parallel_stack and tf.concat are equal
```

[Here](https://colab.research.google.com/gist/jvishnuvardhan/5caa1efff76de239a36fa68ced8a10d0/untitled.ipynb) is a gist for reference. Thanks!

Closing this issue as this was already resolved.
