### ISSUE TITLE
Tensorflow C++ API on Windows/VS2015: unresolved external symbol

### ISSUE THREAD

**Issue by caocuong0306** [tensorflow/tensorflow#27527]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: NA
- TensorFlow installed from (source or binary): source
- TensorFlow version: 1.13.1
- Python version: 3.5
- Installed using virtualenv? pip? conda?: pip
- Bazel version (if compiling from source): 0.19
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 9.2
- GPU model and memory: Nvidia GTX 1070

**Describe the problem**

I successfully built Tensorflow using Bazel from source.

I obtained the following files.

- bazel-bin\tensorflow\libtensorflow_cc.dll (renamed from libtensorflow_cc.so)
- bazel-bin\tensorflow\libtensorflow_cc.lib (renamed from liblibtensorflow_cc.so.ifso)
- bazel-bin\tensorflow\libtensorflow_framework.dll (renamed from libtensorflow_framework.so)
- bazel-bin\tensorflow\libtensorflow_framework.lib (renamed from liblibtensorflow_framework.so.ifso)

In Visual Studio 2015

- I included headers from bazel-genfiles (include/, third_pary/, com_google_absl, com_googlesource_code_re2, protobuf_archive\src, etc)
- I also configured Linked to link with .lib files.

**Provide the exact sequence of commands / steps that you executed before running into the problem**

In the code, I simply declare the following param:
auto root = tensorflow::Scope::NewRootScope();

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

Severity	Code	Description	Project	File	Line	Source	Suppression State
Error	LNK1120	3 unresolved externals	Program	D:\Project_Tensorflow\x64\Release\Program.exe	1	Build	
Error	LNK2011	precompiled object not linked in; image may not run	Program	D:\Project_Tensorflow\Program\TestTensorflow.obj	1	Build	
Error	LNK2001	unresolved external symbol "public: static class tensorflow::Scope __cdecl tensorflow::Scope::NewRootScope(void)" (?NewRootScope@Scope@tensorflow@@SA?AV12@XZ)	Program	D:\Project_Tensorflow\Program\utils.obj	1	Build	
Error	LNK2001	unresolved external symbol "public: __cdecl tensorflow::Scope::~Scope(void)" (??1Scope@tensorflow@@QEAA@XZ)	Program	D:\Project_Tensorflow\Program\utils.obj	1	Build	

Please help if you have an idea. Thank you very much.

**Comment by caocuong0306** [comment]
According to this guide (https://joe-antognini.github.io/machine-learning/windows-tf-project), “unresolved external symbol” errors occur if you don't include sufficient Additional Dependencies.

However, bazel generates only libtensorflow_cc.lib and libtensorflow_framework.lib, and I already included them both. 

Please give me a hand. Thanks.

**Comment by alpha-gradient** [comment]
兄弟，解决了吗？解决了告诉我说一声啊 = =，我也遇到同样的问题了。。

**Comment by Adnan-annan** [comment]
@alpha-gradient did you solve the problem ?

**Comment by sitting-duck** [comment]
Please check out a tutorial I wrote concerning this subject here: https://github.com/sitting-duck/stuff/tree/master/ai/tensorflow/build_tensorflow_1.14_source_for_Windows#step-7-build-the-dll

Feel free to ask me questions by responding to this comment or emailing ashley.tharp@gmail.com

**Comment by ymodak** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
