### ISSUE TITLE
TF2.0 / `SequenceFeatures` doesn't have a `_is_feature_layer` property.

### ISSUE THREAD

**Issue by seungbaeji** [tensorflow/tensorflow#27531]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Mac OS
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.0-alpha
- Python version: 3.6.8
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

You can collect some of this information using our environment capture [script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with
python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"

**Describe the current behavior**
I follow the example [Classify structred data](https://www.tensorflow.org/alpha/tutorials/keras/feature_columns) as below:
```
feature_layer = SequenceFeatures(columns, name=INPUT_NAME)

model = keras.Sequential([
    feature_layer,
    keras.layers.LSTM(1, return_sequence=True),
    keras.layers.LSTM(1),
    keras.layers.Dense(1, activation='relu', name=OUTPUT_NAME)
])

model.compile(optimizer='adam', loss='mse')
model.fit(DATASET, epochs=5)
```
and it shows an error:
`ValueError: Passing a dictionary input to a Sequential Model which doesn't have FeatureLayer as the first layer is an error.`

However, I found the reason that `SequenceFeatures` doesn't have a property `is_feature_layer` as below:
```
## tensorflow/python/keras/engine/training_utils.py
# TODO(rohanj): This is a hack to get around not depending on feature_column and
# create a cyclical dependency. Figure out a cleaner solution
def is_feature_layer(layer):
  """Returns whether `layer` is a FeatureLayer or not."""
  return getattr(layer, '_is_feature_layer', False)

## tensorflow/python/feature_column/feature_column_v2.py
@keras_export('keras.layers.DenseFeatures')
class DenseFeatures(_BaseFeaturesLayer):
  def __init__(self, feature_columns, trainable=True, name=None, **kwargs):

    super(DenseFeatures, self).__init__(
        feature_columns=feature_columns,
        trainable=trainable,
        name=name,
        expected_column_type=DenseColumn,
        **kwargs)

  @property
  def _is_feature_layer(self):
    return True
   
  def _target_shape(self, input_shape, total_elements):
    return (input_shape[0], total_elements)
    ...

## tensorflow/python/feature_column/sequence_feature_column.py
@keras_export('keras.experimental.SequenceFeatures')
class SequenceFeatures(fc._BaseFeaturesLayer):
    def __init__(self, feature_columns, trainable=True, name=None, **kwargs):

    super(SequenceFeatures, self).__init__(
        feature_columns=feature_columns,
        trainable=trainable,
        name=name,
        expected_column_type=fc.SequenceDenseColumn,
        **kwargs)

  def _target_shape(self, input_shape, total_elements):
    return (input_shape[0], input_shape[1], total_elements)
   ...
```
I think it would be better to move the `_is_feature_layer` property to the`_BaseFeaturesLayer` for a while.
 
**Describe the expected behavior**

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by arthurarg** [comment]
Hi seungbaeji, I think sparse tensor input to keras models is not supported yet. This is needed in order for the SequenceFeatures layer to work. I think there is some work in progress to add this support, so that can be expected soon. Once this is done, yes adding the `_is_feature_layer` property as you suggested should allow to use SequenceFeatures with such models.

**Comment by arthurarg** [comment]
There might be a work around if you use categorical columns:
I think that sequence categorical columns can handle dense tensors, but you have to be cautious about the way the sequence length is handled in that case.
A and with a subclassed keras model, you can use the SequenceFeatures layer without running into the `_is_feature_layer ` error that you described.
That should not work with `sequence_numeric_column` though.

**Comment by rmothukuru** [comment]
@seungbaeji,
The Tutorial, [Classify structured data with feature columns](https://www.tensorflow.org/tutorials/structured_data/feature_columns) can be executed without any error. Please find [the Gist](https://colab.research.google.com/github/tensorflow/docs/blob/master/site/en/tutorials/structured_data/feature_columns.ipynb) of the working code. Thanks!
