### ISSUE TITLE
C++ compilation of rule '@highwayhash//:sip_hash' failed (Tensorflow serving on Android)

### ISSUE THREAD

**Issue by M1ch13l** [tensorflow/tensorflow#2753]
Operating System: Ubuntu 16 64bit

Installed:
Android NDK (r10e / r11c), 
Android SDK (Latest), 
Tensorflow (Latest), 
Tensorflow serving (Latest), 
Bazel (0.2.1 / 0.2.3)

I can build android projects (SDK and NDK) with bazel, build Tensorflow with bazel and build android jni projects with bazel. 

This is the Error I get when trying to build an android project which uses tensorflow serving: ($ bazel build //MouthDetection:android).

`ERROR: /home/michiel/.cache/bazel/_bazel_michiel/224c8e6cc63c3cf5a14b148ed24603d7/external/highwayhash/BUILD:17:1: C++ compilation of rule '@highwayhash//:sip_hash' failed: arm-linux-androideabi-gcc failed: error executing command external/androidndk/ndk/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-gcc -fstack-protector-strong -fpic -ffunction-sections -funwind-tables ... (remaining 38 argument(s) skipped): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
In file included from external/highwayhash/highwayhash/sip_hash.h:23:0,
                 from external/highwayhash/highwayhash/sip_hash.cc:15:
external/highwayhash/highwayhash/state_helpers.h: In function 'void highwayhash::UpdateState(const char*, highwayhash::uint64, State*)':
external/highwayhash/highwayhash/state_helpers.h:36:76: error: there are no arguments to 'static_assert' that depend on a template parameter, so a declaration of 'static_assert' must be available [-fpermissive]
   static_assert((kPacketSize & (kPacketSize - 1)) == 0, "Size must be 2^i.");
                                                                            ^
external/highwayhash/highwayhash/state_helpers.h:36:76: note: (if you use '-fpermissive', G++ will accept your code, but allowing the use of an undeclared name is deprecated)
In file included from external/highwayhash/highwayhash/sip_hash.cc:15:0:
external/highwayhash/highwayhash/sip_hash.h: At global scope:
external/highwayhash/highwayhash/sip_hash.h:31:9: error: expected nested-name-specifier before 'Key'
   using Key = uint64[2];
         ^
external/highwayhash/highwayhash/sip_hash.h:34:38: error: 'Key' does not name a type
   explicit INLINE SipHashState(const Key& key) {
                                      ^
external/highwayhash/highwayhash/sip_hash.h: In constructor 'highwayhash::SipHashState::SipHashState(const int&)':
external/highwayhash/highwayhash/sip_hash.h:35:39: error: invalid types 'const int[int]' for array subscript
     v0 = 0x736f6d6570736575ull ^ key[0];
                                       ^
external/highwayhash/highwayhash/sip_hash.h:36:39: error: invalid types 'const int[int]' for array subscript
     v1 = 0x646f72616e646f6dull ^ key[1];
                                       ^
external/highwayhash/highwayhash/sip_hash.h:37:39: error: invalid types 'const int[int]' for array subscript
     v2 = 0x6c7967656e657261ull ^ key[0];
                                       ^
external/highwayhash/highwayhash/sip_hash.h:38:39: error: invalid types 'const int[int]' for array subscript
     v3 = 0x7465646279746573ull ^ key[1];
                                       ^
external/highwayhash/highwayhash/sip_hash.h: At global scope:
external/highwayhash/highwayhash/sip_hash.h:114:50: error: 'Key' in 'class highwayhash::SipHashState' does not name a type
 static INLINE uint64 SipHash(const SipHashState::Key& key, const char* bytes,
                                                  ^
external/highwayhash/highwayhash/sip_hash.h: In function 'highwayhash::uint64 highwayhash::SipHash(const int&, const char*, highwayhash::uint64)':
external/highwayhash/highwayhash/sip_hash.h:116:52: error: no matching function for call to 'ComputeHash(const int&, const char*&, const uint64&)'
   return ComputeHash<SipHashState>(key, bytes, size);
                                                    ^
external/highwayhash/highwayhash/sip_hash.h:116:52: note: candidate is:
In file included from external/highwayhash/highwayhash/sip_hash.h:23:0,
                 from external/highwayhash/highwayhash/sip_hash.cc:15:
external/highwayhash/highwayhash/state_helpers.h:63:8: note: template<class State> highwayhash::uint64 highwayhash::ComputeHash(const typename State::Key&, const char*, highwayhash::uint64)
 uint64 ComputeHash(const typename State::Key& key, const char* bytes,
        ^
external/highwayhash/highwayhash/state_helpers.h:63:8: note:   template argument deduction/substitution failed:
external/highwayhash/highwayhash/state_helpers.h: In substitution of 'template<class State> highwayhash::uint64 highwayhash::ComputeHash(const typename State::Key&, const char*, highwayhash::uint64) [with State = highwayhash::SipHashState]':
external/highwayhash/highwayhash/sip_hash.h:116:52:   required from here
external/highwayhash/highwayhash/state_helpers.h:63:8: error: no type named 'Key' in 'class highwayhash::SipHashState'
In file included from external/highwayhash/highwayhash/sip_hash.cc:15:0:
external/highwayhash/highwayhash/sip_hash.h: At global scope:
external/highwayhash/highwayhash/sip_hash.h:120:60: error: 'Key' in 'class highwayhash::SipHashState' does not name a type
 static INLINE uint64 ReduceSipTreeHash(const SipHashState::Key& key,
                                                            ^
Target //MouthDetection:android failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 32.618s, Critical Path: 18.78s
`

Does anyone know a solution to this problem

**Comment by andrewharp** [comment]
Are you trying to run a Tensorflow server on Android? Currently we only support the named Android libraries such as //tensorflow/core:android_tensorflow_lib -- it's not expected that others will compile for Android.

Also, as a note, Bazel 0.2.3 and below do not support Android NDK11. The next release of Bazel should, though.

**Comment by aselle** [comment]
Automatically closing due to lack of recent activity. Please reopen when further information becomes available.

**Comment by perone** [comment]
Operating System: Ubuntu 14.04 LTS 64bit

Installed:
Android NDK (r12b), 
Android SDK (Latest), 
Tensorflow (0.9), 
Bazel (0.3.0)

I faced the same problem, then I changed to use "//tensorflow/core:android_tensorflow_lib", now the error is:
```
external/eigen_archive/eigen-eigen-d02e6a705c30/unsupported/Eigen/CXX11/../../../Eigen/src/Core/arch/CUDA/TypeCasting.h: In function 'TgtPacket Eigen::internal::pcast(const SrcPacket&) [with SrcPacket = Eigen::internal::Packet4h; TgtPacket = __vector(4) float]':
external/eigen_archive/eigen-eigen-d02e6a705c30/unsupported/Eigen/CXX11/../../../Eigen/src/Core/arch/CUDA/TypeCasting.h:143:38: error: '_mm_cvtm64_si64' was not declared in this scope
   __int64_t a64 = _mm_cvtm64_si64(a.x);
                                      ^
Target //tensorflow/maneaflow:maneaflow failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 174.487s, Critical Path: 168.61s
```

I'm building with the following command:

`bazel build :mydemo --crosstool_top=//external:android/crosstool --cpu=x86 --host_crosstool_top=@bazel_tools//tools/cpp:toolchain`

And with the following BUILD file:

```
cc_binary(
    name = "mydemo",
    srcs = ["mydemo.cc"],
    deps = [
        "//tensorflow/core:android_tensorflow_lib",
    ]
)
```

I'm just trying to build a very simple C++ TensorFlow example for Android x86.
