### ISSUE TITLE
What's the license of pre-trained TensorFlow.js models?

### ISSUE THREAD

**Issue by philipphenkel** [tensorflow/tensorflow#27534]
I want to use tfjs-models in a commercial application. While source code in the [tfjs-models repository](https://github.com/tensorflow/tfjs-models) is licensed under Apache 2.0, I did not find any info about the license of the models hosted on storage.googleapis.com.

For example [body-pix](https://github.com/tensorflow/tfjs-models/tree/master/body-pix) is loading its model from [storage.googleapis.com/tfjs-models](https://storage.googleapis.com/tfjs-models)
e.g.
[posenet_mobilenet_025_partmap/model.json](https://storage.googleapis.com/tfjs-models/savedmodel/posenet_mobilenet_025_partmap/model.json)
[posenet_mobilenet_025_partmap/tensorflowjs_model.p](https://storage.googleapis.com/tfjs-models/savedmodel/posenet_mobilenet_025_partmap/tensorflowjs_model.pb)
[posenet_mobilenet_025_partmap/weights_manifest.json](https://storage.googleapis.com/tfjs-models/savedmodel/posenet_mobilenet_025_partmap/weights_manifest.json)

Are the files on [storage.googleapis.com/tfjs-models](https://storage.googleapis.com/tfjs-models) licensed under Apache 2.0 as well?

If yes, it would be great to document it, and I'm willing to submit a PR.

**Comment by dynamicwebpaige** [comment]
The [Apache 2.0 license](https://github.com/tensorflow/tfjs-models/blob/master/LICENSE) has been added to the TensorFlow.js models repo. Am closing this issue; thank you for the request!
