### ISSUE TITLE
ValueError: Input 0 of layer dense is incompatible with the layer: its rank is undefined, but the layer requires a defined rank on Colab script downloaded to local machine

### ISSUE THREAD

**Issue by serv-inc** [tensorflow/tensorflow#27539]
As a companion issue to #27538 with tensorflow 2.0.0a. Script fails with

> ValueError: Input 0 of layer dense is incompatible with the layer: its rank is undefined, but the layer requires a defined rank.

in the line

```  layers.Dense(image_data.num_classes, activation='softmax')```
**System information**
- TensorFlow version:
> ('v1.12.0-9492-g2c319fb415', '2.0.0-alpha0')

using an updated script

```python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"
```

which also works for tensorflow 1.
- Doc Link: https://www.tensorflow.org/tutorials/images/hub_with_keras

**Describe the documentation issue**
The downloaded .py script (see #27538) fails to run (it's not clear-cut if this is a documentation issue or simply a bug) at
```
model = tf.keras.Sequential([
  feature_extractor_layer,
  layers.Dense(image_data.num_classes, activation='softmax')
])
```

**We welcome contributions by users. Will you be able to update submit a PR (use the [doc style guide](https://www.tensorflow.org/community/documentation)) to fix the doc Issue?**
If it's a doc issue, I'd love to. It could go deeper than that. The same issue appears for the MCVE at stackoverflow: https://stackoverflow.com/questions/55490885/error-converting-keras-model-to-tfjs-duplicate-weight-name-variable

**Comment by serv-inc** [comment]
@arnoegw solved this on stackoverflow:

> Does it help to replace tensorflow=2.0.0-alpha0 with tf-nightly-2.0-preview

So just `pip install tf-nightly-2.0-preview` and it works.

**Comment by abbazs** [comment]
> @arnoegw solved this on stackoverflow:
> 
> > Does it help to replace tensorflow=2.0.0-alpha0 with tf-nightly-2.0-preview
> 
> So just `pip install tf-nightly-2.0-preview` and it works.

This doesn't work in Windows 10 as the windows builds are not available.

**Comment by serv-inc** [comment]
Reopened for @abbazs.

**Comment by serv-inc** [comment]
Reopened for @abbazs.

**Comment by jasonzhang2022** [comment]
tf-nightly-2.0-preview works in Linux

**Comment by serv-inc** [comment]
@jasonzhang2022 : yes, like a charm. It also works on Mac OS X. There is no nightly version for windows, though. (this should be closed, as a windows nightly build is arguably a feature request)
