### ISSUE TITLE
[TF==2.0.0-alpha0] tf.keras.Model reinitializes set weights. 

### ISSUE THREAD

**Issue by mauricelucy** [tensorflow/tensorflow#27541]
### System information
- Have I written custom code: **Yes**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): **Linux Ubuntu 16.04**
- TensorFlow installed from (source or binary): **pip install tensorflow==2.0.0-alpha0**
- TensorFlow version (use command below): **2.0.0-alpha0**
- Python version: **3.7.1**
- **Using only CPU**

### Describe the current behavior
When I initialize a convolution layer with some weights, instead of the weights being set, it will be randomly re-initialized. Print output returns at each run a different weight.

**Code to reproduce the issue**
```
import tensorflow.keras
import numpy as np

weight = np.ndarray(
    shape=[1, 1, 1, 1],
    dtype='float32')
weight[0, 0, 0, 0] = -0.8888
bias = np.ndarray(
    shape=[1],
    dtype='float32')
bias[0] = 0

weights = [weight, bias]

inputs = tensorflow.keras.layers.Input(shape=(1,1,1), name='inputs')
outputs = tensorflow.keras.layers.Conv2D(filters=1,
                                 kernel_size=1,
                                 strides=(1,1),
                                 kernel_regularizer=tensorflow.keras.regularizers.l2(0.0005),
                                 weights=weights,
                                 use_bias=True,
                                 activation=None,
                                 padding='same')(inputs)
model = tensorflow.keras.Model(inputs=inputs,
                              outputs=outputs)

for layer in model.layers:
    for weight in layer.get_weights():
        print(weight) # wrong output: [[[[1.6804]]]] [0.]
```

### Describe the expected behavior
with:
- keras version 2.1.5 
- using tensorflow backend version 1.6.0

When I initialize a convolution layer with some weights, the weights will be set and stick. Print output returns as expected: [[[[-0.8888]]]] [0.]

This is an useful feature, especially when one is converting from one model format to another. For example when converting darknet (model.cfg, model.weights) to keras (model.h5). 

**Code to reproduce**
```
import keras
import numpy as np

weight = np.ndarray(
    shape=[1, 1, 1, 1],
    dtype='float32')
weight[0, 0, 0, 0] = -0.8888
bias = np.ndarray(
    shape=[1],
    dtype='float32')
bias[0] = 0
weights = [weight, bias]
inputs = keras.layers.Input(shape=(1,1,1), name='inputs')
outputs = keras.layers.Conv2D(filters=1,
                                 kernel_size=1,
                                 strides=(1,1),
                                 kernel_regularizer=keras.regularizers.l2(0.0005),
                                 weights=weights,
                                 use_bias=True,
                                 activation=None,
                                 padding='same')(inputs)
model = keras.Model(inputs=inputs,
                              outputs=outputs)

for layer in model.layers:
    for weight in layer.get_weights():
        print(weight)  # correct output: [[[[-0.8888]]]] [0.]
```

### Questions:
 Is this intended? Or how can this be disabled? How can I help you solve this issue. Thanks for taking your time looking into this.

**Comment by jvishnuvardhan** [comment]
@mauricelucy I am closing this as it was resolved in `tf-nightly-gpu-2.0-preview==2.0.0.dev20190723`. Please check the [gist here](https://colab.sandbox.google.com/gist/jvishnuvardhan/2df53e68f336fa3e02524632e7612bbf/tf_27541.ipynb). Please feel free to open if the issue persisits. Thanks!
