### ISSUE TITLE
Add Tensorflow.Distributions to 2.0

### ISSUE THREAD

**Issue by dorian821** [tensorflow/tensorflow#27547]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using): tf_nightly_gpu_2.0_preview-2.0.0.dev20190327-cp36-cp36m-win_amd64
- Are you willing to contribute it (Yes/No): No

**Describe the feature and the current behavior/state.**

Will tensorflow.distributions be added to 2.0? Currently, TFP doesn't work with 2.0 due to its absence.

Thanks!

**Will this change the current api? How?**

No

**Who will benefit with this feature?**

Users of Tensorflow Probability

**Any Other info.**

**Comment by henrysky** [comment]
``tfp-nightly`` should works fine with Tensorflow 2.0, at least for my package CI test cases.

**Comment by armando-fandango** [comment]
distributions is part of tfp : https://www.tensorflow.org/probability/api_docs/python/tfp/distributions

**Comment by dorian821** [comment]
@armando-fandango intuitively, this is what I would expect, but I get this error. and if you open up the actual distribution modules in tfp, you'll see that they import from tf

```
In [1]: import tensorflow_probability
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-1-03228327e8d6> in <module>()
----> 1 import tensorflow_probability

C:\Users\asus\Anaconda3\lib\site-packages\tensorflow_probability\__init__.py in <module>()
     19
     20 # from tensorflow_probability.google import staging  # DisableOnExport
---> 21 from tensorflow_probability.python import *  # pylint: disable=wildcard-import
     22 from tensorflow_probability.python.version import __version__

C:\Users\asus\Anaconda3\lib\site-packages\tensorflow_probability\python\__init__.py in <module>()
     20
     21 from tensorflow_probability.python import bijectors
---> 22 from tensorflow_probability.python import distributions
     23 from tensorflow_probability.python import edward2
     24 from tensorflow_probability.python import glm

C:\Users\asus\Anaconda3\lib\site-packages\tensorflow_probability\python\distributions\__init__.py in <module>()
     20 # pylint: disable=unused-import,line-too-long,g-importing-member
     21
---> 22 from tensorflow_probability.python.distributions.autoregressive import Autoregressive
     23 from tensorflow_probability.python.distributions.batch_reshape import BatchReshape
     24 from tensorflow_probability.python.distributions.binomial import Binomial

C:\Users\asus\Anaconda3\lib\site-packages\tensorflow_probability\python\distributions\autoregressive.py in <module>()
     24
     25
---> 26 class Autoregressive(tf.distributions.Distribution):
     27   """Autoregressive distributions.
     28

AttributeError: module 'tensorflow' has no attribute 'distributions'

In [2]:
```

@henrysky, thanks, I'll give it a try.

**Comment by dynamicwebpaige** [comment]
@dorian821 You might need to install `tfp-nightly`, if you had a previous version of TensorFlow Probability (i.e., not compliant with TF 2.0). Let us know if you run into any snags! 🙂

**Comment by dorian821** [comment]
@dynamicwebpaige thanks! I've installed it and it's working fine. I've noticed that tfp-nightly-gpu however is still missing a lot of the layers and distributions present in tfp-nightly. Is the gpu distribution likely to be updated soon?

**Comment by henrysky** [comment]
I think they abandoned the tfp-gpu since tfp is completely based on tf now. So tfp-gpu is not neccessary anymore

**Comment by dorian821** [comment]
ah ok, great. thanks for clarifying.
