### ISSUE TITLE
tf.contrib.labeled_tensor incorrectly handling or failing with None dimensions

### ISSUE THREAD

**Issue by lw394** [tensorflow/tensorflow#27548]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution : macOS Sierra
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 1.12
- Python version: 2.7

**labeled_tensor.mul fails with None dimensions when tf.multiply doesn't.**

ipdb> X

<LabeledTensor 'X:0' shape=(1, 1, 2, 12, 1, 300) dtype=float32
 axes=[('a', Dimension(1)),
       ('b', Dimension(1)),
       ('c', Dimension(2)),
       ('d', Dimension(12)),
       ('e', Dimension(1)),
       ('f', Dimension(200))]>

ipdb> Y

<LabeledTensor 'Y:0' shape=(?, 6, 1, 1, 200, 300) dtype=float32
 axes=[('a', Dimension(None)),
       ('b', Dimension(6)),
       ('c', Dimension(1)),
       ('d', Dimension(1)),
       ('e', Dimension(200)),
       ('f', Dimension(300))]>

ipdb> X*Y

*** ValueError: Mismatched 'a' axis on input tensors: Axis('a', Dimension(1)) and Axis('a', Dimension(None))

ipdb> lt.mul(X,Y)

*** ValueError: Mismatched 'a' axis on input tensors: Axis('a', Dimension(1)) and Axis('a', Dimension(None))

ipdb> tf.multiply(X,Y)

<tf.Tensor  'Mul_2:0' shape=(?, 6, 2, 12, 200, 300) dtype=float32>

**Comment by dynamicwebpaige** [comment]
@lw394 Thanks for the question! Endpoints housed in `tf.contrib.*` are unsupported, with volatile functionality, and [`tf.contrib.labeled_tensor`](https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md#list-of-projects) will be deprecated in TensorFlow 2.0. 

`lt.mul`, `*`, and `tf.multiply` have slightly different functionality (for example, the latter supports broadcasting).

**Comment by lw394** [comment]
Thanks for the reply!  Will there something serving this purpose in 2.0?

**Comment by jvishnuvardhan** [comment]
I think it was resolved. I am closing the issue. But, please let me know if I'm mistaken.
