### ISSUE TITLE
iOS example running bug

### ISSUE THREAD

**Issue by maelp** [tensorflow/tensorflow#2754]
### Environment info
Operating System: iOS

### Steps to reproduce
1. Follow the contrib/makefile/README to install the tensorflow iOS core lib
2. Download the graph .pb files and copy them in the .xcodeproj
3. Run the example, an error is logged

### Logs or other output that would be helpful

```
Running model failed:Invalid argument: No OpKernel was registered to support Op 'DecodeJpeg' with these attrs
	[[Node: DecodeJpeg = DecodeJpeg[acceptable_fraction=1, channels=3, fancy_upscaling=true, ratio=1, try_recover_truncated=false](DecodeJpeg/contents)]]
```

Is there a modification to do to the building of the lib to include jpeg ops?

Other notes:

 - the version of Eigen downloaded in the `Makefile` is not the same as the one configured in the `.xcodeproj` (the include path uses another version hash), I kept the one from the `Makefile`
 - after downloading <http://download.tensorflow.org/models/image/imagenet/inception-2015-12-05.tgz> as indicated in the `README`, the `.pb` and `.txt` files don't have the same names as the ones in the iOS examples, I renamed them, although I'm not sure if the examples refer to the same model

Those last issues seem fixed by <https://github.com/tensorflow/tensorflow/commit/a9d1af0cf55a28e46b0527dc927e249eafea4418#diff-05f2ac6ab411cf0c1e4ad1d7b96caf22R45>

**Comment by maelp** [comment]
Might be related to bug <https://github.com/tensorflow/tensorflow/issues/2570>

**Comment by maelp** [comment]
I'm trying the following:

 - removing the `decode_jpeg` kernel from excluded list in Android (if for some reason we use the same kernels when building on iOS)
 - adding `tensorflow/core/kernels/decode_jpeg_op.cc` to `tf_cc_files.txt`

**Comment by StephenOman** [comment]
Can you try the model located here:
[https://storage.googleapis.com/download.tensorflow.org/models/inception5h.zip](url)

This is the one that is referenced in the Android example documentation and is working for me on iOS.

Re: Eigen. The hash was updated a few days ago. Are you running from the latest version?

**Comment by maelp** [comment]
The new file contains the proper model (although your link seems to be formatted weirdly, the `href` is not the same as the text of the link)

I still can't build the lib with the DecodeJPEG op for some reason, did you change something to the build file when you built it ?

Thanks for Eigen -- so I should update the hash in the Makefile, can you tell which one you are using?

**Comment by StephenOman** [comment]
I've fixed my comment so the URL to the model is correct. Thanks for flagging that.

I didn't have to change either the Eigen hash or the build file. I simply checked out the code (master branch) two days ago and ran the build scripts, before opening the xcode project.

**Comment by maelp** [comment]
Also jpeg files seem to be explicitly removed in `gen_file_lists`

<https://github.com/tensorflow/tensorflow/blob/3c5233d54d3dc431bdee2a5756cc2f1f9b270503/tensorflow/contrib/makefile/gen_file_lists.sh#L22>

**Comment by maelp** [comment]
@StephenOman did you manage to run and test the model? The app builds fine, but then it crashes at runtime

**Comment by StephenOman** [comment]
Yes, have it running and working on my iPhone.

**Comment by StephenOman** [comment]
Did you try deploying on a device with the newer model?

**Comment by maelp** [comment]
Not yet, I'm rebuilding the lib, but I will test it with the new model
