### ISSUE TITLE
tf.keras lambda layer with sparse tensor caused AttributeError: 'SparseTensor' object has no attribute 'tocoo'

### ISSUE THREAD

**Issue by jianlingzhong** [tensorflow/tensorflow#27557]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Mac OSX 10.14
- TensorFlow installed from (source or binary): pip install
- TensorFlow version (use command below): 1.13
- Python version: 3.6

**Describe the current behavior**
sparse tensor operation inside a custom keras layer should not affect outside behavior if returning the expected type

**Describe the expected behavior**
`AttributeError: 'SparseTensor' object has no attribute 'tocoo'`

**Code to reproduce the issue**
```python

import tensorflow as tf
import scipy.sparse
import numpy as np

def input_fn():

    x = scipy.sparse.random(1, 400)
    y = scipy.random.randint(2, size=(1,1))

    indices = np.mat([x.row, x.col]).transpose()
    sp = tf.sparse.SparseTensor(indices, x.data, x.shape)
    d = tf.data.Dataset.from_tensors((sp,y))
    return d

input_layer = tf.keras.layers.Input(shape=(400, ), sparse=True)
weights = tf.get_variable(name='weights', shape=(400, 1))

weights_mult = lambda x: tf.sparse_tensor_dense_matmul(x, weights)
output_layer=  tf.keras.layers.Lambda(weights_mult)(input_layer)
model = tf.keras.Model([input_layer], output_layer)
model.compile(loss='binary_crossentropy', optimizer='sgd', metrics=['accuracy'])
d = input_fn()
model.fit(d.make_one_shot_iterator(), epochs=3, steps_per_epoch=1)
```

**Other info / logs**
```
Epoch 1/3
Traceback (most recent call last):
  File "sparse.py", line 24, in <module>
    model.fit(d.make_one_shot_iterator(), epochs=3, steps_per_epoch=1)
  File "/Users/jz/coding/t1/lib/python3.6/site-packages/tensorflow/python/keras/engine/training.py", line 880, in fit
    validation_steps=validation_steps)
  File "/Users/jz/coding/t1/lib/python3.6/site-packages/tensorflow/python/keras/engine/training_arrays.py", line 266, in model_iteration
    batch_outs = f(actual_inputs)
  File "/Users/jz/coding/t1/lib/python3.6/site-packages/tensorflow/python/keras/backend.py", line 3046, in __call__
    sparse_coo = value.tocoo()
AttributeError: 'SparseTensor' object has no attribute 'tocoo'
```

**Comment by SharoneDayan** [comment]
I have the same issue. Any updates?

**Comment by williamwisdom** [comment]
Looks like tf.keras expects you to be passing a scipy sparse matrix if your input is a sparse tensor

```    for tensor, value in zip(self.inputs, inputs):
      ...
      if is_sparse(tensor):
        sparse_coo = value.tocoo()```

**Comment by OmnesRes** [comment]
I ended up using the fact that you can assign an input to a tensor:
`sparse_tensor=tf.SparseTensor(np.stack(sparse.nonzero(), axis=1), sparse.data, sparse.shape)
input=tf.keras.layers.Input(shape=(None,), tensor=sparse_tensor, dtype=tf.float32)`

(sparse is a scipy csr sparse matrix)

**Comment by ArthurWang10086** [comment]
same question too.

**Comment by SharoneDayan** [comment]
Maybe the article I wrote can help ? https://medium.com/dailymotion/how-to-design-deep-learning-models-with-sparse-inputs-in-tensorflow-keras-fd5e754abec1
I implemented a custom Dense layer that ingests both sparse and dense tensors, and used subclassing in keras to train a model

**Comment by tongtong1990** [comment]
For those who is trying to find the solution for the same issue: This is a bug on TF 1.13 and 1.14, which gets resolved on 1.15.

Example code can be found here with 1.15:

https://github.com/tensorflow/tensorflow/issues/31819

**Comment by rmothukuru** [comment]
@jianlingzhong,
Your code runs now without error. Please find [the Gist](https://colab.research.google.com/gist/rmothukuru/d7a7eaa328652f16b477eab176042890/gh_27557.ipynb) of the working code. Thanks!

**Comment by kitbransby** [comment]
Upgrading from tf 1.14 to 1.15 fixed this for me. thank you !
