### ISSUE TITLE
Poincare hyperbolic embeddings support

### ISSUE THREAD

**Issue by vitalyli** [tensorflow/tensorflow#27559]
As you might have seen Facebook released hyperbolic embeddings training; 
Is there any plan to support those in Tensorflow?

https://github.com/facebookresearch/poincare-embeddings

**Comment by bellettif** [comment]
Hi, I'd be happy to undertake this if this is still of interest to you. I have written a prototype in tensorflow some time ago.

**Comment by vitalyli** [comment]
yes that would be great.

**Comment by bellettif** [comment]
Alright, sounds good.

**Comment by CrickWu** [comment]
Working on this with @bellettif .

**Comment by tilakrayal** [comment]
@vitalyli,
Have you got the chance to have a look at this official document for the api `PoincareNormalize` where it projects into the **Poincare** ball with **norm <= 1.0 - epsilon** from the tensorflow addons.

https://www.tensorflow.org/addons/api_docs/python/tfa/layers/PoincareNormalize

Thank you!

**Comment by tilakrayal** [comment]
Closing this as stale. Please reopen if this is still a valid request. Thank you!
