### ISSUE TITLE
GcsFilesystem not able to set dns cache when using long constructor

### ISSUE THREAD

**Issue by ziliangpeng** [tensorflow/tensorflow#27552]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using): 2.0.0-alpla0
- Are you willing to contribute it (Yes/No): Yes

**Describe the feature and the current behavior/state.**

The GcsFileSystem has a default constructor and a long constructor. While the default constructor initialize variables either to default option or from environment variables, the long constructor initialize a few variables that's passed in from constructor parameters, but left out the others (e.g. dns cache).

**Will this change the current api? How?**

No. We can still initialize the other things from environment variables.

**Who will benefit with this feature?**

anyone who uses GcsFileSystem can have more options configuring the filesystem while using the long constructor.

**Any Other info.**

**Comment by ziliangpeng** [comment]
If this looks good I can submit a PR.

**Comment by ziliangpeng** [comment]
@saeta What's your thought as the dns cache author? 🙂

**Comment by saeta** [comment]
Hi @ziliangpeng ! Thanks for reaching out. I think this would be great to fix. (Out of curiosity, do you have an alternate DNS cache implementation in mind, or some other use case?)

**Comment by ziliangpeng** [comment]
@saeta Hey, thanks for the response! 

Taking a deeper look into the code, it looks like the DNS cache can be bake into the http connection factory, which is part of the long constructor's parameter, so I think there is a way to do DNS caching without modifying the constructor (tho not sure if this is the recommended way).

Don't have an alternate impl in head, but even if there is another impl, it looks like it can be baked into the connection factory too.

**Comment by saeta** [comment]
Closing this out, as it appears to not be making progress. If someone is interested in pushing this along, please do feel free. Thanks! -Brennan
