### ISSUE TITLE
Caused by: java.lang.IllegalArgumentException: ByteBuffer is not a valid flatbuffer model

### ISSUE THREAD

**Issue by PikkaPikkachu** [tensorflow/tensorflow#27560]
Hi,
I am training a model for image classification in TensorFlow using pre-trained model of MobileNet and embedding the .tflite file in Android app. 

It so happens that if I do `model.add(layers.Flatten())` after adding the MobileNet model, I get the following error, when executing the Android app:
`Caused by: java.lang.IllegalArgumentException: ByteBuffer is not a valid flatbuffer model`

However, if I use `model.add(layers.GlobalAveragePooling2D())` after the MobileNet model, the app works normally. 

Could someone please help me as to why the `layers.Flatten()` is causing trouble?

Complete code is available [here](https://github.com/PikkaPikkachu/train-em-all/). 
Thanks!

**Comment by jvishnuvardhan** [comment]
This is not Build/Installation or Bug/Performance issue. Please post this kind of support questions at [Stackoverflow](https://stackoverflow.com/questions/tagged/tensorflow). There is a big community to support and learn from your questions. GitHub is mainly for addressing bugs in installation and performance. Thanks!

**Comment by PikkaPikkachu** [comment]
@jvishnuvardhan thanks! Have opened the question [here](https://stackoverflow.com/questions/55948770/why-does-using-layers-flatten-in-cnn-model-cause-the-error-in-android-when-i-a) for anyone else having the same query.
