### ISSUE TITLE
State build requires bazel <=0.23.0 for v2.0.0-alpha0

### ISSUE THREAD

**Issue by biltongza** [tensorflow/tensorflow#27575]
<em>Please make sure that this is a documentation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:doc_template</em>

**System information**
- TensorFlow version: v2.0.0-alpha0
- Doc Link: https://www.tensorflow.org/install/source_windows#install_bazel

**Describe the documentation issue**
I downloaded the latest (at the time of writing, 0.24.1) Bazel binary and when I tried to `./configure.py` I got this: 
```
You have bazel 0.24.1 installed.
Please downgrade your bazel installation to version 0.23.0 or lower to build TensorFlow! To downgrade: download the installer for the old version (from https://github.com/bazelbuild/bazel/releases) then run the installer.
```
I think it would be useful to state explicitly that 0.23.0 is the version required to build Tensorflow to save some time. I even just downloaded 0.23.2 because I didn't see that the message says 0.23.0 and sure enough, I got the same complaint about 0.23.2.

**We welcome contributions by users. Will you be able to update submit a PR (use the [doc style guide](https://www.tensorflow.org/community/documentation)) to fix the doc Issue?**

Yes. Will do a PR shortly.

**Comment by biltongza** [comment]
PR https://github.com/tensorflow/docs/pull/465

**Comment by ymodak** [comment]
PR has been merged. Closing this issue. Thanks!
