### ISSUE TITLE
No simple function optimisation examples for tensorflow 2.0?

### ISSUE THREAD

**Issue by cottrell** [tensorflow/tensorflow#27584]
I don't see any simple function optimisation example for tensorflow 2.0.

Something like log(x) ** 2 could be good.

**Comment by jvishnuvardhan** [comment]
@cottrell Currently there are several [tutorials](https://www.tensorflow.org/alpha) covering major concepts of TF broadly. In future, more tutorials will be added. Please stay tuned. I am closing the issue. Thanks!
