### ISSUE TITLE
RaggedTensor casting bug

### ISSUE THREAD

**Issue by ARozental** [tensorflow/tensorflow#27598]
version 2.0.0-alpha.
Nested RaggedTensor are cast to int64 without apparent reason:

with regular tensors (ok):
```
>>> tf.constant([[1]], dtype=tf.int8)
<tf.Tensor: id=98, shape=(1, 1), dtype=int8, numpy=array([[1]], dtype=int8)>
```
with nested RaggedTensor (not ok):
```
>>> tf.ragged.constant([[1]], dtype=tf.int8)
tf.RaggedTensor(values=tf.Tensor([1], shape=(1,), dtype=int8), row_splits=tf.Tensor([0 1], shape=(2,), dtype=int64))
```

Also they can not be used to create generators even with dtype=int64. The following code leads to:

> The expected type was int64, but the yielded element was <tf.RaggedTensor [[6]]>.

```

class LineGenerator(object):
  def get_next_line(self):
    while True:
      out = [[6]]
      yield tf.ragged.constant(out, dtype=tf.int64)

class Dataset(object):
  def __init__(self, generator=LineGenerator()):
    self.next_element = self.build_iterator(generator)

  def build_iterator(self, gen: LineGenerator):
    dataset = tf.data.Dataset.from_generator(gen.get_next_line,output_types = tf.int64)
    #some other code...
```

**Comment by captain-pool** [comment]
the data generated from `tf.data.from_generator` is type casted into desired type, by converting it into numpy array

https://github.com/tensorflow/tensorflow/blob/20bbe5a17eeda011c4de74aa48d59ff4fc2f2090/tensorflow/python/data/ops/dataset_ops.py#L456-L457

https://github.com/tensorflow/tensorflow/blob/20bbe5a17eeda011c4de74aa48d59ff4fc2f2090/tensorflow/python/ops/script_ops.py#L167

However, as for numpy it **doesn't allow** variable length Sequences and Raises a `ValueError` when the cast is being performed.
[https://stackoverflow.com/a/4675383/9947584](https://stackoverflow.com/a/4675383/9947584)
So, for that reason, the following error is raised.
An Alternative approach for your issue will be using SparseTensors. Please take a look into it.

**Comment by captain-pool** [comment]
On a Second thought,
This issue can be solved by modifying the from_generator() function.
@dynamicwebpaige  @alextp can I work on it?

**Comment by ARozental** [comment]
Thanks, the above solution avoids the conversion bug though it seems there is another issue with building a generator of RuggedTensors

> tensorflow/core/framework/op_kernel.cc:1419] Unimplemented: Unsupported object type RaggedTensor

stack trace:

>   File "/Users/alonrozental/IdeaProjects/AGENT/create_pretraining_data.py", line 92, in <module>
> 2019-04-07 16:39:02.397857: W tensorflow/core/framework/op_kernel.cc:1419] Unimplemented: Unsupported object type RaggedTensor
>     tf.compat.v1.app.run()
>   File "/Users/alonrozental/.pyenv/versions/3.6.5/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 40, in run
> 2019-04-07 16:39:02.398489: W tensorflow/core/framework/op_kernel.cc:1419] Unimplemented: Unsupported object type RaggedTensor
>     _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
>   File "/Users/alonrozental/.pyenv/versions/3.6.5/lib/python3.6/site-packages/absl/app.py", line 300, in run
>     _run_main(main, args)
>   File "/Users/alonrozental/.pyenv/versions/3.6.5/lib/python3.6/site-packages/absl/app.py", line 251, in _run_main
>     sys.exit(main(argv))
>   File "/Users/alonrozental/IdeaProjects/AGENT/create_pretraining_data.py", line 79, in main
>     d = Dataset()
>   File "/Users/alonrozental/IdeaProjects/AGENT/create_pretraining_data.py", line 48, in __init__
>     self.next_element = self.build_iterator(generator)
>   File "/Users/alonrozental/IdeaProjects/AGENT/create_pretraining_data.py", line 60, in build_iterator
>     element = iter.get_next()
>   File "/Users/alonrozental/.pyenv/versions/3.6.5/lib/python3.6/site-packages/tensorflow/python/data/ops/iterator_ops.py", line 644, in get_next
>     return self._next_internal()
>   File "/Users/alonrozental/.pyenv/versions/3.6.5/lib/python3.6/site-packages/tensorflow/python/data/ops/iterator_ops.py", line 577, in _next_internal
>     output_shapes=self._flat_output_shapes)
>   File "/Users/alonrozental/.pyenv/versions/3.6.5/lib/python3.6/site-packages/tensorflow/python/ops/gen_dataset_ops.py", line 1954, in iterator_get_next_sync
>     _six.raise_from(_core._status_to_exception(e.code, message), None)
>   File "<string>", line 3, in raise_from
> tensorflow.python.framework.errors_impl.UnimplementedError: Unsupported object type RaggedTensor
> 	 [[{{node PyFunc}}]] [Op:IteratorGetNextSync]
> 2019-04-07 16:39:02.437561: W tensorflow/core/kernels/data/generator_dataset_op.cc:79] Error occurred when finalizing GeneratorDataset iterator: Failed precondition: Python interpreter state is not initialized. The process may be terminated.
> 	 [[{{node PyFunc}}]]

my code looks like this:

```
class Dataset(object):
  def __init__(self, generator=LineGenerator()):
    self.next_element = self.build_iterator(generator)

  def build_iterator(self, gen: LineGenerator):
    dataset = tf.data.Dataset.from_generator(gen.get_next_line,output_types = tf.int64) #the right way
    iter = dataset.make_one_shot_iterator()
    element = iter.get_next() #this line gives the error

    return element
d = Dataset()
```

**Comment by captain-pool** [comment]
I know. I'm not yet complete. I'm testing out various ways.
Will create a PR as soon as I'm done.

**Comment by captain-pool** [comment]
@ARozental You may now take a look. This is the fastest way to fix the bug. `gen_dataset_ops` creates Tensor out of the Data provided, and there's no support for RaggedTensors.

**Comment by ARozental** [comment]
@captain-pool This is what my second note was about. When I add these lines:
```
            if isinstance(ret, ragged_tensor.RaggedTensor):
              ret_arrays.append(math_ops.cast(ret, dtype))
              continue
```
It does solve the first bug:
> The expected type was int64, but the yielded element was <tf.RaggedTensor [[6]]>.


but then you get to the second one (which I could not see before):
> tensorflow/core/framework/op_kernel.cc:1419] Unimplemented: Unsupported object type RaggedTensor

I wasn't able to find out my self how deep this rabbit hole goes.

**Comment by captain-pool** [comment]
@ARozental what do you mean? Ia the new fix not working?
Please check PR: #27605
I typecasted the RaggedTensor into normal tensor. Because, I saw, there's no support for RaggedTensor by dataset on a C++ level.

**Comment by ARozental** [comment]
That is a problem...
my use case is the one from the TF documentation

https://www.tensorflow.org/guide/ragged_tensors
> Hierarchical inputs, such as text documents that are subdivided into sections, paragraphs, sentences, and words

Basically, I'm trying to encode entire books, but if every book has "max_number_of_capters", every chapter has "max_number_of_paragraphs" and every paragraph has "max_number_of_sentences" then I won't be able to fit even one book in my GPU memory :/

**Comment by captain-pool** [comment]
@ARozental you can read the tensors. And Remove the Paddings from the tensors as they arrive, to create RaggedTensors out of it. That can be a way to handle this.

**Comment by ARozental** [comment]
@captain-pool thanks. I'm trying something similar to make it work for now. Though creating padding just so that they can be removed is not very efficient as I need to create the RuggedTensor 1 element at a time from the non-padding tokens before I embed it in to vectors.

**Comment by alextp** [comment]
For the dataset & raggedtensor integration you should be able to return a raggedtensor from a dataset because dataset can under the hood destructure ragged tensors into their component tensors

**Comment by edloper** [comment]
A clarification for the initial bug description: there's no casting issue here, and the values are not being converted to int64.  The dtype=int64 that you see at the end of the following example applies only to the row_splits tensor, not to the overall ragged tensor:

```
>>> tf.ragged.constant([[1]], dtype=tf.int8)
tf.RaggedTensor(values=tf.Tensor([1], shape=(1,), dtype=int8), row_splits=tf.Tensor([0 1], shape=(2,), dtype=int64))
```

To be more explicit:

```
>>> rt = tf.ragged.constant([[1]], dtype=tf.int8)
>>> assert rt.dtype == tf.int8
>>> assert rt.values.dtype == tf.int8
>>> assert rt.row_splits.dtype == tf.int64
```

As subsequent comments in the bug deduced, the basic problem is that RaggedTensors are not fully supported by datasets yet.  We are actively working on adding this support, and expect it to be ready within the next few weeks.

**Comment by ARozental** [comment]
Thank you @edloper

**Comment by edloper** [comment]
tf.data support for RaggedTensors was added by 5fe90dc.

**Comment by bionicles** [comment]
@edloper how do you use this? especially with parse_sequence_example

**Comment by stekiri** [comment]
@edloper, even though the title of this issue wasn't really accurate, I have the feeling that the issue was not resolved when adding ragged tensor support to datasets.

Here a short snippet that reproduces the issue with `tf 2.2.0-rc3`:

```
import tensorflow as tf


def ragged_tensor_generator():
    while True:
        yield tf.ragged.constant([[1, 2], [1]], dtype=tf.int32)


ds = tf.data.Dataset.from_generator(
    generator=ragged_tensor_generator,
    output_types=tf.int32,
    output_shapes=(2, None))

iterator = iter(ds)
record = next(iterator)
```

As mentioned [earlier](https://github.com/tensorflow/tensorflow/issues/27598#issuecomment-480566659), the numpy conversion fails which produces the following error:

```
TypeError: `generator` yielded an element that could not be converted to the expected type. The expected type was int32, but the yielded element was <tf.RaggedTensor [[1, 2], [1]]>.
```

**Comment by edloper** [comment]
This is a bug with Dataset.from_generator.  #37400 is a PR to fix it, though I think it's been stalled for a little while on making sure it doesn't break a test.

**Comment by edloper** [comment]
@bionicles If you want to get ragged tensors from sequence examples, you can use [tf.io.RaggedFeature](https://www.tensorflow.org/api_docs/python/tf/io/RaggedFeature).  E.g.:

```
sequence_features = {'my_feature': tf.io.RaggedFeature(dtype=tf.int64)}
result = tf.io.parse_sequence_example(
    example_batch, sequence_features=sequence_features) 
```

**Comment by OOF-dura** [comment]
> @bionicles If you want to get ragged tensors from sequence examples, you can use [tf.io.RaggedFeature](https://www.tensorflow.org/api_docs/python/tf/io/RaggedFeature). E.g.:
> 
> ```
> sequence_features = {'my_feature': tf.io.RaggedFeature(dtype=tf.int64)}
> result = tf.io.parse_sequence_example(
>     example_batch, sequence_features=sequence_features) 
> ```

Hi @edloper ~
Do you have any ideas about how to write a data generator outputting dict?
https://github.com/tensorflow/tensorflow/issues/40425

Thanks!
