### ISSUE TITLE
ModuleNotFoundError: No module named 'tensorflow.python'

### ISSUE THREAD

**Issue by phornstein** [tensorflow/tensorflow#27593]
**System information**
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Windows 10
- **TensorFlow installed from (source or binary)**: tried "conda install tensorflow", "pip install tensorflow", and "pip install https://storage.googleapis.com/tensorflow/windows/cpu/tensorflow-1.13.1-cp36-cp36m-win_amd64.whl" 
- **TensorFlow version**: latest
- **Python version**: 3.6
- **Installed using virtualenv? pip? conda?**: tried pip and conda

I am trying to run Tensorflow in an anaconda 3.6 environment. I've tried installing tensorflow using pip, conda, and pip with the link to the wheel. No matter the installation method when I try to import tensorflow to test the installation I receive the error:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\"USERNAME"\AppData\Roaming\Python\Python36\site-packages\tensorflow\__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
ModuleNotFoundError: No module named 'tensorflow.python'

I've looked through the C:\Users\"USERNAME"\AppData\Roaming\Python\Python36\site-packages\tensorflow directory and cannot find any files named "tensorflow.python" nor can I find the "pywrap_tensorflow" file. 

After searching the issues tab I found thread #22300 with a similar problem. The admins suggested the user was missing a dll that contains the tensorflow.python file, but there was never a resolution. The user in thread #22300 is on linux while I am on windows 10. Is there a way to download the missing dlls or any other debugging steps I can take?

**Comment by lamberta** [comment]
Hi Parker, have you tried the steps for Windows/Conda here? https://www.tensorflow.org/install/pip

**Comment by phornstein** [comment]
Billy,
I’ve tried all of the options listed on the tensorflow install docs. All produce the same “no tensorflow.python” module error.

**Comment by ymodak** [comment]
Did you download and install the Microsoft Visual C++ 2015 Redistributable Update 3? Can you please confirm?

**Comment by ymodak** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Comment by WangChai-10** [comment]
It's correct.

**Comment by mikeyEcology** [comment]
I had this same problem on a mac OS and this helped me:
`pip install -U numpy`

**Comment by nicpatel963** [comment]
I'm facing same problem please give me solution this is embracing.
