### ISSUE TITLE
tf_upgrade_v2 fails on google colab and latest jupyter notebook

### ISSUE THREAD

**Issue by pleabargain** [tensorflow/tensorflow#27602]
in all fairness tensorflow 2 is in alpha... but the docs indicate the tf1 > tf2 script should work:
https://www.tensorflow.org/alpha/guide/upgrade

**System information**
using the code from https://www.tensorflow.org/alpha/guide/upgrade
I get syntax errors on google colab and on jupyter notebook

- TensorFlow installed from (source or binary):
!pip install tensorflow==2.0.0-alpha0 

- TensorFlow version (use command below):
mesh-tensorflow          0.0.5                
tensorflow               2.0.0a0              
tensorflow-estimator     1.13.0               
tensorflow-hub           0.4.0                
tensorflow-metadata      0.13.0               
tensorflow-probability   0.6.0  

- Python version:
google-api-python-client 1.6.7                
ipython                  5.5.0                
ipython-genutils         0.2.0                
ipython-sql              0.3.9                
opencv-contrib-python    3.4.3.18             
opencv-python            3.4.5.20             
python-apt               1.6.3+ubuntu1        
python-chess             0.23.11              
python-dateutil          2.5.3                
python-louvain           0.13                 
python-rtmidi            1.2.1                
python-slugify           3.0.2                
python-utils             2.3.0 

**Describe the current behavior**
tested on jupyter notebook 
jupyter --version
4.4.0
and google colab

**Describe the expected behavior**
tf_upgrade_v2  should work in in jupyter and google colab
**Code to reproduce the issue**
try the code yourself here:
https://colab.research.google.com/drive/1pVvIgkjGeWNyGWdy4A4gfEFQRdLJO8_G

**Other info / logs**
here is the source code
https://colab.research.google.com/drive/1pVvIgkjGeWNyGWdy4A4gfEFQRdLJO8_G

Here is the video showing the results:
https://youtu.be/u15oD3c_xHk

**Comment by lc0** [comment]
@pleabargain in colab/jupyter you need to prefix your bash commands.

try to run it like
```
!tf_upgrade_v2 --infile copy_of_got_book_generator.py --outfile TF2_got_book_generator.py
```

Starting with `!`

**Comment by pleabargain** [comment]
I am SO embarrassed. Thank you for pointing to my bone head mistake!
