### ISSUE TITLE
GPU Installation Issue

### ISSUE THREAD

**Issue by qo4on** [tensorflow/tensorflow#27603]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10, i5-750 only SSE4.2, without AVX.
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: No
- TensorFlow installed from (source or binary): pip install tf-nightly-gpu-2.0-preview
- TensorFlow version: TensorFlow 2.0
- Python version: conda create --name tensorflow-2.0 python=3.6
- Installed using virtualenv? pip? conda?: pip install tf-nightly-gpu-2.0-preview
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: cuda10, cuDNN 7.3.1,
- GPU model and memory: GTX1060 6GB

Do you know how to make tensorflow-2.0 work on nvidia gpu? I did the following without any error:
conda create --name tensorflow-2.0 python=3.6
activate tensorflow-2.0
pip install tf-nightly-gpu-2.0-preview
conda install -c anaconda cudatoolkit
conda install -c anaconda cudnn

But then:
>>> import tensorflow as tf
Traceback (most recent call last):
  File "C:\Users\Frust\Anaconda3\envs\tensorflow-2.0\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\Frust\Anaconda3\envs\tensorflow-2.0\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\Frust\Anaconda3\envs\tensorflow-2.0\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Users\Frust\Anaconda3\envs\tensorflow-2.0\lib\imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\Frust\Anaconda3\envs\tensorflow-2.0\lib\imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: Произошел сбой в программе инициализации библиотеки динамической компоновки (DLL).

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Frust\Anaconda3\envs\tensorflow-2.0\lib\site-packages\tensorflow\__init__.py", line 27, in <module>
    from tensorflow._api.v2 import audio
  File "C:\Users\Frust\Anaconda3\envs\tensorflow-2.0\lib\site-packages\tensorflow\_api\v2\audio\__init__.py", line 8, in <module>
    from tensorflow.python.ops.gen_audio_ops import decode_wav
  File "C:\Users\Frust\Anaconda3\envs\tensorflow-2.0\lib\site-packages\tensorflow\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Users\Frust\Anaconda3\envs\tensorflow-2.0\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "C:\Users\Frust\Anaconda3\envs\tensorflow-2.0\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\Frust\Anaconda3\envs\tensorflow-2.0\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\Frust\Anaconda3\envs\tensorflow-2.0\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Users\Frust\Anaconda3\envs\tensorflow-2.0\lib\imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\Frust\Anaconda3\envs\tensorflow-2.0\lib\imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: Произошел сбой в программе инициализации библиотеки динамической компоновки (DLL).

Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.﻿

**Comment by Mylittlerapture** [comment]
I also have problem when trying to install gpu version of tf2. Only the error is different.

`THESE PACKAGES DO NOT MATCH THE HASHES FROM THE REQUIREMENTS FILE. If you have updated the package versions, please update the hashes. Otherwise, examine the package contents carefully; someone may have tampered with them.
    tensorflow-gpu==2.0.0-alpha0 from https://files.pythonhosted.org/packages/2b/39/5447eb09d096fba399614d856ecb0f7f51c78070074592efe81e4cdd52d8/tensorflow_gpu-2.0.0a0-cp36-cp36m-win_amd64.whl#sha256=70b7faae24f6a20394b60f7ae38ad4d37232d8be85bd3289479c74d51366c2b9:
        Expected sha256 70b7faae24f6a20394b60f7ae38ad4d37232d8be85bd3289479c74d51366c2b9
             Got        e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855`

**Comment by qo4on** [comment]
Any suggestion how to fix that?

**Comment by gadagashwini** [comment]
Did you download and install the Microsoft Visual C++ 2015 Redistributable Update 3? Can you please confirm?

**Comment by qo4on** [comment]
It's installed already.

**Comment by gadagashwini** [comment]
@qo4on  Thanks for confirming.

**Comment by ymodak** [comment]
Did you add cuda, cudnn paths to environment? Please take a look at similar issues. #26059, #26364

**Comment by qo4on** [comment]
> Did you add cuda, cudnn paths to environment?

Which paths should I use when install cuda and cudnn through these commands?
conda install -c anaconda cudatoolkit
conda install -c anaconda cudnn

**Comment by ymodak** [comment]
You need to add sub folders: ```bin``` , ```include``` and ```lib``` to the path.

**Comment by qo4on** [comment]
> You need to add sub folders: `bin` , `include` and `lib` to the path.

I mean do I have to run these conda commands when cudnn-10.1-windows10-x64-v7.5.0.56.zip and cuda_10.1.105_418.96_win10.exe are already installed?
conda install -c anaconda cudatoolkit
conda install -c anaconda cudnn

**Comment by ymodak** [comment]
You already have cuda 10.0 toolkit, so need to install separately. You can add bin, include, lib folders consecutively placed in Library directory.

**Comment by qo4on** [comment]
What should I install separately?

**Comment by ymodak** [comment]
[NVIDIA® GPU drivers](https://www.nvidia.com/Download/index.aspx?lang=en-us) —CUDA 10.0 requires 410.x or higher.

**Comment by qo4on** [comment]
I have NVIDIA Creator Ready Driver 419.67 already installed. Cudatoolkit 10.0.130-0 and cudnn-7.3.1 installed also as I showed on the screenshot above. I don't understand what I should install separately.

**Comment by ymodak** [comment]
Right now you have to add bin, include, lib folders in your file system but not added to windows path. You have to add them. Take a look at  [Adding folder paths to the Windows path variable](https://docs.alfresco.com/4.2/tasks/fot-addpath.html)

**Comment by ymodak** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
