### ISSUE TITLE
'flatten_atrous_conv'  misses to flatten some atrous_convs

### ISSUE THREAD

**Issue by WenguoLi** [tensorflow/tensorflow#27617]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 16.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version (use command below):  master
- Python version: 2.7
- Bazel version (if compiling from source): 0.22.0
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Describe the current behavior**
I'm trying to optimize TF Model ' [xception65_coco_voc_trainval](http://download.tensorflow.org/models/deeplabv3_pascal_trainval_2018_01_04.tar.gz)' with graph_transforms tools.

Optimize for inference
`
bazel-bin/tensorflow/python/tools/optimize_for_inference --input=frozen.pb --output=stripped.pb --frozen_graph=True --input_names="sub_7" --output_names="ResizeBilinear_2"
`
Graph Transforms
`bazel-bin/tensorflow/tools/graph_transforms/transform_graph --in_graph="stripped.pb" --out_graph="flatten.pb" --inputs='sub_7' --outputs='ResizeBilinear_2' --transforms='flatten_atrous_conv'`

**Describe the expected behavior**
'flatten_atrous_conv'  misses to flatten some atrous_convs. 
![transform](https://user-images.githubusercontent.com/31765154/55704734-80988800-5a0f-11e9-8985-69f0bcb7b837.jpg)

**Comment by petewarden** [comment]
The optimize_for_inference script is deprecated, so we're not likely to be able to fix this soon unfortunately. Adding to contributions welcome.

**Comment by kumariko** [comment]
@WenguoLi Could you please let us know if you still need help on this ? We recommend that you upgrade to 2.6 which is latest stable version of TF and let us know if the issue still persists in newer versions. If it is resolved then please feel free to move this issue to close status ? Thanks!
