### ISSUE TITLE
E1102 non-callable raised by pylint when extending from tf.keras.layers.Layer

### ISSUE THREAD

**Issue by armando-fandango** [tensorflow/tensorflow#27611]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): custom-ops container
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): nightly-2.0-preview
- Python version: the one with custom-ops container
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

You can collect some of this information using our environment capture [script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with
python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"

**Describe the current behavior**

As given in this page : https://www.tensorflow.org/tutorials/eager/custom_layers
I am trying to change the code in seq2seq as follows:
in decoder.py : `class BaseDecoder(tf.keras.layers.Layer):`

However, while running the pylint stage of sanity_checks it produces the following error:

`tensorflow_addons/seq2seq/decoder_test.py:63: [E1102(not-callable), DecodeRNNTest._testDecodeRNN] my_decoder is not callable

tensorflow_addons/seq2seq/decoder_test.py:140: [E1102(not-callable), DecodeRNNTest._testDynamicDecodeRNNWithTrainingHelperMatchesDynamicRNN] my_decoder is not callable
`

**Describe the expected behavior**

The E1102 warning should not be raised.

**Code to reproduce the issue**
To reproduce, in this pull request: https://github.com/tensorflow/addons/pull/145
Go to decoder.py and change the signature of class in line 132

The warning disappear for pylint2 in current pull request, as currently it imports layers from tensorflow.python.keras and then extends layers.Layers

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by armando-fandango** [comment]
This code shows that there is something that pylint is not able to infer but objects from classes inherited from tf.keras.layers.Layer are callable: 

class a(tf.keras.layers.Layer):
  pass
class b(a):
  pass
class c(b):
  pass
aobj = a()
bobj = b()
cobj = c()
print(callable(aobj))
print(callable(bobj))
print(callable(cobj))

prints True 3 times.

**Comment by jvishnuvardhan** [comment]
@armando-fandango Could you check whether the issue was resolved or not? I know recently there were some updates in pylint. Thanks!

**Comment by jvishnuvardhan** [comment]
Closing due to lack of recent activity. Please update the issue when new information becomes available, and we will open a new issue. Thanks!
