### ISSUE TITLE
LD_LIRARY_PATH instead of LD_LIBRARY_PATH 

### ISSUE THREAD

**Issue by paul-bd** [tensorflow/tensorflow#27620]
Hello, 
in tensorflow/stream_executor/platform/default/dso_loader.cc line 50
LD_LIRARY_PATH is called instead of LD_LIBRARY_PATH
Best

**Comment by jvishnuvardhan** [comment]
I am closing this issue as the PR raised on this issue was merged already. But, please let me know if I'm mistaken. Thanks!
