### ISSUE TITLE
Huawei (android 6.0，OpenGL3.1 is Mali) GPU slower than CPU

### ISSUE THREAD

**Issue by anneyking** [tensorflow/tensorflow#27626]
I have two mobile phones, one is XiaoMi  (Android 9.0，OpenGL3.1 is Adreno), the other is Huawei (Android 6.0, OpenGL3.1 is Mail). When I run this demo app (Tensor Flow Lite GPU delegate), GPU is faster in the XiaoMi mobile phone than CPU, but in Huawei mobile phone, GPU is slower than CPU. What's the reason, the system version problem? Or the OpenGL ES chip problem?

**Comment by anneyking** [comment]
？？？？

**Comment by rootkitchao** [comment]
It depends on the specific model of your Huawei device.Some Huawei HiSilicon SOCs have very low GPU performance.In addition, the performance of the memory controller of the individual models of the HiSilicon SOC has performance problems.Devices that support NNAPI can use GPU/DSP/TPU to speed up some OPs, perhaps for performance improvements.

**Comment by anneyking** [comment]
well,If my device GPU is good enough, but my Android system is less than 8.1 (NNAPI needs to be greater than 8.1), what happens? in tensorflow lite demo app,Will the GPU be faster than the CPU?

**Comment by impjdi** [comment]
@anneyking 

Thanks for reporting.  We also have noticed the performance degradation with Mali devices.  We're actively investigating where the performance regression happened.  I'll update the thread when we find the root cause.

**Comment by holyhao** [comment]
@impjdi I test the inference time of mobilentv2 on Huawei Kirin seris GPU.  It is really a strange things. It shows same worse performance on  970 and 980, and shows better performance on 960.  It is sure that 980 has a stronger GPU,  but 960 get the best performance. Also, 980 gpu get slight accelerate compared to its cpu (about 30%). But, 960  gpu get  great accelerate compared to its cpu (about 7x). Below are some results on Kirin GPUs. So, can the tensorflow lite optimize for this?


|      | Kirin 980 (Mail 76) | Kirin 970 (Mail 72) | Kirin 960(Mail 71) |
| :-: | :-: | :-: | :-: |
| mobilenetv2(224*224) | 19ms | 21ms |14ms |
| ssdlite_mobilenetv2(300*300) | 41ms | 33ms | 29ms |

**Comment by freedomtan** [comment]
@impjdi FYR. Dunno if this is same problem, but it seems there is a problem on some Qualcomm platforms too. I bought a Pixel 3a last week. NNAPI driver doesn't work on it, so I tried GPU Delegate on it. I got GPU numbers much worse than expected with my [quick-and-dirty benchmark](https://github.com/freedomtan/glDelegateBench/). I also got similar GPU numbers for Mobilenet V1 on both [TfLiteCameraDemo](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/java/demo) apk and command line label_image.

model name | CPU 1 thread (ms) | CPU 4 threads (ms) | GPU delegate (ms)
-- | -- | -- | --
Mobilenet | 113 | 80 | 118
PoseNet | 138 | 96 | 175
DeepLab V3 | 173 | 132 | 270
Mobilenet SSD V2 COCO | 200 | 167 | 250

**Comment by impjdi** [comment]
@freedomtan 

We have prioritized and have someone working on Mali performance.  Maybe he can find the problem soon.  Hopefully that also addresses the Pixel 3a issue...

**Comment by freedomtan** [comment]
@impjdi FYR. I got more reasonable GPU numbers on Pixel 3a after the GlPersistentBuffer 87ae6fb8ee4.

model name | CPU 1 thread (ms) | CPU 4 threads (ms) | GPU (ms)
-- | --: | --: | --:
Mobilenet | 113 | 80 | 52
PoseNet | 138 | 96 | 78
DeepLab V3 | 173 | 132 | 144
Mobilenet SSD V2 COCO | 200 | 167 | 113

**Comment by impjdi** [comment]
@freedomtan 

Thanks for measuring the timing.  My colleague @NikolayChirkov added those improvements a couple days ago.  It doesn't solve the Mali performance bug, which we're still looking into, but improves some performance issues.

**Comment by freedomtan** [comment]
@impjdi It turns out that I was wrong. The faster numbers are on Pixel 3a running Android Q beta 3 and slower numbers are on Android P. The aforementioned patch doesn't help improve performance on Pixel 3a running Android P. Which means the slower numbers might be caused by GPU driver(s). Maybe the some of the Mali performance issues are caused by driver too?

**Comment by impjdi** [comment]
@freedomtan 

Thanks for the update.  Yeah, Driver versions definitely play a big role in GPU inference.  Thay may be possible.

**Comment by Saduf2019** [comment]
@anneyking 
Could you please try on the latest tf version and let us know if this is still an issue.
