### ISSUE TITLE
[doc/keras] `__init__` of `tf.keras.losses.BinaryCrossentropy` is not rendered correctly

### ISSUE THREAD

**Issue by csukuangfj** [tensorflow/tensorflow#27627]
- Doc Link: https://www.tensorflow.org/api_docs/python/tf/keras/losses/BinaryCrossentropy#class_binarycrossentropy

**Describe the documentation issue**

The `__init__` function of `tf.keras.losses.BinaryCrossentropy` is not rendered correctly.

See the link here https://www.tensorflow.org/api_docs/python/tf/keras/losses/BinaryCrossentropy#methods

**Comment by shashvatshahi1998** [comment]
You mean that in documentation __init__ is not described directly it is started from __call__?

**Comment by csukuangfj** [comment]
@shashvatshahi1998 

````

#### Args:

* <b>`from_logits`</b>: Whether `output` is expected to be a logits tensor. By default,
    we consider that `output` encodes a probability distribution.
* <b>`label_smoothing`</b>: If greater than `0` then smooth the labels.
* <b>`reduction`</b>: Type of <a href="../../../tf/losses/Reduction"><code>tf.losses.Reduction</code></a> to apply to loss. Default value is
    `SUM_OVER_BATCH_SIZE`.
* <b>`name`</b>: Optional name for the op.

<h2 id="__init__"><code>__init__</code></h2>

``` python
__init__(
    from_logits=False,
    label_smoothing=0,
    reduction=losses_impl.ReductionV2.SUM_OVER_BATCH_SIZE,
    name=None
)

---------
is obviously in its raw format.
---------

**Comment by ymodak** [comment]
Closing this issue since this is resolved. Feel free to reopen if have further questions. Thanks!
