### ISSUE TITLE
Tensorflow lite undefined reference

### ISSUE THREAD

**Issue by strattist** [tensorflow/tensorflow#27629]
**System information**
- OS Platform and Distribution: Linux Ubuntu 18.04
- TensorFlow installed from: source
- TensorFlow version: 1.12.1
- Bazel version: 0.15.0
- GCC/Compiler version: 7.3.0
(No python related information since I try to compile lite for C/C++ usage)

**Describe the problem**

**Provide the exact sequence of commands / steps that you executed before running into the problem**

First of all, I use CMake through a combo  `add_custom_command` and `add_custom_target` to handle the tensorflow build for me. I try to build tensorflow lite for x86 or ARM depending on my needs (I've done it before on the 1.10 tensorflow version).

The commands I execute to build tensorflow are in a script: 
```
bash configure
bazel --output_base=~/.tmp/tensorflow_lite/1.12.1/.Debug_x86 \
         build --jobs=4 \
                 //tensorflow/contrib/lite/experimental/c:libtensorflowlite_c.so
```
The build happens fine, I link `libtensorflowlite_c.so` to the custom CMake target I want to use in my own environment and it shows correctly on my make logs. 

However I have undefined references for: 
```
`tflite::DefaultErrorReporter()'
`tflite::Interpreter::AllocateTensors()'
`tflite::InterpreterBuilder::InterpreterBuilder(tflite::FlatBufferModel const&, tflite::OpResolver const&)'
`vtable for tflite::MutableOpResolver'
`tflite::InterpreterBuilder::operator()(std::unique_ptr<tflite::Interpreter, std::default_delete<tflite::Interpreter> >*)'
`tflite::InterpreterBuilder::~InterpreterBuilder()'
`tflite::Interpreter::Invoke()'
`tflite::Interpreter::~Interpreter()'
`vtable for tflite::ops::builtin::BuiltinOpResolver'
`tflite::Interpreter::SetNumThreads(int)'
`tflite::FlatBufferModel::~FlatBufferModel()'
`tflite::ops::builtin::BuiltinOpResolver::BuiltinOpResolver()'
`tflite::FlatBufferModel::BuildFromFile(char const*, tflite::ErrorReporter*)'
```
I quickly checked the bazel workspace and build directives and it seems my issues are related to the `framework` cc_library bazel is creating and that is linked to `libtensorflowlite_c` through the `c_api`.

I don't know bazel a lot, I'm a bit lost with the dependencies. I would say the dependencies should propagate like this `framework -> c_api & c_api_internal -> libtensorflowlite_c.so`. Is it what happen?
Should I add `//tensorflow/contrib/lite:framework` and other bazel target to be sure they are built? 

How bazel handles mutual dependency, is this an acceptable situation? It happens between `context` (`//tensorflow/contrib/lite`) and `c_api_internal` (`//tensorflow/contrib/lite/experimental/c`) and between `frawework` (`//tensorflow/contrib/lite`) and `c_api_internal` (`//tensorflow/contrib/lite/experimental/c`).

```
# context definition, needs c_api_internal
cc_library(
    name = "context",
    hdrs = ["context.h"],
    deps = ["//tensorflow/contrib/lite/c:c_api_internal"],
)
# framework definition, needs c_api_internal (only deps are shown)
cc_library(
    name = "framework",
    srcs = [...] + select({...}),
    hdrs = [...],
    copts = tflite_copts(),
    defines = select({...}),
    linkopts = [] + select({...}),
    deps = [
        ":arena_planner",
        ":graph_info",
        ":memory_planner",
        ":schema_fbs_version",
        ":simple_memory_arena",
        ":string",
        ":util",
        "//tensorflow/contrib/lite/c:c_api_internal",
        "//tensorflow/contrib/lite/core/api",
        "//tensorflow/contrib/lite/kernels:eigen_support",
        "//tensorflow/contrib/lite/kernels:gemm_support",
        "//tensorflow/contrib/lite/nnapi:nnapi_lib",
        "//tensorflow/contrib/lite/profiling:profiler",
        "//tensorflow/contrib/lite/schema:schema_fbs",
    ] + select({...}),
)
# c_api_internal definition, needs context & framework
cc_library(
    name = "c_api_internal",
    srcs = ["c_api.h"],
    hdrs = ["c_api_internal.h"],
    copts = tflite_copts(),
    visibility = [
        "//tensorflow/contrib/lite/experimental/c:__subpackages__",
    ],
    deps = [
        "//tensorflow/contrib/lite:context",
        "//tensorflow/contrib/lite:framework",
    ],
)
# 
```

**Comment by cmooreml** [comment]
@strattist did you resolve with cmake?

**Comment by strattist** [comment]
Yes, for x86 I use these bazel commands: 

```
bash configure
  bazel --output_base=/.tmp/tensorflow_lite/1.12.1/.Debug_x86 \
        build --jobs=4 \
              --cxxopt='-std=gnu++11' \
              //tensorflow/contrib/lite/experimental/c:libtensorflowlite_c.so
```

For ARM and AARCH64 I used the Makefile they give in `./tensorflow/tensorflow/contrib/lite/tools/make` although I modified it to add everything within the experimental directory:
- Add `$(wildcard tensorflow/contrib/lite/experimental/c/*.cc)` to the base `CORE_CC_ALL_SRCS` Makefile variable
- Add `$(wildcard tensorflow/contrib/lite/experimental/kernels/*.cc)` to the `CORE_CC_ALL_SRCS` insice the `BUILD_TYPE` condition just below.
- I also deleted the `schema_generated.h` build rule.

It worked that way for me.
