### ISSUE TITLE
[doc/keras] incorrect comment in `__init__` of `tf.keras.layers.AveragePooling1D`

### ISSUE THREAD

**Issue by csukuangfj** [tensorflow/tensorflow#27633]
- Doc Link: https://www.tensorflow.org/api_docs/python/tf/keras/layers/AveragePooling1D#arguments

**Describe the documentation issue**
See the comment below

```
pool_size: Integer, size of the **max** pooling windows.
```

It should be **average** instead of **max** since this is average pooling.

Furthermore, the format of the description for `input shape` and `output shape` is broken.
It is not rendered in a list format.

**Comment by mihaimaruseac** [comment]
Closed via 31be1b7 / #27779
