### ISSUE TITLE
Missing documentation for variable ops.

### ISSUE THREAD

**Issue by smr97** [tensorflow/tensorflow#27634]
<em>Please make sure that this is a documentation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:doc_template</em>

**System information**
- TensorFlow version: v1.13
- Doc Link:

**Describe the documentation issue**
Hi, I am looking for documentation on the ReadVariableOp and VarHandleOp. Specifically as to what are the inputs that they take and what do they produce exactly. I dug around the source code for mentions of these ops and found some calls [here](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/ops/resource_variable_ops.py#L196) and [here](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/ops/resource_variable_ops.py#L864). While this hints at the signature of these ops, I would love to look at the implementation, which probably exists in [this](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/ops/resource_variable_ops.py#L37) module, but I can not find it in this public repo's master branch. Could someone point me to this?

Alternately, is there any documentation on these ops written [this](https://www.tensorflow.org/api_docs/cc/class/tensorflow/ops/fused-batch-norm) way?

Thanks!
**We welcome contributions by users. Will you be able to update submit a PR (use the [doc style guide](https://www.tensorflow.org/community/documentation)) to fix the doc Issue?**

**Comment by amahendrakar** [comment]
@smr97,
You can find the documentation of `ReadVariableOp` and `VarHandleOp` with their inputs and output below

- https://www.tensorflow.org/api_docs/python/tf/raw_ops/ReadVariableOp
- https://www.tensorflow.org/api_docs/python/tf/raw_ops/VarHandleOp

Marking the issue as closed. Please feel free to re-open if necessary. Thanks!
