### ISSUE TITLE
Typo in SpaceToBatchND and BatchToSpaceND documentation

### ISSUE THREAD

**Issue by alexeyr** [tensorflow/tensorflow#27638]
**System information**
- TensorFlow version: 1.13
- Doc Link: https://www.tensorflow.org/api_docs/cc/class/tensorflow/ops/space-to-batch-n-d, https://www.tensorflow.org/api_docs/cc/class/tensorflow/ops/batch-to-space-n-d

**Describe the documentation issue**
Example 2 in https://www.tensorflow.org/api_docs/cc/class/tensorflow/ops/space-to-batch-n-d says

> The output tensor has shape `[4, 1, 1, 3]` and value:

>     [[[1, 2, 3]], [[4, 5, 6]], [[7, 8, 9]], [[10, 11, 12]]]

However, that value's shape is `[4, 1, 3]`. It appears the shape is correct, but the value should be

    [[[[1, 2, 3]]], [[[4, 5, 6]]], [[[7, 8, 9]]], [[[10, 11, 12]]]]

The same issue is present in https://www.tensorflow.org/api_docs/cc/class/tensorflow/ops/batch-to-space-n-d example 2.

**We welcome contributions by users. Will you be able to update submit a PR (use the [doc style guide](https://www.tensorflow.org/community/documentation)) to fix the doc Issue?**
Yes.

**Comment by jvishnuvardhan** [comment]
@alexeyr This was resolved in recent docs on TF website. Please check the [page here](https://www.tensorflow.org/api_docs/python/tf/raw_ops/SpaceToBatchND).

Current example shows as shown below
`[[[[1, 2, 3]]], [[[4, 5, 6]]], [[[7, 8, 9]]], [[[10, 11, 12]]]]`

I am closing this issue as this was already resolved. Please feel free to reopen if I am mistaken. Thanks!
