### ISSUE TITLE
[doc/keras] incorrect comment in the example for `tf.keras.layers.Add`

### ISSUE THREAD

**Issue by csukuangfj** [tensorflow/tensorflow#27632]
- Doc Link: https://www.tensorflow.org/api_docs/python/tf/keras/layers/Add#class_add

**Describe the documentation issue**

See the code example (https://www.tensorflow.org/api_docs/python/tf/keras/layers/Add#class_add)

```python
    added = keras.layers.Add()([x1, x2])  # equivalent to added =
    keras.layers.add([x1, x2])
```

It should be

```
    added = keras.layers.Add()([x1, x2])  # equivalent to added = keras.layers.add([x1, x2])
```

**Comment by shashvatshahi1998** [comment]
@csukuangfj  I am added a pr regarding that issue.

**Comment by csukuangfj** [comment]
you're adding too many commits.

**Comment by csukuangfj** [comment]
git squash
