### ISSUE TITLE
Training on device with TensorFlow Lite

### ISSUE THREAD

**Issue by miaout17** [tensorflow/tensorflow#27646]
This ticket tracks supporting on-device training with TensorFlow Lite. 

A few high-level milestones:

- [ ] Functional prototype for basic training (e.g. convolution / dense network)
- [ ] Functional prototype for training with control flow (e.g. RNN / LSTM networks)
- [ ] Productionize / optimize basic training
- [ ] Productionize / optimize training with control flow

See also #17328

**Comment by amitsrivastava78** [comment]
@miaout17 , i will be very interested in this work, please let me know if you can offload some of the work to me for this.

Regards
Amit

**Comment by hamlatzis** [comment]
@miaout17 yes I would also want to know if in the future (near future maybe?) we could have training on the device with TF Lite

keep up the good work

**Comment by kistora** [comment]
Any news about this feature ?
I'm wondering as it is part of the TFlite 2019 roadmap https://www.tensorflow.org/lite/guide/roadmap

**Comment by himanshurobo** [comment]
@miaout17 : Waiting for good news?

**Comment by kistora** [comment]
This is a usefull link to integrate federated learning on android: https://vision-air.github.io/federated.html

**Comment by CiriousJoker** [comment]
@miaout17 
Any news on this? I'm trying to create a product that basically relies on this as part of it's USP since I want users to be able to create their own gestures.

**Comment by xumengwei** [comment]
Any updates on supporting trianing on Android? Especially with GPU support. Thanks!

**Comment by pengyuan-zhou** [comment]
> This is a usefull link to implement federated learning on android: https://vision-air.github.io/federated.html

might be too greedy, but have you found any opensource code from them or similar ones?
Thanks:)

**Comment by chunduriv** [comment]
@miaout17 ,

TensorFlow Lite now supports training your models on-device, in addition to running inference. On-device training enables interesting personalization use cases where models can be fine-tuned based on user needs.

For more details please refer [this article](https://blog.tensorflow.org/2021/11/on-device-training-in-tensorflow-lite.html). Thanks!

**Comment by chunduriv** [comment]
Are you satisfied with the resolution of your issue?
[Yes](https://goo.gl/forms/Oe0tEvODFRoI2gJF3)
[No](https://goo.gl/forms/fUjzOfrtkFbrOT8d2)
