### ISSUE TITLE
Kubernetes Charts for Tensorflow 2.0

### ISSUE THREAD

**Issue by ChethanUK** [tensorflow/tensorflow#27647]
**System information**
- TensorFlow version (you are using): 2.0
- Are you willing to contribute it (Yes/No): Yes

**Describe the feature and the current behavior/state.**
Would be nice to have Kubernetes charts which users can deploy and train or server the tf models. 

**Will this change the current API? How?**
NO, but will help users.

**Who will benefit with this feature?**
Those who are using K8s already...

Would need 2 charts:
1. CPU Version TF-2.0
2. GPU Version TF-2.0

**Comment by martinwicke** [comment]
The right place for this would likely be tensorflow/ecosystem.

**Comment by rmothukuru** [comment]
@ChethanUK,
Can you please refer to the documentation of [Tensorflow's ML Pipeline using Kubeflow](https://www.tensorflow.org/tfx/guide/kubeflow), this Tutorial on [How to Run Tensorflow Pipeline on Kubeflow](https://www.tensorflow.org/tfx/tutorials/tfx/cloud-ai-platform-pipelines#7_run_your_first_tfx_pipeline_on_kubeflow) and the [documentation of Kubeflow Pipelines](https://www.kubeflow.org/docs/components/pipelines/overview/pipelines-overview/) and let us know if this is what you are looking for?
Thanks!
