### ISSUE TITLE
Java: add support for Alpine Linux (Docker)

### ISSUE THREAD

**Issue by neterium** [tensorflow/tensorflow#27643]
**System information**
- TensorFlow version (you are using): 1.12
- Are you willing to contribute it (Yes/No): No

**Describe the feature and the current behavior/state.**
I'm using the TF Java library to serve prediction requests and I don't have any issue there.
However, I'm building a docker image from my server. The size is 343mb from openjdk:8-jdk-alpine, but TF does not work (Error loading shared library ld-linux-x86-64.so.2).
I noticed in the doc that only Ubuntu was supported. Ok.
I created the image from ubuntu:18.04 and installed the jdk over it... no more error as expected, but the size of the image jumps to 500m :(, even after cleaning out everything I could.

Any plans to make it work from the openjdk:8-jdk-alpine image (or provide a minimalist dockerfile which inherits from that one) ?

**Will this change the current api? How?**
No

**Who will benefit with this feature?**
A lot, I can imagine

**Any Other info.**

**Comment by jvishnuvardhan** [comment]
@neterium Could you check whether the issue persists with latest TF( 1.13.1 and/or 2.0)? Thanks!

**Comment by neterium** [comment]
Just tried (1.13.1) , same error:

> Caused by: java.lang.UnsatisfiedLinkError: /tmp/tensorflow_native_libraries-1555007765207-0/libtensorflow_jni.so: Error loading shared library ld-linux-x86-64.so.2: No such file or directory (needed by /tmp/tensorflow_native_libraries-1555007765207-0/libtensorflow_jni.so)
>         at java.lang.ClassLoader$NativeLibrary.load(Native Method)
>         at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
>         at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1824)
>         at java.lang.Runtime.load0(Runtime.java:809)
>         at java.lang.System.load(System.java:1086)
>         at org.tensorflow.NativeLibrary.load(NativeLibrary.java:101)
>         at org.tensorflow.TensorFlow.init(TensorFlow.java:66)
>         at org.tensorflow.TensorFlow.<clinit>(TensorFlow.java:70)
>         at org.tensorflow.SavedModelBundle.<clinit>(SavedModelBundle.java:170)
>

**Comment by angersson** [comment]
We do not have any plans to support Alpine Linux in our Docker containers. However, we welcome contributions to the tensorflow/tools/dockerfiles directory.

**Comment by KabirKwatra** [comment]
[This StackOverflow thread](https://stackoverflow.com/questions/50288034/unsatisfiedlinkerror-tmp-snappy-1-1-4-libsnappyjava-so-error-loading-shared-li/51655643#51655643) might be helpful

**Comment by tilakrayal** [comment]
@neterium ,
Can you please check this [comment](https://github.com/tensorflow/tensorflow/issues/27643#issuecomment-519159209) and let us know if it helps.Thanks!
