### ISSUE TITLE
[Feature Request] Need for manual parallelization of a tensorflow graph (or function)

### ISSUE THREAD

**Issue by caissalover** [tensorflow/tensorflow#27644]
- TensorFlow version (you are using): 2.0

**Describe the feature and the current behavior/state.**
Today, there's no easy way to parallelize a single tf graph (or function in 2.0) to different inputs. tf.map_fn doesn't parallelize and tf.while_loop doesn't generate error when the graph is run sequentially. It's strange really what the keyword parallel_iterations even does in tf.while_loop

**Will this change the current api? How?**
I request a feature named tf.prange (parallel_range) or something equivalent which can be used inside tf.function, as shown below,

     @tf.function
     def foo():
          for i in tf.prange(100):
                 ...

which will help us to get an error if an op depends on the values of previous flows in a function. Or some other solution to parallelize and raise error in case of no parallelization. As of now, everything happens in the backend and it's difficult to find the problems that lead to such sequential execution of tf graph.

**Who will benefit with this feature?**
Coders wanting to manually parallelize a particular graph to multiple inputs. (Potentially every ML developer with minimal resources)

P.S. This would make things extremely convenient.
https://github.com/tensorflow/tensorflow/issues/24774 and https://github.com/tensorflow/tensorflow/issues/1984 also state how inconvenient manual parallelization is in tensorflow since quite some time.

An exact same issue has been raise before. https://github.com/tensorflow/tensorflow/issues/12492

**Comment by amanp592** [comment]
@caissalover i would love to work on this, can you help me out?

**Comment by alextp** [comment]
@agarwal-ashish I think this can be implemented somehow with autograph and pfor.

Assigning to you for triage.

**Comment by agarwal-ashish** [comment]
@caissalover, regarding semantics of parallel_iterations in while_loop, conceptually it is unrolling up to that many loop iterations at any instant and then trying to execute it like a sequential graph. This allows up to that many iterations to run in parallel, but if there are dependencies across iterations, those dependencies are executed sequentially, while still trying to run other parts in parallel.

pfor, under python/ops/parallel_for, uses SPMD semantics for dealing with state accesses across iterations. Hence the semantics are not the same as running all iterations in parallel and bailing out if there are dependencies.

If you wrote your own while_loop, than you'd be responsible for checking what loop carried variables you used. Another option is to let autograph convert code with tf.range, and then inspecting then generated graph to check for loop carried state.

**Comment by mdanatg** [comment]
@caissalover , could you give us a concrete example to make sure we're on the same page about the idea?
I think there are multiple ways in which it can be understood, and my take is annotating the loop somehow to error out if it cannot be trivially parallelized.

That would mean, this loop is trivially parallelizable:

```
ta = tf.TensorArray(...)
for i in tf.range(n):
  tf.autograph.set_loop_options(force_parallel=True)  # Ok
  ta = ta.write(i, ta.read(i) + 1)
```

Whereas this is not:

```
ta = tf.TensorArray(...)
for i in tf.range(n):
  tf.autograph.set_loop_options(force_parallel=True)  # Raises an error: ta[i] depends on ta[i-1] - cannot run in parallel
  ta = ta.write(i, ta.read(i - 1) + 1)
```

Does this match your suggestion?

**Comment by caissalover** [comment]
Yes, exactly @mdanatg . So if an error is raised in 2nd case while force_parallel, we'll be able to achieve desired speed more easily by changing the faulty code. I hope that the above syntax structure will not execute all the loops in parallel but just the one here. Otherwise nested loops can be a problem.

**Comment by mdanatg** [comment]
I think the bottleneck here is the TensorArray piece. There currently isn't a way to asynchronously update a TensorArray (as is the case for variables, for instance), which causes dependencies between loop iterations (in the example above `ta` depends on the previous iteration).

We could use variables and scatter_update, but in that case the loop would no longer be differentiable.

In essence, I think what we need is a truly parallel map_fn. This could be achieved by unrolling the loop, a mechanism commonly used in compilers (depicted below, without the part that handled uneven splits):

```
unroll_size = 20
for i in tf.range(0, n, unroll_size):
  i_min = i * unroll_size
  i_max = (i + 1) * unroll_size
  unroll_results = []
  for k in range(unroll_size):  # this will be unrolled in the graph
    i = i_min + k
    unroll_results.append(input[i] + 1)
  ta = ta.scatter(tf.range(i_min, i_max), tf.stack(unroll_results))
```

I think this could be feasibly implemented either in map_fn or in autograph.

**Comment by mdanatg** [comment]
Actually, it seems that `map_fn` is already optimized and does parallelize. Have you run any tests that show no performance change when increasing parallel_iterations from 1 to a larger value?

**Comment by caissalover** [comment]
@mdanatg No, that is not true, I have just now ran my graph at parallel_iterations=1 and 114, and my GPU utilization and time of running the graph didn't change much. It is not optimized.

**Comment by mdanatg** [comment]
Right, scratch that last note, it was referring to a sentence in the original post.

@agarwal-ashish , could we use the bailing-out logic that you have in pfor and raise an error when this directive was present? AutoGraph can detect it, but statically checking for loop-carried state would be a more involved effort which we wouldn't have time to work on right away.

**Comment by agarwal-ashish** [comment]
@mdanatg, as mentioned earlier in the thread, pfor has SPMD semantics, not strict sequential semantics. Hence it may not raise errors with concurrent state accesses across iterations.

**Comment by mdanatg** [comment]
It turns out that automatically parallelizing arbitrary code is a topic very much open to research and we're unlikely to have a robust general solution any time soon.

That said, APIs like `tf.map_fn`, `tf.while_loop`, `tf.data` and `tf.distribute` are quite aggressive in parallelizing loops, even when it might not appear that they aren't. Ultimately it becomes an engineering task to profile and fine tune the code where performance is critical, and given current advancements, that is likely to remain the case for all but very specific applications.
