### ISSUE TITLE
Add name=None argument to roll function

### ISSUE THREAD

**Issue by Gurpreetsingh9465** [tensorflow/tensorflow#27665]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version 2.0:
- Are you willing to contribute it Yes:

**Describe the feature and the current behavior/state.**
`tensorflow.python.ops.manip_ops.roll` does not take name=None as parameter the current API
does not allow that

**Will this change the current api? How?**
Yes, roll function in `tensorflow.python.ops.manip_ops.roll` will take name=None as argument which will return a tensor with `name=name` and not the default one `roll_n`

**File where roll exists**
[manip_ops.py](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/ops/manip_ops.py)

**Comment by alextp** [comment]
There's an open PR, no need to assign the issue.

**Comment by alextp** [comment]
There's an open PR, no need to assign the issue.

**Comment by kumariko** [comment]
@Gurpreetsingh9465 We see that [PR #27075](https://github.com/tensorflow/tensorflow/pull/27075) is merged , please let us know if we can close this issue ?
