### ISSUE TITLE
Using slim to train my own model, ImportError: cannot import name 'slim'

### ISSUE THREAD

**Issue by lerrry13579** [tensorflow/tensorflow#27664]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):window7 Anacoda3 env
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version (use command below):1.2.1
- Python version:3.5.4
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

You can collect some of this information using our environment capture [script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with
python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"

**Describe the current behavior**
a importerror when i copy nets from slim ,however i have installed a slim in c:\programdata\anacoda3\lib\site-packages

from nets import nets_factory

**Other info / logs**
ImportError                               Traceback (most recent call last)
<ipython-input-5-a29f10245850> in <module>()
      2 import tensorflow as tf
      3 from PIL import Image
----> 4 from nets import nets_factory
      5 import numpy as np

E:\Tensorflow\learning\nets\nets_factory.py in <module>()
     22 import tensorflow as tf
     23 
---> 24 from nets import alexnet
     25 from nets import cifarnet
     26 from nets import i3d

E:\Tensorflow\learning\nets\alexnet.py in <module>()
     39 import tensorflow as tf
     40 
---> 41 slim = tf.contrib.slim
     42 trunc_normal = lambda stddev: tf.truncated_normal_initializer(0.0, stddev)
     43 

C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\util\lazy_loader.py in __getattr__(self, item)
     51 
     52   def __getattr__(self, item):
---> 53     module = self._load()
     54     return getattr(module, item)
     55 

C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\util\lazy_loader.py in _load(self)
     40   def _load(self):
     41     # Import the target module and insert it into the parent's namespace
---> 42     module = importlib.import_module(self.__name__)
     43     self._parent_module_globals[self._local_name] = module
     44 

C:\ProgramData\Anaconda3\lib\importlib\__init__.py in import_module(name, package)
    124                 break
    125             level += 1
--> 126     return _bootstrap._gcd_import(name[level:], package, level)
    127 
    128 

C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\contrib\__init__.py in <module>()
     55 from tensorflow.contrib import saved_model
     56 from tensorflow.contrib import seq2seq
---> 57 from tensorflow.contrib import slim
     58 from tensorflow.contrib import solvers
     59 from tensorflow.contrib import sparsemax

ImportError: cannot import name 'slim'

**Comment by Peng-Ru** [comment]
You can try something like ' import tensorflow.contrib.slim as slim ' or upgrade your tensorflow version to 1.8 or higher

**Comment by achandraa** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
