### ISSUE TITLE
Automatic mixed precision for tensorflow-gpu

### ISSUE THREAD

**Issue by rootkitchao** [tensorflow/tensorflow#27668]
Recently, I noticed that NVIDIA updated the Deep Learning SDK documentation and added [Tensorflow Automixing Accuracy Training.](https://docs.nvidia.com/deeplearning/sdk/mixed-precision-training/index.html#tensorflow-amp)This looks very simple,only need to set:
`os.environ['TF_ENABLE_AUTO_MIXED_PRECISION'] = '1'`
But I didn't find any relevant information on the tensorflow website and github.Does this really work?Or need additional conditions?

**Comment by ppwwyyxx** [comment]
It is part of NVIDIA's own tensorflow. It is not integrated into the official tensorflow.

**Comment by rootkitchao** [comment]
> It is part of NVIDIA's own tensorflow. It is not integrated into the official tensorflow.

thank you for your reply

**Comment by byronyi** [comment]
I believe it's available for nightly and 1.14 with #26342.
