### ISSUE TITLE
tensorflow2.0.0-alpha no eagarTensor when using dataset.map

### ISSUE THREAD

**Issue by eyiztan** [tensorflow/tensorflow#27672]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): 
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):  Windows10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):  binary
- TensorFlow version (use command below): 2.0.0-alpha
- Python version: 3.7
- Bazel version (if compiling from source):  
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:  v9.0.176
- GPU model and memory:  NVIDIA GeForce GTX   42GB 

You can collect some of this information using our environment capture [script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with
python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"

**Describe the current behavior**
when using dataset.map to parse tfrecord, the tensor is not eagerTensor

**Describe the expected behavior**
hope all the tensor could be eagerTensor in tf2.0

**Code to reproduce the issue**

Provide a reproducible test case that is the bare minimum necessary to generate the problem.
```
def parse_tf_record(tf_record):
    features = {'image': tf.io.FixedLenFeature([], tf.string, default_value=""),
                'height': tf.io.FixedLenFeature([], tf.int64, default_value=0),
                'width': tf.io.FixedLenFeature([], tf.int64, default_value=0),
                'shape': tf.io.VarLenFeature(tf.float32),
                }

    parsed_features = tf.io.parse_single_example(tf_record, features)
    image = tf.io.decode_raw(parsed_features['image'], tf.uint8)
    height = tf.cast(parsed_features['height'], tf.int32)
    width = tf.cast(parsed_features['width'], tf.int32)
    image = tf.reshape(image, [height, width, 3])

    image = tf.image.convert_image_dtype(image, dtype=tf.float32)

    shape = tf.sparse.to_dense(parsed_features['shape'], default_value=0.0)

    shape = tf.reshape(shape, [Config.num_point, 6])

    print(shape.numpy())   ##  <------ when using dataset.map, will fail at this line 

    return image, shape

def run_train(train_tf_record)

    dataset = tf.data.TFRecordDataset([train_tf_record])

    for item in dataset:
        parse_tf_record(item)    ##  <---------- when debug into , the all the tensor in 'parse_tf_record' is eagerTensor 
 

    dataset = dataset.repeat().shuffle(1000).map(parse_tf_record,  
   num_parallel_calls=4).batch(32)

## <---------when debug into, all the tensor in 'parse_tf_record' is tensor

    for item in dataset.take(1):
        print(item)


if __name__ == '__main__':
    train_tf_record = 
    run_train(train_tf_record)

```

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by ymodak** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow-tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.
