### ISSUE TITLE
Not found: No registered '_FusedMatMul' OpKernel for CPU devices compatible with node

### ISSUE THREAD

**Issue by SefaZeng** [tensorflow/tensorflow#27671]
I changed the title of this post since it occurs new problems. And you can see it at the latest comment.Thx.
_________________________________________________________________________________

<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):linux 3.10.107
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):source
- TensorFlow version (use command below):1.12
- Python version:2.7.5
- Bazel version (if compiling from source):No bazel.I use the build_all_linux.sh.
- GCC/Compiler version (if compiling from source): 4.8.2
- CUDA/cuDNN version: no
- GPU model and memory: no

You can collect some of this information using our environment capture [script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with
python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"

**Describe the current behavior**
I trained a model with python and save it as ckpt files, and then transform it to pb file. I make the tensorflow to a stastic library and then try to load the model on c++. I can create the session and ReadBinaryProto, but when I run this code ,it fails and return theis message:
`tensorflow::Status status_create = m_session->Create(*m_graphdef);`

> Invalid argument: No OpKernel was registered to support Op 'Sin' with these attrs.  Registered devices: [CPU], Registered kernels:
>   <no registered kernels>
> 
>          [[{{node parallel_0/rnnsearch_0/add_timing_signal/Sin}} = Sin[T=DT_FLOAT, _device="/gpu:0"](parallel_0/rnnsearch_0/add_timing_signal/mul_2)]]
> 

**Describe the expected behavior**
The model will be loaded successfully.
**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.
```
tensorflow::Status status_create_sess = tensorflow::NewSession(tensorflow::SessionOptions(), &m_sess);
	if(!status_create_sess.ok()){
		cout<<"ERROR: FAIL TO CREATE SESSION"<<endl;
		cout<<status_create_sess.ToString()<<endl;
		m_eris = FAIL_TO_CREATE_SESSION;
		return m_eris;
	}

	m_graphdef = new(std::nothrow) tensorflow::GraphDef;
	if(m_graphdef==NULL){
		cout<<"ERROR: FAIL TO LOAD MODEL"<<endl;
		m_eris = FAIL_TO_LOAD_MODEL;
		return m_eris;
	}

	tensorflow::Status status_load = tensorflow::ReadBinaryProto(tensorflow::Env::Default(), model_path, m_graphdef);
	if(!status_load.ok()){
		cout<<"ERROR: FAIL TO LOAD MODEL"<<endl;
		cout<<status_load.ToString()<<endl;
		m_eris = FAIL_TO_LOAD_MODEL;
		return m_eris;
	}   
	tensorflow::Status status_create = m_sess->Create((*m_graphdef));
	if(!status_create.ok()){
		cout<<"ERROR: FAIL TO CREATE GRAPh IN SESSION"<<endl;
		cout<<status_create.ToString()<<endl;
		m_eris=FAIL_TO_CREATE_GRAPH;
		return m_eris;
	}
```
**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by SefaZeng** [comment]
I can find math_ops.cc in the source code of tensorflow , and I can find the Sin ops here. But it still return this message, so could somebody so kind to tell me where can I check the registered ops?

**Comment by SefaZeng** [comment]
I try to print the register list via  `tensorflow::OpRegistry::Global()->DebugString(false)` , but it returns 

> error: 'tensorflow::OpRegistry' has not been declared

Does this mean I didn't build the tensorflow to a static lib correctly? But I can load a simple graph with two tensors to add.

**Comment by SefaZeng** [comment]
Ok.I can print all the register ops and I can find Sin here.

> Op<name=Sin; signature=x:T -> y:T; attr=T:type,allowed=[DT_BFLOAT16, DT_HALF, DT_FLOAT, DT_DOUBLE, DT_COMPLEX64, DT_COMPLEX128]>

So, where is the problem? It seems related to [#18807](https://github.com/tensorflow/tensorflow/issues/18807),but I tried 1.6 1.12 1.10 and all the version returns the same error.

**Comment by SefaZeng** [comment]
Need I build the tensorflow with bazel? Is there any difference with building from makefile and bazel?

**Comment by SefaZeng** [comment]
Any help?

**Comment by SefaZeng** [comment]
I try to use print_seletive_registration_header tool to set op_to_register.h, but there are a lot of  

> Warning: no kernel found for op XXX

And even some very basic ops I think. Do I need to change something or compile the tensorflow before?

**Comment by SefaZeng** [comment]
I change the tensorflow to 1.10 of both static lib and python version , it can load the graph. But I can't set the tensor value like the many blogs did before.
```
	tensorflow::TensorShape seq_input_shape;
	cout<<input.size()<<endl;
	seq_input_shape.AddDim(1);
	seq_input_shape.AddDim(input.size());
	tensorflow::TensorShape input_length_shape;
	input_length_shape.AddDim(1);
	input_length_shape.AddDim(1);
	cout<<seq_input_shape<<endl;
	cout<<seq_input_shape.dims()<<endl;
	tensorflow::Tensor seq_input(tensorflow::DT_INT32, seq_input_shape);
	tensorflow::Tensor input_length(tensorflow::DT_INT32, input_length_shape);
	cout<<"input tensor ok"<<endl;
	cout<<seq_input.AllocatedBytes()<<endl;

	//std::copy_n(input.begin(),input.size(),seq_input.flat<int>().data());
	//cout<<"good here"<<endl;
	//vector<int> temp = {input.size()};
	//std::copy_n(temp.begin(),temp.size(),input_length.flat<int>().data());

	auto inputMapped = seq_input.tensor<int,2>();
	auto inputLengthMapped = input_length.tensor<int,2>();

	for(int i = 0;i<input.size();i++){
		cout<<i<<endl;
		cout<<input[i]<<endl;
		inputMapped(0,i) = input[i];
	}
```
Everytime I try to set the tensor value , it returns segmentation default. No matter what I use ,tensor<int,2> or flat <int> . So I try to another way , but I don't know whether it work or not, because if I try to print the tensor value, still segmentation fault error.
```
	for(int i = 0;i<input.size();i++){
		cout<<i<<endl;
		cout<<input[i]<<endl;
		inputMapped = &input[i];
                inputMapped+=1;
	}
```
And then I finally can run the model , but it returns No OpKernel once again!!!!!!!!!!

>  Executor failed to create kernel. Not found: No registered '_FusedMatMul' OpKernel for CPU devices compatible with node {{node parallel_0/rnnsearch_0/encoder/forward0/while/gru_cell/linear_state/BiasAdd}}
>         .  Registered:  <no registered kernels>
> 
>          [[parallel_0/rnnsearch_0/encoder/forward0/while/gru_cell/linear_state/BiasAdd]]
> run error
> Not found: No registered '_FusedMatMul' OpKernel for CPU devices compatible with node {{node parallel_0/rnnsearch_0/encoder/forward0/while/gru_cell/linear_state/BiasAdd}}
>         .  Registered:  <no registered kernels>
> 
>          [[parallel_0/rnnsearch_0/encoder/forward0/while/gru_cell/linear_state/BiasAdd]]
> 

I am tired, is there any ways to solve the problem? plz...

**Comment by aselle** [comment]
Ops and kernels are different things. build_all_linux.sh is probably not registering kernels properly. You can try making a simple bazel binary that loads the graphs and tries to run it. That way you can eliminate your code as a possible problem.

**Comment by alokprasad** [comment]
> Ops and kernels are different things. build_all_linux.sh is probably not registering kernels properly. You can try making a simple bazel binary that loads the graphs and tries to run it. That way you can eliminate your code as a possible problem.
> 
> Stricly speaking anything in contrib (which build_all_linux) is may or may not work, but we don't generally support.

@aselle building using makefile is much simpler than bazel , 
also for most of the platform libtensorflow_cc.so is not easy to build ( e.g androdi)
but libtensorflow-core.a can easily be built on android

**Comment by alokprasad** [comment]
how to register math_ops in libtensorflow-core.a

**Comment by alokprasad** [comment]
> math_ops.cc

@SefaZeng  where you able to integrate the operation in math_ops.cc in libtensorflow-core.a

**Comment by SefaZeng** [comment]
> > math_ops.cc
> 
> @SefaZeng where you able to integrate the operation in math_ops.cc in libtensorflow-core.a

I change the tensorflow version to 1.13 and the problem is solved... I dont know why, but it work for me, although my tensorflow-py version is 1.10.

**Comment by psyhtest** [comment]
I have the [same issue](https://github.com/ctuning/ck-tensorflow/blob/master/package/lib-tensorflow-1.14.0-src-static/README.md) with TF C++ 1.14 and the MLPerf ResNet model.

**Comment by kumariko** [comment]
@SefaZeng We are checking to see if you still need help on this issue. We recommend that you upgrade to 2.6 which is latest stable version of TF and let us know if the issue still persists in newer versions. we will get you the right help.Thanks!
