### ISSUE TITLE
ImportError: DLL load failed: Unable to find specific module.

### ISSUE THREAD

**Issue by daniziz** [tensorflow/tensorflow#27689]
Hi all,

Im unable to import keras or tensorflow in jupyter:

### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Windows 10 Pro
- **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device**: HP Omen, i7 7700HQ, 16GB RAM
- **TensorFlow installed from (source or binary)**: pip install tensorflow-gpu
- **TensorFlow version (use command below)**: 1.13.1
- **Python version**: 3.7.3
- **CUDA/cuDNN version**: 10.1
- **GPU model and memory**: GTX 1060 laptop
- **Exact command to reproduce**: import tensorflow as tf

---TRACE---

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
~\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow.py in <module>
     57 
---> 58   from tensorflow.python.pywrap_tensorflow_internal import *
     59   from tensorflow.python.pywrap_tensorflow_internal import __version__

~\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py in <module>
     27             return _mod
---> 28     _pywrap_tensorflow_internal = swig_import_helper()
     29     del swig_import_helper

~\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py in swig_import_helper()
     23             try:
---> 24                 _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
     25             finally:

~\AppData\Local\Continuum\anaconda3\lib\imp.py in load_module(name, file, filename, details)
    241         else:
--> 242             return load_dynamic(name, filename, file)
    243     elif type_ == PKG_DIRECTORY:

~\AppData\Local\Continuum\anaconda3\lib\imp.py in load_dynamic(name, path, file)
    341             name=name, loader=loader, origin=path)
--> 342         return _load(spec)
    343 

ImportError: DLL load failed: No se puede encontrar el módulo especificado.

During handling of the above exception, another exception occurred:

ImportError                               Traceback (most recent call last)
<ipython-input-6-9ab9087e201e> in <module>
----> 1 import tensorflow
      2 print(tensorflow.__version__)
      3 # Puedes añadir todos los imports adicionales que necesites aquí
      4 import keras
      5 from keras.datasets import fashion_mnist

~\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow\__init__.py in <module>
     22 
     23 # pylint: disable=g-bad-import-order
---> 24 from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
     25 
     26 from tensorflow._api.v1 import app

~\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow\python\__init__.py in <module>
     47 import numpy as np
     48 
---> 49 from tensorflow.python import pywrap_tensorflow
     50 
     51 # Protocol buffers

~\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow.py in <module>
     72 for some common reasons and solutions.  Include the entire stack trace
     73 above this error message when asking for help.""" % traceback.format_exc()
---> 74   raise ImportError(msg)
     75 
     76 # pylint: enable=wildcard-import,g-import-not-at-top,unused-import,line-too-long

ImportError: Traceback (most recent call last):
  File "C:\Users\dizquierdo\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\dizquierdo\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\dizquierdo\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Users\dizquierdo\AppData\Local\Continuum\anaconda3\lib\imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\dizquierdo\AppData\Local\Continuum\anaconda3\lib\imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: No se puede encontrar el módulo especificado.

Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

Regards

**Comment by amanp592** [comment]
@daniziz can you be more specific to which tensorflow-gpu version you're using??

**Comment by daniziz** [comment]
@amanp592 My Bad, I was to lazy to check it because I was running out of time when I opened the post.

Here it goes:

tensorflow-gpu            1.13.1                   pypi_0    pypi

Regards!

**Comment by daniziz** [comment]
Acording to NVIDIA doc, I've compiled debugQuery.exe in order to check if cuda is correctly installed. 

Here goes te output:

(base) C:\ProgramData\NVIDIA Corporation\CUDA Samples\v10.1\bin\win64\Debug>deviceQuery.exe
deviceQuery.exe Starting...

 CUDA Device Query (Runtime API) version (CUDART static linking)

Detected 1 CUDA Capable device(s)

Device 0: "GeForce GTX 1060 with Max-Q Design"
  CUDA Driver Version / Runtime Version          10.1 / 10.1
  CUDA Capability Major/Minor version number:    6.1
  Total amount of global memory:                 6144 MBytes (6442450944 bytes)
  (10) Multiprocessors, (128) CUDA Cores/MP:     1280 CUDA Cores
  GPU Max Clock rate:                            1342 MHz (1.34 GHz)
  Memory Clock rate:                             4004 Mhz
  Memory Bus Width:                              192-bit
  L2 Cache Size:                                 1572864 bytes
  Maximum Texture Dimension Size (x,y,z)         1D=(131072), 2D=(131072, 65536), 3D=(16384, 16384, 16384)
  Maximum Layered 1D Texture Size, (num) layers  1D=(32768), 2048 layers
  Maximum Layered 2D Texture Size, (num) layers  2D=(32768, 32768), 2048 layers
  Total amount of constant memory:               65536 bytes
  Total amount of shared memory per block:       49152 bytes
  Total number of registers available per block: 65536
  Warp size:                                     32
  Maximum number of threads per multiprocessor:  2048
  Maximum number of threads per block:           1024
  Max dimension size of a thread block (x,y,z): (1024, 1024, 64)
  Max dimension size of a grid size    (x,y,z): (2147483647, 65535, 65535)
  Maximum memory pitch:                          2147483647 bytes
  Texture alignment:                             512 bytes
  Concurrent copy and kernel execution:          Yes with 2 copy engine(s)
  Run time limit on kernels:                     Yes
  Integrated GPU sharing Host Memory:            No
  Support host page-locked memory mapping:       Yes
  Alignment requirement for Surfaces:            Yes
  Device has ECC support:                        Disabled
  CUDA Device Driver Mode (TCC or WDDM):         WDDM (Windows Display Driver Model)
  Device supports Unified Addressing (UVA):      Yes
  Device supports Compute Preemption:            Yes
  Supports Cooperative Kernel Launch:            No
  Supports MultiDevice Co-op Kernel Launch:      No
  Device PCI Domain ID / Bus ID / location ID:   0 / 1 / 0
  Compute Mode:
     < Default (multiple host threads can use ::cudaSetDevice() with device simultaneously) >

deviceQuery, CUDA Driver = CUDART, CUDA Driver Version = 10.1, CUDA Runtime Version = 10.1, NumDevs = 1
Result = PASS

**Comment by gadagashwini** [comment]
@daniziz, Hi, Did you download and install the Microsoft Visual C++ 2015 Redistributable Update 3? Can you please confirm?

**Comment by daniziz** [comment]
Hi @gadagashwini ,

No... this is what i have installed on my laptop:

![image](https://user-images.githubusercontent.com/39950437/55944804-aa3cf380-5c49-11e9-933a-c581664f30ac.png)

regards!

**Comment by daniziz** [comment]
> @daniziz, Hi, Did you download and install the Microsoft Visual C++ 2015 Redistributable Update 3? Can you please confirm?

Hi @gadagashwini ,

No, I don't. This is what I have installed:

![image](https://user-images.githubusercontent.com/39950437/55944878-da849200-5c49-11e9-8717-f36bb0683478.png)

should I do it?

regards!!

**Comment by daniziz** [comment]
Hi @gadagashwini ,

Same error with Microsoft Visual C++ 2015 Redistributable Update 3 installed... 

:(

**Comment by gadagashwini** [comment]
Thanks for confirming.

**Comment by ymodak** [comment]
duplicate #26364

**Comment by lllhhu** [comment]
My local development environment is ok, but publish to other environment has this problem, please help me to have a look

Unable to load DLL 'tensorflow' or one of its

**Comment by lllhhu** [comment]
My local development environment is ok, but publish to other environment has this problem, please help me to have a look

Unable to load DLL 'tensorflow' or one of its
