### ISSUE TITLE
import error

### ISSUE THREAD

**Issue by gauravbisht098** [tensorflow/tensorflow#27693]
Traceback (most recent call last):
  File "C:/Users/GAURAV/PycharmProjects/Object_Detection/object", line 9, in <module>
    from utils import label_map_util
ImportError: cannot import name 'label_map_util'

**Comment by amanp592** [comment]
@gauravbisht098 hey! try this `from object_detection.utils import label_map_util` and see if it works!

**Comment by gauravbisht098** [comment]
I did but then it said no object detection module found

**Comment by amanp592** [comment]
@gauravbisht098 pip install utils again and see if it works! also update me if it worked

**Comment by gauravbisht098** [comment]
I already did

**Comment by ymodak** [comment]
This issue is more suitable on [tensorflow/models](https://github.com/tensorflow/models/issues/new) repo. Please take a look at duplicate issue https://github.com/tensorflow/models/issues/1990

**Comment by gauravbisht098** [comment]
Can you send me a best object detection code..???
