### ISSUE TITLE
LookupError: No gradient defined for operation 'ScatterUpdate_675' (op type: ScatterUpdate)

### ISSUE THREAD

**Issue by psnegi** [tensorflow/tensorflow#2770]
### Environment info
Operating System:  Ubuntu 14.04 TLS

Installed version of CUDA and cuDNN: 
-rw-r--r-- 1 root root 189170 May 10 10:51 /usr/local/cuda/lib/libcudadevrt.a
lrwxrwxrwx 1 root root     16 May 10 10:51 /usr/local/cuda/lib/libcudart.so -> libcudart.so.7.5
lrwxrwxrwx 1 root root     19 May 10 10:51 /usr/local/cuda/lib/libcudart.so.7.5 -> libcudart.so.7.5.18
-rwxr-xr-x 1 root root 311596 May 10 10:51 /usr/local/cuda/lib/libcudart.so.7.5.18
-rw-r--r-- 1 root root 558020 May 10 10:51 /usr/local/cuda/lib/libcudart_static.a

using 0.8.0 and  0.9.0rc0 version cpu only.
I am building a graph involving scatter_update operation. When building optimizer op I am getting following error
**LookupError: No gradient defined for operation 'ScatterUpdate_675' (op type: ScatterUpdate)**

Looks like gradient is not defined for scatter_update.

**Comment by prb12** [comment]
This is expected.

ScatterUpdate is a stateful operation on a variable.  If you use operations like this in your model then you will not be able to automatically compute the gradient. (You will notice that none of the state related ops have an associated gradient function.)

If you would like to discuss this limitation further, please feel free to ask on StackOverflow and tag it with the `tensorflow` tag.
