### ISSUE TITLE
When using long time inference TFLite GPU not working in mobile (demo app)

### ISSUE THREAD

**Issue by Nanamare** [tensorflow/tensorflow#27703]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Mobile device= Pixel 2, Samsung Galaxy 6, 7, 8
- TensorFlow Lite version : experimental-0.0.1
- GPU : Adreno 540 

**Describe the current behavior**
Using more than about 10 minutes, keep running Demo App, but not working inference.
Normal inference time: about 50ms (pixel 2)
Abnormal inference time: about 3ms (pixel 2)
The same problem occurs in other phones.(Galaxy series ( >= 6), Xiaomi redmi note series)

**Code to reproduce the issue**
[Just demo code](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/java/demo)

**Comment by impjdi** [comment]
We had a situation that `glDispatchProgram` would just fail after 400k calls (or something like that) on a particular phone.  Hm, I'm actually surprised that it happens on so many phones as you have described.

**Comment by sachinprasadhs** [comment]
Hi, Could you please try using the latest version, now the Android version dependency has been increased.
Please follow the guide here  https://www.tensorflow.org/lite/performance/delegates for more details.
