### ISSUE TITLE
Link to the definiton tf.image broken

### ISSUE THREAD

**Issue by surgan12** [tensorflow/tensorflow#27709]
### **On the page** 
https://www.tensorflow.org/api_docs/python/tf/image

### **The link Under heading**
 `Module
    tf.Image`

https://www.tensorflow.org/code/stable/tensorflow/_api/v1/image/__init__.py
**is broken.**

**Comment by lamberta** [comment]
This one looks fixed: https://www.tensorflow.org/api_docs/python/tf/image
