### ISSUE TITLE
XLA: build failed on 32bits platform

### ISSUE THREAD

**Issue by cee1** [tensorflow/tensorflow#27704]
**System information**
- OS Platform and Distribution: Linux
- TensorFlow installed from (source or binary): build tensorflow on arm cortex-a15
- TensorFlow version: 1.13.1
- Bazel version (if compiling from source): binary, 0.19.2
- GCC/Compiler version (if compiling from source):  binary, gcc 5.3

**Describe the problem**
Build failed at tensorflow/compiler/xla/service/llvm_ir/llvm_util.cc:378
```c++
378                 b->CreateIntToPtr(b->getInt64(absl::bit_cast<int64>(&LogS64)),
379                                   log_function_type->getPointerTo()),
```
Looks like XLA doesn't support 32bits platform?

**Any other info / logs**
**external/com_google_absl/absl/base/casts.h:179:3: error: static assertion failed: Source and destination types should have equal sizes.**
```
tensorflow/compiler/xla/service/llvm_ir/llvm_util.cc:378:76:   required from here
...
In instantiation of 'Dest absl::bit_cast(const Source&) [with Dest = long long int; Source = const char*; typename std::enable_if<(! absl::internal_casts::is_bitcastable<Dest, Source>::value), int>::type <anonymous> = 0]':
```
- Note: related code snippet (tensorflow/compiler/xla/service/llvm_ir/llvm_util.cc:378)
```c++
374 void EmitLogging(const char* tag, llvm::Value* value, llvm::IRBuilder<>* b) {
375   llvm::FunctionType* log_function_type = llvm::FunctionType::get(
376       b->getVoidTy(), {b->getInt64Ty(), b->getInt64Ty()}, /*isVarArg=*/false);
377   b->CreateCall(log_function_type,
378                 b->CreateIntToPtr(b->getInt64(absl::bit_cast<int64>(&LogS64)),
379                                   log_function_type->getPointerTo()),
380                 {b->getInt64(absl::bit_cast<int64>(tag)), value});
381 }
```

**Comment by gadagashwini** [comment]
@cee1, Request you to go through this [link](https://www.tensorflow.org/xla/overview#supported_platforms) for XLA support platforms. Thanks !

**Comment by cee1** [comment]
> @cee1, Request you to go through this [link](https://www.tensorflow.org/xla/overview#supported_platforms) for XLA support platforms. Thanks !

Thanks for the reply.

Some questions:
a) For AOT, tfcompile is needed, it can be built from tensorflow source code, right?
b) AOT requires "XLA option" enabled during "./configure"?  If yes, the problem still exists (unable to compile due to assertion failure)

**Comment by ymodak** [comment]
@jlebar

**Comment by jlebar** [comment]
> TensorFlow installed from (source or binary): build tensorflow on arm cortex-a15

Building TF on ARM is not supported (meaning, "good luck").  However, targeting ARM *using tfcompile* from an x86 host is supported, and I agree this code is broken even in that case.  We don't specify whether we support 32-bit ARM, but it would strike me as pretty odd if we only could target 64-bit ARM.

I am a bit confused, though, because EmitLogging does not appear to be called from anywhere?

In any case, would you be willing to send a patch?  We don't readily have capability to test this platform.

**Comment by ymodak** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
