### ISSUE TITLE
nvcc error   : 'cudafe++' died with status 0xC0000005 (ACCESS_VIOLATION)

### ISSUE THREAD

**Issue by Rtik1988** [tensorflow/tensorflow#27706]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10 Pro, 1809, 17763.379
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): source
- TensorFlow version: v1.13.1
- Python version: v3.5.0:374f501f4567
- Installed using virtualenv? pip? conda?: pip
- Bazel version (if compiling from source): 0.20.0
- GCC/Compiler version (if compiling from source): Microsoft (R) C/C++ Optimizing Compiler Version 19.00.24234.1 for x64
- CUDA/cuDNN version: 10.0/7.5
- GPU model and memory: NVIDIA GeForce RTX 2080 Ti

**Describe the problem**
Build of kernels:transpose_functor_gpu  fails with the following error
```
nvcc error   : 'cudafe++' died with status 0xC0000005 (ACCESS_VIOLATION)
```
and this error:
```
ERROR: D:/tensorflow/tensorflow/core/kernels/BUILD:1687:1: C++ compilation of rule '//tensorflow/core/kernels:transpose_functor_gpu' failed (Exit 5): python.exe failed: error executing command
```

The problem seems very similar to [this](https://github.com/tensorflow/tensorflow/issues/27576) issue.

**Provide the exact sequence of commands / steps that you executed before running into the problem**

(tensorflow-v1.13) d:\tensorflow>python ./configure.py
WARNING: The following rc files are no longer being read, please transfer their contents or import their path into one of the standard rc files:
nul
WARNING: Running Bazel server needs to be killed, because the startup options are different.
WARNING: --batch mode is deprecated. Please instead explicitly shut down your Bazel server using the command "bazel shutdown".
INFO: Invocation ID: e482c527-4d04-440e-b726-4dcee4cabbba
You have bazel 0.20.0 installed.
Please specify the location of python. [Default is C:\Users\admin\tensorflow-v1.13\Scripts\python.exe]:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: module 'site' has no attribute 'getsitepackages'
Found possible Python library paths:
  C:\Users\admin\tensorflow-v1.13\Lib\site-packages
Please input the desired Python library path to use.  Default is [C:\Users\admin\tensorflow-v1.13\Lib\site-packages]

Do you wish to build TensorFlow with XLA JIT support? [y/N]: n
No XLA JIT support will be enabled for TensorFlow.

Do you wish to build TensorFlow with ROCm support? [y/N]: n
No ROCm support will be enabled for TensorFlow.

Do you wish to build TensorFlow with CUDA support? [y/N]: y
CUDA support will be enabled for TensorFlow.

Please specify the CUDA SDK version you want to use. [Leave empty to default to CUDA 10.0]: 10.0

Please specify the location where CUDA 10.0 toolkit is installed. Refer to README.md for more details. [Default is C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.0]:

Please specify the cuDNN version you want to use. [Leave empty to default to cuDNN 7]: 7.5

Please specify the location where cuDNN 7 library is installed. Refer to README.md for more details. [Default is C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.0]:

Please specify a list of comma-separated Cuda compute capabilities you want to build with.
You can find the compute capability of your device at: https://developer.nvidia.com/cuda-gpus.
Please note that each additional compute capability significantly increases your build time and binary size. [Default is: 3.5,7.0]: 7.5

Please specify optimization flags to use during compilation when bazel option "--config=opt" is specified [Default is /arch:AVX]: /arch:AVX2

Would you like to override eigen strong inline for some C++ compilation to reduce the compilation time? [Y/n]:
Eigen strong inline overridden.

Preconfigured Bazel build configs. You can use any of the below by adding "--config=<>" to your build command. See .bazelrc for more details.
        --config=mkl            # Build with MKL support.
        --config=monolithic     # Config for mostly static monolithic build.
        --config=gdr            # Build with GDR support.
        --config=verbs          # Build with libverbs support.
        --config=ngraph         # Build with Intel nGraph support.
        --config=dynamic_kernels        # (Experimental) Build kernels into separate shared objects.
Preconfigured Bazel build configs to DISABLE default on features:
        --config=noaws          # Disable AWS S3 filesystem support.
        --config=nogcp          # Disable GCP support.
        --config=nohdfs         # Disable HDFS support.
        --config=noignite       # Disable Apacha Ignite support.
        --config=nokafka        # Disable Apache Kafka support.
        --config=nonccl         # Disable NVIDIA NCCL support.

(tensorflow-v1.13) d:\tensorflow>bazel build --config=opt //tensorflow/tools/pip_package:build_pip_package

**Any other info / logs**
ERROR: D:/tensorflow/tensorflow/core/kernels/BUILD:1687:1: C++ compilation of rule '//tensorflow/core/kernels:transpose_functor_gpu' failed (Exit 5): python.exe failed: error executing command

nvcc error   : 'cudafe++' died with status 0xC0000005 (ACCESS_VIOLATION)
Target //tensorflow/tools/pip_package:build_pip_package failed to build
INFO: Elapsed time: 542.611s, Critical Path: 293.00s
INFO: 3067 processes: 3067 local.
FAILED: Build did NOT complete successfully

**Comment by ymodak** [comment]
You need to [Install Visual C++ Build Tools 2015](https://www.tensorflow.org/install/source_windows#install_visual_c_build_tools_2015) Please take a look at these [instructions](https://www.tensorflow.org/install/source_windows).

**Comment by Rtik1988** [comment]
Visual C++ Build Tools 2015 are installed. I was following the [instructions](https://www.tensorflow.org/install/source_windows) and [this](https://medium.com/@amsokol.com/update-2-how-to-build-and-install-tensorflow-gpu-cpu-for-windows-from-source-code-using-bazel-61c26553f7e8) article as a reference (without the Eigen patch).

**Comment by CovertKoala** [comment]
I'm continually receiving this error as well building 2.0b1 on windows, same configure settings, but compute capability 6.1 and bazel 0.26 (per the error I get while installing according to the instructions on https://www.tensorflow.org/install/source_windows).

**Comment by ymodak** [comment]
Can you please try this workaround and see if it helps? Thanks!
https://github.com/tensorflow/tensorflow/issues/27576#issuecomment-504703397

**Comment by gunan** [comment]
This is a bug in cuda 10 distribution. you can try building with cuda 10.1, or simply replace the cudafe++ binary in your cuda 10 distribution with the cuda 10.1 version.

Closing the issue as a duplicate.
