### ISSUE TITLE
tf-nightly-2.0-preview's tf.summary doesn't work with tensorboard

### ISSUE THREAD

**Issue by janosh** [tensorflow/tensorflow#27719]
**System information**
- Have I written custom code: no
- OS: macOS 10.14.4
- TensorFlow installed from: binary
- TensorFlow version: 2.0.0-dev20190410 (latest nightly)
- Python version: 3.6.7 (miniconda)

**Current behavior & code to reproduce the issue**

The following code

```py
import tensorflow as tf

summary_writer = tf.summary.create_file_writer("tmp")

with summary_writer.as_default():
    for i in range(100):
        tf.summary.scalar("index", i, step=i)
summary_writer.close()
```

outputs an events file to `/tmp` but trying to view it with `tensorboard --logdir ./tmp`  throws
```
Exception in thread Reloader:
AttributeError: module 'tensorflow._api.v2.compat.v1' has no attribute 'pywrap_tensorflow'
```
followed by
```
W0410 17:26:13.712886 123145489154048 core_plugin.py:172] Unable to get first event timestamp for run .: No event timestamp could be found
```
and an empty TB dashboard. I'm running the latest `tb-nightly`. Any ideas what's causing this?

**Perhaps related:**
- #27713

**Comment by nfelt** [comment]
Closing this in favor of the tensorboard issue, https://github.com/tensorflow/tensorboard/issues/2106
