### ISSUE TITLE
Support large embeddings with `MirroredStrategy` and `MultiWorkerMirroredStrategy`

### ISSUE THREAD

**Issue by yuefengz** [tensorflow/tensorflow#27726]
**System information**
- TensorFlow version (you are using): TF 2.0
- Are you willing to contribute it (Yes/No): Yes

**Describe the feature and the current behavior/state.**
Currently, `MirroredStrategy` and `MultiWorkerMirroredStrategy` assume a model replica including its embeddings could fit in one GPU or one machine. Allgather is used to aggregated gradients with respect to embeddings.

We would like to understand whether it is necessary and important to support
1. placing embeddings on host with `MirroredStrategy` and why using `ParameterServerStrategy` is not ideal
2. replicating embeddings on host with `MultiWorkerMirroredStrategy` and why in this case using `ParameterServerStrategy` is not ideal
2. sharding embeddings in `MultiWorkerMirroredStrategy` and why `ParameterServerStrategy` is not ideal.

**Will this change the current api? How?**
Yes.

**Who will benefit with this feature?**
Users who use large embeddings in their models.

**Any Other info.**
N/A

**Comment by asheetal** [comment]
I was starting out with MirroredStrategy with embeddings and realized it wasn't as easy as with other model building. Anyone have any tutorial or got something working? Seems this is an open topic almost 2 years old

**Comment by cocorosiekz** [comment]
What's the progress of this issue?
