### ISSUE TITLE
How i upgrade tensorflow 1.13.1 to 1.4.0 in window(without GPU)

### ISSUE THREAD

**Issue by KumarPardeep1** [tensorflow/tensorflow#27720]
i want to upgrade tensroflow 1.13.1 to 1.4.0 in window 10 without GPU 
i upgrade it but it stop 1.13.1. 
is this possible for me to reach 1.4.0 tensorflow version,
 if it is then hoW?

**Comment by sunithapriya** [comment]
You can try building the TensorFlow package from source for windows using the link [https://www.tensorflow.org/install/source_windows]. 
The build is tested for tensorflow-1.4.0 on CPU:

<img width="740" alt="Screen Shot 2019-04-11 at 5 49 18 PM" src="https://user-images.githubusercontent.com/43215312/55995373-54387200-5c82-11e9-8fcf-68e72ab30611.png">

**Comment by achandraa** [comment]
Is this still an issue ? Please let us know. Thanks!

**Comment by KumarPardeep1** [comment]
> Is this still an issue? Please let us know. Thanks!

yes, still there is an issue.
I am not able to update tensorflow.

**Comment by wdirons** [comment]
Clarification, you want to **downgrade** from 1.13 to 1.4 ?  Why move to so old of a version?

1.14 is not finished yet. 1.13.1 is the latest version.

**Comment by achandraa** [comment]
Moving to older versions might lead to compatibility issues. We recommend to stay with the latest version unless and until it is required. You can try above solution provided and let us know on the update. Thanks!

**Comment by achandraa** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
