### ISSUE TITLE
When test， An exception has occurred, use %tb to see the full traceback.

### ISSUE THREAD

**Issue by vinovsmamba** [tensorflow/tensorflow#27732]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): I download code from https://github.com/tegg89/SRCNN-Tensorflow
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Win 10 64 bits
- TensorFlow installed from (source or binary): anaconda3 64bits  conda install
- TensorFlow version (use command below): tensorflow-gpu 1.13.1

- Python version: 3.6.8  spyder 3.3.3
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: CUDA 10.0.130  cudnn 7.3.1 installed via conda with tensorflow together
- GPU model and memory: notebook gtx1060 3GB

You can collect some of this information using our environment capture [script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with
python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"
![image](https://user-images.githubusercontent.com/41459859/55927092-bd9e8d80-5c4e-11e9-9b88-afa87c4d1717.png)

**Describe the current behavior**

runfile('F:/F_coding/other/SRCNN-Tensorflow-master/main.py', wdir='F:/F_coding/other/SRCNN-Tensorflow-master')
C:\Users\myaccount\AppData\Roaming\Python\Python36\site-packages\h5py\__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
{'batch_size': <absl.flags._flag.Flag object at 0x000001A7E0DF4518>,
 'c_dim': <absl.flags._flag.Flag object at 0x000001A7E6D0C390>,
 'checkpoint_dir': <absl.flags._flag.Flag object at 0x000001A7E6D0C588>,
 'epoch': <absl.flags._flag.Flag object at 0x000001A7E0DDEC18>,
 'h': <tensorflow.python.platform.app._HelpFlag object at 0x000001A7E6D0C710>,
 'help': <tensorflow.python.platform.app._HelpFlag object at 0x000001A7E6D0C710>,
 'helpfull': <tensorflow.python.platform.app._HelpfullFlag object at 0x000001A7E6D0C780>,
 'helpshort': <tensorflow.python.platform.app._HelpshortFlag object at 0x000001A7E6D0C7F0>,
 'image_size': <absl.flags._flag.Flag object at 0x000001A7E0DF4908>,
 'is_train': <absl.flags._flag.BooleanFlag object at 0x000001A7E6D0C630>,
 'label_size': <absl.flags._flag.Flag object at 0x000001A7E175F6D8>,
 'learning_rate': <absl.flags._flag.Flag object at 0x000001A7E6AABBE0>,
 'sample_dir': <absl.flags._flag.Flag object at 0x000001A7E6D0C5F8>,
 'scale': <absl.flags._flag.Flag object at 0x000001A7E6D0C438>,
 'stride': <absl.flags._flag.Flag object at 0x000001A7E6D0C4E0>}
WARNING:tensorflow:From D:\scholarship\anaconda\envs\tensorflow\lib\site-packages\tensorflow\python\framework\op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
WARNING:tensorflow:From D:\scholarship\anaconda\envs\tensorflow\lib\site-packages\tensorflow\python\util\tf_should_use.py:193: initialize_all_variables (from tensorflow.python.ops.variables) is deprecated and will be removed after 2017-03-02.
Instructions for updating:
Use `tf.global_variables_initializer` instead.
 [*] Reading checkpoints...
WARNING:tensorflow:From D:\scholarship\anaconda\envs\tensorflow\lib\site-packages\tensorflow\python\training\saver.py:1266: checkpoint_exists (from tensorflow.python.training.checkpoint_management) is deprecated and will be removed in a future version.
Instructions for updating:
Use standard file APIs to check for files with this prefix.
INFO:tensorflow:Restoring parameters from checkpoint\srcnn_21\SRCNN.model-2550000
 [*] Load SUCCESS
Testing...
An exception has occurred, use %tb to see the full traceback.
![image](https://user-images.githubusercontent.com/41459859/55927114-d1e28a80-5c4e-11e9-8537-53bf878702d3.png)

SystemExit

**Describe the expected behavior**
idk
**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by jvishnuvardhan** [comment]
This is not Build/Installation or Bug/Performance issue. Please post this kind of support questions at [Stackoverflow](https://stackoverflow.com/questions/tagged/tensorflow). There is a big community to support and learn from your questions. GitHub is mainly for addressing bugs in installation and performance. 

This is more related to an issue with another repository. So please post in that [repo](https://github.com/tegg89/SRCNN-Tensorflow/issues) or in Stackoverflow. Thanks!

**Comment by jvishnuvardhan** [comment]
I am closing this issue as it is a support questions more suited for Stackoverflow. Thanks!
