### ISSUE TITLE
Invalid value in tensor used for shape: -1879048192

### ISSUE THREAD

**Issue by zhouxiaowei1120** [tensorflow/tensorflow#27742]
When I  try to reshape a tensor with high dimension, it causes the error as follows:

Invalid value in tensor used for shape: -1879048192

The code is : tf.reshape(scores, shape=[-1, nb_features*nb_features]), where scores is a matrix whose shape is 45192*45192 and nb_features is 45192.

WHy I get this error? Is the dimension too high?

Thank you.

**Comment by bipinkc19** [comment]
tf.reshape(scores, shape=[-1, nb_featuresnb_features]) should be 
tf.reshape(scores, shape=[-1, nb_features, nb_features])
Also nb_feature * nb_feature is 2042316864 but you are passing a tensor of shape 1879048192.

The new tensor after reshape has shape [-1, x, x] so the original tensor passed should of shape [x * x]

**Comment by zhouxiaowei1120** [comment]
> tf.reshape(scores, shape=[-1, nb_featuresnb_features]) should be
> tf.reshape(scores, shape=[-1, nb_features, nb_features])
> Also nb_feature * nb_feature is 2042316864 but you are passing a tensor of shape 1879048192.
> 
> The new tensor after reshape has shape [-1, x, x] so the original tensor passed should of shape [x * x]
 Sorry, the right code is tf.reshape(scores, shape=[-1, nb_features * nb_features]). I want to reshape the matrix from [nb_features, nb_features] to [-1,  nb_features * nb_features].

**Comment by bipinkc19** [comment]
I hope this will be helpful to you.
```import tensorflow as tf
a = [[2.6, 3.25, 4.32, 12], [1, 2, 3, 4], [1, 2, 3, 4],[1, 2, 3, 4]]
var = tf.placeholder(tf.float32, shape=[4, 4], name="x")
ans = tf.reshape(var, shape=[-1, 4 * 4])
with tf.Session() as sess:
    print(sess.run(ans, feed_dict={t:a}))
```

### Output:
[[ 2.6   3.25  4.32 12.    1.    2.    3.    4.    1.    2.    3.    4. 1.    2.    3.    4.  ]]

The problem might be that the tensor passed in the reshape is not of shape [nb_feature, nb_feature], make sure the input value has the correct shape.

**Comment by zhouxiaowei1120** [comment]
Thank you for your help. I try later. @bipinkc19

**Comment by gadagashwini** [comment]
We are closing this issue for now due to lack of activity. Please comment if this is still an issue for you. Thanks!
