### ISSUE TITLE
Building Tensorflow on Windows (CPU only) issue

### ISSUE THREAD

**Issue by vishwesh5** [tensorflow/tensorflow#27754]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): **Windows 10 - c5.nlarge AWS Instance**
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: **NA**
- TensorFlow installed from (source or binary): **Source**
- TensorFlow version: **r1.13** (Tried with **r.12** as well)
- Python version: **Python 3.6** (Conda)
- Installed using virtualenv? pip? conda?: **NA**
- Bazel version (if compiling from source): **0.19**
- GCC/Compiler version (if compiling from source): **Using Visual Studio 2017**
- CUDA/cuDNN version: **NA**
- GPU model and memory: **NA**

**Describe the problem**
I started off with the [instructions provided on TensorFlow page](https://www.tensorflow.org/install/source_windows), 

1. I installed Python 3.6 in PATH.
2. Installed Bazel 0.19 from Releases page. 
3. Installed Visual Studio 2017 since VS 2015 was not installing properly on Windows 10.
4. Installed the c++ build tools for VS 2017.
5. Installed MSYS2, and installed patch, unzip and git
6. Created the environment variables as specified in [Bazel documentation](https://docs.bazel.build/versions/master/windows.html#build-c)
```
C:\projects\bazel> bazel build //examples/cpp:hello-world

C:\projects\bazel> bazel-bin\examples\cpp\hello-world.exe
```
The above example worked fine. The paths I used were different.
7. Used git to clone tensorflow and then checked out **r1.13**
8. Used `python .\configure.py` [Log file](https://github.com/tensorflow/tensorflow/files/3069060/configure_log.txt)
9. Used `bazel build --config=opt //tensorflow/tools/pip_package:build_pip_package` [Log file]
(https://github.com/tensorflow/tensorflow/files/3069130/bazel_log.txt)

I have tried the following things as well but they have resulted in errors everytime:

```bazel build --config=opt --define=no_tensorflow_py_deps=true //tensorflow/tools/pip_package:build_pip_package

bazel build --config=opt --define=no_tensorflow_py_deps=true //tensorflow/tools/pip_package:build_pip_package

bazel build --config=opt --define=no_tensorflow_py_deps=true --local_resources 2048,.5,1.0 //tensorflow/tools/pip_package:build_pip_package```


I would appreciate any help regarding this.

**Comment by rootkitchao** [comment]
For the compilation of the CPU version, you can use CMAKE.In addition TF 1.13 needs to use MSVC 2015 update 3 compiler, MSVC2017 may have some problems.(see https://www.tensorflow.org/install/source_windows#tested_build_configurations)

**Comment by vishwesh5** [comment]
Thanks. I will try it out.
