### ISSUE TITLE
[Build error] TensorFlow Lite GPU delegate

### ISSUE THREAD

**Issue by jaebaek** [tensorflow/tensorflow#27757]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
    - Debian 4.19.20-1rodete1 (2019-02-12 > 2018) x86_64 GNU/Linux
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
    - Build for Android by adding the following code:
```
android_sdk_repository (
    name = "androidsdk",
    api_level = 26,
    build_tools_version = "26.0.2",
    path = "...",
)

android_ndk_repository(
    name = "androidndk",
    path = ".../android-ndk-r19c",
    api_level = 19,
)
```
- TensorFlow installed from (source or binary): source
- TensorFlow version: master, commit number 7bdb14a0b
- Python version: 2.7.16rc1
- Installed using virtualenv? pip? conda?: no
- Bazel version (if compiling from source): 0.24.1
- GCC/Compiler version (if compiling from source): Android (5058415 based on r339409) clang version 8.0.2
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

**Describe the problem**

Tried [TensorFlow Lite GPU delegate](https://www.tensorflow.org/lite/performance/gpu) and got a build error.

After adding the following code into WORKSPACE under tensorflow source code's root directory,
```
android_sdk_repository (
    name = "androidsdk",
    api_level = 26,
    build_tools_version = "26.0.2",
    path = "...",
)

android_ndk_repository(
    name = "androidndk",
    path = ".../android-ndk-r19c",
    api_level = 19,
)
```

I ran the following command:
```
bazel build --cxxopt=--std=c++11 //tensorflow/lite/java/demo/app/src/main:TfLiteCameraDemo
```

it reports:
```
bazel-out/android-armeabi-v7a-opt/bin/external/FP16/_virtual_includes/FP16/fp16.h:5:10: fatal error: 'fp16/fp16.h' file not found
#include <fp16/fp16.h>
         ^~~~~~~~~~~~~
1 error generated.
Target //tensorflow/lite/java/demo/app/src/main:TfLiteCameraDemo failed to build
```

**Provide the exact sequence of commands / steps that you executed before running into the problem**

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by impjdi** [comment]
Hm. When I add android_sdk_repository or android_ndk_repository, I would get something like:

ERROR: /usr/local/google/home/impjdi/src/tensorflow/WORKSPACE:160:1: Cannot redefine repository after any load statement in the WORKSPACE file (for repository 'androidsdk')
ERROR: /usr/local/google/home/impjdi/src/tensorflow/WORKSPACE:165:1: Cannot redefine repository after any load statement in the WORKSPACE file (for repository 'androidndk')
ERROR: Error evaluating WORKSPACE file

Then, when I remove, I get:

ERROR: /usr/local/google/home/impjdi/src/tensorflow/tensorflow/lite/java/demo/app/src/main/BUILD:7:1: no such package '@androidsdk//com.android.support': BUILD file not found on package path and referenced by '//tensorflow/lite/java/demo/app/src/main:TfLiteCameraDemo'
ERROR: /usr/local/google/home/impjdi/src/tensorflow/tensorflow/lite/java/demo/app/src/main/BUILD:7:1: no such package '@androidsdk//com.android.support': BUILD file not found on package path and referenced by '//tensorflow/lite/java/demo/app/src/main:TfLiteCameraDemo'
ERROR: Analysis of target '//tensorflow/lite/java/demo/app/src/main:TfLiteCameraDemo' failed; build aborted: no such package '@androidsdk//com.android.support': BUILD file not found on package path

However, I can build gl_delegate.  Can you give me finer instructions?  I think you and I are not in sync.

**Comment by freedomtan** [comment]
@jaebaek and @impjdi FYI. I can build apk with 'bazel build --cxxopt=--std=c++11 //tensorflow/lite/java/demo/app/src/main:TfLiteCameraDemo' on Ubuntu 18.04 and macOS without modification.

**Comment by impjdi** [comment]
@freedomtan 

Interesting.  Did you install Android Studio?

**Comment by freedomtan** [comment]
@impjdi I do have Android Studio installed, but usually I use standalone SDK and NDK, something like the following lines are in my `.tf_configure.bazelrc`
```
build --action_env ANDROID_NDK_HOME="/Users/freedom/work/android-ndk-r17b"
build --action_env ANDROID_NDK_API_LEVEL="28"
build --action_env ANDROID_BUILD_TOOLS_VERSION="28.0.3"
build --action_env ANDROID_SDK_API_LEVEL="28"
build --action_env ANDROID_SDK_HOME="/Users/freedom/work/android-sdk-mac_86"
```

**Comment by impjdi** [comment]
@jaebaek 

https://github.com/tensorflow/tensorflow/commit/bb530c6f82a06a8136042fccdd9456580f89f837

might have solved the issue.  Could you check?

**Comment by impjdi** [comment]
I just realized the commit I mentioned above does exactly what @jaebaek attempted to do in PR #27758.  Marking issue as closed.
