### ISSUE TITLE
ValueError: Provide an input shape for input array 'Placeholder'

### ISSUE THREAD

**Issue by BlueAnthony** [tensorflow/tensorflow#27753]
**System information**
- OS Platform and Distribution : Ubuntu 16.04
- TensorFlow installed from : conda install
- TensorFlow version : gpu-1.13.1
------------------------------------------------Error-------------------------------------------------------<
`File "convertpb2tflite.py", line 5, in <module>
    tflite_model=convert.convert()
File "/home/yuchen/anaconda2/envs/Conv-TasNet/lib/python3.6/site-packages/tensorflow/lite/python/lite.py", line 406, in ### ### convert
    "'{0}'.".format(_tensor_name(tensor)))
### **ValueError: Provide an input shape for input array 'Placeholder'.**
`

----------------------------------------------------My code----------------------------------------------------------<
I try to convert the model from [https://github.com/chaodengusc/DeWave](url) to tflite format.
And, the inference looks like this:
`p_keep_ff = tf.placeholder(tf.float32, shape=None)
p_keep_rc = tf.placeholder(tf.float32, shape=None)
in_data = tf.placeholder(tf.float32, shape=[batch_size, FRAMES_PER_SAMPLE, NEFF])
BiModel = Model(n_hidden, batch_size, p_keep_ff, p_keep_rc)
embedding = BiModel.inference(in_data)`

Then, I use this code to convert frozen.pb:
`convert= tf.lite.TFLiteConverter.from_frozen_graph("frozen.pb",input_arrays=["Placeholder","Placeholder_1","Placeholder_2"],output_arrays=["l2_normalize"],input_shapes={"Placeholder":None,"Placeholder_1":None,"Placeholder_2":[128, 100, 129]})
convert.post_training_quantize=True
tflite_model=convert.convert()
open("model.tflite","wb").write(tflite_model)`

-----------------------------------------------------MyQuestion--------------------------------------------------<
As above, original shape placeholder is none, how should I set the shape of Placeholder?
Thank you!!

**Comment by ymodak** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.

If you think we've misinterpreted a bug, please comment again with a clear explanation, as well as all of the information requested in the [issue template](https://github.com/tensorflow/tensorflow/issues/new/choose). Thanks!

**Comment by leiiiooo** [comment]
hello @ymodak  any answers? how you solve this question
