### ISSUE TITLE
Issue in code of image captioning notebook

### ISSUE THREAD

**Issue by ks-net-positive** [tensorflow/tensorflow#27759]
<em>Please make sure that this is a documentation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:doc_template</em>

**System information**
- TensorFlow version: Any
- Doc Link: https://github.com/tensorflow/docs/blob/master/site/en/r2/tutorials/sequences/image_captioning.ipynb

**Describe the documentation issue**
The code in this [cell](https://colab.research.google.com/github/tensorflow/docs/blob/master/site/en/r2/tutorials/sequences/image_captioning.ipynb#scrollTo=uEWM9xrYcg45) which sets `vocab_size = len(tokenizer.word_index) + 1` is wrong. `vocab_size` is set to `8235+1`, but actually needs to be set to `5000+1`, as `top_k = 5000`

**We welcome contributions by users. Will you be able to update submit a PR (use the [doc style guide](https://www.tensorflow.org/community/documentation)) to fix the doc Issue?** Yes

**Comment by ymodak** [comment]
The doc link you provided is incorrect. Can you please point to the correct one? Thanks!

**Comment by ymodak** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
