### ISSUE TITLE
TFLite Toco unable to fully quantize (QUANTIZED_UINT8) graph with unpack/unstack

### ISSUE THREAD

**Issue by TF-Deve** [tensorflow/tensorflow#27760]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):  No.
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): Using Tensorflow in Anaconda
- TensorFlow version (use command below): 1.12.0, 1.13.1, tf-nightly
- Python version: 3.6.xxx

**Describe the current behavior**
I have a quantization-aware trained static rnn LSTM, with unstack. I used TFLiteLSTMCell defined in this file: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/experimental/examples/lstm/rnn_cell.py
I manually inserted fake quant nodes in the graph and generated a .pb file.
When I want to convert my .pb file to .tflite model in toco with "converter.inference_type = tf.contrib.lite.constants.QUANTIZED_UINT8"
I got this error below:
F tensorflow/contrib/lite/toco/graph_transformations/quantize.cc:474] Unimplemented: this graph contains an operator of type Unpack for which the quantized form is not yet implemented. Sorry, and patches welcome (that's a relatively fun patch to write, mostly providing the actual quantized arithmetic code for this op).\nAborted (core dumped)

**Describe the expected behavior**
Expectation: The graph can be convert to .tflite file. 

**Code to reproduce the issue**
I have my .pb file attached below:
[my_frozen_graph.zip](https://github.com/tensorflow/tensorflow/files/3069858/my_frozen_graph.zip)

My toco code below to regenerate the error:
`graph_def_file = "my_frozen_graph.pb"     # This is the .pb file.
input_arrays = ["Reshape_1"]        # This is the name of the input node
output_arrays = ["labels_softmax"]  # This is the name of the ouput node

converter = tf.contrib.lite.TFLiteConverter.from_frozen_graph(graph_def_file, input_arrays, output_arrays)
converter.inference_type = tf.contrib.lite.constants.QUANTIZED_UINT8
input_arrays = converter.get_input_arrays()
converter.quantized_input_stats = {input_arrays[0] : (227., 0.92)}  # mean, std_dev
tflite_model = converter.convert()
open("static_rnn_with_unstack.tflite", "wb").write(tflite_model)   # The resulting .tflite file.`

**Other info / logs**
As asked by @jdduke , I filled this issue. Thanks in advance.

**Comment by jdduke** [comment]
@alanchiao any thoughts on adding this? Should be straightforward, and we already support pack.

**Comment by ANSHUMAN87** [comment]
@jdduke , @alanchiao : I have uploaded PR for this issue, please check, Thanks!
