### ISSUE TITLE
TensorFlow : Machine Translation example Segmentation fault (Core dumped)

### ISSUE THREAD

**Issue by suraj1990** [tensorflow/tensorflow#2776]
![cuda](https://cloud.githubusercontent.com/assets/5551707/15954993/e761dda4-2efa-11e6-8d70-a36a8ad02239.png)
GitHub issues are for bugs / installation problems / feature requests.  
For general support from the community, see [StackOverflow](https://stackoverflow.com/questions/tagged/tensorflow).
To make bugs and feature requests more easy to find and organize, we close issues that are deemed
out of scope for GitHub Issues and point people to StackOverflow.

For bugs or installation issues, please provide the following information.
The more information you provide, the more easily we will be able to offer
help and advice.

### Environment info
Operating System: AWS X2-large GPU instance. Ubuntu

Installed version of CUDA 7.5 and cuDNN: 7.5.18
(please attach the output of `ls -l /path/to/cuda/lib/libcud*`):

If installed from binary pip package, provide:

1. Which pip package you installed.
2. The output from `python -c "import tensorflow; print(tensorflow.__version__)"`. - 0.8.0

If installed from sources, provide the commit hash:

### Steps to reproduce
1. Running the translate.py script from tensorflow/modles/rnn/translate path
2. It downloads the files, unzip's the files
3. prepares the data - > creates the vocabulary for English and French data -> tockenizes the data -> train_set = read_data(en_train, fr_train, FLAGS.max_train_data_size) 
4. In train_set = read_data(en_train, fr_train, FLAGS.max_train_data_size) there is a crash bacause of out of memory.

### What have you tried?
1. Tried to give smaller batch size. varied from 32,64 ...512

### log
segmentation fault(core dumped)
I tried to run gdb and when I back traced I found this
PyObject_Malloc (nbytes=<optimized out) at ../objects/obmalloc.c 934

How can I run Machine Translation example on a smaller dataset.

### Logs or other output that would be helpful
(If logs are large, please upload as attachment).

**Comment by girving** [comment]
This sounds like a system configuration issue with either Python or CUDA, especially the bit where PyObject_Malloc crashes.  Do you have multiple versions of Python installed on your machine?  What information did you give to configure?

**Comment by ebrevdo** [comment]
It would also be good if you could run "thread all apply backtrace" -- would be good to see where the TensorFlow C++ code is when you get the malloc failure.

**Comment by suraj1990** [comment]
I understood from this thread https://github.com/tensorflow/tensorflow/issues/600#issuecomment-225301315 that the crash is because of my RAM size. I see that my RAM is not sufficient to load full training data. i.e 22M sentences. So as suggested in the link, I am currently setting  max_train_data_size to 10M or which ever value your RAM can handle. It runs fine.

**Comment by sirgogo** [comment]
Similar problem here, albeit different network. I'm not training on a GPU, but my machine has 64gb RAM. I have to adjust the batch size, or else I get a` Segmentation fault (core dumped)` error on the optimizer (backprop) step.

However, monitoring the RAM usage (e.g. htop), it never crawls above 4GB. So I am inclined to believe this is a bug with tensorflow overestimating the memory required. Backprop should scale linearly with the batch size, and I am seeing this until it faults at an arbitrary point.

Any ideas?! This is severely limiting my ability to train large models. Using a small batch size is just not going to cut it! -- the estimation of the gradient direction is very poor for large models if the batch size is too small.

**Comment by girving** [comment]
@sirgogo Please file a new issue.  You are training on CPU rather than GPU, and this one was closed on June 15.
