### ISSUE TITLE
Unable to convert fine-tuned model to tflite model

### ISSUE THREAD

**Issue by Single430** [tensorflow/tensorflow#27765]
**System information**
- Linux Ubuntu 18.04:
- pip:
- tensorflow==1.13.1:

**CMD**

```bash
bazel-bin/tensorflow/lite/toco/toco \
--input_file=../output/ner_model.pb \
--output_file=../output/ner_model.tflite \
--input_format=TENSORFLOW_GRAPHDEF \
--output_format=TFLITE \
--inference_type=QUANTIZED_UINT8 \
--input_shapes=1,512:1,512 \
--input_arrays=input_ids,input_mask \
--output_arrays=pred_ids \
--default_ranges_min=0 --default_ranges_max=512 \
--allow_custom_ops
```

**Provide the text output from tflite_convert**

```
Constant array bert/embeddings/word_embeddings lacks MinMax information. To make up for that, we will now compute the MinMax from actual array elements. That will result in quantization parameters that probably do not match whichever arithmetic was used during training, and thus will probably be a cause of poor inference accuracy.
Unimplemented: this graph contains an operator of type OneHot for which the quantized form is not yet implemented. Sorry, and patches welcome (that's a relatively fun patch to write, mostly providing the actual quantized arithmetic code for this op).
```

Also, please include a link to a GraphDef or the model if possible.

**Any other info / logs**

```bash
bazel-bin/tensorflow/tools/graph_transforms/summarize_graph \
--in_graph=../output/ner_model.pb
```

**output**

```
Found 2 possible inputs: (name=input_ids, type=int32(3), shape=[?,512]) (name=input_mask, type=int32(3), shape=[?,512]) 
No variables spotted.
Found 1 possible outputs: (name=pred_ids, op=Identity) 
Found 101686282 (101.69M) const parameters, 0 (0) variable parameters, and 18 control_edges
Op types used: 683 Const, 214 Identity, 136 Mul, 106 Add, 74 MatMul, 73 BiasAdd, 57 Reshape, 57 Pack, 52 Transpose, 50 Mean, 38 Sub, 25 StopGradient, 25 SquaredDifference, 25 Rsqrt, 24 BatchMatMul, 23 Enter, 19 ExpandDims, 16 Shape, 14 StridedSlice, 12 Sqrt, 12 Softmax, 12 RealDiv, 12 Erf, 9 Range, 8 Switch, 8 NextIteration, 8 Merge, 7 ConcatV2, 4 TensorArrayV3, 4 Select, 4 Fill, 4 Less, 3 Assert, 3 Exit, 3 Slice, 3 Squeeze, 3 All, 3 Cast, 3 Max, 3 Maximum, 2 TensorArraySizeV3, 2 TensorArrayScatterV3, 2 TensorArrayReadV3, 2 ReverseSequence, 2 TensorArrayGatherV3, 2 TensorArrayWriteV3, 2 ArgMax, 2 Equal, 2 Placeholder, 2 Minimum, 2 LoopCond, 2 LogicalAnd, 2 GreaterEqual, 1 Sign, 1 OneHot, 1 Sum, 1 Abs, 1 Tanh, 1 LessEqual, 1 GatherV2, 1 GatherNd
```

**Comment by amitsrivastava78** [comment]
@Single430 , try to provide --mean_values & --std_dev_values along with QUANTIZED_UINT8 and let me know if you succeed.

Regards
Amit

**Comment by Single430** [comment]
@amitsrivastava78  Thank you very much for your reply, but how do I fill in the values of --mean_values and --std_values?

**Comment by amitsrivastava78** [comment]
@Single430 for starter you can fill below values 
--mean_values=128 
--std_dev_values=127

If it works you can read the documentation for more details

Regards
Amit

**Comment by Single430** [comment]
`ERROR:  2019-04-25 09:43:00.214538: F tensorflow/lite/toco/model_cmdline_flags.cc:263] Check failed: mean_values.size() == model_flags->input_arrays_size()`

I don't know how to solve it. @amitsrivastava78 　　thanks you.

**Comment by amitsrivastava78** [comment]
@Single430 , sorry for the oversight, i just mixed up the issues, I saw your log and it clearly says following : - 

 _Unimplemented: this graph contains an operator of type OneHot for which the quantized form is not yet implemented. Sorry, and patches welcome (that's a relatively fun patch to write, mostly providing the actual quantized arithmetic code for this op)._


Problem is quantize version of onehot vector is not supported by TFlite, 

@suharshs  whats your take on this ? Shall i go ahead and raise the PR for the same ?

@Single430 : - Will take the further action once @suharshs gives a go.

Regards
Amit

**Comment by amitsrivastava78** [comment]
@Single430 , i think @suharshs is yet to respond in the mean time, can you upload the model file which has this quantized version of OneHot, I will try to verify my implementation against this model and send you the PR which can solve this problem.

Regards
Amit

**Comment by Single430** [comment]
@amitsrivastava78     I uploaded the pb file, please let me know if you need other files.  
 This is a model for Chinese entity recognition.
https://drive.google.com/file/d/1vZNpt5tcqfivQFRfLrtApMwIoURxmYCy/view?usp=sharing

**Comment by suharshs** [comment]
thanks, yes sg to go ahead with a onehot impl. in addition to the kernel, you will likely need to add new hardcode rule in this file:
https://github.com/rockchip-linux/tensorflow/blob/master/tensorflow/contrib/lite/toco/graph_transformations/hardcode_min_max.cc
Since the range of onehot should be hardcoded [0, 1].

Thanks!

**Comment by amitsrivastava78** [comment]
@suharshs , thanks for the response and for pointing me into the right direction, i have raised the PR for the same. Kindly review.

@Single430 , it might take some time for the PR to merge, till then use this for your testing and post the results here.

Regards
Amit

**Comment by ymodak** [comment]
Please test with latest version of TF and reopen the issue if it still exists. Thank you.

**Comment by TianHongZXY** [comment]
@Single430  hello, how did you solve the problem of unsupported op BatchMatMul?
