### ISSUE TITLE
linux build tensorflow c++ API error

### ISSUE THREAD

**Issue by laiqb** [tensorflow/tensorflow#27778]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): centos7
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: no
- TensorFlow installed from (source or binary): source
- TensorFlow version: 1.9
- Python version: python3
- Installed using virtualenv? pip? conda?: no
- Bazel version (if compiling from source):0.11.0- (@non-git) 
- GCC/Compiler version (if compiling from source): gcc 4.8
- CUDA/cuDNN version: no
- GPU model and memory: no

**Describe the problem**

**Provide the exact sequence of commands / steps that you executed before running into the problem**
how to solve the error. thanks. which version is stable
1. tensorflow/contrib/makefile/build_all_linux.sh 
2. ./configure
3. bazel build --config=opt //tensorflow:libtensorflow_cc.so.
show Info:
[root@192 tensorflow]# bazel build --config=opt //tensorflow:libtensorflow_cc.so
WARNING: Config values are not defined in any .rc file: opt
WARNING: /root/.cache/bazel/_bazel_root/efb88f6336d9c4a18216fb94287b8d97/external/protobuf_archive/WORKSPACE:1: Workspace name in /root/.cache/bazel/_bazel_root/efb88f6336d9c4a18216fb94287b8d97/external/protobuf_archive/WORKSPACE (@com_google_protobuf) does not match the name given in the repository's definition (@protobuf_archive); this will cause a build error in future versions
ERROR: /root/tensorflow/tensorflow/core/platform/default/build_config/BUILD:153:1: no such package '@png_archive//': Traceback (most recent call last):
	File "/root/tensorflow/third_party/repo.bzl", line 88
		_apply_patch(ctx, ctx.attr.patch_file)
	File "/root/tensorflow/third_party/repo.bzl", line 56, in _apply_patch
		fail("patch command is not found, ple...")
patch command is not found, please install it and referenced by '//tensorflow/core/platform/default/build_config:platformlib'
ERROR: Analysis of target '//tensorflow:libtensorflow_cc.so' failed; build aborted: no such package '@png_archive//': Traceback (most recent call last):
	File "/root/tensorflow/third_party/repo.bzl", line 88
		_apply_patch(ctx, ctx.attr.patch_file)
	File "/root/tensorflow/third_party/repo.bzl", line 56, in _apply_patch
		fail("patch command is not found, ple...")
patch command is not found, please install it
INFO: Elapsed time: 27.651s
FAILED: Build did NOT complete successfully (40 packages loaded)

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

bazel version
[root@192 bazel-0.11]# bazel version
Build label: 0.11.0- (@non-git)
Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Thu Apr 24 19:52:56 +51264 (1555578330776)
Build timestamp: 1555578330776
Build timestamp as int: 1555578330776

**Comment by wdirons** [comment]
Bazel version 0.24.0 will not work with TensorFlow 1.9.

Use bazel version 0.11.0 or 0.10.0 to build tensorflow 1.9.

Reference this page to find which bazel to use for which tensorflow version:
https://www.tensorflow.org/install/source

**Comment by laiqb** [comment]
@wdirons @ymodak it is not work. the information updated

**Comment by wdirons** [comment]
@laiqb , the error now in the above message is

> patch command is not found, please install it 

`yum install patch` should resolve that issue.

**Comment by laiqb** [comment]
@wdirons it works. thanks
