### ISSUE TITLE
Isn't current tensorflow-git r0.9? 

### ISSUE THREAD

**Issue by jiapei100** [tensorflow/tensorflow#2778]
### Environment info
Operating System: Ubuntu 16.04

Installed version of CUDA and cuDNN: 
cuda 7.5
cudnn 5.0.5

Build from source, tensorflow-git-master

Just use bazel to build tensorflow, which built out a version 0.8.0, instead of 0.9.0 ....

Shouldn't current git master build out 0.9.0, instead of 0.8.0?

Cheers
Pei

**Comment by yaroslavvb** [comment]
Building from master builds "head" which is newer than 0.9.0

**Comment by jiapei100** [comment]
@yaroslavvb 
Weird that I just git clone tensorflow, and have it built with bazel 3.0.0, only tensorflow-0.8.0 has been built out....

**Comment by yaroslavvb** [comment]
All the binaries you build should be build at version "head" where do u see
0.8?

**Comment by jiapei100** [comment]
@yaroslavvb 
Do you mean this?
```
jiapei@jiapei-GT72-6QE:~/Downloads/machinelearning/deeplearning/tensorflow$ cat .git/HEAD
ref: refs/heads/master
jiapei@jiapei-GT72-6QE:~/Downloads/machinelearning/deeplearning/tensorflow$ cat .git/refs/heads/master 
6431560b7ec3565154cb9cdc9c827db78ccfebe7
```

**Comment by girving** [comment]
@jiapei100 The source version will say 0.8 until we release 0.9; currently we're at 0.9.0rc0 < 0.9.
