### ISSUE TITLE
How to's fully_connected_reader.py raises an AttributeError

### ISSUE THREAD

**Issue by aaronlelevier** [tensorflow/tensorflow#27785]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution: Mac OSX
- Mobile device: No
- TensorFlow installed from (source or binary): pip installed
- TensorFlow version: `tensorflow==1.12.0`
- Python version: Python 2.7.16
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: no
- GPU model and memory: no

You can collect some of this information using our environment capture [script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with
python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"

`('v1.12.0-rc2-3-ga6d8ffae09', '1.12.0')`

**Describe the current behavior**

When running this how to script:

https://github.com/tensorflow/tensorflow/blob/master/tensorflow/examples/how_tos/reading_data/fully_connected_reader.py

An `AttributeError` is raised

```
Traceback (most recent call last):
  File "fully_connected_reader.py", line 218, in <module>
    tf.app.run(main=main, argv=[sys.argv[0]] + unparsed)
  File "/Users/aaron/Documents/github/tfx/venv/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "fully_connected_reader.py", line 186, in main
    run_training()
  File "fully_connected_reader.py", line 140, in run_training
    train=True, batch_size=FLAGS.batch_size, num_epochs=FLAGS.num_epochs)
  File "fully_connected_reader.py", line 129, in inputs
    iterator = tf.compat.v1.data.make_one_shot_iterator(dataset)
AttributeError: 'module' object has no attribute 'v1'
```

**Describe the expected behavior**

Code should run without error in the "how to"

**Code to reproduce the issue**

Call the Python file with `tf` installed

```
python fully_connected_reader.py
```

**To fix**

To fix this error, I changed `line 129` from:

```
iterator = tf.compat.v1.data.make_one_shot_iterator(dataset)
```

to:

```
iterator = tf.data.Dataset.make_one_shot_iterator(dataset)
```

**Comment by ymodak** [comment]
The example has been updated to support latest version of TF. ```tf.compat.v1.data.make_one_shot_iterator``` is correct for 2.0 compatibility. The [master branch example](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/examples/how_tos/reading_data/fully_connected_reader.py)should pass in TF 1.13.1
You can also try [TF 1.12 branch example](https://github.com/tensorflow/tensorflow/blob/r1.12/tensorflow/examples/how_tos/reading_data/fully_connected_reader.py) for your case.
