### ISSUE TITLE
Provide a working example involving reading csv data

### ISSUE THREAD

**Issue by demongolem** [tensorflow/tensorflow#278]
I have successfully read in csv data.  I have successfully trained/classified using the mnist data utility.  But I have not successfully been able to train from csv data.

It would also be helpful to clarify pack vs concat which is done on at StackOverflow for a given question but is left unexplained on the tensorflow site.

**Comment by toddpi314** [comment]
Agreed here. 

Anyone at 10+ hours of lib usage will figure out the simplicity of the data pipeline, but for people rolling through the tutorial, it would be helpful to have at least one sample batch-importer for a few other popular data formats.

**Comment by josh11b** [comment]
https://www.tensorflow.org/versions/master/how_tos/reading_data/index.html#csv-files
is what we have now.  Is there a standard data set that comes in CSV format?

**Comment by demongolem** [comment]
Isn't Fisher's iris data set available in csv?  I would think that this
would be good for demonstration purposes in this case.

**Comment by b0noI** [comment]
I would like to help with this one.

**Comment by gunan** [comment]
https://www.tensorflow.org/versions/master/how_tos/reading_data/#csv-files

Is this sufficient to close this issue?

**Comment by toddpi314** [comment]
Well done. This is very clear.

**Comment by hdon** [comment]
Just an FYI, this was Google search result #5 for me when I searched `tensorflow classification csv` but the link you guys mention is a 404.

**Comment by gunan** [comment]
The guide has moved to this page:
https://www.tensorflow.org/programmers_guide/reading_data

**Comment by noamaig** [comment]
Another FYI  the updated link gunan mentioned in his last reply to hdon doesn't contain the word "csv" at all.

**Comment by DollarAkshay** [comment]
@noamaig I found one example here : https://www.tensorflow.org/get_started/datasets_quickstart#build_a_csv_line_parser

Just type CSV in the tensorflow website search bar

**Comment by josh11b** [comment]
@rachellim

**Comment by lpere** [comment]
I am a C/C++ programmer who wanted to play with tf, not cats, not puppies, but let's say a set of strings and floats. I googled the csv and tf for hours, what I found is 1) a lot of talk about what a neuron and what the meaning of the word "deep". Then 2) a lot of hugely complicated python programs with flowers and such, using data I don't want. And some 3) short and incomplete or 4) long and complicated documents that does not say how to define a simple network, read the data from a txt file and print the results.

It is extremely frustrating.

**Comment by rachellim** [comment]
@lpere -- thanks for sharing about your experience, and sorry to hear it was frustrating. When I google "tensorflow csv data", the second result I get is ["Importing Data | TensorFlow" ](https://www.tensorflow.org/guide/datasets) [Note that if you click on the first result, "Reading data", there is a link on a page to "Importing data" too]. On the "Importing Data" page, there is a section for "Consuming CSV data" that I added on May 18. Does this fit your needs? If not, let me know I can improve the documentation there.

**Comment by zsoltszakaly** [comment]
Though it is a very old issue, this is still the one brought up when one googles for loading a CSV file in TF through C++ (along with an unanswered SO question).
It would be great to see an example of reading a CSV file just with the raw operations. I can read a file with ReadFile and the result is a dimensionless string tensor with the whole content in one cell. I can also decode a CSV content into tensors representing the columns with DecodeCSV if the input is a 1-dimension string tensor with one input line being one string cell (and no header). What I cannot do, cannot find is a raw operation that makes a 1D string tensor from the 0D string removing the header and splitting it into lines/cells.
Is there a documentation for this?
(I tried to ask for support on SO but in general there is hardly any support for raw operations - sorry).
