### ISSUE TITLE
Can't import tensorflow 2.0-alpha on win10 python=3.6.8

### ISSUE THREAD

**Issue by StudyExchange** [tensorflow/tensorflow#27809]
**System information**
- OS Platform and Distribution: ```Win10```
- TensorFlow installed from (source or binary): ```pip install tensorflow==2.0.0-alpha0```
- TensorFlow version: ```tensorflow 2.0.0a0```
- Python version: ```Python 3.6.8 :: Anaconda, Inc.```
- Installed using virtualenv? pip? conda?: ```Anaconda pip```

**Describe the problem**
1. Run ```python``` at anaconda prompt, start python runtime.
2. Run ```import tensorflow```, get error as below:
```
>>> import tensorflow
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'tensorflow'
```

**Comment by gadagashwini** [comment]
@StudyExchange, Please do confirm, whether the tensorflow is installed at Anaconda prompt or outside the anaconda. Thanks!

**Comment by StudyExchange** [comment]
Tensorflow is installed at Anaconda Prompt!
```
(base) C:\Users\username>activate tf2
(tf2) C:\Users\username>python
Python 3.6.8 |Anaconda, Inc.| (default, Feb 21 2019, 18:30:04) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'tensorflow'
>>>
```

**Comment by gadagashwini** [comment]
@StudyExchange You need to add sub folders: bin and lib to the path. Thanks!

**Comment by StudyExchange** [comment]
I created bin and lib at project folder, but don't work!
```
(base) D:\>mkdir tf2_demo

(base) D:\>cd tf2_demo

(base) D:\tf2_demo>activate tf2

(tf2) D:\tf2_demo>mkdir bin lib

(tf2) D:\tf2_demo>dir
 驱动器 D 中的卷是 新加卷
 卷的序列号是 169B-ACE3

 D:\tf2_demo 的目录

2019/04/16  20:27    <DIR>          .
2019/04/16  20:27    <DIR>          ..
2019/04/16  20:27    <DIR>          bin
2019/04/16  20:27    <DIR>          lib
               0 个文件              0 字节
               4 个目录 53,466,030,080 可用字节

(tf2) D:\tf2_demo>python
Python 3.6.8 |Anaconda, Inc.| (default, Feb 21 2019, 18:30:04) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'tensorflow'
>>>
```

**Comment by ymodak** [comment]
You need to install the Microsoft Visual C++ 2015 Redistributable Update 3.
https://www.tensorflow.org/install/pip#1.-install-the-python-development-environment-on-your-system

**Comment by StudyExchange** [comment]
It work by installing the Microsoft Visual C++ 2015 Redistributable Update 3, thank you!
