### ISSUE TITLE
Potential Contribution: Ansible roles & playbooks

### ISSUE THREAD

**Issue by kuza55** [tensorflow/tensorflow#2780]
I've been running tensorflow on ec2 spot instances rather than buying a GPU, and I've written a few ansible playbooks to make this easier given spot instances go down, etc.

I split the base software out into two separate Ansible roles, one for CUDA/cuDNN: (For those unfamiliar with Ansible, the meat is in blob/master/tasks/main.yml)
https://github.com/kuza55/ansible-cudnn
And one for Bazel/TensorFlow:
https://github.com/kuza55/ansible-tensorflow

I've also got a playbook for baking an ec2 AMI from these, and for setting up more AWS-specific things, which I'll open source after I figure out how they should be structured that isn't super specific to all of my ec2 settings.

One thing I haven't done, but may be of interest, is to put together a playbook for setting up a tensorflow cluster and then doing some distributed training.

Let me know if there is any interest in accepting these and linking to them from somewhere (it takes people a while to realize there's a lot of good stuff in the contrib directory).

I'll probably try and submit these to Ansible Galaxy in the hopes people can find it more easily in either case.

**Comment by andydavis1** [comment]
This sounds like a useful contribution. We would be happy to link to this on the community section of our resource page. Could send a pull request to add this link?

**Comment by aselle** [comment]
Automatically closing due to lack of recent activity. Please reopen when further information becomes available.

**Comment by kuza55** [comment]
So, I made some example playbooks that use these roles: https://github.com/kuza55/ansible-examples/tree/master/tensorflow

I also ended up writing up detailed instructions on how to use the playbooks I open sourced: https://medium.com/@kuza55/deep-learning-in-the-cloud-tensorflow-on-ec2-spot-instances-with-ansible-554ef7f59423#.ii8f4st5t

Would it be appropriate to link the Medium post in the community section?

**Comment by aselle** [comment]
@martinwicke, Could we add a link somewhere to this in the ocmmunity section?

**Comment by martinwicke** [comment]
I think we should link to both from the resource/community section. Make a PR with the change to add it to the list?

**Comment by michaelisard** [comment]
@kuza55 would you make a PR to add links from the resource and community sections? Thanks!

**Comment by aselle** [comment]
Automatically closing due to lack of recent activity. Please reopen when new information becomes available.
