### ISSUE TITLE
NNAPI doesn't support tensors with rank 0 (index 3 name PadV2/constant_values)

### ISSUE THREAD

**Issue by RoyIronGrey** [tensorflow/tensorflow#27807]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- OS Platform and Distribution : Windows 10 and Android 9.0
- Mobile device : Xiaomi 8
- TensorFlow version : org.tensorflow:tensorflow-lite:0.0.0-nightly (using 1.11.0 has the same problem)
- Model: resnet18 convert from Pytorch 

**logs from Android 9.0**
E/tflite: NNAPI doesn't support tensors with rank 0 (index 3 name PadV2/constant_values)
E/tflite: Returning error since TFLite returned failure nnapi_delegate.cc:736.
    Failed to build graph for NNAPI

**other**
if I use resnet50 from tensorflow.contrib.slim.python.slim.nets, it also has similar problem like:
E/tflite: NNAPI doesn't support tensors with rank 0 (index 7 name inference_model/Mean/reduction_indices)
    Returning error since TFLite returned failure nnapi_delegate.cc:736.
    Failed to build graph for NNAPI

**Comment by muddham** [comment]
@RoyIronGrey In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thanks!

**Comment by RoyIronGrey** [comment]
> @RoyIronGrey In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thanks!
```java
protected Interpreter tflite;
private Interpreter.Options tfliteOptions = new Interpreter.Options();

tfliteModel = loadModelFile(activity);

/** This is for tensorflow-lite:0.0.0-nightly **/
/** If I activate this option, the error like the title will occur**/
tfliteOptions.setUseNNAPI(true);

tflite = new Interpreter(tfliteModel, tfliteOptions);

protected String getModelPath() {
      return "resnet18_mv.tflite";
} 
```

Below is Python Code and Script to describe how to get the model
```python
'''
  Package Version
    torch:       0.4.0
    torchvision: 0.2.1
    tensorflow:  1.12.0
    mmdnn:       0.2.4
'''

'''
  Part 1: Pytorch resnet18 saving
'''

# Resnet18 model from torchvision
base_model = getattr(torchvision.models, 'resnet18')(pretrained=True)

# Load weights
weights    = 'resnet18_model_checkpoint.pth.tar'
checkpoint = torch.load(weights)
base_dict  = {'.'.join(k.split('.')[1:]): v for k,v in list(checkpoint['state_dict'].items())}
base_model.load_state_dict(base_dict)
base_model.eval()

# Save model
model_path = 'resnet18_model.pth'
torch.save(base_model, model_path)
```

```script
'''
  Part 2: Resnet18 from Pytorch (.pth) to Tensorflow (.pb) with MMdnn
          See https://github.com/Microsoft/MMdnn/blob/master/mmdnn/conversion/pytorch/README.md#convert-pytorch-pre-trained-models-to-ir
'''

mmtoir -f pytorch -d resnet18 --inputShape 3,224,224 -n resnet18_model.pth
mmtocode -f tensorflow --IRModelPath resnet18.pb --IRWeightPath resnet18.npy --dstModelPath tf_resnet18.py
mmtomodel -f tensorflow -in tf_resnet18.py -iw resnet18.npy -o tf_resnet18 --dump_tag SERVING
```

```python
'''
  Part 3: Tensorflow (.pb) to Tensorflow Lite (.lite) with TFLiteConverter.from_session
'''

with tf.Session() as sess:

    mmdnn_pb_path = 'tf_resnet18/'

    # Load pb model file (MMdnn, see https://github.com/Microsoft/MMdnn/blob/master/mmdnn/conversion/tensorflow/README.md#reuse-the-converted-tensorflow-model)
    tf.saved_model.loader.load(sess, [tf.saved_model.tag_constants.SERVING], mmdnn_pb_path)

    input_node_name  = 'input'
    output_node_name = 'dense/BiasAdd'
    input_tensor     = sess.graph.get_tensor_by_name(input_node_name  + ':0')   # Input tensor
    output_tensor    = sess.graph.get_tensor_by_name(output_node_name + ':0')   # Logits tensor

    # Convert
    converter        = tf.contrib.lite.TFLiteConverter.from_session(sess, [input_tensor], [output_tensor])
    tflite_model     = converter.convert()

    open('tf_resnet18.tflite', "wb").write(tflite_model)
```

**Comment by RoyIronGrey** [comment]
> @RoyIronGrey In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thanks!

And Thanks for your attention!

**Comment by jdduke** [comment]
@miaowang14 can you provide an update on scalar support?

**Comment by miaowang14** [comment]
I have a pending fix internally, and will further test / improve it. Looking forward to get it ready for the next couple of days.

**Comment by miaowang14** [comment]
@RoyIronGrey is the issue still reproducible on top of tree?

**Comment by RoyIronGrey** [comment]
> @RoyIronGrey is the issue still reproducible on top of tree?

Thanks for your reply. Yes, If I use the same edition of TF lite API. Is there anything new or any new edition for this problem?

**Comment by RoyIronGrey** [comment]
> @RoyIronGrey is the issue still reproducible on top of tree?

Or I may misunderstand what you mean

**Comment by miaowang14** [comment]
@RoyIronGrey We just submitted a couple of fixes related to this issue. I don't think tensorflow-lite:0.0.0-nightly or 1.11.0 build include them.

You might be able to build TFLite binaries from source and try it out: https://www.tensorflow.org/lite/guide/build_arm64

**Comment by jdduke** [comment]
The nightly should have the fixes, but you might need to [clear your gradle cache](https://stackoverflow.com/questions/23025433/how-to-clear-gradle-cache).

**Comment by RoyIronGrey** [comment]
> The nightly should have the fixes, but you might need to [clear your gradle cache](https://stackoverflow.com/questions/23025433/how-to-clear-gradle-cache).
Yes, It works. But why does it cost more time and unsteady?(Maybe I made some mistakes)
Below it's the difference
```java
     //If set useNNAPI true
     tfliteOptions.setUseNNAPI(true);
     //time from Log
     infer mv/frame: 375 ms
     infer mv/frame: 175 ms
     infer mv/frame: 516 ms
```
```java
     //If set useNNAPI false
     tfliteOptions.setUseNNAPI(false);
     //time from Log
     infer mv/frame: 100 ms
     infer mv/frame: 87 ms
```

**Comment by miaowang14** [comment]
I guess the performance issues could be related two possible causes:
1. There are still operations in the Model not supported by NNAPI, so they fallback to TFLite CPU implementation. The overhead and sync cost between multiple subgraphs  could be high.
2. The model itself is a floating point model, while Mi8 may just have an hardware accelerator (Hexagon DSP) that can only accelerate quantized 8bit models.

**Comment by miaowang14** [comment]
I will mark this specific issue as fixed. But feel free to keep comment on it or create new ones if you have questions about the performance and NNAPI delegate.

**Comment by RoyIronGrey** [comment]
> I will mark this specific issue as fixed. But feel free to keep comment on it or create new ones if you have questions about the performance and NNAPI delegate.

Thanks a lot! I'll stay focus on the processing of this project as it really supports my research
