### ISSUE TITLE
cannot import _mklinit

### ISSUE THREAD

**Issue by hiepnguyen034** [tensorflow/tensorflow#27808]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- Windows 10
- TensorFlow installed from pip install tensorflow-gpu
- TensorFlow version: 1.13.1
- Python version: 3.7.3
- Installed using virtualenv? pip? conda?: pip
- CUDA/cuDNN version: 9.0
- GPU model and memory: GTX 970M- 3GB

**Describe the problem**
I accidentally deleted Anaconda3 in my home directory so I installed Anaconda again and things started to fall apart. Before that, everything worked perfectly with tensorflow 1.9, pthon 3.6.4, and CUDA 9.0
**Provide the exact sequence of commands / steps that you executed before running into the problem**
```
import tensorflow as tf
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Hiep Nguyen\Anaconda3\lib\site-packages\tensorflow\__init__.py", line 24, in <mo
dule>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "C:\Users\Hiep Nguyen\Anaconda3\lib\site-packages\tensorflow\python\__init__.py", line 47,
 in <module>
    import numpy as np
  File "C:\Users\Hiep Nguyen\Anaconda3\lib\site-packages\numpy\__init__.py", line 140, in <module
>
    from . import _distributor_init
  File "C:\Users\Hiep Nguyen\Anaconda3\lib\site-packages\numpy\_distributor_init.py", line 34, in
 <module>
    from . import _mklinit
  ImportError: DLL load failed: The specified module could not be found.
```

**Comment by hiepnguyen034** [comment]
It is actually a conda-related problem. I did not activate the environment before importing tensorflow.

**Comment by zenetio** [comment]
I am using Anaconda3, Python 3.6 and was facing the same issue. I fixed it doing 
pip install numpy==1.17.5
