### ISSUE TITLE
Differential (Delta) Model Update

### ISSUE THREAD

**Issue by MentalGear** [tensorflow/tensorflow#27815]
I'm new to tensorflow. My area of usage would be on device execution for item recognition.
As my use case requires frequent updates on the items to recognize, I was wondering if it is possible to update models in a delta way, e.g. to only transfer the updated data and not the whole model each time.

**Comment by gadagashwini** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged//tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.
Thanks!

**Comment by MentalGear** [comment]
Well, it would be a feature request if this functionality isn’t available yet. :P

**Comment by gadagashwini** [comment]
@MentalGear, Tensorflow supports save and restore model. Please find tutorial in this [link](https://www.tensorflow.org/tutorials/keras/save_and_restore_models) which help you to save model and restore. Thanks!

**Comment by MentalGear** [comment]
Well, my feature request was about a more efficient transfer of a model for offline use, not save and restore operations.

**Comment by ymodak** [comment]
@MentalGear Can you please fill the [feature request](https://github.com/tensorflow/tensorflow/issues/new?template=30-feature-request.md) issue template and post issue. Please try to elaborate as much as you can. Thanks!
