### ISSUE TITLE
Build tensorflow C++ failed

### ISSUE THREAD

**Issue by fsx950223** [tensorflow/tensorflow#27828]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):source
- TensorFlow version (use command below):nightly
- Python version:
- Bazel version (if compiling from source):0.24.1
- GCC/Compiler version (if compiling from source):6.3.0
- CUDA/cuDNN version:
- GPU model and memory:

You can collect some of this information using our environment capture [script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with
python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"

**Describe the current behavior**

```
ERROR: /home/fsx950223/tensorflow/tensorflow/core/kernels/BUILD:3370:1: C++ compilation of rule '//tensorflow/core/kernels:batch_matmul_op' failed (Exit 1)
In file included from external/eigen_archive/unsupported/Eigen/CXX11/../../../Eigen/Core:296:0,
                 from external/eigen_archive/unsupported/Eigen/CXX11/Tensor:14,
                 from ./third_party/eigen3/unsupported/Eigen/CXX11/Tensor:1,
                 from ./tensorflow/core/kernels/batch_matmul_op_impl.h:25,
                 from tensorflow/core/kernels/batch_matmul_op_real.cc:16:
external/eigen_archive/unsupported/Eigen/CXX11/../../../Eigen/src/Core/products/GeneralBlockPanelKernel.h: In member function 'void Eigen::internal::lhs_process_one_packet<nr, LhsProgress, RhsProgress, LhsScalar, RhsScalar, ResScalar, AccPacket, LhsPacket, RhsPacket, ResPacket, GEBPTraits, LinearMapper, DataMapper>::peeled_kc_onestep(Eigen::Index, const LhsScalar*, const RhsScalar*, GEBPTraits, LhsPacket*, Eigen::internal::lhs_process_one_packet<nr, LhsProgress, RhsProgress, LhsScalar, RhsScalar, ResScalar, AccPacket, LhsPacket, RhsPacket, ResPacket, GEBPTraits, LinearMapper, DataMapper>::RhsPacketx4*, RhsPacket*, AccPacket*, AccPacket*, AccPacket*, AccPacket*) [with int nr = 4; long int LhsProgress = 1l; long int RhsProgress = 1l; LhsScalar = Eigen::half; RhsScalar = Eigen::half; ResScalar = Eigen::half; AccPacket = Eigen::half; LhsPacket = Eigen::half; RhsPacket = Eigen::half; ResPacket = Eigen::half; GEBPTraits = Eigen::internal::gebp_traits<Eigen::half, Eigen::half, false, false, 1, 0>; LinearMapper = Eigen::internal::BlasLinearMapper<Eigen::half, long int, 0>; DataMapper = Eigen::internal::blas_data_mapper<Eigen::half, long int, 0, 0>]':
external/eigen_archive/unsupported/Eigen/CXX11/../../../Eigen/src/Core/products/GeneralBlockPanelKernel.h:1351:33: internal compiler error: in assign_temp, at function.c:961
     __asm__  ("" : "+x,m" (*A0));
```

**Describe the expected behavior**
Compile success

**Code to reproduce the issue**

Provide a reproducible test case that is the bare minimum necessary to generate the problem.
``` sh
bazel build -c dbg --cxxopt="-D_GLIBCXX_USE_CXX11_ABI=0" //tensorflow/cc/example:example --local_resources 2048,.5,1.0
```
**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by hoonkai** [comment]
Same here. I'm having the same issue.

**Comment by uddmorningsun** [comment]
@fsx950223 Same issue, did you resolve this problem finally? If so, could you share a workaround, thanks !

**Comment by fsx950223** [comment]
> @fsx950223 Same issue, did you resolve this problem finally? If so, could you share a workaround, thanks !

add ```-c opt``` to the ```bazel``` build command.
