### ISSUE TITLE
tflite support for Softplus (exp and log are already supported)

### ISSUE THREAD

**Issue by jackshi0912** [tensorflow/tensorflow#27822]
**System information**
- gLinux
- TensorFlow installed from source
- TensorFlow version head

**Provide the text output from tflite_convert**

```
Some of the operators in the model are not supported by the standard TensorFlow Lite runtime. If those are native TensorFlow operators, you might be able to use the extended runtime by passing --enable_select_tf_ops, or by setting target_ops=TFLITE_BUILTINS,SELECT_TF_OPS when calling tf.lite.TFLiteConverter(). Otherwise, if you have a custom implementation for them you can disable this error with --allow_custom_ops, or by setting allow_custom_ops=True when calling tf.lite.TFLiteConverter(). Here is a list of builtin operators you are using: ADD, CONCATENATION, CONV_2D, MAX_POOL_2D, MEAN, MIRROR_PAD, MUL, RSQRT, SQUARED_DIFFERENCE, SUB, TRANSPOSE_CONV. Here is a list of operators for which you will need custom implementations: Softplus.
```

We already support log and exp. Softplus seems like a simple addition.

**Comment by amitsrivastava78** [comment]
@jdduke , what is your take on this, should we have this operator support in the tflite kernel or should we transform the operator into log and exp using transform graph ?

Regards
Amit

**Comment by miaout17** [comment]
Beware. It will be problematic SoftPlus is simply transformed to log(exp(x) + 1).  There will be numerical stability issues when input is too large or too small. 

If going the transformation route, we need to do something like this:
https://github.com/tensorflow/tensorflow/blob/ee82131dbccd4e99decb8c05c43bc2bb387ad6ac/tensorflow/core/kernels/softplus_op.h#L50

**Comment by amitsrivastava78** [comment]
@miaout17,thanks for the heads up, highly appreciated your valuable input, will study this deeply and raise a PR in coming days

Regards 
Amit

**Comment by amitsrivastava78** [comment]
@miaout17 , i have raised the PR, kindly have a look.

Regards
Amit

**Comment by rmothukuru** [comment]
@jackshi0912,
Sorry for the delayed response. With respect to [jdduke's comment in this PR](https://github.com/tensorflow/tensorflow/pull/28042#issuecomment-510988913), 

> Until we find another model which requires this op, I'd rather we rely on using the select TF ops, or we add this as a custom op that users can optionally link into their app.

It's more than 2 years since this feature has been requested and there has been no **`Model`** which requires this Op. Do you still think this feature is still relevant? Thanks!
