### ISSUE TITLE
Problem building libtensorflow.so on Debian system with Bazel

### ISSUE THREAD

**Issue by segvee** [tensorflow/tensorflow#27833]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Debian Stretch (9.8, latest)
- TensorFlow installed from (source or binary): source
- TensorFlow version: r1.13.1
- Python version: Python 2.7.13
- Installed using virtualenv? pip? conda?: Official Debian repository
- Bazel version (if compiling from source): 0.19.2
- GCC/Compiler version (if compiling from source): gcc (Debian 6.3.0-18+deb9u1) 6.3.0 20170516
- GPU model and memory: Intel HD 4000

I am trying to compile Tensorflow release 1.13 from source in order to obtain the shared library libtensorflow.so using bazel. I do this by invoking
`bazel build //tensorflow:libtensorflow.so`

After some time the build stops with the following error message
`ERROR: ~/tensorflow/tensorflow_r1.13.1/tensorflow/core/kernels/BUILD:4312:1: C++ compilation of rule '//tensorflow/core/kernels:sparse_reduce_op' failed (Exit 1)
In file included from tensorflow/core/kernels/sparse_reduce_op.cc:25:0:
./tensorflow/core/util/sparse/sparse_tensor.h: In static member function 'static tensorflow::Status tensorflow::sparse::SparseTensor::Create(tensorflow::Tensor, tensorflow::Tensor, tensorflow::sparse::SparseTensor::VarDimArray, tensorflow::sparse::SparseTensor::VarDimArray, tensorflow::sparse::SparseTensor*)':
./tensorflow/core/util/sparse/sparse_tensor.h:68:22: warning: 'dims' may be used uninitialized in this function [-Wmaybe-uninitialized]
     if (order.size() != dims) {
         ~~~~~~~~~~~~~^~~~~~~
In file included from external/eigen_archive/unsupported/Eigen/CXX11/Tensor:124:0,
                 from ./third_party/eigen3/unsupported/Eigen/CXX11/Tensor:1,
                 from ./tensorflow/core/framework/numeric_types.h:20,
                 from ./tensorflow/core/framework/allocator.h:23,
                 from ./tensorflow/core/framework/op_kernel.h:23,
                 from tensorflow/core/kernels/sparse_reduce_op.cc:20:
external/eigen_archive/unsupported/Eigen/CXX11/src/Tensor/TensorReduction.h: In static member function 'static void std::_Function_handler<void(_ArgTypes ...), _Functor>::_M_invoke(const std::_Any_data&, _ArgTypes&& ...) [with _Functor = Eigen::internal::TensorExecutor<Expression, Eigen::ThreadPoolDevice, Vectorizable, Tileable>::run(const Expression&, const Eigen::ThreadPoolDevice&) [with Expression = const Eigen::TensorAssignOp<Eigen::TensorMap<Eigen::TensorFixedSize<std::complex<float>, Eigen::Sizes<>, 1, long int>, 16, Eigen::MakePointer>, const Eigen::TensorReductionOp<Eigen::internal::SumReducer<std::complex<float> >, const Eigen::DimensionList<long int, 1ul>, const Eigen::TensorMap<Eigen::Tensor<std::complex<float>, 1, 1, long int>, 0, Eigen::MakePointer>, Eigen::MakePointer> >; bool Vectorizable = true; bool Tileable = false]::<lambda(Eigen::internal::TensorExecutor<const Eigen::TensorAssignOp<Eigen::TensorMap<Eigen::TensorFixedSize<std::complex<float>, Eigen::Sizes<>, 1, long int>, 16, Eigen::MakePointer>, const Eigen::TensorReductionOp<Eigen::internal::SumReducer<std::complex<float> >, const Eigen::DimensionList<long int, 1ul>, const Eigen::TensorMap<Eigen::Tensor<std::complex<float>, 1, 1, long int>, 0, Eigen::MakePointer>, Eigen::MakePointer> >, Eigen::ThreadPoolDevice, true, false>::StorageIndex, Eigen::internal::TensorExecutor<const Eigen::TensorAssignOp<Eigen::TensorMap<Eigen::TensorFixedSize<std::complex<float>, Eigen::Sizes<>, 1, long int>, 16, Eigen::MakePointer>, const Eigen::TensorReductionOp<Eigen::internal::SumReducer<std::complex<float> >, const Eigen::DimensionList<long int, 1ul>, const Eigen::TensorMap<Eigen::Tensor<std::complex<float>, 1, 1, long int>, 0, Eigen::MakePointer>, Eigen::MakePointer> >, Eigen::ThreadPoolDevice, true, false>::StorageIndex)>; _ArgTypes = {long int, long int}]':
external/eigen_archive/unsupported/Eigen/CXX11/src/Tensor/TensorReduction.h:801:9: internal compiler error: in emit_move_insn, at expr.c:3547
         values[i] = internal::InnerMostDimReducer<Self, Op>::reduce(*this, firstIndex + i * num_values_to_reduce,
         ^~~~~~
`

**Comment by ymodak** [comment]
Can you please follow these steps to [install TF from sources](https://www.tensorflow.org/install/source#setup_for_linux_and_macos). Thanks!

**Comment by ymodak** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Comment by tjhgit** [comment]
Exact same problem here. Also on debian same error. Tried different versions of bazel, different versions of tensorflow (2.0, 1.14) but always getting compile error.

Using the following command for building:
bazel build -c opt --copt=-mavx --copt=-mavx2 --copt=-mfma --copt=-mfpmath=both --copt=-msse4.2 --cxxopt="-D_GLIBCXX_USE_CXX11_ABI=0" -k //tensorflow/tools/pip_package:build_pip_package --verbose_failures

I followed closely the build instructions.

**Comment by sonbn0** [comment]
I have the same error
Debian stretch
GCC 6
python3.6

**Comment by wormwang** [comment]
Ubuntu 18.04.2 ,TF 1.13.3 gcc 7.4 & gcc 8.3 meet same this error external/eigen_archive/unsupported/Eigen/CXX11/../../../Eigen/src/Core/products/GeneralBlockPanelKernel.h:1879:3:  internal compiler error: in emit_move_insn, at expr.c:3723 } ^
--

**Comment by myungjoo** [comment]
Custom Linux, TF 1.13
bazel 0.19.2
gcc 6.2.1
aarch64

shows the exact same error.

**Comment by ghostrider** [comment]
Same story here. 
GCC 8.2.0 
TF 2.2.0 
bazel 3.0.0
64bit cpu
