### ISSUE TITLE
tf-nightly-gpu 1.14.1 failed call to cuInit: CUDA_ERROR_UNKNOWN: unknown error

### ISSUE THREAD

**Issue by wmylxmj** [tensorflow/tensorflow#27830]
My Python version is 3.7.1, the operating system is Windows 10, the CUDA version is cuda_10.0.130_411.31_win10, the cudnn version is cudnn-10.0-windows 10-x64-v7.4.2.24, the GPU is Intel (R) UHD Graphics 620, and the tf-nightly-gpu-1.14.1.20190323 is installed.
When I run `import tensorflow as tf`, there is no problem.
When I run:
`m1 = tf.constant([[3, 3]])`
`m2 = tf.constant([[2], [2]])`
`p = tf.matmul(m1, m2)`
`sess =  tf.Session()`
`r = sess.run(p)`
there is no variable "r" in my variable explorer.
When I run:
`print(p)`
I get this:
![QQ图片20190414154532 (2)](https://user-images.githubusercontent.com/38285222/56089888-83422400-5ecc-11e9-9d7a-5ff8bee54cf4.jpg)
What should I do? Thanks!

**Comment by wmylxmj** [comment]
I know the answer.

**Comment by iamsurya** [comment]
@wmylxmj Please share the answer so that others can benefit from it. I'm running into the same error.

**Comment by bine-86-04** [comment]
@wmylxmj I have the same problem, and I am not smart enough to solve it. Can you please share what you did to make it work?

**Comment by iamsurya** [comment]
@bine-86-04 This usually happens if you are trying to run tensorflow-gpu with an nvidia GPU. It is possible that you don't have CUDA installed on your computer. It is also possible that the tensorflow binary you downloaded was compiled with a different version of CUDA than you have installed.
