### ISSUE TITLE
Proper way to build Tensorflow for arbitrary CUDA Compute Capability

### ISSUE THREAD

**Issue by ndandanov** [tensorflow/tensorflow#27840]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): **Linux Ubuntu 18.04**
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): **docker image** (_tensorflow/tensorflow:devel-gpu-py3_) for building tensorflow
- TensorFlow version: **1.13.0**
- Python version: **3.5**
- Installed using virtualenv? pip? conda?: **docker image**
- Bazel version (if compiling from source): **0.23.2** _(default for the docker image)_
- GCC/Compiler version (if compiling from source): **5.4.0 20160609** _(default for the docker image)_
- CUDA/cuDNN version: **10.0**
- GPU model and memory: [NVIDIA QUADRO K4200](https://www.nvidia.com/content/dam/en-zz/Solutions/design-visualization/quadro-product-literature/DS-NV-Quadro-K4200-JUL24-US-NV-r-HR.pdf)

**Describe the problem**

Following the [build instructions for docker with GPU support with CUDA](https://www.tensorflow.org/install/source#gpu_support_2) leads to a pip wheel with support for CUDA Compute Capability 3.5, 5.2, 6.0, 6.1, 7.0.

However, the GPU I am trying to set up Tensorflow for supports only CUDA Compute Capability 3.0. Going through the documentation I did not manage to find a clear instruction on how to enable support for non-default CUDA Compute Capability during the build process. Despite trying a couple of different approaches, I always got the following error:

```python
2019-04-14 22:58:01.822303: I tensorflow/compiler/xla/service/platform_util.cc:197] StreamExecutor cuda device (0) is of insufficient compute capability: 3.5 required, device is 3.0
```

when trying to execute the following command:
```python
python -c "import tensorflow as tf; tf.enable_eager_execution(); print(tf.reduce_sum(tf.random_normal([1000, 1000])))"
```

**Provide the exact sequence of commands / steps that you executed before running into the problem**

I tried to edit `/tensorflow_src/.tf_configure.bazelrc` in the docker container by having `TF_CUDA_COMPUTE_CAPABILITIES="3.0,3.5,5.2,6.0,6.1,7.0"` before building, but this did not solve the problem.
I set the respective shell variable `TF_CUDA_COMPUTE_CAPABILITIES="3.0,3.5,5.2,6.0,6.1,7.0"` before configuring with bazel, but this also did not result in a working image.

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by wdirons** [comment]
Have you tried to build with XLA turned off? It appears XLA requires a gpu with the minimal capability of 3.5: https://github.com/tensorflow/tensorflow/blob/adf8dac492adb33d4c71a4271f6f003a156eae22/tensorflow/compiler/xla/service/platform_util.cc#L36

**Comment by ndandanov** [comment]
@wdirons, thank you for your fast response!

I built tensorflow by modifying `build:xla --define with_xla_support=false` (it was true after the initial `./configure`, despite setting the use of XLA JIT to false) in `tensorflow_src/.tf_configure.bazelrc` and also by exporting `TF_CUDA_COMPUTE_CAPABILITIES="3.0"`.

The built wheel installed successfully and seems to be working, I am using it now as a test.
Perhaps these specifics can be somehow added in the documentation (or FAQ) and the issue can be closed. :)

**Comment by wdirons** [comment]
That is odd behavior, the behavior of ./configure setting it to true is expected, let me explain:

When true is answered what is written to `.tf_configure.bazelrc` is:
> build --define with_xla_support=true

When `false` is answered what is wrrtten to `.tf_configure.bazelrc` is:
> build:xla --define with_xla_support=true

The difference is in 'build' vs 'build:xla', bazel build automatically includes all build parameters, but only includes `build:xyz` parameters when `--config=xyz` is passed in via the bazel build command line

**Comment by wdirons** [comment]
In ./configure for master, but not in 1.13, is a warning about using XLA with TF_CUDA_COMPUTE_CAPABILITIES < 3.5.

https://github.com/tensorflow/tensorflow/blob/master/configure.py#L1021-L1023

**Comment by ndandanov** [comment]
Thank you for the elaborate replies, @wdirons!

I am novice to `bazel` so was unaware when it includes `build:xyz` parameters in the build. Therefore I modified the `build:xla --define with_xla_support` from `true` to `false` and the build seems to have succeeded and to result in a working wheel.

Using the `tensorflow/tensorflow:devel-gpu-py3` docker image from a couple of weeks ago, I also received the `WARNING: XLA does not support CUDA compute capabilities lower than 3.5. Disable XLA when running on older GPUs.` warning. It was a bit confusing because in my case it was printed towards the end of the configuration procedure.

I had not taken a look at the `configure.py` before. During the configuration procedure I was not prompted to specify a list of CUDA compute capabilities as many tutorials point out.
Now I see that this message is contained in `ask_cuda_compute_capabilities` and it was not printed due to the `TF_CUDA_COMPUTE_CAPABILITIES` environment variable being already set up in the docker image.

**Comment by ymodak** [comment]
Closing this issue since its resolved. Feel free to reopen if have further questions. Thanks!

**Comment by zz** [comment]
Can't use tersonflow with K4200, so I have to use Pytroch. Good job, tersonflow team!
```
(tensorflow) ➜  tensorflow python -c "import tensorflow as tf;print(tf.reduce_sum(tf.random.normal([1000, 1000])))"

2019-10-23 18:52:56.886068: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1
2019-10-23 18:52:56.918140: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties:
name: Quadro K4200 major: 3 minor: 0 memoryClockRate(GHz): 0.784
pciBusID: 0000:03:00.0
2019-10-23 18:52:56.920414: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.0
2019-10-23 18:52:56.949430: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10.0
2019-10-23 18:52:56.964393: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10.0
2019-10-23 18:52:56.969524: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10.0
2019-10-23 18:52:57.004353: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10.0
2019-10-23 18:52:57.026557: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10.0
2019-10-23 18:52:57.093799: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2019-10-23 18:52:57.095530: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1700] Ignoring visible gpu device (device: 0, name: Quadro K4200, pci bus id: 0000:03:00.0, compute capability: 3.0) with Cuda compute capability 3.0. The minimum required Cuda capability is 3.5.
2019-10-23 18:52:57.134106: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2019-10-23 18:52:57.269851: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2294740000 Hz
2019-10-23 18:52:57.274847: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x5b7df80 executing computations on platform Host. Devices:
2019-10-23 18:52:57.274902: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): Host, Default Version
2019-10-23 18:52:57.334299: I tensorflow/compiler/xla/service/platform_util.cc:197] StreamExecutor cuda device (0) is of insufficient compute capability: 3.5 required, device is 3.0
2019-10-23 18:52:57.342662: F tensorflow/stream_executor/lib/statusor.cc:34] Attempting to fetch value instead of handling error Internal: no supported devices found for platform CUDA
```

**Comment by dimitree54** [comment]
> Can't use tersonflow with K4200, so I have to use Pytorch. Good job, tersonflow team!
> 
> ```
> (tensorflow) ➜  tensorflow python -c "import tensorflow as tf;print(tf.reduce_sum(tf.random.normal([1000, 1000])))"
> 
> 2019-10-23 18:52:56.886068: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1
> 2019-10-23 18:52:56.918140: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties:
> name: Quadro K4200 major: 3 minor: 0 memoryClockRate(GHz): 0.784
> pciBusID: 0000:03:00.0
> 2019-10-23 18:52:56.920414: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.0
> 2019-10-23 18:52:56.949430: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10.0
> 2019-10-23 18:52:56.964393: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10.0
> 2019-10-23 18:52:56.969524: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10.0
> 2019-10-23 18:52:57.004353: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10.0
> 2019-10-23 18:52:57.026557: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10.0
> 2019-10-23 18:52:57.093799: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
> 2019-10-23 18:52:57.095530: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1700] Ignoring visible gpu device (device: 0, name: Quadro K4200, pci bus id: 0000:03:00.0, compute capability: 3.0) with Cuda compute capability 3.0. The minimum required Cuda capability is 3.5.
> 2019-10-23 18:52:57.134106: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
> 2019-10-23 18:52:57.269851: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2294740000 Hz
> 2019-10-23 18:52:57.274847: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x5b7df80 executing computations on platform Host. Devices:
> 2019-10-23 18:52:57.274902: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): Host, Default Version
> 2019-10-23 18:52:57.334299: I tensorflow/compiler/xla/service/platform_util.cc:197] StreamExecutor cuda device (0) is of insufficient compute capability: 3.5 required, device is 3.0
> 2019-10-23 18:52:57.342662: F tensorflow/stream_executor/lib/statusor.cc:34] Attempting to fetch value instead of handling error Internal: no supported devices found for platform CUDA
> ```

PyTorch 1.5 also does not support compute capability <3.5

**Comment by yselivonchyk** [comment]
In order to get custom CC during compilation I'd suggest simply editing the ./configure.py file (https://github.com/tensorflow/tensorflow/blob/master/configure.py)

```
...
_DEFAULT_CUDA_COMPUTE_CAPABILITIES = '3.5,7.0'
...
```
