### ISSUE TITLE
Lite runtime is not supported in proto3

### ISSUE THREAD

**Issue by graphific** [tensorflow/tensorflow#2784]
compiling proto3 for ios with `tensorflow/contrib/makefile/compile_ios_protobuf.sh` an error is thrown on the `make` step:

`google/protobuf/unittest_proto3_arena_lite.proto: Lite runtime is not supported in proto3.`

It seems that Lite support has been added to the master branch of protobuf however: https://github.com/google/protobuf/issues/1443

any idea why this error persists? Same for a clean pull and install of tf, as well as a couple of other proto branches.

**Comment by cwhipkey** [comment]
The failing file unittest_proto3_arena_lite.proto comes the protobuf library itself, and was added at the same time that lite+proto3 support was added.  So it seems like a mismatch between the version of protobuf downloaded by download_dependencies.sh, and the protoc compiler used to run the unit test - although I would have expected the test to use the protoc built from that code.

Just to check, what does   protoc --version   give for you?

@petewarden

**Comment by petewarden** [comment]
My usual recommendation is to make sure that you do a host install of the protobuf version you've downloaded, to make sure that the headers, libraries, and protoc binary that's in /usr/* are compatible with the version we're compiling for Android. This may be overkill, and I'm looking at better ways of handling this (e.g. compiling a local copy of the host protobuf and using that local protoc), but it does simplify things a lot.

**Comment by graphific** [comment]
Doing a full host install with correct osx version in compile_ios_protobuf.sh (OSX_VERSION=darwin15.0.0 in my case) and recompiling for iOS seems to do the trick. tnx!

**Comment by juansalas** [comment]
@graphific Looks like I have the same issue. I updated my darwin version in _compile_ios_protobuf.sh_ to **OSX_VERSION=darwin15.0.0** but still not working. How you solved it ? Thanks!

**Comment by graphific** [comment]
@juansalas hard to say actually since I was compiling a bunch of things, but I think doing a full protobuf reinstall from the master branch should fix it.
