### ISSUE TITLE
How to use libtensorflow-lite.a with C++ on Raspberry Pi 3?

### ISSUE THREAD

**Issue by LedahBlack** [tensorflow/tensorflow#27855]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):Rasbian
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: Raspberry Pi 3b+
- TensorFlow installed from (source or binary):No
- TensorFlow version:No
- Python version:3.5
- Installed using virtualenv? pip? conda?:No
- Bazel version (if compiling from source):No
- GCC/Compiler version (if compiling from source):No
- CUDA/cuDNN version:No
- GPU model and memory:No

I have trained own model and converted to lite model. Then I have generated libtensorflow-lite.a with cross-compiling on Ubuntu 16.04. I am trying to find the header file of all the objects in the libtensorflow-lite.a. Is this correct ? How to use it on Raspberry Pi 3 ? 

In addition, the path to the libtensorflow-lite.a generated when using cross-compilation is /tensorflow/lite/tools/make/gen/rpi_armv7l/lib is not the same as the official teaching path.
Does this compile fail?

**Comment by jinyige** [comment]
you have to make a *.a file by yourself. follow this guide:https://tensorflow.google.cn/lite/guide/build_rpi

**Comment by LedahBlack** [comment]
> 你必須自己製作一個* .a文件。請按照以下指南操作：[https](https://tensorflow.google.cn/lite/guide/build_rpi)：[//tensorflow.google.cn/lite/guide/build_rpi](https://tensorflow.google.cn/lite/guide/build_rpi)

@jinyige I have made the *.a file in accordance with the official instructions. If I want to use this *.a file, should I need a .h file?

**Comment by ymodak** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.

If you think we've misinterpreted a bug, please comment again with a clear explanation, as well as all of the information requested in the [issue template](https://github.com/tensorflow/tensorflow/issues/new/choose). Thanks!
