### ISSUE TITLE
Problem building tensorflow on Ubuntu system with Bazel gpu flavor

### ISSUE THREAD

**Issue by Dayananda-V** [tensorflow/tensorflow#27852]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04.2 LTS
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): source
- TensorFlow version: master
- Python version: Python 3.6.7
- Installed using virtualenv? pip? conda?: NA
- Bazel version (if compiling from source): 0.23.2
- GCC/Compiler version (if compiling from source): gcc (Ubuntu 6.5.0-2ubuntu1~18.04) 6.5.0 20181026
- CUDA/cuDNN version: 9.2
- GPU model and memory: GeForce GTX 1060 Max-Q GPU with 6GB of VRAM

Faced tensorflow compilation problem with below details

> user@user:/opt/work/work_tf/tensbazel build -j 8 --config=opt --config=cuda //tensorflow/tools/pip_package:build_pip_package
> Extracting Bazel installation...
> Starting local Bazel server and connecting to it...
> WARNING: The following configs were expanded more than once: [cuda]. For repeatable flags, repeats are counted twice and may lead to unexpected behavior.
> DEBUG: /home/user/.cache/bazel/_bazel_user/f793b012987ffd570584b4a3e97b9108/external/bazel_tools/tools/cpp/lib_cc_configure.bzl:115:5: 
> Auto-Configuration Warning: 'TMP' environment variable is not set, using 'C:\Windows\Temp' as default
> ERROR: /home/user/.cache/bazel/_bazel_user/f793b012987ffd570584b4a3e97b9108/external/com_github_googlecloudplatform_google_cloud_cpp/google/cloud/BUILD:27:1: no such target '@bazel_tools//tools/cpp:cc_flags': target 'cc_flags' not declared in package 'tools/cpp' defined by /home/user/.cache/bazel/_bazel_user/f793b012987ffd570584b4a3e97b9108/external/bazel_tools/tools/cpp/BUILD and referenced by '@com_github_googlecloudplatform_google_cloud_cpp//google/cloud:generate_build_info'
> ERROR: Analysis of target '//tensorflow/tools/pip_package:build_pip_package' failed; build aborted: Analysis failed
> INFO: Elapsed time: 43.643s
> INFO: 0 processes.
> FAILED: Build did NOT complete successfully (327 packages loaded, 8419 targets configured)
>     Fetching @grpc; fetching 18s
>     Fetching @com_google_absl; fetching 18s
>     Fetching @aws; fetching 17s
>     Fetching @llvm; fetching 15s
>     Fetching @nasm; fetching 9s

**Any other info / logs**
This problem is reported after merge "Update Google Cloud C++ Client to the v0.8.1 release." (commit id : 0602e366015a85899e3f2cc645667dd308f4fbb5) changes.

**Comment by wdirons** [comment]
To get around this problem, I had to upgrade bazel to version 0.24.1

**Comment by Dayananda-V** [comment]
Thanks @wdirons with bazel 0.24.1 version tensorflow compilation problem is not exists.
