### ISSUE TITLE
get error message when use tf.summary.scalar() with TF 2.0

### ISSUE THREAD

**Issue by breadbread1984** [tensorflow/tensorflow#27856]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): tf-nightly-gpu-2.0-preview: 2.0.0-dev20190413
- Python version: 3.6.7
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: 10.0
- GPU model and memory: Yes, 11GB

You can collect some of this information using our environment capture [script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with
python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"

**Describe the current behavior**

I get the following error message when I use tensorflow in GPU mode. When I use tensorflow in CPU mode, such error message doesn't occur.

>AttributeError: module 'tensorboard.summary._tf.summary' has no attribute 'summary_scope'

**Describe the expected behavior**

I expect no error when I call tf.summary.scalar() in TF2.0 in both GPU and CPU mode.

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

```Python
#!/usr/bin/python3

import tensorflow as tf;

def main():

    log = tf.summary.create_file_writer('checkpoints');
    with log.as_default():
        tf.summary.scalar('loss',1., step = 0);

if __name__ == "__main__":

    main();
```

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by mhalenka** [comment]
Just in case it might help, I got past this issue today by running
``pip3 install --upgrade --force-reinstall tb-nightly``

**Comment by breadbread1984** [comment]
thx.
