### ISSUE TITLE
Possible wrong assumption for how a dense flow filed is stored

### ISSUE THREAD

**Issue by alisaaalehi** [tensorflow/tensorflow#27868]
In `dense_image_warp` function it is assumed that flow vectors are stored in source location of flow vectors while for dense optical flow datasets like **Middlebury**, **MPI Sinte**, **Flying Chairs**it is not the case.

In the following simple example a black dot moves from the location (2,6) in image one to (5,10) in image two. So, flow vector for that point is (3,4). In Tensorflow code it assumes that flow field is stored in **Format A**. That is why [here](https://github.com/tensorflow/tensorflow/blob/79d8779069a154a74786c28bf9d8af3d0cbd9905/tensorflow/contrib/image/python/ops/dense_image_warp.py#L172) it is explained:

> ... where the warp is specified by a dense
>   flow field of offset vectors that define the correspondences of pixel values
>   in the output image back to locations in the  source image. Specifically, the
>   pixel value at output[b, j, i, c] is
>   images[b, j - flow[b, j, i, 0], i - flow[b, j, i, 1], c].

![FlowExplained-tensorflow](https://user-images.githubusercontent.com/39167815/56152784-3ae13f80-5f7a-11e9-8cb0-a26d097f062d.png)

Can anybody explain the reason to implement this function in this way? While this format is useful for some specific tasks, it is not consistent with standard datasets.

I would suggest changing the assumption to **Format B** and modify the code to do backward warping (given image 2 and flow field, it will reconstruct image 1). Specifically, the pixel value at 
output[b, j, i, c] would be  images[b, j + flow[b, j, i, 0], i + flow[b, j, i, 1], c]

In terms of implementation, line [210](https://github.com/tensorflow/tensorflow/blob/79d8779069a154a74786c28bf9d8af3d0cbd9905/tensorflow/contrib/image/python/ops/dense_image_warp.py#L210) can be changed to:

```python
query_points_on_grid = batched_grid + flow
```

**Comment by alisaaalehi** [comment]
So, what do you think guys? Let me know your thoughts, please.
Should I go ahead and make a PR for this?

**Comment by ymodak** [comment]
Thanks for your investigation. Contrib is deprecated starting TF 2.0 . Probably this can be a good candidate for [tensorflow/addons](https://github.com/tensorflow/addons).
