### ISSUE TITLE
0.9rc0 regression when using scan over axes with shape None

### ISSUE THREAD

**Issue by jlowin** [tensorflow/tensorflow#2787]
A simple cumulative sum with scan that worked in TF 0.8 fails in 0.9rc0 with an inconsistent shape error. I have attached code to illustrate the error below. Basically, a scan over the 0th axis fails when a different axis has None shape. This occurs, for example, when computing a cumulative sum over an arbitrary axis of a minibatched variable (after first transposing that axis to be in the 0th position).

### Environment info
Operating System: Mac OSX 10.11.5

Installed version of CUDA and cuDNN: 
(please attach the output of `ls -l /path/to/cuda/lib/libcud*`): N/A

If installed from binary pip package, provide:

1. Which pip package you installed: 

  `https://storage.googleapis.com/tensorflow/mac/tensorflow-0.9.0rc0-py3-none-any.whl`

2. The output from `python -c "import tensorflow; print(tensorflow.__version__)"`.

  `0.9.0rc0`

If installed from sources, provide the commit hash:

### Steps to reproduce

Run the following code:
```python
import tensorflow as tf
x = tf.placeholder(dtype=tf.float32, shape=[None, 2])
xT = tf.transpose(x)
# scan over dimension 0 (with shape None)
result = tf.scan(lambda a, x: a + x, x)
# scanned over transposed dimension 0 (with shape 2)
resultT = tf.scan(lambda a, x: a + x, xT)
```

To see the following error:
`ValueError: Inconsistent shapes: saw (?,) but expected (?,) (and infer_shape=True)`

**Comment by jarrydfillmore** [comment]
+1!

**Comment by ebrevdo** [comment]
@yuanbyu we may have to either plumb infer_shape=True through scan/map_fn/etc or just set infer_shape=False everywhere.  what do you think is best?

**Comment by ebrevdo** [comment]
We may have pushed a fix for this in an unrelated bugfix to TensorArray.  It hasn't been merged into github yet.  Try this in a couple of days on the version of TF in master and report back.

**Comment by jlowin** [comment]
Just to check in -- this script still raises an error in the 0.9.0 release.

**Comment by thomasquintana** [comment]
+1 Is there are update on this issue? It's currently blocking me as well.

**Comment by ebrevdo** [comment]
Is this still an issue in the nightlies?

**Comment by thomasquintana** [comment]
@ebrevdo  I'm using the 0.9.0 release. I will try with master first thing in the AM and update the thread. -- Thanks!

**Comment by thomasquintana** [comment]
@ebrevdo I just tried with 0.10.0rc0 and I still have the same issue.

`ValueError: Inconsistent shapes: saw (?,) but expected (?,) (and infer_shape=True)`

**Comment by barimohsin** [comment]
@ebrevdo this is a showstopper for me as well.. dealing with same issue as mentioned by @thomasquintana.. will appreciate if someone from google tensorflow team take a look at it soon.

**Comment by ebrevdo** [comment]
Fix has been pushed; takes a few days to reach github.  When you call
tf.scan/tf.map_fn, pass the argument infer_shape=False and things should
work.  Added your use case as a unit test.

**Comment by thomasquintana** [comment]
Thank you so much! I am traveling for a few days but I will try on Friday from the nightly build and update this thread.

Cheers!

**Comment by thomasquintana** [comment]
This problem is fixed! -- Cheers, Tom

**Comment by wwmmqq** [comment]
➜  src python -c "import tensorflow; print(tensorflow.__version__)"
1.2.0

➜  ValueError: Inconsistent shapes: saw (?, ?) but expected (150,) (and infer_shape=True)
