### ISSUE TITLE
Having trouble running tensorflow with gpu

### ISSUE THREAD

**Issue by goldblum** [tensorflow/tensorflow#27874]
**System information**
- Ubuntu 18.04
- TensorFlow installed from source (not sure what this means)
- TensorFlow version 1.12.0
- Python version 3.6
- Installed using pip
- CUDA/cuDNN version 9.1
- GPU model and memory: GV100 

I'm new to tensorflow, and I'm trying to run it using a GPU. I've installed tensorflow in the past, but not the gpu version. Today, I uninstalled the old version, and installed the gpu version (1.12.0). I'm getting the following error when I try to run basic commands: 

" ImportError: libcublas.so.9.0: cannot open shared object file: No such file or directory
Failed to load the native TensorFlow runtime. "

I've done some troubleshooting, including installing an older version of tensorflow, but nothing seems to work. Has anyone dealt with this problem before?

**Comment by wdirons** [comment]
TensorFlow requires an exact version of cuda it was built with to be installed. It says above you have CUDA 9.1 installed, but TensorFlow only supported CUDA 9.0 and then with TensorFlow 1.13.1 they supported CUDA 10.0. 

You need to uninstall CUDA 9.1 and install either CUDA 9.0 for TensorFlow 1.12, or CUDA 10.0 for TensorFlow 1.13.1

**Comment by ymodak** [comment]
Closing this issue since wdiron's comment solves the issue. Feel free to reopen if have any questions. Thanks!
