### ISSUE TITLE
Error: Can't build Tensorflow Lite for Raspberry Pi 3b+.

### ISSUE THREAD

**Issue by jinyige** [tensorflow/tensorflow#27889]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):**Raspbian GNU/Linux 9.8 (stretch)**
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary):N/A
- TensorFlow version:**the latest**
- Python version: N/A
- Installed using virtualenv? pip? conda?: N/A
- Bazel version (if compiling from source):N/A
- GCC/Compiler version (if compiling from source):**gcc version 6.3.0 20170516 (Raspbian 6.3.0-18+rpi1+deb9u1)**
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

**Describe the problem**

trying to build Tensorflow Lite for  Raspberry Pi 3b+
followed the instructions on https://tensorflow.google.cn/lite/guide/build_rpi 

 **at the last step got lots of errors such as:** 

`In file included from ./tensorflow/lite/experimental/c/c_api.h:24:0,
                 from ./tensorflow/lite/experimental/c/c_api_experimental.h:19,
                 from tensorflow/lite/experimental/c/c_api_experimental.cc:16:
./tensorflow/lite/experimental/c/c_api_types.h:1:1: error: expected unqualified-id before ‘.’ token
 ../../c/c_api_internal.h
 ^
In file included from tensorflow/lite/experimental/c/c_api_experimental.cc:16:0:
./tensorflow/lite/experimental/c/c_api_experimental.h:28:24: error: ‘TFL_Status’ does not name a type
 TFL_CAPI_EXPORT extern TFL_Status TFL_InterpreterResetVariableTensors(
                        ^~~~~~~~~~
./tensorflow/lite/experimental/c/c_api_experimental.h:38:5: error: variable or field ‘TFL_InterpreterOptionsAddBuiltinOp’ declared void
     TFL_InterpreterOptions* options, TFL_BuiltinOperator op,
     ^~~~~~~~~~~~~~~~~~~~~~
./tensorflow/lite/experimental/c/c_api_experimental.h:38:5: error: ‘TFL_InterpreterOptions’ was not declared in this scope
./tensorflow/lite/experimental/c/c_api_experimental.h:38:29: error: ‘options’ was not declared in this scope
     TFL_InterpreterOptions* options, TFL_BuiltinOperator op,
                             ^~~~~~~
./tensorflow/lite/experimental/c/c_api_experimental.h:38:58: error: expected primary-expression before ‘op’
     TFL_InterpreterOptions* options, TFL_BuiltinOperator op,
                                                          ^~
./tensorflow/lite/experimental/c/c_api_experimental.h:39:5: error: expected primary-expression before ‘const’
     const TFL_Registration* registration, int min_version, int max_version);
     ^~~~~
./tensorflow/lite/experimental/c/c_api_experimental.h:39:43: error: expected primary-expression before ‘int’
     const TFL_Registration* registration, int min_version, int max_version);
                                           ^~~
./tensorflow/lite/experimental/c/c_api_experimental.h:39:60: error: expected primary-expression before ‘int’
     const TFL_Registration* registration, int min_version, int max_version);
                                                            ^~~
./tensorflow/lite/experimental/c/c_api_experimental.h:48:5: error: variable or field ‘TFL_InterpreterOptionsAddCustomOp’ declared void
     TFL_InterpreterOptions* options, const char* name,
     ^~~~~~~~~~~~~~~~~~~~~~
./tensorflow/lite/experimental/c/c_api_experimental.h:48:5: error: ‘TFL_InterpreterOptions’ was not declared in this scope
./tensorflow/lite/experimental/c/c_api_experimental.h:48:29: error: ‘options’ was not declared in this scope
     TFL_InterpreterOptions* options, const char* name,
                             ^~~~~~~
./tensorflow/lite/experimental/c/c_api_experimental.h:48:38: error: expected primary-expression before ‘const’
     TFL_InterpreterOptions* options, const char* name,
                                      ^~~~~
./tensorflow/lite/experimental/c/c_api_experimental.h:49:5: error: expected primary-expression before ‘const’
     const TFL_Registration* registration, int min_version, int max_version);
     ^~~~~
./tensorflow/lite/experimental/c/c_api_experimental.h:49:43: error: expected primary-expression before ‘int’
     const TFL_Registration* registration, int min_version, int max_version);
                                           ^~~
./tensorflow/lite/experimental/c/c_api_experimental.h:49:60: error: expected primary-expression before ‘int’
     const TFL_Registration* registration, int min_version, int max_version);
                                                            ^~~
In file included from tensorflow/lite/experimental/c/c_api.cc:21:0:
./tensorflow/lite/experimental/c/c_api_types.h:1:1: error: expected unqualified-id before ‘.’ token
 ../../c/c_api_internal.h

`

**Comment by NarenSuri** [comment]
does anyone know the solution? I got the same error too.

**Comment by NarenSuri** [comment]
@petewarden could you advise in resolving the error above? I have got the same issue, compiling and building lite for raspberry pi

**Comment by jinyige** [comment]
> does anyone know the solution? I got the same error too.
I change the Tensorflow version. Choose the stable version, not the master
