### ISSUE TITLE
build error on latest master 

### ISSUE THREAD

**Issue by guizili0** [tensorflow/tensorflow#27883]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Centos 7.4.1708
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:NA
- TensorFlow installed from (source or binary): source
- TensorFlow version: commit 0e4117f67192a140466ba66513035e24bbd1a474
- Python version: 3.6
- Installed using virtualenv? pip? conda?: source
- Bazel version (if compiling from source):0.22.0
- GCC/Compiler version (if compiling from source): gcc 6.3.0
- CUDA/cuDNN version: NA
- GPU model and memory:NA

**Describe the problem**

**Provide the exact sequence of commands / steps that you executed before running into the problem**
ERROR: /home/guizili/.cache/bazel/_bazel_guizili/fb08bc8aff974002b12a4e85119bd120/external/com_github_googlecloudplatform_google_cloud_cpp/google/cloud/BUILD:27:1: no such target '@bazel_tools//tools/cpp:cc_flags': target 'cc_flags' not declared in package 'tools/cpp' defined by /home/guizili/.cache/bazel/_bazel_guizili/fb08bc8aff974002b12a4e85119bd120/external/bazel_tools/tools/cpp/BUILD and referenced by '@com_github_googlecloudplatform_google_cloud_cpp//google/cloud:generate_build_info'
ERROR: Analysis of target '//tensorflow/tools/pip_package:build_pip_package' failed; build aborted: Analysis failed

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by idrissbellil** [comment]
The same problem here (attempt to build from master) :

- Ubuntu 18.04
- Bazel version: 0.23.1
- Python version: 2.7.15rc1 and 3.6.7

**Comment by npanpaliya** [comment]
This is because, we need bazel 0.24.0 or above to build the latest master. Try with bazel 0.24.0 or 0.24.1.

**Comment by idrissbellil** [comment]
updating Bazel  to 0.24.1 solves this build issue.

**Comment by rootkitchao** [comment]
Here is a tip for compiling the tensorflow master branch.In many cases only certain versions of bazel can be successfully compiled.Check the Continuous build status, read the compile log for the corresponding version, and find the available bazel version.

**Comment by guizili0** [comment]
Thanks all it works on 0.24.1.
Basically, if the bazel version need upgrade, TF will increase the minimal supported version of bazel, that maybe a issue.

**Comment by wdirons** [comment]
The minimal version of bazel was updated yesterday in https://github.com/tensorflow/tensorflow/commit/407a4f3b9d39055a981b91c15f6911fdb38135d5

I think this defect is resolved.

**Comment by jvishnuvardhan** [comment]
I am closing the issue as it was resolved. But, please let me know if I'm mistaken.

**Comment by mrgloom** [comment]
Update 0.23.1 -> 0.25.2 helped.
