### ISSUE TITLE
TypeError: The `train_input_config` must be a input_reader_pb2.InputReader.

### ISSUE THREAD

**Issue by sofeikov** [tensorflow/tensorflow#27894]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
no
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
linux ubuntu 16.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
n\a
- TensorFlow installed from (source or binary):
binary
- TensorFlow version (use command below):
v1.12.0-10232-g9a43dfe 1.13.1
- Python version:
Python 3.7.1
- Bazel version (if compiling from source):
n/a
- GCC/Compiler version (if compiling from source):
n/a
- CUDA/cuDNN version:
n/a
- GPU model and memory:
n/a

**Describe the current behavior**
I've been following examples located here:
https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/running_pets.md

Instead of running it in the Google cloud, I wanted to run it locally. I will attach training configs files below. So when i run this command:
`object_detection/model_main.py --pipeline_config_path=/home/konsof01/work/models/research/pipiline_config.proto
--model_dir=/home/konsof01/tmp
--alsologtostderr`

I get the following error:

> Traceback (most recent call last):
>   File "object_detection/model_main.py", line 109, in <module>
>     tf.app.run()
>   File "/home/konsof01/anaconda3/lib/python3.7/site-packages/tensorflow/python/platform/app.py", line 40, in run
>     _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
>   File "/home/konsof01/anaconda3/lib/python3.7/site-packages/absl/app.py", line 300, in run
>     _run_main(main, args)
>   File "/home/konsof01/anaconda3/lib/python3.7/site-packages/absl/app.py", line 251, in _run_main
>     sys.exit(main(argv))
>   File "object_detection/model_main.py", line 105, in main
>     tf.estimator.train_and_evaluate(estimator, train_spec, eval_specs[0])
>   File "/home/konsof01/anaconda3/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/training.py", line 471, in train_and_evaluate
>     return executor.run()
>   File "/home/konsof01/anaconda3/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/training.py", line 611, in run
>     return self.run_local()
>   File "/home/konsof01/anaconda3/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/training.py", line 712, in run_local
>     saving_listeners=saving_listeners)
>   File "/home/konsof01/anaconda3/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 358, in train
>     loss = self._train_model(input_fn, hooks, saving_listeners)
>   File "/home/konsof01/anaconda3/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1124, in _train_model
>     return self._train_model_default(input_fn, hooks, saving_listeners)
>   File "/home/konsof01/anaconda3/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1151, in _train_model_default
>     input_fn, model_fn_lib.ModeKeys.TRAIN))
>   File "/home/konsof01/anaconda3/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 992, in _get_features_and_labels_from_input_fn
>     self._call_input_fn(input_fn, mode))
>   File "/home/konsof01/anaconda3/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1079, in _call_input_fn
>     return input_fn(**kwargs)
>   File "/home/konsof01/work/models/research/object_detection/inputs.py", line 486, in _train_input_fn
>     raise TypeError('The `train_input_config` must be a '
> TypeError: The `train_input_config` must be a input_reader_pb2.InputReader.

The problem occurs in this piece of code in `inputs.py`:

`
    if not isinstance(train_input_config, input_reader_pb2.InputReader):
      raise TypeError('The `train_input_config` must be a '
                      'input_reader_pb2.InputReader.')
`
However:

> model_pb2.DetectionModel
> <class 'model_pb2.DetectionModel'>
> type(model_config)
> <class 'model_pb2.DetectionModel'>
> 

but `isinstance(train_input_config, input_reader_pb2.InputReader) is False`
Pipeline config file: 
[pipiline_config.proto.zip](https://github.com/tensorflow/tensorflow/files/3085417/pipiline_config.proto.zip)

Why is that?
Thank you

**Describe the expected behavior**

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by jvishnuvardhan** [comment]
@sofeikov This issue is more related TF models repo [here](https://github.com/tensorflow/models/issues). I am closing it here. Please post it in models repo so that the issue has more visibility. Thanks!
