### ISSUE TITLE
DLL load failed while importing tensorflow cpu 2.0

### ISSUE THREAD

**Issue by TyScris** [tensorflow/tensorflow#27890]
(I'm 14yo and I'm french so it's a bit hard... sorry for that i will do my best)
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Win 10 x64
- TensorFlow installed from (source or binary): 
cmd cd C:\Users\Admin\AppData\Local\Programs\Python\Python37\Scripts
Then  pip install tensorflow==2.0.0-alpha0 
Np here
- Python version: 3.7.3

**Describe the current behavior**
I have an error while import tensorflow (cf screen)

**Describe the expected behavior**
tensorflow should import properly

**Code to reproduce the issue**
I install tensorflow as I tell and I try :
import tensorflow

**Other info / logs**
I tried w/ conda, same thing
![clean](https://user-images.githubusercontent.com/30508173/56212750-f4174680-605a-11e9-9b89-a622371760e5.png)

**Comment by ymodak** [comment]
You need to install Microsoft Visual C++ Build Tools 2015. Please take a look instructions given on https://www.tensorflow.org/install/pip. Select Windows in steps 1 and 2.

**Comment by ymodak** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
