### ISSUE TITLE
Can't easily write custom C++ ops which update resource variables

### ISSUE THREAD

**Issue by girving** [tensorflow/tensorflow#27899]
**System information**
- TensorFlow version (you are using): HEAD
- Are you willing to contribute it (Yes/No): No (moving headers is best done inside Google)

**Describe the feature and the current behavior/state.**

We're trying to update optimizers like the ones at https://github.com/openai/blocksparse/blob/master/blocksparse/optimize.py to support parameters stored as resource variables. Looking at the TensorFlow source code for the built-in optimizer ops, it seems necessary to have relatively complicated locking and copy-on-write logic to handle the different states a resource variable could be in. TensorFlow uses helper functions in [`core/kernels/training_op_helpers.h`](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/kernels/training_op_helpers.h) to do this, calling `MaybeLockVariableInputMutexesInOrder` and `GetInputTensorFromVariable`.

Unfortunately, `training_op_helpers.h` is not in the public TensorFlow headers, so we can't just `#include` it. Worse, it depends on internal functions that `libtensorflow_framework.so` doesn't even export (notably, `tensorflow::functor::DenseUpdate` for the copy-on-write), so copying the headers also doesn't suffice.

Can we move this file and the relevant dependencies into `framework` or a similarly public location?

**Will this change the current api? How?**

Yes.  Those helpers would become public.

**Who will benefit with this feature?**

People writing new C++ optimizers.

**Any Other info.**

Related StackOverflow question (cc @daniel-ziegler): https://stackoverflow.com/questions/55661246/how-to-write-custom-c-ops-which-update-resource-variables

**Comment by aselle** [comment]
@alextp, do we have any better solution than exposing this api surface to solve Geoffrey's needs?

**Comment by alextp** [comment]
I don't have a plan to expose this in a better way, but I think this should be doable as a PR (no weird internal dependencies I can think of) so I'll mark as contributions welcome now.
