### ISSUE TITLE
[TF 2.0] documentation in guides for feature columns, in particular `numeric_column`

### ISSUE THREAD

**Issue by lendle** [tensorflow/tensorflow#27895]
**System information**
- TensorFlow version: 2.0.0-alpha0
- Doc Link: https://www.tensorflow.org/alpha

Guides/examples that use feature columns follow a bad pattern for numeric features. In particular, the examples in the guides always create a list of scalar `numeric_column`s instead of one `numeric_column` with all numeric features. This results in really bad performance when training. See [this thread](https://groups.google.com/a/tensorflow.org/d/msg/discuss/Vt0JGKF_Bno/S5XXmdaoCQAJ).
Locations in the docs (there may be others I missed): 
* https://www.tensorflow.org/alpha/tutorials/estimators/linear#base_feature_columns
* https://www.tensorflow.org/guide/estimators#structure_of_a_pre-made_estimators_program
* https://www.tensorflow.org/alpha/tutorials/keras/feature_columns#choose_which_columns_to_use
* https://www.tensorflow.org/alpha/tutorials/estimators/boosted_trees#create_feature_columns_and_input_functions
* https://www.tensorflow.org/alpha/tutorials/estimators/boosted_trees_model_understanding#create_feature_columns_input_fn_and_the_train_the_estimator

The '[Feature Columns guide](https://www.tensorflow.org/guide/feature_columns)' from TF 1 or anything analogous is not available in the [TF 2 docs](https://www.tensorflow.org/alpha). That guide does mention the shape parameter, but does not discuss performance at all, and also describes creating a separate `numeric_column` for each feature in the Iris dataset in [this section](https://www.tensorflow.org/guide/feature_columns#numeric_column).

**Comment by karmel** [comment]
@random-forests -- what is the status of that guide? Do we have someone working on it?

Regarding the performance issues, @lendle , would you be interested in submitting a PR to one of the colabs to illustrate what you mean? Or creating a separate tutorial discussing the performance implications of decisions around feature columns?

**Comment by lendle** [comment]
@karmel the thread I referenced in the issue links to a jupyter notebook gist that illustrates the performance issues. I won't have time to provide more than that for the time being.

**Comment by random-forests** [comment]
@lendle, thank you for this feedback! @karmel, we don't have anyone working on a FC guide from my side. We do have a contributor hacking on an update "Classify structured data" tutorial to use the Pet Finder dataset https://www.kaggle.com/c/petfinder-adoption-prediction/data, which is a bit more fun / real-world. I'll share this thread with her so we can avoid these performance problems in the new tutorial at least.

**Comment by lamberta** [comment]
. @MarkDaoust added an example of a fix in https://github.com/tensorflow/docs/commit/05db4b0b1aa2e399898f10886585b19c611a85c5 if someone is available to apply it across the other notebooks that are listed here.

**Comment by JvPy** [comment]
Still open? would like to help

**Comment by Saduf2019** [comment]
@lendle please confirm if the issue still exist

**Comment by Saduf2019** [comment]
Moving this to closed status as there is no response.

**Comment by MarkDaoust** [comment]
Some of these got fixed, we're moving away from feature-columns, but we are sure in newer docs avoid this sort of issue with equivalent keras layers.
