### ISSUE TITLE
Transforming date values

### ISSUE THREAD

**Issue by Malonl** [tensorflow/tensorflow#27893]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using): 1.13.1
- Are you willing to contribute it (Yes/No): No 

**Describe the feature and the current behavior/state.**
Hi.

I have a use case where I want to use date features as input values for a predictive model. I need to transform the date features to be useful.
For example, I need to know the difference between two dates (for example, just the difference in days between 01-04-2019 and 16-04-2019, but the dates can also be months or years apart).
Or just getting the day of the month, the month itself or the year (i.e. for 16-04-2019, getting 16, 4 and 2019 as seperate values).

My question is if it is possible to do this within TFX and if not, is this a feature that is coming up?
It would be important for my use case because the transform needs to be done in the graph format so that I can serve the model with the transformations inside the pipeline.
Otherwise I would need to add something that can do this for me outside of TFX.

Thanks in advance!

Martijn

**Comment by Efaq** [comment]
Same issue here!

**Comment by jvishnuvardhan** [comment]
@Malonl Could you post this in [transform](https://github.com/tensorflow/transform/issues) or [tfx](https://github.com/tensorflow/tfx/issues) repos as it is more related to them. Please post i t there and then close here. Thanks!

**Comment by Malonl** [comment]
@jvishnuvardhan I will. Thank you.
