### ISSUE TITLE
saved_model.load gives KeyError in 2.0.0 Same model loads fine in 1.13

### ISSUE THREAD

**Issue by imikic** [tensorflow/tensorflow#27904]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- TensorFlow installed from (source or binary):binary
- TensorFlow version (use command below): 2.0.0
- Python version: 3.6.5

**Describe the current behavior**
I am trying to load a model saved in 1.x in 2.0.0. Here is the model: https://storage.googleapis.com/marco-168219-model/savedmodel.zip

This is the error I am getting: KeyError: <tf.Tensor 'map/while/Switch_1:0' shape=() dtype=float32>

The same model loads fine in 1.13

**Describe the expected behavior**

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

model = tf.saved_model.load(model_dir)

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by allenlavoie** [comment]
Could you try a more recent 2.0 nightly? This SavedModel is loading for me in 2.0.0-dev20190416. It was likely fixed by https://github.com/tensorflow/tensorflow/commit/36611db67d01b77a59ecf120d9cfedede4dc29e8#diff-1c53130b8026996623d861b2d18d60ca

**Comment by imikic** [comment]
Yes, it works with today's nightly. Thank you!
