### ISSUE TITLE
ResizeBilinear FP16 CUDA Kernel Support

### ISSUE THREAD

**Issue by mhurliman** [tensorflow/tensorflow#27902]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): no
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 1.13.1
- Python version: 3.6
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 10/7.4.1
- GPU model and memory: NVIDIA Titan V

**Describe the current behavior**
The resize bilinear CUDA kernel omits FP16 support. The implementation accepts a templated tensor type, but then internally performs a hard-cast to a float during filtering, which is then written to a float tensor. Couldn't the templated type be propagated to the output as in resize nearest neighbor?

This causes a significant and anomalous perf drop when converting from FP32 to FP16 in networks that utilize this operation.

**Describe the expected behavior**
An FP16 variant would be implemented alongside the FP32 CUDA implementation, with performance scaling appropriately between the two.

**Comment by ymodak** [comment]
In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thanks!

**Comment by mhurliman** [comment]
At its core this is a feature request, not a bug report. I just happened upon the missing feature through a performance drop. 
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/kernels/resize_bilinear_op_gpu.cu.cc#L350

**Comment by mhurliman** [comment]
I did a quick-n-dirty conversion yesterday to just accept a second templated parameter throughout the call-stack and registration code - it just casts it at the beginning/end of the kernel. It built successfully but haven't gotten time to test it at all. 

If it works I'll test the performance against a version that casts and performs all computations in the template type to determine whether its worth the additional code changes.

The commit is visible on my TF fork here: https://github.com/mhurliman/tensorflow/commit/6d807626656708d833552c888a749b93e7a726b6

**Comment by x10000year** [comment]
any update? @mhurliman

**Comment by sanjoy** [comment]
@mhurliman, I'd be happy to review a PR that fixes this.

**Comment by mhurliman** [comment]
I've been off this for a long time, haha. I don't know the state of this code in the main repository now. Has anything changed with the bilinear upscale kernel since May?

**Comment by mhurliman** [comment]
I guess the update would be that I didn't get to testing the performance. It's a pretty simple change, should be able to cherry-pick the commit easily enough and create a small test network.

**Comment by x10000year** [comment]
@mhurliman Great! Really need this feature!

**Comment by rmothukuru** [comment]
@mhurliman,
Sorry for the delayed response. Can you please let us know if the functionality you are looking for can be achieved using [Post Training Quantization](https://www.tensorflow.org/lite/performance/post_training_quantization), as it supports **`Floating Point 16 operations`** with **`GPU`**? Thanks!
