### ISSUE TITLE
pydoc.ErrorDuringImport: problem in tensorflow.keras - ImportError: cannot import name 'Layer'

### ISSUE THREAD

**Issue by bjayakumar** [tensorflow/tensorflow#27900]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Centos 7
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: NA
- TensorFlow installed from (source or binary): Binary
- TensorFlow version: 1.13.1
- Python version: 3.6.8
- Installed using virtualenv? pip? conda?: Conda
- Bazel version (if compiling from source): Nope
- GCC/Compiler version (if compiling from source): Nope
- CUDA/cuDNN version: CUDA Version 10.1.105 /7

- GPU model and memory:  GeForce GTX 1080 Ti and  11178 MiB

**Describe the problem**
I get the error when I was importing keras.

**Provide the exact sequence of commands / steps that you executed before running into the problem**
    `from tensorflow.python.estimator.keras import Layer`

**Any other info / logs**
`Traceback (most recent call last):
  File "/home/bjayakumar/.conda/envs/py36/lib/python3.6/pydoc.py", line 343, in safeimport
    module = __import__(path)
  File "/home/bjayakumar/.conda/envs/py36/lib/python3.6/site-packages/tensorflow/keras/__init__.py", line 20, in <module>
    from . import layers
  File "/home/bjayakumar/.conda/envs/py36/lib/python3.6/site-packages/tensorflow/keras/layers/__init__.py", line 8, in <module>
    from tensorflow.python.estimator.keras import Layer
ImportError: cannot import name 'Layer'`

This solution is not working for me.
**https://github.com/tensorflow/tensorflow/issues/24847**

**Comment by ymodak** [comment]
Can you try with,
```from tensorflow.keras.layers import Layer```

**Comment by ymodak** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Comment by shivam5285** [comment]
> Can you try with,
> `from tensorflow.keras.layers import Layer`

I also have same issue. When I tried this I got following error
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/shivam/.local/lib/python3.6/site-packages/tensorflow/keras/__init__.py", line 20, in <module>
    from . import layers
  File "/home/shivam/.local/lib/python3.6/site-packages/tensorflow/keras/layers/__init__.py", line 8, in <module>
    from tensorflow.python.estimator.keras import Layer
ImportError: cannot import name 'Layer'

**Comment by jss367** [comment]
> Can you try with,
> `from tensorflow.keras.layers import Layer`

I tried that and got this error:

```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-4-2c540853ba16> in <module>
----> 1 from tensorflow.keras.layers import Layer

C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\keras\__init__.py in <module>
     18 from tensorflow.keras import estimator
     19 from tensorflow.keras import initializers
---> 20 from tensorflow.keras import layers
     21 from tensorflow.keras import losses
     22 from tensorflow.keras import metrics

C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\keras\layers\__init__.py in <module>
      6 from __future__ import print_function
      7 
----> 8 from tensorflow.python.estimator.keras import Layer
      9 from tensorflow.python.keras import Input
     10 from tensorflow.python.keras.applications.densenet import Activation

ImportError: cannot import name 'Layer' from 'tensorflow.python.estimator.keras' (C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\estimator\keras.py)
```
I fixed it by upgrading to the latest version of tensorflow.

**Comment by namwoo-konkuk** [comment]
try to downgrade keras=2.3.0 with tensorflow=2.2.0

**Comment by Tango-GauriBhatnagar** [comment]
Installing keras via pip & conda both worked for me.
pip install keras.
conda install keras
