### ISSUE TITLE
Issue re-building with Dockerfile.devel-gpu file

### ISSUE THREAD

**Issue by maxmelnick** [tensorflow/tensorflow#2790]
I tried to build my own version of the `Dockerfile.devel-gpu` with the instructions on [this page](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/tools/docker) but got the error as seen in the details below. 

After doing some troubleshooting I noticed the `tensorflow/core` folder wasn't getting created by the `git clone` statement that's in the `Dockerfile.devel-gpu` so I updated it to explicitly clone the `-b r0.8` branch and it worked successfully. See below for detailed updates. Is this the proper approach to take to resolve this issue or am I missing something? 

**Executed this command**

`$ docker build --pull -t $USER:tensorflow-suffix -f Dockerfile.devel-gpu .`

**Got this error**

```
...
INFO: Reading 'startup' options from /root/.bazelrc: --batch
Extracting Bazel installation...
____Loading package: tensorflow/tools/pip_package
____Loading...
____Loading package: tensorflow/core
____Loading package: tensorflow/models/image/cifar10
ERROR: /tensorflow/tensorflow/tools/pip_package/BUILD:23:1: error loading package 'tensorflow/core': Extension file not found. Unable to load package for '//google/protobuf:protobuf.bzl': BUILD file not found on package path and referenced by '//tensorflow/tools/pip_package:build_pip_package'.
ERROR: Loading failed; build aborted.
____Elapsed time: 1.802s
The command '/bin/sh -c ./configure &&     bazel build -c opt --config=cuda tensorflow/tools/pip_package:build_pip_package &&     bazel-bin/tensorflow/tools/pip_package/build_pip_package /tmp/pip &&     pip install --upgrade /tmp/pip/tensorflow-*.whl' returned a non-zero code: 1
```

**Select contents of Dockerfile.devel-gpu BEFORE (results in error)**

`RUN git clone --recursive https://github.com/tensorflow/tensorflow.git && \
    cd tensorflow && \
    git checkout r0.8`

**Select contents of Dockerfile.devel-gpu AFTER (working successfully)**

`RUN git clone -b r0.8 --recursive https://github.com/tensorflow/tensorflow.git && \
    cd tensorflow && \
    git checkout r0.8`

### Environment info
Operating System: Ubuntu 14.04.3 LTS (GNU/Linux 3.13.0-74-generic x86_64)

Installed version of CUDA and cuDNN: Using `nvidia/cuda:7.5-cudnn4-devel` as base image for Docker build

Docker version 1.11.2, build b9f10c9

**Comment by girving** [comment]
@caisq Can you comment?

**Comment by maxmelnick** [comment]
It looks like the regular `git clone https://github.com/tensorflow/tensorflow.git` command is now including the tensorflow/core folder again. Not sure if this was a caching issue on my end but all good now. Thanks!

**Comment by cancan101** [comment]
@maxmelnick What was the solution to this?

**Comment by gnujimmik** [comment]
Do you know if it will work on ubuntu16.04? I have tried it with the git clone -b ~, but still not working.

**Comment by maxmelnick** [comment]
@cancan101 Unfortunately, I'm not exactly sure what the solution was because it all of a sudden started working again. I think it may have been a caching issue, but can't say for sure.

**Comment by cancan101** [comment]
I actually go it to work by adding the `-b r0.8` to the clone command.
