### ISSUE TITLE
TensorFlowLite: failed to load native library: Library tensorflowlite_jni not found; at  /system/lib64

### ISSUE THREAD

**Issue by schawla1988** [tensorflow/tensorflow#27918]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):  downloaded .aar file from https://mvnrepository.com/artifact/org.tensorflow/tensorflow-lite/1.13.1
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: Samsung Galaxy A5
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 1.13.1
- Python version: 3.7
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: NA
- GPU model and memory: NA

You can collect some of this information using our environment capture [script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with
python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"

**Describe the current behavior** Trying to load .tflite file on Android device. Getting error "TensorFlowLite: failed to load native library: Library tensorflowlite_jni not found; at  /system/lib64". It is not able to find the tensorflowlite_jni.so at /system/lib64 path. If I push the file to /system/lib64 path in device it works

**Describe the expected behavior**: It should work without the requirement of external push

**Code to reproduce the issue**: 1. Generate a .tflite file after model training on desktop
2. download .aar file from https://mvnrepository.com/artifact/org.tensorflow/tensorflow-lite/1.13.1
3. Build Android binary using downloaded .aar file and .tflite file along with Android Application trying to load .tflite file
4. Run time error while app is trying to load the .tflite file
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

04-17 17:50:00.518  4470  4470 W **System.err: TensorFlowLite: failed to load native library: Library tensorflowlite_jni not found; tried [/system/lib64/libtensorflowlite_jni.so]** 04-17 17:50:00.519  4470  4470 W System.err: TensorFlowLite: failed to load native library: Library tensorflowlite_jni not found; tried [/system/lib64/libtensorflowlite_jni.so] 04-17 17:50:00.528  8077  8077 D OpenGLRenderer: Skia GL Pipeline 04-17 17:50:00.539  5932  5959 V ContactsProvider_EventLog: contents_sample_query: [ uri = content://com.android.contacts/contacts(usr:0), pkg = com.samsung.android.bixby.service(6596), prj = [name_raw_contact_id, contact_last_updated_timestamp], sel = name_raw_contact_id <= 1 AND ( contact_last_updated_timestamp > 1555500415060 OR (contact_last_updated_timestamp = 1555500415060 AND name_raw_contact_id > 1 )), selArg = null, so = contact_last_updated_timestamp ASC LIMIT 300, cv = null, dur = 27, ret = 0, trw = false ] 04-17 17:50:00.541  8077  8077 D EmergencyMode: [EmergencyManager] android createPackageContext successful 04-17 17:50:00.543  4470  4470 E system_server: No implementation found for long org.tensorflow.lite.NativeInterpreterWrapper.createErrorReporter(int) (tried Java_org_tensorflow_lite_NativeInterpreterWrapper_createErrorReporter and Java_org_tensorflow_lite_NativeInterpreterWrapper_createErrorReporter__I) 04-17 17:50:00.544  4470  4470 E Zygote  : System zygote died with exception 04-17 17:50:00.544  4470  4470 E Zygote  : java.lang.UnsatisfiedLinkError: No implementation found for long org.tensorflow.lite.NativeInterpreterWrapper.createErrorReporter(int) (tried Java_org_tensorflow_lite_NativeInterpreterWrapper_createErrorReporter and Java_org_tensorflow_lite_NativeInterpreterWrapper_createErrorReporter__I) 04-17 17:50:00.544  4470  4470 E Zygote  :     at org.tensorflow.lite.NativeInterpreterWrapper.createErrorReporter(Native Method) 04-17 17:50:00.544  4470  4470 E Zygote  :     at org.tensorflow.lite.NativeInterpreterWrapper.<init>(NativeInterpreterWrapper.java:73) 04-17 17:50:00.544  4470  4470 E Zygote  :     at org.tensorflow.lite.NativeInterpreterWrapper.<init>(NativeInterpreterWrapper.java:54) 04-17 17:50:00.544  4470  4470 E Zygote  :     at org.tensorflow.lite.Interpreter.<init>(Interpreter.java:114) 04-17 17:50:00.544  4470  4470 E Zygote  :     at android.hardware.VirtualProximityService.initTflite(VirtualProximityService.java:184) 04-17 17:50:00.544  4470  4470 E Zygote  :     at android.hardware.VirtualProximityService.onCreate(VirtualProximityService.java:99) 04-17 17:50:00.544  4470  4470 E Zygote  :     at android.app.ActivityThread.handleCreateService(ActivityThread.java:3757) 04-17 17:50:00.544  4470  4470 E Zygote  :     at android.app.ActivityThread.access$1400(ActivityThread.java:237) 04-17 17:50:00.544  4470  4470 E Zygote  :     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808) 04-17 17:50:00.544  4470  4470 E Zygote  :     at android.os.Handler.dispatchMessage(Handler.java:106) 04-17 17:50:00.544  4470  4470 E Zygote  :     at android.os.Looper.loop(Looper.java:214) 04-17 17:50:00.544  4470  4470 E Zygote  :     at com.android.server.SystemServer.run(SystemServer.java:802) 04-17 17:50:00.544  4470  4470 E Zygote  :     at com.android.server.SystemServer.main(SystemServer.java:624) 04-17 17:50:00.544  44
04-17 17:50:00.544  4470  4470 E Zygote  :     at com.android.server.SystemServer.main(SystemServer.java:624) 04-17 17:50:00.544  4470  4470 E Zygote  :     at java.lang.reflect.Method.invoke(Native Method) 04-17 17:50:00.544  4470  4470 E Zygote  :     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 04-17 17:50:00.544  4470  4470 E Zygote  :     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:945) 04-17 17:50:00.545  4470  4470 D AndroidRuntime: Shutting down VM

**Comment by Dayananda-V** [comment]
@schawla1988 

would you share the below deatils to help you out the above problem,
1- build script which use to compile android app? 
2- your handset cpu abi version(adb shell getprop ro.product.cpu.abi)?
3- sdk and ndk version which you configure with tensorflow?

**Comment by tzy0204** [comment]
I faced the same problem, @schawla1988 's solution is not working for me, could anybody have idea?
Thanks.

**Comment by jdduke** [comment]
It looks like you're trying to reference the shared library from a system service? In which case, it's your responsibility to put the native shared library where it can be used.
