### ISSUE TITLE
[CI] Ubuntu CC  is still "Expected — Waiting for status to be reported" after 14 days.

### ISSUE THREAD

**Issue by leemgs** [tensorflow/tensorflow#27916]
It is strange. Let's see the operation status of Tensorflow CI on  PR #27466.  The work status of **Ubuntu CC**  is still "**Expected — Waiting for status to be reported**" even though 14 days is passed after the contributor submitted PR #27466. Why does not `Ubuntu CC`  report the result either PASS or FAILURE? Why Ubuntu CC is still running for 14 days?

* https://github.com/tensorflow/tensorflow/pull/27466
![image](https://user-images.githubusercontent.com/82404/56286270-50aa5c80-6154-11e9-993c-e2c6188d823b.png)

Above all, lots of PRs do not have got the execution result of Tensorflow CI.  Please see the red circles below. Why these situations have repeatedly generated?

![image](https://user-images.githubusercontent.com/82404/56286707-5fddda00-6155-11e9-846a-177ccaa3e9ee.png)

**Comment by gadagashwini** [comment]
@leemgs The yellow dot essentially means that not all checks have run. We don't run all the checks until a reviewer has approved the PR. Hope that clarifies it.

**Comment by leemgs** [comment]
> We don't run all the checks until a reviewer has approved the PR. Hope that clarifies it.

Is it mean that the CI system does not report any results until a reviewer has approved the PR? It's weird. It is not helpful to the reviewers because the CI system works as one of the reviewers. In general, the major goal of the CI system is to help the reviewer (without the final approver of the PR).
