### ISSUE TITLE
tf-2.0: AttributeError: module 'tensorflow' has no attribute 'optimizers'

### ISSUE THREAD

**Issue by LGTrader** [tensorflow/tensorflow#27929]
**System information**
- OS Platform and Distribution Ubuntu 18.04 LTS
- TensorFlow installed from source or binary): source
- TensorFlow version (use command below): v2.0.0-alpha0-4-g2c2d508 2.0.0-alpha0
- Python version: 3.5.7
- Bazel version (if compiling from source): From docker image
- GCC/Compiler version (if compiling from source): From docker image
- CUDA/cuDNN version: NA
- GPU model and memory: NA

**Describe the current behavior**
This documentation suggests there are 4 ways to load an optimizer:
https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/optimizers

However:

(tf_35) mark@science:~$ python tf_optimizers.py 
Traceback (most recent call last):
  File "tf_optimizers.py", line 7, in <module>
    opt4 = tf.optimizers.Adagrad
AttributeError: module 'tensorflow' has no attribute 'optimizers'

**Describe the expected behavior**

opt = tf.optimizers.Adagrad doesn't work. The first 3 methods do.

**MINIMAL code to reproduce the issue**

import tensorflow as tf
tf.__version__

opt1 = tf.compat.v2.keras.optimizers.Adagrad
opt2 = tf.compat.v2.optimizers.Adagrad
opt3 = tf.keras.optimizers.Adagrad
opt4 = tf.optimizers.Adagrad

I don't know if this is a documentation issue or a tensorflow bug.

**Comment by jvishnuvardhan** [comment]
@LGTrader I don't see any issue. Here is the [gist](https://colab.sandbox.google.com/gist/jvishnuvardhan/8cc804d896d0bb5a107635d7566ea708/untitled103.ipynb).

Please make sure you have installed TF2.0. When I tried the above gist with TF1.13.1, it has thrown an error. So those four links work well for TF2.0 only. Please let me know what you think. If you agree, please close the issue. Thanks!

**Comment by LGTrader** [comment]
@jvishnuvardhan 

I reworked the code and ran it in Jupyter Notebook on my system. I cannot download the same TF2.0 alpha version that you use because my CPU doesn't have an instruction set (AVX I think) that is now required so my version is built locally from the same code as of a couple of weeks ago. It does identify as 2.0-alpha-0

Also, a simple call to help(tf) actually does not show tf.optimizers as an option but does show tf.compat and tf.keras so I think everything is consistent.

For now I'm going to assume that possibly I caught the code in a weird state when I built this and will close the report. If I get a chance to rebuild newer code and still see it I think I can reopen it and we'll try again. If you think it's important to keep looking at this I assume you can reopen also?

Thanks!


import tensorflow as tf
print(tf.__version__)
opt1 = tf.compat.v2.keras.optimizers.Adagrad
opt2 = tf.compat.v2.optimizers.Adagrad
opt3 = tf.keras.optimizers.Adagrad
print(opt1)
print(opt2)
print(opt3)
2.0.0-alpha0
<class 'tensorflow.python.keras.optimizer_v2.adagrad.Adagrad'>
<class 'tensorflow.python.keras.optimizer_v2.adagrad.Adagrad'>
<class 'tensorflow.python.keras.optimizer_v2.adagrad.Adagrad'>
opt4 = tf.optimizers.Adagrad
print(opt4)
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-15-a356bbac2b8f> in <module>
----> 1 opt4 = tf.optimizers.Adagrad
      2 print(opt4)

AttributeError: module 'tensorflow' has no attribute 'optimizers'





Help on package tensorflow:

NAME
    tensorflow - Bring in all of the public TensorFlow interface into this module.

PACKAGE CONTENTS
    _api (package)
    app (package)
    audio (package)
    autograph (package)
    bitwise (package)
    compat (package)
    compiler (package)
    config (package)
    contrib (package)
    core (package)
    data (package)
    debugging (package)
    distribute (package)
    distributions (package)
    dtypes (package)
    errors (package)
    estimator (package)
    examples (package)
    experimental (package)
    feature_column (package)
    gfile (package)
    graph_util (package)
    image (package)
    initializers (package)
    io (package)
    keras (package)
    layers (package)
    libtensorflow_framework
    linalg (package)
    lite (package)
    logging (package)
    lookup (package)
    losses (package)
    manip (package)
    math (package)
    metrics (package)
    nest (package)
    nn (package)
    profiler (package)
    python (package)
    python_io (package)
    quantization (package)
    queue (package)
    ragged (package)
    random (package)
    raw_ops (package)
    resource_loader (package)
    saved_model (package)
    sets (package)
    signal (package)
    sparse (package)
    spectral (package)
    strings (package)
    summary (package)
    sysconfig (package)
    test (package)
    tools (package)
    tpu (package)
    train (package)
    user_ops (package)
    v1
    version (package)

**Comment by jvishnuvardhan** [comment]
@LGTrader I am reopening it as I noticed Attribute error with tf-nightly. I don't see any issue with TF2.0.0-alpha0. We need to check whether we need to update tf-nightly or the docs on website. Thanks for finding this issue. 

AttributeError                            Traceback (most recent call last)
<ipython-input-2-a368a9a6e043> in <module>()
      3 opt2 = tf.compat.v2.optimizers.Adagrad
      4 opt3 = tf.keras.optimizers.Adagrad
----> 5 opt4 = tf.optimizers.Adagrad

/usr/local/lib/python3.6/dist-packages/tensorflow/python/util/deprecation_wrapper.py in __getattr__(self, name)
    104     if name.startswith('_dw_'):
    105       raise AttributeError('Accessing local variables before they are created.')
--> 106     attr = getattr(self._dw_wrapped_module, name)
    107     if (self._dw_warning_count < _PER_MODULE_WARNING_LIMIT and
    108         name not in self._dw_deprecated_printed):

AttributeError: module 'tensorflow' has no attribute 'optimizers'

**Comment by LGTrader** [comment]
Thanks. You saved me building again. (about 4 hours on my machine) I'll look for feedback in this thread and rebuild to verify fixes later if appropriate.

**Comment by tanzhenyu** [comment]
I think the latest change to enable tf.optimizers.Adagrad might not be in the alpha0 release, can you install nightly and try it? pip install tf-nightly-gpu-2.0-preview

**Comment by LGTrader** [comment]
I cannot install any of the prebuilt versions of TF as they depend on the AVX instruction set and my Intel i7-980 Extreme processor doesn't have that. This requires I build from source. You can get an overview of what I go through to build here:

https://github.com/tensorflow/tensorflow/issues/26553

I'm very happy to try out any specific Docker image (to get the GPU support) and version of Tensorflow you'd like me to try but I'm not a coding professional and I sometimes need a little hand holding. ;-) I'll investigate getting the preview version you mention.

**Comment by tanzhenyu** [comment]
Ah thanks for letting me know your constraint. As an alternative approach, you could easily try your code by running in [Google Colab](https://colab.sandbox.google.com/notebooks/welcome.ipynb#recent=true), and once verified we could worry about the rebuilding issue.

**Comment by LGTrader** [comment]
I've not used Colab but have been meaning to investigate. I'm not clear if I have to pay for access so any info for individual user types like me is much appreciated but I'll certainly check it out. Thanks!

**Comment by LGTrader** [comment]
OK, I'm running in Colab but it's importing tf-1.13.1. I need to find the right way to import and will get back to you when I am across that threshold. Thanks!

**Comment by jvishnuvardhan** [comment]
@LGTrader Google colab is free. Earlier I shared a colab gist [here](https://github.com/tensorflow/tensorflow/issues/27929#issuecomment-486464851). Just open it and run.Thanks!

**Comment by tanzhenyu** [comment]
I think as long as you have a google account (for example using your GMail), then Colab is free. 
A very fun fact is that Colab just starts to support Tesla T4 (though I think you are relying on CPU but not GPU), but just FYI for whoever is interested.
@martinwicke

**Comment by LGTrader** [comment]
Yes, it's up and running for me. I'm sure Google will shut me down if I do anything too expensive but it stores notebooks on my Google Drive and I've duplicated  jvishnuvardhan 's example.

I'll continue doing small stuff in Colab so learn more but I think the next step is to possibly rebuild here from source and make sure I don't see the problem anymore. I'm working on setting up the Docker stuff as I write. I need to find the right command to git clone tf-nightly-gpu-2.0-preview and I'll go to work on that 6 hour build.

Thanks!

**Comment by tanzhenyu** [comment]
Thank you for confirming with us! Closing it now.
