### ISSUE TITLE
[CI] Is TensorFlow-jenkins bot died?

### ISSUE THREAD

**Issue by leemgs** [tensorflow/tensorflow#27939]
Has Tensoflow-Jenkins bot been running now? We could  get the some messages from the bot when PR was submitted in the past (e.g., PR #13557). However, It seems that we could not see the any activity of the Tensoflow-Jenkins bot recently. What is the CI infrastructure  (e.g., Jenkins, Kokoro, Travis-CI, Circle-CI, and so on)of the Tensorflow deep-learning framework?

* Example: PR #24314 (On Dec-13-2019)
![image](https://user-images.githubusercontent.com/82404/56335313-f6061480-61d6-11e9-9118-c8d4ff11c39e.png)

* Example: PR #20809 (On Jun-4-2019)
![image](https://user-images.githubusercontent.com/82404/56335253-b5a69680-61d6-11e9-9795-045c7b0fb94e.png)

* Example: PR #13557 (On Oct-8-2017)
![image](https://user-images.githubusercontent.com/82404/56335169-652f3900-61d6-11e9-9d5f-a6ea642bb606.png)

**Comment by ymodak** [comment]
Closing this issue since it is not related TensorFlow modules. Thanks!
