### ISSUE TITLE
Read timed out and referenced by '//tensorflow/tools/pip_package:licenses'

### ISSUE THREAD

**Issue by liqi-c** [tensorflow/tensorflow#27938]
bazel build --config=opt //tensorflow/tools/pip_package:build_pip_package   
 Fetching @jpeg; fetching 167s
ERROR: /mnt/d/Project/TensorFlow/tensorflow-master/tensorflow/tools/pip_package/BUILD:145:1: no such package '@grpc//third_party/address_sorting': java.io.IOException: Error downloading [http://mirror.tensorflow.org/github.com/grpc/grpc/archive/4566c2a29ebec0835643b972eb99f4306c4234a3.tar.gz, https://github.com/grpc/grpc/archive/4566c2a29ebec0835643b972eb99f4306c4234a3.tar.gz] to /home/qili/.cache/bazel/_bazel_qili/f937d3405457c6b857b73c6deab45175/external/grpc/4566c2a29ebec0835643b972eb99f4306c4234a3.tar.gz: Read timed out and referenced by '//tensorflow/tools/pip_package:licenses'
ERROR: Analysis of target '//tensorflow/tools/pip_package:build_pip_package' failed; build aborted: no such package '@grpc//third_party/address_sorting': java.io.IOException: Error downloading [http://mirror.tensorflow.org/github.com/grpc/grpc/archive/4566c2a29ebec0835643b972eb99f4306c4234a3.tar.gz, https://github.com/grpc/grpc/archive/4566c2a29ebec0835643b972eb99f4306c4234a3.tar.gz] to /home/qili/.cache/bazel/_bazel_qili/f937d3405457c6b857b73c6deab45175/external/grpc/4566c2a29ebec0835643b972eb99f4306c4234a3.tar.gz: Read timed out
INFO: Elapsed time: 168.452s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded, 0 targets configured)

**Comment by liqi-c** [comment]
How can i configure to avoid Time out problem ?

**Comment by liqi-c** [comment]
网速问题，很多工具无法成功下载，导致安装一直失败，尝试过用本地下载安装无法安装的工具，但是安装之后，用bazel安装依旧会自己下载 
最后多次尝试安装，网络好的时候就能装上  
或者只用安装某些工具，我只需要其中的一个工具，最后放弃整个pip_package安装，只安装了某些工具 
sudo bazel build --config=noaws tensorflow/tools/graph_transforms:summarize_graph

**Comment by muddham** [comment]
@liqi-c  May I request you to post your reply in english and also, It looks like you haven't used a template to create this issue. Please resubmit your issue using a template from [here](https://github.com/tensorflow/tensorflow/issues/new/choose). We ask users to use the template because it reduces overall time to resolve a new issue by avoiding extra communication to get to the root of the issue. We will close this issue in lieu of the new one you will create from the template. Thank you for your cooperation.

**Comment by muddham** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
