### ISSUE TITLE
NameError: name 'MyCapper' is not defined

### ISSUE THREAD

**Issue by monjoybme** [tensorflow/tensorflow#27932]
For gardient clipping in case of Adam optimizer, I'm using below code. 
```
# Create an optimizer.
opt = AdamOptimizer(learning_rate=0.1)

# Compute the gradients for a list of variables.
grads_and_vars = opt.compute_gradients(loss)

# grads_and_vars is a list of tuples (gradient, variable).  Do whatever you
# need to the 'gradient' part, for example cap them, etc.
capped_grads_and_vars = [(MyCapper(gv[0]), gv[1]) for gv in grads_and_vars]

# Ask the optimizer to apply the capped gradients.
opt.apply_gradients(capped_grads_and_vars)
```
But I'm getting error 

> NameError: name 'MyCapper' is not defined

**Fulltraceback:**

`grads = [(MyCapper(gv[0]), gv[1]) for gv in grads_and_vars]

NameError: name 'MyCapper' is not defined`

Pleae help.

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: NA
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 1.10.0
- Python version: 3.6.5
- Bazel version (if compiling from source): NA
- GCC/Compiler version (if compiling from source): 7.2.0
- CUDA/cuDNN version: Cuda compilation tools, release 9.0, V9.0.176
- GPU model and memory: Tesla V100 

You can collect some of this information using our environment capture [script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with
python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"

**Describe the current behavior**

**Describe the expected behavior**

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by muddham** [comment]
@monjoybme In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thanks!

**Comment by monjoybme** [comment]
The above code snippet is taken from the official TensorFlow website [link](https://www.tensorflow.org/api_docs/python/tf/train/Optimizer). `MyCapper` function has been called there.

**Comment by jvishnuvardhan** [comment]
@monjoybme You need to write MyCapper function according to your requirement. If you don't want to constrain your gradients, then comment that line (where `MyCapper` is there) and run. Thanks.

I am closing this issue. Please post this kind of support questions in Stackoverflow. Thanks!
