### ISSUE TITLE
ModuleNotFoundError: No module named 'tensorflow'  in spyder | windows + anaconda

### ISSUE THREAD

**Issue by danny1718** [tensorflow/tensorflow#27935]
**System information**
- OS Platform and Distribution : Windows 10 64-bits
- TensorFlow installed from (source or binary): Python 3.6 CPU-only | https://storage.googleapis.com/tensorflow/windows/cpu/tensorflow-1.13.1-cp36-cp36m-win_amd64.whl
- TensorFlow version: 1.13.1
- Python version: 3.6.8
- Installed using virtualenv? pip? conda?: conda

**Describe the problem**

Hi,
I have struggled for hours to install tensorflow to Anaconda and finally succeeded. Hope my experience can help those who have same problem with installation.

I have tried a lot of methods before, such as:
```
pip install tensorflow
conda install tensorflow
```
etc,.
These methods might act as it installed properly but when I tested it in spyder, there were some problems, such as:

> ImportError: cannot import name 'abs'
> attributeerror: module 'tensorflow' has no attribute '__version__'

I  just installed tensorflow successfully in Anaconda following the instructions from: https://www.tensorflow.org/install/pip
2. Create a virtual environment (recommended)
``` 
(base) C:\Users\XXXX>conda create -n venv pip python=3.6
(base) C:\Users\XXXX>conda activate venv
(venv) C:\Users\XXXX>pip install --ignore-installed --upgrade https://storage.googleapis.com/tensorflow/windows/cpu/tensorflow-1.13.1-cp36-cp36m-win_amd64.whl
```

Then I test it in terminal:
```
(venv) C:\Users\XXXX>python
Python 3.6.8 |Anaconda, Inc.| (default, Feb 21 2019, 18:30:04) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
>>> tf.__version__
'1.13.1'
```

It works!
But when I tried to import tensorflow in spyder:
> ModuleNotFoundError: No module named 'tensorflow'

**Solution**

This problem might cause by using virtual environment, and in Anaconda, your spyder or Jupyter Notebook works in default root, but tensorflow is installed in an isolated virtual environment 'venv'. So just install a new spyder or Jupyter Notebook under the virtual enviroment.
- 1. Open Anaconda Navigation
![image](https://user-images.githubusercontent.com/15613656/56325165-c273ad80-6136-11e9-9438-ec8f8eb759c9.png)
- 2. Change 'Applications on' to the virtual environment you just created ('venv')
- 3. Install a new spyder under 'venv'
- 4. Run the new spyder and test
![image](https://user-images.githubusercontent.com/15613656/56325929-c228e180-6139-11e9-9135-9d00715e03bf.png)

**Comment by jvishnuvardhan** [comment]
@danny1718 Great. Thanks for the detailed instructions. This will really help for people who user Anaconda to install TF in virtual environment. Thanks again.

**Comment by jvishnuvardhan** [comment]
Thanks for the detailed instructions. I closing this issue.

This is not Build/Installation or Bug/Performance issue. Please post this kind of support questions at [Stackoverflow](https://stackoverflow.com/questions/tagged/tensorflow). There is a big community to support and learn from your questions. GitHub is mainly for addressing bugs in installation and performance. Thanks!

**Comment by Pranav-Gairola** [comment]
Thank you so much. Very much appreciable. @danny1718

**Comment by Augustlongpeaceful** [comment]
super amazing, this is the most valuable posts I ever saw, directly solve my problem!! THX
one more small question, which environment would be better to install? why not install all packages in the base or root environment?

**Comment by hamBan** [comment]
Thanks a lot for these instructions. I could not find them anywhere else.

**Comment by montoyama** [comment]
Excelent, clever guy ..

**Comment by Anitha1997** [comment]
thank you so much

**Comment by dipen0807** [comment]
I created the another environment "tf" from anaconda navigator and installed the Jupyter. Now what happened is that in this new Jupiter my tensoflow works but all other previously installed libraries do not work(like sklearn)m and in the old jupyter tensorflow doesnt work and other libraries work.

So how to solve this issue?

**Comment by danny1718** [comment]
> I created the another environment "tf" from anaconda navigator and installed the Jupyter. Now what happened is that in this new Jupiter my tensoflow works but all other previously installed libraries do not work(like sklearn)m and in the old jupyter tensorflow doesnt work and other libraries work.
> 
> So how to solve this issue?

--------------------------------------------------------------------------------------------------------------

Hi Dipen,

The libs installed in the default environment would not work in the 'tf' environment because they are two separate environments. And also, tensorflow was installed in the 'tf' environment so it can't be found in the default one.

To solve this issue, you can install all the libs you need in 'tf' use pip (recommended) or you can re-install tensorflow in the default environment.

**Comment by Anustup900** [comment]
If you are using anaconda navigator then this might be a alternate solution : 
i) First at the initial time when you are installing anaconda navigator you will start with the base_DIR as the environment 
ii.) Next set up Tensorflow in the base environment by running ''conda install tensoflow '' in base directory 
iii.) Next as you install Tensorflow over there you can find anather virtual environment Tensorflow_gpu in anaconda navigator 
![t1](https://user-images.githubusercontent.com/60361231/87962511-f295c300-cad4-11ea-9508-540d9175f8dd.PNG)
as shown in the image 
iv.) select it as the default environment run it in terminal and pass the command : 
![t2](https://user-images.githubusercontent.com/60361231/87962628-1c4eea00-cad5-11ea-9236-29274e70a55b.PNG)
Next directly download Jupyter Lab or notebook or Spyder over it and launch it with the command : %load_ext tensorboard
It will work .
Thank you

**Comment by scottti312** [comment]
Yess finally thank you

**Comment by arun-jathari** [comment]
> **System information**
> 
> * OS Platform and Distribution : Windows 10 64-bits
> * TensorFlow installed from (source or binary): Python 3.6 CPU-only | https://storage.googleapis.com/tensorflow/windows/cpu/tensorflow-1.13.1-cp36-cp36m-win_amd64.whl
> * TensorFlow version: 1.13.1
> * Python version: 3.6.8
> * Installed using virtualenv? pip? conda?: conda
> 
> **Describe the problem**
> 
> Hi,
> I have struggled for hours to install tensorflow to Anaconda and finally succeeded. Hope my experience can help those who have same problem with installation.
> 
> I have tried a lot of methods before, such as:
> 
> ```
> pip install tensorflow
> conda install tensorflow
> ```
> 
> etc,.
> These methods might act as it installed properly but when I tested it in spyder, there were some problems, such as:
> 
> > ImportError: cannot import name 'abs'
> > attributeerror: module 'tensorflow' has no attribute '**version**'
> 
> I just installed tensorflow successfully in Anaconda following the instructions from: https://www.tensorflow.org/install/pip
> 2. Create a virtual environment (recommended)
> 
> ```
> (base) C:\Users\XXXX>conda create -n venv pip python=3.6
> (base) C:\Users\XXXX>conda activate venv
> (venv) C:\Users\XXXX>pip install --ignore-installed --upgrade https://storage.googleapis.com/tensorflow/windows/cpu/tensorflow-1.13.1-cp36-cp36m-win_amd64.whl
> ```
> 
> Then I test it in terminal:
> 
> ```
> (venv) C:\Users\XXXX>python
> Python 3.6.8 |Anaconda, Inc.| (default, Feb 21 2019, 18:30:04) [MSC v.1916 64 bit (AMD64)] on win32
> Type "help", "copyright", "credits" or "license" for more information.
> >>> import tensorflow as tf
> >>> tf.__version__
> '1.13.1'
> ```
> 
> It works!
> But when I tried to import tensorflow in spyder:
> 
> > ModuleNotFoundError: No module named 'tensorflow'
> 
> **Solution**
> 
> This problem might cause by using virtual environment, and in Anaconda, your spyder or Jupyter Notebook works in default root, but tensorflow is installed in an isolated virtual environment 'venv'. So just install a new spyder or Jupyter Notebook under the virtual enviroment.
> 
> * 1. Open Anaconda Navigation
>      ![image](https://user-images.githubusercontent.com/15613656/56325165-c273ad80-6136-11e9-9438-ec8f8eb759c9.png)
> * 1. Change 'Applications on' to the virtual environment you just created ('venv')
> * 1. Install a new spyder under 'venv'
> * 1. Run the new spyder and test
>      ![image](https://user-images.githubusercontent.com/15613656/56325929-c228e180-6139-11e9-9135-9d00715e03bf.png)

Thanks for the links
i found [anaconda link ](https://www.tensorflow.org/install/pip#conda)through which i've installed tensorflow in just two commands

conda create --name py3-TF2
conda install -c anaconda tensorflow

the second command is a list of sub-commands customized by anaconda community
after installation i have
python                    3.7.9
tensorflow                2.1.0
tensorboard               2.2.1
numpy                     1.19.1
pip                       20.2.2
scipy                     1.5.2

**Comment by arun-jathari** [comment]
Thanks for the links
i found anaconda link through which i've installed tensorflow in just two commands

conda create --name py3-TF2
conda install -c anaconda tensorflow

the second command is a list of sub-commands customized by anaconda community
after installation i have
python 3.7.9
tensorflow 2.1.0
tensorboard 2.2.1
numpy 1.19.1
pip 20.2.2
scipy 1.5.2

**Comment by mbrav** [comment]
Anaconda on Windows is such a pain in the ass. If I install Anaconda with all the libraries, then I expect to have all the tools integrated in my `venv`, including TensorFlow, but then that takes 10 minutes to install because I'm on my secondary HDD with Windows 10 installed, and not my primary NVM.e SSD drive where I have my Linux distro installed, because ultimately, **and here is my main rant against whom I have:** NVIDEA!! because they do not release Open Source Drivers for their GPU's and make so many people's lives a pain in the ass! Feel me? Yes, because, [f**k NVIDEA](https://www.youtube.com/watch?v=iYWzMvlj2RQ)

**Comment by dalerobichaudpi** [comment]
@danny1718 - I went through the same painful steps and then I saw this post. You saved my interest in tensorflow! All working beautifully now.

**Comment by exeptionerror** [comment]
[[Solved] Spyder ModuleNotFoundError In anaconda
](https://exerror.com/spyder-modulenotfounderror-in-anaconda/)
