### ISSUE TITLE
tensorflow.python.framework.errors_impl.NotFoundError: Op type not registered 'TFLite_Detection_PostProcess' in binary

### ISSUE THREAD

**Issue by jyotirmayghosh** [tensorflow/tensorflow#27953]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04 LTS
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): pip
- TensorFlow version: 1.9
- Python version: python 3
- Installed using virtualenv? pip? conda?: pip
- Bazel version (if compiling from source): 
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 
- GPU model and memory: GeForce RTX 2080 Ti/PCIe/SSE2  memory:15.6 GiB

I am trying to convert tflite_graph.pb to .tflite from terminal. Earlier I was using tensorflow 1.3 and used the below command to convert:

`tflite_convert  --graph_def_file=/home/user/Desktop/FaceDetection/frozen_tflite/tflite_graph.pb --output_file=/home/user/Desktop/FaceDetection/frozen_tflite/coverted_frozen_graph.tflite --input_arrays=normalized_input_image_tensor --output_arrays="detection_boxes","detection_scores","detection_classes","num_detections" --input_shape=1,300,300,3 --allow_custom_ops=True
` 

That time I got an error that tflite_convert command not found. After digging few git issues and stackover flow, I found that this will work with **tensorflow 1.9**

I used the pip install -upgrade tensorflow==1.9 to upgrade the tf.

It ran with the following error:
`2019-04-18 17:24:39.216037: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
Traceback (most recent call last):
  File "/usr/local/bin/tflite_convert", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/contrib/lite/python/tflite_convert.py", line 320, in main
    app.run(main=run_main, argv=sys.argv[:1])
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/contrib/lite/python/tflite_convert.py", line 316, in run_main
    _convert_model(tflite_flags)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/contrib/lite/python/tflite_convert.py", line 91, in _convert_model
    converter = _get_toco_converter(flags)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/contrib/lite/python/tflite_convert.py", line 81, in _get_toco_converter
    return converter_fn(**converter_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/contrib/lite/python/lite.py", line 204, in from_frozen_graph
    import_graph_def(graph_def, name="")
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/util/deprecation.py", line 432, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/importer.py", line 418, in import_graph_def
    graph._c_graph, serialized, options)  # pylint: disable=protected-access
tensorflow.python.framework.errors_impl.NotFoundError: Op type not registered 'TFLite_Detection_PostProcess' in binary running on user. Make sure the Op and Kernel are registered in the binary running in this process. Note that if you are loading a saved graph which used ops from tf.contrib, accessing (e.g.) `tf.contrib.resampler` should be done before importing the graph, as contrib ops are lazily registered when the module is first accessed.`

**tensorflow.python.framework.errors_impl.NotFoundError: Op type not registered 'TFLite_Detection_PostProcess' in binary**

Can anyone help me to solve this issue?

Thank in adv.

**Comment by muddham** [comment]
@jyotirmayghosh Can you please upgrade tensorflow to as one user mentioned in #5277 that Upgrading to 1.11 worked.

**Comment by jyotirmayghosh** [comment]
Yes I have solved this issue.
Thanks

**Comment by GangaMegha** [comment]
How did you solve it? Did upgrading to tensorflow 1.11 help? I'm currently using tensorflow 1.14.0 and I'm facing a similar issue.

**Comment by zz7379** [comment]
> How did you solve it? Did upgrading to tensorflow 1.11 help? I'm currently using tensorflow 1.14.0 and I'm facing a similar issue.

Me too

**Comment by Dasinator21** [comment]
> How did you solve it? Did upgrading to tensorflow 1.11 help? I'm currently using tensorflow 1.14.0 and I'm facing a similar issue.

Yep same problem but using 1.15 tensorflow
