### ISSUE TITLE
All Diagrams Missing

### ISSUE THREAD

**Issue by KevlarTheGreat** [tensorflow/tensorflow#27956]
**System information**
- TensorFlow version: N/A
- Doc Link: https://github.com/tensorflow/docs/blob/master/site/en/guide/premade_estimators.md
https://github.com/tensorflow/docs/blob/master/site/en/guide/custom_estimators.md

**Describe the documentation issue**
All of the diagrams / images are missing from both of the links above. 

**We welcome contributions by users. Will you be able to update submit a PR (use the [doc style guide](https://www.tensorflow.org/community/documentation)) to fix the doc Issue?**
No.  I don't know what the diagrams were supposed to be.

**Comment by muddham** [comment]
@KevlarTheGreat We will take a look at it. Thanks!

**Comment by jvishnuvardhan** [comment]
@KevlarTheGreat Thanks for finding these links. I also cannot see the figures in those two links.Thanks!

**Comment by yashk2810** [comment]
THis was updated: https://www.tensorflow.org/guide/estimator

Please reopen if image is still not found.
