### ISSUE TITLE
error when using batch_normalize in tensorflow.contrib

### ISSUE THREAD

**Issue by guohengkai** [tensorflow/tensorflow#2797]
When I try to use batch_normalize as `bn = batch_normalize(conv, convnet=True)`, the error is as follows:

> File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/learn/python/learn/ops/batch_norm_ops.py", line 72, in batch_normalize
>     lambda: (ema_mean, ema_var))
>   File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/control_flow_ops.py", line 1316, in cond
>     p_2, p_1 = switch(pred, pred)
>   File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/control_flow_ops.py", line 260, in switch
>     return gen_control_flow_ops._switch(data, pred, name=name)
>   File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_control_flow_ops.py", line 370, in _switch
>     result = _op_def_lib.apply_op("Switch", data=data, pred=pred, name=name)
>   File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/op_def_library.py", line 464, in apply_op
>     (prefix, dtypes.as_dtype(input_arg.type).name))
> TypeError: Input 'pred' of 'Switch' Op has type float32 that does not match expected type of bool.

Operating System: Ubuntu 14.04, 64 bits
Pip package: https://storage.googleapis.com/tensorflow/linux/gpu/tensorflow-0.9.0rc0-cp27-none-linux_x86_64.whl
The output from `python -c "import tensorflow; print(tensorflow.__version__)"`: 0.9.0rc0

**Comment by JulesGM** [comment]
I also have this problem when trying to run 
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/examples/skflow/resnet.py

**Comment by decster** [comment]
also have this problem when trying to use tensorflow.contrib.learn.ops.conv2d

**Comment by ilblackdragon** [comment]
We have a new `batch_norm` op in `tf.contrib.layers` that suppose to work correctly. Please try it.
