### ISSUE TITLE
piecewise_constant_decay not supported by xla: Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by vishalsubbiah** [tensorflow/tensorflow#27970]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): CENTOS 7
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: NA
- TensorFlow installed from (source or binary): source 
- TensorFlow version (use command below): 1.13
- Python version: 3.6
- Bazel version (if compiling from source): 0.21
- GCC/Compiler version (if compiling from source): 6.3.0
- CUDA/cuDNN version: NA
- GPU model and memory: NA

 I am trying to run a model which uses `tf.train.piecewise_constant_decay` with xla.  Previously this was supported in tf1.10 when I last tried. I am now trying the same script in tf1.13. 

I receive a segmentation fault when I run it now. After digging around it seems to be because of type `DT_STRING` which the `const` kernel doesn't seem to support. 

When I see what operations are supported by the `Const` kernel, 
(`bazel run -c opt -- tensorflow/compiler/tf2xla:tf2xla_supported_ops --device=XLA_CPU_JIT`) it shows 
``` 
Const | dtype={bool,complex64,double,float,half,int32,int64,int8,qint32,qint8,quint8,string,uint32,uint64,uint8}
```  

To reproduce this bug, a simple example is:
```
import tensorflow as tf
from tensorflow.contrib.compiler.xla import compile
import numpy as np

LABELS = 10
HIDDEN_SIZE = 256
BATCH_SIZE = 64
FEAT_DIM = 784

xla_flag = True


def model_fn(features, labels):
    with tf.variable_scope("fc", use_resource=True):
        net = tf.keras.layers.Dense(units=HIDDEN_SIZE,
                                    activation=tf.nn.relu)(features)
        logits = tf.keras.layers.Dense(units=LABELS)(net)
        cross_entropy = tf.reduce_mean(
            tf.nn.softmax_cross_entropy_with_logits(labels=labels,
                                                    logits=logits))
        global_step = tf.train.get_or_create_global_step()
        boundaries = [100000, 110000]
        values = [1.0, 0.5, 0.1]
        learning_rate = tf.train.piecewise_constant_decay(global_step, boundaries, values)
        train_step = tf.train.GradientDescentOptimizer(
            learning_rate, name="final_node").minimize(cross_entropy)
        with tf.control_dependencies([train_step]):
            return tf.identity(cross_entropy, name="results")

x = tf.placeholder(tf.float32, [BATCH_SIZE, FEAT_DIM], name='x')
y = tf.placeholder(tf.float32, [BATCH_SIZE, LABELS], name='y')

if xla_flag:
    (xla_loss,) = compile(model_fn, [x,y])
else:
    xla_loss = model_fn(x,y)

with tf.Session() as sess:
    sess.run(tf.initialize_all_variables())
    ans = sess.run(xla_loss,feed_dict={x:np.ones((BATCH_SIZE,FEAT_DIM)),y:np.ones((BATCH_SIZE,LABELS))})
```

While looking at the implementation, it seems like it could be because of the name_scope defined at https://github.com/tensorflow/tensorflow/blob/r1.13/tensorflow/python/training/learning_rate_decay_v2.py#L169 

Please let me know if there is a solution, or if I am doing something wrong from my side.

**Comment by ymodak** [comment]
@jlebar

**Comment by jlebar** [comment]
Would you be willing to check with a nightly build?  I believe we may have fixed this recently.

**Comment by vishalsubbiah** [comment]
It looks like it was fixed in this pr https://github.com/tensorflow/tensorflow/commit/0b85b901b256b7e771b0597a7b3184ce7bf2319e

**Comment by ymodak** [comment]
Closing this issue since its resolved. Feel free to reopen if have any further problems. Thanks!
