### ISSUE TITLE
increase throughput for `ResizeBilinearKernel`

### ISSUE THREAD

**Issue by ThisIsIsaac** [tensorflow/tensorflow#27977]
`ResizeBilinearKernel` in [cuda file](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/kernels/resize_bilinear_op_gpu.cu.cc) there are 3 major changes for improvement:

1. `images` is `NHWC` which makes reads and writes to global memory uncoalesced. By changing the input and output to `NCHW`, we can increase the overall speed by a few folds
2. instead of spawning each thread for every element, spawn only as many threads as `output_height * output_width`, and have each thread iterate over `channel ` and `batch` dimension. this has two benefits: it increases throughput roughly 30%, and it allows smaller kernel launches which allows more number of concurrent kernels to be present on the device.
3. use `__restrict__` modifier for both input and output. This alone increase throughput 2~4%

The above improvements is something that can be applied to general kernels that perform element-wise operation to a vector. I have a working code of `ResizeBilinearKernel` with increased throughput which I can push in a couple days as soon as I get a few uncertainties straightened out. I would really appreciate your help.

Thanks :)

**Comment by muddham** [comment]
@ThisIsIsaac Thanks for your contribution. We will take a look at it.

**Comment by ThisIsIsaac** [comment]
@muddham 
Thanks for looking into it. I have tested the performance, and it seems to have 4~5 x speedup while occupying GPU less ( with less threads ).

**Comment by rmothukuru** [comment]
@ThisIsIsaac,
Sorry for the delayed response and Thank you for the Feature Request. Since you have a clarify on what needs to be changed in the CUDA File, can you please submit a PR with the suggested changes, if the issue is still relevant? Thanks!

**Comment by ThisIsIsaac** [comment]
@rmothukuru 
I've made a pull request a couple years back with @chsigg and it has been merged to the main branch, so I'll close the issue.

Would you be the right person to bother for future pull requests regarding CUDA kernels?

**Comment by rmothukuru** [comment]
@ThisIsIsaac,
Thank you for your response. Regarding your question about PRs, please feel free to submit them because we have a Team of Google Engineers to review them. Thanks!
