### ISSUE TITLE
Linking error with libtflite_gpu_gl.so caused by TfLiteGpuDelegateDelete absence among exported symbols

### ISSUE THREAD

**Issue by boother** [tensorflow/tensorflow#27987]
**System information:**
- OS Platform and Distribution: Linux Ubuntu 14.04
- TensorFlow installed from source
- TensorFlow version: 2.0 alpha
- Bazel version: 0.24.1
- GCC/Compiler version: clang 8.0.2

**Issue:**

TfLiteGpuDelegateDelete doesn't declared as exported symbol in tensorflow/lite/delegates/gpu/gl_delegate.h. This caused linking error with libtflite_gpu_gl.so.

Build command:
bazel build -c opt --config android_arm64 --copt -Os --copt -DTFLITE_GPU_BINARY_RELEASE --copt **-fvisibility=hidden** --linkopt -s --strip always --cxxopt='--std=c++11' //tensorflow/lite/delegates/gpu:libtflite_gpu_gl.so

**Reproduce:**

////////
// Set up interpreter.
auto model = FlatBufferModel::BuildFromFile(model_path);
ops::builtin::BuiltinOpResolver op_resolver;
std::unique_ptr<Interpreter> interpreter;
InterpreterBuilder(*model, op_resolver)(&interpreter);

////////
// NEW: Prepare GPU delegate.
auto* delegate = TfLiteGpuDelegateCreate(/*options=*/nullptr);
if (interpreter->ModifyGraphWithDelegate(delegate) != kTfLiteOk) return;

////////
// Run inference.
WriteToInputTensor(interpreter->typed_input_tensor<float>(0));
if (interpreter->Invoke() != kTfLiteOk) return;
ReadFromOutputTensor(interpreter->typed_output_tensor<float>(0));

////////
// Clean up.
**TfLiteGpuDelegateDelete(delegate);**

I followed example described at tensorflow/lite/delegates/gpu/README.md

**Comment by holyhao** [comment]
So, what the sdk and ndk version do you use?

**Comment by impjdi** [comment]
@boother 

If you change

```
void TfLiteGpuDelegateDelete(TfLiteDelegate* delegate);
```

to

```
TFL_CAPI_EXPORT void TfLiteGpuDelegateDelete(TfLiteDelegate* delegate);
```

things should work.  I will fix this in the internal repository; it may take a bit to be reflected on the open source repository.

**Comment by impjdi** [comment]
This should now be fixed.

https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/delegates/gpu/gl_delegate.h
