### ISSUE TITLE
TFLite crash on Android running a model for NNPI

### ISSUE THREAD

**Issue by alexcohn** [tensorflow/tensorflow#27983]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): **No**
- OS Platform and Distribution: **n/a**
- Mobile device: **Android Q Emulator** and **Xiaomi A2**
- TensorFlow installed from: **binary**
- TensorFlow version: **1.13.1**
- GPU model and memory: **?**

**Describe the current behavior**
Simple program wroks with CPU, but crashes when NNAPI is turned on, with words:

    E/tflite: Op code 67 is currently not delegated to NNAPI
    E/tflite: Returning error since TFLite returned failure nnapi_delegate.cc:739.

**Expected behavior**
I would expect TFLite to fall back to CPU for the opcodes that cannot work with NNAPI.

**Code to reproduce the issue**
GitHub repo: https://github.com/alexcohn/tflite-nnapi

**Comment by alexcohn** [comment]
![Screenshot_1555683477](https://user-images.githubusercontent.com/736435/56428247-5f655080-62c7-11e9-958e-d56d2971a967.png)

**Comment by freedomtan** [comment]
Current Java API uses `tflite::interpreter->UseNNAPI()` which doesn't not directly support fallback. If newer NNAPI delegate is used, see e.g. benchmark_model in master branch [1] or my working change to label_image for tflite [2],  then you can get what you want. 

[1] https://github.com/tensorflow/tensorflow/commit/1b77aae95919415947204afc1803648aa126a376
[2] https://github.com/freedomtan/tensorflow/commit/792c394286e89291edb0673ed619c5b714bdc231

**Comment by alexcohn** [comment]
@freedomtan Is the new delegate an *all or nothing* thing, or it bypasses to CPU only the unsupported operations?

**Comment by freedomtan** [comment]
Fallback to CPU if an op is not supported in NNAPI. It turns out it's quite easy to enable that in Java. I have a quick dirty hack https://github.com/freedomtan/tensorflow/commit/65acda8f5a53c088ad9ed1032d9578a479379c45. Will clean up it later.

**Comment by jvishnuvardhan** [comment]
@alexcohn Is this resolved by @freedomtan suggestion. Thanks!

**Comment by alexcohn** [comment]
I can confirm that appying `addDelegate(NnApiDelegate())` instead of `setUseNNAPI(true)` (requires https://github.com/freedomtan/tensorflow/commit/8ecb5a4ae01e0305e95871fbc77b2b038115e58b) resolves the crash. 

Unfortunately, after learning more about NNAPI [performance issues](https://github.com/tensorflow/tensorflow/issues/28283#issuecomment-488161897) I cannot use this delegate in our Android app.

**Comment by jdduke** [comment]
Another note on this end, we'll shortly be removing the "old" NNAPI implementation entirely in favor of the NNAPI delegate. Existing use of "Interpreter::SetUseNnapi(bool)" will take advantage of the new delegate.

**Comment by miaowang14** [comment]
”Op code 67 is currently not delegated to NNAPI“

Which operation is this? and the type of the tensors?
If it is supported by NNAPI, I can help update delegate to support it.

**Comment by freedomtan** [comment]
@miaowang14 I think op 67 is transpose convolution, which is not supported by NNAPI before Q :-)
