### ISSUE TITLE
Can't install TensorFlow Windows 7 64bit Python 3.7.2

### ISSUE THREAD

**Issue by Kuaranir** [tensorflow/tensorflow#27990]
here is a mistake after typing "pip install tensorlow".
I tried type it in cmd and PyCharm console too. Nothing.

C:\Users\Alex\PycharmProjects\ML>pip install tensorflow
Collecting tensorflow
  Could not find a version that satisfies the requirement tensorflow (from versions: )
No matching distribution found for tensorflow

**Comment by qwtsc** [comment]
According to [official install guide](https://www.tensorflow.org/install/pip), tf only supports 3.6, 3.5, 3.4.

**Comment by Kuaranir** [comment]
Thank you a lot :)

**Comment by raonvk** [comment]
Hi Kuaranir

I have same error while installing Tensorflow in Win7 x64 bit
Could you please explain how to fix?
RAO NVK
![Error_tf_install](https://user-images.githubusercontent.com/38853257/56467274-e5031080-642d-11e9-8537-e129d5a6afa2.jpg)

**Comment by Kuaranir** [comment]
Ah, i have installed Python 3.6.8 instead of 3.7.2, but it doesnt work still  [https://a.radikal.ru/a36/1904/b1/87457f81d96d.jpg](url)

**Comment by raonvk** [comment]
Hi
try this below, working now
pip install --upgrade https://storage.googleapis.com/tensorflow/mac/cpu/tensorflow-1.13.1-py3-none-any.whl

**Comment by gadagashwini** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
