### ISSUE TITLE
Tensorflow on windows using docker

### ISSUE THREAD

**Issue by varunteja28** [tensorflow/tensorflow#2800]
Hey i am trying to install tensorflow on windows 10 machine using docker. I am getting this message for a very long time. please help me out with this or suggest any alternative.
Thanks
![capture](https://cloud.githubusercontent.com/assets/18229244/15984549/20b37872-2fed-11e6-9f40-4fbbedcc3c88.JPG)

**Comment by mrry** [comment]
The message indicates that the container started successfully. You should now be able to connect to the Jupyter kernel running inside the container.
