### ISSUE TITLE
Cannot Make TfRecords Work for Image-sentence Pairs

### ISSUE THREAD

**Issue by nvidiaman** [tensorflow/tensorflow#28008]
Hi,

I am stuck on making tfrecords work for image-text pair data.

Here is the code to create tfrecord from numpy array of image features and a text file,

```
def npy_to_tfrecords(numpy_array, text_file, output_file):
      f = open(text_file)

      # write records to a tfrecords file
      writer = tf.python_io.TFRecordWriter(output_file)

      # Loop through all the features you want to write
      for X, line in zip(numpy_array, f) :
         #let say X is of np.array([[...][...]])
         #let say y is of np.array[[0/1]]

         txt = "{}".format(line[:-1])
         txt = txt.encode()

         # Feature contains a map of string to feature proto objects
         feature = {}
         feature['x'] = tf.train.Feature(float_list=tf.train.FloatList(value=X.flatten()))
         feature['y'] = tf.train.Feature(bytes_list=tf.train.BytesList(value=[txt]))

         # Construct the Example proto object
         example = tf.train.Example(features=tf.train.Features(feature=feature))

         # Serialize the example to a string
         serialized = example.SerializeToString()

         # write the serialized objec to the disk
         writer.write(serialized)
      writer.close()
```

I cannot make the dataset after this:
```

def load_data_tfr():
    
   train = tf.data.TFRecordDataset("train.tfrecord")

   # example proto decode
   def _parse_function1(example_proto):
      keys_to_features = {'x': tf.FixedLenFeature(2048, tf.float32),
                          'y': tf.VarLenFeature(tf.string) } 
      parsed_features = tf.parse_single_example(example_proto, keys_to_features)
      return {"x": parsed_features['x'], "y":  parsed_features['y']} # ['x'], parsed_features['y']

   # Parse the record into tensors.
   train = train.map(_parse_function1)

   return train
```

`train_data = load_data_tfr()`

I keep . getting the error:

```
random.shuffle(train_data)

    for i in reversed(range(1, len(x))):
TypeError: object of type 'MapDataset' has no len()
```

Any help? thank you.

**Comment by gadagashwini** [comment]
Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version. Also, did you compile from source or install a binary?

Make sure you also include the exact command if possible to produce the output included in your test case. If you are unclear what to include see the issue template displayed in [the Github new issue template](https://github.com/tensorflow/tensorflow/issues/new/choose).

We ask for this in the issue submission template, because it is really difficult to help without that information. Thanks!

**Comment by nvidiaman** [comment]
@gadagashwini thanks for reply. could you share an example where image and text data was paired using tfrecord? I just want to pair text with some vector, i.e. one vector for each line of text.  I am on  linux, conda installed tensorflow gpu 1.16.

**Comment by gadagashwini** [comment]
@nvidiaman This [link](https://github.com/tensorflow/docs/blob/master/site/en/r2/tutorials/load_data/images.ipynb) may help you. Thanks!

**Comment by gadagashwini** [comment]
Hi, request you to post any support related questions in StackOverflow. We encourage users to post only bug/feature request here. If you think it is a bug/feature, please fill this template and open a new issue. Thank you !
