### ISSUE TITLE
Transformer network weights - demo error 

### ISSUE THREAD

**Issue by umayuxlabs** [tensorflow/tensorflow#28009]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Colab
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: No
- TensorFlow installed from (source or binary): tf-nightly-gpu-2.0-preview
- TensorFlow version (use command below): 2.0.0-dev20190420
- Python version: 3
- Bazel version (if compiling from source): Colab
- GCC/Compiler version (if compiling from source): Colab
- CUDA/cuDNN version: Colab
- GPU model and memory: Colab

You can collect some of this information using our environment capture [script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with
python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"

**Describe the current behavior**

I have been trying the demos of tensorflow 2.0, particularly the transformers example. However, the current transformer example is not working anymore. This is the error output: 

ValueError: Weights for model sequential_3 have not yet been created. Weights are created when the Model is first called on inputs or `build()` is called with an `input_shape`.

Seems like the latest tensorflow version 2.0.0-dev20190420 has changed a way how to call the inputs or set the weights. 

It was working with the tf version 2.0.0-dev20190413. 
In conclusion the transformer demo is not working anymore, is there any way to get installed in colab the 2.0.0-dev20190413 version?

**Describe the expected behavior**

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

Instructions are here: https://colab.research.google.com/github/tensorflow/docs/blob/master/site/en/r2/tutorials/text/transformer.ipynb#scrollTo=8QG9nueFQKXx

I used the GPU version.

I just ran the colab transformer notebook: https://colab.research.google.com/github/tensorflow/docs/blob/master/site/en/r2/tutorials/text/transformer.ipynb#scrollTo=8QG9nueFQKXx

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by cevrim** [comment]
I'm having the same problem.

**Comment by umayuxlabs** [comment]
> I'm having the same problem.

Hi @cevrim, 

Actually, we were able to fix the problem in the meantime by using the previous release of tensorflow, you just need to change the tf installation to this: 

!pip install tf-nightly-gpu-2.0-preview==2.0.0.dev20190413

This is something temporal, but, it would be good to know about those changes and how to address them. 

Regards

**Comment by cevrim** [comment]
Hi @umayuxlabs ,

Thank you for sharing your fix, I was trying to do the same thing.

Regards

**Comment by achandraa** [comment]
@umayuxlabs : Thank you for your support.
@cevrim : Were you able to resolve ?

**Comment by cevrim** [comment]
@achandraa Yes, it's resolved.

**Comment by achandraa** [comment]
Closing the issue since it is resolved. Thanks!

**Comment by starhou** [comment]
I'm having the same problem ! @achandraa 
I write a layer with the APIs of tf.nn. When using the layer together with other written layers, such as tf.keras.layers. Dense, I got the error "ValueError: Weights for model sequential_3 have not yet been created. Weights are created when the Model is first called on inputs or `build()` is called with an `input_shape`." However, the layer works well seperately.
Here is my layer.
`class cov(layers.Layer):
  def __init__(self, filters_width = (3,), 
              strides = 1,  
              padding = 'VALID', 
              dilations = None, **kwargs):
    super(cov, self).__init__(**kwargs)
    self.filters_width = filters_width
    self.strides = strides
    self.padding = padding
    self.dilations = dilations

  def build(self, input_shape):
    
    self.filters = self.add_weight(shape=self.filters_width+(input_shape[-1], input_shape[-1]),
                        initializer='random_normal',
                        trainable=True) 
  def call(self, inputs):
    output = tf.nn.convolution(
        input = inputs,
        filters = self.filters,
        strides = self.strides,
        padding = self.padding,
        data_format = None,
        dilations = self.dilations,
        name = 'cov'
    )
    return output`
