### ISSUE TITLE
TF 2.0 Bug or Feature? keras includes duplicated shared variables in model.variables

### ISSUE THREAD

**Issue by thuyen** [tensorflow/tensorflow#28003]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): pip nightly
- TensorFlow version (use command below): 2.0.0-dev20190415
- Python version: 3.6
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

You can collect some of this information using our environment capture [script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with
python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"

**Describe the current behavior**
The two following layers give different number of variable in `model.variables`. Keras duplicates shared variables in the variable list:
```
import tensorflow as tf
import numpy as np

class MLayer(tf.Module):
    def __init__(self):
        super(MLayer, self).__init__()
        conv = tf.keras.layers.Conv2D(3, 3, 1, padding='SAME')
        self.convs = [conv] * 7

    def __call__(self, x):
        for conv in self.convs:
            x = conv(x)
        return x

class KLayer(tf.keras.models.Model):
    def __init__(self):
        super(KLayer, self).__init__()
        conv = tf.keras.layers.Conv2D(3, 3, 1, padding='SAME')
        self.convs = [conv] * 7

    def call(self, x):
        for conv in self.convs:
            x = conv(x)
        return x

xnp = np.random.rand(1, 224, 224, 3)
x = tf.constant(xnp, tf.float32)

model = MLayer()
y = model(x)
v = [variable.name for variable in model.variables]
print(v, len(v))

model = KLayer()
y = model(x)
v = [variable.name for variable in model.variables]
print(v, len(v))
```
The first print:
```
['conv2d/kernel:0', 'conv2d/bias:0'] 2
```
The second prints: 
```
['k_layer/conv2d_1/kernel:0', 'k_layer/conv2d_1/bias:0', 'k_layer/conv2d_1/kernel:0', 'k_layer/conv2d_1/bias:0', 'k_layer/conv2d_1/kernel:0', 'k_layer/conv2d_1/bias:0', 'k_layer/conv2d_1/kernel:0', 'k_layer/conv2d_1/bias:0', 'k_layer/conv2d_1/kernel:0', 'k_layer/conv2d_1/bias:0', 'k_layer/conv2d_1/kernel:0', 'k_layer/conv2d_1/bias:0', 'k_layer/conv2d_1/kernel:0', 'k_layer/conv2d_1/bias:0'] 14
```
**Describe the expected behavior**

I would expect two layers have the same number of variables. 

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by ymodak** [comment]
I was able to reproduce the behavior with ```TF nightly '1.14.1-dev20190423'```

**Comment by ymodak** [comment]
This is fixed with latest version of TensorFlow nightly build version '2.1.0-dev20191021'
Output:
```python
['conv2d/kernel:0', 'conv2d/bias:0'] 2
['k_layer/conv2d_1/kernel:0', 'k_layer/conv2d_1/bias:0'] 2
```
Thanks!
