### ISSUE TITLE
New weight initialisation when using dropout and ReLU

### ISSUE THREAD

**Issue by arnupretorius** [tensorflow/tensorflow#28004]
- Are you willing to contribute it (Yes/No): Yes

**Describe the feature**
In a recent NeurIPS paper ([Pretorius et al. 2018](https://arxiv.org/pdf/1811.00293.pdf)), we derived a new weight initialisation strategy for deep ReLU networks that use dropout. This new initialisation ensures stable variance propagation for ReLU activations travelling through a dropout layer. The go-to initialisation for dense ReLU layers is the He initialisation, but in the above paper, we showed that if a dropout layer is applied after a dense ReLU layer the variances are longer preserved in the forward pass. This can lead to unstable signal propagation in deep ReLU networks that use dropout. We fix this with the new initialisation and thought it might be useful to the community if there was a Tensorfow implementation.  

**Will this change the current api? How?**
It should not require the current api to change.

**Proposed implementation**
In short, the initialisation samples from a normal distribution with zero mean and `stddev = \sqrt{2*(1-p)/fan_in}`, where `p is the probability of an element to be zeroed` when passing through the dropout layer following the dense layer being initialised. To implement the initialisation in Tensorflow, I was thinking perhaps something along these lines of code being added to the `init_ops.py`? This init should be applied to dense ReLU layers preceding a dropout layer.

```python
def dropout(rate, seed=None):
  """Dropout initializer.
  It draws samples from a normal distribution centred on 0
  with standard deviation given by
  `stddev = sqrt(2*(1-rate) / fan_in)` where `fan_in` is the number of
  input units in the weight tensor and `rate` is the probability of an 
  element to be zeroed as set in the dropout layer applied after this dense layer.
  Arguments:
      rate: The dropout rate, between 0 and 1. This should be set equal to the dropout rate in the subsequent dropout layer.
      seed: A Python integer. Used to seed the random generator.
  Returns:
      An initializer.
  References:
      [Pretorius et al., 2018]
      (https://papers.nips.cc/paper/7814-critical-initialisation-for-deep-signal-propagation-in-noisy-rectifier-neural-networks)
      # pylint: disable=line-too-long
      ([pdf](https://papers.nips.cc/paper/7814-critical-initialisation-for-deep-signal-propagation-in-noisy-rectifier-neural-networks.pdf))
  """
  if not (rate >= 0 and rate < 1):
        raise ValueError("rate must be a scalar tensor or a float in the "
                         "range [0, 1), got %g" % rate)
  return VarianceScaling(
      scale=2.0*(1.0-rate), mode="fan_in", distribution="normal", seed=seed)
```

**Who will benefit with this feature?**
Hopefully, anyone applying dropout in a deep ReLU network. :)

*Side note: We do not sample from a truncated normal since in our experiments we noticed that when sampling from a truncated normal (which is currently the default), the signal propagation dynamics did not fit with the theory predicting variance preservation during the forward pass. This was the case for both the He init and our dropout init. Therefore, we would also suggest a  (non-truncated) normal as the default for the standard initialisers currently implemented (e.g. He and Xavier etc.).

**Comment by rmothukuru** [comment]
@arnupretorius,
Sorry for the delayed response. Do you feel this **`New Weight Initialization`** holds good even now? If so, since you are clear with what changes needs to be done and where the changes are to be done in the source code, feel free to submit a PR and we will be happy to review it. Thank you.
