### ISSUE TITLE
Error building from source:  "/usr/bin/env: python2.7: No such file or directory"

### ISSUE THREAD

**Issue by peterzcc** [tensorflow/tensorflow#2801]
I'm building tensorflow from source but I don't know why python2.7 is required. Does anyone know whether I can change the crosstool_wrapper_driver_is_not_gcc file?

ERROR: ~/.cache/bazel/_bazel_czeng/211970d9a1065a07eafbeb7dcc542b10/external/protobuf/BUILD:331:1: Linking of rule '@protobuf//:protoc' failed: crosstool_wrapper_driver_is_not_gcc failed: error executing command
  (cd /csproject/dygroup2/czeng/.cache/bazel/_bazel_czeng/211970d9a1065a07eafbeb7dcc542b10/execroot/tensorflow && \
  exec env - \
  third_party/gpus/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc -o bazel-out/host/bin/external/protobuf/protoc bazel-out/host/bin/external/protobuf/_objs/protoc/external/protobuf/src/google/protobuf/compiler/main.o bazel-out/host/bin/external/protobuf/libprotoc_lib.a bazel-out/host/bin/external/protobuf/libprotobuf.a bazel-out/host/bin/external/protobuf/libprotobuf_lite.a -lpthread -lstdc++ -B/usr/bin/ -pie -Wl,-z,relro,-z,now -no-canonical-prefixes -pass-exit-codes '-Wl,--build-id=md5' '-Wl,--hash-style=gnu' -Wl,-S -Wl,--gc-sections): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 127.
/usr/bin/env: python2.7: No such file or directory

**Comment by peterzcc** [comment]
Seems like changing the python2.7 to python2 works in the first line of third_party/gpus/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc

**Comment by peterzcc** [comment]
Solved by changing the interpreter to python2

**Comment by suiyuan2009** [comment]
fixed in version 0.9.0
