### ISSUE TITLE
can't do serving with model generated by TF2.0

### ISSUE THREAD

**Issue by breadbread1984** [tensorflow/tensorflow#28019]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.0.0rc0
- Python version: 3.6.7
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

You can collect some of this information using our environment capture [script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with
python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"

**Describe the current behavior**

I trained model with tf.keras's functional api with tensorflow 2.0 and save model with tf.keras.Model.save() and convert the h5 model with tf.compat.v1.saved_model.simple_save(). When I try to serve the model with the command

```Bash
saved_model_cli run --dir ./serving_model --tag_set serve --signature_def serving_default --input_exp 'input_image = np.random.normal(size=(1,28,28,1))'
```

 I get error message

>RunTimeError: The Session graph is empty. Add operations to the graph before calling run().

**Describe the expected behavior**

I expect that an output tensor representing the class of the input handwriting digit is returned from the serving.

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

Please refer to my project at https://github.com/breadbread1984/EagerExecutionDemo. after train with train_mnist.py, executing start_serving.sh will reproduce the problem.

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by muddham** [comment]
@breadbread1984 This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.If you think we've misinterpreted a bug, please comment again with a clear explanation, as well as all of the information requested in the [issue template](https://github.com/tensorflow/tensorflow/issues/new/choose). Thanks!

**Comment by allenlavoie** [comment]
With eager execution enabled I'd use v2 SavedModel APIs rather than compat.v1. Could you take a look at the [2.x SavedModel guide](https://www.tensorflow.org/alpha/guide/saved_model) and see if that works for you?

**Comment by breadbread1984** [comment]
Thx, I will try it.
