### ISSUE TITLE
Annotating negative class in object detection (Faster R-CNN)

### ISSUE THREAD

**Issue by malahmadi1** [tensorflow/tensorflow#28012]
I am currently training Faster R-CNN on some data and try to build a detector based on our data.
Since my data set has some images without the object of interest in it.
How do I annotate them? (i.e., what will be the bounding box for these images)
Also, does annotating the negative class improve the training?

**Comment by achandraa** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged//tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.Thanks!
