### ISSUE TITLE
Logger suggests non-existent module attribute 'tf.keras.layers.CuDNNLSTM' when using 'tf.keras.layers.LSTM'

### ISSUE THREAD

**Issue by jwiebels** [tensorflow/tensorflow#28026]
**System information**
- Windows 10 Education
- TensorFlow installed from (source or binary): pip install tensorflow-gpu==2.0.0-alpha0
- TensorFlow version: tensorflow-gpu==2.0.0-alpha0
- Python version: 3.7.3
- CUDA/cuDNN version: CUDA 10.0 / cuDNN 7.3.1
- GPU model and memory: NVIDIA GeForce GTX 1080 / 16GB

**Describe the current behavior**
Logger throws warning, that the use of 'tf.keras.layers.LSTM' is not optimized for performance on GPU. Suggests 'tf.keras.layers.CuDNNLSTM' instead, but module attribute 'CuDNNLSTM' doesn't exist.

[Screenshot](https://imgur.com/gdvAPAr)

**Describe the expected behavior**
Usage of 'tf.keras.layers.CuDNNLSTM' doesn't throw an AttributeError, when being a suggested solution.

**Code to reproduce the issue**
```
import tensorflow as tf

# Initialising the RNN
regressor = tf.keras.models.Sequential()

# Adding the first LSTM layer and some Dropout regularisation
regressor.add(tf.keras.layers.LSTM(units = 50, return_sequences = True, input_shape = (X_train.shape[1], 1)))   # using not-perfomance-optimized LSTM, produces warning
regressor.add(tf.keras.layers.Dropout(0.2))

# Adding a second LSTM layer and some Dropout regularisation
regressor.add(tf.keras.layers.CuDNNLSTM(units = 50, return_sequences = True))   # using log-suggested LSTM, throws AttributeError
regressor.add(tf.keras.layers.Dropout(0.2))
```
[lstm_stocks.zip](https://github.com/tensorflow/tensorflow/files/3101494/lstm_stocks.zip)

**Comment by gadagashwini** [comment]
@jwiebels Please find instructions in this [link](https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/keras/layers/LSTM#used_in_the_tutorials) which help you to use tf.keras.layers.LSTM with CuDNN implemetation. Let me know how it progresses. Thanks!

**Comment by gadagashwini** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
