### ISSUE TITLE
Using tensorflow-gpu == 1.7.0 with CUDA 8

### ISSUE THREAD

**Issue by Akella17** [tensorflow/tensorflow#28024]
I am facing ```ImportError``` when I try calling ```tensorflow-gpu == 1.7.0``` on a system with ```CUDA 8``` and ```CuDNN 5.1```. I am not authorized to update the CUDA version of the system, so am looking for a workaround.

> ImportError: libcublas.so.9.0: cannot open shared object file: No such file or directory

**Comment by rootkitchao** [comment]
You can try to compile the tensorflow gpu of the specified CUDA version.But not sure if this will succeed.

**Comment by Akella17** [comment]
```tensorflow-gpu == 1.7.0``` is a requirement that needs to be met in the project. ```CUDA``` and ```CuDNN``` versions of the system are not to be altered with. Is there a workaround to this problem?

**Comment by Carmezim** [comment]
@Akella17 You can still compile TensorFlow from source with the codebase on v.1.7.0 targeting the CUDA/CuDNN versions specified.

**Comment by Akella17** [comment]
Okay. Thanks :)
