### ISSUE TITLE
tf.control_dependencies does execute nodes in the right order

### ISSUE THREAD

**Issue by jonassod** [tensorflow/tensorflow#28020]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): v1.10.0-rc1-19-g656e7a2b34,  1.10.0
- Python version: 3.6.6
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 9.0/7
- GPU model and memory:

You can collect some of this information using our environment capture [script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with
python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"

**Describe the current behavior**
with tf.control_dependiencies does not execute the dependant nodes before the nodes in the with block

**Describe the expected behavior**
the nodes in the with block are executed after the dependant nodes

**Code to reproduce the issue**
import tensorflow as tf
import numpy as np

x = tf.Variable(initial_value = 0.0, name = "x", dtype = tf.float32)
y = tf.Variable(initial_value = 0.0, name = "y", dtype = tf.float32)
zero = tf.constant(value = 0.0, dtype = np.float32, name = "zero")
op1 = tf.assign(x, zero)
with tf.control_dependencies([op1]):
    op2 = tf.assign(y, x)
with tf.control_dependencies([op2]):
    tf.assign_add(y, 1, name = "assign_add")

sess = tf.Session()
sess.run("assign_add")
print("y", sess.run("y:0"))

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by ppwwyyxx** [comment]
You should include the output of your code to show what the problem is. Please note that not everyone gets the same output running the same code.

Your issue sounds similar to existing ones such as #16277 and #14498, which can be solved by using ResourceVariable.

**Comment by achandraa** [comment]
Please have a look on @ppwwyyxx  suggestion and let us know. Thanks!

**Comment by jonassod** [comment]
Hi, thanks for the links to similar issues. My problem now seems to be more a question regarding the specification: In the code snippet below, can we say anything of the order of execution for the nodes node_a, node_b and node_c?

with tf.control_dependencies([node_a, node_b]):
    node_d = 10*node_c
sess.run(node_d)

I assumed that node_a and node_b were executed before node_c but when testing I saw that this is not always the case (even though it is the case in some situations) 

From #16277 it sounds like the behaviour for tf.Variable is complicated and depends on the type of operations in node_a, node_b and node_c, while the behaviour for tfe.Variable should be more predictable.

In the responses to a similar issue I also found: 
"The only guarantee tensorflow makes about order of execution is that all dependencies (either data or control) of an op are executed before that op gets executed."
https://github.com/tensorflow/tensorflow/issues/15077#issuecomment-349111997# 

Am I correct in saying that you should not use tf.control_dependencies() to ensure the order of reading/writing variables?

**Comment by ppwwyyxx** [comment]
> Am I correct in saying that you should not use tf.control_dependencies() to ensure the order of reading/writing variables?

For `tf.Variable` I think this is true. Execution order on ResourecVariable or `tfe.Variable` is better defined, however.

**Comment by achandraa** [comment]
@jonassod : Were you able to get the clarification ?

**Comment by jonassod** [comment]
Well, I understand that this is not a bug in Tensorflow, so in that sens it’s clear. The intended behavior for tf.control_dependencies() is however not clear to me. The question I am having is as follows:

In the code snippet below, can we say anything of the order of execution for the nodes node_a, node_b and node_c?

with tf.control_dependencies([node_a, node_b]):
node_d = 10*node_c
sess.run(node_d)

**Comment by ymodak** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow-tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.
