### ISSUE TITLE
java api runs much slower than Python API

### ISSUE THREAD

**Issue by mengpengfei** [tensorflow/tensorflow#28031]
i predict image with python api 
only need 15ms,
but with the same model,java api need 500+ms

**Comment by mengpengfei** [comment]
the java api need 400+ms
code: 
List<Tensor<?>> tesnsors=s.runner().feed("input", image).fetch("dense_decoded").run();

but the python api only need about 40ms ，

i think java api should more faster than the python api,

what can i do to let java api more faster?

**Comment by mengpengfei** [comment]
i test it on the same computer,the same model,the same image

**Comment by gadagashwini** [comment]
@mengpengfei This looks duplicate of [#27999.](https://github.com/tensorflow/tensorflow/issues/27999) Can we close this. Thanks!

**Comment by mengpengfei** [comment]
yes of course,   my goal is to solve this problem,   but nobody solve it

**Comment by gadagashwini** [comment]
@mengpengfei Since the issue is a duplicate. We shall close this issue and can track resolution on this [#27999](https://github.com/tensorflow/tensorflow/issues/27999). Thanks!

**Comment by mengpengfei** [comment]
ok
