### ISSUE TITLE
Object detection API, training part: NewRandomAccessFile failed to Create/Open: data/object-detection.pbtxt

### ISSUE THREAD

**Issue by Gerahal** [tensorflow/tensorflow#28033]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No I followed Sentdex tutorial about object detection API
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): pip install, GPU version of tensorflow
- TensorFlow version (use command below): 1.13.1
- Python version: 3.7
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: CUDA toolkit: 10.0.130 and cuDNN: 7.3.1
- GPU model and memory: NVIDIA GTX970M, 3GB

When I try this command in the anaconda prompt:
(from ...Tensorflow\models\research\object_detection)

python legacy/train.py 
--train_dir=training/ 
--pipeline_config_path=training/faster_rcnn_inception_v2_pets.config 
--logtostderr

It should start training to detect the objects I want but I get this error: 

tensorflow.python.framework.errors_impl.NotFoundError: NewRandomAccessFile failed to Create/Open: data/object-detection.pbtxt : Le fichier sp\udce9cifi\udce9 est introuvable.
; No such file or directory

And I can't figure why I get this error, the object-detection.pbtxt is in the right place, I have also tried to put entire path ( C:/folder1/folder2/.../data/object-detection.pbtxt ) in the config file. I tried to use normal / double slash or backslash in my command line and inside the config file.

Is it because of object-detection.pbtxt that is considered as a .txt file when I created it with the notepad ?
Hoping to find a solution quick.

**Comment by rootkitchao** [comment]
You should post this issue to [tensorflow/models](https://github.com/tensorflow/models).

**Comment by RitikaPandey77** [comment]
hey I got the same error, can you tell me where I am going wrong ?

**Comment by Pulkit12dhingra** [comment]
hey I am getting similar error
can you tell me where I am going wrong
