### ISSUE TITLE
i use tensoflow model to predict with java api,why it is more slowly than python or c++ api?

### ISSUE THREAD

**Issue by mengpengfei** [tensorflow/tensorflow#28030]
i use tensoflow model to predict with java api,why it is more slowly than python or c++ api?

**Comment by gadagashwini** [comment]
@mengpengfei This looks duplicate of [#27999](https://github.com/tensorflow/tensorflow/issues/27999). Can we close this. Thanks!

**Comment by mengpengfei** [comment]
yes， no problems
