### ISSUE TITLE
5526 illegal hardware instruction (core dumped)  python3

### ISSUE THREAD

**Issue by Darkells** [tensorflow/tensorflow#28032]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):Linux Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version:1.13.1
- Python version:3.7.3
- Installed using virtualenv? pip? conda?:pip3
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:GTX950M/4G

**Describe the problem**

**Provide the exact sequence of commands / steps that you executed before running into the problem**

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by Carmezim** [comment]
@Darkells Could you please provide the remaining details requested on the issue template? Otherwise it is difficult to properly assess and provide a solution. Thanks

**Comment by Darkells** [comment]
@Carmezim Thank you for your reply, I have fixed this problem.Because my cpu G4400 isn't support AVX

**Comment by achandraa** [comment]
Great that the issue got resolved. Let me close it.
