### ISSUE TITLE
Failed to create capture session; configuration failed

### ISSUE THREAD

**Issue by inakaaay** [tensorflow/tensorflow#28039]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): None
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: im using Raspberry Pi for android things implementation
- TensorFlow installed from (source or binary):
- TensorFlow version (use command below): 
- Python version:
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Describe the current behavior**
 i was going to implement the android repository(i edited the AndroidManifest.xml a little so only the DetectorActivity is going to launch) in android things when it failed to open the camera  

**Describe the expected behavior**
this was supposed to show a live camera preview
**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

**Other info / logs**
`ImageUtils:Native library not found,native RGB -> YUV conversion may be unavailable.
CameraConnectionFragment: Opening camera preview: 640x4480
CameraDevice-JV-0: Stream configuration failed due to: endConfigure:372: Camera 0: Unsupported set of inputs/outputs provided
CameraCaptureSession: Session 0: Failed to create capture session; configuration failed
`

**Comment by ymodak** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.
Thanks!
