### ISSUE TITLE
tflite segmentation model throws error on android

### ISSUE THREAD

**Issue by ajinkya933** [tensorflow/tensorflow#28040]
**System information**
- What is the top-level directory of the model you are using: models->research ->Deeplab
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 16.04
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below):1.13
- Bazel version (if compiling from source): bazel-0.24.0-installer-darwin-x86_64
- CUDA/cuDNN version: NA
- GPU model and memory: No GPUs used
- Exact command to reproduce:
tflite_convert \
  --output_file=test.lite \
  --graph_def_file=frozen_inference_graph.pb \
  --input_arrays=ImageTensor \
  --output_arrays=SemanticPredictions \
  --input_shapes=1,600,450,3 \
  --inference_input_type=QUANTIZED_UINT8 \
  --inference_type=FLOAT \
  --mean_values=128 \
  --std_dev_values=128 

**Describe the current behavior**
I am using tflite for semantic segmentation. I have a model trained to segment objects from background, this model is trained on deeplab.

I have converted this model(frozen inference graph) into tflite format using the below code:
```
tflite_convert \
  --output_file=test.lite \
  --graph_def_file=frozen_inference_graph.pb \
  --input_arrays=ImageTensor \
  --output_arrays=SemanticPredictions \
  --input_shapes=1,600,450,3 \
  --inference_input_type=QUANTIZED_UINT8 \
  --inference_type=FLOAT \
  --mean_values=128 \
  --std_dev_values=128 
```
The model loads on android, but when I try to run inference it gives me this error:

```
    Caused by: java.lang.IllegalStateException: Internal error: Unexpected failure when preparing tensor allocations: third_party/tensorflow/lite/kernels/unpack.cc:54 NumDimensions(input)

        1 was not true.Node number 4 (UNPACK) failed to prepare.

```

**Code to reproduce the issue**

tflite_convert \
  --output_file=test.lite \
  --graph_def_file=frozen_inference_graph.pb \
  --input_arrays=ImageTensor \
  --output_arrays=SemanticPredictions \
  --input_shapes=1,600,450,3 \
  --inference_input_type=QUANTIZED_UINT8 \
  --inference_type=FLOAT \
  --mean_values=128 \
  --std_dev_values=128 

**How do I resove this error?**

**Comment by ajinkya933** [comment]
I got to the next step by applying:

```
tflite_convert \
  --output_file=test2.lite \
  --graph_def_file=frozen_inference_graph_3mbvoc.pb \
  --input_arrays=ImageTensor \
  --output_arrays=SemanticPredictions \
  --input_shapes=1,450,600,3 \
  --inference_input_type=QUANTIZED_UINT8 \
  --inference_type=FLOAT \
  --mean_values=128 \
  --std_dev_values=128
```

The problem was in input shape mismatch. Even if this removes the error the graph generated by using above code does not produce any output. 

![Screenshot from 2019-04-23 14-42-20](https://user-images.githubusercontent.com/17012391/56633675-bfb81180-667c-11e9-9cde-908655827e40.png)

The graph on left is [my graph](https://drive.google.com/file/d/1uWcOCAHBcYwwf0yQSIJLlrctFNSr91oq/view). and the graph on right is googles graph.
How do I convert my tflight-graph to match that of [googles graph](https://drive.google.com/file/d/1wJ9RMFuZqs_TOW27ZPK6feToqmnNbepw/view)

**Comment by SanthoshRajendiran** [comment]
Give the input_arrays as sub_7 and output_arrays as ResizeBilinear_2. You will get the desired output.

**Comment by ajinkya933** [comment]
@SanthoshRajendiran  I get this when I try input_arrays as sub_7 and output_arrays as ResizeBilinear_2:

`tflite_convert   --output_file=resized.tflite   --graph_def_file=frozen_inference_graph_3mbvoc.pb   --input_arrays=sub_7   --output_arrays=ResizeBilinear_2   --input_shapes=1,450,600,3   --inference_input_type=QUANTIZED_UINT8   --inference_type=FLOAT   --mean_values=128   --std_dev_values=128
`

Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/bin/tflite_convert", line 11, in <module>
    sys.exit(main())
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow/lite/python/tflite_convert.py", line 442, in main
    app.run(main=run_main, argv=sys.argv[:1])
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow/lite/python/tflite_convert.py", line 438, in run_main
    _convert_model(tflite_flags)
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow/lite/python/tflite_convert.py", line 122, in _convert_model
    converter = _get_toco_converter(flags)
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow/lite/python/tflite_convert.py", line 109, in _get_toco_converter
    return converter_fn(**converter_kwargs)
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow/lite/python/lite.py", line 285, in from_frozen_graph
    sess.graph, input_arrays)
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow/lite/python/convert_saved_model.py", line 189, in get_tensors_from_tensor_names
    ",".join(invalid_tensors)))
ValueError: Invalid tensors 'sub_7' were found.

**Comment by SanthoshRajendiran** [comment]
Sry.. It must be sub_2.. Just now checked your graph properly

**Comment by ajinkya933** [comment]
ya just realized that, it generates the graph now, im checking its results on android

**Comment by ajinkya933** [comment]
I converted it here ([link](https://drive.google.com/file/d/1A-FYCHGCcafyk66ALm_7_EVt7Zd31697/view?usp=sharing))however when I run it on android (I am using [this](https://github.com/dailystudio/ml/tree/master/deeplab) guys code to do that). I get an error :

`Caused by: java.lang.IllegalArgumentException: Cannot convert between a TensorFlowLite buffer with 810000 bytes and a ByteBuffer with 792588 bytes.`

**Comment by SanthoshRajendiran** [comment]
This is because of the variation in the input and output sizes from the default GPU model. The value fixed by dailystudio is based on 224 as input and output size. You will have to find out what will be your corresponding values.

**Comment by ajinkya933** [comment]
Hi @SanthoshRajendiran as per your suggestions I found that IMAGE_MEAN, IMAGE_STD and BYTES_PER_POINT in DeepLabLite.java file are specified according to 257x257 input size in mind

```
private final static String MODEL_PATH = "deeplabv3_257_mv_gpu.tflite";
    private final static boolean USE_GPU = false;

    private static final float IMAGE_MEAN = 128.0f;
    private static final float IMAGE_STD = 128.0f;
    private final static int INPUT_SIZE = 257;
    private final static int NUM_CLASSES = 2;
    private final static int COLOR_CHANNELS = 3;
    private final static int BYTES_PER_POINT = 4;
```

IMAGE_MEAN, and  IMAGE_STD are INPUT_SIZE/2=128.5. 

Here they (dailystudio) have a advantage of INPUT_SIZE being same for width and height i.e 257x257.
In my case I have w=600 and h=450, how Do I mention these dimensions inside the INPUT_SIZE argument ?
