### ISSUE TITLE
Weird behavior using tf.Variable in a tf.data.experimental.map_and_batch callback function

### ISSUE THREAD

**Issue by prclibo** [tensorflow/tensorflow#28043]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: NA
- TensorFlow installed from (source or binary): 1.13.1 from conda
- TensorFlow version (use command below): 1.13.1
- Python version: 3.7.3
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

You can collect some of this information using our environment capture [script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with
python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"

**Code to reproduce the issue**

```
import tensorflow as tf

def foo(x):
    array = tf.Variable(lambda: tf.zeros(20, dtype=tf.float32),
            trainable=False, use_resource=True)
    ind = tf.reshape(x, [-1, 1])
    val = tf.reshape(tf.cast(x, tf.float32), [-1])

    array_assign = array.assign(tf.zeros_like(array))
    with tf.control_dependencies([array_assign]):
        array = array.scatter_nd_update(ind, tf.cast(val, dtype=tf.float32))

    return array

dataset = tf.data.Dataset.range(20)
# dataset = dataset.map(foo)
# dataset = dataset.batch(5)
dataset = dataset.apply(
        tf.data.experimental.map_and_batch(foo, 5, num_parallel_batches=1))

iterator = dataset.make_initializable_iterator()

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    sess.run(iterator.initializer)
    next_element = iterator.get_next()
    fetches = sess.run(next_element)
    print(fetches)
```

**Describe the current behavior**

If using normal `map` and `batch`, one get

```
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 2. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 3. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 4. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
```

**Describe the expected behavior**

If using `map_and_batch`, one get changing results like:

```
[[0. 1. 2. 3. 4. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 4. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 2. 3. 4. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 2. 3. 4. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 4. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
```

There should be always only one and non-duplicate non-zeros per-line.

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

Not sure if this is related to #27507 . On a [Colab with tf-nightly](https://colab.research.google.com/drive/1DzTvOJRXYUk0CSjvGa11ewmjTP7VJ1kF), #27507 seems fixed but this issue still reproduces.

**Comment by jvishnuvardhan** [comment]
@prclibo I got the following result 
WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/resource_variable_ops.py:435: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 2. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 3. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 4. 5. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]

Could you try to run it in Google colab or upgrade your TF1.13.1 and run it. Please let me know how it progresses. Thanks!

**Comment by prclibo** [comment]
@jvishnuvardhan No, on the above colab (https://colab.research.google.com/drive/1DzTvOJRXYUk0CSjvGa11ewmjTP7VJ1kF) the issue still reproduces, with updated tf-nightly version:

> `Successfully installed google-pasta-0.1.5 tb-nightly-1.14.0a20190423 tf-estimator-nightly-1.14.0.dev2019042301 tf-nightly-1.14.1.dev20190423 wrapt-1.11.1`

Which version are you using?

**Comment by jvishnuvardhan** [comment]
@prclibo I had used TF1.13.1 as you mentioned TF1.13.1 in your issue template.
I just tried TF-nightly and the output is as follows
W0424 01:48:58.248569 139709344798592 deprecation.py:323] From <ipython-input-3-5ac9480b764d>:19: map_and_batch (from tensorflow.python.data.experimental.ops.batching) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.data.Dataset.map(map_func, num_parallel_calls)` followed by `tf.data.Dataset.batch(batch_size, drop_remainder)`. Static tf.data optimizations will take care of using the fused implementation.
[[0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 2. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 3. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 2. 0. 4. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]

The result is not what is expected but the map_and_batch is going to be deprecated (check the warning above). The suggested op is map followed by batch which is working well in tf-nightly.  What is the point in using deprecated op when you have better working ops that replaced the deprecated op. Please let me know what you think. Thanks!

**Comment by prclibo** [comment]
@jvishnuvardhan Thanks for the tests. However I still reproduce it with separate `map` and `batch` in 1.14.1-dev20190423 (`!pip install tf-nightly`). See the last cell in https://colab.research.google.com/drive/1DzTvOJRXYUk0CSjvGa11ewmjTP7VJ1kF

Maybe you can share a successful Colab?

**Comment by jvishnuvardhan** [comment]
@prclibo I have changed one line in your code
`dataset = dataset.map(foo, num_parallel_calls=1)`
This is the output I get
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 2. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 3. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 4. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]

Here is the [gist](https://colab.sandbox.google.com/gist/jvishnuvardhan/2f3d68380a525f793bf63b7f13543c9e/test_tensorflow_27507.ipynb). Thanks!

**Comment by prclibo** [comment]
@jvishnuvardhan thanks, but setting `num_parallel_calls=1` does not really solve the issue, right?
I would expect that when `num_parallel_calls > 1` each line in its output has only one element scattered and the element is different from each other lines. The order of line can be permuted or not depending on the threading implementation. But the issue is not solved for `num_parallel_calls > 1` right now.

**Comment by jsimsa** [comment]
The behavior you see if expected because your `foo` function is using shared state -- the `array` variable will be shared by all invocations of the `foo` function because that's how resource variables in TensorFlow work. Furthermore, `map_and_batch` with `num_parallel_batches` with perform concurrent invocations of `foo`. That means that you will have multiple instances of `foo` all accessing (reading / writing) `array` at the same time, which explains the behavior you are seeing.

If you would like to achieve the "expected" behavior, use a constant instead of variable. As far as I can tell there is no good reason for you to need to be using a variable.

**Comment by prclibo** [comment]
@jsimsa Thanks. The reason of using a variable is that I failed to use a constant tensor in a `Dataset.map` callback operated by `scatter_nd_update`. See the second cell in https://github.com/tensorflow/tensorflow/issues/11239#issuecomment-313784148

Doing scattering onto a constant `tf.zeros(20)` causes `AttributeError: 'Tensor' object has no attribute '_lazy_read'`. Is there any workaround to solve this?

**Comment by jsimsa** [comment]
You can achieve the desired the behavior using the following simpler program:

```
import tensorflow as tf

def foo(x):
  array = tf.one_hot(x, 20) * tf.cast(x, dtype=tf.float32)
  return array

dataset = tf.data.Dataset.range(20)
dataset = dataset.map(foo)
dataset = dataset.batch(5)

iterator = dataset.make_initializable_iterator()

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    sess.run(iterator.initializer)
    next_element = iterator.get_next()
    fetches = sess.run(next_element)
    print(fetches)
```
