### ISSUE TITLE
I have the error FailedPreconditionError: Attempting to use uninitialized value dense_2/bias 	 [[node dense_2/bias/read (defined at C:/Users/TRAN THI DIEM/Documents/diem/research/ReinforcementLearning/code/CodeforlearningReinforcement/CNNandRL/Object-recognition-CIFAR-10-master/code_22_4_2019_done_firstversion_50loop_100images_verify_optimize_error_loss_ok_backup_version1.py:76) ]]

### ISSUE THREAD

**Issue by diemtran1005** [tensorflow/tensorflow#28041]
Here is my code. Please let me know what is my problem

import tensorflow as tf
from keras.datasets import cifar10
from keras.utils import np_utils
import numpy as np

import keras.backend as K
K.set_learning_phase(0)
import random
state_size = [32,32,3]
y = tf.placeholder(tf.float32, [None,10])
inputs_ = tf.placeholder(tf.float32, [None, *state_size])
learning_rate = 0.001
sess = tf.Session()
#sess.run(tf.initialize_all_variables())
sess.run(tf.global_variables_initializer())
init_op = tf.group(tf.initialize_all_variables(), tf.initialize_local_variables())
sess.run(init_op)
def neural_network_model ():
    #inputs_ = tf.placeholder(tf.float32, [None, *state_size])

    
    conv1 = tf.layers.conv2d(inputs=inputs_,
                              filters=32,
                              kernel_size=[3,3],
                              strides=[1,1],
                              padding="same",
                              kernel_initializer=tf.contrib.layers.xavier_initializer_conv2d()
                              )

    conv1_batchnorm = tf.layers.batch_normalization(conv1,
                                                     training=True,
                                                     epsilon=1e-5
                                                     )

    conv1_out = tf.nn.elu(conv1_batchnorm)
## --> [30, 30, 32]

    conv2 = tf.layers.conv2d(inputs=conv1_out,
                              filters=32,
                              kernel_size=[3, 3],
                              strides=[1,1],
                              padding="same",
                              kernel_initializer=tf.contrib.layers.xavier_initializer_conv2d()
                              )

    conv2_batchnorm = tf.layers.batch_normalization(conv2,
                                                     training=True,
                                                     epsilon=1e-5
                                                     )

    conv2_out = tf.nn.elu(conv2_batchnorm)
## --> [28, 28, 32]

    conv3 = tf.layers.conv2d(inputs=conv2_out,
                              filters=64,
                              kernel_size=[3,3],
                              strides=[1,1],
                              padding="VALID",
                              kernel_initializer=tf.contrib.layers.xavier_initializer_conv2d()
                              )

    conv3_batchnorm = tf.layers.batch_normalization(conv3,
                                                     training=True,
                                                     epsilon=1e-5
                                                     )

    conv3_out = tf.nn.elu(conv3_batchnorm)
## --> [26, 26, 64]

    flatten = tf.layers.flatten(conv3_out)
## --> [43,264]

    fc = tf.layers.dense(inputs=flatten,
                          units=512,
                          activation=tf.nn.elu,
                          kernel_initializer=tf.contrib.layers.xavier_initializer()
                          )

    output = tf.layers.dense(inputs=fc,
                              kernel_initializer=tf.contrib.layers.xavier_initializer(),
                              units=10,
                              activation=None)
    return output

def training_network_option1 ():
    sess = tf.Session()
#sess.run(tf.initialize_all_variables())
    sess.run(tf.global_variables_initializer())
#    y = tf.placeholder(tf.float32, [None,10])
    prediction = neural_network_model()
    # OLD VERSION:
    #cost = tf.reduce_mean( tf.nn.softmax_cross_entropy_with_logits(prediction,y) )
    # NEW:
    cost = tf.reduce_mean( tf.nn.softmax_cross_entropy_with_logits(logits=prediction, labels=y) )
    optimizer=tf.train.RMSPropOptimizer(learning_rate).minimize(cost)
    return cost, optimizer
    
def training_network_option2 ():
#    y = tf.placeholder(tf.float32, [None,10])
    sess = tf.Session()
#sess.run(tf.initialize_all_variables())
    sess.run(tf.global_variables_initializer())
    prediction = neural_network_model()
    # OLD VERSION:
    #cost = tf.reduce_mean( tf.nn.softmax_cross_entropy_with_logits(prediction,y) )
    # NEW:
    cost = tf.reduce_mean( tf.nn.softmax_cross_entropy_with_logits(logits=prediction, labels=y) )
    optimizer=tf.train.MomentumOptimizer(learning_rate).minimize(cost)    
    return cost, optimizer
    
def training_network_option3 ():
#    y = tf.placeholder(tf.float32, [None,10])
    sess = tf.Session()
#sess.run(tf.initialize_all_variables())
    sess.run(tf.global_variables_initializer())
    prediction = neural_network_model()
    # OLD VERSION:
    #cost = tf.reduce_mean( tf.nn.softmax_cross_entropy_with_logits(prediction,y) )
    # NEW:
    cost = tf.reduce_mean( tf.nn.softmax_cross_entropy_with_logits(logits=prediction, labels=y) )
    optimizer=tf.train.AdamOptimizer(learning_rate).minimize(cost) 
    return cost, optimizer

    
    

def possible_action():
    batch =0
    stochastic =1
    mini_batch = 2

    actions =np.array([batch, stochastic, mini_batch])
    return actions

def normalize(x):
    """
        argument
            - x: input image data in numpy array [32, 32, 3]
        return
            - normalized x
    """
    min_val = np.min(x)
    max_val = np.max(x)
    x = (x-min_val) / (max_val-min_val)
    return x

(X_train, y_train), (X_test, y_test) = cifar10.load_data()

X_train = X_train.astype('float32')
X_test = X_test.astype('float32')
X_train = normalize(X_train)
X_test = normalize(X_test)
y_train = np_utils.to_categorical(y_train)
y_test = np_utils.to_categorical(y_test)
num_classes = y_test.shape[1]

#DQNetwork

action_size = 3

batch_size = 10

state_batch = 100//batch_size
# Exploration parameters for epsilon greedy strategy
explore_start = 1.0            # exploration probability at start
explore_stop = 0.01            # minimum exploration probability 
decay_rate = 0.1            # exponential decay rate for exploration prob

# Q learning hyperparameters
gamma = 0.95  

actions = np.array(possible_action())
current_action =actions [0]

#dqn1 = DQNetwork(state_size, action_size)
#dqn2 = DQNetwork(state_size, action_size)
#dqn_total = DQNetwork(state_size, action_size)

#current_state =X_train[0:64]
#Y_label =y_train[0:64]

loss_actions = []
loss_actions_test = []
action_test = []
loss_total_test = []
#loss_next_state = 100*random ()

loss_before = 2*(random.random())
Qtable =np.zeros((state_batch,action_size))
np.random.seed(100)
exp_exp_tradeoff = 0.5

#print ("random of explore", exp_exp_tradeoff)
step=0

for eps in range(50):
   i = 0
   print ("\n")
   while i<state_batch-1:
   #while i<20:
        current_state = X_train[i*batch_size:(i+1)*batch_size]
    
        Y_label = y_train [i*batch_size:(i+1)*batch_size]
        
       # dqn = DQNetwork(state_size, action_size, learning_rate)
        #sess.run(dqn.optimizer,feed_dict={dqn.inputs_:current_state,dqn.label:Y_label
                                                       # }) 
        #sess.run(dqn.input_action, feed_dict = {dqn.input_action: current_action})
       # dqn = DQNetwork(state_size, action_size, learning_rate,current_action)
        if current_action == 0:
           cost,optimizer = training_network_option1 ()
        elif current_action ==1:
           cost,optimizer = training_network_option2 ()
        elif current_action ==2:   
           cost,optimizer = training_network_option2 ()
        
   
       
        _, loss_current = sess.run([optimizer, cost], feed_dict={inputs_: current_state, y: Y_label})

**Comment by achandraa** [comment]
Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version. Also, did you compile from source or install a binary?

Make sure you also include the exact command if possible to produce the output included in your test case. If you are unclear what to include see the issue template displayed in [the Github new issue template](https://github.com/tensorflow/tensorflow/issues/new/choose).

We ask for this in the issue submission template, because it is really difficult to help without that information. Thanks!

**Comment by achandraa** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
