### ISSUE TITLE
misalignment in BahdanauAttention documentation

### ISSUE THREAD

**Issue by vishalsubbiah** [tensorflow/tensorflow#28054]
**System information**
- TensorFlow version: 1.13
- Doc Link: https://www.tensorflow.org/api_docs/python/tf/contrib/seq2seq/BahdanauAttention

Under the description for the __init__ function, in the Args, the memory_sequence_length should be in its own point and not part of memory.

**We welcome contributions by users. Will you be able to update submit a PR (use the [doc style guide](https://www.tensorflow.org/community/documentation)) to fix the doc Issue?** Yes, I can submit a PR for this.

**Comment by yongtang** [comment]
Added PR #28267 for the fix.
