### ISSUE TITLE
Where is the legacy_seq2seq of the tensorflow 2.0 version?

### ISSUE THREAD

**Issue by longer008** [tensorflow/tensorflow#28058]
Where is the legacy_seq2seq of the tensorflow 2.0 version?

**Comment by jvishnuvardhan** [comment]
@flylonger It is [here](https://github.com/tensorflow/tensorflow/tree/r2.0/tensorflow/contrib/legacy_seq2seq). Thanks!

**Comment by jasonzhang2022** [comment]
seq2seq is mentioned in this tutorial: https://www.tensorflow.org/alpha/tutorials/text/nmt_with_attention. But the link is broken

**Comment by jvishnuvardhan** [comment]
@jasonzhang2022 Are you mentioning about the link here "TensorFlow Neural Machine Translation (seq2seq) tutorial. " I think that link is taking us to tutorial home page. Please let us know if there is any other links that are not working. If the link is taking you to "error 404" then please provide your location (ex. America, Europe, Asia, etc). Thanks!

**Comment by jasonzhang2022** [comment]
Yes, I mean that link. I expect the link taking me to the seq2seq tutorial
instead of tutorial home page.

**Comment by amahendrakar** [comment]
> @flylonger It is [here](https://github.com/tensorflow/tensorflow/tree/r2.0/tensorflow/contrib/legacy_seq2seq). Thanks!

@longer008,
Please check this comment and let us know if helps. Thanks!
