### ISSUE TITLE
Failed to get device properties, error code: 30

### ISSUE THREAD

**Issue by stevehawley** [tensorflow/tensorflow#28053]
**Describe the current behavior**
I commented under issue #26255 but the original poster closed the issue as his problem was solved by updating to tensorflow 2.

I am opening a new issue because updating to the pre-release is not an option and I have no way to even trap this error to try to handle it, plus it is an unknown error code so no hint as to how to proceed.

Unknown error and failure to initialize GPU. 
```
2019-04-19 13:16:22.838705: E tensorflow/core/grappler/clusters/utils.cc:83] Failed to get device properties, error code: 30
Failed to initialize GPU device #0: unknown error
```
My configuration:
Windows 10 Home
Tensorflow 1.13.1
Python 3.5
GTX 1060 Mobile Max-Q

It doesn't happen every time I run my program. I have localized it to running load_model from keras, before reaching that point I have imported tensorflow and verified that gpu is available.
```python
  if tf.test.is_gpu_available():
        logger.debug("GPU is available")
```
Is there a way to catch this error or check for it and recover/attempt to reinitialize?

Thanks
**Describe the expected behavior**
Report the actual error, provide mechanism to catch the exception and handle it.

**Code to reproduce the issue**
The failure is intermittent

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by achandraa** [comment]
@stevehawley : Could you be able to provide more details on the issue and its context. If possible, provide a code to reproduce the bug. Thanks!

**Comment by stevehawley** [comment]
I have no idea what is causing it, other than it occurs when running load_model and it is an intermittent failure. It occurs essentially at startup, there isn't a variation in sequence of events that leads to the failure as far as I can see at this time.

I would be happy to add any debug code you suggest and report back.

**Comment by zjumhy97** [comment]
I have a error like this:
`2019-04-24 22:43:01.696579: E tensorflow/core/grappler/clusters/utils.cc:83] Failed to get device properties, error code: 30`
and I don't know how to deal with it.

**Comment by achandraa** [comment]
@stevehawley : Sure that would help us to dig in easily. Thanks!

**Comment by mylogon341** [comment]
@stephanwlee I have the **exact** same config as you and I am also running into this issue. I am using SSD_Mobilenet_v2 for object detection. mobilenet v1 was working fine for me the other day so will probably just revert to that. I run into the same issue when running train.py and model_main.py. Not sure what details to provide that might help, but feel free to ask

**Comment by jvishnuvardhan** [comment]
@stevehawley Could you provide any standalone code to reproduce the issue? thanks!

**Comment by stevehawley** [comment]
@jvishnuvardhan I'm sorry, I cannot provide code that reproduces it as it is an intermittent issue. If you have debug code you would like me to add to the software to capture data for further debugging I would be happy to do that.

**Comment by aaroey** [comment]
Error code 30 is cudaErrorUnknown. There could be many reasons. It would be good if anyone can provide code and model/data that can consistently reproduce the problem.

**Comment by stevehawley** [comment]
In the past where I have had a customer reporting an intermittent issue I would add better error reporting so the next time it occurs we would have the data we need to explain and maybe fix the issue. Can such a thing be added to tensorflow around this line of code? Could it capture more information from cuda? Maybe throw an exception so that the application can do something to handle the error? Currently the error is logged but there is no good way for the application to know a problem occurred and respond appropriately.

**Comment by aaroey** [comment]
@stevehawley I think this will be hard. Sometimes it may not be possible or very hard to recover from CUDA errors. Some of the errors are 'sticky'. Typically those are the kinds of errors that lead to the unexpected kernel termination, and the only way out is to completely reset GPU state with cudaDeviceReset(). And for some of them, rebooting the machine or resetting the GPU is the only way to recover. So this usually goes deeper than TF and can explain why it didn't bother to attempt recovering. If you have a better idea please let me know.

In addition, if you have a repro, even though it cannot reproduce the problem consistently, but as long as it can reproduce the problem say one at a hundred times, it would be very helpful and probably means there is a bug somewhere else, and we'll be happy to investigate.

**Comment by aaroey** [comment]
@nluehr do you have any ideas?

**Comment by stevehawley** [comment]
Understand that it may not be recoverable, but the current behavior is that an error has occurred and the GPU is in an unknown state, the error is logged but the application is unaware and continues to try to use the GPU with no result. At a minimum I think tensorflow should throw an exception so that the application can inform the user and cleanup. 

If there is an API for resetting the GPU the application could decide to try some number of times before giving up, then report the failure to the user, cleanup and exit.

**Comment by aaroey** [comment]
@stevehawley sorry I misunderstood that before. So you were saying to let it return an error status. @rmlarsen do you think that's something we can/should do?

**Comment by rowem** [comment]
@aaroey   I have the same error message; see screenshot of conda prompt history below.
![Anaconda Prompt history Capture](https://user-images.githubusercontent.com/28427504/58682955-e83ad600-83b5-11e9-8841-1fdc6e49dfa1.PNG)

PC Details:
Windows 10 Home
Dell 7559 with 16gb RAM, NVIDIA GTX960M (4GB)

Jupyter Notebook to re-produce the error is in ZIP file below.  You will need to download the Flickr8k dataset to run this code
[GPU_failed_to_get_device_code.zip](https://github.com/tensorflow/tensorflow/files/3239765/GPU_failed_to_get_device_code.zip)
.
The failure is not fatal, as code keeps processing (very slowly), presumably on the CPU, but not sure what "Adapting to protcol v5.1...." line on Anaconda prompt means??
I have only run this code twice and it gave the same error message each time, with a full re-boot between runs.
I have also seen the same conda prompt history message running other, similar keras based code in the last few weeks, so would love to find a solution.

**Comment by a-gn** [comment]
Hi, I get that same error message every time I call `session.run(something)`. Here's one simple call that triggers it:

```
Python 3.7.2 (tags/v3.7.2:9a3ffc0492, Dec 23 2018, 23:09:28) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
>>> sess = tf.Session()
2019-05-31 10:26:17.055157: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
2019-05-31 10:26:18.052608: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1433] Found device 0 with properties:
name: GeForce GTX 1050 major: 6 minor: 1 memoryClockRate(GHz): 1.493
pciBusID: 0000:01:00.0
totalMemory: 4.00GiB freeMemory: 3.30GiB
2019-05-31 10:26:18.059187: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1512] Adding visible gpu devices: 0
2019-05-31 10:26:20.176475: I tensorflow/core/common_runtime/gpu/gpu_device.cc:984] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-05-31 10:26:20.180563: I tensorflow/core/common_runtime/gpu/gpu_device.cc:990]      0
2019-05-31 10:26:20.182798: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1003] 0:   N
2019-05-31 10:26:20.185520: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 3011 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1050, pci bus id: 0000:01:00.0, compute capability: 6.1)
>>> sess.run(tf.rank(tf.Variable([3], dtype = tf.int32)))
WARNING:tensorflow:From C:\Users\user\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\framework\op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
2019-05-31 10:26:46.385633: E tensorflow/core/grappler/clusters/utils.cc:83] Failed to get device properties, error code: 30
1
>>>
```

In case it matters, I'm on an XPS 15 9560 (so, Optimus) and have CUDA 10.0 and have tensorflow-gpu 1.13.1 installed from pip. If you need more information I'd be happy to provide it, this makes computations quite slow for me.

**Comment by amans191** [comment]
Did you find a fix? I would love to know how you solved the issue.

**Comment by aaroey** [comment]
@andyly would you mind to take a look at this? What will be the best way for Grappler to report the error?

**Comment by a-gn** [comment]
> Did you find a fix? I would love to know how you solved the issue.

If that can help, a few days ago I compiled TensorFlow 1.14 with CUDA 10.1 (not yet supported by the pip binaries), and I'm *reasonably sure* that I didn't have this error and the GPU was used.

But then I reinstalled Windows and now I'm getting build errors, so I can't check anymore. I will post here if I succeed in compiling it again.

**Comment by a-gn** [comment]
I compiled TensorFlow 1.14.0 for CUDA 10.1 on Windows 10, then ran a small script using it, and I got another error message: `E tensorflow/core/grappler/clusters/utils.cc:87] Failed to get device properties, error code: 999`. The GPU was used though, so the error doesn't seem important.

**Comment by kuccello** [comment]
Hi all, I have encountered this issue consistently while working through the TF tutorial for the fashion-mnist (https://www.tensorflow.org/tutorials/keras/basic_classification).

My rig is a Razor Pro laptop (Late 2016), win 10 pro with a Thunderbolt 3 connected egpu Razor Core X Chroma housing an Asus GeForce 2080 Ti

```
WARNING:tensorflow:From C:\Users\kuccello\Anaconda3\lib\site-packages\tensorflow\python\ops\resource_variable_ops.py:435: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
2019-07-21 09:57:23.404013: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX AVX2
2019-07-21 09:57:25.163980: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1433] Found device 0 with properties: 
name: GeForce RTX 2080 Ti major: 7 minor: 5 memoryClockRate(GHz): 1.65
pciBusID: 0000:07:00.0
totalMemory: 11.00GiB freeMemory: 9.03GiB
2019-07-21 09:57:25.861157: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1433] Found device 1 with properties: 
name: GeForce GTX 1060 major: 6 minor: 1 memoryClockRate(GHz): 1.6705
pciBusID: 0000:01:00.0
totalMemory: 6.00GiB freeMemory: 4.97GiB
2019-07-21 09:57:25.861781: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1512] Adding visible gpu devices: 0, 1
2019-07-21 09:57:27.554340: I tensorflow/core/common_runtime/gpu/gpu_device.cc:984] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-07-21 09:57:27.554600: I tensorflow/core/common_runtime/gpu/gpu_device.cc:990]      0 1 
2019-07-21 09:57:27.554763: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1003] 0:   N N 
2019-07-21 09:57:27.555168: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1003] 1:   N N 
2019-07-21 09:57:27.555731: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 8699 MB memory) -> physical GPU (device: 0, name: GeForce RTX 2080 Ti, pci bus id: 0000:07:00.0, compute capability: 7.5)
2019-07-21 09:57:27.557220: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:1 with 4716 MB memory) -> physical GPU (device: 1, name: GeForce GTX 1060, pci bus id: 0000:01:00.0, compute capability: 6.1)
Epoch 1/5
2019-07-21 09:57:28.924614: I tensorflow/stream_executor/dso_loader.cc:152] successfully opened CUDA library cublas64_100.dll locally
```

The code executes and makes a prediction. The error code 30 seems to happen consistenly when calling

```python
predictions = model.predict(test_images)
```

Snipped output from log

```
...
8928/10000 [=========================>....] - ETA: 0s - loss: 0.3602 - acc: 0.8694
 9600/10000 [===========================>..] - ETA: 0s - loss: 0.3614 - acc: 0.8697
10000/10000 [==============================] - 1s 87us/sample - loss: 0.3590 - acc: 0.8705
Test accuracy: 0.8705
2019-07-21 09:58:10.393072: E tensorflow/core/grappler/clusters/utils.cc:83] Failed to get device properties, error code: 30
Predictions: [1.22570145e-05 3.14548632e-09 4.37460756e-07 1.29987212e-08
 1.61830727e-07 2.23822240e-02 1.34041156e-05 1.87597424e-01
 1.36709845e-04 7.89857388e-01]
Highest Confidence: 9
...
```

**Comment by p-dimi** [comment]
If it's any help - I was running a script for model compression, and started getting this error when I disconnected my laptop from the power and it started running on battery.
After I reconnected it to the power, and restarted the script, the errors did not return.

**Comment by a-gn** [comment]
> I was running a script for model compression, and started getting this error when I disconnected my laptop from the power and it started running on battery.

Probably your laptop is configured to shut the GPU off when on battery? This doesn't work for me, I always keep it plugged.

**Comment by AbhishekKarthik** [comment]
Even I was facing the same problem while training my model using a GPU, then I updated my NVIDIA GPU driver using GeForce Experience App and the error stopped occurring.

**Comment by CHIKKIZZY** [comment]
Updating my Nvidia driver worked for me too. Thanks @AbhishekKarthik

**Comment by s-sd** [comment]
I had the same issue. It appeards to be an issue with the save or load model. What I did was, I created the model again and saved and loaded only the weights. This solved it for me. Hope that helps.

**Comment by sanjoy** [comment]
> I commented under issue #26255 but the original poster closed the issue as his problem was solved by updating to tensorflow 2. ...  I am opening a new issue because updating to the pre-release is not an option

Can you check if upgrading to TF 2 helps now that TF2 is no longer pre-release?

> but the current behavior is that an error has occurred and the GPU is in an unknown state, the error is logged but the application is unaware and continues to try to use the GPU with no result. At a minimum I think tensorflow should throw an exception so that the application can inform the user and cleanup.

If you need this behavior perhaps you could explicitly do `assert tf.test.is_gpu_available()`?

**Comment by AndrewKalugin** [comment]
I had the same issue. My work machine is a laptop.
I solved this problem by lifting the electricity limit. And I started the entire cooling system to the maximum.

**Comment by fsan** [comment]
I have this problem because of a condition of two different processes concurring for initilizating tensorflow.
I really did not solve the problem, but, I found some workaround for my case.

Im using a Nvidia v100 + Nvidia tensorflow docker image 20.03
I have a lib that wraps some Tensorflow models and an application that runs this lib + another models in tf too.

In the beginning of my app I start a Process (multiprocess.Process) and this process will include the lib that includes tensorflow during its initialization causing the Nvidia+tf stuff to be started.
Meanwhile the main thread of my original process keeps its own bootstrapping and tries to initialize TF.


When a call from the subprocess reaches a tf code it will freeze and will display the "Failed to get device properties..."
I'm not sure why, but I noticed that TF does not work well when different processes from same root tries to use TF before. So I changed my code from multiprocessing.Process to threading.Thread and the error is gone.

For a proper solution I will refactor my code and avoid one of the inits because it isn't really necessary at that point.
But I thought to share my experience here in case it enlightens someone else.

**Comment by fjsh84** [comment]
Hi
with NVIDIAe  Geforce GT 525m i  have this error for this code device_lib.list_local_devices(session_config=None):
RuntimeError: failed to get compute capability major for device: UNKNOWN ERROR (1); 0
Is this because of my compute capability (2.1)?

**Comment by nluehr** [comment]
Hi, @fjsh84. TensorFlow requires a compute capability of at least 3.5 per https://www.tensorflow.org/install/gpu. The CUDA toolkit has also removed support for Compute Capability 2.x hardware. The specific error you note is more likely caused by the NVIDIA driver or CUDA runtime not being configured correctly. But that doesn't really matter given that the hardware wouldn't be supported anyway.

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this issue, as you are using an older version of tensorflow(1.x) which is officially considered as end of life. We recommend that you upgrade to 2.4 or later version and let us know if the issue still persists in newer versions. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, Please open a new issue for any help you need against 2.x, and we will get you the right help.
