### ISSUE TITLE
TypeError: 'Tensor' object is not callable when using tf.keras.optimizers.Adam, works fine when using tf.compat.v1.train.AdamOptimizer

### ISSUE THREAD

**Issue by tarrade** [tensorflow/tensorflow#28068]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Mac OS 
- TensorFlow installed from (source or binary): binary with pip
- TensorFlow version (use command below): 2.0 alpha0
- Python version: 3.6

**Describe the current behavior**
I am trying to migrate 1.12 code using estimator to TF 2.0 using everything from keras as it is suggested. Unfortunatley there is no example yet in TF 2.0 documentation. Here it is only partially using new keras functions:
https://www.tensorflow.org/alpha/tutorials/distribute/multi_worker

```
    # Compute loss for both TRAIN and EVAL modes
    ##loss = tf.compat.v1.losses.softmax_cross_entropy(onehot_labels=labels, logits=logits)
    loss = tf.keras.losses.CategoricalCrossentropy(from_logits=True)(labels, logits)

    # Generate necessary evaluation metrics
    ##accuracy = tf.compat.v1.metrics.accuracy(labels=tf.argmax(input=labels, axis=1), predictions=classes, name='accuracy')
    accuracy = tf.keras.metrics.CategoricalAccuracy()
    accuracy.update_state(labels, logits)

    eval_metrics = {'accuracy': accuracy}

    tf.summary.scalar('accuracy', accuracy.result())

    # Provide an estimator spec for `ModeKeys.EVAL`
    if mode == tf.estimator.ModeKeys.EVAL:
        return tf.estimator.EstimatorSpec(mode=mode,
                                          loss=loss,
                                          eval_metric_ops=eval_metrics)

    # Provide an estimator spec for `ModeKeys.TRAIN`
    if mode == tf.estimator.ModeKeys.TRAIN:

        # crashing
        optimizer = tf.keras.optimizers.Adam(learning_rate=0.01, beta_1=0.9, epsilon=1e-07)

        ##optimizer = tf.compat.v1.train.AdamOptimizer(learning_rate=0.001, beta1=0.9)

        train_op = optimizer.minimize(loss, tf.compat.v1.train.get_or_create_global_step())

        return tf.estimator.EstimatorSpec(mode=mode,
                                          loss=loss,
                                          train_op=train_op)
```

**Describe the expected behavior**
replacing:
`optimizer = tf.keras.optimizers.Adam(learning_rate=0.01, beta_1=0.9, epsilon=1e-07)`
by 
`optimizer = tf.compat.v1.train.AdamOptimizer(learning_rate=0.001, beta1=0.9)`
it works without any issue.

There is so many changes with TF 2.0, that it could be that I am did a wrong implementation but I managed to migrate all old components to keras layer, loss, metrics ...

I couldn't find an equivalent for "tf.compat.v1.train.get_or_create_global_step()" for TF 2.0 (without using the compatibility module v1)

**Code to reproduce the issue**
`# estimator model
def baseline_estimator_model(features, labels, mode, params):
    """
    Model function for Estimator
    """
    print('model based on keras layer but return an estimator model')

    # gettings the bulding blocks
    model = keras_building_blocks(params['dim_input'], params['num_classes'])

    dense_inpout = features['dense_input']

    # Logits layer
    if mode == tf.estimator.ModeKeys.TRAIN:
        logits = model(dense_inpout, training=True)
    else:
        logits = model(dense_inpout, training=False)

    # Compute predictions
    probabilities = tf.nn.softmax(logits)
    classes = tf.argmax(input=probabilities, axis=1, )

    # made prediction
    predictions = {
        'classes': classes,
        'probabilities': probabilities,
    }

    # to be tested
    predictions_output = tf.estimator.export.PredictOutput(predictions)

    #predictions_output = {
    #    'classify': tf.estimator.export.PredictOutput(predictions)
    #}

    # Provide an estimator spec for `ModeKeys.PREDICT`
    if mode == tf.estimator.ModeKeys.PREDICT:
        return tf.estimator.EstimatorSpec(mode=mode,
                                          predictions=predictions,
                                          export_outputs={tf.saved_model.DEFAULT_SERVING_SIGNATURE_DEF_KEY: predictions_output})

    # Compute loss for both TRAIN and EVAL modes
    ##loss = tf.compat.v1.losses.softmax_cross_entropy(onehot_labels=labels, logits=logits)
    loss = tf.keras.losses.CategoricalCrossentropy(from_logits=True)(labels, logits)

    # Generate necessary evaluation metrics
    ##accuracy = tf.compat.v1.metrics.accuracy(labels=tf.argmax(input=labels, axis=1), predictions=classes, name='accuracy')
    accuracy = tf.keras.metrics.CategoricalAccuracy()
    accuracy.update_state(labels, logits)

    #print(tf.argmax(input=labels, axis=1))
    #print(classes)

    eval_metrics = {'accuracy': accuracy}

    tf.summary.scalar('accuracy', accuracy.result())

    # Provide an estimator spec for `ModeKeys.EVAL`
    if mode == tf.estimator.ModeKeys.EVAL:
        return tf.estimator.EstimatorSpec(mode=mode,
                                          loss=loss,
                                          eval_metric_ops=eval_metrics)

    # Provide an estimator spec for `ModeKeys.TRAIN`
    if mode == tf.estimator.ModeKeys.TRAIN:

        # crashing
        optimizer = tf.keras.optimizers.Adam(learning_rate=0.01, beta_1=0.9, epsilon=1e-07)

        #optimizer = tf.compat.v1.train.AdamOptimizer(learning_rate=0.001, beta1=0.9)

        print('step 7')
        train_op = optimizer.minimize(loss, tf.compat.v1.train.get_or_create_global_step())

        print('step 8')
        return tf.estimator.EstimatorSpec(mode=mode,
                                          loss=loss,
                                          train_op=train_op)
        print('step 9')`

notebook can be find here with the code, tf.dataset ...:
https://github.com/tarrade/proj_DL_models_and_pipelines_with_GCP/blob/master/notebook/TF_2.0/08-Mnist_keras_estimator.ipynb

**Other info / logs**
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<timed exec> in <module>

~/Desktop/Work/Data_Science/Tutorials_Codes/Python/proj_DL_models_and_pipelines_with_GCP/src/model_mnist_2_0_v1/trainer/model.py in train_and_evaluate(FLAGS, use_keras)
    587                                       #exporters=exporter)
    588 
--> 589     tf.estimator.train_and_evaluate(estimator, train_spec, eval_spec)
    590 
    591 def train_and_evaluate_old(FLAGS, use_keras):

~/anaconda3/envs/env_gcp_dl_2_0_alpha/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/training.py in train_and_evaluate(estimator, train_spec, eval_spec)
    471         '(with task id 0).  Given task id {}'.format(config.task_id))
    472 
--> 473   return executor.run()
    474 
    475 

~/anaconda3/envs/env_gcp_dl_2_0_alpha/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/training.py in run(self)
    611         config.task_type != run_config_lib.TaskType.EVALUATOR):
    612       logging.info('Running training and evaluation locally (non-distributed).')
--> 613       return self.run_local()
    614 
    615     # Distributed case.

~/anaconda3/envs/env_gcp_dl_2_0_alpha/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/training.py in run_local(self)
    712         max_steps=self._train_spec.max_steps,
    713         hooks=train_hooks,
--> 714         saving_listeners=saving_listeners)
    715 
    716     eval_result = listener_for_eval.eval_result or _EvalResult(

~/anaconda3/envs/env_gcp_dl_2_0_alpha/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/estimator.py in train(self, input_fn, hooks, steps, max_steps, saving_listeners)
    357 
    358       saving_listeners = _check_listeners_type(saving_listeners)
--> 359       loss = self._train_model(input_fn, hooks, saving_listeners)
    360       logging.info('Loss for final step: %s.', loss)
    361       return self

~/anaconda3/envs/env_gcp_dl_2_0_alpha/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/estimator.py in _train_model(self, input_fn, hooks, saving_listeners)
   1137       return self._train_model_distributed(input_fn, hooks, saving_listeners)
   1138     else:
-> 1139       return self._train_model_default(input_fn, hooks, saving_listeners)
   1140 
   1141   def _train_model_default(self, input_fn, hooks, saving_listeners):

~/anaconda3/envs/env_gcp_dl_2_0_alpha/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/estimator.py in _train_model_default(self, input_fn, hooks, saving_listeners)
   1167       worker_hooks.extend(input_hooks)
   1168       estimator_spec = self._call_model_fn(
-> 1169           features, labels, ModeKeys.TRAIN, self.config)
   1170       global_step_tensor = training_util.get_global_step(g)
   1171       return self._train_with_estimator_spec(estimator_spec, worker_hooks,

~/anaconda3/envs/env_gcp_dl_2_0_alpha/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/estimator.py in _call_model_fn(self, features, labels, mode, config)
   1125 
   1126     logging.info('Calling model_fn.')
-> 1127     model_fn_results = self._model_fn(features=features, **kwargs)
   1128     logging.info('Done calling model_fn.')
   1129 

~/Desktop/Work/Data_Science/Tutorials_Codes/Python/proj_DL_models_and_pipelines_with_GCP/src/model_mnist_2_0_v1/trainer/model.py in baseline_estimator_model(features, labels, mode, params)
    440 
    441         print('step 7')
--> 442         train_op = optimizer.minimize(loss, tf.compat.v1.train.get_or_create_global_step())
    443 
    444         print('step 8')

~/anaconda3/envs/env_gcp_dl_2_0_alpha/lib/python3.6/site-packages/tensorflow/python/keras/optimizer_v2/optimizer_v2.py in minimize(self, loss, var_list, grad_loss, name)
    294     """
    295     grads_and_vars = self._compute_gradients(
--> 296         loss, var_list=var_list, grad_loss=grad_loss)
    297 
    298     return self.apply_gradients(grads_and_vars, name=name)

~/anaconda3/envs/env_gcp_dl_2_0_alpha/lib/python3.6/site-packages/tensorflow/python/keras/optimizer_v2/optimizer_v2.py in _compute_gradients(self, loss, var_list, grad_loss)
    326     with backprop.GradientTape() as tape:
    327       tape.watch(var_list)
--> 328       loss_value = loss()
    329     grads = tape.gradient(loss_value, var_list, grad_loss)
    330 

TypeError: 'Tensor' object is not callable

**Comment by tarrade** [comment]
Same error message when I do it in a more native 2.0 way:

`train_op = optimizer.minimize(loss,var_list=model.weights)`

**Comment by ymodak** [comment]
For using ```tf.train.get_or_create_global_step``` in TF 2.X ```tf.compat.v1.train.get_or_create_global_step()``` is correct conversion. You will have to use v1 compatibility module to use that function.

**Comment by tarrade** [comment]
ok, for 'optimizer.minimize(loss, tf.compat.v1.train.get_or_create_global_step())'
but even using 'optimizer.minimize(loss,var_list=model.weights)' which is more native for TF 2.0 and doesn't use 'tf.train.get_or_create_global_step' it crashing so the issue is somewhere else I guess. Thanks for the follow up.

**Comment by ymodak** [comment]
Okay. I will close this issue for now. You can reopen when additional information is available or can file a new issue if it's not a related error. Thanks!

**Comment by wangmorgan** [comment]
opt = tf.optimizers.Adam(learning_rate=0.02, beta_1=0.99, epsilon=1e-1)
TypeError: 'NoneType' object is not callable

**Comment by wangmorgan** [comment]
opt = tf.optimizers.Adam(learning_rate=0.02, beta_1=0.99, epsilon=1e-1)
TypeError: 'NoneType' object is not callable

**Comment by fireingthehole** [comment]
train_step=tf.keras.optimizers.SGD(rate).minimize(loss,var_list=tf.compat.v1.trainable_variables())
TypeError: 'Tensor' object is not callable
the same error.

**Comment by nitinmnsn** [comment]
I ran into the same error. For me the issue was that the loss has to be a callable that takes no inputs and returns the loss but, i was feeding the actual loss. Hope this helps someone

**Comment by whitish** [comment]
Same issue:
`
    weights = K.variable(np.ones(5), dtype='float64')
    chosen_action = K.argmax(weights, 0)

    # inputs
    reward = Input(shape=(1,), dtype='float64')

    # current bandit's weight
    resp_weight = K.gather(weights, chosen_action)

    loss = K.log(resp_weight) * reward
    optimizer = SGD(learning_rate = 0.001).minimize(loss, var_list=[weights])
`

`TypeError: 'Tensor' object is not callable`

**Comment by nitinmnsn** [comment]
@whitish - your loss has to be a callable that takes no inputs and returns the loss

**Comment by ggproRIC** [comment]
def stochastic_gradient_descent(X, y_true, epochs, learning_rate = 0.01):
 
    number_of_features = X.shape[1]
    # numpy array with 1 row and columns equal to number of features. In 
    # our case number_of_features = 3 (area, bedroom and age)
    w = np.ones(shape=(number_of_features)) 
    b = 0
    total_samples = X.shape[0]
    
    price_list = []
    epoch_list = []
    
    for i in range(epochs):    
        random_index = random.randint(0,total_samples-1) # random index from total samples
        sample_x = X[random_index]
        sample_y = y_true[random_index]
        
        y_predicted = np.dot(w, sample_x.T) + b
    
        w_grad = -(2/total_samples)*(sample_x.T.dot(sample_y-y_predicted))
        b_grad = -(2/total_samples)*(sample_y-y_predicted)
        
        w = w - learning_rate * w_grad
        b = b - learning_rate * b_grad
        
        price = np.square(sample_y-y_predicted)
        
        if i%100==0: # at every 100th iteration record the price and epoch value
            price_list.append(price)
            epoch_list.append(i)
        
    return w, b, price, price_list, epoch_list
w_sgd, b_sgd, price_sgd, price_list_sgd, epoch_list_sgd = SGD(scaled_X,scaled_y.reshape(scaled_y.shape[0],),10000)
w_sgd, b_sgd, price_sgd
TypeError                                 Traceback (most recent call last)
<ipython-input-56-7d0451465b94> in <module>
----> 1 w_sgd, b_sgd, price_sgd, price_list_sgd, epoch_list_sgd = SGD (scaled_X,scaled_y.reshape(scaled_y.shape[0],),10000)
      2 w_sgd, b_sgd, price_sgd

TypeError: 'SGD' object is not callable
