### ISSUE TITLE
make tflite test error.

### ISSUE THREAD

**Issue by licunhao** [tensorflow/tensorflow#28061]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):Ubuntu 16.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):source
- TensorFlow version:lastest
- Python version:2.7
- Installed using virtualenv? pip? conda?:pip
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):7.3.0
- CUDA/cuDNN version:
- GPU model and memory:

**Describe the problem**
make tflite test target
then error occurs.

**Provide the exact sequence of commands / steps that you executed before running into the problem**
make -f tensorflow/lite/experimental/micro/tools/make/Makefile test 

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.
- In file included from tensorflow/lite/experimental/micro/kernels/depthwise_conv.cc:18:0:
- ./tensorflow/lite/kernels/internal/common.h:48:10: fatal error: fixedpoint/fixedpoint.h: No such file or directory
-  #include "fixedpoint/fixedpoint.h"

**Comment by licunhao** [comment]
I can not find the code about fixedpoint.h at the code tree in repository.

**Comment by Dayananda-V** [comment]
Make sure compile binary source with latest gemmlowp pakage, make sure gemmlowp this package is exist in build.

**Comment by licunhao** [comment]
@Dayananda-V  
Thank you for reply.
I will try it.

**Comment by licunhao** [comment]
@Dayananda-V 
I did what you suggest.
It works well.
Thank you. Now I close the issue.
