### ISSUE TITLE
unify keras.optimizer and tf.train.Optimizer behavior

### ISSUE THREAD

**Issue by zh794390558** [tensorflow/tensorflow#28064]
when I using tf.train.Adam to replace kearas.optimizer.Adam the fit method rasize error about global_step not exits.

**Comment by muddham** [comment]
@zh794390558 In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thanks!

**Comment by muddham** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
