### ISSUE TITLE
Building TF with custom GCC requires hardcoded ld,nm and as

### ISSUE THREAD

**Issue by akors** [tensorflow/tensorflow#2806]
Hi! I am using Fedora 23 to build TensorFlow with GPU support.

GPU support requires a specific GCC version, 4.9 for successful compilation. Since this version is not available from the Fedora Package repositories, it has to be compiled from source. Unfortunately, there are a few obstacles using this version with bazel.

One of those is the following:
After configuring TensorFlow with the self-compiled GCC, and running bazel, the compilation stops with the following message:

`gcc: error trying to exec 'as': execvp: No such file or directory`
or
`gcc: error trying to exec 'nm': execvp: No such file or directory`
or
`gcc: error trying to exec 'ld': execvp: No such file or directory`

To work around this, one can compile GCC by hardcoding the paths to those tools, by adding this to the configuration line of GCC:
`--with-ld=/bin/ld --with-nm=/bin/nm --with-as=/usr/bin/as`

This does seem rather strange, however, because those programs are on the path, and the custom GCC without bazel is capable of producing working binaries just fine. I feel that in a well-working build system, this kind of hacks should not be necessary.

This is probably a bazel bug, but since I am compiling TensorFlow with it and I cannot be sure that it's not a TF issue, I am creating this here.
Please ping bazel devs as required.

**Comment by akors** [comment]
@davidzchen

It seems that you have taken to fixing TF builds with a custom compiler? If so, than you might also be interested in this oddity. Thanks for your work!

**Comment by martinwicke** [comment]
I believe this is indeed a bazel problem. I wouldn't know what we can do inside TensorFlow to address this. I would file an issue for bazel.

**Comment by akors** [comment]
I created Issue https://github.com/bazelbuild/bazel/issues/1713 in bazel for this.

**Comment by KeyKy** [comment]
I have got the same problem gcc: error trying to exec 'as': execvp: No such file or directory.
and I solved it by copy and paste the /usr/bin/as to the same folder as gcc 5.3(/usr/local/bin/gcc)
