### ISSUE TITLE
[TF2.0] SavedModel can't save output layer with multiple outputs

### ISSUE THREAD

**Issue by zzh8829** [tensorflow/tensorflow#28066]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): mac
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.0.0-alpha0
- Python version: 3.7

**Describe the current behavior**
`tf.saved_model.save` does not work on keras model when the output layer produce multiple outputs.

**Describe the expected behavior**
SavedModel should produce same outputs as the original model.

**Code to reproduce the issue**
```
import tensorflow as tf
from tensorflow.keras.layers import Input, Lambda

class TwoOutputs(tf.keras.layers.Layer):
    def call(self, x):
        return x + 1, x - 1

inputs = Input([2], dtype=tf.int32)
outputs = TwoOutputs()(inputs)  # subclass version is broken
# outputs = Lambda(lambda x: (x + 1, x - 1))(inputs)  # functional version also broken
model = tf.keras.Model(inputs, outputs)

print(model(tf.constant([[0, 1], [2, 3]])))  # works fine

tf.saved_model.save(model, 'checkpoints/test')
model = tf.saved_model.load('checkpoints/test')
infer = model.signatures[tf.saved_model.DEFAULT_SERVING_SIGNATURE_DEF_KEY]
print(infer.structured_outputs)  # wrong signatures
print(infer(tf.constant([[0, 1], [2, 3]])))  # wrong output

```
**Other info / logs**
The automatically generated saved_model signature relies on the name of outputs.
Keras model generates `model.output_names` here 
https://github.com/tensorflow/tensorflow/blob/f0fba04cd274e7ffa24ab8e49f888ef6974e6f7a/tensorflow/python/keras/engine/network.py#L329
For outputs layers with multiple outputs, all outputs will have the same name!
When creating saved_model, tensorflow uses the following _wrapped_model function to generate the ConcreteFunction signature
https://github.com/tensorflow/tensorflow/blob/f0fba04cd274e7ffa24ab8e49f888ef6974e6f7a/tensorflow/python/keras/saving/saving_utils.py#L108

In our case the model has `outputs` [x1, x2] with `output_names` [layer, layer].
the _wrapped_model function produces signature `{layer: x2}` which is wrong!! 
x1 gets dropped from the output of saved model.

**Comment by allenlavoie** [comment]
Thank you for the great bug report! Should be fixed in https://github.com/tensorflow/tensorflow/commit/d7cd03f1398cd33fc8579ce336b602350ac99259
