### ISSUE TITLE
deprecation warning in confusion_matrix.py 

### ISSUE THREAD

**Issue by mayankmetha** [tensorflow/tensorflow#28076]
This template is for miscellaneous issues not covered by the other issue categories.

For questions on how to work with TensorFlow, or support for problems that are not verified bugs in TensorFlow, please go to [StackOverflow](https://stackoverflow.com/questions/tagged/tensorflow).

If you are reporting a vulnerability, please use the [dedicated reporting process](https://github.com/tensorflow/tensorflow/blob/master/SECURITY.md).

For high-level discussions about TensorFlow, please post to discuss@tensorflow.org, for questions about the development or internal workings of TensorFlow, or if you would like to know how to contribute to TensorFlow, please post to developers@tensorflow.org.

OS: Ubuntu 18.04.2
Tensorflow-gpu: 2.0.0alpha0

WARNING: Logging before flag parsing goes to stderr.
W0423 15:59:53.297839 140450503571264 deprecation.py:323] From <path>/python3.6/site-packages/tensorflow/python/ops/confusion_matrix.py:194: to_int64 (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.cast` instead.
W0423 15:59:53.298299 140450503571264 deprecation.py:323] From <path>/python3.6/site-packages/tensorflow/python/ops/confusion_matrix.py:195: to_int32 (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.cast` instead.

**Comment by mihaimaruseac** [comment]
These have been fixed on master, next update of alpha/tf2.0 will have them fixed. Thank you for notifying us about them
