### ISSUE TITLE
TF2.0.0-alpha0  'Tensor' object has no attribute 'numpy'

### ISSUE THREAD

**Issue by happiness-ai** [tensorflow/tensorflow#28075]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):colab
- TensorFlow installed from (source or binary):binary
- TensorFlow version (use command below):2.0.0-alpha0
- Python version:3.6

'Tensor' object has no attribute 'numpy' when use tf.data 

ds_train = tf.data.Dataset.from_tensor_slices((train_x_paths,train_y_labels))
def readFile(path,label):
  return tf.io.read_file(path).numpy(),label

ds_train.map(readFile)

AttributeError                            Traceback (most recent call last)
<ipython-input-94-7fc15313765a> in <module>()
----> 1 ds_train.map(readFile)

10 frames
<ipython-input-92-a8cf88784b63> in readFile(path, label)
      1 def readFile(path,label):
----> 2   return tf.io.read_file(path).numpy(),label
      3 

AttributeError: 'Tensor' object has no attribute 'numpy'

**Comment by Carmezim** [comment]
@happiness-ai Do you have eager execution enabled?

**Comment by happiness-ai** [comment]
@Carmezim TF2.0.0-alpha0

**Comment by gadagashwini** [comment]
This question is better asked on StackOverflw. Since it is not a bug or feature request. There is also a larger community that reads questions there. Thanks!

**Comment by Carmezim** [comment]
@gadagashwini should the issue be closed then?

**Comment by jinfagang** [comment]
@CarbonComputed @Carmezim Same issue. Since already tf2.0, why do say open eager execution? Does not it already support eager execution?

**Comment by Johnny65456** [comment]
Do you solve it? I have the same problem with eager execution already enabled.
