### ISSUE TITLE
TensorFlow 2.0: Allow simple tensorboard summary usage

### ISSUE THREAD

**Issue by andreas-eberle** [tensorflow/tensorflow#28073]
**System information**
- TensorFlow version (you are using): 2.0 alpha 0
- Are you willing to contribute it (Yes/No): willing yes, but I don't have enough experience with the TF internals.

**Describe the feature and the current behavior/state.**
As to my current research and a [stackoverflow question on writing image summaries](https://stackoverflow.com/questions/55421290/tensorflow-2-0-keras-how-to-write-image-summaries-for-tensorboard), I think there is no user friendly way of writing arbitrary summaries from a TensorFlow 2.0 Keras model.

In more complex models, a developer might want to write scalars, histograms or simply images generated from tensors which are created in the middle of the network. With tf.layers and estimators, I could easily take such a tensor and write it to TensorBoard with tf.summary. At the moment there does not seem to be an equally easily usable way to do this with the Keras API.

From the user perspective, I imagine a special TensorBoard logging layer, that can be chained into the model. This layer would then handle creating the summary writer and getting/maintaining the current model step. 
E.g. when using `Sequential`, it could look like:
```
model = keras.models.Sequential([
	keras.layers.Flatten(input_shape=(28, 28), name="flatten"),
	keras.layers.Dense(128, activation='relu', name="dense1"),
	TensorBoardLoggingLayer("my-logging-dir", lambda input: tf.summary.scalar("first-value", input[0]))
	keras.layers.Dense(10, activation='softmax', name="dense2")
])
```

Furthermore, if the user creates a custom layer they could extend from this `TensorBoardLoggingLayer` and use its handling of the summary writer to easily write summaries of internal parts of their layer.

**Will this change the current api? How?**
It would add a new layer but not effect other, existing API.

**Who will benefit with this feature?**
Everybody that wants to debug a model or get more insights into it. This is especially important when you create custom layers (e.g. implementing new stuff from/for papers) or if you want to debug e.g. images of inner results of your network.

**Any Other info.**
I think it is crucial to have an easy to use possibility to debug and track our networks with TensorFlow. This was/is possible with the tf.layers / tf.estimtators APIs. In my view it is a must to have this in the TF 2.0 ecosystem.

**Comment by wookayin** [comment]
You can use `tf.keras.layers.Lambda` to inject arbitrary expressions as a Layer, and collect all the created summaries.

**Comment by andreas-eberle** [comment]
Not really, how would I get the current step of the model. I need the step to be able to write a summary. My point is that there should be a layer handling the step and summary writer for me, so not everybody has to do it on their own.

**Comment by karmel** [comment]
This feature is being worked on, but is currently blocked on some functionality from TensorBoard. @omalleyt12 will update the thread when we have made progress here.

**Comment by sahilpasricja** [comment]
> You can use `tf.keras.layers.Lambda` to inject arbitrary expressions as a Layer, and collect all the created summaries.

I was using tensor board conv model with tf.layers , now when I switch to tf.keras and try publishing weights to logs using summary, I am left with 2 options and both have issues 

1)Use call back to store weights - It's working upto storing weights but it has no provision of mentioning plugin name in it ( like my old model). Without plugin name, I can not identify data to be presented by mu custom plugin on tensorboard 
2) Use callback (on_test_batch_end) to call my summary method, with this I can get a chance to store my  plugin name but when  i try storing the data from summary in logs it gives an error 

'Tensor' object has no attribute 'value'

Do we have any way to store weights using callback and also store with them the plugin name ?

**Comment by Saduf2019** [comment]
@andreas-eberle 

    Please post this issue on [keras-team/keras repo.](https://github.com/keras-team/keras/issues)
    To know more see;
    https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999
