### ISSUE TITLE
Windows Build working with cuda 10.1 and vs2019

### ISSUE THREAD

**Issue by atemysemicolon** [tensorflow/tensorflow#28086]
I am only writing this as an issue as I got tensorflow with win 10 building with cuda 10.1 and vs2019 .
I am not sure if my changes can be general, they seem to work for me and I can train MNIST on GPU. The cuda changes could be relevant, the others might be working only for my system config. 

<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): source
- TensorFlow version: 2.0a
- Python version: 3.6.5
- Installed using virtualenv? pip? conda?: pip
- Bazel version (if compiling from source): 20
- GCC/Compiler version (if compiling from source): visual studo 2019
- CUDA/cuDNN version: 10.1/7
- GPU model and memory: gtx 1080 ti , 4gv

**Describe the problem**
Cannot compile tensorflow 2.0 alpha on windows with cuda 10.1, and visual studio 2019

**Provide the exact sequence of commands / steps that you executed before running into the problem**
- Hardlinked visual studio 2019 as 2017 with `mklink`
- modified bazel scripts and stream operators as in : https://github.com/atemysemicolon/tensorflow/commit/54faf06d5c10e8875b9ce36b941004aceb44c8b9 
- Compiles

**Any other info / logs**
- Visual 2019 does not seem to be supported by older versions of Bazel. Bazel 24.1 causes compilation issues using nvcc. However, cheating bazel into thinking 2019 is 2017 is good enough - by hardlinking the 2019 folder to 2017 in C:\Program Files\Microsoft Visual Studio\..
- I had to modify bazel to not generate workspaces for mac and linux,
- _The most important one seems to be the modification in `cuda_10_0.inc `in `tensorflow/stream_executer/cuda/...`_

**Comment by achandraa** [comment]
TensorFlow supports CUDA 10.0 (TensorFlow >= 1.13.0). Please refer this [link](https://www.tensorflow.org/install/gpu#software_requirements) and let us know in case of any clarification. Thanks!

**Comment by atemysemicolon** [comment]
This guide is for 10.1 , not 10

**Comment by achandraa** [comment]
Unfortunately, none of the TensorFlow versions officially support CUDA 10.1. As of now we have to build TensorFlow version>=1.13.0 using CUDA 10.0. Thanks!

**Comment by achandraa** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Comment by atemysemicolon** [comment]
I thought only when someone builds it , it could be officially supported xd
