### ISSUE TITLE
Porting Tensorflow-Lite to Google TEE OS(Trusty OS)

### ISSUE THREAD

**Issue by sunzc** [tensorflow/tensorflow#28088]
I'm trying to port Tensorflow-Lite to Google TEE OS(Trusty OS) which runs in Secure World on mobile devices with ARM TrustZone support. 

Inspired by [Tensorflow-Lite for Micro-controller](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/experimental/micro), I start from a [Portable Reference Code](https://drive.google.com/open?id=1cawEQAkqquK_SO4crReDYqf_v7yAwOY8), which doesn't require any standard C or C++ libraries. However, when I try to port it to [Trusty repo](https://android.googlesource.com/trusty/manifest). I get compiling errors, because the trusty prebuilt toolchain doesn't have c++ headers, while  the Tensorflow-lite's flatbuffer library relies on c++ headers. 

I tried to manually copy c/c++ header files from 

`tensorflow/tensorflow/lite/experimental/micro/tools/make/downloads/gcc_embedded/arm-none-eabi/include/`  

to  `trusty/trusty/user/app/recognize_commands_test/third_party/include`

and add proper code in corresponding Makefile 

`trusty/trusty/user/app/recognize_commands_test/rules.mk`

However, there are some redefine errors due to micros defined in both trusty os c header files 

`external/lk/include/shared/lk/compiler.h` 

and the copied c/c++ headers `include/sys/cdefs.h` .

I also tried to only add c++ headers, instead of c/c++ headers, but no-definition errors pop up, like cstdio use a lot of functions defined in stdio.h like "fprintf, rename, fsetpos, putc" which are defined in c header files, at the same time, the trusty os 's prebuilt compiler already has a set of c header files defined in the toolchain's include directory. 

Any idea in porting tensorflow-lite to Trusty OS? or specific advice in solving the lack of C++ header files problem?

I know this type of problems is more related to adding c++ support for Trusty OS, but as far as I know, there's no discussing forum or active github repo for Google Trusty OS development. If you know any, please let me know. Great thanks!

**Comment by muddham** [comment]
@sunzc This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.If you think we've misinterpreted a bug, please comment again with a clear explanation, as well as all of the information requested in the [issue template](https://github.com/tensorflow/tensorflow/issues/new/choose). Thanks!

**Comment by sunzc** [comment]
> @sunzc This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.If you think we've misinterpreted a bug, please comment again with a clear explanation, as well as all of the information requested in the [issue template](https://github.com/tensorflow/tensorflow/issues/new/choose). Thanks!

Agree, thank you!
