### ISSUE TITLE
Installation issue on the Raspberry Pi

### ISSUE THREAD

**Issue by aallan** [tensorflow/tensorflow#28082]
**System information**

- OS Platform and Distribution: Raspberry Pi 3+ with Raspbian 2019-04-08 release
- TensorFlow installed from (source or binary): binary
- TensorFlow version: tensorflow-1.13.1
- Python version: Python 3.5.3
- Installed using: pip

**Describe the problem**

Installing TensorFlow on the Raspberry Pi with a clean build of the latest version of Raspbian,

```
sudo apt install libatlas-base-dev
sudo apt-get install python3-pip
pip3 install tensorflow
```

and then importing it into `python3` environment generates the following error

```
$ python3
Python 3.5.3 (default, Sep 27 2018, 17:25:39) 
[GCC 6.3.0 20170516] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
/usr/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: compiletime version 3.4 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.5
  return f(*args, **kwds)
/usr/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: builtins.type size changed, may indicate binary incompatibility. Expected 432, got 412
  return f(*args, **kwds)
>>> 
```

Presumably the binary build of TensorFlow is expecting Python 3.4 here? There seems to be other people complaining about this, but I can't find a solution. Anyone?

A full log of the installation is available: [installation.log](https://github.com/tensorflow/tensorflow/files/3108312/installation.log)

**Comment by bennuttall** [comment]
Those are warnings, not errors. The wheels were built with Python 3.4 but are compatible with newer Python versions. It works just fine!
