### ISSUE TITLE
Fatal error in build from source

### ISSUE THREAD

**Issue by daviduarte** [tensorflow/tensorflow#28087]
**### System information**
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 18.04
- **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device**: No
- **TensorFlow installed from (source or binary)**: Source
- **TensorFlow version (use command below)**: 1.12.2
- **Python version**: 3.6
- **Bazel version (if compiling from source)**: 0.15
- **GCC/Compiler version (if compiling from source)**: 4.8
- **CUDA/cuDNN version**: 9.0 / 7.1.4
- **GPU model and memory**: GTX 760
- **Exact command to reproduce**:

**### Describe the problem**
I'm trying build tensorflow from source as [these instructions](https://www.tensorflow.org/install/source#configuration_options). I used the software versions as above (following the [Tested build configurations](https://www.tensorflow.org/install/source#configuration_options)). After few seconds, a fatal error arives: 

```
ERROR: /home/daviduarte/.cache/bazel/_bazel_daviduarte/a8562d3526d775d3816a038c038b230e/external/com_googlesource_code_re2/BUILD:26:1: C++ compilation of rule '@com_googlesource_code_re2//:re2' failed (Exit 1)
In file included from /usr/include/c++/4.8/memory:81:0,
                 from external/com_googlesource_code_re2/util/sparse_array.h:107,
                 from external/com_googlesource_code_re2/re2/re2.cc:27:
/usr/include/c++/4.8/bits/unique_ptr.h: In instantiation of 'struct std::default_delete<int []>':
/usr/include/c++/4.8/bits/unique_ptr.h:288:33:   required by substitution of 'template<class _Up> static typename _Up::pointer std::unique_ptr<_Tp [], _Dp>::_Pointer::__test(typename _Up::pointer*) [with _Up = _Up; _Tp = int; _Dp = std::default_delete<int []>] [with _Up = std::default_delete<int []>]'
/usr/include/c++/4.8/bits/unique_ptr.h:296:25:   required from 'class std::unique_ptr<int []>::_Pointer'
/usr/include/c++/4.8/bits/unique_ptr.h:299:57:   required from 'class std::unique_ptr<int []>'
external/com_googlesource_code_re2/util/sparse_array.h:334:26:   required from here
/usr/include/c++/4.8/bits/unique_ptr.h:79:51: internal compiler error: Segmentation fault
  using __remove_cv = typename remove_cv<_Up>::type;
                                                   ^
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-4.8/README.Bugs> for instructions.
The bug is not reproducible, so it is likely a hardware or OS problem.
Target //tensorflow/tools/pip_package:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 66.791s, Critical Path: 11.38s
INFO: 300 processes: 300 local.
FAILED: Build did NOT complete successfully

```

If I simple try again, typing:
> bazel clean
> ./configure
> enter the exacly configuration above

another DIFFERENT error appears:

```
ERROR: /home/daviduarte/.cache/bazel/_bazel_daviduarte/a8562d3526d775d3816a038c038b230e/external/grpc/BUILD:388:1: C++ compilation of rule '@grpc//:grpc_plugin_support' failed (Exit 1)
external/grpc/src/compiler/node_generator.cc: In member function 'google::protobuf::Arena* google::protobuf::FileDescriptorProto::GetArenaNoVirtual() const':
external/grpc/src/compiler/node_generator.cc:278:1: internal compiler error: Segmentation fault
 }  // namespace grpc_node_generator
 ^
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-4.8/README.Bugs> for instructions.
The bug is not reproducible, so it is likely a hardware or OS problem.
Target //tensorflow/tools/pip_package:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 52.049s, Critical Path: 11.22s
INFO: 152 processes: 152 local.
FAILED: Build did NOT complete successfully
```

I tried several times with others tensorflow version (always respecting the Tested build configurations). Each try gives a different fatal error. Sometimes with Segmentation fault. 

With GCC 6 I stay several minutes in the compilation process, them suddenly a fatal error with a segmentation fault appears. 

**### Source code / logs**
Here is the complete log of my last try: 
[erro.txt](https://github.com/tensorflow/tensorflow/files/3109326/erro.txt)

And here is the my build configuration typed in ./configure:
[build_config.txt](https://github.com/tensorflow/tensorflow/files/3109328/build_config.txt)

**Comment by wdirons** [comment]
I don't see the bazel build command line you used. Did you follow this tip from the instructions:

> Building TensorFlow from source can use a lot of RAM. If your system is memory-constrained, limit Bazel's RAM usage with: --local_resources 2048,.5,1.0.

running out of memory causes random failures in the build.

**Comment by daviduarte** [comment]
I'm using a computer with 32GB and I keep up with the memory in my attempts, and always the memory usage was relatively low. But anyway I used the command. I also ventured change the compiler used, from GCC 4.8 to GCC 6. Then, my bazel compile command looks like: 

> bazel build --config=opt --config=cuda --local_resources 20480,.5,1.0 --cxxopt="-D_GLIBCXX_USE_CXX11_ABI=0" //tensorflow/tools/pip_package:build_pip_package

The add the two new flags: 
> -local_resources 20480,.5,1.0 (as recommended)
> --cxxopt="-D_GLIBCXX_USE_CXX11_ABI=0" (For GCC 5 and later)

After some seconds, a new error appears:
```
ERROR: /home/daviduarte/.cache/bazel/_bazel_daviduarte/a8562d3526d775d3816a038c038b230e/external/protobuf_archive/BUILD:105:1: C++ compilation of rule '@protobuf_archive//:protobuf' failed (Exit 1)
external/protobuf_archive/src/google/protobuf/descriptor.cc:7319:1: internal compiler error: Segmentation fault
 }  // namespace google
 ^
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-6/README.Bugs> for instructions.
Target //tensorflow/tools/pip_package:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 129.343s, Critical Path: 15.03s
INFO: 124 processes: 124 local.
FAILED: Build did NOT complete successfully
```

**Comment by daviduarte** [comment]
I compiled in other identical computer, and for my surprise, the TF was compiled like a charm.

**Comment by gunan** [comment]
Looks like both of these ran into internal GCC bugs:
```
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-6/README.Bugs> for instructions.
Target //tensorflow/tools/pip_package:build_pip_package failed to build
```
As we have not seen these issues ourselves, I do not think we can help much.
You can try reaching out to gcc community for help.

**Comment by ArmageddonKnight** [comment]
I encountered the same issue when compiling the core library using g++. May I know whether there is any solution to this problem?

**Comment by 1e100** [comment]
@ArmageddonKnight try using fewer threads when building. E.g. if your CPU has 64 hyperthreads like mine try `--jobs=16` or `--jobs=32`. My CPU is Threadripper 3070 by the way. Compiler is GCC8, and OS is Ubuntu 20.04. I get segfault when compiling without the `--jobs` flag, and don't get the segfault when I reduce the number of parallel tasks. Could be that something overheats or draws too much power for the motherboard to handle. It's definitely not the lack of RAM in my case as I have 128GB.

**Comment by ArmageddonKnight** [comment]
@1e100 Thanks for your reply. I have tried using the command `make -j 1` (not in the TensorFlow project but some other large codebase using the `make` build system) but this error still randomly occurs. I definitely agree that this might not be caused by lack of RAM.

**Comment by 1e100** [comment]
@ArmageddonKnight try running prime95 in torture mode on your system. If it fails, it's a stability issue with the system.
