### ISSUE TITLE
use the tf.train.Checkpoint ,  optimizer Adam  is not the Ttrackable object???

### ISSUE THREAD

**Issue by hacker-lin** [tensorflow/tensorflow#28080]
my  TF Version is  2.0.0-alpha0

https://www.tensorflow.org/alpha/tutorials/text/nmt_with_attention#checkpoints_object-based_saving
above the link. and the  auchor
I learn the  document tutorials 
and use the code :
checkpoint = tf.train.Checkpoint(optimizer=optimizer,
                                 encoder=encoder,
                                 decoder=decoder)

cause the error :
ValueError: `Checkpoint` was expecting a trackable object (an object derived from `TrackableBase`), got <tensorflow.python.keras.optimizers.Adam object at 0x000002A561A5F400>. If you believe this object should be trackable (i.e. it is part of the TensorFlow Python API and manages state), please open an issue.

**Comment by allenlavoie** [comment]
That sounds like you're getting the v1 API. There is a trackable tf.train.AdamOptimizer in v1, but the v1 Keras optimizers are not trackable.

In v2 you should see a `<class 'tensorflow.python.keras.optimizer_v2.adam.Adam'>` (note the optimizer_v2) and it will also be trackable. You can use `tf.compat.v2.keras.optimizers.Adam` to make sure you're getting it.

**Comment by hacker-lin** [comment]
> That sounds like you're getting the v1 API. There is a trackable tf.train.AdamOptimizer in v1, but the v1 Keras optimizers are not trackable.
> 
> In v2 you should see a `<class 'tensorflow.python.keras.optimizer_v2.adam.Adam'>` (note the optimizer_v2) and it will also be trackable. You can use `tf.compat.v2.keras.optimizers.Adam` to make sure you're getting it.

emm,    i use pycharm,  so  i have to  use this met import 
"from tensorflow.python import keras"    (in  console can use  "from tensorflow import keras)
I  change  the linue    from 
     " optimizer = keras.optimizers.Adam()"  
     to 
    " optimizer = tf.optimizers.Adam() "                          
and  only this ,  it works

**Comment by allenlavoie** [comment]
Oh neat, didn't realize we had the tf.optimizers alias. Yes, that's the v2 version.
