### ISSUE TITLE
DLL load failed: The specified procedure could not be found.

### ISSUE THREAD

**Issue by Dudemanword** [tensorflow/tensorflow#28095]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10 64 bit
- TensorFlow installed from (source or binary): binary
- TensorFlow version: Latest version as of 4/23/2019 (Cannot check, Can't import tensorflow to check version)
- Python version: 3.7
- Installed using virtualenv? pip? conda?: pip
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

**Describe the problem**

When attempting to load tensorflow:

```import tensorflow as tf```

The following error gets thrown:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "XXXXXXXXXX\venv\lib\site-packages\tensorflow\__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "XXXXXXXXXX\venv\lib\site-packages\tensorflow\python\__init__.py", line 52, in <module>
    from tensorflow.core.framework.graph_pb2 import *
  File "XXXXXXXXXX\venv\lib\site-packages\tensorflow\core\framework\graph_pb2.py", line 6, in <module>
    from google.protobuf import descriptor as _descriptor
  File "XXXXXXXXXX\venv\lib\site-packages\google\protobuf\descriptor.py", line 47, in <module>
    from google.protobuf.pyext import _message
ImportError: DLL load failed: The specified procedure could not be found.

**Provide the exact sequence of commands / steps that you executed before running into the problem**
All commands are being run as part of the powershell terminal provided in vscode

I created a virtual environment:
```virtualenv --system-site-packages -p python3 ./venv```

Started the virtual environment:
```.\venv\Scripts\activate```

Installed tensorflow;

```pip install tensorflow```

Attempted to check if the installation was a success:

```python```

Then:

```import tensorflow as tf```

The error gets thrown when inputting the above command

**Any other info / logs**
I am using VS code as my editor of choice. I am using the powershell terminal in VS Code. I attempted to downgrade my python version to 3.6. That did not work. I later tried to downgrade my protobuf version from 3.6.1 to 3.6.0 but I was informed that the current version of tensorflow only works with 3.6,1, I'm not sure what's going on

**Comment by achandraa** [comment]
@Dudemanword : Please have a look on #25072 and let us know if that helps. Thanks!

**Comment by Dudemanword** [comment]
This worked for me

**Comment by Dudemanword** [comment]
@achandraa Downgrading protobuf to 3.6.0 worked for me. Thank you

**Comment by achandraa** [comment]
Great to know that it worked for you. I am closing this issue since it is resolved.Thanks!
