### ISSUE TITLE
Runtime crash due to build time configuration inconsistency/bug (CUDA 10.1)

### ISSUE THREAD

**Issue by kgizdov** [tensorflow/tensorflow#28093]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Arch Linux x86_64
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): source
- TensorFlow version: 1.13.1 (equivalently affects 2.0.0-alpha0)
- Python version: 3.7.3
- Installed using virtualenv? pip? conda?: native system install
- Bazel version (if compiling from source): 0.22.0
- GCC/Compiler version (if compiling from source): GCC 8.3.0
- CUDA/cuDNN version: 10.1
- GPU model and memory: any

**Describe the problem**
At configuration time, TensorFlow checks if given CUDA version is indeed available by inspecting SONAMEs of libs. Then it links to the closest version available on the system. At runtime, however, it has stored the plain version number as a string (in `stream_executor/dso_loader.cc`), given to it at configuration time, and tries to load those libraries exactly instead -  not the ones it actually build/linked against. Normally, this will not be such a problem, however, it is inconsistent and in the case of CUDA 10.1, of course, results in a crash. CUDA 10.1 libraries ship as filenames `lib*.so.10.1.0.105`, but some are labelled with `SONAME lib*.so.10.1` and others are labelled `SONAME lib*.so.10`. This results in either a build error or runtime error depending on how tensorflow was configured, but in any case, it prevents TensorFlow from working.

**Provide the exact sequence of commands / steps that you executed before running into the problem**
```bash
$ ./build.sh
  export PYTHON_BIN_PATH=/usr/bin/python
  export USE_DEFAULT_PYTHON_LIB_PATH=1
  export TF_NEED_JEMALLOC=1
  export TF_NEED_KAFKA=0
  export TF_NEED_OPENCL_SYCL=0
  export TF_NEED_AWS=0
  export TF_NEED_GCP=0
  export TF_NEED_HDFS=0
  export TF_NEED_S3=0
  export TF_ENABLE_XLA=1
  export TF_NEED_GDR=0
  export TF_NEED_VERBS=0
  export TF_NEED_OPENCL=0
  export TF_NEED_MPI=0
  export TF_NEED_TENSORRT=0
  export TF_NEED_NGRAPH=0
  export TF_NEED_IGNITE=0
  export TF_NEED_ROCM=0
  export TF_SET_ANDROID_WORKSPACE=0
  export TF_DOWNLOAD_CLANG=0
  export TF_NCCL_VERSION=2.4
  export NCCL_INSTALL_PATH=/usr
  export TF_IGNORE_MAX_BAZEL_VERSION=1
  export CC_OPT_FLAGS="-march=haswell"
  export TF_NEED_CUDA=1
  export GCC_HOST_COMPILER_PATH=/usr/bin/gcc
  export HOST_CXX_COMPILER_PATH=/usr/bin/gcc
  export TF_CUDA_CLANG=0
  export CUDA_TOOLKIT_PATH=/opt/cuda
  export TF_CUDA_VERSION=10.1
  export CUDNN_INSTALL_PATH=/usr/lib
  export TF_CUDNN_VERSION=7
  export TF_CUDA_COMPUTE_CAPABILITIES=3.5,3.7,5.0,5.2,5.3,6.0,6.1,6.2,7.0,7.2,7.5
  ./configure
  bazel \
    build --config=opt \
      //tensorflow:libtensorflow.so \
      //tensorflow:libtensorflow_cc.so \
      //tensorflow:install_headers \
      //tensorflow/tools/pip_package:build_pip_package
  bazel-bin/tensorflow/tools/pip_package/build_pip_package "${srcdir}"/tmpcudaopt
```
```
# BUILD ERROR:
ERROR: Skipping '//tensorflow/tools/pip_package:build_pip_package': error loading package 'tensorflow/tools/pip_package': in /build/tensorflow/tensorflow/tensorflow.bzl: Encountered error while reading extension file 'cuda/build_defs.bzl': no such package '@local_config_cuda//cuda': Traceback (most recent call last):
	File "/build/tensorflow/third_party/gpus/cuda_configure.bzl", line 1502
		_create_local_cuda_repository(repository_ctx)
	File "/build/tensorflow/third_party/gpus/cuda_configure.bzl", line 1266, in _create_local_cuda_repository
		_find_libs(repository_ctx, cuda_config)
	File "/build/tensorflow/third_party/gpus/cuda_configure.bzl", line 859, in _find_libs
		_find_cuda_lib("cublas", repository_ctx, cpu_value, c..., ...)
	File "/build/tensorflow/third_party/gpus/cuda_configure.bzl", line 773, in _find_cuda_lib
		find_lib(repository_ctx, [("%s/%s%s" % (bas...], ...)))
	File "/build/tensorflow/third_party/gpus/cuda_configure.bzl", line 747, in find_lib
		auto_configure_fail(("None of the libraries match th...)))
	File "/build/tensorflow/third_party/gpus/cuda_configure.bzl", line 341, in auto_configure_fail
		fail(("\n%sCuda Configuration Error:%...)))

Cuda Configuration Error: None of the libraries match their SONAME: /opt/cuda/lib64/libcublas.so.10.1
```
```python
# $ ./tensorflow_test.py
#!/usr/bin/env python

import tensorflow as tf
mnist = tf.keras.datasets.mnist

(x_train, y_train),(x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(512, activation=tf.nn.relu),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10, activation=tf.nn.softmax)
])
model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

model.fit(x_train, y_train, epochs=5)
val = model.evaluate(x_test, y_test)
print('Result is:\n{}'.format(val[0]))
print('Success!')
```
```
# RUNTIME ERROR:
2019-04-23 23:51:16.393767: I tensorflow/stream_executor/dso_loader.cc:142] Couldn't open CUDA library libcublas.so.10.1. LD_LIBRARY_PATH: 
2019-04-23 23:51:16.393797: F tensorflow/stream_executor/lib/statusor.cc:34] Attempting to fetch value instead of handling error Failed precondition: could not dlopen DSO: libcublas.so.10.1; dlerror: libcublas.so.10.1: cannot open shared object file: No such file or directory
[1]    4805 abort (core dumped)  ./tensorflow_test.py
```
**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

The following patch allows a workaround for CUDA 10.1 and specific affected libs:
```patch
diff --git a/tensorflow/stream_executor/dso_loader.cc b/tensorflow/stream_executor/dso_loader.cc
index 6dda5d6315..4df1d0dcfc 100644
--- a/tensorflow/stream_executor/dso_loader.cc
+++ b/tensorflow/stream_executor/dso_loader.cc
@@ -46,7 +46,7 @@ string GetCudnnVersion() { return TF_CUDNN_VERSION; }
 
 /* static */ port::Status DsoLoader::GetCublasDsoHandle(void** dso_handle) {
   return GetDsoHandle(FindDsoPath(port::Env::Default()->FormatLibraryFileName(
-                                      "cublas", GetCudaVersion()),
+                                      "cublas", "10"),
                                   GetCudaLibraryDirPath()),
                       dso_handle);
 }
@@ -63,14 +63,14 @@ string GetCudnnVersion() { return TF_CUDNN_VERSION; }
 
 /* static */ port::Status DsoLoader::GetCufftDsoHandle(void** dso_handle) {
   return GetDsoHandle(FindDsoPath(port::Env::Default()->FormatLibraryFileName(
-                                      "cufft", GetCudaVersion()),
+                                      "cufft", "10"),
                                   GetCudaLibraryDirPath()),
                       dso_handle);
 }
 
 /* static */ port::Status DsoLoader::GetCurandDsoHandle(void** dso_handle) {
   return GetDsoHandle(FindDsoPath(port::Env::Default()->FormatLibraryFileName(
-                                      "curand", GetCudaVersion()),
+                                      "curand", "10"),
                                   GetCudaLibraryDirPath()),
                       dso_handle);
 }
diff --git a/third_party/gpus/cuda_configure.bzl b/third_party/gpus/cuda_configure.bzl
index 8aa5b89cdd..7ed4bb8b45 100644
--- a/third_party/gpus/cuda_configure.bzl
+++ b/third_party/gpus/cuda_configure.bzl
@@ -842,7 +842,7 @@ def _find_libs(repository_ctx, cuda_config):
               repository_ctx,
               cpu_value,
               cuda_config.cuda_toolkit_path,
-              cuda_config.cuda_version,
+              '',
           ),
       "cusolver":
           _find_cuda_lib(
@@ -850,7 +850,7 @@ def _find_libs(repository_ctx, cuda_config):
               repository_ctx,
               cpu_value,
               cuda_config.cuda_toolkit_path,
-              cuda_config.cuda_version,
+              '',
           ),
       "curand":
           _find_cuda_lib(
@@ -858,7 +858,7 @@ def _find_libs(repository_ctx, cuda_config):
               repository_ctx,
               cpu_value,
               cuda_config.cuda_toolkit_path,
-              cuda_config.cuda_version,
+              '',
           ),
       "cufft":
           _find_cuda_lib(
@@ -866,7 +866,7 @@ def _find_libs(repository_ctx, cuda_config):
               repository_ctx,
               cpu_value,
               cuda_config.cuda_toolkit_path,
-              cuda_config.cuda_version,
+              '',
           ),
       "cudnn":
           _find_cuda_lib(
```

**Comment by kgizdov** [comment]
I would also like to mention that the following #26230 also suffers from the same problem. It tried to avoid it, but it only defers it. It allows to give `TF_CUDA_VERSION` and `TF_CUDA_LIB_VERSION` strings at configuration time, but ultimately, this will result in the same bug as not all CUDA libraries have (or are guaranteed to have) the same version.

**Comment by kgizdov** [comment]
ping @svenstaro

**Comment by chsigg** [comment]
I think this should mostly be fixed already with the dso_loader.cc code changed to *GetCudaLibVersion()* in the appropriate places. I say mostly because there was a bug that will be fixed in PR #28021.

**Comment by kgizdov** [comment]
@chsahit Just had a quick look. I don't agree. Also, specifically `GetCudaLibVersion()` is just postponing the issue, since it relies on the fact a single config time supplied constant can describe a possibly multitude of lib versions. Also, it seems there is a disconnect between config time and runtime library version determination, if I read the code correctly. I think lib versions must be determined once, either only at config time or only at runtime. They should also not fully rely on a user supplied constant and be determined per required lib - as it is done at config time, except currently it's hardcoded. Instead, it should be allowed to find appropriate versions and the result propagated for each to common generated header.

**Comment by chsigg** [comment]
CUDA libraries come with different versions in their name. 
- cuDNN, NCCL, TensorRT use major only.
- CUDA runtime uses major.minor.
- cuSPARSE, cuFFT, cuBLAS etc used major.minor up to 10.0, and just major starting with v10.1

CudaVersion() matches the second one (major.minor). 
CudaLibVersion() matches the last one (major.minor up to v10.0, major starting with v10.1).

The value of CudaVersion() and CudaLibVersion() is determined during the CUDA repository configuration and is written into a header file.

Does that clear things up?

I'm closing this issue. Feel free to reopen if PR #28021 doesn't fix the issue for you.

**Comment by mengdong** [comment]
as of 04/29, I am still experience following issue build with cuda 10.1

System information
OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: n/a
TensorFlow installed from (source or binary): source
TensorFlow version: master
Python version: 3.6.7
Installed using virtualenv? pip? conda?: system install to /usr
Bazel version (if compiling from source): 0.24.1
GCC/Compiler version (if compiling from source): GCC 7.3.0
CUDA/cuDNN version: 10.1/7.5.0


ERROR: /tensorflow/tensorflow/core/kernels/BUILD:1018:1: output 'tensorflow/core/kernels/_objs/diag_op_gpu/diag_op_gpu.cu.pic.o' was not created
ERROR: /tensorflow/tensorflow/core/kernels/BUILD:1018:1: not all outputs were created or valid
Target //tensorflow/tools/pip_package:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 962.337s, Critical Path: 139.55s
INFO: 10586 processes: 10586 local.
FAILED: Build did NOT complete successfully
