### ISSUE TITLE
Debug build fail: cuda_platform.cc

### ISSUE THREAD

**Issue by LuyuanChen** [tensorflow/tensorflow#28091]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04.2
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): Source
- TensorFlow version: 1.13/1.13.1/1.14
- Python version:3.6.7
- Installed using virtualenv? pip? conda?: pip
- Bazel version (if compiling from source): 0.21.0 (not from source)
- GCC/Compiler version (if compiling from source): 7.3.0
- CUDA/cuDNN version: 10.0/7.5
- GPU model and memory: RTX2080Ti/11GB

**Describe the problem**

**Provide the exact sequence of commands / steps that you executed before running into the problem**

Command used to build:
`bazel build --config=opt --config=cuda  -c dbg --strip=never //tensorflow/tools/pip_package:build_pip_package --verbose_failures`

Along the way, some code modifications are made to silent some errors, they are mentioned:
#24457
#22766
#2355

For some reason, the string parsing code in gpu_device.cc@1305 doesn't work and always errored out "Illegal version name [7.5]", so I hardcoded the cuda version.

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

```
ERROR: /home/lc/Developer/tensorflow/tensorflow/compiler/jit/ops/BUILD:16:1: Executing genrule //tensorflow/compiler/jit/ops:xla_ops_wrapper_py_pygenrule failed (Aborted): bash failed: error executing command
  (cd /home/lc/.cache/bazel/_bazel_lc/ba81b28ccf9c216ae3340fd9b9605d54/execroot/org_tensorflow && \
  exec env - \
    CUDA_TOOLKIT_PATH=/usr/local/cuda \
    CUDNN_INSTALL_PATH=/usr/local/cuda-10.0 \
    GCC_HOST_COMPILER_PATH=/usr/bin/gcc \
    LD_LIBRARY_PATH=/usr/local/cuda/lib64:/usr/local/cuda/lib64:/usr/local/cuda/lib64: \
    PATH=/bin:/usr/bin \
    PYTHON_BIN_PATH=/usr/bin/python3 \
    PYTHON_LIB_PATH=/usr/local/lib/python3.6/dist-packages \
    TF_CUDA_CLANG=0 \
    TF_CUDA_COMPUTE_CAPABILITIES=7.5 \
    TF_CUDA_VERSION=10.0 \
    TF_CUDNN_VERSION=7 \
    TF_NCCL_VERSION='' \
    TF_NEED_CUDA=1 \
    TF_NEED_OPENCL_SYCL=0 \
    TF_NEED_ROCM=0 \
  /bin/bash -c 'source external/bazel_tools/tools/genrule/genrule-setup.sh; bazel-out/host/bin/tensorflow/compiler/jit/ops/gen_xla_ops_wrapper_py_py_wrappers_cc , '\'''\'' 0 0 > bazel-out/k8-opt/genfiles/tensorflow/compiler/jit/ops/xla
_ops.py')
Execution platform: @bazel_tools//platforms:host_platform: bash failed: error executing command
  (cd /home/lc/.cache/bazel/_bazel_lc/ba81b28ccf9c216ae3340fd9b9605d54/execroot/org_tensorflow && \
  exec env - \
    CUDA_TOOLKIT_PATH=/usr/local/cuda \
    CUDNN_INSTALL_PATH=/usr/local/cuda-10.0 \
    GCC_HOST_COMPILER_PATH=/usr/bin/gcc \
    LD_LIBRARY_PATH=/usr/local/cuda/lib64:/usr/local/cuda/lib64:/usr/local/cuda/lib64: \
    PATH=/bin:/usr/bin \
    PYTHON_BIN_PATH=/usr/bin/python3 \
    PYTHON_LIB_PATH=/usr/local/lib/python3.6/dist-packages \
    TF_CUDA_CLANG=0 \
    TF_CUDA_COMPUTE_CAPABILITIES=7.5 \
    TF_CUDA_VERSION=10.0 \
    TF_CUDNN_VERSION=7 \
    TF_NCCL_VERSION='' \
    TF_NEED_CUDA=1 \
    TF_NEED_OPENCL_SYCL=0 \
    TF_NEED_ROCM=0 \
  /bin/bash -c 'source external/bazel_tools/tools/genrule/genrule-setup.sh; bazel-out/host/bin/tensorflow/compiler/jit/ops/gen_xla_ops_wrapper_py_py_wrappers_cc , '\'''\'' 0 0 > bazel-out/k8-opt/genfiles/tensorflow/compiler/jit/ops/xla
_ops.py')
Execution platform: @bazel_tools//platforms:host_platform
2019-04-23 18:11:46.123378: F tensorflow/stream_executor/cuda/cuda_platform.cc:201] Non-OK-status: MultiPlatformManager::RegisterPlatform(std::move(platform)) status: Internal:
/bin/bash: line 1: 20352 Aborted                 (core dumped) bazel-out/host/bin/tensorflow/compiler/jit/ops/gen_xla_ops_wrapper_py_py_wrappers_cc , '' 0 0 > bazel-out/k8-opt/genfiles/tensorflow/compiler/jit/ops/xla_ops.py
Target //tensorflow/tools/pip_package:build_pip_package failed to build
INFO: Elapsed time: 6.256s, Critical Path: 4.98s
INFO: 21 processes: 21 local.
FAILED: Build did NOT complete successfully
```

Thanks in advance for your help

**Comment by muddham** [comment]
@LuyuanChen Request you to please follow the [link (https://github.com/tensorflow/tensorflow/issues/8462), Hope it helps in resolution. Please let us know your progress. Thanks!

**Comment by LuyuanChen** [comment]
Thanks for your reply! 

But I don't think I share the same problem the link points too. I.e. I can compile TF just fine in normal mode (without the dbg flag). I think that means at least my CUDA/CuDNN installation is good.

**Comment by LuyuanChen** [comment]
Anyways, for anyone who doesn't need to mess with CUDA kernel level debugging, the following command is good enough
`bazel build  --cxxopt='-g' --cxxopt='-Og' --copt='-Og' --config cuda //tensorflow/tools/pip_package:build_pip_package`

Got from #27744
