### ISSUE TITLE
matmul for RaggedTensors / tf.ragged.ragged_dense_matmul

### ISSUE THREAD

**Issue by danielegrattarola** [tensorflow/tensorflow#28109]
**System information**
- TensorFlow version (you are using): 2.0.0a0

**Describe the feature and the current behavior/state.**
Allow to compute a matrix multiplication between a `RaggedTensor` and a standard dense tensor, returning a `RaggedTensor`.  
The behavior would be similar to `tf.sparse.sparse_dense_matmul`. 

For instance, given a `RaggedTensor` of shape `(batch, None, channels_in)`, and a dense tensor of shape `(channels_in, channels_out)`, the operation would return a `RaggedTensor` of shape `(batch, None, channels_out)`, where all entries along the ragged dimension have been multiplied by the dense tensor. 

**Will this change the current api? How?**
It could be implemented as a standalone operation like `tf.sparse.sparse_dense_matmul`, or it could be part of the existing API (for instance, `tf.math.sum` supports `RaggedTensors` as is). 

**Who will benefit with this feature?**
Anybody working with irregular data, with applications ranging from computer vision (irregular images) to deep learning on graphs.  
Given the possibility to have `matmul` and `add` on `RaggedTensors`, one could implement dense, convolutional, and recurrent layers operating directly on irregular data.

**Comment by captain-pool** [comment]
@jsimsa, @edloper is any work is being done on this, internally?

**Comment by edloper** [comment]
If `rt` is your ragged tensor with shape `(batch, None, channels_in)`, and `t` is your dense tensor with shape `(channels_in, channels_out)`, then you can do a matrix multiplication using:

    tf.ragged.map_flat_values(tf.matmul, rt, t)

Or equivalently:

    rt.with_flat_values(tf.matmul(rt.flat_values, t))

However, this isn't as easily discoverable as it should be.  Perhaps we should update tf.matmul to do this automatically.

(Note: using `map_flat_values` for this assumes that the innermost dimension of the ragged tensor is not ragged, as is the case in your example.  If the innermost dimension of the ragged tensor is ragged, then it's not clear how matmul should be defined.)

**Comment by danielegrattarola** [comment]
@edloper that works great. 
I agree that maybe it could be made more explicit in the docs, since matmul is a very important op in most applications. 

I'm gonna leave the issue open for now, I'll have a look at tf.matmul and see if I can do what you propose.

Thanks!

**Comment by TaekSoonJang** [comment]
@edloper 

* Tensorflow version: 2.0.0

I encountered this issue while figuring out doing matmul on a ragged tensor.

```python
rt = tf.ragged.constant([
    [
        [1.99, 2.1],
        [0.2, 0.1],
        [0.1, 0.5]
    ],
    [
        [1.0, 2.0],
        [3.0, 0.2]
    ]
], dtype=tf.float32)

t = tf.random.normal((2, 5))

tf.ragged.map_flat_values(tf.matmul, rt, t)
```

Above is the problem I am working on, but it ended up like:

```
InvalidArgumentErrorTraceback (most recent call last)
<ipython-input-35-9196c08d139c> in <module>
     13 t = tf.random.normal((2, 5))
     14 
---> 15 tf.ragged.map_flat_values(tf.matmul, rt, t)

/usr/local/lib/python3.7/dist-packages/tensorflow_core/python/ops/ragged/ragged_functional_ops.py in map_flat_values(op, *args, **kwargs)
     92     # and the splits.
     93     return ragged_tensor.RaggedTensor.from_nested_row_splits(
---> 94         op(*inner_args, **inner_kwargs), nested_splits_lists[0], validate=False)
     95 
     96 

/usr/local/lib/python3.7/dist-packages/tensorflow_core/python/util/dispatch.py in wrapper(*args, **kwargs)
    178     """Call target, and fall back on dispatchers if there is a TypeError."""
    179     try:
--> 180       return target(*args, **kwargs)
    181     except (TypeError, ValueError):
    182       # Note: convert_to_eager_tensor currently raises a ValueError, not a

/usr/local/lib/python3.7/dist-packages/tensorflow_core/python/ops/math_ops.py in matmul(a, b, transpose_a, transpose_b, adjoint_a, adjoint_b, a_is_sparse, b_is_sparse, name)
   2763     else:
   2764       return gen_math_ops.mat_mul(
-> 2765           a, b, transpose_a=transpose_a, transpose_b=transpose_b, name=name)
   2766 
   2767 

/usr/local/lib/python3.7/dist-packages/tensorflow_core/python/ops/gen_math_ops.py in mat_mul(a, b, transpose_a, transpose_b, name)
   6124       else:
   6125         message = e.message
-> 6126       _six.raise_from(_core._status_to_exception(e.code, message), None)
   6127   # Add nodes to the TensorFlow graph.
   6128   if transpose_a is None:

~/c3dl-client/lib/six.py in raise_from(value, from_value)

InvalidArgumentError: In[0] is not a matrix. Instead it has shape [10] [Op:MatMul] name: MatMul/
```

Would you help me do matmul on a ragged tensor as you suggested?

**Comment by decibelcooper** [comment]
@TaekSoonJang I believe you want to use either the `ragged_rank` or `inner_shape` argument of `tf.ragged.constant`

```python
rt = tf.ragged.constant([
    [
        [1.99, 2.1],
        [0.2, 0.1],
        [0.1, 0.5]
    ],
    [
        [1.0, 2.0],
        [3.0, 0.2]
    ]
], dtype=tf.float32, ragged_rank=1)

t = tf.random.normal((2, 5))

tf.ragged.map_flat_values(tf.matmul, rt, t)
```

**Comment by rmothukuru** [comment]
@danielegrattarola,
Sorry for the delayed response. In the documentation corresponding to [Ragged Tensor](https://www.tensorflow.org/api_docs/python/tf/ragged), in the section, [Additional ops that support RaggedTensor](https://www.tensorflow.org/api_docs/python/tf/ragged#additional_ops_that_support_raggedtensor_2), it is mentioned as 

> Arguments that accept RaggedTensors are marked in **bold**.

Below that statement, there are many operations, along with MatMul, as shown below:

![image](https://user-images.githubusercontent.com/48206667/116085396-66947580-a6bc-11eb-8ccb-ff87efef4732.png)

Can you please confirm if this is what you are looking for? Thanks!

**Comment by edloper** [comment]
@rmothukuru, Note that `tf.math.multiply` and `tf.linalg.matmul` are different operations.  RaggedTensors do support `tf.math.multiply` (elementwise multiplication).  They do not currently have direct support for `tf.linalg.matmul`; but as noted in the comments above, this operation can be performed (assuming both matrices have a non-ragged inner dimension) using `tf.ragged.map_flat_values(tf.matmul, x, y)`.

**Comment by rmothukuru** [comment]
@edloper,
Sorry for the misunderstanding.

**Comment by danielegrattarola** [comment]
As @edloper said, I was referring to `tf.matmul` in the original issue. 
However, since the operation can be implemented as a map, and probably also as a combination of `tf.math.multiply` and `tf.math.reduce_sum`, and since the issue is a few years old, I'd say that the requested is not likely to be implemented in the library so it's safe to close this issue. 

Thanks to everyone involved.
