### ISSUE TITLE
libtensorflowlite.so usage is not documented

### ISSUE THREAD

**Issue by imnotkind** [tensorflow/tensorflow#28105]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: Nexus 5X API 28 (android studio)
- TensorFlow installed from (source or binary): source
- TensorFlow version: master, r1.14
- Python version: 3.7
- Installed using virtualenv? pip? conda?: virtualenv pip
- Bazel version (if compiling from source): 0.24.1
- GCC/Compiler version (if compiling from source): MSVC 14.1
- CUDA/cuDNN version: 10.0 / 7.4
- GPU model and memory: RTX 2080 / 8GB

**Describe the problem**
I am in windows, but `libtensorflow_cc.so` build succeeded in windows for me.
But I cannot build libtensorflowlite.so, it says not all outputs were created or valid.
I don't know how to look into further build error details with bazel.

**Provide the exact sequence of commands / steps that you executed before running into the problem**
python configure.py
- no XLA JIT
- no ROCm
- yes CUDA (or no CUDA, both fails)
- yes Eigen Strong Inline

`bazel build --config opt //tensorflow/lite:libtensorflowlite.so`
```
INFO: From Linking tensorflow/lite/libtensorflowlite.so:
LINK : warning LNK4044: unrecognized option '/s'; ignored
ERROR: D:/myusers/haebin/program/tensorflow-master/tensorflow/lite/BUILD:426:1: output 'tensorflow/lite/libtensorflowlite.so.if.lib' was not created
ERROR: D:/myusers/haebin/program/tensorflow-master/tensorflow/lite/BUILD:426:1: not all outputs were created or valid
Target //tensorflow/lite:libtensorflowlite.so failed to build
INFO: Elapsed time: 90.626s, Critical Path: 28.46s
INFO: 182 processes: 182 local.
FAILED: Build did NOT complete successfully
```

**Any other info / logs**
I'm just curious, but is it possible to run tensorflow lite source codes (C++) in Windows 10 x86-64, if I successfully build this libtensorflowlite.so and include some libraries? I already succeeded in running tensorflow C++ codes with libtensorflow_cc.so in Windows.
I have read the docs and it seems like you guys offer a C++ api, but only in mobile environments?? Is tensorflow lite impossible to run in normal desktops?

**Additionally what I tried later (also didn't work)**
Ok, so I just gave up on native Windows tf lite, and tried to build android c++ shared lib with bazel. I used `bazel build //tensorflow/lite:libtensorflowlite.so --config=android --cpu
=x86 --cxxopt='--std=c++11' -c opt` in linux, because it seemed like building on windows bazel fails. I successfully built `libtensorflowlite.so` and tried these instructions : https://stackoverflow.com/questions/49834875/problems-with-using-tensorflow-lite-c-api-in-android-studio-project
So I built shared lib on linux, and tried to use it in windows android studio. I thought that it's eventually for android, so it would be ok to do that. (is it?)
But I got an error : incompatible target.

```
Build command failed.
Error while executing process C:\Users\poins\AppData\Local\Android\Sdk\cmake\3.6.4111459\bin\cmake.exe with arguments {--build D:\MyUsers\Haebin\repo\androidtflite\app\.externalNativeBuild\cmake\debug\x86 --target native-lib}
[1/1] Linking CXX shared library D:\MyUsers\Haebin\repo\androidtflite\app\build\intermediates\cmake\debug\obj\x86\libnative-lib.so
FAILED: cmd.exe /C "cd . && C:\Users\poins\AppData\Local\Android\Sdk\ndk-bundle\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe  --target=i686-none-linux-android --gcc-toolchain=C:/Users/poins/AppData/Local/Android/Sdk/ndk-bundle/toolchains/x86-4.9/prebuilt/windows-x86_64 --sysroot=C:/Users/poins/AppData/Local/Android/Sdk/ndk-bundle/sysroot -fPIC -isystem C:/Users/poins/AppData/Local/Android/Sdk/ndk-bundle/sysroot/usr/include/i686-linux-android -D__ANDROID_API__=15 -g -DANDROID -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -mstackrealign -Wa,--noexecstack -Wformat -Werror=format-security -std=c++11  -O0 -fno-limit-debug-info  -Wl,--exclude-libs,libgcc.a -Wl,--exclude-libs,libatomic.a -nostdlib++ --sysroot C:/Users/poins/AppData/Local/Android/Sdk/ndk-bundle/platforms/android-15/arch-x86 -Wl,--build-id -Wl,--warn-shared-textrel -Wl,--fatal-warnings -LC:/Users/poins/AppData/Local/Android/Sdk/ndk-bundle/sources/cxx-stl/llvm-libc++/libs/x86 -Wl,--no-undefined -Wl,-z,noexecstack -Qunused-arguments -Wl,-z,relro -Wl,-z,now -shared -Wl,-soname,libnative-lib.so -o D:\MyUsers\Haebin\repo\androidtflite\app\build\intermediates\cmake\debug\obj\x86\libnative-lib.so CMakeFiles/native-lib.dir/native-lib.cpp.o  D:/MyUsers/Haebin/repo/androidtflite/app/src/main/cpp/distribution/lib/libtensorflowlite_x86.so -llog -latomic -lm "C:/Users/poins/AppData/Local/Android/Sdk/ndk-bundle/sources/cxx-stl/llvm-libc++/libs/x86/libc++_static.a" "C:/Users/poins/AppData/Local/Android/Sdk/ndk-bundle/sources/cxx-stl/llvm-libc++/libs/x86/libc++abi.a" "C:/Users/poins/AppData/Local/Android/Sdk/ndk-bundle/sources/cxx-stl/llvm-libc++/libs/x86/libandroid_support.a" && cd ."
C:/Users/poins/AppData/Local/Android/Sdk/ndk-bundle/toolchains/x86-4.9/prebuilt/windows-x86_64/lib/gcc/i686-linux-android/4.9.x/../../../../i686-linux-android/bin\ld: error: D:/MyUsers/Haebin/repo/androidtflite/app/src/main/cpp/distribution/lib/libtensorflowlite_x86.so: incompatible target

clang++.exe: error: linker command failed with exit code 1 (use -v to see invocation)

ninja: build stopped: subcommand failed.
```
why is it incompatible? am I even right in using this C++ api this way? why is there no guide in tensorflow?

**Comment by jdduke** [comment]
Hi @imnotkind, just so it's clear, you're trying to build a shared library that you can deploy/use on an Android ARM device?

For that, you should use:
```
bazel build //tensorflow/lite:libtensorflowlite.so --config=android_arm64 --cxxopt='--std=c++11' -c opt
```

If you use `-cpu =x86` you're building for the emulator (for which you can use `--config=android_x86`).

Our libraries should be compatible with Windows, though, so let me look into that compilation failure.

**Comment by jdduke** [comment]
It's not well documented, apologies. We steer most Android developers to either the Android Java .aars or the prebuilt Maven libs.

We're working on a way to properly package not just the native shared C++ library but all of the necessary headers, which should make it much easier for C++ developers to use who aren't using bazel for their own project. We'll of course be adding complete documentation on how to do this on the regular dev site.

**Comment by jdduke** [comment]
Let me tweak this bug to be a feature request around the C++ documentation and usage.

**Comment by ValYouW** [comment]
That would be great, thanks!
Can I find prebuilt libs on maven (or maybe extract it from the Tensorflow Lite package)?
What would be the command to build the libs for iOS? 
Thx

**Comment by ValYouW** [comment]
Wrote a blog post on what it took me to build both the aar lib and c++ lib...
http://www.valyouw.com/2019/11/building-tensorflow-lite-for-android-on.html

**Comment by jdduke** [comment]
The tentative plan is for us to package the C++/C headers in the Android .aars that we host on Maven, alongside the prebuilt libs. It should then be straightforward to develop agains the native APIs using gradle (we'll have a sample). For iOS, we have the TensorFlowLiteC CocoaPod, but haven't finalized how we want to distribute the C++ APIs.

**Comment by ValYouW** [comment]
@jdduke Can I build for ios on Mac? when trying to pass `--config=ios_x86_64` or `--config=ios_arm64` but I get the error that "config value is not defined in any .rc", I am on the v2.0.0 branch.
If I omit the `--config` altogether the build is successful but Im not sure that the resulting `libtensorflowlite.so` would run on ios... (?)

Thx.

**Comment by ValYouW** [comment]
OK, trying the `master` branch and `ios_arm64` does compile, however it fails linking due to mac's clang I believe, I get the error:
`ld: unknown option: -z `
and if I remove the `-z defs` option from the BUILD file it fails on the other option which is unknown: `--version-script`.
Any idea??

**Comment by ValYouW** [comment]
Just an update, using `build_ios_universal_lib.sh` under `lite/tools/make` worked...

**Comment by jdduke** [comment]
@karimnosseir @yyoon can you offer guidance on this one?

**Comment by mohantym** [comment]
Hi @imnotkind ! I think this issue has been addressed [here](https://www.tensorflow.org/lite/guide/android#build_android_app_using_c) in the 2.8 version . You can use different target architectures to select a suitable build for your lite file . Ref [1](https://www.tensorflow.org/lite/guide/reduce_binary_size), [2](https://www.tensorflow.org/lite/guide/build_arm). Thanks!

**Comment by karimnosseir** [comment]
Looks resolved. Feel free to file an issue if you are still having problem.

Thanks
