### ISSUE TITLE
FP16 CUDA support

### ISSUE THREAD

**Issue by Archernarkiu** [tensorflow/tensorflow#28103]
Though tensorflow python api support fp16, actually model's performing won't benefit from this dytpe. I found there wasn't any content like _'cublasHgemm'_ in source file to support FP16. So I wonder is there any official schedule  to support FP16, or if there exist other ways to use FP16 for training/inference with tensorflow.

**Comment by ppwwyyxx** [comment]
> model's performing won't benefit from this dytpe

model's speed does benefit from this dtype (your mileage may vary depend on your model/hardware/other factors, of course)

**Comment by Archernarkiu** [comment]
@ppwwyyxx @muddham 
Here is my steps，
1. I  test my fp16 and fp32 tensorflow model on both P100 and GTX1080ti, and the results shows there wasn't any improvement.
2. I use the scripts in this repo https://github.com/hma02/cublasHgemm-P100 to test the performance of P100 and GTX1080ti,and the result shows below:
(1) fp16 will get 2x faster than fp32 on P100.
(2) fp32 will get 64x faster than fp16 on GTX1080ti.
the result above is just consistent with  Nvidia offical documents.
3. So I look into tensorflow source code, and there only contains 'cublasSgemm' , but no 'cublasHgemm' found.
As far as I know, tensorflow will call cuda interface while computing on a gpu. And my experiment denotes that the lack of cuda support lead to tensorflow's low performance on fp16.

So, is my conclusion right? Or is there exist any other way that I am not aware of to run a fp16 model on tensorflow.

**Comment by rootkitchao** [comment]
Nvidia Pascal GPU, only GP100 chip supports hardware FP16 calculation.So GTX1080TI can't get speed boost by using FP16.

**Comment by ppwwyyxx** [comment]
>  I look into tensorflow source code, and there only contains 'cublasSgemm' , but no 'cublasHgemm' found

Tensorflow not containing the string does not mean tensorflow does not use fp16. There are other ways to use fp16 without calling the function.

**Comment by jvishnuvardhan** [comment]
Closing this out since I understand it to be resolved, but please let me know if I'm mistaken. Thanks!
