### ISSUE TITLE
Unable to Convert Retrained MobileNet V2 SDD Model to .tflite Model for TensorFlow Lite Object Detection Android Demo

### ISSUE THREAD

**Issue by ash-yanagisawa** [tensorflow/tensorflow#28107]
**System information**
- Colab
- GPU
- Python 3
- TensorFlow 1.13.1

**Model**
ssd_mobilenet_v2_coco_2018_03_29

**Provide the text output from tflite_convert**
Please refer and run to the following .ipynb file with Colab
https://github.com/ash-yanagisawa/tensorflow-object-detection-training-colab/blob/master/tensorflow_object_detection_training_colab.ipynb

TensorFlow Lite Object Detection Android Demo
https://github.com/tensorflow/examples/tree/master/lite/examples/object_detection/android

**Any other info / logs**
Some of the operators in the model are not supported by the standard TensorFlow Lite runtime and are not recognized by TensorFlow. If you have a custom implementation for them you can disable this error with --allow_custom_ops, or by setting allow_custom_ops=True when calling tf.lite.TFLiteConverter(). Here is a list of builtin operators you are using: ADD, CONCATENATION, CONV_2D, DEPTHWISE_CONV_2D, LOGISTIC, RESHAPE. Here is a list of operators for which you will need custom implementations: TFLite_Detection_PostProcess.

**Comment by achandraa** [comment]
Please have a look #27832 or [#27241](https://github.com/tensorflow/tensorflow/issues/27241). Let us know if that helps. Thanks!

**Comment by achandraa** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
