### ISSUE TITLE
 ERROR when building pip package: undeclared function related to swig

### ISSUE THREAD

**Issue by peterzcc** [tensorflow/tensorflow#2811]
I was able to build the cc:tutorials_example_trainer , but failed to build the  pip package. Could anyone suggest how I can fix it? Thanks a lot!

### Environment info
Operating System:
CentOS 6.5
Installed version of CUDA and cuDNN: 
(please attach the output of `ls -l /path/to/cuda/lib/libcud*`):
cuda-7.5

### Steps to reproduce
1. I used python 3.5.1  installled by pyenv
2. I installed swig from source

### Error Log
ERROR: /csproject/dygroup2/czeng/downloads/tensorflow/tensorflow/python/BUILD:978:1: C++ compilation of rule '//tensorflow/python:_pywrap_tensorflow.so' failed: crosstool_wrapper_driver_is_not_gcc failed: error executing command
  (cd /csproject/dygroup2/czeng/.cache/bazel/_bazel_czeng/211970d9a1065a07eafbeb7dcc542b10/execroot/tensorflow && \
  exec env - \
    PATH=/project/dygroup2/czeng//.pyenv/shims:/project/dygroup2/czeng//.pyenv/bin:/project/dygroup2/czeng/venv/bin:/usr/lib64/qt-3.3/bin:/usr/local/bin:/bin:/usr/bin:/usr/local/cuda-7.5/bin:/usr/local/cuda-7.5/nvvm/bin:/csproject/dygroup2/czeng/venv/cudnnv5 \
    TMPDIR=/tmp/2110270.1.all.q \
  third_party/gpus/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc -U_FORTIFY_SOURCE '-D_FORTIFY_SOURCE=1' -fstack-protector -fPIE -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 -DNDEBUG -ffunction-sections -fdata-sections -g0 '-std=c++11' -MD -MF bazel-out/host/bin/tensorflow/python/_objs/_pywrap_tensorflow.so/tensorflow/python/pywrap_tensorflow.pic.d '-frandom-seed=bazel-out/host/bin/tensorflow/python/_objs/_pywrap_tensorflow.so/tensorflow/python/pywrap_tensorflow.pic.o' -fPIC -DGPR_BACKWARDS_COMPATIBILITY_MODE -iquote . -iquote bazel-out/host/genfiles -iquote external/protobuf -iquote bazel-out/host/genfiles/external/protobuf -iquote external/bazel_tools -iquote bazel-out/host/genfiles/external/bazel_tools -iquote external/farmhash_archive -iquote bazel-out/host/genfiles/external/farmhash_archive -iquote external/jpeg_archive -iquote bazel-out/host/genfiles/external/jpeg_archive -iquote external/png_archive -iquote bazel-out/host/genfiles/external/png_archive -iquote external/highwayhash -iquote bazel-out/host/genfiles/external/highwayhash -iquote external/re2 -iquote bazel-out/host/genfiles/external/re2 -iquote external/eigen_archive -iquote bazel-out/host/genfiles/external/eigen_archive -iquote external/grpc -iquote bazel-out/host/genfiles/external/grpc -iquote external/nanopb_git -iquote bazel-out/host/genfiles/external/nanopb_git -isystem external/protobuf/src -isystem bazel-out/host/genfiles/external/protobuf/src -isystem external/bazel_tools/tools/cpp/gcc3 -isystem external/farmhash_archive/farmhash-34c13ddfab0e35422f4c3979f360635a8c050260 -isystem bazel-out/host/genfiles/external/farmhash_archive/farmhash-34c13ddfab0e35422f4c3979f360635a8c050260 -isystem external/jpeg_archive/jpeg-9a -isystem bazel-out/host/genfiles/external/jpeg_archive/jpeg-9a -isystem external/png_archive/libpng-1.2.53 -isystem bazel-out/host/genfiles/external/png_archive/libpng-1.2.53 -isystem external/highwayhash -isystem bazel-out/host/genfiles/external/highwayhash -isystem external/re2 -isystem bazel-out/host/genfiles/external/re2 -isystem third_party/eigen3 -isystem bazel-out/host/genfiles/third_party/eigen3 -isystem external/eigen_archive/eigen-eigen-5f86b31739cd -isystem bazel-out/host/genfiles/external/eigen_archive/eigen-eigen-5f86b31739cd -isystem third_party/gpus/cuda/include -isystem bazel-out/host/genfiles/third_party/gpus/cuda/include -isystem third_party/py/numpy/numpy_include -isystem bazel-out/host/genfiles/third_party/py/numpy/numpy_include -isystem util/python/python_include -isystem bazel-out/host/genfiles/util/python/python_include -isystem third_party/gpus/cuda -isystem bazel-out/host/genfiles/third_party/gpus/cuda -isystem third_party/gpus/cuda/extras/CUPTI/include -isystem bazel-out/host/genfiles/third_party/gpus/cuda/extras/CUPTI/include -isystem external/grpc/include -isystem bazel-out/host/genfiles/external/grpc/include -isystem external/grpc -isystem bazel-out/host/genfiles/external/grpc -Wno-self-assign -Wno-write-strings -no-canonical-prefixes -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -fno-canonical-system-headers -c bazel-out/host/bin/tensorflow/python/pywrap_tensorflow.cc -o bazel-out/host/bin/tensorflow/python/_objs/_pywrap_tensorflow.so/tensorflow/python/pywrap_tensorflow.pic.o): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
bazel-out/host/bin/tensorflow/python/pywrap_tensorflow.cc: In function 'swig_module_info* SWIG_Python_GetModule()':
bazel-out/host/bin/tensorflow/python/pywrap_tensorflow.cc:2452:51: error: 'PyCObject_Import' was not declared in this scope
         (char*)"type_pointer" SWIG_TYPE_TABLE_NAME);
                                                   ^
bazel-out/host/bin/tensorflow/python/pywrap_tensorflow.cc: In function 'void SWIG_Python_SetModule(swig_module_info*)':
bazel-out/host/bin/tensorflow/python/pywrap_tensorflow.cc:2521:92: error: 'PyCObject_FromVoidPtr' was not declared in this scope
   PyObject *pointer = PyCObject_FromVoidPtr((void *) swig_module, SWIG_Python_DestroyModule);
                                                                                            ^
bazel-out/host/bin/tensorflow/python/pywrap_tensorflow.cc:2512:22: warning: unused variable 'swig_empty_runtime_method_table' [-Wunused-variable]
   static PyMethodDef swig_empty_runtime_method_table[] = { {NULL, NULL, 0, NULL} };/* Sentinel */
                      ^
bazel-out/host/bin/tensorflow/python/pywrap_tensorflow.cc: In function 'swig_type_info* SWIG_Python_TypeQuery(const char*)':
bazel-out/host/bin/tensorflow/python/pywrap_tensorflow.cc:2544:60: error: 'PyCObject_AsVoidPtr' was not declared in this scope
     descriptor = (swig_type_info *) PyCObject_AsVoidPtr(obj);
                                                            ^
bazel-out/host/bin/tensorflow/python/pywrap_tensorflow.cc:2549:51: error: 'PyCObject_FromVoidPtr' was not declared in this scope
       obj = PyCObject_FromVoidPtr(descriptor, NULL);
                                                   ^
bazel-out/host/bin/tensorflow/python/pywrap_tensorflow.cc: In function 'PyObject* _wrap_GetMatchingFiles(PyObject*, PyObject*)':
bazel-out/host/bin/tensorflow/python/pywrap_tensorflow.cc:5392:23: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     for (int i = 0; i < converted.size(); ++i) {
                       ^
At global scope:
cc1plus: warning: unrecognized command line option "-Wno-self-assign"
Target //tensorflow/tools/pip_package:build_pip_package failed to build

**Comment by caisq** [comment]
Which version of SWIG are you using? Can you try 3.0.8+?

**Comment by peterzcc** [comment]
Hi @caisq 

Thanks for your reply. I tried SWIG Version 3.0.8 to my virtualenv directory but another error occured, saying that libpcre.so.1 not found

**Comment by Phhere** [comment]
Same happens for 3.0.10
`(cd /root/.cache/bazel/_bazel_root/2b02cca0edf7f3a977d1db2d1af2e0e1/execroot/tensorflow-0.9.0 && \
  exec env - \
    PATH=/software/gcc/6.1.0/login/bin:/software/tensorflow/0.9.0/:/software/python/3.4.5/login/bin:/software/intel/xe2015/composer_xe_2015.1.133/bin/intel64:/software/intel/xe2015/composer_xe_2015.1.133/bin/intel64_mic:/software/intel/xe2015/composer_xe_2015.1.133/debugger/gui/intel64:/software/CUDA/7.5.18/bin:/software/bazel/0.3.0:/software/java/1.8.0_25//bin:/usr/pbs/bin:.:/bin:/usr/bin:/usr/local/bin:/usr/X11R6/bin \
  /software/gcc/6.1.0/login/bin/gcc -U_FORTIFY_SOURCE '-D_FORTIFY_SOURCE=1' -fstack-protector -Wall -Wl,-z,-relro,-z,now -B/software/gcc/6.1.0/login/bin -B/usr/bin -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 -DNDEBUG -ffunction-sections -fdata-sections '-std=c++0x' '-frandom-seed=bazel-out/local-py3-opt/bin/tensorflow/python/_objs/_pywrap_tensorflow.so/tensorflow/python/pywrap_tensorflow.pic.o' -fPIC -iquote . -iquote bazel-out/local-py3-opt/genfiles -iquote external/protobuf -iquote bazel-out/local-py3-opt/genfiles/external/protobuf -iquote external/bazel_tools -iquote bazel-out/local-py3-opt/genfiles/external/bazel_tools -iquote external/farmhash_archive -iquote bazel-out/local-py3-opt/genfiles/external/farmhash_archive -iquote external/jpeg_archive -iquote bazel-out/local-py3-opt/genfiles/external/jpeg_archive -iquote external/png_archive -iquote bazel-out/local-py3-opt/genfiles/external/png_archive -iquote external/highwayhash -iquote bazel-out/local-py3-opt/genfiles/external/highwayhash -iquote external/re2 -iquote bazel-out/local-py3-opt/genfiles/external/re2 -iquote external/eigen_archive -iquote bazel-out/local-py3-opt/genfiles/external/eigen_archive -iquote external/grpc -iquote bazel-out/local-py3-opt/genfiles/external/grpc -iquote external/nanopb_git -iquote bazel-out/local-py3-opt/genfiles/external/nanopb_git -isystem external/protobuf/src -isystem bazel-out/local-py3-opt/genfiles/external/protobuf/src -isystem external/bazel_tools/tools/cpp/gcc3 -isystem external/farmhash_archive/farmhash-34c13ddfab0e35422f4c3979f360635a8c050260 -isystem bazel-out/local-py3-opt/genfiles/external/farmhash_archive/farmhash-34c13ddfab0e35422f4c3979f360635a8c050260 -isystem external/jpeg_archive/jpeg-9a -isystem bazel-out/local-py3-opt/genfiles/external/jpeg_archive/jpeg-9a -isystem external/png_archive/libpng-1.2.53 -isystem bazel-out/local-py3-opt/genfiles/external/png_archive/libpng-1.2.53 -isystem external/highwayhash -isystem bazel-out/local-py3-opt/genfiles/external/highwayhash -isystem external/re2 -isystem bazel-out/local-py3-opt/genfiles/external/re2 -isystem third_party/eigen3 -isystem bazel-out/local-py3-opt/genfiles/third_party/eigen3 -isystem external/eigen_archive/eigen-eigen-d02e6a705c30 -isystem bazel-out/local-py3-opt/genfiles/external/eigen_archive/eigen-eigen-d02e6a705c30 -isystem third_party/py/numpy/numpy_include -isystem bazel-out/local-py3-opt/genfiles/third_party/py/numpy/numpy_include -isystem util/python/python_include -isystem bazel-out/local-py3-opt/genfiles/util/python/python_include -isystem third_party/gpus/cuda -isystem bazel-out/local-py3-opt/genfiles/third_party/gpus/cuda -isystem third_party/gpus/cuda/include -isystem bazel-out/local-py3-opt/genfiles/third_party/gpus/cuda/include -isystem external/grpc/include -isystem bazel-out/local-py3-opt/genfiles/external/grpc/include -isystem external/grpc -isystem bazel-out/local-py3-opt/genfiles/external/grpc -Wno-self-assign -Wno-write-strings -fno-canonical-system-headers -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -MD -MF bazel-out/local-py3-opt/bin/tensorflow/python/_objs/_pywrap_tensorflow.so/tensorflow/python/pywrap_tensorflow.pic.d -c bazel-out/local-py3-opt/bin/tensorflow/python/pywrap_tensorflow.cc -o bazel-out/local-py3-opt/bin/tensorflow/python/_objs/_pywrap_tensorflow.so/tensorflow/python/pywrap_tensorflow.pic.o): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
bazel-out/local-py3-opt/bin/tensorflow/python/pywrap_tensorflow.cc: In function 'swig_module_info* SWIG_Python_GetModule()':
bazel-out/local-py3-opt/bin/tensorflow/python/pywrap_tensorflow.cc:2452:51: error: 'PyCObject_Import' was not declared in this scope
         (char*)"type_pointer" SWIG_TYPE_TABLE_NAME);
`
