### ISSUE TITLE
How to specify Tensorflow Estimator Version when building tensorflow from source?

### ISSUE THREAD

**Issue by shizukanaskytree** [tensorflow/tensorflow#28118]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 16.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): source
- TensorFlow version: tf-nightly==1.13.1
- Python version: 3.6
- Installed using virtualenv? pip? conda?: pip
- Bazel version (if compiling from source): 
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 10.0
- GPU model and memory: 1080ti

**Describe the problem**

How to specify Tensorflow Estimator Version when building tensorflow from source?

I get the source code from commit id: d5a1417612a396dc8f5b8be08d3428367fa3771e
I find that Tensorflow Estimator is changed when I install it.

- `tf-estimator-nightly    1.14.0.dev2019042301` # new one
- `tf-estimator-nightly   1.14.0.dev2019031401` # previous one

The new one is not compatible with the d5a1417612a396dc8f5b8be08d3428367fa3771e code.
So, how to specify Tensorflow Estimator Version to `1.14.0.dev2019031401`?

**Provide the exact sequence of commands / steps that you executed before running into the problem**

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

```bash 
...
  File "/home/wxf/anaconda3/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/__init__.py", line 25, in <module>
    import tensorflow_estimator.python.estimator.estimator_lib
  File "/home/wxf/anaconda3/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/estimator_lib.py", line 22, in <module>
    from tensorflow_estimator.python.estimator.canned.baseline import BaselineClassifier
  File "/home/wxf/anaconda3/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/canned/baseline.py", line 65, in <module>
    from tensorflow_estimator.python.estimator import estimator
  File "/home/wxf/anaconda3/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1708, in <module>
    class EstimatorV2(Estimator):
  File "/home/wxf/anaconda3/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1711, in EstimatorV2
    export_savedmodel = deprecation.HIDDEN_ATTRIBUTE
AttributeError: module 'tensorflow.python.util.deprecation' has no attribute 'HIDDEN_ATTRIBUTE'
```

**Comment by mihaimaruseac** [comment]
Can you try `pip install tf-estimator-nightly==1.14.0.dev2019031401` just before building?

The change of nightly should have been only on the r1.14 branch

**Comment by mihaimaruseac** [comment]
Perfect. Sometime in the future the two projects won't be that tightly coupled.

Closing now as this has been fixed / has workaround
