### ISSUE TITLE
Issue for tf.keras.layers.DenseFeatures when model.build is called

### ISSUE THREAD

**Issue by skydoorkai** [tensorflow/tensorflow#28111]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes, my own example code.
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: No
- TensorFlow installed from (source or binary): binary, from tensorflow/tensorflow:2.0.0a0-gpu-py3 docker image.
- TensorFlow version (use command below): 2.0.0a0
- Python version: 3.5
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: n/a
- GPU model and memory: n/a

**Describe the current behavior**
tf.keras.layers.DenseFeatures is a new keras layer added in tf2.0a0. This is the first layer for tf.keras.Model that accepts dict of tensors as the input.

If tf.keras.layers.DenseFeatures is used as the first layer in a keras model created by subclass tf.keras.Model,  model.build(input_shape) will fail with any type of input_shape.

**Describe the expected behavior**
model.build(input_shape) will succeed, and corresponding model variables are created.

**Code to reproduce the issue**

```
import tensorflow as tf

feature_columns = [tf.feature_column.numeric_column(header) for header in ['c1', 'c2']]

class TestModel(tf.keras.Model):
    def __init__(self, feature_columns):
        super(TestModel, self).__init__()
        self.feature_layer = tf.keras.layers.DenseFeatures(feature_columns)
        self.dense_layer = tf.keras.layers.Dense(8)

    def call(self, inputs):
        x = self.feature_layer(inputs)
        return self.dense_layer(x)

model = TestModel(feature_columns=feature_columns)
shape = {'c1': (1,1), 'c2': (1,1)}
# change to:
# shape = [(1,1), (1, 1)]
# also fails.
model.build(shape)
print(model.trainable_variables)
```

**Other info / logs**
https://github.com/skydoorkai/tests_and_issues/tree/master/tensorflow/densefeature
provides with the repro Dockerfile, and a possible solution to it: Network.build(input_shape) accepts dict as the input.

**Comment by IanQS** [comment]
Seems like this is closely related to #27416 where the issue boils down to not being able to use DenseFeatures in a functional style?

**Comment by tanzhenyu** [comment]
@skydoorkai The approach referenced above looks good to me. Do you want to make a PR? If not I will submit a fix

**Comment by ymodak** [comment]
This issue exists with latest tf 2.0 nightly version '2.0.0-dev20190906'

**Comment by tanzhenyu** [comment]
@skydoorkai On the other hand, why do you want to build it? An alternative way is to call the model:
model(some dictionary of numpy inputs or keras.Input)

**Comment by jvishnuvardhan** [comment]
@skydoorkai As mentioned by @tanzhenyu calling the model works. Please check the gist [here](https://colab.sandbox.google.com/gist/jvishnuvardhan/d7f73dae8cd44241cb7e83f478f0096f/untitled853.ipynb). Thanks!

Please close the issue if this was resolved for you. Thanks!

**Comment by jvishnuvardhan** [comment]
I am closing the issue as it was resolved. Please feel free to reopen if the issue persists again. Thanks!

**Comment by lakezhang** [comment]
Why I get the same error in  TensorFlow 2.3.0?

import tensorflow as tf
tf.__version__
'2.3.0'

ValueError: Specified input shape is not one of the valid types. Please specify a batch input shape of type tuple or list of input shapes. User provided input type: <class 'dict'>

**Comment by lakezhang** [comment]
> I am closing the issue as it was resolved. Please feel free to reopen if the issue persists again. Thanks!

Why I get the same error in TensorFlow 2.3.0?

python : 3.6
tensorflow : 2.3.0
OS : macos

import tensorflow as tf
tf.version
'2.3.0'

ValueError: Specified input shape is not one of the valid types. Please specify a batch input shape of type tuple or list of input shapes. User provided input type: <class 'dict'>

**Comment by lakezhang** [comment]
I get the same error in linux and Tensorflow 2.2.0 too!

python: 3.8
tensorflow: 2.2.0
OS: Centos Linux 3.10.0-957.el7.x86_64 #1 SMP Thu Nov 8 23:39:32 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

Traceback (most recent call last):
  File "test.py", line 17, in <module>
    model.build(shape)
  File "/home/zhangzeming/anaconda3/lib/python3.8/site-packages/tensorflow/python/keras/engine/network.py", line 632, in build
    raise ValueError('Specified input shape is not one of the valid types. '
ValueError: Specified input shape is not one of the valid types. Please specify a batch input shape of type tuple or list of input shapes. User provided input type: <class 'dict'>

**Comment by lakezhang** [comment]
I get the same error in linux and Tensorflow 2.2.0 too!

python: 3.8
tensorflow: 2.2.0
OS: Centos Linux 3.10.0-957.el7.x86_64 #1 SMP Thu Nov 8 23:39:32 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

Traceback (most recent call last):
File "test.py", line 17, in
model.build(shape)
File "/home/work/anaconda3/lib/python3.8/site-packages/tensorflow/python/keras/engine/network.py", line 632, in build
raise ValueError('Specified input shape is not one of the valid types. '
ValueError: Specified input shape is not one of the valid types. Please specify a batch input shape of type tuple or list of input shapes. User provided input type: <class 'dict'>
