### ISSUE TITLE
Build fails due to missing @kissfft//:LICENSE

### ISSUE THREAD

**Issue by nickovs** [tensorflow/tensorflow#28129]
**System information**
- OS Platform and Distribution: Ubuntu 18.04
- TensorFlow installed from (source or binary): source 
- TensorFlow version: r1.14 https://github.com/tensorflow/tensorflow/commit/70d8199abb0c548fe75568cebe6bd9e2b7e6c25e
- Python version: 3.6.7
- Installed using virtualenv? pip? conda?: from source
- Bazel version (if compiling from source): 0.24.1
- GCC/Compiler version (if compiling from source): 7.3.0
- CUDA/cuDNN version: 10.0/7.5
- GPU model and memory: RTX 2060 6GB

**Describe the problem**

The current master fails to build because it fails to find `@kissfft//:LICENSE`.

**Provide the exact sequence of commands / steps that you executed before running into the problem**

```
git checkout r1.14
git pull --recurse-submodules.
bazel clean --expunge
./configure
bazel build --config=opt --config=cuda //tensorflow/tools/pip_package:build_pip_package
```

**Any other info / logs**
This appears to be due to a recent check-in (https://github.com/tensorflow/tensorflow/commit/15209edfc99cf9ef44c81cd37977a326ccee31c3 ) expecting to find a missing file.

**Comment by photogaff** [comment]
I got this exact same error:
ERROR: missing input file '@kissfft//:LICENSE'

**Comment by mihaimaruseac** [comment]
Fixed on master by 02badbcaba I think

**Comment by mihaimaruseac** [comment]
Should be fixed on r1.14 by #28136

**Comment by wdirons** [comment]
Builds on master are still failing.

**Comment by wdirons** [comment]
This commit may have fixed it on master: https://github.com/tensorflow/tensorflow/commit/7b8594571921a4e1885372edbabd30ac36192257

[The build hasn't failed yet at least]

**Comment by mihaimaruseac** [comment]
I'm sorry, the initial commit I posted was not fixing the build as I thought. The one you mentioned did.

**Comment by md-k-sarker** [comment]
Build succeeded at April 25 evening, but not installing. 
While installing it gives this error:
```
Collecting kissfft<1.3.1,>=1.3.0 (from tensorflow==1.13.1)
  Could not find a version that satisfies the requirement kissfft<1.3.1,>=1.3.0 (from tensorflow==1.13.1) (from versions: )
No matching distribution found for kissfft<1.3.1,>=1.3.0 (from tensorflow==1.13.1)
```
 
OS: Centos 7
Tensorflow: master branch. v1.13.1
Python: 3.5.2

**Comment by bananabowl** [comment]
Sorry for the breakage - this should have been fixed by https://github.com/tensorflow/tensorflow/commit/b63f929cc71abe8e7ccb8bd452fc51ab2cdef3ee

Please re-open if you are still experiencing problems.

**Comment by gbolcer** [comment]
I have to compile from sources as, while I have a modern GPU, my old xeon CPU lacks the SSE4 instruction set. 

bazel build --config=opt --config=cuda //tensorflow/tools/pip_package:build_pip_package
succeeds

./bazel-bin/tensorflow/tools/pip_package/build_pip_package /tmp/tensorflow_pkg
succeeds

pip3 install /tmp/tensorflow_pkg/tensorflow-1.13.1-cp36-cp36m-linux_x86_64.whl 

Collecting kissfft<1.3.1,>=1.3.0 (from tensorflow==1.13.1)
Exception:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/lib/python3/dist-packages/pip/commands/install.py", line 353, in run
    wb.build(autobuilding=True)
  File "/usr/lib/python3/dist-packages/pip/wheel.py", line 749, in build
    self.requirement_set.prepare_files(self.finder)
  File "/usr/lib/python3/dist-packages/pip/req/req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/usr/lib/python3/dist-packages/pip/req/req_set.py", line 554, in _prepare_file
    require_hashes
  File "/usr/lib/python3/dist-packages/pip/req/req_install.py", line 278, in populate_link
    self.link = finder.find_requirement(self, upgrade)
  File "/usr/lib/python3/dist-packages/pip/index.py", line 465, in find_requirement
    all_candidates = self.find_all_candidates(req.name)
  File "/usr/lib/python3/dist-packages/pip/index.py", line 423, in find_all_candidates
    for page in self._get_pages(url_locations, project_name):
  File "/usr/lib/python3/dist-packages/pip/index.py", line 568, in _get_pages
    page = self._get_page(location)
  File "/usr/lib/python3/dist-packages/pip/index.py", line 683, in _get_page
    return HTMLPage.get_page(link, session=self.session)
  File "/usr/lib/python3/dist-packages/pip/index.py", line 795, in get_page
    resp.raise_for_status()
  File "/usr/share/python-wheels/requests-2.18.4-py2.py3-none-any.whl/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://pypi.org/simple/kissfft/

Ubuntu 18.10
bazel 0.24.1
python 3.6.8
gcc-6 (others gcc-7, gcc-8 installed but configured to use 6)
cuda 10.0 (downgraded from 10.1)

I did compile kissfft from github and did a make install, but no help. 

It looks like a configuration issue in the bazel workspace that can be changed, but not sure where to look. Any help would be appreciated.

**Comment by gbolcer** [comment]
I guess I should read the instructions!

bazel clean
git update
bazel build --config=opt --config=cuda //tensorflow/tools/pip_package:build_pip_package
./bazel-bin/tensorflow/tools/pip_package/build_pip_package --nightly_flag /tmp/tensorflow_pkg
pip3 install /tmp/tensorflow_pkg/tensorflow-1.13.1-cp36-cp36m-linux_x86_64.whl 

The inclusion of the --nightly_flag when building the wheel fixed it.
