### ISSUE TITLE
Broken link for tensorboard

### ISSUE THREAD

**Issue by sergulaydore** [tensorflow/tensorflow#2813]
The link [https://www.tensorflow.org/versions/tensorboard/README.html](https://www.tensorflow.org/versions/tensorboard/README.html) for README file in [tensorboard](https://www.tensorflow.org/versions/master/how_tos/summaries_and_tensorboard/index.html) page is broken.

**Comment by prb12** [comment]
@danmane  This link still appears broken...

**Comment by RenatoUtsch** [comment]
This was fixed in the tensorboard page. The link https://www.tensorflow.org/versions/tensorboard/README.html was actually wrong. The correct is https://www.tensorflow.org/code/tensorflow/tensorboard/README.md

**Comment by RenatoUtsch** [comment]
Actually, there was a second Readme link on the page that I missed. I'll fix that.

**Comment by RenatoUtsch** [comment]
Fixed by 6b08d99, #3733 and #3734.

**Comment by danmane** [comment]
(The fix won't propagate to the website until the next rebuild. )
