### ISSUE TITLE
pb file cannot run on my mobile devices with android demo,but it pass with python scripts

### ISSUE THREAD

**Issue by sunzhe09** [tensorflow/tensorflow#28144]
here is my log:
No OpKernel was registered to support Op 'Range' with these attrs.  Registered devices: [CPU], Registered kernels:
      device='CPU'; Tidx in [DT_INT32]
      device='CPU'; Tidx in [DT_FLOAT]
    
    	 [[{{node unpool/range}} = Range[Tidx=DT_INT64](unpool/range/start, unpool/range/limit, unpool/range/delta)]]

I don't know why the Range operation 's data_type is int64  ,how can I  solve this probelm? If this is the cause,why my pb files can run pass with python on pc

**Comment by jvishnuvardhan** [comment]
@sunzhe09 Could you provide more details about the issue and context? Also, it would be great if you can provide any commands you followed. Please provide as many details as possible to resolve the issue faster. Thanks!

**Comment by sunzhe09** [comment]
sorry for my lately，here is my test model.pb
，I convert it 。the input node is Placeholder  ，output node is  sigmoid。you can freeze it！

**Comment by azilaazman** [comment]
@sunzhe09 any updates or progress made? im stuck on a similar error.

**Comment by sunzhe09** [comment]
> @sunzhe09 any updates or progress made? im stuck on a similar error.

No，I just change my tensorflow to 1.12.2，hope it helps！
