### ISSUE TITLE
Error running TFLite Quantized model on NNAPI

### ISSUE THREAD

**Issue by tamamachi** [tensorflow/tensorflow#28140]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Android 9 PQ2A.190205.001
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: Pixel 3
- TensorFlow installed from (source or binary):TensorFlow Lite from AAR
- TensorFlow version (use command below):tensorflow-lite:0.0.0-nightly

**Describe the current behavior**
We have an image classification model trained from scratch in frozen graph format and:

1. .tflite model converted without post-training quantization works well on CPU and NNAPI.
2. .tflite model converted with post-training quantization works well on CPU.
3. .tflite model converted with post-training quantization fails on NNAPI with following error message:

```
E/Utils: Invalid input tensor type TENSOR_QUANT8_ASYMM for input 1, expected TENSOR_FLOAT32
E/tflite: Returning error since NNAPI returned failure nnapi_delegate.cc:696.
    Returning error since TFLite returned failure nnapi_delegate.cc:739.
    Failed to build graph for NNAPI
```

We share the same code across all cases.

**Describe the expected behavior**
the quantized model should work on NNAPI

**Code to reproduce the issue**
Almost same as example below:
https://github.com/tensorflow/tensorflow/tree/eae92e9d58846f559561ae1c8934a025e740aeb2/tensorflow/lite/examples/android/app

We'd happy to attach our tflite model but GitHub says it's too large 😢 
The beginning of our model is like this:

<img width="1136" alt="スクリーンショット 2019-04-25 16 43 52" src="https://user-images.githubusercontent.com/3690310/56718223-58cc5280-6779-11e9-8573-222d7a156313.png">

**Comment by nardeas** [comment]
Just received the same error in similar conditions. +1 for this

**Comment by suharshs** [comment]
The NNAPI doesn't have post-training quantization tool support just yet, we are working on adding this as soon as we can, for now you will need to rely on tflite’s cpu fallback operatinos.

**Comment by mohantym** [comment]
Hi @tamamachi !  
We are checking to see whether you still need help in this issue .  Have you checked [NNAPI](https://www.tensorflow.org/lite/performance/nnapi#quantization) documentation on post-quantization from 2.8 version now yet?

**Comment by tamamachi** [comment]
Hi @mohantym ,
Thank you for letting me know. 
Unfortunately I've left from the team and I personally do not need help anymore. 
According to the document post-training quantization for NNAPI is ready (I haven't tested myself though) so feel free to close this issue.

**Comment by mohantym** [comment]
Ok @tamamachi !Thanks for responding. Closing this issue for now.
