### ISSUE TITLE
dataset object has no attribute 'output_shapes' in tensorflow 2.0 alpha version

### ISSUE THREAD

**Issue by gandalflee** [tensorflow/tensorflow#28148]
<em>Please make sure that this is a documentation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:doc_template</em>

**System information**
- TensorFlow version:2.0.0-alpha0
- Doc Link: https://tensorflow.google.cn/alpha/tutorials/text/text_classification_rnn

**Describe the documentation issue**
in the line 
"train_dataset = train_dataset.padded_batch(BATCH_SIZE, train_dataset.output_shapes)"
"train_dataset.output_shapes" can not run, train_dataset of tensorflow2.0 has no attribute 'output_shapes'.

**We welcome contributions by users. Will you be able to update submit a PR (use the [doc style guide](https://www.tensorflow.org/community/documentation)) to fix the doc Issue?**

**Comment by muddham** [comment]
@gandalflee I ran the code in google colab that was provided here, no error was shown. I ran this in cpu version. can you please check and let us know.

**Comment by mckinziebrandon** [comment]
I ran this on CPU and am seeing the same error.

**Comment by gandalflee** [comment]
> @gandalflee I ran the code in google colab that was provided here, no error was shown. I ran this in cpu version. can you please check and let us know.

please check the dataset api doc of version 2.0:
https://tensorflow.google.cn/versions/r2.0/api_docs/python/tf/data/Dataset
and version 1.13:
https://tensorflow.google.cn/api_docs/python/tf/data/Dataset

we can not find all properties (output_shapes,output_types) of version 1.13  in version 2.0, and, also can not find method "make_one_shot_iterator" in version 2.0.
is this a bug? or a new structure of dataset in tf2.0?

**Comment by gandalflee** [comment]
> @gandalflee I ran the code in google colab that was provided here, no error was shown. I ran this in cpu version. can you please check and let us know.

this error only shown in tf2.0.
 in tf1.13, it is ok

**Comment by muddham** [comment]
@gandalflee Executed the same in cpu version but I have not received any error,please see attached screen.As no error reproduced, closing this issue.
![image](https://user-images.githubusercontent.com/48215502/57353957-c7e97400-7187-11e9-9461-9e2047e2280f.png)

**Comment by suziW** [comment]
i think the output_shapes attribute is defined in tensorflow_datasets module
try first `import tensorflow_datasets as tfds`, and i get pass this error
tensorflow official should solve this problem

**Comment by SamuelMarks** [comment]
Try using [`tf.compat.v1.data.get_output_shapes`](https://www.tensorflow.org/api_docs/python/tf/compat/v1/data/get_output_shapes)

**Comment by grahit27** [comment]
Thanks @SamuelMarks. This command works.

**Comment by NFeruch** [comment]
> 
> 
> Try using [`tf.compat.v1.data.get_output_shapes`](https://www.tensorflow.org/api_docs/python/tf/compat/v1/data/get_output_shapes)

@SamuelMarks What do you mean by 'use' that link. Could you elaborate

**Comment by SamuelMarks** [comment]
@NFeruch So what was required—functionality wise—is now in the `get_output_shapes` function.
