### ISSUE TITLE
Float 16 for training ,storage,and running on tflite CPU and GPU

### ISSUE THREAD

**Issue by holyhao** [tensorflow/tensorflow#28146]
Since the tensorflow lite supports the GPU on mobile phone. But, it only supports float32 and float 16, the model size with float32 is too large. So, will the float16 be available for training and storage, and for converting to .tflite.

**Comment by impjdi** [comment]
Someone is actively working on this.  I don't have an exact ETA for this, but should land pretty soon.

**Comment by jvishnuvardhan** [comment]
@holyhao This is a stale issue. If someone is looking for an example to implement `float16` quantization, [Here](https://www.tensorflow.org/lite/performance/post_training_float16_quant) is an example described in detail in TF website. 

I am closing this issue. Please feel free to reopen if there is any related issue. Thanks!
