### ISSUE TITLE
[TF 2.0] Tf.keras.layers.Lambda does not fail if it does not support masking, but mask is passed

### ISSUE THREAD

**Issue by foxik** [tensorflow/tensorflow#28143]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): **YES**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): **Linux Debian Stable**
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: **N/A**
- TensorFlow installed from (source or binary): **binary**
- TensorFlow version (use command below): **CPU, both TF-2.0.0a0 and tf-nightly-2.0-preview-2.0.0.dev20190315**
- Python version: **3.5.3**
- Bazel version (if compiling from source): **N/A**
- GCC/Compiler version (if compiling from source): **N/A**
- CUDA/cuDNN version: **N/A**
- GPU model and memory: **N/A**

**Describe the current behavior**

When `tf.keras.layers.Lambda` is created without `mask` argument, it does not support masking (https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/keras/layers/core.py#L733). However, when a mask is passed, it is silently ignored and `None` is returned as the output mask (https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/keras/layers/core.py#L797).

**Describe the expected behavior**

When `tf.keras.layers.Lambda` is created without `mask` argument, it does not support masking. Therefore, when a mask is passed, it should raise an exception similarly to what `Layer.compute_mask` does (https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/keras/engine/base_layer.py#L494).

**Code to reproduce the issue**
```python
import numpy as np
import tensorflow as tf
m = tf.keras.Sequential([
    tf.keras.layers.Masking(.0),
    tf.keras.layers.Lambda(tf.nn.sigmoid)])
#     tf.keras.layers.GlobalMaxPool1D()])
m(np.array([[[0.]]]))
```

The above code does not fail and produces empty output mask. If the `Lambda` layer is replaced by `GlobalMaxPool1D` (which does not support masking), the model fails during construction.

**Other info / logs**

A fix is simple -- the `Lambda.compute_mask` should include the test present in `Layer.compute_mask`, namely: https://github.com/tensorflow/tensorflow/blob/9fc8d696b7019ad09d408933de0e4a4e7b81976f/tensorflow/python/keras/engine/base_layer.py#L505-L510

**Comment by jvishnuvardhan** [comment]
@foxik I could reproduce the issue with 2.0.0-alpha0 and tf-nightly. Here is the output(error) when `tf.keras.layers.GlobalMaxPool1D()])` enabled.

```
TypeError                                 Traceback (most recent call last)
<ipython-input-2-e24ba2c63d0f> in <module>()
      5     #tf.keras.layers.Lambda(tf.nn.sigmoid)])
      6      tf.keras.layers.GlobalMaxPool1D()])
----> 7 m(np.array([[[0.]]]))

4 frames
/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/base_layer.py in compute_mask(self, inputs, mask)
    503       if any(m is not None for m in nest.flatten(mask)):
    504         raise TypeError('Layer ' + self.name + ' does not support masking, '
--> 505                         'but was passed an input_mask: ' + str(mask))
    506       # masking not explicitly supported: return None as mask.
    507       return None

TypeError: Layer global_max_pooling1d does not support masking, but was passed an input_mask: tf.Tensor([[False]], shape=(1, 1), dtype=bool)
```


With TF1.13.1, I don't see the above error. Here is the output when `tf.keras.layers.GlobalMaxPool1D()])` enabled.
<tf.Tensor 'sequential/Max:0' shape=(1, 1) dtype=float64>

Thanks!

**Comment by foxik** [comment]
Note that the situation got even worse in TF 2.1, where `supports_masking` is not respected even for `GlobalMaxPool1D`, see #33260 :-(

**Comment by tanzhenyu** [comment]
Thanks for the report!
Looking through the code, here's my understanding:
1) The previous behavior (up until Tensorflow 2.0.0.alpha) is alway call self.compute_mask. Since GlobalMaxPooling doesn't override compute_mask, it will call `base_layer.compute_mask` and error out.
2) The current behavior (since Tensorflow 2.0.0 stable) is simply to swallow the mask if self.supports_masking=False and `compute_mask` is not overridden. Specifically the implementation:
```python
    # Only compute the mask if the Layer explicitly supports masking or has
    # overridden `compute_mask`.
    should_compute_mask = (
        hasattr(self, 'compute_mask') and
        (self.supports_masking or
         not getattr(self.compute_mask, '_is_default', False)))

    if mask_already_computed:
      flat_masks = [getattr(x, '_keras_mask', None) for x in flat_outputs]
    elif not should_compute_mask:
      flat_masks = [None for _ in flat_outputs]
    else:
      output_masks = self.compute_mask(inputs, previous_mask)
      # `compute_mask` can return a single `None` even when a Layer
      # has multiple outputs.
      if output_masks is None:
        flat_masks = [None for _ in flat_outputs]
      else:
        flat_masks = nest.flatten(output_masks)
```

This is definitely an un-noted behavior change. But I'm not sure if this is a bad change?

**Comment by rmothukuru** [comment]
@foxik ,
The code could be run successfully when executed with **`Tensorflow Version 2.4.1`**. Please find [the Gist](https://colab.research.google.com/gist/rmothukuru/6eed6a584bc9eba2fbe801a2f2d81c1a/gh_28143.ipynb) of the working code. Thanks!

**Comment by foxik** [comment]
@rmothukuru It seems (see also #33260 and especially comment https://github.com/tensorflow/tensorflow/issues/33260#issuecomment-609114823) that the semantics of masking changed since TF 2.0.0beta (since commit https://github.com/tensorflow/tensorflow/commit/8c65ee1de5ebcb85485cb0f7e5bc008134a394e7).

Therefore, I am closing this issue, it is enough to track the problem in #33260. But given that this mask semantics is around since TF 2.0, it is very unlikely to change, and with RaggedTensors I have stopped using masking anyway.

Cheers!
