### ISSUE TITLE
Define new ops with pure python

### ISSUE THREAD

**Issue by gaohuazuo** [tensorflow/tensorflow#2814]
AFAIK, new ops can't be created with python alone. However, such feature would be quite helpful when dealing with not-so-common IO, e.g. reading an LMDB, or when experimenting with new algorithms.

**Comment by ibab** [comment]
There's the `tf.py_func` op which lets you insert Python functions into the computational graph: https://www.tensorflow.org/versions/r0.9/api_docs/python/script_ops.html
Is this close to what you had in mind?

**Comment by gaohuazuo** [comment]
That's exactly what I'm looking for. @ibab Thanks!
