### ISSUE TITLE
Keras ValueError stops autograph building

### ISSUE THREAD

**Issue by ipod825** [tensorflow/tensorflow#28158]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): no
- TensorFlow installed from (source or binary):
pip
- TensorFlow version (use command below):
2.0.0-dev20190424
- Python version:
3.7.1
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
  cudatoolkit-10.0.130-0                                                                                                  
  cudnn-7.3.1-cuda10.0_0
- GPU model and memory:
GeForce RTX 2080 Ti

**Describe the current behavior**
Calling keras layer without calling `build()` automatically infers the shapes of the trainable variables. This works both in eager mode and graph mode in the current `2.0-alpha` version. However, running the provided code in `2.0.0-dev20190424` version, it gives the following error message:

```
W0425 12:08:40.775576 139922429134656 tf_logging.py:161] Entity <function update at 0x7f41dd7038c8> could not be transform
ed and will be executed as-is. Some features (e.g. tensor-dependent conditionals and loops) may not work as expected. Erro
r details can be found in the logs when running with the env variable AUTOGRAPH_VERBOSITY >= 1. Please report this to the
AutoGraph team. Cause: ValueError during conversion: Weights for model sequential have not yet been created. Weights are c
reated when the Model is first called on inputs or `build()` is called with an `input_shape`.
```
**Describe the expected behavior**

**Code to reproduce the issue**
```python
import os

import tensorflow as tf
from tensorflow.keras import layers, models, optimizers

os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'

model = models.Sequential([layers.Dense(1, activation='relu')])
optimizer = optimizers.SGD()

# Is this line needed in graph mode?
# model.build((None, 1))


@tf.function
def update(batch):
    with tf.GradientTape() as tape:
        output = model(batch)
    grads = tape.gradient(output, model.trainable_variables)
    optimizer.apply_gradients(zip(grads, model.trainable_variables))


if __name__ == "__main__":

    batch = tf.zeros((1, 1), dtype=tf.float32)
    update(batch)

```

**Comment by jvishnuvardhan** [comment]
I could reproduce the issue with tf-nightly. However, there is no error with TF2.0.0-alpha0. Thanks!

**Comment by mdanatg** [comment]
Just submitted a fix that should allow your code to work without calling model.build.
