### ISSUE TITLE
BUG on `tf.saved_model.load` with large variable

### ISSUE THREAD

**Issue by zakizhou** [tensorflow/tensorflow#28153]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): mac
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: none
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.0.alpha0
- Python version:
- Bazel version (if compiling from source): none
- GCC/Compiler version (if compiling from source): none
- CUDA/cuDNN version: none
- GPU model and memory: none

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
It works fine when run this in one console
```
import tensorflow as tf
import numpy as np


m = tf.Module()
m.v = tf.Variable(np.random.normal(size=(200, 200)).astype(np.float64))
m.f = tf.function(lambda x: x + m.v[0, 0])

tf.saved_model.save(m, "save/model", signatures={
    "predict": m.f.get_concrete_function(tf.constant(3., dtype=tf.float64))
})
```
and then the other
```
import tensorflow as tf
m = tf.saved_model.load("save/model")
```

If you change 200 to 20000, you will see errors on load
```
import tensorflow as tf
import numpy as np


m = tf.Module()
m.v = tf.Variable(np.random.normal(size=(20000, 20000)).astype(np.float64))
m.f = tf.function(lambda x: x + m.v[0, 0])

tf.saved_model.save(m, "save/model", signatures={
    "predict": m.f.get_concrete_function(tf.constant(3., dtype=tf.float64))
})
```
```
import tensorflow as tf
tf.saved_model.load("save/model")
# tensorflow.python.framework.errors_impl.InvalidArgumentError: save/model/variables/variables.data-00000-of-00001; Invalid argument [Op:RestoreV2]
```
**Describe the expected behavior**

Should be able to load regardless of the size of variable

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.
see above
**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by zakizhou** [comment]
@allenlavoie what's wrong with `tf.saved_model.load`

**Comment by allenlavoie** [comment]
FWIW I can't reproduce on Linux (on a machine with plenty of memory). It's probably mac-specific; I think someone reported a similar issue for checkpointing that only affected macs. I haven't had a chance to find a mac and debug it yet.

**Comment by zakizhou** [comment]
@allenlavoie I tested on ubuntu18.04 and there is no bugs involved.

**Comment by allenlavoie** [comment]
If it affects macs it is a bug. We do support macs. But possibly a duplicate of https://github.com/tensorflow/tensorflow/issues/18769
