### ISSUE TITLE
Link to Images guide broken

### ISSUE THREAD

**Issue by SoloSynth1** [tensorflow/tensorflow#28169]
**System information**
- TensorFlow version: N/A
- Doc Link: https://www.tensorflow.org/api_docs/python/tf/image

**Describe the documentation issue**

On the page
https://www.tensorflow.org/api_docs/python/tf/image

The link within the text "See the Images guide." is broken.
(It is currently directing to https://www.tensorflow.org/api_guides/python/image, but 404'd)

_edit: Removed contents from template unrelated to the issue._

**Comment by muddham** [comment]
@SoloSynth1 I had accessed the page provided, it says 404 error. We will take a look. Thanks for bringing this to our notice.

**Comment by jvishnuvardhan** [comment]
First two links are not working as shown in the [screenshot](https://screenshot.googleplex.com/Tv3SBDNQrmU). 
First link that is not working (bold_italic): Defined in tensorflow/_api/v1/image/**___init__.py_**
Second link that is not working (bold_italic): See the _**Images**_ guide . Thanks!

**Comment by vijayphoenix** [comment]
I can add an updated API guide similar to [image.md](https://github.com/tensorflow/docs/blob/r1.11/site/en/api_guides/python/image.md)

@muddham @jvishnuvardhan please share your views. Thank you

**Comment by MarkDaoust** [comment]
Hi @vijayphoenix 

We don't have an api-gides section anymore, but if you want to add that information back to the [docstring of the `tf.image` module](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/ops/image_ops.py), that could be good.

If you take this on, remember that the generated page includes a list of all the symbols in the module.

also remember that if you include example code, please use [doctest format](https://docs.python.org/3/library/doctest.html).

**Comment by vijayphoenix** [comment]
Hi @MarkDaoust,
I will do the necessary changes and make a PR.

Thank you for your input.

**Comment by vijayphoenix** [comment]
Hi @MarkDaoust,
I made a PR https://github.com/tensorflow/tensorflow/pull/37171 addressing this issue. Please take a look.
Thank you

**Comment by MarkDaoust** [comment]
LGTM, Thanks.
