### ISSUE TITLE
F tensorflow/core/lib/monitoring/collection_registry.cc:77] Cannot register 2 metrics with the same name: /tensorflow/cc/saved_model/load_attempt_count

### ISSUE THREAD

**Issue by PengchengYan** [tensorflow/tensorflow#28164]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
   EulerOS 4.8.5-4
- TensorFlow installed from (source or binary):
   source
- TensorFlow version:
  1.10.0
- Bazel version (if compiling from source):
  0.15.0
- GCC/Compiler version (if compiling from source):
  4.9.4

**Describe the problem**
Dear TensorFlow contributors,
I am using java to execute tensorflow model in tomcat in Linux with libtensorflow_jni.so and libtensorflow.jar , I have put libtensorflow_framework.so in LD_LIBRARY_PATH,  when the program started, the error happened:

F tensorflow/core/lib/monitoring/collection_registry.cc:77] Cannot register 2 metrics with the same name: /tensorflow/cc/saved_model/load_attempt_count

**Any other info / logs**
I guess maybe there are sth repeated in libtensorflow_jni.so and libtensorflow_framework.so and cause 'register 2 metrics'?

I read https://github.com/tensorflow/tensorflow/issues/13522，but I donnot know how to remove tensorflow-c dependency？

need your help，thanks

**Comment by PengchengYan** [comment]
or maybe I need to remove tensorflow_cc dependency?

**Comment by PengchengYan** [comment]
I resolved it by building with "--config=monolithic", so it seems work OK now.

**Comment by jvishnuvardhan** [comment]
Closing this out since I understand it to be resolved, but please let me know if I'm mistaken.

**Comment by PengchengYan** [comment]
yes, it has been resolved@jvishnuvardhan

**Comment by TuringLee** [comment]
> I resolved it by building with "--config=monolithic", so it seems work OK now.

hello,  what did you rebuilding ?

**Comment by sandeep22-v** [comment]
> I resolved it by building with "--config=monolithic", so it seems work OK now.

What all flags have you enabled for bazel build  apart from opt and monolithic
bazel build --config=opt //tensorflow/tools/pip_package:build_pip_package


I'm also facing the same issue..Can you please tell that sir
