### ISSUE TITLE
Text classification doc Google Colab notebook issue

### ISSUE THREAD

**Issue by viktordelacruz** [tensorflow/tensorflow#28168]
**System information**
- TensorFlow version: 1.13.1
- Doc Link: https://www.tensorflow.org/tutorials/keras/basic_text_classification

**Describe the documentation issue**
When running the Google Colab notebook from the documentation itself, I get an error saying "Object arrays cannot be loaded when allow_pickle=False". More details can be found in the attached image. Note that I ran the code directly from the Google colab notebook attached in the documentation.

Thank you!

![bug](https://user-images.githubusercontent.com/20063012/56782705-deeca580-681a-11e9-8ca2-6f51eef0c733.png)

**Comment by gadagashwini** [comment]
@viktordelacruz Please have look on this [#28102](https://github.com/tensorflow/tensorflow/issues/28102). Let us know how it progresses. Thanks!

**Comment by gadagashwini** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
