### ISSUE TITLE
Executing genrule //tensorflow/contrib/session_bundle/example:half_plus_two failed

### ISSUE THREAD

**Issue by kmhofmann** [tensorflow/tensorflow#2816]
Hi,
Installing TensorFlow from source fails on my system. There seems to be some Python-related error when building 'half_plus_two'.
See (hopefully) all relevant output below.

### Environment info
Operating System:

> lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04 LTS
Release:	16.04
Codename:	xenial

> uname -a
Linux the-beast 4.4.0-24-generic #43-Ubuntu SMP Wed Jun 8 19:27:37 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

Installed version of CUDA and cuDNN: 
(please attach the output of `ls -l /path/to/cuda/lib/libcud*`):

> ls -l /usr/local/cuda-8.0/lib64/libcud*
-rw-r--r-- 1 root root   560184 Jun 12 16:53 /usr/local/cuda-8.0/lib64/libcudadevrt.a
lrwxrwxrwx 1 root root       16 Jun 12 16:53 /usr/local/cuda-8.0/lib64/libcudart.so -> libcudart.so.8.0
lrwxrwxrwx 1 root root       19 Jun 12 16:53 /usr/local/cuda-8.0/lib64/libcudart.so.8.0 -> libcudart.so.8.0.27
-rwxr-xr-x 1 root root   394472 Jun 12 16:53 /usr/local/cuda-8.0/lib64/libcudart.so.8.0.27
-rw-r--r-- 1 root root   737516 Jun 12 16:53 /usr/local/cuda-8.0/lib64/libcudart_static.a
-rwxr-xr-x 1 root root 78065952 Jun 12 16:54 /usr/local/cuda-8.0/lib64/libcudnn.so
-rwxr-xr-x 1 root root 78065952 Jun 12 16:54 /usr/local/cuda-8.0/lib64/libcudnn.so.5
-rwxr-xr-x 1 root root 78065952 Jun 12 16:54 /usr/local/cuda-8.0/lib64/libcudnn.so.5.0.5
-rw-r--r-- 1 root root 68709594 Jun 12 16:54 /usr/local/cuda-8.0/lib64/libcudnn_static.a

If installed from sources, provide the commit hash:
bf83048d5f28b7fa0f39df799bd01a8fc581f5cf

### Steps to reproduce
1. Clone TensorFlow and follow instructions to build from source:
https://www.tensorflow.org/versions/r0.9/get_started/os_setup.html#installation-for-linux
2. Execute command
bazel build -c opt --config=cuda //tensorflow/tools/pip_package:build_pip_package
which ultimately fails.

### Logs or other output that would be helpful

This should be the relevant part:

michael@the-beast:~/devel/tensorflow$ bazel build -c opt --config=cuda //tensorflow/tools/pip_package:build_pip_package --verbose_failures
WARNING: /home/michael/.cache/bazel/_bazel_michael/09c785d214849e49e64c5959b4c31911/external/protobuf/WORKSPACE:1: Workspace name in /home/michael/.cache/bazel/_bazel_michael/09c785d214849e49e64c5959b4c31911/external/protobuf/WORKSPACE (@__main__) does not match the name given in the repository's definition (@protobuf); this will cause a build error in future versions.
WARNING: /home/michael/devel/tensorflow/util/python/BUILD:11:16: in includes attribute of cc_library rule //util/python:python_headers: 'python_include' resolves to 'util/python/python_include' not in 'third_party'. This will be an error in the future.
WARNING: /home/michael/.cache/bazel/_bazel_michael/09c785d214849e49e64c5959b4c31911/external/highwayhash/WORKSPACE:1: Workspace name in /home/michael/.cache/bazel/_bazel_michael/09c785d214849e49e64c5959b4c31911/external/highwayhash/WORKSPACE (@__main__) does not match the name given in the repository's definition (@highwayhash); this will cause a build error in future versions.
WARNING: /home/michael/.cache/bazel/_bazel_michael/09c785d214849e49e64c5959b4c31911/external/re2/WORKSPACE:1: Workspace name in /home/michael/.cache/bazel/_bazel_michael/09c785d214849e49e64c5959b4c31911/external/re2/WORKSPACE (@__main__) does not match the name given in the repository's definition (@re2); this will cause a build error in future versions.
INFO: Found 1 target...
ERROR: /home/michael/devel/tensorflow/tensorflow/contrib/session_bundle/example/BUILD:38:1: Executing genrule //tensorflow/contrib/session_bundle/example:half_plus_two failed: bash failed: error executing command 
  (cd /home/michael/.cache/bazel/_bazel_michael/09c785d214849e49e64c5959b4c31911/execroot/tensorflow && \
  exec env - \
    PATH=/home/michael/torch/install/bin:/home/michael/devel/jdk1.8.0_77/bin:/home/michael/devel/bazel/output:/usr/local/cuda-8.0/bin:/home/michael/devel/gocode/bin:/home/michael/torch/install/bin:/home/michael/torch/install/bin:/home/michael/torch/install/bin:/home/michael/torch/install/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin \
  /bin/bash -c 'source external/bazel_tools/tools/genrule/genrule-setup.sh; rm -rf /tmp/half_plus_two; /usr/bin/python bazel-out/host/bin/tensorflow/contrib/session_bundle/example/export_half_plus_two; cp -r /tmp/half_plus_two/* bazel-out/local_linux-opt/genfiles/tensorflow/contrib/session_bundle/example/half_plus_two'): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcublas.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcufft.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcuda.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcurand.so.8.0 locally
Traceback (most recent call last):
  File "/home/michael/.cache/bazel/_bazel_michael/09c785d214849e49e64c5959b4c31911/execroot/tensorflow/bazel-out/host/bin/tensorflow/contrib/session_bundle/example/export_half_plus_two.runfiles/org_tensorflow/tensorflow/contrib/session_bundle/example/export_half_plus_two.py", line 32, in <module>
    import tensorflow as tf
  File "/home/michael/.cache/bazel/_bazel_michael/09c785d214849e49e64c5959b4c31911/execroot/tensorflow/bazel-out/host/bin/tensorflow/contrib/session_bundle/example/export_half_plus_two.runfiles/org_tensorflow/tensorflow/__init__.py", line 23, in <module>
    from tensorflow.python import *
  File "/home/michael/.cache/bazel/_bazel_michael/09c785d214849e49e64c5959b4c31911/execroot/tensorflow/bazel-out/host/bin/tensorflow/contrib/session_bundle/example/export_half_plus_two.runfiles/org_tensorflow/tensorflow/python/__init__.py", line 52, in <module>
    from tensorflow.core.framework.graph_pb2 import *
  File "/home/michael/.cache/bazel/_bazel_michael/09c785d214849e49e64c5959b4c31911/execroot/tensorflow/bazel-out/host/bin/tensorflow/contrib/session_bundle/example/export_half_plus_two.runfiles/org_tensorflow/tensorflow/core/framework/graph_pb2.py", line 16, in <module>
    from tensorflow.core.framework import attr_value_pb2 as tensorflow_dot_core_dot_framework_dot_attr__value__pb2
  File "/home/michael/.cache/bazel/_bazel_michael/09c785d214849e49e64c5959b4c31911/execroot/tensorflow/bazel-out/host/bin/tensorflow/contrib/session_bundle/example/export_half_plus_two.runfiles/org_tensorflow/tensorflow/core/framework/attr_value_pb2.py", line 16, in <module>
    from tensorflow.core.framework import tensor_pb2 as tensorflow_dot_core_dot_framework_dot_tensor__pb2
  File "/home/michael/.cache/bazel/_bazel_michael/09c785d214849e49e64c5959b4c31911/execroot/tensorflow/bazel-out/host/bin/tensorflow/contrib/session_bundle/example/export_half_plus_two.runfiles/org_tensorflow/tensorflow/core/framework/tensor_pb2.py", line 16, in <module>
    from tensorflow.core.framework import tensor_shape_pb2 as tensorflow_dot_core_dot_framework_dot_tensor__shape__pb2
  File "/home/michael/.cache/bazel/_bazel_michael/09c785d214849e49e64c5959b4c31911/execroot/tensorflow/bazel-out/host/bin/tensorflow/contrib/session_bundle/example/export_half_plus_two.runfiles/org_tensorflow/tensorflow/core/framework/tensor_shape_pb2.py", line 22, in <module>
    serialized_pb=_b('\n,tensorflow/core/framework/tensor_shape.proto\x12\ntensorflow\"z\n\x10TensorShapeProto\x12-\n\x03\x64im\x18\x02 \x03(\x0b\x32 .tensorflow.TensorShapeProto.Dim\x12\x14\n\x0cunknown_rank\x18\x03 \x01(\x08\x1a!\n\x03\x44im\x12\x0c\n\x04size\x18\x01 \x01(\x03\x12\x0c\n\x04name\x18\x02 \x01(\tB/\n\x18org.tensorflow.frameworkB\x11TensorShapeProtosP\x01\x62\x06proto3')
TypeError: __init__() got an unexpected keyword argument 'syntax'
Target //tensorflow/tools/pip_package:build_pip_package failed to build
INFO: Elapsed time: 16.639s, Critical Path: 8.93s

**Comment by yaroslavvb** [comment]
I think I"ve seen this error when "git pull" overwrote files like CROSSTOOL
that ./configure sets up, can you try again after ./configure?

**Comment by kmhofmann** [comment]
The error still occurs after a fresh repository clone, a new call to ./configure, and also cleaning the Bazel cache (~/.cache/bazel).

**Comment by H0icky** [comment]
I delete the old version of protobuf

**Comment by H0icky** [comment]
I delete the old version(2.6.1) protobuf and it works
TF need protobuf 3.0
pip install --upgrade https://storage.googleapis.com/tensorflow/linux/cpu/protobuf-3.0.0b2.post2-cp27-none-linux_x86_64.whl

**Comment by kmhofmann** [comment]
Indeed, I verified that this works in a virtualenv environment. Compilation then succeeds with protobuf-3.0.0b2. Thanks!

The current documentation (https://www.tensorflow.org/versions/r0.9/get_started/os_setup.html#protobuf-library-related-issues) does not make it clear that installing a custom protobuf library is necessary for compilation. Instead, it is mentioned that "Install the above package after you have installed TensorFlow via pip, as the standard pip install tensorflow would install the python only pip package."
The "Installing from sources" section does not link to the "Protobuf library related issues" section.

It would be great if either the documentation could be amended, or (even better) this precondition could be checked before starting compilation, and a meaningful error message could be emitted.
