### ISSUE TITLE
Tensorflow.org display errors.

### ISSUE THREAD

**Issue by Whisht** [tensorflow/tensorflow#28173]
Hello there, something display error with **tensorflow.org** with a bunch of messy.
Just like this.
![image](https://user-images.githubusercontent.com/16497652/56794571-fdfe2e00-6840-11e9-8237-f03d8a8c4743.png)
![image](https://user-images.githubusercontent.com/16497652/56794637-21c17400-6841-11e9-9a46-ea10b982ebf1.png)

**Comment by jvishnuvardhan** [comment]
@Whisht It is strange. I know you are trying to access tutorials page. Tutorials page should look like this https://screenshot.googleplex.com/DMWAtBAQvkx

1. Could you tell from which region (Asia, Europe, America etc) your are accessing TF website? 
2. Are you using Chrome? Could you check the same page using others (IE,Firefox, Safari etc)
3. Do you see similar things in other pages. Could you share a screenshot.
Thanks!

**Comment by Whisht** [comment]
@jvishnuvardhan 
Absolutely.
> 1. I access tensorflow.org from China.
> 2. Yes, the browser is Chrome. And this page display the same error no matter browser I use.
> 3.  The same error is happened in `https://developers.google.com/` and any sub-page of `tensorflow.org`.
Here are the screenshots.
![Snipaste_2019-05-01_12-54-10](https://user-images.githubusercontent.com/16497652/57006111-ac72ec00-6c10-11e9-9dcf-91f39a99a235.png)
![Snipaste_2019-05-01_12-53-19](https://user-images.githubusercontent.com/16497652/57006112-ad0b8280-6c10-11e9-94ca-413e1abedd4a.png)
![Snipaste_2019-05-01_12-55-52](https://user-images.githubusercontent.com/16497652/57006113-ad0b8280-6c10-11e9-94c1-5c8f6254d83d.png)
![Snipaste_2019-05-01_12-52-53](https://user-images.githubusercontent.com/16497652/57006114-ada41900-6c10-11e9-8f5c-41ce02be46c1.png)

**Comment by lamberta** [comment]
@Whisht Does this happen when you access the site through tensorflow.google.cn ? Do you have any JavaScript blockers on?

**Comment by Whisht** [comment]
@lamberta No matter tensorflow.google.cn or tensorflow.org, I encountered the same error. And I have turned the  blockers off. For that I did't misjudge, I have tried to access these website through other browsers, such as Firefox and Microsoft Edge which have no type of plug-ins.

**Comment by lamberta** [comment]
This seems related to how webfonts from fonts.googleapis.com are blocked in China.
Tracking: b/134091451

**Comment by lamberta** [comment]
Hi @Whisht, can you try this again? Testing thinks you have a Chrome extension installed that is blocking Google web fonts.

**Comment by Whisht** [comment]
Hello, @lamberta .Sorry for not follwing up this issue.
Here is my latest testing result.
I test the display result throug 3 browsers. MS egde, Firefox as well as Chrome. There still exists the same problem.

-  The common display error of top bar.

![Snipaste_2019-06-29_13-16-06](https://user-images.githubusercontent.com/16497652/60380061-4cae8b00-9a71-11e9-85f3-878138fb185a.png)
- Edge without angy extension installed.
![edge](https://user-images.githubusercontent.com/16497652/60380062-546e2f80-9a71-11e9-972a-1a7a6efd6430.png)
- Chrome with AD blocker.
![chrome](https://user-images.githubusercontent.com/16497652/60380073-926b5380-9a71-11e9-8b2f-e2b61c78c3bb.png)
- Chrome that turning off all extension.
![chrome 无痕](https://user-images.githubusercontent.com/16497652/60380076-a616ba00-9a71-11e9-803e-4d0dc151cd84.png)
- Firefox without any installed extension.
![firefox](https://user-images.githubusercontent.com/16497652/60380123-79af6d80-9a72-11e9-8e4d-d8ac47ab1e69.png)


By the way, Whether I access `tensorflow.org` through a shadowsocks proxy or access `tensorflow.org.cn` directly. There are same display error.
![Snipaste_2019-06-29_13-31-33](https://user-images.githubusercontent.com/16497652/60380105-4076fd80-9a72-11e9-9ab0-578cca99fef3.png)

**Comment by lamberta** [comment]
Thank you, @Whisht, for the follow up.

**Comment by lamberta** [comment]
Thanks, @Whisht.

Seems to be an issue with Google Fonts getting blocked. Assuming you're using a VPN to access tensorflow.org or using tensorflow.google.cn, these resources should be available. There may be something at the ISP-level going on.

SInce there doesn't seem like much we can do, closing this issue for now. We can re-examine if there are more reports.

Thank you for your help and will keep an eye on it.

**Comment by Whisht** [comment]
That's all right, thanks for your kindly help@lamberta

**Comment by zurgeg** [comment]
I know this is an old issue, but I was having the same problem on Firefox. Clearing cookies (lock icon > Clear Cookies and Site Data) helped, until I refreshed. I read this issue, and decided to try and turn off UBlock Origin.  That solved the problem. Is it possible you have a tracking protection feature on?
