### ISSUE TITLE
padding causal with conv1d gives an error

### ISSUE THREAD

**Issue by volvador** [tensorflow/tensorflow#28186]
**System information**
- I wrote custom code
- System : Linux
- TensorFlow 1.11
- Keras version(embedded in TF) '2.1.6-tf'

It seems keras Conv1D (embedded in Tensorflow) does not support 'causal' in Conv1D contrary to what is stated in the class doc string in the code. Here is a simple code to reproduce

    from tensorflow.python.keras.models import Sequential
    from tensorflow.python.keras.layers import InputLayer
    from tensorflow.python.keras.layers.convolutional import Conv1D
    model = Sequential()
    model.add(InputLayer(name='input_layer', input_shape=(5,3,)))
    model.add(Conv1D(1, kernel_size=1, padding='causal'))

This results in the error

    ValueError: Attr 'padding' of 'Conv2D' Op passed string 'CAUSAL' not in: "SAME", "VALID".

Any help please? (please notice I am trying to construct a `Conv1D` layer but the error mentions `Conv2D`

**Comment by yongtang** [comment]
With tensorflow 1.13.1 I am not seeing the issue. Think the issue has been resolved?

**Comment by gadagashwini** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
