### ISSUE TITLE
PhasedLSTMCell only accepts 1-dimensional time input

### ISSUE THREAD

**Issue by ghost** [tensorflow/tensorflow#28185]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):

Yes

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):

Docker image, details below;
```
REPOSITORY              TAG                      IMAGE ID            CREATED             SIZE
tensorflow/tensorflow   latest-gpu-py3-jupyter   8c77abe6b462        8 weeks ago         3.57GB
```

- TensorFlow installed from (source or binary):
Binary

- TensorFlow version (use command below):
Git Version: v1.13.1-0-g6612da8951
Version: 1.13.1

- Python version:
3.5.2

- CUDA/cuDNN version:

```
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2018 NVIDIA Corporation
Built on Sat_Aug_25_21:08:01_CDT_2018
Cuda compilation tools, release 10.0, V10.0.130
```

- GPU model and memory:
NVIDIA GTX 1050 Ti

**Describe the current behavior**

When passing multi-dimensional time input into a Phased LSTM Cell, I am presented with an arithmetic error;

```
ValueError: Dimensions must be equal, but are 6 and 256 for 'test/rnn/sub' (op: 'Sub') with input shapes: [?,6], [256].
```

This appears to be caused by the following line in `rnn_cell.py`, which seems to make the assumption that `time` has one dimension;

```
~usr/local/lib/python3.5/dist-packages/tensorflow/contrib/rnn/python/ops/rnn_cell.py in _get_cycle_ratio(self, time, phase, period)
   1965     phase_casted = math_ops.cast(phase, dtype=time.dtype)
   1966     period_casted = math_ops.cast(period, dtype=time.dtype)
-> 1967     shifted_time = time - phase_casted
   1968     cycle_ratio = self._mod(shifted_time, period_casted) / period_casted
   1969     return math_ops.cast(cycle_ratio, dtype=dtypes.float32)
```

**Describe the expected behavior**

LSTM computes phases and `shifted_time` for *each* parameter separately (in this case, this would require `shifted_time` and other relevant variables to be the same size as the number of features in the input - e.g. 6 input features implies that `shifted_time` should be a 6-dimensional vector)

**Code to reproduce the issue**

```python
import tensorflow as tf

from tensorflow.keras import backend as K
from tensorflow.keras.models import Model
from tensorflow.keras.utils import Sequence

from tensorflow.keras.layers import (
    RNN,
    Input,
    Dense
)

from tensorflow.contrib.rnn import PhasedLSTMCell

K.clear_session()

with tf.variable_scope('test', reuse=tf.AUTO_REUSE):
    t_series_dim = 6
    output_dim = 1

    # Inputs here
    timestamps = Input(shape=(None, t_series_dim,), name='t_input')
    feature_signals = Input(shape=(None, t_series_dim,), name='ts_input')

    # Layer configuration
    ## Time-series input
    time_input = (timestamps, feature_signals)
    
    cell = PhasedLSTMCell(256)
    ts_x = RNN(cell, return_sequences=False)(time_input)
    
    # Output layer
    logits = Dense(output_dim, name='logits', activation='sigmoid')(ts_x)

    # Stick it all together inside a model...
    model = Model(
        inputs=[timestamps, feature_signals],
        outputs=[logits]
    )

    # Define an optimiser and metrics, and compile the model
    model.compile(
        optimizer='adam',
        loss=['binary_crossentropy'],
        metrics=['binary_accuracy']
    )
```

**Other info / logs**

To give you some context, I have several sensors generating signals at uneven sample rates. For example, "sensor 1" reports at a frequency of 2Hz, while others may range up to 16Hz. Each of these features has their own time stamps (e.g. the first 5 time stamps for "sensor 1" at 2Hz would be something like [0.0, 0.5, 1.0, 1.5, 2.0] - while "sensor 2" at 8Hz would be something like [0.0, 0.125, 0.25, 0.375, 0.5]) so it's more helpful to provide each individual feature's timestamps alongside the feature.

I'm not sure if I am describing this adequately. Please ask for clarification if required!

**Comment by jvishnuvardhan** [comment]
@newey01c  I could reproduce the issue with TF1.13.1. Thanks!

**Comment by qlzh727** [comment]
From the docstring in the call() method of PhasedLSTMCell, its quite clear that its expecting two tensor, and the shape are (batch, 1) and (batch, features_size). So the timestamps input in your code snippet is actually not correct. The shape of that should be
```python
 timestamps = Input(shape=(None, 1), name='t_input')
```

**Comment by newey01c** [comment]
@qlzh727 you are correct. However, in the case of several inputs with vastly different sample rates (e.g. imagine 2 sensors; one with 1000Hz sample rate, and the other with 2.5Hz) it doesn't seem a particularly efficient strategy. Obviously this is an exaggerated scenario but it's illustrative. To jointly train a Phased LSTM on outputs from these sensors, one would need to essentially stretch the 2.5Hz sample tensor to the same dimensions as the 1000Hz, so that the time tensor can be used to represent both inputs.

If it's worthwhile, I'm happy to try and develop an alternative implementation (so that users can provide a time tensor for each input). What are your thoughts as to the performance implications of this?

**Comment by qlzh727** [comment]
I haven't dig deep into the paper yet, but we are no long releasing contrib in Tensorflow 2.0, the change you are about to make will probably never get released anymore.

Having said that, if you would like to contribute the change, you can make the updated cell to tensorflow/addons repository, which is the new github repository for extended APIs.

**Comment by rthadur** [comment]
Contrib has been depreciated here in Tensorflow repo and moved to tensorflow/addons , please reopen the issue in https://github.com/tensorflow/addons/issues if this exists in latest version. Thank you
