### ISSUE TITLE
tf.gradients casts away imaginary part of result when differentiating by a real value 

### ISSUE THREAD

**Issue by ibab** [tensorflow/tensorflow#2818]
This is continued from #2255:

Differentiating a complex expression by a real value with `tf.gradients` should yield a complex value, but this doesn't seem to be the way that `tf.gradients` works at the moment.
If I run

```
import tensorflow as tf
import numpy as np

s = tf.Session()
x = tf.placeholder(tf.float32)

z = tf.complex(0., x)

print('full', s.run(tf.gradients(z, [x]), feed_dict={x: 1}))
print('real', s.run(tf.gradients(tf.real(z), [x]), feed_dict={x: 1}))
print('imag', s.run(tf.gradients(tf.imag(z), [x]), feed_dict={x: 1}))
```

The output is

```
full [0.0]
real [0.0]
imag [1.0]
```

while I would have expected

```
full [0.0 + 1.0j]
real [0.0]
imag [1.0]
```

I suspect that `tf.gradients` always casts the final result to the type of the variable that we differentiate with respect to, which makes sense in many circumstances, but leads to incorrect behaviour in this case.

**Comment by ibab** [comment]
I've thought about this some more and realized that tensorflow expression aren't necessarily holomorphic, which means returning a complex number doesn't always make sense.
Maybe it would be better to throw an error if the user tries to differentiate a complex expression?
The user can always insert a `tf.real` to make it work the way it currently does, and this would prevent accidental mistakes.

**Comment by girving** [comment]
Throwing an error is an option.  For consistency I'd prefer to throw an error if the tensor isn't scalar as well.  Unfortunately, absorbing either change would require verifying that all the downstream code doesn't (weirdly) depend on this behavior, which makes it hard to do from the outside.

**Comment by corcra** [comment]
If not an error, a warning at least would be useful.

**Comment by ftamburin** [comment]
I am trying to compute the gradients of a complex function in Tensorflow, but I have some trouble. 
Could it be the same problem described by @ibab ?
Here is my code:
```
import numpy as np
import tensorflow as tf

def CompSEQ(rho0):

    def EvolveRHO(prev, input):
        return tf.matmul(rho0,prev)

    rhos = tf.scan(EvolveRHO, np.array([1, 2, 3]), initializer=rho0)
    return tf.real(tf.trace(tf.unpack(tf.slice(rhos,[2,0,0],[1,2,2]))[0]))

np.random.seed(1234)
N = 2

x_r = tf.Variable(tf.zeros([N,N], dtype=tf.float32))
x_i = tf.Variable(tf.zeros([N,N], dtype=tf.float32))
fun = CompSEQ(tf.complex(x_r,x_i))
#grad = tf.gradients([fun],[x_r,x_i])    # THIS LINE CAUSES THE PROBLEM!!!

sess = tf.Session()
sess.run(tf.initialize_all_variables())

re = np.random.rand(N,N).astype(np.float32)
im = np.random.rand(N,N).astype(np.float32)
print('fun',sess.run(fun, feed_dict={x_r:re, x_i:im}))
print('grad',sess.run(grad, feed_dict={x_r:re, x_i:im}))
```
I use 2 input float32 vectors x,y that will be transformed into a complex matrix. All the computations are performed using complex numbers and at the end all the result is transformed into a float32 by taking the real part. If I comment the call to tf.gradients (as in the code) everything works fine, but when I try to compute the gradients I get the following error:
```
Traceback (most recent call last):
  File "errorS.py", line 18, in <module>
    grad = tf.gradients([fun],[x_r,x_i])	# THIS LINE CAUSES THE PROBLEM!!!
  File "/Users/tamburin/Library/Python/2.7/lib/python/site-packages/tensorflow/python/ops/gradients.py", line 486, in gradients
    _VerifyGeneratedGradients(in_grads, op)
  File "/Users/tamburin/Library/Python/2.7/lib/python/site-packages/tensorflow/python/ops/gradients.py", line 264, in _VerifyGeneratedGradients
    dtypes.as_dtype(inp.dtype).name))
ValueError: Gradient type float32 generated for op name: "scan/while/Switch_1"
op: "Switch"
input: "scan/while/Merge_1"
input: "scan/while/LoopCond"
attr {
  key: "T"
  value {
    type: DT_COMPLEX64
  }
}
attr {
  key: "_class"
  value {
    list {
      s: "loc:@scan/while/Merge_1"
    }
  }
}
 does not match input type complex64
```
Converting all the computations into float32 variables (replacing tf.complex with tf.add and deleting tf.real) resolves the problem, but I need to maintain the computation on complex variables (this is a very simplified example w.r.t. my real problem).

**Comment by jingli9111** [comment]
Same problem when running dynamic_rnn with complex hidden state.

  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tensorflow/python/ops/gradients.py", line 264, in _VerifyGeneratedGradients
    dtypes.as_dtype(inp.dtype).name))
ValueError: Gradient type float32 generated for op name: "RNN/while/Switch_2"
op: "Switch"
input: "RNN/while/Merge_2"
input: "RNN/while/LoopCond"
attr {
  key: "T"
  value {
    type: DT_COMPLEX64
  }
}
attr {
  key: "_class"
  value {
    list {
      s: "loc:@RNN/while/Merge_2"
    }
  }
}
 does not match input type complex64

**Comment by jingli9111** [comment]
Same problem when running dynamic_rnn with complex hidden states. 
```
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tensorflow/python/ops/gradients.py", line 264, in _VerifyGeneratedGradients
    dtypes.as_dtype(inp.dtype).name))
ValueError: Gradient type float32 generated for op name: "RNN/while/Switch_2"
op: "Switch"
input: "RNN/while/Merge_2"
input: "RNN/while/LoopCond"
attr {
  key: "T"
  value {
    type: DT_COMPLEX64
  }
}
attr {
  key: "_class"
  value {
    list {
      s: "loc:@RNN/while/Merge_2"
    }
  }
}
 does not match input type complex64
```

**Comment by girving** [comment]
The linked commit means TensorFlow now raises an exception for the complex case.  There were too many uses of the nonscalar real case, so that persists.

**Comment by jony0917** [comment]
Raising an exeception is not the best option, people will still be confused about why my code raises an exeception, tensorflow had better to make the definition of gradients clear.

https://github.com/tensorflow/tensorflow/issues/20613

**Comment by NEGU93** [comment]
> This is continued from #2255:
> 
> Differentiating a complex expression by a real value with `tf.gradients` should yield a complex value, but this doesn't seem to be the way that `tf.gradients` works at the moment.
> If I run
> 
> ```
> import tensorflow as tf
> import numpy as np
> 
> s = tf.Session()
> x = tf.placeholder(tf.float32)
> 
> z = tf.complex(0., x)
> 
> print('full', s.run(tf.gradients(z, [x]), feed_dict={x: 1}))
> print('real', s.run(tf.gradients(tf.real(z), [x]), feed_dict={x: 1}))
> print('imag', s.run(tf.gradients(tf.imag(z), [x]), feed_dict={x: 1}))
> ```
> 
> The output is
> 
> ```
> full [0.0]
> real [0.0]
> imag [1.0]
> ```
> 
> while I would have expected
> 
> ```
> full [0.0 + 1.0j]
> real [0.0]
> imag [1.0]
> ```
> 
> I suspect that `tf.gradients` always casts the final result to the type of the variable that we differentiate with respect to, which makes sense in many circumstances, but leads to incorrect behaviour in this case.

If you check the definition of the gradient I posted in [stackoverflow](https://stackoverflow.com/questions/57108959/how-does-tf-gradients-manages-non-holomorphic-functions/), the result you are having makes perfect sense.

As said, I still don't know WHY tensorflow uses that definition of the gradient but makes perfect sense for real scalar function wtf of complex variables.
