### ISSUE TITLE
Tensorflow v1.13.1 CUDA Compilation fails on Windows 10

### ISSUE THREAD

**Issue by MiguelAlgaba** [tensorflow/tensorflow#28184]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): source
- TensorFlow version: v1.13.1
- Python version: 3.7.0
- Installed using virtualenv? pip? conda?:
- Bazel version (if compiling from source): 0.21.0
- GCC/Compiler version (if compiling from source): 
- CUDA/cuDNN version: 7.5.1
- GPU model and memory: GeForce GTX1080 8Gb

**Describe the problem**

Tensorflow fails to build when configured to use CUDA

**Provide the exact sequence of commands / steps that you executed before running into the problem**

- Installed Python 3.7.0
	- With pip as optional feature
	- Adding Python to environment variables

- Installed MSYS2
	pacman -Syu
	pacman -Su
	pacman -S git patch unzip

- Installed Bazel 0.21.0
	- Downloaded bazel-0.21.0-windows-x86_64.exe
	- Renamed it to bazel.exe
	- Moved bazel.exe to C:\bazel (C:\bazel\bazel.exe)
	- Added C:\bazel to the user variables PATH
	- Added C:\msys64\usr\bin to user variables PATH
	- Added C:\msys64\usr\bin\bash.exe to a new BAZEL_SH user variable

- Installed CUDA 10.0

	- Downloaded and installed NVIDIA GeForce Experience to install NVIDIA GPU drivers v430.39 on GTX1080 card
	- Downloaded and installed CUDA Toolkit 10.0 from https://developer.nvidia.com/cuda-toolkit-archive
	- Downloaded and installed cuDNN SDK 7.5.1 for CUDA 10 from https://developer.nvidia.com/cudnn
		- Downloaded cudnn-10.0-windows10-x64-v7.5.1.10.zip from https://developer.nvidia.com/cudnn
		- Copied cuda\bin\cudnn64_7.dll to C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0\bin
		- Copied cuda\include\cudnn.h to C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0\include
		- Copied cuda\lib\x64\cudnn.lib to C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0\lib\x64
		- Checked CUDA_PATH was set to C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0
		- Added the following paths to the user environment variable PATH
           		C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0\bin
           		C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0\extras\CUPTI\libx64
          		C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0\include
           		C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0

- Installed Tensorflow dependencies

	pip3 install six numpy wheel
	pip3 install keras_applications==1.0.6 --no-deps
	pip3 install keras_preprocessing==1.0.5 --no-deps

- Downloaded and configured Tensorflow v.1.13.1 for CUDA support

	git clone https://github.com/tensorflow/tensorflow.git
	cd tensorflow
    	git checkout r1.13
	cd tensorflow
	bazel clean
	python ./configure.py

	When prompted “Do you wish to build TensorFlow with CUDA support?” selected “y”
	When prompted to specify the CUDA compute capabilitied, specified 3.5,6.1 (for GeForce GTX1080)

- Build command that fails

	bazel build --config=opt --config=cuda --define=no_tensorflow_py_deps=true //tensorflow/tools/pip_package:build_pip_package
	
**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

The following file contains the configure step of Tensorflow and the console log of the build command that fails for me:

[2019.04.26_tensorflow_1.13.1_cuda10_build_error_windows10.txt](https://github.com/tensorflow/tensorflow/files/3121627/2019.04.26_tensorflow_1.13.1_cuda10_build_error_windows10.txt)

**Comment by muddham** [comment]
@MiguelAlgaba As per the [link](https://www.tensorflow.org/install/source_windows#gpu) , TF 1.13.1 supports python 3.5 - 3.6 and try to install relevant Bazel,CUDA and cuDNN components. Please let us know how it progresses. Thanks!

**Comment by d3x0r** [comment]
I have been having issues building this.  From github repo; and I'm not sure if it's exactly the same issue...

    if os.path.isfile(python_bin_path) and os.access(python_bin_path, os.X_OK):
```
M:\javascript\tensorflow\node_modules\@tensorflow\tfjs-node\deps\tensorflow>bazel build --config=opt tensorflow/tools/pip_package:build_pip_package
WARNING: Ignoring JAVA_HOME, because it must point to a JDK, not a JRE.
INFO: Build options --action_env and --python_path have changed, discarding analysis cache.
INFO: Repository 'cython' used the following cache hits instead of downloading the corresponding file.
 * Hash 'bccc9aa050ea02595b2440188813b936eaf345e85fb9692790cecfe095cf91aa' for http://mirror.tensorflow.org/github.com/cython/cython/archive/0.28.4.tar.gz
If the definition of 'cython' was updated, verify that the hashes were also updated.
ERROR: C:/general/work3/javascript/tensorflow/node_modules/@tensorflow/tfjs-node/deps/tensorflow/third_party/py/numpy/BUILD:11:1: no such package '@local_config_python//': Tracebac
k (most recent call last):
        File "C:/general/work3/javascript/tensorflow/node_modules/@tensorflow/tfjs-node/deps/tensorflow/third_party/py/python_configure.bzl", line 344
                _create_local_python_repository(repository_ctx)
        File "C:/general/work3/javascript/tensorflow/node_modules/@tensorflow/tfjs-node/deps/tensorflow/third_party/py/python_configure.bzl", line 292, in _create_local_python_repo
sitory
                _check_python_bin(repository_ctx, python_bin)
        File "C:/general/work3/javascript/tensorflow/node_modules/@tensorflow/tfjs-node/deps/tensorflow/third_party/py/python_configure.bzl", line 234, in _check_python_bin
                _fail(("--define %s='%s' is not execut...)))
        File "C:/general/work3/javascript/tensorflow/node_modules/@tensorflow/tfjs-node/deps/tensorflow/third_party/py/python_configure.bzl", line 27, in _fail
                fail(("%sPython Configuration Error:%...)))
Python Configuration Error: --define PYTHON_BIN_PATH='C:/tools/Python27/python.exe' is not executable. Is it the python binary?
 and referenced by '//third_party/py/numpy:headers'
ERROR: Analysis of target '//tensorflow/tools/pip_package:build_pip_package' failed; build aborted: Analysis failed
INFO: Elapsed time: 7.875s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (267 packages loaded, 4593 targets configured)
    currently loading: tensorflow/lite/schema
```

Which is really just

```
Python Configuration Error: --define PYTHON_BIN_PATH='C:/tools/Python27/python.exe' is not executable. Is it the python binary?
```


``` py
def _check_python_bin(repository_ctx, python_bin):
    """Checks the python bin path."""
    cmd = '[[ -x "%s" ]] && [[ ! -d "%s" ]]' % (python_bin, python_bin)
    result = repository_ctx.execute([_get_bash_bin(repository_ctx), "-c", cmd])
    if result.return_code == 1:
        _fail("--define %s='%s' is not executable. Is it the python binary?" % (
            _PYTHON_BIN_PATH,
            python_bin,
        ))
```

I don't think [[-x]] works in command prompt... was there some bash shell I missed having to use?


tensorflow\third_party\py\python_configure.bzl

```
    python_bin = _get_python_bin(repository_ctx)
---    _check_python_bin(repository_ctx, python_bin)
+++    #_check_python_bin(repository_ctx, python_bin)
    python_lib = _get_python_lib(repository_ctx, python_bin)
---    _check_python_lib(repository_ctx, python_lib)
+++    #_check_python_lib(repository_ctx, python_lib)

```

Now I get up to it's truing to run patch with c:\windows\system32\bash.exe which is a WSL image that can't change directory to ....

```
Non-zero return code(2) when executing 'C:\WINDOWS\system32\bash.exe -l -c "patch" "-p1" "-d" "C:/users/panther/_bazel_panther/7dujpcn3/external/png_archive" "-i" "C:/general/work3
/javascript/tensorflow/node_modules/@tensorflow/tfjs-node/deps/tensorflow/third_party/png_fix_rpi.patch"':
Stdout:
Stderr: patch: **** Can't change to directory C:/users/panther/_bazel_panther/7dujpcn3/external/png_archive : No such file or directory
 and referenced by '//tensorflow/tools/pip_package:licenses'
```

**Comment by gadagashwini** [comment]
@MiguelAlgaba Were able to resolve the issue? Thanks!

**Comment by mihaimaruseac** [comment]
Also, note that there is now a Tensorflow 1.13.2 release which might have the build issue solved.

**Comment by jselstad** [comment]
(I was able to solve the `python.exe' is not executable. Is it the python binary?` issue by running the `bazel build` command from git Bash instead of Powershell.)

**Comment by gadagashwini** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
