### ISSUE TITLE
Building 2.0 from master branch using --config=v2 creating 1.13.1 version

### ISSUE THREAD

**Issue by md-k-sarker** [tensorflow/tensorflow#28198]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Centos 7
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): source 
- TensorFlow version: tried to 
- Python version: 3.5.2
- Installed using virtualenv? pip? conda?: pip
- Bazel version (if compiling from source): 0.24.1
- GCC/Compiler version (if compiling from source): 6.2.0
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

**Describe the problem**
Tried to build and install tensorflow 2.0 from master branch using --config=v2. It is building but the build version is 1.13.1. After installing the version it also shows 1.13.1 while run: `tf.__version__`

How can I build tensorflow 2.0 from master branch? 

**Provide the exact sequence of commands / steps that you executed before running into the problem**
```
bazel --output_base=$tf_deps/ build \ 
--config=v2 \ 
--copt="-O3" --copt="-g" -s -c opt \ 
//tensorflow/tools/pip_package:build_pip_package
```

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached. 
```
import tensorflow as tf
tf.__version__
1.13.1
```

**Comment by freedomtan** [comment]
With `--config=v2`, you get TensorFlow 2.0. The `tf.__version__` is not updated though.  Check something like `tf.version` to see if you are using `tensorflow._api.v2`

**Comment by md-k-sarker** [comment]
Thanks. got it. 
So when using --config=v2 on master branch it builds both v1 and v2 and v2 is enabled by default.

**Comment by md-k-sarker** [comment]
Thanks. 
[Official documentation](https://www.tensorflow.org/tensorboard/r2/graphs) is saying to check version using tf.__version__ . It did not say to check tf.version. 

**In fact while testing I am not finding tensorflow 2.0 functionalities in this binary.** 

Using tf.version it shows: 
```
>>> tf.version
<module 'tensorflow._api.v2.version' from '/nfs/site/home/xxxxx/anaconda/envs/py352_tf2.0.0a0_pre_compiled/lib/python3.5/site-packages/tensorflow/_api/v2/version/__init__.py'>
```
If I try to run the experiment mentioned in [official doc](https://www.tensorflow.org/tensorboard/r2/graphs), especially this line:
```
tensorboard_callback = keras.callbacks.TensorBoard(log_dir=logdir)
```
it says 
```
File "xxxx.py", line yy, in <module>
    tb_callback = keras.callbacks.Tensorboard(log_dir=logdir,
AttributeError: module 'tensorflow.python.keras.api._v2.keras.callbacks' has no attribute 'Tensorboard'
```
That means although it is showing v2 using tf.version it does not have tf2.0 funcationalities. 

So what would be the way to get 2.0 functionalities by building from master branch source (not using the 2.0 release branch)?
