### ISSUE TITLE
while_loop inside @tf.contrib.eager.defun only loop once

### ISSUE THREAD

**Issue by yuanqing-wang** [tensorflow/tensorflow#28197]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): OSX 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 1.13
- Python version: 3.6
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
`tf.while_loop` only loops once
**Describe the expected behavior**
`tf.while_loop` only loops more than once
**Code to reproduce the issue**
```
@tf.contrib.eager.defun
def fn():
    idx = 0
    max_iter = 5
    
    def loop_body(idx):
        print('loop once')
        return idx + 1
    
    tf.while_loop(
        lambda idx: idx < max_iter,
        lambda idx: loop_body(idx),
        [idx]
        )
    
    
fn() # -> only printed once
```
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by allenlavoie** [comment]
You can use `tf.print` instead, which will print every time the loop body executes. `print` will only run while building the TensorFlow graph.

**Comment by yuanqing-wang** [comment]
but the value of `idx` remains `0` after the whole thing

```
@tf.contrib.eager.defun
def fn():
    idx = 0
    max_iter = 5
    
    def loop_body(idx):
        tf.print('loop once')
        return idx + 1
    
    tf.while_loop(
        lambda idx: idx < max_iter,
        lambda idx: loop_body(idx),
        [idx]
        )
    
    print(idx) # ==> 0
    
    
fn()
```

**Comment by allenlavoie** [comment]
`while_loop` returns the updated value as a Tensor. Or you can use AutoGraph and write this as a normal Python for loop; if you're looping over a Tensor value like `tf.range` it'll manage this stuff for you.

**Comment by yuanqing-wang** [comment]
thanks!

what I provided above was a minimal working example. what I wanted to do was to use `tf.while_loop` to update several values in a matrix.

```
    idx = 0
    max_iter = tf.shape(double_bond_idxs)[0]
    
    def loop_body(idx):
        # get the double bond idx
        chr_idx = double_bond_idxs[idx]

        # change the bond order in the adjaceny map to 2
        adjacency_map[chr_idx, chr_idx + 1].assign(
            tf.constant(2, dtype=tf.float32))
        
        return idx + 1
```
I wanted to put `2` into the position `[chr_idx, chr_idx + 1]` of my `adjacency_map` Variable, based on the values in `double_bond_idxs`. Would `tf.while_loop` in this case be appropriate? Or to be more general, what would be the best way to put values in a matrix variable at certain positions recorded in a `Tensor`?

Thanks!

Also, we I don't put my function under `@tf.contrib.eager.defun` it worked fine, and had my desired property, but it's just slow.

**Comment by allenlavoie** [comment]
More efficient to use something like `scatter_nd_update`:

```
v = tf.Variable(tf.ones([5, 5]))
indices = tf.tile(tf.range(tf.shape(v)[0])[:, tf.newaxis], [1, 2])
values = tf.tile([2.], [tf.shape(v)[0]])
v.scatter_nd_update(indices, values)
```

That'd set the diagonal, but you can change `indices` to be whatever you want.

**Comment by yuanqing-wang** [comment]
Thanks! But is there a way to modify an object multiple times using a `tf.while_loop` under `@tf.distribution.eager.defun`?

**Comment by yuanqing-wang** [comment]
something like this:

```
@tf.contrib.eager.defun
def fn():
    counter = tf.Variable(0, dtype=tf.int32)
    
    idx = 0
    max_iter = 5
    
    def loop_body(idx):
        counter = counter + 1
        return idx + 1
    
    tf.while_loop(
        lambda idx: idx < max_iter,
        lambda idx: loop_body(idx),
        [idx]
        )
    
    print(counter)
    
    
fn()
```

note that this works fine if there's no `@tf.contrib.eager.defun`

**Comment by allenlavoie** [comment]
You can use `variable.assign` in the loop body, just add a control dependency to one of the loop outputs.

**Comment by achandraa** [comment]
@yuanqing-wang : Did you get chance to try @allenlavoie's suggestion. Please let us know. Thanks!

**Comment by yuanqing-wang** [comment]
@achandraa yes, it works, but control dependency is indeed needed.

**Comment by achandraa** [comment]
@yuanqing-wang : Good to know that it worked for you. We will be happy to help in case you get any other related issues. Thanks!
