### ISSUE TITLE
404 error on TensorFlow Lite model repository

### ISSUE THREAD

**Issue by 1330154737** [tensorflow/tensorflow#28203]
<em>Please make sure that this is a documentation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:doc_template</em>

**System information**
- TensorFlow version:
- Doc Link:

**Describe the documentation issue**
This link is unreachable
```
Table 1: Top-1 accuracy of floating point and fully quantized CNNs on Imagenet Validation dataset.
Our pre-trained models are available in the TensorFlow Lite model repository. The code used to generate these models is available.
```

**We welcome contributions by users. Will you be able to update submit a PR (use the [doc style guide](https://www.tensorflow.org/community/documentation)) to fix the doc Issue?**

**Comment by achandraa** [comment]
@1330154737 : Unfortunately did not get the link. Can you please provide the link to check the issue. Thanks!
