### ISSUE TITLE
Can't convert to Tensorflow Lite with operation Cast

### ISSUE THREAD

**Issue by futuyao** [tensorflow/tensorflow#28206]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 16.04
- TensorFlow installed from (source or binary): binary
- TensorFlow version (or github SHA if from source): 1.12.0

**Provide the text output from tflite_convert**

```
Traceback (most recent call last):
  File "predict_tflite.py", line 740, in <module>
    evaluatePlanes(args)
  File "predict_tflite.py", line 95, in evaluatePlanes
    predictions = getResults(options)
  File "predict_tflite.py", line 289, in getResults
    pred_dict = getPredictionCustom(options)
  File "predict_tflite.py", line 538, in getPredictionCustom
    tflite_model = converter.convert()
  File "/home/alexfu/PlaneNet/venv/local/lib/python2.7/site-packages/tensorflow/contrib/lite/python/lite.py", line 453, in convert
    **converter_kwargs)
  File "/home/alexfu/PlaneNet/venv/local/lib/python2.7/site-packages/tensorflow/contrib/lite/python/convert.py", line 342, in toco_convert_impl
    input_data.SerializeToString())
  File "/home/alexfu/PlaneNet/venv/local/lib/python2.7/site-packages/tensorflow/contrib/lite/python/convert.py", line 135, in toco_convert_protos
    (stdout, stderr))
RuntimeError: TOCO failed see console for info.
2019-04-27 02:28:16.893332: I tensorflow/contrib/lite/toco/graph_transformations/graph_transformations.cc:39] Before Removing unused ops: 1517 operators, 2341 arrays (0 quantized)
2019-04-27 02:28:16.938974: I tensorflow/contrib/lite/toco/graph_transformations/graph_transformations.cc:39] Before general graph transformations: 1517 operators, 2341 arrays (0 quantized)
2019-04-27 02:28:16.939290: F tensorflow/contrib/lite/toco/graph_transformations/resolve_constant_unary.cc:164] Unsupported cast op input type
Aborted (core dumped)

None
```

Also, please include a link to a GraphDef or the model if possible.
https://mega.nz/#!sjpT2DiQ!Uo-6hxyldmtnPoKk3TTdUHKZADRGy6nIPlmAeVzJs_8
(Actually using DeepLab in this model)

**Any other info / logs**

Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by achandraa** [comment]
@futuyao : Did you get chance to have a look on this [link](https://www.tensorflow.org/lite/guide/ops_compatibility). Let us know if that helps. Thanks!

**Comment by futuyao** [comment]
Cast is a supported operation. But in my model, I'm using operation Cast with input type Bool and output type float32. I'm not sure if the casting from input type Bool is supporter. Do you have more information on this?

More details here at line 234 at tensorflow/lite/toco/graph_transformations/resolve_constant_unary.cc:
```
if (unary_op->type == OperatorType::kCast) {
    for (int i = 0; i < output_buffer_size; i++) {
      float outval = 0.0f;
      if (input_array.buffer->type == ArrayDataType::kFloat) {
        outval = static_cast<float>(
            input_array.GetBuffer<ArrayDataType::kFloat>().data[i]);
      } else if (input_array.buffer->type == ArrayDataType::kUint8) {
        outval = static_cast<float>(
            input_array.GetBuffer<ArrayDataType::kUint8>().data[i]);
      } else if (input_array.buffer->type == ArrayDataType::kInt32) {
        outval = static_cast<float>(
            input_array.GetBuffer<ArrayDataType::kInt32>().data[i]);
      } else if (input_array.buffer->type == ArrayDataType::kInt64) {
        outval = static_cast<float>(
            input_array.GetBuffer<ArrayDataType::kInt64>().data[i]);
      } else {
        LOG(FATAL) << "Unsupported cast op input type";
      }
      output_float_data[i] = outval;
    }
```

**Comment by SanthoshRajendiran** [comment]
@futuyao  I think cast operation does not support bool input.

**Comment by futuyao** [comment]
> @futuyao I think cast operation does not support bool input.

I've made a small change to the converter code, and it should support bool after the fix. See #28315 .

**Comment by gadagashwini** [comment]
@futuyao Can you submit this PR against master? . Thanks!

**Comment by gadagashwini** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Comment by ksevta** [comment]
> > @futuyao I think cast operation does not support bool input.
> 
> I've made a small change to the converter code, and it should support bool after the fix. See #28315 .

I am facing the same issue while converting model to TFLite. can you please tell how you solved it?

**Comment by ablenesi** [comment]
This issue is now fixed on master, try converting with RC 2 toco.
