### ISSUE TITLE
Deprecation warning in ctc_batch_cost function (python/keras/backend.py)

### ISSUE THREAD

**Issue by arthurflor23** [tensorflow/tensorflow#28200]
This template is for miscellaneous issues not covered by the other issue categories.

For questions on how to work with TensorFlow, or support for problems that are not verified bugs in TensorFlow, please go to [StackOverflow](https://stackoverflow.com/questions/tagged/tensorflow).

If you are reporting a vulnerability, please use the [dedicated reporting process](https://github.com/tensorflow/tensorflow/blob/master/SECURITY.md).

For high-level discussions about TensorFlow, please post to discuss@tensorflow.org, for questions about the development or internal workings of TensorFlow, or if you would like to know how to contribute to TensorFlow, please post to developers@tensorflow.org.

OS: Arch linux
Tensorflow: 2.0.0alpha0

WARNING: Logging before flag parsing goes to stderr. 
W0426 20:17:50.524740 140527476778624 deprecation.py:323] From /python3.7/site-packages/tensorflow/python/keras/backend.py:5151: to_int32 (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version. 
Instructions for updating:
Use `tf.cast` instead.

W0426 20:17:50.689021 140527476778624 deprecation.py:323] From /python3.7/site-packages/tensorflow/python/keras/backend.py:5130: to_int64 (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.cast` instead.

**Comment by achandraa** [comment]
@arthurflor23 : Please give us some more details on the issue you are facing. Thanks!

**Comment by arthurflor23** [comment]
Hi! Sorry, but It's more the prevention of the bug, considering that the functions to_int32 and to_int64 will be removed in a future version.

**Comment by ymodak** [comment]
Apologies but I am having trouble understanding your query. Are you asking to add deprecation warning to ```ctc_batch_cost``` function ? In that case its not required since we have included this function in TF 2.0 
Also deprecation warnings for ```to_int32``` and ```to_int64`` functions look correct. Please let me know if I am missing something. Thanks!

**Comment by arthurflor23** [comment]
That's right, will this be updated at some point? I think I made a mistake then, sorry
