### ISSUE TITLE
tf.tuple can't be indexed with tensor in graph mode

### ISSUE THREAD

**Issue by breadbread1984** [tensorflow/tensorflow#28219]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.0.0.dev20190427
- Python version: 3.6.7
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**

the tf.tuple can't be indexed by tensor in graph mode.

**Describe the expected behavior**

tf.tuple should support index with tensor in graph mode.

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

```python
import tensorflow as tf;

@tf.function
def func(a):
    i = tf.constant(0);
    return a[i];

t = tf.tuple([tf.constant(0),tf.constant(1)]);
a = func(t);
```
**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by captain-pool** [comment]
You can use `tf.gather()` or `tf.gather_nd()`.

**Comment by breadbread1984** [comment]
I tried the following code and failed.

```python
import numpy as np;
import tensorflow as tf;

@tf.function
def get(t, indices):
    return tf.gather(t, indices);

t = tf.tuple([tf.constant(np.random.normal(size = (3,4))), tf.constant(np.random.normal(size=(4,5)))]);
indices = tf.constant([0]);
a = get(t,indices);
```

The error message is
>ValueError: Tried to convert 'params' to a tensor and failed. Error: Dimension 0 in both shapes must be equal, but are 3 and 4. Shapes are [3,4] and [4,5].

**Comment by captain-pool** [comment]
@jsimsa is there any known method for handling this?
The `Pack` Operation is raising this error, in `tf.gather()` and `tf.slice()`.

**Comment by jsimsa** [comment]
Wrapping `t` in `convert_to_tensor` does the trick:

```
import tensorflow as tf;

tf.enable_v2_behavior()

@tf.function
def func(a):
    i = tf.constant(0);
    return a[i];
    #return tf.slice(a, [0], [1])[0];

t = tf.tuple([tf.constant(0),tf.constant(1)]);
print(t[0].numpy())  # prints 0
a = func(tf.convert_to_tensor(t));
print(a.numpy())  # prints 0
```

**Comment by breadbread1984** [comment]
tf.tuple as a tensorflow utility should support being index by tensor. otherwise, it has nothing difference from python's tuple. without index by tensor function, the following problem can't be solved.

```python
import numpy as np;
import tensorflow as tf;

@tf.function
def get(t, index):
    return t[index];

t = tf.tuple([tf.constant(np.random.normal(size = (3,4))), tf.constant(np.random.normal(size=(4,5)))]);
index = tf.constant(0);
a = get(t,index);
```

**Comment by ymodak** [comment]
Closing this issue since jsimsa has provided a workaround. Feel free to reopen this issue if have further questions or perhaps open a feature request to add this functionality if necessary. Thanks!
