### ISSUE TITLE
Inspecting the Tensorflow 2.0 python package: unable to find or import modules

### ISSUE THREAD

**Issue by galeone** [tensorflow/tensorflow#28214]
I'm analyzing the Tensorflow 2.0 Python package using `importlib` to loop through the symbols of the tensorflow package (see: https://github.com/galeone/rtf/blob/master/rtf/generators/base.py#L72 ).

There are certain modules that `importlib` is not able to load or find, e.g. the `tf.losses` `tf.keras.losses`, `tf.optmizers` (and all the module alias) etc. So far, recursively using `importlib.import_module` I get this structure

```
.
├── autograph
├── compat
│   ├── v1
│   │   ├── autograph
│   │   ├── config
│   │   ├── data
│   │   ├── distribute
│   │   ├── estimator
│   │   ├── io
│   │   ├── keras
│   │   │   ├── applications
│   │   │   ├── datasets
│   │   │   ├── mixed_precision
│   │   │   ├── optimizers
│   │   │   ├── preprocessing
│   │   │   └── wrappers
│   │   ├── layers
│   │   ├── lite
│   │   │   └── experimental
│   │   ├── lookup
│   │   ├── nn
│   │   ├── random
│   │   ├── saved_model
│   │   ├── tpu
│   │   ├── train
│   │   └── xla
│   └── v2
│       ├── autograph
│       ├── config
│       ├── data
│       ├── distribute
│       ├── estimator
│       ├── io
│       ├── keras
│       │   ├── applications
│       │   ├── datasets
│       │   ├── mixed_precision
│       │   ├── optimizers
│       │   ├── preprocessing
│       │   └── wrappers
│       ├── lookup
│       ├── random
│       ├── tpu
│       ├── train
│       └── xla
├── config
├── data
├── distribute
├── estimator
├── io
├── keras
│   ├── applications
│   ├── datasets
│   ├── mixed_precision
│   ├── optimizers
│   ├── preprocessing
│   └── wrappers
├── lite
│   ├── experimental
│   │   └── examples
│   │       └── lstm
│   ├── python
│   │   └── optimize
│   └── toco
├── lookup
├── random
├── tools
│   └── docs
├── tpu
├── train
└── xla
```

that is incomplete.

Is there a way to use the `importlib` module to get the complete structure of the tensorflow package and to successfully load the module?

Here's a minimum reproducible example:

## Install

```
pip install --upgrade tf-nightly-2.0-preview
```

## Loading losses

```python
import importlib 
importlib.import_module("tensorflow.losses")
```

Produces the error: "ModuleNotFoundError: No module named 'tensorflow.losses'"

This happens only in Tensorflow 2.0, if I install Tensorflow 1.14 I can inspect more or less every package without any failure (haven't tested in depth).

Disclosure: this is a crosspost from https://groups.google.com/a/tensorflow.org/forum/#!topic/developers/jibh60HPGA0

Greetings

**Comment by muddham** [comment]
@galeone Request you to please refer the [link 2.0](https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/losses) and use the built in loss functions.
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.If you think we've misinterpreted a bug, please comment again with a clear explanation, as well as all of the information requested in the [issue template](https://github.com/tensorflow/tensorflow/issues/new/choose). Thanks!

**Comment by galeone** [comment]
Hi,
This is an "other issue", I opened it using the template for "other issues".

There is no built-in loss function, and it is not a StackOverflow question
since it is not about how to use Tensorflow.

The question is: why is impossible to import using Python importlib certain
modules of the Tensorflow package in Tensorflow 2.0?

Making the module inspectable and usable from Python is something that was
possible in Tensorflow 1.14 but is no more possible in 2.0.

I guess this is classifiable as a bug since it makes impossible to use the
library in this particular case.

(I'm from my mobile, sorry for the typos and any other monstrosity)

**Comment by mihaimaruseac** [comment]
Through investigation so far, it seems that this is fooled by the Lazy loaders we are using. Need to investigate more and see if we can fix it.

**Comment by galeone** [comment]
Yes, I can confirm. I analyzed the source code a bit, and I found a lot of magic happening in a `v2/api.py` file (or something similar, I don't remember exactly), explicitly saying that lazy loaders are being used

**Comment by gunan** [comment]
Adding @yifeif.
@galeone could you share your use case with us, maybe then we can see where exactly the problem is. or how to work around it.

**Comment by galeone** [comment]
The use case is the inspection of the tensorflow package (tensorflow==2.0.0beta1) using reflection.

I need this because I'm working on a project that has the goal of emulating the same TensorFlow structure (packages, sub-packages, classes, and so on) and creating a new Python package that has the same structure. __[*]__

If you have some minute, you can have a look at the file: https://github.com/galeone/rtf/blob/master/rtf/generators/base.py

If the package is `tensorflow` I got the result I posted on the opening post. I can inspect many sub-modules, but most of them are impossible to reach and inspect (`tf.keras.losses`, `tf.losses`, `tf.optimizers`, ...).

__[*]__The goal of the project is to have a Python package, that has the same structure of the TensorFlow package, but that instead of locally executing the commands on the current machine, has every class/method/function reimplemented as a gRPC call, in order to remote execute TensorFlow

**Comment by gunan** [comment]
One thing I can recommend is, our python API is actually documented here:
https://github.com/tensorflow/tensorflow/tree/master/tensorflow/tools/api/golden

Would the documented API be useful?

**Comment by gunan** [comment]
Also, the tools to generate this API is also right here:
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/api/lib/python_object_to_proto_visitor.py

Could you try this tool out to see if it works better for you?

**Comment by galeone** [comment]
This folder ( https://github.com/tensorflow/tensorflow/tree/master/tensorflow/tools/api/golden/v2 ) contains, perhaps, everything I need. Can you confirm that this is the TF 2 Python API completely described as protobuf? I mean: these files can be parsed and I can get the complete hierarchy of the tensorflow==2.0.0beta1 package I'm using?

The API generator, instead, look useful but I'm not sure on how to use it to get the complete hierarchy in the format I need. Searching in the repository I can only find a single usage in a test
 https://github.com/tensorflow/tensorflow/blob/a45a9d2ac8862b8f7162f6189ab567ed194c02b7/tensorflow/tools/api/tests/api_compatibility_test.py#L314

**Comment by gunan** [comment]
I can confirm that for any given commit, these files will give you the full TF API. We have continuous tests, and presubmit tests that prevent these files and the TF api going out of sync.

The api symbols stored in these files are using this protocol buffer:
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/api/lib/api_objects.proto#L37

**Comment by galeone** [comment]
This is great and it will help me **a lot**. 

Also from what I can see from the test I linked, using the visitor is not that difficult and it looks like I can use it to build `TFAPIObject` messages just buy looping over the files and post-process them
https://github.com/tensorflow/tensorflow/blob/a45a9d2ac8862b8f7162f6189ab567ed194c02b7/tensorflow/tools/api/tests/api_compatibility_test.py#L341 

right?

**Comment by gunan** [comment]
As far as I know, you are correct.
@annarev just in case something has changed since I last touched that code.

**Comment by yifeif** [comment]
Does something like the following work for your usecase @galeone?
tf = importlib.import_module("tensorflow")
getattr(tf, "losses")

**Comment by galeone** [comment]
@yilei this approach seems to work!

But why is this happening? I mean: I can't load `"tensorflow.losses"` using `importlib.import_module` but I can load the losses package using `getattr`. Is this something related to the lazy loading of the modules?

Moreover, having it working using `getattr` and not using `import_module` is an expected behavior?

**Comment by mihaimaruseac** [comment]
Hi,

Yes, lazy loading makes the modules only available via `getattr`

You can also try looking into `sys.modules`, even if the module is lazy loaded it should be as a key there (though probably not all of its submodules)

**Comment by Saduf2019** [comment]
@galeone 
Please let us know if this is still an issue.

**Comment by galeone** [comment]
@Saduf2019 no more an issue :+1:

**Comment by Saduf2019** [comment]
@galeone 
Thank you for your update, glad to hear its not an issue anymore.
