### ISSUE TITLE
max_pool_with_argmax index calculation

### ISSUE THREAD

**Issue by mwalton** [tensorflow/tensorflow#2821]
max_pool_with_argmax returns an argmax array which doesn't seem to account for the batch dimension. That is, the op returns the flattened index as: (height * width + x) * channels + c instead of ((b * height + y) * width + x) * channels + c as indicated in the API

**Comment by sherrym** [comment]
Could you please cut and paste the code that you believe is doing this incorrectly?

Could you please also include a unit test demonstrating the problem? Thanks.

**Comment by aselle** [comment]
Automatically closing because there was no response. Please reopen if it is still an issue.
