### ISSUE TITLE
The Nadam optimizer is non-deterministic due to a race condition related to inter_op_parallelism_threads

### ISSUE THREAD

**Issue by koute** [tensorflow/tensorflow#28215]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes.
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Arch Linux
- TensorFlow installed from (source or binary): Arch Linux repositories
- TensorFlow version (use command below): 'unknown' 1.13.1
- Python version: 3.7.3
- GPU model and memory: None. I'm running on CPU.

**Describe the current behavior**

When `inter_op_parallelism_threads` is set to `1` the `iterations` variable in Nadam optimizer from `tensorflow/python/keras/optimizers.py` always starts at `1` when the optimizer is executed; when `inter_op_parallelism_threads` is higher than `1` then `iterations` sometimes starts as `0`. The higher the `inter_op_parallelism_threads` is set to the higher the chance that `iterations` will start at `0` instead of at `1`.

(I know this because I `tf.Print`'d everything inside of the Nadam optimizer.)

This makes the training results non-deterministic since the Nadam optimizer depends on the current iteration number when calculating the weight updates.

**Describe the expected behavior**

The Nadam optimizer will be deterministic.

**Code to reproduce the issue**

```python
#!/usr/bin/python

import tensorflow as tf;
import numpy as np;

constant = tf.keras.initializers.constant;

inter_op_parallelism_threads = 1
# inter_op_parallelism_threads = 20

session_conf = tf.ConfigProto(intra_op_parallelism_threads=1, inter_op_parallelism_threads=inter_op_parallelism_threads)
graph = tf.get_default_graph()
session = tf.Session(graph=graph, config=session_conf)
tf.keras.backend.set_session(session)

optimizer = tf.keras.optimizers.Nadam(lr=1.0, beta_1=0.9, beta_2=0.999, epsilon=1e-7)

bias = constant(np.array([1.0]))
weights = constant(np.array([1.0]))
layer = tf.keras.layers.Dense(1, bias_initializer=bias, kernel_initializer=weights, input_shape=(1,))

model = tf.keras.Sequential()
model.add(layer)
model.compile(optimizer=optimizer, metrics=["accuracy"], loss=["mean_squared_error"])

input = np.array([1.0])
output = np.array([1.0])
model.train_on_batch(input, output)

w = layer.get_weights()
print(w)
```

Output when `inter_op_parallelism_threads` is set to 20 (so `iterations` starts at `0`):

```
[array([[-0.0564518]], dtype=float32), array([-0.0564518], dtype=float32)]
```

Output when `inter_op_parallelism_threads` is set to 1 (so `iterations` starts at `1`):

```
[array([[-0.49368942]], dtype=float32), array([-0.49368942], dtype=float32)]
```

**Comment by achandraa** [comment]
@koute : I have tried to reproduce the issue on colab (tf1.13.1) but unfortunately I am able to get the same result in both the cases mentioned (inter_op_parallelism_threads = 1 or inter_op_parallelism_threads = 20). Please let us know if it is still an issue. Thanks!

**Comment by koute** [comment]
@achandraa Yes. I have no idea why it doesn't reproduce on colab; it does locally on my PC every time I run it. It's a race condition though, so I'm not surprised.

It does reproduce in a different way on colab though. Select "GPU" in "Runtime" -> "Change runtime type" and you'll always hit the case where `iterations` starts at `0` (so you'll get `-0.05648327`; it's not exactly the same as in my original reproduction most likely due to the fact that now it's running on the GPU instead of the CPU); if you select "None" then you'll always hit the case when `iterations` starts at `1` (so you'll get `-0.49368942` as result). I believe the root cause of this should be the same as my original issue.

**Comment by achandraa** [comment]
@koute : Tried in Colab (GPU runtime) as suggested but got the same result for cases where inter_op_parallelism_threads = 0 or inter_op_parallelism_threads = None which is [array([[-0.05648327]], dtype=float32), array([-0.05648327], dtype=float32)]. And this is on tensorflow version 1.13.1. Can you try and let us know whether you are getting different on Colab with same environment. Thanks!

**Comment by koute** [comment]
@achandraa Yes, you're getting the same results as I do. Now change the runtime to CPU, and you'll always get `-0.49368942`.

I'll reiterate what I said - on Colab the original issue does not reproduce in the way as originally described, i.e. the parallelism settings do not matter, but it does reproduce in a different way. Here's a handy table:

```
| Runtime | initial value of iterations | Result      |
| --------------------------------------------------- |
| CPU     | 1                           | -0.49368942 |
| GPU     | 0                           | -0.05648327 |
| --------------------------------------------------- |
```

The results on both runtimes should be the same. I believe the root cause of this problem should be the same as the root cause of my original problem.

**Comment by achandraa** [comment]
I got following output while running on different runtimes on Colab with version 1.13.1 :

| Runtime | initial value of iterations | Result        |
| ------------------------------------------------------------   |
| CPU       | 1                                 | -0.0564518   |
| GPU       | 0                                 | -0.05648327 |
| ------------------------------------------------------------   | 

This is what we are referring to ?

**Comment by koute** [comment]
So you're getting the same values on both the CPU and the GPU runtime? This is really strange. Because that's not what I am getting. Are you perhaps getting assigned a slightly different environment on Colab or something like that? (I'm not really too familiar with how exactly it works.)

Here are the screenshots of my results:

CPU results - https://imgur.com/eqhsNTn
GPU results - https://imgur.com/dj2uxNg

This is on the default Colab environment in a fresh Python 3 notebook.

**Comment by achandraa** [comment]
After checking again and trying on default Colab environment in a fresh Python 3 notebook with TensorFlow version 1.13.1,  I was able to reproduce the issue with the outputs you have provided. Below  are the result : 

Runtime : CPU
Initial value of iterations : 1
Result : -0.49368942

Runtime : GPU
Initial value of iterations : 0
Result : -0.05648327

**Comment by Saduf2019** [comment]
@koute 

Please post this issue on [keras-team/keras repo.](https://github.com/keras-team/keras/issues)
To know more see;
https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999
