### ISSUE TITLE
AttributeError: module 'tensorflow' has no attribute 'keras'

### ISSUE THREAD

**Issue by 007fred50** [tensorflow/tensorflow#28213]
Hello,

I have a question i can't compile while i have installed:
tensorflow                2.0.0a0
Keras                     2.2.4

I got error:
AttributeError: module 'tensorflow' has no attribute 'keras'

my Code:
import tensorflow as tf
mnist = tf.keras.datasets.mnist

I'm in Mac OS X 10.14

Somthing i do wrong?

**Comment by 007fred50** [comment]
Hello,

i found it the fix was. in Mac OS (cd ~/) there are a folder named tensorflow
inside homefolder. you create a file named: test.py

my Code:
import tensorflow as tf
mnist = tf.keras.datasets.mnist

I'm in Mac OS X 10.14

And it works now. i think you need to have the folder (cd ~/tensorflow)

**Comment by 007fred50** [comment]
Hello,

If you change the file name to (tensorflow.py)
it'll come with error:
AttributeError: module 'tensorflow' has no attribute 'keras'

**Comment by ymodak** [comment]
Thanks for trying TF 2.0 alpha. Naming a script tensorflow.py messes up importing tf modules. Thus it is not a recommended naming convention.

**Comment by Manasmalhotra** [comment]
I am facing error AttributeError: module 'tensorflow' has no attribute 'keras' in windows,please tell what to do

**Comment by 007fred50** [comment]
what is your python file name?

**Comment by Manasmalhotra** [comment]
Thanks for your reply to my query, but I got the solution to it, a file in
the same folder was named tensorflow by me.
