### ISSUE TITLE
InvalidArgumentError: logits and labels must have the same first dimension

### ISSUE THREAD

**Issue by Bornlex** [tensorflow/tensorflow#28226]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Google Colab
- TensorFlow installed from (source or binary): 1.13
- TensorFlow version (use command below): 1.13
- Python version: 3.6

**Describe the current behavior**
I have created a dataset and I am trying to feed it to my model. Here is the shape:
`<DatasetV1Adapter shapes: ((1, ?, ?, ?), (1, 50)), types: (tf.uint8, tf.float32)>`

I constructed it pretty simply from a pandas.DataFrame:
```python
filenames_ds = tf.data.Dataset.from_tensor_slices(categ_img[:1000]['image_name'])
labels_ds    = tf.data.Dataset.from_tensor_slices(categ_img[:1000]['category_label'])
images_ds    = filenames_ds.map(lambda x: tf.image.decode_jpeg(tf.read_file(x)))
labels_ds    = labels_ds.map(lambda x: tf.one_hot(x, NUM_CATEGORIES))
ds = tf.data.Dataset.zip((images_ds, labels_ds))
ds = ds.apply(tf.contrib.data.batch_and_drop_remainder(1))
```

I am feeding it to a ResNet-based network. However, I keep getting this error:
```
InvalidArgumentError: logits and labels must have the same first dimension, got logits shape [1,50] and labels shape [50]
```

I also tried to create the dataset slightly differently (this line replaces the old labels_ds line):
```python
labels_ds    = labels_ds.map(lambda x: tf.expand_dims(tf.one_hot(x, NUM_CATEGORIES), axis=0))
```

So the shape is now:
`<DatasetV1Adapter shapes: ((1, ?, ?, ?), (1, 1, 50)), types: (tf.uint8, tf.float32)>`

But the error is exactly the same. Nothing changed.

I don't know what to do exactly. Here is the model, in case it matters:
```python
base_model = ResNet50(weights='imagenet', include_top=False, input_shape=(None, None, 3))
for layer in base_model.layers:
    layer.trainable = False
x = base_model.output
x = GlobalAveragePooling2D()(x)
    
for fc in FC_LAYERS:
    x = Dense(fc, activation='relu')(x)
    x = Dropout(DROPOUT)(x)
    
output    = Dense(NUM_CATEGORIES, activation='softmax', name='fully-connected')(x)
model     = Model(inputs=base_model.input, outputs=output)
optimizer = tf.keras.optimizers.SGD(lr=LEARNING_RATE)
cce       = tf.keras.losses.CategoricalCrossentropy()
    
model.compile(optimizer, loss=cce)
return model
```

I already asked on [StackOverflow](https://stackoverflow.com/questions/55855543/invalidargumenterror-logits-and-labels-must-have-the-same-first-dimension?noredirect=1#comment98380254_55855543) but no answer.

Can someone tell me if I am doing something wrong (very likely) or if this is a bug please?

Thank you for your help.
This is my first Github issue, so do not hesitate to tell me if I need to improve, adapt, change something.

Thanks guys.

**Comment by muddham** [comment]
@Bornlex Please refer the links [1](https://stackoverflow.com/questions/34519423/tensorflow-error-logits-and-labels-must-be-same-size), [2](https://stackoverflow.com/questions/49161174/tensorflow-logits-and-labels-must-have-the-same-first-dimension). This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.If you think we've misinterpreted a bug, please comment again with a clear explanation, as well as all of the information requested in the [issue template](https://github.com/tensorflow/tensorflow/issues/new/choose). Thanks!

**Comment by Bornlex** [comment]
Of course. Thank you for your answer.

I found out that I might have missed something.
The following line made things work:

```python
model.compile(loss='categorical_crossentropy', optimizer=optimizer, metrics=['accuracy'])
```

I have no idea why though. Thank you anyway.
