### ISSUE TITLE
tf.batch_gather with higher dimensional indices for one batch

### ISSUE THREAD

**Issue by VincentStimper** [tensorflow/tensorflow#28229]
**System information**
- TensorFlow version (you are using): 1.13
- Are you willing to contribute it (Yes/No): Yes

**Describe the feature and the current behavior/state.**
`tf.batch_gather` is currently able to handle an arbitrary number of batch dimensions, but there is only one dimension of the indices of a single batch. I needed higher dimensional indices for one batch for my purposes, so I extended the `tf.batch_gather` function (see https://github.com/VincentStimper/tf-batch-gather-extension).

**Will this change the current api? How?**
One would need to pass an axis to `tf.batch_gather` since this cannot be inferred form the dimensions of `params` and `indices`, but axis could be `None` by default causing the function to act as originally implemented.

**Who will benefit with this feature?**
Everyone with specific requirements to gather elements from tensors by indices.

**Comment by alextp** [comment]
So you want something like batch_dims in gather_nd? Look at [the docs for gather_nd](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/ops/array_ops.py#L3527) on the tree and see if it solves your problem.

**Comment by VincentStimper** [comment]
No, in `tf.gather_nd` you slice multiple axis of the `params` tensor, but I want to slice only along one axis, but with a higher dimensional index to get a higher dimensional result. This can be done in the `tf.gather` function, which is unfortunatly not able to deal with batch axes. To understand what I mean have a look at my repo https://github.com/VincentStimper/tf-batch-gather-extension where I implemented an solution, please.

**Comment by yangysc** [comment]
Yeah, it's very useful, thanks! @VincentStimper

**Comment by alextp** [comment]
There is tf.batch_gather / tf.gather(..., batch_dims=...). I think those should solve your feature request.

**Comment by alextp** [comment]
Sorry, I meant gather_nd with batch_dimensions.
