### ISSUE TITLE
matmul gives different results for tensor based on shape

### ISSUE THREAD

**Issue by fast-reflexes** [tensorflow/tensorflow#28225]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10 Pro N, 64-bit
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: -
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 1.13.1
- Python version: 3.6.8
- Bazel version (if compiling from source): -
- GCC/Compiler version (if compiling from source): -
- CUDA/cuDNN version: -
- GPU model and memory: No GPU

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**

Given a tensor X with shape (1, 1, 256), matmul gives slightly different output for matmul(X, W) and matmul(tf.tile(X, [1, 2, 1]), W)

**Describe the expected behavior**

The 60 elements of the output of matmul(X, W) should match exactly the first 60 outputs of matmul(tf.tile(X, [1, 2, 1]), W)

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

```
import tensorflow as tf
import numpy as np
import platform

print("Python version", platform.python_version())
print("Tensorflow version", tf.__version__)
print("Numpy version", np.version.version)

X = tf.random.normal((1, 1, 256), dtype = tf.float32, stddev = 0.0001, seed = 1)
W = tf.random.normal((1, 256, 60), dtype = tf.float32, stddev = 0.0001, seed = 1)

s = tf.Session()
a = tf.matmul(X, W)
b = tf.matmul(tf.tile(X, [1, 2, 1]), W)
a, b = s.run([a, b])
print(a[0][0][0], b[0][0][0])
```

For me, the output is:

Python version 3.6.8
Tensorflow version 1.13.1
Numpy version 1.16.2
2019-04-28 12:27:37.641095: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
5.1921496e-08 5.1921518e-08

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

I understand that floating point approximation might play a role here but should the output depend on the shape like this?

**Comment by picciama** [comment]
I can reproduce this with Tensorflow 2.0.0 and `dtype=tf.float64`
Choose X with shape (a,b) and W with shape (b, c).
Now, I reduce the c dimension of the W tensor using `tf.boolean_mask` to filter out some columns. The results then differ by up to 1e-14.
Interestingly, this happens only to some values but not to others. 
While I can imagine it has to do with some precision problems, there are two reasons it shouldn't happen:
- X is a design matrix in my case, thus containing only the values 0 and 1 for which I don't expect such differences when performing `matmul` operations.

**Comment by jvishnuvardhan** [comment]
@fast-reflexes Is this still an issue for you? I tried running your code in `TF1.x` as well as  in `TF2.x`. Results are not exact but very close (till 13th or 14th decimal if dtype is `tf.float32`) and the results are even closer if dtype is `tf.float64`. 

Please check the [gist here](https://colab.research.google.com/gist/jvishnuvardhan/92196f377c28f50d277baa947070ae68/untitled.ipynb) with `TF1.x` and [gist here](https://colab.research.google.com/gist/jvishnuvardhan/69da3900897f72df79272cf088e959ca/untitled996.ipynb) with `TF2.5`. Thanks!
