### ISSUE TITLE
Documentation for C APIs

### ISSUE THREAD

**Issue by fade2black** [tensorflow/tensorflow#28228]
Is there any detailed documentation for C APIs besides  [version example](https://www.tensorflow.org/install/lang_c#build) and [c_api.h](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/c/c_api.h)? For example, creating a session and tensors, running queries, get tensor result, etc.

**Comment by alextp** [comment]
Look at the [tests](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/c/c_api_test.cc) for usage examples, they are pretty thorough.
