### ISSUE TITLE
Self-train MobileNet on ImageNet

### ISSUE THREAD

**Issue by fzyzcjy** [tensorflow/tensorflow#28227]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using): latest
- Are you willing to contribute it (Yes/No): Yes if I can

**Describe the feature and the current behavior/state.**
Hi! Thank you very much for these wonderful libraries!
I want to have a mobilenet with alpha=0.125 (or possibly smaller) to make it even more light-weight. Since there is no pretrained models (only with alpha=0.25 and so on), I want to first pretrain it on mobilenet, and then use it for fine-tuning. Therefore, I would appreciate it if I could be given the code you use to pretrain it on mobilenet. Thank you very much!

**Will this change the current api? How?**
NO

**Who will benefit with this feature?**
everyone who wants to train on ImageNet by themselves

**Any Other info.**
it seems that to achieve this, it is only needed to open source some simple scripts :)

Thanks so much!

**Comment by suharshs** [comment]
Hi apologies for the delay in getting to this, we have released the scripts we used to make the pretrained models here: https://github.com/tensorflow/models/blob/master/research/slim/nets/mobilenet_v1_train.py
and 
https://github.com/tensorflow/models/blob/master/research/slim/nets/mobilenet_v1_eval.py

**Comment by fzyzcjy** [comment]
WOW Thank you so much!
