### ISSUE TITLE
Implement variable length sequences for seq2seq

### ISSUE THREAD

**Issue by wb14123** [tensorflow/tensorflow#2823]
Now, seq2seq uses bucketing to deal with variable length sequences. Which need to define many models and require manually tuning.  While in RNN, some models implement variable length sequences with a param `sequence_length`, which I think is a better method. So how about use the same method in RNN to implement variable length sequences for seq2seq?

**Comment by ebrevdo** [comment]
This is on the near-future TODO list.

**Comment by wb14123** [comment]
Where can I see the TODO list? I'm interesting in implement this.

**Comment by ebrevdo** [comment]
We already have interest from about 2 folks internally to implement this.
Please be patient and we'll have something "soonish".

**Comment by wb14123** [comment]
Thanks. Looking forward it.

**Comment by jihunchoi** [comment]
Hello, is there advance on this issue?
I'm not rushing you; I'm using seq2seq with pleasure with bucketing and padding technique. :)

**Comment by tgs266** [comment]
Not trying to sound pushy at all, I was just wondering how the process on this is moving along?

**Comment by jihunchoi** [comment]
There exists quite good progress on #4686!
It's not be merged yet but I think most of the functionalities are ready to use, and I'm actually using it.

**Comment by tgs266** [comment]
That's great news!
