### ISSUE TITLE
Warning recommends using unexisting tf.keras.layers.CuDNNLSTM layer

### ISSUE THREAD

**Issue by Jsevillamol** [tensorflow/tensorflow#28232]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 16.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): pip install tensorflow-gpu==2.0.0-alpha0
- TensorFlow version (use command below): 2.0.0-alpha0
- Python version: 3.7.3
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 10.0
- GPU model and memory: GeForce GTX 1080 Ti, 11175MiB

**Describe the current behavior**
In TF-GPU 2.0 

**Describe the expected behavior**
Either have a `tf.keras.layers.CuDNNLSTM` or remove the warning.

**Code to reproduce the issue**
This to raise the warning

    import tensorflow as tf
    import tensorflow.keras.layers as ll
    input_ = ll.Input((100,50))
    x = ll.LSTM(100)(input_)

This to try to use CuDNNLSTM 

    import tensorflow as tf
    import tensorflow.keras.layers as ll
    input_ = ll.Input((100,50))
    x = tf.keras.layers.CuDNNLSTM(100)(input_)

**Other info / logs**

The warning message:

    W0428 17:18:46.256715 140569873639168 tf_logging.py:161] <tensorflow.python.keras.layers.recurrent.UnifiedLSTM object at 0x7fd8c75a9940>: Note that this layer is not optimized for performance. Please use tf.keras.layers.CuDNNLSTM for better performance on GPU.

When trying to call CuDNNLSTM:

    AttributeError: module 'tensorflow.keras.layers' has no attribute 'CuDNNLSTM'

**Comment by muddham** [comment]
@Jsevillamol Able to reproduce the issue. TF 2.0.0-alpha0 uses tf.compat.v1.keras.layers.CuDNNLSTM Please check the reference [link](https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/compat/v1/keras/layers/CuDNNLSTM?hl=en)

I had updated the code with this alias as below and I dont see cuDNNLSTM warning.Please let us know how it progresses. Thanks!

import tensorflow as tf
import tensorflow.keras.layers as ll
input_ = ll.Input((100,50))
x = tf.compat.v1.keras.layers.CuDNNLSTM(100)(input_)

WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/resource_variable_ops.py:435: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.

**Comment by hchungdelta** [comment]
I also have encountered this issue.
As @muddham mentioned, when I used `tf.compat.v1.keras.layers.CuDNNLSTM` to replace it, the warning message was gone.

However, I found that although the warning appears when using `tf.keras.layers.CuDNNLSTM`,
the training efficiency are the same as  `tf.compat.v1.keras.layers.CuDNNLSTM`
(Of course both are many times faster than `tf.compat.v1.keras.layers.LSTM`)

I wonder if it is just fine to remove the warning.

**Comment by Jsevillamol** [comment]
@hchungdelta I noticed that I am confused.  In my installation of TF 2.0 there is no longer a `tf.keras.layers.CuDNNLSTM`, just the the `tf.compat.v1.keras.layers.CuDNNLSTM` one.

**Comment by hchungdelta** [comment]
@Jsevillamol  You are right. And I must apologize since I misuse the name in previous comment. 
I use `tf.keras.layers.LSTM`  not `tf.keras.layers.CuDNNLSTM`.  (I edited the previous comment, sorry about making confusing)
`tf.keras.layers.CuDNNLSTM` no longer exists in TF 2.0. Since it was already combined into LSTM.(So you might see the function name of LSTM is "UnifiedLSTM").

**Comment by muddham** [comment]
@Jsevillamol Please confirm if you are happy to close this issue.

**Comment by Jsevillamol** [comment]
@muddham I am happy to close the issue if you are - I personally think that the warning should be removed in TF 2.0 since it is misleading for new users, but it is not causing me any major trouble.

**Comment by jvishnuvardhan** [comment]
@Jsevillamol I could reproduce the Attribute Error but I don't see any warning as you mentioned. Please check my GitHub [gist](https://colab.sandbox.google.com/gist/jvishnuvardhan/8a2b480eefa661f5acd8c93cae10b967/untitled138.ipynb) and try to run it on your system. If you see the warning, please let me know I could work on resolving the `warning`. Thanks

**Comment by muddham** [comment]
I Could reproduce the warning message using tensorflow gpu. please see attached
![image](https://user-images.githubusercontent.com/48215502/57275026-c605af00-70ba-11e9-9ff6-a4bb1fe9cabe.png)

**Comment by jvishnuvardhan** [comment]
@Jsevillamol Could check my [gist](https://colab.sandbox.google.com/gist/jvishnuvardhan/573ca634e39162eb4c48cabe042b89ca/untitled138.ipynb) and may be upgrade your TF2.0.0-alpha0 and run it again. If you see any error, we would like to resolve that. Thanks!

**Comment by Jsevillamol** [comment]
@jvishnuvardhan I can no longer reproduce the issue!

**Comment by stephenmdicke27** [comment]
tf.compat.v1.keras.layers.CuDNNLSTM  works for me. Is it going to be available on non-beta1 platforms? What replaces it in TF 2.0.0-beta1 ?
