### ISSUE TITLE
[TF 2.0 API Docs] tf.audio.decode_wav

### ISSUE THREAD

**Issue by missaugustina** [tensorflow/tensorflow#28237]
API doc update for https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/audio/decode_wav

Correct links? No
Clear Description? No
Usage Example?
Parameters Defined? Yes, not verified against current code
Returns defined? Yes, not verified against current code
Raises listed and defined? No
Visuals, if applicable? No

I will submit a PR, please assign this bug to me.

**Comment by gadagashwini** [comment]
@missaugustina  Could you provide more details about the what you want to work on and context.

**Comment by missaugustina** [comment]
Hi, I'm working on the API docs per the doc sprint info, what are you confused about?

**Comment by missaugustina** [comment]
I plan to submit a PR for this issue

**Comment by missaugustina** [comment]
Related to Issue #28236

**Comment by robgmsn** [comment]
Just got this answered on SO...

```
raw_audio = tf.io.read_file(filename)
waveform = tf.audio.decode_wav(raw_audio)
```

https://stackoverflow.com/questions/58096095/how-does-tf-audio-decode-wav-get-its-contents
