### ISSUE TITLE
tf.image and eager execution bug

### ISSUE THREAD

**Issue by Ouwen** [tensorflow/tensorflow#28241]
For tensorflow 1.13 and 2.0.0a, tf.image requires explicit `tf.constant` instead of `numpy` arrays.

https://colab.research.google.com/drive/1CrbsY4L7KJLP3IuB_gs4KJiz2szuVDb9

```python
import tensorflow as tf
import numpy as np
print(tf.__version__)

image = np.random.random([512, 512, 1])
tf.square(image, image).shape # works


image = np.random.random([512, 512, 1])
tf.image.ssim_multiscale(image, image, max_val=1).shape # fails  

image = tf.constant(np.random.random([512, 512, 1]))
tf.image.ssim_multiscale(image, image, max_val=1) # works
```

**Comment by yongtang** [comment]
@Ouwen The link is not accessible, could you post the code instead?

**Comment by Ouwen** [comment]
@yongtang my apologies, I've changed the settings on the colab notebook and posted the code above.

**Comment by jvishnuvardhan** [comment]
I could reproduce the issue in TF2.0. I think either we need to update the code or update the doc saying the dtype of img should be a tensor. Thanks!

**Comment by yongtang** [comment]
Added a PR #28274 for the fix.
