### ISSUE TITLE
[feature request] Bidirectional with explict cell_fw & cell_bw parameters

### ISSUE THREAD

**Issue by soloice** [tensorflow/tensorflow#28245]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using): all version with `tf.keras.layers.Bidirectional`
- Are you willing to contribute it (Yes/No): Yes

**Describe the feature and the current behavior/state.**

For bidirectional rnns, the TF native API EXPLICITLY specifies the forward & backward rnn cells as in `tf.nn.bidirectional_dynamic_rnn(cell_fw, cell_bw)`, while the high-level keras API `tf.keras.layers.Bidirectional(tf.keras.layers.RNN(cell, unroll=True))` creates forward and backward layers IMPLICITLY, which may cause confusion. 

> Just recall how much confusion `tf.nn.rnn_cell.MultiRNNCell` has caused with TF 0.12: At that time, a list of the **SAME** RNNCell instance is passed but different parameters are created for each RNN layer. Later this behaviour is fixed with a list of **DIFFERENT** RNNCell instances, and a list of the **SAME** RNNCell instance will lead to parameter sharing across layers.

My point is, `tf.keras.layers.Bidirectional` should accept two RNNCell instances (one forward and one backward). If both `cell_fw` and `cell_bw` are exposed to users, it will be more consistent with the TF native API and users will know they are using two different RNN cells for forward and backward purpose.

This new interface design also enables more complicated use cases, e.g.: using a 2-layer forward LSTM with hidden size 1024 each layer & a 3-layer backward GRU with hidden size 512 each layer, or sharing the parameters between forward & backward RNN if users wish.

**Will this change the current api? How?**
No. Due to compatibility concern, the `cell_fw` and `cell_bw` can be designated as key word arguments, making sure normal users are not influenced while higher level users gain more control.

**Who will benefit with this feature?**
Advanced RNN users. Or users familiar with the original `tf.nn.bidirectional_dynamic_rnn(cell_fw, cell_bw)` API.

**Comment by qlzh727** [comment]
Ack, thanks for the feature request, I think it make sense to make this change, will send an update within this week.

**Comment by soloice** [comment]
Thanks.

**Comment by qlzh727** [comment]
This should now be fixed by https://github.com/tensorflow/tensorflow/commit/fe5e1f39590f5847a384dcccb33956a5c2606d16

**Comment by soloice** [comment]
Such a quick fix.
