### ISSUE TITLE
[TF 2.0] Using tf.py_function which has tf.string type input in dataset.map() generates dtype warning.

### ISSUE THREAD

**Issue by KichangKim** [tensorflow/tensorflow#28248]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): 
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10 x64 1809
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): pip
- TensorFlow version (use command below): unknown 2.0.0-dev20190428
- Python version: 3.6.7
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: CUDA 10.0, cudnn-10.0-windows10-x64-v7.5.0.56
- GPU model and memory: GeForce GTX 1070 8GB

**Describe the current behavior**
Using tf.py_function which has tf.string type input generates warning like this:

> W0429 14:24:18.965364 13252 backprop.py:820] The dtype of the watched tensor must be floating (e.g. tf.float32), got tf.string

This warning did not shown with v1.12.0-9492-g2c319fb415 2.0.0-alpha0, but 2.0.0-dev20190428 does.

**Describe the expected behavior**
dtype warning should not be shown.

**Code to reproduce the issue**
```
import tensorflow as tf


def transform_tag_python(x):
    return 1.0


dataset = tf.data.Dataset.from_tensor_slices(['tag1'])
dataset = dataset.map(lambda x: tf.py_function(
    transform_tag_python, (x,), (tf.float32,)))

for sample in dataset:
    print(sample)
```

**Comment by shashvatshahi1998** [comment]
Look where tf.py_function is defined there is no such warning file present regarding dtype to be float. So why it is showing this?

**Comment by rbrueckner** [comment]
I am facing the same issue.

**Comment by jvishnuvardhan** [comment]
@KichangKim There was no warning when `TF2.0.0-alpha0` or `tf-nightly` was used. The issue was reproduced with `tf-nightly-2.0-preview`. We will check for the source of error and resolve it. Thanks for finding this. Thanks!

**Comment by sleighsoft** [comment]
Here:
https://github.com/tensorflow/tensorflow/blob/88ed9779719b8b2136a596c7b4dda875568894a3/tensorflow/python/eager/backprop.py#L841

**Comment by alextp** [comment]
It's likely the tape.watch here https://github.com/tensorflow/tensorflow/blob/88520c4dd6aa804330b053a35676eeffc3380d65/tensorflow/python/ops/script_ops.py#L108 which needs to be called only for floating dtypes.

**Comment by alextp** [comment]
I'll happily accept a PR to fix this.

**Comment by feihugis** [comment]
The PR #30107 is submitted to fix this issue.

cc @alextp

**Comment by vineetred** [comment]
Looks like the PR failed a few checks. Is the issue still persisting?

**Comment by littleaich** [comment]
This issue still exists in tf-2 version beta-1.

**Comment by sleighsoft** [comment]
You have to use nightly builds
