### ISSUE TITLE
[TF 2.0] Using preserve_aspect_ratio=True in tf.image.resize() generates deprecation warning.

### ISSUE THREAD

**Issue by KichangKim** [tensorflow/tensorflow#28246]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): 
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10 x64 1809
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): pip install tensorflow-gpu==2.0.0-alpha0
- TensorFlow version (use command below): v1.12.0-9492-g2c319fb415 2.0.0-alpha0
- Python version: 3.6.7
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: CUDA 10.0, cudnn-10.0-windows10-x64-v7.5.0.56
- GPU model and memory: GeForce GTX 1070 8GB

**Describe the current behavior**
Using preserver_aspect_ratio flag generates deprecation warnings.
0429 13:13:47.903097 23940 deprecation.py:323] From 

> C:\Users\XXXXXX\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\ops\image_ops_impl.py:993: to_float (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
W0429 13:13:47.905097 23940 deprecation.py:323] From 

> C:\Users\XXXXXX\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\ops\image_ops_impl.py:999: to_int32 (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.

**Describe the expected behavior**
Should not show warning.

**Code to reproduce the issue**
```
import tensorflow as tf


def load_image(x):
    image = tf.io.read_file(x)
    image = tf.io.decode_png(image)
    image = tf.image.resize(image, size=(
        128, 128), preserve_aspect_ratio=True)

    return image


with tf.device('/cpu:0'):
    image_2 = load_image('test.jpg')
    print(image_2.numpy().shape)
```

**Comment by yongtang** [comment]
@KichangKim The warnings should have been fixed in: https://github.com/tensorflow/tensorflow/commit/df3a3375941b9e920667acfe72fb4c33a8f45503

**Comment by KichangKim** [comment]
Thanks for investigation.
