### ISSUE TITLE
ImportError: cannot import name 'tflite_convert'

### ISSUE THREAD

**Issue by beeteax** [tensorflow/tensorflow#28253]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): Pip
- TensorFlow version (use command below): v1.13.1-0-g6612da8951
- Python version: 3.6.5
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 10/ 7.5
- GPU model and memory: Tesla V100

How can i resolve this issue ???

/home/ubuntu/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Traceback (most recent call last):
  File "./DeepSpeech.py", line 21, in <module>
    from tensorflow.contrib.lite.python import tflite_convert

**Comment by muddham** [comment]
@beeteax please provide the link which you are refering  and provide the complete log to help you with resolution.

**Comment by muddham** [comment]
@beeteax Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
