### ISSUE TITLE
tf.image.decode_png doesn't work for palette-based images

### ISSUE THREAD

**Issue by adrianstaniec** [tensorflow/tensorflow#28256]
**System information**
- Have I written custom code
- Linux Ubuntu 18.04
- TensorFlow installed from source 
- TensorFlow version:  v1.12.0-0-ga6d8ffae09 1.12.0
- Python version: 3.6.7
- CUDA/cuDNN version: V10.0.130
- GPU model and memory: RTX2080 Ti

**Describe the current behavior**

Pixel values should be the same regardless if loading the image by PIL or  by TF

**Describe the expected behavior**

Pixel values are different

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

```
from PIL import Image
import numpy as np

import tensorflow as tf
tf.enable_eager_execution()

PATH = '/tmp/42313738-65c10f7c-807e-11e8-8f11-9db821e3c3cc.png'

im = Image.open(PATH)
ar = np.asarray(im)
pil_max = np.max(ar)
print(pil_max)

im = tf.gfile.FastGFile(PATH, 'rb').read()
ar = tf.image.decode_png(im, channels=1)
tf_max = tf.reduce_max(ar)
print(tf_max)

assert tf_max == pil_max
```

image:
[here](https://user-images.githubusercontent.com/26040/42313738-65c10f7c-807e-11e8-8f11-9db821e3c3cc.png)

**Other info / logs**
I suspect that the problem is caused by tensorflow loading the first RGB channel, (so the red channel)
instead of the color indexes, for palette based png images like given example.

related to #20028

**Comment by captain-pool** [comment]
The Problem is with the `channel=1` parameter.
You are converting the image to Grayscale, which is nothing but a weighted average of the channels. So this changes the value of the pixels.
This code works perfectly, for `channel=0` where the number of channels of the original image is preserved, causing no change in the value of the pixels.
For more info refer to:
https://www.tensorflow.org/versions/r1.12/api_docs/python/tf/image/decode_png

**Comment by adrianstaniec** [comment]
1. That is not the problem, and the code doesn't work perfectly if I use channel=0.
     if I use channel=0, I get again a RGB image with 3 channels, which I don't want.
     I want the single channel indexed-based image.


2. The documentation doesn't mention anything about taking a weighted average of the channels.

3. I am sorry, the image I have provided it not the best, please try this code:
```
from PIL import Image
import numpy as np
import tensorflow as tf
tf.enable_eager_execution()

PATH = '/tmp/xX4Stvh.png'

im = tf.gfile.FastGFile(PATH, 'rb').read()
ar = tf.image.decode_png(im, channels=0)
tf_max = tf.reduce_max(ar)
print(tf_max)

im = Image.open(PATH)
ar = np.asarray(im)
pil_max = np.max(ar)
print(pil_max)
```
on this image:
https://i.imgur.com/xX4Stvh.png

it has only three colors, so the difference in behaviour will be more apparent

**Comment by captain-pool** [comment]
>     1. That is not the problem, and the code doesn't work perfectly if I use channel=0.
>        if I use channel=0, I get again a RGB image with 3 channels, which I don't want.
>        I want the single channel indexed-based image.
> 
>     2. The documentation doesn't mention anything about taking a weighted average of the channels.
> 
>     3. I am sorry, the image I have provided it not the best, please try this code:
> 
> 
> ```
> from PIL import Image
> import numpy as np
> import tensorflow as tf
> tf.enable_eager_execution()
> 
> PATH = '/tmp/xX4Stvh.png'
> 
> im = tf.gfile.FastGFile(PATH, 'rb').read()
> ar = tf.image.decode_png(im, channels=0)
> tf_max = tf.reduce_max(ar)
> print(tf_max)
> 
> im = Image.open(PATH)
> ar = np.asarray(im)
> pil_max = np.max(ar)
> print(pil_max)
> ```
> 
> on this image:
> https://i.imgur.com/xX4Stvh.png
> 
> it has only three colors, so the difference in behaviour will be more apparent

Sorry for the confusion. The Main reason for this error is, PIL opens images in palette mode. This means the color from the channels are mapped to a color palette and that palette index is provided in each location of the image. However tensorflow, decodes the image into Channels and doesn't use this concept of palette. So, when the Pillow Image object is converted to numpy array, the values at the various positions is not intensity of the pixels of the color channel, which is in the case of tensorflow.

The correct way to verify this is:
```python
from PIL import Image
import numpy as np
import tensorflow as tf
tf.enable_eager_execution()

PATH = '/tmp/xX4Stvh.png'

im = tf.gfile.FastGFile(PATH, 'rb').read()
ar = tf.image.decode_png(im, channels=0)
tf_max = tf.reduce_max(ar)
print(tf_max)

im = Image.open(PATH).convert('RGB') # This convert() function converts from 
                                     # PIL exclusive Palette mode to channel mode
ar = np.asarray(im)
pil_max = np.max(ar)
print(pil_max)
```

And about the weighted average thing. When you are loading a color image in channel mode and request it to convert to grayscale (`channels=0` does that). A weighted average on all the channels(R,G,B) is calculated to produce the value for one channel. (That's why the number of channels for grayscaled image is 1 and RGB colored image, is 3)
Reference: https://en.wikipedia.org/wiki/Grayscale#Converting_color_to_grayscale

**Comment by adrianstaniec** [comment]
thanks for the response capitan-pool
So the whole point is that I actually only care about these palette indexes, not about the RGB values.
Those palette index values are the target class IDs for semantic segmentation.

**Comment by captain-pool** [comment]
> thanks for the response capitan-pool
> So the whole point is that I actually only care about these palette indexes, not about the RGB values.
> Those palette index values are the target class IDs for semantic segmentation.

Huh? That has nothing to do with semantic segmentation. You don't care about Palette Values for any sort of deep vision related tasks, in general. You need to use the 3 Channels of RGB, 4 Channels of RGBA, or 1 channel of Grayscale.

**Comment by adrianstaniec** [comment]
ok, forget the segmentation part.

Could you just answer this question:
*How can I achieve the same behavior with tensorflow as I had with PIL?*

because what you have suggested before is the opposite,
you modified the PIL code to match the tensorflow implementation

**Comment by captain-pool** [comment]
You can do something similar using,
```python
import tensorflow as tf
img = tf.image.decode_png(tf.io.read_file(/path/to/png/file))
```

**Comment by captain-pool** [comment]
> ok, forget the segmentation part.
> 
> Could you just answer this question:
> _How can I achieve the same behavior with tensorflow as I had with PIL?_
> 
> because what you have suggested before is the opposite,
> you modified the PIL code to match the tensorflow implementation

You can do something similar using,
```python
import tensorflow as tf
img = tf.image.decode_png(tf.io.read_file(/path/to/png/file))
```

**Comment by adrianstaniec** [comment]
Could someone else look at this issue, please?
I am sorry, but captain-pool doesn't get it

**Comment by jvishnuvardhan** [comment]
This is not Build/Installation or Bug/Performance issue. Please post this kind of support questions at [Stackoverflow](https://stackoverflow.com/questions/tagged/tensorflow). There is a big community to support and learn from your questions. GitHub is mainly for addressing bugs in installation and performance. Thanks!

**Comment by chenweizhi** [comment]
the only way you could do is to re-save your png file in "RGB" mode . in this case,  the image datas are the indices of  palette，which you needed to training a semantic segment model , and decoding function in tensorflow works correctly  . side effect is that you cant see anything in preview, because Its valuse is too low to be seen

**Comment by jvishnuvardhan** [comment]
This is not Build/Installation or Bug/Performance issue. Please post this kind of support questions at [Stackoverflow](https://stackoverflow.com/questions/tagged/tensorflow). There is a big community to support and learn from your questions. GitHub is mainly for addressing bugs in installation and performance. Thanks!

**Comment by doraeric** [comment]
I just met the same problem, it looks like there is no way to get the correct palette indexes with native tensorflow. However, I solved my problem with `tf.py_func`. I'll leave my code here in case somebody finds it useful.
```python
import tensorflow as tf
import numpy as np
from PIL import Image

dataset = tf.data.Dataset.from_tensor_slices({
    'image': ['img00.png', 'img01.png'],
    'index': [0, 1]
    })

def load_image_func(image, index):
    return np.array(Image.open(image)), index

dataset = dataset.map(lambda x: (
    tf.py_func(load_image_func, [x['image'], x['index']], [tf.uint8, x['index'].dtype])))
```

**Comment by alar0330** [comment]
A clean solution would be to re-implement a custom op to decode a PNG without palette conversion.

Currently, the conversion is done at [core-level](https://github.com/tensorflow/tensorflow/blob/38cdb9ff8548efc920039d68dd94b5581db6314a/tensorflow/core/lib/png/png_io.cc#L284):
```cpp
  // convert palette to rgb(a) if needs be.
  if (context->color_type == PNG_COLOR_TYPE_PALETTE)
    png_set_palette_to_rgb(context->png_ptr);
```

**Comment by tanzhenyu** [comment]
This is a valid issue that shouldn't be closed and likely drives user away if not properly handled, as it represents an important use case. @adrianstaniec you're right it doesn't work and for exactly the reasons @alar0330 mentioned.
I believe the fix doesn't require any API level change, i.e., tf.image.decode_png(mask_path) should have same behavior as np.array(Image.Open(mask_path))

**Comment by yongtang** [comment]
The issue comes from a redundant ` png_set_rgb_to_gray` call in the C++ kernel for palette-based images. I have created a PR #41472 to fix this issue.

**Comment by mvonpohle** [comment]
After the rollback of the fix, this is now again a problem. When loading index PNGs TF should allow the user to choose whether to use the palette to convert the pixel index or choose to load the raw index value themselves. 

Thanks to @alar0330 for the workaround.
