### ISSUE TITLE
AttributeError: module 'tensorboard.summary._tf.summary' has no attribute 'summary_scope'

### ISSUE THREAD

**Issue by Ormagardskvaedi** [tensorflow/tensorflow#28266]
I try this tutorial: [Hyperparameter Tuning with the HParams Dashboard](https://www.tensorflow.org/tensorboard/r2/hyperparameter_tuning_with_hparams) and it seems to not be up to date.

My setup:

- Jupyterlab: '0.33.12'
- ipython: '7.2.0'
- python: '3.6.7'
- tensorflow: '2.0.0-dev20190426'

I have a problem with the line `tf.summary.scalar('accuracy', accuracy, step=1, description="The accuracy")`

I'm getting this error and I do not know how to handle it.

```
AttributeError                            Traceback (most recent call last)
<ipython-input-27-1053baffc567> in <module>
      8             print(hparams)
      9             run_name = "run-%d" % session_num
---> 10             run("logs/hparam_tuning/" + run_name, hparams)
     11             session_num += 1

<ipython-input-26-1dc9836089ce> in run(run_dir, hparams)
      7         summary_end = hparams_summary.session_end_pb(api_pb2.STATUS_SUCCESS)
      8 
----> 9         tf.summary.scalar('accuracy', accuracy, step=1, description="The accuracy")
     10         tf.summary.experimental.write_raw_pb(summary_start.SerializeToString(), step=1)
     11         tf.summary.experimental.write_raw_pb(summary_end.SerializeToString(), step=1)

~/hugoenv/lib/python3.6/site-packages/tensorboard/plugins/scalar/summary_v2.py in scalar(name, data, step, description)
     53   summary_metadata = metadata.create_summary_metadata(
     54       display_name=None, description=description)
---> 55   with tf.summary.summary_scope(
     56       name, 'scalar_summary', values=[data, step]) as (tag, _):
     57     tf.debugging.assert_scalar(data)

AttributeError: module 'tensorboard.summary._tf.summary' has no attribute 'summary_scope'
```

**Comment by jvishnuvardhan** [comment]
@Ormagardskvaedi I could reproduce the issue with the tutorial. However, if you change
`!pip install -q tf-nightly-2.0-preview` with 
`!pip install -q tensorflow==2.0.0-alpha0` 
then it runs without any `AttributeError`. Thanks!

**Comment by wchargin** [comment]
@Ormagardskvaedi: Thanks for the report! This should be resolved by
tensorflow/tensorboard#2110, which is available in the latest
TensorBoard nightly releases. Could you try running

```
!pip install -q -U tb-nightly
```

from within your notebook context to pull in the latest version? (You
may have to restart the kernel for this to take effect.)

**Comment by wchargin** [comment]
Assuming from your :+1: that the upgrade solved your problem; if not,
please let us know and we can reopen.
