### ISSUE TITLE
Feature Request: TFLite RELU quantization

### ISSUE THREAD

**Issue by ajarthurs** [tensorflow/tensorflow#28268]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
Arch Linux 5.0.7

- TensorFlow installed from (source or binary):
source

- TensorFlow version (or github SHA if from source):
5d3aa3663a7a07e9f6494ec86fee5be44aa00597

**Provide the text output from tflite_convert**
Using `tensorflow/lite/tools/optimize/calibration` via Python for calibration-and-quantization. Reports the following after calibration, during quantization.
```
RuntimeError: Quantization not yet supported for op: RELU
```

Also, please include a link to a GraphDef or the model if possible.
`tensorflow/tpu/models/official/retinanet` is one example model containing RELU.

**Any other info / logs**

Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by jvishnuvardhan** [comment]
@ajarthurs Could you provide more details on the feature you are requesting. If you provide little more details on the features and its use cases then it will be great. Thanks!

**Comment by ajarthurs** [comment]
Sure. I am attempting to quantize the RetinaNet model using TFLite's calibration optimization tool. Here is a complete example. A copy of a floating-point (32bit) RetinaNet TFLite model, trained on MSCOCO, can be found at https://www.dropbox.com/s/hnkmqzcasb8lu8n/retinanet-float32.tflite?dl=0

[calibrate_and_quantize.py](https://github.com/tensorflow/tensorflow/files/3131714/calibrate_and_quantize.py.zip) is a Python script that runs TFLite's calibration tool to quantize the said model. To run it:
```
# Adjust paths as needed.
$ PYTHONPATH=path/to/tensorflow/tpu/models/official/retinanet:$PYTHONPATH python calibrate_and_quantize.py --input_tflite_file=retinanet-float32.tflite --output_tflite_file=retinanet-int8.tflite --train_file_pattern=path/to/mscoco-tfrecords/train*
```

Without patching `tensorflow/lite/tools/optimize/operator_property.cc`, the script will actually end with an error stating: `RuntimeError: Quantization not yet supported for op: RESIZE_BILINEAR` (see similar request #28269). After adding `RESIZE_BILINEAR` to the op-list in `tensorflow/lite/tools/optimize/operator_property.cc`, the Python script will then report `RuntimeError: Quantization not yet supported for op: RELU`.

A floating-point TFLite implementation of `RELU` is in `tensorflow/lite/kernels/activations.cc:(GenericPrepare,ReluEval)` (lines 104 and 331).

**Comment by amitsrivastava78** [comment]
@ajarthurs , I have raised on PR for 8-bit quantization #27028 , it might take some time for this to merge in the mean time you can take this and test it and post the results here.

Regards
Amit

**Comment by ajarthurs** [comment]
@amitsrivastava78 Thanks Amit, I'll give your PR a try.

**Comment by ajarthurs** [comment]
Needed to add RELU. After that, I can quantize and evaluate RELU.
https://github.com/ajarthurs/tensorflow/commit/6e3aa830b2327f08ce88c6c097e7b432e77b1aae

**Comment by amitsrivastava78** [comment]
@ajarthurs , thanks for the feedback, Great to see that things worked out for you.

@liyunlu0618 issue seems to be resolved with the PR, it might take some time for this to get merged, but we can close the issue for now.

Regards
Amit

**Comment by liyunlu0618** [comment]
RELU should be supported for now, at least in nightly. Closing the issue.
