### ISSUE TITLE
Graph transform tool  Node Quantization gives error 

### ISSUE THREAD

**Issue by alexcpn** [tensorflow/tensorflow#28276]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 16.04
- TensorFlow installed from (source or binary): Via Docker tensorflow/serving:1.13.0-gpu 
- TensorFlow version (use command below): 1.13
- CUDA/cuDNN version: From Docker  tensorflow/serving:1.13.0-gpu
- GPU model and memory: NVIDIA V100 32 GB

**Describe the current behaviour**
After Quantizing Weights and Nodes using the Graph transform tool on the SSD model from TF model zoo I get the following error

**Code snippet**

```
transforms = ['add_default_attributes', \
  'strip_unused_nodes', \
  'remove_nodes(op=Identity, op=CheckNumerics)',\
  'fold_constants(ignore_errors=true)',
  'fold_batch_norms',
  'fold_old_batch_norms',
  'quantize_weights',
  'quantize_nodes',
  'strip_unused_nodes',
  'sort_by_execution_order']

optimize_graph('/coding/ssd_inception_v2_coco_2018_01_28', 'frozen_inference_graph.pb' ,
               transforms, output_node_names,outname='optimized_model_weight_quant.pb')
```
**Error Snippet**

`details = "input_max_range must be larger than input_min_range.`

**Describe the expected behaviour**
Should work

**Code to reproduce the issue**

All details are logged here 
https://medium.com/@alexcpn/optimizing-any-tensorflow-model-using-tensorflow-transform-tools-and-using-tensorrt-1cc190cafe1f
+ colab here
https://colab.research.google.com/drive/1wQpWoc40kf__WSjfTqDaReMx6fFjUn48
Client 

**Other info / logs**
Docker container used for the optimization is : tensorflow/tensorflow:1.13.0rc1-gpu-jupyter
Docker used for serving : tensorflow/serving:1.13.0-gpu 
Model used  *ssd_resnet_50_fpn_coco* form TF model zoo -https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/detection_model_zoo.md

```
(Got an error, <_Rendezvous of RPC that terminated with:
	status = StatusCode.INVALID_ARGUMENT
	details = "input_max_range must be larger than input_min_range.
	 [[{{node Postprocessor/BatchMultiClassNonMaxSuppression/map/while/MultiClassNonMaxSuppression/ClipToWindow_87/Area/mul_eightbit/Postprocessor/BatchMultiClassNonMaxSuppression/map/while/MultiClassNonMaxSuppression/ClipToWindow_87/Area/sub_1/quantize}}]]
	 [[{{node Postprocessor/BatchMultiClassNonMaxSuppression/map/while/MultiClassNonMaxSuppression/zeros_like_83}}]]"
	debug_error_string = "{"created":"@1555723203.356344655","description":"Error received from peer","file":"src/core/lib/surface/call.cc","file_line":1036,"grpc_message":"input_max_range must be larger than input_min_range.\n\t [[{{node Postprocessor/BatchMultiClassNonMaxSuppression/map/while/MultiClassNonMaxSuppression/ClipToWindow_87/Area/mul_eightbit/Postprocessor/BatchMultiClassNonMaxSuppression/map/while/MultiClassNonMaxSuppression/ClipToWindow_87/Area/sub_1/quantize}}]]\n\t [[{{node Postprocessor/BatchMultiClassNonMaxSuppression/map/while/MultiClassNonMaxSuppression/zeros_like_83}}]]","grpc_status":3}"
>)

```

Also I tried before running a model that was converted from Keras to tensorflow - Retinanet.(CNN) Again QunatizeNodes did not work with the following error. Colab for that here 
https://colab.research.google.com/drive/1u79vDN4MZuq6gYIOkPmWsbghjunbDq6m

```
_Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.UNIMPLEMENTED
	details = "Broadcast between [1,9,4] and [221,1,4] is not supported yet.
	 [[{{node anchors_3/add_2/eightbit}}]]
	 [[{{node filtered_detections/map/while/non_max_suppression_17/NonMaxSuppressionV3}}]]"
	debug_error_string = "{"created":"@1552348256.140400062","description":"Error received from peer","file":"src/core/lib/surface/call.cc","file_line":1017,"grpc_message":"Broadcast between [1,9,4] and [221,1,4] is not supported yet.\n\t [[{{node anchors_3/add_2/eightbit}}]]\n\t [[{{node filtered_detections/map/while/non_max_suppression_17/NonMaxSuppressionV3}}]]","grpc_status":12}"
```

**Comment by alexcpn** [comment]
Any update regarding this. I can help in someway conducting some tests

**Comment by lukemelas** [comment]
Any update on this?

**Comment by mohantym** [comment]
Hi @alexcpn !

We are checking to see whether you still need help in this issue . 
1.x versions are not supported anymore.  Have you checked the models from [Model](https://github.com/tensorflow/models) repo yet?

Thank you!
