### ISSUE TITLE
make test_micro_speech looping 

### ISSUE THREAD

**Issue by RobotEdh** [tensorflow/tensorflow#28271]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- Linux edh-VirtualBox 4.18.0-17-generic #18~18.04.1-Ubuntu SMP Fri Mar 15 15:27:12 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
- TensorFlow installed from (source or binary): Git
- TensorFlow version: 1.13.1
- Python version:Python 2.7.15rc1
- Installed using virtualenv? pip? conda?: pip
- Bazel version (if compiling from source): No
- GCC/Compiler version (if compiling from source): gcc version 7.3.0 (Ubuntu 7.3.0-27ubuntu1~18.04)
- CUDA/cuDNN version: No
- GPU model and memory: No

**Describe the problem**
The following command described in the **README** located in **tensorflow\lite\experimental\micro\examples\micro_speech** loops for ever:
_make -f tensorflow/lite/experimental/micro/tools/make/Makefile test_micro_speech_

**Provide the exact sequence of commands / steps that you executed before running into the problem**
I have followed the sequence described in the README:

1. make -f tensorflow/lite/experimental/micro/tools/make/Makefile
2. make -f tensorflow/lite/experimental/micro/tools/make/Makefile test_micro_speech

**Any other info / logs**

The reason is a "`while true`" in the source **micro_speech**

but the makefile should run micro_speech_test instead, so i think that the issue is in the makefile but i don't understant this makefile.

`.tensorflow/lite/experimental/micro/testing/test_linux_binary.sh tensorflow/lite/experimental/micro/tools/make/gen/linux_x86_64/bin/micro_speech '~~~ALL TESTS PASSED~~~'`

**Comment by wangtz** [comment]
Hi Robot,

Is this still an issue? In my recent test, I don't seem to be able to reproduce it.

**Comment by petewarden** [comment]
I think we recently fixed this, so closing, but reopen if you see a recurrence.
