### ISSUE TITLE
tf.print should indicate that it is printing tensor values

### ISSUE THREAD

**Issue by akshaym** [tensorflow/tensorflow#28289]
**System information**
- TensorFlow version (you are using): nightly
- Are you willing to contribute it (Yes/No): yes

**Describe the feature and the current behavior/state.**
Currently:
> tf.enable_v2_behavior()
> tf.print(tf.ones([0, 5, 256]))
[]

Preferred (similar to numpy):
> tf.enable_v2_behavior()
> tf.print(tf.ones([0, 5, 256]))
Tensor([])

**Will this change the current api? How?**
No, hopefully not. Even though the behavior is changed. 

**Who will benefit with this feature?**
Its confusing to have tensors print their values directly and I wasted some time thinking the value I was tf.print-ing was a python list.

**Any Other info.**
cc @tomerk

**Comment by dynamicwebpaige** [comment]
In the most recent version of TensorFlow 2.x, `print()` demonstrates the desired behavior, even though `tf.print` does not:

```python
print(tf.ones([0, 5, 256]))
```

**Comment by tomerk** [comment]
Also, just a note:

In numpy, print(array) actually prints in the form:
[]
Instead of in the form array([]).

array([]) is just the repl form.

E.g.
>>> print(np.ones((4, 5)))
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
>>> np.ones((4, 5))
array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])
