### ISSUE TITLE
[1.12] tensorflow.python.ops yielding strange results

### ISSUE THREAD

**Issue by NiklasDL** [tensorflow/tensorflow#28280]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution: Windows 10
- TensorFlow installed from (source or binary): Anaconda
- TensorFlow version (use command below): 1.12
- Python version:3.6.7
- CUDA/cuDNN version: 9.0
- GPU model and memory: K80

**Describe the current behavior**

I run the following code snipped:

```
import numpy as np
from tensorflow.python.framework import ops
from tensorflow.python.ops import random_ops
from tensorflow.python.ops import math_ops
from keras import backend as K

my_input = np.random.random((4, 2, 2, 3))
noise_shape = (my_input.shape[0], 1, 1, my_input.shape[3])
x = ops.convert_to_tensor(my_input, name="x")
rate = 0.51
random_tensor = random_ops.random_uniform(noise_shape, dtype=x.dtype)
K.eval(random_tensor)
```

which yields:

```
array([[[[0.64819453, 0.48363056, 0.44276874]]],

       [[[0.67051313, 0.53013834, 0.90202074]]],

       [[[0.39960238, 0.70830756, 0.70461008]]],

       [[[0.99692272, 0.80207655, 0.05433749]]]])
```

Now if I run

```
keep_mask = (random_tensor >= rate)
K.eval(math_ops.cast(keep_mask, x.dtype))
```

I obtain

```
array([[[[0., 0., 0.]]],

       [[[0., 1., 0.]]],

       [[[0., 0., 1.]]],

       [[[0., 0., 0.]]]])
```

**Describe the expected behavior**

I would expect the output of 

```
keep_mask = (random_tensor >= rate)
K.eval(math_ops.cast(keep_mask, x.dtype))
```

to be 

```
array([[[[1., 0., 0.]]],

       [[[1., 1., 1.]]],

       [[[0., 1., 1.]]],

       [[[1., 1., 0.]]]])
```

**Comment by jvishnuvardhan** [comment]
@NiklasDL I could reproduce the issue with TF1.12 and TF1.13. However, everything works as expected in TF2.0.0-alpha0 (GitHub gist is [here](https://colab.sandbox.google.com/gist/jvishnuvardhan/06da0e027b9a8818bfb1a3b2cfc3372f/untitled126.ipynb). Thanks!

**Comment by wangpengmit** [comment]
random_ops.random_uniform is a stateful op, so every K.eval on it (or a graph containing it) will return a different result. In your TF2 code, eager mode is on by default, so random_ops.random_uniform is evaluated only once. Note that random_ops.random_uniform is going to be replaced by new stateful random ops in https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/ops/stateful_random_ops.py (also see RFC https://github.com/tensorflow/community/blob/master/rfcs/20181217-tf2-random-numbers.md).

**Comment by NiklasDL** [comment]
@wangpengmit Thanks for the clarification.
