### ISSUE TITLE
Can not completely disable GPU & CUDA support. 

### ISSUE THREAD

**Issue by MrSlayer02** [tensorflow/tensorflow#2829]
This only applies to `TensorFlow 0.9`.

Even if you disable GPU support when configuring `TensorFlow`, you will still need CUDA to build it. Indeed, `Eigen::half` (half floats) should only be used when running on a GPU, it's not CPU-compatible. 

But they are always used, and this causes exceptions to be thrown if our `Eigen `version does not contains the `Eigen/src/arch/CUDA` folder and headers. (=You don't have CUDA installed).

Thanks for fixing this as fast as possible. If you need some other infos, just ask me.

**Comment by benoitsteiner** [comment]
@MrSlayer02 Eigen::half runs on both CPU and GPU. The code resides in a directory called CUDA purely for historical reasons. Moreover tensorflow 0.9 pulls a recent version of Eigen that contains the CUDA directory whether or not TensorFlow is compiled with CUDA support.

Can you document what you're trying to do as well as the symptoms that you experience ?

**Comment by MrSlayer02** [comment]
I was trying to install `TensorFlow 0.9` on a Raspberry Pi 3, but I got an error that told me g++ could not `static_cast` from `Eigen::half` to `float`. The header Half.h is not there in the pulled eigen version. 
Actually it seems TensorFlow declares `struct half` in `namespace Eigen` (header `strcat.h`) but does not instantiates it. Maybe this is normally done in Half.h...

**Comment by benoitsteiner** [comment]
This could be because the makefile used to compile TensorFlow on Raspberry Pi isn't up to date, so we end up pulling a very old version of Eigen instead of the correct one. Can you send me the command(s) you use to launch your build ? I'll take a look.

**Comment by MrSlayer02** [comment]
After installing bazel and protobuf, I used : 

- `git clone --recurse-submodules https://github.com/tensorflow/tensorflow`
- `grep -Rl 'lib64'| xargs sed -i 's/lib64/lib/g'`
- `sudo ./configure` ; I configured no Google Platform Support and no GPU support
- `sudo bazel build -c opt --local_resources 1024,1.0,1.0 --verbose_failures --ignore_unsupported_sandboxing --copt="-mfpu=neon" tensorflow/tools/pip_package:build_pip_package`

**Comment by samjabrahams** [comment]
It looks like the issue is with the Neon GCC compiler instruction. I was able to build TensorFlow 0.9rc0 today by simply taking out `--copt="-mfpu=neon"`. I'm not an expert in the GCC instructions for ARM, but I'll continue to look into options for various optimizations that may be possible without messing up the compiler.

@MrSlayer02 linked [his error log](http://pastebin.com/zUfP4xsP) in the parallel issue thread on the TF on RPi repo- you can see it's complaining about converting to a Neon type.
