### ISSUE TITLE
saved_model does not save and restore the state of the random number generator

### ISSUE THREAD

**Issue by quanvuong** [tensorflow/tensorflow#28302]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: NA
- TensorFlow installed from (source or binary): pip wheel
- TensorFlow version (use command below): 1.13.1
- Python version: 3.6.5
- Bazel version (if compiling from source): NA
- GCC/Compiler version (if compiling from source): NA
- CUDA/cuDNN version: NA
- GPU model and memory: NA (Running on CPU only)

**Describe the current behavior**

Using tf.saved_model to save session does not save the state of the random number generator associated with the graph that the session executes.

**Describe the expected behavior**

I was hoping to find a way to save and restore the state of the random number generator. 

**Code to reproduce the issue**

Given two files, save_rng.py and restore_rng.py as below:

save_rng.py

```
import tensorflow as tf
import tensorflow_probability as tfp

tf.set_random_seed(0)

sess = tf.Session()

base_dist = tfp.distributions.MultivariateNormalDiag(
    loc=tf.zeros(4),
    scale_diag=tf.ones(4)
)

samples_0 = base_dist.sample(sample_shape=(2))

builder = tf.saved_model.builder.SavedModelBuilder('./sess_save')

builder.add_meta_graph_and_variables(sess,
                                     [tf.saved_model.tag_constants.TRAINING])

builder.save()

samples_1 = base_dist.sample(sample_shape=(2))

out = sess.run([samples_0, samples_1])

print(out)
```

restore_rng.py

```
import tensorflow as tf
import tensorflow_probability as tfp

tf.set_random_seed(0)

sess = tf.Session()

base_dist = tfp.distributions.MultivariateNormalDiag(
    loc=tf.zeros(4),
    scale_diag=tf.ones(4)
)

tf.saved_model.loader.load(sess,
                           [tf.saved_model.tag_constants.TRAINING],
                           './sess_save')

samples_1 = base_dist.sample(sample_shape=(2))

out = sess.run(samples_1)

print(out)

```

save_rng.py is executed first, and then restore_rng.py.

1. If the state of the random number generator is saved and restored, then out[1] in save_rng.py should have the same value as out in restore_rng.py. But they don't contain the same values.

2. tf.saved_model.loader.load is definitely changing the state of the random number generator because out[0] in save_rng.py is not even equal to out in restore_rng.py, which should be equal otherwise because I'm setting the global level seed to 0.

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by allenlavoie** [comment]
@wangpengmit do we have stateless random distributions that are usable? And a guide or something to point people to?

For background, traditionally TF's random state has not been saveable. It has just lived in the kernels for the random operations. It also depends on the number of ops previously created in the graph, which may be the odd behavior you're seeing on load. We've recently added "stateless" versions of these operations which take the state as a Tensor. With that setup you can save the rng's state in a Variable and so in a SavedModel.

**Comment by wangpengmit** [comment]
@allenlavoie More precisely, we have a new *stateful* RNG (https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/ops/stateful_random_ops.py) that stores its state in tf.Variable and can be checkpointed. The only guide so far is the RFC (https://github.com/tensorflow/community/blob/master/rfcs/20181217-tf2-random-numbers.md) for it. We'll perhaps add a tutorial/guide in the future. There are also *stateless* RNGs (https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/ops/stateless_random_ops.py) that have existed for a while and may also suit your need.

**Comment by allenlavoie** [comment]
Maybe I'll start calling these "external-state" random ops if I remember. The point is that there's no state in the kernel itself, even if it modifies a variable.

**Comment by wangpengmit** [comment]
Closing this issue since the behavior is fixed by the new stateful ops and no work will be done to fix the old ones.

**Comment by jackd** [comment]
Is there an equivalent way to separate `tf.data.Dataset.shuffle` state?
