### ISSUE TITLE
Error .\tensorflow/compiler/xla/service/hlo_cost_analysis.h(42): error C2131 while building

### ISSUE THREAD

**Issue by MChaus** [tensorflow/tensorflow#28304]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): **Windows 10**
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: **Not mobile device**
- TensorFlow installed from (source or binary): **source**
- TensorFlow version: **r1.13**
- Python version: **3.6.8**
- Installed using virtualenv? pip? conda?: **virtualenv**
- Bazel version (if compiling from source):  **0.21.0**
- GCC/Compiler version (if compiling from source): **Оптимизирующий компилятор Microsoft (R) C/C++ версии 19.00.24234.1 для x64**
- CUDA/cuDNN version: **No CUDA**
- GPU model and memory: **No GPU**

**Describe the problem**
Hi!
I've tried to build tensorflow from source. I've installed all necessary tools but clashed with some errors while building tensorflow with XLA JIT support. 

**Provide the exact sequence of commands / steps that you executed before running into the problem**
My config looks like that:
**(.venv) C:\libs\tensorflow>python configure.py**

location of python. [Default is C:\libs\tensorflow\.venv\Scripts\python.exe]
Python library path to use.  Default is [C:\libs\tensorflow\.venv\Lib\site-packages]
XLA JIT support will be enabled for TensorFlow.
No ROCm support will be enabled for TensorFlow.
No CUDA support will be enabled for TensorFlow.
Default is /arch:AVX
Eigen strong inline overridden.

Then I started building process:
**(.venv) C:\libs\tensorflow>bazel build --config=opt //tensorflow/tools/pip_package:build_pip_package**

**Any other info / logs**
Error message looks like that:
...
.\tensorflow/compiler/xla/service/hlo_cost_analysis.h(42): error C2131: выражение не определяется константой
.\tensorflow/compiler/xla/service/hlo_cost_analysis.h(42): note: сбой был вызван значением указателя, не поддающимся анализу
.\tensorflow/compiler/xla/service/hlo_cost_analysis.h(43): error C2131: выражение не определяется константой
.\tensorflow/compiler/xla/service/hlo_cost_analysis.h(43): note: сбой был вызван значением указателя, не поддающимся анализу
.\tensorflow/compiler/xla/service/hlo_cost_analysis.h(44): error C2131: выражение не определяется константой
.\tensorflow/compiler/xla/service/hlo_cost_analysis.h(44): note: сбой был вызван значением указателя, не поддающимся анализу
.\tensorflow/compiler/xla/service/hlo_cost_analysis.h(45): error C2131: выражение не определяется константой
.\tensorflow/compiler/xla/service/hlo_cost_analysis.h(45): note: сбой был вызван значением указателя, не поддающимся анализу
...
Target //tensorflow/tools/pip_package:build_pip_package failed to build
INFO: Elapsed time: 1871,018s, Critical Path: 142,69s
INFO: 664 processes: 664 local.
FAILED: Build did NOT complete successfully

**Comment by muddham** [comment]
@MChaus Current master is TF1.13.1. checkout the master branch (not r1.13) and compile tensorflow from there?checkout the master branch (not r1.13) and compile tensorflow from there? Thanks!

**Comment by MChaus** [comment]
> @MChaus Current master is TF1.13.1. checkout the master branch (not r1.13) and compile tensorflow from there?checkout the master branch (not r1.13) and compile tensorflow from there? Thanks!

Unfortunately building TF from master branch didn't help. I have the same error. 
Also I checked git tag. The response of **git describe --tags** was:
v1.12.1-1110-g530d379ac1

Also I've updated my bazel. Now I have 0.24.1 version.

**Comment by muddham** [comment]
@MChaus The error trace log provided here is in other language, can you please repost in English.Also can you confirm which version of Microsoft Visual studio you have used. As per the build [link](https://tensorflow.google.cn/install/source_windows#cpu) Microsoft Visual studio is 2015.

**Comment by MChaus** [comment]
@muddham I have Microsoft VS Community 2017 with installed build tools for VC++ 2015.3. 
Build was started in command line VS2015 x64 Native Tools.

The translation of the log:

**Comment by muddham** [comment]
@MChaus Please refer the [link](https://github.com/tensorflow/tensorflow/issues/24890),install TF 2.0 nightly directly via pip and it works and see if it works

**Comment by MChaus** [comment]
@muddham I've installed latest stable version of TF last week via pip - tensorflow 1.13.1. It works fine, but I want to try build TF with additional configurations like MKL for further acceleration. 
I desided to start from the simpliest default version without any additional dependencies and got that errors.

**Comment by muddham** [comment]
@MChaus Could you please try installing TF using Conda [link](https://anaconda.org/anaconda/tensorflow-mkl). Please let us know how it progresses. Thanks!

**Comment by MChaus** [comment]
@muddham I've installed TF-mkl via Anaconda today and found out that it is 2 times slower than TF installed via pip. Maybe it's because I have AMD processor. Well, it looks like that I can use standard TF from pip without any inconveniences, but I can't build TF from source with custom configurations for today.

**Comment by preethivenkatesh** [comment]
@MChaus, our optimizations through MKL are built to accelerate performance on Intel Xeon processors. We don't support accelerations for other processors as of yet.

**Comment by jvishnuvardhan** [comment]
Closing this out since I understand it to be resolved, but please let me know if I'm mistaken. Please open a new issue if you notice any bug when you install TF from source. In this issue, you cannot use MKL to accelerate performance as it doesn't support AMD processor. Thanks!

**Comment by rlewkowicz** [comment]
@jvishnuvardhan 
Sorry to ping you all over the place, the bug is still a bug. Use conda doesn't resolve the esoteric compilation issues. 

I'm on an 8700k which supports both mkl and AVX. 

```
Execution platform: @bazel_tools//platforms:host_platform
.\tensorflow/compiler/xla/service/hlo_cost_analysis.h(42): error C2131: expression did not evaluate to a constant
.\tensorflow/compiler/xla/service/hlo_cost_analysis.h(42): note: failure was caused by unevaluable pointer value
.\tensorflow/compiler/xla/service/hlo_cost_analysis.h(43): error C2131: expression did not evaluate to a constant
.\tensorflow/compiler/xla/service/hlo_cost_analysis.h(43): note: failure was caused by unevaluable pointer value
.\tensorflow/compiler/xla/service/hlo_cost_analysis.h(44): error C2131: expression did not evaluate to a constant
.\tensorflow/compiler/xla/service/hlo_cost_analysis.h(44): note: failure was caused by unevaluable pointer value
.\tensorflow/compiler/xla/service/hlo_cost_analysis.h(45): error C2131: expression did not evaluate to a constant
.\tensorflow/compiler/xla/service/hlo_cost_analysis.h(45): note: failure was caused by unevaluable pointer value
Target //tensorflow/tools/pip_package:build_pip_package failed to build
```

Windows 10, bazel 24.1, cuda 10.0

**Comment by jvishnuvardhan** [comment]
@rlewkowicz No problem. Ping me when you need help.
Based on https://github.com/tensorflow/tensorflow/issues/28211#issuecomment-499219197, it seems XLA support was not built into TF builds related to Windows. It's better if you can open a new issue with details as the original issue was little different than what you have. Thanks!

**Comment by FishHe** [comment]
Closing XLA support at configure step helps.

> XLA support was not built into TF builds related to Windows. 

``` 
Do you wish to build TensorFlow with XLA JIT support? [y/N]: **N**
```
