### ISSUE TITLE
Installation gives me error

### ISSUE THREAD

**Issue by TomasRoj** [tensorflow/tensorflow#28308]
I am trying to install tensorflow with a pip in a virualvenv. Python version 3.7 running on windows 10. Error: (venv) C:\Users\rojto\PythonCLI>pip install --upgrade tensorflow
Collecting tensorflow
  ERROR: Could not find a version that satisfies the requirement tensorflow (from versions: none)
ERROR: No matching distribution found for tensorflow

**Comment by Dayananda-V** [comment]
@TomasRoj 

Please provide all of the information requested in the issue template. Thanks!

**Comment by TomasRoj** [comment]
I gave you everything you need. Os, platform and error message. No more informations needed,
