### ISSUE TITLE
tf.hessians fails when applied to the output of a RNN

### ISSUE THREAD

**Issue by csejourne** [tensorflow/tensorflow#28310]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: Yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Windows 10 and Ubuntu 18.04
- **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device**: No
- **TensorFlow installed from (source or binary)**: binary: conda install tensorflow
- **TensorFlow version (use command below)**: 1.13.1
- **Python version**: both 3.6.8 and 3.7.3
- **Bazel version (if compiling from source)**: None
- **GCC/Compiler version (if compiling from source)**: None
- **CUDA/cuDNN version**: None
- **GPU model and memory**: Not used
- **Exact command to reproduce**: none

### Describe the problem
I need to compute the hessians of a **tensor** output from a **RNN** structure w.r.t to its inputs. However, this leads to an error reported in the joint file. I think it is a bug as just replacing ``tf.hessians`` by ``tf.gradients`` leads to a working code.

I think it may be due to an low-level implementation of RNN cells with ``tf.while_loop``s, as indicated by the error.

### Source code / logs
```
import tensorflow as tf
from tensorflow.keras.layers import RNN, GRUCell, Dense

# Define size of variable. TODO: adapt to data
inp_dim = 2
num_units = 50
batch_size = 100
timesteps = 10

# Reset the graph, so as to avoid errors
tf.reset_default_graph()

inputs = tf.ones(shape=(timesteps, batch_size, inp_dim))

### Building the model
cells = [GRUCell(num_units), GRUCell(num_units)]
rnn = RNN(cells, time_major=True, return_sequences=True)
final_layer = Dense(1, input_shape=(num_units,))

# Apply to inputs
last_state = rnn(inputs)
f = final_layer(last_state)

[derivs] = tf.hessians(f, inputs)

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    grads = sess.run(derivs)
```
[stacktrace.log](https://github.com/tensorflow/tensorflow/files/3134827/stacktrace.log)

**Comment by csejourne** [comment]
I write this comment so as to provide an update on this issue. I narrowed down the issue do the simpler MWE I am posting just below. When computing an output **tensor** using a ``tf.map_fn``tools and applying ``tf.hessians`` to it w.r.t its inputs, the graph fails to construct. I don't need to use an eager execution or a ``tf.Session()`` 

```
import tensorflow as tf

# create output tensors
tf.reset_default_graph()
x = tf.constant([1., 2.])
f = tf.map_fn(lambda a: a**2, x)
g = x*x

# Compute gradients
d_fx = tf.gradients(f, x) # Works
d_gx = tf.gradients(g, x) # Works
dd_fx = tf.hessians(f, x) # Fails with same error as original issue
dd_gx = tf.hessians(g, x) # Works
```

I do not report the stacktrace, as it is the same as the one in the original post. 

PS: when updating the issue I create, should I edit my original post or create new comments?

**Comment by muddham** [comment]
@csejourne Able to reproduce this issue in 1.13 . We will look at it.

ValueError                                Traceback (most recent call last)
<ipython-input-2-ffbab77f1668> in <module>()
     10 d_fx = tf.gradients(f, x) # Works
     11 d_gx = tf.gradients(g, x) # Works
---> 12 dd_fx = tf.hessians(f, x) # Fails with same error as original issue
     13 dd_gx = tf.hessians(g, x) # Works

18 frames
/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/control_flow_util.py in CheckInputFromValidContext(op, input_op)
    312         input_op.name, "".join(traceback.format_list(input_op.traceback)))
    313     logging.info(log_msg)
--> 314     raise ValueError(error_msg + " See info log for more details.")

ValueError: Cannot use 'while/gradients/f_count_1' as input to 'while/gradients/f_count' because they are in different while loops. See info log for more details.

**Comment by csejourne** [comment]
I thought of a workaround about this one. Maybe using the argument ``unroll=True`` would allow to bypass this error. However, I tried and got the input shape wrong, so I can't say for now if it would work on now. I´ll get back to you

**Comment by csejourne** [comment]
Ok, so I got two different workaround that allow to compute ``tf.hessians`` w.r.t the inputs.

### First workaround

Using ``unroll=True`` prevents Tensorflow from creating the symbolic ``tf.while_loop`` as said in the documentation. Without this symbolic loop, the following code runs smoothly.

```
import tensorflow as tf
from tensorflow.keras.layers import RNN, GRUCell, Dense

# Define size of variable. TODO: adapt to data
inp_dim = 2
num_units = 50
batch_size = 100
timesteps = 10

# Reset the graph, so as to avoid errors
tf.reset_default_graph()

inputs = tf.ones(shape=(timesteps, batch_size, inp_dim))

### Building the model
cell = GRUCell(num_units)
rnn = RNN(cell, time_major=True, unroll=True)
final_layer = Dense(1, input_shape=(num_units,))

# Apply to inputs
last_state = rnn(inputs)
f = final_layer(last_state)

[derivs] = tf.hessians(f, inputs)

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    grads = sess.run(derivs)
```

However for my need I needed to discard the time dimension (i.e remove it or set it to 1). It is at the moment not possible to unroll the RNN when ``time_dimension in [None, 1]``. For this reason, I just did the following workaround.

#### Second workaround

```
import tensorflow as tf
from tensorflow.keras.layers import RNN, GRUCell, Dense

# Define size of variable. TODO: adapt to data
inp_dim = 2
num_units = 50
batch_size = 100
# Reset the graph, so as to avoid errors
tf.reset_default_graph()

state = [tf.Variable(tf.zeros((batch_size, num_units)))]
inputs = tf.ones(shape=(batch_size, inp_dim))

### Building the model
cells = [GRUCell(num_units), GRUCell(num_units)]

_, temp = cells[0](inputs, state)
f, _ = cells[1](inputs, temp)

[derivs] = tf.hessians(f, inputs)

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    grads = sess.run(derivs)
```

This just consists of chaining a la mano the different cells used. It also works smoothly

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this issue, as you are using an older version of tensorflow(1.x) which is officially considered as end of life. We recommend that you upgrade to 2.4 or later version and let us know if the issue still persists in newer versions. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, Please open a new issue for any help you need against 2.x, and we will get you the right help.
