### ISSUE TITLE
3D CNN with tf.nn.conv3d_transpose on CPU: 50-100 GB RAM free but segfault + "terminate called after throwing an instance of 'std::bad_alloc' what(): std::bad_alloc"

### ISSUE THREAD

**Issue by TeoZosa** [tensorflow/tensorflow#28313]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): **YES**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): **Linux Ubuntu 18.04 (three machines) & Windows 10 Pro (two machines)**
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: **N/A**
- TensorFlow installed from (source or binary): **binary; tensorflow-gpu2.0.0alpha0 (Windows machines), tensorflow/tensorflow:2.0.0a0-py3-jupyter docker image (Ubuntu 18.04 machines)**
- TensorFlow version (use command below): **v1.12.0-9492-g2c319fb415 2.0.0-alpha0 (Windows)**
- Python version: **3.6.4 (Windows)**
- Bazel version (if compiling from source): **N/A**
- GCC/Compiler version (if compiling from source): **N/A**
- CUDA/cuDNN version: **10/7.4.1 (Windows); N/A (Ubuntu 18.04)**
- GPU model and memory: **Titan RTX (Windows machine 1); GTX 1080 (Windows machine 2); CPU-only (Ubuntu 18.04 machines 1-3)**

All machines specs:
- CPUs: **Dual socket, 8 cores each CPU (Xeon E5-2670, E5-2687w on the machine with the Titan RTX), 32 total logical processors.** 
- RAM: **128 GB**  

**Describe the current behavior**

3D CNN with deconvolution (tf.nn.conv3d_transpose) to upsample 1 channel volumes x2 in all three dimensions. Training on GPU and using 64^3 image patches works fine. For inference I moved ops to the CPU in order to handle large volumes that wouldn't otherwise fit in GPU memory. But now I have run into the below errors:

1. Frequent crashes when using more than 50% of available CPU cores. On Ubuntu 18.04 it completely kills the node and I have to physically power cycle the machine. On Windows, I'm lucky if it doesn't freeze indefinitely at a blue screen. 

2. Visual bug for inputs >~130^3 (generally whenever it gives me a warning that I'm allocating >10% of system memory) where the last slices of the volume converge to intensity ~ 0.39 (coincidentally, very close to a constant that the model adds to the output to correct for grayscale intensity). This get progressively worse with larger volumes (~130^3 < dims < ~175^3)

3. Segfault for inputs > ~175^3. 
Example output: 

**On Windows:** 
2019-04-26 14:56:19.461143: W tensorflow/core/framework/allocator.cc:124] Allocation of 20320616448 exceeds 10% of system memory.
2019-04-26 14:58:23.532021: W tensorflow/core/framework/allocator.cc:124] Allocation of 20320616448 exceeds 10% of system memory.
2019-04-26 14:58:23.532021: W tensorflow/core/framework/allocator.cc:124] Allocation of 20320616448 exceeds 10% of system memory.
Segmentation Fault

Note: It once gave me a popup with an error of the form, "Instruction at 0xDED referenced memory at 0XBEEF. The memory could not be read".   

**On Ubuntu 18.04: ** 
2019-05-01 02:29:47.571830: W tensorflow/core/framework/allocator.cc:116] Allocation of 26311577600 exceeds 10% of system memory.
terminate called after throwing an instance of 'std::bad_alloc' what(): std::bad_alloc

**Note:** I generally still have 50-100 GB of free memory when these errors occur so it's not for lack of memory. 
**Note:**: I have replicated this phenomenon across all machines using just CPU. On the Windows machines, I get the same results when I have attempted to move all ops to the GPU save for deconvolution (which will not fit on the GPU).

**Describe the expected behavior**
No crashing, processing large inputs if available resources allow. 

**Code to reproduce the issue**
N/A

**Other info / logs**
N/A

**Comment by TeoZosa** [comment]
Still experiencing this issue. Running same tests on an AWS instance (r4.4xlarge).  New error using the docker image (tensorflow/tensorflow:2.0.0a0-py3-jupyter): *** Error in `python': munmap_chunk(): invalid pointer: 0x00007fb8d4794040 *** (see attached log for a full stack trace top resource usage at time of crash
[051519_AWS_docker_crash_stack_trace_TF_issues.txt](https://github.com/tensorflow/tensorflow/files/3184641/051519_AWS_docker_crash_stack_trace_TF_issues.txt)
![051519_AWS_docker_crash_top_TF_issues](https://user-images.githubusercontent.com/13070236/57813253-516aea00-7724-11e9-9d55-85e1c3f32210.png)

)

**Comment by TeoZosa** [comment]
Update: tested both the pre-compiled binary (tensorflow2.0.0a0) and different versions of building from source (w & w/o XLA JIT support, --config=opt --config=numa, --config=numa, --config=opt) all with the same resource utilization and error as above.

**Comment by TeoZosa** [comment]
Update: A _semi-_solution on the AWS instance involving compiling with the Intel MKL-DNN solves the gray issue as well as the crashing issue (in some cases; see below). 

BUT it requires >5x the amount of RAM and is >2x slower. Additionally, memory is not deallocated immediately, causing crashes when there is a queue of input samples. The huge increase in required RAM usages causes crashes for larger inputs that a normal tensorflow build would theoretically have been able to handle if not for this bug.

**Comment by TeoZosa** [comment]
Update: Now there is another bug where inference results are artifacted (see attached; should be completely black)

![051719_artifacts_TF_issues](https://user-images.githubusercontent.com/13070236/57960418-79da1c00-78bd-11e9-9987-05fd8b33d95b.png)

configs file for MKL-DNN & TF: 

import os
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()
threads = 64
sockets = 2
args =  tf.ConfigProto(
  allow_soft_placement=True,
  log_device_placement=False,
  intra_op_parallelism_threads=threads,# Setting this equal to the number of physical cores is recommended. Setting the value to 0, which is the default, results in the value being set to the number of logical cores - this is an alternate option to try for some architectures. This value and OMP_NUM_THREADS should be equal.
  inter_op_parallelism_threads=sockets, #Setting this equal to the number of sockets is recommended. Setting the value to 0, which is the default, results in the value being set to the number of logical cores.
  gpu_options=(tf.GPUOptions(allow_growth=True)
               ))
os.environ["KMP_BLOCKTIME"] = '0'
os.environ["KMP_SETTINGS"] = '1'
os.environ["KMP_AFFINITY"]=  'granularity=fine,verbose,compact,1,0'
os.environ["OMP_NUM_THREADS"]= str(threads)

**Comment by TeoZosa** [comment]
May be related to: #21637

**Comment by TeoZosa** [comment]
Update:

XLA JIT compilation of the CPU deconvolution ops FIXES the problem altogether (no empty slices from the original bug, no checkerboard artifacts from the MKL-DNN bug) BUT is now an order of magnitude slower (~200 minutes vs. 4 minutes) and still allocates much more memory than a normal tensorflow inference, so this unfortunately not a feasible solution.

**Comment by TeoZosa** [comment]
Any ideas on where to go next?

**Comment by tanzhenyu** [comment]
@jvishnuvardhan I don't have expertise on this thus unassigning myself.

**Comment by TeoZosa** [comment]
Anyone?

**Comment by sushreebarsa** [comment]
@TeoZosa It looks like you are using an older Version of Tensorflow. Many bugs have been fixed in the latest version. Could you please execute your code using Latest Version 2.4.1 or 2.5 and let us know if the issue still persists? Thanks!
