### ISSUE TITLE
[TF 2.0 API Docs] tf.image.extract_image_patches

### ISSUE THREAD

**Issue by hendercine** [tensorflow/tensorflow#28314]
### Existing URLs containing the issue:
https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/image/extract_image_patches

### Description of issue (what needs changing):

- #### Clear Description
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Only a single sentence description is provided.

- #### Usage Example
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;No usage example is provided.

- #### Raises Listed and Defined
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Errors are not defined.

- #### Visuals, if Applicable
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;No visuals are included.

**Comment by seanpmorgan** [comment]
Thanks for identifying this!

@dynamicwebpaige Should we be marking API issues using the r2.0 branch or master? I'm not sure it matters for the most part, but just as an example I believe this API will be `tf.image.extract_patches` on TF2 release.
https://github.com/tensorflow/tensorflow/commit/52d006a310b8ef6b8bbe48911a183215c4494943#diff-68052049ee5dc7573829a5fdb7a57310

**Comment by hendercine** [comment]
My pleasure, Sean. Very good question regarding the branch. I totally
forgot to check the branch onto which I was adding the issue. I'd be happy
to resubmit to a development branch.

**Comment by amahendrakar** [comment]
@hendercine,
Is this still an issue?

Please take a look at similar API [tf.image.extract_patches](https://www.tensorflow.org/api_docs/python/tf/image/extract_patches) which has a clear description and usage example. Thanks!
