### ISSUE TITLE
tf2.0 get numpy from tensor

### ISSUE THREAD

**Issue by jinfagang** [tensorflow/tensorflow#28311]
How to get the numpy from tensor? it says there is no numpy method. as far as I know, tf2.0 does not encourage users using session anymore, so how to get the acutally value from a tensor?

```python

import tensorflow as tf
import tensorflow_datasets as tfds


dataset, metadata = tfds.load('fashion_mnist', as_supervised=True, with_info=True)
train_dataset, test_dataset = dataset['train'], dataset['test']

train_dataset = train_dataset.shuffle(100).batch(12).repeat()

for img, label in train_dataset.take(1):
    img = img.numpy()
    print(img.shape)
    print(img)
    

```

error:

```
 img = img.numpy()
AttributeError: 'Tensor' object has no attribute 'numpy'
```

**Comment by captain-pool** [comment]
> How to get the numpy from tensor? it says there is no numpy method. as far as I know, tf2.0 does not encourage users using session anymore, so how to get the acutally value from a tensor?
> 
> ```python
> import tensorflow as tf
> import tensorflow_datasets as tfds
> 
> 
> dataset, metadata = tfds.load('fashion_mnist', as_supervised=True, with_info=True)
> train_dataset, test_dataset = dataset['train'], dataset['test']
> 
> train_dataset = train_dataset.shuffle(100).batch(12).repeat()
> 
> for img, label in train_dataset.take(1):
>     img = img.numpy()
>     print(img.shape)
>     print(img)
>     
> ```
> 
> error:
> 
> ```
>  img = img.numpy()
> AttributeError: 'Tensor' object has no attribute 'numpy'
> ```

Please include the following details.
1. print(tf.__version__)
2. Is it running in Graph Mode or Eager Mode? (You can check that by printing `type(img)` before calling `.numpy()`.

**Comment by jvishnuvardhan** [comment]
@jinfagang As mentioned by @captain-pool , you might be using Graph Mode. If you have installed TF2.0, then running your code produces output as expected.
`print(img.shape)` ==> `(12, 28, 28, 1)`
`type(img)`            ==> `numpy.ndarray`

Here is GitHub [gist](https://colab.sandbox.google.com/gist/jvishnuvardhan/11f4737679237250cff63aba0e6714b0/untitled129.ipynb). You could run it in Google colab and see the results. Thanks!

In future, please post this kind of support questions in [Stackoverflow](https://stackoverflow.com/questions/tagged/tensorflow). There is a big community to support and learn from your questions. GitHub is mainly for addressing bugs in installation and performance. Thanks!

**Comment by jinfagang** [comment]
@jvishnuvardhan  Thanks, I will, but since I already in tf2.0 but can not get value instantly which is not same with what tensorflow 2.0 claims.

type(img) got something like this:

```
(416, 416, 3)
<class 'tensorflow.python.framework.ops.Tensor'>
```

**Comment by ywangeq** [comment]
@jinfagang  Me too. I can not get the numpy value from tensor due to the .numpy() which is different in the former version with eager version

**Comment by ywangeq** [comment]
@jinfagang but you can check whether the function was wrapped by '@tf.function'

**Comment by hurleyLi** [comment]
is there any way to use .numpy() within a function decorated by @tf.function?

**Comment by captain-pool** [comment]
Hey Hurley! Nope there isn't .numpy() is a function available to
EagerTensors However once decorated with @tf.function, the function becomes
a graph Tensor.

**Comment by hurleyLi** [comment]
Thanks for the response @captain-pool !
What I really wanted is to be able to get values from a tensor, for example: in
```
tf.random.fixed_unigram_candidate_sampler(
    ...
    unigrams=()
)
```
`unigrams` accept a list of values, and I'd like to provide `unigrams` with values calculated from Tensor calculations, but it's not possible to implement within a @tf.function in tf2.0. 

If there any way to work this around so I can get values from a Tensor while within a function decorated by @tf.function?

Thanks for your time!
Hurley

**Comment by captain-pool** [comment]
> Thanks for the response @captain-pool !
> What I really wanted is to be able to get values from a tensor, for example: in
> 
> ```
> tf.random.fixed_unigram_candidate_sampler(
>     ...
>     unigrams=()
> )
> ```
> 
> `unigrams` accept a list of values, and I'd like to provide `unigrams` with values calculated from Tensor calculations, but it's not possible to implement within a @tf.function in tf2.0.
> 
> If there any way to work this around so I can get values from a Tensor while within a function decorated by @tf.function?
> 
> Thanks for your time!
> Hurley

Hey @hurleyLi , I'm not sure about it, any TensorFlow function should be able to take tensors in value fields.
CC: @jinfagang

**Comment by jvishnuvardhan** [comment]
Please open an new issue by filling [issue template](https://github.com/tensorflow/tensorflow/issues/new/choose) with your details, and provide a simple standalone code to reproduce the issue. Thanks!

**Comment by yourtheron** [comment]
I encounter the same issue. I wrote a custom loss function and I want to see its returned value, 
```
	for ep in range(epoch):
		print('Start of epoch %d' % (ep,))
		# Each step crosses one minibatch
		for step, data in enumerate(dsTrain):
			yPred = TUNet(data[0])
			loss = SoftDiceLoss(yPred, data[1])
			print(loss)
```
The TUNet was built by keras' layers, and SoftDiceLoss() is implemented by tf tensors
```
		def SoftDiceLoss(yPred, yTrue):
			'''
			SoftDiceLoss calculates multi-class soft dice loss
			loss = avg_batch(1-(sum(W_k*sum(yPred.*yTrue)))/(sum(W_ksum(yPred^2+yTrue^2))))
			where W_k = 1/(number of voxels in class k)^2
		   Class number of segmented regions includes background
			Input:
				yPred/yTrue: prediced and desired outputs shaped as [mbSize, classNum, tensor dimensions]. Also, both must be float-point
			Return:
				loss: a scalar
			'''
			epsilon = 1e-16 
			yTrue =tf.dtypes.cast(yTrue, dtype=yPred.dtype)
			# Dot product yPred and yTrue and sum them up for each datum and class
			crossProd=tf.multiply(yPred, yTrue)
			# As a symbolic tensor, dimensions and shapes etc. cannot be extracted from data, nor can it be used in subroutines.
			crossProdSum=tf.math.reduce_sum(crossProd, axis=np.arange(2, 5))
			# Calculate weight for each datum and class 
			weight = tf.math.reduce_sum(yTrue, axis=np.arange(2, 5))
			weight = tf.math.divide(1, tf.math.square(weight)+epsilon)
			# Weighted sum over classes
			numerator = 2*tf.math.reduce_sum(tf.multiply(crossProdSum, weight), axis=1)
			# Saquared summation 
			yySum = tf.math.reduce_sum(tf.math.square(yPred) + tf.math.square(yTrue), axis=np.arange(2, 5))
			# Weighted sum over classes
			denominator = tf.math.reduce_sum(tf.multiply(weight, yySum), axis=1)
			# Get individual loss and average over minibatch
			loss = tf.math.reduce_mean(1 - tf.math.divide(numerator, denominator+epsilon))
			
			return loss
```
So how can I see the loss value?

**Comment by RaymondJiangkw** [comment]
Maybe `numpy.asarray` will help.

**Comment by khaniamir** [comment]
> 
> 
> Maybe `numpy.asarray` will help.

This method does not work.
The tensor cannot be converted to an array by asarray

**Comment by RaymondJiangkw** [comment]
> > Maybe `numpy.asarray` will help.
> 
> This method does not work.
> The tensor cannot be converted to an array by asarray

I do not know whether I fully understand the condition in which this problem is raised. But based on my experience, it does work. If there is any misunderstanding, I apologize first.

For a simple example,
`import numpy as np`
`import tensorflow as tf`
`from tensorflow.keras.layers import Dense`
`from tensorflow.keras.models import Sequential`

`X = 10 * np.random.rand(10000,1)`
`Y = 2 * X + 1`

`model = Sequential([`
`    Dense(3),`
`    Dense(1)`
`])`
`model.compile(optimizer='adam',loss='mean_squared_error',metric = 'accuracy')`
`model.fit(X,Y,epochs = 10)`

`output = model(np.array([[2]]))`

`print(output)`
`# tf.Tensor([[5.050682]], shape=(1, 1), dtype=float32)`

`print(np.asarray(output))`
`# [[5.050682]]` `

**Comment by tvrbanec** [comment]
> `print(np.asarray(output))`

NotImplementedError: Cannot convert a symbolic Tensor (module_apply_default/truediv:0) to a numpy array. This error may indicate that you're trying to pass a Tensor to a NumPy call, which is not supported
