### ISSUE TITLE
The source code compiles tensorflow off tensorrt is invalid.

### ISSUE THREAD

**Issue by wangguangyuan** [tensorflow/tensorflow#28329]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- TensorFlow installed from (source or binary):
- TensorFlow version: master branch
- Python version:3.6
- Bazel version (if compiling from source):0.24
- CUDA/cuDNN version:10.0/7.5
- GPU model and memory:12G

When the source code compiles tensorflow, it closes TensorRT through the prompt of ./configure. But still reports: Could not find any NvInfer.h matching version '' in any subdirectory error.

Configure option：

./configure 
WARNING: --batch mode is deprecated. Please instead explicitly shut down your Bazel server using the command "bazel shutdown".
You have bazel 0.24.1 installed.
Please specify the location of python. [Default is /home/guangyuan/anaconda3/envs/tfsource/bin/python]: 

Found possible Python library paths:
  /home/guangyuan/anaconda3/envs/tfsource/lib/python3.6/site-packages
Please input the desired Python library path to use.  Default is [/home/guangyuan/anaconda3/envs/tfsource/lib/python3.6/site-packages]

Do you wish to build TensorFlow with XLA JIT support? [Y/n]: y
XLA JIT support will be enabled for TensorFlow.

Do you wish to build TensorFlow with OpenCL SYCL support? [y/N]: n
No OpenCL SYCL support will be enabled for TensorFlow.

Do you wish to build TensorFlow with ROCm support? [y/N]: n
No ROCm support will be enabled for TensorFlow.

Do you wish to build TensorFlow with CUDA support? [y/N]: y
CUDA support will be enabled for TensorFlow.

**Do you wish to build TensorFlow with TensorRT support? [y/N]: n**
No TensorRT support will be enabled for TensorFlow.

Error:
**Could not find any NvInfer.h matching version '' in any subdirectory:**
        ''
        'include'
        'include/cuda'
        'include/*-linux-gnu'
        'extras/CUPTI/include'
        'include/cuda/CUPTI'
of:
        '/lib'
        '/lib/x86_64-linux-gnu'
        '/lib32'
        '/libx32'
        '/usr'
        '/usr/lib'
        '/usr/lib/x86_64-linux-gnu'
        '/usr/lib/x86_64-linux-gnu/libfakeroot'
        '/usr/lib32'
        '/usr/libx32'
        '/usr/local/cuda-10.0'
        '/usr/local/zlib/lib'
Asking for detailed CUDA configuration...

**Comment by wdirons** [comment]
This should have been fixed by this commit: https://github.com/tensorflow/tensorflow/commit/28fc9cccd176a113b9f0401d0c569ca1b9d207c3

Please try pulling the latest code.

**Comment by achandraa** [comment]
Please let us know if you are still facing the problem. Thanks!

**Comment by achandraa** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
