### ISSUE TITLE
Random Uniform Not Supported for TFlite Conversion

### ISSUE THREAD

**Issue by futuyao** [tensorflow/tensorflow#28324]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04
- TensorFlow installed from (source or binary): source
- TensorFlow version (or github SHA if from source): tf-nightly 1.14.0-rc0

**Provide the text output from tflite_convert**

```
Some of the operators in the model are not supported by the standard TensorFlow Lite runtime and are not recognized by TensorFlow. If you have a custom implementation for them you can disable this error with --allow_custom_ops, or by setting allow_custom_ops=True when calling tf.lite.TFLiteConverter(). Here is a list of builtin operators you are using: ADD, AVERAGE_POOL_2D, BATCH_TO_SPACE_ND, CAST, CONCATENATION, CONV_2D, FULLY_CONNECTED, GREATER_EQUAL, MUL, RESHAPE, RESIZE_BILINEAR, SPACE_TO_BATCH_ND. Here is a list of operators for which you will need custom implementations: RandomUniform.
```

Also, please include a link to a GraphDef or the model if possible.

**Any other info / logs**

I followed [#26300](https://github.com/tensorflow/tensorflow/issues/26300) by using
```
converter.target_ops = [tf.lite.OpsSet.TFLITE_BUILTINS,
                        tf.lite.OpsSet.SELECT_TF_OPS]
```
But I still can't create .tflite file correctly.

**Comment by futuyao** [comment]
There's a warning from lite/toco/graph_transformations/resolve_constant_random_uniform.cc

`RandomUniform op outputting "segmentation_dropout/random_uniform/RandomUniform" is truly random (using /dev/random system entropy). Therefore, cannot resolve as constant. Set "seed" or "seed2" attr non-zero to fix this`

**Comment by gadagashwini** [comment]
@futuyao In order to expedite the trouble-shooting process,Please provide the detail error message. Thanks!

**Comment by futuyao** [comment]
Resolved by downgrading Tensorflow version to r1.13.

**Comment by futuyao** [comment]
I can now convert the model to tflite with select tensorflow operators. But when I try to load the model in XCode for iOS, it sill can't find Random Uniform operator.

`Didn't find custom op for name 'RandomUniform' with version 1`

**Comment by futuyao** [comment]
I can now convert the model to tflite with select tensorflow operators. But when I try to load the model in XCode for iOS, it sill can't find Random Uniform operator.

`Didn't find custom op for name 'RandomUniform' with version 1`

**Comment by haozha111** [comment]
Sorry for the late reply!

Could you provide with us the .tflite flabuffer or the original GraphDef you are usin(assuming it's not confidential), so that I can give it a try.

**Comment by futuyao** [comment]
> Sorry for the late reply!
> 
> Could you provide with us the .tflite flabuffer or the original GraphDef you are usin(assuming it's not confidential), so that I can give it a try.

I have my tflite file here: https://drive.google.com/file/d/1yIjABOGxUTP81O0gJeaRHFayoNLiDKIi/view?usp=sharing

Thanks!

**Comment by haozha111** [comment]
Sorry for the late.

It seems like the iOS app is not built with the select TF ops (RandomUniform), so it can't resolve the op at runtime.

Could you follow instructions here and try again? Thanks.
https://www.tensorflow.org/lite/guide/ops_select#ios

**Comment by jaeyoo** [comment]
Hi, @futuyao

Sorry for the belated. Is ios ops_select working for your model?

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this issue, as you are using an older version of tensorflow(1.x) which is officially considered as end of life. We recommend that you upgrade to 2.4 or later version and let us know if the issue still persists in newer versions. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, Please open a new issue for any help you need against 2.x, and we will get you the right help.
