### ISSUE TITLE
Distributed Training TF2.0 Input Pipeline Bug

### ISSUE THREAD

**Issue by KUASWoodyLIN** [tensorflow/tensorflow#28334]
System information

OS Platform and Distribution: Docker-nvidia(2.0.0a0-gpu-py3)
TensorFlow version: '2.0.0-alpha0'
Python version: 3.5.2
CUDA/cuDNN version: 10.0

Hello I'm trying the [Code](https://github.com/tensorflow/docs/blob/master/site/en/r2/tutorials/distribute/keras.ipynb) here.
Ant it come out **error info**.
```
WARNING: Logging before flag parsing goes to stderr.
W0502 07:45:49.047524 140435350275840 distributed_training_utils.py:182] Your input callback is not one of the predefined Callbacks that supports DistributionStrategy. You might encounter an error if you access one of the model's attributes as part of the callback since these attributes are not set. You can access each of the individual distributed models using the `_grouped_model` attribute of your original model.
W0502 07:45:49.050312 140435350275840 distributed_training_utils.py:182] Your input callback is not one of the predefined Callbacks that supports DistributionStrategy. You might encounter an error if you access one of the model's attributes as part of the callback since these attributes are not set. You can access each of the individual distributed models using the `_grouped_model` attribute of your original model.
W0502 07:45:49.052523 140435350275840 distributed_training_utils.py:182] Your input callback is not one of the predefined Callbacks that supports DistributionStrategy. You might encounter an error if you access one of the model's attributes as part of the callback since these attributes are not set. You can access each of the individual distributed models using the `_grouped_model` attribute of your original model.
Epoch 1/10
      1/Unknown - 5s 5s/step - loss: 2.2896 - accuracy: 0.1406
W0502 07:45:57.873010 140435350275840 callbacks.py:236] Method (on_train_batch_end) is slow compared to the batch update (0.178479). Check your callbacks.
    468/Unknown - 9s 19ms/step - loss: 0.2455 - accuracy: 0.9304
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-16-d96263311d23> in <module>
----> 1 model.fit(train_dataset, epochs=10, callbacks=callbacks)

/usr/local/lib/python3.5/dist-packages/tensorflow/python/keras/engine/training.py in fit(self, x, y, batch_size, epochs, verbose, callbacks, validation_split, validation_data, shuffle, class_weight, sample_weight, initial_epoch, steps_per_epoch, validation_steps, validation_freq, max_queue_size, workers, use_multiprocessing, **kwargs)
    744             steps_per_epoch=steps_per_epoch,
    745             validation_steps=validation_steps,
--> 746             validation_freq=validation_freq)
    747 
    748     batch_size = self._validate_or_infer_batch_size(

/usr/local/lib/python3.5/dist-packages/tensorflow/python/keras/engine/training_distributed.py in fit_distributed(model, x, y, batch_size, epochs, verbose, callbacks, validation_split, validation_data, shuffle, class_weight, sample_weight, initial_epoch, steps_per_epoch, validation_steps, validation_freq)
    129         validation_steps=validation_steps,
    130         validation_freq=validation_freq,
--> 131         steps_name='steps_per_epoch')
    132 
    133 

/usr/local/lib/python3.5/dist-packages/tensorflow/python/keras/engine/training_arrays.py in model_iteration(model, inputs, targets, sample_weights, batch_size, epochs, verbose, callbacks, val_inputs, val_targets, val_sample_weights, shuffle, initial_epoch, steps_per_epoch, validation_steps, validation_freq, mode, validation_in_fit, prepared_feed_values_from_dataset, steps_name, **kwargs)
    260         try:
    261           # `ins` can be callable in DistributionStrategy + eager case.
--> 262           actual_inputs = ins() if callable(ins) else ins
    263           batch_outs = f(actual_inputs)
    264         except errors.OutOfRangeError:

/usr/local/lib/python3.5/dist-packages/tensorflow/python/keras/engine/training_arrays.py in get_distributed_inputs()
    470     def get_distributed_inputs():
    471       return distributed_training_utils._prepare_feed_values(
--> 472           model, inputs, targets, sample_weights, mode)
    473 
    474     # In the eager case, we want to call the input method per step, so return

/usr/local/lib/python3.5/dist-packages/tensorflow/python/keras/engine/distributed_training_utils.py in _prepare_feed_values(model, inputs, targets, sample_weights, mode)
    565   """
    566   strategy = model._distribution_strategy
--> 567   inputs, targets, sample_weights = _get_input_from_iterator(inputs, model)
    568   inputs = flatten_perdevice_values(strategy, inputs)
    569   targets = flatten_perdevice_values(strategy, targets)

/usr/local/lib/python3.5/dist-packages/tensorflow/python/keras/engine/distributed_training_utils.py in _get_input_from_iterator(iterator, model)
    547   # Validate that all the elements in x and y are of the same type and shape.
    548   validate_distributed_dataset_inputs(
--> 549       model._distribution_strategy, x, y, sample_weights)
    550   return x, y, sample_weights
    551 

/usr/local/lib/python3.5/dist-packages/tensorflow/python/keras/engine/distributed_training_utils.py in validate_distributed_dataset_inputs(distribution_strategy, x, y, sample_weights)
    247   # If each element of x and y are not tensors, we cannot standardize and
    248   # validate the input and targets.
--> 249   x_values_list = validate_per_device_inputs(distribution_strategy, x)
    250 
    251   if y is not None:

/usr/local/lib/python3.5/dist-packages/tensorflow/python/keras/engine/distributed_training_utils.py in validate_per_device_inputs(distribution_strategy, x)
    294 
    295     # Validate that the shape and dtype of all the elements in x are the same.
--> 296     validate_all_tensor_shapes(x, x_values)
    297     validate_all_tensor_types(x, x_values)
    298 

/usr/local/lib/python3.5/dist-packages/tensorflow/python/keras/engine/distributed_training_utils.py in validate_all_tensor_shapes(x, x_values)
    315     if x_shape != x_values[i].get_shape().as_list():
    316       raise ValueError('Input tensor shapes do not match for distributed tensor'
--> 317                        ' inputs {}'.format(x))
    318 
    319 

ValueError: Input tensor shapes do not match for distributed tensor inputs PerReplica:{
  0 /job:localhost/replica:0/task:0/device:GPU:0: tf.Tensor(
[[[[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]
   ...
   [0.]
   [0.]
   [0.]]]], shape=(64, 28, 28, 1), dtype=float32),
  1 /job:localhost/replica:0/task:0/device:GPU:1: tf.Tensor(
[[[[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]
   ...
   [0.]
   [0.]
   [0.]]]], shape=(32, 28, 28, 1), dtype=float32)
}
```

it because gpu0 and gpu1 can't get the same shape, 
so I modify Input pipeline, add `.repeat(2)` in the pipeline
```
train_dataset = mnist_train.repeat(2).map(scale).shuffle(BUFFER_SIZE).batch(BATCH_SIZE)
```
and it work!

but I think the Input pipeline should repeat by itself.

**Comment by muddham** [comment]
@KUASWoodyLIN I ran the google colab link provided using gpu and it went through without any errors and no modifications are done to the code. can you please check and let us know.

W0503 10:49:24.512632 139824653981568 distributed_training_utils.py:182] Your input callback is not one of the predefined Callbacks that supports DistributionStrategy. You might encounter an error if you access one of the model's attributes as part of the callback since these attributes are not set. You can access each of the individual distributed models using the `_grouped_model` attribute of your original model.
Epoch 1/10
      1/Unknown - 6s 6s/step - loss: 2.2981 - accuracy: 0.0781W0503 10:49:32.975298 139824653981568 callbacks.py:236] Method (on_train_batch_end) is slow compared to the batch update (0.298758). Check your callbacks.
    938/Unknown - 21s 23ms/step - loss: 0.2007 - accuracy: 0.9425
Learning rate for epoch 1 is 0.0010000000474974513
938/938 [==============================] - 21s 23ms/step - loss: 0.2007 - accuracy: 0.9425
Epoch 2/10
930/938 [============================>.] - ETA: 0s - loss: 0.0661 - accuracy: 0.9806
Learning rate for epoch 2 is 0.0010000000474974513
938/938 [==============================] - 14s 15ms/step - loss: 0.0658 - accuracy: 0.9807
Epoch 3/10
929/938 [============================>.] - ETA: 0s - loss: 0.0452 - accuracy: 0.9862
Learning rate for epoch 3 is 0.0010000000474974513
938/938 [==============================] - 14s 15ms/step - loss: 0.0455 - accuracy: 0.9862
Epoch 4/10
928/938 [============================>.] - ETA: 0s - loss: 0.0240 - accuracy: 0.9934
Learning rate for epoch 4 is 9.999999747378752e-05
938/938 [==============================] - 14s 14ms/step - loss: 0.0240 - accuracy: 0.9934
Epoch 5/10
9............................

**Comment by KUASWoodyLIN** [comment]
@muddham 
I also have test on google colab, and the google colab is only run on single GPU.
but I think this problem is only come out when with multi-gpu.

**Comment by bluesbeyond** [comment]
got the same problem just now.
  468/Unknown - 5s 12ms/step - loss: 0.0570 - accuracy: 0.9830---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-36-e5f10b39d923> in <module>
----> 1 model.fit(train_dataset, epochs=10000, callbacks=callbacks)

/usr/local/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py in fit(self, x, y, batch_size, epochs, verbose, callbacks, validation_split, validation_data, shuffle, class_weight, sample_weight, initial_epoch, steps_per_epoch, validation_steps, validation_freq, max_queue_size, workers, use_multiprocessing, **kwargs)
    744             steps_per_epoch=steps_per_epoch,
    745             validation_steps=validation_steps,
--> 746             validation_freq=validation_freq)
    747
    748     batch_size = self._validate_or_infer_batch_size(

/usr/local/lib/python3.7/site-packages/tensorflow/python/keras/engine/training_distributed.py in fit_distributed(model, x, y, batch_size, epochs, verbose, callbacks, validation_split, validation_data, shuffle, class_weight, sample_weight, initial_epoch, steps_per_epoch, validation_steps, validation_freq)
    129         validation_steps=validation_steps,
    130         validation_freq=validation_freq,
--> 131         steps_name='steps_per_epoch')
    132
    133

/usr/local/lib/python3.7/site-packages/tensorflow/python/keras/engine/training_arrays.py in model_iteration(model, inputs, targets, sample_weights, batch_size, epochs, verbose, callbacks, val_inputs, val_targets, val_sample_weights, shuffle, initial_epoch, steps_per_epoch, validation_steps, validation_freq, mode, validation_in_fit, prepared_feed_values_from_dataset, steps_name, **kwargs)
    260         try:
    261           # `ins` can be callable in DistributionStrategy + eager case.
--> 262           actual_inputs = ins() if callable(ins) else ins
    263           batch_outs = f(actual_inputs)
    264         except errors.OutOfRangeError:

/usr/local/lib/python3.7/site-packages/tensorflow/python/keras/engine/training_arrays.py in get_distributed_inputs()
    470     def get_distributed_inputs():
    471       return distributed_training_utils._prepare_feed_values(
--> 472           model, inputs, targets, sample_weights, mode)
    473
    474     # In the eager case, we want to call the input method per step, so return

/usr/local/lib/python3.7/site-packages/tensorflow/python/keras/engine/distributed_training_utils.py in _prepare_feed_values(model, inputs, targets, sample_weights, mode)
    565   """
    566   strategy = model._distribution_strategy
--> 567   inputs, targets, sample_weights = _get_input_from_iterator(inputs, model)
    568   inputs = flatten_perdevice_values(strategy, inputs)
    569   targets = flatten_perdevice_values(strategy, targets)

/usr/local/lib/python3.7/site-packages/tensorflow/python/keras/engine/distributed_training_utils.py in _get_input_from_iterator(iterator, model)
    547   # Validate that all the elements in x and y are of the same type and shape.
    548   validate_distributed_dataset_inputs(
--> 549       model._distribution_strategy, x, y, sample_weights)
    550   return x, y, sample_weights
    551

/usr/local/lib/python3.7/site-packages/tensorflow/python/keras/engine/distributed_training_utils.py in validate_distributed_dataset_inputs(distribution_strategy, x, y, sample_weights)
    247   # If each element of x and y are not tensors, we cannot standardize and
    248   # validate the input and targets.
--> 249   x_values_list = validate_per_device_inputs(distribution_strategy, x)
    250
    251   if y is not None:

/usr/local/lib/python3.7/site-packages/tensorflow/python/keras/engine/distributed_training_utils.py in validate_per_device_inputs(distribution_strategy, x)
    294
    295     # Validate that the shape and dtype of all the elements in x are the same.
--> 296     validate_all_tensor_shapes(x, x_values)
    297     validate_all_tensor_types(x, x_values)
    298

/usr/local/lib/python3.7/site-packages/tensorflow/python/keras/engine/distributed_training_utils.py in validate_all_tensor_shapes(x, x_values)
    315     if x_shape != x_values[i].get_shape().as_list():
    316       raise ValueError('Input tensor shapes do not match for distributed tensor'
--> 317                        ' inputs {}'.format(x))
    318
    319

ValueError: Input tensor shapes do not match for distributed tensor inputs PerReplica:{
  0 /job:localhost/replica:0/task:0/device:GPU:0: tf.Tensor(

**Comment by bluesbeyond** [comment]
This is fixed by method of KUASWoodyLIN. Thanks.

**Comment by muddham** [comment]
@KUASWoodyLIN Can you please let us know if you are happy to close if no issue persists

**Comment by KUASWoodyLIN** [comment]
@muddham  
```train_dataset = mnist_train.repeat(2).map(scale).shuffle(BUFFER_SIZE).batch(BATCH_SIZE)```
Add repeat(2) fixed the problem is because: 
120000(train_num * repeat) / 64(batch) = 1875 it can be divisible.
if change batch size to `62`:
120000(train_num * repeat) / 62(batch) = 1935.48, Even though you repeat it 2 time error will still come out.

I think the best solution is fix `tf.data`, that it automatic repeat at mulit-gpu.

**Comment by muddham** [comment]
@KUASWoodyLIN As this is resolved, this issue will be closed.
