### ISSUE TITLE
r1.14 with cuda 10.1 build failed

### ISSUE THREAD

**Issue by alanpurple** [tensorflow/tensorflow#28330]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): ubuntu 18.04.2
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): source
- TensorFlow version: 1.14.0rc0
- Python version: 3.7.3
- Installed using virtualenv? pip? conda?: N/A
- Bazel version (if compiling from source): 0.24.1
- GCC/Compiler version (if compiling from source):  7.4.0
- CUDA/cuDNN version: 10.1/7.5.2
- GPU model and memory: RTX2080Ti GDDR6 11GB

**Describe the problem**

build failed

**Provide the exact sequence of commands / steps that you executed before running into the problem**

bazel build

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

external/protobuf_archive/src/google/protobuf/map.h:490:29: error: cannot call member function ‘bool google::protobuf::Map<Key, T>::InnerMap::TableEntryIsNonEmptyList(google::protobuf::Map<Key, T>::size_type) const [with Key = std::__cxx11::basic_string<char>; T = std::__cxx11::basic_string<char>; google::protobuf::Map<Key, T>::size_type = long unsigned int]’ without object
         if (m_->TableEntryIsNonEmptyList(bucket_index_)) {
         ~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~
external/protobuf_archive/src/google/protobuf/map.h:504:24: error: cannot call member function ‘bool google::protobuf::Map<Key, T>::InnerMap::TableEntryIsList(google::protobuf::Map<Key, T>::size_type) const [with Key = std::__cxx11::basic_string<char>; T = std::__cxx11::basic_string<char>; google::protobuf::Map<Key, T>::size_type = long unsigned int]’ without object
         return m_->TableEntryIsList(bucket_index_);
         ~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~
ERROR: /home/wproject/repo/tensorflow/tensorflow/core/kernels/BUILD:4124:1: output 'tensorflow/core/kernels/_objs/histogram_op_gpu/histogram_op_gpu.cu.pic.o' was not created
ERROR: /home/wproject/repo/tensorflow/tensorflow/core/kernels/BUILD:4124:1: not all outputs were created or valid
Target //tensorflow/tools/pip_package:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.

**Comment by melrobin** [comment]
I am having the same issue.

**Comment by wdirons** [comment]
This is due to a bug in the nvcc compiler with CUDA 10.1. NVIDIA is working on a fix.

Same issue has been reported in https://github.com/tensorflow/tensorflow/issues/26155

You can try gcc 7.2

**Comment by alanpurple** [comment]
closing this issue since today's cuda update resolve errors
