### ISSUE TITLE
Is it possible to add a layer to an Estimator after training it?

### ISSUE THREAD

**Issue by jxieeducation** [tensorflow/tensorflow#28342]
Hi all,

After training an estimator, we'd like to modify the model and add a custom layer. 

Is there a way to modify the estimator model that way?

Thanks!

**Comment by gadagashwini** [comment]
@jxieeducation It looks, This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged//tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there. Let us know. Thanks!
