### ISSUE TITLE
TrtGraphConverterV2 does not preserve output names in the signature_def

### ISSUE THREAD

**Issue by olesalscheider** [tensorflow/tensorflow#28346]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below):  master from April 22nd
- Python version: 3.6.7
- Bazel version (if compiling from source): 0.24
- GCC/Compiler version (if compiling from source): 7.4
- CUDA/cuDNN version: 10.0 / 7.5.0
- GPU model and memory: GTX 1080 Ti

**Describe the current behavior**
If you use TrtGraphConverterV2 to convert a function in a saved_model to use TRT it does not preserve the output names in the signature_def of the saved model.

If the saved function (decorated with tf.function) returned a dict {'output_a': a, 'output_b': b} the names 'output_a' and 'output_b' are in the saved_model. After conversion with TrtGraphConverterV2 they are changed to the default names 'output_0' and 'output_1'.

**Describe the expected behavior**
The names of the outputs should not change. This breaks all code that loads the model and relies on the correct names.

**Code to reproduce the issue**
Take any saved_model that contains a function returning a dict.
Then run this:
```
conversion_params = trt_convert.DEFAULT_TRT_CONVERSION_PARAMS._replace(precision_mode=trt_convert.TrtPrecisionMode.FP16, max_batch_size=1, max_workspace_size_bytes=8000000000)

trt_converter = trt_convert.TrtGraphConverterV2(input_saved_model_dir='your_saved_model', input_saved_model_signature_key='your_key', conversion_params=conversion_params)
trt_converter.convert()
trt_converter.save('your_saved_model')
```
Use saved_model_cli to inspect the saved_model.

**Comment by muddham** [comment]
@olesalscheider In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thanks!

**Comment by olesalscheider** [comment]
You can use this code to reproduce the issue:

https://gist.githubusercontent.com/olesalscheider/366f33115016ac9d5f2976ec17124496/raw/f5b68bf571f325742c1bc24658f0de04b3d3b33c/wrong_outputs.py

The output names should be the same before and after conversion but they are not.

**Comment by muddham** [comment]
@olesalscheider Able to reproduce the issue.

Our saved model has the following structured outputs:
{'output_a': TensorSpec(shape=(), dtype=tf.float32, name='output_a'), 'output_b': TensorSpec(shape=(), dtype=tf.float32, name='output_b')}
Running TF-TRT conversion...
Our converted model has the following structured outputs:
{'output_0': TensorSpec(shape=(), dtype=tf.float32, name='output_0'), 'output_1': TensorSpec(shape=(), dtype=tf.float32, name='output_1')}

**Comment by aaroey** [comment]
Thanks for reporting this. I can reproduce the problem, will make a fix soon.

**Comment by bitterengsci** [comment]
Is it actually fixed??????

**Comment by aaroey** [comment]
@bixia1 do you know if this is still a problem?
