### ISSUE TITLE
Tensorflow lite example with alternate image source

### ISSUE THREAD

**Issue by pnduffy** [tensorflow/tensorflow#28347]
I would like an example similar to the TensorFlow lite Android example that doesn't use the camera but an alternate image source, like from network stream. Is there something available that has such an example?

**Comment by achandraa** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged//tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there and provide support. Thanks!
