### ISSUE TITLE
Enable eager execution fails after testing if executing eagerly

### ISSUE THREAD

**Issue by TerjeNorderhaug** [tensorflow/tensorflow#28351]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Colab
- TensorFlow installed from (source or binary): pip install -q "tensorflow==1.13.1"
- TensorFlow version (use command below): 1.13.1
- Python version: 2.7.15rc1

**Describe the current behavior**

Calling `tf.enable_eager_execution()` after `tf.executing_eagerly()` fails with:

    ValueError: tf.enable_eager_execution must be called at program startup. 

Note that this happens *at* program startup (after runtime restart on Colab). Calling `tf.enable_eager_execution()` by itself does *not* result in the exception. Not to confuse with issue #21893

**Describe the expected behavior**

It should be possible to check whether tensorflow is executing eagerly before programs enable eager execution. This is relevant for forward compatibility with *tensorflow 2.0.0-alpha0* which does not implement enable_eager_execution() but instead reports:

    AttributeError: 'module' object has no attribute 'enable_eager_execution'

**Code to reproduce the issue**

    import tensorflow as tf
    if not tf.executing_eagerly():
        tf.enable_eager_execution()

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

ValueErrorTraceback (most recent call last)
<ipython-input-1-a1e6f3444523> in <module>()
      7 
      8 if not tf.executing_eagerly():
----> 9   tf.enable_eager_execution()

1 frames
/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.pyc in enable_eager_execution(config, device_policy, execution_mode)
   5459         device_policy=device_policy,
   5460         execution_mode=execution_mode,
-> 5461         server_def=None)
   5462 
   5463 

/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.pyc in enable_eager_execution_internal(config, device_policy, execution_mode, server_def)
   5538   else:
   5539     raise ValueError(
-> 5540         "tf.enable_eager_execution must be called at program startup.")
   5541 
   5542   # Monkey patch to get rid of an unnecessary conditional since the context is

ValueError: tf.enable_eager_execution must be called at program startup.

**Comment by jaingaurav** [comment]
From what I tested, I believe this behavior has been fixed already in the latest tf-nightly and should be coming in 1.14. If not please let us know and re-open.

**Comment by jaingaurav** [comment]
@TerjeNorderhaug: Though the exception has been fixed in the nightlies, were you looking for the `tf.executing_eagerly` symbol to be included in 2.0?

**Comment by TerjeNorderhaug** [comment]
The `tf.executing_eagerly` symbol is already [in the 2.0 api](https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/executing_eagerly) and works as I expected with the _2.0.0-alpha0_ as well as the _tf-nightly-gpu-2.0-preview_.
