### ISSUE TITLE
AttributeError: 'tuple' object has no attribute 'ndims'

### ISSUE THREAD

**Issue by hiteshnitetc** [tensorflow/tensorflow#28362]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version (use command below):
- Python version:
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**

**Describe the expected behavior**

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

I am trying to run Virtual Batch Nomalization from [Here]( tensorflow/tensorflow/contrib/gan/python/features/python/virtual_batchnorm_impl.py ) with reference batch of size (10,50,50,1) of float32 type, which means that total 10 images of 50*50 type with channel=1. I write for this `S1=VBN(S)`. And getting error `AttributeError: 'tuple' object has no attribute 'ndims'`

**Comment by achandraa** [comment]
Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version. Also, did you compile from source or install a binary?

Make sure you also include minimal code snippet that can depict the issue. You can follow the [template](https://github.com/tensorflow/tensorflow/issues/new/choose) for the same.

We ask for this in the issue submission template, because it is really difficult to help without that information. Thanks!

**Comment by hiteshnitetc** [comment]
@achandraa Hello. My os is Ubuntu(16.04, 64bit). Python version- 3.6.7, Tensorflow version- 1.13.1, keras-2.2.4, I install tensorflow from instruction `pip install tensorflow`. I use exactly same code as mention in my question for virtual batch normalization.

**Comment by achandraa** [comment]
Tried checking your code snippet from the link provided but could not find it. Can you please help me to get the minimal code snippet that can depict the scenario. Thanks!

**Comment by hiteshnitetc** [comment]
https://github.com/tensorflow/tensorflow/blob/r1.13/tensorflow/contrib/gan/python/features/python/virtual_batchnorm_impl.py

**Comment by hiteshnitetc** [comment]
@achandraa waiting for your valuable reply

**Comment by ymodak** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow-tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.
