### ISSUE TITLE
Retrain image detection with MobileNet for use in TFjs, failure in tensorflowjs_converter

### ISSUE THREAD

**Issue by serv-inc** [tensorflow/tensorflow#28365]
It is unclear whether this is a documentation or a programming issue. If misfiled, please say so and suggest whether a new issue should be raised, or what else can be done.

**System information**
- TensorFlow version:
 ('v1.13.1-0-g6612da8951', '1.13.1') (see #27538)
('v1.12.0-9492-g2c319fb415', '2.0.0-alpha0') (see #27539) and
tf-nightly-2.0-preview (see https://stackoverflow.com/questions/55682557/)

- Doc Link:
https://www.tensorflow.org/hub/tutorials/image_retraining and
https://www.tensorflow.org/tutorials/images/hub_with_keras

**Describe the documentation issue**
Both documents mention but do not describe conversion to mobile models. Yet, conversion using `tensorflowjs_converter` failed in every attempt. See https://stackoverflow.com/questions/55849309/retrain-image-detection-with-mobilenet, which mentions two attempts by me as well as questions by others with the same problem.

**We welcome contributions by users. Will you be able to update submit a PR (use the [doc style guide](https://www.tensorflow.org/community/documentation)) to fix the doc Issue?**

As soon as it is working, I would gladly fix and/or augment the docs.  I have not gotten **`tensorflowjs_converter`** to **work on a retrained MobileNet model**, despite the docs stating that it should work, [e.g.](https://www.tensorflow.org/tutorials/images/hub_with_keras#export_your_model):

> This saved model can loaded for inference later, or converted to TFLite or TFjs.

**Comment by ymodak** [comment]
This issue is more suitable on tensorflow js repo. Please post it on [tensorflow js](https://github.com/tensorflow/tfjs). Thanks!

**Comment by serv-inc** [comment]
@ymodak: It's now at https://github.com/tensorflow/tfjs/issues/1576. Thanks!
