### ISSUE TITLE
tf.image.resize_image_with_pad(image, 108, 56) gives 109 by 56 output for some images

### ISSUE THREAD

**Issue by dmus** [tensorflow/tensorflow#28363]
[7953_4_3337_294_54_110.txt](https://github.com/tensorflow/tensorflow/files/3141289/7953_4_3337_294_54_110.txt)
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): tf 1.12, tf 1.13, tf-nightly
- Python version: 3.6.7
- CUDA/cuDNN version: not applicable
- GPU model and memory: not applicable

**Describe the current behavior**
For some images, not for all tf.image.resize_image_with_pad(image, 108, 56) gives an output size of 109 by 56

**Describe the expected behavior**
 tf.image.resize_image_with_pad(image, 108, 56) should always give an output of 108 by 56

**Code to reproduce the issue**
    `import tensorflow as tf 
    import pdb
    import cv2
    import base64

    #tf.enable_eager_execution()

    with tf.Session() as sess:
        img_path = '7953_4_3337_294_54_110.txt'
    
        with open(img_path, 'r') as the_file:
            image_string_base64 = the_file.read()

        image_string = tf.decode_base64(image_string_base64)

        image = tf.image.decode_png(image_string)
        image = tf.image.resize_image_with_pad(image, 108, 56)

        print(image)

        img_array = sess.run(image)
        print(img_array.shape)
    
        cv2.imwrite('test.png', cv2.cvtColor(img_array, cv2.COLOR_BGR2RGB))`

**Other info / logs**
With eager execution it works correctly

**Comment by dmus** [comment]
It seems that tf.image.resize_image_with_pad gives slightly different results under eager execution than under graph mode

**Comment by jvishnuvardhan** [comment]
@dmus Can you provide a code to reproduce the issue? Please use any public data if your data is private. Thanks!

**Comment by dmus** [comment]
@jvishnuvardhan See here for a gist: https://colab.research.google.com/gist/dmus/edbed5154d07be197ced49e52ad3ea79/untitled0.ipynb

**Comment by jvishnuvardhan** [comment]
@dmus This works for most of the other dimensions. I have changed `height` to 106,107, 109 etc and it worked as expected. When target height is 108, then this op produces an error as there are multiple calculations (for scaling image) when the code uses math_ops.floor function. Please take a look at the [source code](https://github.com/tensorflow/tensorflow/blob/a5c387b5ed78c9126424618d5c70f51cd3799857/tensorflow/python/ops/image_ops_impl.py#L1129) If you are interested. For temporary workaround is to use `image = tf.image.resize_image_with_crop_or_pad(image, 108, 56)`.

I think this is a bug. Thanks for finding this.

**Comment by hyeygit** [comment]
(Going through longstanding unresolved issues) 

This should've been fixed starting tf2.0+. I've verified it and you can see the code snippet [here](https://colab.research.google.com/drive/1dkxgCqbwzd3RZgrYqRKWrLGD3zYHRGuh?usp=sharing).
