### ISSUE TITLE
An error ocurred while starting the kernel(tensorflow-gpu)

### ISSUE THREAD

**Issue by Oldhuntor** [tensorflow/tensorflow#28364]
While using the keras to proceed the code suddenly，the warining came out which are as follow：

An error ocurred while starting the kernel
2019󈚩󈚧 16:08:03.433226: I c:\users\user\source\repos\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:1405] Found device 0 with properties: 
name: GeForce RTX 2060 major: 7 minor: 5 memoryClockRate(GHz): 1.2
pciBusID: 0000:01:00.0
totalMemory: 6.00GiB freeMemory: 4.89GiB
2019󈚩󈚧 16:08:03.435266: I c:\users\user\source\repos\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:1484] Adding visible gpu devices: 0
2019󈚩󈚧 16:08:05.728803: I c:\users\user\source\repos\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:965] Device interconnect StreamExecutor with strength 1 edge matrix:
2019󈚩󈚧 16:08:05.730056: I c:\users\user\source\repos\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:971] 0 
2019󈚩󈚧 16:08:05.730321: I c:\users\user\source\repos\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:984] 0: N 
2019󈚩󈚧 16:08:05.730723: I c:\users\user\source\repos\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:1097] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 4644 MB memory) ‑> physical GPU (device: 0, name: GeForce RTX 2060, pci bus id: 0000:01:00.0, compute capability: 7.5

**my system information**
- win10
- cuda9.2
- cdunn7.2
- python3.65
- TensorFlow version :1.10.0
- GPU/CPU:RTX2060,i7 9750h
- memory:16g

but when i used tensorflow directly,without processing code by keras,there was no warning and competely successful.
Despite all this,I still prefer keras rather than directly using tensorflow，somebody help me please XD.

**Comment by wdirons** [comment]
The messages posted above all look like informational messages and not warnings.

**Comment by Oldhuntor** [comment]
> The messages posted above all look like informational messages and not warnings.

Thank you for your reply，Although it can not be considered as error or warning,it stuck in epoch1 and came out this message.

**Comment by muddham** [comment]
@Oldhuntor This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.If you think we've misinterpreted a bug, please comment again with a clear explanation, as well as all of the information requested in the [issue template](https://github.com/tensorflow/tensorflow/issues/new/choose). Thanks!

**Comment by Oldhuntor** [comment]
> @Oldhuntor This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.If you think we've misinterpreted a bug, please comment again with a clear explanation, as well as all of the information requested in the [issue template](https://github.com/tensorflow/tensorflow/issues/new/choose). Thanks!

Thank you for your reply,i'm going to ask question in that platform.
