### ISSUE TITLE
tensorflow2.0 InvalidArgumentError for multiple GPU

### ISSUE THREAD

**Issue by brealisty** [tensorflow/tensorflow#28372]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:  NO
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Windows server 2016
- **TensorFlow installed from (source or binary)**: pip install
- **TensorFlow version (use command below)**: 2.0-alpha0
- **Python version**: 3.6
- **CUDA/cuDNN version**: cuda10.0; cudnn7.5 for cuda10.0
- **GPU model and memory**: 4*1080Ti  each 11GB

### Describe the problem
I try to test the multiple GPU tutorials of tf2.0, both [keras](https://github.com/tensorflow/docs/blob/master/site/en/r2/tutorials/distribute/keras.ipynb) and [training loop](https://github.com/tensorflow/docs/blob/master/site/en/r2/tutorials/distribute/training_loops.ipynb) get the same error:
> tensorflow.python.framework.errors_impl.InvalidArgumentError: No OpKernel was registered to support Op 'NcclAllReduce' used by {{node training/Adam/NcclAllReduce}}with these attrs: [reduction="sum", T=DT_FLOAT, num_devices=4, shared_name="c0"]
> Registered devices: [CPU, GPU]
Registered kernels:
  <no registered kernels>

	 [[training/Adam/NcclAllReduce]] [Op:__inference_keras_scratch_graph_4244]

all the code copy from the two link, and do not change one letter. It is a bug or I do something wrong?

**Comment by ziyigogogo** [comment]
Hi there, have you solved this ?

**Comment by brealisty** [comment]
> Hi there, have you solved this ?

no, not even TF1.13, I guess the problem from the OS plateform.

**Comment by spatters** [comment]
According to the guide, https://www.tensorflow.org/guide/distribute_strategy, MirroredStrategy defaults to using NCCL for cross device communication and NCCL is not available on Windows.

"If you wish to override the cross device communication, you can do so using the cross_device_ops argument by supplying an instance of tf.distribute.CrossDeviceOps. Currently we provide tf.distribute.HierarchicalCopyAllReduce and tf.distribute.ReductionToOneDevice as 2 other options other than tf.distribute.NcclAllReduce which is the default."

**Comment by brealisty** [comment]
> According to the guide, https://www.tensorflow.org/guide/distribute_strategy, MirroredStrategy defaults to using NCCL for cross device communication and NCCL is not available on Windows.
> 
> "If you wish to override the cross device communication, you can do so using the cross_device_ops argument by supplying an instance of tf.distribute.CrossDeviceOps. Currently we provide tf.distribute.HierarchicalCopyAllReduce and tf.distribute.ReductionToOneDevice as 2 other options other than tf.distribute.NcclAllReduce which is the default."

oh, thank u. I will try it

**Comment by ziyigogogo** [comment]
hi there, after a day-long searching, I finally come out the idea. NCCL is a native library for GPUs communication which is only official supported for Linux. Thus here are two solutions:
1. find windows non-official version of [NCCL](https://github.com/NVIDIA/nccl) (nod recommend)
2. As spatter's suggestion, custom reduction OP:[example](https://github.com/tensorflow/tensorflow/issues/21470)
