### ISSUE TITLE
tf.data.Dataset allow change of structure

### ISSUE THREAD

**Issue by sleighsoft** [tensorflow/tensorflow#28374]
**System information**
- TensorFlow version (you are using): v2
- Are you willing to contribute it (Yes/No): only python code

**Describe the feature and the current behavior/state.**
My current use case is as follows:
I get a dataset from `tensorflow_datasets.load()` where the structure is `(image, label)`, e.g. `MNIST`. I would like to only use the `image` information of that dataset. Therefore I tried to find a way to "unpack" that dataset from a dict into a single element (so no key required to work on it).

```python
# Currently

dataset = tfds.load('MNIST', split='train')
for d in dataset:
  # Now d has the "shape" {'image': tensor, 'label': tensor}

# What I would like to do
dataset = tfds.load('MNIST', split='train')
dataset = tf.data.Dataset.unpack(dataset, 'image')
for d in dataset:
  # Now d is a tensor
```

When the dataset is `unpacked` I can also do further transformations on it, e.g. `filter`, `batch`, ...

**Will this change the current api? How?** No

**Who will benefit with this feature?** Users of `tensorflow_dataset` I assume.

**Any Other info.**

**Comment by sleighsoft** [comment]
It could also be seen as a kind of subset, where when the subset size is 1 it unpacks the dict to a tensor.
This would allow selecting multiple keys as a subset from a `tf.data.Dataset`.

**Comment by jsimsa** [comment]
Hi @sleighsoft you can use the `map` transformation to do what you want:

```
dataset = tfds.load('MNIST', split='train')
dataset = dataset.map(lambda x: x['image'])
# now dataset only contains sequence of images
```
