### ISSUE TITLE
TensorFlow Lite converter type mismatch during keras model conversion

### ISSUE THREAD

**Issue by Knize** [tensorflow/tensorflow#28373]
**System information**
- OS Platform and Distributio: Elementary OS 5
- TensorFlow version (use command below): 1.13.1
- Python version: 3.7.3
- CUDA/cuDNN version:
cudatoolkit               10.0.130
cudnn                     7.3.1
- GPU model and memory: GTX 1060 6 Gb

**Error**
TypeError: Input 'y' of 'Equal' Op has type float32 that does not match type int32 of argument 'x'.
in tensorflow/python/framework/op_def_library.py, line 547, in _apply_op_helper

**Code to reproduce the issue**
`tflite_convert
  --output_file=./tflite_model.tflite
  --keras_model_file=./images/train-set/train-set_model.h5`
How net was trained and saved shown in file attached.
Full console output attached also.
[net and console.zip](https://github.com/tensorflow/tensorflow/files/3142890/net.and.console.zip)

The same if called by python API.

Trained model:
[train-set_model.h5.zip](https://github.com/tensorflow/tensorflow/files/3154779/train-set_model.h5.zip)

**Comment by muddham** [comment]
@Knize Can you please use the tf nightly build and check if the issue still persists or not.

**Comment by Knize** [comment]
@muddham With tf-nightly result is
E tensorflow/core/grappler/grappler_item_builder.cc:637] Init node conv2d_1/kernel/Assign doesn't exist in graph
Full console output attached.
[console.txt](https://github.com/tensorflow/tensorflow/files/3150277/console.txt)

**Comment by amitsrivastava78** [comment]
@Knize , can you please attach the train-set_model.h5 file as well, will try to reproduce the error on my work station and give you a solution.

Regards
Amit

**Comment by muddham** [comment]
@Knize Please refer the stackoverflow [link](https://stackoverflow.com/questions/54122044/tensorflow-lite-init-node-doesnt-exist). Stackoverflow user says he could resolve this issue by downgrading to tensorflow 1.12.Please let us know how it progresses . Thanks!

**Comment by Knize** [comment]
@amitsrivastava78 Uploaded. Thanks in advance. I trained another net in order to make file small enough to attach. So it's more or less dummy net only to reproduce problem.

**Comment by Knize** [comment]
@muddham OK, i'll try and post results here in a day or two.

**Comment by Knize** [comment]
@muddham Looks like downgrading to 1.12 helped. Thank you.

**Comment by muddham** [comment]
@Knize As this is resolved. We will close this issue. Thanks!
