### ISSUE TITLE
Get placeholder for initial state of nested RNN

### ISSUE THREAD

**Issue by danijar** [tensorflow/tensorflow#2838]
For RNN cells, we get the initial state using `cell.zero_state()` and the last state after processing a sequence using `rnn.dynamic_rnn()`. However, to use the last state as the initial state for the next run, one must create a `tf.placeholder()`. As far as I know, currently there is no way to create and fill such  a placeholder (or nested tuple of placeholders) automatically. Such a feature would be very useful so that we don't have to adjust the placeholder manually when changing the RNN cell.

**Comment by ebrevdo** [comment]
Is this request specifically for truncated BPTT?  or something more general?

**Comment by danijar** [comment]
It's for both truncated BPTT and architectures using LSTM decoders. In the second case, the cells are initialized with some encoded activation. For an example see: Skip-Thought Vectors (Kiros et al. 2015).

**Comment by tomrunia** [comment]
I am also interested in having a good way to remember the LSTM states for the next batch. This question was also asked by me on StackOverflow: http://stackoverflow.com/questions/38241410/tensorflow-remember-lstm-state-for-next-batch-stateful-lstm

**Comment by ebrevdo** [comment]
We are working on a system that makes this easy. Something should already
in the github repo within a coupe of weeks.

**Comment by tomrunia** [comment]
This might be of interest to @danijar : https://github.com/tensorflow/tensorflow/issues/2695
Great that you are working on things to make this easier, I will wait for an update :-)

**Comment by yangzw** [comment]
In the example ptb_word_lm.py,  
`  state = m.initial_state.eval()
  for step, (x, y) in enumerate(reader.ptb_iterator(data, m.batch_size,
                                                    m.num_steps)):
    cost, state, _ = session.run([m.cost, m.final_state, eval_op],
                                 {m.input_data: x,
                                  m.targets: y,
                                  m.initial_state: state})` 
However, there is no placeholder for `m.ititial_state`. Why this could work?

**Comment by danijar** [comment]
@yangzw You can feed in values for any tensor. Placeholders are just special in that they throw an error if you don't feed them while a variable would silently use its last value.

**Comment by ebrevdo** [comment]
We now have a comprehensive solution for truncated BPTT; introduced in 955efc90026ee08205ad84551dd4a308439fd741.  See `tf.contrib.training.batch_sequences_with_states`.  Unfortunately for now the only examples are in the unit tests.

Automatically creating nested placeholders would be useful.  I'll look into adding this.

**Comment by wpm** [comment]
Is there example code for the `my_parser` function in the example in the [documentation](https://github.com/tensorflow/tensorflow/blob/4d579354034497d7fb58d01263dea72fc0014edd/tensorflow/g3doc/api_docs/python/functions_and_classes/shard4/tf.contrib.training.batch_sequences_with_states.md) for `batch_sequences_with_states`?

I'm trying to figure it out from the documentation but am still having questions.

**Comment by nitishgupta** [comment]
@ebrevdo : In my opinion there should be something more general. For cases in which one trains a RNN with the whole sequence being fed at once but during inference requires fetching and feeding the states on a per time-step basis, the solution right now is not very neat. Is there some hope of fetching and feeding list of state tuples for MultiRNNCell in some way.

**Comment by danijar** [comment]
I'm current solving this by holding the state in a non-trainable variable that I initialize from the default state. The variable name is prefixed by `state/` and I have helper functions to return a dictionary from name to tensor containing all variables matching this prefix. Similarly, I have a helper function to assign variable values from this dictionary. This is a general way to handle context, but it's not straight forward using the existing TensorFlow features. Moreover, it doesn't work with the new decision to represent LSTM states as tuples.

**Comment by ebrevdo** [comment]
@danijar: I recommend against using a non-trainable variable because this is not thread-safe (you can't run multiple inference threads against the same graph).  However, it's not too hard to create some placeholder tensors and wrap them in the necessary tuple type.  Similarly when calling a session run, one can pull out the "next state" tuple and store it, feeding it as an input to the next session.run.  This is decidedly more thread-safe than the variable solution (and in fact is zero-copy if you're doing this in a C++ client; though sadly not zero-copy in python since TF runtime must copy feed_dict inputs from python since python does its own memory management)

@nitishgupta you can now fetch an arbitrary tuple type in python.  don't think you can feed one though (but that may have changed recently?)  since usually per-step RNN inference is meant done in a C++ client, i don't have any plans to add python sugar for this.

@wpm  an example of "my_parser" is something that reads a serialized `SequenceExample` via a reader and deserializes it using `parse_single_sequence_example`.  The `parse_single_sequence_example` call returns `context` and `sequences` dictionaries that exactly match some of the inputs of `batch_sequences_with_states`.

**Comment by ebrevdo** [comment]
@danijar since session.run only supports feed_dict of the format {key: value} where key is either a Tensor or a string (the tensor's name), i'm unable to create this kind of placeholder.  However you can always use:

```
c_state = tf.placeholder(...)
h_state = tf.placeholder(...)
initial_state = tf.nn.rnn_cell.LSTMStateTuple(c_state, h_state)

sess.run(..., feed_dict={c_state: ..., h_state: ...})
```

**Comment by danijar** [comment]
@ebrevdo Thanks for the example. It would be nice to be able to interchange the cell without changing the placeholder/feed logic. That way, people can write operations that take a cell as parameter, and supports any inplementation, including use defined ones. Do you know how if that's possible?

**Comment by carlthome** [comment]
> It would be nice to be able to interchange the cell without changing the placeholder/feed logic.

:+1:

**Comment by carlthome** [comment]
I figure some utility function for getting all RNN state tensors as variables or placeholders would be nice. E.g. something like:

```python
def rnn_placeholders(state):
    """Convert RNN state tensors to placeholders with the zero state as default."""
    structure = []
    fetches = []
    if isinstance(state, tf.Tensor):
        placeholder = tf.placeholder_with_default(
            input=state,
            shape=state.shape,
            name='state')
        return placeholder, placeholder
    else: 
        for x in state:
            child_structure, child_fetches = rnn_placeholders(x)
            structure.append(child_structure)
            if isinstance(child_fetches, tf.Tensor):
                fetches.append(child_fetches)
            else:
                fetches.extend(child_fetches)
    return tuple(structure), fetches


cell = ...  # LSTMStateTuple, MultiRNNCell, etc.

# Create placeholders for all RNN state tensors.
state, rnn_fetches = rnn_placeholders(cell.zero_state(batch_size, tf.float32))

tf.nn.dynamic_rnn(..., initial_state=state)

next_initial_rnn_state = None
if next_initial_rnn_state is not None:
    feed_dict = dict(zip(rnn_fetches, next_initial_rnn_state))
else:
    feed_dict = {}
results = sess.run([train_op] + rnn_fetches, feed_dict=feed_dict)
next_initial_rnn_state = results[1:]
```

**Comment by kovek** [comment]
Why is it be interesting to use the output of a run as the input of the next run? By the different runs do you mean two different batches? Do you mean two series within a batch? What if the zero_state was just random noise?

**Comment by danijar** [comment]
@kovek When input sequences are too long to fit into memory, we need to chunk them. Even though we usually don't backpropagate across chunk boundaries, we want to at least carry over the hidden state of the RNN.

**Comment by carlthome** [comment]
I now do something like this:

```python
def rnn_placeholders(state):
    """Convert RNN state tensors to placeholders with the zero state as default."""
    if isinstance(state, tf.contrib.rnn.LSTMStateTuple):
        c, h = state
        c = tf.placeholder_with_default(c, c.shape, c.op.name)
        h = tf.placeholder_with_default(h, h.shape, h.op.name)
        return tf.contrib.rnn.LSTMStateTuple(c, h)
    elif isinstance(state, tf.Tensor):
        h = state
        h = tf.placeholder_with_default(h, h.shape, h.op.name)
        return h
    else:
        structure = [rnn_placeholders(x) for x in state]
        return tuple(structure)

state = rnn_placeholders(cell.zero_state(batch_size, tf.float32))
```
which works with arbitrarily nested RNN structures and works well enough until the state managing stuff @ebrevdo seems to be working on in the seq2seq stuff (it's hinted at in around the RNN documentation, anyway) becomes available.

**Comment by RylanSchaeffer** [comment]
Has any progress been made here?

**Comment by RylanSchaeffer** [comment]
@ebrevdo , does `tf.contrib.training.batch_sequences_with_states` work with sequence to sequence models, and if so, how?

My guess is that I need to create two `batch_sequences_with_state`, one for the input sequence and the other for the output sequence, and then feed one into my encoder and the other into my decoder. Is that correct?

**Comment by RylanSchaeffer** [comment]
@danijar , maybe you know the answer?

**Comment by danijar** [comment]
@RylanSchaeffer I don't know but this doesn't seem related to creating an placeholder for the RNN state. Please ask the question on StackOverflow instead.

**Comment by carlthome** [comment]
Here's a cleaner alternative relying more on @ebrevdo `nest`:

```python
from tensorflow.contrib.framework import nest

state = nest.map_structure(
    lambda x: tf.placeholder_with_default(x, x.shape, x.op.name),
    cell.zero_state(batch_size, tf.float32))

for tensor in nest.flatten(state):
    tf.add_to_collection('rnn_state_input', tensor)

x, new_state = tf.nn.dynamic_rnn(...)

for tensor in nest.flatten(new_state):
    tf.add_to_collection('rnn_state_output', tensor)
```

**Comment by archiki** [comment]
@carlthome How do you use this implementation while running the session, we still dont specify an inital state to the dynamic RNN right? Could you please ellaborate?

**Comment by leimao** [comment]
The way used in PTB language modeling solves the problem. But it does not look elegant. I wonder if there is any follow-up regarding feeding the previous output of RNN to the current input. I used PyTorch for similar tasks and it seems that their ways of solving it is more elegant.

**Comment by Sody666** [comment]
> @yangzw You can feed in values for any tensor. Placeholders are just special in that they throw an error if you don't feed them while a variable would silently use its last value.

Yes. testing code:
`
x = tf.Variable(2)
y = tf.constant(3)

mul = tf.math.multiply(x, y)

with tf.Session() as s:
    tf.global_variables_initializer().run()
    print(s.run(mul, feed_dict={x: 6}))
    print(s.run(x))
`

Result: 
18
2
