### ISSUE TITLE
TPU Performance Regression 1.12 -> 1.13

### ISSUE THREAD

**Issue by jschneier** [tensorflow/tensorflow#28381]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 16.04 & 18.04
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 1.12.0 & 1.13.1
- Python version: 3.6.8
- CUDA/cuDNN version: N/A TPU
- GPU model and memory: N/A TPU

**Describe the current behavior**

Upgrading from Tensorflow 1.12.0 to 1.13.1 shows a large performance regression. Training goes from 2100 examples/s & 8.2 global steps/s to 860 examples/s & 3.4 global steps/s.

**Describe the expected behavior**

I would expect no performance penalty or improved performance for upgrading a library.

**Other info / logs**
Here are the outputs of `capture_tpu_profile` for the base case & regression case respectively.
![Base Profile](https://user-images.githubusercontent.com/2245080/57163873-35bc2700-6da7-11e9-856a-677a6b021731.png)
![ Regression Profile](https://user-images.githubusercontent.com/2245080/57163877-3785ea80-6da7-11e9-87de-e05dd121be30.png)

For reference this profile was captured during training on MobileNet but we have also observed this on other convolutional architectures. We also use quantization.

**Comment by jschneier** [comment]
For reference this profile was captured during training on MobileNet but we have also observed this on other convolutional architectures. We also use quantization.

**Comment by Saduf2019** [comment]
@jschneier 
please let us know if the issue still persist.

**Comment by Saduf2019** [comment]
@jschneier
please update on the above comment

**Comment by jschneier** [comment]
I no longer work on this at all so I won't be able to provide updates.

**Comment by Saduf2019** [comment]
@jschneier
 in that case could you please let us know if we could move this issue to closed status.
