### ISSUE TITLE
Tensorflow does not build with "--config=monolithic": "multiple definition"

### ISSUE THREAD

**Issue by Binero** [tensorflow/tensorflow#28397]
**System information**
- OS Platform and Distribution: Ubuntu 19.04 64bit on Digital Ocean
- TensorFlow installed from (source or binary): source
- TensorFlow version: r1.13 branch
- Python version: 3.7.3 (/usr/bin/python3)
- Bazel version (if compiling from source): 0.21.0
- GCC/Compiler version (if compiling from source): 8.3.0
- CUDA/cuDNN version: disabled

Compiling tensorflow from source gives linking errors on the end, all of which are related to "multiple definition".

```bash
bazel build --define=grpc_no_ares=true --config=opt --config=monolithic --config=ngraph --config=mkl --config=noaws //tensorflow/tools/pip_package:build_pip_package --local_resources 6000,.5,1.0 &> log.txt
```

[log.txt](https://github.com/tensorflow/tensorflow/files/3144670/log.txt)

**Comment by Binero** [comment]
The problem is solved by removing the "--config=monolithic" option.

**Comment by muddham** [comment]
@Binero As this is resolved, closing this issue. Thanks!

**Comment by Binero** [comment]
@muddham Is it not supposed to build regardless?
