### ISSUE TITLE
[tflite doc] CONV_2D_TRANSPOSE -> TRANSPOSE_CONV

### ISSUE THREAD

**Issue by syoyo** [tensorflow/tensorflow#28406]
## Existing URLs containing the issue:

https://www.tensorflow.org/lite/guide/ops_compatibility

## Description of issue (what needs changing):

TensorFlow `r1.13`.

`CONV_2D_TRANSPOSE` op is not present in TensorFlow Lite schema.
After glimpsed `toco` source code,  `tf.nn.conv2d_transpose`(`Conv2DBackpropInput`) is converted to `TRANSPOSE_CONV`.

https://github.com/tensorflow/tensorflow/blob/r1.13/tensorflow/lite/toco/import_tensorflow.cc#L1778 

So updating tflite documentation(replace `CONV_2D_TRANSPOSE` with `TRANSPOSE_CONV`  ) would be nice.

**Comment by muddham** [comment]
@syoyo Can you please elaborate the above information, cause CONV_2D_TRANSPOSE method is visible . Please see attached.
![image](https://user-images.githubusercontent.com/48215502/57302011-dee08580-70f7-11e9-8df4-66881b712aa7.png)

**Comment by syoyo** [comment]
@muddaham Yes that's what I found. Documentation should be updated by syncing with the implementation(or tflite schema).

**Comment by aselle** [comment]
I'm preparing a fix for this.
