### ISSUE TITLE
Mac os tensorflow website gets wrong

### ISSUE THREAD

**Issue by WuChannn** [tensorflow/tensorflow#28409]
when i open the website with my macbook air, the website gets wrong results like following:
![Screen Shot 2019-05-05 at 3 54 53 PM](https://user-images.githubusercontent.com/25492462/57190612-ab162c00-6f4e-11e9-82f4-835830952fb8.png)
![Screen Shot 2019-05-05 at 3 54 53 PM](https://user-images.githubusercontent.com/25492462/57190645-12cc7700-6f4f-11e9-9df3-b05ccb829555.png)

**Comment by muddham** [comment]
@WuChannn Can you please check with different browsers like Google Chrome, firefox etc. Also there could be network fluctuations due to which the page would not have loaded properly.

**Comment by WuChannn** [comment]
Thanks. I use google chrome already, but the problem appeared. Maybe the website isn’t suitable for 13 inches screen?------------------ Original ------------------From: muddham  <notifications@github.com>Date: Mon,May 6,2019 7:15 PMTo: tensorflow/tensorflow <tensorflow@noreply.github.com>Cc: WuChannn <wuzchng@gmail.com>, Mention <mention@noreply.github.com>Subject: Re: [tensorflow/tensorflow] Mac os tensorflow website gets wrong(#28409)@WuChannn Can you please check with different browsers like Google Chrome, firefox etc. Also there could be network fluctuations due to which the page would not have loaded properly.

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/tensorflow/tensorflow/issues/28409#issuecomment-489583759",
"url": "https://github.com/tensorflow/tensorflow/issues/28409#issuecomment-489583759",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by muddham** [comment]
@WuChannn This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.If you think we've misinterpreted a bug, please comment again with a clear explanation, as well as all of the information requested in the [issue template](https://github.com/tensorflow/tensorflow/issues/new/choose). Thanks!
