### ISSUE TITLE
Reloaded replicated model did not work  for distributed training

### ISSUE THREAD

**Issue by bluesbeyond** [tensorflow/tensorflow#28417]
I am running distributed tutorial as following. I can use the unsaved 'model' in replicated mode to evaluate but the reloaded replicated_model didn't work.
I am using CentOS7.5+Python3.7.1. I am not sure what's wrong with this.
In [45]: with strategy.scope():
    ...:     replicated_model=tf.keras.experimental.load_from_saved_model(path)
    ...:     replicated_model.compile(loss='sparse_categorical_crossentropy',
    ...:             optimizer=tf.keras.optimizers.Adam(),
    ...:             metrics=['accuracy'])
    ...:     eval_loss,eval_acc=replicated_model.evaluate(eval_dataset)
    ...:
2019-05-06 00:59:35.889966: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1546] Adding visible gpu devices: 0, 1
2019-05-06 00:59:35.890048: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1015] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-05-06 00:59:35.890110: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1021]      0 1
2019-05-06 00:59:35.890119: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1034] 0:   N Y
2019-05-06 00:59:35.890126: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1034] 1:   Y N
2019-05-06 00:59:35.890631: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1149] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 21625 MB memory) -> physical GPU (device: 0, name: Tesla P40, pci bus id: 0000:3b:00.0, compute capability: 6.1)
2019-05-06 00:59:35.890865: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1149] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:1 with 21625 MB memory) -> physical GPU (device: 1, name: Tesla P40, pci bus id: 0000:d8:00.0, compute capability: 6.1)
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-45-9147a4df43ec> in <module>
      3     replicated_model.compile(loss='sparse_categorical_crossentropy',
      4             optimizer=tf.keras.optimizers.Adam(),
----> 5             metrics=['accuracy'])
      6     eval_loss,eval_acc=replicated_model.evaluate(eval_dataset)
      7

/usr/local/lib/python3.7/site-packages/tensorflow/python/training/tracking/base.py in _method_wrapper(self, *args, **kwargs)
    454     self._setattr_tracking = False  # pylint: disable=protected-access
    455     try:
--> 456       result = method(self, *args, **kwargs)
    457     finally:
    458       self._setattr_tracking = previous_value  # pylint: disable=protected-access

/usr/local/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py in compile(self, optimizer, loss, metrics, loss_weights, sample_weight_mode, weighted_metrics, target_tensors, distribute, **kwargs)
    459                 'with strategy.scope():\n'
    460                 '  model=_create_model()\n'
--> 461                 '  model.compile(...)'% (v, strategy))
    462
    463   @property

ValueError: Variable (<tf.Variable 'conv2d_1_10/kernel:0' shape=(3, 3, 1, 32) dtype=float32>) was not created in the distribution strategy scope of (<tensorflow.python.distribute.mirrored_strategy.MirroredStrategy object at 0x7f4a5a7814a8>). It is most likely due to not all layers or the model or optimizer being created outside the distribution strategy scope. Try to make sure your code looks similar to the following.
with strategy.scope():
  model=_create_model()
  model.compile(...)

**Comment by gadagashwini** [comment]
@bluesbeyond Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version. Also, did you compile from source or install a binary?

Make sure you also include the exact command if possible to produce the output included in your test case. If you are unclear what to include see the issue template displayed in [the Github new issue template](https://github.com/tensorflow/tensorflow/issues/new/choose).

We ask for this in the issue submission template, because it is really difficult to help without that information. Thanks!

**Comment by gadagashwini** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
