### ISSUE TITLE
Eigen version bump breaks nightly AVX512 build with gcc 6.3

### ISSUE THREAD

**Issue by byronyi** [tensorflow/tensorflow#28411]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Debian 9.9
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy): N/A
- TensorFlow installed from (source or binary): source
- TensorFlow version: e432bf03931f4062f7c5e3a1553aff61a7294751
- Python version: 2.7.13
- Installed using virtualenv? pip? conda?: virtualenv
- Bazel version (if compiling from source): 0.24.1
- GCC/Compiler version (if compiling from source): (Debian 6.3.0-18+deb9u1) 6.3.0 20170516
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

**Describe the problem**

In a GCE VM with AVX512 supported CPU:

```
bazel build --config=opt //tensorflow/tools/pip_package:build_pip_package
```

**Any other info / logs**

```
In file included from /usr/lib/gcc/x86_64-linux-gnu/6/include/immintrin.h:59:0,
                 from external/eigen_archive/unsupported/Eigen/CXX11/../../../Eigen/src/Core/util/ConfigureVectorization.h:318,
                 from external/eigen_archive/unsupported/Eigen/CXX11/../../../Eigen/Core:22,
                 from external/eigen_archive/unsupported/Eigen/CXX11/Tensor:14,
                 from ./third_party/eigen3/unsupported/Eigen/CXX11/Tensor:1,
                 from ./tensorflow/core/framework/tensor_shape.h:21,
                 from ./tensorflow/core/kernels/conv_grad_ops.h:164,
                 from tensorflow/core/kernels/conv_grad_filter_ops.cc:21:
/usr/lib/gcc/x86_64-linux-gnu/6/include/avx512vlbwintrin.h: In function 'typename Eigen::internal::enable_if<Eigen::internal::unpacket_traits<T>::masked_load_available, Packet>::type Eigen::internal::ploadu(const typename Eigen::internal::unpacket_traits<Packet>::type*, typename Eigen::internal::unpacket_traits<Packet>::mask_t) [with Packet = Eigen::internal::Packet16h]':
/usr/lib/gcc/x86_64-linux-gnu/6/include/avx512vlbwintrin.h:105:1: error: inlining failed in call to always_inline '__m256i _mm256_maskz_loadu_epi16(__mmask16, const void*)': target specific option mismatch
 _mm256_maskz_loadu_epi16 (__mmask16 __U, void const *__P)
 ^~~~~~~~~~~~~~~~~~~~~~~~
In file included from external/eigen_archive/unsupported/Eigen/CXX11/../../../Eigen/Core:202:0,
                 from external/eigen_archive/unsupported/Eigen/CXX11/Tensor:14,
                 from ./third_party/eigen3/unsupported/Eigen/CXX11/Tensor:1,
                 from ./tensorflow/core/framework/tensor_shape.h:21,
                 from ./tensorflow/core/kernels/conv_grad_ops.h:164,
                 from tensorflow/core/kernels/conv_grad_filter_ops.cc:21:
external/eigen_archive/unsupported/Eigen/CXX11/../../../Eigen/src/Core/arch/GPU/PacketMathHalf.h:598:38: note: called from here
   result.x = _mm256_maskz_loadu_epi16(mask, from);
              ~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~
Target //tensorflow/tools/pip_package:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 387.379s, Critical Path: 200.24s
INFO: 763 processes: 763 local.
FAILED: Build did NOT complete successfully
```

Bisect to b53fd7648b5ca7eaeceb602617433be6e9a4abec reports the following error:

```
In file included from /usr/lib/gcc/x86_64-linux-gnu/6/include/immintrin.h:59:0,
                 from external/eigen_archive/Eigen/src/Core/util/ConfigureVectorization.h:318,
                 from external/eigen_archive/Eigen/Core:22,
                 from ./third_party/eigen3/Eigen/Core:1,
                 from ./tensorflow/compiler/xla/service/cpu/runtime_conv2d.h:19,
                 from tensorflow/compiler/xla/service/cpu/runtime_conv2d.cc:16:
/usr/lib/gcc/x86_64-linux-gnu/6/include/avx512vlbwintrin.h: In function 'typename Eigen::internal::enable_if<Eigen::internal::unpacket_traits<T>::masked_load_available, Packet>::type Eigen::internal::ploadu(const typename Eigen::internal::unpacket_traits<Packet>::type*, typename Eigen::internal::unpacket_traits<Packet>::mask_t) [with Packet = Eigen::internal::Packet16h]':
/usr/lib/gcc/x86_64-linux-gnu/6/include/avx512vlbwintrin.h:105:1: error: inlining failed in call to always_inline '__m256i _mm256_maskz_loadu_epi16(__mmask16, const void*)': target specific option mismatch
 _mm256_maskz_loadu_epi16 (__mmask16 __U, void const *__P)
 ^~~~~~~~~~~~~~~~~~~~~~~~
In file included from external/eigen_archive/Eigen/Core:202:0,
                 from ./third_party/eigen3/Eigen/Core:1,
                 from ./tensorflow/compiler/xla/service/cpu/runtime_conv2d.h:19,
                 from tensorflow/compiler/xla/service/cpu/runtime_conv2d.cc:16:
external/eigen_archive/Eigen/src/Core/arch/GPU/PacketMathHalf.h:598:38: note: called from here
   result.x = _mm256_maskz_loadu_epi16(mask, from);
              ~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~
Target //tensorflow/tools/pip_package:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 639.500s, Critical Path: 90.25s
INFO: 4690 processes: 4690 local.
FAILED: Build did NOT complete successfully
```

Reverting b53fd7648b5ca7eaeceb602617433be6e9a4abec resolves the issue.

**Comment by byronyi** [comment]
Gentle ping @ezhulenev

**Comment by ezhulenev** [comment]
I guess `from` pointer has to be reinterpret_casted similar to the method above: https://bitbucket.org/eigen/eigen/src/1984a10c33ea299487e6492602076cccc56a97be/Eigen/src/Core/arch/GPU/PacketMathHalf.h#lines-588:600

I'll submit this change to Eigen and will bump the version.

**Comment by ezhulenev** [comment]
Eigen PR is out: https://bitbucket.org/eigen/eigen/pull-requests/639/fix-avx512-gcc-63-compilation/diff

**Comment by byronyi** [comment]
Should be fixed by c9e93a1bbfb7041e9f86c6c73ec617afc5bbcb51, but got the following error:

```
In file included from /usr/lib/gcc/x86_64-linux-gnu/6/include/immintrin.h:59:0,
                 from external/eigen_archive/Eigen/src/Core/util/ConfigureVectorization.h:318,
                 from external/eigen_archive/Eigen/Core:22,
                 from ./third_party/eigen3/Eigen/Core:1,
                 from ./tensorflow/compiler/xla/service/cpu/runtime_single_threaded_conv2d.h:19,
                 from tensorflow/compiler/xla/service/cpu/runtime_single_threaded_conv2d.cc:16:
/usr/lib/gcc/x86_64-linux-gnu/6/include/avx512vlbwintrin.h: In function 'typename Eigen::internal::enable_if<Eigen::internal::unpacket_traits<T>::masked_load_available, Packet>::type Eigen::internal::ploadu(const typename Eigen::internal::unpacket_traits<Packet>::type*, typename Eigen::internal::unpacket_traits<Packet>::mask_t) [with Packet = Eigen::internal::Packet16h]':
/usr/lib/gcc/x86_64-linux-gnu/6/include/avx512vlbwintrin.h:105:1: error: inlining failed in call to always_inline '__m256i _mm256_maskz_loadu_epi16(__mmask16, const void*)': target specific option mismatch
 _mm256_maskz_loadu_epi16 (__mmask16 __U, void const *__P)
 ^~~~~~~~~~~~~~~~~~~~~~~~
In file included from external/eigen_archive/Eigen/Core:202:0,
                 from ./third_party/eigen3/Eigen/Core:1,
                 from ./tensorflow/compiler/xla/service/cpu/runtime_single_threaded_conv2d.h:19,
                 from tensorflow/compiler/xla/service/cpu/runtime_single_threaded_conv2d.cc:16:
external/eigen_archive/Eigen/src/Core/arch/GPU/PacketMathHalf.h:598:38: note: called from here
   result.x = _mm256_maskz_loadu_epi16(mask, reinterpret_cast<const __m256i*>(from));
              ~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Target //tensorflow/tools/pip_package:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 736.417s, Critical Path: 111.79s
INFO: 3870 processes: 3870 local.
FAILED: Build did NOT complete successfully
```

**Comment by ezhulenev** [comment]
@anuj-rawat any ideas what's the problem here?

@byronyi what bazel command are you trying to run? It seems that this problem might be coming from wrong combination of compiler flags. Something similar: https://github.com/xianyi/OpenBLAS/issues/1797

**Comment by anuj-rawat** [comment]
I think the problem might be that `_mm256_maskz_loadu_epi16` requires AVX512VL and AVX512BW. I will update the API similar to what you did in AVX/PacketMath.h to only use AVX intrinsics. If I am unable to do that, I will add a guard.

**Comment by anuj-rawat** [comment]
I could recreate the build failure. I am sure it is because of `_mm256_maskz_loadu_epi16` requiring AVX512VL and AVX512BW. Since currently this API is not used anywhere, I will remove it for now and create an Eigen PR.

**Comment by anuj-rawat** [comment]
The change is now merged in Eigen. The next EIgen bump in TensorFlow should pull it in.

**Comment by jvishnuvardhan** [comment]
Closing this out since I understand it to be resolved, but please let me know if I'm mistaken. Thanks!

**Comment by xieyi4650** [comment]
ubuntu 16.04
gcc 5.4.0 20160609 
python 3.6
bazel: 0.26.1
cuda 10
cudnn 7.6.5
tensorflow:  [r1.14]https://github.com/tensorflow/tensorflow/tree/r1.14
docker image build by using  [dockerfiles](https://github.com/tensorflow/tensorflow/tree/r1.14/tensorflow/tools/dockerfiles),  change python version to python3.6

build command
`bazel build --config=opt --config=cuda  --verbose_failures //tensorflow/tools/pip_package:build_pip_package`


Firstly, I build a docker image, then I build tensorflow in the image. And encountered the same problem.

Any other info / logs:

`/usr/lib/gcc/x86_64-linux-gnu/5/include/avx512vlbwintrin.h: In function 'typename Eigen::internal::enable_if<Eigen::internal::unpacket_traits<T>::masked_load_available, Packet>::type Eigen::internal::ploadu(const typename Eigen::internal::unpacket_traits<Packet>::type*, typename Eigen::internal::unpacket_traits<Packet>::mask_t) [with Packet = Eigen::internal::Packet16h; typename Eigen::internal::enable_if<Eigen::internal::unpacket_traits<T>::masked_load_available, Packet>::type = Eigen::internal::Packet16h; typename Eigen::internal::unpacket_traits<Packet>::type = Eigen::half; typename Eigen::internal::unpacket_traits<Packet>::mask_t = short unsigned int]':
/usr/lib/gcc/x86_64-linux-gnu/5/include/avx512vlbwintrin.h:105:1: error: inlining failed in call to always_inline '__m256i _mm256_maskz_loadu_epi16(__mmask16, const void*)': target specific option mismatch
 _mm256_maskz_loadu_epi16 (__mmask16 __U, void const *__P)
 ^
In file included from external/eigen_archive/Eigen/Core:202:0,
                 from ./third_party/eigen3/Eigen/Core:1,
                 from ./tensorflow/compiler/xla/service/cpu/runtime_single_threaded_conv2d.h:19,
                 from tensorflow/compiler/xla/service/cpu/runtime_single_threaded_conv2d.cc:16:
external/eigen_archive/Eigen/src/Core/arch/GPU/PacketMathHalf.h:598:38: error: called from here
   result.x = _mm256_maskz_loadu_epi16(mask, reinterpret_cast<const __m256i*>(from));
`

other information：

-  I can build successfully with docker image that ubuntu 18.04 gcc 7.4.0 with the same other config above.

-  I have change workspace.bzl "eigen_archive" with [b53fd7648b](https://github.com/tensorflow/tensorflow/commit/b53fd7648b5ca7eaeceb602617433be6e9a4abec) 

gett error:

`./tensorflow/core/kernels/eigen_spatial_convolutions.h:108:61: error: 'masked_store_available' is not a member of 'Eigen::internal::unpacket_traits<__vector(16) float>'
In file included from ./tensorflow/core/util/padding.h:26:0,
                 from ./tensorflow/core/framework/common_shape_fns.h:21,
                 from ./tensorflow/core/framework/resource_mgr.h:25,
                 from ./tensorflow/core/kernels/conv_ops.h:20,
                 from tensorflow/core/kernels/conv_ops.cc:25:
./tensorflow/core/util/tensor_format.h: In function 'int tensorflow::GetTensorSpatialDims(int, tensorflow::TensorFormat)':
./tensorflow/core/util/tensor_format.h:127:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
./tensorflow/core/util/tensor_format.h: In function 'int tensorflow::GetTensorDimsFromSpatialDims(int, tensorflow::TensorFormat)':
./tensorflow/core/util/tensor_format.h:151:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
`

and [e432bf0393](https://github.com/tensorflow/tensorflow/commit/e432bf03931f4062f7c5e3a1553aff61a7294751), 
get error:
`/usr/lib/gcc/x86_64-linux-gnu/5/include/avx512vlbwintrin.h:105:1: error: inlining failed in call to always_inline '__m256i _mm256_maskz_loadu_epi16(__mmask16, const void*)': target specific option mismatch
 _mm256_maskz_loadu_epi16 (__mmask16 __U, void const *__P)
 ^
In file included from external/eigen_archive/Eigen/Core:202:0,
                 from ./third_party/eigen3/Eigen/Core:1,
                 from ./tensorflow/compiler/xla/service/cpu/runtime_conv2d.h:19,
                 from tensorflow/compiler/xla/service/cpu/runtime_conv2d.cc:16:
external/eigen_archive/Eigen/src/Core/arch/GPU/PacketMathHalf.h:598:38: error: called from here
   result.x = _mm256_maskz_loadu_epi16(mask, from);
`

How can I solve this problem? @anuj-rawat @ezhulenev

**Comment by anuj-rawat** [comment]
@xieyi4650 , What is the eigen in your original build with the problem? Is it at [c85345](https://github.com/tensorflow/tensorflow/commit/c853459a0a88187a3a4e8adc6dd1eea6bbd566bc#diff-455a4c7f8e22d7c514e8c2caa27506c5)? - this should have the fix already. The API was removed from  `Eigen/src/Core/arch/GPU/PacketMathHalf.h`

**Comment by xieyi4650** [comment]
clone code by 
git  checkout  r1.14
@anuj-rawat  my workspace.bzl  is：
`name = "eigen_archive",
        sha256 = "74845ea27e19a1bcf63f3f271de62e06798f23e0467bb9d45b83a94918941b23",
        strip_prefix = "eigen-eigen-20cbc6576426",
        urls = [
            "http://mirror.tensorflow.org/bitbucket.org/eigen/eigen/get/20cbc6576426.tar.gz",
            "https://bitbucket.org/eigen/eigen/get/20cbc6576426.tar.gz",
        ],
`
if update urls flowing [c85345](https://github.com/tensorflow/tensorflow/commit/c853459a0a88187a3a4e8adc6dd1eea6bbd566bc#diff-455a4c7f8e22d7c514e8c2caa27506c5) then 
`
ERROR: An error occurred during the fetch of repository 'eigen_archive':
   java.io.IOException: Error downloading [http://mirror.tensorflow.org/bitbucket.org/eigen/eigen/get/a0d250e79c79.tar.gz, https://bitbucket.org/eigen/eigen/get/a0d250e79c79.tar.gz] to /root/.cache/bazel/_bazel_root/b9065c75c7fa26a9c046c3c10662a85c/external/eigen_archive/a0d250e79c79.tar.gz: All mirrors are down: [Connection reset, GET returned 404 Not Found]
ERROR: /tensorflow_1_14_ubuntu16/third_party/eigen3/BUILD:30:1: no such package '@eigen_archive//': java.io.IOException: Error downloading [http://mirror.tensorflow.org/bitbucket.org/eigen/eigen/get/a0d250e79c79.tar.gz, https://bitbucket.org/eigen/eigen/get/a0d250e79c79.tar.gz] to /root/.cache/bazel/_bazel_root/b9065c75c7fa26a9c046c3c10662a85c/external/eigen_archive/a0d250e79c79.tar.gz: All mirrors are down: [Connection reset, GET returned 404 Not Found] and referenced by '//third_party/eigen3:eigen3'
ERROR: Analysis of target '//tensorflow/tools/pip_package:build_pip_package' failed; build aborted: no such package '@eigen_archive//': java.io.IOException: Error downloading [http://mirror.tensorflow.org/bitbucket.org/eigen/eigen/get/a0d250e79c79.tar.gz, https://bitbucket.org/eigen/eigen/get/a0d250e79c79.tar.gz] to /root/.cache/bazel/_bazel_root/b9065c75c7fa26a9c046c3c10662a85c/external/eigen_archive/a0d250e79c79.tar.gz: All mirrors are down: [Connection reset, GET returned 404 Not Found]
`
and when I go to `http://mirror.tensorflow.org/bitbucket.org/eigen/eigen/get/a0d250e79c79.tar.gz` there nothing on it

**Comment by anuj-rawat** [comment]
The fix is not in the Eigen version that you are using.

I am also unable to access `http://mirror.tensorflow.org/bitbucket.org/eigen/eigen/get/a0d250e79c79.tar.gz`, but I can still access the other mirror `https://bitbucket.org/eigen/eigen/get/a0d250e79c79.tar.gz`. Could you try to edit the `workspace.bzl` to remove the mirror that is down and only keep the one that works?

**Comment by xieyi4650** [comment]
@anuj-rawat  
Yes, I have tried to remove the mirror that is down, and get error below. Seems that tensorflow url must be the first.
`
ERROR: An error occurred during the fetch of repository 'eigen_archive':
   tf_http_archive(urls) must have redundant URLs. The mirror.tensorflow.org URL must be present and it must come first. Even if you don't have permission to mirror the file, please put the correctly formatted mirror URL there anyway, because someone will come along shortly thereafter and mirror the file.
ERROR: /tensorflow_1_14_ubuntu16/tensorflow/tools/pip_package/BUILD:155:1: no such package '@eigen_archive//': tf_http_archive(urls) must have redundant URLs. The mirror.tensorflow.org URL must be present and it must come first. Even if you don't have permission to mirror the file, please put the correctly formatted mirror URL there anyway, because someone will come along shortly thereafter and mirror the file. and referenced by '//tensorflow/tools/pip_package:licenses'
ERROR: Analysis of target '//tensorflow/tools/pip_package:build_pip_package' failed; build aborted: no such package '@eigen_archive//': tf_http_archive(urls) must have redundant URLs. The mirror.tensorflow.org URL must be present and it must come first. Even if you don't have permission to mirror the file, please put the correctly formatted mirror URL there anyway, because someone will come along shortly thereafter and mirror the file.
INFO: Elapsed time: 2.693s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (95 packages loaded, 7580 targets configured)
    currently loading: @llvm// ... (2 packages)
`

**Comment by ezhulenev** [comment]
I've just mirrored Eigen to http://mirror.tensorflow.org/bitbucket.org/eigen/eigen/get/a0d250e79c79.tar.gz, either we never mirrored it before, or lost it.
