### ISSUE TITLE
Reset sequence of samples generate by tf.random.uniform without restarting the session

### ISSUE THREAD

**Issue by BrEr** [tensorflow/tensorflow#28428]
As of the rules I have raised this issue on StackOverflow but it's dying a slow death over there, therefore I ask it here: https://stackoverflow.com/questions/55951644/reset-sequence-of-samples-generate-by-tf-random-uniform-without-restarting-the-s

I can set the seed of the random.uniform operation, but this seed is only used as "starting-point" of the session. I cannot instruct the tensor to "re-initialize" from the set seed.

I want to train my model on random samples generated by random.uniform and every batch I want the same samples to be used, without having to store these samples.

I could create one big array to write these uniform samples into and use that to train upon, but using random.uniform tensor with a "reset" of the seed every batch seems more elegant and more memory friendly. In some use cases I have to create millions and millions of random uniform samples. Using tf.data with a random.uniform tensor should be way more elegant.

**Comment by achandraa** [comment]
Please provide details such as platform you are using (operating system, architecture), TensorFlow version used. If possible, please provide the minimal code snippet which can depict the issue at hand. You can refer this [template](https://github.com/tensorflow/tensorflow/issues/new/choose) to fill in the required information. Thanks!

**Comment by achandraa** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Comment by BrEr** [comment]
I am using both Windows 7 and Ubuntu 18.04 and the issue is the same for both platforms cause I am trying to figure out how I can use the API. I am using TF 1.13.
