### ISSUE TITLE
Why we cannot define two networks in the same graph when they are trained independently

### ISSUE THREAD

**Issue by Firyuza** [tensorflow/tensorflow#28421]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using): 1.4.1
- Are you willing to contribute it (Yes/No): No

**Describe the feature and the current behavior/state.**
Why we cannot define two networks in the same graph when they are trained independently.

It can be done only using two different grpahs.

**Will this change the current api? How?**
No, just allow to define two networks in the same graph that have to be trained independently.

**Who will benefit with this feature?**

Developers and production code. Because it's time and memory consuming to create two graphs.

**Any Other info.**

**Comment by tilakrayal** [comment]
@Firyuza,
Here is the work-around, please try from your end.
Please try to make a separate graph for each network to run them in parallel in different sessions:

```
graph1 = tf.Graph()
with graph1.as_default():
  model1 = build_model()

graph2 = tf.Graph()
with graph2.as_default():
  model2 = build_model()
```
  
the build_model() defines all placeholders, variables and training ops. Both models should use the same naming for variables, which will allow them to swap easily.

Each network can be trained using a snapshot of the other network for the target (the latest or previous best). Periodically, each network is saved to the disk via **tf.Saver()** and restored using the weights of one of the networks.  Thank you!
