### ISSUE TITLE
TensorFlow Lite conversion of frozen graph error

### ISSUE THREAD

**Issue by Dayananda-V** [tensorflow/tensorflow#28438]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04.2
- TensorFlow installed from (source or binary): Source
- TensorFlow version (or github SHA if from source): 2f9cc84ba3f5d59753d843f167adee2e2534c143

**Provide the text output from tflite_convert**
While converting [faster_rcnn_nas](http://download.tensorflow.org/models/object_detection/faster_rcnn_nas_coco_2018_01_28.tar.gz) from tensoflow trained model to tensorflow lite found some error.
```
Unsupported Control Flow Ops:
1. Enter
2. Exit
3. Merge
4. Switch
5. LoopCond

Unsupported Lite Ops:
1. NonMaxSuppressionV2
2. TensorArrayGatherV3
3. TensorArrayReadV3
4. TensorArrayScatterV3
5. TensorArraySizeV3
6. TensorArrayV3
7. TensorArrayWriteV3

Unsupported Quantize Ops:
1. Div
2. Exp
3. Cast
4. Fill
5. Range
6. Size
7. Tile
8. ZerosLike
9. Unpack 

```

Also, please include a link to a GraphDef or the model if possible.

**Any other info / logs**

Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.
[faster_rcnn_nas_lite_error.txt](https://github.com/tensorflow/tensorflow/files/3148187/faster_rcnn_nas_lite_error.txt)

**Comment by amitsrivastava78** [comment]
@jdduke  This seems to be a problem faced by alot of people in the past, is there any plans of implementing the data flow ops in the tflite ? Also would like to know your take on implementing it along with flow_in's which is tricky thing to do.
If you are ok would like to raise on RFC for this and take it forward for implementation.

Regards
Amit

**Comment by jdduke** [comment]
@miaout17 can you de-dupe against our tracking control flow issue? We'll be improving the documentation around control flow-related conversion in the near future (an area we're actively working to improve over the next several quarters).

**Comment by alanchiao** [comment]
Would it be helpful at all for us to add an error message in TOCO where it points directly to a FAQ or Github issue (for control flow / LSTMs) when there is an Unsupported Control Flow Op?

**Comment by miaout17** [comment]
Let's use #28485 for tracking TensorFlow Lite control flow support. A RFC already existed. 
@alanchiao sounds a good idea.

**Comment by ANSHUMAN87** [comment]
Unpack PR is already raised & approved: #27881

**Comment by Dayananda-V** [comment]
Range op quantization support found ynder #27103

**Comment by amitsrivastava78** [comment]
Quantization support for Exp is raised as PR now.

Regards
Amit

**Comment by garikana** [comment]
The PR for Quantization support for Exp was closed. Any update on when/if this will be include in future?

Thanks,
Alex

**Comment by tilakrayal** [comment]
@Dayananda-V,
The related issue #28485 was closed & where it was mentioned that With a new converter now the default. TFLite should support Control Flow V2 ops. If you have a model with control flow ops, please try to enable control flow v2.
to enable Control flow v2: **tf.enable_control_flow_v2()** and also the PR #27881 was merged for Quantization support added for Unpack Op. Thank you!
