### ISSUE TITLE
How to enable INTEL_MKL_ML?

### ISSUE THREAD

**Issue by fengyuICT** [tensorflow/tensorflow#28437]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 16.04
- TensorFlow installed from (source or binary):  source
- TensorFlow version: 1.10
- Python version: 2.7.13
- Installed using virtualenv? pip? conda?:  none
- GCC/Compiler version (if compiling from source): 5.4
- Intel CPU

**Describe the problem**
I want build tensorflow with mkl that use the command below:
bazel build tensorflow/tools/benchmark:benchmark_model --verbose_failures -c opt --copt=-march=native --config=mkl --copt="-mfpmath=both" --copt=-mavx --copt=-mavx2 --copt=-mfma --copt=-msse4.2
but when I gdb with file tensorflow/core/kernels/mkl_conv_ops.cc, I find INTEL_MKL_ML is disabled and use the #else branch code.
you can read the file tensorflow/core/kernels/mkl_conv_ops.cc that
#ifdef INTEL_MKL_ML
class MklConv2DOp : public OpKernel {
  Path1
}
#else 
class MklConv2DOp : public OpKernel {
  Path2
}
#endif
WHY tensorflow execute Path2 not Path1? what the difference between these two paths?

**Provide the exact sequence of commands / steps that you executed before running into the problem**

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by fengyuICT** [comment]
Is build option "--config=mkl" means that tensorflow use mkl-dnn as default? So how can i build tensorflow with mkl-ml?

**Comment by Leslie-Fang** [comment]
if you didn't want to use mkldnn, could you try this build options "--copt=-DINTEL_MKL_ML_ONLY"? And see if it would use the path1 you mentioned above

**Comment by achandraa** [comment]
@fengyuICT : Please have a look on @Leslie-Fang's suggestion and let us know if that helps. Thanks!

**Comment by fengyuICT** [comment]
I use tensorflow 1.10, it has macro INTEL_MKL_ML, so I add options --copt=-DINTEL_MKL_ML according to @Leslie-Fang , it works. Thanks ^_^
