### ISSUE TITLE
Tensorflow 1.12.2 a typo for 1.13.2?

### ISSUE THREAD

**Issue by PallHaraldsson** [tensorflow/tensorflow#28439]
I note there was 1.12.0, but no 1.12.1.

https://github.com/tensorflow/tensorflow/releases has 1.12.2.

**Comment by mihaimaruseac** [comment]
No, the vulnerability was fixed on master for 1.13 but we also made a patch release for 1.12. There is no 1.12.1 as that tag exists on master instead of on the r1.12 branch.

**Comment by Ark-kun** [comment]
> There is no 1.12.1 as that tag exists on master instead of on the r1.12 branch.

Given the v1.12.1 tag on the releases page this is really confusing.

TF Bazel build is currently broken and it's really hard to find out whether there is any release containing the fix.

**Comment by mihaimaruseac** [comment]
Note that 1.13.2 has been released now
