### ISSUE TITLE
Load Images

### ISSUE THREAD

**Issue by iqbalhabibie** [tensorflow/tensorflow#28445]
There is some problem in loading images 

for n in range(3):
  image_path = random.choice(all_image_paths)
  display.display(display.Image(image_path))
  print(caption_image(image_path))
  print()

Error:
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-9-dd286b0cbeda> in <module>
      2   image_path = random.choice(all_image_paths)
      3   display.display(display.Image(image_path))
----> 4   print(caption_image(image_path))
      5   print()

<ipython-input-8-a5b6e935786e> in caption_image(image_path)
      3 def caption_image(image_path):
      4     image_rel = pathlib.Path(image_path).relative_to(data_root)
----> 5     return "Image (CC BY 2.0) " + ' - '.join(attributions[str(image_rel)].split(' - ')[:-1])
      6 

KeyError: 'daisy\\3764116502_f394428ee0_n.jpg'

Please what is the problem?

<em>Thanks so much for taking the time to file a documentation issue and even
more thanks if you intend to contribute to updating it! Please do introduce
yourself on our mailing list with
[Google Groups](https://groups.google.com/a/tensorflow.org/forum/#!forum/docs)
or [email](mailto:docs@tensorflow.org) and let us know if you have any
questions. We also encourage you to review our
[Documentation Contributor Guide](https://www.tensorflow.org/community/contribute/docs).
As a side note, per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:doc_template</em>

## Existing URLs containing the issue:

Link to the documentation entry, for example:
https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/MyMethod

### Correct Links

Is the link pointing to the source code correct? To find the source code, use
`git grep my_method` from the git command line in your locally checked out
repository.

### Clear Description

Why should someone use this method? How is it useful?

### Usage Example

Is there a usage example?

### Parameters Defined

Are all arguments that can be passed in defined and formatted correctly?

### Returns Defined

Are return values defined?

### Raises Listed and Defined

Are errors defined?
[Example](https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/feature_column/categorical_column_with_vocabulary_file#raises)

### Request Visuals, if Applicable

Are there currently visuals? If not, would they make the content clearer?

### Submit PR?

Are you planning to also submit a
[Pull Request](https://help.github.com/en/articles/about-pull-requests) to fix
this issue? See the
[Documentation Contributor Guide](https://www.tensorflow.org/community/contribute/docs)
the
[Documentation Style Guide](https://www.tensorflow.org/community/contribute/docs_style).

**Comment by muddham** [comment]
@iqbalhabibie I clicked on the link provided (https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/MyMethod) , it says 404 error on page

**Comment by jvishnuvardhan** [comment]
@iqbalhabibie Thanks for finding this link that is not working. On which page, you found the link? Thanks!

**Comment by jvishnuvardhan** [comment]
Closing due to lack of recent activity. Please update the issue when new information becomes available, and we will open a new issue. Thanks!
