### ISSUE TITLE
Improper output shape of DenseFeatures layer with numeric_column 

### ISSUE THREAD

**Issue by durandg12** [tensorflow/tensorflow#28440]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Mac OS 10.13.6
- TensorFlow installed from (source or binary): from pip I think, I don't remember and I don't know the difference
- TensorFlow version: v1.12.0-10066-g5cbe8af8ed 2.0.0-dev20190313
- Python version: 3.6.7

**Describe the problem**

I am using the `DenseFeatures` layer feeded with a feature `numeric_column` with a shape argument of `shape=(3,1)`. According to [the documentation of `numeric_column`](https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/feature_column/numeric_column?hl=en), the output tensor has shape [batch_size] + `shape`. My batch size is 2 and instead of having shape `(2,3,1)` as indicated by the documentation, my output tensor only has output shape of `(2,3)`.

**Provide the exact sequence of commands / steps that you executed before running into the problem**

Here is a minimal working example reproduccing the issue:

```
from tensorflow.data import Dataset
from tensorflow.feature_column import numeric_column
from tensorflow.keras.layers import DenseFeatures

raw_dataset = {'feature1': [[3., 4., 6.], [2., 12., 7.]]}
dataset = Dataset.from_tensor_slices(raw_dataset)
batch_size = 2
batched = dataset.batch(batch_size)
feature_column = numeric_column('feature1', shape=(3,1))
layer = DenseFeatures(feature_column)
for y in batched:
    pass
layer(y)
```

the output of which is

```
<tf.Tensor: id=19, shape=(2, 3), dtype=float32, numpy=
array([[ 3.,  4.,  6.],
       [ 2., 12.,  7.]], dtype=float32)>
```

**Comment by achandraa** [comment]
@durandg12 : I was able to reproduce the output with TensorFlow version 2.0.0-dev20190313 and 2.0.0-alpha0.

**Comment by durandg12** [comment]
The issue is still here in v1.12.1-3259-gf59745a381 2.0.0-beta0

**Comment by durandg12** [comment]
The issue is still here in tf2.0.0.

**Comment by yhliang2018** [comment]
The output is correct, and this is not an issue. The [doc](https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/feature_column/numeric_column?hl=en#args) on  `shape` arg in `numeric_column` means the shape of input tensor to the column (indexed by the `key` arg), not the output one. You may check the docstring of the args `shape` and `default_value` for more details.
