### ISSUE TITLE
How to export a eager mode checkpoint for tfserving

### ISSUE THREAD

**Issue by beichen2012** [tensorflow/tensorflow#28459]
I have train a model by tf1.13 and eager mode, then save it to checkpoint.

now I need to export the model to pb file and deploy on tfserving ?

Is there any one help me?

**Comment by allenlavoie** [comment]
I'd check out the SavedModel guide: https://www.tensorflow.org/alpha/guide/saved_model. You'll want to export a `@tf.function` for serving.

Not really a bug though; please ask these kinds of things on StackOverflow so it's easier to archive the answers.

**Comment by beichen2012** [comment]
> I'd check out the SavedModel guide: https://www.tensorflow.org/alpha/guide/saved_model. You'll want to export a `@tf.function` for serving.
> 
> Not really a bug though; please ask these kinds of things on StackOverflow so it's easier to archive the answers.

tf1.13 had no tf.function.
And if using tf2.0's savedModel, It can not loads  tf1.13's checkpoints correctly.

**Comment by allenlavoie** [comment]
> And if using tf2.0's savedModel, It can not loads tf1.13's checkpoints correctly.

Not sure what that means. If you have code you think should work, please file a bug with a reproduction and I'm happy to take a look.

**Comment by beichen2012** [comment]
Thanks for your reply.
Finally, the graph mode works .
