### ISSUE TITLE
Poor performance on debug version

### ISSUE THREAD

**Issue by Leslie-Fang** [tensorflow/tensorflow#28462]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Centos7.5
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): Source
- TensorFlow version (use command below): 1.12
- Python version: 3.6
- Bazel version (if compiling from source): 0.19
- GCC/Compiler version (if compiling from source): 6.3
- CUDA/cuDNN version:
- GPU model and memory:

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
I build tensorflow from source code for debug with the options **"-c dbg"** 
I also remove the build options: **"-c opt --copt=-O3"**
With this debug version, I only get 1/10 performance comparing with the release version.
I don't know it's normal in your aspect?
Which one(add "-c dbg" or remove "-c opt --copt=-O3") may majorly cause this problem.

**Describe the expected behavior**
Debug version and release version has similar performance.

**Comment by gadagashwini** [comment]
@Leslie-Fang Could you provide more details about the issue and context? Also, In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thanks!

**Comment by Leslie-Fang** [comment]
@gadagashwini Thanks for you reply.

**Comment by Leslie-Fang** [comment]
I suppose it's a expected behavior.
