### ISSUE TITLE
Issue in using Tensorflow lite GPU delegate on iOS device

### ISSUE THREAD

**Issue by arun-sn1** [tensorflow/tensorflow#28468]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): macOS 10.13.6
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:iPhone X
- TensorFlow installed from (source or binary): Binary
- TensorFlow version (use command below): 1.13.1
- Python version: 3.7.3
- Bazel version (if compiling from source): NA
- GCC/Compiler version (if compiling from source): NA
- CUDA/cuDNN version: NA
- GPU model and memory: NA

**Describe the current behavior**
I am trying to benchmark a custom TF lite model on Android and iOS devices with the GPU delegate option. On the Android device(Google Pixel 3), I am able to successfully benchmark the model using the Tensorflow provided benchmark utility (https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/tools/benchmark).

Running the same model on iOS device (iPhone X) without GPU delegate option works fine. However when I try to run it with the GPU delegate option I observe the following error:

**tflite_camera_example[572:134773] [DYMTLInitPlatform] platform initialization successful
Loaded model 1resolved reporter
tflite_camera_example[572:134606] Metal GPU Frame Capture Enabled
tflite_camera_example[572:134606] Metal API Validation Enabled
**depth_multiplier 16 != weights output channels 1**
Node number 53 (MetalGpuDelegate) failed to prepare.
Node number 53 (MetalGpuDelegate) failed to prepare.
Failed to allocate tensors!
tflite_camera_example[572:134606] [MC] System group container for systemgroup.com.apple.configurationprofiles path is /private/var/containers/Shared/SystemGroup/systemgroup.com.apple.configurationprofiles
tflite_camera_example[572:134606] [MC] Reading from public effective user settings.
(lldb)** 

I am modifying the iOS Tensorflowlite sample camera app(https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/examples/ios/camera) as per the instructions in this video from Tensorflow : https://www.youtube.com/watch?v=a5H4Zwjp49c&feature=youtu.be to evaluate the GPU delegate option.

**Describe the expected behavior**
Should be able to run the inference using the GPU delegate on iOS with the same model that worked on android

**Code to reproduce the issue**

**Other info / logs**

**Comment by manoharyes** [comment]
Any update on this issue? I am also facing the same issue. Need urgent help!

**Comment by NikolayChirkov** [comment]
[commit](https://github.com/tensorflow/tensorflow/commit/403417fdc85650181f894ee0aa0fb85dfa75fea4) should resolve the issue.
@manoharyes on which version do you have the issue?

**Comment by manoharyes** [comment]
@NikolayChirkov I am not building TF-lite GPU delegate from source and using it . I am modifying the TF-lite iOS camera example app to evaluate the GPU delegate, which uses pod file based method to fetch the TF-lite GPU delegate library . In the pod file both the options namely : pod 'TensorFlowLiteGpuExperimental' and pod 'TensorFlowLiteGpuExperimental', '0.0.1'  resulted in the same error described in this issue 
 
Could you share the instructions for building the TF-lite GPU delegate for iOS ? 
Any reference to sample iOS application/example that uses this prebuilt TF-lite GPU delegate would also be really useful.

**Comment by tsujie** [comment]
Yes, I saw a similar issue after using my own built tensorflow_lite_gpu.framework.
I built it at latest master branch and have to fix minor errors in metal_delegate.mm. Then built it using 
`bazel build --apple_platform_type ios --cpu=ios_arm64 --cxxopt=-std=c++14 -c opt --copt -DTFLITE_GPU_BINARY_RELEASE --copt -fvisibility=hidden --linkopt -s tensorflow/lite/delegates/gpu:libtensorflowlite_gpu_metal.so`
Built succeed, but when I use it in my app, I get error: Error initialization of input buffer converter

**Comment by arun-sn1** [comment]
I was able to build the latest code of TF-lite GPU delegate for iOS . With this TF-lite GPU delegate library the earlier error (depth_multiplier 16 != weights output channels 1) is no longer there. However when I try to run GPU based inference on my custom model the following error is observed :

**Initialized TensorFlow Lite runtime.
Created TensorFlow Lite delegate for Metal.
Metal GPU Frame Capture Enabled
Metal API Validation Enabled
Execution of the command buffer was aborted due to an error during execution. Caused GPU Hang Error (IOAF code 3)**

@NikolayChirkov  : Any suggestions on how to address this issue? 

@tsujie : I faced a similar error when I ran GPU based inference on iOS devices with SW version below 12.0, but not on devices with version greater than or equal to 12.0

**Comment by weinixuehao** [comment]
@tsujie Can build binary for ios with universal binary at once?

**Comment by tsujie** [comment]
@weinixuehao I need to built libmetal_delegate.a firstly, then run ios universal build script to create the final framework

**Comment by weinixuehao** [comment]
@tsujie if so you need to build libmetal_delegate several time for x86 armv7 arm64 ... ?
Do i uderstand correctness ?

**Comment by weinixuehao** [comment]
@tsujie arm64 x86_64 compiled successfully but armv7 armv7s is failed

**Comment by tsujie** [comment]
@weinixuehao I only built arm64 & x86_64

**Comment by weinixuehao** [comment]
@tsujie 
![image](https://user-images.githubusercontent.com/17869361/60074748-3b563d80-9756-11e9-884f-503b91da1c81.png)
This issue has fixed?

**Comment by NikolayChirkov** [comment]
That's weird. Looking into.

**Comment by tsujie** [comment]
@weinixuehao I built at latest master branch. It is working now.

**Comment by weinixuehao** [comment]
@tsujie 
What date you built?  My is at latest master too.

**Comment by weinixuehao** [comment]
@tsujie @NikolayChirkov
![image](https://user-images.githubusercontent.com/17869361/60144984-1960c780-97f7-11e9-8925-5b64bfff211a.png)
May be this reason which not support simulator
![image](https://user-images.githubusercontent.com/17869361/60145098-83796c80-97f7-11e9-89b3-044387240c7d.png)
![image](https://user-images.githubusercontent.com/17869361/60145104-8b391100-97f7-11e9-8129-dc7da784a1dc.png)
Both print outputs is null

**Comment by faizanophobia** [comment]
> @NikolayChirkov I am not building TF-lite GPU delegate from source and using it . I am modifying the TF-lite iOS camera example app to evaluate the GPU delegate, which uses pod file based method to fetch the TF-lite GPU delegate library . In the pod file both the options namely : pod 'TensorFlowLiteGpuExperimental' and pod 'TensorFlowLiteGpuExperimental', '0.0.1'  resulted in the same error described in this issue
>  
> Could you share the instructions for building the TF-lite GPU delegate for iOS ?
> Any reference to sample iOS application/example that uses this prebuilt TF-lite GPU delegate would also be really useful.

Is this solved?Were you able to run it with GPU on iOS device?
I am also facing the same issue!
