### ISSUE TITLE
 Where is the entry point for Receiver to receive Tensor using GRPC?

### ISSUE THREAD

**Issue by garygb** [tensorflow/tensorflow#28464]
I'm a student trying to understand how distributed TensorFlow transmits Tensor through GRPC. I have now found that the Sender is issuing a generic asynchronous request by calling the `IssueRequest` tool function(as listed below), but how does the Receiver respond to this request? Where is the entry point?

>   // file path: \tensorflow-r1.12\tensorflow\core\distributed_runtime\rpc\grpc_remote_worker.cc
  // Utility method for issuing a generic asynchronous request. The
  // given callback, `done`, will be called when the RPC completes.
  void IssueRequest(const protobuf::Message* request, TensorResponse* response,
                    const ::grpc::string& method, StatusCallback done,
                    CallOptions* call_opts = nullptr) {
        new RPCState<TensorResponse>(&stub_, cq_, method, *request, response,
                                     std::move(done), call_opts);
  }

Thanks!

**Comment by achandraa** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged//tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.
