### ISSUE TITLE
Poor performance while writing custom layers

### ISSUE THREAD

**Issue by nishantb21** [tensorflow/tensorflow#28465]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- Windows 10
- Tensorflow installed from pre-built binary
- TensorFlow version: 1.13.1
- Python: 3.6.6
- CUDA/cuDNN version: 10.0/7.1
- GPU model and memory: GTX 960M/4GB
- CPU: Intel i7 6700HQ

**Describe the current behavior**
I recently had the requirement to code a slightly different version of the convolution layer. The first choice for me was to build a custom layer using your article [here](https://www.tensorflow.org/tutorials/eager/custom_layers). I coded a naive version of 2D Convolution using a O(n^4) code just for basic prototyping. I used a lot of low-level operations like tf.ones, tf.concat, tf.tile, tf.reduce_sum and matrix slicing. To measure inference time I decided to call the object manually by supplying a (256, 256, 3) image as input to the overridden call() method. However, before calling I  included a tf.enable_eager_execution() call at the starting of the code by mistake. The code takes 50 seconds to execute the code on GPU(I monitored the GPU usage so I know it is using the GPU indeed). The peculiar part is that when I omit the tf.enable_eager_execution() it seems to run on the CPU rather inefficiently, in about 980 seconds. To have a yardstick for CPU execution, I re-wrote the same O(n^4) code using numpy exclusively and it takes just 210 seconds.

I also included the custom layer as part of a tf.keras.model and simply printed the model summary. The issue in this scenario is that it seems to execute the entire call routine to print the summary which essentially means that it takes 980 seconds to just print the summary!

**Describe the expected behavior**
There are a couple of questions I have:

1. While I realize that numpy and tensorflow as two completely different libraries, should the disparity in performance be this much? I am overriding the __init__, build and call functions while making the appropriate super calls as per your article. Am I doing something wrong?
2. Do custom layers use the CPU by default? I also tried forcing it by including a with tf.device("/gpu:0") call but that doesn't seem to help at all.

I realize that it might be more efficient to code the convolution by adding a custom op but I want to avoid that in the prototyping stage as much as possible.

**Code to reproduce the issue**
I cannot reveal the code for proprietary reasons but I could furnish a similar version if need be.

Any help in this regard would be much appreciated.

**Comment by achandraa** [comment]
It will be great if you can provide us with the minimal code snippet which can replicate the scenario. Thanks!

**Comment by ymodak** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
