### ISSUE TITLE
Why does TF run ops in the build phase?

### ISSUE THREAD

**Issue by shizukanaskytree** [tensorflow/tensorflow#28463]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information** 
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 16.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): source 
- TensorFlow version:  tf-nightly-1.13.1
- Python version: python 3
- Installed using virtualenv? pip? conda?:  pip
- Bazel version (if compiling from source):  0.23.2
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 10.0/7
- GPU model and memory: 1080ti

**Describe the problem**

**Provide the exact sequence of commands / steps that you executed before running into the problem**

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

Add logging to the code:

```cpp
...
std::clog << "Terminated \n";
ec_.Notify(true);
return false;
...
```

Bazel build output:

```bash
INFO: From Executing genrule //tensorflow/python:cudnn_rnn_ops_pygenrule:
Terminated  # my std::clog output
Terminated 
Terminated 
Terminated 
Terminated 
Terminated 
Terminated 
Terminated 
Terminated 
Terminated 
Terminated 
Terminated 
Terminated 
Terminated 
Terminated 
Terminated 
INFO: From Executing genrule //tensorflow/python:candidate_sampling_ops_pygenrule:
Terminated 
Terminated 
Terminated 
Terminated 
Terminated 
Terminated 
Terminated 
Terminated 
Terminated 
Terminated 
Terminated 
Terminated 
Terminated 
Terminated 
Terminated 
Terminated 
```

I use local eigen instead of the remote repo. I try to tracing / logging eigen library, like `WaitForWork`. 
I find that when I build TF from source, it seems like TF runs the code. Worse, it will segmentation fault / core dump if I add logging to some part code of eigen, like loop.
What is the design behind it?

**Comment by muddham** [comment]
@shizukanaskytree  This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.If you think we've misinterpreted a bug, please comment again with a clear explanation, as well as all of the information requested in the [issue template](https://github.com/tensorflow/tensorflow/issues/new/choose). Thanks!
