### ISSUE TITLE
adjust_hsv_nhwc doesn't process all items

### ISSUE THREAD

**Issue by ThisIsIsaac** [tensorflow/tensorflow#28460]
CUDA kernel  "adjust_hsv_nhwc" in [adjust_hsv_gpu.cu.h](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/kernels/adjust_hsv_gpu.cu.h) doesn't fully iterate through all the items in the input array when the number of threads spawned is larger than the total number of items. A simple fix would be to have each thread iterate through all the items inside a for-loop in order to check that all the items in the input array has been processed. I have implemented a fix for this kernel, and would like to send a pull request after consulting with a dev from TF. ( I can attach my test code if needed )

**Comment by muddham** [comment]
@ThisIsIsaac Thanks for your effort. Please provide your code and elaborate in detail the added fix.

**Comment by muddham** [comment]
@ThisIsIsaac Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Comment by ThisIsIsaac** [comment]
@muddham
Sorry for not mentioning here. I have made a [pull request](https://github.com/tensorflow/tensorflow/pull/28686) for the bug and asked one of the TF devs in contact to review.
