### ISSUE TITLE
suppress logging messages in tf2.0

### ISSUE THREAD

**Issue by jinfagang** [tensorflow/tensorflow#28473]
We have tf.logging.set_verbesity() in tf1.x.

but tf2.0 there is not such module, what should we do?

**Comment by achandraa** [comment]
Please have a look on heading Some Highlights in this [link](https://github.com/tensorflow/tensorflow/releases) which says tf.logging is not supported in 2.0. Let us know if that resolves the issue. Thanks!

**Comment by achandraa** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
