### ISSUE TITLE
checkpoint.save failure on colab when using MirroredStrategy

### ISSUE THREAD

**Issue by Chadys** [tensorflow/tensorflow#28482]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): no
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Google Colab GPU execution
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: /
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below):  1.14.1-dev20190507
- Python version: 3.6.7
- Bazel version (if compiling from source): /
- GCC/Compiler version (if compiling from source): /
- CUDA/cuDNN version: 10.0/7.5.0
- GPU model and memory: Tesla K80

**Describe the current behavior**
The tutorial *tf.distribute.Strategy with Training Loops* fails on the `checkpoint.save(checkpoint_prefix)` call when I run it on Colab, as does any other attempt on my part to use checkpoints with Mirrored strategy in Colab with custom loop. The VM still has lots of disk memory so no problem on this part. I also tried to make it save on a mounted Google drive with no more success.

**Describe the expected behavior**
Checkpoint saving without error.

**Code to reproduce the issue**
Run this in Google Colab : https://www.tensorflow.org/alpha/tutorials/distribute/training_loops
For the code to execute without error (until the save), you'll need to replace
```python
  loss_object = tf.keras.losses.SparseCategoricalCrossentropy(
      reduction=tf.keras.losses.Reduction.NONE)
```
with

```python
  from tensorflow.python.keras.utils import losses_utils
  loss_object = tf.keras.losses.SparseCategoricalCrossentropy(
      reduction=losses_utils.ReductionV2.NONE)
```

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.
```
---------------------------------------------------------------------------

ValueError                                Traceback (most recent call last)

<ipython-input-55-2d2ddd674439> in <module>()
     26 
     27     if epoch % 2 == 0:
---> 28       checkpoint.save(checkpoint_prefix)
     29 
     30     template = ("Epoch {}, Loss: {}, Accuracy: {}, Test Loss: {}, "

6 frames

/usr/local/lib/python3.6/dist-packages/tensorflow/python/distribute/values.py in handle(self)
    578       device = distribute_lib.get_update_device()
    579       if device is None:
--> 580         raise ValueError("`handle` is not available outside the replica context"
    581                          " or a `tf.distribute.Strategy.update()` call.")
    582     return self.get(device=device).handle

ValueError: `handle` is not available outside the replica context or a `tf.distribute.Strategy.update()` call.
```

**Comment by Chadys** [comment]
I reran the tutorial by first calling `tf.enable_eager_execution()` and it works. Weird, I thought that eager_execution was on by default in 2.0, seems not. So checkpoint is only failing in graph mode, maybe you can't use it that way in this mode. The 2.0 docs are great but graph mode examples are still a bit sparse.

**Comment by ymodak** [comment]
@Chadys I was able to execute the colab successfully as is. 
I see that you are using TF 1.14 whereas the tutorial requires TF 2.0 Alpha gpu (default version in colab)
Are you trying to test this colab in TF 1.X?

**Comment by Chadys** [comment]
Yeah it seems to be the wrong tf version that is getting used, but why would that be ? I didn't touch the `!pip install tensorflow-gpu==2.0.0-alpha0`

**Comment by Chadys** [comment]
Found the problem : I had another notebook opened, on which I was working at the same time, where I did the import this way :
```colab
!pip install -q tensorflow-gpu==2.0.0-alpha0
!pip install -q tf-nightly-gpu
```
instead of 
```colab
!pip install -q tensorflow-gpu==2.0.0-alpha0
!pip install -q tf-nightly-gpu-2.0-preview
```
So the 2.0 alpha was replaced by the latest 1.x nightly version. When I opened the notebook of the tutorial, it used the same virtual environment as my other notebook and so, since the requirement tensorflow-gpu==2.0.0-alpha0 was already satisfied, it didn't install anything else and kept using the 1.X nightly, hence the errors.
Take care when you run different notebook in the same environment, lesson learned ! Sorry for the bother, problem resolved !
