### ISSUE TITLE
Enable Slack Github Integration and Notifications

### ISSUE THREAD

**Issue by devstein** [tensorflow/tensorflow#28480]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using): NA
- Are you willing to contribute it (Yes/No): NA

**Describe the feature and the current behavior/state.**

I want to the Slack Github integration to notify my team of activity in `tensorflow/tensorflow`, but I received an error: 
```
Either the app isn't installed on your repository or the repository does not exist. Install it to proceed.
```

To reproduce:

1. Add GitHub app to your Slack workspace
2. In a channel, run `/github subscribe tensorflow/tensorflow`
3. See error 

**Will this change the current api? How?**
NA

**Who will benefit with this feature?**
Everyone who uses Slack for GitHub notifications! 

**Any Other info.**
Only an organization owner can enable this integration

**Comment by devstein** [comment]
This behavior can be mimic-ed in slack by subscribing the Github projects RSS feed

`/feed https://github.com/tensorflow/tensorflow/releases.atom`

**Comment by martinwicke** [comment]
The error message sounds like that would require us to install a slack app on tensorflow. Unfortunately, this is not something we can do. I hope the workaround suggested by @devstein works for you.
