### ISSUE TITLE
cudnn.so could not be found when using bazel-0.21.0 in r1.13

### ISSUE THREAD

**Issue by xinan-jiang** [tensorflow/tensorflow#28497]
**System information**
- OS Platform and Distribution : Linux 3.10.0-CentOS 7
- TensorFlow installed from: source
- TensorFlow version: **r1.13**
- Python version: 2.7
- Bazel version : **0.21.0**
- GCC/Compiler version (if compiling from source): 4.8.5
- CUDA/cuDNN version: cuda9.0/cudnn7.3.1
- GPU model and memory: V-100

**Describe the problem**
I encountered below error using **bazel-0.21.0**. It has gone when replaced with bazel-0.19.2
ERROR: /apsarapangu/disk2/xinan.jxn/my_git/tensorflow/tensorflow/python/BUILD:1847:1: Executing genrule //tensorflow/python:sdca_ops_pygenrule failed (Exit 127): bash failed: error executing command
  (cd /root/.cache/bazel/_bazel_root/xxxxxx/execroot/org_tensorflow && \
  exec env - \
    PATH=/bin:/usr/bin \
  /bin/bash bazel-out/host/genfiles/tensorflow/python/sdca_ops_pygenrule.genrule_script.sh)
Execution platform: @bazel_tools//platforms:host_platform
bazel-out/host/bin/tensorflow/python/gen_sdca_ops_py_wrappers_cc: error while loading shared libraries: libcudnn.so.7: cannot open shared object file: No such file or directory

I have added right LD_LIBRARY_PATH "/usr/local/cuda/lib64:/usr/local/cuda/extras/CUPTI/lib64"
and libcudnn.so.7 is just in /usr/local/cuda/lib64

**Comment by achandraa** [comment]
Did you try to follow the steps mentioned [here](https://www.tensorflow.org/install/source) for the installation. Please let us know. Thanks!

**Comment by achandraa** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
