### ISSUE TITLE
TF_LoadLibrary in c++ when loading resampler.so

### ISSUE THREAD

**Issue by mwsunshine** [tensorflow/tensorflow#28496]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):16.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): source 
- TensorFlow version (use command below):1.7.0
- Python version: 3.5
- Bazel version (if compiling from source): 1.10.0
- GCC/Compiler version (if compiling from source): 5.4.0
- CUDA/cuDNN version:n/a
- GPU model and memory:n/a

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
I freeze a ckpt file into a pb file in python and want to load it in C++. Since the pb file includes tf.contrib.resampler, it fails loading the model saying resampler op is not registered.
I would like to load _resampler_ops.so generated by bazel to fix the bug ( I am not sure am I doing the right thing or not, if not, what should I do to fix this bug?). TF_LoadLibrary("tensorflow-1.7.0/bazel-bin/tensorflow/contrib/resampler/python/ops/_resampler_ops.so
")
the return status is False.
I also tried the path:/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/resampler/python/ops/_resampler_ops.so
the error is the same: load library fails.
Then I tried to rebuild tensorflow using --config=monolithic， and load /usr/local/lib/python3.5/dist-packages/tensorflow/contrib/resampler/python/ops/_resampler_ops.so. 
the error is: segmentation fault; core dumped.

**Describe the expected behavior**
I suppose the TF_LoadLibrary should work and fix the non-registration error.
**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.
string graph_name = argv[1];// name.pb
	Session *session;
	Status status = NewSession(SessionOptions(), &session);
	if (!status.ok())
	{
		cout << "create session wrong: "<< status.ToString() << endl;
		return -1;
	}
	GraphDef graph_def;
	//read model:
	if (!ReadBinaryProto(Env::Default(), graph_name, &graph_def).ok())
	{
		cout << "Read model(pb) failed!" << endl;
		return -1;
	}
TF_Status* status_1 = TF_NewStatus();
	TF_LoadLibrary("tensorflow-1.7.0/bazel-bin/tensorflow/contrib/resampler/python/ops/_resampler_ops.so", status_1);
	if (TF_GetCode(status_1) != TF_OK) {
		cout << "load lib wrong" << endl;
	}
	TF_DeleteStatus(status_1);
	status = session->Create(graph_def);
	if (!status.ok())
	{
		cout << "create graph wrong: " << status.ToString() << endl;
		return -1;
	}
**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by mwsunshine** [comment]
> @mwsunshine Request you to please refer the [link](https://github.com/tensorflow/tensorflow/issues/21251).

I actually have looked into this post, but there are some differences:
1. the poster wants to load his own custom op, while I want to load the built-in op(resampler)
2. TF_LoadLibrary for the poster returns Ok, while returns fails for me.
3. the post haven't figure out how to solve this problem as I know.

**Comment by lfydegithub** [comment]
> _Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template_
> 
> **System information**
> 
> * Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
> * OS Platform and Distribution (e.g., Linux Ubuntu 16.04):16.04
> * Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
> * TensorFlow installed from (source or binary): source
> * TensorFlow version (use command below):1.7.0
> * Python version: 3.5
> * Bazel version (if compiling from source): 1.10.0
> * GCC/Compiler version (if compiling from source): 5.4.0
> * CUDA/cuDNN version:n/a
> * GPU model and memory:n/a
> 
> You can collect some of this information using our environment capture
> [script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
> You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`
> 
> **Describe the current behavior**
> I freeze a ckpt file into a pb file in python and want to load it in C++. Since the pb file includes tf.contrib.resampler, it fails loading the model saying resampler op is not registered.
> I would like to load _resampler_ops.so generated by bazel to fix the bug ( I am not sure am I doing the right thing or not, if not, what should I do to fix this bug?). TF_LoadLibrary("tensorflow-1.7.0/bazel-bin/tensorflow/contrib/resampler/python/ops/_resampler_ops.so
> ")
> the return status is False.
> I also tried the path:/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/resampler/python/ops/_resampler_ops.so
> the error is the same: load library fails.
> Then I tried to rebuild tensorflow using --config=monolithic， and load /usr/local/lib/python3.5/dist-packages/tensorflow/contrib/resampler/python/ops/_resampler_ops.so.
> the error is: segmentation fault; core dumped.
> 
> **Describe the expected behavior**
> I suppose the TF_LoadLibrary should work and fix the non-registration error.
> **Code to reproduce the issue**
> Provide a reproducible test case that is the bare minimum necessary to generate the problem.
> string graph_name = argv[1];// name.pb
> Session _session; Status status = NewSession(SessionOptions(), &session); if (!status.ok()) { cout << "create session wrong: "<< status.ToString() << endl; return -1; } GraphDef graph_def; //read model: if (!ReadBinaryProto(Env::Default(), graph_name, &graph_def).ok()) { cout << "Read model(pb) failed!" << endl; return -1; } TF_Status_ status_1 = TF_NewStatus();
> TF_LoadLibrary("tensorflow-1.7.0/bazel-bin/tensorflow/contrib/resampler/python/ops/_resampler_ops.so", status_1);
> if (TF_GetCode(status_1) != TF_OK) {
> cout << "load lib wrong" << endl;
> }
> TF_DeleteStatus(status_1);
> status = session->Create(graph_def);
> if (!status.ok())
> {
> cout << "create graph wrong: " << status.ToString() << endl;
> return -1;
> }
> **Other info / logs**
> Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

I have the same issue, have you solved it？help me T_T

**Comment by mwsunshine** [comment]
> > _Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template_
> > **System information**
> > 
> > * Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
> > * OS Platform and Distribution (e.g., Linux Ubuntu 16.04):16.04
> > * Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
> > * TensorFlow installed from (source or binary): source
> > * TensorFlow version (use command below):1.7.0
> > * Python version: 3.5
> > * Bazel version (if compiling from source): 1.10.0
> > * GCC/Compiler version (if compiling from source): 5.4.0
> > * CUDA/cuDNN version:n/a
> > * GPU model and memory:n/a
> > 
> > You can collect some of this information using our environment capture
> > [script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
> > You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`
> > **Describe the current behavior**
> > I freeze a ckpt file into a pb file in python and want to load it in C++. Since the pb file includes tf.contrib.resampler, it fails loading the model saying resampler op is not registered.
> > I would like to load _resampler_ops.so generated by bazel to fix the bug ( I am not sure am I doing the right thing or not, if not, what should I do to fix this bug?). TF_LoadLibrary("tensorflow-1.7.0/bazel-bin/tensorflow/contrib/resampler/python/ops/_resampler_ops.so
> > ")
> > the return status is False.
> > I also tried the path:/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/resampler/python/ops/_resampler_ops.so
> > the error is the same: load library fails.
> > Then I tried to rebuild tensorflow using --config=monolithic， and load /usr/local/lib/python3.5/dist-packages/tensorflow/contrib/resampler/python/ops/_resampler_ops.so.
> > the error is: segmentation fault; core dumped.
> > **Describe the expected behavior**
> > I suppose the TF_LoadLibrary should work and fix the non-registration error.
> > **Code to reproduce the issue**
> > Provide a reproducible test case that is the bare minimum necessary to generate the problem.
> > string graph_name = argv[1];// name.pb
> > Session _session; Status status = NewSession(SessionOptions(), &session); if (!status.ok()) { cout << "create session wrong: "<< status.ToString() << endl; return -1; } GraphDef graph_def; //read model: if (!ReadBinaryProto(Env::Default(), graph_name, &graph_def).ok()) { cout << "Read model(pb) failed!" << endl; return -1; } TF_Status_ status_1 = TF_NewStatus();
> > TF_LoadLibrary("tensorflow-1.7.0/bazel-bin/tensorflow/contrib/resampler/python/ops/_resampler_ops.so", status_1);
> > if (TF_GetCode(status_1) != TF_OK) {
> > cout << "load lib wrong" << endl;
> > }
> > TF_DeleteStatus(status_1);
> > status = session->Create(graph_def);
> > if (!status.ok())
> > {
> > cout << "create graph wrong: " << status.ToString() << endl;
> > return -1;
> > }
> > **Other info / logs**
> > Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.
> 
> I have the same issue, have you solved it？help me T_T

sorry I haven't solved it.

**Comment by lfydegithub** [comment]
> > > _Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template_
> > > **System information**
> > > 
> > > * Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
> > > * OS Platform and Distribution (e.g., Linux Ubuntu 16.04):16.04
> > > * Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
> > > * TensorFlow installed from (source or binary): source
> > > * TensorFlow version (use command below):1.7.0
> > > * Python version: 3.5
> > > * Bazel version (if compiling from source): 1.10.0
> > > * GCC/Compiler version (if compiling from source): 5.4.0
> > > * CUDA/cuDNN version:n/a
> > > * GPU model and memory:n/a
> > > 
> > > You can collect some of this information using our environment capture
> > > [script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
> > > You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`
> > > **Describe the current behavior**
> > > I freeze a ckpt file into a pb file in python and want to load it in C++. Since the pb file includes tf.contrib.resampler, it fails loading the model saying resampler op is not registered.
> > > I would like to load _resampler_ops.so generated by bazel to fix the bug ( I am not sure am I doing the right thing or not, if not, what should I do to fix this bug?). TF_LoadLibrary("tensorflow-1.7.0/bazel-bin/tensorflow/contrib/resampler/python/ops/_resampler_ops.so
> > > ")
> > > the return status is False.
> > > I also tried the path:/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/resampler/python/ops/_resampler_ops.so
> > > the error is the same: load library fails.
> > > Then I tried to rebuild tensorflow using --config=monolithic， and load /usr/local/lib/python3.5/dist-packages/tensorflow/contrib/resampler/python/ops/_resampler_ops.so.
> > > the error is: segmentation fault; core dumped.
> > > **Describe the expected behavior**
> > > I suppose the TF_LoadLibrary should work and fix the non-registration error.
> > > **Code to reproduce the issue**
> > > Provide a reproducible test case that is the bare minimum necessary to generate the problem.
> > > string graph_name = argv[1];// name.pb
> > > Session _session; Status status = NewSession(SessionOptions(), &session); if (!status.ok()) { cout << "create session wrong: "<< status.ToString() << endl; return -1; } GraphDef graph_def; //read model: if (!ReadBinaryProto(Env::Default(), graph_name, &graph_def).ok()) { cout << "Read model(pb) failed!" << endl; return -1; } TF_Status_ status_1 = TF_NewStatus();
> > > TF_LoadLibrary("tensorflow-1.7.0/bazel-bin/tensorflow/contrib/resampler/python/ops/_resampler_ops.so", status_1);
> > > if (TF_GetCode(status_1) != TF_OK) {
> > > cout << "load lib wrong" << endl;
> > > }
> > > TF_DeleteStatus(status_1);
> > > status = session->Create(graph_def);
> > > if (!status.ok())
> > > {
> > > cout << "create graph wrong: " << status.ToString() << endl;
> > > return -1;
> > > }
> > > **Other info / logs**
> > > Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.
> > 
> > 
> > I have the same issue, have you solved it？help me T_T
> 
> sorry I haven't solved it.

but i think that issue is very impotent and clear.

**Comment by starstalmax** [comment]
Steps that helped me with this issue:
1. change dlopen flag to RTLD_LAZY | RTLD_GLOBAL  in platform/core/posix/load_library.cc 
2. add of "-rdynamic" compilation flag to my custom  build of executable
There is.

the reason to fail was  _ZTIN10tensorflow8OpKernelE symbol that is undefined in _resampler_ops.so but present in framework libs;
