### ISSUE TITLE
Move the Dockerfiles to ubuntu-18.04

### ISSUE THREAD

**Issue by gautamkmr** [tensorflow/tensorflow#28495]
[Current Dockerfile](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/dockerfiles/dockerfiles/gpu.Dockerfile#L22) we have is based out of 16.04, its better if we can move to 18.04.

The corresponding version of TF Serving is already using 18.04 based ubuntu in their Dockerfile.

**Comment by angersson** [comment]
@tfboyd Do you know if someone is already working on this?

**Comment by tfboyd** [comment]
I have already moved all of my testing to 18.04 based docker files.  I have not issues moving the defaults to 18.04.  We can virtually copy my performance docker files.  https://github.com/tensorflow/benchmarks/tree/master/perfzero/docker

I would approve that without hesitation.
