### ISSUE TITLE
Lack of support for word-embedding on GPU

### ISSUE THREAD

**Issue by smartcat2010** [tensorflow/tensorflow#2849]
Dear experts,

I faced some problems when training model with word-embedding. For simplify the case, I make a helloworld example in this file:
[WE_example.py.txt](https://github.com/tensorflow/tensorflow/files/313712/WE_example.py.txt)

The task is to classify each sentence into 10 classes. Each sentence is length of 30 words. Firstly I use embedding_lookup to get all 30 word-vectors, then I use tf.map_fn(lambda x:tf.reduce_max(x,0), …) to reduce each sentence’s 30 word-vectors into a single “sentence vector”. Then It put this “sentence vector” as DNN's input.

The following are problems & questions:
a.    If I use “tf.train.RMSPropOptimizer” as optimizer, it reports “NotImplementedError”, the details is in the following stderr file:
[RMSPropOptimizer_NotImplemented.stderr.txt](https://github.com/tensorflow/tensorflow/files/313717/RMSPropOptimizer_NotImplemented.stderr.txt)
So, is there a plan to implement RMSPropOptimizer’s support for word-embedding in next release?

b.    Then I replace “tf.train.RMSPropOptimizer” by “tf.train.MomentumOptimizer”.  It works! But the GPU usage is only around 22%. I think putting embedding matrix on host memory (“/cpu:0”) causes data-transfer delay, which may lower down the GPU usage. Then I remove the “with tf.device(‘/cpu:0’)” in line 21(just before definition of word-embedding variable), to put the word-embedding matrix into GPU memory. And run it again. It shows “tensorflow.python.framework.errors.InvalidArgumentError: AttrValue must not have reference type value of float_ref”. 
I put the stdout & stderr as follows:
[MomentumOptimizer_on_GPU.stdout.txt](https://github.com/tensorflow/tensorflow/files/313725/MomentumOptimizer_on_GPU.stdout.txt)
[MomentumOptimizer_on_GPU.stderr.txt](https://github.com/tensorflow/tensorflow/files/313727/MomentumOptimizer_on_GPU.stderr.txt)

It seems that putting word-embedding into GPU memory is not supported by all operators. I also found the same issue in [word2vec_basic.py](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/examples/tutorials/word2vec/word2vec_basic.py) , the line 144 “# Ops and variables pinned to the CPU because of missing GPU implementation” .
And also [word2vec.py](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/models/embedding/word2vec.py) Ln508. It also put word-embedding definition onto /cpu:0.

Word-embedding is very popular in NLP domain. It is usually very large(more than 1GB in internet-level data). So putting it from host memory side to GPU global memory side may save a lot of data-transfer time cost. Is there any plan to fully support it in ALL operators in future release?

c.    Then I replace “tf.train.MomentumOptimizer” by “tf.train.GradientDescentOptimizer”, still removing “/cpu:0”. Then it works! The GPU usage is around 25%~30%. If adding “/cpu:0”, the GPU usage is around 20%~25%.

d.    Because the GPU usage is always below 30%(also in my real code running real data). Is there any way to profiling it to find where is the speed bottleneck?

Sorry for so many questions... But it's really a blocking issue for NLP guys...

**Comment by sherrym** [comment]
For d, you can follow instructions here to get profiling information:

http://stackoverflow.com/questions/37751739/tensorflow-code-optimization-strategy/37774430#37774430

**Comment by prb12** [comment]
There are a number of operators (especially those working on integer types) which are not registered for GPU, and for some fairly complex reasons this is not likely to change in the near future.

Many of the general questions above are better suited for StackOverflow. Please could you ask them there and tag them with the `tensorflow` tag.

**Comment by ravyg** [comment]
Might be helpful:
https://github.com/ravyg/tensorflow/commit/2a83490455f0f02ea05fc447551cacea1c1b8cb6
Supports:
1) Multi-threaded Incremental word2vec
2) Mini-batched skip-gram model GPU support 
3) Works with Tensorflow r0.12 with Checkpoints (New saver in TFr0.12)
