### ISSUE TITLE
cyclic graph is not supported?

### ISSUE THREAD

**Issue by framsc** [tensorflow/tensorflow#28498]
Please correct me if I am wrong.
I am building cyclic graph. However cyclic graph is not supported in tensorflow. 

**System information**
- TensorFlow version: 2.0.0-alpha0
- Are you willing to contribute it (Yes/No): Yes

**Who will benefit with this feature?**
tf is more expressive with cyclic graph. tf.while can be build with cyclic graph with conditional node.  Recursion, such as https://stackoverflow.com/questions/43129225/python-recursive-tensorflow-fibonacci-number-calculation, can be written easily.

**Comment by mayou36** [comment]
Can you may be more specific about the cyclic graph? What would you expect to run (that is not doable with a while_loop)?

**Comment by frams163com** [comment]
For example, Sentiment Analisys with Recursive Neural Network. [https://chainer-colab-notebook.readthedocs.io/en/latest/notebook/official_example/sentiment.html](url)

Recursive Neural Network can be implemented neatly with cyclic graph. Maybe Graph Neural Network too. These models are very hard to implement in current version TensorFlow. 

Is TensorFlow assuming that the Computation Graph is acyclic, especially in the XLA module?

**Comment by kumariko** [comment]
@framsc We are checking to see if you still need help on this issue. Could you please check with latest stable version of TF which is `TF2.7` ? Thanks

**Comment by jonas-eschle** [comment]
> For example, [Sentiment Analisys with Recursive Neural Network](https://chainer-colab-notebook.readthedocs.io/en/latest/notebook/official_example/sentiment.html)
> 
> Recursive Neural Network can be implemented neatly with cyclic graph. Maybe Graph Neural Network too. These models are very hard to implement in current version TensorFlow.
> 
> Is TensorFlow assuming that the Computation Graph is acyclic, especially in the XLA module?

Yes, simply speaking, they are DAGs (as also pointed [out here](https://stackoverflow.com/questions/37571518/tensorflow-graphs-are-tensorflow-graphs-dag-what-happens-in-assignadd-operati)). There is still the possibility to have while loops and similar, that's probably the best bet.

**Comment by mdanatg** [comment]
It is possible to build cyclic TF graphs, but only using low-level (and undocumented) APIs, not via the Python API which is limited to tracing (hence cannot build cyclic graphs).

The nodes in a cycle cannot all be from the same frame (to understand what frames are, have a look at http://download.tensorflow.org/paper/white_paper_tf_control_flow_implementation_2017_11_1.pdf). In other words, at the moment there are only a few ops which can be used to close a cycle. Though one could technically add more (e.g. to support recursion).

As long as the condition above is met, it is technically possible to build cyclic graphs, though that's not well supported at the moment. If you're in Python, one potential avenue is https://www.tensorflow.org/api_docs/python/tf/graph_util/import_graph_def, though we're working on replacing that API with something better supported in TF2.

**Comment by tilakrayal** [comment]
@framsc,
Have you got the chance to have a look at this official document where with the combination of [TensorFlow2.x and Keras](https://www.tensorflow.org/guide/keras/rnn) it's easier to build recurrent networks with both of them, which are basically cyclic graphs. 
https://www.tensorflow.org/api_docs/python/tf/graph_util/import_graph_def

Thank you!
