### ISSUE TITLE
SKFlow - in CPP

### ISSUE THREAD

**Issue by sirinath** [tensorflow/tensorflow#285]
Can you consider developing https://github.com/google/skflow in CPP with binding to other languages including Python than pure Python?

**Comment by girving** [comment]
This looks like an issue for skflow, which is a separate project from tensorflow.

**Comment by sirinath** [comment]
Issue tracker is not enabled in SKFlow.

**Comment by girving** [comment]
Unfortunately it's still a separate project, so we can't track it's issues here.

**Comment by sirinath** [comment]
OK. Sure. I though they were related.
