### ISSUE TITLE
Tensorflow build does not support bazel 0.25???

### ISSUE THREAD

**Issue by zealotpb** [tensorflow/tensorflow#28506]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version:
- Python version:
- Installed using virtualenv? pip? conda?:
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Describe the problem**

**Provide the exact sequence of commands / steps that you executed before running into the problem**

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

Tensorflow source doesn't support bazel 0.25 ??

WARNING: --batch mode is deprecated. Please instead explicitly shut down your Bazel server using the command "bazel shutdown".
You have bazel 0.25.0- (@non-git) installed.
Please downgrade your bazel installation to version 0.24.1 or lower to build TensorFlow! To downgrade: download the installer for the old version (from https://github.com/bazelbuild/bazel/releases) then run the installer.

This seems stupid.

**Comment by wcq19941215** [comment]
when i used bazel 0.24.1, This problem has been solved

**Comment by achandraa** [comment]
@zealotpb : You can try bazel 0.24.1 as suggested by @wcq19941215  and let us know if that helps. Thanks!

**Comment by wdirons** [comment]
I will mention the reason bazel 0.25.0 is not supported yet (because I think that is the question being asked) is that bazel 0.25.0 was only released 9 ago and has not been tested with the tensorflow builds. New bazel versions have a long history of breaking the tensorflow builds, so the recommendation is the build with the versions that have been tested.

The release notes for bazel 0.25.0 list 6 incompatible changes from the 0.24.0 version of bazel, so this new version of bazel could very well break the current TensorFlow build. In time it will be tested and supported.

**Comment by mihaimaruseac** [comment]
Once Bazel 1.0 is released we won't have that many incompatible changes between versions which are released so frequently (there's a bazel 0.25.1 out already). At that point we will be able to support a wider range of versions, at the moment the corresponding line in `./configure.py` uses exactly one Bazel version, the one that we are confident TensorFlow builds with: https://github.com/tensorflow/tensorflow/blob/be23374b52af36e3cad3a6a7a5bd58634c29755c/configure.py#L1391

**Comment by achandraa** [comment]
@zealotpb :  Hope the comments resolved the issue. Kindly let us know. Thanks!

**Comment by mihaimaruseac** [comment]
Note that now TensorFlow builds with bazel from 0.24.1 to 0.25.2:

https://github.com/tensorflow/tensorflow/blob/bcee53ab6f4131b6d5a4061c0ad2f2a48e286b90/configure.py#L1391

I think this can be closed

**Comment by achandraa** [comment]
Closing the issue since it is clarified. Thanks!
