### ISSUE TITLE
Error while converting .pb model into tensorflowlite model

### ISSUE THREAD

**Issue by hoonkai** [tensorflow/tensorflow#28504]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 16.04
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below): 1.14
- Python version: 3.7.3
- Bazel version (if compiling from source): 0.25

**Describe the current behavior**

Converting Deeplab .pb model into TFLite model gives the following error:

```
F tensorflow/lite/toco/model_cmdline_flags.cc:289] Check failed: uses_single_input_flags
```

**Code to reproduce the issue**

```
bazel-bin/tensorflow/lite/toco/toco \
--input_file=flatten.pb \
--input_format=TENSORFLOW_GRAPHDEF \
--output_format=TFLITE \
--output_file="lite.tflite" \
--inference_input_type=FLOAT \
--input_data_type=FLOAT \
--input_arrays=sub_7 \
--output_arrays=ResizeBilinear_3 \
--input_shapes=1,513,513,3
```

**Other info / logs**
Here is the flatten graph `flatten.pb`: https://drive.google.com/open?id=1u6crZ9fBv-Xz88AJcqRyu17p9vFIiNPf

**Comment by haozha111** [comment]
Please try converting '--input_data_type=FLOAT' to '--input_data_types=FLOAT'. Let me know if you have other questions. Thanks.

**Comment by hoonkai** [comment]
@haozha111 Oh! Well spotted. Thanks.
