### ISSUE TITLE
gfile.Copy does not overwrite dest file properly on posix filesystems

### ISSUE THREAD

**Issue by tsawada** [tensorflow/tensorflow#28508]
**Describe the current behavior**
`gfile.Copy(overwrite=True)` does not truncate the destination file before overwriting. That means if the src file is shorter than the dest file, the resulting dest file contains the mix of the two.

**Describe the expected behavior**
`gfile.Copy(overwrite=True)` results in having the exact same content of src file in the dest file.

**Code to reproduce the issue**
```
$ echo 'aaa' > a.txt
$ echo 'bbbbbb' > b.txt
$ python3 -c "from tensorflow import gfile; gfile.Copy('a.txt', 'b.txt', overwrite=True)"
$ cat b.txt
aaa
bb
```

Tested with `pip3 install tensorflow==1.13.1`, python 3.5.2
`b.txt` should have `aaa` as  the content, not `aaa\nbb`.

Ref. https://www.tensorflow.org/api_docs/python/tf/gfile/Copy

**Comment by tsawada** [comment]
CC @Joeper214 who found this issue

**Comment by muddham** [comment]
@tsawada From the above referenced issue, can see a PR was raised, Can you please check if this is resolved after this change got merged.

**Comment by tsawada** [comment]
I built latest master `8a8a109e` and my `o_trunc` branch within `tensorflow/tensorflow:devel` docker container, and confirmed that the problem reproduces on the `master`, and not on `o_trunc`.

**Comment by mihaimaruseac** [comment]
Oh, the PR fixing this hasn't been yet merged (due to my commit causing a merge conflict, sorry about that)
