### ISSUE TITLE
Bazel build error

### ISSUE THREAD

**Issue by Scofield666** [tensorflow/tensorflow#28500]
Follow the instructions listed in [https://www.tensorflow.org/install/source](url), but encountered errors when building 

```
 bazel build --config=opt --config=cuda //tensorflow/tools/pip_package:build_pip_package
```

The errors are:
```
INFO: Analysed target //tensorflow/tools/pip_package:build_pip_package (320 packages loaded).
INFO: Found 1 target...
ERROR: /home/ww/.cache/bazel/_bazel_ww/7b32ff1c0ac316bf710c70621fc9fbba/external/double_conversion/BUILD.bazel:12:1: C++ compilation of rule '@double_conversion//:double-conversion' failed (Exit 1)
/tmp/ccv70MBq.s: Assembler messages:
/tmp/ccv70MBq.s:1068: Error: operand type mismatch for `vxorps'
/tmp/ccv70MBq.s:1076: Error: operand type mismatch for `vxorps'
Target //tensorflow/tools/pip_package:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 9.214s, Critical Path: 0.43s
INFO: 6 processes: 6 local.
FAILED: Build did NOT complete successfully
```
Tensorflow: 1.11
bazel: 0.15.0

**Comment by achandraa** [comment]
Please provide details about what platform you are using (operating system, architecture). Also, did you compile from source or install a binary?

Make sure you also include the exact command if possible to produce the output included in your test case. If you are unclear what to include see the issue template displayed in [the Github new issue template](https://github.com/tensorflow/tensorflow/issues/new/choose).

We ask for this in the issue submission template, because it is really difficult to help without that information. Thanks!

**Comment by Scofield666** [comment]
Actually, the problem above is innocuous.
But I have another question that when I compile the tensorflow1.11 following [instructions](https://www.tensorflow.org/install/install_sources) in conda environment, which environment does this version of tensorflow exist? In this conda environment or in my base environment?

**Comment by Scofield666** [comment]
Here I add my system info for your reference.
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):Linux Mint 17.3 Rosa
- TensorFlow installed from (source or binary): source
- TensorFlow version: 1.11
- Python version: 3.6
- Installed using virtualenv? pip? conda?: conda
- Bazel version (if compiling from source): 0.15.0
- GCC/Compiler version (if compiling from source): 5.4.0
- CUDA/cuDNN version: 9.0/7.5
- GPU model and memory: GeForce GTX 1080ti

**Comment by achandraa** [comment]
@Scofield666 : TensorFlow version will exist in the environment where we installed it. Please let us know if that resolves the issue. Thanks!

**Comment by achandraa** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
