### ISSUE TITLE
GoDoc link error

### ISSUE THREAD

**Issue by theonlydaleking** [tensorflow/tensorflow#28514]
## URL(s) with the issue:

https://github.com/tensorflow/tensorflow/blob/master/tensorflow/go/doc.go

## Description of issue (what needs changing):

The link doesn't work. It strips the trailing `.md` off the URL when it is redirected through `tensorflow.org/code`

### Correct links

it is correct, I think the redirect is broken. for example, if you change 
`https://www.tensorflow.org/code/tensorflow/go/README.md` 
to
`https://www.tensorflow.org/code/tensorflow/go/README.md.md` 

it works.

### Parameters defined

NA

### Returns defined

NA

### Raises listed and defined

NA
### Usage example

NA

### Request visuals, if applicable

NA

### Submit a pull request?

i don't think a PR is the solution here. if there is a better URL tho i'm happy to submit a PR.

**Comment by jvishnuvardhan** [comment]
@theonlydaleking Thanks for finding this link that is not working. I raised a PR to correct the link in the source. Thanks!

**Comment by jvishnuvardhan** [comment]
I am closing this as this was resolved by the following https://github.com/tensorflow/tensorflow/pull/28946. Thanks!
