### ISSUE TITLE
Tensorflow failed to CMake due to Python module not found: tensorflow/contrib/tpu/ops on Windows server 2016

### ISSUE THREAD

**Issue by spacelg** [tensorflow/tensorflow#28517]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
  Windows server 2016
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
  Source
- TensorFlow version:
  [d58b53e](https://github.com/tensorflow/tensorflow/commit/d58b53e19c3d06cea5909c66379d073aea153651) 
- Python version:
Anaconda 4.1.1 (Python 2.7.14 64-bit)
- Installed using virtualenv? pip? conda?:
- Bazel version (if compiling from source):
N/A
- GCC/Compiler version (if compiling from source):
VS2017 15.7.2
- CUDA/cuDNN version:
NVidia CUDA Toolkit 8.0
 NVidia CUDNN 5.1
- GPU model and memory:
N/A

Describe the problem:
Tensorflow failed to CMake due to Python module not found: tensorflow/contrib/tpu/ops. It can be reproduced on latest revision, could you please help take a look at this? Thanks!

Note: 
We did not find the ops in the D:\Tensorflow\src\tensorflow\contrib\tpu path according to the error message. However, the ops path is at D:\Tensorflow\src\tensorflow\contrib\tpu\python\ops.

Repro steps:
1. git clone https://github.com/tensorflow/tensorflow D:\Tensorflow\src
2. pushd D:\Tensorflow
3. set PreferredToolArchitecture=x64
4. set rel=Release
5. set cmake_dir=D:\Tensorflow\src\tensorflow\contrib\cmake
6. set CUDNN_HOME="C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.2\cuda"
7. set PY=C:\ProgramData\Anaconda3
7. set _CL_=/FS
8. mkdir build_x64   && pushd build_x64
9. cmake D:\Tensorflow\src\tensorflow\contrib\cmake -A x64 -DCMAKE_BUILD_TYPE=Release -DPYTHON_EXECUTABLE=C:\ProgramData\Anaconda3\python.exe -DPYTHON_LIBRARIES=C:\ProgramData\Anaconda3\libs\python36.lib -DSWIG_EXECUTABLE=D:\Tensorflow\swigwin-3.0.12\swig.exe -Dtensorflow_BUILD_PYTHON_TESTS=ON -Dtensorflow_BUILD_SHARED_LIB=ON

[log_x64_cmake.log](https://github.com/tensorflow/tensorflow/files/3156985/log_x64_cmake.log)

Error Message:
[executing command] cmake D:\Tensorflow\src\tensorflow\contrib\cmake -A x64 -DCMAKE_BUILD_TYPE=Release -DPYTHON_EXECUTABLE=C:\ProgramData\Anaconda3\python.exe -DPYTHON_LIBRARIES=C:\ProgramData\Anaconda3\libs\python36.lib -DSWIG_EXECUTABLE=D:\Tensorflow\swigwin-3.0.12\swig.exe -Dtensorflow_BUILD_PYTHON_TESTS=ON -Dtensorflow_BUILD_SHARED_LIB=ON 
-- Building for: Visual Studio 15 2017
CMake Warning at CMakeLists.txt:9 (message):
  Your current cmake generator is set to use 32 bit toolset architecture.
  This may cause "compiler out of heap space" errors when building.  Consider
  using the flag -Thost=x64 when running cmake.  Ignore this if you are on
  CMake GUI.
-- Selecting Windows SDK version 10.0.17134.0 to target Windows 10.0.14393.
-- The C compiler identification is MSVC 19.22.27706.96
-- The CXX compiler identification is MSVC 19.22.27706.96
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/VC/Tools/MSVC/14.14.26428/bin/Hostx64/x64/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/VC/Tools/MSVC/14.14.26428/bin/Hostx64/x64/cl.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/VC/Tools/MSVC/14.14.26428/bin/Hostx64/x64/cl.exe
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/VC/Tools/MSVC/14.14.26428/bin/Hostx64/x64/cl.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Performing Test COMPILER_OPT_ARCH_NATIVE_SUPPORTED
-- Performing Test COMPILER_OPT_ARCH_NATIVE_SUPPORTED - Failed
-- Performing Test MSVC_OPENMP_SUPPORT
-- Performing Test MSVC_OPENMP_SUPPORT - Success
-- Performing Test COMPILER_OPT_WIN_CPU_SIMD_SUPPORTED
-- Performing Test COMPILER_OPT_WIN_CPU_SIMD_SUPPORTED - Success
-- D:/Tensorflow/build_x64/abseil_cpp/src/abseil_cpp_build
-- Found PythonInterp: C:/ProgramData/Anaconda3/python.exe (found version "3.6.5") 
-- Found PythonLibs: C:/ProgramData/Anaconda3/libs/python36.lib (found version "3.6.5") 
CMake Error at tf_python.cmake:217 (message):
  Python module not found: tensorflow/contrib/tpu/ops
Call Stack (most recent call first):
  CMakeLists.txt:612 (include)

-- Found SWIG: D:/Tensorflow/swigwin-3.0.12/swig.exe (found version "3.0.12") 
-- Configuring incomplete, errors occurred!
See also "D:/Tensorflow/build_x64/CMakeFiles/CMakeOutput.log".
See also "D:/Tensorflow/build_x64/CMakeFiles/CMakeError.log".
[command took 31 seconds]

**Comment by muddham** [comment]
@spacelg We encourage you to use bazel to build TF, unfortunately we do not support cmake builds for TF. Thanks!

Here are the links to build TF ,
Build from source - https://www.tensorflow.org/install/source_windows
Build from pip - https://www.tensorflow.org/install/pip (select windows in step 1 and 2)

Please let us know how it progresses. Thanks!

**Comment by rounakskm** [comment]
Hello, 
I need to generate a .sln file so that I can work with Visual Studio 2017. Which I dont think we can do using bazel.
Since there is no folder "ops" under the tensorflow/contrib/tpu, I got failure when I configure.

Could you point me to a resource showing how to use Tensorflow C++ API with Visual Studio 2017.
Thank you

**Comment by muddham** [comment]
@rounakskm As your requirement is building Tensorflow C++ API with Visual Studio 2017, request you to please open a separate ticket for this.

**Comment by muddham** [comment]
@spacelg As there is no response from your side , we will close this issue.
@rounakskm Please open a new issue with your requirements so we will take it forward

**Comment by wangxuesong29** [comment]
@rounakskm Are you able to compile with vs 2017 or 2019? For me, I am using vs2019, and it complains about `python module not found: tensorflow/contrib/rnn/kernels`.

**Comment by mousumipaul** [comment]
I am also using vs2019. and I am facing the following errors:
Python proto directory not found: tensorflow/contrib/tpu/profiler
Python module not found: tensorflow/contrib/rnn/ops
Python module not found: tensorflow/contrib/tpu/profiler

I checked those folders. In rnn kernels folder is missing also profiler folder is missing from tpu.
Does any body knows that whether these are moved to somewhere else?

**Comment by ARCog** [comment]
Same here, has someone figured it out?

**Comment by ARCog** [comment]
-- Selecting Windows SDK version 10.0.17763.0 to target Windows 10.0.18362.
-- C:/Users/aurel/source/repos/tensorflow/tensorflow/contrib/cmake/build/abseil_cpp/src/abseil_cpp_build
CMake Error at tf_python.cmake:132 (message):
  Python proto directory not found: tensorflow/contrib/gdr
Call Stack (most recent call first):
  CMakeLists.txt:612 (include)


CMake Error at tf_python.cmake:132 (message):
  Python proto directory not found: tensorflow/contrib/mpi
Call Stack (most recent call first):
  CMakeLists.txt:612 (include)


CMake Error at tf_python.cmake:132 (message):
  Python proto directory not found: tensorflow/contrib/mpi_collectives
Call Stack (most recent call first):
  CMakeLists.txt:612 (include)


CMake Error at tf_python.cmake:132 (message):
  Python proto directory not found: tensorflow/contrib/tpu/profiler
Call Stack (most recent call first):
  CMakeLists.txt:612 (include)


CMake Error at tf_python.cmake:132 (message):
  Python proto directory not found: tensorflow/contrib/verbs
Call Stack (most recent call first):
  CMakeLists.txt:612 (include)


CMake Error at tf_python.cmake:217 (message):
  Python module not found: tensorflow/contrib/kafka/python
Call Stack (most recent call first):
  CMakeLists.txt:612 (include)


CMake Error at tf_python.cmake:217 (message):
  Python module not found: tensorflow/contrib/kafka/python/ops
Call Stack (most recent call first):
  CMakeLists.txt:612 (include)


CMake Error at tf_python.cmake:217 (message):
  Python module not found: tensorflow/contrib/ignite/python
Call Stack (most recent call first):
  CMakeLists.txt:612 (include)


CMake Error at tf_python.cmake:217 (message):
  Python module not found: tensorflow/contrib/ignite/python/ops
Call Stack (most recent call first):
  CMakeLists.txt:612 (include)


CMake Error at tf_python.cmake:217 (message):
  Python module not found: tensorflow/contrib/kinesis/python
Call Stack (most recent call first):
  CMakeLists.txt:612 (include)


CMake Error at tf_python.cmake:217 (message):
  Python module not found: tensorflow/contrib/kinesis/python/ops
Call Stack (most recent call first):
  CMakeLists.txt:612 (include)


CMake Error at tf_python.cmake:217 (message):
  Python module not found: tensorflow/contrib/mpi_collectives/python
Call Stack (most recent call first):
  CMakeLists.txt:612 (include)


CMake Error at tf_python.cmake:217 (message):
  Python module not found: tensorflow/contrib/mpi_collectives/python/ops
Call Stack (most recent call first):
  CMakeLists.txt:612 (include)


CMake Error at tf_python.cmake:217 (message):
  Python module not found: tensorflow/contrib/rnn/kernels
Call Stack (most recent call first):
  CMakeLists.txt:612 (include)


CMake Error at tf_python.cmake:217 (message):
  Python module not found: tensorflow/contrib/rnn/ops
Call Stack (most recent call first):
  CMakeLists.txt:612 (include)


CMake Error at tf_python.cmake:217 (message):
  Python module not found: tensorflow/contrib/tpu/profiler
Call Stack (most recent call first):
  CMakeLists.txt:612 (include)


-- Configuring incomplete, errors occurred!
See also "C:/Users/aurel/source/repos/tensorflow/tensorflow/contrib/cmake/build/CMakeFiles/CMakeOutput.log".
See also "C:/Users/aurel/source/repos/tensorflow/tensorflow/contrib/cmake/build/CMakeFiles/CMakeError.log".

**Comment by sxj731533730** [comment]
when i using vs2017+cmake+tf-r1.15 to making static lib,i encounter a  problem;
CMake Error at tf_python.cmake:132 (message):
  Python proto directory not found: tensorflow/contrib/tpu/profiler
Call Stack (most recent call first):
  CMakeLists.txt:612 (include)
