### ISSUE TITLE
bazel test fails "C++ compilation of rule '@protobuf_archive//:protoc_lib' failed (Exit 2): python.exe failed: error executing command"

### ISSUE THREAD

**Issue by luorixiangyang** [tensorflow/tensorflow#28513]
Env:
OS: windows 10
bazel version: 0.25
tensorflow version:r1.14
python:3.6.4

I use  command to build .whl file is ok:
bazel build --config=opt --config=cuda --define=no_tensorflow_py_deps=true //tensorflow/tools/pip_package:build_pip_package

before action:
I modify third_party/gpus/crosstool/BUILD.tpl.  
cc_toolchain(
    name = "cc-compiler-local",
    all_files = "%{linker_files}",
    compiler_files = ":empty",
    #cpu = "local",    **#remove cpu attribute**
    dwp_files = ":empty",
    linker_files = "%{linker_files}",
    objcopy_files = ":empty",
    strip_files = ":empty",
    # To support linker flags that need to go to the start of command line
    # we need the toolchain to support parameter files. Parameter files are
    # last on the command line and contain all shared libraries to link, so all
    # regular options will be left of them.
    supports_param_files = 1,
    toolchain_identifier = "local_linux",
)

cc_toolchain(
    name = "cc-compiler-darwin",
    all_files = "%{linker_files}",
    compiler_files = ":empty",
    #cpu = "darwin", **#remove cpu attribute**
    dwp_files = ":empty",
    linker_files = "%{linker_files}",
    objcopy_files = ":empty",
    strip_files = ":empty",
    supports_param_files = 0,
    toolchain_identifier = "local_darwin",
)
because there will make a exception to [#7075](https://github.com/bazelbuild/bazel/issues/7075) 
 so remove the cpu attribute. 

**But**   when i run bazel test behind command occur exception:
bazel test --noincompatible_disable_crosstool_file tensorflow/contrib/tensor_forest:model_ops_test

error:
$ bazel test --noincompatible_disable_crosstool_file tensorflow/contrib/tensor_forest:model_ops_test
Starting local Bazel server and connecting to it...
WARNING: The following configs were expanded more than once: [cuda]. For repeatable flags, repeats are counted twice and may lead to unexpected behavior.
Loading:
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
    currently loading: tensorflow/contrib/tensor_forest
Loading: 0 packages loaded
    currently loading: tensorflow/contrib/tensor_forest
Loading: 0 packages loaded
    currently loading: tensorflow/contrib/tensor_forest
Loading: 0 packages loaded
    currently loading: tensorflow/contrib/tensor_forest
Loading: 0 packages loaded
    currently loading: tensorflow/contrib/tensor_forest
Loading: 0 packages loaded
    currently loading: tensorflow/contrib/tensor_forest
Loading: 0 packages loaded
    currently loading: tensorflow/contrib/tensor_forest
Analyzing: target //tensorflow/contrib/tensor_forest:model_ops_test (1 packages loaded, 0 targets configured)
Analyzing: target //tensorflow/contrib/tensor_forest:model_ops_test (10 packages loaded, 34 targets configured)
Analyzing: target //tensorflow/contrib/tensor_forest:model_ops_test (31 packages loaded, 847 targets configured)
Analyzing: target //tensorflow/contrib/tensor_forest:model_ops_test (83 packages loaded, 3373 targets configured)
INFO: Analyzed target //tensorflow/contrib/tensor_forest:model_ops_test (84 packages loaded, 4238 targets configured).
INFO: Found 1 test target...
[0 / 15] [-----] BazelWorkspaceStatusAction stable-status.txt ... (4 actions, 0 running)
[0 / 15] [-----] BazelWorkspaceStatusAction stable-status.txt ... (4 actions, 0 running)
ERROR: C:/users/.../7hwgx76p/external/protobuf_archive/BUILD:277:1: C++ compilation of rule '@protobuf_archive//:protoc_lib' failed (Exit 2): python.exe failed: error executing command
  cd C:/users/.../_bazel_.../7hwgx76p/execroot/org_tensorflow
  SET CUDA_TOOLKIT_PATH=C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v9.0
    SET INCLUDE=C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE;C:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt;C:\Program Files (x86)\Windows Kits\8.1\include\shared;C:\Program Files (x86)\Windows Kits\8.1\include\um;C:\Program Files (x86)\Windows Kits\8.1\include\winrt;
    SET LIB=C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\LIB\amd64;C:\Program Files (x86)\Windows Kits\10\lib\10.0.10240.0\ucrt\x64;C:\Program Files (x86)\Windows Kits\8.1\lib\winv6.3\um\x64;
    SET PATH=C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\amd64;C:\Windows\Microsoft.NET\Framework64\v4.0.30319;C:\Windows\Microsoft.NET\Framework64\;C:\Program Files (x86)\Windows Kits\8.1\bin\x64;C:\Program Files (x86)\Windows Kits\8.1\bin\x86;;C:\Windows\system32
    SET PWD=/proc/self/cwd
    SET PYTHON_BIN_PATH=C:/Python/Anaconda3/python.exe
    SET PYTHON_LIB_PATH=C:/Python/Anaconda3/lib/site-packages
    SET RUNFILES_MANIFEST_ONLY=1
    SET TEMP=C:\Users\...\AppData\Local\Temp
    SET TF_CONFIGURE_IOS=0
    SET TF_CUDA_CLANG=0
    SET TF_CUDA_COMPUTE_CAPABILITIES=6.1
    SET TF_NEED_CUDA=1
    SET TF_NEED_OPENCL_SYCL=0
    SET TF_NEED_ROCM=0
    SET TF_NEED_TENSORRT=0
    SET TMP=C:\Users\...\AppData\Local\Temp
  C:/Python/Anaconda3/python.exe -B external/local_config_cuda/crosstool/windows/msvc_wrapper_for_nvcc.py /nologo /showIncludes /MD /O2 /DNDEBUG -w -DWIN32_LEAN_AND_MEAN /DHAVE_PTHREAD /wd4018 /wd4065 /wd4146 /wd4244 /wd4251 /wd4267 /wd4305 /wd4307 /wd4309 /wd4334 /wd4355 /wd4506 /wd4514 /wd4800 /wd4996 /Fobazel-out/x64_windows-opt/bin/external/protobuf_archive/_objs/protoc_lib/java_doc_comment.o /c external/protobuf_archive/src/google/protobuf/compiler/java/java_doc_comment.cc
Execution platform: @bazel_tools//platforms:host_platform
external/protobuf_archive/src/google/protobuf/compiler/java/java_doc_comment.cc(35): fatal error C1083: Cannot open include file: 'google/protobuf/compiler/java/java_doc_comment.h': No such file or directory
Target //tensorflow/contrib/tensor_forest:model_ops_test failed to build
INFO: Elapsed time: 24.179s, Critical Path: 0.55s
INFO: 0 processes.
FAILED: Build did NOT complete successfully

==============================
how to fix it?

**Comment by devimonica** [comment]
@luorixiangyang  Did you solve this ?

**Comment by luorixiangyang** [comment]
I modify tf_cc_test to cc_test to be ok.
tensorflow/contrib/tensor_forest/BUILD

cc_test(
    name = "model_ops_test",
    size = "small",
    srcs = [
        "kernels/model_ops_test.cc",
        "ops/model_ops.cc",
    ],
    ......
)

**Comment by mihaimaruseac** [comment]
Nit: When posting code, or errors, please wrap multiple lines of that with triple backquotes, so that formatting is nice and output is easy to read.

**Comment by ymodak** [comment]
TF 1.14 supports cuda 10.0. I see that you are using cuda 9.0 can you please switch to cuda 10.0 if this is still an issue. Thanks!
