### ISSUE TITLE
Not found: Op type not registered 'StatefulPartitionedCall'

### ISSUE THREAD

**Issue by fischeru** [tensorflow/tensorflow#28511]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Debian 9.9
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: No
- TensorFlow installed from (source or binary): source
- TensorFlow version: 2.0
- Python version: 3.5.3
- Installed using virtualenv? pip? conda?: - 
- Bazel version (if compiling from source): 0.22
- GCC/Compiler version (if compiling from source): clang from ./configure
- CUDA/cuDNN version: -
- GPU model and memory: -

I built libtensorflow_cc.so and libtensorflow_framework.so from source using bazel, CPU only. Using the resulting libraries I can compile my small c++ project just fine with cmake (requires some work with dependencies and headers).

However when I load a model via LoadSavedModel into a SavedModelBundle I get the following output:

2019-05-07 15:21:15.497043: I tensorflow/cc/saved_model/loader.cc:240] Loading SavedModel with tags: { serve }; from: /.../.../model_dir/autoencoder
2019-05-07 15:21:15.511093: I tensorflow/cc/saved_model/loader.cc:289] SavedModel load for tags { serve }; Status: fail. Took 13982 microseconds.
Not found: Op type not registered 'StatefulPartitionedCall' in binary running on ---. Make sure the Op and Kernel are registered in the binary running in this process.

The model has been trained in python and is a functional keras model. It was exported via keras.experimental.export_saved_model. My guess is that the 'StatefulPartitionedCall' is added by the export.

When I compile my cpp using bazel inside the tensorflow repo everything goes fine. So is the build of  the shared libraries not up to date or am I doing something wrong?

**Comment by allenlavoie** [comment]
I'm somewhat confused about the setup. You compiled with cmake and StatefulPartitionedCall isn't registered, and then at the same git commit you compiled with bazel and it worked?

**Comment by fischeru** [comment]
Both times I compiled with bazel from the same commit. Once the libtensorflow_cc.so with the command 'bazel build  //tensorflow:libtensorflow_cc.so'. The resulting shared library is then used, I don't think it matters in which build system. As far as I understand the library is missing the above mentioned op.

But when I compile my cpp directly with bazel inside the repo everything works out. My cpp is sitting in tensorflow/cc/examples/test.cpp with a BUILD file:
 
load("//tensorflow:tensorflow.bzl", "tf_cc_binary")

tf_cc_binary(
    name = "test_cc",
    srcs = ["test.cpp"],
    deps = [
        "//tensorflow/cc/saved_model:loader",
        "//tensorflow/cc/saved_model:constants",
        "//tensorflow/cc/saved_model:signature_constants",
        "//tensorflow/cc/saved_model:tag_constants",
    ],
)

The test.cpp is basically a one liner:

#include "tensorflow/cc/saved_model/loader.h"
#include "tensorflow/cc/saved_model/tag_constants.h"

int main() {  

    std::string model_path = "/my/path/to/model";
    tensorflow::SavedModelBundle bundle;
    
    auto status = tensorflow::LoadSavedModel(
		tensorflow::SessionOptions(),
		tensorflow::RunOptions(),
		model_path,
		{tensorflow::kSavedModelTagServe},
		&bundle
	);

    std::cout << status << std::endl;

    return 0;
}

I just added deps to the BUILD until it worked, no clue what exactly is necessary. The point is that with this setup the StatefulPartitionedCall exists.

**Comment by fischeru** [comment]
Sorry. Problem was on my side. I moved the resulting .so's which was apparently breaking everything. 

It would be nice to have an explanation what these libraries are doing and needing somewhere in an official guide. 

 I'll close the issue.
