### ISSUE TITLE
tfdbg and tf.data API:  Inconsistency with handling dataset iterators' OutOfRangeError

### ISSUE THREAD

**Issue by CountingClouds** [tensorflow/tensorflow#28527]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):  Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):  Mac OS Mojave v10.14.4
- TensorFlow installed from (source or binary):  Binary (PIP)
- TensorFlow version (use command below):  pip install tensorflow==1.13.1
- Python version:  3.6.2
- CUDA/cuDNN version:  N/A (found bug on CPU version)

print(tf.GIT_VERSION, tf.VERSION):  ==>  'v1.13.0-rc2-5-g6612da8951' 1.13.1

**Describe the current behavior**
Different behavior while using tfbdg responding to catching OutOfRangeError required for iteratively looping on dataset iterators from the tf.data API.  Using tfdbg command  'run -t 100', we get execution as normally expected.  Using tfbdg command 'run -f has_inf_or_nan', we get a cascade of errors.

**Describe the expected behavior**
Running tfbdg with a filter vs running without a filter produces the same code errors when dealing with catching OutOfRangeErrors.

**Code to reproduce the issue**
```
import tensorflow as tf
from tensorflow.python import debug as tf_debug

dataset = tf.data.Dataset.range(3)
iterator = dataset.make_initializable_iterator()
next_element = iterator.get_next()
result = tf.add(next_element, next_element)

with tf.Session() as sess:

  sess = tf_debug.LocalCLIDebugWrapperSession(sess)

  sess.run(iterator.initializer)
  while(True):
    try:
      output = sess.run(result)
      print(output)
    except tf.errors.OutOfRangeError:
      print("End of dataset")
      break
```

**Other info / logs**
FYI: This code snippit is a condensed version of a similarly-structured larger project I am working with; in that larger project (which I am unable to condensely reproduce at this time) the difference between running with tfbdg with a filter produces error 'OutOfRangeError is not iterable' and halts execution whereas tfdbg running without a filter does not and executes normally as intended (ie. slightly different than the discrepency displayed in the code snippet above).

**Comment by ymodak** [comment]
I was able to reproduce the reported behavior in TF 1.13.1

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.

**Comment by CountingClouds** [comment]
It is no longer needed. Thanks,
Daniel ReMine
