### ISSUE TITLE
build_pip_package broken because of 58b53e19c3d06cea5909c66379d073aea153651

### ISSUE THREAD

**Issue by claynerobison** [tensorflow/tensorflow#28526]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution ( Linux Ubuntu 16.04):
- TensorFlow version: master at 66b193faeecda4e6bc7e2767c2d927eecd199a34
- Python version: 2
- Installed using virtualenv? pip? conda?: docker container build
- Bazel version (if compiling from source): 0.24.1
- GCC/Compiler version (if compiling from source): 5.3

**Describe the problem**
build_pip_package is failing: 
```
[0m[91mTarget //tensorflow/tools/pip_package:build_pip_package up-to-date:
  bazel-bin/tensorflow/tools/pip_package/build_pip_package
[0m[91mINFO: Elapsed time: 559.703s, Critical Path: 225.66s
INFO: 12822 processes: 12822 local.
[0m[91mINFO: Build completed successfully, 13671 total actions
[0m[91mINFO: Build completed successfully, 13671 total actions
[0mWed May 8 17:39:25 UTC 2019 : === Preparing sources in dir: /tmp/tmp.kL5rPiZPYi
/tensorflow /tensorflow
/tensorflow
[91mcp: cannot stat 'bazel-bin/tensorflow/tools/pip_package/build_pip_package.runfiles/org_tensorflow/external/local_config_cuda/cuda/cuda/cuda_config.h': No such file or directory
```

**Provide the exact sequence of commands / steps that you executed before running into the problem**

bazel --bazelrc=/root/.bazelrc build -c opt     tensorflow/tools/pip_package:build_pip_package &&     bazel-bin/tensorflow/tools/pip_package/build_pip_package /tmp/whl

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by muddham** [comment]
@claynerobison Request you to please follow the steps mentioned in the [link](https://www.tensorflow.org/install). In the log it says could not find cudaconfig.h so if you want to install TF gpu,Please install relevant components as per the OS and let us know how it progresses. Thanks!

**Comment by mihaimaruseac** [comment]
Also, that commit doesn't seem to exist

**Comment by wdirons** [comment]
This was fixed yesterday by: https://github.com/tensorflow/tensorflow/commit/98bf24deb21e8d0b5c11aedfe655f6f7a5e022ad

The GPU builds were working fine, it was the non gpu builds that could failed finding cuda.h :)

**Comment by muddham** [comment]
@claynerobison Can you please try the fix suggested by wdirons and let us know. Thanks!

**Comment by muddham** [comment]
@claynerobison Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
