### ISSUE TITLE
Python Flow-based Programming UI (graphical designer IDE) similar to FlowHub or Node-red

### ISSUE THREAD

**Issue by developeralgo8888** [tensorflow/tensorflow#28530]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using): 1.13 and 2.0
- Are you willing to contribute it (Yes/No):yes

**Describe the feature and the current behavior/state.**
Python Flow-based Programming UI (graphical designer IDE) similar to NoFLo or others but using Python API  which is more complete . Design the entire model on a canvas by drag-and-drop components on the canvas, then generate the python code and that can be run externally or on the system as a python code. This will make it easy for new users to design new models without coding but benefit from the knowledge 

**Will this change the current api? How?** Not really 

**Who will benefit with this feature?** Tons of new users to Tensorflow AI  without indepth AI low-level programming 

**Any Other info.**

**Comment by ymodak** [comment]
@mihaimaruseac Can you PTAL? Thanks!

**Comment by mihaimaruseac** [comment]
I think it's better to get PTAL from @martinwicke and @dynamicwebpaige though this feature request seems to not have a lot of details

**Comment by martinwicke** [comment]
In this generality, this is not a feature request we will be working on in the foreseeable future. If there's significant interest in something like this from the community, we would encourage organizing a group and coming up with a more detailed proposal. 

I will close this issue.

**Comment by DonaldTsang** [comment]
Here are three examples
- https://github.com/Cloud-CV/Fabrik
- https://github.com/TommyX12/tensorbuilder
- https://github.com/sharmalab/tensorflow-gui 
@developeralgo8888 please take a look and see if you can contribute to these projects
