### ISSUE TITLE
change weights during training

### ISSUE THREAD

**Issue by blablaen** [tensorflow/tensorflow#2854]
Hi,
I train a model and save it to ckpt file.
The next think i want do to is to load the model and change some of his weights. I read the TF API and didn't find any way to do that. Am i missing something? Is there a way to change the weights during training?

thank a lot!

**Comment by sherrym** [comment]
How do you want to change the weights?

**Comment by blablaen** [comment]
Every weight < threshold 
Assign weight = const

**Comment by blablaen** [comment]
http://stackoverflow.com/questions/34220532/how-to-assign-value-to-a-tensorflow-variable

**Comment by sherrym** [comment]
You can do something like:

v = tf.Variable(1.0)
c = tf.constant(2.0)
c2 =  tf.cond(v < c, lambda: tf.constant(3.0), lambda: tf.constant(4.0))
v2 = tf.assign(v, c2)
with tf.Session() as sess:
  sess.run(tf.initialize_all_variables())
  print sess.run(v2)

**Comment by blablaen** [comment]
thanks

**Comment by syyuan1993** [comment]
Is there a way to change some variable into "untrainable" while training?
