### ISSUE TITLE
ssd_mobilenet_v2 model convert tflite errors

### ISSUE THREAD

**Issue by yjfncu** [tensorflow/tensorflow#28547]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- TensorFlow 1.12, python 3.6.5
I use tensorflow object_detection train ssd_mobilenet_v2 model on my own dataset, and this code(https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/running_on_mobile_tensorflowlite.md) convert trained ckpt model to pb, and use this .pb file predict on my dataset, the result is very good. but I use tf.contrib.lite.TFLiteConverte convert this .pb file to .tflite file, outputs some erros :
:RuntimeError: TOCO failed see console for info. Converting unsupporteOp node missing output type attribute,   NonMaxSuppressionV3,  and so on...
this is my convert code:
graph_def_file = 'graph.pb'
input_arrays = ['image_tensor']
output_arrays = ['num_detections', 'detection_boxes', 'detecction_scores', 'detection_class']
converter = tf.contrib.lite.TFFLiteConverter.from_frozen_graph(graph_def_file, input_arrays, output_arrays, input_shapes={'image_tensor':[1,300,300,3]})
#converter.post_training_quantize=True
#converter.default_ranges_stats=(0,6)
tflite_model = converter.convert()
open('detect.tflite', 'wb').write(tflite_model)
does anyone meet thsi problems, thanks a lot

**Comment by muddham** [comment]
@yjfncu Request you to please refer this [link](https://github.com/tensorflow/tensorflow/issues/22106). Please let us know how it progresses. Thanks!

**Comment by muddham** [comment]
@yjfncu Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
