### ISSUE TITLE
AttributeError: module 'tensorflow_hub.tf_v1' has no attribute 'estimator'

### ISSUE THREAD

**Issue by sveah** [tensorflow/tensorflow#28556]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): MacOS Mojave 10.14.3 (18D109)
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: NA
- TensorFlow installed from (source or binary): binary
- TensorFlow version: 1.13.1
- Python version:  3.7.2
- Installed using virtualenv? pip? conda?: virtualenv 
- Bazel version (if compiling from source): NA
- GCC/Compiler version (if compiling from source): NA
- CUDA/cuDNN version: 
- GPU model and memory: Intel Iris Plus Graphics 640 1536 MB

**Describe the problem**

**Provide the exact sequence of commands / steps that you executed before running into the problem**

I just installed Tensorflow-hub and Tensorflow as described in the Tensorflow installation instructions. When I run the following code:

`import tensorflow as tf
import pandas as pd
import tensorflow_hub as hub
import numpy as np
import os, sys
from sklearn.metrics.pairwise import cosine_similarity

# get cosine similairty matrix
def cos_sim(input_vectors):
    similarity = cosine_similarity(input_vectors)
    return similarity

# get topN similar sentences
def get_top_similar(sentence, sentence_list, similarity_matrix, topN):
    # find the index of sentence in list
    index = sentence_list.index(sentence)
    # get the corresponding row in similarity matrix
    similarity_row = np.array(similarity_matrix[index, :])
    # get the indices of top similar
    indices = similarity_row.argsort()[-topN:][::-1]
    return [sentence_list[i] for i in indices]

module_url = "https://tfhub.dev/google/universal-sentence-encoder/2" #@param ["https://tfhub.dev/google/universal-sentence-encoder/2", "https://tfhub.dev/google/universal-sentence-encoder-large/3"]

# Import the Universal Sentence Encoder's TF Hub module
embed = hub.Module(module_url)

# Reduce logging output.
tf.logging.set_verbosity(tf.logging.ERROR)

sentences_list = [
    # phone related
    'My phone is slow',
    'My phone is not good',
    'I need to change my phone. It does not work well',
    'How is your phone?',

    # age related
    'What is your age?',
    'How old are you?',
    'I am 10 years old',

    # weather related
    'It is raining today',
    'Would it be sunny tomorrow?',
    'The summers are here.'
]

with tf.Session() as session:

  session.run([tf.global_variables_initializer(), tf.tables_initializer()])
  sentences_embeddings = session.run(embed(sentences_list))

similarity_matrix = cos_sim(np.array(sentences_embeddings))

sentence = "It is raining today"
top_similar = get_top_similar(sentence, sentences_list, similarity_matrix, 3)

# printing the list using loop
for x in range(len(top_similar)):
    print(top_similar[x])

Then I get the following issue after running it:

Traceback (most recent call last):
  File "/Users/svea/PycharmProjects/untitled/main.py", line 3, in <module>
    import tensorflow_hub as hub
  File "/Users/svea/PycharmProjects/untitled/venv/lib/python3.7/site-packages/tensorflow_hub/__init__.py", line 30, in <module>
    from tensorflow_hub.estimator import LatestModuleExporter
  File "/Users/svea/PycharmProjects/untitled/venv/lib/python3.7/site-packages/tensorflow_hub/estimator.py", line 63, in <module>
    class LatestModuleExporter(tf_v1.estimator.Exporter):
AttributeError: module 'tensorflow_hub.tf_v1' has no attribute 'estimator'

This is my first work with Tensorflow and I could not find any solutions. Thank you for any help!

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by muddham** [comment]
@sveah Please reference this issue [link](https://github.com/tensorflow/hub/issues/289). As this is related to tensorflow hub request you to please post this in TF Hub repo [link](https://github.com/tensorflow/hub/issues/new). Hence this issue will be closed.
