### ISSUE TITLE
Tensorflow build issue on Windows

### ISSUE THREAD

**Issue by starkdm** [tensorflow/tensorflow#28551]
**System information**

- OS Platform and Distribution: Windows 10 1809 Build
- TensorFlow installed from (source or binary): source
- TensorFlow version: latest (get with `git clone`)
- Python version: 2.7.16
- Installed using virtualenv? pip? conda?: pip
- Bazel version (if compiling from source): 0.23.0
- CUDA/cuDNN version: not installed

**Problem**

I need to build Tensorflow on Windows for further use in my C++ VS project. There are appear errors when trying to build from source with Bazel. I tried to follow the installation instructions set out on the official website: https://www.tensorflow.org/install/source_windows

Build command (CPU only):
`bazel build --config=opt //tensorflow/tools/pip_package:build_pip_package`

**Logs**

> Starting local Bazel server and connecting to it...
> ERROR: C:/users/lenovo/desktop/tensorflow/third_party/python_runtime/BUILD:5:1: no such package '@local_config_python//': Traceback (most recent call last):
>         File "C:/users/lenovo/desktop/tensorflow/third_party/py/python_configure.bzl", line 344
>                 _create_local_python_repository(repository_ctx)
>         File "C:/users/lenovo/desktop/tensorflow/third_party/py/python_configure.bzl", line 296, in _create_local_python_repository
>                 _get_numpy_include(repository_ctx, python_bin)
>         File "C:/users/lenovo/desktop/tensorflow/third_party/py/python_configure.bzl", line 276, in _get_numpy_include
>                 _execute(repository_ctx, [python_bin, "-c",..."], <2 more arguments>)
>         File "C:/users/lenovo/desktop/tensorflow/third_party/py/python_configure.bzl", line 56, in _execute
>                 _fail("\n".join([error_msg.strip() if ... ""]))
>         File "C:/users/lenovo/desktop/tensorflow/third_party/py/python_configure.bzl", line 27, in _fail
>                 fail(("%sPython Configuration Error:%...)))
> Python Configuration Error: Problem getting numpy include path.
> Traceback (most recent call last):
>   File "<string>", line 1, in <module>
> ImportError: No module named numpy
> Is numpy installed?
>  and referenced by '//third_party/python_runtime:headers'
> ERROR: Analysis of target '//tensorflow/tools/pip_package:build_pip_package' failed; build aborted: Analysis failed
> INFO: Elapsed time: 31.933s
> INFO: 0 processes.
> FAILED: Build did NOT complete successfully (195 packages loaded, 3695 targets configured)
>     Fetching @grpc; fetching 11s
>     Fetching @llvm; fetching 9s
>     Fetching @boringssl; fetching
>     Fetching @local_config_python;

**Comment by achandraa** [comment]
Please let us know which version of TensorFlow you are using. Also try to check whether numpy is installed or not. If yes which version of numpy is installed and what is the path for the same. Thanks!

**Comment by starkdm** [comment]
> Please let us know which version of TensorFlow you are using. Also try to check whether numpy is installed or not. If yes which version of numpy is installed and what is the path for the same. Thanks!

numpy install path: c:\users\lenovo\appdata\local\programs\python\python37\lib\site-packages (1.16.3 version)

Where in sources I can view library version?

**Comment by achandraa** [comment]
Did you get chance to look on this [issue](https://stackoverflow.com/questions/48547709/tensorflow-1-5-build-failing-missing-path). Let us know if that helps. Thanks!

**Comment by starkdm** [comment]
Use `--action_env` in Bazel command? I tried it.

**Comment by achandraa** [comment]
Did you try following the steps mentioned in [TensorFlow website](https://www.tensorflow.org/install/source_windows).If not, please give it a try and let us know if you are still stuck. Also let us know which TensorFlow version you are using.Thanks!

**Comment by achandraa** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
