### ISSUE TITLE
Building TensorFlow Lite Micro for TARGET=bluepill fails

### ISSUE THREAD

**Issue by jenselofsson** [tensorflow/tensorflow#28555]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 16.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: NA
- TensorFlow installed from (source or binary): Source
- TensorFlow version: b02f70947d
- Python version: 3.6
- Installed using virtualenv? pip? conda?: NA
- Bazel version (if compiling from source): 0.25.1
- GCC/Compiler version (if compiling from source): arm-none-eabi-g++ 7.3.1
- CUDA/cuDNN version: NA
- GPU model and memory: NA

**Describe the problem**
When building Tensorflow Lite Micro for the bluepill target the build fails on the file tensorflow/lite/experimental/micro/kernels/depthwise_conv.cc with the following message:

In file included from ./tensorflow/lite/kernels/internal/common.h:49:0,
        from tensorflow/lite/experimental/micro/kernels/depthwise_conv.cc:18:
tensorflow/lite/experimental/micro/tools/make/downloads/gemmlowp/profiling/instrumentation.h: In constructor 'gemmlowp::Mutex::Mutex()':
tensorflow/lite/experimental/micro/tools/make/downloads/gemmlowp/profiling/instrumentation.h:70:13: error: 'pthread_mutex_init' was not declared in this scope
    Mutex() { pthread_mutex_init(&m, NULL); }
                   ^~~~~~~~~~~~~~~~~~
             pthread_mutex_t
tensorflow/lite/experimental/micro/tools/make/downloads/gemmlowp/profiling/instrumentation.h: In destructor 'gemmlowp::Mutex::~Mutex()':
tensorflow/lite/experimental/micro/tools/make/downloads/gemmlowp/profiling/instrumentation.h:71:14: error: 'pthread_mutex_destroy' was not declared in this scope
   ~Mutex() { pthread_mutex_destroy(&m); }
              ^~~~~~~~~~~~~~~~~~~~~
tensorflow/lite/experimental/micro/tools/make/downloads/gemmlowp/profiling/instrumentation.h:71:14: note: suggested alternative: 'pthread_mutexattr_t'
   ~Mutex() { pthread_mutex_destroy(&m); }
              ^~~~~~~~~~~~~~~~~~~~~
              pthread_mutexattr_t
tensorflow/lite/experimental/micro/tools/make/downloads/gemmlowp/profiling/instrumentation.h: In member function 'void gemmlowp::Mutex::Lock()':
tensorflow/lite/experimental/micro/tools/make/downloads/gemmlowp/profiling/instrumentation.h:73:17: error: 'pthread_mutex_lock' was not declared in this scope
   void Lock() { pthread_mutex_lock(&m); }
                 ^~~~~~~~~~~~~~~~~~
tensorflow/lite/experimental/micro/tools/make/downloads/gemmlowp/profiling/instrumentation.h:73:17: note: suggested alternative: 'pthread_mutex_t'
   void Lock() { pthread_mutex_lock(&m); }
                 ^~~~~~~~~~~~~~~~~~
                 pthread_mutex_t
tensorflow/lite/experimental/micro/tools/make/downloads/gemmlowp/profiling/instrumentation.h: In member function 'void gemmlowp::Mutex::Unlock()':
tensorflow/lite/experimental/micro/tools/make/downloads/gemmlowp/profiling/instrumentation.h:74:19: error: 'pthread_mutex_unlock' was not declared in this scope
   void Unlock() { pthread_mutex_unlock(&m); }
                   ^~~~~~~~~~~~~~~~~~~~
tensorflow/lite/experimental/micro/tools/make/downloads/gemmlowp/profiling/instrumentation.h:74:19: note: suggested alternative: 'pthread_mutex_t'
   void Unlock() { pthread_mutex_unlock(&m); }
                   ^~~~~~~~~~~~~~~~~~~~
                   pthread_mutex_t
tensorflow/lite/experimental/micro/tools/make/Makefile:209: recipe for target 'tensorflow/lite/experimental/micro/tools/make/gen/bluepill_cortex-m3/obj/tensorflow/lite/experimental/micro/kernels/depthwise_conv.o' failed
make: *** [tensorflow/lite/experimental/micro/tools/make/gen/bluepill_cortex-m3/obj/tensorflow/lite/experimental/micro/kernels/depthwise_conv.o] Error 1

**Provide the exact sequence of commands / steps that you executed before running into the problem**
make -f tensorflow/lite/experimental/micro/tools/make/Makefile TARGET=bluepill test

**Any other info / logs**
Reverting commit a52f5b54e8 fixes the build issue.

**Comment by wangtz** [comment]
Hi Jens,

This is because we accidentally leaked profiling code to the TF Lite part and broke TFL micro. It should have been solved by now. Could you try again?

Thanks,

**Comment by jenselofsson** [comment]
> Hi Jens,
> 
> This is because we accidentally leaked profiling code to the TF Lite part and broke TFL micro. It should have been solved by now. Could you try again?
> 
> Thanks,

Hi!

It compiles fine now, although the tests themselves fails with the message included in logs.txt.

[logs.txt](https://github.com/tensorflow/tensorflow/files/3330454/logs.txt)

**Comment by wangtz** [comment]
Eh... WaitUntilLine

Sounds like you need to type enter on you console?

**Comment by petewarden** [comment]
Thanks Jens! Unfortunately there are some timeout issues with the Renode software emulation testing. I'm closing this one since the original issue is solved, but we have a new team who will be helping improve the emulation tests on our side, so hopefully the bluepill testing should become more reliable.
