### ISSUE TITLE
TensorFlow test execution fails with Bazel v0.24.1 on s390x

### ISSUE THREAD

**Issue by Nayana-ibm** [tensorflow/tensorflow#28553]
**System information**
OS Platform and Distribution (e.g., Linux Ubuntu 16.04): **Linux Ubuntu 18.04 s390x**
Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: **NA**
TensorFlow installed from (source or binary): **Source**
TensorFlow version: **current master** 
Python version: **2.7.x**
Installed using virtualenv? pip? conda?: **Building from source**
Bazel version (if compiling from source): **v0.24.1**
GCC/Compiler version (if compiling from source): **7.4.0 (Ubuntu 18.04)**
JAVA : **openjdk version "11.0.2" 2019-01-15**
**OpenJDK Runtime Environment (build 11.0.2+9-Ubuntu-3ubuntu118.04.3)**
CUDA/cuDNN version: **NA**
GPU model and memory: **NA**

**Describe the problem**
Tensorflow test command fails with Bazel v0.24.1 

**Details:** 

I have built Bazel v0.24.1 from source using steps mentioned below: 

```
mkdir bazel && cd bazel
wget https://github.com/bazelbuild/bazel/releases/download/0.24.1/bazel-0.24.1-dist.zip
unzip bazel-0.24.1-dist.zip 
chmod -R +w .
env EXTRA_BAZEL_ARGS="--host_javabase=@local_jdk//:jdk" bash ./compile.sh
export PATH=$PATH:/bazel/output/
```

Then built TensorFlow master :
```
export JAVA_HOME=/usr/lib/jvm/java-11-openjdk-s390x
export PATH=$JAVA_HOME/bin:$PATH
git clone https://github.com/tensorflow/tensorflow
cd tensorflow
export TF_NEED_GCP=0
export TF_NEED_HDFS=0
export TF_NEED_CUDA=0
export TF_NEED_MKL=0
export TF_NEED_OPENCL=0
export TF_NEED_VERBS=0
export TF_NEED_S3=0
export TF_NEED_KAFKA=0
export TF_NEED_AWS=0
export TF_ENABLE_XLA=0
yes "" | ./configure

# Build
bazel --host_jvm_args="-Xms512m" --host_jvm_args="-Xmx1024m" build  --define=tensorflow_mkldnn_contraction_kernel=0 --config=opt //tensorflow/tools/pip_package:build_pip_package

```
Tried to execute tests:

```
# Run bazel test command. Double test timeouts to avoid flakes.
 bazel  --host_jvm_args="-Xms1024m" --host_jvm_args="-Xmx2048m" test \
    --test_tag_filters=-gpu,-benchmark-test -k \
  --test_timeout 300,450,1200,3600 --build_tests_only \
  --test_output=errors -- \
  //tensorflow/... -//tensorflow/compiler/...  
```
  
At this step, test execution failed with below error:
`ERROR: /external/bazel_tools/tools/jdk/BUILD:443:14: Configurable attribute "actual" doesn't match this configuration: Could not find a JDK for host execution environment, please explicitly provide one using `--host_javabase.``

Tried to provide `--host_javabase` to test command however `--host_javabase` option not getting recognized.
`[bazel FATAL src/main/cpp/blaze.cc:1329] Unknown startup option: '--host_javabase=@local_jdk//:jdk'`

Could you please provide some suggestions/inputs on this? How to execute TensorFlow tests?

**Comment by Nayana-ibm** [comment]
@gunan Could you please advice

**Comment by wdirons** [comment]
Hi @Nayana-ibm , For Power, we have started to include `--host_javabase=@bazel_tools//tools/jdk:remote_jdk11` on the command line. Perhaps you can try that.

Because it is a test option (and not a bazel general option) it has to be included after the `test` argument (and not before)

**Comment by muddham** [comment]
@Nayana-ibm Request you to please try the tested build configurations [link](https://www.tensorflow.org/install/source#linux), Please install relevant bazel version as per the TF version . Let us know how it progresses. Thanks!

**Comment by Nayana-ibm** [comment]
@wdirons I tried with `--host_javabase=@bazel_tools//tools/jdk:remote_jdk11` option after test argument however facing same issue: 

` bazel test --host_javabase=@bazel_tools//tools/jdk:remote_jdk11 --test_tag_filters=-gpu,-benchmark-test -k --test_timeout 300,450,1200,3600 --build_tests_only --test_output=errors -- //tensorflow/... -//tensorflow/compiler/...`

`ERROR: /home/external/bazel_tools/tools/jdk/BUILD:460:14: Configurable attribute "actual" doesn't match this configuration: Could not find a JDK for host execution environment, please explicitly provide one using `--host_javabase.``

**Comment by Nayana-ibm** [comment]
@muddham ya..I have checked build configurations link for all latest versions however I need to build TF master on s390x

**Comment by wdirons** [comment]
For Power we are building bazel with the jdk embedded in it. Perhaps that needs to be done for s390 also. @tjakob , can you share how that is done for Power, or do you other ideas to solve this problem?

**Comment by tjakob** [comment]
@Nayana-ibm Can you try `--host_javabase=@local_jdk//:jdk` again? (but after the test command)
This should use the local java installation.
I can give more information on how to embed the jdk into a bazel build, but if the local installation is an option, it is much easier.

**Comment by gunan** [comment]
@meteorcloudy Are you aware of any changes in bazel that would createproblems in detecting java?

**Comment by meteorcloudy** [comment]
@cushon Any idea on this?

**Comment by cushon** [comment]
cc @iirina

**Comment by Nayana-ibm** [comment]
Finally I could build Bazel, TensorFlow and execute TF tests using Bazel 0.24.1 and OpenJDK 11 on s390x Ubuntu 18.04

**Bazel build** :  env **EXTRA_BAZEL_ARGS="--host_javabase=@local_jdk//:jdk"** bash ./compile.sh
**TF build** :  bazel --host_jvm_args="-Xms512m" --host_jvm_args="-Xmx1024m" build  --define=tensorflow_mkldnn_contraction_kernel=0 --config=opt //tensorflow/tools/pip_package:build_pip_package


**TF Test case execution:** 
bazel --host_jvm_args="-Xms1024m" --host_jvm_args="-Xmx2048m" test **--host_javabase="@local_jdk//:jdk"** 
    --test_tag_filters=-gpu,-benchmark-test -k 
  --test_timeout 300,450,1200,3600 --build_tests_only 
  --test_output=errors -- 
  //tensorflow/... -//tensorflow/compiler/... -//tensorflow/lite/... 
  -//tensorflow/core/platform/cloud/... -//tensorflow/contrib/lite/... 
  -//tensorflow/contrib/cloud/... -//tensorflow/java/...

**Comment by Nayana-ibm** [comment]
Further some tests are failing with an error :
```
ERROR: /external/mkl_dnn/BUILD.bazel:101:1: Couldn't build file external/mkl_dnn/_objs/mkldnn_single_threaded/utils.pic.o: C++ compilation of rule '@mkl_dnn//:mkldnn_single_threaded' failed (Exit 1)
external/mkl_dnn/src/common/utils.cpp:22:10: fatal error: xmmintrin.h: No such file or directory
 #include "xmmintrin.h"
          ^~~~~~~~~~~~~
compilation terminated.
```

This is specific to Intel and not working on s390x platform.

Tried with export TF_NEED_MKL=0 but same issue.

This file is included through this[ commit](https://github.com/tensorflow/tensorflow/commit/2f345d145e261213168745a0d3f1aef19282c458) in `tensorflow/core/framework/variant_test.cc`
@ebrevdo : Do you any idea on this? How to skip this on s390x?

**Comment by ebrevdo** [comment]
Parts of the file need to be guarded with some ifdefs.  I can add them next
week.

**Comment by ebrevdo** [comment]
We can probably check the value of EIGEN_VECTORIZE_SSE after importing
eigen headers as a guard.

**Comment by ghltshubh** [comment]
@wdirons I installed bazel from https://public.dhe.ibm.com/ibmdl/export/pub/software/server/ibm-ai/conda/linux-ppc64le/ but I am still getting 
Could not find any cuda.h matching version '' in any subdirectory:
        ''
        'include'
        'include/cuda'
        'include/*-linux-gnu'
        'extras/CUPTI/include'
        'include/cuda/CUPTI'
of:
        '/lib'
        '/opt/ibm/spectrum_mpi/jsm_pmix/lib'
        '/opt/ibm/spectrum_mpi/lib'
        '/opt/ibutils/lib64'
        '/opt/mellanox/hcoll/lib'
        '/opt/mellanox/mxm/lib'
        '/opt/mellanox/sharp/lib'
        '/usr'
        '/usr/lib64'
        '/usr/lib64/mysql'
Asking for detailed CUDA configuration...

Please specify the CUDA SDK version you want to use. [Leave empty to default to CUDA 10]:

**Comment by Nayana-ibm** [comment]
@ebrevdo Is the file guarded with ifdefs?  Could you please point to commit id?

**Comment by gunan** [comment]
ping!
any updates here?
Is this still a problem with newer bazel versions?

**Comment by ebrevdo** [comment]
I believe someone sent a PR to guard.

**Comment by gunan** [comment]
OK, then closing the issue.
Please reopen if this is still not resolved.
