### ISSUE TITLE
tensorflow 1.13.1 and RTX 2080 Ti

### ISSUE THREAD

**Issue by liiutengbo** [tensorflow/tensorflow#28557]
tensorflow 1.13.1 can only  identify the max compute capability is 72, but RTX 2080 ti is 75,how can they are used together ?

**Comment by achandraa** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged//tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there and can provide better support for such issues. Thanks!
