### ISSUE TITLE
TFLite GPU delegate produces very different results

### ISSUE THREAD

**Issue by hoonkai** [tensorflow/tensorflow#28563]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution: Linux Ubuntu 16.04)
- Mobile device if the issue happens on mobile device: LG V30 Android 8.0.0
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below): 0.0.0-gpu-experimental
- Python version: 3.6.5

**Describe the current behavior**

When DeepLab [mobilenetv2_coco_voc_trainaug](http://download.tensorflow.org/models/deeplabv3_mnv2_pascal_train_aug_2018_01_29.tar.gz) is run on a sample image using GPU delegate, the result is significantly different to that generated using CPU. The TFLite model was converted using:

```
tflite_convert \
--output_file= mobilenetv2_coco_voc_trainaug.tflite \
--graph_def_file=$FROZEN_GRAPH \
--input_arrays=sub_7 \
--output_arrays=ResizeBilinear_3 \
--inference_type=FLOAT \
--inference_input_type=FLOAT
```
And, here's the [TFLite model](https://drive.google.com/file/d/1rlD4uBxKegUuWVPBzllFVTQXlJTNb1g0/view?usp=sharing) used.

CPU gives the following (using random colours):

![Screenshot_2019-05-10-13-30-19](https://user-images.githubusercontent.com/14197204/57501503-2438c900-732b-11e9-930d-0f9ba51451fe.png)

GPU delegate gives the following (using random colours):

![Screenshot_2019-05-10-13-29-13](https://user-images.githubusercontent.com/14197204/57501509-2733b980-732b-11e9-824c-bb9c360926ee.png)

Basically, all pixels here are (wrongly) identified to be of the same class (at index 0) because the scores for class 0 are always the highest.

Similarly, if [mobilenetv2_ade20k_train](http://download.tensorflow.org/models/deeplabv3_mnv2_ade20k_train_2018_12_03.tar.gz) is used, the two also give very different results:

CPU gives the following (using random colours):

![Screenshot_2019-05-10-04-10-59](https://user-images.githubusercontent.com/14197204/57530071-c4b5da00-7379-11e9-94f1-2d87282eb9eb.png)

GPU delegate gives the following (using random colours):

![Screenshot_2019-05-10-04-09-41](https://user-images.githubusercontent.com/14197204/57530083-cc757e80-7379-11e9-859e-41804569b851.png)

Here's the [TFLite model](https://drive.google.com/file/d/1RdHs85WPxL1u0TUlPHwCqdY6KOn5XuYe/view?usp=sharing) used.

Indeed, the models use operations like `SPACE_TO_BATCH`, but as far as I know these operations should only affect speed performance.

**Describe the expected behavior**

CPU and GPU delegate should produce the same masks.

**Comment by hoonkai** [comment]
I've added my results for mobilenetv2_coco_voc_trainaug as well.

**Comment by hoonkai** [comment]
Can I ask how the [deeplabv3_257_mv_gpu.tflite](https://storage.googleapis.com/download.tensorflow.org/models/tflite/gpu/deeplabv3_257_mv_gpu.tflite) provided in the guide was converted? Was it done using `tflite_convert` or was there some tweaking to make it work on GPU?

**Comment by impjdi** [comment]
@hoonkai 

If I remember correctly, the only thing we changed for that model was 513x513 input image to 257x257 because the network wouldn't fit into the GPU memory.  The rest should be the same.  I think one of the engineers just ran toco on the frozen graph def.

**Comment by impjdi** [comment]
@hoonkai 

I also downloaded your model, and you're correct that `SPACE_TO_BATCH_ND` etc. are not supported, but should run, in theory, fine.  But because of the residual connections, e.g. `decoder/ResizeBilinear_1`, I'm not 100% sure whether it will work.  We often only run 100% mobile GPU-compatible graphs, and haven't done extensive testing for partially runnable graphs.

**Comment by hoonkai** [comment]
@impjdi Right. So, do you think `toco` was run on the frozen graph def provided with [mobilenetv2_coco_voc_trainaug ](http://download.tensorflow.org/models/deeplabv3_mnv2_pascal_train_aug_2018_01_29.tar.gz)? If so, wouldn't that produce the same model as running `tflite_convert`? For some reason, the one I generated contains `SPACE_TO_BATCH_ND`, etc. but the one provided in the guide doesn't.

**Comment by hoonkai** [comment]
@impjdi  You mentioned the residual connections may cause the failure. Do you know why GPU delegates don't handle residual connections in particular?

**Comment by lwu025** [comment]
This there any progress on this issue? I face similar problem and I wish to know how to convert mobilenetv2_coco_voc_trainaug model to the tflite version without BATCH_TO_SPACE_ND (like the  deeplabv3_257_mv_gpu.tflite )

**Comment by impjdi** [comment]
@hoonkai 

Sorry, I didn't get time to investigate this.  I'm a bit swamped with CVPR preparation for the last 2-3 weeks.  I might have more cycles after CVPR.

I am not certain how our team obtained the deeplab v3 model.  I requested at one point, and I was given the TFLite model directly.  Then it didn't run because 513x513 was too huge for GPU memory; custom modification was performed to scale it down to 257x257, but I was not directly involved.  Do you want me to chase down the person and ask how the TFLite model file was created?

**Comment by lwu025** [comment]
@impjdi 
I wish you can chase down. This issue is related to my issue #29618 and #29509

**Comment by hoonkai** [comment]
@hoonkai Thanks for picking this up again. Can I ask why you think residual connections may not work properly on GPU?

**Comment by lwu025** [comment]
@hoonkai 
Hi, I figured out a brute method to get rid of BATCH_TO_SPACE:
1. open your <path_to_your_tensorflow>/tensorflow/python/ops/nn_impl.py
2. At line 514: add one more parameter "dilations=[1, rate[0], rate[1], 1],"
3. At line 520: modify "dilation_rate=rate," to "dilation_rate=[1, 1],"
4. rerun your deeplab script (for example: local_test_mobilenetv2.sh), change checkpoint and crop size according to your requirement. For me, size = 257, check_point = http://download.tensorflow.org/models/deeplabv3_mnv2_dm05_pascal_trainaug_2018_10_01.tar.gz.
5. convert .pb to .tflite, input layer = sub_2, output layer = ResizeBilinear_2
6. You will get a model with structure identical to deeplabv3_257_mv_gpu.tflite!!

**Comment by jsolves** [comment]
Any progress deleting all those awful BATCH_TO_SPACE_ND layers that makes converted tfmodels run like a turtle...?

**Comment by lwu025** [comment]
> Any progress deleting all those awful BATCH_TO_SPACE_ND layers that makes converted tflite files run like a turtle...?

My method works good for me. I removed all BATCH_TO_SPACE_ND and it gives me correct result.

**Comment by jsolves** [comment]
Sure, but my 514 and 520 lines are comments... xD

**Comment by lwu025** [comment]
> Sure, but my 514 and 520 lines are comments... xD

My version is 1.13.0rc0
I hope this screenshot can help find the piece of code.
Line 514 is new and Line 520 is modified
![Uploading Screenshot from 2019-07-18 10-03-07.png…]()

**Comment by jsolves** [comment]
Hello, I managed to change those lines in nn_impl.py and now my converted model has no batchtospace stuff. Thank you very much.
 
 Now the only difference between my converted model and the oficial one is the input quantization. Mine is 0 <= q <= 255 while oficial's is -1 ≤ q ≤ 0.9921875. I have no luck finding something to modify this, Does anyone know how to "magically" change this?

**Comment by jsolves** [comment]
I have been trying my .tflite because it infered bad results, but then I realized that the previous generated .pb does that, too. So It seems that the first conversion to .pb isn't working...
