### ISSUE TITLE
tensorflow 2.0 from_generator

### ISSUE THREAD

**Issue by celinew1221** [tensorflow/tensorflow#28578]
While using from_generator, tensorflow is giving me this message. Is there a way to turn this off?

> W0509 19:06:38.972821 139709270456064 deprecation.py:323] From /home/celine/.environments/tensorflow_new/lib/python3.5/site-packages/tensorflow/python/data/ops/dataset_ops.py:410: py_func (from tensorflow.python.ops.script_ops) is deprecated and will be removed in a future version.
> Instructions for updating:
> tf.py_func is deprecated in TF V2. Instead, there are two
>     options available in V2.
>     - tf.py_function takes a python function which manipulates tf eager
>     tensors instead of numpy arrays. It's easy to convert a tf eager tensor to
>     an ndarray (just call tensor.numpy()) but having access to eager tensors
>     means `tf.py_function`s can use accelerators such as GPUs as well as
>     being differentiable using a gradient tape.
>     - tf.numpy_function maintains the semantics of the deprecated tf.py_func
>     (it is not differentiable, and manipulates numpy arrays). It drops the
>     stateful argument making all functions stateful.
>

**Comment by achandraa** [comment]
Did you get chance to have a look on #26348. Let us know if that solves the problem. Thanks!

**Comment by celinew1221** [comment]
The problem is gone by using the following code in tensorflow 2.0:
```
tflogger = tf.get_logger()
tflogger.setLevel('ERROR')
```

**Comment by achandraa** [comment]
@celinew1221 : Good to know it solved your issue.

**Comment by achandraa** [comment]
Are you satisfied with the resolution of your issue?<br> [Yes](https://docs.google.com/forms/d/e/1FAIpQLSfaP12TRhd9xSxjXZjcZFNXPGk4kc1-qMdv3gc6bEP90vY1ew/viewform?entry.85265664=Yes&entry.2137816233=28578)<br> [No](https://docs.google.com/forms/d/e/1FAIpQLSfaP12TRhd9xSxjXZjcZFNXPGk4kc1-qMdv3gc6bEP90vY1ew/viewform?entry.85265664=No&entry.2137816233=28578)
