### ISSUE TITLE
tensorflow 2.0 giving tf.print message while using rejection_resample

### ISSUE THREAD

**Issue by celinew1221** [tensorflow/tensorflow#28577]
I am using rejection_resample from tensorflow v2.0, this is giving me the following message. While this is no big deal, it is kind of annoying. I don't think this is an issue on my end, I didn't use any tf.print. It will be great to turn this off. Thank you.

> 
> Instructions for updating:
> Use tf.print instead of tf.Print. Note that tf.print returns a no-output operator that directly prints the output. Outside of defuns or eager mode, this operator will not be executed unless it is directly specified in session.run or used as a control dependency for other operators. This is only a concern in graph mode. Below is an example of how to ensure tf.print executes in graph mode:
> ```python
>     sess = tf.Session()
>     with sess.as_default():
>         tensor = tf.range(10)
>         print_op = tf.print(tensor)
>         with tf.control_dependencies([print_op]):
>           out = tf.add(tensor, tensor)
>         sess.run(out)
>     ```
> Additionally, to use tf.print in python 2.7, users must make sure to import
> the following:
> 
>   `from __future__ import print_function`
>

**Comment by muddham** [comment]
@celinew1221 I ran the code provided in TF GPU 2.0.0-alpha0. Have not received any error.
![image](https://user-images.githubusercontent.com/48215502/57530948-fe74e980-7355-11e9-8ad6-736c082a5c01.png). Please check and let us know.

**Comment by celinew1221** [comment]
The code provided was in the error message itself. I am using rejection sampling function, and that produces this message. But I managed to get rid of it with the following code:

```
tflogger = tf.get_logger()
tflogger.setLevel('ERROR')
```
