### ISSUE TITLE
[XLA] AlgebraicSimplifierTest::DotContractingReorder_NoChangeInContractingDimsOrder is broken (reads out-of-bounds in an array)

### ISSUE THREAD

**Issue by jlebar** [tensorflow/tensorflow#28579]
https://github.com/tensorflow/tensorflow/commit/3eb4a44f0536888881d49df60c18f528b7122d25 fixed a bug in `AlgebraicSimplifierTest::DotContractingReorder_NoChangeInContractingDimsOrder` that was causing it not to run.

With that bug fixed, the test now crashes XLA!  STR, get rid of "DISABLED_" from the front of the test and run it.  It should crash with an out-of-bounds array access in `ComposePermutation`.

@BinFan would you be willing to have a look at this?  I can't assign the bug to you because you're not in the github TF organization, so I've assigned it to myself.

**Comment by BinFan** [comment]
Sure. I'll take a look.

**Comment by jlebar** [comment]
I believe this was fixed by the PR above.
