### ISSUE TITLE
Build TensorFlow Lite for ARM64 boards failed

### ISSUE THREAD

**Issue by zhang-ray** [tensorflow/tensorflow#28589]
**System information**
- Linux Ubuntu 16.04
- TensorFlow installed from (source or binary): source 
- TensorFlow version: r1.14

**Describe the problem**
I got build error: undefined reference to `NnApiImplementation()'

**Provide the exact sequence of commands / steps that you executed before running into the problem**
I followed https://www.tensorflow.org/lite/guide/build_arm64 . Here are the exact sequence of commands:
`git clone https://github.com/tensorflow/tensorflow && cd tensorflow`
`git checkout -b r1.14 origin/r1.14`
`./tensorflow/lite/tools/make/download_dependencies.sh` `./tensorflow/lite/tools/make/build_aarch64_lib.sh`

**Any other info / logs**
I got these error info when I execute `build_aarch64_lib.sh` :

/home/administrator/tensorflow/tensorflow/lite/tools/make/gen/aarch64_armv8-a/lib/libtensorflow-lite.a(nnapi_delegate.o): In function `tflite::NNAPIAllocation::~NNAPIAllocation()':
nnapi_delegate.cc:(.text+0x28): undefined reference to `NnApiImplementation()'
/home/administrator/tensorflow/tensorflow/lite/tools/make/gen/aarch64_armv8-a/lib/libtensorflow-lite.a(nnapi_delegate.o): In function `tflite::NNAPIAllocation::NNAPIAllocation(char const*, tflite::ErrorReporter*)':
nnapi_delegate.cc:(.text+0x1a4): undefined reference to `NnApiImplementation()'
/home/administrator/tensorflow/tensorflow/lite/tools/make/gen/aarch64_armv8-a/lib/libtensorflow-lite.a(nnapi_delegate.o): In function `tflite::NNAPIDelegate::~NNAPIDelegate()':
nnapi_delegate.cc:(.text+0x218): undefined reference to `NnApiImplementation()'
nnapi_delegate.cc:(.text+0x234): undefined reference to `NnApiImplementation()'
/home/administrator/tensorflow/tensorflow/lite/tools/make/gen/aarch64_armv8-a/lib/libtensorflow-lite.a(nnapi_delegate.o): In function `tflite::addTensorOperands(tflite::Subgraph*, ANeuralNetworksModel*, unsigned int*, std::vector<long, std::allocator<long> >*)':
nnapi_delegate.cc:(.text+0x2b8): undefined reference to `NnApiImplementation()'
/home/administrator/tensorflow/tensorflow/lite/tools/make/gen/aarch64_armv8-a/lib/libtensorflow-lite.a(nnapi_delegate.o):nnapi_delegate.cc:(.text+0x578): more undefined references to `NnApiImplementation()' follow
collect2: error: ld returned 1 exit status
tensorflow/lite/tools/make/Makefile:227: recipe for target '/home/administrator/tensorflow/tensorflow/lite/tools/make/gen/aarch64_armv8-a/bin/minimal' failed
make: *** [/home/administrator/tensorflow/tensorflow/lite/tools/make/gen/aarch64_armv8-a/bin/minimal] Error 1
make: *** Waiting for unfinished jobs....

**Comment by jdduke** [comment]
This should be fixed on head. Note that the 1.14 branch is in a state of flux and will be updated with the fix. Please re-open if you find otherwise (testing against head).
