### ISSUE TITLE
Keras code in colab from tensorflow.org is not showing tensorflow version details

### ISSUE THREAD

**Issue by muddham** [tensorflow/tensorflow#28596]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version (use command below):
- Python version:
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**

**Describe the expected behavior**

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by muddham** [comment]
Able to reproduce the issue . Please see the attached image.
![image](https://user-images.githubusercontent.com/48215502/57529375-61648180-7352-11e9-8081-a9a452e73238.png)

**Comment by jvishnuvardhan** [comment]
@muddham I don't see any issue. Please check the attached [GitHub gist](https://colab.sandbox.google.com/gist/jvishnuvardhan/afd188f0434e01f55b7aac61667e0d08/keras.ipynb). Thanks!

**Comment by kaaanishk** [comment]
Seems to be working correctly for me. @muddham I'm unable to reproduce the error from the given [link](https://colab.research.google.com/github/tensorflow/docs/blob/master/site/en/guide/keras.ipynb#scrollTo=7e1LPcXx0gR6). Are you still facing the problem?
![Screen Shot 2019-05-12 at 6 34 11 PM](https://user-images.githubusercontent.com/46882326/57582614-a28c9b00-74e4-11e9-946b-175066983dde.png)
