### ISSUE TITLE
tensorflow 2.0 rejection resample printing proportion of examples ... message

### ISSUE THREAD

**Issue by celinew1221** [tensorflow/tensorflow#28597]
I am using tensorflow 2.0 CUDA 10.

The message comes from rejection sampling. I receive multiple lines similar to this:
> Proportion of examples rejected by sampler is high: [0.935080409][0.935080409 0.0649196059][0 1]

Turn the logging level to ERROR does not help. Is there a way to turn this off or direct it to a disk file so that it won't mess up my other progress messages? You can use the following snippet to reproduce:

```
import tensorflow as tf
import numpy as np
# everything is based on tensorflow 2.0

# this is important or rejection sample won't work
# I set this here so that all random process keeps the same order but you can
# also set it at rejection_resample function
tf.random.set_seed(2342)


def map2label(sample):
    return tf.cast(tf.math.equal(sample, 2), tf.int32)

np_data = np.array([0,2,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2])
target_dist = [0.5, 0.5]
init_dist = [(np_data.shape[0]-3)/np_data.shape[0], 3/np_data.shape[0]]

dataset = tf.data.Dataset.from_tensor_slices(np_data)
rej = tf.data.experimental.rejection_resample(map2label, target_dist, init_dist, 20)
dataset = dataset.apply(rej)

bucket_counts = [0, 0]
for i in range(100):
    for data in dataset:
        class_id, data_content = data
        bucket_counts[class_id.numpy()] += 1
print("This is your target_dist", target_dist, "This is your initial distribution", init_dist)
print("This is your result counts", bucket_counts,
      "This is your final dist", bucket_counts[0] / np.sum(bucket_counts), bucket_counts[1] / np.sum(bucket_counts))
```

**Comment by gadagashwini** [comment]
@celinew1221 Could you provide more details about the issue and context? Please provide as many details as possible to resolve the issue faster. Thanks!

**Comment by celinew1221** [comment]
I’m confused. What other information do you need? The sample code is what I used to undersample data - using rejection sampling. However, with a highly unbalanced dataset, like the one I used here, it will spit out the information I quoted above, which is every annoying when I have other debug/info printed to screen.

**Comment by jvishnuvardhan** [comment]
@celinew1221 Can you try 
```
import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3' 
#0 = all messages are logged (default behavior)
#1 = INFO messages are not printed
#2 = INFO and WARNING messages are not printed
#3 = INFO, WARNING, and ERROR messages are not printed
```

This is not Build/Installation or Bug/Performance issue. Please post this kind of support questions at [Stackoverflow](https://stackoverflow.com/questions/tagged/tensorflow). There is a big community to support and learn from your questions. GitHub is mainly for addressing bugs in installation and performance. Thanks!
