### ISSUE TITLE
python3.exe crush after running python script with tensorflow

### ISSUE THREAD

**Issue by abdou31** [tensorflow/tensorflow#28590]
Hello ,
I'm setting and cloned the this project :
https://github.com/yinguobing/cnn-facial-landmark
But when i run: 

> python3 landmark.py 

I get this bug : 

![ce](https://user-images.githubusercontent.com/19480228/57519953-c8ffda00-731c-11e9-9e8e-21c9db0e0387.PNG)

when i debug , i get this : 

![des](https://user-images.githubusercontent.com/19480228/57520070-13815680-731d-11e9-8b58-73e93587da41.PNG)

Note : I test tensorflow with code mentionned in the readme and it work perfectly . 

![image](https://user-images.githubusercontent.com/19480228/57520025-fa78a580-731c-11e9-8432-a4171c6b956a.png)

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform: Windows 10 x64
- TensorFlow installed from (binary):
- TensorFlow version (1.13)
- Python version:(3.6)
- CUDA/cuDNN version: 10.0/7.5
- GPU model and memory: Nvidia Geforce 840m 4.00 Go

How can i solve this error ?

**Comment by achandraa** [comment]
Can you give us some more info on the error you are facing ? Could not able to read the actual error message. Thanks!

**Comment by abdou31** [comment]
I think that the error will gone , i missed some tensorflow files ( train.record , test.record , valid.record )  that should be generated by Tensorflow , I follow this tuto :
+ https://github.com/faust690226/cnn-facial-landmark-tutorial

**Comment by achandraa** [comment]
Good to hear that. I will be closing this issue since it is resolved. Thanks!
