### ISSUE TITLE
Spread Sheet Abstraction in TensorBoard

### ISSUE THREAD

**Issue by sirinath** [tensorflow/tensorflow#286]
Spreadsheet abstraction is more convenient and familiar. Is it possible to add flow based Spreadsheet like modelling capabilities:

 - http://www.ankhor.com/
 - https://www.dadisp.com/
 - http://matrex.sourceforge.net/
 - https://www.quantrix.com/en/

Here the inputs and outputs on each node in the Dataflow Graph are abstracted as cells to which you can link and perform computations which forms a sub graph but which is rendered as a spreadsheet.

**Comment by sirinath** [comment]
Also make TensorBoard an embeddable UI editor which you can use in parts of other Web UIs.

**Comment by bhack** [comment]
Do you think at something related to [FBP](http://www.jpaulmorrison.com/fbp/software.html)?

**Comment by sirinath** [comment]
It has some resemblance. In CS there is hardly anything new but just old wine in new bottles.

Some other similar projects:

 - http://noflojs.org/
 - http://www.pothosware.com/
 - http://orcc.sourceforge.net/
 - etc.

But in this case I am looking for something in the like of Flow Sheets (http://www.ankhor.com/).

**Comment by bhack** [comment]
Noflo was analyzed by the same author at http://www.jpaulmorrison.com/fbp/noflo.html

**Comment by sirinath** [comment]
OK

**Comment by girving** [comment]
This is out of scope for tensorboard, which is a visualization platform rather than a graph generation platform.  A separate project building on tensorflow might be interesting, though!
