### ISSUE TITLE
[Installation problem] ImportError: No module named google.protobuf

### ISSUE THREAD

**Issue by GoMapur** [tensorflow/tensorflow#2860]
Installation problem
### Environment info
Operating System: Ubuntu 14.04

Installed version of CUDA and cuDNN: None
(please attach the output of `ls -l /path/to/cuda/lib/libcud*`):

If installed from binary pip package, provide:

### Which pip package you installed.
- adium-theme-ubuntu (0.3.4)
- apt-xapian-index (0.45)
- argparse (1.2.1)
- auxlib (0.0.39)
- chardet (2.0.1)
- colorama (0.2.5)
- command-not-found (0.3)
- conda (4.0.8)
- configobj (4.7.2)
- Cython (0.20.1post0)
- debtagshw (0.1)
- decorator (3.4.0)
- defer (1.0.6)
- deluge (1.3.6)
- dirspec (13.10)
- dnspython (1.11.1)
- duplicity (0.6.23)
- enum34 (1.1.6)
- gyp (0.1)
- h5py (2.2.1)
- html5lib (0.999)
- httplib2 (0.8)
- ipython (1.2.1)
- Jinja2 (2.7.2)
- Landscape-Client (14.12)
- lockfile (0.8)
- lxml (3.3.3)
- Mako (0.9.1)
- MarkupSafe (0.18)
- matplotlib (1.3.1)
- mercurial (2.8.2)
- nose (1.3.1)
- numexpr (2.2.2)
- numpy (1.11.0)
- oauthlib (0.6.1)
- oneconf (0.3.7.14.04.1)
- PAM (0.4.2)
- pexpect (3.1)
- Pillow (2.3.0)
- pip (1.5.4)
- piston-mini-client (0.7.5)
- pomodoro-indicator (0.1.0)
- powerline-status (2.2.dev9999-git.841c25f6b61e1632d7f2343289c52698bcb9b805)
- protobuf (3.0.0b2)
- psutil (3.2.2)
- pycosat (0.6.1)
- pycrypto (2.6.1)
- pycups (1.9.66)
- pycurl (7.19.3)
- pygame (1.9.1release)
- pygobject (3.12.0)
- pyne (0.5.0-rc1)
- pyOpenSSL (0.13)
- pyparsing (2.0.1)
- pyrtlsdr (0.2.0)
- pyserial (2.6)
- pysmbc (1.0.14.1)
- PyTAPS (1.4)
- python-apt (0.9.3.5ubuntu2)
- python-dateutil (1.5)
- python-debian (0.1.21-nmu2ubuntu2)
- python-libtorrent (0.16.13)
- pytz (2012c)
- pyxdg (0.25)
- PyYAML (3.11)
- reportlab (3.0)
- requests (2.2.1)
- scipy (0.13.3)
- sessioninstaller (0.0.0)
- setuptools (23.0.0)
- simplegeneric (0.8.1)
- six (1.10.0)
- software-center-aptd-plugins (0.0.0)
- sympy (0.7.4.1)
- system-service (0.1.6)
- tables (3.1.1)
- tensorflow (0.9.0rc0)
- Twisted-Core (13.2.0)
- Twisted-Web (13.2.0)
- unity-launcher-folders (14.09.4)
- unity-lens-photos (1.0)
- urllib3 (1.7.1)
- vboxapi (1.0)
- wheel (0.29.0)
- wsgiref (0.1.2)
- xdiagnose (3.6.3build2)
- zope.interface (4.0.5)

### The output from `python -c "import tensorflow; print(tensorflow.__version__)"`.

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/__init__.py", line 23, in <module>
    from tensorflow.python import *
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/__init__.py", line 58, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/__init__.py", line 52, in <module>
    from tensorflow.core.framework.graph_pb2 import *
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/core/framework/graph_pb2.py", line 6, in <module>
    from google.protobuf import descriptor as _descriptor
ImportError: No module named google.protobuf

Error importing tensorflow.  Unless you are using bazel,
you should not try to import tensorflow from its source directory;
please exit the tensorflow source tree, and relaunch your python interpreter
from there.

If installed from sources, provide the commit hash:

### Steps to reproduce
I followed instructed steps to install tensorflow, however, my python seems to miss the googlebuf package. Weirdly, it does recognize tensorflow package under the same dist-packages folder.

### What have you tried?
I tried to modify the PYTHONPATH and reinstall tensorflow and pip several times.

### Logs or other output that would be helpful
(If logs are large, please upload as attachment).
 ~  python
Python 2.7.11 |Anaconda 4.0.0 (64-bit)| (default, Dec  6 2015, 18:08:32) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://anaconda.org
>>> import tensorflow
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/__init__.py", line 23, in <module>
    from tensorflow.python import *
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/__init__.py", line 58, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/__init__.py", line 52, in <module>
    from tensorflow.core.framework.graph_pb2 import *
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/core/framework/graph_pb2.py", line 6, in <module>
    from google.protobuf import descriptor as _descriptor
ImportError: No module named google.protobuf

Error importing tensorflow.  Unless you are using bazel,
you should not try to import tensorflow from its source directory;
please exit the tensorflow source tree, and relaunch your python interpreter
from there.
>>>

**Comment by sherrym** [comment]
Could you try running:

sudo pip install protobuf

and retry your command?

**Comment by GoMapur** [comment]
Hi, I tried and here is the response.

 mapur@mapur-ThinkPad-T540p  ~  sudo pip install protobuf
Requirement already satisfied (use --upgrade to upgrade): protobuf in /usr/local/lib/python2.7/dist-packages
Cleaning up...
 mapur@mapur-ThinkPad-T540p  ~  python 
Python 2.7.11 |Anaconda 4.0.0 (64-bit)| (default, Dec  6 2015, 18:08:32) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://anaconda.org
>>> import tensorflow
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/__init__.py", line 23, in <module>
    from tensorflow.python import *
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/__init__.py", line 58, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/__init__.py", line 52, in <module>
    from tensorflow.core.framework.graph_pb2 import *
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/core/framework/graph_pb2.py", line 6, in <module>
    from google.protobuf import descriptor as _descriptor
ImportError: No module named google.protobuf


Error importing tensorflow.  Unless you are using bazel,
you should not try to import tensorflow from its source directory;
please exit the tensorflow source tree, and relaunch your python interpreter
from there.
>>>

**Comment by GoMapur** [comment]
I believe this is caused by a conda issue that it wont work if there's a library outside conda but conda neither can use it nor can uninstall it.

**Comment by concretevitamin** [comment]
Closing since this seems to have been identified and/or resolved.
