### ISSUE TITLE
Tensorflow Lite GPU Delegate - Argmax Op Request

### ISSUE THREAD

**Issue by SanthoshRajendiran** [tensorflow/tensorflow#28600]
<em>Tensorflow Lite GPU Delegate - Argmax Op Request</em>

**System information**
- TensorFlow version (you are using): Tensorflow 1.13
Tensorflow Lite GPU Delegate 0.0.0-nightly
- Are you willing to contribute it (Yes/No): Yes

**Describe the feature and the current behavior/state.**
The current GPU delegate does not support Argmax op to run on the mobile GPU. It is one of the major stuff needed to be done for effective deeplab processing on the GPU, which could also be helpful in running the entire model on the GPU in the later stage. So, it would be useful if you could provide support for Argmax functionality on TFLite-GPU Delegate. In the current context, deeplab execution falls back from GPU to CPU on introduction of Argmax op. If that could not be done, can there be any other alternative to Argmax that can be used to effect a 2 class segmentation, or can a combination of ops can be added unto the base Model to effect a complete TFLite GPU Delegate model. If so, what has to be done?

**Will this change the current api? How?**
No. It is one more tflite op request. So, it must not affect other ops and functionality

**Who will benefit with this feature?**
Edge learning and Deeplab developers

**Comment by SanthoshRajendiran** [comment]
Are there any chances that Argmax GPU Delegate op will be introduced in the near future??

**Comment by impjdi** [comment]
@SanthoshRajendiran 

Given how resource constraint we are, we probably can't accommodate these individual requests =/

We have max pooling with indices.  Could you use that, or customize with that as a basis?  After all, we opensourced the GPU backend so you can customize it for your needs ;)

**Comment by SanthoshRajendiran** [comment]
@impjdi  Thank you.. Will look into customizing the GPU Backend code.
