### ISSUE TITLE
Tensorflow gives incorrect results for simple example

### ISSUE THREAD

**Issue by kenryd** [tensorflow/tensorflow#28608]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 16.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): v1.13.1-2-g09e3b09e69 1.13.1
- Python version: 2.7
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: CUDA 10.0
- GPU model and memory: GeForce GTX 1080

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
The actual output is [0.7853982 1.1071488]

**Describe the expected behavior**
The expected output is [0.7853982 0.7853982]

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.
```

from __future__ import print_function
import tensorflow as tf

with tf.device('cpu:0'):
    val0 = tf.ones((1,), dtype=tf.float32)
    val0 = tf.Print(val0, [])
    a = tf.atan2(val0, val0)
    b = tf.atan2(val0 + 1, val0 + 1)
    c = tf.concat([a, b], axis=0)
    c = tf.identity(c)

with tf.Session() as sess:
    print(sess.run(c))
```

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by jvishnuvardhan** [comment]
@kenryd I could reproduce this with TF1.13.1. However, with TF2.0, the results are what you expected. [GitHub Gist](https://colab.sandbox.google.com/gist/jvishnuvardhan/40edc993f3c1ce726a47dddd5bff7c6d/untitled151.ipynb) is here for TF2.0.0-alpha0. Thanks!

**Comment by kenryd** [comment]
@jvishnuvardhan In your link tf.Print is removed (I believe it was deprecated and remove in 2.0?). However, removing the tf.Print op in 1.13 also "fixes" the behavior, so this doesn't not address the problem.

My concern is that this bug is some memory problem, and "just use 2.0" isn't a solution. It's also not possible for everyone to just upgrade to 2.0 since tensorflow is often integrated into large projects where upgrading takes a significant amount of time.

The answer I get for the second value is 1.1071488 which is equal to atan2(2.0, 1.0), so tensorflow may be reading memory erroneously. If so, this is very concerning and undercuts any results I get in tensorflow: how do I know they're correct if there are bugs like this? Is there a way to avoid this specific bug in tensorflow 1.13?

**Comment by alextp** [comment]
This looks like a grappler bug which was fixed a few months ago. Can you reproduce it on nightly?

**Comment by kenryd** [comment]
@alextp After installing tf-nightly (1.14.1) it does indeed seem to be fixed. Thanks! Do you by chance know which commit fixed this issue?

**Comment by alextp** [comment]
No, not off the top of my head.
