### ISSUE TITLE
Custom layer build should fail if it includes tensor computations

### ISSUE THREAD

**Issue by seanpmorgan** [tensorflow/tensorflow#28602]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- TensorFlow installed from (source or binary): Binary
- TensorFlow version (use command below): 2.0
- Python version: Any

**Describe the current behavior**
Since https://github.com/tensorflow/tensorflow/commit/9df99aafc3480638cd8d2bf6a0caeab111b68302 it is required that there not be tensor computations in a layer's `build` method. We noticed this [because our layer serialization failed](https://github.com/tensorflow/addons/issues/203 ) after this commit. The fix was to move tensor computation into `call` method, though it was a silent fail and  would have been very difficult to troubleshoot if it didn't fail on a nightly. 

**Describe the expected behavior**
The build method should raise some kind of error saying that tensor computation is not allowed in build. It should also probably be mentioned in the documentation of TF or Keras:
https://www.tensorflow.org/tutorials/eager/custom_layers
https://keras.io/layers/writing-your-own-keras-layers/

It's sort of suggested but not well enough imo, especially with the hard to find fail it produces

**Code to reproduce the issue**
https://github.com/tensorflow/addons/pull/208

**Comment by omalleyt12** [comment]
HI @seanpmorgan, thanks for the issue! Everything in `build` should happen only once regardless, so for most cases Tensor computations in `build` are safe. Could you provide a minimal repro of why this is not true in your case?

**Comment by seanpmorgan** [comment]
I think there's more to this than simply running computations in build... but:

Here is it failing on tf2-nightly. If you uncomment `self._keras_style = False` it will pass:
https://colab.research.google.com/drive/1gyYBwE5r4scMc74JTSXaEd75v49-3IT2

Here it is passing on tf2-alpha:
https://colab.research.google.com/drive/1SNn9DG9C0eDCrATG-bNW_9d53DtEw5cl

**Comment by omalleyt12** [comment]
I see, thanks! This pattern will not work in general in 2.0 (for example, as a standalone layer in eager or a tf.function training loop). That's because in eager, once you call `tf.nn.l2_normalize` on a Variable, this is just a constant value that is no longer tied to the Variable

**Comment by seanpmorgan** [comment]
Ah thank you. Sorry this was overlooked when converting a layer from tf 1.x
