### ISSUE TITLE
Unexpected tf.version.GIT_VERSION for nightly builds

### ISSUE THREAD

**Issue by byronyi** [tensorflow/tensorflow#28628]
In colab, use the following commands to reproduce:

```
!pip uninstall tensorflow -yq && pip install tf-nightly-gpu==1.14.1.dev20190510 -q
import tensorflow as tf
tf.version.GIT_VERSION
```

Which shows ``v1.12.1-1705-g978532afa9`` (last hex is not any git commit btw)

Shouldn't it be the git version used to build that package instead?

Gentle ping @gunan and @yifeif

**Comment by muddham** [comment]
@byronyi Able to reproduce the issue. Please find attached log

'v1.12.1-1705-g978532afa9'

**Comment by wdirons** [comment]
The instructions in the new bug template (https://github.com/tensorflow/tensorflow/issues/new?template=00-bug-performance-issue.md) say for TF 1.X to use

`python -c "import tensorflow as tf; print(tf.GIT_VERSION)"`

**Comment by byronyi** [comment]
> The instructions in the new bug template (https://github.com/tensorflow/tensorflow/issues/new?template=00-bug-performance-issue.md) say for TF 1.X to use
> 
> `python -c "import tensorflow as tf; print(tf.GIT_VERSION)"`

I tried with

```
!pip uninstall tensorflow -yq && pip install tf-nightly-gpu==1.14.1.dev20190512 -q
import tensorflow as tf
print(tf.GIT_VERSION)
```

and I got:

```
b'v1.13.1-2-g09e3b09e69'
```

I am not aware how I should track a particular commit or snapshot for which the package is built.

**Comment by gunan** [comment]
@av8ramit Looking at this, I also cannot find g09e3b09e69.
Is it possible we create a bad commit when we run update_version during the nightly package build?

**Comment by av8ramit** [comment]
I don't think so. Let me take a look and investigate.

**Comment by av8ramit** [comment]
So git_version is behaving unexpectedly for tf_nightly packages. Unfortunately the hash logic is complicated and pulls from GitHub. Unfortunately, we may have to rely on the date for a window for the hash. We are not offering much support for nightly packages.

**Comment by byronyi** [comment]
@av8ramit does this mean I better not rely on GIT_VERSION strong in the nightly package?

**Comment by wdirons** [comment]
I did find a way to map from TensorFlow's GIT_VERSION to a commit hash (I just was unable to find this issue to update it)

Here is an example:
```
$ pip3 install tf-nightly==1.15.0.dev20190627

$ python3 -c "import tensorflow as tf; print(tf.version.GIT_VERSION)"
v1.12.1-5074-g51b4b90060

$ git clone https://github.com/tensorflow/tensorflow
$ cd tensorflow
$ git rev-list -n 1 v1.12.1-5074-g51b4b90060
51b4b90060bf2fb46b100648e739899054a84bea
```

**Comment by av8ramit** [comment]
@byronyi yes unfortunately I would advise against it.
