### ISSUE TITLE
Tensorboard: non-square images are overlapped

### ISSUE THREAD

**Issue by qbx2** [tensorflow/tensorflow#2862]
### Environment info
Operating System: Ubuntu 14.04

If installed from sources, provide the commit hash:
592675b2b8d1cabbf923638942ea6f200abe353a

### Steps to reproduce
1. Log some non-square (rectangle, 72x105 in my case) images (at least two) with SummaryWriter.
2. Load the log file with tensorboard.
3. Now, you will see the images are overlapped on images tab.

### What have you tried?
1. I tried to fix the CSS with Chrome debugger.<br />
I changed `height` property in `.tf-image-grid-0 .tag-name-cell.tf-image-grid` and `.tf-image-grid-0 .image-cell.tf-image-grid` to `auto`, and it seems to be good.<br />
However, I don't know what files need to be patched to apply this change.

### Logs or other output that would be helpful
Here is a screenshot of overlapped images.
`input/image/1`, `input/image/2` is not being shown properly.
Last image isn't overlapped.

<img width="620" alt="2016-06-15 4 20 07" src="https://cloud.githubusercontent.com/assets/5977817/16056438/7631b366-32b0-11e6-940e-1dfb7f532990.png">

**Comment by jart** [comment]
Thanks for reporting this issue @qbx2. I'm doing a bunch of work on polishing the images dashboard right now. I'll make sure this gets fixed in the near future.
