### ISSUE TITLE
`ConcreteFunction` does not raise errors when inputs and `tf.TensorSpec` are not compatible with each other

### ISSUE THREAD

**Issue by zakizhou** [tensorflow/tensorflow#28635]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): osx
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: none
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 1.14.1-dev20190509
- Python version: 3.7.1
- Bazel version (if compiling from source):None
- GCC/Compiler version (if compiling from source):None
- CUDA/cuDNN version:None
- GPU model and memory:None

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
```
import tensorflow as tf
tf.enable_v2_behavior()


@tf.function
def test_rank(x):
    return x


test_rank_cf = test_rank.get_concrete_function(tf.TensorSpec([None, None], tf.float32))
# run smoothly, should raise errors here?
test_rank_cf(tf.random.normal((2, 3, 4)))
```
**Describe the expected behavior**
Errors should be rasied if inputs and `tf.TensorSpec` are not compatible with each other
**Code to reproduce the issue**
See the above
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by achandraa** [comment]
I was able to replicate the behavior with TensorFlow 1.14.1-dev20190509 on Colab.

**Comment by jvishnuvardhan** [comment]
@zakizhou I think it is working as expected. Please check the [gist](https://colab.sandbox.google.com/gist/jvishnuvardhan/c7fde452c04e77184a796f4a700cb80d/untitled196.ipynb).

When I provide input of `int32`, it throws an error. I added this line in the end
`test_rank_cf(tf.fill([2,3,4],3))   # this throws an error as input is int32 whereas it was expecting float32`

**Comment by zakizhou** [comment]
@jvishnuvardhan 
`tf.TensorSpec([None, None], tf.float32)` means that the tensor provided for this concrete function should be a Tensor of rank two and tf.float32 as dtype, neither a mismatch with dtype nor rank should raise errors, in your example, there is a mismatch between dtype, so this concrete function exactly raises errors on the mismatch of dtype as it is expected to do, but `tf.random.normal((2, 3, 4))` is a tensor of rank three, not rank two, so errors should also be raised.

**Comment by alextp** [comment]
This is somewhat working as intended. By design concretefunction performs very little validation; you trade this against getting very low python overhead at execution time.

If you want validation pass a signature argument to tf.function and then call it.
