### ISSUE TITLE
switch statement

### ISSUE THREAD

**Issue by melo19890618** [tensorflow/tensorflow#28647]
I am a beginner of tensorflow。When I use tensorflow, I want to do this:
If (global_step%2==0):
      Compute and store
elif(global_step%2!=0):
      Get the stored date
After analysis, I found that tensorflow builds a graph using tf.cond instead of if。。。 else。。。.So I modified the code：tf.cond(tf.cast(global_step%2==0),tf.bool,Compute and store,  Get the stored date).However, there are still problems with such modifications after testing：Because the use of the tf.cond function will run both branches at the time of the feed, so add extra store and get overhead.
The purpose I want to accomplish is If (global_step%2==0)，Compute and store；else Get the stored date。This can reduce the computational overhead。
So I want to ask everyone how to achieve this in tensorflow?

**Comment by achandraa** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged//tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there and can provide better support for such issues. Thanks!
