### ISSUE TITLE
tf.lite.TFLiteConverter.from_saved_model error

### ISSUE THREAD

**Issue by toandrew** [tensorflow/tensorflow#28649]
**System information**
- OS Platform and Distribution (MacOS 10.14.4):
- TensorFlow installed from (binary):
- TensorFlow version (tensorflow==1.13.1):

**Provide the text output from tflite_convert**

Some of the operators in the model are not supported by the standard TensorFlow Lite runtime and are not recognized by TensorFlow. If you have a custom implementation for them you can disable this error with --allow_custom_ops, or by setting allow_custom_ops=True when calling tf.lite.TFLiteConverter(). Here is a list of builtin operators you are using: ADD, CAST, CONCATENATION, CONV_2D, EQUAL, EXPAND_DIMS, FILL, FULLY_CONNECTED, GATHER, LESS, LOGICAL_AND, LOGISTIC, MAXIMUM, MAX_POOL_2D, MINIMUM, PACK, RANGE, REDUCE_MAX, REDUCE_MIN, RESHAPE, SHAPE, SPARSE_TO_DENSE, STRIDED_SLICE, TRANSPOSE. Here is a list of operators for which you will need custom implementations: LSTMBlockCell, Merge, Switch.
Traceback (most recent call last):
  File "/Users/jim/src/ai/xiayu/deepiano/venv/bin/toco_from_protos", line 11, in <module>
    load_entry_point('tensorflow', 'console_scripts', 'toco_from_protos')()
  File "/Users/jim/src/ai/xiayu/deepiano/venv/lib/python3.7/site-packages/tensorflow-1.13.1-py3.7-macosx-10.14-x86_64.egg/tensorflow/lite/toco/python/toco_from_protos.py", line 59, in main
    app.run(main=execute, argv=[sys.argv[0]] + unparsed)
  File "/Users/jim/src/ai/xiayu/deepiano/venv/lib/python3.7/site-packages/tensorflow-1.13.1-py3.7-macosx-10.14-x86_64.egg/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "/Users/jim/src/ai/xiayu/deepiano/venv/lib/python3.7/site-packages/tensorflow-1.13.1-py3.7-macosx-10.14-x86_64.egg/tensorflow/lite/toco/python/toco_from_protos.py", line 33, in execute
    output_str = tensorflow_wrap_toco.TocoConvert(model_str, toco_str, input_str)
Exception: We are continually in the process of adding support to TensorFlow Lite for more ops. It would be helpful if you could inform us of how this conversion went by opening a github issue at https://github.com/tensorflow/tensorflow/issues/new?template=40-tflite-op-request.md
 and pasting the following:

Some of the operators in the model are not supported by the standard TensorFlow Lite runtime and are not recognized by TensorFlow. If you have a custom implementation for them you can disable this error with --allow_custom_ops, or by setting allow_custom_ops=True when calling tf.lite.TFLiteConverter(). Here is a list of builtin operators you are using: ADD, CAST, CONCATENATION, CONV_2D, EQUAL, EXPAND_DIMS, FILL, FULLY_CONNECTED, GATHER, LESS, LOGICAL_AND, LOGISTIC, MAXIMUM, MAX_POOL_2D, MINIMUM, PACK, RANGE, REDUCE_MAX, REDUCE_MIN, RESHAPE, SHAPE, SPARSE_TO_DENSE, STRIDED_SLICE, TRANSPOSE. Here is a list of operators for which you will need custom implementations: LSTMBlockCell, Merge, Switch.

Also, please include a link to a GraphDef or the model if possible.

Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by muddham** [comment]
@toandrew Request you to please refer [link1](https://www.tensorflow.org/lite/guide/ops_select), [link2](https://www.tensorflow.org/lite/guide/ops_custom). Please let us know how it progresses. Thanks!

**Comment by muddham** [comment]
@toandrew Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
