### ISSUE TITLE
Multi-GPU performance degradation in custom built TF

### ISSUE THREAD

**Issue by byronyi** [tensorflow/tensorflow#28653]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): tensorflow/benchmarks
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Debian 9.4
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy): N/A
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below): 33141833284a81a5ab3300047d2845c7124f4a66
- Python version: Python 3.5.3
- Bazel version (if compiling from source): 0.24.1
- GCC/Compiler version (if compiling from source): 6.3
- CUDA/cuDNN version: 10.0/7.4
- GPU model and memory: V100-PCIE-32GB

**Describe the current behavior**

Use the following command to compile (without running of `./configure`):

```
bazel build \
    -c opt \
    --jobs=32 \
    --action_env=PYTHON_BIN_PATH="/usr/bin/python3" \
    --action_env=PYTHON_LIB_PATH="/usr/local/lib/python3.5/dist-packages" \
    --python_path="/usr/bin/python3" \
    --define with_xla_support=true \
    --copt=-Wno-sign-compare \
    --copt=-march=broadwell \
    --host_copt=-march=broadwell \
    --define=with_default_optimizations=true \
    --config=cuda \
    --config=gdr \
    --config=mkl \
    //tensorflow/tools/pip_package:build_pip_package
```

Use the following command for benchmarking:

```
python benchmarks/scripts/tf_cnn_benchmarks/tf_cnn_benchmarks.py \
    --model=resnet50 \
    --batch_size=256 \
    --use_fp16 \
    --variable_update=parameter_server \
    --local_parameter_device=cpu \
    --num_gpus=$NUM_GPUS
```

| TF Version | 1-GPU | 2-GPU | 4-GPU | 8-GPU |
|:-:|:-:|:-:|:-:|:-:|
|1.13.1|786.63|1557.89|2982.52|5741.76|
|1.14.1.dev20190512|779.81|1547.23|2872.75|5671.7|
| 33141833284a81a5ab3300047d2845c7124f4a66|776.75|387.99|713.77|1249.80|

**Describe the expected behavior**

Related to #28628. I am currently not sure how to reproduce a custom build with the same GIT_VERSION as of nightly. I will try to reproduce this issue with the next nightly package.

**Comment by byronyi** [comment]
Removing ``--config=mkl`` resolves this issue.

**Comment by byronyi** [comment]
Gentle ping @claynerobison @nhasabni @mahmoud-abuzaina what is your recommended configuration if we try to run our wide and deep models on a mixed CPU/GPU cluster? Do we need to have a MKL build and a separate CUDA build?

**Comment by av8ramit** [comment]
As requested on the RFC, here is the build script for the nightly configuration.

Ubuntu 14.04
Python 3.5 
Bazel 0.24.1
GCC 4.8


```
# Run configure.
export TF_NEED_GCP=1
export TF_NEED_HDFS=1
export TF_NEED_S3=1
export TF_NEED_CUDA=1
export TF_CUDA_VERSION=10
export TF_CUDNN_VERSION=7
export TF_CUDA_COMPUTE_CAPABILITIES=3.5,3.7,5.2,6.0,6.1,7.0
export TF_NEED_TENSORRT=1
export TENSORRT_INSTALL_PATH=/usr/local/tensorrt
export CC_OPT_FLAGS='-mavx'
export PYTHON_BIN_PATH=$(which python3.5)
export PROJECT_NAME="tf_nightly_gpu"
yes "" | "$PYTHON_BIN_PATH" configure.py

# Build the pip package
bazel build --config=opt tensorflow/tools/pip_package:build_pip_package
mkdir pip_pkg
./bazel-bin/tensorflow/tools/pip_package/build_pip_package pip_pkg --gpu --nightly_flag
```
