### ISSUE TITLE
NotFoundError: Resource worker/embedding_layer

### ISSUE THREAD

**Issue by sarim-zafar** [tensorflow/tensorflow#28654]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Google Colab
- GPU model and memory: TPU

**Describe the current behavior**
When i try to call fit on a character level LSTM based model I get following error `NotFoundError: Resource worker/embedding_layer/embeddings/N10tensorflow3VarE does not exist.
	 [[{{node embedding_layer/embedding_lookup}}]]`

**Describe the expected behavior**
If I run the exact same model on a GPU, everything works as expected (eg. the model trains).

**Code to reproduce the issue**
I am following the official google guides as to how train a keras model on tpu using the tensorflow contrib keras to tpu model function

**Other info / logs**
```Train on 501147 samples, validate on 55684 samples
---------------------------------------------------------------------------
NotFoundError                             Traceback (most recent call last)
<ipython-input-32-fff2e852201f> in <module>()
----> 1 model.fit(X,y,epochs=1,validation_split=0.1,batch_size=batch_size)#,callbacks=callbacks)

4 frames
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/errors_impl.py in __exit__(self, type_arg, value_arg, traceback_arg)
    526             None, None,
    527             compat.as_text(c_api.TF_Message(self.status.status)),
--> 528             c_api.TF_GetCode(self.status.status))
    529     # Delete the underlying status object from memory otherwise it stays alive
    530     # as there is a reference to status from this from the traceback due to

NotFoundError: Resource worker/embedding_layer/embeddings/N10tensorflow3VarE does not exist.
	 [[{{node embedding_layer/embedding_lookup}}]]```

**Comment by gadagashwini** [comment]
@sarim-zafar Could you provide the minimum code snippet to reproduce the issue reported here. Thanks!

**Comment by sarim-zafar** [comment]
`# define LSTM
input_layer = Input(
      name='seed', shape=(longest,), batch_size=batch_size, dtype=tf.int32)
l0=Embedding(input_dim=max_token_index+1,output_dim=d,name='embedding_layer',mask_zero=True)(input_layer)
l1=GRU(128, return_sequences=True,dropout=0.2)(l0)
l2=GRU(128, return_sequences=True,dropout=0.2)(l1)
l3=GRU(128, return_sequences=True,dropout=0.2)(l2)
output=GRU(max_token_index+1,return_sequences=False, activation='softmax',dropout=0.2)(l3)
model = tf.keras.Model(inputs=[input_layer], outputs=[output])`
