### ISSUE TITLE
mode.fit() Error: ValueError: TypeError: len() of unsized object

### ISSUE THREAD

**Issue by IcarusZqt** [tensorflow/tensorflow#28651]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): No
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): pip install tensorflow==2.0.0-alpha0
- TensorFlow version (use command below):2.0.0-alpha0
- Python version: 3.6.3
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`
2.0.0-alpha0
**Describe the current behavior**
I run the code on my local machine : the TF 2.0 Alpha Train your first neural network: basic classification.
There is all right with the code before i call : model.fit(train_images, train_labels, epochs=5).
The errors are:
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-10-2e1aa44bfe09> in <module>
      1 # 训练
----> 2 model.fit(x_train, y_train, batch_size=50, epochs=50, validation_split=0.1, verbose=1)

D:\Softwares\Anaconda3\lib\site-packages\tensorflow\python\keras\engine\training.py in fit(self, x, y, batch_size, epochs, verbose, callbacks, validation_split, validation_data, shuffle, class_weight, sample_weight, initial_epoch, steps_per_epoch, validation_steps, validation_freq, max_queue_size, workers, use_multiprocessing, **kwargs)
    871           validation_steps=validation_steps,
    872           validation_freq=validation_freq,
--> 873           steps_name='steps_per_epoch')
    874 
    875   def evaluate(self,

D:\Softwares\Anaconda3\lib\site-packages\tensorflow\python\keras\engine\training_arrays.py in model_iteration(model, inputs, targets, sample_weights, batch_size, epochs, verbose, callbacks, val_inputs, val_targets, val_sample_weights, shuffle, initial_epoch, steps_per_epoch, validation_steps, validation_freq, mode, validation_in_fit, prepared_feed_values_from_dataset, steps_name, **kwargs)
    237     # Setup work for each epoch
    238     epoch_logs = {}
--> 239     model.reset_metrics()
    240     if mode == ModeKeys.TRAIN:
    241       callbacks.on_epoch_begin(epoch, epoch_logs)

D:\Softwares\Anaconda3\lib\site-packages\tensorflow\python\keras\engine\training.py in reset_metrics(self)
   1171     if hasattr(self, 'metrics'):
   1172       for m in self.metrics:
-> 1173         m.reset_states()
   1174 
   1175     # Reset the state of loss metric wrappers.

D:\Softwares\Anaconda3\lib\site-packages\tensorflow\python\keras\metrics.py in reset_states(self)
    197     when a metric is evaluated during training.
    198     """
--> 199     K.batch_set_value([(v, 0) for v in self.variables])
    200 
    201   @abc.abstractmethod

D:\Softwares\Anaconda3\lib\site-packages\tensorflow\python\keras\backend.py in batch_set_value(tuples)
   2878   if ops.executing_eagerly_outside_functions():
   2879     for x, value in tuples:
-> 2880       x.assign(np.asarray(value, dtype=dtype(x)))
   2881   else:
   2882     with get_graph().as_default():

D:\Softwares\Anaconda3\lib\site-packages\tensorflow\python\ops\resource_variable_ops.py in assign(self, value, use_locking, name, read_value)
   1051     # initialize the variable.
   1052     with _handle_graph(self.handle):
-> 1053       value_tensor = ops.convert_to_tensor(value, dtype=self.dtype)
   1054       self._shape.assert_is_compatible_with(value_tensor.shape)
   1055       assign_op = gen_resource_variable_ops.assign_variable_op(

D:\Softwares\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py in convert_to_tensor(value, dtype, name, preferred_dtype, dtype_hint)
   1048   preferred_dtype = deprecation.deprecated_argument_lookup(
   1049       "dtype_hint", dtype_hint, "preferred_dtype", preferred_dtype)
-> 1050   return convert_to_tensor_v2(value, dtype, preferred_dtype, name)
   1051 
   1052 

D:\Softwares\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py in convert_to_tensor_v2(value, dtype, dtype_hint, name)
   1106       name=name,
   1107       preferred_dtype=dtype_hint,
-> 1108       as_ref=False)
   1109 
   1110 

D:\Softwares\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py in internal_convert_to_tensor(value, dtype, name, as_ref, preferred_dtype, ctx, accept_symbolic_tensors)
   1184 
   1185     if ret is None:
-> 1186       ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
   1187 
   1188     if ret is NotImplemented:

D:\Softwares\Anaconda3\lib\site-packages\tensorflow\python\framework\constant_op.py in _constant_tensor_conversion_function(v, dtype, name, as_ref)
    302                                          as_ref=False):
    303   _ = as_ref
--> 304   return constant(v, dtype=dtype, name=name)
    305 
    306 

D:\Softwares\Anaconda3\lib\site-packages\tensorflow\python\framework\constant_op.py in constant(value, dtype, shape, name)
    243   """
    244   return _constant_impl(value, dtype, shape, name, verify_shape=False,
--> 245                         allow_broadcast=True)
    246 
    247 

D:\Softwares\Anaconda3\lib\site-packages\tensorflow\python\framework\constant_op.py in _constant_impl(value, dtype, shape, name, verify_shape, allow_broadcast)
    251   ctx = context.context()
    252   if ctx.executing_eagerly():
--> 253     t = convert_to_eager_tensor(value, ctx, dtype)
    254     if shape is None:
    255       return t

D:\Softwares\Anaconda3\lib\site-packages\tensorflow\python\framework\constant_op.py in convert_to_eager_tensor(value, ctx, dtype)
    112     return t
    113   else:
--> 114     return ops.EagerTensor(value, handle, device, dtype)
    115 
    116 

ValueError: TypeError: len() of unsized object
**Describe the expected behavior**

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by gadagashwini** [comment]
@IcarusZqt In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thanks!

**Comment by creeeeeg** [comment]
````
import tensorflow as tf
import matplotlib.pyplot as plt
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Conv2D, Dropout, Flatten, MaxPooling2D

(x_train, y_train), (x_test, y_test) = tf.keras.datasets.mnist.load_data()

x_train = x_train.reshape(x_train.shape[0], 28, 28, 1)
x_test = x_test.reshape(x_test.shape[0], 28, 28, 1)
input_shape = (28, 28, 1)

x_train = x_train.astype('float32')
x_test = x_test.astype('float32')

# normalize rgb codes by dividing by the max rgb value of 255...
x_train /= 255
x_test /= 255

model = Sequential()
model.add(Conv2D(28, kernel_size=(3,3), input_shape=input_shape))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Flatten()) # Flattening the 2D arrays for fully connected layers
model.add(Dense(128, activation=tf.nn.relu))
model.add(Dropout(0.2))
model.add(Dense(10,activation=tf.nn.softmax))

model.compile(optimizer = 'adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])


model.fit(x=x_train, y=y_train, epochs=10)
````

Here's a repro for an example that is giving me the same issue... just attempting to use mnist to go through some 2.0 stuff... hope this is the right place to respond... I'm getting the same or similar error as follows....

> Traceback (most recent call last):
> 
>   File "<ipython-input-14-c21a5ac899c2>", line 1, in <module>
>     model.fit(x=x_train, y=y_train, epochs=10)
> 
>   File "C:\Users\c\AppData\Local\Continuum\anaconda3\envs\venv\lib\site-packages\tensorflow\python\keras\engine\training.py", line 873, in fit
>     steps_name='steps_per_epoch')
> 
>   File "C:\Users\c\AppData\Local\Continuum\anaconda3\envs\venv\lib\site-packages\tensorflow\python\keras\engine\training_arrays.py", line 239, in model_iteration
>     model.reset_metrics()
> 
>   File "C:\Users\c\AppData\Local\Continuum\anaconda3\envs\venv\lib\site-packages\tensorflow\python\keras\engine\training.py", line 1173, in reset_metrics
>     m.reset_states()
> 
>   File "C:\Users\c\AppData\Local\Continuum\anaconda3\envs\venv\lib\site-packages\tensorflow\python\keras\metrics.py", line 199, in reset_states
>     K.batch_set_value([(v, 0) for v in self.variables])
> 
>   File "C:\Users\c\AppData\Local\Continuum\anaconda3\envs\venv\lib\site-packages\tensorflow\python\keras\backend.py", line 2880, in batch_set_value
>     x.assign(np.asarray(value, dtype=dtype(x)))
> 
>   File "C:\Users\c\AppData\Local\Continuum\anaconda3\envs\venv\lib\site-packages\tensorflow\python\ops\resource_variable_ops.py", line 1053, in assign
>     value_tensor = ops.convert_to_tensor(value, dtype=self.dtype)
> 
>   File "C:\Users\c\AppData\Local\Continuum\anaconda3\envs\venv\lib\site-packages\tensorflow\python\framework\ops.py", line 1050, in convert_to_tensor
>     return convert_to_tensor_v2(value, dtype, preferred_dtype, name)
> 
>   File "C:\Users\c\AppData\Local\Continuum\anaconda3\envs\venv\lib\site-packages\tensorflow\python\framework\ops.py", line 1108, in convert_to_tensor_v2
>     as_ref=False)
> 
>   File "C:\Users\c\AppData\Local\Continuum\anaconda3\envs\venv\lib\site-packages\tensorflow\python\framework\ops.py", line 1186, in internal_convert_to_tensor
>     ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
> 
>   File "C:\Users\c\AppData\Local\Continuum\anaconda3\envs\venv\lib\site-packages\tensorflow\python\framework\constant_op.py", line 304, in _constant_tensor_conversion_function
>     return constant(v, dtype=dtype, name=name)
> 
>   File "C:\Users\c\AppData\Local\Continuum\anaconda3\envs\venv\lib\site-packages\tensorflow\python\framework\constant_op.py", line 245, in constant
>     allow_broadcast=True)
> 
>   File "C:\Users\c\AppData\Local\Continuum\anaconda3\envs\venv\lib\site-packages\tensorflow\python\framework\constant_op.py", line 253, in _constant_impl
>     t = convert_to_eager_tensor(value, ctx, dtype)
> 
>   File "C:\Users\c\AppData\Local\Continuum\anaconda3\envs\venv\lib\site-packages\tensorflow\python\framework\constant_op.py", line 114, in convert_to_eager_tensor
>     return ops.EagerTensor(value, handle, device, dtype)
> 
> ValueError: TypeError: len() of unsized object

**Comment by IcarusZqt** [comment]
> ```
> import tensorflow as tf
> import matplotlib.pyplot as plt
> from tensorflow.keras.models import Sequential
> from tensorflow.keras.layers import Dense, Conv2D, Dropout, Flatten, MaxPooling2D
> 
> (x_train, y_train), (x_test, y_test) = tf.keras.datasets.mnist.load_data()
> 
> x_train = x_train.reshape(x_train.shape[0], 28, 28, 1)
> x_test = x_test.reshape(x_test.shape[0], 28, 28, 1)
> input_shape = (28, 28, 1)
> 
> x_train = x_train.astype('float32')
> x_test = x_test.astype('float32')
> 
> # normalize rgb codes by dividing by the max rgb value of 255...
> x_train /= 255
> x_test /= 255
> 
> model = Sequential()
> model.add(Conv2D(28, kernel_size=(3,3), input_shape=input_shape))
> model.add(MaxPooling2D(pool_size=(2, 2)))
> model.add(Flatten()) # Flattening the 2D arrays for fully connected layers
> model.add(Dense(128, activation=tf.nn.relu))
> model.add(Dropout(0.2))
> model.add(Dense(10,activation=tf.nn.softmax))
> 
> model.compile(optimizer = 'adam',
>               loss='sparse_categorical_crossentropy',
>               metrics=['accuracy'])
> 
> 
> model.fit(x=x_train, y=y_train, epochs=10)
> ```
> 
> Here's a repro for an example that is giving me the same issue... just attempting to use mnist to go through some 2.0 stuff... hope this is the right place to respond... I'm getting the same or similar error as follows....
> 
> > Traceback (most recent call last):
> > File "", line 1, in 
> > model.fit(x=x_train, y=y_train, epochs=10)
> > File "C:\Users\c\AppData\Local\Continuum\anaconda3\envs\venv\lib\site-packages\tensorflow\python\keras\engine\training.py", line 873, in fit
> > steps_name='steps_per_epoch')
> > File "C:\Users\c\AppData\Local\Continuum\anaconda3\envs\venv\lib\site-packages\tensorflow\python\keras\engine\training_arrays.py", line 239, in model_iteration
> > model.reset_metrics()
> > File "C:\Users\c\AppData\Local\Continuum\anaconda3\envs\venv\lib\site-packages\tensorflow\python\keras\engine\training.py", line 1173, in reset_metrics
> > m.reset_states()
> > File "C:\Users\c\AppData\Local\Continuum\anaconda3\envs\venv\lib\site-packages\tensorflow\python\keras\metrics.py", line 199, in reset_states
> > K.batch_set_value([(v, 0) for v in self.variables])
> > File "C:\Users\c\AppData\Local\Continuum\anaconda3\envs\venv\lib\site-packages\tensorflow\python\keras\backend.py", line 2880, in batch_set_value
> > x.assign(np.asarray(value, dtype=dtype(x)))
> > File "C:\Users\c\AppData\Local\Continuum\anaconda3\envs\venv\lib\site-packages\tensorflow\python\ops\resource_variable_ops.py", line 1053, in assign
> > value_tensor = ops.convert_to_tensor(value, dtype=self.dtype)
> > File "C:\Users\c\AppData\Local\Continuum\anaconda3\envs\venv\lib\site-packages\tensorflow\python\framework\ops.py", line 1050, in convert_to_tensor
> > return convert_to_tensor_v2(value, dtype, preferred_dtype, name)
> > File "C:\Users\c\AppData\Local\Continuum\anaconda3\envs\venv\lib\site-packages\tensorflow\python\framework\ops.py", line 1108, in convert_to_tensor_v2
> > as_ref=False)
> > File "C:\Users\c\AppData\Local\Continuum\anaconda3\envs\venv\lib\site-packages\tensorflow\python\framework\ops.py", line 1186, in internal_convert_to_tensor
> > ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
> > File "C:\Users\c\AppData\Local\Continuum\anaconda3\envs\venv\lib\site-packages\tensorflow\python\framework\constant_op.py", line 304, in _constant_tensor_conversion_function
> > return constant(v, dtype=dtype, name=name)
> > File "C:\Users\c\AppData\Local\Continuum\anaconda3\envs\venv\lib\site-packages\tensorflow\python\framework\constant_op.py", line 245, in constant
> > allow_broadcast=True)
> > File "C:\Users\c\AppData\Local\Continuum\anaconda3\envs\venv\lib\site-packages\tensorflow\python\framework\constant_op.py", line 253, in _constant_impl
> > t = convert_to_eager_tensor(value, ctx, dtype)
> > File "C:\Users\c\AppData\Local\Continuum\anaconda3\envs\venv\lib\site-packages\tensorflow\python\framework\constant_op.py", line 114, in convert_to_eager_tensor
> > return ops.EagerTensor(value, handle, device, dtype)
> > ValueError: TypeError: len() of unsized object

Hi, i uninstall my Anaconda(python 3.6.3) and install the latest Anaconda and the error is gone.
