### ISSUE TITLE
I can not import tf successfully although it doesn't output any error

### ISSUE THREAD

**Issue by WY19940327** [tensorflow/tensorflow#28666]
<em> </em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Win10 64bit
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version: 1.8.0
- Python version: 3.6
- Installed using virtualenv? pip? conda?: conda
- Bazel version (if compiling from source): 0.16.1
- GCC/Compiler version (if compiling from source): gcc 6.3
- CUDA/cuDNN version: CUDA_9.0; cuDNN_7.1
- GPU model and memory: GTX 1080ti

**Describe the problem**

I follow the guide : https://www.pugetsystems.com/labs/hpc/The-Best-Way-to-Install-TensorFlow-with-GPU-Support-on-Windows-10-Without-Installing-CUDA-1187/
but when I used cmd or spyder to write&run tensorflow with 'import tensorflow as tf', the console will run a moment and output none

**Any other info / logs**

![spyder](https://user-images.githubusercontent.com/49911630/57619542-1d2ae880-75c1-11e9-97b8-c417790f4afb.png)

**Comment by gadagashwini** [comment]
@WY19940327 I tried reproducing the issue  but the code executed and also displayed the result. Can you try once again and let us know if that still gives no output. Also follow the instructions in this [link](https://www.tensorflow.org/install/pip) to install Tensorflow. Thanks!

**Comment by WY19940327** [comment]
Thank U! I will try to reinstall tf follow your link and give you res

**Comment by WY19940327** [comment]
@gadagashwini I reinstall tf-gpu follow your link, but the system output same things

![image](https://user-images.githubusercontent.com/49911630/57771285-411b3500-774d-11e9-8bfe-c1aa005d4ee3.png)

![image](https://user-images.githubusercontent.com/49911630/57771321-598b4f80-774d-11e9-8f88-a3dfccb165fe.png)

![image](https://user-images.githubusercontent.com/49911630/57771406-96efdd00-774d-11e9-9cc5-8187f1890b3d.png)

**Comment by gadagashwini** [comment]
@WY19940327 Just to clarify, Did you install tensorflow inside the conda environment or outside?

**Comment by WY19940327** [comment]
@gadagashwini  I installed tensorflow by 'conda -c anaconda tensorflow-gpu==1.8.0' before you gave me the guide link which used the pip. maybe some thing wrong in my processing

**Comment by gadagashwini** [comment]
@WY19940327 To verify, Please let us know if you are still stuck?  Thanks!

**Comment by WY19940327** [comment]
@gadagashwini yes. it made me crazy. no matter I used conda or pip tf follow your guide, I always got same problem with the 'import tf'

**Comment by WY19940327** [comment]
@gadagashwini  sorry, I found my gtx 1080ti is used cuda10.0, not cuda9.0. I try to change my cuda version

**Comment by WY19940327** [comment]
@gadagashwini I successfully installed the tensorflow-gpu==1.13.0 (even though there were something wrong). 
![image](https://user-images.githubusercontent.com/49911630/57930363-ba9f5880-78f0-11e9-9678-588cc6afa851.png)
However, I also can't use tensorflow-gpu normally
![image](https://user-images.githubusercontent.com/49911630/57930520-208be000-78f1-11e9-9c07-efb1d97de561.png)

**Comment by WY19940327** [comment]
@gadagashwini god like! I just remove the env which installed by conda and use virtualenv, then everything has been OK. Anyway, thanks your help.

![image](https://user-images.githubusercontent.com/49911630/57962284-033a2e80-7950-11e9-82a2-1decc6dff4eb.png)

**Comment by gadagashwini** [comment]
@WY19940327 Glad it resolved. Will close this. Thanks!
