### ISSUE TITLE
ImportError: /lib64/libm.so.6: version `GLIBC_2.23' not found (required by /home/xsx/.conda/envs/tensorflow/lib/python3.7/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so)

### ISSUE THREAD

**Issue by PrimaryKey** [tensorflow/tensorflow#28660]
- centos7_DVD(The latest version)
- python: 3.7.3
- tensorflow:  1.13.1
- anaconda: Anaconda3-2019.03-Linux-x86_64

After the installation of tensorflow(cpu version) via pip command, I just used import tensorflow as tf which leads to the following error message；

```
### >>> import tensorflow
Traceback (most recent call last):
  File "/home/xsx/.conda/envs/tensorflow/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/home/xsx/.conda/envs/tensorflow/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/home/xsx/.conda/envs/tensorflow/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/home/xsx/.conda/envs/tensorflow/lib/python3.7/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/home/xsx/.conda/envs/tensorflow/lib/python3.7/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: /lib64/libm.so.6: version `GLIBC_2.23' not found (required by /home/xsx/.conda/envs/tensorflow/lib/python3.7/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so)
```

I try to update GLIBC_2.23,But the whole system crashed；

This problem has been bothering me for a week and my system has crashed three times.

**Is it a version support issue for tensorflow?**

**Comment by PrimaryKey** [comment]
Today, I tried to downgrade the python version to 3.6.8, and all the problems were gone.
I don't know if I should cry or laugh.
Hope to help you.

**Comment by MikeJay-ctrl** [comment]
Thanks! 
Downgrading python did the job for me too, out of curiosity what made you choose to downgrade to this specific version

**Comment by PrimaryKey** [comment]
> Thanks!
> Downgrading python did the job for me too, out of curiosity what made you choose to downgrade to this specific version

This is my first question on GITHUB.
I am very happy to help you solve this problem, and congratulations on your successful installation.
I forgot which blog I saw about the version, so I tried it and just tried it.

**Comment by billtubbs** [comment]
Had same problem.  Super annoying.that  `python             pkgs/main/linux-64::python-3.7.3-h0371630_0`

**Comment by Hemnepal** [comment]
Creating this new environment worked on mine too

**Comment by philippbayer** [comment]
Hello, 3.7.3 did not work for me, I still got the same error, but with 3.6.8 it worked:

    conda create -n tf-cpu tensorflow python=3.6.8

**Comment by PrimaryKey** [comment]
a good news.

**Comment by pournami123** [comment]
A solution that worked for me in centos 7 with miniconda installed
Create an environment for tensorflow with the python version=3.6.8
`conda create -n tfgpu tensorflow python=3.6.8
`
Now install the tensorflow with version 1.13.1
`conda install tensorflow-gpu==1.13.1
`

**Comment by HaFred** [comment]
If you have set up a conda enviroment like me but wanna install tensorflow1.14 (rather than tensorflow2) with CUDA10.1, you could try to install tensorflow with `conda install`. https://github.com/tensorflow/tensorflow/issues/26289#issuecomment-515494697

**Comment by JiangKui007** [comment]
It work for me. 
`conda create -n tf-cpu tensorflow==1.13.1`

can install python3.7.9 and tensorflow 1.13.1
