### ISSUE TITLE
AttributeError: '_OptionsDataset' object has no attribute 'output_shapes'

### ISSUE THREAD

**Issue by lucifer2288** [tensorflow/tensorflow#28669]
Downloading / extracting dataset imdb_reviews (?? GiB) to /home/lucifer/tensorflow_datasets/imdb_reviews/subwords8k/0.0.1...
Dl Completed...:   0%|          | 0/1 [00:01<?, ? url/s]
Dl Size...:   0%|          | 0/80 [00:01<?, ? MiB/s]
Dl Completed...:   0%|          | 0/1 [00:41<?, ? url/s]MiB]
Dl Size...:   1%|▏         | 1/80 [00:41<54:16, 41.23s/ MiB]
Dl Completed...:   0%|          | 0/1 [01:52<?, ? url/s]/ MiB]
Dl Size...:   2%|▎         | 2/80 [01:52<1:05:24, 50.31s/ MiB]
Dl Completed...:   0%|          | 0/1 [02:12<?, ? url/s]MiB]  
Dl Size...:   4%|▍         | 3/80 [02:12<52:38, 41.02s/ MiB]
Dl Completed...:   0%|          | 0/1 [02:55<?, ? url/s]MiB]
Dl Size...:   5%|▌         | 4/80 [02:55<52:45, 41.65s/ MiB]
Dl Completed...:   0%|          | 0/1 [03:01<?, ? url/s]MiB]
Dl Size...:   6%|▋         | 5/80 [03:01<38:43, 30.98s/ MiB]
Dl Completed...:   0%|          | 0/1 [03:34<?, ? url/s]MiB]
Dl Size...:   8%|▊         | 6/80 [03:34<39:07, 31.72s/ MiB]
Dl Completed...:   0%|          | 0/1 [03:39<?, ? url/s]MiB]
Dl Size...:   9%|▉         | 7/80 [03:39<28:48, 23.68s/ MiB]

...........

Dl Size...:  99%|█████████▉| 79/80 [38:44<00:42, 42.73s/ MiB]
Dl Completed...:   0%|          | 0/1 [40:17<?, ? url/s] MiB]
Dl Size...: 100%|██████████| 80/80 [40:17<00:00, 57.89s/ MiB]
Dl Completed...:   0%|          | 0/1 [40:54<?, ? url/s]     
Dl Size...: 81 MiB [40:54, 51.50s/ MiB]
Dl Completed...:   0%|          | 0/1 [42:18<?, ? url/s]
Dl Size...: 82 MiB [42:18, 61.31s/ MiB]
Dl Completed...:   0%|          | 0/1 [42:50<?, ? url/s]
Dl Size...: 83 MiB [42:50, 52.68s/ MiB]
Dl Completed...:   0%|          | 0/1 [43:56<?, ? url/s]

........

Dl Size...: 154 MiB [1:22:41, 80.27s/ MiB]
Dl Completed...: 100%|██████████| 1/1 [1:23:56<00:00, 4554.05s/ url]
Dl Size...: 155 MiB [1:23:56, 78.58s/ MiB]
Dl Completed...: 100%|██████████| 1/1 [1:24:53<00:00, 4554.05s/ url]
Dl Completed...: 2 url [1:25:03, 3352.75s/ url]                     
Dl Size...: 156 MiB [1:25:03, 72.26s/ MiB]

25000 examples [00:28, 863.60 examples/s] 
Shuffling...:   0%|          | 0/10 [00:00<?, ? shard/s]WARNING: Logging before flag parsing goes to stderr.
W0513 21:39:05.540721 140294086346560 deprecation.py:323] From /home/lucifer/anaconda3/lib/python3.7/site-packages/tensorflow_datasets/core/file_format_adapter.py:249: tf_record_iterator (from tensorflow.python.lib.io.tf_record) is deprecated and will be removed in a future version.
Instructions for updating:
Use eager execution and: 
`tf.data.TFRecordDataset(path)`

Reading...: 0 examples [00:00, ? examples/s]
Reading...: 2500 examples [00:00, 230117.41 examples/s]
Writing...:   0%|          | 0/2500 [00:00<?, ? examples/s]
Writing...: 100%|██████████| 2500/2500 [00:00<00:00, 172112.14 examples/s]
Reading...: 0 examples [00:00, ? examples/s]
Reading...: 2500 examples [00:00, 198575.13 examples/s]
Writing...:   0%|          | 0/2500 [00:00<?, ? examples/s]
Writing...: 100%|██████████| 2500/2500 [00:00<00:00, 191566.22 examples/s]
Reading...: 0 examples [00:00, ? examples/s]
Reading...: 2500 examples [00:00, 203007.82 examples/s]
Writing...:   0%|          | 0/2500 [00:00<?, ? examples/s]

........

17342 examples [00:02, 5761.24 examples/s]
17994 examples [00:03, 5968.74 examples/s]
18644 examples [00:03, 6116.94 examples/s]
19303 examples [00:03, 6249.34 examples/s]
19966 examples [00:03, 6358.77 examples/s]
20624 examples [00:03, 6421.09 examples/s]
21278 examples [00:03, 6428.01 examples/s]
21935 examples [00:03, 6468.08 examples/s]
22588 examples [00:03, 6486.41 examples/s]
23241 examples [00:03, 6458.44 examples/s]
23890 examples [00:03, 6432.71 examples/s]
24551 examples [00:04, 6482.91 examples/s]
25000 examples [00:04, 5994.04 examples/s]
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-4-31d575d3ee06> in <module>
      1 dataset, info = tfds.load('imdb_reviews/subwords8k', with_info=True,
----> 2                           as_supervised=True)
      3 train_dataset, test_dataset = dataset['train'], dataset['test']

~/anaconda3/lib/python3.7/site-packages/tensorflow_datasets/core/api_utils.py in disallow_positional_args_dec(fn, instance, args, kwargs)
     50     _check_no_positional(fn, args, ismethod, allowed=allowed)
     51     _check_required(fn, kwargs)
---> 52     return fn(*args, **kwargs)
     53 
     54   return disallow_positional_args_dec(wrapped)  # pylint: disable=no-value-for-parameter

~/anaconda3/lib/python3.7/site-packages/tensorflow_datasets/core/registered.py in load(name, split, data_dir, batch_size, download, as_supervised, with_info, builder_kwargs, download_and_prepare_kwargs, as_dataset_kwargs)
    251   if download:
    252     download_and_prepare_kwargs = download_and_prepare_kwargs or {}
--> 253     dbuilder.download_and_prepare(**download_and_prepare_kwargs)
    254 
    255   if as_dataset_kwargs is None:

~/anaconda3/lib/python3.7/site-packages/tensorflow_datasets/core/api_utils.py in disallow_positional_args_dec(fn, instance, args, kwargs)
     50     _check_no_positional(fn, args, ismethod, allowed=allowed)
     51     _check_required(fn, kwargs)
---> 52     return fn(*args, **kwargs)
     53 
     54   return disallow_positional_args_dec(wrapped)  # pylint: disable=no-value-for-parameter

~/anaconda3/lib/python3.7/site-packages/tensorflow_datasets/core/dataset_builder.py in download_and_prepare(self, download_dir, download_config)
    234         else:  # Mode is forced or stats do not exists yet
    235           logging.info("Computing statistics.")
--> 236           self.info.compute_dynamic_properties()
    237         # Set checksums of downloaded (or cached) files, and size:
    238         self.info.download_checksums = dl_manager.recorded_download_checksums

~/anaconda3/lib/python3.7/site-packages/tensorflow_datasets/core/dataset_info.py in compute_dynamic_properties(self)
    243 
    244   def compute_dynamic_properties(self):
--> 245     self._compute_dynamic_properties(self._builder)
    246     self._fully_initialized = True
    247 

~/anaconda3/lib/python3.7/site-packages/tensorflow_datasets/core/dataset_info.py in _compute_dynamic_properties(self, builder)
    256         # Fill DatasetFeatureStatistics.
    257         dataset_feature_statistics, schema = get_dataset_feature_statistics(
--> 258             builder, split_name)
    259 
    260         # Add the statistics to this split.

~/anaconda3/lib/python3.7/site-packages/tensorflow_datasets/core/dataset_info.py in get_dataset_feature_statistics(builder, split)
    488   # Start here, we've processed all examples.
    489 
--> 490   output_shapes_dict = dataset.output_shapes
    491   output_types_dict = dataset.output_types
    492 

AttributeError: '_OptionsDataset' object has no attribute 'output_shapes'

**Comment by lucifer2288** [comment]
Tutorials in TF2.0 Alpha
linux ubuntu 18.04
GTX780
tensorflow2.0  alpha0 gpu version

when i run "Text classification with an RNN",  the error comes as follows:

**Comment by gadagashwini** [comment]
@lucifer2288 I tried reproducing the issue through colab link of Text classification with an RNN but the code executed without any error. Can you try once again and let us know if that still gives error. Thanks!

**Comment by lucifer2288** [comment]
> @lucifer2288 I tried reproducing the issue through colab link of Text classification with an RNN but the code executed without any error. Can you try once again and let us know if that still gives error. Thanks!

thank you very much,  i solved this problem by update tensorflow-datasets from v1.0.1 to v1.0.2,  case closed,

**Comment by lucifer2288** [comment]
> @lucifer2288 I tried reproducing the issue through colab link of Text classification with an RNN but the code executed without any error. Can you try once again and let us know if that still gives error. Thanks!

Thank you dude

**Comment by ZhiqingXiao** [comment]
I just try the "text_classification.ipynb" in the colab. The issue still exists.
(tensorflow-datasets version: 1.3.2)

**Comment by jiankaiwang** [comment]
The attribute `output_shapes` was deprecated, you can access the output shapes via `tf.compat.v1.data.get_output_shapes()`.

**Comment by toaomalkster** [comment]
The docs need updating to with recommended solution:
https://www.tensorflow.org/tutorials/keras/text_classification

Still has
```
train_batches = (
    train_data
    .shuffle(BUFFER_SIZE)
    .padded_batch(32, train_data.output_shapes))

test_batches = (
    test_data
    .padded_batch(32, train_data.output_shapes))
```
