### ISSUE TITLE
Support size 0 tensors with parse_example and parse_single_example

### ISSUE THREAD

**Issue by shoyer** [tensorflow/tensorflow#2867]
Currently, this fails `InvalidArgumentError: Name: <unknown>, Feature: a is required but could not be found.`:

```
import tensorflow as tf
sess = tf.InteractiveSession()

features = {'a': tf.FixedLenFeature([0], tf.int64, [])}
serialized = tf.placeholder(tf.string, [])
parsed = tf.parse_single_example(serialized, features)

example_str = tf.train.Example().SerializeToString()
sess.run(parsed['a'], feed_dict={serialized: example_str})
```

(The same is true for `tf.parse_example`.)

This sort of thing may seem useless, but can be handy for writing generic code that handles variable sized input (with fixed size for each graph).

**Comment by ebrevdo** [comment]
This is definitely useful.  Are you interested in piping this through the parser library?

**Comment by aselle** [comment]
Automatically closing due to lack of recent activity. Thanks!
