### ISSUE TITLE
[TF 2.0 API Docs] tf  - typo, extra symbols in pip install doc copy code

### ISSUE THREAD

**Issue by ghchinoy** [tensorflow/tensorflow#28680]
## Existing URL(s) with the issue:
https://www.tensorflow.org/versions/r2.0/api_docs/python/tf

## Description of issue (what needs changing):

Copyable code block has extra characters `",` at the end:

```pip install tensorflow==2.0.0-alpha0",```

### Clear description

Copyable code block should be changed to the following to make copying easier.

```pip install tensorflow==2.0.0-alpha0```

### Correct links

This is the overview for the TF 2.0 API, but I couldn't find the docstring in the referred source: https://github.com/tensorflow/tensorflow/blob/r2.0/tensorflow/__init__.py

### Submit a pull request?

Would love to, but couldn't find in source where this was a docstring or being generated :(

**Comment by gadagashwini** [comment]
@ghchinoy Looks like this is fixed. 
Can you please let us know if you are happy to close if no issue persists. Thanks!
