### ISSUE TITLE
Error using tensorflow module, even appearing in the list shown by pip list

### ISSUE THREAD

**Issue by wagnerDestro** [tensorflow/tensorflow#28684]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- TensorFlow installed from (source or binary): source
- TensorFlow version:
- Python version: 3.7.3
- Installed using virtualenv? pip? conda?: pip
- GPU model and memory: MX920

**Describe the problem**

I can't use tensorflow module, even appearing in the list shown by pip list

**Provide the exact sequence of commands / steps that you executed before running into the problem**

I executed the 3 first commands: 
_python3 --version
pip3 --version
virtualenv --version_

But, the answer I get from the 1st command was: "python3" is not recognized as a intern or extern command, operational program or a batch file

Then I just keep with the installation, because the virtualenv and the pip3 were updated, and after that, I tried to do the command:
_virtualenv --system-site-packages -p python3 ./venv_
But the answer I get was:
_The path python3 (from --python=python3) does not exist_

so, I couldn't create the virtual environment.
After that, I wrote the command:
_pip3 install --user --upgrade tensorflow_

And the command:
_pip list_

In the answer of the last one, the list showed that the tensorflow was installed, but when I tried to run an example provided by the TensorFlow site, PyCharm couldn't find the module, and now I don't know what to do.
Also, when I write the command: 
_python -c "import tensorflow as tf; tf.enable_eager_execution(); print(tf.reduce_sum(tf.random_normal([1000, 1000])))"_

I get this answer:
_2019-05-13 21:40:50.182555: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
tf.Tensor(1277.5322, shape=(), dtype=float32)_

**Comment by gadagashwini** [comment]
@wagnerDestro Please follow the instructions in this [link](https://www.tensorflow.org/install/pip) to install tensorflow. Thanks!

**Comment by wagnerDestro** [comment]
@gadagashwini I followed the steps in the tensorflow guide. I even reinstalled Python 3 to make sure, but the error persists.

**Comment by gadagashwini** [comment]
@wagnerDestro Can you recheck and confirm that your cpu supports AVX2?

**Comment by gadagashwini** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
