### ISSUE TITLE
Keras model to tensorflow trainable pb file and checkpoint

### ISSUE THREAD

**Issue by imnotkind** [tensorflow/tensorflow#28681]
I tried to convert keras h5 model into pb and checkpoint files.
```python
from keras import backend as K
from keras.models import load_model
import tensorflow as tf

model = load_model('model/my_model.h5')

K.set_learning_phase(0) #0 : test, 1 : train

sess = K.get_session()

saver = tf.train.Saver()
saver.save(sess, 'keras/keras.ckpt')

sess.graph.as_default()
graph = sess.graph

with open('keras/keras.pb', 'wb') as f:
    f.write(graph.as_graph_def().SerializeToString())
```

I succeeded in bringing this pb and checkpoint to tensorflow and running the graph, obtaining an inference.
But the problem is, I have no idea how to train this thing.
Usually, tensorflow models have a training operation, and we just have to sess.run that operation, but I'm assuming keras is working in a different way somehow.
Is it possible to train keras models when they are converted to tensorflow models?

**Comment by ymodak** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow-tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.
