### ISSUE TITLE
ConvLSTM2D - Include feedback loop from c_tm1 (carry state)

### ISSUE THREAD

**Issue by cgebbe** [tensorflow/tensorflow#28698]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using): 1.13
- Are you willing to contribute it (Yes/No): Yes

Currently, the ConvLSTM2D layer does not include any feedback from C_tm1 (the carry state from the previous timestamp), see https://github.com/tensorflow/tensorflow/blob/r1.13/tensorflow/python/keras/layers/convolutional_recurrent.py#L717

This stands in contrast to the description of the original paper which is cited as a reference: https://arxiv.org/abs/1506.04214v1 .

The missing feedback loop is already documented "The current implementation does not include the feedback loop on the cells output". However, is there a reason that this feedback was omitted? If not, I don't see why it should be different from the paper....

**Will this change the current api? How?** 
We might add a boolean flag to either incorporate such feedback or not.

**Who will benefit with this feature?**
Any researcher looking for an implementation exactly like the original paper.

**Any Other info.**

**Comment by cgebbe** [comment]
P.s.: If I am not mistaken, it might not be straightforward, because we would need to store three different kernels:

W_x = [W_xi, W_xf, W_xo, W_xc] = [filter_height, filter_width, num_batch, num_filter*4]
W_h = [W_hi, W_hf, W_ho, W_hc] = [filter_height, filter_width, num_filter, num_filter*4]
W_c = [W_ci, W_cf, W_co] = [num_batch, input_width, input_height, 3] - Must be same width and height as X_T and C_t due to Hadamard product (see below) !

However, there is only self.kernel and self.recurrent_kernel for storage available. Can I simply add a self.recurrent_kernel_2 or is there a better option?

**Comment by qlzh727** [comment]
I think the code was originally from keras implementation in https://github.com/keras-team/keras/pull/3906. The context of not having feedback loop from previous state is kind of lost.

**Comment by qlzh727** [comment]
I took a look of the paper, it seems that the original paper was not using the vanilla version of LSTM, but a fully connected version. With that version, there is an extra weight for carry state of T - 1. I think we should have a new weight field for it, which only fuses 3 gates (input, forget, output, no carry gate). Probably we can call it recurrent_carry_kernel.

**Comment by qlzh727** [comment]
Sorry for the very late reply. This feature is quite stale and we actually don't have much bandwidth to address it. I am closing this for now, and feel free to reopen it if this is feature request is critical.
