### ISSUE TITLE
sequence_length causes error when using GRU

### ISSUE THREAD

**Issue by jstaker7** [tensorflow/tensorflow#287]
Calling this works just fine:
outputs, states = rnn.rnn(gru_cell, input, initial_state=initial_state)

But this causes an error:
outputs, states = rnn.rnn(gru_cell, input, initial_state=initial_state, sequence_length=seq_length)

Where I have tried the following for seq_length:
seq_length = tf.placeholder(tf.int64)
seq_length = tf.placeholder(tf.int32)
seq_length = tf.placeholder(tf.int64, shape=[1,1])

This is the error:

File "/site-packages/tensorflow/models/rnn/rnn.py", line 85, in rnn
    output_state = cell(input_, state)
  File "/site-packages/tensorflow/models/rnn/rnn_cell.py", line 120, in __call__
    2 * self._num_units, True, 1.0))
  File "/site-packages/tensorflow/models/rnn/linear.py", line 29, in linear
    shapes = [a.get_shape().as_list() for a in args]
  File "/site-packages/tensorflow/python/framework/tensor_shape.py", line 676, in as_list
    return [dim.value for dim in self._dims]
TypeError: 'NoneType' object is not iterable

**Comment by hujiewang** [comment]
bug confirmed

**Comment by ebrevdo** [comment]
Are you using the 0.6.0 package? This should be fixed in HEAD on github.

**Comment by vrv** [comment]
Should be fixed in 0.7+
