### ISSUE TITLE
defun + random + addition = explode

### ISSUE THREAD

**Issue by amilsted** [tensorflow/tensorflow#28709]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution: Colab or WSL Ubuntu 18.04
- Mobile device if the issue happens on mobile device:
- TensorFlow installed from: binary
- TensorFlow version: 1.13.1 or 1.14.1-dev20190514
- Python version: 3.6.8
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Describe the current behavior**
Using `defun` in eager mode, this very simple function seems to cause havoc. In particular, the first run takes a *long* time and a *lot* of memory, both scaling seemingly exponentially with the `n_iter` parameter below.
```python
import time
import tensorflow as tf
tf.enable_v2_behavior()

def f(D, num_iter):
    x = tf.random_uniform((D,))
    for i in range(num_iter):
        x = x + x
    return x

# DANGER: Increasing this much beyond 20 may use up all your memory...
n_iter = 22

t0 = time.time()
f(10, n_iter)
print(time.time() - t0)  # order ms

f_g = tf.contrib.eager.defun(f)
for i in range(3):
    t0 = time.time()
    f_g(10, n_iter)
    print(time.time() - t0)  # around 30s first run for n_iter=22! After that it's fast.
```
Replacing `x = tf.random_uniform((D,))` with `x = tf.ones((D,))` eliminates the problem, as does replacing `x = x + x` with `x = 2*x`.
In graph mode the problem does not occur:
```python
import time
import tensorflow as tf

def graph_fun(node):
    with tf.Session() as sesh:
        for i in range(3):
            t0 = time.time()
            sesh.run(node)
            print(time.time() - t0)

def f(D, num_iter):
    x = tf.random_uniform((D,))
    for i in range(num_iter):
        x = x + x
    return x

n_iter = 100

tf.reset_default_graph()
t0 = time.time()
fres = f(10, n_iter)
print(time.time() - t0)  # around 0.4s

graph_fun(fres)  # around 0.6 s first run, then essentially zero.
```

**Describe the expected behavior**
This very simple defun'd function should execute quickly, including the graph-building and graph optimization steps.

**Comment by muddham** [comment]
@amilsted Able to reproduce the issue in eager mode as below.
0.0017082691192626953
28.53006386756897
0.0010156631469726562
0.0005068778991699219.

After Replacing x = tf.random_uniform((D,)) with x = tf.ones((D,)) eliminates the problem, as does replacing x = x + x with x = 2*x.
0.0022535324096679688
0.0447695255279541
0.0005967617034912109
0.0005047321319580078

**Comment by alextp** [comment]
This is a known issue because n_iter is a python scalar in your example, so this just generates a very large graph. 

The small operations which improve things should just make graph building quicker (afaict).

**Comment by amilsted** [comment]
> 
> 
> This is a known issue because n_iter is a python scalar in your example, so this just generates a very large graph.
> 
> The small operations which improve things should just make graph building quicker (afaict).

`n_iter` is `22` in the example. This is not a "large graph". Also, it is fast in graph mode, but (apparently) *exponentially* slower (space and time) in the `n_iter` variable when using defun. If this is expected behavior I am somewhat flabbergasted!

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.
