### ISSUE TITLE
 Shown unsupported ops after compilling  tf.lite.TFLiteConverter.from_frozen_graph on SSD_Mobilenet_v1_0.75_depth_coco model

### ISSUE THREAD

**Issue by harsh020goyal** [tensorflow/tensorflow#28700]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):Linux Ubuntu 16.04
- TensorFlow installed from (source or binary):source
- TensorFlow version (or github SHA if from source):1.13.1

I tried running TensorflowLite converter as follow:

import tensorflow as tf

graph_def_file="./frozen_inference_graph.pb"
input_arrays=["image_tensor"]
output_arrays=["detection_boxes","detection_scores","num_detections","detection_classes"]
input_tensor={"image_tensor":[1,300,300,3]}

converter = tf.lite.TFLiteConverter.from_frozen_graph(graph_def_file, input_arrays, output_arrays,input_tensor)
converter.target_ops = [tf.lite.OpsSet.TFLITE_BUILTINS,tf.lite.OpsSet.SELECT_TF_OPS]
converter.allow_custom_ops=True
tflite_model = converter.convert()
open("detect.tflite", "wb").write(tflite_model)

Once it is complete, I get the following output of unsupported ops:

NonMaxSuppressionV2,TensorArrayGatherV3,TensorArrayReadV3,Size,Where,Enter,TensorArraySizeV3,LoopCond,Exit,TensorArrayV3.

This is a ssd_mobilenet_v1_0.75_depth_coco model trained through tensorflow object detection API . It is performing well on tensorflow, but it contains ops not supported by TensorflowLite. I have tried several other models from the tensorflow model zoo, and they all have similar unsupported ops.

Downloading link for the .pb file are :
[http://download.tensorflow.org/models/object_detection/ssd_mobilenet_v1_0.75_depth_300x300_coco14_sync_2018_07_03.tar.gz](url)

**Comment by muddham** [comment]
@harsh020goyal Request you to please refer the [link1](https://github.com/tensorflow/tensorflow/issues/25331), [link2](https://github.com/tensorflow/tensorflow/issues/27832). Please try if that helps and let us know how it progresses.

**Comment by harsh020goyal** [comment]
commit Converting unsupported operations - Enter, Exit, Merge, Switch #27832

**Comment by harsh020goyal** [comment]
@commit Converting unsupported operations - Enter, Exit, Merge, Switch  #27832

**Comment by harsh020goyal** [comment]
#27832

**Comment by harsh020goyal** [comment]
@https://github.com/tensorflow/tensorflow/issues/27832

**Comment by harsh020goyal** [comment]
#27832 Converting unsupported operations - Enter, Exit, Merge, Switch

**Comment by harsh020goyal** [comment]
#25331

**Comment by harsh020goyal** [comment]
#25022

**Comment by muddham** [comment]
@harsh020goyal Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
