### ISSUE TITLE
Possible wrong comments in minimax_discriminator_loss

### ISSUE THREAD

**Issue by benmyara** [tensorflow/tensorflow#28701]
## URL(s) with the issue:
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/gan/python/losses/python/losses_impl.py#L468

https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/gan/python/losses/python/losses_impl.py#L477

## Description of issue (what needs changing):

One line 468:     `# -log((1 - label_smoothing) - sigmoid(D(x)))`

Shouldn't it be `-(1-label_smoothing) * log(sigmoid(D(x))` ?
I'm uncertain about the label_smoothing part, but I think the argument of the `log` is wrong.

On line 477: `# -log(- sigmoid(D(G(x))))`
Shouldn't it be `-log(1-sigmoid(D(G(x))`?

**Comment by ymodak** [comment]
@brianwa84 Can you PTAL at this issue? Thanks!

**Comment by brianwa84** [comment]
@joelshor would probably be better

**Comment by brianwa84** [comment]
@joel-shor, that is

**Comment by joel-shor** [comment]
Yes I think you're right. The comment is inconsistent with the function-level description, which is correct. Do you want to change it? Please not that `tf.contrib` will be going away in future version of tensorflow, so it probably makes more sense to change it in `tensorflow_gan` here and here. Do you want to send me a CL to fix this?

https://github.com/tensorflow/gan/blob/master/tensorflow_gan/python/losses/losses_impl.py#L549
https://github.com/tensorflow/gan/blob/master/tensorflow_gan/python/losses/losses_impl.py#L558

Feel free to ignore the label smoothing in the description; it would make more sense to just match the terms in the function-level description.
