### ISSUE TITLE
tfexample_decoder_test.py fails on s390x for dtype float32 and image_format 'raw'

### ISSUE THREAD

**Issue by kbhute-ibm** [tensorflow/tensorflow#28704]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):Linux Ubuntu 16.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:NA
- TensorFlow installed from (source or binary):Source
- TensorFlow version (use command below):1.12.0
- Python version:2.7.12
- Bazel version (if compiling from source):0.15.0
- GCC/Compiler version (if compiling from source): gcc version 5.4.0 20160609
- CUDA/cuDNN version:NA
- GPU model and memory:NA

**Describe the current behavior**
python ./tensorflow/contrib/slim/python/slim/data/tfexample_decoder_test.py TFExampleDecoderTest.testDecodeExampleWithRawEncodingFloatDtype fails

**Describe the expected behavior**
It should pass on s390x like on Intel.

**Code to reproduce the issue**
python ./tensorflow/contrib/slim/python/slim/data/tfexample_decoder_test.py TFExampleDecoderTest.testDecodeExampleWithRawEncodingFloatDtype 

**Other info / logs**
python ./tensorflow/contrib/slim/python/slim/data/tfexample_decoder_test.py TFExampleDecoderTest.testDecodeExampleWithRawEncodingFloatDtype

======================================================================
FAIL: testDecodeExampleWithRawEncodingFloatDtype (__main__.TFExampleDecoderTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./tensorflow/contrib/slim/python/slim/data/tfexample_decoder_test.py", line 242, in testDecodeExampleWithRawEncodingFloatDtype
    image, serialized_example = self.GenerateImage(
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/test_util.py", line 1591, in assertAllClose
    self._assertAllCloseRecursive(a, b, rtol=rtol, atol=atol, msg=msg)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/test_util.py", line 1561, in _assertAllCloseRecursive
    (path_str, path_str, msg)))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/test_util.py", line 1496, in _assertArrayLikeAllClose
    a, b, rtol=rtol, atol=atol, err_msg="\n".join(msgs), equal_nan=True)
  File "/usr/local/lib/python2.7/dist-packages/numpy/testing/utils.py", line 1395, in assert_allclose
    verbose=verbose, header=header, equal_nan=equal_nan)
  File "/usr/local/lib/python2.7/dist-packages/numpy/testing/utils.py", line 778, in assert_array_compare
    raise AssertionError(msg)
AssertionError:
Not equal to tolerance rtol=1e-06, atol=0
Mismatched value: a is different from b.
not close where = (array([0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1]), array([0, 0, 1, 1, 1, 2, 2, 2, 0, 0, 0, 1, 1, 1, 2, 2, 2]), array([1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2]))
not close lhs = [  1.   2.   3.   4.   5.   6.   7.   8.   9.  10.  11.  12.  13.  14.  15.
  16.  17.]
not close rhs = [  4.60060299e-41   8.96831017e-44   2.30485571e-41   4.60074312e-41
   5.74868682e-41   6.89663052e-41   8.04457422e-41   9.10844002e-44
   5.83080291e-42   1.15705214e-41   1.73102399e-41   2.30499584e-41
   2.87896769e-41   3.45293955e-41   4.02691140e-41   4.60088325e-41
   4.88786917e-41]
not close dif = [  1.   2.   3.   4.   5.   6.   7.   8.   9.  10.  11.  12.  13.  14.  15.
  16.  17.]
not close tol = [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
dtype = float32, shape = (2, 3, 3)
(mismatch 94.4444444444%)
 x: array([[[  0.,   1.,   2.],
        [  3.,   4.,   5.],
        [  6.,   7.,   8.]],...
 y: array([[[  0.000000e+00,   4.600603e-41,   8.968310e-44],
        [  2.304856e-41,   4.600743e-41,   5.748687e-41],
        [  6.896631e-41,   8.044574e-41,   9.108440e-44]],...

----------------------------------------------------------------------
Ran 1 test in 2.034s

FAILED (failures=1)

**Comment by kbhute-ibm** [comment]
In this test case https://github.com/tensorflow/tensorflow/blob/bcee53ab6f4131b6d5a4061c0ad2f2a48e286b90/tensorflow/contrib/slim/python/slim/data/tfexample_decoder_test.py#L233 , image and decoded_image do not match on BE, however on LE, it matches. While debugging more observed that, `image.dtype.str` is `>f4` on s390x however on Intel, its `<f4`. This shows byte ordering of NumPy array is interpreted according to machine endianness. If byte ordering of `image` array is modified in GenerateImage function as below:

```diff
+import sys
@@ -93,7 +93,14 @@ class TFExampleDecoderTest(test.TestCase):
     num_pixels = image_shape[0] * image_shape[1] * image_shape[2]
     image = np.linspace(
         0, num_pixels - 1,
        num=num_pixels).reshape(image_shape).astype(image_dtype)

+  # If machine is big endian, change the byte ordering 
+  # so that it should be interpreted correctly.
+    if image_dtype == np.float32 and sys.byteorder == "big":
+      image = image.astype('<f4')
     tf_encoded = self._Encoder(image, image_format)
```

With this change, dtype and data values remain same for image array. image and decoded_image arrays match. @martinwicke @mrry @gunan Please let me know your inputs in this and if I can do PR for this. 

Also I am curious to know what is the real time use case where this functionality can be encountered?

**Comment by kbhute-ibm** [comment]
In this test case https://github.com/tensorflow/tensorflow/blob/bcee53ab6f4131b6d5a4061c0ad2f2a48e286b90/tensorflow/contrib/slim/python/slim/data/tfexample_decoder_test.py#L233 , image and decoded_image do not match on BE, however on LE, it matches. While debugging more observed that, `image.dtype.str` is `>f4` on s390x however on Intel, its `<f4`. This shows byte ordering of NumPy array is interpreted according to machine endianness. If byte ordering of `image` array is modified in GenerateImage function as below:

```diff
+import sys
@@ -93,7 +93,14 @@ class TFExampleDecoderTest(test.TestCase):
     num_pixels = image_shape[0] * image_shape[1] * image_shape[2]
     image = np.linspace(
         0, num_pixels - 1,
        num=num_pixels).reshape(image_shape).astype(image_dtype)

+  # If machine is big endian, change the byte ordering 
+  # so that it should be interpreted correctly.
+    if image_dtype == np.float32 and sys.byteorder == "big":
+      image = image.astype('<f4')
     tf_encoded = self._Encoder(image, image_format)
```

With this change, dtype and data values remain same for image array. image and decoded_image arrays match. @martinwicke @mrry @gunan Please let me know your inputs in this and if I can do PR for this. 

Also I am curious to know what is the real time use case where this functionality can be encountered?

**Comment by kbhute-ibm** [comment]
Hi @ymodak,
Could you please put your inputs on this?

**Comment by kbhute-ibm** [comment]
Hi @ymodak @martinwicke @mrry Could you please share your thoughts on the proposed change?

**Comment by martinwicke** [comment]
Is changing the test the right way to do this or should this be fixed inside _Encoder?

Or should it be fixed in `constant`?

**Comment by kbhute-ibm** [comment]
Hi @martinwicke,
The fix can be kept in _Encoder function but its defined in same test [here](https://github.com/tensorflow/tensorflow/blob/6db4b700fe1a286cc4dda030c1044dcc6c9919b2/tensorflow/contrib/slim/python/slim/data/tfexample_decoder_test.py#L66). We can not fix it inside `constant` because dtype conversion has to be done before calling tostring() on `image` https://github.com/tensorflow/tensorflow/blob/6db4b700fe1a286cc4dda030c1044dcc6c9919b2/tensorflow/contrib/slim/python/slim/data/tfexample_decoder_test.py#L75

The diff looks like below in case of _Encoder:

```diff
+import sys
 from tensorflow.contrib.slim.python.slim.data import tfexample_decoder
 from tensorflow.core.example import example_pb2
 from tensorflow.core.example import feature_pb2
@@ -72,6 +72,9 @@ class TFExampleDecoderTest(test.TestCase):
       tf_image = constant_op.constant(image, dtype=dtypes.uint8)
       return image_ops.encode_png(tf_image)
     if image_format in ['raw', 'RAW']:
+      #If machine is big endian, change the byte ordering
+      if image.dtype == np.float32 and sys.byteorder == "big":
+        image = image.astype('<f4')
       return constant_op.constant(image.tostring(), dtype=dtypes.string)

   def GenerateImage(self, image_format, image_shape, image_dtype=np.uint8):
```

Please let us know your inputs.

**Comment by martinwicke** [comment]
I'm fine with either fix, if you want to make a PR, we'll merge it. 

I'm only concerned that this is fixing the test and not the underlying issue, but I don't have a great solution for that.

**Comment by kbhute-ibm** [comment]
Thanks @martinwicke We have raised a PR for the above changes. Please find it here https://github.com/tensorflow/tensorflow/pull/29527.
