### ISSUE TITLE
gcloud ai-platform fails with TFv2 Saved Model

### ISSUE THREAD

**Issue by ehennis** [tensorflow/tensorflow#28708]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No.
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10 and Google Colab
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): Binary
- TensorFlow version (use command below):  v1.12.0-9492-g2c319fb415 2.0.0-alpha0
- Python version: 3.6.7
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
I am following this tutorial: https://cloud.google.com/ml-engine/docs/tensorflow/deploying-models and using a model I created in TFv2. I am able to create the Saved_Model in my Colab using the following code:
```
import time
saved_model_path = "/content/gdrive/My Drive/Colab Notebooks/{}".format(int(time.time()))
tf.keras.experimental.export_saved_model(restored_model, saved_model_path)
```
This created a folder with the PB file and assets and variables folder. I then upload that to my bucket in the Google Cloud. I then ran the command to predict:
`gcloud ai-platform local predict --model-dir=$MODEL_DIR --text-instances ci.txt --framework TENSORFLOW`
The ci.txt is a comma separated list of my input numbers.
I get the following error that shows my values:

> Traceback (most recent call last):
>   File "lib/googlecloudsdk/command_lib/ml_engine/local_predict.py", line 184, in <module>
>     main()
>   File "lib/googlecloudsdk/command_lib/ml_engine/local_predict.py", line 179, in main
>     signature_name=args.signature_name)
>   File "/google/google-cloud-sdk/lib/third_party/ml_sdk/cloud/ml/prediction/prediction_lib.py", line 102, in local_predict
>     predictions = model.predict(instances, signature_name=signature_name)
>   File "/google/google-cloud-sdk/lib/third_party/ml_sdk/cloud/ml/prediction/prediction_utils.py", line 268, in predict
>     preprocessed, stats=stats, **kwargs)
>   File "/google/google-cloud-sdk/lib/third_party/ml_sdk/cloud/ml/prediction/frameworks/tf_prediction_lib.py", line 363, in predict
>     "Exception during running the graph: " + str(e))
> cloud.ml.prediction.prediction_utils.PredictionError: Failed to run the provided model: Exception during running the graph: invalid literal for float(): 81,71,80,76,1,3 (Error code: 2)

**Describe the expected behavior**
I expect the code to return a single number.

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.
Here is the saved_model: 
[ver1.zip](https://github.com/tensorflow/tensorflow/files/3178529/ver1.zip)

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by gadagashwini** [comment]
@ehennis Can you recheck and confirm that your cpu supports AVX2?

**Comment by ehennis** [comment]
I built the model in Google Colab and exported there as well. Does my computer supporting that matter?

If it does, I am running Windows 10 and couldn't find an easy way to determine if my cpu supports that. I did see a place to run a check in C++ code.

**Comment by ymodak** [comment]
@ehennis This issue is more suitable on [Google Cloud AI Platform](https://github.com/GoogleCloudPlatform/cloudml-samples/issues). Please post it on [Google Cloud AI Platform](https://github.com/GoogleCloudPlatform/cloudml-samples/issues). Thanks!

**Comment by ehennis** [comment]
Created ticket 420

https://github.com/GoogleCloudPlatform/cloudml-samples/issues/420
