### ISSUE TITLE
Keep version fixed when searching API docs

### ISSUE THREAD

**Issue by ianhellstrom** [tensorflow/tensorflow#28706]
When using the search bar in the [API docs](https://www.tensorflow.org/versions/r1.13/api_docs/python/tf) with a version in the URL, any search will include pages from different API versions, which means you often end up in the wrong module and have to click on the correct version _again_.

## How to reproduce

- Go to: https://www.tensorflow.org/versions/r1.13/api_docs/python/tf
- Type in 'unsorted_segment_' and wait for the results to appear (see image)
- Choose the top 'Pages' result
- You're now in the 1.9 API rather than 1.13. 

<img width="394" alt="Screenshot 2019-05-14 at 16 13 38" src="https://user-images.githubusercontent.com/49023008/57705141-8d8a4600-7663-11e9-8640-5a3fdde51ae8.png">

**Comment by jvishnuvardhan** [comment]
@ianhellstrom I see 1.13.1 on top of the results. Could you check again or let me know if I am making any mistake. Here is the screenshot. Thanks!

unsorted_segment_
<img width="914" alt="Screen Shot 2019-05-22 at 8 14 34 PM" src="https://user-images.githubusercontent.com/46058173/58223447-8819a500-7cce-11e9-827a-d1ce53a8111a.png">

**Comment by Saduf2019** [comment]
@ianhellstrom Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Comment by MarkDaoust** [comment]
Hi @ianhellstrom 

We've hidden all the old versions of the docs from search. We've also moved most of the old versions off the site, Into [branches on the tensorflow_docs repository](https://github.com/tensorflow/docs/tree/r1.9/site/en/api_docs).

So I think this is fixed.
