### ISSUE TITLE
ValueError: Invalid tensors 'outputs' were found when converting from .pb to .tflite

### ISSUE THREAD

**Issue by anonym24** [tensorflow/tensorflow#28729]
I successfully retrained mobilenet quantized model (`architecture="mobilenet_1.0_128_quantized"`) with my own image dataset:

    python3 -m scripts.retrain \
      --bottleneck_dir=tf_files/bottlenecks_quant \
      --how_many_training_steps=50000 \
      --model_dir=tf_files/models/ \
      --summaries_dir=tf_files/training_summaries/"mobilenet_1.0_128_quant" \
      --output_graph=tf_files/retrained_graph_50000_1.0_128.pb \
      --output_labels=tf_files/retrained_labels.txt \
      --architecture="mobilenet_1.0_128_quantized" \
      --image_dir=images

When I try to convert .pb file to .tflite using

    toco \
      --graph_def_file=tf_files/retrained_graph_50000_1.0_128.pb \
      --output_file=tf_files/retrained_graph_50000_1.0_128.tflite \
      --input_format=TENSORFLOW_GRAPHDEF --output_format=TFLITE \
      --inference_type=QUANTIZED_UINT8 \
      --input_shape="1,128,128,3" \
      --input_array=input \
      --output_array=outputs \
      --std_dev_values=127.5 --mean_value=127.5

It fails with the next error:

> ValueError: Invalid tensors 'outputs' were found.

Script uses this link to download mobilenet model: http://download.tensorflow.org/models/mobilenet_v1_1.0_128_frozen.tgz

```
data_url = 'http://download.tensorflow.org/models/mobilenet_v1_'
data_url += version_string + '_' + size_string + '_frozen.tgz'
```

**Comment by ymodak** [comment]
What version of TF are you using? Also can you use ```tflite_convert``` to convert your model?

**Comment by ymodak** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Comment by Ehtasha** [comment]
@anonym24  I'm also facing same issue.

Did you resolve this issue ?
