### ISSUE TITLE
Wrong MD5 checksum for flatbuffers when building Tensorflow Lite Micro using make

### ISSUE THREAD

**Issue by jenselo** [tensorflow/tensorflow#28735]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 16.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): Source
- TensorFlow version: ba63891c8b
- Python version: NA
- Installed using virtualenv? pip? conda?: NA
- Bazel version (if compiling from source): NA
- GCC/Compiler version (if compiling from source): NA
- CUDA/cuDNN version: NA
- GPU model and memory: NA

**Describe the problem**
When running
make -f tensorflow/lite/experimental/micro/tools/make/Makefile test
the command fails when downloading the flatbuffers archive, since there is a mismatch with the MD5 sums.

**Provide the exact sequence of commands / steps that you executed before running into the problem**
make -f tensorflow/lite/experimental/micro/tools/make/Makefile test

**Any other info / logs**
tensorflow/lite/experimental/micro/tools/make/download_and_extract.sh "https://github.com/google/gemmlowp/archive/719139ce755a0f31cbf1c37f7f98adcc7fc9f425.zip" "7e8191b24853d75de2af87622ad293ba" tensorflow/lite/experimental/micro/tools/make/downloads/gemmlowp                        
downloading https://github.com/google/gemmlowp/archive/719139ce755a0f31cbf1c37f7f98adcc7fc9f425.zip
tensorflow/lite/experimental/micro/tools/make/download_and_extract.sh "http://mirror.tensorflow.org/github.com/google/flatbuffers/archive/v1.11.0.tar.gz" "3811552512049fac3af419130904bc55" tensorflow/lite/experimental/micro/tools/make/downloads/flatbuffers                           
downloading http://mirror.tensorflow.org/github.com/google/flatbuffers/archive/v1.11.0.tar.gz
Checksum error for 'http://mirror.tensorflow.org/github.com/google/flatbuffers/archive/v1.11.0.tar.gz'. Expected 3811552512049fac3af419130904bc55 but found 02c64880acb89dbd57eebacfd67200d8                                                                                               
tensorflow/lite/experimental/micro/tools/make/Makefile:198: recipe for target 'tensorflow/lite/experimental/micro/tools/make/downloads/flatbuffers' failed                                                                                                                                 
make: *** [tensorflow/lite/experimental/micro/tools/make/downloads/flatbuffers] Error 1

**Comment by jenselo** [comment]
Here's a PR that fixes the issue: https://github.com/tensorflow/tensorflow/pull/28736

**Comment by mihaimaruseac** [comment]
Thank you for the PR. Now that it landed, I think this can be closed.
