### ISSUE TITLE
use GradientTape to compute gradient cost all memory

### ISSUE THREAD

**Issue by jjjjjie** [tensorflow/tensorflow#28730]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):Linux Ubuntu 16.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):pip3
- TensorFlow version (use command below): v1.13.1-0-g6612da8951' 1.13.1
- Python version:3.5.2
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 10.0.130/ 7.5.0
- GPU model and memory: GeForce GTX 1060 5GB

**Describe the current behavior**

When i use tf.GradientTape to compute gradients, it will use all gpu memory even though I use GPUoption in session.

**Describe the expected behavior**

GPU memory should be controled

**Code to reproduce the issue**

```
import tensorflow as tf

def mul(x):
    y = tf.layers.dense(x, 3)
    return y

x = tf.placeholder(tf.float32, [None, 2])

with tf.GradientTape() as gg:
    gg.watch(x)
    f_eval = mul(x)
    grad = gg.gradient(f_eval, x)
del gg


gpu_options = tf.GPUOptions(per_process_gpu_memory_fraction=0.2)
sess = tf.InteractiveSession(config=tf.ConfigProto(gpu_options=gpu_options))
sess.run(tf.global_variables_initializer())
import time
time.sleep(5)
```

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

> Observing memory usage, it always use more than 4100MB memory because my GPU only has 5G memory.

**Comment by muddham** [comment]
@jjjjjie Can you please update to tf-nightly. I ran the code in tf-nightly, did not receive any out of memory issues

**Comment by jjjjjie** [comment]
@muddham What is your GPU memory cost in nvidia-smi when code is running?

**Comment by jvishnuvardhan** [comment]
@jjjjjie You need to close the session that you opened. Please check the [gist](https://colab.sandbox.google.com/gist/jvishnuvardhan/b9f3354f00098b813437902a36166d9c/untitled188.ipynb). Thanks!

**Comment by jjjjjie** [comment]
@jvishnuvardhan Thanks for your reply, Maybe I didn’t express my issue clearly, I mean this op always cost all GPU memory although I set this option: 
`gpu_options = tf.GPUOptions(per_process_gpu_memory_fraction=0.2)`
I think   tf.GPUOptions should control this session can take up  less than 20% of the memory but it always take up 100%. This is my confusion, not after session is finish. Thanks!

**Comment by aaroey** [comment]
It seems to me that tf.GradientTape will use the eager context which contains a default ConfigProto different than the one used in the Session API. 

@jaingaurav, can you comment?

**Comment by jjjjjie** [comment]
@aaroey Thanks! So it means if I want to control gpu usage of tf.GradientTape I must use eager mode?

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.

**Comment by jvishnuvardhan** [comment]
@jjjjjie Is this still an issue for you? I ran it in colab gpu environment with `TF1.15.5` and I didn't notice full gpu memory. [Here](https://colab.research.google.com/gist/jvishnuvardhan/27f403d734c1e084e87c09dcc4e89819/untitled987.ipynb) is a gist for our reference. Thanks!

Please note we are no longer supporting `TF1.x` version. Can you please check and open a new issue if the issue persists with `TF2.x` versions.  Thanks!
