### ISSUE TITLE
Tensorflow Type error when trying to iterate the Tensors in loop

### ISSUE THREAD

**Issue by JafferWilson** [tensorflow/tensorflow#28732]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
 Yes. It is mentioned as above in the code. I want to go as it is with loop and conditions. I know there are short hand functions but I want to customize it my way later during the go.
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
Windows 10 Desktop
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
No it did not as I am using Desktop system for the development
- TensorFlow installed from (source or binary):
Using Pip on Python 3.5.0 64 bit
- TensorFlow version (use command below):
Tensorflow version is 1.12.0
- Python version:
Python 3.5.0
- Bazel version (if compiling from source): ?
- GCC/Compiler version (if compiling from source):?
- CUDA/cuDNN version: No usng CPU version
- GPU model and memory: There isn't any as I faced issue during the go.
I have the following scenario:

```
y = tf.placeholder(tf.float32, [None, 1],name="output")
layers = [tf.contrib.rnn.BasicRNNCell(num_units=n_neurons,activation=tf.nn.leaky_relu, name="layer"+str(layer))
         for layer in range(2)]
multi_layer_cell = tf.contrib.rnn.MultiRNNCell(layers)
rnn_outputs, states = tf.nn.dynamic_rnn(multi_layer_cell, X, dtype=tf.float32)
stacked_rnn_outputs = tf.reshape(rnn_outputs, [-1, 100]) 
stacked_outputs = tf.layers.dense(stacked_rnn_outputs, 1)
outputs = tf.reshape(stacked_outputs, [-1, 2, 1])
outputs = tf.identity(outputs[:,1,:], name="prediction")
loss = Custom_loss(y,outputs)
optimizer = tf.train.AdamOptimizer(learning_rate=learning_rate) 
training_op = optimizer.minimize(loss,name="training_op")
```
The custom loss function I tried is:

```
def Custom_loss(y,outputs):
    hold_loss = []
    for exp,pred in zip(y,outputs):
        if exp >= pred:
            result = tf.pow(pred * 0.5,2) - exp
            hold_loss.append(result)
        else:
            hold_loss.append(tf.subtract(pred-exp))
    return tf.reduce_mean(hold_loss)
```
Now when I am trying to implement this I am getting the following error:

`TypeError: Tensor objects are only iterable when eager execution is enabled. To iterate over this tensor use tf.map_fn.`
I have tried implementing the tf.map_fn() but there is the same error I encounter. I have used the following question:
[How to explain the result of tf.map_fn?](https://stackoverflow.com/questions/46096767/how-to-explain-the-result-of-tf-map-fn)

Kindly, help me get through this issue? How I can iterate the tensor? What way is best for the custom loss function implementation?
I am willing to have the custom function become a part of the graph so that I can train it effectively.

**Comment by ymodak** [comment]
The code snippet you provided looks incomplete. Can you please edit the issue and update the minimal code snippet to reproduce the issue reported. Thanks!

**Comment by JafferWilson** [comment]
@ymodak Ok lets take a lok at the following scenario with the minimal code snippet.
```
import tensorflow as tf
import numpy as np
def Custom_loss(y,outputs):
    hold_loss = []
    for exp,pred in zip(y,outputs):
        if exp >= pred:
            result = tf.pow(pred * 0.5,2) - exp
            hold_loss.append(result)
        else:
            hold_loss.append(tf.subtract(pred-exp))
    return tf.reduce_mean(hold_loss)
np_x = np.random.randn(100)
np_y = np.random.randn(100)

x = tf.constant(np_x)
y = tf.constant(np_y)

with tf.Session() as sess:
   assert sess.run(Custom_loss(x, y))
```
I guess that this will help.

**Comment by alextp** [comment]
@JafferWilson your question about map_fn seems to have been answered correctly.

Again, to iterate over a tensor either use tf.function (available in nightly, tf2 alpha, and soon-to-be-released 1.14), eager execution, or map_fn.

**Comment by JafferWilson** [comment]
@alextp I guess no one answered anything here. Where is the answer? I guess you were in a hurry of closing the issue and forgot to answer.
Please let me know what is the right way. You see in the above conversation I have received message that my answer is not minimal. Please let me know as I have mention the sample code to ya.

**Comment by alextp** [comment]
What I meant is that if you just use tf.map_fn like the code below it works:

```python
import tensorflow as tf
import numpy as np
def Custom_loss(y,outputs):
    hold_loss = []
    def f(a):
      exp, pred = a
      return tf.cond(exp >= pred, lambda: tf.pow(pred * 0.5, 2) - exp, lambda: (pred-exp))
    hold_loss = tf.map_fn(f, (y, outputs), dtype=tf.float64)
    return tf.reduce_mean(hold_loss)
np_x = np.random.randn(100)
np_y = np.random.randn(100)

x = tf.constant(np_x)
y = tf.constant(np_y)

with tf.Session() as sess:
   assert sess.run(Custom_loss(x, y))
```

**Comment by JafferWilson** [comment]
@alextp Thank you for the help.
