### ISSUE TITLE
TFLite only slightly faster with GPU on Helio P22

### ISSUE THREAD

**Issue by munum** [tensorflow/tensorflow#28742]
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): n/a
- Mobile device: **Xiaomi Redmi 6**
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below): r1.13
- Python version: n/a
- Bazel version (if compiling from source): n/a
- GCC/Compiler version (if compiling from source): n/a
- CUDA/cuDNN version: n/a
- GPU model and memory: **PowerVR GE8320**

**Describe the current behavior**

Running the [TFLite Demo](https://github.com/tensorflow/tensorflow/tree/6d28416/tensorflow/lite/java/demo), average inference time for 1 thread is **480ms**, but it's just **370ms** with GPU. With 4 threads, it's **360ms**.

**Describe the expected behavior**

I'd expect GPU performance to be (significantly) better than 4-thread CPU. Granted it's not a great GPU, but I'd expect it to be substantially faster than the CPU.

**Other info / logs**

Xiaomi Redmi 6:
- OS | Android 8.1 (Oreo), planned upgrade to Android 9.0 (Pie)
- Chipset | Mediatek MT6762 Helio P22 (12 nm)
- CPU | Octa-core 2.0 GHz Cortex-A53
- GPU | PowerVR GE8320

**Comment by impjdi** [comment]
@munum 

Do you get a warning like

> WARNING: op code #42 cannot be handled by this delegate.

?

**Comment by hoonkai** [comment]
> @munum
> 
> Do you get a warning like
> 
> > WARNING: op code #42 cannot be handled by this delegate.
> 
> ?

No. I'm just using the demo app, the models of which I believe contain only supported ops.

> Also, are you using FP16?

I'm using the demo app's default options.

**Comment by tgpsantos** [comment]
Hey :) Were you able to improve the performance with GPU?

**Comment by impjdi** [comment]
Unfortunately not.  We're making some plumbing to improve parallelism of certain ops.  With a lot of people on vacation, it's going slow.

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this issue, as you are using an older version of tensorflow(1.x) which is officially considered as end of life. We recommend that you upgrade to 2.4 or later version and let us know if the issue still persists in newer versions. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, Please open a new issue for any help you need against 2.x, and we will get you the right help.
