### ISSUE TITLE
Parallel 2 conv layer but got the same time consumption as serial

### ISSUE THREAD

**Issue by tansor** [tensorflow/tensorflow#28740]
Hi,
I'm trying to study the parallelization of static graphs, so I realize tensorflow codes with 2 convolution layers taking the same input.
Here's my code with tensorflow 1.12.0.
```
import os
import time
import math
import numpy as np
import tensorflow as tf

os.environ["CUDA_DEVICE_ORDER"] = "PCI_BUS_ID"
os.environ["CUDA_VISIBLE_DEVICES"] = "0"

def test(m, session, feed_dict, t):
    for i in range(t):
        session.run([m.y, m.z], feed_dict=feed_dict)

def main():
    m = Model()
    session = tf.Session()
    session.run(m.init_op)
    feed_dict = {
        m.x: np.zeros([4, 56, 56, 32]),
    }
    print('hot')
    test(m, session, feed_dict, 100)
    print('start')
    start = time.time()
    test(m, session, feed_dict, 10000)
    print((time.time()-start) / 10000 * 1000)

class Model:
    def _conv_layer(self, name, input_var, stride, in_channels, out_channels):
        KERNEL_SIZE = 3
        with tf.variable_scope(name) as scope:
            filter_shape = [KERNEL_SIZE, KERNEL_SIZE, out_channels, in_channels]
            kernel = tf.get_variable(
                'weights',
                shape=filter_shape,
                initializer=tf.truncated_normal_initializer(stddev=math.sqrt(2.0 / KERNEL_SIZE / KERNEL_SIZE / in_channels)),
                dtype=tf.float32
            )
            biases = tf.get_variable(
                'biases',
                shape=[out_channels],
                initializer=tf.constant_initializer(0.0),
                dtype=tf.float32
            )
            output = tf.nn.bias_add(
                tf.nn.conv2d(
                    input_var,
                    kernel,
                    [1, stride, stride, 1],
                    padding='SAME'
                ),
                biases
            )
            return output

    def __init__(self):
        tf.reset_default_graph()
        self.x = tf.placeholder(tf.float32, [None, 56, 56, 32])

        self.y = self._conv_layer('layer', self.x, 1, 32, 32)
        self.z = self._conv_layer('layer2', self.x, 1, 32, 32)

        self.init_op = tf.initialize_all_variables()

if __name__ == '__main__':
    main()
```
The time consumption is the same as `self.z = self._conv_layer('layer2', self.y, 1, 32, 32)` (note the `self.y`), so that confuse me about the parallel performance of tensorflow, can any body help to explain that or realize the true parallel way of 2 conv layers (in a single gpu) ?

**Comment by achandraa** [comment]
Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow cpu/gpu version used. Did you try it from source or binary? How much time it took for parallel and serial time consumption. If you are unclear on the template, please use [template link](https://github.com/tensorflow/tensorflow/issues/new/choose) to fill in the details. Thanks!

**Comment by tansor** [comment]
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 16.04
- TensorFlow installed from (source or binary): python-pip
- TensorFlow version (use command below): 1.12.0
- Python version: python3.5
- CUDA/cuDNN version: CUDA 9.0.176, cuDNN 7.4.1
- GPU model and memory: NVidia 1080Ti, 11G
- Parallel or Serial time consumption: Same, about 3 ms both

**Comment by achandraa** [comment]
Tried verifying on Colab with TensorFlow version 1.13.1 (CPU and GPU), found significant time consumption difference between the two. Can you please help me out to know whether the result is consistent with you also or not with the same version. Thanks!

**Comment by achandraa** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
