### ISSUE TITLE
[tensorflow/docs]Translate variables.md from English to Chinese.

### ISSUE THREAD

**Issue by Mr-Nineteen** [tensorflow/tensorflow#28762]
Thank you for submitting a TensorFlow documentation issue. Per our GitHub
policy, we only address code/doc bugs, performance issues, feature requests, and
build/installation issues on GitHub.

The TensorFlow docs are open source! To get involved, read the documentation
contributor guide: https://www.tensorflow.org/community/contribute/docs

## URL(s) with the issue:

Please provide a link to the documentation entry, for example:
https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/MyMethod

### Clear description

For example, why should someone use this method? How is it useful?

### Correct links

Is the link to the source code correct?

### Parameters defined

Are all parameters defined and formatted correctly?

### Returns defined

Are return values defined?

### Raises listed and defined

Are the errors defined? For example,
https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/feature_column/categorical_column_with_vocabulary_file#raises

### Usage example

Is there a usage example?

### Request visuals, if applicable

Are there currently visuals? If not, will it clarify the content?

### Submit a pull request?

Are you planning to also submit a pull request to fix the issue? See the docs
contributor guide: https://www.tensorflow.org/community/contribute/docs and the
docs style guide: https://www.tensorflow.org/community/contribute/docs_style

**Comment by dynamicwebpaige** [comment]
This would be a great project for an upcoming global TensorFlow Docs Sprint, or for the Chinese translation group. cc: @lamberta

**Comment by lamberta** [comment]
Yes! Consider joining the [Chinese docs list](https://groups.google.com/a/tensorflow.org/forum/#!forum/docs-zh-cn): docs-zh-cn@tensorflow.org 

@duanw0916 is coordinating some Chinese translation efforts, perhaps he can point you in the right direction?

**Comment by jvishnuvardhan** [comment]
@Mr-Nineteen Is there any actionable item like raising PR? 

Since the issue opened, there were lot of improvements in the TF docs of several languages but `variables.md` is not there. 

Can we close this issue here. Thanks
