### ISSUE TITLE
Name of losses.Reduction.SUM_BY_NONZERO_WEIGHTS is misleading

### ISSUE THREAD

**Issue by hannagabor** [tensorflow/tensorflow#28763]
**Describe the current behavior**
`losses.Reduction.SUM_BY_NONZERO_WEIGHTS` calculates the mean, not the sum. (The behavior is in sync with the [docs](https://www.tensorflow.org/api_docs/python/tf/losses/Reduction).)
**Describe the expected behavior**
I would expect `losses.Reduction.SUM_BY_NONZERO_WEIGHTS` to calculate the sum, not the mean.

**Comment by amahendrakar** [comment]
@hannagabor,
As per [this documentation page](https://www.tensorflow.org/api_docs/python/tf/compat/v1/losses/Reduction), `SUM_BY_NONZERO_WEIGHTS` is deprecated. Currently, [tf.keras.losses.Reduction](https://www.tensorflow.org/api_docs/python/tf/keras/losses/Reduction) has the value `SUM_OVER_BATCH_SIZE`.

Marking the issue as closed. Please feel free to re-open if necessary. Thanks!
