### ISSUE TITLE
cannot really use eager execution to see tensors inside of a layer.

### ISSUE THREAD

**Issue by zadeck** [tensorflow/tensorflow#28779]
i am using tf-nightly-gpu-2.0-preview dev20190516 on ubuntu 18.04.

whenever I try to convert a tensor into a numpy array from inside the "call" function of a custom keras layer i get the following stack trace when I start execution:

  File "<stdin>", line 1, in <module>
  File "/home/zadeck/learning/tfkeras/interrow/trainPlant.py", line 101, in main
    modelObj.add (recLayer)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/tracking/base.py", line 457, in _method_wrapper
    result = method(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/sequential.py", line 192, in add
    output_tensor = layer(self.outputs[0])
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/base_layer.py", line 629, in __call__
    outputs = call_fn(inputs, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/autograph/impl/api.py", line 90, in wrapper
    ), args, kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/autograph/impl/api.py", line 377, in converted_call
    result = converted_f(*effective_args, **kwargs)
  File "/tmp/tmp1ojmi3gq.py", line 9, in tf__call
    ag__.converted_call('plotPicture', viewImage, ag__.ConversionOptions(recursive=True, force_conversion=False, optional_features=(), internal_convert_user_code=True), (ag__.converted_call('numpy', x, ag__.ConversionOptions(recursive=True, force_conversion=False, optional_features=(), internal_convert_user_code=True), (), None), 0), None)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/autograph/impl/api.py", line 219, in converted_call
    f = getattr(owner, f)
AttributeError: 'Tensor' object has no attribute 'numpy'

This happens very early in my eager execution as if someone behind the scenes is calling the compiler on each layer before execution begins.   If i try to use the numpy attribute outside of the keras layers i have no problem.   

I do not explicitly call the "compile" function for my model.

I am able to trick the system into making this work hiding the access to the numpy call inside of an indirect function call.

code within keras layer that works properly:

def build (self, input_shape):
    ...
    self.indirect = self.nothing

def call (self, x):
    self.indirect (x)
    self.indirect = self.useXnumpy

def nothing (self, x):
    y = 1

def useXnumpy (self, x):
    ... =  x.numpy ()

what does not work is either have the call to x.numpy () directly in the "call" function for a keras layer or to directly call the useXnumpy routine from the "call" function of a keras layer.   Having the indirect call fools the compiler or preprocessor sufficiently to allow the values to be executed.   

I do not know if the real bug is that the preprocessing step should not be executed on the layer when in eager mode or if it simply needs to be told that calling numpy() is ok on tensors.     

I do know that i am in eager mode because i have no problem accessing the numpy function on tensors inside the loss function.    it is simply trying to do that from within a keras layer that causes problems.

**Comment by achandraa** [comment]
Will it be possible to provide minimal code snippet that can reproduce the issue. It would definitely help us to debug the issue faster. Thanks!

**Comment by zadeck** [comment]
try this:
================
lorien:~/work(44) python3
Python 3.6.7 (default, Oct 22 2018, 11:32:17) 
[GCC 8.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tfkeras.bugs.badnumpy as bn
>>> bn.main ()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/zadeck/learning/tfkeras/bugs/badnumpy.py", line 24, in main
    modelObj.add (myLayer)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/tracking/base.py", line 457, in _method_wrapper
    result = method(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/sequential.py", line 192, in add
    output_tensor = layer(self.outputs[0])
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/base_layer.py", line 629, in __call__
    outputs = call_fn(inputs, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/autograph/impl/api.py", line 90, in wrapper
    ), args, kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/autograph/impl/api.py", line 377, in converted_call
    result = converted_f(*effective_args, **kwargs)
  File "/tmp/tmpze72bong.py", line 6, in tf__call
    print(ag__.converted_call('numpy', x, ag__.ConversionOptions(recursive=True, force_conversion=False, optional_features=(), internal_convert_user_code=True), (), None))
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/autograph/impl/api.py", line 219, in converted_call
    f = getattr(owner, f)
AttributeError: 'Tensor' object has no attribute 'numpy'
>>> 
===========================
badnumpy.py follows
===========================
import tensorflow as tf
from tensorflow.keras import backend as B
from tensorflow.keras.models import Sequential
from tensorflow.keras.models import Model
from tensorflow.keras.layers import InputLayer
from tensorflow.keras import optimizers
from tensorflow.keras.layers import Layer


def main ():
    trainData = [1.,2.,3.,4.,5.,6.,7.,8.]
    trainLabel = [1.,2.,3.,4.,5.,6.,7.,8.]

    B.set_floatx('float32')
    B.set_image_data_format('channels_last')

    inputLayer = InputLayer (input_shape = (1),
                             dtype = "float32", name = "InputLayer")
    myLayer = MyLayer ()
    optimizerObj = optimizers.Adam()
    modelObj = Sequential ()
    modelObj.add (inputLayer)
    modelObj.add (myLayer)

    lossObj = MyLoss ()
    
    labelIndex = 0
    lossHistory = []
    for (batchIdx, data) in enumerate(trainData):
        target = trainLabel[batchIdx]
        with tf.GradientTape() as tape:
            logits = modelObj(data, training=True)
            batchLossVec = lossObj(target, logits)

        batchLoss = batchLossVec.numpy ().sum ()
        lossHistory.append(batchLossVec.numpy().mean())
        grads = tape.gradient(batchLossVec, modelObj.trainable_variables)
        optimizer.apply_gradients(zip(grads, modelObj.trainable_variables))

class MyLoss ():
    def __init__(self, *args, **kwargs):
        super(MyLoss, self).__init__(*args, **kwargs)

    def __call__ (self, y_true, y_pred, *args, **kwargs):
        return 1
        
class MyLayer (Layer):
    def __init__(self, *args, **kwargs):
        super(MyLayer, self).__init__(*args, **kwargs)

    def call (self, x):
        print (x.numpy ())

**Comment by ymodak** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow-tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.
