### ISSUE TITLE
batch_util CopySliceToElement does not support uint32, uint64 dtypes

### ISSUE THREAD

**Issue by BryanCutler** [tensorflow/tensorflow#28775]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below): master
- Python version: 3.6
- Bazel version (if compiling from source): 0.25.1
- GCC/Compiler version (if compiling from source): 5.4.0
- CUDA/cuDNN version:
- GPU model and memory:

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**

When batch_util::CopySliceToElement gets a dtype of uint32 or uint64, it fails with error:
`Unimplemented: CopySliceToElement Unhandled data type: 22`  (this is uint32)

This is an issue for using tensor_slice_dataset_op, which can calls this function and should also support these dtypes.

**Describe the expected behavior**
This function should handle these primitive types

**Code to reproduce the issue**
Unit tests in tensor_slice_dataset_op_test.cc fail when these dtypes are added

**Other info / logs**
NA

**Comment by muddham** [comment]
@BryanCutler Please provide simple reproducible code to investigate further.

**Comment by BryanCutler** [comment]
@muddham the additions to the test in #28776 reproduce the issue, but also here is a simple script

```python
c = tf.constant(0, shape=[4, 1, 2], dtype=tf.dtypes.uint32)
ds = tf.data.Dataset.from_tensor_slices(c)
it = ds.make_one_shot_iterator()
n = it.get_next()
with tf.Session() as sess:
    print(sess.run(n))
```

produces error:
```
UnimplementedError (see above for traceback): CopySliceToElement Unhandled data type: 22
	 [[node IteratorGetNext (defined at <ipython-input-9-74466e672a7d>:1) ]]
```
