### ISSUE TITLE
TF Lite can't run example project of select tensorflow operators on iOS

### ISSUE THREAD

**Issue by futuyao** [tensorflow/tensorflow#28778]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): macOS 10.14.5
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): source
- TensorFlow version: r1.13
- Python version: 2.7
- Installed using virtualenv? pip? conda?: N/A
- Bazel version (if compiling from source): 0.19.2
- GCC/Compiler version (if compiling from source): 4.2.1
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

**Describe the problem**

**Provide the exact sequence of commands / steps that you executed before running into the problem**

Following guide: [Select TensorFlow operators to use in TensorFlow Lite](https://www.tensorflow.org/lite/guide/ops_select)

Built with command
`tensorflow/contrib/makefile/build_all_ios_with_tflite.sh -a arm64`

Ran example project in XCode
`tensorflow/lite/examples/ios/camera/tflite_camera_example_with_select_tf_ops.xcodeproj`

Got a list of 20 errors in cstring that look like
`No member named 'memcpy' in the global namespace`
`No member named 'memmove' in the global namespace; did you mean 'remove'?`
`No member named 'strcpy' in the global namespace`
`No member named 'strncpy' in the global namespace`

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by futuyao** [comment]
Is there a commit / branch / tag where I can run this example tflite_camera_example_with_select_tf_ops.xcodeproj successfully?

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.
