### ISSUE TITLE
Conv2D breaking when used with keras Model subclassing

### ISSUE THREAD

**Issue by AakashKumarNain** [tensorflow/tensorflow#28777]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 16.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.0 alpha gpu 
- Python version: 3.6
- Bazel version (if compiling from source):N/A
- GCC/Compiler version (if compiling from source):N/A
- CUDA/cuDNN version:
- GPU model and memory:

**Describe the current behavior**
I am trying to use `tf.keras.Model` subclassing to define my model but it is failing on the first conv layer. Here is the code I am using:

```python

class CustomModel(tf.keras.Model):
  def __init__(self, **kwargs):
    super(CustomModel, self).__init__(**kwargs)
    self.conv1   = Conv2D(32, (3, 3), padding='same')
    self.conv2   = Conv2D(64, (3, 3), padding='same')
    self.pool    = MaxPooling2D(pool_size=(2, 2))
    self.bn      = BatchNormalization()
    self.relu    = Activation("relu")
    self.softmax = Activation("softmax")
    self.drop1   = Dropout(0.25)
    self.drop2   = Dropout(0.5)
    self.dense1  = Dense(512)
    self.dense2  = Dense(10)
    self.flat    = Flatten()
    
  
  
  def call(self, inputs, train):
    z = self.conv1(inputs)
    z = self.bn(z, training=train)
    z = self.relu(z)
    
    z = self.conv1(z)
    z = self.bn(z, training=train)
    z = self.relu(z)
    z = self.pool(z)
    z = self.drop1(z, training=train)
    
    z = self.conv2(z)
    z = self.bn(z, training=train)
    z = self.relu(z)
    
    z = self.conv2(z)
    z = self.bn(z, training=train)
    z = self.relu(z)
    z = self.pool(z)
    z = self.drop1(z, training=train)
    
    z = self.flat(z)
    z = self.dense1(z)
    z = self.relu(z)
    z = self.drop2(z, training=train)
    z = self.dense2(z)
    z = self.softmax(z)
    
    return z
```
In order to check if the model is working fine, I am passing a random input to the model in this way:

```
random_input = np.random.rand(32,32, 3).astype(np.float32)
random_input = np.expand_dims(random_input, axis=0)
preds = model(random_input, train=False)
```

But this throws the following error: `InvalidArgumentError: input depth must be evenly divisible by filter depth: 32 vs 3 [Op:Conv2D]`

The same model works fine with `Sequential/Functional` API. So either I am missing out on something or there is something wrong with the subclassing. Can you please look into it?

**Comment by gadagashwini** [comment]
@AakashKumarNain In order to expedite the trouble-shooting process, please provide a minimum code snippet to reproduce the issue reported here. Thanks!

**Comment by AakashKumarNain** [comment]
@gadagashwini except for the `import` statements, what I have provided is the code snippet

**Comment by gadagashwini** [comment]
@AakashKumarNain Thanks for the information.

**Comment by AakashKumarNain** [comment]
@gadagashwini You are welcome

**Comment by gadagashwini** [comment]
I am able to reproduce the issue on colab with TF 2.0alpha . This is the error message I got InvalidArgumentError: input depth must be evenly divisible by filter depth: 32 vs 3 [Op:Conv2D]

**Comment by AakashKumarNain** [comment]
Any updates on this? I think this is a major bug

**Comment by tanzhenyu** [comment]
Not sure what do you mean by it's working in Functional API...
The problem here is you call:
z = conv1(inputs)
which builds the layer to accepts an input of 3 channels

then you call:
z = conv1(z)
which is an input of 32 channels

This is confusing `conv1`, I think it fails with all subclass/functional/sequential, can you double check?

The error definitely needs improvement, but using colab I do see that the error message is much clearer in 1.14.

**Comment by AakashKumarNain** [comment]
When I say
`z = conv1(z)`, I mean that I want to add another layer that has 32 output channels and a filter of size (3,3). So, `conv1` is a layer with `32` output channels which I should be able to use at multiplt places in my net. Is it clear now?

**Comment by tanzhenyu** [comment]
Like mentioned above, we don't have a layer that accepts dynamic number of channels. If you run conv1 with input of (1, 32, 32, 3), the weight inside layer will be shape of (3, 3, 3, 32), which stands for (kernel_size, kernel_size, input_channels, output_channels). And now you pass another input which is 32 channels, so the weight will have to change shape to (3, 3, 32, 32), it's not possible.

**Comment by tanzhenyu** [comment]
Instead make another conv layer would help fix this

**Comment by AakashKumarNain** [comment]
But then I have to write all the layers in `__init__` and then call every layer in `call` method which doesn't seem optimal to me. Is there any example you can point to for ref?

**Comment by tanzhenyu** [comment]
You can write smaller blocks that does this, for reference, checkout keras applications:
https://github.com/keras-team/keras-applications/blob/master/keras_applications/densenet.py#L93-L120

**Comment by AakashKumarNain** [comment]
I am aware of that but that is `Functional` API which works fine. This one is the case of `subclassing` and `eager` mode

**Comment by tanzhenyu** [comment]
Do you have a minimal code snippet for functional model?

**Comment by AakashKumarNain** [comment]
Yeah sure. Here is the code for functional model:
```
def build_functional_model():
  img_input = Input(shape=(224,224,3))
  x = Conv2D(32, (3,3), activation='relu')(img_input)
  x = Conv2D(32, (3,3), activation='relu')(x)
  x = MaxPooling2D((2,2))(x)
  
  x = Conv2D(64, (3,3), activation='relu')(x)
  x = Conv2D(64, (3,3), activation='relu')(x)
  x = MaxPooling2D((2,2))(x)
  
  x = Flatten()(x)
  x = Dropout(0.25)(x)
  x = Dense(512, activation='relu')(x)
  x = Dropout(0.5)(x)
  x = Dense(10, activation='softmax')(x)
  
  model= Model(img_input, x)
  return model

```
If I write the `custom model` as I have shown above in the original post, which I think is the right way to do it, then it throws the error. If you need to run it by yourself, then you can check out this notbeook: https://colab.research.google.com/drive/1mBf1mErwN0lDEFqu6fQI-SpK7PpSp5Xl

**Comment by tanzhenyu** [comment]
This functional model is completely legitimate because you indeed created two different Conv2D layers, one for input shape (224,224,3), one for (224,224,32)....The subclass model will not work because you're reusing the same layer

**Comment by AakashKumarNain** [comment]
I think we are still not on the same page. Let me try to elaborate it again:
1) I want to build a model using subclassing
2) In my model, I can have one particular type of layer repeated. For example, a `Conv2D` layer with `32` filters can be used in multiple places as shown in the above example.
3) If this isn't the right way to declare all the types of layer I am going to use in my model, can you please show me an example of how to do that?

**Comment by tanzhenyu** [comment]
...Like I have mentioned twice above, if your functional model is doing something like:
x = Conv2D(32, (3, 3), activation='relu')(img_input)
x = Conv2D(32, (3, 3), activation='relu')(x)

then in your subclass model you should do:
self.conv1 = Conv2D(32, (3, 3))
self.conv2 = Conv2D(32, (3, 3))

**Comment by jvishnuvardhan** [comment]
@AakashKumarNain Based on comments from @tanzhenyu , here is the model (modified couple of lines in your code) that works. Please let's know what you think.

```
import os
import glob
import h5py
import math
import shutil


import numpy as np 
from pathlib import Path
import matplotlib.pyplot as plt
import matplotlib.pylab as pl


from tensorflow.keras.models import Sequential, Model, load_model
from tensorflow.keras.applications.resnet50 import ResNet50, preprocess_input
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Dense, Dropout, Activation
from tensorflow.keras.layers import Input, Flatten, SeparableConv2D, BatchNormalization
from tensorflow.keras.optimizers import Adam, SGD, RMSprop
from tensorflow.keras.callbacks import ModelCheckpoint, Callback, EarlyStopping
from tensorflow.keras.utils import to_categorical

from tensorflow.keras import backend as K
import tensorflow as tf

class CustomModel(tf.keras.Model):
  def __init__(self, **kwargs):
    super(CustomModel, self).__init__(**kwargs)
    self.conv1   = Conv2D(32, (3, 3), padding='same')
    self.conv2   = Conv2D(32, (3, 3), padding='same')
    self.conv3   = Conv2D(64, (3, 3), padding='same')
    self.conv4   = Conv2D(64, (3, 3), padding='same')
    self.pool    = MaxPooling2D(pool_size=(2, 2))
    self.bn      = BatchNormalization()
    self.relu    = Activation("relu")
    self.softmax = Activation("softmax")
    self.drop1   = Dropout(0.25)
    self.drop2   = Dropout(0.5)
    self.dense1  = Dense(512)
    self.dense2  = Dense(10)
    self.flat    = Flatten()
    
  
  
  def call(self, inputs, train):
    z = self.conv1(inputs)
    z = self.bn(z, training=train)
    z = self.relu(z)
    
    z = self.conv2(z)
    z = self.bn(z, training=train)
    z = self.relu(z)
    z = self.pool(z)
    z = self.drop1(z, training=train)
    
    z = self.conv3(z)
    z = self.bn(z, training=train)
    z = self.relu(z)
    
    z = self.conv4(z)
    z = self.bn(z, training=train)
    z = self.relu(z)
    z = self.pool(z)
    z = self.drop1(z, training=train)
    
    z = self.flat(z)
    z = self.dense1(z)
    z = self.relu(z)
    z = self.drop2(z, training=train)
    z = self.dense2(z)
    z = self.softmax(z)
    
    return z

model =CustomModel()
random_input = np.random.rand(32,32, 3).astype(np.float32)
random_input = np.expand_dims(random_input, axis=0)
preds = model(random_input, train=False)
```

**Comment by AakashKumarNain** [comment]
Thanks. I got that. The only thing is that it is not a very good design IMO because you are declaring  same thing with two diff variables in `__init__`.

**Comment by gasar8** [comment]
Hi @AakashKumarNain, I was struggling with the same problem and it was strange to me to define "same" layer multiple times, too. However after realising I should do this, I implemented a workaround (which is not really nice, but it works). What I did was:

```self.conv   = [Conv2D(32, (3, 3), padding='same') for layer in range(4)]'''

and then

```z = self.conv[0](z)
z = self.conv[0](z)
z = self.conv[0](z)'''

**Comment by manp-git** [comment]
Hi I am struggling with the same issue. Here is the code snippet if somebody can help out:-

conv_output = tensorflow.keras.backend.conv2d(input_tensor, kernel=modified_weights, strides=(1, 1), padding='same', dilation_rate=(1,1), data_format='channels_last')

input_tensor.shape( )= (1, 56, 56, 64)
modifies_weights.shape( ) = (64, 3, 3, 64)


Tried with channels_first also ; same error;

This some experimentation from resnet50 model from the where the required layer output and weights have been correctly extracted; The dimensions have been confirmed to be correct from there.

**Comment by ocuk** [comment]
@AakashKumarNain @gasar8 Try layer subclassing. You can define a new layer (or a sequence of layers) once and then re-use them as you build your model. Here is a good example https://www.linkedin.com/pulse/model-sub-classing-custom-training-loop-from-scratch-tensorflow
