### ISSUE TITLE
ExtractImagePatches Op Request

### ISSUE THREAD

**Issue by anidh** [tensorflow/tensorflow#28789]
**System information**
- Ubuntu 14.04
- Tensorflow Installed from Binary:
- TensorFlow version 1.13:

**Provide the text output from tflite_convert**

```
Some of the operators in the model are not supported by the standard TensorFlow Lite runtime. If those are native TensorFlow operators, you might be able to use the extended runtime by passing --enable_select_tf_ops, or by setting target_ops=TFLITE_BUILTINS,SELECT_TF_OPS when calling tf.lite.TFLiteConverter(). Otherwise, if you have a custom implementation for them you can disable this error with --allow_custom_ops, or by setting allow_custom_ops=True when calling tf.lite.TFLiteConverter(). Here is a list of builtin operators you are using: CONCATENATION, CONV_2D, MAXIMUM, MAX_POOL_2D, MUL, PAD. Here is a list of operators for which you will need custom implementations: ExtractImagePatches.
```

Also, please include a link to a GraphDef or the model if possible.
This is the onedrive link for the file
[Google Drive Link](https://drive.google.com/open?id=1pu_IAj2b9GoU4HCDd___MLg_20ikB8DZ)

**Any other info / logs**

I was trying to convert Tiny YOLO model to the tflite format when i encountered this error.

**Comment by gadagashwini** [comment]
@anidh Please provide the correct link. Thanks!

**Comment by anidh** [comment]
Hi @gadagashwini Sorry for the broken link, I've updated the issue with new google drive link.

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.

**Comment by mohantym** [comment]
Hi @anidh ! 1.x versions are not supported any more. In the 2.x version , You can resolve the Select ops by putting below the code snippet before converting it to a lite model. Attaching documents on [Select Ops](https://www.tensorflow.org/lite/guide/ops_select) and [Custom Ops ](https://www.tensorflow.org/lite/guide/ops_custom)for reference. Thank you!

```
converter.target_spec.supported_ops = [
  tf.lite.OpsSet.TFLITE_BUILTINS, # enable TensorFlow Lite ops.
  tf.lite.OpsSet.SELECT_TF_OPS # enable TensorFlow ops.
]
#converter.allow_custom_ops = True (if you are using any custom ops)

tflite_model = converter.convert()
open("converted_model.tflite", "wb").write(tflite_model)
```
