### ISSUE TITLE
catch keyboard interrupt in tf.function

### ISSUE THREAD

**Issue by decewei** [tensorflow/tensorflow#28786]
**System information**
- TensorFlow version (you are using): 2.0.0-alpha
- Are you willing to contribute it (Yes/No): Maybe depends on workload

**Describe the feature and the current behavior/state.** keyboard interrupt in tf.function. Currently I cannot keyboard interrupt or break the loop in tf.function made training function.

**Will this change the current api? How?** Depends on how tf 2.0 works. Might need to change the way c++ and python interface so that we can kill the threads.

**Who will benefit with this feature?** Developers. We don't need to pkill a training process, restarts it, load checkpoint and do inference.

**Comment by alextp** [comment]
I don't have the bandwidth to work on this now but would welcome a PR.

**Comment by vedhasp** [comment]
If this is still open, I'd like to take a stab at it.

**Comment by alextp** [comment]
@mrry does this overlap with the cancellationmanager thing you started looking at?

**Comment by mrry** [comment]
There is probably some overlap, although I was only planning to develop support for programmatic cancellation, and not intercepting Python’s `KeyboardInterrupt`.

@vedhasp It would be great if you took a stab at adding this, and I’d be happy to help you get it in! Before sending a complete Pull Request, could you sketch your plans on this issue thread, and we can make sure that it’s compatible with the existing cancellation support in the TensorFlow runtime? Thanks!
