### ISSUE TITLE
TF Lite select tf ops example linker error: libtensorflow-lite.a missing tflite subgraph

### ISSUE THREAD

**Issue by futuyao** [tensorflow/tensorflow#28783]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): macOS 10.14.5
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: iPhone 7
- TensorFlow installed from (source or binary): source
- TensorFlow version: r1.13
- Python version: 2.7
- Installed using virtualenv? pip? conda?: pip
- Bazel version (if compiling from source): 0.19.2
- GCC/Compiler version (if compiling from source): 4.2.1
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

**Describe the problem**

**Provide the exact sequence of commands / steps that you executed before running into the problem**

Followed guide on [Select TensorFlow operators to use in TensorFlow Lite](https://www.tensorflow.org/lite/guide/ops_select)

Then tried to run example project `tensorflow/lite/examples/ios/camera/tflite_camera_example_with_select_tf_ops.xcodeproj`

Gave linker errors as below

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

Errors as below:

> Undefined symbol: tflite::Subgraph::ModifyGraphWithDelegate(_TfLiteDelegate*)
> 
> Undefined symbol: tflite::Subgraph::AddTensors(int, int*)
> 
> Undefined symbol: tflite::Subgraph::SetTensorParametersReadOnly(int, TfLiteType, char const*, unsigned long, int const*, TfLiteQuantizationParams, char const*, unsigned long, tflite::Allocation const*)
> 
> Undefined symbol: tflite::Subgraph::ResetVariableTensors()
> 
> Undefined symbol: tflite::Subgraph::Invoke()
> 
> Undefined symbol: tflite::Subgraph::ResizeInputTensor(int, std::__1::vector<int, std::__1::allocator<int> > const&)
> 
> Undefined symbol: tflite::Subgraph::SetExecutionPlan(std::__1::vector<int, std::__1::allocator<int> > const&)
> 
> Undefined symbol: tflite::Subgraph::SetTensorParametersReadWrite(int, TfLiteType, char const*, unsigned long, int const*, TfLiteQuantizationParams, bool)
> 
> Undefined symbol: tflite::Subgraph::SetVariables(std::__1::vector<int, std::__1::allocator<int> >)
> 
> Undefined symbol: tflite::Subgraph::AddNodeWithParameters(std::__1::vector<int, std::__1::allocator<int> > const&, std::__1::vector<int, std::__1::allocator<int> > const&, char const*, unsigned long, void*, _TfLiteRegistration const*, int*)
> 
> Undefined symbol: tflite::Subgraph::AllocateTensors()
> 
> Undefined symbol: tflite::Subgraph::SetInputs(std::__1::vector<int, std::__1::allocator<int> >)
> 
> Undefined symbol: tflite::Subgraph::UseNNAPI(bool)
> 
> Undefined symbol: tflite::Subgraph::SetExternalContext(TfLiteExternalContextType, TfLiteExternalContext*)
> 
> Undefined symbol: tflite::Subgraph::SetOutputs(std::__1::vector<int, std::__1::allocator<int> >)
> 
> Undefined symbol: tflite::Subgraph::Subgraph(tflite::ErrorReporter*, TfLiteExternalContext**, std::__1::vector<std::__1::unique_ptr<tflite::Subgraph, std::__1::default_delete<tflite::Subgraph> >, std::__1::allocator<std::__1::unique_ptr<tflite::Subgraph, std::__1::default_delete<tflite::Subgraph> > > >*)

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this issue, as you are using an older version of tensorflow(1.x) which is officially considered as end of life. We recommend that you upgrade to 2.4 or later version and let us know if the issue still persists in newer versions. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, Please open a new issue for any help you need against 2.x, and we will get you the right help.
