### ISSUE TITLE
reduction_ops_gpu_complex128.cu.pic.o was not created

### ISSUE THREAD

**Issue by Tayseer-bme** [tensorflow/tensorflow#28796]
**System information**
- Ubuntu 18.04.2
- https://github.com/VLOGroup/tensorflow-icg
- CUDA 10
- cudNN 7
- Python 3.6.8 |Anaconda, Inc.|
- GCC 7.3.0
- Bazel version 0.11.1

While building Tensorflow-icg (https://github.com/VLOGroup/tensorflow-icg) on a Slurm Cluster occurred the error 

```
 #warning "host_defines.h is an internal header file and must not be used directly.  This file will be removed in a future CUDA release.  Please use cuda_runtime_api.h or cuda_runtime.h instead."
  ^~~~~~~
./tensorflow/core/kernels/reduction_gpu_kernels.cu.h(271): error: initializer not allowed for __shared__ variable

./tensorflow/core/kernels/reduction_gpu_kernels.cu.h(320): error: initializer not allowed for __shared__ variable

./tensorflow/core/kernels/reduction_gpu_kernels.cu.h(271): error: initializer not allowed for __shared__ variable

./tensorflow/core/kernels/reduction_gpu_kernels.cu.h(320): error: initializer not allowed for __shared__ variable

./tensorflow/core/kernels/reduction_gpu_kernels.cu.h(271): error: initializer not allowed for __shared__ variable

./tensorflow/core/kernels/reduction_gpu_kernels.cu.h(320): error: initializer not allowed for __shared__ variable

6 errors detected in the compilation of "/tmp/tmpxft_00005f84_00000000-7_reduction_ops_gpu_complex128.cu.compute_52.cpp1.ii".
ERROR: /cluster/ty00gyna/tensorflow-icg/tensorflow/core/kernels/BUILD:2709:1: output 'tensorflow/core/kernels/_objs/reduction_ops_gpu/tensorflow/core/kernels/reduction_ops_gpu_complex128.cu.pic.o' was not created

ERROR: /cluster/ty00gyna/tensorflow-icg/tensorflow/core/kernels/BUILD:2709:1: not all outputs were created or valid
Target //tensorflow/tools/pip_package:build_pip_package failed to build

```

**Comment by Tayseer-bme** [comment]
https://github.com/tensorflow/tensorflow/commit/3c245f52912612ed9d8e20245ddb5de055680969
and :

Modify "./tensorflow/core/kernels/reduction_gpu_kernels.cu.h"
replace:
__shared__ value_type partial_sums[32 * 33];
by:
__shared__ __align__(
alignof(value_type)) char partial_sums_raw[32 * 33 * sizeof(value_type)];
value_type* partial_sums = reinterpret_cast<value_type*>(partial_sums_raw);

**Comment by jvishnuvardhan** [comment]
@Tayseer-bme Could you provide more details on the issue and context? Thanks!

**Comment by Tayseer-bme** [comment]
@jvishnuvardhan 
while building tensorflow, we can solve this error by following this steps:

1- Modify "tensorflow/core/platform/macros.h" as same as in the link 
https://github.com/tensorflow/tensorflow/commit/3c245f52912612ed9d8e20245ddb5de055680969

2- Modify "./tensorflow/core/kernels/reduction_gpu_kernels.cu.h"
replace:
shared value_type partial_sums[32 * 33];
by:
shared align(
alignof(value_type)) char partial_sums_raw[32 * 33 * sizeof(value_type)];
value_type* partial_sums = reinterpret_cast<value_type*>(partial_sums_raw);

the problem is solved

**Comment by gunan** [comment]
@Tayseer-bme would you like to send a pull request with the fixes you proposed?

**Comment by Tayseer-bme** [comment]
@gunan I don't know a lot about a pull request !

**Comment by jvishnuvardhan** [comment]
Automatically closing this out since I understand it to be resolved, but please let me know if I'm mistaken. If anyone interested in creating PR, please feel free to create a PR. Thanks!

**Comment by shalijiang** [comment]
I have still the exact same issue, has it been resolved?

**Comment by Hawk0826** [comment]
@Tayseer-bme  Thank you! I follow the steps and then it works. But when I run the train_mri_vn.py, it shows `Non-OK-status: status_ status: Failed precondition: could not dlopen DSO: libcupti.so.10.1; dlerror: libcupti.so.10.1: cannot open shared object file: No such file or directory` and `tensorflow.python.framework.errors_impl.InternalError:` Failed to create CUPTI subcriber.` Have you ever met this bug? and how you resolve it?

**Comment by vivien624** [comment]
It arises other issue:

./tensorflow/core/kernels/reduction_gpu_kernels.cu.h(324): error: identifier "partial_sums_raw" is undefined

./tensorflow/core/kernels/reduction_gpu_kernels.cu.h(322): error: expected a declaration

 ./tensorflow/core/kernels/reduction_gpu_kernels.cu.h(273): error: identifier "partial_sums_raw" is undefined

./tensorflow/core/kernels/reduction_gpu_kernels.cu.h(271): error: expected a declaration
