### ISSUE TITLE
tf.data.Dataset::cache doesn't cleanup unused lock and tmp files 

### ISSUE THREAD

**Issue by lgeiger** [tensorflow/tensorflow#28798]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 1.13.1 / 1.14.dev / 2.0.0-alpha0
- Python version: 3.7.3
- CUDA/cuDNN version: -
- GPU model and memory: -

**Describe the current behavior**
`tf.data.Dataset::cache` doesn't cleanup unused `lock` and `tmp` files if the iterator doesn't complete a pass over the whole dataset or if the process exits before cache has been completed. This means subsequent runs of the same code with an incomplete cache will fail with:
```python traceback
tensorflow.python.framework.errors_impl.AlreadyExistsError: There appears to be a concurrent caching iterator running - cache lockfile already exists ('cache/mnist_0.lockfile'). If you are sure no other running TF computations are using this cache prefix, delete the lockfile and re-initialize the iterator. Lockfile contents: Created at: 1558092594 [Op:IteratorGetNextSync]
```

**Describe the expected behavior**
The iterator should cleanup incomplete cache files if finished or if the process exits. This would be really handy when running multiple runs on the machine and if processes might error or finish before the cache has been complete.

**Code to reproduce the issue**
```python
import tensorflow as tf 
import tensorflow_datasets as tfds 

tf.enable_eager_execution() # if version 1.x

data = tfds.load("mnist", split=tfds.Split.TRAIN) 
cached = data.cache("cache/mnist").shuffle(100).repeat().batch(128) 
 
for feat in cached: 
    print("iterating")
```

**Comment by muddham** [comment]
@lgeiger Able to reproduce the issue with the provided code.
NotFoundError: cache/mnist_0.lockfile; No such file or directory [Op:IteratorGetNextSync]

**Comment by muddham** [comment]
@lgeiger After running the provided code, got the below error.
NotFoundError: cache/mnist_0.lockfile; No such file or directory [Op:IteratorGetNextSync]
