### ISSUE TITLE
tf.signal.stft supports only float32 inputs 

### ISSUE THREAD

**Issue by PCerles** [tensorflow/tensorflow#28804]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using): 1.13
- Are you willing to contribute it (Yes/No): maybe but not much experience

**Describe the feature and the current behavior/state.**
tf.signal.stft allows computing the short-time fourier transform over an input signal. Right now, the op only supports float32 inputs. I'm getting significant differences between a numpy and TF implementation because of this. The RFFT implementation in tensorflow supports float64 inputs and none of the other functions called require float32 so I can't see too many obstacles to fixing. 

https://github.com/tensorflow/tensorflow/blob/r1.13/tensorflow/python/ops/signal/spectral_ops.py

**Will this change the current api? How?**
No
**Who will benefit with this feature?**
People moving their frequency-domain processing into tensorflow. 
**Any Other info.**
Would also be good to allow rfft to work on complex128.

**Comment by AlexeyG** [comment]
Why is this closed? Has it been decided that there will be no implementation?
