### ISSUE TITLE
Signature defs lost when calling saved_model_cli convert

### ISSUE THREAD

**Issue by JonTriebenbach** [tensorflow/tensorflow#28812]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
```
Yes.  Using saved_model_cli tool.
```
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
```
cat /etc/os-release 
NAME="Red Hat Enterprise Linux Server"
VERSION="7.6 (Maipo)"
ID="rhel"
ID_LIKE="fedora"
VARIANT="Server"
VARIANT_ID="server"
VERSION_ID="7.6"
PRETTY_NAME="Red Hat Enterprise Linux Server 7.6 (Maipo)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:7.6:GA:server"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 7"
REDHAT_BUGZILLA_PRODUCT_VERSION=7.6
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="7.6"
```
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
```
Source
```
- TensorFlow version (use command below):
```
python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"
2019-05-17 20:37:38.121490: I tensorflow/stream_executor/platform/default/dso_loader.cc:43] Successfully opened dynamic library libcudart.so.10.1
v1.12.1-142-gcd15418 1.14.0-rc0
```
- Python version:
```
python --version
Python 3.6.8 :: Anaconda, Inc.
```
- Bazel version (if compiling from source):
```
0.24.1
```
- GCC/Compiler version (if compiling from source):
```
7.3.0
```
- CUDA/cuDNN version:
```
cudatoolkit               10.1.152 
cudnn                     7.5.1_10.1 
```
- GPU model and memory:
```
Tesla V100-SXM2
16130MiB
```
You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`
```
python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"
2019-05-17 20:37:38.121490: I tensorflow/stream_executor/platform/default/dso_loader.cc:43] Successfully opened dynamic library libcudart.so.10.1
v1.12.1-142-gcd15418 1.14.0-rc0
```

**Describe the current behavior**

The "predict" signature definition is lost when running the `saved_model_cli convert` command against a resnet model.

**Describe the expected behavior**
Both the "predict" signature, and the "serving_default" signature definitions should be in the saved_model.

Code was removed near these lines in trt_convert.py when the code was restructured in the r1.14 branch:
https://github.com/tensorflow/tensorflow/blob/6b657e327cc9ca6e2906ade3e4877e3303065d70/tensorflow/python/compiler/tensorrt/trt_convert.py#L254

The original code in the v1.13.1 tagged version looped through all of the signature definitions:
https://github.com/tensorflow/tensorflow/blob/6612da89516247503f03ef76e974b51a434fb52e/tensorflow/contrib/tensorrt/python/trt_convert.py#L292

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

The following steps will show the issue with the converted graph:
```
mkdir -p $HOME/saved-models
cd $HOME/saved-models
wget http://download.tensorflow.org/models/official/20181001_resnet/savedmodels/resnet_v1_fp16_savedmodel_NCHW.tar.gz
tar --no-same-owner -xzvf resnet_v1_fp16_savedmodel_NCHW.tar.gz

cd $HOME
mkdir -p $HOME/inference-models/resnet_v1_50_fp16

saved_model_cli convert --dir $HOME/saved-models/resnet_v1_fp16_savedmodel_NCHW/1538686290 --output_dir $HOME/inference-models/resnet_v1_50_fp16/cli --tag_set serve tensorrt --precision_mode FP16 --max_batch_size 1 --is_dynamic_op False

saved_model_cli show --dir $HOME/saved-models/resnet_v1_fp16_savedmodel_NCHW/1538686290 --all # Will show "predict" saved model signature definition

saved_model_cli show --dir $HOME/inference-models/resnet_v1_50_fp16/cli --all # The "predict" signature definition does not exist in the converted model
```

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by aaroey** [comment]
This is intended behavior, since the TRT converter is designed to convert only one signature at a time. If you want to convert two signatures you'll need to run the converter twice by specifying different `[input_saved_model_signature_key](https://github.com/tensorflow/tensorflow/blob/6b657e327cc9ca6e2906ade3e4877e3303065d70/tensorflow/python/compiler/tensorrt/trt_convert.py#L1066)`s (which is not supported by saved_model_cli yet). That will result in two different SavedModels, which is also the behavior for TF2.0.

If this doesn't satisfy your requirement, would you please let us know and provide a detailed use case? Thanks.

**Comment by JonTriebenbach** [comment]
The answer only covers the Tensorflow 2.0 case.  The problem was reported against Tensorflow 1.14.0.  If this answer is also for Tensorflow 1.14.0, then this is a breakage between Tensorflow 1.13.1 and Tensorflow 1.14.0.  In Tensorflow 1.13.1, all signatures were converted.  Why would that behavior be changed in Tensorflow 1.14.0?  Thanks.

**Comment by aaroey** [comment]
@JonTriebenbach that is the answer for both 2.0 and 1.14. I'm sorry for the inconvenience, but this is actually not a breakage, since in 1.13 tensorrt is in contrib/ and which doesn't have [backward compatibility guarantee](https://www.tensorflow.org/guide/version_compat). In 1.14 we change many things of tensorrt integration including many of the APIs in order to move it to TF core, and this is part of those changes. 

Also, would you please let us know your use case if this change is a blocker for you? Thanks a lot.

**Comment by prosperhitfz** [comment]
I am very pleased to know the info. And I do not use the repository to make changes. I just want to learn something about machine learning. Thank you👀


 
---Original---

**Comment by JonTriebenbach** [comment]
The problem is that without the input_saved_model_signature_key support, which is currently missing, the convert tool chooses the last signature, the "serving_default" signature.  It appears the serving_default signature is compatible and will work in the pre-trained models I have downloaded, but I wonder if that is true for every multi-headed model?
