### ISSUE TITLE
plzz help

### ISSUE THREAD

**Issue by lakshitha1629** [tensorflow/tensorflow#28825]
Use standard file APIs to check for files with this prefix.

```
WARNING:tensorflow:From C:\Users\HP\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\tools\freeze_graph.py:232: convert_variables_to_constants (from tensorflow.python.framework.graph_util_impl) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.compat.v1.graph_util.convert_variables_to_constants
WARNING:tensorflow:From C:\Users\HP\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\framework\graph_util_impl.py:245: extract_sub_graph (from tensorflow.python.framework.graph_util_impl) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.compat.v1.graph_util.extract_sub_graph
Traceback (most recent call last):
  File "export_inference_graph.py", line 156, in <module>
    tf.app.run()
  File "C:\Users\HP\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\platform\app.py", line 125, in run
    _sys.exit(main(argv))
  File "export_inference_graph.py", line 152, in main
    write_inference_graph=FLAGS.write_inference_graph)
  File "C:\Users\HP\Desktop\RE\models\research\object_detection\exporter.py", line 465, in export_inference_graph
    write_inference_graph=write_inference_graph)
  File "C:\Users\HP\Desktop\RE\models\research\object_detection\exporter.py", line 421, in _export_inference_graph
    placeholder_tensor, outputs)
  File "C:\Users\HP\Desktop\RE\models\research\object_detection\exporter.py", line 264, in write_saved_model
    builder = tf.saved_model.builder.SavedModelBuilder(saved_model_path)
  File "C:\Users\HP\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\saved_model\builder_impl.py", line 425, in __init__
    super(SavedModelBuilder, self).__init__(export_dir=export_dir)
  File "C:\Users\HP\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\saved_model\builder_impl.py", line 100, in __init__
    "directory: %s" % export_dir)
AssertionError: Export directory already exists. Please specify a different export directory: inference_graph\saved_model
```

**Comment by Transwert** [comment]
a advice, be more specific to your problem, like state it in more formal and broader way, with proper indentation in you code as well as your output received, then people may help you in better way :)

**Comment by gadagashwini** [comment]
@lakshitha1629 Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version. Also, did you compile from source or install a binary?

Make sure you also include the exact command if possible to produce the output included in your test case. If you are unclear what to include see the issue template displayed in [the Github new issue template](https://github.com/tensorflow/tensorflow/issues/new/choose).

We ask for this in the issue submission template, because it is really difficult to help without that information. Thanks!

**Comment by mihaimaruseac** [comment]
`AssertionError: Export directory already exists. Please specify a different export directory: inference_graph\saved_model` tells you the issue: you either delete the `inference_graph\saved_model` or specify a different one when running.

**Comment by gadagashwini** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
