### ISSUE TITLE
module 'tensorflow._api.v1.keras.layers' has no attribute 'Lamdba'

### ISSUE THREAD

**Issue by Krum3L** [tensorflow/tensorflow#28828]
Cannot build my code due to "module 'tensorflow._api.v1.keras.layers' has no attribute 'Lamdba'" heres the code thats related to it:

`classifier_layer = layers.Lamdba(classifier_layer, input_shape = IMAGE_SIZE*[3])
classifier_model = tf.keras.Sequential([classifier_layer])
classifier_mode.summary()`

Im currently just "Copy pasting" / writing it from the Tensorflow tutorial 
(https://www.tensorflow.org/tutorials/images/hub_with_keras) to understand how it works, im very unsure why its not working for me since i used every import they used on the page aswell, looked up if i need to install another package (had to do that some times already) but unfortunally i didnt found anything.

**Comment by captain-pool** [comment]
> Cannot build my code due to "module 'tensorflow._api.v1.keras.layers' has no attribute 'Lamdba'" heres the code thats related to it:
> 
> `classifier_layer = layers.Lamdba(classifier_layer, input_shape = IMAGE_SIZE*[3]) classifier_model = tf.keras.Sequential([classifier_layer]) classifier_mode.summary()`
> 
> Im currently just "Copy pasting" / writing it from the Tensorflow tutorial
> (https://www.tensorflow.org/tutorials/images/hub_with_keras) to understand how it works, im very unsure why its not working for me since i used every import they used on the page aswell, looked up if i need to install another package (had to do that some times already) but unfortunally i didnt found anything.

Hi! Can you provide the Version of Tensorflow, OS Version,etc. you are using? It would be nice if you close this issue and open another issue using the issue template, provided.

**Comment by Krum3L** [comment]
Hello, sorry for the late reply, im gonna open a new issue.. unfortunally i dont know how to close this one.
