### ISSUE TITLE
Error Loading Package @io_bazel_rules_docker when building Tensorflow

### ISSUE THREAD

**Issue by Acidic9** [tensorflow/tensorflow#28824]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): Source
- TensorFlow version: 1.12.2 / master branch
- Python version: Python 3.6.8 :: Anaconda, Inc.
- Installed using virtualenv? pip? conda?: Conda
- Bazel version (if compiling from source): 0.25.2
- GCC/Compiler version (if compiling from source): gcc version 8.2.0 (Rev3, Built by MSYS2 project)
- CUDA/cuDNN version: Cuda v10.1 - cudnn-9.2-windows10-x64-v7.5.1.10
- GPU model and memory: NVidia 1060

**Describe the problem**
Build failing when running `bazel build --config=opt //tools/pip_package:build_pip_package`
with error:
```
ERROR: error loading package '': Encountered error while reading extension file 'repositories/repositories.bzl': no such package '@io_bazel_rules_docker//repositories'
```

**Provide the exact sequence of commands / steps that you executed before running into the problem**
I followed the tutorial here: https://medium.com/@amsokol.com/how-to-build-and-install-tensorflow-gpu-cpu-for-windows-from-source-code-using-bazel-d047d9342b44

```
> python configure.py
Python Location (default): C:\Users\Arise\Miniconda3\envs\tensorflow-v1.10\python.exe
Python Libraries Path (default): C:\Users\Arise\Miniconda3\envs\tensorflow-v1.10\lib\site-packages
XLA JIT support: No
ROCm support: No
CUDA support: Yes
CUDA compute capabilities (default): 3.5,7.0
Optimization Flags Bazel (default): --config=opt
Override Eigen Strong Inline (default): Yes
```

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

```
(tensorflow-v1.10) C:\Users\Arise\tensorflow-build\tensorflow>bazel build
Starting local Bazel server and connecting to it...
WARNING: Usage: bazel build <options> <targets>.
Invoke `bazel help build` for full description of usage and options.
Your request is correct, but requested an empty set of targets. Nothing will be built.
INFO: An error occurred during the fetch of repository 'io_bazel_rules_docker'
INFO: Call stack for the definition of repository 'io_bazel_rules_docker':
 - C:/users/arise/_bazel_arise/ji3ak47x/external/bazel_toolchains/repositories/repositories.bzl:37:9
 - C:/users/arise/tensorflow-build/tensorflow/WORKSPACE:29:1
ERROR: error loading package '': Encountered error while reading extension file 'repositories/repositories.bzl': no such package '@io_bazel_rules_docker//repositories': Traceback (most recent call last):
        File "C:/users/arise/_bazel_arise/ji3ak47x/external/bazel_tools/tools/build_defs/repo/git.bzl", line 234
                _clone_or_update(ctx)
        File "C:/users/arise/_bazel_arise/ji3ak47x/external/bazel_tools/tools/build_defs/repo/git.bzl", line 74, in _clone_or_update
                fail(("error cloning %s:\n%s" % (ctx....)))
error cloning io_bazel_rules_docker:
+ cd C:/users/arise/_bazel_arise/ji3ak47x/external
+ rm -rf C:/users/arise/_bazel_arise/ji3ak47x/external/io_bazel_rules_docker C:/users/arise/_bazel_arise/ji3ak47x/external/io_bazel_rules_docker
/usr/bin/bash: line 5: rm: command not found
ERROR: error loading package '': Encountered error while reading extension file 'repositories/repositories.bzl': no such package '@io_bazel_rules_docker//repositories': Traceback (most recent call last):
        File "C:/users/arise/_bazel_arise/ji3ak47x/external/bazel_tools/tools/build_defs/repo/git.bzl", line 234
                _clone_or_update(ctx)
        File "C:/users/arise/_bazel_arise/ji3ak47x/external/bazel_tools/tools/build_defs/repo/git.bzl", line 74, in _clone_or_update
                fail(("error cloning %s:\n%s" % (ctx....)))
error cloning io_bazel_rules_docker:
+ cd C:/users/arise/_bazel_arise/ji3ak47x/external
+ rm -rf C:/users/arise/_bazel_arise/ji3ak47x/external/io_bazel_rules_docker C:/users/arise/_bazel_arise/ji3ak47x/external/io_bazel_rules_docker
/usr/bin/bash: line 5: rm: command not found
INFO: Elapsed time: 2.642s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
```

**Comment by Acidic9** [comment]
I managed to fix this by adding the following to the top of my WORKSPACE file:
```python
http_archive(
    name = "io_bazel_rules_docker",
    sha256 = "aed1c249d4ec8f703edddf35cbe9dfaca0b5f5ea6e4cd9e83e99f3b0d1136c3d",
    strip_prefix = "rules_docker-0.7.0",
    urls = ["https://github.com/bazelbuild/rules_docker/archive/v0.7.0.tar.gz"],
)
```
If you do the same, you probably want to ensure you get the latest version here https://github.com/bazelbuild/rules_docker and copy the code snippet from the README instead of from here.

**Comment by QuellaZhang** [comment]
Same failure, can someone help?
ERROR: error loading package '': Encountered error while reading extension file 'repositories/repositories.bzl': no such package '@io_bazel_rules_docker//repositories': Traceback (most recent call last):
        File "C:/users/vcntwtt/_bazel_vcntwtt/cd6duifl/external/bazel_tools/tools/build_defs/repo/git.bzl", line 234
                _clone_or_update(ctx)
        File "C:/users/vcntwtt/_bazel_vcntwtt/cd6duifl/external/bazel_tools/tools/build_defs/repo/git.bzl", line 74, in _clone_or_update
                fail(("error cloning %s:\n%s" % (ctx....)))
error cloning io_bazel_rules_docker:
java.io.IOException: ERROR: src/main/native/windows/processes-jni.cc(456): CreateProcessW("bash" -c "
cd C:/users/vcntwtt/_bazel_vcntwtt/cd6duifl/external
set -ex
( cd C:/users/vcntwtt/_bazel_vcntwtt/cd6duifl/external &&
    if ! ( cd 'C:/users/vcntwtt/_bazel_vcntwtt/cd6duifl/external(...)): The system cannot find the file specified.

**Comment by Acidic9** [comment]
@QuellaZhang Did you read my comment above? Did it not work?

**Comment by achandraa** [comment]
@Acidic9 : Looks like you were able to resolve this issue. Let us know. Thanks!

**Comment by achandraa** [comment]
Closing the issue since it is resolved. Thanks!

**Comment by QuellaZhang** [comment]
@Acidic9 Thanks for the patch, I can build successfully with the patch. 

But the final reason I found it is that the Python library installation is not complete, I reinstall the Python64 and  follow the build steps, then I can successfully build the latest Tensorflow source code without any patch.

In addition, I found that if we did not execute "pacman -S git patch unzip" after installing msys32, it will report similar errors.

**Comment by leriomaggio** [comment]
I got into the very same issue when I tried to compile `TensorFlow 2.0.0-beta1` from source with 
*Intel-MKL* (CPU only) support.

I solved the issue by including the following directive on top of the `WORKSPACE` file:

```python
# Download the rules_docker repository at release v0.8.1
http_archive(
    name = "io_bazel_rules_docker",
    sha256 = "87fc6a2b128147a0a3039a2fd0b53cc1f2ed5adb8716f50756544a572999ae9a",
    strip_prefix = "rules_docker-0.8.1",
    urls = ["https://github.com/bazelbuild/rules_docker/archive/v0.8.1.tar.gz"],
)
``` 

The directive has been taken from here: https://github.com/bazelbuild/rules_docker

HTH

**Comment by ArtificialArchitect** [comment]
I'm not very impressed with bazel so far, I am not even building a docker image. So I spent 4+ hours compiling, and it didn't even generate the wheel but it said it had completed. Now when I try to build the package again, I get this error. I think makefiles worked quite well, and I am just calling this bagel now.

**Comment by ArtificialArchitect** [comment]
Well I got it building (again, and again) but it is starting all over. The whole purpose of make is that it tracks the file time and date so you don't have to continously rebuild the same thing over and over.

**Comment by ArtificialArchitect** [comment]
I think tensorflow is very good and I am glad they have made it for everyone. But I have spent over a day with bazel going nowhere, and I am getting tired.

**Comment by ArtificialArchitect** [comment]
Well, that is black magic. I see it was waiting all that time for me to issue a command to construct the wheel. Pretty cool, like reading an old DSP books and thinking why the wheel looks like it goes backwards.

**Comment by ArtificialArchitect** [comment]
Well I did get it to compile on linux before, I forgot that you had to use the actual thing to launch the wheel into creation. The problem was I had moved a drive letter on windows and this broke bazel. Fixing the drive it worked fine. Just confused why that changed. It is important I can build tensorflow for the machine so the logic gates will set correctly to the computer system.

**Comment by gbolcer** [comment]
> 
> 
> I managed to fix this by adding the following to the top of my WORKSPACE file:
> 
> ```python
> http_archive(
>     name = "io_bazel_rules_docker",
>     sha256 = "aed1c249d4ec8f703edddf35cbe9dfaca0b5f5ea6e4cd9e83e99f3b0d1136c3d",
>     strip_prefix = "rules_docker-0.7.0",
>     urls = ["https://github.com/bazelbuild/rules_docker/archive/v0.7.0.tar.gz"],
> )
> ```
> 
> If you do the same, you probably want to ensure you get the latest version here https://github.com/bazelbuild/rules_docker and copy the code snippet from the README instead of from here.

https://github.com/bazelbuild/rules_docker/blob/master/WORKSPACE

**Comment by kasunvj** [comment]
> ```python
> http_archive(
>     name = "io_bazel_rules_docker",
>     sha256 = "aed1c249d4ec8f703edddf35cbe9dfaca0b5f5ea6e4cd9e83e99f3b0d1136c3d",
>     strip_prefix = "rules_docker-0.7.0",
>     urls = ["https://github.com/bazelbuild/rules_docker/archive/v0.7.0.tar.gz"],
> )
> ```
Successful!!. but not on the top of workspace file. put these lines after loading http_archive

**Comment by Tameli** [comment]
Hi @Acidic9 

> ```python
> http_archive(
>     name = "io_bazel_rules_docker",
>     sha256 = "aed1c249d4ec8f703edddf35cbe9dfaca0b5f5ea6e4cd9e83e99f3b0d1136c3d",
>     strip_prefix = "rules_docker-0.7.0",
>     urls = ["https://github.com/bazelbuild/rules_docker/archive/v0.7.0.tar.gz"],
> )
> ```

to which WORKSPACE file did you added the code snippet above?The exact path would help me a lot. I'm sorry if it should be obvious.Thank you so much!

**Comment by Acidic9** [comment]
> to which WORKSPACE file did you added the code snippet above?The exact path would help me a lot. I'm sorry if it should be obvious.Thank you so much!

@Tameli the `WORKSPACE` file is in the root of the project.

**Comment by Tameli** [comment]
@Acidic9 Thank you!!
