### ISSUE TITLE
error: default initialization of an object of const type 'const Subgraph::Identity' without a user-provided default constructor

### ISSUE THREAD

**Issue by dbl001** [tensorflow/tensorflow#28839]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
OS X 10.11.6
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
Source
- TensorFlow version:
13.1
- Python version:
3.6.7
- Installed using virtualenv? pip? conda?:
Conda
- Bazel version (if compiling from source):
bazel 18.1 & 0.21.1
- GCC/Compiler version (if compiling from source):
$ g++ --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 8.0.0 (clang-800.0.42.1)
Target: x86_64-apple-darwin15.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
MacBook-Pro:tensorflow davidlaxer$ c++ --version
Apple LLVM version 8.0.0 (clang-800.0.42.1)
Target: x86_64-apple-darwin15.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
MacBook-Pro:tensorflow davidlaxer$ clang --version
clang version 5.0.0 (tags/RELEASE_500/final)
Target: x86_64-apple-darwin15.6.0
Thread model: posix
InstalledDir: /Users/davidlaxer/anaconda/bin
MacBook-Pro:tensorflow davidlaxer$ which clang
/Users/davidlaxer/anaconda/bin/clang
MacBook-Pro:tensorflow davidlaxer$ /Users/davidlaxer/anaconda/bin/clang --version
clang version 5.0.0 (tags/RELEASE_500/final)
Target: x86_64-apple-darwin15.6.0
Thread model: posix

- CUDA/cuDNN version:
CPU Only
- GPU model and memory:

**Describe the problem**
ERROR: /Users/davidlaxer/tensorflow/tensorflow/core/grappler/graph_analyzer/BUILD:5:1: C++ compilation of rule '//tensorflow/core/grappler/graph_analyzer:graph_analyzer_lib' failed (Exit 1)
tensorflow/core/grappler/graph_analyzer/graph_analyzer.cc:75:28: error: default initialization of an object of const type 'const Subgraph::Identity' without a user-provided default constructor
  const Subgraph::Identity empty_parent;
                           ^
                                       {}
1 error generated.
Target //tensorflow/tools/pip_package:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.

**Provide the exact sequence of commands / steps that you executed before running into the problem**

$ bazel build --config=opt //tensorflow/tools/pip_package:build_pip_package

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by ymodak** [comment]
TensorFlow requires [macOS 10.12.6 (Sierra) or later (64-bit)](https://www.tensorflow.org/install/pip#system-requirements)

**Comment by dbl001** [comment]
I was able to Tensorflow built 1.12  from source on 10.11.6.
Is that the final version I can build on this OS?

**Comment by dbl001** [comment]
In Tensorflow 13.1 , I adjusted the Subgraph::Identity initialization.  But ...

```
ERROR: /Users/davidlaxer/tensorflow/tensorflow/contrib/ignite/BUILD:148:1: Executing genrule //tensorflow/contrib/ignite:gen_igfs_ops_pygenrule failed (Trace/breakpoint trap): bash failed: error executing command /bin/bash -c ... (remaining 1 argument(s) skipped)
dyld: lazy symbol binding failed: Symbol not found: _clock_gettime
  Referenced from: /private/var/tmp/_bazel_davidlaxer/f9fe21ec5c09226e5ca0dce9376abe82/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/contrib/ignite/../../../_solib_darwin_x86_64/_U_S_Stensorflow_Scontrib_Signite_Cgen_Ugen_Uigfs_Uops_Upy_Uwrappers_Ucc___Utensorflow/libtensorflow_framework.so (which was built for Mac OS X 10.12)
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: _clock_gettime
  Referenced from: /private/var/tmp/_bazel_davidlaxer/f9fe21ec5c09226e5ca0dce9376abe82/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/contrib/ignite/../../../_solib_darwin_x86_64/_U_S_Stensorflow_Scontrib_Signite_Cgen_Ugen_Uigfs_Uops_Upy_Uwrappers_Ucc___Utensorflow/libtensorflow_framework.so (which was built for Mac OS X 10.12)
  Expected in: /usr/lib/libSystem.B.dylib

/bin/bash: line 1: 53224 Trace/BPT trap: 5       bazel-out/host/bin/tensorflow/contrib/ignite/gen_gen_igfs_ops_py_wrappers_cc , '' 0 0 > bazel-out/darwin-opt/genfiles/tensorflow/contrib/ignite/python/ops/gen_igfs_ops.py
Target //tensorflow/tools/pip_package:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 3007.455s, Critical Path: 200.07s
INFO: 2483 processes: 2483 local.
FAILED: Build did NOT complete successfully

```

**Comment by gunan** [comment]
I am not familiar with this code. Please reassign to grappler developers.

**Comment by petewarden** [comment]
I'm not familiar with grappler unfortunately, unassigning myself.

**Comment by mohantym** [comment]
Hi @dbl001 ! 
It seems you are using older versions(1.x versions) of Tensorflow. We recommend that you upgrade  your code base to 2.x  versions as many features and bug fixes has been done in newer versions and let us know if the issue still persists in newer versions. 

Tensorflow 2.6 is available on Macbook M1 ,Please follow this [reference ]( https://developer.apple.com/metal/tensorflow-plugin/)
You can also build from using this [link](https://www.tensorflow.org/install/source) using Bazel. Please create a new issue ,if you face any problem!

Thanks!
