### ISSUE TITLE
bazel still report error: name 'http_archive' is not defined

### ISSUE THREAD

**Issue by IeiuniumLux** [tensorflow/tensorflow#28832]
I'm experiencing the same error described in issue #27189, when I try to build TF v1.12.2 using Bazel 0.25.2 on a Jetson TX2
```
$ export TF_NEED_CUDA=1
$ export TF_CUDA_VERSION=9.0
$ export CUDA_TOOLKIT_PATH=/usr/local/cuda
$ export TF_CUDNN_VERSION=7.1.5
$ export CUDNN_INSTALL_PATH=/usr/lib/aarch64-linux-gnu/
$ export TF_CUDA_COMPUTE_CAPABILITIES=6.2

$ bazel build --config=opt --config=cuda //tensorflow/tools/pip_package:build_pip_package

WARNING: The following configs were expanded more than once: [cuda]. For repeatable flags, repeats are counted twice and may lead to unexpected behavior.
ERROR: /home/nvidia/git/tensorflow/WORKSPACE:3:1: name 'http_archive' is not defined
ERROR: Error evaluating WORKSPACE file
ERROR: error loading package '': Encountered error while reading extension file 'closure/defs.bzl': no such package '@io_bazel_rules_closure//closure': error loading package 'external': Could not load //external package
ERROR: error loading package '': Encountered error while reading extension file 'closure/defs.bzl': no such package '@io_bazel_rules_closure//closure': error loading package 'external': Could not load //external package
INFO: Elapsed time: 0.222s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
```

**Comment by muddham** [comment]
@IeiuniumLux Can you please let us know if you have followed the steps mentioned in the tensorflow website [link](https://www.tensorflow.org/install/source#tested_build_configurations) ,also please install relevant bazel version as mentioned in the link and mention the OS platform details.

**Comment by IeiuniumLux** [comment]
@muddham Yes, those are the exact the steps I'm following.  The link doesn't list the Bazel version for TF v1.12.2 though.  Are you saying that I should use Bazel 0.15.0 instead of 0.25.2?

**Comment by mihaimaruseac** [comment]
For v.12.2 you should use Bazel 0.15.0.

Running `./configure` before building is always a good idea as there are checks to ensure the toolchain you're using is compatible with the code.

**Comment by IeiuniumLux** [comment]
@mihaimaruseac I did run the ./configure before building it.  Anyhow, let's me try with Bazel 0.15.0 and report back the results. Thanks!

**Comment by muddham** [comment]
@IeiuniumLux Please try installing relevant bazel 0.15.0 also refer the [link](https://github.com/tensorflow/tensorflow/issues/27189)

**Comment by IeiuniumLux** [comment]
With Bazel 0.15.0, the build got further.  However, a little bit after a hour building, it failed with this error.  Any suggestion?

ERROR: /home/nvidia/git/tensorflow/tensorflow/contrib/lite/kernels/internal/BUILD:455:1: C++ compilation of rule '//tensorflow/contrib/lite/kernels/internal:tensor_utils' failed (Exit 1): crosstool_wrapper_driver_is_not_gcc failed: error executing command 
  (cd /home/nvidia/.cache/bazel/_bazel_nvidia/01c445c7b00bca0241913a79fcd99718/execroot/org_tensorflow && \
  exec env - \
    CUDA_TOOLKIT_PATH=/usr/local/cuda \
    CUDNN_INSTALL_PATH=/usr/lib/aarch64-linux-gnu \
    GCC_HOST_COMPILER_PATH=/usr/bin/gcc \
    LD_LIBRARY_PATH=/home/nvidia/ros_ws/devel/lib:/opt/ros/kinetic/lib:/opt/ros/kinetic/lib/aarch64-linux-gnu \
    PATH=/opt/ros/kinetic/bin:/usr/local/cuda-9.0/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin \
    PWD=/proc/self/cwd \
    PYTHON_BIN_PATH=/usr/bin/python3 \
    PYTHON_LIB_PATH=/usr/lib/python3/dist-packages \
    TF_CUDA_CLANG=0 \
    TF_CUDA_COMPUTE_CAPABILITIES=6.2 \
    TF_CUDA_VERSION=9.0 \
    TF_CUDNN_VERSION=7 \
    TF_NCCL_VERSION=1 \
    TF_NEED_CUDA=1 \
    TF_NEED_OPENCL_SYCL=0 \
    TF_NEED_ROCM=0 \
  external/local_config_cuda/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc -MD -MF bazel-out/arm-opt/bin/tensorflow/contrib/lite/kernels/internal/_objs/tensor_utils/tensorflow/contrib/lite/kernels/internal/tensor_utils.pic.d '-frandom-seed=bazel-out/arm-opt/bin/tensorflow/contrib/lite/kernels/internal/_objs/tensor_utils/tensorflow/contrib/lite/kernels/internal/tensor_utils.pic.o' -D__CLANG_SUPPORT_DYN_ANNOTATION__ -iquote . -iquote bazel-out/arm-opt/genfiles -iquote external/com_google_absl -iquote bazel-out/arm-opt/genfiles/external/com_google_absl -iquote external/bazel_tools -iquote bazel-out/arm-opt/genfiles/external/bazel_tools -iquote external/arm_neon_2_x86_sse -iquote bazel-out/arm-opt/genfiles/external/arm_neon_2_x86_sse -iquote external/gemmlowp -iquote bazel-out/arm-opt/genfiles/external/gemmlowp '-std=c++11' -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -fPIC -U_FORTIFY_SOURCE '-D_FORTIFY_SOURCE=1' -fstack-protector -Wall -fno-omit-frame-pointer -no-canonical-prefixes -DNDEBUG -g0 -O2 -ffunction-sections -fdata-sections '-march=native' -O3 '-mfpu=neon' -c tensorflow/contrib/lite/kernels/internal/tensor_utils.cc -o bazel-out/arm-opt/bin/tensorflow/contrib/lite/kernels/internal/_objs/tensor_utils/tensorflow/contrib/lite/kernels/internal/tensor_utils.pic.o)
gcc: error: unrecognized command line option '-mfpu=neon'
Target //tensorflow/tools/pip_package:build_pip_package failed to build
INFO: Elapsed time: 5924.627s, Critical Path: 227.50s
INFO: 5436 processes: 5436 local.
FAILED: Build did NOT complete successfully

**Comment by mihaimaruseac** [comment]
What's the output of `gcc --version`?

**Comment by IeiuniumLux** [comment]
@mihaimaruseac 
gcc (Ubuntu/Linaro 5.4.0-6ubuntu1~16.04.11) 5.4.0 20160609

**Comment by mihaimaruseac** [comment]
I guess the option forward is to try removing `"-mpfu=neon"` lines from https://github.com/tensorflow/tensorflow/blob/6b634657d8ff1355132c3838271e4f569d1ffaba/tensorflow/contrib/lite/kernels/internal/BUILD#L21-L37

**Comment by mihaimaruseac** [comment]
Also, if you want, can you also post the output of `gcc -dumpmachine`? That tells you what GCC can build for.

**Comment by IeiuniumLux** [comment]
@mihaimaruseac 

nvidia@tegra-ubuntu:~$ gcc -dumpmachine
aarch64-linux-gnu

I'm going to build it without the "-mpfu=neon" option. But before, let me ask a few questions. 

Do I need to run `./configure` before building it again?

Is it normal for the build to take more than a hour to complete on a Nvidia TX2?

Finally, is a [NCCL](https://docs.nvidia.com/deeplearning/sdk/nccl-install-guide/index.html) required by TF to build?

BTW, thank you for your assistance with this.

**Comment by mihaimaruseac** [comment]
Ok, so for AArch64 `-mfpu=neon` is not needed as neon is mandatory and included by default. Still dubious that the compiler would complain instead of silently ignoring but not the topic to discuss that here.

I think it is better to run `./configure` again as you changed some options. Though these seem to be in Bazel files, so probably there won't be any change. Better safe though, so I recommend rerunning.

I got builds taking 4-5 hours at one point, it all depends on how many CPUs and how powerful they are. The codebase is quite big.

You can build without NCCL. In fact, many times I built without any GPU at all.

**Comment by IeiuniumLux** [comment]
After almost 3 hours into the build, it failed with some kind of native TensorFlow runtime error:

--------------------------------------------------------------------
ERROR: /home/nvidia/git/tensorflow/tensorflow/BUILD:533:1: Executing genrule //tensorflow:tf_python_api_gen_v1 failed (Exit 1): bash failed: error executing command 
  (cd /home/nvidia/.cache/bazel/_bazel_nvidia/01c445c7b00bca0241913a79fcd99718/execroot/org_tensorflow && \
  exec env - \
    LD_LIBRARY_PATH=/home/nvidia/ros_ws/devel/lib:/opt/ros/kinetic/lib:/opt/ros/kinetic/lib/aarch64-linux-gnu \
    PATH=/opt/ros/kinetic/bin:/usr/local/cuda-9.0/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin \
  /bin/bash -c 'source external/bazel_tools/tools/genrule/genrule-setup.sh; bazel-out/host/bin/tensorflow/create_tensorflow.python_api_1 --root_init_template=tensorflow/api_template.__init__.py --apidir=bazel-out/host/genfiles/tensorflow_api/v1/ --apiname=tensorflow --apiversion=1 --package=tensorflow.python --output_package=tensorflow._api.v1 bazel-out/host/genfiles/tensorflow/_api/v1/__init__.py bazel-out/host/genfiles/tensorflow/_api/v1/app/__init__.py bazel-out/host/genfiles/tensorflow/_api/v1/bitwise/__init__.py bazel-out/host/genfiles/tensorflow/_api/v1/compat/__init__.py bazel-out/host/genfiles/tensorflow/_api/v1/data/__init__.py bazel-out/host/genfiles/tensorflow/_api/v1/data/experimental/__init__.py bazel-out/host/genfiles/tensorflow/_api/v1/debugging/__init__.py bazel-out/host/genfiles/tensorflow/_api/v1/distributions/__init__.py bazel-out/host/genfiles/tensorflow/_api/v1/dtypes/__init__.py bazel-out/host/genfiles/tensorflow/_api/v1/errors/__init__.py bazel-out/host/genfiles/tensorflow/_api/v1/feature_column/__init__.py bazel-out/host/genfiles/tensorflow/_api/v1/gfile/__init__.py bazel-out/host/genfiles/tensorflow/_api/v1/graph_util/__init__.py bazel-out/host/genfiles/tensorflow/_api/v1/image/__init__.py bazel-out/host/genfiles/tensorflow/_api/v1/io/__init__.py bazel-out/host/genfiles/tensorflow/_api/v1/initializers/__init__.py bazel-out/host/genfiles/tensorflow/_api/v1/keras/__init__.py bazel-out/host/genfiles/tensorflow/_api/v1/keras/activations/__init__.py bazel-out/host/genfiles/tensorflow/_api/v1/keras/applications/__init__.py bazel-out/host/genfiles/tensorflow/_api/v1/keras/applications/densenet/__init__.py bazel-out/host/genfiles/tensorflow/_api/v1/keras/applications/inception_resnet_v2/__init__.py bazel-out/host/genfiles/tensorflow/_api/v1/keras/applications/inception_v3/__init__.py bazel-out/host/genfiles/tensorflow/_api/v1/keras/applications/mobilenet/__init__.py bazel-out/host/genfiles/tensorflow/_api/v1/keras/applications/mobilenet_v2/__init__.py bazel-out/host/genfiles/tensorflow/_api/v1/keras/applications/nasnet/__init__.py bazel-out/host/genfiles/tensorflow/_api/v1/keras/applications/resnet50/__init__.py bazel-out/host/genfiles/tensorflow/_api/v1/keras/applications/vgg16/__init__.py bazel-out/host/genfiles/tensorflow/_api/v1/keras/applications/vgg19/__init__.py bazel-out/host/genfiles/tensorflow/_api/v1/keras/applications/xception/__init__.py bazel-out/host/genfiles/tensorflow/_api/v1/keras/backend/__init__.py bazel-out/host/genfiles/tensorflow/_api/v1/keras/callbacks/__init__.py bazel-out/host/genfiles/tensorflow/_api/v1/keras/constraints/__init__.py bazel-out/host/genfiles/tensorflow/_api/v1/keras/datasets/__init__.py bazel-out/host/genfiles/tensorflow/_api/v1/keras/datasets/boston_housing/__init__.py bazel-out/host/genfiles/tensorflow/_api/v1/keras/datasets/cifar10/__init__.py bazel-out/host/genfiles/tensorflow/_api/v1/keras/datasets/cifar100/__init__.py bazel-out/host/genfiles/tensorflow/_api/v1/keras/datasets/fashion_mnist/__init__.py bazel-out/host/genfiles/tensorflow/_api/v1/keras/datasets/imdb/__init__.py bazel-out/host/genfiles/tensorflow/_api/v1/keras/datasets/mnist/__init__.py bazel-out/host/genfiles/tensorflow/_api/v1/keras/datasets/reuters/__init__.py bazel-out/host/genfiles/tensorflow/_api/v1/keras/estimator/__init__.py bazel-out/host/genfiles/tensorflow/_api/v1/keras/initializers/__init__.py bazel-out/host/genfiles/tensorflow/_api/v1/keras/layers/__init__.py bazel-out/host/genfiles/tensorflow/_api/v1/keras/losses/__init__.py bazel-out/host/genfiles/tensorflow/_api/v1/keras/metrics/__init__.py bazel-out/host/genfiles/tensorflow/_api/v1/keras/models/__init__.py bazel-out/host/genfiles/tensorflow/_api/v1/keras/optimizers/__init__.py bazel-out/host/genfiles/tensorflow/_api/v1/keras/preprocessing/__init__.py bazel-out/host/genfiles/tensorflow/_api/v1/keras/preprocessing/image/__init__.py bazel-out/host/genfiles/tensorflow/_api/v1/keras/preprocessing/sequence/__init__.py bazel-out/host/genfiles/tensorflow/_api/v1/keras/preprocessing/text/__init__.py bazel-out/host/genfiles/tensorflow/_api/v1/keras/regularizers/__init__.py bazel-out/host/genfiles/tensorflow/_api/v1/keras/utils/__init__.py bazel-out/host/genfiles/tensorflow/_api/v1/keras/wrappers/__init__.py bazel-out/host/genfiles/tensorflow/_api/v1/keras/wrappers/scikit_learn/__init__.py bazel-out/host/genfiles/tensorflow/_api/v1/layers/__init__.py bazel-out/host/genfiles/tensorflow/_api/v1/linalg/__init__.py bazel-out/host/genfiles/tensorflow/_api/v1/logging/__init__.py bazel-out/host/genfiles/tensorflow/_api/v1/losses/__init__.py bazel-out/host/genfiles/tensorflow/_api/v1/manip/__init__.py bazel-out/host/genfiles/tensorflow/_api/v1/math/__init__.py bazel-out/host/genfiles/tensorflow/_api/v1/metrics/__init__.py bazel-out/host/genfiles/tensorflow/_api/v1/nn/__init__.py bazel-out/host/genfiles/tensorflow/_api/v1/nn/rnn_cell/__init__.py bazel-out/host/genfiles/tensorflow/_api/v1/profiler/__init__.py bazel-out/host/genfiles/tensorflow/_api/v1/python_io/__init__.py bazel-out/host/genfiles/tensorflow/_api/v1/quantization/__init__.py bazel-out/host/genfiles/tensorflow/_api/v1/random/__init__.py bazel-out/host/genfiles/tensorflow/_api/v1/resource_loader/__init__.py bazel-out/host/genfiles/tensorflow/_api/v1/strings/__init__.py bazel-out/host/genfiles/tensorflow/_api/v1/saved_model/__init__.py bazel-out/host/genfiles/tensorflow/_api/v1/saved_model/builder/__init__.py bazel-out/host/genfiles/tensorflow/_api/v1/saved_model/constants/__init__.py bazel-out/host/genfiles/tensorflow/_api/v1/saved_model/loader/__init__.py bazel-out/host/genfiles/tensorflow/_api/v1/saved_model/main_op/__init__.py bazel-out/host/genfiles/tensorflow/_api/v1/saved_model/signature_constants/__init__.py bazel-out/host/genfiles/tensorflow/_api/v1/saved_model/signature_def_utils/__init__.py bazel-out/host/genfiles/tensorflow/_api/v1/saved_model/tag_constants/__init__.py bazel-out/host/genfiles/tensorflow/_api/v1/saved_model/utils/__init__.py bazel-out/host/genfiles/tensorflow/_api/v1/sets/__init__.py bazel-out/host/genfiles/tensorflow/_api/v1/sparse/__init__.py bazel-out/host/genfiles/tensorflow/_api/v1/spectral/__init__.py bazel-out/host/genfiles/tensorflow/_api/v1/summary/__init__.py bazel-out/host/genfiles/tensorflow/_api/v1/sysconfig/__init__.py bazel-out/host/genfiles/tensorflow/_api/v1/test/__init__.py bazel-out/host/genfiles/tensorflow/_api/v1/train/__init__.py bazel-out/host/genfiles/tensorflow/_api/v1/train/queue_runner/__init__.py bazel-out/host/genfiles/tensorflow/_api/v1/user_ops/__init__.py')
Traceback (most recent call last):
  File "/home/nvidia/.cache/bazel/_bazel_nvidia/01c445c7b00bca0241913a79fcd99718/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/create_tensorflow.python_api_1.runfiles/org_tensorflow/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/home/nvidia/.cache/bazel/_bazel_nvidia/01c445c7b00bca0241913a79fcd99718/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/create_tensorflow.python_api_1.runfiles/org_tensorflow/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/home/nvidia/.cache/bazel/_bazel_nvidia/01c445c7b00bca0241913a79fcd99718/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/create_tensorflow.python_api_1.runfiles/org_tensorflow/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/usr/lib/python3.5/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/usr/lib/python3.5/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: /home/nvidia/.cache/bazel/_bazel_nvidia/01c445c7b00bca0241913a79fcd99718/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/create_tensorflow.python_api_1.runfiles/org_tensorflow/tensorflow/python/_pywrap_tensorflow_internal.so: undefined symbol: _ZN3Aws11Environment6GetEnvB5cxx11EPKc

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nvidia/.cache/bazel/_bazel_nvidia/01c445c7b00bca0241913a79fcd99718/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/create_tensorflow.python_api_1.runfiles/org_tensorflow/tensorflow/python/tools/api/generator/create_python_api.py", line 27, in <module>
    from tensorflow.python.tools.api.generator import doc_srcs
  File "/home/nvidia/.cache/bazel/_bazel_nvidia/01c445c7b00bca0241913a79fcd99718/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/create_tensorflow.python_api_1.runfiles/org_tensorflow/tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/home/nvidia/.cache/bazel/_bazel_nvidia/01c445c7b00bca0241913a79fcd99718/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/create_tensorflow.python_api_1.runfiles/org_tensorflow/tensorflow/python/pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/home/nvidia/.cache/bazel/_bazel_nvidia/01c445c7b00bca0241913a79fcd99718/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/create_tensorflow.python_api_1.runfiles/org_tensorflow/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/home/nvidia/.cache/bazel/_bazel_nvidia/01c445c7b00bca0241913a79fcd99718/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/create_tensorflow.python_api_1.runfiles/org_tensorflow/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/home/nvidia/.cache/bazel/_bazel_nvidia/01c445c7b00bca0241913a79fcd99718/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/create_tensorflow.python_api_1.runfiles/org_tensorflow/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/usr/lib/python3.5/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/usr/lib/python3.5/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: /home/nvidia/.cache/bazel/_bazel_nvidia/01c445c7b00bca0241913a79fcd99718/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/create_tensorflow.python_api_1.runfiles/org_tensorflow/tensorflow/python/_pywrap_tensorflow_internal.so: undefined symbol: _ZN3Aws11Environment6GetEnvB5cxx11EPKc


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.
Target //tensorflow/tools/pip_package:build_pip_package failed to build
INFO: Elapsed time: 25367.470s, Critical Path: 430.44s
INFO: 8521 processes: 8521 local.
FAILED: Build did NOT complete successfully

**Comment by mihaimaruseac** [comment]
At this point I would try recloning the branch on a different directory and recompiling again. Perhaps something else changed?

**Comment by mihaimaruseac** [comment]
Any updates? Did recloning and recompiling work?

**Comment by IeiuniumLux** [comment]
@mihaimaruseac,  I re-cloned the branch on a different directory and recompiled again.  Unfortunately, it crashed because it ran out of disk space after 6 hours into the build.

I'm now going to build it on another TX2 system.  I'll post an update.

BTW, should I build TF-1.13.1 with Bazel 0.19.2 instead TF-1.12.0 with Bazel 0.15.0?

OR, should I save myself time and just install the version from Nvidia ?

https://developer.nvidia.com/embedded/downloads#?search=tensorflow

**Comment by mihaimaruseac** [comment]
I'd recommend to use the newest version if you want to compile by yourself.

If you can use a precompiled binary, that's better

**Comment by IeiuniumLux** [comment]
@mihaimaruseac By newest version, do you mean TF-1.13.1 ?  

And by a precompiled binary, do you mean install the version from [Nvidia](https://developer.nvidia.com/embedded/downloads#?search=tensorflow) and forget about build it myself?

**Comment by mihaimaruseac** [comment]
Yes to both of the questions. For the first one, you can also try master.

**Comment by IeiuniumLux** [comment]
@mihaimaruseac In that case, then I'm going to go with the TF-1.13.1 precompiled binary version from Nvidia and save myself from the trouble of spending 6+ hours building it from source.  Thank you for time and assistance with this.
