### ISSUE TITLE
TypeError: cannot unpack non-iterable NoneType object

### ISSUE THREAD

**Issue by SlowMonk** [tensorflow/tensorflow#28833]
loss = tf.losses.mean_squared_error(labels,logits)
cnn_optimizer = tf.keras.optimizers.Adam(1e-4)

# Notice the use of `tf.function`
# This annotation causes the function to be "compiled".
#@tf.function
def train_step(logits,labels):    
    with tf.GradientTape() as cnn_tape:
        print("train_step")
        loss = tf.losses.mean_squared_error(labels,logits)
        #print("loss",loss)
        gradient_of_cnn = cnn_tape.gradient(loss,model.trainable_variables)
        cnn_optimizer.apply_gradients(gradient_of_cnn)

def train(train_dataset,train_labels_dataset,epochs):
    for epoch in range(epochs):
        start = time.time()
        
        for train_batch,label_batch in zip(train_dataset,train_labels_dataset):
            print(train_batch.shape,label_batch.shape)
            logits = tf.argmax(train_batch)
            labels = label_batch
            train_step(logits,labels)
            
        if (epoch + 1) % 15 == 0:
            checkpoint.save(file_prefix = checkpoint_prefix)
        print ('Time for epoch {} is {} sec'.format(epoch + 1, time.time()-start))

%%time
train(train_dataset,train_labels_dataset, EPOCHS)

(256, 28, 28, 1) (256,)
train_step
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<timed eval> in <module>()

<ipython-input-16-6e197a4fd13b> in train(train_dataset, train_labels_dataset, epochs)
      7             logits = tf.argmax(train_batch)
      8             labels = label_batch
----> 9             train_step(logits,labels)
     10 
     11         if (epoch + 1) % 15 == 0:

<ipython-input-15-c1d555ba6f91> in train_step(logits, labels)
      8         #print("loss",loss)
      9         gradient_of_cnn = cnn_tape.gradient(loss,model.trainable_variables)
---> 10         cnn_optimizer.apply_gradients(gradient_of_cnn)

~/anaconda3/lib/python3.7/site-packages/tensorflow/python/keras/optimizer_v2/optimizer_v2.py in apply_gradients(self, grads_and_vars, name)
    394       ValueError: If none of the variables have gradients.
    395     """
--> 396     grads_and_vars = _filter_grads(grads_and_vars)
    397     var_list = [v for (_, v) in grads_and_vars]
    398 

~/anaconda3/lib/python3.7/site-packages/tensorflow/python/keras/optimizer_v2/optimizer_v2.py in _filter_grads(grads_and_vars)
    914   filtered = []
    915   vars_with_empty_grads = []
--> 916   for grad, var in grads_and_vars:
    917     if grad is None:
    918       vars_with_empty_grads.append(var)

TypeError: cannot unpack non-iterable NoneType object

**Comment by achandraa** [comment]
Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version. Also, did you compile from source or install a binary?

Make sure you also include the exact code snippet to depict the problem. If you are unclear what to include see the issue template displayed in [the Github new issue template](https://github.com/tensorflow/tensorflow/issues/new/choose).

We ask for this in the issue submission template, because it is really difficult to help without that information. Thanks!

**Comment by achandraa** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Comment by anshikasaxena05** [comment]
def gradient_descent(init_m,init_c,x,t,learning_rate,iterations,error_threshold):
    m=init_m
    c=init_c
    error_values=list()
    mc_values=list()
    for i in range(iterations):
        e=error(m,x,c,t)
        if e<error_threshold:
            print('ERROR')
            break
            error_values.append(e)
            m,c=update(m,x,c,t,learning_rate)
            mc_values.append((m,c))
            return m,c,error_values,mc_values
init_m=0.9
init_c=0
learning_rate=0.001
iterations=100
error_threshold=0.001

m,c,error_values,mc_values= gradient_descent(init_m, init_c, xtrain, ytrain,learning_rate,iterations,error_threshold)

**I am getting this error please help**


TypeError                                 Traceback (most recent call last)
<ipython-input-26-b291d8eef5c0> in <module>
      5 error_threshold=0.001
      6 
----> 7 m,c,error_values,mc_values= gradient_descent(init_m, init_c, xtrain, ytrain,learning_rate,iterations,error_threshold)

TypeError: cannot unpack non-iterable NoneType object

**Comment by aviral-31** [comment]
> def gradient_descent(init_m,init_c,x,t,learning_rate,iterations,error_threshold):
> m=init_m
> c=init_c
> error_values=list()
> mc_values=list()
> for i in range(iterations):
> e=error(m,x,c,t)
> if e<error_threshold:
> print('ERROR')
> break
> error_values.append(e)
> m,c=update(m,x,c,t,learning_rate)
> mc_values.append((m,c))
> return m,c,error_values,mc_values
> init_m=0.9
> init_c=0
> learning_rate=0.001
> iterations=100
> error_threshold=0.001
> 
> m,c,error_values,mc_values= gradient_descent(init_m, init_c, xtrain, ytrain,learning_rate,iterations,error_threshold)
> 
> **I am getting this error please help**
> 
> TypeError Traceback (most recent call last)
> in
> 5 error_threshold=0.001
> 6
> ----> 7 m,c,error_values,mc_values= gradient_descent(init_m, init_c, xtrain, ytrain,learning_rate,iterations,error_threshold)
> 
> TypeError: cannot unpack non-iterable NoneType object

Hi Anshika. I had the same problem. Just found out that my indents in defining the update and gradient descent functions were incorrect. Indents are the spaces at the start of a command. Usually, they're taking care of by python but make sure that the return function is properly indented. Tell me if this solves your problem.
