### ISSUE TITLE
No gradients provided for any variable: ['cnn_model_14/conv2d_42/kernel:0', 'cnn_model_14/conv2d_42/bias:0', 'cnn_model_14/conv2d_43/kernel:0', 'cnn_model_14/conv2d_43/bias:0', 'cnn_model_14/dense_28/kernel:0', 'cnn_model_14/dense_28/bias:0', 'cnn_model_14/dense_29/kernel:0', 'cnn_model_14/dense_29/bias:0'].

### ISSUE THREAD

**Issue by SlowMonk** [tensorflow/tensorflow#28836]
> ---------------------------------------------------------------------------
> ValueError                                Traceback (most recent call last)
> <timed eval> in <module>()
> 
> <ipython-input-92-4e8fa0eeafe4> in train(train_dataset, train_labels_dataset, epochs)
>       8             labels = label_batch
>       9             print('logits->',logits.shape , 'labels->',labels.shape)
> ---> 10             train_step(logits,labels)
>      11 
>      12         if (epoch + 1) % 15 == 0:
> 
> ~/anaconda3/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py in __call__(self, *args, **kwds)
>     424     # This is the first call of __call__, so we have to initialize.
>     425     initializer_map = {}
> --> 426     self._initialize(args, kwds, add_initializers_to=initializer_map)
>     427     if self._created_variables:
>     428       try:
> 
> ~/anaconda3/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py in _initialize(self, args, kwds, add_initializers_to)
>     368     self._concrete_stateful_fn = (
>     369         self._stateful_fn._get_concrete_function_internal_garbage_collected(  # pylint: disable=protected-access
> --> 370             *args, **kwds))
>     371 
>     372     def invalid_creator_scope(*unused_args, **unused_kwds):
> 
> ~/anaconda3/lib/python3.7/site-packages/tensorflow/python/eager/function.py in _get_concrete_function_internal_garbage_collected(self, *args, **kwargs)
>    1311     if self._input_signature:
>    1312       args, kwargs = None, None
> -> 1313     graph_function, _, _ = self._maybe_define_function(args, kwargs)
>    1314     return graph_function
>    1315 
> 
> ~/anaconda3/lib/python3.7/site-packages/tensorflow/python/eager/function.py in _maybe_define_function(self, args, kwargs)
>    1578           or call_context_key not in self._function_cache.missed):
>    1579         self._function_cache.missed.add(call_context_key)
> -> 1580         graph_function = self._create_graph_function(args, kwargs)
>    1581         self._function_cache.primary[cache_key] = graph_function
>    1582         return graph_function, args, kwargs
> 
> ~/anaconda3/lib/python3.7/site-packages/tensorflow/python/eager/function.py in _create_graph_function(self, args, kwargs, override_flat_arg_shapes)
>    1510             arg_names=arg_names,
>    1511             override_flat_arg_shapes=override_flat_arg_shapes,
> -> 1512             capture_by_value=self._capture_by_value),
>    1513         self._function_attributes)
>    1514 
> 
> ~/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/func_graph.py in func_graph_from_py_func(name, python_func, args, kwargs, signature, func_graph, autograph, autograph_options, add_control_dependencies, arg_names, op_return_value, collections, capture_by_value, override_flat_arg_shapes)
>     692                                           converted_func)
>     693 
> --> 694       func_outputs = python_func(*func_args, **func_kwargs)
>     695 
>     696       # invariant: `func_outputs` contains only Tensors, IndexedSlices,
> 
> ~/anaconda3/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py in wrapped_fn(*args, **kwds)
>     315         # __wrapped__ allows AutoGraph to swap in a converted function. We give
>     316         # the function a weak reference to itself to avoid a reference cycle.
> --> 317         return weak_wrapped_fn().__wrapped__(*args, **kwds)
>     318     weak_wrapped_fn = weakref.ref(wrapped_fn)
>     319 
> 
> ~/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/func_graph.py in wrapper(*args, **kwargs)
>     684                   optional_features=autograph_options,
>     685                   force_conversion=True,
> --> 686               ), args, kwargs)
>     687 
>     688         # Wrapping around a decorator allows checks like tf_inspect.getargspec
> 
> ~/anaconda3/lib/python3.7/site-packages/tensorflow/python/autograph/impl/api.py in converted_call(f, owner, options, args, kwargs)
>     390     return _call_unconverted(f, args, kwargs)
>     391 
> --> 392   result = converted_f(*effective_args, **kwargs)
>     393 
>     394   # The converted function's closure is simply inserted into the function's
> 
> /tmp/tmplz2l0k7l.py in tf__train_step(logits, labels)
>       5     loss = ag__.converted_call('mean_squared_error', tf.losses, ag__.ConversionOptions(recursive=True, verbose=0, strip_decorators=(tf.function, defun, ag__.convert, ag__.do_not_convert, ag__.converted_call), force_conversion=False, optional_features=(), internal_convert_user_code=True), (labels, logits), {})
>       6     gradient_of_cnn = ag__.converted_call('gradient', cnn_tape, ag__.ConversionOptions(recursive=True, verbose=0, strip_decorators=(tf.function, defun_1, ag__.convert, ag__.do_not_convert, ag__.converted_call), force_conversion=False, optional_features=(), internal_convert_user_code=True), (loss, model.trainable_variables), {})
> ----> 7     ag__.converted_call('apply_gradients', cnn_optimizer, ag__.ConversionOptions(recursive=True, verbose=0, strip_decorators=(tf.function, defun_2, ag__.convert, ag__.do_not_convert, ag__.converted_call), force_conversion=False, optional_features=(), internal_convert_user_code=True), (zip(gradient_of_cnn, model.trainable_variables),), {})
>       8 
>       9 
> 
> ~/anaconda3/lib/python3.7/site-packages/tensorflow/python/autograph/impl/api.py in converted_call(f, owner, options, args, kwargs)
>     265 
>     266   if not options.force_conversion and conversion.is_whitelisted_for_graph(f):
> --> 267     return _call_unconverted(f, args, kwargs)
>     268 
>     269   # internal_convert_user_code is for example turned off when issuing a dynamic
> 
> ~/anaconda3/lib/python3.7/site-packages/tensorflow/python/autograph/impl/api.py in _call_unconverted(f, args, kwargs)
>     186     return f.__self__.call(args, kwargs)
>     187 
> --> 188   return f(*args, **kwargs)
>     189 
>     190 
> 
> ~/anaconda3/lib/python3.7/site-packages/tensorflow/python/keras/optimizer_v2/optimizer_v2.py in apply_gradients(self, grads_and_vars, name)
>     394       ValueError: If none of the variables have gradients.
>     395     """
> --> 396     grads_and_vars = _filter_grads(grads_and_vars)
>     397     var_list = [v for (_, v) in grads_and_vars]
>     398 
> 
> ~/anaconda3/lib/python3.7/site-packages/tensorflow/python/keras/optimizer_v2/optimizer_v2.py in _filter_grads(grads_and_vars)
>     922   if not filtered:
>     923     raise ValueError("No gradients provided for any variable: %s." %
> --> 924                      ([v.name for _, v in grads_and_vars],))
>     925   if vars_with_empty_grads:
>     926     logging.warning(
> 
> ValueError: No gradients provided for any variable: ['cnn_model_14/conv2d_42/kernel:0', 'cnn_model_14/conv2d_42/bias:0', 'cnn_model_14/conv2d_43/kernel:0', 'cnn_model_14/conv2d_43/bias:0', 'cnn_model_14/dense_28/kernel:0', 'cnn_model_14/dense_28/bias:0', 'cnn_model_14/dense_29/kernel:0', 'cnn_model_14/dense_29/bias:0'].
> 
> 

====================================================================

```

from __future__ import absolute_import, division, print_function, unicode_literals

#!pip install tensorflow-gpu==2.0.0-alpha0
import tensorflow as tf

from tensorflow.keras import datasets, layers, models
print(tf.__version__)
import os
import time
import numpy as np


(train_images, train_labels), (test_images, test_labels) = datasets.mnist.load_data()

train_images = train_images.reshape((60000, 28, 28, 1))
test_images = test_images.reshape((10000, 28, 28, 1))

# Normalize pixel values to be between 0 and 1
train_images, test_images = train_images / 255.0, test_images / 255.0

# Load training and eval data
((train_data, train_labels),
 (eval_data, eval_labels)) = tf.keras.datasets.mnist.load_data()
train_data = train_data.reshape((60000,28,28,1))
eval_data = eval_data.reshape((10000,28,28,1))

train_data = train_data/np.float32(255)
train_labels = train_labels.astype(np.int32)  # not required

eval_data = eval_data/np.float32(255)
eval_labels = eval_labels.astype(np.int32)  # not required

EPOCHS = 50
noise_dim = 100
num_examples_to_generate = 16
BUFFER_SIZE = 60000
BATCH_SIZE = 256

# We will reuse this seed overtime (so it's easier)
# to visualize progress in the animated GIF)
seed = tf.random.normal([num_examples_to_generate, noise_dim])


# Batch and shuffle the data
train_dataset = tf.data.Dataset.from_tensor_slices(train_data).shuffle(BUFFER_SIZE).batch(BATCH_SIZE)
train_labels_dataset =  tf.data.Dataset.from_tensor_slices(train_labels).shuffle(BUFFER_SIZE).batch(BATCH_SIZE)


input_shape = (28,28.1)
class cnn_model(tf.keras.Model):
    def __init__(self):
        super(cnn_model,self).__init__()
        
        #self.conv1 = layers.Conv2D(32,(3,3),activation='relu',input_shape= input_shape)
        self.conv1 = layers.Conv2D(32, 3, 3, padding='same', activation='relu')
        self.maxpool = layers.MaxPool2D((2,2))
        self.conv2 = layers.Conv2D(64,(3,3),activation ='relu')
        self.conv3 = layers.Conv2D(128,(3,3),activation='relu')
        self.flatten = layers.Flatten()
        self.dense64 = layers.Dense(64,activation='relu')
        self.dense10 = layers.Dense(10,activation='relu')
        self.dropout = layers.Dropout(0.25)
    def call(self,inputs):
        x = self.conv1(inputs)
        x = self.conv2(x)
        x = self.maxpool(x)
        x = self.dropout(x)
        x = self.flatten(x)
        x = self.dense64(x)
        x = self.dense10(x)
        return x



model = cnn_model()
#result=tf.argmax(model(train_data[:10]))
labels = train_labels[:50]
logits = tf.argmax(model(train_data[:50]),axis=1)
#print(labelss.shape)
print(logits.shape , ':', labels.shape)
print('logits->',logits)
print("=======")
print('labels->',labels[1])
#print(train_labels[:10])


cnn_optimizer = tf.optimizers.Adam(1e-4)


checkpoint_dir = './training_checkpoints'
checkpoint_prefix = os.path.join(checkpoint_dir, "ckpt")
checkpoint = tf.train.Checkpoint(cnn_optimizer=cnn_optimizer)



# Notice the use of `tf.function`
# This annotation causes the function to be "compiled".
@tf.function
def train_step(logits,labels):    
    with tf.GradientTape() as cnn_tape:
        print("train_step")
        loss = tf.losses.mean_squared_error(labels,logits)
        #print("loss",loss)
        gradient_of_cnn = cnn_tape.gradient(loss,model.trainable_variables)
        
        cnn_optimizer.apply_gradients(zip(gradient_of_cnn,model.trainable_variables))
        
        #cnn_optimizer.minimize(loss,var_list=model.trainable_variables)


def train(train_dataset,train_labels_dataset,epochs):
    for epoch in range(epochs):
        start = time.time()
        
        for train_batch,label_batch in zip(train_dataset,train_labels_dataset):
            print(train_batch.shape,label_batch.shape)
            logits = tf.argmax(model(train_batch),axis=1)
            labels = label_batch
            print('logits->',logits.shape , 'labels->',labels.shape)
            train_step(logits,labels)
            
        if (epoch + 1) % 15 == 0:
            checkpoint.save(file_prefix = checkpoint_prefix)
        print ('Time for epoch {} is {} sec'.format(epoch + 1, time.time()-start))


%%time
train(train_dataset,train_labels_dataset, EPOCHS)
```

**Comment by achandraa** [comment]
Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version. Also, did you compile from source or install a binary?

Make sure you also include the code snippet to depict the problem. If you are unclear what to include see the issue template displayed in [the Github new issue template](https://github.com/tensorflow/tensorflow/issues/new/choose).

We ask for this in the issue submission template, because it is really difficult to help without that information. Thanks!

**Comment by jiarenyf** [comment]
I have also meet the problem, if I removed the `@tf.function` above the `train_step` function, the model ran successfully. However, when I added the `@tf.function` above the `train_step` function, error came. The error was: `ValueError: No gradients provided for any variable`.

This is my code:
```
def train():
    loss_fn = LOSS_DICT[ARGS.loss]
    model, block_size = NETWORK_DICT[ARGS.network]()
    dataset_train = read_data(
        ARGS.batch_size_train, ARGS.label_file_train, True, ARGS.workers, block_size)

    if not os.path.exists(ARGS.model_dir):
        os.mkdir(ARGS.model_dir)
    checkpoint = tf.train.latest_checkpoint(ARGS.model_dir)
    begin_epoch = int(checkpoint.split('-')[-1])+1 if checkpoint else 1

    logger = MyLogger(ARGS.record_path)
    optimizer = tk.optimizers.SGD(learning_rate=ARGS.learning_rate)

    @tf.function
    def train_step(step, batch_data):
        imgs, labels, imgs_width, labels_len = batch_data
        with tf.GradientTape() as tape:
            logits = model(imgs, training=True)
            logits_len = tf.cast(tf.math.ceil(
                tf.divide(imgs_width, block_size)), tf.int32)
            loss, accuracy, prediction = loss_fn(
                labels, logits, labels_len, logits_len, CLASSES)
        grads = tape.gradient(loss, model.trainable_variables)
        optimizer.apply_gradients(zip(grads, model.trainable_variables))

        loss_mean = np.mean(loss.numpy())
        accuracy_mean = np.mean(accuracy.numpy())
        print(f'Loss of step#{step+1} is {loss_mean} ...')
        print(f'Accruacy of step#{step+1} is {accuracy_mean} ...')

    for epoch in range(begin_epoch, ARGS.epoches+begin_epoch):
        print(f'Epoch {epoch} start ...')
        for step, batch_data in enumerate(dataset_train):
            train_step(step, batch_data)

        quit()
        print(f'Epoch {epoch} finish ...')
    logger.close()
    # delete_not_best_models(ARGS.model_prefix, best_test_epoch)
```

@achandraa Could you please help me, thanks.

**Comment by achandraa** [comment]
@jiarenyf : Apology for delayed response. Please open a new issue by following the [Template.](https://github.com/tensorflow/tensorflow/issues/new/choose) 

Meanwhile let me close this issue due to lack of recent activities. Thanks!

**Comment by UdiBhaskar** [comment]
I am also getting the same issue.
