### ISSUE TITLE
TFLite GPU support for C++

### ISSUE THREAD

**Issue by hoonkai** [tensorflow/tensorflow#28838]
**System information**
- TensorFlow version (you are using): 0.0.1-gpu-experimental
- Are you willing to contribute it (Yes/No): Yes

**Describe the feature and the current behavior/state.**

Anyone know if Tensorflow Lite has GPU support for C++ (or Python)? I've seen guides for Android and iOS, but I haven't come across anything about C++ (or Python).

**Who will benefit with this feature?**

C++ and Python developers.

**Comment by freedomtan** [comment]
Check the [READE.md](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/delegates/gpu/README.md) of `tensorflow/lite/delegates/gpu/`. I added GPU delegate to label_image and sent PR https://github.com/tensorflow/tensorflow/pull/27464. TFLite [benchmark_model](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/tools/benchmark) supports GPU delegate already. I don't think the GPU delegate is exported Python.

**Comment by hoonkai** [comment]
@freedomtan Thanks for the pointer. If my understanding of the code is correct, GPU delegates are only used on Android. Can delegates work on desktop?

**Comment by freedomtan** [comment]
Yes, as far as I know, current GL ES and Metal backends were for Android and iOS. But, it should be possible to make the GL ES compute shader backend work on non-Android platforms. I didn't try. With some hacks, I made the iOS Metal backend work on my iMac before.

**Comment by impjdi** [comment]
@hoonkai 

Some of our engineers were able to run the GPU delegate on desktop with Mesa, but it's not a use case we can support as ... I am one of the people who couldn't get it to work.  Also, the optimization parameters may not be applicable for desktop use.  You're welcome to try out, but I wouldn't be able to support any problems with it :(
