### ISSUE TITLE
GPU visible device selection causes segfault in tf-nightly-gpu

### ISSUE THREAD

**Issue by alsrgv** [tensorflow/tensorflow#28845]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): no
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 16.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): 
- TensorFlow version (use command below): tf-nightly-gpu==1.14.1.dev20190519
- Python version: 2.7
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 10.0
- GPU model and memory:

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
The following code causes a segfault:
```python
import tensorflow as tf

config = tf.ConfigProto()
config.gpu_options.visible_device_list = '0'
sess = tf.Session(config=config)
print(sess)
```

**Describe the expected behavior**
No segfault.  GPU pinning should work.

cc @jaingaurav

**Comment by alsrgv** [comment]
It looks like https://github.com/tensorflow/tensorflow/pull/28885 pulled whatever caused this issue into r1.14. Could you make sure the fix gets picked into r1.14 as well?

cc @annarev

**Comment by yifeif** [comment]
I tried gdb on this and saw it failed at `
Thread 1 "python" received signal SIGSEGV, Segmentation fault.
0x00007fff2608c6fa in stream_executor::StreamExecutorMemoryAllocator::StreamExecutorMemoryAllocator(stream_executor::Platform const*, absl::Span<stream_executor::StreamExecutor* const>) () from /.env/local/lib/python2.7/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so`
@skye @hawkinsp could this be related to the recent StreamExecutorMemoryAllocator changes?

**Comment by cheshire** [comment]
@alsrgv Could you verify that https://github.com/tensorflow/tensorflow/commit/fc2863425d742585b6e7d8b0ae9d008d2bfbe72f fixes the issue? I'll be cherry-picking it into r1.14.

**Comment by alsrgv** [comment]
@cheshire, the fix works, thanks!

**Comment by yifeif** [comment]
Thanks @cheshire!
