### ISSUE TITLE
TF2.0 DocSprint Prep - Error with Dataset Example

### ISSUE THREAD

**Issue by netskink** [tensorflow/tensorflow#28843]
## URL(s) with the issue:

https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/data/Dataset

## Description of issue (what needs changing):

The Example for "from_generator" fails.

### Clear description

This example uses tf.enable_eager_execution() which gives the following error
AttributeError: module 'tensorflow' has no attribute 'enable_eager_execution'

If you remove this line of code the example runs but identifies this code is deprecated in TF V2.

### Correct links

I do not see a link to the source.

### Parameters defined

The parameters are defined but the example only uses three of the four parameters.  The last parameter is optional but not shown how to be used.

### Returns defined

The return code is defined correctly as a dataset.

### Raises listed and defined

Are the errors defined? For example,
https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/feature_column/categorical_column_with_vocabulary_file#raises

### Usage example

There is a usage example.  This PR is regarding the example.

### Request visuals, if applicable

There are not example.

### Submit a pull request?
yes
https://github.com/tensorflow/tensorflow/pull/28842

Are you planning to also submit a pull request to fix the issue? See the docs
contributor guide: https://www.tensorflow.org/community/contribute/docs and the
docs style guide: https://www.tensorflow.org/community/contribute/docs_style
yes
https://github.com/tensorflow/tensorflow/pull/28842

**Comment by achandraa** [comment]
@netskink : Thank you for bringing this out.

**Comment by netskink** [comment]
You are welcome achandraa.  Yesterday there was discussion regarding the branches.  Is 2.0 updates going into master branch or r2.0 branch?

**Comment by achandraa** [comment]
Yes you are right. The updates for 2.0 are going to r2.0 branch as of now.

**Comment by ymodak** [comment]
This is fixed now. Thanks!
https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/data/Dataset#for_example_3
