### ISSUE TITLE
TFLiteConverterV2 has no attribute 'from_saved_model'

### ISSUE THREAD

**Issue by pharrellyhy** [tensorflow/tensorflow#28856]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): **No**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): **Ubuntu 16.04**
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version (use command below): **v1.12.0-9492-g2c319fb415 2.0.0-alpha0**
- Python version: **3.6**
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: **9.0/7.1.4**
- GPU model and memory:

**Describe the current behavior**
When running `tf.lite.TFLiteConverter.from_saved_model(saved_model_path)`, an error occurs as described in the title.

**Describe the expected behavior**
The TF lite converter should work properly.

**Code to reproduce the issue**
Just follow the sample code in [here](https://www.tensorflow.org/lite/r2/convert/python_api)
```
import tensorflow as tf
root = tf.train.Checkpoint()
root.v1 = tf.Variable(3.)
root.v2 = tf.Variable(2.)
root.f = tf.function(lambda x: root.v1 * root.v2 * x)

export_dir = '/tmp/test_saved_model'
input_data = tf.constant(1., shape=[1, 1])
to_save = root.f.get_concrete_function(input_data)
tf.saved_model.save(root, export_dir, to_save)

converter = tf.lite.TFLiteConverter.from_saved_model(export_dir)
tflite_model = converter.convert()
```

**Comment by gargn** [comment]
`from_saved_model` wasn't added until after the alpha was released. Details are available in the comment here: https://www.tensorflow.org/lite/r2/convert/python_api. Can you upgrade to `tf-nightly-2.0-preview` and rerun your code?

**Comment by pharrellyhy** [comment]
@gargn I originally compiled tf-2.0 from source and had the same issue. Then I switched to tf-1.12. Here is the version of my tf-2.0: `v2.0.0-alpha0-4-g2c2d508 2.0.0-alpha0`.

**Comment by gargn** [comment]
I installed last night's `tf-nightly-2.0-preview` using `pip install tf-nightly-2.0-preview` (specifically `2.0.0.dev20190529`) and ran the code you provided without error.

**Comment by gargn** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
