### ISSUE TITLE
tf.summary.image does not work with keras layers in tf 2.0 due to EagerExecution issues

### ISSUE THREAD

**Issue by 2649** [tensorflow/tensorflow#28868]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Official tf docker 
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):No
- TensorFlow version (use command below):2.0.0-alpha0
- Python version: 3.5
- CUDA/cuDNN version: 10.1
- GPU model and memory:Titan V

I use tf.keras subclassing, but when I want to track the some images in my network, the error at the bottom of the post occurs. Initially,  I think the reason for the error is, that `tf.summary.image` becomes a normal Tensor as input, but needs an eagerTensor. If I create a random tensor in the summary function and evaluate the type it is an eagerTensor, but if I use a Tensor from a `keras.layers.Layer` class it evaluates to a normal Tensor and throws the error (you can try it in your code). 

First I thought that the `tf.dataset` returns a non-eager tensor, but if I use a numpy array as input, the same error occurs as well. So the error might be caused by the `keras.layer.Layer` class.

The error occurs on GPU and CPU.

**Working example**
```
import tensorflow as tf
import numpy as np

inp_arr_without_ds = np.random.rand(2, 200, 200, 3)

inp_arr_4_ds = np.random.rand(2, 2, 200, 200, 3)
tf_ds = tf.data.Dataset.from_tensor_slices((inp_arr_4_ds, inp_arr_4_ds))
tf_ds = tf_ds.map(lambda x, y: (x, y)).repeat(10).shuffle(10)

class random_model(tf.keras.Model):
    
    def __init__(self, name):
        super(random_model, self).__init__(name=name)
        self.conv_1 = tf.keras.layers.Conv2D(3, [3, 3], padding="same")
        self.tf_board_writer = tf.summary.create_file_writer("test")
        self.img_callback = [tf.keras.callbacks.LambdaCallback(on_epoch_end=self.save_img)]
        
    def call(self, inputs):
        self.initialized_layer = self.conv_1(inputs)
        return self.initialized_layer
    
    def save_img(self, epochs, logs):
        with self.tf_board_writer.as_default():
            # Does not work: type: class 'tensorflow.python.framework.ops.Tensor' 
            tf.summary.image("image", self.initialized_layer, step=epochs)
            
            # Does work type: class 'tensorflow.python.framework.ops.EagerTensor'
            #tf.summary.image("image", tf.random.uniform([2, 200, 200, 3]), step=epochs) 
            
    def compile_model(self):
        self.compile(tf.optimizers.Adam(0.001), tf.losses.mean_absolute_error)
    
    def fit_model_with_ds(self, ds):
        self.fit(ds, callbacks=self.img_callback)
        
    def fit_model_with_array(self, x, y):
        self.fit(x, y, callbacks=self.img_callback)

print(tf.__version__)        

# Both do not work
non_ds_model = random_model("non_ds") 
non_ds_model.compile_model()
non_ds_model.fit_model_with_array(inp_arr_without_ds, inp_arr_without_ds)
            
tf_ds_model = random_model("tf_ds")
tf_ds_model.compile_model()
tf_ds_model.fit_model_with_ds(tf_ds)
```

    
    

> **Error Message**
```
> 2.0.0-alpha0
> 
> ---------------------------------------------------------------------------
> TypeError                                 Traceback (most recent call last)
> <ipython-input-25-0b5a4b30a43a> in <module>
>      39 non_ds_model = random_model("non_ds")
>      40 non_ds_model.compile_model()
> ---> 41 non_ds_model.fit_model_with_array(inp_arr_without_ds, inp_arr_without_ds)
>      42 
>      43 tf_ds_model = random_model("tf_ds")
> 
> <ipython-input-25-0b5a4b30a43a> in fit_model_with_array(self, x, y)
>      32 
>      33     def fit_model_with_array(self, x, y):
> ---> 34         self.fit(x, y, callbacks=self.img_callback)
>      35 
>      36 print(tf.__version__)
> 
> /usr/local/lib/python3.5/dist-packages/tensorflow/python/keras/engine/training.py in fit(self, x, y, batch_size, epochs, verbose, callbacks, validation_split, validation_data, shuffle, class_weight, sample_weight, initial_epoch, steps_per_epoch, validation_steps, validation_freq, max_queue_size, workers, use_multiprocessing, **kwargs)
>     871           validation_steps=validation_steps,
>     872           validation_freq=validation_freq,
> --> 873           steps_name='steps_per_epoch')
>     874 
>     875   def evaluate(self,
> 
> /usr/local/lib/python3.5/dist-packages/tensorflow/python/keras/engine/training_arrays.py in model_iteration(model, inputs, targets, sample_weights, batch_size, epochs, verbose, callbacks, val_inputs, val_targets, val_sample_weights, shuffle, initial_epoch, steps_per_epoch, validation_steps, validation_freq, mode, validation_in_fit, prepared_feed_values_from_dataset, steps_name, **kwargs)
>     406     if mode == ModeKeys.TRAIN:
>     407       # Epochs only apply to `fit`.
> --> 408       callbacks.on_epoch_end(epoch, epoch_logs)
>     409     progbar.on_epoch_end(epoch, epoch_logs)
>     410 
> 
> /usr/local/lib/python3.5/dist-packages/tensorflow/python/keras/callbacks.py in on_epoch_end(self, epoch, logs)
>     288     logs = logs or {}
>     289     for callback in self.callbacks:
> --> 290       callback.on_epoch_end(epoch, logs)
>     291 
>     292   def on_train_batch_begin(self, batch, logs=None):
> 
> <ipython-input-25-0b5a4b30a43a> in save_img(self, epochs, logs)
>      20         with self.tf_board_writer.as_default():
>      21             # Does not work: type: class 'tensorflow.python.framework.ops.Tensor'
> ---> 22             tf.summary.image("image", self.initialized_layer, step=epochs)
>      23 
>      24             # Does work type: class 'tensorflow.python.framework.ops.EagerTensor'
> 
> /usr/local/lib/python3.5/dist-packages/tensorboard/plugins/image/summary_v2.py in image(name, data, step, max_outputs, description)
>      71     encoded_images = tf.map_fn(tf.image.encode_png, limited_images,
>      72                                dtype=tf.string,
> ---> 73                                name='encode_each_image')
>      74     # Workaround for map_fn returning float dtype for an empty elems input.
>      75     encoded_images = tf.cond(
> 
> /usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/map_fn.py in map_fn(fn, elems, dtype, parallel_iterations, back_prop, swap_memory, infer_shape, name)
>     226                                      dynamic_size=False,
>     227                                      infer_shape=True)
> --> 228         for elem in elems_flat]
>     229     # Unpack elements
>     230     elems_ta = [
> 
> /usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/map_fn.py in <listcomp>(.0)
>     226                                      dynamic_size=False,
>     227                                      infer_shape=True)
> --> 228         for elem in elems_flat]
>     229     # Unpack elements
>     230     elems_ta = [
> 
> /usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/tensor_array_ops.py in __init__(self, dtype, size, dynamic_size, clear_after_read, tensor_array_name, handle, flow, infer_shape, element_shape, colocate_with_first_write_call, name)
>    1036         element_shape=element_shape,
>    1037         colocate_with_first_write_call=colocate_with_first_write_call,
> -> 1038         name=name)
>    1039 
>    1040     self._implementation.parent = weakref.ref(self)
> 
> /usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/tensor_array_ops.py in __init__(***failed resolving arguments***)
>     742     if isinstance(size, ops.EagerTensor):
>     743       size = size.numpy()
> --> 744     self._tensor_array = [None for _ in range(size)]
>     745 
>     746   @property
> 
> TypeError: 'Tensor' object cannot be interpreted as an integer
> 

```

**Comment by muddham** [comment]
@2649 Ran the provided code, it says NameError: name 'map_ds' is not defined. Please provide full reproducible code to investigate it further.

**Comment by 2649** [comment]
@muddham Sorry, my bad. This was an old variable. Now you can run it.

**Comment by 2649** [comment]
@muddham investigated further the problem and when you evaluate `tf.executing_eagerly()` in every function, only the `call()` function evaluates to `False`. I am not sure if this is expected or not?

**Comment by muddham** [comment]
@2649 Able to reproduce the issue with th provided code.

TypeError: 'Tensor' object cannot be interpreted as an integer

**Comment by 2649** [comment]
Any ideas?

**Comment by jvishnuvardhan** [comment]
@2649 I think there is some issue with your callback code that is giving the error. If I remove the callback function from `model.fit` then there is no error. Please check the [gist here](https://colab.sandbox.google.com/gist/jvishnuvardhan/98cea0e3381567496b1dad4228fe4601/tf28868_keras_layers.ipynb). Thanks!

**Comment by 2649** [comment]
@jvishnuvardhan Yes this is correct. I already pointed it out in the first post. The tf 2.0 documentation recommends to use `tf.summary.image` to log image files. This function excepts an eager tensor. However, when you use keras to train your model,  it will build a static graph and the summary will throw the mentioned error.

**Comment by tanzhenyu** [comment]
Thanks for reporting.
This is by design. tf.keras in 2.0 automatically wrap the call in tf.function (to accelerate computation), so output is symbolic tensor, which then you used for callbacks.
To make this work, there are two approaches:
1) use the regular model fit with Tensorboard callback, or tf.print (whichever works in your case)
2) compile the model with run_eagerly=True, so that output is EagerTensor instead of symbolic tensor.

**Comment by mlippie** [comment]
This issue is not resolved for me. I use the regular fit function with the tensorboard callback, but I still get the same error. Setting the run_eagerly parameter also does not help. I use the output from a convolutional layer as input to the image summary operation.

Is there anything else I should be aware of to make this work?

**Comment by 2649** [comment]
I just switched from the keras compile and fit method to a custom training loop with gradient tape and wrap the computational parts in a `tf.function`. These are only few more lines of code, but you are very flexible. I'm very satisfied with this functionality. In between the `tf.function` calls you can use the `tf.summary` api, because it returns eager tensors. I used this [tutorial](https://www.tensorflow.org/beta/tutorials/generative/cvae).

**Comment by tanzhenyu** [comment]
@mlippie If there is something not working with model.fit and callback, can you file another bug and include your code snippet?

**Comment by shaolinkhoa** [comment]
Hi @tanzhenyu,
I tested with tensorflow-gpu 2.0.0-rc0 and still have this problem while using `tf.summary.image` with a `tf.keras.layer` of a model
`TypeError: 'Tensor' object cannot be interpreted as an integer`
I follow the [Using TensorBoard in Notebooks](https://www.tensorflow.org/tensorboard/r2/tensorboard_in_notebooks) . You can check [this notebook file](https://colab.research.google.com/drive/1HIe4EnwOomI0tC9vsVUcMX-zdbpV0QFU)

**Comment by fengyang0317** [comment]
@shaolinkhoa 
Have you solved this problem?

**Comment by shaolinkhoa** [comment]
@fengyang0317 
I'm sorry, I couldn't, therefore, I'm using Pytorch now.

**Comment by tnybny** [comment]
This issue should not be closed. Still experiencing this exact issue and the suggestions in [https://github.com/tensorflow/tensorflow/issues/28868#issuecomment-518076766](above comment) by @tanzhenyu are not fixes.

**Comment by Engineero** [comment]
Still experiencing this issue in TF2.1 and TF2.2

**Comment by courageon** [comment]
Just ran into this issue, tf.summary.image seems to not work with symbolic tensors. I'm trying to display output from a layer in my network.

**Comment by Farbdose** [comment]
>  Just ran into this issue, tf.summary.image seems to not work with symbolic tensors. I'm trying to display output from a layer in my network.

@courageon Not sure If i just ran into the _exactly_ same issue but I managed to fix mine with this:

```
output = myModel(input)
output = tf.convert_to_tensor(output.numpy().copy())
tf.summary.image("Preview", output, step=0)```
