### ISSUE TITLE
TF1.14 compile still fails with CUDA 10.1 ("Could not find any cublas_api.h")

### ISSUE THREAD

**Issue by plopresti** [tensorflow/tensorflow#28865]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): CentOS 7.6
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): Source
- TensorFlow version: r1.14 tag
- Python version: 3.6
- Installed using virtualenv? pip? conda?: venv
- Bazel version (if compiling from source): 0.24.1
- GCC/Compiler version (if compiling from source): 8.2.1
- CUDA/cuDNN version: 10.1/7.5.1
- GPU model and memory: V100

**Describe the problem**

CUDA build fails because cublas_api.h is now under /usr/include and not /usr/local/cuda/include. (And the r1.14 find_cuda_config.py script ignores TF_CUDA_PATHS when searching for cublas.)

This problem is fixed on master. Someone just needs to bring third_party/gpu/find_cuda_config.py to the r1.14 branch.

**Provide the exact sequence of commands / steps that you executed before running into the problem**

env TF_CUDA_PATHS=/usr/local/cuda,/usr ./configure
bazel build --config=opt --config=cuda //tensorflow/tools/pip_package:build_pip_package

**Any other info / logs**

Cuda Configuration Error: Failed to run find_cuda_config.py: Could not find any cublas_api.h matching version '' in any subdirectory:
        ''
        'include'
        'include/cuda'
        'include/*-linux-gnu'
        'extras/CUPTI/include'
        'include/cuda/CUPTI'
of:
        '/usr/local/cuda'

INFO: Elapsed time: 0.468s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)

**Comment by muddham** [comment]
@plopresti Can you please follow the steps [install TF from sources](https://www.tensorflow.org/install/source#tested_build_configurations). Please install 10.0 CUDA version and let us know how it progresses. Thanks!

**Comment by muddham** [comment]
@plopresti Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Comment by acifonelli** [comment]
Reopening the issue just because I faced the same problem on Windows.

**System Information**
- *OS Platform*: Windows 10
- *TensorFlow installed from (source or binary)*: Source
- *TensorFlow version*: master at 2fd2eff6cb
- *Python version*: 3.6.8
- *Bazel version (if compiling from source)*: 0.26.1
- *GCC/Compiler version (if compiling from source)*: MSVC Tools 19.20 (cl v.)
- *CUDA/cuDNN version*: 10.1/7.6.1
- *GPU model and memory*: Quadro P1000 4GB

**Describe the problem**
During the configuration process I specified the CUDA paths with as `C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1`. When Bazel launches `cuda_configure.bzl`, the `find_cuda_config.py` script is not able to locate the libraries because the paths are purged from the single back slashes.

**Provide the exact sequence of commands / steps that you executed before running into the problem**
I was following the steps provided on the [Build from source on Windows](https://www.tensorflow.org/install/source_windows) page. The error raised after launching the bazel compilation.

**Any other info/logs**
```
Reading rc options for 'build' from d:\tensorflow\.tf_configure.bazelrc:
'build' options:
    --action_env PYTHON_BIN_PATH=C:/Program Files/Python36/python.exe
    --action_env PYTHON_LIB_PATH=C:/Program Files/Python36/lib/site-packages
    --python_path=C:/Program Files/Python36/python.exe
    --action_env TF_CUDA_VERSION=10.1
    --action_env TF_CUDNN_VERSION=7.6.1
    --action_env TF_CUDA_PATHS=C:Program FilesNVIDIA GPU Computing ToolkitCUDAv10.1,C:localcudnn-10.1-v7.6.1cuda
    --action_env CUDA_TOOLKIT_PATH=C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.1
    --action_env TF_CUDA_COMPUTE_CAPABILITIES=6.1
    --config=cuda
    --config monolithic
    --copt=-w
    --host_copt=-w
    --copt=-DWIN32_LEAN_AND_MEAN
    --host_copt=-DWIN32_LEAN_AND_MEAN
    --copt=-DNOGDI
    --host_copt=-DNOGDI
    --verbose_failures
    --distinct_host_configuration=false
    --define=override_eigen_strong_inline=true
    --action_env TF_CONFIGURE_IOS=0
```

I moved forward adding an additional back slash to the paths I was specifying.

**Comment by AndreyPlotkinOr** [comment]
You may instead use backslashes, as in all other paths.
Worked for me.

**Comment by ayrtondenner** [comment]
What worked for me was editing the `find_cuda_config.py` file. I went to line 455, after the script updated variable base_paths by filtering paths that existed via `os.path.exists(path)`, and then I added a `base_paths.append("C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v10.1")` line, explicit adding to base_paths the CUDA path in my Windows 10. After that, `bazel build --config=v2 //tensorflow/tools/pip_package:build_pip_package` stopped complaining that it didn't find `cublas_api.h` file.

Observation: I had to run `configure.cmd` again, and even it started to find CUDA and cuDNN automatically, without the need to explicit inform their paths. Changing `find_cuda_config.py` also fixes `configure.cmd` calls.

**Comment by elvetian** [comment]
Adding BAZEL_VC environment variable for the VC++ build tool location solved it for me:
BAZEL_VC
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC

**Comment by redradist** [comment]
I have faced with the same issue:

For such path `C:\tools\cuda,C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1`:
```console
INFO: Repository local_config_cuda instantiated at:
  C:/tensorflow/WORKSPACE:19:16: in <toplevel>
  C:/tensorflow/tensorflow/workspace.bzl:98:19: in tf_repositories
Repository rule cuda_configure defined at:
  C:/tensorflow/third_party/gpus/cuda_configure.bzl:1399:33: in <toplevel>
ERROR: An error occurred during the fetch of repository 'local_config_cuda':
   Traceback (most recent call last):
        File "C:/tensorflow/third_party/gpus/cuda_configure.bzl", line 1369, column 38, in _cuda_autoconf_impl
                _create_local_cuda_repository(repository_ctx)
        File "C:/tensorflow/third_party/gpus/cuda_configure.bzl", line 955, column 35, in _create_local_cuda_repository
                cuda_config = _get_cuda_config(repository_ctx, find_cuda_config_script)
        File "C:/tensorflow/third_party/gpus/cuda_configure.bzl", line 657, column 30, in _get_cuda_config
                config = find_cuda_config(repository_ctx, find_cuda_config_script, ["cuda", "cudnn"])
        File "C:/tensorflow/third_party/gpus/cuda_configure.bzl", line 635, column 41, in find_cuda_config
                exec_result = _exec_find_cuda_config(repository_ctx, script_path, cuda_libraries)
        File "C:/tensorflow/third_party/gpus/cuda_configure.bzl", line 629, column 19, in _exec_find_cuda_config
                return execute(repository_ctx, [python_bin, "-c", decompress_and_execute_cmd])
        File "C:/tensorflow/third_party/remote_config/common.bzl", line 208, column 13, in execute
                fail(
Error in fail: Repository command failed
Could not find any cudnn.h, cudnn_version.h matching version '' in any subdirectory:
        ''
        'include'
        'include/cuda'
        'include/*-linux-gnu'
        'extras/CUPTI/include'
        'include/cuda/CUPTI'
of:
        'C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1'
ERROR: Skipping '//tensorflow/tools/pip_package:build_pip_package': no such package '@local_config_cuda//cuda': Repository command failed
Could not find any cudnn.h, cudnn_version.h matching version '' in any subdirectory:
        ''
        'include'
        'include/cuda'
        'include/*-linux-gnu'
        'extras/CUPTI/include'
        'include/cuda/CUPTI'
of:
        'C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1'
WARNING: Target pattern parsing failed.
ERROR: no such package '@local_config_cuda//cuda': Repository command failed
Could not find any cudnn.h, cudnn_version.h matching version '' in any subdirectory:
        ''
        'include'
        'include/cuda'
        'include/*-linux-gnu'
        'extras/CUPTI/include'
        'include/cuda/CUPTI'
of:
        'C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1'
INFO: Elapsed time: 0.381s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
    currently loading: tensorflow/tools/pip_package
```

And for such path `C:\\tools\\cuda,C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v10.1`:
```console
INFO: Repository local_config_cuda instantiated at:
  C:/tensorflow/WORKSPACE:19:16: in <toplevel>
  C:/tensorflow/tensorflow/workspace.bzl:98:19: in tf_repositories
Repository rule cuda_configure defined at:
  C:/tensorflow/third_party/gpus/cuda_configure.bzl:1399:33: in <toplevel>
ERROR: An error occurred during the fetch of repository 'local_config_cuda':
   Traceback (most recent call last):
        File "C:/tensorflow/third_party/gpus/cuda_configure.bzl", line 1369, column 38, in _cuda_autoconf_impl
                _create_local_cuda_repository(repository_ctx)
        File "C:/tensorflow/third_party/gpus/cuda_configure.bzl", line 1214, column 56, in _create_local_cuda_repository
                host_compiler_includes + _cuda_include_path(
        File "C:/tensorflow/third_party/gpus/cuda_configure.bzl", line 363, column 32, in _cuda_include_path
                inc_entries.append(realpath(repository_ctx, cuda_config.cuda_toolkit_path + "/include"))
        File "C:/tensorflow/third_party/remote_config/common.bzl", line 268, column 19, in realpath
                return execute(repository_ctx, [bash_bin, "-c", "realpath \"%s\"" % path]).stdout.strip()
        File "C:/tensorflow/third_party/remote_config/common.bzl", line 208, column 13, in execute
                fail(
Error in fail: Repository command failed
realpath: 'C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.1/include': No such file or directory
ERROR: Skipping '//tensorflow/tools/pip_package:build_pip_package': no such package '@local_config_cuda//cuda': Repository command failed
realpath: 'C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.1/include': No such file or directory
WARNING: Target pattern parsing failed.
ERROR: no such package '@local_config_cuda//cuda': Repository command failed
realpath: 'C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.1/include': No such file or directory
INFO: Elapsed time: 1.268s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
    currently loading: tensorflow/tools/pip_package
```

Why it so complicated to compile tensorflow for Windows ???

It seems for me that it is bunch of issues in python script on Windows ((

**Comment by redradist** [comment]
I have faced with another issue:

```console
If the definition of 'com_google_protobuf' was updated, verify that the hashes were also updated.
ERROR: An error occurred during the fetch of repository 'com_google_protobuf':
   Traceback (most recent call last):
        File "C:/tensorflow/third_party/repo.bzl", line 110, column 25, in _tf_http_archive
                _apply_patch(ctx, ctx.attr.patch_file)
        File "C:/tensorflow/third_party/repo.bzl", line 68, column 32, in _apply_patch
                _execute_and_check_ret_code(ctx, cmd)
        File "C:/tensorflow/third_party/repo.bzl", line 52, column 13, in _execute_and_check_ret_code
                fail(("Non-zero return code({1}) when executing '{0}':\n" + "Stdout: {2}\n" +
Error in fail: Non-zero return code(2) when executing 'C:\WINDOWS\system32\bash.exe -l -c "patch" "-p1" "-d" "C:/users/{user}/_bazel_{user}/xv6zejqw/external/com_google_protobuf" "-i" "C:/tensorflow/third_party/protobuf/protobuf.patch"':
Stdout:
Stderr: patch: **** Can't change to directory C:/users/{user}/_bazel_{user}/xv6zejqw/external/com_google_protobuf : No such file or directory
ERROR: Analysis of target '//tensorflow/tools/pip_package:build_pip_package' failed; build aborted: no such package '@com_google_protobuf//': Non-zero return code(2) when executing 'C:\WINDOWS\system32\bash.exe -l -c "patch" "-p1" "-d" "C:/users/{user}/_bazel_{user}/xv6zejqw/external/com_google_protobuf" "-i" "C:/tensorflow/third_party/protobuf/protobuf.patch"':
Stdout:
Stderr: patch: **** Can't change to directory C:/users/{user}/_bazel_{user}/xv6zejqw/external/com_google_protobuf : No such file or directory
```

It is pretty strange because when I run the following command manually it works:
'C:\WINDOWS\system32\bash.exe -l -c "patch" "-p1" "-d" "C:/users/{user}/_bazel_{user}/xv6zejqw/external/com_google_protobuf" "-i" "C:/tensorflow/third_party/protobuf/protobuf.patch"'

But build still fails ...
