### ISSUE TITLE
module 'tensorflow._api.v1.keras.layers' has no attribute 'Lamdba'

### ISSUE THREAD

**Issue by Krum3L** [tensorflow/tensorflow#28861]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
`classifier_layer = layers.Lamdba(classifier_layer, input_shape = IMAGE_SIZE*[3]) 
classifier_model = tf.keras.Sequential([classifier_layer]) classifier_mode.summary()`
- OS Platform and 
Distribution (e.g., Linux Ubuntu 16.04): Windows 10 Pro, 64bit, build number 17763.503
- TensorFlow installed from (source or binary): pip install
- TensorFlow version (use command below): 1.13.1
- Python version: 3.7
- Using Visual studios as a compiler
- CUDA/cuDNN version: cant find my CUDA/cuDNN version.
- GPU model and memory: GTX 1060 6GB

**Describe the current behavior**
Giving ma a attribute error.

**Describe the expected behavior**
Not getting the attribute error

**Code to reproduce the issue**
`classifier_layer = layers.Lamdba(classifier_layer, input_shape = IMAGE_SIZE*[3]) classifier_model = tf.keras.Sequential([classifier_layer]) classifier_mode.summary()`

Provide a reproducible test case that is the bare minimum necessary to generate the problem.
just compile it.

**Other info / logs**
`classifier_layer = layers.Lamdba(classifier_layer, input_shape = IMAGE_SIZE*[3]) 
classifier_model = tf.keras.Sequential([classifier_layer]) classifier_mode.summary()`
module 'tensorflow._api.v1.keras.layers' has no attribute 'Lamdba'

**Comment by gadagashwini** [comment]
@Krum3L Code snippet you provided looks incomplete, In order to expedite the trouble-shooting process, please provide a minimal code snippet to reproduce the issue reported here. Thanks!

**Comment by Krum3L** [comment]
Hello,
I made a pastebin since i dont mind sharing the code (currently just learning and you can call it "copy pasting" the code forom the tensorflow tutorials)
Heres the code: https://pastebin.com/8QaWkqr5

**Comment by gadagashwini** [comment]
@Krum3L Thanks for the code snippet. I am able to reproduce the issue reported here.

**Comment by jvishnuvardhan** [comment]
@Krum3L I checked your code and found lot of typos that is why the code is not running properly. I found your are trying to learn this [tutorial](https://www.tensorflow.org/tutorials/images/hub_with_keras). I ran the code in the Google colab and it worked without any issue. 

When you run if you see any issue, please post it in [TF_Hub_repo]( https://github.com/tensorflow/hub/issues) so that your issue will get more visibility and faster resolution. Thanks!

**Comment by Krum3L** [comment]
Hello,
Well, its good to hear that its only typo's and notthing with the code itself... i wrote alot of that day and probably had alot of typos because of that...
Sorry for the trouble i have caused.
