### ISSUE TITLE
Analysis of target '//tensorflow/contrib/tensor_forest:model_ops_test' failed; build aborted: for tensorflow/contrib/tensor_forest/libutils.so

### ISSUE THREAD

**Issue by luorixiangyang** [tensorflow/tensorflow#28898]
env:
OS: windows 10
bazel version: 0.24.1
tensorflow version:r1.14
python:3.6.4
CUDA:9.0
cuDNN: 7.4

----------------------------------

send under command in gitBash could complete successfully
```
$ bazel build --config=opt --config=cuda --define=no_tensorflow_py_deps=true //tensorflow/tools/pip_package:build_pip_package
```

----------------------------------

but send bazel test command encounter error, details as following.:
command(in gitBash):

```
$ bazel test tensorflow/contrib/tensor_forest:model_ops_test

Starting local Bazel server and connecting to it...
WARNING: The following configs were expanded more than once: [cuda]. For repeatable flags, repeats are counted twice and may lead to unexpected behavior.
Loading:
Loading: 0 packages loaded
Analyzing: target //tensorflow/contrib/tensor_forest:model_ops_test (1 packages loaded, 0 targets configured)
Analyzing: target //tensorflow/contrib/tensor_forest:model_ops_test (33 packages loaded, 352 targets configured)
Analyzing: target //tensorflow/contrib/tensor_forest:model_ops_test (58 packages loaded, 2552 targets configured)
Analyzing: target //tensorflow/contrib/tensor_forest:model_ops_test (82 packages loaded, 4125 targets configured)
Analyzing: target //tensorflow/contrib/tensor_forest:model_ops_test (83 packages loaded, 4154 targets configured)
ERROR: file 'tensorflow/contrib/tensor_forest/libutils.so' is generated by these conflicting actions:
Label: //tensorflow/contrib/tensor_forest:model_ops_test
RuleClass: cc_test rule
Configuration: c9dc3b2a2ac77c2e5a3c9175e9c4aa9e
Mnemonic: Symlink
Action key: 0ac20b0e60679a64dc9111fddc500670
Progress message: Copying Execution Dynamic Library
PrimaryInput: File:[[<execution_root>]bazel-out/x64_windows-opt/bin]tensorflow/core/grappler/clusters/libutils.so, File:[[<execution_root>]bazel-out/x64_windows-opt/bin]tensorflow/core/grappler/costs/libutils.so
PrimaryOutput: File:[[<execution_root>]bazel-out/x64_windows-opt/bin]tensorflow/contrib/tensor_forest/libutils.so
ERROR: Analysis of target '//tensorflow/contrib/tensor_forest:model_ops_test' failed; build aborted: for tensorflow/contrib/tensor_forest/libutils.so, previous action: action 'Copying Execution Dynamic Library', attempted action: action 'Copying Execution Dynamic Library'
INFO: Elapsed time: 10.421s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (84 packages loaded, 4219 targets configured)
ERROR: Couldn't start the build. Unable to run tests
FAILED: Build did NOT complete successfully (84 packages loaded, 4219 targets configured)
```

**Comment by luorixiangyang** [comment]
To add on:
I execute py_test suits by "bazel test" is successful, but execute tf_cc_test suits will occur above exceptions.
So i think maybe problems about c compiler. Hope you can help me to fix it. thanks.

**Comment by luorixiangyang** [comment]
I also find there are files suffix is not .so and instead of .a file :libutils.a, libutils.a-2.params  in the target folder in windows10,  but have correct so files in Ubuntu18 env. so how to change it. Do y think upgrade cuda support version could solve this issue.

**Comment by achandraa** [comment]
Did you try following the steps from [TensorFlow website](https://www.tensorflow.org/install/source_windows). Also check [GPU support](https://www.tensorflow.org/install/gpu#hardware_requirements) for CUDA compatibility with TensorFlow version.

**Comment by luorixiangyang** [comment]
> Did you try following the steps from [TensorFlow website](https://www.tensorflow.org/install/source_windows). Also check [GPU support](https://www.tensorflow.org/install/gpu#hardware_requirements) for CUDA compatibility with TensorFlow version.

yes, i did it following the TensorFlow website and also chech the GPU support for CUDA compatibility with tensorflow version. 

env:
OS: windows 10
bazel version: 0.24.1
tensorflow version:r1.14
python:3.6.4
CUDA:9.0
cuDNN: 7.4

**Comment by luorixiangyang** [comment]
> Did you try following the steps from [TensorFlow website](https://www.tensorflow.org/install/source_windows). Also check [GPU support](https://www.tensorflow.org/install/gpu#hardware_requirements) for CUDA compatibility with TensorFlow version.

Thank you for your reply.
I did the steps follow official guide, following is my develop environment：

OS: windows 10
bazel version: 0.24.1
tensorflow version:r1.14
python:3.6.4
CUDA:9.0
cuDNN: 7.4.1

**Comment by achandraa** [comment]
Can you try with higher version of CUDA and let us know if that helps. For your reference TensorFlow supports CUDA 10.0 (TensorFlow >= 1.13.0). Have a look on [GPU support](https://www.tensorflow.org/install/gpu#software_requirements) link, Thanks!

**Comment by luorixiangyang** [comment]
> Can you try with higher version of CUDA and let us know if that helps. For your reference TensorFlow supports CUDA 10.0 (TensorFlow >= 1.13.0). Have a look on [GPU support](https://www.tensorflow.org/install/gpu#software_requirements) link, Thanks!

Hi achandraa,
I update the CUDA 10.0 and driver to 419.17 , cudnn 7.5, Tensorflow 2.0,  but use under command still encounter the error, i don't know why is libutils.a generated instead of libutils.so file in windows environment(In GitBash):
$ bazel test tensorflow/contrib/tensor_forest:model_ops_test
WARNING: The following configs were expanded more than once: [cuda]. For repeatable flags, repeats are counted twice and may lead to unexpected behavior.
Loading:
Loading: 0 packages loaded
DEBUG: C:/users/l00446796/_bazel_l00446796/vmio52nn/external/build_bazel_rules_apple/apple/repositories.bzl:35:5:
WARNING: `build_bazel_rules_apple` depends on `bazel_skylib` loaded from https://github.com/bazelbuild/bazel-skylib.git (tag 0.6.0), but we have detected it already loaded into your workspace from None (tag None). You may run into compatibility issues. To silence this warning, pass `ignore_version_differences = True` to `apple_rules_dependencies()`.

Analyzing: target //tensorflow/contrib/tensor_forest:model_ops_test (0 packages loaded, 0 targets configured)
ERROR: file 'tensorflow/contrib/tensor_forest/libutils.so' is generated by these conflicting actions:
Label: //tensorflow/contrib/tensor_forest:model_ops_test
RuleClass: cc_test rule
Configuration: 6f9afee38480077f2e1d7771555e31bc
Mnemonic: Symlink
Action key: 87cfd65dad66dcad42fb5f761552ee9c
Progress message: Copying Execution Dynamic Library
PrimaryInput: File:[[<execution_root>]bazel-out/x64_windows-opt/bin]tensorflow/core/grappler/clusters/libutils.so, File:[[<execution_root>]bazel-out/x64_windows-opt/bin]tensorflow/core/grappler/costs/libutils.so
PrimaryOutput: File:[[<execution_root>]bazel-out/x64_windows-opt/bin]tensorflow/contrib/tensor_forest/libutils.so
ERROR: Analysis of target '//tensorflow/contrib/tensor_forest:model_ops_test' failed; build aborted: for tensorflow/contrib/tensor_forest/libutils.so, previous action: action 'Copying Execution Dynamic Library', attempted action: action 'Copying Execution Dynamic Library'
INFO: Elapsed time: 0.398s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded, 0 targets configured)
ERROR: Couldn't start the build. Unable to run tests
FAILED: Build did NOT complete successfully (0 packages loaded, 0 targets configured)

**Comment by luorixiangyang** [comment]
export BAZEL_SH="$(cygpath -m $(realpath $(which bash)))"
export JAVA_HOME="/c/Program Files/Java/jdk1.8.0_73"
export JRE_HOME=$JAVA_HOME/jre
export CLASSPATH=.:$JAVA_HOME/lib/dt.jar:$JAVA_HOME/lib/tools.jar:$JRE_HOME/lib
export PATH=$JAVA_HOME/bin:$PATH
export PATH="/c/Python/Anaconda3:$PATH"

export PATH="/c/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.0/bin:$PATH"
export PATH="/c/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.0/libnvvp:$PATH"
export PATH="/c/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.0/extras/CUPTI/libx64:$PATH"
set BAZEL_VS="/C/Program Files (x86)/Microsoft Visual Studio 14.0"
set BAZEL_VC="/C/Program Files (x86)/Microsoft Visual Studio 14.0/VC"

**Comment by luorixiangyang** [comment]
I found if use cc_test instead of tf_cc_test for model_ops_test, then command:
bazel test tensorflow/contrib/tensor_forest:model_ops_test to be success.
so maybe some wrong about tf_cc_test. kindly to check this information.

**cc_test**(
    name = "model_ops_test",
    size = "small",
    srcs = [
        "kernels/model_ops_test.cc",
        "ops/model_ops.cc",
    ],
    deps = [
        ":forest_proto_impl",
        ":model_ops_lib",
        "//tensorflow/contrib/tensor_forest/kernels/v4:decision-tree-resource_impl",
        "//tensorflow/core:framework_headers_lib",
        "//tensorflow/core:test",
        "//tensorflow/core:test_main",
        "//tensorflow/core:testlib",
    ],
)

**Comment by ymodak** [comment]
You have successfully installed TF however you are running into issues when implementing [TensorForest](https://github.com/tensorflow/tensorflow/tree/r1.14/tensorflow/contrib/tensor_forest). Is that correct?
I suspect that the specified test target is incorrect.

**Comment by ymodak** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
