### ISSUE TITLE
Website Issue; Some lines in tutorials should pass session data

### ISSUE THREAD

**Issue by r0fls** [tensorflow/tensorflow#289]
I get this error when following the [tutorial](http://tensorflow.org/tutorials/mnist/pros/index.html#deep-mnist-for-experts), using the `eval` function:

    in _eval_using_default_session
    raise ValueError("Cannot evaluate tensor using eval(): No default "
    ValueError: Cannot evaluate tensor using eval(): No default session is registered. Use 'with DefaultSession(sess)' or pass an explicit session to eval(session=sess)`

It also happens with `run`, for instance in the line ` train_step.run(feed_dict={x: batch[0], y_: batch[1], keep_prob: 0.5})`.

**Comment by mrry** [comment]
Have you followed all of the steps in the tutorial in order? Near the beginning it has instructions to [start a `tf.InteractiveSession`](http://tensorflow.org/tutorials/mnist/pros/index.html#start-tensorflow-interactivesession). If you do so, that error should never be raised.

**Comment by r0fls** [comment]
I did, but I also went through the basic and then the advanced tutorial. Maybe those lines needed to be reran when starting the second tutorial? Seems like something I would have neglected to do...
