### ISSUE TITLE
No module named 'tensorflow_hub'

### ISSUE THREAD

**Issue by pinnareet** [tensorflow/tensorflow#28915]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 16.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): source
- TensorFlow version: 1.13.1
- Python version: 3.6.4
- Installed using virtualenv? pip? conda?: pip3
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

It's on a Google Cloud Platform machine. 

**Describe the problem**
In jupyter-notebook python3 
Got the following error
ModuleNotFoundError: No module named 'tensorflow_hub'

When executed import tensorflow_hub as hub

**Provide the exact sequence of commands / steps that you executed before running into the problem**
Many commands that I can't remember, but basically I installed tensorflow_hub using pip3 install tensorflow-hub

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by abhinavsagar** [comment]
It works for me
`Collecting tensorflow-hub
  Downloading https://files.pythonhosted.org/packages/10/5c/6f3698513cf1cd730a5ea66aec665d213adf9de59b34f362f270e0bd126f/tensorflow_hub-0.4.0-py2.py3-none-any.whl (75kB)
    100% |████████████████████████████████| 81kB 162kB/s
Requirement already satisfied: six>=1.10.0 in c:\users\win 10\appdata\local\programs\python\python36\lib\site-packages (from tensorflow-hub) (1.10.0)
Requirement already satisfied: protobuf>=3.4.0 in c:\users\win 10\appdata\local\programs\python\python36\lib\site-packages (from tensorflow-hub) (3.6.1)
Requirement already satisfied: numpy>=1.12.0 in c:\users\win 10\appdata\local\programs\python\python36\lib\site-packages (from tensorflow-hub) (1.16.3)
Requirement already satisfied: setuptools in c:\users\win 10\appdata\local\programs\python\python36\lib\site-packages (from protobuf>=3.4.0->tensorflow-hub) (39.0.1)
Installing collected packages: tensorflow-hub
Successfully installed tensorflow-hub-0.4.0`
Have you installed numpy ? What about protobuf ?

**Comment by gadagashwini** [comment]
@pinnareet Can you please follow [these](https://www.tensorflow.org/hub/installation) to install tensorflow-hub. Thanks!

**Comment by gadagashwini** [comment]
Closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Comment by pinnareet** [comment]
I'm really sorry for the late reply. numpy and protobuf are installed. I also attached screenshots showing tensorflow-hub installed but failed to load in python3. 
<img width="567" alt="Screenshot 2019-05-28 15 56 55" src="https://user-images.githubusercontent.com/4829500/58517821-96017700-8161-11e9-9cde-3f09bec887f2.png">
<img width="1420" alt="Screenshot 2019-05-28 15 57 07" src="https://user-images.githubusercontent.com/4829500/58517823-96017700-8161-11e9-90cd-27db6abd228c.png">
<img width="1241" alt="Screenshot 2019-05-28 15 58 41" src="https://user-images.githubusercontent.com/4829500/58517824-96017700-8161-11e9-8171-0286e3d505f1.png">

**Comment by gadagashwini** [comment]
@pinnareet This question better asked on [Tensorflow hub](https://github.com/tensorflow/hub/issues) repo. Thanks!

**Comment by AyazSaiyed** [comment]
> pip install https://files.pythonhosted.org/packages/10/5c/6f3698513cf1cd730a5ea66aec665d213adf9de59b34f362f270e0bd126f/tensorflow_hub-0.4.0-py2.py3-none-any.whl


It worked for me . Please try these
