### ISSUE TITLE
[TF2.0] steps_per_epoch parameter not working when input data passed as dictionary

### ISSUE THREAD

**Issue by tcbegley** [tensorflow/tensorflow#28928]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): binary (pip)
- TensorFlow version (use command below): v1.12.0-9492-g2c319fb415 2.0.0-alpha0
- Python version: 3.6.8
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 
- GPU model and memory:

**Describe the current behavior**
If using a dictionary to pass input to a `keras.Model` with named inputs, the `steps_per_epoch` argument appears to have no effect. Instead as many steps are performed as needed for a full epoch.

**Describe the expected behavior**
I would expect only as many iterations as specified by `steps_per_epoch` in each iteration. While it's possible I have misunderstood something, this is the behaviour in TensorFlow 1 when I run analogous code.

**Code to reproduce the issue**
```python
import numpy as np
import tensorflow as tf

x = np.random.random((1000, 2))
y = 2 * x[:, 0] + 3 * x[:, 1] + np.random.normal(size=(1000,))

input_ = tf.keras.Input((2,), name="input")
output = tf.keras.layers.Dense(1)(input_)
model = tf.keras.Model(inputs=[input_], outputs=[output])

model.compile(tf.optimizers.Adam(), loss=tf.losses.mse)
```

with this setup, I observe

```python
model.fit(
    x, y, steps_per_epoch=2, batch_size=10,
)
```
```
2/2 [==============================] - 0s 38ms/step - loss: 1.5998
```

but on the other hand, if I pass the input as a dictionary I observe

```python
model.fit(
    {"input": x}, y, steps_per_epoch=2, batch_size=10,
)
```
```
1000/1000 [==============================] - 5s 5ms/sample - loss: 1.5324
```

Strangely, if I then run the first `.fit` command again, it also performs a full pass over the data, rather than doing the specified number of steps as originally.

In TensorFlow 1, with the same code as above, but a TensorFlow 1 friendly model compilation step

```python
model.compile(
    tf.train.AdamOptimizer(),
    loss=tf.losses.mean_squared_error,
)
```

I do not see the same issue, the number of steps is as specified, whether data is passed in a dictionary or not.

**Other info / logs**
This could be related to #28710? Though the author there was using TensorFlow 1 and reported that data input as NumPy arrays did not cause problems, so this seemed different enough for its own issue. Happy for them to be consolidated if they are too similar.

**Comment by gadagashwini** [comment]
@tcbegley I tried reproducing the issue through colab with Tf 2.0.0-alpha0 but the code executed as expected. Can you try once again and let us know if that still gives weird output. Thanks!

**Comment by tcbegley** [comment]
@gadagashwini thanks for getting back to me.

I was able to replicate my issue in Google Colab, see [this notebook](https://colab.research.google.com/drive/1pjpBakrkgd0pQKhGhnQW2_PNUUXKI28G).

As in the screenshot below, which is taken from that notebook, the first fit argument performs two steps of training, the second cell appears to do a full pass over the data, ignoring the `steps_per_epoch` argument. As I stated in my original post this is different to behaviour in TensorFlow 1, and also different to my interpretation of the docs, so I think it's a bug.

![image](https://user-images.githubusercontent.com/15220906/58250963-72ea5800-7d5a-11e9-852c-abb6916d9686.png)

**Comment by gadagashwini** [comment]
I was able to reproduce the mentioned output.

**Comment by ymodak** [comment]
@tcbegley Is this issue with tf 2.0 nightly build? (pip install tf-nightly-2.0-preview)

**Comment by tcbegley** [comment]
@ymodak I tried out the nightly build, and everything worked correctly, so it seems likely this issue has also been resolved.

**Comment by ymodak** [comment]
Great. Thanks for confirming. I will close this issue now. Feel free to reopen if still have problems. Thanks!
