### ISSUE TITLE
Build tensorflow lite for aarch64: Error in script download_dependencies.sh and build_aarch64_lib.sh

### ISSUE THREAD

**Issue by vizero1** [tensorflow/tensorflow#28926]
**System information**
- OS Platform and Distribution: Google coral board aarch64
- TensorFlow lite installed from source
- TensorFlow version: master branch

If I run the script ./tensorflow/lite/tools/make/download_dependencies.sh  from the root directory of the repo I am getting following error:

**downloading http://mirror.tensorflow.org/bitbucket.org/eigen/eigen/get/a0d250e79c79.tar.gz**

**gzip: stdin: not in gzip format**
**tar: Child returned status 1**
**tar: Error is not recoverable: exiting now**

2 days ago I had not the problem to run the script download_dependencies.sh.
There was some clean up of dependencies for tensorflow lite at least if I check the commit messages of the master branch.
Could it have something to do with that?

Thanks in advance!

**Comment by vizero1** [comment]
https://github.com/tensorflow/tensorflow/commit/69aa57b4158da0f09ca732ee302ef453fa6b3209#diff-455a4c7f8e22d7c514e8c2caa27506c5

There was an update to the artifact it tries to download.  Tried to download both with wget and  the old artifact is available but the new one can't be downloaded.

**Comment by vizero1** [comment]
Could fix that problem with following change:
In tensorflow/lite/tools/make/download_dependencies.sh script I changed the EIGEN_URL definition in line 32 to use https instead of http
`EIGEN_URL="$(grep -o 'https.*bitbucket.org/eigen/eigen/get/.*tar\.gz' "${BZL_FILE_PATH}" | grep -v mirror.bazel | head -n1)"`

**Comment by XiaYuanxiang** [comment]
Hello, did you slove the problem?
I meet the same problem

**Comment by XiaYuanxiang** [comment]
Hello，I changed  the code to EIGEN_URL="$(grep -o 'https.*bitbucket.org/eigen/eigen/get/.*tar\.gz' "${BZL_FILE_PATH}" | grep -v mirror.bazel | head -n1)"   as you said，but i still meet the problem 
gzip: stdin: unexpected end of file
tar: Child returned status 1
tar: Error is not recoverable: exiting now

any suggestion will help，Thanks

**Comment by sunrise-ceo** [comment]
> error: x29 cannot be used in asm here

Experiencing the same issue while compiling TFLite natively on ARMv8-A (after trying [this](https://stackoverflow.com/questions/56055359/tensorflow-lite-arm64-error-cannot-convert-const-int8x8-t) solution as well).

**Comment by val-storm** [comment]
Same issue compiling for ARM6

**Comment by dongxiao92** [comment]
same issue for me. My platform is nvidia jetson tx2. I changed the eigen url as this [https://github.com/tensorflow/tensorflow/commit/69aa57b4158da0f09ca732ee302ef453fa6b3209#diff-455a4c7f8e22d7c514e8c2caa27506c5](url)

**Comment by RuABraun** [comment]
Same issue.

**Comment by ohnoholly** [comment]
Same issue on Raspberry Pi3 B+

**Comment by aketkhan** [comment]
Same issue on Raspberry Pi 3B

**Comment by Finniu** [comment]
download_dependencies.sh completed successfully.

**Comment by vizero1** [comment]
> download_dependencies.sh completed successfully.

But can you build it afterwards for arm?

**Comment by Finniu** [comment]
no, there is an error which is X 29 or something like that can not be used 


| |
牛帅
邮箱：n719171101@163.com
|

签名由 网易邮箱大师 定制

On 06/05/2019 19:33, vizero1 wrote:

download_dependencies.sh completed successfully.

But can you build it afterwards for arm?

**Comment by dongxiao92** [comment]
any updates on this issue?

**Comment by aakbar5** [comment]
Hi, I am having the same error, I found that cURL command is having

`<?xml version='1.0' encoding='UTF-8'?><Error><Code>NoSuchKey</Code><Message>The specified key does not exist.</Message><Details>No such object: mirror.tensorflow.org/bitbucket.org/eigen/eigen/get/a0d250e79c79.tar.gz</Details></Error>` because http://mirror.tensorflow.org/ is not having `a0d250e79c79.tar.gz`. 

Just for information that tensorflow repo was set to commit f5ce1c00d4397875ff3d706881bd46430f4a9667 (HEAD -> master, tag: v1.14.0-rc0)

**Comment by aakbar5** [comment]
Oh..there is a PR https://github.com/tensorflow/tensorflow/pull/29017 to fix this issue. https://github.com/tensorflow/tensorflow/issues/29030 is also the same as this one.

**Comment by Finniu** [comment]
@aakbar5 The method they proposed above, which is changing the download address and key, just follow it!

**Comment by vizero1** [comment]
@aakbar5 the more significant problem is building tensorflow lite for aarch64. If you run the script you get the following error "error: x29 cannot be used in asm here"
We are waiting for a fix for that problem.

**Comment by dongxiao92** [comment]
@vizero1 Here is a possible solution and I tried it on my jetson tx2 board. It worked. In the arm architecture, it seems the x29 register is used as the frame pointer register by default. By adding the '-fomit-frame-pointer' to the CXXFLAGS in the Makefile, we can tell the compiler the x29 register can be used without worrying about impacting the frame pointer.

**Comment by jetblack1** [comment]
Don't know if this is related.. trying to build `v1.13.1` on `ubuntu` `raspberry pi 2` with
```
CI_DOCKER_EXTRA_PARAMS="-e CI_BUILD_PYTHON=python3 -e CROSSTOOL_PYTHON_INCLUDE_PATH=/usr/include/python3.6" tensorflow/tools/ci_build/ci_build.sh PI-PYTHON3 tensorflow/tools/ci_build/pi/build_raspberry_pi.sh
```

but getting this error
```
...
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Reading package lists...
Building dependency tree...
Reading state information...
Package ffmpeg is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Unable to locate package clang-format-3.8
E: Couldn't find any package by regex 'clang-format-3.8'
E: Package 'ffmpeg' has no installation candidate
The command '/bin/sh -c /install/install_deb_packages.sh' returned a non-zero code: 100
ERROR: docker build failed. Dockerfile is at /home/ubuntu/apps/tensorflow/tensorflow/tools/ci_build/Dockerfile.pi-python3
```

**Comment by vizero1** [comment]
> @vizero1 Here is a possible solution and I tried it on my jetson tx2 board. It worked. In the arm architecture, it seems the x29 register is used as the frame pointer register by default. By adding the '-fomit-frame-pointer' to the CXXFLAGS in the Makefile, we can tell the compiler the x29 register can be used without worrying about impacting the frame pointer.

Yes that resolves the "x29 register" error but now I am getting the following error: 

```

> /usr/src/app/tensorflow/lite/tools/make/gen/aarch64_armv8-a/lib/libtensorflow-lite.a(while.o): In function `tflite::ops::custom::while_kernel::Init(TfLiteContext*, char const*, unsigned long)':
> while.cc:(.text+0x1d88): undefined reference to `flatbuffers::ClassicLocale::instance_'
> while.cc:(.text+0x1d94): undefined reference to `flatbuffers::ClassicLocale::instance_'
> while.cc:(.text+0x1df8): undefined reference to `flatbuffers::ClassicLocale::instance_'
> while.cc:(.text+0x1e08): undefined reference to `flatbuffers::ClassicLocale::instance_'
> /usr/src/app/tensorflow/lite/tools/make/gen/aarch64_armv8-a/lib/libtensorflow-lite.a(audio_spectrogram.o): In function `tflite::ops::custom::audio_spectrogram::Init(TfLiteContext*, char const*, unsigned long)':
> audio_spectrogram.cc:(.text+0x1070): undefined reference to `flatbuffers::ClassicLocale::instance_'
> /usr/src/app/tensorflow/lite/tools/make/gen/aarch64_armv8-a/lib/libtensorflow-lite.a(audio_spectrogram.o):audio_spectrogram.cc:(.text+0x107c): more undefined references to `flatbuffers::ClassicLocale::instance_' follow
> collect2: error: ld returned 1 exit status

```
Someone has a solution for that? Found following issues  #26731 and #28863 related to that.

**Comment by thotaram** [comment]
Hi @dongxiao92 
Did you solve the flatbuffers issue.
I am also getting similar error, Please let me know once you resolve the issue.
Thanks inadvance.

**Comment by aakbar5** [comment]
@dongxiao92, @thotaram, To solve the flatbuffer, I did the following
`git clone https://github.com/google/flatbuffers.git`
`cd flatbuffers`
`cmake -G "Unix Makefiles"`
`make`
`make install`
 
Once flatbuffers is installed, Append `-lflatbuffers` to the `LIBS` in `tensorflow/lite/tools/make/Makefile`.

**Comment by thotaram** [comment]
@aakbar5 
Hi, I have followed your inputs still am getting the similar issue.

while.cc:(.text+0x1d04): undefined reference to `flatbuffers::ClassicLocale::instance_'
while.cc:(.text+0x1d18): undefined reference to `flatbuffers::ClassicLocale::instance_'
while.cc:(.text+0x1d6c): undefined reference to `flatbuffers::ClassicLocale::instance_'
while.cc:(.text+0x1d78): undefined reference to `flatbuffers::ClassicLocale::instance_'

Have you resolved Flatbuffers issue using above commands.
Please help me still am missing anything.

**Comment by aakbar5** [comment]
@thotaram,
Could you confirm your `LDOPTS` variable? Mine looks like `LDOPTS := -L/usr/local/lib -L/usr/lib`.

**Comment by thotaram** [comment]
@aakbar5 
Hi,
Thank your for your quick reply.
For me it is like
LDOPTS := -L/usr/lib
I changed LDOPTS as per your suggestions.
LDOPTS := -L/usr/local/lib -L/usr/lib

Still am getting the error.
My Makefile changes are 
TARGET := aarch64
TARGET_ARCH := armv8-a
CXXFLAGS := -O3 -DNDEBUG -fPIC -flax-vector-conversions -fomit-frame-pointer
LIBS := \
-lstdc++ \
-lflatbuffers \

Can you please share your Makefile to resolve this problem.

**Comment by thotaram** [comment]
@aakbar5 
In Makefile i could not find LDOPTS where it is using.
Only LDOPTS option is there but it is not using in Makefile.
Can you please share where LDOPTS is used in Makefile.

**Comment by aakbar5** [comment]
> @aakbar5
> In Makefile i could not find LDOPTS where it is using.
> Only LDOPTS option is there but it is not using in Makefile.
> Can you please share where LDOPTS is used in Makefile.
If I recall correctly, I was using HEAD revision of the Tensorflow master branch. Moreover I hope you are doing native compilation not cross compilation.

**Comment by thotaram** [comment]
I am using tensorflow version 1.13.1
While compiling the sources i can see the below command(aarch64-linux-gnu-g++)

aarch64-linux-gnu-g++ O3 -DNDEBUG -fPIC -flax-vector-conversions -fomit-frame-pointer  -std=c++11 -march=armv8-a -funsafe-math-optimizations -ftree-vectorize -fPIC 
Below link i have followed to cross compile tensorflow lite.
https://www.tensorflow.org/lite/guide/build_arm64

Please give your inputs whether am doing right procedure or not?

**Comment by vizero1** [comment]
@aakbar5 Compiled flatbuffers and added it to the libs in Makefile.
Changed LDOPTS to -L/usr/local/lib -L/usr/lib .
```
aarch64-linux-gnu-g++ -O3 -DNDEBUG -fPIC -flax-vector-conversions  --std=c++11 -march=armv8-a -funsafe-math-optimizations -ftree-vectorize -flax-vector-conversions -fomit-frame-pointer -fPIC -I. -I/usr/src/app/tensorflow/tensorflow/lite/tools/make/../../../../../ -I/usr/src/app/tensorflow/tensorflow/lite/tools/make/../../../../../../ -I/usr/src/app/tensorflow/tensorflow/lite/tools/make/downloads/ -I/usr/src/app/tensorflow/tensorflow/lite/tools/make/downloads/eigen -I/usr/src/app/tensorflow/tensorflow/lite/tools/make/downloads/absl -I/usr/src/app/tensorflow/tensorflow/lite/tools/make/downloads/gemmlowp -I/usr/src/app/tensorflow/tensorflow/lite/tools/make/downloads/neon_2_sse -I/usr/src/app/tensorflow/tensorflow/lite/tools/make/downloads/farmhash/src -I/usr/src/app/tensorflow/tensorflow/lite/tools/make/downloads/flatbuffers/include -I -I/usr/local/include \
-o /usr/src/app/tensorflow/tensorflow/lite/tools/make/gen/aarch64_armv8-a/bin/minimal /usr/src/app/tensorflow/tensorflow/lite/tools/make/gen/aarch64_armv8-a/obj/tensorflow/lite/examples/minimal/minimal.o \
 /usr/src/app/tensorflow/tensorflow/lite/tools/make/gen/aarch64_armv8-a/lib/libtensorflow-lite.a -Wl,--no-export-dynamic -Wl,--exclude-libs,ALL -Wl,--gc-sections -Wl,--as-needed -lrt -lstdc++ -lpthread -lm -ldl -lrt
```
That is the command it uses for compilation. Still have the flatbuffers error :/

**Comment by thotaram** [comment]
I could not understand the below your point.
Still have the flatbuffers error :/
You are also facing the faltbuffers issue, or issue is resolved by changing Makefile.
Can you please send the tensorflow master branch link.

**Comment by thotaram** [comment]
@aakbar5 
/tensorflow/tensorflow/lite/tools/make/gen/aarch64_armv8-a/lib/libtensorflow-lite.a -Wl,--no-export-dynamic -Wl,--exclude-libs,ALL -Wl,--gc-sections -Wl,--as-needed -lrt -lstdc++ -lpthread -lm -ldl 

In the above statement i could not see the "-lflatbuffers" library. Although it is there in LIBS in Makefile.

**Comment by vizero1** [comment]
@thotaram 
Now it is running for me. Changed in the aarch64_makefile.inc the LIBS part and added -lflatbuffers.

```
  LIBS := \
    -lflatbuffers \
    -lstdc++ \
    -lpthread \
    -lm \
    -ldl \
    -lrt
```

**Comment by mrudulaathi** [comment]
@aakbar5 For some reason the linker is not able to use the flatbuffer library. It gives the following error:

 /usr/lib/gcc-cross/aarch64-linux-gnu/7/../../../../aarch64-linux-gnu/bin/ld: skipping incompatible //usr/local/lib/libflatbuffers.a when searching for -lflatbuffers
/usr/lib/gcc-cross/aarch64-linux-gnu/7/../../../../aarch64-linux-gnu/bin/ld: cannot find -lflatbuffers

Would it make a difference if you were trying to cross compile instead of natively compiling the tflite for ARM?

**Comment by thotaram** [comment]
@vizero1 
Included -lfaltbuffers in aarch64_makefile.inc file LIBS part.
Still am getting the below error.
tensorflow/tensorflow/lite/tools/make/gen/aarch64_armv8-a/lib/libtensorflow-lite.a -Wl,--no-export-dynamic -Wl,--exclude-libs,ALL -Wl,--gc-sections -Wl,--as-needed -lrt -lflatbuffers -lstdc++ -lpthread -lm -ldl -lrt
/usr/lib/gcc-cross/aarch64-linux-gnu/5/../../../../aarch64-linux-gnu/bin/ld: skipping incompatible //usr/local/lib/libflatbuffers.a when searching for -lflatbuffers
/usr/lib/gcc-cross/aarch64-linux-gnu/5/../../../../aarch64-linux-gnu/bin/ld: cannot find -lflatbuffers
collect2: error: ld returned 1 exit status

**Comment by aakbar5** [comment]
> @aakbar5
> /tensorflow/tensorflow/lite/tools/make/gen/aarch64_armv8-a/lib/libtensorflow-lite.a -Wl,--no-export-dynamic -Wl,--exclude-libs,ALL -Wl,--gc-sections -Wl,--as-needed -lrt -lstdc++ -lpthread -lm -ldl
> 
> In the above statement i could not see the "-lflatbuffers" library. Although it is there in LIBS in Makefile.

Have you tried your luck by adding -lflatbuffers in the above command?

**Comment by aakbar5** [comment]
> @aakbar5 For some reason the linker is not able to use the flatbuffer library. It gives the following error:
> 
> /usr/lib/gcc-cross/aarch64-linux-gnu/7/../../../../aarch64-linux-gnu/bin/ld: skipping incompatible //usr/local/lib/libflatbuffers.a when searching for -lflatbuffers
> /usr/lib/gcc-cross/aarch64-linux-gnu/7/../../../../aarch64-linux-gnu/bin/ld: cannot find -lflatbuffers
> 
> Would it make a difference if you were trying to cross compile instead of natively compiling the tflite for ARM?

Yes, it's matter a lot as you need to make sure that you are not exposing libs and headers of your host machine for cross-compilation. For example there are a lot of variables in the build system which are just assuming that /usr/lib or /usr/include is having correct libs/headers which won't be case for cross-compilation.

**Comment by thotaram** [comment]
@aakbar5 
Have you tried your luck by adding -lflatbuffers in the above command?

I included -lfaltbuffers in aarch64_makefile.inc file. Now it showing as below

tensorflow/tensorflow/lite/tools/make/gen/aarch64_armv8-a/lib/benchmark-lib.a -Wl,--no-export-dynamic -Wl,--exclude-libs,ALL -Wl,--gc-sections -Wl,--as-needed -lrt -lflatbuffers -lstdc++ -lpthread -lm -ldl -lrt

Still getting the error after adding this -lfaltbuffers also. Please see the below error.

/usr/lib/gcc-cross/aarch64-linux-gnu/5/../../../../aarch64-linux-gnu/bin/ld: skipping incompatible //usr/local/lib/libflatbuffers.a when searching for -lflatbuffers
/usr/lib/gcc-cross/aarch64-linux-gnu/5/../../../../aarch64-linux-gnu/bin/ld: cannot find -lflatbuffers

**Comment by aakbar5** [comment]
> @aakbar5
> Have you tried your luck by adding -lflatbuffers in the above command?
> 
> I included -lfaltbuffers in aarch64_makefile.inc file. Now it showing as below
> 
> tensorflow/tensorflow/lite/tools/make/gen/aarch64_armv8-a/lib/benchmark-lib.a -Wl,--no-export-dynamic -Wl,--exclude-libs,ALL -Wl,--gc-sections -Wl,--as-needed -lrt -lflatbuffers -lstdc++ -lpthread -lm -ldl -lrt
> 
> Still getting the error after adding this -lfaltbuffers also. Please see the below error.
> 
> /usr/lib/gcc-cross/aarch64-linux-gnu/5/../../../../aarch64-linux-gnu/bin/ld: skipping incompatible //usr/local/lib/libflatbuffers.a when searching for -lflatbuffers
> /usr/lib/gcc-cross/aarch64-linux-gnu/5/../../../../aarch64-linux-gnu/bin/ld: cannot find -lflatbuffers

@thotaram, Are you sure that flatbuffers is in /usr/local/lib/ because that's where ld is looking for. However make sure that your flatbuffers lib is built with the correct toolchain. 

Are you sure that you are not mixing libraries of different toolchains? I am thinking about this due to `skipping incompatible` message.

**Comment by thotaram** [comment]
Below is my flatbuffer library.
-rwxr-xr-x 1 root root 4897132 Jun  6 10:34 /usr/local/lib/libflatbuffers.a
As per your inputs i compiled the flatbuffers source code.
cmake -G "Unix Makefiles"
make
make install
Please let me know still am missing anything.

**Comment by thotaram** [comment]
@aakbar5 
Hi, 
Skipping incompatible issue is not coming now. Getting the below error.

opt/gcc-linaro-7.4.1-2019.02-x86_64_aarch64-linux-gnu/bin/../lib/gcc/aarch64-linux-gnu/7.4.1/../../../../aarch64-linux-gnu/bin/ld: cannot find -lflatbuffers
collect2: error: ld returned 1 exit status
tensorflow/lite/tools/make/Makefile:269: recipe for target '/home/aiiec/ARMNN/TF_lite_latest/tensorflow/tensorflow/lite/tools/make/gen/aarch64_armv8-a/bin/minimal' failed
make: *** [/home/xxxx/ARMNN/TF_lite_latest/tensorflow/tensorflow/lite/tools/make/gen/aarch64_armv8-a/bin/minimal] Error 1
make: *** Waiting for unfinished jobs....
aarch64-linux-gnu-ar: creating /home/xxxx/ARMNN/TF_lite_latest/tensorflow/tensorflow/lite/tools/make/gen/aarch64_armv8-a/lib/benchmark-lib.a

Can you please suggest how to resolve it.

**Comment by thotaram** [comment]
@aakbar5 
Hi,
Can you please share cmake command to cross compile the Flatbuffers source code for ARM64
Thanks andvance.

**Comment by mohan-barathi** [comment]
Hi ..!
I git-cloned tensorflow, and on the latest branch i executed `download_dependencies.sh` and `build_aarch64_lib.sh` 
( after disabling the NNAPI and adding the above mentioned compiler flags )

I was able to generate the static library `libtensorflow-lite.a`, but the compilation terminated with error on compiling `<TF root>/tensorflow/lite/tools/make/gen/aarch64_armv8-a/bin/minimal`

I'm not sure whether the static library compilation is complete.
Can anyone please help me in pointing out a resource / example for using this static library for building a simple working application ..?!

**Comment by sagarsahu27** [comment]
Hi All,

I am still facing issue with eigen URL, even I use http or https
wget https://mirror.tensorflow.org/bitbucket.org/eigen/eigen/get/a0d250e79c79.tar.gz --no-check-certificate
--2019-06-27 11:47:15--  https://mirror.tensorflow.org/bitbucket.org/eigen/eigen/get/a0d250e79c79.tar.gz
Resolving mirror.tensorflow.org (mirror.tensorflow.org)... 172.217.163.176, 2404:6800:4007:80f::2010
Connecting to mirror.tensorflow.org (mirror.tensorflow.org)|172.217.163.176|:443... connected.
WARNING: no certificate subject alternative name matches
        requested host name ‘mirror.tensorflow.org’.
HTTP request sent, awaiting response... 404 Not Found
2019-06-27 11:47:16 ERROR 404: Not Found.

I changed to http://www.bitbucket.org/eigen/eigen/get/a0d250e79c79.tar.gz and it is compiling for me but can we get some fix, **I don't want to change URL for each and every release** ?

Please note, I am not facing compilation issue because I wrote my own CMake for tflite just for compiling libtensorflow-lite.a taking reference from Makefile, I didn't need to compile flatbuffer library but has to add one util.cpp from it. I am not compiling Benchmark app so can't say this will work for you. If I will compile benchmark will let you know.

**Comment by thotaram** [comment]
Hi All,
Tensorflow lite build is successful, able to run examples.

label_image.cc example ran successfully with opencv 3.2.0 version but getting errors with opencv 3.4 and opencv 4.1.0 versions.

below code is changed in the Makefile
$(LABEL_IMAGE_BINARY): $(LABEL_IMAGE_OBJS) $(LIB_PATH)
	@mkdir -p $(dir $@)
	$(CXX) $(CXXFLAGS) $(INCLUDES) \
	-o $(LABEL_IMAGE_BINARY) $(LABEL_IMAGE_OBJS) \
	$(LIBFLAGS) $(LIB_PATH) $(LDFLAGS) $(LIBS) -L/home/xxx/opencvAarch64/opencv/build/install/lib -lopencv_core -lopencv_imgcodecs -lopencv_imgproc -lopencv_highgui

With opencv 3.2 is working fine, getting errors when includes 3.4 or 4.1 libraries.
ERROR:
 /home/xxx/TFlite/TensorFlow_Lite/tensorflow/tensorflow/lite/tools/make/gen/aarch64_armv8-a/lib/libtensorflow-lite.a -Wl,--no-export-dynamic -Wl,--exclude-libs,ALL -Wl,--gc-sections -Wl,--as-needed -lstdc++ -lpthread -lm -ldl -lrt /home/xxx/TFlite/TensorFlow_Lite/tensorflow/tensorflow/lite/tools/make/gen/aarch64_armv8-a/lib/benchmark-lib.a -L/home/xxx/opencvAarch64/opencv_4.1.0/opencv-4.1.0/build/install/lib -lopencv_core -lopencv_imgcodecs -lopencv_imgproc -lopencv_highgui -lopencv_features2d -lopencv_calib3d -lopencv_flann
/home/xxx/TFlite/TensorFlow_Lite/tensorflow/tensorflow/lite/tools/make/gen/aarch64_armv8-a/obj/tensorflow/lite/examples/custom_sv_psd_image/psd/src_psd/psdl_label.o: In function `tflite::label_image::RunInference(tflite::label_image::Settings*)':
label.cc:(.text+0x2214): **undefined reference to `cv::imread(cv::String const&, int)'**
label.cc:(.text+0x22c4): undefined reference to `cv::String::deallocate()'
label.cc:(.text+0x2f88): undefined reference to `cv::String::allocate(unsigned long)'
label.cc:(.text+0x3678): undefined reference to `cv::String::deallocate()'


Please suggest how to resolve this problem.

Thanks,
Ram.

**Comment by terryheo** [comment]
I've tested download_dependencies.sh and build_aarch64_lib.sh today.
It works well so let me close this issue.
