### ISSUE TITLE
Request for ScatterNd on Tensorflow Lite

### ISSUE THREAD

**Issue by gitathrun** [tensorflow/tensorflow#28934]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
Ubuntu 16.04
- TensorFlow installed from (source or binary):
Binary
- TensorFlow version (or github SHA if from source):
1.13.1 and 2.0-preview

**Provide the text output from tflite_convert**

```
Some of the operators in the model are not supported by the standard TensorFlow Lite runtime and are not recognized by TensorFlow. If you have a custom implementation for them you can disable this error with --allow_custom_ops, or by setting allow_custom_ops=True when calling tf.lite.TFLiteConverter(). Here is a list of builtin operators you are using: ........

. Here is a list of operators for which you will need custom implementations: ScatterNd.
```

Also, please include a link to a GraphDef or the model if possible.

**Any other info / logs**

Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by srjoglekar246** [comment]
New op requests are tracked at [#21526](https://github.com/tensorflow/tensorflow/issues/21526). Could you put a comment there and close this issue? Thanks!
