### ISSUE TITLE
Optimize transpose ops

### ISSUE THREAD

**Issue by amilsted** [tensorflow/tensorflow#28933]
**System information**
- TensorFlow version (you are using): 1.13.1
- Are you willing to contribute it (Yes/No): No (I lack the expertise to mess with the graph optimizer).

**Describe the feature and the current behavior/state.**
TF is not very smart about transpositions. For example, the graph optimizer could do the following:
1. Merge adjacent transpositions (each transpose op costs time and creates a new tensor).
2. Pull transpositions through reshapes where possible (transposing with fewer dimensions should be faster, and is currently often *much* see #32).
3. Merge transpose ops with adjacent matmul ops where possible (turn a matrix transpose into a transpose argument for the matmul op).

Currently, none of these appear to happen.
I can provide some test cases that illustrate these improvements if desired.

**Will this change the current api? How?**
No API changes.

**Who will benefit with this feature?**
People who build graphs with lots of transpose operations.

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.

**Comment by tilakrayal** [comment]
@amilsted ,
Can you please take a look at this [comment](https://github.com/google/TensorNetwork/issues/70#issuecomment-495032135) for the same issue which states `the XLA compiler will eliminate redundant transposes and fold the remaining ones into the multiplies`.Thanks!
