### ISSUE TITLE
Is there any difference in mAP from fronzen graph to .tflite model?

### ISSUE THREAD

**Issue by joaolcaas** [tensorflow/tensorflow#28938]
I'm running android example following this [artichle](https://medium.com/tensorflow/training-and-serving-a-realtime-mobile-object-detector-in-30-minutes-with-cloud-tpus-b78971cf1193) from tensorflow. On it, the author talk about the mAP while the training is running. The mAP[0.5] it's equals to 82%. Then, next in the article, the model is transformed to .tflite, but he do not talk about mAP or any difference on this value. Can any one tell me if there is any change or some documentation that can help me on that? Thanks!

**Comment by srjoglekar246** [comment]
The mAP should remain the same, since the model was trained with quantization-aware training. Typically, accuracies fall a bit with [post-training quantization](https://www.tensorflow.org/lite/performance/post_training_quantization), but not vanilla conversion to TFLite.

**Comment by joaolcaas** [comment]
Thanks for answer me, @srjoglekar246 ! Do you have any documentation that comprove it? Sorry if its sound that i don't trust you rs, i just need a better explanation

**Comment by srjoglekar246** [comment]
Its basically a function of how the [TFLite converter](https://www.tensorflow.org/lite/convert) works. For conversion that doesn't employ post-training quantization, we simply copy over the weights from the original TF graph. You could probably dig around the [converter code](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/toco) to see how it works.

**Comment by joaolcaas** [comment]
I see! Thank you again
