### ISSUE TITLE
TypeError in RNNs tutorial

### ISSUE THREAD

**Issue by chennakeshava1998** [tensorflow/tensorflow#28939]
## URL(s) with the issue:
https://www.tensorflow.org/tutorials/keras/basic_regression
### Clear description

The `model = build_model()` function results in a `TypeError` and gives the following trace:
```
TypeError                                 Traceback (most recent call last)
<ipython-input-19-671884cecb64> in <module>
----> 1 model = build_model()

<ipython-input-18-d3556ed39f80> in build_model()
      3     layers.Dense(64, activation=tf.nn.relu, input_shape=[64]),
      4     layers.Dense(64, activation=tf.nn.relu),
----> 5     layers.Dense(1)
      6   ])
      7 

~/anaconda3/lib/python3.7/site-packages/keras/engine/sequential.py in __init__(self, layers, name)
     91         if layers:
     92             for layer in layers:
---> 93                 self.add(layer)
     94 
     95     @property

~/anaconda3/lib/python3.7/site-packages/keras/engine/sequential.py in add(self, layer)
    130             raise TypeError('The added layer must be '
    131                             'an instance of class Layer. '
--> 132                             'Found: ' + str(layer))
    133         self.built = False
    134         if not self._layers:

TypeError: The added layer must be an instance of class Layer. Found: <tensorflow.python.keras.layers.core.Dense object at 0x7efe86908f28>


```

### Parameters defined

Are all parameters defined and formatted correctly? <br>
Yes. This method does not use any parameters apart from `train_dataset` which has been replaced with a constant in my above example.

### Raises listed and defined

This raises a TypeError.

**Comment by jvishnuvardhan** [comment]
@chennakeshava1998 I ran the tutorial without any issues. Here is the [gist](https://colab.sandbox.google.com/gist/jvishnuvardhan/138d0e438232934cd0c7b759ca411923/basic_regression.ipynb). Can you create a gist or share code to reproduce the issue? Thanks!

**Comment by chennakeshava1998** [comment]
Here is the gist of a reduced version of the tutorial. I am using it for a different application, so I only needed the model creation parts. Gist: https://gist.github.com/chennakeshava1998/e38e8da0a6adf0640d8b5640095f3b83

The only change I have made is in specifying the input dimension to the RNN. I have used a constant of [64] instead of the length of an array.

**Comment by jvishnuvardhan** [comment]
@chennakeshava1998 Here is the working version. `keras.Sequential` and  `tensorflow.keras.Sequential` are different where one is implemented inside other framework. When model was built entirely on tensorflow framework there is no issue. Thanks!

I am closing this issue. Thanks!

**Comment by chennakeshava1998** [comment]
okay, thanks a lot!
