### ISSUE TITLE
how to use multiple parameters server under synchronous gradient update

### ISSUE THREAD

**Issue by zzqiang04053080** [tensorflow/tensorflow#2894]
recently, I try to train the inceptionV3 mode with multi machine. As described in [https://github.com/tensorflow/models/tree/master/inception](url),  tutorial describes how to train inceptionv3 using tensorflow  distributed version, but only use a parameter server.
I want to know how to use multiple parameters server under synchronous gradient update, anyone can give guidance?

**Comment by andydavis1** [comment]
This is a question better suited for StackOverflow. Please ask it there and tag it with the `tensorflow` tag.
