### ISSUE TITLE
Link for migrating from deprecated DNNLinearCombinedRegressor is broken

### ISSUE THREAD

**Issue by teddyward** [tensorflow/tensorflow#28944]
Thank you for submitting a TensorFlow documentation issue. Per our GitHub
policy, we only address code/doc bugs, performance issues, feature requests, and
build/installation issues on GitHub.

The TensorFlow docs are open source! To get involved, read the documentation
contributor guide: https://www.tensorflow.org/community/contribute/docs

## URL(s) with the issue:

https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/learn/python/learn/estimators/dnn_linear_combined.py#L849

## Description of issue (what needs changing):

Link is broken. Why is it deprecated? What should I do about it?

**Comment by ymodak** [comment]
Perhaps this is the link you are looking for,
https://github.com/tensorflow/tensorflow/tree/master/tensorflow/contrib/learn
It covers the migration instructions.

**Comment by teddyward** [comment]
Ok, that works! The link in the docstring is still broken, so other people may encounter the same problem, but thanks.
