### ISSUE TITLE
CUDA GPU support for contrib static makefile build on Linux and possibly MacOS and Windows

### ISSUE THREAD

**Issue by samhodge** [tensorflow/tensorflow#28945]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using): v1.13.1
- Are you willing to contribute it (Yes/No): Yes

**Describe the feature and the current behavior/state.**
Using contrib make file I can build static libraries on Windows and Linux

git clone https://github.com/tensorflow/tensorflow.git
cd tensorflow
git checkout v1.13.1
./configure #give details for CPU
bazel build --opt config //tensorflow:libtensorflow_cc.so #setup up proto headers etc
./tensorflow/contrib/makefile/build_all_linux.sh
export LD_LIBRARY_PATH=$PWD/tensorflow/contrib/makefile/gen/host-protobuf/lib
./tensorflow/contrib/makefile/gen/bin/benchmark --help

(The above works pretty well under OSX also)

I can see in the Makefile there is some support for CUDA builds on the NVIDIA Tegra platform for Android.

would it be possible to make it create the .a file for CUDA linkage mentioned in the Tegra part of the build script?

**Will this change the current api? How?**
No

**Who will benefit with this feature?**
People integrating Tensorflow who need static linkage AND GPU acceleration using C++ API.

If you are using Tensorflow as a plugin then the function init can only be called once

see
https://stackoverflow.com/questions/43665674/what-is-the-purpose-of-tensorflowportinitmain
https://github.com/tensorflow/tensorflow/issues/22810
https://stackoverflow.com/questions/52683649/libtensorflow-cc-so-initialised-a-second-time-causes-segfault

Allowing static linking overcomes this problem

**Any Other info.**
Also see:
https://github.com/tensorflow/tensorflow/issues/28388

**Comment by samhodge** [comment]
I am having moderate success with the tensorflow/contrib/cmake project.

There is only a minor modification needed to the CMakelists.txt as the cudnn static is not available for OSX and it is called cudnn.dylib.7 rather than cudnn.so

**Comment by samhodge** [comment]
The success was shortlived, the dnn.proto is not accounted for in the contrib CMake, not is the absl/containers/flatbuffer...

This experience was after getting the CMake file to run succefully on MacOS to find CUDNN, CUDA CUPTI etc

**Comment by samhodge** [comment]
I am continuing on CentOS 7.4 to see if I can get a build done, the configuration via CMake 3.7.2 on CentOS 6.10 was successful but the build was lacking the ability to pull down dependency packages.

**Comment by samhodge** [comment]
Adding related issue
https://github.com/tensorflow/tensorflow/issues/29042

**Comment by mihaimaruseac** [comment]
I think we should close this as makefile build is no longer supported
