### ISSUE TITLE
Updated Eigen breaks builds

### ISSUE THREAD

**Issue by coderforlife** [tensorflow/tensorflow#28948]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Fedora 30
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): source
- TensorFlow version: 2.0
- Python version: 3.7
- Installed using virtualenv? pip? conda?: source in virtualenv
- Bazel version (if compiling from source): 0.25.2-1
- GCC/Compiler version (if compiling from source): 9.1.1-1
- CUDA/cuDNN version: 10.1

**Describe the problem**

master branch earlier today could compile fine, now it no longer can with the following error in many files:

```
external/eigen_archive/unsupported/Eigen/CXX11/../../../Eigen/src/Core/arch/GPU/Half.h(717): error: no suitable constructor exists to convert from "float" to "Eigen::half"
```

It seems commit cf5687d4b3f66fecbab4ac35f89be0b9edac17eb may have caused this since it updated the Eigen version.

**Provide the exact sequence of commands / steps that you executed before running into the problem**

```
virtualenv tensorflow
cd tensorflow
. bin/activate
pip install --upgrade --force-reinstall pip setuptools
pip install wheel numpy scipy keras
git clone https://github.com/tensorflow/tensorflow.git --single-branch --branch master
cd tensorflow

./configure
# Use default values except:
#   CUDA support: Y and TensorRT support: Y
#   Only support compute capability 7.0 and not 6.1

export TMP=/tmp
bazel build --jobs 15 -c opt --config=opt --config=v2 --config=mkl --config=numa \
    --copt=-march=native --cxxopt=-march=native --copt=-O3 --cxxopt=-O3 \
    //tensorflow/tools/pip_package:build_pip_package --verbose_failures
```

**Comment by coderforlife** [comment]
It looks like commit 6b58886adedecdebfab069367f1cf78c893bab24 (which rolls back cf5687d4b3f66fecbab4ac35f89be0b9edac17eb) fixes the issue. I have gotten a lot further with compiling, including at least a few of the files that failed previously. Will update more upon compilation completion.

As a side note, the update of Eigen seemed to only effect CUDA-compiled code (.cu.cc files), but there were so many errors from it that I am not certain.

**Comment by jvishnuvardhan** [comment]
@coderforlife Were you able to resolve the issue? Thanks!

**Comment by coderforlife** [comment]
Building master after commit 6b58886adedecdebfab069367f1cf78c893bab24 worked fine.

**Comment by jvishnuvardhan** [comment]
Closing this out since I understand it to be resolved, but please let me know if I'm mistaken. Thanks!
