### ISSUE TITLE
Eager execution in tf.data map_func

### ISSUE THREAD

**Issue by Zhengtq** [tensorflow/tensorflow#28957]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using):tf-2.0-alpha
- Are you willing to contribute it (Yes/No):No

**Describe the feature and the current behavior/state.**
I really want the release version of TF2.0 could bring the eager mode in the [map_function](https://www.tensorflow.org/api_docs/python/tf/data/Dataset#map) in its tf.data API. For now, TF2.0-alpha do not apply eager mode in the map_function in tf.data API. However, pepole usually use map_function in tf.data API to parse data and do some image augmentation. To parse data in TF is really convenient. But when it comes to image augmentation, the official TF API is far less sufficient(under non eager mode), for people could use some origin Python API or the API from many other third party libraries to do image augmentation which is badly in need of eager mode. So eager mode in tf.data map_function pipeline is really really necessary for us tensorflow users.

**Will this change the current api? How?**

**Who will benefit with this feature?**

**Any Other info.**

**Comment by alew3** [comment]
I think this would be awesome. I just had a lot of issues trying to do image augmentation with TF2 and tf.data. TF2 addons image also don't support graph mode for now. They are also working on a fix.

**Comment by dynamicwebpaige** [comment]
Pinging @jsimsa for visibility. 🙂

**Comment by jsimsa** [comment]
This is not planned to be supported in the near future. I will mark this feature request as "contributions welcome".
