### ISSUE TITLE
`BaseSession._Callable.__del__` doesn’t detect closed session correctly

### ISSUE THREAD

**Issue by EFanZh** [tensorflow/tensorflow#28959]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Arch Linux
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: Not tested
- TensorFlow installed from (source or binary): Binary
- TensorFlow version (use command below): 1.13.1
- Python version: 3.7.3
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

**Describe the current behavior**

`BaseSession._Callable.__del__` doesn’t detect closed session correctly. Running the code I provided below will causes the following error message being printed:

```
Exception ignored in: <function BaseSession._Callable.__del__ at 0x7fe50cc480d0>
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1455, in __del__
    self._session._session, self._handle, status)
  File "/usr/lib/python3.7/site-packages/tensorflow/python/framework/errors_impl.py", line 528, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.CancelledError: Session has been closed.
```

The error message doesn’t affect the correctness of the program, but it is annoying to see.

**Describe the expected behavior**

The test program exits without printing the error message.

**Code to reproduce the issue**

```python
import tensorflow as tf
from tensorflow.core.protobuf.config_pb2 import CallableOptions


def main():
    with tf.Session() as session:
        t = tf.zeros(shape=())

        c = session._make_callable_from_options(CallableOptions(fetch=[t.name]))

        print(c())


if __name__ == '__main__':
    main()
```

**Other info / logs**

Here is my analysis:

- This is the definition of `BaseSession.close`:

  https://github.com/tensorflow/tensorflow/blob/592fa18bc134d9b9527f3d87ba51d6ae0378e3da/tensorflow/python/client/session.py#L736-L747

  If it is called on an alive session, `self._closed` will be set to `True` but `self._session` will not change.
- This is the definition of `BaseSession.__del__`:

  https://github.com/tensorflow/tensorflow/blob/592fa18bc134d9b9527f3d87ba51d6ae0378e3da/tensorflow/python/client/session.py#L749-L764

  This method will set `self._session` to `None`.

- This is the definition of `BaseSession._Callable.__del__`:

  https://github.com/tensorflow/tensorflow/blob/592fa18bc134d9b9527f3d87ba51d6ae0378e3da/tensorflow/python/client/session.py#L1467-L1473

  It only detect `self._session._session`, but not `self._session._closed`.

So if a `BaseSession._Callable` is being destroyed after the corresponding session being closed, but before the session being destroyed, `TF_SessionReleaseCallable` will be called on a closed session, which will raise the exception mentioned above.

There are two possible fixes:

1. Set `self._session` to `None` in `BaseSession.close`.
2. Detect `self._session._closed` in `BaseSession._Callable.__del__`.

Maybe related: #3388, #24367.

**Comment by achandraa** [comment]
I was able to reproduce the issue on Colab with TensorFlow version 1.13.
