### ISSUE TITLE
Tensorflow lite elementwise operation not working in gpu delegate (ADD & SUB)

### ISSUE THREAD

**Issue by anilsathyan7** [tensorflow/tensorflow#28968]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): NIL
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 16.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: OnePlus 3 , Android 8.0.0
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below): TF 1.13
- Python version: 3.5
- Bazel version (if compiling from source): 0.24.1
- GCC/Compiler version (if compiling from source): 5.4.0
- CUDA/cuDNN version: 5.4.0
- GPU model and memory: NIL

**Describe the current behavior**
 
When we are trying to run a tflite model with element-wise operations like ADD and SUB (appended via custom code) on an android application (**org.tensorflow:tensorflow-lite:0.0.1-gpu-experimental**)   it throws an error message and crashes the application.

Also it fails during android benchmark test in gpu mode, with the same error message. However  the same model runs in CPU mode in the same android application and also clears the android benchmark test in CPU mode without errors.

We also tried the same model with tensorflow-lite gpu nightly version. But it does not give any any information about where the nodes are being run (i.e CPU or GPU). The problem is with the last couple of elementwise operations at the end of the model and it looks like they automatically falls back to CPU with '**org.tensorflow:tensorflow-lite:0.0.0-nightly**'. Even the cast operator (not supported by GPU), runs in nighlty tflite GPU delegate without any warning. We believe it is running in CPU, based on the speed or time taken to execute those nodes. TF-lite nightly doesn't give any info of whether it falls back to CPU or runs in GPU (unlike experimental version), when it encounters an unsupported op in GPU.Also it looks like errors and warnings are suppressed in nightlty version.

**Describe the expected behavior**

The tensorflow lite model should run without errors in GPU and CPU with element-wise operators.

**Code to reproduce the issue**

Here is the snapshot of the models which produced the aforementioned errors.

1. Model 1:-

![2](https://user-images.githubusercontent.com/1130185/58264257-2c691d80-7d9b-11e9-8f8f-0d10b9c94e32.png)

2. Model 2:-

![3](https://user-images.githubusercontent.com/1130185/58264318-473b9200-7d9b-11e9-8838-68871f946df3.png)

Models: 
[Models.zip](https://github.com/tensorflow/tensorflow/files/3212972/Models.zip)

Both run in CPU mode; but fails in GPU !!!

**Other info / logs**

1. **Model 1 Error Log :  With ADD and SUB**

adb shell /data/local/tmp/benchmark_model_gpu --graph=/data/local/tmp/work_test_trial_fulltest_257op_dm05_257_blend_cast_dbadd6.tflite --use_gpu=true
adb: /opt/intel/intelpython27/lib/libcrypto.so.1.0.0: no version information available (required by adb)
STARTING!
Min num runs: [50]
Min runs duration (seconds): [1]
Inter-run delay (seconds): [-1]
Num threads: [1]
Benchmark name: []
Output prefix: []
Min warmup runs: [1]
Min warmup runs duration (seconds): [0.5]
Graph: [/data/local/tmp/work_test_trial_fulltest_257op_dm05_257_blend_cast_dbadd6.tflite]
Input layers: []
Input shapes: []
Use nnapi : [0]
Use legacy nnapi : [0]
Use gpu : [1]
Allow fp16 : [0]
nnapi error: requires android sdk version to be at least 27
Loaded model /data/local/tmp/work_test_trial_fulltest_257op_dm05_257_blend_cast_dbadd6.tflite
resolved reporter
INFO: Initialized TensorFlow Lite runtime.
INFO: Created TensorFlow Lite delegate for GPU.
ERROR: Next operations are not supported by GPU delegate:
**SUB: Incorrect operation type passed**
First 77 operations will run on the GPU, and the remaining 2 on the CPU.
**ERROR: TfLiteGpuDelegate Prepare: fuse_auto_input failed**
ERROR: Node number 79 (TfLiteGpuDelegate) failed to prepare.

Failed to apply GPU delegate.
Aborted 

2. **Model 2 Error Log: With ADD only**

adb shell /data/local/tmp/benchmark_model_gpu --graph=/data/local/tmp/work_test_trial_fulltest_257op_dm05_257_blend_cast_dbadd8.tflite --use_gpu=true
adb: /opt/intel/intelpython27/lib/libcrypto.so.1.0.0: no version information available (required by adb)
STARTING!
Min num runs: [50]
Min runs duration (seconds): [1]
Inter-run delay (seconds): [-1]
Num threads: [1]
Benchmark name: []
Output prefix: []
Min warmup runs: [1]
Min warmup runs duration (seconds): [0.5]
Graph: [/data/local/tmp/work_test_trial_fulltest_257op_dm05_257_blend_cast_dbadd8.tflite]
Input layers: []
Input shapes: []
Use nnapi : [0]
Use legacy nnapi : [0]
Use gpu : [1]
Allow fp16 : [0]
nnapi error: requires android sdk version to be at least 27
Loaded model /data/local/tmp/work_test_trial_fulltest_257op_dm05_257_blend_cast_dbadd8.tflite
resolved reporter
INFO: Initialized TensorFlow Lite runtime.
INFO: Created TensorFlow Lite delegate for GPU.
ERROR: TfLiteGpuDelegate Prepare: fuse_auto_input failed
ERROR: Node number 76 (TfLiteGpuDelegate) failed to prepare.

Failed to apply GPU delegate.
Aborted

Also refer: Issue #28606

Is the issue fixed in latest nightly or experimental versions?
We tried the following gradle dependencies in app:-
1. org.tensorflow:tensorflow-lite-gpu:0.0.0-nightly
2. org.tensorflow:tensorflow-lite:0.0.1-gpu-experimental

But it does not run properly with either of the versions ...

**Comment by anilsathyan7** [comment]
I managed to build the tflite and tflite-gpu aar from source by downloading the latest tensorflow and compiling them using bazel. I followed the instruction from the following  link- https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/java/BUILD. (Hope this way we can get the latest updates..)

Now the error ''SUB: Incorrect operation type passed' seems to be resolved.Also this time we were able to get the complete error log about the node execution( CPU or GPU) in android.Also the NNAPI package not found error was also resolved(but it's still there when we use Jcenter gradle dependency).

However two other issues still remains unresolved...
Here is the error log 

```
05-25 12:47:13.384 15160-15190/android.example.com.tflitecamerademo E/AndroidRuntime: FATAL EXCEPTION: CameraBackground
    Process: android.example.com.tflitecamerademo, PID: 15160
    java.lang.IllegalArgumentException: Internal error: Failed to apply delegate: Next operations are not supported by GPU delegate:
    **SUB: Expected 2 input tensor(s), but node has 1 runtime input(s).**
    **First 77 operations will run on the GPU, and the remaining 4 on the CPU.TfLiteGpuDelegate Prepare: Number of outputs exceeds 1Node number 81 (TfLiteGpuDelegate) failed to prepare.**

```

![error_tflite](https://user-images.githubusercontent.com/1130185/58366387-0f456380-7eef-11e9-8fe6-888c312f0650.png)

Issues:- 
1. SUB: Expected 2 input tensor(s), but node has 1 runtime input(s).
2. Number of outputs exceeds 1Node number
3. Even though all nodes are GPU supported ops, its falling back to CPU

![error2](https://user-images.githubusercontent.com/1130185/58366472-51bb7000-7ef0-11e9-9a51-e6b1381cdcdc.png)

The same issue (Number of outputs exceeds 1Node number) exists in the above model.

However in CPU mode the models run without any issues...

[models2.zip](https://github.com/tensorflow/tensorflow/files/3219213/models2.zip)

**Comment by anilsathyan7** [comment]
Here is another example where add, sub and mul have different behaviours..

1. Add

```
Error:- ERROR: TfLiteGpuDelegate Prepare: fuse_auto_input failed
ERROR: Node number 76 (TfLiteGpuDelegate) failed to prepare.

```
Failed to apply GPU delegate.
Aborted

![add](https://user-images.githubusercontent.com/1130185/58468457-33a57800-815b-11e9-92d4-d291884496ff.png)

2. Sub

Error:- Falls back to CPU

```
ERROR: Next operations are not supported by GPU delegate:
SUB: Incorrect operation type passed
First 75 operations will run on the GPU, and the remaining 1 on the CPU.
Applied GPU delegate.
```


![sub](https://user-images.githubusercontent.com/1130185/58468501-48820b80-815b-11e9-8d69-bde2c9095750.png)

**But the same model works with mul !!!**

![mul](https://user-images.githubusercontent.com/1130185/58468544-5c2d7200-815b-11e9-8865-c510a4de38d4.png)

Also all the above models works with CPU ...

**Comment by anilsathyan7** [comment]
We tried to benchmark the above models in latest android benchmark tool; but got "fuse_auto_input failed" error for SUB and ADD operators

**Comment by impjdi** [comment]
@anilsathyan7 

Thanks for atttaching the model.  I'll pass that on to one of our engineers.

re: fuse_auto_input, you can see that the error comes from gpu/gl/compiler.cc when options_.auto_input_fusion is enabled.  This is not the external option, but an internal one.  If this is blocking you, I would suggest disabling fuse_auto_input.

**Comment by anilsathyan7** [comment]
How can we disable fuse_auto_input during tflite conversion?

**Comment by impjdi** [comment]
Not during conversion.

In `tensorflow/lite/delegates/gpu/gl_delegate.cc`, add `compile_options.auto_input_fusion = false;` to where the rest of `compile_options` are specified.

**Comment by yxchng** [comment]
@impjdi Any updates on this?

**Comment by yxchng** [comment]
@impjdi When will this bug be resolved? The compile options for `auto_input_fusion` does not seem to work for TFLiteConverter in TF 2.0.

**Comment by impjdi** [comment]
Sorry, forgot to reply to your question in December.

Since I haven't heard back from @anilsathyan7 , I assume he's good.  I usually don't close issues myself, leaving it up to the OP.

I ran his TFLite models just now and things seem to run fine--that's with TFLiteGpuDelegateV2.

**Comment by impjdi** [comment]
Nope, never mind.  I can see this fails when I force things to be run on OpenGL.

**Comment by impjdi** [comment]
Okay.  I looked deeper into this.  I found the issue but the fix is not trivial at the moment, i.e. it's gonna take some time to fix this.

The pattern this `fuse_auto_input` is not able to handle is the following diamond case:

`A -> B -> D`
`A -> C -> D`

When it comes to fusing `B`, `C`, and `D` into a fused `D`, the rule assumes that the inputs of `B` and `C` are different tensors, but in this case, they are the same (`A`) and the fusion fails.

**Comment by impjdi** [comment]
commit 8eaea75c6d89239e88c8c4b0a0077cba5c519ef2 should guard this issue.  There will be a proper fix, but for now, this should make your network not crash anymore.

**Comment by JeiKeiLim** [comment]
Came across here while googling same issue.

No problem
``` python
xy_div0 = tf.fill(tf.shape(feat_xy0), 1.23)
box_xy0 = tf.sigmoid(feats0[:, :, :, 0:1]) / xy_div0

# or

box_xy0 = tf.sigmoid(feats0[:, :, :, 0:1]) / 1.23
```

Problem
``` python
xy_div0 = tf.fill(tf.shape(feat_xy0), div_shape[0])
box_xy0 = tf.sigmoid(feats0[:, :, :, 0:1]) / xy_div0

# or, of course

box_xy0 = tf.sigmoid(feats0[:, :, :, 0:1]) / div_shape[0]
```

This is frustrating. All I wanted to do is simple divide and I cannot do it.
I will keep digging whether there is a workaround to do this.

**Comment by impjdi** [comment]
@JeiKeiLim does mul work instead of div?

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this issue, as you are using an older version of tensorflow(1.x) which is officially considered as end of life. We recommend that you upgrade to 2.4 or later version and let us know if the issue still persists in newer versions. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, Please open a new issue for any help you need against 2.x, and we will get you the right help.
