### ISSUE TITLE
tensorflow compile error

### ISSUE THREAD

**Issue by allendred** [tensorflow/tensorflow#28961]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>
**grpc** **sha256** checksum was"*" but wanted"*"
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):source
- TensorFlow version:branch:master  05/23/2019
- Python version:2.7
- Installed using virtualenv? pip? conda?:
- Bazel version (if compiling from source):0.24.1
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:10/7.5.1
- GPU model and memory:

8g
**Describe the problem**
Downloading  **grpc** from github ,the sha256 checksum is not suit for the .bzl files.
**Provide the exact sequence of commands / steps that you executed before running into the problem**
Almost every time I compile tensorflow ,this bug will turn out.
the last few times I was lucky,the  sha code was right after  tried so .many times.

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by fsx950223** [comment]
> _Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template_
> **grpc** **sha256** checksum was"_" but wanted"_"
> **System information**
> 
> * OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
> * Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
> * TensorFlow installed from (source or binary):source
> * TensorFlow version:branch:master  05/23/2019
> * Python version:2.7
> * Installed using virtualenv? pip? conda?:
> * Bazel version (if compiling from source):0.24.1
> * GCC/Compiler version (if compiling from source):
> * CUDA/cuDNN version:10/7.5.1
> * GPU model and memory:
> 
> 8g
> **Describe the problem**
> Downloading **grpc** from github ,the sha256 checksum is not suit for the .bzl files.
> **Provide the exact sequence of commands / steps that you executed before running into the problem**
> Almost every time I compile tensorflow ,this bug will turn out.
> the last few times I was lucky,the sha code was right after tried so .many times.
> 
> **Any other info / logs**
> Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.
Bad network will lead this problem,you can download grpc package from browser and set a web server for the package,then you change bzl url to your server url and you can download package from your server directly.

**Comment by allendred** [comment]
> > _Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template_
> > **grpc** **sha256** checksum was"_" but wanted"_"
> > **System information**
> > 
> > * OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
> > * Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
> > * TensorFlow installed from (source or binary):source
> > * TensorFlow version:branch:master  05/23/2019
> > * Python version:2.7
> > * Installed using virtualenv? pip? conda?:
> > * Bazel version (if compiling from source):0.24.1
> > * GCC/Compiler version (if compiling from source):
> > * CUDA/cuDNN version:10/7.5.1
> > * GPU model and memory:
> > 
> > 8g
> > **Describe the problem**
> > Downloading **grpc** from github ,the sha256 checksum is not suit for the .bzl files.
> > **Provide the exact sequence of commands / steps that you executed before running into the problem**
> > Almost every time I compile tensorflow ,this bug will turn out.
> > the last few times I was lucky,the sha code was right after tried so .many times.
> > **Any other info / logs**
> > Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.
> 
> Bad network will lead this problem,you can download grpc package from browser and set a web server for the package,then you change bzl url to your server url and you can download package from your server directly.
THANKS
