### ISSUE TITLE
Adding multiclass support to BoostedTreesClassifier

### ISSUE THREAD

**Issue by leticiawanderley** [tensorflow/tensorflow#28979]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using): 1.13.1
- Are you willing to contribute it (Yes/No): Yes

**Describe the feature and the current behavior/state.**
The BoostedTreesClassifier supports binary classification only.

**Will this change the current api? How?**
No. The API already has a placeholder parameter `n_classes`.

**Who will benefit with this feature?**
People who need to perform multiclass classification.

**Any Other info.**

**Comment by nickelbob** [comment]
Hi! Has there been any progress on this? If not, can anyone describe an implementation path? I'd be willing to take a crack at it if it is not too involved. Thank!

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.

**Comment by ymodak** [comment]
Multi-class support for BoostedTreesClassifier is now added. Thanks!
https://www.tensorflow.org/api_docs/python/tf/estimator/BoostedTreesClassifier#args_1
