### ISSUE TITLE
It is too painful to install a gpu-surpport edition on Ubuntu 16.04

### ISSUE THREAD

**Issue by MMingabc** [tensorflow/tensorflow#2897]

**Comment by yaroslavvb** [comment]
You'll need CUDA 8.0 and latest NVidia drivers. Here are instructions I followed to install them
https://gist.github.com/yaroslavvb/07b2d9a828f82792ebef2a080e814f0f

A small side-effect is that X server will no longer work after this, but you'll be able to run TensorFlow through SSH

**Comment by sherrym** [comment]
I will consider this resolved. :)

**Comment by wagonhelm** [comment]
I walked through how to do it with Ubuntu 16.04 and using Cuda 7-5 using apt-get.

https://www.youtube.com/watch?v=HM57GyqwGxA
