### ISSUE TITLE
[TF 1.13]: Mishandling dropout and recurrent dropout when feeding them as placeholder inputs to SimpleRNNCell in tf.keras.layers

### ISSUE THREAD

**Issue by kusur** [tensorflow/tensorflow#28983]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): NA (Working on Google Colab)
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: NA
- TensorFlow installed from (source or binary): NA (Working on Google Colab)
- TensorFlow version (use command below): 1.13.1
- Python version: 3.6.7
- Bazel version (if compiling from source): NA (Working on Google Colab)
- GCC/Compiler version (if compiling from source): NA (Working on Google Colab)
- CUDA/cuDNN version: NA (Working on Google Colab)
- GPU model and memory: NA (Working on Google Colab)

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
I am trying to use `tf.keras.layers` in my code to see how it works. While trying to forecast time series in Tensorflow using RNN, I am using dropout method. If I hard-code the values of `dropout` and `recurrent_dropout`, my program runs perfectly. However, I need to perform inference on the model and for that the dropout needs to be turned off. I am using `tf.placeholder_with_default` but this is throwing an error.

**Describe the expected behavior**
Ideally there should be no error while using `tf.placeholder_with_default` but since `recurrent.py` allows only float values for `dropout` and `recurrent_dropout` this error is coming up. Is there any way to pass `dropout` and `recurrent_dropout` values at runtime?

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.
```Python
# Library imports
import matplotlib.pyplot as plt
import tensorflow as tf
import numpy as np

# Variable initialization
t_min = 0
t_max = 30
resolution = 1e-2
n_steps = 20
n_inputs = 1
n_outputs = 1
n_neurons = 100
learning_rate = 1e-2

TimeSeriesDropout_graph = tf.Graph()
with TimeSeriesDropout_graph.as_default():
  keep_prob_input_default = np.array(1.0,dtype='float32')
  keep_prob_input = tf.placeholder_with_default(keep_prob_input_default,shape=())
  keep_prob_state_default = np.array(1.0,dtype='float32')
  keep_prob_state = tf.placeholder_with_default(keep_prob_state_default,shape=())
#   keep_prob_input = 0.5
#   keep_prob_state = 0.5
  X = tf.placeholder(dtype=tf.float32,shape=(None,n_steps,n_inputs))
  y = tf.placeholder(dtype=tf.float32,shape=(None,n_steps,n_outputs))
  multiple_rnn_cell = [tf.keras.layers.SimpleRNNCell(units=n_neurons,activation='relu'
                                                     ,dropout=keep_prob_input
                                                     ,recurrent_dropout=keep_prob_state)
                     ,tf.keras.layers.SimpleRNNCell(units=n_neurons//2,activation='relu'
                                                     ,dropout=keep_prob_input
                                                    ,recurrent_dropout=keep_prob_state)
                     ,tf.keras.layers.SimpleRNNCell(units=n_neurons//4,activation='relu'
                                                     ,dropout=keep_prob_input
                                                    ,recurrent_dropout=keep_prob_state)
                     ,tf.keras.layers.SimpleRNNCell(units=n_neurons//8,activation='relu'
                                                     ,dropout=keep_prob_input
                                                    ,recurrent_dropout=keep_prob_state)]
  stacked_rnn_cell = tf.keras.layers.StackedRNNCells(multiple_rnn_cell)
  rnn_output = tf.keras.layers.RNN(stacked_rnn_cell,return_sequences=True,return_state=True)(X)
  outputs_reshaped = tf.reshape(rnn_output[0],(-1,n_neurons//8))
  output = tf.keras.layers.Dense(units=n_outputs)(outputs_reshaped)
  output_stacked = tf.reshape(output,(-1,n_steps,n_outputs))
  loss = tf.reduce_mean(tf.square(y-output_stacked))
  optimizer = tf.train.AdamOptimizer(learning_rate=learning_rate)
  training_op = optimizer.minimize(loss)
  init = tf.global_variables_initializer()
  saver = tf.train.Saver()
```

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

```bash
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-30-16da420b4722> in <module>()
     10   multiple_rnn_cell = [tf.keras.layers.SimpleRNNCell(units=n_neurons,activation='relu'
     11                                                      ,dropout=keep_prob_input
---> 12                                                      ,recurrent_dropout=keep_prob_state)
     13                      ,tf.keras.layers.SimpleRNNCell(units=n_neurons//2,activation='relu'
     14                                                      ,dropout=keep_prob_input

1 frames
/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/layers/recurrent.py in __init__(self, units, activation, use_bias, kernel_initializer, recurrent_initializer, bias_initializer, kernel_regularizer, recurrent_regularizer, bias_regularizer, kernel_constraint, recurrent_constraint, bias_constraint, dropout, recurrent_dropout, **kwargs)
   1061     self.bias_constraint = constraints.get(bias_constraint)
   1062 
-> 1063     self.dropout = min(1., max(0., dropout))
   1064     self.recurrent_dropout = min(1., max(0., recurrent_dropout))
   1065     self.state_size = self.units

/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py in __bool__(self)
    651       `TypeError`.
    652     """
--> 653     raise TypeError("Using a `tf.Tensor` as a Python `bool` is not allowed. "
    654                     "Use `if t is not None:` instead of `if t:` to test if a "
    655                     "tensor is defined, and use TensorFlow ops such as "

TypeError: Using a `tf.Tensor` as a Python `bool` is not allowed. Use `if t is not None:` instead of `if t:` to test if a tensor is defined, and use TensorFlow ops such as tf.cond to execute subgraphs conditioned on the value of a tensor.
```

**Comment by achandraa** [comment]
In order to expedite the trouble-shooting process, please provide a full minimal code snippet to reproduce the issue reported here. Thanks!

**Comment by kusur** [comment]
@achandraa The code given in the original post reproduces the issue. The only caveat is that this code was run on Google Colab. Please let me know if you need any more information from me.

**Comment by achandraa** [comment]
Will it be possible to provide the values for various parameters you are trying as in n_steps, n_inputs, n_outputs etc to check the exact code snippet for the issue. This will help us to proceed faster. Thanks!

**Comment by kusur** [comment]
@achandraa My apologies. I have updated the original code snippet with all the relevant library imports and variable initializations

**Comment by achandraa** [comment]
Thanks for sharing the information. I have tried on Colab  with TensorFlow version 1.13.1 and was able to reproduce the issue.

**Comment by qlzh727** [comment]
If you check the implementation of the dropout in keras, it actually has a switch for turning on/off based on whether its in training mode or not. See https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/keras/layers/recurrent.py#L2662. 

As long as your custom training code is populating the "learning_phase" value correctly, then it will correctly enable/disable dropout during training and inferencing. The value is auto populated if you are using keras model.fit/eval/predict. If you are using different training loop, then just set the value by keras.backend.set_learning_phase(). See https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/keras/backend.py#L307

**Comment by qlzh727** [comment]
Also, as the doctring stated, the dropout/recurrent_dropout should just be float, rather than tensor or placeholder. So the code is working as intended.

https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/keras/layers/recurrent.py#L1287

**Comment by kusur** [comment]
@qlzh727 Thanks for your response and apologies for coming back so late on this. I understand that as the code is functioning as per the documentation. While I understand that Keras disables training at the time of inference, this is not something which seems applicable to Tensorflow. Could you please help me understand why was the decision of not allowing tensors as dropout in RNN taken?

**Comment by qlzh727** [comment]
Keras dropout is designed exactly to help user avoid feeding placeholder and turn on/off between training and inference. 

Since dropout does not make sense during inference, what user should worry about is only the dropout rate during training. Asking user to be aware of training/inference context, and managing the switching is too much overhead. That's why we design the API to consume the complexity for user, and let them focus on building the model.
