### ISSUE TITLE
how to compile the Tensorflow source code  on Mac

### ISSUE THREAD

**Issue by HOTFIGHTER** [tensorflow/tensorflow#28988]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):  Mac
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): source
- TensorFlow version:  r1.12
- Python version: 2.7
- Installed using virtualenv? pip? conda?:
- Bazel version (if compiling from source): 0.15.0
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Describe the problem**
when I build the TensorFlow, The error result is:
ERROR: /private/var/tmp/_bazel_xmly/88507af8aae72d6d7037a76bc898c925/external/protobuf_archive/BUILD:260:1: Linking of rule '@protobuf_archive//:js_embed' failed (Exit 1)
ld: unknown option: -no-as-needed
clang: error: linker command failed with exit code 1 (use -v to see invocation)
Target //tensorflow:libtensorflow_cc.so failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 1.394s, Critical Path: 0.40s
INFO: 0 processes.
FAILED: Build did NOT complete successfully

**Provide the exact sequence of commands / steps that you executed before running into the problem**

The methods I already tried are:
./configure
bazel build -c opt //tensorflow:libtensorflow_cc.so

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by muddham** [comment]
@HOTFIGHTER Please refer the steps mentioned in this [link](https://www.tensorflow.org/install/source#tested_build_configurations)

**Comment by muddham** [comment]
@HOTFIGHTER Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
