### ISSUE TITLE
[make] gen_file_lists.sh output to wrong directory

### ISSUE THREAD

**Issue by StephenOman** [tensorflow/tensorflow#2899]
The gen_file_lists.sh script in contrib/makefile outputs the generated lists to the incorrect directory:

```
bazel query 'kind("source file", deps(//tensorflow/core:android_tensorflow_lib))' | \
grep "//tensorflow/.*\.cc$" | \
grep -v "gen_proto_text" | \
grep -E -v "jpeg" | \
grep -E -v "png" | \
sed -E 's#^//##g' | \
sed -E 's#:#/#g' \
> make/tf_cc_files.txt
```

The "make/" should be removed as "make" expects the lists to be in the same directory as the Makefile.

**Comment by petewarden** [comment]
Thanks for the report! This should be fixed in #2936, closing now.
