### ISSUE TITLE
Is there any c++ api examples for tensorflow lite？

### ISSUE THREAD

**Issue by engineer1109** [tensorflow/tensorflow#28999]
I dont like java and swift.
I prefer c++.
However, I seldom see any c++ api helps.

**Comment by lwu025** [comment]
There are two examples I found:
tensorflow/lite/examples/label_image
and 
tensorflow/lite/tools/benchmark

**Comment by muddham** [comment]
@engineer1109 Did you get chance to review the link suggested by @lwu025

**Comment by gadagashwini** [comment]
Closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
