### ISSUE TITLE
bazel build failed on tf1.6 on tx2

### ISSUE THREAD

**Issue by mpkuse** [tensorflow/tensorflow#28990]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 16.04 (aarch64)
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): source (trying to install)
- TensorFlow version: v1.6.0
- Python version: 2.7
- Installed using virtualenv? pip? conda?:
- Bazel version (if compiling from source): 0.11 (installed from sourcecode)
- GCC/Compiler version (if compiling from source): 5.4
- CUDA/cuDNN version: 9.0/7
- GPU model and memory: Nvidia Jetson TX2 (DJI Manifold2)

**Describe the problem**
On my DJI Manifold2 (Nvidia TX2) I am trying to install tensorflow. I am trying to install from scratch. 
The tx2 was not setup with the jetpack, however, it has cuda9 and cudnn7 installed. 
I am following these instructions: https://gist.github.com/vellamike/7c26158c93e89ef155c1cc953bbba956 

I could install bazel (0.11.0) successfully. 
`./configure` works alright. I have said no to everything accept for cuda and jemalloc. 

```
bazel build --verbose_failures --config=opt --config=cuda //tensorflow/tools/pip_package:build_pip_package 
```

This fails to give: 
````
INFO: From Compiling tensorflow/core/kernels/tile_functor_gpu.cu.cc:
Killed
ERROR: /home/dji/Downloads/tensorflow/tensorflow/core/kernels/BUILD:848:1: output 'tensorflow/core/kernels/_objs/tile_ops_gpu/tensorflow/core/kernels/tile_functor_gpu.cu.pic.o' was not created
ERROR: /home/dji/Downloads/tensorflow/tensorflow/core/kernels/BUILD:848:1: not all outputs were created or valid
Target //tensorflow/tools/pip_package:build_pip_package failed to build
INFO: Elapsed time: 84.543s, Critical Path: 82.14s
FAILED: Build did NOT complete successfully
```
Please see attachement for full lowg
[errorlog.txt](https://github.com/tensorflow/tensorflow/files/3216060/errorlog.txt)

**Comment by gadagashwini** [comment]
@mpkuse Please have look on [Tested build configuration](https://www.tensorflow.org/install/source#tested_build_configurations) for Tf-gpu 1.6.0.Thanks!

**Comment by gadagashwini** [comment]
Were you able to resolve this?

**Comment by gadagashwini** [comment]
Closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
