### ISSUE TITLE
how to use xla with c++ api in tensorflow

### ISSUE THREAD

**Issue by x666633** [tensorflow/tensorflow#28996]
tensorflow_version: 1.13.1
other： C++ inference; CPU
My steps are as follows: 
1. I trained with Python on GPU
2. converted  model with freeze_graph.py
3. put it on CPU and use c++ language for inference.

How to use C++ to open the XLA settings, I use the following code,  no effect(before timecost == after timecost).

OptimizerOptions optimizer_options = _tf_options.config.graph_options().optimizer_options();
optimizer_options.set_global_jit_level(OptimizerOptions::ON_1);

GraphOptions graph_options = _tf_options.config.graph_options();
graph_options.mutable_optimizer_options()->CopyFrom(optimizer_options);

_tf_options.config.mutable_graph_options()->CopyFrom(graph_options);
@sanjoy

**Comment by gadagashwini** [comment]
@x666633 It looks This is not Build/Installation or Bug/Performance issue. Please post this kind of support questions at Stackoverflow. There is a big community to support and learn from your questions. GitHub is mainly for addressing bugs in installation and performance. If you still stuck, you can get back to us.Thanks!

**Comment by gadagashwini** [comment]
Closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Comment by tangjie77wd** [comment]
@x666633  Hello,have you solved this problem? I have the same with you .
