### ISSUE TITLE
Unable to get predictions from .tflite graph.

### ISSUE THREAD

**Issue by deepLearningEnthusiast** [tensorflow/tensorflow#28997]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- TensorFlow installed from (source or binary): tensorflow installed using pip
- TensorFlow version (use command below): 1.13.1
- Python version: python 3.6
- Bazel version (if compiling from source): 0.25.2
- CUDA/cuDNN version:  10.0
- GPU model and memory: NVIDIA GeForce GTX 1080 Ti 

**Describe the current behavior**
I have fine tuned ssdlite_mobilenet_v1 model and have the frozen graph post completion of training process.

Used the below mentioned code to convert the frozen.pb grpah into tflite version.
tflite_convert \
--output_file=test.tflite \
--graph_def_file=tflite_graph.pb \
--input_arrays=normalized_input_image_tensor \
--output_arrays='TFLite_Detection_PostProcess','TFLite_Detection_PostProcess:1','TFLite_Detection_PostProcess:2','TFLite_Detection_PostProcess:3' \
--input_shape=1,300,300,3 \
--allow_custom_ops

I wanted to confirm if the results on test data of tflite model matches the frozen.pb file, however the model would not give out any output at all. 

	interpreter =tf.lite.Interpreter(model_path="path/to/test.tflite")
	interpreter.allocate_tensors()
	input_details = interpreter.get_input_details()
	output_details = interpreter.get_output_details()
        // image is of format 1 x300x300x3 and the avlues are between -1 to 1
      	interpreter.set_tensor(input_details[0]['index'], image)
	output_data1 = interpreter.get_tensor(output_details[0]['index'])
	classes = interpreter.get_tensor(output_details[1]['index'])
	confidence_scores = interpreter.get_tensor(output_details[2]['index'])
print(output_data1)
print(classes)
print(confidence_scores)

The print statements give no result out. 

Any help provided would be greatly appreciated.

**Comment by haozha111** [comment]
did you forget to call interpreter.invoke()?

**Comment by ramyrao** [comment]
Thank you for your response.
I did know I had to use interpreter.invoke(). 
However, when I used invoke() I ran into another error in the below mentioned line
```
output_data1 = interpreter.get_tensor(output_details[0]['index'])
```

Error Message:
ValueError: Cannot set tensor: Got tensor of type 0 but expected type 1 for input 260 

Input details are as follows:
input_details: [{'name': 'normalized_input_image_tensor', 'index': 260, 'shape': array([  1, 300, 300,   3], dtype=int32), 'dtype': <class 'numpy.float32'>, 'quantization': (0.0, 0)}]

Please let me know if you need any other information to help me figure this out

**Comment by deepLearningEnthusiast** [comment]
Thank you for your response.
I did know I had to use interpreter.invoke().
However, when I used invoke() I ran into another error in the below mentioned line

interpreter.set_tensor(input_details[0]['index'], image)
Error Message:
ValueError: Cannot set tensor: Got tensor of type 0 but expected type 1 for input 260

Input details are as follows:
input_details: [{'name': 'normalized_input_image_tensor', 'index': 260, 'shape': array([ 1, 300, 300, 3], dtype=int32), 'dtype': <class 'numpy.float32'>, 'quantization': (0.0, 0)}]

Please let me know if you need any other information to help me figure this out

**Comment by haozha111** [comment]
Sorry for the late. The input tensor `normalized_input_image_tensor` should have float32 type, but it seems like you are passing the `image` array with the wrong type. Could you check again if the data type is matched?

**Comment by ymodak** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
