### ISSUE TITLE
[Translation] Translation for Korean

### ISSUE THREAD

**Issue by polpolie** [tensorflow/tensorflow#28994]
We've translated this part of guidelines to Korean on our repository with github pages.

This is URL of Korean repository : https://github.com/BangSeongJin/translation_to_korean.git

**Comment by muddham** [comment]
@polpolie I understand that you have translated this github page, can you please let us know the purpose of this issue in detail, so that we can take this forward.

**Comment by polpolie** [comment]
We learned about the tensor flow that is becoming an issue these days through various media,
So we have been working on the Korean Herbal Tensor Flow Community. And
We are looking for other ways to apply open source.

**Comment by jvishnuvardhan** [comment]
@polpolie you could raise Pull Requests and merge your contributions into the `master` branch of TensorFlow or TF2.0. Thanks!

**Comment by kumariko** [comment]
@polpolie Could you please let us know if you still need help on this ? if it is resolved then please feel free to move this issue to close status ? Thanks!

**Comment by jvishnuvardhan** [comment]
Closing this due to lack of recent activity. Thanks!
