### ISSUE TITLE
minimum req: Cuda compute capability 3.5

### ISSUE THREAD

**Issue by graphific** [tensorflow/tensorflow#29]
Tensorflow seems to require a cuda compute capability of 3.5, thereby excluding amazon G2 instances which use a GRID K520 with 3.0, might be good to know:

	tensorflow/core/common_runtime/gpu/gpu_init.cc:88] Found device 0 with properties:
	name: GRID K520
	major: 3 minor: 0 memoryClockRate (GHz) 0.797
	pciBusID 0000:00:03.0
	Total memory: 4.00GiB
	Free memory: 3.95GiB
	I tensorflow/core/common_runtime/gpu/gpu_init.cc:112] DMA: 0
	I tensorflow/core/common_runtime/gpu/gpu_init.cc:122] 0:   Y
	I tensorflow/core/common_runtime/gpu/gpu_device.cc:611] Ignoring gpu device (device: 0, name: GRID K520, pci bus id: 0000:00:03.0) with Cuda compute capability 3.0. The minimum required Cuda capability is 3.5.
	I tensorflow/core/common_runtime/gpu/gpu_device.cc:611] Ignoring gpu device (device: 0, name: GRID K520, pci bus id: 0000:00:03.0) with Cuda compute capability 3.0. The minimum required Cuda capability is 3.5.
	I tensorflow/core/common_runtime/gpu/gpu_device.cc:611] Ignoring gpu device (device: 0, name: GRID K520, pci bus id: 0000:00:03.0) with Cuda compute capability 3.0. The minimum required Cuda capability is 3.5.

**Comment by vrv** [comment]
Thanks!  De-duping with https://github.com/tensorflow/tensorflow/issues/25
