### ISSUE TITLE
Check code description in seq2seq.py - embedding_rnn_seq2seq

### ISSUE THREAD

**Issue by hugman** [tensorflow/tensorflow#290]
I'm checking the codes line by line to understand how TF works. 

Please check following comments are correct or not. 

https://github.com/tensorflow/tensorflow/blob/master/tensorflow/models/rnn/seq2seq.py#L198-L199

It seems that the encoder_inputs for <code>embedding_rnn_seq2seq</code> should have indexs of vocabularies.

<code> encoder_inputs: [batch_size] </code> 
<code> decoder_inputs: [batch_size] </code>

If not, give some tips to understand it.

**Comment by lukaszkaiser** [comment]
You're right, they should be 1D batch-size tensors of integers. Correcting, great thanks for bringing this up!

**Comment by hugman** [comment]
There are similar comment - mistakes in embedding_* classes. (It's not that serious though)

**Comment by vrv** [comment]
If there are comments to be fixed, please send PRs for them -- I think we correct some of these already.
