### ISSUE TITLE
How to improve MKL performance? 

### ISSUE THREAD

**Issue by x666633** [tensorflow/tensorflow#29008]
**system information**

OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux
TensorFlow installed from (source or binary): source
TensorFlow version: 1.13.1
Python version: 2.7.13
GCC/Compiler version (if compiling from source): 5.4
MKL  version: mklml_lnx_2019.0.3.20190220/

**Describe the problem**
My steps are as follows:

1. I trained with Python on GPU
2. converted model with freeze_graph.py
3. put it on CPU and use c++  for inference 
   (build tensorflow source with --config=mkl --copt="-DEIGEN_USE_VML"

**my MKL setting is**
setenv("KMP_BLOCKTIME","0",1);
setenv("KMP_SETTIONS","1",1);
setenv("KMP_AFFINITY","granularity=fine,verbose,compact,1,0",1);
setenv("OMP_NUM_THREADS",num_of_theads.c_str(),1);

**my model is bert**

**my cpuinfo is** 
vendor_id	: GenuineIntel
cpu family	: 6
model		: 79
model name	: Intel(R) Xeon(R) CPU E5-26xx v4
stepping	: 1
microcode	: 0x1
cpu MHz		: 2394.446
cache size	: 4096 KB
physical id	: 0
siblings	: 16
core id		: 15
cpu cores	: 16
apicid		: 15
initial apicid	: 15
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx lm constant_tsc rep_good nopl eagerfpu pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch bmi1 avx2 bmi2 rdseed adx xsaveopt
bogomips	: 4788.89
clflush size	: 64
cache_alignment	: 64
address sizes	: 40 bits physical, 48 bits virtual

**my test result  :**
(C++ inference CPU)
a. use MKL :  200ms
b. do not use MKL: 200ms

**How can I improve performance？？**

@Leslie-Fang  @TensorFlow-MKL

**Comment by x666633** [comment]
setenv("KMP_BLOCKTIME","0",1);
setenv("KMP_SETTIONS","1",1);
setenv("KMP_AFFINITY","granularity=fine,verbose,compact,1,0",1);
setenv("OMP_NUM_THREADS",4,1);


batch_size_32_nomkl: 800ms
batch_size_32_mkl:300ms

batch_size_1_nomkl: 200ms
batch_size_1_mkl:200ms

**how can i change the mklsetting to impove my batchsize_1 performance**

**Comment by preethivenkatesh** [comment]
Could you please try these settings

KMP_AFFINITY=granularity=fine,verbose,compact,1,0
KMP_BLOCKTIME=	1
OMP_NUM_THREADS=	# of physical cores
intra_op_parallelism_threads=# physical cores
inter_op_parallelism_threads=1

you can set it using the code snippet before running the session
```
import os
os.environ["KMP_BLOCKTIME"] = "1"
os.environ["KMP_SETTINGS"] = "1"
os.environ["KMP_AFFINITY"]= "granularity=fine,verbose,compact,1,0"
os.environ["OMP_NUM_THREADS"]= <# physical cores>
config = tf.ConfigProto()
config.intra_op_parallelism_threads = <# physical cores>
config.inter_op_parallelism_threads = 1
tf.Session(config=config)
```
also enable hyperthreading if applicable

**Comment by Leslie-Fang** [comment]
echo with @preethivenkatesh 
@x666633 ```OMP_NUM_THREADS``` and ```intra_op_parallelism_threads``` set at the number of physical cores is one of the BKM.

BTW: What's the build option of ```--copt="-DEIGEN_USE_VML"```
I see a relevant one ```EIGEN_USE_MKL_VML``` which stands for use Intel VML for mkl. 
If we don't add this build option, which default would mkl use? @preethivenkatesh @TensorFlow-MKL

**Comment by preethivenkatesh** [comment]
It’s the same flag in both cases you mentioned. EIGEN_USE_MKL_VML is a macro. It can be used by passing via compiler preprocessing option -DEIGEN_USE_MKL_VML, where –D (stands for define) is compiler flag which says macro should be applied to entire source during compilation. Also, this can be directly defined in a source by using directive #define EIGEN_USE_MKL_VML

**Comment by TensorFlow-MKL** [comment]
@x666633 please close this issue if we have answered your query
