### ISSUE TITLE
Error occurred while compiling TensorFlow for Java 

### ISSUE THREAD

**Issue by mrchor** [tensorflow/tensorflow#29023]
Error occurred while compiling TensorFlow for Java 
Hi guys. Can you help me to see why?
The following is the environment:
GPU: no
Gcc:4.8
TensorFlow: 1.7.1
Bazel: 0.10.0
![image](https://user-images.githubusercontent.com/10007145/58367415-9572a180-7f11-11e9-9c37-f1cb06670748.png)

**Comment by gadagashwini** [comment]
@mrchor Please have look on [Tensorflow for Java](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/java/README.md). Thanks!

**Comment by gadagashwini** [comment]
Closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
