### ISSUE TITLE
LSTM with sample_weight fails with batch_size > 1

### ISSUE THREAD

**Issue by ingo-m** [tensorflow/tensorflow#29026]
**System information**

* Have I written custom code: Yes
* OS Platform and Distribution: Debian 9.9
* TensorFlow installed from: pip
* TensorFlow version: 1.13.1
* Python version: 3.7.3
* GPU model and memory: n/a - tested in CPU mode

**Describe the current behavior**

An unexpected error occurs when training an LSTM with `sample_weight` and `batch_size > 1`. The error does not occur if `batch_size = 1`, or if omitting `sample_weight`.

**Describe the expected behavior**

I would expect to be able to train an LSTM using `sample_weight` and `batch_size > 1`. As far as I understand it, `sample_weight` can be used for weighting the loss function, and according to the [docs](https://www.tensorflow.org/api_docs/python/tf/keras/models/Model) it can be "a flat (1D) Numpy array with the same length as the input samples" - i.e. same length as `batch_size`.

**Code to reproduce the issue**

Here's a minimal example:

```python
import numpy as np
import tensorflow as tf

batch_size = 32
sequence_len = 1
embedding_size = 100

x_train = np.random.randn(batch_size, sequence_len, embedding_size)
y_train = np.random.randn(batch_size, embedding_size)
sample_weight = np.random.randn(batch_size)

train_input = tf.keras.Input(shape=(sequence_len, embedding_size),
                             batch_size=batch_size)

lstm_layer = tf.keras.layers.LSTM(200,
                                  return_sequences=False,
                                  )(train_input)

dense_layer = tf.keras.layers.Dense(embedding_size,
                                    )(lstm_layer)

model = tf.keras.models.Model(inputs=train_input, outputs=dense_layer)

model.summary()

model.compile(optimizer=tf.keras.optimizers.RMSprop(lr=0.001),
              loss=tf.losses.mean_squared_error)

loss = model.train_on_batch(x_train,
                            y=y_train,
                            sample_weight=sample_weight)
```

**Other info / logs**

Traceback:

```
Traceback (most recent call last):
  File "bug_minimal_example.py", line 35, in <module>
    sample_weight=sample_weight)
  File "/home/john/miniconda3/envs/py_main/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py", line 1188, in train_on_batch
    outputs = self.train_function(ins)  # pylint: disable=not-callable
  File "/home/john/miniconda3/envs/py_main/lib/python3.7/site-packages/tensorflow/python/keras/backend.py", line 3076, in __call__
    run_metadata=self.run_metadata)
  File "/home/john/miniconda3/envs/py_main/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1439, in __call__
    run_metadata_ptr)
  File "/home/john/miniconda3/envs/py_main/lib/python3.7/site-packages/tensorflow/python/framework/errors_impl.py", line 528, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: Can not squeeze dim[0], expected a dimension of 1, got 32
	 [[{{node loss/dense_loss/Squeeze}}]]
```

**Comment by gadagashwini** [comment]
I was able reproduce the mentioned issue.

**Comment by qlzh727** [comment]
I don't think this is the issue for LSTM, but more generally for loss and sample weights. Adding @pavithrasv.

**Comment by pavithrasv** [comment]
Tried to reproduce the issue, it repros on nightly but does not repro on 2.0 nightly. Yet to dig into what changed between the versions with regards to this issue.

**Comment by pavithrasv** [comment]
The issue is because you are using `tf.losses.mean_squared_error` with keras. This is not supported in 1.x. TensorFlow losses do not work with Keras in 1.x. You can replace the loss with `tf.keras.losses.mean_squared_error` or simple the string 'mse' and your code should work. 

Please let me know if that fixed the issue for you. Thanks!

**Comment by ingo-m** [comment]
@pavithrasv Great, I agree that this resolves the issue. Thanks a lot!
