### ISSUE TITLE
Tflite Qualcomm DSP acceleration 

### ISSUE THREAD

**Issue by startupgurukul** [tensorflow/tensorflow#29028]
Hello folks, it is exciting to see announcement of qcomm DSP acceleration, aimed to be released late this summer, creating issue to track it. 

![Screenshot_2019-05-25-20-01-49-069_com google android youtube](https://user-images.githubusercontent.com/11027129/58370789-3704ed80-7f28-11e9-8859-9d643a6cb605.png)
![Screenshot_2019-05-25-20-02-11-683_com google android youtube](https://user-images.githubusercontent.com/11027129/58370790-379d8400-7f28-11e9-8619-294e108d4ed1.png)

**Comment by startupgurukul** [comment]
https://github.com/tensorflow/tensorflow/tree/master/tensorflow/contrib/hvx

**Comment by zh794390558** [comment]
@startupgurukul Does tflite support DSP board?

**Comment by startupgurukul** [comment]
Not yet, they are planning to add it by the end of this summer. 

If you are evaluating options, consider mediatek Helios p90,it even beats Snapdragon 855 performance at a cost of  710/730 . According to them, Mlkit supports APU(equivalent of DSP) 

https://www.mediatek.com/blog/googles-ml-kit-arrives-on-the-p90

**Comment by zh794390558** [comment]
@startupgurukul  I mean the DSP  board without cpu on it, just only dsp.

**Comment by startupgurukul** [comment]
I hope so if your DSP supports hexagon SDK from Qualcomm, would rather wait from a tensorflower for a confirmation

**Comment by wangtz** [comment]
@zh794390558 Hi Hui, what kind of DSP are you looking into? If the TFL micro interpreter can be compiled by the DSP compiler and ran on the DSP, then hypothetically the DSP should be able to run TFL micro models.

**Comment by ArtCust** [comment]
I'd like to ask about current third party module [hvx](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/contrib/hvx) will it be working with tflite as of now?

I see that currently hexagon kernel is built only for regular tensorflow (tensorflow/core/kernels/hexagon/BUILD)
If so does it mean that without adding it to tflite we will be unable to benefit from qualcomm addon?

**Comment by DoumanAsh** [comment]
I'd like to ask about current third party module [hvx](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/contrib/hvx) will it be working with tflite as of now?

I see that currently hexagon kernel is built only for regular tensorflow (tensorflow/core/kernels/hexagon/BUILD)
If so does it mean that without adding it to tflite we will be unable to benefit from qualcomm addon?

**Comment by karimnosseir** [comment]
Hexagon Delegate is available now 
See
https://www.tensorflow.org/lite/performance/hexagon_delegate
