### ISSUE TITLE
Where is "tensorflow/lite/delegates/gpu/gl/compiled_model_generated.h"?

### ISSUE THREAD

**Issue by hoonkai** [tensorflow/tensorflow#29031]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): 16.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: n/a
- TensorFlow installed from (source or binary): source
- TensorFlow version: master
- Python version: n/a
- Installed using virtualenv? pip? conda?: n/a
- Bazel version (if compiling from source): n/a
- GCC/Compiler version (if compiling from source): n/a
- CUDA/cuDNN version: n/a
- GPU model and memory: n/a

**Describe the problem**

I'm looking at [serialization.h#L28](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/delegates/gpu/gl/serialization.h#L28) where it includes `tensorflow/lite/delegates/gpu/gl/compiled_model_generated.h`, but where's the file located? Is it meant to be generated at compile time? How is it generated?

Thanks

**Comment by gadagashwini** [comment]
This is not Build/Installation or Bug/Performance issue. Please post this kind of support questions at [StackOverflow](http://stackoverflow.com/questions/tagged//tensorflow). There is a big community to support and learn from your questions. GitHub is mainly for addressing bugs in installation and performance. Thanks!

**Comment by makihiro** [comment]
Hi @hoonkai,
I'm facing the same issue while compiling too.
How have you solved this?

**Comment by mlinxiang** [comment]
me too

**Comment by gadagashwini** [comment]
@makihiro and @mlinxiang, Please post a new issue and provide all the information asked by the [template](https://github.com/tensorflow/tensorflow/issues/new/choose). We ask this because it's more efficient to have one thread dedicated to one issue. Thanks!

**Comment by mlinxiang** [comment]
> @makihiro and @mlinxiang, Please post a new issue and provide all the information asked by the [template](https://github.com/tensorflow/tensorflow/issues/new/choose). We ask this because it's more efficient to have one thread dedicated to one issue. Thanks!

i fixed this, because i compile tflite use tools/make  tool, first i run bazel build --cxxopt=--std=c++11 -c opt --config android_arm64 tensorflow/lite/delegates/gpu:gl_delegate which will convert tensorflow/lite/delegates/gpu/gl/*.fbs file to *.h in the response path of bazel-genfiles, which contain compiled_model_generated.h, then i copy these head files to the original path where *.fbs, and my build task success.

**Comment by makihiro** [comment]
@mlinxiang Thank you. That works fine for me.
