### ISSUE TITLE
CUDA Toolkit 10.1 Update compile tf2.0

### ISSUE THREAD

**Issue by yanhaiming56** [tensorflow/tensorflow#29035]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): source
- TensorFlow version: r2.0
- Python version: 3.7.3
- Installed using virtualenv? pip? conda?: pip
- Bazel version (if compiling from source):0.25.2
- GCC/Compiler version (if compiling from source):gcc
- CUDA/cuDNN version: 10.1 Update
- GPU model and memory: GTX960M 2G

**Describe the problem**

When I get tensorflow source from "git clone https://github.com/tensorflow.git" and "git checkout r2.0",  why do I get that the package is tensorflow 1.13.1 yet, rather than the tensorflow 2.0 after compiling it successfully.

**Comment by gadagashwini** [comment]
@yanhaiming56 Please have a look on this [link](https://www.tensorflow.org/install/source#download_the_tensorflow_source_code). Thanks!

**Comment by lifeishard** [comment]
I have the same problem, even using the master branch with  --config=v2 option

**Comment by gadagashwini** [comment]
@lifeishard  Please post a new issue and provide all the information asked by the template. We ask this because it's more efficient to have one thread dedicated to one issue. Thanks!

**Comment by gadagashwini** [comment]
Closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
