### ISSUE TITLE
eigen/get/a0d250e79c79.tar.gz: Error 404

### ISSUE THREAD

**Issue by hoonkai** [tensorflow/tensorflow#29030]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): 16.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: n/a
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below): master
- Python version: 3.6
- Bazel version (if compiling from source): 0.25
- GCC/Compiler version (if compiling from source): n/a
- CUDA/cuDNN version: n/a
- GPU model and memory: n/a

**Describe the current behavior**

```
$./tensorflow/lite/tools/make/download_dependencies.sh

downloading http://mirror.tensorflow.org/bitbucket.org/eigen/eigen/get/a0d250e79c79.tar.gz
tar: Unrecognized archive format
tar: Error exit delayed from previous errors.
```

Error 404.

Related #28926.

**Comment by yongtang** [comment]
I assume the issue could be fixed with PR #29017

**Comment by muddham** [comment]
@hoonkai Please let us know if this issue is resolved once the PR has been merged

**Comment by achandraa** [comment]
Automatically closing due to lack of recent activity. Please update if this still an issue or new information is  available. Thanks!
