### ISSUE TITLE
one 404 page needs to be fixed

### ISSUE THREAD

**Issue by duanw0916** [tensorflow/tensorflow#29047]
At the beginning of sub title [Train from tf.data datasets](https://www.tensorflow.org/alpha/guide/keras/overview#train_from_tfdata_datasets), there is a super link pointing to **Datasets API**.

But when you click it out, only 404 page is what you get.

Since this API is very often been used, it would be better to correct this as soon as possible.

**Comment by jvishnuvardhan** [comment]
@duanw0916 Thanks for finding this broken link. I am closing this issue as PR related to this issue has been merged to `master` branch. Thanks!
