### ISSUE TITLE
Why are ResNet101/ResNeXt50/ResNeXt101 not included in TensorFlow´s Keras distribution?

### ISSUE THREAD

**Issue by EmielBoss** [tensorflow/tensorflow#29040]
**System information**
- TensorFlow version (you are using): 1.13.1
- Are you willing to contribute it (Yes/No): No

**Describe the feature and the current behavior/state.**
`tf.keras.applications` contains only ResNet50, as browsing to the `site-packages/tensorflow/python/keras/applications` folder shows only `resnet50.py`. Why are ResNet101/ResNeXt50/ResNeXt101 not included? Is there a repo where I can get them from?

**Will this change the current api? How?**
No.

**Who will benefit with this feature?**
Users who wish to use pretrained ResNet101/ResNeXt50/ResNeXt101, which are available in Keras´ stand-alone distribution (if the documentation is right).

**Comment by ymodak** [comment]
[ResNet101](https://www.tensorflow.org/api_docs/python/tf/keras/applications/ResNet101V2), [ResNet50](https://www.tensorflow.org/api_docs/python/tf/keras/applications/ResNet50V2), [ResNet152](https://www.tensorflow.org/api_docs/python/tf/keras/applications/ResNet152V2) have now been added (both V1 and V2 architectures). 
Thanks!

**Comment by samra-irshad** [comment]
ResNeXt architectures are still missing. I need to train ResNeXt-101 for my application and it seems I have to write it from scratch since there's no 'ready-to-import' module in Tensorflow's keras distribution.

**Comment by ymodak** [comment]
You are right. This is a WIP. See https://github.com/tensorflow/tensorflow/pull/37146

**Comment by praveenmec67** [comment]
Is there any update on this issue, as it is difficult to not able to find ResNeXt as part of Tensorflow Keras API.
