### ISSUE TITLE
Not able to install tensorflow alpha on Mac OS

### ISSUE THREAD

**Issue by keahie** [tensorflow/tensorflow#29059]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Mac OS Mojave 10.14.4
- TensorFlow installed from (source or binary): source
- TensorFlow version: 2.0.0 alpha
- Python version: 3.7.3
- Installed using virtualenv? pip? conda?: pip
- CUDA/cuDNN version: none
- GPU model and memory: Intel Iris Graphics 6100 - 1536 MB

**Describe the problem**

I'm not able to install tensorflow with the following command: `pip3 install tensorflow==2.0.0-alpha0`. Every time when I run the command I get the error zsh: 2.0.0-alpha0 not found. I tried different python3 versions, but none of them worked

**Provide the exact sequence of commands / steps that you executed before running into the problem**

Just install python 3.7.3 and run the command `pip3 install tensorflow==2.0.0-alpha0`

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

Error: `zsh: 2.0.0-alpha0 not found`

**Comment by gadagashwini** [comment]
@keahie  Please find instructions in this [link](https://www.tensorflow.org/install/pip) which help you to install Tensorflow. Let us know how it progresses. Thanks!

**Comment by gadagashwini** [comment]
Closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
