### ISSUE TITLE
mobile_ssd_v2_float_coco.tflite model :Cannot copy between a TensorFlowLite tensor with shape [1, 2034, 4] and a Java object with shape [1, 10, 4].

### ISSUE THREAD

**Issue by Gmrevo** [tensorflow/tensorflow#29054]
When using mobile_ssd_v2_float_coco.tflite model with Tensorflow Object Detection [example](https://github.com/tensorflow/examples/tree/master/lite/examples/object_detection/android) code,  I am facing this error:

` Process: org.tensorflow.lite.examples.detection, PID: 30765
    java.lang.IllegalArgumentException: Cannot copy between a TensorFlowLite tensor with shape [1, 2034, 4] and a Java object with shape [1, 10, 4].
        at org.tensorflow.lite.Tensor.throwIfShapeIsIncompatible(Tensor.java:282)
        at org.tensorflow.lite.Tensor.throwIfDataIsIncompatible(Tensor.java:249)
        at org.tensorflow.lite.Tensor.copyTo(Tensor.java:141)
        at org.tensorflow.lite.NativeInterpreterWrapper.run(NativeInterpreterWrapper.java:161)
        at org.tensorflow.lite.Interpreter.runForMultipleInputsOutputs(Interpreter.java:275)
        at org.tensorflow.lite.examples.detection.tflite.TFLiteObjectDetectionAPIModel.recognizeImage(TFLiteObjectDetectionAPIModel.java:220)
        at org.tensorflow.lite.examples.detection.DetectorActivity$2.run(DetectorActivity.java:197)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:214)
        at android.os.HandlerThread.run(HandlerThread.java:65)`

- I did change the
` `private static final int TF_OD_API_INPUT_SIZE = 320;`` 
 - Followed this StackOverflow solution [https://stackoverflow.com/questions/54423649/tensorflow-lite-gpu-support-on-object-detector](url)
This gives only a partial soluton the problem. Can anyone suggest a proper solution.

**Comment by muddham** [comment]
@Gmrevo Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version. Also, did you compile from source or install a binary?

Make sure you also include the exact command if possible to produce the output included in your test case. If you are unclear what to include see the issue template displayed in [the Github new issue template](https://github.com/tensorflow/tensorflow/issues/new/choose).

We ask for this in the issue submission template, because it is really difficult to help without that information. Thanks!

**Comment by Gmrevo** [comment]
@muddham Thanks for the suggestion.
The project  has been compiled in Android Studio using these dependencies:
`dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar','*.aar'])
    implementation 'com.android.support:appcompat-v7:28.0.0'
    implementation 'com.android.support:design:28.0.0'
    implementation 'org.tensorflow:tensorflow-lite:0.0.0-nightly'
    implementation 'org.tensorflow:tensorflow-lite-gpu:0.0.0-nightly'
}
`
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Mobile device : Samsung A7: 
- TensorFlow version: implementation 'org.tensorflow:tensorflow-lite:0.0.0-nightly'
                                   implementation 'org.tensorflow:tensorflow-lite-gpu:0.0.0-nightly'




**Describe the problem**

**Provide the exact sequence of commands / steps that you executed before running into the problem**
When using mobile_ssd_v2_float_coco.tflite model with Tensorflow Object Detection [example](https://github.com/tensorflow/examples/tree/master/lite/examples/object_detection/android) code,  I am facing this error:

` Process: org.tensorflow.lite.examples.detection, PID: 30765
    java.lang.IllegalArgumentException: Cannot copy between a TensorFlowLite tensor with shape [1, 2034, 4] and a Java object with shape [1, 10, 4].
        at org.tensorflow.lite.Tensor.throwIfShapeIsIncompatible(Tensor.java:282)
        at org.tensorflow.lite.Tensor.throwIfDataIsIncompatible(Tensor.java:249)
        at org.tensorflow.lite.Tensor.copyTo(Tensor.java:141)
        at org.tensorflow.lite.NativeInterpreterWrapper.run(NativeInterpreterWrapper.java:161)
        at org.tensorflow.lite.Interpreter.runForMultipleInputsOutputs(Interpreter.java:275)
        at org.tensorflow.lite.examples.detection.tflite.TFLiteObjectDetectionAPIModel.recognizeImage(TFLiteObjectDetectionAPIModel.java:220)
        at org.tensorflow.lite.examples.detection.DetectorActivity$2.run(DetectorActivity.java:197)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:214)
        at android.os.HandlerThread.run(HandlerThread.java:65)`

- I did change the
` `private static final int TF_OD_API_INPUT_SIZE = 320;`` 
 - Followed this StackOverflow solution [https://stackoverflow.com/questions/54423649/tensorflow-lite-gpu-support-on-object-detector](url)
This gives only a partial solution to the problem. Can anyone suggest a proper solution? 

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by jdduke** [comment]
So, these models aren't directly compatible. That is, the model included with the detection sample creates the following output tensors: locations, classes, scores, detections. The `mobile_ssd_v2_float_coco.tflite` model produces a 1x2034x4 encodings output tensor and a 1x2034x91 class predictions tensor. You'll need to modify the logic in TFLiteObjectDetectionAPIModel to handle this altered output format. You can use the [Netron](https://electronjs.org/apps/netron) visualization tool to help identify how the output tensors differ.

**Comment by Gmrevo** [comment]
@jdduke Thanks for the suggestion. Hopefully, this will help to crack down the problem.

**Comment by Gmrevo** [comment]
@jdduke One more query, The official documentation suggests model but after analyzing the Model with Netron, 
`mobile_ssd_v2_float_coco.tflite`
OUTPUT:
raw_outputs/box_encodings
id: raw_outputs/box_encodings
type: float32[1,2034,4]
raw_outputs/class_predictions
id: raw_outputs/class_predictions
type: float32[1,2034,91]

Whereas the default used in the demo has different parameters. How can we use `mobile_ssd_v2_float_coco.tflite` to enable GPU.

**Comment by VirRajpurohit** [comment]
@Gmrevo 
Hi,

Any solution you got for above error. I am stuck in the same from last few days. Can you please assist.

Thanks

**Comment by Gmrevo** [comment]
Hi Vir, 

> @Gmrevo
> Hi,
> 
> Any solution you got for the above error. I am stuck in the same from the last few days. Can you please assist.
> 
> Thanks

Enabling GPU in my project still has been a mystery. I couldn't get the delegate working but you can always look for enabling **NNAPI** at the android side. You can refer to the NNAPI implementation in the class file attached below.
[TFLiteObjectDetectionAPIModel_javaClass.txt](https://github.com/tensorflow/tensorflow/files/3496271/TFLiteObjectDetectionAPIModel_javaClass.txt)

**Comment by VirRajpurohit** [comment]
@Gmrevo 

Hi,

Thanks for your quick reply.
I have replaced the file with yours.

Ended up with the same error as above.

```
java.lang.IllegalArgumentException: Cannot copy between a TensorFlowLite tensor with shape [1, 1917, 4] and a Java object with shape [1, 10, 4].
        at org.tensorflow.lite.Tensor.throwIfShapeIsIncompatible(Tensor.java:282)
        at org.tensorflow.lite.Tensor.throwIfDataIsIncompatible(Tensor.java:249)
        at org.tensorflow.lite.Tensor.copyTo(Tensor.java:141)
        at org.tensorflow.lite.NativeInterpreterWrapper.run(NativeInterpreterWrapper.java:161)
        at org.tensorflow.lite.Interpreter.runForMultipleInputsOutputs(Interpreter.java:275)
        at org.tensorflow.lite.examples.detection.tflite.TFLiteObjectDetectionAPIModel.recognizeImage(TFLiteObjectDetectionAPIModel.java:240)
        at org.tensorflow.lite.examples.detection.DetectorActivity$2.run(DetectorActivity.java:181)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:214)
        at android.os.HandlerThread.run(HandlerThread.java:65)

```

**Comment by jdduke** [comment]
You need to change the shape of the output buffer that you're feeding to the interpreter. The error message is saying that the Java array you've provided doesn't match the shape of the output tensor. In the sample, the number of detections is hardcoded to 10, but it looks like your model is outputting 1917. Might be an issue with how you've converted your model.

**Comment by VirRajpurohit** [comment]
The number of detections is hardcoded to 10, but it looks like your model is outputting 1917-> So hardcoding to 1917 should work? 

Also this 1917 value is coming from model so what changes model needs?

**Comment by Davari393** [comment]
> The number of detections is hardcoded to 10, but it looks like your model is outputting 1917-> So hardcoding to 1917 should work?
> 
> Also this 1917 value is coming from model so what changes model needs?

Hi Vir.
Can you solve the problem?

**Comment by VirRajpurohit** [comment]
@Davari393 

Yes it got resolved.
The change was in the input tensor in tflite model.
Somehow it is dependent on inter compatibility hence, [1,10,4] was the array our android code expects so same array (input tensor whilce creating model) needs to be passed in .tflite file.

**Comment by HaFred** [comment]
> @Davari393
> 
> Yes it got resolved.
> The change was in the input tensor in tflite model.
> Somehow it is dependent on inter compatibility hence, [1,10,4] was the array our android code expects so same array (input tensor whilce creating model) needs to be passed in .tflite file.

Hi Vir, I hardcoded the num_detection into 1917 but it still doesn't work. The .tflite file is compiled using TOCO so I thought it cannot be changed right? May I ask you how you solve this exactly?

**Comment by HaFred** [comment]
I solved the same problem by doing as this https://github.com/tensorflow/tensorflow/issues/22106#issuecomment-428409506

**Comment by Ammu1991** [comment]
> @Davari393
> Yes it got resolved.
> The change was in the input tensor in tflite model.
> Somehow it is dependent on inter compatibility hence, [1,10,4] was the array our android code expects so same array (input tensor while creating model) needs to be passed in .tflite file.

Hello Vir,
I am facing same issue  java.lang.IllegalArgumentException: Cannot copy between a TensorFlowLite tensor with shape [1, 2034, 91] and a Java object with shape [1, 10, 4].

Can you please elaborate what changes you have done it at input side. I am using ssd_mobilenet_v3_small_coco_2019_08_14.


Thanks in advance.

**Comment by Ammu1991** [comment]
> @Davari393
> Yes it got resolved.
> The change was in the input tensor in tflite model.
> Somehow it is dependent on inter compatibility hence, [1,10,4] was the array our android code expects so same array (input tensor whilce creating model) needs to be passed in .tflite file.
> 
> Hi Vir, I hardcoded the num_detection into 1917 but it still doesn't work. The .tflite file is compiled using TOCO so I thought it cannot be changed right? May I ask you how you solve this exactly?

Hello Davari393,
@Davari393 Are you able to solve the issue.

Thanks in advance.

**Comment by SirPhemmiey** [comment]
For anyone who hasn't resolved the issue, this is how i resolved the issue; 

I noticed that the output tensor of the sample detection model is different from the output tensor of my custom model so i tweaked the TFLiteModelObjectDetectionAPIModel.java file by changing the `numBytesPerChannel`, `NUM_DETECTIONS`, variable to match mine. 

PS: IF you don't know your output tensors, you can check it with this wonderful too > https://lutzroeder.github.io/netron/

**Comment by Ammu1991** [comment]
Hello,

I am using ssd_mobilenet_v3_small_coco_2019_08_14 model
Even I am facing same issue. Can you please guide me how to solve this
issue.

 TF_OD_API_INPUT_SIZE=320
 TF_OD_API_IS_QUANTIZED = true
 private static final int NUM_DETECTIONS = 2034;

outputLocations = new float[1][NUM_DETECTIONS][4];
Error:
E/AndroidRuntime: FATAL EXCEPTION: inference
    Process: org.tensorflow.lite.examples.detection, PID: 26039
    java.lang.IllegalArgumentException: Cannot copy between a
TensorFlowLite tensor with shape [1, 2034, 91] and a Java object with shape
[1, 2034, 4].

**Comment by AliceSchaw** [comment]
I got the same issue,  I set num_classes as 5 to train my custom dataset. but I got the error: java.lang.IllegalArgumentException: Cannot copy between a TensorFlowLite tensor with shape [1, 10, 4] and a Java object with shape [1, 5, 4]. Why is the output tensor 10?

label_map.pbtxt
```
item {
  id: 1
  name: 'me'
}

item {
  id: 2
  name: 'teammate'
}

item {
  id: 3
  name: 'enemy'
}

item {
  id: 4
  name: 'enemy_no_threat'
}

item {
  id: 5
  name: 'ignorance'
}
```


ssdlite_mobilenet_v3_small_320x320_coco.config
```
model {
  ssd {
    inplace_batchnorm_update: true
    freeze_batchnorm: false
    num_classes: 5
    box_coder {
      faster_rcnn_box_coder {
        y_scale: 10.0
        x_scale: 10.0
        height_scale: 5.0
        width_scale: 5.0
      }
    }
    matcher {
      argmax_matcher {
        matched_threshold: 0.5
        unmatched_threshold: 0.5
        ignore_thresholds: false
        negatives_lower_than_unmatched: true
        force_match_for_each_row: true
        use_matmul_gather: true
      }
    }
    similarity_calculator {
      iou_similarity {
      }
    }
    encode_background_as_zeros: true
    anchor_generator {
      ssd_anchor_generator {
        num_layers: 6
        min_scale: 0.2
        max_scale: 0.95
        aspect_ratios: 1.0
        aspect_ratios: 2.0
        aspect_ratios: 0.5
        aspect_ratios: 3.0
        aspect_ratios: 0.3333
      }
    }
    image_resizer {
      fixed_shape_resizer {
        height: 320
        width: 320
      }
    }
    box_predictor {
      convolutional_box_predictor {
        min_depth: 0
        max_depth: 0
        num_layers_before_predictor: 0
        use_dropout: false
        dropout_keep_probability: 0.8
        kernel_size: 3
        use_depthwise: true
        box_code_size: 4
        apply_sigmoid_to_scores: false
        class_prediction_bias_init: -4.6
        conv_hyperparams {
          activation: RELU_6,
          regularizer {
            l2_regularizer {
              weight: 0.00004
            }
          }
          initializer {
            random_normal_initializer {
              stddev: 0.03
              mean: 0.0
            }
          }
          batch_norm {
            train: true,
            scale: true,
            center: true,
            decay: 0.97,
            epsilon: 0.001,
          }
        }
      }
    }
    feature_extractor {
      type: 'ssd_mobilenet_v3_small'
      min_depth: 16
      depth_multiplier: 1.0
      use_depthwise: true
      conv_hyperparams {
        activation: RELU_6,
        regularizer {
          l2_regularizer {
            weight: 0.00004
          }
        }
        initializer {
          truncated_normal_initializer {
            stddev: 0.03
            mean: 0.0
          }
        }
        batch_norm {
          train: true,
          scale: true,
          center: true,
          decay: 0.97,
          epsilon: 0.001,
        }
      }
      override_base_feature_extractor_hyperparams: true
    }
    loss {
      classification_loss {
        weighted_sigmoid_focal {
          alpha: 0.75,
          gamma: 2.0
        }
      }
      localization_loss {
        weighted_smooth_l1 {
          delta: 1.0
        }
      }
      classification_weight: 1.0
      localization_weight: 1.0
    }
    normalize_loss_by_num_matches: true
    normalize_loc_loss_by_codesize: true
    post_processing {
      batch_non_max_suppression {
        score_threshold: 1e-8
        iou_threshold: 0.6
        max_detections_per_class: 100
        max_total_detections: 100
        use_static_shapes: true
      }
      score_converter: SIGMOID
    }
  }
}

train_config: {
  batch_size: 512
  sync_replicas: true
  startup_delay_steps: 0
  replicas_to_aggregate: 32
  num_steps: 800000
  data_augmentation_options {
    random_horizontal_flip {
    }
  }
  data_augmentation_options {
    ssd_random_crop {
    }
  }
  optimizer {
    momentum_optimizer: {
      learning_rate: {
        cosine_decay_learning_rate {
          learning_rate_base: 0.4
          total_steps: 800000
          warmup_learning_rate: 0.13333
          warmup_steps: 2000
        }
      }
      momentum_optimizer_value: 0.9
    }
    use_moving_average: false
  }
  max_number_of_boxes: 100
  unpad_groundtruth_tensors: false
}

train_input_reader: {
  tf_record_input_reader {
    input_path: "/home/cy/workspace/ssd/tfdata/sausagetain.record"
  }
  label_map_path: "/home/cy/workspace/ssd/tfdata/sausage_label_map.pbtxt"
}

eval_config: {
  num_examples: 8000
}

eval_input_reader: {
  tf_record_input_reader {
    input_path: "/home/cy/workspace/ssd/tfdata/sausageval.record"
  }
  label_map_path: "/home/cy/workspace/ssd/tfdata/sausage_label_map.pbtxt"
  shuffle: false
  num_readers: 1
}
```

Convert pb to tflite.
```
tensorflow/lite/toco/toco \
--input_file=/Users/cy/PycharmProjects/sausage.pb \
--output_file=/Users/cy/PycharmProjects/detect5.tflite \
--output_format=TFLITE \
--input_arrays=normalized_input_image_tensor \
--input_shapes=1,320,320,3 \
--output_arrays='TFLite_Detection_PostProcess','TFLite_Detection_PostProcess:1','TFLite_Detection_PostProcess:2','TFLite_Detection_PostProcess:3' \
--inference_type=FLOAT \
--mean_values=128 \
--std_values=128 \
--allow_custom_ops \
--change_concat_input_ranges=false 
```

**Comment by shivangipandey06** [comment]
I hard coded the value and changed it to 1917 instead of 10, but again i am getting error as this .Please help.

 java.lang.IllegalArgumentException: Cannot copy between a TensorFlowLite tensor with shape [1, 1917, 2] and a Java object with shape [1, 1917].
        at org.tensorflow.lite.Tensor.throwIfShapeIsIncompatible(Tensor.java:435)
        at org.tensorflow.lite.Tensor.throwIfDataIsIncompatible(Tensor.java:392)
        at org.tensorflow.lite.Tensor.copyTo(Tensor.java:250)
        at org.tensorflow.lite.NativeInterpreterWrapper.run(NativeInterpreterWrapper.java:166)
        at org.tensorflow.lite.Interpreter.runForMultipleInputsOutputs(Interpreter.java:314)
        at org.tensorflow.lite.examples.detection.tflite.TFLiteObjectDetectionAPIModel.recognizeImage(TFLiteObjectDetectionAPIModel.java:231)
        at org.tensorflow.lite.examples.detection.DetectorActivity$2.run(DetectorActivity.java:182)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:201)
        at android.os.HandlerThread.run(HandlerThread.java:65)

**Comment by jdduke** [comment]
It's not clear where the [2] dimension value is coming from, but your output buffer appears to be the wrong shape. @srjoglekar246 can help advise.

**Comment by shivangipandey06** [comment]
This is my model which i trained in that [1,1917,2] scores  , is this and i am unable to make changes accordingly in my android project as its showing error as i mentioned above
[Uploading 
TFLiteObjectDetectionAPIModel_javaClass.txt…]()
![Screenshot (45)](https://user-images.githubusercontent.com/48325131/83105918-2ce87280-a0d9-11ea-866a-02237a100520.png)

**Comment by jdduke** [comment]
You need to change the shape of the output Java array you provide to [1,1917,2].

**Comment by Tezcan98** [comment]
Is there anyone who solve this problem ? I got stuck. I 'm trying to modify .java code but it don't work :|

**Comment by srjoglekar246** [comment]
@Tezcan98 Which model are you using?

**Comment by Tezcan98** [comment]
Im just tryin on ssd_mobilenet_v2_320x320_coco since learn if tflite converter works but I can't get any successful result. 
I will deploy a website can convert from .pb or .h5 to .tflite, this will be a great service.

**Comment by srjoglekar246** [comment]
@Tezcan98 Did you modify the app code to accept 320x320 input? What error are you getting? Is it [this one](https://github.com/tensorflow/tensorflow/issues/29054#issuecomment-634617023)?

**Comment by Tezcan98** [comment]
@srjoglekar246 
My convert operation is this
`
!pip install tf-nightly  # Restart runtime after this line

import tensorflow as tf

model = tf.saved_model.load("ssd_mobilenet_v2_320x320_coco17_tpu-8/saved_model")
concrete_func = model.signatures[tf.saved_model.DEFAULT_SERVING_SIGNATURE_DEF_KEY]
concrete_func.inputs[0].set_shape([1, 320, 320, 3])  
 
tf.saved_model.save(model, "saved_model_updated",signatures=model.signatures[tf.saved_model.DEFAULT_SERVING_SIGNATURE_DEF_KEY])
converter = tf.lite.TFLiteConverter.from_saved_model(saved_model_dir='saved_model_updated',signature_keys=['serving_default'] )

converter.optimizations = [tf.lite.Optimize.DEFAULT]
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS, tf.lite.OpsSet.SELECT_TF_OPS]
tflite_model = converter.convert()
`

If I use converter.optimizations = [tf.lite.Optimize.DEFAULT] line, model converted to quantization so Im getting Cannot copy ... [1,100] to a Java object with shape [1, 10, 4] 
If I comment this line I got [1, 1917, 4] to ... with shape [1, 10, 4] error

Thank you for your interest.

**Comment by srjoglekar246** [comment]
Please follow [these instructions](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/running_on_mobile_tf2.md) for converting SSD models for TFLite.

**Comment by Tezcan98** [comment]
Thanks I'll try it. I hope I can do it :)

**Comment by Tezcan98** [comment]
Thanks, it works. I used colab code they share. this model detect duck and there is 1 class at last layer and different from I've tried so they mean this code is work. Can I write you from mail If I get different issue ?

**Comment by srjoglekar246** [comment]
Feel free to just follow up here, so that its better for me to track :-)

**Comment by tbikash62** [comment]
Hello 

Great comments to read that actually people solved it! 

In my case (Not yet solved)- 

1. TF_OD_API_INPUT_SIZE = 320;  (changed to 320-->It was 300)
2. TF_OD_API_MODEL_FILE = "detect1.tflite";
3. TF_OD_API_LABELS_FILE = "labelmap.txt";

Below is my I/P and O/P tensor for models- 
![image](https://user-images.githubusercontent.com/58831041/137597274-a0a7d180-1f6b-4032-b22d-f93ba1337a87.png)


Getting error as below - 
![image](https://user-images.githubusercontent.com/58831041/137597316-53368dd2-70ce-4f2d-8782-f4724db29cbb.png)

Code part, is the input and output part correct? Please guide me. 
![image](https://user-images.githubusercontent.com/58831041/137597335-ae0cee91-03da-47d9-9dc7-e266ca9a798d.png)

Thank you!

**Comment by srjoglekar246** [comment]
@tbikash62 Did you convert your model recently? I think there were some changes to our converter recently, due to which the order of the outputs might get changed. 

See the 'Test TFLite model' section in [this colab](https://github.com/tensorflow/models/blob/master/research/object_detection/colab_tutorials/eager_few_shot_od_training_tflite.ipynb), where we look at the TFLite model's input & output details (`output_details = interpreter.get_output_details()`). You can `print()` that information in a Python script to check what shapes your model's outputs have. It is likely that the java code you mentioned above assumes an output ordering of tensors which isn't followed by the model, so you will have to change that part of the code.

Don't change the input buffer dimensions, it needs to be 1*inputSize*inputSize*numBytesperchannel*3.

**Comment by tbikash62** [comment]
Hello @srjoglekar246 

Thank you for the guidance. 

Did you convert your model recently?
Yes, on 15th of this month. 

```
Code Snippet used - 
# Load the TFLite model and allocate tensors.
interpreter = tf.lite.Interpreter(model_path=os.path.join(paths['MODEL_PATH'], 'my_ssd_mobnet', 'tfliteexport', 'saved_model', 'detect1.tflite'))
interpreter.allocate_tensors()

input_details = interpreter.get_input_details()
output_details = interpreter.get_output_details()

print(input_details)
print(output_details)

# Test the model on random input data.
input_shape = input_details[0]['shape']
input_data = np.array(np.random.random_sample(input_shape), dtype=np.float32)
interpreter.set_tensor(input_details[0]['index'], input_data)

interpreter.invoke()

# The function `get_tensor()` returns a copy of the tensor data.
# Use `tensor()` in order to get a pointer to the tensor.
output_data = interpreter.get_tensor(output_details[0]['index'])
print(output_data)
```
```

OUTPUT - 

print(input_details)
[{'name': 'serving_default_input:0', 'index': 0, **'shape': array([  1, 320, 320,   3]),** 'shape_signature': array([  1, 320, 320,   3]), 'dtype': <class 'numpy.float32'>, 'quantization': (0.0, 0), 'quantization_parameters': {'scales': array([], dtype=float32), 'zero_points': array([], dtype=int32), 'quantized_dimension': 0}, 'sparsity_parameters': {}}]

print(output_details)
[{'name': 'StatefulPartitionedCall:1', 'index': 335**, '**shape': array([ 1, 10])**, '**shape_signature': array([ 1, 10]), 'dtype': <class 'numpy.float32'>, 'quantization': (0.0, 0), 'quantization_parameters': {'scales': array([], dtype=float32), 'zero_points': array([], dtype=int32), 'quantized_dimension': 0}, 'sparsity_parameters': {}}, {'name': 'StatefulPartitionedCall:3', 'index': 333, 'shape': array([ 1, 10,  4]), 'shape_signature': array([ 1, 10,  4]), 'dtype': <class 'numpy.float32'>, 'quantization': (0.0, 0), 'quantization_parameters': {'scales': array([], dtype=float32), 'zero_points': array([], dtype=int32), 'quantized_dimension': 0}, 'sparsity_parameters': {}}, {'name': 'StatefulPartitionedCall:0', 'index': 336, 'shape': array([1]), 'shape_signature': array([1]), 'dtype': <class 'numpy.float32'>, 'quantization': (0.0, 0), 'quantization_parameters': {'scales': array([], dtype=float32), 'zero_points': array([], dtype=int32), 'quantized_dimension': 0}, 'sparsity_parameters': {}}, {'name': 'StatefulPartitionedCall:2', 'index': 334, 'shape': array([ 1, 10]), 'shape_signature': array([ 1, 10]), 'dtype': <class 'numpy.float32'>, 'quantization': (0.0, 0), 'quantization_parameters': {'scales': array([], dtype=float32), 'zero_points': array([], dtype=int32), 'quantized_dimension': 0}, 'sparsity_parameters': {}}]

print(output_data)
[[0.2532972  0.1299967  0.06841362 0.06171301 0.04120497 0.03646466 0.03233587 0.0318325  0.03004893 0.02726024]]
```

So is it the java code or error in the model itself, I mean do I have to retrain? 

As of now, keeping inputs as it is. (float32 so getting multiplied by 4--> 1*320*320*4)
![image](https://user-images.githubusercontent.com/58831041/137814034-f5f3e41d-026c-43c7-8d81-5a207d8bf671.png)

Exact error line for tensor mismatch is at - 
![image](https://user-images.githubusercontent.com/58831041/137814275-440c0a51-897a-4d2d-a029-b637d9a1a077.png)

**Comment by khizii** [comment]
Hey @tbikash62 i need your help as our problem is same but i can't figure out this problem on my own. i am getting the same error as yours Please help me
My code is below:
![Screenshot 2024-02-16 203916](https://github.com/tensorflow/tensorflow/assets/137616658/f0d94b00-0841-476f-93f3-211117a5664f)
