### ISSUE TITLE
How to avoid asking when executing "python ./configure.py"

### ISSUE THREAD

**Issue by QuellaZhang** [tensorflow/tensorflow#29051]
This is not a truely issue with building or installing TF, but a important question for us.

When we execute "python ./configure.py" it will ask the dependencies, configuration and others, we have to manually confirm. What I should do to have "python ./configure.py" read the default parameters(we use default parameters) directly and don't need us to confirm. Or is there some parameters to avoid these questions?

Because we need to integrate the build steps into a script for daily build testing, every time we run the script it will empty the configuration and get the latest source to rebuild the TF , but "python ./configure.py" will prevent the script from continuing, 

This question is important to us. Can you provide solution to solve this problem? Thanks in advance.

**Comment by gunan** [comment]
We set environment variables to change the defaults o configure script, and then run it with `yes "" | $PYTHON_BIN_PATH configure.py` You can see an example of this here:
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/ci_build/linux/gpu/run_py3_core.sh

**Comment by QuellaZhang** [comment]
Thanks for you information, now Tensorflow can be successfully built with script.
