### ISSUE TITLE
Why has the RNN API changed so drastically?

### ISSUE THREAD

**Issue by ushnish** [tensorflow/tensorflow#2905]
The new 0.9 version has 3 changes which has broken my existing functionality.

1. Have to use tensorflow.python.ops.rnn_cell instead of tensorflow.models.rnn.rnn_cell
2. Have to use cell(inputs, state..) instead of rnn.rnn(cell, inputs, state ...)
3. Initial_state keyword arg has been removed
4. Worst of all, i can't find any mention of variable sequence length in the new version of rnn_cell code

Can someone at least advice on how to use variable sequence lengths in this version? For now I'm reverting back to 0.8 so my code works again

**Comment by martinwicke** [comment]
@ebrevdo is there a conversion howto? That would be helpful.

**Comment by ebrevdo** [comment]
The RNN api wasn't documented until 0.9, so it was liable to change.  Now that it is documented and "officially released", it has the same guarantees as the rest of core.

That said, none of the functionality has changed - it was just moved.

You can use tensorflow.nn.rnn_cell.*, tensorflow.nn.rnn(), tensorflow.nn.dynamic_rnn(), etc.  You do not have to call the cell directly.

initial_state is available to tensorflow.nn.rnn()

@martinwicke for whatever reason, the rnn documentation does not show up [here](https://www.tensorflow.org/versions/r0.9/api_docs/python/index.html).  Do these api docs need to be updated?

**Comment by martinwicke** [comment]
r0.9 docs reflect changes to the docs made before we branched. Are those
changes on the r0.9 branch?

**Comment by ebrevdo** [comment]
The documentation will be fixed by #2933
