### ISSUE TITLE
InvalidArgumentError: Expected image (JPEG, PNG, or GIF), got unknown format starting with 'AAAAAAAAAAAAAAAA' 

### ISSUE THREAD

**Issue by wilk10** [tensorflow/tensorflow#29061]
**System information**
- OS Platform and Distribution: MacOS Sierra 10.12.6
- TensorFlow installed from (source or binary): with pip
- TensorFlow version (use command below): 1.13.1
- Python version: 3.7.0

**Describe the problem**

I'm preparing my trained model (custom Keras) for deploy on Tensorflow Serving so that it receives image bytes and returns a prediction mask. Here's my `signature_def`:
```
signature_def['predict_images']:
  The given SavedModel SignatureDef contains the following input(s):
    inputs['inputs'] tensor_info:
        dtype: DT_STRING
        shape: (-1)
        name: image_bytes:0
  The given SavedModel SignatureDef contains the following output(s):
    outputs['outputs'] tensor_info:
        dtype: DT_FLOAT
        shape: (-1, 256, 256, 1)
        name: conv2d_23/Sigmoid:0
  Method name is: tensorflow/serving/predict
```
My `serving_input_receiver_fn` function is:
```
def process_image(self, image_buffer):
    image = tf.image.decode_jpeg(image_buffer, channels=3)
    image = tf.image.convert_image_dtype(image, dtype=tf.float32)
    image = tf.expand_dims(image, 0)
    image = tf.image.resize_bilinear(image, [256, 256], align_corners=False)
    image = tf.squeeze(image, [0])
    image = tf.cast(image, tf.float32) / 255.0
    return image

def serving_input_receiver_fn(self):
    input_ph = tf.placeholder(dtype=tf.string, shape=[None], name='image_bytes')
    images_tensor = tf.map_fn(self.process_image, input_ph, back_prop=False, dtype=tf.float32)
    return tf.estimator.export.ServingInputReceiver({'input_1': images_tensor}, {'image_bytes': input_ph})
```

When i load my image from S3 with the following code:
```
image = load_image_from_s3('s3://bucket/path/to/image.png')
bytes_image = base64.b64encode(image).decode('utf-8')
with tf.Session(graph=tf.Graph()) as sess:
    model = tf.saved_model.loader.load(sess, ["serve"], 'gs://bucket/saved/model/dir/')
    graph = tf.get_default_graph()
    input_dict, output_dict = _signature_def_to_tensors(model.signature_def['predict_images'])
    predictions = sess.run(output_dict, feed_dict={input_dict['inputs']: [bytes_image]})
```
i get the following error:
```
InvalidArgumentError (see above for traceback): Expected image (JPEG, PNG, or GIF), got unknown format starting with 'AAAAAAAAAAAAAAAA'
```
but if i load the same image from local as follows:
```
image_data = tf.gfile.GFile('/local/path/to/image.png', 'rb').read()
```
and call predictions as:
```
predictions = sess.run(output_dict, feed_dict={input_dict['inputs']: [image_data]})
```
It does work. How can i get it to work with base64 encoding  so that i can then deploy and use it with Tensorflow Serving and my live application?

**Notes**:
This works too:
```
tf.image.decode_jpeg(bytes_image, channels=3)
<tf.Tensor 'DecodeJpeg:0' shape=(?, ?, 3) dtype=uint8>
```
I've already tried a similar versions of this issue [on StackOverflow](https://stackoverflow.com/questions/56275522/tensorflow-serving-how-to-decode-base64-encoded-png-images-during-preprocessing)

Thank you so much for the support! I hope it's a question relevant to this channel

**Comment by achandraa** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged//tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there and can provide better and quick help for such type of issues. Thanks!

**Comment by wilk10** [comment]
Thank you, i was just about to close the ticket. I solved it in a different way using [this](https://github.com/mhwilder/tf-keras-gcloud-deployment/) as an excellent guide
