### ISSUE TITLE
Cmake Project is abandoned?

### ISSUE THREAD

**Issue by engineer1109** [tensorflow/tensorflow#29074]
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows/Ubuntu

- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below): 1.12-1.14
- Python version: 3.5/3.6
- Bazel version (if compiling from source): 0.21-0.253
- GCC/Compiler version (if compiling from source): 
- CUDA/cuDNN version: 10.0 7.5
- GPU model and memory: 11G

I found cmake project from 1.12 is abandoned.
I want to build c++  dll on windows.
The ubuntu so is compiled easily by bazel. Windows is hard.
What should I do?

**Comment by gadagashwini** [comment]
@engineer1109 Unfortunately we don't provide support for the CMake build anymore. You may have more luck building with Bazel for Windows using -c dbg. Please have look on [build tensorflow from source](https://www.tensorflow.org/install/source_windows). Thanks!

**Comment by engineer1109** [comment]
@gadagashwini  Command is bazel build --config=opt --config=cuda --define=no_tensorflow_py_deps=true //tensorflow:tensorflow.dll？

**Comment by engineer1109** [comment]
E:\tensorflow_maskrcnn\.\include\tensorflow/core/platform/default/logging.h(260): error C2589: '(': illegal token on ri
ght side of '::' [E:\tensorflow_maskrcnn\buildvs\main.vcxproj]
E:\tensorflow_maskrcnn\.\include\tensorflow/core/platform/default/logging.h(260): error C2059: syntax error: '::' [E:\t
ensorflow_maskrcnn\buildvs\main.vcxproj]
E:\tensorflow_maskrcnn\.\include\tensorflow/core/platform/default/logging.h(260): error C2143: syntax error: missing ';
' before '{' [E:\tensorflow_maskrcnn\buildvs\main.vcxproj]

See something wrong with 
TF_DEFINE_CHECK_OP_IMPL(Check_EQ,
                        ==)  // Compilation error with CHECK_EQ(NULL, x)?
TF_DEFINE_CHECK_OP_IMPL(Check_NE, !=)  // Use CHECK(x == NULL) instead.
TF_DEFINE_CHECK_OP_IMPL(Check_LE, <=)
TF_DEFINE_CHECK_OP_IMPL(Check_LT, <)
TF_DEFINE_CHECK_OP_IMPL(Check_GE, >=)
TF_DEFINE_CHECK_OP_IMPL(Check_GT, >)

**Comment by engineer1109** [comment]
There are VC complicts.
if (TF_PREDICT_FALSE(v2 >= (std::numeric_limits<int>::max)())) { 
to solve

**Comment by engineer1109** [comment]
c_api.lib(c_api.o) : error LNK2005: TF_GetCode already defined in tensorflow.lib(libtensorflow.so) [E:\tensorflow_maskr
cnn\buildvs\main.vcxproj]
c_api.lib(c_api.o) : error LNK2005: TF_SetConfig already defined in tensorflow.lib(libtensorflow.so) [E:\tensorflow_mas
krcnn\buildvs\main.vcxproj]
c_api.lib(c_api.o) : error LNK2005: TF_SetStatus already defined in tensorflow.lib(libtensorflow.so) [E:\tensorflow_mas
krcnn\buildvs\main.vcxproj]
     Creating library E:/tensorflow_maskrcnn/buildvs/Release/main.lib and object E:/tensorflow_maskrcnn/buildvs/Release
  /main.exp
E:\tensorflow_maskrcnn\buildvs\Release\main.exe : fatal error LNK1169: one or more multiply defined symbols found [E:\t
ensorflow_maskrcnn\buildvs\main.vcxproj]

**Comment by engineer1109** [comment]
All the compiling is ok now.

But run a model meet this problem.
Not found: No session factory registered for the given session options: {target: "" config: } Registered factories are {}.

**Comment by mihaimaruseac** [comment]
See https://github.com/tensorflow/tensorflow/issues/28388#issuecomment-497192950 about the question in title.

Also, some nit: please format code blocks using 3 backticks, to make them easier to read.

**Comment by samhodge** [comment]
@engineer1109 

Have a look at the following example code:
https://github.com/tensorflow/tensorflow/tree/master/tensorflow/tools/benchmark

You should be able to get that running with libnsync.lib a few abeil-cpp libs libprotobuf.lib and the tensorflow.dll

Then you can run basically any model from the one binary, there are heaps of helpful hints about running a model in this file.

**Comment by samhodge** [comment]
@engineer1109 

you will also need this and its header
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/util/reporter.cc

**Comment by engineer1109** [comment]
Sure it is abandoned
