### ISSUE TITLE
Documenting the Ref keyword from operations input/output types

### ISSUE THREAD

**Issue by dorier** [tensorflow/tensorflow#29072]
Thank you for submitting a TensorFlow documentation issue. Per our GitHub
policy, we only address code/doc bugs, performance issues, feature requests, and
build/installation issues on GitHub.

The TensorFlow docs are open source! To get involved, read the documentation
contributor guide: https://www.tensorflow.org/community/contribute/docs

### Clear description

Some operations, like `Assign`, use a `Ref` keyword for their input and/or output. (example: tensorflow/core/ops/state_ops.cc). This keyword is not documented anywhere.

Additionally, I haven't found any way to combine `Ref` with `list` (i.e. make an operation take a list of mutable tensors as input).

**Comment by amahendrakar** [comment]
@dorier,
Please take a look at [this documentation](https://www.tensorflow.org/api_docs/python/tf/Variable#ref) for the `ref()` function and let us know if this is what you're looking for. Thanks!
