### ISSUE TITLE
TensorBoard UI issue with tf.function

### ISSUE THREAD

**Issue by mazy1998** [tensorflow/tensorflow#29076]
The code does not behave like the code in https://www.tensorflow.org/tensorboard/r2/graphs. It is rather a blank you with 3 words.

**Comment by mazy1998** [comment]
<img width="1440" alt="Screen Shot 2019-05-28 at 3 22 20 PM" src="https://user-images.githubusercontent.com/8387388/58471566-9bf55900-815d-11e9-91bd-bd5e1ef8fe85.png">

**Comment by mazy1998** [comment]
I apologize for the inconvenience the problem was with Safari, everything works as expected with google chrome(shocker).

**Comment by achandraa** [comment]
We will be closing the issue since it looks like it is resolved. Please feel free to open new issue in case you have any problem. Thanks!
