### ISSUE TITLE
Cannot install tensorflow via PIP 

### ISSUE THREAD

**Issue by extreme4all** [tensorflow/tensorflow#29096]
so following the tutorial: https://www.tensorflow.org/install/pip?lang=python3 didnt really work..
i even deleted all my previous python versions and got a singe python 3.6.0 64 bit running (all my other where 32 bit)

`python --version` => 3.6.0
`pip --version` =>19.1.1
`virtualenv --version `=>16.6.0

`pip install --upgrade tensorflow`
=>
> Collecting tensorflow
>   ERROR: Could not find a version that satisfies the requirement tensorflow (from versions: none)
> ERROR: No matching distribution found for tensorflow

**Comment by lufol** [comment]
Maybe consider following these instructions for the installation at [stackoverflow](https://stackoverflow.com/a/42596864).

**Comment by extreme4all** [comment]
i have also tried to install via link found on the tensorflow install page, this gave the error wheel not supported.

**Comment by muddham** [comment]
@extreme4all Did you get chance to try the link suggested by @lufol , Please let us know your OS

**Comment by extreme4all** [comment]
> 
> 
> @extreme4all Did you get chance to try the link suggested by @lufol , Please let us know your OS

for some reason the link provided there (python3 -m pip install --upgrade https://storage.googleapis.com/tensorflow/mac/cpu/tensorflow-1.12.0-py3-none-any.whl) works but the windows one on tensorflow forum doesn't 
https://storage.googleapis.com/tensorflow/windows/cpu/tensorflow-1.13.1-cp36-cp36m-win_amd64.whl

**Comment by extreme4all** [comment]
i have tried some extra things:

all of these give the error not a suppported wheel on this platform:

Windows
--
Python 3.5 CPU-only | https://storage.googleapis.com/tensorflow/windows/cpu/tensorflow-1.13.1-cp35-cp35m-win_amd64.whl
Python 3.5 GPU support | https://storage.googleapis.com/tensorflow/windows/gpu/tensorflow_gpu-1.13.1-cp35-cp35m-win_amd64.whl
Python 3.6 CPU-only | https://storage.googleapis.com/tensorflow/windows/cpu/tensorflow-1.13.1-cp36-cp36m-win_amd64.whl
Python 3.6 GPU support | https://storage.googleapis.com/tensorflow/windows/gpu/tensorflow_gpu-1.13.1-cp36-cp36m-win_amd64.whl

this does actualy work but gives error when running code demo.py [from](https://github.com/run-youngjoo/SC-FEGAN) :

macOS (CPU-only)
--
Python 2.7 | https://storage.googleapis.com/tensorflow/mac/cpu/tensorflow-1.13.1-py2-none-any.whl
Python > 3.4 | https://storage.googleapis.com/tensorflow/mac/cpu/tensorflow-1.13.1-py3-none-any.whl

error:
ModuleNotFoundError: No module named '_pywrap_tensorflow_internal'

**Comment by forrestneo** [comment]
I also met this problem。
I have already solved it。
here is my solution：
    install anaconda-64bit（This error will occur in other versions.）
    pip install virtualenv
    activate virtualenv
    pip install tensorflow

**Comment by lufol** [comment]
@extreme4all did @forrestneo 's solution solved your problem?

**Comment by jvishnuvardhan** [comment]
Automatically closing this out since I understand it to be resolved, but please let me know if I'm mistaken.Thanks!

**Comment by cheadevit** [comment]
# pip install tensorflow
ERROR: Could not find a version that satisfies the requirement tensorflow (from versions: none)
ERROR: No matching distribution found for tensorflow

for me, I got an error like this. can you all help?

**Comment by jvishnuvardhan** [comment]
@cheadevit Can you please create a new issue with more details on the commands you used? Thanks!

**Comment by ruze00** [comment]
Downgrade to Python 3.6.7

**Comment by abdelouahab1** [comment]
I solved this issue by simply installing: 

pip install virtualenv
activate virtualenv 
source python 
source activate
pip install tensorflow=="x.x.x" (needed version)
