### ISSUE TITLE
There have no tensorflow/contrib/tpu/ops module in b211c7a commit

### ISSUE THREAD

**Issue by trialzuki** [tensorflow/tensorflow#29092]
Sorry if I'm something miss. It's my first attempt to make an issue.

commit b211c7a

In the :
tensorflow/contrib/cmake/python_modules.txt:
....
tensorflow/contrib/tpu
tensorflow/contrib/tpu/ops   <<< line 435
tensorflow/contrib/tpu/profiler
tensorflow/contrib/tpu/python
...

But this module is not in the directory:
tensorflow/contrib/tpu

**Comment by gadagashwini** [comment]
@trialzuki Could you provide more details about the issue and context?

**Comment by trialzuki** [comment]
> @trialzuki Could you provide more details about the issue and context?

I tried to bild project from commit **b211c7a** (last release at 28 may 2019) with 
- Windows 7
- Visual Studio 2019
- cmake
.. and got build error: 
tensorflow/contrib/cmake/tf_python.cmake:217 module tensorflow/contrib/tpu/ops does not exist. 

then 
checked tensorflow/contrib/cmake/tf_python.cmake .. 
checked tensorflow/contrib/cmake/python_modules.txt ..

and found that in tensorflow/contrib/cmake/python_modules.txt:435 
notes module tensorflow/contrib/tpu/ops, but there no module "ops" in tensorflow/contrib/tpu, only in
tensorflow/contrib/tpu/python

**Comment by ymodak** [comment]
The required directories exist in [r.13 branch](https://github.com/tensorflow/tensorflow/tree/r1.13/tensorflow/contrib/tpu)

**Comment by trialzuki** [comment]
In commit:
-=-=- 
commit a83ccd34e729bb642232e63925e5e95e8cf65c1d
Author: Jonathan Hseu <jhseu@google.com>
Date:   Wed Feb 13 16:58:28 2019 -0800

    Move TPU ops to TF core.

    PiperOrigin-RevId: 233859132
-=-=-

Path tensorflow/contrib/tpu/ops removed. 
I think Jonathan Hseu forgot remove line 217 from tensorflow/contrib/cmake/tf_python.cmake file.

Can I fix it?

**Comment by jhseu** [comment]
Thanks @trialzuki . I just sent out a change to delete that line.

**Comment by jhseu** [comment]
https://github.com/tensorflow/tensorflow/commit/a45d4bd80c3d93466a8daf641fe699c6d00096f2

If that doesn't work for you, feel free to reopen or send a pull request.

**Comment by lytum** [comment]
> [a45d4bd](https://github.com/tensorflow/tensorflow/commit/a45d4bd80c3d93466a8daf641fe699c6d00096f2)
> 
> If that doesn't work for you, feel free to reopen or send a pull request.

Sorry, i still have the problem "CMake Error at tf_python.cmake:217 (message):
  Python module not found: tensorflow/contrib/tpu/ops"

and I download the tensorflow-r1.14 from github

Do you have any suggestion about the error? Many thanks for any information.

**Comment by trialzuki** [comment]
Hi. 
As I can remember I'm already make the same fix it in my local copy. )
