### ISSUE TITLE
Support for special functions

### ISSUE THREAD

**Issue by Bonnevie** [tensorflow/tensorflow#291]
If the intent is for TensorFlow to be a general purpose computational tool for machine learning there should be more support for special functions (i.e. the functions in scipy.special). In particular, functions occurring in probability distributions such as the gamma(ln) are quite central to probabilistic machine learning.

**Comment by girving** [comment]
Thanks, special functions are well worth adding, and we'd welcome contributions in this direction.

**Comment by akuz** [comment]
I was just thinking of implementing some Bayesian learning on TensorFlow and realised that I would need the Gamma and also in particular LogGamma (this is just the log of the gamma function computed directly). These are absolutely essential for many distributions (Beta, Dirichlet). I would love to help to add them, however could you please provide some small guidance on where to start? I see there are many levels of op implementation, description, Python wrapping etc. Thanks

**Comment by akuz** [comment]
Found it: https://www.tensorflow.org/versions/master/how_tos/adding_an_op/index.html

**Comment by vrv** [comment]
@ebrevdo is already half-way to implementing this, I think (I think he added it to Eigen for both CPU and GPU? not sure if it's been upstreamed yet).

**Comment by ebrevdo** [comment]
Yeah; this has been implemented and should make it into the next upstream release.  I've added lgamma to Eigen (both ours & upstream) and added an lgamma unary op.

Digamma should also make its way in, in the next 2 weeks.

**Comment by akuz** [comment]
@ebrevdo is it possible for me to pull the lgamma implementation from your repo? I can't see it in your profile, perhaps it's internal at your company, and I can't just pull changes from it? I really need lgamma soon, can't wait ;)

**Comment by akuz** [comment]
@ebrevdo hi, I saw you implemented erf, erfc, and lgamma in Eigen. Why not also implement tgamma from the same section of <cmath>, just so that all four functions from "Error and gamma functions" section would be available? http://en.cppreference.com/w/cpp/header/cmath

Looking forward for them to become available as TensorFlow operations! Thank you

**Comment by davmre** [comment]
@akuz I've been using a hack where you just define a series expansion within the TF graph. It's not pretty and I don't guarantee accuracy, but if you really can't wait for proper support it might be worth a try:

    def gammaln(x):
        # fast approximate gammaln from paul mineiro
        # http://www.machinedlearnings.com/2011/06/faster-lda.html
        logterm = tf.log (x * (1.0 + x) * (2.0 + x))
        xp3 = 3.0 + x
        return -2.081061466 - x + 0.0833333 / xp3 - logterm + (2.5 + x) * tf.log (xp3)

**Comment by ebrevdo** [comment]
It'll get pushed to the public repo next week.

**Comment by ebrevdo** [comment]
CPU and GPU versions of lgamma, digamma, erf, and erfc are in, igamma/igammac/betainc are coming soon.  Marking as done.

**Comment by dush64** [comment]
Sorry to dig this up again, but are there any plans to incorporate the polygamma function (1) in the near future? Anything using a Dirichlet / Beta prior distribution will utilise the digamma function, for which the gradient is the polygamma.

**Comment by ebrevdo** [comment]
As far as I can tell, the digamma function is only used for entropy and
other log-expectation calculations.  The rest use gamma or log-gamma.

**Comment by dush64** [comment]
That's true - sorry, should have been more specific. The digamma/polygamma come up when computing expectations and KL divergences for dirichlet distributions. Is this general enough to warrant a place in Tensorflow, or should I be independently implementing it (or contributing it)?

**Comment by ebrevdo** [comment]
it is worthwhile to add trigamma or polygamma from cephes.  you will have to add it to Eigen first, and verify CUDA support works.  see bitbucket.org/eigen/eigen/ and specifically my PRs adding lgamma/digamma/igamma/igammac/erf/errfc to that repository.  happy to review your code there.

**Comment by girving** [comment]
However, let's split any new special functions off into a new issue.

**Comment by ebrevdo** [comment]
Agreed; this issue is closed.  First push changes to Eigen and then open an issue to bring tri/polygamma into TensorFlow once that's done.
