### ISSUE TITLE
Tf 2.0 with cuda 10.1 build from source compiles to 1.13 package

### ISSUE THREAD

**Issue by lifeishard** [tensorflow/tensorflow#29102]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution:Linux Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): Source
- TensorFlow version: TF2.0
- Python version: 3.7
- Installed using virtualenv? pip? conda?: conda
- Bazel version (if compiling from source): 0.25.3
- GCC/Compiler version (if compiling from source): 7.4.0
- CUDA/cuDNN version: 10.1
- GPU model and memory: GTX 1060 3GB

**Describe the problem**
I am trying to build tensorflow 2.0 from source with cuda 10.1 . I followed a method used by #28936  but the package I build is always 1.13 even with --config=v2 flag

**Provide the exact sequence of commands / steps that you executed before running into the problem**
conda create -n tf2build pip python=3.7
source activate tf2build
pip install --upgrade --force-reinstall pip setuptools
pip install wheel numpy scipy keras
git clone https://github.com/tensorflow/tensorflow.git --single-branch --branch master
cd tensorflow

./configure
 Use default values except:
 CUDA support: Y

export TMP=/tmp
bazel build -c opt --config=opt --config=v2  \
    --copt=-march=native --cxxopt=-march=native \
    //tensorflow/tools/pip_package:build_pip_package --verbose_failures

./bazel-bin/tensorflow/tools/pip_package/build_pip_package --nightly_flag /tmp/tensorflow_pkg

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

creating the package had the following log:

There are no errors during the compilation process, only warnings

Tue May 28 16:30:14 EDT 2019 : === Preparing sources in dir: /tmp/tmp.C6skAbFOnh
~/tfbuild/tf2build/tensorflow ~/tfbuild/tf2build/tensorflow
~/tfbuild/tf2build/tensorflow
Tue May 28 16:30:32 EDT 2019 : === Building wheel
warning: no files found matching '*.pyd' under directory '*'
warning: no files found matching '*.pd' under directory '*'
warning: no files found matching '*.dylib' under directory '*'
warning: no files found matching '*.dll' under directory '*'
warning: no files found matching '*.lib' under directory '*'
warning: no files found matching '*.csv' under directory '*'
warning: no files found matching '*.h' under directory 'tensorflow/include/tensorflow'
warning: no files found matching '*' under directory 'tensorflow/include/Eigen'
warning: no files found matching '*.h' under directory 'tensorflow/include/google'
warning: no files found matching '*' under directory 'tensorflow/include/third_party'
warning: no files found matching '*' under directory 'tensorflow/include/unsupported'
Tue May 28 16:30:54 EDT 2019 : === Output wheel file is in: /tmp/tensorflow_pkg

**Comment by wdirons** [comment]
From the instructions above, it does appear the final build is 2.0, regardless of what the version says. In several places in master the version number is still listed as 1.13.1 (for example: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/pip_package/setup.py#L50)

If you want to update the version numbers prior to the build, you can run this script prior to running configure
`./tensorflow/tools/ci_build/update_version.py --nightly --version 2.0.0`

**Comment by lifeishard** [comment]
The wheel file it generates is tf_nightly-1.13.1-cp37-cp37m-linux_x86_64.whl
After I install the package, tf.__version__ still shows 1.13

**Comment by muddham** [comment]
@lifeishard Can you please follow the TF installation steps mentioned in this [link](https://www.tensorflow.org/install/source)

**Comment by achandraa** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
