### ISSUE TITLE
Keras Vanilla Installation | RuntimeError: Python version >= 3.5 required

### ISSUE THREAD

**Issue by justinvzyl** [tensorflow/tensorflow#29100]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
[+] No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
[+] Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
[+] NA
- TensorFlow installed from (source or binary):
[+] Binary
- TensorFlow version (use command below):
[+] Tensorflow v1.13.1-0-g6612da8951
- Python version:
[+] Python 3.6.0
- Bazel version (if compiling from source):
[+] NA
- GCC/Compiler version (if compiling from source):
[+] GCC 7.4.0
- CUDA/cuDNN version:
[+] CUDA v9.1.85
- GPU model and memory:
[+] GTX 1050 Mobile 4Gb

**Describe the current behavior**

Installation of Keras from source fails by doing the following.

Running the commands as per the Keras installation instructions in a virtual environment.

sudo python setup.py install
...
File "/tmp/easy_install-vOk903/scipy-1.3.0/setup.py", line 31, in
author_email='francois.chollet@gmail.com',
RuntimeError: Python version >= 3.5 required.

**Describe the expected behavior**

Successful Keras installation.

**Code to reproduce the issue**

[+] conda create -n kerasenv python=3.5.0
[+] conda activate kerasenv
[+] pip install tensorflow
[+] git clone https://github.com/keras-team/keras.git
[+] cd keras
[+] sudo python setup.py install

**Other info / logs**
[+] [errorlog2.txt](https://github.com/tensorflow/tensorflow/files/3230162/errorlog2.txt)

[+] Keras Issue: https://github.com/keras-team/keras/issues/12837

**Comment by justinvzyl** [comment]
Full stack trace: 
[trace.txt](https://github.com/tensorflow/tensorflow/files/3230219/trace.txt)

**Comment by CyberZHG** [comment]
Because `scipy==1.3.0` does not support python 2 anymore. You can install `scipy==1.2.1` before install `Keras`.

**Comment by justinvzyl** [comment]
Thanks for the reply. That fixes the problem. But why does it revert back to python 2 when the environment is set to use python 3.6.0?

**Comment by wdirons** [comment]
My guess is the step `sudo python setup.py install` is using the system python, because the sudo command would not inherit the current users environment. 

What does `sudo python --version` return?  2.7 probably

Do you need the sudo command?

**Comment by justinvzyl** [comment]
> My guess is the step `sudo python setup.py install` is using the system python, because the sudo command would not inherit the current users environment.
> 
> What does `sudo python --version` return? 2.7 probably
> 
> Do you need the sudo command?

Yup, `sudo python --version` returns `Python 2.7.15rc1` ... So there is the problem.

`sudo` is needed I believe to allow the `setup.py` file to have the correct permissions to install all the necessary dependencies. 

Running `python setup.py install` returns `error: [Errno 13] Permission denied`

**Comment by wdirons** [comment]
Can you do `which python`, and then run `sudo <path to python> setup.py install` ?

**Comment by justinvzyl** [comment]
Thanks @wdirons that fixes the issue. Installation completes without any errors. 

Is there any way to fix this issue permanently? ie not have to explicitly specify to use the environment python version? Or is that just how the chips will fall if attempting to install keras from source in a virtualenv?

**Comment by wdirons** [comment]
I ran myself:

[+] conda create -n kerasenv python=3.5.0
[+] conda activate kerasenv
[+] pip install tensorflow
[+] git clone https://github.com/keras-team/keras.git
[+] cd keras
[+] python setup.py install

and didn't have any problems at all.

```
Using /home/irons/anaconda2/envs/kerasenv/lib/python3.5/site-packages
Finished processing dependencies for Keras==2.2.4
```

As conda should be creating a virtual environment in a directory that user has access to, pip or python setup.py install should have access to write to that directory.

**Comment by achandraa** [comment]
@justinvzyl : Can we close the issue since it looks like it is resolved. Thanks!
@wdirons : Thanks for the support.

**Comment by justinvzyl** [comment]
@achandraa Yup will close, thanks for the support @wdirons
