### ISSUE TITLE
Some of the operators in the model are not supported by the standard TensorFlow Lite runtime.

### ISSUE THREAD

**Issue by liuyulin19921213** [tensorflow/tensorflow#29117]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- TensorFlow installed from (source or binary):
- TensorFlow version (or github SHA if from source):

**Provide the text output from tflite_convert**

```
Some of the operators in the model are not supported by the standard TensorFlow Lite runtime. If those are native TensorFlow operators, you might be able to use the extended runtime by passing --enable_select_tf_ops, or by setting target_ops=TFLITE_BUILTINS,SELECT_TF_OPS when calling tf.lite.TFLiteConverter(). Otherwise, if you have a custom implementation for them you can disable this error with --allow_custom_ops, or by setting allow_custom_ops=True when calling tf.lite.TFLiteConverter(). Here is a list of builtin operators you are using: ADD, ADD_N, CAST, CONCATENATION, CONV_2D, FLOOR, FULLY_CONNECTED, GATHER_ND, LOGISTIC, MAXIMUM, MINIMUM, MUL, PACK, RESHAPE, RESIZE_NEAREST_NEIGHBOR, STRIDED_SLICE, SUB. Here is a list of operators for which you will need custom implementations: ROUND.


```

Also, please include a link to a GraphDef or the model if possible.

**Any other info / logs**

Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by lufol** [comment]
For converting a model to `tf.lite`, please have a look at this similar problem #29124.

**Comment by muddham** [comment]
@liuyulin19921213 Did you get chance to try the link suggest by @lufol. Please check and let us know how it progresses. Thanks!

**Comment by liuyulin19921213** [comment]
I tested it 【https://www.tensorflow.org/lite/guide/ops_select 】， but it didn't pass。

**Comment by liuyulin19921213** [comment]
Some of the operators in the model are not supported by the standard TensorFlow Lite runtime and are not recognized by TensorFlow. If you have a custom implementation for them you can disable this error with --allow_custom_ops, or by setting allow_custom_ops=True when calling tf.lite.TFLiteConverter(). Here is a list of builtin operators you are using: ADD, ADD_N, CAST, CONCATENATION, CONV_2D, FLOOR, FULLY_CONNECTED, GATHER_ND, LOGISTIC, MAXIMUM, MINIMUM, MUL, PACK, RESHAPE, RESIZE_NEAREST_NEIGHBOR, STRIDED_SLICE, SUB. Here is a list of operators for which you will need custom implementations: ROUND.

**Comment by liuyulin19921213** [comment]
Only added --allow_custom_ops Can generate **.tflite.
 But it can't be loaded in Android studio demo。

**Comment by lufol** [comment]
Please consider opening a new issue if you have a problem with Android Studio and mark this as closed.

Regards

**Comment by liuyulin19921213** [comment]
In fact, they are a problem, because adding --allow_custom_ops ignores the error and causes an error on andrdoistudio. So you can't add --allow_custom_ops , of course I tried --target_ops=TFLITE_BUILTINS, SELECT_TF_OPS This is not possible. The log information is above.

**Comment by lufol** [comment]
Oh yes, you are right.
Then please consider the example of transforming the `sin` to an tf.lite instance [here](https://www.tensorflow.org/lite/guide/ops_custom)
If that is not an option for you, maybe you can apply the function that is not compatible with tf.lite outside of your graph in order to avoid writing much extra code.

**Comment by jdduke** [comment]
ROUND is now a builtin op, which version of TensorFlow are you using? You should be able to convert/run with the latest nightly.

**Comment by liuyulin19921213** [comment]
Then please consider the example of transforming the sin to an tf.lite instance here. 
The link here can't be opened.
The current version is 1.13.1. I think it should be consistent with the version of the algorithm engineer. Not used 2.0.0.
The version used in android-studio is 0.0.0-nightly(" implementation 'org.tensorflow:tensorflow-lite:0.0.0-nightly'")

**Comment by lufol** [comment]
For me the link works. Here once again https://www.tensorflow.org/lite/guide/ops_custom

**Comment by liuyulin19921213** [comment]
I tried the 2.0. version, the same error, Round 。

**Comment by liuyulin19921213** [comment]
It seems that only try   https://www.tensorflow.org/lite/guide/ops_custom。
But it feels very troublesome.
