### ISSUE TITLE
Support RaggedTensors in sequence feature columns 

### ISSUE THREAD

**Issue by shkarupa-alex** [tensorflow/tensorflow#29115]
**System information**
- TensorFlow version (you are using): 2.0.0-dev20190527
- Are you willing to contribute it (Yes/No): No

**Describe the feature and the current behavior/state.**
Currently `tf.feature_column.sequence_*` columns support only sparse tensor inputs.
It would be great if they will support ragged tensors too. At least thru type checking and `to_sparse` method (but maybe there will be a better performing way).

**Will this change the current api? How?**
No, API won't changes.

**Who will benefit with this feature?**
Developers who work with NLP models where ragged tensors are more natural than Sparse ones.

**Any Other info.**
See `Code to reproduce` and especially comment `This is my wish` from https://github.com/tensorflow/tensorflow/issues/29113

**Comment by kumariko** [comment]
@shkarupa-alex We are checking to see if you still need help on this issue. Could you please check with latest stable version of TF which is `TF2.7` ? please check [link](https://www.tensorflow.org/guide/ragged_tensor) .Thanks!
