### ISSUE TITLE
tensorflow_addons can not be imported

### ISSUE THREAD

**Issue by weiminson** [tensorflow/tensorflow#29111]
Could you plz help to solve this issue?

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution ( Linux Ubuntu 16.04):

- TensorFlow installed from: source
- TensorFlow version: 2.0.0-dev20190528
- Python version: 3.6
- CUDA/cuDNN version: 10
- GPU model and memory: GTX 2080 ti

**Describe the current behavior**

I updated Tensorflow from 2.0 a to 2.0.0-dev20190528 and came up with the error  while importing tensorflow_addons, some object could not be opened by the TF framework:

**Code to reproduce the issue**
import tensorflow_addons as tfa

**Other info / logs**

  File "/mnt/HDD1/kaiyi/Split-UNet/module.py", line 1, in <module>
    import tensorflow_addons as tfa
  File "/home/bmiter/anaconda3/envs/SplitU/lib/python3.6/site-packages/tensorflow_addons/__init__.py", line 75, in <module>
    from tensorflow_addons import image
  File "/home/bmiter/anaconda3/envs/SplitU/lib/python3.6/site-packages/tensorflow_addons/image/__init__.py", line 20, in <module>
    from tensorflow_addons.image.distort_image_ops import adjust_hsv_in_yiq
  File "/home/bmiter/anaconda3/envs/SplitU/lib/python3.6/site-packages/tensorflow_addons/image/distort_image_ops.py", line 24, in <module>
    get_path_to_datafile("custom_ops/image/_distort_image_ops.so"))
  File "/home/bmiter/anaconda3/envs/SplitU/lib/python3.6/site-packages/tensorflow/python/framework/load_library.py", line 61, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename)
tensorflow.python.framework.errors_impl.NotFoundError: libtensorflow_framework.so: cannot open shared object file: No such file or directory

Process finished with exit code 1

**Comment by wesboyt** [comment]
I believe tensorflow-gpu 2.0 nightly is incompatible with the pypi addons distribution, and the addons nightly in pypi is currently broken. So what you need to do is build the addons repo from source by cloning it locally.

**Comment by ymodak** [comment]
Did you install the [tensorflow-addon module](https://github.com/tensorflow/addons#installation) using
```pip install tensorflow-addons```

**Comment by weiminson** [comment]
Yep, exactly dat command

**Comment by wesboyt** [comment]
https://github.com/tensorflow/addons/issues/193

**Comment by weiminson** [comment]
> Did you install the [tensorflow-addon module](https://github.com/tensorflow/addons#installation) using?
> `pip install tensorflow-addons`

Yep, it could work before I update Tensorflow version of my virtual environment.

**Comment by weiminson** [comment]
> [tensorflow/addons#193](https://github.com/tensorflow/addons/issues/193)
> 
> [tensorflow/addons#241](https://github.com/tensorflow/addons/issues/241)

Thanks weboyt, so what I should is to clone the latest version of tensorflow_addons to my local directory and import directly from it? Maybe uninstall tfa first?

**Comment by weiminson** [comment]
> I believe tensorflow-gpu 2.0 nightly is incompatible with the pypi addons distribution, and the addons nightly in pypi is currently broken. So what you need to do is build the addons repo from source by cloning it locally.

Hi weboyt, I tried to update tensorflow_addons with the following [command](https://github.com/tensorflow/tensorflow/issues/29111#issuecomment-497084359):
pip install ./artifacts/tensorflow_addons-0.3.0.dev0-cp27-cp27mu-linux_x86_64.whl
Followed by the Error below:
tensorflow_addons-0.3.0.dev0-cp27-cp27mu-linux_x86_64.whl is not a supported wheel on this platform.

the tensorflow version I am using is '2.0.0-dev20190528'

Could you plz help to explain that?

**Comment by wesboyt** [comment]
Outside of my experience unfortunately. I got it working on a 18.04 laptop but it has bugs, I don't think the nightly/addons is in a release ready state quite yet. Youll have the best luck reverting from 2.0 if you need addons and dont know how to build from source, just use the standard pip install.

**Comment by ymodak** [comment]
@seanpmorgan Can you please take a look? Thanks!

**Comment by seanpmorgan** [comment]
@wesboyt is correct. The PyPi package is built against tf2-alpha and it will break against tf2 nightly. We're aiming to have a tensorflow-addons nightly built in the next week or so... alternatively you can build form source. We also expect a tf2-rc at some point and we'll make sure to package against that ASAP.

My guess from the error you're getting is  that either your python env is not py27 (as that particular whl was built for) or you're not on a linux system. 

Regarding the speed up... GPU kernels have yet to be implemented but they are on the near term roadmap https://github.com/tensorflow/addons/issues/118. The ability to use dynamic kernels was just added. If there are any bugs in the transformer as it exists though please post an issue and we'll get it taken care of.

**Comment by ymodak** [comment]
Closing this issue. Feel free to reopen if still have any further problems. Thanks!

**Comment by weiminson** [comment]
> @wesboyt is correct. The PyPi package is built against tf2-alpha and it will break against tf2 nightly. We're aiming to have a tensorflow-addons nightly built in the next week or so... alternatively you can build form source. We also expect a tf2-rc at some point and we'll make sure to package against that ASAP.
> 
> My guess from the pip error you're getting is that either your python env is not py27 (as that particular whl was built for) or you're not on a linux system.
> 
> Regarding the speed up... GPU kernels have yet to be implemented but they are on the near term roadmap [tensorflow/addons#118](https://github.com/tensorflow/addons/issues/118). The ability to use dynamic kernels was just added. If there are any bugs in the transformer as it exists though please post an issue and we'll get it taken care of.

@seanpmorgan thanks for your explanation. Unfortunately, I had to use the latest version of tensorflow to avoid another bug lol. Will keep trying the latest tensorflow-addons version.

**Comment by seanpmorgan** [comment]
@weiminson Sounds good... be on the lookout for a tf-addons 0.4 release soon following the TF2-release in the coming days. Once we build against that a lot of these mismatch issues should be fixed.

**Comment by wesboyt** [comment]
yea that was my conundrum as well, using the transformer model example required the nightly build because model saving is fried in alpha. Because addons breaks nightly you cannot use nightly either. So realistically you either build from source entirely, or you revert to stable release. So any user without the know how to build from source by themselves is stuck on stable.

**Comment by weiminson** [comment]
> transformer

@wesboyt Your explanation makes sense. Cheers.

**Comment by seanpmorgan** [comment]
Just FYI this was released earlier today. Let us know if you have any issues:
https://github.com/tensorflow/addons/releases/tag/v0.4.0

**Comment by weiminson** [comment]
> Just FYI this was released earlier today. Let us know if you have any issues:
> https://github.com/tensorflow/addons/releases/tag/v0.4.0

Thanks dude, will try.
