### ISSUE TITLE
tf.data.Dataset.from_generator() empties after use even with repeat()

### ISSUE THREAD

**Issue by mr-ubik** [tensorflow/tensorflow#29123]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Arch Linux
- TensorFlow installed from (source or binary): PyPI binary
- TensorFlow version (use command below): 2.0.0-dev20190526
- Python version: 3.7

**Describe the current behavior**

A `tf.data.Dataset` created using `from_generator()` is consumed and not recreated/repeated even when explicitly invoking the `repeat()` method.

**Describe the expected behavior**

If `repeat()` is being invoked, repeat the dataset.

**Code to reproduce the issue**

https://github.com/tensorflow/tensorflow/issues/25254#issuecomment-496828699

**Other info / logs**

The issue is present both when manually iterating over it in a custom training scenario and when using `tf.keras.Model.fit()`.

**Comment by mr-ubik** [comment]
Actually, it was my fault :man_facepalming: I had a generator emptying and not being recreated way way upstream in my pipeline. Sorry :heart:

**Comment by zhenghh04** [comment]
I encountered the same issue. 
I had a python generator: gen
`tf.data.Dataset.from_generator(lambda: gen,  ....) `
It does not support repeat. But if I define a lambda generator outside of tf.data.from_generator(gen_lambda, ...) as follows
```
gen_lambda = lambda: gen
tf.data.Dataset.from_generator(gen_lambda,  ....) solved the issue. 

```
It supports repeat method.
