### ISSUE TITLE
keras lstm cell has no zero state when wrapped with a dropoutwrapper

### ISSUE THREAD

**Issue by alexv1247** [tensorflow/tensorflow#29129]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Microsoft Windows 10
- TensorFlow installed from (source or binary): Anaconda
- TensorFlow version (use command below): tensorflow 1.13.1  gpu_py37h83e5d6a_0
- Python version: 3.7
- CUDA/cuDNN version: 7.3.1
- GPU model and memory: GTX 1060 6gb

This problem is very similar to #25641. But that issue was closed and the problem was found in a future version of tensorflow (2.0.0. alpha). This is why I opened a new issue, becuase the current stable release version has the same error. 

I want to create a RNN layer with stacked lstm cells. The lstm cells are wrapped with the dropoutwrapper. Since I define no initial state, the RNN tries to get the zero state from the lstm cells. There the error occurs, saying that a lstmcell has no attribute zero_state. 
        
        import tensorflow as tf
        with tf.Session() as sess:
        tensor = tf.zeros(shape=(1, 20, 5), dtype=tf.float32)
        inputs = tf.keras.layers.Input(shape=(10, 5), tensor=tensor)
        cell = tf.keras.layers.LSTMCell(10)
        cell = tf.nn.rnn_cell.DropoutWrapper(cell=cell)
        rnn = tf.keras.layers.RNN(cell=cell)(inputs)

Here is the error message:

          File "C:/Users/vaith/PycharmProjects/Bayesian_Neural_Nets/bayesian_lstm_main.py", line 25, in main
           rnn = tf.keras.layers.RNN(cell=cell)(inputs)
           File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\keras\layers \recurrent.py", line 701, in __call__
           return super(RNN, self).__call__(inputs, **kwargs)
           File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\keras\engine\base_layer.py", line 554, in __call__
           outputs = self.call(inputs, *args, **kwargs)
           File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\keras\layers\recurrent.py", line 759, in call
            inputs, initial_state, constants)
           File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\keras\layers\recurrent.py", line 863, in _process_inputs
            initial_state = self.get_initial_state(inputs)
           File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\keras\layers\recurrent.py", line 679, in get_initial_state
            inputs=None, batch_size=batch_size, dtype=dtype)
           File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\ops\rnn_cell_impl.py", line 298, in get_initial_state
            return self.zero_state(batch_size, dtype)
           File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\ops\rnn_cell_impl.py", line 1232, in zero_state
            return self._cell.zero_state(batch_size, dtype)
           AttributeError: 'LSTMCell' object has no attribute 'zero_state'

**Comment by muddham** [comment]
@alexv1247 Able to reproduce the issue on TF 1.13 GPU and TF nightly

**Comment by karmel** [comment]
The Keras cells have a dropout argument that you should use directly, rather than passing through the DropoutWrapper. See, for example, https://github.com/tensorflow/tensorflow/blob/r1.13/tensorflow/python/keras/layers/recurrent.py#L1022 . + @qlzh727 for more guidance.

**Comment by qlzh727** [comment]
The keras RNN cell has default dropout support, which mean user probably should just directly using that. Please see API doc param "dropout" and "recurrent_dropout" for any of the RNN layer and cells. 

DropoutWrapper is used mostly for legacy TF rnn cell, and some custom cells in tf.contrib.

**Comment by alexv1247** [comment]
so will the dropout wrapper work with the cudnnlstm cell from tf contrib?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by qlzh727** [comment]
In TF 2.0, we merge the cudnn implementation into the normal LSTM/GRU keras layer, so you don't have to use the contrib version anymore.
