### ISSUE TITLE
mirror.tensorflow.org has an invalid https cert

### ISSUE THREAD

**Issue by perfinion** [tensorflow/tensorflow#29127]
third_party distfiles that are downloaded from the starlark functions `tf_http_archive` or `third_party_http_archive` currently are mirrored to mirror.tensorflow.org via http. Changing them to https fails with an invalid cert (it currently points to *.storage.googleapis.com) 

For example from `tensorflow/workspace.bzl`:
https://mirror.tensorflow.org/docs.python.org/2.7/_sources/license.rst.txt

The third party archives should be served over https for everyones security, `https://mirror.bazel.build/` used to be over https, so `mirror.tensorflow.org` should too.

**Comment by AlexWick** [comment]
This should be elevated to a webmaster's attn.

**Comment by lamberta** [comment]
Filed an internal ticket to track: b/135291877

**Comment by gunan** [comment]
mirror.tensorflow.org does not really have https set up.
thats why I converted all the mirror.tensorflow.org links to http.

In workspace.bzl case the security is provided by the sha checks we have, so not having ssl does not cause big security issues.

**Comment by gunan** [comment]
@frankchn @mihaimaruseac is this resolved?

**Comment by frankchn** [comment]
Yeah the relevant URLs are updated to https://storage.googleapis.com/mirror.tensorflow.org, which has a correct TLS certificate.
