### ISSUE TITLE
Batch Training for different input sizes

### ISSUE THREAD

**Issue by lufol** [tensorflow/tensorflow#29136]
**System information**
- TensorFlow version (you are using): 2.0
- Are you willing to contribute it (Yes/No): Yes

**Describe the feature and the current behavior/state.**
For fully convolution networks training the network with different inputs sizes in batches is not supported, but could be changed.

**Will this change the current api? How?**
The optitmizers would need to be changed, such that the updates for the convolutional layer are summed for the different inputs.

**Who will benefit with this feature?**
People training fully convolutional networks. Padding of the input data could be completely avoided.

**Comment by lufol** [comment]
@dynamicwebpaige could you please share your ideas on this?

**Comment by lufol** [comment]
Due to very little response I'm closin this. Feel free to write me when this issue is interesting for you.

**Comment by tanzhenyu** [comment]
"Padding from the input data could be completely avoided" -- seems you're trying to have a dynamic shape on image dimension instead of batch dimension?

**Comment by lufol** [comment]
Actually my idea was to have both dynamically. 
As far as I know it is currently not possible to train a network on batches of data of different sizes. E.g. batch: image_1 512x512, image_2 256x256. 
My idea was to make this possible.

**Comment by tanzhenyu** [comment]
1) We do support dynamic batch.
2) That's probably a fundamental change within Tensorflow. I'm not sure we're planning to do that. If you'd like to contribute we'd welcome that.
