### ISSUE TITLE
Mixed precision LossScaleOptimizer doesn't work with Keras

### ISSUE THREAD

**Issue by nsmetanin** [tensorflow/tensorflow#29130]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 16.04
- TensorFlow installed from (source or binary): PyPi
- TensorFlow version (use command below): 1.13.1
- Python version: 3.5.2

**Describe the current behavior**

https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/mixed_precision/python/loss_scale_optimizer.py#L102

tf.contrib.mixed_precision.loss_scale_optimizer.LossScaleOptimizer doesn't implement variables() method (because it doesn't call base class `__init__` nor override it), so it fails when used within Keras model training with the following stack trace on model.fit_generator call:

```
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/keras/engine/training.py", line 1426, in fit_generator
    initial_epoch=initial_epoch)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/keras/engine/training_generator.py", line 164, in model_iteration
    callbacks._call_begin_hook(mode)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/keras/callbacks.py", line 212, in _call_begin_hook
    self.on_train_begin()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/keras/callbacks.py", line 279, in on_train_begin
    callback.on_train_begin(logs)
  File "/usr/local/lib/python3.5/dist-packages/horovod-0.16.0-py3.5-linux-x86_64.egg/horovod/_keras/callbacks.py", line 30, in on_train_begin
    self.backend.get_session().run(bcast_op)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/keras/backend.py", line 482, in get_session
    _initialize_variables(session)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/keras/backend.py", line 749, in _initialize_variables
    variables = _get_variables(get_graph())
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/keras/backend.py", line 743, in _get_variables
    variables.update(opt.optimizer.variables())
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/optimizer.py", line 946, in variables
    optimizer_variables = [v for v in self._non_slot_variables()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/optimizer.py", line 1025, in _non_slot_variables
    return self._non_slot_dict.values()
AttributeError: 'LossScaleOptimizer' object has no attribute '_non_slot_dict'
```

**Describe the expected behavior**

Wrapping the optimizer in a LossScaleOptimizer should work transparently with Keras models, as it implements tf.optimizers.Optimizer base class.

To solve this problem, there's a need to either pass undelying optimizer variables() method (together with passing LossScaleManager variables too) or fill slot- and non-slot variables some other way.

Workaround example:
```
class MyExponentialUpdateLossScaleManager(ExponentialUpdateLossScaleManager):
    def variables(self):
        return [self._loss_scale, self._num_good_steps, self._num_bad_steps]

class MyLossScaleOptimizer(LossScaleOptimizer):
    def variables(self):
        return self._opt.variables() + self._loss_scale_manager.variables()
```

**Code to reproduce the issue**

```
from tensorflow.train import AdamOptimizer 
from tensorflow.contrib.mixed_precision import LossScaleOptimizer, ExponentialUpdateLossScaleManager
...
optimizer = AdamOptimizer()
loss_scale_manager = ExponentialUpdateLossScaleManager(init_loss_scale=2 ** 32, incr_every_n_steps=1000)
optimizer = LossScaleOptimizer(optimizer, loss_scale_manager)
...
model.compile(optimizer=optimizer, ...)
```

Full example
```
import numpy as np
import tensorflow as tf
from tensorflow.train import AdamOptimizer
from tensorflow.contrib.mixed_precision import LossScaleOptimizer, ExponentialUpdateLossScaleManager

input = tf.keras.layers.Input(shape=(16,))
output = tf.keras.layers.Dense(1)(input)
model = tf.keras.models.Model(input, output)

optimizer = AdamOptimizer()
# Works without these two lines below
loss_scale_manager = ExponentialUpdateLossScaleManager(init_loss_scale=2 ** 32, incr_every_n_steps=1000)
optimizer = LossScaleOptimizer(optimizer, loss_scale_manager)

model.compile(optimizer=optimizer, loss='binary_crossentropy')
model.fit(np.zeros((16, 16)), np.zeros((16,)))
```

**Comment by achandraa** [comment]
Thanks for the detailed explanation. Will it be possible to provide a minimal exact full code snippet that can reproduce the issue. It would be easy for us to proceed faster. Thanks!

**Comment by nsmetanin** [comment]
Updated the description above with the full code example, thanks!

**Comment by achandraa** [comment]
Thanks for sharing the information. I have tried on Colab with TensorFlow version 1.13.1 and was able to reproduce the issue.

**Comment by karmel** [comment]
@reedwm -- can you advise on the best combination of APIs to use here?

**Comment by reedwm** [comment]
The contrib LossScaleOptimizer is deprecated. Try using `tf.train.experimental.MixedPrecisionLossScaleOptimizer` instead.

**Comment by hahnjiang** [comment]
> The contrib LossScaleOptimizer is deprecated. Try using `tf.train.experimental.MixedPrecisionLossScaleOptimizer` instead.

The version of this API is tensorflow 1.14, how about tensorflow 1.13.1 ?

**Comment by reedwm** [comment]
Unfortunately, no LossScaleOptimizer can be used in tf.keras with 1.13.1.

**Comment by reedwm** [comment]
Closing this as contrib has been removed in TF 2.
