### ISSUE TITLE
tf.sparse.placeholder with partial defined shape return a SparseTensor with fully undefined shape

### ISSUE THREAD

**Issue by gongliyu** [tensorflow/tensorflow#29134]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): Anaconda
- TensorFlow version (use command below): 1.13
- Python version: 3.7.1
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory: 

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
```python
In [37]: X = tf.sparse.placeholder(tf.float32, (None, 3, 4))

In [38]: X.shape
Out[38]: TensorShape([Dimension(None), Dimension(None), Dimension(None)])
```

**Describe the expected behavior**

I would expect the shape of X to be:
TensorShape([Dimension(None), Dimension(3), Dimension(4)])

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by gongliyu** [comment]
BTW, I found that most of the ops on SparseTensor will return a SparseTensor with shape of all Nones, even if the input is fully defined. However, shape inference is really important if we want to use SparseTensor.

**Comment by gadagashwini** [comment]
I could reproduce the issue with Tensorflow 1.13.1.

**Comment by alextp** [comment]
Currently SparseTensor is not capable of representing partially unknown shapes well. We have three options: either a fully unknown shape, a known rank but all unknown dimensions, or fully known shape.

The reason why this is the case is that the shape of a SparseTensor is represented as a Tensor. So either the tensor is constant, and then we know all dimensions, or it's not, and then we either know its shape (which determines the rank of the sparsetensor) or we do not (which means a sparsetensor with a fully unknown shape).

This is I think an unintended but unavoidable consequence of the existing representation for sparsetensor, so I don't think it's feasible to fix.

**Comment by rmehyde** [comment]
For anyone who comes across this issue there seems to be better support for this in TF 2.3 using the `tf.keras.backend.placeholder` API (not sure if this was true in 2.0 as well).

You can define sparse placeholders with partial shapes:
```python
>>> X = tf.keras.backend.placeholder(shape=(None, 3, 4), dtype=tf.float32, sparse=True)
>>> X.shape
TensorShape([None, 3, 4])
```

And while the following is still true:

> BTW, I found that most of the ops on SparseTensor will return a SparseTensor with shape of all Nones, even if the input is fully defined. However, shape inference is really important if we want to use SparseTensor.

You can get around it by wrapping the outputs in `tf.sparse.reset_shape()` calls, supplying the expected shape as a `Tensor` with `-1` instead of `None` for unknown dimensions.

Hope this helps.
