### ISSUE TITLE
PyCharms can't resolve certain "from" imports

### ISSUE THREAD

**Issue by annarev** [tensorflow/tensorflow#29144]
PyCharms doesn't provide suggestions for some of the TensorFlow imports. For example:

```python
from tensorflow.nn import rnn_cell
from tensorflow.keras import losses
```

In these cases, PyCharms doesn't provide suggestions for `rnn_cell` or `losses` members.

A potential solution for the `rnn_cell` import is to put API tree under root of TensorFlow pip package instead of under `_api/v1` or `_api/v2`. However, this won't fix suggestions for `keras` import since `keras` API is in a different directory and we create an alias for it under `tensorflow`.

This issue is a follow up from https://github.com/tensorflow/tensorflow/issues/26502.

**Comment by ErmiaAzarkhalili** [comment]
Hi,
Could you please let us know when this issue would be resolved as it makes our lives too difficult.
WQe cannot utilize pycharm now to import keras from tensorflow.

**Comment by ErmiaAzarkhalili** [comment]
@mihaimaruseac I think this issue should be reopened again since we have not resolved the issue yet.

**Comment by mihaimaruseac** [comment]
This issue is open

**Comment by Burton2000** [comment]
Still an issue for me using the beta release of tf2. 

Using pycharm 2019.

**Comment by dulm** [comment]
it's to difficult to use tf now with out ide promp.  tf-nightly-2.0-preview           2.0.0.dev20190714

**Comment by mihaimaruseac** [comment]
This should be workable now from 2.0 latest release candidate

**Comment by disembarrasing** [comment]
The code works, at least a simple example from official tf page, but IDE (Pycharm Professional 2019 in my case) still doesn't provide any suggestions except for `tensorflow.estimator`

**Comment by mihaimaruseac** [comment]
That's news. Can you try with https://github.com/tensorflow/tensorflow/issues/26502#issuecomment-537225803?

**Comment by disembarrasing** [comment]
Just checked it, the EAP build works, I do apologise for the confusion

**Comment by Saduf2019** [comment]
@annarev  
Can you please try on latest version and update if the issue persist.
