### ISSUE TITLE
Add implementation of LAYER conv1d_transpose

### ISSUE THREAD

**Issue by marianogabitto** [tensorflow/tensorflow#29157]
Would it be possible that someone implements a conv1d_transpose layer? 

There is a tf.contrib.nn.conv1d_transpose implementation but it has many problems, such as the need for hardcoding batch size. 

**System information**
- TensorFlow version (you are using): 1.3
- Are you willing to contribute it (Yes/No): Yes.

**Will this change the current api? How?**
It will create a new implementation of a layer.

**Who will benefit with this feature?**
Many users, in particular people working on 1d time series, etc.

**Comment by tanzhenyu** [comment]
Fixed. Closing it.
