### ISSUE TITLE
the cloud TPU training is trapped and do nothing 

### ISSUE THREAD

**Issue by MaeThird** [tensorflow/tensorflow#29156]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):Y
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):Linux instance-1 4.9.0-8-amd64 #1 SMP Debian 4.9.130-2 (2018-10-27) x86_64 GNU/Linux
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): pip installed
- TensorFlow version (use command below): 1.13
- Python version: 3.5
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory: NO GPU

**Describe the current behavior** 
training my model on the cloud TPU(3.8) through a VM instance.
The log is:
```
2019-05-30 02:33:14.644845: W tensorflow/core/distributed_runtime/rpc/grpc_session.cc:354] GrpcSession::ListDevices will initialize the session with an empty graph and other defaults because the session has not yet been created.
INFO:tensorflow:Creating heartbeat manager for ['/job:tpu_worker/replica:0/task:0/device:CPU:0']
INFO:tensorflow:Creating heartbeat manager for ['/job:tpu_worker/replica:0/task:0/device:CPU:0']
INFO:tensorflow:Configuring worker heartbeat: shutdown_mode: WAIT_FOR_COORDINATOR

INFO:tensorflow:Configuring worker heartbeat: shutdown_mode: WAIT_FOR_COORDINATOR

INFO:tensorflow:Init TPU system
INFO:tensorflow:Init TPU system
INFO:tensorflow:Initialized TPU in 1 seconds
INFO:tensorflow:Initialized TPU in 1 seconds
INFO:tensorflow:Starting infeed thread controller.
INFO:tensorflow:Starting infeed thread controller.
INFO:tensorflow:Starting outfeed thread controller.
INFO:tensorflow:Starting outfeed thread controller.
INFO:tensorflow:Enqueue next (80) batch(es) of data to infeed.
INFO:tensorflow:Enqueue next (80) batch(es) of data to infeed.
INFO:tensorflow:Dequeue next (80) batch(es) of data from outfeed.
INFO:tensorflow:Dequeue next (80) batch(es) of data from outfeed.

```
It looks like everything is ok.But after a period of waiting,I found there was 
no new checkpoint file wrote out on the bucket.
To my supprise is that **the monitor showing the memory usage of the TPU is about 6G,the cpu usage of the TPU is 0 and the cpu usage of the host VM is 0 too**!
Now that what are you doing my host VM and the costly TPU?
Anyone can help?

**Comment by MaeThird** [comment]
![1944686123](https://user-images.githubusercontent.com/14851411/58646074-36f55b00-8337-11e9-9dfc-948485aa6cba.jpg)
The upper is running on my local PC with a Nvidia GPU card(batch_size:16) and the lower part is the cloud TPU running.
It's really really slow on TPU(more than 10 min,batch_size:4 per shard). It's looks like being trapped...

**Comment by muddham** [comment]
@MaeThird In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thanks!

**Comment by MaeThird** [comment]
after ten hours' torment I create a new node installed with tf-1.14.1.dev and it works as expect now.

**Comment by muddham** [comment]
@MaeThird Glad to hear it worked, hence this issue will be closed
