### ISSUE TITLE
TFLite GPU supported ops not working

### ISSUE THREAD

**Issue by SanthoshRajendiran** [tensorflow/tensorflow#29159]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 16.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: Oneplus3, Poco F1
- TensorFlow installed from (source or binary): Binary
- TensorFlow version (use command below): 1.13
- Python version: 3.6.8
- Bazel version (if compiling from source): NIL
- GCC/Compiler version (if compiling from source): NIL
- CUDA/cuDNN version: NIL
- GPU model and memory: NIL

**Describe the current behavior**
Some of the GPU supported TFLite ops, does not run in GPU properly. On CPU it behaves properly and each time with a different combination even with supported ops, the behavior of the model changes and even not able to benchmark it to find the issues. Moreover, fall back mechanism is also not followed, if it is not running in GPU.

**Describe the expected behavior**
TFLite GPU supported ops, must run in GPU. If there are unsupported ops in the graph for which execution cannot be done, execution must fall back to CPU. 

**Code to reproduce the issue**
We have tried appending some nodes on top of Deeplab gpu converted model. All appended nodes are still supported ops by GPU Delegate. We have attached with this issue, the graph and the error log while trying to benchmark the TFLite model.

**Attachments**

**Error Log**

**Command:**
`adb shell taskset f0 /data/local/tmp/benchmark_model --graph=/data/local/tmp/retest_9_27.tflite --enable_op_profiling=true --use_gpu=true`

**Output**
STARTING!
Min num runs: [50]
Min runs duration (seconds): [1]
Inter-run delay (seconds): [-1]
Num threads: [1]
Benchmark name: []
Output prefix: []
Min warmup runs: [1]
Min warmup runs duration (seconds): [0.5]
Graph: [/data/local/tmp/retest_9_27.tflite]
Input layers: []
Input shapes: []
Use nnapi : [0]
Use legacy nnapi : [0]
Use gpu : [1]
Allow fp16 : [0]
Enable op profiling: [1]
Loaded model /data/local/tmp/retest_9_27.tflite
resolved reporter
INFO: Initialized TensorFlow Lite runtime.
INFO: Created TensorFlow Lite delegate for GPU.
ERROR: TfLiteGpuDelegate Prepare: Dimension can not be reduced to linear.
ERROR: Node number 93 (TfLiteGpuDelegate) failed to prepare.

Failed to apply GPU delegate.
Aborted 

**File to reproduce the issue**
[retest_9_27.tflite.zip](https://github.com/tensorflow/tensorflow/files/3235853/retest_9_27.tflite.zip)

**Comment by impjdi** [comment]
@SanthoshRajendiran 

Thanks for sharing the network.  I don't know which op requires is, but according to your log

> ERROR: TfLiteGpuDelegate Prepare: Dimension can not be reduced to linear.

and the function which emits that error message `Status SetAllDimensions<Linear>(const TfLiteIntArray* dimensions, Linear* shape)` (in `tensorflow/lite/delegates/gpu/common/model_builder.cc`), it looks like you have a tensor that is fed into an op that expects a linear tensor in the shape of `[1, 1, 1, x]` but that is not.  Do you think you can find out who calls this function (which op) and what the actual requested tensor shape is?

**Comment by SanthoshRajendiran** [comment]
It was expecting a linear tensor, and we tried creating a constant in its place hoping that will be straightforward doing our work, as we were expecting some basic mathematical operations..

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this issue, as you are using an older version of tensorflow(1.x) which is officially considered as end of life. We recommend that you upgrade to 2.4 or later version and let us know if the issue still persists in newer versions. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, Please open a new issue for any help you need against 2.x, and we will get you the right help.
