### ISSUE TITLE
Please provide the weight pruned InceptionV3 and MobileNetV1 models

### ISSUE THREAD

**Issue by lee-bin** [tensorflow/tensorflow#29163]
I want to try the compression performance of weight pruning of TensorFlow. Is it OK for you to provide the model after pruning? e.g., the 50% sparsity MobileNetV1?

**Comment by gadagashwini** [comment]
@lee-bin Please have a look on this [link](https://www.tensorflow.org/model_optimization/guide/pruning/pruning_with_keras). Let us know if that helps. Thanks!

**Comment by lee-bin** [comment]
Thanks! I had tried that before, but it's MNIST model, not InceptionV3 and MobileNetV1.
Could you please share the codes or the pruned model for these two models?
I know that you have tested it from [here](https://www.tensorflow.org/model_optimization/guide/pruning#image_classification).
I'm very new to this, any help would be appreciated.

**Comment by gadagashwini** [comment]
@lee-bin This is not Build/Installation or Bug/Performance issue. Please post this kind of support questions at [StackOverflow](http://stackoverflow.com/questions/tagged//tensorflow). There is a big community to support and learn from your questions. GitHub is mainly for addressing bugs in installation and performance. Thanks!

**Comment by lee-bin** [comment]
Thanks! I asked it at https://stackoverflow.com/questions/56470335/is-there-any-keras-code-to-reproduce-the-weight-pruning-of-mobilenet.
