### ISSUE TITLE
Unicode op tests fail on s390x with "Could not create converter for input encoding: SHIFT-JIS" error

### ISSUE THREAD

**Issue by kbhute-ibm** [tensorflow/tensorflow#29165]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04 s390x
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: No
- TensorFlow installed from (source or binary): Source
- TensorFlow version (use command below): v1.131.
- Python version: 2.7.15rc1
- Bazel version (if compiling from source): 0.20.0
- GCC/Compiler version (if compiling from source): gcc 7.4
- CUDA/cuDNN version: NA
- GPU model and memory: NA

**Describe the current behavior**
`python ./tensorflow/python/kernel_tests/unicode_decode_op_test.py` fails with following error:

InvalidArgumentError (see above for traceback): Could not create converter for input encoding: SHIFT-JIS
         [[node UnicodeDecodeWithOffsets/UnicodeDecodeWithOffsets (defined at /usr/local/lib/python2.7/dist-packages/absl/testing/parameterized.py:264) ]]

**Describe the expected behavior**
This should pass like Intel. 

**Code to reproduce the issue**
bazel test -c opt //tensorflow/python/kernel_tests:unicode_decode_op_test OR 
bazel test -c opt //tensorflow/python/kernel_tests:unicode_transcode_op_test

**Other info / logs**
```
> iconv -l | grep -i shift
CSSHIFTJIS//
SHIFT-JIS//
SHIFT_JIS//
SHIFT_JISX0213//
```
Error logs are updated
[unicode_decode_logs.log](https://github.com/tensorflow/tensorflow/files/3237313/unicode_decode_logs.log)

Can anyone please tell us the impact of this failure on functionality? Also does anyone have any clue on this issue? Thanks in advance.

**Comment by muddham** [comment]
@kbhute-ibm This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.If you think we've misinterpreted a bug, please comment again with a clear explanation, as well as all of the information requested in the [issue template](https://github.com/tensorflow/tensorflow/issues/new/choose). Thanks!

**Comment by hamatake** [comment]
TF requires hermetic builds, so the ICU conversion data is embedded in the binary as a byte-array. It currently uses little-endian layout. The TF team doesn't have bandwidth to add big-endian support currently, but a PR would be welcome. The data embedding takes place here: https://github.com/tensorflow/tensorflow/blob/master/third_party/icu/data/BUILD.bazel. 

Byte ordering has come up as an issue w.r.t. saved models as well, and the preference there was to store a single format on disk and byte-swap at runtime if required: https://github.com/tensorflow/tensorflow/issues/16364. The same approach is probably preferred here; at the very least, we should not be statically linking two versions of the same data in the binary.

**Comment by kbhute-ibm** [comment]
@hamatake Thanks for the pointers that gave us direction for further debugging.

**Comment by namrata-ibm** [comment]
@hamatake, I was trying to regenerate the ICU conversion data for big endian. Followed steps mentioned here: https://github.com/tensorflow/tensorflow/blob/v2.0.0/third_party/icu/data/BUILD.bazel

However it seems to regenerate same little endian format data. Are the pre-processing steps different for big endian? Is there some other way to reproduce the conversion data?

**Comment by hamatake** [comment]
icupkg lets you change byte ordering for a given .dat file. See the manpage
for full instructions, but '-tb' creates big-endian ASCII output and '-te'
creates big-endian EBCDIC output.

**Comment by namrata-ibm** [comment]
@hamatake, I followed below steps to recreate the data for big endian system:
1. built and installed ICU v64.2
2. Generated `icudt64b_dat.c` as per steps in https://github.com/tensorflow/tensorflow/blob/master/third_party/icu/data/BUILD.bazel (did not give any Data filter file here)
3. Note, the above build generated `icudt64b.dat` for me( **single letter following the version number in the file name was **b****) so assuming it generated correct format data, I tried using this data file directly in TensorFlow, however test failed with `InvalidArgumentError: Could not create converter for input encoding: shift_jis`
4. Further I tried using `icupkg` to convert the data file using '-tb' as well as '-te' however test still failed. 

Am I missing anything here? Could you please help?

**Comment by hamatake** [comment]
If the data package already has 'b' in the name than it should be
appropriate for big-endian. You shouldn't need icupkg in that case. You are
correct to follow the new (post v64) instructions for building icu data.
Did you modify the filename and symbol names properly when appending
to icudt64b_dat.c (the output of genccode)? Did you gzip/split the .c file
and rename it to match the pattern icu_conversion_data.c.gz.*?

**Comment by namrata-ibm** [comment]
@hamatake, yes, ran steps as listed below in icu4c/source :
```
./runConfigureICU Linux
make clean && make
cd data/out/tmp

genccode icudt64b.dat
echo 'U_CAPI const void * U_EXPORT2 uprv_getICUData_conversion() { return icudt64b_dat.bytes; }' >> icudt64b_dat.c

cp icudt64b_dat.c icu_conversion_data.c
gzip -v icu_conversion_data.c
split --number=10 icu_conversion_data.c.gz icu_conversion_data.c.gz. 
```
This created similar files currently present under data folder. Also tried the same with master which generated icudt66b.dat but that did not work either.

**Comment by hamatake** [comment]
Hmm, that looks correct to me. I don't have a big-endian platform to test
on, unfortunately. Since this is more of an ICU data packaging issue than a
tensorflow-specific issue, I'd recommend icu-support@lists.sourceforge.net.

**Comment by namrata-ibm** [comment]
@hamatake, issue indeed seems to be with data packaging as running CJK related tests in ICU pass on big endian (https://github.com/unicode-org/icu/blob/master/icu4c/source/samples/ucnv/convsamp.cpp#L542)

Had a query about use case related to CJK conversion. How critical is this functionality in TensorFlow and how often will user encounter this?

Thank you for the pointers, Appreciate the help provided!

**Comment by hamatake** [comment]
CJK conversion happens only when the user has CJK input data and they
explicitly ask for it to be decoded. I can't say how often this happens, as
there is little visibility into what data users are loading.

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this issue, as you are using an older version of tensorflow(1.x) which is officially considered as end of life. We recommend that you upgrade to 2.4 or later version and let us know if the issue still persists in newer versions. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, Please open a new issue for any help you need against 2.x, and we will get you the right help.

**Comment by rposts** [comment]
Hi there, problem still exists in TF 2.5.0 on s390x.  Investigation in progress to determine if the root cause of the test case failure is still the same.
