### ISSUE TITLE
Unable to serialize dict that is wrapped around tracking `_DictWrapper`

### ISSUE THREAD

**Issue by hartikainen** [tensorflow/tensorflow#29170]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: n/a
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 1.14.0-rc0
- Python version: 3.7
- Bazel version (if compiling from source): n/a
- GCC/Compiler version (if compiling from source): n/a
- CUDA/cuDNN version: n/a
- GPU model and memory: n/a

**Describe the current behavior**
`dict` objects wrapped around `_DictWrapper` by `AutoTrackable` are not serializable by pickle.

**Describe the expected behavior**
`dict` objects wrapped around `_DictWrapper` by `AutoTrackable` are serializable by pickle.

**Code to reproduce the issue**
```python
import pickle
import tensorflow as tf
from tensorflow.python.training.tracking.tracking import AutoTrackable


class MyTrackable(AutoTrackable):
    def __init__(self):
        self.random_op = {
            'tf.trandom.uniform(())': tf.random.uniform(())
        }


def main():
    my_trackable = MyTrackable()
    value = tf.Session().run(my_trackable.random_op)
    print(type(value))
    pickle.dumps(value)


if __name__ == '__main__':
    main()
```
This fails with the following error:
```
$ python ./dict_wrapper_test.py
<class 'tensorflow.python.training.tracking.data_structures._DictWrapper'>
Traceback (most recent call last):
  File "./tests/dict_wrapper_test.py", line 20, in <module>
    main()
  File "./tests/dict_wrapper_test.py", line 16, in main
    pickle.dumps(value)
NotImplementedError: object proxy must define __reduce_ex__()
```

Not exactly sure if this is a bug or a feature. Should the built-in data structures that are tracked be serializable?

**Comment by allenlavoie** [comment]
Thanks for the report. Just an oversight; should be working now.

**Comment by hartikainen** [comment]
Damn, that was fast! Thanks a lot @allenlavoie!
