### ISSUE TITLE
tf.fill does not have dtype

### ISSUE THREAD

**Issue by Mistobaan** [tensorflow/tensorflow#2917]
[tf.fill](https://www.tensorflow.org/versions/r0.9/api_docs/python/constant_op.html#fill)

Does not provide a dtype keyword like tf.ones, tf.zeros.  Is there a particular reason or is just missing ? You can force it by casting the number but I don't think is clean `tf.fill([10,10], np.int16(8))`.

EDIT: seems also tf.linspace and tf.range

**Comment by prb12** [comment]
@rmlarsen Could you take a quick look pls?

**Comment by rmlarsen** [comment]
Sorry for missing this one. I don't think this is a good change. By leaving the explicit casting outside the op, the user is unable to provide a value that is not  in the range of the desired type, and therefore less likely to be surprised by getting back a tensor with a different value than the one they specified.

**Comment by aselle** [comment]
Automatically closing due to lack of recent activity. Please reopen when further information becomes available.

**Comment by aselle** [comment]
Automatically closing due to lack of recent activity. Please reopen when further information becomes available.
