### ISSUE TITLE
Test cases for GPU delegate GL ops

### ISSUE THREAD

**Issue by mun3** [tensorflow/tensorflow#29183]
**System information**
- TensorFlow version (you are using): 0.0.1-gpu
- Are you willing to contribute it (Yes/No): Yes

**Describe the feature and the current behavior/state.**

I was going through the GL ops and noticed that test cases are available for just 3 ops (`add`, `elementwise` and `relu`). Will test cases be available for ops like `reshape`?

**Will this change the current api? How?**
No

**Who will benefit with this feature?**
Anyone trying to debug GPU delegate ops.

**Comment by impjdi** [comment]
@mun3 

Great time to ask.  Yes, we are in the process of moving our unit tests from Google-internal location to TF repository.  You will see more in coming weeks.  Well, there's CVPR conference in the middle, but at least by end of June, you should see unit test for all ops.
