### ISSUE TITLE
When building quantize_graph in r1.14 with mkl, it shows "nothing to build"

### ISSUE THREAD

**Issue by lihaofd** [tensorflow/tensorflow#29194]
**System information**
- OS Platform and Distribution (CentOS 7):
- TensorFlow installed from (source or binary): https://github.com/tensorflow/tensorflow.git
- TensorFlow version: r1.14
- Python version: 3.6
- Installed using virtualenv? pip? conda?: Build from source
bazel build --config=mkl --copt="-DEIGEN_USE_VML" -s -c opt //tensorflow/tools/pip_package:build_pip_package can work
- Bazel version (if compiling from source): 0.24.1
- GCC/Compiler version (if compiling from source): 6.3

**Describe the problem**
Trying
bazel build --config=mkl --copt="-DEIGEN_USE_VML" -c opt tensorflow/contrib/quantize:quantize_graph

It shows
Target //tensorflow/contrib/quantize:quantize_graph up-to-date (nothing to build)
I can't find quantize_graph binary after built.

**Comment by agramesh1** [comment]
@lihaofd  You can get it from the Intel AI tools here https://github.com/IntelAI/tools/tree/master/tensorflow_quantization .  Pinging @TensorFlow-MKL for support.

**Comment by preethivenkatesh** [comment]
@lihaofd Please let us know if you were able to successfully build quantization tool based on the early comment

**Comment by lihaofd** [comment]
it works for me, thanks!

**Comment by lihaofd** [comment]
it works for me, thanks!
