### ISSUE TITLE
[2.0] SparseTensor shape becomes none after AutoGraph

### ISSUE THREAD

**Issue by llan-ml** [tensorflow/tensorflow#29198]
The bug is found with `tf-nightly-gpu-2.0-preview (2.0.0.dev20190530)`.

To reproduce:

<pre>
import tensorflow as tf

x = tf.sparse.SparseTensor(indices=[[0, 0], [1, 2]], values=[1, 2], dense_shape=[3, 4])

def foo(q):
  print(q.shape)

foo(x)                              # Output: (3,4)
tf.function(foo)(x)                 # Output: (None, None)
</pre>

The version `2.0.0alpha0` does not have this bug.

**Comment by muddham** [comment]
@llan-ml Able to reproduce the issue in tf-nightly-gpu-2.0-preview (2.0.0.dev20190530) and (2.0.0.dev20190603) .

**Comment by alextp** [comment]
@edloper I think this is related to the recent composite tensor destructuring in tf.function and not so much related to autograph.

Does that make sense to you? If so, what do you think we should do here?

**Comment by edloper** [comment]
Prior to PR d2502f0, tf.function treated SparseTensor as opaque Python objects, and would retrace the function unless the *same* SparseTensor (the identical object) was passed in.  E.g.:

```
>>> a = tf.sparse.SparseTensor(indices=[[0, 0], [1, 2]], values=[1, 2], dense_shape=[3, 4])
>>> b = tf.sparse.SparseTensor(indices=[[0, 0], [1, 2]], values=[1, 2], dense_shape=[3, 4])
>>> c = tf.sparse.SparseTensor(indices=[[0, 0], [1, 2]], values=[1, 2], dense_shape=[3, 4])
>>> @tf.function
... def foo(q):
...   print('tracing for', q.shape)

# OLD BEHAVIOR (prior to PR d2502f0)
>>> foo(a), foo(b), foo(c)  # retraces each time it's called.
tracing for (3, 4)
tracing for (3, 4)
tracing for (3, 4)
```

PR d2502f0 updated `tf.function` to understand the structure of SparseTensor and related types (like RaggedTensor), and to not retrace the function when different SparseTensors are passed in.

```
# NEW BEHAVIOR (after PR d2502f0)
>>> foo(a), foo(b), foo(c)  # note: only traced one time.
tracing for (?, ?)
```

This impacts `SparseTensor`, because the values of tensors (including `SparseTensor.dense_shape`) are not available inside the body of the traced function.  E.g.:

```
>>> t = tf.constant([1, 2, 3])
>>> def foo(t):
...   print tf.get_static_value(t)
>>> foo(t)
[1, 2, 3]
>>> tf.function(foo)(t)
None
```

In the case of SparseTensor, the shape is stored in a tensor (namely `SparseTensor.dense_shape`, so the value isn't available inside the function body.  (The SparseTensor.shape property effectively just returns `tf.get_static_value(self.dense_shape)`).

If you need the sparse tensor shape inside your function, and don't mind retracing for each different shape that you're called with, a workaround might be to do something like this:

```
def foo(x):
  return _foo(x, x.shape)

@tf.function
def _foo(x, x_shape):
  ...function body...
```

**Comment by llan-ml** [comment]
@edloper Thanks for you explanation. 

In my case, I need to write a custom dense layer to support sparse inputs. The keras `Layer.__call__` will automatically defer the shape of inputs to build variables. However, the deferred shapes are always `None` for SparseTensors, and it will raise errors since the shape of variables being built cannot be determined.

If I remember correctly, keras just uses `inputs` to defer input shapes, and explicitly passing a shape array seems not to solve the problem.

**Comment by Saduf2019** [comment]
@llan-ml 
please let us know if the issue still persist

**Comment by llan-ml** [comment]
@Saduf2019 Yes. If we use a sparse tensor as an argument of `tf.function`, each dimension of the shape of that sparse tensor inside the function is always None.

**Comment by ravikyram** [comment]
I could reproduce the issue with TF 2.2-rc4.Please, find the gist [here](https://colab.sandbox.google.com/gist/ravikyram/ab5b196622f4ef300470e641e974b340/untitled861.ipynb).Thanks!

**Comment by ravikyram** [comment]
I could reproduce the issue with TF 2.2,2.3-rc1, nightly versions(`2.4.0-dev20200715`) .Please, find the gist [here](https://colab.research.google.com/gist/ravikyram/27c8ebcf4760f0e07c6ad574346fb42f/untitled131.ipynb).Thanks!

**Comment by Saduf2019** [comment]
I could reproduce the issue with TF 2.5 .Please, find the gist [here](https://colab.research.google.com/gist/Saduf2019/e19bf295505b2f4c6af8c41fa345f995/untitled589.ipynb).Thanks!

**Comment by kumariko** [comment]
I could reproduce the issue with TF 2.6 .Please, find the gist [**`here`**](https://colab.research.google.com/gist/kumariko/66c89f1252dabfbb95f65d0fe0f2c9f4/untitled589.ipynb#scrollTo=grgBDlrgCxqN).Thanks!

**Comment by sushreebarsa** [comment]
@llan-ml This issue is not replicating in TF v2.7.0 on colab . Could you please have a look at the [gist](https://colab.research.google.com/gist/sushreebarsa/c44b219aafee43af566a6ccaf9b17061/gist29198.ipynb) and let us know if it helps? Thank you!

**Comment by llan-ml** [comment]
@sushreebarsa The issue still persists. You should use `tf.function(foo)(x)` instead of `tf.function(foo(x))`.

**Comment by mohantym** [comment]
I could replicate this issue in 2.8, 2.9 and nightly but was getting a different result when I used tf.shape(q) instead of  q.shape. 
Attached[ gist](https://colab.sandbox.google.com/gist/mohantym/05441f9a8d07e06d17a7752fbdfedcdc/git_29198.ipynb#scrollTo=maKEhgFf0zVG) for reference.

**Comment by pjpratik** [comment]
I was able to reproduce this issue in TF Nightly 2.12.0.dev20221215. Please find the gist [here](https://colab.sandbox.google.com/gist/pjpratik/6b064c18984359f464d229302191ab97/29198.ipynb). Thank you.

**Comment by tilakrayal** [comment]
@llan-ml,
I tried to execute the code on tf-nightly v2.13.0-dev20230420, and the code was executed without any issue/error & also the output was also as expected. Kindly find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/b4193dab0eb933bf89f1cf84de52abf0/untitled.ipynb). Thank you!

![Screenshot 2023-04-20 10 00 37 PM](https://user-images.githubusercontent.com/81610181/233430035-f81d697c-8ef0-42f2-a624-c5e3162e1fca.png)
