### ISSUE TITLE
tf.function spuriously fails for branched super() calls

### ISSUE THREAD

**Issue by ethereon** [tensorflow/tensorflow#29191]
`tf.function` fails spuriously under Python 3.7.3 for the following example:

```python
import tensorflow as tf

class Base(tf.Module):
    def __call__(self, x):
        return x + 1.

class Sub(Base):
    def __call__(self, x):
        return super().__call__(x) if True else 1.

@tf.function
def test():
    return Sub()(tf.constant(42.))

print(test())

```

(Colab: https://colab.research.google.com/drive/1_pS1K0biwse1oTIuuEv0lZYavbE61HAP)

This produces the following error:
```python
RuntimeError: in converted code:

    bug.py:16 test  *
        return Sub()(tf.constant(42.))
    bug.py:12 __call__  *
        return super().__call__(x) if True else 1.

    RuntimeError: super(): no arguments
```

**Observations**

- Everything works correctly without the `tf.function` decoration
- The branch in `__call__` seems necessary to trigger the bug. Skipping the branch doesn't trigger it. Replacing `True` with `False` doesn't trigger it.
- The bug can be triggered even if the condition evaluates to False (for example, replacing `True` with `x < 0` for `x=42`)
- Replacing `tf.constant(42.)` with `42.` doesn't trigger the bug

Tested on TensorFlow 2.0 nightly `2.0.0-dev20190529` on Ubuntu `16.04` with Python `3.7.3`

**Comment by zakizhou** [comment]
change
```
return super().__call__(x) if True else 1.
```
to
```
return super(Sub, self).__call__(x) if True else 1.
```
there will be no errors

**Comment by ethereon** [comment]
@zakizhou Sure, but the point is that `super()` without any arguments is [perfectly valid in Python 3](https://www.python.org/dev/peps/pep-3135/) and as such, this should not result in a failure. Furthermore, the sensitivity to the conditional hints at further issues in `tf.function`

**Comment by gadagashwini** [comment]
I am able to reproduce the issue with Tensorflow  nightly 2.0.0-dev20190529. Thanks!

**Comment by mdanatg** [comment]
I believe this is related to #26029 - the Python3-style super() is indeed not handled correctly yet; we're working to fix that.

It's indeed strange that the issue doesn't replicate reliably - I'll have a closer look.

**Comment by ethereon** [comment]
@mdanatg: this continues to be an issue even with the recent attempt at supporting argument-less super.

In the new [super_in_original_context](https://github.com/tensorflow/tensorflow/blob/612ceb6c488e228fa5246d2452799cf2691ef5f1/tensorflow/python/autograph/operators/py_builtins.py#L92-L130) implementation, the technique used for getting `self` seems a bit fragile. In particular, existence of conditionals (and, presumably, other scoping constructs) around the `super` call causes it to break in various ways.

I've included a couple of samples in [this colab notebook](https://colab.research.google.com/drive/1aoqSo9StvVHDPHhH7Ao4WYm_t6UycnWd)

**Comment by mdanatg** [comment]
@ethereon Thank you for follow-up and the samples! Indeed, our current resolution for handling `super()` is not yet complete, and will only work if the call is in a method (or outside control flow, as you pointed out).
@kkimdev has been working on addressing this. We intentionally oversimplified the solution to assume the original caller of `super()` is exactly one frame up the call stack in the converted code, and we're working on a follow-up improvement that removes that incorrect assumption and instead walks the call stack to find the caller, which can be any number of levels above. We hope to have this ready shortly, and will ping this thread when ready.

In the mean time, the following should be a reliable wokraround:

```
base_self = super()
return base_self.__call__(x) if True else 1
```
```
base_self = super()
if True:
  return base_self.__call__(x)
return 1
```
```
base_self = super()
def local_nested_function():
  return base_self.__call__(x)
return local_nested_function()
```

Again, all these workarounds should hopefully not be needed soon.

**Comment by mdanatg** [comment]
This should not be more robustly handled with the commit that will land soon. If you have a chance to give it a try, I'd love to know if we missed any corner case.
