### ISSUE TITLE
Rank of Tensors

### ISSUE THREAD

**Issue by gigigi743** [tensorflow/tensorflow#292]
I think that there is an error in the description of the rank of the tensors.
In the example the tensor has  rank 3 i think but you wrote that it has rank 2. 

http://tensorflow.org/resources/dims_types.html

"
Rank

In the TensorFlow system, tensors are described by a unit of dimensionality known as rank. Tensor rank is not the same as matrix rank. Tensor rank (sometimes referred to as order or degree or n-dimension) is the number of dimensions of the tensor. For example, the following tensor (defined as a Python list) has a rank of -------2-------------:

t = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

A rank two tensor is what we typically think of as a matrix, a rank one tensor is a vector. For a rank two tensor you can acccess any element with the syntax t[i, j]. For a rank three tensor you would need to address an element with 't[i, j, k]'.
"
let me know .
Thanks
gg

**Comment by matheusportela** [comment]
It seems correct to me. A tensor rank refers to the number of dimensions, not the size of its elements. Therefore, a vector has rank 1, a matrix has rank 2, a cube has rank 3, and so on.

This is exemplified in the following sentence `A rank two tensor is what we typically think of as a matrix, a rank one tensor is a vector` and in the table below extracted from http://tensorflow.org/resources/dims_types.html.

<img width="812" alt="screen shot 2015-11-19 at 9 15 04 am" src="https://cloud.githubusercontent.com/assets/2743105/11269428/0c63a4a0-8e9e-11e5-90dd-2f536260739f.png">

**Comment by girving** [comment]
Yes, that tensor has rank 2, since it's a 2-dimensional array (list of lists).
