### ISSUE TITLE
how to use interactive_graphviz for xla?

### ISSUE THREAD

**Issue by jackalcooper** [tensorflow/tensorflow#29203]
in [xla doc](https://www.tensorflow.org/xla/jit#tutorial) it suggest that 

> /tmp/foo will contain the HLO before and after optimizations for each HLO module that's run. You can read this as-is, or you can visualize it using tensorflow/compiler/xla/tools:interactive_graphviz.

but I cannot locate this binary.

**Comment by gadagashwini** [comment]
@jackalcooper Can you provide more details about the issue?

**Comment by jackalcooper** [comment]
@gadagashwini in the TensorFlow 1.14 release note, it mentioned that:

> XLA
XLA HLO graphs can be inspected with interactive_graphviz tool now.

but I couldn't find how to use it.

**Comment by jvishnuvardhan** [comment]
This is not Build/Installation or Bug/Performance issue. Please post this kind of support questions at [Stackoverflow](https://stackoverflow.com/questions/tagged/tensorflow). There is a big community to support and learn from your questions. GitHub is mainly for addressing bugs in installation and performance. Thanks!
