### ISSUE TITLE
[TF 2.0 API Docs] tf.queue.FIFOQueue

### ISSUE THREAD

**Issue by HardPlant** [tensorflow/tensorflow#29212]
## URL(s) with the issue:
https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/queue/FIFOQueue

## Description of issue (what needs changing):

Some methods not provides raising error lists

### Raises listed and defined

* dequeue
* dequeue_many
* dequeue_up_to
* enqueue
* enqueue_many

### Submit a pull request?
I will

Are you planning to also submit a pull request to fix the issue? See the docs
contributor guide: https://www.tensorflow.org/community/contribute/docs and the
docs style guide: https://www.tensorflow.org/community/contribute/docs_style

**Comment by jvishnuvardhan** [comment]
@HardPlant This is a stale issue. Is there any actionable item like raising PR? 

If you plan to raise a PR, please feel free to use updated version https://www.tensorflow.org/api_docs/python/tf/queue/FIFOQueue

Thanks for your contribution.
