### ISSUE TITLE
Build failure with upcoming Python toolchain change in Bazel 0.27

### ISSUE THREAD

**Issue by brandjon** [tensorflow/tensorflow#29220]
Bazel 0.27 will flip [`--incompatible_use_python_toolchains`](https://github.com/bazelbuild/bazel/issues/7899). A [downstream presubmit](https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/1008#0016c105-4c66-4506-83fd-72ee26749782) shows Tensorflow failing for this change.

One of the side-effects of the flag is that it causes Bazel to actually run Python targets with the interpreter selected by Bazel at analysis time, rather than whatever the system `python` command happens to be. It's likely you have targets that should be Python 2, and were previously running as Python 2, that are now running as Python 3 due to this bug fix. (Note that as of Bazel 0.25, `python_version` defaults to PY3 if not given.)

For each Python 2 `py_binary` / `py_test` target (or macros creating such targets), add the attribute `python_version = "PY2"`. If you have any PY2 targets built in the host configuration, you must add `--host_force_python=PY2` to your bazelrc.

Looking at the failures, I see for instance [`tf_python_api_gen_v1`](https://github.com/tensorflow/tensorflow/blob/50883f7ca9b98e30d303dad5d20b76e05a947f36/tensorflow/BUILD#L774), generated by `gen_api_init_files`, which [creates](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/tools/api/generator/api_gen.bzl#L66-L76) a `py_binary` with no `python_version` attribute.

See the flag's tracking issue (above) for more details.

**Comment by brandjon** [comment]
Bazel at head now emits [helpful warning messages](https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/1017#8f969893-683c-4c1a-b71e-fddc82257ed8/265-628) when a host-configured tool may be failing due to having the wrong Python version. But all such host target failures can be fixed at once by setting `--host_force_python=PY2`.

**Comment by brandjon** [comment]
> Looking at the failures, I see for instance [`tf_python_api_gen_v1`](https://github.com/tensorflow/tensorflow/blob/50883f7ca9b98e30d303dad5d20b76e05a947f36/tensorflow/BUILD#L774), generated by `gen_api_init_files`, which [creates](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/tools/api/generator/api_gen.bzl#L66-L76) a `py_binary` with no `python_version` attribute.

FTR, while `python_version` ought to be set for clarity's sake, it won't help since this is a host-configured tool. Only `--host_force_python` can affect its version. You should still set the attribute for documentation purposes and because eventually it'll have an effect once the host config is eliminated from Bazel.

**Comment by brandjon** [comment]
It's a bit painful to reproduce the build locally. At the same time, TF is disabled in CI right now, waiting on protocolbuffers/protobuf#6207. So I don't think I'm in a position to confirm that setting this flag fixes the Python issue right now.

**Comment by brandjon** [comment]
Ping @gunan?

**Comment by gunan** [comment]
Ah, I am sorry that I have missed this issue. will try looking into this today, or tomorrow.
Also pinging @annarev as she is knowledgeable about python_api_gen_* targets

**Comment by meteorcloudy** [comment]
I tested `--host_force_python=PY2`, it does fix the failure. But I wonder what if we don't have python2 installed on the system. Will it cause a failure? @brandjon

**Comment by meteorcloudy** [comment]
Maybe a better way to fix this is to make all targets compatible with Python3?

**Comment by brandjon** [comment]
> But I wonder what if we don't have python2 installed on the system. Will it cause a failure?

In principle, if a target is analyzed as PY2 or PY3, it ought to be run under Python 2 or Python 3 respectively at execution time. If the target platform doesn't have that version of Python installed, that should be a build failure (if the absence of the interpreter is known by the toolchain) or execution failure (if the toolchain does autodetection at execution time).

The tricky use case is if you want to define a target that works under either version of Python. We don't directly support this but it should be possible with a macro and a dispatching target that chooses the right dependency based on a select() on platform constraints.
