### ISSUE TITLE
ExecutorState crash on specific iOS devices

### ISSUE THREAD

**Issue by benMattes** [tensorflow/tensorflow#29229]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): iPhone XR, iPhone XS using iOS 12.2
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: See above. 
- TensorFlow installed from (source or binary): Source
- TensorFlow version (use command below): 1.12
- Python version: 3.6.8
- Bazel version (if compiling from source): 0.22.0 
- GCC/Compiler version (if compiling from source): GCC
- CUDA/cuDNN version: N/A
- GPU model and memory:

**Describe the current behavior**

Last year we built an LSTM RNN using Tensorflow 1.12 and Python 3.6.8. After struggling for a couple of weeks we managed to get the tensorflow mobile static libraries compiled and running on iPhone and were able to run our model (a real-time Human Activity Recognition application, FWIW). 

On Apple's latest hardware (iPhone XR and XS) we are seeing seemingly random crashes after running inference for 20+ seconds. We receive a EXC_BAD_ACCESS crash as follows:

tensorflow::(anonymous namespace)::ExecutorState::Process(tensorflow::(anonymous namespace)::ExecutorState::TaggedNode, long long)

This custom model was built with BasicLSTMCell which makes it, from what we can discern, unsuitable for TFLite at this point (since LSTM Ops are not yet supported outside of the experimental branch). For reference (python code for the graph): 

        lstm_cells = [tf.contrib.rnn.BasicLSTMCell(num_units=n_neurons)
                      for layer in range(n_layers)]
        multi_cell = tf.contrib.rnn.MultiRNNCell(lstm_cells)
        outputs, states = tf.nn.dynamic_rnn(multi_cell, x, dtype=tf.float32)
        top_layer_h_state = states[-1][1]
  
**Other info / logs**

0 | PlayFitt | tensorflow::(anonymous namespace)::ExecutorState::Process(tensorflow::(anonymous namespace)::ExecutorState::TaggedNode, long long) + 56780
-- | -- | --
1 | PlayFitt | tensorflow::(anonymous namespace)::ExecutorState::Process(tensorflow::(anonymous namespace)::ExecutorState::TaggedNode, long long) + 58744
2 | PlayFitt | std::__1::__function::__func<std::__1::__bind<void (tensorflow::(anonymous namespace)::ExecutorState::*)(tensorflow::(anonymous namespace)::ExecutorState::TaggedNode, long long), tensorflow::(anonymous namespace)::ExecutorState*, tensorflow::(anonymous namespace)::ExecutorState::TaggedNode const&, long long&>, std::__1::allocator<std::__1::__bind<void (tensorflow::(anonymous namespace)::ExecutorState::*)(tensorflow::(anonymous namespace)::ExecutorState::TaggedNode, long long), tensorflow::(anonymous namespace)::ExecutorState*, tensorflow::(anonymous namespace)::ExecutorState::TaggedNode const&, long long&> >, void ()>::operator()() + 89040
3 | PlayFitt | Eigen::NonBlockingThreadPoolTempl<tensorflow::thread::EigenEnvironment>::WorkerLoop(int) + 276848
4 | PlayFitt | std::__1::__function::__func<tensorflow::thread::EigenEnvironment::CreateThread(std::__1::function<void ()>)::'lambda'(), std::__1::allocator<tensorflow::thread::EigenEnvironment::CreateThread(std::__1::function<void ()>)::'lambda'()>, void ()>::operator()() + 275152
5 | PlayFitt | void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, std::__1::function<void ()> > >(void*) + 56
6 | libsystem_pthread.dylib | _pthread_body + 132
8 | (Missing) | (Missing)

**Comment by renjie-liu** [comment]
Hi Ben,

Firstly, I would recommend you to try out tflite lstm (yes, it's under experimental, but I think switching to tflite can give you benefits on performance & binary size)

Back to the question, please note tf.nn.dynamic_rnn returns final_state, see [here](https://www.tensorflow.org/api_docs/python/tf/nn/dynamic_rnn#returns)

so you should do

```
outputs, final_state = tf.nn.dynamic_rnn(multi_cell, x, dtype=tf.float32)
top_layer_h_state = final_state[1]
```

cheers,
