### ISSUE TITLE
Node.js (JavaScript) TensorFlow Lite Wrapper API

### ISSUE THREAD

**Issue by hossein-b** [tensorflow/tensorflow#29236]
Is there any Node.js (JavaScript) API wrapper for TF Lite, for instance, if we can install:
npm install @tensorflow/tfjs-lite

**Comment by Brouilles** [comment]
Good Idea!

**Comment by nsthorat** [comment]
Just curious why you would want this over the Node.js bindings to the TensorFlow C library or to TensorFlow.js backends?

**Comment by hossein-b** [comment]
I am working on an embedded  aarch64_armv8 and I have compiled Tensorflow Lite by using this  [link](https://www.tensorflow.org/lite/guide/build_arm64), at the end, I have two these files:
benchmark-lib.a  libtensorflow-lite.a
Now, I want to bind these output files to node.js and run the following code for an instance:

```
// posenet
const tf = require('@tensorflow/tfjs-node');
const posenet = require('@tensorflow-models/posenet');
const {
    createCanvas, Image
} = require('canvas')
const imageScaleFactor = 0.5;
const outputStride = 16;
const flipHorizontal = false;
const videoWidth =426; 
const videoHeight =240; 
const img = new Image();
const canvas = createCanvas(videoWidth, videoHeight);
const ctx = canvas.getContext('2d');

const tryModel = async(imgsrc) => {
    const net = await posenet.load(0.75);
    img.src = imgsrc;
    ctx.drawImage(img, 0, 0);
    const input = tf.browser.fromPixels(canvas);
    const pose = await net.estimateSinglePose(input, imageScaleFactor, flipHorizontal, outputStride);
    return JSON.stringify(pose);
}
let tmodel = tryModel('./01_standing.png');
tmodel.then(function(result) {
   console.log('result:' + result);
});

```

**Comment by Jonarod** [comment]
@hossein-b I am in your same situation right now. Did you figure out what to do next ?

**Comment by kumariko** [comment]
@hossein-b Could you please let us know if you still need help on this ? if it is resolved then please feel free to move this issue to close status ? Thanks!

**Comment by hossein-b** [comment]
> @hossein-b Could you please let us know if you still need help on this ? if it is resolved then please feel free to move this issue to close status ? Thanks!

Thanks for your comment. I changed my mind to use Python Tensorflow, and it solved my problem.

**Comment by kumariko** [comment]
@hossein-b Could you please close this ticket if it is resolved for you ?
