### ISSUE TITLE
[TF 2.0 API Docs] tf.keras.layers.LSTM

### ISSUE THREAD

**Issue by YongJieYongJie** [tensorflow/tensorflow#29247]
## URL(s) with the issue:

https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/keras/layers/LSTM

*Suggestion: Where applicable, the documentation for this should be consistent with the base class [tf.keras.layers.RNN](https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/keras/layers/RNN) and other derived classes.*

### Clear description

 1. Use of backticks can be made more consistent and in line with the [Documentation Style - Write about code](https://www.tensorflow.org/community/contribute/docs_style#write_about_code). For example, the value "True" and "False" in the description is not surronded by backticks, as recommended by the Documentation Style guide.

### Correct links

 1. Link to the source code at "python/keras/layers/recurrent_v2.py" is incorrect. It points to https://github.com/tensorflow/tensorflow/tree/r2.0/tensorflow/python/keras/layers/recurrent_v2.py, which is a 404 page. Correct link (for master) should be https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/keras/layers/recurrent_v2.py.

### Parameters defined

 1. (As with the Clear Heading section above) Use of backticks can be made more consistent and in line with the [Documentation Style - Write about code](https://www.tensorflow.org/community/contribute/docs_style#write_about_code). For example, the value "True" and "False" in the description is not surronded by backticks, as recommended by the Documentation Style guide.

 1. `__init__(...)`:
    - Parameter `time_major` is not defined.
    - The default value is specified within the text of some of the parameter definitions *but not all*. For example, the definition for `unroll` is:
       >Boolean (default False). If True, the network will be unrolled, else a symbolic loop will be used. Unrolling can speed-up a RNN, although it tends to be more memory-intensive. Unrolling is only suitable for short sequences.  

       whereas the definition for `return_state` is:  

       > Boolean. Whether to return the last state in addition to the output.

1. `get_dropout_mask_for_cell(...)`:
    - First word of the definition of the parameters should be capitalized

1. `get_initial_state(...)`:
    - Parameter `inputs` is not defined.

1. `reset_states(...)`:
    - Parameter `states` is not defined.

### Returns defined

Return value is not defined for the following:
 - `get_initial_state(...)`
 - `reset_dropout_mask()`
 - `reset_recurrent_dropout_mask()`
 - `reset_state()`

For the last three items above, perhaps it is sufficiently clear that nothing will be returned.

### Raises listed and defined

No errors are defined.

### Usage example

No usage examples are provided. However, the description does have links to relevant guides and tutorials as follows:

 - Used in the guide:
    - [The Keras Functional API in TensorFlow](https://www.tensorflow.org/alpha/guide/keras/functional)  

 - Used in the tutorials:
    - [Load text with tf.data](https://www.tensorflow.org/alpha/tutorials/load_data/text)
    - [Text classification with an RNN](https://www.tensorflow.org/alpha/tutorials/text/text_classification_rnn)
    - [Text generation with an RNN](https://www.tensorflow.org/alpha/tutorials/text/text_generation)

### Request visuals, if applicable

There are current *no* visuals. LSTM itself might be too broad a topic to be dealt with comprehensively using visuals in this documentation page.

### Submit a pull request?

Are you planning to also submit a pull request to fix the issue?  
**No.** *(I can fix the formatting and syntax issues, but populating the missing parameter definitions is currently beyond my level 😅)*

### Related Issue

#26197

**Comment by ymodak** [comment]
This is now fixed with TF 2.4.1 core api docs. Thanks!
https://www.tensorflow.org/api_docs/python/tf/keras/layers/LSTM
