### ISSUE TITLE
[TF 2.0 API Docs] tf.image.transpose

### ISSUE THREAD

**Issue by Aqsa-K** [tensorflow/tensorflow#29245]
Doc link: https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/image/transpose

### Usage example

No usage example is provided.

**Comment by jvishnuvardhan** [comment]
@Aqsa-K This was already fixed [here](https://www.tensorflow.org/api_docs/python/tf/image/transpose) in the recent TF version. Thanks!

I am closing this issue as this was resolved. Thanks!
