### ISSUE TITLE
[TF 2.0 API Docs] tf.image.rot90

### ISSUE THREAD

**Issue by Aqsa-K** [tensorflow/tensorflow#29243]
Doc link: https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/image/rot90

### Usage example

No usage example is provided.

### Request visuals, if applicable

No Visuals are included. A visual example of rotation can be added although not necessary.

**Comment by gadagashwini** [comment]
@Aqsa-K Please point the correct link. Thanks!

**Comment by Aqsa-K** [comment]
@gadagashwini the link is correct. I added the link for reference only. The heading was misleading and have removed it from the issue description. Apologies.

**Comment by gadagashwini** [comment]
@Aqsa-K Looks like Doc link provided above is pointing to error 404.Can you please check and Let me know if that is same with you. Thanks!

**Comment by Aqsa-K** [comment]
I have copied the link again from the redirection in excel sheet. Please try now.

**Comment by jvishnuvardhan** [comment]
Automatically closing this out since I understand it to be resolved by the PR #29610 (merged already), but please let me know if I'm mistaken.Thanks!
