### ISSUE TITLE
[TF 2.0 API Docs] tf.io.extract_jpeg_shape

### ISSUE THREAD

**Issue by Aqsa-K** [tensorflow/tensorflow#29244]
Doc link: https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/io/extract_jpeg_shape

### Correct links

Link not provided. Path is written but href is not provided.

### Raises listed and defined

Errors are not defined.

### Usage example

No usage example is provided.

**Comment by rmothukuru** [comment]
@Aqsa-K,
Sorry for the delayed response. Your statement that is mentioned below, is not clear:

> Link not provided. Path is written but href is not provided.

Can you please elaborate it?  Thanks!
