### ISSUE TITLE
Problems and solutions in installing tf on Redhat

### ISSUE THREAD

**Issue by jinfengfeng** [tensorflow/tensorflow#2924]
I encountered several problems in installing tensorflow on Redhat system. I solved them by googling solutions. Hope my experience may be helpful to some users.

OS version: Red Hat Enterprise Linux Server release 6.2 (Santiago)
Linux kernel: 2.6.32-220.el6.x86_64

Problems and solutions:

 **1. glibc version is too low** 

Install higer version glibc, e.g. glibc-2.17.
Please use at least version 2.17. You can configure the installation using --prefix option to specify the path to install, and then modify LD_LIBRARY_PATH to include the new glibc library.

 **2. link problem after install higher version of glibc**

Error info looks like:
"
error while loading shared libraries: __vdso_time: invalid mode for dlopen():Invalid argument
"
You need to use the following method to run a program (eg. python):
/path/to/glibc-2.17/lib/ld-linux-x86-64.so.2 --library-path /path/to/glibc-2.17/lib:$LD_LIBRARY_PATH:/path/to/gcc-5.2.0/lib64:/usr/lib64/ /path/to/anaconda/bin/python2.7

 **3. numpy version problem** 

Install new version of numpy using pip.

 **4. protobuf3 not found, and** 
Error in python after 'import tensorflow': TypeError: __init__() got an unexpected keyword argument 'syntax'

pip install 'protobuf>=3.0.0a3'
 
 **5.  failed call to cuInit: CUDA_ERROR_NO_DEVICE**
Explicitly specify a cuda device in you environment variable:
export CUDA_VISIBLE_DEVICES=0

 **6. libcuda.so.1 not found**

Explicitly specify the path of this lib in your LD_LIBRARY_PATH environment variable. 
libcuda.so is in usually in /usr/lib64

 **7. ELFCLASS32 error**
elf is incorrect, should use a 64-bits .so file (usually in */lib64)

 **8. glibc 2.15 cannot create regular file `/var/db/Makefile': Permission denied**
Use glibc 2.17 or  even higher version.

**Comment by sherrym** [comment]
Thanks, @jinfengfeng .

**Comment by thegyro** [comment]
@jinfengfeng  Hi I have installed tensorflow within Anaconda. After manually installing the higher version of glibc, I had the link problem `error while loading shared libraries: __vdso_time: invalid mode for dlopen():Invalid argument` as you had specified. I tried running your command but it isn't working, I get the error  `python: error while loading shared libraries: python: cannot open shared object file: No such file or directory`. Any help? Thanks!

**Comment by IvyGongoogle** [comment]
@jinfengfeng I can not understand the second point `2. link problem after install higher version of glibc` in your above solution. How to solve this error:
`while loading shared libraries: __vdso_time: invalid mode for dlopen():Invalid argument`
?

**Comment by naveenjafer** [comment]
@jinfengfeng I did not understand Point 2 either, could you please help. @IvyGongoogle Were you able to solve the issue?

**Comment by shm007g** [comment]
I did not understand Point 2 either, could you please help. @IvyGongoogle Were you able to solve the issue?

**Comment by naveenjafer** [comment]
I tried what was mentioned in point 2, but running a command like `/opt/glibc-2.17/lib/ld-linux-x86-64.so.2 --library-path /opt/glibc-2.17/lib:$LD_LIBRARY_PATH:usr/lib64/ /home/njafer/python/bin/python3` at least works, but a command like `/opt/glibc-2.17/lib/ld-linux-x86-64.so.2 --library-path /opt/glibc-2.17/lib:$LD_LIBRARY_PATH:usr/lib64/ ls` gives me a `
ls: error while loading shared libraries: ls: cannot open shared object file`

**Comment by mjwen** [comment]
@naveenjafer 
To run ` ls`, you may need something like

`/opt/glibc-2.17/lib/ld-linux-x86-64.so.2 --library-path /opt/glibc-2.17/lib:$LD_LIBRARY_PATH:usr/lib64/ /bin/ls`
