### ISSUE TITLE
[TF 2.0 API Docs] tf.math.maximum / tf.maximum

### ISSUE THREAD

**Issue by whatevergeek** [tensorflow/tensorflow#29242]
**System information**

TensorFlow version: 2.0
Doc Link: https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/math/maximum

**Describe the documentation issue**

**Links**
python/ops/gen_math_ops.py
The implementation of the code is in c++.
However, the documentation references a generated python file.
which we can't open, or can't view a representative implementation.

Perhaps, we can add a representative implementation for such function.

**Usage Example**
No usage example is provided.

**Comment by ymodak** [comment]
TF 2.4 docs are updated with the usage example. Thanks!
https://www.tensorflow.org/api_docs/python/tf/math/maximum
