### ISSUE TITLE
[TF 2.0 API Docs] tf.autograph.to_code

### ISSUE THREAD

**Issue by ghchinoy** [tensorflow/tensorflow#29254]
## URL(s) with the issue:

https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/autograph/to_code

### Clear description

Initial description could be clearer, instead of referring to another function as similar (`to_graph`), restate primary use case: 
* From: “Similar to to_graph, but returns Python source code as a string.”
* To: “`to_code` is a low-level API that returns the AutoGraph generated Python source code as a string. This is similar to `to_graph`, which returns the TensorFlow graph, instead of Python.”

### Usage example

No usage example in docs, only references to guides/example, would suggest uplifting an example from a guide to the docs for completeness (ref https://www.tensorflow.org/alpha/guide/autograph)

### Submit a pull request?

Yes

**Comment by jvishnuvardhan** [comment]
@ghchinoy I notice you raise a PR to resolve this issue. Unfortunately that was not against `master` so the PR was closed. Can you submit that PR against `master`. Thanks!

**Comment by jvishnuvardhan** [comment]
@ghchinoy Can you submit this PR against `master`? You can copy and paste the closed PR and open it against `master` that will be helpful to the community. Thanks!

**Comment by jvishnuvardhan** [comment]
Closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
