### ISSUE TITLE
change 'py_func' to 'py_function' in https://www.tensorflow.org/beta/guide/data#applying_arbitrary_python_logic

### ISSUE THREAD

**Issue by NickleDave** [tensorflow/tensorflow#29256]
Thank you for submitting a TensorFlow documentation issue. Per our GitHub
policy, we only address code/doc bugs, performance issues, feature requests, and
build/installation issues on GitHub.

The TensorFlow docs are open source! To get involved, read the documentation
contributor guide: https://www.tensorflow.org/community/contribute/docs

## URL(s) with the issue:

#https://www.tensorflow.org/alpha/guide/data#applying_arbitrary_python_logic
https://www.tensorflow.org/beta/guide/data#applying_arbitrary_python_logic
## Description of issue (what needs changing):

minor typo, just need to update `py_func` in example so it is `py_function`

### Clear description

In last 4 lines of code block underneath "applying arbitrary python logic" section

```Python
dataset = dataset.map(
    lambda filename, label: tuple(tf.py_func(
        _read_py_function, [filename, label], [tf.uint8, label.dtype])))
dataset = dataset.map(_resize_function)
```

### Correct links

Yes

### Parameters defined

Yes

### Returns defined

Yes

### Raises listed and defined
Yes

### Usage example

Yes

### Request visuals, if applicable

No, not needed

### Submit a pull request?

No

**Comment by lamberta** [comment]
Thanks for the report, David.
That file is over here, would you mind making the fix and then I can merge it: https://github.com/tensorflow/docs/blob/master/site/en/r2/guide/data.md

**Comment by ymodak** [comment]
Closing this issue since the PR https://github.com/tensorflow/docs/pull/697 has been merged. Thanks!
