### ISSUE TITLE
[TF 2.0 API Docs] tf.autograph.set_verbosity

### ISSUE THREAD

**Issue by ghchinoy** [tensorflow/tensorflow#29250]
## URL(s) with the issue:

https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/autograph/set_verbosity

### Clear description

Description could be clearer:

* Reference to Abseil's logging format could be referenced rather than only to Abseil, itself (user would have to hunt through docs to see the logging output format referenced)
* There's a slight misspelling in the args for `alsologtostdout`
    “ it is recommended to set this value to a larges number, like 10” should be “ it is recommended to set this value to a large number, like 10”

### Submit a pull request?

Yes.

**Comment by gadagashwini** [comment]
Closing this issue since the associated PR has been merged. Feel free to reopen if the problem still persists. Thanks!
