### ISSUE TITLE
Always bind "localhost" when starting workers

### ISSUE THREAD

**Issue by tobegit3hub** [tensorflow/tensorflow#2925]
Now we have tried distributed TensorFlow and run multiple workers. It works but we found that it always bind "localhost" when I would like to bind one of my NICs.

Is it the bug? Or do I miss something because I found nothing to configure it in any document.

### Environment info
Operating System: Ubuntu 16.04

Installed version of CUDA and cuDNN:  No

If installed from binary pip package, provide:

1. Which pip package you installed.

```
root@100cd4fb5bca:/notebooks# pip --version
pip 8.1.1 from /usr/local/lib/python2.7/dist-packages (python 2.7)
```

2. The output from `python -c "import tensorflow; print(tensorflow.__version__)"`.

```
root@100cd4fb5bca:/notebooks# python -c "import tensorflow; print(tensorflow.__version__)"
0.8.0
```

### Steps to reproduce
1. docker run -it tensorflow/tensorflow bash
2. Write the server code of `one_worker.py`.
3. `python ./one_worker.py`

```
root@100cd4fb5bca:/notebooks# cat one_worker.py
import tensorflow as tf

worker1 = "www.a.com:2222"
worker_hosts = [worker1]

cluster_spec = tf.train.ClusterSpec({"worker": worker_hosts})

server = tf.train.Server(cluster_spec, job_name="worker", task_index=0)

server.join()
```

### Logs or other output that would be helpful

```
root@100cd4fb5bca:/notebooks# python ./one_worker.py
I tensorflow/core/distributed_runtime/rpc/grpc_channel.cc:206] Initialize HostPortsGrpcChannelCache for job worker -> {localhost:2222}
I tensorflow/core/distributed_runtime/rpc/grpc_server_lib.cc:202] Started server with target: grpc://localhost:2222
```

**Comment by sherrym** [comment]
Excellent question! The short answer is that it's not a bug. We always start an in-process server on localhost. So to use this correctly, you actually need to have a separate script which logs onto www.a.com and start the server. See https://github.com/tensorflow/tensorflow/blob/master/tensorflow/g3doc/how_tos/distributed/index.md
for details.

Here's the slightly longer answer should you be interested:

When this line is called on www.a.com,
  server = tf.train.Server(cluster_spec, job_name="worker", task_index=0)
a GrpcServer is created with target grpc://localhost:2222. This server knows how to talk to the tasks in the same job via GrpcChannels:
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/distributed_runtime/rpc/grpc_server_lib.cc#L150

Hope that helps. :)

Sherry

**Comment by tobegit3hub** [comment]
Thanks @sherrym and it helps a lot.

But I have another question. If it's target is always "localhost", how can the client which is in another host connect with this server? We can specify the "server.target" when initializing "Session" but it doesn't work to connect with "www.a.com:2222" or the ip.

**Comment by mrry** [comment]
> If the server.target has to be localhost:$post, the client has to be in the same host with the worker. Is that right?

No, the client and worker do not have to be on the same host. The `tf.train.Server` class is a Python wrapper for a server in the *local process*, so it always binds to a port on `localhost`. (It ignores the hostname that you specify for the corresponding task in the `tf.train.ClusterSpec`, so that you can use the same `ClusterSpec` in all processes.)

The client only needs to create a `tf.Session`, and does not need to create a `tf.train.Server` (though it can if you like). For example, you can run a server on `"www.a.com"` that listens on port 2222, and connect to it from another machine by creating a `tf.Session("grpc://www.a.com:2222")`.

**Comment by tobegit3hub** [comment]
Sorry for bothering. I was wrong when I test with `www.a.com` and definitely we can run servers and clients in different hosts.

Thanks for your help! @sherrym @mrry
