### ISSUE TITLE
[TF 2.0] Dataset has no attribute 'make_one_shot_iterator'

### ISSUE THREAD

**Issue by BingyuZhou** [tensorflow/tensorflow#29252]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Google Colab
- TensorFlow version (use command below): 2.0
- Python version:
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Describe the current behavior**
Report attribute error as :
 **AttributeError: 'BatchDataset' object has no attribute 'make_one_shot_iterator'**

**Describe the expected behavior**

**Code to reproduce the issue**
```
from __future__ import absolute_import, division, print_function, unicode_literals

# Install TensorFlow
!pip install tensorflow==2.0.0-alpha0

import tensorflow as tf
import tensorflow.keras.models as Models
import numpy as np

inc_dataset = tf.data.Dataset.range(100)
dec_dataset = tf.data.Dataset.range(0, -100, -1)
dataset = tf.data.Dataset.zip((inc_dataset, dec_dataset))
batched_dataset = dataset.batch(4)

iterator = batched_dataset.make_one_shot_iterator()
next_element = iterator.get_next()
```

**Comment by srijithrajeev** [comment]
As per [Release 2.0.0-alpha0](https://www.libupdate.com/libs/e0a82003-3ced-44dd-82c7-f8196968440e), tf.data.Dataset.make_one_shot_iterator() has been deprecate  in V1, removed from V2, and added to tf.compat.v1.data.make_one_shot_iterator().

**Comment by muddham** [comment]
@BingyuZhou Did you get chance to try as suggest by @srijithrajeev . I had tried and no error was shown.
tf.compat.v1.data.make_one_shot_iterator(batched_dataset)

**Comment by achandraa** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Comment by breadbread1984** [comment]
is there a counterpart of one_shot_iterator in tf 2.0. how can I keep the context of a dataset?

**Comment by fonnesbeck** [comment]
Can someone address the question from @breadbread1984? There doesnt appear to be any clear guidance in the docs regarding what the best practices are in the absence of `one_shot_iterator`.

**Comment by Giszy** [comment]
```python
import tensorflow as tf
import tensorflow.keras.models as Models
import numpy as np

inc_dataset = tf.data.Dataset.range(100)
dec_dataset = tf.data.Dataset.range(0, -100, -1)
dataset = tf.data.Dataset.zip((inc_dataset, dec_dataset))
batched_dataset = dataset.batch(4)


#iterator = batched_dataset.make_one_shot_iterator()
#next_element = iterator.get_next()

for next_element in batched_dataset:
    tf.print(next_element)
```

**Comment by breadbread1984** [comment]
iterator is necessary when you use multiple trainset together for training. for example, training mtcnn requires both wider face and celeba. you have to use iterator but a loop. but I have solved the problem buy tf.data.Dataset.__iter__()

**Comment by abratchik** [comment]
Hi @breadbread1984, could you please elaborate a bit how you managed to work around this issue? I'm trying to run the mnist.py from models/official/mnist and it fails in the  eval_input_fn() for exact same reason - no  make_one_shot_iterator() method. 

Here is the code that fails:
```

  def eval_input_fn():
    batched_dataset = dataset.test(flags_obj.data_dir).batch(flags_obj.batch_size)
    return batched_dataset.make_one_shot_iterator().get_next()
```

**Comment by breadbread1984** [comment]
@abratchik you can create iterator with

```python
  def eval_input_fn():
    batched_dataset = dataset.test(flags_obj.data_dir).batch(flags_obj.batch_size)
    return batched_dataset.__iter__()
```

**Comment by Giszy** [comment]
```python
import tensorflow as tf
import tensorflow.keras.models as Models
import numpy as np

inc_dataset = tf.data.Dataset.range(100)
dec_dataset = tf.data.Dataset.range(0, -100, -1)
dataset = tf.data.Dataset.zip((inc_dataset, dec_dataset))
batched_dataset = dataset.batch(4)


#iterator = batched_dataset.make_one_shot_iterator()
#next_element = iterator.get_next()

for x, y in batched_dataset:
    tf.print('the first iter', x)
    tf.print('ther sencod iter', y)
```

**Comment by viariasv** [comment]
> @abratchik you can create iterator with
> 
> ```python
>   def eval_input_fn():
>     batched_dataset = dataset.test(flags_obj.data_dir).batch(flags_obj.batch_size)
>     return batched_dataset.__iter__()
> ```
> 
> you can get a batch with
> 
> ```python
> iter = eval_input_fn();
> sample = next(iter);
> ```

thank you sir, that's the solution.

**Comment by hsh2438** [comment]
You just use iter() function like below.

iterator = iter(batched_dataset)
next_element = iterator.get_next()

**Comment by kvijaysai** [comment]
What is the solution for an error like this for below function?

```
def input_data():
    filenames = get_filenames()
    print(len(filenames))
    train_dataset = tf.data.Dataset.from_tensor_slices(filenames)
    train_dataset = train_dataset.shuffle(100).repeat()
    train_dataset = train_dataset.map(parse_image, num_parallel_calls=4).batch(batch_size)
    return train_dataset.make_one_shot_iterator()
```

Error is
```
Traceback (most recent call last):
  File "soft_n_cut_loss.py", line 307, in <module>
    iterator = input_data()
  File "C:\IU\Spring 2020\CSCI-B 657 Computer Vision\Project\unsupervised\wnet2\W-Net\input_data.py", line 26, in input_data
    return train_dataset.make_one_shot_iterator()
AttributeError: 'BatchDataset' object has no attribute 'make_one_shot_iterator'
```

If I use the iterator s mentioned in the comments above then I get error as:
```
Traceback (most recent call last):
  File "soft_n_cut_loss.py", line 307, in <module>
    iterator = input_data()
  File "C:\IU\Spring 2020\CSCI-B 657 Computer Vision\Project\unsupervised\wnet2\W-Net\input_data.py", line 27, in input_data
    iterator = iter(train_dataset)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow_core\python\data\ops\dataset_ops.py", line 334, in __iter__
    raise RuntimeError("__iter__() is only supported inside of tf.function "
RuntimeError: __iter__() is only supported inside of tf.function or when eager execution is enabled.
```

Can you please help me, how I can progress in this case? It would be great if someone can help me with the change I need to make in my function so that it works

**Comment by kvijaysai** [comment]
Hey,

It's working for me. I did below 2 things:

1. Added this in import libraries, earlier it was import tensorflow as tf
```
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()
```

2. In main function, added the below snippet
```
iterator = input_data()
images = iterator.get_next()
```

**Comment by engrmz** [comment]
Hello,
This solves my error. 


```
# import tensorflow as tf
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()
```

```
iterator = tf.compat.v1.data.make_one_shot_iterator(dataset)
```

**Comment by Harrypotterrrr** [comment]
@kvijaysai  Hi, downgrading the v2 to fit the compatibility is not a good workaround to deal with such kind of things. You can try the following code
``` python
def input_data():
    filenames = get_filenames()
    print(len(filenames))
    train_dataset = tf.data.Dataset.from_tensor_slices(filenames)
    train_dataset = train_dataset.shuffle(100).repeat()
    train_dataset = train_dataset.map(parse_image, num_parallel_calls=4).batch(batch_size)
    return train_dataset
train_iter = iter(train_dataset)
for I in range(step_num):
    input, output = train_iter.get_next()
```
You could check [tf.data.Iterator](https://www.tensorflow.org/api_docs/python/tf/data/Iterator) for more info.

**Comment by Harrypotterrrr** [comment]
I have got a similar problem. I deploy my train dataset and val dataset on multi gpus.
for the training dataset, I use the following code to build the dataset, while for the validation dataset, that requires me to iterate for each time of specified steps. Thus, I choose `tf.dataset.Iterator` to deal with such things, as the above comment shows.
However, when I tried to deploy the `val_iter` to multi gpus, the error is thrown. Anyone could help me out with this.
``` python
    with self.mirrored_strategy.scope():
            self.model = model(config)
            self.optimizer = tf.optimizers.Adam(learning_rate=self.config["lr"])
        self.train_dataset, self.val_dataset, self.test_dataset = dataloader()
        self.train_dataset = self.mirrored_strategy.experimental_distribute_dataset(self.train_dataset)
        self.val_dataset = self.mirrored_strategy.experimental_distribute_dataset(iter(self.val_dataset))
```

**Comment by soran-ghaderi** [comment]
You can create an iterator using the following function:

`
def dataset_iterator():
      dataset = dataset.repeat().prefetch(prefetch_batches)
      print("dataset: ", dataset)
      
      dataset_iterator = dataset.__iter__()
`

**Comment by soran-ghaderi** [comment]
You can create an iterator using the following function:

```
def dataset_iterator():
dataset = dataset.repeat().prefetch(prefetch_batches)
print("dataset: ", dataset)

  dataset_iterator = dataset.__iter__()
```

**Comment by wzZero** [comment]
> 
just return iterator is feasible, but im not sure how to make sure that self._training_data_generator is right,do i need to write a for-loop and yield something? here's part of my code：
```python
    def individual_batch_generator(self,inputs,targets):
        assert len(inputs) == len(targets)
        indices = np.arange(len(inputs))
        np.random.shuffle(indices)
        for index in range(0,len(inputs)):
            if self.in_memory_data:
                yield inputs[index], targets[index]
            else:
                input_features = self.individual_load_feature(inputs[index])
                yield input_features, targets[index]
```

and when i run my code it still errors with input ran out of data, i just put the returned iterator into model.fit T.T
