### ISSUE TITLE
[TF 2.0 API Docs] tf.greater

### ISSUE THREAD

**Issue by imransalam** [tensorflow/tensorflow#29257]
## URL(s) with the issue:

https://www.tensorflow.org/versions/master/api_docs/python/tf/math/greater

## Description of issue (what needs changing):

Correct link is not provided in the sense that it is only a text and not an actual link to the file.
No usage example is given in the documentation.
Raises are also not listed

### Correct links

Correct link is not provided in the sense that it is only a text and not an actual link to the file.

### Raises listed and defined

Raises are not listed in the documentation

### Usage example

There is no usage example provided

**Comment by ymodak** [comment]
This has been fixed. Thanks!
https://www.tensorflow.org/api_docs/python/tf/math/greater
