### ISSUE TITLE
Failed to load the native TensorFlow runtime

### ISSUE THREAD

**Issue by el-cucu** [tensorflow/tensorflow#29259]
**System information**
- OS Platform: Windows10
- TensorFlow installed from (source or binary): binary
- TensorFlow version: 1.13.1
- Python version: Python 3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 22:22:05) [MSC v.1916 64 bit (AMD64)] on win32
- Installed using virtualenv? pip? conda?: virtualenv
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: Cuda V10.0.130/ cuDNN: cudnn-10.0-windows10-x64-v7.5.0.56
- GPU model and memory: RTX 2070 8G
- NVIDIA Driver: NVIDIA-SMI 416.34       Driver Version: 416.34       CUDA Version: 10.0

**Packages**
Package              Version
-------------------- -------
absl-py              0.7.1
astor                0.8.0
gast                 0.2.2
grpcio               1.21.1
h5py                 2.9.0
Keras-Applications   1.0.8
Keras-Preprocessing  1.1.0
Markdown             3.1.1
mock                 3.0.5
numpy                1.16.4
pip                  19.1.1
protobuf             3.8.0
setuptools           41.0.1
six                  1.12.0
tensorboard          1.13.1
tensorflow-estimator 1.13.0
tensorflow-gpu       1.13.1
termcolor            1.1.0
virtualenv           16.6.0
Werkzeug             0.15.4
wheel                0.33.4

**Description**
I have tried every possible combination of CUDA/cuDNN and I still cannot make it work (last 3 days fighting, I need help). I even installed 3.7 (tried already with python 3.6.6 and 3.68)

**Stack-trace**
(venv) F:\workspace\ml>python -c "import tensorflow as tf; tf.enable_eager_execution(); print(tf.reduce_sum(tf.random_normal([1000, 1000])))"
Traceback (most recent call last):
  File "F:\workspace\ml\venv\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "F:\workspace\ml\venv\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "F:\workspace\ml\venv\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "F:\workspace\ml\venv\lib\imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "F:\workspace\ml\venv\lib\imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: A dynamic link library (DLL) initialization routine failed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "F:\workspace\ml\venv\lib\site-packages\tensorflow\__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "F:\workspace\ml\venv\lib\site-packages\tensorflow\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "F:\workspace\ml\venv\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "F:\workspace\ml\venv\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "F:\workspace\ml\venv\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "F:\workspace\ml\venv\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "F:\workspace\ml\venv\lib\imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "F:\workspace\ml\venv\lib\imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: A dynamic link library (DLL) initialization routine failed.

Failed to load the native TensorFlow runtime.

**Paths**
C:\WINDOWS
C:\WINDOWS\system32
C:\WINDOWS\System32\Wbem
F:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0\bin
F:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0\extras\CUPTI\libx64
F:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0\include
F:\Program Files\NVIDIA GPU Computing Toolkit\TensorRT\TensorRT-5.0.4.3\lib
F:\Program Files\NVIDIA GPU Computing Toolkit\cuDNN\cudnn-10.0-windows10-x64-v7.5.0.56\bin
F:\Program Files\NVIDIA GPU Computing Toolkit\cuDNN\cudnn-10.0-windows10-x64-v7.5.0.56\include
C:\Users\JIAM\AppData\Local\Programs\Python\Python37-32\
C:\Users\JIAM\AppData\Local\Programs\Python\Python37-32\Scripts\
C:\Program Files\NVIDIA Corporation\NVSMI
...
(In this order)

**Comment by el-cucu** [comment]
Installing tensorflow-gpu with pip proved to be one of the most frustrating experiences.
I still do not know what it was missing, after a while looked and installed using conda.

If I ever find out what was the problem I will post, I almost certain it is the way the package is compiled; I used dependency walker and the only thing I noticed is an error related to windows API references which I am not even sure why were even there to begging with unless the package was compiled using a Windows 8 machine.

**Comment by achandraa** [comment]
Just to verify did you try to follow instructions from [TensorFlow website](https://www.tensorflow.org/install/pip) for installing TF binary. Also we need to install proper Microsoft Visual c++ version. Please have a look or let us know if you have already tried the steps. Thanks!

**Comment by el-cucu** [comment]
> Just to verify did you try to follow instructions from [TensorFlow website](https://www.tensorflow.org/install/pip) for installing TF binary. Also we need to install proper Microsoft Visual c++ version. Please have a look or let us know if you have already tried the steps. Thanks!

I followed  the instructions. 
As a note: Using dependency walker I found issues with API-MS-WIN-XXXXX.DLL and EXT-MS-WIN-XXX.

**Comment by achandraa** [comment]
Please have a look on this [issue](https://github.com/tensorflow/tensorflow/issues/28848#issuecomment-495057676) and let us know if that helps to resolve the problem. Thanks!

**Comment by achandraa** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Comment by GateraGael** [comment]
Instructions that I followed

Without CUDA: https://www.pugetsystems.com/labs/hpc/How-to-Install-TensorFlow-with-GPU-Support-on-Windows-10-Without-Installing-CUDA-UPDATED-1419/

With CUDA: https://towardsdatascience.com/installing-tensorflow-with-cuda-cudnn-and-gpu-support-on-windows-10-60693e46e781

Also useful for future reference: https://medium.com/@mainakdutta76/gpu-configuration-for-deep-learning-f35a8bf0f5e1
