### ISSUE TITLE
[TF 2.0 API Docs] tf.clip_by_norm

### ISSUE THREAD

**Issue by noahhkim** [tensorflow/tensorflow#29264]
Thank you for submitting a TensorFlow documentation issue. Per our GitHub
policy, we only address code/doc bugs, performance issues, feature requests, and
build/installation issues on GitHub.

The TensorFlow docs are open source! To get involved, read the documentation
contributor guide: https://www.tensorflow.org/community/contribute/docs

## URL(s) with the issue:

https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/clip_by_norm

### Raises listed and defined

Errors are not defined.

### Request visuals, if applicable

No visuals are included.

**Comment by yongtang** [comment]
Added a PR #29264 for the fix.
