### ISSUE TITLE
Any plans to support tf.map_fn/tf.fold{l,r} with multiple tensors?

### ISSUE THREAD

**Issue by Lunarmony** [tensorflow/tensorflow#2926]
I might be interested in potentially working on this too, but just want to make sure that this doesn't conflict with any planned work :)

**Comment by sherrym** [comment]
Please feel free to send a PR.

Added @yuanbyu just in case.

**Comment by yuanbyu** [comment]
Some form of this is probably at HEAD.  Could you check if it meets your needs? If not, contributions are very welcome.

**Comment by ebrevdo** [comment]
Multiple tensors are now supported for map_fn and scan.

**Comment by nitishgupta** [comment]
Can you please give an example of how can map_fn be used for multiple tensors? Does it take a list of tensors and expects a function call on a list of 'unpacked' tensors?

**Comment by yuanbyu** [comment]
See the doc.
