### ISSUE TITLE
[TF 2.0 API Docs] tf.group

### ISSUE THREAD

**Issue by imransalam** [tensorflow/tensorflow#29262]
## URL(s) with the issue:

https://www.tensorflow.org/versions/master/api_docs/python/tf/group
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/ops/control_flow_ops.py

## Description of issue (what needs changing):

A clear description should be added and a proper usage example is to be added. 

### Clear description

For example:
A group operations can run multiple operations at the same time, operations are not sequential and they will be executed when tf.group will be called.

### Usage example

There is no usage example provided except for a link to where it's being used.

### Submit a pull request?
Yes
https://github.com/tensorflow/tensorflow/pull/29265

**Comment by ymodak** [comment]
The documentation has been updated. Thanks!
https://www.tensorflow.org/api_docs/python/tf/group
