### ISSUE TITLE
[TF 2.0 API Docs] tf.guarantee_const

### ISSUE THREAD

**Issue by imransalam** [tensorflow/tensorflow#29267]
## URL(s) with the issue:

https://www.tensorflow.org/versions/master/api_docs/python/tf/guarantee_const

## Description of issue (what needs changing):

No usage example is provided and the link does not exist. The raises are also not defined.

### Correct links

The link does not exists and is also a simple text

### Raises listed and defined

Raises are not listed

### Usage example

No usage example provided.

### Submit a pull request?

No

**Comment by rmothukuru** [comment]
Raised [a CL](https://critique-ng.corp.google.com/cl/370898060) to fix this issue. Thanks!
