### ISSUE TITLE
[TF 2.0 API Docs] tf.VariableAggregation

### ISSUE THREAD

**Issue by noahhkim** [tensorflow/tensorflow#29261]
## URL(s) with the issue:

https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/VariableAggregation

### Clear description

The description is not opinionated about when to use this symbol, and unclear on what aggregation methods for combining gradients would be useful for.

### Parameters defined

Parameters are poorly defined, and not formatted appropriately.

### Returns defined

Returns are not defined.

### Raises listed and defined

Errors are not defined.

### Usage example

No usage example is provided.

### Request visuals, if applicable

No visuals are included.

**Comment by rmothukuru** [comment]
@noahhkim,
Sorry for the delayed response. Can you please let us know if you would be interested to contribute by submitting a PR? Thanks!
