### ISSUE TITLE
tf.autograph.experimental.Feature

### ISSUE THREAD

**Issue by hendercine** [tensorflow/tensorflow#29270]
## URL(s) with the issue: 
https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/autograph/experimental/Feature

### Clear description

There is no description provided.

### Parameters defined

Parameters are undefined.

### Returns defined

Return values are not defined.

### Raises listed and defined

Errors are not defined? 

### Usage example

There is not a usage example.

**Comment by mdanatg** [comment]
experimental.Feature is not a function, so most of those fields don't apply. I'll send a CL to clarify in that it's an enumeration type and show an example.
