### ISSUE TITLE
[TF 2.0 API Docs] tf.keras.metrics

### ISSUE THREAD

**Issue by HenrySiau** [tensorflow/tensorflow#29273]
## URL(s) with the issue:
https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/keras/metrics

## Description of issue (what needs changing):
the link to the source code links to 404 page
`Defined in python/keras/api/_v2/keras/metrics/__init__.py.`

### Correct links
https://github.com/tensorflow/tensorflow/blob/r2.0/tensorflow/python/keras/metrics.py

### Submit a pull request?
no

**Comment by ymodak** [comment]
The webpage has been updated and all links are working now. Thanks!
