### ISSUE TITLE
tf.data.Options

### ISSUE THREAD

**Issue by hendercine** [tensorflow/tensorflow#29280]
## URL(s) with the issue:

https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/data/Options
### Usage example

There is no usage example.

**Comment by nikitamaia** [comment]
Closing this issue since [2.4 docs link to usage examples](https://www.tensorflow.org/api_docs/python/tf/data/Options#used-in-the-notebooks_1) in the tutorials
