### ISSUE TITLE
Issue With Usage Example in tf.estimator.BaselineEstimator

### ISSUE THREAD

**Issue by MariaNazari** [tensorflow/tensorflow#29288]
Links to Issue: https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/estimator/BaselineEstimator
https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/estimator/DNNEstimator
https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/estimator/DNNLinearCombinedEstimator
https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/estimator/LinearEstimator

So I noticed that in the usage example for the modules listed above, they reference tf.contrib.estimator.multi_label_head(), and I heard that tf.contrib is being deprecated. There is not replacement yet available for multi_label_head, and I wanted to bring this to you attention.

**Comment by dynamicwebpaige** [comment]
Thanks for letting us know about these instances of `tf.contrib.*` in our documentation's usage examples! We will want to modify these to be in canonical TensorFlow 2.0 style. 🙂 

@martinwicke

**Comment by martinwicke** [comment]
@karmel FYI

**Comment by yhliang2018** [comment]
@MariaNazari Thanks for pointing this out! Will update the doc strings with the expose of public Head APIs (very soon).

**Comment by yhliang2018** [comment]
The docs have been updated to 2.x APIs, and you may check it [here](https://www.tensorflow.org/api_docs/python/tf/estimator).
