### ISSUE TITLE
[TF 2.0 API Docs] tf.divide

### ISSUE THREAD

**Issue by skalagarla** [tensorflow/tensorflow#29285]
## URL(s) with the issue:

https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/math/divide

### Parameters defined

Parameter 'Name' is defined but no documentation provided regarding how to use it.

**Comment by ymodak** [comment]
The name argument is optional and can be any user-specified string.
```python
import tensorflow as tf
a = tf.math.divide( x=10, y=5, name='Division')
a.name
'Division:0'
```
