### ISSUE TITLE
[TF 2.0 API Docs] tf.data.experimental.Reducer

### ISSUE THREAD

**Issue by skalagarla** [tensorflow/tensorflow#29296]
## URL(s) with the issue:

https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/data/experimental/Reducer

### Clear description

Better description could be provided

### Parameters defined

No

### Returns defined

No

### Usage example

No example is provided

**Comment by jvishnuvardhan** [comment]
Added an example through this https://github.com/tensorflow/tensorflow/pull/53346

I am closing this issue as this was resolved. Please feel free to reopen if I anything missing. Thanks!
