### ISSUE TITLE
[TF 2.0 API Docs] tf.keras.layers.maximum

### ISSUE THREAD

**Issue by sam3ay** [tensorflow/tensorflow#29297]
## URL(s) with the issue:

https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/keras/layers/maximum

## Description of issue (what needs changing):

Clarify description, and add usage examples.

### Clear description

Description gives no insight into this methods function.

### Usage example

No Usage example provided.

**Comment by jvishnuvardhan** [comment]
Automatically closing this out since I understand it to be resolved by the PR https://github.com/tensorflow/tensorflow/pull/29725 (merged already), but please let me know if I'm mistaken.Thanks!
