### ISSUE TITLE
[TF 2.0 API Docs] tf.data.experimental.OptionalStructure

### ISSUE THREAD

**Issue by skalagarla** [tensorflow/tensorflow#29292]
## URL(s) with the issue:
https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/data/experimental/OptionalStructure

### Clear description

No description provided to any of the defined methods

### Usage example

No usage example is provided

**Comment by jvishnuvardhan** [comment]
@skalagarla I think this was already resolved. `tf.OptionalSpec` is an aliase of `OptionalStructure`. Please check the [page here](https://www.tensorflow.org/api_docs/python/tf/OptionalSpec)

I am closing this issue as this was resolved. Please feel free to reopen if I am mistaken. Thanks!
