### ISSUE TITLE
GFile gcs_file_system crashes with bad header

### ISSUE THREAD

**Issue by alexrenda** [tensorflow/tensorflow#29304]
**System information**
- OS Platform and Distribution: MacOS Mojave 10.14.3
- TensorFlow installed from (source or binary): binary
- TensorFlow version: `0.12.0-rc1-7-ga13284f-dirty 0.12.0`
- Python version: Python 3.7.0

```
import tensorflow as tf
with tf.gfile.Open('gs://bucket_name/file_name') as f:
    f.write('foo\n')
```
crashes with error 
```
Traceback (most recent call last):
  File "/tmp/foo.py", line 4, in <module>
    f.write('foo\n')
  File "/usr/local/lib/python3.7/site-packages/tensorflow/python/lib/io/file_io.py", line 150, in __exit__
    self.close()
  File "/usr/local/lib/python3.7/site-packages/tensorflow/python/lib/io/file_io.py", line 182, in close
    pywrap_tensorflow.Set_TF_Status_from_Status(status, ret_status)
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/contextlib.py", line 119, in __exit__
    next(self.gen)
  File "/usr/local/lib/python3.7/site-packages/tensorflow/python/framework/errors_impl.py", line 469, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.InternalError: Unexpected response from GCS when writing to gs://bucket_name/file_name: 'Location' header not returned.
```

This seems to be due to 
https://github.com/tensorflow/tensorflow/blob/efdc88cf13827a22fbb7f4d58a14a3cfe57fd21c/tensorflow/core/platform/cloud/gcs_file_system.cc#L509
which checks for the "Location" header (with specifically a capital 'L').

However on my system:
`curl 'https://www.googleapis.com/upload/storage/v1/b/bucket_name/o?uploadType=resumable&name=file_name' -XPOST -H 'X-Upload-Content-Length: 10' -H'Authorization: Bearer TOKEN' --verbose`
returns the header "location" with a lowercase 'l', which causes the above error.

Changing that byte from "L" to "l" in the tensorflow `so` file fixes this for me (although that code is currently running successfully on other machines, so I'm not sure what makes mine special).

**Comment by ymodak** [comment]
@rinugun Can you please take a look? Thanks!

**Comment by orsharir** [comment]
@alexrenda Hi, I've encountered a similar issue, but it happens only when using TPUs where SummaryWriter throws the same exception. Have you managed to sort it out in your case?

**Comment by sachinprasadhs** [comment]
tf.gfile has been moved under [tf.io.gfile,](https://www.tensorflow.org/api_docs/python/tf/io/gfile), could you please try in the latest version and check if the error still persists. Thanks!
