### ISSUE TITLE
[TF 2.0 API Docs] tf.estimator.VocabInfo

### ISSUE THREAD

**Issue by eashtianjr** [tensorflow/tensorflow#29307]
## URL(s) with the issue:

https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/estimator/VocabInfo

### Clear description

This API Documentation does not state when or when not to use this symbol. The description lacks details specific to the desired use case. 

### Correct links

The link to the source code is correct.

### Parameters defined

All of the parameters are defined and formatted correctly.

### Returns defined

Return values are not defined.

### Raises listed and defined

Errors are not defined.

### Usage example

The API Symbol also doesn't contain well-documented code sample(s). The current code samples provided are missing concise explanations. For example, why would you use the different backup initializers or invocations?

### Request visuals, if applicable

No visuals specified.

### Submit a pull request?

Yes, I've created a pull request.
https://github.com/tensorflow/tensorflow/pull/29520

**Comment by achandraa** [comment]
Can you please help us to reference corresponding PR raised on master branch. Thanks!

**Comment by eashtianjr** [comment]
@achandraa I've updated the pull request to https://github.com/tensorflow/tensorflow/pull/29520

**Comment by achandraa** [comment]
@eashtianjr : Thanks for the update.

**Comment by achandraa** [comment]
Closing the issue since PR is merged to master. Thanks!
