### ISSUE TITLE
Is contrib/quantization available through Python interface?

### ISSUE THREAD

**Issue by changyun79** [tensorflow/tensorflow#2930]
It works in C++ if I build label_image example but if I call through python, I got:
tensorflow.python.framework.errors.NotFoundError: Op type not registered 'QuantizeV2'

Is there any build file I need to update? I tested on RC0.9 release. Thanks.

**Comment by sherrym** [comment]
In Python it's call  tf.contrib.quantization.python.quantize_v2.

**Comment by sherrym** [comment]
Please let me know if it works for you. Thanks.

**Comment by changyun79** [comment]
Thanks for the response. It happened when I load the pretrained and converted graph as
`
        with tf.gfile.FastGFile(model_path, 'rb') as f:
            graph_def = tf.GraphDef()
            graph_def.ParseFromString(f.read())
            _ = tf.import_graph_def(graph_def, name='')
`
and then run the session
`
            correct += np.sum(sesh.run(top_k_op,
                                       feed_dict={input_node: images,
                                                  label_node: labels}))
`
Does it mean I have to update the the graph (.pb) file? Thanks.

btw, I am new to tensorflow.

**Comment by changyun79** [comment]
I found the solution from Pete Warden's blog. @petewarden Thanks. Pete provided solutions for both Python and C++ interface cases while I misread python part.
