### ISSUE TITLE
[TF 2.0 API Docs] tf.identity_n

### ISSUE THREAD

**Issue by imransalam** [tensorflow/tensorflow#29317]
## URL(s) with the issue:

https://www.tensorflow.org/versions/master/api_docs/python/tf/identity_n

### Correct links

The path should be href, also the file it refers to does not exists

### Raises listed and defined

Raises are not listed and defined

### Submit a pull request?

No

**Comment by amahendrakar** [comment]
@imransalam,
The link you've provided doesn't exist anymore.

Could you please take a look at the latest version of the documentation for [tf.identity_n](https://www.tensorflow.org/api_docs/python/tf/identity_n) and let us know if this is still an issue. Thanks!
