### ISSUE TITLE
keras.model.load_weights does not consider custom model(layer) 

### ISSUE THREAD

**Issue by edwardyehuang** [tensorflow/tensorflow#29310]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):Ubuntu 18.04
- TensorFlow installed from (source or binary): conda/Anaconda
- TensorFlow version (use command below):1.13 (Issue still existed in the latest source code)

I failed to load the official **Resnet** h5 weights with self implemented **Resnet** using the **tf.keras.model**.

I found the behaviour of **load_weights** in **network.py** does not considered the sub **tf.keras.model**.

For example, the **Resnet** has a **ConvBlock** and a **IdentityBlock**. Instead of use a **function** to define them, I used **tf.keras.model** to define them, so it followed the latest standard.

Instead of simply pass the **self.layers** to **load_weights_from_hdf5_group_by_name**.  The **load_weights** function is **network.py** should collect all layers inside the sub model, then pass to **load_weights_from_hdf5_group_by_name**.

[network.py](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/keras/engine/network.py) line 1415

Suggested naive fix:

    def get_all_layers (model : tf.keras.Model):

        layers = []

        for layer in model.layers:
            if isinstance(layer, tf.keras.Model):
                layers.extend(get_all_layers(layer))
            else:
                layers.append(layer)

        return layers

**Comment by edwardyehuang** [comment]
Confirmed again, this issue is existed

**Comment by achandraa** [comment]
Will it be possible to provide a minimal code snippet that can reproduce the issue. It will really help us to understand the issue more clearly. Thanks!

**Comment by edwardyehuang** [comment]
For example 

```
import tensorflow as tf

class ConvBlock(tf.keras.Model):

    def __init__(self, kernel_size, filters, stage, block, strides=(2, 2), weight_decay = 0., momentum = 0.9):

        super(ConvBlock, self).__init__()

        filters1, filters2, filters3 = filters

        conv_name_base = 'res' + str(stage) + block + '_branch'
        bn_name_base = 'bn' + str(stage) + block + '_branch'

        self.conv2a = tf.keras.layers.Conv2D(filters1, (1, 1), strides=strides, kernel_initializer='he_normal', name=conv_name_base + '2a', kernel_regularizer=tf.keras.regularizers.l2(weight_decay))
        self.bn2a   = tf.keras.layers.BatchNormalization(name=bn_name_base + '2a', momentum=momentum)

        # ...........................................

    def call(self, input):

        #............................................


class Resnet (tf.keras.Model):

    def __init__ (self, weight_decay = 0., momentum = 0.9):

        super(Resnet, self).__init__()

        self.conv1_pad  = tf.keras.layers.ZeroPadding2D(padding=(3, 3), name='conv1_pad')
        self.conv1      = tf.keras.layers.Conv2D(64, (7, 7), strides=(2, 2), padding='valid', kernel_initializer='he_normal', name='conv1', kernel_regularizer=tf.keras.regularizers.l2(weight_decay))
        self.bn_conv1   = tf.keras.layers.BatchNormalization(name='bn_conv1', momentum=momentum)

        self.pool1_pad  = tf.keras.layers.ZeroPadding2D(padding=(1, 1), name='pool1_pad')
        self.pool1      = tf.keras.layers.MaxPooling2D((3, 3), strides=(2, 2))
        
        # SubModel Weights not loaded
        self.conv_block2a = ConvBlock(3, [64, 64, 256], stage=2, block='a', strides=(1, 1))   
        
        #...............................................


# Test code 

resnet = Resnet()
resnet(tf.zeros([1, 512, 512, 3]))
resnet.load_weights("resnet50_weights_tf_dim_ordering_tf_kernels_notop.h5", by_name=True)

```

**Comment by edwardyehuang** [comment]
The tf.keras.Model.load_weights will not load the weights for the ConvBlock in above code.

**Comment by jvishnuvardhan** [comment]
@edwardyehuang Can you provide a standalone code to reproduce the issue? The current code shows `NotImplementedError: When subclassing the `Model` class, you should implement a `call` method.`. Thanks!

**Comment by edwardyehuang** [comment]
> 
> 
> @edwardyehuang Can you provide a standalone code to reproduce the issue? The current code shows `NotImplementedError: When subclassing the `Model`class, you should implement a`call` method.`. Thanks!

The example above is not a full code

**Comment by edwardyehuang** [comment]
[resnet.zip](https://github.com/tensorflow/tensorflow/files/3429272/resnet.zip)

**Comment by edwardyehuang** [comment]
Cannot believe you guys still cannot understand my issue...
For example, 
Conv2d is the subclass of tf.keras.layer 
Resnet and ConvBlock are the subclass of tf.keras.Model
A Resnet class contains Conv2d and ConvBlock instances
A ConvBlock contains Conv2d instances
When doing the load h5 weight by name for Resnet. It will only load the weights for the tf.keras.layer instances in Resnet. The tf.keras.layer instances in ConvBlock is ignored

**Comment by tanzhenyu** [comment]
Hmm...AFAIK .layers has issues for functional and subclassed models. But if with the solution you proposed it works fine, then we'd appreciate if you want to contribute.

**Comment by edwardyehuang** [comment]
#31049

**Comment by tanzhenyu** [comment]
Closing this. Let's move discussion to the PR.

**Comment by xiang-zhe** [comment]
@edwardyehuang
it seems that  load_weights(.h5, name=True) not work when changing the one layer of  subclassed model name(in faster rcnn) ,it still raise erro about shape dismatch:
```
ValueError: Layer #4 (named "b_box_head"), weight <tf.Variable 'faster_rcnn/b_box_head/new_rcnn_class_logits/kernel:0' shape=(1024, 3) dtype=float32, numpy=
array([[ 0.01749247,  0.02859198, -0.05616229],
       [-0.02462629, -0.00092562,  0.01323454],
       [-0.00727267,  0.06154063, -0.04503936],
       ...,
       [-0.00280149,  0.07457583,  0.00443103],
       [-0.01985164,  0.05016208,  0.01354645],
       [-0.05778077, -0.00505048,  0.04575966]], dtype=float32)> has shape (1024, 3), but the saved weight has shape (1024, 81).

```
Layer #4 (named "b_box_head") including some layers, and i change the one layer name from 'rcnn_class_logits' to 'new_rcnn_class_logits' according to the KERAS site, any helps? thanks
ubuntu 16 +python 3 + tf2

**Comment by edwardyehuang** [comment]
I found this issue is still not resolved. Let's fix this now. @tanzhenyu  Could you reopen this issue?
