### ISSUE TITLE
[TF 2.0 API Docs] tf.identity

### ISSUE THREAD

**Issue by imransalam** [tensorflow/tensorflow#29315]
## URL(s) with the issue:

https://www.tensorflow.org/versions/master/api_docs/python/tf/identity
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/ops/array_ops.py

### Raises listed and defined

Raises are not listed and defined

### Usage example

No usage example provided

### Submit a pull request?

Yes
https://github.com/tensorflow/tensorflow/pull/29316

**Comment by ymodak** [comment]
Closing this issue since its resolved. Thanks!
https://www.tensorflow.org/api_docs/python/tf/identity?version=stable
