### ISSUE TITLE
[TF 2.0 API Docs] tf.data 

### ISSUE THREAD

**Issue by netskink** [tensorflow/tensorflow#29324]
## URL(s) with the issue:

https://www.tensorflow.org/versions/master/api_docs/python/tf/data
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/data/__init__.py

### Added reference to three tutorials on using tf.data

Since there are a mix of r2.0 and r1.x tutorials on datasets, these three are relevant for 2.0

### Correct links

Yes
### Parameters defined

Yes/NA

### Returns defined

Yes/NA

### Raises listed and defined

No/Perhaps NA

### Usage example

No, this is to add a pointer to usage.

### Request visuals, if applicable

No. It would be good to have some simple visuals relative to the different classes.

### Submit a pull request?

[#29323](https://github.com/tensorflow/tensorflow/pull/29323)

**Comment by nikitamaia** [comment]
Closing this issue since PR #29323 is closed
