### ISSUE TITLE
[TF 2.0 API Docs] tf.image.adjust_saturation

### ISSUE THREAD

**Issue by imransalam** [tensorflow/tensorflow#29332]
## URL(s) with the issue:

https://www.tensorflow.org/versions/master/api_docs/python/tf/image/adjust_saturation
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/ops/image_ops_impl.py

### Raises listed and defined

Raises are not listed

### Usage example

No usage example has been provided

### Submit a pull request?

Yes
https://github.com/tensorflow/tensorflow/pull/29333

**Comment by gadagashwini** [comment]
Closing this issue since the associated PR has been merged. Feel free to reopen if the problem still persists. Thanks!
