### ISSUE TITLE
[TF 2.0 API Docs] tf.image.central_crop

### ISSUE THREAD

**Issue by imransalam** [tensorflow/tensorflow#29334]
## URL(s) with the issue:

https://www.tensorflow.org/versions/master/api_docs/python/tf/image/central_crop
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/ops/image_ops_impl.py

### Usage example

No usage example provided

### Submit a pull request?

Yes

**Comment by achandraa** [comment]
Closing the issue since PR is merged to master. Thanks!
