### ISSUE TITLE
[TF 2.0 API Docs] tf.data.Dataset.map() example has web render issues.

### ISSUE THREAD

**Issue by netskink** [tensorflow/tensorflow#29339]
## URL(s) with the issue:

https://www.tensorflow.org/versions/master/api_docs/python/tf/data
https://www.tensorflow.org/versions/master/api_docs/python/tf/data/Dataset
https://www.tensorflow.org/versions/master/api_docs/python/tf/data/TextLineDataset

https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/data/ops/dataset_ops.py

### The map() method call for each of these classes has an example which is not being rendered properly.

This is what is intended by the docstring

```
   # NOTE: The following examples use `{ ... }` to represent the
    # contents of a dataset.
    # Each element is a `tf.Tensor` object.
    a = { 1, 2, 3, 4, 5 }
    # `map_func` takes a single argument of type `tf.Tensor` with the same
    # shape and dtype.
    result = a.map(lambda x: ...)
```

This is what gets rendered to the web.  It looks like the back tick references have an issue.

```
# NOTE: The following examples use `{ ... }` to represent the
# contents of a dataset.
# Each element is a <a href="../../tf/Tensor"><code>tf.Tensor</code></a> object.
a = { 1, 2, 3, 4, 5 }
# `map_func` takes a single argument of type <a href="../../tf/Tensor"><code>tf.Tensor</code></a> with the same
# shape and dtype.
result = a.map(lambda x: ...)
```

### Submit a pull request?

No, the docstring looks correct.  I don't know how to fix the error.

**Comment by anestisdotpy** [comment]
Why are there reference links inside the code after all? I'm confused.

**Comment by netskink** [comment]
The code creates documentation via doc strings.

**Comment by netskink** [comment]
I don’t know if the code links work or not.  That is a good point.

**Comment by ymodak** [comment]
The issue also exists in r2.0 https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/data/Dataset#for_example_5

**Comment by lamberta** [comment]
Regarding the links in the code block, we auto-link backticked TF symbols, so it's probably written as \`tf.Tensor\`. We probably shouldn't expand links in code blocks, if we can detect that.

**Comment by anestisdotpy** [comment]
> Regarding the links in the code block, we auto-link backticked TF symbols, so it's probably written as `tf.Tensor`. We probably shouldn't expand links in code blocks, if we can detect that.

Could we check for "#" in the same line? In that way we could know that it is a code comment and thus, not link it.

**Comment by yashk2810** [comment]
Yes, that would work.

**Comment by anestisdotpy** [comment]
I would like to work on it if that is okay with you and if you could point me in the right direction as I don't know where this is done.

**Comment by yashk2810** [comment]
Hey, you can definitely work on it. Thanks.

To start, changing the regular expression here (https://github.com/tensorflow/docs/blob/master/tools/tensorflow_docs/api_generator/parser.py#L118) to not consider lines that start with '#' should solve it.

Good luck and let me know if you have any questions :)

**Comment by anestisdotpy** [comment]
I have opened a PR. I believe that should do the work.

Thanks!

**Comment by anestisdotpy** [comment]
I think this issue could be closed now as it is solved!

**Comment by lamberta** [comment]
Thank you, Anestis!
