### ISSUE TITLE
[TF 2.0 API Docs] tf.image.adjust_jpeg_quality

### ISSUE THREAD

**Issue by imransalam** [tensorflow/tensorflow#29330]
## URL(s) with the issue:

https://www.tensorflow.org/versions/master/api_docs/python/tf/image/adjust_jpeg_quality
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/ops/image_ops_impl.py

### Raises listed and defined

Raises are not listed and defined.

### Usage example

No usage example has been provided

### Submit a pull request?

Yes
https://github.com/tensorflow/tensorflow/pull/29331

**Comment by ymodak** [comment]
Closing this issue since the associated PR has been merged. Thanks!
