### ISSUE TITLE
[TF 2.0 API Docs] tf.data.Dataset and tf.data.experimental.CsvDataset list_files

### ISSUE THREAD

**Issue by netskink** [tensorflow/tensorflow#29338]
## URL(s) with the issue:

https://www.tensorflow.org/versions/master/api_docs/python/tf/data/Dataset#list_files
https://www.tensorflow.org/versions/master/api_docs/python/tf/data/experimental/CsvDataset#list_files

https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/data/

### list_files() routine for both classes use the same bit of code to describe how to use the method.  The descriptive text is written in docstring and it looks like this
Example:
      If we had the following files on our filesystem:
        - /path/to/dir/a.txt
        - /path/to/dir/b.py
        - /path/to/dir/c.py
      If we pass "/path/to/dir/*.py" as the directory, the dataset
      would produce:
        - /path/to/dir/b.py
        - /path/to/dir/c.py

However, when rendered it is all one line without the indentation or bullet points.  So it looks like this:

If we had the following files on our filesystem: - /path/to/dir/a.txt - /path/to/dir/b.py - /path/to/dir/c.py If we pass "/path/to/dir/*.py" as the directory, the dataset would produce: - /path/to/dir/b.py - /path/to/dir/c.py

This should be corrected.

**Comment by netskink** [comment]
Ahh, this also causes problems with TextLineDataset.list_files() routine.  Its probably in every subclass method as well. ie. TFRecordDataset

**Comment by amahendrakar** [comment]
@netskink,
I see that in the latest version of the documentation the pages are rendered as expected i.e. with bullet points and indentation. 

- https://www.tensorflow.org/api_docs/python/tf/data/Dataset#list_files
- https://www.tensorflow.org/api_docs/python/tf/data/experimental/CsvDataset#list_files

Closing this issue as it is resolved. Please feel free to re-open if mistaken. Thanks!
