### ISSUE TITLE
In eager mode, the name of variables always has a suffix of value index

### ISSUE THREAD

**Issue by llan-ml** [tensorflow/tensorflow#29348]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using): 2.0.0alpla0
- Are you willing to contribute it (Yes/No):

**Describe the feature and the current behavior/state.**
<pre>
In [32]: type(x)
Out[32]: tensorflow.python.ops.resource_variable_ops.ResourceVariable

In [33]: x.name
Out[33]: 'my_model/context_predictor/kernel:0'

In [34]: x.name.split(":")[0]
Out[34]: 'my_model/context_predictor/kernel'
</pre>

**Will this change the current api? How?**
We can add a property to `tf.Tensor` like:
<pre>
@property
def unique_name(self):      # or other simpler names
  return self.name.split(":")[0]
</pre>
**Who will benefit with this feature?**
Who wants to get variable names

**Comment by lufol** [comment]
Running the small snippet you provided, I get this error `AttributeError: Tensor.name is meaningless when eager execution is enabled.`
Could you please provide a working demo?

**Comment by llan-ml** [comment]
@lufol My mistake. We should only consider to get variable names in tf2.
<pre>
In [8]: w = tf.Variable(tf.random.normal((3, 4)), name="test")

In [9]: w.name
Out[9]: 'test:0'

In [10]: w.name.split(":")[0]
Out[10]: 'test'
</pre>

**Comment by lufol** [comment]
Thanks for the correction, now I can reproduce your problem.
A possible solution, without adding new code to tf, would be to use `w._shared_name`.
But keep in mind that this is a protected member of class `Variable`.

If this solves your problem, please close sthis issue.
Best regards
Lukas

**Comment by llan-ml** [comment]
@lufol BTW, do you know why this property is defined to be protected. You know, in tf 1.x, we often use `w.op.name` to get the shared name here.

**Comment by lufol** [comment]
@llan-ml Sorry, I have no clue. I just thought, maybe the index after `name` is counted up if the same name is used again, but this is not the case as
`w = tf.Variable(tf.random.normal((3, 4)), name="test")`
`v = tf.Variable(tf.random.normal((3, 4)), name="test")`
`print(w.name)`
`print(v.name)`
Outputs is both cases
`test:0`
