### ISSUE TITLE
Tensorflow 2.0 doesn't start new compute cycle with tensor.numpy()

### ISSUE THREAD

**Issue by jackshi0912** [tensorflow/tensorflow#29340]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: Yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 18.04
- **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device**: n/a
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: 2.0 alpha
- **Python version**: 3.6
- **Bazel version (if compiling from source)**: n/a
- **GCC/Compiler version (if compiling from source)**: n/a
- **CUDA/cuDNN version**: n/a
- **GPU model and memory**: n/a
- **Exact command to reproduce**:

if __name__ == "__main__":
    rand: tf.Tensor = tf.random.uniform([], minval=1, maxval=10, dtype=tf.int32)
    print([rand.numpy() for i in range(20)])

### Describe the problem
When you run the following (equivalent code from tensorflow 1):
tf.compat.v1.disable_eager_execution()
if __name__ == "__main__":
    rand: tf.Tensor = tf.random.uniform([], minval=1, maxval=10, dtype=tf.int32)
    with tf.compat.v1.Session() as sess:
        print([rand.eval() for i in range(20)])

You get different output for every eval() call. This make sense since every eval() call executes the subgraph to evaluate rand node. When you execute the same code in Tensorflow 2.0, the result seems to be cached for some reason.

**Comment by nimuh** [comment]
I will gladly work on this. Any tips? @jackshi0912

**Comment by achandraa** [comment]
@jackshi0912 : Please help us to know the definition of "name" in the code. It will surely help us to proceed further. Thanks!

**Comment by llan-ml** [comment]
@achandraa I think it should be `if __name__ == "__main__"`.

You can reproduce this with `tf2` by:
<pre>
rand = tf.random.uniform([], minval=1, maxval=10, dtype=tf.int32)
print([rand.numpy() for i in range(20)])
</pre>
and
<pre>
rand = tf.random.uniform([], minval=1, maxval=10, dtype=tf.int32)
with tf.compat.v1.Session() as sess:
    print([rand.eval() for i in range(20)])
</pre>

**Comment by jackshi0912** [comment]
A broader problem that is related to the design of Eager Execution:

In tf1, you could do something like sess.run([all the nodes you want to compute]). This way you can run a single compute cycle with all the nodes evaluated.
Is there a similar function in tf2? Say I have some RNG as part of my graph, I would like to grab all their values along with some results based on them all in one compute cycle. For example:

rand1 = tf.random.uniform([], minval=1, maxval=10, dtype=tf.int32)
rand2 = tf.random.uniform([], minval=1, maxval=10, dtype=tf.int32)
output = some_very_complicated_stack(rand1, rand2)
with tf.compat.v1.Session() as sess:
    rand1_val, rand2_val, output_val = sess.run([rand1, rand2, output])

This way I know what the output value is of my system as well as the random input that went into it in the same compute cycle. I don't see a way to accomplish this in tf2 yet.

**Comment by jackshi0912** [comment]
> I will gladly work on this. Any tips? @jackshi0912

In tf1, eval() or sess.run() resets the "readyness" of the nodes because each call is a separate compute cycle. 
My guess is that in tf2, numpy() does not reset the "readyness" of the nodes. It sees that the node is already evaluated with a cached value and just grabbed it.

**Comment by llan-ml** [comment]
@jackshi0912 You should write them in a function:
<pre>
In [5]: def foo():
   ...:     rand1 = tf.random.uniform([], minval=1, maxval=10, dtype=tf.int32)
   ...:     rand2 = tf.random.uniform([], minval=1, maxval=10, dtype=tf.int32)
   ...:     output = rand1 + rand2
   ...:     return rand1, rand2, output
   ...:
   ...:

In [6]: foo()
Out[6]:
(&lttf.Tensor: id=425, shape=(), dtype=int32, numpy=3>,
 &lttf.Tensor: id=429, shape=(), dtype=int32, numpy=7>,
 &lttf.Tensor: id=430, shape=(), dtype=int32, numpy=10>)

In [7]: foo()
Out[7]:
(&lttf.Tensor: id=437, shape=(), dtype=int32, numpy=7>,
 &lttf.Tensor: id=441, shape=(), dtype=int32, numpy=4>,
 &lttf.Tensor: id=442, shape=(), dtype=int32, numpy=11>)
</pre>

Just think tf2 as numpy. You cannot do what you want in numpy without repeatedly calling a function.

**Comment by achandraa** [comment]
Just to verify whether I am on track or not, I have tried reproducing the below code snippet on Colab with TF2.0-alpha/2.0.0-dev20190605/1.13.1 and was able to get different output each time I am executing the snippet. 

**On TF1.13.1 :**
import tensorflow as tf 
tf.compat.v1.disable_eager_execution()
if __name__ == "__main__":
  rand: tf.Tensor = tf.random.uniform([], minval=1, maxval=10, dtype=tf.int32)
  with tf.compat.v1.Session() as sess:
    print([rand.eval() for i in range(20)])

**On TF2.0 :**
import tensorflow as tf 
if __name__ == "__main__":
  rand: tf.Tensor = tf.random.uniform([], minval=1, maxval=10, dtype=tf.int32)
  with tf.compat.v1.Session() as sess:
    print([rand.eval() for i in range(20)])

Let me know if I am missing out anything. Thanks!

**Comment by jackshi0912** [comment]
Thank you for this info!

I'm old school graph sessions user. I still think of "Tensors" as a compute graph node that can be evaluated rather than actual values. It will take some time to get used to tensorflow 2.0.

Thanks you!

**Comment by achandraa** [comment]
Sure @jackshi0912 . Please feel free to connect with us with the separate issue if you are stuck anywhere.

**Comment by achandraa** [comment]
Are you satisfied with the resolution of your issue?<br> [Yes](https://docs.google.com/forms/d/e/1FAIpQLSfaP12TRhd9xSxjXZjcZFNXPGk4kc1-qMdv3gc6bEP90vY1ew/viewform?entry.85265664=Yes&entry.2137816233=29340)<br> [No](https://docs.google.com/forms/d/e/1FAIpQLSfaP12TRhd9xSxjXZjcZFNXPGk4kc1-qMdv3gc6bEP90vY1ew/viewform?entry.85265664=No&entry.2137816233=29340)
