### ISSUE TITLE
Markdown format issue in tutorials/load_data/tf_records

### ISSUE THREAD

**Issue by howl-anderson** [tensorflow/tensorflow#29352]
## URL(s) with the issue:

https://www.tensorflow.org/tutorials/load_data/tf_records

## Description of issue (what needs changing):
in the context

> The tf.train.Feature message type can accept one of the following three types (See the [.proto file](https://www.tensorflow.org/tutorials/load_data/(https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/example/feature.proto)%20for%20reference). Most other generic types can be coerced into one of these.

Note: the link of `.proto file` is incorrect. 

It should be 

> The tf.train.Feature message type can accept one of the following three types (See the [.proto file](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/example/feature.proto) for reference). Most other generic types can be coerced into one of these.

**Comment by gadagashwini** [comment]
Closing this issue since the associated PR has been merged. Feel free to reopen if the problem still persists. Thanks!
