### ISSUE TITLE
Tensor traversing

### ISSUE THREAD

**Issue by Arjun8900** [tensorflow/tensorflow#29351]
How to traverse a Tensor? Let's say a tensor is of dims (3, Q, R, S). I want to traverse all three 3D tensor one by one 
0th 3D tensor    (Q,R,S)
1th 3D tensor    (Q,R,S)
2nd 3D tensor   (Q,R,S)
3rd 3D tensor    (Q,R,S)
Any leads will be appreciated.

**Comment by achandraa** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged//tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there and provide better and faster help for such type of issues. Thanks!
