### ISSUE TITLE
[Doc] Broken reference link in basic text classification tutorial

### ISSUE THREAD

**Issue by ivenk** [tensorflow/tensorflow#29358]
# DOC Issue

## URL(s) with the issue:
https://www.tensorflow.org/tutorials/keras/basic_text_classification

## Description of issue (what needs changing):
Broken(Wrong) Link in basic text classification tutorial. Needs to be updated/removed/changed.

### Clear description
In the basic text classification tutorial (imdb reviews) the reference link for pad_sequences points to https://www.tensorflow.org/api_docs/python/tf/keras/preprocessing/sequence/pad_sequences but you get redirected to 
https://www.tensorflow.org/api_docs/python/tf/keras/preprocessing
which is pretty unhelpful. 
+
on 
https://www.tensorflow.org/api_docs/python/tf/keras/preprocessing
the reference link to the keras documentation returns a 404.
So there is not much information to be gained from following that link.

**Comment by wizard-kv** [comment]
The reference link for pad_sequences
https://keras.io/preprocessing/sequence/

**Comment by jvishnuvardhan** [comment]
@ivenk Thanks for finding this broken link. I am closing the issue as it was resolved by the PR https://github.com/tensorflow/docs/pull/629. Thanks!
