### ISSUE TITLE
TFLite: Pruning & Distillation Features

### ISSUE THREAD

**Issue by fzyzcjy** [tensorflow/tensorflow#29360]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using): 1.x, latest
- Are you willing to contribute it (Yes/No): y

**Describe the feature and the current behavior/state.**

In https://www.tensorflow.org/lite/performance/model_optimization, it says that

> 
> Model optimization uses multiple techniques:
> * Reduce parameter count with pruning and structured pruning.
> * Reduce representational precision with quantization.
> * Update the original model topology to a more efficient one with reduced parameters or faster execution. For example, tensor decomposition methods and distillation.
> We support quantization, and are working to add support for other techniques.

Therefore, I wonder roughly *when will the pruning and distillation be supported?* e.g. a month? a year? Thanks very much!

**Will this change the current api? How?**
no

**Who will benefit with this feature?**
**everyone** using tflite to deploy models on mobiles!

**Any Other info.**
n/a

**Comment by alanchiao** [comment]
https://www.tensorflow.org/model_optimization/guide/pruning will be of interest to you. We've started to consolidate our documentation there.

TLDL: pruning is support to get model storage improvements. We're still working on builtin sparsity support in TFLite for latency improvements, as suggested in the roadmap also.

Distillation would be much longer term and I cannot give a good estimate now.

**Comment by fzyzcjy** [comment]
@alanchiao Thanks very much for your reply! So you mean that, for LATENCY improvemnets, pruning does not work? What techniques can further improve latency? Thanks!

**Comment by alanchiao** [comment]
For latency improvements, pruning where it is today doesn't help. It will in the future with additional work on our end.

https://www.tensorflow.org/model_optimization/guide/pruning and https://www.tensorflow.org/lite/performance/best_practices is what's available for now.

Latency will also naturally improve as we optimize the operations (which is actively happening).

**Comment by fzyzcjy** [comment]
@alanchiao Thanks very much! 😄 I wonder how many times can it be faster before it achieves the physical limitation?

**Comment by alanchiao** [comment]
How many times faster before hitting the physical limitation is very much dependent on the model and hardware you're using. All the different techniques include benchmark numbers (including stacking multiple techniques together). I recommend looking at them.

1. A larger model is more amenable to compression/speedups. 
2. Certain models (e.g. LSTMs with gemv) are memory bound and others (e.g. CNNs) are compute bound (bound meaning its the bottleneck). That affects the potential speedups on a certain hardware.
3. Look up details about mobile GPUs (e.g. https://medium.com/tensorflow/tensorflow-lite-now-faster-with-mobile-gpus-developer-preview-e15797e6dee7) and EdgeTPU for potential speedups on accelerators. 
4. More recent versions of CPUs provide special hardware instructions with very significant (e.g. 2x) speedups

**Comment by fzyzcjy** [comment]
Thank you very much for providing so detailed reply!

**Comment by sujoyrc** [comment]
> For latency improvements, pruning where it is today doesn't help. It will in the future with additional work on our end.
> 
> https://www.tensorflow.org/model_optimization/guide/pruning and https://www.tensorflow.org/lite/performance/best_practices is what's available for now.
> 
> Latency will also naturally improve as we optimize the operations (which is actively happening).

When do you think this will be included in tensorflow / TFLite release ? Is there a targeted timeline ? We are planning to do an internal development if this is not expected within this year (2020) based on this.

**Comment by alanchiao** [comment]
@sujoyrc : could you go to this issue and ask the same question? The assignee should communicate where things are.

https://github.com/tensorflow/model-optimization/issues/173

If there's not much of a response, feel free to ping me in this thread.
