### ISSUE TITLE
Unable to build tensorflow from source

### ISSUE THREAD

**Issue by pradeepdw** [tensorflow/tensorflow#29381]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution :Linux Ubuntu 16.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): Source
- TensorFlow version: 1.13.1, 1.14
- Python version: Py3.5 & 3.6
- Installed using virtualenv? pip? conda?: trying to build from source inside docker container.
- Bazel version (if compiling from source): 0.24.0
- GCC/Compiler version (if compiling from source): gcc (Ubuntu 5.4.0-6ubuntu1~16.04.11) 5.4.0 20160609
- CUDA/cuDNN version: 10
- GPU model and memory: GTX 1060 NVIDIA, Tesla T4

**Describe the problem**
a) I downloaded the docker image from https://hub.docker.com/r/tensorflow/tensorflow/ with tags "devel-gpu-py3" and "nightly-gpu-py3". 
b) Inside the docker container i ran ./configure and selected the default paths. Python 3.6, TensorRT, CUDA and CUDNN were all detected.
c) Gave the bazel command below:
-------------------------------------------------------------
root@bad5744dae2b:/tensorflow# bazel build --config=opt --config=cuda //tensorflow/tools/pip_package:build_pip_package
d) i get build failure logs as below.
Starting local Bazel server and connecting to it...
WARNING: The following configs were expanded more than once: [cuda]. For repeatable flags, repeats are counted twice and may lead to unexpected behavior.
DEBUG: /root/.cache/bazel/_bazel_root/68a62076e91007a7908bc42a32e4cff9/external/bazel_tools/tools/cpp/lib_cc_configure.bzl:115:5: 
Auto-Configuration Warning: 'TMP' environment variable is not set, using 'C:\Windows\Temp' as default
Traceback (most recent call last):
  File "/root/.cache/bazel/_bazel_root/68a62076e91007a7908bc42a32e4cff9/external/org_tensorflow/tensorflow/tools/git/gen_git_source.py", line 34, in <module>
    from future.builtins import bytes
ModuleNotFoundError: No module named 'future'
ERROR: /tensorflow/tensorflow/core/BUILD:2750:1: no such package '@local_config_git//': Traceback (most recent call last):
	File "/tensorflow/third_party/git/git_configure.bzl", line 61
		_fail(result.stderr)
	File "/tensorflow/third_party/git/git_configure.bzl", line 14, in _fail
		fail(("%sGit Configuration Error:%s %...)))
Git Configuration Error: Traceback (most recent call last):
  File "/root/.cache/bazel/_bazel_root/68a62076e91007a7908bc42a32e4cff9/external/org_tensorflow/tensorflow/tools/git/gen_git_source.py", line 34, in <module>
    from future.builtins import bytes
ModuleNotFoundError: No module named 'future' and referenced by '//tensorflow/core:version_info_gen'
ERROR: /tensorflow/tensorflow/core/BUILD:2750:1: no such package '@local_config_git//': Traceback (most recent call last):
	File "/tensorflow/third_party/git/git_configure.bzl", line 61
		_fail(result.stderr)
	File "/tensorflow/third_party/git/git_configure.bzl", line 14, in _fail
		fail(("%sGit Configuration Error:%s %...)))
Git Configuration Error: Traceback (most recent call last):
  File "/root/.cache/bazel/_bazel_root/68a62076e91007a7908bc42a32e4cff9/external/org_tensorflow/tensorflow/tools/git/gen_git_source.py", line 34, in <module>
    from future.builtins import bytes
ModuleNotFoundError: No module named 'future'

 and referenced by '//tensorflow/core:version_info_gen'
ERROR: /tensorflow/tensorflow/core/BUILD:2750:1: no such package '@local_config_git//': Traceback (most recent call last):
	File "/tensorflow/third_party/git/git_configure.bzl", line 61
		_fail(result.stderr)
	File "/tensorflow/third_party/git/git_configure.bzl", line 14, in _fail
		fail(("%sGit Configuration Error:%s %...)))
Git Configuration Error: Traceback (most recent call last):
  File "/root/.cache/bazel/_bazel_root/68a62076e91007a7908bc42a32e4cff9/external/org_tensorflow/tensorflow/tools/git/gen_git_source.py", line 34, in <module>
    from future.builtins import bytes
ModuleNotFoundError: No module named 'future'

 and referenced by '//tensorflow/core:version_info_gen'
ERROR: Analysis of target '//tensorflow/tools/pip_package:build_pip_package' failed; build aborted: no such package '@local_config_git//': Traceback (most recent call last):
	File "/tensorflow/third_party/git/git_configure.bzl", line 61
		_fail(result.stderr)
	File "/tensorflow/third_party/git/git_configure.bzl", line 14, in _fail
		fail(("%sGit Configuration Error:%s %...)))
Git Configuration Error: Traceback (most recent call last):
  File "/root/.cache/bazel/_bazel_root/68a62076e91007a7908bc42a32e4cff9/external/org_tensorflow/tensorflow/tools/git/gen_git_source.py", line 34, in <module>
    from future.builtins import bytes
ModuleNotFoundError: No module named 'future'

INFO: Elapsed time: 22.198s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (355 packages loaded, 7796 targets configured)
    currently loading: tensorflow/lite/schema

**Any other info / logs**
NA

**Comment by gadagashwini** [comment]
@pradeepdw Looks future module is not installed, please install future by 
`pip3 install future` 
Let us know if that solves the problem. Thanks!

**Comment by pradeepdw** [comment]
Hi,

I installed "future" as mentioned by you. I still get this below error.

./tensorflow/core/platform/default/logging.h:261:1: note: in expansion of macro 'TF_DEFINE_CHECK_OP_IMPL'
 TF_DEFINE_CHECK_OP_IMPL(Check_EQ,
 ^
**_ERROR: /root/.cache/bazel/_bazel_root/68a62076e91007a7908bc42a32e4cff9/external/nccl_archive/BUILD.bazel:54:1: undeclared inclusion(s) in rule '@nccl_archive//:device_lib':_**
this rule is missing dependency declarations for the following files included by 'external/nccl_archive/src/collectives/device/functions.cu.cc':
  'external/nccl_archive/src/collectives/device/common.h'
Target //tensorflow/tools/pip_package:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 255.662s, Critical Path: 152.97s
INFO: 2095 processes: 2095 local.
FAILED: Build did NOT complete successfully
root@a2fb73b2703e:/tensorflow#

**Comment by pradeepdw** [comment]
I just did the below stuff...
>> git clone https://github.com/tensorflow/tensorflow.git
>>cd tensorflow
>>docker pull tensorflow/tensorflow:devel-gpu-py3
>>docker run --runtime=nvidia -it -w /tensorflow -v $PWD:/tensorflow --name devel_gpu_py3 -e HOST_PERMS="$(id -u):$(id -g)" tensorflow/tensorflow:devel-gpu-py3 bash

In the docker container's prompt,
root@a2fb73b2703e:/tensorflow# ./configure --> make all the configurations
root@a2fb73b2703e:/tensorflow# bazel build --config=opt --config=cuda //tensorflow/tools/pip_package:build_pip_package
Encounterd this error pasted above.

**Comment by gadagashwini** [comment]
@pradeepdw Just to verify, Did you follow the official website to build tensorflow from source using [docker](https://www.tensorflow.org/install/source#docker_linux_builds). Let us know if that resolves your issue. Thanks!

**Comment by pradeepdw** [comment]
Yes, i have followed exactly the same instructions in the link you mentioned. The Docker image i used is "tensorflow/tensorflow:devel-gpu-py3" and the docker command i used is mentioned above.
By the way, i have built 1.12.0 from source (using corresponding docker image) the same way and it works fine every time.

**Comment by angersson** [comment]
@pradeepdw, please try building TensorFlow with the `/tensorflow_src` directory instead. That is the most recent source code version the container was confirmed to build.

**Comment by angersson** [comment]
This issue has become stale, so I'm closing it to keep the tracker clean.
