### ISSUE TITLE
[TF 2.0 API Docs] tf.image.convert_image_dtype

### ISSUE THREAD

**Issue by imransalam** [tensorflow/tensorflow#29386]
## URL(s) with the issue:

https://www.tensorflow.org/api_docs/python/tf/image/convert_image_dtype
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/ops/image_ops_impl.py

### Raises listed and defined

Raises are not listed.

### Usage example

Usage example is not provided

### Submit a pull request?

Yes
https://github.com/tensorflow/tensorflow/pull/29387

**Comment by gadagashwini** [comment]
Closing this issue since the associated PR has been merged. Feel free to reopen if the problem still persists. Thanks!
