### ISSUE TITLE
Missing documentation for executing TF 1.0 frozen and saved models

### ISSUE THREAD

**Issue by msektrier** [tensorflow/tensorflow#29384]
## URL(s) with the issue:

https://www.tensorflow.org/versions/r2.0/api_docs/python/tf

## Description of issue (what needs changing):

I cannot find a documentation how to do the native inference with a frozen or saved model in TF 2.0.

### Clear description

We would like to do inferences/predictions with existing models we trained in Tensorflow 1. Therefore, we have normal frozen and saved models. However, we cannot find a documentation how we can load these models and execute them afterwards. 
We managed to load the [Graph objects](https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/Graph) but the Graph objects do not allow us to do predictions.

In the TFJS project the API is clear to us but in TF 2.0 we struggle a lot.  

### Usage example

Is there a usage example?

```
import os
import tensorflow as tf

# Load the Tensorflow model into memory.
detection_graph = tf.compat.v1.Graph()
with detection_graph.as_default():
    od_graph_def = tf.compat.v1.GraphDef()
    with tf.io.gfile.GFile(PATH_TO_FROZEN_MODEL, 'rb') as fid:
        serialized_graph = fid.read()
        od_graph_def.ParseFromString(serialized_graph)
        tf.import_graph_def(od_graph_def, name='')
```

### Submit a pull request?

many thanks,
Sebastian

**Comment by achandraa** [comment]
Just to verify have you converted 1.x code to 2.0 and then trying to use predictions from saved model ? Please have a look on this [link](https://medium.com/tensorflow/upgrading-your-code-to-tensorflow-2-0-f72c3a4d83b5) to get some help on code upgradation and this [link](https://www.tensorflow.org/guide/saved_model#build_and_load_a_savedmodel) for building and loading a saved model. Let us know if that helps. Thanks!

**Comment by achandraa** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
