### ISSUE TITLE
Tensorflow.image.resize_images not upgraded

### ISSUE THREAD

**Issue by kriskorrel-cw** [tensorflow/tensorflow#29380]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): MacOS
- TensorFlow installed from (source or binary): pip
- TensorFlow version (use command below): 2.0.0a0
- Python version: 3.7.3

**Describe the current behavior**
The function `tensorflow.image.resize_images()` is not upgraded with the tf_upgrade_v2 script. It is not replaced with any working function in tf2.

**Describe the expected behavior**
The function to be converted to `tf.image.resize()`?

**Code to reproduce the issue**
Upgrade the following code with tf_upgrade_v2 and run it in tensorflow 2.0
```python
import tensorflow

tensorflow.image.resize_images()
```

**Comment by gadagashwini** [comment]
@kriskorrel-cw The function tensorflow.image.resize_images() has been upgraded with tf.image.resize() in TF 2.0. For more information refer [this](https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/image/resize). Thanks!

**Comment by kriskorrel-cw** [comment]
Yes, I say that. But shouldn't `tf_upgrade_v2` then automatically convert to this? Now I run into errors when I upgrade my project to TensorFlow 2.0, since the function is not automatically converted.

**Comment by ymodak** [comment]
The **tf_upgrade_v2** converter tool looks for ```tf``` keyword.
Following changes to your code should do the trick,
```python
import tensorflow as tf
tf.image.resize_images()
```
Output:
```python
INFO line 12:0: Renamed 'tf.image.resize_images' to 'tf.image.resize'
TensorFlow 2.0 Upgrade Script
-----------------------------
Converted 1 files
Detected 0 issues that require attention
--------------------------------------------------------------------------------


Make sure to read the detailed log 'report.txt'
```

**Comment by kriskorrel-cw** [comment]
Ah okay, but that is still very confusing.
Why wouldn't tensorflow upgrade tensorflow imports? Tf is only an (unofficial) shorthand for tensorflow that is commonly used, but there is nothing wrong with just `import tensorflow`.

**Comment by ymodak** [comment]
This is a limitation of the converter tool as of now. However making it more robust to cases like these is on our road map. Please use import tensorflow as tf with upgrade script. Thanks!
