### ISSUE TITLE
Is there any way to get the size of the TFRecordDataset?

### ISSUE THREAD

**Issue by RitchieAlpha** [tensorflow/tensorflow#29385]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using): tensorflow-2.0.0-alpha0
- Are you willing to contribute it (Yes/No): Yes

**Describe the feature and the current behavior/state.**
I get some tfrecord files from someone. when I try to train the network with tf.keras.Model.fit(), it needs to pass a parameter "steps_per_train", but I don't know the size and how many data was saved in the tfrecord files. I have read the document of tensorflow2.0 but I find nothing help, so is there any way to get the size of the TFRecordDataset? Thank u

**Will this change the current api? How?**
No, it won't change the current api. It may add an attribute with a "get" function.

**Who will benefit with this feature?**
Every who need to know the size of tfrecord dataset

**Any Other info.**

**Comment by jsimsa** [comment]
No, the only way to find out the cardinality of TFRecordDataset is to enumerate all of its elements.
