### ISSUE TITLE
[tf2.0] decode numpy array with bytes format stored in tensor

### ISSUE THREAD

**Issue by jinfagang** [tensorflow/tensorflow#29396]
I can not found any documentation about this. 

I saved some numpy arrays into tfrecord, it stored as bytes (using np.array().to_bytes() method)

When read it back, there were no way to decode that bytes back to numpy.

Anyone knows how to solve it?

**Comment by jvishnuvardhan** [comment]
@jinfagang tensor.numpy() --> gives numpy array of the given tensor in TF2.0.
```python
a=tf.constant([1,2,3,4,5])
a # <tf.Tensor: id=32, shape=(5,), dtype=int32, numpy=array([1, 2, 3, 4, 5], dtype=int32)>
a.numpy() # array([1, 2, 3, 4, 5], dtype=int32)
```
This is not Build/Installation or Bug/Performance issue. Please post this kind of support questions at [Stackoverflow](https://stackoverflow.com/questions/tagged/tensorflow). There is a big community to support and learn from your questions. GitHub is mainly for addressing bugs in installation and performance. Thanks!

**Comment by jvishnuvardhan** [comment]
I think it was resolved. I am closing the issue. But, please let me know if I'm mistaken. Thanks!
