### ISSUE TITLE
[2.0alpha0 AutoGraph] tf.function does not automatically transform nested class methods

### ISSUE THREAD

**Issue by llan-ml** [tensorflow/tensorflow#29393]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.0.0alpha0
- Python version: 3.6.5

**Describe the current behavior**
When we define multiple methods for a class and only decorate one of them with `@tf.function`, the nested methods are not automatically transformed and some errors raise.

**Describe the expected behavior**
We only need decorate the outermost method.

**Code to reproduce the issue**
<pre>
# -*- coding: utf-8 -*-
# @Author  : Lin Lan (ryan.linlan@gmail.com)

from __future__ import absolute_import
from __future__ import division
from __future__ import print_function

import tensorflow as tf

class Foo(tf.keras.Model):
    def __init__(self):
        super(Foo, self).__init__()
        self.dense = tf.keras.layers.Dense(20)
        self.embeddings = tf.Variable(tf.random.normal((100, 5)), dtype=tf.float32)

    @tf.function
    def call(self, inputs):
        embeddings = tf.nn.embedding_lookup(
            self.embeddings, inputs)
        return self._inner(embeddings)

    # @tf.function
    def _inner(self, embeddings):
        batch = tf.shape(embeddings)[0]
        ta = tf.TensorArray(tf.float32, size=batch)
        for i in tf.range(batch):
            this = self.dense(embeddings[i][tf.newaxis, :])
            ta = ta.write(i, this)
        return ta.stack()

foo = Foo()
res = foo([0, 2, 4, 6, 8])
</pre>

**Other info / logs**
`TypeError: Tensor objects are only iterable when eager execution is enabled. To iterate over this tensor use tf.map_fn.`

Also decorating the method `_inner` eliminate the error.

**Comment by llan-ml** [comment]
It took me a lot of time to find this bug (or intended behavior?) from my original code. It would be better to add a warning in the doc of `tf.function`.

**Comment by achandraa** [comment]
Have tried with TF version 2.0.0-alpha on Colab and was able to reproduce the issue as mentioned in the description.

**Comment by alextp** [comment]
You shouldn't need to decorate self._inner. @mdanatg why isn't it being caught here?

**Comment by mdanatg** [comment]
This is a bug. We'll have it fixed in the nightly soon.

**Comment by llan-ml** [comment]
Hi @mdanatg Any updates regarding to this issue?

**Comment by mdanatg** [comment]
Yep! It will likely be fixed today, or sometime next week at the latest.
