### ISSUE TITLE
Enable GPU support for Object Detection Sample Android Tflite App 

### ISSUE THREAD

**Issue by Gmrevo** [tensorflow/tensorflow#29390]
The [official documentation](https://www.tensorflow.org/lite/performance/gpu#supported_models_and_ops) suggests `mobile_ssd_v2_float_coco.tflite` model for enabling GPU delegate, but after analyzing the Model with [Netron,](https://electronjs.org/apps/netron) ( visualization tool to help identify how the output tensors differ.)
`mobile_ssd_v2_float_coco.tflite`
OUTPUT:
raw_outputs/box_encodings
id: raw_outputs/box_encodings
type: float32[1,2034,4]
raw_outputs/class_predictions
id: raw_outputs/class_predictions
type: float32[1,2034,91]

Whereas the default model `detect.tflite` used in the demo has 4 different parameters.
OUTPUT: 
TFLite_Detection_PostProcess
id: TFLite_Detection_PostProcess
type: float32
TFLite_Detection_PostProcess:1
id: TFLite_Detection_PostProcess:1
type: float32
TFLite_Detection_PostProcess:2
id: TFLite_Detection_PostProcess:2
type: float32
TFLite_Detection_PostProcess:3
id: TFLite_Detection_PostProcess:3
type: float32
ie for **Location, Classes, Scores, Number and detections**

**How can we use `mobile_ssd_v2_float_coco.tflite`or any model to get enable GPU with Object Detection, Please suggest?**

**Comment by achandraa** [comment]
Please help us to get information like what platform you are using. Also include the TensorFlow version and other relevant information. If you are unclear. please use the Template
(https://github.com/tensorflow/tensorflow/issues/new/choose).

We ask for this in the issue submission template, because it is really difficult to help without that information. Thanks!

**Comment by achandraa** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
