### ISSUE TITLE
Rewrite git history to purge large model files

### ISSUE THREAD

**Issue by cesarsalgado** [tensorflow/tensorflow#294]
As the following commit comment https://github.com/tensorflow/tensorflow/commit/7e1e25b16ba8d01edf6d53d442cac4f93deda2c1  mentioned, I think this would be a good idea. There is no reason to keep this burden in the history.

**Comment by vrv** [comment]
This was done, sort of.  We removed the large model files and some animated gifs, then rewrote the history.  Unfortunately, despite some checks on our side, the animated gifs made their way back in a more recent commit. :(

The repo is a lot smaller without the models in the history, and we don't want to rewrite the history again.  We'll live with our 20-30MiB mistake.
