### ISSUE TITLE
[TF 2.0 API Docs] tf.io.decode_json_example

### ISSUE THREAD

**Issue by SimiCode** [tensorflow/tensorflow#29401]
**Existing URLs containing the issue:**
https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/io/decode_json_example

### Description of issue (what needs changing):
**Correct Links**
The link to the python script where the function is defined is inactive. 
Wrong: python/ops/gen_parsing_ops.py.
Correct: (The file mentioned here is not in the repo)

**Usage Example**
No usage example is provided.
Use Cases: The documentation does not define when to use and when not to use the symbol.

**Raises Listed and Defined**
Errors are not defined.

**Comment by jvishnuvardhan** [comment]
I think this was resolved with the update docs. https://www.tensorflow.org/api_docs/python/tf/io/decode_json_example

In the update docs, the links are active and working. Also, provided an example.

I am closing this issue as this was resolved. Thanks!
