### ISSUE TITLE
[TF 2.0 API Docs] tf.keras.backend.maximum

### ISSUE THREAD

**Issue by KengoWada** [tensorflow/tensorflow#29408]
## URL(s) with the issue:

Please provide a link to the documentation entry, for example:
https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/keras/backend/maximum

### Clear description

The description is not clear enough.

### Correct links

The links are okay.

### Parameters defined

The parameters are defined.

### Returns defined

The return values are defined.

### Raises listed and defined

Errors are not defined or listed.

### Usage example

There is no usage example.

### Request visuals, if applicable

There are no visuals.

### Submit a pull request?

No.

**Comment by lufol** [comment]
Hi @KengoWada could you please fill out the form you submitted above by replacing the non-bold text with you text?

**Comment by KengoWada** [comment]
Sorry about that. I have updated the form. Thank you.

**Comment by lufol** [comment]
I just created a pull-request [here](https://github.com/tensorflow/tensorflow/pull/29435).

**Comment by gadagashwini** [comment]
@KengoWada,
Closing this issue since the associated PR has been merged. Feel free to reopen if the problem still persists. Thanks!
