### ISSUE TITLE
https://www.tensorflow.org/versions/api_docs/python/tf link does not exist

### ISSUE THREAD

**Issue by anestisdotpy** [tensorflow/tensorflow#29400]
## URL(s) with the issue: 
https://www.tensorflow.org/versions

### Clear Description 

When someone is in [this page](https://www.tensorflow.org/versions) , clicking on the bullet point `r1.13 (stable)` redirects to a `404 not found page`.

### Correct links

The bullet point targets [here](https://www.tensorflow.org/versions/api_docs/python/tf) while it should target [here](https://www.tensorflow.org/api_docs/python/tf). 

### Submit a pull request?

I tried to fix it but I cannot find where this link ref is stated. If someone could point me in the right direction I could fix it, otherwise someone else could do it.

**Comment by lamberta** [comment]
Thanks. That link should point here: https://www.tensorflow.org/api_docs/python/tf

But it's losing the left nav---just like when you select it API from the dropdown and select 1.13

**Comment by anestisdotpy** [comment]
Looks fixed now so the issue can be closed I guess.

**Comment by lamberta** [comment]
Working on it :)
Fixing leftnav issue now

**Comment by anestisdotpy** [comment]
Oh okay. The error does not exist for me anymore so I thought someone has fixed it already.

**Comment by ymodak** [comment]
Closing this issue since its resolved. Thanks!
