### ISSUE TITLE
[TF 2.0 API Docs] tf.io.decode_base64

### ISSUE THREAD

**Issue by Emanuz** [tensorflow/tensorflow#29402]
## Existing Url with the issue:
https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/io/decode_base64

### Clear description

For example, why should someone use this method? How is it useful?

### Correct links
The link to the python script where the function is define is inactive
Wrong: python/ops/gen_string_ops.py
Correct (The file is not mentioned in the repo)
### Parameters defined

Are all parameters defined and formatted correctly?

### Returns defined

Are return values defined?

### Raises listed and defined

Are the errors defined? For example,
https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/feature_column/categorical_columErrors are not defined

### Usage example

No usage example provided
Use case: (The documentation does not define how to use, when to use the symbol)

**Comment by kumariko** [comment]
@Emanuz We are checking to see if you still need help on this issue. Could you please have a look on the [link1](https://www.tensorflow.org/api_docs/python/tf/io/decode_base64) , [link2](https://stackoverflow.com/questions/48910253/why-would-tensorflow-decode-base64-fail-due-to-invalid-character-but-base64-b64?rq=1) and let us know if it helps? Thanks
