### ISSUE TITLE
[TF 2.0 API Docs] tf.data.experimental.make_saveable_from_iterator

### ISSUE THREAD

**Issue by Rwothoromo** [tensorflow/tensorflow#29406]
## URL(s) with the issue:

https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/data/experimental/make_saveable_from_iterator

### Returns defined

The returns section is missing.

### Raises listed and defined

Raises are neither listed nor defined.

**Comment by KabirKwatra** [comment]
Issue can be closed

**Comment by achandraa** [comment]
Closing the issue since its been merged. Thanks!
