### ISSUE TITLE
[TF 2.0a0] fail to use If within GradientTape which is within tf.range loop.

### ISSUE THREAD

**Issue by llan-ml** [tensorflow/tensorflow#29427]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.0.0alpha0
- Python version: 3.6.5

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.
<pre>
# -*- coding: utf-8 -*-
# @Author  : Lin Lan (ryan.linlan@gmail.com)

from __future__ import absolute_import
from __future__ import division
from __future__ import print_function

import numpy as np
import tensorflow as tf

class Model(tf.keras.Model):
    def __init__(self):
        super(Model, self).__init__()
        self.dense1 = tf.keras.layers.Dense(100)
        self.dense2 = tf.keras.layers.Dense(100)
        self.dense3 = tf.keras.layers.Dense(100)

    def call(self, inputs):
        x = self.dense1(inputs)
        x = self.dense2(x)
        outputs = self.dense3(x)
        return outputs

model = Model()
optimizer = tf.keras.optimizers.SGD()

@tf.function
def train(data):
    batch_size = data.shape[0]
    grads = tf.TensorArray(tf.float32, size=batch_size)
    for i in tf.range(batch_size):
        with tf.GradientTape() as tape:
            if True:
                y = model(data[i][tf.newaxis, :])
                loss = tf.reduce_mean(tf.square(y))
        this_grads = tape.gradient(loss, model.trainable_weights)
        this_grads = tf.concat([tf.reshape(g, [-1]) for g in this_grads], axis=0)
        grads = grads.write(i, this_grads)
    return grads.stack()

x = np.random.rand(10, 100).astype(np.float32)
print(train(x))
</pre>
**Other info / logs**
`ValueError: TensorFlow requires that the following symbols must be initialized to a Tensor, Variable or TensorArray before the loop: ('loss',)`.

If we comment `if True`, the code works.

**Comment by llan-ml** [comment]
I found that interchanging `with ... as tape` and `if True` also fails, i.e.,
<pre>
...
for i in tf.range(batch_size):
  if True:
    with tf.GradientTape() as tape:
...
</pre>

**Comment by hegman12** [comment]
Hi,
what will happen if your "IF" condition evaluated to false? it will never create loss tensor. I think that is why it did not work. Below code works.

```
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function

import numpy as np
import tensorflow as tf


class Model(tf.keras.Model):
    def __init__(self):
        super(Model, self).__init__()
        self.dense1 = tf.keras.layers.Dense(100)
        self.dense2 = tf.keras.layers.Dense(100)
        self.dense3 = tf.keras.layers.Dense(100)

    def call(self, inputs):
        x = self.dense1(inputs)
        x = self.dense2(x)
        outputs = self.dense3(x)
        return outputs


model = Model()
optimizer = tf.keras.optimizers.SGD()


@tf.function
def train(data):
    batch_size = data.shape[0]
    grads = tf.TensorArray(tf.float32, size=batch_size)
    for i in tf.range(batch_size):
        with tf.GradientTape() as tape:
            #loss=tf.constant(1)
            if True:
                y = model(data[i][tf.newaxis, :])
                loss = tf.reduce_mean(tf.square(y))
            else:
                loss=tf.constant(1)
        this_grads = tape.gradient(loss, model.trainable_weights)
        this_grads = tf.concat([tf.reshape(g, [-1]) for g in this_grads], axis=0)
        grads = grads.write(i, this_grads)
    return grads.stack()


x = np.random.rand(10, 100).astype(np.float32)
print(train(x))
```

**Comment by llan-ml** [comment]
@hegman12 I get it! Thanks for your attention. This is not a tf bug, and I'll close this issue.
