### ISSUE TITLE
failed to pip install tensorflow gpu on win10 and Could not install packages due to an EnvironmentError

### ISSUE THREAD

**Issue by zhilonglu** [tensorflow/tensorflow#29428]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):win10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version:tf_nightly_gpu_2.0_preview
- Python version:python 3.6.3
- Installed using virtualenv? pip? conda?:pip conda
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:  cuda_10.0.130_411.31_win10.exe  cudnn-10.0-windows10-x64-v7.5.0.56.zip
- GPU model and memory:GTX 1050

**Describe the problem**
I am trying to install tensorflow gpu on win10,but faild after many times.
I also try to use conda,but failed. It takes me alomost one day to figure it out but failed finnaly,
So upset and come here for help,thank you!
**Provide the exact sequence of commands / steps that you executed before running into the problem**
pip install tf_nightly_gpu_2.0_preview-2.0.0.dev20190604-cp36-cp36m-win_amd64.whl

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.
The error occurs when pip install tf-nightly-gpu-2.0-preview
Could not install packages due to an EnvironmentError: [Errno 2] No such file or directory: 'C:\\Users\\XXXX\\AppData\\Local\\Temp\\pip-install-9z06414_\\tf-nightly-gpu-2.0-preview\\tf_nightly_gpu_2.0_preview-2.0.0.dev20190604.data/purelib/tensorflow/include/tensorflow/include/external/eigen_archive/Eigen/src/Core/products/GeneralMatrixMatrixTriangular_BLAS.h'

**Comment by mmv** [comment]
`pip` is trying to write a temporary file at `C:\Users\XXXX\AppData\Local\Temp\pip-install-9z06414_\tf-nightly-gpu-2.0-preview\tf_nightly_gpu_2.0_preview-2.0.0.dev20190604.data/purelib/tensorflow/include/tensorflow/include/external/eigen_archive/Eigen/src/Core/products/GeneralMatrixMatrixTriangular_BLAS.h` which has 260 characters. If the `XXXX` for your username is different, this means you'll be over 260 characters. By default, this hits a limit in Windows APIs, which exists for compatibility with previous versions, but isn't really needed.

You can see on [Windows documentation](https://docs.microsoft.com/en-us/windows/desktop/fileio/naming-a-file#maximum-path-length-limitation) instructions on how to disable that limit, which should solve your problem.

**Comment by ymodak** [comment]
duplicate #24705
