### ISSUE TITLE
Unittest and test_session interaction

### ISSUE THREAD

**Issue by danieltudosiu** [tensorflow/tensorflow#29439]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 1.12.1 / 1.13.1 / 1.14.0rc0
- Python version: 3.5 / 3.6 / 3.7
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: 10.0.130
- GPU model and memory: 7.5.0

Environment capture available at: https://pastebin.com/N26BUeSy

**Describe the current behavior**
Additional "ghost" tests are being run but skipped when using unittest with Tensorflow TestCase class. This behavior is present in 1.12.1. When upgrading to 1.13.1 or 1.14.0rc0, the tests are being skipped entirely as the "ghost" test is in regards to the test_session method that you have within the tensorflow.python.framework.testutils and unittest believes that the tests are not actually tests.

**Describe the expected behavior**
No "ghost" tests should be run at all in 1.12.1 and the tests work in 1.13.1 and 1.14.0rc0.

**Code to reproduce the issue**
```
import tensorflow as tf
import numpy as np
import unittest

print(tf.__version__)

def get_entry_np(t, indices_d1, indices_d2, batch_size):
    result = np.zeros(batch_size)
    for i in range(batch_size):
        result[i] = t[i, indices_d1[i], indices_d2[i]]
    return result
    

def get_entry_tf(t, indices_d1, indices_d2, batch_size):
    indices = tf.stack([tf.range(batch_size), indices_d1, indices_d2], axis=1)
    return tf.gather_nd(t, indices)

## Start of region of interest
# Please enable and disable this region with Tensorflow 1.12.1 and then with 1.13.1 or 1.14.0rc0 and the behaviour will be seen   
try:
    delattr(tf.test.TestCase,'test_session')
except AttributeError:
    pass

class OwnTestCase(tf.test.TestCase):
    pass
## End of region of interest
class TestCaseTest(tf.test.TestCase):
        
    def test_get_entry(self):
        success = True
        for _ in range(10):
            # sample input
            batch_size, d1, d2 = map(int, np.random.randint(low=2, high=100, size=3))
            test_input = np.random.random([batch_size, d1, d2])
            test_indices_d1 = np.random.randint(low=0, high=d1-1, size=[batch_size])
            test_indices_d2 = np.random.randint(low=0, high=d2-1, size=[batch_size])
            # evaluate the numpy version
            test_result = get_entry_np(test_input, test_indices_d1, test_indices_d2, batch_size)
            # evaluate the tensorflow version
            with self.cached_session() as sess:
                tf_input = tf.constant(test_input, dtype=tf.float32)
                tf_indices_d1 = tf.constant(test_indices_d1, dtype=tf.int32)
                tf_indices_d2 = tf.constant(test_indices_d2, dtype=tf.int32)
                tf_result = get_entry_tf(tf_input, tf_indices_d1, tf_indices_d2, batch_size)
                tf_result = sess.run(tf_result)
                # check that outputs are similar
                success = success and np.allclose(test_result, tf_result)
    
        self.assertEqual(success, True)
```

**Comment by ericspod** [comment]
To expand on this, unittest is search for method names and finds tf.test.TestCast.test_session. This is treated as a test which is erroneous and so gets logged as "Not a test.". However it also causes actual tests to be ignored as well in this manner. Deleting the method entirely allows tests to run as the above code shows.

**Comment by alextp** [comment]
Why would it cause actual tests to be ignored? I'm confused.

**Comment by ericspod** [comment]
What appears to be happening is the unittest framework is being used to search for methods beginning with "test". The test_session method is found to be one of these erroneously and causes tests to be skipped. We haven't been able to figure out why this wasn't a problem in the past. Our tests in TF 1.12 work correctly but having upgraded to 1.13 (and then tried 1.14 betas) they acquire this skipping behaviour.

**Comment by alextp** [comment]
@gunan do you know who maintains TestCase?

**Comment by gunan** [comment]
I have been aware of the issue around "test_session", but afaik it has been that way for a very very long time. Here is the line that skips "test_session"
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/framework/test_util.py#L1747

A little investigation showed that we moved around the "skip" logic recently with this commit:
https://github.com/tensorflow/tensorflow/commit/f9f50b6cf831cdfef15d952152f43ba6542a14ad
And I think that may be why you are seeing your tests that have the name ".test_session" skipped.
Pinging @eddie-zhou @mrry for the change.

For the resolution, I think this is just the fallout from a small bad design decision we had within TensorFlowTestCase. We should document this behaviour to avoid the pain you went through. But my recommendation for the resolution would be to rename the tests, but have this behaviour documented. Maybe instead of "Not a test" the message can say "due to `test_session` method in tensorflowTestCase, all tests with this name are skipped. Please rename your tests"?

**Comment by eddie-zhou** [comment]
I believe @gunan is correct, and his suggestion seems reasonable.

**Comment by ericspod** [comment]
We can try something like that. We're changing tests around a bit anyway so we can do that. The issue we noticed was that tests were getting skipped that didn't even use test_session nor have that in their names at all. We found it hard to correlate behaviour with what methods we were calling. Our solution of deleting test_session from the class works but of course is horrid. Thanks for the help.

**Comment by gunan** [comment]
I agree with you that it is not a great solution.
Thankfully, test_session is deprecated and is planned to be removed. At which point we can remove it completely from the TestCase class and remove the hack. Sorry for the inconvenience!

**Comment by wookayin** [comment]
For someone who might find this in the future by Googling:

If you are using pytest, you could write a `conftest.py` (in the project root, etc.) file including the following hook, to have `test_session`s **not collected** rather than *skipped*:

```python
def pytest_collection_modifyitems(session, config, items):
  """Do not collect TensorFlowTestCase.test_sesion as a test case."""
  items[:] = [item for item in items if not (
    item.location[0].endswith('test_util.py') and item.name == 'test_session')]
```

Reference: https://docs.pytest.org/en/latest/reference.html

**Comment by gunan** [comment]
Unfortunately, TF is not using pytest, our testing libraries are derived from [python unittest](https://docs.python.org/2/library/unittest.html). So I do not think the above solution will work in this case.

**Comment by bhavints** [comment]
> What appears to be happening is the unittest framework is being used to search for methods beginning with "test". The test_session method is found to be one of these erroneously and causes tests to be skipped. We haven't been able to figure out why this wasn't a problem in the past. Our tests in TF 1.12 work correctly but having upgraded to 1.13 (and then tried 1.14 rc0) they acquire this skipping behaviour.

Yes this appears to have happened
