### ISSUE TITLE
Initializing a tf.Variable with he_normal

### ISSUE THREAD

**Issue by sayakpaul** [tensorflow/tensorflow#29430]
Hi. I am trying to implement [NALU](https://arxiv.org/abs/1808.00508) using TF 2.0. I am on MacBook Air 2015 (CPU) and TensorFlow version is `2.0.0-alpha0`. 

So, I was looking for ways to initialize the `W_hat` parameter using _He Initialization_ in TensorFlow 2.0. 

Things I have tried:
- ```python 
    W_hat = tf.Variable(initial_value=tf.initializers.he_normal(),                        
    trainable=True, 
    name='W_hat', shape=(2,1))
   ```
  👆results in - 
    ```
     
    TypeError                                 Traceback (most recent call last)
    <ipython-input-25-b78fa0d268a9> in <module>
      1 tf.Variable(initial_value=tf.initializers.he_normal(),                        
      2             trainable=True,
      ----> 3             name='W_hat', shape=(2,1))

     /miniconda3/lib/python3.7/site-packages/tensorflow/python/ops/variables.py in __call__(cls, 
    *args, **kwargs)
    212       return cls._variable_v1_call(*args, **kwargs)
    213     elif cls is Variable:
     --> 214       return cls._variable_v2_call(*args, **kwargs)
    215     else:
    216       return super(VariableMetaclass, cls).__call__(*args, **kwargs)

    TypeError: _variable_v2_call() got an unexpected keyword argument 'shape'
   ```

- The second try was bound to produce the error I think but anyhow I did it just to be sure - 
   ```python
         W_hat = tf.Variable(initial_value=tf.initializers.he_normal(),                        
         trainable=True, 
          name='W_hat')
   ```
   The trace for this one is attached. 
   [trace.txt.zip](https://github.com/tensorflow/tensorflow/files/3256057/trace.txt.zip)

Would be great to see suggestions.

**Comment by alextp** [comment]
The error about shape missing is probably just because the shape argument to tf.Variable was recently introduced into the TF API and you're running a version before that.

**Comment by sayakpaul** [comment]
Both the snippets were written using the 2.0 variant only.

**Comment by sayakpaul** [comment]
I should have searched a bit more before raising the issue. It was really simple of a solution:
```python
shape = (2,)
initializer = tf.initializers.he_normal()
var = tf.Variable(initializer(shape=shape))
```
