### ISSUE TITLE
Extracting features from mixed layer in inception-v3 

### ISSUE THREAD

**Issue by kyrs** [tensorflow/tensorflow#2943]
Hi,
For my project I need to extract the features from the mixed layer in inception-v3. But, for doing so I need the name of various tensor layer.
as far as I know 
`pool_1:0 correspond to (35X35X192) feature matrix`
`pool_3:0 correspond to (2048,) feature matrix`
`conv_1:0 correspond to ((147X147X32)) feature matrix`
`conv_2:0 correspond to (147X147X64) feature matrix`
`conv_3:0 correspond to (73X73X80) feature matrix`  
`conv_4:0 correspond to (71X71X192) feature matrix`

I am interested in final mixed layer [8X8X2048] `mixed_10` as mentioned in `model.txt` Can you please tell me how to extract this layer

**Comment by prb12** [comment]
This is a question better suited for StackOverflow. Please ask it there and tag it with the `tensorflow` tag.
