### ISSUE TITLE
Error using deepbinner:  ImportError: libcuda.so.1: cannot open shared object file: No such   file or directory   Failed to load the native TensorFlow runtime.

### ISSUE THREAD

**Issue by gmercadov** [tensorflow/tensorflow#29436]
Hello.
I'm trying to use deepbinner software for demultiplexing native barcodes that separate by patients after MinION sequencing. I've obtained this error. Has anyone got any idea about what's happening? Thank you!

`(Deepbinner) [ugm@et8 Lecturas_30_05_2019]$ deepbinner classify  
--native fast5_pass/ > classifications
Using TensorFlow backend.
Traceback (most recent call last):
   File  
"/programas/anaconda/3-4.4.0/envs/Deepbinner/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in  
<module>
     from tensorflow.python.pywrap_tensorflow_internal import *
   File  
"/programas/anaconda/3-4.4.0/envs/Deepbinner/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in  
<module>
     _pywrap_tensorflow_internal = swig_import_helper()
   File  
"/programas/anaconda/3-4.4.0/envs/Deepbinner/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in  
swig_import_helper
     _mod = imp.load_module('_pywrap_tensorflow_internal', fp,  
pathname, description)
   File  
"/programas/anaconda/3-4.4.0/envs/Deepbinner/lib/python3.6/imp.py",  
line 243, in load_module
     return load_dynamic(name, filename, file)
   File  
"/programas/anaconda/3-4.4.0/envs/Deepbinner/lib/python3.6/imp.py",  
line 343, in load_dynamic
     return _load(spec)
ImportError: libcuda.so.1: cannot open shared object file: No such  
file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
   File "/programas/anaconda/3-4.4.0/envs/Deepbinner/bin/deepbinner",  
line 10, in <module>
     sys.exit(main())
   File  
"/programas/anaconda/3-4.4.0/envs/Deepbinner/lib/python3.6/site-packages/deepbinner/deepbinner.py", line 59, in  
main
     from .classify import classify
   File  
"/programas/anaconda/3-4.4.0/envs/Deepbinner/lib/python3.6/site-packages/deepbinner/classify.py", line 24, in  
<module>
     from keras.models import load_model
   File  
"/programas/anaconda/3-4.4.0/envs/Deepbinner/lib/python3.6/site-packages/keras/__init__.py", line 3, in  
<module>
     from . import utils
   File  
"/programas/anaconda/3-4.4.0/envs/Deepbinner/lib/python3.6/site-packages/keras/utils/__init__.py", line 6, in  
<module>
     from . import conv_utils
   File  
"/programas/anaconda/3-4.4.0/envs/Deepbinner/lib/python3.6/site-packages/keras/utils/conv_utils.py", line 9, in  
<module>
     from .. import backend as K
   File  
"/programas/anaconda/3-4.4.0/envs/Deepbinner/lib/python3.6/site-packages/keras/backend/__init__.py", line 89, in  
<module>
     from .tensorflow_backend import *
   File  
"/programas/anaconda/3-4.4.0/envs/Deepbinner/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py", line 5, in  
<module>
     import tensorflow as tf
   File  
"/programas/anaconda/3-4.4.0/envs/Deepbinner/lib/python3.6/site-packages/tensorflow/__init__.py", line 24, in  
<module>
     from tensorflow.python import pywrap_tensorflow  # pylint:  
disable=unused-import
   File  
"/programas/anaconda/3-4.4.0/envs/Deepbinner/lib/python3.6/site-packages/tensorflow/python/__init__.py", line 49, in  
<module>
     from tensorflow.python import pywrap_tensorflow
   File  
"/programas/anaconda/3-4.4.0/envs/Deepbinner/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 74, in  
<module>
     raise ImportError(msg)
ImportError: Traceback (most recent call last):
   File  
"/programas/anaconda/3-4.4.0/envs/Deepbinner/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in  
<module>
     from tensorflow.python.pywrap_tensorflow_internal import *
   File  
"/programas/anaconda/3-4.4.0/envs/Deepbinner/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in  
<module>
     _pywrap_tensorflow_internal = swig_import_helper()
   File  
"/programas/anaconda/3-4.4.0/envs/Deepbinner/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in  
swig_import_helper
     _mod = imp.load_module('_pywrap_tensorflow_internal', fp,  
pathname, description)
   File  
"/programas/anaconda/3-4.4.0/envs/Deepbinner/lib/python3.6/imp.py",  
line 243, in load_module
     return load_dynamic(name, filename, file)
   File  
"/programas/anaconda/3-4.4.0/envs/Deepbinner/lib/python3.6/imp.py",  
line 343, in load_dynamic
     return _load(spec)
ImportError: libcuda.so.1: cannot open shared object file: No such  
file or directory

Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.`

**Comment by ymodak** [comment]
Please provide following information; Thanks!
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version:
- Python version:
- Installed using virtualenv? pip? conda?:
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:



**Describe the problem**

**Provide the exact sequence of commands / steps that you executed before running into the problem**

**Comment by ymodak** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
