### ISSUE TITLE
TFLite: Slow float global pooling performance

### ISSUE THREAD

**Issue by sbsky** [tensorflow/tensorflow#29443]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: Raspberry pi, however issue is reproducible on desktop
- TensorFlow installed from (source or binary): Source
- TensorFlow version (use command below): v1.12.1-3185-g1a4a0aee1f 1.13.1
- Python version: 3.6
- CUDA/cuDNN version: -
- GPU model and memory: -

Using tensor flow lite, global av/max pooling is much slower on float than it is for quantised models.  Using tensor flow 2.0 nightly, together with the instructions here:
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/tutorials/post_training_integer_quant.ipynb

Using the following tf 2.0 code & tflite profiling tool generates the following outputs:

Float
```python
import tensorflow as tf

out_name = 'mobilenet_v2.tflite'
print(tf.version.GIT_VERSION, tf.version.VERSION)

input = tf.keras.layers.Input(shape=(32, 32, 3,))
x = tf.keras.layers.Conv2D(filters=256, kernel_size=(1, 1))(input)
x = tf.keras.layers.Activation('relu')(x)
x = tf.keras.layers.GlobalAveragePooling2D()(x)
model = tf.keras.Model(inputs=[input], outputs=[x])

model.summary()

converter = tf.lite.TFLiteConverter.from_keras_model(model)
tflite_model = converter.convert()
open(out_name, "wb").write(tflite_model)`


============================== Summary by node type ==============================
            [Node type]   [count]   [avg ms]     [avg %]     [cdf %]   [mem KB] [times called]
                    MEAN         1     1.774     91.774%     91.774%     0.000         1
                CONV_2D         1     0.159     8.226%   100.000%     0.000         1

```
Quantized
```python
import tensorflow as tf

out_name = 'mobilenet_v2.tflite'
print(tf.version.GIT_VERSION, tf.version.VERSION)

input = tf.keras.layers.Input(shape=(32, 32, 3,))
x = tf.keras.layers.Conv2D(filters=256, kernel_size=(1, 1))(input)
x = tf.keras.layers.Activation('relu')(x)
x = tf.keras.layers.GlobalAveragePooling2D()(x)
model = tf.keras.Model(inputs=[input], outputs=[x])

model.summary()

converter = tf.lite.TFLiteConverter.from_keras_model(model)
converter.optimizations = [tf.lite.Optimize.DEFAULT]

cifar_train, _ = tf.keras.datasets.cifar10.load_data()
images = tf.cast(cifar_train[0], tf.float32) / 255.0
cifar_ds = tf.data.Dataset.from_tensor_slices((images)).batch(1)
def representative_data_gen():
  for input_value in cifar_ds.take(100):
    yield [input_value]

converter.representative_dataset = representative_data_gen

tflite_model = converter.convert()
open(out_name, "wb").write(tflite_model)

============================== Summary by node type ==============================
            [Node type]   [count]   [avg ms]     [avg %]     [cdf %]   [mem KB] [times called]
                CONV_2D         1     4.625     95.165%     95.165%     0.000         1
                    MEAN         1     0.226     4.650%     99.815%     0.000         1
                QUANTIZE         1     0.009     0.185%   100.000%     0.000         1
              DEQUANTIZE         1     0.000     0.000%   100.000%     0.000         1
```
I had a poke through the source code, I could find the arm neon accelerated pooling code for integers here:
```
tensorflow/lite/kernels/⁨internal/optimized⁩/integer_ops⁩/pooling.h
```
It seems to me that there are no neon optimisations for pooling with float datatype?

**Comment by sbsky** [comment]
So I've done a bit more digging, I was able to get much better performance by using the average pooling function.  keras.GlobalAveragePooling2D by default uses mean:
```
backend.mean(inputs, axis=[2, 3])
```

Example using tf.nn.avg_pool2d:
```
import tensorflow as tf

out_name = 'mobilenet_v2.tflite'
print(tf.version.GIT_VERSION, tf.version.VERSION)

input = tf.keras.layers.Input(shape=(32, 32, 3,))
x = tf.keras.layers.Conv2D(filters=256, kernel_size=(1, 1))(input)
x = tf.keras.layers.Activation('relu')(x)

x = tf.nn.avg_pool2d(x, ksize=(x.shape[1], x.shape[2]), padding='VALID', strides=(1, 1))
x = tf.reshape(x, (1, x.shape[-1]))

model = tf.keras.Model(inputs=[input], outputs=[x])

model.summary()

converter = tf.lite.TFLiteConverter.from_keras_model(model)
cifar_train, _ = tf.keras.datasets.cifar10.load_data()
images = tf.cast(cifar_train[0], tf.float32) / 255.0
cifar_ds = tf.data.Dataset.from_tensor_slices((images)).batch(1)
def representative_data_gen():
  for input_value in cifar_ds.take(100):
    yield [input_value]

converter.representative_dataset = representative_data_gen

tflite_model = converter.convert()
open(out_name, "wb").write(tflite_model)
```




============================== Summary by node type ==============================

            [Node type]   [count]   [avg ms]     [avg %]     [cdf %]   [mem KB] [times called]

                CONV_2D         1     0.160     75.472%     75.472%     0.000         1

        AVERAGE_POOL_2D         1     0.052     24.528%   100.000%     0.000         1

                RESHAPE         1     0.000     0.000%   100.000%     0.000         1

**Comment by lu-wang-g** [comment]
First, AVERAGE_POOL_2D (corresponds to tf.nn.avg_pool2d) has been optimized for the float path while MEAN (corresponds to GlobalAveragePooling2D) has not yet been optimized in tflite.

Second, your code of converting the tflite model using AVERAGE_POOL_2D does not seem right. You need to set the flag for optimization: converter.optimizations = [tf.lite.Optimize.DEFAULT]. Without it, you'll end up with undefined state, and most likely it will be a float model.

**Comment by lgeiger** [comment]
> First, AVERAGE_POOL_2D (corresponds to tf.nn.avg_pool2d) has been optimized for the float path while MEAN (corresponds to GlobalAveragePooling2D) has not yet been optimized in tflite.

@lu-wang-g @ymodak What do you think about converting `TFL_MeanOp` to `TFL_AveragePool2DOp` and `TFL_ReshapeOp` in the new MLIR based converter for the case of `GlobalAveragePooling2D`?
This would be very helpful for users trying to convert Keras models to TFLite since it is quite common to use `GlobalAveragePooling2D` or `tf.reduce_mean` in models.

**Comment by leejaeyeop** [comment]
Thanks to everyone! I was considering about removing squeeze and excite block from the network as it is too slow. But, after I switched GlobalAveragePoolin2D to tf.nn.avg_pool2d and now it becomes faster 👍

**Comment by JimHeo** [comment]
Is MEAN op supported in GPU delegate now?
I can't find the operation in this link: [https://www.tensorflow.org/lite/performance/gpu](https://www.tensorflow.org/lite/performance/gpu)
