### ISSUE TITLE
calling import_graph_def with op_dict dependency

### ISSUE THREAD

**Issue by epnev** [tensorflow/tensorflow#29444]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using): 1.13
- Are you willing to contribute it (Yes/No): Yes although I'm far from an expert

**Describe the feature and the current behavior/state.**

I'm using `import_graph_def` to load and deploy a model stored in an `.pb` file. I'm opening an issue because I saw the following message:

> calling import_graph_def (from tensorflow.python.framework.importer) with op_dict is deprecated and will be removed in a future version.
> Instructions for updating:
> Please file an issue at https://github.com/tensorflow/tensorflow/issues if you depend on this feature.

Please let me know if there is an alternative that won't be removed soon.

**Will this change the current api? How?**

Most likely not

**Who will benefit with this feature?**

Users who have such a dependency, including the users of our [CaImAn](https://github.com/flatironinstitute/CaImAn) package.

**Comment by alextp** [comment]
Don't pass an op_dict then.

**Comment by shubhambagwari** [comment]
can anybody help me in this issue "[ValueError: node 'Placeholder' in input_map does not exist in graph (input_map entry: input_image:0->Placeholder:0)](https://github.com/tensorflow/tensorflow/issues/53593)"
