### ISSUE TITLE
Different Results on Different Machines

### ISSUE THREAD

**Issue by HansikaPH** [tensorflow/tensorflow#29477]
I am having a problem with the reproducibility of results. When I run the code with the same seed on two different machines I get different results. But on the same machine, it gives me the same results all the time. Are you guys aware of any such issue?

**Comment by divyanshshekhar** [comment]
Are you sure that you are using same version of numpy and python on all machines? Maybe different versions have slight variation in randomization algorithm.

**Comment by HansikaPH** [comment]
Yes. The versions are exactly the same. But the results are not reproducible across machines.

**Comment by HansikaPH** [comment]
Okay, I figured out that the randomness was being produced by the following two functions in my code.

tf.random_normal()
tf.truncated_normal_initializer()

When I leave out the functionality coming from these two functions, the results are exactly equal on the two machines. I do not set the seed argument of these functions explicitly during the function call. Rather, I set it globally using the tf.set_random_seed() function. My understanding is that the globally set seed from the tf.set_random_seed() function is incorporated when producing the distributions using the above two functions. Please correct me if I am wrong. This actually makes sense, because I get the same result through multiple runs on the same machine.

Now my question is, does Tensorflow use any machine specific information within the functionalities of the above two functions?

**Comment by hegman12** [comment]
Hi,

yes. There is an issue with global seed in tensorflow. this seems to be resolved in 2.0. refer below. 

https://github.com/tensorflow/tensorflow/issues/9171

**Comment by HansikaPH** [comment]
Hi,

Thanks @hegman12 for pointing me to the above issue.
