### ISSUE TITLE
There is no docker image with "devel" for version 1.13.1 and 1.14 in docker hub

### ISSUE THREAD

**Issue by pradeepdw** [tensorflow/tensorflow#29476]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 16.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: NA
- TensorFlow installed from (source or binary): Docker image for tag '1.13.1-devel-gpu-py3' and for 1.14
- TensorFlow version: 1.13.1 and 1.14
- Python version: 3.6
- Installed using virtualenv? pip? conda?: Docker image unavailability issue
- Bazel version (if compiling from source): NA
- GCC/Compiler version (if compiling from source): NA
- CUDA/cuDNN version: 10.0
- GPU model and memory: GTX 1060 NVIDIA 

**Describe the problem**
There is no docker image with "devel" for version 1.13.1 and 1.14 in docker hub. I am not able to compile these versions from source and install. There are no tag with names "1.13.1-devel-gpu-py3" and "1.14.0-devel-gpu-py3".

**Provide the exact sequence of commands / steps that you executed before running into the problem**
The issue is with unavailability of Image with "devel" tag for 1.13.1 and 1.14.0.

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.
NA

**Comment by angersson** [comment]
That's correct. Following TF 1.12, we no longer provide `devel` containers based on specific versions, as `devel` tags are to be used for developing TensorFlow. If you would like to develop from source, please use the `devel-` tags instead, which are intended to support development for TensorFlow at master `HEAD`.

**Comment by bjarthur** [comment]
without a devel version with bazel, how then is one supposed to run the speech_commands [example](https://www.tensorflow.org/tutorials/sequences/audio_recognition#streaming_accuracy)?

**Comment by angersson** [comment]
@bjarthur, our `devel-` tags do contain Bazel. You should be able to use the existing `devel-` images to run the audio file generator.

**Comment by bjarthur** [comment]
so to run the examples i have to be on master?  would prefer to be on a release branch.

**Comment by angersson** [comment]
For the examples that use compiled source code, yes, that's correct. However, our development images do also contain a known-to-compile-commit in `/tensorflow_src`.

**Comment by mihaimaruseac** [comment]
Also note that once in the docker container other branches can also be checked out and built from. We don't guarantee that the code will compile, though in the majority of cases it should as the last commit on a release branch should also be the commit from which we generate the release associated docker tag. Thus, modulo some environment changes, only one `devel-` container should be needed to build on any release branch

**Comment by rky0930** [comment]
If TF 1.14.0 `devel` image will not be provided, Can you share how to reproduce speed of 1.12.0-devel-gpu with TF 1.14.0-gpu ?
There is  a speed difference between `devel` and `not devel `image during training phase. 
Although I don't develop from  source, I prefer to use 'devel' image for training
<img width="427" alt="tensorflow_dockerfile_steps_per_secs" src="https://user-images.githubusercontent.com/5013450/66796453-abc1de00-ef42-11e9-8567-08d6931e51a0.png">
: In this experiment, there are about 3 steps difference per sec.

**Comment by muik** [comment]
I also tried to build a image of tensorflow/tensorflow:1.14.0-devel-gpu-py3 which has source compiled tf installed.
But I couldn't build the image which is faster to train than non-devel tag like 1.12.0-devel-gpu-py3.

So, I really want to know building the image like that tf team officially built devel tag until 1.12.0.
