### ISSUE TITLE
Automatically merge identical ops

### ISSUE THREAD

**Issue by gaohuazuo** [tensorflow/tensorflow#2948]
When an op constructing function is called for multiple times on the same set of inputs, each of these calls adds a new op to the graph, which leads to extra computation. I understand that this could be avoided in most cases by reusing the output tensor. However, this can't be easily done in some situations, e.g. when using different optimizers for different parts of a neural network. Therefore, IMHO, it would be beneficial to have the framework automatically merge identical ops.

**Comment by yaroslavvb** [comment]
BTW PR #2747 has logic to detect when Python function call would create an op that's already in the graph and reuse that op if so

**Comment by prb12** [comment]
This is really a general usage question and as such is better suited for StackOverflow. Please consider re-asking there and tag it with the `tensorflow` tag.

TensorFlow graphs are extensively rewritten before execution, and one of the optimizations is common subexpression elimination which would remove duplicate code in cases where it does not affect the result.  So, in most cases this should not be a _performance_ issue.  

If you have a specific model where this is a performance problem, please consider capturing an execution Timeline using the RunOptions to session.Run() and reopen this issue.  

Similarly, if the graphdef is excessively large, please consider posting an example of the code idiom which is resulting in duplication.
