### ISSUE TITLE
tf.keras InvalidArgumentError: Incompatible shapes for batch size > 1

### ISSUE THREAD

**Issue by gustavz** [tensorflow/tensorflow#29489]
**System information**
- Have I written custom code (as opposed to using example directory):  yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):  macOS
- TensorFlow backend (yes / no):  yes
- TensorFlow version:  v1.12.1-1845-g27cfc61581 1.14.1-dev20190514
- Keras version:  using tf.keras
- Python version:  3.7.3
- CUDA/cuDNN version:   -
- GPU model and memory:  -

When fitting a tf.keras LSTM encoder-decoder model (or any model with Timedistributed(Dense(1)) layer at the end)

    model = Sequential()
    model.add(LSTM(200, activation='relu', input_shape=(72,3)))
    model.add(RepeatVector(24))
    model.add(LSTM(200, activation='relu', return_sequences=True))
    model.add(TimeDistributed(Dense(int(100), activation='relu')))
    model.add(TimeDistributed(Dense(1)))
    model.compile(loss='mse', optimizer='adam')

with a `batch_size>1` I see the following Error:

    keras InvalidArgumentError: Incompatible shapes: [100,24,1] vs. [100,24]

where in this case 100 is the `batch_size` and 24 is length of the output sequence.

The training data has the shape: `[samples, time_steps, n_features]`, so something like:

    X_train:(13641, 72, 3) and y_train:(13641, 24, 1)

**Comment by gustavz** [comment]
the error was due to a mal formated validation dataset, which was missing the final (batch_size,n_outputs,1) dimension

**Comment by xiaojiangwangjiang** [comment]
I have the same problem.can you help me ?
problem:
tensorflow.python.framework.errors_impl.InvalidArgumentError: Incompatible shapes: [50,3] vs. [3000,3]
[[{{node training/Adam/gradients/loss/dense_1_loss/mul_grad/BroadcastGradientArgs}}]]
#3000 is my total text number
# batch_size = 50

code:

sentence_input = Input(shape=(1000,), dtype='int32')
embedded_sequences = embedding_layer(sentence_input)
# print(embedded_sequences.shape)
l_lstm = Bidirectional(GRU(100, return_sequences=True))(embedded_sequences)
l_att = AttLayer(100)(l_lstm)

a = Lambda(concated,output_shape=(300,))(l_att)

preds = Dense(3, activation='softmax')(a)
model = Model(sentence_input, preds)
model.summary()
model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])
print("model fitting - attention network")
h = model.fit(x_train, y_train, validation_data=(x_val, y_val), batch_size=50, epochs=5)
plt.plot(h.history["loss"], label="train_loss")
plt.plot(h.history["val_loss"], label="val_loss")
plt.plot(h.history["acc"], label="train_acc")
plt.plot(h.history["val_acc"], label="val_acc")
plt.legend()
plt.show()


#thanks

**Comment by xiaojiangwangjiang** [comment]
I have the same problem.can you help me ?
problem:
tensorflow.python.framework.errors_impl.InvalidArgumentError: Incompatible shapes: [50,3] vs. [3000,3]
[[{{node training/Adam/gradients/loss/dense_1_loss/mul_grad/BroadcastGradientArgs}}]]
#3000 is my total text number
#batch_size =50

code:

sentence_input = Input(shape=(1000,), dtype='int32')
embedded_sequences = embedding_layer(sentence_input)
l_lstm = Bidirectional(GRU(100, return_sequences=True))(embedded_sequences)
l_att = AttLayer(100)(l_lstm)

a = Lambda(concated,output_shape=(300,))(l_att)

preds = Dense(3, activation='softmax')(a)
model = Model(sentence_input, preds)
model.summary()
model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])
print("model fitting - attention network")
h = model.fit(x_train, y_train, validation_data=(x_val, y_val), batch_size=50, epochs=5)
plt.plot(h.history["loss"], label="train_loss")
plt.plot(h.history["val_loss"], label="val_loss")
plt.plot(h.history["acc"], label="train_acc")
plt.plot(h.history["val_acc"], label="val_acc")
plt.legend()
plt.show()
