### ISSUE TITLE
Better docs for node methods

### ISSUE THREAD

**Issue by alquraishi** [tensorflow/tensorflow#295]
I see that nodes / tensors have a number of available methods, like `eval` and `get_shape`, which are very useful for interrogating the graph in interactive sessions for debugging and such. But as far as I can tell they're not really documented anyway. Seems like very useful features that are worth drawing attention to.

**Comment by mrry** [comment]
Hi there,

Are you referring to the API docs for Operation and Tensor? These are provided here:

* http://tensorflow.org/api_docs/python/framework.html#Operation
* http://tensorflow.org/api_docs/python/framework.html#Tensor

If there's anything that's not clear in here, or that you think would be worth adding, please let us know!

**Comment by alquraishi** [comment]
Yeah I see them now. Perhaps the docs should be reorganized a bit more to make them accessible? I see that the interface of the docs has changed just now, although the lack of collapseable navigation on the left makes it really hard to discover things.

**Comment by cesarsalgado** [comment]
I like to use ipython to check the documentation of the methods. Enter obj_name. and press `tab` to show the available methods for an object and enter obj_name.method_name? to see the documentation of the method.
