### ISSUE TITLE
tensorflow debugger `run -t` fails on keras

### ISSUE THREAD

**Issue by winston-zillow** [tensorflow/tensorflow#29501]
See the description at https://stackoverflow.com/questions/56452641/tensorflow-debugger-run-t-failed-running-keras-model

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Mac OS
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 1.13.1
- Python version: 3.7
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Describe the current behavior**

Exception thrown

**Describe the expected behavior**

Run the number of iteration as specified in the `run -t` command

**Code to reproduce the issue**

See  https://stackoverflow.com/questions/56452641/tensorflow-debugger-run-t-failed-running-keras-model

**Other info / logs**

**Comment by gadagashwini** [comment]
I am able to reproduce the reported issue with tensorflow 1.13.1 version. Thanks!

**Comment by caisq** [comment]
@gadagashwini Thanks for the bug report. We'll push a commit to fix this at HEAD soon.

**Comment by caisq** [comment]
@winston-zillow  Thanks for the bug report. We'll push a commit to fix this at HEAD soon.
