### ISSUE TITLE
[TF 2.0 API Docs] tf.image.crop_and_resize

### ISSUE THREAD

**Issue by imransalam** [tensorflow/tensorflow#29507]
## URL(s) with the issue:

https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/image/crop_and_resize
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/ops/image_ops_impl.py

### Raises listed and defined

Raises are not defined

### Usage example

No usage example is given

### Submit a pull request?

Yes
https://github.com/tensorflow/tensorflow/pull/29508

**Comment by ymodak** [comment]
Closing this issue since the associated PR has been merged. Thanks!
