### ISSUE TITLE
Installation of Tensorflow on Mac OS X 10.11.5 wheel not supported?

### ISSUE THREAD

**Issue by cyriltw** [tensorflow/tensorflow#2951]
Tried installing Tensorflow but wheel not supported on this platform. 

### Environment info
Operating System: Mac OS X 10.11.5

If installed from binary pip package, provide:

1. sudo -H pip install --upgrade https://storage.googleapis.com/tensorflow/mac/tensorflow-0.8.0-py2-none-any.whl
2. Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named tensorflow

If installed from sources, provide the commit hash:

### Steps to reproduce
1. sudo -H pip install --upgrade https://storage.googleapis.com/tensorflow/mac/tensorflow-0.8.0-py2-none-any.whl

### Logs or other output that would be helpful
tensorflow-0.8.0-py2-none-any.whl is not a supported wheel on this platform.

**Comment by martinwicke** [comment]
Can you post the output of pip --version? It's possible that your pip is installed for python3.

**Comment by cyriltw** [comment]
@martinwicke yep spot on that seems to be the issue. 

`pip 8.1.2 from /Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages (python 3.5)`

I want to use Tensorflow on Python2. which version of pip is suitable for this?

**Comment by martinwicke** [comment]
Just run "easy_install-2.7 pip" (or similar), that should make a pip2.7 and
probably also moves the pip symlink to the py2 version.
