### ISSUE TITLE
[TF 2.0 API Docs] tf.io.decode_image

### ISSUE THREAD

**Issue by imransalam** [tensorflow/tensorflow#29511]
## URL(s) with the issue:

https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/io/decode_image
https://github.com/tensorflow/tensorflow/edit/master/tensorflow/python/ops/image_ops_impl.py

### Usage example

No usage example given

### Submit a pull request?

Yes
https://github.com/tensorflow/tensorflow/pull/29512

**Comment by amahendrakar** [comment]
@imransalam,
The `Used in the notebooks` section has been added in the latest version of the documentation for [tf.io.decode_image](https://www.tensorflow.org/api_docs/python/tf/io/decode_image).

Closing the issue as it is resolved. Please feel free to re-open if mistaken. Thanks!
