### ISSUE TITLE
tf.scatter_add does not throw an error

### ISSUE THREAD

**Issue by shirindora** [tensorflow/tensorflow#29526]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): macOS 10.14.5
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 1.13.1
- Python version: 3.6
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
The documentation of [tf.scatter_add](https://www.tensorflow.org/api_docs/python/tf/scatter_add) states that it requires the following:
```
updates.shape = indices.shape + ref.shape[1:]
```
However, no exception is thrown when I run the code below. In this code, the terms in the condition above have below values.
```
updates.shape = (204671, 100)
indices.shape = (204671, 2)
ref.shape[1:] = (80, 100)
```
This makes it harder to understand the behavior of the function ```tf.scatter_add``` in case ```indices``` is a matrix. Specifically, what is the difference between ```tf.scatter_add``` and ```tf.scatter_nd``` when ```indices``` is a matrix.

**Describe the expected behavior**
An exception should be thrown when the condition in ```tf.scatter_add``` is not met.

**Code to reproduce the issue**

```
import tensorflow as tf
from tensorflow_probability.python.distributions import Bernoulli, Normal

if __name__ == '__main__':
    tf.enable_eager_execution()

    event_dist = Bernoulli(probs=0.2)
    kernel_dist = Normal(loc=0, scale=1)

    events = event_dist.sample(sample_shape=(128, 80, 100), seed=0)
    kernel = kernel_dist.sample(sample_shape=(100, 100), seed=0)

    event_idx = tf.where(events)
    event_effect = tf.gather(kernel, event_idx[:, 2])  # PSP due to each spike
    comp = tf.get_variable(name='v1', shape=(128, 80, 100), initializer=tf.zeros_initializer())
    tf.scatter_add(comp, event_idx[:, :2], event_effect)
```

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by ymodak** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow-tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.
