### ISSUE TITLE
Support RaggedTensor in table lookups

### ISSUE THREAD

**Issue by Zoltrix** [tensorflow/tensorflow#29529]
**System information**
- TensorFlow version (you are using): 2.0.0-alpha0 
- Are you willing to contribute it (Yes/No): No

**Describe the feature and the current behavior/state.**
Make Table lookups (`tf.lookup.StaticHashTable` for example) support Ragged Tensor. Currently it only supports Tensor & Sparse Tensor.

**Will this change the current api? How?**
No

**Who will benefit with this feature?**
Pretty much any NLP practitioner using this awesome library :)

**Any Other info.**

**Comment by shamoji101** [comment]
Why don't you use tf.ragged.map_flat_values?  raggedTensor.values has very long range flat value which is normal tensor.

**Comment by leandro-gracia-gil** [comment]
By the way, I have noticed that at least in TF 2.2 it does not seem possible to have ragged tensors stored as hash values either (or at least not when using KeyValueTensorInitializers). It raises an exception about ragged tensors not having len().

Is there any particular reason for this? It feels like there's nothing really preventing this to work.
- The first dimension of any ragged tensor is uniform, implying that while len(tensor) might fail, tensor.shape[0] should provide the value this is looking for.
- While I ignore the details of how this is exactly implemented, shouldn't the values of a hash table only require being comparable for equality, as they are compared with the rest of elements in the same bucket?
- The traceback suggests that the exception comes from an attempt to convert the ragged tensor into a constant tensor, even a constant ragged tensor is provided.

**Comment by kumariko** [comment]
@Zoltrix We are checking to see if you still need help on this issue. please check with the latest stable version of TF which  is`TF2.7` and also check https://github.com/tensorflow/tensorflow/issues/29529#issuecomment-635916245
