### ISSUE TITLE
learn datasets not found

### ISSUE THREAD

**Issue by miahunsicker** [tensorflow/tensorflow#2952]
GitHub issues are for bugs / installation problems / feature requests.  
For general support from the community, see [StackOverflow](https://stackoverflow.com/questions/tagged/tensorflow).
To make bugs and feature requests more easy to find and organize, we close issues that are deemed
out of scope for GitHub Issues and point people to StackOverflow.

For bugs or installation issues, please provide the following information.
The more information you provide, the more easily we will be able to offer
help and advice.

### Environment info
Operating System:

Installed version of CUDA and cuDNN: 
(please attach the output of `ls -l /path/to/cuda/lib/libcud*`):

If installed from binary pip package, provide:

1. Which pip package you installed.
2. The output from `python -c "import tensorflow; print(tensorflow.__version__)"`.

I have tensorflow 0.8.0 installed and when i import learn the datasets are not an option

![screen shot 2016-06-19 at 3 00 22 pm](https://cloud.githubusercontent.com/assets/8854444/16180075/dbe3ff6c-362e-11e6-8f5a-4a7cf575f5cf.png)
![screen shot 2016-06-19 at 3 02 10 pm](https://cloud.githubusercontent.com/assets/8854444/16180076/dbfd3fa4-362e-11e6-836d-d98c68400389.png)

**Comment by martinwicke** [comment]
0.8.0 doesn't contain (all of) tf.contrib.learn. Can you check with 0.9?

**Comment by miahunsicker** [comment]
works! thank you. I didn't think I missed that because when I prompted "pip install tensorflow --upgrade" it returned tf 0.8.0 was up to date.
