### ISSUE TITLE
Fractional pooling

### ISSUE THREAD

**Issue by amirstar** [tensorflow/tensorflow#2953]
Is there or (will there be) a "Fractional Pooling" support in tensorflow?

**Comment by prb12** [comment]
Apparently we do have some Fractional pooling ops in development which should (hopefully) make it into the external tree shortly.

**Comment by michaelisard** [comment]
This should be coming out soon.

**Comment by KendallWeihe** [comment]
Any word on this?

**Comment by michaelisard** [comment]
Sorry for the delay. It is still making its way through code review, but really should be soon now!
