### ISSUE TITLE
Virtual TF package breaks tf.sysconfig based include path

### ISSUE THREAD

**Issue by byronyi** [tensorflow/tensorflow#29532]
As f1ffa0225ae19870c1473b1d70faf0ceaeea9862 landed yesterday, the framework library is now moved from `tensorflow` to `tensorflow_core` and the include path also changed to `tensorflow_core/include`.

`tf.sysconfig.get_include` and `tf.sysconfig.get_lib` should be changed accordingly but they are not. This breaks downstream packages such as horovod and tensorflow_io that build custom ops and link to TF. It also means any binary distributions of these packages will break binary backward compatibility with this change.

See https://github.com/horovod/horovod/issues/1129 for a reproducing procedure.

Ping @mihaimaruseac @yifeif

**Comment by mihaimaruseac** [comment]
Sorry about that, will fix today.

**Comment by mihaimaruseac** [comment]
I think this should be fixed now, but let me know if not and I missed something.
