### ISSUE TITLE
TF2-beta has mismatch between libtensorflow_framework and link flag

### ISSUE THREAD

**Issue by seanpmorgan** [tensorflow/tensorflow#29540]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 16.04
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.0.0.b0

**Describe the current behavior**
There is a mismatch in the name of `libtensorflow_framework` and the `tf.sysconfig.get_link_flag` name. As an [example TF-Addons uses this to link](https://github.com/tensorflow/addons/blob/master/configure.sh#L46) with tensorflow core. 
```
$ python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"
('v1.12.1-3259-gf59745a381', '2.0.0-beta0')

$ python -c "import tensorflow as tf; print(tf.sysconfig.get_link_flags())"
['-L/usr/local/lib/python2.7/dist-packages/tensorflow', '-l:libtensorflow_framework.so.2

$ ll /usr/local/lib/python2.7/dist-packages/tensorflow
total 34128
drwxr-sr-x 10 root staff     4096 Jun  7 17:24 ./
drwxrwsr-x  1 root staff     4096 Jun  7 17:24 ../
...
drwxr-sr-x  9 root staff     4096 Jun  7 17:24 include/
-rwxr-xr-x  1 root staff 34858656 Jun  7 17:24 libtensorflow_framework.so.1*
drwxr-sr-x  5 root staff     4096 Jun  7 17:24 lite/
drwxr-sr-x 29 root staff     4096 Jun  7 17:24 python/
drwxr-sr-x  6 root staff     4096 Jun  7 17:24 tools/


```
**Describe the expected behavior**
The framework should be named `libtensorflow_framework.so.2`

**Code to reproduce the issue**
```
pip install tensorflow==2.0.0.b0
```

cc @yifeif @perfinion

**Comment by yifeif** [comment]
Seems like it might be due to VERSION is set to 1.13.1 here https://github.com/tensorflow/tensorflow/blob/r2.0/tensorflow/tensorflow.bzl#L60

**Comment by seanpmorgan** [comment]
This issue is now fixed on beta1. Closing and thanks for the help!
