### ISSUE TITLE
tf.train.Saver fails on AutoTrackable

### ISSUE THREAD

**Issue by gehring** [tensorflow/tensorflow#29541]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): public colab instance
- TensorFlow installed from (source or binary): tf-nightly-1.14.1.dev20190607
- TensorFlow version (use command below): 1.14.1.dev20190607
- Python version: 3.6.7

**Describe the current behavior**
Manually specifying an instance of AutoTrackable (e.g., tf.Module) causes `tf.train.Saver` to fail with a somewhat cryptic error:

`ValueError: Attr 'dtypes' of 'SaveV2' Op passed list of length 0 less than minimum 1.`

The issue seems to come from a call to `Trackable._gather_saveables_for_checkpoint` which is not overridden by `tf.Module` or `AutoTrackable`. 

**Describe the expected behavior**
I'm not sure if this is intended to work (so maybe this should be a feature request?) but at the least I think the issue should be caught earlier and return a more informative error message. 

The docs for `tf.train.Saver` call for a list/dict of `SaveableObject`, which `AutoTrackable` is not, but it seems odd that it isn't. It is possible that I am misunderstanding the `SaveableObject`/`Saver` API, but I do feel like `AutoTrackable` should be compatible `tf.train.Saver`.

**Code to reproduce the issue**
```python
import tensorflow as tf

class MyModel(tf.Module):
  
  def __init__(self):
    super(MyModel, self).__init__()
    self._var = tf.Variable(1.)
    
model = MyModel()
saver = tf.train.Saver({"model": model})
```

**Other info / logs**
@tomhennigan

**Comment by allenlavoie** [comment]
Please use `tf.train.Checkpoint` rather than `tf.train.Saver` to save objects: https://www.tensorflow.org/beta/guide/checkpoints (the guide is for 2.x, but the APIs are in 1.x as well).

The error message could be improved though; the reason it gets that far is that you can pass some Trackable objects to Saver (e.g. MirroredVariables).

**Comment by gehring** [comment]
Thanks for the response! I had just assumed that `Saver` would be present in 2.x. Since it's not, this is probably not worth much manpower. It might be worth marking `tf.train.Saver` as deprecated since the issue arises using features present in 1.x. Alternatively, if deprecating is not desirable, a warning in the `tf.train.Saver` docs would probably help people like me who accidentally mix the old and new TF features.

**Comment by achandraa** [comment]
@gehring : Thanks for your support to the community. Can we close the issue since it looks to be resolved.  Let us know.

**Comment by gehring** [comment]
@achandraa The issue is resolved on my end but I do think a note in the docs would help prevent others from running into the same confusion. I've made a small PR for this (#29609). Feel free modify/merge/close the PR however you think is best and close this issue.

**Comment by achandraa** [comment]
@gehring : Thanks for raising the PR. We will close the issue once PR gets merged.

**Comment by gehring** [comment]
@achandraa PR merged, closing this issue. Feel free to re-open if you feel like there is still something to address.

**Comment by achandraa** [comment]
@gehring : Thanks for the update. Please feel free to come back in case of any other issue.

**Comment by achandraa** [comment]
Are you satisfied with the resolution of your issue?<br> [Yes](https://docs.google.com/forms/d/e/1FAIpQLSfaP12TRhd9xSxjXZjcZFNXPGk4kc1-qMdv3gc6bEP90vY1ew/viewform?entry.85265664=Yes&entry.2137816233=29541)<br> [No](https://docs.google.com/forms/d/e/1FAIpQLSfaP12TRhd9xSxjXZjcZFNXPGk4kc1-qMdv3gc6bEP90vY1ew/viewform?entry.85265664=No&entry.2137816233=29541)
