### ISSUE TITLE
Tensorflow 2.0 alpha/beta performance

### ISSUE THREAD

**Issue by arthurflor23** [tensorflow/tensorflow#29549]
**System information**
Google Colab system (GPU mode) with TensorFlow 2.0 and Python 3.

**Describe the current behavior**
Using TensorFlow 2.0 beta (pip install) on a CNN-RNN (two bidirecional lstm), is taking about 25 minutes to complete a single epoch (training).

**Describe the expected behavior**
The curious thing is that when using the same code, same file/platform (google colab) but with the Alpha version of the TF 2.0 (pip install), the same epoch takes around only 70 seconds.

**Other info / logs**
Everything is the same in both scenarios and also the identification of the GPU:
> Found GPU at: / device: GPU: 0

Another thing I noticed is that the alpha warning disappeared:

> W0608 02:52:12.500632 140219739858816 tf_logging.py:161] <tensorflow.python.keras.layers.recurrent.UnifiedLSTM object at 0x7f86d4231da0>: Note that this layer is not optimized for performance. Please use tf.keras.layers.CuDNNLSTM for better performance on GPU.

Maybe it has something related?

**Comment by llan-ml** [comment]
@arthurflor23  Refer to #29506

**Comment by qlzh727** [comment]
Sorry for the performance regression, we are aware of this issue, and trying to address it right now. Please monitor on https://github.com/tensorflow/tensorflow/issues/29506 which is the same issue.
