### ISSUE TITLE
ModuleNotFoundError: No module named 'tensorflow.python.ops.cond_v2'

### ISSUE THREAD

**Issue by davordavidovic** [tensorflow/tensorflow#29553]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Google Colab
- TensorFlow version (use command below): tensorflow-gpu 2.0.0-beta and any tf 2.0 nightly build
- Python version: Python 3.6.7
- GPU model and memory: Tesla K80 (12GB RAM)

**Describe the current behavior**
Initilalizing a Keras model raises following error: ModuleNotFoundError: No module named 'tensorflow.python.ops.cond_v2' when using Google Colab

Code was working fine until yesterday's build. The error doesn't go away in other tf 2.0 versions.

**Code to reproduce the issue**
base_model = tf.keras.applications.MobileNetV2(input_shape=(128,128,3),
                                                   include_top=False,
                                                   weights='imagenet')
or

base_model = tf.keras.applications.MobileNetV2(input_shape=(128,128,3))

**Comment by mihaimaruseac** [comment]
I see you closed the issue. Does that mean you found a fix?

**Comment by davordavidovic** [comment]
It turned out to be a Colab issue for me. I just restarted the environment and installed the dev20190607 nightly build then it started working fine!

**Comment by mihaimaruseac** [comment]
Perfect. Thank you.

For full disclosure: I made a change which broke a few things in the nightlies since 6th of June until today so I was gathering to see if there were unaccounted for failures
