### ISSUE TITLE
TF2 Nightly-20190608 unable to link to core framework

### ISSUE THREAD

**Issue by seanpmorgan** [tensorflow/tensorflow#29559]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 14.04+
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): tf_nightly_2.0_preview==2.0.0.dev20190608
- Python version: Python2 / 3
- Bazel version (if compiling from source): 0.24.1

**Describe the current behavior**
TF Addons is failing to link to the tensorflow core framework for our python 2 build:
```
tensorflow_addons/custom_ops/text/cc/kernels/skip_gram_kernels.cc:20:49: fatal error: tensorflow/core/framework/op_kernel.h: No such file or directory
 #include "tensorflow/core/framework/op_kernel.h"

tensorflow_addons/custom_ops/text/cc/ops/skip_gram_ops.cc:16:42: fatal error: tensorflow/core/framework/op.h: No such file or directory
 #include "tensorflow/core/framework/op.h"

./tensorflow_addons/custom_ops/image/cc/kernels/euclidean_distance_transform_op.h:23:52: fatal error: tensorflow/core/framework/tensor_types.h: No such file or directory
 #include "tensorflow/core/framework/tensor_types.h"

....
```

Strangely this is only affecting our python2 builds. See the build logs in https://github.com/tensorflow/addons/pull/273

**Describe the expected behavior**
Able to correctly link to the framework.

**Other info / logs**
Assuming this is related to the virtual pip package. Should these be looking in `tensorflow_core/...`?

cc @mihaimaruseac @perfinion

**Comment by mihaimaruseac** [comment]
Sorry for the breakage. I think #29561 should fix this, but I'll take another look at this tomorrow

**Comment by byronyi** [comment]
According to the nightly RFC, it is possible to have same day nightly packages for different platforms at different commits. Ping @gunan to double check.

**Comment by gunan** [comment]
Correct. If the tree is healthy, nightly is automatically pushed. If the tree is unhealthy, we may skip pushing nightlies for a particular configuration for days.

**Comment by seanpmorgan** [comment]
Sounds good. I don't think it disrupted any work on this but FWIW the reason Python3 didn't fail was because there was no [py34 nightly published for 20190608](https://pypi.org/project/tf-nightly-2.0-preview/2.0.0.dev20190608/#files).

**Comment by mihaimaruseac** [comment]
I think that these should be fixed now

**Comment by achandraa** [comment]
@seanpmorgan : let me know if we can close this issue since it looks to be fixed. Thanks!

**Comment by seanpmorgan** [comment]
Can confirm this is good to close. Thanks!
