### ISSUE TITLE
TF 2.0 Beta TPUStrategy

### ISSUE THREAD

**Issue by chiayewken** [tensorflow/tensorflow#29550]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: NA
- TensorFlow installed from (source or binary): Binary
- TensorFlow version (use command below): v1.12.1-3259-gf59745a381 2.0.0-beta0
- Python version: 3.6.7
- Bazel version (if compiling from source): NA
- GCC/Compiler version (if compiling from source): NA
- CUDA/cuDNN version: NA
- GPU model and memory: NA

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
Running the following code to setup TPUStrategy results in NotFoundError: No registered 'ConfigureDistributedTPU' OpKernel for TPU_SYSTEM devices compatible with node {{node ConfigureDistributedTPU}}

`import tensorflow as tf
cluster_resolver = tf.distribute.cluster_resolver.TPUClusterResolver()
tf.config.experimental_connect_to_host(cluster_resolver.master())
tf.tpu.experimental.initialize_tpu_system(cluster_resolver)
tpu_strategy = tf.distribute.experimental.TPUStrategy(cluster_resolver)`

**Describe the expected behavior**
TPUStrategy setup completes without error.

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.
https://colab.research.google.com/drive/1trrM2E-x912TiP0CeHtAi8jxZaA5y_SL

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.
With reference to the [Distributed Training docs](https://www.tensorflow.org/beta/guide/distribute_strategy), I understand that TPUStrategy does not support all APIs in Tensorflow 2.0 Beta:
![image](https://user-images.githubusercontent.com/29782952/59141572-00c47500-89e2-11e9-82a4-9e045187db00.png)
However, given that some APIs are supported, it would follow that the TPUStrategy initialization in Tensorflow 2.0 Beta is expected to be functional. Hence, this bug report. Thank you!

**Comment by saberkun** [comment]
Hello, this error should be a basic issue that your Cloud TPU version is too old that does not contain the particular kernel you need. Could you try to contact Cloud TPU account team or raise an issue in https://github.com/tensorflow/tpu? I think you will need a tf 1.14 TPU at least (or tf-nightly), as it is close to tf 2.0 beta.

**Comment by goldiegadde** [comment]
Hi Chia, 
as noted in the doc section referenced by you, the TPU support is planned for a 2.0RC release.

**Comment by jhseu** [comment]
Yep, it'll work in the RC, or if you use the nightlies.
