### ISSUE TITLE
Initialize Layer with weights loaded from files

### ISSUE THREAD

**Issue by prannayk** [tensorflow/tensorflow#29572]
```python
embedding = tf.keras.layers.Embedding(1000, 64, 
    initializer=tf.keras.initializer.FileInitializer("weights.npy", verify_shape=True))
```

**System information**
- TensorFlow version (you are using): 1.13.1
- Are you willing to contribute it (Yes/No): Yes

**Describe the feature and the current behavior/state.**
Presently there is no way to directly tell Tensorflow to initialize the weights of a layer from a file without loading them up first and passing them. This is not required and can be done at the target device itself using the callback.
**Will this change the current api? How?**
The current API remains unchanged.
**Who will benefit with this feature?**
Anyone doing NLP, Vision, who might want to specificly load the weights of a layer from a file. This could also help in sharing weights of a few layers of a complicated neural network. It is definitely beneficial when working with word2vec like embedding layers. 

If it's fine, I would like to get assigned to this.

**Comment by aiinall** [comment]
Excuse me, how to use a pre-trained embedding in tensorflow 1.13 or 2.0 RNN as initial weights in an embedding layer?  e.g. 
embedding = tf.keras.layers.Embedding(input_dim=len(vocab), output_dim=EMBED_SIZE, input_length=MAX_LEN,   weights=[embedding_matrix], trainable=False)
I get the following runtime error. RuntimeError: Cannot get value inside Tensorflow graph function.

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.

**Comment by Saduf2019** [comment]
@prannayk 
Please post this issue on[ keras-team/keras repo.](https://github.com/keras-team/keras/issues)
To know more see;
https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999
