### ISSUE TITLE
Tensorflow 2 eager execution is off by default

### ISSUE THREAD

**Issue by seven-dev** [tensorflow/tensorflow#29573]
This code:
```python
import tensorflow as tf
print(tf.__version__)
print(tf.executing_eagerly())
```
Produces this output:
```
2.0.0-beta0
False
```

I build it from source.

**Comment by jaingaurav** [comment]
@seven-dev: How are you building it? I believe you need to specify `--config=v2`. I tried the following in colob without any issue:

```
from __future__ import absolute_import, division, print_function, unicode_literals

!pip install tensorflow-gpu==2.0.0-beta0
import tensorflow as tf

print(tf.__version__)
print(tf.executing_eagerly())
```

Closing for now. But feel free to re-open if I missed something

**Comment by seven-dev** [comment]
I just followed the guide but I checked out the branch "2.0.0-beta0":  
https://www.tensorflow.org/install/source  

I can't find that flag anywhere in bazelrc files hmm...

**Comment by goldiegadde** [comment]
The documentation needs to be updated, and we are working on fixing it. Thanks for bringing this to our attention.

**Comment by goldiegadde** [comment]
the guide is updated, https://www.tensorflow.org/install/source
can you please try and let us know ?

**Comment by seven-dev** [comment]
I will leave it building today in the afternoon and tomorrow I'll tell you how it went. Thank you for your help.

**Comment by seven-dev** [comment]
Yeah, it works :) Thank you very much!  
```python
>>> import tensorflow as tf
>>> print(tf.__version__)
2.0.0-beta1
>>> print(tf.executing_eagerly())
True
```

**Comment by akuzni2** [comment]
Why is eager execution turned on by default? It's much slower. Shouldn't it be up to the user's discretion to turn it on if needed?
