### ISSUE TITLE
Tensorflow 2.0 graph slower than eager for dynamic batch sizes

### ISSUE THREAD

**Issue by mmv** [tensorflow/tensorflow#29578]
**System information**
- Have I written custom code: Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10, Linux, Colaboratory
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): unknown 2.0.0-beta0
- Python version: 3.6.7
- CUDA/cuDNN version: 10
- GPU model and memory: Quadro M1000M, Colaboratory, ...

**Describe the current behavior**
Passing data with variable batch sizes to a training graph (as created by `tf.function`) causes the graph execution to be significantly slower than just executing the training in eager mode. It's also significantly slower than executing the same inputs with graph mode in TF1.x

While passing data with variable batch sizes is uncommon on most DL tasks, it is required for tasks on Geometric Learning. For example, if your data is graphs, even if you fix the same number of graphs per batch, you can still get a varying number of nodes or edges.

**Describe the expected behavior**
Graph mode should always be faster than eager mode.
Graph mode in TF2.0 should be at least approximately as fast as graph mode in TF 1.x.

**Code to reproduce the issue**
[Colab notebook available here](https://colab.research.google.com/drive/1xUVb0NAeOdefofgjKQhL_MB-XPILdSo_). Running with GPU makes eager mode significantly faster and the time difference more noticeable.

**Comment by jvishnuvardhan** [comment]
@mmv I was able to reproduce the issue with TF2.0-beta0. Thanks!

**Comment by mdanatg** [comment]
I had a quick look at the colab. The code is fairly complex which makes it difficult to identify specific inefficiencies.

@martinwicke could you route this to the appropriate person? Looks like a performance regression in graph mode.

It would be great to have a smaller reproducing example, but I believe that might be difficult to find.

**Comment by mmv** [comment]
I've added another cell at the end of the Colab notebook to show that the graph-compiled function is only slow for inputs with sizes it hasn't yet seen. If dimensions are repeated, the execution time is fast, as expected.

**Comment by guillaumekln** [comment]
This is possibly related to #29075.

**Comment by goldiegadde** [comment]
mmv@ have you tested this with TensorFlow 2.0.0  that has been released, 
fix for https://github.com/tensorflow/tensorflow/issues/29075 that was referenced above has been cherrypicked into the r2.0 branch.

**Comment by jvishnuvardhan** [comment]
@goldiegadde I ran the code (@mmv code) with `TF2.0.0` and `TF2.0.0b0`.  I noticed `TF2.0.0` is consistently faster than `TF2.0.0b0`.  Please check the [gist with `TF2.0`](https://colab.sandbox.google.com/gist/jvishnuvardhan/e16e60b3356be6284ca1bd84ebd2a1c9/tf2-bugs-graph-slower-than-eager.ipynb) and the [gist with `TF2.0.0b0`](https://colab.sandbox.google.com/gist/jvishnuvardhan/33f145cf86aece336a71da4924a85908/tf2-bugs-graph-slower-than-eager.ipynb). Thanks!

**Comment by mmv** [comment]
This has been resolved with along with #29075 — I'll go ahead and close it.
