### ISSUE TITLE
Op type not registered 'swish_f32' in binary running

### ISSUE THREAD

**Issue by a411919924** [tensorflow/tensorflow#29574]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- TensorFlow installed from (source or binary):
- TensorFlow version (or github SHA if from source):

**Provide the text output from tflite_convert**

```
---------------------------------------------------------------------------
NotFoundError                             Traceback (most recent call last)
<ipython-input-9-a62a8332a64b> in <module>
     10       verbose=1,
     11     use_multiprocessing=True,
---> 12     workers=4)

/usr/local/lib/python3.5/dist-packages/tensorflow/python/keras/engine/training.py in fit_generator(self, generator, steps_per_epoch, epochs, verbose, callbacks, validation_data, validation_steps, validation_freq, class_weight, max_queue_size, workers, use_multiprocessing, shuffle, initial_epoch)
   1513         shuffle=shuffle,
   1514         initial_epoch=initial_epoch,
-> 1515         steps_name='steps_per_epoch')
   1516 
   1517   def evaluate_generator(self,

/usr/local/lib/python3.5/dist-packages/tensorflow/python/keras/engine/training_generator.py in model_iteration(model, data, steps_per_epoch, epochs, verbose, callbacks, validation_data, validation_steps, validation_freq, class_weight, max_queue_size, workers, use_multiprocessing, shuffle, initial_epoch, mode, batch_size, steps_name, **kwargs)
    255 
    256       is_deferred = not model._is_compiled
--> 257       batch_outs = batch_function(*batch_data)
    258       if not isinstance(batch_outs, list):
    259         batch_outs = [batch_outs]

/usr/local/lib/python3.5/dist-packages/tensorflow/python/keras/engine/training.py in train_on_batch(self, x, y, sample_weight, class_weight, reset_metrics)
   1256         outputs = self.train_function(ins)  # pylint: disable=not-callable
   1257       else:
-> 1258         self._make_fit_function()
   1259         outputs = self._fit_function(ins)  # pylint: disable=not-callable
   1260 

/usr/local/lib/python3.5/dist-packages/tensorflow/python/keras/engine/training.py in _make_fit_function(self)
   2175     ]
   2176     self._make_train_function_helper(
-> 2177         '_fit_function', [self.total_loss] + metrics_tensors)
   2178 
   2179   def _make_test_function_helper(self, fn_name, outputs):

/usr/local/lib/python3.5/dist-packages/tensorflow/python/keras/engine/training.py in _make_train_function_helper(self, fn_name, outputs)
   2160             updates=updates,
   2161             name='train_function',
-> 2162             **self._function_kwargs)
   2163         setattr(self, fn_name, fn)
   2164 

/usr/local/lib/python3.5/dist-packages/tensorflow/python/keras/backend.py in function(inputs, outputs, updates, name, **kwargs)
   3241       raise ValueError('Session keyword arguments are not support during '
   3242                        'eager execution. You passed: %s' % (kwargs,))
-> 3243     return EagerExecutionFunction(inputs, outputs, updates=updates, name=name)
   3244 
   3245   if kwargs:

/usr/local/lib/python3.5/dist-packages/tensorflow/python/keras/backend.py in __init__(self, inputs, outputs, updates, name)
   3162         lifted_map = lift_to_graph.lift_to_graph(
   3163             init_tensors=init_tensors, graph=exec_graph, sources=inputs,
-> 3164             add_sources=True, handle_captures=True, base_graph=source_graph)
   3165 
   3166         inputs = [lifted_map[i] for i in inputs]

/usr/local/lib/python3.5/dist-packages/tensorflow/python/eager/lift_to_graph.py in lift_to_graph(init_tensors, graph, sources, disallowed_placeholders, add_sources, handle_captures, base_graph)
    313         continue
    314 
--> 315       _copy_non_source(op=op, graph=graph, op_map=op_map)
    316 
    317     return op_map

/usr/local/lib/python3.5/dist-packages/tensorflow/python/eager/lift_to_graph.py in _copy_non_source(op, graph, op_map)
    158         dtypes=[x.dtype for x in op.outputs],
    159         attrs=op.node_def.attr,
--> 160         name=op.name)
    161   op_map[op] = copied_op
    162   for i, o in enumerate(op.outputs):

/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/func_graph.py in create_op(self, op_type, inputs, dtypes, input_types, name, attrs, op_def, compute_shapes, compute_device)
    450     return super(FuncGraph, self).create_op(
    451         op_type, inputs, dtypes, input_types, name, attrs, op_def,
--> 452         compute_device=compute_device)
    453 
    454   def capture(self, tensor, name=None):

/usr/local/lib/python3.5/dist-packages/tensorflow/python/util/deprecation.py in new_func(*args, **kwargs)
    505                 'in a future version' if date is None else ('after %s' % date),
    506                 instructions)
--> 507       return func(*args, **kwargs)
    508 
    509     doc = _add_deprecated_arg_notice_to_docstring(

/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py in create_op(***failed resolving arguments***)
   3477           input_types=input_types,
   3478           original_op=self._default_original_op,
-> 3479           op_def=op_def)
   3480       self._create_op_helper(ret, compute_device=compute_device)
   3481     return ret

/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py in __init__(self, node_def, g, inputs, output_types, control_inputs, input_types, original_op, op_def)
   1975     else:
   1976       if op_def is None:
-> 1977         op_def = self._graph._get_op_def(node_def.op)
   1978       # TODO(skyewm): op_def_library.apply_op() flattens the incoming inputs.
   1979       # Refactor so we don't have to do this here.

/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py in _get_op_def(self, type)
   3864     with c_api_util.tf_buffer() as buf:
   3865       # pylint: disable=protected-access
-> 3866       c_api.TF_GraphGetOpDef(self._c_graph, compat.as_bytes(type), buf)
   3867       # pylint: enable=protected-access
   3868       data = c_api.TF_GetBuffer(buf)

NotFoundError: Op type not registered 'swish_f32' in binary running on tensorflow-20190607-122214. Make sure the Op and Kernel are registered in the binary running in this process. Note that if you are loading a saved graph which used ops from tf.contrib, accessing (e.g.) `tf.contrib.resampler` should be done before importing the graph, as contrib ops are lazily registered when the module is first accessed.```

Also, please include a link to a GraphDef or the model if possible.

**Any other info / logs**

My running environment:
Tensorflow 2.0 alpha,
Python 3.5.3
on Google Cloud Platform.

Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by achandraa** [comment]
In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Also let us know whether you are using CPU/GPU version of TF 2.0 alpha and information about the platform (architecture and operating system). Thanks!

**Comment by skyflynil** [comment]
Most likely is that 'swish_f32' is a kind of user defined function (even though originally from tf.nn.swish) and stored in the GraphDef's library.function part. Somehow such function is removed during some actions, such as tf.graph_util.remove_training_nodes.

**Comment by 1n1n1t3** [comment]
tf.compat.v1.disable_eager_execution() fixed that issue for me.

**Comment by a411919924** [comment]
> tf.compat.v1.disable_eager_execution() fixed that issue for me but I'm using the Python API for tflite convert.
> 
> EDIT: That's not helping at all though, because later I get errors with the tflite converter because it needs to be in eager execution.

It finally works for me. Thank you so much!

**Comment by NathanHowell** [comment]
it looks like there is a new way (in TF 2.0?) to register gradients that works in eager mode:

```python
@tf.custom_gradient
def swish(features):
    @tf.function
    def _grad(grad):
        sigmoid_features = tf.math.sigmoid(features)
        activation_grad = (sigmoid_features * (1.0 + features * (1.0 - sigmoid_features)))
        return grad * activation_grad

    return features * tf.nn.sigmoid(features), _grad

```

**Comment by captainst** [comment]
> Most likely is that 'swish_f32' is a kind of user defined function (even though originally from tf.nn.swish) and stored in the GraphDef's library.function part. Somehow such function is removed during some actions, such as tf.graph_util.remove_training_nodes.

Thank you achandraa.  I encountered the same error when convert the efficientnet model (pb file) to tensorRT format. Removing **tf.graph_util.remove_training_nodes** before **convert_variables_to_constants** does resolve this error for me.

I am not sure if this change affects the final performance in inference though.

**Comment by skyflynil** [comment]
> > Most likely is that 'swish_f32' is a kind of user defined function (even though originally from tf.nn.swish) and stored in the GraphDef's library.function part. Somehow such function is removed during some actions, such as tf.graph_util.remove_training_nodes.
> 
> Thank you skyflynil. I encountered the same error when convert the efficientnet model (pb file) to tensorRT format. Removing **tf.graph_util.remove_training_nodes** before **convert_variables_to_constants** does resolve this error for me.
> 
> I am not sure if this change affects the final performance in inference though.

@captainst I think you can still keep the remove _training_nodes part. There is just some post processing to workaround this issue.
option 1: copy back the function part of the graphdef. suppose the graphdef before/after removing training nodes are graph_def and new_graph_def, you can do
` for function_def in graph_def.library.function:
    f function_def.signature.name == 'swish_f32':
        new_graph_def.library.function.extend([copy.deepcopy(function_def)])
`
option 2:
inline the swish_f32 into the graphdef by using sigmoid and mul, it might be useful for TensorRT.

**Comment by skyflynil** [comment]
BTW, the new efficientnet for edge tpu seems to be a better choice for gpu device and tensorrt.

**Comment by captainst** [comment]
@skyflynil Many thanks. I am using jetrson NANO with classification stuffs. Although removing **tf.graph_util.remove_training_nodes** when freezing the keras model eliminates the error, the generated tensorRT model has problems and generate equal probabilities for each category (I was using softmax with 4 outputs), so the result is something like (0.25, 0.25, 0.25, 0.25). 
I tried to inference using the normal tensorflow .pb file and it gave correct results. So I think that probably there is some incongruence during the process **Keras model -> tensorflow pb -> tensorRT model**. Still need to figure out.

**Comment by StephenGreat** [comment]
> > > Most likely is that 'swish_f32' is a kind of user defined function (even though originally from tf.nn.swish) and stored in the GraphDef's library.function part. Somehow such function is removed during some actions, such as tf.graph_util.remove_training_nodes.
> > 
> > 
> > Thank you skyflynil. I encountered the same error when convert the efficientnet model (pb file) to tensorRT format. Removing **tf.graph_util.remove_training_nodes** before **convert_variables_to_constants** does resolve this error for me.
> > I am not sure if this change affects the final performance in inference though.
> 
> @captainst I think you can still keep the remove _training_nodes part. There is just some post processing to workaround this issue.
> option 1: copy back the function part of the graphdef. suppose the graphdef before/after removing training nodes are graph_def and new_graph_def, you can do
> 
> ```python
> for function_def in graph_def.library.function:
>      if function_def.signature.name == 'swish_f32':
>         new_graph_def.library.function.extend([copy.deepcopy(function_def)])
> ```
> 
> option 2:
> inline the swish_f32 into the graphdef by using sigmoid and mul, it might be useful for TensorRT.

Actually, some functions for graph optimization cause that problem.
These functions are :

- strip_unused_lib.strip_unused
- graph_util.remove_training_nodes 
- fold_batch_norms

The following code must be after these optimized functions.
`for function_def in graph_def.library.function:
     if function_def.signature.name == 'swish_f32':
        new_graph_def.library.function.extend([copy.deepcopy(function_def)])`

**Comment by lazy2panda** [comment]
> 最有可能的是，“swish_f32”是一种用户定义的函数（即使最初来自 tf.nn.swish）并存储在 GraphDef 的 library.function 部分中。在某些操作（例如 tf.graph_util.remove_training_nodes）期间，以某种方式删除了此类功能。

this works for me!!  thank you !
