### ISSUE TITLE
bulid form source 1.13.1 no such package '@org_sqlite//

### ISSUE THREAD

**Issue by nikenj** [tensorflow/tensorflow#29583]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):centos7
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version:1.13.1
- Python version:3.6
- Installed using virtualenv? pip? conda?:virtualenv
- Bazel version (if compiling from source):0.25.3
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:10.0
- GPU model and memory:

when i build tf  from source and run this command:
bazel build --config=opt --config=cuda //tensorflow/tools/pip_package:build_pip_package

there is a error :no such package '@org_sqlite//:
`ERROR: /tmp/tf/tensorflow/tensorflow/contrib/summary/BUILD:65:1: no such package '@org_sqlite//': java.io.IOException: Error downloading [http://mirror.tensorflow.org/www.sqlite.org/2019/sqlite-amalgamation-3280000.zip, https://www.sqlite.org/2019/sqlite-amalgamation-3280000.zip] to /home/tico/.cache/bazel/_bazel_tico/111e4735042cad380f0b87cff4bce3f6/external/org_sqlite/sqlite-amalgamation-3280000.zip: All mirrors are down: [GET returned 404 Not Found, sun.security.validator.ValidatorException: PKIX path bu`

i think the  download url is wrong , when i open this url:
 http://mirror.tensorflow.org/www.sqlite.org/2019/sqlite-amalgamation-3280000.zip
the page can not open, and in the  http://mirror.tensorflow.org/ page ,for www.sqlite.org key,there only have this:

```
<Contents>
<Key>
www.sqlite.org/2018/sqlite-amalgamation-3240000.zip
</Key>
<Generation>1553535068786424</Generation>
<MetaGeneration>2</MetaGeneration>
<LastModified>2019-03-25T17:31:08.786Z</LastModified>
<ETag>"4ea1e0c6e7e82cb0490d4753d6878698"</ETag>
<Size>2206612</Size>
</Contents>
```

so , i  vi  the workspace.bzl  file  and  change the  sqlite download url http://mirror.tensorflow.org/www.sqlite.org/2019/sqlite-amalgamation-3280000.zip to  https://mirror.bazel.build/www.sqlite.org/2018/sqlite-amalgamation-3240000.zip
,then it works!

**Comment by wdirons** [comment]
The branch r1.13 already has this change:
https://github.com/tensorflow/tensorflow/commit/714572bd063d54f9a38b920872e3d394a4f6c06b

It will be available when 1.13.2 is tagged and released. 

FYI 3.24 was deleted because it had a security issue.

**Comment by mihaimaruseac** [comment]
We haven't generated yet the new mirror and the 1.13 branch is in a state for 1.13.2 patch release. sorry for the issues this raised. I expect that by the end of the week this should be fixed.

**Comment by einzigsue** [comment]
Hi mihaimaruseac,

I think the mirror is down again. I got the following error when building TensorFlow/2.0.0-beta1 from source.
"""
An error occurred during the fetch of repository 'org_sqlite':
   java.io.IOException: Error downloading [http://mirror.tensorflow.org/www.sqlite.org/2019/sqlite-amalgamation-3280000.zip, https://www.sqlite.org/2019/sqlite-amalgamation-3280000.zip] to /short/z00/yxs900/tmp/_bazel_yxs900/7d93e1dcd15cd969c36cafda24edd905/external/org_sqlite/sqlite-amalgamation-3280000.zip: All mirrors are down: [GET returned 404 Not Found, sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target]
"""

Cheers
Yue

**Comment by mihaimaruseac** [comment]
Thank you for pointing this out. I will investigate and try to fix quick

**Comment by einzigsue** [comment]
Hi mihaimaruseac,
Many thanks to the prompt reply. Please let me know when it is fixed and I will resume compiling then. 
Cheers
Yue

**Comment by mihaimaruseac** [comment]
The mirror should be fixed now.
