### ISSUE TITLE
TFLite build failed in 7348ee578693bb5aacdb45a1be746f0c933fc65f

### ISSUE THREAD

**Issue by chenjiaoAngel** [tensorflow/tensorflow#29582]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):linux
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):source
- TensorFlow version:7348ee578693bb5aacdb45a1be746f0c933fc65f
- Python version:2.7
- Installed using virtualenv? pip? conda?:pip
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Describe the problem**

**Provide the exact sequence of commands / steps that you executed before running into the problem**

I use tensorflow/tensorflow/lite/java/demo in Android studio.
Android studio version:3.1.2 Andoird_NDK=r16b
run build, it comes error:
<img width="1351" alt="image" src="https://user-images.githubusercontent.com/38650344/59168984-dbaf3e00-8b6a-11e9-98d5-c69cd43a6c2c.png">

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.
The log info is:
Could not download tensorflow-lite-gpu.aar (org.tensorflow:tensorflow-lite-gpu:0.0.0-nightly)
   > Could not get resource 'https://jcenter.bintray.com/org/tensorflow/tensorflow-lite-gpu/0.0.0-nightly/tensorflow-lite-gpu-0.0.0-nightly.aar'.
      > Could not GET 'https://jcenter.bintray.com/org/tensorflow/tensorflow-lite-gpu/0.0.0-nightly/tensorflow-lite-gpu-0.0.0-nightly.aar'.
         > Connect to d29vzk4ow07wi7.cloudfront.net:443 [d29vzk4ow07wi7.cloudfront.net/13.224.42.66, d29vzk4ow07wi7.cloudfront.net/13.224.42.221, d29vzk4ow07wi7.cloudfront.net/13.224.42.134, d29vzk4ow07wi7.cloudfront.net/13.224.42.149] failed: Read timed out

**Comment by chenjiaoAngel** [comment]
Now it occurs other problem: 程序包org.tensorflow.lite.nnapi不存在
import org.tensorflow.lite.nnapi.NnApiDelegate; error, can't find this

**Comment by jdduke** [comment]
Note that you need to include *both* the tensorflow-lite-gpu lib *and* the `tensorflow-lite` library in your gradle build. You might need to [clear your gradle cache](https://stackoverflow.com/questions/23025433/how-to-clear-gradle-cache) for the NNAPI library to appear.

**Comment by chenjiaoAngel** [comment]
Thanks this problem has been solved
