### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by AliShokri** [tensorflow/tensorflow#29591]
https://www.tensorflow.org/images/models/pose_estimation.gif

this Link is broken

**Comment by anestisdotpy** [comment]
Could you please give some more information? 
Where does this link exist in the docs? (i.e. Where did you click it and realised it's broken?)

**Comment by AliShokri** [comment]
Hi dear Anestis, Yes. I was just browsing TensorFlow docs on the link below:
https://www.tensorflow.org/lite/models/pose_estimation/overview

But there is a broken link in the middle of the page
https://www.tensorflow.org/images/models/pose_estimation.gif

**Comment by anestisdotpy** [comment]
I believe it is supposed to point in this [link](https://raw.githubusercontent.com/irealva/tfjs-models/master/posenet/demos/camera.gif) and this [docs file](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/g3doc/models/pose_estimation/overview.md) should be changed. We should wait for a tensorflower before opening a PR. 
Would you like to submit it if that's the case?

**Comment by lamberta** [comment]
Thanks for the report!
That link should point here: https://www.tensorflow.org/images/lite/models/pose_estimation.gif
Would someone be able to make a PR?
