### ISSUE TITLE
Post Training Quantization slower in latest tf-nightly vs tf 1.10

### ISSUE THREAD

**Issue by BrindusaNiculae** [tensorflow/tensorflow#29596]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):  Ubuntu 18.04.2 LTS
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): pip
- TensorFlow version (use command below): tensorflow==1.10.0 vs tf-nightly==1.14.1.dev20190606
- Python version: 3.6.8
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**

I have converted the mobilenetv2_1.0_224_frozen.pb model to tflite and performed post training quantization in two virtual environments - one with tf-nightly==1.14.1.dev20190606 (following the instructions from here: https://github.com/tensorflow/tensorflow/blob/r2.0/tensorflow/lite/tutorials/post_training_quant.ipynb) and one with tensorflow==1.10.0.

During inference, I have observed that the model converted with the latest tensorflow version is ~2x slower

**Describe the expected behavior**
I expect that the latest post training quantization should remain as fast as the one in version 1.10.
 
**Code to reproduce the issue**
The scripts used for conversion:
[conversion_scripts.zip](https://github.com/tensorflow/tensorflow/files/3272376/conversion_scripts.zip)

For inference I have used tflite 1.10 and tflite 2.0.

I have used the profiling functionality of tflite and observed that:
   - in tf 1.10 there are 49 DEQUANTIZE Nodes vs 15 DEQUANTIZE Nodes for tf 1.14.1.dev20190606
   - CONV_2D is ~3x slower for the converted model in tf 1.14.1.dev20190606 (when running a float model CONV_2D seems similar in both tf versions)
   - by looking at the run order of the nodes it seems that only the depthwise nodes are quantized in tf 1.14.1.dev20190606 but in tf 1.10 expand, project and depthwise are quantized.

Here is the Summary by node type for tf 1.10:
```
Number of nodes executed: 115
============================== Summary by node type ==============================
	             [Node type]	  [count]	  [avg ms]     [times called]
	       DEPTHWISE_CONV_2D	       17	   151.612	   68
	                 CONV_2D	       36	   125.676	    144
	              DEQUANTIZE	       49	     7.872	     	      196
	                     ADD	       10	     0.288	            40
	         AVERAGE_POOL_2D	        1	     0.056	    	   4
	                 SOFTMAX	        1	     0.028	     	        4
	                 RESHAPE	        1	     0.004	     	        4

```

And the Summary by node type for tf 1.14.1.dev20190606:
```

Number of nodes executed: 81
============================== Summary by node type ==============================
	             [Node type]	  [count]	  [avg ms]	   [times called]
	                 CONV_2D	       36	   380.280	        144
	       DEPTHWISE_CONV_2D	       17	   160.624	   68
	                     ADD	       10	     0.428	     	       40
	         AVERAGE_POOL_2D	        1	     0.056	    	        4
	                 SOFTMAX	        1	     0.028	     	        4
	              DEQUANTIZE	       15	     0.016	     	       60
	                 RESHAPE	        1	     0.004	               4
```

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by suharshs** [comment]
What device are you benchmarking on? It is likely that the quantized benchmark numbers on x86 (desktop) are slower (especially because the graph with fewer Dequantize nodes seems right to me, since Conv2d's should have "hybrid" quantized implementation).

To get an accurate performance measure you will need to benchmark on an optimized mobile device.

(also note, i don't believe this tool was complete in 1.10).

**Comment by BrindusaNiculae** [comment]
Thank you for your response! 

I have run the benchmarks on desktop and on a Raspberry Pi 3B.

**Comment by mohantym** [comment]
Hi @BrindusaNiculae !
It seems you are using older versions(1.x versions) of Tensorflow. We recommend that you upgrade  your code base to 2.x  versions as many features and bug fixes has been done in newer versions and let us know if the issue still persists in newer versions. Thanks!
