### ISSUE TITLE
Unhandled API callback messages when using GPU tracing

### ISSUE THREAD

**Issue by prb12** [tensorflow/tensorflow#2959]
Using the GPU tracer (e.g. via session.Run with RunOptions FULL_TRACE) results in warnings like the following:
```
W tensorflow/core/common_runtime/gpu/gpu_tracer.cc:513] Unhandled API Callback for 2 41
W tensorflow/core/common_runtime/gpu/gpu_tracer.cc:513] Unhandled API Callback for 2 41
```

These are believed to be harmless, but are obviously annoying.  A fix is in progress.

**Comment by akors** [comment]
Hi, has a fix arrived? Is there a workaround?

**Comment by prb12** [comment]
I just submitted a fix internally... it should go out to github in the next sync.  

If this is a blocker for you then a simple workaround is to add the code below [here](https://github.com/tensorflow/tensorflow/blob/r0.9/tensorflow/core/common_runtime/gpu/gpu_tracer.cc#L488):

```
  } else if ((domain == CUPTI_CB_DOMAIN_RUNTIME_API) &&
             (cbid == CUPTI_RUNTIME_TRACE_CBID_cudaMemcpy_v3020 ||
              cbid == CUPTI_RUNTIME_TRACE_CBID_cudaMemcpyAsync_v3020)) {
```

**Comment by akors** [comment]
Hi, I have just tested with TensorFlow master, and it seems that there are no more "API  Callback" warnings anymore.

Commit f2a69f30fb159f4dd7d6550562e6e0c2e1f05c3a seems to have fixed the issue, and I suggest closing it.

**Comment by prb12** [comment]
Thanks!
