### ISSUE TITLE
Better support for composite dataflow variables and time series

### ISSUE THREAD

**Issue by sirinath** [tensorflow/tensorflow#296]
Perhaps you can have better support for composite data flow variables. E.g. modelling a moving window multivariate time-series, where you have a series of vectors and as new vectors are added calculations are triggered only for values which need re calculation. Also if a calculation is dependent on a slice updates are propagated in the most optimal way that only the needed data is recalculated.

The composite values can be:

 - Same type:

   - Vectors
   - Matrices
   - Arrays
   - Series
   - Data frames
   - Slices

- Different types:

   - Tuples (also series with different types)
   - Tables (also Data Frames with different types)
   - Views (slices with different types)

**Comment by sirinath** [comment]
This can include dataflow optimised data structures.

**Comment by girving** [comment]
This is somewhat covered by the queue functionality.
