### ISSUE TITLE
tensorflow/contrib module still tries to import cloud even when TF is compiled without GCP support

### ISSUE THREAD

**Issue by erwa** [tensorflow/tensorflow#29617]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): RHEL 7.3
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: n/a
- TensorFlow installed from (source or binary): source
- TensorFlow version: 1.13.1
- Python version: 3.7
- Installed using virtualenv? pip? conda?: pip
- Bazel version (if compiling from source): 0.21.0
- GCC/Compiler version (if compiling from source): 6.3.1
- CUDA/cuDNN version: n/a
- GPU model and memory: n/a

**Describe the problem**

It seems `tensorflow.contrib` will try to `import cloud` on an x86 machine even when TF is compiled without GCP support:

```
if os.name != "nt" and platform.machine() != "s390x":
  from tensorflow.contrib import cloud
```

I build TF with `--config=nogcp` which causes the `cloud` module NOT to be included in the pip package. But then when `tensorflow.contrib` is importing, you get `ImportError: cannot import name 'cloud' from 'tensorflow.contrib'`.

**Provide the exact sequence of commands / steps that you executed before running into the problem**

Build TF with `--config=nogcp`:

```
bazel build --config=nogcp //tensorflow/tools/pip_package:build_pip_package
```

Install the pip package, start Python, and run `import tensorflow.contrib`.

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by mihaimaruseac** [comment]
Can you try with 1.14 which was just released yesterday?

**Comment by erwa** [comment]
Hi @mihaimaruseac,

I haven't tried with 1.14 but I imagine the problem still exists looking at the code: https://github.com/tensorflow/tensorflow/blob/r1.14/tensorflow/contrib/__init__.py#L30-L31

I worked around the issue by changing those lines to:
```
if os.name != "nt" and platform.machine() != "s390x" and platform.machine() != "x86_64":
  from tensorflow.contrib import cloud
```

as I'm building and running on an x86_64 machine.

**Comment by Zhiqiang-Ye** [comment]
@mihaimaruseac 1.14 still has this issue. I used @erwa 's workaround to get tensorflow working.

**Comment by ppwwyyxx** [comment]
I'm running in the same issue, building TF r1.14 with the following flags:
```
--config=xla --config=mkl --config=noaws --config=nogcp --config=nohdfs --config=nokafka --config=noignite --config=numa
```

@gunan

**Comment by jw447** [comment]
Same problem here for mac. I think for mac, os.name = 'posix'. Do I need to import cloud to run tensorflow on mac? I built tensorflow 1.13 with --config=nogcp.
