### ISSUE TITLE
tensorflow.python.framework.errors_impl.InvalidArgumentError: Input to reshape is a tensor with 76800 values, but the requested shape has 768

### ISSUE THREAD

**Issue by Rmuli** [tensorflow/tensorflow#29623]
The shape of the intermediate tensor is as follows：
lad_tensor: (1, 17, 17, 768)
AvgPool_1a_5x5: (1, 5, 5, 768)
Conv2d_1b_1x1: (1, 5, 5, 128)
Conv2d_2a_5x5 (1, 1, 1, 768)
for example: aux_logits --> Tensor("××××", shape=(1, 1, 1, 768), dtype=float32)
and I want to convert a four-dimensional tensor into a two-dimensional tensor, I use the following method：
bottleneck_tensor=tf.squeeze(aux_logits,[1,2],name='SpatialSqueeze')
or：
bottleneck_tensor=tf.reshape(aux_logits,(-1,768),name='SpatialSqueeze')
So the result is：
bottleneck_tensor: Tensor("×××××", shape=(1, 768), dtype=float32)

But I use the following statement ：
bottleneck_input = tf.placeholder_with_default(
bottleneck_tensor, shape=[None, 768],
name='BottleneckInputPlaceholder')

The program reported the following error：
tensorflow.python.framework.errors_impl.InvalidArgumentError: Input to reshape is a tensor with 76800 values, but the requested shape has 768
[[Node: train/gradients/AuxLogits/SpatialSqueeze_grad/Reshape = Reshape[T=DT_FLOAT, Tshape=DT_INT32, _device="/job:localhost/replica:0/task:0/device:GPU:0"](train/gradients/final_training_ops/Wx_plus_b/MatMul_grad/tuple/control_dependency, train/gradients/AuxLogits/SpatialSqueeze_grad/Shape)]]
and 76800=768×100，train_batch_size=100

But if I use the following statement, the program does not report errors：
bottleneck_input = tf.placeholder_with_default(
s, shape=[None, 768],
name='BottleneckInputPlaceholder')
and s is the type of array

but I find in TensorBoard, the nodes in the graph are disconnected

I'm very confused about it !

**Comment by ymodak** [comment]
It looks like you haven't used a template to create this issue. Please resubmit your issue using a template from [here](https://github.com/tensorflow/tensorflow/issues/new/choose). We ask users to use the template because it reduces overall time to resolve a new issue by avoiding extra communication to get to the root of the issue. We will close this issue in lieu of the new one you will create from the template. Thank you for your cooperation.
