### ISSUE TITLE
TF 2.0 tf.image.non_max_suppression always output the length of max_output_size

### ISSUE THREAD

**Issue by JoelTsui** [tensorflow/tensorflow#29628]
tensorflow version: tensorflow-2.0.0-beta0

```
import tensorflow as tf

print(tf.__version__)

bbox = [[0,0,0,0],[0,0,0,0],[0.71619,0.3128575,0.7752377,0.37428612],[0.71619,0.3128575,0.7752377,0.37428612]]
scores = [2.4719129,1.701416,0.89775455,4.354542]

selected_index = tf.image.non_max_suppression(bbox,scores,3000,0.99)

print(selected_index)
```

and the output is
```
2.0.0-beta0
tf.Tensor([3 0 0 ... 0 0 0], shape=(3000,), dtype=int32)
```

I also tried `tf.image.non_max_suppression_padded` function with parameter `pad_to_max_output_size=False` and `pad_to_max_output_size=True`, the output shape is the same

**Comment by achandraa** [comment]
I have tried on Colab with TF CPU version 2.0.0-beta and was able to reproduce the issue.

**Comment by ravikyram** [comment]
@JoelTsui 
Can you please try with nightly version (`!pip install tf-nightly`) and let us know the whether the issue persists.I have tried and please find the gist [here](https://colab.sandbox.google.com/gist/ravikyram/26b4d9836f53dc6a3032888d77804266/untitled616.ipynb). Thanks!
