### ISSUE TITLE
How to change the protobuf version compiled in the tensorflow？

### ISSUE THREAD

**Issue by engineer1109** [tensorflow/tensorflow#29621]
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): 18.04.2
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): Master source
- TensorFlow version (use command below): 1.13.2
- Python version: 3.6
- Bazel version (if compiling from source): 0.26
- GCC/Compiler version (if compiling from source): 7.4
- CUDA/cuDNN version: 10 7.5
- GPU model and memory: 11G

I met this problem for tensorflow c++ application.
/home/wjl/github/tensorflow/bazel-genfiles/tensorflow/core/protobuf/verifier_config.pb.h:18:2: error: #error incompatible with your Protocol Buffer headers. 
My system is protobuf 3.8. Tensorflow uses 3.7.
How can I change it?

**Comment by engineer1109** [comment]
GRPC now cannot compile for 3.7 protobuf.

**Comment by ravikyram** [comment]
Just to verify did you follow the steps to change the protobuf version using pip install protobuf==3.7.Let us know if it resolves your issue.Thanks

**Comment by ravikyram** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
