### ISSUE TITLE
TensorBoard in SageMaker notebook doesn't work with an S3 location on AL

### ISSUE THREAD

**Issue by kalyc** [tensorflow/tensorflow#29620]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Amazon Linux
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 1.13.1
- Python version: 27 and 36
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Describe the current behavior**
`tensorboard --logdir "s3://[bucket]" --inspect`

Error log: 
`No event files found within logdir s3://[bucket]`
`2019-05-29 00:03:04.879182: I tensorflow/core/platform/retrying_utils.cc:70] The operation failed and will be automatically retried in 0.459992 seconds (attempt 1 out of 10), caused by: Failed precondition: Not a directory`

**Describe the expected behavior**

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

**Other info / logs**
`sudo cp /etc/ssl/certs/ca-bundle.crt /etc/ssl/certs/ca-certificates.crt` fixes the issue

----

Amazon Linux:
[ec2-user@ip-172-31-28-240 certs]$ pwd
/etc/ssl/certs
[ec2-user@ip-172-31-28-240 certs]$ ls -alL *.crt
-r--r--r-- 1 root root 211658 Mar  8 19:58 ca-bundle.crt

[ec2-user@ip-172-31-28-240 certs]$ ls -al *.crt
lrwxrwxrwx 1 root root 49 Mar  8 19:58 ca-bundle.crt -> /etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem
lrwxrwxrwx 1 root root 55 Mar  8 19:58 ca-bundle.trust.crt -> /etc/pki/ca-trust/extracted/openssl/ca-bundle.trust.crt

----

Ubuntu:
ubuntu@ip-172-31-76-35:/etc/ssl/certs$  ls -alL *.crt
-rw-r--r-- 1 root root 233394 Mar 19 07:23 ca-certificates.crt

---

Can Tensorflow move the required /etc/ssl/certs/ca-certificates in the right location for tensorboard to work with Amazon Linux?

**Comment by gowtham-kp** [comment]
@kalyc. Can you please create an issue in the [TesorBoard section](https://github.com/tensorflow/tensorboard/issues). Thanks!
