### ISSUE TITLE
Tensor flow lite stable release for Linux on ARM 64 bit

### ISSUE THREAD

**Issue by TrungLM13** [tensorflow/tensorflow#29626]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):

**Describe the problem**
Have we have any version(or tag) for tensor flow lite which can build successfully (or stable release) for ARM64 ?
 I have try many tag version, but sometimes script build was deleted, what's happend?
If it is not stable now, please tell me and I think I will try it later.

Some bug Im facing now:
https://www.gitmemory.com/issue/tensorflow/tensorflow/28863/496775232
https://github.com/tensorflow/tensorflow/issues/25120

**Comment by gadagashwini** [comment]
@TrungLM13 Just to verify, Did you get a chance to go through the [Build TensorFlow Lite for ARM64](https://www.tensorflow.org/lite/guide/build_arm64) official website. Let us know if that solves your problem. Thanks!

**Comment by TrungLM13** [comment]
Hello @gadagashwini , I followed by official website step by step. And I faced the same problem I post before.
I try to v1.12.2 and it can help me to pass #28863 bug I had to face with #25120.
Finally I pass all issue by disable NNAPI. and it work,
But when I try to use new version v1.13... or v1.14....
it is still bug #28863 .

Another thing, it seem likes that script build arm at some version was deleted and added again??? What happened for it?

**Comment by gadagashwini** [comment]
> Hello @gadagashwini , I followed by official website step by step. And I faced the same problem I post before.
> I try to v1.12.2 and it can help me to pass #28863 bug I had to face with #25120.
> Finally I pass all issue by disable NNAPI. and it work,
> But when I try to use new version v1.13... or v1.14....
> it is still bug #28863 .
> 
> Another thing, it seem likes that script build arm at some version was deleted and added again??? What happened for it?

@TrungLM13 Thanks for updating.

**Comment by chunduriv** [comment]
@TrungLM13,

You can use latest tensorflow (i.e 2.8) which also supports for Linux on ARM 64 bit.

Please refer [Build TensorFlow Lite for ARM boards](https://www.tensorflow.org/lite/guide/build_arm) may help you. Thanks!
