### ISSUE TITLE
`Check failed` error in Keras distributed (MultiWorkerMirroredStrategy) training.

### ISSUE THREAD

**Issue by protsenkovi** [tensorflow/tensorflow#29629]
Hello, in attempt to train simple keras model in distributed environment with TF 2.0 MultiWorkerMirroredStrategy I have encoutered an error `Check failed: size >= 0 ... Aborted` that appears only when the number of workers in TF_CONFIG is greater than 1. 

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
True

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
CentOS Linux release 7.4.1708 (Core)

- TensorFlow installed from (source or binary):
pip install

- TensorFlow version (use command below):
v1.12.1-3259-gf59745a381 2.0.0-beta0

- Python version:
3.6.7

**Describe the current behavior**

When run with more then one worker it fails:

```
Train on 2781 steps
Epoch 1/100
2019-06-11 10:54:04.220333: F tensorflow/core/framework/tensor_shape.cc:324] Check failed: size >= 0 (-19 vs. 0)
Aborted
```

The negative value in check seems to depend only on `drop_remainder` argument to `padded_batch` method and not on: `num_inputs`, `batch_size`, length of dataset, `epochs`. It equals to `-19` when `drop_remainder=False` and to `-16` when `drop_remainder=True`.

```
Check failed: size >= 0 (-19 vs. 0) <-> drop_remainder=False
Check failed: size >= 0 (-16 vs. 0) <-> drop_remainder=True
```

**Describe the expected behavior**

Should work

**Code to reproduce the issue**
Save this script as `tensorflow_issues_29629.py` and run on each node with fully qualified domain names `master` and `slave1`:
```
python tensorflow_issues_29629.py `hostname -f` 
```
or set different index of worker in TF_CONFIG in `tensorflow_issues_29629.py` on different nodes.

```python
import tensorflow as tf
import tensorflow.keras as keras
import types
import numpy as np
import json
import os
import sys

hostname_idx = {
    "master": 0,
    "slave1": 1
}
worker_index = hostname_idx[sys.argv[1]]


os.environ['TF_XLA_FLAGS'] = '--tf_xla_cpu_global_jit'
os.environ['TF_CONFIG'] = json.dumps({
    'cluster': {
        'worker': ["master:1531",
                   "slave1:1531"
                  ]
    },
    'task': {'type': 'worker', 'index': worker_index}
})

mirrored_strategy = tf.distribute.experimental.MultiWorkerMirroredStrategy()
options_distribute = tf.data.Options()
options_distribute.experimental_distribute.auto_shard = True

def sliding_window(values, window_size=2, stride=1, start=0):
    i = start
    r = None
    if i+window_size <= len(values):
        yield values[i:i+window_size]
    while True:
        i = i+stride
        if (i+window_size-1) < len(values):
            yield values[i:i+window_size]
        else:
            break
            
num_timesteps = 100
num_timesteps_to_predict = 1000
num_signals = 2
num_inputs = num_signals*num_timesteps_to_predict
batch_size = 2**5
epochs = 100

dataset = types.SimpleNamespace()
dataset.xmin = 0
dataset.xmax = 50
dataset.size = 100000
dataset.split_train_ratio = 0.9

dataset.x = np.linspace(dataset.xmin, dataset.xmax, dataset.size)
dataset.y = np.array([np.sin(dataset.x*(i+1)) for i in range(num_signals)])
dataset.input = np.array([list(sliding_window(y,
                                    window_size=num_timesteps,
                                    stride=1,
                                    start=0))[:-num_timesteps_to_predict] for y in dataset.y])
dataset.target = np.array([list(sliding_window(y,
                                     window_size=num_timesteps_to_predict,
                                     stride=1,
                                     start=num_timesteps)) for y in dataset.y])

dataset.input = np.transpose(dataset.input, axes=[1,2,0])
dataset.target = np.transpose(dataset.target, axes=[1,2,0])

dataset.target = dataset.target.reshape((dataset.target.shape[0], dataset.target.shape[1]*dataset.target.shape[2]))

split_point = int(len(dataset.input)*dataset.split_train_ratio)
split_point = (split_point//batch_size)*batch_size
dataset.train_input = dataset.input[:split_point]
dataset.train_target = dataset.target[:split_point]


input_dataset = tf.data.Dataset.zip((tf.data.Dataset.from_tensor_slices(dataset.train_input), 
                                     tf.data.Dataset.from_tensor_slices(dataset.train_target)))
input_dataset = input_dataset.padded_batch(batch_size, 
                                           ((num_timesteps, num_signals), 
                                            (num_timesteps_to_predict*num_signals)),
                                           drop_remainder=False)
# Check failed: size >= 0 (-19 vs. 0) <-> drop_remainder=False
# Check failed: size >= 0 (-16 vs. 0) <-> drop_remainder=True
# num_inputs, batch_size, length of dataset, epochs do not change this value

input_dataset = input_dataset.shuffle(dataset.size)
input_dataset = input_dataset.with_options(options_distribute)

print('Train dataset shape', dataset.train_input.shape)
print('MultiWorkerMirroredStrategy: ', mirrored_strategy)


with mirrored_strategy.scope():
    inputs = keras.Input(shape=(num_timesteps, num_signals), name='input')
    lstm = keras.layers.LSTM(num_inputs)(inputs)
    model = keras.Model(inputs=inputs, outputs=lstm)
    optimizer = keras.optimizers.RMSprop(lr=1e-3)
    model.compile(loss=keras.losses.mean_squared_error,
                  optimizer=optimizer,
                  metrics=['accuracy'])
    
model.fit(input_dataset, epochs=epochs)
model.save('past_100_pred_1000_model.h5') 
```

**Other info / logs**

One guess is that protobuf or python->cpp marshalling is broken.. Python, tensorflow, protobuf version are the same across machines.

```
libprotobuf               3.8.0                h8b12597_0    conda-forge
protobuf                  3.8.0            py36he1b5a44_0    conda-forge
```

**Comment by rchao** [comment]
Hello protsenkovi, thanks for reporting the issue. Can you provide a stack trace so there's more information for us to look into it?

**Comment by protsenkovi** [comment]
@rchao Excuse me, rchao, I thought about your request several times and do not understand how to do that. The only message I get now on error is from CHECK_GE in tensorflow/core/framework/tensor_shape.cc:324. Should I get C++ stacktrace? Can I do it without recompilation?

**Comment by rchao** [comment]
No problem. Can you do me a favor and check if you'd still get the same error without using tf.distribute.Strategy? That is, removing `with mirrored_strategy.scope():` and see what happens. Thanks.

**Comment by protsenkovi** [comment]
@rchao I have removed this line and it is training as expected. 

```
Epoch 1/100
  71/2781 [..............................] - ETA: 2:28:00 - loss: 0.4671 - accuracy: 0.0000e+00
```

**Comment by rchao** [comment]
Thanks! That's useful to know. Will post here once there's some update.

**Comment by rchao** [comment]
@protsenkovi I tried a few times but never successfully reproduced this issue (with python 3 and TF 2 enabled). Are you able to repro the issue consistently?

**Comment by protsenkovi** [comment]
@rchao Unfortunately, yes. I've checked it again with `env_dirs` and `pkgs_dirs` pointing to the same nfs folders now and got the same behaviour.

**Comment by jvishnuvardhan** [comment]
@protsenkovi Is this still an issue? Can you check with `TF2.0` and let us know whether the issue persists with latest TF version. Thanks!

**Comment by protsenkovi** [comment]
@jvishnuvardhan With latest stable release of TF 2.0 the issue is gone.

**Comment by jvishnuvardhan** [comment]
I am closing the issue as it was resolved in `TF2.0`. Please feel free to open it if the issue persists again. Thanks!
