### ISSUE TITLE
[TF 2.0 API Docs]  tf.io.read_file

### ISSUE THREAD

**Issue by SimiCode** [tensorflow/tensorflow#29648]
## URL(s) with the issue:
https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/io/read_file

### Clear description
The description does not give recommendations of when and when not to use this symbol.

### Correct links
The link to the source code file (python/ops/gen_io_ops.py) is dormant.

### Raises listed and defined
Errors are not defined.

### Usage example
No usage example provided.

### Submit a pull request?
Yes

**Comment by rmothukuru** [comment]
@SimiCode,
Detailed description, along with usage examples are present in the Nightly Version. Please refer the [Nightly Version of Documentation of tf.io.read_file](https://www.tensorflow.org/api_docs/python/tf/io/read_file?version=nightly). Thanks!
