### ISSUE TITLE
[TF 2.0 API Docs] tf.io.FixedLenFeature

### ISSUE THREAD

**Issue by Emanuz** [tensorflow/tensorflow#29646]
## Existing Url with the issue:
https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/io/FixedLenFeature

## Description of issue (what needs changing):
Clear description with parameters, returns and usage example
### Correct links
The link to the python script where the function is define is active https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/io/FixedLenFeature

### Parameters defined
No parameters defined

### Returns defined
No returns defined

### Raises listed and defined
The raises is defined further in this link
https://github.com/tensorflow/tensorflow/blob/r2.0/tensorflow/python/ops/parsing_ops.py

###Are the errors defined? For example,
Errors are not defined

### Usage example
Usage example provided in this link https://www.tensorflow.org/beta/tutorials/load_data/tf_records

**Comment by rmothukuru** [comment]
Created [a CL](https://critique-ng.corp.google.com/cl/373339875) to fix this issue. Thanks!
