### ISSUE TITLE
Fail to activate tensorflow

### ISSUE THREAD

**Issue by zxzhijia** [tensorflow/tensorflow#2965]
I installed tensorflow on raspberry pi but fail to activate it:

pi@raspberrypi:~ $ sudo pip install ./tensorflow-0.8.0-cp27-none-linux_armv7l.whl 
Unpacking ./tensorflow-0.8.0-cp27-none-linux_armv7l.whl
Requirement already satisfied (use --upgrade to upgrade): numpy>=1.8.2 in /usr/lib/python2.7/dist-packages (from tensorflow==0.8.0)
Requirement already satisfied (use --upgrade to upgrade): protobuf==3.0.0b2 in /usr/local/lib/python2.7/dist-packages (from tensorflow==0.8.0)
Requirement already satisfied (use --upgrade to upgrade): wheel in /usr/lib/python2.7/dist-packages (from tensorflow==0.8.0)
Requirement already satisfied (use --upgrade to upgrade): six>=1.10.0 in /usr/local/lib/python2.7/dist-packages/six-1.10.0-py2.7.egg (from tensorflow==0.8.0)
Installing collected packages: tensorflow
Successfully installed tensorflow
Cleaning up...
pi@raspberrypi:~ $ source activate tensorflow
-bash: activate: No such file or directory
pi@raspberrypi:~ $

**Comment by mrry** [comment]
`activate` is typically only used if you install TensorFlow in a virtualenv. Since you don't appear to have done this, you should be able to use TensorFlow straight away, e.g. by running `python` and typing `import tensorflow as tf` at the prompt.

**Comment by zxzhijia** [comment]
Thank you very much. It works.
