### ISSUE TITLE
Bug on `gather_nd` with gradient.

### ISSUE THREAD

**Issue by Sangwon91** [tensorflow/tensorflow#29656]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 16.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): pip
- TensorFlow version (use command below): tf2-gpu-beta
- Python version: 3.6.8
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 
- GPU model and memory:

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
A simple test code
```python
v = tf.Variable(np.random.uniform(size=[2,2]), dtype=tf.float32)

with tf.GradientTape() as tape:
    l = tf.gather_nd(v, [[1, 1]])
    l = tf.reduce_sum(l)
    
grads = tape.gradient(l, v)
print(grads)
````
gives following error message
```
---------------------------------------------------------------------------
LookupError                               Traceback (most recent call last)
<ipython-input-12-28efd3aa3042> in <module>
      5     l = tf.reduce_sum(l)
      6 
----> 7 grads = tape.gradient(l, v)
      8 print(grads)

~/anaconda3/envs/tf2/lib/python3.6/site-packages/tensorflow/python/eager/backprop.py in gradient(self, target, sources, output_gradients, unconnected_gradients)
   1000         output_gradients=output_gradients,
   1001         sources_raw=flat_sources_raw,
-> 1002         unconnected_gradients=unconnected_gradients)
   1003 
   1004     if not self._persistent:

~/anaconda3/envs/tf2/lib/python3.6/site-packages/tensorflow/python/eager/imperative_grad.py in imperative_grad(tape, target, sources, output_gradients, sources_raw, unconnected_gradients)
     74       output_gradients,
     75       sources_raw,
---> 76       compat.as_str(unconnected_gradients.value))

~/anaconda3/envs/tf2/lib/python3.6/site-packages/tensorflow/python/eager/backprop.py in _gradient_function(op_name, attr_tuple, num_inputs, inputs, outputs, out_grads, skip_input_indices)
    131   """
    132   mock_op = _MockOp(attr_tuple, inputs, outputs, op_name, skip_input_indices)
--> 133   grad_fn = ops._gradient_registry.lookup(op_name)  # pylint: disable=protected-access
    134   if grad_fn is None:
    135     return [None] * num_inputs

~/anaconda3/envs/tf2/lib/python3.6/site-packages/tensorflow/python/framework/registry.py in lookup(self, name)
     95     else:
     96       raise LookupError(
---> 97           "%s registry has no entry for: %s" % (self._name, name))

LookupError: gradient registry has no entry for: ResourceGatherNd
```
**Describe the expected behavior**
the grads should be `[[0, 0], [0, 1]]` but error occurs. 

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by Sangwon91** [comment]
I just found very weird behavior.
If I replace v to v+0 like below,
```python
v = tf.Variable(np.random.uniform(size=[2,2]), dtype=tf.float32)

with tf.GradientTape() as tape:
    l = tf.gather_nd(v+0, [[1, 1]])
    l = tf.reduce_sum(l)
    
grads = tape.gradient(l, v)
print(grads)
```
it gives expected result...
```
tf.Tensor(
[[0. 0.]
 [0. 1.]], shape=(2, 2), dtype=float32)
```
It seems the direct access to variables with `gather_nd` ruines something unexpected...

**Comment by gadagashwini** [comment]
@Sangwon91 I could able to reproduce the reported issue with Tensorflow 2.0.0.beta0. Thanks!
