### ISSUE TITLE
[TF 2.0 API Docs] tf.lite.OpHint.OpHintArgumentTracker

### ISSUE THREAD

**Issue by Denis-kisina** [tensorflow/tensorflow#29654]
URL(s) with the issue:
https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/lite/OpHint/OpHintArgumentTracker

Description of issue (what needs changing):
The link to the TF 2.0 API Documentation is broken, it does not link to the documentation of the API. So, there is no documentation of TF 2.0 for this function.

**Comment by jvishnuvardhan** [comment]
@Denis-kisina Where did you find this link? We need to correct that page to route the target to correct location. Thanks!

**Comment by Denis-kisina** [comment]
@jvishnuvardhan this is the documents link. https://docs.google.com/spreadsheets/d/1p3vqbocbKmcZQGrlxk9m2jHuleu8yr-XRbfKum0IDD8/edit#gid=0

**Comment by jvishnuvardhan** [comment]
@Denis-kisina Currently there is no documentation for that op. [Here](https://www.tensorflow.org/api_docs/python/tf/lite/OpHint/OpHintArgumentTracker) is the link to TF1.13 version of that op. Thanks!

**Comment by amahendrakar** [comment]
@Denis-kisina,
The documentation of that API for 2.x version can be found here
https://www.tensorflow.org/api_docs/python/tf/compat/v1/lite/OpHint/OpHintArgumentTracker

Thanks!
