### ISSUE TITLE
[TF 2.0 API Docs] tf.lite.OpHint

### ISSUE THREAD

**Issue by Denis-kisina** [tensorflow/tensorflow#29653]
## URL(s) with the issue:
https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/lite/OpHint

## Description of issue (what needs changing):
The link to the TF 2.0 API Documentation  is broken, it does not link to the documentation of the API. So, there is no documentation of TF 2.0 for this function.

**Comment by gadagashwini** [comment]
@Denis-kisina In Tflite 2.0 version lite.OpHint has removed. Please have a look on [release](https://github.com/tensorflow/tensorflow/releases#TensorFlow%20Lite) note. Thanks!

**Comment by gadagashwini** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
