### ISSUE TITLE
[TF 2.0 API Docs] tf.data.experimental

### ISSUE THREAD

**Issue by kabahima** [tensorflow/tensorflow#29650]
## Existing URLs containing the issue:
https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/data/experimental

## Description of the issue:
Correct Links: All links are correct and well defined

## Clear Description

The description is not clear about when to use this symbol 

## Usage Example
No usage example is provided.

## Parameters Defined
Parameters are poorly defined, and not formatted appropriately.

## Returns Defined
Returns are not defined.

## Raises Listed and Defined
Errors are not defined.

## Visuals, if Applicable
No visuals are included.

**Comment by jvishnuvardhan** [comment]
@kabahima This `Experimental API` page lists overview of the methods available in this API.  so, it is not required to have any usage examples or returns defined for this API. 

For example, `Counter` method under `Experimental API` clearly shows examples and arguments are shown.

https://www.tensorflow.org/versions/r2.5/api_docs/python/tf/data/experimental/Counter

If you see anything is missing for those methods under `Experimental API`, then please raise a new issue. 

I am closing this issue. Please feel free to reopen if I am mistaken. Thanks!
