### ISSUE TITLE
[TF 2.0 API Docs] tf.data.experimental.Counter

### ISSUE THREAD

**Issue by TrevorNathan** [tensorflow/tensorflow#29652]
Thank you for submitting a TensorFlow documentation issue. Per our GitHub
policy, we only address code/doc bugs, performance issues, feature requests, and
build/installation issues on GitHub.

The TensorFlow docs are open source! To get involved, read the documentation
contributor guide: https://www.tensorflow.org/community/contribute/docs

## URL(s) with the issue:

Please provide a link to the documentation entry, for example:
https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/data/experimental/Counter

### Clear description
The description is not clear, not provided as in the DOCS

### Raises listed and defined
Errors are not defined at all

### Request visuals, if applicable
No visuals are included

### Submit a pull request?
Yes

**Comment by nikitamaia** [comment]
Hi @TrevorNathan, late response here but can you take a look a[ look at the 2.4 API docs for Counter](https://www.tensorflow.org/api_docs/python/tf/data/experimental/Counter) and let me know if the description is now clear?

**Comment by jvishnuvardhan** [comment]
@TrevorNathan I think this was resolved in recently updated page https://www.tensorflow.org/versions/r2.5/api_docs/python/tf/data/experimental/Counter .

I am closing this issue as this was resolved. Please feel free to reopen if I am mistaken. Thanks!
