### ISSUE TITLE
Updating NCCL from 2.3.5 to 2.4.7 broke the build

### ISSUE THREAD

**Issue by wdirons** [tensorflow/tensorflow#29662]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): tensorflow/tensorflow:devel-gpu-py3 docker image
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): source
- TensorFlow version: master / HEAD / 21f595c4c6a92ade7fa650d004cdb32c7e80ecf5
- Python version: 3.6.7
- Installed using virtualenv? pip? conda?: source
- Bazel version (if compiling from source): 0.24.1
- GCC/Compiler version (if compiling from source): 7.4.0
- CUDA/cuDNN version: 10.0 / 7
- GPU model and memory: 2 P100 16 GB GPUs

**Describe the problem**

bazel build fails with

```
ERROR: /root/.cache/bazel/_bazel_root/efb88f6336d9c4a18216fb94287b8d97/external/nccl_archive/BUILD.bazel:69:1: undeclared inclusion(s) in rule '@nccl_archive//:nccl':
this rule is missing dependency declarations for the following files included by 'external/nccl_archive/src/collectives/broadcast.cc':
  'external/nccl_archive/src/collectives/collectives.h'
```

**Provide the exact sequence of commands / steps that you executed before running into the problem**

```
docker pull tensorflow/tensorflow:devel-gpu-py3
docker run -idt --name nccl-failure docker.io/tensorflow/tensorflow:devel-gpu-py3 bash
docker attach nccl-failure

cd $HOME
git clone https://github.com/tensorflow/tensorflow
cd tensorflow/
./configure  [pressed enter for all prompts]
bazel build //tensorflow/tools/pip_package:build_pip_package
```

**Any other info / logs**
Error started after Commit 5b5ada737a7f2c69c51748b0f54636b6849580a5 "Update NCCL from 2.3.5 to 2.4.7" was merged.

**Comment by freedomtan** [comment]
I ran into the same problem. Quick fix for this problem:
```diff
diff --git a/third_party/nccl/archive.BUILD b/third_party/nccl/archive.BUILD
index 6604541..4dc7d9a 100644
--- a/third_party/nccl/archive.BUILD
+++ b/third_party/nccl/archive.BUILD
@@ -55,6 +55,7 @@ cuda_rdc_library(
     name = "device",b/third_party/nccl/archive.BUILD
     srcs = [
         "src/collectives/device/functions.cu.cc",
+        "src/collectives/device/common.h",
         ":device_srcs",
     ],
     deps = [
```

**Comment by byronyi** [comment]
A side note: if you install the same NCCL development package in your environment, you will not reproduce this error.

**Comment by freedomtan** [comment]
@byronyi which means using headers from installed NCCL instead of the one fetched by bazel?

**Comment by wdirons** [comment]
@freedomtan , Thank you for the fix. You should submit a pull request to get this fixed in the master branch. (I can but I don't want to take credit for your work. :) )

**Comment by freedomtan** [comment]
@wdirons I didn't send PR because this quick fix is dirty. there should be more elegant way :)

**Comment by freedomtan** [comment]
@wdirons in case you didn't notice it. should be fixed by 7aaf366 which rollbacked 5b5ada7 :-)

**Comment by wdirons** [comment]
Thank you @freedomtan , I hadn't seen it. (First time I logged in since the commit was rolled back.) Thank you!

**Comment by byronyi** [comment]
@chsigg Any chance this change will be submitted soon? I see that at NCCL 2.4.2 it got a serious bug for long-running jobs, and has been upgraded to 2.4.6 for PyTorch: https://github.com/pytorch/pytorch/issues/20630

**Comment by chsigg** [comment]
Yes, it will be resubmitted shortly.
