### ISSUE TITLE
tf.layers.dense deprecation update hint

### ISSUE THREAD

**Issue by BreakBB** [tensorflow/tensorflow#29677]
Referencing the deprecation hint of https://www.tensorflow.org/api_docs/python/tf/layers/dense

## Description of issue (what needs changing):

I wasn't able to find the referenced `tf.keras.layers.dense`, but only `tf.keras.layers.Dense`. Could this be a simple typo and the latter was ment to be pointed to?

### Submit a pull request?

If this is a simple issue and not a functionality missing or a fault of me not finding the referenced method, then yes, I would PR it.

**Comment by ymodak** [comment]
Submitted a PR[https://github.com/tensorflow/tensorflow/pull/29827] to fix the issue. Thanks!
