### ISSUE TITLE
tf.image.crop_and_resize 

### ISSUE THREAD

**Issue by ruinianxu** [tensorflow/tensorflow#29672]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 14.04):
- TensorFlow installed from (binary):
- TensorFlow version (1.9):

Hi all, 
I am looking at op crop_and_resize which takes image, boxes, box_index and crop_size as input. My question is why dimension of boxes is (num_boxes by, 4) while image has (batch, height, width, depth). Does it mean the same boxes for every image? And output is also (num_boxes, crop_height, crop_width, depth). Should it be (batch, num_boxes, crop_height, crop_width, depth)? 
Thanks in advance for any help.

**Comment by gadagashwini** [comment]
@ruinianxu It Looks This is not Build/Installation or Bug/Performance issue. Please post this kind of support questions at [StackOverflow](http://stackoverflow.com/questions/tagged//tensorflow). There is a big community to support and learn from your questions. GitHub is mainly for addressing bugs in installation and performance. Thanks!

**Comment by gadagashwini** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Comment by bvm84** [comment]
"Should it be (batch, num_boxes, crop_height, crop_width, depth)?" - It seems it shoud, but not implemented. In current state crop_and_resize breaks data flow in graph mode.
