### ISSUE TITLE
the tfdbg CLI does not apepar  in tensorflow alpha2.0

### ISSUE THREAD

**Issue by aaronlyt** [tensorflow/tensorflow#29679]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):   Linux Ubuntu 18.04
- TensorFlow installed from (source or binary):   pip install
- TensorFlow version (use command below):   tensorflow apha 2.0
- Python version:   3.6.3
- CUDA/cuDNN version:   CUDA Version 10.1.105, cudnn 7.5
- GPU model and memory:   GTX 2080TI

*Describe the current behavior**
```
from tensorflow.python import debug as tf_debug
keras.backend.set_session(\
        tf_debug.LocalCLIDebugWrapperSession(tf.compat.v1.Session()))
```
**the tfdbg CLI does not apepar**, I want to know what is the problem, and how to solve it

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

```
import sys
import os
import json
import numpy as np
import tensorflow as tf
import tensorflow.keras as keras

os.environ['CUDA_VISIBLE_DEVICES'] = ''

def basic_generator():
    """
    """
    data_x = [[0, 1, 2, 3], [1, 2, 3, 4], \
        [0, 1, 3, 4], [0, 2, 1, 4]]
    data_y = [[0, 1, 2, 3], [1, 2, 3, 4], \
        [0, 1, 3, 4], [0, 2, 1, 4]]
    for x, y in zip(data_x, data_y):
        yield (x, y)

if __name__ == "__main__":
    params = { 
       'seq_len': 8,
        'use_bert': False,
        'batch_size': 2,
        'epochs': 5,
        'vocab_len': 5,
        'num_entities': 3,
        'use_pre_emb': False,
        'emb_dim': 20,
        'use_emb_drop': False,
        'emb_drop_rate': 0.8,
        'num_layer': 1,
        'num_lstm_cell': [15],
        'rec_drops': [0.8],
        'lr': 0.001
    }

    output_types = (tf.int32, tf.int32)
    dataset = tf.data.Dataset.from_generator(\
        basic_generator, output_types)
    dataset = dataset.padded_batch(\
        params['batch_size'], \
            ([params['seq_len'], ], [params['seq_len'], ]))

    from tensorflow.python import debug as tf_debug
    keras.backend.set_session(\
        tf_debug.LocalCLIDebugWrapperSession(tf.compat.v1.Session()))

    dataset = dataset.map(lambda x, y: (x, tf.one_hot(y, params['num_entities'])))
    dataset = dataset.repeat(params['epochs'])
    
    #model = LstmCrf(params)
    model = keras.Sequential()
    inputs = keras.Input(shape=(None, ))
    emb_ini = keras.initializers.TruncatedNormal()
    model.add(keras.layers.Embedding(\
                params['vocab_len'], params['emb_dim'], \
                    embeddings_initializer=emb_ini, mask_zero=True))        
    model.add(keras.layers.TimeDistributed(\
        keras.layers.Dense(params['num_entities'])))
    model.add(keras.layers.Activation('softmax'))
       
    model.compile(optimizer=keras.optimizers.Adam(params['lr']), \
        loss='categorical_crossentropy', \
            metrics=['accuracy'])

    model.fit(dataset, epochs=params['epochs'], \
        steps_per_epoch=2)
    
```

**Comment by achandraa** [comment]
Can you give a try with CUDA 10.0 and let us know if you are still stuck. I have tried with 2.0-alpha on CUDA 10.0  Colab (GPU- Tesla T4) and was able to execute the snippet provided without any issue. Thanks!

**Comment by caisq** [comment]
Adding myself (owner of tfdbg).

**Comment by achandraa** [comment]
Is this still an issue ? Please reach out to us in case you are stuck or else we can close the issue for now. Thanks!

**Comment by aaronlyt** [comment]
surprise, it give me new error: AttributeError: module 'tensorflow.keras.backend' has no attribute 'set_session'

**Comment by achandraa** [comment]
Have tried following snippet on Colab with TF version 2.0-alpha but did not get any error :

import tensorflow as tf 
from tensorflow.python import debug as tf_debug
import tensorflow.keras as keras
keras.backend.set_session(\
        tf_debug.LocalCLIDebugWrapperSession(tf.compat.v1.Session()))

Can you try this and let us know if you are still stuck. Thanks!

**Comment by aaronlyt** [comment]
I still have this error

**Comment by jimhoprogramming** [comment]
i think you use the "import tensorflow.keras as keras" point to tf2.0 api. but setup tfdebug using "LocalCLIDebugWrapperSession"  this call old version tf to get the session . then two version do not merge.
but i want to konw how to use  new tf 2.0 that no session api to load tfdebug? Tfdebug need session.

**Comment by caisq** [comment]
@jimhoprogramming 

TF Debugger (tfdbg) for TF v2.0 is still being designed and will be made available at a later time. As you pointed out, tfdbg is originally designed for TF v1.x and is centered around the tf.Session API. As tf.Session is replaced by eager execution and tf.functions in 2.0, the debugger feature needs to be adapted to the architectural change.

If you have a specific use case (e.g., finding Infinities and NaNs, or other debugging workflows), please let us know. It'll inform the design of the new version of tfdbg.

cc @alextp @mdan @wicke @bileschi

**Comment by caisq** [comment]
cc @GalOshri

**Comment by jimhoprogramming** [comment]
Thanks,I debugging for some cnn having NaN case indeed.so,only way it was go black to tf v1.6 to do it.

**Comment by amahendrakar** [comment]
@aaronlyt,
Could you please update TensorFlow to the latest stable version v2.4 and check if you are facing the same issue?

Also, please go through [this debugging guide](https://www.tensorflow.org/tensorboard/debugger_v2) and check if it helps. Thanks!
