### ISSUE TITLE
can not start session

### ISSUE THREAD

**Issue by gggh000** [tensorflow/tensorflow#29682]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version (use command below):
- Python version:
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**

**Describe the expected behavior**

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by gggh000** [comment]
Python crash after creating a session after import tensorflow.


root@guyen-MS-7B22:/home/guyen# python3
Python 3.6.7 (default, Oct 22 2018, 11:32:17)
[GCC 8.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
>>> sess = tf.Session()
2019-06-12 08:39:58.346199: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
terminate called after throwing an instance of 'ihipException'
  what():  std::exception
Aborted (core dumped)
root@guyen-MS-7B22:/home/guyen# pip3 freeze | grep tensorflow
tensorflow-estimator==1.13.0
tensorflow-gpu==1.13.1
tensorflow-rocm==1.13.3
root@guyen-MS-7B22:/home/guyen# uname -r
4.18.0-21-generic
root@guyen-MS-7B22:/home/guyen# lsb_release --all
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.2 LTS
Release:        18.04
Codename:       bionic
root@guyen-MS-7B22:/home/guyen#

**Comment by wysohn** [comment]
To use tensorflow-gpu, you have to install cudnn with cuda installed.

if you have installed them, make sure the LD_LIBRARY_PATH is correctly set and pointing to where the cudnn libraries are located.

They usually reside in /usr/loca/cuda/, so `echo $LD_LIBRARY_PATH` should give you some path to the library if you have set up your environment correctly.

Also, note that cudnn seem to be version specific, so you have to install a specific version, libcublas.so.10.0 in your case, to make it work.

**Comment by achandraa** [comment]
@gggh000 : Did you try following the steps mention in [TensorFlow website](https://www.tensorflow.org/install/pip). Please have a look on the instruction from the link to install TF using pip or source. Also have a look on software requirement for TensorFlow various versions [here](https://www.tensorflow.org/install/gpu#software_requirements). Thanks!

**Comment by gggh000** [comment]
I don't understand the response. You said cudnn to be installed but on nvidia website says cudnn is installed a part of the cuda toolkit. After installation, i don't see cudnn and your instruction does not specify where to find it either. I don't see any specific download link available that downloads cudnn, any link for cudnn brings back to main cuda installer url.

**Comment by gggh000** [comment]
I am using 10.0

**Comment by gggh000** [comment]
No my response below was wrong that was my initial attempt. I located and installed installer for cudnn both runtime and developer version but still did not work ofr ubuntu 1804. I will post the error message later.

**Comment by wysohn** [comment]
Sorry for being vague if you are responding to me.

Anyway, the point here is that libcublas.so.10.0 should be present in the $LD_LIBRARY_PATH

That's where tensorflow-gpu looks for the necessary library for GPU acceleration.

If `echo $LD_LIBRARY_PATH` prints out something rather than empty string, then libcublas.so.10.0 is not present in that location.

I didn't try the cuda toolkit myself so cannot say anything about it, but if it's indeed an automatic installation, it also had to set appropriate $LD_LIBRARY_PATH

**Comment by gggh000** [comment]
how could i expect the rest of the journey to be smooth? I can not do as simple as installing tensorflow-gpu version without huge complication encountered here and you guys are not even sure what is the problem?

**Comment by wysohn** [comment]
You may find this link useful: https://www.tensorflow.org/install/gpu

**Comment by gggh000** [comment]
it locked up the whole login screen when i followed the instruction

**Comment by ymodak** [comment]
Sorry to hear you are having a difficult time installing TF. From the error message,
```
File "/usr/lib/python3.6/imp.py", line 343, in load_dynamic
return _load(spec)
ImportError: libcublas.so.10.0: cannot open shared object file: No such file or directory
```
we are certain that it has arisen due to incorrect cuda path to the environment. Please take a look at [linux setup guide](https://www.tensorflow.org/install/gpu#linux_setup) if haven't already.

You can also try installing TF-CPU version by simply,
``` pip install tensorflow```
Thanks!

**Comment by ymodak** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Comment by gggh000** [comment]
please re-opened it, it is not fixed yet.

**Comment by gggh000** [comment]
why are you recommending cpu version when I specifically want GPU??

**Comment by ymodak** [comment]
Can you please attach a screenshot of your Environment variables?

**Comment by ymodak** [comment]
Automatically closing due to lack of response. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
