### ISSUE TITLE
Error building hlo_verifier_test.cc

### ISSUE THREAD

**Issue by DavidNorman** [tensorflow/tensorflow#29684]
```
tensorflow/compiler/xla/service/hlo_verifier_test.cc:719:31: error: 'StrReplaceAll' is not a member of 'absl'
   return ParseHloString(absl::StrReplaceAll(
                               ^~~~~~~~~~~~~
```

- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes - but no changes to this file.
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): ubuntu 18.04
- TensorFlow installed from (source or binary): source build
- TensorFlow version (use command below): master
- Python version: master build
- Bazel version (if compiling from source): 0.24.1
- GCC/Compiler version (if compiling from source): gcc (Ubuntu 7.3.0-27ubuntu1~18.04) 7.3.0

When building from source including XLA I receive the error above.

**Comment by ravikyram** [comment]
Just to verify did you get chance to follow instructions from [TensorFlow website](https://www.tensorflow.org/install/source) .Please, let us know. Thanks

**Comment by ravikyram** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
