### ISSUE TITLE
TF2-BETA: Model inputs check bug with new feature: distribute model without cloning.

### ISSUE THREAD

**Issue by ziyigogogo** [tensorflow/tensorflow#29680]
**System information**
- Have I written custom code: Yes
- OS Platform: Win10
- TensorFlow installed: pip install
- TensorFlow version: tensorflow-gpu==2.0.0-beta0 and tf-nightly-gpu-2.0-preview==2.0.0.dev20190509
- Python version: 3.6

**Describe the current behavior**
Distribute strategy cannot properly handle dict/tuple type inputs in tensorflow-gpu==2.0.0-beta0 while there is no problem in non-distribute scenario.

What the interesting thing is that in tf2.0-alpha, the bug existed already, but later in tf-nightly-gpu-2.0-preview==2.0.0.dev20190509. The problem seems to be solved. In that version, both distribute/non-distribute scenarios works good with dict type inputs. But I dont know why this bug appears again in beta version.

I thought this problem is caused when distribute strategy trying to slice the inputs equally to all replica. Maybe the input parse method in distribute strategy is not fully tested. But since there is no public change log for tf-nightly. So i myself cannot dig this anymore without the help of tf team members.

```python
import tensorflow as tf
from tensorflow.python.keras import layers as KL
from tensorflow.python.keras import models as KM
import numpy as np

def custom_loss(predict, label, weight):
    bce = tf.losses.binary_crossentropy(label, predict)
    return tf.reduce_mean(bce * weight)

def create_model():
    input_img = KL.Input([64, 64, 3], name="img")
    input_lbl = KL.Input([64, 64, 1], name="lbl")
    input_weight = KL.Input([64, 64], name="weight")
    predict = KL.Conv2D(2, [1, 1], padding="same")(input_img)
    my_loss = KL.Lambda(lambda x: custom_loss(*x), name="my_loss")([predict, input_lbl, input_weight])
    model = KM.Model(inputs=[input_img, input_lbl, input_weight], outputs=[predict, my_loss])
    model.add_loss(model.get_layer("my_loss").output)
    model.compile(optimizer="adam")
    return model

def get_dict_dataset():
    def map_fn(img, lbl, weight):
        inputs = {"img": img, "lbl": lbl, "weight": weight}
        targets = {}
        return inputs, targets

    fake_imgs = np.ones([50, 64, 64, 3])
    fake_lbls = np.ones([50, 64, 64, 1])
    fake_weights = np.ones([50, 64, 64])

    return tf.data.Dataset.from_tensor_slices((fake_imgs, fake_lbls, fake_weights)).map(map_fn).batch(10)
```
tensorflow-gpu==2.0.0-beta0
in non-distribute scenario:
```python
model = create_model()
data = get_dict_dataset()
model.fit(data)
10/10 [==============================] - 1s 143ms/step - loss: 0.0000e+00
```
in distribute scenario:
```python
strategy = tf.distribute.MirroredStrategy(cross_device_ops=tf.distribute.HierarchicalCopyAllReduce())
with strategy.scope():
    model = create_model()
    data = get_dict_dataset()
    model.fit(data)
AttributeError: 'dict' object has no attribute 'shape'
```
Still not working Even if i change the dict to tuple:
```python
def get_tuple_dataset():
    def map_fn(img, lbl, weight):
        inputs = (img, lbl, weight)
        targets = tuple()
        return inputs, targets

    fake_imgs = np.ones([50, 64, 64, 3])
    fake_lbls = np.ones([50, 64, 64, 1])
    fake_weights = np.ones([50, 64, 64])

    return tf.data.Dataset.from_tensor_slices((fake_imgs, fake_lbls, fake_weights)).map(map_fn).batch(10)

with strategy.scope():
    model = create_model()
    data = get_tuple_dataset()
    model.fit(data)
ValueError: Error when checking model input: the list of Numpy arrays that you are passing to your model is not the size the model expected. Expected to see 3 array(s), but instead got the following list of 2 arrays
```

Again, the scenarios described above working good in  tf-nightly-gpu-2.0-preview==2.0.0.dev20190509. And again there is no public change log for tf-nightly so I cannot dig this any deeper alone.

**Describe the expected behavior**
Since the model behavior should be consistent. Tf team should decide weather to support dict type inputs. If no, both distribute/non-distribute model should not accept dict input and vice versa.

**Comment by ziyigogogo** [comment]
After tracing the inputs values, i finally found that:
the problem is caused by method "def _prepare_feed_values" in tensorflow/python/keras/distribute/distributed_training_utils.py
```python
def _prepare_feed_values(model, inputs, targets, sample_weights, mode):
  ...
  if isinstance(inputs, dict):
    inputs = [inputs[key] for key in model._feed_input_names]
  if is_distributing_by_cloning(model):
    inputs = flatten_per_replica_values(strategy, inputs)
    targets = flatten_per_replica_values(strategy, targets)
    # Expand 1-dimensional inputs.
    # TODO(b/124535720): Remove once this standarize data logic is shared with
    # main flow.
    inputs, targets = nest.map_structure(
        training_utils.standardize_single_array, (inputs, targets))
  ...
```
In tf2.0 beta, the return value of condition "if is_distributing_by_cloning(model)" is False, so that the inputs are not processed by "flatten_per_replica_values(strategy, inputs)" which will flat the dict type inputs to tensors. Then i continued to dig and found this in method "def compile" in tensorflow/python/keras/engine/training.py(line250):
```python
# Check whether the experimental feature of distributing the Model without
    # cloning is requested.
    # TODO(b/124517980, b/124377929): Remove this temporary undocumented way
    # of enabling the feature and graduate it to the main distributed code path.
    self._cloning = kwargs.pop('cloning', False)
    self._validate_compile_param_for_distribution_strategy(self.run_eagerly,
                                                           sample_weight_mode,
                                                           target_tensors,
                                                           weighted_metrics)
    self.optimizer = optimizers.get(optimizer)
```
Noticed that the arg: while in tf2.0-beta, the default value of "cloning" is False while in tf-nightly-0509 the value is True. So, here is the temp solution: in tf2.0-beta, when compiling the model, one should pass a kwarg cloning = True and everything behave the same as the previous version.

**But we should noticed that the temp solution is not meaning that there is no bug. As we see in the comment left in the source code:** 
```python
# Check whether the experimental feature of distributing the Model without cloning is requested.
```
At least we know that the feature "distributing model without cloning" should reconsider the current implementation in "def _prepare_feed_values" so that machine can know how to process dict/tuple type inputs for "non-cloning " accordingly. **Otherwise, the non-cloning feature should not enabled in a stable release in my understanding.**

**Comment by guptapriya** [comment]
Thank for you for reporting. We will take a look.

**Comment by isaprykin** [comment]
I submitted https://github.com/tensorflow/tensorflow/commit/6d00cb1a2f9303cb084ff2218700ab8479bc4e2b and https://github.com/tensorflow/tensorflow/commit/ce59aa0be80384d096a13efaca2b8c6e071b9a54 because of this issue and it should be resolved now.

Thanks for reporting and good debugging skills!  Re-open if still an issue.

**Comment by ziyigogogo** [comment]
@isaprykin hi, if this mean i will get the fixed version using latest tf-nightly?

**Comment by isaprykin** [comment]
Yes.
