### ISSUE TITLE
[TF 2.0 API Docs]  tf.keras.metrics.BinaryAccuracy

### ISSUE THREAD

**Issue by kabahima** [tensorflow/tensorflow#29683]
TensorFlow version: 2.0
## Existing URLs containing the issue:
https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/keras/metrics/BinaryAccuracy

## Description of the issue (what needs changing):

- #### Correct links: 
       Yes

- #### Clear Description: 
   No, The description does not  give recommendations of when and when not to use this symbol

- #### Usage Example: 
       Yes
- #### Parameters Defined:

  Parameters are poorly defined, and not formatted appropriately.
- ####  Returns Defined: 

    Returns are not defined
. 
- ####  Raises listed and Defined:

   Errors are not defined.

- #### Visuals if applicable: 
   No visuals are included.

**Comment by ymodak** [comment]
The docs are updated with TF 2.4 api docs. Thanks!
See https://www.tensorflow.org/api_docs/python/tf/keras/metrics/BinaryAccuracy
