### ISSUE TITLE
 [TF 2.0 API Docs] tf.keras.constraints.MinMaxNorm

### ISSUE THREAD

**Issue by kabahima** [tensorflow/tensorflow#29685]
# Existing URLs containing the issue:
https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/keras/constraints/MinMaxNorm
## Description of the issue (what needs changing):
- ### Correct links:
     Yes

- ###  Clear Description:
  No, The description does not give recommendations of when and when not to use this symbol

- ### Usage Example:
   No usage example 

- ### Parameters Defined:
   Parameters are Well defined

  - ### Returns are not defined

- ### Raises listed and Defined:
  Errors are not defined.

- ### Visuals if applicable:
  No visuals are included.

**Comment by rlrahulkanojia** [comment]
Waiting for a response as soon as possible.

**Comment by jvishnuvardhan** [comment]
More details about constraints is listed here https://keras.io/api/layers/constraints/

I am closing this issue as enough details are listed in the `keras.io`

Please note that Keras development moved to [keras-team/keras](keras-team/keras repo](https://github.com/keras-team/keras/issues) repository to focus entirely on only keras. Thanks!
