### ISSUE TITLE
[Find header file after build manually tensor flow lite]

### ISSUE THREAD

**Issue by TrungLM13** [tensorflow/tensorflow#29686]
Hello, I built tensorflow lite for ARM 64 on Linux.
And After building successful I have a library called "libtensorflow-lite.a"
As you know, if we want to use this lib, we have both lib and header file (.h file in my case).
But where can I get all header file for libtensorflow lib.
In result folder (gen folder in my case), I see bin, lib, object but include folder does't exist.

**Comment by kumariko** [comment]
@TrungLM13 Could you please let us know if you still need help on this ? if it is resolved then please feel free to move this issue to close status ? Thanks!
