### ISSUE TITLE
Get Per-sample Gradient for a Batch

### ISSUE THREAD

**Issue by qin-yu** [tensorflow/tensorflow#29694]
**System information**
- TensorFlow version (you are using): --
- Are you willing to contribute it (Yes/No): Yes, but not sure if I am able to.

**Describe the feature and the current behavior/state.**
Now when I do SGD on a model, the gradients for a batch is returned but I want an array of gradients such that each element corresponds to a sample in this batch.

**Will this change the current api? How?**
I assume we can achieve this by changing `optimizer.compute_gradients` or `tf.gradients`

**Who will benefit with this feature?**
There are other ways to use the gradients including the one I am trying to implement.

**Any Other info.**

**Comment by achandraa** [comment]
Thanks for reaching out to us. Can you please let us know to which TensorFlow version this feature will be intended to.

**Comment by qin-yu** [comment]
> Thanks for reaching out to us. Can you please let us know to which TensorFlow version this feature will be intended to.

to version 1.13 would be nice.

**Comment by alextp** [comment]
I think you can already achieve this using [tf.vectorized_map](https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/vectorized_map) and `tf.gradients`.

**Comment by qin-yu** [comment]
> I think you can already achieve this using [tf.vectorized_map](https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/vectorized_map) and `tf.gradients`.

Thanks! I'll look into that~
