### ISSUE TITLE
Tflite results dont match corresponding Tensorflow for Mobilenet.

### ISSUE THREAD

**Issue by ignvinay** [tensorflow/tensorflow#29693]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows10 and Ubuntu16.04
- TensorFlow installed from (source or binary): pip install tensorflow-gpu
- TensorFlow version (or github SHA if from source):1.13

[mobilenet_tflite_test.zip](https://github.com/tensorflow/tensorflow/files/3281327/mobilenet_tflite_test.zip)

**Provide the text output from tflite_convert**

```
# Copy and paste here
```

Also, please include a link to a GraphDef or the model if possible.
https://storage.googleapis.com/download.tensorflow.org/models/mobilenet_v1_1.0_224_frozen.tgz

**Any other info / logs**
Description : I am trying to quantize the Mobilenet using tflite. After converting , i used tensorflow to validate my results. I find that quantized results are not matching to float tensorflow based results.
I have an output for about 10 elements and maximum value index , both of them are mismatching as shown.
Please let me know whether i am missing any thing or is this real problem ?

_--------------------Float values are --------------------------
[-1.8004932  -0.23941718  0.61870384 -0.4235621  -1.1386781   0.99633265
  0.16455668  0.743189   -1.9882091  -1.270742  ]
Max Index  (array([420], dtype=int64),)
---------Fixed pt values are -----------------------------------
[-2. -8.  0. -6. -2. -6.  2. -2. -2. -2.]
Max Index  (array([812], dtype=int64),)_

Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by kumariko** [comment]
@ignvinay We are checking to see if you still need help on this issue, as you are using an older version of tensorflow(1.x) which is officially considered as end of life. We recommend that you upgrade to 2.6 which is latest stable version of TF and let us know if the issue still persists in newer versions. we will get you the right help.Thanks!
