### ISSUE TITLE
tensorflow 2.0 tf.data cache

### ISSUE THREAD

**Issue by celinew1221** [tensorflow/tensorflow#29697]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): NO
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 16.04
- TensorFlow installed from (source or binary): Binary pip3
- TensorFlow version (use command below):  2.0.0.dev20190523 
- Python version: 3.5
- CUDA/cuDNN version: 10/7
- GPU model and memory: Titan V 12GB

**Describe the current behavior**
Whenever using dataset.cache("tmp_disk_file"), memory keeps increasing even though I save them into a disk file.  

**Describe the expected behavior**
No memory usage difference with and without cache to disk.

**Code to reproduce the issue**
I don't have a code to regenerate the exact issue, but here is a pipeline sample.
```
list_of_tfrecords = [filename1, filename2, filename3]
# construct_dataset will form a pipeline to process data, 
# at the end of the pipeline, cache that pipeline for file
list_of_datasets_to_cache = [construct_dataset(filename) for filename in list_of_tfrecords]
train_dataset = tf.data.experimental.sample_from_datasets(list_of_datasets_to_cache)
```
Note: the reason I'm doing this is I have a very expensive pipeline, I want to speed up the second epoch. There's better way doing this, but I want to do it this way because I'm doing cross-validation, and if I cache by forming a pipeline with all files, then I can't reuse the cache (I'm going to change to different folds next epoch - i.e. new dataset).

**Comment by achandraa** [comment]
Will it be possible for you to present a minimal code snippet that can replicate the issue. This will help not only to understand the issue more clearly but also to proceed faster. Thanks!

**Comment by achandraa** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
