### ISSUE TITLE
Export FeatureColumn and subclasses

### ISSUE THREAD

**Issue by novog** [tensorflow/tensorflow#29709]
**System information**

- TensorFlow version (you are using): 2.0.0b0
- Are you willing to contribute it (Yes/No): Yes

**Describe the feature and the current behavior/state.**

TensorFlow should export the `FeatureColumn` class and all classes that are subclasses of it. Currently, only the functions used to construct objects of these types, such as `numeric_column`, are exported.

**Will this change the current api? How?**

Yes, it will change the current api by extending it.

**Who will benefit with this feature?**

- Developers who want to extend the provided `FeatureColumn` functionality, such as by subclassing `FeatureColumn` or by creating new functions to instantiate members of its existing subclasses
- Developers who document and/or verify their code using type annotations

**Any Other info.**

**Comment by rmothukuru** [comment]
@novog,
Sorry for the delayed response. In **`Tensorflow Version 2.x`**, as we recommend [TF Keras](https://www.tensorflow.org/api_docs/python/tf/keras) over [Estimators](https://www.tensorflow.org/guide/estimator) and the [Saved Model](https://www.tensorflow.org/guide/saved_model) over [Export Functionality](https://www.tensorflow.org/api_docs/python/tf/compat/v1/keras/experimental/export_saved_model), can you please let us know if this **`functionality`** is still relevant? Thanks!

**Comment by novog** [comment]
To be clear, by "export", I meant in the sense of making a Python class available in user code, not in the sense of saving models to disk. However, based on your comment about Estimators, I am guessing that Keras [Preprocessing Layers](https://keras.io/guides/preprocessing_layers/) are now preferred over `FeatureColumn`. Closing.
