### ISSUE TITLE
ERROR: Using multiple TPUs in a single session is not yet implemented

### ISSUE THREAD

**Issue by maxima120** [tensorflow/tensorflow#29701]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Debian 9
- TensorFlow installed from (source or binary): preinstalled
- TensorFlow version (use command below): 1.13.1
- Python version: 3.5

**Describe the current behavior**

Error when trying to use 2 x TPUs v3 in TPUClusterResolver

**Describe the expected behavior**

No error

Model
```
TPU_ADDRESS1 = 'grpc://10.240.1.2:8470'
TPU_ADDRESS2 = 'grpc://10.240.2.2:8470'
   
opt = tf.train.AdamOptimizer(0.01)

model.compile(optimizer=opt, loss='categorical_crossentropy', metrics=['categorical_accuracy'])

tpu_model = tf.contrib.tpu.keras_to_tpu_model(model, 
        strategy=tf.contrib.tpu.TPUDistributionStrategy(
            tf.contrib.cluster_resolver.TPUClusterResolver(tpu = [TPU_ADDRESS1,TPU_ADDRESS2])))
```
Error
```
/usr/local/lib/python3.5/dist-packages/tensorflow/python/distribute/cluster_resolver/tpu_cluster_resolver.py in __init__(self, tpu, zone, project, job_name, coordinator_name, coordinator_address, credentials, service, discovery_url)
    215       if len(tpu) != 1:
    216         raise NotImplementedError(
--> 217             'Using multiple TPUs in a single session is not yet implemented')
    218       tpu = tpu[0]
    219 

NotImplementedError: Using multiple TPUs in a single session is not yet implemented
```

**Comment by dangerzone** [comment]
Sorry to resurrect a year old issue, but I'm running into the same limitations. 

Are there any plans to support multiple TPUs not in a pod configuration?

**Comment by maxima120** [comment]
> Are there any plans to support multiple TPUs not in a pod configuration?

is TPU pod makes difference? could you please elaborate

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.

**Comment by bhack** [comment]
Please check https://cloud.google.com/tpu/docs/training-on-tpu-pods

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this issue, as you are using an older version of tensorflow(1.x) which is officially considered as end of life. We recommend that you upgrade to 2.4 or later version and let us know if the issue still persists in newer versions. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, Please open a new issue for any help you need against 2.x, and we will get you the right help.
