### ISSUE TITLE
TF problem when run with lingvo

### ISSUE THREAD

**Issue by sun-peach** [tensorflow/tensorflow#29719]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- Ubuntu 16.04:
- TensorFlow installed from pip:
- TensorFlow 1.13:
- 3.5:
- conda and pip:
- Bazel 0.26.1:
- 4.8:
- CUDA/cuDNN 10.0/ 7.5:
- RTX 2080 TI:

This may be not the proper area to ask. But I cannot find any other place to ask. I am running lingvo based on tensorflow. I follow their mnist demo and run:

bazel build -c opt //lingvo:trainer

It gives me an error:

Extracting Bazel installation...
Starting local Bazel server and connecting to it...
DEBUG: Rule 'subpar' indicated that a canonical reproducible form can be obtained by modifying arguments commit = "07ff5feb7c7b113eea593eb6ec50b51099cf0261", shallow_since = "1524766240 -0700" and dropping ["tag"]
INFO: Analyzed target //lingvo:trainer (37 packages loaded, 4470 targets configured).
INFO: Found 1 target...
ERROR: missing input file '@tensorflow_solib//:tensorflow_solib/libtensorflow_framework.so.1'
ERROR: /home/feit/.cache/bazel/_bazel_feit/965fc5b73beb9f5ea41273ac0e3737bf/external/tensorflow_solib/BUILD:2:1: @tensorflow_solib//:framework_lib: missing input file '@tensorflow_solib//:tensorflow_solib/libtensorflow_framework.so.1'
Target //lingvo:trainer failed to build
Use --verbose_failures to see the command lines of failed build steps.
ERROR: /home/feit/.cache/bazel/_bazel_feit/965fc5b73beb9f5ea41273ac0e3737bf/external/tensorflow_solib/BUILD:2:1 1 input file(s) do not exist
INFO: Elapsed time: 9.563s, Critical Path: 0.02s
INFO: 0 processes.
FAILED: Build did NOT complete successfully

What is this about? How can I fix it?

**Comment by gadagashwini** [comment]
@sun-peach Just to verify, Did you follow this link to install lingvo. Let us know if that works for you. Thanks!

**Comment by sun-peach** [comment]
Yes. But I do the "installing directly". I can manage to do the first steps:

mkdir -p /tmp/mnist
bazel run -c opt //lingvo/tools:keras2ckpt -- --dataset=mnist --out=/tmp/mnist/mnist

But after that, the problem pops out.

**Comment by sun-peach** [comment]
@gadagashwini BTW, I also tried with tensorflow 1.14 (also tf-nightly). The same problem.

**Comment by ymodak** [comment]
The tensorflow lingvo gihub repo can be a good platform to raise this issue. Please post it on [tensorflow/lingvo](https://github.com/tensorflow/lingvo/issues) . Thanks!

**Comment by gf-sdu** [comment]
finaly,how do you solve this problem?
