### ISSUE TITLE
How to generate graph.pbtxt file from the frozen_graph.pb file?

### ISSUE THREAD

**Issue by hardiktechnoplanet** [tensorflow/tensorflow#29718]
Hello,
I am trying to import a custom tensor flow model in opencv using the dnn module. Below is the example command:
cvNet = cv2.dnn.readNetFromTensorflow('frozen_inference_graph.pb','graph.pbtxt')
I have the frozen_inference_graph.pb' file? Please tell me how can I generate the 'graph.pbtxt' file?

Below is the complete code:
#!/usr/bin/env python
import cv2

# Load a model imported from Tensorflowload using OpenCV dnn module
cvNet = cv2.dnn.readNetFromTensorflow('frozen_inference_graph.pb','graph.pbtxt')

# Input image
img = cv2.imread("image1.jpg")
rows = img.shape[0]
cols = img.shape[1]

# Use the given image as input, which needs to be blob(s).
cvNet.setInput(cv2.dnn.blobFromImage(img, size=(300, 300), swapRB=True, crop=False))

# Runs a forward pass to compute the net output
cvOut = cvNet.forward()

# Loop on the outputs
for detection in cvOut[0,0,:,:]:
    score = float(detection[2])
    if score > 0.3:
        left = detection[3] * cols
        top = detection[4] * rows
        right = detection[5] * cols
        bottom = detection[6] * rows
        cv2.rectangle(img, (int(left), int(top)), (int(right), int(bottom)), (23, 230, 210), thickness=2)

cv2.imshow('img', img)
#save the image
cv2.imwrite( "processedImg4.jpg", img );
cv2.waitKey()
cv2.destroyAllWindows()

**Comment by achandraa** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged//tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there and provide better help to such type of issues. Thanks!
