### ISSUE TITLE
Session crashed when I use TFLiteConverter with tf.lite.OpsSet.TFLITE_BUILTINS_INT8 option.

### ISSUE THREAD

**Issue by ohtaman** [tensorflow/tensorflow#29715]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes. 
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Colaboratory (Ubuntu 18.04.2 LTS)
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: NA
- TensorFlow installed from (source or binary): pre-installed
- TensorFlow version (use command below): 2.0.0-beta0
- Python version: Python 3.6.7
- Bazel version (if compiling from source): NA
- GCC/Compiler version (if compiling from source) NA:
- CUDA/cuDNN version: CUDA v10.0.130, cuDNN 7.6.0 
- GPU model and memory: K80

**Describe the current behavior**
I tried to build fully quantized AutoEncoder model using TF2.0 beta and keras on [Colaboratory](https://colab.research.google.com/gist/ohtaman/09c66e27f240d151f6f17ac4a9f62e54/-post-training-integer-quantization-error.ipynb)
But when I run TFLiteConverter.convert method, the Jupyter kernel crashes and the session is restarted.

**Describe the expected behavior**

Finish conversion without any errors.

**Code to reproduce the issue**

Please check [Colaboratory](https://colab.research.google.com/gist/ohtaman/09c66e27f240d151f6f17ac4a9f62e54/-post-training-integer-quantization-error.ipynb)

**Other info / logs**

```
Jun 13, 2019, 6:47:41 AM | WARNING | WARNING:root:kernel dd551b22-18b1-4c36-917e-0dc4b698c41e restarted
-- | -- | --
Jun 13, 2019, 6:47:41 AM | INFO | KernelRestarter: restarting kernel (1/5), keep random ports
Jun 13, 2019, 6:47:38 AM | WARNING | what(): _Map_base::at
Jun 13, 2019, 6:47:38 AM | WARNING | terminate called after throwing an instance of 'std::out_of_range'
Jun 13, 2019, 6:47:38 AM | WARNING | INFO: Initialized TensorFlow Lite runtime.
```

**Comment by achandraa** [comment]
Tried executing the Colab code snippet and was able to replicate the issue.

**Comment by suharshs** [comment]
Hmm, when I run the colab just now and it works fine for me, am i reproducing the error incorrectly? 

![githubcolab](https://user-images.githubusercontent.com/1450614/59544225-01b74400-8ec5-11e9-9e8c-2b5452b9e5d0.png)

Can you verify that this is still an issue?

**Comment by ohtaman** [comment]
Yes, session crashes in my environment. The lower left Japanese message means it.
I also checked that same error appears with tensorflow-gpu-2.0-beta1 .

![image](https://user-images.githubusercontent.com/329750/59547868-b2364e00-8f80-11e9-8e7f-b3386613e1db.png)

I found that the cause of this error is the upsampling implemented by myself.
If I use `keras.layers.UpSampling2D(2, interpolation='bilinear')`, it works well.
In the colab notebook, I implemented upsampling by myself because UpSampling2D with interpolation='nearest' is not supported by the quantization tool yet.

```python
    def upsampling(x):
        x = keras.backend.repeat_elements(x, scale[0], axis=1)
        x = keras.backend.repeat_elements(x, scale[1], axis=2)
        return x
```

**Comment by jvishnuvardhan** [comment]
@ohtaman I am closing the issue as it was resolved in `tf-nightly`. Please feel free to open it if the issue persists again. Please check the [gist here](https://colab.sandbox.google.com/gist/jvishnuvardhan/701764218387356183515f772bbef27f/-post-training-integer-quantization-error.ipynb). Thanks!
