### ISSUE TITLE
EagerFunc tensor conversion error - dtype mismatch

### ISSUE THREAD

**Issue by kami93** [tensorflow/tensorflow#29727]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 1.13.1
- Python version: 3.7
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: 10.0 / 7.4.2
- GPU model and memory: 1080Ti

**Describe the current behavior**
[GIST Link 1](https://gist.github.com/kami93/27da32514c4c9b085bf4fd20dcf6ef57)
[GIST Link 2](https://gist.github.com/kami93/49355db2491ff7b4a03a22fbfbce09f7)

I am trying to use tfe.pyfunc to combine eager block in the operation graph (See Link 1). There are four input arguments to the eager mode function of dtype tf.float32 and tf.int32. When I try to calculate the gradient of a tensor w.r.t some variables that the calculations involving them are happen in the eager block, the error in the Link 2 is raised (TypeError: Cannot convert provided value to EagerTensor. Provided value: 0.0 Requested dtype: int32).

**Describe the expected behavior**
The gradient is calculated and returned after calling tf.Session.run,

**Code to reproduce the issue**
See Link 1.

**Other info / logs**
See Link 2.
I posted a Pull Request for the fix of this issue. [https://github.com/tensorflow/tensorflow/pull/29728](https://github.com/tensorflow/tensorflow/pull/29728)

**Comment by gadagashwini** [comment]
@kami93 Let us know is this still an issue. Thanks!

**Comment by gadagashwini** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
