### ISSUE TITLE
MirroredStrategy does not work with CudnnLSTM

### ISSUE THREAD

**Issue by sharvil** [tensorflow/tensorflow#29730]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04 LTS
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below): 1.13.1 v1.13.1-2-ga5c387b5ed
- Python version: 3.6.7
- Bazel version (if compiling from source): 0.21.0
- GCC/Compiler version (if compiling from source): 7.4.0
- CUDA/cuDNN version: 10.1
- GPU model and memory: 1080 Ti 11GB

**Describe the current behavior**
Unable to train a model using MirroredStrategy with CudnnLSTM. Fails with the following error:

```
FailedPreconditionError (see above for traceback): Error while reading resource variable cudnn_lstm/opaque_kernel from Container: localhost. This could mean that the variable was uninitialized. Not found: Container localhost does not exist. (Could not find resource: localhost/cudnn_lstm/opaque_kernel)
	 [[node Shape_2/Identity_1/ReadVariableOp (defined at /home/sharvil/.virtualenv/tensorflow/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/estimator.py:1254) ]]
```

**Describe the expected behavior**
Code should run.

**Code to reproduce the issue**
```python
import tensorflow as tf


def gen():
  yield 0


def model_fn(features, labels, mode):
  shape = [1, 100, 10]
  x = tf.random_normal(shape)
  y = tf.zeros(shape)

  cell = tf.contrib.cudnn_rnn.CudnnLSTM(1, shape[-1])
  prediction, _ = cell(x)

  loss = tf.reduce_sum(tf.squared_difference(prediction, y))
  train_op = tf.train.AdamOptimizer().minimize(loss, tf.train.get_or_create_global_step())
  return tf.estimator.EstimatorSpec(mode, prediction, loss, train_op)

config = tf.estimator.RunConfig()
# Training begins successfully with the following line commented out.
config = config.replace(train_distribute=tf.distribute.MirroredStrategy())
estimator = tf.estimator.Estimator(model_fn, '/tmp/tf-bug', config=config)
estimator.train(input_fn=lambda: tf.data.Dataset.from_generator(gen, tf.int32))
```

**Comment by achandraa** [comment]
Have tried on Colab with TF 1.13.1 (CUDA 10.0) and was able to reproduce the issue.

**Comment by guptapriya** [comment]
I tested with 1.14 in a colab and it seems to work. Please try with 1.14 and re-open if still an issue.
