### ISSUE TITLE
Undefined symbol: DeleteGpuDelegate(_TfLiteDelegate*)

### ISSUE THREAD

**Issue by weinixuehao** [tensorflow/tensorflow#29739]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version:
- Python version:
- Installed using virtualenv? pip? conda?:
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Describe the problem**

**Provide the exact sequence of commands / steps that you executed before running into the problem**

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

I had built tensorflowlite.a for ios follow offcial website, build successful!
but not working for gpu, below is error msg with xcode:

Undefined symbol: DeleteGpuDelegate(_TfLiteDelegate*)
![image](https://user-images.githubusercontent.com/17869361/59423729-4e3b4a80-8e05-11e9-9844-dfa2fe2f785b.png)

Offcial website building instruction do not enable gpu feature, how to do this?

Below is website about how to build tensorflowlite for ios
https://www.tensorflow.org/lite/guide/build_ios

**Comment by achandraa** [comment]
Please have a look on #28468 and let us know if that resolves the issue. Also can you please provide us the code snippet and information about the TensorFlow version you are using. Thanks!

**Comment by weinixuehao** [comment]
@achandraa 
thanks!

I came cross a strange issues only occurred on HuaWei Phone. 
For phone infomation with this image.
![image](https://user-images.githubusercontent.com/17869361/59587579-26572a00-9118-11e9-8b20-67a14a5c8f08.png)

At first time run inference no crash, It is always crash at second time. below is crash info.
![image](https://user-images.githubusercontent.com/17869361/59587879-e3498680-9118-11e9-8fe6-bf97e2e2301b.png)

Below is processed crash info with ndk-stack, but unable to locate in tensorflow source as build tflite from source with no debug symbols and i do not know how to build with debug symbol

I have tried many methods for building tflite with debug symbol but not successed
For example
1、 bazel build -c dbg --strip=never --compilation_mode=dbg --per_file_copt=//tensorflow/lite/.*\.cc@-g,-O0  //tensorflow/lite:libtensorflowLite.so --crosstool_top=//external:android/crosstool --cpu=armeabi-v7a --host_crosstool_top=@bazel_tools//tools/cpp:toolchain --cxxopt="-std=c++11"
with -c dbg --strip=never  --compilation_mode=dbg

**Comment by impjdi** [comment]
@weinixuehao 

Sorry for the late response.  I've been out of town.

I need a little bit of clarification.  This bug started with linking error "undefined symbol of DelegateGpuDelegate" but now, you're experiencing a crash that is not related to the GPU delegate, right?

**Comment by weinixuehao** [comment]
@impjdi Right!
This is two issues

**Comment by jianchong-chen** [comment]
@weinixuehao 
I meet the same crash problem on zuk z2 and mi6. My code is almost same as yours. 
It crashed at the DepthWiseConv.
Have you fixed the problem? Thank you!

**Comment by weinixuehao** [comment]
@jianchong-chen 
I used tflite java version to deal with the problem because having no time to consider it.  
if you still want to use c++ api which building tflite yourself maybe is a good start
such as building it with xcode or android studio directly which has a benefits to allow you debugging  this source and to watch some variable when them vary

**Comment by patterson163** [comment]
@weinixuehao @jianchong-chen  hello,I met a similar problem.The app crush when running at the invoke-code.But I use libtensorflowtflite_jni.so in official-prebuilt AAR.I now have another issue,how do you init your tflite model? And how do you detect the image?Do you put your interpreter and input/output tensor in global variable at JNI c++ file?I doubt this maybe a Android  error but I don't know how to solve it.Looking forward to your reply

**Comment by kumariko** [comment]
@weinixuehao Could you please let us know if this issue still persists ? If it is resolved then please feel free to move this issue to close status ? Thanks!
