### ISSUE TITLE
Autograph failed for function contains Non-ASCII character comment in TF 2.0.0-beta0

### ISSUE THREAD

**Issue by munemasa** [tensorflow/tensorflow#29734]
**System information**

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 7
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.0.0-beta0
- Python version: 3.6.8
- CUDA/cuDNN version: 10.0
- GPU model and memory: GeForce GTX 1080 8GB

**Describe the current behavior**

When using non-ASCII character in the function with @tf.function, autograph failed.

> W0613 17:25:35.704982  5776 ag_logging.py:145] Entity <function train at 0x0000000003C96F28> could not be transformed and will be executed as-is. Please report 
this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: (unicode
 error) 'utf-8' codec can't decode byte 0x93 in position 1: invalid start byte (tmp9j9bce4r.py, line 6)

Temporary file is created by Shift JIS (Japanese Windows default) character code.

**Describe the expected behavior**

No warning and building a graph successfully.

**Code to reproduce the issue**

```
import tensorflow as tf
@tf.function
def train():
    ''' Japanese character 日本語 '''
    pass
train()
```

**Comment by gadagashwini** [comment]
@munemasa I tried reproducing the issue on Colab with Tf-2.0.0.beta0 but i did not receive any error. Let us know if that still an issue. Thanks!

**Comment by munemasa** [comment]
@gadagashwini I think it will be occurred on non utf-8 system.
Japanese Windows is used CP932(Shift JIS) coding system as default.

**Comment by mdanatg** [comment]
It appears that the temporary file is saved with the wrong encoding - will investigate.

**Comment by mdanatg** [comment]
@munemasa https://github.com/tensorflow/tensorflow/commit/8125a69d70b5e7a36a62c58656dfe03c01518d1e should fix this at head. Please reopen this bug if that didn't work.
