### ISSUE TITLE
tacotron pb model conversion to tflite

### ISSUE THREAD

**Issue by alokprasad** [tensorflow/tensorflow#29737]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
Ubuntu 18.04
- TensorFlow installed from (source or binary):
Source 1.13.1
- TensorFlow version (or github SHA if from source):
1.13.1

**Provide the text output from tflite_convert**

```
# Some of the operators in the model are not supported by the standard TensorFlow Lite runtime. If those are native TensorFlow operators, you might be able to use the extended runtime by passing --enable_select_tf_ops, or by setting target_ops=TFLITE_BUILTINS,SELECT_TF_OPS when calling tf.lite.TFLiteConverter(). Otherwise, if you have a custom implementation for them you can disable this error with --allow_custom_ops, or by setting allow_custom_ops=True when calling tf.lite.TFLiteConverter(). Here is a list of builtin operators you are using: ADD, CAST, CONCATENATION, CONV_2D, DIV, EXPAND_DIMS, FILL, FLOOR, FULLY_CONNECTED, GATHER, GREATER_EQUAL, LESS, LOGICAL_AND, LOGICAL_NOT, LOGICAL_OR, LOGISTIC, MAXIMUM, MINIMUM, MUL, PACK, RANGE, REDUCE_ANY, REDUCE_MAX, RESHAPE, SELECT, SHAPE, SOFTMAX, SPLIT, SQUEEZE, STRIDED_SLICE, SUM, TANH, TILE, TRANSPOSE. Here is a list of operators for which you will need custom implementations: All, BatchMatMul, Enter, Exit, LoopCond, Merge, RandomUniform, ReverseSequence, Round, Switch, TensorArrayGatherV3, TensorArrayReadV3, TensorArrayScatterV3, TensorArraySizeV3, TensorArrayV3, TensorArrayWriteV3.

```

Also, please include a link to a GraphDef or the model if possible.

**Any other info / logs**

Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by ymodak** [comment]
Please take a look at https://www.tensorflow.org/lite/guide/faq#models_operations to know more.

**Comment by ymodak** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
