### ISSUE TITLE
custom op: undefined symbol: _ZN10tensorflow8str_util9LowercaseEN4absl11string_viewE

### ISSUE THREAD

**Issue by zh794390558** [tensorflow/tensorflow#29738]
**System information**
tensorflow/tensorflow   latest-py3                     4ddde1227df8       
tensorflow/tensorflow   devel-py3                      b558e7fc2018 

**Describe the current behavior**
compile ops.so under latest-py3 , then using the ops.so with tf c++ api under devel-py3.

the error is below:
```
ops.so: undefined symbol: _ZN10tensorflow8str_util9LowercaseEN4absl11string_viewE
```

**Describe the expected behavior**
I think ops.so will work in both docker image.

**Other info / logs**
refs:
https://github.com/tensorflow/io/issues/161
https://github.com/tensorflow/io/issues/173

**Comment by gadagashwini** [comment]
@zh794390558 Please provide details about what platform you are using (operating system, architecture). Make sure you also include the exact command if possible to produce the output included in your test case.

**Comment by zh794390558** [comment]
@gadagashwini All test is on Docker Images provided by Tensorflow.
```
tensorflow/tensorflow latest-py3 4ddde1227df8
tensorflow/tensorflow devel-py3 b558e7fc2018
```

custom_op.so compile under latest-py3, using under devel-py3.

I think this is the compile problem. latest-py3 using pip install tensorflow, which maybe compile not under the latest-py3 image.

**Comment by angersson** [comment]
@zh794390558, the `latest-` Docker images aren't designed to build custom ops. Can you use the `tensorflow/tensorflow:custom-op` image instead?

**Comment by zh794390558** [comment]
@angersson  I need using `latest-` docker images to run experiment, which need using custom ops.  And I think all `tf` image are based on same image. I also may using the `latest-` image to train model on GPU devices, so I think it must support build custom ops under any `tf` images.

**Comment by angersson** [comment]
@yifeif I'm not sure if the `latest` images can work for this -- `custom-op` is the way to go, right?

**Comment by angersson** [comment]
Also, @zh794390558, you'll need to use `devel` instead of `latest-devel` -- `latest-devel` is much older (I'm working on getting them synced up, but `devel` is the canonical image).

**Comment by zh794390558** [comment]
`devel` has pip package installed? And it has source code? I need a docker images which has `bazel`, `tensorflow_src`,  `tensorflow pip package`, and can compile `custom ops`.

**Comment by zh794390558** [comment]
This problem not solved now for 1.14-py3 image.

**Comment by zh794390558** [comment]
what's the difference of `custom-ops` and `latest-py3`?

**Comment by zh794390558** [comment]
custom-ops using g++4.8, but python 3.4.3, our repo must using python>=3.6.

**Comment by yifeif** [comment]
Hi @zh794390558, the custom-op images should contains the same tool chain as how our pip packages are built with, which is not necessary the case for latest-py3 etc docker images. Could you take a look at https://github.com/tensorflow/custom-op ?

**Comment by zh794390558** [comment]
@yifeif So this the problem, I just want to using one released image to training model with python3, which can also compile and run with custom-ops.  `custom-op` not satisfy my needs.

**Comment by angerson** [comment]
@zh794390558, this image has python3: 

```
$ docker run -it tensorflow/tensorflow:custom-op-ubuntu16 /bin/bash
$ python3 -V
Python 3.6.8
```

If that doesn't work for you, you may need to put together your own image.
