### ISSUE TITLE
Improve interface for warmstarting non-TRAINABLE variables in warm_starting_util

### ISSUE THREAD

**Issue by gabegrand** [tensorflow/tensorflow#29748]
**System information**
- TensorFlow version (you are using): 1.13.1
- Are you willing to contribute it (Yes/No): Yes (if need be)

**Describe the feature and the current behavior/state.**
When warmstarting a pre-trained estimator, a common workflow is to warmstart a small number of non-TRAINABLE variables in addition to the TRAINABLE_VARIABLES. In particular, when warmstarting a Keras estimator with BatchNorm layers, it's necessary to manually warmstart the moving_mean and moving_variance variables, since these are non-trainable (see https://github.com/tensorflow/tensorflow/issues/19903, https://github.com/tensorflow/tensorflow/issues/17950, https://github.com/keras-team/keras/pull/9965). Failure to properly restore these variables can break warmstarting for pre-trained Keras models like InceptionV3 (see https://github.com/keras-team/keras/issues/9214).

The current solution is to create `tf.estimator.WarmStartSettings()` object with `vars_to_warm_start=['.*']`. As per the [TF WarmStartSettings docs ](https://www.tensorflow.org/api_docs/python/tf/estimator/WarmStartSettings), passing in a list will warmstart all variables (including non-TRAINABLE), which allows users to warmstart vars from GLOBAL_VARIABLES. However, as [noted](https://github.com/tensorflow/tensorflow/issues/19903#issuecomment-470009739) by some users, this solution is undesirable because it will warmstart all GLOBAL_VARIABLES (including global_step, accumulators, and other state that we generally don't want to restore). 

Ideally, the warmstart API should allow users to cherry-pick additional non-TRAINABLE variables to warmstart alongside TRAINABLE variables. Unfortunately, it's generally not possible to use the regex mechanism in `vars_to_warm_start` for this purpose, since there's no distinction between trainable and non-trainable variables in the default TF variable naming scheme. Furthermore, in most cases, the `WarmStartSettings` object is defined before graph creation, so it's not possible for the user to access `TRAINABLE_VARIABLES` or `GLOBAL_VARIABLES` at Estimator creation time. 

**Proposed solution**
Extend the `tf.train.warm_start()` / `tf.estimator.WarmStartSettings()` API to allow the user to separately define TRAINABLE and non-TRAINABLE variables to warmstart. I can see a couple ways to accomplish this:

1. Create separate arguments `trainable_vars_to_warmstart` and `nontrainable_vars_to_warmstart`, where non-TRAINABLE variables are defined as `set(GLOBAL_VARIABLES) - set(TRAINABLE_VARIABLES)`.
2. Extend the `vars_to_warmstart` arg to accept a dict of `{"trainable": ".*", "nontrainable": "\moving_\"}`, which in this case would warmstart all TRAINABLE_VARIABLES plus the BatchNorm moving mean and variance.

**Will this change the current api? How?**
Depending on the solution, the args for `tf.train.warm_start()` / `tf.estimator.WarmStartSettings()` may change. Something like Option 2 above would probably be able to preserve backwards compatibility reasonably well.

**Who will benefit with this feature?**
Users who want to warmstart a pre-trained Keras model that contains BatchNormalization layers or other stateful model components not found in TRAINABLE_VARIABLES.

**Any Other info.**
This [blog post](http://blog.datumbox.com/the-batch-normalization-layer-of-keras-is-broken/) gives useful background on partially-overlapping issues related to BatchNorm in Keras.

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.

**Comment by rmothukuru** [comment]
@gabegrand,
Sorry for the delayed response. The documentation of [Estimators](https://www.tensorflow.org/guide/estimator) state: 

> Warning: Estimators are not recommended for new code. Estimators run v1.Session-style code which is more difficult to write correctly, and can behave unexpectedly, especially when combined with TF 2 code. Estimators do fall under our compatibility guarantees, but will receive no fixes other than security vulnerabilities. See the migration guide for details.

Can you please let us know if this **`Feature`** is still relevant? Thanks!

**Comment by gabegrand** [comment]
Thanks for following up @rmothukuru. That’s right, this feature is no longer relevant, unless you have a time machine that goes back to pre-pandemic times. (If only I’d know I’d have bigger things to worry about than warmstarting APIs for TF…)
