### ISSUE TITLE
 'TensorSliceDataset' object has no attribute {'make_initializable_iterator', 'output_shapes', 'make initializable_iterator'...}

### ISSUE THREAD

**Issue by jackshi0912** [tensorflow/tensorflow#29747]
Short description
TensorSliceDataset is lacking a lot of attributes to make is usable ('make_initializable_iterator', 'output_shapes', 'make initializable_iterator'...).

Environment information

Operating System: 18.04
Python version: 3.6
tensorflow-datasets/tfds-nightly version: tfds-nightly
tensorflow/tensorflow-gpu/tf-nightly/tf-nightly-gpu version: tf-nightly-2.0-preview
Reproduction instructions

randt = tf.random.uniform([2000, 80, 5])
dataset = tf.data.Dataset.from_tensor_slices(randt)
dataset.batch(20)
iter = dataset.make_one_shot_iterator()

Link to logs
AttributeError: 'TensorSliceDataset' object has no attribute 'make_one_shot_iterator'

**Comment by claytonjschneider** [comment]
@jackshi0912 was this resolved? I've been encountering this frequently in Jupyter Notebooks as I'm shifting from 1.14 to 2.0.0-alpha

**Comment by jackshi0912** [comment]
Yes, this method is no longer supported in 2.0
You should consider justing using a for loop to iterate through the dataset. Pretty much all methods that returns a graph node is gone.

**Comment by claytonjschneider** [comment]
Thank you. I'm using an example COLAB notebook from TF 1.14 and trying to migrate it to 2.0. I'm not new to coding, but am to TF. 

I don't think iteration is necessary in this example, unless I'm misunderstanding the tf objects... 

`print('type: ', tf.data.get_output_types(path_ds))`. I know the method is deprecated, but having types / shapes of even one image printed would still be useful for this project. Any thoughts?
