### ISSUE TITLE
Inference Time TensorFlow C++ API vs Python API

### ISSUE THREAD

**Issue by PythonImageDeveloper** [tensorflow/tensorflow#29746]
Hi,
In the inference mode, Is C++ API faster than Python API? In the some issues, I see the C++ slower than python, why? Is this right?
[Issue 1](https://github.com/tensorflow/tensorflow/issues/22852 )
[Issue 2](https://github.com/tensorflow/tensorflow/issues/15552)

**Comment by gadagashwini** [comment]
@PythonImageDeveloper It looks, This is not bug/performance or build/install issue. Please post this kind of support questions at [StackOverflow](http://stackoverflow.com/questions/tagged//tensorflow). There is a big community to support and learn from your questions. GitHub is mainly for addressing bugs in installation and performance. Thanks!

**Comment by PythonImageDeveloper** [comment]
Here is best where that people can be answer the question.

**Comment by jvishnuvardhan** [comment]
@PythonImageDeveloper Based on this comment, https://github.com/tensorflow/tensorflow/issues/15552#issuecomment-396573076 it need some warm-up. Thanks! If you have further question, could you create a standalone code using recent TF version and share a gist. Thanks!

**Comment by jvishnuvardhan** [comment]
This is a stale issue. Please check the issue with latest TensorFlow. If the issue still persists in the newer version of TF, please feel free to reopen it by providing details about the issue and a standalone code to reproduce the issue. Thanks!
