### ISSUE TITLE
tf.Print was not rendered correctly in the website

### ISSUE THREAD

**Issue by jvishnuvardhan** [tensorflow/tensorflow#29755]
Thank you for submitting a TensorFlow documentation issue. Per our GitHub
policy, we only address code/doc bugs, performance issues, feature requests, and
build/installation issues on GitHub.

The TensorFlow docs are open source! To get involved, read the documentation
contributor guide: https://www.tensorflow.org/community/contribute/docs

## URL(s) with the issue:

https://www.tensorflow.org/api_docs/python/tf/Print

## Description of issue (what needs changing):

[tf.Print](https://www.tensorflow.org/api_docs/python/tf/Print) was not rendered correctly in the website. I understand that it was deprecated in TF2.0, but it should be rendered correctly in the TF website.

### Correct links

https://www.tensorflow.org/api_docs/python/tf/Print

### Submit a pull request?

Are you planning to also submit a pull request to fix the issue? See the docs
contributor guide: https://www.tensorflow.org/community/contribute/docs and the
docs style guide: https://www.tensorflow.org/community/contribute/docs_style

**Comment by RonLek** [comment]
@jvishnuvardhan Mind if I resolve this?

**Comment by jvishnuvardhan** [comment]
@RonLek Please go ahead and resolve through PR. Thanks!

**Comment by lamberta** [comment]
That file is here: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/ops/logging_ops.py

There is a code block sample in the warning note. The deprecation notice should be short and any code examples should move under `def Print`.

Thanks for taking a look

**Comment by RonLek** [comment]
@jvishnuvardhan  @lamberta Please let me know if it works fine. Thanks!
