### ISSUE TITLE
No module named 'tensorflow._api'

### ISSUE THREAD

**Issue by AndSay22** [tensorflow/tensorflow#29750]
**System information**
- Microsoft Windows 10 Home
- Version 10.0.17.134 Build 17134
- TensorFlow installed from: Not sure, installed using python environments within visual studio
- TensorFlow version: 1.13.1
- Python version: 3.7 (64-bit)
- Installed using pip
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory: Asus - GeForce GTX 1060 6GB Dual Video Card

New user to python and this website. So please bear with me and I'll do my best. 

I am attempting to run a simple code here: https://www.tensorflow.org/tutorials/load_data/images
in order to eventually upload my own set of images for a neural net to process. 

I'm using visual studio as well, and know little about how that could affect things. 

Here is my exact code: 

```
from __future__ import absolute_import, division, print_function

import tensorflow as tf
tf.enable_eager_execution()
tf.VERSION

AUTOTUNE = tf.data.experimental.AUTOTUNE
```
And here is the full error provided:

```
Traceback (most recent call last):
  File "c:\program files (x86)\microsoft visual studio\2019\community\common7\ide\extensions\microsoft\python\core\ptvsd_launcher.py", line 119, in <module>
    vspd.debug(filename, port_num, debug_id, debug_options, run_as)
  File "c:\program files (x86)\microsoft visual studio\2019\community\common7\ide\extensions\microsoft\python\core\Packages\ptvsd\debugger.py", line 41, in debug
    run(address, filename, *args, **kwargs)
  File "c:\program files (x86)\microsoft visual studio\2019\community\common7\ide\extensions\microsoft\python\core\Packages\ptvsd\_local.py", line 80, in run_file
    run(argv, addr, **kwargs)
  File "c:\program files (x86)\microsoft visual studio\2019\community\common7\ide\extensions\microsoft\python\core\Packages\ptvsd\_local.py", line 140, in _run
    _pydevd.main()
  File "c:\program files (x86)\microsoft visual studio\2019\community\common7\ide\extensions\microsoft\python\core\Packages\ptvsd\_vendored\pydevd\pydevd.py", line 2329, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "c:\program files (x86)\microsoft visual studio\2019\community\common7\ide\extensions\microsoft\python\core\Packages\ptvsd\_vendored\pydevd\pydevd.py", line 1664, in run
    return self._exec(is_module, entry_point_fn, module_name, file, globals, locals)
  File "c:\program files (x86)\microsoft visual studio\2019\community\common7\ide\extensions\microsoft\python\core\Packages\ptvsd\_vendored\pydevd\pydevd.py", line 1671, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "c:\program files (x86)\microsoft visual studio\2019\community\common7\ide\extensions\microsoft\python\core\Packages\ptvsd\_vendored\pydevd\_pydev_imps\_pydev_execfile.py", line 25, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "C:\Users\Andrew\Desktop\Visual Studio\Python\Scoliosis NN Thesis\ScNN_v1.1.py", line 3, in <module>
    import tensorflow as tf
  File "D:\Apps\Python\lib\site-packages\tensorflow\__init__.py", line 26, in <module>
    from tensorflow._api.v1 import app
**ModuleNotFoundError: No module named 'tensorflow._api'**
Press any key to continue . . .
```
If there is any other information I can provide, please let me know.

**Comment by LeonHillmann** [comment]
Hello,
for me it looks like something went wrong installing tensorflow.
1) There are problems in Visual Studio installing tensorflow since - as far as I know - uses virtual environments to install its packages. Especially with the gpu version.

It doesnt look like a driver issue to me so something must have gone wrong there. I would recommend trying to installing it locally on your real machine and not in an virtual environment. That will probably make it work just follow the tensorflow documentation. https://www.tensorflow.org/install/gpu

Best,
Leon

**Comment by AndSay22** [comment]
> Hello,
> for me it looks like something went wrong installing tensorflow.
> 
> 1. There are problems in Visual Studio installing tensorflow since - as far as I know - uses virtual environments to install its packages. Especially with the gpu version.
> 
> It doesnt look like a driver issue to me so something must have gone wrong there. I would recommend trying to installing it locally on your real machine and not in an virtual environment. That will probably make it work just follow the tensorflow documentation. https://www.tensorflow.org/install/gpu
> 
> Best,
> Leon

Thank you Leon, I'll give that a try.

**Comment by LeonHillmann** [comment]
> > Hello,
> > for me it looks like something went wrong installing tensorflow.
> > 
> > 1. There are problems in Visual Studio installing tensorflow since - as far as I know - uses virtual environments to install its packages. Especially with the gpu version.
> > 
> > It doesnt look like a driver issue to me so something must have gone wrong there. I would recommend trying to installing it locally on your real machine and not in an virtual environment. That will probably make it work just follow the tensorflow documentation. https://www.tensorflow.org/install/gpu
> > Best,
> > Leon
> 
> Thank you Leon, I'll give that a try.

When I was running it on my machine. It was all right and working. If it was the solution for you, please close the issue. And always happy to help :)

Best,
Leon

**Comment by AndSay22** [comment]
> > > Hello,
> > > for me it looks like something went wrong installing tensorflow.
> > > 
> > > 1. There are problems in Visual Studio installing tensorflow since - as far as I know - uses virtual environments to install its packages. Especially with the gpu version.
> > > 
> > > It doesnt look like a driver issue to me so something must have gone wrong there. I would recommend trying to installing it locally on your real machine and not in an virtual environment. That will probably make it work just follow the tensorflow documentation. https://www.tensorflow.org/install/gpu
> > > Best,
> > > Leon
> > 
> > 
> > Thank you Leon, I'll give that a try.
> 
> When I was running it on my machine. It was all right and working. If it was the solution for you, please close the issue. And always happy to help :)
> 
> Best,
> Leon

As of the time of writing, I ran into another issue when attempting to install the latest CUDA, cuDNN, visual studio IDE, and python. I am attempting to use 9.0 versions of CUDA and cuDNN to see if that works.

**Comment by mihaimaruseac** [comment]
Just to confirm, is this using a nightly version of TF or a released one?

**Comment by AndSay22** [comment]
> Just to confirm, is this using a nightly version of TF or a released one?
> 
> Can you try
> 
> ```python
> import tensorflow as tf
> print(tf.__version__)
> ```

I have trouble just running the import tensorflow command. However, you may be on to something. I believe I at one point used a nightly version, which may be causing the issue (as I said, I'm new at this and am very much still learning). Hopefully a clean install will fix the issue.

**Comment by mihaimaruseac** [comment]
Can you try

```bash
pip uninstall tensorflow
pip uninstall tensorflow_estimator
pip install tensorflow tensorflow_estimator
```

Just to make sure. If the `tensorflow_estimator` uninstall fails (with not found) just ignore that error

**Comment by mihaimaruseac** [comment]
Can also check the installed version by looking at the file names in `D:\Apps\Python\lib\site-packages`. You'll see a `tensorflow` folder and a `tensorflow-<version>` or a `tf-nightly-<version>` one

**Comment by AndSay22** [comment]
Leon: Thank you for your comment. I believe I have it working now with version 10 of both CUDA and cuDNN installed independently of visual code. Running import tensorflow as tf now works.

Mihaimaruseac: I've since already uninstalled and reinstalled everything, so I believe any nightly versions should also be gone.

**Comment by samuelgjabel** [comment]
> Can you try
> 
> ```shell
> pip uninstall tensorflow
> pip uninstall tensorflow_estimator
> pip install tensorflow tensorflow_estimator
> ```
> 
> Just to make sure. If the `tensorflow_estimator` uninstall fails (with not found) just ignore that error

thanks helped me  :p

**Comment by mihaimaruseac** [comment]
Locking to prevent "it works" and "thanks" messages from drowning up the solution
