### ISSUE TITLE
ModuleNotFoundError: No module named 'tensorflow.python.saved_model.model_utils

### ISSUE THREAD

**Issue by Charlie4zc** [tensorflow/tensorflow#29765]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):NO
- OS Platform and Distribution :Linux Ubuntu 16.04
- TensorFlow installed from (source or binary):conda install tensorflow-gpu=1.13.1
- Python version:3.6

I have installed tf=2.0.0 before on another conda env ,but after uninstalling tf=2.0.0 the whole tensorflow on every conda env has been ruined. Trying different envs/python-version doesn't work at all. 
`pip uninstall/install tensorflow_estimator` in/out of conda envs doesn't work as well

**Comment by sourabhXIII** [comment]
@Charlie4zc 
How did you solve it?
I am facing same problem while working with Tensorlfow object detection API.
