### ISSUE TITLE
Batched tf.RaggedTensor with tf.data.Dataset returns invalid ragged tensors

### ISSUE THREAD

**Issue by gehring** [tensorflow/tensorflow#29763]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): public colab instance
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 1.14.0-rc1
- Python version: 3.6

**Describe the current behavior**
Iterating on a batched dataset made from tensor slices of ragged tensors produces `tf.RaggedTensor` that seem to be improperly formatted. Specifically, calling `RaggedTensor.value_rowids` return the row index for every element in `RaggedTensor.values`. This is inconsistent with the output obtained from calling `RaggedTensor.value_rowids` directly on the original tensor (or slice of the original), and also inconsistent with the format expected by `tf.RaggedTensor. from_value_rowids`.
 
**Describe the expected behavior**
Given a batched ragged tensor `x`, manually building a new one using `tf.RaggedTensor. from_value_rowids(x.values, x.value_rowids())` should work. Currently this raise an exception at runtime (not during graph construction).

**Code to reproduce the issue**
```python
import numpy as np
import tensorflow as tf


data_values = tf.RaggedTensor.from_row_splits(
    np.arange(8).reshape((-1, 2)),
    np.array([0, 2, 3, 4]),
)

dataset = tf.data.Dataset.from_tensor_slices(data_values)
dataset = dataset.repeat()
dataset = dataset.batch(3)

iterator = dataset.make_one_shot_iterator()
batch = iterator.get_next()

a = tf.RaggedTensor.from_value_rowids(batch.values, batch.value_rowids())
with tf.Session() as sess:
  sess.run(a)  # this fails due to invalid shapes
  assert np.allclose(sess.run(batch.value_rowids()),  # this will also fail
                     sess.run(data_values.value_rowids()))
  
```

**Comment by gehring** [comment]
This appears to be fixed in tf-nightly (version `1.14.1-dev20190619`). This issue is probably safe to close.

**Comment by PistaSaki** [comment]
Thank you, it seems to work!
I have a related problem, but maybe I should open it as another issue:
I have a dataset from generator, containing uneven tensors. After batching I would expect it to return dataset with RaggedTensors. At present it fails. 
Here is a minimal example:
```python
import numpy as np
import tensorflow as tf
from tensorflow.data import Dataset

def get_iterator():
    return map(lambda x: np.ones([x, 1]), range(4))
    
ds = Dataset.from_generator(get_iterator, output_types= tf.float32,
                            output_shapes=[None, 1])

for x in ds:
    print(x)    

print("Batched:")

for x in ds.batch(2):
    print(x) 
```

**Comment by PistaSaki** [comment]
Sorry, I found probably a more related issue:
https://github.com/tensorflow/tensorflow/issues/27653
and I repated my above comment there.
