### ISSUE TITLE
Compiler dependent error for TFLite micro's FastInt32ToBufferLeft

### ISSUE THREAD

**Issue by stakemura** [tensorflow/tensorflow#29779]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):Windows 10 x64
- TensorFlow installed from (source or binary):source
- TensorFlow version (use command below):1.14.0-rc1
- Python version:not used
- Bazel version (if compiling from source):not used
- GCC/Compiler version (if compiling from source):Visual C++ 14 or higher.

**Describe the current behavior**
Can't build all TFLite micro's samples on Windows or some embedded systems (requires Visual C++).

**Describe the expected behavior**

[TFLite micro's FastInt32ToBufferLeft](https://github.com/tensorflow/tensorflow/blob/4053e17dbb7a1be85553e5173c2e08fb9653d33f/tensorflow/lite/experimental/micro/debug_log_numbers.cc#L80) causes Error C4146 `unary minus operator applied to unsigned type, result still unsigned` on Visual C++. Meanwhile, tensoflow's implementaion has no problem.
This issue can be solved by rewriting `u = -u;` to `u = 0 - u;` as follows.

* [TFLite micro's FastInt32ToBufferLeft](https://github.com/tensorflow/tensorflow/blob/4053e17dbb7a1be85553e5173c2e08fb9653d33f/tensorflow/lite/experimental/micro/debug_log_numbers.cc#L80)
```cpp
// Populates the provided buffer with an ASCII representation of the number.
char* FastInt32ToBufferLeft(int32_t i, char* buffer) {
  uint32_t u = i;
  if (i < 0) {
    *buffer++ = '-';
    u = -u;
  }
  return FastUInt32ToBufferLeft(u, buffer, 10);
}
```

* [Tensorflow's FastInt32ToBufferLeft](https://github.com/tensorflow/tensorflow/blob/4213d5c1bd921f8d5b7b2dc4bbf1eea78d0b5258/tensorflow/core/lib/strings/numbers.cc#L131)
```cpp
size_t FastInt32ToBufferLeft(int32 i, char* buffer) {
  uint32 u = i;
  size_t length = 0;
  if (i < 0) {
    *buffer++ = '-';
    ++length;
    // We need to do the negation in modular (i.e., "unsigned")
    // arithmetic; MSVC++ apparently warns for plain "-u", so
    // we write the equivalent expression "0 - u" instead.
    u = 0 - u;
  }
  length += FastUInt32ToBufferLeft(u, buffer);
  return length;
}
```

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.
```cpp
#include "tensorflow/lite/experimental/micro/debug_log_numbers.h"
int main()
{
    char s[80];
    FastInt32ToBufferLeft(-1, s);
    return 0;
}
```
This issue is critical for us.
Would you like to modify the code?

**Comment by wangtz** [comment]
This makes a lot of sense. Do you want to kindly provide a PR?

Thanks,

**Comment by Saduf2019** [comment]
@stakemura 
Is this still an issue
