### ISSUE TITLE
Please add a flag to prevent app.run from terminating with  _sys.exit(main(argv))

### ISSUE THREAD

**Issue by mfeblowitz** [tensorflow/tensorflow#29776]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using): 1.12.x, for now
- Are you willing to contribute it (Yes/No): No. Simple fix but easy to depart from tf naming conventions, and also to not propagate it properly through the code and doc.

**Describe the feature and the current behavior/state.**
Current behavior is for tf to call _sys.exit at the end of app.run completion:

tensorflow/tensorflow/python/platform/app.py, line 125: 
```
 # Call the main function, passing through any arguments
  # to the final program.
  _sys.exit(main(argv))
```
In python applications where tf.app.run is to be invoked multiple times, it would be useful to suppress the _sys.exit. The current workaround is to call out to an external script, only for the purpose of continued processing after the app.run call.

WHat's needed is a flag - something like _prevent_sys_exit, or whatever is consistent with tf flag naming conventions.
 
**Will this change the current api? How?**
Probably not, but would add another flag to externally specifiable set of tf flags.
**Who will benefit with this feature?**
Anyone with a need to not have a python sys.exit call immediately after running a tf app.

 A specific benefit is to aid both logging and debugging, which are much more difficult with call-outs to external scripts.

**Any Other info.**

**Comment by jvishnuvardhan** [comment]
@mfeblowitz Sorry for the delay in my response. Can you please check with `TF1.15`? Thanks!

**Comment by jvishnuvardhan** [comment]
Closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
