### ISSUE TITLE
Complex Number Calculations Not Available On GPU -- No Supported Kernels

### ISSUE THREAD

**Issue by LeavesBreathe** [tensorflow/tensorflow#2977]
Hey Guys,

Have been trying to implement unitary RNN in tensorflow. Big thanks to @khaotik as he has done much work on implementing unitary RNN's in his repo here:

https://github.com/sherjilozair/char-rnn-tensorflow

When I try to implement this on a GPU I run into several kernel support errors. Here are some operations that do not currently have kernels for the `complex64` dtype:

- `tf.conj`
- `tf.matmul` (which is crucial)

I'm unsure if `batch_fft` has supported GPU kernels. 

Regardless, having these kernels would give tensorflow the ability to explore entirely new architectures as several new RNN papers use complex numbers now. I'm not sure how difficult it would be to write these kernels but much thanks to those who could do it.

**Comment by kashif** [comment]
I would be happy to have a look at this issue unless someone else has started

**Comment by kashif** [comment]
@LeavesBreathe can you kindly test with my branch? Thanks!

**Comment by LeavesBreathe** [comment]
@kashif thanks for doing this. Right now my gpu's are tied up so it will be at least a few days before I can give it a test. Will post back here upon testing. Thanks again.

**Comment by rryan** [comment]
tf.matmul/tf.batch_matmul support for complex types is now in:
https://github.com/tensorflow/tensorflow/commit/6c7681fbbcc3c244f3e406abc4ea1287fd717752

**Comment by kashif** [comment]
can this issue be closed?

**Comment by LeavesBreathe** [comment]
@kashif  i'm testing urnn's right now on the gpu and it seems that the implementation is pretty slow right now. I hesitate to close the issue right now but I can if you feel that its justified. It does seem that the unitary rnn is about 10x slower than vanilla lstm on a titan x.
