### ISSUE TITLE
How to build Dockerfile.ubuntu  for tensorflow-gpu

### ISSUE THREAD

**Issue by mk123qwe** [tensorflow/tensorflow#29782]
How to build Dockerfile.ubuntu  for tensorflow-gpu
ubuntu16.04
tensorflow-gpu1.12.0

I have  nvidia-docker  Dockerfile.ubuntu

**Comment by gadagashwini** [comment]
@mk123qwe Please find instructions in this [link](https://www.tensorflow.org/install/docker) which help you to install Tensorflow from docker. Let us know if that solve your problem. Thanks!

**Comment by gadagashwini** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
