### ISSUE TITLE
Install from pip, run test and results in "illegal instruction" for tensorflow-gpu

### ISSUE THREAD

**Issue by AlexYoung757** [tensorflow/tensorflow#29788]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): CentOs 7.5
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): pip per https://www.tensorflow.org/install/pip
- TensorFlow version: 1.11.0
- Python version: 3.6.8
- Installed using virtualenv? pip? conda?: N/A
- Bazel version (if compiling from source):N/A
- GCC/Compiler version (if compiling from source):N/A
- CUDA/cuDNN version:  cuda9.0 and cudnn7.0
- GPU model and memory: Tesla P100

**Describe the problem**
when i  import tensorflow，the error as follow：
illegal instruction
i don't know why，please help me.

**Comment by 8bitmp3** [comment]
Which version of TF are you trying to use? 

See #17411 , #19809 and https://stackoverflow.com/questions/49094597/illegal-instruction-core-dumped-after-running-import-tensorflow

Also maybe try running it in a `virtualenv` with Python 3.6 then `pip3 install tensorflow-gpu` or even 2.0 `tensorflow-gpu==2.0.0-beta1`. Check the full instructions on how to install with pip or docker [here](https://www.tensorflow.org/install/pip).

**Comment by AlexYoung757** [comment]
@8bitmp3  thank you for your reply. emm, i us tf1.11. In fact,  i just want do some try on bert and i must upgrade tf.

**Comment by gadagashwini** [comment]
> @8bitmp3 thank you for your reply. emm, i us tf1.11. In fact, i just want do some try on bert and i must upgrade tf. I use pip but the result is too bad. errors alway go on.
> so, i use conda, but another error happen. that's very terribel!! please save me~~

Can you include error message that you are getting. Thanks!

**Comment by AlexYoung757** [comment]
@gadagashwini  here is the detail：
tensorflow.python.framework.errors_impl.InternalError: failed initializing StreamExecutor for CUDA device ordinal 0: Internal: failed call to cuDevicePrimaryCtxRetain: CUDA_ERROR_NOT_SUPPORTED: operation not supported

**Comment by gadagashwini** [comment]
@AlexYoung757 Just to verify, did you add the lib and bin to path? Thanks!

**Comment by AlexYoung757** [comment]
@gadagashwini   yep! i am sure that i add the lib and bin to path. i can use the command: nvcc -v
to verify

**Comment by ymodak** [comment]
TensorFlow release binaries version 1.6 and higher are prebuilt with AVX instruction sets. This means on any CPU that do not have these instruction sets either CPU or GPU version of TF will fail to load. I suspect that your CPU model does not support AVX instruction set. Can you please confirm?. Thanks!

**Comment by AlexYoung757** [comment]
@ymodak thank you for your reply.  en i find that my cpu model does not support AVX instruction set. it only supports sse 、sse2 . 
so if  i want to install tensorflow 1.11 , what should i do. Maybe i must install from source code?

**Comment by ymodak** [comment]
The easiest way to use TF will be to switch to [google colab](https://colab.sandbox.google.com/notebooks/welcome.ipynb#recent=true). You get pre-installed stable TF version on it (currently running TF 1.14). Also you can use ```pip install``` to install any other preferred TF version if required.
It has added advantage since you can you easily switch to different hardware accelerators (cpu, gpu, tpu) as per the task. All you need is good internet connection and you are all set.
Another option will be to install TF version 1.5 on your local machine.

**Comment by AlexYoung757** [comment]
@ymodak . thanks , i have solved this problem. After modify the AVX instruction sets ,all the question has done.

**Comment by ymodak** [comment]
Are you satisfied with the resolution of your issue?
[Yes](https://goo.gl/forms/Oe0tEvODFRoI2gJF3)
[No](https://goo.gl/forms/fUjzOfrtkFbrOT8d2)
