### ISSUE TITLE
latest stable tensorflow which is compatible with cuda 9

### ISSUE THREAD

**Issue by megjoshi** [tensorflow/tensorflow#29793]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): binary
- TensorFlow version: 1.12.2
- Python version: 3.6
- Installed using virtualenv? pip? conda?: pip
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 9
- GPU model and memory:

**Describe the problem**
I want to know which is the last known stable version which is compatible with cuda 9. Iwant to use lateset tensorflow code which has a bug fix but i am not able to do coz that is not compatible with cuda 9. I cant upgrade to cuda 10, it will break others old model architecture. 

**Provide the exact sequence of commands / steps that you executed before running into the problem**

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by mihaimaruseac** [comment]
1.12.2 is the latest version

**Comment by achandraa** [comment]
Can we close the issue since the query is been answered. Let us know. Thanks!
