### ISSUE TITLE
Do you have a 3Ddata of crop_and_resize function implementation?

### ISSUE THREAD

**Issue by huang229** [tensorflow/tensorflow#29790]
Do you have a 3Ddata of crop_and_resize function implementation? DATA of shape `[batch, depth, image_height, image_width, channel]`.  If not, are the crop_and_resize implementations of 2D detailed? As long as I know the implementation details of 2D, I can realize the application of 3D.

**Comment by achandraa** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged//tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there and provide better and faster support for such issues. Thanks!
