### ISSUE TITLE
Could we have F1 Score and F-Scores in TF 2.0?

### ISSUE THREAD

**Issue by CJMenart** [tensorflow/tensorflow#29799]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using): TF 2.0 alpha
- Are you willing to contribute it (Yes/No): Unlikely. I am going to try to build a workaround, but I've never contributed to TF and probably wouldn't be able to figure out the right way to put together code you'd want in master...I will post any useful code I come up with though if allowed.

**Describe the feature and the current behavior/state.**
I would like to be able to do 'model.compile(..., metrics=['F1'])
Or even 'model.compile(..., metrics=['FX']) for an arbitrary float X.
I'm guessing we don't currently have it because it's not in Keras?

**Will this change the current api? How?**
No

**Who will benefit with this feature?**
F1 score and F-scores are relatively common in evaluating classification algorithms.

**Any Other info.**
I see a related request, seemingly for TF 1.x, in 
https://github.com/tensorflow/tensorflow/issues/28207
but I don't know if it went anywhere.

https://en.wikipedia.org/wiki/F1_score

**Comment by CJMenart** [comment]
OK. I built a couple Metric classes on top of Precision and Recall. It should at least allow
metrics=[metrics.FScore(F=2)...].

Since this issue arose from work I have to go through a paperwork chain before I'm allowed to post anything. Should take about a month. If this is not irrelevant by then I'll comment back to ask:

1. What branch to do a pull request on (Just r2.0?)
2. Whether this can go in metrics.py, or if it would have to live somewhere else by account of not being part of Keras.

**Comment by RomainBarraud** [comment]
Could you share your implementation for the F1 score?

**Comment by CJMenart** [comment]
As I said...it will be hopefully about a month.

**Comment by ziyigogogo** [comment]
just a quick glimpse, since f1 == dice according to (https://en.wikipedia.org/wiki/F1_score)
And the computation cost for compute dice is less compared with f1. 
So a base sample code of f1 score for img segmentation:
```python
@tf.function
def f1(y_true, y_pred):
    y_true = K.flatten(y_true)
    y_pred = K.flatten(y_pred)
    return 2 * (K.sum(y_true * y_pred)+ K.epsilon()) / (K.sum(y_true) + K.sum(y_pred) + K.epsilon())
```

**Comment by cyrilou242** [comment]
Here is an implementation for tf 1.13 

```python
from tensorflow.python.keras import metrics

class F1Score(metrics.Metric):
  """Computes the f1_score of the predictions with respect to the labels.

  For example, if `y_true` is [0, 1, 1, 1] and `y_pred` is [1, 0, 1, 1]
  then the f1_score value is 0.66. If the weights were specified as
  [0, 0, 1, 0] then the precision value would be 1.

  The metric creates three local variables, `true_positives`, `false_positives` and
  `false_negatives` that are used to compute the f1 score.
  This value is ultimately returned as `f1_score`, an operation that
  simply divides computes 2* `precision`*`recall` /(`precision` + `recall`).
  Where `precision` is ...
  and `recall` is ...

  If `sample_weight` is `None`, weights default to 1.
  Use `sample_weight` of 0 to mask values.

  Usage: ...
  """

  def __init__(self, thresholds=None, name=None, dtype=None):
    """Creates a `F1Score` instance.

    Args:
      thresholds: (Optional) Defaults to 0.5. A float value or a python
        list/tuple of float threshold values in [0, 1]. A threshold is compared
        with prediction values to determine the truth value of predictions
        (i.e., above the threshold is `true`, below is `false`). One metric
        value is generated for each threshold value.
      name: (Optional) string name of the metric instance.
      dtype: (Optional) data type of the metric result.
    """
    super(F1Score, self).__init__(name=name, dtype=dtype)
    self.thresholds = metrics._parse_init_thresholds(
        thresholds, default_threshold=0.5)
    self.tp = self.add_weight(
        'true_positives',
        shape=(len(self.thresholds),),
        initializer=metrics.init_ops.zeros_initializer)
    self.fp = self.add_weight(
        'false_positives',
        shape=(len(self.thresholds),),
        initializer=metrics.init_ops.zeros_initializer)
    self.fn = self.add_weight(
        'false_negatives',
        shape=(len(self.thresholds),),
        initializer=metrics.init_ops.zeros_initializer)

  def update_state(self, y_true, y_pred, sample_weight=None):
    """Accumulates true positive, false positive and false negative statistics.

    Args:
      y_true: The ground truth values.
      y_pred: The predicted values.
      sample_weight: Optional weighting of each example. Defaults to 1. Can be a
        `Tensor` whose rank is either 0, or the same rank as `y_true`, and must
        be broadcastable to `y_true`.

    Returns:
      Update op.
    """
    return metrics._update_confusion_matrix_variables({
        metrics._ConfusionMatrix.TRUE_POSITIVES: self.tp,
        metrics._ConfusionMatrix.FALSE_POSITIVES: self.fp,
        metrics._ConfusionMatrix.FALSE_NEGATIVES: self.fn
    }, y_true, y_pred, self.thresholds, sample_weight)

  def result(self):
    precision = math_ops.div_no_nan(self.tp, self.tp + self.fp)
    recall = math_ops.div_no_nan(self.tp, self.tp + self.fn)
    numerator = math_ops.multiply(precision, recall)
    denominator = math_ops.add(precision, recall)
    frac = math_ops.div_no_nan(numerator, denominator)
    result = math_ops.multiply(tf.constant(2.), frac)

    return result[0] if len(self.thresholds) == 1 else result

  def reset_states(self):
    num_thresholds = len(to_list(self.thresholds))
    for v in self.variables:
      K.set_value(v, np.zeros((num_thresholds,)))
```

Metrics have changed a bit, there are now `top_k` and `class_id` parameters that would have to be implemented, and theres also the method `get_config` to implement. 

I can free some time and make a pull request if the approach in the code above is validated.

**Comment by pavithrasv** [comment]
This would be a good candidate for the AddOns repository (https://github.com/tensorflow/addons) and based on how widely it is being used we can move it to TensorFlow core.

**Comment by pavithrasv** [comment]
Please feel free to send a PR to the add ons repository.

**Comment by douglas125** [comment]
This "kind of" works for me (I wanted to have class_id in f1)

But it throws a warning that I don't know how to parse:

> WARNING: Entity <bound method F1Score.update_state of <INS_model.F1Score object at 0x00000181D733C588>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method F1Score.update_state of <INS_model.F1Score object at 0x00000181D733C588>>: AttributeError: module 'gast' has no attribute 'Str'

```
from tensorflow.python.ops import init_ops
from tensorflow.python.ops import math_ops
from tensorflow.python.keras.metrics import Metric
from tensorflow.python.keras.utils import metrics_utils
from tensorflow.python.keras.utils.generic_utils import to_list
from tensorflow.python.keras import backend as K
class F1Score(Metric):
  """Computes the F1 of the predictions with respect to the labels.
  The metric creates two local variables, `true_positives` and `false_positives`
  that are used to compute the precision. This value is ultimately returned as
  `precision`, an idempotent operation that simply divides `true_positives`
  by the sum of `true_positives` and `false_positives`.
  If `sample_weight` is `None`, weights default to 1.
  Use `sample_weight` of 0 to mask values.
  If `top_k` is set, we'll calculate precision as how often on average a class
  among the top-k classes with the highest predicted values of a batch entry is
  correct and can be found in the label for that entry.
  If `class_id` is specified, we calculate precision by considering only the
  entries in the batch for which `class_id` is above the threshold and/or in the
  top-k highest predictions, and computing the fraction of them for which
  `class_id` is indeed a correct label.
  Usage:
  ```python
  m = tf.keras.metrics.F1Score()
  m.update_state([0, 1, 1, 1], [1, 0, 1, 1])
  print('Final result: ', m.result().numpy())
  ```
  Usage with tf.keras API:
  ```python
  model = tf.keras.Model(inputs, outputs)
  model.compile('sgd', loss='mse', metrics=[tf.keras.metrics.F1Score()])
  ```
  """

  def __init__(self,
               thresholds=None,
               top_k=None,
               class_id=None,
               name=None,
               dtype=None):
    """Creates a `F1Score` instance.
    Args:
      thresholds: (Optional) A float value or a python list/tuple of float
        threshold values in [0, 1]. A threshold is compared with prediction
        values to determine the truth value of predictions (i.e., above the
        threshold is `true`, below is `false`). One metric value is generated
        for each threshold value. If neither thresholds nor top_k are set, the
        default is to calculate precision with `thresholds=0.5`.
      top_k: (Optional) Unset by default. An int value specifying the top-k
        predictions to consider when calculating precision.
      class_id: (Optional) Integer class ID for which we want binary metrics.
        This must be in the half-open interval `[0, num_classes)`, where
        `num_classes` is the last dimension of predictions.
      name: (Optional) string name of the metric instance.
      dtype: (Optional) data type of the metric result.
    """
    super(F1Score, self).__init__(name=name, dtype=dtype)
    self.init_thresholds = thresholds
    self.top_k = top_k
    self.class_id = class_id

    default_threshold = 0.5 if top_k is None else metrics_utils.NEG_INF
    self.thresholds = metrics_utils.parse_init_thresholds(
        thresholds, default_threshold=default_threshold)
    self.true_positives = self.add_weight(
        'true_positives',
        shape=(len(self.thresholds),),
        initializer=init_ops.zeros_initializer)
    self.false_positives = self.add_weight(
        'false_positives',
        shape=(len(self.thresholds),),
        initializer=init_ops.zeros_initializer)
    self.false_negatives = self.add_weight(
        'false_negatives',
        shape=(len(self.thresholds),),
        initializer=init_ops.zeros_initializer)    

  def update_state(self, y_true, y_pred, sample_weight=None):
    """Accumulates true positive and false positive statistics.
    Args:
      y_true: The ground truth values, with the same dimensions as `y_pred`.
        Will be cast to `bool`.
      y_pred: The predicted values. Each element must be in the range `[0, 1]`.
      sample_weight: Optional weighting of each example. Defaults to 1. Can be a
        `Tensor` whose rank is either 0, or the same rank as `y_true`, and must
        be broadcastable to `y_true`.
    Returns:
      Update op.
    """
    metrics_utils.update_confusion_matrix_variables(
        {
            metrics_utils.ConfusionMatrix.TRUE_POSITIVES: self.true_positives,
            metrics_utils.ConfusionMatrix.FALSE_POSITIVES: self.false_positives,
            metrics_utils.ConfusionMatrix.FALSE_NEGATIVES: self.false_negatives
        },
        y_true,
        y_pred,
        thresholds=self.thresholds,
        top_k=self.top_k,
        class_id=self.class_id,
        sample_weight=sample_weight)

  def result(self):
    precision = math_ops.div_no_nan(self.true_positives,
                                 self.true_positives + self.false_positives)
    recall = math_ops.div_no_nan(self.true_positives,
                                 self.true_positives + self.false_negatives)
    result = 2*math_ops.div_no_nan(math_ops.multiply(precision, recall),
                                   math_ops.add(precision, recall))
    return result[0] if len(self.thresholds) == 1 else result

  def reset_states(self):
    num_thresholds = len(to_list(self.thresholds))
    K.batch_set_value(
        [(v, np.zeros((num_thresholds,))) for v in self.variables])

  def get_config(self):
    config = {
        'thresholds': self.init_thresholds,
        'top_k': self.top_k,
        'class_id': self.class_id
    }
    base_config = super(F1Score, self).get_config()
    return dict(list(base_config.items()) + list(config.items()))
```

**Comment by cyrilou242** [comment]
My solution is very outdated. 
F1 score has been implemented in the AddOns repository (https://github.com/tensorflow/addons).

Have a look at `tensorflow_addons.metrics.F1Score`

**Comment by PhilipMay** [comment]
F1 in addons seems to have an ugly bug: https://github.com/tensorflow/addons/issues/825
