### ISSUE TITLE
Tensorflow lite: micro_vision is missing person_detect_model_data.cc

### ISSUE THREAD

**Issue by aakbar5** [tensorflow/tensorflow#29792]
Micro vision demo of the Tensorflow Lite is missing model file `person_detect.tflite` as well as `person_detect_model_data.cc` due to which it can't be compiled.

Tensorflow repo info:
```
commit b5102aa41000068787f56a25c3fd48f7d9a80f42 (HEAD -> master, origin/master, origin/HEAD)
Author: A. Unique TensorFlower <gardener@tensorflow.org>
Date:   Fri Jun 14 02:39:21 2019 -0700

    Remove absl::bit_casts of non-trivially-copyable Eigen types, and replace them with a new, extensible xla::BitCast call. The latter does everything absl::bit_cast does, but additionally can be specialized to support non-trivial types.
    
    PiperOrigin-RevId: 253194104
```

**Comment by petewarden** [comment]
This should be fixed now, so closing. Could you let us know if not and we can reopen.

**Comment by nealjack** [comment]
Hi,

I'm looking at the master branch (856af529) and can not find the .tflite model or .cc data file. Is there a different commit or branch that has these files?

**Comment by aakbar5** [comment]
@nealjack You need to run makefile as it will be downloaded during build process.

**Comment by aakbar5** [comment]
Where can I find the model files (.pb or .tflite etc) which have been used to generate person_detect_model_data.cc? @petewarden

**Comment by nealjack** [comment]
I have the same question.

**Comment by njeffrie** [comment]
They are currently only available as c++ source files.  I will have a look at adding the source model to the download.  In the meantime, a simple c++ method which dumps the array to file would re-create the tflite model.  You can find the grayscale c++ file [here](https://storage.googleapis.com/download.tensorflow.org/data/tf_lite_micro_person_data_grayscale.zip):  and the RGB model c++ file [here](https://storage.googleapis.com/download.tensorflow.org/data/tf_lite_micro_person_data.tgz).

**Comment by aakbar5** [comment]
@njeffrie, Thanks - actually for my workspace I have already reverse engineered the .tflite file as well as input data images (I couldn't clearly the face of the person in the picture. Is it you? :) ). IMO uploading .tflite makes sense for the use-case where one doesn't want to compiled alongwith the executable as my application already loading some resources from the storage device so placing model file(s) there makes sense.

I will give shot to the RGB model too.

**Comment by IlkayW** [comment]
@njeffrie Could you upload the .tflite model in the mean time?
It would be very beneficial for me to have the original (unquantized) model as well.
Is there a possibility to get these files?

Thank you in advance :)

**Comment by IlkayW** [comment]
@aakbar5 How did you reversely get the proper .tflite model?
