### ISSUE TITLE
TensorFlow Lite: undefined reference to `flatbuffers::ClassicLocale::instance_'

### ISSUE THREAD

**Issue by YangJiao1996** [tensorflow/tensorflow#29806]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04
- TensorFlow installed from (source or binary): source
- TensorFlow version: r1.13
- Python version: 3.5
- Installed using virtualenv? pip? conda?: virtualenv
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source): 7.4.0
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

**Describe the problem**
I was following the [instructions](https://www.tensorflow.org/lite/guide/build_rpi) to crosscompile TensorFlow Lite for my Raspberry Pi. I got the error messages showing the undefined reference to flatbuffers. 
I believe all the dependencies for Lite are downloaded by the `download_dependencies.sh` script, but I do not have Bazel installed. Is Bazel necessary for compiling TensorFlow Lite?

**Any other info / logs**
```
/home/user/GitRepo/tensorflow/tensorflow/lite/tools/make/gen/rpi_armv7l/lib/libtensorflow-lite.a(while.o): In function `tflite::ops::custom::while_kernel::Init(TfLiteContext*, char const*, unsigned int)':
while.cc:(.text+0x1648): undefined reference to `flatbuffers::ClassicLocale::instance_'
/home/user/GitRepo/tensorflow/tensorflow/lite/tools/make/gen/rpi_armv7l/lib/libtensorflow-lite.a(audio_spectrogram.o): In function `tflite::ops::custom::audio_spectrogram::Init(TfLiteContext*, char const*, unsigned int)':
audio_spectrogram.cc:(.text+0xe0c): undefined reference to `flatbuffers::ClassicLocale::instance_'
/home/user/GitRepo/tensorflow/tensorflow/lite/tools/make/gen/rpi_armv7l/lib/libtensorflow-lite.a(detection_postprocess.o): In function `tflite::ops::custom::detection_postprocess::Init(TfLiteContext*, char const*, unsigned int)':
detection_postprocess.cc:(.text+0x211c): undefined reference to `flatbuffers::ClassicLocale::instance_'
/home/user/GitRepo/tensorflow/tensorflow/lite/tools/make/gen/rpi_armv7l/lib/libtensorflow-lite.a(detection_postprocess.o): In function `flexbuffers::Reference::AsInt64() const':
detection_postprocess.cc:(.text._ZNK11flexbuffers9Reference7AsInt64Ev[_ZNK11flexbuffers9Reference7AsInt64Ev]+0x264): undefined reference to `flatbuffers::ClassicLocale::instance_'
/home/user/GitRepo/tensorflow/tensorflow/lite/tools/make/gen/rpi_armv7l/lib/libtensorflow-lite.a(if.o): In function `tflite::ops::custom::if_kernel::Init(TfLiteContext*, char const*, unsigned int)':
if.cc:(.text+0xf8c): undefined reference to `flatbuffers::ClassicLocale::instance_'
/home/user/GitRepo/tensorflow/tensorflow/lite/tools/make/gen/rpi_armv7l/lib/libtensorflow-lite.a(mfcc.o):mfcc.cc:(.text+0x118c): more undefined references to `flatbuffers::ClassicLocale::instance_' follow
collect2: error: ld returned 1 exit status
tensorflow/lite/tools/make/Makefile:267: recipe for target '/home/user/GitRepo/tensorflow/tensorflow/lite/tools/make/gen/rpi_armv7l/bin/minimal' failed
make: *** [/home/user/GitRepo/tensorflow/tensorflow/lite/tools/make/gen/rpi_armv7l/bin/minimal] Error 1
make: *** Waiting for unfinished jobs....
```

**Comment by bhavints** [comment]
Same issue here

**Comment by YangJiao1996** [comment]
I realized that I made a stupid mistake: I forgot to change the current git branch to the correct version. Hope that could also solve your problem. @bhavints

**Comment by mohan-barathi** [comment]
Hi @YangJiao1996 ..

I am trying to build tflite for aarch64 architecture. I faced some issues, and followed the thread [26731](https://github.com/tensorflow/tensorflow/issues/26731) to solve those one by one.

But still, I'm still facing the `undefined reference to `flatbuffers::ClassicLocale::instance_` issue in compiling minimal and benchmark binaries.
So, I am not sure whether the generated static library is functional or not.

Could you please update on what branch you found the issue fixed ..?!
Many Thanks in advance ..! :)

**Comment by T-Troll** [comment]
Same problem here, but for armv7.

Seems like new version of flatbuffers donesn't have pre-generated lib, and makefile doesn't build it.
Let me check deeper.

**Comment by YangJiao1996** [comment]
@mohan-barathi 
I was using the r1.13 branch for cross-compiling.
@T-Troll 
I also tried to compile locally on my armv7 device. After switching to r1.13 branch, I did not get the errors mentioned in this thread. (Other errors did occur, but I did not dive into it since I already have the library built.)

**Comment by T-Troll** [comment]
I made a patch in Makefile for this -

1. add `$(wildcard tensorflow/lite/tools/make/downloads/flatbuffers/src/util.cpp)` at ther end of CORE_CC_ALL_SRC
2. change LIB_OBJS and BENCHMARK_OBJS to `$(patsubst %.cc,%.o,$(patsubst %.c,%.o,$(patsubst %.cpp,%.o,$(TF_LITE_CC_SRCS)))))` and `
$(patsubst %.cc,%.o,$(patsubst %.c,%.o,$(patsubst %.cpp,%.o,$(BENCHMARK_SRCS)))))`
3. add `$(OBJDIR)%.o: %.cpp
        @mkdir -p $(dir $@)
        $(CXX) $(CXXFLAGS) $(INCLUDES) -c $< -o $@` near other OBJDIR declarations.

Now it builds and works.

**Comment by PeterVanNostrand** [comment]
@T-Troll I am also trying to build TensorFlow Lite and am running into the same issue. I attempted to make the changed you suggested but am getting an error regarding `patsubst`. Could you share your edited Makefile?

**Comment by mohan-barathi** [comment]
Hi @T-Troll ..!

I am currently trying the change you suggested, for aarch64.
I think there is an extra trailing ` )` at the end of 2 `patsubst` expressions you mentioned in change 2.

@PeterVanNostrand ... Did you remove that trailing `)` and try ..?!

**Comment by PeterVanNostrand** [comment]
@mohan-barathi Thanks for the reply. I thought that might have been the problem, but I found a different workaround. If you checkout branch [r1.13](https://github.com/tensorflow/tensorflow/tree/r1.13) from TensorFlow instead of the master branch then the build scripts work as is. I just successfully cross-compiled TFLite for the RPi3B

**Comment by mohan-barathi** [comment]
@PeterVanNostrand ... Good that you can build it. But I am trying for aarch64 architecture, and there is no script for that in 1.13 branch. 😞 

@T-Troll ... After making the changes you have suggested, i am facing the issue
```
aarch64-linux-gnu-gcc: error: armv8-a: No such file or directory
<builtin>: recipe for target 'tensorflow/lite/c/c_api_internal.o' failed
```

and when i checked with `./build_rpi_lib.sh`, a similar error occured:
```
arm-linux-gnueabihf-gcc: error: armv7l: No such file or directory
arm-linux-gnueabihf-g++: error: armv7l: No such file or directory
<builtin>: recipe for target 'tensorflow/lite/c/c_api_internal.o' failed
```
Probably i am doing something wrong when editing the `Makefile` as you suggested.
Can you please provide the working Makefile via a gist or something .?!

Many Thanks in advance ...! :)

**Comment by josemotta** [comment]
Similar libflatbuffers error trying cross compile in a HyperV Debian Linux for the RPI3B+. I already tried with r2.0 and r1.13 with same issue.

In my case, latest error message after several suggested fixes is:

```
//usr/local/lib/libflatbuffers.a: error adding symbols: File format not recognized
collect2: error: ld returned 1 exit status
```
I previously installed flatbuffers lib with:
```
git clone https://github.com/google/flatbuffers.git
cd flatbuffers
apt-get install cmake
cmake -G "Unix Makefiles"
make
make install
```
and also updated LIBS at `tensorflow/lite/tools/make/Makefile`:
```
LIBS := \
+-lflatbuffers \
-lstdc++ \
-lpthread \
-lm \
-ldl \
-lrt
```
Did I miss anything?

**Comment by T-Troll** [comment]
Some points. I build TF lite for custom ARM board, so i use armel, not armhf.
Here are my Makefile - https://yadi.sk/d/KDQHxzSb-y5u5Q

**Comment by YangJiao1996** [comment]
Looks like many people are still having problems in building the library, so I reopened this issue for further discussion. Please let me know when we have solutions for all platforms mentioned in this thread. Thank you! @T-Troll

**Comment by T-Troll** [comment]
> In my case, latest error message after several suggested fixes is:
> //usr/local/lib/libflatbuffers.a: error adding symbols: File format not recognized
> Did I miss anything? Looks like lib was not built for RPI3+

It's a bit heavy way, libflatbuffers not required by tflite, but seems like old hack (see in Makefile) didn't work yet. But it should be ok, if you build it for the same arch as well.

**Comment by bhavints** [comment]
I partially solved this issue by getting the build_aarch64.sh script from the master branch. I also had to change a few things in the makefile (like building zlib from source and also adding -ldl to my library opts).

**Comment by josemotta** [comment]
Hi @T-Troll, thanks for the hack. I checked that your makefile added the "flatbuffers" line below to CORE_CC_ALL_SRCS assignment. Then, I´ll keep trying.

`$(wildcard tensorflow/lite/tools/make/downloads/flatbuffers/src/util.cpp)`

By the way, the regular Tensorflow is installing smoothly at RPI3B+:
```
sudo apt-get update
sudo apt install libatlas-base-dev
pip3 install tensorflow
```

**Comment by covertg** [comment]
Same issue here, Debian 10 trying to build for a Pi. Thanks @T-Troll! The three edits below resolved the issue.

> I made a patch in Makefile for this -
> 
>     1. add `$(wildcard tensorflow/lite/tools/make/downloads/flatbuffers/src/util.cpp)` at ther end of CORE_CC_ALL_SRC
> 
>     2. change LIB_OBJS and BENCHMARK_OBJS to `$(patsubst %.cc,%.o,$(patsubst %.c,%.o,$(patsubst %.cpp,%.o,$(TF_LITE_CC_SRCS)))))` and ` $(patsubst %.cc,%.o,$(patsubst %.c,%.o,$(patsubst %.cpp,%.o,$(BENCHMARK_SRCS)))))`
> 
>     3. add `$(OBJDIR)%.o: %.cpp @mkdir -p $(dir $@) $(CXX) $(CXXFLAGS) $(INCLUDES) -c $< -o $@` near other OBJDIR declarations.
> 
> 
> Now it builds and works.

**Comment by NatGr** [comment]
> Same issue here, Debian 10 trying to build for a Pi. Thanks @T-Troll! The three edits below resolved the issue.
> 
> > I made a patch in Makefile for this -
> > ```
> > 1. add `$(wildcard tensorflow/lite/tools/make/downloads/flatbuffers/src/util.cpp)` at ther end of CORE_CC_ALL_SRC
> > 
> > 2. change LIB_OBJS and BENCHMARK_OBJS to `$(patsubst %.cc,%.o,$(patsubst %.c,%.o,$(patsubst %.cpp,%.o,$(TF_LITE_CC_SRCS)))))` and ` $(patsubst %.cc,%.o,$(patsubst %.c,%.o,$(patsubst %.cpp,%.o,$(BENCHMARK_SRCS)))))`
> > 
> > 3. add `$(OBJDIR)%.o: %.cpp @mkdir -p $(dir $@) $(CXX) $(CXXFLAGS) $(INCLUDES) -c $< -o $@` near other OBJDIR declarations.
> > ```
> > 
> > 
> > Now it builds and works.

Hi, I have the same use case but when adding those modifications, I ran into 
```
arm-linux-gnueabihf-g++: error: armv7l: No such file or directory
arm-linux-gnueabihf-gcc: error: armv7l: No such file or directory
```
like @mohan-barathi.
Did you faced something similar?

**Comment by T-Troll** [comment]
> ```
> arm-linux-gnueabihf-g++: error: armv7l: No such file or directory
> arm-linux-gnueabihf-gcc: error: armv7l: No such file or directory
> ```

Yes, it belongs to mess in makefile or in /targets/rpi_makefile.inc

**Comment by aaag97** [comment]
can someone attach the makefile please? I'm having trouble implementing the changes and the link for the makefile that has been posted does not work for me

**Comment by T-Troll** [comment]
> can someone attach the makefile please? I'm having trouble implementing the changes and the link for the makefile that has been posted does not work for me

Ok, this one for you - https://mega.nz/#!eYVSzaII (but i don't know the country Yandex is blocked, you are the first). I will not use google drive, dropbox or any other global-spy services.

**Comment by aaag97** [comment]
Thank you! @T-Troll it finally works for me :)

**Comment by jvishnuvardhan** [comment]
Automatically closing this out since I understand it to be resolved, but please let me know if I'm mistaken.Thanks!

**Comment by covertg** [comment]
@jvishnuvardhan this issue is still in the codebase. I'm not knowledgeable enough about the TF codebase to know whether this solution is a hacky workaround or a clean solution — but I don't think the issue should be closed. Think we need a PR.

**Comment by jvishnuvardhan** [comment]
@covertg I am opening it. Are you or anyone interested in creating a PR? Thanks!

**Comment by T-Troll** [comment]
The only discussible hack here is adding utils.cpp, the rest is just support for .cpp file handling.
I can't push it directly, let me check about request.

**Comment by lllidan-yuandian** [comment]
> > can someone attach the makefile please? I'm having trouble implementing the changes and the link for the makefile that has been posted does not work for me
> 
> Ok, this one for you -https://mega.nz/#!eYVSzaII!cJbqTnJa2QYotKpJtnFnLl9gaIl4z9rnAizmOn_yQQ8 (but i don't know the country Yandex is blocked, you are the first). I will not use google drive, dropbox or any other global-spy services.

Thanks, it works

**Comment by mohan-barathi** [comment]
Hi @T-Troll ... 
Thanks for the update. I have added the workarounds mentioned in issue [26731](https://github.com/tensorflow/tensorflow/issues/26731) along with your changes to the Makefile.

Now I am successful in building the library for aarch64 architecture.
[Gist of the new integrated Makefile](https://gist.github.com/mohan-barathi/538c45a77cd8531fb9f4367dd2e0cd1a)

**Comment by petewarden** [comment]
It looks like this is working now, so closing.

**Comment by wahyubram82** [comment]
> @PeterVanNostrand ... Good that you can build it. But I am trying for aarch64 architecture, and there is no script for that in 1.13 branch. 
> 
> @T-Troll ... After making the changes you have suggested, i am facing the issue
> 
> ```
> aarch64-linux-gnu-gcc: error: armv8-a: No such file or directory
> <builtin>: recipe for target 'tensorflow/lite/c/c_api_internal.o' failed
> ```
> 
> and when i checked with `./build_rpi_lib.sh`, a similar error occured:
> 
> ```
> arm-linux-gnueabihf-gcc: error: armv7l: No such file or directory
> arm-linux-gnueabihf-g++: error: armv7l: No such file or directory
> <builtin>: recipe for target 'tensorflow/lite/c/c_api_internal.o' failed
> ```
> 
> Probably i am doing something wrong when editing the `Makefile` as you suggested.
> Can you please provide the working Makefile via a gist or something .?!
> 
> Many Thanks in advance ...! :)

first, type this:
`aarch64_linux_ ` and press TAB button twice, to view your compiler command.
mine is `aarch64-linux-android-g++-8`

then just edit the file build_aarch64_lib.sh
`nano build_aarch64_lib.sh`

you will see this line

`make -j4 VERBOSE=1 TARGET=aarch64 -C "${TENSORFLOW_DIR}" -f tensorflow/lite/tools/make/MakeFile`

change it with:

`make -j4 VERBOSE=1 TARGET=aarch64-linux-android-g++-8 -C "${TENSORFLOW_DIR}" -f tensorflow/lite/tools/make/MakeFile`

that's all finish...
