### ISSUE TITLE
FeatureColumn - implement many-to-one categorical column

### ISSUE THREAD

**Issue by novog** [tensorflow/tensorflow#29808]
- TensorFlow version (you are using): 2.0.0b0
- Are you willing to contribute it (Yes/No): Yes

**Describe the feature and the current behavior/state.**
Currently, categorical column class numbers can be assigned sequentially based on a list or one-input-per-line file. It would be useful to support situations where groups of possible input values are known to be equivalent, and so should have the same class number. This feature could be implemented via a `categorical_column_with_vocabulary_dict` function that accepts a dictionary mapping input values to class numbers, rather than a list or file.

**Will this change the current api? How?**
Yes; it would add a `categorical_column_with_vocabulary_dict` function.

**Who will benefit with this feature?**
People using non-normalized input data where multiple possible inputs can be equivalent will benefit.

**Any Other info.**

**Comment by rmothukuru** [comment]
@novog,
Sorry for the delayed response. The documentation of [Estimators](https://www.tensorflow.org/guide/estimator) states:

> Warning: Estimators are not recommended for new code. Estimators run v1.Session-style code which is more difficult to write correctly, and can behave unexpectedly, especially when combined with TF 2 code. Estimators do fall under our compatibility guarantees, but will receive no fixes other than security vulnerabilities. See the migration guide for details.

Can you please let us know if this **`Feature`** is still relevant? Thanks!
