### ISSUE TITLE
Having problem modifying sample_distorted_bounding_box

### ISSUE THREAD

**Issue by jerryzhang0411** [tensorflow/tensorflow#29828]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 16.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): source
- TensorFlow version: r1.14
- Python version: 3.5
- Installed using virtualenv? pip? conda?: virtualenv
- Bazel version (if compiling from source): 0.25.2
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 9.0/7.0
- GPU model and memory:

**Describe the problem**

Hi all. I am trying to modify the behavior of tf.image.sample_distorted_bounding_box so I digged into sample_distorted_bounding_box_op.cc and made some changes including several lines of `cout << "Hi" << endl;` for logging. Then I recompiled this library using `bazel build //tensorflow/core/kernels/sample_distorted_bounding_box_op`. However when I reran tf.image.sample_distorted_bounding_box, it seems nothing changed. May I know what else should I do to modify the TensorFlow built-in api?

Thanks in advance!

**Comment by achandraa** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged//tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there and can provide faster and better help for such issues. Thanks!
