### ISSUE TITLE
[TF 2.0 API Docs] tf.estimator.SessionRunHook

### ISSUE THREAD

**Issue by percyashu** [tensorflow/tensorflow#29822]
URL(s) with the issue:

https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/estimator/SessionRunHook
Description of issue (what needs changing):
Clear description

Yes clear description
Correct links

The link to the source code correct.
Parameters defined

All parameters defined and formatted correctly.
Returns defined

Return values are defined.
Raises listed and defined

No raises listed and defined.
Usage example

No usage examples provided
Request visuals, if applicable

No visuals included

**Comment by jvishnuvardhan** [comment]
I think this was resolved with the update docs which list couple of guides and tutorials to migrate `SessionRunHook` to recent and more advanced methods.
https://www.tensorflow.org/api_docs/python/tf/estimator/SessionRunHook

> This guide demonstrates how to migrate from SessionRunHook to TensorFlow 2's custom callbacks with the tf.keras.callbacks.Callback API

I am closing this issue as this was resolved. Thanks!
