### ISSUE TITLE
[TF 2.0 API Docs] tf.estimator.StepCounterHook

### ISSUE THREAD

**Issue by percyashu** [tensorflow/tensorflow#29821]
## URL(s) with the issue:

https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/estimator/SessionRunHook

### Clear description

Yes clear description

### Correct links

The link to the source code correct.

### Parameters defined

All parameters defined and formatted correctly.

### Returns defined
Return values are defined.

### Raises listed and defined
No raises listed and defined.

### Usage example

No usage examples provided

### Request visuals, if applicable

No visuals included

**Comment by ymodak** [comment]
duplicate #29822
