### ISSUE TITLE
GPU Support - Shared Object Exclusion 

### ISSUE THREAD

**Issue by ghost** [tensorflow/tensorflow#29835]
[UPDATE]:  This issue is about Maven artifact organization / dependency management and documentation.  

**System information**
- OS Platform and Distribution: Linux Ubuntu 18.04.2 LTS
- TensorFlow installed from Maven, version 1.13.1
- TensorFlow version: 1.13.1
- Python version: 3.6.7
- Installed using virtualenv
- CUDA/cuDNN version:  NVIDIA-SMI 418.43       Driver Version: 418.43       CUDA Version: 10.1
- GPU model and memory: 4xNvidia 1080Ti, 

**Describe the problem**

I have created a TensorFlow model in Python and saved it to the disk using the standard method:

    builder = tf.saved_model.builder.SavedModelBuilder(model_directory) 
    builder.add_meta_graph_and_variables(sess, [tf.saved_model.tag_constants.SERVING]) 
    builder.save(False)

Next I am loading the model in Java:

    SavedModelBundle savedModelBundle = SavedModelBundle.loader(modelDir)
        .withTags("serve")
        .withConfigProto(
            ConfigProto.newBuilder()
                .setGpuOptions(
                    GPUOptions.newBuilder()
                        .setPerProcessGpuMemoryFraction(1.0).build())
                .setLogDevicePlacement(true)
                .build().toByteArray())
        .load();
    Session session = savedModelBundle.session();

In my pom.xml I have

    <dependency>
        <groupId>org.tensorflow</groupId>
        <artifactId>tensorflow</artifactId>
        <version>${tensorflow.version}</version>
    </dependency>
    <dependency>
        <groupId>org.tensorflow</groupId>
        <artifactId>proto</artifactId>
        <version>${tensorflow.version}</version>
    </dependency>
    <dependency>
        <groupId>org.tensorflow</groupId>
        <artifactId>libtensorflow_jni_gpu</artifactId>
        <version>${tensorflow.version}</version>
    </dependency>

However, this fails to use my GPU's on startup

    2019-06-15 23:48:38.130731: I tensorflow/compiler/xla/service/service.cc:150] 
        XLA service 0x7fbfc4656e10 executing computations on platform Host. Devices:
    2019-06-15 23:48:38.130768: I tensorflow/compiler/xla/service/service.cc:158]   
        StreamExecutor device (0): <undefined>, <undefined>
        Device mapping:
            /job:localhost/replica:0/task:0/device:XLA_CPU:0 -> device: XLA_CPU device
    2019-06-15 23:48:38.131168: I tensorflow/core/common_runtime/direct_session.cc:317]    
       Device mapping:
        /job:localhost/replica:0/task:0/device:XLA_CPU:0 -> device: XLA_CPU device

Please advise on how to use GPU with SaveModelBundle.

**Comment by dwilliams999** [comment]
One interesting thing to note here, is that when I download the shared objects manually:

    https://storage.googleapis.com/tensorflow/libtensorflow/libtensorflow_jni-gpu-linux-x86_64-1.13.1.tar.gz

and place them in my shaded jar resources

    19798441 Fri Nov 30 04:08:00 PST 1979 org/tensorflow/native/linux-x86_64/libtensorflow_framework.so
    281091096 Fri Nov 30 04:08:00 PST 1979 org/tensorflow/native/linux-x86_64/libtensorflow_jni.so

 then I am able to use my GPUs

    2019-06-16 07:07:16.919142: I tensorflow/compiler/xla/service/service.cc:150] XLA service 0x7ff270e69e80 executing computations on platform CUDA. Devices:
    2019-06-16 07:07:16.919178: I tensorflow/compiler/xla/service/service.cc:158]   StreamExecutor device (0): GeForce GTX 1080 Ti, Compute Capability 6.1
    2019-06-16 07:07:16.919192: I tensorflow/compiler/xla/service/service.cc:158]   StreamExecutor device (1): GeForce GTX 1080 Ti, Compute Capability 6.1
    2019-06-16 07:07:16.919204: I tensorflow/compiler/xla/service/service.cc:158]   StreamExecutor device (2): GeForce GTX 1080 Ti, Compute Capability 6.1
    2019-06-16 07:07:16.919215: I tensorflow/compiler/xla/service/service.cc:158]   StreamExecutor device (3): GeForce GTX 1080 Ti, Compute Capability 6.1
    2019-06-16 07:07:16.942508: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 3598270000 Hz

Is it possible that the Maven artifacts are out of date in Maven Central?  What is the difference between the shared objects hosted in Maven vs storage.googleapis?

**Comment by dwilliams999** [comment]
Update, the solution to this issue is related to the Maven shade plugin.  With Maven shade, an exclusion must be made to enable GPU support:

        <dependency>
            <groupId>org.tensorflow</groupId>
            <artifactId>tensorflow</artifactId>
            <exclusions>
                <exclusion>
                    <groupId>org.tensorflow</groupId>
                    <artifactId>libtensorflow_jni</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>org.tensorflow</groupId>
            <artifactId>proto</artifactId>
        </dependency>
        <dependency>
            <groupId>org.tensorflow</groupId>
            <artifactId>libtensorflow_jni_gpu</artifactId>
        </dependency>

It would be nice if this was documented on the [Java installation guideline](https://www.tensorflow.org/install/lang_java), or better would be to publish Maven artifacts which explicitly provide the required native support and not bundle libtensorflow_jni with the [tensorflow dependency](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/java/maven/tensorflow/pom.xml).

**Comment by dwilliams999** [comment]
Thanks @achandraa for adding the docs tag.  Here's another interesting thing to highlight in the solution.  If you want seamless Mac OSX support, plus automatic Linux support for GPU, then any Maven Shade Plugin solution for creating wide jars will also need filter exclusions:

	<filters>
	    <filter>
	        <artifact>org.tensorflow:libtensorflow_jni</artifact>
	        <excludes>
	            <exclude>org/tensorflow/native/linux-x86_64/**</exclude>
	            <exclude>org/tensorflow/native/windows-x86_64/**</exclude>
	        </excludes>
	    </filter>
	    <filter>
	        <artifact>org.tensorflow:libtensorflow_jni_gpu</artifact>
	        <includes>
	            <include>org/tensorflow/native/linux-x86_64/**</include>
	            <include>org/tensorflow/native/windows-x86_64/**</include>
	        </includes>
	    </filter>
	</filters>

As an aside, since the shared objects in `org.tensorflow:libtensorflow_jni_gpu` will downgrade to CPU when there is no GPU, why not bundle these with `org.tensorflow:libtensorflow_jni`?

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.
