### ISSUE TITLE
Tensorflow for Kotlin Multiplatform

### ISSUE THREAD

**Issue by natanfudge** [tensorflow/tensorflow#29837]
Currently Tensorflow supports [Javascript](https://www.tensorflow.org/js), [Java](https://www.tensorflow.org/install/lang_java), and [C](https://www.tensorflow.org/install/lang_c). These are all the target programming languages of [Kotlin Multiplatform](https://kotlinlang.org/docs/reference/multiplatform.html). Therefore, it would be theoretically possible to port Tensorflow to be a Kotlin Multiplatform Library by just reusing the existing APIs. 
Are there any plans for this? If not, what do you think about the idea?

**Comment by ymodak** [comment]
duplicate #27064
