### ISSUE TITLE
Multiple CPU usage ineffective: CPU utilization only 200% on a 8 core VM

### ISSUE THREAD

**Issue by jun-z** [tensorflow/tensorflow#2983]
This is the same as #583. Opening a new issue since CPU utilization is still low. I built tensorflow with `-mavx2` flag and ran `examples/tutorials/word2vec/word2vec_basic.py`. TensorFlow is recognizing num of cores as 8, yet still only 200% of CPU is used during training.

### Environment info
Operating System:
14.04.1-Ubuntu x86_64 GNU/Linux

Installed version of CUDA and cuDNN: 
No CUDA or cuDNN installed.

If installed from sources, provide the commit hash:
Commit hash:
```
840c4ac
a2d6cf7
5b66275
27b83b7
b77f607
ce330a7
2c33855
451f18c
af794ed
921b709
```

### Steps to reproduce
1. Enable logging of `inter_op_parallelism_threads` and `intra_op_parallelism_threads`.
2. Configure, build tensorflow with AVX2 with this command
`bazel build -c opt --copt=-mavx2 //tensorflow/tools/pip_package:build_pip_package`
3. Build wheel, install package and run ` python examples/tutorials/word2vec/word2vec_basic.py`.

**Comment by prb12** [comment]
This is not a bug.  

The word2vec_**basic**.py tutorial is an unoptimized example designed to illustrate a point. It feeds training examples via a sequential and high-overhead mechanism, contains numerous small ops which are expensive to dispatch and there are parts of the model where there is not much opportunity for parallelism.    

Please read the [tutorial](https://www.tensorflow.org/versions/r0.9/tutorials/word2vec/index.html) section entitled "**Optimizing the Implementation**" which states:

> For example, the naive code we used in this tutorial would suffer compromised speed because we use Python for reading and feeding data items -- each of which require very little work on the TensorFlow back-end

The tutorial provides two faster variants. 
https://github.com/tensorflow/tensorflow/blob/r0.9/tensorflow/models/embedding/word2vec.py
https://github.com/tensorflow/tensorflow/blob/r0.9/tensorflow/models/embedding/word2vec_optimized.py

**Comment by orian** [comment]
Just for future references, models have been moved to a separate repo:
https://github.com/tensorflow/models/tree/master/tutorials/embedding
