### ISSUE TITLE
Using TF estimator with tf.data fetched from tfds

### ISSUE THREAD

**Issue by vmirly** [tensorflow/tensorflow#29832]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.00-beta
- Python version: 3.7
- Bazel version (if compiling from source): NA
- GCC/Compiler version (if compiling from source): NA
- CUDA/cuDNN version: NA
- GPU model and memory: NA

**Describe the current behavior**

I am trying to use a pre-made estimator with a dataset fetched from tensorflow_dataset. I have followed the steps from the guide, but it gives an error:

```
RuntimeError: Attempting to capture an EagerTensor without building a function.
```

I have also looked at this other issue ([issue #24592](https://github.com/tensorflow/tensorflow/issues/24592)) but the solution provided there does not apply to me.

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

I am trying to use the pre-made estimator `tf.estimator.DNNClassifier` to use on the MNIST dataset. I load the dataset from `tensorflow_dataset`.

I pursue the following four steps: first building the dataset pipeline and defining the input function:

```python
## Step 1
mnist, info = tfds.load('mnist', with_info=True)

ds_train_orig, ds_test = mnist['train'], mnist['test']

def train_input_fn(dataset, batch_size):
    dataset = dataset.map(lambda x:({'image-pixels':tf.reshape(x['image'], (-1,))}, 
                                    x['label']))
    return dataset.shuffle(1000).repeat().batch(batch_size)
```

Then, in step 2, I define the feature column with a single key, and shape 784:

```python
## Step 2:
image_feature_column = tf.feature_column.numeric_column(key='image-pixels',
                                                        shape=(28*28))

image_feature_column
NumericColumn(key='image-pixels', shape=(784,), default_value=None, dtype=tf.float32, normalizer_fn=None)
```

Step 3, I instantiated the estimator as follows:

```python
## Step 3:
dnn_classifier = tf.estimator.DNNClassifier(
    feature_columns=image_feature_column,
    hidden_units=[16, 16],
    n_classes=10)
```

And finally, step 4 using the estimator by calling the `.train()` method:

```python
## Step 4:
dnn_classifier.train(
    input_fn=lambda:train_input_fn(ds_train_orig, batch_size=32),
    #lambda:iris_data.train_input_fn(train_x, train_y, args.batch_size),
    steps=20)
```

**Comment by vmirly** [comment]
Solved, based on the answer from Stackoverflow: https://stackoverflow.com/questions/56612386/defining-the-input-function-for-tensorflow-pre-made-estimator/56615591#56615591 

For eager execution, I should define the tfds dataset inside the function.

**Comment by DachuanZhao** [comment]
@vmirly same error ...... Thanks for your answer , but I think ```For eager execution, I should define the tfds dataset inside the function.``` should be written in tensorflow estimator document ......
