### ISSUE TITLE
tf.image.decode_and_crop_jpeg parameter crop_window changed

### ISSUE THREAD

**Issue by alon1samuel** [tensorflow/tensorflow#29844]
Thank you for submitting a TensorFlow documentation issue. Per our GitHub
policy, we only address code/doc bugs, performance issues, feature requests, and
build/installation issues on GitHub.

The TensorFlow docs are open source! To get involved, read the documentation
contributor guide: https://www.tensorflow.org/community/contribute/docs

## URL(s) with the issue:
https://www.tensorflow.org/api_docs/python/tf/io/decode_and_crop_jpeg

## Description of issue :
Documentation of parameter type - crop_window

### Clear description
The type of parameter is list of int and in the documentation it says:

>     crop_window: A `Tensor` of type `int32`.

**Comment by ymodak** [comment]
I made a toy example and observed that ```crop_window`` argument can take a tensor as well as a list. Perhaps we can make changes to the existing documentation.

**Comment by lamberta** [comment]
Ya know, I don't know where this docstring lives :/
Found it in this wrappers.go file: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/go/op/wrappers.go
but I'm not certain that's the source of truth.

**Comment by MarkDaoust** [comment]
This is a hard one to track down the SOT for.

The builtin ops's docstrings are usuallt set by these protos:
 https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/api_def/base_api/api_def_DecodeJpeg.pbtxt 

There isn't one for "decode_and_crop", it's not implemented as a stand alone op. It's an overload of DecodeImage?:

https://github.com/tensorflow/tensorflow/tree/master/tensorflow/core/kernels/decode_image_op.cc

---------------------------

Anyway, enough spelunking. 

I believe the correct answer here is:

> **Any function that takes a `Tensor` argument will also accept anything that can be converted to a tensor by `tf.convert_to_tensor`**

This is/should be true for every op, not just this one. If there's an action to take here it's that we need to better publicize the above fact. 

How about we add it to the top of: https://www.tensorflow.org/guide/tensors 

WDYT?

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.

**Comment by MarkDaoust** [comment]
The current docs say: 

```
crop_window:  A Tensor of type int32. 1-D. The crop window: [crop_y, crop_x, crop_height, crop_width].
```

So this is fixed.
