### ISSUE TITLE
[TF 2.0 API Docs] tf.errors.ResourceExhaustedError

### ISSUE THREAD

**Issue by Wil2129** [tensorflow/tensorflow#29847]
## URL with the issue:

https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/errors/ResourceExhaustedError

## Description of issue (what needs changing):

The API symbol doesn't contain a complete, self-contained, coherent, appropriately formatted, and well-documented code sample.

### Usage example

No usage example

**Comment by kumariko** [comment]
@Wil2129 We are checking to see if you still need help on this issue. Could you please have a look on the [link1](https://github.com/tensorflow/tensorflow/blob/v2.7.0/tensorflow/python/framework/errors_impl.py#L367-L379) , [link2](https://www.tensorflow.org/versions/r2.7/api_docs/python/tf/errors/ResourceExhaustedError) and let us know if it helps?
