### ISSUE TITLE
[TF 2.0 API Docs] tf.debugging.assert_type

### ISSUE THREAD

**Issue by Wil2129** [tensorflow/tensorflow#29849]
## URL with the issue:

https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/debugging/assert_type

## Description of issue (what needs changing):

The API symbol doesn't contain a complete, self-contained, coherent, appropriately formatted, and well-documented usage example code sample and the return values aren't defined

### Usage example

No usage example

### Returns defined

The return values aren't defined

**Comment by ymodak** [comment]
Closes this issue since commit [52a7bfe](https://github.com/tensorflow/tensorflow/commit/52a7bfee453e449e715e7f0847e74f03ff6b9036) updates the docs for usage examples. Thanks!
