### ISSUE TITLE
tf.keras.layers.Conv3DTranspose ignores dilation_rate parameter

### ISSUE THREAD

**Issue by jankukacka** [tensorflow/tensorflow#29841]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): N/A
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): N/A
- TensorFlow version (use command below): 1.13
- Python version: Any
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

**Describe the current behavior**

 `Conv3DTranspose` layer ignores `dilation_rate` parameter. The shape of the output tensor stays the same regardless of the `dilation_rate` parameter.

**Describe the expected behavior**

 `Conv3DTranspose` should behave like `Conv2DTranspose` and handle dilated transposed convolution. Note that `Conv3D` handles dilated convolutions all right.

**Code to reproduce the issue**

    import tensorflow as tf
    import numpy as np
    from tensorflow.keras.layers import Conv3DTranspose

    sess = tf.Session()
    x = tf.placeholder(tf.float32, shape=(None,3,3,3,1))
    layer = Conv3DTranspose(filters=1, kernel_size=3, dilation_rate=2)
    result = layer(x)
    sess.run(tf.global_variables_initializer())
    output = sess.run(result, {x:np.ones((2,3,3,3,1))})

    ## Expected output shape = (2,7,7,7,1)
    ## Actual output shape = (2,5,5,5,1)

**Other info / logs**
The problematic code seems to be here:
https://github.com/tensorflow/tensorflow/blob/r1.13/tensorflow/python/keras/layers/convolutional.py#L890

**Comment by achandraa** [comment]
Have tried on Colab with TF 1.13.1 and was able to reproduce the issue.

**Comment by jankukacka** [comment]
Perhaps this is a feature request rather than a bug. I checked that `Conv2DTranspose` uses custom implementation from Keras submodule (https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/keras/backend.py#L4633) which is not implemented for 3D transposed convolutions at all...

**Comment by tanzhenyu** [comment]
Conv3DTranspose does not have a dilation rate for now

**Comment by tanzhenyu** [comment]
Would you like to make a PR out of it? I will make this as contribution welcome.

**Comment by jaketae** [comment]
Not sure if this is directly relevant to this thread, but is `keras.backend.conv3d_transpose` still a relevant function worth keeping? It seems like `keras.layers.Conv3DTranspose` calls on `nn_ops` directly instead of routing to `keras.backend`. This contrasts with similar layers like `keras.layers.Conv2DTranspose`, which calls on `keras.backend.conv2d_transpose` internally (which then eventually calls on `nn_ops`).

At any rate, I'll be editing the docstrings to erase the `dilation_rate` argument as of now since it is an unsupported feature as of yet.

**Comment by tanzhenyu** [comment]
Fixed here: https://github.com/tensorflow/tensorflow/commit/46c79db67db33d7a14e124fc0b5cf23e0910d039

**Comment by fthielke** [comment]
The commit linked above does _not_ fix the problem:

While dilation_rate is now passed to the parent constructor, it is not actually used - neither for output shape calculation in the call to `conv_utils.deconv_output_length` nor for the actual computation in the call to `nn.conv3d_transpose`.

The test case introduced in the commit is also wrong in that regard - the output shape with a dilation rate of 2 for an input of `(5, 7, 6)` should be `(9, 11, 10)`.

Besides, dilation_rate is still not even stored in the config dict.
