### ISSUE TITLE
[TF 2.0 API Docs] tf.dynamic_stitch

### ISSUE THREAD

**Issue by lkmandy** [tensorflow/tensorflow#29858]
## System Information
Tensorflow version: 2.0

## URL(s) with the issue:
https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/dynamic_stitch

### Raises listed and defined
No errors have been defined

**Comment by ymodak** [comment]
The docs are now updated https://www.tensorflow.org/api_docs/python/tf/dynamic_stitch
Thanks!
