### ISSUE TITLE
[TF 2.0 API Docs] https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/keras/layers/MaxPool1D

### ISSUE THREAD

**Issue by allenbangai** [tensorflow/tensorflow#29855]
1.	The parameters pool_function and input_spec in https://github.com/tensorflow/tensorflow/blob/r2.0/tensorflow/python/keras/layers/pooling.py#L59 where not defined the documentation https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/keras/layers/MaxPool1D and no return where defined.

**Comment by allenbangai** [comment]
1. The parameters of pool_function at line 65, input_spec at line 70 and base_config at 597 in https://github.com/tensorflow/tensorflow/blob/r2.0/tensorflow/python/keras/layers/pooling.py where not defined in https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/keras/layers/MaxPool3D and https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/keras/layers/MaxPool2D.

2. Return types where not defined in both https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/keras/layers/MaxPool3D and https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/keras/layers/MaxPool2D.

**Comment by sushreebarsa** [comment]
@allenbangai Please post this issue on [keras-team/keras repo.](https://github.com/keras-team/keras/issues)
To know more see;
[https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999](https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999)
