### ISSUE TITLE
[TF 2.0 API Docs] Documentation describes non existing symbol

### ISSUE THREAD

**Issue by xurror** [tensorflow/tensorflow#29852]
https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/debugging/check_numerics

This link gives a description of a symbol in a module which is supposed to be at https://github.com/tensorflow/tensorflow/tree/r2.0/tensorflow/python/ops

But the module doesn't seem to exist

**Comment by jvishnuvardhan** [comment]
@xurror The symbol you are looking will be generated file as it was clearly mentioned in the description as `Defined in generated file: python/ops/gen_array_ops.py`. There are files that generates this file. Thanks! Please let me know if you are looking for any other details. Thanks!

**Comment by jvishnuvardhan** [comment]
Automatically closing this out since I understand it to be resolved, but please let me know if I'm mistaken.Thanks!
