### ISSUE TITLE
[TF 2.0 API Docs] tf.errors.DeadlineExceededError

### ISSUE THREAD

**Issue by lkmandy** [tensorflow/tensorflow#29859]
## System Information
Tensorflow version: 2.0

## URL(s) with the issue:
https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/errors/DeadlineExceededError

### Clear description
The description could be better; needs more content for clarification

### Usage example
No usage example defined  

### Submit a pull request?
No

**Comment by rmothukuru** [comment]
@lkmandy,
In the documentation of [tf.errors.DeadlineExceededError](https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/errors/DeadlineExceededError), it is mentioned 

> This exception is not currently used.

Since we don't use this **`Exception`**, can you please let us know if we can close this issue? Thanks!

**Comment by lkmandy** [comment]
Yes please, you can close this issue if the Exception is deprecated or something like that
