### ISSUE TITLE
[TF 2.0 API Docs] tf.div_no_nan

### ISSUE THREAD

**Issue by Wil2129** [tensorflow/tensorflow#29853]
## URL(s) with the issue:

https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/div_no_nan

## Description of issue (what needs changing):

The web page corresponding to the link does not exist. Error 404

### Correct links

The link is not correct. The page doesn't exist

**Comment by achandraa** [comment]
Can you please help us to know from which link this [page](https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/div_no_nan) is been directed. Thanks!

**Comment by Wil2129** [comment]
The link is correct but the page does not exists
![Untitled](https://user-images.githubusercontent.com/23650880/59790851-c489f200-92c8-11e9-899b-f33e776bcf29.png)

**Comment by achandraa** [comment]
Not able to find out the original page which links to this 404 error page. Is it been directed from [here](https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/). Thanks!

**Comment by Wil2129** [comment]
This  is the [https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/div_no_nan](link) from the documentation. And as I said the link is as it should be but when you go there you see the 404 error page. Or am I not understanding the question?

**Comment by achandraa** [comment]
Sorry for not able to convey the message. It looks like you are referring to wrong page. Please have a look to this [link](https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/math/divide_no_nan) which is under tf.math with the name divide_no_nan and let us know if this is the one you are searching for. Thanks!

**Comment by Wil2129** [comment]
Yeah, I looks like this is the correct link. The fact is, in the docs task the name of the API symbol is [tf.div_no_nan](https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/div_no_nan) whereas [tf.math.divide_no_nan](https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/math/divide_no_nan) is not even present there. I think this might be the symbol that was meant to be there. Also, sorry for the late reply 😥.

**Comment by achandraa** [comment]
Good to know that was the correct link. Can we close on this issue since it is resolved. Let us know. Thanks!

**Comment by Wil2129** [comment]
Yeah, and now someone needs to add the correct symbol to the docs task.

**Comment by achandraa** [comment]
Are you satisfied with the resolution of your issue?<br> [Yes](https://docs.google.com/forms/d/e/1FAIpQLSfaP12TRhd9xSxjXZjcZFNXPGk4kc1-qMdv3gc6bEP90vY1ew/viewform?entry.85265664=Yes&entry.2137816233=29853)<br> [No](https://docs.google.com/forms/d/e/1FAIpQLSfaP12TRhd9xSxjXZjcZFNXPGk4kc1-qMdv3gc6bEP90vY1ew/viewform?entry.85265664=No&entry.2137816233=29853)
