### ISSUE TITLE
[TF 2.0 API Docs] tf.dynamic_partition

### ISSUE THREAD

**Issue by lkmandy** [tensorflow/tensorflow#29854]
## System information
Tensorflow version: 2.0

## URL(s) with the issue:
https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/dynamic_partition

### Raises listed and defined
No errors have been defined

### Submit a pull request?
Yes

**Comment by mohantym** [comment]
Hi @lkmandy , The above URL in template is working fine  . Could you please point out the exact issue in URL?

**Comment by lkmandy** [comment]
My point was  **tf.dynamic_partition**  doesn't have a **Raises section** like in the case of **tf.map_fn**  [https://bit.ly/3DZ0DCn](https://bit.ly/3DZ0DCn)

There is no section describing possible errors that may occur while using tf.dynamic_partition.

**Comment by mohantym** [comment]
Hi @Saduf2019 ,Could you please look into this issue!

**Comment by sushreebarsa** [comment]
@lkmandy It raises InvalidArgumentError in the following cases:
1. If partitions are not in range [0, num_partiions)
2.  If partitions.shape does not match the prefix of the data.shape argument.
Please have a look at [this](https://www.tensorflow.org/api_docs/python/tf/dynamic_partition) page for more information. Thank you!

**Comment by sushreebarsa** [comment]
@lkmandy Thank you for the quick response! 
Could you please move this issue to closed status as it is fixed?
Thank you!
