### ISSUE TITLE
[TF 2.0 API Docs] tf.data.experimental.rejection_resample

### ISSUE THREAD

**Issue by lkmandy** [tensorflow/tensorflow#29850]
## System  Information
Tensorflow version: 2.0

## URL(s) with the issue:
https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/data/experimental/rejection_resample

## Description of issue (what needs changing):
No recommendations of when and when not to use this symbol have been provided.
The description is not clear, it needs more content

### Raises listed and defined
No raises listed

### Usage example
No usage example has been provided

### Request visuals, if applicable
No visuals, but they will be very useful if present

### Submit a pull request? 
No

**Comment by rthadur** [comment]
This function has been deprecated in latest version , closing this issue. Thank you
