### ISSUE TITLE
[TF 2.0 API Docs] tf.data.experimental.unbatch

### ISSUE THREAD

**Issue by lkmandy** [tensorflow/tensorflow#29851]
## System information
Tensorflow version: 2.0

## URL(s) with the issue:
https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/data/experimental/unbatch

## Description of issue (what needs changing):
The description needs more content, as no description has been provided for the available functions.
No recommendations have been given on when and when not to use this symbol

### Parameters defined
No parameters have been defined

### Raises listed and defined
No errors defined

### Request visuals, if applicable
No visuals, the content will be clarified if visuals are provided

### Others
This symbol is deprecated, am not sure if this review will  still be useful

### Submit a pull request?
No

**Comment by ymodak** [comment]
`tf.data.experimental.unbatch` is deprecated and recommend to use `tf.data.Dataset.unbatch()` instead.
The docs are updated with [`tf.data.Dataset.unbatch()`](https://www.tensorflow.org/api_docs/python/tf/data/Dataset#unbatch)
