### ISSUE TITLE
Typo in Tensorflow Core 2.0b's Advanced Tutorial=>Loading data=>Building an image input pipeline

### ISSUE THREAD

**Issue by priancho** [tensorflow/tensorflow#29868]
## URL(s) with the issue:
https://www.tensorflow.org/beta/tutorials/load_data/images#load_and_format_the_images

## Description of issue (what needs changing):
Under "Load and format the images" section, the original code below fails to run since it uses a variable `img_path`, which should be `image_path` instead.

```python
import matplotlib.pyplot as plt

image_path = all_image_paths[0]
label = all_image_labels[0]

plt.imshow(load_and_preprocess_image(img_path))
plt.grid(False)
plt.xlabel(caption_image(img_path))
plt.title(label_names[label].title())
print()
```

### Clear description
This is a simple typo and needs to be fixed.

### Correct links
Not related.

### Parameters defined
Not related.

### Returns defined
Not related.

### Raises listed and defined
Not related.

### Usage example
Not related.

### Request visuals, if applicable
Not related.

### Submit a pull request?
Not this time.

**Comment by ymodak** [comment]
I was able to execute the colab successfully. I see that ```img_path``` is defined under "load_and_format_the_images "
https://www.tensorflow.org/beta/tutorials/load_data/images#load_and_format_the_images
Therefore the code should not break. Can you please confirm?

**Comment by svobora** [comment]
I believe it should be the other way around, rename `image_path` to `img_path`. 

@ymodak You did not notice that `image_path `is unused did you? Obviously the example works.

**Comment by priancho** [comment]
@ymodak As you mentioned it works, because `img_path` is defined in the beginning of sub-section `Load and format the images`.
If the use of `img_path` is intended, I think that `image_path` should be removed as @svobora said :-)

**Comment by yashk2810** [comment]
This is being fixed here (https://github.com/tensorflow/docs/pull/699#discussion_r295488663)

**Comment by ymodak** [comment]
Closing this issue since the associated PR has been merged. Thanks!
