### ISSUE TITLE
ImportError: libcudart.so.7.5: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by ShuaiW** [tensorflow/tensorflow#2986]
- GPU: GTX 1080
- GPU driver: 367.27
- OS: Ubuntu 16.04
- CUDA: 8.0 rc
- cudnn: 8.0

When I` import tensorflow `I got the error in the header. Looks like tensorflow doesn't support one (or more) or those?

**Comment by vrv** [comment]
You have to install from sources right now to use any library that's still in release candidate mode.

**Comment by talpay** [comment]
Try `sudo ldconfig /usr/local/cuda/lib64`

**Comment by AFAgarap** [comment]
It says `sbin/ldconfig.real: /usr/local/cuda/lib64/libcudnn.so.5 is not a symbolic link`

**Comment by xinqiu** [comment]
There is a easy way.
```
cd /usr/local/cuda/lib64/
cp libcudnn.so.8.0.5 libcudnn.so.5
```
