### ISSUE TITLE
[TF 2.0] Converting keras model to estimator ignores data-types

### ISSUE THREAD

**Issue by pekaalto** [tensorflow/tensorflow#29862]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): 
ProductName:	Mac OS X
ProductVersion:	10.14.2
BuildVersion:	18C54
- TensorFlow installed from (source or binary): pip install ...
- TensorFlow version (use command below): v1.12.1-3259-gf59745a381 2.0.0-beta0
- Python version: 3.6.8

**Describe the current behavior**
When converting Keras model to estimator it converts all integer inputs to floats or doubles.
This will result in data-type errors in the converted estimator.  

I am not entirely sure if this is a bug or "feature" because this function is indeed called in the conversion: https://github.com/tensorflow/estimator/blob/c956dd32561bac645a1cd870d3c8cfe8e9fe969b/tensorflow_estimator/python/estimator/keras.py#L62

However, this is blocking using integer-inputs in the converted estimator.

**Describe the expected behavior**
Input-data-types are preserved when converting keras-model to estimator.

**Code to reproduce the issue**
Small example to reproduce the issue:

```
import numpy as np
import tensorflow as tf
from tensorflow.python.keras import layers
from tensorflow.python.keras.estimator import model_to_estimator_v2

x_shape = (3,)
n_class = 5
batch_size = 10

x = layers.Input(shape=x_shape, name="x", dtype=tf.int64)

class StupidLayer(layers.Layer):
    def build(self, input_shape):
        self.y = tf.random.poisson(
            lam=10, shape=(batch_size,) + x_shape, dtype=tf.int64
        )
        super().build(input_shape)

    def call(self, inputs, **kwargs):
        return tf.cast(inputs * self.y, tf.float32)

y = StupidLayer()(x)

model = tf.keras.Model(inputs=x, outputs=y)

X = np.random.randint(50, size=(batch_size,) + x_shape, dtype="int64")

model.compile(optimizer="sgd", loss="categorical_crossentropy")
model.predict(X)

tf_estimator = model_to_estimator_v2(keras_model=model)
next(tf_estimator.predict(lambda: X))
```

Because input is converted to float, last line results in 
```
TypeError: Input 'y' of 'Mul' Op has type int64 that does not match type float32 of argument 'x'.
```

**Comment by achandraa** [comment]
Have tried on Colab with TF 2.0beta and was able to get mentioned error.

**Comment by karmel** [comment]
Triage notes: we have a fix for this going in right now. @tanzhenyu will update when it's in the nightlies.

**Comment by tanzhenyu** [comment]
This works in tf-nightly-2.0-preview since the fix was submitted yesterday.
