### ISSUE TITLE
TFRecord guide doesn't show how to serialize and parse tensors

### ISSUE THREAD

**Issue by bionicles** [tensorflow/tensorflow#29877]
## URL(s) with the issue:

Please provide a link to the documentation entry, for example:
https://www.tensorflow.org/beta/tutorials/load_data/tf_records#creating_a_tfexample_message
https://www.tensorflow.org/tutorials/load_data/tf_records

## Description of issue (what needs changing):
the TFRecord docs don't show how to serialize and parse tensors to a TFRecord. It's a minimal example with a bunch of strings, integers, and floats. How do you include tensor features in a tf.train.Example ?

The whole tf.train / tf.io / tf.data thing feels scattered and full of unnecessary boilerplate. Why are Examples Features, Feature in train, but then then we have to write a bunch of boilerplate tf.io functions like **_float_value _byte_value** to make the actual features? All I want to do is make a TFRecord with a bunch of tensors of different shapes in each entry. 

### Clear description

All of this stuff should be simplified and put into tf.data... Tf.io feels pointless since tf.data is meant to do the same thing. 

Why can't the tensorflow guide to TFRecord tell us how to write tensor data to a TFRecord and read it with TFData? 

Why do we need to write so much boilerplate to add features to tf.train.Example?

Why is Data IO spread out over four separate modules (train, io, dtypes, and data) ?

**Comment by novog** [comment]
You could add `FeatureColumn`s to this list. They can be used as a part of the input data flow to perform some common transformations (although as far as I can tell, only `Estimator`s can currently consume them, which is a shame).

**Comment by bionicles** [comment]
It's really hard to know the difference between all these different functions...

FixedLenSequenceFeature, VarLenFeature,
parse_example, parse_single_example, parse_single_sequence_example ? 

Extremely frustrating to implement what ought to be simple, get data, write data, read data

**Comment by bionicles** [comment]
https://www.tensorflow.org/versions/r1.14/api_docs/python/tf/train/Example

Zero information.

**Comment by novog** [comment]
To be fair, the 2.0 beta version of the documentation has a bit more info.

https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/train/Example
https://www.tensorflow.org/beta/tutorials/load_data/tf_records

The point stands that a guide on how all of these these various systems most easily interface with each other would be quite useful.

**Comment by bionicles** [comment]
Sounds like feature creep

**Comment by MikeOfZen** [comment]
more of a general complaint, the entire TF records API needs a user-friendly overhaul.
it's a simple operation, write data, read data.
Tensors are well aware of their shapes and datatypes.
Python strings are strings and Python numbers are numbers. I dont understand why I need a page long boilerplate (from the guide) to describe each element 4! times.

if python pickle can handle arbitrary python objects and python JSON can handle arbitrarily nested data in one line, TF should be able to handle its own objects and other primitives without so much fuss.

**Comment by chrishmorris** [comment]
This documentation helps a lot: https://medium.com/mostly-ai/tensorflow-records-what-they-are-and-how-to-use-them-c46bc4bbb564. It could usefully be used as the basis for a tutorial on the official TF site.

**Comment by MarkDaoust** [comment]
@MikeOfZen, IIUC [tf.data.Snapshot](https://github.com/tensorflow/community/pull/193) will be the fix you're looking for.

Right @jsimsa?

But yes, it looks like we could use a section on `tf.io.parse_tensor` and `tf.io.serialize_tensor` either way.

**Comment by jsimsa** [comment]
@MarkDaoust I don't think that [tf.data.Snapshot](https://github.com/tensorflow/community/pull/193) will provide what is @MikeOfZen asking for. IIUC, he would like to have a simple API to "save" and "load" arbitrary structure of tensors. 

@MikeOfZen a challenge that Python pickling does not need to solve but TensorFlow ser/de does is how to statically infer shapes and types so that a traced Python function can be executed as a dataflow computation. A simple "load(file)" operation does not provide any information into what the shape and type of the data stored in the file is which is needed to be known statically (i.e. reading from a file is not good enough) at the time a Python function with this operation is traced. So even if we had "save" and "load" as primitives, the "load" primitive would still likely need to specify a structure of `tf.TypeSpec`s that describe the shape and type of the loaded data for the sake of static shape inference.

The building blocks of "snapshot" could be used for implementing "save" and "load" which is something I can imagine doing as a follow up to "snapshot" and will take it into consideration in tf.data 2020 plans.

**Comment by MikeOfZen** [comment]
@jsimsa  thank you for your response. Yes, you understood it correctly.
I appericiate the diffcutly of integrating this dynamic into the graph tracing. 

I wouldn't mind indicating the tensor types&shapes before a 'load' operation.
or even having a seperate 'descriptor' file (though it can also be a header in a regular data file)
for the static graph building.

right now, this information has to be coded anyway into the ser/deser code.
to illustrate. a simple code to serialize an example (with a single tensor) for a TF records file is something like this:
```
def bytes_feature(value):
    return tf.train.Feature(bytes_list=tf.train.BytesList(value=[value]))

def encode_example(mask):
    mask = tf.constant(mask)
    mask = tf.io.serialize_tensor(mask).numpy()

    feature = {
           'mask'     : bytes_feature(mask),
            }
    example_proto = tf.train.Example(features=tf.train.Features(feature=feature))
    return example_proto.SerializeToString()
```
This is quite convuluted and verbose. and the shape and type are not mentioned here (the type is used in the deserialization as you said) 

Even if the functionality remains as it is, a friendliar API that hides this could be a decent solution.

But Anyway, it's great that this is on your mind!

**Comment by vman049** [comment]
I second @MikeOfZen. The TensorFlow documentation, at least for this functionality, needs a significant revamp and needs to be much more user-friendly. I have wasted three hours on something that should have taken 30 seconds and still don't have an answer.

**Comment by vicpara** [comment]
Just finished digging into the darkest corners of `tensorflow` and `tensorflow/datasets` to get me a workable solutions. Everything seems duct taped and half baked. It's so bad that the guys from `tensorflow/datasets` almost built everything again around the protobuf serialization so you don't have to be worries.

What I don't really understand is why can't all the magic happen automatically. The tensors as they stand today, without any other funky new object have everything we need to put them on disk. Unless they do want to go bespoke (which most of us don't) we should get zero exposure to protobuf API. The TF backend should be able to do it automatically. Tensors in, tensors out.

As most of us are currently doing it 
`tensor`-> `numpy`->`bytes`->`string`->`protobuf`-> `bytes_on_disk` -> `protobuf` -> `funky representation on graph few on this planet understand` -> `string/bytes/weird tensorflow backend artifacts` -> tensors of bytestrings I need to call `.numpy()` on -> numpy objects -> finally my tensor.

Ok. I managed to get a solution working using only the Protobuf api available in tensorflow. This approach avoid serializing numpy data to bytes and passing the raw bytes to the TFRecord. This approach forces the use of a special py_function that cannot be serialized and moved on the graph when sending data to the TPU or in a distributed environment. 

The code is available at https://gist.github.com/vicpara/5c23c78d0f3105af53798272e628d2ad . Hope it helps more keep sane while dealing with this API.

As the map function that does the tensor manipulation of the feature dictionary produced by the `TFRecordDataset` is not required anymore, the above approach also avoids the additional `set_shape` operation outside the `@py_function` scope in an additional map operation.

**Comment by joannayoo0117** [comment]
Are there any updates on this? I'm using TPU which make things more complicated. 
Ideally, I want to run operations in TPU, return as tensor which is still on TPU, directly access the gs bucket and write the result as TFRecord. 
All the options I found require the tensor to be transformed to something else (i.e. bytes, numpy, float etc etc), which TPU is not too happy about. 
It would be really great to have a function that just writes tensor to tf record.

**Comment by MattdaVill** [comment]
Hello everyone, I am having some troubles trying to import data into a TFX pipeline, if anyone can point me in the right direction I'd really appreciate it. I have a 3D Ragged (or Sparse if need be) Tensor, where each 2D slice is an example which I'd like to feed into my pipeline. Each 2D tensor is composed of a variable number or rows, but they collectively form one example, not just a batch of examples. What is the best way to encode this structure, so that the ExampleGen component of the tfx pipeline can feed it into the pipeline?
So far I have tried the instructions in this guide https://medium.com/mostly-ai/tensorflow-records-what-they-are-and-how-to-use-them-c46bc4bbb564 to turn it in a tf.train.SequenceExample, so that each feature has a vector inside the value field, and written the result to a tf.Record. For some reason I am really struggling to unpack it though.

Any help would be really appreciated!

Matt

Ps: Please note that the 3rd dim of the tensor is pretty long, say 40k, so writing each example into a tf.Record would generate an equal number of files, which in my opinion impractical, inefficient and not very elegant, but I'm happy to be wrong.

**Comment by fredo838** [comment]
there's now `tf.data.experimental.save(tf_dataset, path)`, which is what we're all been waiting for I think. You don't need to `tf.io.serialize` the dataset yourself anymore. The current version (at time of writing), still requires you to know the `output_signature` of the `tf.data.Dataset` you're trying to load, but that's no longer needed in the `nightly` build. 
current:
https://www.tensorflow.org/api_docs/python/tf/data/experimental/save
nightly:
https://www.tensorflow.org/api_docs/python/tf/data/experimental/save?version=nightly

```
>>> def gen():
...   for i in range(10):
...     yield i,i
... 
>>> ds = tf.data.Dataset.from_generator(gen, output_signature=(tf.TensorSpec(dtype=tf.int32,shape=()),tf.TensorSpec(dtype=tf.int32,shape=())))
>>> tf.data.experimental.save(ds, "test.tfrecord")
>>> loaded_ds = tf.data.experimental.load("test.tfrecord") # this should work in the `nightly`
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: load() missing 1 required positional argument: 'element_spec'
>>> loaded_ds = tf.data.experimental.load("test.tfrecord", element_spec=(tf.TensorSpec(dtype=tf.int32,shape=()),tf.TensorSpec(dtype=tf.int32,shape=())))
>>> for i in loaded_ds:
...   print(i)
... 
(<tf.Tensor: shape=(), dtype=int32, numpy=0>, <tf.Tensor: shape=(), dtype=int32, numpy=0>)
(<tf.Tensor: shape=(), dtype=int32, numpy=1>, <tf.Tensor: shape=(), dtype=int32, numpy=1>)
(<tf.Tensor: shape=(), dtype=int32, numpy=2>, <tf.Tensor: shape=(), dtype=int32, numpy=2>)
(<tf.Tensor: shape=(), dtype=int32, numpy=3>, <tf.Tensor: shape=(), dtype=int32, numpy=3>)
(<tf.Tensor: shape=(), dtype=int32, numpy=4>, <tf.Tensor: shape=(), dtype=int32, numpy=4>)
(<tf.Tensor: shape=(), dtype=int32, numpy=5>, <tf.Tensor: shape=(), dtype=int32, numpy=5>)
(<tf.Tensor: shape=(), dtype=int32, numpy=6>, <tf.Tensor: shape=(), dtype=int32, numpy=6>)
(<tf.Tensor: shape=(), dtype=int32, numpy=7>, <tf.Tensor: shape=(), dtype=int32, numpy=7>)
(<tf.Tensor: shape=(), dtype=int32, numpy=8>, <tf.Tensor: shape=(), dtype=int32, numpy=8>)
(<tf.Tensor: shape=(), dtype=int32, numpy=9>, <tf.Tensor: shape=(), dtype=int32, numpy=9>)
```

**Comment by SuryanarayanaY** [comment]
Hi @bionicles ,

Iam not sure of the old documentation example at the time of this issue.There has been continuous updation in documentation with each version and I believe this document [link](https://www.tensorflow.org/tutorials/load_data/tfrecord) might be what you expecting. Could you please check and confirm whether your requirement is fulfilled now?

Thankyou!

**Comment by vicpara** [comment]
> Hi @bionicles ,
> 
> Iam not sure of the old documentation example at the time of this issue.There has been continuous updation in documentation with each version and I believe this document [link](https://www.tensorflow.org/tutorials/load_data/tfrecord) might be what you expecting. Could you please check and confirm whether your requirement is fulfilled now?
> 
> Thankyou!

100 years later nobody cares about it. If you give it a few more years maybe the OP will retire. 
Classic Google support and appreciation.
