### ISSUE TITLE
Use Tensorflow like Numpy, disable gradients entirely

### ISSUE THREAD

**Issue by sleighsoft** [tensorflow/tensorflow#29870]
I thought about using tensorflow for occasions where I have used numpy so far.

Most of the time gradients take up the most memory when doing "NN" things with tensorflow.  I was wondering if Tensorflow (v 2.0) always collects gradients in the background, even when I don't  use them.

And if that is the case, if there is a way to disable gradients entirely in order to conserve memory.

Does Tensorflow v2 only compute/store intermediate gradients when using operations inside `tf.GradientTape`? Or does tf.GradientTape just "record" or "map" to them?

I didn't think this is a Stackoverflow issue, as if this is indeed the case it might be a feature request.

**Comment by allenlavoie** [comment]
GradientTape holds its own reference to intermediate activations, a regular Python refcount increment. Without a tape we don't reference any activations (but they may be referenced somewhere in your code, e.g. in a Python variable). So you're good already; just don't use a tape and memory will be fine.

GradientTape also doesn't do any computation until `.gradient` is called, it just saves a record of operations and input and output Tensors. TF doesn't do any gradient computation without a tape active.

**Comment by sleighsoft** [comment]
Thank you for your answer @allenlavoie. This would be nice to see in the GradientTape documentation.

**Comment by lostmsu** [comment]
@allenlavoie is this applicable to 1.15? When I am building a graph, does the tape come in as a part of optimizer?

**Comment by allenlavoie** [comment]
Yes, optimizers will compute gradients (either `tf.gradients` or `tf.GradientTape` depending on v1/v2). Using a gradient-based optimizer (or `GradientTape`/`gradients` manually) will change the structure of the graph to increase memory usage in the same way it happens executing eagerly.
