### ISSUE TITLE
SequenceFeatures layer requires a SparseTensor... only to convert it to a regular Tensor

### ISSUE THREAD

**Issue by durandg12** [tensorflow/tensorflow#29879]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): no
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): macOS 10.13.6
- TensorFlow installed from (source or binary): from pip install
- TensorFlow version (use command below): v1.12.1-3259-gf59745a381 2.0.0-beta0
- Python version: v3.6.7:6ec5cf24b7, Oct 20 2018, 03:02:14

**Describe the current behavior**

When I call a `SequenceFeatures` layer on a dense tensor, like a tensor produced with numpy, a `TypeError` is raised because `SequenceFeatures` `call` method expects a `SparseTensor` as input. When looking at the log it appears that the function producing the `TypeError` is `sparse_tensor_to_dense`. So, `SequenceFeatures` does expect a `SparseTensor`, only to convert it to a dense `Tensor`, and fails if given a `Tensor` that is already dense.

**Describe the expected behavior**

I think `SequenceFeatures` `call` should accepts dense `Tensor` objects and just don't try to convert them from sparse to dense.

**Code to reproduce the issue**

```
import numpy as np
import tensorflow as tf
from tensorflow.feature_column import sequence_numeric_column
from tensorflow.keras.experimental import SequenceFeatures

#print(tf.version.GIT_VERSION, tf.version.VERSION)

seq_fc = sequence_numeric_column('feature1')
seq_layer = SequenceFeatures(seq_fc)

batch_size, sequence_length = 3, 5
raw_data = np.array(range(batch_size * sequence_length), dtype=np.float32)
data = np.reshape(raw_data, (batch_size, sequence_length))

dict_data = {'feature1': data}
seq_layer(dict_data)
```
This produces the following error log:

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-5-aa46f578fa6e> in <module>
      1 dict_data = {'feature1': data}
----> 2 seq_layer(dict_data)

~/Documents/tf2beta/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer.py in __call__(self, inputs, *args, **kwargs)
    710           with base_layer_utils.autocast_context_manager(
    711               input_list, self._mixed_precision_policy.should_cast_variables):
--> 712             outputs = self.call(inputs, *args, **kwargs)
    713           self._handle_activity_regularization(inputs, outputs)
    714           self._set_mask_metadata(inputs, outputs, input_masks)

~/Documents/tf2beta/lib/python3.6/site-packages/tensorflow/python/feature_column/sequence_feature_column.py in call(self, features)
    138       with ops.name_scope(column.name):
    139         dense_tensor, sequence_length = column.get_sequence_dense_tensor(
--> 140             transformation_cache, self._state_manager)
    141         # Flattens the final dimension to produce a 3D Tensor.
    142         output_tensors.append(self._process_dense_tensor(column, dense_tensor))

~/Documents/tf2beta/lib/python3.6/site-packages/tensorflow/python/feature_column/sequence_feature_column.py in get_sequence_dense_tensor(self, transformation_cache, state_manager)
    553     sp_tensor = transformation_cache.get(self, state_manager)
    554     dense_tensor = sparse_ops.sparse_tensor_to_dense(
--> 555         sp_tensor, default_value=self.default_value)
    556     # Reshape into [batch_size, T, variable_shape].
    557     dense_shape = array_ops.concat(

~/Documents/tf2beta/lib/python3.6/site-packages/tensorflow/python/ops/sparse_ops.py in sparse_tensor_to_dense(sp_input, default_value, validate_indices, name)
   1447     TypeError: If `sp_input` is not a `SparseTensor`.
   1448   """
-> 1449   sp_input = _convert_to_sparse_tensor(sp_input)
   1450 
   1451   return gen_sparse_ops.sparse_to_dense(

~/Documents/tf2beta/lib/python3.6/site-packages/tensorflow/python/ops/sparse_ops.py in _convert_to_sparse_tensor(sp_input)
     66     return sparse_tensor.SparseTensor.from_value(sp_input)
     67   if not isinstance(sp_input, sparse_tensor.SparseTensor):
---> 68     raise TypeError("Input must be a SparseTensor.")
     69   return sp_input
     70 

TypeError: Input must be a SparseTensor.
```

**Workaround**

Converting the input to sparse before calling `SequenceFeatures` does make the code work:

```
import numpy as np
import tensorflow as tf
from tensorflow.feature_column import sequence_numeric_column
from tensorflow.keras.experimental import SequenceFeatures

#print(tf.version.GIT_VERSION, tf.version.VERSION)

seq_fc = sequence_numeric_column('feature1')
seq_layer = SequenceFeatures(seq_fc)

batch_size, sequence_length = 3, 5
raw_data = np.array(range(batch_size * sequence_length), dtype=np.float32)
data = np.reshape(raw_data, (batch_size, sequence_length))

#####
# convert the input tensor in a sparse tensor
zero = tf.constant(0, dtype=tf.float32)
where = tf.not_equal(data, zero)
indices = tf.where(where)
values = tf.gather_nd(data, indices)
sparse = tf.SparseTensor(indices, values, data.shape)
dict_data_but_sparse = {'feature1': sparse}
#####

seq_layer(dict_data_but_sparse)
```

correctly outputs the following:

```
(<tf.Tensor: id=367, shape=(3, 5, 1), dtype=float32, numpy=
 array([[[ 0.],
         [ 1.],
         [ 2.],
         [ 3.],
         [ 4.]],
 
        [[ 5.],
         [ 6.],
         [ 7.],
         [ 8.],
         [ 9.]],
 
        [[10.],
         [11.],
         [12.],
         [13.],
         [14.]]], dtype=float32)>,
 <tf.Tensor: id=355, shape=(3,), dtype=int64, numpy=array([5, 5, 5])>)
```

**Comment by ravikyram** [comment]
I have tried  on colab with TF version 2.0 beta and was able to reproduce the issue.

**Comment by martinwicke** [comment]
I looked at this a little but and this particular conversion is indeed simply to eliminate. I am not at all sure we're not requiring sparsity elsewhere in the sequence feature columns though. @rohan100jain would know better.

**Comment by durandg12** [comment]
The issue is still here in tf2.0.0 and it keeps needing to add unnecessary operations in my models. I use the new `tf.sparse_to_dense` as a workaround now butin the end it is almost the same as before.

**Comment by mmilosav** [comment]
@rohan100jain Any update on this?  The issue persists in 2.2.0-dev20200306.  Many thanks.

**Comment by tanzhenyu** [comment]
This could probably be fixed by not converting a dense tensor, and also needs to update how to get sequence_length from a dense tensor (tf.shape(input_tensor)[1])

**Comment by jtromans** [comment]
Not a fix but to avoid some code, you may with to use the `dense_to_sparse` from `tensorflow_probability` math library, which ultimately achieves the same thing as the work around suggested by @durandg12. 

```
import tensorflow_probability as tfp
_sparse = tfp.math.dense_to_sparse(data) 
print(_sparse)
```

**Comment by Saduf2019** [comment]
I am able to replicate the issue on tf-nightly(2.4.0-dev20200809), please find the [gist here](https://colab.research.google.com/gist/Saduf2019/57ce89aa46458594e15178ab4c10349f/untitled345.ipynb).

**Comment by tanzhenyu** [comment]
We'd encourage you to try [Keras Preprocessing Layers](https://github.com/tensorflow/community/blob/master/rfcs/20191212-keras-categorical-inputs.md#workflow-1----official-guide-on-how-to-replace-feature-columns-with-kpl). Feel free to re-open this issue if this doesn't work.
We will try to deprecated SequenceFeatures (given it's experimental and it literally doesn't work well with Keras)
