### ISSUE TITLE
I think Windows performance might be poor due to WDDM? tensorflow-gpu

### ISSUE THREAD

**Issue by rlewkowicz** [tensorflow/tensorflow#29874]
So personally I have very poor performance on windows when it comes to object detection. Doesn't matter if I build from source, pip, conda etc, it's about 5-10x slower on windows vs linux. 

I see sporadic reports across tensorflow and pytorch stating similar things. Some bugs confirmed, but with no follow up. 

I'm hoping someone on this project has access to a non consumer nvidia card. I think that's the titan series. None of the geforce cards will work (thanks nvidia). I ask you to do any of the object detection api tutorials, or even any custom implementation.  Test it on linux, then the same on windows. 

I'm hyper confident you will find a significant discrepancy between the two. Then enable TCC on your non consumer card, and see if the performance then becomes similar. 

I'm basing my assumption on this:
https://stackoverflow.com/questions/19944429/cuda-performance-penalty-when-running-in-windows

**Comment by achandraa** [comment]
Thanks for reaching out to us. Please let us know which TensorFlow GPU version you are using.

**Comment by rlewkowicz** [comment]
@achandraa recently I'm using 2.0 beta gpu. From pip and from source.

I think I also had issues with 1.13 though. I'll spend some time verifying tonight when I get home.

**Comment by jvishnuvardhan** [comment]
@rlewkowicz Is this still an issue? Can you check with `TF2.0` and let us know whether the issue persists with latest TF version. Thanks!

**Comment by rlewkowicz** [comment]
@jvishnuvardhan I'm having trouble with the 2.0 release due to https://github.com/tensorflow/tensorflow/issues/31509. I'm debating how much time I want to spend on it. Are you asking me because you know of a specific change that might have fixed the issue, or are you just seeing if it worked itself out?

**Comment by jvishnuvardhan** [comment]
@rlewkowicz There were lots of improvements between `2.0beta` to `2.0`. I am thinking your issue might have been resolved. If possible, Check `tf-nightly` also. Thanks!

**Comment by KellyHwong** [comment]
I'm running a ResNet56v2 model training experiment, each epoch has 1600 image samples with 224*244 pixels. It is interesting that when I trained it on Windows 10, it took 15 hours per epoch! While the time is only 10 hour on macOS. 1.5x time!
My environment is, conda python 3.7 on Windows and homebrew python 3.7 on macOS, tf 2.1 for both system.
My mac is 2015 MBPR with Intel i7 4770HQ.

**Comment by rlewkowicz** [comment]
Just as a heads up, I had done some basic tests, unfortunately it's not been resolved. Ultimately I'm hyper confident that it's WDDM vs TCC. It's just unfortunate my 1400 dollar graphics card doesn't support TCC because nvidia chooses to gate their hardware.

**Comment by sushreebarsa** [comment]
@rlewkowicz  It looks like you are using an older Version of Tensorflow 2.0. Many bugs have been fixed in the latest version. Can you please execute your code using Latest stable Version(2.5) and let us know if the issue still persists? Thanks!

**Comment by rlewkowicz** [comment]
> @rlewkowicz It looks like you are using an older Version of Tensorflow. Many bugs have been fixed in the latest version. Can you please execute your code using Latest stable Version(2.5) and let us know if the issue still persists? Thanks!

Unfortunately I'm deep into some other projects right now and wont have the time to get this environment off the ground. Ultimately, I'm not confident that anything short of a major architectural shift is going to help. When the OS eats a bunch of space on your GPU out of the gate, you know it's not good. It's hands are in the pie before you can get a slice. 

Pick any implementation based on speed. Preferably something in the 60-100 fps range. Yolo v3 tiny for example. Run it on linux, run it on windows. Windows is going to be drastically slower.

**Comment by tilakrayal** [comment]
Is this still an issue?
Could you please update TensorFlow to the latest stable version v.2.7 and let us know if you are facing the same error. Thanks!
