### ISSUE TITLE
https://www.tensorflow.org/guide/using_tpu 2.0b

### ISSUE THREAD

**Issue by CrackerHax** [tensorflow/tensorflow#29885]
## URL(s) with the issue:
https://www.tensorflow.org/guide/using_tpu

## Description of issue (what needs changing):

Needs to be completely redone

### Clear description

Everything is wrong and examples do not work

**Comment by jvishnuvardhan** [comment]
@CrackerHax Thanks for the noticing issues in that page. Could you be little more clear in describing what do you mean by `completely redone` and could you point which examples donot work? Are you interested in raising a PR to update the page? Thanks!

**Comment by jvishnuvardhan** [comment]
[Here](https://github.com/tensorflow/docs/blob/master/site/en/guide/using_tpu.md) is the page if you are interested to update and raise a PR. Thanks!

**Comment by CrackerHax** [comment]
Try the example... literally nothing works. Error for everything. If I knew how to do this I wouldn't mind fixing it but the whole reason I am reading the documentation in the first place is that I don't know how to do this....

**Comment by jvishnuvardhan** [comment]
@CrackerHax Thanks! Yesterday I made some corrections and the PR https://github.com/tensorflow/docs/pull/710 raised was merged already. I agree this is one of the old content which need to be updated. More changes are in our pipeline. Please stay tuned. Thanks!

**Comment by jvishnuvardhan** [comment]
I am closing this for now as we have listed this in our pipeline and will be updating in the near future. But, if you or any one want to contribute then please raise PR's to correct. Thanks!
