### ISSUE TITLE
XLA builds with NCCL even when it is disabled

### ISSUE THREAD

**Issue by MattConley** [tensorflow/tensorflow#29886]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): Source
- TensorFlow version: 1.14/master
- Python version: 3.6
- Installed using virtualenv? pip? conda?: N/A
- Bazel version (if compiling from source): 0.24.1
- GCC/Compiler version (if compiling from source): Linaro 7.4.0
- CUDA/cuDNN version: 10.0
- GPU model and memory: Jetson Xavier

**Describe the problem**
Build fails when NCCL is disabled. XLA's build file builds NCCL with the `if_cuda` conditional (https://github.com/tensorflow/tensorflow/blob/v1.14.0-rc1/tensorflow/compiler/xla/service/gpu/BUILD#L359), but should be using `if_nccl` instead (https://github.com/tensorflow/tensorflow/blob/v1.14.0-rc1/tensorflow/core/kernels/BUILD#L210).

**Provide the exact sequence of commands / steps that you executed before running into the problem**
Trying to build TensorFlow with CUDA support but with NCCL disabled (--config=cuda and --config=nonccl bazel options) causes this issue.

**Comment by jlebar** [comment]
@jvishnuvardhan hey, I'm leaving the TensorFlow/XLA teams.  I've updated go/tf-who-do-i-notify to point to a different point of contact.  Ideally we'd have some sort of XLA group you could use instead, I don't know if that's possible to set up?

**Comment by sanjoy** [comment]
Hi Matt,

Thanks for the report.  Are you willing to make a PR to fix this?  Your suggestion to use `if_nccl` sounds quite reasonable, although you'll also have to update `NcclAllReduceThunk::NcclIsEnabled` to do the right thing.

**Comment by MattConley** [comment]
Sure, I'll link the PR here as soon as I submit it.

Thanks,
Matt Conley

**Comment by MattConley** [comment]
Submitted PR #30507 to address this issue

**Comment by MattConley** [comment]
Closing as @chsigg fixed in commit [9b9bea6](https://github.com/tensorflow/tensorflow/commit/9b9bea65159eea4c8452d7f8b702b32dcb3cea8e)
