### ISSUE TITLE
always_record_summaries in tf 2.0

### ISSUE THREAD

**Issue by Oktai15** [tensorflow/tensorflow#29883]
I can't find `tf.summary.always_record_summaries` or `do_always_record_summaries` in tensorflow 2.0. Where can I find it?

**Comment by Oktai15** [comment]
According to https://github.com/tensorflow/tensorflow/issues/26405, now I don't need `always_record_summaries` anymore, but I want to get the exact answer :)

**Comment by brunapinos** [comment]
Hi! 
It seems that if you want to set summary recording on or off, you can use the function  [`tf.summary.record_it()`](https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/summary/record_if), and defined in [`python/ops/summary_ops_v2.py`](https://github.com/tensorflow/tensorflow/blob/8e423e3d56390671f0d954c90f4fd163ab02a9c1/tensorflow/python/ops/summary_ops_v2.py#L102).
As it was said in #26405, the recording is on by default, so if want to turn it off, I think you should use the method above.
The `always_record_summaries` is still defined in [`python/ops/summary_ops_v2.py`](https://github.com/tensorflow/tensorflow/blob/8e423e3d56390671f0d954c90f4fd163ab02a9c1/tensorflow/python/ops/summary_ops_v2.py#L136) and simply return `record_if(True)`, but I was not able to use it.

**Comment by achandraa** [comment]
@Oktai15  : Have a look on @brunapinos's suggestion and let us know if that helps to resolve the issue. Thanks!

**Comment by Oktai15** [comment]
@achandraa yes, thank you
