### ISSUE TITLE
[TF 2.0 API Docs] tf.keras.backend.count_params

### ISSUE THREAD

**Issue by lkmandy** [tensorflow/tensorflow#29890]
## System Information
Tensorflow version 2.9

## URL(s) with the issue:
https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/keras/backend/count_params

### Clear description
The description is not clear, no details on how to use this symbol

### Raises listed and defined
No errors have been defined 

### Request visuals, if applicable
No visuals? an example using arrays could be represented in visual form for clarification

### Submit a pull request?
No

**Comment by rmothukuru** [comment]
@lkmandy,
[Example code](https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/keras/backend/count_params#example) is available, which demonstrates how to use this functionality. Can you please confirm if this is what you are looking for? Thanks!
