### ISSUE TITLE
Need example of mixed precision in eager execution mode

### ISSUE THREAD

**Issue by edwardyehuang** [tensorflow/tensorflow#29898]
https://www.tensorflow.org/versions/r1.14/api_docs/python/tf/train/experimental/enable_mixed_precision_graph_rewrite

https://www.tensorflow.org/versions/r1.14/api_docs/python/tf/train/experimental/MixedPrecisionLossScaleOptimizer

https://www.tensorflow.org/versions/r1.14/api_docs/python/tf/keras/mixed_precision/experimental/LossScaleOptimizer

I have tried all of them. None of them worked for me in eager mode. Could you provide some examples?

**Comment by achandraa** [comment]
Please have a look on #29241. PR for "enable_mixed_precision_graph_rewrite" is in queue. Thanks!

**Comment by edwardyehuang** [comment]
That one is for the Graph Mode. I have already worked in Graph Mode. I cannot work in Eager Execution Mode.

**Comment by edwardyehuang** [comment]
Sorry, my mistake.

The **tf.keras.Model.compile** and **tf.keras.Model.fit** is still able to use in Eager Execution Mode.

Close this issue now.
