### ISSUE TITLE
[TF 2.0 API Docs] tf.sets.difference

### ISSUE THREAD

**Issue by Rodriq** [tensorflow/tensorflow#29897]
## System Information

TensorFlow version: 2.0

## URL(s) with the issue:

https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/sets/difference

### Raises listed and defined

Raises not listed and defined.
Every method has a way that it can be mishandled, maybe when a wrong parameter or wrong order of parameters is/are passed in ( e.g, in this case, two sets `a` and `b` in which the last elements don't match) will raise an error.

### Request visuals, if applicable

No visuals

### Submit a pull request?

No

**Comment by yongtang** [comment]
Added a PR #29938 for the fix.
