### ISSUE TITLE
Import pre-trained model to MATLAB?

### ISSUE THREAD

**Issue by ifjesus** [tensorflow/tensorflow#2989]
Hi,

I am training my own CNN model using tensorflow.

I wonder if there is a way to import a (pre-)trained model (in tensorflow format, .ckpt) into MATLAB/Simulink or Caffe?

Thank you in advance.

**Comment by prb12** [comment]
This is a question better suited for StackOverflow. Please ask it there and tag it with the `tensorflow` tag.
