### ISSUE TITLE
inconsistent variable initialization behavior for callables / ops

### ISSUE THREAD

**Issue by dannygoldstein** [tensorflow/tensorflow#2990]
When a variable is initialized with a callable, running the initializer of the variable has no effect after it is run once:

```python
import tensorflow as tf
import scipy

session = tf.InteractiveSession()
retrand = lambda: scipy.random.random(size=[2,2])
var = tf.Variable(retrand, dtype=tf.float32)
session.run(var.initializer)
var.eval()
# prints array([[ 0.73060566,  0.26469722],
#               [ 0.63376802,  0.64898247]], dtype=float32)
session.run(var.initializer)
var.eval()
# prints array([[ 0.73060566,  0.26469722],
#              [ 0.63376802,  0.64898247]], dtype=float32)
# (same as first call)
```
If a variable is initialized with a tensorflow init op, then rerunning the initializer changes the variable state:

```python
var = tf.Variable(tf.random_normal([2,2]))
session.run(var.initializer)
var.eval()
#prints 
#array([[ 0.61732173,  0.14423341],
#       [ 0.3965871 , -0.98214936]], dtype=float32)
session.run(var.initializer)
var.eval()
# prints 
# array([[ 0.48240849,  0.26547143],
#      [ 1.18776596, -0.12901327]], dtype=float32)
```

Why do variables initialized with a callable only call the callable once, even if they are initialized repeatedly, when variables initialized with an init op rerun the op on each run of the initializer? Is there any way to have a variable initialized with a callable call it each time the variable's initializer is run?

### Environment info
Operating System:  Mac OSX
(please attach the output of `ls -l /path/to/cuda/lib/libcud*`): None
If installed from binary pip package, provide: 
1. Which pip package you installed.
https://storage.googleapis.com/tensorflow/mac/tensorflow-0.9.0rc0-py2-none-any.whl
2. The output from `python -c "import tensorflow; print(tensorflow.__version__)"`.
0.9.0rc0

**Comment by ibab** [comment]
> Is there any way to have a variable initialized with a callable call it each time the variable's initializer is run?

You can define the initializer as a `PyFunc` op.
Note that you need to manually specify the output shape of your op with `tensor.set_shape` before you can use it to initialize a variable.
```python
import tensorflow as tf
import numpy as np
import scipy

session = tf.InteractiveSession()

def get_random():
    return scipy.random.random(size=[2,2]).astype(np.float32)

init = tf.py_func(get_random, [], [tf.float32])[0]
init.set_shape((2, 2))
var = tf.Variable(init)
session.run(var.initializer)
print(var.eval())
#[[ 0.97525001  0.68293589]
# [ 0.59959763  0.14780547]]
session.run(var.initializer)
print(var.eval())
#[[ 0.7729072   0.84212685]
# [ 0.74777764  0.97365493]]
```

**Comment by dannygoldstein** [comment]
Thanks!

On Wed, Jun 22, 2016 at 3:47 PM, Igor Babuschkin <notifications@github.com>
wrote:

> Is there any way to have a variable initialized with a callable call it
> each time the variable's initializer is run?
>
> You can define the initializer as a PyFunc op.
> Note that you need to manually specify the output shape of your op with
> tensor.set_shape before you can use it to initialize a variable.
>
> import tensorflow as tfimport numpy as npimport scipy
>
> session = tf.InteractiveSession()
> def get_random():
>     return scipy.random.random(size=[2,2]).astype(np.float32)
>
> init = tf.py_func(get_random, [], [tf.float32])[0]
> init.set_shape((2, 2))
> var = tf.Variable(init)
> session.run(var.initializer)print(var.eval())#[[ 0.97525001  0.68293589]# [ 0.59959763  0.14780547]]
> session.run(var.initializer)print(var.eval())#[[ 0.7729072   0.84212685]# [ 0.74777764  0.97365493]]
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/tensorflow/tensorflow/issues/2990#issuecomment-227900152>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ACpC4M2MCb7ZvaD_jlqiYIAfJvEdvdhyks5qObuSgaJpZM4I7bnS>
> .
>



-- 
Danny Goldstein
http://astro.berkeley.edu/~dgold/
