### ISSUE TITLE
why are there so many  function as parameter that passed into in python code ?

### ISSUE THREAD

**Issue by timcredy** [tensorflow/tensorflow#29906]
why are there so many  functions as parameter that be passed into another function in Python code ?
It's hard to understand it !

**Comment by ziyigogogo** [comment]
Child education is not hard, so go back to the kindergarten please.

**Comment by ravikyram** [comment]
Can you please elaborate on your query.Thanks!

**Comment by mihaimaruseac** [comment]
Closing as there is a lack of response and the question seems more fitted for StackOverflow.
