### ISSUE TITLE
"Node 'Const' is not unique" Using C++ api on windows to freeze graph

### ISSUE THREAD

**Issue by linyuhui** [tensorflow/tensorflow#29907]
I use *FreezeSavedModel* fucntion in source code https://github.com/tensorflow/tensorflow/blob/v1.12.0/tensorflow/cc/tools/freeze_saved_model.cc to freeze graph, and use tensorflow::WriteBinaryProto to export pb file. it report an error: "Node 'Const' is not unique". Then I check code in *FreezeSavedModel* fucntion, I find out in function *ConvertVariableToConstant*(https://github.com/tensorflow/tensorflow/blob/v1.12.0/tensorflow/cc/tools/freeze_saved_model.cc#L149),   after running 
```
 const_node->set_op("Const");
```
the op and name and device of const_node all are set to "Const". And I check the address of member op_, name_, device_ of const_node, they are all the same.

Similarly, if you run`const_node->set_name(variable_node.name());` , the op and name and device of const_node all are set to name of this variable_node.

**System information**
- Windows 10
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below): v1.12.0
- Bazel version (if compiling from source): bazel 0.15
- CUDA/cuDNN version: 10/7
- GPU: 1050ti

I use vs2015 update3 to compile tensorflow and add some msvc symbols manually.

**Comment by achandraa** [comment]
In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thanks!

**Comment by linyuhui** [comment]
```	
tensorflow::SavedModelBundle saved_model_bundle;
tensorflow::MetaGraphDef *meta_graph_def = &(&saved_model_bundle)->meta_graph_def;
*meta_graph_def->mutable_graph_def() = graph_def;
saved_model_bundle.session->Create(graph_def);
saved_model_bundle.session->Run({ { "save/Const", t } }, {}, { "save/restore_all" }, nullptr);
tensorflow::GraphDef frozen_graph_def;
std::unordered_set<string> inputs;
std::unordered_set<string> outputs;
TF_CHECK_OK(FreezeSavedModel(saved_model_bundle, &frozen_graph_def,
		&inputs, &outputs));
```
the definition of FreezeSavedModel is in https://github.com/tensorflow/tensorflow/blob/v1.12.0/tensorflow/cc/tools/freeze_saved_model.cc

**Comment by minjac** [comment]
> 
> 
> ```
> tensorflow::SavedModelBundle saved_model_bundle;
> tensorflow::MetaGraphDef *meta_graph_def = &(&saved_model_bundle)->meta_graph_def;
> *meta_graph_def->mutable_graph_def() = graph_def;
> saved_model_bundle.session->Create(graph_def);
> saved_model_bundle.session->Run({ { "save/Const", t } }, {}, { "save/restore_all" }, nullptr);
> tensorflow::GraphDef frozen_graph_def;
> std::unordered_set<string> inputs;
> std::unordered_set<string> outputs;
> TF_CHECK_OK(FreezeSavedModel(saved_model_bundle, &frozen_graph_def,
> 		&inputs, &outputs));
> ```
> 
> the definition of FreezeSavedModel is in https://github.com/tensorflow/tensorflow/blob/v1.12.0/tensorflow/cc/tools/freeze_saved_model.cc

Hey, try to edit your freeze_saved_model.cc.
before:
void ConvertVariableToConstant(const NodeDef& variable_node,
                               const Tensor& variable_value,
                               NodeDef* const_node) {
  const_node->set_name(variable_node.name());
  const_node->set_op("Const");
  (*const_node->mutable_attr())["dtype"] = variable_node.attr().at("dtype");
  variable_value.AsProtoTensorContent(
      (*const_node->mutable_attr())["value"].mutable_tensor());
}
change:
void _ConvertVariableToConstant(const NodeDef& variable_node,
                               const Tensor& variable_value,
                               NodeDef* const_node) {
  *const_node = variable_node;
  const_node->set_name(variable_node.name());
  const_node->set_op("Const");
  (*const_node->mutable_attr())["dtype"] = variable_node.attr().at("dtype");
  variable_value.AsProtoTensorContent((*const_node->mutable_attr())["value"].mutable_tensor());
}
It is worked for me.

**Comment by ck-intel** [comment]
@linyuhui I am facing similar issue on windows. Were you able to solve the issue?
For my work I have build Tensorflow from source, and I have added missing protobuf symbols in def_file_filter.py.tpl file, to resolve the protobuf related linking errors.
