### ISSUE TITLE
The parameter M is a placeholder type variable. M's dimension is [None, 4]. Because the dimension information is None, it is impossible to use None as a cyclic variable.

### ISSUE THREAD

**Issue by huang229** [tensorflow/tensorflow#29904]
The parameter M is a placeholder type variable. M's dimension is [None, 4]. Because the dimension information is None, it is impossible to use None as a cyclic variable. I need to use None dimension to extract four coordinate information, and then deduct this area from the feature map. What should I do? Thank you very much.

**Comment by achandraa** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged//tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there and can provide better and faster help to such issues. Thanks!
