### ISSUE TITLE
Cannot authenticate in CoLab with tensorfow 2.0.0-beta1

### ISSUE THREAD

**Issue by ssable** [tensorflow/tensorflow#29908]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): CoLab
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.0.0-beta1
- Python version: 3.6.7
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Describe the current behavior**
google.colab.auth.authenticate_user() will fail with tensorflow 2.0.0-beta1

**Describe the expected behavior**

**Code to reproduce the issue**
!pip install -q tensorflow==2.0.0-beta1
from google.colab import auth
auth.authenticate_user()

**Other info / logs**

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-4-e9280defa4ea> in <module>()
     25 
     26 from google.colab import auth
---> 27 auth.authenticate_user()
     28 
     29 prepared_record_paths = tf.io.gfile.glob(training_data)

/usr/local/lib/python3.6/dist-packages/google/colab/auth.py in authenticate_user(clear_output)
    154       with tf.compat.v1.Session('grpc://{}'.format(colab_tpu_addr)) as sess:
    155         with open(_get_adc_path()) as auth_info:
--> 156           tf.contrib.cloud.configure_gcs(
    157               sess, credentials=_json.load(auth_info))
    158   if _check_adc():

AttributeError: module 'tensorflow' has no attribute 'contrib'

**Comment by dynamicwebpaige** [comment]
Was not able to reproduce, but am experiencing a time out:

<img width="531" alt="Screen Shot 2019-06-18 at 11 46 45 PM" src="https://user-images.githubusercontent.com/3712347/59742835-6f47d500-9223-11e9-9312-dce284b6fe09.png">

**Comment by ssable** [comment]
Thanks for looking at this issue.

I had opened the issue in the wrong repo as the issue is rather with colab itself. So I opened a new one there:
https://github.com/googlecolab/colabtools/issues/602

To reproduce the issue you need to activate "Hardware accelerator: TPU" in "Notebook Settings". Otherwise it works indeed.
I will close this ticket as the issue can be followed in colabtools issues directly.
