### ISSUE TITLE
tensorflow-gpu==2.0.0-beta1 AND tf-nightly-gpu-2-0-preview 2.0.0.dev20190607 fail with errors on windows 64 

### ISSUE THREAD

**Issue by vidyabhandary** [tensorflow/tensorflow#29905]
When installing tensorflow on windows 64 Home edition (with GPU enabled for tensorflow ) - I get the following two errors (with both tensorflow beta and the nightly preview )

ERROR: tensorflow-gpu 2.0.0b1 has requirement tb-nightly<1.14.0a20190604,>=1.14.0a20190603, but you'll have tb-nightly 1.15.0a20190617 which is incompatible.
ERROR: tfp-nightly 0.8.0.dev20190617 has requirement cloudpickle==1.1.1, but you'll have cloudpickle 1.2.1 which is incompatible.

ERROR: tf-nightly-gpu-2-0-preview 2.0.0.dev20190607 has requirement tb-nightly<1.15.0a0,>=1.14.0a0, but you'll have tb-nightly 1.15.0a20190617 which is incompatible.
ERROR: tfp-nightly 0.8.0.dev20190617 has requirement cloudpickle==1.1.1, but you'll have cloudpickle 1.2.1 which is incompatible.

**System information**
- Windows 10 64 bit Home edition with NVidia GPU
- TensorFlow installed from (source or binary): 
- TensorFlow version: tf-nightly-gpu-2.0-preview=tf_nightly_gpu_2.0_preview-2.0.0.dev20190607
AND
tensorflow-gpu==2.0.0-beta1
- Python version: 3.6.8
- Installed using virtualenv? pip? conda?: pip install inside a newly created env using virtualenv
- CUDA/cuDNN version: CUDA - cuda_10.1.168_425.25_win10 , cuDNN - cudnn-10.1-windows10-x64-v7.6.0.64
- GPU model and memory: GEForce GTX 1050 Ti, 8 GB

**Describe the problem**
Getting 2 errors on trying to install tf-nightly-gpu-2.0-preview / tensorflow-gpu==2.0.0-beta1. 

ERROR: tf-nightly-gpu-2-0-preview 2.0.0.dev20190607 has requirement tb-nightly<1.15.0a0,>=1.14.0a0, but you'll have tb-nightly 1.15.0a20190617 which is incompatible.
ERROR: tfp-nightly 0.8.0.dev20190617 has requirement cloudpickle==1.1.1, but you'll have cloudpickle 1.2.1 which is incompatible. 

**Provide the exact sequence of commands / steps that you executed before running into the problem**
I am trying to install tensorflow 2.0 beta / tf-nightly on my windows machine using pip install inside a virtual environment.

Commands -
1. python -m pip install --upgrade pip setuptools virtualenv
2. virtualenv <python path> env
3. Activate the environment
4. python -m pip install --upgrade -r requirements.txt
requirements.txt - Contains the following
```
##### Core scientific packages
jupyter==1.0.0
matplotlib==3.0.3
numpy==1.16.2
pandas==0.24.1
scipy==1.1.0

##### Machine Learning packages
scikit-learn==0.20.3

# Optional: the XGBoost library is only used in the ensemble learning chapter.
xgboost==0.82

##### TensorFlow-related packages

# Replace tensorflow with tensorflow-gpu if you want GPU support. If so,
# you need a GPU card with CUDA Compute Capability 3.5 or higher support, and
# you must install CUDA, cuDNN and more: see tensorflow.org for the detailed
# installation instructions.

#tf-nightly-2.0-preview
#tensorflow-gpu==2.0.0-beta1
tf-nightly-gpu-2.0-preview

#tensorboard
tb-nightly

#tensorflow-datasets
tfds-nightly

tensorflow-hub

# Optional: only used in chapter 13.
#tensorflow-transform==0.13.0

# Optional: only used in chapter 16.
# At the present (April 2019) the TF Addons library is only available on Linux
# So uncomment this line if you are using Linux.
#tensorflow-addons

# Optional: the TF Agents library is only needed in chapter 18
tf-agents-nightly

# Optional: the TF Serving API library is just needed for chapter 19.
tensorflow-serving-api

##### Image manipulation
imageio==2.5.0
Pillow==5.4.1
scikit-image==0.14.2

##### Reinforcement Learning library

# OpenAI gym is only needed in chapter 18.
# There are a few dependencies you need to install first, check out:
# https://github.com/openai/gym#installing-everything
gym[atari]==0.10.9

##### Additional utilities

# Joblib is a set of tools to provide lightweight pipelining
joblib==0.13.2

# May be useful with Pandas for complex "where" clauses (e.g., Pandas
# tutorial).
numexpr==2.6.9

# Optional: these libraries can be useful in chapter 3, exercise 4.
nltk==3.4
urlextract==0.9

# Needed in chapter 19.
requests==2.22.0

# Optional: nice utility to diff Jupyter Notebooks.
#nbdime==1.0.5

# Optional: tqdm displays nice progress bars, ipywidgets for tqdm's notebook support
tqdm==4.31.1
ipywidgets==7.4.2
```

**Comment by gadagashwini** [comment]
@vidyabhandary Please find instructions in this [link](https://www.tensorflow.org/install/pip) which help you to install Tensorflow. Let us know how that progresses. Thanks!

**Comment by vidyabhandary** [comment]
Those are the same commands that are being used. 
I have created the virualenv , activated it and then used pip install (via requirements.txt)

**Comment by vidyabhandary** [comment]
If it helps I get similar error message in the colab environment too - although the versions are different

ERROR: tf-nightly-2-0-preview 2.0.0.dev20190618 has requirement tb-nightly<1.15.0a0,>=1.14.0a0, but you'll have tb-nightly 1.15.0a20190618 which is incompatible.

ERROR: tfp-nightly 0.8.0.dev20190619 has requirement cloudpickle==1.1.1, but you'll have cloudpickle 0.6.1 which is incompatible.

**Comment by mihaimaruseac** [comment]
This is an error in your python environment, not TensorFlow.

You could `pip install cloudpickle==1.1.1` and see if that works.

**Comment by vidyabhandary** [comment]
I do not install cloudpickle separately. It is installed as part of tensorflow. And I am using a clean virtual environment every time. Even colab gives similar error when installing from scratch.

**Comment by jvishnuvardhan** [comment]
@vidyabhandary Can you share a gist from colab? Thanks!

**Comment by mihaimaruseac** [comment]
Somehow there are 2 packages in your `requirements.py` requiring two different version of `cloudpickle`

Will debug this week.

**Comment by vidyabhandary** [comment]
@mihaimaruseac  - Thanks for the clue. It looks like scikit-image and tfp-nightly both have dependency on cloudpickle.  The other dependency for tb-nightly version still shows an error though. 

ERROR: tf-nightly-gpu-2-0-preview 2.0.0.dev20190626 has requirement tb-nightly<1.15.0a0,>=1.14.0a0, but you'll have tb-nightly 1.15.0a20190624 which is incompatible.

@jvishnuvardhan - I have created a GitHub gist at this path. 

https://gist.github.com/vidyabhandary/e9fd7ef120922e90479cd95be05ab889

I am currently not looking at the errors for ipython 5.5.0, google-colab 1.0.0, datascience 0.10.6 and albumentations since none of them appear in my local environment.

**Comment by mihaimaruseac** [comment]
Assigning to @nfelt for tensorboard versioning changes.

**Comment by mihaimaruseac** [comment]
Actually, @vidyabhandary can you try using `tb_nightly==1.14.0a20190614` in `requirements.py` instead of just `tb-nightly`? Version changed recently as TF 1.14 was launched but the 2.0 branch was not updated (most likely won't be until mid July)

**Comment by vidyabhandary** [comment]
With that change I no longer this error - 

ERROR: tf-nightly-gpu-2-0-preview 2.0.0.dev20190626 has requirement tb-nightly<1.15.0a0,>=1.14.0a0, but you'll have tb-nightly 1.15.0a20190624 which is incompatible.

Thanks !!

**Comment by mihaimaruseac** [comment]
Thank you for confirming fix. I'm going to close the issue now but feel free to reopen if there's something else to solve here and I missed it
