### ISSUE TITLE
TF=GPU 2.0.0b TF Transform missing AUTOTUNE on import

### ISSUE THREAD

**Issue by Ryandry1st** [tensorflow/tensorflow#29919]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): POSIX
- TensorFlow version: 2.0.0b-gpu
- Python version: 3.6.7
- Installed using virtualenv? pip? conda?: pip
- CUDA/cuDNN version: 
- GPU model and memory: Tesla T4

**Describe the problem**
Attempted to use TFX, specifically TF Transform, however when importing TF Transform it throws the error that AUTOTUNE is unknown.

`!pip install tensorflow_transform`
`import tensorflow_transform as tft`

**Any other info / logs**
AttributeError: module 'tensorflow.python.data.experimental.ops.optimization' has no attribute 'AUTOTUNE'
For the full log see the attached file

[TF_Transform_Import_Error.txt](https://github.com/tensorflow/tensorflow/files/3302615/TF_Transform_Import_Error.txt)

**Comment by achandraa** [comment]
Looks like a TF Transform issue. For better and faster support, please post it to [Transform repository](https://github.com/tensorflow/transform/issues). Thanks!

**Comment by Ryandry1st** [comment]
Closing and reopened as https://github.com/tensorflow/transform/issues/123

**Comment by broughtong** [comment]
I believe this is not to do with the transform, but with the initialisation of tensorflow contrib. I just updated to 2.0.0b1, and when I run just

```
from tensorflow import contrib
autograph = contrib.autograph
``` 

from [here](https://www.tensorflow.org/guide/autograph) I receive the following error also:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/george/.local/lib/python3.6/site-packages/tensorflow/contrib/__init__.py", line 38, in <module>
    from tensorflow.contrib import data
  File "/home/george/.local/lib/python3.6/site-packages/tensorflow/contrib/data/__init__.py", line 103, in <module>
    from tensorflow.contrib.data.python.ops.readers import CsvDataset
  File "/home/george/.local/lib/python3.6/site-packages/tensorflow/contrib/data/python/ops/readers.py", line 48, in <module>
    prefetch_buffer_size=optimization.AUTOTUNE,
AttributeError: module 'tensorflow.python.data.experimental.ops.optimization' has no attribute 'AUTOTUNE'
```

Looking at the error log you provided, it appears to be the same problem
