### ISSUE TITLE
ModuleNotFoundError: No module named '_pywrap_tensorflow'

### ISSUE THREAD

**Issue by sarrthak** [tensorflow/tensorflow#29913]
Hello all,

I am trying to import tensorflow but it shows the following error. 

`ModuleNotFoundError: No module named '_pywrap_tensorflow'`

I have already tried to add the MSVC140.DLL file from [ttps://www.dll-files.com/msvcp140.dll.html]( https://www.dll-files.com/msvcp140.dll.html)  it still shows the stated error. 

OS: Windows 10
Python version: 3.6.4
Conda version: 4.6.14
PIP version: 19.1.1
GPU: AMD Radeon R540x
Command used to install tensorflow: `conda install tensorflow `  ; `pip install https://storage.googleapis.com/tensorflow/mac/cpu/tensorflow-1.12.0-py3-none-any.whl` which I got from this link [https://stackoverflow.com/questions/38896424/tensorflow-not-found-using-pip](https://stackoverflow.com/questions/38896424/tensorflow-not-found-using-pip)

I don't use CUDA services and am using only CPU support.

```
(base) (picktolight) F:\Internship\Nokia_work>python
Python 3.6.4 (v3.6.4:d48eceb, Dec 19 2017, 06:04:45) [MSC v.1900 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
Traceback (most recent call last):
  File "F:\Internship\Nokia_work\picktolight\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 18, in swig_import_helper
    fp, pathname, description = imp.find_module('_pywrap_tensorflow', [dirname(__file__)])
  File "F:\Internship\Nokia_work\picktolight\lib\imp.py", line 297, in find_module
    raise ImportError(_ERR_MSG.format(name), name=name)
ImportError: No module named '_pywrap_tensorflow'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\Internship\Nokia_work\picktolight\lib\site-packages\tensorflow\python\__init__.py", line 66, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "F:\Internship\Nokia_work\picktolight\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 28, in <module>
    _pywrap_tensorflow = swig_import_helper()
  File "F:\Internship\Nokia_work\picktolight\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 20, in swig_import_helper
    import _pywrap_tensorflow
ModuleNotFoundError: No module named '_pywrap_tensorflow'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "F:\Internship\Nokia_work\picktolight\lib\site-packages\tensorflow\__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "F:\Internship\Nokia_work\picktolight\lib\site-packages\tensorflow\python\__init__.py", line 72, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "F:\Internship\Nokia_work\picktolight\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 18, in swig_import_helper
    fp, pathname, description = imp.find_module('_pywrap_tensorflow', [dirname(__file__)])
  File "F:\Internship\Nokia_work\picktolight\lib\imp.py", line 297, in find_module
    raise ImportError(_ERR_MSG.format(name), name=name)
ImportError: No module named '_pywrap_tensorflow'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\Internship\Nokia_work\picktolight\lib\site-packages\tensorflow\python\__init__.py", line 66, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "F:\Internship\Nokia_work\picktolight\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 28, in <module>
    _pywrap_tensorflow = swig_import_helper()
  File "F:\Internship\Nokia_work\picktolight\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 20, in swig_import_helper
    import _pywrap_tensorflow
ModuleNotFoundError: No module named '_pywrap_tensorflow'


Failed to load the native TensorFlow runtime.
```
Also, I am getting the error using cmd. 
![image](https://user-images.githubusercontent.com/31880143/59679060-836fe000-91eb-11e9-9b24-d962049753f1.png)

**Any help will be greatly appreciated.** 
 **Thanks a lot!**

**Comment by rlewkowicz** [comment]
I'm not super familiar with conda, but I think it's supposed to be one or the other regarding pip. 

I think with conda, that's your package manager now (although you can still use pip). You can also use it to create an environment, and then just use pip. Using both doesn't make sense. 

For windows, you could do a classic install of python and just do pip install tensorflow. 

If you have an intel cpu, these might be useful as well:

https://software.intel.com/en-us/articles/intel-optimization-for-tensorflow-installation-guide

**Comment by mihaimaruseac** [comment]
Why are you installing a MacOS pip on a windows machine?

**Comment by sarrthak** [comment]
@rlewkowicz  I did try to use pip with this but got an error. 

```
(picktolight) F:\Internship\Nokia_work>pip install tensorflow
Collecting tensorflow
  ERROR: Could not find a version that satisfies the requirement tensorflow (from versions: none)
ERROR: No matching distribution found for tensorflow
```
So, decided to use conda instead but got this, 

```
(picktolight) F:\Internship\Nokia_work>conda install tensorflow
Collecting package metadata: done
Solving environment: done

# All requested packages already installed.

(picktolight) F:\Internship\Nokia_work>python
Python 3.6.4 (v3.6.4:d48eceb, Dec 19 2017, 06:04:45) [MSC v.1900 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'tensorflow'
>>> ^Z
```
I really am not able to understand this.

**Comment by sarrthak** [comment]
@mihaimaruseac  I first tried with this link, present on the main documentation.

[https://storage.googleapis.com/tensorflow/windows/cpu/tensorflow-1.13.1-cp36-cp36m-win_amd64.whl](https://storage.googleapis.com/tensorflow/windows/cpu/tensorflow-1.13.1-cp36-cp36m-win_amd64.whl)

but then got the following error, 

```
(picktolight) F:\Internship\Nokia_work>pip install https://storage.googleapis.com/tensorflow/windows/cpu/tensorflow-1.13.1-cp36-cp36m-win_amd64.whl
ERROR: tensorflow-1.13.1-cp36-cp36m-win_amd64.whl is not a supported wheel on this platform.
```
So had no choice but to use the link, 
[https://storage.googleapis.com/tensorflow/mac/cpu/tensorflow-1.12.0-py3-none-any.whl](https://storage.googleapis.com/tensorflow/mac/cpu/tensorflow-1.12.0-py3-none-any.whl)

because this is the only thing that works, but then I get this error,
`ModuleNotFoundError: No module named '_pywrap_tensorflow' `

**Comment by mihaimaruseac** [comment]
Are you by any chance on a 32bits system?

Also, the fact that Conda says TF is installed but Python doesn't see it is an indication that python path doesn't include conda dirs

**Comment by sarrthak** [comment]
@mihaimaruseac  No, I am using a 64-bits OS.
I think the path can be an issue, but I am using `virtualenv`  shouldn't that help? 
All the required packages get stored in the `virtualenv` folder, so python should take it from there or that is what I think. 
Maybe, if you can elaborate more on the path issue, I can try with that.

**Comment by mihaimaruseac** [comment]
I don't think Conda install in the virtualenv path :-/

**Comment by sarrthak** [comment]
@mihaimaruseac    Well, Anaconda installs its own version of python. I tried using `import tensorflow`.
but got the following error. 

```
F:\Internship\Nokia_work>py
Python 3.7.1 (default, Dec 10 2018, 22:54:23) [MSC v.1915 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow
Traceback (most recent call last):
  File "C:\Users\Admin\Anaconda3\lib\site-packages\numpy\core\__init__.py", line 16, in <module>
    from . import multiarray
ImportError: DLL load failed: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Admin\Anaconda3\lib\site-packages\tensorflow\__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "C:\Users\Admin\Anaconda3\lib\site-packages\tensorflow\python\__init__.py", line 47, in <module>
    import numpy as np
  File "C:\Users\Admin\Anaconda3\lib\site-packages\numpy\__init__.py", line 142, in <module>
    from . import add_newdocs
  File "C:\Users\Admin\Anaconda3\lib\site-packages\numpy\add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "C:\Users\Admin\Anaconda3\lib\site-packages\numpy\lib\__init__.py", line 8, in <module>
    from .type_check import *
  File "C:\Users\Admin\Anaconda3\lib\site-packages\numpy\lib\type_check.py", line 11, in <module>
    import numpy.core.numeric as _nx
  File "C:\Users\Admin\Anaconda3\lib\site-packages\numpy\core\__init__.py", line 26, in <module>
    raise ImportError(msg)
ImportError:
Importing the multiarray numpy extension module failed.  Most
likely you are trying to import a failed build of numpy.
If you're working with a numpy git repo, try `git clean -xdf` (removes all
files not under version control).  Otherwise reinstall numpy.

Original error was: DLL load failed: The specified module could not be found.

>>> ^Z
```
I think conda did not install the package in the default python path (which has python 3.6.4) and installed the packages on its Python path (which has 3.7.1 version of python).

**Comment by achandraa** [comment]
Just to verify did you try following steps from [TensorFlow website](https://www.tensorflow.org/install/pip). Let us know. Thanks!

**Comment by sarrthak** [comment]
@achandraa  Yes, I followed the exact process as mentioned on the website. 
As stated above `pip install tensorflow` gave me an error. So I tried using the wheel link provided on the website, but it showed unsupported wheel. 

[https://storage.googleapis.com/tensorflow/windows/cpu/tensorflow-1.13.1-cp36-cp36m-win_amd64.whl](https://storage.googleapis.com/tensorflow/windows/cpu/tensorflow-1.13.1-cp36-cp36m-win_amd64.whl) 
I tried to use the above link.
The command I gave was,
`pip install https://storage.googleapis.com/tensorflow/windows/cpu/tensorflow-1.13.1-cp36-cp36m-win_amd64.whl`

**Comment by mihaimaruseac** [comment]
It really seems that your environment is in a terrible state. But let's try to debug. Can you please tell me the outputs of

```bash
$ pip --version
$ python3.6 -m pip --version 
```

Make sure you're running the above commands in a clear directory, without any virtualenv/conda environment active

**Comment by sarrthak** [comment]
**@mihaimaruseac @rlewkowicz @achandraa  Thank you all! The problem got solved.** 

I solved my problem by completely migrating to Anaconda. I uninstalled all versions of python ( had 3 versions 3.6.4, 3.7.3, and 3.6.8 ). It seems 3.7.3  and 3.6.8 were installed my Anaconda. As stated `pip install tensorflow` was not working but `conda install tensorflow` was working.
 
As it was pointed out by **@mihaimaruseac** the conda command installed everything to its own Path (As conda used Python 3.7.3, and its Path was `C:\Users\Admin\Anaconda3`) , while on my **Command Prompt** I was still running Python 3.6.4 (which had `C:\Users\Admin\AppData\Local\Python35-36` as its path). 

This created a conflict, as `conda install tensorflow` (I had added conda path to my cmd prompt so could access it from there ) installed everything in its own path which had **Python 3.7.3** as its default. As pointed out here [https://github.com/ContinuumIO/anaconda-issues/issues/1508]( https://github.com/ContinuumIO/anaconda-issues/issues/1508) **(while using Anaconda I got this Numpy  error, so decided to follow the steps listed out on this issue.)** 

For convineince, I am mentioning the commands here:

```
set ROOT=%TEMP%
cd %ROOT%
powershell -command "& { (New-Object Net.WebClient).DownloadFile('https://repo.continuum.io/miniconda/Miniconda3-4.3.21-Windows-x86.exe', 'mc3.exe') }"
start /wait "" mc3.exe /InstallationType=JustMe /AddToPath=0 /RegisterPython=0 /NoRegistry=1 /S /D=%ROOT%\mc3
: Properly activate the env.
%ROOT%\mc3\Scripts\activate.bat
: Update everything
conda update -y --all
conda install -y numpy
python -c "import numpy"
```
**This solved my problem for a while but conda degraded its Python version to 3.6.8, and all my Python packages started to give error. It was like everything I ever wrote gave me an error.**  
This is when I lost my patience and decided to completely migrate from `pip` to `conda`. 
So I decided to delete the current version of Anaconda Navigator and all versions of Python from my PC, and then redownloaded Anaconda Navigator from here:  [https://www.anaconda.com/distribution/](https://www.anaconda.com/distribution/). 

I have not downloaded any version of python after this and only use Anaconda Prompt to use Python that too in a conda environment. 
**Now, I make a conda environment for everything I do and usually use Python 3.5.0  (which In my opinion the most stable release of python till date)** , I hope I may never encounter this and everything goes on without Python creating any more problems in my life.
Now, I only use anaconda distribution, hoping to never encounter these errors ever again. 
**But really thanks to you all!! I wouldn't have been able to solve this madness without you helping me.**

**Thanks a lot for your help and Patience!!**
**Cheers!**

**Comment by cool-man-vk** [comment]
It is showing that the platform not supported!
