### ISSUE TITLE
Error running tf.nn.atrous_conv2d on TF 0.9.0rc0

### ISSUE THREAD

**Issue by lukovkin** [tensorflow/tensorflow#2991]
Getting error running tf.nn.atrous_conv2d on TensorFlow 0.9.0rc0. The same code runs successfully on TensorFlow 0.8.0 installed from the source.

### Environment info
Operating System: Ubuntu 14.04

Installed version of CUDA and cuDNN:  None

If installed from binary pip package, provide:

1. https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.9.0rc0-cp35-cp35m-linux_x86_64.whl
2. 0.9.0rc0

### Steps to reproduce
1. Install TF from the package
2. Call tf.nn.atrous_conv2d from the client code (see code here - https://github.com/nmayorov/ufcnn/blob/master/ufcnn/ufcnn.py)
3. Get TypeError: __int__ returned non-int (type NoneType)

### What have you tried?
1. Installation of 0.8.0 from the source helps

### Logs or other output that would be helpful
Traceback (most recent call last):
  File "UFCNN_functional.py", line 2050, in <module>
    x, y_hat, *_ = construct_ufcnn(n_inputs=2, n_outputs=y_train.shape[2], n_levels=4, n_filters=150)
  File "/notebook/UFCNN/ufcnn/ufcnn/ufcnn.py", line 227, in construct_ufcnn
    x = tf.nn.relu(conv(x, w, b, filter_length, dilation))
  File "/notebook/UFCNN/ufcnn/ufcnn/ufcnn.py", line 15, in conv
    x = tf.nn.atrous_conv2d(x, w, dilation, padding='VALID')
  File "/root/miniconda2/envs/keras/lib/python3.5/site-packages/tensorflow/python/ops/nn_ops.py", line 169, in atrous_conv2d
    in_width = int(value_shape[2])
TypeError: __int__ returned non-int (type NoneType)

**Comment by prb12** [comment]
Looks like you are passing in the `value` parameter a placeholder with a shape which does not specify the width and height dimensions [here](https://github.com/nmayorov/ufcnn/blob/master/ufcnn/ufcnn.py#L238).   The `atrous_conv2d` op (at least in 0.9) requires the `in_height` and `in_width` dimensions to be defined: 
https://github.com/tensorflow/tensorflow/blob/r0.9/tensorflow/python/ops/nn_ops.py#L169
You appear to be able to leave the batch dimension unspecified.

The handling of these parameters was improved in the following commit: https://github.com/tensorflow/tensorflow/commit/3a744a417178646712e9cda0a85655d5d8968e19

If this is a problem for you, could you please try against a newer build and see if this fixes your problem?

**Comment by lukovkin** [comment]
@prb12 Thank you for your response, we'll take a look.

**Comment by nmayorov** [comment]
All these is not surprise for me, later versions of TF support variable size dimensions in `atrous_conv2d` and I never had any problem with it. This issue can be close.

**Comment by lukovkin** [comment]
@nmayorov Are you sure that it will not re-occure in 0.9.0 release?

**Comment by nmayorov** [comment]
Well, it depends on what will be included in 0.9.0 release. At the moment I see that the 0.9 branch doesn't contain this fix. A bit of inconvenience, but what can we do.

The solution on our side is to create our ufcnn with a fixed length of signals (which sort of contradicts sequence-to-sequence paradigm). But it is better to discuss it not here.

**Comment by lukovkin** [comment]
OK, closed.
