### ISSUE TITLE
Defun and function input_signatures don't accept variables as input

### ISSUE THREAD

**Issue by fps7806** [tensorflow/tensorflow#29922]
Defun and function input_signatures don't accept variables as input. To bypass this, we have to explicitly convert tf.Variables to tf.Tensors
**System information**
- TensorFlow installed from (source or binary):binary
- TensorFlow version (use command below): 1.13.1

**Code to reproduce the issue**
```
import tensorflow as tf

tf.enable_eager_execution()

@tf.contrib.eager.function(input_signature=[tf.TensorSpec(shape=None, dtype=tf.float32)])
def identity(x):
  return x

a = tf.Variable(())
print(identity(a.read_value()))
print(identity(a))
```

This fails on the second call:
```
ValueError: When input_signature is provided, all inputs to the Python function must be Tensors.
```

**Comment by achandraa** [comment]
Please have a look on this [link](https://www.tensorflow.org/api_docs/python/tf/contrib/eager/defun) which says python function compiled with an input_signature must only accept Tensors as arguments. Let us know if that helps to resolve the issue. Thanks!

**Comment by fps7806** [comment]
> Please have a look on this [link](https://www.tensorflow.org/api_docs/python/tf/contrib/eager/defun) which says python function compiled with an input_signature must only accept Tensors as arguments. Let us know if that helps to resolve the issue. Thanks!

I see, that behavior is somewhat unintuitive. I would expect that all `tf.Variable`s would get automatically converted to `tf.Tensor` like we expect from all other ops.

Thanks for looking into it anyway!
