### ISSUE TITLE
link tensorflow1.13.1 static library failed  (gcc 4.9.3)

### ISSUE THREAD

**Issue by cSingleboy** [tensorflow/tensorflow#29927]
In file included from /home/cuijg/Documents/computer_so/xuhuanwen/so_cmake/src/publiclib-lite/third_party/tensorflow_1.13.1/static_lib/eigen/unsupported/Eigen/CXX11/Tensor:120:0,
                 from /home/cuijg/Documents/computer_so/xuhuanwen/so_cmake/src/publiclib-lite/third_party/tensorflow_1.13.1/static_lib/third_party/eigen3/unsupported/Eigen/CXX11/Tensor:1,
                 from /home/cuijg/Documents/computer_so/xuhuanwen/so_cmake/src/publiclib-lite/third_party/tensorflow_1.13.1/static_lib/tensorflow/core/framework/tensor.h:21,
                 from /home/cuijg/Documents/computer_so/xuhuanwen/so_cmake/src/publiclib-lite/third_party/tensorflow_1.13.1/static_lib/tensorflow/core/public/session.h:24,
                 from /home/cuijg/Documents/computer_so/xuhuanwen/so_cmake/src/src/L2/Algorithm_ctrinterest/nn_raw.h:17,
                 from /home/cuijg/Documents/computer_so/xuhuanwen/so_cmake/src/src/L2/Algorithm_ctrinterest/nnso_raw.h:9,
                 from /home/cuijg/Documents/computer_so/xuhuanwen/so_cmake/src/src/L2/Algorithm_ctrinterest/model.cpp:2:
/home/cuijg/Documents/computer_so/xuhuanwen/so_cmake/src/publiclib-lite/third_party/tensorflow_1.13.1/static_lib/eigen/unsupported/Eigen/CXX11/src/Tensor/TensorBlock.h: In static member function ‘static void Eigen::internal::TensorBlockIO<Scalar, StorageIndex, NumDims, Layout, BlockRead>::Copy(const Block&, StorageIndex, const Dimensions&, const Dimensions&, const Scalar*, Scalar*)’:
/home/cuijg/Documents/computer_so/xuhuanwen/so_cmake/src/publiclib-lite/third_party/tensorflow_1.13.1/static_lib/eigen/unsupported/Eigen/CXX11/src/Tensor/TensorBlock.h:393:63: error: the value of ‘j’ is not usable in a constant expression
         if (++block_iter_state[j].count < block_iter_state[j].size) {
                                                               ^
/home/cuijg/Documents/computer_so/xuhuanwen/so_cmake/src/publiclib-lite/third_party/tensorflow_1.13.1/static_lib/eigen/unsupported/Eigen/CXX11/src/Tensor/TensorBlock.h:392:16: note: ‘int j’ is not const
       for (int j = 0; j < num_squeezed_dims; ++j) {
                ^
/home/cuijg/Documents/computer_so/xuhuanwen/so_cmake/src/publiclib-lite/third_party/tensorflow_1.13.1/static_lib/eigen/unsupported/Eigen/CXX11/src/Tensor/TensorBlock.h:393:35: error: parse error in template argument list
         if (++block_iter_state[j].count < block_iter_state[j].size) {
                                   ^
/home/cuijg/Documents/computer_so/xuhuanwen/so_cmake/src/publiclib-lite/third_party/tensorflow_1.13.1/static_lib/eigen/unsupported/Eigen/CXX11/src/Tensor/TensorBlock.h: In static member function ‘static void Eigen::internal::TensorBlockCwiseUnaryIO<UnaryFunctor, StorageIndex, OutputScalar, NumDims, Layout>::Run(const UnaryFunctor&, const Dimensions&, const Dimensions&, OutputScalar*, Eigen::array<StorageIndex, NumDims>&, const InputScalar*)’:
/home/cuijg/Documents/computer_so/xuhuanwen/so_cmake/src/publiclib-lite/third_party/tensorflow_1.13.1/static_lib/eigen/unsupported/Eigen/CXX11/src/Tensor/TensorBlock.h:604:21: error: parse error in template argument list
         if (++state.count < state.size) {
                     ^
/home/cuijg/Documents/computer_so/xuhuanwen/so_cmake/src/publiclib-lite/third_party/tensorflow_1.13.1/static_lib/eigen/unsupported/Eigen/CXX11/src/Tensor/TensorBlock.h: In static member function ‘static void Eigen::internal::TensorBlockCwiseBinaryIO<BinaryFunctor, StorageIndex, OutputScalar, NumDims, Layout>::Run(const BinaryFunctor&, const Dimensions&, const Dimensions&, OutputScalar*, Eigen::array<StorageIndex, NumDims>&, const LeftScalar*, Eigen::array<StorageIndex, NumDims>&, const RightScalar*)’:
/home/cuijg/Documents/computer_so/xuhuanwen/so_cmake/src/publiclib-lite/third_party/tensorflow_1.13.1/static_lib/eigen/unsupported/Eigen/CXX11/src/Tensor/TensorBlock.h:758:21: error: parse error in template argument list
         if (++state.count < state.size) {
                     ^
In file included from /home/cuijg/Documents/computer_so/xuhuanwen/so_cmake/src/publiclib-lite/third_party/tensorflow_1.13.1/static_lib/eigen/unsupported/Eigen/CXX11/Tensor:143:0,
                 from /home/cuijg/Documents/computer_so/xuhuanwen/so_cmake/src/publiclib-lite/third_party/tensorflow_1.13.1/static_lib/third_party/eigen3/unsupported/Eigen/CXX11/Tensor:1,
                 from /home/cuijg/Documents/computer_so/xuhuanwen/so_cmake/src/publiclib-lite/third_party/tensorflow_1.13.1/static_lib/tensorflow/core/framework/tensor.h:21,
                 from /home/cuijg/Documents/computer_so/xuhuanwen/so_cmake/src/publiclib-lite/third_party/tensorflow_1.13.1/static_lib/tensorflow/core/public/session.h:24,
                 from /home/cuijg/Documents/computer_so/xuhuanwen/so_cmake/src/src/L2/Algorithm_ctrinterest/nn_raw.h:17,
                 from /home/cuijg/Documents/computer_so/xuhuanwen/so_cmake/src/src/L2/Algorithm_ctrinterest/nnso_raw.h:9,
                 from /home/cuijg/Documents/computer_so/xuhuanwen/so_cmake/src/src/L2/Algorithm_ctrinterest/model.cpp:2:
/home/cuijg/Documents/computer_so/xuhuanwen/so_cmake/src/publiclib-lite/third_party/tensorflow_1.13.1/static_lib/eigen/unsupported/Eigen/CXX11/src/Tensor/TensorMorphing.h: In member function ‘void Eigen::TensorEvaluator<const Eigen::TensorReshapingOp<NewDimensions, XprType>, Device>::block(Eigen::TensorEvaluator<const Eigen::TensorReshapingOp<NewDimensions, XprType>, Device>::OutputTensorBlock*) const’:
/home/cuijg/Documents/computer_so/xuhuanwen/so_cmake/src/publiclib-lite/third_party/tensorflow_1.13.1/static_lib/eigen/unsupported/Eigen/CXX11/src/Tensor/TensorMorphing.h:319:35: error: parse error in template argument list
         if (++block_iter_state[i].count < block_iter_state[i].size) {
                                   ^
CMakeFiles/so_cmake.dir/build.make:153: recipe for target 'CMakeFiles/so_cmake.dir/src/src/L2/Algorithm_ctrinterest/model.cpp.o' failed
make[3]: *** [CMakeFiles/so_cmake.dir/src/src/L2/Algorithm_ctrinterest/model.cpp.o] Error 1
CMakeFiles/Makefile2:72: recipe for target 'CMakeFiles/so_cmake.dir/all' failed
make[2]: *** [CMakeFiles/so_cmake.dir/all] Error 2
CMakeFiles/Makefile2:84: recipe for target 'CMakeFiles/so_cmake.dir/rule' failed
make[1]: *** [CMakeFiles/so_cmake.dir/rule] Error 2
Makefile:118: recipe for target 'so_cmake' failed
make: *** [so_cmake] Error 2

**Comment by ileniTudor** [comment]
I had the same issue
I resolved it by manually downloading the eigen v 3.3.7 (last stable)
 http://eigen.tuxfamily.org/index.php?title=Main_Page

And replace the tensorflow/contrib/makefile/downloads/eigen folder with the content from the .zip file.

**Comment by gadagashwini** [comment]
@cSingleboy Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version. Also, did you compile from source or install a binary?

Make sure you also include the exact command if possible to produce the output included in your test case. If you are unclear what to include see the issue template displayed in [the Github new issue template](https://github.com/tensorflow/tensorflow/issues/new/choose).

We ask for this in the issue submission template, because it is really difficult to help without that information. Thanks!

**Comment by gadagashwini** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Comment by OrHirshfeldFFR** [comment]
I had a similar issue and solved it by compiling it with gcc-7 instead of gcc-6
