### ISSUE TITLE
Tf.app.flags implicit parsing potentially causes crash with exception

### ISSUE THREAD

**Issue by tlranda** [tensorflow/tensorflow#29921]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
Yes
- OS Platform and Distribution:
Linux Fedora 30
- TensorFlow installed from:
binary
- TensorFlow version:
1.13.1
- Python version:
3.7.3
- CUDA version
10.0
- GPU Model
NVIDIA TITAN V Black

**Describe the current behavior**

The -h, -help, -helpshort, and -helpfull arguments may cause exceptions to be triggered as opposed to displaying flags, default values, and programmer-provided information. This seems to occur when the `tf.app.flags` abseil wrapper attempts to use implicit parsing.

**Describe the expected behavior**

When any value of -h, -help, -helpshort, -helpfull are provided as arguments to scripts using `tf.app.flags`, the help list should appear.

**Code to reproduce the issue**
```python
''' mwe.py: displays tensorflow --help argument issue '''
from tensorflow import app
app.flags.DEFINE_string('myflag', 'Default', 'Help output')
FLAGS = app.flags.FLAGS
global_string = "This string causes the abseil wrapper to begin processing the {0} flag".format(FLAGS.myflag)
def main(_):
  print("This string causes TF to race the abseil parsing process, which kills the help menu using string %s" % FLAGS.myflag)
if __name__ == '__main__':
  app.run(main)
```

**Other info / logs**
The below bash script uses the above code to display the issue. Notably, using abseil's app.flags will NOT cause the exception to occur with the same source code.
```bash
python mwe.py --help
sed -i 's/global_string/#global_string/g' mwe.py
python mwe.py --help
```

This is related to issue #28581. After elaborating on the issue and not receiving a response, I have opened this new issue. If further information is required, please let me know how I may assist you.

**Comment by ravikyram** [comment]
Can you please let us know what are the exceptions you are facing .Thanks.

**Comment by tlranda** [comment]
Sure. Hopefully you can reproduce these results by running the included code above. But here's what I get:
```bash
python mwe.py
This string causes TF to race the abseil parsing process, which kills the help menu using string Default
```
```bash
python mwe.py -help
```
```python
Traceback (most recent call last):
 File “mwe.py”, line 5, in <module>
   global_string = “This string causes the abseil wrapper to begin processing the {0} flag”.format(FLAGS.myflag)
 File “/home/.local/lib/python3.7/site-packages/tensorflow/python/platform/flags.py”, line 84, in __getattr__
   wrapped(_sys.argv)
 File “/home/.local/lib/python3.7/site-packages/absl/flags/_flagvalues.py”, line 633, in __call__
   name, value, suggestions=suggestions)
absl.flags._exceptions.UnrecognizedFlagError: Unknown command line flag ‘help’
```
I should also note that if you switch to just using abseil without the tensorflow wrapper (change `from tensorflow import app` to `from absl import app`, the following exception is raised regardless of whether or not a help flag is specified:

```bash
python mwe_absl.py [-help]
```
```python
Traceback (most recent call last):
  File "mwe.py", line 5, in <module>
    global_string = "This string causes the abseil wrapper to begin processing the {0} flag".format(FLAGS.myflag)
  File "/home/.local/lib/python3.7/site-packages/absl/flags/_flagvalues.py", line 491, in __getattr__
    raise _exceptions.UnparsedFlagAccessError(error_message)
absl.flags._exceptions.UnparsedFlagAccessError: Trying to access flag --myflag before flags were parsed.
```

**Comment by ravikyram** [comment]
I was able to reproduce the code in Colab. Thanks.

**Comment by mihaimaruseac** [comment]
Sorry, I just saw this. Will investigate

**Comment by mihaimaruseac** [comment]
It also reproduces in latest nightly.

However, I don't think I'm a good owner for this, don't know where to fix. Unassigning myself.

**Comment by ymodak** [comment]
Tested with TF 1.15.0rc1 it breaks with message,
```python
UnrecognizedFlagError: Unknown command line flag 'f'
```

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.

**Comment by tlranda** [comment]
I am no longer maintaining the particular codebase, but I was able to update my minimum working example as follows for 2.x compatibility and the issue still seems to occur. That said, it may be lower priority as it is legacy behavior now.

mwe_2x.py
```
import tensorflow as tf
from tensorflow.compat.v1 import app, flags
FLAGS = flags.FLAGS
flags.DEFINE_string('myflag', 'Default', 'Help output')
global_string = f"Use abseil wrapper to access {FLAGS.myflag}"
def main(argv):
  print(f"Race condition on {FLAGS.myflag}")
if __name__ == '__main__':
  app.run(main)
```

Test for error and resulting exception:
```
python3 mwe_2x.py --help
```
Output:
```
Traceback (most recent call last):
  File "mwe_2x.py", line 5, in <module>
    global_string = f"Use abseil wrapper to access {FLAGS.myflag}"
  File "/.../python3.8/site-packages/tensorflow/python/platform/flags.py", line 85, in __getattr__
    wrapped(_sys.argv)
  File "/.../python3.8/site-packages/absl/flags/_flagvalues.py", line 654, in __call__
    raise _exceptions.UnrecognizedFlagError(
absl.flags._exceptions.UnrecognizedFlagError: Unknown command line flag 'help'
```

Test to ensure error originates from Tensorflow, not Abseil (Abseil on its own properly creates exception):
```
sed "s/^import/#import/" mwe_2x.py > mwe_2x_test1.py;
sed -i "" -e "s/tensorflow.compat.v1/absl/" mwe_2x_test1.py;
python3 mwe_2x_test1.py --help
```
Output:
```
Traceback (most recent call last):
  File "mwe_2x_test1.py", line 6, in <module>
    global_string = f"Use abseil wrapper to access {FLAGS.myflag}"
  File "/.../python3.8/site-packages/absl/flags/_flagvalues.py", line 498, in __getattr__
    raise _exceptions.UnparsedFlagAccessError(error_message)
absl.flags._exceptions.UnparsedFlagAccessError: Trying to access flag --myflag before flags were parsed.
```
Note that Abseil properly catches the race condition even in --help is not given:
```
python3 mwe_test1.py
```
Output:
```
Traceback (most recent call last):
  File "mwe_2x_test1.py", line 5, in <module>
    global_string = f"Use abseil wrapper to access {FLAGS.myflag}"
  File "/.../python3.8/site-packages/absl/flags/_flagvalues.py", line 498, in __getattr__
    raise _exceptions.UnparsedFlagAccessError(error_message)
absl.flags._exceptions.UnparsedFlagAccessError: Trying to access flag --myflag before flags were parsed.
```

Test to run as expected, but without desired behavior:
```
sed "s/global_string/#global_string/" mwe_2x.py > mwe_2x_test2.py;
python3 mwe_2x.py --help
```
Output:
```

       USAGE: mwe_2x_test2.py [flags]
flags:

mwe_2x_test2.py:
  --myflag: Help output
    (default: 'Default')

Try --helpfull to get a list of all flags.
```

**Comment by mihaimaruseac** [comment]
If it only comes from `tf.compat`, then I think we can close this. Thank you
