### ISSUE TITLE
Code Using FeatureColumn W/ Keras Functional API works for 2.0.0-alpha0 But is broken for 2.0.0-beta1

### ISSUE THREAD

**Issue by HubberDev** [tensorflow/tensorflow#29923]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):Y
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 16.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary):Source
- TensorFlow version (use command below):2.0.0-beta1
- Python version:3.5
- Bazel version (if compiling from source):N/A
- GCC/Compiler version (if compiling from source):N/A
- CUDA/cuDNN version:N/A
- GPU model and memory:N/A

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
This is related to the closed issue https://github.com/tensorflow/tensorflow/issues/27416.
The code snippet below feeds feature columns to Keras models built from functional API. The code works fine for Tensorflow 2.0.0-alpha0 but brakes for Tensorflow 2.0.0-beta1 with the following error message:

49 validation examples
61 test examples
Traceback (most recent call last):
File "/tmp/zeppelin_pyspark-5282677307998123760.py", line 326, in 
exec(code)
File "", line 44, in 
File "/usr/lib/envs/env-1923-ver-2635-a-4.2.9-py-3.5.3/lib/python3.5/site-packages/tensorflow/python/keras/engine/base_layer.py", line 662, in call
outputs = call_fn(inputs, *args, **kwargs)
File "/usr/lib/envs/env-1923-ver-2635-a-4.2.9-py-3.5.3/lib/python3.5/site-packages/tensorflow/python/autograph/impl/api.py", line 166, in wrapper
), args, kwargs)
File "/usr/lib/envs/env-1923-ver-2635-a-4.2.9-py-3.5.3/lib/python3.5/site-packages/tensorflow/python/autograph/impl/api.py", line 340, in converted_call
if inspect_utils.isbuiltin(f):
File "/usr/lib/envs/env-1923-ver-2635-a-4.2.9-py-3.5.3/lib/python3.5/site-packages/tensorflow/python/autograph/pyct/inspect_utils.py", line 84, in isbuiltin
if f in six.moves.builtins.dict.values():
File "/usr/lib/envs/env-1923-ver-2635-a-4.2.9-py-3.5.3/lib/python3.5/site-packages/pandas/core/generic.py", line 1478, in nonzero
.format(self.class.name))
ValueError: The truth value of a DataFrame is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/tmp/zeppelin_pyspark-5282677307998123760.py", line 333, in 
raise Exception(traceback.format_exc())
Exception: Traceback (most recent call last):
File "/tmp/zeppelin_pyspark-5282677307998123760.py", line 326, in 
exec(code)
File "", line 44, in 
File "/usr/lib/envs/env-1923-ver-2635-a-4.2.9-py-3.5.3/lib/python3.5/site-packages/tensorflow/python/keras/engine/base_layer.py", line 662, in call
outputs = call_fn(inputs, *args, **kwargs)
File "/usr/lib/envs/env-1923-ver-2635-a-4.2.9-py-3.5.3/lib/python3.5/site-packages/tensorflow/python/autograph/impl/api.py", line 166, in wrapper
), args, kwargs)
File "/usr/lib/envs/env-1923-ver-2635-a-4.2.9-py-3.5.3/lib/python3.5/site-packages/tensorflow/python/autograph/impl/api.py", line 340, in converted_call
if inspect_utils.isbuiltin(f):
File "/usr/lib/envs/env-1923-ver-2635-a-4.2.9-py-3.5.3/lib/python3.5/site-packages/tensorflow/python/autograph/pyct/inspect_utils.py", line 84, in isbuiltin
if f in six.moves.builtins.dict.values():
File "/usr/lib/envs/env-1923-ver-2635-a-4.2.9-py-3.5.3/lib/python3.5/site-packages/pandas/core/generic.py", line 1478, in nonzero
.format(self.class.name))
ValueError: The truth value of a DataFrame is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

**Describe the expected behavior**
The code snippet is expected to work.

Or please help point out what needs to be changed to make it work.

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.
```
from __future__ import absolute_import, division, print_function

import numpy as np
import pandas as pd

#!pip install tensorflow==2.0.0-alpha0
import tensorflow as tf

from tensorflow import feature_column
from tensorflow import keras
from tensorflow.keras import layers
from sklearn.model_selection import train_test_split

URL = 'https://storage.googleapis.com/applied-dl/heart.csv'
dataframe = pd.read_csv(URL)
dataframe.head()

train, test = train_test_split(dataframe, test_size=0.2)
train, val = train_test_split(train, test_size=0.2)
print(len(train), 'train examples')
print(len(val), 'validation examples')
print(len(test), 'test examples')

# A utility method to create a tf.data dataset from a Pandas Dataframe
def df_to_dataset(dataframe, shuffle=True, batch_size=32):
  dataframe = dataframe.copy()
  labels = dataframe.pop('target')
  ds = tf.data.Dataset.from_tensor_slices((dict(dataframe), labels))
  if shuffle:
    ds = ds.shuffle(buffer_size=len(dataframe))
  ds = ds.batch(batch_size)
  return ds

batch_size = 5 # A small batch sized is used for demonstration purposes
train_ds = df_to_dataset(train, batch_size=batch_size)
val_ds = df_to_dataset(val, shuffle=False, batch_size=batch_size)
test_ds = df_to_dataset(test, shuffle=False, batch_size=batch_size)

age = feature_column.numeric_column("age")

feature_columns = []
feature_layer_inputs = {}

# numeric cols
for header in ['age', 'trestbps', 'chol', 'thalach', 'oldpeak', 'slope', 'ca']:
  feature_columns.append(feature_column.numeric_column(header))
  feature_layer_inputs[header] = tf.keras.Input(shape=(1,), name=header)

# bucketized cols
age_buckets = feature_column.bucketized_column(age, boundaries=[18, 25, 30, 35, 40, 45, 50, 55, 60, 65])
feature_columns.append(age_buckets)

# indicator cols
thal = feature_column.categorical_column_with_vocabulary_list(
      'thal', ['fixed', 'normal', 'reversible'])
thal_one_hot = feature_column.indicator_column(thal)
feature_columns.append(thal_one_hot)
feature_layer_inputs['thal'] = tf.keras.Input(shape=(1,), name='thal', dtype=tf.string)

# embedding cols
thal_embedding = feature_column.embedding_column(thal, dimension=8)
feature_columns.append(thal_embedding)

# crossed cols
crossed_feature = feature_column.crossed_column([age_buckets, thal], hash_bucket_size=1000)
crossed_feature = feature_column.indicator_column(crossed_feature)
feature_columns.append(crossed_feature)

batch_size = 32
train_ds = df_to_dataset(train, batch_size=batch_size)
val_ds = df_to_dataset(val, shuffle=False, batch_size=batch_size)
test_ds = df_to_dataset(test, shuffle=False, batch_size=batch_size)

feature_layer = tf.keras.layers.DenseFeatures(feature_columns)
feature_layer_outputs = feature_layer(feature_layer_inputs)

x = layers.Dense(128, activation='relu')(feature_layer_outputs)
x = layers.Dense(64, activation='relu')(x)

baggage_pred = layers.Dense(1, activation='sigmoid')(x)

model = keras.Model(inputs=[v for v in feature_layer_inputs.values()], outputs=baggage_pred)

model.compile(optimizer='adam',
              loss='binary_crossentropy',
              metrics=['accuracy'])

model.fit(train_ds)
```
**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by karmel** [comment]
I can't seem to replicate this, and it's unclear what line the error message is coming from. Can you try again, and can you clarify what is triggering the error message?

For the record, output I get from the code above:

```
193 train examples
49 validation examples
61 test examples
7/7 [==============================] - 1s 162ms/step - loss: 2.4949 - accuracy: 0.5337
<google3.third_party.tensorflow.python.keras.callbacks.History at 0x7fb722d01ad0>
```

**Comment by HubberDev** [comment]
@karmel thanks for looking at this. That is strange.
Yes, I can still reproduce it from my zeppelin notebook. I traced the code a little bit to find the offending statement. Here is the minimal code snippets demonstrating the issue:

```
from __future__ import absolute_import, division, print_function

import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow import feature_column
from tensorflow import keras
from tensorflow.keras import layers
from sklearn.model_selection import train_test_split

print(np.__version__)
print(pd.__version__)
print(tf.__version__)

feature_columns = []
feature_layer_inputs = {}

age = feature_column.numeric_column("age")
feature_layer_inputs["age"] = keras.Input(shape=(1,), name="age")
feature_columns.append(age)

feature_layer = keras.layers.DenseFeatures(feature_columns)
feature_layer_outputs = feature_layer(feature_layer_inputs)
# x = layers.Dense(128, activation='relu')(feature_layer_outputs)
# y = layers.Dense(1, activation='sigmoid')(x)

# model = keras.Model(inputs=feature_layer_inputs, outputs=y)
```
The version of numpy, pandas, and tensorflow are as follows:
1.16.4
0.24.2
2.0.0-beta1

The offending column is
```
feature_layer_outputs = feature_layer(feature_layer_inputs)
```
The following is the starck trace:
Traceback (most recent call last):
  File "/tmp/zeppelin_pyspark-5407917517763439165.py", line 331, in <module>
    exec(code)
  File "<stdin>", line 7, in <module>
  File "/usr/lib/envs/env-1923-ver-2647-a-4.2.9-py-3.5.3/lib/python3.5/site-packages/tensorflow/python/keras/engine/base_layer.py", line 662, in __call__
    outputs = call_fn(inputs, *args, **kwargs)
  File "/usr/lib/envs/env-1923-ver-2647-a-4.2.9-py-3.5.3/lib/python3.5/site-packages/tensorflow/python/autograph/impl/api.py", line 166, in wrapper
    ), args, kwargs)
  File "/usr/lib/envs/env-1923-ver-2647-a-4.2.9-py-3.5.3/lib/python3.5/site-packages/tensorflow/python/autograph/impl/api.py", line 340, in converted_call
    if inspect_utils.isbuiltin(f):
  File "/usr/lib/envs/env-1923-ver-2647-a-4.2.9-py-3.5.3/lib/python3.5/site-packages/tensorflow/python/autograph/pyct/inspect_utils.py", line 84, in isbuiltin
    if f in six.moves.builtins.__dict__.values():
  File "/usr/lib/envs/env-1923-ver-2647-a-4.2.9-py-3.5.3/lib/python3.5/site-packages/pandas/core/generic.py", line 1478, in __nonzero__
    .format(self.__class__.__name__))
ValueError: The truth value of a DataFrame is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

**Comment by mahzoon** [comment]
@HubberDev The code (in the beginning of the issue) runs fine for me
```7/7 [==============================] - 1s 104ms/step - loss: 3.3066 - accuracy: 0.4560```
Also, the minimal code works fine.

Settings:
python 3.6.4
tf 2.0.0-beta1
I saved your code to a file and ran it by calling python (no notebooks).

**Comment by HubberDev** [comment]
Apparently, it worked on local machine as well with the same setting. Might be something wrong on my notebook setting.
@mahzoon thanks for confirming it.
Closing this ticket. Sorry for the false alarm.
