### ISSUE TITLE
`tf.GradientTape.gradient` returns `None` when `sources` is a tensor (not a variable)

### ISSUE THREAD

**Issue by jackd** [tensorflow/tensorflow#29942]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes (see below)
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): ubuntu 18.04
- TensorFlow installed from (source or binary): pip (tf-nightly-gpu)
- TensorFlow version (use command below): v1.12.1-3447-g5a0f1bbfb7 1.14.1-dev20190606
- Python version: 3.6.8 (anaconda)
- CUDA/cuDNN version: 10/7
- GPU model and memory: GTX 1050-ti

**Describe the current behavior**
`tf.GradientTape.gradient` is inconsistent with its documentation and `tf.gradients` when computing gradients with respect to tensors. It returns `None` rather than the partial derivative.

**Describe the expected behavior**
Behave as per `tf.gradients`.

**Code to reproduce the issue**
```python
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function

import tensorflow as tf

x0 = tf.get_variable('x0', shape=(), dtype=tf.float32)
x1 = tf.constant(3.)
x = x0 + x1
# x = tf.constant(3.0)
y = tf.constant(4.0)
with tf.GradientTape() as tape:
    z = x + y
    tape_grad = tape.gradient(z, x)
    print(tape_grad)  # None
tf_grad, = tf.gradients(z, x)

with tf.Session() as sess:
    print(sess.run(tf_grad))  # 1
```

**Comment by fps7806** [comment]
[GradientTape](https://www.tensorflow.org/api_docs/python/tf/GradientTape) doesn't automatically watch Tensors. You need to add `tape.watch(x)`
```
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function

import tensorflow as tf

x0 = tf.get_variable('x0', shape=(), dtype=tf.float32)
x1 = tf.constant(3.)
x = x0 + x1
# x = tf.constant(3.0)
y = tf.constant(4.0)
with tf.GradientTape() as tape:
    tape.watch(x)
    z = x + y
tape_grad = tape.gradient(z, x)
print(tape_grad)  # not None
tf_grad, = tf.gradients(z, x)

with tf.Session() as sess:
    print(sess.run(tf_grad))  # 1
```

**Comment by jackd** [comment]
My apologies, and thank you.

**Comment by sailormoon2016** [comment]
Hi @fps7806, I had similar problem, can you have a look at my code [issues #30190](https://github.com/tensorflow/tensorflow/issues/30190)? I added `tape.watch()`, checked my indentation and had my tensors included under the tape. Thanks!
