### ISSUE TITLE
cifar10_multi_gpu_train.py - unintended loss reporting

### ISSUE THREAD

**Issue by alrojo** [tensorflow/tensorflow#2994]
#cifar10_multi_gpu_train.py
At this [line](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/models/image/cifar10/cifar10_multi_gpu_train.py#L180), every loss for each tower in the multi GPU is calculated

However, these losses are not averaged, and it seems like the loss from the last GPU is used to return [loss](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/models/image/cifar10/cifar10_multi_gpu_train.py#L246).

Is this on purpose (if yes, why?) or is it a bug in the code?

**Comment by prb12** [comment]
This is a question better suited for StackOverflow. Please ask it there and tag it with the `tensorflow` tag.
