### ISSUE TITLE
TFLite Macro README instructions don't build. 

### ISSUE THREAD

**Issue by mehmetalianil** [tensorflow/tensorflow#29954]
The README.md file at https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/experimental/micro/README.md

indicates that a make call with test keyword will run all tests:
```
make -f tensorflow/lite/experimental/micro/tools/make/Makefile test
```
But this results in a syntax error:

```
~/tensorflow$ make -f tensorflow/lite/experimental/micro/tools/make/Makefile test
/bin/sh: 1: [[: not found
tensorflow/lite/experimental/micro/tools/make/download_and_extract.sh "http://mirror.tensorflow.org/github.com/google/flatbuffers/archive/v1.11.0.tar.gz" "02c64880acb89dbd57eebacfd67200d8" tensorflow/lite/experimental/micro/tools/make/downloads/flatbuffers 
downloading http://mirror.tensorflow.org/github.com/google/flatbuffers/archive/v1.11.0.tar.gz
tensorflow/lite/experimental/micro/tools/make/download_and_extract.sh: line 84: curl: command not found
tensorflow/lite/experimental/micro/tools/make/Makefile:198: recipe for target 'tensorflow/lite/experimental/micro/tools/make/downloads/flatbuffers' failed
make: *** [tensorflow/lite/experimental/micro/tools/make/downloads/flatbuffers] Error 127
```

In both my systems (Ubuntu 18.04 on WSL and Virtualmachine) make is defaulted to /bin/sh and not /bin/bash therefore `[[` is not interpreted. 

It is not an issue, but still, I thought the makefile would just work (TM). Many others might also, since it is indicated in README.
I the same line is available in the upcoming TinyML book, that is how I ran it.  
@petewarden 

![ezgif com-optimize (4)](https://user-images.githubusercontent.com/551129/59755686-a8fef700-9288-11e9-85aa-527d5d6d78e1.gif)

**Comment by wangtz** [comment]
Apart from [[ which sounds strange to me. [[ is a way in bash to express control flows. 

There is another error on curl:

tensorflow/lite/experimental/micro/tools/make/download_and_extract.sh: line 84: curl: command not found


Could you install curl and try again?

**Comment by petewarden** [comment]
Closing, since there's been no update for a while, and I believe installing curl should fix this.
