### ISSUE TITLE
Filling up shuffle buffer (this may take a while): 9544 of 10000

### ISSUE THREAD

**Issue by abdou31** [tensorflow/tensorflow#29957]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution: Windows 10 x64
- TensorFlow installed from (source or binary):binary
- TensorFlow version (use command below):1.13.1
- Python version:3.6
- CUDA/cuDNN version:10.0/7.4
- GPU model and memory: Nvidia Geforce 840m / 4.00 Go

I used CNN facial landmarks for training my own dataset , when I start training I get some lines :
> I tensorflow/core/kernels/data/shuffle_dataset_op.cc:101] Filling up shuffle buffer (this may take a while): 7024 of 10000
2019-06-19 12:02:24.102469: I tensorflow/core/kernels/data/shuffle_dataset_op.cc:101] Filling up shuffle buffer (this may take a while): 9544 of 10000

I want to know, are those lines meaning errors?
Thanks.

**Comment by ravikyram** [comment]
Can you please confirm whether you are getting expected results.Also, please share with us full code snippet to reproduce the issue reported here. Thanks!

**Comment by abdou31** [comment]
I used CNN facial landmark project :
+ https://github.com/yinguobing/cnn-facial-landmark
I have modified the code : 

+ [landmark.zip](https://github.com/tensorflow/tensorflow/files/3314778/landmark.zip)

**Comment by ravikyram** [comment]
I tried to reproduce the issue. It looks some datasets are missing to reproduce the issue.Request you to provide the datasets. Thanks.

**Comment by abdou31** [comment]
Did you mean upload datasets or just you want print their names?

**Comment by ravikyram** [comment]
Please upload the datasets for reproducing the issue. Thanks!

**Comment by abdou31** [comment]
Actually, I used many different datasets and their size is big (including whole images).
But I will give you examples of image:
![001_03](https://user-images.githubusercontent.com/19480228/60178668-60ad7f00-981c-11e9-9941-b83052b0b369.jpg)
![image_0010](https://user-images.githubusercontent.com/19480228/60178714-6d31d780-981c-11e9-8ff9-5112e2a7edf9.jpg)

**Comment by ravikyram** [comment]
I tried reproducing the issue with the above image placed in testiriss.record folder but i am getting the below error.Thanks! 

FailedPreconditionError (see above for traceback): testiriss.record; Is a directory [[node IteratorGetNext (defined at <ipython-input-4-ecad13bca4e7>:249) ]]

**Comment by abdou31** [comment]
What command you execute?

**Comment by ravikyram** [comment]
I have tried executing the code(landmark.py) given by you by placing the image in testiriss.record folder.Thanks!

**Comment by abdou31** [comment]
You should followed some instructions before executing landmark.py

**Comment by ymodak** [comment]
Apologies for the delay in response. Those are log info and not errors. See https://github.com/tensorflow/tensorflow/blob/42b5da6659a75bfac77fa81e7242ddb5be1a576a/tensorflow/core/kernels/data/shuffle_dataset_op.cc#L138

**Comment by abdou31** [comment]
@ymodak, Thanks for your answer

**Comment by nashid** [comment]
@ymodak thanks - but what this log means?
