### ISSUE TITLE
Which license must be provided with my application when using the tensorflow C API?

### ISSUE THREAD

**Issue by dagophil** [tensorflow/tensorflow#29953]
I am developing a commercial application that uses the tensorflow C API. At all kinds of places, for example, https://github.com/tensorflow/tensorflow/blob/master/LICENSE, I found that tensorflow uses the Apache License 2.0. However, when I downloaded the C API from https://www.tensorflow.org/install/lang_c (https://storage.googleapis.com/tensorflow/libtensorflow/libtensorflow-cpu-windows-x86_64-1.13.1.zip) it came with a huge LICENSE file that lists many 3rd party libraries.

Which license do I need to distribute with my application? Do I need to add the Apache License 2.0 for tensorflow or do I need to add the content of the LICENSE file that came with the C API?

**Comment by dagophil** [comment]
Has there been any progress on this issue? I still do not know which license I need to distribute with an application that uses the tensorflow C API.

**Comment by MarkDaoust** [comment]
Hi @dagophil, 

Our license is in [LICENSE](https://github.com/tensorflow/tensorflow/blob/master/LICENSE).

Beyond that, we can't provide any legal advice.  You may want to consult your own counsel if you have questions.

Good luck.
