### ISSUE TITLE
tf.contrib.layers.group_norm() Error: Failed to convert object

### ISSUE THREAD

**Issue by MaeThird** [tensorflow/tensorflow#29961]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):  Linux  CentOS 3.10.0-693.2.2.el7.x86_64
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): b'v1.13.1-0-g6612da8951' 1.13.1
- Python version: python3.6
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source): gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-36)
- CUDA/cuDNN version: cuda-10.0, cudnn-7.6
- GPU model and memory: 16G(Nvidia-P100)

this is the repost from:[issues](29636)

**Comment by achandraa** [comment]
Looks like a known issue. Please have a look on #24409 discussion regarding the same and let us know if that resolves the problem. Thanks!

**Comment by achandraa** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
