### ISSUE TITLE
TypeError: moments_v2() got an unexpected keyword argument 'keep_dims'

### ISSUE THREAD

**Issue by zsdonghao** [tensorflow/tensorflow#29963]
TypeError: moments_v2() got an unexpected keyword argument 'keep_dims'

**Comment by gadagashwini** [comment]
@zsdonghao Can you provide more details about issue and context. Thanks!

**Comment by zsdonghao** [comment]
fixed by changing to `keepdims` , the online docs of TF need to be updated!!!
