### ISSUE TITLE
AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'decode'

### ISSUE THREAD

**Issue by aalok1993** [tensorflow/tensorflow#29972]
I am using tensorflow on python 3.7, Ubuntu 16.04. The code which throws the above mentioned error is written below. It is based on the following [code](https://www.tensorflow.org/guide/datasets#applying_arbitrary_python_logic_with_tfpy_func). I am getting this error on both tensorflow 1.13 as well as 2.0.0-beta1

I have a dataset folder containing millions of data pair of the form (image,timeseries). The timeseries is in numpy format. I want to use np.load() function to load the data. But the filename is in string tensor format. np.load() does not accept tensorflow.python.framework.ops.EagerTensor

	import tensorflow as tf
	import numpy as np
	import imageio

	#tf.enable_eager_execution()    # use this line if using tensorflow 1.13

	imageio.imwrite('data.jpg', np.random.rand(256,256,3))
	np.save('data.npy',np.ones(1024))

	def load(image_file,timeseries_file):
	  image = tf.io.read_file(image_file)
	  image = tf.image.decode_jpeg(image)
	  timeseries = np.load(timeseries_file.decode())
	  timeseries = tf.convert_to_tensor(timeseries, np.float32)
	  image = tf.cast(image, tf.float32)
	  timeseries = tf.cast(timeseries, tf.float32)
	  return image, timeseries

	image_files = ['data.jpg']
	timeseries_files = ['data.npy']
	train_dataset = tf.data.Dataset.from_tensor_slices((image_files, timeseries_files))
	train_dataset = train_dataset.map(
	    lambda image_file, timeseries_file: tuple(tf.py_function(
	        load, [image_file, timeseries_file], [tf.float32, tf.float32])))
	for x in train_dataset.take(1):
		print(x)

**Comment by martinwicke** [comment]
You need to add `.numpy()` if you want to use the result of a TensorFlow computation directly (i.e., in your case, to get the string from the `EagerTensor`, which you call `.decode` on).

**Comment by liuzhiwei1997** [comment]
hi，Do you have solved this problem?I ran into the same problem

**Comment by abhisheknagarajan** [comment]
I have a following program:

from PIL import Image
import numpy as np
from skimage import transform

model2 = load_model('ip_classification.hdf5')

def accept_bright(custom_img):
    
    # Bright Accept Images
    contrast = cv2.convertScaleAbs(custom_img, alpha=1, beta=100)
    blurred = cv2.GaussianBlur(contrast, (7, 7), 0)
    thresh = cv2.threshold(blurred, 225, 255, cv2.THRESH_BINARY)[1]
    thresh = cv2.erode(thresh, None, iterations=3)
    thresh = cv2.dilate(thresh, None, iterations=5)
    return thresh

def accept_low(custom_img):
    
    # Low Accept Images
    contrast = cv2.convertScaleAbs(custom_img, alpha=1, beta=110)
    blurred = cv2.GaussianBlur(contrast, (5, 5), 0)
    thresh = cv2.threshold(blurred, 200, 255, cv2.THRESH_BINARY)[1]
    thresh = cv2.erode(thresh, None, iterations=5)
    thresh = cv2.dilate(thresh, None, iterations=5)
    return thresh

def reject_bright(custom_img):
    
    # Bright Reject Images
    contrast = cv2.convertScaleAbs(custom_img, alpha=1, beta=60)
    blurred = cv2.GaussianBlur(contrast, (7, 7), 0)
    thresh = cv2.threshold(blurred, 180, 255, cv2.THRESH_BINARY)[1]
    thresh = cv2.erode(thresh, None, iterations=7)
    thresh = cv2.dilate(thresh, None, iterations=3)
    return thresh

def reject_low(custom_img):
    
    # Dark Reject Images
    contrast = cv2.convertScaleAbs(custom_img, alpha=1, beta=50)
    blurred = cv2.GaussianBlur(contrast, (3, 3), 0)
    thresh = cv2.threshold(blurred, 150, 255, cv2.THRESH_BINARY)[1]
    thresh = cv2.erode(thresh, None, iterations=7)
    thresh = cv2.dilate(thresh, None, iterations=3)
    return thresh

def load(img):
    threshold = 140
    if np.mean(img) > threshold:
        #image = Image.open(img)
        images = image.convert(mode = 'L')
        image_np = np.array(images)
        sharp = np.array([[0, -1, 0], [-1, 5, -1], [0, -1, 0]])       # sharpening the image
        custom_img = cv2.filter2D(image_np,-1,sharp)
        
        # Blob implementation
        detector = cv2.SimpleBlobDetector_create()
        # Detect blobs.
        keypoints = detector.detect(custom_img)
        num_blobs = len(keypoints)
        if num_blobs > 0:
            w = reject_bright(custom_img)
            np_image = Image.fromarray(w)
            np_image = np.array(np_image).astype('float32')/255
            np_image = transform.resize(np_image, (256, 256, 1))
            np_image = np.expand_dims(np_image, axis=0)                  # (1,256,256,1)
            return np_image
        else:
            x = accept_bright(custom_img)
            np_image = Image.fromarray(x)
            np_image = np.array(np_image).astype('float32')/255
            np_image = transform.resize(np_image, (256, 256, 1))
            np_image = np.expand_dims(np_image, axis=0)                  # (1,256,256,1)
            return np_image
        
    elif np.mean(img) < threshold:
        #image = Image.open(img)
        images = image.convert(mode = 'L')
        image_np = np.array(images)
        sharp = np.array([[0, -1, 0], [-1, 5, -1], [0, -1, 0]])       # sharpening the image
        custom_img = cv2.filter2D(image_np,-1,sharp)
        # Blob implementation
        detector = cv2.SimpleBlobDetector_create()
        # Detect blobs.
        keypoints = detector.detect(custom_img)
        num_blobs = len(keypoints)
        if num_blobs > 0:
            y = reject_low(custom_img)
            np_image = Image.fromarray(y)
            np_image = np.array(np_image).astype('float32')/255
            np_image = transform.resize(np_image, (256, 256, 1))
            np_image = np.expand_dims(np_image, axis=0)                  # (1,256,256,1)
            return np_image
        else:
            z = accept_low(custom_img)
            np_image = Image.fromarray(z)
            np_image = np.array(np_image).astype('float32')/255
            np_image = transform.resize(np_image, (256, 256, 1))
            np_image = np.expand_dims(np_image, axis=0)                  # (1,256,256,1)
            return np_image


inp = Image.open('C:\\Users\\nabhishe\\MITC_Project\\RGB_compiled_images\\Reject-A26491-001-Sample - 74-2.jpg')
image2 = load(inp)
label = model2.predict(image2)
plt.imshow(image2.reshape(256,256),cmap='gray')
plt.show()
print("Predicted Class (0 - Accept , 1 - Reject): ", label[0][0])

Error:
AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'convert'

can someone help me with this
