### ISSUE TITLE
custom filter with tf.nn.conv2d

### ISSUE THREAD

**Issue by halbaqshi** [tensorflow/tensorflow#29974]
I want to build spiking convolution in tensor flow like tf.nn.conv2d. 
spiking convolution is like normal convolution but filter is depend on previous filter on the same layrt . so in each one layer the filter will be updated based on pre-neuron or output of previous neuron.

for example. I have input x & convolution c
x=
1  2   3
3  3   2
2  2   4

c= 
1  1  1
1  1  1
1  1  1
after i apply spiking 
the first neuron will be like normal CNN
1 x 0+1 x 0+1 x 0+1 x 0+1 x 1+1 x 2+1 x 0+1 x 3+1 x 3=9
but second neuron neuron in CNN will be
1 x 0+1 x 0+1 x 0+1 x 1+1 x 2+1 x 3+1 x 3+1 x 3+1 x 2=14
where in Spiking CNN the second neuron wil be
9+14
because the formula for spiking cnn to calculate neuron(i) will be equal to { normal cnn for neuron(i) + cnn for neuron(i-1) }

for more details 
visit:
https://arxiv.org/pdf/1703.03854.pdf

https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0204596

**Comment by gadagashwini** [comment]
Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version. Also, did you compile from source or install a binary?

Make sure you also include the exact command if possible to produce the output included in your test case. If you are unclear what to include see the issue template displayed in [the Github new issue template](https://github.com/tensorflow/tensorflow/issues/new/choose).

We ask for this in the issue submission template, because it is really difficult to help without that information. Thanks!

**Comment by halbaqshi** [comment]
I'm using anaconda with Python 3.7 on Windows 10, tensorflow 1.12
I installed it using pip
The function tf.nn.conv2d it perform normal convolution with correct results but I want to do custom convolution so each filter is change for each vector or neuron

**Comment by gadagashwini** [comment]
@halbaqshi In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thanks!

**Comment by halbaqshi** [comment]
This is the snippet of code and the output

![image](https://user-images.githubusercontent.com/52009924/59860601-e0080200-9387-11e9-815a-996aea5c804a.png)


![image](https://user-images.githubusercontent.com/52009924/59860639-f8781c80-9387-11e9-99a7-39c6d6a6a893.png)


insted of convolution as shown in the out put I want to convert to spiking to neuron network like below

![image](https://user-images.githubusercontent.com/52009924/59860989-9f5cb880-9388-11e9-862d-0094111d124b.png)


and the issue is 
![image](https://user-images.githubusercontent.com/52009924/59861028-b4394c00-9388-11e9-8f86-69d6179c0090.png)

**Comment by halbaqshi** [comment]
pr like this 

![image](https://user-images.githubusercontent.com/52009924/59861213-0c704e00-9389-11e9-8765-1bee6dec8d25.png)

**Comment by gadagashwini** [comment]
@halbaqshi Please provide us the complete executable code in order to expedite the trouble-shooting process.Thanks!

**Comment by halbaqshi** [comment]
M code is too long and is related to database and machine learning to train data. I `ll give you simple example with numbers

`import tensorflow as tf
inpu= tf.Variable([5,8,2,7,3,4,5,9,8.0])
inpu=tf.reshape(inpu,[-1,3,3,1])
filte=tf.Variable([1,1,1,1,1,1,1,1,1.0])
filte=tf.reshape(filte,[3,3,1,-1])
first_conv = tf.nn.conv2d(inpu, filte, [1, 1, 1,1],'SAME') 
first_conv2=tf.reshape(first_conv,[3*3])
cc=tf.shape([9])
cc[0]=tf.Variable(first_conv2[0])
for i in (1,np.array(first_conv2).shape):
    cc[i]=tf.add(first_conv2[i],fcc[i-1])
cc=tf.reshape(cc,[-1,3,3,1])
second_conv = tf.nn.conv2d(cc, filte, [1, 1, 1,1],'SAME') 
second_conv2=tf.reshape(second_conv,[3*3])
sess=tf.InteractiveSession()
tf.global_variables_initializer().run()
print(sess.run(inpu))
print(sess.run(filte))
print(sess.run(first_conv))`

**Comment by halbaqshi** [comment]
![image](https://user-images.githubusercontent.com/52009924/59972210-c509dd80-9593-11e9-8d3d-26530a114b65.png)

**Comment by gadagashwini** [comment]
I am able to reproduce the issue on Colab with Tensorflow 1.12.0.

**Comment by Leslie-Fang** [comment]
@halbaqshi 
Could substitute this slice of code  in yours:
```
import numpy as np
#cc=tf.shape([9])
cc=tf.Variable(tf.zeros(3*3, tf.float32))
#cc[0]=tf.Variable(first_conv2[0])

cc[0].assign(first_conv2[0])

for i in range(1,cc.shape[0]):
    #cc[i]=tf.add(first_conv2[i],cc[i-1])
    #tf.add(first_conv2[i], cc[i - 1])
    cc[i].assign(tf.add(first_conv2[i], cc[i - 1]))
```

**Comment by halbaqshi** [comment]
@Leslie-Fang 
look at the issue below after I applied your suggestion

code:

`import tensorflow as tf
def create_conv_model():
    is_training=True
    if is_training:dropout_prob = tf.placeholder(tf.float32, name='dropout_prob')
    input_frequency_size = 40
    input_time_size = 98
    fingerprint_size=3920
    fingerprint_input = tf.placeholder(tf.float32, [None, fingerprint_size], name='fingerprint_input')
    fingerprint_4d = tf.reshape(fingerprint_input,[-1, input_time_size, input_frequency_size, 1])
    first_filter_width = 8
    first_filter_height = 20
    first_filter_count = 64
    first_weights = tf.Variable(tf.truncated_normal([first_filter_height, first_filter_width, 1, first_filter_count],stddev=0.01))
    first_bias = tf.Variable(tf.zeros([first_filter_count]))
    first_conv = tf.nn.conv2d(fingerprint_4d, first_weights, [1, 1, 1, 1],'SAME') + first_bias
    first_conv2=tf.reshape(first_conv,[input_time_size*input_frequency_size*64])
    cc=tf.Variable(tf.zeros(input_time_size*input_frequency_size*64, tf.float32))
    cc[0].assign(first_conv2[0])
    for i in (1,input_time_size*input_frequency_size*64):
        cc[i].assign(tf.add(first_conv2[i], cc[i - 1]))
    first_conv=tf.reshape(cc,[-1, input_time_size, input_frequency_size, 64])
    first_relu = tf.nn.relu(first_conv)
    if is_training:first_dropout = tf.nn.dropout(first_relu, dropout_prob)
    else:first_dropout = first_relu
    max_pool = tf.nn.max_pool(first_dropout, [1, 2, 2, 1], [1, 2, 2, 1], 'SAME')
    second_filter_width = 4
    second_filter_height = 10
    second_filter_count = 64
    second_weights = tf.Variable(tf.truncated_normal([second_filter_height, second_filter_width, first_filter_count,second_filter_count],stddev=0.01))
    second_bias = tf.Variable(tf.zeros([second_filter_count]))
    second_conv = tf.nn.conv2d(max_pool, second_weights, [1, 1, 1, 1],'SAME') + second_bias
    second_relu = tf.nn.relu(second_conv)
    if is_training:second_dropout = tf.nn.dropout(second_relu, dropout_prob)
    else:second_dropout = second_relu
    second_conv_shape = second_dropout.get_shape()
    second_conv_output_width = second_conv_shape[2]
    second_conv_output_height = second_conv_shape[1]
    second_conv_element_count = int(second_conv_output_width * second_conv_output_height *second_filter_count)
    flattened_second_conv = tf.reshape(second_dropout,[-1, second_conv_element_count])
    label_count = model_settings['label_count']
    final_fc_weights = tf.Variable(tf.truncated_normal([second_conv_element_count, label_count], stddev=0.01))
    final_fc_bias = tf.Variable(tf.zeros([label_count]))
    final_fc = tf.matmul(flattened_second_conv, final_fc_weights) + final_fc_bias
    if is_training:return final_fc, dropout_prob
    else:return final_fc
create_conv_model()`

issue

---------------------------------------------------------------------------
InvalidArgumentError                      Traceback (most recent call last)
~\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow\python\framework\ops.py in _create_c_op(graph, node_def, inputs, control_inputs)
   1575   try:
-> 1576     c_op = c_api.TF_FinishOperation(op_desc)
   1577   except errors.InvalidArgumentError as e:

InvalidArgumentError: slice index 250880 of dimension 0 out of bounds. for 'strided_slice_12' (op: 'StridedSlice') with input shapes: [250880], [1], [1], [1] and with computed input tensors: input[1] = <250880>, input[2] = <250881>, input[3] = <1>.

During handling of the above exception, another exception occurred:

ValueError                                Traceback (most recent call last)
<ipython-input-5-988f602eae47> in <module>
     44     if is_training:return final_fc, dropout_prob
     45     else:return final_fc
---> 46 create_conv_model()

<ipython-input-5-988f602eae47> in create_conv_model()
     18     cc[0].assign(first_conv2[0])
     19     for i in (1,input_time_size*input_frequency_size*64):
---> 20         cc[i].assign(tf.add(first_conv2[i], cc[i - 1]))
     21     first_conv=tf.reshape(cc,[-1, input_time_size, input_frequency_size, 64])
     22     first_relu = tf.nn.relu(first_conv)

~\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow\python\ops\array_ops.py in _SliceHelperVar(var, slice_spec)
    762   """
    763 
--> 764   return _slice_helper(var._AsTensor(), slice_spec, var)
    765 
    766 

~\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow\python\ops\array_ops.py in _slice_helper(tensor, slice_spec, var)
    522         ellipsis_mask=ellipsis_mask,
    523         var=var,
--> 524         name=name)
    525 
    526 

~\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow\python\ops\array_ops.py in strided_slice(input_, begin, end, strides, begin_mask, end_mask, ellipsis_mask, new_axis_mask, shrink_axis_mask, var, name)
    688       ellipsis_mask=ellipsis_mask,
    689       new_axis_mask=new_axis_mask,
--> 690       shrink_axis_mask=shrink_axis_mask)
    691 
    692   parent_name = name

~\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow\python\ops\gen_array_ops.py in strided_slice(input, begin, end, strides, begin_mask, end_mask, ellipsis_mask, new_axis_mask, shrink_axis_mask, name)
  10185         begin_mask=begin_mask, end_mask=end_mask, ellipsis_mask=ellipsis_mask,
  10186         new_axis_mask=new_axis_mask, shrink_axis_mask=shrink_axis_mask,
> 10187         name=name)
  10188     _result = _op.outputs[:]
  10189     _inputs_flat = _op.inputs

~\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow\python\framework\op_def_library.py in _apply_op_helper(self, op_type_name, name, **keywords)
    785         op = g.create_op(op_type_name, inputs, output_types, name=scope,
    786                          input_types=input_types, attrs=attr_protos,
--> 787                          op_def=op_def)
    788       return output_structure, op_def.is_stateful, op
    789 

~\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow\python\util\deprecation.py in new_func(*args, **kwargs)
    452                 'in a future version' if date is None else ('after %s' % date),
    453                 instructions)
--> 454       return func(*args, **kwargs)
    455     return tf_decorator.make_decorator(func, new_func, 'deprecated',
    456                                        _add_deprecated_arg_notice_to_docstring(

~\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow\python\framework\ops.py in create_op(***failed resolving arguments***)
   3153           input_types=input_types,
   3154           original_op=self._default_original_op,
-> 3155           op_def=op_def)
   3156       self._create_op_helper(ret, compute_device=compute_device)
   3157     return ret

~\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow\python\framework\ops.py in __init__(self, node_def, g, inputs, output_types, control_inputs, input_types, original_op, op_def)
   1729           op_def, inputs, node_def.attr)
   1730       self._c_op = _create_c_op(self._graph, node_def, grouped_inputs,
-> 1731                                 control_input_ops)
   1732 
   1733     # Initialize self._outputs.

~\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow\python\framework\ops.py in _create_c_op(graph, node_def, inputs, control_inputs)
   1577   except errors.InvalidArgumentError as e:
   1578     # Convert to ValueError for backwards compatibility.
-> 1579     raise ValueError(str(e))
   1580 
   1581   return c_op

ValueError: slice index 250880 of dimension 0 out of bounds. for 'strided_slice_12' (op: 'StridedSlice') with input shapes: [250880], [1], [1], [1] and with computed input tensors: input[1] = <250880>, input[2] = <250881>, input[3] = <1>.

**Comment by halbaqshi** [comment]
@Leslie-Fang still not working, for more details check below:

code:

`import tensorflow as tf
def create_SNN_conv_model(fingerprint_input,fweights,  is_training):
    if is_training:dropout_prob = tf.placeholder(tf.float32, name='dropout_prob')
    input_frequency_size =40
    input_time_size =98
    fingerprint_4d = tf.reshape(fingerprint_input,[-1, input_time_size, input_frequency_size, 1])
    first_weights=fweights
    first_filter_count=64
    first_bias = tf.Variable(tf.zeros([first_filter_count]))
    first_conv = tf.nn.conv2d(fingerprint_4d, first_weights, [1, 1, 1, 1],'SAME') + first_bias
    first_conv2=tf.reshape(first_conv,[-1,first_conv.get_shape()[1]*first_conv.get_shape()[2] ])
    cc= tf.placeholder(tf.float32, shape=(first_conv.get_shape()[1]*first_conv.get_shape()[2]), name='cc')
    cc[0].assign(first_conv2[0])
    for i in (1,first_conv.get_shape()[1]*first_conv.get_shape()[2]): 
        cc[i].assign(tf.add(first_conv2[i], cc[i - 1]))
    first_conv=tf.reshape(cc,[-1, input_time_size, input_frequency_size, 64])
    first_relu = tf.nn.relu(first_conv)
    if is_training:first_dropout = tf.nn.dropout(first_relu, dropout_prob)
    else:first_dropout = first_relu
    max_pool = tf.nn.max_pool(first_dropout, [1, 2, 2, 1], [1, 2, 2, 1], 'SAME')
    first_conv_shape = first_dropout.get_shape()
    first_conv_output_width = first_conv_shape[2]
    first_conv_output_height = first_conv_shape[1]
    first_conv_element_count = int(first_conv_output_width * first_conv_output_height *first_filter_count)
    flattened_first_conv = tf.reshape(first_dropout,[-1, first_conv_element_count])
    label_count = model_settings['label_count']
    final_fc_weights = tf.Variable(tf.truncated_normal([first_conv_element_count, label_count], stddev=0.01))
    final_fc_bias = tf.Variable(tf.zeros([label_count]))
    final_fc = tf.matmul(flattened_first_conv, final_fc_weights) + final_fc_bias
    if is_training:return final_fc, dropout_prob
    else:return final_fc
sess=tf.InteractiveSession()
fingerprint_input = tf.placeholder(tf.float32, [None, fingerprint_size], name='fingerprint_input')
ground_truth_input = tf.placeholder(tf.float32, [None, label_count], name='groundtruth_input')
first_weights = tf.placeholder(tf.float32, name='first_weights')
logits, dropout_prob = create_SNN_conv_model(fingerprint_input,first_weights,is_training=True)
    `

and issue is
`

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-5-ced944478b6b> in <module>
     34 ground_truth_input = tf.placeholder(tf.float32, [None, label_count], name='groundtruth_input')
     35 first_weights = tf.placeholder(tf.float32, name='first_weights')
---> 36 logits, dropout_prob = create_SNN_conv_model(fingerprint_input,first_weights,is_training=True)
     37 

<ipython-input-5-ced944478b6b> in create_SNN_conv_model(fingerprint_input, fweights, is_training)
     11     first_conv2=tf.reshape(first_conv,[-1,first_conv.get_shape()[1]*first_conv.get_shape()[2] ])
     12     cc= tf.placeholder(tf.float32, shape=(first_conv.get_shape()[1]*first_conv.get_shape()[2]), name='cc')
---> 13     cc[0].assign(first_conv2[0])
     14     for i in (1,first_conv.get_shape()[1]*first_conv.get_shape()[2]):
     15         cc[i].assign(tf.add(first_conv2[i], cc[i - 1]))

~\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow\python\ops\array_ops.py in assign(val, name)
    696 
    697     if var is None:
--> 698       raise ValueError("Sliced assignment is only supported for variables")
    699 
    700     if name is None:

ValueError: Sliced assignment is only supported for variables`
>

**Comment by halbaqshi** [comment]
try to run the last code in your device

**Comment by halbaqshi** [comment]
I also tried this code and got other issue

    import tensorflow as tf
    def create_SNN_conv_model(fingerprint_input,fweights,  is_training):
      if is_training:dropout_prob = tf.placeholder(tf.float32, name='dropout_prob')
      input_frequency_size =40
      input_time_size =98
      fingerprint_4d = tf.reshape(fingerprint_input,[-1, input_time_size, input_frequency_size, 1])
      first_weights=fweights
      first_filter_count=64
      first_bias = tf.Variable(tf.zeros([first_filter_count]))
      first_conv = tf.nn.conv2d(fingerprint_4d, first_weights, [1, 1, 1, 1],'SAME') + first_bias
      first_conv2=tf.reshape(first_conv,[None,first_conv.get_shape()[1]*first_conv.get_shape()[2] ])
      cc= tf.placeholder(tf.float32, shape=(None,first_conv.get_shape()[1]*first_conv.get_shape()[2]), name='cc')
      cc[0]=tf.assign(first_conv2[0])
      for i in (1,first_conv.get_shape()[1]*first_conv.get_shape()[2]): 
          cc[i]=tf.assign(tf.add(first_conv2[i], cc[i - 1]))
      first_conv=tf.reshape(cc,[-1, input_time_size, input_frequency_size, 64])
      first_relu = tf.nn.relu(first_conv)
      if is_training:first_dropout = tf.nn.dropout(first_relu, dropout_prob)
      else:first_dropout = first_relu
      max_pool = tf.nn.max_pool(first_dropout, [1, 2, 2, 1], [1, 2, 2, 1], 'SAME')
      first_conv_shape = first_dropout.get_shape()
      first_conv_output_width = first_conv_shape[2]
      first_conv_output_height = first_conv_shape[1]
      first_conv_element_count = int(first_conv_output_width * first_conv_output_height *first_filter_count)
      flattened_first_conv = tf.reshape(first_dropout,[-1, first_conv_element_count])
      label_count = model_settings['label_count']
      final_fc_weights = tf.Variable(tf.truncated_normal([first_conv_element_count, label_count], stddev=0.01))
      final_fc_bias = tf.Variable(tf.zeros([label_count]))
      final_fc = tf.matmul(flattened_first_conv, final_fc_weights) + final_fc_bias
      if is_training:return final_fc, dropout_prob
      else:return final_fc
   sess=tf.InteractiveSession()
  fingerprint_input = tf.placeholder(tf.float32, [None, fingerprint_size], name='fingerprint_input')
  ground_truth_input = tf.placeholder(tf.float32, [None, label_count], name='groundtruth_input')
  first_weights = tf.placeholder(tf.float32, name='first_weights')
  logits, dropout_prob = create_SNN_conv_model(fingerprint_input,first_weights,is_training=True)

**Comment by halbaqshi** [comment]
also I tried to use tf.scatter_spdate and find other issue, for details:

code:

    import tensorflow as tf
    def create_SNN_conv_model(fingerprint_input,first_weights, is_training):
        input_frequency_size =40
        input_time_size = 98
        if is_training:dropout_prob = tf.placeholder(tf.float32, name='dropout_prob')
        fingerprint_4d = tf.reshape(fingerprint_input,[-1, input_time_size, input_frequency_size, 1])
        first_weights=first_weights
        first_filter_count=64
        first_bias = tf.Variable(tf.zeros([first_filter_count]))
        first_conv = tf.nn.conv2d(fingerprint_4d, first_weights, [1, 1, 1, 1],'SAME') + first_bias
        first_conv2=tf.reshape(first_conv,[tf.shape(first_conv)[0],first_conv.get_shape()[1]*first_conv.get_shape()[2]*first_conv.get_shape()[3]])
        cc = tf.reshape(first_conv2,[tf.shape(first_conv)[0], first_conv2.get_shape()[1]])
        cc=tf.scatter_update(cc,[tf.shape(first_conv2)[0],0],first_conv2[tf.shape(first_conv2)[0],0])
        k=(first_conv.get_shape()[1]*first_conv.get_shape()[2]*first_conv.get_shape()[3])-1
        for i in range(1,k): 
            cc=tf.scatter_update(cc,[tf.shape(first_conv2)[0],i],tf.add(first_conv2[tf.shape(first_conv2)[0],0],cc[tf.shape(first_conv2)[0]:i - 1]))
        first_conv=tf.reshape(cc,[tf.shape(first_conv)[0],first_conv.get_shape()[1],first_conv.get_shape()[2],first_conv.get_shape()[3]])
        first_relu = tf.nn.relu(first_conv)
        if is_training:first_dropout = tf.nn.dropout(first_relu, dropout_prob)
        else:first_dropout = first_relu
        #max_pool = tf.nn.max_pool(first_dropout, [1, 2, 2, 1], [1, 2, 2, 1], 'SAME')
        first_conv_shape = first_dropout.get_shape()
        first_conv_output_width = first_conv_shape[1]
        first_conv_output_height = first_conv_shape[0]
        first_conv_output_count = first_conv_shape[2]
        first_conv_element_count = int(first_conv_output_width * first_conv_output_height*first_conv_output_count)
        flattened_first_conv = tf.reshape(first_dropout,[-1, first_conv_element_count])
        label_count = 9
        final_fc_weights = tf.Variable(tf.truncated_normal([first_conv_element_count, label_count], stddev=0.01))
        final_fc_bias = tf.Variable(tf.zeros([label_count]))
        final_fc = tf.matmul(flattened_first_conv, final_fc_weights) + final_fc_bias
        if is_training:return final_fc, dropout_prob
        else:return final_fc
    first_filter_width = 8
    first_filter_height = 20
    first_filter_count = 64
    first_weights = tf.Variable(tf.truncated_normal([first_filter_height, first_filter_width, 1, first_filter_count],stddev=0.01))    
    fingerprint_input = tf.placeholder(tf.float32, [None, 3920], name='fingerprint_input')
    create_SNN_conv_model(fingerprint_input,first_weights, is_training=True)
    sess=tf.InteractiveSession()
    tf.global_variables_initializer().run()
    print(sess.run(foo))

issue:

    ---------------------------------------------------------------------------
    AttributeError                            Traceback (most recent call last)
    <ipython-input-6-bcffbcb02f7a> in <module>
         37 first_weights = tf.Variable(tf.truncated_normal([first_filter_height, first_filter_width, 1, first_filter_count],stddev=0.01))
         38 fingerprint_input = tf.placeholder(tf.float32, [None, 3920], name='fingerprint_input')
    ---> 39 create_SNN_conv_model(fingerprint_input,first_weights, is_training=True)
         40 sess=tf.InteractiveSession()
         41 tf.global_variables_initializer().run()

    <ipython-input-6-bcffbcb02f7a> in create_SNN_conv_model(fingerprint_input, first_weights, is_training)
         11     first_conv2=tf.reshape(first_conv,[tf.shape(first_conv)[0],first_conv.get_shape()[1]*first_conv.get_shape()[2]*first_conv.get_shape()[3]])
         12     cc = tf.reshape(first_conv2,[tf.shape(first_conv)[0], first_conv2.get_shape()[1]])
    ---> 13     cc=tf.scatter_update(cc,[tf.shape(first_conv2)[0],0],first_conv2[tf.shape(first_conv2)[0],0])
         14     k=(first_conv.get_shape()[1]*first_conv.get_shape()[2]*first_conv.get_shape()[3])-1
         15     for i in range(1,k):

    ~\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow\python\ops\state_ops.py in scatter_update(ref, indices, updates, use_locking, name)
        290     return gen_state_ops.scatter_update(ref, indices, updates,
        291                                         use_locking=use_locking, name=name)
    --> 292   return ref._lazy_read(gen_resource_variable_ops.resource_scatter_update(  # pylint: disable=protected-access
        293       ref.handle, indices, ops.convert_to_tensor(updates, ref.dtype),
        294       name=name))

    AttributeError: 'Tensor' object has no attribute '_lazy_read'

**Comment by halbaqshi** [comment]
I want to solve at least one of these code

**Comment by halbaqshi** [comment]
I want to run any one of the previous code

**Comment by halbaqshi** [comment]
any help??
@gadagashwini 
@Leslie-Fang 
@tensorflowbutler 
@jvishnuvardhan

**Comment by jvishnuvardhan** [comment]
@halbaqshi The error [here](https://github.com/tensorflow/tensorflow/issues/29974#issuecomment-504722486) is as expected. As `cc` is a tensor object, it doesn't allow item assignment. You need to create a list for that purpose. Thanks!

**Comment by halbaqshi** [comment]
When I update the code like below it worked fine for building the model but while training it give me an error which is slide with dimensions 100 is out of bounds and it refers to cc.append

To see the code :
 
    create_conv_model(fingerprint_input, model_settings, is_training):
if is_training:dropout_prob = tf.placeholder(tf.float32, name='dropout_prob')
input_frequency_size = model_settings['dct_coefficient_count']
input_time_size = model_settings['spectrogram_length']
fingerprint_4d = tf.reshape(fingerprint_input,[-1, input_time_size, input_frequency_size, 1])
first_filter_width = 8
first_filter_height = 20
first_filter_count = 64
first_weights = tf.Variable(tf.truncated_normal([first_filter_height, first_filter_width, 1, first_filter_count],stddev=0.01))
first_bias = tf.Variable(tf.zeros([first_filter_count]))
first_conv = tf.nn.conv2d(fingerprint_4d, first_weights, [1, 1, 1, 1],'SAME') + first_bias  
first_conv2=tf.reshape(first_conv,[tf.shape(first_conv)[0],first_conv.get_shape()[1]*first_conv.get_shape()[2]*first_conv.get_shape()[3]])
#cc = tf.reshape(first_conv2,[tf.shape(first_conv)[0], first_conv2.get_shape()[1]*first_conv.get_shape()[2]*first_conv.get_shape()[3]])
cc=[]
cc.append(first_conv2[tf.shape(first_conv2)[0],0])
k=(first_conv.get_shape()[1]*first_conv.get_shape()[2]*first_conv.get_shape()[3])
k=6400
print(k)
for i in xrange(1,k): 
print(i)
cc.append(tf.add(first_conv2[tf.shape(first_conv2)[0],i],cc[i - 1]))
first_conv=tf.reshape(cc,[-1,64,10,10])
 
#first_conv=tf.reshape(cc,[first_conv.get_shape()[0],first_conv.get_shape()[1],first_conv.get_shape()[2],first_conv.get_shape()[3]])
first_relu = tf.nn.relu(first_conv)
 
if is_training:first_dropout = tf.nn.dropout(first_relu, dropout_prob)
else:first_dropout = first_relu
#second_filter_width = 4
#second_filter_height = 10
#second_filter_count = 64
#second_weights = tf.Variable(tf.truncated_normal([second_filter_height, second_filter_width, first_filter_count,second_filter_count],stddev=0.01))
#second_bias = tf.Variable(tf.zeros([second_filter_count]))
#second_conv = tf.nn.conv2d(max_pool, second_weights, [1, 1, 1, 1],'SAME') + second_bias
#second_relu = tf.nn.relu(second_conv)
#if is_training:second_dropout = tf.nn.dropout(second_relu, dropout_prob)
#else:second_dropout = second_relu
#second_conv_shape = second_dropout.get_shape()
#second_conv_output_width = second_conv_shape[2]
#second_conv_output_height = second_conv_shape[1]
#second_conv_element_count = int(second_conv_output_width * second_conv_output_height *second_filter_count)
#flattened_second_conv = tf.reshape(second_dropout,[-1, second_conv_element_count])
first_conv_shape = first_dropout.get_shape()
first_conv_output_width = first_conv_shape[2]
first_conv_output_height = first_conv_shape[1]
first_conv_element_count = int(first_conv_output_width * first_conv_output_height *first_filter_count)
#flattened_first_conv = tf.reshape(first_dropout,[-1, first_conv_element_count])
flattened_first_conv = tf.reshape(first_dropout,[-1, 6400])
label_count = model_settings['label_count']
final_fc_weights = tf.Variable(tf.truncated_normal([6400, label_count], stddev=0.01))
#final_fc_weights = tf.Variable(tf.truncated_normal([first_conv_element_count, label_count], stddev=0.01))
final_fc_bias = tf.Variable(tf.zeros([label_count]))
final_fc = tf.matmul(flattened_first_conv, final_fc_weights) + final_fc_bias
if is_training:return final_fc, dropout_prob
else:return final_fc
