### ISSUE TITLE
Tensorflow installe using GPU but it is using only CPU

### ISSUE THREAD

**Issue by sanakhamekhem** [tensorflow/tensorflow#29970]
I have installed tensorflow from source using bazel on ubuntu 16.xx

tensorflow version 1.11.0
bazel 0.18.0rc6
python 2.7.11
cuda 9.2 (j'utilse celle dans dossier /home/ahmed/tmp/cuda-9.2)
cudnn 7.1.4
nccl 2.4.2

the build sucessfull , the installation is also OK.
However, the tensorflow does'nt use GPU.

Whe I run : 

import tensorflow as tf
sess = tf.Session(config=tf.ConfigProto(log_device_placement=True))

**2019-06-19 17:49:28.775658: E tensorflow/stream_executor/cuda/cuda_driver.cc:300] failed call to cuInit: UNKNOWN ERROR (-1)
2019-06-19 17:49:28.775751: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:163] retrieving CUDA diagnostic information for host: ubuntu-Precision-Tower-7910
2019-06-19 17:49:28.775770: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:170] hostname: ubuntu-Precision-Tower-7910
2019-06-19 17:49:28.775831: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:194] libcuda reported version is: Invalid argument: expected %d.%d, %d.%d.%d, or %d.%d.%d.%d form for driver version; got "1"
2019-06-19 17:49:28.775898: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:198] kernel reported version is: 396.54.0
Device mapping: no known devices.
2019-06-19 17:49:28.777666: I tensorflow/core/common_runtime/direct_session.cc:291] Device mapping:**

Wed Jun 19 17:54:39 2019
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 396.54                 Driver Version: 396.54                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 108...  Off  | 00000000:04:00.0  On |                  N/A |
| 28%   49C    P8    19W / 250W |    180MiB / 11177MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  TITAN Xp            Off  | 00000000:05:00.0 Off |                  N/A |
| 23%   33C    P8    16W / 250W |      2MiB / 12196MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0      1385      G   /usr/lib/xorg/Xorg                           137MiB |
|    0      2744      G   compiz                                        41MiB |
+-----------------------------------------------------------------------------+

**Comment by achandraa** [comment]
Could you check this [issue](https://github.com/tensorflow/tensorflow/issues/19266#issuecomment-399686258) which is similar to your issue but for older TF version. If those solutions doesn't work, could you uninstall and reinstall CUDA and cuDNN? Please let us know how it progresses. Also, try to uninstall and reinstall tensorflow-gpu and try following the instructions from [TensorFlow website](https://www.tensorflow.org/install/source). Thanks!

**Comment by achandraa** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
