### ISSUE TITLE
Build failed after upgrading protobuf from 3.7.1 to 3.8.0

### ISSUE THREAD

**Issue by feihugis** [tensorflow/tensorflow#29978]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): MacOS Mojave
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): source
- TensorFlow version: latest
- Python version: 3.6.2
- Installed using virtualenv? pip? conda?:
- Bazel version (if compiling from source): 0.26
- GCC/Compiler version (if compiling from source): LLVM version 10.0.1 (clang-1001.0.46.4)
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

**Describe the problem**

After upgrading protobuf from 3.7.1 to 3.8.0, the bazel build failed. 

If reverting the upgrade commit(https://github.com/tensorflow/tensorflow/commit/508f76b1d9925304cedd56d51480ec380636cb82), the build works well.

**Provide the exact sequence of commands / steps that you executed before running into the problem**

`bazel test //tensorflow/core/kernels/data:range_dataset_op_test`

**Any other info / logs**
```
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=1 --terminal_columns=192
INFO: Reading rc options for 'test' from /Users/fei/Documents/Github/tensorflow/.bazelrc:
  Inherited 'build' options: --apple_platform_type=macos --define framework_shared_object=true --define=use_fast_cpp_protos=true --define=allow_oversize_protos=true --spawn_strategy=standalone --strategy=Genrule=standalone -c opt --announce_rc --define=grpc_no_ares=true --define=PREFIX=/usr --define=LIBDIR=$(PREFIX)/lib --define=INCLUDEDIR=$(PREFIX)/include
INFO: Reading rc options for 'test' from /Users/fei/Documents/Github/tensorflow/.tf_configure.bazelrc:
  Inherited 'build' options: --action_env PYTHON_BIN_PATH=/Users/fei/venv-py/tf-src/bin/python --action_env PYTHON_LIB_PATH=/Users/fei/venv-py/tf-src/lib/python3.6/site-packages --python_path=/Users/fei/venv-py/tf-src/bin/python --action_env TF_CONFIGURE_IOS=0
INFO: Reading rc options for 'test' from /Users/fei/Documents/Github/tensorflow/.tf_configure.bazelrc:
  'test' options: --flaky_test_attempts=3 --test_size_filters=small,medium --test_tag_filters=-benchmark-test,-no_oss,-oss_serial --build_tag_filters=-benchmark-test,-no_oss --test_tag_filters=-gpu,-nomac,-no_mac --build_tag_filters=-gpu,-nomac,-no_mac
INFO: Build option --runs_per_test has changed, discarding analysis cache.
INFO: Analyzed target //tensorflow/core/kernels/data:range_dataset_op_test (1 packages loaded, 7713 targets configured).
INFO: Found 1 test target...
ERROR: /private/var/tmp/_bazel_fei/5dc7b372a7c45427ff30500d3e22fe26/external/com_google_protobuf/BUILD:106:1: C++ compilation of rule '@com_google_protobuf//:protobuf_lite' failed (Exit 1)
external/com_google_protobuf/src/google/protobuf/arena.cc:53:13: error: use of undeclared identifier 'LifecycleId'
std::atomic<LifecycleId> ArenaImpl::lifecycle_id_generator_;
            ^
1 error generated.
Target //tensorflow/core/kernels/data:range_dataset_op_test failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 1.726s, Critical Path: 0.74s
INFO: 0 processes.
FAILED: Build did NOT complete successfully

FAILED: Build did NOT complete successfully
```

cc: @angersson

**Comment by angersson** [comment]
@meteorcloudy can you have a look at this?

**Comment by feihugis** [comment]
@angersson @meteorcloudy This issue is resolved. It seems to be caused by the protobuf version conflicts with that installed on my laptop (which is `3.7.1`). After uninstalling protobuf in my system and `bazel clean --expunge`, the bazel build works well. I'm not sure how the protobuf installed on my laptop affects the TF bazel build.

**Comment by ravikyram** [comment]
I am closing this issue as it was resolved.Thanks

**Comment by angersson** [comment]
@feihugis Thanks for the update!
