### ISSUE TITLE
bazel build --config=opt //tensorflow/tools/pip_package:build_pip_package 

### ISSUE THREAD

**Issue by harsh204016** [tensorflow/tensorflow#29973]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>
Hello Tensorflow team
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):Windows 10 64bit
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:NA
- TensorFlow installed from (source or binary):Don't know
- TensorFlow version:1.13.1
- Python version:3.6.5
- Installed using virtualenv? pip? conda? :pip
- Bazel version (if compiling from source):0.22
- GCC/Compiler version (if compiling from source):Don't know
- CUDA/cuDNN version:NA
- GPU model and memory:NA

**Describe the problem**
I am following the commands Build from source on Windows and got stuck

C:\Users\DELL\tensorflow>bazel build --config=opt //tensorflow/tools/pip_package:build_pip_package
WARNING: The following rc files are no longer being read, please transfer their contents or import their path into one of the standard rc files:
c:\users\dell\tensorflow/tools/bazel.rc
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=1 --terminal_columns=120
INFO: Options provided by the client:
  'build' options: --python_path=C:/Users/DELL/Miniconda3/python.exe
INFO: Reading rc options for 'build' from c:\users\dell\tensorflow\.tf_configure.bazelrc:
  'build' options: --action_env PYTHON_BIN_PATH=C:/Users/DELL/Miniconda3/python.exe --action_env PYTHON_LIB_PATH=C:/Users/DELL/Miniconda3/lib/site-packages --python_path=C:/Users/DELL/Miniconda3/python.exe --action_env TF_NEED_OPENCL_SYCL=0 --action_env TF_NEED_CUDA=0 --action_env TF_DOWNLOAD_CLANG=0 --define grpc_no_ares=true --strip=always --config monolithic --copt=-w --host_copt=-w --verbose_failures
ERROR: Config value monolithic is not defined in any .rc file
INFO: Invocation ID: 0388987f-5098-402f-afd1-3cf7ab4f3e40

**Provide the exact sequence of commands / steps that you executed before running into the problem**
I installed Msys2 
 then used pacman -S git patch unzip
set path as C:\msys64\usr\bin\bash.exe for BAZEL_SH
I installed  Visual C++ Build Tools 2015
git clone https://github.com/tensorflow/tensorflow.git 
cd tensorflow
git checkout r1.9
python ./configure.py
bazel build --config=opt //tensorflow/tools/pip_package:build_pip_package

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.
I tried many ways to resolve this but can't find the solution please help me out and if possible please make video for this

**Comment by achandraa** [comment]
Please have a look on this [similar issue](https://github.com/tensorflow/tensorflow/issues/23401#issuecomment-434681778) and let us know if that resolves the error. Thanks!

**Comment by achandraa** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Comment by harsh204016** [comment]
while running the command git checkout branchname 
which branchname I have to used in this command??

**Comment by mihaimaruseac** [comment]
Where did you get the command from? There is some context which is missing in your question above

**Comment by harsh204016** [comment]
I am following the commands given on this 

**Build from source on Windows**
https://www.tensorflow.org/install/source_windows

**Comment by mihaimaruseac** [comment]
Quoting from there

> ```
> git clone https://github.com/tensorflow/tensorflow.git
> cd tensorflow
> ```
>
> The repo defaults to the master development branch. You can also checkout a release branch to build:
> 
> ```
> git checkout branch_name  # r1.9, r1.10, etc.
> ```

You can use master (getting you the latest code) or the release branch corresponding to the TF version you want to build from source (e.g., `r1.13` for 1.13.* series)

**Comment by harsh204016** [comment]
Now when I am running this command
**python ./configure.py**

I am getting this error:
```
(base) C:\Users\DELL\tensorflow>python ./configure.py
python: can't open file './configure.py': [Errno 2] No such file or directory
```

**Comment by mihaimaruseac** [comment]
Do you have `configure.py` in that directory? Try `dir`/`ls`

**Comment by harsh204016** [comment]
Yes,In tensorflow folder configure file is present but not in .py extension.

**Comment by mihaimaruseac** [comment]
That's strange. It is supposed to exist in both formats as [`configure` ](https://github.com/tensorflow/tensorflow/blob/master/configure) just calls `configure.py`:
https://github.com/tensorflow/tensorflow/blob/377a4df447c3b8ca086e0b5860083f1752f416b8/configure#L12

**Comment by mihaimaruseac** [comment]
Most likely you didn't get a full clone of the repository, or accidentally removed files. I suggest trying again from scratch, from a new fresh clone

**Comment by eduardoavila1m** [comment]
Check that the Path has been included

Take a look into this tutorial

https://github.com/EdjeElectronics/TensorFlow-Lite-Object-Detection-on-Android-and-Raspberry-Pi#step-2-build-tensorflow-from-source
