### ISSUE TITLE
error saving file while using tf.data.experimental.TFRecordWriter at https://www.tensorflow.org/beta/tutorials/load_data/tf_records#writing_a_tfrecord_file

### ISSUE THREAD

**Issue by ak-org** [tensorflow/tensorflow#29980]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): 
python notebook using python v3.7.

- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.0.0-beta
[tfrecord-example-with-tfdata.ipynb.zip](https://github.com/tensorflow/tensorflow/files/3307947/tfrecord-example-with-tfdata.ipynb.zip)

- Python version: 3.7
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory: Deep learning VM available on GCP 

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
I am following the tutorial at https://www.tensorflow.org/beta/tutorials/load_data/tf_records#writing_a_tfrecord_file

**Describe the expected behavior**
I should be able to save the file. 

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.
See attached python notebook

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by gadagashwini** [comment]
Was able to reproduce the issue with Tensorflow 2.0.0.beta1 on my system. Thanks!

**Comment by martinwicke** [comment]
When you write (let's say, in eager mode, since that's simpler), you need to iterate through the dataset. In the relevant cell of your notebook:

```
writer = tf.compat.v1.data.experimental.TFRecordWriter(filename)
for features in serialized_features_dataset:
  writer.write(features)
```

This doesn't look like a bug in TensorFlow to me (of course I may be missing something). Please open a new issue if I am mistaken.
