### ISSUE TITLE
Tensorflow Distributed Learning Tutorial Code not working on localhost

### ISSUE THREAD

**Issue by AshwinAmbal** [tensorflow/tensorflow#29988]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): MacOS Mojave Version 10.14.5 (Darwin-18.6.0-x86_64-i386-64bit)
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.0.0-beta1
- Python version: 3.7.3
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

**Describe the current behavior**
I have used the exact same code from the Tensorflow 2.0 Distributed Training Tutorial as in [https://www.tensorflow.org/beta/tutorials/distribute/multi_worker_with_estimator](url). The model does not run on localhost and the code returns an error with **"Unable to destroy server_ object, so releasing instead. Servers don't support clean shutdown."**
The same error was reported here: #27562 but the fix says to use "localhost" which I have already done and the model still won't run. Moreover, removing TF_CONFIG allows the model to run perfectly fine but adding it is what causes the error. 

**Describe the expected behavior**
The model runs as described in the tutorial.

**Code to reproduce the issue**
### Run the code below in a local machine:

```
from __future__ import absolute_import, division, print_function, unicode_literals

import tensorflow_datasets as tfds
import tensorflow as tf
import os
import json

BUFFER_SIZE = 10000
BATCH_SIZE = 64

def input_fn(mode, input_context=None):
    datasets, info = tfds.load(name='mnist',
                                with_info=True,
                                as_supervised=True)
    mnist_dataset = (datasets['train'] if mode == tf.estimator.ModeKeys.TRAIN else
                     datasets['test'])

    def scale(image, label):
        image = tf.cast(image, tf.float32)
        image /= 255
        return image, label

    if input_context:
        mnist_dataset = mnist_dataset.shard(input_context.num_input_pipelines,
                                            input_context.input_pipeline_id)
    return mnist_dataset.map(scale).shuffle(BUFFER_SIZE).batch(BATCH_SIZE)


NUM_WORKERS = 1
IP_ADDRS = ['localhost']
PORTS = [12345]

os.environ['TF_CONFIG'] = json.dumps({
    'cluster': {
        'worker': ['%s:%d' % (IP_ADDRS[w], PORTS[w]) for w in range(NUM_WORKERS)]
    },
    'task': {'type': 'worker', 'index': 0}
})

LEARNING_RATE = 1e-4

def model_fn(features, labels, mode):
    model = tf.keras.Sequential([
      tf.keras.layers.Conv2D(32, 3, activation='relu', input_shape=(28, 28, 1)),
      tf.keras.layers.MaxPooling2D(),
      tf.keras.layers.Flatten(),
      tf.keras.layers.Dense(64, activation='relu'),
      tf.keras.layers.Dense(10, activation='softmax')
    ])
    logits = model(features, training=False)

    if mode == tf.estimator.ModeKeys.PREDICT:
        predictions = {'logits': logits}
        return tf.estimator.EstimatorSpec(labels=labels, predictions=predictions)

    optimizer = tf.compat.v1.train.GradientDescentOptimizer(
      learning_rate=LEARNING_RATE)
    loss = tf.keras.losses.SparseCategoricalCrossentropy(
      from_logits=True, reduction=tf.keras.losses.Reduction.NONE)(labels, logits)
    loss = tf.reduce_sum(loss) * (1. / BATCH_SIZE)
    if mode == tf.estimator.ModeKeys.EVAL:
        return tf.estimator.EstimatorSpec(mode, loss=loss)

    return tf.estimator.EstimatorSpec(
      mode=mode,
      loss=loss,
      train_op=optimizer.minimize(
          loss, tf.compat.v1.train.get_or_create_global_step()))

strategy = tf.distribute.experimental.MultiWorkerMirroredStrategy()

config = tf.estimator.RunConfig(train_distribute=strategy)

classifier = tf.estimator.Estimator(
    model_fn=model_fn, config=config)
eval_result = tf.estimator.train_and_evaluate(
    classifier,
    train_spec=tf.estimator.TrainSpec(input_fn=input_fn),
    eval_spec=tf.estimator.EvalSpec(input_fn=input_fn)
)

print(eval_result)

```

**Other info / logs**
```
2019-06-19 18:52:26.920506: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2019-06-19 18:52:26.922213: I tensorflow/core/distributed_runtime/rpc/grpc_channel.cc:250] Initialize GrpcChannelCache for job worker -> {0 -> localhost:12345}
2019-06-19 18:52:26.922707: I tensorflow/core/distributed_runtime/rpc/grpc_server_lib.cc:365] Started server with target: grpc://localhost:12345
WARNING: Logging before flag parsing goes to stderr.
W0619 18:52:26.923428 4497626560 cross_device_ops.py:1164] Some requested devices in `tf.distribute.Strategy` are not visible to TensorFlow: /job:worker/replica:0/task:0/device:CPU:0
W0619 18:52:26.926181 4497626560 estimator.py:1811] Using temporary folder as model directory: /var/folders/g1/9kky40_94s9_5qckppqs5fs9w56_br/T/tmp6x4api2p
W0619 18:52:26.928005 4497626560 distribute_coordinator.py:829] `eval_strategy` is not passed in. No distribution strategy will be used for evaluation.
W0619 18:52:26.928821 4497626560 cross_device_ops.py:1164] Some requested devices in `tf.distribute.Strategy` are not visible to TensorFlow: /job:worker/replica:0/task:0/device:CPU:0
W0619 18:52:26.929581 4497626560 cross_device_ops.py:1164] Some requested devices in `tf.distribute.Strategy` are not visible to TensorFlow: /job:worker/replica:0/task:0/device:CPU:0
W0619 18:52:27.373800 123145474756608 deprecation.py:323] From /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tensorflow/python/ops/array_ops.py:1340: add_dispatch_support.<locals>.wrapper (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
W0619 18:52:27.378234 4497626560 monitored_session.py:347] Collective ops may deadlock with `save_checkpoints_secs` please use `save_checkpoint_steps` instead. Clearing `save_checkpoint_secs` and setting `save_checkpoint_steps` to 1000 now.
None
2019-06-19 18:52:37.840780: W tensorflow/core/common_runtime/eager/context.cc:232] Unable to destroy server_ object, so releasing instead. Servers don't support clean shutdown.
```

**Comment by runner-yang** [comment]
Do you resolve this problem?
I also meet the same question. I found that the problem appeared in the official demon of estimator and keras when using one worker two workers. 
I also change the localhost according to the discussion #27562, however, it doesn't work.
I don't understand that is "Moreover, removing TF_CONFIG allows the model to run perfectly fine ".

**Comment by AshwinAmbal** [comment]
Hi @runner-yang ,
No, I haven't resolved it yet.
When using Python 3.6, Tensorflow 1.13.0, I get an unimplemented error because the server destroy or shutdown function hasn't been implemented yet. But Python 3.7 and Tensorflow 2.0, gives the error that I have stated above. 
And about the TF_CONFIG variable, what I meant was that the code/model compiles and runs without the TF_CONFIG but adding it is what causes the error. So the root cause should be something related to the functions that parse and execute from the TF_CONFIG environment variable. It would be a good place to start looking...

**Comment by achandraa** [comment]
@AshwinAmbal : I have tried to reproduce the issue on Colab with TF version 2.0beta1 and was unable to get the mentioned error. Can you please help us to replicate the issue. For reference [Colab Link](https://colab.sandbox.google.com/drive/1z7QDcwzgKrIix1tyDrASSQ_J2_Uj9wqI#scrollTo=kHWWkBDhiCLL). Thanks!

**Comment by AshwinAmbal** [comment]
Hi @achandraa , 
I am unable to access the Colab link that you have given. 
Anyway, this error occurs in localhost when configuring TF_CONFIG. In Colab, I think the Collective Ops is pre-configured. So we don't set the TF_CONFIG environment variable right? Moreover, the tutorial mentioned not to set the variable in Colab. This error occurs when we run the same piece of code in our local machine after setting the TF_CONFIG Environment variable. You can reproduce the error by running the sample code given above in this thread and running it in your local machine.

**Comment by martinwicke** [comment]
Mixing single worker TF_CONFIG and a MultiWorkerMirrored Strategy used with Estimator seem like a very odd combination. 

That said, if the tutorial says that, it needs to be fixed, and the error should really be better.

**Comment by dubey** [comment]
Note that the "unable to destroy server object" message is a red herring.  The training does complete, however it does not run evaluate because no evaluator task was started in this cluster.  The return value of `train_and_evaluate` is `None` in this case, which is printed before the last line in the logs.

In order to run evaluation, please start a separate evaluator task.  #27857 has more details.

I've updated the tutorial to provide an example of a `TF_CONFIG` with 2 workers; the single worker example wasn't great.
