### ISSUE TITLE
If variable has huge size, where this variable is located when serveral parameter servers.

### ISSUE THREAD

**Issue by fantajeon** [tensorflow/tensorflow#29999]
I have tried to model data using two-layered(linear, w*x + b) neural network using custom tf.estimate.Estimator and distribution strategy(default? train_distribution=None), and then an input feature dimension is so huge(almost > 100K).
If I have [300, 128] layered with biased term, it could be as following:
1st layer: w1 variable will be 100K> x 300(float32), b1 = [1]
2nd layer: w2 variable will be 300 x 128(float32) b2 = [1]

Finally, my question is that w1 is so big size, where is w1 variable located? Is the w1 variable spread equally with other parameter servers or located in one parameter server.

Thank you for reading even my poor english, in advance.

**Comment by ravikyram** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged//tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there and can provide better and faster resolution to such issues.Thanks

**Comment by fantajeon** [comment]
Thank you. :)
