### ISSUE TITLE
libtensorflow_jni.so: libcudnn.so.7: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by whaozl** [tensorflow/tensorflow#29997]
tensorflow version=1.8.0
java=1.8.0
cuda=9.1
cudnn=7

**I used java to call the GPU when I reported the following error:**

java.lang.UnsatisfiedLinkError: /tomcat/temp/tensorflow_native_libraries-1561013286760-0/libtensorflow_jni.so: libcudnn.so.7: cannot open shared object file: No such file or directory

```
        <dependency>
            <groupId>org.tensorflow</groupId>
            <artifactId>tensorflow</artifactId>
            <exclusions>
                <exclusion>
                    <groupId>org.tensorflow</groupId>
                    <artifactId>libtensorflow_jni</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>org.tensorflow</groupId>
            <artifactId>libtensorflow_jni_gpu</artifactId>
        </dependency>
```

when delete as follows. This program prompts that the GPU cannot be found, forcing the CPU
```
            <exclusions>
                <exclusion>
                    <groupId>org.tensorflow</groupId>
                    <artifactId>libtensorflow_jni</artifactId>
                </exclusion>
            </exclusions>
```
Can you help me? Thanks a lot.

**Comment by achandraa** [comment]
Just to verify are you trying to build TensorFlow from source from steps mentioned in [TensorFlow website](https://www.tensorflow.org/install/source). Also let us know on which platform you are seeing the issue. Thanks!

**Comment by whaozl** [comment]
Thank you for you reply. I use tf in java 1.8 centos7.

**Comment by whaozl** [comment]
or, Can ask？How to configure pom TensorFlow under GPU? The above methods have no effect.

**Comment by HedgehogCode** [comment]
Hi,
it seems like the cudnn library is not on your library path. You can start your application with the environment variable `LD_LIBRARY_PATH=/path/to/cuda/lib64/:/path/to/cudnn/lib64` or you could add the path to your global library path like described [here](https://www.cyberciti.biz/faq/linux-setting-changing-library-path/).

**Comment by whaozl** [comment]
Thank you, In fact, this path is configured.
Finally, I did a lot of experiments and proved that this is ok.
```
 <dependency>
            <groupId>org.tensorflow</groupId>
            <artifactId>tensorflow</artifactId>
        </dependency>
        <dependency>
            <groupId>org.tensorflow</groupId>
            <artifactId>libtensorflow_jni_gpu</artifactId>
        </dependency>
```

**Comment by yhweb** [comment]
install cudnn 
Can solve the problem

**Comment by whaozl** [comment]
thank you, I had solved this problem. and cudnn had installed originally.

**Comment by aloksingh3110** [comment]
> thank you, I had solved this problem. and cudnn had installed originally.

how you have solved the above problem can you explain the procedure..

**Comment by whaozl** [comment]
and, only use gpu version tensorflow jar.

**Comment by yangxudong** [comment]
> Thank you, In fact, this path is configured.
> Finally, I did a lot of experiments and proved that this is ok.
> 
> ```
>  <dependency>
>             <groupId>org.tensorflow</groupId>
>             <artifactId>tensorflow</artifactId>
>         </dependency>
>         <dependency>
>             <groupId>org.tensorflow</groupId>
>             <artifactId>libtensorflow_jni_gpu</artifactId>
>         </dependency>
> ```

Can the gpu be used in this way?

**Comment by whaozl** [comment]
yes.
