### ISSUE TITLE
TF2 - apparent memory leak when running dataset ops eagerly

### ISSUE THREAD

**Issue by morgangiraud** [tensorflow/tensorflow#29996]
**System information**
- Have I written custom code: yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): OSX
- TensorFlow installed from (source or binary): 2.0.0beta
- TensorFlow version (use command below): v1.12.1-3259-gf59745a381 2.0.0-beta0
- Python version: 3.6.8

**Describe the current behavior**
When using the function `tf.autograph.to_graph`, I see a memory leak which I don't see if I use the annotation `@tf.function`

**Describe the expected behavior**
There should not be a memory leak.

**Code to reproduce the issue**
```python
import os
import psutil
import numpy as np

import tensorflow as tf

process = psutil.Process(os.getpid())


# @tf.function
def train_epoch(model, p_data):
    for real_inputs in p_data:
        model * real_inputs


train_epoch = tf.autograph.to_graph(train_epoch)

data = np.random.normal(0., 1., [10000, 2])
p_data = tf.data.Dataset.from_tensor_slices(data).batch(32)

model = tf.Variable([1., 1.], dtype=tf.float64)

for i in range(5000):
    train_epoch(model, p_data)

    if i % 50 == 0:
        print(process.memory_info().rss)
```

**Comment by achandraa** [comment]
I have tried on Colab with TF version 2.0beta and was able to reproduce the issue.

**Comment by mdanatg** [comment]
I did a few tests. In short, this seems to be related to `Dataset.reduce` (which is what is generated in this case).

The leak reproduces even without `autograph.to_code`, if we run the code that would be effectively generated:

```
import os
import psutil
import numpy as np

import tensorflow as tf

tf = tf.compat.v2
tf.enable_v2_behavior()

process = psutil.Process(os.getpid())


# @tf.function
def train_epoch(model, p_data):

  def reduce_func(_, real_inputs):
    model * real_inputs
    return (tf.constant(0),)  # These tf.constant(0) are dummy variables - reduce requires at least one var.

  p_data.reduce(((tf.constant(0),), ()), reduce_func)


# train_epoch = tf.autograph.to_graph(train_epoch)

data = np.random.normal(0., 1., [10000, 2])
p_data = tf.data.Dataset.from_tensor_slices(data).batch(32)

model = tf.Variable([1., 1.], dtype=tf.float64)

for i in range(5000):
    train_epoch(model, p_data)

    if i % 50 == 0:
        print(process.memory_info().rss)
```

The leak only seems to happen for datasets - if we replace `p_data` with reshaped version of `data` (in effect causing the for loop to run as a `tf.while_loop`), the leak doesn't reproduce:

```
import os
import psutil
import numpy as np

import tensorflow as tf

tf = tf.compat.v2
tf.enable_v2_behavior()

process = psutil.Process(os.getpid())


# @tf.function
def train_epoch(model, data):
    for real_inputs in data:
        model * real_inputs


train_epoch = tf.autograph.to_graph(train_epoch)

data = np.random.normal(0., 1., [10016, 2])  # Fit batches evenly
data = data.reshape([313, 32, 2])
# p_data = tf.data.Dataset.from_tensor_slices(data).batch(32)

model = tf.Variable([1., 1.], dtype=tf.float64)

for i in range(5000):
    train_epoch(model, data)

    if i % 50 == 0:
        print(process.memory_info().rss)
```

**Comment by mdanatg** [comment]
@jsimsa any insight into this?

**Comment by mdanatg** [comment]
Jiri and I spoke offline. For technical reasons, `Dataset.reduce` re-traces its function whenever called during Eager execution. This in effect adds a new trace to the default graph, which accounts for the increase in memory use.

For this reason, we recommend caution when iterating over Datasets repeatedly in Eager execution, even with AutoGraph. We recommend using `tf.function`, as in increases performance and avoids these memory build-ups. `tf.function` also applies AutoGraph, so you won't need to call it separately.

```
@tf.function
def train_epoch(model, p_data):
    for real_inputs in p_data:
        model * real_inputs

for i in range(5000):
    train_epoch(model, p_data)
```

**Comment by 2649** [comment]
@mdanatg  Is there any other way than wrapping the iteration of a dataset into a tf.function. My custom training loops need eager tensors to use the tf.summary API. Can I manually free the memory from the tf.dataset? 

Furthermore, this should be noted in the [documentation](https://www.tensorflow.org/beta/tutorials/eager/custom_training_walkthrough#training_loop), since it iterates several times of the dataset while being in eager mode.

**Comment by mdanatg** [comment]
@jaingaurav I agree that it's worth noting it in the docs somewhere.

@2649 as far as I know, the tf.summary API should work inside tf.function as well - unless you're perhaps encountering a different bug? Unfortunately I don't know of a way to manually free up the memory. @jsimsa might know of a way.

**Comment by 2649** [comment]
@mdanatg No it is not really a bug. I have some numpy operations in my summary calls, which do not work in tf.function. But I just changed them to ´tf´ operations. It is just a comfort problem.

**Comment by 2649** [comment]
Ok, the memory leak has a higher impact on my custom training loops than I expected. For everyone who needs a quick fix:  You can disable trace (`tf.summary.trace_off()`) before you iterate over a dataset and enable it afterwards (`tf.summary.trace_on() `).  This worked in my case.

@mdanatg Do you see any problems with this workaround?

**Comment by mdanatg** [comment]
It's hard to make a in the general case, but I don't see a problem with disabling trace, if it's not needed.

**Comment by xiumingzhang** [comment]
Thanks @2649 for proposing this quick fix. I wonder if you could provide some intuitions/explanations as to why this worked?

BTW, I strongly think this problem should at least be mentioned (if not fixed) in all of the official docs whenever iterating a dataset happens.
