### ISSUE TITLE
TensorFlow 1.3 build fails with OpenMPI

### ISSUE THREAD

**Issue by a-gn** [tensorflow/tensorflow#30001]
**System information**
- OS Platform and Distribution: Linux Ubuntu 16.04
- TensorFlow installed from (source or binary): source
- TensorFlow version: 1.3.1
- Python version: 3.5.2
- Installed using virtualenv? pip? conda?: git
- Bazel version (if compiling from source): 0.4.5
- GCC/Compiler version (if compiling from source): 5.4.0
- CUDA/cuDNN version: 8.0/6
- GPU model and memory: none (explained below) and 8GB

**Describe the problem**
Building TensorFlow 1.3 leads to an error when MPI support is enabled:

```
In file included from ./tensorflow/contrib/mpi/mpi_utils.h:27:0,
                 from tensorflow/contrib/mpi/mpi_utils.cc:18:
./third_party/mpi/mpi.h:2673:41: fatal error: openmpi/ompi/mpi/cxx/mpicxx.h: No such file or directory
compilation terminated.
```

**Provide the exact sequence of commands / steps that you executed before running into the problem**

```bash
git clone git@github.com:tensorflow/tensorflow.git
cd tensorflow
git checkout v1.3.1
./configure # enable HDFS, CUDA and MPI support, full output in the next section
bazel build -s --config=opt --config=cuda //tensorflow/tools/pip_package:build_pip_package
```

**Any other info / logs**
The full build output is [there](https://drive.google.com/file/d/19g1oVyPUf1AfRwHBrpMJx5T1o9ZHc7hK/view?usp=sharing).

I am building TensorFlow in a VM for another system that has a CUDA-compatible GPU. That is why I have installed CUDA and enabled CUDA support, despite the VM not having access to my laptop's GPU (GTX 1050).

This is the output of `./configure`, including my choices (I enabled HDFS, CUDA and MPI support):
```
...........
You have bazel 0.4.5 installed.
Please specify the location of python. [Default is /usr/bin/python]: /usr/bin/python3
Found possible Python library paths:
  /usr/lib/python3/dist-packages
  /usr/local/lib/python3.5/dist-packages
Please input the desired Python library path to use.  Default is [/usr/lib/python3/dist-packages]

Using python library path: /usr/lib/python3/dist-packages
Do you wish to build TensorFlow with MKL support? [y/N]
No MKL support will be enabled for TensorFlow
Please specify optimization flags to use during compilation when bazel option "--config=opt" is specified [Default is -march=native]:
Do you wish to use jemalloc as the malloc implementation? [Y/n]
jemalloc enabled
Do you wish to build TensorFlow with Google Cloud Platform support? [y/N]
No Google Cloud Platform support will be enabled for TensorFlow
Do you wish to build TensorFlow with Hadoop File System support? [y/N] y
Hadoop File System support will be enabled for TensorFlow
Do you wish to build TensorFlow with the XLA just-in-time compiler (experimental)? [y/N]
No XLA support will be enabled for TensorFlow
Do you wish to build TensorFlow with VERBS support? [y/N]
No VERBS support will be enabled for TensorFlow
Do you wish to build TensorFlow with OpenCL support? [y/N]
No OpenCL support will be enabled for TensorFlow
Do you wish to build TensorFlow with CUDA support? [y/N] y
CUDA support will be enabled for TensorFlow
Do you want to use clang as CUDA compiler? [y/N]
nvcc will be used as CUDA compiler
Please specify the CUDA SDK version you want to use, e.g. 7.0. [Leave empty to default to CUDA 8.0]:
Please specify the location where CUDA 8.0 toolkit is installed. Refer to README.md for more details. [Default is /usr/local/cuda]:
Please specify which gcc should be used by nvcc as the host compiler. [Default is /usr/bin/gcc]:
Please specify the cuDNN version you want to use. [Leave empty to default to cuDNN 6.0]:
Please specify the location where cuDNN 6 library is installed. Refer to README.md for more details. [Default is /usr/local/cuda]:
Please specify a list of comma-separated Cuda compute capabilities you want to build with.
You can find the compute capability of your device at: https://developer.nvidia.com/cuda-gpus.
Please note that each additional compute capability significantly increases your build time and binary size.
[Default is: "3.5,5.2"]: 6.2
Do you wish to build TensorFlow with MPI support? [y/N] y
MPI support will be enabled for TensorFlow
Please specify the MPI toolkit folder. [Default is /usr]: /usr/lib/openmpi
Configuration finished
```

I have installed `libopenmpi-dev`.

**Comment by a-gn** [comment]
I have tried to fix the build, as described in [this question](https://stackoverflow.com/questions/56669899/building-tensorflow-import-mpi-headers-from-outside-of-the-bazel-root), without success. Setting `CC=mpicc` didn't help, as mentioned in the comments.

**Comment by a-gn** [comment]
The build succeeds with MVAPICH installed from source, keeping the default MPI toolkit path `/usr/local`. The problem exists only when OpenMPI is used.

**Comment by gadagashwini** [comment]
@a-gn Did you a get chance to look [#26610](https://github.com/tensorflow/tensorflow/issues/26610) issue. Thanks!

**Comment by a-gn** [comment]
@gadagashwini I saw this issue, but their problem seems different from mine: in my case, Bazel looks for headers in the wrong place and fails executing the `//tensorflow/contrib/mpi:mpi_utils` rule; in theirs, it fails during the `//tensorflow:tf_python_api_gen_v1` genrule with a problem I don't really understand.

**Comment by byronyi** [comment]
Do you get a chance to configure.py the OpenMPI path?

**Comment by a-gn** [comment]
@byronyi Yes, I gave `/usr/lib/openmpi`. I tried other paths, but the `configure` script expects this directory to contain `lib` and `include`, and shows an error if it doesn't.

`/usr` is the default, but OpenMPI doesn't install in `/usr/include` and `/usr/lib` the files Bazel is looking for. It puts them in `/usr/lib/openmpi` instead.

**Comment by byronyi** [comment]
Ping @jbedorf

**Comment by jbedorf** [comment]
Looks like the path/file detection during configure fails, similar to this issue: https://github.com/tensorflow/tensorflow/issues/11903
The fact that it tries to include the `mpicxx.h` file should mean you can prevent that by disabling those headers via: `CC_OPT_FLAGS="-DOMPI_SKIP_MPICXX=1` as extra build line argument (see the previous mentioned issue)

**Comment by gadagashwini** [comment]
@a-gn Did you check the @jbedorf comment. Thanks!

**Comment by a-gn** [comment]
@gadagashwini Hi, I haven't yet, but I switched to building and installing MVAPICH from source instead of OpenMPI since I needed a working build.

I did try to set this variable like this: `OMPI_SKIP_MPICXX=1 bazel build [...]`, but I still had the same error about `mpicxx.h`. I don't know if setting it like @jbedorf suggested fixes that.

For now I can work with MVAPICH, I will try in the next days again with that option. Thanks :)

**Comment by byronyi** [comment]
> @gadagashwini Hi, I haven't yet, but I switched to building and installing MVAPICH from source instead of OpenMPI since I needed a working build.
> 
> I did try to set this variable like this: `OMPI_SKIP_MPICXX=1 bazel build [...]`, but I still had the same error about `mpicxx.h`. I don't know if setting it like @jbedorf suggested fixes that.
> 
> For now I can work with MVAPICH, I will try in the next days again with that option. Thanks :)

It is likely that your Bazel does sandboxing for its compilation, so setting it as a global ENV might not be as effective as passing it as an option.

**Comment by gadagashwini** [comment]
@a-gn Can we close this issue now since you got workaround. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Comment by a-gn** [comment]
Sure, thanks for your help.
