### ISSUE TITLE
a writing error in tf.contrib.data.map_and_batch

### ISSUE THREAD

**Issue by xixiaoyao** [tensorflow/tensorflow#30004]
## URL(s) with the issue:

https://www.tensorflow.org/api_docs/python/tf/contrib/data/map_and_batch

## Description of issue (what needs changing):

Args document of this API:

> num_parallel_calls: (Optional.) A tf.int32 scalar tf.Tensor, representing the number of elements to process in parallel. If not specified, batch_size * num_parallel_batches elements will be processed in **parallel**.

the last word should be `sequential` rather than `parallel`

**Comment by mrry** [comment]
The word “parallel” is correct here. The point of `map_and_batch` is to parallelize the execution of the map function and the copy into the output batch tensor(s).
