### ISSUE TITLE
Memory Leak Converting Numpy ndarry to Tensor

### ISSUE THREAD

**Issue by zmimlitz** [tensorflow/tensorflow#3000]
I'm working on a small convolution network to identify faces which takes png images and loads them into numpy arrays through PIL.  Once all the images are loaded, they are passed into the tensorflow model through `train_op.train(feed_dict={input:train_images})`.  The problem is that each iteration of the training loop copies a new batch from the total loaded images before passing the batch into train_op and that memory is never released.

I've looked and looked and found several related issues to memory not being released but nothing that I thought really fit my problem or had a working solution.  I am aware that this process of pre-loading images is not ideal, but I have other obstacles to using a queue structure to read the images directly to tensors and I would like to address this as a memory leak.

### Environment info
Operating System: Ubuntu 14.04
Python: 2.7.6
Tensorflow: 0.8.0
CUDA: 7.5
cuDNN: 4.0.7

### Steps to reproduce
Below is a short python script that replicates the problem by loading an image (pass a filepath as argument) and passing it to `tf.image.random_flip_left_right()` while printing out the memory in use by on the computer.  
```
import tensorflow as tf
import psutil
import numpy as np
import Image
import sys
import gc

def printMemUsed(discript):
	print("%s:\t%d" % (discript, psutil.virtual_memory().used))

def main(file):
	sess = tf.InteractiveSession()
	im = Image.open(file)
	arr = np.array(im)
	printMemUsed("After Array Creation")
	arr = flipArr(arr)
	printMemUsed("After Tensor Conversion")
	del arr
	printMemUsed("After Array Deletion")

def flipArr(arr):
	tensor = tf.image.random_flip_left_right(arr)
	arr = tensor.eval()
	return arr	

if __name__ == '__main__':
	main(sys.argv[1])
	printMemUsed("After Scope Lost")
	gc.collect()
	printMemUsed("After gc Collect")
```

For me this program prints:
> After Array Creation:   1196838912
> After Tensor Conversion:        1273106432
> After Array Deletion:   1273106432
> After Scope Lost:       1273106432
> After gc Collect:       1273106432

### What have you tried?
1. As shown in the example, gc.collect() and del do nothing to free the memory, it is not released when the variables pass out of scope (loop or method), only when the program exits, or in my case when I run out of RAM causing the machine to hang until manually restarted.
1. Again I recognize that there are other (perhaps better) ways to get images into tensorflow, but at least for the start I'd like to address why the memory is not released.

### Other Comments
The plot below shows memory usage over the first 5 training rounds of my full model.  The orange points mark the top of each loop.  The first jump is the creation of the batch, which passes all the images through `tf.image.random_flip_left_right()` as in the example above, the second jump from calling `train_op.train(feed_dict={input:train_images})`, passing in the newly created batch.

![memory_leak_plot](https://cloud.githubusercontent.com/assets/10762452/16284315/75e71fec-3885-11e6-915e-a6d9f6610119.png)

**Comment by ibab** [comment]
The problem might be that you're copying the contents of `arr` into the global tensorflow graph each time you call `tf.image.random_flip_left_right(arr)` (as this automatically creates a constant op to hold the contents of `arr`).
The global graph persists until your script finishes.
You could try to create an op that computes the flipped image and then pass in the array using `feed_dict`, as in this modified version of your script:
```
import tensorflow as tf
import psutil
import numpy as np
import Image
import sys
import gc

def printMemUsed(discript):
    print("%s:\t%d" % (discript, psutil.virtual_memory().used))

def main(file):
    sess = tf.InteractiveSession()
    im = Image.open(file)
    arr = np.array(im)
    printMemUsed("After Array Creation")
    arr = flipArr(arr)
    printMemUsed("After Tensor Conversion")
    del arr
    printMemUsed("After Array Deletion")

def flipArr(arr):
    tf_arr = tf.placeholder(dtype=arr.dtype)
    flipped = tf.image.random_flip_left_right(tf_arr)
    arr = flipped.eval(feed_dict={tf_arr: arr})
    return arr  

if __name__ == '__main__':
    main(sys.argv[1])
    printMemUsed("After Scope Lost")
    gc.collect()
    printMemUsed("After gc Collect")
```

It could be helpful to run `print(tf.get_default_graph().as_graph_def())` to check what ends up in your graph after each iteration.

**Comment by zmimlitz** [comment]
Wow that seemed to solved the problem.  Data is now being returned after the batch creation returns.   However at least at the beginning the batch method is not releasing as much as it consumed and train_op is still leaking, but the amount to which they do so decays out after the first few iterations to a (mostly) even use function.  The graph below shows 10 iterations.

![memory_leak_plot_2](https://cloud.githubusercontent.com/assets/10762452/16287145/e0206aca-3895-11e6-944d-87586d853244.png)

Over 400 iterations in use memory increased by less than 100MB, was formally more like 5GB.  Thank you, that was a silly thing for me to do wrong.

**Comment by ibab** [comment]
Are you also using `psutil.virtual_memory().used` to produce the graph?
Not sure if that would give you an accurate picture of the memory consumption.

**Comment by zmimlitz** [comment]
Yes the graph is generated from the output from `psutil.virtual_memory().used`.  The values printed match the behavior I observe in `top` and since I work on this computer remotely through ssh I'm confident that the tensorflow script is the only thing running and taking up meaningful quantities of memory.

**Comment by prb12** [comment]
The comment by @lbab is correct - your original code was effectively adding all of the images to the graph as tensorflow constants!  (InteractiveSession probably increases the risk of this sort of mistake)  You could verify this by saving the graphdef to a file and opening it in an editor. 

@zmimlitz Note: virtual address space size is not usually a good way to measure memory consumption (depending on all sorts of low level implementation details of the heap, thread stacks and other things, you may end up with lots of virtual pages not backed by physical memory).  Resident set size is usually a much better indicator of what pages are actually being used.  We have noticed that the default linux heap implementation seems to have some quite bad behavior in this respect when running TensorFlow.

For problems like this, it is often informative to try running with the [TCMalloc](http://goog-perftools.sourceforge.net/doc/tcmalloc.html) heap, which a) performs much better in both space and cost overheads, and b) includes a very useful heap profiler.

**Comment by zmimlitz** [comment]
Thank you, I'll definitely look into TCMalloc for future memory monitoring.  In the meantime I am satisfied that the original problem I saw was the fault my implementation and has (regardless of viewing) been resolved by the change recommended by @ibab.  I don't seem to have permission to close this Issue but you are welcome to do so.  Thank you for the help.

**Comment by prb12** [comment]
> I don't seem to have permission to close this Issue but you are welcome to do so. Thank you for the help.

You're welcome!
