### ISSUE TITLE
TensorFlow 1.14 docker images lacking

### ISSUE THREAD

**Issue by harahu** [tensorflow/tensorflow#30009]
This template is for miscellaneous issues not covered by the other issue categories.

For questions on how to work with TensorFlow, or support for problems that are not verified bugs in TensorFlow, please go to [StackOverflow](https://stackoverflow.com/questions/tagged/tensorflow).

If you are reporting a vulnerability, please use the [dedicated reporting process](https://github.com/tensorflow/tensorflow/blob/master/SECURITY.md).

For high-level discussions about TensorFlow, please post to discuss@tensorflow.org, for questions about the development or internal workings of TensorFlow, or if you would like to know how to contribute to TensorFlow, please post to developers@tensorflow.org.

---

There doesn't seem to be any docker images published along side the resent tf 1.14 release. Is this intentional, or can we expect them in the near future?

**Comment by angersson** [comment]
You're right -- thanks for the report. Our Docker CI system got confused because of our coincident release of the 2.0 beta (whose containers were pushed instead). I've triggered the builds manually and the images should be available in a few hours.

**Comment by angersson** [comment]
`1.14.0` images have been published and the `latest` tag has been updated too. Thanks for waiting!

**Comment by harahu** [comment]
Thank you so much!

**Comment by angersson** [comment]
Happy to help! I've also pushed an internal change that will prevent the CI from getting confused in the future. Thanks!
