### ISSUE TITLE
Tensorflow Lite Micro fails to build for embedded targets due to dependencing on gemmlowp

### ISSUE THREAD

**Issue by jenselofsson** [tensorflow/tensorflow#30007]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 16.04
- TensorFlow installed from (source or binary): Source
- TensorFlow version: 420473f1fb
- GCC/Compiler version (if compiling from source): arm-none-eabi-g++ 7.3.1

**Describe the problem**
Building Tensorflow Lite Micro fails when building for the bluepill target, due to an unmet dependency.

The problem seems to be caused by the fact that tensorflow/lite/kernels/internal/common.h includes tensorflow/lite/kernels/internal/optimized/cpu_check.h. 

tensorflow/lite/kernels/internal/common.h is in turn included by the kernels in Tensorflow Lite Micro.

This adds gemmlowp as a dependency, which causes Tensorflow Lite Micro to not build when building for eg Cortex-M3 in the bluepill case.

**Provide the exact sequence of commands / steps that you executed before running into the problem**
$ make -f tensorflow/lite/experimental/micro/tools/make/Makefile TARGET=bluepill test

**Any other info / logs**
`
In file included from tensorflow/lite/experimental/micro/tools/make/downloads/gemmlowp/public/../internal/dispatch_gemm_shape.h:23,
                 from tensorflow/lite/experimental/micro/tools/make/downloads/gemmlowp/public/gemmlowp.h:19,
                 from ./tensorflow/lite/kernels/cpu_backend_context.h:21,
                 from ./tensorflow/lite/kernels/internal/optimized/cpu_check.h:18,
                 from ./tensorflow/lite/kernels/internal/common.h:25,
                 from tensorflow/lite/experimental/micro/kernels/depthwise_conv.cc:18:
tensorflow/lite/experimental/micro/tools/make/downloads/gemmlowp/public/../internal/multi_thread_gemm.h: In member function 'void gemmlowp::BlockingCounter::Wait()':
tensorflow/lite/experimental/micro/tools/make/downloads/gemmlowp/public/../internal/multi_thread_gemm.h:203:14: error: 'std::this_thread' has not been declared
         std::this_thread::sleep_for(std::chrono::milliseconds(1));
`

Full error log:
[errorlog.txt](https://github.com/tensorflow/tensorflow/files/3310477/errorlog.txt)

**Comment by ladyada** [comment]
just verified & ditto for `TARGET=arduino` (trying to compile for cortex m4 in arduino using the mock_speech generator)

**Comment by wangtz** [comment]
Pete's recent commit should have solved this problem. https://github.com/tensorflow/tensorflow/commit/97123eff9496776d31cac2131ad65f07e9614f95

**Comment by ladyada** [comment]
Thanks @petewarden! I'll try this out and add to our Arduino-ready library https://github.com/adafruit/Adafruit_TFLite_Micro_Speech - we got it [working really nicely on a Cortex M4](https://blog.adafruit.com/2019/06/24/tiny-machine-learning-on-the-edge-with-tensorflow-lite-running-on-samd51-arduino-tensorflow-tinyml-tensorflow/)

Here's a video of it in action :)
 [![Tiny Machine Learning on the Edge with TensorFlow Lite Running on SAMD51](http://img.youtube.com/vi/cn9PEDX_qLk/0.jpg)](http://www.youtube.com/watch?v=cn9PEDX_qLk "Tiny Machine Learning on the Edge with TensorFlow Lite Running on SAMD51")

**Comment by jenselofsson** [comment]
> Pete's recent commit should have solved this problem. [97123ef](https://github.com/tensorflow/tensorflow/commit/97123eff9496776d31cac2131ad65f07e9614f95)

That seems to have fixed it, thanks!
