### ISSUE TITLE
FlexAudioSpectrogram ops is not supported by the tflite interpreter

### ISSUE THREAD

**Issue by zhizunbao-y** [tensorflow/tensorflow#30003]
When I run a model converted from speech command demo using lite Interpreter, the error is:
Traceback (most recent call last):
  File "/home/yuan/anaconda3/envs/TFLite/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/home/yuan/tensorflow-master/tensorflow/examples/speech_commands/audio/audio_processor_lite.py", line 41, in run
    self._interpreter.allocate_tensors()
  File "/home/yuan/anaconda3/envs/TFLite/lib/python3.7/site-packages/tensorflow_core/lite/python/interpreter.py", line 198, in allocate_tensors
    return self._interpreter.AllocateTensors()
  File "/home/yuan/anaconda3/envs/TFLite/lib/python3.7/site-packages/tensorflow_core/lite/python/interpreter_wrapper/tensorflow_wrap_interpreter_wrapper.py", line 106, in AllocateTensors
    return _tensorflow_wrap_interpreter_wrapper.InterpreterWrapper_AllocateTensors(self)
RuntimeError: Regular TensorFlow ops are not supported by this interpreter. Make sure you invoke the Flex delegate before inference.Node number 0 (FlexAudioSpectrogram) failed to prepare.
But the model provided by speech command android demo works  well. (https://github.com/tensorflow/examples/blob/master/lite/examples/speech_commands/android/README.md)

**Comment by achandraa** [comment]
Please help us to know which TensorFlow version you are using. Thanks!

**Comment by zhizunbao-y** [comment]
> Please help us to know which TensorFlow version you are using. Thanks!

OK. I used "pip3 install tf-nightly" to install the tensorflow, and the version is 1.14.1-dev20190615

**Comment by miaout17** [comment]
Hi Alan, could you take a look at the speech demo, or do you know who's familar with this?

**Comment by vihari1729** [comment]
Try this
tflite_convert
--output_file=/output.tflite
--graph_def_file /path/to/my_frozen_graph.pb
--input_arrays decoded_sample_data,decoded_sample_data:1
--output_arrays labels_softmax
--allow_custom_ops

**Comment by jaeyoo** [comment]
@zhizunbao-y 

Hi, could you please try 1) tf-nightly >= 2.3.0 and 2) flex op?
```
converter = tf.lite.TFLiteConverter.from_saved_model(your_model)
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS, tf.lite.OpsSet.SELECT_TF_OPS]
tflite_model = converter.convert()
```

**Comment by kumariko** [comment]
@zhizunbao-y We are checking to see if you still need help on this issue, as you are using an older version of tensorflow(1.x) which is officially considered as end of life. We recommend that you upgrade to 2.6 which is latest stable version of TF and let us know if the issue still persists in newer versions.Thanks!
