### ISSUE TITLE
building error on win7 with VS2015: ADD_LIBRARY for library tf_contrib_tpu_ops without any source files 

### ISSUE THREAD

**Issue by cj741** [tensorflow/tensorflow#30015]
System information

OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Win7 X64
Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
TensorFlow installed from (source or binary): source
TensorFlow version:1.13.1
Python version:3.6
Installed using virtualenv? pip? conda?:conda
Bazel version (if compiling from source):cmake
GCC/Compiler version (if compiling from source):vs 2015
CUDA/cuDNN version:no cuda
GPU model and memory:no gpu
Describe the problem
when I use cmake GUI config TF, it show me the folowing error message:
"You have called ADD_LIBRARY for library tf_contrib_tpu_ops without any source files. This typically indicates a problem with your CMakeLists.txt file
CMake Error at tf_python.cmake:217 (message):
Python module not found: tensorflow/contrib/tpu/ops"
I think the problem is all the source files were moved to "tensorflow/core/tpu", do you have idea how to change the path from "tensorflow/contrib/tpu/ops" to "tensorflow/core/tpu"? or how to block the tpu module in config file?
many thanks~
Provide the exact sequence of commands / steps that you executed before running into the problem

**Comment by achandraa** [comment]
Can you try building TensorFlow from source using Bazel since support for cmake is no longer there. You can follow the steps mentioned in [TensorFlow website](https://www.tensorflow.org/install/source_windows) for reference. Let us know you are stuck anywhere. Thanks!

**Comment by cj741** [comment]
Hi Achandraa,
Thanks for you response, I have looked the instruction you mentioned, it tell how to build a whl file. If I want to generate a vs .sln and build a .lib file, what should I do?
Thanks!

**Comment by cj741** [comment]
Hello Achandrra and Ymodak, 
Any suggestion on it?
Thanks~

**Comment by ymodak** [comment]
@cj741 Apologies for the delay in response. We no longer support cmake builds and recommend to use bazel to build tensorflow from source. Thanks!
