### ISSUE TITLE
Lossy conversion from float32 to uint8. Range [0, 1]. Convert image to uint8 prior to saving to suppress this warning.

### ISSUE THREAD

**Issue by aquadzn** [tensorflow/tensorflow#30025]
Version : tensorflow-gpu==2.0.0-beta1
OS : Ubuntu 18.04 LTS

`W0621 10:32:12.746317 139752995510080 util.py:64] Lossy conversion from float32 to uint8. Range [0, 1]. Convert image to uint8 prior to saving to suppress this warning.`

not something important but do you know how to remove this warning?

I already included 
`import os
import tensorflow as tf
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3'`

**Comment by martinwicke** [comment]
Can you add the code which generates this warning? It's hard to say whether it's important without knowing what you were trying to do.

**Comment by aquadzn** [comment]
> Can you add the code which generates this warning? It's hard to say whether it's important without knowing what you were trying to do.

https://github.com/aquadzn/neural-style/blob/master/model.py

**Comment by martinwicke** [comment]
This warning is generated by imageio, not tensorflow: https://github.com/imageio/imageio/blob/ef1f24f23ae959cccf646128dba7b403638d9b5e/imageio/core/util.py

You can use tf.convert_image_dtype to make sure that images are properly scaled to 0...255.

**Comment by SuperShinyEyes** [comment]
In TF 1.14.0, it's [tf.image.convert_image_dtype](https://www.tensorflow.org/api_docs/python/tf/image/convert_image_dtype).
