### ISSUE TITLE
TF 2.0 tensor.numpy() inside of map() functions

### ISSUE THREAD

**Issue by Ryandry1st** [tensorflow/tensorflow#30035]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using): 2.0.0b1
- Are you willing to contribute it (Yes/No): No

**Describe the feature and the current behavior/state.**
Currently, there is no way to get a numpy array from a tensor during graph execution, even if it is well defined. Specifically I am working with a funciton to map to a dataset, where I would like to get the np array from the tensor, however with eager execution disabled (due to static graph execution) it is not possible. There does not appear to be a workaround because the normal workaround in static cases is the py_func() function but that can only return tensors, defeating the purpose in this case.

**Will this change the current api? How?**
No significant changes beyond adding a method that would allow for numpy arrays to be returned during a map function. It would likely have to be specific because there are a number of times that one could improperly use this outside of a use case like dataset.map

**Who will benefit with this feature?**
developers working with custom datasets which require custom mapped functions to interact with other libraries that expect numpy arrays. Definitely a larger number of the research community could make use of this than hobbyist to be sure.

**Any Other info.**

**Comment by jsimsa** [comment]
Could you please provide an example that illustrates the use case that you would like to support? Thanks.

**Comment by Ryandry1st** [comment]
Sure, I am looking at some image preprocessing techniques, ideally getting the advantage of preprocessing rather than using the ImageDataGenerator option. In order to do this many libraries would require the numpy array data rather than a tensor. A similar desire, although in a purely TF implementation, was mentioned in this thread: https://twitter.com/pmdanton/status/1144388777235947520.

**Comment by jsimsa** [comment]
IIUC, [numpy_function](https://www.tensorflow.org/api_docs/python/tf/numpy_function) used within `tf.data.Dataset.map` should address your use case.

**Comment by Ryandry1st** [comment]
That solves the problem for me, thank you!
