### ISSUE TITLE
bazel 0.26.1 git rules break on Windows

### ISSUE THREAD

**Issue by compnerd** [tensorflow/tensorflow#30034]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10 (build 18912.1001)
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): source
- TensorFlow version: master
- Python version: 2.7
- Installed using virtualenv? pip? conda?:
- Bazel version (if compiling from source): 0.26.1
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version:
- GPU model and memory:

**Describe the problem**

The default git worker rules from bazel 0.26.1 actually assume bash.  However, Windows 10 with WSL will provide a bash that is a redirection to the default WSL installation.  This is both difficult to track down as well as behaves incorrectly when trying to build TensorFlow for Windows.

**Provide the exact sequence of commands / steps that you executed before running into the problem**

`bazel --config=opt --config=v2 build //tensorflow:...`

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by compnerd** [comment]
CC: @saeta

**Comment by compnerd** [comment]
BTW, it seems that bazel 0.27.0 rewrote the git rules to avoid the inline generated bash script.  This should help, though it seems that the current version for bazel for TensorFlow is 0.26.1.  I'm unfortunately, not familiar enough with bazel to figure out how to override the rules with the one from 0.27.0

**Comment by saeta** [comment]
Not sure at all, but it might make more sense to figure out how to upgrade the version of Bazel TensorFlow uses directly to 0.27.0 instead, unless there's something else that's blocking... (Guesses: CI infra, maybe?)

**Comment by compnerd** [comment]
Hmm, is there an easy way to check if the infra will support the bump?

**Comment by saeta** [comment]
Hmm, not sure. Maybe @gunan might know?

**Comment by mihaimaruseac** [comment]
There is work in progress to upgrade bazel but it is going to take some time as it is currently blocked on another infrastructure release task

**Comment by gunan** [comment]
I think this upgrade is complete, I forgot to update this issue when we fixed the problem. Closing.
