### ISSUE TITLE
ParseSequenceExample should return Ragged Tensor or have an option for this

### ISSUE THREAD

**Issue by bionicles** [tensorflow/tensorflow#30045]
**System information**
- TensorFlow version (you are using): 1.14r
- Are you willing to contribute it (Yes/No): Yes

**Describe the feature and the current behavior/state.**
Right now, ParseSequenceExample returns sparse tensors. Instead, it should return Ragged tensors. This causes issues with our molecular dynamics project because padded tensors contain zeros which are misinterpreted as extra atoms in simulation. As a workaround we have to make lists of tensors, which interrupts training. Will try another approach by mapping twice

Sequence Examples are suited to make Ragged tensors because they both address the same variable-length issue

**Will this change the current api? How?**
dataset = tf.data.TFRecordDataset(files)
dataset = dataset.batch(batch_size=BATCH_SIZE)
dataset = dataset.map(parse_function) 
```
def parse_function(batch):
    ... define batch features ...
    return parse_sequence_example(batch, ragged=True, context_features=context_features, sequence_features=sequence_features)
```
**Who will benefit with this feature?**
people who don't want to pause training to postprocess data coming out of TFRecordDataset 

**Any Other info.**
it would be nice to return a tuple of ragged tensors for each sequence feature. context features can remain as tensors

Happy to try workarounds but it's hard to share our code as it requires making a special proteins dataset of TFRecords

**Comment by bionicles** [comment]
Ugh, not sure how to accomplish this! How do you parse tfrecords of sequence examples into Ragged Tensors or just lists/tuples of tensors? It works only with batch_size 1, higher batch sizes try to concat the tensors and fail. 

the `for item in dataset` pattern is cool but not sure how to get multiple elements if we can't use Dataset.batch

i guess we could just append to a list until the list is full and then train and empty the list. but that doesn't seem like real batch training. Keras models don't support ragged tensors either, which is a bummer, because it's a great idea for NLP and unstructured data

**Comment by edloper** [comment]
* We are planning to add RaggedTensor support to ParseSequenceExample.  In the mean-time, you may be able to use the following:

```
dataset = dataset.map(tf.RaggedTensor.from_sparse)
```

* We are actively working on adding support for RaggedTensor to Keras.

**Comment by bionicles** [comment]
Thank you @edloper! I was also thinking windows might help

**Comment by rmothukuru** [comment]
@bionicles,
Sorry for the delayed response. The documentation of [ParseSequenceExampleV2](https://www.tensorflow.org/api_docs/cc/struct/tensorflow/ops/parse-sequence-example-v2/attrs) and [tf.io.parse_single_sequence_example](https://www.tensorflow.org/api_docs/python/tf/io/parse_single_sequence_example) shows the support of **`Ragged Tensor`**. 

Can you please let us know if that is what you are looking for? Thanks!
