### ISSUE TITLE
Installation documentation and mac wheels

### ISSUE THREAD

**Issue by timokau** [tensorflow/tensorflow#30042]
## URL(s) with the issue:

https://www.tensorflow.org/install/pip

### Clear description

There are no binary wheels for tensorflow 1.14 for mac (should be [here](https://storage.googleapis.com/tensorflow/mac/cpu/tensorflow-1.14.0-py3-none-any.whl)) and the documentation page still points to 1.13.

Is 1.14 still considered unstable? Was the wheel generation and documentation update simply forgotten? Or is it normal that it takes a couple of days after the release?

**Comment by patricksnape** [comment]
Any update on when the wheels will appear on the googleapis storage? They exist on pypi?

**Comment by mihaimaruseac** [comment]
Seems there was a bug in the release process pipeline.

We'll (try to) solve this issue this week, sorry about this.

**Comment by angersson** [comment]
Added @av8ramit too. I wonder if there's a desync between our upload scripts.

**Comment by av8ramit** [comment]
Taking a look now.

**Comment by av8ramit** [comment]
It appears the 1.14 build upload was not completed. Can you try again now please?

**Comment by timokau** [comment]
Yes, the downloads work now! The [documentation](https://www.tensorflow.org/install/pip) still points to 1.13 though.

**Comment by mihaimaruseac** [comment]
I think @lamberta can fix the documentation link, assigning to him

**Comment by lamberta** [comment]
Site updated: https://www.tensorflow.org/install/pip#package-location

**Comment by timokau** [comment]
Thank you!
