### ISSUE TITLE
Tensorflow Variables Copy Issue

### ISSUE THREAD

**Issue by RuofanKong** [tensorflow/tensorflow#3005]
I am using Tensorflow 0.8 to train the Deep Neural Networks. Currently, I encounter an issue that I want to define two exact same Neural Networks N1 and N2, and I train N1, during the training loop, I copy updated weights from N1 to N2 every 4 iterations. In fact, I know there is way using `tf.train.saver.save()` to save all N1 weights into a `.ckpt` file on Disk, and using `tf.train.saver.restore()` to load those weights from `.ckpt` file, which is equivalent to the copy functionality. However, this load/reload will impact the training speed, and I wonder if there are other more efficient ways to do the copy (For example, do in-memory copy, etc.). Thanks!

**Comment by andydavis1** [comment]
This is a question better suited for StackOverflow. Please ask it there and tag it with the `tensorflow` tag
