### ISSUE TITLE
tensorflow docker images with python3.6 as default version

### ISSUE THREAD

**Issue by zh794390558** [tensorflow/tensorflow#30057]
Since many repo using python 3.6 as default version, so recommend using python3.6 as default version for tensorflow docker images.

**Comment by wdirons** [comment]
On this page: https://hub.docker.com/r/tensorflow/tensorflow/ it states:

> Images built after May 20 2019 (TF nightly, plus TF versions 1.14 and onward) are based on Ubuntu 18.04. Earlier images are based on Ubuntu 16.04.

Python 3.6 is the default for Ubuntu 18.04, so while the web page doesn't clearly state it. Starting from TF 1.14 the `-py3` docker containers will have python 3.6 as the default.


```
$ docker run --rm tensorflow/tensorflow:1.14.0-py3 python --version
Python 3.6.8


FYI @angersson - if you want to consider updating the doc for that. [The section that says python 3.5 is now wrong.]
```

**Comment by angersson** [comment]
Thanks @wdirons! I've updated the page.

@zh794390558, @wdirons is correct -- recently built `py3` images (1.14+ and `nightly` images) include Python 3.6 thanks to Ubuntu 18.
