### ISSUE TITLE
TensorBoard doesn't display Events under Safari

### ISSUE THREAD

**Issue by jd20** [tensorflow/tensorflow#3006]
I've been attempting to view events in TensorBoard, using both the mnist_with_summaries.py tutorial, and a much simpler example from the "Hello, TensorFlow!" article (example code at the bottom of this page: https://www.oreilly.com/learning/hello-tensorflow). In both cases, I can see the Graph, but nothing under Events.

### Environment info
Operating System: OSX 10.11.5
Running Python 3.5.1 (installed from the DMG installer on python.org)
Installed tensorflow 0.9.0rc0 via pip3

### Steps to reproduce
1. Paste the following code into a file:

```python
import tensorflow as tf

x = tf.constant(1.0, name='input')
w = tf.Variable(0.8, name='weight')
y = tf.mul(w, x, name='output')
y_ = tf.constant(0.0, name='correct_value')
loss = tf.pow(y - y_, 2, name='loss')
train_step = tf.train.GradientDescentOptimizer(0.025).minimize(loss)

for value in [x, w, y, y_, loss]:
    tf.scalar_summary(value.op.name, value)

summaries = tf.merge_all_summaries()

sess = tf.Session()
summary_writer = tf.train.SummaryWriter('log_simple_stats', sess.graph)

sess.run(tf.initialize_all_variables())
for i in range(100):
    summary_writer.add_summary(sess.run(summaries), i)
    sess.run(train_step)
```

2. Run the code, then after it is complete, run "tensorboard --logdir=log_simple_stats/"
3. Go to localhost:6006, under Events, there are no Runs listed.
### What have you tried?
1. Adding a flush() call to the summary writer
2. Copying the css and js directories under tensorboard/lib, from source (this had no effect, so I reverted the change)

### Logs or other output that would be helpful
The log output looks like:
Looking in log_simple_stats reveals:
```bash
-rw-r--r--  1 jason  staff  19030 Jun 23 01:11 events.out.tfevents.1466669497.hostname.local
MD5 (events.out.tfevents.1466669497.hostname.local) = f7032e6e643bbac6b0009411a02cb8db
```

And the logs from tensorboard:

```bash
~ tensorboard --logdir=log_simple_stats/
WARNING:tensorflow:Found more than one graph event per run. Overwriting the graph with the newest event.
WARNING:tensorflow:IOError [Errno 2] No such file or directory: '/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/tensorflow/tensorboard/TAG' on path /Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/tensorflow/tensorboard/TAG
WARNING:tensorflow:Unable to read TensorBoard tag
Starting TensorBoard  on port 6006
(You can navigate to http://0.0.0.0:6006)
127.0.0.1 - - [23/Jun/2016 01:11:11] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [23/Jun/2016 01:11:11] "GET /lib/css/global.css HTTP/1.1" 200 -
127.0.0.1 - - [23/Jun/2016 01:11:11] "GET /external/d3/d3.min.js HTTP/1.1" 200 -
127.0.0.1 - - [23/Jun/2016 01:11:11] "GET /external/lodash/lodash.min.js HTTP/1.1" 200 -
...
```

**Comment by jd20** [comment]
After re-reading the TensorBoard README again, I realized what the issue might be... I was using Safari instead of Chrome. Trying out Chrome 51, the Events tab displays properly now. TensorBoard broken under Safari 9.1.1, and title updated to reflect.

**Comment by danmane** [comment]
I think the pip package is outdated; the particular issue you describe (graphs tab works, events tab never works) is fixed in a newly-built pip package, and we will rebuild the pip package before release. However, in the local testing I'm doing, Safari is pretty spotty, I think because it doesn't play well with webcomponents/Polymer. We don't currently consider Safari a supported browser so I don't invest much in making sure that it's working. But both Chrome and FF are fine.

If you feel strongly that we should be paying more attention to Safari let me know.

**Comment by jd20** [comment]
I don't think missing Safari support is that big a deal (more just a nice-to-have), but it may help others if TB displayed a warning when loading inside of Safari, explaining it's not a supported browser (like a dismiss-able banner, or even on the command line if it detects a Safari user agent). I'm sure like me, others on the Mac will make the same mistake, since in the tutorials for TensorBoard there's no mention of browser incompatibilities. Even the first time I skimmed the TensorBoard README, I missed the browser compatibility warning.

**Comment by episodeyang** [comment]
Just for the record, supporting all popular browsers is a big deal and must-to-have. Now tensorboard is working in safari after the update :)

In the long run, cross-browser support should stay.
