### ISSUE TITLE
Method mentioned in documentation is missing: tf.keras.preprocessing.text.tokenizer_from_json

### ISSUE THREAD

**Issue by alexwal** [tensorflow/tensorflow#30061]
**System information**
- TensorFlow version: v2.0.0-beta0-16-g1d91213fe7 2.0.0-beta1

**Describe the current behavior**
Error raised when attempting to call `tf.keras.preprocessing.text.tokenizer_from_json`:
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
----> 1 tf.keras.preprocessing.text.tokenizer_from_json

AttributeError: module 'tensorflow.python.keras.api._v2.keras.preprocessing.text' has no attribute 'tokenizer_from_json'
```

**Describe the expected behavior**
I expect this method to be callable per the documentation of `tf.keras.preprocessing.text.Tokenizer.to_json` (below), which says we can use `keras.preprocessing.text.tokenizer_from_json(json_string)` to load a tokenizer.

Otherwise, there's no obvious way to use the output of `Tokenizer.to_json` to restore a tokenizer.

```
Signature: tf.keras.preprocessing.text.Tokenizer.to_json(self, **kwargs)
Docstring:
Returns a JSON string containing the tokenizer configuration.
To load a tokenizer from a JSON string, use
`keras.preprocessing.text.tokenizer_from_json(json_string)`.

# Arguments
    **kwargs: Additional keyword arguments
        to be passed to `json.dumps()`.

# Returns
    A JSON string containing the tokenizer configuration.
```
**Code to reproduce the issue**
```python3
json_string = tf.keras.preprocessing.text.Tokenizer().to_json()
tf.keras.preprocessing.text.tokenizer_from_json(json_string)
```

**Comment by yongtang** [comment]
Added a PR #30062 for the fix.
