### ISSUE TITLE
No such package 'tensorflow/contrib/android': BUILD file not found on package path

### ISSUE THREAD

**Issue by abdou31** [tensorflow/tensorflow#30065]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10 x64
- TensorFlow installed from (source or binary): source
- TensorFlow version: last version from Github
- Python version: 3.6
- Installed using virtualenv? pip? conda?:
- Bazel version (if compiling from source): 0.26
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 10.0/7.4
- GPU model and memory: Nivida Geforce 840m

**Describe the problem**

I try to use this tool for building .so file using this command line:
> bazel build -c opt //tensorflow/contrib/android:libtensorflow_inference.so  --crosstool_top=//external:android/crosstool --host_crosstool_top=@bazel_tools//tools/cpp:toolchain --cxxopt=-std=c++11  --cpu=armeabi-v7a

But I get this error :
> ERROR: Skipping '//tensorflow/contrib/android:libtensorflow_inference.so': no such package 'tensorflow/contrib/android': BUILD file not found on package path
WARNING: Target pattern parsing failed.
ERROR: no such package 'tensorflow/contrib/android': BUILD file not found on package path
INFO: Elapsed time: 0.543s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)

How can I solve it?
Thanks

**Comment by ymodak** [comment]
Were you able to solve this issue?

**Comment by abdou31** [comment]
I did not continue with this command line,
I followed other instruction to generate tflite file model

**Comment by ymodak** [comment]
Closing this issue since you were able to get a workaround. Feel free to reopen if have further questions. Thanks!

**Comment by abdou31** [comment]
Why you closed this issue?
You did not give me any solution to my problem.

**Comment by jdduke** [comment]
I'm not able to repro the problem using the BUILD rule @ https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/android/BUILD#L61. It's possible there are issues with building on a Windows host, though I don't see an immediate reason why. In any case, TensorFlow Mobile (which contrib/android supports) has been deprecated in favor of TensorFlow Lite. We'll be sure to update the documentation accordingly.

**Comment by abdou31** [comment]
I have used python tflite converter and I get tflite model. So for now I want to know how can I use tflite model and how can I extract features from this file?

**Comment by jdduke** [comment]
For general TensorFlow Lite usage please see the guide @ https://www.tensorflow.org/lite/guide. There are complete steps for using inference after you've successfully converted your model.

**Comment by abdou31** [comment]
this documentation didn't have instruction how it works the extraction of features from the output nodes!

**Comment by jdduke** [comment]
Extracting output features is model-dependent. The output tensors are simply typed buffers. Here is some [additional guidance](https://www.tensorflow.org/lite/guide/faq#how_do_i_determine_the_inputsoutputs_for_graphdef_protocol_buffer) for better understanding model outputs.

**Comment by abdou31** [comment]
Thanks, I will seet it

**Comment by jtdutta1** [comment]
You're getting this error because there is no contrib module in the master branch. Switch to a release branch and you'll get contrib there.
