### ISSUE TITLE
Support Sparse Tensors in py_function

### ISSUE THREAD

**Issue by novog** [tensorflow/tensorflow#30069]
- TensorFlow version (you are using): 2.0.0b0
- Are you willing to contribute it (Yes/No): No

**Describe the feature and the current behavior/state.**
Currently, sparse tensors don't seem to be supported as inputs to `py_function`. Attempting to pass one results in an error like "`TypeError: Tensors in list passed to 'input' of 'EagerPyFunc' Op have types [<NOT CONVERTIBLE TO TENSOR>] that are invalid.`". Example:

    def dataset_map_sparse_test():
        input_data_sparse = tf.SparseTensor(indices=[[0, 0], [1, 2]], values=[1, 2], dense_shape=[3, 4])
        input_data_dense = tf.sparse.to_dense(input_data_sparse)
    
        ds_dense = tf.data.Dataset.from_tensor_slices(input_data_dense)
        ds_sparse = tf.data.Dataset.from_tensor_slices(input_data_sparse)

        def inner_fn(*input):
            return input

        def outer_fn(*input_data):
            return tf.py_function(
                inner_fn,
                input_data,
                (tf.int32,))

        # this works
        ds_dense_mapped = ds_dense.map(outer_fn)
        print(next(iter(ds_dense_mapped)))

        # this results in the error specified above
        ds_sparse_mapped = ds_sparse.map(outer_fn)
        print(next(iter(ds_sparse_mapped)))

**Will this change the current api? How?**
Yes. The `inp` parameter of `py_function` currently accepts a list of `Tensor` objects; this change would broaden it to accept either `Tensor`s or `SparseTensor`s. (Possibly `_TensorLike`s?)

**Who will benefit with this feature?**
Anyone wishing to pass sparse tensors to a `py_function`-wrapped function. There are situations where this wrapping is necessary; for example, functions passed to `Dataset.map` cannot perform certain operations unless the function is wrapped using `py_function`.

**Any Other info.**

**Comment by alextp** [comment]
I think now that we have compositetensor and typespec it should be straightforward to implement sparsetensor support in py_function by treating all composites generically.

I don't have the bandwidth to do this now, so leaving as contributions welcome.

**Comment by pradyumna1** [comment]
@alextp I would like to work on this, can I please go ahead?

**Comment by novog** [comment]
Would "all composites" include ragged tensors, or should I create a separate feature request for that? Thanks!

**Comment by alextp** [comment]
Composites include ragged tensors and a lot of other things as well.

**Comment by alextp** [comment]
@pradyumna1 please go ahead!

**Comment by novog** [comment]
I notice that someone had already created issue #26453 (Allow py_function to support functions that return RaggedTensor). Implementing this feature using composite tensors would also satisfy that issue.

**Comment by minhtriet** [comment]
I made changes in file `op_def_library.py` so that CompositeTensor is now allowed. However, there are some missing features of `CompositeTensor` that does not allow adding the node to the computation graph, for example `._as_tf_output()`, which is used in function `_create_c_op`. That function only appears in class `Tensor`. Could you advise on this @alextp?

**Comment by novog** [comment]
@minhtriet, in a similar feature request (#27679), @edloper provided a helpful workaround in the form of a wrapper around `py_function`, which he suggested could be integrated into `_internal_py_func`. Does that help?

**Comment by minhtriet** [comment]
Thank you @novog, I could not read work on it right now, would get back to you in a couple of days

**Comment by minhtriet** [comment]
So, I updated `tf.py_function` in [my fork](https://github.com/minhtriet/tensorflow/blob/master/tensorflow/python/ops/script_ops.py#L373)  

Rerunning the code, the error is
```
2019-12-14 21:38:52.367270: I tensorflow/core/common_runtime/process_util.cc:115] Creating new thread pool with default inter op setting: 4. Tune using inter_op_parallelism_threads for best performance.
(<tf.Tensor: id=20, shape=(4,), dtype=int32, numpy=array([1, 0, 0, 0])>,)
2019-12-14 21:38:53.274875: W tensorflow/core/framework/op_kernel.cc:1622] OP_REQUIRES failed at iterator_ops.cc:929 : Invalid argument: {{function_node __inference_Dataset_map_outer_fn_28}} pyfunc_1 returns 3 values, but expects to see 1 values.
	 [[{{node PyFuncStateless}}]]
Traceback (most recent call last):
  File "C:/Users/cool/Code/tf_contrib_conda/test.py", line 28, in <module>
    dataset_map_sparse_test()
  File "C:/Users/cool/Code/tf_contrib_conda/test.py", line 26, in dataset_map_sparse_test
    print(next(iter(ds_sparse_mapped)))
  File "C:\Users\cool\Miniconda3\envs\tf_contrib_conda\lib\site-packages\tensorflow_core\python\data\ops\iterator_ops.py", line 622, in __next__
    return self.next()
  File "C:\Users\cool\Miniconda3\envs\tf_contrib_conda\lib\site-packages\tensorflow_core\python\data\ops\iterator_ops.py", line 666, in next
    return self._next_internal()
  File "C:\Users\cool\Miniconda3\envs\tf_contrib_conda\lib\site-packages\tensorflow_core\python\data\ops\iterator_ops.py", line 651, in _next_internal
    output_shapes=self._flat_output_shapes)
  File "C:\Users\cool\Miniconda3\envs\tf_contrib_conda\lib\site-packages\tensorflow_core\python\ops\gen_dataset_ops.py", line 2672, in iterator_get_next_sync
    _six.raise_from(_core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.InvalidArgumentError: {{function_node __inference_Dataset_map_outer_fn_28}} pyfunc_1 returns 3 values, but expects to see 1 values.
	 [[{{node PyFuncStateless}}]] [Op:IteratorGetNextSync]
```

My guess is that the creation of sparsed tensor works, but somehow `next()` does not work because `pyfunc_1` returned 3 values, which I could not debug. Could someone give me a pointer?

**Comment by alextp** [comment]
This issue likely happens because the sparsetensor isn't being unpacked into its 3 component values.

**Comment by minhtriet** [comment]
Hi @alextp, thank you for the reply. Right now I am using `tensorflow_core.python.util.nest.pack_sequence_as` to produce the output ([here](https://github.com/minhtriet/tensorflow/blob/master/tensorflow/python/ops/script_ops.py#L461)), but somehow `_is_composite_tensor` returns `False`, which I do not understand why

The call stack is 

```
_sequence_like, nest.py:149
pack_sequence_as, nest.py:471
_get_defun_inputs, func_graph.py:1160
_get_defun_inputs_from_args, func_graph.py:1062
func_graph_from_py_func, func_graph.py:837
_create_graph_function, function.py:2041
_maybe_define_function, function.py:2150
_get_concrete_function_internal_garbage_collected, function.py:1848
_get_concrete_function_internal, function.py:1854
__init__, dataset_ops.py:2695
__init__, dataset_ops.py:3416
map, dataset_ops.py:1211
dataset_map_sparse_test, test.py:25          << This is the test from OP
<module>, test.py:28
```

**Comment by alextp** [comment]
That doesn't make sense to me because SparseTensor is a composite: https://github.com/tensorflow/tensorflow/blob/bb45024ae9d3df0127d1c1056b08f25e60ba601c/tensorflow/python/framework/sparse_tensor.py#L48

So it's likely something else that is going on here.
