### ISSUE TITLE
Device getting slower when running tensorflow c++

### ISSUE THREAD

**Issue by Wang-Guanyu** [tensorflow/tensorflow#30068]
Dear all, I have encountered a problem that tensorflow inference time is getting slower. 

Situation:

Our device is used in the production line and tensorflow prediction is one of the module in the whole project. Since in production line the device is operating for a very long time (24 hours non-stop), after a few days (probably 3-5 days) we can feel that the device is getting slower and tensorflow inference time is about 2-3 times as usual. We suspect it was caused by GPU memory leak or some other issues. May I ask has anyone encountered such problem? How should I do with this situation?

Environment:

OS: Windows 10 (64 bits)
CPU: I7 - 6th Generation
GPU: Nvidia GTX 1050 Ti
TF Version: r1.4
CMake build with VS 2015

**Comment by Wang-Guanyu** [comment]
BTW, if I want to reset GPU memory during runtime (maybe use session->Close() ), what should I do or how should I modify the source code? Seems currently session->Close() will not free GPU memory. Thanks!

**Comment by ymodak** [comment]
To reset gpu memory allocation; See https://github.com/tensorflow/tensorflow/issues/17048#issuecomment-367948448

**Comment by ymodak** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
