### ISSUE TITLE
AttributeError: module 'tensorflow' has no attribute 'set_random_seed'

### ISSUE THREAD

**Issue by Jie-Yuan** [tensorflow/tensorflow#30070]
tf2.0

    tf.set_random_seed(self._seed)
AttributeError: module 'tensorflow' has no attribute 'set_random_seed'

**Comment by eduardofv** [comment]
Moved to `tf.random.set_seed()`
https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/random/set_seed

**Comment by gadagashwini** [comment]
@Jie-Yuan Were you able to resolve this issue?

**Comment by gadagashwini** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
