### ISSUE TITLE
Can build tflite with xcode ?

### ISSUE THREAD

**Issue by weinixuehao** [tensorflow/tensorflow#30072]
I build tflite with https://www.tensorflow.org/lite/guide/build_ios and set not optimizing code for debug code in tflite 
Though can hit breakpoint and step by step to debug sources but has some messy so i want build tflite from source with xcode

**Comment by achandraa** [comment]
@weinixuehao : Thanks for reaching out to us. Can you please help us to understand more about the issue you are facing as in which TensorFlow version you are using, which step you are stuck in. It will help us to resolve the issue faster. Thanks!

**Comment by weinixuehao** [comment]
I built tflite binary with debug symbols by -g option but debug experience is not better. some variable could not view value and step by step debuging has some messy so i wanted build source directly with xcode but this way need to know which files to compile
