### ISSUE TITLE
Default values not listed for hyperparameters in tfp ExponentiatedQuadratic class

### ISSUE THREAD

**Issue by alinaselega** [tensorflow/tensorflow#30085]
## URL(s) with the issue:

https://www.tensorflow.org/probability/api_docs/python/tfp/positive_semidefinite_kernels/ExponentiatedQuadratic

## Description of issue (what needs changing):

List default values for hyperparameters `amplitude` and `length_scale` that are used when a kernel is created with default values, as suggested [here](https://www.tensorflow.org/probability/api_docs/python/tfp/distributions/GaussianProcess#examples):

```
tfd = tfp.distributions
psd_kernels = tfp.positive_semidefinite_kernels

# Define a kernel with default parameters.
kernel = psd_kernels.ExponentiatedQuadratic()
```

### Parameters defined

Default values for `amplitude` and `length_scale` are not listed (apart from a keyword 'None').

**Comment by jvishnuvardhan** [comment]
@alinaselega This is more related to `tfp` repo. Please post it in tfp repo [here](https://github.com/tensorflow/probability/issues) and close this issue. Thanks!

**Comment by alinaselega** [comment]
OK, thanks!
