### ISSUE TITLE
NotImplementedError for learn.TensorFlowEstimator.restore

### ISSUE THREAD

**Issue by rishsriv** [tensorflow/tensorflow#3008]
I had saved a model using tensorflow.contrib.learn and am currently trying to restore it. However, I am getting a `NotImplementedError`.

```
---------------------------------------------------------------------------
NotImplementedError                       Traceback (most recent call last)
<ipython-input-9-2a884c20d327> in <module>()
----> 1 gender_classifier = learn.TensorFlowEstimator.restore('gender_classifier_model/')

/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/learn/python/learn/estimators/base.pyc in restore(cls, path, config)
    336       custom_estimator = TensorFlowEstimator(model_fn=None, **model_def)
    337       # pylint: disable=protected-access
--> 338       custom_estimator._restore(path)
    339       return custom_estimator
    340 

/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/learn/python/learn/estimators/base.pyc in _restore(self, path)
    295       path: Path to checkpoints and other information.
    296     """
--> 297     raise NotImplementedError
    298 
    299   @classmethod
```
I realized that this is indeed not implemented in the [latest commit](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/learn/python/learn/estimators/base.py).

Until this is implemented, are there any workarounds? I tried pickling the model but was not able to do so, as it is a Module object.

**Comment by andydavis1** [comment]
For workarounds, please ask this question on StackOverflow.  Please ask it there and tag it with the `tensorflow` tag.

**Comment by bakwc** [comment]
NotImplemented means that it never should be implemented? Or it will be implemented later? Or this is some wrong usage issue?

**Comment by ilblackdragon** [comment]
To save and restore model just pass the same `model_dir` into Estimator.

For example:
```
est = LinearClassifier(model_dir='/tmp/dir1', ...)
est.fit(...)
...
est2 = LinearClassifier(model_dir='/tmp/dir1', ...)
est2.fit(..)
```

**Comment by rifatmahmud** [comment]
@ilblackdragon , for custom models, it doesn't seem to be working.(Like when using the TensorFlowEstimator).
Is there any workaround?

**Comment by rifatmahmud** [comment]
Got to work with initializing classifier as classifier=Estimator(model_fn=function_name,model_dir=dir_path). If the original function is not specified, it fails.
But, then, I am running into[ this issue](https://github.com/tensorflow/tensorflow/issues/2797), as I am using a ConvNet(from mnist example of skflow).

**Comment by amitphadke** [comment]
@rifatmahmud  Do you have an example where you got it to work?

**Comment by frankhuang014** [comment]
Is there  any solution for tf.contrib.learn.TensorFlowRNNRegressor? It seems that TensorFlowRNNRegressor dose not have parameter "model_dir". Please help me. Thanks!

**Comment by spate141** [comment]
```
classifier = learn.TensorFlowRNNClassifier.restore('/opt/model')


//anaconda/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/estimators/base.pyc in _restore(self, path)
    418       path: Path to checkpoints and other information.
    419     """
--> 420     raise NotImplementedError
    421 
    422   @classmethod

NotImplementedError:
```

Any solution yet ?

**Comment by IsaacBanjo** [comment]
Exactly same problem here. The learn.TensorFlowEstimator class does not have model_dir as an argument, and its _restore function is just empty. Any one can help? Thank you very much!

**Comment by IsaacBanjo** [comment]
@rifatmahmud  In the work around you mentioned. That is using its base class, so do you mean using the base class to fit, save and restore? But that base class even doesn't have a predict_proba function... Thanks!

**Comment by bakwc** [comment]
I wasn't able to make it works, so I just started to use original tensowrflow without skflow wrapper. Seems like skflow wrapper is very fresh.

**Comment by ilblackdragon** [comment]
Please don't use `TensorFlowEstimator` it's deprecated and will be removed in next version.
Use `Estimator` for custom models and then you have `model_dir` to specify to load from existing saved checkpoint.

**Comment by IsaacBanjo** [comment]
@ilblackdragon thanks for your response. I already wrote a tensorflow graph myself and make it work. The `Estimator` class seems not having a model_type as an argument; i.e., I can't choose what kind of cell to pass in as my network's major component. And it does not have predict_proba function either. Thanks!

**Comment by ilblackdragon** [comment]
@IsaacBanjo Not sure what do you mean by model_type? You can pass any parameter via `params` that you will receive in your model function. To get `predict_proba` just run `predict` on the probability predictions. 

E.g. it's just `est.predict(..., outputs=['probability'])['probability']` if your model function returns something like this `return {'probability': probs, 'class': tf.argmax(probs, axis=1)}, loss, train_op`

**Comment by IsaacBanjo** [comment]
@ilblackdragon I meant model_fn. Previously in my machine there is no such field. Now I see it at https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/learn/python/learn/estimators/estimator.py. Thanks!

**Comment by vtansaku** [comment]
@ilblackdragon When you say "if your model function returns something like this return {'probability': probs, 'class': tf.argmax(probs, axis=1)}, loss, train_op", can you give an example of what you define for probs?
