### ISSUE TITLE
Multiple duplicate tflite android example projects

### ISSUE THREAD

**Issue by mukulhase** [tensorflow/tensorflow#30087]
### Description:
There are two examples for "tflite image classification on android" on the Tensorflow repo which achieve the same thing. They both have almost identical code but slight differences(In UI and in code).

**Example A:** https://github.com/tensorflow/examples/tree/master/lite/examples/image_classification/android
**Example B:** https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/java

I would like to know which one is supposed to be used, and whether they can be merged so that this confusion is avoided?

### Example of a difference:

- In example A we do **not** create a NNAPI Delegate

https://github.com/tensorflow/examples/blob/156a12782a06f085adeb6b352c2763648cece066/lite/examples/image_classification/android/app/src/main/java/org/tensorflow/lite/examples/classification/tflite/Classifier.java#L179

- But in example B we do create an NNAPI Delegate

https://github.com/tensorflow/tensorflow/blob/e8ad5b0552a03e5d065a8f302dd0c0e0ae6b3925/tensorflow/lite/java/demo/app/src/main/java/com/example/android/tflitecamerademo/ImageClassifier.java#L186

**Comment by jdduke** [comment]
Thanks for flagging this, please refer to Example A, we'll likely be removing Example B from the lite repo soon.

In practice, using `setUseNNAPI(true)` is equivalent to adding the `NnApiDelegate`.

**Comment by Saduf2019** [comment]
@mukulhase 
Is this still an issue.

**Comment by jdduke** [comment]
@miaout17 we should probably remove the OSS version of the image classifier in https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/java/demo and point users to the examples repo. Please re-assign as appropriate.

**Comment by mohantym** [comment]
@mukulhase ! Beside NNAPI implementation, Build methods are different on both examples ( One is gradle.build and another is bazel build). I can see a depreciation warning now on android example here [though](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/examples/android/app).
