### ISSUE TITLE
[TF 2.0 API Docs] tf.image.extract_glimpse

### ISSUE THREAD

**Issue by imransalam** [tensorflow/tensorflow#30097]
## URL(s) with the issue:

https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/image/extract_glimpse

### Raises listed and defined

Raises are not listed and defined

### Usage example

No usage example is given

### Pull Request

https://github.com/tensorflow/tensorflow/pull/30098

**Comment by gadagashwini** [comment]
Closing this issue since the associated PR has been merged. Feel free to reopen if the problem still persists. Thanks!
