### ISSUE TITLE
Compiling protos for Golang

### ISSUE THREAD

**Issue by jc2729** [tensorflow/tensorflow#30093]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version: v1.14.0
- Python version:
- Installed using virtualenv? pip? conda?:
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Describe the problem** I'm trying to compile the protos using `protoc` so I can import the MetaGraph Go struct. Some of the protos (tensorflow/core/protobuf/saved_object_graph.proto, tensorflow/core/protobuf/trackable_object_graph.proto, tensorflow/core/protobuf/struct.proto) that are depended on lack `option go _package`, so `protoc` generates Go files with different package names (ending in protobuf and tensorflow) in the same directory, making both packages non-importable. 

**Provide the exact sequence of commands / steps that you executed before running into the problem**
1. `protoc` on all protos in tensorflow/core/lib/core/
2. `protoc` on all protos in tensorflow/core/framework/
3. `protoc` on protos in tensorflow/core/protobuf: saver.proto, struct.proto, trackable_object_graph.proto, saved_object_graph.proto, meta_graph.proto, saved_model.proto

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by achandraa** [comment]
Just to verify which OS are you using ?

**Comment by jc2729** [comment]
I've tried this on Ubuntu and OSX

**Comment by ymodak** [comment]
@asimshankar Can you PTAL? Thanks!

**Comment by asimshankar** [comment]
Unfortunately, I'm no longer working on TensorFlow. Perhaps @jhseu might be able to help.
Regardless, seems like it should be fine to add the package statements like those added in #17262

**Comment by ymodak** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
