### ISSUE TITLE
AttributeError: module 'tensorflow._api.v2.train' has no attribute 'FtrlOptimizer'

### ISSUE THREAD

**Issue by keurcien** [tensorflow/tensorflow#30092]
Thank you for submitting a TensorFlow documentation issue. Per our GitHub
policy, we only address code/doc bugs, performance issues, feature requests, and
build/installation issues on GitHub.

The TensorFlow docs are open source! To get involved, read the documentation
contributor guide: https://www.tensorflow.org/community/contribute/docs

## URL(s) with the issue:

Please provide a link to the documentation entry, for example:
https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/estimator/LinearClassifier

## Description of issue (what needs changing):

`FtrlOptimizer` is not accessible from `tf.train`:

```python
# Or estimator using the FTRL optimizer with regularization.
estimator = LinearClassifier(
    feature_columns=[categorical_column_a,
                     categorical_feature_a_x_categorical_feature_b],
    optimizer=tf.train.FtrlOptimizer(
      learning_rate=0.1,
      l1_regularization_strength=0.001
    )
    ### should be optimizer=tf.keras.optimizers.Ftrl(...)
)

> AttributeError: module 'tensorflow._api.v2.train' has no attribute 'FtrlOptimizer'
```

### Clear description

N/A

### Correct links

N/A

### Parameters defined

N/A

### Returns defined

N/A

### Raises listed and defined

N/A

### Usage example

N/A

### Request visuals, if applicable

N/A

### Submit a pull request?

N/A

**Comment by ravikyram** [comment]
Can you please provide your full code snippet to reproduce the issue.Thanks!

**Comment by keurcien** [comment]
Sure, here's my MWE:

```python
import tensorflow as tf
print(tf.__version__)

> 2.0.0-beta1
```

```python
from tensorflow.estimator import LinearClassifier

feature_columns = []

for feature_name in ['some_feature_a', 'some_feature_b']:
    feature_columns.append(
        tf.feature_column.numeric_column(feature_name, dtype=tf.float32)
    )

estimator = LinearClassifier(
    feature_columns=feature_columns,
    optimizer=tf.train.FtrlOptimizer(
      learning_rate=0.1,
      l1_regularization_strength=0.001
    )
)

> AttributeError: module 'tensorflow._api.v2.train' has no attribute 'FtrlOptimizer'
```

The `Ftrl` optimizer (or any other optimizer) can be called from `tf.optimizers` or `tf.keras.optimizers`:

```python
estimator = LinearClassifier(
    feature_columns=feature_columns,
    optimizer=tf.optimizers.Ftrl(
      learning_rate=0.1,
      l1_regularization_strength=0.001
    )
)
```

**Comment by mayyapillai** [comment]
I have similar issue: 

Version: tensorflow._api.v2.version
             tensorflow-gpu==2.0Beta1 

Code:

		example = tf.train.example(features=tf.train.features(feature={
			'height': _int64_feature(rows),
			'width': _int64_feature(cols),
			'depth': _int64_feature(depth),
			'label_raw': _bytes_feature(label_raw),
			'image_raw': _bytes_feature(image_raw)}))

Error:

Traceback (most recent call last):
  File "train_v1.1.py", line 236, in <module>
    main(sys.argv)
  File "train_v1.1.py", line 226, in main
    convert_to(train_images, train_labels, datafolder)
  File "train_v1.1.py", line 136, in convert_to
    example = tf.train.example(features=tf.train.features(feature={
**AttributeError: module 'tensorflow._api.v2.train' has no attribute 'example'**

**Comment by mayyapillai** [comment]
I found a way to get past this issue. 


ef _parse_function(example_proto):
	feature_description = {
		'height': tf.io.FixedLenFeature([], tf.int64),
		'width':  tf.io.FixedLenFeature([], tf.int64),
		'depth':  tf.io.FixedLenFeature([], tf.int64),
		'label_raw':  tf.io.FixedLenFeature([], tf.string),
		'image_raw':  tf.io.FixedLenFeature([], tf.string),
	}
	parsed_features = tf.io.parse_single_example(example_proto, feature_description)
	return parsed_features["height"], parsed_features["width"], parsed_features["depth"], parsed_features["image_raw"], parsed_features["label_raw"]

...
...
serialized_example = tf.data.TFRecordDataset(filenames)
serialized_example = serialized_example.map(_parse_function)

Calling tf.io.parse_single_example inside tf.Data.map() function as above works without error. 

Thank you.

**Comment by ymodak** [comment]
@keurcien Perhaps you can use ```python tf.keras.optimizers.Ftrl``` instead
https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/keras/optimizers/Ftrl
```python
from tensorflow.estimator import LinearClassifier

feature_columns = []

for feature_name in ['some_feature_a', 'some_feature_b']:
    feature_columns.append(
        tf.feature_column.numeric_column(feature_name, dtype=tf.float32)
    )

estimator = LinearClassifier(
    feature_columns=feature_columns,
    optimizer=tf.keras.optimizers.Ftrl(
      learning_rate=0.1,
      l1_regularization_strength=0.001
    )
)
```

**Comment by ymodak** [comment]
@keurcien Thanks for catching this. Sent a PR to address this issue.

**Comment by yhliang2018** [comment]
First, `tf.train.FtrlOptimizer` is not exposed in TF 2.0, and you may use tf.compat.v1 to access it. Secondly, LinearClassifier in TF 2.0 supports tf.keras.optimziers.* (and tf.optimizers.*) only, and you cannot use `tf.train.*Optimizer` here. 

So this is the intended behavior, not an actual issue.

**Comment by yhliang2018** [comment]
Ah, just notice this is about the doc string issue. Yes, that's right. Thank you!

**Comment by xiNA2019** [comment]
hi yhliang2018, do u know how to use tf.contrib.keras.optimizers.Adamax?

**Comment by yhliang2018** [comment]
@xiNA2019 Hi, Adamax optimizer has been exposed in TF 2.0. Please check https://www.tensorflow.org/api_docs/python/tf/keras/optimizers/Adamax

**Comment by loretoparisi** [comment]
I had the same problem here:

```
!pip install scikit-learn
!pip install tensorflow-gpu
!pip install tensorflow-hub
!pip install bert-tensorflow
from sklearn.model_selection import train_test_split
import pandas as pd
import tensorflow as tf
import tensorflow_hub as hub
from datetime import datetime

import bert
from bert import run_classifier
from bert import optimization
from bert import tokenization
```

**Comment by yhliang2018** [comment]
Are you in TF 1.x or TF 2.0? In general, `tf.train.Optimizer` has been deprecated in TF 2.0, and you need to use [`tf.compat.v1.Optimizer`](https://www.tensorflow.org/api_docs/python/tf/compat/v1/train/Optimizer) (then the deprecation message shows up but it's a warning only). In TF 2.0,  the Keras optimziers [`tf.keras.optimizers.*`](https://www.tensorflow.org/api_docs/python/tf/keras/optimizers) are recommended to use.

**Comment by EvanZ** [comment]
@loretoparisi I'm getting a similar error trying to run the Bert example here in my own Jupyter notebook running on EC2 (using TF2.0 on an Ubuntu deep learning AMI):

https://colab.research.google.com/github/google-research/bert/blob/master/predicting_movie_reviews_with_bert_on_tf_hub.ipynb#scrollTo=IhJSe0QHNG7U

`from bert import tokenization`

```
AttributeError                            Traceback (most recent call last)
<ipython-input-24-f9c3f4b9c6d5> in <module>()
----> 1 from bert import optimization

~/bert/optimization.py in <module>()
     85 
     86 
---> 87 class AdamWeightDecayOptimizer(tf.train.Optimizer):
     88   """A basic Adam optimizer that includes "correct" L2 weight decay."""
     89 

AttributeError: module 'tensorflow_core._api.v2.train' has no attribute 'Optimizer'
```

**Comment by Shawnsyx** [comment]
Thank you!

**Comment by Shawnsyx** [comment]
> @loretoparisi I'm getting a similar error trying to run the Bert example here in my own Jupyter notebook running on EC2 (using TF2.0 on an Ubuntu deep learning AMI):
> 
> https://colab.research.google.com/github/google-research/bert/blob/master/predicting_movie_reviews_with_bert_on_tf_hub.ipynb#scrollTo=IhJSe0QHNG7U
> 
> `from bert import tokenization`
> 
> ```
> AttributeError                            Traceback (most recent call last)
> <ipython-input-24-f9c3f4b9c6d5> in <module>()
> ----> 1 from bert import optimization
> 
> ~/bert/optimization.py in <module>()
>      85 
>      86 
> ---> 87 class AdamWeightDecayOptimizer(tf.train.Optimizer):
>      88   """A basic Adam optimizer that includes "correct" L2 weight decay."""
>      89 
> 
> AttributeError: module 'tensorflow_core._api.v2.train' has no attribute 'Optimizer'
> ```
> 
> Even running the code in the Colab notebook gives a similar warning (although not an error):
> `WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/bert/optimization.py:87: The name tf.train.Optimizer is deprecated. Please use tf.compat.v1.train.Optimizer instead. `

EvanZ, try to change the code in the 87 line,
`tf.train.Optimizer` 
-> ` tf.keras.optimizers.Optimizer`

**Comment by senthilmk** [comment]
Any updates on this one?

**Comment by yhliang2018** [comment]
@senthilmk What is your question? This issue is already answered and closed. Please open a new one if necessary.
