### ISSUE TITLE
Cannot reuse the self.Dense() defined in __init__(self) in call(self, x)

### ISSUE THREAD

**Issue by MyRespect** [tensorflow/tensorflow#30091]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 16.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.0.0-beta1
- Python version:  Python 3.5.2
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
When I define the following:
```
class MNISTModel(Model):
    def __init__(self):
        super(MNISTModel, self).__init__()
        self.conv1 = Conv2D(32, (3, 3), input_shape=(28, 28, 1))
        self.activ = Activation('relu')
        self.flatt = Flatten()
        self.dense = Dense(200) #Here I want to reuse this Dense() layer
        self.dense1 = Dense(200) #However, I need to re-define the same layer again to use in call()
        self.dens2 = Dense(10)
```
**Describe the expected behavior**
I think that we only need to define the self.Dense(200) only once, but we can reuse it in the  def call(self, x)
**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.
```
import numpy as np
import tensorflow as tf
from tensorflow import keras
from tensorflow.data import Dataset
from tensorflow.keras import datasets, Model, losses, optimizers, metrics
from tensorflow.keras.layers import Dense, Flatten, Conv2D, Activation, MaxPooling2D


class MNISTModel(Model):
    def __init__(self):
        super(MNISTModel, self).__init__()
        self.conv1 = Conv2D(32, (3, 3), input_shape=(28, 28, 1))
        self.activ = Activation('relu')
        self.conv2 = Conv2D(32, (3, 3))
        self.maxpo = MaxPooling2D(pool_size=(2, 2))
        self.conv3 = Conv2D(64, (3, 3))
        self.flatt = Flatten()
        self.dense = Dense(200)
        self.dense1 = Dense(200)
        self.dens2 = Dense(10)

    def call(self, x):
        x = self.conv1(x)
        x = self.activ(x)
        x = self.conv2(x)
        x = self.activ(x)
        x = self.maxpo(x)

        x = self.conv3(x)
        x = self.activ(x)
        x = self.conv3(x)
        x = self.activ(x)
        x = self.maxpo(x)

        x = self.flatt(x)
        x = self.dense(x)
        x = self.activ(x)
        x = self.dense1(x)
        x = self.activ(x)
        return self.dens2(x)


(train_data, train_labels), (test_data, test_labels) = datasets.mnist.load_data()
train_data, test_data = train_data / 255.0, test_data / 255.0
train_data = train_data[..., tf.newaxis]
test_data = test_data[..., tf.newaxis]
print(train_data.shape, test_data.shape, type(train_data))
train_data = Dataset.from_tensor_slices(
    (train_data, train_labels)).shuffle(60000).batch(128)
test_data = Dataset.from_tensor_slices((test_data, test_labels)).batch(128)


model = MNISTModel()
loss_object = losses.SparseCategoricalCrossentropy()
optimizer = optimizers.Adam()

train_loss = metrics.Mean(name='train_loss')
train_accuracy = metrics.SparseCategoricalAccuracy(name='train_accuracy')
test_loss = metrics.Mean(name='test_loss')
test_accuracy = metrics.SparseCategoricalAccuracy(name='test_accuracy')


@tf.function
def train_step(images, labels):
    with tf.GradientTape() as tape:
        logits = model(images)
        loss_value = loss_object(labels, logits)
    grads = tape.gradient(loss_value, model.trainable_variables)
    optimizer.apply_gradients(zip(grads, model.trainable_variables))
    train_loss(loss_value)
    train_accuracy(labels, logits)


@tf.function
def test_step(images, labels):
    logits = model(images)
    tloss_value = loss_object(labels, logits)
    test_loss(tloss_value)
    test_accuracy(labels, logits)


EPOCHS = 5

for epoch in range(EPOCHS):
    for images, labels in train_data:
        train_step(images, labels)

    for test_images, test_labels in test_data:
        test_step(test_images, test_labels)

    template = 'Epoch {}, Loss: {}, Accuracy: {}, Test Loss: {}, Test Accuracy: {}'
    print (template.format(epoch + 1, train_loss.result(), train_accuracy.result()
                           * 100, test_loss.result(), test_accuracy.result() * 100))
```
**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by gadagashwini** [comment]
@MyRespect After executing the above code on Colab with Tensorflow 2.0.0.beta1 I got the following error 
`ValueError: Input 0 of layer conv2d_5 is incompatible with the layer: expected axis -1 of input shape to have value 32 but received input with shape [128, 10, 10, 64]`.

**Comment by MyRespect** [comment]
Yes, you reproduced my bug. This is because I use 
`        x = self.conv3(x)
        x = self.activ(x)
        x = self.conv3(x)`
in the __call__(), but if you define 
`self.conv3_1 = Conv2D(64, (3, 3))` 
in the __init__(), and use it in the __call__():
`        x = self.conv3(x)
        x = self.activ(x)
        x = self.conv3_1(x)`
you can avoid the problem. So here I think it is a bug to be fixed.

**Comment by omalleyt12** [comment]
@MyRespect Thanks for the bug! You can reuse layers, you just have to make sure that the shapes of your second inputs are compatible with the shapes of your first inputs to the layer, in this case it looks like that is not true for your model
