### ISSUE TITLE
I think there is a small mistake in the tensorflow's documents

### ISSUE THREAD

**Issue by gomiss** [tensorflow/tensorflow#301]
I don't know whether it's right to report documents mistakes in this place,i don't find other place to report mistakes...
On tensorflow's website, the introduce of [tf.transpose(a, perm=None, name='transpose')](http://tensorflow.org/api_docs/python/array_ops.md#transpose) in the doc says:

For example:
```
# 'x' is [[1 2 3]
#         [4 5 6]]
tf.transpose(x) ==> [[1 4]
                     [2 5]
                     [3 6]]
  
# Equivalently
tf.transpose(x perm=[0, 1]) ==> [[1 4]
                                 [2 5]
                                 [3 6]]
```
I think the perm should be [1, 0] , not [0, 1].

**Comment by girving** [comment]
Thanks, we've noticed this and it should be in the next git sync.
