### ISSUE TITLE
CPU memory is not released after calling sess.run and closing session

### ISSUE THREAD

**Issue by fgvbrt** [tensorflow/tensorflow#30108]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 16.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): not sure
- TensorFlow version (use command below): v1.13.1-0-g6612da8
- Python version: 3.7.3
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: CUDA 10.0
- GPU model and memory: Tesla V100, 16130MiB

**Describe the current behavior**
I observed increase of cpu memory usage (and not releasing memory) when fetching big tensors with `sess.run` from gpu and also not releasing cpu memory when closing session and resetting graph.

I attached example and memory profiler logs. I tested 3 situations:
1) Create two variables on gpu and fetch them in one `sess.run` call: memory increases by 1057MiB and is not released after closing session and resetting graph)
2) Create two variables on gpu and fetch them one by one with `sess.run` call: memory increases by 528MiB and is not released after closing session and resetting graph)
3) Create two variables on сpu and fetch them: memory isn’t increased and released after closing session.

**Describe the expected behavior**
Memory is released after `sess.run` and closing session, like in case 3 above but for gpu.

**Code to reproduce the issue**
https://gist.github.com/fgvbrt/7e9163267e1bc1fc501916125e09cd6d

**Other info / logs**
Logs with run commands for 3 situation above:
[profile.txt](https://github.com/tensorflow/tensorflow/files/3323401/profile.txt)

**Comment by fgvbrt** [comment]
Hello, I just wanted to check if anyone had a chance to look at this error?
I am working on model pruning and to fully utilize pruned architecture I rebuild graph during training. And this error is causing a lot of problems and inconvenience

**Comment by sachinprasadhs** [comment]
Since we no longer support Tensorflow 1.x issues, could you please update your code in Tensorflow 2.x and let us know if you are still facing issue, Thank you!
