### ISSUE TITLE
Dataset.cache() Followed by Dataset.zip() Throws AlreadyExistsError

### ISSUE THREAD

**Issue by devstein** [tensorflow/tensorflow#30105]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): OSX Mojave 10.14.5
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): `pipenv install --pre tensorflow==2.0.0-beta1`
- TensorFlow version (use command below): `2.0.0-beta1`
- Python version: 3.6.8
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

`1v2.0.0-beta0-16-g1d91213fe7`

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**

1. Cache a dataset
2. Derive other datasets from it
3. Zip the derived datasets into a single dataset
4. See cache error

```
AlreadyExistsError: There appears to be a concurrent caching iterator running - cache lockfile already exists
```

**Describe the expected behavior**
Only cache the dataset once and not throw an error.

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

```python
import tensorflow as tf


def map_file_to_xy_dataset(filename, params):
    # Generate a dataset from the filename
    csv_dataset = tf.data.experimental.CsvDataset(...)

    # Cache at unique file location (i.e filename)
    cached_dataset = csv_dataset.cache(...)

    # Generate x dataset (all but id column)
    x_dataset = cached_dataset.map(lambda *x: x[0:-1])

    # Generate y dataset (last column of each file)
    y_dataset = cached_dataset.map(lambda *x: x[-1])

    # ZIP the X, Y datasets 
    # This will throw AlreadyExistsError 
    xy_dataset = tf.data.Dataset.zip((x_dataset, y_dataset))

    return xy_dataset


def generate_dataset():
    filenames_dataset = tf.data.Dataset.list_files(data_glob)

    dataset = filenames_dataset.flat_map(map_file_to_xy_dataset)

    return dataset


```

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by achandraa** [comment]
I have tried to reproduce with below code snippet in Colab with TF CPU version 2.0beta1 and was not able to reproduce the error. 

```
import tensorflow as tf

def map_file_to_xy_dataset(filename):
    # Generate a dataset from the filename
    csv_dataset = tf.data.experimental.CsvDataset("Iris.csv",["float32","float32","float32","float32","float32"])

    # Cache at unique file location (i.e filename)
    cached_dataset = csv_dataset.cache("Iris.csv")

    # Generate x dataset (all but id column)
    x_dataset = csv_dataset.map(lambda *x: x[0:-1])

    # Generate y dataset (last column of each file)
    y_dataset = csv_dataset.map(lambda *x: x[-1])

    # ZIP the X, Y datasets 
    # This will throw AlreadyExistsError 
    xy_dataset = tf.data.Dataset.zip((x_dataset, y_dataset))

    return xy_dataset


def generate_dataset():
    filenames_dataset = tf.data.Dataset.list_files("Iris.csv")

    dataset = filenames_dataset.flat_map(map_file_to_xy_dataset)

    return dataset

dataset=generate_dataset()
dataset
```
Please let us know if we are missing out something. Thanks!

**Comment by devstein** [comment]
@achandraa Thanks for looking into this! Did you iterate over the dataset? I'm still able to reproduce with your code by adding the following:

```python
for x,y in dataset:
    print(x,y)
```

If this still doesn't work, the only other difference is the `filenames_dataset` I'm using has multiple files.

**Comment by gadagashwini** [comment]
@devstein I am not able to reproduce the issue with above code and where to add these two lines 
```
for x,y in dataset:
    print(x,y) . 

```Can you help us to reproduce the issue. Thanks!

**Comment by devstein** [comment]
@gadagashwini Did you try using a `tf.data.Dataset.list_files("*.csv")` where there are multiples CSV files in the file path? This is the only difference between my code and the example

**Comment by gadagashwini** [comment]
@devstein Tried reproducing the issue and I received error saying `<DatasetV1Adapter shapes: (((), (), (), ()), ()), types: ((tf.float32, tf.float32, tf.float32, tf.float32), tf.float32)>`. Thanks!

**Comment by devstein** [comment]
@gadagashwini What line did you receive this error? Did you try 

```python
for x,y in dataset:
  print(x,y)
```

**Comment by feihugis** [comment]
@devstein @gadagashwini This error message `AlreadyExistsError: There appears to be a concurrent caching iterator running - cache lockfile already exists` looks reasonable. It is caused by that multiple datasets are trying to be cached in the same file. You can change the line `cached_dataset = csv_dataset.cache("Iris.csv")` to be `cached_dataset = csv_dataset.cache("cached_" + filename)` so that each cached dataset has a unique file name.

**Comment by devstein** [comment]
@feihugis I am caching to a unique location for every file. This is my exact code for generating each filename:

```python
def generate_cache_filename(filename, directory):
    filename_no_slashes = tf.strings.regex_replace(filename, r"\/", "_")

    cache_filename = tf.strings.join([directory, filename_no_slashes],
                                     separator="/")

    return cache_filename
```

**Comment by feihugis** [comment]
@devstein Could you print the filenames used for the cache to make sure they are unique?

The following code works for me:
```Python
  def map_file_to_xy_dataset(filename):
    # Generate a dataset from the filename
    csv_dataset = tf.data.experimental.CsvDataset(filename,
                                                  ["float32", "float32",
                                                   "float32", "float32",
                                                   "float32"],
                                                  header=True,)

    # Cache at unique file location (i.e filename)
    cached_dataset = csv_dataset.cache("cached_"+filename)

    # Generate x dataset (all but id column)
    x_dataset = csv_dataset.map(lambda *x: x[0:1])

    # Generate y dataset (last column of each file)
    y_dataset = csv_dataset.map(lambda *x: x[-1])

    # ZIP the X, Y datasets
    # This will throw AlreadyExistsError
    xy_dataset = tf.data.Dataset.zip((x_dataset, y_dataset))

    return xy_dataset

  def generate_dataset(file_pattern):
    filenames_dataset = tf.data.Dataset.list_files(file_pattern)
    dataset = filenames_dataset.flat_map(map_file_to_xy_dataset)
    return dataset

  dataset = generate_dataset("/Users/fei/Desktop/csv_test/*.csv")
  for x, y in dataset:
    print(x, y)
```

**Comment by devstein** [comment]
@feihugis 

Can you re-run with the corrected code below? I run into the issue when mapping over the `cached_dataset` not the `csv_dataset`

```python
  def map_file_to_xy_dataset(filename):
    # Generate a dataset from the filename
    csv_dataset = tf.data.experimental.CsvDataset(filename,
                                                  ["float32", "float32",
                                                   "float32", "float32",
                                                   "float32"],
                                                  header=True,)

    # Cache at unique file location (i.e filename)
    cached_dataset = csv_dataset.cache("cached_"+filename)

    # Generate x dataset (all but id column)
    x_dataset = cached_dataset.map(lambda *x: x[0:1])

    # Generate y dataset (last column of each file)
    y_dataset = cached_dataset.map(lambda *x: x[-1])

    # ZIP the X, Y datasets
    # This will throw AlreadyExistsError
    xy_dataset = tf.data.Dataset.zip((x_dataset, y_dataset))

    return xy_dataset

  def generate_dataset(file_pattern):
    filenames_dataset = tf.data.Dataset.list_files(file_pattern)
    dataset = filenames_dataset.flat_map(map_file_to_xy_dataset)
    return dataset

  dataset = generate_dataset("/Users/fei/Desktop/csv_test/*.csv")
  for x, y in dataset:
    print(x, y)

```

Thanks for the help!

**Comment by feihugis** [comment]
Oh, my bad. Now I got this error `tensorflow.python.framework.errors_impl.NotFoundError: cached_/Users/fei/Desktop/csv_test/3.csv_0.lockfile; No such file or directory [Op:IteratorGetNextSync]`. It is different from yours. I guess the problem you met is caused by the cache file name. I am looking into the error I met.

**Comment by devstein** [comment]
@feihugis Thanks!

**Comment by gadagashwini** [comment]
@devstein Were you able to resolve the issue? Thanks!

**Comment by feihugis** [comment]
@gadagashwini @jsimsa I am working on the fix. The issue can be reproduced by the simplified code below:
```
  csv_dataset = tf.data.Dataset.range(0, 1000, 1)
  cached_dataset = csv_dataset.cache("cache_test")
  x_dataset = cached_dataset.map(lambda x: x)
  y_dataset = cached_dataset.map(lambda x: x * 2)
  xy_dataset = tf.data.Dataset.zip((x_dataset, y_dataset))

  for x, y in xy_dataset:
    print(x, y)
```

@devstein The workaround solution is to change `cached_dataset = csv_dataset.cache("cache_test")` to be `cached_dataset = csv_dataset.cache()` which will use the memory cache instead of file cache.

**Comment by jsimsa** [comment]
This behavior is expected because your input pipeline definition is trying to create the same cache twice (once for each component of the zip) and it will not be reused.

Instead, you should do the following (which will also be more efficient):

```
def map_file_to_dataset(filename, params):
    # Generate a dataset from the filename
    csv_dataset = tf.data.experimental.CsvDataset(...)

    # Cache at unique file location (i.e filename)
    cached_dataset = csv_dataset.cache(...)

   return dataset.map(lambda *x: (x[0:-1], x[-1]))
```

**Comment by devstein** [comment]
@jsimsa I separated the two operations because I window the `x_dataset` afterward and not the `y_dataset`, but I'll switch it to split the datasets after I window. Appreciate the help!
