### ISSUE TITLE
Makefile build broken on macOS

### ISSUE THREAD

**Issue by themightyoarfish** [tensorflow/tensorflow#30117]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): 10.14.5 (18F203)
- TensorFlow installed from (source or binary): source
- TensorFlow version: 8e423e3d56390671f0d954c90f4fd163ab02a9c1
- Python version: 2.7 (but not building pip package)
- Bazel version (if compiling from source): not used
- GCC/Compiler version (if compiling from source):
```
Apple LLVM version 10.0.1 (clang-1001.0.46.4)
Target: x86_64-apple-darwin18.6.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

**Describe the problem**

I am followin https://github.com/tensorflow/tensorflow/tree/master/tensorflow/contrib/makefile on macOS Mojave.

Running
```
bash tensorflow/contrib/makefile/build_all_linux.sh
```
terminates with the error
```
Undefined symbols for architecture x86_64:
  "_CFRelease", referenced from:
      absl::time_internal::cctz::local_time_zone() in time_zone_lookup.o
  "_CFStringGetCString", referenced from:
      absl::time_internal::cctz::local_time_zone() in time_zone_lookup.o
  "_CFStringGetLength", referenced from:
      absl::time_internal::cctz::local_time_zone() in time_zone_lookup.o
  "_CFStringGetMaximumSizeForEncoding", referenced from:
      absl::time_internal::cctz::local_time_zone() in time_zone_lookup.o
  "_CFTimeZoneCopyDefault", referenced from:
      absl::time_internal::cctz::local_time_zone() in time_zone_lookup.o
  "_CFTimeZoneGetName", referenced from:
      absl::time_internal::cctz::local_time_zone() in time_zone_lookup.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

May this come from not having XCode installed? I assume the (seemingly missing) Core Foundation libraries are shipped with macOS regardless. But it is listed as a dependency for iOS, so maybe macOS should be mentioned thereabouts as well?

Update: The makefile seems to link the CoreFoundation framework only for iOS, the comment notwithstanding.
https://github.com/tensorflow/tensorflow/blob/2f4121b1a7266aef4007457aa348c5f7f01eb539/tensorflow/contrib/makefile/Makefile#L912

I added
```
ifeq ($(TARGET),OSX)
    HOST_LDOPTS += -framework CoreFoundation
endif
```
and the compilation proceeds at least (can't say whether it will succeed yet).

**Comment by themightyoarfish** [comment]
The proposed solution alone did not help. I _instead_ modified the block beginning in line 242 of the Makefile to always pass `-framework CoreFoundation` to the compiler options.
```
# If we're on OS X, make sure that globals aren't stripped out.
ifeq ($(TARGET),OSX)
ifeq ($(HAS_GEN_HOST_PROTOC),true)
	LIBFLAGS += -L$(MAKEFILE_DIR)/gen/protobuf-host/lib
	export LD_LIBRARY_PATH=$(MAKEFILE_DIR)/gen/protobuf-host/lib
endif
	LDFLAGS += -all_load
	CXX_FLAGS += -framework CoreFoundation   #  <--- here 
endif
```

This yields a lot of warnings about unused linker args, but ultimately seems to work (I'm not quite sure if I had to add the initial `HOST_LDOPTS` modifications as well).

**Comment by mihaimaruseac** [comment]
Makefile build is no longer supported, it's povided on a best-effort basis.

I currently don't have access to a Mac machine to try and fix this, unfortunately

**Comment by themightyoarfish** [comment]
I think I have the fix ready, I can hopefully submit a PR.

**Comment by mihaimaruseac** [comment]
That would be awesome. Please assign me as reviewer to PR

**Comment by themightyoarfish** [comment]
See https://github.com/tensorflow/tensorflow/pull/30214

**Comment by gunan** [comment]
Looks like https://github.com/tensorflow/tensorflow/pull/30279 is already merged. closing.

**Comment by aqeeliqbal** [comment]
Still having this problem. i am build static library for android using MacOS system.
```
Undefined symbols for architecture x86_64:
  "_CFRelease", referenced from:
      absl::time_internal::cctz::local_time_zone() in time_zone_lookup.o
  "_CFStringGetCString", referenced from:
      absl::time_internal::cctz::local_time_zone() in time_zone_lookup.o
  "_CFStringGetLength", referenced from:
      absl::time_internal::cctz::local_time_zone() in time_zone_lookup.o
  "_CFStringGetMaximumSizeForEncoding", referenced from:
      absl::time_internal::cctz::local_time_zone() in time_zone_lookup.o
  "_CFTimeZoneCopyDefault", referenced from:
      absl::time_internal::cctz::local_time_zone() in time_zone_lookup.o
  "_CFTimeZoneGetName", referenced from:
      absl::time_internal::cctz::local_time_zone() in time_zone_lookup.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [/Users/granjur/Documents/tensorflow/tensorflow/contrib/makefile/gen/host_bin/proto_text] Error 1
make: *** Waiting for unfinished jobs....
```
i have tried building with both command
`tensorflow/contrib/makefile/build_all_android.sh`
and 
`make -f tensorflow/contrib/makefile/Makefile TARGET=ANDROID`
but same result

**Comment by themightyoarfish** [comment]
I think I also had the problem after the merge, not quite sure though. It could be that `CoreFoundation` gets linked into the library alright, but not the benchmark app that gets built as well.

**Comment by aqeeliqbal** [comment]
so how to solve this?
i only need to build library.

**Comment by themightyoarfish** [comment]
If you just need it once, you can hardcode `-framework CoreFoundation` to the makefile targets `$(LIB_PATH)` and `$(BENCHMARK_NAME)`.

**Comment by aqeeliqbal** [comment]
thanks for the hint, can you please direct me exactly where (what line number) i should add this.
