### ISSUE TITLE
[TF2.0] How to do image data augmentation using Dataset

### ISSUE THREAD

**Issue by svobora** [tensorflow/tensorflow#30112]
Hello everyone,

since TF2.0, it seems that image data augmentation is made more difficult than in 1.x. I admit I am now not able to do such a simple thing as adding random rotation to my pipeline. 

Using Dataset, I `map` my preprocess function to the pipeline. I can perform augmentations available in tf.image, but these are rather limited in range, e.g. I am not happy with rot90. I would like to add a TF->PIL->rotate->TF code, but it always raises exception during eager because obviously the input dimensions are not known.

```
image = tf.io.read_file(path)
image = tf.image.decode_image(image, channels=3)
image = tf.image.random_flip_left_right(image)
image = SOMEHOWROTATE(image, angle)
```

Seems that keras ImageDataGenerator should have been used, but I am not able to integrate it into Dataset pipeline. Previously in TF1, I used py_func in which I was able to convert tensors to pil images and rotate. Anyone can help?

Please do not forward this to stackoverflow, as user base of TF2.0 is very sparse there. It seems to be very difficult to find examples of using TF2.0.

r

**Comment by ofexe** [comment]
Did you get the right image. I use map function, and I can't even get the string of "path".

**Comment by makercob** [comment]
in dataset.map:
1. do random brightness/saturation/hue with tf.image functions.
2. wrap OpenCV operation with tf.py_function(rotation with warp affine).
but currently I'm having lots of trouble dealing with tf.py_function when distribute strategy is employed. see: [https://github.com/tensorflow/tensorflow/issues/31117](url)

**Comment by ymodak** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Comment by somedadaism** [comment]
This is still a massive problem. Can you guide us to a workaround/solution?

**Comment by shamoji101** [comment]
TF2.0's rotate pipeline solution is this code.
```
import tensorflow as tf
import tensorflow_addons as tfa
import numpy as np 
@tf.function
def rotate_tf(image):
    if image.shape.__len__() ==4:
            
        random_angles = tf.random.uniform(shape = (tf.shape(image)[0], ), minval = -np
        .pi / 4, maxval = np.pi / 4)
    if image.shape.__len__() ==3:
        random_angles = tf.random.uniform(shape = (), minval = -np
        .pi / 4, maxval = np.pi / 4)

    return tfa.image.rotate(image,random_angles)


(train_x,train_y),(test_x,test_y) =  keras.datasets.mnist.load_data()
train_x=train_x.reshape(-1,28,28,1)
train_ds=tf.data.Dataset.from_tensor_slices(train_x)
train_ds=train_ds.batch(512).map(rotate_tf) # map first is too slow in first time
for x in train_ds:
    X = x.numpy().reshape((-1,28,28))
    break
plt.figure(facecolor="white")
for i in range(16):
    plt.subplot(4,4,i+1)
    plt.imshow(X[i,:])
    plt.grid(False)
plt.show()
```
![mnist_rotate](https://user-images.githubusercontent.com/33369460/68120578-16b27380-ff49-11e9-8713-1f6eadb1acd0.png)
