### ISSUE TITLE
Op type not registered 'LeakyRelu' in binary running on some PC.

### ISSUE THREAD

**Issue by EternalSaga** [tensorflow/tensorflow#30118]
**Tensorflow version:**
Due to some problems according to the production environment, I only can use the tensorflow 1.9 or 1.10.

**Problem description**
I'm trying to deploy the yolov3 trained model through the c++ api. The trained model are coming from these two repositories, [`tensorflow-yolov3`](https://github.com/YunYang1994/tensorflow-yolov3) and  [`keras-yolo3`](https://github.com/qqwweee/keras-yolo3). 
However, when I was creating the session by using the graph definition, the session create status report that "Op type not registered 'LeakyRelu' in binary running on my pc".
`    auto session = std::unique_ptr<tensorflow::Session>();
    session.reset(tensorflow::NewSession(tensorflow::SessionOptions()));
    Status session_create_status = session->Create(graph_def);
    if (!session_create_status.ok())
    {
        throw std::runtime_error(session_create_status.error_message());
    }`

**Operating System Information**
I test my code on both ubuntu 18.04 and Windows10. The error is the same.
**Some research**
I tried to use the tensorflow 1.9 and tensorflow 1.10 at the same time, but the problem is the same. I read the tensorflow api and I found that the tf.nn module has the leaky relu operation but the c++ api does not.
Is there any possibility to add the support of leaky relu throught c++ api on the old version of tensorflow?

**Comment by jvishnuvardhan** [comment]
@EternalSaga Can you try recent TF 1.14.0 version and let us know how it progresses. Also, please fill the issue template [here](https://github.com/tensorflow/tensorflow/issues/new/choose). thanks!

**Comment by EternalSaga** [comment]
> 
> 
> @EternalSaga Can you try recent TF 1.14.0 version and let us know how it progresses. Also, please fill the issue template [here](https://github.com/tensorflow/tensorflow/issues/new/choose). thanks!

Thank you for your reply. I compiled the TF 1.13.1 successfully. However, I cannot organize the header files successfully. In fact, the header files for TF 1.9 and 1.10 come from this repository [tensorflow-windows-wheel](https://github.com/fo40225/tensorflow-windows-wheel). This repo does not provide the orgnized headers for TF which versions after 1.10. Aditionally, I cannot find any official guide for using tensorflow_cc.so and it's c++ api as a standalone library for other c++ project without using bazel.

**Comment by hksonngan** [comment]
I got the same issue and update 1.40 solved this
https://storage.googleapis.com/tensorflow/libtensorflow/libtensorflow-gpu-windows-x86_64-1.14.0.zip
https://storage.googleapis.com/tensorflow/libtensorflow/libtensorflow-cpu-windows-x86_64-1.14.0.zip

**Comment by jvishnuvardhan** [comment]
@hksonngan Thanks for providing the resolution.

I am closing this issue. Please feel free to reopen if the issue persists again. Thanks!
