### ISSUE TITLE
Saver's restore method uses deprecated checkpoint_exists method.

### ISSUE THREAD

**Issue by abdullahselek** [tensorflow/tensorflow#30119]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
Yes, I have written custom Python code.
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
macOS Mojave 10.14.5
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
No
- TensorFlow installed from (source or binary):
Binary using pip
- TensorFlow version (use command below):
('v1.9.0-0-g25c197e023', '1.9.0')
- Python version:
Python 3.6.5
- Bazel version (if compiling from source):
NA
- GCC/Compiler version (if compiling from source):
NA
- CUDA/cuDNN version:
NA
- GPU model and memory:
Intel Iris Pro 1536 MB

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
I try to restore previously saved checkpoint variables and I get a method deprecated error.

**Describe the expected behavior**
I could restore checkpoints.

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.
```
import os
import tensorflow as tf

graph_path = os.path.join('plant_disease_classification/ckpts/', 'plants-disease-model.meta')
checkpoint_path = os.path.join('plant_disease_classification/ckpts/', 'plants-disease-model')

session = tf.compat.v1.Session()
saver = tf.compat.v1.train.import_meta_graph(graph_path)
# get error on line below
saver.restore(session, checkpoint_path)
# and try this as well same depracation error
saver.restore(session, tf.train.latest_checkpoint('plant_disease_classification/ckpts/'))
```

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.
```
WARNING: Logging before flag parsing goes to stderr.
W0625 14:28:02.910645 4579825088 deprecation.py:323] From /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tensorflow/python/training/saver.py:1276: checkpoint_exists (from tensorflow.python.training.checkpoint_management) is deprecated and will be removed in a future version.
Instructions for updating:
Use standard file APIs to check for files with this prefix.
```

**Comment by ravikyram** [comment]
Just to verify whether you are able to restore previously saved checkpoint variables .Deprecation warning gives information about the function which will not be available in future version and it makes the user aware of this information.

**Comment by abdullahselek** [comment]
Sadly I can't restore my previously saved checkpoints.

**Comment by allenlavoie** [comment]
That's not an error, it's just a warning. It won't stop program execution.

**Comment by ravikyram** [comment]
@abdullahselek 
Can we close the issue since this is not a bug. Let us know. Thanks!

**Comment by abdullahselek** [comment]
@ravikyram yes we can close, I'm closing right now.
