### ISSUE TITLE
TPU error in eager execution

### ISSUE THREAD

**Issue by capilano** [tensorflow/tensorflow#30129]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- TensorFlow version (use command below): 1.14.0
- Python version: 3.6
- GPU model and memory: N/A

**Describe the current behavior**
InternalError: Failed copying input tensor from /job:worker/replica:0/task:0/device:CPU:0 to /job:worker/replica:0/task:1/device:CPU:0 in order to run ExperimentalAutoShardDataset: Unable to parse tensor proto Additional GRPC error information: {"created":"@1561473418.214771131","description":"Error received from peer","file":"external/grpc/src/core/lib/surface/call.cc","file_line":1

I get the above error when running model.fit . For my input pipeline , I use tf.Records in conjunction with the Dataset API and feed in a batch of numpy arrays as input and labels to the model.fit function.
I am fairly certain that I am not exceeding any tensor memory limits and all my operations are well within the 2Gb limit and all my dtypes are either float32 or int32

**Describe the expected behavior**

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by capilano** [comment]
InternalError: Failed copying input tensor from /job:worker/replica:0/task:0/device:CPU:0 to /job:worker/replica:0/task:1/device:CPU:0 in order to run ExperimentalAutoShardDataset: Unable to parse tensor proto Additional GRPC error information: {"created":"@1561473418.214771131","description":"Error received from peer","file":"external/grpc/src/core/lib/surface/call.cc","file_line":1

**Comment by jmgc** [comment]
@capilano How did you solve the issue?

**Comment by capilano** [comment]
@jmgc I was using google colab's TPU and went back to using non eager mode, TF1.14 does not support eager training in TPU(or atleast its still buggy) and in google colab even if you update tensorflow to 2.0, the TPU machine still uses 1.14. So that was one issue.
So there are a couple of options.
1.) Use TF 2.0 and do everything in eager mode(which is default), but you will need cloud TPU, not colab TPU.
2.) Use TF 1.14 in non eager mode and shard the dataset, there are multiple ways to do it. I am currently using TF1.14 and using keras layers and models inside the distribute strategy and using custom training loops to train  a GAN model, but you can also use model.fit and pass a dataset to it directly after calling strategy.experimental_distribute_dataset.
