### ISSUE TITLE
Attempt to convert a value (1.0) with an unsupported type (<class 'numpy.float32'>) to a Tensor.

### ISSUE THREAD

**Issue by guyko81** [tensorflow/tensorflow#30120]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
No, I have used the example script from [https://www.tensorflow.org/api_docs/python/tf/convert_to_tensor](url)

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
Windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
pip install (binary)
- TensorFlow version (use command below):
2.0.0-beta1
- Python version:
3.6.6
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
10.0
- GPU model and memory:
GeForce GTX 1050, 4GB

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
I was trying to convert a numpy array to a tensorflow tensor as in the example code.
**Describe the expected behavior**
Should give back tensor (as it works properly in earlier versions)
**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.
`import numpy as np

def my_func(arg):
  arg = tf.convert_to_tensor(arg, dtype=tf.float32)
  return tf.matmul(arg, arg) + arg

#The following calls are equivalent.
`import numpy as np

def my_func(arg):
  arg = tf.convert_to_tensor(arg, dtype=tf.float32)
  return tf.matmul(arg, arg) + arg

#The following calls are equivalent.
value_1 = my_func(tf.constant([[1.0, 2.0], [3.0, 4.0]])) 
value_2 = my_func([[1.0, 2.0], [3.0, 4.0]]) 
value_3 = my_func(np.array([[1.0, 2.0], [3.0, 4.0]], dtype=np.float32)) `

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.
`---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-1-f167d18ea32e> in <module>
      9 value_1 = my_func(tf.constant([[1.0, 2.0], [3.0, 4.0]]))
     10 value_2 = my_func([[1.0, 2.0], [3.0, 4.0]])
---> 11 value_3 = my_func(np.array([[1.0, 2.0], [3.0, 4.0]], dtype=np.float32))

<ipython-input-1-f167d18ea32e> in my_func(arg)
      3 
      4 def my_func(arg):
----> 5   arg = tf.convert_to_tensor(arg, dtype=tf.float32)
      6   return tf.matmul(arg, arg) + arg
      7 

~\Anaconda3\envs\Tensorflow_2_0_Beta\lib\site-packages\tensorflow\python\framework\ops.py in convert_to_tensor_v2(value, dtype, dtype_hint, name)
   1156       name=name,
   1157       preferred_dtype=dtype_hint,
-> 1158       as_ref=False)
   1159 
   1160 

~\Anaconda3\envs\Tensorflow_2_0_Beta\lib\site-packages\tensorflow\python\framework\ops.py in internal_convert_to_tensor(value, dtype, name, as_ref, preferred_dtype, ctx, accept_symbolic_tensors, accept_composite_tensors)
   1235 
   1236     if ret is None:
-> 1237       ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
   1238 
   1239     if ret is NotImplemented:

~\Anaconda3\envs\Tensorflow_2_0_Beta\lib\site-packages\tensorflow\python\framework\constant_op.py in _constant_tensor_conversion_function(v, dtype, name, as_ref)
    303                                          as_ref=False):
    304   _ = as_ref
--> 305   return constant(v, dtype=dtype, name=name)
    306 
    307 

~\Anaconda3\envs\Tensorflow_2_0_Beta\lib\site-packages\tensorflow\python\framework\constant_op.py in constant(value, dtype, shape, name)
    244   """
    245   return _constant_impl(value, dtype, shape, name, verify_shape=False,
--> 246                         allow_broadcast=True)
    247 
    248 

~\Anaconda3\envs\Tensorflow_2_0_Beta\lib\site-packages\tensorflow\python\framework\constant_op.py in _constant_impl(value, dtype, shape, name, verify_shape, allow_broadcast)
    252   ctx = context.context()
    253   if ctx.executing_eagerly():
--> 254     t = convert_to_eager_tensor(value, ctx, dtype)
    255     if shape is None:
    256       return t

~\Anaconda3\envs\Tensorflow_2_0_Beta\lib\site-packages\tensorflow\python\framework\constant_op.py in convert_to_eager_tensor(value, ctx, dtype)
    113     return t
    114   else:
--> 115     return ops.EagerTensor(value, handle, device, dtype)
    116 
    117 

ValueError: Attempt to convert a value (1.0) with an unsupported type (<class 'numpy.float32'>) to a Tensor.
`

**Comment by achandraa** [comment]
I have tried the code snippet in Colab with TF GPU version 2.0beta1 and it executed without error.  Please help us to reproduce the issue. Thanks!

**Comment by guyko81** [comment]
Thanks for the reply, I have re-installed the tensorflow 2.0beta1, and now the problem is not present anymore. 
Don't know the reasons why, sorry.

**Comment by achandraa** [comment]
Great to know the issue is resolved. Thanks!

**Comment by michalisfrangos** [comment]
Unfortunately, the error has returned!

- tensorlfow version : 2.1.0-dev20191023 

-  python 3.7
- error  `ValueError: Attempt to convert a value (1) with an unsupported type (<class 'numpy.int32'>) to a Tensor.

- code to reproduce:

`import os
import glob
import numpy as np
import tensorflow as tf
import matplotlib.pyplot as plt

import tensorflow as tf
print(tf.__version__)

def windowed_dataset(series, window_size, batch_size, shuffle_buffer):
    series = tf.expand_dims(series, axis=-1)
    ds = tf.data.Dataset.from_tensor_slices(series)
    ds = ds.window(window_size + 1, shift=1, drop_remainder=True)
    ds = ds.flat_map(lambda w: w.batch(window_size + 1))
    ds = ds.shuffle(shuffle_buffer).repeat()    
    ds = ds.map(lambda w: (w[:-1], w[1:]))
    return ds.batch(batch_size)# .prefetch(1)


#data
n = 3500
time = np.arange(0,n,dtype= np.float)
series = np.sin(time/50.) + 0.5*np.random.rand(np.size(time))+1
split_time = 3000
time_train = time[:split_time]
x_train = series[:split_time]
time_valid = time[split_time:]
x_valid = series[split_time:]
#plt.plot(series)

tf.keras.backend.clear_session()
tf.random.set_seed(51)
np.random.seed(51)
window_size = 64
batch_size = 256
shuffle_buffer_size = 1000

# format data for rnn
train_set = windowed_dataset(x_train, window_size=window_size, batch_size=100, shuffle_buffer=shuffle_buffer_size)

# model 
inputs = tf.keras.Input(shape=(window_size,1))
x = tf.keras.layers.Conv1D(filters=60, kernel_size=5,
                           strides=1, padding="causal",
                           activation="relu",
                           input_shape=[window_size, 1])(inputs)
x = tf.keras.layers.LSTM(64, return_sequences=True)(x)
x = tf.keras.layers.LSTM(64, return_sequences=True)(x)
x = tf.keras.layers.Dense(30, activation="relu")(x)
x = tf.keras.layers.Dense(10, activation="relu")(x)
x = tf.keras.layers.Dense(1)(x)
outputs = tf.keras.layers.Lambda(lambda x: x * 3)(x)
model = tf.keras.Model(inputs=inputs, outputs=outputs)

optimizer = tf.keras.optimizers.SGD(lr=5e-3, momentum=0.9)
model.compile(loss=tf.keras.losses.Huber(),
              optimizer=optimizer,
              metrics=["mae"])

history = model.fit(train_set,epochs= 60, steps_per_epoch = 10)
`

`

**Comment by leo-gan** [comment]
Installing numpy 1.16.4 worked for me. Thanks!

**Comment by edwardpassagi** [comment]
reverting to numpy 1.16.4 fixes the problem for me, thanks.
