### ISSUE TITLE
Enable SupervisedInputReceiver

### ISSUE THREAD

**Issue by WangYongzhao** [tensorflow/tensorflow#30159]
I want to serving a model with SupervisedInputReceiver, but I found this feature is not official supported by tensorflow. Is there replacement for this feature? if no, I suggest to enable this feature.

**System information**
- TensorFlow version (you are using): 1.13.1
- Are you willing to contribute it (Yes/No): Yes

**Describe the feature and the current behavior/state.**
https://github.com/tensorflow/estimator/blob/master/tensorflow_estimator/python/estimator/export/export.py#L251
this class is not in the related __init__.py, so can't use it officially

**Will this change the current api? How?** I think no.

**Who will benefit with this feature?** who want to serve model with both input/output.

**Comment by achandraa** [comment]
Thanks for your contribution to the community. This feature looks like related to serving a model. Can you please raise the issue in [TensorFlow Serving](https://github.com/tensorflow/serving/issues) repository for better and faster help. Thanks!

**Comment by WangYongzhao** [comment]
sure, moved to TensorFlow Serving.

**Comment by WangYongzhao** [comment]
kindly ping...

**Comment by gowtham-kp** [comment]
@WangYongzhao Can you please provide how 'SupervisedInputReceiver' can help the wider community?

**Comment by WangYongzhao** [comment]
do you mean the difference of 'ServingInputReceiver' and 'SupervisedInputReceiver'?
its function diff should be clear here. https://github.com/tensorflow/estimator/blob/master/tensorflow_estimator/python/estimator/export/export.py#L251

for my cases, I was doing some neural machine trasatlation experiment, I can use 'ServingInputReceiver' to generate some traslations, while i can use 'SupervisedInputReceiver' to get the relation of translation/source.

This should be a very generic usage, and that's why someone already implement this feature.
Just don't know why not expose this feature.

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.
