### ISSUE TITLE
Documentation Page - CSS is messed up

### ISSUE THREAD

**Issue by suyashjoshi** [tensorflow/tensorflow#30151]
Bug Description:

## URL(s) with the issue:
https://www.tensorflow.org/api_docs/java/reference/org/tensorflow/package-summary

### Clear description

See above
<img width="1494" alt="Screen Shot 2019-06-25 at 2 29 37 PM" src="https://user-images.githubusercontent.com/395039/60135239-1eba0580-9756-11e9-9094-3430ab265841.png">

### Correct links

N/A

### Parameters defined

N/A

### Returns defined

N/A

### Raises listed and defined

N/A

### Usage example

See attached screenshot

### Request visuals, if applicable

Yes, see attached screenshot

### Submit a pull request?

No

**Comment by ymodak** [comment]
I was able to load the link successfully using safari browser on macbook pro. Please make sure you have strong internet connection and try again. Thanks!
