### ISSUE TITLE
Tensorflow Webpage API tab Link error

### ISSUE THREAD

**Issue by SAswinGiridhar** [tensorflow/tensorflow#30164]
## Description of issue (what needs changing):

The Tensorflow API for 1.13 leads to 1.12 page kindly fix the hyperlink .

### Clear description

The change in the API list can cause confusion

### Request visuals, if applicable
![image](https://user-images.githubusercontent.com/11817160/60156197-98f79200-9809-11e9-846d-c7d2d1471a74.png)

**Comment by lamberta** [comment]
Fixed in https://github.com/tensorflow/tensorflow/issues/30206
