### ISSUE TITLE
TF 2.0 - Put Tensor into some Numpy functions continuously increases memory usage

### ISSUE THREAD

**Issue by movinghoon** [tensorflow/tensorflow#30165]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04
- TensorFlow installed from (source or binary): pip package tensorflow==2.0.0-beta1
- TensorFlow version (use command below): v2.0.0-beta0-17-g8e423e3 2.0.0-beta1
- Python version: 3.7.3
- CUDA/cuDNN version: 10.0.0/7.3.1
- GPU model and memory: Titan Xp 11Gb

**Describe the current behavior**
 Memory leak when we put Tensor into some Numpy functions (ex - np.array(), np.zeros_like()). Following attached code continuously increases memory usage.

**Describe the expected behavior**
No memory usage explosion.

**Code to reproduce the issue**
```
import tensorflow as tf
import numpy as np
import time

x = tf.random.normal((1024, 1024))
for i in range(int(1e7)):
    y = np.array(x)
    time.sleep(0.01)
```

**Comment by achandraa** [comment]
I have tried on Colab with TF GPU version 2.0beta1 and was able to reproduce the issue. The code snippet caused crashed in Colab after using all available RAM.

**Comment by alextp** [comment]
@superbobry is this related to the recent __array_interface__ changes?

**Comment by superbobry** [comment]
I couldn't reproduce the issue using the nightly when running on CPU. Will be able to try on GPU on Monday.

**Comment by superbobry** [comment]
I've reproduced the leak on GPU, fix is on the way.
