### ISSUE TITLE
TFLite GPU works slower than CPU

### ISSUE THREAD

**Issue by Augnine** [tensorflow/tensorflow#30169]
I run tflite in Qualcomm 660, for a test，there is just a con2d. But when i run it,
cpu costs 30ms  while  cpu costs 130ms.
I don't know why

**Comment by zchfaq** [comment]
![test](https://user-images.githubusercontent.com/8298991/60170483-18518980-983b-11e9-9a80-cce3d1aa3518.JPG)

**Comment by ymodak** [comment]
> I run tflite in Qualcomm 660, for a test，there is just a con2d. But when i run it,
> cpu costs 30ms while cpu costs 130ms.
> I don't know why

I believe there's a slight typo here. However can you please confirm the performance of gpu over cpu. Thanks!

**Comment by zchfaq** [comment]
@ymodak  I am sorry ,i made a mistake in writing. gpu costs 130ms, much slower than cpu

**Comment by impjdi** [comment]
@zchfaq 

Wow, that's a pretty weird tensor dims that I haven't seen in the past.  I'm pretty sure our shaders are not optimized for that use case.  How did you get to a tensor size of 1x1x32000x1 and then apply conv of 256x1x20x1?  Can you elaborate a bit?

**Comment by maoxin7676** [comment]
Thank you for your prompt attention to this matter. Our task is audio processing，the 1*1*32000*1 tensor is original input （sample rate 8000Hz， time 4s）,apply conv of 256*1*20*1 for encoding.

**Comment by maoxin7676** [comment]
Thank you for your prompt attention to this matter. Our task is audio processing，the1x1x32000x1 tensor is original input （sample rate 8000Hz， time 4s）,apply conv of 256x1x20x1 for encoding.

> @zchfaq
> 
> Wow, that's a pretty weird tensor dims that I haven't seen in the past. I'm pretty sure our shaders are not optimized for that use case. How did you get to a tensor size of 1x1x32000x1 and then apply conv of 256x1x20x1? Can you elaborate a bit?

**Comment by impjdi** [comment]
@maoxin7676 

Thanks for clarification.  I was able to check that it's even worse on my Pixel 2 XL than what you reported.

[conv_2d.tflite.zip](https://github.com/tensorflow/tensorflow/files/3344500/conv_2d.tflite.zip)

This is an artificial TFLite file I have generated.  I'll check tomorrow why it's doing so bad.

**Comment by impjdi** [comment]
@maoxin7676 @zchfaq 

Sorry that it took longer (I got busy earlier in the week, and then there was independence day holiday).

As I mentioned earlier, it's a pretty unusual configuration for which we haven't optimized.  I don't have your `CONV_2D`'s `Conv2DOptions`, so I cannot tell the exact settings.  However, now that everything is open sourced, you can play around yourself ;)

The parallelization of the `CONV_2D` op is specified right here:
`//tensorflow/lite/delegates/gpu/gl/kernels/conv.cc` which may (or may not) lead to
`//tensorflow/lite/delegates/gpu/gl/workgroups/default_calculator.cc`.  There is a limit of the total number of threads per GPU.  It can range from 128 to 512 depending on the model, but other than that, you can play around with the setting to optimize for your tensor shape.

Also note that the tensor shape of 1x1x32000x1 will be expanded internally to 1x1x32000x4.  So you will get a significant hit on the memory size.  OpenGL delegate is mainly memory bound, so if possible, I would try to change 1x1x32000x1 to 1x1x1x32000 and then change the `CONV_2D` somehow, but that may not be trivial.

If playing with workload and workgroup doesn't work, in worst case, you are left with writing your own shader program code for maximum parallelism.

**Comment by kumariko** [comment]
@Augnine Could you please let us know if this issue still persists ? If it is resolved then please feel free to move this issue to close status ? please check https://github.com/tensorflow/tensorflow/issues/30169#issuecomment-509416942 Thanks!
