### ISSUE TITLE
How does Tensorflow convert to TensorflowJS?

### ISSUE THREAD

**Issue by zzj0402** [tensorflow/tensorflow#30166]
I am working on a conversion of a Java machine learning platform. I am curious on how did TensorFlow manage to transcompile. If so, which toolsets are used?

**Comment by gadagashwini** [comment]
This is not Build/Installation or Bug/Performance issue. Please post this kind of support questions at [StackOverflow](http://stackoverflow.com/questions/tagged//tensorflow). There is a big community to support and learn from your questions. GitHub is mainly for addressing bugs in installation and performance. Thanks!

**Comment by gadagashwini** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
