### ISSUE TITLE
How to write the  .bmp images from tensors to disk after resizing ?

### ISSUE THREAD

**Issue by mohapatras** [tensorflow/tensorflow#30172]
I am trying to read bmp images, resize them and write the image to disk using tensorflow. I have succeeded in reading it but unable to find a way write it to disk. Any idea how to do it ?

Here is the code below:

```
import tensorflow as tf

img_path = "D:/image01.bmp"

img = tf.read_file(img_path)

img_decode = tf.image.decode_bmp(img, channels=1) # unit8 tensor

IMG_WIDTH = 256

IMG_HEIGHT = 256

img_cast = tf.cast(img_decode,dtype=tf.float32)

img_res = tf.image.resize_bilinear(img_4d, (IMG_HEIGHT, IMG_WIDTH), align_corners=True)
```
The problem is I can't find a "encode_bmp" or any bmp related function that can be used to encode the image and save the resized image to disk.

**Comment by mohapatras** [comment]
@gadagashwini I tried reading, preprocessing images with tensorflow APIs. e.g. JPEG, PNG etc. I see a encode function for each formats but not the same for "BMP". Having that option to encode it back will help.

**Comment by gadagashwini** [comment]
@mohapatras Thanks for finding this.

**Comment by freedomtan** [comment]
@mohamedadaly I started and contributed the bmp decoder so that I can test TensorFlow in command line programs on Android (Android image decoding APIs are Java APIs. Not easy to use them in command line C++ programs). So, yes, if nobody contributed a decoder for bmp, maybe you can start one :-)

**Comment by mohapatras** [comment]
@freedomtan I think "decoder for bmp" should be encoder.

**Comment by freedomtan** [comment]
@mohapatras yes, updated :-)

**Comment by mohapatras** [comment]
@ymodak Any solution yet on encoding bitmaps ?

**Comment by mihaimaruseac** [comment]
To be honest, TensorFlow seems overkill for the flow described here. If you only want to programmatically resize images you can use ImageMagik or Python's PIL.

I think adding an encoder for bitmaps to TensorFlow is very low priority, but PRs are always welcome.

**Comment by yongtang** [comment]
@mohapatras I added encode_bmp in tensorflow-io PR https://github.com/tensorflow/io/pull/539, you can take a look. If the API is stable enough later on we can push to TensorFlow core repo if needed.

**Comment by mohapatras** [comment]
@yongtang Sorry for the late reply. I will look into it. Thank you.

**Comment by rmothukuru** [comment]
@mohapatras,
Can you please let us know if [this PR](https://github.com/tensorflow/io/pull/539) has resolved this issue so that close it? Thanks!

**Comment by mohapatras** [comment]
@rmothukuru Yes the issue is resolved. Sorry for the late reply.
