### ISSUE TITLE
Keras model doesn't compile for Edge-tpu if Dense layer contains [16, 32, 64, ...] neurons

### ISSUE THREAD

**Issue by YaroslavSchubert** [tensorflow/tensorflow#30173]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Google Colab
- TensorFlow version (use command below): 1.15.0-dev20190626, 2.0-beta1
- Python version: 3

**Describe the current behavior**
Couldn't convert keras model for Edge-tpu when Dense layer consists of [16, 32, 64, 128, 2^n and n>3]  neurons , but work for any other number.
Error:

```
 ERROR: :119 std::abs(input_product_scale - bias_scale) <= 1e-6 * std::min(input_product_scale, bias_scale) was not true.
ERROR: Node number 33 (FULLY_CONNECTED) failed to prepare.
```

**Describe the expected behavior**
Convert keras model for Edge-tpu successfully

**Code to reproduce the issue**
Colab to reproduce issue:
https://colab.research.google.com/drive/1H0L-UioDKHdl6QbT6OtJc5jplzWTi1qB

**Comment by petewarden** [comment]
This looks like an Edge TPU issue that I'm not familiar with, so unassigning myself.

**Comment by jvishnuvardhan** [comment]
Is this still an issue? Can you check with `TF2.0` and let us know whether the issue persists with latest TF version. Thanks!

**Comment by jvishnuvardhan** [comment]
@YaroslavSchubert Is this still an issue? If not, please close this issue. Thanks!

**Comment by jvishnuvardhan** [comment]
Closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
