### ISSUE TITLE
Getting `bad_alloc` in allocateTensors 

### ISSUE THREAD

**Issue by aminbenarieb** [tensorflow/tensorflow#30176]
**What I've done:**
I've picked up [one of iOS Tensorflow examples]([https://github.com/tensorflow/examples/tree/master/lite/examples/object_detection/ios]) and tried to use my `.tflite` model

**What I expected**:
Loaded model just like in the example.

**What I've got**:
`uncaught exception of type std::bad_alloc` and here are the logs with it:
```
    2019-06-26 15:25:45.414765+0300 Celly[5485:1152189] Initialized TensorFlow Lite runtime.
    Celly(5485,0x1006aebc0) malloc: can't allocate region
    *** mach_vm_map(size=1800945664) failed (error code=3)
    Celly(5485,0x1006aebc0) malloc: *** set a breakpoint in malloc_error_break to debug
    libc++abi.dylib: terminating with uncaught exception of type std::bad_alloc: std::bad_alloc
```

Is there any known workaround or help from documentation or so? Is this problem in the model, so it needs to be optimised or configured appropriately?

**Comment by aminbenarieb** [comment]
It seems that the issue is coming from the model, so it needs to be optimized. I managed to avoid out of memory crash by increasing the number of threads the tensorflow interpreter could use.

**Comment by kumariko** [comment]
please follow this [**link**](https://stackoverflow.com/questions/9456728/how-to-deal-with-bad-alloc-in-c) for the clarification of your issue, I hope it helps. Feel free to open new issue if the issue still persists. Thanks!
