### ISSUE TITLE
how to generate image_ops.h with makefile?

### ISSUE THREAD

**Issue by kakashidan** [tensorflow/tensorflow#3017]
As TensorFlow v0.9.0 RC0 add makefile for better cross-platform build support (C API only), i try to compile [Image Recognition](https://www.tensorflow.org/versions/r0.9/tutorials/image_recognition/index.html) with makefile (which is compiled with bazel originally). However, it raise error that 

```
image_ops.h: No such file...
```

And I cannot find `image_ops.h` in `tensorflow/cc/ops/`. But when I compile it with Bazel, the error is gone.
### what you have tried?
1. I analysed `tensorflow/tensorflow.bzl` and `BUILD` files related and found that image_ops.h(or many others) was generated by `tensorflow/cc/ops/cc_op_gen.cc` automatically.
2. I found files which generated by`tensorflow/contrib/makefile/gen_file_lists.sh` didn't contain cc_ops_gen.cc etc. Is it not supported yet with makefile?
### My Questions:
1. how to generate image_ops.h with makefile so as to compile [Image Recongnition](https://www.tensorflow.org/versions/r0.9/tutorials/image_recognition/index.html) successfully.
2. Has image_ops any other lib dependencies?

**Comment by cg31** [comment]
A simple workaround is: run Bazel to generate the ops files, then use them.

FYI, I asked if these files could be generted by Makefile before:
https://github.com/tensorflow/tensorflow/pull/2440#issuecomment-221466416

**Comment by kakashidan** [comment]
@cg31 Thank you for your reply. The idea, using the ops files generated by Bazel, seems to NOT work for me.
Actually, I wanna to use ops such as DecodePng, DecodeJpeg, ReadFile, etc. However, these ops are not compiled into libtensorflow-core.a and link errors below are raised.
```
main.cc:(.text+0x386): undefined reference to `tensorflow::ops::Const(tensorflow::StringPiece, tensorflow::GraphDefBuilder::Options const&)'
main.cc:(.text+0x3b9): undefined reference to `tensorflow::ops::ReadFile(tensorflow::NodeBuilder::NodeOut, tensorflow::GraphDefBuilder::Options const&)'
main.cc:(.text+0x4ff): undefined reference to `tensorflow::ops::DecodePng(tensorflow::NodeBuilder::NodeOut, tensorflow::GraphDefBuilder::Options const&)'
main.cc:(.text+0x5fa): undefined reference to `tensorflow::ops::DecodeJpeg(tensorflow::NodeBuilder::NodeOut, tensorflow::GraphDefBuilder::Options const&)'
main.cc:(.text+0x6ad): undefined reference to `tensorflow::ops::Cast(tensorflow::NodeBuilder::NodeOut, tensorflow::DataType, tensorflow::GraphDefBuilder::Options const&)'
main.cc:(.text+0x700): undefined reference to `tensorflow::ops::Const(int, tensorflow::GraphDefBuilder::Options const&)'
main.cc:(.text+0x754): undefined reference to `tensorflow::ops::ExpandDims(tensorflow::NodeBuilder::NodeOut, tensorflow::NodeBuilder::NodeOut, tensorflow::GraphDefBuilder::Options const&)'
main.cc:(.text+0x87f): undefined reference to `tensorflow::ops::ResizeBilinear(tensorflow::NodeBuilder::NodeOut, tensorflow::NodeBuilder::NodeOut, tensorflow::GraphDefBuilder::Options const&)'
main.cc:(.text+0xa2d): undefined reference to `tensorflow::ops::Sub(tensorflow::NodeBuilder::NodeOut, tensorflow::NodeBuilder::NodeOut, tensorflow::GraphDefBuilder::Options const&)'
main.cc:(.text+0xa67): undefined reference to `tensorflow::ops::Div(tensorflow::NodeBuilder::NodeOut, tensorflow::NodeBuilder::NodeOut, tensorflow::GraphDefBuilder::Options const&)'
main.o: In function `LoadGraph(std::string, std::unique_ptr<tensorflow::Session, std::default_delete<tensorflow::Session> >*)':
main.cc:(.text+0x1170): undefined reference to `tensorflow::ReadBinaryProto(tensorflow::Env*, std::string const&, google::protobuf::MessageLite*)'
main.o: In function `GetTopLabels(std::vector<tensorflow::Tensor, std::allocator<tensorflow::Tensor> > const&, int, tensorflow::Tensor*, tensorflow::Tensor*)':
main.cc:(.text+0x1445): undefined reference to `tensorflow::ops::Const(int, tensorflow::GraphDefBuilder::Options const&)'
main.cc:(.text+0x1490): undefined reference to `tensorflow::ops::Const(tensorflow::Tensor const&, tensorflow::GraphDefBuilder::Options const&)'
main.cc:(.text+0x14ca): undefined reference to `tensorflow::ops::TopKV2(tensorflow::NodeBuilder::NodeOut, tensorflow::NodeBuilder::NodeOut, tensorflow::GraphDefBuilder::Options const&)'
main.o: In function `main':
main.cc:(.text+0x22ed): undefined reference to `tensorflow::Flag::Flag(char const*, std::string*)'
main.cc:(.text+0x230f): undefined reference to `tensorflow::Flag::Flag(char const*, std::string*)'
main.cc:(.text+0x2331): undefined reference to `tensorflow::Flag::Flag(char const*, std::string*)'
main.cc:(.text+0x23e7): undefined reference to `tensorflow::Flag::Flag(char const*, std::string*)'
main.cc:(.text+0x240c): undefined reference to `tensorflow::Flag::Flag(char const*, std::string*)'
main.o:main.cc:(.text+0x2456): more undefined references to `tensorflow::Flag::Flag(char const*, std::string*)' follow
main.o: In function `main':
main.cc:(.text+0x267d): undefined reference to `tensorflow::io::JoinPath(tensorflow::StringPiece, tensorflow::StringPiece)'
main.cc:(.text+0x279f): undefined reference to `tensorflow::io::JoinPath(tensorflow::StringPiece, tensorflow::StringPiece)'
main.o: In function `tensorflow::ops::Const(std::initializer_list<float>, tensorflow::GraphDefBuilder::Options const&)':
```

**Comment by danieleghisi** [comment]
Hi, 

I think I have the same issue; I cannot find the many .h files needed to compile via C/C++ api and apparently generated by cc_op_gen (the first of which is array_ops.h).

@cg31: how can I run Bazel to generate the ops files? What command should I use?
I've tried "bazel build cc_ops" (while inside the cc folder), but that didn't seem work.

I'm sorry if the question is silly - I'm a tensorflow/bazel newbie...

Daniele

**Comment by kakashidan** [comment]
@danieleghisi you can run bazel in the tensorflow root directory
```bazel build tensorflow/cc:cc_ops```. But, the ops files generated stay in the ```bazel-genfiles/tensorflow/cc/ops```

```bazel build cc_ops``` don't work because of some relative path in the BUILD file.

eg.
```
git clone https://github.com/tensorflow/tensorflow
cd tensorflow
bazel build tensorflow/cc:cc_ops
```

**Comment by hartsantler** [comment]
`bazel build tensorflow/cc::cc_ops` may work, didn't get a chance to try it because it trigger a full rebuild of tensorflow, which takes forever on my machine.

I noticed this ugly code in `cc_op_gen.cc`
```c++
// Converts:
//   bazel-out/.../genfiles/(external/YYY/)?XX
// to: XX.
string GetPath(const std::string& dot_h_fname) {
  auto pos = dot_h_fname.find("/genfiles/");
  string result = dot_h_fname;
  if (pos != string::npos) {
    // - 1 account for the terminating null character (\0) in "/genfiles/".
    result = dot_h_fname.substr(pos + sizeof("/genfiles/") - 1);
  }
  if (result.size() > sizeof("external/") &&
      result.compare(0, sizeof("external/") - 1, "external/") == 0) {
    result = result.substr(sizeof("external/") - 1);
    pos = result.find("/");
    if (pos != string::npos) {
      result = result.substr(pos + 1);
    }
  }
  return result;
}
```

by ugly i mean, generating header files from a script-like c++ program that is hard coded to the bazel build system.

**Comment by danieleghisi** [comment]
Thanks, I had managed to compile, but I didn't know that generated files were in bazel-genfiles/tensorflow/cc/ops and for some reason I couldn't find them. That works!

**Comment by tomasreimers** [comment]
@danieleghisi, did this work for you? I am still finding I need to link against the gif_archive / jpeg_archive / png_archive to get the functions that underly the DecodeImage ops...

**Comment by danieleghisi** [comment]
@tomasreimers I still have some issues but I can't fully remember which ones; I ended up removing everything and reinstalling, yet I gave up on the C api thing; just using python...

**Comment by ipeerbhai** [comment]
I just ran into the same missing file on Windows when building.  Bazel isn't one of the Windows requirements, so how do I generate the file on that platform?  CMAKE/SWIG don't return any errors, and only when building with MSBuild do I see image_ops.h and array_ops.h as missing.

**Comment by gunan** [comment]
On windows, you can use either CMAKE or Bazel.
We use makefile primarily for iOS support.
@kakashidan It is possible some of the libraries you are trying to use are excluded in makefile build?
You can see this piece for details:
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/makefile/Makefile#L418

Please see the README file in makefile folder for more details.

**Comment by drpngx** [comment]
Assuming @gunan 's instructions worked.

**Comment by Koshub** [comment]
@gunan So what are the steps to include for example "tensorflow/cc/ops/array_ops.h" to the result build? Do I need firstly build with Bazel and then with makefile or do I need to add functions I want to use to makefile/tf_*_files.sh and then just build with makefile? I'm trying to build for iOS using build_all_ios.sh so could you please describe the steps? I would like to use examples from https://www.tensorflow.org/api_guides/cc/guide but I need use Bazel functionality. It is good to reduce the lib size to exclude some functions but how could I run different small examples on iOS?
