### ISSUE TITLE
build using cmake failed

### ISSUE THREAD

**Issue by sragini24** [tensorflow/tensorflow#30183]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): Source
- TensorFlow version:1.14.0
- Python version:3.6
- Installed using virtualenv? pip? conda?:virtualenv
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source): VS 2105
- CUDA/cuDNN version: 10
- GPU model and memory: GTX Titan X

**Describe the problem**
Missing directory/files: tensorflow/contrib/tpu/ops
**Provide the exact sequence of commands / steps that you executed before running into the problem**
running Cmake 
tensorflow/contrib/cmake/python_modules.txt contains the line but no  tensorflow/contrib/tpu/ops does not exist

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by gadagashwini** [comment]
@sragini24 We don't provide support for the CMake build anymore. Please use bazel instead to build.Thanks!

**Comment by sragini24** [comment]
Could you provide me a link to the procedures to use bazel  to generate c++ code for use with Visual Studio 2015?
Thanks

**Comment by gadagashwini** [comment]
@sragini24  Have a look at this issue [#24885](https://github.com/tensorflow/tensorflow/issues/24885). Thanks

**Comment by gadagashwini** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
