### ISSUE TITLE
Signature Issue in Docker image

### ISSUE THREAD

**Issue by mrcpj1998** [tensorflow/tensorflow#30196]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Docker - Arch Linux 5.1.15-arch1
- TensorFlow installed from (source or binary): Through docker
- TensorFlow version (use command below): latest
- Python version: 3
- GPU model and memory: GTX 2080, 8 i think?

**Describe the current behavior**
When pulling the docker image `tensorflow/tensorflow:latest-gpu-py3` and running `apt-get update` some signatures fail to fetch and thus the build fails immediately

**Describe the expected behavior**
Should update apt issues

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.
This was tested 27/06/2019:  

    cd `mktemp -d`
    echo "FROM tensorflow/tensorflow:latest-gpu-py3" > Dockerfile
    echo "RUN apt-get update" >> Dockerfile
    docker build .

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.
Terminal log: https://pastebin.com/EYzFE5wP

**Comment by wdirons** [comment]
I just tried this and did not get an error. Could it be an environment issue?

Ping @angersson for this thoughts

```
$ docker build .
Sending build context to Docker daemon 2.048 kB
Step 1/2 : FROM tensorflow/tensorflow:latest-gpu-py3
Trying to pull repository registry.access.redhat.com/tensorflow/tensorflow ...
Pulling repository registry.access.redhat.com/tensorflow/tensorflow
Trying to pull repository docker.io/tensorflow/tensorflow ...
latest-gpu-py3: Pulling from docker.io/tensorflow/tensorflow
6abc03819f3e: Already exists
05731e63f211: Already exists
0bd67c50d6be: Already exists
d5c73556cc1e: Already exists
e059dd98ac7c: Already exists
e4732fdd9b39: Already exists
cbeb255d6ab1: Pull complete
0809e577f6d6: Pull complete
421e23cecfe8: Pull complete
a5abf0996067: Pull complete
d718e4299c08: Pull complete
f401bdaa92ad: Pull complete
6669e38ab1ba: Pull complete
5b6ac7f35d3d: Pull complete
Digest: sha256:e72e66b3dcb9c9e8f4e5703965ae1466b23fe8cad59e1c92c6e9fa58f8d81dc8
Status: Downloaded newer image for docker.io/tensorflow/tensorflow:latest-gpu-py3
 ---> a7a1861d2150
Step 2/2 : RUN apt-get update
 ---> Running in 26b8c9aa858a

Get:1 file:/var/nvinfer-runtime-trt-repo-5.0.2-ga-cuda10.0  InRelease
Ign:1 file:/var/nvinfer-runtime-trt-repo-5.0.2-ga-cuda10.0  InRelease
Get:2 file:/var/nvinfer-runtime-trt-repo-5.0.2-ga-cuda10.0  Release [574 B]
Get:2 file:/var/nvinfer-runtime-trt-repo-5.0.2-ga-cuda10.0  Release [574 B]
Ign:3 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64  InRelease
Hit:4 http://archive.ubuntu.com/ubuntu bionic InRelease
Get:5 http://security.ubuntu.com/ubuntu bionic-security InRelease [88.7 kB]
Ign:7 https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1804/x86_64  InRelease
Hit:8 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64  Release
Get:9 http://archive.ubuntu.com/ubuntu bionic-updates InRelease [88.7 kB]
Get:10 https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1804/x86_64  Release [564 B]
Get:11 https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1804/x86_64  Release.gpg [801 B]
Get:12 http://archive.ubuntu.com/ubuntu bionic-backports InRelease [74.6 kB]
Get:14 http://security.ubuntu.com/ubuntu bionic-security/universe amd64 Packages [720 kB]
Get:15 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 Packages [865 kB]
Get:16 https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1804/x86_64  Packages [10.8 kB]
Get:17 http://archive.ubuntu.com/ubuntu bionic-updates/universe amd64 Packages [1229 kB]
Get:18 http://security.ubuntu.com/ubuntu bionic-security/main amd64 Packages [561 kB]
Get:19 http://archive.ubuntu.com/ubuntu bionic-backports/universe amd64 Packages [3927 B]
Fetched 3644 kB in 2s (1715 kB/s)
Reading package lists...
 ---> e22d3844eff4
Removing intermediate container 26b8c9aa858a
Successfully built e22d3844eff4
```

**Comment by mrcpj1998** [comment]
@wdirons Haven gotten home from work i tried it on a local desktop. No issues there. I guess i'll have to look into the environment tomorrow.

Any idea what can cause these kinds of glitches?

**Comment by mihaimaruseac** [comment]
Could be an issue upstream, on `apt` side.

**Comment by angersson** [comment]
@mrcpj1998 It's also possible that an old local version of `latest-gpu-py3` could be causing this. Does anything change if you run `docker pull tensorflow/tensorflow:latest-gpu-py3` first?

I also couldn't replicate the issue on my machine.

**Comment by gadagashwini** [comment]
@mrcpj1998 Did you get a chance look @angersson's solution. Thanks!

**Comment by mrcpj1998** [comment]
After yesterday, did a pacman -Syu and docker pull, then built without cache. I haven't been able to reproduce this image. So definitely something weird, but this issue can be closed

**Comment by gadagashwini** [comment]
@mrcpj1998 Will close issue now, Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
