### ISSUE TITLE
Resnet model Tensorflow facial landmarks (Detect in real time)

### ISSUE THREAD

**Issue by abdou31** [tensorflow/tensorflow#30197]
Hello,
I worked on a project (CNN facial landmarks [github project](https://github.com/yinguobing/cnn-facial-landmark). 
I set my own dataset and I trained to detect just the eye region.
My question is:
Did can this project ( Resnet Model ) support detection in real time?
If yes, How Tensorflow works to detect in real time?
Thanks

**Comment by capilano** [comment]
Resnet 18 can give you real time performance(or at least near real-time) on a mobile GPU and probably even on a good CPU if you adjust the channels carefully. Just go with a conventional CNN model is my suggestion. I built one a while back(using squeeze net like structures) with fairly good performance.(less than 10ms on a desktop CPU for a single image)

**Comment by abdou31** [comment]
I have tested a script that tested the frozen model produced after training,
Actually, for the video, I get false prediction and I can see landmarks drawn on the video stream.
But when I open the webcam I didn't get any landmarks drawn and the video is too slow.
      

            face_img = cv2.resize(face_img, (INPUT_SIZE, INPUT_SIZE))
            face_img = cv2.cvtColor(face_img, cv2.COLOR_BGR2RGB)
            img=np.array(face_img).reshape(1,128,128,3) # update here
            landmarks = detect_marks(img, sess, detection_graph)

As you can see batch=1 ,input_width=128 and channels are 3 (RGB).
So when I tried to increase the number of batchs, I get this error :
> img=np.array(face_img).reshape(32,128,128,3)
ValueError: cannot reshape array of size 49152 into shape (32,128,128,3)

Do you have any idea about how can I solve this error?

**Comment by capilano** [comment]
Why are you asking this question on the tensorflow github issues page?  
I do not get what you are trying to do. Why are you trying to reshape a(1,128,128,3) array into a (32,128,128,3) array? You have to do it like this if this is what you really wanted to do
img_list = []
for i in range(32):
      img = np.array(face_img)  ## do not reshape into (1,128,128,3)
      img_list.append(img)
img_list = np.array(img_list)
img_list = np.reshape(img_list,(32,128,128,3)

**Comment by abdou31** [comment]
The reshape into 32 gives an error that I have posted in the previous comment

**Comment by capilano** [comment]
You can only reshape arrays that have equal sizes.  128*128*3*1, is not equal to 32*128*128*3, so you can not reshape like that.

**Comment by capilano** [comment]
You cannot reshape arrays like that. They have to have the same size, before and after reshape.For example, you can reshape an array of shape (64,2) into an array of shape(128,1) etc where the sizes of the flattened arrays are the same

**Comment by ziyigogogo** [comment]
Stackoverflow is a better place for question like this.

**Comment by abdou31** [comment]
@capilano Thanks, I will try the code that you posted and I will show what I get

**Comment by abdou31** [comment]
@ziyigogogo StackOverflow no longer give any attention to such questions.

**Comment by robieta** [comment]
@capilano and @ziyigogogo are correct: Stackoverflow is the appropriate forum for this sort of question.

**Comment by joel5638** [comment]
Can we train the facial landmark on different models like fasterrcnn, ssd and mobilenet using this https://github.com/yinguobing/cnn-facial-landmark?

**Comment by abdou31** [comment]
@joel5638 I think the answer is no, you should change the architecture

**Comment by joel5638** [comment]
Okay. 
What if i want to follow traditional Deep Learning methodology in labeling the data, creating tf records and then training using rcnn or mobilenet? Is it possible? Using tensorflow or pytorch.

**Comment by abdou31** [comment]
@joel5638 Yes, give it a try
