### ISSUE TITLE
Generating Data Flow Graph for existing code or IR, ByteCode, IL, Object Code, AST, etc.

### ISSUE THREAD

**Issue by sirinath** [tensorflow/tensorflow#302]
There are a lot of existing libraries and code.  It will be good if there is a mechanism to generated the Dataflow representation of these programs in TensorFlow. Say I have a library you can analyse the Intermediate Code (ByteCode, IL, IR, Web Asm, Object Code, directly from particular languages code, etc.) and from this generate the DataFlow graph with a view to target GPU, FPGA, Other Accelerate or conventional scenarios.

There were some commercial products doing just the above but I have forgotten some of these vendors. https://www.maxeler.com/ also do this but just one of the vendors I remember.

**Comment by girving** [comment]
This is out of scope for the main tensorflow project.  Projects that generate TF graphs from other intermediate representations are certainly possible, but they would belong in separate repos.
