### ISSUE TITLE
keras.utils.vis_utils.plot_model() raises TypeError: 'InputLayer' object is not iterable

### ISSUE THREAD

**Issue by CreeperLava** [tensorflow/tensorflow#30204]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Mint 19.3
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.0.0b1
- Python version: 3.6
- CUDA/cuDNN version: /
- GPU model and memory: GTX 940MX, 430.26

**Describe the current behavior**
Running `keras.utils.vis_utils.plot_model()` on a `tensorflow.python.keras.engine.training.Model` object raises `TypeError: 'InputLayer' object is not iterable`. This problem seems very similar to #24622, where the same issue was reported for Sequential objects.

**Describe the expected behavior**
Save a png image of the model.

**Code to reproduce the issue**
```
import tensorflow as tf
from keras.utils.vis_utils import plot_model

input_2D = tf.keras.Input(shape=(None, None, 3)) # unknown width and length, 3 channels (RGB)
network_2D = tf.keras.layers.Conv2D(
    filters = 128,  # dimensionality of output space
    kernel_size = 5,  # shape of 2D convolution window (5x5)
)(input_2D)

input_3D = tf.keras.Input(shape=(None, None, None, 1)) # unknown width, length and depth, 1 gray channel
network_3D = tf.keras.layers.Conv3D(
    filters = 128,  # dimensionality of output space
    kernel_size = 5,  # shape of 2D convolution window (5x5)
)(input_3D)

network_2D = tf.expand_dims(network_2D, axis=-2)
network_combined = network_2D + network_3D

model_combined = tf.keras.Model(inputs = [input_2D, input_3D], outputs = network_combined)
plot_model(model_combined, to_file='model_combined.png')
```

**Other info / logs**
```Traceback (most recent call last):
  File ".../repo/venv/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 3296, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-26-7a3e8204fbca>", line 19, in <module>
    plot_model(model_combined, to_file='model_combined.png')
  File ".../repo/venv/lib/python3.6/site-packages/keras/utils/vis_utils.py", line 132, in plot_model
    dot = model_to_dot(model, show_shapes, show_layer_names, rankdir)
  File ".../repo/venv/lib/python3.6/site-packages/keras/utils/vis_utils.py", line 109, in model_to_dot
    for inbound_layer in node.inbound_layers:
TypeError: 'InputLayer' object is not iterable```

**Comment by gadagashwini** [comment]
@CreeperLava I tried to reproduce the issue on colab with Tensorflow 2.0.0.beta1 but i received following error message `NameError: name 'plot_model' is not defined` .Thanks!

**Comment by CreeperLava** [comment]
Right, I forgot an import. Add `from keras.utils.vis_utils import plot_model`

**Comment by gadagashwini** [comment]
Now I am able reproduce the issue with Tensorflow 2.0.0.beta1 and got the same error.

**Comment by ymodak** [comment]
You may use ```tf.keras.utils.plot_model``` instead of ```from keras.utils.vis_utils import plot_model```
https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/keras/utils/plot_model
This will keep your consistent with TF framework.
Thus your last line of code snippet will be as below;
```python
tf.keras.utils.plot_model(model_combined, to_file='model_combined.png')
```
![image](https://user-images.githubusercontent.com/42785357/60373695-ef093880-99b5-11e9-928d-97c3760d1cb2.png)
