### ISSUE TITLE
sys.version_info conditional for enum34 breaks poetry (and contaminates requires in general)

### ISSUE THREAD

**Issue by areeh** [tensorflow/tensorflow#30200]
To prevent enum34 issues such as #15136 a `sys.version_info` conditional was added, as can be seen in the TF source [here](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/pip_package/setup.py#L101)

As per [PEP508](https://www.python.org/dev/peps/pep-0508/#environment-markers) the recommended way is using environment markers.

Using the old `sys.version_info` method breaks tools such as poetry (see eg [issue 844](https://github.com/sdispater/poetry/issues/844), and the [owner's response](https://github.com/sdispater/poetry/issues/844#issuecomment-458178991))

Specifically this breaks some of our build pipelines that get the enum34 dependency information from PyPi, which is then put into site-packages, contaminating the build and leading to crashes in various interesting ways (eg if pip/python runs from site-packages, it will use enum34 which breaks when `enum.IntFlag` is accessed)

I'm hoping this can be fixed for TensorFlow too, see eg an example [here](https://github.com/confluentinc/confluent-kafka-python/pull/583/commits/4e6250d861c5be23fc45d8d11d2b8f0e8e218ab2)

**Comment by kung-foo** [comment]
PyPi responds with this list of dependencies for tensorflow:
```
$ curl -s https://pypi.org/pypi/tensorflow/1.14.0/json | jq .info.requires_dist
[
  "absl-py (>=0.7.0)",
  "astor (>=0.6.0)",
  "gast (>=0.2.0)",
  "google-pasta (>=0.1.6)",
  "keras-applications (>=1.0.6)",
  "keras-preprocessing (>=1.0.5)",
  "numpy (<2.0,>=1.14.5)",
  "six (>=1.10.0)",
  "protobuf (>=3.6.1)",
  "tensorboard (<1.15.0,>=1.14.0)",
  "tensorflow-estimator (<1.15.0rc0,>=1.14.0rc0)",
  "termcolor (>=1.1.0)",
  "wrapt (>=1.11.1)",
  "grpcio (>=1.8.6)",
  "wheel",
  "mock (>=2.0.0)",
  "backports.weakref (>=1.0rc1)",
  "enum34 (>=1.1.6)"
]
```

compare this to llvmlite which explicitly includes a version marker:

```
$ curl -s https://pypi.org/pypi/llvmlite/json | jq .info.requires_dist
[
  "enum34 ; python_version < \"3.4\""
]
```

**Comment by yongtang** [comment]
Added a PR #30255 for the fix.
