### ISSUE TITLE
API link for r1.13 directs to r1.12 instead

### ISSUE THREAD

**Issue by micw523** [tensorflow/tensorflow#30206]
Thank you for submitting a TensorFlow documentation issue. Per our GitHub
policy, we only address code/doc bugs, performance issues, feature requests, and
build/installation issues on GitHub.

The TensorFlow docs are open source! To get involved, read the documentation
contributor guide: https://www.tensorflow.org/community/contribute/docs

## Description of issue (what needs changing):

The link under API/r1.13 is pointing to r1.12.

The link should point to r1.13 https://www.tensorflow.org/versions/r1.13/api_docs/python/tf

**Comment by lamberta** [comment]
Thanks. Fix is now on prod
