### ISSUE TITLE
installation fails "FAILED: Build did NOT complete successfully"

### ISSUE THREAD

**Issue by xfsm1912** [tensorflow/tensorflow#30205]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): MacOS Mojave 10.14.5
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): source 
- TensorFlow version: 1.13
- Python version: 3.7.3
- Installed using virtualenv? pip? conda?:pip 
- Bazel version (if compiling from source): 0.26.1
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: No CUDA support will be enabled for TensorFlow.
- GPU model and memory: 

**Describe the problem**
after I install Bazel and ./configure, I try to run 'bazel build --config=opt //tensorflow/tools/pip_package:build_pip_package', then it gives me error information:

ERROR: /Users/Jianhua/tensorflow/tensorflow/lite/kernels/internal/BUILD:558:1: undeclared inclusion(s) in rule '//tensorflow/lite/kernels/internal:tensor_utils':
this rule is missing dependency declarations for the following files included by 'tensorflow/lite/kernels/internal/tensor_utils.cc':
  'tensorflow/lite/kernels/internal/optimized/sse_tensor_utils.h'
  'tensorflow/lite/kernels/internal/optimized/sse_tensor_utils_impl.h'
Target //tensorflow/tools/pip_package:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 571.490s, Critical Path: 54.09s
INFO: 673 processes: 673 local.
FAILED: Build did NOT complete successfully

**Provide the exact sequence of commands / steps that you executed before running into the problem**

git clone https://github.com/tensorflow/tensorflow.git
cd tensorflow

./configure

bazel build --config=opt //tensorflow/tools/pip_package:build_pip_package

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by gadagashwini** [comment]
@xfsm1912 Downgrade the bazel version to 0.26.0 and check the build. Let us know if you stuck. Thanks!

**Comment by xfsm1912** [comment]
OK, it looks like I directly run 'pip install tensorflow' can solve the problem with bazel 0.26.1. Now my tensorflow and keras can run well for LSTM structure

**Comment by gadagashwini** [comment]
@xfsm1912 Good to know that you found workaround. Will close this issue now. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
