### ISSUE TITLE
Substitute to keras.backend.get_session()

### ISSUE THREAD

**Issue by sayakpaul** [tensorflow/tensorflow#30218]
Hi. 

Currently, I am exploring the Movidius Neural Compute Stick by Intel along with OpenVINO. For this, I am using `tensorflow` 1.13.1 since it still has `tensorflow.keras.back.get_session()`. Now why `get_session()`. This is because using this function I can easily extract the session from my `tensorflow.keras` model and use that session to generate `.pb` file. This `.pb` file is then supplied to OpenVINO to get the necessary files to run inference on an NCS. 

I am looking for ways to generate the `.pb` file using `tensorflow` 2.0. Following is how I do it using `tensorflow` 1.13.1:

```python
sess = K.get_session()
frozen = tf.graph_util.convert_variables_to_constants(sess,
	sess.graph_def, [model.output.op.name])
graph_io.write_graph(frozen, os.getcwd(), "inference_graph.pb", as_text=False)
```

where K is the alias for `tensorflow.keras.backend`.

**Comment by pandrey-fr** [comment]
Hi,
I have no experience with `.pb` files, but if you have a keras Model instance, you probably can just use `my_model.save('some_folder')`, which creates multiple outputs in the pointed folder, including a `.pb` file.
I hope this helps.

**Comment by sayakpaul** [comment]
@pandrey-fr 

> Hi,
I have no experience with .pb files, but if you have a keras Model instance, you probably can just use my_model.save('some_folder'), which creates multiple outputs in the pointed folder, including a .pb file.
I hope this helps.

Will surely try. I did know about `model.save()` but I did not that it creates `.pb` file. Thank you :)

**Comment by pandrey-fr** [comment]
You're welcome! It used not to, but from the docs it seems that this is becoming the default behavior in TF 2.0.
