### ISSUE TITLE
core dump occurred when run boosted tree classifier demo in official tutorial

### ISSUE THREAD

**Issue by loadwiki** [tensorflow/tensorflow#30211]
Intel(R) Xeon(R) CPU E5-2650 v4 @ 2.20GHz
CentOS Linux release 7.2.1511 (Core)
install from pip
CPU-version
tensorflow                               1.14.0rc1
tensorflow-estimator             1.14.0

Run boosted tree model from [official demo code ](https://www.tensorflow.org/tutorials/estimators/boosted_trees)
`est.train(train_input_fn, max_steps=100)`
If 'max_steps ' set to 100 , core dump occurred.
If 'max_steps ' set to 10, demo code go successful.

I tested the case with tf version 1.13 an another ubuntu docker, issue existed the same.
In tf version 1.10, there is an exception because the implementation of boosted tree does not support numeric columns.

I'm a little confused with the parameter 'max_steps'.  Model trained by SGD, steps refers the times of mini_batch, or something likes 'epoch'.  Optimization algorithm for boosted tree model must compute the entire dataset for both individual tree and tree node split. So what's the param 'steps' and 'max_steps' stand for?

**Comment by gadagashwini** [comment]
@loadwiki I tried executing the official demo code on colab and i set 'max_steps' to 10 and 100, but i did not see an issue. Can you check once and let us know is this still an issue. Thanks!

**Comment by gadagashwini** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
