### ISSUE TITLE
"Could not find platform independent libraries"  && "Missing input file"

### ISSUE THREAD

**Issue by zhangwei0119** [tensorflow/tensorflow#3021]
I am installing Tensorflow on a server without internet access.  I can now build tutorials_example_trainer without GPU support and successfully execute it, but can't move forward to complete the installation. Can you please help me to diagnosis ? Thanks!  

### Environment info
Operating System:
   Red Hat Enterprise Linux Server release 6.6 (Santiago)

Installed version of CUDA and cuDNN: 
(please attach the output of `ls -l /path/to/cuda/lib/libcud*`):
-rw-r--r-- 1 root root  28585480 Aug 15  2015 libcublas_device.a
lrwxrwxrwx 1 root root        16 Jun 15 19:52 libcublas.so -> libcublas.so.7.5
lrwxrwxrwx 1 root root        19 Jun 15 19:52 libcublas.so.7.5 -> libcublas.so.7.5.18
-rwxr-xr-x 1 root root  23938736 Aug 15  2015 libcublas.so.7.5.18
-rw-r--r-- 1 root root  28220076 Aug 15  2015 libcublas_static.a
-rw-r--r-- 1 root root    322936 Aug 15  2015 libcudadevrt.a
lrwxrwxrwx 1 root root        16 Jun 15 19:52 libcudart.so -> libcudart.so.7.5
lrwxrwxrwx 1 root root        19 Jun 22 03:12 libcudart.so.7.0 -> libcudart.so.7.5.18
lrwxrwxrwx 1 root root        19 Jun 15 19:52 libcudart.so.7.5 -> libcudart.so.7.5.18
-rwxr-xr-x 1 root root    383336 Aug 15  2015 libcudart.so.7.5.18
-rw-r--r-- 1 root root    720192 Aug 15  2015 libcudart_static.a
-rwxr-xr-x 1 root root  59909104 Jun 15 20:09 libcudnn.so
-rwxr-xr-x 1 root root  59909104 Jun 15 20:09 libcudnn.so.5
-rwxr-xr-x 1 root root  59909104 Jun 15 20:09 libcudnn.so.5.0.5
lrwxrwxrwx 1 root root        17 Jun 22 03:13 libcudnn.so.6.5 -> libcudnn.so.5.0.5
-rw-r--r-- 1 root root  58775484 Jun 15 20:09 libcudnn_static.a
lrwxrwxrwx 1 root root        15 Jun 15 19:52 libcufft.so -> libcufft.so.7.5
lrwxrwxrwx 1 root root        18 Jun 15 19:52 libcufft.so.7.5 -> libcufft.so.7.5.18
-rwxr-xr-x 1 root root 111231960 Aug 15  2015 libcufft.so.7.5.18
-rw-r--r-- 1 root root 115104400 Aug 15  2015 libcufft_static.a
lrwxrwxrwx 1 root root        16 Jun 15 19:52 libcufftw.so -> libcufftw.so.7.5
lrwxrwxrwx 1 root root        19 Jun 15 19:52 libcufftw.so.7.5 -> libcufftw.so.7.5.18
-rwxr-xr-x 1 root root    447664 Aug 15  2015 libcufftw.so.7.5.18
-rw-r--r-- 1 root root     42206 Aug 15  2015 libcufftw_static.a
lrwxrwxrwx 1 root root        17 Jun 15 19:52 libcuinj64.so -> libcuinj64.so.7.5
lrwxrwxrwx 1 root root        20 Jun 15 19:52 libcuinj64.so.7.5 -> libcuinj64.so.7.5.18
-rwxr-xr-x 1 root root   5751400 Aug 15  2015 libcuinj64.so.7.5.18
-rw-r--r-- 1 root root   1649726 Aug 15  2015 libculibos.a
lrwxrwxrwx 1 root root        16 Jun 15 19:52 libcurand.so -> libcurand.so.7.5
lrwxrwxrwx 1 root root        19 Jun 15 19:52 libcurand.so.7.5 -> libcurand.so.7.5.18
-rwxr-xr-x 1 root root  51765952 Aug 15  2015 libcurand.so.7.5.18
-rw-r--r-- 1 root root  51992564 Aug 15  2015 libcurand_static.a
lrwxrwxrwx 1 root root        18 Jun 15 19:52 libcusolver.so -> libcusolver.so.7.5
lrwxrwxrwx 1 root root        21 Jun 15 19:52 libcusolver.so.7.5 -> libcusolver.so.7.5.18
-rwxr-xr-x 1 root root  37034328 Aug 15  2015 libcusolver.so.7.5.18
-rw-r--r-- 1 root root  16613348 Aug 15  2015 libcusolver_static.a
lrwxrwxrwx 1 root root        18 Jun 15 19:52 libcusparse.so -> libcusparse.so.7.5
lrwxrwxrwx 1 root root        21 Jun 15 19:52 libcusparse.so.7.5 -> libcusparse.so.7.5.18
-rwxr-xr-x 1 root root  36816424 Aug 15  2015 libcusparse.so.7.5.18
-rw-r--r-- 1 root root  44445334 Aug 15  2015 libcusparse_static.a
lrwxrwxrwx 1 root root        14 Jun 15 19:52 libnppc.so -> libnppc.so.7.5
lrwxrwxrwx 1 root root        17 Jun 15 19:52 libnppc.so.7.5 -> libnppc.so.7.5.18
-rwxr-xr-x 1 root root    427168 Aug 15  2015 libnppc.so.7.5.18
-rw-r--r-- 1 root root     20664 Aug 15  2015 libnppc_static.a
lrwxrwxrwx 1 root root        14 Jun 15 19:52 libnppi.so -> libnppi.so.7.5
lrwxrwxrwx 1 root root        17 Jun 15 19:52 libnppi.so.7.5 -> libnppi.so.7.5.18
-rwxr-xr-x 1 root root  63516808 Aug 15  2015 libnppi.so.7.5.18
-rw-r--r-- 1 root root  90106200 Aug 15  2015 libnppi_static.a
lrwxrwxrwx 1 root root        14 Jun 15 19:52 libnpps.so -> libnpps.so.7.5
lrwxrwxrwx 1 root root        17 Jun 15 19:52 libnpps.so.7.5 -> libnpps.so.7.5.18
-rwxr-xr-x 1 root root   6047400 Aug 15  2015 libnpps.so.7.5.18
-rw-r--r-- 1 root root   8647292 Aug 15  2015 libnpps_static.a
lrwxrwxrwx 1 root root        16 Jun 15 19:52 libnvblas.so -> libnvblas.so.7.5
lrwxrwxrwx 1 root root        19 Jun 15 19:52 libnvblas.so.7.5 -> libnvblas.so.7.5.18
-rwxr-xr-x 1 root root    456112 Aug 15  2015 libnvblas.so.7.5.18
lrwxrwxrwx 1 root root        24 Jun 15 19:52 libnvrtc-builtins.so -> libnvrtc-builtins.so.7.5
lrwxrwxrwx 1 root root        27 Jun 15 19:52 libnvrtc-builtins.so.7.5 -> libnvrtc-builtins.so.7.5.18
-rwxr-xr-x 1 root root  22408512 Aug 15  2015 libnvrtc-builtins.so.7.5.18
lrwxrwxrwx 1 root root        15 Jun 15 19:52 libnvrtc.so -> libnvrtc.so.7.5
lrwxrwxrwx 1 root root        18 Jun 15 19:52 libnvrtc.so.7.5 -> libnvrtc.so.7.5.17
-rwxr-xr-x 1 root root  18199288 Aug 15  2015 libnvrtc.so.7.5.17
lrwxrwxrwx 1 root root        18 Jun 15 19:52 libnvToolsExt.so -> libnvToolsExt.so.1
lrwxrwxrwx 1 root root        22 Jun 15 19:52 libnvToolsExt.so.1 -> libnvToolsExt.so.1.0.0
-rwxr-xr-x 1 root root     37936 Aug 15  2015 libnvToolsExt.so.1.0.0
-rw-r--r-- 1 root root     25840 Aug 15  2015 libOpenCL.so
drwxr-xr-x 2 root root      4096 Jun 15 19:52 stubs

If installed from sources, provide the commit hash:
  r0.9 master

### What have you tried?
1. Transferred the tensorflow repo and the dependency repos to server, modified WORKSPACE and tensorflow/workspace.bzl
2. Built bazel-real from source code and gcc-4.9.0 from source because version of the gcc library with the server isn't compatible. 
3. Manually copied anaconda3 (with python 3.5), 
4. set customized PATH and LD_LIBRARY_PATH to use the new bazel, gcc, python etc.
5. eventually successfully build tutorials_example_trainer without GPU support
         bazel build -c opt //tensorflow/cc:tutorials_example_trainer
   and can run it without use_gpu
         bazel-bin/tensorflow/cc/tutorials_example_trainer 
6. But failed on building tutorials_example_trainer with cuda. Seems need to set PYTHONHOME. but after I didn't that, no change at all.

        bazel build -c opt --config=cuda //tensorflow/cc:tutorials_example_trainer

ERROR: /home/wzhan/.cache/bazel/_bazel_wzhan/c2f4a381d5d3be272ee3353b5d3cb1aa/external/protobuf/BUILD:331:1: Linking of rule '@protobuf//:protoc' failed: crosstool_wrapper_driver_is_not_gcc failed: error executing command
  (cd /home/wzhan/.cache/bazel/_bazel_wzhan/c2f4a381d5d3be272ee3353b5d3cb1aa/execroot/tensorflow && \
  exec env - \
  third_party/gpus/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc -o bazel-out/host/bin/external/protobuf/protoc bazel-out/host/bin/external/protobuf/_objs/protoc/external/protobuf/src/google/protobuf/compiler/main.o bazel-out/host/bin/external/protobuf/libprotoc_lib.a bazel-out/host/bin/external/protobuf/libprotobuf.a bazel-out/host/bin/external/protobuf/libprotobuf_lite.a -lpthread -lstdc++ -B/usr/bin/ -pie -Wl,-z,relro,-z,now -no-canonical-prefixes -pass-exit-codes '-Wl,--build-id=md5' '-Wl,--hash-style=gnu' -Wl,-S -Wl,--gc-sections): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
Could not find platform independent libraries <prefix>
Could not find platform dependent libraries <exec_prefix>
Consider setting $PYTHONHOME to <prefix>[:<exec_prefix>]
ImportError: No module named site
Target //tensorflow/cc:tutorials_example_trainer failed to build
INFO: Elapsed time: 22.901s, Critical Path: 17.57s

7. Failed to build :build_pip_package (without gpu support). It reported different file missed each time 

$ bazel build -c opt //tensorflow/tools/pip_package:build_pip_package
/home/wzhan/.bazel/bin/bazel-real
WARNING: Sandboxed execution is not supported on your system and thus hermeticity of actions cannot be guaranteed. See http://bazel.io/docs/bazel-user-manual.html#sandboxing for more information. You can turn off this warning via --ignore_unsupported_sandboxing.
WARNING: /home/wzhan/.cache/bazel/_bazel_wzhan/c2f4a381d5d3be272ee3353b5d3cb1aa/external/protobuf/WORKSPACE:1: Workspace name in /home/wzhan/.cache/bazel/_bazel_wzhan/c2f4a381d5d3be272ee3353b5d3cb1aa/external/protobuf/WORKSPACE (@__main__) does not match the name given in the repository's definition (@protobuf); this will cause a build error in future versions.
WARNING: /usr/local/tf/tensorflow/util/python/BUILD:11:16: in includes attribute of cc_library rule //util/python:python_headers: 'python_include' resolves to 'util/python/python_include' not in 'third_party'. This will be an error in the future.
WARNING: /home/wzhan/.cache/bazel/_bazel_wzhan/c2f4a381d5d3be272ee3353b5d3cb1aa/external/re2/WORKSPACE:1: Workspace name in /home/wzhan/.cache/bazel/_bazel_wzhan/c2f4a381d5d3be272ee3353b5d3cb1aa/external/re2/WORKSPACE (@__main__) does not match the name given in the repository's definition (@re2); this will cause a build error in future versions.
INFO: Found 1 target...
ERROR: missing input file ## ### **'**@webcomponentsjs//:ShadowDOM.min.js**'.**
ERROR: /usr/local/tf/tensorflow/tensorflow/tools/pip_package/BUILD:23:1: Creating runfiles tree bazel-out/local-py3-opt/bin/tensorflow/tools/pip_package/build_pip_package.runfiles failed: build-runfiles failed: error executing command /home/wzhan/.cache/bazel/_bazel_wzhan/c2f4a381d5d3be272ee3353b5d3cb1aa/execroot/tensorflow/_bin/build-runfiles ... (remaining 2 argument(s) skipped): com.google.devtools.build.lib.shell.AbnormalTerminationException: Process terminated by signal 15.
ERROR: /usr/local/tf/tensorflow/tensorflow/tools/pip_package/BUILD:23:1: //tensorflow/tools/pip_package:build_pip_package: missing input file '@webcomponentsjs//:ShadowDOM.min.js'.
Target //tensorflow/tools/pip_package:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.
ERROR: /usr/local/tf/tensorflow/tensorflow/tools/pip_package/BUILD:23:1 1 input file(s) do not exist.
INFO: Elapsed time: 3.593s, Critical Path: 0.08s

8 build :build_pip_package with GPU support also reports "missing file"

$ bazel build -c opt --config=cuda //tensorflow/tools/pip_package:build_pip_package
/home/wzhan/.bazel/bin/bazel-real
WARNING: Sandboxed execution is not supported on your system and thus hermeticity of actions cannot be guaranteed. See http://bazel.io/docs/bazel-user-manual.html#sandboxing for more information. You can turn off this warning via --ignore_unsupported_sandboxing.
WARNING: /home/wzhan/.cache/bazel/_bazel_wzhan/c2f4a381d5d3be272ee3353b5d3cb1aa/external/protobuf/WORKSPACE:1: Workspace name in /home/wzhan/.cache/bazel/_bazel_wzhan/c2f4a381d5d3be272ee3353b5d3cb1aa/external/protobuf/WORKSPACE (@__main__) does not match the name given in the repository's definition (@protobuf); this will cause a build error in future versions.
WARNING: /usr/local/tf/tensorflow/util/python/BUILD:11:16: in includes attribute of cc_library rule //util/python:python_headers: 'python_include' resolves to 'util/python/python_include' not in 'third_party'. This will be an error in the future.
WARNING: /home/wzhan/.cache/bazel/_bazel_wzhan/c2f4a381d5d3be272ee3353b5d3cb1aa/external/re2/WORKSPACE:1: Workspace name in /home/wzhan/.cache/bazel/_bazel_wzhan/c2f4a381d5d3be272ee3353b5d3cb1aa/external/re2/WORKSPACE (@__main__) does not match the name given in the repository's definition (@re2); this will cause a build error in future versions.
INFO: Found 1 target...
ERROR: missing input file '@grpc//:src/core/lib/support/tmpfile_win32.c'.
ERROR: /home/wzhan/.cache/bazel/_bazel_wzhan/c2f4a381d5d3be272ee3353b5d3cb1aa/external/protobuf/BUILD:71:1: C++ compilation of rule '@protobuf//:protobuf_lite' failed: crosstool_wrapper_driver_is_not_gcc failed: error executing command third_party/gpus/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc -U_FORTIFY_SOURCE '-D_FORTIFY_SOURCE=1' -fstack-protector -fPIE -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object ... (remaining 43 argument(s) skipped): com.google.devtools.build.lib.shell.AbnormalTerminationException: Process terminated by signal 15.
ERROR: /home/wzhan/.cache/bazel/_bazel_wzhan/c2f4a381d5d3be272ee3353b5d3cb1aa/external/grpc/BUILD:38:1: @grpc//:gpr: missing input file '@grpc//:src/core/lib/support/tmpfile_win32.c'.
Target //tensorflow/tools/pip_package:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.
ERROR: /home/wzhan/.cache/bazel/_bazel_wzhan/c2f4a381d5d3be272ee3353b5d3cb1aa/external/grpc/BUILD:38:1 1 input file(s) do not exist.
INFO: Elapsed time: 4.185s, Critical Path: 2.34s

**Comment by zhangwei0119** [comment]
from the error message, it seems python version problem, but the problem still there after I changed a couple of different versions. all version can "import site" correctly when it runs alone

Could not find platform independent libraries <prefix>
Could not find platform dependent libraries <exec_prefix>
Consider setting $PYTHONHOME to <prefix>[:<exec_prefix>]
ImportError: No module named site

**Comment by zhangwei0119** [comment]
After struggling with the installation on the silly "secured" server for two weeks, the team started to discuss switching to torch as it already works. Can anybody please help?

**Comment by martinwicke** [comment]
Which version of bazel have you compiled? We're testing with 0.3 (not head), it would probably be good to rule that out as a source of trouble.

@damienmg can you see something in this?

**Comment by zhangwei0119** [comment]
Release 0.3.0 (2016-06-10), baseline: a9301fa

Is it the correct one?

**Comment by zhangwei0119** [comment]
Building errors keep changing. Now when I execute " bazel build -c opt --config=cuda //tensorflow/cc:tutorials_example_trainer --verbose_failures",  the error messages are:


ERROR: /root/.cache/bazel/_bazel_root/48b0697df5815d95b49fd98c3083955b/external/protobuf/BUILD:331:1: Linking of rule '@protobuf//:protoc' failed: crosstool_wrapper_driver_is_not_gcc failed: error executing command
  (cd /root/.cache/bazel/_bazel_root/48b0697df5815d95b49fd98c3083955b/execroot/tensorflow && \
  exec env - \
  third_party/gpus/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc -o bazel-out/host/bin/external/protobuf/protoc bazel-out/host/bin/external/protobuf/_objs/protoc/external/protobuf/src/google/protobuf/compiler/main.o bazel-out/host/bin/external/protobuf/libprotoc_lib.a bazel-out/host/bin/external/protobuf/libprotobuf.a bazel-out/host/bin/external/protobuf/libprotobuf_lite.a -lpthread -lstdc++ -B/usr/bin/ -pie -Wl,-z,relro,-z,now -no-canonical-prefixes -pass-exit-codes '-Wl,--build-id=md5' '-Wl,--hash-style=gnu' -Wl,-S -Wl,--gc-sections): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
Could not find platform independent libraries <prefix>
Could not find platform dependent libraries <exec_prefix>
Consider setting $PYTHONHOME to <prefix>[:<exec_prefix>]
ImportError: No module named site
Target //tensorflow/cc:tutorials_example_trainer failed to build

## **I manually change to the tmp directory and execute the command, no error at all.**

**Comment by damienmg** [comment]
> Transferred the tensorflow repo and the dependency repos to server, modified WORKSPACE and tensorflow/workspace.bzl

How did you do that?

**Comment by zhangwei0119** [comment]
download the repos from another machine, transferred to the server and modify new_git_repository -> new_local_repository, new_http_archive -> new_local_repository

**Comment by damienmg** [comment]
What does your new workspace.bzl looks like?

Can you try to `bazel build @webcomponentsjs//:ShadowDOM.min.js`?

**Comment by zhangwei0119** [comment]
### workspace.bzl looks like below

def tf_workspace(path_prefix = "", tf_repo_name = ""):
  native.new_local_repository(
    name = "eigen_archive",
    path = "/usr/local/tf/tensorflow/local_repos/eigen-eigen-5f86b31739cd",
    build_file = path_prefix + "eigen.BUILD",
  )

  native.local_repository(
    name = "re2",
    path = "/usr/local/tf/tensorflow/local_repos/re2",
  )

  native.local_repository(
    name = "gemmlowp",
    path = "/usr/local/tf/tensorflow/local_repos/gemmlowp",
  )

  native.new_local_repository(
    name = "farmhash_archive",
    path = "/usr/local/tf/tensorflow/local_repos/farmhash-34c13ddfab0e35422f4c3979f360635a8c050260",
    build_file = path_prefix + "farmhash.BUILD",
  )

### webcomponentjs settings in WORKSPACE

new_local_repository(
  name = "webcomponentsjs",
  build_file = "/usr/local/tf/tensorflow/bower.BUILD",
  path = "/usr/local/tf/tensorflow/local_repos/webcomponentsjs",
)

### ls local_repos/webcomponentsjs/ -l

total 68
-rw-r--r--  1 wzhan root  564 Jun 23 01:17 banner.txt
-rw-r--r--  1 wzhan root  423 Jun 23 01:17 bower.json
-rw-r--r--  1 wzhan root 2507 Jun 23 01:17 CONTRIBUTING.md
-rw-r--r--  1 wzhan root 3781 Jun 23 01:17 gulpfile.js
-rw-r--r--  1 wzhan root 1559 Jun 23 01:17 LICENSE.md
-rw-r--r--  1 wzhan root  737 Jun 23 01:17 package.json
-rw-r--r--  1 wzhan root 9095 Jun 23 01:17 README.md
drwxr-xr-x 11 wzhan root 4096 Jun 23 01:17 src
drwxr-xr-x 10 wzhan root 4096 Jun 23 01:17 tests
-rw-r--r--  1 wzhan root   93 Jun 23 01:17 wct.conf.json
-rw-r--r--  1 wzhan root 2916 Jun 23 01:17 webcomponents.js
-rw-r--r--  1 wzhan root 2167 Jun 23 01:17 webcomponents-lite.js
-rw-r--r--  1 wzhan root 2167 Jun 24 03:26 webcomponents-lite.min.js
-rw-r--r--  1 root  root 2916 Jun 25 15:46 webcomponents.min.js
drwxr-xr-x  2 wzhan root 4096 Jun 23 01:17 workbench

### LOG of bazel build @webcomponentsjs//:ShadowDOM.min.js --verbose_failures

INFO: Found 1 target...
ERROR: missing input file '@webcomponentsjs//:ShadowDOM.min.js'.
ERROR: /root/.cache/bazel/_bazel_root/48b0697df5815d95b49fd98c3083955b/external/webcomponentsjs/BUILD:577:12: @webcomponentsjs//:ShadowDOM.min.js: missing input file '@webcomponentsjs//:ShadowDOM.min.js'.
ERROR: /root/.cache/bazel/_bazel_root/48b0697df5815d95b49fd98c3083955b/external/webcomponentsjs/BUILD:577:12 1 input file(s) do not exist.
INFO: Elapsed time: 1.799s, Critical Path: 0.00s

**Comment by damienmg** [comment]
You cloned the wrong version of webcomponentjs, see https://github.com/webcomponents/webcomponentsjs/tree/v0.7.22 for the good one (you should clone tag the specific tag)

**Comment by martinwicke** [comment]
Thanks Damien. I'm closing this. @zhangwei0119 if you have indications for a bug in TensorFlow, you can comment to reopen.
