### ISSUE TITLE
error C2280: 'tensorflow::FunctionLibraryDefinition &tensorflow::FunctionLibraryDefinition::operator =(const tensorflow::FunctionLibraryDefinition &)': attempting to reference a deleted function

### ISSUE THREAD

**Issue by mayadav1** [tensorflow/tensorflow#30212]
**System information**
- OS Platform :   Windows 10 Pro
- TensorFlow version: 2.99
- Python version: Python 3.6.8 :: Anaconda, Inc.
- Installed using virtualenv: conda
- Bazel version :  0.24.1
- MSVC17
- NO CUDA

configuration : 
Please specify the location of python. [Default is C:\Users\zen2_microsoft\Anaconda3\envs\tensorflow-1.13.1-without-mkl\python.exe]:
Found possible Python library paths:
  C:\Users\zen2_microsoft\Anaconda3\envs\tensorflow-1.13.1-without-mkl\lib\site-packages
Please input the desired Python library path to use.  Default is [C:\Users\zen2_microsoft\Anaconda3\envs\tensorflow-1.13.1-without-mkl\lib\site-packages]
Do you wish to build TensorFlow with XLA JIT support? [y/N]: N
No XLA JIT support will be enabled for TensorFlow.
Do you wish to build TensorFlow with ROCm support? [y/N]: N
No ROCm support will be enabled for TensorFlow.
Do you wish to build TensorFlow with CUDA support? [y/N]: N
No CUDA support will be enabled for TensorFlow.
Please specify optimization flags to use during compilation when bazel option "--config=opt" is specified [Default is /arch:AVX]:
Would you like to override eigen strong inline for some C++ compilation to reduce the compilation time? [Y/n]: N

**Describe the problem**
Build fails with below error .
compilation error log :

  C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.12.25827/bin/HostX64/x64/cl.exe /nologo /DCOMPILER_MSVC /DNOMINMAX /D_WIN32_WINNT=0x0601 /D_CRT_SECURE_NO_DEPRECATE /D_CRT_SECURE_NO_WARNINGS /bigobj /Zm500 /EHsc /wd4351 /wd4291 /wd4250 /wd4996 /I. /Ibazel-out/x64_windows-opt/genfiles /Ibazel-out/x64_windows-opt/bin /Iexternal/com_google_absl /Ibazel-out/x64_windows-opt/genfiles/external/com_google_absl /Ibazel-out/x64_windows-opt/bin/external/com_google_absl /Iexternal/eigen_archive /Ibazel-out/x64_windows-opt/genfiles/external/eigen_archive /Ibazel-out/x64_windows-opt/bin/external/eigen_archive /Iexternal/local_config_sycl /Ibazel-out/x64_windows-opt/genfiles/external/local_config_sycl /Ibazel-out/x64_windows-opt/bin/external/local_config_sycl /Iexternal/nsync /Ibazel-out/x64_windows-opt/genfiles/external/nsync /Ibazel-out/x64_windows-opt/bin/external/nsync /Iexternal/gif_archive /Ibazel-out/x64_windows-opt/genfiles/external/gif_archive /Ibazel-out/x64_windows-opt/bin/external/gif_archive /Iexternal/jpeg /Ibazel-out/x64_windows-opt/genfiles/external/jpeg /Ibazel-out/x64_windows-opt/bin/external/jpeg /Iexternal/com_google_protobuf /Ibazel-out/x64_windows-opt/genfiles/external/com_google_protobuf /Ibazel-out/x64_windows-opt/bin/external/com_google_protobuf /Iexternal/com_googlesource_code_re2 /Ibazel-out/x64_windows-opt/genfiles/external/com_googlesource_code_re2 /Ibazel-out/x64_windows-opt/bin/external/com_googlesource_code_re2 /Iexternal/farmhash_archive /Ibazel-out/x64_windows-opt/genfiles/external/farmhash_archive /Ibazel-out/x64_windows-opt/bin/external/farmhash_archive /Iexternal/fft2d /Ibazel-out/x64_windows-opt/genfiles/external/fft2d /Ibazel-out/x64_windows-opt/bin/external/fft2d /Iexternal/highwayhash /Ibazel-out/x64_windows-opt/genfiles/external/highwayhash /Ibazel-out/x64_windows-opt/bin/external/highwayhash /Iexternal/zlib_archive /Ibazel-out/x64_windows-opt/genfiles/external/zlib_archive /Ibazel-out/x64_windows-opt/bin/external/zlib_archive /Iexternal/double_conversion /Ibazel-out/x64_windows-opt/genfiles/external/double_conversion /Ibazel-out/x64_windows-opt/bin/external/double_conversion /Iexternal/snappy /Ibazel-out/x64_windows-opt/genfiles/external/snappy /Ibazel-out/x64_windows-opt/bin/external/snappy /Iexternal/eigen_archive /Ibazel-out/x64_windows-opt/genfiles/external/eigen_archive /Ibazel-out/x64_windows-opt/bin/external/eigen_archive /Iexternal/nsync/public /Ibazel-out/x64_windows-opt/genfiles/external/nsync/public /Ibazel-out/x64_windows-opt/bin/external/nsync/public /Iexternal/gif_archive/lib /Ibazel-out/x64_windows-opt/genfiles/external/gif_archive/lib /Ibazel-out/x64_windows-opt/bin/external/gif_archive/lib /Iexternal/gif_archive/windows /Ibazel-out/x64_windows-opt/genfiles/external/gif_archive/windows /Ibazel-out/x64_windows-opt/bin/external/gif_archive/windows /Iexternal/com_google_protobuf/src /Ibazel-out/x64_windows-opt/genfiles/external/com_google_protobuf/src /Ibazel-out/x64_windows-opt/bin/external/com_google_protobuf/src /Iexternal/farmhash_archive/src /Ibazel-out/x64_windows-opt/genfiles/external/farmhash_archive/src /Ibazel-out/x64_windows-opt/bin/external/farmhash_archive/src /Iexternal/zlib_archive /Ibazel-out/x64_windows-opt/genfiles/external/zlib_archive /Ibazel-out/x64_windows-opt/bin/external/zlib_archive /Iexternal/double_conversion /Ibazel-out/x64_windows-opt/genfiles/external/double_conversion /Ibazel-out/x64_windows-opt/bin/external/double_conversion /D__CLANG_SUPPORT_DYN_ANNOTATION__ /DEIGEN_MPL2_ONLY /DEIGEN_MAX_ALIGN_BYTES=64 /DEIGEN_HAS_TYPE_TRAITS=0 /DTF_USE_SNAPPY /showIncludes /MD /O2 /Oy- /DNDEBUG /wd4117 -D__DATE__="redacted" -D__TIMESTAMP__="redacted" -D__TIME__="redacted" /Gy /Gw -w -DWIN32_LEAN_AND_MEAN -DNOGDI /arch:AVX /Fobazel-out/x64_windows-opt/bin/tensorflow/core/grappler/_objs/grappler_item/grappler_item.obj /c tensorflow/core/grappler/grappler_item.cc
Execution platform: @bazel_tools//platforms:host_platform
external/com_google_absl\absl/meta/type_traits.h(141): error C2280: 'tensorflow::FunctionLibraryDefinition &tensorflow::FunctionLibraryDefinition::operator =(const tensorflow::FunctionLibraryDefinition &)': attempting to reference a deleted function
.\tensorflow/core/framework/function.h(334): note: see declaration of 'tensorflow::FunctionLibraryDefinition::operator ='
external/com_google_absl\absl/meta/type_traits.h(121): note: see reference to alias template instantiation 'IsCopyAssignableImpl<tensorflow::FunctionLibraryDefinition>' being compiled
external/com_google_absl\absl/meta/type_traits.h(150): note: see reference to class template instantiation 'absl::type_traits_internal::is_detected<absl::type_traits_internal::IsCopyAssignableImpl,T>' being compiled
        with
        [
            T=tensorflow::FunctionLibraryDefinition
        ]
external/com_google_absl\absl/meta/type_traits.h(432): note: see reference to class template instantiation 'absl::is_copy_assignable<T>' being compiled
        with
        [
            T=tensorflow::FunctionLibraryDefinition
        ]
external/com_google_absl\absl/types/internal/optional.h(173): note: see reference to class template instantiation 'absl::is_trivially_copy_assignable<tensorflow::FunctionLibraryDefinition>' being compiled
tensorflow/core/grappler/grappler_item.cc(118): note: see reference to class template instantiation 'absl::optional<tensorflow::FunctionLibraryDefinition>' being compiled
.\tensorflow/core/framework/function.h(334): note: 'tensorflow::FunctionLibraryDefinition &tensorflow::FunctionLibraryDefinition::operator =(const tensorflow::FunctionLibraryDefinition &)': function was explicitly deleted
external/com_google_absl\absl/meta/type_traits.h(144): error C2280: 'tensorflow::FunctionLibraryDefinition &tensorflow::FunctionLibraryDefinition::operator =(const tensorflow::FunctionLibraryDefinition &)': attempting to reference a deleted function
.\tensorflow/core/framework/function.h(334): note: see declaration of 'tensorflow::FunctionLibraryDefinition::operator ='
external/com_google_absl\absl/meta/type_traits.h(121): note: see reference to alias template instantiation 'IsMoveAssignableImpl<tensorflow::FunctionLibraryDefinition>' being compiled
external/com_google_absl\absl/meta/type_traits.h(155): note: see reference to class template instantiation 'absl::type_traits_internal::is_detected<absl::type_traits_internal::IsMoveAssignableImpl,T>' being compiled
        with
        [
            T=tensorflow::FunctionLibraryDefinition
        ]
external/com_google_absl\absl/types/internal/optional.h(328): note: see reference to class template instantiation 'absl::is_move_assignable<T>' being compiled
        with
        [
            T=tensorflow::FunctionLibraryDefinition
        ]
external/com_google_absl\absl/types/optional.h(120): note: see reference to class template instantiation 'absl::optional_internal::assign_copy_traits<T>' being compiled
        with
        [
            T=tensorflow::FunctionLibraryDefinition
        ]
.\tensorflow/core/framework/function.h(334): note: 'tensorflow::FunctionLibraryDefinition &tensorflow::FunctionLibraryDefinition::operator =(const tensorflow::FunctionLibraryDefinition &)': function was explicitly deleted
Target //tensorflow/tools/pip_package:build_pip_package failed to build
INFO: Elapsed time: 11024.399s, Critical Path: 6294.48s
INFO: 2398 processes: 2398 local.
FAILED: Build did NOT complete successfully 

Please help me out .

**Comment by ravikyram** [comment]
Just to verify did you get chance to follow instructions from [Tensorflow Website](https://www.tensorflow.org/install/source_windows).Thanks!

**Comment by mayadav1** [comment]
@ravikyram 
Yes I have followed below instructions:
1) conda create -n tensorflow-1.13.1-without-mkl python=3.6 anaconda
2)conda activate tensorflow-1.13.1-without-mkl
3)Install MSYS2
 set environmental variable, under PATH -> C:\msys64\usr\bin
4)Install JDK12 and set environmental variable : JAVA_HOME = C:\Program Files\Java\jdk-12
5)pacman -Syu zip unzip
6)pacman -Syuu --noconfirm patch
7)set BAZEL_VC=C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC
8) set BAZEL_SH=C:\msys64\usr\bin\bash.exe
9) git clone https://github.com/tensorflow/tensorflow.git -b r2.99
10) python ./configure.py
11) bazel build --config=opt //tensorflow/tools/pip_package:build_pip_package
Please correct me in case i am wrong.

**Comment by gunan** [comment]
I think 2.99 is just an experimental branch.
It is possible that it is simply broken.
Could you try 2.0 or 1.4?

**Comment by mayadav1** [comment]
@gunan 
Issue with r1.3  #30599

**Comment by stewart-r** [comment]
Just to confirm I am also seeing this on `2.0` and current master (commit `sha:1ba28ea0022ce67bd5286cc8c30d7cb5fc7f7bad` ).

I see it on one windows machine but not another with exactly the same code, bazel version, etc. :-/ 

Trying to pin down what the difference between these two is but, so far, without success.

**Comment by smistad** [comment]
I am also getting this error on 1.14 using MSVC 2017 and bazel 0.24.1

**Comment by smistad** [comment]
I was able to get around this error by upgrading the Visual Studio 2017 Build Tools and Community IDE to the latest version 15.9.14. Maybe someone can verify if this is a valid fix, for instance @stewart-r ?

**Comment by ivafanas** [comment]
The same problem (tensorflow 1.14.0, MSVC 2017 (15.19.18), bazel 0.24.1)

Seems like a problem in `absl::optional` implementation that might require copy assignment operator for the underlying type but it shouldn't.

I've made a local fast fix with replacement of `absl::optional` to `unique_ptr` [patch](https://github.com/tensorflow/tensorflow/files/3983191/patch_tf_fn_lib_no_copy_assign.txt) and it compiles nice.

Better fix would be to reuse `std::optional` and I have no idea why tensorflow developers didn't (maybe obsolete code when `std::optional` was not available in C++ stdlib).

**Comment by ListsOfArrays** [comment]
std::optional wasn't supported in MSVC 2015 as far as I can tell, meaning the absl or boost one had to be used instead of the std library one (https://devblogs.microsoft.com/cppblog/stdoptional-how-when-and-why/). I'm trying your patch on MSVC 2019, and I have a feeling it's going to work. I wonder if we should patch absl, or if tensorflow is going to transition away from MSVC 2015 at some point soon. 2017 is officially supported so something broke here probably recently. :D

**Comment by gunan** [comment]
Thank you very much for debugging!
On our side, TF recently moved the official builds to MSVC 2019, that may be why we missed the issue.

We try to use STL as much as possible due to various reasons, some performance, some know issues with interoperability with eigen, etc. So using std::optional may not be OK for us.
We can look into patching absl, as it looks like MSVC 2017 users are also reporting issues.
