### ISSUE TITLE
tensorflow:libtensorflow_cc.so fails to build for --cpu=armeabi-v7a

### ISSUE THREAD

**Issue by flamxi** [tensorflow/tensorflow#30226]
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: Yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 18.04.3
- **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device**:
- **TensorFlow installed from (source or binary)**: source
- **TensorFlow version (use command below)**: current master branch(28.06.2019)
- **Python version**: 3.6
- **Bazel version (if compiling from source)**: 0.24.1
- **GCC/Compiler version (if compiling from source)**:7.4.0 
- **CUDA/cuDNN version**:Not Used
- **GPU model and memory**:
- **Exact command to reproduce**:
bazel build -c opt //tensorflow:libtensorflow_cc.so --crosstool_top=//external:android/crosstool --host_crosstool_top=@bazel_tools//tools/cpp:toolchain --cpu=armeabi-v7a --verbose_failures --cxxopt="-DTENSROFLOW_DISABLE_META" --jobs 8 --copt="-funsafe-math-optimizations" --copt="-ftree-vectorize" --copt="-fomit-frame-pointer" --copt=-DNO_LOCAL_MEM --copt=-DEIGEN_DONT_VECTORIZE_SYCL --copt=-DMDB_USE_ROBUST=0 --cxxopt="-fPIC" --cxxopt="-std=c++11"

### Describe the problem
Trying to compile //tensorflow:libtensorflow_cc.so for armeabi-v7a and/or for arm64-v8a, both failing with the output:
**ERROR: ../tensorflow/tensorflow/cc/saved_model/BUILD:40:1: no such target '//tensorflow/core:saved_model_portable_proto': target 'saved_model_portable_proto' not declared in package 'tensorflow/core' defined by ../tensorflow/tensorflow/core/BUILD and referenced by '//tensorflow/cc/saved_model:reader**

**Comment by jdduke** [comment]
TensorFlow (Mobile) for Android is deprecated. Is there a reason you cannot use TensorFlow Lite?

**Comment by flamxi** [comment]
@jdduke thanks for replying.
I am fairly new to Tensorflow, and I am using it with C++ API, and since the tensorflow has more ops, I need to use it instead of the Lite.

**Comment by flamxi** [comment]
@jdduke do we have any news in this !!!

**Comment by jdduke** [comment]
You can use certain whitelisted TensorFlow operators from TensorFlow Lite using [this approach](https://www.tensorflow.org/lite/guide/ops_select). The [label_image](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/examples/label_image/label_image.cc#L157) example shows how to use the C++ API.
