### ISSUE TITLE
May need more packages in Anaconda 2019.3 in win 10 1903

### ISSUE THREAD

**Issue by swun90** [tensorflow/tensorflow#30224]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): **Windows 10 64-bit 1903**
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: No
- TensorFlow installed from (source or binary): `.whl`
- TensorFlow version: **1.14.0**
- Python version: **3.7.3 (from Anaconda 2019.3)**
- Installed using virtualenv? pip? conda?: **pip**
- Bazel version (if compiling from source): no
- GCC/Compiler version (if compiling from source): no
- CUDA/cuDNN version: no
- GPU model and memory: no GPU (Intel® UHD Graphics 630)

**Describe the problem**

I need to install tensorflow in an offline environment. So I installed Anaconda 2019.3. And downloaded tensorflow .whl file (`tensorflow-1.14.0-cp37-cp37m-win_amd64.whl`). As the `tensorflow/tools/pip_package/setup.py ` file said, other packages were needed. Here I quote,
```
REQUIRED_PACKAGES = [
    'absl-py >= 0.7.0',
    'astor >= 0.6.0',
    'gast >= 0.2.0',
    'google_pasta >= 0.1.6',
    'keras_applications >= 1.0.8',
    'keras_preprocessing >= 1.0.5',
    'numpy >= 1.14.5, < 2.0',
    'opt_einsum >= 2.3.2',
    'six >= 1.10.0',
    'protobuf >= 3.6.1',
    'tensorboard >= 1.14.0, < 1.15.0',
    'tensorflow_estimator >= 1.14.0rc0, < 1.15.0rc0',
    'termcolor >= 1.1.0',
    'wrapt >= 1.11.1',
]
```
But actually, this list was not enough.
`markdown >= 2.6.8` was required by `tensorboard == 1.14.0`. 
`grpcio >= 1.8.6` was required by `tensorflow == 1.14.0`.
And, `setuptools >= 41.0.0` was required by `tensorflow == 1.14.0`, since `setuptools == 40.8.0` in Anaconda 2019.3.

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by ravikyram** [comment]
Can you please help us with error log for faster resolution.Thanks!

**Comment by swun90** [comment]
Not sure about the error log. The `pip install <pkg.whl>` command gave the error messages that other packages were required. I downloaded and installed the required packages, then tensorflow and tensorboard could be installed.

To make the issue short, the `REQUIRED_PACKAGES` listed might not be enough. `markdown >= 2.6.8`, `grpcio >= 1.8.6` are required.

**Comment by ravikyram** [comment]
Just to verify did you get chance to follow instructions from [Tensorflow Website](https://www.tensorflow.org/install/pip).Thanks!

**Comment by swun90** [comment]
Here's my installation steps
1. Install Anaconda 2019.3(python 3). Download all the packages from Tensorflow website and https://pypi.org/
2. `pip install <pkg.whl>` or `cd <pkg>; python setup.py install`  depending on whether the package has wheel installer or not.
3. `pip install tensorflow-1.12.0-cp36-cp36m-win_amd64.whl`

**Comment by swun90** [comment]
And, after the latest versions of `markdown`, `grpcio` and `setuptools` installed, tensorflow was installed successfully in my computer. I have ran a simple case using tensorflow.

**Comment by ravikyram** [comment]
@swun90 Can i close this issue as your issue was resolved.Thanks!
