### ISSUE TITLE
Tensorflow Lite conversion misshapes bias vector of FullyConnected

### ISSUE THREAD

**Issue by dukecyto** [tensorflow/tensorflow#30232]
**System information**
- Have I written custom code: tflite converter code is straight from an example script
- OS Platform and Distribution: Mac OS 10.14.5
- TensorFlow installed from: `pip install tf-nightly` and `pip install tensorflow`
- TensorFlow version:
tested on  `v1.12.1-5178-gbafa0371c8 1.15.0-dev20190628` and `v1.13.0-rc2-5-g6612da8951 1.13.1`
- Python version: 3.6.5

**Describe the current behavior**
TFLite converter incorrectly shapes the bias for FullyConnected operators.
Specifically in my test case (see attached model below), in the original freeze graph model, `MatMul_6` takes a product of 32x12 matrix and 12x1 vector then `add_7` adds a 32x1 vector to it as a bias. The converted TFLite model puts these two operations together into a FullyConnected op, and somehow its bias `MatMul_6_bias` is incorrectly shaped as a single-element vector. Consequently, the inference result of this TFLite model is incorrect.

**Describe the expected behavior**
The bias vectors should be shaped as they were in the original freeze graph model.

**Code to reproduce the issue**
[tflite_bias_shape_issue.zip](https://github.com/tensorflow/tensorflow/files/3340234/tflite_bias_shape_issue.zip)
This zip file contains debug.pb (TF freeze graph model) and debug.tflite (TFLite converted model from frozen model). The conversion code is taken straight from the document:
```
import tensorflow as tf
graph_def_file = "debug.pb"
input_arrays = ["input"]
output_arrays = ["Reshape_1"]
converter = tf.lite.TFLiteConverter.from_frozen_graph(graph_def_file, input_arrays, output_arrays)
tflite_model = converter.convert()
open("debug.tflite", "wb").write(tflite_model)
```
The model has extra operators in the beginning (Sub, Div, Gather) just because I did not have time to rebuild the bare minimal test case but I think it is already simple enough.

**Comment by dukecyto** [comment]
[fc_op.zip](https://github.com/tensorflow/tensorflow/files/3340595/fc_op.zip)
OK here is the bare minimal case. It's just MatMul then Add, which TFLite converts to FullyConnected with an incorrect bias shape.

**Comment by dukecyto** [comment]
Any words on this issue? This seems like a grave issue without any workaround. I tried many things like adding extra ops or dimensions but the converter stubbornly insists on optimizing everything to a simple FullyConnected op with an incorrect, single-element bias.

**Comment by ANSHUMAN87** [comment]
@dukecyto : I have checked into the fc_op model you shared. The output shape is (32, 1), is it not the expected one? Sorry if i misinterpreted your issue.

**Comment by dukecyto** [comment]
@ANSHUMAN87 Please use a visualization tool such as Netron and have a look at both `fc_op.pb` and `fc_op.tflite`. In the FullyConnected op of `fc_op.tflite`, The shape of the "bias" input is chopped off to a single-element vector. I do not think this is a visualization problem because the network actually evaluates to an incorrect value.

**Comment by ANSHUMAN87** [comment]
@dukecyto : Thanks for your detailed reply. I got your issue clearly now. I will work on it, and share solution for it. Please stay tuned. Thanks!

**Comment by ANSHUMAN87** [comment]
@dukecyto : I have found the reason for the issue. I will upload a PR to fix it. In the mean time, i can give you work around for the issue.
Currently your model has operation like, Weight[32x12] X Input[12, 1], followed by BiasAdd(Add) [32x1].

I would suggest to change the order as below, Input[1, 12] X Weight[12x32], followed by BiasAdd(Add)[1x32], and then you can add Transpose to fulfill your expected shape for next layer.

I hope it will solve your blocking issue. Please let me know your results, Thanks!

**Comment by dukecyto** [comment]
@ANSHUMAN87 This sound like great news! I while I wait for your PR to get merged, I will try your suggested workaround.

**Comment by dukecyto** [comment]
@ANSHUMAN87 The suggested workaround is confirmed to work with my complete model, generating expected inference results. All extra transposes are optimized out in the final TFLite compute graph but is messy in the code and is a major pitfall in using TFLite so I still look forward to your PR getting merged.

**Comment by gargn** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Comment by dukecyto** [comment]
@gargn er, isn't it more like Tensorflow team updates ME on the progress?

**Comment by gargn** [comment]
@ANSHUMAN87 Do you have an update on your PR?

**Comment by ANSHUMAN87** [comment]
@dukecyto, @gargn : i am extremely sorry, could not upload the PR yet, please give me some time(may be next week), will inform you about the progress. Thanks!

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this issue, as you are using an older version of tensorflow(1.x) which is officially considered as end of life. We recommend that you upgrade to 2.4 or later version and let us know if the issue still persists in newer versions. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, Please open a new issue for any help you need against 2.x, and we will get you the right help.
