### ISSUE TITLE
`xla.compile` + `tf.function` lose information about compile-time constants

### ISSUE THREAD

**Issue by mdanatg** [tensorflow/tensorflow#30235]
**System information**
- TensorFlow version (use command below): 1.14

**Describe the current behavior**

In Eager mode, when a function is compiled with `xla.compile`, any constant arguments are auto-cast to Tensors, but these Tensors don't appear to reflect the fact that they are constant. Certain ops, like `tf.range` are sensitive to constant inputs due to the need for static shapes.

In effect, the following code raises an error:

```
import tensorflow as tf

tf.enable_eager_execution()

@tf.function
def bad(count):
  return tf.range(count)

xla.compile(bad, (3,))
```
```
InvalidArgumentError: Argument to function must be a compile-time constant, but unable to resolve argument value to a constant.
	This error might be occurring with the use of xla.compile. If it is not necessary that every Op be compiled with XLA, an alternative is to use auto_jit with OptimizerOptions.global_jit_level = ON_2 or the environment variable TF_XLA_FLAGS="tf_xla_auto_jit=2" which will attempt to use xla to compile as much of the graph as the compiler is able to.
	 [[{{node cluster}}]] [Op:__inference_xla_compile_wrapper_196]
```

Whereas this code works:

```
import tensorflow as tf

tf.enable_eager_execution()

@tf.function
def good():
  return tf.range(3)

xla.compile(good, ())
```
```
[<tf.Tensor: id=157, shape=(3,), dtype=int32, numpy=array([0, 1, 2], dtype=int32)>]
```

**Describe the expected behavior**

The two snippets of code above should be equivalent, that is, they should both run successfully.

**Comment by ymodak** [comment]
@sanjoy Can you please take a look? Thanks!

**Comment by sanjoy** [comment]
CC @alextp @joker-eph 

I think this will be tricky to fix given what little I understand about `tf.function` and python decorators.  Moreover, I'm especially worried that this will lead to a slippery slope where users will expect `xla.compile(bad, (2+1,))`, `xla.compile(bad, (5-x+x,))` etc. to also work.

I understand that the UX here is not ideal, but is this blocking you in some way?

**Comment by sushreebarsa** [comment]
Hi There,

We are checking to see if you still need help on this issue, as you are using an older version of tensorflow(1.x) which is officially considered as end of life. We recommend that you upgrade to 2.4 or later version and let us know if the issue still persists in newer versions.we will get you the right help.Thanks!

**Comment by mdanatg** [comment]
It seems stale - closing.
