### ISSUE TITLE
.tflite converted model (from .h5 file) not working as expected

### ISSUE THREAD

**Issue by prat96** [tensorflow/tensorflow#30249]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes, custom model to count fingers, but the TFLite converter code is same as example scripts provided in API docs.
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04 LTS
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: All android devices using TFlite example app (replaced the sample models with my custom tflite model)
- TensorFlow installed from (source or binary): pip installed tensorflow-gpu AND tf-nightly-gpu
- TensorFlow version (use command below): Tried on 1.14, 1.13, 1.14-nightly, 2.0.0-beta1
- Python version: 3.6.7
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: Cuda 10.0
- GPU model and memory: GTX 1060 6GB

**Describe the current behavior**
I've trained a simple CNN to count number of fingers held up. The model works really well (~99% accuracy on test images). Now, I'm trying to deploy this model on the edge by converting the saved model (.h5 file) to a .tflite file.

Using tf.lite.TFLiteConverter.from_keras_model_file(), it converts and gives me a .tflite file with this error:
`tensorflow/core/grappler/grappler_item_builder.cc:637] Init node conv2d/kernel/Assign doesn't exist in graph`

Now, when I load this tflite file and try to make predictions on the same input images, it always predicts 'ZERO' which is the first class label and with probability = 0.003922. The rest of the classes are always 0.00, I get the same results when loading my tflite model in the Android Image classification example app from Tensorflow repo's.

**Describe the expected behavior**
I expect my .tflite model to behave the same as my Tensorflow .h5 model. But it always predicts 
the first class label with the same probability score. 
I've tried converting to .tflite with TF-gpu versions 1.14, 1.13, nightly 1.14 and TF-2.0.0-beta1
**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.
**My custom model:**
```
redacted
```

**Code I used to convert to .tflite:** 

```
import tensorflow as tf

converter = tf.lite.TFLiteConverter.from_keras_model_file("fingers_latest.h5")
tflite_model = converter.convert()
open("fingers_latest.tflite", "wb").write(tflite_model)
```

**Code to load and test the .tflite model:**

```
import tensorflow as tf
import tkinter as tk
from tkinter import filedialog
import PIL
from PIL import Image
import numpy as np
import time

# DEF. PARAMETERS
img_row, img_column = 256, 256
num_channel = 3
num_batch = 1
input_mean = 0
input_std = 255
floating_model = False

path_1 = r"./models/fingers_latest.tflite"
labels_path = "./models/labels.txt"

def load_labels(filename):
    my_labels = []
    input_file = open(filename, 'r')
    for l in input_file:
        my_labels.append(l.strip())
    return my_labels

interpreter = tf.lite.Interpreter(path_1)
interpreter.allocate_tensors()

# obtaining the input-output shapes and types
input_details = interpreter.get_input_details()
output_details = interpreter.get_output_details()
print(input_details, '\n', output_details)

# file selection window for input selection
root = tk.Tk()
root.withdraw()
file_path = filedialog.askopenfilename()
input_img = Image.open(file_path)
input_img = input_img.resize((img_row, img_column))
input_img = np.expand_dims(input_img, axis=0)

input_img = (np.float32(input_img) - input_mean) / input_std

interpreter.set_tensor(input_details[0]['index'], input_img)

# running inference
interpreter.invoke()

output_data = interpreter.get_tensor(output_details[0]['index'])
results = np.squeeze(output_data)

top_k = results.argsort()[-5:][::-1]
labels = load_labels(labels_path)
for i in top_k:
    print('{0:08.6f}'.format(float(results[i] / 255.0)) + ":", labels[i]) 
```

Why does this tflite model not work as expected? Am I missing something during the conversion or using operations that aren't supported in TFlite? Please help!

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

[My .h5 model and a test file, if you would like to try it yourself](https://drive.google.com/drive/folders/1_jiRqHgRUyV5YBNcDPKPtZMGjUpkf8sC)

**Comment by prat96** [comment]
Solved the issue, closing it.

**Comment by git-hamza** [comment]
Can you please post your solution as well, i am facing the same problem.
