### ISSUE TITLE
TPU Outfeed Dequeue Many

### ISSUE THREAD

**Issue by aidangomez** [tensorflow/tensorflow#30252]
I have an application that is bottlenecked by waiting for elements to be dequeued from the TPU. Is there any way to dequeue many from the outfeed in a single operation?

Right now my program runs two threads in parallel:
  1. a computation followed by an outfeed_enqueue
  2. a outfeed_dequeue that collects elements from the outfeed and acts on them

for Thread 1. I can execute the op ~30 times for every dequeue in Thread 2. So ideally, I'd like to dequeue the 30 batches that are sitting in my outfeed queue instead of a single batch at a time. Is there a way to do this?

I'm running TF 1.13 (although I'm sure TF 1.14 would be fine too).

**Comment by gadagashwini** [comment]
@aidangomez Please have look at [TPU parallel execution](https://www.tensorflow.org/api_docs/python/tf/tpu/shard). Please let us know if that helps. Thanks!
