### ISSUE TITLE
including human ethics inside tensorflow as tf.ethics

### ISSUE THREAD

**Issue by hasansaikat** [tensorflow/tensorflow#30259]
wouldn't it be great to integrate ethics inside tensorflow.like when a baby is born,they get in touch with social norms.as they start to grow up their brain based on social norms/ethics start to react.based on previous norms new norms start to kick off inside brain.

by the way human ethics has an evolution timeline like the biological evolution.it is changing.

**Comment by gadagashwini** [comment]
This is not Build/Installation or Bug/Performance issue. Please post this kind of support questions at [StackOverflow](http://stackoverflow.com/questions/tagged//tensorflow). There is a big community to support and learn from your questions. GitHub is mainly for addressing bugs in installation and performance. Thanks!
