### ISSUE TITLE
Problem Passing Tensor Attr to Custom Op in Eager Execution Mode

### ISSUE THREAD

**Issue by oracle3001** [tensorflow/tensorflow#30253]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Windows 10:
- TensorFlow installed from binary:
- TensorFlow version 1.14:
- Python version 3.7:
- CUDA/cuDNN version 10:

I am defining a new custom Op in C++, which takes in a single attribute of type tensor and a single input tensor variable. A stripped version of the Op code is below:

    #include "tensorflow/core/framework/op.h"
    #include "tensorflow/core/framework/op_kernel.h"
    
    using namespace tensorflow;
    
    REGISTER_OP("DoStuff")
        .Attr("attr: tensor = { dtype: DT_FLOAT }")
        .Input("in: float")
        .Output("out: float");
    
    class DoStuffOp : public OpKernel {
    public:
        explicit DoStuffOp(OpKernelConstruction *context) : OpKernel(context) {
            OP_REQUIRES_OK(context, context->GetAttr("attr", &attr_));
            // ...
        }
    
        void Compute(OpKernelContext *context) override {
            // ...
        }
    
    private:
        Tensor attr_;
    };
    
    REGISTER_KERNEL_BUILDER(Name("DoStuff").Device(DEVICE_CPU), DoStuffOp);

I can compile the Op into a .so file fine. Now, the following code runs.

    import tensorflow as tf
    dostufflib = tf.load_op_library('build/do_stuff.so')
    sess = tf.InteractiveSession() 

    sample_in = np.random.rand(3,3)
    sample_in_t = tf.convert_to_tensor(sample_in, dtype=np.float32)
    sample_atrr = np.zeros([3,3], dtype=np.float32)
    sample_attr_t = tf.contrib.util.make_tensor_proto(sample_atrr)

    Y = dostufflib.do_stuff(in=sample_in_t, attr=sample_attr_t)

However, if I try to use eager execution mode i.e.

    import tensorflow as tf
    tf.compat.v1.enable_eager_execution()
    dostufflib = tf.load_op_library('build/do_stuff.so')
    
    sample_in = np.random.rand(3,3)
    sample_in_t = tf.convert_to_tensor(sample_in, dtype=np.float32)
    sample_atrr = np.zeros([3,3], dtype=np.float32)
    sample_attr_t = tf.contrib.util.make_tensor_proto(sample_atrr)
    
    Y = dostufflib.do_stuff(in=sample_in_t, attr=sample_attr_t)

I get the following error,

    tensorflow.python.framework.errors_impl.UnimplementedError: Attr sample_locs has unhandled type 6

**Comment by Blade6570** [comment]
facing the similar issue and the error message is 
AttributeError: Tensor.op is meaningless when eager execution is enabled.

**Comment by oracle3001** [comment]
This is also a problem in TF 2.x.x

**Comment by josh11b** [comment]
It is possible that the Eager execution runtime does not support tensor attrs. In general, though, you should never use an attr for values that can be an input. So attrs should be used for things that affect the signature like number or type of inputs or outputs. The main reason for Tensor attrs in the first place was for the Const op, which is handled in a different way in eager execution.

**Comment by dtarakanov1** [comment]
> It is possible that the Eager execution runtime does not support tensor attrs.

Indeed and this is true for TF2.0:

https://github.com/tensorflow/tensorflow/blob/1c83755e5a1269b528042e6d318d66e363ffc349/tensorflow/python/eager/pywrap_tfe_src.cc#L412

It's a shame because, having eager execution the default option for TF2.0, it's not even possible to use e.g. `tf.compat.v1.summary.image()` :
```
tensorflow.python.framework.errors_impl.UnimplementedError: Attr bad_color has unhandled type 6 [Op:ImageSummary] name: input_image
```

**Comment by jaingaurav** [comment]
Thanks for digging up the code @dtarakanov1. Regarding the image summary, you should be able to use `tf.compat.v2.summary.image` which should be compatible with Eager mode execution.

As @josh11b has mentioned, it seems like using a tensor attr is recommended. Instead, the tensor should be an input.

Thus, I am closing the issue, but please feel free to re-open if need to support tensor attributes in eager mode is necessary.

**Comment by dtarakanov1** [comment]
Please don't close the issue. My question differs from the original problem a bit.

**Comment by jaingaurav** [comment]
dtarakanov1@: I agree that your need to use image summaries differs slightly. However, isn't the recommendation for the original issue to use tensors as an input vs an attribute?
