### ISSUE TITLE
python 3.5 mnist implementation error

### ISSUE THREAD

**Issue by gnujimmik** [tensorflow/tensorflow#3025]
GitHub issues are for bugs / installation problems / feature requests.  
For general support from the community, see [StackOverflow](https://stackoverflow.com/questions/tagged/tensorflow).
To make bugs and feature requests more easy to find and organize, we close issues that are deemed
out of scope for GitHub Issues and point people to StackOverflow.

For bugs or installation issues, please provide the following information.
The more information you provide, the more easily we will be able to offer
help and advice.

### Environment info
Operating System: ubuntu 16.04 / 14.04

Installed version of CUDA and cuDNN: NA
(please attach the output of `ls -l /path/to/cuda/lib/libcud*`):

If installed from binary pip package, provide: NA

1. Which pip package you installed.
2. The output from `python -c "import tensorflow; print(tensorflow.__version__)"`. 0.8.0
If installed from sources, provide the commit hash:

### Steps to reproduce
1. Just implemented the mnist code provided by tensorflow. 
2.
3.

### What have you tried?
1. While starting training, I have got an error as below. I have tried with ubuntu 14.04 and ubuntu 16.04, tensorflow 0.8 and tensorflow 0.9, both had the same error. However, when I tried it with python 2.7, it worked. Now with python 3.5, not working.

### Logs or other output that would be helpful
(If logs are large, please upload as attachment).

TypeError                                 Traceback (most recent call last)
<ipython-input-9-80fac15278ee> in <module>()
----> 1 training()

<ipython-input-8-d1198db7bf1d> in training()
     11         loss = mnist.loss(logits, labels_placeholder)
     12         train_op = mnist.training(loss, FLAGS.learning_rate)
---> 13         eval_correct = mnist.evaluation(logits, labels_placeholder)
     14         # Build the summary operation based on the TF collections of Summaries.
     15         summary_op = tf.merge_all_summaries()

/opt/conda/lib/python3.5/site-packages/tensorflow/examples/tutorials/mnist/mnist.py in evaluation(logits, labels)
    146   # the examples where the label is in the top k (here k=1)
    147   # of all logits for that example.
--> 148   correct = tf.nn.in_top_k(logits, labels, 1)
    149   # Return the number of true entries.
    150   return tf.reduce_sum(tf.cast(correct, tf.int32))

/opt/conda/lib/python3.5/site-packages/tensorflow/python/ops/gen_nn_ops.py in in_top_k(predictions, targets, k, name)
    547   """
    548   return _op_def_lib.apply_op("InTopK", predictions=predictions,
--> 549                               targets=targets, k=k, name=name)
    550 
    551 

/opt/conda/lib/python3.5/site-packages/tensorflow/python/ops/op_def_library.py in apply_op(self, op_type_name, name, **keywords)
    484             for base_type in base_types:
    485               _SatisfiesTypeConstraint(base_type,
--> 486                                        _Attr(op_def, input_arg.type_attr))
    487             attrs[input_arg.type_attr] = attr_value
    488             inferred_from[input_arg.type_attr] = input_name

/opt/conda/lib/python3.5/site-packages/tensorflow/python/ops/op_def_library.py in _SatisfiesTypeConstraint(dtype, attr_def)
     57           "DataType %s for attr '%s' not in list of allowed values: %s" %
     58           (dtypes.as_dtype(dtype).name, attr_def.name,
---> 59            ", ".join(dtypes.as_dtype(x).name for x in allowed_list)))
     60 
     61 

TypeError: DataType float32 for attr 'T' not in list of allowed values: int32, int64

**Comment by prb12** [comment]
> Just implemented the mnist code provided by tensorflow. 2. 3.

Could you please be a bit more precise.
Is this code you 'implemented' based on a tutorial? If so, could you please 
a) check carefully for any transcription mistakes
b) if you believe there are none, please provide a link to the 'provided code' and a copy of the code you are executing.

Alternatively, if this an unmodified example program from the TensorFlow distribution could you please provide the *exact* sequence of command lines used to build and execute the program.

Thanks!

**Comment by gnujimmik** [comment]
The code I had was obsolete and now it is working fine. Thanks!
