### ISSUE TITLE
Optimizing the Frozen Graph

### ISSUE THREAD

**Issue by essalahsouad** [tensorflow/tensorflow#30268]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):macOS
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:Nan
- TensorFlow installed from (source or binary):binary
- TensorFlow version:1.13.0-rc2
- Python version:3.7.2
- Installed using virtualenv? pip? conda?:pip
- Bazel version (if compiling from source):0.27.0
- GCC/Compiler version (if compiling from source):Nan
- CUDA/cuDNN version:Nan
- GPU model and memory:Nan
**Describe the problem**
Optimizing the Frozen Graph using The optimize_for_inference tool
refering to this [tuto](https://heartbeat.fritz.ai/intro-to-machine-learning-on-android-how-to-convert-a-custom-model-to-tensorflow-lite-e07d2d9d50e3)
**Provide the exact sequence of commands / steps that you executed before running into the problem**
`bazel build tensorflow/python/tools:optimize_for_inference && \ bazel-bin/tensorflow/python/tools/optimize_for_inference.py \ --input=/Users/hak/tensorboard/logs/frozen.pb \ --output=/Users/hak/tensorboard/logs/frozen_opt.pb \ --frozen_graph=True \ --input_names=ImageTensor \ --output_names=ReziseBilinear_1`
refer to this 
[link](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/tools/optimize_for_inference.py)
### trace back 

> INFO: Build completed successfully, 1 total action
> -bash:  bazel-bin/tensorflow/python/tools/optimize_for_inference.py: No such file or directory
> 
Adding that I'm not sure about the input and the output names options
any help??

**Comment by gadagashwini** [comment]
@essalahsouad Please provide the correct link of optimize_for_inference.py. Thanks!

**Comment by essalahsouad** [comment]
@gadagashwini could you take a look now

**Comment by freedomtan** [comment]
@essalahsouad if you read the [link](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/tools/optimize_for_inference.py) you provided carefully, you can find that the command line to run it is
```sh
bazel-bin/tensorflow/python/tools/optimize_for_inference
```
instead of 
```sh
bazel-bin/tensorflow/python/tools/optimize_for_inference.py
```

**Comment by essalahsouad** [comment]
@freedomtan thank you, it's my fault
