### ISSUE TITLE
Get the number of GPUs used in Tensorflow Distributed in a multi node approach

### ISSUE THREAD

**Issue by DEKHTIARJonathan** [tensorflow/tensorflow#30262]
I am currently trying to compare Horovod and Tensorflow Distributed API. 

When using using Horovod, I am able to access the total number of GPUs currently used as follows:

```python
import horovod.tensorflow as hvd
size = hvd.size()
```

A similar concept is available when using PyTorch Distributed API:
```python
size = int(os.environ["WORLD_SIZE"])
```

-----------

I would like to perform the same operation and obtain the number of GPUs currently in use for multi GPUs/nodes with TF Distributed official API.

I can't use `CUDA_VISIBLE_DEVICES` environment variable as it would only work on a single node.

**Comment by guptapriya** [comment]
I think `Strategy.num_replicas_in_sync` is what you're looking for if you are using distribution strategy:

https://www.tensorflow.org/api_docs/python/tf/distribute/Strategy#num_replicas_in_sync

Does this work?

**Comment by DEKHTIARJonathan** [comment]
Thanks it answered my question.
