### ISSUE TITLE
How should i use tf.image.draw_bounding_box() when each batch have different bbox_num ?

### ISSUE THREAD

**Issue by AaronStuart** [tensorflow/tensorflow#30267]
The documents show that bboxes' shape is [batch, num_bounding_boxes, 4]. This means every batch have same number of bbox. 
But in detect, each image may have different number of bboxes. Who can tell me how should i do, thanks !
BTW, I use tf.gather_nd() to get bboxes, is there any method to get dimension-aligned bboxes? 

**System information**
- TensorFlow version (you are using): Tensorflow 1.13

**Comment by ymodak** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow-tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.
