### ISSUE TITLE
cp: cannot stat 'bazel-bin/tensorflow/tools/pip_package/build_pip_package.runfiles/tensorflow': No such file or directory

### ISSUE THREAD

**Issue by cancan101** [tensorflow/tensorflow#3027]
### Steps to reproduce
1. `docker build ./tensorflow/tools/docker/Dockerfile.devel-gpu`

### Logs or other output that would be helpful
```
cp: cannot stat 'bazel-bin/tensorflow/tools/pip_package/build_pip_package.runfiles/tensorflow': No such file or directory
cp: cannot stat 'bazel-bin/tensorflow/tools/pip_package/build_pip_package.runfiles/external': No such file or directory
The command '/bin/sh -c ./configure &&     bazel build --local_resources 3072,3.0,1.0 -c opt --config=cuda tensorflow/tools/pip_package:build_pip_package &&     bazel-bin/tensorflow/tools/pip_package/build_pip_package /tmp/pip &&     pip install --upgrade /tmp/pip/tensorflow-*.whl' returned a non-zero code: 1
```

**Comment by prb12** [comment]
Could you please provide more details of the TensorFlow version you are using?

**Comment by cancan101** [comment]
I am using the Dockerfile from [here](https://github.com/4Catalyzer/tensorflow/blob/dcbc4701845b6bad57b6183514d64d0eeabad57a/tensorflow/tools/docker/Dockerfile.devel-gpu) which checks out `r0.8`. I am also setting:
```
ENV TF_UNOFFICIAL_SETTING=1 \
    TF_CUDA_COMPUTE_CAPABILITIES=3.0
```

**Comment by vrv** [comment]
We probably need to update the Dockerfile to check out r0.9, bazel 0.3.0 doesn't work with r0.8.

**Comment by martinwicke** [comment]
I want to get rid of this dockerfile. As a stopgap, can you use the Dockerfile we use for testing? 

https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/ci_build/Dockerfile.gpu

**Comment by cancan101** [comment]
I am using the following Dockerfile with the relevant changes highlighted and it now builds: https://github.com/4Catalyzer/tensorflow/blob/ce67e52461f9e6b05ec8cd35d0736dd0c68f07eb/tensorflow/tools/docker/Dockerfile.devel-gpu#L82-L85

**Comment by martinwicke** [comment]
Cool, thanks! Do you want to make a PR with that?

**Comment by cancan101** [comment]
https://github.com/tensorflow/tensorflow/pull/3143

**Comment by aselle** [comment]
Seems like this is resolved. Closing for now.

**Comment by Julius-ZCJ** [comment]
@cancan101 Hi ，I have met the same problem, can you tell more details about how you solved this problem. Thank you very much
