### ISSUE TITLE
tflite_convert  .h5 to .tflite Init node Conv1/kernel/Assign do esn't exist in graph

### ISSUE THREAD

**Issue by rkuo2000** [tensorflow/tensorflow#30272]
**System information**
- OS Platform and Distribution : Windows 7
- TensorFlow version: tensorflow_gpu-1.14.0
- Python version: 3.7.3 
- CUDA/cuDNN version: 10.1 / 7.6.1
- GPU model and memory: GTX1080Ti / 11GB

**Describe the current behavior**
after transfer learning on tensorflow.keras mobilenet v2 and saved .h5,
*`tflite_convert --keras_model_file=tl_mobilenetv2.h5 --output_file=tl_mobilenetv2.tflite --allow_custom_ops`*

**Describe the Issues**
.tflite is generated, but error message shown:
**E tensorflow/core/grappler/grappler_item_builder.cc:637] Init node Conv1/kernel/Assign doesn't exist in graph**

**Other info / logs**
Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 10143 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1080 Ti, pci bus id: 0000:03:00.0, compute capability: 6.1)
2019-07-01 18:16:28.142672: E tensorflow/core/grappler/grappler_item_builder.cc:637] Init node Conv1/kernel/Assign doesn't exist in graph

**Comment by haozha111** [comment]
Could you share your keras model file with me so I can give it a try? Thanks.

**Comment by rkuo2000** [comment]
https://drive.google.com/open?id=1sTwEgYMDPUV5DsXA1sBG_7MxjE9Xicxc

**Comment by EstechRnD** [comment]
I'm also facing the same problem. 

System information

OS Platform and Distribution : Windows 10
TensorFlow version: tensorflow_gpu-1.14.0
Python version: 3.5.6
CUDA/cuDNN version: 10.1 / 7.6.1
GPU model and memory: GTX1050 / 4GB

**Comment by zmk5** [comment]
I have this issue too. Even the example code located [here](https://www.tensorflow.org/lite/convert/python_api#exporting_a_tfkeras_file_) gives the following error:

```
>>> tflite_model = converter.convert()
2019-08-28 17:42:49.934545: I tensorflow/core/grappler/devices.cc:60] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0 (Note: TensorFlow was not compiled with CUDA support)
2019-08-28 17:42:49.934746: I tensorflow/core/grappler/clusters/single_machine.cc:359] Starting new session
2019-08-28 17:42:49.937814: E tensorflow/core/grappler/grappler_item_builder.cc:637] Init node dense/kernel/Assign doesn't exist in graph
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/zmk5/.local/lib/python3.6/site-packages/tensorflow/lite/python/lite.py", line 898, in convert
    **converter_kwargs)
  File "/home/zmk5/.local/lib/python3.6/site-packages/tensorflow/lite/python/convert.py", line 404, in toco_convert_impl
    input_data.SerializeToString())
  File "/home/zmk5/.local/lib/python3.6/site-packages/tensorflow/lite/python/convert.py", line 172, in toco_convert_protos
    "TOCO failed. See console for info.\n%s\n%s\n" % (stdout, stderr))
tensorflow.lite.python.convert.ConverterError: TOCO failed. See console for info.
/bin/sh: 1: toco_from_protos: not found
```

OS Platform and Distribution : Ubuntu 18.04
TensorFlow version: tensorflow-1.14.0
Python version: 3.6.8

**Comment by yakeer** [comment]
Same error here.
Has anyone got over it somehow?

**Comment by zmk5** [comment]
I've been looking and have yet to find a solution. I attempted this with the Command Line operator they provide and it still doesn't work, even for their own example code lol

**Comment by sreeharshaangara** [comment]
Same issue for my as well, 
2019-08-29 20:44:30.935433: I tensorflow/core/grappler/devices.cc:60] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0 (Note: TensorFlow was not compiled with CUDA support)
2019-08-29 20:44:30.947953: I tensorflow/core/grappler/clusters/single_machine.cc:356] Starting new session
2019-08-29 20:44:30.952924: E tensorflow/core/grappler/grappler_item_builder.cc:656] Init node dense/kernel/Assign doesn't exist in graph

**Comment by koala9013** [comment]
Facing same issue as well,

Anyone got a solution?

**Comment by liushengzhong1023** [comment]
Same issue here with tf1.14 on Ubuntu 16.04. Any solutions or ideas yet?

**Comment by sreyasm** [comment]
Same issue here with TF1.14 on Windows 10.

**Comment by xinglinzh** [comment]
Just got the same issue with TF1.14 with Mac 10.14.6

**Comment by joker2017** [comment]
Same issue here with TF1.14 on Windows 10

**Comment by haozha111** [comment]
Sorry for the wait. I'm taking a look now. Will update once I got any new findings. Thanks!

**Comment by haozha111** [comment]
Hi,

I could convert the keras mobilenet model to tflite without issue using the TF 2 API as documented here:
https://www.tensorflow.org/lite/convert/python_api#end-to-end_mobilenet_conversion_

Please note that there are API signature changes between TF 1.X and TF2.0. The code instructions in that page is based on TF 2.0 API.

Could you please use the latest TF 2.0 code (the official 2.0 version has been released last week) and see if that issue could be resolved?

Thanks and sorry for the inconvenience.

**Comment by haozha111** [comment]
If that issue still exists, could you please share your keras model file (.h5) with me so that I can take a look (the link of above Google Drive is not valid any more).

**Comment by carlosbabativa** [comment]
I am having the same issue... 
tf 1.13
win 10

I ran into that issue once I  managed to fix a previous issue I was facing (having [None, None, None, 3] in the input layer. I had managed to solve the previous issue by adding a custom 
input_shapes={'input_1':[1,448,448,3]}
I tried the nightly method enable_v2_behavior and tested the TFLiteConverter but I am running into the same issue again. I noticed that input_shapes is no longer an argument of .from_keras_model.

Is there any other way to define the input shapes?

**Comment by Vinschni** [comment]
Same issue here
[model.h5.zip](https://github.com/tensorflow/tensorflow/files/3821243/model.h5.zip)

**Comment by Alcatraz-XW** [comment]
Same issue with TF1.14 on raspi4b

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.

**Comment by hwangdeyu** [comment]
Same issue with TF1.15.2...
