### ISSUE TITLE
why official tensorflow lite android demo faster than building library by myself

### ISSUE THREAD

**Issue by JoelTsui** [tensorflow/tensorflow#30275]
I use the official android demo [here](https://github.com/tensorflow/examples/tree/master/lite/examples/object_detection/android),and run the model I created by myself under device rk3288, the inference cost is about 200ms, but when I build `libtensorflowlite.so` by myself using the command below, it cost almost 500ms, I can't understand the gap. **Does any one know how to build tensorflow-lite c++  library by ourself, and get the same level of performance by official?**

The build command is here:

`bazel build -c opt --crosstool_top=//external:android/crosstool  --host_crosstool_top=@bazel_tools//tools/cpp:toolchain --cxxopt="-std=c++11" --fat_apk_cpu=armeabi-v7a  --config=android_arm //tensorflow/lite:libtensorflowlite.so`

**Comment by jdduke** [comment]
Try using:

`--config=android_arm64` instead of `--fat_apk_cpu=armeabi-v7a --config=android_arm`

**Comment by JoelTsui** [comment]
> Try using:
> 
> `--config=android_arm64` instead of `--fat_apk_cpu=armeabi-v7a --config=android_arm`

Using arm64 cup architecture, it will build with ruy, and I can get the same inference time cost. But the cpu architecture of rk3288 is 32 bit, only support armeabi-v7a. I test inference cost between official android demo and project created by myself under rk3288 of armeabi-v7a, the time cost vary greatly, so I wander if I missed some building definitions

**Comment by JoelTsui** [comment]
I am using the same so, and write test code all by c++ native, then running under rk3288, it costs 100ms, so I think it maybe something wrong when embedding into android project

**Comment by JoelTsui** [comment]
I think I found the solution. When I open camera, the inference time cost suddenly increase.

**Comment by leeli92** [comment]
> I am using the same so, and write test code all by c++ native, then running under rk3288, it costs 100ms, so I think it maybe something wrong when embedding into android project

hi,I have read your question and i need your help, would like to ask you some questions? I used your build command to build libtensorflowlite.so, but an error occurred :
![image](https://user-images.githubusercontent.com/17593272/61166157-e5f29c80-a55b-11e9-86c5-de14383291ab.png)
My guess is that the relevant environment versions don't match, my tensorflow is release-1.14.0 and bazel-0.18.0 .Can you give me some advice please?

**Comment by JoelTsui** [comment]
You should configure tensorflow project before running bazel command
