### ISSUE TITLE
Failed to load nodelet [/zed/zed_wrapper_node] of type [zed_wrapper/ZEDWrapperNodelet]

### ISSUE THREAD

**Issue by abdo-robotic** [tensorflow/tensorflow#30271]
hello i have worked with zed camera for long time when i run my zed camera this morning i got this error 

ROS_MASTER_URI=http://localhost:11311

process[zed/zed_wrapper_node-1]: started with pid [2349]
process[zed/zed_state_publisher-2]: started with pid [2350]
[ INFO] [1561980098.631115078]: Initializing nodelet with 4 worker threads.
[ERROR] [1561980100.164477981]: Failed to load nodelet [/zed/zed_wrapper_node] of type [zed_wrapper/ZEDWrapperNodelet] even after refreshing the cache: Failed to load library /home/abanay/catkin_ws/devel/lib//libZEDWrapper.so. Make sure that you are calling the PLUGINLIB_EXPORT_CLASS macro in the library code, and that names are consistent between this macro and your XML. Error string: Could not load library (Poco exception = libnvidia-fatbinaryloader.so.384.130: cannot open shared object file: No such file or directory)
[ERROR] [1561980100.164522687]: The error before refreshing the cache was: Failed to load library /home/abanay/catkin_ws/devel/lib//libZEDWrapper.so. Make sure that you are calling the PLUGINLIB_EXPORT_CLASS macro in the library code, and that names are consistent between this macro and your XML. Error string: Could not load library (Poco exception = libnvidia-fatbinaryloader.so.384.130: cannot open shared object file: No such file or directory)

**Comment by gadagashwini** [comment]
@abdo-robotic Looks like this issue is not related to Tensorflow. Can you confirm us. Thanks!

**Comment by abdo-robotic** [comment]
i reinstalled cuda zed sdk ROS  and i keep getting the same error

**Comment by gadagashwini** [comment]
@abdo-robotic Looks this issue is not related Tensorflow, Can you post this issue in appropriate repo. Thanks!

**Comment by gadagashwini** [comment]
Will close this issue, please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Comment by abdo-robotic** [comment]
i reinstalled  ubuntu and cuda, it work well now thank you
