### ISSUE TITLE
[TF 2.0] tf.keras.preprocessing.image

### ISSUE THREAD

**Issue by alik3954** [tensorflow/tensorflow#30286]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using): 2.0.0-beta1
- Are you willing to contribute it (Yes/No): No

**Describe the feature and the current behavior/state.**
Keras has neat data feeder in ```tf.keras.preprocessing.image.ImageDataGenerator``` that is basically working for Python 2 only because it uses ```PIL``` for images which currently is not available for Python 3.
**Will this change the current api? How?**
It will not change the API, it just makes it work with python 3 (perhaps using pillow)
**Who will benefit with this feature?**
Anyone trying to use Python3 API of TF2.0 
**Any Other info.**

**Comment by tanzhenyu** [comment]
Our focus has been pivoted to support this through Python3 via [this work](https://github.com/keras-team/governance/blob/master/rfcs/20190729-keras-preprocessing-redesign.md).
