### ISSUE TITLE
[TF 2.0] Minor changes to the 'Load images with tf.data' tutorial + fix image links

### ISSUE THREAD

**Issue by 8bitmp3** [tensorflow/tensorflow#30283]
_URL(s) with the issue:_
https://www.tensorflow.org/beta/tutorials/load_data/images

_Description of main issue:_
Pls take a look at JPG/JPEG links in the 'Load images with tf.data' tutorial in the 'Inspect the images' section. When you inspect the site elements they appear to be missing a letter 'g' as in `jpeg` or `jpg`
```
https://www.tensorflow.org/beta/tutorials/load_data/images_files/output_16_0.jpe
https://www.tensorflow.org/beta/tutorials/load_data/images_files/output_16_2.jpe
https://www.tensorflow.org/beta/tutorials/load_data/images_files/output_16_4.jpe
```

_Other minor suggestions:_
Rearrangement of words, fixing some grammar, addition/subtraction of commas/colons/spaces in English and Python for consistency - will submit a PR right away for your review @MarkDaoust @lamberta

**Comment by lamberta** [comment]
Thank you. We recently hit this filename issue ... something about nb_convert and mime types. @yashk2810 is looking in to it.

**Comment by yashk2810** [comment]
@MarkDaoust has a fix on the way. This should be fixed soon.

**Comment by MarkDaoust** [comment]
Thanks for the report.

Yes mimetypes

https://github.com/jupyter/nbconvert/pull/175
https://www.onebigfluke.com/2014/02/crazy-python-mimetypes-module.html

The fix is in, and the site-updater is running now. This will be resolved by EOD.
