### ISSUE TITLE
ERROR: no such package 'tensorflow/lite/toco': Unable to determine the local repository for directory /home/devim/tensorflow/tensorflow/lite/toco

### ISSUE THREAD

**Issue by devimonica** [tensorflow/tensorflow#30282]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu
- TensorFlow installed from (source or binary): 
- TensorFlow version: 1.12.0
- Python version: 2.7.15
- Installed using virtualenv? pip? conda?: python-pip
- Bazel version (if compiling from source): 0.26.0
- GCC/Compiler version (if compiling from source): 
- CUDA/cuDNN version: Using CPU
- GPU model and memory: N/A

Code used:

`bazel run -c opt tensorflow/lite/toco:toco -- --input_file=models/research/object_detection/tflite_graph.pb --output_file=models/research/object_detection/detect.tflite --input_shapes=1,300,300,3 --input_arrays=normalized_input_image_tensor --output_arrays='TFLite_Detection_PostProcess','TFLite_Detection_PostProcess:1','TFLite_Detection_PostProcess:2','TFLite_Detection_PostProcess:3' --inference_type=QUANTIZED_UINT8 --mean_values=128 --std_values=128 --change_concat_input_ranges=false --allow_custom_ops`

I got this error

INFO: Options provided by the client:
  Inherited 'common' options: --isatty=1 --terminal_columns=120
INFO: Reading rc options for 'run' from /home/devim/tensorflow/.bazelrc:
  Inherited 'build' options: --apple_platform_type=macos --define framework_shared_object=true --define=use_fast_cpp_protos=true --define=allow_oversize_protos=true --spawn_strategy=standalone --strategy=Genrule=standalone -c opt --announce_rc --define=grpc_no_ares=true --define=PREFIX=/usr --define=LIBDIR=$(PREFIX)/lib --define=INCLUDEDIR=$(PREFIX)/include
INFO: Reading rc options for 'run' from /home/devim/tensorflow/.tf_configure.bazelrc:
  Inherited 'build' options: --host_force_python=PY2 --action_env PYTHON_BIN_PATH=/home/devim/venv/bin/python --action_env PYTHON_LIB_PATH=/home/devim/venv/lib/python2.7/site-packages --python_path=/home/devim/venv/bin/python --action_env TF_CONFIGURE_IOS=0
ERROR: Skipping 'tensorflow/lite/toco:toco': no such package 'tensorflow/lite/toco': Unable to determine the local repository for directory /home/devim/tensorflow/tensorflow/lite/toco
WARNING: Target pattern parsing failed.
ERROR: no such package 'tensorflow/lite/toco': Unable to determine the local repository for directory /home/devim/tensorflow/tensorflow/lite/toco
INFO: Elapsed time: 0.092s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
FAILED: Build did NOT complete successfully (0 packages loaded)

The directory tensorflow/lite/toco exists and here is the screenshot.
![Capture](https://user-images.githubusercontent.com/48072621/60449936-b7d59a00-9bf6-11e9-8a12-b5318d93bef3.JPG)

**Comment by devimonica** [comment]
@aselle @achandraa @jvishnuvardhan can you please look into this ?

**Comment by ymodak** [comment]
Toco converter is deprecated with TF 1.12. Can you please try [```tflite_convert```](https://www.tensorflow.org/lite/convert/cmdline_examples#command-line_tools_) instead?
Installing tf-nightly is recommended for using TensorFlow Lite Converter.

**Comment by ymodak** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
