### ISSUE TITLE
AttributeError: module 'tensorflow' has no attribute 'matrix_band_part'

### ISSUE THREAD

**Issue by lizaigaoge550** [tensorflow/tensorflow#30297]
Tensorflow 2.0.0-alpha0 AttributeError: module 'tensorflow' has no attribute 'matrix_band_part'

**Comment by mihaimaruseac** [comment]
Can you provide a code sample, version you are using, how you installed it, operating platform, etc? There is an issue template with all the details that should be filled in to get a faster response.

**Comment by rmothukuru** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
