### ISSUE TITLE
[Question] Adding new hardware device support

### ISSUE THREAD

**Issue by Scott-Thomas-Dev** [tensorflow/tensorflow#30293]
Hello, 
I'm developing a tensorflow modification to support a new hardware device and I was curious if there had been any update to the procedure since this issue was first raised in: 
Feature Request: plug-in support for new devices #4359

I'm following along with the documentation provided here
https://github.com/knuedge/tensorflow/blob/36e0cdf04f294bfd51931d4f78e291590ed0d3ec/tensorflow/g3doc/hardware/adding_support/index.md

But it is quite out of date so before I plow ahead I'd like to know that this isn't a solved problem.

Thanks,
Scott

**Comment by ravikyram** [comment]
@Scott-Thomas-Dev 
Please, check whether the below links will helps you. Thanks!
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/common_runtime/device.h
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/common_runtime/device_factory.h

**Comment by jpienaar** [comment]
Hey Scott,

This issue slipped through my filter.

We are working on a new proposal & prototype to get some larger community feedback.  But its not there yet. Could you perhaps tell me more about the target?

Thanks,

Jacques

**Comment by kevint324** [comment]
Hi Jpienaar
Is there any reference document or discussion about the new proposal?
We are trying to make our platform works on tensorflow and it involves quite some code change and quite a lot of them involves framework change which is kinda ugly.
Also any schedule about the proposal and prototype?

Thanks
Kevin

**Comment by jpienaar** [comment]
Unfortunately the design/prototype did not get the buy in from other folks and is being redesigned post more exploration work. It may be 3-6 months before the next one. The closest externally visible is the changes we are making on the new TF & XLA integration using MLIR. This is still early though. In the interim the two options are the existing ones of creating a new TF device or a new XLA device.

Best,

Jacques

**Comment by bhack** [comment]
Is it still too early?

**Comment by asharma20** [comment]
Following this as well

**Comment by edwardyehuang** [comment]
Any update?

**Comment by harishch4** [comment]
Any update?

**Comment by kevint324** [comment]
I'm not speaking for tensorflow community and this is just for your information
Recently tensorflow 2.5 released device plugin
https://blog.tensorflow.org/2021/06/pluggabledevice-device-plugins-for-TensorFlow.html

IMHO, the device plugin along with MLIR/TFRT is the ultimate solution for 3rd party device vendors to hook their chips into TF.

**Comment by harishch4** [comment]
> I'm not speaking for tensorflow community and this is just for your information
> Recently tensorflow 2.5 released device plugin
> https://blog.tensorflow.org/2021/06/pluggabledevice-device-plugins-for-TensorFlow.html
> 
> IMHO, the device plugin along with MLIR/TFRT is the ultimate solution for 3rd party device vendors to hook their chips into TF.

This looks awesome, thanks!

**Comment by gadagashwini** [comment]
Hi @Scott-Thomas-Dev, Pluggable device for TensorFlow is available now. Objective is to implement a pluggable device mechanism which allows to run existing TensorFlow programs on a new device without user changing the code. For more information and how to use Plugin devices for Tensorflow can be found [here](https://github.com/tensorflow/community/blob/master/rfcs/20200624-pluggable-device-for-tensorflow.md). Thank you!
