### ISSUE TITLE
Typo in variable name in Variables Getting Started Doc

### ISSUE THREAD

**Issue by zpardos** [tensorflow/tensorflow#303]
Example code begins by defining the counter variable as "var" but later on adds to an undefined variable called "state"

**Comment by robertmcanany** [comment]
Also, toward the end of the same example, the line ```with tf.Session()``` caused an error.  I got it to work by using ```with tf.Session() as sess:``` instead.

**Comment by vrv** [comment]
Should be fixed now, thanks!
