### ISSUE TITLE
installation isuuse 

### ISSUE THREAD

**Issue by RaghvendraDubey20** [tensorflow/tensorflow#30302]
Traceback (most recent call last):
  File "eg1.py", line 1, in <module>
    import tensorflow as tf
  File "C:\Program Files\Python36\lib\site-packages\tensorflow\__init__.py", line 28, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\__init__.py", line 52, in <module>
    from tensorflow.core.framework.graph_pb2 import *
  File "C:\Program Files\Python36\lib\site-packages\tensorflow\core\framework\graph_pb2.py", line 7, in <module>
    from google.protobuf import descriptor as _descriptor
  File "C:\Program Files\Python36\lib\site-packages\google\protobuf\descriptor.py", line 47, in <module>
    from google.protobuf.pyext import _message
ImportError: DLL load failed: The specified procedure could not be found.
![error](https://user-images.githubusercontent.com/52444630/60493670-ebd8ba00-9cdf-11e9-95e5-c03f9210a8dd.png)

**Comment by TuringEmmy** [comment]
Raghvendra Dubey
        您好！我已收到您的邮件。
        
        有什么问题随时与我联系和沟通，祝好！


2019-7-2
| |
xxx
|
|
yonglonggeng@163.com
|
签名由网易邮箱大师定制
On 7/2/2019 15:50，Raghvendra Dubey<notifications@github.com> wrote：

Traceback (most recent call last):
File "eg1.py", line 1, in
import tensorflow as tf
File "C:\Program Files\Python36\lib\site-packages\tensorflow_init_.py", line 28, in
from tensorflow.python import pywrap_tensorflow # pylint: disable=unused-import
File "C:\Program Files\Python36\lib\site-packages\tensorflow\python_init_.py", line 52, in
from tensorflow.core.framework.graph_pb2 import *
File "C:\Program Files\Python36\lib\site-packages\tensorflow\core\framework\graph_pb2.py", line 7, in
from google.protobuf import descriptor as _descriptor
File "C:\Program Files\Python36\lib\site-packages\google\protobuf\descriptor.py", line 47, in
from google.protobuf.pyext import _message
ImportError: DLL load failed: The specified procedure could not be found.

**Comment by RaghvendraDubey20** [comment]
please help me to fix this ,i have a lot to assignment pending just because of this issue

**Comment by RaghvendraDubey20** [comment]
> Raghvendra Dubey 您好！我已收到您的邮件。 有什么问题随时与我联系和沟通，祝好！ 2019-7-2 | | xxx | | yonglonggeng@163.com | 签名由网易邮箱大师定制 On 7/2/2019 15:50，Raghvendra Dubey<notifications@github.com> wrote： Traceback (most recent call last): File "eg1.py", line 1, in import tensorflow as tf File "C:\Program Files\Python36\lib\site-packages\tensorflow_init_.py", line 28, in from tensorflow.python import pywrap_tensorflow # pylint: disable=unused-import File "C:\Program Files\Python36\lib\site-packages\tensorflow\python_init_.py", line 52, in from tensorflow.core.framework.graph_pb2 import * File "C:\Program Files\Python36\lib\site-packages\tensorflow\core\framework\graph_pb2.py", line 7, in from google.protobuf import descriptor as _descriptor File "C:\Program Files\Python36\lib\site-packages\google\protobuf\descriptor.py", line 47, in from google.protobuf.pyext import _message ImportError: DLL load failed: The specified procedure could not be found. — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.

help me to figure out what is the problem

**Comment by RonLek** [comment]
@RaghvendraDubey20  Try doing one of the things suggested here https://github.com/tensorflow/tensorflow/issues/22794 and here https://stackoverflow.com/questions/52092810/tensorflow-error-dll-load-failed-the-specified-procedure-could-not-be-found.
It's mostly a compatibility problem between your CUDA and tensorflow version.

**Comment by ravikyram** [comment]
Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version. Also, did you compile from source or install a binary?

 If you are unclear what to include see the issue template displayed in the Github new issue [template](https://github.com/tensorflow/tensorflow/issues/new/choose)

We ask for this in the issue submission template, because it is really difficult to help without that information. Thanks!

**Comment by ravikyram** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
