### ISSUE TITLE
tf.keras.layers.Conv1DTranspose ?

### ISSUE THREAD

**Issue by yoshihikoueno** [tensorflow/tensorflow#30309]
This is somewhat related to the issue #8729, which is already solved.
In the issue, tf.nn.conv1d_transpose was requested and implemented in the end.

But the corresponding function in tf.layers or tf.keras is missing.
In other words, there's no function like tf.layers.conv1d_transpose, tf.keras.layers.Conv1DTranspose.

Can you please implement it?
Since there's already tf.nn.conv1d_transpose, I guess it doesn't take so much time to implement it.

**Comment by tanzhenyu** [comment]
This is already implemented.
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/keras/layers/convolutional.py

**Comment by yoshihikoueno** [comment]
Thank you for your response.

But could you tell me in which branch and file we can find the function
tf.keras.layers.Conv1D?

I can't find it in the file you said.

**Comment by tanzhenyu** [comment]
Oh it seems that we only have 2dtranspose, but not 1dtranspose.

**Comment by yoshihikoueno** [comment]
Any updates so far?

**Comment by tuxzz** [comment]
Since TensorFlow already has `tf.nn.conv1d_transpose`, it should be easy to implement `tf.keras.Conv1DTranspose`.

**Comment by Guitaricet** [comment]
It is really weird to not to have Conv1DTransposed in TF.
I feel like I am able to turn right 90 degrees, but not left. Yes, this is not a huge problem because you can always turn right 3 times, but why?

Anyway, this is what I use and I hope it'll help someone

```python
class Conv1DTranspose(tf.keras.layers.Layer):
    def __init__(self, filters, kernel_size, strides=1, padding='valid'):
        super().__init__()
        self.conv2dtranspose = tf.keras.layers.Conv2DTranspose(
          filters, (kernel_size, 1), (strides, 1), padding
        )

    def call(self, x):
        x = tf.expand_dims(x, axis=2)
        x = self.conv2dtranspose(x)
        x = tf.squeeze(x, axis=2)
        return x
```

**Comment by kpe** [comment]
even just for symmetry reasons - ``Conv1DTranspose`` needs to find it's way in the Keras API.

It has been requested already (see #6724) but denied as it can't be reduced to a ``Conv2DTranspose`` which is already implemented. But if we keep that reasoning, why do we need ``Conv1D``, ``Conv2D`` if all of them can be replaced with a ``Conv3D``.

And let`s face it ``Conv1DTranspose`` is not that exotic, that everyone who needs it, should be forced to implement it's own version.

Could it be, that ``Conv1DTranspose`` is not here, because it is not in the original Keras API? Should we report the issue there first, and wait until it finds it's way back to TF?

**Comment by tanzhenyu** [comment]
Somehow this falls outside of my radar. I will make this done today.

**Comment by tanzhenyu** [comment]
This is fixed and should be available in tf-nightly tomorrow. Closing it.

**Comment by kpe** [comment]
Thank you @tanzhenyu - that was really quick!

P.S. I guess it also resolves #29157

**Comment by tanzhenyu** [comment]
> Thank you @tanzhenyu - that was really quick!
> 
> P.S. I guess it also resolves #29157

Yeah, resolving that too. Thanks

**Comment by yassinejaoudi** [comment]
Hi @tanzhenyu 

I have got this error while running 'Conv1DTranspose': 

AttributeError: module 'tensorflow.keras.layers' has no attribute 'Conv1DTranspose'

while in TensorFlow documentation, this has been implemented. Could you please guide me on this?

**Comment by highstronger** [comment]
I met the same problem when using 'Timeseries anomaly detection using an Autoencoder' from Keras[https://keras.io/examples/timeseries/timeseries_anomaly_detection/](url). And I find that Tensorflow>=2.30 add the Conv1DTranspose, [https://tensorflow.google.cn/versions/r2.3/api_docs/python/tf/keras/layers/Conv1DTranspose](url).
