### ISSUE TITLE
TensorFlow Lite Micro int8 quantization support?

### ISSUE THREAD

**Issue by fouco2** [tensorflow/tensorflow#30314]
------------------------

### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 18.04
- **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device**: STM32F746G
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: '1.14.0'
- **Python version**: 3.7.3
- **Bazel version (if compiling from source)**:
- **GCC/Compiler version (if compiling from source)**: 
- **CUDA/cuDNN version**:
- **GPU model and memory**:
- **Exact command to reproduce**: 

You can collect some of this information using our environment capture script:

https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh

You can obtain the TensorFlow version with:

```bash
python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"
```

### Describe the problem
[feature request] 
.tflite model exported with a tensorflow version > r.1.13 are not compatible anymore with TensorFlow Lite Micro experimental Library. 

Kernels functions has to be updated to support asymetric per-axis quantization. 

Is there any release schedule on this lib?

### Source code / logs
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached. Try to provide a reproducible test case that is the bare minimum necessary to generate the problem.

**Comment by alanchiao** [comment]
Release schedule on which library? Tensorflow 1.14 is publicly available now (latest release) and any model you train (and then utilize something like post-training quantization) to produce a quantized model should be fine, according to the error message

**Comment by fouco2** [comment]
Production of a quantized model is fine, but the integration on an embedded device using TensorFlow lite experimental micro lib is not working. 
To my mind it is due to the asymmetric per-axis quantization not supported by micro kernel. So my question was more "is there any update of the experimental micro lib schedule?"

**Comment by dimtass** [comment]
I'm having the same issue with stm32f746 and tflite-micro.
I'm running `v1.14.0-rc1-22-gaf24dc9 1.14.0` version.

When using `OPTIMIZE_FOR_SIZE` or `QUANTIZED_UINT8` in TFLiteConverter and get the tflite flatbuffer, then when the buffer is parsed, the `tensorflow/lite/experimental/micro/simple_tensor_allocator.c:TfLiteTypeSizeOf` complains that:

> Only float32, int16, int32, int64, uint8, bool, complex64 supported currently.

And according to `c_api_internal.h` the type is set to `kTfLiteInt8`, which fails.

Without optimization, the flatbuffer is more than 3x times the size and also needs much more RAM.
Is there any way to enforce kTfLiteUInt8?
I thought that `tf.lite.constants.QUANTIZED_UINT8` was doing that, but for some reason it uses INT8.

**Comment by petewarden** [comment]
Assigning to @njeffrie since he's looking into this now.

**Comment by njeffrie** [comment]
We are working to support signed int8 quantization on micro.  Which operators are  you using?  We tend to prioritize based on usage, so this info can help us choose which ops to prioritize.  We currently have int8 versions of fully_connected and we are close to landing int8 per-channel versions of conv2d and depthwise_conv.

**Comment by dimtass** [comment]
Hi @njeffrie thanks for the reply. As you already mentioned the conv2d and depthwise_conv are the most common used and also in my case I've tried to use those two.

Thanks!

**Comment by njeffrie** [comment]
We have landed int8 reference kernels for conv, depthwise_conv, fully_connected and several other ops.  Thanks for your feedback and please feel free to re-open if you are still running into any issues.
