### ISSUE TITLE
The docs are unscrollable with JavaScript disabled

### ISSUE THREAD

**Issue by KOLANICH** [tensorflow/tensorflow#30316]
## URL(s) with the issue:

https://www.tensorflow.org/api_docs/python/tf/stack

## Description of issue (what needs changing):

```css
body[pending] {
	overflow: hidden;
}
```

should be removed.

### Clear description
JS is considered harmful, so the docs should be usable without JS.

The same problem is present in Android and Fuchsia docs.

**Comment by lamberta** [comment]
Thanks for the report.

We currently push old versions to GitHub and these are plain Markdown files: https://github.com/tensorflow/docs/blob/r1.10/site/en/api_docs/python/tf/stack.md

But we will also start pushing the the current version as part of the standard release. Good point.

**Comment by KOLANICH** [comment]
Thanks for the workaround, but I think that the websites should be fixed too.

**Comment by lamberta** [comment]
I've filed an internal ticket: b/136665885
Can't promise anything and JavaScript will remain on the site—but maybe we can at least get it to scroll without it :)

**Comment by lamberta** [comment]
Alright ... scrolling without JavaScript should be fixed in prod now.
I don't have a way to test but let me know if you run into an issue. Thanks

**Comment by KOLANICH** [comment]
Works like a charm. Thanks to evereone involved in fixing it!
