### ISSUE TITLE
TFlite conversion of Conv1D with dilation !=1

### ISSUE THREAD

**Issue by yodakohl** [tensorflow/tensorflow#30315]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Google Colab
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): tensorflow==2.0.0-beta1
- Python version: python3

**Describe the current behavior**
After converting a Conv1D op to tensorflow lite the interpreter cannot allocate tensors:

` tensorflow/lite/kernels/space_to_batch_nd.cc:96 NumDimensions(op_context.input) != kInputDimensionNum (3 != 4)Node number 0 (SPACE_TO_BATCH_ND) failed to prepare.
`

**Describe the expected behavior**
Tflite model should be able to load and execute.

**Code to reproduce the issue**

```
!pip install -q tensorflow==2.0.0-beta1

import tensorflow as tf

from tensorflow.keras.models import Model
from tensorflow.keras.layers import *

def get_model():
  input = tf.keras.Input(shape=(10,40))
  
  #No error when dilation rate == 1
  layer = Conv1D(32, (3),dilation_rate =2, padding='same',use_bias=False) (input)
  layer = GlobalMaxPooling1D()(layer)
  output = Dense(2) (layer)

  model = Model(inputs=[input], outputs=[output])
  return model


model = get_model()

converter = tf.lite.TFLiteConverter.from_keras_model(model)

tflite_model = converter.convert()
open("./trained_model.tflite", "wb").write(tflite_model)


interpreter = tf.lite.Interpreter(model_path="./trained_model.tflite")

interpreter.allocate_tensors()
```

**Other info / logs**
The problem does not occur when dilation_rate ==1

**Comment by ANSHUMAN87** [comment]
This issue is solved with PRs #28410, #27867 & #28179.  Thanks!

**Comment by rmothukuru** [comment]
Closing the issue as it has been resolved

**Comment by amahendrakar** [comment]
Was able to reproduce the issue with [TF v2.1](https://colab.research.google.com/gist/amahendrakar/5216cdcb0582cc62e6a6518ea5334e2e/2-1-template.ipynb) and [TF-nightly](https://colab.research.google.com/gist/amahendrakar/14ab31228c0693ab78b78ed73f0145d0/tf-nightly.ipynb#scrollTo=ieAW-NK5iqpf) i.e. v2.2.0-dev20200327. Please find the attached gist. Thanks!

**Comment by jdduke** [comment]
@karimnosseir can you take a look?

**Comment by karimnosseir** [comment]
@amahendrakar Can you share the sample code ?
The example in the original issue works when i tried it.

Thanks

**Comment by amahendrakar** [comment]
@karimnosseir,
Sure, below are the links of the gist using
- TF v2.1
https://colab.research.google.com/gist/amahendrakar/5216cdcb0582cc62e6a6518ea5334e2e/2-1-template.ipynb

- TF-nightly
https://colab.research.google.com/gist/amahendrakar/14ab31228c0693ab78b78ed73f0145d0/tf-nightly.ipynb#scrollTo=ieAW-NK5iqpf

**Comment by suicao** [comment]
@karimnosseir Hi, what tensorflow version were you using?

**Comment by karimnosseir** [comment]
Thanks @amahendrakar I can reproduce it on the 2.1 but works with nightly. Can you please retry.

@suicao i was using tf-nightly

**Comment by suicao** [comment]
I can confirm that this works with ```'2.2.0-dev20200414```

**Comment by amahendrakar** [comment]
@karimnosseir,
Works without any issues with the latest TF-nightly i.e. v2.2.0-dev20200415. Please find the gist [here](https://colab.research.google.com/gist/amahendrakar/67ba5ecd35433f7e61e5102f8d74611a/30315-tf-nightly.ipynb#scrollTo=ieAW-NK5iqpf). Thanks!

**Comment by karimnosseir** [comment]
Thanks for confirming. I am closing the issue. Please feel free to reopen/create a new one if you have any problems.

Thanks

**Comment by petros-giannakopoulos** [comment]
Issue still exists in TF 2.2 stable.
