### ISSUE TITLE
ImportError: /lib64/libc.so.6: version `GLIBC_2.15' not found on importing Keras

### ISSUE THREAD

**Issue by SuchismitaSahu1993** [tensorflow/tensorflow#30329]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version:
- Python version:
- Installed using virtualenv? pip? conda?:
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Describe the problem**

**Provide the exact sequence of commands / steps that you executed before running into the problem**

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by ravikyram** [comment]
Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version & Keras Version. Also, did you compile from source or install a binary?
Request you to fill the issue template  because it is really difficult to help without that information. Thanks!

**Comment by SuchismitaSahu1993** [comment]
OS details :
Linux rndarch45 2.6.32-696.30.1.el6.x86_64 #1 SMP Fri May 18 11:50:44 EDT 2018 x86_64 x86_64 x86_64 GNU/Linux


GLIB version= 2.12
Tensorflow version= 1.14.1

I was using PIP install

**Comment by ravikyram** [comment]
Please, go through the [link ](https://www.tensorflow.org/guide/keras) .you can directly import keras from tensorflow. Thanks!

**Comment by SuchismitaSahu1993** [comment]
@ravikyram 

Sorry, but my importing tensorflow itself isn't working because of the GLIBC incompatibility. The error is for not proper installation of tensorflow, not keras.

**Comment by ravikyram** [comment]
Just to verify did you get chance to follow instructions from [TensorFlow](https://www.tensorflow.org/install/pip) website .Please, let us know. Thanks!.

**Comment by ravikyram** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
