### ISSUE TITLE
Optimizer classes do not support complex variables

### ISSUE THREAD

**Issue by RafaelCosman** [tensorflow/tensorflow#3032]
Using TF 0.8.0.

`````` ---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-4-871aef3761c0> in <module>()
----> 1 train_step = tf.train.GradientDescentOptimizer(0.01).minimize(cross_entropy)
      2 init = tf.initialize_all_variables()

/usr/local/lib/python2.7/site-packages/tensorflow/python/training/optimizer.pyc in minimize(self, loss, global_step, var_list, gate_gradients, aggregation_method, colocate_gradients_with_ops, name)
    188         loss, var_list=var_list, gate_gradients=gate_gradients,
    189         aggregation_method=aggregation_method,
--> 190         colocate_gradients_with_ops=colocate_gradients_with_ops)
    191     return self.apply_gradients(grads_and_vars, global_step=global_step,
    192                                 name=name)

/usr/local/lib/python2.7/site-packages/tensorflow/python/training/optimizer.pyc in compute_gradients(self, loss, var_list, gate_gradients, aggregation_method, colocate_gradients_with_ops)
    243       grads = control_flow_ops.tuple(grads)
    244     grads_and_vars = list(zip(grads, var_list))
--> 245     self._assert_valid_dtypes([v for g, v in grads_and_vars if g is not None])
    246     return grads_and_vars
    247 

/usr/local/lib/python2.7/site-packages/tensorflow/python/training/optimizer.pyc in _assert_valid_dtypes(self, tensors)
    354         raise ValueError(
    355             "Invalid type %r for %s, expected: %s." % (
--> 356                 dtype, t.name, [v for v in valid_dtypes]))
    357 
    358   # --------------

ValueError: Invalid type tf.complex64 for complex_weight_variable:0, expected: [tf.float32].```
``````

**Comment by ibab** [comment]
Maybe it would be enough to throw an error specific to complex numbers that says
```
ValueError: Can't optimize complex variables.
Express complex variables using tf.complex(a, b), where a and b are real.
```
A solution that works with complex numbers would involve creating two real variables, and replacing every occurence of the old one with `tf.complex(a, b)`.
Wouldn't that also involve copying the graph?

**Comment by beniroquai** [comment]
Is this still an open issue? What do you mean by "replacing every occurence of the old one with tf.complex(a, b)" ? Is it possible to optimize a given complex-valued output of a layer?

**Comment by skye** [comment]
Automatically closing due to lack of recent activity. Since this issue is old at this point, please reopen the issue if it still occurs when tried with the latest version of Tensorflow. Thank you.

**Comment by Joshuaalbert** [comment]
Indeed if you want to optimize over a complex variable you need to instead define two float variables which take the place of real and imaginary parts, and then use var_list=[real_var, imag_var].

**Comment by kovkev** [comment]
@Joshuaalbert Would it take care of doing back propagation the way it is explained in the following paper? 

https://openreview.net/forum?id=H1S8UE-Rb

That still needs to be implemented somehow, right? Do you know what the best way to do so would be?

**Comment by Joshuaalbert** [comment]
The paper you mention uses projections of the form `W = W_r + i W_i` and input tensors of the form `x= x_r + i x_i`. The standard perceptron complex output is then 
```
y_r + i y_i = f(Real(W x)) + i f(Imag(W x)) 
= f( W_r x_r - W_i x_i) + i f(W_r x_i + W_i x_r)
= f(   (W_r, W_i)^T . (x_r, -x_i)^T ) + i f(   (W_r, W_i)^T . (x_i, x_r)^T ) 
```
In the last line you see that you can represent the complex weight kernel as `W_r` and `W_i` stacked on top of each other.
Therefore you can represent this complex forward projection as the following set of operations:
```
Assume N = output size of each perceptron
  x_r = tf.real(x)
  x_i = tf.imag(x)
  x_1 = tf.concat([x_r, -x_i], axis=0)
  x_2 = tf.concat([x_i, x_r], axis=0)
  layer_1 = tf.keras.layers.Dense(N)
  # use the same layer twice and the kernel will represent (W_r, W_i)^T
  y_r = layer_1(x_1)
  y_i = layer_1(x_2)
  # to add more layers again for x_1 and x_2 from y_r and y_i
  x_1 = tf.concat([y_r, -y_i], axis=0)
  x_2 = tf.concat([y_i, y_r], axis=0)
  layer_2 = tf.keras.layers.Dense(N)
  z_r = layer_2(z_1)
  z_i = layer_2(z_2)
  ...
To combine outputs into complex you can always do tf.complex(real_part, imag_part)
The loss function must be real and can be loss(real_part) + loss(imag_part)
```

My observations are that since complex numbers are merely a particular container of two real numbers you are actually restricting yourself by choosing to use complex numbers. In general if you wanted to allow more complex patterns you should form an input `input = tf.concat([tf.real(x), tf.imag(x)], axis=-1)`.

**Comment by beniroquai** [comment]
Thanks for clarfying this. This might be a bit of off-topic, but what could be the best way to define a complex loss-function? Just imagine you compare imag/imag with real/real in your loss function or you do it with abs and phase of your complex number. There is a wrap-around problem with the phase at 2p, but maybe it's a better metric if it comes to stability. 

Maybe it's faster to optimize first for the magnitude 10 iterations and then for the phase, eventually you approach to you final result faster? I've just started to see these challenges. Are you familiar with this?

**Comment by Joshuaalbert** [comment]
Generally, doing it in phase and amplitude space is better because there are far fewer local minima, however then yes you have phase wrapping. If you do it in phase/amp space then you should solve phase first (mostly) before doing pase+amplitude. Phase errors are usually the most important. I'm curious what problem you are trying to solve?

**Comment by beniroquai** [comment]
The main use right now is for using inverse problems on a GPU. Especially everything which is related to light fields in optics.

**Comment by Joshuaalbert** [comment]
I see, a colleague of mine is doing adaptive optics and predicting phase screens.

**Comment by beniroquai** [comment]
Sounds cool. Did you publish anything on that already? I’m a bit curious :)

 

Von: Joshua George Albert <notifications@github.com>
Antworten an: tensorflow/tensorflow <reply@reply.github.com>
Datum: Donnerstag, 14. Dezember 2017 um 23:05
An: tensorflow/tensorflow <tensorflow@noreply.github.com>
Cc: beniroquai <bene.d@gmx.de>, Comment <comment@noreply.github.com>
Betreff: Re: [tensorflow/tensorflow] Optimizer classes do not support complex variables (#3032)

 

I see, a colleague of mine is doing adaptive optics and predicting phase screens.
