### ISSUE TITLE
TensofflowLite on Andoid: Didn't find op for builtin opcode 'CONV_2D' version '2'

### ISSUE THREAD

**Issue by MichalMisiaszek** [tensorflow/tensorflow#30332]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes, I am using custom Flutter plugin for Firebase Custom model
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): MacOS
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: Samsun S10 / Emulator
- TensorFlow installed from (source or binary): tf-nightly
- TensorFlow version (use command below): 1.14
- Python version: 3.7
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
Android library fails to load InceptionV3 model converted to TFLite.
```E/CustomCompatChecker(15099): The model is INCOMPATIBLE. It may contain unrecognized custom ops, or not FlatBuffer format: java.lang.IllegalArgumentException: Internal error: Cannot create interpreter: Didn't find op for built-in opcode 'CONV_2D' version '2'```
**Describe the expected behavior**
Model loaded. Simple models, or not optimized work. 

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.
1. Convert TF InceptionV3 to TFLite (with optimization for size)
2. Load model to Android device - fails sometimes not finding a matching model or the error above.
**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by jdduke** [comment]
You need a newer version of TensorFlow Lite, at least 1.14.0, which was just published this past week (https://bintray.com/google/tensorflow/tensorflow-lite/1.14.0).
