### ISSUE TITLE
tf.keras.datasets not batched correctly

### ISSUE THREAD

**Issue by ngc92** [tensorflow/tensorflow#30346]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code: yes
- OS Platform and Distribution Linux Mint 19
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): v2.0.0-beta0-16-g1d91213fe7 2.0.0-beta1
- Python version: 3.6

**Describe the current behavior**
Using the return values of `tf.keras.datasets.Cifar10` in `model.fit` seems to process the entire dataset in one batch, independent of the given batch size.

**Describe the expected behavior**
Both versions should take the same amount of time.

**Code to reproduce the issue**
```
from tensorflow import keras

(x, y), _ = keras.datasets.cifar10.load_data()
x = (x / 255.0).reshape(x.shape[0], -1)

model = keras.Sequential([keras.layers.Dense(10)])

# commenting out these lines result in way slower training
x = x[0:10]
y = y[0:10]

model.compile("sgd", "sparse_categorical_crossentropy")
model.fit(x, y, epochs=1, batch_size=1, steps_per_epoch=10)

```

**Other info / logs**
The example as written:
```
10/10 [==============================] - 0s 5ms/step - loss: 7.4634
```

and with the marked lines commented out:
```
10/10 [==============================] - 8s 786ms/step - loss: 5.7648
```

**Comment by gadagashwini** [comment]
I could reproduce the issue on Colab with Tensorflow version 2.0.0.beta1.

**Comment by omalleyt12** [comment]
@ngc92 the keras.datasets return NumPy arrays, by doing `x = x[0:10]` you are telling it to only look at 10 samples, otherwise it is looking at the whole data, `steps_per_epoch` is ignored for NumPy arrays and only used for Datasets
