### ISSUE TITLE
TensorFlow 1.14 artifacts on Maven Central?

### ISSUE THREAD

**Issue by maksim-m** [tensorflow/tensorflow#30348]
The latest version of [tensorflow](https://mvnrepository.com/artifact/org.tensorflow/tensorflow) and [tensorflow-android](https://mvnrepository.com/artifact/org.tensorflow/tensorflow-android) artifacts is 1.13.1. Will version 1.14.0 be published?

**Comment by rmothukuru** [comment]
@maksim-m ,
The Artifacts of Official Tensorflow for 1.14 is present in this [Github link](https://github.com/tensorflow/tensorflow/tree/r1.14/tensorflow). 

Artifacts for Tensorflow for Java and Andriod can be found in this [Github link](https://github.com/tensorflow/tensorflow/tree/r1.14/tensorflow/java)

**Comment by maksim-m** [comment]
Thanks for the reply, but the links you provide only contain the source code and build instructions,  not the artifacts (.jar and .aar files) for Java and Android. Thus, the users have to build TensorFlow themselves first. 

Prior to the release of version 1.14 there was always an official release of TensorFlow for Java and Android on Maven Central. Even [official documentation suggests](https://www.tensorflow.org/install/lang_java#tensorflow_with_apache_maven) to install TensorFlow for Java from Maven Central, but the artifacts for 1.14 are not uploaded there.

**Comment by tarhack** [comment]
I Maxim, 
I have this message when I test my installation :
Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
It's mean that i cannot use TensorFlow  on my system ?
Thx
Rick

**Comment by sistemas3-mv** [comment]
> 
> 
> Thanks for the reply, but the links you provide only contain the source code and build instructions, not the artifacts (.jar and .aar files) for Java and Android. Thus, the users have to build TensorFlow themselves first.
> 
> Prior to the release of version 1.14 there was always an official release of TensorFlow for Java and Android on Maven Central. Even [official documentation suggests](https://www.tensorflow.org/install/lang_java#tensorflow_with_apache_maven) to install TensorFlow for Java from Maven Central, but the artifacts for 1.14 are not uploaded there.

I join the @maksim-m 's request. I think its neccesary to upload the artifacts to Maven Central.

**Comment by tarhack** [comment]
Hi, 
Thx
I join the @maksim-m 's request. I think its neccesary to upload the artifacts to Maven Central.
(1.14.0)

**Comment by sjamesr** [comment]
I'm working on resolving a missing `android_buildinfo.json` artifact which is blocking the release to Maven.

**Comment by sjamesr** [comment]
I've uploaded artifacts for tensorflow to Maven Central, with the exception of tensorflow-android. There are some changes to how that artifact is released which are causing some delays, sorry about that!

**Comment by ssrp** [comment]
Hi @sjamer, thank you for adding 1.14.0 version to Maven. 

When will the tensorflow-android 1.14.0 be released on Maven Central? I'd like to use some operations in my application which are supported only in 1.14.0, such as GatherV2.

Thanks!

**Comment by sistemas3-mv** [comment]
> 
> 
> I found some issues with the 1.14.0 release of TF Java, I'm working on a 1.14.0.1 right now to fix those. This means 1.14.0 is not usable in its current form (at least on Mac and Linux).
> 
> Also working on an answer for tensorflow-android, no ETA right now.

Hi @sjamesr are there any updates about the Android package? 

I'm waiting for the release.

**Comment by mihaimaruseac** [comment]
There will be a 1.15 release soon with the usual release process (release candidates, final release) instead of trying to patch the broken 1.14. Sorry about that

**Comment by ssrp** [comment]
Hi @mihaimaruseac 
Thanks for the information! May I also ask when is the expected release date for tensorflow-android 1.15?
Thanks a lot

**Comment by mihaimaruseac** [comment]
They should be released at around the same time

**Comment by mihaimaruseac** [comment]
Hi @ssrp. There has been a release candidate for 1.15, can you please check that tensorflow-android is also released?

**Comment by maksim-m** [comment]
@mihaimaruseac it's not released on Maven Central. The latest version of tensorflow for Java is [1.14.0](https://mvnrepository.com/artifact/org.tensorflow/tensorflow) (which is not [usable in its current form](https://github.com/tensorflow/tensorflow/issues/30348#issuecomment-512922088)) and the latest version of tensorflow-android is [1.13.1](https://mvnrepository.com/artifact/org.tensorflow/tensorflow-android).

**Comment by ssrp** [comment]
Hi @mihaimaruseac, it is not released on Maven Central yet.
Also, I found the 1.15 artifacts of TF for Java and Android [here](https://github.com/tensorflow/tensorflow/tree/v1.15.0-rc1/tensorflow/java/) but I couldn't tell if it is updated (comparing with [1.14 Artifacts](https://github.com/tensorflow/tensorflow/tree/r1.14/tensorflow/java/)).

**Comment by mihaimaruseac** [comment]
Assigning @jdduke in this case

**Comment by jdduke** [comment]
Apologies for any confusion, we are no longer releasing TensorFlow Mobile Android artifacts on Maven. This can still be built from source, but it will not be part of the official release. TensorFlow Lite Maven artifacts for Android are available at the [usual link](https://mvnrepository.com/artifact/org.tensorflow/tensorflow-lite?repo=bt-google-tensorflow). Standard (desktop) TensorFlow artifacts for 1.14 [have been published](https://mvnrepository.com/artifact/org.tensorflow/tensorflow), and should be published with future releases.
