### ISSUE TITLE
Using pre trained tflite model on android

### ISSUE THREAD

**Issue by ramrahu** [tensorflow/tensorflow#30349]
Hello,
I have been trying to use your pre trained .tflite model on android app. Its giving me the following error:
java.lang.IllegalArgumentException: Cannot convert between a TensorFlowLite tensor with type FLOAT32 and a Java object of type [I (which is compatible with the TensorFlowLite type INT32)
This is when I use the command tfLite.runForMultipleInputsOutputs(inputArray, outputScoresNames); to run the model
If I use tfLite.run(inputs, outputScores); to run the model, it executes without error but always outputs only the first character in the list.
Could anyone help me with this error??
Thanks in advance.

**Comment by gadagashwini** [comment]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- TensorFlow installed from (source or binary):
- TensorFlow version (or github SHA if from source):


**Provide the text output from tflite_convert**

```
# Copy and paste here
```

Also, please include a link to a GraphDef or the model if possible.

**Any other info / logs**

Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by gadagashwini** [comment]
@ramrahu Please fill the above template to expedite the trouble-shooting process. 
We ask for this in the issue submission template, because it is really difficult to help without that information. Thanks!

**Comment by ramrahu** [comment]
**System information**

OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 14.04
TensorFlow installed from (source or binary): Source
TensorFlow version (or github SHA if from source): 1.13

**Provide the text output from tflite_convert**
I didn't use tflite_convert. I was just trying a pre trained tflite model to check if the app is functioning fine, but it was causing the above mentioned problem.

**Comment by jdduke** [comment]
Which model are you using? Can you provide an exact link? And what is the type of `inputArray` and `outputScoresNames`?

**Comment by ramrahu** [comment]
These are the tyoes:
**Object[] inputArray = {floatInputBuffer, sampleRateList};
Map<Integer, Object> outputScoresNames = new HashMap<>();
    outputScoresNames.put(0, outputScores);**
I have used the pretrained model mentioned in this link:
https://github.com/mozilla/DeepSpeech
I downloaded using this command mentioned in the link: **wget https://github.com/mozilla/DeepSpeech/releases/download/v0.5.1/deepspeech-0.5.1-models.tar.gz**

**Comment by jdduke** [comment]
Right, but what are the types of `floatInputBuffer`, `sampleRateList` and `outputScores`?

**Comment by ramrahu** [comment]
floatInputBuffer is float, sampleRateList is int and outputScores is float

**Comment by jdduke** [comment]
I believe the sampleRateList should also be a float array. You can inspect the graph inputs/ouputs using our [visualization tool](https://www.tensorflow.org/lite/guide/faq#how_do_i_inspect_a_tflite_file) or with something like [Netron](https://electronjs.org/apps/netron).

**Comment by ramrahu** [comment]
ok thanks will have a look at it. how about the run() function I mentioned in my first question? It doesn't give any error. It gives a result but the result contains only a single character repeated multiple times.

**Comment by ramrahu** [comment]
> I believe the sampleRateList should also be a float array. You can inspect the graph inputs/ouputs using our [visualization tool](https://www.tensorflow.org/lite/guide/faq#how_do_i_inspect_a_tflite_file) or with something like [Netron](https://electronjs.org/apps/netron).

Hi this suggestion solved that error. But I am getting a new error now
**java.lang.IllegalStateException: Internal error: Unexpected failure when preparing tensor allocations: tensorflow/lite/kernels/concatenation.cc:68 t->dims->size != t0->dims->size (1 != 2)Node number 27 (CONCATENATION) failed to prepare.**
Any idea how to fix this??

**Comment by jdduke** [comment]
What are the dimensions of your inputs? I believe the model requires 4 inputs, but I see you only provide 2 (input_node[1,16,19,26], previous_state_c[1,2048], previous_state_h[1,2048], input_samples[512]).

**Comment by ramrahu** [comment]
The ones that you mentioned are the dimensions. I've attached my code file. Maybe you will be able to help me better in clearing the error. And apologies I forgot to mention one thing. I changed the model from the pretrained model to my model. I trained the same architecture mentioned above with my data. The latest error I posted is from my model. I've commented the lines giving me the error.
public class SpeechActivity extends Activity {
  private static final float SAMPLE_RATE = 16000;
  private static final int SAMPLE_DURATION_MS = 5000;
  private static final int RECORDING_LENGTH = (int) (SAMPLE_RATE * SAMPLE_DURATION_MS / 1000);
  private static final String MODEL_FILENAME = "file:///android_asset/output_graph_240hrs.tflite";

    private static final char[] map = new char[]{'0', ' ', 'a', 'b', 'c', 'd', 'e', 'f', 'g',
            'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q',
            'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z','\''};

  // UI elements.
  private static final int REQUEST_RECORD_AUDIO = 13;
  private Button startButton;
  private TextView outputText;
  private static final String LOG_TAG = SpeechActivity.class.getSimpleName();

  // Working variables.
  short[] recordingBuffer = new short[RECORDING_LENGTH];
  int recordingOffset = 0;
  boolean shouldContinue = true;
  private Thread recordingThread;
  boolean shouldContinueRecognition = true;
  private Thread recognitionThread;
  private final ReentrantLock recordingBufferLock = new ReentrantLock();
  //private TensorFlowInferenceInterface inferenceInterface;
  private Interpreter tfLite;

  private static MappedByteBuffer loadModelFile(AssetManager assets, String modelFilename)
          throws IOException {
    AssetFileDescriptor fileDescriptor = assets.openFd(modelFilename);
    FileInputStream inputStream = new FileInputStream(fileDescriptor.getFileDescriptor());
    FileChannel fileChannel = inputStream.getChannel();
    long startOffset = fileDescriptor.getStartOffset();
    long declaredLength = fileDescriptor.getDeclaredLength();
    return fileChannel.map(FileChannel.MapMode.READ_ONLY, startOffset, declaredLength);
  }

  @Override
  protected void onCreate(Bundle savedInstanceState) {
    // Set up the UI.
    super.onCreate(savedInstanceState);
    setContentView(R.layout.activity_speech);
    startButton = (Button) findViewById(R.id.start);
    startButton.setOnClickListener(
        new View.OnClickListener() {
          @Override
          public void onClick(View view) {

              startRecording();
          }
        });
    outputText = (TextView) findViewById(R.id.output_text);

    String actualModelFilename = MODEL_FILENAME.split("file:///android_asset/", -1)[1];

    // Load the Pretrained WaveNet model.
    //inferenceInterface = new TensorFlowInferenceInterface(getAssets(), MODEL_FILENAME);
    try {
      tfLite = new Interpreter(loadModelFile(getAssets(), actualModelFilename));
    } catch (IOException e) {
      e.printStackTrace();
    }

    tfLite.resizeInput(0, new int[] {RECORDING_LENGTH, 1});
    //tfLite.resizeInput(1, new int[] {1});

    requestMicrophonePermission();
  }

  private void requestMicrophonePermission() {
    requestPermissions(
        new String[] {android.Manifest.permission.RECORD_AUDIO}, REQUEST_RECORD_AUDIO);
  }

  @Override
  public void onRequestPermissionsResult(
      int requestCode, String[] permissions, int[] grantResults) {
    if (requestCode == REQUEST_RECORD_AUDIO
        && grantResults.length > 0
        && grantResults[0] == PackageManager.PERMISSION_GRANTED) {
    }
  }

  public synchronized void startRecording() {
    if (recordingThread != null) {
      return;
    }
    shouldContinue = true;
    recordingThread =
        new Thread(
            new Runnable() {
              @Override
              public void run() {
                record();
              }
            });
    recordingThread.start();
  }

  private void record() {
    android.os.Process.setThreadPriority(android.os.Process.THREAD_PRIORITY_AUDIO);

    // Estimate the buffer size we'll need for this device.
    int bufferSize =
        AudioRecord.getMinBufferSize(
                (int) SAMPLE_RATE, AudioFormat.CHANNEL_IN_MONO, AudioFormat.ENCODING_PCM_16BIT);
    if (bufferSize == AudioRecord.ERROR || bufferSize == AudioRecord.ERROR_BAD_VALUE) {
      bufferSize = (int) (SAMPLE_RATE * 2);
    }
    short[] audioBuffer = new short[bufferSize / 2];

    AudioRecord record =
        new AudioRecord(
            MediaRecorder.AudioSource.DEFAULT,
                (int) SAMPLE_RATE,
            AudioFormat.CHANNEL_IN_MONO,
            AudioFormat.ENCODING_PCM_16BIT,
            bufferSize);

    if (record.getState() != AudioRecord.STATE_INITIALIZED) {
      Log.e(LOG_TAG, "Audio Record can't initialize!");
      return;
    }

    record.startRecording();

    Log.v(LOG_TAG, "Start recording");


    while (shouldContinue) {
      int numberRead = record.read(audioBuffer, 0, audioBuffer.length);
        Log.v(LOG_TAG, "read: " + numberRead);
      int maxLength = recordingBuffer.length;
      recordingBufferLock.lock();
      try {
          if (recordingOffset + numberRead < maxLength) {
              System.arraycopy(audioBuffer, 0, recordingBuffer, recordingOffset, numberRead);
          } else {
              shouldContinue = false;
          }
        recordingOffset += numberRead;
      } finally {
        recordingBufferLock.unlock();
      }
    }
    record.stop();
    record.release();
    startRecognition();
  }

  public synchronized void startRecognition() {
    if (recognitionThread != null) {
      return;
    }
    shouldContinueRecognition = true;
    recognitionThread =
        new Thread(
            new Runnable() {
              @Override
              public void run() {
                recognize();
              }
            });
    recognitionThread.start();
  }

  private void recognize() {
    Log.v(LOG_TAG, "Start recognition");

    short[] inputBuffer = new short[RECORDING_LENGTH];
    float[][] floatInputBuffer = new float[1][RECORDING_LENGTH];
    float[][] outputScores = new float[16][map.length];
    //String[] outputScoresNames = new String[]{OUTPUT_SCORES_NAME};
    float[] sampleRateList = new float[] {SAMPLE_RATE};
    Map<Integer, Object> outputScoresNames = new HashMap<>();
    outputScoresNames.put(0, outputScores);


      recordingBufferLock.lock();
      try {
        int maxLength = recordingBuffer.length;
          System.arraycopy(recordingBuffer, 0, inputBuffer, 0, maxLength);
      } finally {
        recordingBufferLock.unlock();
      }

      // We need to feed in float values between -1.0 and 1.0, so divide the
      // signed 16-bit inputs.
      for (int i = 0; i < RECORDING_LENGTH; ++i) {
        floatInputBuffer[0][i] = inputBuffer[i] / 32767.0f;
      }

      //MFCC java library.
      /*MFCC mfccConvert = new MFCC();
      float[] mfccInput = mfccConvert.process(floatInputBuffer);
      Log.v(LOG_TAG, "MFCC Input======> " + Arrays.toString(mfccInput));*/

      Object[] inputArray = {floatInputBuffer, sampleRateList};

      // Run the model.
      //inferenceInterface.feed(INPUT_DATA_NAME, mfccInput, 1, 157, 20);
      //inferenceInterface.run(outputScoresNames);
      //inferenceInterface.fetch(OUTPUT_SCORES_NAME, outputScores);
      //tfLite.runForMultipleInputsOutputs(inputArray, outputScoresNames); //error
      tfLite.run(floatInputBuffer, outputScores); //error
      Log.v(LOG_TAG, "OUTPUT======> " + Arrays.toString(outputScores));
      //Output the result.
      String result = "";
      for (int i = 0; i<outputScores.length; i++) {
          for (int j = 0; j<outputScores[i].length; j++) {
              if (outputScores[i][j] == 0)
                  break;
              result += map[Math.round(outputScores[i][j])];
          }
      }
      final String r = result;
      this.runOnUiThread(new Runnable() {
          @Override
          public void run() {
              outputText.setText(r);
          }
      });
      Log.v(LOG_TAG, "End recognition: "+result);
    }
}

**Comment by jdduke** [comment]
> . I changed the model from the pretrained model to my model. I trained the same architecture mentioned above with my data. 

Are your inputs/outputs identical to the DeepSpeech model?

**Comment by jdduke** [comment]
Part of the problem here is that you're trying to plug in the DeepSpeech model into the SpeechRecognition sample, which is using a *very* different model. These models take different inputs and provide different outputs.

**Comment by jdduke** [comment]
This question would be better served asking on StackOverflow. It doesn't appear to be an issue with TensorFlow Lite, but in how you're using TensorFlow Lite.

**Comment by ramrahu** [comment]
> > . I changed the model from the pretrained model to my model. I trained the same architecture mentioned above with my data.
> 
> Are your inputs/outputs identical to the DeepSpeech model?

Sorry for late response. Yes it is the same.
