### ISSUE TITLE
Can tensorflow support alluxio as storage filesystem?

### ISSUE THREAD

**Issue by myg821561935** [tensorflow/tensorflow#30347]
hello，
   As a storage middle tier, alluxio can mount file systems such as hdfs, nfs, etc., while providing efficient caching capabilities. If tensorflow supports reading data directly from alluxio, it would be very beneficial.

**Comment by haoyuan** [comment]
Hi @myg821561935 , you can find instruction about how to do this here: https://docs.alluxio.io/os/user/stable/en/compute/Tensorflow.html

@BinFan

**Comment by ravikyram** [comment]
@myg821561935  Did you get a chance to see the instructions suggested by haoyuan. Thanks!

**Comment by ravikyram** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
