### ISSUE TITLE
[TF 1.14 Keras] probably bug in network._map_graph_network

### ISSUE THREAD

**Issue by ziky90** [tensorflow/tensorflow#30357]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): 
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Both OS-X and Ubuntu
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): 1.14.0 binary
- TensorFlow version (use command below): 1.14
- Python version: 3.6.
- Bazel version (if compiling from source): NA
- GCC/Compiler version (if compiling from source): NA
- CUDA/cuDNN version: NA
- GPU model and memory: NA

**Describe the current behavior**
I have a CNN model that works well with tensorflow==1.13.1 (building the network, training the network and predicting from the network), but after the update to tensorflow==1.14.0 I'm getting following exception:

```
ValueError: Graph disconnected: cannot obtain value for tensor Tensor("dropout_1/cond/Merge:0", shape=(?, 160, 160, 16), dtype=float32) at layer "concatenate". The following previous layers were accessed without issue: ['net_input', 'initial_conv2D', 'batch_normalization', 'activation', 'conv2d', 'dropout']
```

**Other info / logs**
After debugging and going through the implementation of `network._map_graph_network` it seems to me that there is either some bug (significantly changed behaviour between tensorflow==1.13.1 and tensorflow 1.14.0) in the graph disconnections checking.
When I run the code with tensorflow==1.13.1 the tensorboard graph looks as follows:
![Screenshot 2019-07-03 at 16 36 37](https://user-images.githubusercontent.com/1810839/60600754-134b8780-9db1-11e9-811f-7f36afdc4a77.png)
From this I'm not sure why layer dropout_1 (conditional dropout) is checked in the concatenate layer? I assume that droupout should have been checked there?

**Comment by mihaimaruseac** [comment]
Thank you for the report. Just a small clarifying question: can you also try against nightly version? I think this might have been fixed already, but I might be wrong.

**Comment by ziky90** [comment]
@mihaimaruseac I've tried it against tf-nightly and I'm getting exactly the same exception.

**Comment by mihaimaruseac** [comment]
I'll defer to the Keras team then, as I'm not sure where to go from here

**Comment by sedghi** [comment]
same problem here too

**Comment by ziky90** [comment]
@sedghi interesting, thank you, but unfortunately in my case workaround using `tf.concat`, at least as `Lambda` layer does not work for me. I'm still getting the same error message.

**Comment by ziky90** [comment]
very much related to https://github.com/tensorflow/tensorflow/issues/30355

**Comment by ziky90** [comment]
I'm further proceeding in debugging. It currently looks like in the case when layer is an input to more than one concatenation than following strange thing happen:

My testing graph (NOTE: tensorboard printed from tensorflow==1.13.2)
![Screenshot 2019-10-11 at 12 16 34](https://user-images.githubusercontent.com/1810839/66657009-6306de00-ec3f-11e9-94c4-02dbde6f4b87.png)

For some reason concatenate layer in the red circle has correctly 2 input layer, but incorrectly 3 input tensors:
![Screenshot 2019-10-11 at 14 26 07](https://user-images.githubusercontent.com/1810839/66657129-93e71300-ec3f-11e9-8dc8-17652e3ea542.png)

I've noticed both of this in `_map_graph_network` and inside in `build_map` function. From this I assume that the bug is not in `network._map_graph_network` function, but somewhere in the construction of the graph.

Does anybody has some idea where should I look further? It seems to me that there might be some problem in the `keras.engine.Layer` `keras.layer.merge._Merge` or maybe somewhere else? Any suggestions @mihaimaruseac @fchollet

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.
