### ISSUE TITLE
TensorFlow C binding for Raspberry Pi

### ISSUE THREAD

**Issue by marianopeck** [tensorflow/tensorflow#30359]
**System information**
- TensorFlow version (you are using): 1.13.1
- Are you willing to contribute it (Yes/No): yes, at least as a tester

**Describe the feature and the current behavior/state.**
I asked on [StackOverflow if there was a TensorFlow C binding for ARM/RaspberryPi](https://stackoverflow.com/questions/56837317/how-can-i-get-a-tensorflow-c-binding-for-raspberry-pi) but I got no answer after many days. 

I couldn't find anything on the website, so I suspect this is not yet available? 

If it is just a matter that you don't distribute the binaries, I have no troubles to compile it myself if I have the instructions and if it is known to work. But I haven't found anything confirming that either. 

**Will this change the current api? How?**
No

**Who will benefit with this feature?**
All language bindings that use the C library and want to run on any ARM board

**Any Other info.**

**Comment by freedomtan** [comment]
The last paragraph of the "[TensorFlow for C](https://www.tensorflow.org/install/lang_c)" you cited points to a [how-to](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/lib_package/README.md) file which does show you how to build TensorFlow C API from source code with `bazel`

**Comment by marianopeck** [comment]
Thanks @freedomtan. I didn't know if something special compilation was needed for ARM. Are you aware of people/projects compiling it and using successfully?

**Comment by freedomtan** [comment]
something like

```
CC=clang-6.0 CXX=clang++-6.0 \
bazel build --config opt --local_resources 1024.0,0.5,0.5 \
--copt=-mfpu=neon-vfpv4 \
--copt=-ftree-vectorize \
--copt=-funsafe-math-optimizations \
--copt=-ftree-loop-vectorize \
--copt=-fomit-frame-pointer \
--copt=-DRASPBERRY_PI \
--host_copt=-mfpu=neon-vfpv4 \
--host_copt=-ftree-vectorize \
--host_copt=-funsafe-math-optimizations \
--host_copt=-ftree-loop-vectorize \
--host_copt=-fomit-frame-pointer \
--host_copt=-DRASPBERRY_PI \
//tensorflow/tools/lib_package:libtensorflow
```
works for me.

**Comment by ravikyram** [comment]
@marianopeck Just to verify did you get a chance to follow instructions as suggested by freedomtan .Thanks!

**Comment by marianopeck** [comment]
Hi @ravikyram 
Not yet. I will see if I can try it this week. 
BTW, if there is a compilation instruction and people claim it works, any reason why the binaries are not officially distributed as the rest of the  "TensorFlow for C"?

**Comment by marianopeck** [comment]
Hi @freedomtan 
Which version did you use? It's 2.0? Or older too? I would like to try with 1.13.1 or similar. 
Thanks

**Comment by freedomtan** [comment]
@marianopeck I use master branch most of the time. I think it works on TensorFlow versions before 1.10 to current master.

**Comment by marianopeck** [comment]
Hi @freedomtan 
Thanks, I am trying now to compile it myself but I wasn't even able to compile `bazel` on the first place :(    I am getting this issue: https://github.com/bazelbuild/bazel/issues/8882
If I am able to pass that, I will continue..

**Comment by freedomtan** [comment]
@marianopeck I haven't tried newer bazel, general comment is to increase your swap space and maximum Java heap size (e.g., `-J-Xmx1024m` instead of `-J-Xmx512m`)

**Comment by marianopeck** [comment]
Hi, as I found no binary available, I had to manage myself.
I finally took the time to [write down everything I found during my attempt to get TensorFlow C library compiled for Raspberry Pi](https://dev.to/martinezpeck/challenge-accepted-build-tensorflow-c-binding-for-raspberry-pi-in-2019-4f89). In that tutorial, I point back to this issue in case any progress is made. 
Thank you

**Comment by freedomtan** [comment]
good to see another effort on Smalltalk + TensorFlow. Smalltalk is one of my favorite language. I tried [Pharo bindings for TensorFlow](https://github.com/PolyMathOrg/libtensorflow-pharo-bindings) before and was able to use both TensorFlow C API and TensorFlow Lite C API on x86 machines

**Comment by marianopeck** [comment]
Hi @freedomtan 
We are in the same boat then :)  That's great to hear. The Pharo bindings are actually a port made by @SergeStinckwich  from the [work done on Cuis Smalltalk](https://github.com/Cuis-Smalltalk/Machine-Learning). The latter was mostly done by @gerasdf and he is now doing most of the [port to VASmalltalk](https://github.com/vasmalltalk/tensorflow-vast).
I am interested in hearing about your experiments. To avoid making noise in this issue, I will send you an email.
Thanks!

**Comment by SergeStinckwich** [comment]
hi @marianopeck, @freedomtan already have done some contributions to the Pharo port.
Yes all on the same boat, let's try to go in the same direction :-) Let's discuss about that in ESUG 2019 ?

**Comment by marianopeck** [comment]
OK, I sent you both and the rest of the involved parts a private email to so that we can continue discussing :)

**Comment by PINTO0309** [comment]
Although I do not have C language implementation skills, I tried to generate a binary for RaspberryPi of Tensorflow v1.14.0. I have not confirmed the operation.
https://github.com/PINTO0309/Tensorflow-bin.git

**Comment by marianopeck** [comment]
That worked perfectly!!

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.
