### ISSUE TITLE
Compiling custom GPU operation on Microsoft Windows 10

### ISSUE THREAD

**Issue by alayu** [tensorflow/tensorflow#30356]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Microsoft Windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): Source
- TensorFlow version: 1.12.3
- Python version: 3.5.0
- Installed using virtualenv? pip? conda?: conda
- Bazel version (if compiling from source): 0.17.2
- GCC/Compiler version (if compiling from source): 7.4.0
- CUDA/cuDNN version: 9
- GPU model and memory: NVIDIA Quadro P100

**Describe the problem**
I've been trying to get a custom operation working with a Windows version of TensorFlow GPU version from the guide: https://www.tensorflow.org/guide/extend/op#compiling_the_kernel_for_the_gpu_device

**Provide the exact sequence of commands / steps that you executed before running into the problem**

1. Clone the repository:

```powershell
git clone https://github.com/tensorflow/tensorflow.git 
```

I put my C++ implementation of sqrt_kernels.cc, sqrt.h, and sqrt_kernels.cu.cc in tensorflow\tensorflow\core\user_ops

**sqrt_kerenls.cc**
```c++
#if GOOGLE_CUDA
#define EIGEN_USE_GPU
#endif

#include "sqrt.h"
#include <math.h>
#include "tensorflow/core/framework/op_kernel.h"

using namespace tensorflow;

using CPUDevice = Eigen::ThreadPoolDevice;
using GPUDevice = Eigen::GpuDevice;

// CPU specialization of actual computation
template <typename T>
struct SqrtFunctor<CPUDevice, T>{

    void operator()(const CPUDevice& d, int size, const T* in, T* out){
        for(int i = 0; i < size; ++i){
            out[i] = sqrt(in[i]);
        }
    }
};

//Opkernel definition
//template paramter T is datatype of tensors

template <typename Device, typename T>
class SqrtOp : public OpKernel {
    public:
     explicit SqrtOp(OpKernelConstruction* context) : OpKernel(context) {}

     void Compute(OpKernelContext* context) override {

         const Tensor& input_tensor = context->input(0);

         Tensor* output_tensor = NULL;

         OP_REQUIRES_OK(context, context->allocate_output(0, input_tensor.shape(), &output_tensor));

         OP_REQUIRES(context, input_tensor.NumElements() <= tensorflow:kint32max, errors::InvalidArgument("Too many elements in tensor"));

         SqrtFunctor<Device, T>(){
             context->eigen_device<Device>(),
             static_cast<int>(input_tensor.NumElements()),
             input_tensor.flat<T>().data(),
             output_tensor->flat<T>().data());
         }
     }

};

//Register the Kernels
#define REGISTER_CPU(T)                     \
 REGISTER_KERNEL_BUILDER(                   \
        Name("Sqrt").Device(DEVICE_CPU).TypeConstraint<T>("T"), \
        SqrtOp<CPUDevice, T>);
 REGISTER_CPU(float);
 REGISTER_CPU(int32);

#ifdef GOOGLE_CUDA
#define REGISTER_GPU(T)
 extern template struct SqrtFunctor<GPUDevice, T>;   \
REGISTER_KERNEL_BUILDER(
    Name("Sqrt").Device(DEVICE_GPU).TypeConstraint<T>("T"), \
    SqrtOp<GPUDevice, T>);
REGISTER_GPU(float);
REGISTER_GPU(int32);
#endif
}
}
```

**sqrt_kenels.cu.cc**
```c++
#if GOOGLE_CUDA

#define EIGEN_USE_GPU

#include "sqrt.h"
#include "tensorflow/core/util/cuda_kernel_helper.h"


using namespace tensorflow;

using GPUDevice = Eigen::GpuDevice;

template <typename T>

__global__ void SqrtCudaKernel(const int size, const T* in, T* out){

    for(int i = blockIdx.x * blockDim.x + threadIdx.x; i < size; i += blockDim.x * gridDim.x){

        out[i] = sqrt(ldg(in + i));
    }
}

template <typename T>
struct SqrtFunctor<GPUDevice, T> {
    void operator()(const GPUDevice& d, int size, const T* in, T* out){

        int block_count = 1024;
        int thread_per_block = 20;

        SqrtCudaKernel<T> <<<block_count, thread_per_block, 0, d.stream()>>>(size,in,out);

    }
};

template struct SqrtFunctor<GPUDevice, float>;
template struct SqrtFunctor<GPUDevice, int32>;
}
}

#endif
```
**sqrt.h**

```c++
#ifndef SQRT_H_
#define SQRT_H_

namespace tensorflow {

namespace functor{


template <typename Device, typename T>

struct SqrtFunctor{
    void operator()(const Device&d, int size, const T* in, T* out);
};

#if GOOGLE_CUDA

template <typename Eigen::GpuDevice, typename T>
struct SqrtFunctor{
    void operator()(const Eigen::GpuDevice & d, int size, const T* in, T* out);
};
#endif

}

}

#endif
```

2. Afterwards I configure and built the tensorflow library by using bazel:

```powershell
python ./configure.py
```

3.  This is where I get my error after running this command:

```powershell
nvcc -std=c++11 -c -o cuda_op_kernel.cu.o cuda_op_kernel.cu.cc \
  ${TF_CFLAGS[@]} -D GOOGLE_CUDA=1 -x cu -Xcompiler -fPIC
nvcc warning : The -std=c++11 flag is not supported with the configured host compiler. Flag will be ignored.
sqrt_kernels.cu.cc
cl : Command line warning D9002 : ignoring unknown option '-fPIC'
sqrt_kernels.cu.cc
C://Users//alayu//AppData//Local//Programs//Python//Python35//lib//site-packages//tensorflow//include\third_party/eigen3/unsupported/Eigen/CXX11/Tensor(1): fatal error C1083: Cannot open include file: 'unsupported/Eigen/CXX11/Tensor': No such file or directory
```

I found the file "unsupported/Eigen/CXX11/Tensor'" in the path that it said it couldn't find it in, so I don't know what the error could be. Does nvcc require a specific gcc version? If it requires me to downgrade, I had originally used cygwin to install the latest version and it doesn't seem like they include older versions in their installer.

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by mrry** [comment]
Reassigning this to @gunan, as I'm not familiar with the current state of the Windows build.

**Comment by gunan** [comment]
Yifei is actively working on custom op support on windows.
She may have some updates.

**Comment by sanatmpa1** [comment]
@alayu,

We are checking to see if you still need help on this issue.You can checkout this detailed [guide](https://www.tensorflow.org/guide/create_op?hl=lt_Dowloand) which helps you in creating custom operation.

We recommend that you upgrade to `2.6` which is latest stable version of TF and let us know if the issue still persists in newer versions. Thanks!
