### ISSUE TITLE
UnboundLocalError when TF_NewSessionOptions fails in session.py

### ISSUE THREAD

**Issue by yaroslavvb** [tensorflow/tensorflow#3035]
The following fails with UnboundLocalError after https://github.com/tensorflow/tensorflow/commit/b80a4a8732dfcbbeb348b9f8470aa420bab3931b

```
session = tf.Session(tf.ConfigProto(log_device_placement=True))

Traceback (most recent call last):
  File "opts_error.py", line 3, in <module>
    session = tf.Session(tf.ConfigProto(log_device_placement=True))
  File "/Users/yaroslavvb/tfimmediate_hood/tensorflow/_python_build/tensorflow/python/client/session.py", line 880, in __init__
    super(Session, self).__init__(target, graph, config=config)
  File "/Users/yaroslavvb/tfimmediate_hood/tensorflow/_python_build/tensorflow/python/client/session.py", line 147, in __init__
    tf_session.TF_DeleteSessionOptions(opts)

UnboundLocalError: local variable 'opts' referenced before assignment

```

It's an incorrect usage of `Session`  I think it used to fail with a more informative message like ``*** TypeError: Expected binary or unicode string, got log_device_placement: true` before https://github.com/tensorflow/tensorflow/commit/b80a4a8732dfcbbeb348b9f8470aa420bab3931b

This commit moved creation inside the "try/finally" block, so real exception is swallowed, and this exception happens because "opts" right hand side doesn't get evaluated

**Comment by prb12** [comment]
This has been fixed.  It will take a little while to make it out into the GitHub repo.
