### ISSUE TITLE
How to get model predictions on all classes after applying Transfer Learning in TF2.0?

### ISSUE THREAD

**Issue by rishabhsahrawat** [tensorflow/tensorflow#30350]
I have been following [transfer learning with TFHub](https://www.tensorflow.org/beta/tutorials/images/hub_with_keras) to implement transfer learning in my model for text classification. In the example, I do not understand how to get probabilities for all the classes (1000 classes before + 5 classes after implementing transfer learning). At the end of the tutorial, they only show predictions on the 5 classes on which the model was re-trained, but I want to have probabilities also on the 1000 classes. I can not find any documentation or explanation on how to achieve this. If anyone has any ideas or some useful links, please feel free to share. THANK YOU!
This was my main question.

**About model, where I want to implement this idea of transfer learning.**
I have a text dataset of 8000 classes, since the data size is too big so it can not be loaded into the RAM of my machine. So I want to train on small-small sizes of data i.e. 4000 classes and 4000 classes. I trained my model freshly on 4000 classes first, the learned model gives me good results. Now I want to retrain the saved model on the rest 4000 classes using Transfer Learning (I am also open to any other way), but after doing a lot of google searches seems like it is impossible to retrain a model on new classes, at least in text classification. If you have read this part and have some suggestions or ideas please share them, I will be very thankful.

**Comment by ravikyram** [comment]
For faster resolution please post the issue on [TFHub](https://github.com/tensorflow/hub/issues)
repository.Thanks!

**Comment by rishabhsahrawat** [comment]
@ravikyram thank you for your suggestion, I posted the issue on [TFHub](https://github.com/tensorflow/hub/issues) and here is the [issue #328](https://github.com/tensorflow/hub/issues/328#issuecomment-508732983). Just in case someone is also looking for it.

**Comment by ravikyram** [comment]
@rishabhsahrawat Can i close this issue . We can follow-up the issue #328 on TFHub for the resolution. Thanks!
