### ISSUE TITLE
Bad inference on mobilenet quantized graph

### ISSUE THREAD

**Issue by joaolcaas** [tensorflow/tensorflow#30371]
Hi! I'm having some trouble about quantization on ssd_mobilenet_v1, doing inferences on raspberry Pi 3. I have trained this model using 2007voc dataset with the following comand:

```bash
python /models/research/object_detection/legacy/train.py \
		--train_dir $TRAIN_DIR \
		--pipeline_config_path "$TRAIN_DIR/pipeline.config"
```
And params '{"batch_size":8,"learning_rate":0.003}'.
To generate both frozen and quantized graph, i use the following comand:

```bash
/tensorflow/bazel-bin/tensorflow/tools/graph_transforms/transform_graph \
		--in_graph="$TRAIN_DIR/frozen_inference_graph.pb" \
		--out_graph="$TRAIN_DIR/quantized_graph.pb" \
		--inputs='image_tensor' \
		--outputs=MobilenetV1/Predictions/Reshape_1 \
		--transforms='
		quantize_weights'
```

Doing inferences using just the quantized graph, the result is really good. The model predict almost everything, with good bouding boxes. But, when i do inferences using the quantized graph, the bouding boxes look like this:
![my2](https://user-images.githubusercontent.com/23393117/60616312-8c45e180-9da7-11e9-9328-77d62e71b144.png)

I know the inference time is not equals when we compare both models. And i also know the mAP is note the same, but it is suposed to be that bad?

### Process information
- **The main process you can find [here](https://medium.com/nanonets/how-to-easily-detect-objects-with-deep-learning-on-raspberrypi-225f29635c74)**
- **I use for train:**
- Linux 16.04
- Core i7-4770s
- 16GB Ram
- **I use for Inference:**
- Raspberry Pi3

**Comment by ravikyram** [comment]
Can you please confirm the bad inference is on frozen_inference_graph.pb or quantized_graph.pb?.Also ,please let us know did you convert .pb model to Lite to see the inference on raspberry Pi 3. I .

**Comment by joaolcaas** [comment]
The bad inference happened on quantized_grap.pb. And i did not convert to lite. I used quantized_graph.pb to make inferences on raspberry using this [code](https://github.com/NanoNets/TF-OD-Pi-Test/blob/master/ObjectDetectionPredict.py). There is a way to convert to lite and run on raspberry? Anyway, i do not think that gonna solve my problem, once the bad inferences happened alredy on .pb quantized graph

**Comment by kumariko** [comment]
@joaolcaas Could you please let us know if this issue still persists ? If it is resolved then please feel free to move this issue to close status ?Thanks!
