### ISSUE TITLE
Tflite for microcontrollers : micro speech example with more keywords (yes, no, up, down ..) fails

### ISSUE THREAD

**Issue by saumpsh** [tensorflow/tensorflow#30376]
**System information**
- Have I written custom code : No
- OS Platform and Distribution : Linux Ubuntu 16.04 host machine with TensorFlow docker image
- Mobile device : SparkFun Edge Development Board
- TensorFlow installed from (source or binary): Source
- TensorFlow version : 1.14.0
- Python version: Python 2.7.15+
- Bazel version : 0.27 (apt repository)
- GCC/Compiler version : 7.4.0
- GPU model and memory: Nvidia GTX 1070

**Describe the current behavior**

I am trying to extend the [Micro Speech example](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/experimental/micro/examples/micro_speech) by adding more keywords such as 'yes, no, stop, go, up, down' etc. I followed the instructions for  training and converting the model to tflite format from the [Micro Speech GitHub page](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/experimental/micro/examples/micro_speech#creating-your-own-model). However, when I add my newly trained and converted 'tiny_conv_micro_features_model_data.cc' file to my project, compiling and running it on the Sparkfun Microcontroller gives the following error :

 '_Bad input tensor parameters in model_' . 

**More detail and analysis on the above problem**

I successfully compiled and ran the Micro Speech example on SparkFun Edge Development Board using [AI on a microcontroller with TensorFlow Lite and SparkFun Edge](https://codelabs.developers.google.com/codelabs/sparkfun-tensorflow/#0) tutorial.

Next, I trained the model for recognizing more ("yes,no,up,down")  keywords giving the following commands:

> bazel run -c opt --copt=-mavx2 --copt=-mfma --verbose_failures --host_force_python=PY2 tensorflow/examples/speech_commands:train -- \
--model_architecture=tiny_conv --window_stride=20 --preprocess=micro \
--wanted_words="yes,no,up,down" --silence_percentage=25 --unknown_percentage=25 --quantize=1

Then I added the newly created 'tiny_conv_micro_features_model_data.cc' file to the [micro_speech_test project](https://drive.google.com/file/d/1cawEQAkqquK_SO4crReDYqf_v7yAwOY8/view) in order to verify that the newly trained model works correctly. Compiling the project and running the binary gives the following error: 

![image](https://user-images.githubusercontent.com/36483321/60624860-310df200-9d9b-11e9-8fef-83cab23fc777.png)

This shows that interpreter requires an input tensor of shape: (1, 49, 43, 1), but the interpreter receives tensor of shape (1, 49, 40, 1) from the newly trained model. 

If the model is trained on input tensor of shape  (1, 49, 43, 1) as per the the [ spectrogram ](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/experimental/micro/examples/micro_speech#calculating-the-input-to-the-neural-network) of (49x43) pixels, how does the model interpreter of the micro speech project receives wrong shaped input tensor? 

Is it because we select input shape as (1, 49, 40, 1), while converting '.pb' file to '.tfilte' file by running the bazel command:

> bazel run tensorflow/lite/toco:toco -- \
--input_file=/tmp/tiny_conv.pb --output_file=/tmp/tiny_conv.tflite \
--input_shapes=1,49,40,1 --input_arrays=Reshape_1 --output_arrays='labels_softmax' \
--inference_type=QUANTIZED_UINT8 --mean_values=0 --std_values=9.8077

as per the instruction on [GitHub page](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/experimental/micro/examples/micro_speech#creating-your-own-model) If this is the reason why is the input shape been selected as (1,49,40,1) and not (1,49,43,1).

I also tried the above command by changing the input_shapes argument as --input_shapes=1,49,43,1. But this gives the following error:

![image](https://user-images.githubusercontent.com/36483321/60626163-c8c10f80-9d9e-11e9-9bff-b49f9a92cedb.png)

To verify that whether this error occurs due to adding more keywords to the wanted words argument (such as 'yes, no, up, down'), I trained the model only for 'yes,no' keywords. Still the same error and problem persisted as above.

I have not made any changes to the TensorFlow or micro speech example source files for the above experimentation. I just replaced the pre-existing 'tiny_conv_micro_features_model_data.cc' file by the new 'tiny_conv_micro_features_model_data.cc' file of the newly trained model for verifying my work.

Kindly guide me to solve my above problem.

Thanks.

**Comment by saumpsh** [comment]
Hi,

Can someone ( @petewarden @gadagashwini ) guide me to the solution of the above problem? It would be of great help.

Thank you.

**Comment by tuanphan09** [comment]
The input shape (1,49,40,1) is right which mean there are bugs in their code. 'tflite for microcontrollers' is on progress so you should update the source code. I re-generated 'micro_speech' from the source a week ago and it solved my problem!!!

**Comment by saumpsh** [comment]
Hi,

@tuanphan09 Thank you for helping me out. It solved my problem and now I am able to successfully compile and deploy my model to the microcontroller.

**Comment by piisku78** [comment]
@saumpsh What was your solution? I'm having the same problem...

**Comment by piisku78** [comment]
Thanks for the info. I installed locally nightly build instead of standard 1.14.0 and got it working.

tf-estimator-nightly 1.14.0.dev2019072901
tf-nightly           1.15.0.dev20190729

It think nightly builds have some TF operations which does not exist in 1.14.0

**Comment by FelipeWcosta** [comment]
Hello everyone, I am getting an error when I try to install depedences using '!pip install -q tf-estimator-nightly==1.14.0.dev2019072901 tf-nightly-gpu==1.15.0.dev20190729' in Google Colab. Does anyone know how I can fix this?
