### ISSUE TITLE
TensorFlow Lite Metadata samples

### ISSUE THREAD

**Issue by lutzroeder** [tensorflow/tensorflow#30387]
Are there any sample files or documentation how `metadata` and `metadata_buffer` in TensorFlow Lite models is used? @wangtz 494ed4d2100d94b3cca782d7134eac306d79d59b

**Comment by impjdi** [comment]
@lutzroeder 

Nope, not really.  We are using it for user-defined info at the moment.  For example, how to normalize (it's often hard to tell if you have a model with float input... should it be 0-255.f or -1f~1f or 0-1f etc.)  or how to interpret output (which of these 400 points corresponds to eyes, nose, lips etc. in a face mesh model).  All of these depends on the model and its author.  We don't have standardized methods to read from or write to it.
