### ISSUE TITLE
The GPU is not used after installed from source. 

### ISSUE THREAD

**Issue by jdxyw** [tensorflow/tensorflow#30389]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
Ubuntu 16.04.3 LTS
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
build from source
- TensorFlow version:
1.14
- Python version:
2.7
- Installed using virtualenv? pip? conda?:
pip
- Bazel version (if compiling from source):
0.24
- GCC/Compiler version (if compiling from source):
gcc 5.4
- CUDA/cuDNN version:
CUDA 9.0 cuDNN 7.0
- GPU model and memory:
Tesla K80

**Describe the problem**

**Provide the exact sequence of commands / steps that you executed before running into the problem**

`bazel build -c opt --config=cuda --config=mkl --config=nogcp --config=nohdfs --config=nokafka --config=noignite --config=nonccl //tensorflow/tools/pip_package:build_pip_package
./bazel-bin/tensorflow/tools/pip_package/build_pip_package /tmp/tensorflow_pkg
pip install /tmp/tensorflow_pkg/tensorflow-1.14.0-cp27-cp27mu-linux_x86_64.whl
`

After installing, I am trying to use the GPU to traning, get such error.

`2019-07-04 03:30:19.903538: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Could not dlopen library 'libcusolver.so.9.0'; dlerror: /usr/local/cuda/lib64/libcusolver.so.9.0: undefined symbol: GOMP_critical_end; LD_LIBRARY_PATH: /usr/lib64/openmpi/lib/:/usr/local/cuda/lib64:/usr/local/lib:/usr/lib:/usr/local/cuda/extras/CUPTI/lib64:/usr/local/mpi/lib:/lib/:`

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by jdxyw** [comment]
find the reason. the tf 1.14 need cuda 10.

**Comment by bonlime** [comment]
I have the same issue and it looks like the problem is much deeper. The same error appears when I build any TF 2.0 version with CUDA 9.0 support

**Comment by njzjz** [comment]
So, TensorFlow 1.14 does not support CUDA 9?

**Comment by bonlime** [comment]
@njzjz I tried building versions 1.13, 1.14.0, 1.14.2, 2.0.0beta0, 2.0.0beta1 on multiple machines but always got the same error `Could not dlopen library 'libcusolver.so.9.0'; dlerror: /usr/local/cuda/lib64/libcusolver.so.9.0: undefined symbol: GOMP_critical_end; ` 
I'm not really experienced in building things from source so I was unable to solve this problem

**Comment by bonlime** [comment]
just compiled TF `1.12.0` - everything works fine

**Comment by jdxyw** [comment]
rollback to 1.12.0 (CUDA 9.0), everything is ok now.

**Comment by bonlime** [comment]
@jdxyw  but it doesn't solve the original issue. Compiling `TF>=1.13` from source for CUDA 9 doesn't work.

**Comment by liyi193328** [comment]
meet the same issues , how to solve it ?

**Comment by bonlime** [comment]
@liyi193328 check the issue 30753 above. There is a solution there

**Comment by liyi193328** [comment]
@bonlime Got it, very tricky. Thanks a lot

**Comment by Ian09** [comment]
It seems if you have pytorch 1.10, and if you import torch before tensorflow, this problems does not appear and tf2.0 (build with cuda9) can work. I dont know why, but on my machine it works. Could anyone tell my the reason?
