### ISSUE TITLE
run bazel failed:FATAL: ExecuteProgram(C:\Users\Administrator/_bazel_Administrator/install/9470fb600225157f1e34c45c6d4dc834/_embedded_binaries/embedded_tools/jdk/bin/java.exe) failed: 6

### ISSUE THREAD

**Issue by cj741** [tensorflow/tensorflow#30390]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): win7
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:no
- TensorFlow installed from (source or binary):source
- TensorFlow version: 2.0
- Python version: 3.6
- Installed using virtualenv? pip? conda?:conda
- Bazel version (if compiling from source): 0.27
- GCC/Compiler version (if compiling from source):no
- CUDA/cuDNN version:no
- GPU model and memory:no

**Describe the problem**
After I installed bazel 0.27.1, I try to run the command "bazel", it show the error
"FATAL: ExecuteProgram(C:\Users\Administrator/_bazel_Administrator/install/9470fb600225157f1e34c45c6d4dc834/_embedded_binaries/embedded_tools/jdk/bin/java.exe) failed: 6"
but when move into the path "C:\Users\Administrator/_bazel_Administrator/install/9470fb600225157f1e34c45c6d4dc834/_embedded_binaries/embedded_tools/jdk/bin/", it is ok to run "bazel", do you have idea on it? and how to solve it.
Thanks,

**Provide the exact sequence of commands / steps that you executed before running into the problem**

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by gadagashwini** [comment]
@cj741 Just to verify, did you follow the steps mentioned in official [Tensorflow](https://www.tensorflow.org/install/source_windows) Website and did bazel installed properly? Thanks!

**Comment by cj741** [comment]
@gadagashwini  Thanks for your response, I have try to install bazel from Chocolatey and download the Bazel binary (bazel-<version>-windows-x86_64.exe), both of them are still have the same error.

**Comment by gadagashwini** [comment]
Could you downgrade Bazel to 0.26.0 as that is the max version allowed. Let us know if this resolves your problem. Thanks!

**Comment by cj741** [comment]
I have tried Bazel 0.23.0, since on the stackoverflow, someone say the higher versions are not work well with tensorflow, but still got the same problem.

**Comment by gunan** [comment]
From what I can see, this is a bazel bug.
Please reach out to bazel team.

**Comment by cj741** [comment]
ok, I send the problem to the bazel team, thanks~

**Comment by gadagashwini** [comment]
@cj741 Can you please let us know if you are happy to close this issue. Thanks!
