### ISSUE TITLE
TFLite on Android (JNI) gives inconsistent results when the input ByteBuffer is reused

### ISSUE THREAD

**Issue by aleist** [tensorflow/tensorflow#30393]
**System information**
- Have I written custom code: yes
- OS Platform and Distribution: Android 7.1 (compileSdkVersion 28)
- Mobile device: Galaxy S7 (custom ROM Android 7.1)
- TensorFlow version: TFLite 1.14.0

**Describe the current behavior**
I create a TFLite Interpreter and allocate a direct ByteBuffer in Java to process a sequence of images. I then copy image data into the buffer for inference, which runs in an AsyncTask with a serial executor, so the Interpreter and buffer are only used by one forward pass at a time.

Doing this the predictions sometimes (always?) relate to an earlier (possibly always the first) image in the sequence, not the current image. So things work reliably for the first image, but not for the following images.

I can circumvent this problem by allocating a new ByteBuffer for every frame. I'd like to avoid these frequent allocations, but more importantly I am having a hard time figuring out why I am getting this behaviour in the first place. It's almost like TFLite doesn't use the updated data in the buffer when it sees that the buffer reference hasn't changed.

**Describe the expected behavior**

I expect to be able to reuse the input ByteBuffer with updated contents across multiple inference calls.

**Comment by jdduke** [comment]
You should be able to reuse a ByteBuffer, as [that is what we do in all of our samples](https://github.com/tensorflow/examples/blob/master/lite/examples/image_classification/android/app/src/main/java/org/tensorflow/lite/examples/classification/tflite/Classifier.java#L84). When re-populating the ByteBuffer each frame, make sure you [rewind it first](https://github.com/tensorflow/examples/blob/master/lite/examples/image_classification/android/app/src/main/java/org/tensorflow/lite/examples/classification/tflite/Classifier.java#L230). You'll also need to make sure you provided that ByteBuffer to every Interpreter.run() call.

**Comment by aleist** [comment]
I update the ByteBuffer in a native library via JNI calls. The C++ code does not update the position or limit values, it simply retrieves the pointer and overwrites all RGB pixel values of the buffer, so rewind isn't necessary. This JNI call happens from the same AsyncTask instance that is also running inference. Here is the relevant code snippet run by AsyncTask.doInBackground. Variable `floatImage` is the ByteBuffer used for inference. The `outputMap` is newly allocated for this inference call.

      // Convert the image to float in range [-1, 1].
      Trace.beginSection("convertToFloat");
      try {
        Utils.convertImageToFloat(mInput, mInputWidth, mInputHeight, NUM_CHANNELS, 1f / 127.5f,
            -1f, floatImage);
      } catch (Exception e) {
        Log.e(TAG, mData.id, ": ", e.getMessage());
        return;
      } finally {
        Trace.endSection(); // convertToFloat
      }

      Trace.beginSection("inference");
      try {
        mTFLite.runForMultipleInputsOutputs(new Object[]{floatImage}, outputMap);
      } catch (Exception e) {
        Log.e(TAG, mData.id, ": ", e.getMessage());
        return;
      } finally {
        Trace.endSection(); // inference
      }

**Comment by jdduke** [comment]
Just curious, if you're using JNI to convert to a ByteBuffer in native code, why not simply use the native C++ APIs that we provide? Or is it for convenience in using the BinTray/JCenter .aars that we distribute?

Just confirming that your ByteBuffer is a direct ByteBuffer (allocateDirect())? Are you using the 1.14 .aar that we just published? Or a nightly build?

**Comment by aleist** [comment]
Yes I could have used the native APIs. It was simply familiarity with the JNI APIs, as I had used them before. Given that the input data is in a direct ByteBuffer (yes, allocated with `allocateDirect()`), the overhead seemed negligible.

I used the JCenter `implementation 'org.tensorflow:tensorflow-lite:1.13.1'` dependency previously, but for this model I needed TFLite 1.14.0 and the dependency wasn't available yet when I was working on this a couple of weeks ago. I ended up building libtensorflowlite.jar and libtensorflowlite_jni.so from the source revision tagged 1.14.0 in Git. I'll go back to using the dependency when I next touch this code.

I haven't spent any more time on this as it works correctly with a new ByteBuffer per frame, but I'm still at a loss as to what's causing the issues I encountered when reusing a single buffer.

**Comment by jdduke** [comment]
Yeah, this is very odd given that all of our samples reuse a persistent ByteBuffer across frames. The only difference is that we populate the (direct) ByteBuffer from Java, not from native.

In your native code, are you calling GetDirectBufferAddress() every single frame? Or are you caching the native pointer? If the latter, I'm not sure there are guarantees that the address will remain persistent for the duration of the ByteBuffer's lifetime.

**Comment by aleist** [comment]
Yes I call GetDirectBufferAddress() for every frame. The implementation of convertImageToFloat is very straight forward (with only a couple of checks omitted):

```
  const size_t inSize = static_cast<size_t>(height) * width * channels;
  const auto* inData = sns::bufferAs<const uint8_t>(env, image);
  auto* outData = sns::bufferAs<float>(env, out);
  if (!inData || !outData) return;

  for (size_t i = 0; i < inSize; i++) {
    outData[i] = static_cast<float>(inData[i]) * scale + add;
  }

template<class T>
T* bufferAs(JNIEnv* env, jobject buffer) {
  void* buf = env->GetDirectBufferAddress(buffer);
  if (buf == nullptr) {
    throwException(env, JEX_ILLEGAL_ARGUMENT, "Cannot access the buffer");
    return nullptr;
  }
  return reinterpret_cast<T*>(buf);
}
```

I'll experiment some more when I have time for it.
