### ISSUE TITLE
Reduction / Term Rewriting / Optimisation / etc.

### ISSUE THREAD

**Issue by sirinath** [tensorflow/tensorflow#304]
Can you add an optimisation layer which will do a global optimisation based on a pre defined set of rules  to ensure that the resulting DAG is the absolute minimised form (based on the set of rewiring rules) to transform the inputs to the the outputs or effects. Based on the domain or know ledge of the input data you can register new rules and also when adding new operation you should be able to add new rules.

Perhaps this can be part of the DSL (https://github.com/tensorflow/tensorflow/issues/70)

**Comment by sirinath** [comment]
Above can be further optimised using the effects and how they propagate and what the effects are on each node. Prima facie list of effects to tract in optimisation:

 - IO effects
 - Computational Operation Resource Consumption effects
 - Memory usage effects
 - Volatility / scheduling / ordering effects
 - Other user defined effects

So there a balance can be achived between computation, memory, in inevitable system calls, IO operation and buffering (back pressure management), etc. in a formal well defined manner.

**Comment by aselle** [comment]
Work on performance continues, especially in terms of optimization and balancing memory, cpu, distribution tradeoffs. This issue is extremely broad so so it is not practically actionable as a single issue. Since our roadmaps cover this issue, I am closing this for now.
