### ISSUE TITLE
how to use tensorflow::tensor in c++

### ISSUE THREAD

**Issue by maohuui** [tensorflow/tensorflow#30406]
python code:
 input_tensor = tf.placeholder(dtype=tf.float32, shape=[1, 256, 512, 3], name='input_tensor')
 phase_tensor = tf.constant(False, tf.bool)

c++ code:
tensorflow::Tensor input_tensor(tensorflow::DT_FLOAT, tensorflow::TensorShape({1, 256, 512, 3}));
    tensorflow::Tensor phase(tensorflow::DT_BOOL, tensorflow::TensorShape());
    phase.scalar<bool>()() = false;

this convertion is right?
who can help me?

**Comment by gadagashwini** [comment]
This is not Build/Installation or Bug/Performance issue. Please post this kind of support questions at [StackOverflow](http://stackoverflow.com/questions/tagged//tensorflow). There is a big community to support and learn from your questions. GitHub is mainly for addressing bugs in installation and performance. Thanks!

**Comment by gadagashwini** [comment]
Closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
