### ISSUE TITLE
Poor documentation of tf.saved_model.Builder

### ISSUE THREAD

**Issue by twatzl** [tensorflow/tensorflow#30408]
## URL(s) with the issue:
https://www.tensorflow.org/api_docs/python/tf/saved_model/Builder

## Description of issue (what needs changing):

The documentation is unclear on several points and especially hard to understand for people who are new to tensorflow.

### Clear description

What is the difference of using saved_model.Builder to other ways of exporting models and graphs? For someone just wanting to use a pre-trained tensorflow model it is very hard to get an overview over all the different types of formats etc. 

For example what is the difference to tf.io.write_graph? As far as I could find out I need to use the saved_model stuff, because it is able to add tags, which tf.io is not able to do and which is needed for serving. The docs are very unclear on the whole topic of how to use pre trained models in a custom application. (for example in https://github.com/tensorflow/models/blob/master/research/slim/export_inference_graph.py tf.io.write_graph is used)

There is also no data types given for the parameters so as someone new to TF I am absolutely unable to guess what should go there. The only description is foo_signatures and foo_assets, but there is no example showing how these parameters are properly used.

I managed to use saved_model.simple_save, but it is deprecated and from the documentation of the saved_model.Builder, I have no idea how I could replicate the same functionality as with simple_save.

### Usage example

There is example code, but there is no complete example on how to create a frozen graph or on how to export (and import again) a pre-trained model.

### Submit a pull request?

I am an absolute beginner to TF so I cannot correct the docs in a meaningful way. sorry

**Comment by rmothukuru** [comment]
@twatzl ,
If your goal is to replicate **tf.saved_model.simple_save**, you can use  **tf.compat.v1.saved_model.simple_save** instead. 

You can find clear documentation about Saved Model in the [Save And Restore section of TF Website](https://www.tensorflow.org/guide/saved_model#save_and_restore_models).

Please let us know if that helps.

**Comment by rmothukuru** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
