### ISSUE TITLE
Resolving Empty Clusters in tf.contrib.factorization.KMeans 

### ISSUE THREAD

**Issue by AhmadM-DL** [tensorflow/tensorflow#30405]
**System information**
- TensorFlow version : 1.14.0
- Are you willing to contribute it : If my time and my skills permit

**Describe the feature and the current behavior/state.**

Hi,
I am working on implementing a state-of-the-art deep learning architecture. The architecture requires applying KMeans algorithm on every epoch. However, the current graph generated by the "__init__" function in **tf.contrib.factorization.KMeans** doesn't support resolving empty clusters. I.e. it doesn't prevent the formation of empty clusters. 

The approach I want to implement is to assign a new cluster center for the empty cluster by perturbing a non-empty cluster center and assigning some points in the non_empty cluster to the empty one.

**Will this change the current API? How?**
Yup, by adding a new parameter to the KMeans "__init__" function.
The added parameter corresponds to whether the returned graph should support the prevention of empty clusters formation or no. Something like  a Boolean **prevent_empty_clusters**.

**Who will benefit with this feature?**
The feature will give the KMeans API users more options. Those who are interested in a KMeans algorithm that prevents empty clusters are the ones who will benefit. 

**Any Other info.**
No

**Comment by AhmadM-DL** [comment]
Any New Updates Related to this Issue

**Comment by alextp** [comment]
Contrib is no longer actively maintained, so closing this issue. Consider looking at the tf-addons package for a potential new home for your feature idea.
