### ISSUE TITLE
 I noticed that MonitoredSession is a very inefficient method.How to save the model according to the set conditions, not periodically.

### ISSUE THREAD

**Issue by mk123qwe** [tensorflow/tensorflow#30412]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**win10
- TensorFlow version (you are using):1.12
- Are you willing to contribute it (Yes/No):no

**Describe the feature and the current behavior/state.**
 I noticed that MonitoredSession is a very inefficient method.Saving the model periodically.
**Will this change the current api? How?**
Setting conditions to save the model, not periodically.
**Who will benefit with this feature?**
everyone
**Any Other info.**

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.
