### ISSUE TITLE
NCHW or NHWC when convert .pb into .tflite

### ISSUE THREAD

**Issue by luzhen1412** [tensorflow/tensorflow#30411]
**System information**
- OS Platform and Distribution :Linux Ubuntu 16.04
- TensorFlow installed from (source or binary):
- TensorFlow version (or github SHA if from source):1.13.1

**Provide the text output from tflite_convert**

Check failed: status.ok() Unexpected value for attribute 'data_format'. Expected 'NHWC'

**Any other info / logs**

The model I trained uses 'NCHW', such as my TF point - conv2d, which is in NCHW format. Now I want to convert frozen.pb to frozen. tflite. The above error occurred in the program. I want to know how I can successfully convert NCHW-formatted models to tflite when I only have frozen.pb. Thanks

**Comment by gargn** [comment]
Can you provide a minimally reproducible example? Either provide the frozen graph with the commands to convert the model, or provide a snippet of code that produces the same error.
