### ISSUE TITLE
TF2.0beta1+cudnn: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize

### ISSUE THREAD

**Issue by hgffly** [tensorflow/tensorflow#30421]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- TensorFlow installed from (source or binary): virtualenv and pip
- TensorFlow version (use command below): tensorflow-gpu 2.0.0-beta1
- Python version: 3.6.7
- GCC/Compiler version (if compiling from source): 7.4.0
- CUDA/cuDNN version: 7.6.0
- GPU model and memory:  GTX1660Ti, 6 GB

**Describe the current behavior**
UnknownError                              Traceback (most recent call last)
<ipython-input-1-df32bfd3ff54> in <module>
      1 import tensorflow as tf
----> 2 tf.keras.layers.Conv2D(10, 3)(tf.ones((1, 5, 5, 3)))

~/venv_tf2.0/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer.py in __call__(self, inputs, *args, **kwargs)
    710           with base_layer_utils.autocast_context_manager(
    711               input_list, self._mixed_precision_policy.should_cast_variables):
--> 712             outputs = self.call(inputs, *args, **kwargs)
    713           self._handle_activity_regularization(inputs, outputs)
    714           self._set_mask_metadata(inputs, outputs, input_masks)

~/venv_tf2.0/lib/python3.6/site-packages/tensorflow/python/keras/layers/convolutional.py in call(self, inputs)
    194 
    195   def call(self, inputs):
--> 196     outputs = self._convolution_op(inputs, self.kernel)
    197 
    198     if self.use_bias:

~/venv_tf2.0/lib/python3.6/site-packages/tensorflow/python/ops/nn_ops.py in __call__(self, inp, filter)
   1076 
   1077   def __call__(self, inp, filter):  # pylint: disable=redefined-builtin
-> 1078     return self.conv_op(inp, filter)
   1079 
   1080 

~/venv_tf2.0/lib/python3.6/site-packages/tensorflow/python/ops/nn_ops.py in __call__(self, inp, filter)
    632 
    633   def __call__(self, inp, filter):  # pylint: disable=redefined-builtin
--> 634     return self.call(inp, filter)
    635 
    636 

~/venv_tf2.0/lib/python3.6/site-packages/tensorflow/python/ops/nn_ops.py in __call__(self, inp, filter)
    231         padding=self.padding,
    232         data_format=self.data_format,
--> 233         name=self.name)
    234 
    235 

~/venv_tf2.0/lib/python3.6/site-packages/tensorflow/python/ops/nn_ops.py in conv2d(input, filter, strides, padding, use_cudnn_on_gpu, data_format, dilations, name, filters)
   1950                            data_format=data_format,
   1951                            dilations=dilations,
-> 1952                            name=name)
   1953 
   1954 

~/venv_tf2.0/lib/python3.6/site-packages/tensorflow/python/ops/gen_nn_ops.py in conv2d(input, filter, strides, padding, use_cudnn_on_gpu, explicit_paddings, data_format, dilations, name)
   1029             input, filter, strides=strides, use_cudnn_on_gpu=use_cudnn_on_gpu,
   1030             padding=padding, explicit_paddings=explicit_paddings,
-> 1031             data_format=data_format, dilations=dilations, name=name, ctx=_ctx)
   1032       except _core._SymbolicException:
   1033         pass  # Add nodes to the TensorFlow graph.

~/venv_tf2.0/lib/python3.6/site-packages/tensorflow/python/ops/gen_nn_ops.py in conv2d_eager_fallback(input, filter, strides, padding, use_cudnn_on_gpu, explicit_paddings, data_format, dilations, name, ctx)
   1128   explicit_paddings, "data_format", data_format, "dilations", dilations)
   1129   _result = _execute.execute(b"Conv2D", 1, inputs=_inputs_flat, attrs=_attrs,
-> 1130                              ctx=_ctx, name=name)
   1131   _execute.record_gradient(
   1132       "Conv2D", _inputs_flat, _attrs, _result, name)

~/venv_tf2.0/lib/python3.6/site-packages/tensorflow/python/eager/execute.py in quick_execute(op_name, num_outputs, inputs, attrs, ctx, name)
     65     else:
     66       message = e.message
---> 67     six.raise_from(core._status_to_exception(e.code, message), None)
     68   except TypeError as e:
     69     if any(ops._is_keras_symbolic_tensor(x) for x in inputs):

/usr/lib/python3/dist-packages/six.py in raise_from(value, from_value)

UnknownError: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above. [Op:Conv2D]

**Describe the expected behavior**
Output the inference results

**Code to reproduce the issue**
import tensorflow as tf
tf.keras.layers.Conv2D(10, 3)(tf.ones((1, 5, 5, 3)))

How should resolve it? Thanks

**Comment by kurobaneHITOMI** [comment]
I have also got this problem for several days. 
win10, python3.6, TF2.0beta1, cuda10.0, cudnn7.6.
What's really ridiculous is that it works well when I finished installing them. After about two days when I used layers.conv2D it didn't work and reported Failed to get convolution algorithm. I have tried to fix it for reinstall cuda and cudnn, and check environment variables. It works for time to time, but now it doesn't work completely for the same question. I would like to know how should I do for this too. Thanks

**Comment by hgffly** [comment]
Dear @kurobaneHITOMI 

Now my code works well without this issue by using this:
> `physical_devices = tf.config.experimental.list_physical_devices('GPU') tf.config.experimental.set_memory_growth(physical_devices[0], True)`
> Leading by issued#29632, thank srihari-humbarwadi

It did work, thanks so much

**Comment by alon1samuel** [comment]
> I also have this problem for several days.
> win10, python3.6, TF2.0beta1, cuda10.0, cudnn7.6.
> What's really ridiculous is that it works well when I finished installing them. After about two days when I used layers.conv2D it didn't work and reported Failed to get convolution algorithm. I have tried to fix it for reinstall cuda and cudnn, and check environment variables.
> It seems it has noting to do with cuda cudnn. Now my code works well without this issue by using this:
> `physical_devices = tf.config.experimental.list_physical_devices('GPU') tf.config.experimental.set_memory_growth(physical_devices[0], True)`
> Leading by issued#29632, thank srihari-humbarwadi

Hi, 
This solution didn't work for my. 

I'm running on TF 2 rc1. I've added these lines and I still get this error of Failed to get convolution algorithm...

Are there any other solutions?
Regards, Alon
