### ISSUE TITLE
NameError: Name MNIST is not defined

### ISSUE THREAD

**Issue by machomachopadre** [tensorflow/tensorflow#3043]
I am following the [Deep MNIST](https://www.tensorflow.org/versions/r0.9/tutorials/mnist/pros/index.html#start-tensorflow-interactivesession) tutorial. After copy-pasting code till [here](https://www.tensorflow.org/versions/r0.9/tutorials/mnist/pros/index.html#evaluate-the-model), I get a NameError. The exact output is
 ```
Traceback (most recent call last):
  File "Deep_MNIST.py", line 29, in <module>
    batch = mnist.train.next_batch(50)
NameError: name 'mnist' is not defined
```
This is my file-
```
x = tf.placeholder(tf.float32, shape=[None, 784])
y_ = tf.placeholder(tf.float32, shape=[None, 10])

W = tf.Variable(tf.zeros([784,10]))
b = tf.Variable(tf.zeros([10]))

sess.run(tf.initialize_all_variables())

y = tf.nn.softmax(tf.matmul(x,W) + b)

cross_entropy = tf.reduce_mean(-tf.reduce_sum(y_ * tf.log(y), reduction_indices=[1]))

train_step = tf.train.GradientDescentOptimizer(0.5).minimize(cross_entropy)

for i in range(1000):
  batch = mnist.train.next_batch(50)
  train_step.run(feed_dict={x: batch[0], y_: batch[1]})

correct_prediction = tf.equal(tf.argmax(y,1), tf.argmax(y_,1))
accuracy = tf.reduce_mean(tf.cast(correct_prediction, tf.float32))
print(accuracy.eval(feed_dict={x: mnist.test.images, y_: mnist.test.labels}))
```
Thanks!

**Comment by hnarayanan** [comment]
Hi! Look a little earlier at the instructions, the first section is about loading the MNIST data. And you need to run the following before your snippet of code above:

````
from tensorflow.examples.tutorials.mnist import input_data
mnist = input_data.read_data_sets('MNIST_data', one_hot=True)
````

**Comment by machomachopadre** [comment]
@hnarayanan I already have the MNIST_data directory(i had done it earlier)

**Comment by hnarayanan** [comment]
Yes, but you need to load it in the context of the current python script that you're attempting to run. (In either case, this is a general support issue that I think will soon be moved to StackOverflow.)

**Comment by machomachopadre** [comment]
@hnarayanan How do I load it in context? And also this is not on SO because my account is temporarily not being able to ask questions :P

**Comment by machomachopadre** [comment]
@hnarayanan thanks for your help

**Comment by EN10** [comment]
had the same error, thanks.

**Comment by wei-yuan** [comment]
Same problem, thanks!

**Comment by CryKey3** [comment]
Results:
runfile('C:/Users/3/Documents/Python Scripts/TensorFlow/mnist_basic1.py', wdir='C:/Users/3/Documents/Python Scripts/TensorFlow')
Extracting MNIST_data\train-images-idx3-ubyte.gz
Extracting MNIST_data\train-labels-idx1-ubyte.gz
Extracting MNIST_data\t10k-images-idx3-ubyte.gz
Extracting MNIST_data\t10k-labels-idx1-ubyte.gz
0.9199

Cut and Paste this:

from tensorflow.examples.tutorials.mnist import input_data
mnist = input_data.read_data_sets('MNIST_data', one_hot=True)

import tensorflow as tf
x = tf.placeholder(tf.float32, [None, 784])
W = tf.Variable(tf.zeros([784, 10]))
b = tf.Variable(tf.zeros([10]))
y = tf.nn.softmax(tf.matmul(x, W) + b)
y_ = tf.placeholder(tf.float32, [None, 10])
cross_entropy = tf.reduce_mean(-tf.reduce_sum(y_ * tf.log(y), reduction_indices=[1]))
train_step = tf.train.GradientDescentOptimizer(0.5).minimize(cross_entropy)
init = tf.global_variables_initializer()
sess = tf.Session()
sess.run(init)
for i in range(1000):
  batch_xs, batch_ys = mnist.train.next_batch(100)
  sess.run(train_step, feed_dict={x: batch_xs, y_: batch_ys})
correct_prediction = tf.equal(tf.argmax(y,1), tf.argmax(y_,1))
accuracy = tf.reduce_mean(tf.cast(correct_prediction, tf.float32))
print(sess.run(accuracy, feed_dict={x: mnist.test.images, y_: mnist.test.labels}))

**Comment by digs1998** [comment]
i am getting this now
 No module named 'tensorflow.examples.tutorials
