### ISSUE TITLE
Calibration with Post-training quantization fails on networks that have multiple placeholders

### ISSUE THREAD

**Issue by kmonachopoulos** [tensorflow/tensorflow#30438]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**

- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 16.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: -
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 1.14.0
- Python version: Python 3.5.2
- Bazel version (if compiling from source): -
- GCC/Compiler version (if compiling from source): -
- CUDA/cuDNN version: -
- GPU model and memory: -

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**

I am trying to use post-training quantisation with a calibration data-set to capture the activation ranges. The network is an unrolled lstm-based model. This model has multiple placeholders (3 ph) and the post-training quantisation process breaks because of that.

**Describe the expected behavior**

It is expected the post-training quantisation method to accept networks with multiple placeholders. Trying the same code as below in other networks that has only one placeholder works as expected (although the reference implementations of quantise/de-quantise which are located at the beginning and at the end of the network is extremely slow, but this is another issue).

**Code to reproduce the issue**
```
def representative_dataset_gen():
    for _ in range(1):
        input_node = np.array(np.random.rand(1,16,19,26), dtype=np.float32)
        new_state_c = np.array(np.random.rand(1,2048), dtype=np.float32)
        new_state_h = np.array(np.random.rand(1,2048), dtype=np.float32)
        yield [input_node,new_state_c,new_state_h]
```

```
def load_graph_and_post_train():

    converter = tf.lite.TFLiteConverter.from_frozen_graph(args.graph, 
        input_arrays=[ "input_node","previous_state_c","previous_state_h" ], 
        output_arrays=["logits"], 
        input_shapes={"input_node": [1,16,19,26], "previous_state_c":[1,2048], "previous_state_h":[1,2048]} )

    converter.optimizations = [tf.lite.Optimize.DEFAULT]
    converter.representative_dataset = representative_dataset_gen

    tflite_quant_model = converter.convert()
    open("./models/post_train_calibration_model.tflite", "wb").write(tflite_quant_model)

if __name__ == '__main__':
    parser = ArgumentParser(description='post-training quantisation')
    parser.add_argument('-graph', required=True, type=str, help='The pb model')
    args = parser.parse_args()
    load_graph_and_post_train()
```

**Other info / logs**
2019-07-05 14:03:13.996584: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2019-07-05 14:03:14.003163: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 3192860000 Hz
2019-07-05 14:03:14.007918: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x6b0b650 executing computations on platform Host. Devices:
2019-07-05 14:03:14.007953: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): <undefined>, <undefined>
WARNING: Logging before flag parsing goes to stderr.
W0705 14:03:15.397149 140670832994048 deprecation_wrapper.py:119] From post-trainin-quantisation-calib.py:96: The name tf.logging.set_verbosity is deprecated. Please use tf.compat.v1.logging.set_verbosity instead.

W0705 14:03:15.397516 140670832994048 deprecation_wrapper.py:119] From post-trainin-quantisation-calib.py:96: The name tf.logging.INFO is deprecated. Please use tf.compat.v1.logging.INFO instead.

2019-07-05 14:03:15.401800: I tensorflow/core/grappler/devices.cc:60] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0 (Note: TensorFlow was not compiled with CUDA support)
2019-07-05 14:03:15.401952: I tensorflow/core/grappler/clusters/single_machine.cc:359] Starting new session
2019-07-05 14:03:31.757150: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:716] Optimization results for grappler item: graph_to_optimize
2019-07-05 14:03:31.757222: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:718]   constant folding: Graph size after: 388 nodes (-14), 510 edges (-14), time = 10271.6318ms.
2019-07-05 14:03:31.757235: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:718]   constant folding: Graph size after: 388 nodes (0), 510 edges (0), time = 5687.64893ms.
INFO: Initialized TensorFlow Lite runtime.
terminate called after throwing an instance of 'std::out_of_range'
  what():  _Map_base::at
Abort (core dumped)

**Comment by kmonachopoulos** [comment]
Changed the script a little bit. 

When I run post-training quantisation without the argument` converter.optimizations = [tf.lite.Optimize.DEFAULT]` then the script extracts a tflite model (obviously not quatnised). So the problem is probably not the placeholders and the shapes but the u8 optimizer ?

**Comment by eric4337** [comment]
I have std::out_of_range error even with only one placeholder

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.
