### ISSUE TITLE
Operation marked as not fetchable

### ISSUE THREAD

**Issue by nishantb21** [tensorflow/tensorflow#30435]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 16.04, Windows 10
- TensorFlow installed from (source or binary): Binary
- TensorFlow version (use command below): 1.13 and 1.14
- Python version: 3
- CUDA/cuDNN version: 10.0/7
- GPU model and memory: Nvidia GTX 960M 4GB

**Describe the current behavior**
I wanted to reference a list item inside tf.while_loop using a loop variable. Instead of printing the list items one after another it says the following:
```
ValueError: Operation 'while/Identity' has been marked as not fetchable.
```

**Describe the expected behavior**
Expected behaviour is to print the list items.

**Code to reproduce the issue**
```
import tensorflow as tf

class A():
    def __init__(self):
        self.lst = [1, 2, 3]
        self.sess = tf.Session()
        self.total_length = tf.constant(len(self.lst))

    def loop(self, i):
        pr = tf.print(i)
        current_value = self.lst[i.eval(session=self.sess)]
        with tf.control_dependencies([pr]):
            i = tf.add(i, 1)
        return [i]

    def cond(self, i):
        return tf.less(i, self.total_length) 

    def run(self):
        i = tf.constant(0)
        while_op = tf.while_loop(self.cond, self.loop, [i])
        final_i = self.sess.run(while_op)


if __name__ == "__main__":
    obj = A()
    obj.run()
```
I have tried eager execution as well but the same error pops up.

**Other info / logs**
This issue was originally a comment by me in [this thread](https://github.com/tensorflow/tensorflow/issues/4094#issuecomment-502346438). It was confirmed by @mrry that this indeed was a bug. 

Thanks for all the help!

**Comment by mrry** [comment]
Saurabh: This looks like a bug in V1 control flow (in graph mode) to me. Can you take a quick look and confirm? Thanks!

**Comment by saxenasaurabh** [comment]
This seems to be working as intended. Could you try the following code:

```
import tensorflow as tf

class A():
    def __init__(self):
        self.lst = tf.constant([1, 2, 3])
        self.sess = tf.Session()
        self.total_length = tf.size(self.lst)

    def loop(self, i):
        pr = tf.print(i)
        current_value = self.lst[i]
        with tf.control_dependencies([pr]):
            i = tf.add(i, 1)
        return [i]

    def cond(self, i):
        return tf.less(i, self.total_length) 

    def run(self):
        i = tf.constant(0)
        while_op = tf.while_loop(self.cond, self.loop, [i])
        final_i = self.sess.run(while_op)


if __name__ == "__main__":
    obj = A()
    obj.run()
```

**Comment by mrry** [comment]
Apologies for the confusion: I missed the `i.eval(session=self.sess)` inside the loop body, which is indeed not allowed.

**Comment by nishantb21** [comment]
Oh okay, it works! Thanks!
