### ISSUE TITLE
tf.data.Dataset.list_files return is deterministic order when shuffle=False?

### ISSUE THREAD

**Issue by zhjunqin** [tensorflow/tensorflow#30436]
## URL(s) with the issue:
https://www.tensorflow.org/api_docs/python/tf/data/Dataset#list_files

## Description of issue (what needs changing):
In the doc above, it says 
```
NOTE: The default behavior of this method is to return filenames in 
a non-deterministic random shuffled order. 
Pass a seed or shuffle=False to get results in a deterministic order.
```

So if pass `shuffle=False`, it will return a deterministic order.

But if check source code of the function, it calls following function to get matching files.

https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/data/ops/dataset_ops.py#L769

```
  @staticmethod
  def list_files(file_pattern, shuffle=None, seed=None):
      ...
      matching_files = gen_io_ops.matching_files(file_pattern)
```

If we check description of `gen_io_ops.matching_files`,  it says `Note also that the order of filenames returned can be non-deterministic.`

```
@tf_export('matching_files')
def matching_files(pattern, name=None):
  r"""Returns the set of files matching one or more glob patterns.

  Note that this routine only supports wildcard characters in the

  basename portion of the pattern, not in the directory portion.

  Note also that the order of filenames returned can be non-deterministic.

  Args:
    pattern: A `Tensor` of type `string`.
      Shell wildcard pattern(s). Scalar or vector of type string.
    name: A name for the operation (optional).

  Returns:
    A `Tensor` of type `string`.
  """
```

And also the document in https://www.tensorflow.org/api_docs/python/tf/io/matching_files.

```
Defined in generated file: python/ops/gen_io_ops.py.

Note that this routine only supports wildcard characters in the basename portion of the pattern,
not in the directory portion. 
Note also that the order of filenames returned can be non-deterministic.
```

And also description in the function https://www.tensorflow.org/api_docs/python/tf/io/match_filenames_once 

```
Defined in python/training/input.py.

NOTE: The order of the files returned can be non-deterministic.
```

Check source code of the fucntion
https://github.com/tensorflow/tensorflow/blob/r1.14/tensorflow/python/training/input.py#L63

Both `tf.io.matching_files` and  tf.io.match_filenames_once` call `gen_io_ops.matching_files`.

I think it is quite confuse here.

**Comment by feihugis** [comment]
@zhjunqin As `MatchingFilesOp` sorts the matched files [here](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/kernels/matching_files_op.cc#L63), the order of filenames returned should be deterministic. PR #30543 has been submitted to update the related docs.
