### ISSUE TITLE
kissfft compile errors due to old archived version of kissfft

### ISSUE THREAD

**Issue by lwrobinson12356** [tensorflow/tensorflow#30447]
external "kissfft" fails to compile on Windows 10

**System Information**
Windows 10 v1903 on desktop computer 
Building Latest git pull of Tensorflow (7/6/2019)
MSys64
Python 3.6.8 :: Anaconda, Inc.
CUDA 10.1
cuDNN 7
Bazel 0.24.1
MS Visual Studio 2019 Community
NVIDIA GeForce GTX 850M
TF_CUDA_COMPUTE_CAPABILITIES="5.0"

Build Command:
bazel build --config=opt --config=v2 --copt=-nvcc_options=disable-warnings --define=no_tensorflow_py_deps=true //tensorflow/tools/pip_package:build_pip_package

Problem:
When building Tensorflow from source, I get the following errors:

c:\users\lawrence\_bazel_lawrence\jc3cdzjy\execroot\org_tensorflow\external\kissfft\kiss_fft.h(60): error C2061: syntax error: identifier 'int16_t'
...

The problem is line 46 of kiss_fft.h:
"#include <sys/types.h>"
which is an attempt to define int16_t. This doesn't work in Windows, and is depricated in unix. The correct approach is:
"#include <stdint.h>"

NOTE: The author of kissfft has fixed this in recent distributions (see https://github.com/mborgerding/kissfft/blob/master/kiss_fft.h) so updating the tensorflow external archive with a more recent version of kissfft would resolve this issue.

**Comment by yongtang** [comment]
Added PR #30452 for the fix.
