### ISSUE TITLE
mpi_portable_platform.h not found because MPI_LIB_IS_OPENMPI variable is always set to True

### ISSUE THREAD

**Issue by YuMan-Tam** [tensorflow/tensorflow#30440]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Red Hat Linux 7.6 (Maipo) 
- TensorFlow installed from (source or binary): Issue when trying to build from source.
- TensorFlow version: Master Branch (as of 7/4/2019)
- Python version: 3.7.3
- Installed using virtualenv? pip? conda?: Nope.
- Bazel version (if compiling from source): 0.16.1
- GCC/Compiler version (if compiling from source): 5.5

**Describe the problem**

**Provide the exact sequence of commands / steps that you executed before running into the problem**

```./configure``` with ```mpi``` enabled.

```bazel build --config=opt --config=mkl //tensorflow/tools/pip_package:build_pip_package```

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem.

Sorry, the log is somehow lost. But the error is about ```mpi_portable_platform.h``` not found. My system has ```mpich``` installed but not ```open_mpi```. The source file in ```tensorflow/third_party/mpi/mpi.bzl``` contains:

```
def mpi_hdr():
    MPI_LIB_IS_OPENMPI = True
    hdrs = []
    if MPI_LIB_IS_OPENMPI:
        hdrs = ["mpi.h", "mpi_portable_platform.h"]  #When using OpenMPI
    else:
        hdrs = ["mpi.h", "mpio.h", "mpicxx.h"]  #When using MVAPICH
    return hdrs
```

It seems that the variable ```MPI_LIB_IS_OPENMPI``` is always set to ```True``` which won't work if one does not use ```open mpi```. I set the variable to ```False``` and the error goes away.

**Comment by byronyi** [comment]
See https://github.com/tensorflow/tensorflow/blob/master/configure.py#L1192; this line will be changed if you `./configure`.

**Comment by YuMan-Tam** [comment]
> This line will be changed if the `./configure` script detects your MPICH installation. See https://github.com/tensorflow/tensorflow/blob/master/configure.py#L1201.

Yes, I was confused why this hasn't the case. 

When I ran `./configure`, the script did detect the location of my MPICH installation (i.e. rather than me having to manually put in the location. Given this, I still got this error down the road so I was a bit baffled.

**Comment by byronyi** [comment]
Try change configure script and add debug toggle to see why that line wasn’t executed.

**Comment by ravikyram** [comment]
@YuMan-Tam Did you try as suggested by byronyi.
Looks like your issue got resolved.Please, let me know if i am wrong.Thanks!

**Comment by YuMan-Tam** [comment]
> @YuMan-Tam Did you try as suggested by byronyi.
> Looks like your issue got resolved.Please, let me know if i am wrong.Thanks!

@byronyi: Thank you for the suggestion. I did not yet have a chance to test this alternative but will post update when I do.

@ravikyram: The issue is resolved in the sense that I got rid of error by manually changing the source file.   But I still haven't did what @byronyi suggested to figure out why MPICH was not correctly detected by the configuration script. Would you like to me close the issue for now?

**Comment by byronyi** [comment]
Ping @jbedorf; mind to take a look?

**Comment by ravikyram** [comment]
@YuMan-Tam  did you get a chance to look as suggested by @byronyi .Thanks!

**Comment by jbedorf** [comment]
Looks like the problem is that this line fails:
https://github.com/tensorflow/tensorflow/blob/master/configure.py#L1201
The replace command looks for the string without spaces around the ` = ` symbol, while the `mpi.bzl` file has the line with spaces. I'll push a fix later this week.

**Comment by YuMan-Tam** [comment]
> @YuMan-Tam did you get a chance to look as suggested by @byronyi .Thanks!

@ravikyram: Sorry for my late reply. I believe @jbedorf has located the root cause of this issue. The same problem persists in the configure script for the 2.0 version of tensorflow. 

In fact, I am not sure how to do the `debug toggle` as suggested by @byronyi. However, I could investigate further (a.k.a. confirm the finding from @jbedorf) if this is still helpful.
