### ISSUE TITLE
License used in tensorflow repos

### ISSUE THREAD

**Issue by Austinmack-dev** [tensorflow/tensorflow#30442]
Hello Tensorflow Community, 

I am not sure this is the right place to ask this question, but if I were to create my own repository that uses tensorflow and does not modify or add to tensorflow, which license am I required to use for the code that uses tensorflow?  If this is not the correct place to ask this, please direct me to the correct place. 

Thanks

**Comment by ravikyram** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged//tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.

**Comment by ewilderj** [comment]
TensorFlow is Apache 2 licensed, and you may use it under the terms of that license. If you have any specific queries, I refer you to the Apache License FAQ http://www.apache.org/foundation/license-faq.html. I can't give you legal advice, but you can find a lot of information on the web about using the Apache license.
