### ISSUE TITLE
[TF 2.0 API Docs] tf.image.image_gradients

### ISSUE THREAD

**Issue by imransalam** [tensorflow/tensorflow#30445]
## URL(s) with the issue:

https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/image/image_gradients
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/ops/image_ops_impl.py

### Usage example

No usage example provided

### Submit a pull request?

Yes
https://github.com/tensorflow/tensorflow/pull/30446

**Comment by jvishnuvardhan** [comment]
@imransalam Thanks for contributing through PRs.

**Comment by jvishnuvardhan** [comment]
Automatically closing this out since I understand it to be resolved by the https://github.com/tensorflow/tensorflow/pull/30446 (merged already), but please let me know if I'm mistaken.Thanks!
