### ISSUE TITLE
Memory leak when using `tf.linalg.expm` in `tf.keras.layers.Layer`

### ISSUE THREAD

**Issue by liemonade** [tensorflow/tensorflow#30459]
**System information**
- Have I written custom code: *Yes*
- OS Platform and Distribution: *Arch Linux*
- TensorFlow installed from (source or binary): *Binary*
- TensorFlow version (use command below): *2.0.0 Beta 1*
- Python version: *3.7.3*
- CUDA/cuDNN version: *10.0.130* / *7.6.0*
- GPU model and memory: *Nvidia GTX 1060, 6GB*

**Describe the current behavior**
I'm currently working on a costum Keras Layer and need to use `tf.linalg.expm` several times. 
While training my model I noticed that my system would be out of memory after a few minutes. 
Reducing the Layer definition step by step I noticed that the error should be related to `tf.linalg.expm`. 
Every time the layers `call` method is invoked more and more memory get's allocated.
Replacing `return tf.linalg.expm(X)` in the following code example with e.g. `return tf.matmal(X,X)` does not yield this extreme leak of memory.

**Describe the expected behavior**
The memory allocated by an invocation of a`call` method using `tf.linalg.expm` should be freed.
![Number of `call` invocations plotted against memory allocated in Gigabytes](https://user-images.githubusercontent.com/2351787/60768608-18b51480-a0c6-11e9-9d0f-baad36136cc8.png)

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.
```python
import numpy as np
import tensorflow as tf
import os
import matplotlib.pyplot as plt
import psutil


def memory():
    pid = os.getpid()
    py = psutil.Process(pid)
    memory_use = py.memory_info()[0] / 2. ** 30
    return memory_use

class TestLayer(tf.keras.layers.Layer):

    def __init__(self, **kwargs):
        
        super(TestLayer, self).__init__(**kwargs)

    def build(self, input_shape):
        self.s = input_shape

    @tf.function
    def call(self, inputs, training=None):
        
        X = tf.matmul(tf.transpose(inputs),inputs)
        
        return tf.linalg.expm(X)
    


S = tf.keras.Input(shape=(1,), name="sequence", dtype=tf.float64)
T = TestLayer()(S)
model = tf.keras.Model(inputs=S,outputs=T)
dataset = tf.data.Dataset.from_tensors(tf.constant(1)).repeat().map(lambda x: tf.ones([tf.random.uniform([1], minval=100, maxval=3000, dtype=tf.int32)[0],1],dtype=tf.float64))

memory_usage = []

i = 0
for data in dataset:
    s = model(data)
    
    memory_usage.append(memory())

    if i == 1000:
        break
        
    i = i+1
    
plt.figure()
plt.plot(memory_usage)
plt.xlabel("iterations")
plt.ylabel("memory usage")
plt.show()
```

**Other info / logs**
Warning produced when using `tf.linalg.expm`: 
```
    WARNING: Logging before flag parsing goes to stderr.
    W0707 13:40:07.108526 139932625143616 deprecation.py:323] From /home/darvin/.conda/envs/tf2/lib/python3.7/site-packages/tensorflow/python/ops/linalg/linalg_impl.py:280: add_dispatch_support.<locals>.wrapper (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
    Instructions for updating:
    Use tf.where in 2.0, which has the same broadcast rule as np.where
```

**Comment by rmothukuru** [comment]
Could reproduce the issue with TF Version 2.0 beta.

**Comment by amahendrakar** [comment]
@liemonade,
Could you please upgrade to TensorFlow v2.3 and check if you are still facing the issue? Thanks!
