### ISSUE TITLE
Add warning to dropout that it violates Google patent US9406017B2

### ISSUE THREAD

**Issue by alexanderkjeldaas** [tensorflow/tensorflow#30451]
## Description of issue (what needs changing):

Google who to a large extent runs this project has patented dropout.  See https://patents.google.com/patent/US9406017B2/en

This patent is not listed as a pledged patent in Google's list of patents that are thus *not* covered by the [Google Open Patent Non-Assertion Pledge](https://www.google.com/patents/opnpledge/patents/)

Since this could cause serious issues for users, it needs to be documented.

**Comment by alexanderkjeldaas** [comment]
It is possible that the current dropout implementations have been designed to work around this patent.  If not, working around the patent should be considered.

**Comment by ewilderj** [comment]
To the extent any Tensorflow contributor, including Google, holds any patents that may read on
contributions to Tensorflow, those patents are licensed as per the terms of the Apache 2 license in the LICENSE file
