### ISSUE TITLE
loop problem in defining the network

### ISSUE THREAD

**Issue by chencan15** [tensorflow/tensorflow#30455]
- TensorFlow version (you are using): 1.12
- Are you willing to contribute it (Yes/No): Yes

**Describe the feature and the current behavior/state:**

Each data A has the shape of [height, width, channel] and is saved in TFrecord file.
I use an iterator to read batches from my TFrecord file. The input of my network is a 4-dimensional tensor A_batch with shape [batch, height, width, channel]. 

Let Network() represents the network i define and Output represents the output of the network:
Output = Network(A_batch)

Each data A has the shape of [height, width, channel]. I want to have different trainable ops on each channel like (assume channel=3):
```

    ops_0 on A[ : , : , 0]
    ops_1 on A[ : , : , 1]
    ops_2 on A[ : , : , 2]

```

However, the input A_batch with the shape [batch, height, width, channel]. It means i need to loop on batch (assume channel=3):

```
for m in range(batch)
    ops_0 on A_batch [ m , : , :，0 ]
    ops_1 on A_batch [ m , : , :，1 ]
    ops_2 on A_batch [ m , : , :，2 ]

```
**Note that after trainable ops, original data becomes trainable variable.**

**Question 1:**
In defining the network, is it allowed to separate batch data to perform different trainable ops in loop? 

**Question 2:**
In defining the network, is it allowed to assign trainable variable to a tensor to form another trainable variable? 

for example, let A_batch_operated denotes the trainable variable after performing trainable ops_0, ops_1,and ops_2 on batch data A_batch :

```
for m in range(batch)
    A_batch_operated [ m , : , :，0 ]= ops_0 (A_batch [ m , : , :，0 ] )
    A_batch_operated [ m , : , :，1 ]= ops_1 (A_batch [ m , : , :，1 ] )
    A_batch_operated [ m , : , :，2 ]= ops_2 (A_batch [ m , : , :，2 ] )

```
**Question 3:**
Can i add a trainable ops on the new trainable variable on A_batch_operated?  like:

Output= ops_3 (A_batch_operated)

Thank you

**Will this change the current api? How?**
No

**Who will benefit with this feature?**
Some researchers of image/video processing
Any Other info.

**Comment by ymodak** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow-tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.
