### ISSUE TITLE
problem about creating my own model

### ISSUE THREAD

**Issue by WendyWangxyue** [tensorflow/tensorflow#30465]
when i run the code which is write in https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/experimental/micro/examples/micro_speech#creating-your-own-model
bazel run -c opt --copt=-mavx2 --copt=-mfma \
tensorflow/examples/speech_commands:train -- \
--model_architecture=tiny_conv --window_stride=20 --preprocess=micro \
--wanted_words="yes,no" --silence_percentage=25 --unknown_percentage=25 --quantize=1
it also said
ERROR: An error occurred during the fetch of repository 'local_config_python':
   Traceback (most recent call last):
	File "/home/wxy/tensorflow-master/third_party/py/python_configure.bzl", line 344
		_create_local_python_repository(repository_ctx)
	File "/home/wxy/tensorflow-master/third_party/py/python_configure.bzl", line 296, in _create_local_python_repository
		_get_numpy_include(repository_ctx, python_bin)
	File "/home/wxy/tensorflow-master/third_party/py/python_configure.bzl", line 276, in _get_numpy_include
		_execute(repository_ctx, [python_bin, "-c",..."], <2 more arguments>)
	File "/home/wxy/tensorflow-master/third_party/py/python_configure.bzl", line 56, in _execute
		_fail("\n".join([error_msg.strip() if ... ""]))
	File "/home/wxy/tensorflow-master/third_party/py/python_configure.bzl", line 27, in _fail
		fail(("%sPython Configuration Error:%...)))
Python Configuration Error: Problem getting numpy include path.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named numpy
Is numpy installed?
ERROR: /home/wxy/tensorflow-master/third_party/python_runtime/BUILD:5:1: no such package '@local_config_python//': Traceback (most recent call last):
	File "/home/wxy/tensorflow-master/third_party/py/python_configure.bzl", line 344
		_create_local_python_repository(repository_ctx)
	File "/home/wxy/tensorflow-master/third_party/py/python_configure.bzl", line 296, in _create_local_python_repository
		_get_numpy_include(repository_ctx, python_bin)
	File "/home/wxy/tensorflow-master/third_party/py/python_configure.bzl", line 276, in _get_numpy_include
		_execute(repository_ctx, [python_bin, "-c",..."], <2 more arguments>)
	File "/home/wxy/tensorflow-master/third_party/py/python_configure.bzl", line 56, in _execute
		_fail("\n".join([error_msg.strip() if ... ""]))
	File "/home/wxy/tensorflow-master/third_party/py/python_configure.bzl", line 27, in _fail
		fail(("%sPython Configuration Error:%...)))
Python Configuration Error: Problem getting numpy include path.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named numpy
Is numpy installed?
 and referenced by '//third_party/python_runtime:headers'
ERROR: Analysis of target '//tensorflow/examples/speech_commands:train' failed; build aborted: Analysis failed
INFO: Elapsed time: 8.612s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (33 packages loaded, 707 targets c\
FAILED: Build did NOT complete successfully (33 packages loaded, 707 targets c\
onfigured)

i run it in Ubuntu 16.04 and i install the numpy whatever in python 2.x or python 3.n
thank you

**Comment by rmothukuru** [comment]
Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version. Also, did you compile from source or install a binary?

Make sure you also include the exact command if possible to produce the output included in your test case. If you are unclear what to include see the issue template displayed in [the Github new issue template](https://github.com/tensorflow/tensorflow/issues/new).

We ask for this in the issue submission template, because it is really difficult to help without that information. Thanks!

**Comment by WendyWangxyue** [comment]
I use the Linux Ubuntu 16.04 in VMware with Tensorflow 1.14 with CPU. I install Tensorflow with pip.
Build label: 0.27.1
Python 3.5.2
[GCC 5.4.0 20160609] on linux
tf.__version__
'1.14.0'

thank you

**Comment by saumpsh** [comment]
Hi,

I have been able to compile the model for micro_speech successfully. I would recommend setting up a environment using [Docker.](https://www.tensorflow.org/install/docker). Its much easier to work with and it takes care of all TensorFlow related dependencies. 

Also if possible try not to train the model using  VMWare as the training will be too slow. Instead try getting hold of a Linux computer with a good GPU and CPU along with plenty of RAM (16GB or more). 

Once your Docker environment is setup login to your docker container, install Bazel program, and start training as per [the step here](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/experimental/micro/examples/micro_speech). It should work.

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.
