### ISSUE TITLE
TensorflowLite model for On-Device Speech Recognizer

### ISSUE THREAD

**Issue by dattachandan** [tensorflow/tensorflow#30469]
# Description of issue

There a mention of a tensorflowlite model in the Google AI team [blog](https://ai.googleblog.com/2019/03/an-all-neural-on-device-speech.html)

> made publicly available through the model optimization toolkit in the TensorFlow Lite library 

Where can I find this model? Is this the right place: https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/g3doc/models

**Comment by gadagashwini** [comment]
@dattachandan Please have a look at this [link](https://www.tensorflow.org/lite/guide/get_started#1_choose_a_model). Thanks!

**Comment by freedomtan** [comment]
@dattachandan what make publicly available in that blog is
> the parameter quantization and hybrid kernel techniques we developed in 2016

not model(s) :-)

@gadagashwini nope, ASR models are not there :)

**Comment by dattachandan** [comment]
Thanks for the update!

* You mean that the quantization scheme developed by the Google Speech group(to reduce the resolution of the parameters of a neural network from 32-bit floating point values to 8-bit integer values) that was proposed in the paper "On the efficient representation and execution of deep acoustic models" was publicly released in tensorflow lite library [here](https://www.tensorflow.org/model_optimization/guide/quantization/index)

* Does the tested Gboard app mentioned in the [blog](https://ai.googleblog.com/2019/03/an-all-neural-on-device-speech.html) load the ASR TFLite model as applinks to JNI binary(.tflite using TocoConverter?) as the smartreply app [demo](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/models/smartreply/) 

* Is the blog mentioned 80mb model downloaded separately from the Gboard android app while downloading a language file, because the app size is 43.55 mb for release 8.3.6.250752527-release-armeabi-v7a? Or is it in com.google.android.googlequicksearchbox/app_g3_models on the android filesystem? what's the location on Android?

![image](https://user-images.githubusercontent.com/2154248/60935718-f1a54f80-a31e-11e9-8bca-3f34bbbbaa07.png)


* Can this model be used in Google Home in offline mode as well?

* Can this ASR model also run in the [CORAL TPU](https://coral.withgoogle.com/models/) which uses TF Lite?

**Comment by freedomtan** [comment]
@dattachandan can't speak for Google guys. Just what I know

- that's what the blog article claimed.
- not sure if tflite and tflite model are used in this case, probably not
- none of them I guess, should be the feature called "Faster voice typing"
- no idea
- even if it's a tflite model, it should be a weight only quantization one. Not one trained with quantization-aware training. Unlikely to work on Coral Edge TPU.

**Comment by biemster** [comment]
@dattachandan I'm working on getting this model imported in tensorflow as well, and documented my progress on [hackaday.io](https://hackaday.io/project/164399-android-offline-speech-recognition-natively-on-pc).

You'll find there how to get the models (there are 4 tflite models chained together), and how they feed each other. Last thing to get everything up and running is to feed the first in the chain with the audio stream, which must be some log-mel features or filterbanks or so.

I did not get to that yet, so there is some work left for you. :smile: 
Please report your progress here or preferably in my log on HaD.io (I doubt this git issue is the place for it).
