### ISSUE TITLE
Please add Cuda compute capability 6.1 for GTX 1080

### ISSUE THREAD

**Issue by ShuaiW** [tensorflow/tensorflow#3046]
I am building tensorflow from source, and after running below from the root

`bazel build -c opt --config=cuda //tensorflow/cc:tutorials_example_trainer`

I get

> ERROR: /home/shuaiwang/Downloads/tensorflow/tensorflow/cc/BUILD:61:1: error loading package 'tensorflow/core': Encountered error while reading extension file 'protobuf.bzl': no such package '@protobuf//': Error cloning repository: https://github.com/google/protobuf: cannot open git-upload-pack caused by https://github.com/google/protobuf: cannot open git-upload-pack caused by github.com and referenced by '//tensorflow/cc:tutorials_example_trainer'.
> ERROR: /home/shuaiwang/Downloads/tensorflow/tensorflow/cc/BUILD:61:1: error loading package 'tensorflow/core': Encountered error while reading extension file 'protobuf.bzl': no such package '@protobuf//': Error cloning repository: https://github.com/google/protobuf: cannot open git-upload-pack caused by https://github.com/google/protobuf: cannot open git-upload-pack caused by github.com and referenced by '//tensorflow/cc:tutorials_example_trainer'.
> ERROR: Analysis of target '//tensorflow/cc:tutorials_example_trainer' failed; build aborted.
> INFO: Elapsed time: 11.805s

I guess this is because tensorflow doesn't support compute capability for 6.1, which is the only option for GTX 1080, according to [this](https://developer.nvidia.com/cuda-gpus)?

**Comment by vrv** [comment]
You can set this option during ./configure

**Comment by ShuaiW** [comment]
@vrv can you be more specific? thanks

**Comment by vrv** [comment]
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/g3doc/get_started/os_setup.md#configure-tensorflows-canonical-view-of-cuda-libraries

**Comment by ShuaiW** [comment]
@vrv hi I did specify 6.1 in the Cuda compute capabilities step

> Please specify a list of comma-separated Cuda compute capabilities you want to build with.
> You can find the compute capability of your device at: https://developer.nvidia.com/cuda-gpus.
> Please note that each additional compute capability significantly increases your build time and binary size.
> [Default is: "3.5,5.2"]: 6.1

then I got the error build aborted

**Comment by vrv** [comment]
Ah, sorry, I didn't read the error message closely enough.  I'd just try again -- it looks like bazel couldn't git clone the protobuf repository properly, possibly due to transient network issues.  Nothing to do with cuda at all :)

**Comment by ShuaiW** [comment]
@vrv tried multiple times and got the same error :(

Do you think it might be possible that bazel was not installed properly?

**Comment by vrv** [comment]
No idea :(.  Try re-installing bazel, fresh cloning the tensorflow repository in a new directory and try again..

**Comment by ShuaiW** [comment]
@vrv hey I tried re-install bazel and fresh clone, but I get a different error

> ERROR: /home/shuaiwang/Downloads/tensorflow/tensorflow/tools/proto_text/BUILD:31:1: Linking of rule '//tensorflow/tools/proto_text:gen_proto_text_functions' failed: crosstool_wrapper_driver_is_not_gcc failed: error executing command third_party/gpus/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc -o bazel-out/host/bin/tensorflow/tools/proto_text/gen_proto_text_functions ... (remaining 26 argument(s) skipped): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
> /usr/bin/ld: bazel-out/host/bin/tensorflow/core/liblib_internal.a(numbers.o): undefined reference to symbol 'ceil@@GLIBC_2.2.5'
> //lib/x86_64-linux-gnu/libm.so.6: error adding symbols: DSO missing from command line
> collect2: error: ld returned 1 exit status
> Target //tensorflow/cc:tutorials_example_trainer failed to build
> Use --verbose_failures to see the command lines of failed build steps.
> INFO: Elapsed time: 7.452s, Critical Path: 6.54s


Thoughts?

**Comment by goodyttoor** [comment]
The same linking problem as #3029 

Please edit proto_text\BUILD and try building again.
