### ISSUE TITLE
InvalidArgumentError: Retval[0] does not have value when combining tf.case and l2_regularization

### ISSUE THREAD

**Issue by fengyang0317** [tensorflow/tensorflow#30467]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
N/A
- TensorFlow installed from (source or binary):
binary
- TensorFlow version (use command below):
('v1.14.0-rc1-22-gaf24dc91b5', '1.14.0')
- Python version:
 2.7.15
- CUDA/cuDNN version:
7
- GPU model and memory:
GTX 1070, 8G

**Describe the current behavior**
Get the following error when using tf.case and slim.l2_regularization.
```
Traceback (most recent call last):
  File "/home/yfeng23/test/tf/case_test.py", line 20, in <module>
    print(sess.run(loss))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 950, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1173, in _run
    feed_dict_tensor, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1350, in _do_run
    run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1370, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Retval[0] does not have value
```

**Describe the expected behavior**
No error.

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.
```
import tensorflow as tf
import tensorflow.contrib.slim as slim

x = tf.zeros((1, 8))

fn = lambda: slim.fully_connected(x, 4,
                                  weights_regularizer=slim.l2_regularizer(0.1))

pred_fn_pairs = [
  (tf.equal(0, 0), fn),
  (tf.equal(1, 0), fn)
]

y = tf.case(pred_fn_pairs, exclusive=True)

loss = tf.losses.get_regularization_loss()

with tf.Session() as sess:
  sess.run(tf.global_variables_initializer())
  print(sess.run(loss))
```

**Comment by ravikyram** [comment]
I have tried on colab with TF version 1.14 and was able to reproduce the issue.Thanks!

**Comment by ymodak** [comment]
Apologies for the delay in response. In your code snippet ```loss``` is not linked to the fully connected layer. Therefore we can reproduce the error with this minimal code snippet;
```python
losses_1 = tf.losses.get_regularization_loss()
with tf.Session() as sess:
  sess.run(tf.global_variables_initializer())
  print(sess.run(losses_1))
```
Output:
```python
InvalidArgumentError: Retval[0] does not have value
```
Thus its working as expected. Thanks!

**Comment by fengyang0317** [comment]
loss is the norm of the weights in the fully-connected layer. They are linked.

The error is caused by tf.case

I didn't get any error using the following code. The output I get is 0.28207764. 
```
import tensorflow as tf
import tensorflow.contrib.slim as slim

x = tf.zeros((1, 8))

y = slim.fully_connected(x, 4, weights_regularizer=slim.l2_regularizer(0.1))

losses_1 = tf.losses.get_regularization_loss()
with tf.Session() as sess:
  sess.run(tf.global_variables_initializer())
  print(sess.run(losses_1))
``

**Comment by alextp** [comment]
tf.case and slim's regularization are not compatible.

You need to create your regularizers outside of conditional branches (like tf.cond / tf.case) or explicitly return the regularization loss from the case / cond and accumulate it / add it to collections outside.
