### ISSUE TITLE
Tensorflow v1.14.0 with MKL and eigen on osx

### ISSUE THREAD

**Issue by skrisna** [tensorflow/tensorflow#30475]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Mac OSX Mojave 10.14.5
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: No
- TensorFlow installed from (source or binary): source
- TensorFlow version: on master branch, commit 3e5418c3d6
- Python version: 3.7.3
- Installed using virtualenv? pip? conda?: conda
- Bazel version (if compiling from source): 0.25.2
- GCC/Compiler version (if compiling from source): clang-1001.0.46.4
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

**Describe the problem**
I tried to install tensorflow along with MKL and eigen

**Provide the exact sequence of commands / steps that you executed before running into the problem**

```shell
# conda 4.7.5
conda create -n idp-6 -c defaults python=3 pip six numpy wheel setuptools mock 'future>=0.17.1' 'keras-preprocessing=1.0.5' 'keras-applications=1.0.6' mkl mklml
conda activate idp-6
cd tensorflow
export TF_MKL_ROOT=$HOME/miniconda3/envs/idp-6
# This is needed since license.txt does not exist in $TF_MKL_ROOT and the build system expects it
touch $TF_MKL_ROOT/license.txt
yes "" | ./configure
bazel build -c opt --verbose_failures --config=mkl --copt="-DEIGEN_USE_MKL_VML" --config=opt //tensorflow/tools/pip_package:build_pip_package
```

**Any other info / logs**
When I ran it, I got an error at some point in through the build that mkl.h was not found.

As a quick fix, I made the following update and it worked (below). While this is not particularly elegant, but it works for me.

If there is interest, I can provide a pull request that does the right thing for win/osx/linux using third_party/mkl/BUILD as a template.

```diff
diff --git i/third_party/eigen3/BUILD w/third_party/eigen3/BUILD
index bd6cb868a9..fb6970ee36 100644
--- i/third_party/eigen3/BUILD
+++ w/third_party/eigen3/BUILD
@@ -35,6 +35,8 @@ cc_library(
     deps = [
         "@eigen_archive//:eigen",
         "@local_config_sycl//sycl",
+        "@mkl_darwin//:mkl_headers",
+        "@mkl_darwin//:mkl_libs_darwin",
     ],
 )
```

**Comment by jingxu10** [comment]
Hi
Thanks for the quick fix.
I'll share your fix to dev team.
Thank you.

**Comment by NeoZhangJianyu** [comment]
@skrisna Is it possible to close this issue?
