### ISSUE TITLE
Run Tflite model on server

### ISSUE THREAD

**Issue by ajinkya933** [tensorflow/tensorflow#30477]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):Linux Ubuntu 16.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: all android phones
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below): 1.14
- Python version:python3
- Bazel version (if compiling from source):4
- GCC/Compiler version (if compiling from source):na
- CUDA/cuDNN version:na
- GPU model and memory:na

I have a custom trained model and exported it on Tensorflow Lite. It run well on android phones. I would like to run the same model on a Ubuntu server. How can I do that? I am choosing tflite for its small file size but I could not find any way to take inference from *.tflite model directly on a Ubuntu server.

**Comment by gadagashwini** [comment]
@ajinkya933 Did you get a chance look official [Tensorflow](https://www.tensorflow.org/lite/guide/inference) website for tensorflow tite Inference. Thanks!

**Comment by ajinkya933** [comment]
@gadagashwini yes, but there they are more focused on exploring the internal structure of tflite graph which can easily be done through softwares like Netron. What I am interested in getting bounding box output on ubuntu server provided I have *.tflite file as an input

**Comment by ajinkya933** [comment]
?

**Comment by aselle** [comment]
This is possible to do by installing the standard tensorflow pip and using the Python tflite interpreter
https://www.tensorflow.org/api_docs/python/tf/lite/Interpreter
That's the easiest way, it is also possible to use the C++ API, but you'll need to compile tflite yourself.
