### ISSUE TITLE
Op Less<bfloat16> registered twice

### ISSUE THREAD

**Issue by ekuznetsov139** [tensorflow/tensorflow#30476]
In the 1.14 branch, the CPU kernel op "Less" is registered twice for the type bfloat16 (see https://github.com/tensorflow/tensorflow/blob/r1.14/tensorflow/core/kernels/cwise_op_less.cc#L19 : first on line 19 and then on line 21).

This has the effect of throwing an error "InvalidArgumentError: Multiple OpKernel registrations match NodeDef" whenever a bfloat16 comparison on a CPU is attempted.

**Comment by yongtang** [comment]
Added a PR #30479 for the fix.

**Comment by ekuznetsov139** [comment]
The fix looks good.
Note that the same problem is present in master: 
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/kernels/cwise_op_less.cc#L19

**Comment by mangushev** [comment]
Please fix the same issue with bfloat16 registration for less_equal in 1.14:
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/kernels/cwise_op_less_equal.cc
https://github.com/tensorflow/tensorflow/blob/r1.14/tensorflow/core/kernels/cwise_op_less_equal.cc#L19

**Comment by jvishnuvardhan** [comment]
Automatically closing this out since I understand it to be resolved by the PR #30479 (merged already), but please let me know if I'm mistaken.Thanks!

**Comment by mangushev** [comment]
30479 resolves "less op" issue. I do not see that it addresses "less_equal op" issue.

**Comment by yongtang** [comment]
@mangushev Sorry I didn't see the comment about less_equal previously. Have added a PR 31459 to fix `LessEqual`.
