### ISSUE TITLE
[TF2.0] Bug allowing misuse of the batch dimension of a convolution layer

### ISSUE THREAD

**Issue by Dobiasd** [tensorflow/tensorflow#30474]
`tensorflow-1.14.0` rightfully complains about the following minimal example with `ValueError: could not broadcast input array from shape (20,6,6,32) into shape (10,6,6,32)`.

`tensorflow==2.0.0-beta1` however happily runs it and prints `(20, 6, 6, 32)`.

```python3
import numpy as np
import tensorflow.keras.backend as k
from tensorflow.keras.layers import Input, Conv2D, Lambda
from tensorflow.keras.models import Model

def custom_reshape(inputs):
    return k.reshape(inputs, (-1, 8, 8, 3))

inputs = Input(shape=(8, 8, 6))
x = Lambda(custom_reshape)(inputs)
x = Conv2D(32, (3, 3))(x)
model = Model(inputs=inputs, outputs=x)
model.compile(loss='mean_squared_error', optimizer='nadam')
print(model.summary())
batch_size = 10
result = model.predict(np.ones((batch_size, 8, 8, 6)), batch_size=batch_size)
print(result.shape)
```

As [per discussion](https://groups.google.com/a/tensorflow.org/forum/#!topic/testing/txsgcR3cubQ) this seems to be a bug in TF 2.0.

**Comment by Dobiasd** [comment]
It seems that this breaks some fundamental property of batching in general.

Let's take the following example (using `tensorflow==2.0.0-beta1`):

    import numpy as np
    from tensorflow.keras.layers import Input, Conv2D
    from tensorflow.keras.models import Model
    
    inputs = Input(shape=(8, 8, 6))
    x = Conv2D(32, (3, 3))(inputs)
    model = Model(inputs=inputs, outputs=x)
    model.compile(loss='mean_squared_error', optimizer='nadam')
    print(model.summary())
    batch_size = 1
    result = model.predict(np.ones((batch_size, 8, 8, 6)), batch_size=batch_size)
    print(result.shape)

When ran with `batch_size = 1` we get an output tensor with shape `(1, 6, 6, 32)`. With `batch_size = 10` it becomes `(10, 6, 6, 32)`.

But a model like this:

    import numpy as np
    import tensorflow.keras.backend as k
    from tensorflow.keras.layers import Input, Conv2D, Lambda
    from tensorflow.keras.models import Model
    
    def custom_reshape(inputs):
        return k.reshape(inputs, (-1, 8, 8, 3))
    
    inputs = Input(shape=(8, 8, 6))
    x = Lambda(custom_reshape)(inputs)
    x = Conv2D(32, (3, 3))(x)
    model = Model(inputs=inputs, outputs=x)
    model.compile(loss='mean_squared_error', optimizer='nadam')
    print(model.summary())
    batch_size = 1
    result = model.predict(np.ones((batch_size, 8, 8, 6)), batch_size=batch_size)
    print(result.shape)

outputs a `(2, 6, 6, 32)` Tensor. Changing to `batch_size = 10` should (intuitively) result in something with shape `(10, 2, 6, 6, 32)`, but in that case, of course, it does not. Instead, we get `(20, 6, 6, 32)`. Thus, the whole model should be invalid.

**Comment by gadagashwini** [comment]
I am able to reproduce the issue on Colab with Tensorflow 1.14.0 and works as expected with 2.0.0.beta1.

**Comment by Dobiasd** [comment]
@gadagashwini

> I am able to reproduce the issue on Colab with Tensorflow 1.14.0 and works as expected with 2.0.0.beta1.

You mean the other way around, right? The `ValueError` we get with `1.14.0` should be the correct behavior, while not raising this exception in `2.0.0-beta1` seems to be the problem.

**Comment by gadagashwini** [comment]
> @gadagashwini
> 
> > I am able to reproduce the issue on Colab with Tensorflow 1.14.0 and works as expected with 2.0.0.beta1.
> 
> You mean the other way around, right? I.e., the `ValueError` we get with `1.14.0` should be the correct behavior, while not raising this exception in `2.0.0-beta1` seems to be the problem.

Yes @Dobiasd I could able to get the `ValueError` with Tensorflow `1.14.0` and no exception with Tensorflow `2.0.0.beta1`.Thanks!

**Comment by yongtang** [comment]
@Dobiasd With tf-nightly-2.0-preview the code seems to work correctly:
```python
...
...
Traceback (most recent call last):
  File "p.py", line 16, in <module>
    result = model.predict(np.ones((batch_size, 8, 8, 6)), batch_size=batch_size)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow_core/python/keras/engine/training.py", line 872, in predict
    use_multiprocessing=use_multiprocessing)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow_core/python/keras/engine/training_arrays.py", line 717, in predict
    callbacks=callbacks)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow_core/python/keras/engine/training_arrays.py", line 395, in model_iteration
    aggregator.aggregate(batch_outs, batch_start, batch_end)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow_core/python/keras/engine/training_utils.py", line 308, in aggregate
    result.aggregate(batch_element, batch_start, batch_end)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow_core/python/keras/engine/training_utils.py", line 233, in aggregate
    batch_element.shape, self.results.shape))
ValueError: Mismatch between expected batch size and model output batch size. Output shape = (20, 6, 6, 32), expected output shape = shape (10, 6, 6, 32)
ubuntu@ubuntu:/v# python
Python 2.7.15+ (default, Nov 27 2018, 23:36:35) 
[GCC 7.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
>>> tf.version.VERSION
'2.0.0-dev20190713'
>>> tf.version.GIT_VERSION
'v1.12.1-6246-g5d4a6cee73'
>>> 

```

**Comment by Dobiasd** [comment]
@yongtang

> With tf-nightly-2.0-preview the code seems to work correctly

Thanks for the confirmation. I guess this was to be expected since [the fix](https://github.com/tensorflow/tensorflow/commit/37fcf0a0e04b2014864936397c25e6c398135772) includes an explicit test for this. :+1:
