### ISSUE TITLE
Logging doesn't produce any output in console or in Jupyter

### ISSUE THREAD

**Issue by ilblackdragon** [tensorflow/tensorflow#3047]
Currently running examples leads to a void of empty output.
Both in console and in Jupyter notebooks. Which for example of LinearClassifier leads to a "stuck" model because steps by default is None.

**Comment by martinwicke** [comment]
Should we simply force --alsologtostderr, at least in opensource (only file logging is highly unusual), and possibly whenever we detect we're running in an interactive environment?

**Comment by martinwicke** [comment]
Hm. So the logger is already configured to make a StreamHandler which should by default point to stderr (https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/platform/tf_logging.py#L46). Does jupyter discard stderr? Do we have to log to stdout for it to show up?

**Comment by aselle** [comment]
Automatically closing due to lack of recent activity. Please reopen when further information becomes available.

**Comment by ilblackdragon** [comment]
So to make it work in Jupyter, one right now needs to add 
`tf.logging.set_verbosity(tf.logging.INFO)`. Also it prints right now in red as it's `stderr`.

We should support a way to print into `stdout` and by default show `INFO`.

**Comment by drpngx** [comment]
Is this still current?

**Comment by martinwicke** [comment]
The problem persists.

**Comment by dashesy** [comment]
@ilblackdragon setting `tf.logging.set_verbosity(tf.logging.INFO)` did not produce any logging in Jupyter (QtConsole) for me, but I can see the logs in `ipython` shell.

**Comment by andimarafioti** [comment]
Same for me, I don't see any logging in the Jupyter notebook no matter the logging level that I set.

**Comment by tengerye** [comment]
No logging for me, either.

**Comment by samuela** [comment]
FWIW this isn't working for me either. I'm not running in ipython/jupyter. I've tried `tf.logging.set_verbosity(tf.logging.DEBUG)`, `tf.logging.set_verbosity(0)`, and pretty much everything else I can think of. But I'm not seeing anything from `tf.logging.info(...)` in stdout or stderr.
