### ISSUE TITLE
get the planning path from zed camera

### ISSUE THREAD

**Issue by abdo-robotic** [tensorflow/tensorflow#30481]
hello
my question is about how can benefit from planning path topic get from Zed and trace the trajectory of zed motion

**Comment by gadagashwini** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged//tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.

**Comment by abdo-robotic** [comment]
thank you sire
