### ISSUE TITLE
Can't compile TensorFlow 1.3 on Jetson TX2

### ISSUE THREAD

**Issue by a-gn** [tensorflow/tensorflow#30482]
**System information**
- OS Platform and Distribution: Ubuntu 16.04 on Jetson TX2
- TensorFlow installed from: source
- TensorFlow version: 1.3.1
- Python version: 3.5.2
- Bazel version (if compiling from source): 0.4.5 (not working, see below)
- GCC/Compiler version (if compiling from source): 5.4.0
- CUDA/cuDNN version: CUDA 8.0, cuDNN 6.0.
- GPU model and memory: [NVIDIA Pascal GPU, 8GB 128-bit LPDDR4 Memory](https://developer.nvidia.com/embedded/jetson-tx2)

**Describe the problem**

I need to build TensorFlow 1.3 on a Jetson TX2 machine (aarch64). I can't get the build to work, since I don't have Bazel for aarch64 and can't seem to build it. Since TensorFlow can be used on Jetson TX2, I guess that I'm not building it the right way.

**Provide the exact sequence of commands / steps that you executed before running into the problem**

Follow [all the steps in the Bazel installation guide](https://docs.bazel.build/versions/master/install-ubuntu.html#install-with-installer-ubuntu), then

```bash
wget https://github.com/tensorflow/tensorflow/archive/v1.3.1.tar.gz
tar zxf v1.3.1.tar.gz
cd tensorflow-1.3.1
./configure
```

The output:
```
/usr/local/bin/bazel: line 88: /usr/local/lib/bazel/bin/bazel-real: cannot execute binary file: Exec format error
/usr/local/bin/bazel: line 88: /usr/local/lib/bazel/bin/bazel-real: Success
```

I realize that this is a Bazel problem, but since I can't figure out how to build Bazel for that machine, I may have gotten the building method wrong.

**Comment by gunan** [comment]
1.3 is well outside our support windows. Please try again with a more recent release branch.
