### ISSUE TITLE
TOCO input_shape not working as expexted

### ISSUE THREAD

**Issue by mabdullahrafique** [tensorflow/tensorflow#30499]
Hello!
I have converted deeplabv3 model to tflite using TOCO with following command.
`toco --graph_def_file="/home/abdullah/frozen_inference_graph.pb" --output_file="model1.tflite" --output_format="TFLITE" --input_arrays='sub_7' --output_arrays="ResizeBilinear_3" --input_shape= 1,1024,1024,3
`
So, tflite model should take (1, 1024, 1024, 3) input. But when I try to test this model on my laptop for testing using this code it gives output of dimensions mismatch and is still expecting input of (1, 513, 513, 3).

Here is Inference code. 

    import tensorflow as tf
    import numpy as np
    from PIL import Image
    import matplotlib.pyplot as plt

    interpreter = tf.contrib.lite.Interpreter(model_path='/home/abdullah/Documents/Company Work/TFlite/model1.tflite')
    interpreter.allocate_tensors()

    input_details = interpreter.get_input_details()
    output_details = interpreter.get_output_details()

    quantization = None
    using_type = input_details[0]['dtype']

    size = 1024

    image = Image.open('/home/abdullah/Pictures/xyz.jpg')
    image = image.resize((size, size))

    input_shape = input_details[0]['shape']
    image = np.array(image)
    image = image.reshape(1, size, size, 3)
    image = image/127 -1
    input_data = image.astype(using_type)

    print(input_details)

    interpreter.set_tensor(input_details[0]['index'], input_data)
    interpreter.invoke()
    output_data = interpreter.get_tensor(output_details[0]['index'])
    output_data = output_data.reshape(size, size, 21)

    labels = np.argmax(output_data, -1)
    labels = labels.reshape(size, size)

    plt.imshow(labels)
    plt.show()
    print(labels.shape)

    print(labels)
 
I am getting following error. 

`Traceback (most recent call last):
  File "infer.py", line 36, in <module>
    interpreter.set_tensor(input_details[0]['index'], input_data)
  File "/home/abdullah/anaconda3/envs/tflow/lib/python3.6/site-packages/tensorflow/contrib/lite/python/interpreter.py", line 151, in set_tensor
    self._interpreter.SetTensor(tensor_index, value)
  File "/home/abdullah/anaconda3/envs/tflow/lib/python3.6/site-packages/tensorflow/contrib/lite/python/interpreter_wrapper/tensorflow_wrap_interpreter_wrapper.py", line 133, in SetTensor
    return _tensorflow_wrap_interpreter_wrapper.InterpreterWrapper_SetTensor(self, i, value)
ValueError: Cannot set tensor: Dimension mismatch
`

But when I set size=513 it works like charm. 
Moreover, when I print **input_details = interpreter.get_input_details()**
It prints  
`[{'name': 'sub_7', 'index': 283, 'shape': array([  1, 513, 513,   3], dtype=int32), 'dtype': <class 'numpy.float32'>, 'quantization': (0.0, 0)}]
`

Kindly tell me how should I solve this.

**System information**

- OS Platform and Distribution : Ubuntu 18.04):
- TensorFlow installed from : Pip install tensorflow
- TensorFlow version : 1.10.1
- Python version: Python 3.6.8
- Bazel version : NA
- GCC/Compiler version : NA
- CUDA/cuDNN version : 10.0/7.4 
- GPU model and memory: Gtx 1060 and 16 gb RAM

**Comment by liyunlu0618** [comment]
The tflite graph would expect the same input shape as the tf graph. If you want it to be able to take a larger image, you can try:

interpreter.resize_tensor_input(self, input_index, tensor_size)
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/python/interpreter.py#L406

Remember to call interpreter.allocate_tensors() afterwards, since you need to allocate more memory.
