### ISSUE TITLE
/etc/bash.bashrc leads to scp fail

### ISSUE THREAD

**Issue by zzc407063335** [tensorflow/tensorflow#30495]
I tried to copy my model files to a remote docker container using scp, but the ASCII welcome painting and warning sentences, i.e., the logo of "tensorflow" and "WARNING: You are running this container as root ...... ", cause a transfer failure. As `scp` uses `ssh` as the backend, it will fail if you print something when init an interactive shell.

**Comment by mihaimaruseac** [comment]
Can you post the error message and the command you used?

Afaik, motd doesn't interfere with scp.

**Comment by zzc407063335** [comment]
> Can you post the error message and the command you used?
> 
> Afaik, motd doesn't interfere with scp.

I have fixed this problem by removing the `cat` command in /etc/bash.bashrc. The image tag I am using is `tensorflow:1.14.0-gpu-py3`. I know that `motd` does not affect the scp transfer, but the `cat` and `echo` command in /etc/bash.bashrc cause the transfer to fail. I think this is a potential problem for the users who are not familiar with linux. Thanks, close ~
