### ISSUE TITLE
Null Pointer Bug for InferenceContext* in Linux

### ISSUE THREAD

**Issue by zicofish** [tensorflow/tensorflow#30494]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution: Linux CentOS 7 
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 1.14.0
- Python version: 3.6.8

**Describe the current behavior**
When adding a custom op in C++, the shape function passes a NULL InferenceContext pointer.

**Describe the expected behavior**
The pointer should not be NULL. (I have also tested it on Mac OS, and it works fine. But on Linux, it gives a null pointer.)

**Code to reproduce the issue**
This code (as a file `zero_out.cc`) is taken directly from `https://www.tensorflow.org/guide/extend/op`.
```
#include "tensorflow/core/framework/op.h"
#include "tensorflow/core/framework/shape_inference.h"
#include "tensorflow/core/framework/op_kernel.h"
#include <iostream>

using namespace tensorflow;
using shape_inference::InferenceContext;

REGISTER_OP("ZeroOut")
    .Input("to_zero: int32")
    .Output("zeroed: int32")
    .SetShapeFn([](InferenceContext* c) {
      std::cout << "c address: " << c << std::endl;
      c->set_output(0, c->input(0));
      return Status::OK();
    });

class ZeroOutOp : public OpKernel {
 public:
  explicit ZeroOutOp(OpKernelConstruction* context) : OpKernel(context) {}

  void Compute(OpKernelContext* context) override {
      // Just leave it empty
  }
};

REGISTER_KERNEL_BUILDER(
    Name("ZeroOut")
    .Device(DEVICE_CPU),
    ZeroOutOp);

```
Compile the op with the commands:
```
TF_CFLAGS=( $(python -c 'import tensorflow as tf; print(" ".join(tf.sysconfig.get_compile_flags()))') )
TF_LFLAGS=( $(python -c 'import tensorflow as tf; print(" ".join(tf.sysconfig.get_link_flags()))') )
g++ -std=c++11 -shared zero_out.cc -o zero_out.so -fPIC ${TF_CFLAGS[@]} ${TF_LFLAGS[@]} -O2
```
Run the op:
```
import tensorflow as tf
zero_out_module = tf.load_op_library('./zero_out.so')
with tf.Session(''):
  zero_out_module.zero_out([[1, 2], [3, 4]]).eval()
```
This prints the following:
```
c address: 0
Segmentation fault
```

**Comment by Leslie-Fang** [comment]
@acs6610987 I can exactly reproduce your issue with pip install tensorflow==1.14.0
However if I build from 1.14 source code I got different error message:
```
tensorflow.python.framework.errors_impl.InternalError: Missing 0-th output from {{node ZeroOut}}
```

**Comment by masotrix** [comment]
I got NULL pointer too as the address of InferenceContext*. Downgraded to 1.13.0 and it work now.

**Comment by laket** [comment]
This problem might come from the difference of compilers. In #31335, it is recommended that using the docker container provided in [custom-op](https://github.com/tensorflow/custom-op) to resolve this problem.

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.
