### ISSUE TITLE
[Feature] To support casting float32 to int32 in HEX format

### ISSUE THREAD

**Issue by ghostplant** [tensorflow/tensorflow#30493]
**System information**
- TensorFlow version (you are using):
    1.13.x
- Are you willing to contribute it (Yes/No):
    Yes

**Describe the feature and the current behavior/state.**
I want something like `int32_tensor = tf.float_to_hexint(fp32_tensor)` which allows me to get the hex value representation and can be used to further compute with bit-wise operators.

**Will this change the current api? How?**
No, just extend a new op to handle it.

**Who will benefit with this feature?**
Any requirement that is needed to edit the bit value for a float32-type tensor.

**Any Other info.**
No.

**Comment by wangpengmit** [comment]
Hi ghostplant, by HEX do you mean the raw bits of a float32? If you want to learn how to add an new op and contribute, you can read https://www.tensorflow.org/guide/extend/op and https://github.com/tensorflow/tensorflow/commit/688e638da7ebe1f805107f56946ef400ffd89112 as an example.

**Comment by ghostplant** [comment]
@wangpengmit Yes, it is something to make `int int_val = *(int*)&float_val;`
I am using old version TF1.14 which is not suitable to upgrade to 2.0 for other unstable purpose, so I'm afraid I cannot establish full developing environment for latest Tensorflow 2.0 and managing test requirement for all combinations, like GPU, CPU, TF2.0, TF1.14, Windows, Linux, ..

**Comment by wangpengmit** [comment]
I see. I'll add the op.

**Comment by ghostplant** [comment]
@wangpengmit Great, thanks! And `float float_val = *(float*)&int_val;` is needed as well, since the value should be turned back after some int-level / bit-wise operation.

**Comment by ghostplant** [comment]
@wangpengmit I'm also sure whether adding this op will support 2.0 only, or supporing 1.14 as well?

**Comment by wangpengmit** [comment]
An ordinary op like this will work for all versions.

**Comment by wangpengmit** [comment]
@alextp do you know of any existing ops for this? And if not, do you think they should be added as custom ops (https://github.com/tensorflow/community/pull/126/files) or to the core?

**Comment by alextp** [comment]
I think you're talking about tf.bitcast https://www.tensorflow.org/api_docs/python/tf/bitcast

**Comment by khatrishubham88** [comment]
Hi,
It appears this functionality is still not present, or am I confused. The desired type would be equivalent to https://docs.python.org/3/library/functions.html#hex, int should be convertible to hex string and back.
