### ISSUE TITLE
No `output_shape` after tf.keras layer/model build() and call. Is it intended?

### ISSUE THREAD

**Issue by dalgu90** [tensorflow/tensorflow#30498]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 16.04
- TensorFlow installed from (source or binary): binary.
- TensorFlow version (use command below): `2.0.0-beta1` and `tf_nightly_gpu_2.0_preview-2.0.0.dev20190708`
- Python version: 3.6.8
- CUDA/cuDNN version: CUDA 10.0
- GPU model and memory: without and with GPU (P100)

**Describe the current behavior**

Hi, all. When I tried to use `model.summary()`, the output shapes were printed as **multiple**. After few tries, I realized that the `output_shape` of keras layers/models are not determined even after the layer/model was built and called. Here are short examples.

1. Keras layer
```
import tensorflow as tf

dense = tf.keras.layers.Dense(2)
dense.build(input_shape=3)

input_tensor = tf.ones((5, 3), tf.float32)
output_tensor = dense(input_tensor)

# The line below raises "AttributeError: The layer has never been called and thus has no defined output shape."
print(dense.output_shape)
```

2. Keras model
```
import tensorflow as tf

model = tf.keras.models.Sequential([
    tf.keras.layers.Dense(2),
    tf.keras.layers.ReLU(),
    tf.keras.layers.Dense(4),
])

model.build(input_shape=(None, 3))

input_tensor = tf.ones((5, 3), tf.float32)
output_tensor = model(input_tensor)

# The line below raises "AttributeError: The layer has never been called and thus has no defined output shape."
print(model.output_shape)
```

**Describe the expected behavior**
I think keras layer/model should have `output_shape`, but they aren't. Please see if it's intended. I've just started to migrate from TF 1.x to TF 2.0 and to use keras APIs, so I might be wrong when using keras API.

**Code to reproduce the issue**
Described above.

**Other info / logs**

**Comment by gadagashwini** [comment]
I am able to reproduce the issue on Colab with tensorflow 2.0.0.beta1 and tf_nightly_gpu_2.0_preview-2.0.0.dev20190708.

**Comment by pavithrasv** [comment]
@dalgu90 `output_shape` is not supported in eager. https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/keras/engine/base_layer.py#L1493

**Comment by dalgu90** [comment]
@pavithrasv Oh I see. Then the issue here is the wrong type and description of the exception raised.

**Comment by dalgu90** [comment]
I'm closing this issue since it's the desired behavior. Hope the error message will be corrected in the future.
