### ISSUE TITLE
Custom OP Documentation: `-D_GLIBCXX_USE_CXX11_ABI=0` not required anymore?

### ISSUE THREAD

**Issue by PhilJd** [tensorflow/tensorflow#30492]
## URL(s) with the issue:

https://www.tensorflow.org/guide/extend/op#compile_the_op_using_your_system_compiler_tensorflow_binary_installation
(Last Note of the paragraph).

## Description of issue (what needs changing):
The documentation states that customs ops for the binary pip packages should be compiled with `-D_GLIBCXX_USE_CXX11_ABI=0`. For me this actually had to be removed (python 3.7, tensorflow-gpu==1.14.0  from pip), so I guess tf-1.14 is now built with `gcc > 4`?
If someone can confirm, I could open a PR :)

**Comment by sanatmpa1** [comment]
@PhilJd,

The link that has been provided is broken and here is the [new link](https://www.tensorflow.org/guide/create_op#compile_the_op_using_your_system_compiler_tensorflow_binary_installation) for creating OP and the documentation states that, `If you compile your op library with gcc>=5, add -D_GLIBCXX_USE_CXX11_ABI=0 to the command line to make the library compatible with the older abi`. Do you think still this is an issue?

**Comment by PhilJd** [comment]
Hi,
I have no idea, I haven't compiled a custom op for TF in a long tim - I also don't remember in which setup this was so I don't have a way to reproduce anymore. Should we close this as obsolete and if someone still runs into this issue they could reopen?

**Comment by sanatmpa1** [comment]
@PhilJd,

Thanks for the confirmation. I am closing this issue and they can create a new one/reopen if there are any further questions.
