### ISSUE TITLE
Official windows pip package build settings could be better

### ISSUE THREAD

**Issue by kile0** [tensorflow/tensorflow#30509]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: n/a
- TensorFlow installed from (source or binary): binary
- TensorFlow version: 1.14.0
- Python version: 3.7.0
- Installed using virtualenv? pip? conda?: pip
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Describe the problem**
The build settings for the Tensorflow package produced and distributed via pip for windows aren't using the compiler flags that would result in optimal performance. I.e. the pip distributed package doesn't appear to use AVX2 instructions.

Given this, we suspect the package is also not built using LTCG, fp:fast, the new /Ob3 inlining, or the new exception handling /FH4 flags. A nice performance win (and binary size win in the case of /FH4) ought to come out of the small change of simply throwing the appropriate flags.

**Any other info / logs**
Output from running Tensorflow models on MLPerf: "Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2"

**Comment by gunan** [comment]
On all platforms, we aim to build packages that can run on the widest range of machines.
Therefore, we intentionally only build with AVX support.
Therefore, for performance we recommend building TF from sources.
