### ISSUE TITLE
 the ipynb 'Get started with TensorFlow 2.0 for experts' exhausts RAM memory when it runs on GPU

### ISSUE THREAD

**Issue by ruipimenta** [tensorflow/tensorflow#30501]
When I run the notebook 'Get started with TensorFlow 2.0 for experts' using tensorflow GPU all RAM (12gb on Colab) gets consumed before training starts. If I run on colab without GPU it is slow but it runs to the end

**System information**
Colab (but also debian linux 10)

**Comment by ravikyram** [comment]
I tried checking with colab link provided by you and observed it is not consuming more RAM memory. Can you please restart runtime in google colab and check if the issue still persists.

**Comment by ruipimenta** [comment]
That was my mistake. I did not notice I was running tensorflow 1.14 instead of tensorflow 2.0. Sorry
