### ISSUE TITLE
Convert Tensorflow Model to Tensorflow Lite Format Model

### ISSUE THREAD

**Issue by Deepak-HpyAda** [tensorflow/tensorflow#30515]
Convert Tensorflow Model to Tensorflow Lite Format [Conversion + Build]

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Mac OS High Sierra 10.13.6
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): Anaconda Navigator
- TensorFlow version: 1.14.0
- Python version: 3.7.0
- Installed using virtualenv? pip? conda?: conda
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory: No 

I trained my custom model for tensorflow by following this tutorial
https://tensorflow-object-detection-api-tutorial.readthedocs.io/en/latest/training.html
I made all the code work in macOS
I got the output with python code.

My query here is 
I need to run my model in unity through TensorflowLite Plugin
So, I have to convert my tensorflow model to tensorflow lite format
My model's size is 55.5Mb 
I need help, How to convert my model to tensorflow lite model

**Comment by ravikyram** [comment]
This question is better asked on StackOverflow since it is not a bug or feature request. There is also a larger community that reads questions there and provide better and faster support for such issues. Thanks!
