### ISSUE TITLE
Loading Keras model: TypeError: __init__() missing 1 required positional argument: 'fn'

### ISSUE THREAD

**Issue by JoaoLages** [tensorflow/tensorflow#30521]
- Installed with `pip install tensorflow-gpu`, and also tried with `pip install tensorflow` which yielded the same issue.
- tensorflow 1.14
- Keras-Applications 1.0.8 
- Keras-Preprocessing 1.1.0

After saving model with `tf.keras.models.save_model(model=self.predict_model, filepath=path)`, we try to load with `tf.keras.models.load_model(path, custom_objects={'tf': tf})` and it yields the error that I reported in the title.
What possible conflict of packages may I have? Or is this a known bug?

**Comment by JoaoLages** [comment]
All packages in the environment:
```
Package              Version  Location
-------------------- -------- ------------------------
absl-py              0.7.1
astor                0.8.0
backcall             0.1.0
boto3                1.9.184
botocore             1.12.184
cycler               0.10.0
decorator            4.4.0
docutils             0.14
gast                 0.2.2
google-pasta         0.1.7
grpcio               1.22.0
h5py                 2.9.0
ipython              7.6.1
ipython-genutils     0.2.0
jedi                 0.14.0
jmespath             0.9.4
joblib               0.13.2
Keras-Applications   1.0.8
Keras-Preprocessing  1.1.0
kiwisolver           1.1.0
Markdown             3.1.1
matplotlib           3.1.1
networkx             2.3
nltk                 3.4.4
numpy                1.16.4
pandas               0.24.2
parso                0.5.0
pexpect              4.7.0
pickleshare          0.7.5
pip                  19.1.1
prompt-toolkit       2.0.9
protobuf             3.8.0
ptyprocess           0.6.0
Pygments             2.4.2
pyparsing            2.4.0
python-dateutil      2.8.0
pytz                 2019.1
PyYAML               5.1.1
recordclass          0.11.1
s3transfer           0.2.1
scikit-learn         0.21.2
scipy                1.3.0
seaborn              0.9.0
setuptools           41.0.1
six                  1.12.0
sklearn              0.0
tensorboard          1.14.0
tensorflow           1.14.0
tensorflow-estimator 1.14.0
termcolor            1.1.0
torch                1.1.0
tqdm                 4.32.2
traitlets            4.3.2
urllib3              1.25.3
wcwidth              0.1.7
Werkzeug             0.15.4
wheel                0.33.4
wordninja            0.1.5
wrapt                1.11.2
```

**Comment by ravikyram** [comment]
In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thanks!

**Comment by JoaoLages** [comment]
Just create any Keras' model, save it and load with the commands I mentioned

**Comment by ravikyram** [comment]
@JoaoLages 
Can you please check attached zip folder.I am able to save and load the Keras folder.Please, let me know if i am wrong.Thanks!
[keras.zip](https://github.com/tensorflow/tensorflow/files/3381132/keras.zip)

**Comment by ravikyram** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Comment by JoaoLages** [comment]
The problem occurs when saving a Keras model (`save_model` function) in tensorflow-gpu==1.14.0 and loading it in tensorflow==1.14 (`load_model` function)

**Comment by ravikyram** [comment]
@JoaoLages 
I tried with tensorflow-gpu==1.14.0 and able to save and load successfully.Please, find the gist [here](https://colab.sandbox.google.com/gist/ravikyram/014783bb590e13b1884256509b83d0d8/untitled249.ipynb).Thanks!

**Comment by JoaoLages** [comment]
@ravikyram can you try to load it with `tensorflow==1.14`? (and not tensorflow-gpu)

**Comment by ravikyram** [comment]
@JoaoLages 
Loaded using `!pip install tensorflow==1.14`in the below attachment . Request you to have a look on this and let me know if the issue still persists.Thanks!
[keras.zip](https://github.com/tensorflow/tensorflow/files/3690276/keras.zip)

**Comment by JoaoLages** [comment]
I am closing the issue since I am not able to reproduce this error out of my environment.

**Comment by JoaoLages** [comment]
Solved!
`self.model = tf.keras.models.load_model(model_file, custom_objects={'tf': tf}, compile=False)` - not able to use the loss function but works for prediction
