### ISSUE TITLE
not show `raise ValueError` but `unsupported operand` error when using modular arithmetic as minus integer in TF 1.13.1, 1.14.0

### ISSUE THREAD

**Issue by graykode** [tensorflow/tensorflow#30526]
1. tf 1.13.1
![image](https://user-images.githubusercontent.com/10525011/60887589-bc055580-a28f-11e9-8cfd-c08e960a227e.png)

2. tf1.14.0
![image](https://user-images.githubusercontent.com/10525011/60888239-4bf7cf00-a291-11e9-9f37-4c9781883e86.png)

3. tf2.0.0a0
![image](https://user-images.githubusercontent.com/10525011/60887966-a5133300-a290-11e9-9831-9470b875d5fe.png)

Why used `NotImplemented`in `__mod__` and `__rmod__` https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/framework/tensor_shape.py#L221? **It makes to be confused '%' operand is not working**

when people try modular arithmetic with minus integer, error with `raise ValueError("Dimension %d must be >= 0" % self._value)` is feel more good instead of error with `TypeError: unsupported operand type(s) for %:`

What else?
```python
  def __mod__(self, other):
    """Returns `self` modulo `other`.

    Dimension moduli are computed as follows:

    ```python
    tf.Dimension(m)    % tf.Dimension(n)    == tf.Dimension(m % n)
    tf.Dimension(m)    % tf.Dimension(None) == tf.Dimension(None)
    tf.Dimension(None) % tf.Dimension(n)    == tf.Dimension(None)
    tf.Dimension(None) % tf.Dimension(None) == tf.Dimension(None)
    ```

    Args:
      other: Another Dimension, or a value accepted by `as_dimension`.

    Returns:
      A Dimension whose value is `self` modulo `other`.
    """
    other = as_dimension(other)
    if self._value is None or other.value is None:
      return Dimension(None)
    else:
      return Dimension(self._value % other.value)
```
Thanks

**Comment by yongtang** [comment]
Added PR #30563 for the fix.

**Comment by graykode** [comment]
@yoneken Hello. This is my first time leave issue in tensorflow. I dont know how contribution system working, so I leave issue before pull request and check comment for this issue, then I have plan to pull request. I think it's have more priority for who finding issue How do you think about it? Thanks

**Comment by mihaimaruseac** [comment]
Thank you for the issue and the PR.

As the Pr is merged, closing the issue
