### ISSUE TITLE
Failed to convert ssdlite_mobilenet_v2_coco_2018_05_09 to tflite

### ISSUE THREAD

**Issue by AlexZot** [tensorflow/tensorflow#30524]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Google colaboratory
- TensorFlow installed from (source or binary): idk
- TensorFlow version (or github SHA if from source): 1.14

**Provide the text output from tflite_convert**

```
---------------------------------------------------------------------------

ConverterError                            Traceback (most recent call last)

<ipython-input-5-fc0e59056dc1> in <module>()
----> 1 tflite_model = converter.convert()
      2 open("converted_model.tflite", "wb").write(tflite_model)

2 frames

/usr/local/lib/python3.6/dist-packages/tensorflow/lite/python/lite.py in convert(self)
    902           input_arrays_with_shape=self._input_arrays_with_shape,
    903           output_arrays=self._output_arrays,
--> 904           **converter_kwargs)
    905 
    906     if self._is_calibration_quantize():

/usr/local/lib/python3.6/dist-packages/tensorflow/lite/python/convert.py in toco_convert_graph_def(input_data, input_arrays_with_shape, output_arrays, *args, **kwargs)
    371   data = toco_convert_protos(model_flags.SerializeToString(),
    372                              toco_flags.SerializeToString(),
--> 373                              input_data.SerializeToString())
    374   return data
    375 

/usr/local/lib/python3.6/dist-packages/tensorflow/lite/python/convert.py in toco_convert_protos(model_flags_str, toco_flags_str, input_data_str)
    170       stderr = _try_convert_to_unicode(stderr)
    171       raise ConverterError(
--> 172           "TOCO failed. See console for info.\n%s\n%s\n" % (stdout, stderr))
    173   finally:
    174     # Must manually cleanup files.

ConverterError: TOCO failed. See console for info.
2019-07-09 12:08:44.812119: I tensorflow/lite/toco/import_tensorflow.cc:1336] Converting unsupported operation: TFLite_Detection_PostProcess
2019-07-09 12:08:44.833564: F tensorflow/lite/toco/tooling_util.cc:918] Check failed: GetOpWithOutput(model, output_array) Specified output array "detection_boxes" is not produced by any op in this graph. Is it a typo? This should not happen. If you trigger this error please send a bug report (with code to reporduce this error), to the TensorFlow Lite team.
Aborted (core dumped)

```

Also, please include a link to a GraphDef or the model if possible:
https://drive.google.com/open?id=1HJ0bnrOok4Brd5IcB30HYn80itE4dH8_

**Any other info / logs**

I'm using model ssdlite_mobilenet_v2_coco_2018_05_09 from zoo. Have trained it and converted ckpt with command:
`export_tflite_ssd_graph.py --pipeline_config_path training/ssdlite_mobilenet_v2_coco.config --trained_checkpoint_prefix training/model.ckpt-19780 --output_directory tflite_graph --add_postprocessing_op True`

I'm using Python API for conversion of model. My code:
```
import tensorflow as tf
graph_def_file = "/content/tflite_graph.pb"
input_arrays = ["normalized_input_image_tensor"]
output_arrays = ["detection_boxes", "detection_classes", "detection_scores", "num_boxes"]

converter = tf.lite.TFLiteConverter.from_frozen_graph(
  graph_def_file, 
  input_arrays, 
  output_arrays, 
  input_shapes={'normalized_input_image_tensor':[1, 300, 300, 3]}
  )
tflite_model = converter.convert()
open("converted_model.tflite", "wb").write(tflite_model)
```

**Comment by jdduke** [comment]
Hi @AlexZot, I'm unable to access the model you linked, would you mind updating?

What happens if you change `output_arrays` to:
```
output_arrays = [
        'TFLite_Detection_PostProcess', 'TFLite_Detection_PostProcess:1',
        'TFLite_Detection_PostProcess:2', 'TFLite_Detection_PostProcess:3'
    ]
```

**Comment by val9299** [comment]
Hi @AlexZot, 

try output_arrays = ['raw_outputs/box_encodings','raw_outputs/class_predictions']

I'm facing the same issue. Using --add_postprocessing_op True should give an output_array of detection_boxes,detection_classes,detection_scores,num_boxes but it somehow doesn't. How export_tflite_ssd_graph.py has to be used to get a model with 4 outputs? So output_arrays = ['detection_boxes', 'detection_classes', 'detection_scores', 'num_boxes'] would be correct

@jdduke: You can find the model in the model zoo: https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/detection_model_zoo.md

**Comment by AlexZot** [comment]
@jdduke Here is link: https://drive.google.com/open?id=1HJ0bnrOok4Brd5IcB30HYn80itE4dH8_
@val9299 I know that is working with raw outputs, but it means that I have to decode predictions manually.

**Comment by srjoglekar246** [comment]
Hey Alex, can you try adding `converter.allow_custom_ops = True` ?

**Comment by val9299** [comment]
I opened a new issue for specifically my case: https://github.com/tensorflow/tensorflow/issues/31015
Thanks for helping!

**Comment by AlexZot** [comment]
@srjoglekar246 omg, that's worked! Thank you good man! How does this array: ['detection_boxes', 'detection_classes', 'detection_scores', 'num_boxes'] corresponds to this: [TFLite_Detection_PostProcess', 'TFLite_Detection_PostProcess:1', 'TFLite_Detection_PostProcess:2', 'TFLite_Detection_PostProcess:3']

**Comment by val9299** [comment]
I also tried the suggestion. But it looks like the new tflite model has raw outputs just in another format. I thought the goal would be having processed outputs like detection_boxes, detection_classes,...? To get a model like this, something already has to be changed in the freezing process with export_tflite_ssd_graph.py but I also would like to know what has to be changed to get it working.

**Comment by srjoglekar246** [comment]
@AlexZot The `TFLite_Detection_PostProcess:1` value lets the converter know that `detection_classes` is the output from the post-processing op at index 1.

**Comment by kangkang59812** [comment]
> Hey Alex, can you try adding `converter.allow_custom_ops = True` ?

Sorry to bother, I meet this `Converting unsupported operation: TFLite_Detection_PostProcess` too. Where should I add this `converter.allow_custom_ops = True`?

**Comment by kangkang59812** [comment]
> @srjoglekar246 omg, that's worked! Thank you good man! How does this array: ['detection_boxes', 'detection_classes', 'detection_scores', 'num_boxes'] corresponds to this: [TFLite_Detection_PostProcess', 'TFLite_Detection_PostProcess:1', 'TFLite_Detection_PostProcess:2', 'TFLite_Detection_PostProcess:3']

So how to solve this problem `Converting unsupported operation: TFLite_Detection_PostProcess` exactly? 
(1)export_tflite_ssd_graph.py --pipeline_config_path training/ssdlite_mobilenet_v2_coco.config --trained_checkpoint_prefix training/model.ckpt-19780 --output_directory tflite_graph --add_postprocessing_op True. ---->  add_postprocessing_op True or Flase

**Comment by srjoglekar246** [comment]
@kangkang59812 Please look at the following snippet in the first comment:

```
import tensorflow as tf
graph_def_file = "/content/tflite_graph.pb"
input_arrays = ["normalized_input_image_tensor"]
output_arrays = ["detection_boxes", "detection_classes", "detection_scores", "num_boxes"]

converter = tf.lite.TFLiteConverter.from_frozen_graph(
  graph_def_file, 
  input_arrays, 
  output_arrays, 
  input_shapes={'normalized_input_image_tensor':[1, 300, 300, 3]}
  )
tflite_model = converter.convert()
open("converted_model.tflite", "wb").write(tflite_model)
```

There, we need to add `converter.allow_custom_ops = True` for the TFLite SSD inference to work.

And about your second comment: Yes, we need to set `--add_postprocessing_op True`

**Comment by kangkang59812** [comment]
@srjoglekar246  The produced  `converted_model.tflite` is same as the .tflite produced by `bazel` command.  What makes me confused is that the result is different  between `converted_model.tflite` and `tflite_graph.pb`.  I think it still can't convert the `postprocessing_op` sucessfully. For exampe, the bbox has negative values in `converted_model.tflite`'s result, but the values are nomal in 'tflite_graph.pb''s result.

**Comment by srjoglekar246** [comment]
The result, mathematically, shouldn't be that different with our custom op (atleast for 10 detections or so). The reason we do this, is that using the custom op is much easier/faster than using multi-class Non-Max-Suppression that tensorflow does in its graphs.

There is one way to do this with our experimental new converter, which supports builtin NMS ops without using the custom op.

Could you try the following:
1. Modify `pipeline config` as follows:

Before:
```
   post_processing {
      batch_non_max_suppression {
        score_threshold: 0.300000011921
        iou_threshold: 0.600000023842
        max_detections_per_class: 100
        max_total_detections: 100
      }
      score_converter: SIGMOID
    }
```

After:
```
post_processing {
      batch_non_max_suppression {
        score_threshold: 0.300000011921
        iou_threshold: 0.600000023842
        max_detections_per_class: 10
        max_total_detections: 10
        use_class_agnostic_nms: true
        use_static_shapes: true
      }
      score_converter: SIGMOID
    }
```

This reduces the complexity of the NMS graph for TFLite inference.
Also remove this from the config, if present:
`batch_norm_trainable: true`

2. Then, export the inference graph using [TF Object Detection's script](https://pythonprogramming.net/testing-custom-object-detector-tensorflow-object-detection-api-tutorial/) with the following params:
```
--input_type image_tensor --input_shape 1,<height>,<width>,3 --pipeline_config_path /path/to/pipeline.config --trained_checkpoint_prefix /path/to/model.ckpt --output_directory /path/to/output
```

3. Then convert using our experimental converter:
Add this before conversion:
`converter.experimental_new_converter = True`

Use these output arrays:
```
detection_boxes,Postprocessor/BatchMultiClassNonMaxSuppression/stack_3,detection_scores,num_detections
```
Use this input array:
```
Preprocessor/sub
```
Input data type:
```
DT_FLOAT
```

**Comment by kangkang59812** [comment]
@srjoglekar246  Thanks for your patient . I followed the below steps:
1. Following your advice, I change the pipline.config.
2. I use ```
python object_detection/export_tflite_ssd_graph.py \
--pipeline_config_path=$CONFIG_FILE \
--trained_checkpoint_prefix=$CHECKPOINT_PATH \
--output_directory=$OUTPUT_DIR \
--input_type=image_tensor \
--input_shape=1,300,300,3 \
```
to get the .pb file
3.  Then 
```
import tensorflow as tf
graph_def_file = "/Users/kangkang/Documents/code/convert/tflite_graph22.pb"
converter = tf.lite.TFLiteConverter.from_frozen_graph(
    graph_def_file,
    input_arrays=['Preprocessor/sub'],
    output_arrays=['detection_boxes', 'Postprocessor/BatchMultiClassNonMaxSuppression/stack_3',
                   'detection_scores', 'num_detections'],
    input_shapes={'Preprocessor/sub': [1, 300, 300, 3]})
converter.experimental_new_converter = True
tflite_model = converter.convert()
tf_model_files = 'newpost22.tflite'
open(tf_model_files, "wb").write(tflite_model)
```
Thats all what I have done.  Where should I insert your `Input data type:DT_FLOAT`?.  
And I got the error `Check failed: model.HasArray(output_array) Output array not found: detection_boxes`. I am  Very confused about the input and output according to different config.
I upload the [checkpoint](https://drive.google.com/drive/folders/1oaShwaiXsbkPfwG1wa-vDcnFwO9RILCP) on google drive. The model(based on ssd_mobilenet_v2_coco_2018_03_29) is trained on my datasets(55 classes) and the results are good enough on PC. Just want the same result on .tflite.
Thanks sincerely!!!

**Comment by srjoglekar246** [comment]
If latency isn't an issue for you, just use `export_tflite_ssd_graph.py` with the extra param `--use_regular_nms=true`. Does that improve the accuracy?

**Comment by kangkang59812** [comment]
@srjoglekar246 No, the .tflite result on Android is still not the same as .pb result on PC. I have tried `allow_custom_ops ` 、`--use_regular_nms=true` and other methods in the other issues.
