### ISSUE TITLE
How can i make sure the hash is consistent when saving the same model?

### ISSUE THREAD

**Issue by bojangus** [tensorflow/tensorflow#30532]
I'm using the Keras model.save('my_model.h5') function. Every time i save it, the hash changes, even though no changes were made to the weights or settings etc. 

On this page: [link](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/keras/saving/saved_model/save.py), it shows there's a KERAS_CACHE_KEY, is that the culprit? or is some other change/timestamp happening on save? 

I need to identify the specific model in the future and really just want to store it's hash for verification, but if i save the same model twice, i'll never know it was the same one. Can you please help point me in the right direction?

**Comment by gadagashwini** [comment]
@bojangus Please have a look at [link](https://github.com/tensorflow/docs/blob/master/site/en/r2/tutorials/keras/save_and_restore_models.ipynb). Thanks!

**Comment by bojangus** [comment]
@gadagashwini Thank you for the response, but this link is a tutorial on how to save a model. I have no problem saving the models. And i have no problem restoring the models and using them again either. 

I am running the saved models through a hashing function (eg: from the [hashlib](https://docs.python.org/3/library/hashlib.html) module), and the same model comes out with a different hash every time it is saved, even if you re-save it just 5 seconds later. (the weights and parameters haven't changed).

The scenario i'm trying to reach is, the same model is saved at multiple different times, but has the same hash. Any idea on how i can achieve this?

**Comment by bojangus** [comment]
Hi @k-w-w , anything i can do to help clarify this further?

**Comment by bojangus** [comment]
Hi @k-w-w , I realise you're busy, if you could just give me some advice on how to work around it myself, or where to look, that would be great.

**Comment by rmothukuru** [comment]
@bojangus,
Sorry for the delayed response. I think, recommendation in this case is to use [**`Tensorflow Extended, TFX`**](https://www.tensorflow.org/tfx), which effectively handles **`End-To-End Machine Learning Pipelines`**. In your case, the versioning will be taken care by **`Tensorflow Serving`**, a sub system of **`TFX`**.
