### ISSUE TITLE
init_from_checkpoint performing incorrectly

### ISSUE THREAD

**Issue by manurare** [tensorflow/tensorflow#30548]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): Source
- TensorFlow version (use command below): 1.14
- Python version: 2.7
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory: GTX Titan X

**Describe the current behavior**
I have a variable stored in a ckpt called prsr/prior/conv1/weights and i want to do a map assignment to a variable called prsr/prior/conv1/weights_1:0. When I execute the init_from_checkpoint execution it gives the following error 

> ValueError: Assignment map with scope only name prsr/prior/conv1 should map to scope only prsr/prior/conv1/weights. Should be 'scope/': 'other_scope/'.

**Describe the expected behavior**
I think it should assigned correctly the variable from the .ckpt prsr/prior/conv1/weights into the current variable prsr/prior/conv1/weights_1:0 as indicated in the API official documentation:

```
# Initialize partitioned variables using variable's name
init_from_checkpoint('/tmp/model.ckpt',
                     {'old_scope_2/var3': 'new_scope_2/var3'})
```

**Comment by jvishnuvardhan** [comment]
@manurare Can you share a standalone code to reproduce the issue? Thanks!

**Comment by manurare** [comment]
Sorry for the delay. I think I found the issue myself and it was my fault. Thanks for the response nonetheless.
