### ISSUE TITLE
Padded_batch in TF2.0 throws DataLossError: Attempted to pad to a smaller size than the input element. [Op:IteratorGetNextSync]

### ISSUE THREAD

**Issue by rishabhsahrawat** [tensorflow/tensorflow#30557]
I am following [this tutorial](https://www.tensorflow.org/beta/tutorials/load_data/text#split_the_dataset_into_text_and_train_batches) and exactly [here](https://www.tensorflow.org/beta/tutorials/load_data/text#split_the_dataset_into_text_and_train_batches) in
`train_data = train_data.padded_batch(BATCH_SIZE, padded_shapes=([-1],[]))`, it uses the length of the longest sentence in the dataset (which is 16). I want to pad the sentences further to length 8. So, after replacing this 
> **-1**  with **8**
in the line above, it throws the error 

> DataLossError: Attempted to pad to a smaller size than the input element. [Op:IteratorGetNextSync]
on executing `sample_text, sample_labels = next(iter(test_data))

sample_text, sample_labels or on fit method.
I am not sure if this is a bug or a normal behaviour. I want to achieve sentences with shorter paddings. If anyone can help me, I will be very thankful. 
It can be easily done with `tf.keras.preprocessing.sequence.pad_sequences()`but not sure about tf.Data in TF2.0.

**Comment by pandrey-fr** [comment]
Hi,
You simply need to trim your data before instructing padded-batching.
I would recommend doing something in the vein of:
```
train_data = train_data.map(lambda x: x[:8])
train_data = train_data.padded_batch(BATCH_SIZE, padded_shapes=([8], []))
```

I hope this is of help to you! By the way, no offence, but I believe this question would be more suited on a question-answering site like StackOverflow than in a GitHub Issues tracker.

**Comment by rishabhsahrawat** [comment]
Hi @pandrey-fr , thank you for your reply. I tried your suggestion but it is giving me an error since lambda function only takes one argument. The `train_data` is a tf.Dataset type consisting **(data, labels)** tuples and I am not sure how to provide **data** from this tuple to lambda function for slicing. So, I am still stuck after trying many things for last 3 hours.

The reason I posted this question here was because it is a TF document related problem, since it is not clear if [padded_batch](https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/data/Dataset#padded_batch) function will raise an error if one tries to pad with smaller value than the lengths of sentences in the data. There are many documents missing in TF, and this was just one function.

**Comment by pandrey-fr** [comment]
> lambda function only takes one argument

Actually you can have multiple inputs: e.g. to sum two elements `lambda x, y: x + y`, so you should be able to work something around! Good luck :)

> There are many documents missing in TF, and this was just one function.

I strongly agree that the documentation is faulty... This is getting better with time (although the 2.0 release is creating a lot of new issues), and is mainly due to TF being such a big project (I guess it is hard to keep track of everything, even from the inside), but some effort should (in my humble opinion) be made in that direction.

**Comment by rishabhsahrawat** [comment]
thank you again for your suggestion. I still could not do it using `lambda` function because it does not accept tensors and `map` function does not accept numpy objects ([source](https://stackoverflow.com/questions/56075037/how-to-convert-tensor-to-numpy-array-in-tensorflow)), so instead of slicing using `lambda` I used `tf.py_function` and returned back the values to `map` function.

Since I am new to TF, I am sure there are other ways of doing this but I could not find them, if you (or anyone) have any inputs then please share them. I will be happy to add them to my knowledge.
Thank You :)

**Comment by pandrey-fr** [comment]
Seems like a sensible solution! And you are welcome :)

**Comment by ravikyram** [comment]
@rishabhsahrawat 
 let me know if we can close this issue since it looks to be fixed. Thanks!
