### ISSUE TITLE
VS linkage fails with "unresolved external symbol"

### ISSUE THREAD

**Issue by AndreyPlotkinOr** [tensorflow/tensorflow#30552]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10 x64
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): source
- TensorFlow version: git tag v2.0.0_beta1
- Python version: 3.6.7
- Installed using virtualenv? pip? conda?:
- Bazel version (if compiling from source): bazel release 0.24.1
- GCC/Compiler version (if compiling from source): "C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC//bin/amd64/cl.exe"
- Microsoft (R) C/C++ Optimizing Compiler Version 19.00.24234.1 for x64
- CUDA/cuDNN version: 10.1/7.6.1
- GPU model and memory: GeForce GTX 1060 (6GB)

**Describe the problem**
Can't link the code. I get this error:
1>a.obj : error LNK2001: unresolved external symbol "public: int __cdecl google::protobuf::RepeatedPtrField<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > >::size(void)const " (?size@?$RepeatedPtrField@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@protobuf@google@@QEBAHXZ)
1>a.obj : error LNK2001: unresolved external symbol "public: __cdecl tensorflow::SessionOptions::SessionOptions(void)" (??0SessionOptions@tensorflow@@QEAA@XZ)
1>a.obj : error LNK2001: unresolved external symbol "class tensorflow::Session * __cdecl tensorflow::NewSession(struct tensorflow::SessionOptions const &)" (?NewSession@tensorflow@@YAPEAVSession@1@AEBUSessionOptions@1@@Z)
1>b.obj : error LNK2001: unresolved external symbol "public: bool __cdecl google::protobuf::MessageLite::ParseFromArray(void const *,int)" (?ParseFromArray@MessageLite@protobuf@google@@QEAA_NPEBXH@Z)

I checked with dumpbin and didn't find this symbols/exports.
I also tried to patch missing symbols, and it didn't help (https://github.com/guikarist/tensorflow-windows-build-script/blob/master/patches/tf_exported_symbols_msvc.lds)

**Provide the exact sequence of commands / steps that you executed before running into the problem**
I built a tensorflow.dll & tensorflow.lib using this command:
bazel build --config=opt //tensorflow:tensorflow_dll_import_lib

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by gunan** [comment]
@goldiegadde who ran the 2.0 builds.
Goldie, was the GPU windows build successfil for 2.0 release?
Have you ran into this problem yourself?

**Comment by acezzz** [comment]
I encountered the same issue in version 1.14 version. But I think the solution probably works for 2.0 as well. 

The solution is to modify tensorflow\tools\def_file_filter\def_file_filter.py.tpl to add those missing symbols. For instance around line 130.

The long term solution is to modify the rules in this file to include more useful symbols.

**Comment by acezzz** [comment]
The solution proposed at https://github.com/guikarist/tensorflow-windows-build-script/blob/master/patches/tf_exported_symbols_msvc.lds only works for versions earlier than 1.14.

**Comment by AndreyPlotkinOr** [comment]
I edited the file to include missing symbols in v1.14, but it didn't work.

    def_fp.write("\t ??1OpDef@tensorflow@@UEAA@XZ\n")
    def_fp.write("\t ?size@?$RepeatedPtrField@V?$basic_string@DU?$char_traits@D@std@@v?$allocator@D@2@@std@@@protobuf@google@@QEBAHXZ\n")
    def_fp.write("\t ??0SessionOptions@tensorflow@@QEAA@XZ\n")
    def_fp.write("\t ?NewSession@tensorflow@@YAPEAVSession@1@AEBUSessionOptions@1@@z\n")
    def_fp.write("\t ?ParseFromArray@MessageLite@protobuf@google@@QEAA_NPEBXH@Z\n")

Actually TF dll even didn't link.

	Execution platform: @bazel_tools//platforms:host_platform
	   Creating library bazel-out/x64_windows-opt/bin/tensorflow/tensorflow.dll.if.lib and object bazel-out/x64_windows-opt/bin/tensorflow/tensorflow.dll.if.exp
	memory_optimizer.lib(memory_optimizer.obj) : warning LNK4049: locally defined symbol ?DEVICE_CPU@tensorflow@@3QEBDEB (char const * const tensorflow::DEVICE_CPU) imported
	pin_to_host_optimizer.lib(pin_to_host_optimizer.obj) : warning LNK4049: locally defined symbol ?DEVICE_CPU@tensorflow@@3QEBDEB (char const * const tensorflow::DEVICE_CPU) imported
	utils.lib(utils.obj) : warning LNK4049: locally defined symbol ?DEVICE_CPU@tensorflow@@3QEBDEB (char const * const tensorflow::DEVICE_CPU) imported
	collective_param_resolver_distributed.lib(collective_param_resolver_distributed.obj) : warning LNK4217: locally defined symbol ?DEVICE_CPU@tensorflow@@3QEBDEB (char const * const tensorflow::DEVICE_CPU) imported in function "public: __cdecl tensorflow::CollGroupParams::CollGroupParams(void)" (??0CollGroupParams@tensorflow@@QEAA@XZ)
	batch_kernels.lo.lib(batch_kernels.obj) : warning LNK4049: locally defined symbol ?DEVICE_CPU@tensorflow@@3QEBDEB (char const * const tensorflow::DEVICE_CPU) imported
	captured_function.lib(captured_function.obj) : warning LNK4049: locally defined symbol ?DEVICE_CPU@tensorflow@@3QEBDEB (char const * const tensorflow::DEVICE_CPU) imported
	arithmetic_optimizer.lib(arithmetic_optimizer.obj) : warning LNK4049: locally defined symbol ?DEVICE_CPU@tensorflow@@3QEBDEB (char const * const tensorflow::DEVICE_CPU) imported
	pin_to_host_optimizer.lib(pin_to_host_optimizer.obj) : warning LNK4049: locally defined symbol ?DEVICE_GPU@tensorflow@@3QEBDEB (char const * const tensorflow::DEVICE_GPU) imported
	utils.lib(utils.obj) : warning LNK4049: locally defined symbol ?DEVICE_GPU@tensorflow@@3QEBDEB (char const * const tensorflow::DEVICE_GPU) imported
	arithmetic_optimizer.lib(arithmetic_optimizer.obj) : warning LNK4217: locally defined symbol ?DEVICE_GPU@tensorflow@@3QEBDEB (char const * const tensorflow::DEVICE_GPU) imported in function "private: bool __cdecl tensorflow::grappler::`anonymous namespace'::ReorderCastLikeAndValuePreserving::NodeIsOnCpuOrGpu(class tensorflow::NodeDef const *)const " (?NodeIsOnCpuOrGpu@ReorderCastLikeAndValuePreserving@?A0xbdf9375e@grappler@tensorflow@@AEBA_NPEBVNodeDef@4@@Z)
	auto_mixed_precision.lib(auto_mixed_precision.obj) : warning LNK4049: locally defined symbol ?DEVICE_GPU@tensorflow@@3QEBDEB (char const * const tensorflow::DEVICE_GPU) imported
	layout_optimizer.lib(layout_optimizer.obj) : warning LNK4049: locally defined symbol ?DEVICE_GPU@tensorflow@@3QEBDEB (char const * const tensorflow::DEVICE_GPU) imported
	memory_optimizer.lib(memory_optimizer.obj) : warning LNK4049: locally defined symbol ?DEVICE_GPU@tensorflow@@3QEBDEB (char const * const tensorflow::DEVICE_GPU) imported

	tensorflow.dll.if.exp : error LNK2001: unresolved external symbol "?NewSession@tensorflow@@YAPEAVSession@1@AEBUSessionOptions@1@@z" (?NewSession@tensorflow@@YAPEAVSession@1@AEBUSessionOptions@1@@z)
	tensorflow.dll.if.exp : error LNK2001: unresolved external symbol "public: int __cdecl google::protobuf::RepeatedPtrField<class std::basic_string<char,struct std::char_traits<char>,std::allocator<char> > >::size(void)const " (?size@?$RepeatedPtrField@V?$basic_string@DU?$char_traits@D@std@@v?$allocator@D@2@@std@@@protobuf@google@@QEBAHXZ)

	bazel-out/x64_windows-opt/bin/tensorflow/tensorflow.dll : fatal error LNK1120: 2 unresolved externals
	Target //tensorflow:tensorflow_dll_import_lib failed to build

**Comment by acezzz** [comment]
Looks like you are build the C version. You should build the cpp version of tensorflow, which is tensorflow_cc.dll and tensorflow_cc.lib.
Please try to use to use following command
bazel build -c opt  //tensorflow:tensorflow_cc

**Comment by AndreyPlotkinOr** [comment]
Switching to the target you proposed didn't help as well:

	ERROR: D:/data/users/andrey/projects/tensorflow_1.14_cpu_cpp_v5/tensorflow/BUILD:566:1: Linking of rule '//tensorflow:tensorflow_cc.dll' failed (Exit 1120): link.exe failed: error executing command
	  cd D:/data/users/andrey/projects/tensorflow_1.14_cpu_cpp_v5/52qnlwry/execroot/org_tensorflow
	  SET LIB=C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\LIB\amd64;C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\LIB\amd64;C:\Program Files (x86)\Windows Kits\10\lib\10.0.17763.0\ucrt\x64;C:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\lib\um\x64;C:\Program Files (x86)\Windows Kits\10\lib\10.0.17763.0\um\x64;
		SET PATH=C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\amd64;C:\windows\Microsoft.NET\Framework64\v4.0.30319;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\Tools;C:\Program Files (x86)\Windows Kits\10\bin\x64;C:\Program Files (x86)\Windows Kits\10\bin\x86;C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.6.1 Tools\x64\;;C:\windows\system32
		SET PWD=/proc/self/cwd
		SET PYTHON_BIN_PATH=D:/Data/Users/andrey/AppData/Local/Programs/Python/Python36/python.exe
		SET PYTHON_LIB_PATH=D:/Data/Users/andrey/AppData/Local/Programs/Python/Python36/lib/site-packages
		SET RUNFILES_MANIFEST_ONLY=1
		SET TEMP=C:\Users\andrey\AppData\Local\Temp
		SET TF_CONFIGURE_IOS=0
		SET TF_DOWNLOAD_CLANG=0
		SET TF_NEED_CUDA=0
		SET TF_NEED_OPENCL_SYCL=0
		SET TF_NEED_ROCM=0
		SET TMP=C:\Users\andrey\AppData\Local\Temp
	  C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/amd64/link.exe /nologo /DLL /SUBSYSTEM:CONSOLE -defaultlib:advapi32.lib -DEFAULTLIB:advapi32.lib -ignore:4221 -ignore:4221 -ignore:4221 -ignore:4221 -ignore:4221 -ignore:4221 -ignore:4221 -ignore:4221 -ignore:4221 -ignore:4221 -ignore:4221 -ignore:4221 -ignore:4221 -ignore:4221 -ignore:4221 -ignore:4221 -ignore:4221 -ignore:4221 -ignore:4221 -ignore:4221 -ignore:4221 -ignore:4221 -ignore:4221 -ignore:4221 -ignore:4221 -ignore:4221 -ignore:4221 -ignore:4221 -ignore:4221 -ignore:4221 -ignore:4221 -ignore:4221 -ignore:4221 -ignore:4221 -ignore:4221 -ignore:4221 -ignore:4221 -ignore:4221 -ignore:4221 -ignore:4221 -ignore:4221 -ignore:4221 -ignore:4221 -ignore:4221 -ignore:4221 -ignore:4221 -ignore:4221 /MACHINE:X64 @bazel-out/x64_windows-opt/bin/tensorflow/tensorflow_cc.dll-2.params /OPT:ICF /OPT:REF /DEF:bazel-out/x64_windows-opt/bin/tensorflow/tensorflow_filtered_def_file.def /ignore:4070
	Execution platform: @bazel_tools//platforms:host_platform
	   Creating library bazel-out/x64_windows-opt/bin/tensorflow/tensorflow_cc.dll.if.lib and object bazel-out/x64_windows-opt/bin/tensorflow/tensorflow_cc.dll.if.exp
	memory_optimizer.lib(memory_optimizer.obj) : warning LNK4049: locally defined symbol ?DEVICE_CPU@tensorflow@@3QEBDEB (char const * const tensorflow::DEVICE_CPU) imported
	pin_to_host_optimizer.lib(pin_to_host_optimizer.obj) : warning LNK4049: locally defined symbol ?DEVICE_CPU@tensorflow@@3QEBDEB (char const * const tensorflow::DEVICE_CPU) imported
	utils.lib(utils.obj) : warning LNK4049: locally defined symbol ?DEVICE_CPU@tensorflow@@3QEBDEB (char const * const tensorflow::DEVICE_CPU) imported
	collective_param_resolver_distributed.lib(collective_param_resolver_distributed.obj) : warning LNK4217: locally defined symbol ?DEVICE_CPU@tensorflow@@3QEBDEB (char const * const tensorflow::DEVICE_CPU) imported in function "public: __cdecl tensorflow::CollGroupParams::CollGroupParams(void)" (??0CollGroupParams@tensorflow@@QEAA@XZ)
	batch_kernels.lo.lib(batch_kernels.obj) : warning LNK4049: locally defined symbol ?DEVICE_CPU@tensorflow@@3QEBDEB (char const * const tensorflow::DEVICE_CPU) imported
	captured_function.lib(captured_function.obj) : warning LNK4049: locally defined symbol ?DEVICE_CPU@tensorflow@@3QEBDEB (char const * const tensorflow::DEVICE_CPU) imported
	arithmetic_optimizer.lib(arithmetic_optimizer.obj) : warning LNK4049: locally defined symbol ?DEVICE_CPU@tensorflow@@3QEBDEB (char const * const tensorflow::DEVICE_CPU) imported
	tfprof_show.lib(tfprof_show.obj) : warning LNK4217: locally defined symbol TF_NewStatus imported in function "protected: bool __cdecl tensorflow::tfprof::TFShow::LookUpCheckPoint(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,class std::unique_ptr<class tensorflow::tfprof::TFProfTensor,struct std::default_delete<class tensorflow::tfprof::TFProfTensor> > *)" (?LookUpCheckPoint@TFShow@tfprof@tensorflow@@IEAA_NAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEAV?$unique_ptr@VTFProfTensor@tfprof@tensorflow@@U?$default_delete@VTFProfTensor@tfprof@tensorflow@@@std@@@5@@Z)
	tfprof_show.lib(tfprof_show.obj) : warning LNK4217: locally defined symbol TF_DeleteStatus imported in function "protected: bool __cdecl tensorflow::tfprof::TFShow::LookUpCheckPoint(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,class std::unique_ptr<class tensorflow::tfprof::TFProfTensor,struct std::default_delete<class tensorflow::tfprof::TFProfTensor> > *)" (?LookUpCheckPoint@TFShow@tfprof@tensorflow@@IEAA_NAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEAV?$unique_ptr@VTFProfTensor@tfprof@tensorflow@@U?$default_delete@VTFProfTensor@tfprof@tensorflow@@@std@@@5@@Z)
	tfprof_show.lib(tfprof_show.obj) : warning LNK4217: locally defined symbol TF_GetCode imported in function "protected: bool __cdecl tensorflow::tfprof::TFShow::LookUpCheckPoint(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,class std::unique_ptr<class tensorflow::tfprof::TFProfTensor,struct std::default_delete<class tensorflow::tfprof::TFProfTensor> > *)" (?LookUpCheckPoint@TFShow@tfprof@tensorflow@@IEAA_NAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEAV?$unique_ptr@VTFProfTensor@tfprof@tensorflow@@U?$default_delete@VTFProfTensor@tfprof@tensorflow@@@std@@@5@@Z)
	tfprof_show.lib(tfprof_show.obj) : warning LNK4217: locally defined symbol TF_Message imported in function "protected: bool __cdecl tensorflow::tfprof::TFShow::LookUpCheckPoint(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,class std::unique_ptr<class tensorflow::tfprof::TFProfTensor,struct std::default_delete<class tensorflow::tfprof::TFProfTensor> > *)" (?LookUpCheckPoint@TFShow@tfprof@tensorflow@@IEAA_NAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEAV?$unique_ptr@VTFProfTensor@tfprof@tensorflow@@U?$default_delete@VTFProfTensor@tfprof@tensorflow@@@std@@@5@@Z)
	pin_to_host_optimizer.lib(pin_to_host_optimizer.obj) : warning LNK4049: locally defined symbol ?DEVICE_GPU@tensorflow@@3QEBDEB (char const * const tensorflow::DEVICE_GPU) imported
	utils.lib(utils.obj) : warning LNK4049: locally defined symbol ?DEVICE_GPU@tensorflow@@3QEBDEB (char const * const tensorflow::DEVICE_GPU) imported
	arithmetic_optimizer.lib(arithmetic_optimizer.obj) : warning LNK4217: locally defined symbol ?DEVICE_GPU@tensorflow@@3QEBDEB (char const * const tensorflow::DEVICE_GPU) imported in function "private: bool __cdecl tensorflow::grappler::`anonymous namespace'::ReorderCastLikeAndValuePreserving::NodeIsOnCpuOrGpu(class tensorflow::NodeDef const *)const " (?NodeIsOnCpuOrGpu@ReorderCastLikeAndValuePreserving@?A0x145c2c42@grappler@tensorflow@@AEBA_NPEBVNodeDef@4@@Z)
	auto_mixed_precision.lib(auto_mixed_precision.obj) : warning LNK4049: locally defined symbol ?DEVICE_GPU@tensorflow@@3QEBDEB (char const * const tensorflow::DEVICE_GPU) imported
	layout_optimizer.lib(layout_optimizer.obj) : warning LNK4049: locally defined symbol ?DEVICE_GPU@tensorflow@@3QEBDEB (char const * const tensorflow::DEVICE_GPU) imported
	memory_optimizer.lib(memory_optimizer.obj) : warning LNK4049: locally defined symbol ?DEVICE_GPU@tensorflow@@3QEBDEB (char const * const tensorflow::DEVICE_GPU) imported
	tensorflow_cc.dll.if.exp : error LNK2001: unresolved external symbol "?NewSession@tensorflow@@YAPEAVSession@1@AEBUSessionOptions@1@@z" (?NewSession@tensorflow@@YAPEAVSession@1@AEBUSessionOptions@1@@z)
	tensorflow_cc.dll.if.exp : error LNK2001: unresolved external symbol "public: int __cdecl google::protobuf::RepeatedPtrField<class std::basic_string<char,struct std::char_traits<char>,std::allocator<char> > >::size(void)const " (?size@?$RepeatedPtrField@V?$basic_string@DU?$char_traits@D@std@@v?$allocator@D@2@@std@@@protobuf@google@@QEBAHXZ)
	bazel-out/x64_windows-opt/bin/tensorflow/tensorflow_cc.dll : fatal error LNK1120: 2 unresolved externals
	Target //tensorflow:tensorflow_cc failed to build

**Comment by AndreyPlotkinOr** [comment]
Switching to the target you proposed (the exact same command you wrote) didn't help as well.

Adding missing symbols in def_file_filter.py.tpl throws the exception above.
Without editing this file, dll/lib compiled ok, but linking with my code fails with same missing definitions.

**Comment by AndreyPlotkinOr** [comment]
I see missing symbols in these 2 files:
core_cpu_impl.lo.lib
protobuf_lite.lib
But they were not added to dll for some reason.

**Comment by AndreyPlotkinOr** [comment]
I added these libs manually, and got other error of double definition. Probably part of symbol definitions from libs were added into dll.
I temporary resolved it by adding /FORCE:MULTIPLE in my program linking stage.

Running the code gave me other error: 

> 2019-07-18 10:09:26.269905: E tensorflow/core/common_runtime/session.cc:60] Not found: No session factory registered for the given session options: {target: ""}
> Registered factories are {}.

**Comment by AndreyPlotkinOr** [comment]
Currently I have these 3 libs linked in my project:

> tensorflow_cc.dll.if.lib
> core_cpu_impl.lo.lib
> protobuf_lite.lib

and tensorflow_cc.dll near project exe.

Maybe I have to link more libs to overcome "Registered factories are {}." ?

**Comment by gunan** [comment]
This is similar to https://github.com/tensorflow/tensorflow/issues/30647
Let me try to see who I can escalate libtensorflow issues, as I am not very experienced with it.

**Comment by AndreyPlotkinOr** [comment]
May somebody share the place, where writes are to be added in tf_exported_symbols_msvc.lds?

**Comment by noar2** [comment]
You can reference this: https://github.com/sitting-duck/stuff/tree/master/ai/tensorflow/build_tensorflow_1.14_source_for_Windows

"
The reason this is happening is because you can only expose 60,000 symbols in a dll. This is just some limitation of the dll format. The tensorflow library code has more than 60000 symbols, so as the programmer building this dll (a dll is just a binary file for accessing a library at runtime) you will have to manually indicate which symbols you want exposed if they are not already. Google has chosen some default set, but it may not work for everyone.
"

**Comment by franckchateau** [comment]
> Currently I have these 3 libs linked in my project:
> 
> > tensorflow_cc.dll.if.lib
> > core_cpu_impl.lo.lib
> > protobuf_lite.lib
> 
> and tensorflow_cc.dll near project exe.
> 
> Maybe I have to link more libs to overcome "Registered factories are {}." ?

Hello,

Have you solved your problem ?
I have exactly the same issue

thank you very much

**Comment by AndreyPlotkinOr** [comment]
No =(

> > Currently I have these 3 libs linked in my project:
> > > tensorflow_cc.dll.if.lib
> > > core_cpu_impl.lo.lib
> > > protobuf_lite.lib
> > 
> > 
> > and tensorflow_cc.dll near project exe.
> > Maybe I have to link more libs to overcome "Registered factories are {}." ?
> 
> Hello,
> 
> Have you solved your problem ?
> I have exactly the same issue
> 
> thank you very much

**Comment by mohantym** [comment]
Hi @AndreyPlotkinOr ! 
We are checking to see whether you still need help in this issue . Have your tried instructions in this [thread](https://www.tensorflow.org/install/source_windows) yet?
