### ISSUE TITLE
Which Bazel versions are okay for Tensorflow source install?

### ISSUE THREAD

**Issue by karkirowle** [tensorflow/tensorflow#30556]
## URL(s) with the issue:

https://www.tensorflow.org/install/source_windows

## Description of issue (what needs changing):

It is purely a logical issue:
Install Bazel 0.24.1, the build tool used to compile TensorFlow. Set up Bazel to build C++.
[...] Ensure you install Bazel 0.23.0 or lower.

0.24.1 > 0.23.0

**Comment by pandrey-fr** [comment]
Hi, I completely agree with the documentation issue here. The thing is, it really depends on the version of TensorFlow you are trying to compile. You can find this information in the `configure.py` script once you have cloned the Git repo and checked out to the release branch you want to compile.

Not knowing that, I personally had to download three distinct versions of Bazel while running through a compilation yesterday (first one was too recent, second one was okay for master but not for r2.0 which I eventually elected, third one did the trick), which, while not a major issue, was annoying.

**Comment by karkirowle** [comment]
That's good to know, I think this should be stated in the documentation then or an appropriate intersection of the versions should be recommended.

**Comment by mihaimaruseac** [comment]
due to the cadence of Bazel updates, currently there is no Bazel version in the intersection of all supported versions of TF:

TF 1.13 wants bazel 0.19.0 to 0.21.0
TF 1.14 wants bazel 0.24.1 to 0.25.2
TF 2.0 wants bazel 0.24.1 to 0.26.0
TF master wants bazel 0.24.1 to 0.26.1

TF 1.12 just passed it's end of support term. TF 1.13 will reach end of support at end of August at which point bazel 0.24.1 to 0.25.2 can be used for all of the other branches.

**Comment by gadagashwini** [comment]
@karkirowle Did you get a chance to look at the @mihaimaruseac's comment. Thanks!

**Comment by byronyi** [comment]
> Due to the cadence of Bazel updates, currently there is no Bazel version in the intersection of all supported versions of TF:
> 
> TF 1.13 wants bazel 0.19.0 to 0.21.0
> TF 1.14 wants bazel 0.24.1 to 0.25.2
> TF 2.0 wants bazel 0.24.1 to 0.26.0
> TF master wants bazel 0.24.1 to 0.26.1
> 
> TF 1.12 just passed its end of support term. TF 1.13 will reach end of support at end of August at which point bazel 0.24.1 to 0.25.2 can be used for all of the other branches.

Hi Mihai, the note about support term is fairly interesting. Where can I find more information on the lifetime/support for different TF release versions? I suppose it's roughly half a year?

**Comment by mihaimaruseac** [comment]
I think we haven't added it on a public facing documentation, as it has something we talked about only recently. It's supposed to be 6 months.

**Comment by gadagashwini** [comment]
Closing this issue since its addressed. Feel free to reopen if the solution provided doesn't work for you. Thanks!
