### ISSUE TITLE
LogMatrix Gradients

### ISSUE THREAD

**Issue by paul-bd** [tensorflow/tensorflow#30565]
Hi, 
I am trying to optimize a function that requires to compute tf.linalg.logmatrix but this operation doesn't seem to have a gradient as this error came up : LookupError: gradient registry has no entry for: MatrixLogarithm

Best regards,

**Comment by gadagashwini** [comment]
@paul-bd Please provide us the Tenosrflow version and also code snippet to reproduce the reported issue. Thanks!

**Comment by gadagashwini** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
