### ISSUE TITLE
Missing Graph Editor Documentation

### ISSUE THREAD

**Issue by haximilian** [tensorflow/tensorflow#30566]
## URL(s) with the issue:
https://www.tensorflow.org/api_docs/python/tf/contrib/graph_editor
https://www.tensorflow.org/api_guides/python/contrib.graph_editor

## Description of issue (what needs changing):
The Graph Editor API Doc (first link above) links to the Graph Editor Guide (second link above) which is a 404 error.

### Clear description
The broken link to the Graph Editor Guide needs to either be fixed or removed and replaced with some actual, comprehensive documentation on using the Graph Editor. At the moment, there is no documentation on Graph Editor usage available anywhere.

**Comment by leeyspaul** [comment]
hi, happy to take this up by replacing the URL.

**Comment by lamberta** [comment]
Thanks. That guide is gone so removed link in https://github.com/tensorflow/tensorflow/pull/30824

**Comment by haximilian** [comment]
@lamberta Out of curiosity, do you have any idea what happened to the original guide or where I could find it?

**Comment by lamberta** [comment]
@haximilian Yep, some of the older /api_guides are archived here in tensorflow/docs (r1.11 branch): https://github.com/tensorflow/docs/tree/r1.11/site/en/api_guides/python
Though, as you've found, there are still some links that need to be removed.
These guides mostly existed pre-module—and now modules have their own overview pages in the API docs.
