### ISSUE TITLE
Trace/Wallclock Performance Discrepancy 

### ISSUE THREAD

**Issue by iiSeymour** [tensorflow/tensorflow#30571]
**Describe the bug**

Running a converted PyTorch model has some curious performance characteristics were running the `.pb` model directly in TensorFlow is ~2.5 times slower than the onnx runtime.

```bash
$ ./benchmark model
> onnx runtime took 4.83842
> tensorflow took 12.63854
```

Looking at the trace information shows that work is only being done for about 3.5 seconds so the question is what is `session.run` doing for the other ~9 seconds?  

![onnx-tf-rnn-perf](https://user-images.githubusercontent.com/4310904/60820118-b547e700-a198-11e9-8c3f-f48c54e3952e.png)

**To Reproduce**

```python
#!/usr/bin/env python

"""
Benchmark ONNX model
"""

import time
from argparse import ArgumentParser

import numpy as np
import numpy.testing

import onnxruntime as runtime

import tensorflow as tf
from tensorflow.python.client import timeline

def main(args):

    x = np.random.randn(args.chunksize, args.batchsize, 1).astype(np.float32)

    # == ONNX Runtime ==

    options = runtime.SessionOptions()
    session = runtime.InferenceSession(args.model + ".onnx", options)

    input_name = session.get_inputs()[0].name
    output_name = session.get_outputs()[0].name

    t0 = time.time()
    onnxrt_out = session.run([output_name], {input_name: x})
    onnxrt_out = np.array(onnxrt_out[0])
    t1 = time.time()
    print("> onnx runtime took %.5f" % (t1 - t0))
 
    # == TensorFlow ==

    with tf.compat.v1.Session() as session:
        with tf.io.gfile.GFile(args.model + ".pb", "rb") as graph:
            g = tf.compat.v1.GraphDef()
            g.ParseFromString(graph.read())
            tf.import_graph_def(g)

        graph = tf.get_default_graph()
        first = graph.get_tensor_by_name("import/input:0")
        last = graph.get_operations()[-1].outputs[0]

        run_options = tf.RunOptions(trace_level=tf.RunOptions.FULL_TRACE)
        run_metadata = tf.RunMetadata()

        t0 = time.time()
        tensorflow_out = session.run(
            last,
            feed_dict={first: x},
            options=run_options,
            run_metadata=run_metadata
        )
        t1 = time.time()

        tl = timeline.Timeline(run_metadata.step_stats)
        ctf = tl.generate_chrome_trace_format()
        with open('trace_file.json', 'w') as f:
            f.write(ctf)

    print("> tensorflow took %.5f" % (t1 - t0))

    numpy.testing.assert_allclose(
        onnxrt_out,
        tensorflow_out,
        atol=1e-4
    )


if __name__ == "__main__":
    parser = ArgumentParser()
    parser.add_argument("model")
    parser.add_argument('--batchsize', type=int, default=1000)
    parser.add_argument('--chunksize', type=int, default=1000)
    main(parser.parse_args())
```

**Model files**

 - ONNX https://www.dropbox.com/s/jv0hk9h62eymax2/model.onnx
 - TensorFlow https://www.dropbox.com/s/t2n4ut7kwfjq8j2/model.pb

**Python, ONNX, Tensorflow version**

 - Python version: 3.5.3
 - ONNX version: 1.5.0
 - Tensorflow version: 1.14.0

**Additional context**

 - Trace file https://www.dropbox.com/s/vhaq5ykt6vlu5ij/trace_file.json

**Comment by Saduf2019** [comment]
@iiSeymour  
Is this still an issue.

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.
