### ISSUE TITLE
Add should_finialize(state) to tf.data.experimental.Reducer

### ISSUE THREAD

**Issue by fengyang0317** [tensorflow/tensorflow#30585]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using): 1.14.0
- Are you willing to contribute it (Yes/No): No

**Describe the feature and the current behavior/state.**
Current behavior: tf.data.experimental.Reducer will not finalize until the end of a dataset.
Wanted feature: I don't want to reduce the whole dataset. I hope that the Reducer could decide when to finalize based on its state. For example, add the following function inside Reducer and call the function after reduce_func().
def should_finialize(state):
  return True   --> stop reducing anymore, call finalize_func, and return results.
  return False  --> continue reduce.

**Will this change the current api? How?**
No. The default should_finialize always returns False. If anyone wants to change this behavior, he needs to override this function.

**Who will benefit with this feature?**
The tf.data input pipeline will be more versatile with this new feature. It is possible to do more operations without calling a python generator or py_func. For example, we need several different samples from the same class to be in one batch for tf.contrib.losses.metric_learning.triplet_semihard_loss. The labels of a batch may look like the following:
0, 0, 0, 0,
1, 1, 1, 1,
...
15, 15, 15, 15
There are 64 (=16*4) samples in this batch. I cannot find a pure tf.data way to form batches in this way. But with the new feature, we are able to do so.

**Any Other info.**
It seems that Jiri Simsa @jsimsa is very familiar with tf.data.experimental.Reducer.

**Comment by jsimsa** [comment]
I believe that you should be able to achieve this with existing transformations. In particular, I would direct your attention to [group_by_reducer](https://www.tensorflow.org/api_docs/python/tf/data/experimental/group_by_reducer), [group_by_window](https://www.tensorflow.org/api_docs/python/tf/data/experimental/group_by_window), [scan](https://www.tensorflow.org/api_docs/python/tf/data/experimental/scan) and [take_while](https://www.tensorflow.org/api_docs/python/tf/data/experimental/take_while).

If you provide me with a concrete example of input / output behavior, I can provide you a solution based on existing transformations.

**Comment by fengyang0317** [comment]
Thanks for your help.
Let's suppose I have a dataset composed of (image, label).
image, label
im0, 0
im1, 0
im2, 1
im3, 1
im4, 1
im5, 2

I want to generate a batch containing 4 samples. The first two are sharing the same label, and the last two are sharing the same label. This can be down by the following code, which is what I am using now.
```
ds = ds.shuffle(6).repeat()
ds = ds.apply(tf.data.experimental.group_by_window(
  lambda im, label: label,
  lambda key, data: data.batch(2), 
  2))
ds = ds.apply(tf.data.experimental.unbatch())
ds = ds.batch(4)
```

But there is a problem with this code. The first and second samples may be exactly the same one, which is what I want to **avoid** now. I don't want the same example appearing more than once in each window.

Lets' suppose the shuffled stream are
epoch 0: im0, im1, im2, im3, im4, im5
epoch 1: im0, im1, im4, im2, im3, im5
epoch 2: im0, im1, im2, im3, im4, im5
The generated batch should be
batch 0: im0, im1, im2, im3
batch 1: im0, im1, im4, im4
batch 2: im2, im3, im5, im5
...

The third and fourth samples are exactly the same in batch 1 and batch 2. They will not generate any loss for margin-based losses.

What I am expecting is
batch 0: im0, im1, im2, im3
batch 1: im0, im1, im4, ~~im4~~ im2  (when the second im4 is adding to a window, do not add it)
batch 2: im0, im1, im3, im2
batch 3: im3, im4, ...

The window for im5 will not be filled forever.

**Comment by jsimsa** [comment]
You can achieve the desired effect as follows:

```
import numpy as np
import tensorflow as tf

tf.enable_v2_behavior()

data = (['a', 'b', 'c', 'd', 'e', 'f'], 
        np.array([0, 0, 1, 1, 1, 2], dtype=np.int64))

dataset = tf.data.Dataset.from_tensor_slices(data).shuffle(6)

dataset = dataset.apply(tf.data.experimental.group_by_window(
    lambda x, y: y,
    lambda key, x: x.batch(2),
    window_size=2,
))
dataset = dataset.unbatch().batch(4, drop_remainder=True)
dataset = dataset.repeat()

for elem in dataset.take(3):
  x, y = elem
  print(x.numpy(), y.numpy())
```

**Comment by fengyang0317** [comment]
Great! Thank you very much.
