### ISSUE TITLE
Restoring only a PART of the graph from warm_start_from in Estimator

### ISSUE THREAD

**Issue by cocosci** [tensorflow/tensorflow#30581]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using): 1.14
- Are you willing to contribute it (Yes/No):

**Describe the feature and the current behavior/state.**
When restoring a TF estimator, we can use warm_start_from. However, that means all variables will be restored from the checkpoint. (see https://www.tensorflow.org/api_docs/python/tf/estimator/Estimator)
However, what if my model_fn is changed with some more variables being added? In that case, we can't use warm_start_from.
We hope those newly added variables can be initialized by some default initializer while others are loaded from the checkpoint. That way, the estimator can be incrementally defined. Much more flexible!

**Will this change the current api? How?**
No

**Who will benefit with this feature?**
BERT users and Wide-n-deep estimator users.
**Any Other info.**

**Comment by ppham27** [comment]
Restoring from all variables is the default behavior. But it's possible to only restore select variables with WarmStartSettings (https://www.tensorflow.org/api_docs/python/tf/estimator/WarmStartSettings).

**Comment by cocosci** [comment]
> Restoring from all variables is the default behavior. But it's possible to only restore select variables with WarmStartSettings (https://www.tensorflow.org/api_docs/python/tf/estimator/WarmStartSettings).

That method assumes the graph of the estimator is not being modified, right?
Let's say, I firstly train one estimator with all parameters being in the scope of "Round1/"; then I modify the graph of the estimator by adding some more trainable variables in the scope of "Round2/".
In that case, the second graph contains, but bigger than the first graph. Can I use WarmStartSettings to load variables in "Round1/" from the 1st estimator, and then randomly initialize newly added variables in "Round2/"?

Maybe I should use a different model_dir when instantiating the new estimator? Otherwise, the WarmStartSettings will be blocked and the new estimator will simply compare and load all variables from the model specified in model_dir.

Thanks.

**Comment by ppham27** [comment]
No it doesn't assume that at all. You can use `var_name_to_prev_var_name` and pass a dictionary like {'Round2/my_var': 'Round1/my_var'} as long as they are the shape. You can also filter which variables to restore with the `vars_to_warm_start` argument. This question probably belongs on StackOverflow, also.

**Comment by ChandlerGuan** [comment]
> No it doesn't assume that at all. You can use `var_name_to_prev_var_name` and pass a dictionary like {'Round2/my_var': 'Round1/my_var'} as long as they are the shape. You can also filter which variables to restore with the `vars_to_warm_start` argument. This question probably belongs on StackOverflow, also.
> 
> And yes, if you're doing a partial restore, you should be using new model directory.

I think cocosci means some variables in Round2 do not exist in the checkpoint of Round1 and should be initialized by some default initializer.

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.
