### ISSUE TITLE
keras define a trainable weights as layer

### ISSUE THREAD

**Issue by searchlink** [tensorflow/tensorflow#30587]
Hi~I have some problems in use tf.keras to build model. Now I want to define a trainbale weight B with shape(64, 128), then do tensor matrix, how to define a trainable weight B in keras similar to `tf.get_variable`
```
A = Input(shape=(128,))
out = tf.keras.layers.Lambda(lambda x: tf.matmul(x[0], x[1], transpose_b=True))([A, B])
model = Model(inputs=A, outputs=out)
```
I hope someone can help me.It's very grateful!

**Comment by pandrey-fr** [comment]
Hi,

You could simply create a random Tensor, then make it trainable using `tf.Variable`:
```
inputs = tf.keras.Input((128,))
weights = tf.Variable(tf.random.normal((64, 128)))
output = tf.matmul(inputs, tf.transpose(outputs))
model = tf.keras.Model(inputs, output)
```

That being said, you probably have better do something like:
```
inputs = tf.keras.Input((128,))
output = tf.keras.layers.Dense(64, use_bias=False)(inputs)
model = tf.keras.Model(inputs, output)
# And if you want to access the weights:
weights = model.layers[-1].weights[0]
```
Note that you can `tf.transpose` the `weights` tensor if you really want it in `(64, 128)` shape. In this version, you can also pass additional arguments to `tf.keras.layers.Dense` to use a specific initialization scheme.

I hope this helps. By the way, no offence, but this question would be better asked on a questions answering website (e.g. StackOverflow) than on a GitHub Issues tracker.

**Comment by searchlink** [comment]
@pandrey-fr  Sorry to trouble you! Thanks for you answer. I still have some question.Can you help me? In your code, I change something.
```
inputs = tf.keras.Input((128,))
weights = tf.Variable(tf.random.normal((64, 128)))
output = tf.keras.layers.Lambda(lambda x: tf.matmul(x, tf.transpose(weights)))(inputs)
model = tf.keras.Model(inputs, output)
```
the  outputs:
```
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
=================================================================
input_10 (InputLayer)        (None, 128)               0         
_________________________________________________________________
lambda_2 (Lambda)            (None, 64)                0         
=================================================================
Total params: 0
Trainable params: 0
Non-trainable params: 0
```
the defined weights is not trainable. 
In addition, I know Dense can get trained matrix weights and bias. But if  I want add a bias, I can't use Dense.
However, I have to use add_weights in custome layer, for example:
```
class Bias(keras.layers.Layer):
    def build(self, input_shape):
        self.bias = self.add_weight(shape=(64, 128), initializer='zeros', dtype=tf.float32, name='x')
        self.built = True

    def call(self, inputs):
        return inputs + self.bias

inputs = Input(shape=(64, 128))
outputs = Bias()(inputs)
model = Model(inputs=inputs, outputs=outputs)
model.summary()
Layer (type)                 Output Shape              Param #   
=================================================================
input_11 (InputLayer)        (None, 64, 128)           0         
_________________________________________________________________
bias_5 (Bias)                (None, 64, 128)           8192      
=================================================================
Total params: 8,192
Trainable params: 8,192
Non-trainable params: 0
```
Is there any method to define a trainable variable ？

**Comment by pandrey-fr** [comment]
> @pandrey-fr Sorry to trouble you

No worries, I am happy to try to help you - but I think this discussion would be more suited on Stack than here, where it might take some visibility from actual issues which TF developers (of which I am not part - I am just a random TF user) have to deal with.

> the defined weights is not trainable

The variable is defined as trainable, but keras won't make it so in the model, for some reason... The same happens with `tf.keras.backend.variable`, which does not make much sense to me but must be related to how keras builds the model's graph.

Indeed, you would need to write it as a custom layer - or, in this case, use `tf.keras.layers.Dense` (with `use_bias=False` is you do not want to use a bias). Same goes for adding a bias - however unpractical it may seem for something as simple as that, I think your code is the proper workaround.

There may be a better way, but at the moment I do not see it. I would encourage you to copy/paste your question on a more suited website where there is a higher probability that someone with a better idea would read and answer it :)

**Comment by searchlink** [comment]
@pandrey-fr  It's very grateful! I will question on stackoverflow to look for other answers. Thank you~

**Comment by pandrey-fr** [comment]
You are very welcome! (and if I may, you probably should close this issue, and optionally post the answer here afterwards if you manage to get a good one)
