### ISSUE TITLE
TFTRT calib_graph/infer_graph has different output

### ISSUE THREAD

**Issue by CLIsVeryOK** [tensorflow/tensorflow#30595]
I am doing tftrt convert to accelerate tf model.
first, get calib_graph
calibration_graph = trt.create_inference_graph()

second run calib_graph
the output is a tensor with batch_size = 16, output like this

third, I get the int8 graph
int8Graph = trt.calib_graph_to_infer_graph(calibration_graph)
('length and output: ', [array([-0.999994  ,  0.99682164,  0.9992819 ,  0.95060456, -0.8617101 ,
        0.9993279 , -0.994945  ,  0.99960554, -0.99968964,  0.99943244,
        0.9990337 ,  0.9889959 ,  0.91563284,  0.99274397,  0.99358046,
        0.9925939 ], dtype=float32)])

But when I run the int8Graph using the same input data as step2, I get output like this, 
('length and output: ', array([0.952391  , 0.94719326, 0.9581959 , 0.86539173, 0.92513335,
       0.97020185, 0.88829505, 0.97703993, 0.87482417, 0.9612503 ,
       0.95443654, 0.8331325 , 0.9141325 , 0.92734456, 0.94608974,
       0.9845928 ], dtype=float32))

It's really confused, any one met this problem?

by the way, I run origin pb with the same data, I get 
('length and output: ', array([-0.999994  ,  0.99682164,  0.9992819 ,  0.9506048 , -0.8617081 ,
        0.9993279 , -0.9949451 ,  0.99960554, -0.99968964,  0.99943244,
        0.9990337 ,  0.9889959 ,  0.9156331 ,  0.99274397,  0.99358046,
        0.9925939 ], dtype=float32)),
same as my calib_graph result.

So, what's wrong with the int8_graph???

**Comment by gadagashwini** [comment]
@CLIsVeryOK Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version. Also, did you compile from source or install a binary? Thanks!

**Comment by CLIsVeryOK** [comment]
@gadagashwini  I use ubuntu 16.04/1080Ti GPU, tf1.13, installed a binary

**Comment by gadagashwini** [comment]
@CLIsVeryOK Will it be possible to provide us the complete code to reproduce the issue. Thanks!

**Comment by CLIsVeryOK** [comment]
@gadagashwini  please give me your email, I send you the data and code in zip

**Comment by aaroey** [comment]
Hi @CLIsVeryOK, would you please provide the code and data via github? Thanks.

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.
