### ISSUE TITLE
Error(i.e. fatal error C1189: #error:  STL1001: Unexpected compiler version, expected MSVC 19.20 or newer) while building Tensorflow with MSVC 2019 on windows 

### ISSUE THREAD

**Issue by mayadav1** [tensorflow/tensorflow#30599]
System information
OS Platform : Windows 10 Pro
TensorFlow version: r1.3
Python version: Python 3.6.8 :: Anaconda, Inc.
Installed using virtualenv: conda
Bazel version : 0.26.1
MSVC 19

configuration :
Please specify the location of python. [Default is C:\Users\zen2_microsoft\Anaconda3\envs\tensorflow-1.13.1-without-mkl\python.exe]:
Found possible Python library paths:
C:\Users\zen2_microsoft\Anaconda3\envs\tensorflow-1.13.1-without-mkl\lib\site-packages
Please input the desired Python library path to use. Default is [C:\Users\zen2_microsoft\Anaconda3\envs\tensorflow-1.13.1-without-mkl\lib\site-packages]
Do you wish to build TensorFlow with XLA JIT support? [y/N]: N
No XLA JIT support will be enabled for TensorFlow.
Do you wish to build TensorFlow with ROCm support? [y/N]: N
No ROCm support will be enabled for TensorFlow.
Do you wish to build TensorFlow with CUDA support? [y/N]: N
No CUDA support will be enabled for TensorFlow.
Please specify optimization flags to use during compilation when bazel option "--config=opt" is specified [Default is /arch:AVX]:
Would you like to override eigen strong inline for some C++ compilation to reduce the compilation time? [Y/n]: N

Error Description :

 C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.16.27023/bin/HostX64/x64/cl.exe /nologo /DCOMPILER_MSVC /DNOMINMAX /D_WIN32_WINNT=0x0601 /D_CRT_SECURE_NO_DEPRECATE /D_CRT_SECURE_NO_WARNINGS /bigobj /Zm500 /EHsc /wd4351 /wd4291 /wd4250 /wd4996 /I. /Ibazel-out/x64_windows-opt/bin /Iexternal/fft2d /Ibazel-out/x64_windows-opt/bin/external/fft2d /showIncludes /MD /O2 /Oy- /DNDEBUG /wd4117 -D__DATE__="redacted" -D__TIMESTAMP__="redacted" -D__TIME__="redacted" /Gy /Gw -w -DWIN32_LEAN_AND_MEAN -DNOGDI /arch:AVX /Fobazel-out/x64_windows-opt/bin/tensorflow/lite/kernels/internal/_objs/audio_utils/spectrogram.obj /c tensorflow/lite/kernels/internal/spectrogram.cc
Execution platform: @bazel_tools//platforms:host_platform
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.21.27702\include\yvals_core.h(352): fatal error C1189: #error:  STL1001: Unexpected compiler version, expected MSVC 19.20 or newer.
Target //tensorflow/tools/pip_package:build_pip_package failed to build
INFO: Elapsed time: 1719.835s, Critical Path: 17.80s
INFO: 18 processes: 18 local.
FAILED: Build did NOT complete successfully

**Comment by ChaoyiXie** [comment]
I meet the problem too,do you have sloved this problem??

**Comment by mayadav1** [comment]
@ChaoyiXie 
I didn't find solution . facing different issue after VS update 16.2 #31608 . Let me know in case you find something .

**Comment by gunan** [comment]
I ran into this problem when there were multiple versions of visual studio installed. When I  removed the extra visual studio installations (or the command line tools for 2017 or 2015 that you can install with vs 2019) it worked OK for me.

@laszlocsomor @meteorcloudy this looks like a bug in bazel VS detection, maybe?

**Comment by meteorcloudy** [comment]
@gunan , yes, this is a bug in Bazel, which is already fixed from Bazel 0.27.0
See https://github.com/bazelbuild/bazel/pull/7686#issuecomment-492796469

**Comment by laszlocsomor** [comment]
@gunan , the command looks legit. 

I have VC 2019 Community (14.20.27508) installed, and my `yvals_core.h` looks like:
```
   337  #if _MSC_VER < 1920 // Coarse-grained, not inspecting _MSC_FULL_VER
   338  #error STL1001: Unexpected compiler version, expected MSVC 19.20 or newer.
   339  #endif // ^^^ old MSVC ^^^
```

For that particular installation, `_MSC_VER` is `1921`.

It looks like @mayadav1 is getting a bad `_MSC_VER`.

@mayadav1 : Could you please run Bazel with `--verbose_failures` and paste the envvars here too? It will print the failing command, but also all the envvars Bazel set for it.

**Comment by laszlocsomor** [comment]
@mayadav1 : Could you please try something else as well?

1. Create a new directory, for example `c:\foo`
2. Create an empty `WORKSPACE` file there (if you create it with Notepad then make sure to remove the `.txt` extension)
3. Create a `BUILD` file (again, watch that there's no `.txt` extension) with this content:
    ```
    cc_binary(
        name = "msvc_ver",
        srcs = ["msvc_ver.cc"],
    )
    ```
4. Create a `msvc_ver.cc` file with this content:
    ```
    #include <stdio.h>
    #define _T(x) #x
    #define T(x) _T(x)
    int main() {
      printf("_MSC_VER = (%s)\n", T(_MSC_VER));
      return 0;
    }
    ```
5. Open `cmd.exe`, then:
    ```
    cd c:\foo

    bazel run //:msvc_ver
    ```

What's the output?

**Comment by gunan** [comment]
You can now use more recent bazel versions with TF, therefore, this issue is resolved.

**Comment by barisdemiray** [comment]
> You can now use more recent bazel versions with TF, therefore, this issue is resolved.

As if we didn't have strict version limitations of Bazel to use for every single TensorFlow version. Upgrade to Bazel 0.27.0 rules out TensorFlow 1.15 (which needs <= 0.26.1) and older.
