### ISSUE TITLE
Consistent use of else after return (pylint no-else-return)

### ISSUE THREAD

**Issue by lufol** [tensorflow/tensorflow#30591]
While working on some pylint warnings in `tensorflow/python/keras/backend.py` I noticed that two different ways of "if else return" styles are used.

1. `if condition: return 0`
    `return 1`
2. `if condition: return 0`
    `else: return 1`

Is changing the behaiviour to one of the variants considered good practice?
I would like to clear things up (and improve the pylint score :D ).

**Comment by pandrey-fr** [comment]
Both behaviours appear in the PEP 8 style guide (look up "be consistent in return statements." on [this page](https://www.python.org/dev/peps/pep-0008/#programming-recommendations)), so I do not believe there is a preferred one _per se_, at least not in this guide.

That being said, in my humble not-a-tensorflow-developer opinion, you should (in accordance with PEP-8 principles) use the alternative that feels best as to readability and comprehensibility based on context. Parsimony would ask to do as pylint suggests, getting rid of useless `else` statements, but there might be cases in which this statement actually improves the reader's comprehension of what is happening, in which case you should probably keep it. If you worry about pylint scores, you can always add a pylint command in comment on those specific cases.

**Comment by lufol** [comment]
Alright, thanks for clarifying!
