### ISSUE TITLE
(Aborted (core dumped)) - Check failed: GetOpGradFactory()->insert({op, func}).second Duplicated gradient for MapAccumulate

### ISSUE THREAD

**Issue by milinddeore** [tensorflow/tensorflow#30593]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):  Stock example script. 
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): CentOS Linux release 7.6.1810 (Core)
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: On my laptop,
- TensorFlow installed from (source or binary): From source for c++ application. 
- TensorFlow version (use command below): v1.8.0
- Python version: 2.7
- Bazel version (if compiling from source): 0.15.1
- GCC/Compiler version (if compiling from source): g++ (GCC) 4.8.5 20150623 (Red Hat 4.8.5-36)
- CUDA/cuDNN version: CPU only
- GPU model and memory: None.

**Describe the current behavior**
I have a [Standalone c++ build](https://medium.com/@tomdeore/standalone-c-build-tensorflow-opencv-6dc9d8a1412d) process for ubuntu and it works fine with my own code as well as with the c++ [example code](https://www.tensorflow.org/guide/extend/cc) on tensorflow. 

But when i run the same code on CentOS platform. I get following runtime error message and the executable core dumps:

```
2019-07-11 10:20:42.027023: F tensorflow/core/framework/function.cc:1329] Check failed: GetOpGradFactory()->insert({op, func}).second Duplicated gradient for MapAccumulate
Aborted (core dumped)
```
My compilation command is as: 

```
g++ -std=gnu++11 -Wl,-rpath='$ORIGIN/lib' -fPIC -Iinclude -Llib  example.cc -ltensorflow_cc -ltensorflow_framework   -o example
```

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.
Please follow the steps provided on [blog](https://medium.com/@tomdeore/standalone-c-build-tensorflow-opencv-6dc9d8a1412d).

**Comment by ravikyram** [comment]
@milinddeore Can you please confirm whether you are getting runtime error with your code or c++ code on tensorflow ,with CentOS platform.Thanks!

**Comment by milinddeore** [comment]
@ravikyram I got this issues using both my code as well as with c++ code on Tensorflow.

**Comment by jvishnuvardhan** [comment]
@milinddeore Sorry for missing this issue. Can you please check with most recent version of TF like `TF1.15.2` or `TF2.2` (preferred). Thanks!

**Comment by icoffeebeans** [comment]
@jvishnuvardhan Thanks for your reply. I'm also facing this issue on TF1.12.0, when I'm trying to include a deps of `//tensorflow/core/kernels:lookup`. Do you have any idea how to avoid this core issue?

**Comment by jvishnuvardhan** [comment]
@icoffeebeans can you please check with latest version and let us know? Thanks!

**Comment by mihaimaruseac** [comment]
1.12 is not supported.

**Comment by jvishnuvardhan** [comment]
I am closing this issue as `TF1.12` is not supported. Please use recent stable versions. Thanks!

**Comment by qiandu2006** [comment]
the same coredump as @milinddeore
