### ISSUE TITLE
Macros definition for using MKL from Eigen

### ISSUE THREAD

**Issue by UILXELA** [tensorflow/tensorflow#30592]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution Centos 7.2 (e.g., Linux Ubuntu 16.04):
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): source
- TensorFlow version: 1.13.1 Release
- Python version: 3.6.8
- Installed using virtualenv? pip? conda?: Build from source, no conda
- Bazel version (if compiling from source): 0.20.0
- GCC/Compiler version (if compiling from source): 8.2.0
- CUDA/cuDNN version:
- GPU model and memory:

**Describe the problem**
In tensorflow/tensorflow/tensorflow.bzl, it defines the macros used for using MKL from Eigen as below:
`if_mkl(["-DINTEL_MKL=1", "-DEIGEN_USE_VML"])`

However, in Eigen's documentation, the macro is:
`-DEIGEN_USE_MKL_VML`
 
Is this intentional? I tried to read both tensorflow's and Eigen's source code but did not find a reason of that. 
Thanks.
**Provide the exact sequence of commands / steps that you executed before running into the problem**

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by preethivenkatesh** [comment]
-DEIGEN_USE_VML is to use pure Eigen (w/o mkl) while -DEIGEN_USE_MKL_VML is enabling the use of inbuilt Intel MKL through Eigen
