### ISSUE TITLE
gfile for S3 uploads corrupt data when called concurrently

### ISSUE THREAD

**Issue by yasushi-saito** [tensorflow/tensorflow#30598]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):

Ubuntu 16.04

- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):

Amazon DLAMI
- TensorFlow version (use command below):
1.13.1
- Python version:
3.6
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**

I have code that writes .npz files from multiple python processes. python code is single-threaded, and each process writes a separate .npz file. The files are sometimes corrupted on S3. I checked a sha256 checksum of the data in memory, and they differ from the checksum of the written data on S3.

**Describe the expected behavior**

the contents should be identical.

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

I can create a repro if needed.

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

The reason seems to be that the gfile writer doesn't create a unique tempfile when it is invoked within a millisecond.

https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/platform/s3/s3_file_system.cc#L213

Here, the writer creates a tempfile. and the corresponding aws-sdk-cpp code is:

https://github.com/aws/aws-sdk-cpp/blob/master/aws-cpp-sdk-core/source/platform/linux-shared/FileSystem.cpp#L262

The latter code only has a millisecond granularity, so if gfile is called within the same millisecond, it creates the same tempfile and they overwrite each other.

Also, the "XXXXXX" part in s3_file_system.c doesn't do anything, although it's not the cause of this problem.

I created a separate issue in

https://github.com/aws/aws-sdk-cpp/issues/1192

**Comment by gadagashwini** [comment]
@yasushi-saito Provide us the full minimal code snippet which replicates mentioned issue. It will indeed help us to move faster.Thanks!

**Comment by yasushi-saito** [comment]
Try below. You need to change the "test_path" function. With CONCURRENCY = 128, I consistency get "file X is corrupt". With CONCURRENCY = 1, I don't get the error.


`
from tensorflow import gfile
from concurrent import futures
import logging
import random
import string
from typing import List

FILE_SIZE = 4 << 20
CONCURRENCY = 128


def random_string(seed: int) -> bytes:
    r = random.Random(seed)
    buf = bytearray()
    for i in range(FILE_SIZE):
        buf.append(r.randrange(0, 256))
    return bytes(buf)


def do_write(path: str, data: bytes) -> None:
    with gfile.GFile(path, 'wb') as f:
        f.write(data)


def do_validate(path: str, expected: bytes) -> None:
    with gfile.GFile(path, 'rb') as f:
        got = f.read()
    if expected != got:
        return f"{path} is corrput"
    return None


def test_path(n: int) -> str:
    return f"s3://grail-ysaito/tmp/tmpfile{n}"


def main():
    logging.basicConfig(level=logging.DEBUG)
    pool = futures.ThreadPoolExecutor(max_workers=CONCURRENCY)
    num_files = 10
    logging.info("Generating data for %d files", num_files)
    data = [random_string(n) for n in range(num_files)]
    logging.info("Writing %d files", num_files)
    n = 0
    for r in [
            pool.submit(do_write, test_path(n), data[n])
            for n in range(num_files)
    ]:
        r.result()
        n += 1
        if n % 100 == 0:
            logging.info("wrote %d files", n)

    logging.info("Reading %d files", num_files)
    for r in [
            pool.submit(do_validate, test_path(n), data[n])
            for n in range(num_files)
    ]:
        msg = r.result()
        if msg:
            logging.error(msg)


main()

`

**Comment by yasushi-saito** [comment]
Try the attached file. You need to change test_path. With CONCURRENCY > 1, I consistency get file corruption. With CONCURRENCY=1, I don't see an error.

[gfilebug.txt](https://github.com/tensorflow/tensorflow/files/3387404/gfilebug.txt)

**Comment by tomasferraro** [comment]
Any news on this issue? It seems that the aws-sdk fixed the issue on version 1.7.153
https://github.com/aws/aws-sdk-cpp/issues/1192#issuecomment-518383782

**Comment by tomasferraro** [comment]
As now, almost a year has passed since this issue was opened. @jvishnuvardhan do you know if this issue fixed on a newer tf release?

**Comment by jvishnuvardhan** [comment]
@tomasferraro Sorry for missing this issue. Can you please check the issue with recent versions like `TF1.15.2` and `TF2.2`. Thanks!
