### ISSUE TITLE
TFTRT: Can I specify the computation precision for a specific layer?

### ISSUE THREAD

**Issue by x10000year** [tensorflow/tensorflow#30600]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using):
1.14

**Describe the feature and the current behavior/state.**
Support blacklist of ops that cannot use lower precision when converting a graph into tftrt with precision mode of fp16 or int8. Or provide a way to specify a subgraph that cannot be optimized by tftrt.

**Who will benefit with this feature?**
All users that need a mixed precision of their model and want to optimize the model by tftrt.

**Any Other info.**

In my product I'm developing a model that needs full precision for a few layers (which include elementwise ops and conv ops). The layers need full precision because they are doing some math computation that cannot sacrifice precision. I also want to use tftrt to optimize the graph because most of other layers can use precision as low as fp16 or int8. However, i cannot find a way in tftrt to specify a blacklist of ops that cannot use lower precision. And there is no way to specify a subgraph that cannot be optimized by tftrt. Tensorrt supports specifying a precision for a layer but my model uses many ops that don't exist in tensorrt so I cannot convert it into tensorrt.

Thank you.

@trevor-m

**Comment by motionlife** [comment]
the only way is thru tf.cast?

**Comment by x10000year** [comment]
@motionlife  I think tftrt will automatically convert all conv ops to use precision mode specified in the graph conversion api, and there is no way to disable tftrt for a subgraph. How can tf.cast solve this?

**Comment by aaroey** [comment]
I believe now it'll fallback to fp16 if int8 is not available, see [here](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/compiler/tf2tensorrt/convert/convert_nodes.cc#L1581-L1588). Does this work for you @x10000year ?

**Comment by x10000year** [comment]
@aaroey Yes, that's definitely useful! Then I can force some layer to use fp16. It will be better if there's a way to force some layer to use fp32.

**Comment by aaroey** [comment]
@pooyadavoodi would you please take a look? Thanks.

**Comment by pooyadavoodi** [comment]
This feature is currently not supported by TF-TRT.
Since TensorRT supports this already, we can consider adding this feature.
It would require an API such that users can provide a list of ops/subgraphs with their desired precision. 
We don't currently have a plan to add this feature.

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.
