### ISSUE TITLE
Calling .map on a tf.data.Dataset causes unrelated imports to fail

### ISSUE THREAD

**Issue by BeWe11** [tensorflow/tensorflow#30604]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): MacOS 10.14.5
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): v1.12.1-6008-gd883916ee4 2.0.0-dev20190711 
- Python version: 3.6
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Describe the current behavior**

When `.map` is called on a `tf.data.Dataset`, some available imports are getting lost. I've stumbled upon this being unable to import `tf.summary.create_file_writer` after mapping a function onto a dataset, even though I can import it in ipython. Several other methods of `tf.summary` are lost as well. I didn't check whether any other tensorflow models apart form `summary` loose imports.

**Describe the expected behavior**

Calling `.map` on a `tf.data.Dataset` should leave available imports intact.

**Code to reproduce the issue**
```
import tensorflow as tf

print(tf.summary.create_file_writer)

def map_fun(x):
    return x

ds = tf.data.Dataset.from_tensor_slices([1, 2, 3, 4, 5])

ds = ds.map(map_fun)

print(tf.summary.create_file_writer)
```

**Other info / logs**
Output of the above code snippet:
```
<function create_file_writer_v2 at 0x13180d9d8>
2019-07-11 17:12:16.193865: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA                                                  
2019-07-11 17:12:16.208592: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x7fc08db4f5b0 executing computations on platform Host. Devices:                                                                     
2019-07-11 17:12:16.208619: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): <undefined>, <undefined>                                                                                            
Traceback (most recent call last):
  File "bug_test.py", line 12, in <module>
    print(tf.summary.create_file_writer)
AttributeError: module 'tensorflow_core.summary' has no attribute 'create_file_writer'
```

**Comment by gadagashwini** [comment]
@BeWe11 I executed the given code on Colab with Tensorflow 2.0.0-dev20190711 but i did not get any error. The below is the result

```
> 2.0.0-dev20190711
> <function create_file_writer_v2 at 0x7f037d67dea0>
> <function create_file_writer_v2 at 0x7f037d67dea0>
```
Can you please try once and let us know. Thanks!

**Comment by BeWe11** [comment]
After reinstallation of tensorflow, the problem has disappeared. Thanks!
