### ISSUE TITLE
[r13.1] ImportError for  tf.keras.applications.imagenet_utils.preprocess_input

### ISSUE THREAD

**Issue by swghosh** [tensorflow/tensorflow#30610]
**System information**

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Mac OS (Mojave) 10.14.4
- TensorFlow installed from (source or binary): binary (pip)
- TensorFlow version (use command below): 1.13.1
- Python version: 3.6.7

- CUDA/cuDNN version: No GPU
- GPU model and memory: No GPU

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
None of the following imports work are working on the current version:
```{python}
from tensorflow.keras.applications import imagenet_utils
from tensorflow.keras.applications.imagenet_utils import preprocess_input

from tensorflow.keras.applications import preprocess_input
```

**Describe the expected behavior**
The aforementioned imports should work. I reviewed the source code for branch r1.13 examining file tensorflow/python/keras/applications/__init__.py

https://github.com/tensorflow/tensorflow/blob/2aca283764bbbd54a5556319eb7cc0ed323c81f1/tensorflow/python/keras/applications/__init__.py#L74-L86

`preprocess_input` appears to be missing. 

**Code to reproduce the issue**
Provided above.

**Comment by gadagashwini** [comment]
@swghosh The above mentioned imports are available in master branch.Please have a look at this [link](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/keras/applications/__init__.py#L53-L72). let us know if that solves the problem. Thanks!

**Comment by swghosh** [comment]
Sure thing, the imports appear to be working as on the master branch. Thanks for clarifying @gadagashwini
