### ISSUE TITLE
[Documentation] In TF 1.13.1, tf.keras.experimental.export does not exist despite being documented

### ISSUE THREAD

**Issue by zmjjmz** [tensorflow/tensorflow#30616]
## URL(s) with the issue:

https://www.tensorflow.org/versions/r1.13/api_docs/python/tf/keras/experimental/export

## Description of issue (what needs changing):

Ok, so let's say for some arbitrary reason out of your control (*cough* sagemaker *cough*) you are pegged to TensorFlow <= 1.13.1. The cool new `tf.keras.experimental.export` feature looks a _lot_ easier than building all that stuff yourself, so you go to try and use it.

Unfortunately, you get hit with the following error:
```
Traceback (most recent call last):
  File "documented_example.py", line 10, in <module>
    saved_to_path = tf.keras.experimental.export(
AttributeError: 'module' object has no attribute 'export'
```

### Correct links

It is not -- the part that is `Defined in tensorflow/python/keras/saving/saved_model.py.` links to `https://github.com/tensorflow/tensorflow/blob/r1.13/tensorflow/python/keras/saving/saved_model.py` which gets a 404!

### Parameters defined

Probably.

### Returns defined

Very possible

### Raises listed and defined

Yep.

### Usage example

Yes! In fact, it doesn't work.

For posterity here's that usage example copy-pasted into a Github gist: https://gist.github.com/zmjjmz/fcc73dad9f49d34f9c047c108fdd0e3f

### Submit a pull request?

Nope.

**Comment by kmh4321** [comment]
I think the issue is that the newer version (r1.14) has [this module](https://github.com/tensorflow/tensorflow/blob/r1.14/tensorflow/python/keras/saving/saved_model.py#L47) but when the release was cut for 1.14, some changes were backported to r1.13 API documentation?

**Comment by zmjjmz** [comment]
I was thinking that, but the difference between the documentation for 1.13's [`tf.keras.experimental.export`](https://www.tensorflow.org/versions/r1.13/api_docs/python/tf/keras/experimental/export) and 1.14's [`tf.keras.experimental.export_saved_model`](https://www.tensorflow.org/api_docs/python/tf/keras/experimental/export_saved_model) is pretty significant.

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.
