### ISSUE TITLE
Supervisor should start queue runners before initializing the model

### ISSUE THREAD

**Issue by rafaljozefowicz** [tensorflow/tensorflow#3061]
For some use cases, the models use a random batch of inputs when initializing the weights. Currently (as of version 0.9) this is not supported with Supervisor that uses queues. It attempts to initialize the model before starting queue runners (https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/training/supervisor.py#L650 method prepare_or_wait_for_session).

Do you think changing the order of operations in this method is reasonable? 
1. recover_session() 
2. start_queue_runners() (currently done at the end)
3. initialize_model()

Thanks!

**Comment by sherrym** [comment]
Please migrate to using monitored_session which does exactly what you want. I will close this bug as we will not be making any more changes to Supervisor.

**Comment by LMescheder** [comment]
Apparently, MonitoredSession does not solve the issue (see [here](https://github.com/tensorflow/tensorflow/issues/6624)).
