### ISSUE TITLE
Save and Load keras model in multi-gpu environment changing the input and output tensor names

### ISSUE THREAD

**Issue by anilknayak** [tensorflow/tensorflow#30617]
API Used:
Kerras==2.2.4
Tensorflow=1.13.1

Problem Statement:
After I load my saved keras model for retraining, it changes the input and output tensor names.

Code to replicate:
```
from keras.applications import MobileNet
from keras.layers import Input
from keras.utils import multi_gpu_model
from keras.models import model_from_json, load_model

input_tensor = Input(shape=(224, 224, 3), name="input")
pre_trained_model = MobileNet(input_shape=(224,224,3),
                                       alpha=1,
                                       depth_multiplier=1,
                                       dropout=1e-3,
                                       include_top=True,
                                       weights='imagenet',
                                       input_tensor=input_tensor,
                                       classes=1000)
last_layer = pre_trained_model.layers[-1].output
output_tensor = Dense(10, activation='softmax', name='output')(last_layer)
model = Model(inputs=input_tensor, outputs=output_tensor)
model = multi_gpu_model(model, gpus=4)
model.compile(
            optimizer='adam',
            loss='binary_crossentropy',
            metrics='accuracy',
        )

---- Training ----

architecture_file="model_arch.json"
weight_file="model_weights.h5"
model.save_weights(weight_file)
with open(architecture_file, 'w') as f:
     f.write(model.to_json())

```
After the first training, when I froze the model and loaded into the testing environment, I could feed to ```input``` node and get output from ```output```

Then reload and train again
```
 with open(architecture_file, 'r') as f:
      model = model_from_json(f.read())
      model.load_weights(weight_file, by_name=True)

model.compile(
            optimizer='adam',
            loss='binary_crossentropy',
            metrics='accuracy',
        )

---- training ----
architecture_file="model_arch.json"
weight_file="model_weights.h5"
model.save_weights(weight_file)
with open(architecture_file, 'w') as f:
     f.write(model.to_json())
````

After the second training from the saved model, when I froze the model and loaded into the testing environment,
I could feed to input to ```input``` node the input node has changed to ```input_1```

**Comment by anilknayak** [comment]
I have tried same thing using ```model.save()```, the same result, the input tensor name has changed.
Code to reproduce
```
from keras.applications import MobileNet
from keras.layers import Input
from keras.utils import multi_gpu_model
from keras.models import model_from_json, load_model

input_tensor = Input(shape=(224, 224, 3), name="input")
pre_trained_model = MobileNet(input_shape=(224,224,3),
                                       alpha=1,
                                       depth_multiplier=1,
                                       dropout=1e-3,
                                       include_top=True,
                                       weights='imagenet',
                                       input_tensor=None,
                                       classes=1000)
last_layer = pre_trained_model.layers[-1].output
output_tensor = Dense(10, activation='softmax', name='output')(last_layer)
model = Model(inputs=input_tensor, outputs=output_tensor)
model = multi_gpu_model(model, gpus=4)
model.compile(
            optimizer='adam',
            loss='binary_crossentropy',
            metrics='accuracy',
        )

---- Training ----

model_file="entire_model.h5"
model.save(model_file)
```
above code 
1. Input node name by default is ```input_1```
2. output node name is ```output```

then load the previous model and starts the training from where it stopped

```
model = load_model(model_file)
---- training ----
model_file="entire_model.h5"
model.save(model_file)
```

above code 
1. Right now input has two nodes named ```input_1``` and ```input_1_1```
2. output node name is ```output```

but after I load that model for prediction, I could not pass the image to ```input_1``` rather i have to use 
```input_1_1``` instead.

This really a problem, If I have to retrain the model it will every time adds a new input node.

The tensorboard also shows the same ```input_1_1``` as the input not the ```input_1```

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.
