### ISSUE TITLE
Failed to load the native TensorFlow runtime.

### ISSUE THREAD

**Issue by game-sys** [tensorflow/tensorflow#30612]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):Windows 10 64bit
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version (use command below):pip install tensorflow

- Python version:3.7
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:no gpu 

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**

**Describe the expected behavior**

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.
import tensorflow as tf

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

"C:\Users\Mohsin Ali\Anaconda3\envs\keras3.6\python.exe" "G:/Data Camp/keras3.6/test.py"
Traceback (most recent call last):
  File "C:\Users\Mohsin Ali\Anaconda3\envs\keras3.6\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\Mohsin Ali\Anaconda3\envs\keras3.6\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\Mohsin Ali\Anaconda3\envs\keras3.6\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Users\Mohsin Ali\Anaconda3\envs\keras3.6\lib\imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\Mohsin Ali\Anaconda3\envs\keras3.6\lib\imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: A dynamic link library (DLL) initialization routine failed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "G:/Data Camp/keras3.6/test.py", line 1, in <module>
    import tensorflow as tf
  File "C:\Users\Mohsin Ali\Anaconda3\envs\keras3.6\lib\site-packages\tensorflow\__init__.py", line 28, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "C:\Users\Mohsin Ali\Anaconda3\envs\keras3.6\lib\site-packages\tensorflow\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Users\Mohsin Ali\Anaconda3\envs\keras3.6\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "C:\Users\Mohsin Ali\Anaconda3\envs\keras3.6\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\Mohsin Ali\Anaconda3\envs\keras3.6\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\Mohsin Ali\Anaconda3\envs\keras3.6\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Users\Mohsin Ali\Anaconda3\envs\keras3.6\lib\imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\Mohsin Ali\Anaconda3\envs\keras3.6\lib\imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: A dynamic link library (DLL) initialization routine failed.

Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

Process finished with exit code 1

**Comment by rmothukuru** [comment]
@game-sys ,
Can you please confirm if you have installed Visual Studio? If not, can you please install it from this [link](https://visualstudio.microsoft.com/vs/older-downloads/) and check if the issue still persists.
Thanks.

**Comment by game-sys** [comment]
installed Visual studio firstly was working on PyCharm but error not resolved


  Message=Traceback (most recent call last):
  File "C:\Users\Mohsin Ali\Anaconda3\envs\test\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\Mohsin Ali\Anaconda3\envs\test\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\Mohsin Ali\Anaconda3\envs\test\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Users\Mohsin Ali\Anaconda3\envs\test\lib\imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\Mohsin Ali\Anaconda3\envs\test\lib\imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: A dynamic link library (DLL) initialization routine failed.


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.
  Source=C:\Users\Mohsin Ali\source\repos\PythonApplication1\PythonApplication1\PythonApplication1.py
  StackTrace:
  File "C:\Users\Mohsin Ali\source\repos\PythonApplication1\PythonApplication1\PythonApplication1.py", line 2, in <module>
    import tensorflow as tf

**Comment by game-sys** [comment]
anyone can suggest something as problem is not resolved till now

**Comment by gadagashwini** [comment]
@game-sys Can you confirm your CPU supports AVX2 instructions? Thanks!

**Comment by game-sys** [comment]
No my CPU is xeon w3565 and I think it does not support AVX2

**Comment by gadagashwini** [comment]
@game-sys Please take a look at the [Tensorflow](https://www.tensorflow.org/install/source_windows#configuration_options) website. Thanks!

**Comment by game-sys** [comment]
got this using bazel

c:\tensorflow>bazel build --config=opt //tensorflow/tools/pip_package:build_pip_package
WARNING: The following rc files are no longer being read, please transfer their contents or import their path into one of the standard rc files:
c:\tensorflow/tools/bazel.rc
WARNING: Ignoring JAVA_HOME, because it must point to a JDK, not a JRE.
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=1 --terminal_columns=120
INFO: Reading rc options for 'build' from c:\tensorflow\.tf_configure.bazelrc:
  'build' options: --action_env PYTHON_BIN_PATH=C:/Users/Mohsin Ali/Anaconda3/python.exe --action_env PYTHON_LIB_PATH=C:/Users/Mohsin Ali/Anaconda3/lib/site-packages --python_path=C:/Users/Mohsin Ali/Anaconda3/python.exe --define with_xla_support=true --define with_gdr_support=true --define with_verbs_support=true --action_env TF_NEED_OPENCL_SYCL=0 --action_env TF_NEED_CUDA=0 --action_env TF_DOWNLOAD_CLANG=0 --define grpc_no_ares=true --strip=always --config monolithic --copt=-w --host_copt=-w --verbose_failures
ERROR: Config value monolithic is not defined in any .rc file

**Comment by gadagashwini** [comment]
@game-sys Please provide the exact command if possible to produce the output included in your test case. Thanks!

**Comment by game-sys** [comment]
C:\WINDOWS\system32>cd c:\

c:\>cd tensorflow

c:\tensorflow>git checkout r1.9
Already on 'r1.9'
Your branch is up to date with 'origin/r1.9'.

c:\tensorflow>python ./configure.py
WARNING: The following rc files are no longer being read, please transfer their contents or import their path into one of the standard rc files:
c:\tensorflow/tools/bazel.rc
WARNING: Ignoring JAVA_HOME, because it must point to a JDK, not a JRE.
WARNING: --batch mode is deprecated. Please instead explicitly shut down your Bazel server using the command "bazel shutdown".
You have bazel 0.27.2 installed.
Please specify the location of python. [Default is C:\Python27\python.exe]:


Found possible Python library paths:
  C:\Python27\lib\site-packages
Please input the desired Python library path to use.  Default is [C:\Python27\lib\site-packages]

Do you wish to build TensorFlow with XLA JIT support? [y/N]: .Y
Invalid selection: .Y
Do you wish to build TensorFlow with XLA JIT support? [y/N]: Y
XLA JIT support will be enabled for TensorFlow.

Do you wish to build TensorFlow with GDR support? [y/N]: Y
GDR support will be enabled for TensorFlow.

Do you wish to build TensorFlow with VERBS support? [y/N]: Y
VERBS support will be enabled for TensorFlow.

Do you wish to build TensorFlow with CUDA support? [y/N]: N
No CUDA support will be enabled for TensorFlow.

Do you wish to build TensorFlow with MPI support? [y/N]: N
No MPI support will be enabled for TensorFlow.

Please specify optimization flags to use during compilation when bazel option "--config=opt" is specified [Default is /arch:AVX]:


Would you like to interactively configure ./WORKSPACE for Android builds? [y/N]: N
Not configuring the WORKSPACE for Android builds.

Preconfigured Bazel build configs. You can use any of the below by adding "--config=<>" to your build command. See tools/bazel.rc for more details.
        --config=mkl            # Build with MKL support.
        --config=monolithic     # Config for mostly static monolithic build.

c:\tensorflow>


what to do next?

**Comment by game-sys** [comment]
And also tell is above configuration is correct to run tensorflow

**Comment by gadagashwini** [comment]
@game-sys Please take a look at the instructions mentioned in the [Tensorflow website](https://www.tensorflow.org/install/source_windows) to build Tensorflow from source on Windows system.Thanks!

**Comment by gadagashwini** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
