### ISSUE TITLE
Feature: Add safe division in reciprocal operation

### ISSUE THREAD

**Issue by kmh4321** [tensorflow/tensorflow#30620]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using): 1.14 / 2.0 alpha
- Are you willing to contribute it (Yes/No): Yes

**Describe the feature and the current behavior/state.**
Hello, 
I wanted to add a feature to the `tf.math.reciprocal` operation to optionally perform "safe" reciprocal. If the input is zero, it returns zero instead of NaN. I found this feature useful when implementing one of the recent [PR](https://github.com/tensorflow/tensorflow/pull/30152/files#diff-614af081276f42dbb98e5d731d7a1a86R158). This is similar to the [`tf.math.div_no_nan`](https://github.com/tensorflow/tensorflow/pull/21621) operation/PR. 

Should this feature request be approved, I can either add an optional argument to the current `tf.math.reciprocal()` operation which indicates whether to perform safe division. The default for this would be False, thus retaining the current interface. OR I can create a new tf.math operation called `tf.math.reciprocal_no_nan()` similar to the safe division op. Would love inputs on this!

**Will this change the current api? How?**
Depending on the two options laid out above, the first option would change the current API slightly, while the second option adds a new operation. 

**Who will benefit with this feature?**
Any researcher designing algorithms involving reciprocals as well as engineers/developers who would otherwise write wrapper functions to perform safe reciprocals. 

**Any Other info.**

**Comment by alextp** [comment]
tf.math.reciprocal_no_nan is probably the best name for this

**Comment by kmh4321** [comment]
Thank you, @alextp I'll raise a PR for this soon! Would it be possible to assign this issue to me?

**Comment by kmh4321** [comment]
@alextp  I am planning to implement a full-fledged operation (in C++, will be part of `gen_math_ops`) and add a wrapper on Python api similar to the other core math ops. This would have better performance and could perhaps be easily extended to other (non-python) APIs like tfjs in the future.

The other option is to try and implement it with existing TF ops in just the python api, and so only affecting the Python API.  While easier, it seems more restrictive. 

Should I continue with the first option or switch to the second one? Just wanted to check before I start.

**Comment by alextp** [comment]
To implement a full-fledged C++ operation you probably want to change eigen to get this to vectorize well (I think? Let's ask @rmlarsen).

If you don't you won't gain much over implementing this with existing ops, which is what I mildly prefer.

**Comment by kshitij12345** [comment]
@kmh4321 This issue can be closed now!?

**Comment by kmh4321** [comment]
@kshitij12345 sure, I  haven't taken a look at this in a while so you can close it for now.

**Comment by ymodak** [comment]
Closing this issue since the associated PR has been merged and the [feature](https://www.tensorflow.org/api_docs/python/tf/math/reciprocal_no_nan) has been implemented. Thanks!
