### ISSUE TITLE
tf.sysconfig.get_link_flags() issue

### ISSUE THREAD

**Issue by zhangyafeikimi** [tensorflow/tensorflow#30633]
Env:
tensorflow 1.14.0
macos

tf.sysconfig.get_link_flags() returns
```
['-L/Users/kimmyzhang/anaconda2/lib/python2.7/site-packages/tensorflow',
 '-l:libtensorflow_framework.1.dylib']
```

"-l:libtensorflow_framework.1.dylib" will cause a custom op compilation failure:
```
ld: library not found for -l:libtensorflow_framework.1.dylib
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

It should be -ltensorflow_framework.

**Comment by yongtang** [comment]
Think the ld should be `-ltensorflow_framework.1`. Created a PR #30633 for the fix.

**Comment by yongtang** [comment]
The issue has been fixed through PR #30656

**Comment by zhangyafeikimi** [comment]
-ltensorflow_framework is OK.

**Comment by zhangyafeikimi** [comment]
furthermore, on linux, there is the same issue.
