### ISSUE TITLE
CUDA10.1 with tensorflow-gpu==2.0.0b1

### ISSUE THREAD

**Issue by MuseMamba** [tensorflow/tensorflow#30638]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution:Linux manjaro (e.g., Linux Ubuntu 16.04):
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):pip install tensorflow-gpu==2.0.0-b1
- TensorFlow version:2.0.0b1
- Python version:3.7
- Installed using virtualenv? pip? conda?:pip
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:10.1
- GPU model and memory:rtx2070

**Describe the problem**
tf.test.is_gpu_available():
I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Could not dlopen library 'libcudart.so.10.0'; dlerror: libcudart.so.10.0: cannot open shared object file: No such file or directory
2019-07-12 16:39:38.345749: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Could not dlopen library 'libcublas.so.10.0'; dlerror: libcublas.so.10.0: cannot open shared object file: No such file or directory
2019-07-12 16:39:38.345852: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Could not dlopen library 'libcufft.so.10.0'; dlerror: libcufft.so.10.0: cannot open shared object file: No such file or directory
2019-07-12 16:39:38.345953: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Could not dlopen library 'libcurand.so.10.0'; dlerror: libcurand.so.10.0: cannot open shared object file: No such file or directory
2019-07-12 16:39:38.346052: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Could not dlopen library 'libcusolver.so.10.0'; dlerror: libcusolver.so.10.0: cannot open shared object file: No such file or directory
2019-07-12 16:39:38.346153: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Could not dlopen library 'libcusparse.so.10.0'; dlerror: libcusparse.so.10.0: cannot open shared object file: No such file or directory

**Provide the exact sequence of commands / steps that you executed before running into the problem**

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by edwardyehuang** [comment]
Try install the cudatoolkit (2nd latest version) and cudnn via conda

**Comment by sh4kesbeer** [comment]
I am having the same issue under the same conditions except for:
OS: arch
GPU: GT 710

**Comment by MuseMamba** [comment]
> Try to install the cudatoolkit (2nd latest version) and cudnn via conda

Well, I have tried this, but it didn't work. I have installed the cudatoolkit-10.1.168 and cudnn-7.6.0-cuda10.1_0 in m the server.

**Comment by edwardyehuang** [comment]
> 
> 
> > Try to install the cudatoolkit (2nd latest version) and cudnn via conda
> 
> Well, I have tried this, but it didn't work. I have installed the cudatoolkit-10.1.168 and cudnn-7.6.0-cuda10.1_0 in m the server.

Install the cudatookit 10.0.130.
I tried 10.1.168 few weeks before, had some errors

**Comment by pandrey-fr** [comment]
As of now, TensorFlow does not support CUDA 10.1, thus you need to install CUDA 10.0, as indicated in the software requirements section of [https://www.tensorflow.org/install/gpu](https://www.tensorflow.org/install/gpu).

**Comment by MuseMamba** [comment]
> As of now, TensorFlow does not support CUDA 10.1, thus you need to install CUDA 10.0, as indicated in the software requirements section of https://www.tensorflow.org/install/gpu.

Yea, I have installed the ubuntu18 on the server and use the cuda10.0 for tensorflow-gpu==2.0b1, it works so far so good.

**Comment by ravikyram** [comment]
@MuseMamba 
Can we close this issue as it was resolved.Thanks!

**Comment by bingo-todd** [comment]
I have the same problem. Take 'libcurand.so.10.0' as example, in my case, logs said
`I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Could not dlopen library 'libcublas.so.10.0'; dlerror: libcublas.so.10.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/cuda-10.1/lib64`
However in ` /usr/local/cuda-10.1/lib64`, there are libcurand.so, libcurand.so.10, libcurand.10.1.1.243.
and the last two are actually linked to libcurand.so, so I just create a link named libcurand.so.10.0 and link it to libcurand.so, no warnings

**Comment by pierreN** [comment]
Can't bloody nvidia just open source everything. Those managers should be hanged. Wasted way too much time on this.

**Comment by pandrey-fr** [comment]
> Can't bloody nvidia just open source everything. Those managers should be hanged. Wasted way too much time on this.

To be fair, this issue has barely anything to do with CUDA not being open-source, as it is a mere version compatibility issue. That being said...
