### ISSUE TITLE
[Documentation][TF 1.14] Missing documentation for `batch_dims` in `tf.gather`

### ISSUE THREAD

**Issue by MartinusR** [tensorflow/tensorflow#30634]
## URL(s) with the issue:

https://www.tensorflow.org/api_docs/python/tf/gather

## Description of issue (what needs changing):

In TF 1.14, `tf.batch_gather` is marked as deprecated, and the keyword `batch_dims` has been added to `tf.gather` to handle the batch version. Though, the documentation of `tf.gather` has only been updated with the **type** of `batch_dims`, but not **how to use** it neither **what it does**.

The old [`tf.batch_gather`](https://www.tensorflow.org/versions/r1.13/api_docs/python/tf/batch_gather) function was documented in TF 1.13. Though, `tf.gather` is a bit more complex than the old `tf.batch_gather`, so maybe the [documentation of the underlying `_batch_gather`](https://github.com/tensorflow/tensorflow/blob/2aca283764bbbd54a5556319eb7cc0ed323c81f1/tensorflow/python/ops/array_ops.py#L3514) function could be used.

These two existing documentations could be used to complete the existing documentation of `tf.gather`.

### Correct links

Yes.

### Parameters defined

Yes

### Returns defined

Yes

### Raises listed and defined

Yes

### Usage example

Not for using `batch_dims`.

### Submit a pull request?

No.

**Comment by agupta4** [comment]
I would like to make a contribution for this request.

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.

**Comment by MarkDaoust** [comment]
https://www.tensorflow.org/api_docs/python/tf/gather?version=nightly

`tf.gather` docs have been greatly expanded. I think this is covered.
