### ISSUE TITLE
How do I create a custom OP using TF1.14?

### ISSUE THREAD

**Issue by TCBocean** [tensorflow/tensorflow#30632]
I am a TensorFlow beginner. The environment I use is ubuntu18.04, python3.7, TensorFlow-GPU1.14, CUDA10.0.

I want to build a custom OP (using GPU), I saw from the official website tutorial that you need to include #include "tensorflow/core/util/cuda_kernel_helper.h" in the source code.
But when I was "make", I got an error: "cuda_kernel_helper.h" was not found.

In addition, I used the python environment built by anaconda. I found gpu_kernel_helper.h in the folder in the environment. I guess this is a replacement file for cuda_kernel_helper.h. When I replace the file name in my source code, another one appears. Error: "third_party/gpus/cuda/include/cuda_fp16.h" file not found.
After that, I only found the "eigen3" folder in the “third_party” folder and did not find the "gpus" folder.
I installed TensorFlow-gpu using pip. Is there a problem with my installation method?

I hope to get help to solve this problem. thank you all.

**Comment by Uiuran** [comment]
Why are you importing a .h header file in python ? do you know the difference from python API and the C++ backend ? 
The docs:
https://www.tensorflow.org/api_docs

**Comment by TCBocean** [comment]
> Why are you importing a .h header file in python ? do you know the difference from python API and the C++ backend ?
> The docs:
> https://www.tensorflow.org/api_docs

@Uiuran Thank you very much for your answer.
Sorry, I don't know much about this knowledge.
I am trying to learn TensorFlow through the project given below. When I executed the "make" command in the "hdrnet" folder, I had the problems I raised. So I am very confused.
Do I need to install a C++ library into my system?
Project: https://github.com/mgharbi/hdrnet
I look forward to your reply again, thank you.

**Comment by ravikyram** [comment]
@TCBocean 

Just to verify did you get chance to follow instructions from [TensorFlow](https://www.tensorflow.org/guide/extend/op) website .Please, let us know. Thanks!

**Comment by TCBocean** [comment]
> @TCBocean
> 
> Just to verify did you get chance to follow instructions from [TensorFlow](https://www.tensorflow.org/guide/extend/op) website .Please, let us know. Thanks!

@ravikyram 
Hello, in the example, the code for "kernel_example.cu.cc" has a header file "#include tensorflow/core/util/cuda_kernel_helper.h". But when I compiled ".so" with g++, I was prompted not to find this file. I did not find this file in the "\Anaconda3\envs\CV_env\Lib\site-packages\tensorflow\include\tensorflow\core\util" folder.
I did not install the C++ library, but instead used the python library installed by pip. Is Python's TensorFlow library not compiling ".so"? Do I need to install a C++ version of the library?
I saw
"TF_CFLAGS=( $(python -c 'import tensorflow as tf; print(" ".join(tf.sysconfig.get_compile_flags())))) )
TF_LFLAGS=( $(python -c 'import tensorflow as tf; print(" ".join(tf.sysconfig.get_link_flags()))') )" The path obtained is the path in python, which makes me very doubt.
Also, I can't open the two links in "PREREQUISITES:", I don't know what it is inside.
Looking forward to your answer, thank you

**Comment by gunan** [comment]
https://github.com/tensorflow/custom-op for the latest documentation on creating custom ops.
@yifeif may be able to answer if there is anything missing there.

**Comment by TCBocean** [comment]
@yifeif  @ravikyram   
I think I am lucky.
I changed my environment:
Ubuntu16.04
gcc4.8
CUDA9.0
cudnn7.1.4
TensorFlow-gpu1.12
I used the code framework in "https://github.com/tensorflow/custom-op" to replace the custom OP code in the HDRnet project and successfully compiled the dynamic library.
Thank you for your active help.
