### ISSUE TITLE
How to convert TFmodel to TFLite Model????

### ISSUE THREAD

**Issue by Deepak-HpyAda** [tensorflow/tensorflow#30645]
System information

OS Platform and Distribution (e.g., Linux Ubuntu 16.04): MacOS
Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: No
TensorFlow installed from (source or binary): Command Line
TensorFlow version: 1.14.0
Python version: 3.7.3
Installed using virtualenv? pip? conda?: conda
Bazel version (if compiling from source): 0.28.0
GCC/Compiler version (if compiling from source): No
CUDA/cuDNN version: NO
GPU model and memory:NO

I found different ways to convert Tensorflow model to Tensorflow Lite model
using Bazel
using Toco
using tflite_convert.py

All these method give error
I need a proper suggestion to convert TFModel to TFLiteModel
The error says 

**tflite_convert.py: error: --input_arrays and --output_arrays are required with --graph_def_file**

**ValueError: Invalid tensors 'input' were found.**

Thank you

**Comment by rohaansp97** [comment]
the same problem plz anyone help!

**Comment by cruigo93** [comment]
You need to specify name of input layer, for example I used Netron to know it

**Comment by Deepak-HpyAda** [comment]
> You need to specify name of input layer, for example I used Netron to know it

I installed Netron, It asked for model to use. I selected my model. It is displaying a big graph.
I m not able find a solution. How to use the value in my code

**Comment by Deepak-HpyAda** [comment]
I updated the code with 
--input_array=image_tensor—output_array=output
Now a new error has arrived 
**tflite_convert.py: error: the following arguments are required: --output_file**

**Comment by KauthamMurugan** [comment]
You have to give the output file name with path in the --output_file parameter
Eg: --output_file=/Documents/my_Lite_graph.tflite

**Comment by Deepak-HpyAda** [comment]
> You have to give the output file name with path in the --output_file parameter
> Eg: --output_file=/Documents/my_Lite_graph.tflite
 
I Solved it thank you KauthamMurugan

**Comment by Deepak-HpyAda** [comment]
**toco: error: --input_arrays and --output_arrays are required with --graph_def_file**

this is my code

toco --graph_def_file=/Users/deepak/Documents/Tensorflow/workspace/training_demo/trained-inference-graphs/output_inference_graph_v1/frozen_inference_graph.pb--input_array=Identity_6 —output_array=TensorArrayWriteV3 --output_file=/Users/deepak/Desktop/TFlite/frozen_inference_graph.tflite --output_format=TFLITE --input_shape=1,224,224,3--inference_type=FLOAT --inference_input_type=FLOAT

I need Help!!!!

**Comment by ymodak** [comment]
```toco``` is deprecated can you please ```tflite_convert``` instead. See https://www.tensorflow.org/lite/convert/cmdline_examples#command-line_tools_

**Comment by Deepak-HpyAda** [comment]
Hi, Thanks for the feedback

I'm trying with tflite_convert.py 
with this code, kindly verify my code. Even this gives me error

**cd /Applications/anaconda3/envs/tensorflow_cpu/lib/python3.7/site-packages/tensorflow/lite/python

python ./tflite_convert.py --graph_def_file=/Users/deepak/Documents/Tensorflow/workspace/training_demo/trained-inference-graphs/output_inference_graph_v1/frozen_inference_graph.pb --input_array=input—output_array= final_result --output_file=/Users/deepak/Desktop/TFlite/frozen_inference_graph.tflite --input_format=TENSORFLOW_GRAPHDEF --output_format=TFLITE --input_shape=1,300,300,3 --inference_type=FLOAT --input_data_type=FLOAT**

**ValueError: Invalid tensors 'input' were found.**

**Comment by haozha111** [comment]
Hi,

I'm wondering if the input tensor name you specified is correct. Could you try the tf graph summary tool[1] which will list the input/output tensors of a graph?

[1]https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/graph_transforms/summarize_graph_main.cc

**Comment by Deepak-HpyAda** [comment]
Hi, I am able to convert tensorflow model to tensorflowlite model through this code

**tflite_convert --output_file=/Users/deepak/Desktop/Quantize/undertaker.tflite --graph_def_file=/Users/deepak/Desktop/Quantize/tflite_graph.pb --input_arrays=normalized_input_image_tensor --output_arrays='TFLite_Detection_PostProcess','TFLite_Detection_PostProcess:1','TFLite_Detection_PostProcess:2','TFLite_Detection_PostProcess:3' --input_shapes=1,300,300,3 --inference_type=FLOAT  --mean_values=128 --std_dev_values=128 --change_concat_input_ranges=false --allow_custom_ops**

My model is **55.3 Mb** size
After this process my model turn into .tflite file
The size of that file is **54.9 Mb**
I need to **Quantize my model!!!!**

I tried to add **--inference_type= QUANTIZED_UINT8**
This doesn't work for me but 
**--inference_type= FLOAT**
this one is working.....

**<<<<**HOW TO CONVERT MY TENSORFLOW MODEL TO TENSORFLOW LITE MODEL BY QUANTIZING**>>>>**

I need to reduce my model's size as it is been trained to use for mobile device........

**Thanks Tensorflow!!!!!!!!**

**Comment by haozha111** [comment]
Could you post the error here when you specify  --inference_type= QUANTIZED_UINT8?

In the meantime, you can checkout post-training quantization here and give it a try:
https://www.tensorflow.org/lite/performance/post_training_quantization

**Comment by Deepak-HpyAda** [comment]
Thank you 
I solved it. But the accuracy has gone done
I used this code to Convert TFModel to TFlite Model

set the python location in the terminal
**cd /Applications/anaconda3/envs/tensorflow_cpu/lib/python3.7/site-packages/tensorflow/lite/python**

Then add this code to Convert the Model to a Quantized one!!!

**tflite_convert --output_file=$(Output file Location_ name it with outputfile.tflite)
--graph_def_file=$(Input file Location_ name it with inputfile.pb)
--input_arrays=normalized_input_image_tensor --output_arrays='TFLite_Detection_PostProcess','TFLite_Detection_PostProcess:1','TFLite_Detection_PostProcess:2','TFLite_Detection_PostProcess:3' 
--input_shapes=1,300,300,3 
--inference_type=QUANTIZED_UINT8  
--mean_values=128 
--std_dev_values=128 
--change_concat_input_ranges=false 
--allow_custom_ops 
--default_ranges_min=0 
--default_ranges_max=255
**

This code will convert the model to a quantized one, which reduced my model from 55Mb to 13Mb of size....

If you want a model with float inference type then, change the inference type to **FLOAT**
but the model will not reduce its size..

Thanks GITHUB!!!!
Hope this will be useful for Who will Search for 
"How to convert TFModel to TFLite Model"

**Comment by Ehtasha** [comment]
@Deepak-HpyAda 
How you get the output paramters ?
