### ISSUE TITLE
Filling shuffle buffer, this happens before the beginning of every epoch. Is there a way to avoid it?

### ISSUE THREAD

**Issue by rishabhsahrawat** [tensorflow/tensorflow#30646]
I am following [this tutorial](https://www.tensorflow.org/beta/tutorials/load_data/text#split_the_dataset_into_text_and_train_batches), however I am using my own dataset stored as a csv file consisting 1265800 elements. My question is:
Before the beginning of every epoch, it shows `Filling up shuffle buffer (this may take a while)`. I think it means that it is shuffling the dataset before feeding it to the model for training. Is there a way to not to shuffle this before every epoch because it takes time before proceeding to the next epoch.
Also, this behaviour is not seen if I run the example model on Google Colab. I also read [this issue](https://github.com/tensorflow/tensorflow/issues/29957) but didn't help.
Thank you for your inputs.

**Comment by rmothukuru** [comment]
Shuffling is required to Train the Model with as many different Samples (Versatile data) as possible. Since your data is huge, you can use [tf.data.experimental.shuffle_and_repeat](https://www.tensorflow.org/api_docs/python/tf/data/experimental/shuffle_and_repeat), which combines the best of good performance and varied Samples. Refer this [TF Link](https://www.tensorflow.org/guide/performance/datasets#repeat_and_shuffle) for more info.

**Comment by rmothukuru** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Comment by rishabhsahrawat** [comment]
Hi @rmothukuru , thank you for your suggestion. Please excuse me I could not test it earlier and respond here. 
I followed your suggestion and instead of using `Dataset.shuffle` as used in the [link](https://www.tensorflow.org/beta/tutorials/load_data/text#split_the_dataset_into_text_and_train_batches), I am using `Dataset.apply(tf.data.experimental.shuffle_and_repeat())` from [here](https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/data/experimental/shuffle_and_repeat) but the problem still is there. What still happening is, it is still filling up the buffer and for that it is consuming the CPU RAM memory which after sometime fills up and everything stops responding then I have to kill every process. My questions are,
Is this a normal behaviour and if so, then how can one shuffle a huge dataset like this? Or do I need more CPU RAM so that it can be used for filling up the shuffle buffer?

**Comment by rishabhsahrawat** [comment]
I tried to train the model without using `shuffle()` function. It does not fill up the buffer but the start of the model training, it throws `(GPU_0_bfc) ran out of memory trying to allocate 1.37GiB (rounded to 1467428096)`. I am not sure on how to troubleshoot this problem, I tried various batch sizes also like 1,2, 128,256,512, 1024.

**Comment by rishabhsahrawat** [comment]
Hello @rmothukuru , any updates on the issue? Because, I still can not shuffle my data before feeding it to the mode for training. :(

**Comment by jvishnuvardhan** [comment]
@rishabhsahrawat Is this still an issue.? I noticed you have opened multiple issues on this or similar topic. If this was covered in other opened issues, then please close this issue. Thanks!

**Comment by rishabhsahrawat** [comment]
Yes, this has been answered [here](https://github.com/tensorflow/tensorflow/issues/32376).
