### ISSUE TITLE
No TRTEngineOps after Conversion (Tiny Yolov3)

### ISSUE THREAD

**Issue by nseidl** [tensorflow/tensorflow#30657]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): centos 7
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: NA
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below): v1.14.0-rc1-22-gaf24dc91b5 1.14.0
- Python version: 3.6.8
- Bazel version (if compiling from source): NA
- GCC/Compiler version (if compiling from source): NA
- CUDA/cuDNN version: 10.0 / 7.6.0
- GPU model and memory: Tesla V100 32GB

**Describe the current behavior**
I am trying to convert a Tiny Yolov3 frozen graph into a frozen graph with some operations replaced with TRTEngineOps so that they are run with TensorRT. My graph has many [nodes that are supported by TF-TRT](https://docs.nvidia.com/deeplearning/frameworks/tf-trt-user-guide/index.html#supported-ops) yet none are simplified into a TRTEngineOp.

After conversion, this is the count of different `node.op` in the resulting frozen graph:
```
{
    "Placeholder": 1,
    "Const": 84,
    "Mul": 7,
    "Transpose": 26,
    "Conv2D": 13,
    "FusedBatchNorm": 11,
    "LeakyRelu": 11,
    "MaxPool": 6,
    "ResizeNearestNeighbor": 1,
    "Identity": 4,
    "BiasAdd": 2,
    "ConcatV2": 5,
    "Reshape": 2,
    "SplitV": 3,
    "Sigmoid": 6,
    "Exp": 2,
    "Add": 4,
    "Sub": 2
}
```

And, information regarding the conversion process:
```
graph_size(MB)(native_tf): 34.0
graph_size(MB)(trt): 34.0
num_nodes(native_tf): 300
num_nodes(tftrt_total): 190
num_nodes(trt_only): 0
time(s) (trt_conversion): 8.8426
```

**Describe the expected behavior**
I expect some groups of nodes / subgraphs to be converted into TRTEngineOps so that they can run in TensorRT. According to the [supported ops](https://docs.nvidia.com/deeplearning/frameworks/tf-trt-user-guide/index.html#supported-ops), the following operators could / should have been somewhat simplified into TRTEngineOps: `Const`, `Mul`, `Conv2D`, `FusedBatchNorm`, `MaxPool`, `Identity`, `BiasAdd`, `ConcatV2`, `Reshape`, `Sigmoid`, `Exp`, `Add`, and `Sub`. In fact, this is nearly all the operators, save for `Placeholder`, `Transpose`, `LeakyRelu`, `ResizeNearestNeighbor`, and `SplitV`.

**Code to reproduce the issue**
(functionality used from [example here](https://github.com/tensorflow/tensorrt/tree/master/tftrt/examples/object_detection))
```
import tensorflow as tf
import time

from tensorflow.python.compiler.tensorrt import trt_convert as trt

def optimize_model(frozen_graph,
                   use_trt=True,
                   force_nms_cpu=True,
                   replace_relu6=True,
                   remove_assert=True,
                   is_dynamic_op=True,
                   precision_mode='FP32',
                   max_batch_size=1,
                   minimum_segment_size=1,
                   max_workspace_size_bytes=2 << 32,
                   maximum_cached_engines=100,
                   calib_images_dir=None,
                   num_calib_images=None,
                   calib_batch_size=1,
                   calib_image_shape=None,
                   output_path=None):
    # apply graph modifications
    if force_nms_cpu:
        frozen_graph = f_force_nms_cpu(frozen_graph)
    if replace_relu6:
        frozen_graph = f_replace_relu6(frozen_graph)
    if remove_assert:
        frozen_graph = f_remove_assert(frozen_graph)
    # get input names
    output_names = ['inputs', 'output_boxes']

    # optionally perform TensorRT optimization
    if use_trt:
        graph_size = len(frozen_graph.SerializeToString())
        num_nodes = len(frozen_graph.node)
        start_time = time.time()

        converter = trt.TrtGraphConverter(
            input_graph_def=frozen_graph,
            nodes_blacklist=output_names,
            max_workspace_size_bytes=max_workspace_size_bytes,
            precision_mode=precision_mode,
            minimum_segment_size=minimum_segment_size,
            is_dynamic_op=is_dynamic_op,
            maximum_cached_engines=maximum_cached_engines,
            max_batch_size=max_batch_size)
        frozen_graph = converter.convert()

        end_time = time.time()
        print("graph_size(MB)(native_tf): %.1f" % (float(graph_size)/(1<<20)))
        print("graph_size(MB)(trt): %.1f" %
            (float(len(frozen_graph.SerializeToString()))/(1<<20)))
        print("num_nodes(native_tf): %d" % num_nodes)
        print("num_nodes(tftrt_total): %d" % len(frozen_graph.node))
        print("num_nodes(trt_only): %d" % len([1 for n in frozen_graph.node if str(n.op)=='TRTEngineOp']))
        print("time(s) (trt_conversion): %.4f" % (end_time - start_time))

    return frozen_graph

input_graph_path = '/path/to/frozen_graph.pb'

with tf.io.gfile.GFile(input_graph_path, 'rb') as f:
    orig_graph_def = tf.compat.v1.GraphDef()
    orig_graph_def.ParseFromString(f.read())

frozen_graph_def = optimize_model(orig_graph_def,
                                  precision_mode=PRECISION,
                                  max_batch_size=64,
                                  is_dynamic_op=False)

for node in frozen_graph_def.node:
    print(node.op, node.name)
```

**Other info / logs**
Click [here](https://drive.google.com/file/d/1Bgj9h6TJLwedtrhnritRs9eYm_iczG4v/view?usp=sharing) for the graph in question.

Additionally, regardless of which precision of `FP32`, `FP16`, and `INT8` I use for precision, the size of the resulting models is `exactly` the same number of bytes. I observe no inference speed-up either.

**Comment by aaroey** [comment]
Apparently there is some issues with TF-TRT in 1.14, @bananabowl for more information.

If you try with tf-nightly-gpu, the output will look like:
```
2019-07-22 09:20:39.761959: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:716] Optimization results for grappler item: tf_graph
2019-07-22 09:20:39.762029: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:718]   constant folding: Graph size after: 171 nodes (-128), 186 edges (-130), time = 107.078ms.
2019-07-22 09:20:39.762049: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:718]   layout: Graph size after: 223 nodes (52), 238 edges (52), time = 38.567ms.
2019-07-22 09:20:39.762065: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:718]   constant folding: Graph size after: 223 nodes (0), 238 edges (0), time = 44.786ms.
2019-07-22 09:20:39.762081: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:718]   TensorRTOptimizer: Graph size after: 31 nodes (-192), 40 edges (-198), time = 13152.8809ms.
2019-07-22 09:20:39.762097: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:718]   constant folding: Graph size after: 23 nodes (-8), 36 edges (-4), time = 69.685ms.
graph_size(MB)(native_tf): 34.0
graph_size(MB)(trt): 61.6
num_nodes(native_tf): 299
num_nodes(tftrt_total): 23
num_nodes(trt_only): 6
time(s) (trt_conversion): 15.2821
Placeholder inputs
Const detector/tiny-yolo/Conv_6/weights
Const detector/tiny-yolo/Const
Const detector/tiny-yolo/split/split_dim
Const detector/tiny-yolo/ResizeNearestNeighbor/size
Const detector/tiny-yolo/Const_1
Const detector/tiny-yolo/split_1/split_dim
Const Const
Const split/split_dim
Const output_boxes/axis
TRTEngineOp TRTEngineOp_0
Identity detector/tiny-yolo/Conv_6/weights/read
Conv2D detector/tiny-yolo/Conv_6/Conv2D
TRTEngineOp detector/tiny-yolo/TRTEngineOp_3
SplitV detector/tiny-yolo/split
ResizeNearestNeighbor detector/tiny-yolo/ResizeNearestNeighbor
TRTEngineOp detector/tiny-yolo/TRTEngineOp_4
SplitV detector/tiny-yolo/split_1
TRTEngineOp detector/tiny-yolo/TRTEngineOp_6
SplitV split
TRTEngineOp TRTEngineOp_1
TRTEngineOp TRTEngineOp_2
ConcatV2 output_boxes
```

**Comment by chong-lee** [comment]
According to my experience, model optimized directly with the tf default installation package does not have 'TRTEngineOp', which means that the optimization is not successful. According to NVIDIA's official documentation, you need to use TensorFlow container or compile TensorFlow with TensorRT through source code. The latter one I tried is ok(cuda10+tf1.14). Through experiments, QPS of the classification model (inception_v3) for FP16 is increased by 3 times. However, for the OCR model, because the input is not fixed, the optimization is not successful.

**Comment by nseidl** [comment]
> Apparently there is some issues with TF-TRT in 1.14, @bananabowl for more information.
> 
> If you try with tf-nightly-gpu, the output will look like:
> 
> ```
> 2019-07-22 09:20:39.761959: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:716] Optimization results for grappler item: tf_graph
> 2019-07-22 09:20:39.762029: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:718]   constant folding: Graph size after: 171 nodes (-128), 186 edges (-130), time = 107.078ms.
> 2019-07-22 09:20:39.762049: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:718]   layout: Graph size after: 223 nodes (52), 238 edges (52), time = 38.567ms.
> 2019-07-22 09:20:39.762065: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:718]   constant folding: Graph size after: 223 nodes (0), 238 edges (0), time = 44.786ms.
> 2019-07-22 09:20:39.762081: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:718]   TensorRTOptimizer: Graph size after: 31 nodes (-192), 40 edges (-198), time = 13152.8809ms.
> 2019-07-22 09:20:39.762097: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:718]   constant folding: Graph size after: 23 nodes (-8), 36 edges (-4), time = 69.685ms.
> graph_size(MB)(native_tf): 34.0
> graph_size(MB)(trt): 61.6
> num_nodes(native_tf): 299
> num_nodes(tftrt_total): 23
> num_nodes(trt_only): 6
> time(s) (trt_conversion): 15.2821
> Placeholder inputs
> Const detector/tiny-yolo/Conv_6/weights
> Const detector/tiny-yolo/Const
> Const detector/tiny-yolo/split/split_dim
> Const detector/tiny-yolo/ResizeNearestNeighbor/size
> Const detector/tiny-yolo/Const_1
> Const detector/tiny-yolo/split_1/split_dim
> Const Const
> Const split/split_dim
> Const output_boxes/axis
> TRTEngineOp TRTEngineOp_0
> Identity detector/tiny-yolo/Conv_6/weights/read
> Conv2D detector/tiny-yolo/Conv_6/Conv2D
> TRTEngineOp detector/tiny-yolo/TRTEngineOp_3
> SplitV detector/tiny-yolo/split
> ResizeNearestNeighbor detector/tiny-yolo/ResizeNearestNeighbor
> TRTEngineOp detector/tiny-yolo/TRTEngineOp_4
> SplitV detector/tiny-yolo/split_1
> TRTEngineOp detector/tiny-yolo/TRTEngineOp_6
> SplitV split
> TRTEngineOp TRTEngineOp_1
> TRTEngineOp TRTEngineOp_2
> ConcatV2 output_boxes
> ```

@aaroey Thank you. Updating to `tf-nightly-gpu==1.15.0.dev20190718` fixed the issue of no TRTEngineOps being created/used. Closing as this specific issue is fixed.
