### ISSUE TITLE
tf.data.Dataset.map() ignores eager execution

### ISSUE THREAD

**Issue by habernal** [tensorflow/tensorflow#30653]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes, see below
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): MacOS Mojave 10.14.5 (18F132)
- TensorFlow installed from (source or binary): tensorflow==2.0.0b1 from https://pypi.org/
- TensorFlow version (use command below): v2.0.0-beta0-16-g1d91213fe7 2.0.0-beta1
- Python version: Python 3.6.8
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

**Describe the current behavior**

By default, eager execution should be enabled in TF 2.0; so each tensor's value can be accessed by calling `.numpy()`.

When a function relying on accessing a tensor's value is passed as a parameter to `tf.data.Dataset.map()`, it seems that internally the tensor is no longer an `EagerTensor` and accessing its value fails.

**Describe the expected behavior**

I'm not sure whether this behavior is intended or not but either way it should be document and/or fixed.

Purpose: text-based operations on `tf.data.Dataset`, such as custom splitting, filtering, etc. ideally without the need to write a custom operation.

**Code to reproduce the issue**

MWE to reproduce the behavior in colab:

```python
!pip install tensorflow-gpu==2.0.0b1
!pip install tensorflow-datasets==1.0.2

import tensorflow as tf


# transform a string tensor to upper case
def upper_case_fn(t: tf.Tensor) -> tf.Tensor:
    print(type(t))
    return tf.constant(t.numpy().decode('utf-8').upper())


# the same with tf op
def upper_case_tf(t: tf.Tensor) -> tf.Tensor:
    print(type(t))
    return tf.strings.upper(t)


# sanity check
c1 = upper_case_fn(tf.constant('casing_fn'))
print(c1)

c2 = upper_case_tf(tf.constant('casing_tf'))
print(c2)

# dataset
d = tf.data.Dataset.from_tensor_slices([
    tf.constant('hello'),
    tf.constant('world')
])

# working with OP
d2 = d.map(lambda x: upper_case_tf(x))
for _ in d2:
    print(_)

# failing with Python fn
d2 = d.map(lambda x: upper_case_fn(x))
```

**Other info / logs**

```
Installing collected packages: tensorflow-datasets
Successfully installed tensorflow-datasets-1.0.2
<class 'tensorflow.python.framework.ops.EagerTensor'>
tf.Tensor(b'CASING_FN', shape=(), dtype=string)
<class 'tensorflow.python.framework.ops.EagerTensor'>
tf.Tensor(b'CASING_TF', shape=(), dtype=string)
<class 'tensorflow.python.framework.ops.Tensor'>
tf.Tensor(b'HELLO', shape=(), dtype=string)
tf.Tensor(b'WORLD', shape=(), dtype=string)
<class 'tensorflow.python.framework.ops.Tensor'>

---------------------------------------------------------------------------

AttributeError                            Traceback (most recent call last)

<ipython-input-1-44edb2261a09> in <module>()
     36 
     37 # failing with Python fn
---> 38 d2 = d.map(lambda x: upper_case_fn(x))

11 frames

<ipython-input-1-44edb2261a09> in upper_case_fn(t)
      8 def upper_case_fn(t: tf.Tensor) -> tf.Tensor:
      9     print(type(t))
---> 10     return tf.constant(t.numpy().decode('utf-8').upper())
     11 
     12 

AttributeError: 'Tensor' object has no attribute 'numpy'
```

**Comment by habernal** [comment]
My bad, this **is** documented:

```
    Note that irrespective of the context in which `map_func` is defined (eager
    vs. graph), tf.data traces the function and executes it as a graph. To use
    Python code inside of the function you have two options:
...
    2) Use `tf.py_function`, which allows you to write arbitrary Python code but
    will generally result in worse performance than 1).
```

Closing.

**Comment by habernal** [comment]
Nevertheless, it's not clear how to actually do it.... several attemps in this direction failed:

```python
# failing with Python fn
d2 = d.map(lambda x:
           tf.py_function(
               func=upper_case_fn(x),
               inp=[x],
               Tout=tf.string
           )
           )
```

**Comment by dynamicwebpaige** [comment]
Would this be resolved by using [`tf.numpy_function`](https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/numpy_function)? Adding @jsimsa for visibility. 🙂

**Comment by jsimsa** [comment]
The following works:

```
import tensorflow as tf

# transform a string tensor to upper case
def upper_case_fn(t):
    return t.numpy().upper()

# dataset
d = tf.data.Dataset.from_tensor_slices([
    tf.constant('hello'),
    tf.constant('world')
])

d = d.map(lambda x: tf.py_function(upper_case_fn, [x], tf.string))
for _ in d:
    print(_)
```

**Comment by cgebe** [comment]
Is there a simper way to access raw values?

In my case i had to:

```
        def get_label(file_path):
            # convert the path to a list of path components
            parts = file_path.numpy().decode().split(os.path.sep)
            # The second to last is the class-directory
            return [str(self.label_dict[parts[-1]])]
```

on top of calling tf.py_function.

This looks a bit circuitous.

**Comment by bhlarson** [comment]
"tf.py_function" has different behavior and does not replace the need for eager execution for tf.data.Dataset.map functions.  My purpose for using tf.data is to accelerate loading data.  eager execution allows me to inspect tensor values and computation with the debuger.   tf.numpy_function, instrad, converts inputs from tensors to numpy arrays and outputs from numpy arrays to tensors.  I cannot see the tensor values and verify the logic with tf.numpy_function because the tensors are no longer there.  

Please, instead, use @tf.function to enable graph vs eager execution of tf.data.Dataset.map functions consistent with tensorflow 2 behavior

**Comment by jsimsa** [comment]
There is no eager execution of tf.data.

In TF 2 eager mode, tf.data input pipeline graph is constructed eagerly, an iterator for the input pipeline graph is created eagerly, and then, the "give me the next element" is (repeatedly) executed eagerly. The "give me the next element" op executes the input pipeline graph (and often this execution in fact happens asynchronously ahead time so that by the time data is requested, it has already been precomputed).

In other words, given how tf.data works, executing user-defined functions passed to tf.data transformations eagerly is not trivially possible. For that to make sense, there would need to be no asynchrony in the input pipeline and the tf.data (mostly C++) implementation would either need to be updated to support switching between C++ and Python execution (for which the current mechanism is `tf.py_function`) or have alternative Python backend which would be used for this "eager" mode.

The tf.data team has no plans to support this.

**Comment by bhlarson** [comment]
Thank you for your explanation.  The execution pipelining has certainly speed my training and eliminated software bottlenecks compared with my previous python dataset processing.

**Comment by leenabora** [comment]
Following code worked:

    def parse_str(str_tensor):
        raw_string = str_tensor.numpy().decode("utf-8") 
    
        # play with raw string
        raw_string = 'AAA'+raw_string     
        return raw_string
    

Call parse function:


    def tf_pre_processing(row):
      return tf.py_function(parse_str, [row['context']], [tf.string])
    
    
    train = t.map(tf_pre_processing).batch(1).take(1)
    
    list(train)

**Comment by zaccharieramzi** [comment]
@jsimsa Thanks for this explanation.

Given this current limitation, do you have any tips regarding how to best debug a `tf.data` pipeline?
Typically with any other TensorFlow module I would activate eager mode (`tf.config.run_functions_eagerly(True)`) and use breakpoints. Of course without eager mode it's not possible to breakpoint.

**Comment by jsimsa** [comment]
If you would like to debug using breakpoints, my suggestion is to:

1) remove any `prefetch` or `num_parallel_calls` arguments in `map` or `interleave` from your input pipeline
2) wrap all functions passed into tf.data transformations that accept user-defined functions (such as `map`) in `tf.py_function`)

Thanks to 1) the input pipeline will be executing fully synchronously and 2) will allow you to use breakpoints.

**Comment by cgebbe** [comment]
@jsimsa : Your advice on how to debug is greatly appreciated! However, it doesn't seem to work for me :(. Using tensorflow 2.4.1, pycharm and windows and your code example:

```
import tensorflow as tf

tf.config.run_functions_eagerly(True)


def upper_case_fn(t):
    x = t.numpy().upper()  # BREAKPOINT HERE
    return x


# dataset
d = tf.data.Dataset.from_tensor_slices([tf.constant("hello"), tf.constant("world")])
d = d.map(lambda x: tf.py_function(upper_case_fn, [x], tf.string))
for _ in d:
    print(_)
```


Result is: The code does not stop at the specified breakpoint

**Comment by zwbx** [comment]
Same problem
