### ISSUE TITLE
TPUEstimator function requires `train_batch_size` to be set when `use_tpu` is True

### ISSUE THREAD

**Issue by jaymody** [tensorflow/tensorflow#30658]
The [TPUEstimator constructor](https://github.com/JayMody/estimator/blob/e794e634ba52f9e8b04971e74fe24b91857f2228/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py#L2590) requires `train_batch_size` to be set if `use_tpu` is True. 

In cases when I only want to use a TPU estimator to predict, that means I have to pass in an arbitrary value in for `train_batch_size`. Looking deeper into the code, I can't pinpoint why `train_batch_size` needs to be set when on a TPU, but I'm assuming it's required somewhere deeper in the code. 

It was very confusing for me, especially since the documentation is conflicting [pull request #37](https://github.com/tensorflow/estimator/pull/37#issue-297115525). 

Maybe an option should be added that if `train_batch_size` is not set, but one of the other two (eval and predict) are, then provide a warning and pass an arbitrary value for `train_batch_size`. Otherwise maybe be more clear with the documentation that `train_batch_size` must always be set when on a TPU, even if you are only predicting or evaluating.

**Comment by sachinprasadhs** [comment]
TPU Estimator manages its own TensorFlow graph and session, so it is not compatible with TF2 behaviors.
We recommend that you migrate to the newer `tf.distribute.TPUStrategy`. 
See the [TPU guide](https://www.tensorflow.org/guide/tpu) for details.

**Comment by MarkDaoust** [comment]
Yes. `tf.estimator` is deprecated.
