### ISSUE TITLE
About Quantization Full Integer: Test with Yolo Tiny v2

### ISSUE THREAD

**Issue by Izabellaaaq** [tensorflow/tensorflow#30655]
Hello, 

We tested the integer quantization in the scenarios of the table below, but we did not succeed in testing with Yolo Tiny v2, we would like to know what kind of optimization there is in mobilenet, inception and resnet so that we can apply in Yolo so that I can quantize and obtain a smaller inference time for the quantized model.

![image](https://user-images.githubusercontent.com/8125226/61136270-b11e1100-a499-11e9-8d52-efb148f6ab10.png)

**Comment by liyunlu0618** [comment]
Sorry for the delayed response.

1. Try if post-training integer quantization works now.
2. If 1 doesn't work, try not passing representative dataset and only enable default optimization. This gives you a weight-only quantized model. You should be able to see some speedup with that. More details:
https://www.tensorflow.org/lite/performance/post_training_quantization
