### ISSUE TITLE
tf.keras.layers.Conv2D does not initialize kernel and bias when called inside name_scope

### ISSUE THREAD

**Issue by Uiuran** [tensorflow/tensorflow#30666]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 1.14.0
- Python version: Python 2
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: -
- GPU model and memory: No GPU

**Describe the current behavior**

It throws this
FailedPreconditionError: Error while reading resource variable name9/conv_linear/bias from Container: localhost. This could mean that the variable was uninitialized. Not found: Container localhost does not exist. (Could not find resource: localhost/gcnn2d_d1/conv_linear/bias)

when trying to run the graph with a feed dict to get variable value

**Describe the expected behavior**

Expect to see a normal run since the variables are initialized inside the Conv2D function

**Code to reproduce the issue**

graph = tf.Graph()
with graph.name_scope('name9'):
  with graph.as_default():
    sign_in = tf.placeholder(tf.float32,(data_shape[0],data_shape[1],data_shape[2],data_shape[3]), name='signal_in')

    conv = tf.keras.layers.Conv2D(  10, (10,2), padding='valid', name='conv_linear', use_bias=True,  kernel_initializer=tf.initializers.lecun_normal(seed=137), bias_initializer=tf.initializers.lecun_normal(seed=137)  )(sign_in)

data_tensor = np.random.rand(10,40,2,1)
feed_dict = {
  graph.get_tensor_by_name('signal_in:0'):data_tensor
}

op_value = session.run('/name9/conv_linear:0', feed_dict=feed_dict)  
 

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by Uiuran** [comment]
Update, just corrected it by using
``
with graph.as_default():
  with tf.variable_scope('name9'):
``
In relation to this one has to say " never use name_scope to define ops, unless you wanna recover the name_scope of the graph".

and then before running the Op in question

`` 
tf.global_variables_initializer()
sess.run(tf.get_operations()[-1])
``

but have to do and silly if condition to see if any init Op was not added. 

My question relies, why add many Initializers on Variables such Convolutions Variables Scopes and then only initialize them in the run ? Why not immediatly initialize it ? 

What do you think ?

**Comment by anush-o** [comment]
@Uiuran ,
We tried executing the code given by you and we are encountering the error mentioned below

`KeyError: "The name 'signal_in:0' refers to a Tensor which does not exist. The operation, 'signal_in', does not exist in the graph."`

**Comment by Uiuran** [comment]
```python
graph = tf.Graph()
data_shape=(10,40,2,1)

tf.reset_default_graph()
with graph.as_default():
  with tf.variable_scope('name9'):  
    sign_in = tf.placeholder(tf.float32,(data_shape[0],data_shape[1],data_shape[2],data_shape[3]), name='signal_in')
    conv = tf.keras.layers.Conv2D(  10, (10,2), padding='valid', name='conv_linear', use_bias=True,  kernel_initializer=tf.initializers.lecun_normal(seed=137), bias_initializer=tf.initializers.lecun_normal(seed=137)  )(sign_in)

data_tensor = np.random.rand(10,40,2,1)
    
feed_dict = {
  graph.get_tensor_by_name('name9/signal_in:0'):data_tensor
}

session = tf.Session(graph=graph)
op_value = session.run('name9/conv_linear/BiasAdd:0', feed_dict=feed_dict)
```

**Comment by Uiuran** [comment]
maybe this is just a more aesthetical question, either to add the op programmatically or add all in once, like the changes in the 2.0 version.

**Comment by anush-o** [comment]
I was able to replicate the issue with TF version 1.14.Thanks!

**Comment by karmel** [comment]
It looks like you are mixing low-level TF APIs with Keras, which can yield strange behavior. When using Keras, tf.keras.Input is preferable to tf.placeholder, and model.predict is preferable to trying to run individual outputs. You can see some examples [here](https://www.tensorflow.org/guide/keras).

**Comment by Uiuran** [comment]
however the conv implementations force us to use keras, what should be only
a short to a name-space with all ops to do convolution. Also, why input is
supposed to have a different behavior than tf.placeholder ?

Keras, supposing to make the things easier, changes the behavior that one
is waiting from the low level API and make things lot harder to debug.

**Comment by karmel** [comment]
I think that gives me a better sense for what you are trying to do, and I would highly recommend trying out the [beta](https://www.tensorflow.org/beta), in which you can just pass the np array directly through the conv layer:

```
data = np.random.rand(10,40,2,1)
conv = tf.keras.layers.Conv2D(  10, (10,2), padding='valid', name='conv_linear', use_bias=True,  kernel_initializer=tf.initializers.lecun_normal(seed=137), bias_initializer=tf.initializers.lecun_normal(seed=137))
conv(data)
```

**Comment by Uiuran** [comment]
Agree with you, TF 2.0 beta seems to be beautifull and intuitive to use. But i would like to know how much they changed the API and the Backend

**Comment by jvishnuvardhan** [comment]
@Uiuran Please check [`effective_tf2`](https://www.tensorflow.org/beta/guide/effective_tf2), and [`release_notes`](https://github.com/tensorflow/tensorflow/releases) to know how much was changed in 2.0. There are lots of other resources too including [`tutorials`](https://www.tensorflow.org/tutorials).

Please let us know whether we can close the issue. Thanks!

**Comment by Uiuran** [comment]
That's fine for now, i will have look on 2.0beta, the fact is have a lot of code and in moment cant stop sprinting to migrate or to learn the changes, but will do it asap. 

Thank you.
