### ISSUE TITLE
tf.data.Dataset.window encountered `AttributeError: '_VariantDataset' object has no attribute 'numpy'`

### ISSUE THREAD

**Issue by yongtang** [tensorflow/tensorflow#30664]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): n/a
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.0.0b1
- Python version: 2.7
- Bazel version (if compiling from source): n/a
- GCC/Compiler version (if compiling from source): n/a
- CUDA/cuDNN version:n/a
- GPU model and memory: n/a

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
```
ubuntu@ubuntu:/v# python
Python 2.7.15+ (default, Nov 27 2018, 23:36:35) 
[GCC 7.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
>>> tf.version.VERSION
'2.0.0-beta1'
>>> x = tf.data.Dataset.range(5)
>>> y = tf.data.Dataset.range(5).window(2)
>>> for i in x:
...   print(i.numpy())
... 
0
1
2
3
4
>>> for i in y:
...   print(i.numpy())
... 
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
AttributeError: '_VariantDataset' object has no attribute 'numpy'
>>> 
```
**Describe the expected behavior**

In the above example `for i in y:print(i.numpy())` should produce result without AttributeError.
```
for i in y:
...   print(i.numpy())
... 
0
1
2
3
4
```
**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

```python
import tensorflow as tf
tf.version.VERSION
x = tf.data.Dataset.range(5)
y = tf.data.Dataset.range(5).window(2)
for i in x:
  print(i.numpy())
for i in y:
  print(i.numpy())

```
**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by jsimsa** [comment]
This behavior is expected. `window` combines a finite sequence of elements of the input dataset into a single element of type dataset. The dataset object does not have `numpy`. If you would like to iterate over the element of `y`, you should do the following:

```
import tensorflow as tf
tf.version.VERSION
x = tf.data.Dataset.range(5)
y = tf.data.Dataset.range(5).window(2)
for i in x:
  print(i.numpy())
for i in y:
  for j in y:
    print(j.numpy())
```

**Comment by yongtang** [comment]
@jsimsa Thanks for the explanation 👍 !
