### ISSUE TITLE
Tensorboard webpage breaking on current build

### ISSUE THREAD

**Issue by mmuneebs** [tensorflow/tensorflow#3066]
**Tensorboard** GUI is breaking on the latest build after commit https://github.com/tensorflow/tensorflow/commit/861644c0bcae5d56f7b3f439696eefa6df8580ec.

On Chrome, only a blue header with buttons appears.
On Firefox, large button icons appear (unclickable).

The nightly build from about a week ago works fine with the orange header and using same event files.
Operating System: Ubuntu 14.04 x64

**Comment by qbx2** [comment]
This happens to me, too.

**Comment by 0xfe** [comment]
Same here. Here's a screenshot:

<img width="804" alt="screen shot 2016-06-28 at 8 33 14 pm" src="https://cloud.githubusercontent.com/assets/241299/16436876/9c4d87b8-3d6f-11e6-9386-9dd8b12a8249.png">

**Comment by jbruck** [comment]
I had this error, but pulling the most recent version seems to have fixed it.

**Comment by 0xfe** [comment]
Just pulled and rebuilt. Yes this is fixed. I think we can close this issue.

**Comment by mmuneebs** [comment]
Verified. Orange header and orange plots now.
