### ISSUE TITLE
Support Conv3D in profiler for FLOPS counting

### ISSUE THREAD

**Issue by patzm** [tensorflow/tensorflow#30673]
**System information**
- TensorFlow version (you are using): 1.13.1
- Are you willing to contribute it (Yes/No): Yes

**Describe the feature and the current behavior/state.**
The [TensorFlow Profiler](https://www.tensorflow.org/api_docs/python/tf/profiler/profile) currently does not support counting operations / FLOPS of Conv3D layers. I request that we add this feature. This [nice readme](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/profiler/g3doc/profile_model_architecture.md#profile-model-float-operations) describes how to add this, if I am not mistaken.

**Will this change the current api? How?**
No.

**Who will benefit with this feature?**
Everyone that uses 3D convolutions and wants to profile the compute complexity of a model.

**Any Other info.**
Code to quickly see that Conv3D operations are indeed not supported:
```python
import tensorflow as tf

with tf.Graph().as_default() as graph:
    inputs = tf.ones(shape=(1, 5, 32, 32, 3))
    tf.layers.conv3d(
        inputs,
        filters=6,
        kernel_size=(3, 3, 3),
        strides=(1, 1, 1),
        padding="valid",
        use_bias=True,
    )

profiling_options = tf.profiler.ProfileOptionBuilder.float_operation()
tf_profile = tf.profiler.profile(graph, options=profiling_options)
```
output
```
Profile:
node name | # float_ops
_TFProfRoot (--/17.17k flops)
  conv3d/BiasAdd (16.20k/16.20k flops)
  conv3d/kernel/Initializer/random_uniform (486/973 flops)
    conv3d/kernel/Initializer/random_uniform/mul (486/486 flops)
    conv3d/kernel/Initializer/random_uniform/sub (1/1 flops)
```

**Comment by petermattson** [comment]
Hi Patz, this is not mine. Maybe try Tensorboard folks or xprof team?

**Comment by patzm** [comment]
Sorry, I don't quite know what / who the xprof team is and how to reach them. Also, I doubt that this is TensorBoard specific or implemented there 🤔 .

**Comment by trisolaran** [comment]
hi, Martin:
  I am from the profiler team. I am glad to review your patch if you already have it. otherwise, I will try to figure out how to implemented this correctly.
Best
Jie

**Comment by patzm** [comment]
Hi Jie / @trisolaran ,
no I don't have a patch yet. I would be happy to work on it. But a small kick-start would be nice. E.g. the files to start looking. I also found that `depthwise_conv2d`, and also `separable_conv2d` are buggy / incomplete. Didn't file issue for those yet though.

**Comment by trisolaran** [comment]
I was not so sure  about the  nature of this issue but in
tensorflow/python/ops/nn_ops.py have following code:
@ops.RegisterStatistics("Conv3D", "flops")
def _calc_conv3d_flops(graph, node):

I would start from there to figure out why it is not doing what you had expected :)

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.

**Comment by patzm** [comment]
sorry guys, I sadly don't have time to work on this. I will close it for now until I either find time to revisit or if it occurs again.
