### ISSUE TITLE
GTX 1080 with CIFAR 10 example

### ISSUE THREAD

**Issue by zongyuange** [tensorflow/tensorflow#3068]
I ran the tensorflow CIFAR10 example and got the following error: (sometimes shows loss such as loss = 523454323, I reinstall the CPU only version and that works fine.)

### Environment info
Operating System: Ubuntu 14.04
GPU: GTX 1080
Installed version of CUDA and cuDNN: CUDA7.5, CUDNN V4

name: GeForce GTX 1080
major: 6 minor: 1 memoryClockRate (GHz) 1.7335
pciBusID 0000:02:00.0
Total memory: 7.92GiB
Free memory: 7.81GiB
W tensorflow/stream_executor/cuda/cuda_driver.cc:572] creating context when one is currently active; existing: 0x1e22300
I tensorflow/core/common_runtime/gpu/gpu_init.cc:102] Found device 1 with properties: 
name: GeForce GTX 1080
major: 6 minor: 1 memoryClockRate (GHz) 1.7335
pciBusID 0000:01:00.0
Total memory: 7.92GiB
Free memory: 7.05GiB
I tensorflow/core/common_runtime/gpu/gpu_init.cc:126] DMA: 0 1 
I tensorflow/core/common_runtime/gpu/gpu_init.cc:136] 0:   Y Y 
I tensorflow/core/common_runtime/gpu/gpu_init.cc:136] 1:   Y Y 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:838] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX 1080, pci bus id: 0000:02:00.0)
I tensorflow/core/common_runtime/gpu/gpu_device.cc:838] Creating TensorFlow device (/gpu:1) -> (device: 1, name: GeForce GTX 1080, pci bus id: 0000:01:00.0)
2016-06-28 12:03:35.740025: step 0, loss = 4.68 (4.7 examples/sec; 27.498 sec/batch)
W tensorflow/core/kernels/queue_base.cc:292] _0_input_producer: Skipping cancelled enqueue attempt with queue not closed
Traceback (most recent call last):
  File "cifar10_train.py", line 136, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 30, in run
    sys.exit(main(sys.argv))
  File "cifar10_train.py", line 132, in main
    train()
  File "cifar10_train.py", line 105, in train
    assert not np.isnan(loss_value), 'Model diverged with loss = NaN'
AssertionError: Model diverged with loss = NaN

**Comment by yaroslavvb** [comment]
Does it happen with CUDA 8.0? (GTX 1080 might not be well tested with CUDA 7.5, and there's a large improvement in performance on CUDA 8 as well)

**Comment by aymericdamien** [comment]
Using a similar environment: Ubuntu 16.04, GTX1080 (driver 367.27), CUDA 8, CUDNN v5, I didn't run into any issue. It may be linked to CUDA 7.5 or your driver?

**Comment by zongyuange** [comment]
Thanks, I will give it a try with CUDA 8.0 and see if this problem still exists.

**Comment by andydavis1** [comment]
Did this resolve the issue? Can we close this out?

**Comment by zongyuange** [comment]
Hi all, This issues has been resolved with code compiled with CUDA 8.0. 
Thanks all

**Comment by hassnov** [comment]
What tensorflow version were you using?

**Comment by uenoyama** [comment]
the **master branch** of tensorflow works well with GTX1080, CUDA8.0 and cudnn5.
(r0.9 doesn't work.)

**Comment by pannous** [comment]
bug confirmed on a box with  cuDNN4.0 CUDA7.5 GTX970

won't-fix/please-get-new-cuda?
