### ISSUE TITLE
TFLite speech example failing to train with -output_representation='spec'or'mfcc' examples/lite/examples/speech_commands/ml

### ISSUE THREAD

**Issue by KauthamMurugan** [tensorflow/tensorflow#30682]
My Environment 
Working sample Link : https://github.com/tensorflow/examples/tree/master/lite/examples/speech_commands/ml
Virtual environment : Anaconda Navigator
Editor : VS Code
Mode of execution : VS Code integrated Terminal with Conda envs
OS : Mac OSX

Tensorflow Version : 1.13.1 (as required in the samples requirement)

When i download the sample and run it as it is as per the ReadMe file, everything works perfectly fine. 
But when i try to change the "-output_representation" parameter value to 'spec' or 'mfcc' it doesn't work. I get the error `ValueError: total size of new array must be unchanged` in the `model.py line no : 59 x = Reshape([800, 20])(x)`. After a quick traceback i found that the spectrogram fingerprint size is taken as 257x98 for every second. So i change that line to `x = Reshape([257, 98])(x)` and it successfully passed through this line. 
But instead i get the following 
```
Traceback (most recent call last):
  File "/Users/minimaci73/anaconda3/envs/Samples/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1659, in _create_c_op
    c_op = c_api.TF_FinishOperation(op_desc)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Negative dimension size caused by subtracting 3 from 1 for 'conv1d_12/convolution/Conv2D' (op: 'Conv2D') with input shapes: [?,1,1,192], [1,3,192,256].
```
This happens in the line no 99: `x = _reduce_conv(x, 256, 3)`.

When i downloaded the ios example model and opened it in Netron i can clearly see that it uses audio spectrogram. 

What are all the changes that are to be done to train the model with 'spec', 'mfcc' and the 'mfcc_and_raw' ?

**Comment by KauthamMurugan** [comment]
Hi guys any update on this.

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.
