### ISSUE TITLE
Compiling libtensorflow-core.a using NDK16b or later?

### ISSUE THREAD

**Issue by alokprasad** [tensorflow/tensorflow#30684]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
Snapdragon 820 , Android
- TensorFlow installed from (source or binary):
Source
- TensorFlow version (use command below):
1.13

- Python version:
3
- Bazel version (if compiling from source):
NA
- GCC/Compiler version (if compiling from source):
4.9
- CUDA/cuDNN version:
NA
 GPU model and memory:
NA

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
Compilation Error
Due 

e/gen/obj/android_arm64-v8a/tensorflow/contrib/boosted_trees/proto/learner.pb.o
In file included from /opt/google/android-ndk-r16b/sources/cxx-stl/gnu-libstdc++/4.9/include/cwchar:44:0,
                 from /opt/google/android-ndk-r16b/sources/cxx-stl/gnu-libstdc++/4.9/include/bits/postypes.h:40,
                 from /opt/google/android-ndk-r16b/sources/cxx-stl/gnu-libstdc++/4.9/include/bits/char_traits.h:40,
                 from /opt/google/android-ndk-r16b/sources/cxx-stl/gnu-libstdc++/4.9/include/string:40,
                 from /home/nuc2/alok/tf-static-android/tensorflow/tensorflow/contrib/makefile/gen/proto/tensorflow/contrib/boosted_trees/proto/learner.pb.h:7,
                 from /home/nuc2/alok/tf-static-android/tensorflow/tensorflow/contrib/makefile/gen/proto/tensorflow/contrib/boosted_trees/proto/learner.pb.cc:4:
/opt/google/android-ndk-r16b/sources/android/support/include/wchar.h:32:24: fatal error: wchar.h: No such file or directory
 #include_next <wchar.h>

**Describe the expected behavior**

**Code to reproduce the issue**
Checkout r1.13 and export NDK_ROOT=/opt/google/r16b
**Other info / logs**
nuc2@nuc2-NUC7i5BNH:~/alok/tf-static-android/tensorflow$ export e/gen/obj/android_arm64-v8a/tensorflow/contrib/boosted_trees/proto/learner.pb.o
In file included from /opt/google/android-ndk-r16b/sources/cxx-stl/gnu-libstdc++/4.9/include/cwchar:44:0,
                 from /opt/google/android-ndk-r16b/sources/cxx-stl/gnu-libstdc++/4.9/include/bits/postypes.h:40,
                 from /opt/google/android-ndk-r16b/sources/cxx-stl/gnu-libstdc++/4.9/include/bits/char_traits.h:40,
                 from /opt/google/android-ndk-r16b/sources/cxx-stl/gnu-libstdc++/4.9/include/string:40,
                 from /home/nuc2/alok/tf-static-android/tensorflow/tensorflow/contrib/makefile/gen/proto/tensorflow/contrib/boosted_trees/proto/learner.pb.h:7,
                 from /home/nuc2/alok/tf-static-android/tensorflow/tensorflow/contrib/makefile/gen/proto/tensorflow/contrib/boosted_trees/proto/learner.pb.cc:4:
/opt/google/android-ndk-r16b/sources/android/support/include/wchar.h:32:24: fatal error: wchar.h: No such file or directory
 #include_next <wchar.h>

**Comment by jdduke** [comment]
TensorFlow Mobile (supported by contrib/makefile) has been deprecated, and we won't be retroactively patching fixes for 1.13. Is there a reason you cannot use TensorFlow Lite?

**Comment by alokprasad** [comment]
Most of the OPS are not supported on Tensorflow Lite , sometimes development is much faster if there is full support of Tensorflow on Android as we can use existing model as it is. With Unified Header changed in NDK15 and above , Compilation fails . It would be nice if someone make changes in Makefile to support NDK 15 and later and any pointer how to do so.

WIll try to make changes in Makefile and scripts as per 
https://android.googlesource.com/platform/ndk/+/ndk-release-r16/docs/UnifiedHeaders.md
to support new NDK.

**Comment by jdduke** [comment]
Note that you can use TF operators within TFLite using [this approach](https://www.tensorflow.org/lite/guide/ops_select).

**Comment by alokprasad** [comment]
@jdduke with that also with my model its throws error that enter and exit ops not supported
