### ISSUE TITLE
Installation issue with CUDA 8

### ISSUE THREAD

**Issue by bozhu5** [tensorflow/tensorflow#3069]
Hi,

I've attempted to install Tensorflow with CUDA 8 on Ubuntu 14.04 by installing from source since it doesn't seem like there are binaries available (following https://www.tensorflow.org/versions/r0.8/get_started/os_setup.html#installing-from-sources)

Everything installed well, but once I tried importing, I received this while trying to import tensorflow in python:
ImportError: libcudart.so.7.5: cannot open shared object file: No such file or directory.

I'm not sure where this is coming from, since I'm using CUDA 8.  I did have a previous installation of CUDA 7.5, but all those files got replaced, and there is no libcudart.so.7.5 (or anything 7.5) in the cuda lib64 folder.

Any thoughts? Many Thanks!

### Environment info
Operating System: Ubuntu 14.04
Graphics Card: NVIDIA GTX 1080 Founders Edition

Installed version of CUDA and cuDNN: CUDA 8.0, cuDNN 5.0
-rw-r--r-- 1 root     root       560184 Jun 27 16:13 /usr/local/cuda/lib64/libcudadevrt.a
lrwxrwxrwx 1 root     root           16 Jun 27 16:13 /usr/local/cuda/lib64/libcudart.so -> libcudart.so.8.0
lrwxrwxrwx 1 root     root           19 Jun 27 16:13 /usr/local/cuda/lib64/libcudart.so.8.0 -> libcudart.so.8.0.27
-rwxr-xr-x 1 root     root       394472 Jun 27 16:13 /usr/local/cuda/lib64/libcudart.so.8.0.27
-rw-r--r-- 1 root     root       737516 Jun 27 16:13 /usr/local/cuda/lib64/libcudart_static.a
lrwxrwxrwx 1 lfibrain lfibrain       13 Jun 27 17:02 /usr/local/cuda/lib64/libcudnn.so -> libcudnn.so.5
lrwxrwxrwx 1 lfibrain lfibrain       17 Jun 27 17:02 /usr/local/cuda/lib64/libcudnn.so.5 -> libcudnn.so.5.0.5
lrwxrwxrwx 1 lfibrain lfibrain       17 Jun 27 17:46 /usr/local/cuda/lib64/libcudnn.so.5.0 -> libcudnn.so.5.0.5
-rwxr-xr-x 1 lfibrain lfibrain 78065952 Apr 22 15:17 /usr/local/cuda/lib64/libcudnn.so.5.0.5
-rw-r--r-- 1 lfibrain lfibrain 68709594 Apr 22 15:17 /usr/local/cuda/lib64/libcudnn_static.a

If installed from sources, provide the commit hash:
861644c

### Steps to reproduce
1. Install NVIDIA 367 driver
2. Install CUDA 8.0
3. Install cuDNN 5.0
4. Reboot
5. Install tensorflow from source with bazel using the above configuration

### What have you tried?
1. reconfiguring/reinstalling tensorflow with inputting the exact directory locations (instead of pressing ENTER for default), even if the default locations were already correct.

**Comment by MInner** [comment]
afaik, it requires and work just fine with `cuda-7.5` and after you have it installed, you'd have all required `.so` files at `/usr/local/cuda-7.5`

**Comment by zongyuange** [comment]
Try to install with cuda7.5 instead. But i found weird results running the CIFAR 10 example under /models/imag/cifar10/cifar10_train.py

Let me know your results.

**Comment by aselle** [comment]
Closing for now, as we unfortunately do not yet support Cuda 8 as was mentioned by @zongyuange  and @MInner.

**Comment by vrv** [comment]
Others have been able to get it working with cuda 8.0, so I'd try a fresh clone of tensorflow in a different directory and use the latest bazel as well.

**Comment by bozhu5** [comment]
Yes indeed - a fresh clone worked out for me.  Thanks everyone.

**Comment by aselle** [comment]
Awesome. Glad you got it to work.

**Comment by aselle** [comment]
Also, there will be a Cuda 8.0 pre built binary when we are out of RC (see @vrv comment on #3052)

**Comment by vrv** [comment]
Our ./configure process unfortunately requires modifying the source code in the tree when you give it something other than the empty string, so re-cloning is probably the best thing to do in cases like these.

Alternatively, if you leave the defaults, it uses whatever is symlinked at libcudnn.so, and then there should be no source code rewriting going on.

@aselle , it's Nvidia we have to wait for, not us.

**Comment by iqbalmohomed** [comment]
@vrv I noticed that the official cuda 8 drivers are out. The tensorflow install instructions still indicate that source compilation is necessary for this version. Are the docs out of date or does the issue remain?

**Comment by steven200796** [comment]
@bozhu5 could you comment your process for working with a new clone? Many people, including myself, are having issues with cuda 8.0 and tf.

**Comment by gokul-uf** [comment]
@aselle Is TensorFlow binary for CUDA 8 ready?

**Comment by andrenatal** [comment]
I keep getting:

`ImportError: dlopen(/usr/local/lib/python2.7/site-packages/tensorflow/python/_pywrap_tensorflow.so, 10): Library not loaded: @rpath/libcudart.7.5.dylib`

Using CUDA 8 drivers on OSX.

**Comment by aselle** [comment]
Checked in with @gunan. We are aiming for CUDA 8 binaries in rc1.  @andrenatal, your error is because our binaries are for cuda 7.5, so if you want to use cuda 8 right now you have to build it yoruself.

**Comment by gunan** [comment]
@yifeif will keep track of the release of cuda8 binaries.
Yifei, could you close this issue once cuda8 binaries are released?

**Comment by gokul-uf** [comment]
@aselle @gunan What's the ETA of rc1?

**Comment by gunan** [comment]
It depends on the number of issues we see during the release, but at most 1
week.

**Comment by laventura** [comment]
Hi @andrenatal --

I get the same error [ ImportError: dlopen(/usr/local/lib/python2.7/site-packages/tensorflow/python/_pywrap_tensorflow.so, 10): Library not loaded: @rpath/libcudart.7.5.dylib ]  on my MacbookPro (OS X 10.11.6) with 
-- TensorFlow 0.10
-- Python 2.7.12

I installed CUDA 8.0.

Have you been able to make CUDA 8 and Tensor Flow work??

Thanks,
Atul
===============
Here are the results from deviceQuery:
===============
```
./deviceQuery Starting...

 CUDA Device Query (Runtime API) version (CUDART static linking)

Detected 1 CUDA Capable device(s)

Device 0: "GeForce GT 750M"
  CUDA Driver Version / Runtime Version          8.0 / 8.0
  CUDA Capability Major/Minor version number:    3.0
  Total amount of global memory:                 2048 MBytes (2147024896 bytes)
  ( 2) Multiprocessors, (192) CUDA Cores/MP:     384 CUDA Cores
  GPU Max Clock rate:                            926 MHz (0.93 GHz)
  Memory Clock rate:                             2508 Mhz
  Memory Bus Width:                              128-bit
  L2 Cache Size:                                 262144 bytes
  Maximum Texture Dimension Size (x,y,z)         1D=(65536), 2D=(65536, 65536), 3D=(4096, 4096, 4096)
  Maximum Layered 1D Texture Size, (num) layers  1D=(16384), 2048 layers
  Maximum Layered 2D Texture Size, (num) layers  2D=(16384, 16384), 2048 layers
  Total amount of constant memory:               65536 bytes
  Total amount of shared memory per block:       49152 bytes
  Total number of registers available per block: 65536
  Warp size:                                     32
  Maximum number of threads per multiprocessor:  2048
  Maximum number of threads per block:           1024
  Max dimension size of a thread block (x,y,z): (1024, 1024, 64)
  Max dimension size of a grid size    (x,y,z): (2147483647, 65535, 65535)
  Maximum memory pitch:                          2147483647 bytes
  Texture alignment:                             512 bytes
  Concurrent copy and kernel execution:          Yes with 1 copy engine(s)
  Run time limit on kernels:                     Yes
  Integrated GPU sharing Host Memory:            No
  Support host page-locked memory mapping:       Yes
  Alignment requirement for Surfaces:            Yes
  Device has ECC support:                        Disabled
  Device supports Unified Addressing (UVA):      Yes
  Device PCI Domain ID / Bus ID / location ID:   0 / 1 / 0
  Compute Mode:
     < Default (multiple host threads can use ::cudaSetDevice() with device simultaneously) >

deviceQuery, CUDA Driver = CUDART, CUDA Driver Version = 8.0, CUDA Runtime Version = 8.0, NumDevs = 1, Device0 = GeForce GT 750M
Result = PASS
```

**Comment by yaroslavvb** [comment]
@laventura 11rc0 and before are only for CUDA 7.5, you have to wait for later version or build from source if you want CUDA 8

**Comment by andrenatal** [comment]
Building from source, at this step:

`bazel build -c opt --config=cuda //tensorflow/tools/pip_package:build_pip_package`

I  get this error:

`ERROR: /Users/anatal/projects/mozilla/tensorflow/tensorflow/core/kernels/BUILD:1020:1: error while parsing .d file: /private/var/tmp/_bazel_anatal/7c0501261859d426c184c23a4c9e36fa/execroot/tensorflow/bazel-out/local_darwin-opt/bin/tensorflow/core/kernels/_objs/adjust_contrast_op_gpu/tensorflow/core/kernels/adjust_contrast_op_gpu.cu.pic.d (No such file or directory).
nvcc warning : option '--relaxed-constexpr' has been deprecated and replaced by option '--expt-relaxed-constexpr'.
nvcc fatal   : The version ('80000') of the host compiler ('Apple clang') is not supported
Target //tensorflow/tools/pip_package:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 262.184s, Critical Path: 250.97s`

**Comment by gunan** [comment]
That particular error looks like a mismatch between your XCode version and Cuda.
On ubuntu, I was able to get the source code to compile successfully with cuda8.

**Comment by yaroslavvb** [comment]
Googling for error suggests that you need xcode 7.2
