### ISSUE TITLE
ModelCheckpoint should have a way to delete non-best model checkpoints as it goes

### ISSUE THREAD

**Issue by jim-meyer** [tensorflow/tensorflow#30695]
**System information**
- TensorFlow version (you are using): 2.0.0b0
- Are you willing to contribute it (Yes/No): Yes

**Describe the feature and the current behavior/state.**
tensorflow.keras.callbacks.ModelCheckpoint should have an (optional) way to clean up non-best model checkpoints as it goes. This would help avoid disk consumption issues for larger models and other uses cases like doing a lot of training during hyperparameter searches.

**Will this change the current api? How?**
Yes. My proposal is to add a 'delete_previous_best_checkpoints' named argument to the constructor for tensorflow.keras.callbacks.ModelCheckpoint with the default set to False for backward compatibility. The docs would be something like this:
delete_previous_best_checkpoints: If True then the previous best checkpoint will be deleted after a new best checkpoint is saved. Only non-best checkpoints created by the current training session will be deleted. Resumed training from CheckpointA will not delete CheckpointA or any previous checkpoint.

**Who will benefit with this feature?**
Folks training large models in disk consumption conscious environments (think AWS budget). Or folks doing hyperparameter searches where it's easy to create hundreds of checkpoints quickly.

**Any Other info.**
I'm happy to submit a PR for this.

**Comment by eduardofv** [comment]
Hi @jim-meyer, how would it be different to set `save_best_only = True` in the current API?
```
keras.callbacks.ModelCheckpoint(filepath, monitor='val_loss', verbose=0, save_best_only=False, save_weights_only=False, mode='auto', period=1)
```

**Comment by jim-meyer** [comment]
Hi @eduardofv, The behavior I'm seeing is that `save_best_only=True`  doesn't do any deleting of previous "best" models when a new best one is found.
Example: I train a new model for 2 iterations. The first model will obviously be the best we've seen so `save_best_only` causes Model1.h5 to be saved. Next, model 2 is better than 1 so Model2.h5 gets saved. But model1.h5 does not get deleted due to `save_best_only`.
So after 2 epochs I end up with 2 models with `save_best_only=True`:
- Model1.h5
- Model2.h5

With my proposal only 1 model would exist after the second epoch since Model1.h5 would be deleted by the new `delete_previous_best_checkpoints=True` option:
- Model2.h5

Does that help explain it better? If so I'll add something to that effect to the docs in the PR.

**Comment by jvishnuvardhan** [comment]
@jim-meyer Please check the following example from this [source](https://machinelearningmastery.com/check-point-deep-learning-models-keras/) and let us know how your proposal is different from it. Thanks!

```
# Checkpoint the weights for best model on validation accuracy
from keras.models import Sequential
from keras.layers import Dense
from keras.callbacks import ModelCheckpoint
import matplotlib.pyplot as plt
import numpy
# fix random seed for reproducibility
seed = 7
numpy.random.seed(seed)
# load pima indians dataset
dataset = numpy.loadtxt("pima-indians-diabetes.csv", delimiter=",")
# split into input (X) and output (Y) variables
X = dataset[:,0:8]
Y = dataset[:,8]
# create model
model = Sequential()
model.add(Dense(12, input_dim=8, kernel_initializer='uniform', activation='relu'))
model.add(Dense(8, kernel_initializer='uniform', activation='relu'))
model.add(Dense(1, kernel_initializer='uniform', activation='sigmoid'))
# Compile model
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
# checkpoint
filepath="weights.best.hdf5"
checkpoint = ModelCheckpoint(filepath, monitor='val_acc', verbose=1, save_best_only=True, mode='max')
callbacks_list = [checkpoint]
# Fit the model
model.fit(X, Y, validation_split=0.33, epochs=150, batch_size=10, callbacks=callbacks_list, verbose=0)

```

**Comment by jim-meyer** [comment]
Thanks @jvishnuvardhan . After reading that article again I finally noticed this little blurb:
```
A simpler check-point strategy is to save the model weights to the same file, if and only if the validation accuracy improves.
This can be done easily using the same code from above and changing the output filename to be fixed (not include score or epoch information).
```

I had been using filepath='checkpoint-{epoch}.h5'. But now that I remove the {epoch} and am now using 'best-checkpoint.h5' I see that that essentially solves my use case.
I'll put together a PR that does just a minor documentation update to make this a bit more obvious for the next person.

**Comment by jvishnuvardhan** [comment]
@jim-meyer Sure. Go ahead and raise PR to improve documentation. I am closing the issue as it was resolved. Thanks!

**Comment by maxvfischer** [comment]
@jvishnuvardhan Wouldn't it still make sense to have a feature similar to what @jim-meyer is proposing? I'm currently in the same situation: I want previous "best" models to be overwritten by the new "best" model, but I still want to include what `epoch` and `val_loss` the model was generated at. To my understanding it's only possible to do either or? Either overwrite the previous best model and not having `epoch` etc in the name, or have `epoch`etc in the name, but then every new better model is saved.

**Comment by stefan-falk** [comment]
A very simple approach could be this:

```pyton
class KeepNBestCheckpoints(keras.callbacks.Callback):

    def __init__(self, checkpoints_dir, num_keep=5, find_checkpoints_fn=find_checkpoints):
        super().__init__()
        self.checkpoints_dir = checkpoints_dir
        self.num_keep = num_keep
        self.find_checkpoints = find_checkpoints_fn

    def on_test_end(self, logs=None):
        logger = tf.get_logger()
        if self.num_keep and self.num_keep > 0:
            checkpoints = self.find_checkpoints(self.checkpoints_dir, ascending=False)
            for checkpoint in checkpoints[self.num_keep:]:
                logger.debug(f'Removing checkpoint {checkpoint}')
                checkpoint_files = tf.io.gfile.glob(checkpoint + '*')
                for file in checkpoint_files:
                    logger.debug(f'Removing: {file}')
                    tf.io.gfile.remove(file)
```

Where `find_checkpoints()` could be a default implementation like this:

```python
def find_checkpoints(model_dir, ascending=True):
    """Get all checkpoints in descending order sorted by (epoch, step).
    The checkpoint names must follow the pattern ckpt-{epoch}-{step}.index.
    :param model_dir: The location of the model training.
    :param ascending: If True (default) checkpoints are sorted in ascending order (latest to oldest).
    """
    checkpoints = tf.io.gfile.glob(os.path.join(model_dir, 'ckpt-*.index'))
    checkpoints = map(lambda s: s.strip('.index'), checkpoints)
    by_step = list()
    for checkpoint in checkpoints:
        checkpoint_name = os.path.basename(checkpoint)
        _, epoch, step = checkpoint_name.split('-')
        by_step.append(((epoch, step), checkpoint))
    by_step = sorted(by_step, key=itemgetter(0))
    if not ascending:
        by_step = by_step[::-1]
    return list(map(itemgetter(1), by_step))
```

Depending on how you name your checkpoints.

**Comment by schustmi** [comment]
I wrote a [ModelCheckpoint subclass](https://github.com/schustmi/tf_utils/blob/915fe5e231ca302b28cd02dc8ac2e4c772a62e0b/tf_utils/callbacks.py#L34) with this functionality that does not require any custom function to find checkpoints if anyone is still interested in this.
