### ISSUE TITLE
.h5 to tflite conversion error

### ISSUE THREAD

**Issue by dr-rathod** [tensorflow/tensorflow#30690]
working on GOOGLE COLAB

tensorflow version 1.2

INPUT :- 
`from tensorflow.contrib import lite

converter = lite.TFLiteConverter.from_keras_model_file( 'model.h5' ) # Your model's name

model = converter.convert()

file = open( 'model.tflite' , 'wb' )
 
file.write( model )`

ERROR:-
`ImportError                               Traceback (most recent call last)
<ipython-input-1-e02e9998849c> in <module>()
      1 
----> 2 from tensorflow.contrib import lite
      3 converter = lite.TFLiteConverter.from_keras_model_file( 'model.h5' ) # Your model's name
      4 
      5 model = converter.convert()`

`ImportError: cannot import name 'lite'`

**Comment by dr-rathod** [comment]
AND BY THIS INPUT:-
`from  tensorflow.contrib.lite.python import convert_saved_model
convert_saved_model.tflite_from_saved_model(saved_model_dir="model.h5",output_file="/TF_Lite_Model")`

ERROR:-
`ModuleNotFoundError: No module named 'tensorflow.contrib.lite'`

**Comment by anush-o** [comment]
@dr-rathod ,
Is it possible for you to upgrade the TF version to 1.14 and check if the issue still persists. Thanks

**Comment by anush-o** [comment]
Closing due to lack of recent activity.Thanks!
