### ISSUE TITLE
Freeze_graph not supporting tf.control_dependencies

### ISSUE THREAD

**Issue by ghostplant** [tensorflow/tensorflow#30697]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): binary (pypi: tensorflow-gpu==1.14.0)
- TensorFlow version (use command below): 1.14.0
- Python version: 3.6
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: CUDA-10/CUDNN-7
- GPU model and memory: NVIDIA 1080

**Describe the current behavior**
This is the simple code I want to freeze, where `out` node is as the output node names:
```py
  print_op = tf.print(tf.ones([2, 2]))
  with tf.control_dependencies([print_op]):
    out = tf.zeros([3,])
```
By freezing the `out` node with `freeze_graph.freeze_graph(...)`, what I got from the protobuf only contains nodes like `StringFormat`, `PrintV2` and `Ones`. No else information to show there execution order. Seems like the execution order managed by the `tf.control_dependencies` is lost from the frozen graph.

**Code to reproduce the issue**

Freeze any large or small graph that contains using `tf.control_dependencies`, and check how it is described in the frozen protobuf data.

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.
