### ISSUE TITLE
build tensorflow failed with bazel on windows

### ISSUE THREAD

**Issue by cj741** [tensorflow/tensorflow#30701]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):Win7 X64
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):source
- TensorFlow version:2.0
- Python version:3.7
- Installed using virtualenv? pip? conda?:conda
- Bazel version (if compiling from source):0.25.1
- GCC/Compiler version (if compiling from source):no
- CUDA/cuDNN version:no
- GPU model and memory:no

**Describe the problem**
I try to build C++ lib and dll file with Bazel, as the following steps:
1. run "python configure.py", and set up options.
2.run "bazel build --config=opt //tensorflow/tools/lib_package:libtensorflow"
It throw errors:
```
"Loading:
Loading: 0 packages loaded
Loading: 0 packages loaded
INFO: An error occurred during the fetch of repository 'io_bazel_rules_docker'
INFO: Call stack for the definition of repository 'io_bazel_rules_docker':
 - C:/users/administrator/_bazel_administrator/zfk46uyn/external/bazel_toolchain
s/repositories/repositories.bzl:37:9
 - D:/tensorflow/tensorflow/WORKSPACE:29:1
ERROR: error loading package '': Encountered error while reading extension file
'repositories/repositories.bzl': no such package '@io_bazel_rules_docker//reposi
tories': Traceback (most recent call last):
        File "C:/users/administrator/_bazel_administrator/zfk46uyn/external/baze
l_tools/tools/build_defs/repo/git.bzl", line 234
                _clone_or_update(ctx)
        File "C:/users/administrator/_bazel_administrator/zfk46uyn/external/baze
l_tools/tools/build_defs/repo/git.bzl", line 74, in _clone_or_update
                fail(("error cloning %s:\n%s" % (ctx....)))
error cloning io_bazel_rules_docker:
+ cd C:/users/administrator/_bazel_administrator/zfk46uyn/external
+ rm -rf C:/users/administrator/_bazel_administrator/zfk46uyn/external/io_bazel_
rules_docker C:/users/administrator/_bazel_administrator/zfk46uyn/external/io_ba
zel_rules_docker"
```

Thanks for the help!

**Comment by ravikyram** [comment]
Just to verify did you get chance to follow instructions from [TensorFlow](https://www.tensorflow.org/install/source_windows) website .Please, let us know. Thanks!

**Comment by cj741** [comment]
Yes, I followed the instruction, and I found the solution here https://github.com/tensorflow/tensorflow/issues/28824,
but I got new problem as following:

Analyzing: target //tensorflow/tools/lib_package:libtensorflow (0 packages loade
d, 0 targets configured)
INFO: An error occurred during the fetch of repository 'protobuf_archive'
INFO: Call stack for the definition of repository 'protobuf_archive':
 - D:/tensorflow/tensorflow/tensorflow/workspace.bzl:382:5
 - D:/tensorflow/tensorflow/WORKSPACE:105:1

Do you have idea on it?
Thanks

**Comment by gunan** [comment]
I have seen similar issues these days if I did not have `msys` installed or the environment variable `BAZEL_SH` not set up correctly. Did you install bazel as described here and completed all the steps? https://docs.bazel.build/versions/master/install-windows.html

**Comment by cj741** [comment]
Thanks Gunan, the bazel is work well, I got some new errors like following:
Analyzing: target //tensorflow/tools/lib_package:libtensorflow (123 packages loa
ded, 5204 targets configured)
INFO: An error occurred during the fetch of repository 'eigen_archive'
INFO: Call stack for the definition of repository 'eigen_archive':
 - D:/tensorflow/tensorflow/tensorflow/workspace.bzl:148:5
 - D:/tensorflow/tensorflow/WORKSPACE:105:1
INFO: An error occurred during the fetch of repository 'gif_archive'
INFO: An error occurred during the fetch of repository 'lmdb'
INFO: An error occurred during the fetch of repository 'grpc'
INFO: An error occurred during the fetch of repository 'snappy'
INFO: An error occurred during the fetch of repository 'zlib_archive'
INFO: An error occurred during the fetch of repository 'curl'
INFO: Call stack for the definition of repository 'zlib_archive':
 - D:/tensorflow/tensorflow/tensorflow/workspace.bzl:568:5
 - D:/tensorflow/tensorflow/WORKSPACE:105:1
INFO: Call stack for the definition of repository 'snappy':
 - D:/tensorflow/tensorflow/tensorflow/workspace.bzl:590:5
 - D:/tensorflow/tensorflow/WORKSPACE:105:1
INFO: Call stack for the definition of repository 'grpc':
 - D:/tensorflow/tensorflow/tensorflow/workspace.bzl:487:5
 - D:/tensorflow/tensorflow/WORKSPACE:105:1
INFO: Call stack for the definition of repository 'lmdb':
 - D:/tensorflow/tensorflow/tensorflow/workspace.bzl:533:5
 - D:/tensorflow/tensorflow/WORKSPACE:105:1
INFO: An error occurred during the fetch of repository 'png_archive'
INFO: Call stack for the definition of repository 'gif_archive':
 - D:/tensorflow/tensorflow/tensorflow/workspace.bzl:265:5
 - D:/tensorflow/tensorflow/WORKSPACE:105:1
..............................
..............................

Bring trouble to you,
Thanks,

**Comment by cj741** [comment]
anyone can help~

**Comment by gunan** [comment]
```
INFO: An error occurred during the fetch of repository 'gif_archive'
INFO: An error occurred during the fetch of repository 'lmdb'
INFO: An error occurred during the fetch of repository 'grpc'
INFO: An error occurred during the fetch of repository 'snappy'
INFO: An error occurred during the fetch of repository 'zlib_archive'
INFO: An error occurred during the fetch of repository 'curl'
```
These errors point to issues downloading dependencies. Do you happen to be behind a firewall?

**Comment by cj741** [comment]
Thanks gunan, it could be the reason.
