### ISSUE TITLE
training become too slow with custom convolution

### ISSUE THREAD

**Issue by halbaqshi** [tensorflow/tensorflow#30700]
I`m working on:
Windows 10,
64 bit,
Anaconda3 version 5.3.0 
python 3.6.8,
tensorflow version 1.10.0

I built custom convolution with tf.nn.conv2d and it is take long tine building the model, and after building the model and it is take long time around 2 or 3 days for training, and before the training the prepare, the terminal is exit

complete code at code2.txt file in the attachment

for others files try to use any a group of audio files to run the code

[code2.txt](https://github.com/tensorflow/tensorflow/files/3391247/code2.txt)

**Comment by halbaqshi** [comment]
or download and use the speech commend data-set from the following link::

https://ai.googleblog.com/2017/08/launching-speech-commands-dataset.html

**Comment by halbaqshi** [comment]
Screenshot of final output:

![image](https://user-images.githubusercontent.com/52009924/61204770-ccd22300-a6f6-11e9-901f-41226d1c23a8.png)

**Comment by ymodak** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow-tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.
