### ISSUE TITLE
./bazel-bin/tensorflow/tools/pip_package/build_pip_package: No such file or directory

### ISSUE THREAD

**Issue by Davari393** [tensorflow/tensorflow#30705]
Hi guys.
i built Bazel from scratch from here:
https://docs.bazel.build/versions/master/install-compile-source.html

Now i want to run 
./bazel-bin/tensorflow/tools/pip_package/build_pip_package /tmp/tensorflow_pkg

and then lite my model.but when i run it this error appears:
./bazel-bin/tensorflow/tools/pip_package/build_pip_package: No such file or directory

but i have bazel-bin

Can any one help me please?

**Comment by anush-o** [comment]
@Davari393,
Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version.Thanks!

**Comment by anush-o** [comment]
Closing due to lack of recent activity.Thanks!
