### ISSUE TITLE
Running inference on Coral TPU stick results in Segmentation fault

### ISSUE THREAD

**Issue by DocDriven** [tensorflow/tensorflow#30714]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- TensorFlow installed from (source or binary): Docker image tensorflow/tensorflow:gpu-latest
- TensorFlow version (use command below): 1.14.0
- Python version: 2.7.15+
- CUDA/cuDNN version: 10.1
- GPU model and memory: GeForce RTX 2080 Ti

I want to deploy a simple tflite model on a machine with an ARM processor and the Coral TPU Stick, but run into problems and inconsistencies during the process. Due to the procedure being quite long, I decided to post the whole process, so you track every step that I made. Overall goal is to fit a function of the form `f(x) = 2x - 1`.

**1. Train a model with quantization aware training**

```
import tensorflow as tf
from tensorflow import keras
import numpy as np

print(tf.__version__)

train_input = np.array([ -1.0, 0.0, 1.0, 2.0, 3.0, 4.0], dtype=float)
train_truth = np.array([ -3.0, -1.0, 1.0, 3.0, 5.0, 7.0], dtype=float)

def build_keras_model():
	return keras.models.Sequential([
		keras.layers.Dense(units=1, input_shape=[1]),
	])

### train the model
train_graph = tf.Graph()
train_sess = tf.Session(graph=train_graph)

keras.backend.set_session(train_sess)

with train_graph.as_default():
	keras.backend.set_learning_phase(1)
	train_model = build_keras_model()

	tf.contrib.quantize.create_training_graph(input_graph=train_graph, quant_delay=100)
	train_sess.run(tf.global_variables_initializer())

	train_model.compile(
		optimizer='sgd',
		loss='mean_squared_error'
	)
	train_model.fit(train_input, train_truth, epochs=250)

	saver = tf.train.Saver()
	saver.save(train_sess, 'linear.ckpt')
```
This produces the checkpoint. Next, I created an eval graph and loaded the checkpoint.

**2. Create the eval graph and freeze the model**

```
import tensorflow as tf
from tensorflow import keras
import numpy as np

def build_keras_model():
	return keras.models.Sequential([
		keras.layers.Dense(units=1, input_shape=[1]),
	])

# eval
eval_graph = tf.Graph()
eval_sess = tf.Session(graph=eval_graph)

keras.backend.set_session(eval_sess)

with eval_graph.as_default():
	keras.backend.set_learning_phase(0)
	eval_model = build_keras_model()

	tf.contrib.quantize.create_eval_graph(input_graph=eval_graph)

	eval_graph_def = eval_graph.as_graph_def()
	saver = tf.train.Saver()
	saver.restore(eval_sess, 'linear.ckpt')

	frozen_graph_def = tf.graph_util.convert_variables_to_constants(
		eval_sess,
		eval_graph_def,
		[eval_model.output.op.name]
	)

	with open('frozen_model.pb', 'wb') as f:
		f.write(frozen_graph_def.SerializeToString())
```
I resorted to use the python API for freezing it because the command line tool throws errors. Executing this, I get a protocol buffer called `frozen_model.pb`.

**3. Convert the protocol buffer into a tflite model**
```
tflite_convert \
--output_file=model.tflite \
--graph_def_file=frozen_model.pb \
--inference_type=QUANTIZED_UINT8 \
--input_arrays=dense_input \
--output_arrays=dense/BiasAdd \
--mean_values=0 \
--std_dev_values=255 \
--default_ranges_min=-128 \
--default_ranges_max=127
```
Resorting the the command line tool, this produces a tflite model. Although I am not sure how to determine good values for mean, std_dev and the default ranges, the conversion seems to work. I end up with a model, that I was able to load and interpret with the Python API. Apparently, everything has worked as expected.

**4. Use the edgetpu_compiler to create a tflite file that utilizes the TPU stick**

`edgetpu_compiler model.tflite`

This command creates a file called `model_edgetpu.tflite`. No errors, I even get a log file stating that everything worked as expected.

**5. Transferring everything to the ARM machine, running the interpreter there**

I tried to do inference on the target system, using the following C++ snippet to create an interpreter as described on the Coral site.

```
#include <stdio.h>
#include "tensorflow/lite/interpreter.h"
#include "tensorflow/lite/kernels/register.h"
#include "tensorflow/lite/model.h"
#include "tensorflow/lite/tools/gen_op_registration.h"
#include "edgetpu.h"

int main(){

    // load model
    std::unique_ptr<tflite::FlatBufferModel> model = tflite::FlatBufferModel::BuildFromFile("model_edgetpu.tflite");

    if(!model){
        printf("Failed to mmap model\n");
        exit(0);
    }

    // create TPU context handle
    edgetpu::EdgeTpuContext* edgetpu_context = edgetpu::EdgeTpuManager::GetSingleton()->NewEdgeTpuContext().release();

    tflite::ops::builtin::BuiltinOpResolver resolver;
    resolver.AddCustom(edgetpu::kCustomOp, edgetpu::RegisterCustomOp());

    // Build the interpreter
    std::unique_ptr<tflite::Interpreter> interpreter;

    if (tflite::InterpreterBuilder(*model, resolver)(&interpreter) != kTfLiteOk){
            printf("Failed to build interpreter.");
    }

    interpreter->SetExternalContext(kTfLiteEdgeTpuContext, edgetpu_context);
    interpreter->SetNumThreads(1);

    // Allocate memory
    if(interpreter->AllocateTensors() != kTfLiteOk){
            printf("Failed to allocate tensors.");
    }

    // Prepare input(s)
    float a = 0.0;
    interpreter->typed_input_tensor<float>(0)[0] = a;

    // Invoke the interpreter
    interpreter->Invoke();

    // Get output(s)
    float* output = interpreter->typed_output_tensor<float>(0);

    // Should print -1.0
    printf("Result is: %f\n", *output);

    return 0;
}
```

After compiling my executable without any errors, I get an Segmentation fault:
```
root@localhost:/demo# ./tpu_demo 
INFO: Initialized TensorFlow Lite runtime.
Segmentation fault
```

Until this point, no errors have occured during the whole process. So I guess something went wrong during the creation of the tflite model. I also noticed that the non-edge_compiler version of the the tflite model also results in a Segmentation fault on the ARM system, even though I was able to use with the Python API.

Any help is appreciated! Thanks.

**Comment by DocDriven** [comment]
Update: the problem seems to be the conversion process from the frozen model to tflite model. For better control, I switched to the Python API. Using the setup with inference type FLOAT, the model is convertible and deployable.

My code for conversion:

```
import tensorflow as tf

graph_def_file = 'frozen_model.pb'
inputs = ["dense_input"]
outputs = ["dense/BiasAdd"]

sess = tf.Session()

converter = tf.lite.TFLiteConverter.from_frozen_graph(graph_def_file, inputs, outputs)
converter.inference_type = tf.lite.constants.FLOAT
input_arrays = converter.get_input_arrays()

converter.quantized_input_stats = {input_arrays[0]: (0., 1.)} # mean, std_dev

tflite_model = converter.convert()

open('py_converted_model.tflite', 'wb').write(tflite_model)
```

It seems the frozen graph is alright, and something goes wrong during the conversion with quantization enabled. Consider the code which produces a tflite model, that is convertible via the edge_compiler, but fails when loaded.

```
import tensorflow as tf

graph_def_file = 'frozen_model.pb'
inputs = ["dense_input"]
outputs = ["dense/BiasAdd"]

sess = tf.Session()

converter = tf.lite.TFLiteConverter.from_frozen_graph(graph_def_file, inputs, outputs)
converter.inference_type = tf.lite.constants.QUANTIZED_UINT8
input_arrays = converter.get_input_arrays()

converter.allow_custom_ops = True
converter.quantized_input_stats = {input_arrays[0]: (0., 1.)} # mean, std_dev
converter.default_ranges_stats = (-128, 127)

tflite_model = converter.convert()

open('py_converted_model.tflite', 'wb').write(tflite_model)
```

Loading the model with the C++ API, I get an error with a little more output than in the original question:


```
root@localhost:/demo# ./tpu_demo py_converted_model_edgetpu.tflite 
INFO: Initialized TensorFlow Lite runtime.
ERROR: Failed to prepare for TPU. generic::failed_precondition: Custom op already assigned to a different TPU.
ERROR: Node number 0 (edgetpu-custom-op) failed to prepare.

Segmentation fault
```

**Comment by DocDriven** [comment]
@liyunlu0618 
Could you or somebody else confirm the correctness of this workflow? If it is a tensorflow issue, I could stop debugging my code and actually help figuring out the real problem.

Thanks!

**Comment by DocDriven** [comment]
I have tried to reproduce this error with tf 2.0.0-beta1. Unfortunately, it is indeed reproducable, speaking that I can create a model, load and do inference with it via the Python interpreter API. But as soon as I utilize the edgetpu_compiler to create a model for an ARM platform, I get a Seg Fault (again). Here the code to reproduce this:

```
import tensorflow as tf
from tensorflow import keras
import numpy as np

train_x = np.array([ [-4.0], [-3.0], [-2.0], [-1.0], [0.0], [1.0], [2.0], [3.0], [4.0], [5.0]], dtype=np.float32)
train_y = np.array([ -9.0, -7.0, -5.0, -3.0, -1.0, 1.0, 3.0, 5.0, 7.0, 9.0], dtype=np.float32)

test_x = np.array([[4.5]], dtype=np.float32)

def build_model():

	model = keras.models.Sequential()
	model.add(keras.layers.Dense(1, input_shape=(1,)))

	return model

###
### TRAINING
###

model = build_model()
model.compile(optimizer='sgd',
		  	  loss='mean_squared_error',
)

keras_file = 'linear.h5'
model.fit(train_x, train_y, epochs=150)
keras.models.save_model(model, keras_file)

###
### CONVERSION
###

if (tf.__version__ == '2.0.0-beta1'):
	converter = tf.compat.v1.lite.TFLiteConverter.from_keras_model_file(keras_file)
else:
	raise NotImplementedError('Converter not implemented for this tf version')

def representative_dataset_gen():
	for i in range(len(train_x)):
		yield [train_x[i:i+1]]

converter.representative_dataset = representative_dataset_gen
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
converter.inference_input_type = tf.uint8
converter.inference_output_type = tf.uint8
converter.optimizations = [tf.lite.Optimize.DEFAULT]

tflite_file_name = 'converted_linearmodel_tpu_' + str(tf.__version__) + '.tflite'

tflite_model = converter.convert()
open(tflite_file_name, 'wb').write(tflite_model)

###
### INFERENCE FOR TESTING
###

interpreter = tf.lite.Interpreter(model_path=tflite_file_name)
interpreter.allocate_tensors()

input_detail = interpreter.get_input_details()[0]
output_detail = interpreter.get_output_details()[0]

def quantize(real_value):
	std, mean = input_detail['quantization']
	return (real_value / std + mean).astype(np.uint8)

def dequantize(quant_value):
	std, mean = output_detail['quantization']
	return (std * (quant_value - mean)).astype(np.float32)

sample_input = quantize(test_x[0]).reshape(input_detail['shape'])

interpreter.set_tensor(input_detail['index'], sample_input)
interpreter.invoke()

pred_original_model = model.predict(test_x[0])
pred_quantized_model = interpreter.get_tensor(output_detail['index'])

print("Pred Original : ", pred_original_model)
print("Pred Quantized : ", dequantize(pred_quantized_model[0].reshape(output_detail['shape'])))
```

The output of this script on my machine is:
```
INFO: Initialized TensorFlow Lite runtime.
Pred Original :  [[8.042535]]
Pred Quantized :  [[8.030863]]
```
So obviously, the model has been quantized properly and gives reasonable results. Converting this model, I get the following output:
```
user@localhost:~/tf/tensorflow2_beta$ edgetpu_compiler converted_linearmodel_tpu_2.0.0-beta1.tflite 
Edge TPU Compiler version 1.0.249710469
INFO: Initialized TensorFlow Lite runtime.

Model compiled successfully in 6 ms.

Input model: converted_linearmodel_tpu_2.0.0-beta1.tflite
Input size: 1.08KiB
Output model: converted_linearmodel_tpu_2.0.0-beta1_edgetpu.tflite
Output size: 32.52KiB
On-chip memory available for caching model parameters: 8.02MiB
On-chip memory used for caching model parameters: 512.00B
Off-chip memory used for streaming uncached model parameters: 0.00B
Number of Edge TPU subgraphs: 1
Total number of operations: 3
Operation log: converted_linearmodel_tpu_2.0.0-beta1_edgetpu.log
See the operation log file for individual operation details.
```
With the conversion being successful, it seems the problems lies within the interpreter written in C++ (as described under 5. in my original question). When invoked, the executable produces the error:

```
root@localhost:/demo# ./tpu_demo converted_linearmodel_tpu_2.0.0-beta1_edgetpu.tflite 
INFO: Initialized TensorFlow Lite runtime.
ERROR: Failed to prepare for TPU. generic::failed_precondition: Custom op already assigned to a different TPU.
ERROR: Node number 0 (edgetpu-custom-op) failed to prepare.

Segmentation fault
```
Can you guys provide support what is going wrong here? Thanks!

**Comment by DocDriven** [comment]
The problem seems to be the function that allocates memory for the tensors. The function call 

`interpreter->AllocateTensors()`

returns 1, e.g. an error. Upon looking at the file `tensorflow/tensorflow/lite/interpreter.cc` the error originates from the primary_subgraph(), but I wasn't able to figure out what causes the Seg Fault:

```
TfLiteStatus Interpreter::AllocateTensors() {
  return primary_subgraph().AllocateTensors();
}
```

**Comment by vibhatha** [comment]
> I have tried to reproduce this error with tf 2.0.0-beta1. Unfortunately, it is indeed reproducable, speaking that I can create a model, load and do inference with it via the Python interpreter API. But as soon as I utilize the edgetpu_compiler to create a model for an ARM platform, I get a Seg Fault (again). Here the code to reproduce this:
> 
> ```
> import tensorflow as tf
> from tensorflow import keras
> import numpy as np
> 
> train_x = np.array([ [-4.0], [-3.0], [-2.0], [-1.0], [0.0], [1.0], [2.0], [3.0], [4.0], [5.0]], dtype=np.float32)
> train_y = np.array([ -9.0, -7.0, -5.0, -3.0, -1.0, 1.0, 3.0, 5.0, 7.0, 9.0], dtype=np.float32)
> 
> test_x = np.array([[4.5]], dtype=np.float32)
> 
> def build_model():
> 
> 	model = keras.models.Sequential()
> 	model.add(keras.layers.Dense(1, input_shape=(1,)))
> 
> 	return model
> 
> ###
> ### TRAINING
> ###
> 
> model = build_model()
> model.compile(optimizer='sgd',
> 		  	  loss='mean_squared_error',
> )
> 
> keras_file = 'linear.h5'
> model.fit(train_x, train_y, epochs=150)
> keras.models.save_model(model, keras_file)
> 
> ###
> ### CONVERSION
> ###
> 
> if (tf.__version__ == '2.0.0-beta1'):
> 	converter = tf.compat.v1.lite.TFLiteConverter.from_keras_model_file(keras_file)
> else:
> 	raise NotImplementedError('Converter not implemented for this tf version')
> 
> def representative_dataset_gen():
> 	for i in range(len(train_x)):
> 		yield [train_x[i:i+1]]
> 
> converter.representative_dataset = representative_dataset_gen
> converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
> converter.inference_input_type = tf.uint8
> converter.inference_output_type = tf.uint8
> converter.optimizations = [tf.lite.Optimize.DEFAULT]
> 
> tflite_file_name = 'converted_linearmodel_tpu_' + str(tf.__version__) + '.tflite'
> 
> tflite_model = converter.convert()
> open(tflite_file_name, 'wb').write(tflite_model)
> 
> ###
> ### INFERENCE FOR TESTING
> ###
> 
> interpreter = tf.lite.Interpreter(model_path=tflite_file_name)
> interpreter.allocate_tensors()
> 
> input_detail = interpreter.get_input_details()[0]
> output_detail = interpreter.get_output_details()[0]
> 
> def quantize(real_value):
> 	std, mean = input_detail['quantization']
> 	return (real_value / std + mean).astype(np.uint8)
> 
> def dequantize(quant_value):
> 	std, mean = output_detail['quantization']
> 	return (std * (quant_value - mean)).astype(np.float32)
> 
> sample_input = quantize(test_x[0]).reshape(input_detail['shape'])
> 
> interpreter.set_tensor(input_detail['index'], sample_input)
> interpreter.invoke()
> 
> pred_original_model = model.predict(test_x[0])
> pred_quantized_model = interpreter.get_tensor(output_detail['index'])
> 
> print("Pred Original : ", pred_original_model)
> print("Pred Quantized : ", dequantize(pred_quantized_model[0].reshape(output_detail['shape'])))
> ```
> 
> The output of this script on my machine is:
> 
> ```
> INFO: Initialized TensorFlow Lite runtime.
> Pred Original :  [[8.042535]]
> Pred Quantized :  [[8.030863]]
> ```
> 
> So obviously, the model has been quantized properly and gives reasonable results. Converting this model, I get the following output:
> 
> ```
> user@localhost:~/tf/tensorflow2_beta$ edgetpu_compiler converted_linearmodel_tpu_2.0.0-beta1.tflite 
> Edge TPU Compiler version 1.0.249710469
> INFO: Initialized TensorFlow Lite runtime.
> 
> Model compiled successfully in 6 ms.
> 
> Input model: converted_linearmodel_tpu_2.0.0-beta1.tflite
> Input size: 1.08KiB
> Output model: converted_linearmodel_tpu_2.0.0-beta1_edgetpu.tflite
> Output size: 32.52KiB
> On-chip memory available for caching model parameters: 8.02MiB
> On-chip memory used for caching model parameters: 512.00B
> Off-chip memory used for streaming uncached model parameters: 0.00B
> Number of Edge TPU subgraphs: 1
> Total number of operations: 3
> Operation log: converted_linearmodel_tpu_2.0.0-beta1_edgetpu.log
> See the operation log file for individual operation details.
> ```
> 
> With the conversion being successful, it seems the problems lies within the interpreter written in C++ (as described under 5. in my original question). When invoked, the executable produces the error:
> 
> ```
> root@localhost:/demo# ./tpu_demo converted_linearmodel_tpu_2.0.0-beta1_edgetpu.tflite 
> INFO: Initialized TensorFlow Lite runtime.
> ERROR: Failed to prepare for TPU. generic::failed_precondition: Custom op already assigned to a different TPU.
> ERROR: Node number 0 (edgetpu-custom-op) failed to prepare.
> 
> Segmentation fault
> ```
> 
> Can you guys provide support what is going wrong here? Thanks!

Can you provide the log file after running edgetpu_compiler? 
And check how much is TPU compatible? It will give a detailed report. 

Note: There is a *.log file created with partials of your tflite model name added with suffix edgetpu*

ex : <tflite_model_name>_edgetpu.log

**Comment by DocDriven** [comment]
@vibhatha 
Sure, take a look:

```
Edge TPU Compiler version 1.0.249710469
Input: converted_linearmodel_tpu_2.0.0-beta1.tflite
Output: converted_linearmodel_tpu_2.0.0-beta1_edgetpu.tflite

Operator                       Count      Status

FULLY_CONNECTED                1          Mapped to Edge TPU
QUANTIZE                       2          Mapped to Edge TPU
```
Thanks!

**Comment by vibhatha** [comment]
It seems. Everything is good. 

Can u load the tflite model to the interpreter and check what is the expected input shape?
And make sure what you try to infer (input for inference) has the same shape?

**Comment by DocDriven** [comment]
@vibhatha 
I did not find any possibility to inspect my model. What I can show you is the point, where my exe dies:

```
#include <stdio.h>
#include "tensorflow/lite/interpreter.h"
#include "tensorflow/lite/kernels/register.h"
#include "tensorflow/lite/model.h"
#include "tensorflow/lite/tools/gen_op_registration.h"
#include "edgetpu.h"

int main(){

    // load model
    std::unique_ptr<tflite::FlatBufferModel> model = tflite::FlatBufferModel::BuildFromFile("model_edgetpu.tflite");

    if(!model){
        printf("Failed to mmap model\n");
        exit(0);
    }

    // create TPU context handle
    edgetpu::EdgeTpuContext* edgetpu_context = edgetpu::EdgeTpuManager::GetSingleton()->NewEdgeTpuContext().release();

    tflite::ops::builtin::BuiltinOpResolver resolver;
    resolver.AddCustom(edgetpu::kCustomOp, edgetpu::RegisterCustomOp());

    // Build the interpreter
    std::unique_ptr<tflite::Interpreter> interpreter;

    if (tflite::InterpreterBuilder(*model, resolver)(&interpreter) != kTfLiteOk){
            printf("Failed to build interpreter.");
    }

    interpreter->SetExternalContext(kTfLiteEdgeTpuContext, edgetpu_context);
    interpreter->SetNumThreads(1);

    // ########### MALLOC FAILS AND RETURNS 1 ############
    // Allocate memory
    if(interpreter->AllocateTensors() != kTfLiteOk){
            printf("Failed to allocate tensors.");
    }
    // ###################################################

    // Prepare input(s)
    float a = 0.0;

    // ################ THIS LINE CAUSES THE SEG FAULT ###################
    interpreter->typed_input_tensor<float>(0)[0] = a;
    // ###################################################################

    // Invoke the interpreter
    interpreter->Invoke();

    // Get output(s)
    float* output = interpreter->typed_output_tensor<float>(0);

    // Should print -1.0
    printf("Result is: %f\n", *output);

    return 0;
}
```
I guess that the second line tries to write to a place that could not be allocated beforehand.

**Comment by vibhatha** [comment]
`
tflite_fname = "path_to_tflite_model"
interpreter = tf.lite.Interpreter(model_path=tflite_fname)
interpreter.allocate_tensors()

input_detail = interpreter.get_input_details()[0]
output_detail = interpreter.get_output_details()[0]

print("Input Details : ", input_detail)
 print("Output Details : ", output_detail)

def quantize(real_value):
      std, mean = input_detail['quantization']
      return (real_value / std + mean).astype(np.uint8)

        `

Check these details and see if your input array has the right shape?

**Comment by DocDriven** [comment]
@vibhatha 
It seems to have the correct shape. I decided to inspect the tflite models with the tensorflow visualize.py script. It turns out that by setting `converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]`, no further conversion with the edgetpu_compiler seems to be needed. To my knowledge, this is NOT mentioned anywhere.

Therefore, I went the original tflite file. Here, `AllocateTensors()` does indeed return successfully, but as soon as I try to set the inputs, I get the Seg Fault again.

To make it easier for you to verify this, I have uploaded the html file of my tflite model on my repo ([check it here](https://github.com/DocDriven/experimental)). Also, you can find the model itself there.

I suspect I am doing something wrong when trying to set the inputs with the C++ API. After understanding what quantized models require, I changed the original

```
float a = 10.0;
interpreter->typed_input_tensor<float>(0)[0] = a;
```

to 

```
uint8_t b = 120;
interpreter->typed_input_tensor<uint8_t>(4)[0] = b;
```
Unfortunately, I still get the error. Do you have an example on how to do this correctly?

**Comment by DocDriven** [comment]
@vibhatha 
I was finally able to track down the cause of the Seg Faults. For some odd reason, `typed_output_tensor` and `typed_input_tensor` members do NOT work. They did however, when not using the TPU. 

Instead, simply use `typed_tensor` for setting the inputs and getting the outputs.

One last issue remains, however: I have to manually quantize and dequantize inputs and outputs. In Python, it is easy to retrieve std and mean. But is there a similar option in the C++ API?

Anyway, thank you for helping me greatly!

**Comment by vibhatha** [comment]
@DocDriven 
`            test = xtest[i] # from your testing dataset
            test_label = ytest[i] # from your testing dataset
            sample_input = quantize(test).reshape(input_detail['shape'])
            interpreter.set_tensor(input_detail['index'], sample_input)
            interpreter.invoke()
`           
You need to call corresponding C++ endpoints. 

Are you doing it like this?

**Comment by DocDriven** [comment]
@vibhatha
I was finally able to track down the cause of the Seg Faults. For some odd reason, typed_output_tensor and typed_input_tensor members do NOT work. They did however, when not using the TPU.

Instead, simply use typed_tensor for setting the inputs and getting the outputs.

One last issue remains, however: I have to manually quantize and dequantize inputs and outputs. In Python, it is easy to retrieve std and mean. But is there a similar option in the C++ API?

Anyway, thank you for helping me greatly!

**Comment by vibhatha** [comment]
@DocDriven 

It should be something similar. C++ may take a few more lines. But I think it won't be an issue. 
Glad it works now.

**Comment by tawnkramer** [comment]
this example was helpful for me. 
```
converter.inference_input_type = tf.uint8
converter.inference_output_type = tf.uint8
```
was missing from this discussion:
https://www.tensorflow.org/lite/performance/post_training_quantization#full_integer_quantization_of_weights_and_activations

without these two lines, the tflite model will convert and write. But edgetpu_compile will segfault with no information.

**Comment by karimnosseir** [comment]
@DocDriven Are you still facing issues.
Can you please provide an update ?

Thanks

**Comment by DocDriven** [comment]
@karimnosseir 
I have fixed this for my current model. As mentioned before, the problem was the C++ API. I had to use `typed_tensor` for inputs and outputs, otherwise it doesn't work. 

I will close this now as my problem was resolved, but it might be a good idea to mention this somewhere in the official documentation in the troubleshooting section.
