### ISSUE TITLE
Provide Raspberry Pi #aarch64 cross-compile instructions

### ISSUE THREAD

**Issue by marianopeck** [tensorflow/tensorflow#30716]
**System information**
- TensorFlow version (you are using): 1.13.1
- Are you willing to contribute it (Yes/No): yes, at least as a tester

**Describe the feature and the current behavior/state.**

There is no pre-build binary for Raspberry Pi / ARM and the instructions to build from scratch [here](https://www.tensorflow.org/install/source_rpi#build_from_source). However, there is nothing for any kind of SBC (like Raspberry Pi, ODroid, Pine64, etc) with a aarch64 architecture. 

I cannot use the Python wheel. I need the C library to bind to a different language. 

**Will this change the current api? How?**

No. 

**Who will benefit with this feature?**

Anyone using a SBC with a aarch64 OS.

**Comment by eduardofv** [comment]
Haven't tried this myself, but you can [find here](https://www.tensorflow.org/install/pip) how to install using pip directly on the Raspberry Pi

**Comment by marianopeck** [comment]
That would only work for installing the Python wheel. I need the C library to bind via FFI to other languages (like Go, Rust, etc)

**Comment by freedomtan** [comment]
Not sure about 1.13.1, For 1.14 or master branch, Something like 
```
bazel --host_jvm_args=-Xms128m --host_jvm_args=-Xmx2048m \
build --config opt --local_resources 1024,1,1 \
tensorflow/tools/lib_package:libtensorflow
```
should just work. I think I upstreamed necessary patches for
```
bazel --host_jvm_args=-Xms128m --host_jvm_args=-Xmx2048m \
build --config opt --local_resources 1024,1,1 \
tensorflow/tools/pip_package:build_pip_package
```

Raspbian 32-bit is a bit complicated, because for RPI 3, an AAarch64 platform, it runs aarch32 (armv7-a) kernel,  armv6 user-level binaries, and compilers/toolchains configured to armv6.

**Comment by marianopeck** [comment]
Hi @freedomtan 
Thanks for your response. But there is something I am not sure I understand. The link I pasted above (in my original post) is a way for *cross compiling* for Raspberry Pi. Doing something as simple as:

          tensorflow/tools/ci_build/ci_build.sh PI \
          tensorflow/tools/ci_build/pi/build_raspberry_pi.sh

If you see [here](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/ci_build/pi/build_raspberry_pi.sh) you can see all the magic. Cross compiling is much easier and faster than compiling on the Pi. 

I have many images running 64 bits OS on a Pi 3 and 4 (Armiban, Ubuntu Server 18.04, etc)... In addition, an aarch64 build would also help other similar SBC like Pine64, Odriod etc..

What I was proposing is a similar `build_raspberry_pi.sh` but that would allow me to cross-compile for aarch64. 

Thoughts?

**Comment by freedomtan** [comment]
Yes, cross-compiling usually is much faster, esp. for a fresh build. Easier, I don't think so. As I said, the environments before RPi 4 is quite complex.

**Comment by marianopeck** [comment]
Thanks @freedomtan for all your help.
I finally took the time to [write down everything I found during my attempt to get TensorFlow C library compiled for Raspberry Pi](https://dev.to/martinezpeck/challenge-accepted-build-tensorflow-c-binding-for-raspberry-pi-in-2019-4f89). In that tutorial, I point back to this issue in case any progress is done.
Thank you

**Comment by lgeiger** [comment]
I added an AArch64 toolchain to bazel in #38399 which should make cross-compiling a lot easier. It would be great if the PR could get a review.

**Comment by terryheo** [comment]
There are commands to build Python PIP wheel for aarch64.
https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/tools/pip_package

**Comment by terryheo** [comment]
Oh we need a guide to build full Tensorflow package. Let me check it.

**Comment by terryheo** [comment]
You can build TF Python wheel for aarch64.
https://www.tensorflow.org/install/source_rpi#python-3.8-64bit

**Comment by Yasin40** [comment]
> Hi @freedomtan
> Thanks for your response. But there is something I am not sure I understand. The link I pasted above (in my original post) is a way for _cross compiling_ for Raspberry Pi. Doing something as simple as:
> 
> ```
>       tensorflow/tools/ci_build/ci_build.sh PI \
>       tensorflow/tools/ci_build/pi/build_raspberry_pi.sh
> ```
> 
> If you see [here](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/ci_build/pi/build_raspberry_pi.sh) you can see all the magic. Cross compiling is much easier and faster than compiling on the Pi.
> 
> I have many images running 64 bits OS on a Pi 3 and 4 (Armiban, Ubuntu Server 18.04, etc)... In addition, an aarch64 build would also help other similar SBC like Pine64, Odriod etc..
> 
> What I was proposing is a similar `build_raspberry_pi.sh` but that would allow me to cross-compile for aarch64.
> 
> Thoughts?

How can i cross compile TF for ODROID? This script work for odroid xu4?
