### ISSUE TITLE
Low GPU usage of RNN layers under MirroredStrategy

### ISSUE THREAD

**Issue by guillaumekln** [tensorflow/tensorflow#30715]
**System information**
- Have I written custom code: Yes
- OS Platform and Distribution: Ubuntu 14.04
- TensorFlow installed from: binary
- TensorFlow version: `2.0.0b1`
- Python version: 3.6.8
- CUDA/cuDNN version: 10.0 / 
- GPU model and memory: TITAN X

**Describe the current behavior**

RNN layers have poor performance and low GPU usage when used with `MirroredStrategy`. By monitoring `nvidia-smi`, part of the execution seems to run sequentially on each GPU.

**Describe the expected behavior**

With `MirroredStrategy`, the model is expected to be run in parallel.

**Code to reproduce the issue**

Consider the dummy training code below. It generates examples with random shapes and apply a stack of `LSTMCell` on batches of sequences on 3 GPUs. If you replace the RNN layer by e.g. a stack of Dense layers, the parallelism is visibly improved.

```python
import tensorflow as tf

class MyModel(tf.keras.layers.Layer):

    def __init__(self):
        super(MyModel, self).__init__()
        cell = tf.keras.layers.StackedRNNCells(
            [tf.keras.layers.LSTMCell(512) for _ in range(12)])
        self.rnn = tf.keras.layers.RNN(cell)

    def call(self, inputs):
        return self.rnn(inputs)

dataset = tf.data.Dataset.from_tensor_slices(
    tf.random.uniform([10000], minval=1, maxval=80, dtype=tf.int32))
dataset = dataset.shuffle(10000)
dataset = dataset.map(lambda t: tf.zeros([t, 512]))
dataset = dataset.padded_batch(
    64, padded_shapes=tf.compat.v1.data.get_output_shapes(dataset))
dataset = dataset.repeat()
dataset = dataset.prefetch(1)

devices = ["/gpu:0", "/gpu:1", "/gpu:2"]
strategy = tf.distribute.MirroredStrategy(devices=devices)

with strategy.scope():
    dataset = strategy.experimental_distribute_dataset(dataset)
    model = MyModel()
    optimizer = tf.keras.optimizers.Adam()

def step(inputs):
    outputs = model(inputs)
    loss = tf.keras.losses.MeanSquaredError(reduction=tf.keras.losses.Reduction.SUM)(
        tf.zeros_like(outputs), outputs)
    variables = model.trainable_variables
    gradients = optimizer.get_gradients(loss, variables)
    optimizer.apply_gradients(zip(gradients, variables))
    return loss

@tf.function
def train():
    with strategy.scope():
        for inputs in dataset:
            loss = strategy.experimental_run_v2(step, args=(inputs,))

train()
```

cc @jkamalu.

**Comment by dsgupta** [comment]
I am facing the same problem using LSTM layers in a custom subclassed Keras model.

**Comment by yuefengz** [comment]
Could you try with latest nightly to see whether the problem is still there?

**Comment by guillaumekln** [comment]
I tested `tf-nightly-gpu-2.0-preview==2.0.0.dev20190910` and it's not that much better. With the same code as above running on 3 GPUs, the first one is utilized at 100% but the 2 others are below 30% most of the time.

**Comment by sushreebarsa** [comment]
@guillaumekln It looks like you are using an older Version of Tensorflow. Many bugs have been fixed in the latest version. Could you please execute your code using Latest Version 2.4.1 or 2.5.0 and let us know if the issue still persists? Thanks!

**Comment by guillaumekln** [comment]
I ran the code again with TensorFlow 2.5.0 (`experimental_run_v2` should be replaced by `run` to make it work). I'm still seeing the same issue: the usage of each GPU is very low at around 20%.

**Comment by tilakrayal** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
