### ISSUE TITLE
0.9.0 installation issue 

### ISSUE THREAD

**Issue by mrphoenix13** [tensorflow/tensorflow#3071]
I have a system that have no access to the internet. usually I download the wheel file of tensorflow and install it via file. I'm trying to upgrade tensorflow version with my method but it seem it cant be done. I'm trying to upgrade my tensorflow version from 0.8.0 to 0.9.0.
### Environment info
Operating System: Ubuntu 14.04  (CPU version)

### Logs or other output that would be helpful
```Exception:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/local/lib/python2.7/dist-packages/pip/commands/install.py", line 317, in run
    prefix=options.prefix_path,
  File "/usr/local/lib/python2.7/dist-packages/pip/req/req_set.py", line 742, in install
    **kwargs
  File "/usr/local/lib/python2.7/dist-packages/pip/req/req_install.py", line 831, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "/usr/local/lib/python2.7/dist-packages/pip/req/req_install.py", line 1032, in move_wheel_files
    isolated=self.isolated,
  File "/usr/local/lib/python2.7/dist-packages/pip/wheel.py", line 348, in move_wheel_files
    assert info_dir, "%s .dist-info directory not found" % req
AssertionError: cpu-tensorflow==0.9.0 .dist-info directory not found

**Comment by martinwicke** [comment]
What version of pip/setuptools are you running? Can you check if upgrading
might help? We haven't changed anything in our wheel file so I'm surprised
either way since you were able to install 0.8.

**Comment by mrphoenix13** [comment]
my pip version is the latest one 8.1.2 
as I said before upgrading tensorflow from web cause no problem in my system. But when I'm trying to upgrade it via downloaded wheel file in my offline system, It gives me the error that i mentioned before. I'm surprised too. before this release I had no such problem in upgrading via file.

**Comment by martinwicke** [comment]
Can you uninstall 0.8.0 first? I'm wondering whether this is a problem with 0.8.0 instead which surfaces during upgrades. Although I'm just guessing at this point.

**Comment by aselle** [comment]
Automatically closing due to lack of recent of activity. Please reopen if new information becomes available.
