### ISSUE TITLE
TensorFlow import error

### ISSUE THREAD

**Issue by leops95** [tensorflow/tensorflow#30721]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10 x64
- TensorFlow installed from (source or binary): binary
- TensorFlow version: 1.14.0
- Python version: 3.7.4 x64
- Installed using virtualenv? pip? conda?: pip
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory: Intel core i7 6700, 16GB ram

**Describe the problem**
Hi,
I would like to import tensorflow on pycharm. I checked related posts but I think that I missed a step somewhere. Please excuse me I am new to python and may have forgotten something trivial. 

**Provide the exact sequence of commands / steps that you executed before running into the problem**

I installed tensorflow and it succeeded, then run the following code: (I disabled unused import statements but it seems that it is still an issue).

```
from __future__ import absolute_import, division, print_function, unicode_literals

import tensorflow as tf
from tensorflow import keras

import numpy as np
import matplotlib.pyplot as plt
print(tf.__version__)
```

**Any other info / logs**

I get the following error message:

```
Traceback (most recent call last):
  File "C:/Users/Leo Picard/PycharmProjects/tensorflow/tensorflow_init.py", line 4, in <module>
    import tensorflow as tf
  File "C:\Python\lib\site-packages\tensorflow\__init__.py", line 28, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "C:\Python\lib\site-packages\tensorflow\python\__init__.py", line 47, in <module>
    import numpy as np
  File "C:\Python\lib\site-packages\numpy\__init__.py", line 142, in <module>
    from . import core
  File "C:\Python\lib\site-packages\numpy\core\__init__.py", line 23, in <module>
    WinDLL(os.path.abspath(filename))
  File "C:\Python\lib\ctypes\__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 193] %1 is not a valid Win32 application
```

**Comment by eduardofv** [comment]
You may find useful the following videos:
[How to use TensorFlow in PyCharm](https://www.youtube.com/watch?v=K9ypGzuP6xQ) and [De-bug your TensorFlow projects with the PyCharm IDE](https://www.youtube.com/watch?v=hYOOGstEzzM)

**Comment by gadagashwini** [comment]
@leops95 Just to confirm, did you follow the steps mentioned in the [Tensorflow](https://www.tensorflow.org/install/pip) site. Thanks!

**Comment by leops95** [comment]
@gadagashwini Yes, I followed the steps of the first video and I still have the same error message. Now I have the 2.0 version, but I don't believe it's the main issue here. I am working on it and will keep you informed as soon as I find something.

Thanks a lot for your time and consideration towards my request !

**Comment by gadagashwini** [comment]
@leops95 Looks like you found a workaround. Can we close this issue. You can update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Comment by leops95** [comment]
@gadagashwini problem solved. I had to update numpy and suppress pandas FutureWarning using

```
import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)

```

Thanks again for the help !
