### ISSUE TITLE
TensorFlow Lite build fatal error: gtest/gtest.h: No such file or directory

### ISSUE THREAD

**Issue by akotlarsky** [tensorflow/tensorflow#30722]
**System information**
- Raspberry Pi 3
- TensorFlow installed from (source or binary): source
- TensorFlow version:  1.14.0

**Describe the problem**

When natively compiling TensorFlow Lite 1.14.0 in Raspberry Pi 3, I am getting the following compile error:
fatal error: gtest/gtest.h: No such file or directory

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

Here is the error log:
arm-linux-gnueabihf-g++ -O3 -DNDEBUG -fPIC  --std=c++11 -march=armv7-a -mfpu=neon-vfpv4 -funsafe-math-optimizations -ftree-vectorize -fPIC -I. -I/home/pi/tensorflow-1.14.0/tensorflow/lite/tools/make/../../../../../ -I/home/pi/tensorflow-1.14.0/tensorflow/lite/tools/make/../../../../../../ -I/home/pi/tensorflow-1.14.0/tensorflow/lite/tools/make/downloads/ -I/home/pi/tensorflow-1.14.0/tensorflow/lite/tools/make/downloads/eigen -I/home/pi/tensorflow-1.14.0/tensorflow/lite/tools/make/downloads/absl -I/home/pi/tensorflow-1.14.0/tensorflow/lite/tools/make/downloads/gemmlowp -I/home/pi/tensorflow-1.14.0/tensorflow/lite/tools/make/downloads/neon_2_sse -I/home/pi/tensorflow-1.14.0/tensorflow/lite/tools/make/downloads/farmhash/src -I/home/pi/tensorflow-1.14.0/tensorflow/lite/tools/make/downloads/flatbuffers/include -I -I/usr/local/include -c tensorflow/lite/kernels/test_main.cc -o /home/pi/tensorflow-1.14.0/tensorflow/lite/tools/make/gen/rpi_armv7l/obj/tensorflow/lite/kernels/test_main.o
tensorflow/lite/kernels/test_main.cc:17:25: fatal error: gtest/gtest.h: No such file or directory
 #include <gtest/gtest.h>
                         ^
compilation terminated.
tensorflow/lite/tools/make/Makefile:241: recipe for target '/home/pi/tensorflow-1.14.0/tensorflow/lite/tools/make/gen/rpi_armv7l/obj/tensorflow/lite/kernels/test_main.o' failed
make: *** [/home/pi/tensorflow-1.14.0/tensorflow/lite/tools/make/gen/rpi_armv7l/obj/tensorflow/lite/kernels/test_main.o] Error 1
make: *** Waiting for unfinished jobs....
In file included from ./tensorflow/lite/kernels/cpu_backend_gemm.h:22:0,
                 from ./tensorflow/lite/kernels/internal/optimized/optimized_ops.h:42,
                 from tensorflow/lite/kernels/sub.cc:18:
./tensorflow/lite/kernels/cpu_backend_gemm_custom_gemv.h: In static member function ‘static void tflite::cpu_backend_gemm::detail::CustomGemvImpl<LhsScalar, RhsScalar, int, DstScalar, quantization_flavor>::Run(const tflite::cpu_backend_gemm::MatrixParams<LhsScalar>&, const LhsScalar*, const tflite::cpu_backend_gemm::MatrixParams<RhsScalar>&, const RhsScalar*, const tflite::cpu_backend_gemm::MatrixParams<DstScalar>&, DstScalar*, const tflite::cpu_backend_gemm::GemmParams<int, DstScalar, quantization_flavor>&, int, int)’:
./tensorflow/lite/kernels/cpu_backend_gemm_custom_gemv.h:484:13: warning: attributes at the beginning of statement are ignored [-Wattributes]
             [[clang::fallthrough]];
             ^
./tensorflow/lite/kernels/cpu_backend_gemm_custom_gemv.h:487:13: warning: attributes at the beginning of statement are ignored [-Wattributes]
             [[clang::fallthrough]];
             ^
./tensorflow/lite/kernels/cpu_backend_gemm_custom_gemv.h:490:13: warning: attributes at the beginning of statement are ignored [-Wattributes]
             [[clang::fallthrough]];
             ^
./tensorflow/lite/kernels/cpu_backend_gemm_custom_gemv.h:493:13: warning: attributes at the beginning of statement are ignored [-Wattributes]
             [[clang::fallthrough]];
             ^
./tensorflow/lite/kernels/cpu_backend_gemm_custom_gemv.h:496:13: warning: attributes at the beginning of statement are ignored [-Wattributes]
             [[clang::fallthrough]];
             ^
./tensorflow/lite/kernels/cpu_backend_gemm_custom_gemv.h:499:13: warning: attributes at the beginning of statement are ignored [-Wattributes]
             [[clang::fallthrough]];
             ^
pi@raspberrypi:~/tensorflow $

**Comment by akotlarsky** [comment]
After applying fixes described in:

https://github.com/tensorflow/tensorflow/pull/29017/commits/05514a000a017dbe7db7643d084b16def9719c99

and

https://github.com/tensorflow/tensorflow/issues/29806

I successfully built TensorFlow Lite 1.14.0 and 2.0.0-beta1.  Does it make sense?

**Comment by akotlarsky** [comment]
In addition to the above, in order to build aarch64 TensorFlow Lite, in the Makefile retrieved from https://github.com/tensorflow/tensorflow/issues/29806, I had to add -flax-vector-conversions and -fomit-frame-pointer to CXXFLAGS, and set BUILD_WITH_NNAPI=false (as described in https://github.com/tensorflow/tensorflow/issues/26731).

And that is not all...

In order to cross-compile aarch64 TensorFlow Lite in Yocto environment on a Linux host PC, I had to further edit the Makefile and replace ":=" with "?=" for the following macros:  TARGET, TARGET_ARCH, TARGET_TOOLCHAIN_PREFIX, CC_PREFIX, CXX, CC, AR; and replace ":=" with "+=" for the following macros: CXXFLAGS, CCFLAGS, CFLAGS.

Attached is the Makefile that works.
[Makefile.zip](https://github.com/tensorflow/tensorflow/files/3399374/Makefile.zip)

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.

**Comment by akotlarsky** [comment]
Wow, this has been long time ago.  Yes, go ahead and close this issue.

Toly Kotlarsky

[Zebra_Logo_Stacked_K_small]
Toly Kotlarsky
Distinguished Member Technical Staff, R&D
ZEBRA TECHNOLOGIES CORPORATION

One Zebra Plaza
Holtsville, NY 11742
T: +1 631 738 3068 M: +1 215 570 5782
toly.kotlarskyl@zebra.com<mailto:toly.kotlarskyl@zebra.com>
www.zebra.com<http://www.zebra.com/>

Follow Zebra!
[social-fb]<http://www.facebook.com/zebratechnologiesglobal>
[social-tstr]<http://www.twitter.com/zebratechnology>
[social-in]<https://www.linkedin.com/company/167024?trk=tyah&trkInfo=tarId:1398351214615,tas:zebra,idx:3-1-7>
[social-g+]<https://plus.google.com/u/0/b/116127895496262117488/116127895496262117488/posts>
[social-B]<http://blogs.zebra.com/>
[social-youtube]<http://www.youtube.com/user/ZebraTechnologies>
[social-zebra]<http://www.slideshare.net/ZebraTechnologies>
