### ISSUE TITLE
GPU device creation fails when using the CUDA Malloc Allocator

### ISSUE THREAD

**Issue by MattConley** [tensorflow/tensorflow#30736]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): no
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below): 1.14/master
- Python version: 3.6
- Bazel version (if compiling from source): 0.24.1
- GCC/Compiler version (if compiling from source): 7.4.0
- CUDA/cuDNN version: 10.0
- GPU model and memory: RTX 2080

**Describe the current behavior**
GPU device creation fails when the cuda malloc allocator is selected, with the error "No allocator statistics".  This is because of an allocator stats check introduced between releases 1.13.1 and 1.14 in the gpu common runtime  [BaseGPUDeviceFactory::CreateGPUDevice function](https://github.com/tensorflow/tensorflow/blob/r1.14/tensorflow/core/common_runtime/gpu/gpu_device.cc#L1310-L1312).  This check fails when using the cuda malloc allocator because the virtual Allocator method GetStats was never overridden.

**Describe the expected behavior**
GPU device creation should succeed if the user specifies use of the cuda malloc allocator.

**Code to reproduce the issue**
Use the TF_GPU_ALLOCATOR environment variable to select the cuda malloc allocator:
`$ export TF_GPU_ALLOCATOR="cuda_malloc"`

Then, in a python shell, try to use the gpu:
```
$ python

>>> import tensorflow as tf
>>> tf.test.is_gpu_available()
```

**Comment by MattConley** [comment]
Submitted PR #30737 as a proposed solution to implement the GetStats function, thereby not failing the `if(!stats)` check in gpu_device.cc

**Comment by MattConley** [comment]
Looks like my PR was successfully merged; closing the issue.

**Comment by weiserhase** [comment]
Im encountering the same issue 
#48571
