### ISSUE TITLE
Unable to find documentation for framework/ common run time files

### ISSUE THREAD

**Issue by sthomdev** [tensorflow/tensorflow#30730]
Hello TF team,

I've been combing the documentation for any reference to OpKernels, Graphs defs, the executor, rendezvous, ect... the important abstractions that seem to be near the core of tensorflow. So far I haven't been able to find any kind of high level overview of how they all come together. I'm working on a feature that involves adding a new device and I don't want to miss any important abstractions in my implementation.

Does anyone know where I could find documentation that is concerned with how the tensorflow framework / run time work?
Thanks,
Scott

**Comment by Saduf2019** [comment]
@sthomdev please confirm if you are still facing any issue

**Comment by MarkDaoust** [comment]
We have this on our todo list: better documentation for tensorflow internals.

**Comment by SuryanarayanaY** [comment]
Hi @sthomdev ,
Iam not sure about the documentation earlier. I  found there is documentation regarding [Opkernels](https://www.tensorflow.org/guide/create_op) now. Regarding Graphdef i found below statement :

> You should not need to use GraphDefs directly in TF2. To load GraphDefs in TF2, use SavedModel. The SavedModel contains the GraphDef.

which means it may not be much useful now.

There also few APIs regarding executors [here](https://www.tensorflow.org/federated/api_docs/python/tff/framework).

Could you please check and confirm whether the documentation is updated and fulfilled your expectation.

Thankyou!
