### ISSUE TITLE
why GetLocalGPUInfo() using cuda runtime api, I guess it should use cudart_stub instead.

### ISSUE THREAD

**Issue by chengleiwang** [tensorflow/tensorflow#30744]
Base on below commit, cuda Runtime API should wrapped in dynamic load， but I still see  tensorflow/core/grappler/clusters/utils.cc using cuda Runtime API.

commit: 7c5aed39f0148f93cebef850d939558a938b41e7
Remove tensorflow core runtime's explicit dependency on cuda runtime.
- Add stub implementation which is wrapped in dynamic loader
- Replace the runtime dependency with stub in tf_cuda_library

Adopted csigg@'s method in cl/230858143 to work around the issue where the cuda runtime calls in Eigen::initializeDeviceProp() cannot be wrapped with the macro method.

PiperOrigin-RevId: 232063778

**Comment by aaroey** [comment]
@chsigg any ideas?

**Comment by chsigg** [comment]
@yifeif might have missed them or they might have been introduced afterwards.

**Comment by chengleiwang** [comment]
@yifeif ，could you please tell me how to fix this issue? I tried use cc_library instead of tf_cuda_library, code path in GOOGLE_CUDA will not execte.

**Comment by chengleiwang** [comment]
Any suggestion?

**Comment by yifeif** [comment]
@chengleiwang I believe tensorflow/core/grappler/clusters/utils.cc is using cudart_stub.
[`utils`](https://github.com/tensorflow/tensorflow/blob/4eb56665431534476801486257087f16d8ddee4c/tensorflow/core/grappler/clusters/BUILD#L22) is a tf_cuda_library, which depends on [`cudart_stub`](https://github.com/tensorflow/tensorflow/blob/4eb56665431534476801486257087f16d8ddee4c/tensorflow/tensorflow.bzl#L1359) for its implementation.

**Comment by chengleiwang** [comment]
@yifeif, yes, utils depends on cudart_stub, but actually it doesn't call dynamic cuda runtime api. I have debug this for  several days. You can do a quick check by remove cudaGetDevicrProperties() in cudart_stub.cc/cuda_runtime_10_0.inc and then you can run a test , set a breakpoints at cudaGetDeviceProperties() in utils.cc. You can see it still can execute this Api without using dynamic one.

I see that TensorFlow still using static library during the building step. So I guess this is the root cause for this issue. utils.cc will link to static library's symbol. So may I know why TensorFlow still depends on static library? I tried to remove static link part but I got build errors~ would you pls give me some suggestion? I worked on this issue for long days but no progress ~~

**Comment by yifeif** [comment]
Which platform are you on?

**Comment by chengleiwang** [comment]
Ubuntu18.04

**Comment by chengleiwang** [comment]
@yifeif , Are you able to reproduce this issue? Any suggestion?
