### ISSUE TITLE
If padding='same', which side is padded with 0?

### ISSUE THREAD

**Issue by JaneShenYY** [tensorflow/tensorflow#30740]
If set `padding='same'` for `Conv1D`, which side (the start or the end) is padded with 0 if the `kernel_size=2` and `stride=1`?
I checked the code, but didn't find any clue. Hope this simple question can be clarified here. Thanks.

**Comment by ravikyram** [comment]
This question is better asked on StackOverflow since it is not a bug or feature request. There is also a larger community that reads questions there and provide better and faster support for such issues. Thanks!

**Comment by JaneShenYY** [comment]
@ravikyram Thanks for the suggestion. Before asking it here, I put the question on StackOverflow, but no reply after many days. Thus, I came here and thought this place would be more likely to have some responses.

**Comment by ravikyram** [comment]
@JaneShenYY 

Normally padding with zeros will be distributed equally from both left and right  and also up and down.Normally It will not take from one direction.

I am closing this issue since it is not a bug or feature request.Thanks!
