### ISSUE TITLE
Couldn't find and import the 'graph_transforms' module in tensorflow1.14

### ISSUE THREAD

**Issue by Leslie-Fang** [tensorflow/tensorflow#30746]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Centos7.6
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): source 
- TensorFlow version (use command below): 1.14
- Python version: 2.7
- Bazel version (if compiling from source): 24.1
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
```
import tensorflow.tools.graph_transforms as graph_transforms
```
Error message:
```
AttributeError: 'module' object has no attribute 'graph_transforms'
```

**Describe the expected behavior**
Successfully import the graph_transforms module.
 This code succesfully run with tf 1.13 but failed on tf 1.14.

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.
```
import tensorflow.tools.graph_transforms as graph_transforms
```

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.
The installed 'graph_transforms' module seems has been moved to tensorflow_core folder in site-packages.
Is this as expected?

**Comment by Leslie-Fang** [comment]
It seems when running latest the build_pip_package.sh script,  it would move the code from tensorflow folder into the tensorflow_core folder.
```
  # In order to break the circular dependency between tensorflow and
  # tensorflow_estimator which forces us to do a multi-step release, we are
  # creating a virtual python package called tensorflow and moving all the tf
  # code into another python package called tensorflow_core:
  #
  #   * move code from tensorflow to tensorflow_core
  #   * create the virtual pip package: create folder and __init__.py file with
  #     needed code for transparent forwarding
```

**Comment by ravikyram** [comment]
@Leslie-Fang 
I tried reproducing issue with the provided code  using both TF1.13 and 1.14 and i am able to import 
graph _transforms.Thanks!

**Comment by Leslie-Fang** [comment]
@ravikyram 
Really thanks  for your reply.
I aslo try 
```
pip install tensorflow
```
It would install tf1.14 and would **not** reproduce my issue.

However if I build the TF from src with the commit-id: 81acfa851ecf413df02c6bdf4795630524f2f859
It do reproduce the issue.

I also check the PR request, the changes has been introduced since this PR request has been merged https://github.com/tensorflow/tensorflow/pull/29579

@perfinion Is my understanding right?

**Comment by Leslie-Fang** [comment]
I use this command to print tensorflow version
```
python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"
```

1. Build from source code: https://github.com/tensorflow/tensorflow/commit/81acfa851ecf413df02c6bdf4795630524f2f859
('v1.12.1-5541-g81acfa851e', '1.14.0')

2. pip install tensorflow
('v1.14.0-rc1-22-gaf24dc91b5', '1.14.0')

Is this due to some version difference?
Which one would be the long-term supported?

**Comment by Leslie-Fang** [comment]
@ravikyram @ymodak  Hi, sorry to interrupt, but any update of this question?

**Comment by ymodak** [comment]
I was able to reproduced your issue with TF-Nightly version '1.15.0-dev20190723'

**Comment by snajnin** [comment]
Anu update/solution on this issue?

**Comment by GHGmc2** [comment]
try `import tensorflow_core.tools.graph_transforms as graph_transforms` for tf1.x

**Comment by GHGmc2** [comment]
> try `import tensorflow_core.tools.graph_transforms as graph_transforms` for tf1.x

update, use:
`from tensorflow.tools.graph_transforms import xxx`

**Comment by unrahul** [comment]
For 2.0 it seems the issue has cropped up again:

```bash
In [8]: tf.__version__                                                                                                                                                                        
Out[8]: '2.1.0-dev20191114'

In [9]: from tensorflow.tools import graph_transforms                                                                                                                                         
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-9-81608bad8d7f> in <module>
----> 1 from tensorflow.tools import graph_transforms

ImportError: cannot import name 'graph_transforms' from 'tensorflow_core.tools' (/usr/lib/python3.7/site-packages/tensorflow_core/tools/__init__.py)

In [10]: from tensorflow import tools                                                                                                                                                         

In [11]: dir(tools)                                                                                                                                                                           
Out[11]: 
['__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__']
```
The issue is reproducible both with TF2.0 release version and TF nightly.

**Comment by GHGmc2** [comment]
I think there's no  entry to python wrapper of "transform_graph", which was in contrib module on tf1.x

**Comment by venky-intel** [comment]
Was there any resolution or suggestion on how to proceed on this?

**Comment by jesusmariajurado** [comment]
Is there any solution to this?. Thanks.

**Comment by anuragmundhada** [comment]
if i try to import from core, i get the following error:

from tensorflow_core.tools.graph_transforms import TransformGraph

*** ImportError: cannot import name 'TransformGraphWithStringInputs' from 'tensorflow.python.pywrap_tensorflow' (/home/anurag/anaconda3/envs/pytorch/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow.py)

**Comment by samhodge** [comment]
I am having this issue now with 2.2 I will go back to 1.13.1

**Comment by Heldenkrieger01** [comment]
Is there any solution for TF 2.2?

**Comment by PKarhade** [comment]
TransformGraphWithStringInputs is available in tf2.0 however I am planning to jump to tf2.2 or tf2.3 but I couldn't find "TransformGraphWithStringInputs" in these 2 versions. Anyone found any solution regarding that?

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.

**Comment by omerasif57** [comment]
Tensorflow: 
```
tensorboard             2.5.0
tensorboard-data-server 0.6.1
tensorboard-plugin-wit  1.8.0
tensorflow              2.5.0
tensorflow-estimator    2.5.0
tensorflow-serving-api  2.5.1

```
Error:

```
from tensorflow.tools.graph_transforms import TransformGraph
```

> 
> --------------------------------------------------------------------------
> ModuleNotFoundError                      Traceback (most recent call last)
> <ipython-input-77-1fd86d9792e0> in <module>
> ----> 1 from tensorflow.tools.graph_transforms import TransformGraph
> 
> ModuleNotFoundError: No module named 'tensorflow.tools.graph_transforms'


I do not want to downgrade as 1.x has gone EOL. 
Last option would be to go [bazel](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/graph_transforms/README.md#transform-reference) it.

**Comment by pemoi1982jpm** [comment]
Is there a solution for this?
I am trying to use tf2onnx tool but I get an error:

`python3.7 -m tf2onnx.convert --saved-model . --output model.onnx`

```
 File "/home/jupyter/.local/lib/python3.7/site-packages/tf2onnx/tfonnx.py", line 20, in <module>
    from tensorflow.tools.graph_transforms import TransformGraph
ModuleNotFoundError: No module named 'tensorflow.tools.graph_transforms'
```

Using tensorflow 2.8.0

**Comment by omerasif57** [comment]
> Is there a solution for this? I am trying to use tf2onnx tool but I get an error:
> 
> `python3.7 -m tf2onnx.convert --saved-model . --output model.onnx`
> 
> ```
>  File "/home/jupyter/.local/lib/python3.7/site-packages/tf2onnx/tfonnx.py", line 20, in <module>
>     from tensorflow.tools.graph_transforms import TransformGraph
> ModuleNotFoundError: No module named 'tensorflow.tools.graph_transforms'
> ```
> 
> Using tensorflow 2.8.0


Make sure you are using recent versions of `onnx` and `tf2onnx`. 

You can paste you issue on [tensorflow-onnx](https://github.com/onnx/tensorflow-onnx) as well.

### references
- #### tfonnx
    - https://github.com/onnx/tensorflow-onnx/blob/v1.9.3/tf2onnx/tfonnx.py  
    - https://github.com/onnx/tensorflow-onnx/releases/tag/v1.9.3
- ##### graph_transforms
    - https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/graph_transforms/README.md#using-the-graph-transform-tool
