### ISSUE TITLE
TF >=1.13 doesn't support CUDA 9.0

### ISSUE THREAD

**Issue by bonlime** [tensorflow/tensorflow#30753]
**System information**
- OS Platform and Distribution: Linux Ubuntu 16.04
- TensorFlow installed from (source or binary): build from source
- TensorFlow version: `1.13.1, 1.14.0, 2.0.0a, 2.0.0b1`
- Python version: 3.5
- Installed using virtualenv? pip? conda?: ...
- Bazel version (if compiling from source): `0.25.2`
- GCC/Compiler version (if compiling from source): `5.4.0`
- CUDA/cuDNN version: `CUDA 9.0, cudnn 7.6.1`
- GPU model and memory: Tesla V100

**Describe the problem**
I want to compile newer versions of TF from source to support CUDA 9.0 . I tried building all versions after 1.12.0 and always get the same error. Bazel build sucessfully finishes but after I install the resulting pip file and try to import TF it doesn't use GPU's
`Could not dlopen library 'libcusolver.so.9.0'; dlerror: /usr/local/cuda-9.0/lib64/libcusolver.so.9.0: undefined symbol: GOMP_critical_end; LD_LIBRARY_PATH: /usr/local/cuda-9.0/lib64`
```
2019-07-16 14:37:23.856339: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcudart.so.9.0
2019-07-16 14:37:23.857504: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcublas.so.9.0
2019-07-16 14:37:23.858807: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcufft.so.9.0
2019-07-16 14:37:23.859066: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcurand.so.9.0
2019-07-16 14:37:23.859437: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Could not dlopen library 'libcusolver.so.9.0'; dlerror: /usr/local/cuda-9.0/lib64/libcusolver.so.9.0: undefined symbol: GOMP_critical_end; LD_LIBRARY_PATH: /usr/local/cuda-9.0/lib64
2019-07-16 14:37:23.860627: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcusparse.so.9.0
2019-07-16 14:37:23.864452: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcudnn.so.7
2019-07-16 14:37:23.864478: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1663] Cannot dlopen some GPU libraries. Skipping registering GPU devices...

```

**Provide the exact sequence of commands / steps that you executed before running into the problem**

I use `configure` script with all parameters at default except specifying CUDA version. Then I build with:
`bazel build --config=opt --config=cuda //tensorflow/tools/pip_package:build_pip_package`

**Any other info / logs**
This problem was already reported before: #30389  
I also found discussion, where people had the same issue with cusolver library:
https://groups.google.com/forum/#!topic/kaldi-help/8OThZ1lwE9I

**Comment by rishabhsahrawat** [comment]
Try updating your Cuda version to 10.0 exact (also not 10.1). It should support training on GPUs.

**Comment by bonlime** [comment]
@rishabhsahrawat updating CUDA on the server is not an option for multiple reasons. I want to compile TF specifically for CUDA 9.0

**Comment by anush-o** [comment]
@bonlime ,
Please take a look at [software requirements](https://www.tensorflow.org/install/gpu#software_requirements) for TF installation.Thanks!

**Comment by njzjz** [comment]
If TensorFlow only support CUDA 10.0, I think `configure` script should prevent from using other CUDA versions.

**Comment by bonlime** [comment]
@anush-o  it says "TensorFlow supports CUDA 10.0 (TensorFlow >= 1.13.0)". I supposed it meant TF should support old versions of CUDA 9.0 as well as new 10.0

**Comment by anush-o** [comment]
@bonlime ,
This is Tested and existing compatibility of CUDA and TF versions. In order to use CUDA 9.0 you can downgrade the TF version to 1.12.Thanks!

**Comment by bonlime** [comment]
The reason why opened this issue is because I expected TF 1.13 to support lower versions of CUDA as well. Looks like it doesn't. 
I'll close the issue, but if anyone finds a way to compile from sources for CUDA 9.0 feel free to comment here

**Comment by kk325ic** [comment]
@oanush how do you downgrade to 1.12? I got the error message

 ERROR: Could not find a version that satisfies the requirement tensorflow==1.12 (from versions: 1.13.0rc1, 1.13.0rc2, 1.13.1, 1.13.2, 1.14.0rc0, 1.14.0rc1, 1.14.0, 2.0.0a0, 2.0.0b0, 2.0.0b1)

**Comment by njzjz** [comment]
You need to downgrade Python to 3.6. TF 1.12 does not support Python 3.7.

**Comment by 004307ec** [comment]
@bonlime 
```
import ctypes
ctypes.CDLL("libgomp.so.1", mode=ctypes.RTLD_GLOBAL)
```
This two lines might allow you to run CNN networks with TF 1.14 + CUDA 9.
But it might cause strange behavior with LSTM models, where TF tries to allocate extensive VRAM and fails).

**Comment by smr97** [comment]
@004307ec Can you please describe where to add this? Also, do I have to build this from source in order to run TF 1.14 with CUDA 9.0?

**Comment by bonlime** [comment]
@smr97 Yes you have to build from source in order to use TF 1.14 with CUDA 9.0. You need to add the lines above to the beginning of your scripts which use TF

**Comment by sudonto** [comment]
@bonlime , can you confirm that those two lines really affect LSTM behaviour?

**Comment by bonlime** [comment]
@sudonto No. I was only using TF for computer vision tasks, didn't check the LSTM behavior
