### ISSUE TITLE
tf.sparse.to_dense does not work on sparse tensor with string values. 

### ISSUE THREAD

**Issue by simonsays1980** [tensorflow/tensorflow#30750]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04.2 LTS (Bionic Beaver)
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: -
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 1.14.0
- Python version: 3.6.7
- Bazel version (if compiling from source): -
- GCC/Compiler version (if compiling from source): -
- CUDA/cuDNN version: -
- GPU model and memory: -

**Describe the current behavior**
Trying to convert a SparseTensor of type string into the corresponding dense tensor using tf.sparse.to_dense throughs an exception: TypeError: Expected string passed to parameter 'default_value' of op 'SparseToDense', got 0 of type 'int' instead. Error: Expected string, got 0 of type 'int' instead.

**Describe the expected behavior**
Like with using an integer valued SparseTensor I expect tf.sparse.to_dense to return a dense tensor with string values. 

**Code to reproduce the issue**
```
import tensorflow as tf
sample_int    = tf.sparse.SparseTensor(indices=[[0, 0], [1, 2]], values=[1, 2], dense_shape=[3, 4])
sample_string = tf.sparse.SparseTensor(indices=[[0, 0], [1, 2]], values=['a', 'b'], dense_shape=[3, 4])
tf.sparse.to_dense( sample_int )
tf.sparse.to_dense( sample_string )
```
There is also a colab notebook where you can execute the code directly: [https://colab.research.google.com/drive/1OxZCVWdnEYAkmGDZ7hAvP2mkFbxYX4Zh](https://colab.research.google.com/drive/1OxZCVWdnEYAkmGDZ7hAvP2mkFbxYX4Zh)

**Other info / logs**
I came across this issue while reading in some TFRecords that included VarLenFeatures with string-typed lists. Everything worked fine with the VarLenFeatures with integers. Right now I have not even found a way to convert the SparseTensor's string values into a new Tensor as a workaround.

**Comment by yongtang** [comment]
Add a PR #30781 for the fix.
