### ISSUE TITLE
Android: Failed to resolve: tensorflow-lite

### ISSUE THREAD

**Issue by peterszaszlateral** [tensorflow/tensorflow#30755]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): MacOS 10.13.2 HighSierra

- TensorFlow installed from (source or binary): gradle dependency 'org.tensorflow:tensorflow-lite:0.0.0-nightly'
- TensorFlow version: 0.0.0-nightly
- Android Studio : 3.2.1
- Android compile / targetSdkVersion  = 28
- Gradle Version: 4.6

**Describe the problem**

Tensorflow Lite dependency is not resolved 

**Provide the exact sequence of commands / steps that you executed before running into the problem**

Run assembleDebug command -> 
_Could not find tensorflow-lite.aar (org.tensorflow:tensorflow-lite:0.0.0-nightly).
  Searched in the following locations:
      https://jcenter.bintray.com/org/tensorflow/tensorflow-lite/0.0.0-nightly/tensorflow-lite-0.0.0-nightly.aar_

**Any other info / logs**

**Comment by itimmisriis** [comment]
I am receiving this error as well. Assuming this is a nightly build error, but will wait for feedback.

**Comment by joelromanpr** [comment]
You can try using the explicit version 1.14.0

https://bintray.com/google/tensorflow/tensorflow-lite#

**Comment by siddhi-droid** [comment]
@joelromanpr Thanks it worked!

**Comment by peterszaszlateral** [comment]
I can easily replace the dependency, but there are some classes missing in this version

error: cannot find symbol public class TFLiteObjectDetectionAPIModel implements Classifier {
error: cannot find symbol private Interpreter tfLite;
error: cannot find symbo public List<Recognition>

**Comment by jdduke** [comment]
@peterszaszlateral that looks like a different issue. TFLiteObjectDetectionAPIModel is a part of the sample, not of tensorflow-lite.aar.

I'm not able to reproduce the issue with the nightly build, though. Are you able to successfully the build the classification example? https://github.com/tensorflow/examples/tree/master/lite/examples/image_classification/android

**Comment by peterszaszlateral** [comment]
@jdduke It all started working again last week at some point + the sample app you specified is also building successfully. Thanks for the help!

**Comment by jdduke** [comment]
Glad it's working!

**Comment by Ryenum** [comment]
Hello, I am running times error: “Caused by: org.gradle.internal.resolve.ModuleVersionNotFoundException:  Could not find org. Tensorflow: tensorflow - lite - select - tf - ops: 0.0.0 - the nightly - the SNAPSHOT.

"Is there a good solution?

**Comment by Ryenum** [comment]
> 您可以尝试使用显式版本 1.14.0
> 
> https://bintray.com/google/tensorflow/tensorflow-lite#

Hello, how to use this version? Do I need to manually download and import it or do I need to change the library address in the project file?
