### ISSUE TITLE
Multiply complex number with a scalar

### ISSUE THREAD

**Issue by NEGU93** [tensorflow/tensorflow#30757]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using): 1.13.1
- Are you willing to contribute it (Yes/No): Yes

**Describe the feature and the current behavior/state.**

When I multiply a `tf.complex` with any other like `tf.float` it would be helpful to take the float as a complex number with imag part =0 (treat it as a scalar).

**Will this change the current api? How?**
 When using `tf.matmult()` between a complex and a real number it will automatically cast the real one to complex and perform the operation instead of trhowing:
`TypeError: Input 'b' of 'MatMul' Op has type float32 that does not match type complex64 of argument 'a'.`
 
**Who will benefit with this feature?**

I am currently trying to do a Complex-Valued Neural Network and I am having some headache with that. So I think it will helpful when doing a CVNN

**Any Other info.**

**Comment by jvishnuvardhan** [comment]
@NEGU93 The error is correct as you are trying to multiply a complex number (of dtype tf.complex64) with another dtype. Hence, there is a mismatch in dtype. But, if you define `b` as of dtype=tf.complex64, then it works without any issue. Please check the [gist here](https://colab.sandbox.google.com/gist/jvishnuvardhan/dad77e1df747c75d394b284597c18259/tf_30757.ipynb). 

If you looking for different feature and you have a use-case for that then you could raise a PR. Please let me know what you think? Thanks!

**Comment by jvishnuvardhan** [comment]
Closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
