### ISSUE TITLE
Problem compiling version 0.9 for iOS

### ISSUE THREAD

**Issue by lcavalie** [tensorflow/tensorflow#3076]
### Environment info
Operating System: macOS 10.11.5
xcode 7.3.1
I tried installing on 2 different computers and got the exact same error. One system was very clean as it was freshly initialized out of the box and had not been polluted.

### Steps to reproduce
I follow the steps indicated here first for the Makefile and than the steps specific to install for iOS
- clone the repository
- install the dependencies
- run build_all_ios.sh

Everything run fine for a little while and I get the following error:

configure: creating ./config.status
config.status: creating Makefile
config.status: creating scripts/gtest-config
config.status: creating build-aux/config.h
config.status: executing depfiles commands
config.status: executing libtool commands
+ make
/Applications/Xcode.app/Contents/Developer/usr/bin/make  all-recursive
Making all in .
make[2]: Nothing to be done for `all-am'.
Making all in src
/Users/lcavalie/iOSdev/tensorflow/tensorflow/contrib/makefile/gen/protobuf-host/bin/protoc -I. --cpp_out=. google/protobuf/any_test.proto google/protobuf/compiler/cpp/cpp_test_bad_identifiers.proto google/protobuf/map_lite_unittest.proto google/protobuf/map_proto2_unittest.proto google/protobuf/map_unittest.proto google/protobuf/unittest_arena.proto google/protobuf/unittest_custom_options.proto google/protobuf/unittest_drop_unknown_fields.proto google/protobuf/unittest_embed_optimize_for.proto google/protobuf/unittest_empty.proto google/protobuf/unittest_enormous_descriptor.proto google/protobuf/unittest_import_lite.proto google/protobuf/unittest_import.proto google/protobuf/unittest_import_public_lite.proto google/protobuf/unittest_import_public.proto google/protobuf/unittest_lite_imports_nonlite.proto google/protobuf/unittest_lite.proto google/protobuf/unittest_mset.proto google/protobuf/unittest_mset_wire_format.proto google/protobuf/unittest_no_arena_lite.proto google/protobuf/unittest_no_arena_import.proto google/protobuf/unittest_no_arena.proto google/protobuf/unittest_no_field_presence.proto google/protobuf/unittest_no_generic_services.proto google/protobuf/unittest_optimize_for.proto google/protobuf/unittest_preserve_unknown_enum2.proto google/protobuf/unittest_preserve_unknown_enum.proto google/protobuf/unittest.proto google/protobuf/unittest_proto3_arena.proto google/protobuf/unittest_proto3_arena_lite.proto google/protobuf/unittest_proto3_lite.proto google/protobuf/unittest_well_known_types.proto google/protobuf/util/internal/testdata/anys.proto google/protobuf/util/internal/testdata/books.proto google/protobuf/util/internal/testdata/default_value.proto google/protobuf/util/internal/testdata/default_value_test.proto google/protobuf/util/internal/testdata/field_mask.proto google/protobuf/util/internal/testdata/maps.proto google/protobuf/util/internal/testdata/oneofs.proto google/protobuf/util/internal/testdata/struct.proto google/protobuf/util/internal/testdata/timestamp_duration.proto google/protobuf/util/json_format_proto3.proto google/protobuf/util/message_differencer_unittest.proto google/protobuf/compiler/cpp/cpp_test_large_enum_value.proto
make[2]: /Users/lcavalie/iOSdev/tensorflow/tensorflow/contrib/makefile/gen/protobuf-host/bin/protoc: No such file or directory
make[2]: *** [unittest_proto_middleman] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
+ make install
Making install in .
make[2]: Nothing to be done for `install-exec-am'.
 ./install-sh -c -d '/Users/lcavalie/iOSdev/tensorflow/tensorflow/contrib/makefile/gen/protobuf_ios/lib/ios_arm64/lib/pkgconfig'
 /usr/bin/install -c -m 644 protobuf.pc protobuf-lite.pc '/Users/lcavalie/iOSdev/tensorflow/tensorflow/contrib/makefile/gen/protobuf_ios/lib/ios_arm64/lib/pkgconfig'
Making install in src
/Users/lcavalie/iOSdev/tensorflow/tensorflow/contrib/makefile/gen/protobuf-host/bin/protoc -I. --cpp_out=. google/protobuf/any_test.proto google/protobuf/compiler/cpp/cpp_test_bad_identifiers.proto google/protobuf/map_lite_unittest.proto google/protobuf/map_proto2_unittest.proto google/protobuf/map_unittest.proto google/protobuf/unittest_arena.proto google/protobuf/unittest_custom_options.proto google/protobuf/unittest_drop_unknown_fields.proto google/protobuf/unittest_embed_optimize_for.proto google/protobuf/unittest_empty.proto google/protobuf/unittest_enormous_descriptor.proto google/protobuf/unittest_import_lite.proto google/protobuf/unittest_import.proto google/protobuf/unittest_import_public_lite.proto google/protobuf/unittest_import_public.proto google/protobuf/unittest_lite_imports_nonlite.proto google/protobuf/unittest_lite.proto google/protobuf/unittest_mset.proto google/protobuf/unittest_mset_wire_format.proto google/protobuf/unittest_no_arena_lite.proto google/protobuf/unittest_no_arena_import.proto google/protobuf/unittest_no_arena.proto google/protobuf/unittest_no_field_presence.proto google/protobuf/unittest_no_generic_services.proto google/protobuf/unittest_optimize_for.proto google/protobuf/unittest_preserve_unknown_enum2.proto google/protobuf/unittest_preserve_unknown_enum.proto google/protobuf/unittest.proto google/protobuf/unittest_proto3_arena.proto google/protobuf/unittest_proto3_arena_lite.proto google/protobuf/unittest_proto3_lite.proto google/protobuf/unittest_well_known_types.proto google/protobuf/util/internal/testdata/anys.proto google/protobuf/util/internal/testdata/books.proto google/protobuf/util/internal/testdata/default_value.proto google/protobuf/util/internal/testdata/default_value_test.proto google/protobuf/util/internal/testdata/field_mask.proto google/protobuf/util/internal/testdata/maps.proto google/protobuf/util/internal/testdata/oneofs.proto google/protobuf/util/internal/testdata/struct.proto google/protobuf/util/internal/testdata/timestamp_duration.proto google/protobuf/util/json_format_proto3.proto google/protobuf/util/message_differencer_unittest.proto google/protobuf/compiler/cpp/cpp_test_large_enum_value.proto
make[1]: /Users/lcavalie/iOSdev/tensorflow/tensorflow/contrib/makefile/gen/protobuf-host/bin/protoc: No such file or directory
make[1]: *** [unittest_proto_middleman] Error 1
make: *** [install-recursive] Error 1
+ lipo /Users/lcavalie/iOSdev/tensorflow/tensorflow/contrib/makefile/gen/protobuf_ios/lib/iossim_386/lib/libprotobuf.a /Users/lcavalie/iOSdev/tensorflow/tensorflow/contrib/makefile/gen/protobuf_ios/lib/iossim_x86_64/lib/libprotobuf.a /Users/lcavalie/iOSdev/tensorflow/tensorflow/contrib/makefile/gen/protobuf_ios/lib/ios_arm7/lib/libprotobuf.a /Users/lcavalie/iOSdev/tensorflow/tensorflow/contrib/makefile/gen/protobuf_ios/lib/ios_arm7s/lib/libprotobuf.a /Users/lcavalie/iOSdev/tensorflow/tensorflow/contrib/makefile/gen/protobuf_ios/lib/ios_arm64/lib/libprotobuf.a -create -output /Users/lcavalie/iOSdev/tensorflow/tensorflow/contrib/makefile/gen/protobuf_ios/lib/libprotobuf.a
fatal error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/lipo: can't open input file: /Users/lcavalie/iOSdev/tensorflow/tensorflow/contrib/makefile/gen/protobuf_ios/lib/iossim_386/lib/libprotobuf.a (No such file or directory)
+ lipo /Users/lcavalie/iOSdev/tensorflow/tensorflow/contrib/makefile/gen/protobuf_ios/lib/iossim_386/lib/libprotobuf-lite.a /Users/lcavalie/iOSdev/tensorflow/tensorflow/contrib/makefile/gen/protobuf_ios/lib/iossim_x86_64/lib/libprotobuf-lite.a /Users/lcavalie/iOSdev/tensorflow/tensorflow/contrib/makefile/gen/protobuf_ios/lib/ios_arm7/lib/libprotobuf-lite.a /Users/lcavalie/iOSdev/tensorflow/tensorflow/contrib/makefile/gen/protobuf_ios/lib/ios_arm7s/lib/libprotobuf-lite.a /Users/lcavalie/iOSdev/tensorflow/tensorflow/contrib/makefile/gen/protobuf_ios/lib/ios_arm64/lib/libprotobuf-lite.a -create -output /Users/lcavalie/iOSdev/tensorflow/tensorflow/contrib/makefile/gen/protobuf_ios/lib/libprotobuf-lite.a
fatal error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/lipo: can't open input file: /Users/lcavalie/iOSdev/tensorflow/tensorflow/contrib/makefile/gen/protobuf_ios/lib/iossim_386/lib/libprotobuf-lite.a (No such file or directory)

### What have you tried?
I looked into tensorflow/contrib/makefile/gen/ it contains only a protobuf-host folder that is empty and a protobuf_ios folder with the various architectures and on each case only 2 files /lib/ios_arm7/lib/pkgconfig/protobuf-lite.pc and  /lib/ios_arm7/lib/pkgconfig/protobuf.pc 

Assuming that there is a problem with the building of everything related to protobuf I tried to run compile_ios_protobuf.sh it resulted in the exact same error.

### Logs or other output that would be helpful
I can upload the full log if needed

**Comment by petewarden** [comment]
Sorry you're hitting problems! I checked in a related fix to top-of-tree in #3075 a couple of hours ago. Can you give that a try and let me know if that fixes your issue?

**Comment by davlhd** [comment]
The inclusion of _make_host_protoc_ in the latest changes fixed this problem for me.

**Comment by lcavalie** [comment]
Hi pete
I can confirm that #3075 fixed the problem for me. The makefile can actually go through now.
I think this issue can be close. Thanks for your help. (big fan of your blog BTW)
