### ISSUE TITLE
Minimum number of epochs before termination for tf.keras.callbacks.EarlyStopping()

### ISSUE THREAD

**Issue by joglekara** [tensorflow/tensorflow#30767]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using):
1.14
- Are you willing to contribute it (Yes/No):
Yes

**Describe the feature and the current behavior/state.**
This feature is not yet implemented but is simple to implement. It requires an additional flag, storing one more `int`, and few more `if`-statements in tf.keras.callbacks.EarlyStopping().

**Will this change the current api? How?**
Yes, in that one more variable will be available to be assigned when calling the EarlyStopping callback.

**Who will benefit with this feature?**
Anyone who wishes to use EarlyStopping but wants to let the model train for a certain number of epochs before EarlyStopping is activated.

**Any Other info.**
N/A

**Comment by vvsotnikov** [comment]
I think that `patience` parameter is [what you need](https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/keras/callbacks/EarlyStopping#arguments):
> patience: Number of epochs with no improvement after which training will be stopped.

**Comment by joglekara** [comment]
Hmm, not quite. 

I'm saying there needs to be a `minimum` number of epochs before the `patience` parameter kicks in.

@jvishnuvardhan @ravikyram, I'm happy to share the code and submit a PR.

**Comment by jvishnuvardhan** [comment]
@joglekara Do you have any use case that requires the feature you are interested in? Please feel free to submit a PR if you have use cases that supports that feature. 

For most (or all) of the cases I have come across, patience param will be sufficient. In the initial stages of training, there will be high fluctuation in the metrics so it will earlystopping will not kickin for few iterations. Thanks!

**Comment by joglekara** [comment]
Yes, definitely a few use cases for this feature.

The most straightforward one is if you're using a training schedule w.r.t. epoch, you may only want EarlyStopping to apply after a certain portion of the training schedule is reached. 

Sounds good, I will submit a PR

**Comment by jvishnuvardhan** [comment]
@joglekara Why PR was closed by you. Why there is no code in the PR? Please let me know if you are not interested in the PR or want to close this issue. Thanks!

**Comment by joglekara** [comment]
I closed my PR because I was having issues with the email address/CLA. Here's the [open PR](https://github.com/tensorflow/tensorflow/pull/30939)

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.
