### ISSUE TITLE
implementation of tf.dense_tensor_sparse_matmul() such that a matrix product AB can be computed where A is dense and B is sparse.

### ISSUE THREAD

**Issue by joglekara** [tensorflow/tensorflow#30766]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using):
1.14
- Are you willing to contribute it (Yes/No):
Yes

**Describe the feature and the current behavior/state.**
The feature is not implemented in a transparent fashion. The operation can be performed by using tf.sparse.sparse_tensor_dense_matmul() and some matrix algebra. It is a python-only implementation and does not require going into the C/CUDA code.

**Will this change the current api? How?**
It will add a new function call within tf.sparse.

**Who will benefit with this feature?**
Most people who use the Sparse library.

**Any Other info.**
I've already implemented and tested this feature against NumPy's matrix math library. I wanted to bring it up and see if this is a desirable feature.

**Comment by joglekara** [comment]
@ymodak @gadagashwini , I've already implemented this, I am happy to share, or even submit a PR if you like.

**Comment by ymodak** [comment]
Perhaps you can elaborate more on how the new proposed feature distinguishes itself from the current implementation of [tf.sparse.sparse_dense_matmul](https://www.tensorflow.org/api_docs/python/tf/sparse/sparse_dense_matmul)?

**Comment by joglekara** [comment]
The current implementation only allows a `left multiply` with a `SparseTensor`, but what if one needs to be able to perform a `right multiply` with a SparseTensor? One cannot simply reverse the order of operations because matrix products do not commute i.e. AB != BA.

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.

**Comment by joglekara** [comment]
This was merged into v2.1

**Comment by sjtusmartboy** [comment]
@joglekara Please tell us the function name
