### ISSUE TITLE
What replaces tf.data.get_output_shapes in TF 2?

### ISSUE THREAD

**Issue by jbgh2** [tensorflow/tensorflow#30774]
TF 2 Datasets don't appear to have the output_shape property and there is no tf.data.get_output_shapes. 

What do we use instead?

**Comment by ppham27** [comment]
`tf.data.experimental.get_structure` should have shape information.

https://www.tensorflow.org/api_docs/python/tf/data/experimental/get_structure?hl=en

**Comment by jbgh2** [comment]
@ppham27 Thank you! This could be made more obvious in the docs.

**Comment by anush-o** [comment]
@jbgh2 ,
Looks like issue is resolved.Can i proceed for closure.Thanks!

**Comment by anush-o** [comment]
Closing since the issue is resolved.Thanks!
