### ISSUE TITLE
"--config mkl" => mkl_version.h: No such file or directory

### ISSUE THREAD

**Issue by plopresti** [tensorflow/tensorflow#30772]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Red Hat Enterprise Linux 7.6
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): source
- TensorFlow version: master
- Python version: 3.6
- Installed using virtualenv? pip? conda?: N/A
- Bazel version (if compiling from source): 0.26.1
- GCC/Compiler version (if compiling from source): 8.2.1
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

**Describe the problem**

Building TF master with "--config mkl" fails because it is looking for Intel MKL (not MKL-DNN).

**Provide the exact sequence of commands / steps that you executed before running into the problem**

bazel build --config opt --config mkl //tensorflow/tools/pip_package:build_pip_package

**Any other info / logs**
In file included from external/mkl_dnn/src/cpu/rnn/ref_rnn.hpp:28,
                 from external/mkl_dnn/src/cpu/rnn/cell_gru_lbr.cpp:24:
external/mkl_dnn/src/cpu/rnn/../gemm/os_blas.hpp:33:10: fatal error: mkl_version.h: No such file or directory
 #include "mkl_version.h"
          ^~~~~~~~~~~~~~~
compilation terminated.

Note that mkl_version.h is an Intel MKL header, not an MKL-DNN header. It looks like the current MKL-DNN binary blob requires MKL by default.

**Comment by plopresti** [comment]
Update:

If I add these lines (back) to .bazelrc:

    build --spawn_strategy=standalone
    build --strategy=Genrule=standalone

...my build works again.

(Somehow, the "mkl_linux" tree does not make its way into processwrapper-sandbox. I do not know enough about Bazel to understand what the underlying problem is here.)

**Comment by nhasabni** [comment]
It looks like commit [7a2ce469a70e55855b09030a96d2f6eeb825e253](https://github.com/tensorflow/tensorflow/commit/7a2ce469a70e55855b09030a96d2f6eeb825e253) is the reason for this issue.

**Comment by plopresti** [comment]
@nhasabni Thanks. So you could reproduce the problem? I was not sure whether it was somehow my environment.

P.S. Could I convince you to take a peek at (the unrelated) issue 30383 ?

**Comment by nhasabni** [comment]
@plopresti Yes we could reproduce the issue. Also, for 30383, we are looking into it.

**Comment by preethivenkatesh** [comment]
@plopresti, can you confirm if you are still experiencing this issue? BTW  #30383 is fixed in 1.15

**Comment by plopresti** [comment]
@preethivenkatesh This issue is resolved.

Initial testing on #30383 looks good; we are trying other cases and will update soon. Thanks!
