### ISSUE TITLE
Feature Request: Adding a "LayerListWrapper"-like class for adding list of layers (Non-sequential) to keras model.

### ISSUE THREAD

**Issue by BorisPolonsky** [tensorflow/tensorflow#30786]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using): Tensorflow 2.0.0b0-gpu
- Are you willing to contribute it (Yes/No): Yes

**Describe the feature and the current behavior/state.**
Typical scenario: Assume that one needs to add a list that contains variable number of `tf.keras.layers.Layer` to a keras Model. By specifying something like `self.list_of_layers = [...]` in the `__init__` method`tf.keras.Model` subclass objects, the model won't track the trainable variables within layers in the list. For now this can be hacked by appending it to self._layers (e.g. `self._layers += self.list_of_layers`) to make the model object track the variables created in the layers in the list. 

It would be helpful if there were a class like pytorch's `ModuleLists` that wraps list of layers up and enables the model to "register" theses layers and the corresponding `tf.Variable` objects automatically. 

**Will this change the current api? How?**
Yes. New wrapper that accepts list of tf.keras.layers.Layer objects will be added. 
Not sure there will be any side effects
**Who will benefit with this feature?**
People who need to add non-sequential layers to `tf.keras.Model` subclass objects. 
People who are accustomed to the its equivalents in other deep learning framworks (e.g. `ModuleLists` in Pytorch). 
**Any Other info.**
This is also proposed in [this stackoverflow thread](https://stackoverflow.com/questions/56117745/how-to-use-a-list-of-layers-in-tensorflow-2-0).

A simple user case
```Python
class TextCNN(tf.keras.Model):
    def __init__(self, embedding, n_kernels, channel_per_kernel, n_cls):
        super(TextCNN, self).__init__()
        self.embedding = embedding
        self.convs = tuple(tf.keras.layers.Conv1D(channel_per_kernel, n_gram, strides=1, padding="same") for n_gram in range(2, 2 + n_kernels))
        # Temporary hack due to not finding a class like `ModuleLists` in pytorch. 
        self._layers += self.convs
        self.temporal_pooling = tf.keras.layers.GlobalMaxPool1D(data_format="channels_last")
        self.output_fc = tf.keras.layers.Dense(n_cls)
    
    def call(self, x, training=False):
        output = self.embedding(x)
        output = [conv(output) for conv in self.convs]
        output = tf.concat(output, axis=-1)
        output = self.temporal_pooling(output)
        output = self.output_fc(output)
        return output
```

**Comment by pandrey-fr** [comment]
Hi,
I believe that if you change `self.convs` from a tuple to a list, you get the desired results.

```python
class TextCNN(tf.keras.Model):
    def __init__(self, embedding, n_kernels, channel_per_kernel, n_cls):
        super(TextCNN, self).__init__()
        self.embedding = embedding
        self.convs = [
            tf.keras.layers.Conv1D(channel_per_kernel, n_gram, strides=1, padding="same")
            for n_gram in range(2, 2 + n_kernels)
        ]
        self.temporal_pooling = tf.keras.layers.GlobalMaxPool1D(data_format="channels_last")
        self.output_fc = tf.keras.layers.Dense(n_cls)
    
    def call(self, x, training=False):
        output = self.embedding(x)
        output = [conv(output) for conv in self.convs]
        output = tf.concat(output, axis=-1)
        output = self.temporal_pooling(output)
        output = self.output_fc(output)
        return output
```

Generate a model using this class constructor, build it and you should see the proper number of parameters in `model.summary()`.

**Comment by BorisPolonsky** [comment]
That worked and thank @pandrey-fr for the answer. 
I used tuple to prevent content of `self.convs` from being changed. Didn't know why tuple is not allowed in this case.

**Comment by pandrey-fr** [comment]
You are welcome!
I totally understand why you would intuitively go for a tuple instead of a list, and to be honest it could be nice if TF would recognize those (I think this has to do with wrapper classes implementation, but I do not know much about it). Anyway, what matters is that your code works :)
