### ISSUE TITLE
Where can I find binary tensorflow-gpu 1.12 for PPC64LE

### ISSUE THREAD

**Issue by derekhsu** [tensorflow/tensorflow#30784]
The community-supported tensorflow-gpu is 1.14 which require CUDA 10 but I only have CUDA 9, does anyone know where can I find built tensorflow-gpu 1.12?

**Comment by gadagashwini** [comment]
@derekhsu Please find the instructions mentioned in the [Tenosrflow](https://www.tensorflow.org/install/source) website to build tensorflow.Thanks!

**Comment by gadagashwini** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged//tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.

**Comment by ymodak** [comment]
@derekhsu Perhaps you can try,
```pip install tensorflow-gpu==1.12```

**Comment by steffen-AEI** [comment]
Also on ppc64le (RHEL 7.6). None of the versioned nor unversioned install commands work, e.g.
```
$ pip install tensorflow
Collecting tensorflow
  ERROR: Could not find a version that satisfies the requirement tensorflow (from versions: none)
ERROR: No matching distribution found for tensorflow
```
obviously due to the lack of matching wheels for this architecture.
I guess the same would happen on the arm64 server I'd get next week...

**Comment by steffen-AEI** [comment]
Confirmed on arm64. :'(
