### ISSUE TITLE
Allow_soft_placement=True does not solve "no supported kernel for GPU devices is available" problem

### ISSUE THREAD

**Issue by tdplaza** [tensorflow/tensorflow#30782]
I have got this error: 
` InvalidArgumentError (see above for traceback): Cannot assign a device for operation 'model/inference/encoder_LSTM/bidirectional_rnn/fw/fw/Assert/Assert': Could not satisfy explicit device specification '/device:GPU:0' because no supported kernel for GPU devices is available.
Registered kernels:
  device='CPU'
`

other people said that setting tf.ConfigProto to "allow_soft_placement=True" will probably solve this problem.

But it does not. Any other idea? Please help.

**Comment by Rudy-Zhang** [comment]
I got the same issue, did you solve it? @tdplaza

**Comment by Rudy-Zhang** [comment]
I create estimator and preditor based on tensor2tensor following code

```
hp = create_hparams()
decode_hp = create_decode_hparams()
run_conf = t2t_trainer.create_run_config(hp)
estimator = trainer_lib.create_estimator(
    FLAGS.model,
    hp,
    run_conf,
    decode_hparams=decode_hp,
    use_tpu=FLAGS.use_tpu)
predictor=tf.contrib.predictor.from_estimator(estimator, input_fn)
```

then got

> InvalidArgumentError: Cannot assign a device for operation transformer/body/parallel_0/body/encoder/layer_0/self_attention/multihead_attention/dot_product_attention/attention: Could not satisfy explicit device specification '/device:GPU:0' because no supported kernel for GPU devices is available.
> Colocation Debug Info:
> Colocation group had the following types and supported devices: 
> Root Member(assigned_device_name_index_=-1 requested_device_name_='/device:GPU:0' assigned_device_name_='' resource_device_name_='' supported_device_types_=[CPU] possible_devices_=[]
> ImageSummary: CPU 
> 
> Colocation members, user-requested devices, and framework assigned devices, if any:
>   transformer/body/parallel_0/body/encoder/layer_0/self_attention/multihead_attention/dot_product_attention/attention (ImageSummary) /device:GPU:0
> 
> Op: ImageSummary
> Node attrs: max_images=1, T=DT_FLOAT, bad_color=Tensor<type: uint8 shape: [4] values: 255 0 0...>
> Registered kernels:
>   device='CPU'
> 	 [[{{node transformer/body/parallel_0/body/encoder/layer_0/self_attention/multihead_attention/dot_product_attention/attention}}]]
> 
> During handling of the above exception, another exception occurred:

when I print session_config
`print(run_conf.session_config)`

I got 


> gpu_options {
>   per_process_gpu_memory_fraction: 0.95
> }
> **allow_soft_placement: true**
> graph_options {
>   optimizer_options {
>     global_jit_level: OFF
>   }
> }
> isolate_session_state: true


still can't solve this problem

**Comment by tdplaza** [comment]
yes, I did. 

My problem was, I need putting allow_soft_placement=True on both training, and inferencing config Session. 

My problem occurs when I only put it on training config, and inferencing through above  error. 

When inferencing, make sure you put it on configProto, then create a Session with that ConfigProto. Then run the tf.global_variables_initilizer(). Then create a saver object and restore the session using that saver and checkpoint path. Like following. 
![image](https://user-images.githubusercontent.com/31118781/62921486-d62cd900-bde3-11e9-9d2b-c0a2a68f1340.png)

If this does not help, you need find a new way to fix. good luck bro

**Comment by Rudy-Zhang** [comment]
> yes, I did.
> 
> My problem was, I need putting allow_soft_placement=True on both training, and inferencing config Session.
> 
> My problem occurs when I only put it on training config, and inferencing got above error.
> 
> When inferencing, make sure you put it on configProto, then create a Session with that ConfigProto. Then run the tf.global_variables_initilizer(). Then create a saver object and restore the session using that saver and checkpoint path. Like following.
> ![image](https://user-images.githubusercontent.com/31118781/62921486-d62cd900-bde3-11e9-9d2b-c0a2a68f1340.png)
> 
> If this does not help, you need find a new way to fix. good luck bro

Thank you for your remind! I solved the problem just as you did. When I put config in predictor's config, the error does not show any more.

```
session_config = tf.ConfigProto(log_device_placement=True, allow_soft_placement=True)
predictor = tf.contrib.predictor.from_estimator(estimator, input_fn, config=session_config)
```
