### ISSUE TITLE
Unable to find implementation of Select TensorFlow operators

### ISSUE THREAD

**Issue by Jnasic** [tensorflow/tensorflow#30799]
I am trying to use Select tensorflow operators ( https://www.tensorflow.org/lite/guide/ops_select ). I have successfully created AAR file. But android studio is unable to find implementation of 
**implementation 'org.tensorflow:tensorflow-lite-with-select-tf-ops:0.1.100'**

> ERROR: Failed to resolve: org.tensorflow:tensorflow-lite-with-select-tf-ops:0.1.100

as described in (https://www.tensorflow.org/lite/guide/ops_select). 
Kindly tell me how should I implement select-tf-ops tflite version ?
Thanks

**Comment by Oktai15** [comment]
@Jnasic, try to replace all `tf.where` to `where` from this [issue](https://github.com/tensorflow/tensorflow/issues/30222).

**Comment by Jnasic** [comment]
But I am trying to implement this functionality ( https://www.tensorflow.org/lite/guide/ops_select ) which is different than select operator. Actually I shifted to tensorflow lite select operators because I was unable to find custom implementation of ExpandDims which tflite does not support now. If you can help me with this it would be great though.

**Comment by Oktai15** [comment]
@Jnasic I use `tf.expand_dims` and everything is okay, my model is converted to tflite sucessfully. 
Example:
`ps = tf.expand_dims(tf.expand_dims(ps, 1), 1)`

**Comment by Jnasic** [comment]
Ohh great!
But how can I include that in TOCO command. Actually I am using DeepLabv3 + coco trained (http://download.tensorflow.org/models/deeplabv3_mnv2_pascal_trainval_2018_01_29.tar.gz) but I am unable to convert it to tflite because of ExpandDims. I used following command for conversion.

`toco --graph_def_file=/home/abdullah/models-master/research/frozen_casted.pb --input_format=TENSORFLOW_GRAPHDEF --output_format=TFLITE --output_file=deeplabv3_mnv2_pascal_trainval.tflite --inference_type=FLOAT --inference_input_type=QUANTIZED_UINT8 --input_arrays=ImageTensor --output_arrays=SemanticPredictions --input_shapes=1,1024,1024,3 --default_ranges_min=0 --default_ranges_max=255 --allow_custom_ops --architecture=mobilenet_v2 --std_dev_values=128 --mean_values=1
`

**Comment by jdduke** [comment]
Rather than using mvn to install your .aar, you can also add a "libs" folder in your Android Studio project, put your `tensorflow-lite-with-select-tf-ops.aar` file there, and modify your gradle project with:

```
allprojects {
    repositories {
        jcenter()
        flatDir {
            dirs 'libs'
        }
    }
}

dependencies {
    compile(name:'tensorflow-lite-with-select-tf-ops', ext:'aar')
}
```

**Comment by kumariko** [comment]
@Jnasic Could you please let us know if this issue still persists ? If it is resolved then please feel free to move this issue to close status ? check https://github.com/tensorflow/tensorflow/issues/30799#issuecomment-513356671 Thanks!

**Comment by abattery** [comment]
Closing due to the no response. Please file a new issue if this issue persists on the recent TF version.
