### ISSUE TITLE
.predict with numpy arrays fails if predictions are time major instead of batch major

### ISSUE THREAD

**Issue by ismael-elatifi** [tensorflow/tensorflow#30797]
In TF 1.14, .predict fails if predictions are time major i.e. their dimensions are [NB_TIME_STEPS, BATCH_SIZE, N] and not batch major as usual i.e. [BATCH_SIZE, NB_TIME_STEPS, N].
The error is : 
```
  File "......\site-packages\tensorflow\python\keras\engine\training_utils.py", line 169, in aggregate
    self.results[i][batch_start:batch_end] = batch_out
ValueError: could not broadcast input array from shape (NB_TIME_STEPS,BATCH_SIZE,N) into shape (BATCH_SIZE,BATCH_SIZE,N)
```
The cause of the bug is that when TF pre-allocates the destination ndarray in self.results, it always assume batch major dimensions (hardcode).
Code in `tensorflow/python/keras/engine/training_utils.py` :
```
class OutputsAggregator(Aggregator):
  def create(self, batch_outs):
```
```
        elif isinstance(batch_out, np.ndarray):
          # If the output is a ndarray, append an output array pre-allocated
          # to the expected shape of the output.
          shape = (self.num_samples_or_steps,) + batch_out.shape[1:]  <-- HERE IS THE BUG
          self.results.append(np.zeros(shape, dtype=batch_out.dtype))
```
I guess the problematic code is `batch_out.shape[1:]`.
The `[1:]` gets rid of batch size dimension but this is wrong in case of time major ndarray where it removes time dimensions instead. That is why `shape` is (BATCH_SIZE,BATCH_SIZE,N).

**Comment by ravikyram** [comment]
Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version. Also, did you compile from source or install a binary?

Make sure you also include the code snippet to reproduce the issue. If you are unclear what to include see the issue template displayed in the [Github](https://github.com/tensorflow/tensorflow/issues/new/choose) new issue template.

We ask for this in the issue submission template, because it is really difficult to help without that information. Thanks!

**Comment by ismael-elatifi** [comment]
Actually it may not be a bug because TF is somewhat forced to assume first dimension is batch dimension.
I solved my issue by switching to batch major (removing the `x = tf.transpose(x, perm=[1,0,2])` in my model).
I needed time major dimensions because `tf.nn.ctc_greedy_decoder` expects time major logits. But now I do not the transpose inside the model but outside just before the call to tf.nn.ctc_greedy_decoder :
def edit_distance_metric(labels, logits):
    sparse_labels = dense_to_sparse_tensor(labels)
    nb_timesteps_ctc = tf.shape(logits)[1]
    batch_size = tf.shape(logits)[0]
    #logits are batch major
    logits = tf.transpose(logits, perm=[1, 0, 2])
    #logits are now time major
    decoded, log_prob = tf.nn.ctc_greedy_decoder(inputs=logits,  
                                                 sequence_length=tf.fill([batch_size], nb_timesteps_ctc),
                                                 merge_repeated=True)
