### ISSUE TITLE
Add keras.layers.Layer.add_callback

### ISSUE THREAD

**Issue by beasteers** [tensorflow/tensorflow#30809]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using): `1.13.1`
- Are you willing to contribute it (Yes/No): maybe, but I won't have time in the next week or two

**Describe the feature and the current behavior/state.**

Currently, custom Keras layers have `add_loss` and `add_metric`. It would be nice if layers could also contribute their own callback functions as well. 

**Will this change the current api? How?**

It would add a method `add_callback` to the `keras.layers.Layer` class. 

**Who will benefit with this feature?**

The main use case that I see this for is layers that have some warm start or epoch-dependent parameters. By adding them directly inside the layer, it keeps layers completely composable. 

Currently, we need to do something like this:

```python
input = x
my_layer = MyLayer(...)
x = my_layer(x)
...
model = Model(input, x)
model.compile(...)
model.fit(..., callbacks=[WarmStartCallback(my_layer.alpha)])
```

But it would be much cleaner to be able to do this:

```python
class MyLayer(Layer):
    def __init__(self, warm_start=True):
        self.alpha = tf.Variable(...)
        if warm_start:
            self.add_callback(WarmStartCallback(self.alpha))


input = x
x = MyLayer(...)(x)
...
model = Model(input, x)
model.compile(...)
model.fit(...)
```

**Any Other info.**

Off hand, here's a sketch of major changes that I see being needed:

```python
# tf.keras.engine.base_layer
class Layer:
    def __init__(self, ...):
        ...
        self._metrics = []

        # +
        self._callbacks = []
        ...

    @property
    def callbacks(self):
        return self._callbacks + self._gather_children_attribute('callbacks')

    def add_callback(self, callback):
        # maybe some checks, conversions, etc
        ...
        self._callbacks.append(callback)

# tf.keras.engine.training
class Model:
    def fit(..., callbacks=None, ...):
        ...
        # +
        layer_callbacks = self._gather_children_attribute('callbacks') 
        callbacks = layer_callbacks + callbacks if callbacks else layer_callbacks

        func = self._select_training_loop(x)
        ...

```

**Comment by karmel** [comment]
@beasteers -- thanks for the request. At this time, we are having trouble coming up with a way to do this that doesn't introduce a lot of complexity into the code, so we will close this unless we come up with a better approach.
