### ISSUE TITLE
Using tf.function while enumerating a dataset causes an infinite loop

### ISSUE THREAD

**Issue by BeWe11** [tensorflow/tensorflow#30802]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): MacOS 10.14.5
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.0.0-beta1
- Python version: 3.6
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Describe the current behavior**
Using `tf.function` when enumerating a dataset will cause an infinite loop.

**Describe the expected behavior**
Using `tf.function` when enumerating a dataset should not change the looping behavior.

**Code to reproduce the issue**
The code snippet below will hang after the last function call. I'm not printing anything because calling `tf.print` results in a syntax error on colab and I know that these snippets are being run on colab by you. When printing the variable `i`, it's clear that the loop just never stops, i.e. `i` increase indefinitely.

```python
import tensorflow as tf

ds = tf.data.Dataset.from_tensor_slices([1,2,3,4])

def test_loop_without_enumerate_without_decorator(ds):
    for val in ds:
        pass

@tf.function
def test_loop_without_enumerate_with_decorator(ds):
    for val in ds:
        pass

def test_loop_with_enumerate_without_decorator(ds):
    for i, val in enumerate(ds):
        pass

@tf.function
def test_loop_with_enumerate_with_decorator(ds):
    for i, val in enumerate(ds):
        pass

print("Without tf.function and without enumerate")
test_loop_without_enumerate_without_decorator(ds)

print("Without tf.function and with enumerate")
test_loop_with_enumerate_without_decorator(ds)

print("With tf.function and without enumerate")
test_loop_without_enumerate_with_decorator(ds)

print("With tf.function and with enumerate")
test_loop_with_enumerate_with_decorator(ds)
```

**Other info / logs**
Output of the above snippet:
```
Without tf.function and without enumerate
Without tf.function and with enumerate
With tf.function and without enumerate
With tf.function and with enumerate
**HANGS HERE**
```

**Comment by gadagashwini** [comment]
I was able to reproduce the issue on Colab with Tensorflow 2.0.0.beta1. Please have a look at gist of [Colab](https://colab.research.google.com/drive/1UXGUopt4bVq-NUslCJVxw_BHeOlq0Rkz) link. Thanks

**Comment by mdanatg** [comment]
AutoGraph does not currently override `enumerate`, so it has the wrong behavior in graph mode. It would be a nice feature to add, and it shouldn't be too hard to do it.

In the mean time, to enumerate over datasets, please use `ds.enumerate()`. It works both inside and outside `tf.function`:

```
def test_loop_with_ds_enumerate_without_decorator(ds):
    for i, val in ds.enumerate():
        tf.print(i, val)

@tf.function
def test_loop_with_ds_enumerate_with_decorator(ds):
    for i, val in ds.enumerate():
        tf.print(i, val)

print("Without tf.function and ds.enumerate")
test_loop_with_ds_enumerate_without_decorator(ds)

print("With tf.function and ds.enumerate")
test_loop_with_ds_enumerate_with_decorator(ds)
```
```
Without tf.function and ds.enumerate
0 1
1 2
2 3
3 4
With tf.function and ds.enumerate
0 1
1 2
2 3
3 4
```

**Comment by BeWe11** [comment]
@mdanatg thank you, that worked for me. I'm gonna let this issue stay open, as the underlying problem hasn't been fixed yet, but feel free to close if you need to.

**Comment by ilhamfp** [comment]
@mdanatg I'm interested in working on this! I'm confused on how to get started. I've read the documentation on AutoGraph & tf.function decorator as well as [the code](https://github.com/tensorflow/tensorflow/blob/r2.0/tensorflow/python/eager/def_function.py#L725-L1027) and I can't spot which code is responsible for overriding such action. Pardon my inexperience.

**Comment by mdanatg** [comment]
@ilhamfp that's great, happy to help you get started!

The dynamic dispatch can indeed make things a bit confusing.

The place to add this is in the Python builtin overloads file: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/autograph/operators/py_builtins.py

The file contains a number of overloads, check out `len` for instance, that you can use as a model. Then, once you have the overload of `enumerate`, you just need to add it to the lists at the bottom of the file, `SUPPORTED_BUILTINS` and `BUILTIN_FUNCTIONS_MAP` (there's a bit of duplication there). That should be it - the overload for function calls (https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/autograph/impl/api.py#L390, placed in the `api` module for various reasons) should pick it up at Python runtime.

**Comment by ilhamfp** [comment]
@mdanatg Please review #31036  
Thank you :D

**Comment by llan-ml** [comment]
> AutoGraph does not currently override `enumerate`, so it has the wrong behavior in graph mode.

Hi @mdanatg . Just out of curiosity, what do you mean by "wrong behavior in graph mode"? With `tensorflow==2.0alpha0`, I often use `enumerate` to iterate over a list of layers within a call function as follows:
```
In [2]: import tensorflow as tf

In [3]: tf.__version__
Out[3]: '2.0.0-alpha0'

In [4]: from tensorflow.keras.layers import Dense

In [5]: layers = [Dense(10), Dense(20), Dense(30)]

In [6]: @tf.function
   ...: def call(x):
   ...:     for i, layer in enumerate(layers):
   ...:         x = layer(x)
   ...:     return x

In [7]: y = call(tf.random.uniform((10, 20)))
```
It would be grateful if you could explain a bit more.

**Comment by mdanatg** [comment]
@llan-ml I was referring to calling `enumerate` with a `tf.data.Dataset` argument. Called with Python lists it was working fine. See the original post - before #31038, calling `test_loop_with_enumerate_with_decorator` in the original example caused an infinite loop, which was incorrect. At any rate, `enumerate` should now be fully supported for datasets.

**Comment by tgsmith61591** [comment]
@mdanatg

> AutoGraph does not currently override enumerate, so it has the wrong behavior in graph mode. It would be a nice feature to add, and it shouldn't be too hard to do it.

Could you guys add this to [the documentation](https://www.tensorflow.org/api_docs/python/tf/data/Dataset) for tf.Dataset? Seems like a quick addition that would prove super valuable. Thanks!

**Comment by mdanatg** [comment]
@tgsmith61591 This issue should be resolved - enumerate should now work correctly with datasets in tf.function, with TF >= 1.5. Have you been still experiencing issues?
