### ISSUE TITLE
Problem with meta file size when saving model initialized with pre-trained weights

### ISSUE THREAD

**Issue by SimsGautam** [tensorflow/tensorflow#3080]
### Context/Problem

I have pretrained models (from elsewhere) with weights saved as numpy arrays. I want to create a tensorflow model where the weights and biases are initialized with numpy arrays rather than random tensors. I am able to do this (code snippet below), but run into problems when I try saving/loading my model.

Specifically, the problem involves using the `Saver` class to save `model` and `model.meta`. I expect `model.meta` to be much smaller in size than `model`, but this is not the case. In fact, using the code snippet below, you can see that the meta file is the same size as the model file.

This results in problems when importing the meta file with much larger models.

### Environment info
Operating System: Ubunutu 14.04
Tensorflow version: '0.9.0rc0'

### Steps to reproduce

```
import tensorflow as tf
import numpy as np

# normally pretrained weights, but random arrays used for brevity
weights = np.random.rand(1000, 500).astype(np.float32)
biases = np.random.rand(500).astype(np.float32)

x = tf.placeholder(tf.float32, [None, 1000], name='input')

W = tf.Variable(weights)
b = tf.Variable(biases)

fc = tf.matmul(x, W, name='fc1')
fc = tf.nn.bias_add(fc, b)
y_pred = tf.nn.softmax(fc, name='output')

# saving model
sess = tf.Session()
init_op = tf.initialize_all_variables()
sess.run(init_op)
saver = tf.train.Saver()
saver.save(sess, "model")
```

**Comment by andydavis1** [comment]
Looking at tensorflow/tensorflow/core/protobuf/meta_graph.proto, it's clear that the meta graph proto stores the entire graph def (in addition to the meta information). This is why the file is >= model file size.
This was done for use cases where they wanted to package the GraphDef and meta info into one blob.
If this does not fit your use case, you can configure saver.py to not produce the meta files.

**Comment by SimsGautam** [comment]
If I run this snippet instead of the one earlier, then `model` is 2.0M, but `model.meta` is 8.0K. My question regards why running the earlier code (when weights/biases were initialized with a numpy array) result in both `model` and `model.meta` size to be 2.0M, whereas that's not the case here.

```
import tensorflow as tf
import numpy as np

x = tf.placeholder(tf.float32, [None, 1000], name='input')

W = tf.Variable(tf.random_normal([1000,500]))
b = tf.Variable(tf.random_normal([500]))

fc = tf.matmul(x, W, name='fc1')
fc = tf.nn.bias_add(fc, b)
y_pred = tf.nn.softmax(fc, name='output')

# saving model
sess = tf.Session()
init_op = tf.initialize_all_variables()
sess.run(init_op)
saver = tf.train.Saver()
saver.save(sess, "model")
```

**Comment by andydavis1** [comment]
My guess here is that in your first example (where you initialize the variables from the output of numpy random), that this forces the GraphDef to have a large Constant tensor nodes (to contain the 2MB of random data needed to initialize the Variables). For the second case, it does not need to "inline" the Variable initialization data into the graph, because this data is generated when the graph is run.

**Comment by SimsGautam** [comment]
Ah, thanks. Do you happen to know a simple way to initialize the weight/bias variables with a numpy array while not forcing the GraphDef to have large Constant tensor nodes?

**Comment by andydavis1** [comment]
You can try using a placeholder and feed_dict. Here is an example courtesy of @mrry:
 
>>> bigarray = np.zeros((1024, 1024, 1024), dtype=np.float32)
>>> p = tf.placeholder(tf.float32, shape=bigarray.shape)
>>> v = tf.Variable(p)
>>> sess = tf.Session()
>>> sess.run(tf.initialize_all_variables(), feed_dict={p: bigarray})
>>> sess.run(tf.reduce_sum(v))
