### ISSUE TITLE
tf.py_function in tf.data.Dataset pipeline doesn't work with TPUEstimator

### ISSUE THREAD

**Issue by sharvil** [tensorflow/tensorflow#30818]
Environment is Google Colab with TPU runtime.

**Describe the current behavior**
I have an input pipeline that contains tf.py_function as one of its processing steps when training a model with TPUEstimator. When I run the code, I get the following error:

```
No registered 'EagerPyFunc' OpKernel for CPU devices compatible with node {{node EagerPyFunc}}
	.  Registered:  <no registered kernels>

	 [[EagerPyFunc]]
	 [[input_pipeline_task0/MakeIterator]]
```

According to the documentation (https://www.tensorflow.org/guide/using_tpu) "The input pipeline generated by your input_fn is run on CPU." Running the same input code with a standard Estimator on CPU/GPU works just fine. Manually placing the Dataset + all processing steps on the CPU with `tf.device('/cpu:0')` also fails with the same error when training with TPUEstimator.

**Describe the expected behavior**
I should be able to run Python code on the CPU as part of my input pipeline when training on TPUs.

**Code to reproduce the issue**
https://colab.research.google.com/drive/15KuVkukIWdN753ffNjY6jVzT1gyhsBRQ

The notebook linked above is nearly identical to https://colab.research.google.com/github/tensorflow/tpu/blob/master/tools/colab/shakespeare_with_tpuestimator.ipynb. I've just added the following line to the Training Data code cell:

```idx = tf.py_function(lambda x: x, [idx], tf.int32)```

**Comment by ravikyram** [comment]
Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version. Also, did you compile from source or install a binary?

If you are unclear what to include see the issue template displayed in the [Github](https://github.com/tensorflow/tensorflow/issues/new/choose) new issue template.

We ask for this in the issue submission template, because it is really difficult to help without that information. Thanks!

**Comment by sharvil** [comment]
I shared a Google Colab notebook that reproduces the issue... so operating system, architecture, source vs. binary, etc. questions in the new issue template are not relevant. I'm using the default TF version which, at the time of writing, is 1.14.0.

Are you unable to reproduce the issue after running the Colab notebook?

**Comment by jhseu** [comment]
Unfortunately this will be complicated with TPUEstimator since:

- This requires a Python interpreter.
- We run the input pipeline on the TPU VM, which doesn't have an interpreter.
- The Python VM isn't included in the TensorFlow graph.

**Comment by sharvil** [comment]
Is the eventual goal to run the input pipeline on CPU with TPUEstimator or are the docs incorrect? I need to decide if I should re-think my use of TPUs / structure of my input pipeline or if I should wait for the TPUEstimator implementation to catch up to the docs.

**Comment by jhseu** [comment]
The input pipeline does run on CPU, but on the CPU of the TPU VM. Essentially you're connecting to a remote host to run your model. If you can express your input pipeline in terms of tf.data but without the py_func, then it should work.

**Comment by sharvil** [comment]
Gotcha, thanks for the input.

Do you anticipate having a Python VM running in the TPU VM at some point in the future? The input pipeline often needs much more flexibility than the model itself and it's difficult (if not impossible) at times to express a pipeline in terms of _pure_ TF ops.

In my case, I've hacked up our input pipeline to avoid tf.py_function (yay!) but the result is pretty gnarly.

**Comment by jhseu** [comment]
Yeah, in the new TPUStrategy API, we do already support this, and additionally it offers flexibility for the user to do step-at-a-time training and feed in whatever Python numpy arrays they want. It's a bit new, so we'll start documenting it soon.

**Comment by capilano** [comment]
@jhseu Does the distribute strategy support using tf.py_func outside the input pipeline. For instance, is it possible to apply python logic(using pure python, numpy,opencv etc)  to the output tensor of some layer in a model while training.

**Comment by Alex-Fabbri** [comment]
@jhseu with the TPUStrategy API I am still getting the same error as described in the initial issue. I am running on a Google Cloud v3-8, TF version 2.1.0-dev20200102, following [these instructions](https://github.com/tensorflow/models/tree/master/official/transformer#using-tpus). It works fine as is, but if I add the following two lines after [line 86](https://github.com/tensorflow/models/blob/master/official/transformer/v2/data_pipeline.py#L86) to use py_functions: 

```
inputs = tf.py_function(lambda x: x, [inputs], tf.int64)
targets = tf.py_function(lambda x: x, [targets], tf.int64
```

then I get this error: 
```
tensorflow.python.framework.errors_impl.InvalidArgumentError: No OpKernel was registered to support Op 'EagerPyFunc' used by {{node EagerPyFunc}} with these attrs: [Tout=[DT_INT64], is_async=false, Tin=[DT_INT64], _xla_inferred_shapes=[<unknown>], token="pyfunc_0"]
Registered devices: [CPU, TPU, TPU_SYSTEM, XLA_CPU]
Registered kernels:
  <no registered kernels>

         [[EagerPyFunc]]
```

I will try to write my pipeline in terms of tf.data, but if you had any updates on using tf.py_function in this context, that would be great.

**Comment by samkleeman1** [comment]
I have the same problem as above, any updates?

**Comment by capilano** [comment]
@samkleeman1 Sorry, guys I was away for a long while. Why are you using tensorflow estimators, still? Best is to use TF 2.0

**Comment by capilano** [comment]
My experience is a bit dated but you cannot use tf.py_func, The TPU is a standalone unit and any interaction with python needs to be done carefully. As far as I can tell, you need to implement using tensorflow functions, all operations that fit onto the TPU. You can make a host call but If I were you, I would try and minimize host calls and rather use the generic code that Tensorflow provides as a starting point. I have used estimators too, but I think everyone is moving on to TF 2.0

**Comment by fengyang0317** [comment]
> Yeah, in the new TPUStrategy API, we do already support this, and additionally it offers flexibility for the user to do step-at-a-time training and feed in whatever Python numpy arrays they want. It's a bit new, so we'll start documenting it soon.

@jhseu Is there any updates? I tried to use tf.py_function inside dataset.map and still gets an error on TPU.

**Comment by Santosh-Gupta** [comment]
Have you tried with tf 2.3.0 nightly?

**Comment by fengyang0317** [comment]
tf 2.3.0 does not work either.

**Comment by wmcnally** [comment]
Any update on this? Perhaps it was fixed in tf 2.3.1?

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.

**Comment by ameyparanjape** [comment]
Is there any way out to this? I am trying to train EfficientDet-D1 on colab TPUs and running into this.
