### ISSUE TITLE
Feedback on Tensorflow 2.0 beta - documentation issues?

### ISSUE THREAD

**Issue by emrul** [tensorflow/tensorflow#30815]
Hi,

Please accept the following as feedback on my experience of Tensorflow 2.0 (beta):
1. Read the [migration guide](https://www.tensorflow.org/beta/guide/migration_guide) and figured I would give it a go.
2. Installed without issues on my Mac Conda environment.  This was to be the highlight of my successes.
3. The [documentation site](https://www.tensorflow.org/versions/r2.0/api_docs/python/tf) isn't searchable by version and given the frequency and amount of change here it would be nice to find a way to locate where various things have moved to.
4.  By way of example, PhasedLSTMCell, I knew the contrib module is gone in 2.0 but its still in the GitHub 2.0 branch which is misleading.  Further misleading is the comments [here](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/rnn/__init__.py): 
> Created in contrib, eventual plans to move to core.

No indication of where one might currently find it.
5. Figured it might be in in [Addons](https://github.com/tensorflow/addons) but no luck there.
6. I wanted to use tf.keras for the first time.  Maybe its my Pip/Conda environment but no matter what I did I could not get it to import unless I did import tensorflow._python._keras.  Did I miss this in the docs because I swear I didn't read it anywhere.  
After some more poking around I decided I had enough exposure to 2.0 and went back to 1.14 - it did give me some minutes of excitement.

However, I would love 2.0 to be speedily and widely adopted.  The API looks a lot cleaner (from what I read of it, I didn't get to use any ultimately) and I think some improvements around how the documentation is accessible would help uptake.  I'm willing to contribute to help this along if I can.

**Comment by jvishnuvardhan** [comment]
@emrul Just few questions and pointers on docs.

Item (3) : What do you mean by `3. The documentation site isn't searchable by version`?. On the page you listed, you can select any TF version (For Ex. TF1.12) from the dropdown of `API`.  You could see detailed release notes from [here](https://github.com/tensorflow/tensorflow/releases).

Item (4): Regarding `contrib module is gone in 2.0`, contrib is removed from TF2.0 but it is still part of TF1.x. The link you provided points to `master` not  `2.0`. PhasedLSTMCell you can see it [here](https://github.com/tensorflow/tensorflow/blob/r1.14/tensorflow/contrib/rnn/python/ops/rnn_cell.py#L1915-L2062).

Please feel free to contribute through PRs to update documentation and code. Thanks!

**Comment by Saduf2019** [comment]
@emrul 
Is this still an issue

**Comment by jvishnuvardhan** [comment]
I am closing this issue as it is a stale issue. Thanks!
