### ISSUE TITLE
how can I create a model without tf.keras in tf2.0

### ISSUE THREAD

**Issue by gjxcq** [tensorflow/tensorflow#30829]
if I use tf2.0 and not use tf.keras, which advanced api(like tf.layers.* or tf.contrib.* in  tf1.x ) I can use for creating model

**Comment by gadagashwini** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged//tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.
