### ISSUE TITLE
Tensorflow 2.0 - Build From Source not creating Python Wrappers such as _pywrap_tensorflow_internal.lib

### ISSUE THREAD

**Issue by oracle3001** [tensorflow/tensorflow#30839]
**System information**
- OS : Windows 10
- TensorFlow installed from : source 
- TensorFlow : 2.0.0
- Python version : 3.7.3
- Bazel version (if compiling from source): 0.25.2
- GCC/Compiler version (if compiling from source): VS2017
- CUDA/cuDNN version: 10.0
- GPU model and memory: Nvidia 960m

When building tensorflow v1.14 from source, using configure.py script then building the resulting bazel --config=opt, in the bazel-bin/tensorflow output directory, it creates a /python directory containing python wrapper libraries such as _pywrap_tensorflow_internal.lib (which is required when creating custom ops).

Following the same procedure with v2.0.0, it doesn't produce this (using exactly the same config settings) i.e. for whatever reason the build script is now building the python wrappers libraries.

The source code is in the same location as for v1.14, and checking the prebuilt version that can be installed via pip, this directory and associated library are deployed.

Is an additional flag now required to create this additional set of python wrapper libraries?

**Comment by ravikyram** [comment]
Just to verify did you get chance to follow instructions from [TensorFlow](https://www.tensorflow.org/install/source_windows) website .Please, let us know. Thanks!

**Comment by oracle3001** [comment]
Yes, that is the guide I followed. As I say, with v1.14, it builds everything as expected, following the same procedure with v2.0.0, it builds without errors with the main libraries builts, however the directory that usually contains things such as _pywrap_tensorflow_internal.lib has not been created.

**Comment by gunan** [comment]
@meteorcloudy I think he first looked into creating custom ops with TF bazel build.

**Comment by meteorcloudy** [comment]
I never tried to build TensorFlow 2.0 on Windows, is there any guide?

**Comment by gunan** [comment]
The C++ aspects of the build are identical.
As far as I know, you just need to feed the `--config=v2` flag to the bazel command. @goldiegadde to confirm.

**Comment by jvishnuvardhan** [comment]
@oracle3001 was this resolved by following @gunan suggestion? Please close the issue if it was resolved already. Thanks!

**Comment by oracle3001** [comment]
No, this did not resolve the issue.

**Comment by meteorcloudy** [comment]
@oracle3001 I just verified again, `_pywrap_tensorflow_internal.lib` does exist.
I'm building with Bazel 0.26.1 + TF@r2.0 branch
```
bazel build --config=opt --config=v2 tensorflow/tools/pip_package:build_pip_package
bazel-bin/tensorflow/tools/pip_package/build_pip_package ./output
```
When I open the whl file `tensorflow-2.0.0-cp36-cp36m-win_amd64.whl` as a zip file, it exists at `C:\Users\pcloudy\Desktop\tensorflow-2.0.0-cp36-cp36m-win_amd64.zip\tensorflow_core\python\_pywrap_tensorflow_internal.lib`

**Comment by oracle3001** [comment]
I will try with those parameters. With v1.14, the following build arguments resulted in the the python directory i.e _pywrap_tensorflow_internal.lib also getting built in the output.

`bazel build --config=opt //tensorflow:libtensorflow.so `

**Comment by mihaimaruseac** [comment]
Please use the `r1.15`, `r2.0` or the `master` branches instead of `r1.14` as that branch is in an unstable state, unfortunately.

**Comment by ravikyram** [comment]
@oracle3001 
Any update on this issue please. Thanks!

**Comment by oracle3001** [comment]
I have just retried with the very latest code from Github and no it all builds successfully but the _pywrap_tensorflow_internal.lib isn't built.

**Comment by mohantym** [comment]
Hi @oracle3001 !Could you please check on latest stable version of tf 2.6 and   the instructions at this [link ](https://www.tensorflow.org/install/source_windows) for installing Tensorflow in windows from Source. let us know if this is still an issue.Thanks!
