### ISSUE TITLE
The model of tf1 cannot be converted to a model of tflite in tf2

### ISSUE THREAD

**Issue by theangels** [tensorflow/tensorflow#30830]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 16.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: No
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.0.0-beta
- Python version: 3.6.8
- Bazel version (if compiling from source): No
- GCC/Compiler version (if compiling from source): No
- CUDA/cuDNN version: 10
- GPU model and memory: GTX-1080Ti

**Describe the current behavior**
![微信图片_20190718111406](https://user-images.githubusercontent.com/11308780/61426503-2df33400-a94d-11e9-9a56-226c1e6c7a06.png)

**Describe the expected behavior**
Convent successfully.

**Code to reproduce the issue**
``` python
import tensorflow as tf

modelPath = 'saved/old-model.h5'
model = tf.keras.models.load_model(modelPath, compile=False)
converter = tf.lite.TFLiteConverter.from_keras_model(
    model
)
tflite_model = converter.convert()
open("converted_model.tflite", "wb").write(tflite_model)
```

**Other info / logs**
Here are the model link
[model.h5](https://drive.google.com/file/d/1nwb0IOh6UVwJmV0QJgsiYawCKT0RVpxI/view?usp=sharing)

**Comment by gargn** [comment]
I ran the code you provided with the model you provided on the `tf-nightly-2.0-preview` (which is a more recent beta) and I was able to convert the model successfully. For context I ran `pip install tf-nightly-2.0-preview` and have version `2.0.0.dev20190719` installed.

**Comment by ravikyram** [comment]
@theangels 
Did you get a chance to check the comments by @gargn .Thanks!

**Comment by theangels** [comment]
@gargn 
I'm sorry for reply late, still failed, and my TensorFlow's version is v2.0.0-beta0-16-g1d91213fe7 2.0.0-beta1

**Comment by gargn** [comment]
You can install it with `pip install tf-nightly-gpu-2.0-preview`. I tested on last night's GPU nightly (`2.0.0.dev20190725`) and the code seems to work there as well.

**Comment by theangels** [comment]
I update the tf2.0 version but still not work.

![snipaste20190726_091755](https://user-images.githubusercontent.com/11308780/61919018-5fd84c00-af86-11e9-8171-6b920d559197.png)

**Comment by jvishnuvardhan** [comment]
@theangels I ran your code and `old-model.h5` and everything works as expected in Google colab. Please find the [gist here](https://colab.sandbox.google.com/gist/jvishnuvardhan/28f5e193e4b94804fc7cb4e1fde942fa/tf30830.ipynb).

I think there is some installation issue. Did you follow the instructions listed [here](https://www.tensorflow.org/install) for installing `TF2.0`. First uninstall current version, restart computer and install new `TF2.0` by following the instructions on TF website. Thanks!

**Comment by jvishnuvardhan** [comment]
@theangels Did you had time to review my shared gist? Thanks!

**Comment by theangels** [comment]
@jvishnuvardhan Sorry for reply late, I try your shared gist and it works, thank you!
