### ISSUE TITLE
Cannot convert from tensorflow to tensorflow lite

### ISSUE THREAD

**Issue by michisaak** [tensorflow/tensorflow#30832]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Debian 9
- TensorFlow installed from (source or binary): From Conda
- TensorFlow version (or github SHA if from source): 1.14.0

**Text output from tflite_convert**

```
Some of the operators in the model are not supported by the standard TensorFlow Lite runtime. If those are native TensorFlow operators, you might be able to use the extended runtime by passing --enable_select_tf_ops, or by setting target_ops=TFLITE_BUILTINS,SELECT_TF_OPS when calling tf.lite.TFLiteConverter(). Otherwise, if you have a custom implementation for them you can disable this error with --allow_custom_ops, or by setting allow_custom_ops=True when calling tf.lite.TFLiteConverter(). Here is a list of builtin operators you are using: ADD, CAST, CONCATENATION, CONV_2D, DEPTHWISE_CONV_2D, EQUAL, EXP, EXPAND_DIMS, FILL, GATHER, GREATER, GREATER_EQUAL, LESS, LOGICAL_OR, LOGISTIC, MAXIMUM, MINIMUM, MUL, PACK, PAD, RANGE, RESHAPE, RESIZE_BILINEAR, SELECT, SHAPE, SLICE, SPLIT, SQUEEZE, STRIDED_SLICE, SUB, SUM, TOPK_V2, TRANSPOSE, UNPACK, WHERE. Here is a list of operators for which you will need custom implementations: DecodeBmp, DecodeGif, DecodeJpeg, DecodePng, DecodeRaw, Merge, NonMaxSuppressionV3, ParseSingleExample, Substr, Switch.
```

GraphDef :  
https://github.com/michisaak/ObjectDetection/blob/master/saved_model.pb

**Logs**
Traceback (most recent call last):
  File "/home/michaili/anaconda2/envs/retrain/bin/toco_from_protos", line 10, in <module>
    sys.exit(main())
  File "/home/michaili/anaconda2/envs/retrain/lib/python3.5/site-packages/tensorflow/lite/toco/python/toco_from_protos.py", line 59, in main
    app.run(main=execute, argv=[sys.argv[0]] + unparsed)
  File "/home/michaili/anaconda2/envs/retrain/lib/python3.5/site-packages/tensorflow/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/home/michaili/anaconda2/envs/retrain/lib/python3.5/site-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/home/michaili/anaconda2/envs/retrain/lib/python3.5/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "/home/michaili/anaconda2/envs/retrain/lib/python3.5/site-packages/tensorflow/lite/toco/python/toco_from_protos.py", line 33, in execute
    output_str = tensorflow_wrap_toco.TocoConvert(model_str, toco_str, input_str)
Exception: We are continually in the process of adding support to TensorFlow Lite for more ops. It would be helpful if you could inform us of how this conversion went by opening a github issue at https://github.com/tensorflow/tensorflow/issues/new?template=40-tflite-op-request.md

**Comment by gadagashwini** [comment]
@michisaak Please provide any commands you followed to convert Tflite model.Thanks!

**Comment by ymodak** [comment]
https://github.com/tensorflow/tensorflow/issues/30185#issuecomment-506833929
