### ISSUE TITLE
Unable to quantize buffer or min/max value for input 1 in op MUL in subgraph 0, node: 8

### ISSUE THREAD

**Issue by paulbauriegel** [tensorflow/tensorflow#30838]
**System information**
- OS: Linux Ubuntu 19.04
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): v1.14.0-rc1-22-gaf24dc9 1.14.0
- Python version: 3.7.3
- CUDA/cuDNN version: 10.0.130/ 7.4.1
- GPU model and memory: Tesla V100-SXM2-16GB

**Describe the current behavior**
Running the official tutorial on post training quantization:
https://www.tensorflow.org/lite/performance/post_training_quantization
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/tutorials/post_training_quant.ipynb

results in following error message:
`Unable to quantize buffer or min/max value for input 1 in op MUL in subgraph 0, node: 8`

**Describe the expected behavior**
No error

**Code to reproduce the issue**
Run the attached notebook with attached graph.pb and csv:
https://drive.google.com/open?id=1JI45QqwhgR2v4i8GCShkH5eod0TTB7FI

Download YTF Dataset as from here: https://www.cs.tau.ac.il/~wolf/ytfaces/

**Comment by mark-arm** [comment]
I believe this is triggered Mul takes a constant input. In the attached graph this is found here:
![image](https://user-images.githubusercontent.com/35263153/64412735-5f0bfd00-d090-11e9-8ab8-7dbce93e78b7.png)

It can also be reproduced more simply with:

```
import numpy as np
import tensorflow as tf

a = tf.placeholder(dtype=tf.float32, shape=[1])

add = a + 1.
mul = a * 2.

def dataset_gen():
    yield [np.array([1.], dtype=np.float32)]

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())

    converter = tf.lite.TFLiteConverter.from_session(sess, [a], [add, mul])
    converter.optimizations = [ tf.lite.Optimize.DEFAULT ]
    converter.representative_dataset = dataset_gen
    tflite_quant_model = converter.convert()

with open('add_mul_const.tflite', 'wb') as f:
    f.write(tflite_quant_model)
```

This fails with the error:

```Traceback (most recent call last):
  File "add_mul_const.py", line 18, in <module>
    tflite_quant_model = converter.convert()
  File "/Users/maroco01/anaconda3/envs/tf-pip/lib/python3.6/site-packages/tensorflow/lite/python/lite.py", line 908, in convert
    inference_output_type)
  File "/Users/maroco01/anaconda3/envs/tf-pip/lib/python3.6/site-packages/tensorflow/lite/python/lite.py", line 200, in _calibrate_quantize_model
    inference_output_type, allow_float)
  File "/Users/maroco01/anaconda3/envs/tf-pip/lib/python3.6/site-packages/tensorflow/lite/python/optimize/calibrator.py", line 78, in calibrate_and_quantize
    np.dtype(output_type.as_numpy_dtype()).num, allow_float)
  File "/Users/maroco01/anaconda3/envs/tf-pip/lib/python3.6/site-packages/tensorflow/lite/python/optimize/tensorflow_lite_wrap_calibration_wrapper.py", line 115, in QuantizeModel
    return _tensorflow_lite_wrap_calibration_wrapper.CalibrationWrapper_QuantizeModel(self, input_py_type, output_py_type, allow_float)
RuntimeError: Unable to quantize buffer or min/max value for input 1 in op ADD in subgraph 0, node: 0```

**Comment by fangyu1006** [comment]
Meet the same problem. Any solution?

**Comment by MohamedNourArm** [comment]
This issue was fixed in the master branch, seemingly by this commit: https://github.com/tensorflow/tensorflow/commit/a372bb0e9d77b3532eec1bf24a44bbf342673968#diff-69178ece8d1001b2ef7f9b329e9a525b

**Comment by liyunlu0618** [comment]
Closing per last comment.
