### ISSUE TITLE
 mismatch in the description of BatchDot and TensorFlow's implementation. 

### ISSUE THREAD

**Issue by zachmayer** [tensorflow/tensorflow#30846]
## URL(s) with the issue:
https://www.tensorflow.org/api_docs/python/tf/keras/backend/batch_dot

## Description of issue (what needs changing):
I raised [an issue on the plaidML repo](https://github.com/plaidml/plaidml/issues/358), and after some back and forth we determined the documentation for BatchDot doesn't quite match the actual implementation in the tensorflow code.

### Clear description
A BatchDot with x.shape=(1,2,6,2) and y.shape=(1,2,2,3) and axes = (3, 1)has an output shape of (1,2,6,3)) whereas by the TF definition for output shape "A tensor with shape equal to the concatenation of x's shape (less the dimension that was summed over) and y's shape (less the batch dimension and the dimension that was summed over). If the final rank is 1, we reshape it to (batch_size, 1)." sounds like it should have an output shape of (1,2,6,2,3).

### Submit a pull request?
I am not planning to submit a PR at this time, but I may do it later

**Comment by dgkutnic** [comment]
To further elaborate on this issue: there also seems to be output shape mismatches between the TensorFlow and Theano backend implementations of `BatchDot`. Theano's implementation seems to be much closer to the documented definition of `BatchDot` than TensorFlow.

Could we either change the documentation to more clearly describe TensorFlow's engineering decisions behind `BatchDot` or modify the TensorFlow implementation of `BatchDot` to more closely match what is described in the documentation?

**Comment by Saduf2019** [comment]
Moving this to close status as its taken care in later version.

**Comment by zachmayer** [comment]
Can you link to the version where this is taken care of, so I can check that my code works now?  Thanks!

**Comment by Saduf2019** [comment]
@zachmayer 
Apologies for the confusion, can you please provide with stand alone code to support this issue and replicate it.

**Comment by jvishnuvardhan** [comment]
@zachmayer Is this still an issue for you? Can you please share a simple standalone code to reproduce the issue? I have checked your code from the other thread and attaching [here](https://colab.research.google.com/gist/jvishnuvardhan/d11127b6e9bf3024c469daae969015ff/untitled979.ipynb)  as a gist for our reference. Thanks!

**Comment by zachmayer** [comment]
@jvishnuvardhan I was able to fix the issue by calling `.to_numpy()` on my target for training.  I think it was causing a problem because it was a pandas series.

Let me try to make a reproducible example.

**Comment by zachmayer** [comment]
From my ticket in the other repo: https://github.com/plaidml/plaidml/issues/358

1. Make sure you are using the plaidml backend for keras
2. Run:
```from keras.layers import Input, Dense, Dot, Reshape, Flatten
from keras.models import Model

model_in = Input((10,), name='input')
model_out = model_in
model_out = Reshape((-1, 1), name='reshape')(model_out)
model_out = Dot(axes=2, name='dot')([model_out, model_out])
model_out = Flatten(name='flatten')(model_out)
model = Model(model_in, model_out)
model.summary()
model.compile()```

I'll see if the plaidml devs will update their code, now that tensorflow is the only backend supported by kers

**Comment by jvishnuvardhan** [comment]
@zachmayer If this is an issue with `plaidml` backend, then this issue should be opened in their repo. Please let us know if there is any bug with `tensorflow` or `tf.keras`, then please provide a simple standalone code to reproduce the issue. Thanks!

**Comment by zachmayer** [comment]
yeah this is an issue on plaidml's end.  They tried to blame it on tensorflow lol.

Thanks for your attention on this and sorry for the noise!
