### ISSUE TITLE
cannot detect communication between clusters when CollectiveAllReduceStrategy 

### ISSUE THREAD

**Issue by jiahuigeng** [tensorflow/tensorflow#30841]
tensorflow 1.12
CUDA 10
Ubuntu 16.04

Here is the part of code in the main script:
  strategy=tf.contrib.distribute.MirroredStrategy(num_gpus=FLAGS.n_gpus)#devices=["/gpu:0", "/gpu:1"]
  if FLAGS.strategy=="ps":
    os.environ['TF_CONFIG'] = json.dumps({
        'cluster': {
            "worker": ["10.60.131.148:8081", "10.60.131.149:8082"],
            "ps": ["10.60.131.150:8083"]
        },
        'task': {'type': FLAGS.type, 'index': FLAGS.index}
    })
    strategy = tf.contrib.distribute.ParameterServerStrategy(num_gpus_per_worker=FLAGS.n_gpus)
  elif FLAGS.strategy=="collective":
    os.environ['TF_CONFIG'] = json.dumps({
        'cluster': {
            "worker": ["10.60.131.148:8888","10.60.131.149:8888", "10.60.131.150:8888"],
        },
        'task': {'type': FLAGS.type, 'index': FLAGS.index}
    })
    strategy = tf.contrib.distribute.CollectiveAllReduceStrategy(num_gpus_per_worker=FLAGS.n_gpus)

  run_config = tf.estimator.RunConfig(
      model_dir=FLAGS.output_dir,
      save_checkpoints_steps=FLAGS.save_checkpoints_steps,
      train_distribute=strategy
      )
  estimator = tf.estimator.Estimator(
      model_fn=model_fn,
      config=run_config,
      params={"batch_size": FLAGS.train_batch_size}
  )

  if FLAGS.do_train:
    tf.logging.info("***** Running training *****")
    tf.logging.info("  Batch size = %d", FLAGS.train_batch_size)
    train_input_fn = input_fn_builder(
        input_files=input_files,
        max_seq_length=FLAGS.max_seq_length,
        max_predictions_per_seq=FLAGS.max_predictions_per_seq,
        is_training=True)
    estimator.train(input_fn=train_input_fn, max_steps=FLAGS.num_train_steps)

I have three machines each has 3 gpus.
When I run CollectiveAllReduceStrategy, set type as 'worker' and index, the num of gpus for each worker as 3.I run the script independently on three clusters,  and use iftop -n to monitor the network, I did notice any communication between the clusters.
No errors, and from the log I did't know if it now runs the correctly way. Or just single machine 3 gpus, running independently.

Any suggestions or reference links?

**Comment by ymodak** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow-tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.
