### ISSUE TITLE
ImportError: No module named tensorflow

### ISSUE THREAD

**Issue by harsham05** [tensorflow/tensorflow#3084]
**I followed the steps for Anaconda installation for the CPU install of Tensorflow. (r0.9)**

**Despite installation completing successfully in my conda environment on CentOS, I am unable to import tensorflow**

### Environment info
Operating System:  **CentOS 7.2.1511**
                                **Python 2.7.11 Anaconda 4.0.0 (64-bit)**

If installed from binary pip package, provide:

1. Which pip package you installed.
```
# Ubuntu/Linux 64-bit, CPU only, Python 2.7
$ export TF_BINARY_URL=https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.9.0-cp27-none-linux_x86_64.whl
```
2. The output from `python -c "import tensorflow; print(tensorflow.__version__)"`.
```
(tensorflow)[hmanjunatha@curran ~]$ python -c "import tensorflow; print(tensorflow.__version__)"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named tensorflow
```

### What have you tried?
1. Searched on Google, Stackoverflow, but to no avail
2. **OS X installation of tensorflow worked perfectly**

**Comment by harsham05** [comment]
Installation
```
(tensorflow)[hmanjunatha@curran ~]$ pip install --upgrade $TF_BINARY_URL
Collecting tensorflow==0.9.0 from https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.9.0-cp27-none-linux_x86_64.whl
  Downloading https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.9.0-cp27-none-linux_x86_64.whl (27.6MB)
    100% |████████████████████████████████| 27.6MB 39kB/s 
Collecting numpy>=1.8.2 (from tensorflow==0.9.0)
  Using cached numpy-1.11.1-cp27-cp27mu-manylinux1_x86_64.whl
Requirement already up-to-date: six>=1.10.0 in ./anaconda2/envs/tensorflow/lib/python2.7/site-packages (from tensorflow==0.9.0)
Collecting protobuf==3.0.0b2 (from tensorflow==0.9.0)
  Using cached protobuf-3.0.0b2-py2.py3-none-any.whl
Requirement already up-to-date: wheel in ./anaconda2/envs/tensorflow/lib/python2.7/site-packages (from tensorflow==0.9.0)
Collecting setuptools (from protobuf==3.0.0b2->tensorflow==0.9.0)
  Using cached setuptools-23.1.0-py2.py3-none-any.whl
Installing collected packages: numpy, setuptools, protobuf, tensorflow
  Found existing installation: numpy 1.11.0
    Uninstalling numpy-1.11.0:
      Successfully uninstalled numpy-1.11.0
  Found existing installation: setuptools 23.0.0
Cannot remove entries from nonexistent file /home/hmanjunatha/anaconda2/envs/tensorflow/lib/python2.7/site-packages/easy-install.pth
(tensorflow)[hmanjunatha@curran ~]$ 
```

**Comment by thammegowda** [comment]
Paste output of  `python --version`

**Comment by harsham05** [comment]
@thammegowda 
Python 2.7.11 Anaconda 4.0.0 (64-bit)

**Comment by thammegowda** [comment]
@harsham05  Looks good. I suspect anaconda and its PYTHONPATH

**Comment by harsham05** [comment]
Looks like for CentOS, tensorflow needs to be built from source.

**Comment by rob-rowe** [comment]
I am seeing the same problem with Ubuntu 14.04 and Anaconda. I have tried the install with python 2.7, 3.4 and 3.5, and all give the same error: ImportError: No module named tensorflow

**Comment by rob-rowe** [comment]
Same resolution as @harsham05 : build from source worked fine.

**Comment by harsham05** [comment]
@rob-rowe 👍

**Comment by AlvinChen13** [comment]
r0.9 works well, after I upgrade to r0.10, encounter the same issue, and my tensorflow built from source.

**Comment by raviolli** [comment]
I am r1.3 and have encounters the similar issue (built from source). I got a whl but can't import. (centOS)
