### ISSUE TITLE
change protobuf version to 3.8 then build failed

### ISSUE THREAD

**Issue by qiangyang870307** [tensorflow/tensorflow#30842]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 14.04):
- GCC 4.8.4
- build CPU only

**Describe the problem**
when build tensorflow r1.5, upgrade protobuf version by changing proto buf urls, sha256,strip prefix value . Just  As followed:
        "http://mirror.tensorflow.org/github.com/protocolbuffers/protobuf/archive/310ba5ee72661c081129eb878c1bbcec936b20f0.tar.gz",        "https://github.com/protocolbuffers/protobuf/archive/310ba5ee72661c081129eb878c1bbcec936b20f0.tar.gz",
PROTOBUF_SHA256 = "b9e92f9af8819bbbc514e2902aec860415b70209f31dfc8c4fa72515a5df9d59"
 PROTOBUF_STRIP_PREFIX = "protobuf-310ba5ee72661c081129eb878c1bbcec936b20f0"

**build commnd**:
bazel build //tensorflow:libtensorflow_cc.so

the error message is :
---------------------------
ERROR: Skipping '//tensorflow:libtensorflow_cc.so': error loading package 'tensorflow': Extension file not found. Unable to load package for '@bazel_skylib//lib:versions.bzl': The repository could not be resolved
WARNING: Target pattern parsing failed.
ERROR: error loading package 'tensorflow': Extension file not found. Unable to load package for '@bazel_skylib//lib:versions.bzl': The repository could not be resolved
INFO: Elapsed time: 0.652s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
    currently loading: tensorflow
-------------------------

how could I fix the problem  ?

**Comment by qiangyang870307** [comment]
And  no protobuf installed in my system

**Comment by angersson** [comment]
The TF team doesn't provide build support for versions as old as r1.5, sorry. Please try [building the most recent release](https://www.tensorflow.org/install/source) instead.
