### ISSUE TITLE
Restoring Keras model fails inside a distribution strategy scope

### ISSUE THREAD

**Issue by dzhu** [tensorflow/tensorflow#30850]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): **yes**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): **Arch Linux**
- TensorFlow installed from (source or binary): **binary** (using `pip`)
- TensorFlow version (use command below): both `v1.14.0-rc1-22-gaf24dc9 1.14.0` and `v2.0.0-beta0-17-g8e423e3 2.0.0-beta1`
- Python version: **3.7.3**
- CUDA/cuDNN version: **CUDA 10.1.168-4, cuDNN 7.6.1.34-1**
- GPU model and memory: **NVIDIA Quadro P2000, 4GB**

**Describe the current behavior**
Inside a distribution strategy scope, restoring a Keras model (that has been trained at all) with `tf.keras.models.load_model` raises the exception shown below (while handling the optimizer in particular, it seems).

(Looks a bit similar to #28599 if you squint, but many details differ.)

**Describe the expected behavior**
Restoring the model should succeed.

**Code to reproduce the issue**
```python
import numpy as np, tensorflow as tf

strategy = tf.distribute.MirroredStrategy()
path = "/tmp/model.hdf5"

with strategy.scope():
    # Construct model.
    model = tf.keras.models.Sequential([tf.keras.layers.Dense(1, input_shape=(1,))])
    model.compile(optimizer=tf.keras.optimizers.SGD(), loss=tf.keras.metrics.mse)
    # Do a fit so the optimizer weights are created. Removing this lets the restore succeed.
    model.fit(np.array([[1]]), np.array([[1]]))
    # Save and attempt to restore.
    tf.keras.models.save_model(model, path)
    tf.keras.models.load_model(path)
```
**Other info / logs**
Traceback for TF 2.0 (TF 1.14 is the same except for line numbers):
```
  File ".../tensorflow/python/keras/saving/save.py", line 137, in load_model
    return hdf5_format.load_model_from_hdf5(filepath, custom_objects, compile)
  File ".../tensorflow/python/keras/saving/hdf5_format.py", line 187, in load_model_from_hdf5
    model._make_train_function()
  File ".../tensorflow/python/keras/engine/training.py", line 1974, in _make_train_function
    params=self._collected_trainable_weights, loss=self.total_loss)
  File ".../tensorflow/python/keras/optimizer_v2/optimizer_v2.py", line 491, in get_updates
    grads = self.get_gradients(loss, params)
  File ".../tensorflow/python/keras/optimizer_v2/optimizer_v2.py", line 391, in get_gradients
    grads = gradients.gradients(loss, params)
  File ".../tensorflow/python/ops/gradients_impl.py", line 158, in gradients
    unconnected_gradients)
  File ".../tensorflow/python/ops/gradients_util.py", line 543, in _GradientsHelper
    for x in xs
  File ".../tensorflow/python/ops/gradients_util.py", line 543, in <listcomp>
    for x in xs
  File ".../tensorflow/python/distribute/values.py", line 643, in handle
    raise ValueError("`handle` is not available outside the replica context"
ValueError: `handle` is not available outside the replica context or a `tf.distribute.Strategy.update()` call.
```

**Comment by guptapriya** [comment]
Hi - we don't support saving with hdf5 format. However, you can save and restore with the standard TF format - just remove the hdf5 extension from the file path. See https://www.tensorflow.org/beta/tutorials/distribute/save_and_load for more information.

**Comment by dzhu** [comment]
Unfortunately, that does not resolve the issue: it makes `save_model` fail, so that the program never even gets a chance to load the model.

_With TF 1.14:_ removing the extension still defaults to HDF5, leading to the same exception, and specifying `save_format="tf"` gives this:
```
  File ".../tensorflow/python/keras/saving/save.py", line 86, in save_model
    'Saving the model as SavedModel is not supported in TensorFlow 1.X'
NotImplementedError: Saving the model as SavedModel is not supported in TensorFlow 1.Xgraph mode. Please enable eager execution or use the "h5" save format.
```
(I don't think it would be feasible for me to use eager execution, due to external constraints.)

_With TF 2.0:_ removing the extension and specifying `save_format="tf"` both give this exception:
```
  File ".../tensorflow/python/keras/saving/save.py", line 106, in save_model
    saved_model.save(model, filepath, overwrite, include_optimizer)
  File ".../tensorflow/python/keras/saving/saved_model.py", line 1492, in save
    save_lib.save(model, filepath)
  File ".../tensorflow/python/saved_model/save.py", line 835, in save
    meta_graph_def, saveable_view, signatures)
  File ".../tensorflow/python/saved_model/save.py", line 531, in _fill_meta_graph_def
    object_map, resource_map, asset_info = saveable_view.map_resources()
  File ".../tensorflow/python/saved_model/save.py", line 252, in map_resources
    new_variable = resource_variable_ops.copy_to_graph_uninitialized(obj)
  File ".../tensorflow/python/ops/resource_variable_ops.py", line 1791, in copy_to_graph_uninitialized
    synchronization=var.synchronization,
  File ".../tensorflow/python/ops/variables.py", line 514, in synchronization
    raise NotImplementedError
NotImplementedError
```
Using `model.save` instead of `save_model` has the same issues.

Those exceptions occur even with the modified and reduced code shown below, with (1) the call to `save_model` outside the scope, as suggested by the linked document, and (2) no call to `fit` (though the same exceptions happen with `fit` present as well).
```python
import tensorflow as tf

strategy = tf.distribute.MirroredStrategy()

with strategy.scope():
    model = tf.keras.models.Sequential([tf.keras.layers.Dense(1, input_shape=(1,))])
    model.compile(optimizer=tf.keras.optimizers.SGD(), loss=tf.keras.metrics.mse)
tf.keras.models.save_model(model, "/tmp/model", save_format="tf")
```

(Side note: Though I am able to test with 2.0, a solution for 1.x would be more immediately useful for me. But any help with either version is highly appreciated, of course!)

**Comment by guptapriya** [comment]
The error you see with 2.0 has been fixed, which version of 2.0 are you testing with?

For 1.x, maybe you need to use a different API then if that one is not supported. Do you need only the weights from the trained model or do you need the graph too?

**Comment by dzhu** [comment]
For TF 2.0, I have `tf.version.VERSION == '2.0.0-beta1'` and `tf.version.GIT_VERSION == 'v2.0.0-beta0-17-g8e423e3'`. I installed via `pip install tensorflow-gpu==2.0.0b1`. That is the latest released version on both [GitHub](https://github.com/tensorflow/tensorflow/releases) and [PyPI](https://pypi.org/project/tensorflow-gpu/#history), as far as I can tell.

If I understand TF correctly, I don't need to store the graph, as I am restoring in Python with access to the same code that created the model originally. So perhaps `save_model` and `load_model` are overkill. However, I do need the state of the optimizer, which rules out using just `model.{save,load}_weights`. I also attempted to load one copy of the model outside the scope, construct another copy inside the scope, and then use `model.{get,set}_weights` and `model.optimizer.{get,set}_weights`, but it seems that the optimizer weights are not created until `model.fit` has been called with data, so that runs into issues around mismatch of expected number of weights.

In TF 1.14, I also tried `tf.contrib.saved_model.{save,load}_keras_model`, which fails in a different way:
```python
import numpy as np, tensorflow as tf

strategy = tf.distribute.MirroredStrategy()
path = "/tmp/model"

with strategy.scope():
    model = tf.keras.models.Sequential([tf.keras.layers.Dense(1, input_shape=(1,))])
    model.compile(optimizer=tf.keras.optimizers.SGD(), loss=tf.keras.metrics.mse)
    model.fit(np.array([[1]]), np.array([[1]]))
    tf.contrib.saved_model.save_keras_model(model, path)

    model = tf.contrib.saved_model.load_keras_model(path)
    model.compile(optimizer=tf.keras.optimizers.SGD(), loss=tf.keras.metrics.mse)
    model.fit(np.array([[1]]), np.array([[1]]))
```
gives this exception inside the second `model.fit`:
```
  File ".../tensorflow/python/keras/engine/training.py", line 649, in fit
    validation_freq=validation_freq)
  File ".../tensorflow/python/keras/engine/training_distributed.py", line 143, in fit_distributed
    steps_name='steps_per_epoch')
  File ".../tensorflow/python/keras/engine/training_arrays.py", line 274, in model_iteration
    batch_outs = f(actual_inputs)
  File ".../tensorflow/python/keras/backend.py", line 3292, in __call__
    run_metadata=self.run_metadata)
  File ".../tensorflow/python/client/session.py", line 1458, in __call__
    run_metadata_ptr)
tensorflow.python.framework.errors_impl.FailedPreconditionError: Error while reading resource variable dense_2/kernel from Container: localhost. This could mean that the variable was uninitialized. Not found: Resource localhost/dense_2/kernel/N10tensorflow3VarE does not exist.
         [[{{node dense_3/MatMul/ReadVariableOp}}]]
```

**Comment by guptapriya** [comment]
for 2.0, please test with the latest nightly version: https://pypi.org/project/tf-nightly-gpu-2.0-preview/

**Comment by dzhu** [comment]
Thanks, it seems to work with the 2.0 preview version.

For TF 1.14, I've found a workaround, which I'll document here for anyone else coming across this:

1. Save the model with `tf.keras.models.save_model`.
1. Load a copy of the model outside the strategy scope using `tf.keras.models.load_model`. Retrieve its weights using `model.get_weights()` and `model.optimizer.get_weights()`.
1. Create and compile a new copy of the model inside the scope, in the same way as you did the first time.
1. Now, _in a callback_, copy the loaded weights to the newly compiled model and its optimizer. The callback is key: the optimizer weights are not created before the call to `model.fit`, so the copying cannot be done in the normal flow of code, but the `on_train_begin` callback runs after the weights are created and before any training has happened.

An example of what the callback might look like:

```python
class LoadWeightsCallback(tf.keras.callbacks.Callback):
    _chief_worker_only = False

    def __init__(self, weights, optimizer_weights):
        self.weights = weights
        self.optimizer_weights = optimizer_weights

    def on_train_begin(self, logs=None):
        self.model.set_weights(self.weights)
        self.model.optimizer.set_weights(self.optimizer_weights)
```

**Comment by rishabhsahrawat** [comment]
Hi @guptapriya , I tried your suggestion of removing 'h5' extension from the file's name and then I followed tutorial on your provided line but I am receiving following error. Please suggest me if there is a way to train the model again on multiple GPUs from lastly saved model file. Thank you!
`````
  File "model_with_tfsplit.py", line 98, in <module>
    model =tf.keras.models.load_model(model_path) # Loading for retraining
  File "/home/rishabh/.local/lib/python2.7/site-packages/tensorflow_core/python/keras/saving/save.py", line 138, in load_model
    return hdf5_format.load_model_from_hdf5(filepath, custom_objects, compile)
  File "/home/rishabh/.local/lib/python2.7/site-packages/tensorflow_core/python/keras/saving/hdf5_format.py", line 187, in load_model_from_hdf5
    model._make_train_function()
  File "/home/rishabh/.local/lib/python2.7/site-packages/tensorflow_core/python/keras/engine/training.py", line 2059, in _make_train_function
    params=self._collected_trainable_weights, loss=self.total_loss)
  File "/home/rishabh/.local/lib/python2.7/site-packages/tensorflow_core/python/keras/optimizer_v2/optimizer_v2.py", line 506, in get_updates
    return [self.apply_gradients(grads_and_vars)]
  File "/home/rishabh/.local/lib/python2.7/site-packages/tensorflow_core/python/keras/optimizer_v2/optimizer_v2.py", line 438, in apply_gradients
    return distribute_ctx.get_replica_context().merge_call(
AttributeError: 'NoneType' object has no attribute 'merge_call'

**Comment by guptapriya** [comment]
Looking at the logs, it seems that the hdf5 code is still being used in the loading part? Can you use the tf format instead? (or use 2.0 which automatically uses TF format i believe?)

**Comment by rishabhsahrawat** [comment]
Hallo Priya,
thank you for your reply. I am actually using TF 2.0 latest nightly.
Although, just to be clear, do I have to save the file during initial
training without ".h5" extension? or Can I just rename the file because I
saved the model with ".h5" extension and then renamed the file for the
reloading and training which resulted in the error above.

**Comment by guptapriya** [comment]
Yes, you need to save it in tf format to begin with to be able to load back with tf format. just changing the filename later does not help.

**Comment by rishabhsahrawat** [comment]
Alright, I understand. So, there is no other way to continue training on
multiple GPUs.? The thing is my model and datasets are huge so it take many
hours to train for one epoch even. :(
I already have issues (raise this issue here on Github already) training my
model faster on 4 GPUs. Thank you for your help Priya!

**Comment by guptapriya** [comment]
@rishabhsahrawat if you only care about weights and have the model code still, you can simply load the weights into a non distributed setup first. Then copy the weights into a distributed model using set_weights. Similar to workaround proposed in https://github.com/tensorflow/tensorflow/issues/30850#issuecomment-513523828

**Comment by rishabhsahrawat** [comment]
Yes I still have the model. I will try your suggestion tomorrow morning and
will get back to you. Thank you:)

**Comment by rishabhsahrawat** [comment]
Hi @guptapriya , I tried your suggestion on which I am facing following error. 
````
ValueError: You called `set_weights(weights)` on optimizer Adam with a  weight list of length 19, but the optimizer was expecting 0 weights
`````
This is how I am applying it.

`````
model =tf.keras.models.load_model('saved_model.h5')# weight loading
model_weights = model.get_weights()
opt_weights = model.optimizer.get_weights()# optimizers weight

mirrored_strategy = tf.distribute.MirroredStrategy()
with mirrored_strategy.scope():
    <model definition including model.compile()>

class LoadWeightsCallback(tf.keras.callbacks.Callback):
    _chief_worker_only = False

    def __init__(self, weights, optimizer_weights):
        self.weights = weights
        self.optimizer_weights = optimizer_weights

    def on_train_begin(self, logs=None):
        self.model.set_weights(self.weights)
        self.model.optimizer.set_weights(self.optimizer_weights)

model.fit(train_data, epochs=20 , callbacks = [LoadWeightsCallback(model_weights, opt_weights)]
`````

If I try without loading optimizer's weight and just update layers weights, then I receive `Resource Exhausted Error`, but if I either choose only one device in `tf.distribute.MirroredStrategy(devices= ["/gpu:0"])` or just don't define the model inside `mirror_strategy.scope()` then it trains. I only have 2 Tesla T4 GPUs now but earlier when I had 4, I could train the same model on selecting 2 GPUs. I also could use all 4 GPUs but the training speed was slower on 4. There is really a lot going on in `Mirror Strategy` function. Here is my [issue](https://github.com/tensorflow/tensorflow/issues/31162) with this.

**Comment by guptapriya** [comment]
I think the optimizer weights issue is because sometimes optimizer weights are only created during the first step. So when you try to load the weights before training starts, weights have not yet been created. 
One workaround can be to just do 1 step first and then load the weights. @k-w-w do you know what could be a better alternative for loading optimizer weights ?

**Comment by darcula1993** [comment]
with official released tf 2.0, I meet the similar error even try to load the tf format model. 

tensorflow.python.framework.errors_impl.FailedPreconditionError: Error while reading resource variable dense/kernel_34381 from Container: localhost. This could mean that the variable was uninitialized. Not found: Container localhost does not
 exist. (Could not find resource: localhost/dense/kernel_34381) [Op:ReadVariableOp]

**Comment by dhinkris** [comment]
> For TF 2.0, I have `tf.version.VERSION == '2.0.0-beta1'` and `tf.version.GIT_VERSION == 'v2.0.0-beta0-17-g8e423e3'`. I installed via `pip install tensorflow-gpu==2.0.0b1`. That is the latest released version on both [GitHub](https://github.com/tensorflow/tensorflow/releases) and [PyPI](https://pypi.org/project/tensorflow-gpu/#history), as far as I can tell.
> 
> If I understand TF correctly, I don't need to store the graph, as I am restoring in Python with access to the same code that created the model originally. So perhaps `save_model` and `load_model` are overkill. However, I do need the state of the optimizer, which rules out using just `model.{save,load}_weights`. I also attempted to load one copy of the model outside the scope, construct another copy inside the scope, and then use `model.{get,set}_weights` and `model.optimizer.{get,set}_weights`, but it seems that the optimizer weights are not created until `model.fit` has been called with data, so that runs into issues around mismatch of expected number of weights.
> 
> In TF 1.14, I also tried `tf.contrib.saved_model.{save,load}_keras_model`, which fails in a different way:
> 
> ```python
> import numpy as np, tensorflow as tf
> 
> strategy = tf.distribute.MirroredStrategy()
> path = "/tmp/model"
> 
> with strategy.scope():
>     model = tf.keras.models.Sequential([tf.keras.layers.Dense(1, input_shape=(1,))])
>     model.compile(optimizer=tf.keras.optimizers.SGD(), loss=tf.keras.metrics.mse)
>     model.fit(np.array([[1]]), np.array([[1]]))
>     tf.contrib.saved_model.save_keras_model(model, path)
> 
>     model = tf.contrib.saved_model.load_keras_model(path)
>     model.compile(optimizer=tf.keras.optimizers.SGD(), loss=tf.keras.metrics.mse)
>     model.fit(np.array([[1]]), np.array([[1]]))
> ```
> 
> gives this exception inside the second `model.fit`:
> 
> ```
>   File ".../tensorflow/python/keras/engine/training.py", line 649, in fit
>     validation_freq=validation_freq)
>   File ".../tensorflow/python/keras/engine/training_distributed.py", line 143, in fit_distributed
>     steps_name='steps_per_epoch')
>   File ".../tensorflow/python/keras/engine/training_arrays.py", line 274, in model_iteration
>     batch_outs = f(actual_inputs)
>   File ".../tensorflow/python/keras/backend.py", line 3292, in __call__
>     run_metadata=self.run_metadata)
>   File ".../tensorflow/python/client/session.py", line 1458, in __call__
>     run_metadata_ptr)
> tensorflow.python.framework.errors_impl.FailedPreconditionError: Error while reading resource variable dense_2/kernel from Container: localhost. This could mean that the variable was uninitialized. Not found: Resource localhost/dense_2/kernel/N10tensorflow3VarE does not exist.
>          [[{{node dense_3/MatMul/ReadVariableOp}}]]
> ```

anyluck on resolving this?

**Comment by jmwoloso** [comment]
Same error here too

**Comment by OhnkytaBlabdey** [comment]
> Hi @guptapriya , I tried your suggestion on which I am facing following error.
> 
> ```
> ValueError: You called `set_weights(weights)` on optimizer Adam with a  weight list of length 19, but the optimizer was expecting 0 weights
> ```
> 
> This is how I am applying it.
> 
> ```
> model =tf.keras.models.load_model('saved_model.h5')# weight loading
> model_weights = model.get_weights()
> opt_weights = model.optimizer.get_weights()# optimizers weight
> 
> mirrored_strategy = tf.distribute.MirroredStrategy()
> with mirrored_strategy.scope():
>     <model definition including model.compile()>
> 
> class LoadWeightsCallback(tf.keras.callbacks.Callback):
>     _chief_worker_only = False
> 
>     def __init__(self, weights, optimizer_weights):
>         self.weights = weights
>         self.optimizer_weights = optimizer_weights
> 
>     def on_train_begin(self, logs=None):
>         self.model.set_weights(self.weights)
>         self.model.optimizer.set_weights(self.optimizer_weights)
> 
> model.fit(train_data, epochs=20 , callbacks = [LoadWeightsCallback(model_weights, opt_weights)]
> ```
> 
> If I try without loading optimizer's weight and just update layers weights, then I receive `Resource Exhausted Error`, but if I either choose only one device in `tf.distribute.MirroredStrategy(devices= ["/gpu:0"])` or just don't define the model inside `mirror_strategy.scope()` then it trains. I only have 2 Tesla T4 GPUs now but earlier when I had 4, I could train the same model on selecting 2 GPUs. I also could use all 4 GPUs but the training speed was slower on 4. There is really a lot going on in `Mirror Strategy` function. Here is my [issue](https://github.com/tensorflow/tensorflow/issues/31162) with this.

where do i get the callback `LoadWeightsCallback`
