### ISSUE TITLE
Out of Memory Issues with beam search decoder 

### ISSUE THREAD

**Issue by vineel-concat** [tensorflow/tensorflow#30854]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below): 1.13
- Python version: 3.7
- CUDA/cuDNN version: 10/7.66
- GPU model and memory: v100 and 16GB

**Describe the current behaviour**
I am trying to implement a beam search decoder for a project. Currently, I am following the TensorFlow tutorial for neural machine translation from this link 
[tensorflow tutorial](https://github.com/tensorflow/tensorflow/blob/r1.13/tensorflow/contrib/eager/python/examples/nmt_with_attention/nmt_with_attention.ipynb
)
I have replaced the default GRU layer with LSTM layer. Without using beam search decoder, it was working fine with LSTM.

**Code to reproduce the issue**

My current decoder looks as follows:
`
class Decoder(tf.keras.Model):
    def __init__(self, vocab_size, embedding_dim, dec_units, batch_sz, start_tokens, end_token):
        super(Decoder, self).__init__()
        self.batch_sz = batch_sz
        self.dec_units = dec_units
        self.embedding = tf.keras.layers.Embedding(vocab_size, embedding_dim)
        self.lstm = lstm(self.dec_units)
        self.fc = tf.keras.layers.Dense(vocab_size)
        self.cell = tf.contrib.rnn.BasicLSTMCell(self.dec_units)  # tf.contrib.rnn.LSTMCell(self.dec_units)
        self.beam_size = BEAM_SIZE
        self.start_tokens = start_tokens
        self.end_token = end_token

        # used for attention
        self.W1 = tf.keras.layers.Dense(self.dec_units)
        self.W2 = tf.keras.layers.Dense(self.dec_units)
        self.W3 = tf.keras.layers.Dense(self.dec_units)
        self.V = tf.keras.layers.Dense(1)

    def call(self, x, hidden, hidden2, enc_output):
        # enc_output shape == (batch_size, max_length, hidden_size)

        # hidden shape == (batch_size, hidden size)
        # hidden_with_time_axis shape == (batch_size, 1, hidden size)
        # we are doing this to perform addition to calculate the score

        hidden_with_time_axis = tf.expand_dims(hidden, 1)

        hidden_with_time_axis2 = tf.expand_dims(hidden2, 1)

        # score shape == (batch_size, max_length, 1)
        # we get 1 at the last axis because we are applying tanh(FC(EO) + FC(H)) to self.V
        score = self.V(
            tf.nn.tanh(self.W1(enc_output) + self.W2(hidden_with_time_axis) + self.W3(hidden_with_time_axis2)))

        # attention_weights shape == (batch_size, max_length, 1)
        attention_weights = tf.nn.softmax(score, axis=1)

        # context_vector shape after sum == (batch_size, hidden_size)
        context_vector = attention_weights * enc_output
        context_vector = tf.reduce_sum(context_vector, axis=1)

        # x shape after passing through embedding == (batch_size, 1, embedding_dim)
        x = self.embedding(x)

        # x shape after concatenation == (batch_size, 1, embedding_dim + hidden_size)
        x = tf.concat([tf.expand_dims(context_vector, 1), x], axis=-1)

        output, h, c = self.lstm(x)

        logits = self.fc(output)

        beam = tf.contrib.seq2seq.BeamSearchDecoder(self.cell, self.embedding, self.start_tokens, self.end_token,
                                                    tf.contrib.rnn.LSTMStateTuple(
                                                        tf.contrib.seq2seq.tile_batch(h, multiplier=self.beam_size),
                                                        tf.contrib.seq2seq.tile_batch(c,
                                                                                      multiplier=self.beam_size)),
                                                    self.beam_size)
        output, beamOp , _ = tf.contrib.seq2seq.dynamic_decode(
            beam, output_time_major=True, maximum_iterations=MAX_SEQUENCE_LENGTH)

        predicted_ids = tf.transpose(tf.cast(output.predicted_ids[:, :, 0], tf.float32))
        beamOp_h = beamOp[0][0][:, 0]

        beamOp_c = beamOp[0][1][:, 0]

        return predicted_ids, logits, beamOp_h, beamOp_c, attention_weights

    def initialize_hidden_state(self):
        return tf.zeros((self.batch_sz, self.dec_units))
`

I am a newbie to deep learning and TensorFlow and not sure if I am doing it in the correct way.

I am getting Out of memory issue when I start training the model.

I have already asked the question on StackOverflow a few days back since there is no reply, I am raising the issue here. Apologies if it's not an issue from the tensorflow side, as, as of now I am not sure if the issue in my code or not.

**Comment by ymodak** [comment]
Can you please provide the stack trace?
From the issue title looks like you are hitting your gpu memory limit.
You can try reducing the ```batch_size``` and limiting gpu memory usage.
See https://www.tensorflow.org/guide/using_gpu#allowing_gpu_memory_growth

**Comment by vineel-concat** [comment]
Hi,

Yes, I am hitting GPU memory limit, I have reduced my batch size to 32 and units to 512, even then after a few iterations, I am hitting out of memory.

As per my current understanding by default, its using maximum allowed memory (I am running in eager execution mode), I am seeing it in my nvidia-smi output. Also, this is the only task using the GPU:
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 418.40.04    Driver Version: 418.40.04    CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla V100-SXM2...  On   | 00000000:00:1E.0 Off |                    0 |
| N/A   46C    P0    42W / 300W |  15855MiB / 16130MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0     24696      C   ...envs/amazonei_tensorflow_p36/bin/python 15845MiB |
+-----------------------------------------------------------------------------+


Stack trace,

`
---------------------------------------------------------------------------
ResourceExhaustedError                    Traceback (most recent call last)
<ipython-input-22-6135fcffc75e> in <module>
     24             for t in range(1, targ.shape[1]):
     25                 # passing enc_output to the decoder
---> 26                 predicted_ids ,predictions, dec_hidden, dec_hidden2,_ = decoder(dec_input, dec_hidden, dec_hidden2,enc_output)
     27 
     28                 #loss += loss_function(targ[:, t], predictions[:,t])

~/anaconda3/envs/amazonei_tensorflow_p36/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer.py in __call__(self, inputs, *args, **kwargs)
    590       else:
    591         # Eager execution on data tensors.
--> 592         outputs = self.call(inputs, *args, **kwargs)
    593         self._handle_activity_regularization(inputs, outputs)
    594         return outputs

<ipython-input-18-8cdf4ffa6193> in call(self, x, hidden, hidden2, enc_output)
     36         # score shape == (batch_size, max_length, 1)
     37         # we get 1 at the last axis because we are applying tanh(FC(EO) + FC(H)) to self.V
---> 38         score = self.V(tf.nn.tanh(self.W1(enc_output) + self.W2(hidden_with_time_axis) + self.W3(hidden_with_time_axis2)))
     39 
     40         # attention_weights shape == (batch_size, max_length, 1)

~/anaconda3/envs/amazonei_tensorflow_p36/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer.py in __call__(self, inputs, *args, **kwargs)
    590       else:
    591         # Eager execution on data tensors.
--> 592         outputs = self.call(inputs, *args, **kwargs)
    593         self._handle_activity_regularization(inputs, outputs)
    594         return outputs

~/anaconda3/envs/amazonei_tensorflow_p36/lib/python3.6/site-packages/tensorflow/python/keras/layers/core.py in call(self, inputs)
    975       outputs = gen_math_ops.mat_mul(inputs, self.kernel)
    976     if self.use_bias:
--> 977       outputs = nn.bias_add(outputs, self.bias)
    978     if self.activation is not None:
    979       return self.activation(outputs)  # pylint: disable=not-callable

~/anaconda3/envs/amazonei_tensorflow_p36/lib/python3.6/site-packages/tensorflow/python/ops/nn_ops.py in bias_add(value, bias, data_format, name)
   1978       value = ops.convert_to_tensor(value, name="input")
   1979       bias = ops.convert_to_tensor(bias, dtype=value.dtype, name="bias")
-> 1980     return gen_nn_ops.bias_add(value, bias, data_format=data_format, name=name)
   1981 
   1982 

~/anaconda3/envs/amazonei_tensorflow_p36/lib/python3.6/site-packages/tensorflow/python/ops/gen_nn_ops.py in bias_add(value, bias, data_format, name)
    737       else:
    738         message = e.message
--> 739       _six.raise_from(_core._status_to_exception(e.code, message), None)
    740   # Add nodes to the TensorFlow graph.
    741   if data_format is None:

~/anaconda3/envs/amazonei_tensorflow_p36/lib/python3.6/site-packages/six.py in raise_from(value, from_value)

ResourceExhaustedError: OOM when allocating tensor with shape[64,40,1024] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc [Op:BiasAdd] name: decoder/dense_1/BiasAdd/
`

**Comment by vineel-concat** [comment]
Reducing the embeddings dimensions did the trick.

I have reduced the size of embeddings, units and then batch size and finally, I am able to train, but it's super slow compared to the default decoder. 

I have total 65K rows in my data it used to take around 2-3 hours for training with 30-35 epochs.
But now with reduced dimensions, it's been more than 2 hours and I am yet to finish an epoch. 
Is something wrong with my code? or it's usually this slow.

**Comment by ymodak** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.

If you think we've misinterpreted a bug, please comment again with a clear explanation, as well as all of the information requested in the [issue template](https://github.com/tensorflow/tensorflow/issues/new). Thanks!
