### ISSUE TITLE
Nested Layer saving with tf.train.Checkpoint

### ISSUE THREAD

**Issue by VIGS25** [tensorflow/tensorflow#30858]
**System information**

- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 1.13.1
- Python version: 3.5.6

**Describe the current behavior**
tf.train.CheckPoint fails to save variables associated with the child layer, but displays the variables associated with it. 

**Describe the expected behavior**
tf.train.CheckPoint should save variables associated with the child layer

I was trying to compare model saving between nested and non-nested `tf.keras` layers, since I need a nested layer for my task.

I put together a simple script and its corresponding output. 

In the first case, the `Linear` Layer is its own parent and in the second case, the `Linear` layer is made the child of an `NestedLinear` layer. A `tf.keras.Model` is setup with the inputs and outputs and the trainable variables are printed out. After initializing, I attempt to save a checkpoint and list the variables in the checkpoint. 

If you see the output, the number of trainable variables are the same in both cases and the child layer variables are joined to the parent layer.

I assumed that the Checkpoint saving would work in a similar fashion with gathering all variable tensors and having a mapping between the Tensor and its position in the graph topology and save them but the checkpoints fail to save the `Linear` layer variables in the second case.

Maybe there is something I missed, and would like some help on this.

**Code**
```
import tensorflow as tf
import numpy as np
from tensorflow.keras import layers
import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'

class Linear(layers.Layer):

  def __init__(self, units=32, input_dim=32):
    super(Linear, self).__init__()
    self.w = self.add_weight(shape=(input_dim, units),
                             initializer='random_normal',
                             trainable=True, name="W")
    self.b = self.add_weight(shape=(units,),
                             initializer='zeros',
                             trainable=True, name='b')

  def call(self, inputs):
    return tf.matmul(inputs, self.w) + self.b

class NestedLinear(layers.Layer):

  def __init__(self):
    super(NestedLinear, self).__init__()
    self.linear_1 = Linear(32)

  def call(self, inputs):
    x = self.linear_1(inputs)
    return x

inputs = layers.Input(shape=(32,))

print("SAVING SINGLE LAYER")
outputs = Linear(32)(inputs)

model = tf.keras.Model(inputs=inputs, outputs=outputs)
for var in model.trainable_variables:
    print(var)
ckpt = tf.train.Checkpoint(model=model)

sess = tf.Session()
sess.run(tf.global_variables_initializer())
with sess.as_default():
    ckpt.save("ckpt")

for var in tf.train.list_variables("./"):
    print(var)

print("--------------------------------------")

nl_layer = NestedLinear()
outputs = nl_layer(inputs)

print("SAVING NESTED LAYER")

model = tf.keras.Model(inputs=inputs, outputs=outputs)
for var in model.trainable_variables:
    print(var)
ckpt = tf.train.Checkpoint(model=model)

sess = tf.Session()
sess.run(tf.global_variables_initializer())
with sess.as_default():
    ckpt.save("ckpt")

for var in tf.train.list_variables("./"):
    print(var)
```
**Output**

```
SAVING SINGLE LAYER
<tf.Variable 'W:0' shape=(32, 32) dtype=float32>
<tf.Variable 'b:0' shape=(32,) dtype=float32>
('_CHECKPOINTABLE_OBJECT_GRAPH', [])
('model/.ATTRIBUTES/OBJECT_CONFIG_JSON', [])
('model/layer-0/.ATTRIBUTES/OBJECT_CONFIG_JSON', [])
('model/layer_with_weights-0/.ATTRIBUTES/OBJECT_CONFIG_JSON', [])
('model/layer_with_weights-0/W/.ATTRIBUTES/VARIABLE_VALUE', [32, 32])
('model/layer_with_weights-0/b/.ATTRIBUTES/VARIABLE_VALUE', [32])
('save_counter/.ATTRIBUTES/VARIABLE_VALUE', [])
--------------------------------------
SAVING NESTED LAYER
<tf.Variable 'W_1:0' shape=(32, 32) dtype=float32>
<tf.Variable 'b_1:0' shape=(32,) dtype=float32>
('_CHECKPOINTABLE_OBJECT_GRAPH', [])
('model/.ATTRIBUTES/OBJECT_CONFIG_JSON', [])
('model/layer-0/.ATTRIBUTES/OBJECT_CONFIG_JSON', [])
('model/layer_with_weights-0/.ATTRIBUTES/OBJECT_CONFIG_JSON', [])
('save_counter/.ATTRIBUTES/VARIABLE_VALUE', [])
```

**Comment by allenlavoie** [comment]
Can you try with a more recent version of TensorFlow? 1.14 should have this fixed I believe. sub-Layer tracking was not automatic like Model's in 1.13.

**Comment by VIGS25** [comment]
That worked, yes, thanks!
