### ISSUE TITLE
tf.test.is_gpu_available return False

### ISSUE THREAD

**Issue by aspenlin** [tensorflow/tensorflow#30863]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Amazon Linux 2 AMI
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): pip3
- TensorFlow version:tensorflow-gpu-1.14.0
- Python version:3.7.3
- Installed using virtualenv? pip? conda?:pip3
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:10.1
- GPU model and memory:Nvidia Tesla K80, 11441MiB

**Describe the problem**
tf.test.is_gpu_available returns Flase

**Provide the exact sequence of commands / steps that you executed before running into the problem**
python3
import tensorflow as tf
tf.test.is_gpu_available()

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

<img width="688" alt="Screen Shot 2019-07-18 at 17 21 57" src="https://user-images.githubusercontent.com/22419710/61493054-ae7f5800-a980-11e9-9234-175b26c624c3.png">

**Comment by aspenlin** [comment]
I removed CUDA 10.1 and reinstalled 10.0 but the error persists

**Comment by jvishnuvardhan** [comment]
@aspenlin Please check software requirements for Cuda10 [here](https://www.tensorflow.org/install/gpu#software_requirements). 

```
Software requirements
The following NVIDIA® software must be installed on your system:

NVIDIA® GPU drivers —CUDA 10.0 requires 410.x or higher.
CUDA® Toolkit —TensorFlow supports CUDA 10.0 (TensorFlow >= 1.13.0)
CUPTI ships with the CUDA Toolkit.
cuDNN SDK (>= 7.4.1)
(Optional) TensorRT 5.0 to improve latency and throughput for inference on some models.
```

Looking at error trace, I strongly feel CUDA drivers were not compatible to load CUDA10. Tensorflow correctly detects your GPU, but cuDNN you have is 3.7 (major 3 and minor 7) where as the requirements say it is compatible with >=7.4.1. I would say, please check NVIDIA drivers you have installed. It requires >= 410.48. Please check table 1 in this NVIDIA [resource](https://docs.nvidia.com/deploy/cuda-compatibility/index.html). Thanks!

`CUDA 10.0 | >= 410.48`

**Comment by aspenlin** [comment]
Yep you are right. Somehow AWS installs CUDA for you but some of the libraries are missing. I solved the problem by 'sudo yum install cuda-libraries-10-0' and install new cudnn. And now tensorflow.test.is_gpu_available() returns True!

**Comment by jvishnuvardhan** [comment]
@aspenlin Thanks for posting solution here as it will help other users. Thanks again.

**Comment by jabowery** [comment]
I'm running 441.08, which is >= 410.48 with Cuda compilation tools, release 10.0, V10.0.130 and tensorflow 2.0.0 yet, despite having 2 1070 GPUs, is_gpu_available == False:

In [3]: tf.test.is_gpu_available()
2019-12-09 16:50:55.953081: I tensorflow/core/platform/cpu_feature_guard.cc:145] This TensorFlow binary is optimized with Intel(R) MKL-DNN to use the following CPU instructions in performance critical operations:  AVX AVX2
To enable them in non-MKL-DNN operations, rebuild TensorFlow with the appropriate compiler flags.
Out[3]: False
