### ISSUE TITLE
How can I get h5 file to tflite file. I tried to do with the documentation but it is giving me an error

### ISSUE THREAD

**Issue by sajagkc11** [tensorflow/tensorflow#30864]
`from keras.models import load_model
keras_file ="project.h5"
keras.models.save_model(model,keras_file)
from tensorflow import lite
coverter = lite.TFLiteConverter.from_keras_model_file(keras_file)`

This is the error I am getting

```
`ValueError                                Traceback (most recent call last)
<ipython-input-27-d2fc0cb4c75c> in <module>
----> 1 coverter = tf.compat.v1.lite.TFLiteConverter.from_keras_model_file(keras_file)

/anaconda3/envs/py36/lib/python3.6/site-packages/tensorflow/lite/python/lite.py in from_keras_model_file(cls, model_file, input_arrays, input_shapes, output_arrays, custom_objects)
    741 
    742       frozen_func = _convert_to_constants.convert_variables_to_constants_v2(
--> 743           concrete_func)
    744       _set_tensor_shapes(frozen_func.inputs, input_shapes)
    745       return cls(frozen_func.graph.as_graph_def(), frozen_func.inputs,

/anaconda3/envs/py36/lib/python3.6/site-packages/tensorflow/python/framework/convert_to_constants.py in convert_variables_to_constants_v2(func)
    164         input_name = get_name(map_name_to_node[input_name].input[0])
    165       if map_name_to_node[input_name].op != "Placeholder":
--> 166         raise ValueError("Cannot find the Placeholder op that is an input "
    167                          "to the ReadVariableOp.")
    168       # Build a map of Placeholder ops that are inputs to ReadVariableOps to the

ValueError: Cannot find the Placeholder op that is an input to the ReadVariableOp.
```

This is my keras model.
```
model = keras.Sequential()
model.add(keras.layers.Embedding(MAX_NB_WORDS, EMBEDDING_DIM, input_length=Combined.shape[1]))
model.add(keras.layers.SpatialDropout1D(0.2))
model.add(keras.layers.LSTM(100, dropout=0.2, recurrent_dropout=0.2))
model.add(keras.layers.Dense(11, activation='softmax'))
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
model.summary()
epochs = 40
batch_size = 64
history = model.fit(X_train, Y_train, epochs=epochs, batch_size=batch_size,validation_split=0.1,callbacks=[keras.callbacks.EarlyStopping(monitor='val_loss', patience=3, min_delta=0.0001)])


Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
=================================================================
embedding (Embedding)        (None, 50, 100)           40000     
_________________________________________________________________
dropout (Dropout)            (None, 50, 100)           0         
_________________________________________________________________
lstm (LSTM)                  (None, 100)               80400     
_________________________________________________________________
dense (Dense)                (None, 11)                1111      
=================================================================
```
`

**Comment by anush-o** [comment]
@sajagkc11 ,
Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version.Thanks!

**Comment by sajagkc11** [comment]
Model Name:	MacBook Pro
  Model Identifier:	MacBookPro11,3
  Processor Name:	Intel Core i7
  Processor Speed:	2.5 GHz
  Number of Processors:	1
  Total Number of Cores:	4
  L2 Cache (per Core):	256 KB
  L3 Cache:	6 MB
  Hyper-Threading Technology:	Enabled
  Memory:	16 GB
  Boot ROM Version:	153.0.0.0.0
  SMC Version (system):	2.19f12
  Serial Number (system):	C02NF1XAG3QD
  Hardware UUID:	411A542B-6D05-553C-A6D5-7C2EBA5068C6

tensorflow  version                       2.0.0b1 
python version .                         3.7.3

**Comment by sajagkc11** [comment]
@tensorflowbutler Could you help me with this issue?

**Comment by aselle** [comment]
@gargn, is this is bug in converter v2, or do you think its just a lstm converter example.

**Comment by sajagkc11** [comment]
@aselle Thank you for responding. I was thinking if this is the issue on the parameter.(input_arrays and output_arrays)

**Comment by gargn** [comment]
This is an issue with converting LSTMs. There is currently limited support for LSTMs in TFLite. The documented path is available [here](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/experimental/examples/lstm/g3doc/README.md). We are working on improving our support of control flow based operations and models. We will update documentation and the GitHub issues as we make progress on this issue.

**Comment by sajagkc11** [comment]
converter = tf.compat.v1.lite.TFLiteConverter.from_keras_model_file(keras_file)
When I run with the v1 
```
ValueError                                Traceback (most recent call last)
<ipython-input-23-d22030c3debe> in <module>
----> 1 converter = tf.compat.v1.lite.TFLiteConverter.from_keras_model_file(keras_file)

/anaconda3/lib/python3.7/site-packages/tensorflow_core/lite/python/lite.py in from_keras_model_file(cls, model_file, input_arrays, input_shapes, output_arrays, custom_objects)
    833     _set_tensor_shapes(input_tensors, input_shapes)
    834 
--> 835     graph_def = _freeze_graph(sess, input_tensors, output_tensors)
    836     return cls(
    837         graph_def,

/anaconda3/lib/python3.7/site-packages/tensorflow_core/lite/python/util.py in freeze_graph(sess, input_tensors, output_tensors)
    247     output_arrays = [get_tensor_name(tensor) for tensor in output_tensors]
    248     return tf_graph_util.convert_variables_to_constants(sess, graph_def,
--> 249                                                         output_arrays)
    250   else:
    251     return sess.graph_def

/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/util/deprecation.py in new_func(*args, **kwargs)
    322               'in a future version' if date is None else ('after %s' % date),
    323               instructions)
--> 324       return func(*args, **kwargs)
    325     return tf_decorator.make_decorator(
    326         func, new_func, 'deprecated',

/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/framework/graph_util_impl.py in convert_variables_to_constants(sess, input_graph_def, output_node_names, variable_names_whitelist, variable_names_blacklist)
    300         source_op_name = get_input_name(map_name_to_node[source_op_name])
    301       if map_name_to_node[source_op_name].op != "VarHandleOp":
--> 302         raise ValueError("Cannot find the variable that is an input "
    303                          "to the ReadVariableOp.")
    304 

ValueError: Cannot find the variable that is an input to the ReadVariableOp.
```

**Comment by akinpelu746** [comment]
I want to convert my keras model into a tf lite file.
this is my code

import tensorflow as tf
converter = tf.lite.TFLiteConverter.from_keras_model_file( r'/content/drive/My Drive/inceptionv3-transfer-learning__fine_tune.h5') # Your model's name
model = converter.convert()
file = open( 'model.tflite' , 'wb' )
file.write( model )

ValueError: None is only supported in the 1st dimension. Tensor 'input_1' has invalid shape '[None, None, None, 3]'.

what can I do?

**Comment by haozha111** [comment]
TF Lite currently only support the batch dimension to be None, not the other dimensions. Could you specify the image width/height in your model?

**Comment by akinpelu746** [comment]
@ haozha111
my 
Image_width and Image_height = 299,299
i used inception model but i noticed now that my  model input is 

[<tf.Tensor 'input_1_1:0' shape=(?, ?, ?, 3) dtype=float32>]

**Comment by akinpelu746** [comment]
@ haozha111
the Image_width and Image_height = 299,299
iIused inception model but iI noticed now that my model input is

[<tf.Tensor 'input_1_1:0' shape=(?, ?, ?, 3) dtype=float32>]
how can i correct this?

**Comment by haozha111** [comment]
One way to do this is to call the `from_keras_model_file` API:
https://www.tensorflow.org/api_docs/python/tf/lite/TFLiteConverter#from_keras_model_file

You can pass your model's input array, input shapes, output_arrays to this function. In this case, you will first need to know what your input_arrays/output_arrays are (by looking at model.inputs()). Hope that helps.

**Comment by raghavk92** [comment]
I am using tensorflow version 1.14 and i am using the older keras packages in my model creation python file not the tf.keras package within tensorflow. Can i still use `from_keras_model_file` with my model.h5 file created with older Keras packages because in the tflite converter documentation it is mentionted that this function`from_keras_model_file` is to be used with tf.keras model. 

If `from_keras_model_file`  cant be used with models created with older keras packages which procedure do i follow . I found another procedure to convert .h5 -> .pb ->.tflite and use https://github.com/amir-abdi/keras_to_tensorflow for conversion to .pb. Is this the correct procedure or should i follow some other way

Sorry i am a beginner and this might be a pretty basic question but this is my doubt

**Comment by gargn** [comment]
The best way is something like the following (I haven't tested this code):

```
keras_model = tf.keras.models.load_model(model_file, custom_objects)
sess = tf.keras.backend.get_session()

converter = tf.lite.TFLiteConverter(sess, keras_model.inputs, keras_model.outputs)
converter.convert()
```

You might optionally need to call the following before calling `load_model`:
```
tf.keras.backend.clear_session()
tf.keras.backend.set_learning_phase(False)
```

**Comment by akinpelu746** [comment]
how can  I stop my model from predicting what is not trained for?
I trained my model based on tomato leaves but if I feed in any picture apart from tomato leaves my model will still classifier it?
what can I do?

**Comment by raghavk92** [comment]
> The best way is something like the following (I haven't tested this code):
> 
> ```
> keras_model = tf.keras.models.load_model(model_file, custom_objects)
> sess = tf.keras.backend.get_session()
> 
> converter = tf.lite.TFLiteConverter(sess, keras_model.inputs, keras_model.outputs)
> converter.convert()
> ```
> 
> You might optionally need to call the following before calling `load_model`:
> 
> ```
> tf.keras.backend.clear_session()
> tf.keras.backend.set_learning_phase(False)
> ```

So is this for keras models created with normal keras packages or models created with tf.keras module ?

**Comment by gargn** [comment]
@raghavk92 The code snippet provided works with `tf.keras` models.

**Comment by jvishnuvardhan** [comment]
@sajagkc11 Can you try to use `converter.experimental_new_converter = True` and let us know whether it resolved for you or not. 

You could check the solution provided [here](https://github.com/tensorflow/tensorflow/issues/32693) and [here](https://github.com/tensorflow/tensorflow/issues/32608). Thanks!

**Comment by jvishnuvardhan** [comment]
I think the issue was resolved. I am closing the issue. Please feel free to open it if the issue persists again. Thanks!

**Comment by katengames** [comment]
asdfsadf

**Comment by ajaysg94** [comment]
I am using Keras = 2.2.4, Tensorflow = 1.14.0, I wanted to convert **.h5 to tf-lite** but getting the below error. My keras model has LSTM in it. 
```
Traceback (most recent call last):
  File "h5_to_tf_lite.py", line 3, in <module>
    converter = tf.lite.TFLiteConverter.from_keras_model_file('6054c838ad0cf20001c8357e_tr_seq_pred_bidirectional_five_word.h5')
  File "/home/10670769/miniconda3/envs/lym/lib/python3.7/site-packages/tensorflow/lite/python/lite.py", line 762, in from_keras_model_file
    graph_def = _freeze_graph(sess, input_tensors, output_tensors)
  File "/home/10670769/miniconda3/envs/lym/lib/python3.7/site-packages/tensorflow/lite/python/util.py", line 238, in freeze_graph
    output_arrays)
  File "/home/10670769/miniconda3/envs/lym/lib/python3.7/site-packages/tensorflow/python/util/deprecation.py", line 324, in new_func
    return func(*args, **kwargs)
  File "/home/10670769/miniconda3/envs/lym/lib/python3.7/site-packages/tensorflow/python/framework/graph_util_impl.py", line 302, in convert_variables_to_constants
    raise ValueError("Cannot find the variable that is an input "
ValueError: Cannot find the variable that is an input to the ReadVariableOp.
```

I am using this script
```
import tensorflow as tf
#from tensorflow.contrib import lite
converter = tf.lite.TFLiteConverter.from_keras_model_file('model.h5')
converter.experimental_new_converter = True
tfmodel = converter.convert()
open("model.tflite" , "wb").write(tfmodel)
```

**Comment by jvishnuvardhan** [comment]
@ajaysg94 Please open a new issue as this was an old issue. Thanks!
