### ISSUE TITLE
Feature request: 24-bit audio support in tf.audio.decode_wav

### ISSUE THREAD

**Issue by carlthome** [tensorflow/tensorflow#30877]
**System information**
- TensorFlow version (you are using): 1.14
- Are you willing to contribute it (Yes/No): Yes

**Describe the feature and the current behavior/state.**
I'm working with music data of "DVD-quality" i.e. 48 kHz / 24-bit WAV and want to read the files into a `tf.data` pipeline for model training via `tf.io.read_file` and `tf.audio.decode_wav` but unfortunately I got caught up on this exception:

> InvalidArgumentError: Can only read 16-bit WAV files, but received 24 [Op:DecodeWav]

While mastered mixes tend to end up being 44.1 kHz / 16-bit, in my experience 24-bit audio is extremely common among music producers as that format has a good trade-off between disk space and noise floor so the mic gain isn't as finicky etc.

**Will this change the current api? How?**
No.

**Who will benefit with this feature?**
Audio researchers

**Any Other info.**

**Comment by yongtang** [comment]
@carlthome do you have a sample to share? Might be able to take a look.

**Comment by carlthome** [comment]
Here's an example: https://github.com/tensorflow/io/issues/49#issuecomment-518213854

**Comment by yongtang** [comment]
Related link https://github.com/tensorflow/io/pull/409

**Comment by jvishnuvardhan** [comment]
@carlthome was this resolved by @yongtang PR that was merged? Please close the issue if it was already resolved. Thanks!

**Comment by carlthome** [comment]
@jvishnuvardhan, no as far as `tf.audio.decode_wav` goes this happens on 2.0.0:

>InvalidArgumentError: Bad file size for WAV: Expected 16 or 18, but got40 [Op:DecodeWav]

So I guess this is a matter of whether tf.audio should live in tensorflow-io instead or in core?

**Comment by levivosWOW** [comment]
Hi, I would like to give this problem a try. Is it still open or is it resolved?

**Comment by yongtang** [comment]
@levivosWOW The PR in tensorflow-io has been merged and you can use:
```
import tensdorflow as tf
import tensorflow_io as tfio

tfio.audio.decode_wav(tf.io.read_file('24-bit.wav'), dtype=tf.int32))
```
for 24bit wav files.

I will close this issue for now. If you have any questions you can open a new issue in https://github.com/tensorflow/io
