### ISSUE TITLE
cna't use tf.image.resize_images in TFLite

### ISSUE THREAD

**Issue by mmmmayi** [tensorflow/tensorflow#30872]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):Linux Ubuntu 18.04.2
- TensorFlow installed from (source or binary):binary
- TensorFlow version (or github SHA if from source):1.13.1

**Provide the text output from tflite_convert**

```
Some of the operators in the model are not supported by the standard TensorFlow Lite runtime. If those are native TensorFlow operators, you might be able to use the extended runtime by passing --enable_select_tf_ops, or by setting target_ops=TFLITE_BUILTINS,SELECT_TF_OPS when calling tf.lite.TFLiteConverter(). Otherwise, if you have a custom implementation for them you can disable this error with --allow_custom_ops, or by setting allow_custom_ops=True when calling tf.lite.TFLiteConverter(). Here is a list of builtin operators you are using: ADD, AVERAGE_POOL_2D, CONV_2D, FULLY_CONNECTED, MEAN, MUL, RSQRT, SQUARED_DIFFERENCE, SQUEEZE, SUB. Here is a list of operators for which you will need custom implementations: ResizeArea.
```

I think the error happened because of using function of tf.image.resize_images:
```stft = tf.image.resize_images(stft, (128, 128), method=3)```

**Comment by freedomtan** [comment]
You many wanna take a look at [TensorFlow Lite and TensorFlow operator compatibility](https://www.tensorflow.org/lite/guide/ops_compatibility) and the document of [tf.image.resize](https://www.tensorflow.org/api_docs/python/tf/image/resize_images). In short,  `method=3`, that is, `ResizeMethod.AREA` is not supported by TFLite now. I think what you can do is either replacing it with a supported one (bilinear and nearest neighor) or implementing it.

**Comment by gowthamkpr** [comment]
Please try to build the custom ops  from [here](https://www.tensorflow.org/lite/guide/ops_custom). This is the only workaround as of now. Thanks!
