### ISSUE TITLE
TFLite conversion: AudioSpectogram, Mfcc, RandomUniform not supported

### ISSUE THREAD

**Issue by PragmaticSoftwareSolutions** [tensorflow/tensorflow#30879]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): MacOS
- TensorFlow installed from (source or binary): binary
- TensorFlow version (or github SHA if from source): 1.13

**Provide the text output from tflite_convert**

```
Some of the operators in the model are not supported by the standard TensorFlow Lite runtime. If those are native TensorFlow operators, you might be able to use the extended runtime by passing --enable_select_tf_ops, or by setting target_ops=TFLITE_BUILTINS,SELECT_TF_OPS when calling tf.lite.TFLiteConverter(). Otherwise, if you have a custom implementation for them you can disable this error with --allow_custom_ops, or by setting allow_custom_ops=True when calling tf.lite.TFLiteConverter(). Here is a list of builtin operators you are using: ADD, CONV_2D, DIV, FLOOR, FULLY_CONNECTED, MAX_POOL_2D, MUL, RESHAPE, SHAPE, SUB. Here is a list of operators for which you will need custom implementations: AudioSpectrogram, Mfcc, RandomUniform.
```

Also, please include a link to a GraphDef or the model if possible.

**Any other info / logs**

Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by anush-o** [comment]
@PragmaticSoftwareSolutions ,
In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. 
Provide the exact sequence of commands / steps that you executed before running into the problem.Thanks!

**Comment by ymodak** [comment]
Some some operations not implemented in TensorFlow Lite
See 
```--enable_select_tf_ops``` - https://www.tensorflow.org/lite/guide/ops_select
```custom implementations``` - https://www.tensorflow.org/lite/guide/ops_custom
