### ISSUE TITLE
base64 strings contains  " "

### ISSUE THREAD

**Issue by gison93** [tensorflow/tensorflow#30874]
## URL(s) with the issue:
https://www.tensorflow.org/api_docs/python/tf/io/decode_base64

## Description of issue (what needs changing):
Some base64 strings contains  " ".
### Clear description
It could be useful to add this information after this paragraph:

> Input may or may not have padding at the end. See EncodeBase64 for padding. Web-safe means that input must use - and _ instead of + and  /.

**Comment by ymodak** [comment]
Argument ```input``` should cover all string cases.
https://www.tensorflow.org/api_docs/python/tf/io/decode_base64#args
Perhaps you can elaborate more for your doc request? Thanks!

**Comment by gison93** [comment]
My input argument is a base64 string containing spaces.
The standard library base64 is able to decode (ignoring the spaces since are used just for readability) while tf.io.decode_base64 does not recognize that string as a base64 string.
When the spaces are eliminated everything works fine.

I think add a warning on this could be useful:

> Input may or may not have padding at the end. See EncodeBase64 for padding. Web-safe means that input must use - and _ instead of + and /. 
> Input cannot contain " ".

**Comment by ymodak** [comment]
Thanks for elaborating. Its clear now.  Would you like to send a PR to add the message?

**Comment by ymodak** [comment]
```tf.io.decode_base64``` ignores spaces in the string too. I made a toy example to elaborate;
Tested with TF 1.14.0
- String without space

```python
tf.io.decode_base64(input='mystring',name=None) 
<tf.Tensor 'DecodeBase64_14:0' shape=() dtype=string>
```
- String with space
```python
tf.io.decode_base64(input='my string',name=None)
<tf.Tensor 'DecodeBase64_15:0' shape=() dtype=string>
```
Thanks!
