### ISSUE TITLE
Inference on TFLite object detection model fails on run : "(num_classes_with_background - num_classes <= 1) was not true"

### ISSUE THREAD

**Issue by tnodelan** [tensorflow/tensorflow#30881]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes, however greatly adapted from scripts
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10 64bit
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: Lenovo PB2-690M Android 6.0.1 API 23
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below): 1.13.1
- Python version: 3.7.3
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: CUDA toolkit 10.0.130 / cuDNN 7.3.1
- GPU model and memory: Intel i7-6700 3.7GHz 16Go

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
The script is in two parts :
First few pictures are taken on phone to re-train a model with overfiting (ssd_resnet_50_fpn_coco) on the server, which produces a .tflite model, then sends it back to the device. 

Problem emerges when I try to run the inference with a newly taken image and the .tflite model as in the associated TFLite object detection example script : 
Caused by: java.lang.IllegalArgumentException: Internal error: Failed to run on the given Interpreter: tensorflow/lite/kernels/detection_postprocess.cc:688 (num_classes_with_background - num_classes <= 1) was not true.Node number 228 (TFLite_Detection_PostProcess) failed to invoke. 
at org.tensorflow.lite.NativeInterpreterWrapper.run(Native Method)
        at org.tensorflow.lite.NativeInterpreterWrapper.run(NativeInterpreterWrapper.java:149)
        at org.tensorflow.lite.Interpreter.runForMultipleInputsOutputs(Interpreter.java:275)
        at tflite.TFLiteObjectDetectionAPIModel.recognizeImage(TFLiteObjectDetectionAPIModel.java:164)

**Describe the expected behavior**
As you can guess, it would be expected to run without failure. Note that using the .tflite model given by the TFLite object detection example script produces no error with the same picture (although it wouldn't yield any pertinent result). 

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.
Server Python Part, used to convert the exported graph into .tflite file

  ```
    graph_def_file=os.path.join(BOX_PATH, "tflite_graph.pb")
    input_arrays=["normalized_input_image_tensor"]
    output_arrays=['TFLite_Detection_PostProcess','TFLite_Detection_PostProcess:1','TFLite_Detection_PostProcess:2','TFLite_Detection_PostProcess:3']
    input_tensor={"normalized_input_image_tensor":[1, 640, 640, 3]}
    converter = tf.lite.TFLiteConverter.from_frozen_graph(graph_def_file, input_arrays, output_arrays, input_tensor)
    converter.target_ops = [tf.lite.OpsSet.TFLITE_BUILTINS, tf.lite.OpsSet.SELECT_TF_OPS]
    converter.allow_custom_ops = True;
    tflite_quant_model = converter.convert()
    open(os.path.join(BOX_PATH, "frozen_inference_graph.tflite", "wb").write(tflite_quant_model)

```
Here is the principal change in script for the inference run (Java code part):
[TFLiteObjectDetectionAPIModel.txt](https://github.com/tensorflow/tensorflow/files/3411835/TFLiteObjectDetectionAPIModel.txt)

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.
Inference script taken from https://github.com/tensorflow/examples/tree/master/lite/examples/object_detection/android
Model tested with following script prior to .tflite conversion
https://github.com/tiangolo/tensorflow-models/blob/master/research/object_detection/object_detection_tutorial.ipynb

Here it is, thanks for your reply and help !

**Comment by tnodelan** [comment]
Solution ?
I removed that line `converter.target_ops = [tf.lite.OpsSet.TFLITE_BUILTINS, tf.lite.OpsSet.SELECT_TF_OPS]` used during the conversion of the .pb to the .tflite model graph file as the documentation showed this flag as experimental, and the error disappeared. 

However I am not sure of why adding target operations raised an issue, moreover since almost every code sample available seems to add this target_ops flag without any problem.

An Idea of why the problem could have emerged because of this ?

**Comment by BernardinD** [comment]
Is there any progress on this?

**Comment by tnodelan** [comment]
Well I was forced to not use a TFLite model since conversion broke it every time, so instead I used the frozen_graph.pb given by the export_inference_graph method, and the example application using a similar frozen graph to obtain a working app, but I still couldn't put my head around TFLite conversion.

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.
