### ISSUE TITLE
400 bad request when creating pip package

### ISSUE THREAD

**Issue by capers** [tensorflow/tensorflow#3089]
GitHub issues are for bugs / installation problems / feature requests.  
For general support from the community, see [StackOverflow](https://stackoverflow.com/questions/tagged/tensorflow).
To make bugs and feature requests more easy to find and organize, we close issues that are deemed
out of scope for GitHub Issues and point people to StackOverflow.

For bugs or installation issues, please provide the following information.
The more information you provide, the more easily we will be able to offer
help and advice.

### Environment info
Operating System:
CentOS 6
Installed version of CUDA and cuDNN: 7.5, 4.0

(please attach the output of `ls -l /path/to/cuda/lib/libcud*`):
CUDA and cuDNN files are both present

If installed from binary pip package, provide:

1. Which pip package you installed.
2. The output from `python -c "import tensorflow; print(tensorflow.__version__)"`.
NA

If installed from sources, provide the commit hash:
`25023dffcf88f46777b5ddab457ac84a5bed5d2f`

### Steps to reproduce
1. Build package from source
2. Run `bazel build -c opt --config=cuda //tensorflow/tools/pip_package:build_pip_package`

### What have you tried?
1. Have tried looking at #1817 which had same error. It is not intermittent as described in that issue, it fails every single time but works if you just try to clone the repo directly.
2. However, running `git clone https://github.com/google/boringssl.git` results in:
```
git clone https://github.com/google/boringssl.git
Cloning into 'boringssl'...
remote: Counting objects: 26620, done.
remote: Compressing objects: 100% (310/310), done.
remote: Total 26620 (delta 164), reused 0 (delta 0), pack-reused 26299
Receiving objects: 100% (26620/26620), 18.72 MiB | 5.79 MiB/s, done.
Resolving deltas: 100% (18032/18032), done.
Checking connectivity... done.
```
### Logs or other output that would be helpful
(If logs are large, please upload as attachment)
```
bazel build -c opt --config=cuda //tensorflow/tools/pip_package:build_pip_package
WARNING: /root/.cache/bazel/_bazel_root/68a62076e91007a7908bc42a32e4cff9/external/protobuf/WORKSPACE:1: Workspace name in /root/.cache/bazel/_bazel_root/68a62076e91007a7908bc42a32e4cff9/external/protobuf/WORKSPACE (@__main__) does not match the name given in the repository's definition (@protobuf); this will cause a build error in future versions.
WARNING: /tensorflow/util/python/BUILD:11:16: in includes attribute of cc_library rule //util/python:python_headers: 'python_include' resolves to 'util/python/python_include' not in 'third_party'. This will be an error in the future.
WARNING: /root/.cache/bazel/_bazel_root/68a62076e91007a7908bc42a32e4cff9/external/highwayhash/WORKSPACE:1: Workspace name in /root/.cache/bazel/_bazel_root/68a62076e91007a7908bc42a32e4cff9/external/highwayhash/WORKSPACE (@__main__) does not match the name given in the repository's definition (@highwayhash); this will cause a build error in future versions.
WARNING: /root/.cache/bazel/_bazel_root/68a62076e91007a7908bc42a32e4cff9/external/re2/WORKSPACE:1: Workspace name in /root/.cache/bazel/_bazel_root/68a62076e91007a7908bc42a32e4cff9/external/re2/WORKSPACE (@__main__) does not match the name given in the repository's definition (@re2); this will cause a build error in future versions.
ERROR: /tensorflow/tensorflow/core/distributed_runtime/rpc/BUILD:48:1: no such package '@grpc//': Error cloning repository: https://github.com/google/boringssl.git: 400 Bad Request caused by https://github.com/google/boringssl.git: 400 Bad Request and referenced by '//tensorflow/core/distributed_runtime/rpc:grpc_util'.
ERROR: Analysis of target '//tensorflow/tools/pip_package:build_pip_package' failed; build aborted.
INFO: Elapsed time: 49.467s
```

**Comment by capers** [comment]
FWIW I was able to fix this by editing the workspace to use a local repository of boringssl that I cloned manually.

**Comment by andydavis1** [comment]
Unfortunately, this looks like bazel's inability to deal with connectivity issues with github, though not sure why it is persistent in your case. Do you have restricted internet connectivity? In either event, consider opening an issue against the bazel repo for this one.
