### ISSUE TITLE
Makefile build does not create contrib ops

### ISSUE THREAD

**Issue by themightyoarfish** [tensorflow/tensorflow#30898]
**System information**
- OS Platform and Distribution: MacOS
- TensorFlow installed from (source or binary): Source
- TensorFlow version: c6352706d6280d7ed34964969503b104471a9335
- Bazel version (if compiling from source): not used
- GCC/Compiler version (if compiling from source):
```
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include/c++/4.2.1
Apple LLVM version 10.0.1 (clang-1001.0.46.4)
Target: x86_64-apple-darwin18.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

**Describe the problem**

When compiling with `tensorflow/contrib/makefile/build_all_linux.sh`, the following inclusion does not work:
```
#include <tensorflow/cc/ops/standard_ops.h>
```
because the header `#includes` something that's not there:
```
<tfdir>/tensorflow/tensorflow/cc/ops/standard_ops.h:19:10: fatal error: 'tensorflow/cc/ops/array_ops.h' file not found
#include "tensorflow/cc/ops/array_ops.h"
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
```

Searching for `array_ops` in the repository e.g. reveals a CMake macro named `GENERATE_CONTRIB_OP_LIBRARY` defined in in `tensorflow/contrib/cmake/tf_core_ops.cmake`.

https://github.com/tensorflow/tensorflow/blob/6c7c3bb0f3563e8a147935597617cf3d052c7852/tensorflow/contrib/cmake/tf_core_ops.cmake#L76

Obviously, the Makefile does not use this. Is it intentional that these ops are not being built with the makefile? Even if I remove the header, a program does not work at runtime due to missing ops.

I can provide a minimal C++ file and build scripts if desired, but would like to know first if it's supposed to be like this.

**Comment by themightyoarfish** [comment]
The same problem occurs with the CMake build (which I have fixed many problems in, but running into this as well).

**Comment by jingxu10** [comment]
May I know the reason why you don't use bazel?

**Comment by themightyoarfish** [comment]
Because it's generally a pain to install the correct version, and none of my knowledge transfers to it. I find it lamentable that such an important project does not have a build process which works easily on all systems.

**Comment by jingxu10** [comment]
Hi, this issue seems not to be Intel specific, but about compiling of TF. I would suggest other experts to share ideas.

**Comment by mihaimaruseac** [comment]
This came now to my eyes.

Two things: makefile build is no longer supported (since at least months ago). Also, recently we removed contrib as it won't be available in 2.0.

I think it would be best to try using Bazel. `./configure.py` has the versioning information at the top:

https://github.com/tensorflow/tensorflow/blob/250a5d47828aa229857266d59b32314bda79bcb3/configure.py#L52-L53

Once you start using it, makefile knowledge will transfer in time. I'm saying this from experience, I was using makefile's everywhere but then I switch to Bazel for TF and I like this model slightly better for extremely large cross-platform codebases.

**Comment by jvishnuvardhan** [comment]
@themightyoarfish Is this still an issue? Please close the issue if this was resolved already. Thanks!

**Comment by themightyoarfish** [comment]
I have no idea to be honest, i have not touched Tensorflow since raising this issue. I suppose it can be closed for now.
