### ISSUE TITLE
ffmpeg not found when build in Raspberry Pi 3 B+ Raspbian 10

### ISSUE THREAD

**Issue by base0** [tensorflow/tensorflow#30891]
**System information**
- OS : Raspbian 10
- Device : Rasberry Pi 3 B+
- TensorFlow installed from source
- TensorFlow version: 1.9
- Python version: 3
- Installed using : I followed the instruction from https://www.tensorflow.org/install/source_rpi 

I followed the instruction from https://www.tensorflow.org/install/source_rpi   The commands are copy from the link as follows:

`git clone https://github.com/tensorflow/tensorflow.git`

`cd tensorflow`

`git checkout r1.9`

`CI_DOCKER_EXTRA_PARAMS="-e CI_BUILD_PYTHON=python3 -e CROSSTOOL_PYTHON_INCLUDE_PATH=/usr/include/python3.4" `
`    tensorflow/tools/ci_build/ci_build.sh PI-PYTHON3 \`
`    tensorflow/tools/ci_build/pi/build_raspberry_pi.sh`

I got the following error.

> Package ffmpeg is not available, but is referred to by another package.
> This may mean that the package is missing, has been obsoleted, or
> is only available from another source
> 
> E: Package 'ffmpeg' has no installation candidate
> The command '/bin/sh -c /install/install_deb_packages.sh' returned a non-zero code: 100
> ERROR: docker build failed. Dockerfile is at /home/pi/tensorflow/tensorflow/tools/ci_build/Dockerfile.pi-python3

**Comment by praeclarum** [comment]
I am getting the same error. I have tried it on Stretch and Buster on both version 3 and version 4 PIs without success.

**Comment by ymodak** [comment]
Can you please test with TF 2.3 branch since it was last tested with TF 2.3.0-rc2?
