### ISSUE TITLE
failed to “sudo bazel build -c opt --config=cuda --verbose_failures //tensorflow:libtensorflow.so”

### ISSUE THREAD

**Issue by liupengkd** [tensorflow/tensorflow#30899]
I want to compile tensorflow‘ c library version
system info：
  ubuntu 16.04
  bazel 0.19.2
  tensorflow 1.13
  gpu RTX 2080 Ti
  cuda10.0
  cudnn 7.4.2

steps：
1.Install bazel by sh file
2.git clone --recursive https://github.com/tensorflow/tensorflow
3.git checkout r1.3
4.sudo ./configure
5.sudo bazel build -c opt --config=cuda --verbose_failures //tensorflow:libtensorflow.so

error:
 Starting local Bazel server and connecting to it...
WARNING: The following configs were expanded more than once: [cuda]. For repeatable flags, repeats are counted twice and may lead to unexpected behavior.
DEBUG: /home/liupeng/.cache/bazel/_bazel_root/f585ecc291b1d46eb648d7609ae1ce83/external/bazel_tools/tools/cpp/lib_cc_configure.bzl:115:5: 
Auto-Configuration Warning: 'TMP' environment variable is not set, using 'C:\Windows\Temp' as default
ERROR: /home/liupeng/tensorflow/tensorflow/core/kernels/BUILD:4841:1: no such package '@icu//': java.io.IOException: Error downloading [https://mirror.bazel.build/github.com/unicode-org/icu/archive/release-62-1.tar.gz, https://github.com/unicode-org/icu/archive/release-62-1.tar.gz] to /home/liupeng/.cache/bazel/_bazel_root/f585ecc291b1d46eb648d7609ae1ce83/external/icu/release-62-1.tar.gz: Checksum was dd16ace2fbfa98271e266fb6ab4fce056a8baf8274059687fd1b9a1159a44de9 but wanted e15ffd84606323cbad5515bf9ecdf8061cc3bf80fb883b9e6aa162e485aa9761 and referenced by '//tensorflow/core/kernels:unicode_ops'
ERROR: Analysis of target '//tensorflow:libtensorflow.so' failed; build aborted: no such package '@icu//': java.io.IOException: Error downloading [https://mirror.bazel.build/github.com/unicode-org/icu/archive/release-62-1.tar.gz, https://github.com/unicode-org/icu/archive/release-62-1.tar.gz] to /home/liupeng/.cache/bazel/_bazel_root/f585ecc291b1d46eb648d7609ae1ce83/external/icu/release-62-1.tar.gz: Checksum was dd16ace2fbfa98271e266fb6ab4fce056a8baf8274059687fd1b9a1159a44de9 but wanted e15ffd84606323cbad5515bf9ecdf8061cc3bf80fb883b9e6aa162e485aa9761
INFO: Elapsed time: 780.835s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (119 packages loaded, 8680 targets configured)

**Comment by ravikyram** [comment]
Just to verify did you get chance to follow instructions from [TensorFlow](https://www.tensorflow.org/install/source) website .Please, let us know. Thanks!

**Comment by dandy27** [comment]
> I want to compile tensorflow‘ c library version
> system info：
> ubuntu 16.04
> bazel 0.19.2
> tensorflow 1.13
> gpu RTX 2080 Ti
> cuda10.0
> cudnn 7.4.2
> 
> steps：
> 1.Install bazel by sh file
> 2.git clone --recursive https://github.com/tensorflow/tensorflow
> 3.git checkout r1.3
> 4.sudo ./configure
> 5.sudo bazel build -c opt --config=cuda --verbose_failures //tensorflow:libtensorflow.so
> 
> error:
> Starting local Bazel server and connecting to it...
> WARNING: The following configs were expanded more than once: [cuda]. For repeatable flags, repeats are counted twice and may lead to unexpected behavior.
> DEBUG: /home/liupeng/.cache/bazel/_bazel_root/f585ecc291b1d46eb648d7609ae1ce83/external/bazel_tools/tools/cpp/lib_cc_configure.bzl:115:5:
> Auto-Configuration Warning: 'TMP' environment variable is not set, using 'C:\Windows\Temp' as default
> ERROR: /home/liupeng/tensorflow/tensorflow/core/kernels/BUILD:4841:1: no such package '@icu//': java.io.IOException: Error downloading [https://mirror.bazel.build/github.com/unicode-org/icu/archive/release-62-1.tar.gz, https://github.com/unicode-org/icu/archive/release-62-1.tar.gz] to /home/liupeng/.cache/bazel/_bazel_root/f585ecc291b1d46eb648d7609ae1ce83/external/icu/release-62-1.tar.gz: Checksum was dd16ace2fbfa98271e266fb6ab4fce056a8baf8274059687fd1b9a1159a44de9 but wanted e15ffd84606323cbad5515bf9ecdf8061cc3bf80fb883b9e6aa162e485aa9761 and referenced by '//tensorflow/core/kernels:unicode_ops'
> ERROR: Analysis of target '//tensorflow:libtensorflow.so' failed; build aborted: no such package '@icu//': java.io.IOException: Error downloading [https://mirror.bazel.build/github.com/unicode-org/icu/archive/release-62-1.tar.gz, https://github.com/unicode-org/icu/archive/release-62-1.tar.gz] to /home/liupeng/.cache/bazel/_bazel_root/f585ecc291b1d46eb648d7609ae1ce83/external/icu/release-62-1.tar.gz: Checksum was dd16ace2fbfa98271e266fb6ab4fce056a8baf8274059687fd1b9a1159a44de9 but wanted e15ffd84606323cbad5515bf9ecdf8061cc3bf80fb883b9e6aa162e485aa9761
> INFO: Elapsed time: 780.835s
> INFO: 0 processes.
> FAILED: Build did NOT complete successfully (119 packages loaded, 8680 targets configured)

why i see people using -c opt instead of --config=opt? @ravikyram

**Comment by gunan** [comment]
The error message says it cannot download one of the TF dependencies. You need to check your internet connection.
Especially users in china have reported similar issues. Is it possible you are in China?

**Comment by ravikyram** [comment]
@liupengkd 
Can you please confirm if the issue still persists.Thanks!

**Comment by liupengkd** [comment]
@ravikyram I am very sorry, I have been busy recently, there is no reply. I switched to 1.9.0 and compiled successfully. Did not continue to try 1.13

**Comment by liupengkd** [comment]
@gunan Yes, I am in China. I also think so. But when I changed to 1.9.0, I compiled successfully.

**Comment by ravikyram** [comment]
@liupengkd 
Thanks for the update. I am closing this issue since the query is been resolved.Thanks!
