### ISSUE TITLE
time series example

### ISSUE THREAD

**Issue by andrewcz** [tensorflow/tensorflow#309]
is there a multivariate numerical time series example in tensorflow.

Many thanks,
Andrew

**Comment by hartsantler** [comment]
+1

**Comment by avoulk-syn** [comment]
+1

**Comment by rajasrijan** [comment]
+1

**Comment by datnamer** [comment]
+1

**Comment by mbaddar1** [comment]
@girving if no body is working on that issue , i can start working on it

**Comment by girving** [comment]
@mbaddar1: Very cool!

@martinwicke: Do you think this should go in core or the upcoming model zoo?

**Comment by martinwicke** [comment]
Everything that doesn't have a full tutorial associated with it should go
into the zoo (which we will announce shortly). If you want to write a
tutorial we'd be happy to merge it into core.

**Comment by andrewcz** [comment]
Hi guys!
Apologies but is this inferring that somebody will work on the time series problem?
Many thanks guys,
Andrew

**Comment by andrewcz** [comment]
and is there a link to zoo?
Cheers,
Andrew

**Comment by martinwicke** [comment]
Zoo: shortly. Nobody is working on a time series example as far as I know.

**Comment by zhmz90** [comment]
Look forward to that.

**Comment by andrewcz** [comment]
https://m.reddit.com/r/MachineLearning/comments/3sok8k/tensorflow_basic_rnn_example_with_variable_length/

Thought i would post this here. somebody might turn it into a tutorial.
Best,
Andrew

**Comment by bhack** [comment]
:+1:

**Comment by bhack** [comment]
@martinwicke Any update on Zoo? :tiger: :elephant:

**Comment by martinwicke** [comment]
@allenlavoie how far are we with time series?

**Comment by allenlavoie** [comment]
@martinwicke We're looking to open source in Q2. I was actually going to ask you (or someone else who works on Estimators) to look at the API soon.

**Comment by girving** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Comment by allenlavoie** [comment]
New information: probably going to be the (very) beginning of Q3 rather than the end of Q2. Definitely in contrib for 1.3.

Re-opening because this is still relevant.

**Comment by allenlavoie** [comment]
We have some [time series Estimators in contrib](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/contrib/timeseries). Feel free to take a look and open specific bugs/feature requests.
