### ISSUE TITLE
tf.contrib.factorization.WALSMatrixFactorization( AttributeError: 'module' object has no attribute 'WALSMatrixFactorization')

### ISSUE THREAD

**Issue by mabodx** [tensorflow/tensorflow#30907]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version (use command below):
- Python version:
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
I just run walsmodel through gcloud ml-engine jobs
I run it through my mac terminal, I didn't change any code over here https://github.com/GoogleCloudPlatform/training-data-analyst/tree/master/courses/machine_learning/deepdive/10_recommend/walsmodel

But it always has the following error:
experiment_fn tf.contrib.factorization.WALSMatrixFactorization( AttributeError: 'module' object has no attribute 'WALSMatrixFactorization'

`gcloud ml-engine jobs submit training wals_190721_012226 --region=us-east1 --module-name=walsmodel.task --runtime-version 1.14 --python-version 3.5 --package-path=/home/mabodx/anguis/news_recommendation/10_recommend/walsmodel --job-dir=gs://buzzbreak/news_recommendation_2019_07_21T01_18_02Z/ --staging-bucket=gs://buzzbreak --scale-tier=BASIC_GPU --runtime-version= -- --output_dir=gs://buzzbreak/news_recommendation_2019_07_21T01_18_02Z/model_trained_190721_012212 --input_path=gs://buzzbreak/news_recommendation_2019_07_21T01_18_02Z/news/data --num_epochs=500 --nitems=39681 --nusers=38781 --topk=1000`
**Describe the expected behavior**

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.
https://github.com/GoogleCloudPlatform/training-data-analyst/tree/master/courses/machine_learning/deepdive/10_recommend/walsmodel

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by gadagashwini** [comment]
@mabodx Will it be possible to provide the minimal code snippet to reproduce the issue. Thanks!

**Comment by mabodx** [comment]
@gadagashwini  I just use code over here 
https://github.com/GoogleCloudPlatform/training-data-analyst/blob/master/courses/machine_learning/deepdive/10_recommend/walsmodel/model.py#L25

Never change anything

**Comment by gadagashwini** [comment]
@mabodx I tried executing the code given in the file model.py but i didn't see any error. Let us know what is the expected behavior. Thanks!

**Comment by mabodx** [comment]
@gadagashwini 
I just try to run this 
```
Run on Cloud
In [ ]:
%%bash
gsutil -m cp data/* gs://${BUCKET}/wals/data
In [ ]:
%%bash
OUTDIR=gs://${BUCKET}/wals/model_trained
JOBNAME=wals_$(date -u +%y%m%d_%H%M%S)
echo $OUTDIR $REGION $JOBNAME
gsutil -m rm -rf $OUTDIR
gcloud ml-engine jobs submit training $JOBNAME \
    --region=$REGION \
    --module-name=walsmodel.task \
    --package-path=${PWD}/walsmodel \
    --job-dir=$OUTDIR \
    --staging-bucket=gs://$BUCKET \
    --scale-tier=BASIC_GPU \
    --runtime-version=$TFVERSION \
    -- \
    --output_dir=$OUTDIR \
    --input_path=gs://${BUCKET}/wals/data \
    --num_epochs=10 --nitems=5668 --nusers=82802

```
I get this code from this notebook in before `In[36]`
https://github.com/GoogleCloudPlatform/training-data-analyst/blob/master/courses/machine_learning/deepdive/10_recommend/wals.ipynb

![image](https://user-images.githubusercontent.com/4045116/61628733-b65b3700-acb5-11e9-8105-ccd29a2e9615.png)


If you run this from any terminal through command,  you will get the above error (Don't run it through Notebook, because notebook works fine). 
I suppose there is some version error with google cloud sdk version(which is different from google notebook)

**Comment by ymodak** [comment]
Apologies for the delay in response. 
`tf.contrib` is deprecated and has moved out of TensorFlow starting 2.X
