### ISSUE TITLE
ERROR: saved_model_cli

### ISSUE THREAD

**Issue by jeet4690** [tensorflow/tensorflow#30900]
working on ubuntu 18.4

tensorflow version 2.0.0b1

I am trying to find `output_node_names` with the help of command `saved_model_cli show --dir DIR_PATH --all`

got this ERROR `OSError: SavedModel file does not exist at: DIR_PATH`

this is my SAVED MODEL

![Screenshot from 2019-07-20 21-06-51](https://user-images.githubusercontent.com/32290207/61580704-5b4d0700-ab32-11e9-8fac-7fc38ab4b00b.png)

**Comment by jeet4690** [comment]
Please somebody help me to find “output_node_names”, I have to create “freeze_graph.pb”

**Comment by ymodak** [comment]
I don't  see saved_model file in your directory. Your model tree should contain ```saved_model``` file.  I made a toy example to illustrate,
```ssd_mobilenet_v1_coco_2017_11_17
├── checkpoint
├── frozen_inference_graph.pb
├── model.ckpt.data-00000-of-00001
├── model.ckpt.index
├── model.ckpt.meta
└── saved_model
    ├── saved_model.pb
    └── variables
```

**Comment by jeet4690** [comment]
can you please tell me how to create `saved_model` foulder, if not then can you please tell me a code or something to get `output_node_names` (graph is too big so manually do it is not possible ) @ymodak

**Comment by ymodak** [comment]
See https://www.tensorflow.org/guide/saved_model#build_and_load_a_savedmodel to build saved model
and then https://www.tensorflow.org/guide/saved_model#cli_to_inspect_and_execute_savedmodel

**Comment by jeet4690** [comment]
@ymodak problem is the model is pretrained one, i didn't make it. I just want to know the `output_node_names` to convert it into `freeze_graph.pb`

**Comment by ymodak** [comment]
Perhaps referring to this similar post on stackoverflow can help.
https://stackoverflow.com/questions/38958662/tensorflow-what-are-the-output-node-names-for-freeze-graph-py-in-the-model-wi/38959056
Thanks!
