### ISSUE TITLE
Failed to install tensorflow-estimator

### ISSUE THREAD

**Issue by MovGP0** [tensorflow/tensorflow#30905]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
Windows 10.0.18362.0

- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
pip / binary
- TensorFlow version:
1.14 (?)
- Python version:
Python 3.7.4 (installed from Windows Store)
- Installed using virtualenv? pip? conda?:
pip 19.1.1
- Bazel version (if compiling from source):
n/a
- GCC/Compiler version (if compiling from source):
n/a
- CUDA/cuDNN version:
n/a
- GPU model and memory:
Nvidia GeForce GTX 1080; 16 GB

**Describe the problem**

When trying to install Tensorflow, I get an error while installing the Tensorflow-Estimator dependency. 

**Provide the exact sequence of commands / steps that you executed before running into the problem**

* Open `cmd.exe` as administrator

```
pip install --upgrade tensorflow-estimator

ERROR: Could not install packages due to an EnvironmentError: [Errno 2] No such file or directory: 'C:\\Users\\movgp\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python37\\site-packages\\tensorflow_estimator\\python\\estimator\\canned\\linear_optimizer\\python\\utils\\__pycache__\\sharded_mutable_dense_hashtable.cpython-37.pyc'
```

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

```
 Directory of C:\Users\movgp\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\tensorflow_estimator\python\estimator\canned\linear_optimizer\python\utils\__pycache__

2019-07-21  09:46    <DIR>          .
2019-07-21  09:46    <DIR>          ..
2019-07-21  09:46            21,504 sdca_ops.cpython-37.pyc
               1 File(s)         21,504 bytes
```

**Comment by ravikyram** [comment]
@MovGP0 
Just to verify did you get chance to follow instructions from [TensorFlow](https://www.tensorflow.org/install/pip) website .Please, let us know. 
https://stackoverflow.com/questions/55739873/tf-estimator-package-not-installed
Also, please go through the below link and see if it helps you.Thanks!

**Comment by temccarthy** [comment]
I'm having the same problem, I tried both links and neither worked. I also tried the solution to this link, but it didn't work either.
https://github.com/googleapis/google-cloud-python/issues/6647

**Comment by gunan** [comment]
did you try rerunning the command?
On windows, sometimes we see spurious failures.

**Comment by MovGP0** [comment]
@gunan Sure. First thing I've tried.

**Comment by gunan** [comment]
I definitely think this is a pip issue, but not sure where to look for a solution.
Maybe the path is too long and pip has problems?

**Comment by ashleygw** [comment]
I had the exact same problem. Here is what I did to make the installation work:

- Downloaded python from here : https://www.python.org/downloads/release/python-374/

- Ran the installer and installed for all users (I did this because the path length is shorter, who knows if that was the difference). Additionally I also installed pip through this installer as well.

- At the end of the installation I clicked on the button to allow PATH lengths to exceed 260 characters. 

After doing this and re-running "pip install tensorflow-gpu" it passed the error shown above. My guess would be that python installed from the windows store will, by-default, install to a path which is too long or fail to bypass the 260 path-length restriction. Previously I was using the version of Python that came with my Windows 10 installation.

**Comment by MovGP0** [comment]
On Windows 10, you could disable the path length restriction, set an hard link for the installation path, and update the environment variables. 

This way we could have a store-managed version of python that supports the longer paths.

**Comment by MovGP0** [comment]
@gunan can you update the documentation? thank you!

**Comment by gunan** [comment]
@lamberta It may be useful to mention disabling path length restriction may help resolve pip installation issues on windows.

@MovGP0 did disabling tpath length restriction solve the problem for you?
Should we close the issue?

**Comment by lamberta** [comment]
Thanks, but I think we already have this in the docs: https://www.tensorflow.org/install/pip
Select Windows tab ...
*Make sure [long paths are enabled](https://superuser.com/questions/1119883/windows-10-enable-ntfs-long-paths-policy-option-missing) on Windows.*

Is something else needed? (That page [is here in GitHub](https://github.com/tensorflow/docs/blob/master/site/en/install/pip.html))
