### ISSUE TITLE
CPU.ModifyGraphWithDelegate is disallowed when graph is immutable. Delegate should run on the same thread where it was initialized.Node number 64 (TfLiteGpuDelegate) failed to invoke.ed to invoke.

### ISSUE THREAD

**Issue by Gmrevo** [tensorflow/tensorflow#30914]
<em>
-We are trying to enable GPU using GPU delegate in TensorFlow[ object detection sample project](https://github.com/tensorflow/examples/tree/master/lite/examples/object_detection/android), by taking reference from GPU enabled sample project of [Object  Classification](https://github.com/tensorflow/examples/tree/master/lite/examples/image_classification/android).-- we are also using Float Model for detection. </em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Android Studio installed on Ubuntu 16.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: Realme One
- TensorFlow installed from (source or binary):
- TensorFlow version (use command below):
dependencies added:
`implementation 'org.tensorflow:tensorflow-lite:0.0.0-nightly'
implementation 'org.tensorflow:tensorflow-lite-gpu:0.0.0-nightly'`
- Python version:
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory: OpenGL ES 3.2 available on the phone

The project has been compiled in Android Studio using these dependencies:
`dependencies { implementation fileTree(dir: 'libs', include: ['*.jar','*.aar']) implementation 'com.android.support:appcompat-v7:28.0.0' implementation 'com.android.support:design:28.0.0' implementation 'org.tensorflow:tensorflow-lite:0.0.0-nightly' implementation 'org.tensorflow:tensorflow-lite-gpu:0.0.0-nightly' } 
`
**Describe the current behavior**
We are facing this error unable to understand the exact issue:
`CPU.ModifyGraphWithDelegate is disallowed when graph is immutable.
       at org.tensorflow.lite.NativeInterpreterWrapper.run(Native Method)

   java.lang.IllegalArgumentException: Internal error: Failed to run on the given Interpreter: Next operations are not supported by GPU delegate:
   CUSTOM TFLite_Detection_PostProcess: Operation is not supported.
   First 63 operations will run on the GPU, and the remaining 1 on the CPU.TfLiteGpuDelegate Invoke: Delegate should run on the same thread where it was initialized.Node number 64 (TfLiteGpuDelegate) failed to invoke.
   
       at org.tensorflow.lite.NativeInterpreterWrapper.run(Native Method)
       at org.tensorflow.lite.NativeInterpreterWrapper.run(NativeInterpreterWrapper.java:149)
       at org.tensorflow.lite.Interpreter.runForMultipleInputsOutputs(Interpreter.java:275)
       at org.tensorflow.lite.examples.detection.tflite.TFLiteObjectDetectionAPIModel.recognizeImage(TFLiteObjectDetectionAPIModel.java:228)
       at com.demo.webview.bt.webviewbtdemo.basic.TFLiteWrapper$5.run(TFLiteWrapper.java:360)
       at android.os.Handler.handleCallback(Handler.java:873)`
**Describe the expected behavior**

**Code to reproduce the issue**
`public class TFLiteObjectDetectionAPIModel implements Classifier {
  private static final Logger LOGGER = new Logger();

  // Only return this many results.
  private static final int NUM_DETECTIONS = 10;
  // Float model
  private static final float IMAGE_MEAN = 128.0f;
  private static final float IMAGE_STD = 128.0f;
  // Number of threads in the java app
  private static final int NUM_THREADS = 4;
  private boolean isModelQuantized;
  // Config values.
  private int inputSize;
  // Pre-allocated buffers.
  private Vector<String> labels = new Vector<String>();
  private int[] intValues;
  // outputLocations: array of shape [Batchsize, NUM_DETECTIONS,4]
  // contains the location of detected boxes
  private float[][][] outputLocations;
  // outputClasses: array of shape [Batchsize, NUM_DETECTIONS]
  // contains the classes of detected boxes
  private float[][] outputClasses;
  // outputScores: array of shape [Batchsize, NUM_DETECTIONS]
  // contains the scores of detected boxes
  private float[][] outputScores;
  // numDetections: array of shape [Batchsize]
  // contains the number of detected boxes
  private float[] numDetections;

  private ByteBuffer imgData;

  private Interpreter tflite;

  /** Options for configuring the Interpreter. */
  private final Interpreter.Options tfliteOptions = new Interpreter.Options();

  /** The loaded TensorFlow Lite model. */
  private MappedByteBuffer tfliteModel;

  private TFLiteObjectDetectionAPIModel() {}

  /** holds a gpu delegate */
  GpuDelegate gpuDelegate = null;

  /** Memory-map the model file in Assets. */
  private static MappedByteBuffer loadModelFile(AssetManager assets, String modelFilename)
      throws IOException {
    AssetFileDescriptor fileDescriptor = assets.openFd(modelFilename);
    FileInputStream inputStream = new FileInputStream(fileDescriptor.getFileDescriptor());
    FileChannel fileChannel = inputStream.getChannel();
    long startOffset = fileDescriptor.getStartOffset();
    long declaredLength = fileDescriptor.getDeclaredLength();

    return fileChannel.map(FileChannel.MapMode.READ_ONLY, startOffset, declaredLength);
  }

  private void recreateInterpreter() {
    if (tflite != null) {
      tflite.close();
      tflite = new Interpreter(tfliteModel, tfliteOptions);
    }
  }

  public void useGpu() {
    if (gpuDelegate == null) {
      gpuDelegate = new GpuDelegate();
      tfliteOptions.addDelegate(gpuDelegate);
      recreateInterpreter();
    }
  }

  /**
   * Initializes a native TensorFlow session for classifying images.
   *
   * @param assetManager The asset manager to be used to load assets.
   * @param modelFilename The filepath of the model GraphDef protocol buffer.
   * @param labelFilename The filepath of label file for classes.
   * @param inputSize The size of image input
   * @param isQuantized Boolean representing model is quantized or not
   */
  public static Classifier create(
      final AssetManager assetManager,
      final String modelFilename,
      final String labelFilename,
      final int inputSize,
      final boolean isQuantized)
      throws IOException {
    final TFLiteObjectDetectionAPIModel d = new TFLiteObjectDetectionAPIModel();
    //d.setUseNNAPI(true);
    d.useGpu();
    InputStream labelsInput = null;
    String actualFilename = labelFilename.split("file:///android_asset/")[1];
    labelsInput = assetManager.open(actualFilename);
    BufferedReader br = null;
    br = new BufferedReader(new InputStreamReader(labelsInput));
    String line;
    while ((line = br.readLine()) != null) {
      LOGGER.w(line);
      d.labels.add(line);
    }
    br.close();

    d.inputSize = inputSize;

    try {
      d.tflite = new Interpreter(loadModelFile(assetManager, modelFilename));
    } catch (Exception e) {
      throw new RuntimeException(e);
    }

    d.isModelQuantized = isQuantized;
    // Pre-allocate buffers.
    int numBytesPerChannel;
    if (isQuantized) {
      numBytesPerChannel = 1; // Quantized
    } else {
      numBytesPerChannel = 4; // Floating point
    }
    d.imgData = ByteBuffer.allocateDirect(1 * d.inputSize * d.inputSize * 3 * numBytesPerChannel);
    d.imgData.order(ByteOrder.nativeOrder());
    d.intValues = new int[d.inputSize * d.inputSize];

    d.tflite.setNumThreads(NUM_THREADS);
    d.outputLocations = new float[1][NUM_DETECTIONS][4];
    d.outputClasses = new float[1][NUM_DETECTIONS];
    d.outputScores = new float[1][NUM_DETECTIONS];
    d.numDetections = new float[1];
    return d;
  }

  @Override
  public List<Recognition> recognizeImage(final Bitmap bitmap) {
    // Log this method so that it can be analyzed with systrace.
    Trace.beginSection("recognizeImage");

    Trace.beginSection("preprocessBitmap");
    // Preprocess the image data from 0-255 int to normalized float based
    // on the provided parameters.
    bitmap.getPixels(intValues, 0, bitmap.getWidth(), 0, 0, bitmap.getWidth(), bitmap.getHeight());
  //  useGpu();
    imgData.rewind();
    for (int i = 0; i < inputSize; ++i) {
      for (int j = 0; j < inputSize; ++j) {
        int pixelValue = intValues[i * inputSize + j];
        if (isModelQuantized) {
          // Quantized model
          imgData.put((byte) ((pixelValue >> 16) & 0xFF));
          imgData.put((byte) ((pixelValue >> 8) & 0xFF));
          imgData.put((byte) (pixelValue & 0xFF));
        } else { // Float model
          imgData.putFloat((((pixelValue >> 16) & 0xFF) - IMAGE_MEAN) / IMAGE_STD);
          imgData.putFloat((((pixelValue >> 8) & 0xFF) - IMAGE_MEAN) / IMAGE_STD);
          imgData.putFloat(((pixelValue & 0xFF) - IMAGE_MEAN) / IMAGE_STD);
        }
      }
    }
    Trace.endSection(); // preprocessBitmap

    // Copy the input data into TensorFlow.
    Trace.beginSection("feed");
    outputLocations = new float[1][NUM_DETECTIONS][4];
    outputClasses = new float[1][NUM_DETECTIONS];
    outputScores = new float[1][NUM_DETECTIONS];
    numDetections = new float[1];

    Object[] inputArray = {imgData};
    Map<Integer, Object> outputMap = new HashMap<>();
    outputMap.put(0, outputLocations);
    outputMap.put(1, outputClasses);
    outputMap.put(2, outputScores);
    outputMap.put(3, numDetections);
    Trace.endSection();

    // Run the inference call.
    Trace.beginSection("run");
    tflite.runForMultipleInputsOutputs(inputArray, outputMap);
    Trace.endSection();

    // Show the best detections.
    // after scaling them back to the input size.
    final ArrayList<Recognition> recognitions = new ArrayList<>(NUM_DETECTIONS);
    for (int i = 0; i < NUM_DETECTIONS; ++i) {
      final RectF detection =
          new RectF(
              outputLocations[0][i][1] * inputSize,
              outputLocations[0][i][0] * inputSize,
              outputLocations[0][i][3] * inputSize,
              outputLocations[0][i][2] * inputSize);
      // SSD Mobilenet V1 Model assumes class 0 is background class
      // in label file and class labels start from 1 to number_of_classes+1,
      // while outputClasses correspond to class index from 0 to number_of_classes
      int labelOffset = 1;
      recognitions.add(
          new Recognition(
              "" + i,
              labels.get((int) outputClasses[0][i] + labelOffset),
              outputScores[0][i],
              detection));
    }
    Trace.endSection(); // "recognizeImage"
   // runInference();
    return recognitions;
  }`
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

**Please provide help or suggestion to resolve this issue**

**Comment by impjdi** [comment]
@Gmrevo 

I'm not clear on what the problem is.

**Comment by gauravzero** [comment]
Was this issue resolved?
Thanks

**Comment by SunitRoy2703** [comment]
I'm was getting the same problem - "java.lang.IllegalArgumentException: Internal error: Failed to apply delegate: ModifyGraphWithDelegate is disallowed when graph is immutable."

Context: we're creating a tflite depth estimation sample and below is the code for initializing the interpreter with the best options.

```kotlin
 init {
        // Initialize TFLite Interpreter
        val interpreterOptions = Interpreter.Options().apply {
            // Add the GPU Delegate if supported.
            // See -> https://www.tensorflow.org/lite/performance/gpu#android
            if ( CompatibilityList().isDelegateSupportedOnThisDevice ) {
                Logger.logInfo( "GPU Delegate is supported on this device." )
                addDelegate( GpuDelegate( CompatibilityList().bestOptionsForThisDevice ))
            }
            else {
                // Number of threads for computation
                setNumThreads( NUM_THREADS )
            }
            // Add the NNApiDelegate if supported.
            // See -> https://www.tensorflow.org/lite/performance/nnapi#initializing_the_nnapi_delegate
            if ( Build.VERSION.SDK_INT >= Build.VERSION_CODES.P ) {
                Logger.logInfo( "NNAPI is supported on this device." )
                addDelegate( NnApiDelegate() )
            }
        }
        interpreter = Interpreter(FileUtil.loadMappedFile( context, modelFileName ) , interpreterOptions )
        Logger.logInfo( "TFLite interpreter created." )
    }
```

Our mistake was to add both NNAPI and GPU check in the code, and calling ```addDelegate()``` both the times, you should only use one kind of delegate. look if you're doing the same!
I suggest using GPU delegate if you're sharing your code between IOS and Android, as it can be used on both Android and iOS, and using NNAPI and Hexagon if your writing code only for android.

For more details go through this: https://www.tensorflow.org/lite/performance/delegates#delegates_by_platform

**Comment by mohantym** [comment]
Hi @Gmrevo !
We are checking to see whether you still need help in this issue . 
All the Ops are not supported in GPU delegate, So some operation will be skipped by gpu delegates. You can find the [supported ops list ](https://www.tensorflow.org/lite/performance/gpu#supported_ops)here.


As @SunitRoy2703 suggested, you can [benchmark ](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/tools/benchmark)your model against other delegates too( NNAPI, Open CL) for getting  optimum inference time.  

You can also build delegate specific to your mobile using [bazel build commands ](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/delegates/gpu#building-and-runtime:~:text=Building%20and%20Runtime).

Thank you!
