### ISSUE TITLE
[TF 2.0 keras] Conv2D looses shapes with dilation rate other than 1

### ISSUE THREAD

**Issue by lytkarinskiy** [tensorflow/tensorflow#30910]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): macOS Mojave
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): v2.0.0-beta0-16-g1d91213fe7 2.0.0-beta1
- Python version: 3.7
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

**Describe the current behavior**
When I use Conv2D layer with dilation rate other than 1 output looses shapes
**Describe the expected behavior**
I expect to see calculated shape with None only in first dimension
**Code to reproduce the issue**
```python
from tensorflow.keras import Input
from tensorflow.keras.layers import Conv2D

tensor = Input(shape=(512,512,3))

y_1 = Conv2D(filters=256, kernel_size=1, dilation_rate=1, name='dilation_1')(tensor)
y_6 = Conv2D(filters=256, kernel_size=1, dilation_rate=6, name='dilation_6')(tensor)

print(y_1)
print(y_6)
```

**Other info / logs**
Output is:
> Tensor("dilation_1/Identity:0", shape=(None, 512, 512, 256), dtype=float32)
Tensor("dilation_6/Identity:0", shape=(None, None, None, 256), dtype=float32)

**Comment by gadagashwini** [comment]
I could able to reproduce the issue with Tensorflow 2.0.0.beta1 on Colab. Please take a look at gist of [Colab](https://colab.research.google.com/drive/1swIU2bAUBTdgeEcriw_SAJiQtiXtMBLh).

**Comment by jvishnuvardhan** [comment]
@lytkarinskiy This was resolved in tf-nightly-builds. Please check the [gist here](https://colab.sandbox.google.com/gist/jvishnuvardhan/8d0b507a3f1d1972012542f6c440c110/tf_30910_dilation.ipynb). 

I am closing the issue. Feel free to open if the issue persists. Thanks!
