### ISSUE TITLE
BatchNormalization() does not work with autograph

### ISSUE THREAD

**Issue by dgriffiths3** [tensorflow/tensorflow#30928]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 16.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: n/a
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.0-beta
- Python version: 3.6
- Bazel version (if compiling from source): n/a
- GCC/Compiler version (if compiling from source): n/a
- CUDA/cuDNN version: 10.0
- GPU model and memory: Nvidia 1060 6GB

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**

When using the `tf.keras.layers.BatchNormalization()` function using autograph the following error occurs: `ValueError: ('Input has undefined rank:', TensorShape(None))`.

**Describe the expected behavior**

Model will compile and train without issue. As it does without the `@tf.function` decorator.

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

Here is an example of a simple model where this error would occur. This will train without problem in eager mode, but the addition of the `@tf.function` decorator causes the error.

```
class MyModel(tf.keras.Model):

    def__init__(self):
        super(MyModel, self).__init__()

        self.conv1 = tf.keras.layers.Conv2d(8)
        self.bn1 = tf.keras.layers.BatchNormalization()
        self.conv2 = tf.keras.layers.Conv2d(8)
        self.bn2 = tf.keras.layers.BatchNormalization()

    def call(inputs):

        net = self.conv1(inputs)
        net = self.bn1(net)
        net = self.conv2(inputs)
        net = self.bn2(net)

        return tf.nn.softmax(net)

```
**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

```
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/base_layer.py", line 594, in __call__
    self._maybe_build(inputs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/base_layer.py", line 1713, in _maybe_build
    self.build(input_shapes)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/layers/normalization.py", line 252, in build
    raise ValueError('Input has undefined rank:', input_shape)
ValueError: ('Input has undefined rank:', TensorShape(None))
```

**Comment by gadagashwini** [comment]
@dgriffiths3 , Please provide us the complete code to reproduce the issue. Thanks!

**Comment by dgriffiths3** [comment]
I wrote a small script to recreate the issue using standard `tf.keras.layers` ops and there was no problem. I have now found out my error comes when I pass in a tensor from a custom c++ op. The tensor returned from the custom op does not contain the shape information. I'll close this as it's not a bug!
