### ISSUE TITLE
Wrong URL for Cuda download in dll not found error message

### ISSUE THREAD

**Issue by monatis** [tensorflow/tensorflow#30935]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windos 10 64Bit
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): Binary
- TensorFlow version: 2.0.0-beta1
- Python version: 3.6.8
- Installed using virtualenv? pip? conda?: pip
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 10.0 / 7.5
- GPU model and memory: 1050

**Describe the problem**
When Tensorflow 2.0.0-beta1 is installed with pip, the error message stating that dll for Cuda is not found gives a wrong URL to [Cuda 9.0](https://developer.nvidia.com/cuda-90-download-archive) instead of [10.0, which is required by TF 2.0](https://developer.nvidia.com/cuda-10.0-download-archive).

**Provide the exact sequence of commands / steps that you executed before running into the problem**
- `pip install tensorflow-gpu==2.0.0-beta1`

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

> >>> import tensorflow as tf
> Traceback (most recent call last):
>   File "C:\ProgramData\Anaconda3\envs\py368\lib\site-packages\tensorflow\python\platform\self_check.py", line 75, in preload_check
>     ctypes.WinDLL(build_info.cudart_dll_name)
>   File "C:\ProgramData\Anaconda3\envs\py368\lib\ctypes\__init__.py", line 348, in __init__
>     self._handle = _dlopen(self._name, mode)
> OSError: [WinError 126] The specified module could not be found
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "C:\ProgramData\Anaconda3\envs\py368\lib\site-packages\tensorflow\__init__.py", line 40, in <module>
>     from tensorflow.python.tools import module_util as _module_util
>   File "C:\ProgramData\Anaconda3\envs\py368\lib\site-packages\tensorflow\python\__init__.py", line 49, in <module>
>     from tensorflow.python import pywrap_tensorflow
>   File "C:\ProgramData\Anaconda3\envs\py368\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 30, in <module>
>     self_check.preload_check()
>   File "C:\ProgramData\Anaconda3\envs\py368\lib\site-packages\tensorflow\python\platform\self_check.py", line 82, in preload_check
>     % (build_info.cudart_dll_name, build_info.cuda_version_number))
> ImportError: Could not find 'cudart64_100.dll'. TensorFlow requires that this DLL be installed in a directory that is named in your %PATH% environment variable. Download and install CUDA 10.0 from this URL: https://developer.nvidia.com/cuda-90-download-archive

**Comment by ravikyram** [comment]
Just to verify did you get chance to follow instructions from [TensorFlow ](https://www.tensorflow.org/install/gpu)website .Please, let us know. Thanks!

**Comment by monatis** [comment]
@ravikyram I've already installed it correctly, just reporting a mistyped error message in source code.

**Comment by hwdong-net** [comment]
I have the same problem!
