### ISSUE TITLE
[BUG] tf.saved_model.load cannot load Keras compiled model

### ISSUE THREAD

**Issue by captain-pool** [tensorflow/tensorflow#30932]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Elementary OS Loki
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): Binary
- TensorFlow version (use command below): tf-nightly-2.0-preview==2.0.0.dev20190601
- Python version: 3.5.2
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
tf.saved_model.load cannot load compiled keras model, saved as SavedModel in graph mode.
**Describe the expected behavior**
No Error Expected
**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.
```python3
import tensorflow as tf
model = tf.keras.models.Sequential()
model.compile(optimizer="adam", loss="mean_squared_error")
tf.saved_model.save(model, "/tmp/model")
```
Now loading the model:
```python3
import tensorflow as tf
tf.compat.v1.disable_eager_execution()
tf.saved_model.load("/tmp/model")
```
This raises the following error:
`ValueError: '_RestoredOptimizer' is not a valid scope name`
**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/rick/tf2.0/env/lib/python3.5/site-packages/tensorflow/python/saved_model/load.py", line 407, in load
    export_dir)
  File "/home/rick/tf2.0/env/lib/python3.5/site-packages/tensorflow/python/saved_model/load.py", line 58, in __init__
    self._load_all()
  File "/home/rick/tf2.0/env/lib/python3.5/site-packages/tensorflow/python/saved_model/load.py", line 157, in _load_all
    node, setter = self._recreate(proto)
  File "/home/rick/tf2.0/env/lib/python3.5/site-packages/tensorflow/python/saved_model/load.py", line 240, in _recreate
    return factory[kind]()
  File "/home/rick/tf2.0/env/lib/python3.5/site-packages/tensorflow/python/saved_model/load.py", line 227, in <lambda>
    "user_object": lambda: self._recreate_user_object(proto.user_object),
  File "/home/rick/tf2.0/env/lib/python3.5/site-packages/tensorflow/python/saved_model/load.py", line 244, in _recreate_user_object
    looked_up = revived_types.deserialize(proto)
  File "/home/rick/tf2.0/env/lib/python3.5/site-packages/tensorflow/python/saved_model/revived_types.py", line 166, in deserialize
    return (type_registration.from_proto(proto), type_registration.setter)
  File "/home/rick/tf2.0/env/lib/python3.5/site-packages/tensorflow/python/saved_model/revived_types.py", line 87, in from_proto
    return self._object_factory(proto)
  File "/home/rick/tf2.0/env/lib/python3.5/site-packages/tensorflow/python/keras/optimizer_v2/optimizer_v2.py", line 1039, in <lambda>
    object_factory=lambda proto: _RestoredOptimizer(),
  File "/home/rick/tf2.0/env/lib/python3.5/site-packages/tensorflow/python/keras/optimizer_v2/optimizer_v2.py", line 1025, in __init__
    super(_RestoredOptimizer, self).__init__("_RestoredOptimizer")
  File "/home/rick/tf2.0/env/lib/python3.5/site-packages/tensorflow/python/keras/optimizer_v2/optimizer_v2.py", line 263, in __init__
    with backend.name_scope(self._name) as name_scope:
  File "/home/rick/tf2.0/env/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 6523, in __enter__
    return self._name_scope.__enter__()
  File "/usr/lib/python3.5/contextlib.py", line 59, in __enter__
    return next(self.gen)
  File "/home/rick/tf2.0/env/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 4320, in name_scope
    raise ValueError("'%s' is not a valid scope name" % name)
ValueError: '_RestoredOptimizer' is not a valid scope name
```
CC:
@vbardiovskyg 
@srjoglekar246

**Comment by ravikyram** [comment]
I have tried on colab with TF version tf-nightly-2.0-preview==2.0.0.dev20190601 and was able to reproduce the issue.Please, find the [gist](https://colab.research.google.com/drive/1853YfSmRK0AtNnrK5uiu4poZVmGPt7JL) here.Thanks!

**Comment by jvishnuvardhan** [comment]
@captain-pool I cannot reproduce the issue when I use `!pip install tf-nightly-2.0-preview==2.0.0.dev20190718`. Please check the gist [here](https://colab.sandbox.google.com/gist/jvishnuvardhan/cd9804dbb3f558688dbc8c339f1e269f/untitled59.ipynb). This issue might have been resolved after `2.0.0.dev20190601` version. Thanks!

**Comment by captain-pool** [comment]
> @captain-pool I cannot reproduce the issue when I use `!pip install tf-nightly-2.0-preview==2.0.0.dev20190718`. Please check the gist [here](https://colab.sandbox.google.com/gist/jvishnuvardhan/cd9804dbb3f558688dbc8c339f1e269f/untitled59.ipynb). This issue might have been resolved after `2.0.0.dev20190601` version. Thanks!

I tried on 2.0.0-dev20190723, Looks like it's Solved. Thanks for the heads up :)
Closing the issue.
CC:
@vbardiovskyg 
@srjoglekar246

**Comment by ktobah** [comment]
Hi,
I am having the same issue with TF 1.14.0
Is there any other solution besides upgrading TensorFlow to 2.0?

**Comment by captain-pool** [comment]
Hey @ktobah, don't compile the model before saving. That should help you fix this.

**Comment by ktobah** [comment]
Hey @captain-pool,
Thank you for your response. Actually, it is a pre-trained model. All I did was loading it again using 

> ft.keras.models.load_model(model_path)

I did not compile it or anything.

**Comment by captain-pool** [comment]
Hey @ktobah, just to confirm are you trying to load .h5 file, or is it a SavedModel file?

**Comment by Ruoyingw** [comment]
I'm having the same issue.

**Comment by ktobah** [comment]
Hi @captain-pool,
What I do is the following:
1. I load a keras h5 model with ft.keras.models.load_model(model_path)
2. Don't compile or anything, just save it as SavedModel with tf.saved_model.save(model, path) 
Everything works fine here. Then,
3. Load the SavedModel with tf.saved_model.load(path). I get the error:
> '_RestoredOptimizer' is not a valid scope name
When I tried to save with tf.saved_model.simple_save(), it worked fine and I could load the SavedModel just fine.
I am using tf 1.14.0
