### ISSUE TITLE
unable to load trained model

### ISSUE THREAD

**Issue by ankitgc1** [tensorflow/tensorflow#30942]
I trained the NMT model on my RTX2080 ti. I saved the model by

checkpoint_dir = './training_checkpoints'
checkpoint_prefix = os.path.join(checkpoint_dir, "ckpt")
checkpoint = tf.train.Checkpoint(optimizer=optimizer,
                                 encoder=encoder,
                                 decoder=decoder)

and in the training step 

if (epoch + 1) % 2 == 0:
   checkpoint.save(file_prefix = checkpoint_prefix)

and after training, I am loading the trained model by

checkpoint.restore(tf.train.latest_checkpoint(checkpoint_dir))

But my model's output is random. 

### System information
- ** TensorFlow version == 1.14.0(installed through " conda install -c anaconda tensorflow-gpu ")
- **OS Platform and Distribution (e.g., Linux Ubuntu 18.04)**:
- **Python version == 3.7
- **CUDA/cuDNN version**:== 10
- **GPU model and memory**: 11GB

and I am getting this at the end

W0723 07:13:25.044782 140413660407616 util.py:244] Unresolved object in checkpoint: (root).optimizer.beta1_power
W0723 07:13:25.044880 140413660407616 util.py:244] Unresolved object in checkpoint: (root).optimizer.beta2_power
W0723 07:13:25.044922 140413660407616 util.py:248] Unused attribute in object (root).decoder.embedding: ['OBJECT_CONFIG_JSON']
W0723 07:13:25.044954 140413660407616 util.py:248] Unused attribute in object (root).decoder.gru: ['OBJECT_CONFIG_JSON']
W0723 07:13:25.044982 140413660407616 util.py:248] Unused attribute in object (root).decoder.fc: ['OBJECT_CONFIG_JSON']
W0723 07:13:25.045008 140413660407616 util.py:248] Unused attribute in object (root).decoder.W1: ['OBJECT_CONFIG_JSON']
W0723 07:13:25.045034 140413660407616 util.py:248] Unused attribute in object (root).decoder.W2: ['OBJECT_CONFIG_JSON']
W0723 07:13:25.045060 140413660407616 util.py:248] Unused attribute in object (root).decoder.V: ['OBJECT_CONFIG_JSON']
W0723 07:13:25.045086 140413660407616 util.py:248] Unused attribute in object (root).encoder.embedding: ['OBJECT_CONFIG_JSON']
W0723 07:13:25.045122 140413660407616 util.py:248] Unused attribute in object (root).encoder.gru: ['OBJECT_CONFIG_JSON']
W0723 07:13:25.045150 140413660407616 util.py:252] A checkpoint was restored (e.g. tf.train.Checkpoint.restore or tf.keras.Model.load_weights) but not all checkpointed values were used. See above for specific issues. Use expect_partial() on the load status object, e.g. tf.train.Checkpoint.restore(...).expect_partial(), to silence these warnings, or use assert_consumed() to make the check explicit. See https://www.tensorflow.org/alpha/guide/checkpoints#loading_mechanics for details.

**Comment by anush-o** [comment]
@ankitgc1 ,
In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thanks!

**Comment by ankitgc1** [comment]
I changed the model from NMT to for chatbot here are some code snippet.

training phase 
![Screenshot from 2019-07-25 14-39-49](https://user-images.githubusercontent.com/35380717/61861896-7e890500-aeea-11e9-9632-867c823b4f5a.png)


restoring phase

![Screenshot from 2019-07-25 14-39-59](https://user-images.githubusercontent.com/35380717/61861921-8b0d5d80-aeea-11e9-8a04-082905f3a953.png)

**Comment by anush-o** [comment]
@ankitgc1 ,
Can you please provide executable code.Thanks!

**Comment by ankitgc1** [comment]
@anush-o 
you can find all files and code here
https://github.com/ankitgc1/Chatbot-in-tensorflow

**Comment by anush-o** [comment]
@ankitgc1 ,
When tried executing the code by cloning, I got the output as per the screenshot attached.
![Screenshot from 2019-07-31 13-59-46](https://user-images.githubusercontent.com/52397990/62197282-32800980-b39d-11e9-8c10-d800c1029afe.png)
Thanks!

**Comment by ankitgc1** [comment]
@anush-o 
this is random output. first you have to train the model. you can do this thing by just uncommenting the commenting part.

thanks.

**Comment by jvishnuvardhan** [comment]
This is not Build/Installation or Bug/Performance issue. Please post this kind of support questions at [Stackoverflow](https://stackoverflow.com/questions/tagged/tensorflow). There is a big community to support and learn from your questions. GitHub is mainly for addressing bugs in installation and performance. Thanks!
