### ISSUE TITLE
The use of List and Tuple is vague in Tensorflow tf.data.Dataset.map.

### ISSUE THREAD

**Issue by kzhangair** [tensorflow/tensorflow#30948]
System information
Have I written custom code (as opposed to using a stock example script provided in TensorFlow): no
OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 16.04
TensorFlow installed from (source or binary): binary
TensorFlow version (use command below): 1.14.0
Python version: 3.7.3
CUDA/cuDNN version: 10.1.168 / 7.6.0 but also failing in CPU-only mode
GPU model and memory: GTX 1080 8G
Exact command to reproduce:
```
import tensorflow as tf
input = tf.constant([10,20,30])
ds = tf.data.Dataset.from_tensor_slices(input)
#Out: <DatasetV1Adapter shapes: (), types: tf.int32>

ds1=ds.map(lambda x: [x+1, x+2, x+3])
#Out: <DatasetV1Adapter shapes: ((), (), ()), types: (tf.int32, tf.int32, tf.int32)>
ds2=ds.map(lambda x: [[x+1, x+2, x+3]])
#Out: <DatasetV1Adapter shapes: ((3,),), types: (tf.int32,)>
ds3=ds.map(lambda x: ([x+1, x+2, x+3]))
#Out: <DatasetV1Adapter shapes: ((), (), ()), types: (tf.int32, tf.int32, tf.int32)>
```
I think tensorflow treats tuple as nested structures of Tensor and list as tensor, as shown in [link](https://github.com/tensorflow/tensorflow/issues/20481). 
However, `tf.data.Dataset.map` doesn't behave like this in above code. I expect `ds1, d2, ds3` to be of shape `[3, ], [1, 3], ([3, ], )` respectively,  rather than `((), (), ()), ((3,),), ((), (), ())` since top-level list [] should be treated as tensor rather than nested structure.
A [solution](https://stackoverflow.com/questions/57142462/something-strange-about-output-tensor-shape-of-tf-data-dataset-map/57146524?noredirect=1#comment100834064_57146524) is that I use `tf.convert_to_tensor` to force convert `[x+1, x+2, x+3]` to a single tensor but it's not elegant.

ps: It's confusing to output shape only with tuple, why not using list to represent shape and using tuple to represent nested structure of tensor jsut like 
the output of Tensor.shape and Tensor.get_shape. e.g. `#Out: <DatasetV1Adapter shapes: ([],[],[]), types: (tf.int32, tf.int32, tf.int32)>`

**Comment by Saduf2019** [comment]
@kzhangair 
Is this still an issue

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.
