### ISSUE TITLE
Subclassing Model prevents the computation of intermediate values in graph mode

### ISSUE THREAD

**Issue by DeepBlender** [tensorflow/tensorflow#30955]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
Google Colab
- TensorFlow version (use command below):
Tensorflow 2.0 beta 1

**Describe the current behavior**
Computing intermediate values within a subclassed model doesn't work in graph mode.

**Describe the expected behavior**
It should most likely work, as it was possible in TensorFlow 1.x.

**Code to reproduce the issue**
Try it directly in Google Colab. Setting 'use_eager_mode' to True/False switches between the two cases.
https://gist.github.com/DeepBlender/6ab324ab3b14552109979a97bf4acb8f

**Comment by gadagashwini** [comment]
I tried executing the given code on colab and I am able to reproduce the issue with `use_eager_mode=False`. Thanks!

**Comment by ymodak** [comment]
The code provided snippet fails with same message in TF 2.X (eager mode disabled) as well as TF 1.X (eager disabled by default). Can you please confirm if you are able to execute this script successfully in  TF 1.X?

**Comment by DeepBlender** [comment]
@ymodak sorry for the confusion, I meant to say similar functionality, but that does not seem to be accurate either.
It has been my understanding that in TensorFlow 2.0 it should be possible to switch between graph and eager mode flawlessly. This is a relatively simple example where it doesn't work.

**Comment by DeepBlender** [comment]
Even though, the example I presented has a workaround, a minor change will eliminate this workaround. If you add "x = x - 0.5" in "call", the code simply doesn't work anymore and there is no way to compute the intermediate results.

As this way of using the Model class is presented as pretty much the "TensorFlow 2.0 way", this issue is reducing the flexibility quite significantly.

**Comment by RaphaelMeudec** [comment]
@ymodak I'm also having trouble creating subgraph for model using the subclassing API (on TF2). 

Google Colab: https://colab.research.google.com/drive/1kRbgCtF2CIfiK3F75FjDZiI241cfPC-f

Code below:

```python
import numpy as np
import tensorflow as tf

NUM_CLASSES = 10
TARGET_LAYER_NAME = 'target_layer_name'

# Create the Subclassing API Class
class SubclassedModel(tf.keras.Model):
  def __init__(self, name='subclassed'):
    super(SubclassedModel, self).__init__(name=name)
    self.conv_1 = tf.keras.layers.Conv2D(filters=32, kernel_size=(3, 3), activation='relu')
    self.conv_2 = tf.keras.layers.Conv2D(filters=64, kernel_size=(3, 3), activation='relu', name=TARGET_LAYER_NAME)
    self.maxpool_1 = tf.keras.layers.MaxPool2D(pool_size=(2, 2))

    self.flatten = tf.keras.layers.Flatten()

    self.dense_1 = tf.keras.layers.Dense(NUM_CLASSES, activation='softmax')

  def call(self, inputs, **kwargs):
    x = inputs
    for layer in [self.conv_1, self.conv_2, self.maxpool_1, self.flatten, self.dense_1]:
        x = layer(x)

    return x

  def compute_output_shape(self, input_shape):
    shape = tf.TensorShape(input_shape).as_list()
    return tf.TensorShape([shape[0], NUM_CLASSES])

# Initialize a model using the subclassing API
model = SubclassedModel()
model(np.random.random((4, 28, 28, 1)).astype('float32'))  # Sample call to build the model
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

# Trying to fit some random data, all goes well
training_size = 256
sample_x = np.random.random((training_size, 28, 28, 1)).astype('float32')
sample_y = np.eye(NUM_CLASSES)[np.random.choice(NUM_CLASSES, training_size)]
history = model.fit(sample_x, sample_y, epochs=3, verbose=0)

# Trying to extract a subgraph
submodel = tf.keras.Model([model.inputs], [model.get_layer(TARGET_LAYER_NAME).output])
submodel.summary()

# Trying the same thing with sequential API

model_seq = tf.keras.Sequential([
  tf.keras.layers.Conv2D(filters=32, kernel_size=(3, 3), activation='relu', input_shape=(28, 28, 1)),
  tf.keras.layers.Conv2D(filters=64, kernel_size=(3, 3), activation='relu', name=TARGET_LAYER_NAME),
  tf.keras.layers.MaxPool2D(pool_size=(2, 2)),
  tf.keras.layers.Flatten(),
  tf.keras.layers.Dense(NUM_CLASSES, activation='softmax'),
])
model_seq.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])
model_seq.fit(sample_x, sample_y, epochs=3, verbose=0)

submodel_seq = tf.keras.Model([model_seq.inputs], [model_seq.get_layer(TARGET_LAYER_NAME).output])
submodel_seq.summary()
```

Stacktrace is:
![image](https://user-images.githubusercontent.com/12402673/62143005-921fdb80-b2ef-11e9-9c10-ac7285bf4a2d.png)

Is there a workaround for this?

**Comment by omalleyt12** [comment]
@DeepBlender @RaphaelMeudec 

In general it's not possible to extract subgraphs of subclassed Models. For those use cases, please use Functional API models

Functional API models are described by their DAG, but for subclassed Models, the code is the definition and in general it's not possible to extract a DAG from them

Please note that even in 2.0, `model.fit` executes inside its own `tf.function` (similar to 1.x graph style). To run `model.fit` eagerly, compile your Model with `model.compile(..., run_eagerly=True)`

**Comment by DeepBlender** [comment]
Thanks for the clarification!

At this point, the documentation feels very misleading in the sense that "Everything is Possible in TensorFlow 2.0!" kind of sense. For me, it reads like: Do whatever you want. (Intentionally exaggerated of course!)
However, those details are missing (as far as I can see), but they are certainly very important. Should I create a new issue to point to this deficiency in the documentation out or can we repurpose this issue?

**Comment by roymiles** [comment]
Has there been any update on this limitation?

**Comment by misssprite** [comment]
> Thanks for the clarification!
> 
> At this point, the documentation feels very misleading in the sense that "Everything is Possible in TensorFlow 2.0!" kind of sense. For me, it reads like: Do whatever you want. (Intentionally exaggerated of course!)
> However, those details are missing (as far as I can see), but they are certainly very important. Should I create a new issue to point to this deficiency in the documentation out or can we repurpose this issue?

As it allows DAG definition, it will be confusing to have output bound to layers in the functional and subclassing model api. 
For example, consider a simple param sharing case:
```
dense = Dense(256, activation='relu')
x = dense(x)
x = dense(x)
```
What should be bound to the output of the 'dense' layer? A list seems work, but that conflict with layer having multiple outputs.
In sequential api, the model is linear, and things are simple. In the DAG case, it'd be better to operate manually.
