### ISSUE TITLE
What can replace 'initializer = tf.contrib.layers.xavier_initializer_conv2d()' in tensorflow 2.0?

### ISSUE THREAD

**Issue by it-is-a-username** [tensorflow/tensorflow#30959]
Now that tensorflow has no attribute 'contrib'. Thanks a lot!

**Comment by lufol** [comment]
You can find the Glorot initializer which is a different name for the Xavier initializer here: `tf.keras.initializers.GlorotNormal`

I hope this helps!

**Comment by it-is-a-username** [comment]
@lufol It really works. Thank you!

**Comment by ravikyram** [comment]
Can we close this issue as it was resolved.Thanks!

**Comment by ravikyram** [comment]
I am closing this issue as it was resolved.Thanks!

**Comment by jitendra-dexninja** [comment]
tf.contrib.layers.xavier_initializer_conv2d not working in tf2. Resolution?
