### ISSUE TITLE
TF-TRT does not return  correct batch size.

### ISSUE THREAD

**Issue by sgambient** [tensorflow/tensorflow#30969]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 16.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below):1.13.1
- Python version:2.7
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:10.1
- GPU model and memory:T4

**Describe the current behavior**
TF-TRT  seems to return max_batch_size instead of returning the feed batch size.  This breaks current code badly.

**Describe the expected behavior**
Return the batch size as plain TF.

**Code to reproduce the issue**
Should be simple to reproduce. 

**Other info / logs**
None

**Comment by anush-o** [comment]
@sgambient ,
In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thanks!

**Comment by sgambient** [comment]
Ok, will try to . It is related pyfunc that returns  2 arrays of different  first dimension ( e.g.  (25,5) (1,) ) .

**Comment by anush-o** [comment]
@sgambient ,
Please provide the code to reproduce the issue.Thanks!

**Comment by sgambient** [comment]
Found a workaround, but it is beyond ugly.   Could not find any  clean way of getting specific output from multi-output networks, although TF  does assign a unique name to each output.  The code is attached ( the formatting seems to be screwed up - but it is a simple piece of code that works). 

`
import numpy as np
import tensorflow as tf
import tensorflow.contrib.tensorrt as trt
input_names  = []
output_names = []
output_indexes = []

def netw():
    global output_names
    global input_names
    x = tf.placeholder(tf.float32, shape=(None,), name ='x')
    ys = tf.py_func(pyfunc1, [x], [tf.float32, tf.float32], name = 'y')
    print ("x", x)
    print ("ys", ys)
    input_names = [x.name]
    for y in ys:
        output_names.append(y.name.split(":")[0])
        output_indexes.append(int(y.name.split(":")[1]))

def pyfunc1(x):
    return np.sinh(x), np.array (x.shape, dtype=np.float32)

def run_meta():                                                                                
    # Inference with TF-TRT `MetaGraph` and checkpoint files workflow:                         
    graph = tf.Graph()                                                                         
    with graph.as_default():                                                                   
        netw()                                                                                 
        with tf.Session() as sess:                                                             
            # First create a `Saver` object (for saving and rebuilding a                       
            # model) and import your `MetaGraphDef` protocol buffer into it:                   
            #saver = tf.train.import_meta_graph("~/path/to/your/model.ckpt.meta")              
            # Then restore your training data from checkpoint files:                           
            #saver.restore(sess, "~/path/to/your/model.ckptx")                                 
            # Finally, freeze the graph:                                                       
            frozen_graph = tf.graph_util.convert_variables_to_constants(                       
                            sess,                                                              
                            tf.get_default_graph().as_graph_def(),                             
                            output_node_names=output_names                                     
                            )                                                                  
            # Now you can create a TensorRT inference graph from your                          
            # frozen graph:                                                                    
            trt_graph = trt.create_inference_graph(                                            
                            input_graph_def=frozen_graph,                                      
                            outputs=output_names,                                              
                            max_batch_size=25,                                                 
                            max_workspace_size_bytes=1024*1024*1024,                           
                            precision_mode="FP16")                                             
            # Import the TensorRT graph into a new graph and run:                              
            nodes = tf.import_graph_def(                                                       
                        trt_graph,                                                             
                        return_elements=input_names+output_names)                              
            for n in nodes:                                                                    
                print ( "n ", n)                                                               
            x = np.full ((10,), 0.5, dtype=np.float)                                           
            feed_dict = {nodes[0]: x}                                                          
            outputl = []                                                                       
            for i, n in enumerate (nodes[len(input_names):] ):                                 
                idx = output_indexes[i]                                                        
                #idx = 0                                                                       
                outputl.append(n.outputs[idx])                                                 
            ys = sess.run(outputl, feed_dict=feed_dict)                                        
            print ("x", x, " ys ", ys)                                                         
    print ("done run_meta")                                                                    
                                                                                               
if __name__ == '__main__':                                                                     
    run_meta()
`

**Comment by anush-o** [comment]
Please find the gist of [collab](https://colab.research.google.com/drive/1AmdeHVVcWFKhvmZRHFUR00UIsZQx42p1) executed for the given code TF version-1.13.Thanks!

**Comment by aaroey** [comment]
@sgambient I tried with your script but it doesn't output any errors. By `TF-TRT seems to return max_batch_size instead of returning the feed batch size. This breaks current code badly`, could you elaborate? E.g. what does it mean  by `return max_batch_size` and how does it `break current code`?

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.
