### ISSUE TITLE
Make Github templates more intuitive

### ISSUE THREAD

**Issue by lufol** [tensorflow/tensorflow#30960]
Hi,
Frequently I stumble upon issues on the Tensorflow githubpage which do not fill out the template properly. I was curious whether it's possible to make the filling in of the template more intuitive. 

For instance I think it would be nice if there were field to fill in the asked questions right after each question.
Furthermore it would be nice to be required to at least fill some part of the form before being able to submit it.

What do you think? Is it possible to change the template on github in such a way?
I believe that this would improve the speed of resolving issues.

**Comment by ymodak** [comment]
@lufol Thanks for your suggestion. We have an understanding here. Unfortunately at this point of time, GitHub interface has limitation where we cannot enforce users to fill all information asked by the template before posting their issue. However we do highly recommend them to do so.  We strive to help TensorFlow community to the best of our efforts and we revert to the issues wherever we can provide suitable resolution. Thanks!
