### ISSUE TITLE
Online convertor

### ISSUE THREAD

**Issue by MeysamSMH7** [tensorflow/tensorflow#30977]
hello,
i have too many problem to convert  a custom model, install python and ...
actually i have been tired to make a custom model and have asked from a person to make it.
its kind of hard to ask other people to do these simple things and hard to me cuz i dont know cant understand. can you make a online convertor for us?
we upload our images and you give us .tflite and .txt
i think its easy for you and it can save our time too. (i mean install python and other things)
tnx

or if you have it give me the link plz

**Comment by ravikyram** [comment]
This question is better asked on StackOverflow since it is not a bug or feature request. There is also a larger community that reads questions there and provide better and faster support for such issues. Thanks!

**Comment by MeysamSMH7** [comment]
i asked alot but its have to me because i dont know anything about python and im useing sources that i dont know that are they.
All developers always have same problem if you make an online convertor its going to save our time and your wont want to answer to our questions (which most of them are the same)
i lost too many project that because i cant work with python and got too many problems (and also download too many things from Nvidia website that i just lose my laptop`s space)
if its possible create an online convertor please
thanks

**Comment by MeysamSMH7** [comment]
@tensorflowbutler  @ravikyram so? is it possible ?
