### ISSUE TITLE
Excessive overhead with dense layer

### ISSUE THREAD

**Issue by ekuznetsov139** [tensorflow/tensorflow#30972]
Under normal circumstances, propagation through the dense layer should reduce to a matmul operation and possibly an activation operation. However, in tensorflow 1.14, it sometimes does not. This situation arises if the input to the dense layer is at least 3D and its dimensions are not fully determined at the time of graph construction.
If this happens, the framework calls the method tensordot(), which calls the internal method _tensordot_reshape(), which then attempts to determine how to reshape the tensor before calling matmul.
The GPU trace of the whole thing ends up looking like so:

```

[CUDA memcpy HtoD]
void tensorflow::GatherOpKernel<int, int, bool=1>(int const *, int const *, tensorflow::GatherOpKernel<int, int, bool=1>*, __int64, __int64, __int64, __int64)
void tensorflow::GatherOpKernel<int, int, bool=1>(int const *, int const *, tensorflow::GatherOpKernel<int, int, bool=1>*, __int64, __int64, __int64, __int64)
[CUDA memcpy DtoH]
void tensorflow::functor::BlockReduceKernel<int*, int*, int=256, tensorflow::functor::Prod<int>>(int*, int*, int, int, std::iterator_traits<tensorflow::functor::BlockReduceKernel<int*, int*, int=256, tensorflow::functor::Prod<int>>>::value_type)
[CUDA memcpy DtoH]
[CUDA memcpy DtoH]
volta_fp16_s884gemm_fp16_256x128_ldg8_f2f_nn
```

Note that these memcpy's are all for 4-8 bytes, but each one involves a syscall and a pointer validity check, so, they are not exactly free. 

And it is all unnecessary, because the framework does know how big the tensor is, on the CPU side, and something along these lines https://github.com/ekuznetsov139/tensor2tensor/commit/079f51f2c736d547cbd2b4bcfdcedb039827b93a would compute the shape without the use of the GPU.

It might seem trivial, but, in a graph with lots of small dense layers and especially when tensor cores are in play (so that the actual convolution is fairly fast), the overhead may become significant.

The above change to the tensor2tensor project reduces training time per step (NVIDIA Tesla V100, fp16) by at least 10%. Since the issue is fundamental and not specific to tensor2tensor, it would make sense to address it at the framework level.

**Comment by rmothukuru** [comment]
Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version. 

Make sure you also include the exact command if possible to produce the output included in your test case. If you are unclear what to include see the issue template displayed in [the Github new issue template](https://github.com/tensorflow/tensorflow/issues/new/choose).

We ask for this in the issue submission template, because it is really difficult to help without that information. Thanks!

**Comment by ekuznetsov139** [comment]
TensorFlow 1.14, Linux, observed on Debian and Ubuntu.

You may reproduce the effect with the following simple script:
```
from __future__ import absolute_import, division, print_function
import tensorflow as tf
from tensorflow import keras
import numpy as np

input_shape=(40,40)
fix=False
inp=keras.layers.Input(shape=input_shape)
featuresL1 = 4
if fix:
	sh=tf.shape(inp)
	in_shape=tf.concat([sh[0:1]*sh[1:2], sh[-1:] ],axis=0)
	out_shape=tf.concat([sh[:-1], [featuresL1]], axis=0)
	L1inp=tf.reshape(inp,in_shape)
else:
	L1inp = inp
L1=keras.layers.Dense(featuresL1,use_bias=False,activation=tf.nn.relu,name='main')(L1inp)
if fix:
	L1=tf.reshape(L1,out_shape)
L3=keras.layers.Flatten()(L1)
L4=keras.layers.Lambda(lambda x: tf.math.reduce_mean(x, axis=1))(L3)
L5=keras.layers.Flatten()(L4)
model=keras.models.Model(inputs=inp,outputs=L5)
optimizer = tf.compat.v1.train.RMSPropOptimizer(0.001)
train_data=[]
train_labels=[]
for x in range(100):
	train_data.append(tf.constant(np.random.random(input_shape)))
	train_labels.append(np.random.random())
train_data=tf.stack(train_data,axis=0)

model.compile(loss='mse', optimizer=optimizer)
model.summary()
model.fit(x=train_data,y=train_labels,epochs=10,verbose=1,steps_per_epoch=10,shuffle=True)

```
To do the profiling, launch "nvprof --profile-all-processes --print-gpu-trace --log-file nvprof%p.txt" in another terminal on the same system. You will observe that, if 'fix' is 'False', the resulting profile log contains repeated invocations of tensorflow::GatherOpKernel , but, if 'fix' is 'True', the log is about 10% shorter and GatherOpKernel is not used at all.

**Comment by ymodak** [comment]
Apologies for the delay in response. This issue is better surfaced on **tensor2tensor** repository, since changes you are suggesting belong to https://github.com/tensorflow/tensor2tensor/blob/master/tensor2tensor/layers/common_layers.py
Perhaps you can raise issue on https://github.com/tensorflow/tensor2tensor/issues
Thanks!

**Comment by ekuznetsov139** [comment]
The problem is not specific to tensor2tensor, it is demonstrated by the code snipped above that has nothing to do with tensor2tensor.

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.
