### ISSUE TITLE
Sample weights being expanded to match y_true/y_pred before they're sliced using a class_id in keras metrics.

### ISSUE THREAD

**Issue by simian-typist** [tensorflow/tensorflow#30983]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: n/a
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): v2.0.0-beta0-16-g1d91213fe7 2.0.0-beta1
- Python version: 3.6.7
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 10.0
- GPU model and memory: 7.5

**Describe the current behavior**
When passing sample weights and a class id to a metric class `sample_weights` is expanded to match the shape of y_true in [line 306 of this file](https://github.com/tensorflow/tensorflow/blob/r2.0/tensorflow/python/keras/utils/metrics_utils.py#L306), then the slicing using `class_id` is done in [line 312](https://github.com/tensorflow/tensorflow/blob/8e423e3d56390671f0d954c90f4fd163ab02a9c1/tensorflow/python/keras/utils/metrics_utils.py#L312) which means the broadcast weights op in [line 339-340](https://github.com/tensorflow/tensorflow/blob/8e423e3d56390671f0d954c90f4fd163ab02a9c1/tensorflow/python/keras/utils/metrics_utils.py#L339) fails as the shapes don't match anymore.

**Describe the expected behavior**
Sample weights should be squeezed or expanded to match the new shape of y_true and y_pred after they're sliced. Or it could be enforced to be the same shape as y_true and y_pred and then sliced as well.

**Code to reproduce the issue**
This code should illustrate the problem

    import tensorflow as tf
    import numpy as np

    class MaskedRecall(tf.keras.metrics.Metric):

        def __init__(self, class_id=None, name=None, dtype=None):
            super().__init__(name, dtype)
            self.inner = tf.keras.metrics.Recall(class_id=class_id)

        def result(self):
            return self.inner.result()

        def update_state(self, y_true, y_pred, sample_weight=None):
            sample_weight = tf.where(tf.equal(y_true[..., self.inner.class_id], -1),
                                    tf.zeros_like(y_true[..., self.inner.class_id]),
                                    tf.ones_like(y_true[..., self.inner.class_id]))
            self.inner.update_state(y_true, y_pred, sample_weight)

        def reset_states(self):
            self.inner.reset_states()

    if __name__ == "__main__":
        # metric = tf.keras.metrics.Recall()
        metric = MaskedRecall(class_id=0)  # 0)
        y_true = np.array([[[1], [0], [-1]], [[0], [1], [0]]])
        y_pred = np.array([[[1], [0], [0]], [[0], [1], [0]]])

        tf.config.experimental_run_functions_eagerly(True)
        metric.reset_states()
        metric.update_state(y_true, y_pred)
        print("Metric result: ", metric.result())

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

Traceback from the above:
Traceback (most recent call last):
~                                                                                                                                                             │  File "/home/tbradley/Downloads/metric.py", line 34, in <module>
~                                                                                                                                                             │    metric.update_state(y_true, y_pred)
~                                                                                                                                                             │  File "/home/tbradley/.virtualenvs/anim/lib/python3.6/site-packages/tensorflow/python/keras/utils/metrics_utils.py", line 75, in decorated
~                                                                                                                                                             │    update_op = update_state_fn(*args, **kwargs)
~                                                                                                                                                             │  File "/home/tbradley/.virtualenvs/anim/lib/python3.6/site-packages/tensorflow/python/eager/def_function.py", line 400, in __call__
~                                                                                                                                                             │    return self._python_function(*args, **kwds)
~                                                                                                                                                             │  File "/home/tbradley/Downloads/metric.py", line 20, in update_state
~                                                                                                                                                             │    self.inner.update_state(y_true, y_pred, sample_weight)
~                                                                                                                                                             │  File "/home/tbradley/.virtualenvs/anim/lib/python3.6/site-packages/tensorflow/python/keras/utils/metrics_utils.py", line 75, in decorated
~                                                                                                                                                             │    update_op = update_state_fn(*args, **kwargs)
~                                                                                                                                                             │  File "/home/tbradley/.virtualenvs/anim/lib/python3.6/site-packages/tensorflow/python/keras/metrics.py", line 1318, in update_state
~                                                                                                                                                             │    sample_weight=sample_weight)
~                                                                                                                                                             │  File "/home/tbradley/.virtualenvs/anim/lib/python3.6/site-packages/tensorflow/python/keras/utils/metrics_utils.py", line 340, in update_confusion_matrix_vari
~                                                                                                                                                             │ables
~                                                                                                                                                             │    math_ops.cast(sample_weight, dtype=dtypes.float32), y_pred)
~                                                                                                                                                             │  File "/home/tbradley/.virtualenvs/anim/lib/python3.6/site-packages/tensorflow/python/ops/weights_broadcast_ops.py", line 167, in broadcast_weights
~                                                                                                                                                             │    with ops.control_dependencies((assert_broadcastable(weights, values),)):
~                                                                                                                                                             │  File "/home/tbradley/.virtualenvs/anim/lib/python3.6/site-packages/tensorflow/python/ops/weights_broadcast_ops.py", line 103, in assert_broadcastable
~                                                                                                                                                             │    weights_rank_static, values.shape, weights.shape))
~                                                                                                                                                             │ValueError: weights can not be broadcast to values. values.rank=1. weights.rank=2. values.shape=(2,). weights.shape=(2, 1).

**Comment by ravikyram** [comment]
I have tried on colab with TF version 2.0 beta1 and was able to reproduce the issue.Please, find the [gist ](https://colab.research.google.com/drive/1yoHN-3k50q3KHCg6U-vJ2v8U_yqXafI2)here.Thanks!

**Comment by simian-typist** [comment]
I patched my local copy yesterday, it's a very small tweak. I'll make a pull request this afternoon.

**Comment by jvishnuvardhan** [comment]
@simian-typist Thanks for submitting PR to resolve the issue. Thanks!

**Comment by jvishnuvardhan** [comment]
This is still throwing an error with `tf-nightly`. Error trace is as follows. [Here](https://colab.research.google.com/gist/jvishnuvardhan/3dfc9a40e3d200687830c3860b51c92c/untitled47.ipynb) is the gist for our reference.

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-2-3658c987367a> in <module>()
     30     tf.config.experimental_run_functions_eagerly(True)
     31     metric.reset_states()
---> 32     metric.update_state(y_true, y_pred)
     33     print("Metric result: ", metric.result())

6 frames
/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/weights_broadcast_ops.py in assert_broadcastable(weights, values)
    101             " values.shape=%s. weights.shape=%s." % (
    102                 _ASSERT_BROADCASTABLE_ERROR_PREFIX, values_rank_static,
--> 103                 weights_rank_static, values.shape, weights.shape))
    104       weights_shape_static = tensor_util.constant_value(weights_shape)
    105       values_shape_static = tensor_util.constant_value(values_shape)

ValueError: weights can not be broadcast to values. values.rank=2. weights.rank=3. values.shape=(2, 3). weights.shape=(2, 3, 1).

---------------------------------------------------------------------------
NOTE: Current TensorFlow version is 2.2.0-dev20200331. To use TF 1.x instead,
restart your runtime (Ctrl+M .) and run "%tensorflow_version 1.x" before
you run "import tensorflow".
---------------------------------------------------------------------------
```

**Comment by simian-typist** [comment]
Sorry I missed this, I'll have a look over the easter weekend.

**Comment by ravikyram** [comment]
I could reproduce the issue with TF 2.2-rc4.Please, find the gist [here](https://colab.sandbox.google.com/gist/ravikyram/c01ba4f312fede29904b496712f3fbbb/untitled860.ipynb).Thanks!

**Comment by amahendrakar** [comment]
Was able to reproduce the issue with TF v2.3 and TF-nightly i.e. v2.4.0-dev20200909. Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/448971baf40e42a8ee759ebbef1e97a2/30983.ipynb). Thanks!

**Comment by sushreebarsa** [comment]
Was able to reproduce the issue in TF 2.6.0-dev20210527,please find the gist [here ](https://colab.research.google.com/gist/sushreebarsa/14c84a989f5e0d7aa99fe36629dd3c98/untitled17.ipynb)..Thanks !

**Comment by kumariko** [comment]
I could reproduce the issue with TF 2.6 . Please, find the gist [**`here`**](https://colab.research.google.com/gist/kumariko/17efd18642e06b85391f5519e8516b3b/untitled17.ipynb#scrollTo=pUdyzYRG4X2T). Thanks!

**Comment by tensorflowbutler** [comment]
Hi There,

 This is a stale issue. As you are using an older version of tensorflow, we are checking to see if you still need help on this issue. Please test the issue with the latest TensorFlow (TF2.7 and tf-nightly). If the issue still persists with the newer versions of TF, please feel free to open it in [keras-team/keras](https://github.com/keras-team/keras/issues) repository by providing details about the issue and a standalone code to reproduce the issue. Thanks! 

 Please note that Keras development has moved to a separate Keras-team/keras repository to focus entirely on only Keras. Thanks!
