### ISSUE TITLE
Relations/differences between Container and Scopes in Context Manager are not Clear

### ISSUE THREAD

**Issue by Uiuran** [tensorflow/tensorflow#30988]
From respective docs
https://www.tensorflow.org/api_docs/python/tf/container
https://www.tensorflow.org/api_docs/python/tf/VariableScope

The relation between these two context manager is not clear (although variable scope and name scope inter-relation are fine). 

But from the source code ones can see that they are clearly two things that inter-relates but not the same thing. 

Should i use Container only in the eager mode ? why not use only variable scope or name scope instead? also, maybe other questions will come as people uses low-level API to specialize in tensorflow dev.

So i think its an Issue.

Thankyou

**Comment by ymodak** [comment]
The documentation for [tf.compat.v1.variable_scope](https://www.tensorflow.org/api_docs/python/tf/compat/v1/variable_scope) has been updated.
