### ISSUE TITLE
Missing shuffle argument on validation call during training

### ISSUE THREAD

**Issue by andmax** [tensorflow/tensorflow#30993]
On TensorFlow 1.14 (OS Ubuntu 16.04), when I call fit() of a tf.Keras model using HDF5Matrix on both training and validation data, I set the argument shuffle='batch' and it works for training batches, however it fails when starting validation batches:

TypeError: TypeError while preparing batch. If using HDF5 input data, pass shuffle="batch".

  The problem seems to be the shuffle argument missing on the validation call during training:

https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/keras/engine/training_arrays.py#L424

  It seems the recursive call of model_iteration() does not set the argument from parent training call into the validation call.  Simply "shuffle=shuffle" in argument list should fix the issue.

Best,
  Andre.

**Comment by gadagashwini** [comment]
@andmax Will it be possible to provide the minimal code to reproduce the reported issue. Thanks!

**Comment by andmax** [comment]
Yes, based on keras / cifar10 example:
`
import h5py
import numpy as np
import tensorflow as tf
from tensorflow.keras.utils import to_categorical, HDF5Matrix

(Xtr, Ytr), (Xva, Yva) = tf.keras.datasets.cifar10.load_data()
Xtr, Ytr, Xva, Yva, nc = Xtr[:1000], Ytr[:1000], Xva[:100], Yva[:100], 10
Xtr, Xva = Xtr.astype('float32') / 255, Xva.astype('float32') / 255
Ytr, Yva, ins = to_categorical(Ytr, nc), to_categorical(Yva, nc), Xtr.shape[1:]
with h5py.File('cifar10.hdf5', 'w') as h5f:
    h5f['Xtr'], h5f['Ytr'], h5f['Xva'], h5f['Yva'] = Xtr, Ytr, Xva, Yva
del Xtr, Ytr, Xva, Yva

model = tf.keras.models.Sequential()
model.add(tf.keras.layers.Conv2D(8, (3, 3), input_shape=ins, activation='relu'))
model.add(tf.keras.layers.Conv2D(8, (3, 3), activation='relu'))
model.add(tf.keras.layers.MaxPooling2D(pool_size=(2, 2)))
model.add(tf.keras.layers.Dropout(0.25))
model.add(tf.keras.layers.Conv2D(16, (3, 3), activation='relu'))
model.add(tf.keras.layers.Conv2D(16, (3, 3), activation='relu'))
model.add(tf.keras.layers.MaxPooling2D(pool_size=(2, 2)))
model.add(tf.keras.layers.Dropout(0.25))
model.add(tf.keras.layers.Flatten())
model.add(tf.keras.layers.Dense(32, activation='relu'))
model.add(tf.keras.layers.Dropout(0.5))
model.add(tf.keras.layers.Dense(nc, activation='softmax'))
opt = tf.keras.optimizers.RMSprop(lr=0.0001, decay=1e-6)
model.compile(loss='categorical_crossentropy', optimizer=opt, metrics=['acc'])

Xtr, Ytr = HDF5Matrix('cifar10.hdf5', 'Xtr'), HDF5Matrix('cifar10.hdf5', 'Ytr')
Xva, Yva = HDF5Matrix('cifar10.hdf5', 'Xva'), HDF5Matrix('cifar10.hdf5', 'Yva')

model.fit(x=Xtr, y=Ytr, batch_size=32, epochs=100,
          validation_data=(Xva, Yva), shuffle='batch')
`

**Comment by gadagashwini** [comment]
I am bale to reproduce the reported issue with TF version 1.14.0 on Colab, find the gist [here](https://colab.research.google.com/drive/1UuloCJ4vLmILAVws7QxSI4N6IWxYJHCx). Thanks!

**Comment by andmax** [comment]
This issue has *not* been fixed in TF 1.15 and 2.0.

**Comment by andmax** [comment]
This issue is simple to resolve, just place shuffle=shuffle in model_iteration call for val_results in:

https://github.com/tensorflow/tensorflow/blob/r1.15/tensorflow/python/keras/engine/training_arrays.py#L428

In this way, shuffle will not be default to True in validation call raising the TypeError about not being shuffle=batch, here:

https://github.com/tensorflow/tensorflow/blob/r1.15/tensorflow/python/keras/engine/training_arrays.py#L379

**Comment by ymodak** [comment]
This is fixed with TF 2.1.0  Thanks!

**Comment by yhliang2018** [comment]
Close this issue as it's fixed in TF 2.1.
