### ISSUE TITLE
Name Scope Automatic Handling According to the Model Architectures blocks

### ISSUE THREAD

**Issue by Uiuran** [tensorflow/tensorflow#30991]
**System information**
- TensorFlow version (you are using):
- Are you willing to contribute it (Yes/No):
Yes
**Describe the feature and the current behavior/state.**
Tensorflow must be able to give name scopes more logically according to the architecture being built and automatically. Also, must be able to update the names automatically according to the 
Architecture without the dev having to explicity name the things (this should be optional).

Today it only automatically adds numbers sequentially to name/var scope when it is identical
to any other in the collections and you dont add '/' to it

**Will this change the current api? How?**
Add a Name/Var Scope handler. 

This class/template must be used to implement logic of names according to the architecture block connection. E.G. if a block is just the same from the other in the sequence them it must be named as if is a deep part of the same architecture blocks. If it is a ramification of the block given in a sequence but the same arch them he must be named with another tag.
 When duplicating some block to architectonic use, E.G. if you need to frame your data or feature, them each frame must have an coeherent name space block, like the today ordimatlicly done for repeated name space block, but this must be automaticly done for identical built blocks of the model, without the need to explicity code it.
Names must be given as unique ID according to te input-output architecture connection, if it has the same IO from previous Block in the sequence, then each Input-ArchBlock-Output that is IDentical must have the same name with the appropriated tag for deepness in the sequence of blocks.

Somethings still to be cleared, like if you have a sequence of CNN of deepness, say 100, then many of them will have same IO arch type (name), but they must not be enclosed in a name scope according to IO, since it obviously has the same IO pattern.

**Who will benefit with this feature?**

Much more self contained and manageable architectonic blocks, idenpendent of its Variable parameters configuration. This will rapid increase how we search for relevant new Neural Networks architecture, since it is a management tools as much as a vizualization tool and a graph construction tool.

**Any Other info.**

Obs: These Features could be something for the future in Autograph module, if it still dosnt do it

**Comment by Uiuran** [comment]
The tracker isnt tagging as feature request as it should.

**Comment by Uiuran** [comment]
First proposal of simple op blocks tracking through ultrametric space ( only some sketches, lemme know if you cant figure anything of this).
https://github.com/Uiuran/Biological-Images-Datasets/blob/master/drawing/feature.jpg

**Comment by Uiuran** [comment]
Following the proposal, i would implement an auto-tracking of names and updating to new names with a 3-adic ultrametric space in which each triple ramification inside an name consists of: Ops,Inner-Names Dict and Dependency Edges.

Inner-Names Dict points to new 3-adic trees with the same property

In the leaves will always be an Op or None (that is, no Dependency or No Op or No Inner name of any short for this triple).

This can be implemented through linked tables and with Ids being an hashable consisting of an Distance or Ordering Number and a Leave Number.

**Comment by Uiuran** [comment]
Small update here, in my actual code iam doing
```python
graph0 = tf.Graph()
with graph0.as_default():
  with tf.variable_scope('ok'):
    v = tf.Variable(-1.0,name='var')
    a = tf.abs(v)
    
tf.reset_default_graph()
graph = tf.Graph()
with graph.as_default():
  tf.graph_util.import_graph_def(graph0.as_graph_def(),name='IGWT')
  for op in graph.get_operations():
    print(op.name)     
```
For var space redefinition. That is, indeed iam cleaning working space and restarting the graph as a new block, however this would take too much time for immense graphs, in this feature the better way i think is to implement a new function in VarScope Class to directly change the scopes of the graph variables.

**Comment by mdanatg** [comment]
@Uiuran Thanks for the suggestion! I think this could be an interesting idea; it would be worth elaborating on the terminology a bit. More examples are always better. Also, have you looked at the name scoping done for instance by Keras?

I recommend reading the docs on the TF RFC process and c=preparing one according to that process: https://github.com/tensorflow/community/blob/master/governance/TF-RFCs.md

**Comment by Uiuran** [comment]
Iam looking in that direction too, thank you for the hint, update you asap.

**Comment by Uiuran** [comment]
Update: 
In my view we fundamentally must look in the following directions
1- Name editable Variable, in the API. For backward compatibility seems that we would need a ner Variable Version.
2- Module that use the collections with ('__varscope',), rename it properly according to the three mentioned above (today it only gives value 1 for the outer-most variable scopes and value 0 for all inner names that was defined by the user). Then one use this lookup engine to change ('__variable_store',) names.

**Comment by Uiuran** [comment]
plus: would not be better to standardize the names to variable or var in these keys  ('__var_store',)?

**Comment by tilakrayal** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
