### ISSUE TITLE
Building Tensorflow in armhf (olimex a20)

### ISSUE THREAD

**Issue by normads** [tensorflow/tensorflow#3099]
I'm trying to build Tensorflow on an olimex A20 for an embedded NN application. 
I just need to build the C++ or C session API because i'm building the graph in a different box. 

So far I've managed to build protobuf and bazel following this guide. 
https://github.com/samjabrahams/tensorflow-on-raspberry-pi/blob/master/GUIDE.md

But compiling Tensorflow with bazel i get the following error,

`ERROR: /root/.cache/bazel/_bazel_root/8bbee47417ac55737a4a72fb4017df9b/external/highwayhash/BUILD:17:1: C++ compilation of rule '@highwayhash//:sip_hash' failed: gcc failed: error executing command
  (cd /root/.cache/bazel/_bazel_root/8bbee47417ac55737a4a72fb4017df9b/tensorflow && \
  exec env - \
    PATH=/root/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin \
  /usr/bin/gcc -U_FORTIFY_SOURCE '-D_FORTIFY_SOURCE=1' -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 -DNDEBUG -ffunction-sections -fdata-sections -g0 '-std=c++0x' -iquote external/highwayhash -iquote bazel-out/host/genfiles/external/highwayhash -iquote external/bazel_tools -iquote bazel-out/host/genfiles/external/bazel_tools -isystem external/highwayhash -isystem bazel-out/host/genfiles/external/highwayhash -isystem external/bazel_tools/tools/cpp/gcc3 -no-canonical-prefixes -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' '-frandom-seed=bazel-out/host/bin/external/highwayhash/_objs/sip_hash/external/highwayhash/highwayhash/sip_hash.o' -MD -MF bazel-out/host/bin/external/highwayhash/_objs/sip_hash/external/highwayhash/highwayhash/sip_hash.d -c external/highwayhash/highwayhash/sip_hash.cc -o bazel-out/host/bin/external/highwayhash/_objs/sip_hash/external/highwayhash/highwayhash/sip_hash.o): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
In file included from external/highwayhash/highwayhash/sip_hash.cc:15:0:
external/highwayhash/highwayhash/sip_hash.h:31:9: error: expected nested-name-specifier before 'Key'
external/highwayhash/highwayhash/sip_hash.h:31:9: error: using-declaration for non-member at class scope
external/highwayhash/highwayhash/sip_hash.h:31:13: error: expected ';' before '=' token
external/highwayhash/highwayhash/sip_hash.h:31:13: error: expected unqualified-id before '=' token
external/highwayhash/highwayhash/sip_hash.h:34:38: error: 'Key' does not name a type
external/highwayhash/highwayhash/sip_hash.h: In constructor 'highwayhash::SipHashState::SipHashState(const int&)':
external/highwayhash/highwayhash/sip_hash.h:35:39: error: invalid types 'const int[int]' for array subscript
external/highwayhash/highwayhash/sip_hash.h:36:39: error: invalid types 'const int[int]' for array subscript
external/highwayhash/highwayhash/sip_hash.h:37:39: error: invalid types 'const int[int]' for array subscript
external/highwayhash/highwayhash/sip_hash.h:38:39: error: invalid types 'const int[int]' for array subscript
external/highwayhash/highwayhash/sip_hash.h: At global scope:
external/highwayhash/highwayhash/sip_hash.h:114:36: error: 'Key' in 'class highwayhash::SipHashState' does not name a type
external/highwayhash/highwayhash/sip_hash.h: In function 'highwayhash::uint64 highwayhash::SipHash(const int&, const char*, highwayhash::uint64)':
external/highwayhash/highwayhash/sip_hash.h:116:52: error: no matching function for call to 'ComputeHash(const int&, const char*&, const uint64&)'
external/highwayhash/highwayhash/sip_hash.h:116:52: note: candidate is:
external/highwayhash/highwayhash/state_helpers.h:63:8: note: template<class State> highwayhash::uint64 highwayhash::ComputeHash(const typename State::Key&, const char*, highwayhash::uint64)
external/highwayhash/highwayhash/sip_hash.h: At global scope:
external/highwayhash/highwayhash/sip_hash.h:120:46: error: 'Key' in 'class highwayhash::SipHashState' does not name a type
cc1plus: warning: unrecognized command line option "-Wno-free-nonheap-object" [enabled by default]
Target //tensorflow/tools/pip_package:build_pip_package failed to build
INFO: Elapsed time: 1577.488s, Critical Path: 22.08s`

System:
Linux version 3.4.90+ (root@debian) (gcc version 4.7.1 (Debian 4.7.1-7) )

Bazel:
Build label: 0.2.1-2016-06-28 (@447f7f3)
Build target: bazel-out/local_linux-fastbuild/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Tue Jun 28 17:09:27 2016 (1467133767)
Build timestamp: 1467133767
Build timestamp as int: 1467133767

**Comment by petewarden** [comment]
Have you looked at the makefile approach in tensorflow/contrib/makefile? I created this to make it easier to just build the C++ core inference library on platforms like iOS and the Raspberry Pi.

**Comment by normads** [comment]
I haven't. Let me see if i can find my way to it. Would appreciate some pointers though

**Comment by normads** [comment]
Ok i followed your guide here:
https://github.com/tensorflow/tensorflow/tree/master/tensorflow/contrib/makefile

Skipped building protobuf since i already built protobuf in my earlier attempt.
protoc --version
libprotoc 3.0.0

After running
make -f tensorflow/contrib/makefile/Makefile
i got,
gcc: error: unrecognized option ‘--std=c++11’

So i updated gcc to 4.7.2 (gcc version 4.7.2 (Debian 4.7.2-5))
and i got,
./tensorflow/core/lib/gtl/inlined_vector.h:383:10: error: ‘is_trivially_destructible’ is not a member of ‘std’

so i changed ‘is_trivially_destructible’ to 'has_trivial_destructor' and now i'm getting
./tensorflow/core/lib/gtl/array_slice_internal.h:232:38: error: ‘tensorflow::gtl::array_slice_internal::ArraySliceImplBase<const T>::ArraySliceImplBase’ names constructor

I'm obviously trying to build with the wrong gcc version or something. help!

**Comment by normads** [comment]
i could move past the original issue compiling tensorflow since i updated gcc. but it looks like i'm gonna run out of disk space soon. so would appreciate help resolving the makefile method

**Comment by petewarden** [comment]
I would recommend using at least gcc 4.8, that's the first one that has proper C++11 support:
https://gcc.gnu.org/projects/cxx-status.html
The errors you're seeing seem related to the C++11 features that 4.7 is missing.

**Comment by normads** [comment]
debian wheezy armhf only has 4.7. maybe 4.8 is in jessie. I'll try. thanks!
