### ISSUE TITLE
[TF 2.0 API Docs] tf.math.sqrt

### ISSUE THREAD

**Issue by steph-en-m** [tensorflow/tensorflow#30994]
Documentation contributor guide: https://www.tensorflow.org/community/contribute/docs

TensorFlow.v.2.0
Link to doc : https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/math/sqrt

## Doc issue description:

**1.** The generated file in which this symbol is defined .i.e **python/ops/gen_math_ops.py** is just plain text rather than a link to the source file. It would be great if it's rightly linked to the source file to enable change proposals.

**2.** There isn't a clear distinction between the choice of usage of either **tf.sqrt** or **tf.math.sqrt** and the implications (may be performance wise) of choosing one over the other.

**3.** The usage example isn't a complete code sample but largely syntax-like. One of the parameters the function takes is represented by a placeholder symbol rather than a real valued tensor.

**4.** There should also be a mention of the at-least the common errors that may arise as a result of incorrect usage of this function.

**Comment by michelucci** [comment]
If needed I could work on this if is ok with you @dynamicwebpaige . Reading now this https://www.tensorflow.org/community/contribute/docs

**Comment by steph-en-m** [comment]
@michelucci have you achieved any luck with this?

**Comment by michelucci** [comment]
Let me check what the status is. I am in London for a conference until Sunday, so I will have limited time. Will update this issue as soon as I can.

**Comment by steph-en-m** [comment]
I got the file where its defined..no more queries.
