### ISSUE TITLE
Remove the max_batch_size in tf-trt create_inference_graph  api

### ISSUE THREAD

**Issue by sgambient** [tensorflow/tensorflow#31007]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using):1.13.1
- Are you willing to contribute it (Yes/No):  Sure, if I had the wherewithal . 

**Describe the feature and the current behavior/state.**
The max_batch_size batch size limit  can  wreak havoc on codes that  can  increase the batch size dynamically (e.g. going from 25 to 50). 

**Will this change the current api? How?**
 trt.create_inference_graph would no longer need max_batch_size 

**Who will benefit with this feature?**
All

**Any Other info.**

**Comment by aaroey** [comment]
@sgambient the max_batch_size is the limit from [TensorRT library](https://docs.nvidia.com/deeplearning/sdk/tensorrt-api/c_api/classnvinfer1_1_1_i_builder.html#a7285560854aec37979363e1d71709bfe) since each TensorRT engine needs to be built with a specific max_batch_size. But if you set is_dynamic_op to True, TRT engines will be built dynamically and each engine will have max_batch_size set to the batch size that causes it to be built.

**Comment by sgambient** [comment]
Hi, does not seem to work for me. Getting the following error.  

tensorflow/contrib/tensorrt/kernels/trt_engine_op.cc:264] Engine buffer is full. buffer limit=1, current entries=1, requested batch=25

**Comment by aaroey** [comment]
@sgambient would you please set maximum_cached_engines to something larger than 1, e.g. the number of different input shapes?

**Comment by sgambient** [comment]
I see, so it has to be set to maximum possible.  In my case that could be
1000 or more.

**Comment by sgambient** [comment]
What is  the consequence of setting the batch_size to a large number ?

**Comment by aaroey** [comment]
The maximum batch size specifies the batch size for which TensorRT will optimize. So running with smaller batches may result in sub-optimal performance.

**Comment by sgambient** [comment]
That is what I figured.  The batch size can be variable for some DL models , specially in  ROI (Regions of Interest)  type of applications, where one batch slice can trigger  50x  slices down the pipeline.  So, if  input batch size if 25,  some where in the middle of the  pipeline, batch size can become 25*50 = 1250.  Looks like TensorRT  does not handle that use case transparently  at this point - would that be a correct conclusion to have ?

**Comment by aaroey** [comment]
@sgambient yes that is the case. But future version of TensorRT may address this issue by supporting dynamic shapes (even on batch dimension), and we'll update the TF-TRT bridge correspondingly when that comes out.
