### ISSUE TITLE
tf.tensordot documentation describes non-existent `a_axes` and `b_axes` parameters

### ISSUE THREAD

**Issue by bashi-bazouk** [tensorflow/tensorflow#31004]
## URL(s) with the issue:

https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/tensordot

## Description of issue (what needs changing):

There are no `a_axes` and `b_axes` parameters, but the documentation describes the function as if there are.

**Comment by ravikyram** [comment]
@bashi-bazouk 
In the function tf.tensordot( a,    b,    axes,    name=None)
axes parameter means a-axis , b-axis parameters.
For eg: `tf.tensordot(a, b, [[0], [2]])` means `a-axis param =[0]` and `b-axis param=[2].`

For more details refer [this link](https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/tensordot#args).

Thanks!

**Comment by bashi-bazouk** [comment]
Maybe you should make the documentation say that instead of the github issue.

**Comment by ravikyram** [comment]
@bashi-bazouk 

The above information is available in the [documentation.](https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/tensordot#args).Please, let me know if you have any questions.Thanks!

**Comment by bashi-bazouk** [comment]
@ravikyram There is no sentence in the documentation that says that axes parameter decomposes into a_axes and b_axes. The documentation simply starts referring to these arguments, as if they are self-evident. However, they're not, and the lack of that documentation is the reason that I created this issue.

The link you provided points to the exact page that I said is lacking this documentation.
