### ISSUE TITLE
Contradicting bazel versions suggested

### ISSUE THREAD

**Issue by boraca** [tensorflow/tensorflow#31006]
### URL(s) with the issue:

https://www.tensorflow.org/install/source_windows#install_bazel

## Description of issue (what needs changing):
It should be Bazel <0.23.0, not 0.24.1
### Clear description
First and last sentence contradict each other:
Install Bazel 0.24.1,
Ensure you install Bazel 0.23.0 or lower.

### Submit a pull request?
No

**Comment by phreakyphoenix** [comment]
@gadagashwini This issue seems to have been fixed and can be closed. Bazel 0.24.1 or greater is required and is correctly mentioned on the site.
Could I be added as a collaborator on this project? Then I'll be able to self assign tasks and do much more. Thanks.

**Comment by Saduf2019** [comment]
@boraca  Proceeding to close this issue as its resolved
