### ISSUE TITLE
[TF 2.0 Docs] Include @tf.function in site/en/r2/tutorials/generative/cvae.ipynb

### ISSUE THREAD

**Issue by Ryandry1st** [tensorflow/tensorflow#31013]
Thank you for submitting a TensorFlow documentation issue. Per our GitHub
policy, we only address code/doc bugs, performance issues, feature requests, and
build/installation issues on GitHub.

The TensorFlow docs are open source! To get involved, read the documentation
contributor guide: https://www.tensorflow.org/community/contribute/docs

## URL(s) with the issue:
site/en/r2/tutorials/generative/cvae.ipynb

### Clear description
When implementing in colab the performance improves from 30s / epoch average to 3.6s /epoch which is a huge benefit, and well worth highlighting/recommending by adding only 4 lines of code.

### Submit a pull request?
I can do that, yes

Are you planning to also submit a pull request to fix the issue? See the docs
contributor guide: https://www.tensorflow.org/community/contribute/docs and the
docs style guide: https://www.tensorflow.org/community/contribute/docs_style

**Comment by Ryandry1st** [comment]
Pull request submitted

**Comment by Ryandry1st** [comment]
Pull request is submitted, approved, and merged. Website docs just need to be updated to include recent code merge.

**Comment by jvishnuvardhan** [comment]
Automatically closing this out since I understand it to be resolved by the PR https://github.com/tensorflow/docs/pull/871. Thanks for the contribution.
