### ISSUE TITLE
Are tf.TFRecord(num_parallel_reads) and interleave(num_parallel_calls) duplicated?

### ISSUE THREAD

**Issue by chengmengli06** [tensorflow/tensorflow#31019]
Are tf.TFRecord(num_parallel_reads) and interleave(num_parallel_calls) duplicated? what is the behavior if they are both set > 1?  And the difference of shuffle before repeat and shuffle after repeat? I think the design of Dataset is too complicated, we need a more clear approach.

**Comment by ymodak** [comment]
From documentation,  ```tf.TFRecord``` and ```interleave``` do same operation. However ```interleave``` provides more options (map_function, block_length) to optimize the performance.

**Comment by jsimsa** [comment]
no, not at the moment `TFRecord` uses a legacy version of parallel interleaving that does not support autotuning

**Comment by AlexisBRENON** [comment]
So is it `interleave` the recommended way to parallelize (instead of `TFRecordDataset`)?

**Comment by jsimsa** [comment]
After https://github.com/tensorflow/tensorflow/commit/a4030f232072199046888efa95ae82c51959a07b#diff-887ec34979932479f014a211bf634614 `TFRecordDataset` supports autotuning as well.

My recommendation would be to use `TFRecordDataset` and fall back to using `interleave` for advanced use cases.
