### ISSUE TITLE
What is HalfPixelScalerForNN in nearest interpolation?

### ISSUE THREAD

**Issue by daquexian** [tensorflow/tensorflow#31011]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): ArchLinux
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 1.14.1-dev20190526
- Python version: 3.7
- Bazel version (if compiling from source): **tf_env_collect.sh just crashes here**

**Describe the current behavior**
https://github.com/tensorflow/tensorflow/blob/r1.14/tensorflow/core/kernels/resize_nearest_neighbor_op.cc#L111

I am implementing resize op for ONNX. https://github.com/onnx/onnx/pull/2057. I don't know why there is not "-0.5f" like vanilla HalfPixelScaler. The comments don't solve my concern. For example, if `(static_cast<float>(x) + 0.5f) * scale` equals 1.4, minus 0.5f or not will brings completely different result, no matter there is or is not `std::floor`.

**Describe the expected behavior**
I think `-0.5f` is more reasonable

**Comment by ymodak** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.
