### ISSUE TITLE
when using tf.train.exponential_decay , how can i  stop learning_rate changing during test

### ISSUE THREAD

**Issue by zkl99999** [tensorflow/tensorflow#31016]
is there a simple example?

**Comment by jvishnuvardhan** [comment]
This is not Build/Installation or Bug/Performance issue. Please post this kind of support questions at [Stackoverflow](https://stackoverflow.com/questions/tagged/tensorflow). There is a big community to support and learn from your questions. GitHub is mainly for addressing bugs in installation and performance. Thanks!

**Comment by jvishnuvardhan** [comment]
I am closing issue as stackoverflow is better place for this kind of support questions. thanks!
