### ISSUE TITLE
did 2.0beta1 version support cuda 10.1

### ISSUE THREAD

**Issue by l1t1** [tensorflow/tensorflow#31018]
i installed it by
`C:\Python37\Scripts>pip install tensorflow-gpu==2.0.0-beta1`
it is done ok
but when i run `import tensorflow as tf` in python,
it reports
`ImportError: Could not find 'cudart64_100.dll'. TensorFlow requires that this DLL be installed in a directory that is named in your %PATH% environment variable. Download and install CUDA 10.0 from this URL: https://developer.nvidia.com/cuda`
indeed i have installed cuda 10.1
i found the file `cudart64_101.dll` at `C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\bin`, and it is in PATH

**Comment by pandrey-fr** [comment]
No, it does not (see the [documentation](https://www.tensorflow.org/install/gpu)). You therefore need to use CUDA 10.0.

No offence, but this question has been repeatedly asked before - please search closed issues before posting (although it is for sure better to ask than to remain without an answer) :-)

**Comment by ymodak** [comment]
Closing since its resolved. Thanks!
