### ISSUE TITLE
Detail Design doc of tf.Dataset not available

### ISSUE THREAD

**Issue by chengmengli06** [tensorflow/tensorflow#31010]
Want the Detail Design doc of tf.Dataset not available. The current design include quite a lot of tuning parameters such as num_threads, and we users have little about its functionality. It is impossible for use to debug the performance bottleneck, it just looks like a black box.  I think it is necessary for the dataset developers to publish the design doc, and give more details about the data pipeline.

**Comment by chengmengli06** [comment]
@mrry

**Comment by jsimsa** [comment]
tf.data performance is discussed in https://www.tensorflow.org/beta/guide/data_performance

As you can imagine, the original tf.data design doc created in 2017 is outdated and we do not have any plans to create a new one.
