### ISSUE TITLE
Failed to convert an SSD mobilenet model to a frozen graph with 4 outputs by using export_tflite_ssd_graph.py

### ISSUE THREAD

**Issue by val9299** [tensorflow/tensorflow#31015]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): no
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- TensorFlow installed from (source or binary): binary; with conda environment
- TensorFlow version (use command below): 1.13.1
- Python version: 3.6.8
- CUDA/cuDNN version: 10.0 / 7.6.0
- GPU model and memory: GeForce GTX 970, AMD64

**Describe the current behavior**
I get a frozen model with only two outputs (raw_outputs/box_encodings, raw_outputs/class_predictions) when using export_tflite_ssd_graph.py with the extra attribute `add_postprocessing_op True`. I tried this script on these models from model zoo: ssdlite_mobilenet_v2_coco_2018_05_09, ssd_mobilenet_v2_coco_2018_03_29, ssd_mobilenet_v2_oid_v4_2018_12_12

**Describe the expected behavior**
I should get a frozen model with four outputs (detection_boxes, detection_classes, detection_scores, num_boxes) when using `add_postprocessing_op True`.

**Code to reproduce the issue**
`Cd .\ssdlite_mobilenet_v2_coco_2018_05_0`
`Python .\models\research\object_detection\export_tflite_ssd_graph.py --pipeline_config_path pipeline.config --trained_checkpoint_prefix model.ckpt --output_directory my_frozen_graph --add_postprocessing_op True`

**Other info / logs**
I know the outputs of the frozen graphs because I visualized them and tflite_convert worked successfully with this code: `tflite_convert --graph_def_file=my_frozen_graph/tflite_graph.pb --output_file=detect_raw.tflite --input_shapes=1,300,300,3 --input_arrays=normalized_input_image_tensor  --output_arrays=raw_outputs/box_encodings,raw_outputs/class_predictions`

My goal in general is to convert an ssd model from model zoo to a tflite float model with the expected four outputs. If there is another way to achieve this, I'm happy to hear about it. I've already tried to convert the frozen_inference_graph.pb (provided by model zoo) with tflite_convert but it didn't work. I got errors like:
 `Check failed: other_op->type == OperatorType::kMerge Found Sub as non-selected output from Switch, but only Merge supported.` (ssdlite_mobilenet_v2_coco_2018_05_09) or 
`Check failed: dim_size >= 1 (0 vs. 1)` (ssd_mobilenet_v2_coco_2018_03_29, ssd_mobilenet_v2_oid_v4_2018_12_12).
Searching for solving this problem, I read that some ops are missing for tflite and it is recommended to freeze the graph with export_tflite_ssd_graph.py instead and then convert it to tflite. This was successful but only if you want to work with the raw outputs.

Thanks for helping!

**Comment by srjoglekar246** [comment]
So the model converted using `export_tflite_ssd_graph.py` is not intended to be the final model to be used by TFLite.
Heres how it works:

1. The model zoo `.pb` files are the original TF graphs. They contain control flow ops at the end(`Merge`, `Enter`, etc), to perform NMS. TFLite doesn't have full fledged support for control flow ops yet. (Hence you can't directly call `tflite_convert` on the original version).

2. The  `export_tflite_ssd_graph.py` script is used to take this original TF graph, and convert it into an 'intermediate' form that removes all the control-flow logic, and leaves the graph with raw outputs that can be directly fed to a custom TFLite op (thats specifically designed for NMS). However, this graph is an intermediate, and not really the final TFLite version.

3. Then, you use `tflite_convert` to convert this intermediate representation into the final TFLite graph, which should succeed. What we do at this stage, is convert the intermediate graph, and append the post-processing op to it. This model should have the 4 outputs you want.

Without running `tflite_convert`, the output of  `export_tflite_ssd_graph.py` is meaningless for on-device inference. I guess the parameters on the export script weren't named very well, which misled you into thinking that the intermediate graph (after step 2) should contain 4 inputs.

**Comment by val9299** [comment]
Thanks for the explanation! Now I understand.

Because I’ve struggled a little bit finding out how to convert a ssd model. This is one way to do it from the command line:
1.	You have TF and TF object detection installed
2.	Downloading and unpacking the file (the model) from model zoo -> cd into the folder (e.g., `cd …/ssdlite_mobilenet_v2_coco_2018_05_09`)
3.	`python .\models\research\object_detection\export_tflite_ssd_graph.py --pipeline_config_path pipeline.config --trained_checkpoint_prefix model.ckpt --output_directory my_frozen_graph --add_postprocessing_op True`
4.	`tflite_convert --graph_def_file=my_frozen_graph/tflite_graph.pb --output_file=detect.tflite --input_shapes=1,300,300,3 --input_arrays=normalized_input_image_tensor  --output_arrays=TFLite_Detection_PostProcess,TFLite_Detection_PostProcess:1,TFLite_Detection_PostProcess:2,TFLite_Detection_PostProcess:3 --allow_custom_ops`

You get a tflite model (float) with 4 outputs. The output_arrays correspond to “detection_boxes, detection_classes, detection_scores, num_boxes”.

**Comment by srjoglekar246** [comment]
Yup, that is it. Is it failing for you at any step?
Or do you want some help figuring out what the outputs contain?

**Comment by val9299** [comment]
Everything is working, thanks for asking!
I just wanted to share my gained knowledge, so other people can get to the solution faster.

**Comment by leaf918** [comment]
> Thanks for the explanation! Now I understand.
> 
> Because I’ve struggled a little bit finding out how to convert a ssd model. This is one way to do it from the command line:
> 
> 1. You have TF and TF object detection installed
> 2. Downloading and unpacking the file (the model) from model zoo -> cd into the folder (e.g., `cd …/ssdlite_mobilenet_v2_coco_2018_05_09`)
> 3. `python .\models\research\object_detection\export_tflite_ssd_graph.py --pipeline_config_path pipeline.config --trained_checkpoint_prefix model.ckpt --output_directory my_frozen_graph --add_postprocessing_op True`
> 4. `tflite_convert --graph_def_file=my_frozen_graph/tflite_graph.pb --output_file=detect.tflite --input_shapes=1,300,300,3 --input_arrays=normalized_input_image_tensor  --output_arrays=TFLite_Detection_PostProcess,TFLite_Detection_PostProcess:1,TFLite_Detection_PostProcess:2,TFLite_Detection_PostProcess:3 --allow_custom_ops`
> 
> You get a tflite model (float) with 4 outputs. The output_arrays correspond to “detection_boxes, detection_classes, detection_scores, num_boxes”.

solved.

**Comment by rohittayal595** [comment]
> Thanks for the explanation! Now I understand.
> 
> Because I’ve struggled a little bit finding out how to convert a ssd model. This is one way to do it from the command line:
> 
> 1. You have TF and TF object detection installed
> 2. Downloading and unpacking the file (the model) from model zoo -> cd into the folder (e.g., `cd …/ssdlite_mobilenet_v2_coco_2018_05_09`)
> 3. `python .\models\research\object_detection\export_tflite_ssd_graph.py --pipeline_config_path pipeline.config --trained_checkpoint_prefix model.ckpt --output_directory my_frozen_graph --add_postprocessing_op True`
> 4. `tflite_convert --graph_def_file=my_frozen_graph/tflite_graph.pb --output_file=detect.tflite --input_shapes=1,300,300,3 --input_arrays=normalized_input_image_tensor  --output_arrays=TFLite_Detection_PostProcess,TFLite_Detection_PostProcess:1,TFLite_Detection_PostProcess:2,TFLite_Detection_PostProcess:3 --allow_custom_ops`
> 
> You get a tflite model (float) with 4 outputs. The output_arrays correspond to “detection_boxes, detection_classes, detection_scores, num_boxes”.

@val9299 When I am running this model which is converted like this in android, I am getting array of 10 elements with 4 inner elements each, i.e zzasu[0][0][0] = [0.4893098, 0.83000225,0.5201194,0.8918484]; Now I don't understand how these values are corresponding to "“detection_boxes, detection_classes, detection_scores, num_boxes”". Kindly help me with some links to understand.

**Comment by val9299** [comment]
> > Thanks for the explanation! Now I understand.
> > Because I’ve struggled a little bit finding out how to convert a ssd model. This is one way to do it from the command line:
> > 
> > 1. You have TF and TF object detection installed
> > 2. Downloading and unpacking the file (the model) from model zoo -> cd into the folder (e.g., `cd …/ssdlite_mobilenet_v2_coco_2018_05_09`)
> > 3. `python .\models\research\object_detection\export_tflite_ssd_graph.py --pipeline_config_path pipeline.config --trained_checkpoint_prefix model.ckpt --output_directory my_frozen_graph --add_postprocessing_op True`
> > 4. `tflite_convert --graph_def_file=my_frozen_graph/tflite_graph.pb --output_file=detect.tflite --input_shapes=1,300,300,3 --input_arrays=normalized_input_image_tensor  --output_arrays=TFLite_Detection_PostProcess,TFLite_Detection_PostProcess:1,TFLite_Detection_PostProcess:2,TFLite_Detection_PostProcess:3 --allow_custom_ops`
> > 
> > You get a tflite model (float) with 4 outputs. The output_arrays correspond to “detection_boxes, detection_classes, detection_scores, num_boxes”.
> 
> @val9299 When I am running this model which is converted like this in android, I am getting array of 10 elements with 4 inner elements each, i.e zzasu[0][0][0] = [0.4893098, 0.83000225,0.5201194,0.8918484]; Now I don't understand how these values are corresponding to "“detection_boxes, detection_classes, detection_scores, num_boxes”". Kindly help me with some links to understand.

@rohittayal595: I'm not longer working on it. The output is explained here: https://www.tensorflow.org/lite/models/object_detection/overview#output

**Comment by sumeshpandit** [comment]
> > Thanks for the explanation! Now I understand.
> > Because I’ve struggled a little bit finding out how to convert a ssd model. This is one way to do it from the command line:
> > 
> > 1. You have TF and TF object detection installed
> > 2. Downloading and unpacking the file (the model) from model zoo -> cd into the folder (e.g., `cd …/ssdlite_mobilenet_v2_coco_2018_05_09`)
> > 3. `python .\models\research\object_detection\export_tflite_ssd_graph.py --pipeline_config_path pipeline.config --trained_checkpoint_prefix model.ckpt --output_directory my_frozen_graph --add_postprocessing_op True`
> > 4. `tflite_convert --graph_def_file=my_frozen_graph/tflite_graph.pb --output_file=detect.tflite --input_shapes=1,300,300,3 --input_arrays=normalized_input_image_tensor  --output_arrays=TFLite_Detection_PostProcess,TFLite_Detection_PostProcess:1,TFLite_Detection_PostProcess:2,TFLite_Detection_PostProcess:3 --allow_custom_ops`
> > 
> > You get a tflite model (float) with 4 outputs. The output_arrays correspond to “detection_boxes, detection_classes, detection_scores, num_boxes”.
> 
> @val9299 When I am running this model which is converted like this in android, I am getting array of 10 elements with 4 inner elements each, i.e zzasu[0][0][0] = [0.4893098, 0.83000225,0.5201194,0.8918484]; Now I don't understand how these values are corresponding to "“detection_boxes, detection_classes, detection_scores, num_boxes”". Kindly help me with some links to understand.

Hey Can you pls send me the tflite model with 4 output. I am unable to convert it. Thank you.
amansharma8458@gmail.com
