### ISSUE TITLE
Will TF2 include implementations of constrained optimizers?

### ISSUE THREAD

**Issue by ifed-ucsd** [tensorflow/tensorflow#31029]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using): 2.0.0-beta1
- Are you willing to contribute it (Yes/No): Yes

**Describe the feature and the current behavior/state.**
I would like to use an optimizer with optional problem constraints. I am wondering if something like https://www.tensorflow.org/api_docs/python/tf/contrib/constrained_optimization/AdditiveExternalRegretOptimizer will be available in TF2?

**Will this change the current api? How?**

**Who will benefit with this feature?**

**Any Other info.**

**Comment by ymodak** [comment]
TF 2.0 does not contain this feature. However, you can raise a request to add this feature in [tensorflow/addons](https://github.com/tensorflow/addons) repository.
See https://github.com/tensorflow/addons/tree/master/tensorflow_addons/optimizers to know more.
