### ISSUE TITLE
estimator.predcit load model every time

### ISSUE THREAD

**Issue by 3NFBAGDU** [tensorflow/tensorflow#31021]
estimator.predict() works to slowly. I want to predict some text in my model in every 2 seconds. Everytime I call the estimator.predict() function, it loads the model all over again. I want to load the model just once and after that use estimator.predict() every 2 seconds on this same model to get the faster prediction.

**Comment by semal** [comment]
same problem, but using cache session and session.run to predict could solve it.

**Comment by ymodak** [comment]
Perhaps multi-threaded prediction can help you achieve this.
See https://medium.com/element-ai-research-lab/multithreaded-predictions-with-tensorflow-estimators-eb041861da07
