### ISSUE TITLE
timestamps in logs please

### ISSUE THREAD

**Issue by bjarthur** [tensorflow/tensorflow#31032]
in TF 1.12 using the TF API i get nice timing info in the logs:

```
INFO:tensorflow:Elapsed 5976.983817, Step #10825: rate 0.000200, accuracy 96.9%, cross entropy 0.098157
```

the `Elapsed ...` number therein is in seconds.

in TF 2.0-beta using the keras API i sadly don't:

```
710/710 - 0s - loss: 0.3377 - val_loss: 0.5081
```

the `0s` there seems to be the time for that step, not the cumulative elapsed time, as it never changes over the course of an hour long training run.

at the very least it would be nice to have more significant digits on that `0s`.  better yet, would be elapsed time, or just a simple time stamp prefixed to each log entry.

i've searched the docs, but haven't found a way to do this.  sorry if i missed it.

thanks!

**Comment by jvishnuvardhan** [comment]
@bjarthur In the timestamp you could see `ETA` while running the code and after completing an epoch it shows how many seconds it took to complete that epoch and how much time it took per sample. For the example shown below, epoch 1 took 11 seconds to train and 176usec/sample. Please take a look at the [gist here](https://colab.sandbox.google.com/gist/jvishnuvardhan/e752e51174143c5412389736696c222a/tf_31032.ipynb)

```

Epoch 1/5
60000/60000 [==============================] - 11s 176us/sample - loss: 0.2202 - accuracy: 0.9352
Epoch 2/5
60000/60000 [==============================] - 10s 171us/sample - loss: 0.0969 - accuracy: 0.9699
```

If you want overall elapsed time, please import time and get elapsed time as follows.

```
import time
st_time=time.time()
## your model here
## ops
time_elapsed=time.time()-st_time # this gives elapsed time in sec
```
I am closing this issue. Please feel free to open a new issue if you are looking any other feature. Thanks!

**Comment by bjarthur** [comment]
except that as you can see in my example above, my epoch times are so short that they show up as `0s`.  how about some more significant digits?  surely that can't be hard to do.
