### ISSUE TITLE
tf.while loop behaviour in multigpu setting

### ISSUE THREAD

**Issue by colmantse** [tensorflow/tensorflow#31030]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): ubuntu 16.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): pip binary?
- TensorFlow version (use command below): 1.12
- Python version: 3.5
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

I would like to verify if tf.while loop in multiple gpu setting is still an issue. I know that using while loop with variables in multigpu will give wrong result due to the while loop mixing up variables from different gpu under different name scope but same variable scope. I am not sure if this is still the case. Also if this concerns variables only or would similar behaviour happens to non-variables.

**Comment by gadagashwini** [comment]
@colmantse Will it be possible to provide minimal code to reproduce the issue. Thanks!

**Comment by colmantse** [comment]
hi @gadagashwini , will work on it right away.

**Comment by gadagashwini** [comment]
@colmantse Any update on the code snippet. Thanks!

**Comment by colmantse** [comment]
hi sorry, I am still trying to reproduce the issue. maybe I should close for now and reopen when I manage.

**Comment by colmantse** [comment]
@gadagashwini  I managed to reproduce the problem, the code snippet is attached below
Its a py file changed to txt.

[whileTest.txt](https://github.com/tensorflow/tensorflow/files/3480801/whileTest.txt)

**Comment by colmantse** [comment]
Revision on the test script shows that it is instead an input problem and non-variable tf.while loop in multi gpu setting remains totally functional.
