### ISSUE TITLE
Building tensorflow 1.14 (bazel 0.24.1) on Jetson Xavier with the trouble

### ISSUE THREAD

**Issue by suffererofautomation** [tensorflow/tensorflow#31031]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution 
Linux Ubuntu 18.04

- TensorFlow installed from (source or binary):
source

- TensorFlow version:
1.14

- Python version:
3.6.8

- Installed using virtualenv? pip? conda?:
pip3

- Bazel version (if compiling from source):
Build label: 0.24.1- (@non-git)
Build target: bazel-out/aarch64-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Thu Jul 25 13:20:03 2019 (1564060803)
Build timestamp: 1564060803
Build timestamp as int: 1564060803

- GCC/Compiler version (if compiling from source):
gcc 5.5.0

- CUDA/cuDNN version: 
CUDA 10.0
cuDNN 7.5

- GPU model and memory:
Nvidia Jetson AGX Xavier

**Describe the problem**
I try to install tensorflow 1.14 with next config:
`bazel build --config=monolithic --jobs 8 -c opt --linkopt='-lrt' //tensorflow:libtensorflow_cc.so`

But i get an error
```
Starting local Bazel server and connecting to it...
ERROR: /root/tensorflow-1.14/WORKSPACE:94:1: Traceback (most recent call last):
	File "/root/tensorflow-1.14/WORKSPACE", line 94
		tf_workspace()
	File "/root/tensorflow-1.14/tensorflow/workspace.bzl", line 708, in tf_workspace
		native.new_http_archive(name = "double_conversion", urls =..."], <3 more arguments>)
type 'struct' has no method new_http_archive()
ERROR: Error evaluating WORKSPACE file
ERROR: Skipping '//tensorflow:libtensorflow_cc.so': error loading package 'external': Package 'external' contains errors
WARNING: Target pattern parsing failed.
ERROR: error loading package 'external': Package 'external' contains errors
INFO: Elapsed time: 5.360s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
```

Provide the exact sequence of commands / steps that you executed before running into the problem

**Comment by ravikyram** [comment]
Just to verify did you get chance to follow instructions from [TensorFlow](https://www.tensorflow.org/install/source) website .Please, let us know. Thanks!

**Comment by tlkh** [comment]
@suffererofautomation NVIDIA provides validated and optimized binaries. Although currently, it is for TF 1.13.1. Take a look at: https://elinux.org/Jetson_Zoo#TensorFlow

If you want to build from source (assume you have a specific requirement for 1.14 and you cannot wait), check out [this thread](https://devtalk.nvidia.com/default/topic/1055131/jetson-agx-xavier/building-tensorflow-1-13-on-jetson-xavier/). Please consult the thread for a working procedure to build TF from source for Jetson Xavier.

**Comment by gunan** [comment]
Redirecting to tf mobile team.

**Comment by gunan** [comment]
What version of bazel do you have installed?

**Comment by suffererofautomation** [comment]
> What version of bazel do you have installed?

Now i use:
bazel 19.2
tf 1.13

The configuration works perfectly.
The topic may be closed.

**Comment by adragoset** [comment]
I was able to get the c++ api compiled by following the link left by @tlkh. However the pip package will not build for tensorflow 1.14.0 and i get the same error as in [issues/28277](https://github.com/tensorflow/tensorflow/issues/28277#issuecomment-504783335)

**Comment by ravikyram** [comment]
@suffererofautomation 
Can we close this issue since the query is been resolved. Thanks!
