### ISSUE TITLE
Feature Request: Able to store weights to disk when not in use. For sparse inputs/data/training

### ISSUE THREAD

**Issue by Santosh-Gupta** [tensorflow/tensorflow#31043]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using): TF 2.0 Beta
- Are you willing to contribute it (Yes/No): Yes

**Describe the feature and the current behavior/state.**

Ability to store weights to disk when not in use, for sparse inputs/data/training.

An example of is training a very large number of item embeddings (such as word2vec). Say that the number of items(words) is very large, 7 or 8 figures. If trying to train this in Tensorflow, this would cause memory issues since there's a very large number of parameters loaded into memory at a time. For example, if there are 10 million items, and the embedding size is 256, then there are 

10 million * 256 embedding size = 256 million parameters

Which all loaded into memory at a time. However during each training step, only a small fraction of these parameters go through a forward or backwards pass. If we can somehow have the other parameters stored to disk when not in use, that would save on a lot of memory, and therefore greatly expand the number of parameters researchers can test with. 

**Will this change the current api? How?**

I am not sure what is the best way to implement this. Perhaps a new datatype? Or the current datatypes can have a store option. 

**Who will benefit with this feature?**

Anyone working with sparse inputs, data, or training. 

**Any Other info.**

This may give some inspiration. Here is a repo that uses a sqlite database to store the vectors, so not all of them have to be loaded at once.

https://github.com/plasticityai/magnitude

I am thinking, a hacky way to go about this is to have a dummy embedding layer in Keras, which holds whatever parameters that will be used in the training step, and keep the rest in sqlite database. After each training step, the sqlite database values are exchanged with the ones in keras dummy layer, and the keras dummy layer values are replaced with the next values which will be used in the next forward pass. 

Though things will get a little more messy for optimizers with parameter-specific momentum, like Adagrad/Adam.

**Comment by allenlavoie** [comment]
The way people often do this is via multiple parameter servers with embeddings sharded between them, which would be my suggestion. I don't think disks are generally low enough latency for this to make sense. Although you could just make swap really big and let the operating system swap out unused parameters; again I think that's generally too slow.

**Comment by Santosh-Gupta** [comment]
Thanks for the suggestion, I'll look into parameter servers.

I am wondering, if there's any scale where the setup I mentioned wouldn't cause a slowdown, while also reducing memory. Say that the swap would be big enough for 1,000 iterations. For a negative sampling rate of 16, left/right context of 3, and batch size of 512, that might go up to ~12 million embeddings loaded into memory. But if there are say 60 million total items, then the setup might be worth it, unless the big swap in itself caused a big slow down. Maybe the next big swap could be run in parallel during the training phrase, but then again that may have it's own memory issues.

**Comment by allenlavoie** [comment]
Given your numbers, this sounds like less than 10 GiB of embeddings. Personally I'd just buy a stick or two of RAM and stay with a single machine if those are accurate.

But I guess you could put the embedding read as part of the data input pipeline, then like you say limit writes to some small slice of the embeddings. I don't think that's something amenable to wrapping into a high-level API, but it seems doable with existing low-level APIs.

**Comment by Santosh-Gupta** [comment]
Great, thanks for the insights!

**Comment by Santosh-Gupta** [comment]
I'm attempting to make a prototype for simple-ish library for this. Let me know if you have an idea for the best data store for this. At the moment I am just attempting to do embeddings, so just a single row with simple index lookup. I've been asking around but getting a variety of recommendations: hdf5, feather, parquet, postgres, Cassandra, SQLite, and simple files.
