### ISSUE TITLE
No Matching Distribution Found for Tensorflow

### ISSUE THREAD

**Issue by senorpinatta** [tensorflow/tensorflow#31058]
**System information**
- Linux Ubuntu 18.04:
- Nvidia Jetson Xavier
- Python version: 3.6.8

**Describe the problem**

`pip install tensorflow` and `pip3 install tensorflow`

returns:

`ERROR: Could not find a version that satisfies the requirement tensorflow (from versions: none)`
`ERROR: No matching distribution found for tensorflow`

And trying to install the .whl file directly yields:

`ERROR: tensorflow-1.14.0-cp36-cp36m-manylinux1_x86_64.whl is not a supported wheel on this platform.`

I can't understand why I'm getting these errors. My OS and specifications seem compatible.

**Any other info / logs**
https://imgur.com/XtowrBL

**Comment by kung-foo** [comment]
You have an ARM processor. PyPi seems to only have x86/amd64 wheels.

**Comment by rmothukuru** [comment]
@senorpinatta ,
Can you please try the instructions mentioned in [this link ](https://stackoverflow.com/questions/38896424/tensorflow-not-found-using-pip) and let us know if it helps. Thanks.

**Comment by senorpinatta** [comment]
Hi @rmothukuru ,
I googled solutions for this problem for many hours and tried many, many proposed solutions but none seemed to work.

kung-foo seems correct in his statement that Tensorflow does not have any distribution for ARM/aarch64 processors.

To elaborate, I'm trying to install Tensorflow inside a docker container on my Nvidia Xavier device. 

I had especially hoped [this](https://www.tensorflow.org/lite/guide/build_arm64) guide would work (and it does when implemented directly on the device) but it does not work inside docker containers.

It returns:

`Could not import tensorflow. Do not import tensorflow from its source directory change directory to outside the TensorFlow source tree, and relaunch your Python interpreter from there.`

Then, when I move out of the directory where the tensorflow package is installed it can't find where tensorflow is.

It's kind of alarming to me if there's no support for tensorflow on an ARM device specifically geared towards AI/ML and is one of the most powerful devices out there for AI/ML.

Edit: To clarify, Tensorflow is installed on the Xavier during its initial setup by Nvidia's own installer, but there's no support for using Tensorflow inside docker images which I don't think is an uncommon practice in this field.

**Comment by angersson** [comment]
@senorpinatta Yes, you are correct -- the TensorFlow team does not currently offer pre-compiled ARM Python wheel binaries. However, you can compile the package yourself (for example, [here is a demonstration repository created by a TensorFlow community member](https://github.com/lhelontra/tensorflow-on-arm)).

You may also be interested in checking out [TensorFlow SIG Build](https://groups.google.com/a/tensorflow.org/forum/#!forum/build).

**Comment by senorpinatta** [comment]
Thanks for the link to the forum, I'll check it out.
For future readers, the example works for 32-bit architectures, not 64 as far as my attempts have gone.

**Comment by rmothukuru** [comment]
Are you satisfied with the resolution of your issue?<br> [Yes](https://docs.google.com/forms/d/e/1FAIpQLSfaP12TRhd9xSxjXZjcZFNXPGk4kc1-qMdv3gc6bEP90vY1ew/viewform?entry.85265664=Yes&entry.2137816233=31058)<br> [No](https://docs.google.com/forms/d/e/1FAIpQLSfaP12TRhd9xSxjXZjcZFNXPGk4kc1-qMdv3gc6bEP90vY1ew/viewform?entry.85265664=No&entry.2137816233=31058)

**Comment by Sebasdel95** [comment]
@senorpinatta  you saved me bro!!! I was 3 days trying to solve this problem, now I download Python for 64bits and I installed tensorflow!!
Tks man

**Comment by yuanzhedong** [comment]
Nvidia has some pre-compiled versions of tf available on Jetson platform, works fine for me: https://docs.nvidia.com/deeplearning/frameworks/install-tf-jetson-platform/index.html

**Comment by rohitrkr** [comment]
>facing issue to install tensorflow==1.5
Tried many ways..
But dnt know how to do it..
New to Ubuntu and deep learning..
