### ISSUE TITLE
Can't set sprite in Keras Tensorboard Callback

### ISSUE THREAD

**Issue by beasteers** [tensorflow/tensorflow#31050]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using): 1.13.1
- Are you willing to contribute it (Yes/No): maybe, but not at this moment

**Describe the feature and the current behavior/state.**

There is no way to specify a sprite for embedding visualizations with the Tensorboard Callback in Keras. 

**Will this change the current api? How?**

It would add two more parameters to `Tensorboard.__init__()`
 - `embeddings_image_path=None,`
 - `embeddings_image_size=None,`

**Who will benefit with this feature?**

Anyone who wants to be able to see what their embedding clusters actually look like. NLP people are covered tho.

**Any Other info.**

Here's basically what you need. I just don't have the time to write unittests and docs. 

```python
class Tensorboard(Callback):

    def __init__(self,
                   ...
                   embeddings_freq=0,
                   embeddings_layer_names=None,
                   embeddings_metadata=None,
                   embeddings_data=None,

                   ### add
                   embeddings_image_path=None,
                   embeddings_image_size=None,
                   ...):

        ### add 
        self.embeddings_image_path = embeddings_image_path
        self.embeddings_image_size = embeddings_image_size


    def set_model(self, model):
        ...

        ### add/rework a tad ~L282-L290
        # allow embedding parameters to be passed as a dict(layer_name -> param)
        # or as a single string that applies to all layers
        layer_names = embeddings_vars.keys()

        embeddings_metadata = (
            {name: self.embeddings_metadata for name in layer_names}
            if not isinstance(self.embeddings_metadata, dict) else data)
            
        embeddings_image_path = (
            {name: self.embeddings_image_path for name in layer_names}
            if not isinstance(self.embeddings_image_path, dict) else data)

        embeddings_image_size = (
            {name: self.embeddings_image_size for name in layer_names}
            if not isinstance(self.embeddings_image_size, dict) else data)
        ###
        
        try:
            from tensorboard.plugins import projector
        except ImportError:
            raise ImportError('Failed to import TensorBoard. Please make sure that '
                              'TensorBoard integration is complete."')

        # TODO(psv): Add integration tests to test embedding visualization
        # with TensorBoard callback. We are unable to write a unit test for this
        # because TensorBoard dependency assumes TensorFlow package is installed.
        config = projector.ProjectorConfig()
        for layer_name, tensor in embeddings_vars.items():
            embedding = config.embeddings.add()
            embedding.tensor_name = tensor.name

            if (embeddings_metadata is not None and
                layer_name in embeddings_metadata):
                embedding.metadata_path = embeddings_metadata[layer_name]

            ### add 
            if (embeddings_image_path is not None and
                embeddings_image_size is not None and
                layer_name in embeddings_image_path and
                layer_name in embeddings_image_size):

                # this is what I need
                embedding.sprite.image_path = embeddings_image_path[layer_name]
                embedding.sprite.single_image_dim.extend(embeddings_image_size)
            ###

        projector.visualize_embeddings(self.writer, config)

**Comment by gadagashwini** [comment]
@beasteers  As this is more related to TF Tensorboard, please post this in [TF Tensorboard repo](https://github.com/tensorflow/tensorboard). Thanks!

**Comment by beasteers** [comment]
But this isn't an issue with Tensorboard. It's an issue with Tensorflow's Keras Tensorboard callback. 

The changes needs to happen in this repo i.e. `tensorflow/python/keras/callbacks.py`, so I feel like it is better placed as an issue here.

It's not a change that is heavily Tensorboard knowledge-specific. Here's the introductory [tutorial](http://www.pinchofintelligence.com/simple-introduction-to-tensorboard-embedding-visualisation/) I'm trying to reproduce: 

```python
config = projector.ProjectorConfig()
embedding = config.embeddings.add()
embedding.tensor_name = embedding_var.name
embedding.metadata_path = 'metadata.tsv'

####
# the Tensorboard Callback is just missing this bit.
embedding.sprite.image_path = 'sprite.png'
embedding.sprite.single_image_dim.extend([28,28])
####

projector.visualize_embeddings(summary_writer, config)
```

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.

**Comment by beasteers** [comment]
I haven't been using tensorflow much lately, but it looks like it is still an unresolved problem.

See: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/keras/callbacks.py#L2238-L2270

And notice that there is no mention of `embedding.sprite.image_path`

**Comment by Saduf2019** [comment]
@beasteers 
It looks like you are using an older Version of Tensorflow . Many bugs have been fixed in the latest version. Could you please execute your code using Latest Version 2.4.1 or 2.5 and let us know if the issue still persists? 

Can you please open this issue on kears repo in case of any queries.

**Comment by beasteers** [comment]
I don't have any code ready to test this but looking at the source code, there is still no way to set the sprite path or size here:
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/keras/callbacks.py#L2159-L2169

And there is nothing that references `embedding.sprite.image_path` here:
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/keras/callbacks.py#L2284-L2316

So unless I'm mistaken, this issue is still unresolved and there is no way to provide the embedding sprites

**Comment by jvishnuvardhan** [comment]
@beasteers As development of keras moved from TF repo to keras-team/keras repository,  I am closing this from TF repository. We will track this feature request in keras-team/keras

https://github.com/tensorflow/tensorflow/issues/29685
