### ISSUE TITLE
TFLite Interpreter, allocate_tensors() failed to prepare, not kTFLiteInt8/Uint8

### ISSUE THREAD

**Issue by eric4337** [tensorflow/tensorflow#31053]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 16.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): v1.14.0-rc1-22-gaf24dc91b5 1.14.0
- Python version: 3.6.3
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Describe the current behavior**
The graph only consist of ```tf.split()```, where I pin down to for this issue.
After quantization with ```representative_dataset()```, the interpreter fail to `allocate_tensor()`.
`RuntimeError: tensorflow/lite/kernels/dequantize.cc:62 op_context.input->type == kTFLiteUInt8 || op_context.input->type == kTFLiteInt8 was not true.Node number 0 (DEQUANTIZE) failed to prepare`.
I assume ```tf.split()``` cannot be quantize, and nothing to be quantize actually, since if I add ```tf.lite.OpsSet.TFLITE_BUILTINS_INT8``` to fully quantize into INT8, it tell me SPLIT_V is not supported.
So this simple graph should not have any quantize/dequantize at tf.split ops?
Thus checking type if is Int8 and has dequantize layer here seems not to make sense?

**Describe the expected behavior**
Interpreter sucessfully

**Code to reproduce the issue**
```
inputs_raw = tf.placeholder(tf.float32, shape=[1, 32, 32, 1], name='inputs_raw')
outputs = tf.split(value = inputs_raw, num_or_size_splits = 2, axis = 1)[0]

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())

    converter = lite.TFLiteConverter.from_session(sess, [inputs_raw], [outputs])

    converter.optimizations = [lite.Optimize.DEFAULT]
    def representative_data_gen():
        for i in range(1):
            yield [np.random.random_sample((1, 32, 32, 1)).astype(np.float32)]
            #yield [sess.run(tf.random.normal(inputs_raw.get_shape(), dtype = tf.float32, seed = 1))] # both have issue
    converter.representative_dataset = representative_data_gen
    tflite_model = converter.convert()
    open("converted_model_quant_test.tflite", "wb").write(tflite_model)

interpreter = lite.Interpreter(model_path = "converted_model_quant_test.tflite")
nterpreter.allocate_tensors()
```

**Other info / logs**
Traceback (most recent call last):
  File "main.py", line 532, in <module>
    interpreter.allocate_tensors()
  File "/proj/gpu_xxx/.local/lib/python3.6/site-packages/tensorflow/lite/python/interpreter.py", line 95, in allocate_tensors
    return self._interpreter.AllocateTensors()
  File "/proj/gpu_xxx/.local/lib/python3.6/site-packages/tensorflow/lite/python/interpreter_wrapper/tensorflow_wrap_interpreter_wrapper.py", line 106, in AllocateTensors
    return _tensorflow_wrap_interpreter_wrapper.InterpreterWrapper_AllocateTensors(self)
RuntimeError: tensorflow/lite/kernels/dequantize.cc:62 op_context.input->type == kTfLiteUInt8 || op_context.input->type == kTfLiteInt8 was not true.Node number 0 (DEQUANTIZE) failed to prepare.

**Comment by windj007** [comment]
Same issue with TF 1.14.0 from PIP, Python 3.7.

I have just installed tf-nightly-gpu and I cannot get that error with your script. However, my model (image to image) is still not loading with the same error (DEQUANTIZE).

**Comment by haozha111** [comment]
Jian, could you help take a look? Thanks!

**Comment by jiarenyf** [comment]
Having the same problem, under watching ... @jianlijianli

**Comment by Beya2019** [comment]
Having the same problem, under watching ,too ...

**Comment by gudbooy** [comment]
Having the same problem, under watching

**Comment by steve3nto** [comment]
Same problem here. Using keras version of deeplabv3 with mobilenetv2 backbone, this error occurs on node 113, which is a dequantize node who is trying to convert the reduction index for a ReduceMax operation. 

`RuntimeError: tensorflow/lite/kernels/dequantize.cc:62 op_context.input->type == kTfLiteUInt8 || op_context.input->type == kTfLiteInt8 was not true.Node number 113 (DEQUANTIZE) failed to prepare.`

Here is the visualization of node 113 in Netron. It has int32 as input type, that must be the problem.
Could I just modify the graph to hard code a float32 there?
<img width="473" alt="dequantize_error" src="https://user-images.githubusercontent.com/8995945/65073356-ffb4c380-d992-11e9-919a-4f4b044239be.PNG">

**Comment by JiatianWu** [comment]
Similar issue

**Comment by panyongfeng** [comment]
same issue, watching

**Comment by Monism1** [comment]
similar issue

**Comment by nomaad95** [comment]
same issue, watching

**Comment by jimmy9389** [comment]
same issue, watching

**Comment by hope-yao** [comment]
> Same problem here. Using keras version of deeplabv3 with mobilenetv2 backbone, this error occurs on node 113, which is a dequantize node who is trying to convert the reduction index for a ReduceMax operation.
> 
> `RuntimeError: tensorflow/lite/kernels/dequantize.cc:62 op_context.input->type == kTfLiteUInt8 || op_context.input->type == kTfLiteInt8 was not true.Node number 113 (DEQUANTIZE) failed to prepare.`
> 
> Here is the visualization of node 113 in Netron. It has int32 as input type, that must be the problem.
> Could I just modify the graph to hard code a float32 there?
> <img alt="dequantize_error" width="473" src="https://user-images.githubusercontent.com/8995945/65073356-ffb4c380-d992-11e9-919a-4f4b044239be.PNG">

Similar problem. Did you solve it?

**Comment by navid-a** [comment]
I'm having the same issue! Did anyone figure this out?

**Comment by Craftsman381** [comment]
I'm having the same issue! Kindly share the solution here.

**Comment by hlzl** [comment]
Any update on this? It's been a year.

**Comment by milinddeore** [comment]
I got the same issue, upgraded to `v1.15.0` fixed it.

**Comment by hlzl** [comment]
@milinddeore Same for me! You might have to upgrade `pip` if you can‘t find `v1.15.0`.
I believe this issue can be closed @jianlijianli

**Comment by praveenydv** [comment]
I upgrade my tensorflow v1.14.0 to v2.2.0  and it solved

**Comment by manmay-nakhashi** [comment]
crashing in v2.3.0

**Comment by manmay-nakhashi** [comment]
tflite model 
[mb_melgan_quant.zip](https://github.com/tensorflow/tensorflow/files/5055739/mb_melgan_quant.zip)

**Comment by manmay-nakhashi** [comment]
any update on this ?

**Comment by ItsMeTheBee** [comment]
Same issue here with tensorflow-cpu==2.3.0rc0

**Comment by ayush9096** [comment]
@manmay-nakhashi I am also getting that similar issue on mb_melgan model itself. Are you still facing that issue, or were you able to resolve that somehow ?

**Comment by hadizand** [comment]
> crashing in v2.3.0
> RuntimeError: tensorflow/lite/kernels/dequantize.cc:61 op_context.input->type == kTfLiteUInt8 || op_context.input->type == kTfLiteInt8 || op_context.input->type == kTfLiteInt16 || op_context.input->type == kTfLiteFloat16 was not true.Node number 353 (DEQUANTIZE) failed to prepare.

Could you resolve this issue?

**Comment by EpsilonZ** [comment]
Same issue here with tensorflow-cpu==2.3.0rc0. Any workarounds?

**Comment by Rick1Chen** [comment]
Same issue

**Comment by tucachmo2202** [comment]
> Same issue here with tensorflow-cpu==2.3.0rc0

Me too. Do you have solution for that problem? Please tell me the way. Thanks so much!

**Comment by EpsilonZ** [comment]
Supported operations is failing I think. I finally left it like this and it's working:

def export_model_to_tflite(model, X_test, y_test):

	# Convert the model to the TensorFlow Lite format without quantization
	converter = tf.lite.TFLiteConverter.from_keras_model(model)
	tflite_model = converter.convert()

	# Save the model to disk
	open("model.tflite", "wb").write(tflite_model)
		
	def representative_dataset_gen():
		for sample in X_test:
		    sample = np.expand_dims(sample.astype(np.float32), axis=0)
		    yield [sample]
			
	# Convert the model to the TensorFlow Lite format with quantization
	converter = tf.lite.TFLiteConverter.from_keras_model(model)
	converter.optimizations = [tf.lite.Optimize.DEFAULT]
	#converter.target_spec.supported_types = [tf.float32] this fails if you uncomment
	converter.representative_dataset = representative_dataset_gen
		
	tflite_model = converter.convert()
	
	# Save the model to disk
	open("model_quantized.tflite", "wb").write(tflite_model)

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.

**Comment by xiaofengren** [comment]
I'm still observed such issue while I'm using tensorflow==2.3.0rc0. 

RuntimeError: tensorflow/lite/kernels/dequantize.cc:61 op_context.input->type == kTfLiteUInt8 || op_context.input->type == kTfLiteInt8 || op_context.input->type == kTfLiteInt16 || op_context.input->type == kTfLiteFloat16 was not true.Node number 836 (DEQUANTIZE) failed to prepare.
