### ISSUE TITLE
caching cuDNN CNN kernel choices

### ISSUE THREAD

**Issue by ThisIsIsaac** [tensorflow/tensorflow#31051]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using):
- Are you willing to contribute it (Yes):

**Describe the feature and the current behavior/state.**

Pytorch as a functionality to cache the chosen cuDNN kernels when the input dimensions are identical to previous calls:

torch.backend.cudnn.benchmark = True
This improves throughput of a network by 30~40% (again, when the input dimensions of the network do not change).

Here is where the caching is implemented in Aten:
https://github.com/pytorch/pytorch/blob/358fb51e773b8ad509ec270caee5ec1c51d82f38/aten/src/ATen/native/cudnn/Conv.cpp#L340

Do you have any plans to add similar functionality? If not, I would love to send a PR.

**Will this change the current api? How?**

Like pytorch, it would require setting a flag.

**Who will benefit with this feature?**

All forward passes that are performed with fixed input sizes and types

**Any Other info.**

**Comment by aaroey** [comment]
@timshen91 would you please help to take a look at this?
Also @houtoms for comments if any.

**Comment by houtoms** [comment]
Has TF already used similar mechanism https://github.com/tensorflow/tensorflow/blob/e3efabdcaf9359991527c4aec9544dbd1a61c67d/tensorflow/core/kernels/conv_ops.cc#L990?

**Comment by timshen91** [comment]
The similar caching mechanism is already implemented for all cuDNN convolutions: https://github.com/tensorflow/tensorflow/blob/e3efabdcaf9359991527c4aec9544dbd1a61c67d/tensorflow/core/kernels/conv_ops.cc#L990

**Comment by ThisIsIsaac** [comment]
Thanks for the catch! will close
