### ISSUE TITLE
system memory leak

### ISSUE THREAD

**Issue by markpwoodward** [tensorflow/tensorflow#3106]
Running tutorial_example_trainer (similar leak for my own tensorflow scripts) results in ~70MB of memory being lost. `free` shows the memory is used, but `ps` shows that no process is using the memory. Nothing short of a reboot seems to free up the memory.

Reproduce with the following (After the ~10 minute run, you should be down ~7GB of memory)
``for i in `seq 1 100`; do ./bazel-bin/tensorflow/cc/tutorials_example_trainer --use_gpu; done``

os: 14.04
gpu: Titan X (361.28)
commit: 0927e5eaf3f5f031dbb1d3a13ac6529d8263ad9e (from yesterday)
cuda: 7.5
cudnn: 4.0.7
This leak is also present on an EC2 12.04 with an older version of tensorflow, cuda 7.0, cudnn 6.5.

Here is the output from a fresh reboot:
```
woodward@dev-box:~/install_files/tensorflow$ free -g
             total       used       free     shared    buffers     cached
Mem:           125          0        125          0          0          0
-/+ buffers/cache:          0        125
Swap:          127          0        127
woodward@dev-box:~/install_files/tensorflow$ for i in `seq 1 100`; do ./bazel-bin/tensorflow/cc/tutorials_example_trainer --use_gpu &>/dev/null; done
woodward@dev-box:~/install_files/tensorflow$ free -g
             total       used       free     shared    buffers     cached
Mem:           125          7        118          0          0          0
-/+ buffers/cache:          7        118
Swap:          127          0        127
woodward@dev-box:~/install_files/tensorflow$ ps -Ao user,pid,%mem,vsz,rss,command --sort -rss | head -n 10
USER       PID %MEM    VSZ   RSS COMMAND
root      1263  0.0 105648  6532 sshd: woodward [priv]
root      1317  0.0 105648  6512 sshd: woodward [priv]
woodward  1387  0.0  22756  5560 /bin/bash
woodward  1388  0.0  22668  5504 /bin/bash
woodward  1390  0.0  22668  5488 /bin/bash
woodward  1389  0.0  22668  5464 /bin/bash
root      1097  0.0  61384  5376 /usr/sbin/sshd -D
woodward  1366  0.0  22552  5144 -bash
woodward  1365  0.0 106776  5000 sshd: woodward@pts/0
```

**Comment by markpwoodward** [comment]
Further observations:
* The leak occurs with a simple script, but not when the gpu is disabled.

```
woodward@dev-box:~$ cat leak.py
import tensorflow as tf

hello = tf.constant('hello')
with tf.Session() as sess:
  print sess.run(hello)
woodward@dev-box:~$ free -g
             total       used       free     shared    buffers     cached
Mem:           125          0        125          0          0          0
-/+ buffers/cache:          0        125
Swap:          127          0        127
woodward@dev-box:~$ for i in `seq 1 100`; do python leak.py &> /dev/null; done
woodward@dev-box:~$ free -g
             total       used       free     shared    buffers     cached
Mem:           125          7        118          0          0          0
-/+ buffers/cache:          7        118
Swap:          127          0        127
woodward@dev-box:~$ export CUDA_VISIBLE_DEVICES=-1
woodward@dev-box:~$ for i in `seq 1 100`; do python leak.py &> /dev/null; done
woodward@dev-box:~$ free -g
             total       used       free     shared    buffers     cached
Mem:           125          7        118          0          0          0
-/+ buffers/cache:          7        118
Swap:          127          0        127
woodward@dev-box:~$ export CUDA_VISIBLE_DEVICES=0
woodward@dev-box:~$ for i in `seq 1 100`; do python leak.py &> /dev/null; done
woodward@dev-box:~$ free -g
             total       used       free     shared    buffers     cached
Mem:           125         14        111          0          0          0
-/+ buffers/cache:         14        111
Swap:          127          0        127
woodward@dev-box:~$ ps -Ao user,pid,%mem,vsz,rss,command --sort -rss | head -n 5
USER       PID %MEM    VSZ   RSS COMMAND
root      1258  0.0 105648  6420 sshd: woodward [priv]
root     18088  0.0 104436  6120 sshd: root [priv]   
woodward  1331  0.0  22756  5684 /bin/bash
woodward  1329  0.0  22748  5608 /bin/bash
```

**Comment by andydavis1** [comment]
It's suspicious to me that used is the same for "Mem" and also for "buffers/cache". Isn't this just the OS hanging on to some chunks of RAM for buffer cache?

**Comment by markpwoodward** [comment]
The buffers and cached columns are 0GB because I had just rebooted (I also rebooted between between posts, which is how I got down to 0GB used again). The "used" and "free" of the buffers/cache line are  - or + "buffers+cached", since "buffers+cached" is 0GB the two rows are equal. You are correct that a system running for a while will have very different rows, since buffers and cached will be large. 

The field to focus on is row['buffers/cache'], column['free'], this field is the real free memory available to programs. When that field drops to zero, the system hangs (ignoring swap), which is what brought this to my attention on EC2 where the instance only had ~14GB of memory, and that field dropped to 0GB.

`free` says that 7GB are being used, even after you account for buffers and cache, but `ps` says that no programs are using that memory. I believe this suggest a leak in kernel space, but I am not an expert in that. My second post gives a simple script to reproduce the problem. If you have 7GB of ram, then execute that script 100 times, as I do above, and the computer should lock up, or 400 times if you have 28GB, etc. 

In my second post, I first run with GPU enabled and 7GB are leaked, I then run with GPU disabled and 0GB are leaked, I then run again with GPU enabled and another 7GB are leaked, leaving the system with 14GB used, but ps shows that no programs are using that memory. So it seems to be a problem with GPU calls.

Thank you for taking a look at this.

**Comment by vrv** [comment]
From: https://github.com/tensorflow/tensorflow/issues/2728 can you try updating your driver from 361.28 to something very recent?  Even 361.42 caused problems for some people, and it was apparently solved by updating the driver.

**Comment by markpwoodward** [comment]
Oops, the original post of that issue made me think that it was about "within" process memory. As identified there, upgrading the nvidia driver (to 367.27) on my Titan X machine and on the EC2 instance fixed the problem. No more kernel space leak. Thank you!

And thank you all for your hard work on TensorFlow! It is an excellent library.

**Comment by vrv** [comment]
Awesome, glad the driver update fixed the problem!
