### ISSUE TITLE
Why tensorflow r2.0 still load libcudart_static.a in cuda_configure.bzl 

### ISSUE THREAD

**Issue by chengleiwang** [tensorflow/tensorflow#31062]
In tensorflow r2.0, I still can see libcudart_static.a copied to local cuda repository in third_party/gpus/cuda_configure.bzl file, but looks like tensorflow using cuda shared object to access Nvidia GPUs, so why still we need load static library here?

**Comment by chengleiwang** [comment]
Any update?

**Comment by anush-o** [comment]
@chengleiwang ,
Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version. Also, did you compile from source or install a binary?

Make sure you also include the exact command if possible to produce the output included in your test case. If you are unclear what to include see the issue template displayed in [the Github new issue template](https://github.com/tensorflow/tensorflow/issues/new/choose).

We ask for this in the issue submission template, because it is really difficult to help without that information.

**Comment by chengleiwang** [comment]
My system is Ubuntu 18.04 64bit os.
TensorFlow version is r2.0.
Compiled and installed from source.
I follow the TensorFlow document to build the tf. I am ooo at this moment.but I believe you can find the cuda build configuration in /third_part/gpus/cuda/ path. There are many library use libcudart_static.a as dependence.

**Comment by chengleiwang** [comment]
You can see the related code in /third_party/gpus/cuda_configure.bzl 
 "cudart_static": _find_cuda_lib(
            "cudart_static",
            repository_ctx,
            cpu_value,
            cuda_config.config["cuda_library_dir"],
            cuda_config.cuda_version,
            static = True,
        ),

Base on commit: 7c5aed3, tensorflow should use cuda dynamic library instead of static .

**Comment by chengleiwang** [comment]
@gunan , do you know the history of how tensorflow loading cuda library? what's the purpose for using libcuda_static.a before and now?

**Comment by yifeif** [comment]
I don't think we are using those to build the pip package though. I believe those are there so that if users do want to use the static libraries they are available. @chsigg might also know more history on this.

**Comment by chsigg** [comment]
I agree with Yifei, the file is copied but should not be used during the actual build. I would be happy to merge a PR that removes the file copy.

**Comment by chengleiwang** [comment]
Actually I tried to remove the dependency for static libraries, but failed to build tensorflow after that. I will provide more detail fail message later.

May I know who can help provide a PR?

**Comment by byronyi** [comment]
I guess it is still needed by NCCL? See [here](https://github.com/tensorflow/tensorflow/blob/master/third_party/nccl/archive.BUILD#L95). 

Not sure if we could get rid of the static runtime library, though I'd really like to do so.

**Comment by yifeif** [comment]
I see the static runtime dependency has been removed in https://github.com/tensorflow/tensorflow/commit/f819114a2d9d393a60e954d3a3e42d8700ff3b19#diff-063e9e964d14400387e823d7ae9c4b2f

Closing this. Let us know if you are still seeing issues.
