### ISSUE TITLE
Downgrade tensorflow 1.14 to tensorflow 1.13

### ISSUE THREAD

**Issue by abdou31** [tensorflow/tensorflow#31077]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10 x64
- TensorFlow installed from (source or binary): binary 
- TensorFlow version (use command below): 1.14
- Python version: 3.6.8
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:9.0/7.4
- GPU model and memory: Nivida GeForce 840m 3 Go

**Describe the current behaviour**
I training a Resnet Model ( CNN) that detects an eye region with landmarks on real-time using Tensorflow library 
For the first time, I have used Tensorflow library ( 1.13.1), the model gives sometimes results and for others times not for the webcam ( and for video from my dataset ).
I have upgrade Tensorflow to 1.14.1 recently and I have tested my webcam and I don't get any results contrary for a video the same result does not change when I upgrade the version of Tensorflow.
I have a little doubt that the problem may be can related to the version of Tensorflow.
My question is :

+ Can I downgrade the version of Tensorflow 1.14.1 to 1.13.1? ( all packages )

**Comment by tlkh** [comment]
Yes. If you only used the binary package, you can uninstall and install with your package manager. Did you use pip or conda?

For example, for pip you can do:
```shell
pip uninstall tensorflow-gpu -y
pip install tensorflow-gpu==1.13.1
```

**Comment by abdou31** [comment]
Yes, I have used pip.
Thanks for your answer.

**Comment by abdou31** [comment]
When I tried this command I get this error:
> pip install tensorflow-gpu==1.13.1
Collecting tensorflow-gpu==1.13.1
  Could not find a version that satisfies the requirement tensorflow-gpu==1.13.1 (from versions: )
No matching distribution found for tensorflow-gpu==1.13.1

**Comment by anush-o** [comment]
Can you please refer to the [software requirements](https://www.tensorflow.org/install/gpu#software_requirements) for tensorflow 1.13 and above.Thanks!

**Comment by abdou31** [comment]
I solve the issue by changing , pip is related to python 2.x and pip3 is related to python 3.6.8
> pip install tensorflow-gpu==1.13.1
> pip3 install tensorflow-gpu==1.13.1

**Comment by anush-o** [comment]
@abdou31 ,
Looks like issue is resolved,Can i close the issue.?Thanks!

**Comment by abdou31** [comment]
Yes, I will close the issue.
Thanks.

**Comment by AymenFJA** [comment]
For Conda user do the following : 

`conda uninstall tensorflow`

`conda install -c conda-forge tensorflow=1.13`

**Comment by paolosecci** [comment]
ERROR: Could not find a version that satisfies the requirement tensorflow==1.13.1

**Comment by AymenFJA** [comment]
> ERROR: Could not find a version that satisfies the requirement tensorflow==1.13.1

Are you using `conda env` or `python venv`?

Also consider that:

```
Tensorflow only supports the 64-bit version of Python

Tensorflow only supports Python 3.5 to 3.8

So, if you're using an out-of-range version of Python (older or newer) or a 32-bit version, then you'll need to use a different version.
```

**Comment by tjacobconley1** [comment]
I tried both pip and pip3 to re-install 
got the "no matching distribution" error for both

**Comment by tjacobconley1** [comment]
Github should allow images on these forms
