### ISSUE TITLE
torch.unfold function is needed..

### ISSUE THREAD

**Issue by seolhokim** [tensorflow/tensorflow#31072]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using):1.14
- Are you willing to contribute it (Yes/No):Yes

**Describe the feature and the current behavior/state.**
I think sending the function page in torch is the best. https://pytorch.org/docs/stable/_modules/torch/nn/modules/fold.html
**Will this change the current api? How?**
I guess it doesn't.
**Who will benefit with this feature?**
I think it will be popular in Vision Models, cause self attention is arising now to find out relationship in input pixels.(Stand-Alone Self-Attention in Vision Models)

**Any Other info.**

**Comment by alextp** [comment]
unfold looks very similar to tf.extract_image_patches. Which of the differences in the API are important to you?

**Comment by seolhokim** [comment]
i'm sorry to miss to check that function.
