### ISSUE TITLE
fit_generator validation progress bar

### ISSUE THREAD

**Issue by lufol** [tensorflow/tensorflow#31074]
**System information**
- TensorFlow version (you are using): 2.0 beta
- Are you willing to contribute it (Yes/No): Yes

**Describe the feature and the current behavior/state.**
Currently it is not possbile to see the progressbar of the valitation process when the `keras.fit_generator` is running in `verbose=1` or `verbose=2`.

**Will this change the current api? How?**
In https://github.com/tensorflow/tensorflow/blob/456fbc0e498e3d10604973de9f46ca48d62267cc/tensorflow/python/keras/engine/training_generator.py#L320 
the control over the verbosity has to be controllable via the `fit_generator` setup.

**Who will benefit with this feature?**
People using the keras `fit_generator` on large datasets. Especially there the validation process can take long time and therefore seeing the progress is nice.

**Comment by tanzhenyu** [comment]
I thought you made a PR and I LGTMed it. Closing it for now.
