### ISSUE TITLE
import error for python3: _pywrap_tensorflow_internal.so: undefined symbol: _Py_ZeroStruct

### ISSUE THREAD

**Issue by Char-Aznable** [tensorflow/tensorflow#31088]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): centos 6.9
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): source
- TensorFlow version: 1.14.0
- Python version: 3.7.4
- Installed using virtualenv? pip? conda?: build from source
- Bazel version (if compiling from source): 0.25.2
- GCC/Compiler version (if compiling from source): gcc 5.5.0
- CUDA/cuDNN version: 10.1/7.6.2
- GPU model and memory: GTX 1080

**Describe the problem**

**Provide the exact sequence of commands / steps that you executed before running into the problem**

I used a customized tool chain in $LINUXBREWHOME (which is ~/.linuxbrew) to build tensorflow from source using these commands (see below) and the build was successful. And then I built the whl for python3 and installed it using pip3 and they all worked. But when I tried importing tensorflow in python3 using ```python3 -c 'import tensorflow'``` I got an error:
```
ImportError: /home/aznb/.linuxbrew/Cellar/python/3.7.4/lib/python3.7/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so: undefined symbol: _Py_ZeroStruct
``` 
Tensorflow was built using these commands:
```
export GCC_HOST_COMPILER_PREFIX=$LINUXBREWHOME/bin

export PYTHON_BIN_PATH=$(which ${python3})
export PYTHON_LIB_PATH=$LINUXBREWHOME/Cellar/python/3.7.4/lib/python3.7/site-packages
export PYTHONPATH=$LINUXBREWHOME/opt/python3/lib/python3.7/site-packages
export PYTHON_ARG=$LINUXBREWHOME/opt/python3/lib/python3.7/site-packages
export CUDA_TOOLKIT_PATH=$LINUXBREWHOME/Cellar/cuda/10.1/
export CUDNN_INSTALL_PATH=$LINUXBREWHOME/Cellar/cuda/10.1/

export TF_NEED_GCP=0
export TF_NEED_CUDA=1
export TF_CUDA_VERSION="$($CUDA_TOOLKIT_PATH/bin/nvcc --version | sed -n 's/^.*release \(.*\),.*/\1/p')"
export TF_CUDA_COMPUTE_CAPABILITIES=6.1,7.5
export TF_NEED_HDFS=0
export TF_NEED_OPENCL=0
export TF_NEED_JEMALLOC=1
export TF_ENABLE_XLA=0
export TF_NEED_VERBS=0
export TF_CUDA_CLANG=0
export TF_CUDNN_VERSION="$(sed -n 's/^#define CUDNN_MAJOR\s*\(.*\).*/\1/p' $CUDNN_INSTALL_PATH/include/cudnn.h)"
export TF_NEED_MKL=0
export TF_DOWNLOAD_MKL=0
export TF_NEED_AWS=0
export TF_NEED_MPI=0
export TF_NEED_GDR=0
export TF_NEED_S3=0
export TF_NEED_ROCM=0
export TF_NEED_OPENCL_SYCL=0
export TF_SET_ANDROID_WORKSPACE=0
export TF_NEED_COMPUTECPP=0
export GCC_HOST_COMPILER_PATH=$LINUXBREWHOME/Cellar/gcc/5.5.0_4/bin/gcc
export CC_OPT_FLAGS="-march=native"
#export TF_SET_ANDROID_WORKSPACE=0
export TF_NEED_KAFKA=0
export TF_NEED_TENSORRT=0

# when using NCCL you need to install it own your own
#export TF_NCCL_VERSION=1.3

export CC_OPT_FLAGS="-march=native"

#bazel clean --async
#./configure

#bazel build --jobs 16 --crosstool_top=@local_config_cuda//crosstool:toolchain --config=noaws --config=opt --config=cuda //tensorflow/tools/pip_package:build_pip_package
./bazel-bin/tensorflow/tools/pip_package/build_pip_package $TMPDIR/tensorflow-pkg
pip3 install $TMPDIR/tensorflow-pkg/tensorflow-1.14.0-cp37-cp37m-linux_x86_64.whl
```

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by ravikyram** [comment]
Just to verify did you get chance to follow instructions from [TensorFlow](https://www.tensorflow.org/install/source) website .Please, let us know. Thanks!

**Comment by Char-Aznable** [comment]
Yes, I did. 

However, I found the culprit is ```export PYTHON_BIN_PATH=$(which ${python3})``` which should be ```export PYTHON_BIN_PATH=$(which python3)```. Fixing this solves the problem
