### ISSUE TITLE
TensorFlow 2.0 using pretrained word embeddings as input to sequence model

### ISSUE THREAD

**Issue by NeuralGirl** [tensorflow/tensorflow#31086]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using): TF 2.0 Beta
- Are you willing to contribute it (Yes/No):
**Describe the feature and the current behavior/state.**
I've just started exploring TF2.0 and it appears that the word embeddings must be generated as part of the seq2seq model.  

**Will this change the current api? How?**
embedding layer would need to be modified to not train and permit inclusion of pretrained word embeddings

**Who will benefit with this feature?**
anyone who would like to use pretrained word embeddings**Any

 Other info.**
inclusion of pretrained word embeddings would further expedite training so a huge win.

**Comment by pandrey-fr** [comment]
Hi @NeuralGirl,

If you already have pretrained embeddings, you should be able to build a model that takes pre-embedded data as inputs, and add a non-trainable lookup to your embedding matrix to your pipeline so as to conduct the embedding before feeding to the network.

E.g. something in the vein of:
```python
class PretrainedEmbedding(tf.keras.layers.Layer):
    """Non-trainable embedding layer."""

    def __init__(self, embeddings, rate=0.1):
        """"Instantiate the layer using a pre-defined embedding matrix."""
        self.embeddings = tf.constant(embeddings)
        # if you want to add some dropout (or normalization, etc.)
        self.dropout = tf.keras.layers.Dropout(rate=rate)

    def call(self, inputs, training=None):
        """Embed some input tokens and optionally apply dropout."""
        output = tf.nn.embedding_lookup(self.embeddings, inputs)
        return self.dropout(output, training=training)


my_model = tf.keras.models.Sequential([
    tf.keras.Input(input_shape, dtype=tf.int64),
    PretrainedEmbedding(embeddings_array),
    # insert any model architecture here
])
```

If I am missing something or if you would like to indicate a more precise use case your issue arises from, please let me know :-)

**Comment by NeuralGirl** [comment]
Thanks for the prompt followup! Yes, this is what I am looking to do in TF2.0. Thanks!

**Comment by pandrey-fr** [comment]
You are welcome :-)

**Comment by luiz-resende** [comment]
Hi, I've tried to use the aforementioned class to load pretrained embeddings, but the an error message is thrown: AttributeError: 'PretrainedEmbedding' object has no attribute '_trainable'

**Comment by pandrey-fr** [comment]
@luiz-resende The code I posted was lacking a `super` call in its `__init__` method; I edited it so that it should be workable. Note that to be rigorous in respecting the keras API you should also write a `get_config` method and a `compute_output_signature` one for that class, which I did not provide as this is a simple layer sketch.

Let me know if you run into additional issues!

**Comment by pandrey-fr** [comment]
Note that another take at the initial issue could be to assign the pretrained embeddings to an instantiated and built `Embedding` layer set to be non-trainable (_i.e._ whose weights would be frozen).
Something in the vein of:
```python
layer = tf.keras.layers.Embedding(input_dim, output_dim, trainable=False)
layer.build((None, input_dim))  # replace None with a fixed batch size if appropriate
layer.set_weights([pretrained_embeddings_tensor])
```

**Comment by luiz-resende** [comment]
Thanks for followup and for the help! I've tried the second option and it worked perfectly and way cleaner in my model (still transitioning from TF 1.x to 2.0). Thanks again!

**Comment by pandrey-fr** [comment]
You are very welcome :)

**Comment by tanzhenyu** [comment]
You can do this through:
embedding_layer = tf.keras.layers.Embedding(...)
embedding_layer.set_weights(pretrained_ embeddings)

**Comment by arthurdeschamps** [comment]
I think that simply `tf.keras.layers.Embedding(weights=[pre_trained_embeddings])` should work and that way one doesn't need to call `build` and `set_weights` manually.
