### ISSUE TITLE
Building Tensorflow with VS 2019

### ISSUE THREAD

**Issue by vitong** [tensorflow/tensorflow#31085]
_My apologies for starting this conversation here. I didn't think the TensorFlow discussion forum or StackOverflow would be appropriate._

Hello,

I work on the Visual Studio C++ Compiler team. We are interested in helping TensorFlow upgrade to Visual Studio 2019 while also making sure the best compiler switches are being used. We have seen significant throughput and code generation improvements between the Visual Studio 2017 and the 2019 compilers across various projects.

I have several questions:

1. From the [TensorFlow documents](https://www.tensorflow.org/install/source_windows), it looks like the only supported compiler is Visual Studio 2017. **Is VS 2017 being used in the TensorFlow continuous integration and release builds?** I couldn't verify from the logs [here](https://source.cloud.google.com/results/invocations/45f76066-3000-43cf-b55d-9317b4e6b083/targets/tensorflow%2Fgithub%2Fwindows%2Fbazel%2Fcontinuous/log).

2. Are there any plans to move to another compiler toolchain for TensorFlow on Windows?

3. Is there a better channel to ask any other questions that we might have?

Thank you for your time.

**Comment by gunan** [comment]
For CPU builds, as far as I know building with visual studio 2019 should be OK.
We cannot move our builds to visual studio 2019 because CUDA 10 does not support it.
We do definitely use VS 2017 to build TF on our side. Once we upgrade CUDA, we will reevaluate which compiler to base TF off of.

I think you can reach out to @thirupalanisamy to help set up a more formal channel, and build special interest group to discuss build related concerns.
https://groups.google.com/a/tensorflow.org/d/forum/build

**Comment by vitong** [comment]
Thanks for the response, @gunan. I'll reach out separately to create that channel.

I did a quick search for Cuda and Visual Studio and found this: https://docs.nvidia.com/cuda/cuda-installation-guide-microsoft-windows/index.html. It seems like in Cuda 10.1, they now have support for Visual Studio 2019. Do you happen to know if this is sufficient for Tensorflow?

**Comment by gunan** [comment]
We will probably need to keep supporting Cuda 10 for a while. Until we move off of cuda 10, we will kepe the toolchains same across our build environment.

**Comment by vitong** [comment]
That's understandable. If TF could continue using Cuda 10.0 but have that utilize Visual Studio 2019 instead of 2017, would your team consider upgrading to Visual Studio 2019 for both CPU and GPU setups on Windows? 

Is there anything else that might block the TF team from upgrading to Visual Studio 2019?

**Comment by gunan** [comment]
CUDA upgrades are usually a larger discussion for TF prebuilt binaries. Let's have a larger video call about that.

**Comment by vitong** [comment]
Sure. Is there an email/contact I can reach out to, in order to set this up? Thanks again for the help

**Comment by jvishnuvardhan** [comment]
@vitong I think contact was given in [this response](https://github.com/tensorflow/tensorflow/issues/31085#issuecomment-516064289). Also, you could join [Special interest group (SIG)](https://www.tensorflow.org/community/forums#special_interest_groups) related to build/install. There are also lots of other resources on TF website.  Thanks

**Comment by gunan** [comment]
Hi @vitong.
For now, let's continue the discussion through build@tensorflow.org mailing list.

For the questions posed:
I think it is highly likely that TF will skip cuda 10.1 and move to the next release when it is available.
And I can see no issues with using vs 2019, if cuda 10 headers are updated.

**Comment by jvishnuvardhan** [comment]
Automatically closing this out since I understand it to be resolved, but please let me know if I'm mistaken.Thanks!
