### ISSUE TITLE
Can't set tf.keras.backend.variable(trainable=False)

### ISSUE THREAD

**Issue by beasteers** [tensorflow/tensorflow#31089]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using): 1.13.1
- Are you willing to contribute it (Yes/No): maybe, but I don't have time for tests/docs

**Describe the feature and the current behavior/state.**
Currently, I have to do this.
```python
import tensorflow.keras.backend as K

variable = K.variable(5)
variable._trainable = False
```

But changing private attributes always feels dodgy. Ideally, we should just be able to do this.
```python
variable = K.variable(5, trainable=False)
```

**Will this change the current api? How?**

It will add one parameter `trainable=True` to `tensorflow.keras.backend.variable`

**Who will benefit with this feature?**

People who don't like the feeling of having to modify private attributes.

**Any Other info.**
Looking here: https://github.com/tensorflow/tensorflow/blob/ec71eb1ac4986e145845372b44648a03ea0e7545/tensorflow/python/keras/backend.py#L739

```python
def variable(value, dtype=None, name=None, constraint=None, trainable=True):
    ...
    v = variables_module.Variable(
      value,
      dtype=dtypes_module.as_dtype(dtype),
      name=name,
      trainable=trainable, # +++
      constraint=constraint)
    ...
```

Not sure what's going on with the sparse tensor, but you could always raise an exception if 
`hasattr(value, 'tocoo') and trainable == False` if that's a problem.

**Comment by naji-s** [comment]
Any updates on this?

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.

**Comment by beasteers** [comment]
It looks like this is still an unresolved issue: https://github.com/tensorflow/tensorflow/blob/c21a146b96a1aaf30f2849beac9458ed5c658633/tensorflow/python/keras/backend.py#L1052

**Comment by rmothukuru** [comment]
@beasteers,
Sorry for the delayed response. The functionality you are looking for, is implemented in [tf.Variable](https://www.tensorflow.org/guide/variable). Please find [the Gist](https://colab.research.google.com/gist/rmothukuru/ccbb2d0eb8993887a480b9e6b7c23590/gh_31089.ipynb) of the working code. Thanks!

**Comment by beasteers** [comment]
- This question was pertaining to `tf.keras.backend.variable` which is presumably different to `tf.Variable`. If I've missed something and they can in fact be used interchangeably, then it's perhaps that `tf.keras.backend.variable` is now unnecessary because of improving tf+keras core integrations and is just there for legacy purposes. 

But in the keras version it's doing a bit more (`_keras_shape`, `track_variable`, etc.) which I assume is needed for working with keras models.

**Comment by rmothukuru** [comment]
@beasteers,
The documentation for tf.keras.backend.variable couldn't be seen in the documentation of [tf.keras.backend](https://www.tensorflow.org/api_docs/python/tf/keras/backend). Can you please provide references to that API? Thanks!

**Comment by beasteers** [comment]
heres the implementation

https://github.com/tensorflow/tensorflow/blob/v2.5.0/tensorflow/python/keras/backend.py#L1046-L1094

if u look it now has a decorator called `@doc_controls.do_not_generate_docs`

**Comment by naji-s** [comment]
I do second what rmothukuru says.

**Comment by beasteers** [comment]
Looks like it was hidden in the docs in v2.4. But it was there in v2.3. Here's the docs for it:
https://www.tensorflow.org/versions/r2.3/api_docs/python/tf/keras/backend/variable

To reiterate - maybe using `tf.keras.backend.variable` is no longer necessary in tf2 - I have no idea because I haven't had to build a custom keras layer recently.

I'm just going to assume that `tf.keras.backend.variable` is no longer useful and that the default `tf.Variable` handles any of the keras metadata it needs (`_keras_shape`, `track_variable`, etc.)
