### ISSUE TITLE
Bug Issue: tf.case incompatible with list comprehension

### ISSUE THREAD

**Issue by ltrottier** [tensorflow/tensorflow#31084]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): **custom**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
```
$ uname -a
Linux archlinux 5.1.5-arch1-2-ARCH #1 SMP PREEMPT Mon May 27 03:37:39 UTC 2019 x86_64 GNU/Linux
```
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: **None**
- TensorFlow installed from (source or binary): **binary**
- TensorFlow version (use command below):
 **v1.14.0-rc1-22-gaf24dc91b5**
**1.14.0**
- Python version: **3.6**
- Bazel version (if compiling from source): **None**
- GCC/Compiler version (if compiling from source): **None**
- CUDA/cuDNN version: **None**
- GPU model and memory: **None**

**Describe the current behavior**

Bug 1: the function `random_choice` below has the correct behaviour only when using the decorator `@tf.function`. If the decorator is not used, `tf.case` no longer consider the predicate and always outputs the same value.

Bug 2: even if the decorator `@tf.function` is used, the function `random_choice` does not have the correct behaviour if I use list comprehension to create the list of pairs predicate / functions. Although, it has the correct behaviour when the list is populated iteratively with append (in a for loop). 

**Describe the expected behavior**

1. Decorating the function `random_choice` with `@tf.function` should not affect `tf.case`, unless I am not aware of the intricacies of `tf.function` and `tf.case`.

2. Choosing for loops or list comprehension to create the list of predicate / function pairs should not affect `tf.case`, unless (again) I am not aware of the intricacies of `tf.function` and `tf.case`.

**Code to reproduce the issue**

```python
import tensorflow as tf
import tensorflow.keras as keras
import tensorflow.keras.backend as K
import tensorflow_probability as tfp

K.clear_session()

def fct1(x):
  return x + 5

def fct2(x):
  return x - 5

# Bug 1: if you remove `@tf.function`, the function `random_choice` 
# no longer works, because `tf.case` no longer considers `idx`.  
@tf.function
def random_choice(x, choices):
  idx = tfp.distributions.Bernoulli(probs=0.5).sample(1)[0]
  outputs = [c(x) for c in choices]
 
# Bug 2: if you use `@tf.function`, but you replace this code:
  fns = []
  for o in outputs:
    fns.append(lambda: o)
# by this one:
#   fns = [lambda:o for o in outputs]
# then, `tf.case` no longer considers `idx`.

  y = tf.case([(tf.equal(idx, i), fn) for (i, fn) in enumerate(fns)])
  return outputs, idx, y

x = tf.constant([4.0])
choices = [fct1, fct2]
outputs, idx, y = random_choice(x, choices)
sess = tf.Session()
for i in range(10):
  outputs_np, idx_np, y_np = sess.run([outputs, idx, y])
  print(y_np, outputs_np[idx_np])
```

Example outputs.

For the code above (this is the expected behaviour):
```python
[9.] [9.]
[-1.] [-1.]
[-1.] [-1.]
[-1.] [-1.]
[9.] [9.]
[9.] [9.]
[-1.] [-1.]
[9.] [9.]
[9.] [9.]
[-1.] [-1.]
```

When removing `@tf.function`, or when using `@tf.function` but using list comprehension to create `fns` (this is the unexpected behaviour):
```python
[-1.] [9.]
[-1.] [9.]
[-1.] [-1.]
[-1.] [9.]
[-1.] [9.]
[-1.] [9.]
[-1.] [-1.]
[-1.] [-1.]
[-1.] [-1.]
[-1.] [9.]
```

**Other info / logs**

I could reproduce this bug in tensorflow:
**2.0.0-beta1**
**v2.0.0-beta0-16-g1d91213fe7**

**Comment by gadagashwini** [comment]
Was able to reproduce the issue on Colab with Tensorflow 1.14. Please see the [gist here](https://colab.research.google.com/drive/1aaE0CT0DSPlf2fQAPEzlPiT5d8cd8dtQ). Thanks!

**Comment by ltrottier** [comment]
Thanks for the feedback. Let me know when this is fixed.

**Comment by alextp** [comment]
@kkimdev can you help triage this? The implementation of tf.case with eager execution should be relatively straightforward to follow.

**Comment by ltrottier** [comment]
As a side note, I tested `tf.switch_case` in colab 1.14, and I had the same problems.

**Comment by ltrottier** [comment]
If I do this however, it works:
```
idx = tf.constant([0], dtype=tf.int32)
o1 = tf.constant([2.])
o2 = tf.constant([4.])
fns = [lambda: o1, lambda: o2]
tf.switch_case(idx[0], fns)
```

Outputs:
```
<tf.Tensor: id=223, shape=(1,), dtype=float32, numpy=array([2.], dtype=float32)>
```

**Comment by kkimdev** [comment]
@ltrottier Hi, sorry for getting back late.  Though it seems like this is just how Python works.

```python
fns = []
for o in 'abcdefg':
  fns.append(lambda:o)

print(fns[0]())
# prints 'g', not 'a'
```

More info: https://stackoverflow.com/a/19837590

I agree that it's quite confusing though :(

**Comment by ltrottier** [comment]
Thanks for the link. It is indeed how python works. I can't believe I've never seen this before.
