### ISSUE TITLE
Op request tensorflow lite 

### ISSUE THREAD

**Issue by kishorekumarsingh** [tensorflow/tensorflow#31096]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- TensorFlow installed from (source or binary):
- TensorFlow version (or github SHA if from source):

**Provide the text output from tflite_convert**

```
Some of the operators in the model are not supported by the standard TensorFlow Lite runtime. If those are native TensorFlow operators, you might be able to use the extended runtime by passing --enable_select_tf_ops, or by setting target_ops=TFLITE_BUILTINS,SELECT_TF_OPS when calling tf.lite.TFLiteConverter(). Otherwise, if you have a custom implementation for them you can disable this error with --allow_custom_ops, or by setting allow_custom_ops=True when calling tf.lite.TFLiteConverter(). Here is a list of builtin operators you are using: ADD, CAST, CONCATENATION, CONV_2D, DEPTHWISE_CONV_2D, EXP, EXPAND_DIMS, FILL, GATHER, GREATER, GREATER_EQUAL, LESS, LOGICAL_AND, LOGISTIC, MAXIMUM, MINIMUM, MUL, PACK, PAD, RANGE, RESHAPE, RESIZE_BILINEAR, SELECT, SHAPE, SLICE, SPLIT, SQUEEZE, STRIDED_SLICE, SUB, SUM, TILE, TOPK_V2, TRANSPOSE, UNPACK, WHERE, ZEROS_LIKE. Here is a list of operators for which you will need custom implementations: Enter, Exit, LoopCond, Merge, NonMaxSuppressionV3, Switch, TensorArrayGatherV3, TensorArrayReadV3, TensorArrayScatterV3, TensorArraySizeV3, TensorArrayV3, TensorArrayWriteV3.
```

Also, please include a link to a GraphDef or the model if possible.

**Any other info / logs**

Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by gadagashwini** [comment]
@kishorekumarsingh,
Provide the exact sequence of commands / steps that you executed before running into the problem. And also, provide Tensorflow version. Thanks!

**Comment by kishorekumarsingh** [comment]
This is the command that I used:
`tflite_convert 
--graph_def_file=frozen_inference_graph.pb 
--output_file=new_graph.tflite 
--input_format=TENSORFLOW_GRAPHDEF 
--output_format=TFLITE 
--input_shape=1,224,224,3 
--input_array=image_tensor 
--output_array=detection_boxes,detection_scores,detection_classes,num_detections 
--inference_input_type==QUANTIZED_UINT8
--inference_type=FLOAT 
----mean_values=128
 --std_dev_values=128 `

My tensorflow version : 
1.14.0

**Comment by Saduf2019** [comment]
@kishorekumarsingh  
Is this still an issue

**Comment by liyunlu0618** [comment]
Can you try this: https://www.tensorflow.org/lite/guide/ops_select
Feel free to reopen if you run into any issue.
