### ISSUE TITLE
Compilation error with protoc

### ISSUE THREAD

**Issue by CroMocha** [tensorflow/tensorflow#31094]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04
- TensorFlow installed from (source or binary): Installed from source
- TensorFlow version: 1.8
- Python version: 3.6.8
- Installed using virtualenv? pip? conda?: virtualenv
- Bazel version (if compiling from source): 0.12
- GCC/Compiler version (if compiling from source): 7.4.0

**Describe the problem**
I'm following the instructions I've found in:
https://medium.com/@fanzongshaoxing/use-tensorflow-c-api-with-opencv3-bacb83ca5683
to build the shared library of libtensorflow_cc.so and trying to compile the code which follows the tutorial in 
https://github.com/lysukhin/tensorflow-object-detection-cpp?source=post_page---------------------------
However, when I run cmake && make I get lots of compilation errors that tell me that the tensorflow library was generated using an old version of protoc and that I need to regenerate the file.
However I have already built protobuf 3.6.1 from source and running the following command lines I am assured of this:

protoc --version
libprotoc 3.6.1

pip show protobuf
Name: protobuf
Version: 3.6.1
Summary: Protocol Buffers
Home-page: https://developers.google.com/protocol-buffers/
Author: None
Author-email: None
License: 3-Clause BSD License
Location: /home/user/.virtualenvs/cv/lib/python3.6/site-packages
Requires: setuptools, six
Required-by: tensorflow, tensorboard

But I do note that in /usr/bin, there is a different version of protoc
/usr/bin/protoc --version
libprotoc 3.0.0

How should I proceed? Thanks for your consideration.

**Provide the exact sequence of commands / steps that you executed before running into the problem**
After performing the steps in the tutorial to build tensorflow_cc.so with bazel and move them to usr/local
git clone https://github.com/lysukhin/tensorflow-object-detection-cpp.git
cd tensorflow-object-detection-cpp
mkdir build
cd build
cmake ..
make

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

In file included from /usr/local/include/tf/tensorflow/core/framework/variant.h:26:0,
                 from /usr/local/include/tf/tensorflow/core/framework/allocator.h:26,
                 from /usr/local/include/tf/tensorflow/core/framework/tensor.h:20,
                 from /usr/local/include/tf/tensorflow/cc/framework/ops.h:21,
                 from /usr/local/include/tf/tensorflow/cc/ops/const_op.h:19,
                 from /home/marcchoo/tensorflow-object-detection-cpp/main.cpp:6:
/usr/local/include/tf/bazel-genfiles/tensorflow/core/framework/tensor.pb.h:17:2: error: #error This file was generated by an older version of protoc which is
 #error This file was generated by an older version of protoc which is
  ^~~~~
/usr/local/include/tf/bazel-genfiles/tensorflow/core/framework/tensor.pb.h:18:2: error: #error incompatible with your Protocol Buffer headers. Please
 #error incompatible with your Protocol Buffer headers.  Please
  ^~~~~
/usr/local/include/tf/bazel-genfiles/tensorflow/core/framework/tensor.pb.h:19:2: error: #error regenerate this file with a newer version of protoc.
 #error regenerate this file with a newer version of protoc.

In file included from /usr/local/include/tf/bazel-genfiles/tensorflow/core/framework/tensor.pb.h:32:0,
                 from /usr/local/include/tf/tensorflow/core/framework/variant.h:26,
                 from /usr/local/include/tf/tensorflow/core/framework/allocator.h:26,
                 from /usr/local/include/tf/tensorflow/core/framework/tensor.h:20,
                 from /usr/local/include/tf/tensorflow/cc/framework/ops.h:21,
                 from /usr/local/include/tf/tensorflow/cc/ops/const_op.h:19,
                 from /home/marcchoo/tensorflow-object-detection-cpp/main.cpp:6:
/usr/local/include/tf/bazel-genfiles/tensorflow/core/framework/resource_handle.pb.h:17:2: error: #error This file was generated by an older version of protoc which is
 #error This file was generated by an older version of protoc which is
  ^~~~~
/usr/local/include/tf/bazel-genfiles/tensorflow/core/framework/resource_handle.pb.h:18:2: error: #error incompatible with your Protocol Buffer headers. Please
 #error incompatible with your Protocol Buffer headers.  Please
  ^~~~~
/usr/local/include/tf/bazel-genfiles/tensorflow/core/framework/resource_handle.pb.h:19:2: error: #error regenerate this file with a newer version of protoc.
 #error regenerate this file with a newer version of protoc.
  ^~~~~
In file included from /usr/local/include/tf/bazel-genfiles/tensorflow/core/framework/tensor.pb.h:33:0,
                 from /usr/local/include/tf/tensorflow/core/framework/variant.h:26,
                 from /usr/local/include/tf/tensorflow/core/framework/allocator.h:26,
                 from /usr/local/include/tf/tensorflow/core/framework/tensor.h:20,
                 from /usr/local/include/tf/tensorflow/cc/framework/ops.h:21,
                 from /usr/local/include/tf/tensorflow/cc/ops/const_op.h:19,
                 from /home/marcchoo/tensorflow-object-detection-cpp/main.cpp:6:
/usr/local/include/tf/bazel-genfiles/tensorflow/core/framework/tensor_shape.pb.h:17:2: error: #error This file was generated by an older version of protoc which is
 #error This file was generated by an older version of protoc which is
  ^~~~~
/usr/local/include/tf/bazel-genfiles/tensorflow/core/framework/tensor_shape.pb.h:18:2: error: #error incompatible with your Protocol Buffer headers. Please
 #error incompatible with your Protocol Buffer headers.  Please
  ^~~~~
/usr/local/include/tf/bazel-genfiles/tensorflow/core/framework/tensor_shape.pb.h:19:2: error: #error regenerate this file with a newer version of protoc.
 #error regenerate this file with a newer version of protoc.
  ^~~~~
In file included from /usr/local/include/tf/bazel-genfiles/tensorflow/core/framework/tensor.pb.h:34:0,
                 from /usr/local/include/tf/tensorflow/core/framework/variant.h:26,
                 from /usr/local/include/tf/tensorflow/core/framework/allocator.h:26,
                 from /usr/local/include/tf/tensorflow/core/framework/tensor.h:20,
                 from /usr/local/include/tf/tensorflow/cc/framework/ops.h:21,
                 from /usr/local/include/tf/tensorflow/cc/ops/const_op.h:19,
                 from /home/marcchoo/tensorflow-object-detection-cpp/main.cpp:6:
/usr/local/include/tf/bazel-genfiles/tensorflow/core/framework/types.pb.h:17:2: error: #error This file was generated by an older version of protoc which is
 #error This file was generated by an older version of protoc which is
  ^~~~~
/usr/local/include/tf/bazel-genfiles/tensorflow/core/framework/types.pb.h:18:2: error: #error incompatible with your Protocol Buffer headers. Please
 #error incompatible with your Protocol Buffer headers.  Please
  ^~~~~
/usr/local/include/tf/bazel-genfiles/tensorflow/core/framework/types.pb.h:19:2: error: #error regenerate this file with a newer version of protoc.
 #error regenerate this file with a newer version of protoc.

...

**Comment by CroMocha** [comment]
Nvmind, I tried using the older version of protoc 3.5.1 that was verified to work in the tutorial and managed to compile. Guess 3.6.1 couldn't cut it. Where can we find the correct version of protoc for each tensorflow version?

**Comment by angersson** [comment]
The TensorFlow team does not officially support cmake, sorry. Please try out building [from source with Bazel](https://www.tensorflow.org/install/source).
