### ISSUE TITLE
YOLO V3 Tensorflow Lite request

### ISSUE THREAD

**Issue by hailigu** [tensorflow/tensorflow#31095]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- TensorFlow installed from (source or binary):
- TensorFlow version (or github SHA if from source):

**Provide the text output from tflite_convert**

```
Some of the operators in the model are not supported by the standard TensorFlow Lite runtime. If those are native TensorFlow operators, you might be able to use the extended runtime by passing --enable_select_tf_ops, or by setting target_ops=TFLITE_BUILTINS,SELECT_TF_OPS when calling tf.lite.TFLiteConverter(). Otherwise, if you have a custom implementation for them you can disable this error with --allow_custom_ops, or by setting allow_custom_ops=True when calling tf.lite.TFLiteConverter(). Here is a list of builtin operators you are using: ADD, CONCATENATION, CONV_2D, EXP, FILL, GATHER, GREATER_EQUAL, LEAKY_RELU, LOGISTIC, MUL, PAD, RESHAPE, RESIZE_NEAREST_NEIGHBOR, SHAPE, SPLIT_V, SQUEEZE, STRIDED_SLICE, SUB, WHERE. Here is a list of operators for which you will need custom implementations: NonMaxSuppressionV3.

```

Also, please include a link to a GraphDef or the model if possible.

**Any other info / logs**

Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by jvishnuvardhan** [comment]
@hailigu Is this still an issue? Can you share *.h5 or .pb file that you have used? What version of Tensorflow you had used? Thanks!

If this was already resolved, then please close the issue. Thanks!
