### ISSUE TITLE
when will the weights be updated for the sparse tensor in the optimizer

### ISSUE THREAD

**Issue by sjtusmartboy** [tensorflow/tensorflow#31101]
I notice there are both [SparseApplyAdadeltaOp](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/kernels/training_ops.cc#L798) and [ApplyAdadeltaOp](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/kernels/training_ops.cc#L642) in the [/tensorflow/core/kernels/training_ops.cc](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/kernels/training_ops.cc). 

Apparently, when the weights for the dense feature is optimized using Adadelta, the class of `ApplyAdadeltaOp` will be called, while when the weights for the categorical feature is optimized, `SparseApplyAdadeltaOp` will be called.

My question is when the `SparseApplyAdadeltaOp`  is called, for which part of the weights will be updated seems to not be in the code annotation, on earth the wights that are not zero will be updated or the weights whose gradients that are not zero will be updated?

**Comment by sjtusmartboy** [comment]
@ymodak hi, is there any answer for this problem :)

**Comment by sjtusmartboy** [comment]
@oanush hi, but who should I turn to help for this problem?

**Comment by sjtusmartboy** [comment]
@gadagashwini sos

**Comment by ymodak** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.
