### ISSUE TITLE
pip install tensorflow-lite PLEASE!

### ISSUE THREAD

**Issue by Tylersuard** [tensorflow/tensorflow#31103]
I'm finding very, very difficult-to-understand information online for how to install TF-lite.  Most of it involves cross-compilation and 10+ hours of waiting.  Tensorflow installation is easy.  Could you please make it so we can install TF-lite by just typing "pip install tensorflow-lite?"

Thanks!

**Comment by byronyi** [comment]
Just kidding: you should try to build the Android Open Source Project as a practice first.

**Comment by ravikyram** [comment]
Please go through the [link](https://www.tensorflow.org/lite/guide/build_arm64) to build tensorflow-lite.Thanks!

**Comment by Tylersuard** [comment]
Hi Ravikyram.  I've been stuck on those instructions for the last 3 days.  I'm finding them very, very difficult to follow.

**Comment by aselle** [comment]
There are many precompiled binaries for various platforms. See the full guide
https://www.tensorflow.org/lite/guide/

However, here's more links

If you just want to run it on raspberry pi or linux, then you can already do a pip install
https://www.tensorflow.org/lite/guide/python
which can be built by using  from the source tree with these instructions
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/tools/pip_package/README.md

If you want to use it on android you can use the precompiled aar.
https://www.tensorflow.org/lite/guide/android

If you want to use it on ios you can use a cocoapod
https://www.tensorflow.org/lite/guide/ios
