### ISSUE TITLE
Bulld tensorflow from source for Raspberry PI (Python 3.7)

### ISSUE THREAD

**Issue by yarik1988** [tensorflow/tensorflow#31108]
I successfully have built tensorflow 2.0.0b1 for raspberry PI using the guideline
https://www.tensorflow.org/install/source_rpi and command

sudo CI_DOCKER_EXTRA_PARAMS="-e CI_BUILD_PYTHON=python3 -e CROSSTOOL_PYTHON_INCLUDE_PATH=/usr/include/python3.7" tensorflow/tools/ci_build/ci_build.sh PI-PYTHON3 tensorflow/tools/ci_build/pi/build_raspberry_pi.sh

However, generated wheel file is called tensorflow-2.0.0b1-cp34-none-linux_armv7l.whl so I suppose it is for python 3.4

Is there a way to tell installer to use python 3.7 during wheel generation?

**Comment by vinorth05** [comment]
Hello, how did you do to make it work with Python 3.7?

**Comment by yarik1988** [comment]
Look at these releases
https://github.com/lhelontra/tensorflow-on-arm/releases

**Comment by terryheo** [comment]
Please check this.

https://www.tensorflow.org/install/source_rpi#python-3.7
