### ISSUE TITLE
word2vec_basic : Unique nodes clustering

### ISSUE THREAD

**Issue by heenamahour** [tensorflow/tensorflow#3111]
Hi !

I am getting the output of word2vec_basic.py in the following format

```
Nearest to key1  : node1, node2, node3 ..
Nearest to key2 : node2, node4, node5 ..

```
This implies that node2 is comparatively closer to key2 over key1 (Please correct me if I am wrong, as I am newbie here)

It would be great if I get the output in the following format
```
Nearest to key1  : node1, node3 , node6..
Nearest to key2 : node2, node4, node5 ..

```

That is, consider only the closest neighbor for clustering. Suggestions are welcome!

Appreciate the hardwork behind tensorflow :+1:

 
Thanks!

**Comment by andydavis1** [comment]
This is a question better suited for StackOverflow. Please ask it there and tag it with the `tensorflow` tag

**Comment by heenamahour** [comment]
Hi @andydavis1 , I have raised it on stackoverflow.


For future reference: please refer [issue#3111](http://stackoverflow.com/questions/38109476/dictionary-unique-relative-values-where-values-are-of-list-type) 

Thanks!
