### ISSUE TITLE
Convert to TFLite Unexpected value for attribute 'data_format'. Expected 'NHWC'

### ISSUE THREAD

**Issue by paulbauriegel** [tensorflow/tensorflow#31115]
I'm trying to convert a frozen Tensorflow graph. See model [here](https://drive.google.com/open?id=15g1aNF3WdJ7Yw8GRPVEWzBbkaZPIvCGC). I found a lot related bug reports on that issue but non of them was actually solved: [#30411](https://github.com/tensorflow/tensorflow/issues/30411), [#7967](https://github.com/tensorflow/tensorflow/issues/7967),[#24491](https://github.com/tensorflow/tensorflow/issues/24491). 

**System information**
- OS Platform and Distribution: Linux Ubuntu 19.04 64bit
- TensorFlow installed from (source or binary): binary  (CPU)
- TensorFlow version (use command below): v1.14.0-rc1-22-gaf24dc9 1.14.0
- Python version: 3.7.3

**Describe the current behavior**
Running in Jupyter I get following error:
```
ConverterError: TOCO failed. See console for info.
2019-07-28 21:08:26.912035: F tensorflow/lite/toco/import_tensorflow.cc:2619] Check failed: status.ok() Unexpected value for attribute 'data_format'. Expected 'NHWC'
Fatal Python error: Aborted

Current thread 0x00007fc8ee681740 (most recent call first):
  File "/home/paul/anaconda3/envs/openvino/lib/python3.7/site-packages/tensorflow/lite/toco/python/toco_from_protos.py", line 33 in execute
  File "/home/paul/.local/lib/python3.7/site-packages/absl/app.py", line 251 in _run_main
  File "/home/paul/.local/lib/python3.7/site-packages/absl/app.py", line 300 in run
  File "/home/paul/anaconda3/envs/openvino/lib/python3.7/site-packages/tensorflow/python/platform/app.py", line 40 in run
  File "/home/paul/anaconda3/envs/openvino/lib/python3.7/site-packages/tensorflow/lite/toco/python/toco_from_protos.py", line 59 in main
  File "/home/paul/anaconda3/envs/openvino/bin/toco_from_protos", line 10 in <module>
Aborted (core dumped)
```

Running over shell:
```
Traceback (most recent call last):
  File "tensorflow_issue_tflite.py", line 10, in <module>
    tflite_model = converter.convert()
  File "/home/paul/anaconda3/envs/openvino/lib/python3.7/site-packages/tensorflow/lite/python/lite.py", line 898, in convert
    **converter_kwargs)
  File "/home/paul/anaconda3/envs/openvino/lib/python3.7/site-packages/tensorflow/lite/python/convert.py", line 404, in toco_convert_impl
    input_data.SerializeToString())
  File "/home/paul/anaconda3/envs/openvino/lib/python3.7/site-packages/tensorflow/lite/python/convert.py", line 172, in toco_convert_protos
    "TOCO failed. See console for info.\n%s\n%s\n" % (stdout, stderr))
tensorflow.lite.python.convert.ConverterError: TOCO failed. See console for info.
2019-07-28 21:35:22.220584: F tensorflow/lite/toco/import_tensorflow.cc:2619] Check failed: status.ok() Unexpected value for attribute 'data_format'. Expected 'NHWC'
Fatal Python error: Aborted

Current thread 0x00007fae1bce0740 (most recent call first):
  File "/home/paul/anaconda3/envs/openvino/lib/python3.7/site-packages/tensorflow/lite/toco/python/toco_from_protos.py", line 33 in execute
  File "/home/paul/.local/lib/python3.7/site-packages/absl/app.py", line 251 in _run_main
  File "/home/paul/.local/lib/python3.7/site-packages/absl/app.py", line 300 in run
  File "/home/paul/anaconda3/envs/openvino/lib/python3.7/site-packages/tensorflow/python/platform/app.py", line 40 in run
  File "/home/paul/anaconda3/envs/openvino/lib/python3.7/site-packages/tensorflow/lite/toco/python/toco_from_protos.py", line 59 in main
  File "/home/paul/anaconda3/envs/openvino/bin/toco_from_protos", line 10 in <module>
Aborted (core dumped)
```

**Code to reproduce the issue**

```python
import tensorflow as tf

graph_def_file = "model_lcnn_29v2_cpu.pb"

input_arrays = ["0"]
output_arrays = ["MatMul"]

converter = tf.lite.TFLiteConverter.from_frozen_graph(
  graph_def_file, input_arrays, output_arrays)
tflite_model = converter.convert()
open("model_lcnn_29v2.tflite", "wb").write(tflite_model)

```
[](url)

**Comment by haozha111** [comment]
TF Lite's Conv/MaxPool/AvgPool operator only supports NHWC data format right now. I think your model uses NCHW format in those ops. Could you try switch your data format to 'NHWC'?

**Comment by paulbauriegel** [comment]
I would like to switch the data_format, but that is actually not so easy because the model was build in Pytorch->convert to ONNX->convert to frozen graph. And I cannot change the data format of a node without rebuilding the entire graph. Is there some tool from Tensorflow to do that?

**Comment by haozha111** [comment]
There isn't such tool that I'm aware of to convert data format from a graphdef. One way to do this is to manually insert transpose nodes before each of those ops in your graphdef(which could be tricky).

**Comment by paulbauriegel** [comment]
@haozha111 Ok, [modifying the GraphDef](https://github.com/paulbauriegel/tensorflow-tools/blob/master/convert-model-to-NWHC.py) and adding Transpose nodes before and after the convolutional operations let me convert the model. Thanks for the hint 👍

**Comment by haozha111** [comment]
Awesome! We are going to support 'nchw' in the future, so hopefully won't need to do this all on your own. Thanks!

**Comment by ucasiggcas** [comment]
Dear,
how to set the four parameters
--mean_values
--std_dev_values
--default_ranges_min
--default_ranges_max

thx
#32611

**Comment by osheenn** [comment]
> Awesome! We are going to support 'nchw' in the future, so hopefully won't need to do this all on your own. Thanks!

Hey, i am really excited for this. When is it going to happen?

**Comment by jtanios** [comment]
> Awesome! We are going to support 'nchw' in the future, so hopefully won't need to do this all on your own. Thanks!

Any idea when that's happening?

**Comment by maxx2s** [comment]
Hey guys, any updates on this?

**Comment by haozha111** [comment]
> > Awesome! We are going to support 'nchw' in the future, so hopefully won't need to do this all on your own. Thanks!
> 
> Hey y'all, any updates on this?

hi, currently we don't have concrete plans to support it on our roadmap. Sorry about that. If you can share some common scripts that could help walk-around this issue, that will be great. thanks!

**Comment by xserraalza** [comment]
> @haozha111 Ok, [modifying the GraphDef](https://github.com/paulbauriegel/tensorflow-tools/blob/master/convert-model-to-NWHC.py) and adding Transpose nodes before and after the convolutional operations let me convert the model. Thanks for the hint +1
 
Could you please elaborate on how to do that? I have the exact same issue, but I am not sure where to put the transpose and how to modify the GraphDef. Thank you very much!

**Comment by paulbauriegel** [comment]
@xsankar Have a look at the python script I linked in that comment, did it work for you?

**Comment by xsankar** [comment]
@paulbauriegel probably you meant @xserraalza

**Comment by xserraalza** [comment]
Thanks for the quick response! I hadn't noticed the link (it points to the wrong url!), I have now tried it, and it gives me an error on the first node processed:

`
(1, 224, 112, 16)  
(1, 16, 112, 112)  
(1, 16, 224, 112)  
Traceback (most recent call last):\
  File "quantize_tf_model.py", line 42, in <module>\
    assert out_trans.shape == sess.graph.get_tensor_by_name(n_org.name+':0').shape\
AssertionError
`

Do you have any idea on why this may happen?
Thanks!

**Comment by paulbauriegel** [comment]
@xserraalza I'm happy to help, but open an issue here: https://github.com/paulbauriegel/tensorflow-tools/issues I don't think here is the perfect place to discuss why the script fails.

**Comment by xserraalza** [comment]
I managed to make it work changing the order of the strides. Thank you for your work :)

**Comment by MaratZakirov** [comment]
Any update on this?

**Comment by MaratZakirov** [comment]
> I managed to make it work changing the order of the strides. Thank you for your work :)

Could you please share your experience? You probably work with pytorch as I am?

**Comment by xserraalza** [comment]
> > I managed to make it work changing the order of the strides. Thank you for your work :)
> 
> Could you please share your experience? You probably work with pytorch as I am?

I used @paulbauriegel code, and I added the following line after line 29:
`atts["strides"].list.i[-1], atts["strides"].list.i[1] = atts["strides"].list.i[1], atts["strides"].list.i[-1]`

It seemed that the order of the strides channels was not the right one for me. After this change, I managed to convert to NHWC with no problem.

Hope it helps!

**Comment by MaratZakirov** [comment]
> > > I managed to make it work changing the order of the strides. Thank you for your work :)
> > 
> > 
> > Could you please share your experience? You probably work with pytorch as I am?
> 
> I used @paulbauriegel code, and I added the following line after line 29:
> `atts["strides"].list.i[-1], atts["strides"].list.i[1] = atts["strides"].list.i[1], atts["strides"].list.i[-1]`
> 
> It seemed that the order of the strides channels was not the right one for me. After this change, I managed to convert to NHWC with no problem.
> 
> Hope it helps!

Ha ha I just figure out something like that right now even not reading your post)))
Did you convert you model to TFlite. I cant do it even with resnet18 got something like
`Here is a list of operators for which you will need custom implementations: Dilation2D`
Which is completly weird because resnet18 does not have any dilations in convs

**Comment by paulbauriegel** [comment]
@MaratZakirov Yes, forgot to transfer the attributes for the Conv2D layer. I added the fix to the script. As for the `Dilation2D` error look at the solution from https://github.com/tensorflow/tensorflow/issues/38102 maybe that helps:
````
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS,
                                       tf.lite.OpsSet.SELECT_TF_OPS]
````

**Comment by aitikgupta** [comment]
> > > > I managed to make it work changing the order of the strides. Thank you for your work :)
> > > 
> > > 
> > > Could you please share your experience? You probably work with pytorch as I am?
> > 
> > 
> > I used @paulbauriegel code, and I added the following line after line 29:
> > `atts["strides"].list.i[-1], atts["strides"].list.i[1] = atts["strides"].list.i[1], atts["strides"].list.i[-1]`
> > It seemed that the order of the strides channels was not the right one for me. After this change, I managed to convert to NHWC with no problem.
> > Hope it helps!
> 
> Ha ha I just figure out something like that right now even not reading your post)))
> Did you convert you model to TFlite. I cant do it even with resnet18 got something like
> `Here is a list of operators for which you will need custom implementations: Dilation2D`
> Which is completly weird because resnet18 does not have any dilations in convs

[This issue](https://github.com/onnx/onnx-tensorflow/issues/595) leading to [this fix](https://github.com/onnx/onnx-tensorflow/pull/613) might help you, It's an issue when converting to TFlite,  as ONNX -> Frozen pb graph incorporates Dilation2D layer, even when dilations are 1 (by default dilations are 1 in Conv layers)

**Comment by yusuyuan123** [comment]
> @MaratZakirov Yes, forgot to transfer the attributes for the Conv2D layer. I added the fix to the script. As for the `Dilation2D` error look at the solution from #38102 maybe that helps:
> 
> ```
> converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS,
>                                        tf.lite.OpsSet.SELECT_TF_OPS]
> ```

I use your script and get a pb file,but i convert pb to tflite file get a error like this:
F tensorflow/lite/toco/graph_transformations/propagate_fixed_sizes.cc:1305] Check failed: block_shape_array_shape.dims(0) == 2 (3 vs. 2)
Do you have any idea on why this may happen?
Thanks!

**Comment by paulbauriegel** [comment]
@yusuyuan123 Hard to say without having a closer look at your model. You can open a issue in my Repo and we can continue the discussion there.
