### ISSUE TITLE
 fatal error C1083: Cannot open include file: 'ab sl/strings/string_view.h': No such file or directory

### ISSUE THREAD

**Issue by penghao1990** [tensorflow/tensorflow#31126]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (win10):
- TensorFlow installed from (source):
- TensorFlow version:1.14.
- Python version:3.6
- Bazel version (if compiling from source):0.22
- GCC/Compiler version (if compiling from source):cmake3.13.5+MSbuild

**Describe the problem**
I want to build .dll and .lib of TF_C++ API on WIN10.    an error :cannot find absl. And， I have no idea to fix it.
**Provide the exact sequence of commands / steps that you executed before running into the problem**
cmake .. -Thost=x64 -A x64 -DCMAKE_BUILD_TYPE=Release -DSWIG_EXECUTABLE=D:/swigwin-4.0.0/swig.exe -DPYTHON_EXECUTABLE=D:/Anaconda3/envs/tfcc36/python.exe -DPYTHON_LIBRARIES=D:/Anaconda3/envs/tfcc36/libs/python36.lib -Dtensorflow_BUILD_ALL_KERNELS=ON -Dtensorflow_BUILD_CC_EXAMPLE=ON -Dtensorflow_BUILD_CC_TESTS=OFF -Dtensorflow_BUILD_CONTRIB_KERNELS=ON -Dtensorflow_BUILD_MORE_PYTHON_TESTS=OFF -Dtensorflow_BUILD_PYTHON_BINDINGS=ON -Dtensorflow_BUILD_PYTHON_TESTS=OFF -Dtensorflow_BUILD_SHARED_LIB=ON -Dtensorflow_DISABLE_EIGEN_FORCEINLINE=OFF -Dtensorflow_ENABLE_GPU=OFF -Dtensorflow_ENABLE_GRPC_SUPPORT=OFF -Dtensorflow_ENABLE_HDFS_SUPPORT=OFF -Dtensorflow_ENABLE_MKLDNN_SUPPORT=OFF -Dtensorflow_ENABLE_MKL_SUPPORT=OFF -Dtensorflow_ENABLE_POSITION_INDEPENDENT_CODE=ON -Dtensorflow_ENABLE_SNAPPY_SUPPORT=ON -Dtensorflow_ENABLE_SSL_SUPPORT=OFF -Dtensorflow_OPTIMIZE_FOR_NATIVE_ARCH=ON -Dtensorflow_VERBOSE=OFF
MSBuild /p:Configuration=Release ALL_BUILD.vcxproj
**Any other info / logs**

“D:\tfVS\tensorflow-r1.14\tensorflow\contrib\cmake\build\ALL_BUILD.vcxproj”(默认目标) (1) ->
“D:\tfVS\tensorflow-r1.14\tensorflow\contrib\cmake\build\_beam_search_ops.vcxproj”(默认目标) (2) ->
“D:\tfVS\tensorflow-r1.14\tensorflow\contrib\cmake\build\pywrap_tensorflow_internal.vcxproj”(默认目标) (3) ->
“D:\tfVS\tensorflow-r1.14\tensorflow\contrib\cmake\build\pywrap_tensorflow_internal_static.vcxproj”(默认目标) (4) ->
“D:\tfVS\tensorflow-r1.14\tensorflow\contrib\cmake\build\tf_c.vcxproj”(默认目标) (5) ->
“D:\tfVS\tensorflow-r1.14\tensorflow\contrib\cmake\build\tf_cc_framework.vcxproj”(默认目标) (6) ->
“D:\tfVS\tensorflow-r1.14\tensorflow\contrib\cmake\build\tf_core_framework.vcxproj”(默认目标) (7) ->
“D:\tfVS\tensorflow-r1.14\tensorflow\contrib\cmake\build\proto_text.vcxproj”(默认目标) (8) ->
“D:\tfVS\tensorflow-r1.14\tensorflow\contrib\cmake\build\tf_core_lib.vcxproj”(默认目标) (9) ->
(ClCompile 目标) ->
  D:\tfVS\tensorflow-r1.14\tensorflow/core/lib/core/stringpiece.h(29): fatal error C1083: Cannot open include file: 'ab
sl/strings/string_view.h': No such file or directory (compiling source file D:\tfVS\tensorflow-r1.14\tensorflow\core\li
b\core\coding.cc) [D:\tfVS\tensorflow-r1.14\tensorflow\contrib\cmake\build\tf_core_lib.vcxproj]
  D:\tfVS\tensorflow-r1.14\tensorflow/core/lib/core/stringpiece.h(29): fatal error C1083: Cannot open include file: 'ab
sl/strings/string_view.h': No such file or directory (compiling source file D:\tfVS\tensorflow-r1.14\tensorflow\core\li
b\gif\gif_io.cc) [D:\tfVS\tensorflow-r1.14\tensorflow\contrib\cmake\build\tf_core_lib.vcxproj]
  D:\tfVS\tensorflow-r1.14\tensorflow/core/lib/core/stringpiece.h(29): fatal error C1083: Cannot open include file: 'ab
sl/strings/string_view.h': No such file or directory (compiling source file D:\tfVS\tensorflow-r1.14\tensorflow\core\li
b\core\status.cc) [D:\tfVS\tensorflow-r1.14\tensorflow\contrib\cmake\build\tf_core_lib.vcxproj]
  D:\tfVS\tensorflow-r1.14\tensorflow/core/lib/core/stringpiece.h(29): fatal error C1083: Cannot open include file: 'ab
sl/strings/string_view.h': No such file or directory (compiling source file D:\tfVS\tensorflow-r1.14\tensorflow\core\li
b\core\threadpool.cc) [D:\tfVS\tensorflow-r1.14\tensorflow\contrib\cmake\build\tf_core_lib.vcxproj]
  D:\tfVS\tensorflow-r1.14\tensorflow/core/lib/core/stringpiece.h(29): fatal error C1083: Cannot open include file: 'ab
sl/strings/string_view.h': No such file or directory (compiling source file D:\tfVS\tensorflow-r1.14\tensorflow\core\li
b\hash\crc32c.cc) [D:\tfVS\tensorflow-r1.14\tensorflow\contrib\cmake\build\tf_core_lib.vcxproj]
  D:\tfVS\tensorflow-r1.14\tensorflow/core/lib/core/stringpiece.h(29): fatal error C1083: Cannot open include file: 'ab
sl/strings/string_view.h': No such file or directory (compiling source file D:\tfVS\tensorflow-r1.14\tensorflow\core\li
b\db\sqlite.cc) [D:\tfVS\tensorflow-r1.14\tensorflow\contrib\cmake\build\tf_core_lib.vcxproj]
  D:\tfVS\tensorflow-r1.14\tensorflow/core/lib/gtl/array_slice.h(19): fatal error C1083: Cannot open include file: 'abs
l/types/span.h': No such file or directory (compiling source file D:\tfVS\tensorflow-r1.14\tensorflow\core\lib\histogra
m\histogram.cc) [D:\tfVS\tensorflow-r1.14\tensorflow\contrib\cmake\build\tf_core_lib.vcxproj]
  D:\tfVS\tensorflow-r1.14\tensorflow/core/lib/core/stringpiece.h(29): fatal error C1083: Cannot open include file: 'ab
sl/strings/string_view.h': No such file or directory (compiling source file D:\tfVS\tensorflow-r1.14\tensorflow\core\li
b\hash\hash.cc) [D:\tfVS\tensorflow-r1.14\tensorflow\contrib\cmake\build\tf_core_lib.vcxproj]
  D:\tfVS\tensorflow-r1.14\tensorflow/core/lib/core/stringpiece.h(29): fatal error C1083: Cannot open include file: 'ab
sl/strings/string_view.h': No such file or directory (compiling source file D:\tfVS\tensorflow-r1.14\tensorflow\core\li
b\io\block_builder.cc) [D:\tfVS\tensorflow-r1.14\tensorflow\contrib\cmake\build\tf_core_lib.vcxproj]
  D:\tfVS\tensorflow-r1.14\tensorflow/core/lib/core/stringpiece.h(29): fatal error C1083: Cannot open include file: 'ab
sl/strings/string_view.h': No such file or directory (compiling source file D:\tfVS\tensorflow-r1.14\tensorflow\core\li
b\io\path.cc) [D:\tfVS\tensorflow-r1.14\tensorflow\contrib\cmake\build\tf_core_lib.vcxproj]
  D:\tfVS\tensorflow-r1.14\tensorflow/core/lib/core/stringpiece.h(29): fatal error C1083: Cannot open include file: 'ab
sl/strings/string_view.h': No such file or directory (compiling source file D:\tfVS\tensorflow-r1.14\tensorflow\core\li
b\io\inputbuffer.cc) [D:\tfVS\tensorflow-r1.14\tensorflow\contrib\cmake\build\tf_core_lib.vcxproj]
  D:\tfVS\tensorflow-r1.14\tensorflow/core/lib/core/stringpiece.h(29): fatal error C1083: Cannot open include file: 'ab
sl/strings/string_view.h': No such file or directory (compiling source file D:\tfVS\tensorflow-r1.14\tensorflow\core\li
b\io\block.cc) [D:\tfVS\tensorflow-r1.14\tensorflow\contrib\cmake\build\tf_core_lib.vcxproj]
  D:\tfVS\tensorflow-r1.14\tensorflow/core/lib/core/stringpiece.h(29): fatal error C1083: Cannot open include file: 'ab
sl/strings/string_view.h': No such file or directory (compiling source file D:\tfVS\tensorflow-r1.14\tensorflow\core\li
b\io\buffered_inputstream.cc) [D:\tfVS\tensorflow-r1.14\tensorflow\contrib\cmake\build\tf_core_lib.vcxproj]
  D:\tfVS\tensorflow-r1.14\tensorflow/core/lib/core/stringpiece.h(29): fatal error C1083: Cannot open include file: 'ab
sl/strings/string_view.h': No such file or directory (compiling source file D:\tfVS\tensorflow-r1.14\tensorflow\core\li
b\io\format.cc) [D:\tfVS\tensorflow-r1.14\tensorflow\contrib\cmake\build\tf_core_lib.vcxproj]
  D:\tfVS\tensorflow-r1.14\tensorflow/core/lib/core/stringpiece.h(29): fatal error C1083: Cannot open include file: 'ab
sl/strings/string_view.h': No such file or directory (compiling source file D:\tfVS\tensorflow-r1.14\tensorflow\core\li
b\io\iterator.cc) [D:\tfVS\tensorflow-r1.14\tensorflow\contrib\cmake\build\tf_core_lib.vcxproj]
  D:\tfVS\tensorflow-r1.14\tensorflow/core/lib/core/stringpiece.h(29): fatal error C1083: Cannot open include file: 'ab
sl/strings/string_view.h': No such file or directory (compiling source file D:\tfVS\tensorflow-r1.14\tensorflow\core\li
b\io\inputstream_interface.cc) [D:\tfVS\tensorflow-r1.14\tensorflow\contrib\cmake\build\tf_core_lib.vcxproj]
  D:\tfVS\tensorflow-r1.14\tensorflow/core/lib/core/stringpiece.h(29): fatal error C1083: Cannot open include file: 'ab
sl/strings/string_view.h': No such file or directory (compiling source file D:\tfVS\tensorflow-r1.14\tensorflow\core\li
b\io\record_writer.cc) [D:\tfVS\tensorflow-r1.14\tensorflow\contrib\cmake\build\tf_core_lib.vcxproj]
  D:\tfVS\tensorflow-r1.14\tensorflow/core/lib/core/stringpiece.h(29): fatal error C1083: Cannot open include file: 'ab
sl/strings/string_view.h': No such file or directory (compiling source file D:\tfVS\tensorflow-r1.14\tensorflow\core\li
b\io\random_inputstream.cc) [D:\tfVS\tensorflow-r1.14\tensorflow\contrib\cmake\build\tf_core_lib.vcxproj]
  D:\tfVS\tensorflow-r1.14\tensorflow/core/lib/core/stringpiece.h(29): fatal error C1083: Cannot open include file: 'ab
sl/strings/string_view.h': No such file or directory (compiling source file D:\tfVS\tensorflow-r1.14\tensorflow\core\li
b\io\record_reader.cc) [D:\tfVS\tensorflow-r1.14\tensorflow\contrib\cmake\build\tf_core_lib.vcxproj]
  D:\tfVS\tensorflow-r1.14\tensorflow/core/lib/core/stringpiece.h(29): fatal error C1083: Cannot open include file: 'ab
sl/strings/string_view.h': No such file or directory (compiling source file D:\tfVS\tensorflow-r1.14\tensorflow\core\li
b\io\snappy\snappy_inputbuffer.cc) [D:\tfVS\tensorflow-r1.14\tensorflow\contrib\cmake\build\tf_core_lib.vcxproj]
  D:\tfVS\tensorflow-r1.14\tensorflow/core/lib/core/stringpiece.h(29): fatal error C1083: Cannot open include file: 'ab
sl/strings/string_view.h': No such file or directory (compiling source file D:\tfVS\tensorflow-r1.14\tensorflow\core\li
b\io\snappy\snappy_outputbuffer.cc) [D:\tfVS\tensorflow-r1.14\tensorflow\contrib\cmake\build\tf_core_lib.vcxproj]
  D:\tfVS\tensorflow-r1.14\tensorflow/core/lib/core/stringpiece.h(29): fatal error C1083: Cannot open include file: 'ab
sl/strings/string_view.h': No such file or directory (compiling source file D:\tfVS\tensorflow-r1.14\tensorflow\core\li
b\io\table.cc) [D:\tfVS\tensorflow-r1.14\tensorflow\contrib\cmake\build\tf_core_lib.vcxproj]
  D:\tfVS\tensorflow-r1.14\tensorflow/core/lib/core/stringpiece.h(29): fatal error C1083: Cannot open include file: 'ab
sl/strings/string_view.h': No such file or directory (compiling source file D:\tfVS\tensorflow-r1.14\tensorflow\core\li
b\io\table_builder.cc) [D:\tfVS\tensorflow-r1.14\tensorflow\contrib\cmake\build\tf_core_lib.vcxproj]
  D:\tfVS\tensorflow-r1.14\tensorflow/core/lib/core/stringpiece.h(29): fatal error C1083: Cannot open include file: 'ab
sl/strings/string_view.h': No such file or directory (compiling source file D:\tfVS\tensorflow-r1.14\tensorflow\core\li
b\io\two_level_iterator.cc) [D:\tfVS\tensorflow-r1.14\tensorflow\contrib\cmake\build\tf_core_lib.vcxproj]
  D:\tfVS\tensorflow-r1.14\tensorflow/core/lib/core/stringpiece.h(29): fatal error C1083: Cannot open include file: 'ab
sl/strings/string_view.h': No such file or directory (compiling source file D:\tfVS\tensorflow-r1.14\tensorflow\core\li
b\io\zlib_inputstream.cc) [D:\tfVS\tensorflow-r1.14\tensorflow\contrib\cmake\build\tf_core_lib.vcxproj]
  D:\tfVS\tensorflow-r1.14\tensorflow/core/lib/core/stringpiece.h(29): fatal error C1083: Cannot open include file: 'ab
sl/strings/string_view.h': No such file or directory (compiling source file D:\tfVS\tensorflow-r1.14\tensorflow\core\li
b\jpeg\jpeg_mem.cc) [D:\tfVS\tensorflow-r1.14\tensorflow\contrib\cmake\build\tf_core_lib.vcxproj]
  D:\tfVS\tensorflow-r1.14\tensorflow/core/lib/gtl/array_slice.h(19): fatal error C1083: Cannot open include file: 'abs
l/types/span.h': No such file or directory (compiling source file D:\tfVS\tensorflow-r1.14\tensorflow\core\lib\random\d
istribution_sampler.cc) [D:\tfVS\tensorflow-r1.14\tensorflow\contrib\cmake\build\tf_core_lib.vcxproj]
  D:\tfVS\tensorflow-r1.14\tensorflow/core/lib/core/stringpiece.h(29): fatal error C1083: Cannot open include file: 'ab
sl/strings/string_view.h': No such file or directory (compiling source file D:\tfVS\tensorflow-r1.14\tensorflow\core\li
b\io\zlib_outputbuffer.cc) [D:\tfVS\tensorflow-r1.14\tensorflow\contrib\cmake\build\tf_core_lib.vcxproj]
  D:\tfVS\tensorflow-r1.14\tensorflow\core\lib\png\png_io.cc(27): fatal error C1083: Cannot open include file: 'absl/ba
se/casts.h': No such file or directory [D:\tfVS\tensorflow-r1.14\tensorflow\contrib\cmake\build\tf_core_lib.vcxproj]
  D:\tfVS\tensorflow-r1.14\tensorflow/core/lib/gtl/array_slice.h(19): fatal error C1083: Cannot open include file: 'abs
l/types/span.h': No such file or directory (compiling source file D:\tfVS\tensorflow-r1.14\tensorflow\core\lib\random\r
andom_distributions.cc) [D:\tfVS\tensorflow-r1.14\tensorflow\contrib\cmake\build\tf_core_lib.vcxproj]
  D:\tfVS\tensorflow-r1.14\tensorflow/core/lib/core/stringpiece.h(29): fatal error C1083: Cannot open include file: 'ab
sl/strings/string_view.h': No such file or directory (compiling source file D:\tfVS\tensorflow-r1.14\tensorflow\core\li
b\strings\numbers.cc) [D:\tfVS\tensorflow-r1.14\tensorflow\contrib\cmake\build\tf_core_lib.vcxproj]
  D:\tfVS\tensorflow-r1.14\tensorflow/core/lib/core/stringpiece.h(29): fatal error C1083: Cannot open include file: 'ab
sl/strings/string_view.h': No such file or directory (compiling source file D:\tfVS\tensorflow-r1.14\tensorflow\core\li
b\strings\ordered_code.cc) [D:\tfVS\tensorflow-r1.14\tensorflow\contrib\cmake\build\tf_core_lib.vcxproj]
  D:\tfVS\tensorflow-r1.14\tensorflow/core/lib/strings/proto_text_util.h(19): fatal error C1083: Cannot open include fi
le: 'absl/strings/str_cat.h': No such file or directory (compiling source file D:\tfVS\tensorflow-r1.14\tensorflow\core
\lib\strings\proto_text_util.cc) [D:\tfVS\tensorflow-r1.14\tensorflow\contrib\cmake\build\tf_core_lib.vcxproj]
  D:\tfVS\tensorflow-r1.14\tensorflow/core/lib/core/stringpiece.h(29): fatal error C1083: Cannot open include file: 'ab
sl/strings/string_view.h': No such file or directory (compiling source file D:\tfVS\tensorflow-r1.14\tensorflow\core\li
b\monitoring\collection_registry.cc) [D:\tfVS\tensorflow-r1.14\tensorflow\contrib\cmake\build\tf_core_lib.vcxproj]
  D:\tfVS\tensorflow-r1.14\tensorflow/core/lib/core/stringpiece.h(29): fatal error C1083: Cannot open include file: 'ab
sl/strings/string_view.h': No such file or directory (compiling source file D:\tfVS\tensorflow-r1.14\tensorflow\core\li
b\monitoring\sampler.cc) [D:\tfVS\tensorflow-r1.14\tensorflow\contrib\cmake\build\tf_core_lib.vcxproj]
  D:\tfVS\tensorflow-r1.14\tensorflow/core/lib/core/stringpiece.h(29): fatal error C1083: Cannot open include file: 'ab
sl/strings/string_view.h': No such file or directory (compiling source file D:\tfVS\tensorflow-r1.14\tensorflow\core\li
b\strings\scanner.cc) [D:\tfVS\tensorflow-r1.14\tensorflow\contrib\cmake\build\tf_core_lib.vcxproj]
  D:\tfVS\tensorflow-r1.14\tensorflow/core/lib/strings/str_util.h(22): fatal error C1083: Cannot open include file: 'ab
sl/base/macros.h': No such file or directory (compiling source file D:\tfVS\tensorflow-r1.14\tensorflow\core\lib\string
s\str_util.cc) [D:\tfVS\tensorflow-r1.14\tensorflow\contrib\cmake\build\tf_core_lib.vcxproj]
  D:\tfVS\tensorflow-r1.14\tensorflow/core/lib/core/stringpiece.h(29): fatal error C1083: Cannot open include file: 'ab
sl/strings/string_view.h': No such file or directory (compiling source file D:\tfVS\tensorflow-r1.14\tensorflow\core\li
b\strings\base64.cc) [D:\tfVS\tensorflow-r1.14\tensorflow\contrib\cmake\build\tf_core_lib.vcxproj]
  D:\tfVS\tensorflow-r1.14\tensorflow/core/lib/core/stringpiece.h(29): fatal error C1083: Cannot open include file: 'ab
sl/strings/string_view.h': No such file or directory (compiling source file D:\tfVS\tensorflow-r1.14\tensorflow\core\li
b\strings\strcat.cc) [D:\tfVS\tensorflow-r1.14\tensorflow\contrib\cmake\build\tf_core_lib.vcxproj]
  D:\tfVS\tensorflow-r1.14\tensorflow\core\lib\wav\wav_io.cc(22): fatal error C1083: Cannot open include file: 'absl/ba
se/casts.h': No such file or directory [D:\tfVS\tensorflow-r1.14\tensorflow\contrib\cmake\build\tf_core_lib.vcxproj]
  D:\tfVS\tensorflow-r1.14\tensorflow/core/lib/core/stringpiece.h(29): fatal error C1083: Cannot open include file: 'ab
sl/strings/string_view.h': No such file or directory (compiling source file D:\tfVS\tensorflow-r1.14\tensorflow\core\fr
amework\resource_handle.cc) [D:\tfVS\tensorflow-r1.14\tensorflow\contrib\cmake\build\tf_core_lib.vcxproj]
  D:\tfVS\tensorflow-r1.14\tensorflow\core\lib\strings\proto_serialization.cc(19): fatal error C1083: Cannot open inclu
de file: 'absl/memory/memory.h': No such file or directory [D:\tfVS\tensorflow-r1.14\tensorflow\contrib\cmake\build\tf_
core_lib.vcxproj]
  D:\tfVS\tensorflow-r1.14\tensorflow/core/lib/core/stringpiece.h(29): fatal error C1083: Cannot open include file: 'ab
sl/strings/string_view.h': No such file or directory (compiling source file D:\tfVS\tensorflow-r1.14\tensorflow\core\pl
atform\default\human_readable_json.cc) [D:\tfVS\tensorflow-r1.14\tensorflow\contrib\cmake\build\tf_core_lib.vcxproj]
  D:\tfVS\tensorflow-r1.14\tensorflow/core/lib/core/stringpiece.h(29): fatal error C1083: Cannot open include file: 'ab
sl/strings/string_view.h': No such file or directory (compiling source file D:\tfVS\tensorflow-r1.14\tensorflow\core\pl
atform\file_system.cc) [D:\tfVS\tensorflow-r1.14\tensorflow\contrib\cmake\build\tf_core_lib.vcxproj]
  D:\tfVS\tensorflow-r1.14\tensorflow/core/lib/core/stringpiece.h(29): fatal error C1083: Cannot open include file: 'ab
sl/strings/string_view.h': No such file or directory (compiling source file D:\tfVS\tensorflow-r1.14\tensorflow\core\pl
atform\file_system_helper.cc) [D:\tfVS\tensorflow-r1.14\tensorflow\contrib\cmake\build\tf_core_lib.vcxproj]
  D:\tfVS\tensorflow-r1.14\tensorflow/core/lib/core/stringpiece.h(29): fatal error C1083: Cannot open include file: 'ab
sl/strings/string_view.h': No such file or directory (compiling source file D:\tfVS\tensorflow-r1.14\tensorflow\core\pl
atform\platform_strings.cc) [D:\tfVS\tensorflow-r1.14\tensorflow\contrib\cmake\build\tf_core_lib.vcxproj]
  D:\tfVS\tensorflow-r1.14\tensorflow/core/lib/core/stringpiece.h(29): fatal error C1083: Cannot open include file: 'ab
sl/strings/string_view.h': No such file or directory (compiling source file D:\tfVS\tensorflow-r1.14\tensorflow\core\pl
atform\tensor_coding.cc) [D:\tfVS\tensorflow-r1.14\tensorflow\contrib\cmake\build\tf_core_lib.vcxproj]
  D:\tfVS\tensorflow-r1.14\tensorflow/core/lib/core/stringpiece.h(29): fatal error C1083: Cannot open include file: 'ab
sl/strings/string_view.h': No such file or directory (compiling source file D:\tfVS\tensorflow-r1.14\tensorflow\core\pl
atform\windows\windows_file_system.cc) [D:\tfVS\tensorflow-r1.14\tensorflow\contrib\cmake\build\tf_core_lib.vcxproj]

    105 个警告
    48 个错误
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by gadagashwini** [comment]
@penghao1990,
The TensorFlow team does not officially support cmake, sorry. Please try out building from [source with Bazel](https://www.tensorflow.org/install/source_windows). Thanks!

**Comment by gadagashwini** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
