### ISSUE TITLE
Error 'int8x8_t' does not name a type when building with bazel

### ISSUE THREAD

**Issue by hsinpaohuang** [tensorflow/tensorflow#31124]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): ARMv8 aarch64 CentOS Linux release 7.6.1810
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): Source
- TensorFlow version: 1.14
- Python version: 3.7.3
- Installed using virtualenv? pip? conda?: virtualenv
- Bazel version (if compiling from source): 0.24.1
- GCC/Compiler version (if compiling from source): gcc4.8.5
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

**Describe the problem**

Hello,
I encountered the following error while trying to build tensorflow on an ARM machine:

```
/<install folder>/tensorflow/lite/kernels/BUILD:374:1: C++ compilation of rule '//tensorflow/lite/kernels:builtin_op_kernels' failed (Exit 1)
cc1plus: warning: command line option '-std=gnu99' is valid for C/ObjC but not for C++ [enabled by default]
In file included from ./tensorflow/lite/kernels/internal/optimized/depthwiseconv_uint8.h:22:0,
                 from ./tensorflow/lite/kernels/internal/optimized/depthwiseconv_multithread.h:22,
                 from tensorflow/lite/kernels/depthwise_conv.cc:29:
./tensorflow/lite/kernels/internal/optimized/depthwiseconv_uint8_3x3_filter.h: In static member function 'static void tflite::optimized_ops::depthwise_conv::WorkspacePrefetchWrite<(tflite::DepthwiseConvImplementation)3>::Run(int8, int, int8*)':
./tensorflow/lite/kernels/internal/optimized/depthwiseconv_uint8_3x3_filter.h:5775:11: error: 'int8x8_t' does not name a type
     const int8x8_t fill_data_vec_int8 = vdup_n_s8(fill_data);
           ^
./tensorflow/lite/kernels/internal/optimized/depthwiseconv_uint8_3x3_filter.h:5776:11: error: 'uint32x2_t' does not name a type
     const uint32x2_t fill_data_vec = vreinterpret_u32_s8(fill_data_vec_int8);
           ^
./tensorflow/lite/kernels/internal/optimized/depthwiseconv_uint8_3x3_filter.h:5780:55: error: 'fill_data_vec' was not declared in this scope
       vst1_lane_u32(reinterpret_cast<uint32_t*>(ptr), fill_data_vec, 0);
                                                       ^
./tensorflow/lite/kernels/internal/optimized/depthwiseconv_uint8_3x3_filter.h:5780:71: error: 'vst1_lane_u32' was not declared in this scope
       vst1_lane_u32(reinterpret_cast<uint32_t*>(ptr), fill_data_vec, 0);
                                                                       ^
./tensorflow/lite/kernels/internal/optimized/depthwiseconv_uint8_3x3_filter.h:5783:19: error: 'fill_data_vec' was not declared in this scope
                   fill_data_vec, 0);
                   ^
./tensorflow/lite/kernels/internal/optimized/depthwiseconv_uint8_3x3_filter.h:5783:35: error: 'vst1_lane_u32' was not declared in this scope
                   fill_data_vec, 0);
                                   ^
Target //tensorflow/tools/pip_package:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 26.504s, Critical Path: 10.13s
INFO: 23 processes: 23 local.
FAILED: Build did NOT complete successfully
```

**Provide the exact sequence of commands / steps that you executed before running into the problem**

1. Add the following code to the top of `<install folder>/tensorflow/WORKSPACE`, as suggested [here](https://github.com/tensorflow/tensorflow/issues/28824#issuecomment-493675905):

```
http_archive(
    name = "build_bazel_rules_nodejs",
    # Replace with a real SHA256 checksum
    sha256 = "{SHA256}"
    # Replace with a real commit SHA
    strip_prefix = "rules_nodejs-{HEAD}",
    urls = ["https://github.com/bazelbuild/rules_nodejs/archive/{HEAD}.tar.gz"],
)
```
2. Run `./configure` with all option set to n
3. Build tensorflow `bazel build --host_copt="-std=gnu99" --copt="-std=gnu99" --conlyopt="-std=gnu99" //tensorflow/tools/pip_package:build_pip_package`

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.
See above

Any help would be appreciated.

**Comment by gadagashwini** [comment]
@hsinpaohuang, Just to verify, did you install tensorflow lite following the instructions mentioned in the [Tensorflow](https://www.tensorflow.org/lite/guide/build_arm64) website on ARM. Thanks!

**Comment by hsinpaohuang** [comment]
> @hsinpaohuang, Just to verify, did you install tensorflow lite following the instructions mentioned in the [Tensorflow](https://www.tensorflow.org/lite/guide/build_arm64) website on ARM. Thanks!

@gadagashwini, I followed the instructions on how to build tensorflow (not lite) from source from the [official website](https://www.tensorflow.org/install/source).

**Comment by gadagashwini** [comment]
@hsinpaohuang The [official website](https://www.tensorflow.org/install/source_windows) provides the instructions to build Tensorflow on Linux or MacOS platform. Looks like you are building Tensorflow on ARM. Please let me know if my understanding is bad. Thanks!

**Comment by hsinpaohuang** [comment]
> @hsinpaohuang The [official website](https://www.tensorflow.org/install/source_windows) provides the instructions to build Tensorflow on Linux or MacOS platform. Looks like you are building Tensorflow on ARM. Please let me know if my understanding is bad. Thanks!

@gadagashwini You're right. I found a precompiled .whl for aarch64 [here](https://github.com/lhelontra/tensorflow-on-arm) and it worked. Thank you. Closing this issue.

**Comment by gadagashwini** [comment]
Are you satisfied with the resolution of your issue?<br> [Yes](https://docs.google.com/forms/d/e/1FAIpQLSfaP12TRhd9xSxjXZjcZFNXPGk4kc1-qMdv3gc6bEP90vY1ew/viewform?entry.85265664=Yes&entry.2137816233=31124)<br> [No](https://docs.google.com/forms/d/e/1FAIpQLSfaP12TRhd9xSxjXZjcZFNXPGk4kc1-qMdv3gc6bEP90vY1ew/viewform?entry.85265664=No&entry.2137816233=31124)
