### ISSUE TITLE
Can not run  ./build_ios_universal_lib.sh

### ISSUE THREAD

**Issue by ericjiang18** [tensorflow/tensorflow#31134]
According to https://www.tensorflow.org/lite/guide/build_ios, I am running tensorflow/lite/tools/make/build_ios_universal_lib.sh. However, when I run it, it gives me the error: 

Undefined symbols for architecture x86_64:
  "tflite::ResourceVariable::~ResourceVariable()", referenced from:
      tflite::Interpreter::~Interpreter() in benchmark-lib.a(interpreter.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [/Users/broccoli/Downloads/tensorflow-master/tensorflow/lite/tools/make/gen/ios_x86_64/bin/benchmark_model] Error 1

Is there any way to fix this error?

**Comment by spiderMast** [comment]
I had the same problem

**Comment by ericjiang18** [comment]
any news?

**Comment by nkjassal** [comment]
I'm getting a similar issue with the build_ios_universal_lib.sh:
```
Undefined symbols for architecture x86_64:
  "tflite::Interpreter::AllocateTensors()", referenced from:
      _main in minimal.o
  "tflite::Interpreter::Invoke()", referenced from:
      _main in minimal.o
  "tflite::Interpreter::~Interpreter()", referenced from:
      _main in minimal.o
  "tflite::FlatBufferModel::BuildFromFile(char const*, tflite::ErrorReporter*)", referenced from:
      _main in minimal.o
  "tflite::FlatBufferModel::~FlatBufferModel()", referenced from:
      _main in minimal.o
  "tflite::InterpreterBuilder::InterpreterBuilder(tflite::FlatBufferModel const&, tflite::OpResolver const&)", referenced from:
      _main in minimal.o
  "tflite::InterpreterBuilder::~InterpreterBuilder()", referenced from:
      _main in minimal.o
  "tflite::InterpreterBuilder::operator()(std::__1::unique_ptr<tflite::Interpreter, std::__1::default_delete<tflite::Interpreter> >*)", referenced from:
      _main in minimal.o
  "tflite::DefaultErrorReporter()", referenced from:
      _main in minimal.o
  "tflite::PrintInterpreterState(tflite::Interpreter*)", referenced from:
      _main in minimal.o
  "tflite::ops::builtin::BuiltinOpResolver::BuiltinOpResolver()", referenced from:
      _main in minimal.o
  "vtable for tflite::MutableOpResolver", referenced from:
      _main in minimal.o
  NOTE: a missing vtable usually means the first non-inline virtual member function has no definition.
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by yyoon** [comment]
Sorry for the late update to this issue.
The `build_ios_universal.sh` is being deprecated, and the new recommended way of building the TFLite for iOS is using bazel instead.

Could you follow the [recently updated build guide](https://www.tensorflow.org/lite/guide/build_ios) and see if that works for you?

**Comment by ericjiang18** [comment]
@yyoon Thanks I will look into it!

**Comment by yyoon** [comment]
Let me close the bug for now. Please feel free to reopen or file a new issue if the problem persists.
