### ISSUE TITLE
[TF 2.0] gRPC error, in TPUStrategy experimental_distribute_dataset

### ISSUE THREAD

**Issue by captain-pool** [tensorflow/tensorflow#31138]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): Binary
- TensorFlow version (use command below): TF 2.0 Beta 1
- Python version: 3.5
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
Raises this error.
```
InternalError: Failed copying input tensor from /job:worker/replica:0/task:0/device:CPU:0 to /job:worker/replica:0/task:1/device:CPU:0 in order to run ExperimentalAutoShardDataset: Unable to parse tensor proto
Additional GRPC error information:
{"created":"@1564422681.083878500","description":"Error received from peer","file":"external/grpc/src/core/lib/surface/call.cc","file_line":1039,"grpc_message":"Unable to parse tensor proto","grpc_status":3} [Op:ExperimentalAutoShardDataset]
```
**Describe the expected behavior**
Work without any error
**Code to reproduce the issue**
Running the following on Colab produces the error.
`!pip3 install tensorflow==2.0.0b1 &> /dev/null`
```python3
import tensorflow as tf
import os
cluster = tf.distribute.cluster_resolver.TPUClusterResolver(tpu="grpc://%s" % os.environ["COLAB_TPU_ADDR"])
tf.config.experimental_connect_to_host(cluster.get_master())
tf.tpu.experimental.initialize_tpu_system(cluster)
strategy = tf.distribute.experimental.TPUStrategy(cluster)
dataset = tf.data.Dataset.range(100).batch(16)
distributed_dataset = strategy.experimental_distribute_dataset(dataset)
```
CC:
@srjoglekar246 
@vbardiovskyg

**Comment by captain-pool** [comment]
This fixed the issue.
Downloading TF Nightly 2.0 and disabling auto_sharding helped fixed the issue.

**Comment by frankchn** [comment]
Hi @captain-pool, thanks your report. A couple of questions:

1) Which version of Cloud TPUs are you using?
2) Are you using a single TPU or a slice of a Cloud TPU pod (i.e. was it a v2/v3-8 or was it a v2-32 / v3-32 or above)?

**Comment by captain-pool** [comment]
@frankchn I'm using single TPU, v2-8, installed with nightly build.

**Comment by frankchn** [comment]
To clarify, you selected the "nightly" version when creating the TPU in the console and/or created the TPU with `ctpu --version=nightly` or `gcloud compute tpus create --version=nightly`?

**Comment by captain-pool** [comment]
Yep
