### ISSUE TITLE
[go] Include MetaGraphDef in SavedModel for go library

### ISSUE THREAD

**Issue by elaPa** [tensorflow/tensorflow#31140]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using): 1.14
- Are you willing to contribute it (Yes/No): Yes

**Describe the feature and the current behavior/state.**
Currently, the MetaGraphDef is not included in the SavedModel struct (https://github.com/tensorflow/tensorflow/blob/master/tensorflow/go/saved_model.go). The underlying cause is that the protobufs are not pregenerated for go.

**Will this change the current api? How?**
Yes, but It should be a backwards compatible change - the new exposed MetaGraphDef field will be added to SavedModel struct.

**Who will benefit with this feature?**
Everyone who runs inference using go and needs to dynamically load the model's meta graph. Currently, the meta graph /  signature needs to be hardcoded in the code, and it may be fragile if input or output tensor names are change in the python code that generated the saved model. 

**Any Other info.**
Please see the similar issue for java here: https://github.com/tensorflow/tensorflow/issues/19441

**Comment by jhseu** [comment]
Do you need this for the Signature field? That has been added since this was filed.

**Comment by elaPa** [comment]
Yes, I needed this for the signature field. Perfect, thank you for letting me know. Closing this issue then.
