### ISSUE TITLE
FailedPreconditionError when training BERT on Colab

### ISSUE THREAD

**Issue by sangurocactus** [tensorflow/tensorflow#31148]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on a mobile device: N/A
- TensorFlow installed from (source or binary): Not sure
- TensorFlow version (use command below): 1.14.0
- Python version: Python 3
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
We are trying to train a BERT model on Google Colab in keras with tensorflow hub.  The codes are largely copied from https://towardsdatascience.com/bert-in-keras-with-tensorflow-hub-76bcbc9417b with slight modification.  
The model after compilation failed to generate the prediction. I continue to get the error message 'FailedPreconditionError' despite 'with tf.Session() as sess:
     sess.run(tf.global_variables_initializer())'

**Describe the expected behavior**
We expect the model to run and build predictions. 

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.
```def build_model(max_seq_length): 
    in_id = tf.keras.layers.Input(shape=(max_seq_length,), name="input_ids")
    in_mask = tf.keras.layers.Input(shape=(max_seq_length,), name="input_masks")
    in_segment = tf.keras.layers.Input(shape=(max_seq_length,), name="segment_ids")
    
    bert_inputs = [in_id, in_mask, in_segment]
    
    bert_output = BertLayer(n_fine_tune_layers=3, pooling="sequence_output")(bert_inputs)
    
    print(bert_output)
    
    dense = tf.keras.layers.Dense(256, activation='relu')(bert_output)
    
    pred = tf.keras.layers.Dense(1, activation='sigmoid')(dense)
    
    model = tf.keras.models.Model(inputs=bert_inputs, outputs=pred)
    
    model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
    
    model.summary()
    
    return model

def initialize_vars(sess):
    sess.run(tf.local_variables_initializer())
    sess.run(tf.global_variables_initializer())
    sess.run(tf.tables_initializer())
    K.set_session(sess)

sess = tf.Session()

model = build_model(max_seq_length)

with tf.Session() as sess:
     sess.run(tf.global_variables_initializer())

model.fit(
    [train_input_ids, train_input_masks, train_segment_ids], 
    train_labels,
    validation_data=([test_input_ids, test_input_masks, test_segment_ids], test_labels),
    epochs=1,
    batch_size=32
)```

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.
```Tensor("bert_layer_12/bert_layer_12_module_apply_tokens/bert/encoder/Reshape_13:0", shape=(?, ?, 768), dtype=float32)
Model: "model_12"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
==================================================================================================
input_ids (InputLayer)          [(None, 32)]         0                                            
__________________________________________________________________________________________________
input_masks (InputLayer)        [(None, 32)]         0                                            
__________________________________________________________________________________________________
segment_ids (InputLayer)        [(None, 32)]         0                                            
__________________________________________________________________________________________________
bert_layer_12 (BertLayer)       (None, None, 768)    108931396   input_ids[0][0]                  
                                                                 input_masks[0][0]                
                                                                 segment_ids[0][0]                
__________________________________________________________________________________________________
dense_24 (Dense)                (None, None, 256)    196864      bert_layer_12[0][0]              
__________________________________________________________________________________________________
dense_25 (Dense)                (None, None, 1)      257         dense_24[0][0]                   
==================================================================================================
Total params: 109,128,517
Trainable params: 21,460,737
Non-trainable params: 87,667,780
__________________________________________________________________________________________________
Train on 65 samples, validate on 124 samples
---------------------------------------------------------------------------
FailedPreconditionError                   Traceback (most recent call last)
<ipython-input-43-622dfa03de82> in <module>()
     11     validation_data=([test_input_ids, test_input_masks, test_segment_ids], test_labels),
     12     epochs=1,
---> 13     batch_size=32
     14 )

3 frames
/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py in __call__(self, *args, **kwargs)
   1456         ret = tf_session.TF_SessionRunCallable(self._session._session,
   1457                                                self._handle, args,
-> 1458                                                run_metadata_ptr)
   1459         if run_metadata:
   1460           proto_data = tf_session.TF_GetBuffer(run_metadata_ptr)

FailedPreconditionError: Error while reading resource variable bert_layer_12_module/bert/encoder/layer_10/attention/output/LayerNorm/gamma from Container: localhost. This could mean that the variable was uninitialized. Not found: Resource localhost/bert_layer_12_module/bert/encoder/layer_10/attention/output/LayerNorm/gamma/N10tensorflow3VarE does not exist.
	 [[{{node bert_layer_12/bert_layer_12_module_apply_tokens/bert/encoder/layer_10/attention/output/LayerNorm/batchnorm/mul/ReadVariableOp}}]]```

**Comment by gowtham-kp** [comment]
@sangurocactus Please refer to the following solution and let me know if it helps in resolving your issue. Thanks!

**Comment by sangurocactus** [comment]
@gowtham-kp Sorry - is there a link or an image with the solution following your message? I don't see any instruction apart from the one-line message you sent me. Thanks.

**Comment by gowtham-kp** [comment]
Yes @sangurocactus Just for the refence again, here's [some workaround](https://github.com/tensorflow/tensorflow/issues/28287#issuecomment-495005162) for your problem. Thanks!

**Comment by gowtham-kp** [comment]
Closing this issue due to the lack of inactivity. Please add additional comments and we can open the issue again. Thanks!

**Comment by hoangcuong2011** [comment]
I went through this problem and I found the solution @gowthamkpr suggested did not work.
Instead, I found the [solution](https://stackoverflow.com/questions/34001922/failedpreconditionerror-attempting-to-use-uninitialized-in-tensorflow) from stackoverflow helps. I hope my experience is helpful to anyone who happened to stuck with this issue.
