### ISSUE TITLE
Tensorflow 1.14 Keras functional API mixed with ops using placeholders throws InvalidArgumentError 'You must feed a value for placeholder tensor'

### ISSUE THREAD

**Issue by mbeissinger** [tensorflow/tensorflow#31147]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): Binary
- TensorFlow version (use command below): 1.14.0
- Python version: 3.6.8
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

**Describe the current behavior**
Keras layers that have an input dependent on a Tensorflow placeholder will throw an InvalidArgumentError on the op creation step asking to feed a value for the placeholder. Specifically, this happens during the `base_layer_utils.create_keras_history(inputs)` step in the `__call__` function on the layer, where the inputs to the Keras layer are passed through a `GraphExecutionFunction` object made during `backend.function([], op_input)([])`. This exception is new in Tensorflow 1.14.0.

**Describe the expected behavior**
As in previous versions of Tensorflow, I would not expect the InvalidArgumentError to be thrown when I am building the graph mixing Keras with Tensorflow.

**Code to reproduce the issue**
```python
import tensorflow as tf

def compile_errors():
    tf_graph = tf.Graph()
    with tf_graph.as_default():
        image = tf.keras.Input(shape=[224, 224, 3], dtype=tf.float32, name="image")
        scale = tf.placeholder(dtype=tf.float32, shape=[], name="scale")
        scaled_image = image * scale
        conv = tf.keras.layers.Conv2D(filters=32, kernel_size=3, name="conv2d")(scaled_image)
        # conv errors on __call__ here due to create_keras_history making a GraphExecutionFunction:
        # tensorflow.python.framework.errors_impl.InvalidArgumentError: You must feed a value for placeholder tensor 'scale' with dtype float
        # 	 [[{{node scale}}]]

def compile_succeeds():
    tf_graph = tf.Graph()
    with tf_graph.as_default():
        image = tf.keras.Input(shape=[224, 224, 3], dtype=tf.float32, name="image")
        scale = tf.placeholder(dtype=tf.float32, shape=[], name="scale")
        scaled_image = tf.keras.layers.Lambda(function=lambda tensors: tensors[0] * tensors[1])([image, scale])
        conv = tf.keras.layers.Conv2D(filters=32, kernel_size=3, name="conv2d")(scaled_image)
        # this succeeds

if __name__ == "__main__":
    try:
        compile_errors()
        print("Functional API compilation succeeded.")
    except Exception as e:
        print("Functional API compilation errored!", e)
    print()
    compile_succeeds()
    print("Explicit Keras Lambda Layer compilation succeeded.")
```

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by gowtham-kp** [comment]
@mbeissinger As mentioed in this [issue](https://stackoverflow.com/questions/50321139/keras-error-you-must-feed-a-value-for-placeholder-tensor) 'scale' is a  "symbolic" tensor.

This means, they have absolutely no data (or value) until the moment you start fitting or predicting.

**Comment by mbeissinger** [comment]
The example script is not running in eager execution mode and I am not expecting the symbolic tensor made by the placeholder to have or need any value at compile time. Tensorflow 1.13.2 did not throw this exception, why did the behavior change in 1.14 to expect placeholder values immediately and not just at session.run?

**Comment by nairouz** [comment]
Keras does not allow TensorFlow ops unless they are wrapped by a Lambda layer.
@mbeissinger I think there is no bug here.

**Comment by gowtham-kp** [comment]
@nairouz This looks like a bug as TF 1.13 doesn't throw any error but it throws an error with TF 1.14. I think this is a bug.

**Comment by ymodak** [comment]
This is fixed with latest version of TF nightly build '1.15.0-dev20190821'. Thanks!
