### ISSUE TITLE
initializer option for all RNNCell's

### ISSUE THREAD

**Issue by davek44** [tensorflow/tensorflow#3115]
RNN's are very sensitive to the initial weight settings, but only the LSTMCell allows the user to specify an initializer. Could we add similar initializer options for all cells?

More control would be particularly helpful for implementing ReLU RNN's (http://arxiv.org/abs/1504.00941), where the hidden-to-hidden weight matrix should be initialized to the identity matrix.

**Comment by ebrevdo** [comment]
Most cells in core use a merged weight matrix for all gates for performance purposes, making gate specific initialization difficult.  If you have an approach that doesn't involve breaking up the weights into 4 smaller tensors, we should consider it for merging.

**Comment by alquraishi** [comment]
I don't think the issue that @davek44 is raising is gate-specific initialization, but rather just initialization period. LSTMCell allows the user to pass an initializer (used for all gates), but the other types of cells do not (e.g. GRUs).

**Comment by davek44** [comment]
Yes, initializers for all different types of cells (like LSTMCell already has) is an important first step.

@ebrevdo, I see the challenge in trading off flexibility for complexity in initializing different matrices. Are you saying it's also a programming challenge? I imagined it was straightforward to initialize the matrices separately and combine them into the merged version.

**Comment by ebrevdo** [comment]
Performing a concat & then a split of the gradients will still slow down calculation, so I would not modify existing RNNCells with this behavior.  LSTMCell provides the ability to initialize the shared matrix, not individual gate weights.

**Comment by ebrevdo** [comment]
In addition, that initialization option is deprecated, since you can just use tf.variable_scope with a proper initializer (which is what LSTMCell does under the hood).  that parameter will probably go away soonish.

**Comment by alquraishi** [comment]
@davek44 probably the easiest approach to initializing parts of the LSTM matrix differently is to separately construct the desired matrices, concatenate them, and then assign their value to the LSTM matrix using assign.

**Comment by davek44** [comment]
Thanks for the suggestion @alquraishi! I'm most interested in Geoff Hinton's identity initialization of the hidden-hidden weight matrix of the BasicRNNCell. It sounds like the codebase doesn't want to move in the initialization direction that I imagined, so I'll explore ad hoc methods to get it done. Thanks for the feedback @ebrevdo

**Comment by jrajagopal** [comment]
@davek44 Did you get any further with your exploration? I am very much interested in the identity initialization for just the RNN hidden-hidden weights.

**Comment by davek44** [comment]
I did not, but the new CuDNN RNN code appears to have a ReLU RNN that I've been meaning to try. Check it out here: https://github.com/tensorflow/tensorflow/tree/master/tensorflow/contrib/cudnn_rnn

**Comment by jrajagopal** [comment]
I looked that up, but couldn't find gen_cudnn_rnn_ops.py meaning I can't tell how this is different than any RNNCell with activation = tf.nn.relu. Thoughts?

**Comment by davek44** [comment]
The CuDNN RNN code is quite different from the previous Cell-centric framework. I haven't spent much time with it, but you have to pass in your own parameter tensor, which makes it easy to initialize with the identity.

**Comment by ebrevdo** [comment]
There are other changes happening to rnncells right now, adding initializer
arguments will have to wait a while anyway.  If someone is working on this
please sync with me first.

**Comment by Robomate** [comment]
hello, what is the current status for Api 1.2? Can please provide anyone an example how to assign weights to RNN or LSTM cells? with tf.assign, how does that work?

**Comment by blx22** [comment]
Hello, I am also wondering if there are any updates for this? I am currently trying to deal with transfer learning for LSTMCell. I would like to initialize the weights of the LSTMCell with my pretrained model weights. However, I am not very sure how should I approached this problem.

**Comment by amin07** [comment]
Write a new cell, modify call to _Linear() with your trained weights inside your new cell's cell() call..

**Comment by gauravbansal98** [comment]
@davek44 I am trying to initialize the cell with a constant initializer but it is giving en error. The code which I'm using is -  
f = [np.random.normal(size = [15, 40]), np.random.normal(size = [40,])]
init = tf.constant_initializer(f, verify_shape = True, dtype = tf.float32)

cell = tf.contrib.rnn.LSTMCell(lstm_units, initializer = init)
initial_state = cell.zero_state(2, dtype = tf.float32)
unused_encoder_outputs, encoder_state =tf.nn.dynamic_rnn(cell ,source_seq_embedded,sequence_length=source_seq_len,dtype = tf.float32, initial_state = initial_state)

It is giving error - 
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-2-445bac49bd02> in <module>()
     29 initial_state = cell.zero_state(2, dtype = tf.float32)
     30 unused_encoder_outputs, encoder_state =tf.nn.dynamic_rnn(cell ,source_seq_embedded,sequence_length=source_seq_len,
---> 31                                                         dtype = tf.float32, initial_state = initial_state)
     32 
     33 sampling_prob = tf.Variable(0.0, dtype=tf.float32)

/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/rnn.py in dynamic_rnn(cell, inputs, sequence_length, initial_state, dtype, parallel_iterations, swap_memory, time_major, scope)
    625         swap_memory=swap_memory,
    626         sequence_length=sequence_length,
--> 627         dtype=dtype)
    628 
    629     # Outputs of _dynamic_rnn_loop are always shaped [time, batch, depth].

/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/rnn.py in _dynamic_rnn_loop(cell, inputs, initial_state, parallel_iterations, swap_memory, sequence_length, dtype)
    822       parallel_iterations=parallel_iterations,
    823       maximum_iterations=time_steps,
--> 824       swap_memory=swap_memory)
    825 
    826   # Unpack final output if not using output tuples.

/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/control_flow_ops.py in while_loop(cond, body, loop_vars, shape_invariants, parallel_iterations, back_prop, swap_memory, name, maximum_iterations)
   3222     if loop_context.outer_context is None:
   3223       ops.add_to_collection(ops.GraphKeys.WHILE_CONTEXT, loop_context)
-> 3224     result = loop_context.BuildLoop(cond, body, loop_vars, shape_invariants)
   3225     if maximum_iterations is not None:
   3226       return result[1]

/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/control_flow_ops.py in BuildLoop(self, pred, body, loop_vars, shape_invariants)
   2954       with ops.get_default_graph()._lock:  # pylint: disable=protected-access
   2955         original_body_result, exit_vars = self._BuildLoop(
-> 2956             pred, body, original_loop_vars, loop_vars, shape_invariants)
   2957     finally:
   2958       self.Exit()

/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/control_flow_ops.py in _BuildLoop(self, pred, body, original_loop_vars, loop_vars, shape_invariants)
   2891         flat_sequence=vars_for_body_with_tensor_arrays)
   2892     pre_summaries = ops.get_collection(ops.GraphKeys._SUMMARY_COLLECTION)  # pylint: disable=protected-access
-> 2893     body_result = body(*packed_vars_for_body)
   2894     post_summaries = ops.get_collection(ops.GraphKeys._SUMMARY_COLLECTION)  # pylint: disable=protected-access
   2895     if not nest.is_sequence(body_result):

/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/control_flow_ops.py in <lambda>(i, lv)
   3192         cond = lambda i, lv: (  # pylint: disable=g-long-lambda
   3193             math_ops.logical_and(i < maximum_iterations, orig_cond(*lv)))
-> 3194         body = lambda i, lv: (i + 1, orig_body(*lv))
   3195 
   3196     if context.executing_eagerly():

/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/rnn.py in _time_step(time, output_ta_t, state)
    791           call_cell=call_cell,
    792           state_size=state_size,
--> 793           skip_conditionals=True)
    794     else:
    795       (output, new_state) = call_cell()

/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/rnn.py in _rnn_step(time, sequence_length, min_sequence_length, max_sequence_length, zero_output, state, call_cell, state_size, skip_conditionals)
    246     # steps.  This is faster when max_seq_len is equal to the number of unrolls
    247     # (which is typical for dynamic_rnn).
--> 248     new_output, new_state = call_cell()
    249     nest.assert_same_structure(state, new_state)
    250     new_state = nest.flatten(new_state)

/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/rnn.py in <lambda>()
    779 
    780     input_t = nest.pack_sequence_as(structure=inputs, flat_sequence=input_t)
--> 781     call_cell = lambda: cell(input_t, state)
    782 
    783     if sequence_length is not None:

/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/rnn_cell_impl.py in __call__(self, inputs, state, scope, *args, **kwargs)
    337     # method.  See the class docstring for more details.
    338     return base_layer.Layer.__call__(self, inputs, state, scope=scope,
--> 339                                      *args, **kwargs)
    340 
    341 

/usr/local/lib/python3.6/dist-packages/tensorflow/python/layers/base.py in __call__(self, inputs, *args, **kwargs)
    697           if all(hasattr(x, 'get_shape') for x in input_list):
    698             input_shapes = nest.map_structure(lambda x: x.get_shape(), inputs)
--> 699           self.build(input_shapes)
    700         try:
    701           # Note: not all sub-classes of Layer call Layer.__init__ (especially

/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/rnn_cell_impl.py in build(self, inputs_shape)
    765         shape=[input_depth + h_depth, 4 * self._num_units],
    766         initializer=self._initializer,
--> 767         partitioner=maybe_partitioner)
    768     self._bias = self.add_variable(
    769         _BIAS_VARIABLE_NAME,

/usr/local/lib/python3.6/dist-packages/tensorflow/python/layers/base.py in add_variable(self, name, shape, dtype, initializer, regularizer, trainable, constraint, partitioner)
    544             constraint=constraint,
    545             trainable=trainable and self.trainable,
--> 546             partitioner=partitioner)
    547 
    548         if init_graph is not None:  # pylint: disable=protected-access

/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/checkpointable.py in _add_variable_with_custom_getter(self, name, shape, dtype, initializer, getter, overwrite, **kwargs_for_getter)
    434     new_variable = getter(
    435         name=name, shape=shape, dtype=dtype, initializer=initializer,
--> 436         **kwargs_for_getter)
    437 
    438     # If we set an initializer and the variable processed it, tracking will not

/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/variable_scope.py in get_variable(name, shape, dtype, initializer, regularizer, trainable, collections, caching_device, partitioner, validate_shape, use_resource, custom_getter, constraint)
   1315       partitioner=partitioner, validate_shape=validate_shape,
   1316       use_resource=use_resource, custom_getter=custom_getter,
-> 1317       constraint=constraint)
   1318 get_variable_or_local_docstring = (
   1319     """%s

/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/variable_scope.py in get_variable(self, var_store, name, shape, dtype, initializer, regularizer, reuse, trainable, collections, caching_device, partitioner, validate_shape, use_resource, custom_getter, constraint)
   1077           partitioner=partitioner, validate_shape=validate_shape,
   1078           use_resource=use_resource, custom_getter=custom_getter,
-> 1079           constraint=constraint)
   1080 
   1081   def _get_partitioned_variable(self,

/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/variable_scope.py in get_variable(self, name, shape, dtype, initializer, regularizer, reuse, trainable, collections, caching_device, partitioner, validate_shape, use_resource, custom_getter, constraint)
    423           caching_device=caching_device, partitioner=partitioner,
    424           validate_shape=validate_shape, use_resource=use_resource,
--> 425           constraint=constraint)
    426 
    427   def _get_partitioned_variable(

/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/variable_scope.py in _true_getter(name, shape, dtype, initializer, regularizer, reuse, trainable, collections, caching_device, partitioner, validate_shape, use_resource, constraint)
    392           trainable=trainable, collections=collections,
    393           caching_device=caching_device, validate_shape=validate_shape,
--> 394           use_resource=use_resource, constraint=constraint)
    395 
    396     if custom_getter is not None:

/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/variable_scope.py in _get_single_variable(self, name, shape, dtype, initializer, regularizer, partition_info, reuse, trainable, collections, caching_device, validate_shape, use_resource, constraint)
    784         validate_shape=validate_shape,
    785         constraint=constraint,
--> 786         use_resource=use_resource)
    787     if not context.executing_eagerly() or self._store_eager_variables:
    788       # In eager mode we do not want to keep default references to Variable

/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/variable_scope.py in variable(initial_value, trainable, collections, validate_shape, caching_device, name, dtype, constraint, use_resource)
   2218                          name=name, dtype=dtype,
   2219                          constraint=constraint,
-> 2220                          use_resource=use_resource)
   2221 
   2222 

/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/variable_scope.py in <lambda>(**kwargs)
   2208              constraint=None,
   2209              use_resource=None):
-> 2210   previous_getter = lambda **kwargs: default_variable_creator(None, **kwargs)
   2211   for getter in ops.get_default_graph()._variable_creator_stack:  # pylint: disable=protected-access
   2212     previous_getter = _make_getter(getter, previous_getter)

/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/variable_scope.py in default_variable_creator(next_creator, **kwargs)
   2191         collections=collections, validate_shape=validate_shape,
   2192         caching_device=caching_device, name=name, dtype=dtype,
-> 2193         constraint=constraint)
   2194 
   2195 

/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/variables.py in __init__(self, initial_value, trainable, collections, validate_shape, caching_device, name, variable_def, dtype, expected_shape, import_scope, constraint)
    233           dtype=dtype,
    234           expected_shape=expected_shape,
--> 235           constraint=constraint)
    236 
    237   def __repr__(self):

/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/variables.py in _init_from_args(self, initial_value, trainable, collections, validate_shape, caching_device, name, dtype, expected_shape, constraint)
    341             with ops.name_scope("Initializer"), ops.device(None):
    342               self._initial_value = ops.convert_to_tensor(
--> 343                   initial_value(), name="initial_value", dtype=dtype)
    344               shape = (self._initial_value.get_shape()
    345                        if validate_shape else tensor_shape.unknown_shape())

/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/variable_scope.py in <lambda>()
    768           initializer = initializer(dtype=dtype)
    769         init_val = lambda: initializer(  # pylint: disable=g-long-lambda
--> 770             shape.as_list(), dtype=dtype, partition_info=partition_info)
    771         variable_dtype = dtype.base_dtype
    772 

/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/init_ops.py in __call__(self, shape, dtype, partition_info, verify_shape)
    215       verify_shape = self._verify_shape
    216     return constant_op.constant(
--> 217         self.value, dtype=dtype, shape=shape, verify_shape=verify_shape)
    218 
    219   def get_config(self):

/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/constant_op.py in constant(value, dtype, shape, name, verify_shape)
    212   tensor_value.tensor.CopyFrom(
    213       tensor_util.make_tensor_proto(
--> 214           value, dtype=dtype, shape=shape, verify_shape=verify_shape))
    215   dtype_value = attr_value_pb2.AttrValue(type=tensor_value.tensor.dtype)
    216   const_tensor = g.create_op(

/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/tensor_util.py in make_tensor_proto(values, dtype, shape, verify_shape)
    430       nparray = np.empty(shape, dtype=np_dt)
    431     else:
--> 432       _AssertCompatible(values, dtype)
    433       nparray = np.array(values, dtype=np_dt)
    434       # check to them.

/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/tensor_util.py in _AssertCompatible(values, dtype)
    341     else:
    342       raise TypeError("Expected %s, got %s of type '%s' instead." %
--> 343                       (dtype.name, repr(mismatch), type(mismatch).__name__))
    344 
    345 

TypeError: Expected float32, got array([[ 1.04484751e+00,  4.59392878e-02,  8.02706034e-01,
        -1.11174105e+00,  8.89477561e-01, -1.20486729e+00,
         8.86266342e-01, -1.64510319e+00, -9.89266584e-01,
         1.31369015e+00,  4.88107334e-01,  1.49676477e-01,
        -6.81036506e-01, -9.64134982e-02, -1.39690939e+00,
         7.25600555e-02, -9.32924292e-02, -7.95291205e-01,
         2.18235671e-01,  1.01727717e+00,  9.90535181e-01,
        -4.35980568e-01,  7.94711686e-01, -3.13013630e-02,
        -7.20243003e-01, -1.37384000e+00, -9.62151398e-01,
         1.07646743e+00,  4.69513293e-01, -4.47742163e-02,
        -4.95195536e-01,  6.76953787e-01,  2.39035230e-01,
        -1.11104812e-01,  2.05507744e+00,  9.33967217e-01,
        -8.96051458e-01, -8.77908566e-02,  1.43848201e+00,
        -1.04624360e+00],
       [-3.41335190e-01,  1.40035909e+00, -1.60449447e-01,
        -9.41774525e-01,  1.81853256e+00, -2.20882493e-01,
         3.01935183e+00, -6.22724692e-01,  6.57625596e-01,
         3.85760589e-01,  1.25143595e+00,  3.95787835e-01,
        -1.15711379e-01,  1.04277452e+00,  1.18388115e-01,
        -2.67029800e+00,  4.53791661e-01,  1.21855412e+00,
         1.35663694e+00,  1.11392313e+00, -6.14336793e-01,
         2.90739971e-01,  1.37860208e+00,  2.52123588e+00,
        -8.47994930e-01, -1.57757604e-01, -3.22334965e-01,
        -5.11127934e-01,  1.17326724e+00, -1.33463413e-01,
         1.53402616e+00,  9.27541940e-01, -1.65259834e+00,
         1.52193955e+00, -7.02834497e-01,  1.30055130e+00,
        -1.27054858e+00,  1.93102289e+00,  4.90642813e-01,
         1.05364636e+00],
       [-2.82434425e-01,  4.84068350e-01, -1.54210849e+00,
         2.17935455e+00, -1.33159023e+00,  9.24332614e-01,
        -5.04315970e-01,  9.85161964e-01,  8.72890896e-01,
         9.33685162e-01,  2.29173759e-01,  1.80474211e+00,
         7.72485270e-01,  1.11224300e-01, -7.35284649e-01,
         1.22797144e-01,  2.49131972e-02, -8.82123778e-01,
         1.05901313e+00, -3.91695444e-01,  1.52364293e+00,
        -2.02547241e+00, -1.11905764e+00, -1.39702563e-01,
         6.00853245e-01,  1.06457879e+00,  7.23094038e-01,
         2.30281455e-01,  2.85937688e-02,  1.88589155e-02,
         6.45507430e-01, -5.51370987e-02, -1.68287628e+00,
        -3.59386792e-01,  2.64980652e-01, -4.73594067e-01,
        -1.16968518e+00,  6.28055865e-01,  2.84448999e+00,
        -8.13157852e-01],
       [-1.31717291e-01,  1.02786130e+00,  1.53418718e-01,
        -1.97088279e-01,  1.25098576e+00, -3.64066728e-01,
        -1.31257463e-01,  1.64076530e+00, -2.15908745e+00,
        -6.22189979e-01, -2.53163951e-02,  1.44229587e+00,
         1.42744437e+00,  1.17886987e+00, -1.37219218e+00,
         1.95677402e+00,  1.25885663e-01, -1.74788095e-01,
         1.49759607e+00,  1.69086673e+00,  1.70750645e+00,
         8.23124033e-03, -6.57806464e-01, -6.86276358e-01,
         2.76553853e-01, -5.89633972e-01,  4.83433320e-01,
        -4.78963168e-01,  1.57649031e+00, -8.97853620e-01,
         1.12044567e-01, -6.14123732e-01, -2.61661823e-01,
         1.08654068e+00, -2.13519684e+00, -2.20165083e+00,
        -1.79124609e+00,  1.66096352e+00,  1.01991370e+00,
        -6.31529272e-01],
       [-9.41644716e-01, -8.22052119e-02, -7.82717117e-01,
         4.66941465e-01, -3.41506828e-01,  2.85859511e-01,
        -5.39347861e-01,  4.83069925e-01, -1.96077011e+00,
        -1.79893071e+00,  4.02349515e-01,  2.19665512e-01,
         4.81469059e-01, -9.67396064e-01,  1.28371488e+00,
         1.74737441e-01, -1.42200749e+00, -1.02551183e+00,
         9.19474529e-01,  1.10227219e+00,  2.39780104e-01,
         1.54564488e+00,  5.48480031e-01,  2.53774766e-01,
        -1.05690541e+00,  2.04109323e+00, -8.91820616e-01,
        -9.67841805e-01,  6.84840673e-02, -2.64095272e+00,
        -9.63133723e-01,  1.27685637e+00,  6.88337275e-01,
         2.05600684e+00, -1.62778234e+00, -3.23933044e-01,
        -3.16615539e-01, -6.67369617e-01, -1.15297191e+00,
        -5.91319319e-01],
       [ 1.91052422e+00,  6.33272998e-01,  8.26497424e-01,
         6.03023598e-01,  3.92400071e-01,  9.29020785e-01,
        -6.88585491e-01,  9.77940308e-01, -1.26848693e+00,
         9.94840201e-02,  7.52848243e-01, -3.04239973e-01,
         3.67167359e-01,  5.69559156e-01, -6.36591114e-01,
         1.11083130e+00, -8.39891783e-01,  4.10057372e-01,
        -1.38307188e-01,  3.90518293e-01, -5.50275734e-01,
        -8.79075363e-01, -1.66958109e-01,  6.56225679e-01,
         1.95612624e+00, -4.45663548e-01, -1.09293024e-01,
        -2.01618327e+00,  4.58819223e-01,  9.22194083e-01,
         9.95847584e-01,  5.23072609e-02,  1.24794740e+00,
        -4.53764894e-02,  2.95947625e-01, -7.41021448e-01,
         2.50512089e+00,  9.61431201e-01,  1.69506349e+00,
         6.95733555e-01],
       [ 1.16595131e+00, -9.16556527e-01,  1.58695646e+00,
         1.53449732e-01,  1.17051377e-01, -4.14580879e-01,
        -5.97632083e-01, -9.09788623e-02,  2.06036713e-01,
        -1.68144113e+00, -1.44447690e+00,  6.33471999e-01,
         1.67047115e+00,  1.32731338e+00, -1.04672470e+00,
         4.54657832e-01, -2.23668935e-01,  6.40420094e-01,
        -2.76215451e-01,  1.29460409e+00, -1.38940318e-01,
        -1.04813960e+00, -1.47631494e+00,  4.58803440e-01,
         5.98103656e-01, -6.04906161e-01, -5.70246924e-02,
         1.42080757e+00, -1.97360377e+00, -7.95265695e-01,
         2.94820707e-01, -4.83390366e-01,  4.50911220e-01,
         8.74186348e-01, -5.99966992e-01, -1.21949591e-01,
        -2.52309447e-01,  1.53064407e+00,  3.72279673e-01,
         1.07315179e+00],
       [ 8.86889539e-01,  1.16549545e-01,  1.38816289e+00,
         1.01371089e+00, -1.44051110e+00, -3.53644010e-01,
        -3.65782677e-01,  6.13860886e-02, -3.14833634e-01,
         2.59271600e+00,  8.16096390e-01,  1.50172499e-01,
         5.30068573e-01, -7.30386914e-01, -2.03084764e-01,
        -6.74878994e-01,  9.66930750e-02,  7.21899634e-01,
        -1.99889298e-01,  1.64892187e-02, -1.19705017e+00,
        -1.59441455e+00,  6.20422424e-01, -2.18686254e-01,
         1.12343324e+00,  1.86378524e+00, -1.83527953e-01,
        -1.00652180e+00, -1.65150954e-01,  4.72737655e-02,
         4.04227537e-01,  7.75649967e-01, -1.67503021e+00,
         1.58444824e+00, -5.54640787e-01, -9.06882661e-01,
        -8.85061481e-01, -2.57646814e-01, -1.58392420e-01,
        -8.72515024e-01],
       [ 2.30347997e-01,  2.93106723e+00,  2.32079761e+00,
         1.05747984e-02,  6.43344453e-01,  1.48450845e+00,
        -1.32288375e+00, -3.35875203e-02, -1.53430836e-01,
         1.13107152e+00,  2.71825618e-01, -1.70896982e+00,
         6.73988768e-01, -1.52623124e+00,  8.51444615e-01,
         9.58495328e-01,  1.13117333e+00,  1.57066734e-01,
        -2.49850210e-01, -3.57635309e-01,  6.84622356e-01,
         2.02666474e-01, -7.12002046e-01,  1.24946477e-02,
         5.75374743e-01,  1.93356031e-01, -1.29900584e+00,
         5.04674883e-02,  1.22158010e+00,  1.63139677e+00,
        -2.49405615e-01,  1.82925921e+00,  3.54699037e-01,
         9.97620566e-01,  9.85580452e-02,  1.11274364e-01,
        -6.00244704e-01, -1.95023124e-01,  2.00273727e-01,
         1.83794424e+00],
       [ 7.09088942e-01, -1.04879043e+00, -5.74103670e-01,
         7.43992315e-01,  1.52200161e+00, -2.03207326e+00,
         2.11875292e-01,  1.04272441e+00, -1.26958291e+00,
         2.70366571e-01, -2.19008125e-01,  1.40483006e+00,
        -2.09482711e-01, -9.20875207e-01,  1.72865711e+00,
        -2.64627344e-01,  3.47781018e-01,  4.81586537e-01,
         1.07322305e+00, -8.17717513e-01,  1.28391605e+00,
         1.97842517e-01,  1.72612806e+00,  2.13807753e-01,
         1.03357557e+00,  5.84119555e-01, -8.61174988e-01,
        -1.17678694e+00,  1.92928507e+00,  5.60831434e-01,
         3.31615685e-01,  6.15759349e-02, -9.18765403e-02,
        -1.25591199e+00, -1.69617993e+00, -1.04056449e-03,
        -1.02922137e-01, -6.70639273e-01,  1.16609151e-01,
         1.10320101e+00],
       [ 3.14600442e-01, -4.65363105e-01,  1.67887551e+00,
        -6.92450808e-01,  3.14357667e-01,  1.32540623e-01,
         9.15669217e-01, -1.39204004e+00,  7.20252339e-01,
         5.94095417e-01, -8.18707441e-02,  5.91751351e-01,
        -6.68691321e-01,  4.96172554e-01,  5.29582332e-01,
        -1.55275307e-01,  2.46515467e-02,  6.03194472e-01,
         1.31759695e+00,  5.45525211e-01, -2.30398220e-02,
         8.12616540e-01, -2.61076466e-01,  1.66934365e+00,
        -8.31025772e-01, -2.00446090e-01,  2.91231454e-01,
         7.98223470e-01, -9.60227710e-01,  1.90107485e+00,
        -7.44250114e-01, -7.20353857e-01,  1.32092989e-01,
         8.44143593e-01,  5.01753704e-01, -2.05186337e-02,
         1.13485011e+00, -1.06831952e-01,  2.44283342e-01,
        -2.09994058e+00],
       [-6.29958586e-01,  5.63142982e-01, -3.90122789e-01,
         1.63745415e+00,  6.94110430e-01,  8.22926404e-02,
         1.95863036e-01, -1.38925172e-01,  2.25575648e-01,
         8.12663637e-01,  2.17542039e-01, -4.50958688e-01,
        -1.01270050e+00,  3.51468797e-01, -1.67982586e+00,
         1.07461121e+00,  6.99860539e-01,  4.94039591e-01,
        -5.90147661e-01, -1.83109452e+00,  1.03962324e+00,
         1.15843905e+00, -3.49911595e-01,  7.62128043e-01,
        -1.67721454e+00,  3.76573218e-01, -7.48380931e-01,
        -1.00878241e+00,  1.25593116e+00,  1.18679312e+00,
        -1.05711288e+00, -4.00083667e-01, -1.10232880e+00,
         1.21308371e+00, -4.47723244e-01, -2.68600107e-01,
         1.26868008e+00,  8.23863001e-01,  5.47930794e-01,
         2.77146607e-01],
       [ 8.58208487e-02,  1.56905645e+00,  1.82461216e+00,
        -1.95056238e+00,  8.84093358e-01, -2.30546309e-01,
         1.68715760e+00,  1.51402049e+00,  1.97083952e+00,
         3.47050464e-01,  2.45418091e+00, -1.28676786e+00,
        -3.13972072e-02, -9.15640304e-02, -6.08760602e-01,
         6.27315932e-01,  2.99423764e-01,  1.47387084e+00,
        -2.22367289e-01,  1.36963199e+00, -1.03270696e+00,
         5.07323436e-01,  1.03998597e+00,  7.48829007e-01,
         5.56559176e-01,  8.65196651e-01, -9.69346627e-01,
        -3.61670544e-02,  9.58567659e-01, -3.05810054e-01,
         1.57696086e+00,  6.16235833e-01, -1.05029472e+00,
         4.44189207e-01, -2.39608656e+00,  5.52516728e-01,
         1.41880306e+00,  8.11277537e-01,  4.57157626e-01,
        -3.63861533e-01],
       [-5.50649441e-01,  6.17569991e-01, -6.07970309e-01,
         4.38174300e-01, -1.35517086e+00,  2.25004668e-02,
        -3.37577140e-02,  1.06195204e-01,  1.28345880e+00,
        -3.46079223e-01, -1.53264926e-01,  1.22802991e+00,
         1.22813763e-01,  2.24233889e+00, -5.45865371e-01,
        -6.42548620e-01, -5.81109641e-01, -9.70743156e-01,
        -1.80179925e+00, -1.11872377e+00, -2.22970191e+00,
         4.94857288e-01, -5.86297124e-01, -6.56848913e-01,
        -1.17092937e-03, -7.39394009e-01,  1.19986436e+00,
         3.96717450e-01, -1.24115664e-01,  1.00324288e+00,
        -1.14458800e-01, -2.25008521e+00,  5.45973540e-01,
         2.37025750e-01, -1.14356885e+00, -4.88471919e-01,
        -1.13206828e+00, -1.62136190e+00,  1.23749918e-01,
         3.08363831e-01],
       [-2.36785516e+00,  1.93758109e-01,  9.52158319e-01,
         1.74236299e-01, -1.37006190e+00, -3.20627648e-01,
         2.16886312e+00, -8.07024449e-01, -9.12120118e-01,
        -2.45296765e+00,  1.09160450e+00, -1.00823007e+00,
        -1.08279055e-01, -3.37003362e-01,  8.89784314e-01,
         4.28913333e-01, -1.31532876e+00,  1.99979263e-01,
        -2.95699114e-01, -1.07325068e+00, -7.65415033e-01,
        -7.57991272e-01,  1.58699077e+00, -6.27470343e-01,
         4.39592393e-01,  1.19306894e+00, -1.41762289e+00,
        -1.92094209e-01,  4.98275997e-01,  4.75333804e-01,
         2.42416125e-01,  3.97092492e-02,  2.18313764e-01,
         9.20630155e-01,  1.32786770e-01,  1.07811778e+00,
        -1.56297503e-01,  1.84818124e-01,  6.83802272e-01,
        -1.76218224e+00]]) of type 'ndarray' instead.

Can anybody tell why this error is coming, the size of numpy arrays are correct.
