### ISSUE TITLE
quantized for SplitV

### ISSUE THREAD

**Issue by sunzhe09** [tensorflow/tensorflow#31155]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):Ubuntu 16.04
- TensorFlow installed from (source or binary):pip install tensorflow==1.14
- TensorFlow version (or github SHA if from source):1.14.0

**Provide the text output from tflite_convert**

```
tflite_convert  --output_file=quantized.tflite  --graph_def_file=mixnet.pb   --inference_type=QUANTIZED_UINT8     --input_arrays=truediv  --output_arrays=Softmax  --mean_values=128   --std_dev_values=127  --default_ranges_min=0  --default_ranges_max=6
```

Also, please include a link to a GraphDef or the model if possible.

**Any other info / logs**
W tensorflow/lite/toco/graph_transformations/quantize.cc:132] Constant array mixnet-s/mixnet_model/blocks_0/conv2d/kernel lacks MinMax information. To make up for that, we will now compute the MinMax from actual array elements. That will result in quantization parameters that probably do not match whichever arithmetic was used during training, and thus will probably be a cause of poor inference accuracy.
2019-07-30 01:54:53.127377: F ./tensorflow/lite/toco/toco_tooling.h:38] Check failed: s.ok() Unimplemented: this graph contains an operator of type SplitV for which the quantized form is not yet implemented. Sorry, and patches welcome (that's a relatively fun patch to write, mostly providing the actual quantized arithmetic code for this op).
Fatal Python error: Aborted

Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.
