### ISSUE TITLE
Getting an 0.8 .whl when installing from source from master branch

### ISSUE THREAD

**Issue by JohnAllen** [tensorflow/tensorflow#3116]
I'm getting an `0.8` `.whl` when installing from source right now (current master [6-27]; Ubuntu 15.1; Python3.5). Am trying it from scratch again.

- Checked the repo: `README.md`: `# Release 0.9.0`
- cudnn 7.5, is that correct?
- bazel version: `0.2.3`

Output from `ls -l /usr/local/cuda/lib64/cudn*`:

`
 Aug 15  2015 /usr/local/cuda/lib64/libcudadevrt.a
16 Aug 15  2015 /usr/local/cuda/lib64/libcudart.so -> libcudart.so.7.5
19 Aug 15  2015 /usr/local/cuda/lib64/libcudart.so.7.5 -> libcudart.so.7.5.18
383336 Aug 15  2015 /usr/local/cuda/lib64/libcudart.so.7.5.18
720192 Aug 15  2015 /usr/local/cuda/lib64/libcudart_static.a
61453024 Jun 25 17:23 /usr/local/cuda/lib64/libcudnn.so
61453024 Jun 25 17:23 /usr/local/cuda/lib64/libcudnn.so.4
61453024 Jun 25 17:23 /usr/local/cuda/lib64/libcudnn.so.4.0.7
62025862 Jun 25 17:23 /usr/local/cuda/lib64/libcudnn_static.a
`

**And my primary question: what does the following mean:**

`Cudnn libraries, use '6.5' for R2, '7.0' for R3, and '4.0.4' for R4-RC.`

That's about the only thing I can think of that could be causing me problems.

**Comment by JohnAllen** [comment]
Need 0.9 for the `conv3d` support

**Comment by vrv** [comment]
I believe it's named 0.8 but it should have conv3d.  We haven't merged the version number changes from r0.9 back into master.  @caisq @martinwicke

**Comment by JohnAllen** [comment]
Awesome, will check.  Would not have guessed that at all.

**Comment by JohnAllen** [comment]
Closing.  Hope this helps others.  That threw me for a loop.

**Comment by vrv** [comment]
I think we should probably keep this open until we fix the issue

**Comment by martinwicke** [comment]
I merged 0.9 into master earlier today.
