### ISSUE TITLE
Some of the operators in the model are not supported by the standard TensorFlow Lite runtime and are not recognized by TensorFlow. If you have a custom implementation for them you can disable this error with --allow_custom_ops, or by setting allow_custom_ops=True when calling tf.lite.TFLiteConverter(). Here is a list of builtin operators you are using: ADD, CAST, CONCATENATION, CONV_2D, DIV, EXP, FILL, GATHER, GREATER_EQUAL, LEAKY_RELU, LOGISTIC, MAX_POOL_2D, MUL, PACK, REDUCE_MIN, REDUCE_PROD, RESHAPE, RESIZE_NEAREST_NEIGHBOR, SHAPE, SQUEEZE, STRIDED_SLICE, SUB. Here is a list of operators for which you will need custom implementations: NonMaxSuppressionV3, Round, Where

### ISSUE THREAD

**Issue by tranvangaohd1994** [tensorflow/tensorflow#31180]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- TensorFlow installed from (source or binary):
- TensorFlow version (or github SHA if from source):

**Provide the text output from tflite_convert**

```
# Copy and paste here
```

Also, please include a link to a GraphDef or the model if possible.

**Any other info / logs**

Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by gadagashwini** [comment]
@tranvangaohd1994 Provide the exact sequence of commands / steps that you executed before running into the problem and also provide the Tensorflow version. Thanks!

**Comment by gadagashwini** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Comment by tranvangaohd1994** [comment]
Hi @gadagashwini. I do object detection using yolo-tiny. I want to post-processing into model, for example non_max_suppression. So I using Lambda layer like this 👍 
`
model_Cal = Lambda(yolo_post_processing, output_shape=(None,6), name='yolo_post_processing',
            arguments={'anchors': self.anchors, 'num_classes': 80})(self.yolo_model.output) 
self.yolo_model = Model(self.yolo_model.input, model_Cal)
`

In function yolo_post_processing(), I do post_processing to choose best boxes. In this function I use **tf.image.non_max_suppression** or **tf.boolean_mask**
`
class_boxes = tf.boolean_mask(boxes, mask[:, c])

nms_index = tf.image.non_max_suppression(
            class_boxes, class_box_scores, max_boxes_tensor, iou_threshold=iou_threshold)
`
I build model and run it on PC, It's OK. It's work very well. 
But when I convert it to model TFLite to use in Android by this code : 
`
from tensorflow.contrib import lite
    converter = lite.TFLiteConverter.from_keras_model_file('model_data/md_custom_op.h5', input_shapes = {'input_1':[1,416,416,3]})
    tfmodel = converter.convert()
`
I got that error **Here is a list of operators for which you will need custom implementations: NonMaxSuppressionV3, Round, Where**.

I understand that I need to custom operators what don't support by TFLite. But I can't search anyone do this work in python code.  

If they are,please sent me a example about **custom operators**

**Comment by extra159** [comment]
> Hi @gadagashwini. I do object detection using yolo-tiny. I want to post-processing into model, for example non_max_suppression. So I using Lambda layer like this :
> 
> `
> model_Cal = Lambda(yolo_post_processing, output_shape=(None,6), name='yolo_post_processing',
> arguments={'anchors': self.anchors, 'num_classes': 80})(self.yolo_model.output)
> 
> self.yolo_model = Model(self.yolo_model.input, model_Cal)
> `
> 
> In function **yolo_post_processing**(), I do post_processing to choose best boxes. In this function I use **tf.image.non_max_suppression** or **tf.boolean_mask**
> 
> `
> class_boxes = tf.boolean_mask(boxes, mask[:, c])
> 
> nms_index = tf.image.non_max_suppression(
> class_boxes, class_box_scores, max_boxes_tensor, iou_threshold=iou_threshold)
> `
> 
> I build model and run it on PC, It's OK. It's work very well.
> But when I convert it to model TFLite to use in Android by this code :
> 
> `
> from tensorflow.contrib import lite
> 
> converter = lite.TFLiteConverter.from_keras_model_file('model_data/md_custom_op.h5', input_shapes = {'input_1':[1,416,416,3]})
> 
> tfmodel = converter.convert()
> `
> I got that error **Here is a list of operators for which you will need custom implementations: NonMaxSuppressionV3, Round, Where**.
> 
> I understand that I need to custom operators what don't support by TFLite. But I can't search anyone do this work in python code.
> 
> If they are,please sent me a example about **custom operators**

hi,

you can add "converter.allow_custom_ops=True" before "tflite_model = converter.convert()". This is working for me.

**Comment by gadagashwini** [comment]
@tranvangaohd1994, Please let us know if the @extra159's workaround helps this issue. Thanks!

**Comment by tranvangaohd1994** [comment]
Hi extra159, thanks your attention.
If I add "converter.allow_custom_ops=True", it would convert successfully. But Have you try to run model_tflite after convert?? It's going to error not found operator tf.Where, etc . You should try!!
I had to divide into 2 model, one can convert to tflife (output is 3 feature map of CNN-yolo) , one is model_pb to run function tf.image.non_max_suppression() to choose best boxes. That is my solution. Thank you
