### ISSUE TITLE
Add FP16 precision support to TFLite external C API

### ISSUE THREAD

**Issue by stakemura** [tensorflow/tensorflow#31185]
**System information**
- TensorFlow version (you are using):master repository
- Are you willing to contribute it (Yes/No):Yes

**Describe the feature and the current behavior/state.**
Add FP16 precision support to TFLite external C API.

**Will this change the current api? How?**
This change has no influence.

**Who will benefit with this feature?**
TFLite extenal C API users

**Any Other info.**
Here is [my patch](https://github.com/stakemura/tensorflow/commit/d36a995ccb053145162bb993d351086b3eaa10c0)

**Comment by stakemura** [comment]
I'm looking for the function equivalent to [TFLite model benchmark allow_fp16 option](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/tools/benchmark/benchmark_tflite_model.cc#L226).
I think that some additional code is required for supporting GPU delegations.
If needed, I want to submit PR including the additional code.

**Comment by jdduke** [comment]
The relaxed precision is for internal calculations, not for any external inputs, and we don't have any immediate plans for exposing fp16 inputs externally.
