### ISSUE TITLE
Add multi-class classification on tflite

### ISSUE THREAD

**Issue by Vanrap** [tensorflow/tensorflow#31193]
As of now, I believe tensorflowlite can only return predictions belonging to one class. But,it would be great if there was  away to add 2 or more labels in the models. For example, if I want to classify whether a given image is a vegetable or fruit, and also what type of vegetable or fruit, that would be multi label classification.

**System information**
- TensorFlow lite:
- Are you willing to contribute it (No):

**Describe the feature and the current behavior/state.**

**Will this change the current api? How?**
Problems requiring more than 1 label can be solved with higher accuracy and ease.

**Who will benefit with this feature?**
Users of TensorflowLite

**Comment by ravikyram** [comment]
@Vanrap 

Please, go through below links and see if it helps you.Thanks!

https://stackoverflow.com/questions/57282364/building-a-tflite-model-for-multi-class-classification

https://medium.com/towards-artificial-intelligence/testing-tensorflow-lite-image-classification-model-e9c0100d8de3

**Comment by ravikyram** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
