### ISSUE TITLE
Adding AVX2 and FMA makes tensorflow slower on my CPUs

### ISSUE THREAD

**Issue by el1995** [tensorflow/tensorflow#31199]
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): CentOS 7
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: no
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below): 1.14
- Python version: 3.6.8
- Bazel version (if compiling from source): 0.24.1
- GCC/Compiler version (if compiling from source): 4.8.5
- CUDA/cuDNN version: none 
- GPU model and memory: none

I have built several different tensorflow versions from source to compare the performance during inference. Two of my many versions are:
- prebuilt TF 1.14 C API libpackage (with AVX)
- self-built TF 1.14 CAPI libpackage  (with AVX,AVX2,FMA)

Strangely, I experience that the prebuilt version reaches better latency and throughput for every single comparison. I am a bit confused about that as adding additional instruction set architectures during the build should rather result in improved performance...? I am not sure where the difference might be. The self-built version is without XLA JIT.

My question: is there an obvious reason why this might occur? The hardware i use is:
Intel Xeon Gold 6130 GPU 2.10 GHz (on a cluster, starting with 24 cores up to 480 cores)

**Comment by gunan** [comment]
Not using XLA may be the reason making it slower. But I am not the expert on this topic.
@sanjoy any ideas?

**Comment by sanjoy** [comment]
I don't see an obvious reason.  Did you try using a profiler (like perf) to see if you spot a difference.

If you were using XLA in the prebuilt version but not in the self-built version, that could also explain the difference.

**Comment by el1995** [comment]
No I  do the timing with C++'s high resolution clock. Still it is obvious because for 250 subsequent inferences, the pre-built TF 1.14 is faster in 90% of the cases. Indeed I built the version with AVX2 and FMA without XLA. However according to our current second discussion about XLA activation for the C API (see: #29878 ) I must assume that I did not activate XLA because I do not set the TF_XLA_FLAGS. As far as I understand that is a mandatory requirement to activate XLA?

**Comment by sanjoy** [comment]
> As far as I understand that is a mandatory requirement to activate XLA?

No (there are other ways to enable XLA).  You can know for sure by setting `--v=1` and looking for logging messages from xla_compilation_cache.cc saying that we compiled a cluster.

But XLA is not on by default, so to enable it you or a library you're using will have to have done something explicit.

**Comment by el1995** [comment]
How can I set ```--v=1```?

**Comment by sanjoy** [comment]
I'm not totally sure how it works in open source, but I'd expect you can pass it as a command line arg.

**Comment by el1995** [comment]
Ok so my findings:
I did definitely not use XLA and I still constantly get the result that my self-build version with AVX2 and FMA is slower than the pre-built 1.14. Is there anything additional special about the pre-built versions?

**Comment by sanjoy** [comment]
Can you try pre-built vs. self-built with AVX?  That'll get rid of the build environment as a confounding factor.

**Comment by ravikyram** [comment]
@el1995 

Have a look on @sanjoy's suggestion and let us know if that helps to resolve the issue. Thanks!

**Comment by el1995** [comment]
Hi,

unfortunately I will not manage to rebuild further versions due to time constraints. However I meanwhile had some cases where the version with AVX2 and FMA was identically fast as the pre-built version. I guess that the reason for the varying performance is the continuously fluctuating load on the fileserver of our cluster. This may have caused the pre-built version to be faster.
