### ISSUE TITLE
Relax the requirements for saver checkpoints

### ISSUE THREAD

**Issue by alexatknit** [tensorflow/tensorflow#312]
I'm working on testing a few modifications to an existing network including attempting to use it as a teacher in a student/teacher network and swapping its optimizer but I get the following error:

```
Traceback (most recent call last):
  File "knit_net_train_tf.py", line 40, in <module>
    saver.restore(sesh, CHECKPOINT_FILE)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 869, in restore
    sess.run([self._restore_op_name], {self._filename_tensor_name: save_path})
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 401, in run
    results = self._do_run(target_list, unique_fetch_targets, feed_dict_string)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 477, in _do_run
    e.code)
tensorflow.python.framework.errors.NotFoundError: Tensor name "conv1/biases/Adagrad" not found in checkpoint files knitnet.0.ckpt
         [[Node: save/restore_slice_2 = RestoreSlice[dt=DT_FLOAT, preferred_shard=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/restore_slice_2/tensor_name, save/restore_slice_2/shape_and_slice)]]
```

It appears that the saver requires that every variable that exists in the current graph also be present in the checkpoint and that every variable that that exists in the checkpoint also be in the current graph. I can work around this by making major modifications to the way that my network is constructed but I would be nice to have a feature that says "don't error out if you don't find this variable, its ok". Alternatively it appears that I can specify which variables I want to restore, which could also solve the problem, but I have a lot of variable that I haven't explicitly tracked, many of which are created by the optimizer. It would make this feature a lot more useful if there were a function that did "return all variables that this op depends on", which I could call on the training variable or the prediction variable and only save those tensors.

**Comment by ppwwyyxx** [comment]
Agreed on this. Another example could be: I change the dimension (and name) of the last fully-connected layer of some imagenet model, and wanted to load a pre-trained one for some other classification task. An option to ignore the "tensor not found" error would be good. (probably with some warning, or return a list of variables successfully restored).

**Comment by mrry** [comment]
The tooling has improved in 0.8: you can call `tf.all_variables()` to get a list of all of the variables in your model, and use the [`inspect_checkpoint.py`](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/tools/inspect_checkpoint.py) tool to get the list of variables in a checkpoint file, so it should be easier to build the list of variables to restore.

I don't think we'd want to add a less-strict version of `restore()` that ignores missing values, although we'd consider contributions of a tool that integrates the `inspect_checkpoint.py` and `tf.all_variables()` code to make doing this easier.

**Comment by koonyook** [comment]
If so, how can I add a new variable and use them with previously saved variables?

**Comment by futurely** [comment]
When the checkpoint files are saved with a subset of GPUs, they can't be loaded if new GPUs are used. The error is `tensorflow.python.framework.errors.NotFoundError: Tensor name "tower_name_gpu_3/fc/Variable_1" not found in checkpoint files`. How to work around the strict restriction?

**Comment by sherrym** [comment]
@futurely, how do you want to work around this restriction? Do you want to restore all you have, and initialize the rest to what's in the checkpoint? If that's the case, what you can do is this:
1. Initialize all the variables.
2. Get all the variables in the checkpoint by using get_variable_to_shape_map() and restore those only.

See https://github.com/tensorflow/tensorflow/blob/8df836f2611c533c54d2bdaaf107c67afac8d6a5/tensorflow/python/training/saver_test.py#L1214

for usage example.

@koonyook, how do you want to use a new variable with previously saved variables?

**Comment by wangdelp** [comment]
@sherrym , Thanks for the useful information. 
I am adding some new variables to the model serialized on the disk. 
After I get the variables with get_variable_to_shape_map(model_path), how do I only restore those variables? Thank you.

**Comment by danielgordon10** [comment]
I think it's way more user-friendly to allow new names, new shapes, and removed variables (Caffe style). This code seems to get that job done. I call it after running the global init operation.

```python
def optimistic_restore(session, save_file):
    reader = tf.train.NewCheckpointReader(save_file)
    saved_shapes = reader.get_variable_to_shape_map()
    var_names = sorted([(var.name, var.name.split(':')[0]) for var in tf.global_variables()
            if var.name.split(':')[0] in saved_shapes])
    restore_vars = []
    with tf.variable_scope('', reuse=True):
        for var_name, saved_var_name in var_names:
            curr_var = tf.get_variable(saved_var_name)
            var_shape = curr_var.get_shape().as_list()
            if var_shape == saved_shapes[saved_var_name]:
                restore_vars.append(curr_var)
    saver = tf.train.Saver(restore_vars)
    saver.restore(session, save_file)
```

**Comment by PiotrDabkowski** [comment]
@mrry I really don't understand why would not you add an option to restore as much as possible without raising errors if some variable is not present in the checkpoint. It would really make life much easier for a large number of users.

For example, it would be possible to save everything using `Saver(tf.global_variables()) `, add some new variables and restore only global variables that were present in the checkpoint. 

I can implement this feature if you agree.

**Comment by RalphMao** [comment]
@dandelionmane Thanks for your codes. But I found sometimes it would go wrong due to not-found variables.(I met one with Adam/Wxxx). I made a small change to your codes and it works fine for me.

	def optimistic_restore(session, save_file):
		reader = tf.train.NewCheckpointReader(save_file)
		saved_shapes = reader.get_variable_to_shape_map()
		var_names = sorted([(var.name, var.name.split(':')[0]) for var in tf.global_variables()
				if var.name.split(':')[0] in saved_shapes])
		restore_vars = []
            name2var = dict(zip(map(lambda x:x.name.split(':')[0], tf.global_variables()), tf.global_variables()))
		with tf.variable_scope('', reuse=True):
			for var_name, saved_var_name in var_names:
				curr_var = name2var[saved_var_name]
				var_shape = curr_var.get_shape().as_list()
				if var_shape == saved_shapes[saved_var_name]:
					restore_vars.append(curr_var)
		saver = tf.train.Saver(restore_vars)
		saver.restore(session, save_file)

**Comment by yjliang123** [comment]
I have a same question. when I restore my LSTM model trained by tensorflow 0.11, the error message told me some variable can not found in checkpoint file, but when I use the  [inspect_checkpoint.py](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/tools/inspect_checkpoint.py), that variable is existed and have data, I have been confused long time. How can I fixed it?
`NotFoundError (see above for traceback): Tensor name "bias_fc_end" not found in checkpoint files /root/PycharmProjects/....../DataOutput1/Hyperparameter2/Hyperparameter_2_RepeatNum_1_Epoch_3.tfmodel
	 [[Node: save/restore_slice_9 = RestoreSlice[dt=DT_FLOAT, preferred_shard=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/restore_slice_9/tensor_name, save/restore_slice_9/shape_and_slice)]]
	 [[Node: save/restore_slice_9/_1 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/gpu:0", send_device="/job:localhost/replica:0/task:0/cpu:0", send_device_incarnation=1, tensor_name="edge_33_save/restore_slice_9", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/gpu:0"]()]]
`

**Comment by vitalyli** [comment]
If I'm not mistaken saver allow_empty=True achieves what optimistic_restore above does?

**Comment by vitalyli** [comment]
@dandelionmane thanks for your optimistic_restore I've tried it successfully. It really should be part of Saver itself. For my purposes I've modified it only slightly to make function return list of variables given checkpoint path, that way it's not concerned with session yet.

    def optimistic_restore_vars(checkpoint):
        ckpt = tf.train.get_checkpoint_state(os.path.dirname(checkpoint + '/checkpoint'))
        reader = tf.train.NewCheckpointReader(ckpt.model_checkpoint_path)
        saved_shapes = reader.get_variable_to_shape_map()
        var_names = sorted([(var.name, var.name.split(':')[0]) for var in tf.global_variables()
                            if var.name.split(':')[0] in saved_shapes])
        restore_vars = []
        name2var = dict(zip(map(lambda x:x.name.split(':')[0], tf.global_variables()), tf.global_variables()))
        with tf.variable_scope('', reuse=True):
            for var_name, saved_var_name in var_names:
                curr_var = name2var[saved_var_name]
                var_shape = curr_var.get_shape().as_list()
                if var_shape == saved_shapes[saved_var_name]:
                    restore_vars.append(curr_var)
        return restore_vars

    saver = tf.train.Saver(max_to_keep=20, var_list = optimistic_restore_vars(checkpoint) if checkpoint else None)

**Comment by urimerhav** [comment]
+1 on making optimstic_restore an optional behavior of `Saver.restore method`

**Comment by BoyuanJiang** [comment]
The following codes work for me:
```
init_assign_op, init_feed_dict = slim.assign_from_checkpoint(
            checkpoint_path, slim.get_variables_to_restore(), ignore_missing_vars=True)
sess.run(init_assign_op, feed_dict=init_feed_dict)
```
