### ISSUE TITLE
ERROR: Failed to prepare for TPU. generic::failed_precondition: Custom op already assigned to a different TPU.

### ISSUE THREAD

**Issue by DocDriven** [tensorflow/tensorflow#31201]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04 LTS
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: no
- TensorFlow installed from (source or binary): Docker image latest-gpu-py3
- TensorFlow version (use command below): 1.14.0
- Python version: 3.6
- Bazel version (if compiling from source): - 
- GCC/Compiler version (if compiling from source): - 
- CUDA/cuDNN version: 10.1
- GPU model and memory: RTX 2080 Ti

I'm trying to compile tflite models with the edgetpu_compiler for usage with the Coral TPU stick. I have two versions of the tflite file. For the first one, I do not want to use the TPU acceleration (to compare the performances). I invoked the TFLiteConverter with the following configuration:
```
converter = tf.compat.v1.lite.TFLiteConverter.from_keras_model_file(keras_file)
converter.inference_input_type = tf.float32
converter.inference_output_type = tf.float32
converter.optimizations = [tf.lite.Optimize.DEFAULT]
tflite_model = converter.convert()
open(<tflite_file_name>, 'wb').write(tflite_model)
```
For the TPU version, I chose the following options:
```
converter = tf.compat.v1.lite.TFLiteConverter.from_keras_model_file(keras_file)
converter.representative_dataset = representative_dataset_gen
converter.target_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
converter.inference_input_type = tf.uint8
converter.inference_output_type = tf.uint8
converter.optimizations = [tf.lite.Optimize.DEFAULT]
tflite_model = converter.convert()
open(<tflite_file_name>, 'wb').write(tflite_model)
```

To check the output of these, I used the visualize.py script. The second graph has quantize nodes in it. To my understanding, I have to convert the second tflite file with the edgetpu_compiler (the first one is expectedly NOT convertible, as it is not quantized). This seems to work, as the log file outputs:

```
Edge TPU Compiler version 2.0.258810407
Input: linearmodel_1.14.0_uint8.tflite
Output: linearmodel_1.14.0_uint8_edgetpu.tflite

Operator                       Count      Status

FULLY_CONNECTED                1          Mapped to Edge TPU
QUANTIZE                       2          Mapped to Edge TPU
```

However, if I use it with the C++ API, I run into an error when allocating tensors:

```
ERROR: Failed to prepare for TPU. generic::failed_precondition: Custom op already assigned to a different TPU.
ERROR: Node number 0 (edgetpu-custom-op) failed to prepare.
```

I have not found a solution to this problem. I can however, load the non-compiled tflite model, although I suspect this does not provide any time savings.

I have uploaded all tflite models, their html visualizations and the edgetpu log with verbosity 10 to a github repo of mine: https://github.com/DocDriven/experimental

Is this issue already known to you?

**Comment by lu-wang-g** [comment]
The conversion from tflite to edge_tpu seems right. Can you please give an example of how do you invoke the C++ API?

**Comment by DocDriven** [comment]
Sure, just note: 

When assigning a value to the input/output variable with
` interpreter->typed_tensor<uint8_t>(4)[0] = quant_input;`
`uint8_t quant_output = interpreter->typed_tensor<uint8_t>(5)[0];`

you have to change the input and output IDs to 0 and 1 respectively, if you want to use the tflite model generated by the compiler. Also, using `typed_input_tensor` and/or `typed_output_tensor` results in a Seg Fault.

```
#include <iostream>
#include "tensorflow/lite/interpreter.h"
#include "tensorflow/lite/kernels/register.h"
#include "tensorflow/lite/model.h"
#include "tensorflow/lite/tools/gen_op_registration.h"
#include "edgetpu.h"

int main(int argc, char** argv){

    // check for correct CLI input
    if (argc != 3) {
            std::cout << "Invalid number of arguments.\nUsage: " << argv[0] << " <tflite model> <input value>\n";
            exit(0);
    }

    // load model
    std::unique_ptr<tflite::FlatBufferModel> model = tflite::FlatBufferModel::BuildFromFile(argv[1]);

    if(!model){
        std::cout << "Failed to mmap model\n";
        exit(0);
    }   

    // create TPU context handle
    edgetpu::EdgeTpuContext* edgetpu_context = edgetpu::EdgeTpuManager::GetSingleton()->NewEdgeTpuContext().release();

    // Build the interpreter
    tflite::ops::builtin::BuiltinOpResolver resolver;
    resolver.AddCustom(edgetpu::kCustomOp, edgetpu::RegisterCustomOp());
    std::unique_ptr<tflite::Interpreter> interpreter;

    if (tflite::InterpreterBuilder(*model, resolver)(&interpreter) != kTfLiteOk){
            std::cout << "Failed to build interpreter\n";
            exit(0);
    }

    interpreter->SetExternalContext(kTfLiteEdgeTpuContext, edgetpu_context);
    interpreter->SetNumThreads(1);

    // Allocate memory
    if(interpreter->AllocateTensors() != kTfLiteOk){
            std::cout << "Failed to allocate tensors\n";
            exit(0);
    }

    // Get the input from the CL
    float real_input = strtof(argv[2], NULL);

    // Quantize the inputs
    const std::vector<int>& inputs = interpreter->inputs();
    TfLiteTensor* input_tensor = interpreter->tensor(inputs[0]);
    const TfLiteQuantizationParams& input_params = input_tensor->params;
    uint8_t quant_input = (real_input / input_params.scale) + input_params.zero_point;
    interpreter->typed_tensor<uint8_t>(4)[0] = quant_input;

    // Invoke the interpreter
    interpreter->Invoke();

    // Get the output from the model
    uint8_t quant_output = interpreter->typed_tensor<uint8_t>(5)[0];

    // Dequantize the outputs
    const std::vector<int>& outputs = interpreter->outputs();
    TfLiteTensor* output_tensor = interpreter->tensor(outputs[0]);
    const TfLiteQuantizationParams& output_params = output_tensor->params;
    float real_output = output_params.scale * (quant_output - output_params.zero_point);

    // Do something with the output
    std::cout << "Result: " << real_output << "\n";

    return 0;
}
```

The Makefile for compiling this looks like this (paths are specific to my system):

#Makefile for “tpu_demo” C++ application
#Created by SKU 19/07/29

```
PROG = ./output/tpu_demo
CC = g++
CPPFLAGS = -Wall -I/tensorflow -I./src
LDFLAGS = -L./src -ltensorflow-lite -ledgetpu_arm64 -ldl -lrt -pthread
OBJS = ./src/tpu_demo.o

$(PROG) : $(OBJS)
	$(CC) $(OBJS) $(LDFLAGS) -o $(PROG)
tpu_demo.o :
	$(CC) $(CPPFLAGS) -c ./src/tpu_demo.cpp
clean:
	rm -f core $(PROG) $(OBJS)
```

**Comment by DocDriven** [comment]
I realized that I get sporadically different errors when executing the binary. Most of the time it throws the error I reported in the original post, but sometimes I get the following:

```
ERROR: Failed to prepare for TPU. generic::failed_precondition: Missing raw model data.
ERROR: Node number 0 (edgetpu-custom-op) failed to prepare. 
```

I am literally executing the exact same binary over and over again, and get two different error messages. Maybe this helps to track down the bug?!

**Comment by DocDriven** [comment]
@lu-wang-g 
Can you confirm to me if the invocation of the C++ API is correct or not, please?

**Comment by lu-wang-g** [comment]
Hi Sebastian, I don't have quick answer about this issue. I've created an internal bug and assigned it to the Coral team. I'll keep you posted on any updates it may have.

**Comment by DocDriven** [comment]
@lu-wang-g 
Thanks for letting me know! I appreciate it!

**Comment by manoj7410** [comment]
@DocDriven Can you try to download the latest C/C++ libraries from https://coral.googlesource.com/edgetpu/+/refs/heads/release-diploria/libedgetpu/ and try with these libraries ?
Additionally, try to use/modify one of our examples from https://coral.googlesource.com/edgetpu-native/+/refs/heads/release-diploria/edgetpu/cpp/examples/ and see if your model runs with it.

**Comment by DocDriven** [comment]
@manoj7410 Thanks for the help, I was able to run the compiled model with the new libraries. For anyone interested, I replaced the libs on my system with the provided 
```
edgetpu.h
libedgetpu_arm64.so
direct/aarch64-linux_gnu/libedgetpu.so.1
```
(Last is just a symbolic link).
