### ISSUE TITLE
illegal instruction

### ISSUE THREAD

**Issue by faizulhz** [tensorflow/tensorflow#31200]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version:
- Python version:
- Installed using virtualenv? pip? conda?:
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Describe the problem**

**Provide the exact sequence of commands / steps that you executed before running into the problem**

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by faizulhz** [comment]
import tensorflow as tf causes illegal instruction. on docker

**Comment by anush-o** [comment]
@faizulhz ,
Can you please provide all the details mentioned in the standard template?Thanks!

**Comment by Leslie-Fang** [comment]
@faizulhz if you build tensorflow on latest platform with latest instruction such as AVX512. Then use this version on a older platform without AVX instruction . You may get this error.
Please refer to this link: https://github.com/tensorflow/tensorflow/issues/17411

**Comment by oanush** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
