### ISSUE TITLE
TFLite Invalid tensors 'MatMul' were found.

### ISSUE THREAD

**Issue by paulbauriegel** [tensorflow/tensorflow#31206]
TFLite does not convert a containing a MatMul node.

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): `No`
- OS Platform and Distribution: `Ubuntu 19.04 64bit`
- TensorFlow installed from (source or binary): `source`
- TensorFlow version (use command below): `v1.14.0-20-g456fbc0e49 1.14.1`
- Python version: `3.7.3`
- Bazel version (if compiling from source): `0.25.2`
- GCC/Compiler version (if compiling from source): `gcc 8.3.0`
- CUDA/cuDNN version: `None`
- GPU model and memory: `not compiled with CUDA support`

**Describe the current behavior**
When trying to convert [this model](https://drive.google.com/file/d/1oqWFKYXGwars93QmTgr0hd_dsWec77gJ/view?usp=sharing) the TFLiteConverter fails with `
ValueError: Invalid tensors 'MatMul' were found.`. The matmul operation in general does work, whith the example from: https://github.com/tensorflow/tensorflow/issues/27640

```
Traceback (most recent call last):
  File "tensorflow_matmul_issue.py", line 7, in <module>
    converter = tf.lite.TFLiteConverter.from_frozen_graph(graph_def_file, input_arrays, output_arrays, input_shapes={"0": [1, 128, 128, 1]})
  File "/home/paul/anaconda3/envs/openvino/lib/python3.7/site-packages/tensorflow/lite/python/lite.py", line 641, in from_frozen_graph
    sess.graph, output_arrays)
  File "/home/paul/anaconda3/envs/openvino/lib/python3.7/site-packages/tensorflow/lite/python/util.py", line 116, in get_tensors_from_tensor_names
    ",".join(invalid_tensors)))
ValueError: Invalid tensors 'MatMul' were found.
```
**Describe the expected behavior**
No error

**Code to reproduce the issue**
```python
import tensorflow as tf
graph_def_file = "model_lcnn_29v2.pb"

converter = tf.lite.TFLiteConverter.from_frozen_graph(graph_def_file, ["0"], ["MatMul"], input_shapes={"0": [1, 128, 128, 1]})
tflite_model = converter.convert()
open("model_lcnn_29v2.tflite", "wb").write(tflite_model)
```
- [model](https://drive.google.com/file/d/1oqWFKYXGwars93QmTgr0hd_dsWec77gJ/view?usp=sharing)

**Comment by anush-o** [comment]
I was able to replicate the issue with TF version 1.14, please find the Gist of [Colab](https://colab.research.google.com/drive/1U8kKeBAyGtdWgmnCVFaKBS42_QuNpeH1).

**Comment by Mycaster** [comment]
I tried to modify the python source code to print all tensorName and find your outputNodeName is not "MatMul", it is named  "212/212/MatMul"。 

```
def get_tensors_from_tensor_names(graph, tensor_names):
 ...
  tensor_name_to_tensor = {}
  for op in graph.get_operations():
    for tensor in op.values():
      print(get_tensor_name(tensor)) # add this to print all TensorName
      tensor_name_to_tensor[get_tensor_name(tensor)] = tensor

```

output result is :
```
0
...
212/212/MatMul
212/212
```
then it's work when replace output array with newname

```
converter = tf.lite.TFLiteConverter.from_frozen_graph(graph_def_file, ["0"], ["212/212/MatMul"], input_shapes={"0": [2, 128, 128, 1]})
```

**Comment by ymodak** [comment]
Reiterating Mycaster's solution.
You can view the ops names by using following code snippet as well:
```python
import tensorflow as tf
gf = tf.GraphDef()
gf.ParseFromString(open('model_lcnn_29v2.pb','rb').read())
names = [n.name for n in gf.node]
print(names)
```
On inspecting the output we see ```212/212/MatMul``` operation.
Closing this issue since correcting the node name fixes the problem. Thanks!
