### ISSUE TITLE
import tensorflow fail ,error code 3221225501

### ISSUE THREAD

**Issue by Neo01010** [tensorflow/tensorflow#31203]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): no
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): win7 SP1
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): pycharm Interpreter version 
- TensorFlow version (use command below): 1.14.0
- Python version: 3.7.4
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: cuda_10.0.130_411.31
- GPU model and memory:
 import tensorflow fail. 
You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`
![图片](https://user-images.githubusercontent.com/15312660/62227908-54a27780-b3ef-11e9-888c-d09d41f3ad53.png)

**Describe the current behavior**

**Describe the expected behavior**

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

Traceback (most recent call last):
  File "C:\Python37\lib\site-packages\tensorflow\python\pywrap_tensorflow.py",
ine 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Python37\lib\site-packages\tensorflow\python\pywrap_tensorflow_inte
al.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Python37\lib\site-packages\tensorflow\python\pywrap_tensorflow_inte
al.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, descri
ion)
  File "C:\Python37\lib\imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Python37\lib\imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: DLL load failed with error code 3221225501

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python37\lib\site-packages\tensorflow\__init__.py", line 28, in <mo
le>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-
port
  File "C:\Python37\lib\site-packages\tensorflow\python\__init__.py", line 49,
n <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Python37\lib\site-packages\tensorflow\python\pywrap_tensorflow.py",
ine 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "C:\Python37\lib\site-packages\tensorflow\python\pywrap_tensorflow.py",
ine 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Python37\lib\site-packages\tensorflow\python\pywrap_tensorflow_inte
al.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Python37\lib\site-packages\tensorflow\python\pywrap_tensorflow_inte
al.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, descri
ion)
  File "C:\Python37\lib\imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Python37\lib\imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: DLL load failed with error code 3221225501

Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

**Comment by anush-o** [comment]
@Neo01010 ,
Can you please refer the [link](https://devtalk.nvidia.com/default/topic/1057009/error-code-3221225501-when-trying-to-run-tensorflow/).Thanks!

**Comment by oanush** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Comment by xingmegshuo** [comment]
I just want to install tensorflo  not gpu, what should I do?

**Comment by eugene2ko** [comment]
> I just want to install tensorflo not gpu, what should I do?

Try to downgrade your version
pip3 install tensorflow==1.5

**Comment by mihaimaruseac** [comment]
No need to go that back. There are two pip packages, one contains gpu, the other one just cpu code. Make sure you use the right one.
