### ISSUE TITLE
TFLite: Changing weights

### ISSUE THREAD

**Issue by sbsky** [tensorflow/tensorflow#31205]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): OSX
- TensorFlow installed from (source or binary): Binary
- TensorFlow version (use command below): v1.12.1-7529-g3e0ad8a004 2.0.0-dev20190731
- Python version: 3.6.8

I'm attempting to implement Soft Conditional Computation (https://arxiv.org/pdf/1904.04971.pdf).  In this approach, the convolution weights are calculated dynamically for each input.  With a concrete function this works, however tflite seems to freeze the weights from the first input.  I was able to resolve this by calling resize_tensor_input() and allocate_tensors() for each image, at the cost of a small performance hit:

```
    # Note: need to fake resize the input & reallocate tensors
    interpreter.resize_tensor_input(0, (1, in_size, in_size, nb_channels,))
    interpreter.allocate_tensors()
```

My first thought was that tflite hardcodes the weights as an optimisation, however upon looking through the source code this doesn't seem to be the case, leading me to think this is a bug?

Example to reproduce the issue:
```
import tensorflow as tf
import numpy as np

reallocate_tensors = False  # Turn this on to reallocate tensors every run, fixing tflite accuracy
nb_channels = 5
wt_size = 100
in_size = 30

class DynamicWeightTest(tf.keras.layers.Layer):
    def __init__(self,
                 channels,
                 select_size,
                 **kwargs
                 ):
        super().__init__()

        self.channels = channels
        self.select_size = select_size


    def call(self, inputs):
        x = inputs[0]
        wt = inputs[1]

        x = tf.nn.conv2d(x, wt, (1, 1), 'VALID')

        return x


input_wt = tf.keras.layers.Input(shape=(1, nb_channels, wt_size), dtype=tf.float32)
input_data = tf.keras.layers.Input(shape=(in_size, in_size, nb_channels,), dtype=tf.float32)
x = DynamicWeightTest(channels=wt_size, select_size=nb_channels)([input_data, input_wt])

model = tf.keras.Model(inputs=[input_data, input_wt], outputs=[x])

# Get the concrete function from the Keras model.
model_fn = tf.function(lambda x: model(x))
model_fn_concrete = model_fn.get_concrete_function([input_data, input_wt])


# tflite
converter = tf.lite.TFLiteConverter.from_concrete_functions([model_fn_concrete])
converter.optimizations = [tf.lite.Optimize.DEFAULT]

tflite_model = converter.convert()

# Load TFLite model and allocate tensors.
interpreter = tf.lite.Interpreter(model_content=tflite_model)
interpreter.allocate_tensors()

# Get input and output tensors.
input_details = interpreter.get_input_details()
output_details = interpreter.get_output_details()

for _ in range(10):
    data = np.array(np.random.random_sample((1, in_size, in_size, nb_channels,)), dtype=np.float32)
    wt = np.array(np.random.random_sample((1, 1, nb_channels, wt_size)), dtype=np.float32)
    out_ref = model([data, wt])

    # concrete
    out_fn = model_fn_concrete(tf.constant(data), tf.constant(wt))

    # Note: need to fake resize the input & reallocate tensors
    if reallocate_tensors:
        interpreter.resize_tensor_input(0, (1, in_size, in_size, nb_channels,))
        interpreter.allocate_tensors()

    # Call tflite
    interpreter.set_tensor(input_details[0]['index'], data)
    interpreter.set_tensor(input_details[1]['index'], wt)
    interpreter.invoke()
    out_test = interpreter.get_tensor(output_details[0]['index'])

    out_ref = out_ref.numpy()
    out_fn = out_fn.numpy()
    diff = 100. * np.sum(np.abs(out_test - out_ref)) / np.sum(np.abs(out_ref))
    diff_fn = 100. * np.sum(np.abs(out_fn - out_ref)) / np.sum(np.abs(out_ref))
    test_sum = np.sum(out_test)

    print('Diff concrete function is: %f, diff tflite is: %f' % (diff_fn, diff))
```

Example output (without resize & allocate fix):
Diff concrete function is: 0.000000, diff tflite is: 0.000002
Diff concrete function is: 0.000000, diff tflite is: 33.312505
Diff concrete function is: 0.000000, diff tflite is: 34.966878
Diff concrete function is: 0.000000, diff tflite is: 31.750450
Diff concrete function is: 0.000000, diff tflite is: 33.716212
Diff concrete function is: 0.000000, diff tflite is: 34.539647
Diff concrete function is: 0.000000, diff tflite is: 35.657966
Diff concrete function is: 0.000000, diff tflite is: 35.823278
Diff concrete function is: 0.000000, diff tflite is: 36.413545
Diff concrete function is: 0.000000, diff tflite is: 33.483852

Edit: Changed above example to include a variable that turns on/off fix

**Comment by ravikyram** [comment]
@sbsky 
I tried to reproduce the issue. I am getting constant difference in tflite. Please, see below screenshot for your reference.Do you feel it is still a bug?.Please, confirm.Thanks!
![test](https://user-images.githubusercontent.com/51902062/62269229-ffe31900-b44f-11e9-98a0-f06183e0e7d0.png)

**Comment by sbsky** [comment]
My apologies, I could've made the example a bit more clear.  In the example the fix is by default on.  I've now included a variable 'reallocate_tensors' that controls it, now with default off.  Are you able to reproduce?

**Comment by amahendrakar** [comment]
@sbsky,
On running the code with [TF v2.0](https://colab.research.google.com/gist/amahendrakar/39d3391def95ea2eee7d5b2912218a77/tf2-0-template.ipynb), I got different outputs for `reallocate_tensors = False` and `reallocate_tensors = True`.

However, with the latest [TF-nightly](https://colab.research.google.com/gist/amahendrakar/23d6fb76ed3cdd02d1b4b0efa021ce37/tf-nightly.ipynb), both the outputs are almost similar. Could you confirm if this is this the expected behavior? Please find the attached gist. Thanks!

**Comment by sbsky** [comment]
@amahendrakar, no this is a further regression.  It seems that the previous workaround of reallocating tensors no longer functions.  tflite difference should be 0 & match concrete function output.

**Comment by jdduke** [comment]
Hey @sbsky , we've found the issue and it is indeed a bug in the x86 multi-threaded conv implementation for TFLite. This only worked by accident historically, as the tensor reallocation would force update the cached weights field we use in conv. I have a patch now that should resolve the issue. Thanks for flagging this!

Note that this should not be an issue on ARM devices, or on certain Conv permutations (e.g. dilated conv) where we use a completely different codepath.
