### ISSUE TITLE
training code utilize more cpu memory than gpu memory

### ISSUE THREAD

**Issue by mudassirej** [tensorflow/tensorflow#31216]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 16.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below): ('v1.12.0-0-ga6d8ffae09', '1.12.0')
- Python version:2.7
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):5.4.0
- CUDA/cuDNN version:10
- GPU model and memory:RTX2060 6GB

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
I am using tensorflow 1.12.0 with GPU RTX2060 with 6GB memory. I am using reinforcement learning code to train the robot in a gazebo platform using ROS. The issue is that it is utilizing more CPU memory rather than GPU memory. It takes a lot of time to train a robot. I attached a screenshot of the code and the system memory status along with GPU status. From the status, it is shown that it utilized whole 16gb system memory while it utilized 80% GPU memory but the temp and GPU utilization status is low. Its means GPU is not taking the load.
![Screenshot 2019-07-31 16:51:16](https://user-images.githubusercontent.com/45818401/62258506-5135dd00-b43d-11e9-8568-d8575a833655.png)
![Screenshot 2019-08-01 09:03:16](https://user-images.githubusercontent.com/45818401/62258507-5135dd00-b43d-11e9-8bb2-0a4857d20daf.png)
![Screenshot 2019-08-01 09:03:34](https://user-images.githubusercontent.com/45818401/62258509-5135dd00-b43d-11e9-87c3-8cd830c1abf3.png)
![Screenshot 2019-08-01 09:03:43](https://user-images.githubusercontent.com/45818401/62258510-51ce7380-b43d-11e9-9444-e2a23933652c.png)

**Describe the expected behavior**

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by gadagashwini** [comment]
@mudassirej Please take a look at [guide](https://www.tensorflow.org/guide/using_gpu) for GPU utilization. Can you use manual device placement with `tf.device('/GPU:0'):`  Let us know how it progresses. Thanks!

**Comment by mudassirej** [comment]
@gadagashwini I already allot the 80% GPU memory in the train network. It shows that it utilizes memory but as you can be seen from the Nvidia log that it is utilizing 20% only. 
Where I will add this command "tf.device('/GPU:0')?

**Comment by gadagashwini** [comment]
@mudassirej Provide us the full executable code snippet. It will indeed help us to move faster. Thanks!

**Comment by mudassirej** [comment]
[D3QN.tar.gz](https://github.com/tensorflow/tensorflow/files/3470959/D3QN.tar.gz)
These are the files.

**Comment by ymodak** [comment]
I suspect your TF session fails to recognize gpu. 
From the template you say you are using cuda 10.0 however nvidia-smi shows cuda 10.1
Can you please confirm what version of cuda you are installing? Also installed from binary or source?
Also can you please print following output;
```python
tf.Session(config=tf.ConfigProto(log_device_placement=True))
```

**Comment by mudassirej** [comment]
I installed a Cuda version 10 from the source. I attached a picture which shows the running cuda version and tf.session result. It shows XLA-GPU device, what does it mean?
![tensor1](https://user-images.githubusercontent.com/45818401/62994416-5c055e80-be8e-11e9-9019-a43d2856234f.png)

**Comment by ymodak** [comment]
Can you send your code as github gist or google colab gist? It will be easier to work with rather than screenshot. Thanks!

**Comment by mudassirej** [comment]
https://github.com/mudassirej/DQN-with-tensorflow-in-Gazebo
