### ISSUE TITLE
'tensorflow/lite/c/c_api_internal.h' file not found

### ISSUE THREAD

**Issue by meiwuzhao** [tensorflow/tensorflow#31219]
pod create the library MyLibray.framework    s.dependency 'TensorFlowLite'.

build error in tensorlow_lite.framework.  #include "tensorflow/lite/c/c_api_internal.h"

prompt:  'tensorflow/lite/c/c_api_internal.h' file not found

In my framework. just #include <tensorflow_lite/tensorflow/lite/kernels/register.h>

why?

i need to set up what?

**Comment by gadagashwini** [comment]
@meiwuzhao Please provide the information asked in [Template](https://github.com/tensorflow/tensorflow/issues/new?template=40-tflite-op-request.md). Thanks!

**Comment by gadagashwini** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
