### ISSUE TITLE
Some of the operators in the model are not supported by the standard TensorFlow Lite runtime and are not recognized by TensorFlow. If you have a custom implementation for them you can disable this error with --allow_custom_ops, or by setting allow_custom_ops=True when calling tf.lite.TFLiteConverter(). Here is a list of builtin operators you are using: ADD, CONV_2D, TANH. Here is a list of operators for which you will need custom implementations: DEPTH_TO_SPACE.

### ISSUE THREAD

**Issue by jichangsheng** [tensorflow/tensorflow#31227]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- TensorFlow installed from (source or binary):
- TensorFlow version (or github SHA if from source):

**Provide the text output from tflite_convert**

```
# Copy and paste here
```

Also, please include a link to a GraphDef or the model if possible.

**Any other info / logs**

Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by anush-o** [comment]
@jichangsheng ,
Can you please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version.Thanks!

**Comment by ymodak** [comment]
As the error suggests you have to build custom operation for ```DEPTH_TO_SPACE```
See https://www.tensorflow.org/lite/guide/ops_custom

**Comment by oanush** [comment]
@jichangsheng ,
Can you please try @ymodak solution and let us know your feedback?Thanks!

**Comment by oanush** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Comment by jichangsheng** [comment]
It worked and successfully produced the .tflite file.
But when I want to use this file with tf.lite.Interpreter(.tflite), An error raised as
‘ValueError:Didn’t find custom op for name ‘DEPTH_TO_SPACE’ with version 1，Registration failed ‘




--
发自我的网易邮箱手机智能版



在 2019-08-13 18:16:07，oanush <notifications@github.com> 写道：


Closed #31227.
