### ISSUE TITLE
Porting micro_vision example to other other boards.

### ISSUE THREAD

**Issue by Sreerag-ibtl** [tensorflow/tensorflow#31230]
This template is for miscellaneous issues not covered by the other issue categories.

For questions on how to work with TensorFlow, or support for problems that are not verified bugs in TensorFlow, please go to [StackOverflow](https://stackoverflow.com/questions/tagged/tensorflow).

If you are reporting a vulnerability, please use the [dedicated reporting process](https://github.com/tensorflow/tensorflow/blob/master/SECURITY.md).

For high-level discussions about TensorFlow, please post to discuss@tensorflow.org, for questions about the development or internal workings of TensorFlow, or if you would like to know how to contribute to TensorFlow, please post to developers@tensorflow.org.

Is it possible to run this [example](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/experimental/micro/examples/micro_vision) on an Arduino UNO following the the same workflow as in the example, or at least with some minor hacks? TIA

**Comment by gowthamkpr** [comment]
Please refer to the following [doc](https://www.tensorflow.org/lite/microcontrollers#get_started) where tflite with micro controllers is given. Thanks!
