### ISSUE TITLE
Transfer learning with frozen model ( Resnet )

### ISSUE THREAD

**Issue by abdou31** [tensorflow/tensorflow#31232]
Hello,
I want to use transfer learning to detect 80 eye region landmarks instead of 68 face landmarks.
I have a pre-trained frozen graph model pb .
I want to know what are the steps that I can follow to perform the transfer learning to my model?
I see this script, but I don't know how can I use it.
https://github.com/tensorflow/models/blob/master/official/resnet/resnet_run_loop.py

**Comment by ravikyram** [comment]
@abdou31 
Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version.
I am not able to open the link you have provided.Request you to share again.

Please, see the below link if it helps you.Thanks!
https://www.tensorflow.org/tutorials/images/transfer_learning

**Comment by abdou31** [comment]
+ Operating system: Windows 10 x64
+ Tensorflow version: binary 1.13.1
+ Model: Resnet

**Comment by ymodak** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.
