### ISSUE TITLE
events.out.tfevents file is getting too large as training continues

### ISSUE THREAD

**Issue by mhajiaghayi** [tensorflow/tensorflow#31242]
Tensorboard event file is getting too large (> 10Gig) as the training continues. I use custom estimator and input_fn reads data from a generator. Everything works fine except this huge tensorboard file that I think it also reduces the speed. When I increase save_summary_steps parameter, this problem doesn't go away. I have seen other blogs complaining about it and none of them provided a viable solution for it. 

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below): tensorflow-gpu==1.12.0 
tensorflow==1.13.1
tensorflow-estimator==1.13.0
- Python version: Python 3.5.2
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: CUDA 9
- GPU model and memory: Tesla M40 24GB or Nvidia Geforece GTX 1080Ti

**Comment by anush-o** [comment]
@mhajiaghayi ,
In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thanks!

**Comment by mhajiaghayi** [comment]
`  def inputFn(self,tasks, mode, params= None):

    types = ((tf.string,tf.string,tf.float32),tf.float32)
    shapes = ((None,None,None),None)
    datasets = []
    for task in tasks:
        dataset = tf.data.Dataset.from_generator(
                            functools.partial(task.relevanceDb.batchGen,self.args,mode),
                            output_shapes=shapes, output_types=types)
        datasets.append(dataset)
        choice = tf.data.Dataset.range(len(datasets)).flat_map(self.getBatch).repeat(self.args.maxSteps)
        multiDataset = tf.data.experimental.choose_from_datasets(datasets,choice)
    multiDataset = multiDataset.batch(self.args.batchSize).prefetch(1) `

**Comment by gowthamkpr** [comment]
@mhajiaghayi Can you please provide the github gist of the code that you are working with. Thanks!

**Comment by gowthamkpr** [comment]
@mhajiaghayi Can you please post this issue in [Tensorflow/Tensorboard](https://github.com/tensorflow/tensorboard/issues/) as this issue is related to Tensorboard and you can  get a fast reply. Also Please take a look at this [issue](https://github.com/tensorflow/tensorboard/issues/1252) which is quite similar to yours. Thanks!
