### ISSUE TITLE
WALSMatrixFactorization: Input matrix is not invertible. node cond/MatrixSolve

### ISSUE THREAD

**Issue by MiladShahidi** [tensorflow/tensorflow#31248]
**System information**
- Custom code: Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- Mobile device: Noe
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): v1.13.0-rc2-0-gc865ec5621 / 1.13.0-rc2
- Python version: 3.6
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Describe the current behavior**
Factorizing a small 4x4 (dense) matrix with WALSMatrixFactorizaion results in the following error:

> InvalidArgumentError (see above for traceback): Input matrix is not invertible.
> 	 [[node cond/MatrixSolve (defined at /home/milad/PycharmProjects/wals_rec/temp.py:55) ]] 

**Describe the expected behavior**
Factorize the matrix and evaluate without the error.

**Code to reproduce the issue**

	import numpy as np
	import tensorflow as tf
	from tensorflow.contrib.factorization import WALSMatrixFactorization
	import shutil

	def make_input_fn(args):

		def to_sparse(values):
			indices = np.array([[0], [1], [2], [3]], dtype=np.int64)
			sp_tensor = tf.SparseTensor(indices=indices, values=values, dense_shape=values.shape)
			return sp_tensor

		def _input_fn():
			rows_dataset = tf.data.Dataset.from_tensor_slices(args['matrix_values']). \
				map(map_func=to_sparse). \
				repeat(count=None). \
				batch(batch_size=args['batch_size'])

			cols_dataset = tf.data.Dataset.from_tensor_slices(np.transpose(args['matrix_values'])). \
				map(map_func=to_sparse). \
				repeat(count=None). \
				batch(batch_size=4)

			features = {
				WALSMatrixFactorization.INPUT_ROWS: rows_dataset.make_one_shot_iterator().get_next(),
				WALSMatrixFactorization.INPUT_COLS: cols_dataset.make_one_shot_iterator().get_next(),
				WALSMatrixFactorization.PROJECT_ROW: tf.constant(True, name="PROJECT_ROW")
			}
			return features, None

		return _input_fn

	def train_and_evaluate(args):

		def experiment_fn(output_dir):
			return tf.contrib.learn.Experiment(
				tf.contrib.factorization.WALSMatrixFactorization(
					num_rows=args["nrows"],
					num_cols=args["ncols"],
					row_weights=None,
					col_weights=None,
					regularization_coeff=0,
					embedding_dimension=args["n_embeds"],
					model_dir=output_dir),
				train_input_fn=make_input_fn(args),
				eval_input_fn=make_input_fn(args),
				train_steps=10,
				eval_steps=1,
				# Error doesn't happen if min_eval_frequency > train_steps
				min_eval_frequency=5)

		from tensorflow.contrib.learn.python.learn import learn_runner
		learn_runner.run(experiment_fn=experiment_fn, output_dir=args["output_dir"])

	if __name__ == '__main__':

		K = 4
		args = {
			'ncols': K,
			'nrows': K,
			'output_dir': 'wals_temp',
			'n_embeds': 2,
			'n_steps': 5,
			'batch_size': K,
			'matrix_values': np.array([[1, 2, 3, 4],
									   [2, 4, 8, 12],
									   [3, 6, 7, 13],
									   [3, 5, 7, 9]], dtype=np.float32)

		}

		shutil.rmtree(args['output_dir'], ignore_errors=True)
		train_and_evaluate(args)

**Other info / logs**
The error happens on [this line](https://github.com/tensorflow/tensorflow/blob/27d5e277dd6b9a6c3a331ae0dfd51361607d6b9b/tensorflow/contrib/factorization/python/ops/factorization_ops.py#L919). The cause seems to be that the (column) Gramian suddenly becomes zero during evaluation and therefore the lhs of the normal equation is not invertible (training steps run fine). I confirmed this by running it step by step and using tfdbg.

**Comment by anush-o** [comment]
Issue replicating with TF version-1.13,please find the gist of [collab](https://colab.research.google.com/drive/12h3Ud8_NI7i2KrSq7fhIre7memfsoriP) .Thanks!

**Comment by MiladShahidi** [comment]
Thanks for getting back. Do you mean you were not able to replicate the problem with TF 1.13?

Here is (part of) what I get when I run the collab you created.

> InvalidArgumentError: Input matrix is not invertible.
> 	 [[{{node cond/MatrixSolve}}]]
> 
> During handling of the above exception, another exception occurred:
> 
> InvalidArgumentError                      Traceback (most recent call last)
> /usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py in _do_call(self, fn, *args)
>    1368           pass
>    1369       message = error_interpolation.interpolate(message, self._graph)
> -> 1370       raise type(e)(node_def, op, message)
>    1371 
>    1372   def _extend_graph(self):
> 
> InvalidArgumentError: Input matrix is not invertible.
> 	 [[node cond/MatrixSolve (defined at <ipython-input-1-81cc9fbfe66d>:49) ]]

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.
