### ISSUE TITLE
SequenceFeatures gets overly complex when used with a sequence_numeric_column

### ISSUE THREAD

**Issue by durandg12** [tensorflow/tensorflow#31240]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): no
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): macOS 10.13.6
- TensorFlow installed from (source or binary): from pip install
- TensorFlow version (use command below): v2.0.0-beta0-16-g1d91213fe7 2.0.0-beta1
- Python version: v3.6.7:6ec5cf24b7, Oct 20 2018, 03:02:14

**Describe the current behavior**

The behaviour of `SequenceFeatures` layer is really different between when it's used with a feature column produced with `sequence_numeric_column` and when it's used with a feature column produced with `sequence_categorical_column_with_identity`and `embedding_column`.

I've [already reported an issue](https://github.com/tensorflow/tensorflow/issues/29879) where the `call` method of `SequenceFeatures` used with `sequence_numeric_column` unnecessarily requires its input to be a `SparseTensor` instead of a regular `Tensor`.

Today I was experimenting with Keras Funcional API by building a model using two `SequenceFeatures` layers along with both `sequence_numeric_column` and `embedding_column`. I got graphic depictions of the model using `tf.keras.Model.summary` and `tf.keras.utils.plot_model` and discovered that `SequenceFeatures`  with `sequence_numeric_column` gets decomposed in a million of sub-layers of type `TensorFlowOpLayer`, as opposite to the clean and to the point depiction of `SequenceFeatures` with `embedding_column`. This has the only effect of overloading the results of `summary`and `plot_model`with not so relevant information instead of having a concise insight of the graph.

Here is the obtained plot:
![Large and complex plot of the model](https://github.com/durandg12/nn_pictures/blob/master/total_mess.png)

The ![upper part](https://github.com/durandg12/nn_pictures/blob/master/zoom.png) of the plot is due to the conversion of the input into sparse tensor, so this is related to [the previous issue](https://github.com/tensorflow/tensorflow/issues/29879). The focus of the issue I'm opening today is ![this part](https://github.com/durandg12/nn_pictures/blob/master/zoom2.png) which should not exist in my opinion.

**Describe the expected behavior**

Assuming my previous issue is solved, I think that the result of `plot_model` should simply ![look like this](https://github.com/durandg12/nn_pictures/blob/master/expected_model.png).

**Code to reproduce the issue**

```
import numpy as np
import tensorflow as tf
from tensorflow.feature_column import embedding_column, sequence_categorical_column_with_identity, \
    sequence_numeric_column
from tensorflow.keras import Input, Model
from tensorflow.keras.experimental import SequenceFeatures
from tensorflow.keras.layers import Input, Dense


#on my computer I have used a
#custom plot_model instead of tf.keras.utils.plot_model 
#because of a bug, see nota bene below
#from deep.modeltodot import plot_model
from tensorflow.keras.utils import plot_model

print(tf.version.GIT_VERSION, tf.version.VERSION)

#Model preparation
seq_fc_dense = sequence_numeric_column('denseFeat')
seq_layer_dense = SequenceFeatures(seq_fc_dense, name='denseFeatLayer')

nb_cat = 5
seq_fc_cat = sequence_categorical_column_with_identity('catFeat', nb_cat)
seq_fc_cat = embedding_column(seq_fc_cat, 2)
seq_layer_cat = SequenceFeatures(seq_fc_cat, name='catFeatLayer')

input_dense = Input(shape=(None,), name='denseFeat')
input_cat = Input(shape=(None,), name='catFeat', dtype=tf.int32)
# we need to convert input_dense to a sparse tensor, see https://github.com/tensorflow/tensorflow/issues/29879
zero = tf.constant(0, dtype=tf.float32)
indices = tf.where(tf.not_equal(input_dense, zero))
values = tf.gather_nd(input_dense, indices)
sparse = tf.SparseTensor(indices, values, tf.cast(tf.shape(input_dense), dtype=tf.int64))

x_dense = seq_layer_dense({'denseFeat': sparse})[0]
x_cat = seq_layer_cat({'catFeat': input_cat})[0]
x = tf.concat([x_dense, x_cat], -1)
output = Dense(1, activation='sigmoid')(x)

model = Model(inputs={'denseFeat': input_dense, 'catFeat': input_cat}, outputs=output)

#model.summary()
plot_model(model)
```

**Nota bene**
The custom `plot_model` that I used to make my plots is the same as `tf.keras.utils.plot_model` except that I replaced the following import in keras/utils/vis_utils.py:
```
try:
  # pydot-ng is a fork of pydot that is better maintained.
  import pydot_ng as pydot
except ImportError:
  # pydotplus is an improved version of pydot
  try:
    import pydotplus as pydot
  except ImportError:
    # Fall back on pydot if necessary.
    try:
      import pydot
    except ImportError:
      pydot = None
```
by `import pydot_ng as pydot`and I removed the call to `_check_pydot` in `model_to_dot` because it was raising an exception.

**Comment by gadagashwini** [comment]
Was able to replicate the issue with Tensorflow 2.0.0.beta1 on Colab. Please take a look at colab [gist](https://colab.research.google.com/drive/1B9UwKkZRr2WweASkcF0iWJukS0i6pVPY). Thanks!

**Comment by amahendrakar** [comment]
@durandg12,
Could you please update TensorFlow to v2.3 and check if you are still facing the same issue. Thanks!

**Comment by durandg12** [comment]
@amahendrakar the issue is solved, with the caveat that we still have to convert dense tensors to sparse tensors just for the code to convert them back to dense tensors which seems inefficient. Also some behind the scene changes caused an error with the code above so I have to put the transformation to a sparse tensor into a function and wrap it into a `Lambda` layer. So here is the final code I used to test:

```
import numpy as np
import tensorflow as tf
from tensorflow.feature_column import embedding_column, sequence_categorical_column_with_identity, \
    sequence_numeric_column
from tensorflow.keras import Input, Model
from tensorflow.keras.experimental import SequenceFeatures
from tensorflow.keras.layers import Input, Dense

from tensorflow.keras.utils import plot_model

print(tf.version.GIT_VERSION, tf.version.VERSION)

#Model preparation
seq_fc_dense = sequence_numeric_column('denseFeat')
seq_layer_dense = SequenceFeatures(seq_fc_dense, name='denseFeatLayer')

nb_cat = 5
seq_fc_cat = sequence_categorical_column_with_identity('catFeat', nb_cat)
seq_fc_cat = embedding_column(seq_fc_cat, 2)
seq_layer_cat = SequenceFeatures(seq_fc_cat, name='catFeatLayer')

input_dense = Input(shape=(None,), name='denseFeat')
input_cat = Input(shape=(None,), name='catFeat', dtype=tf.int32)
# we need to convert input_dense to a sparse tensor, see https://github.com/tensorflow/tensorflow/issues/29879
def sparse_f(input_dense):
    zero = tf.constant(0, dtype=tf.float32)
    indices = tf.where(tf.not_equal(input_dense, zero))
    values = tf.gather_nd(input_dense, indices)
    sparse = tf.SparseTensor(indices, values, tf.cast(tf.shape(input_dense), dtype=tf.int64))
    return sparse
sparse = tf.keras.layers.Lambda(sparse_f)(input_dense)

x_dense = seq_layer_dense({'denseFeat': sparse})[0]
x_cat = seq_layer_cat({'catFeat': input_cat})[0]
x = tf.concat([x_dense, x_cat], -1)
output = Dense(1, activation='sigmoid')(x)

model = Model(inputs={'denseFeat': input_dense, 'catFeat': input_cat}, outputs=output)

model.summary()
plot_model(model)
```

Here is the resulting output from `plot_model` : [link](https://github.com/durandg12/nn_pictures/blob/master/tf2.3.0-model.png).

**Comment by goldiegadde** [comment]
@durang12 closing this one out, as looks like with latest TF version, the issues are resolved .

**Comment by summa-code** [comment]
> @amahendrakar the issue is solved, with the caveat that we still have to convert dense tensors to sparse tensors just for the code to convert them back to dense tensors which seems inefficient. Also some behind the scene changes caused an error with the code above so I have to put the transformation to a sparse tensor into a function and wrap it into a `Lambda` layer. So here is the final code I used to test:
> 
> ```
> import numpy as np
> import tensorflow as tf
> from tensorflow.feature_column import embedding_column, sequence_categorical_column_with_identity, \
>     sequence_numeric_column
> from tensorflow.keras import Input, Model
> from tensorflow.keras.experimental import SequenceFeatures
> from tensorflow.keras.layers import Input, Dense
> 
> from tensorflow.keras.utils import plot_model
> 
> print(tf.version.GIT_VERSION, tf.version.VERSION)
> 
> #Model preparation
> seq_fc_dense = sequence_numeric_column('denseFeat')
> seq_layer_dense = SequenceFeatures(seq_fc_dense, name='denseFeatLayer')
> 
> nb_cat = 5
> seq_fc_cat = sequence_categorical_column_with_identity('catFeat', nb_cat)
> seq_fc_cat = embedding_column(seq_fc_cat, 2)
> seq_layer_cat = SequenceFeatures(seq_fc_cat, name='catFeatLayer')
> 
> input_dense = Input(shape=(None,), name='denseFeat')
> input_cat = Input(shape=(None,), name='catFeat', dtype=tf.int32)
> # we need to convert input_dense to a sparse tensor, see https://github.com/tensorflow/tensorflow/issues/29879
> def sparse_f(input_dense):
>     zero = tf.constant(0, dtype=tf.float32)
>     indices = tf.where(tf.not_equal(input_dense, zero))
>     values = tf.gather_nd(input_dense, indices)
>     sparse = tf.SparseTensor(indices, values, tf.cast(tf.shape(input_dense), dtype=tf.int64))
>     return sparse
> sparse = tf.keras.layers.Lambda(sparse_f)(input_dense)
> 
> x_dense = seq_layer_dense({'denseFeat': sparse})[0]
> x_cat = seq_layer_cat({'catFeat': input_cat})[0]
> x = tf.concat([x_dense, x_cat], -1)
> output = Dense(1, activation='sigmoid')(x)
> 
> model = Model(inputs={'denseFeat': input_dense, 'catFeat': input_cat}, outputs=output)
> 
> model.summary()
> plot_model(model)
> ```
> 
> Here is the resulting output from `plot_model` : [link](https://github.com/durandg12/nn_pictures/blob/master/tf2.3.0-model.png).

How do we create an input for Sliding Window Time series data ?
