### ISSUE TITLE
Trying to quantize resnet50 tf model

### ISSUE THREAD

**Issue by joyIntel** [tensorflow/tensorflow#31246]
I am trying to quantize [resnet50 tf model](https://github.com/tensorflow/models/tree/master/official/resnet) (NHWC) using imagenet images. 

I am using [this](https://www.tensorflow.org/lite/performance/post_training_quantization) tutorial for reference.

The code is like that - 
![quantize](https://user-images.githubusercontent.com/39498824/62318443-ba731b80-b450-11e9-9dc4-32ec55ac3c0a.png)

I am confused about how to take image inputs as a numpy array inside representative_dataset_gen(). I have tried like this -

![dataset_gen](https://user-images.githubusercontent.com/39498824/62318466-c3fc8380-b450-11e9-9c85-691395f86e38.png)

It is not working.

**Comment by ymodak** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow-tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.
