### ISSUE TITLE
Error when changing transformer hyperparameters

### ISSUE THREAD

**Issue by dawsoneliasen** [tensorflow/tensorflow#31241]
## URL(s) with the issue:
https://www.tensorflow.org/beta/tutorials/text/transformer#set_hyperparameters

## Description of issue (what needs changing):
I've been working with the 'Transformer model for language understanding' notebook on my own dataset. I got it to work with the default hyperparameters. The tutorial explains that I can create a Transformer XL by adjusting the hyperparameters to those that are used in the paper. I changed them to the suggested values, and I am now getting a `ValueError` when I try to train.
```
ValueError: Tensor's shape (8220, 128) is not compatible with supplied shape (8220, 512)
```
I think that this means that some object is not configured properly (not using the hyper parameter variables), but I can't figure out where it's happening. I tried restarting the runtime and running everything again, but it didn't help.

## System information
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): I have made small adjustments to the provided code in the transformer notebook to accommodate my own data. I also changed the values of the hyper parameters of the model.
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):  I am running the notebook in a Colab GPU runtime; Linux Ubuntu 18.04.2
- TensorFlow installed from (source or binary): I'm not exactly sure, I install it using this command, provided with the notebook `pip install -q tensorflow-gpu==2.0.0-beta1`
- TensorFlow version (use command below): `tensorflow-gpu==2.0.0-beta1`
- Python version: 3.6.8
- CUDA version: CUDA: 10.0.130
- GPU model and memory: I'm not sure how to get this info, but it's a Colab GPU runtime.

## Code snippets
I changed the output encoder from a `SubwordTextEncoder` to a `TokenTextEncoder`:
```
tokenizer_out = tfds.features.text.TokenTextEncoder(
    unique_concepts
)
```
I changed the `tf_encode` function to use a single argument instead of two:
```
def tf_encode(element):
    return tf.py_function(encode, [element[0], element[1]], [tf.int64, tf.int64])
```
And I changed the hyperparameter values:
```
num_layers = 6
d_model = 512
dff = 2048
num_heads = 8
```

**Comment by ravikyram** [comment]
Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version. Also, did you compile from source or install a binary?

Make sure you also include the code snippet to reproduce the issue. If you are unclear what to include see the issue template displayed in the Github new issue [template](https://github.com/tensorflow/tensorflow/issues/new/choose).

We ask for this in the issue submission template, because it is really difficult to help without that information. Thanks!

**Comment by dawsoneliasen** [comment]
@ravikyram Thanks for the response, and sorry for the delay. I updated the issue body with this info. Sorry for not including it originally - I used the documentation issue submission template, which does not say anything about system information.

**Comment by ravikyram** [comment]
@dawsoneliasen 
I tried to reproduce the issue in the doc link https://www.tensorflow.org/beta/tutorials/text/transformer#set_hyperparameters
 by changing SubwordTextEncoder to a TokenTextEncoder:I am getting the below error `AttributeError: type object 'TokenTextEncoder' has no attribute 'build_from_corpus'`.Please, help me with the reproducible code. Thanks!

**Comment by dawsoneliasen** [comment]
@ravikyram 
The `TokenTextEncoder` takes a list of tokens to build the vocabulary, instead of building from a corpus. As you can see in the snippet above, I pass a list of tokens to the constructor. You can replicate this by passing any list of unique strings.

**Comment by dawsoneliasen** [comment]
@ravikyram
I just restarted and ran again to try to take another stab at identifying the problem, and it worked. I'm not sure what changed but I'm going to close the issue.

**Comment by dawsoneliasen** [comment]
@ravikyram 
In case you're interested, or someone else runs into this problem:
The issue is caused by the checkpoints that are created when training the model. If you train a model with the default parameters, and then change to the Transformer XL parameters and try to train again, you'll get an error because TF wants to load the checkpoint of the old model.

To resolve, you have to remove the checkpoints before training the Transformer XL. Disconnecting from the runtime doesn't help.
```
!rm -r ./checkpoints
```
