### ISSUE TITLE
TypeError: load_dataset() got an unexpected keyword argument 'test_with_fake_data'

### ISSUE THREAD

**Issue by ziaoang** [tensorflow/tensorflow#3125]
### Environment info
Operating System: ubuntu 14.04 and Mac OSX
Pip install: 0.9.0

In 'tensorflow/tensorflow/examples/skflow/' folder, when run 'text_classification*.py',
the code
'''
dbpedia = learn.datasets.load_dataset(
    'dbpedia', test_with_fake_data=FLAGS.test_with_fake_data)
'''
cause a bug
'''
TypeError: load_dataset() got an unexpected keyword argument 'test_with_fake_data'
'''

It is because that if user install tensorflow by pip, the definition of 'load_dataset()' in 'tensorflow/tensorflow/contrib/learn/python/learn/datasets/__init__.py' is
'def load_dataset(name):',
but in current git version, the definition of 'load_dataset()' is
'def load_dataset(name, size='small', test_with_fake_data=False):'.

**Comment by terrytangyuan** [comment]
@ziaoang Yeah you are using the old version. Please install the latest version.

**Comment by ziaoang** [comment]
Do you mean I should re-install tensorflow via source code instead of pip?

**Comment by ziaoang** [comment]
I re-install tensorflow via source code, and the example runs normally. Thank you @terrytangyuan .
