### ISSUE TITLE
google.protobuf.json_format.MessageToDict incorrectly decodes bytes_list

### ISSUE THREAD

**Issue by robertlugg** [tensorflow/tensorflow#31250]
**System information**

> - Have I written custom code (as opposed to using a stock example script provided in TensorFlow):

YES, custom code.
> - OS Platform and Distribution (e.g., Linux Ubuntu 16.04):

CentOS 7-1810 in VirtualBox VM
```
uname -a
Linux centos7-1810 3.10.0-957.10.1.el7.x86_64 #1 SMP Mon Mar 18 15:06:45 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```
> - TensorFlow installed from (source or binary):

Binary.  Unchanged from tf-nightly.
> - TensorFlow version (use command below):

Note that a warning is printed if I use tf.GIT_VERSION.
```
print(tf.version.GIT_VERSION, tf.VERSION) 
v1.12.1-7396-g12481e7e74 1.15.0-dev20190730
```
> - Python version:

Python 3.6.8 :: Anaconda, Inc.

**Describe the current behavior**
google.protobuf.json_format.MessageToDict, I believe "decodes" bytes_list incorrectly.  What I get is:
`['VGF4aSBBZmZpbGlhdGlvbiBTZXJ2aWNlcw==']`

**Describe the expected behavior**
google.protobuf.json_format.MessageToDict should decode my byte_list to:
`[b'Taxi Affiliation Services']`
, which is what I get when looking directly at the tf.train.Example.

Data is from the chicago_taxi_pipeline demo at:
https://github.com/tensorflow/tfx/blob/master/tfx/examples/chicago_taxi_pipeline

"data_tfrecord-00000-of-00001" is the "eval" output of:
tfx.components.example_gen.csv_example_gen.component.CsvExampleGen

**Code to reproduce the issue**
```
import tensorflow as tf
import google.protobuf.json_format as jfmt

print(tf.__version__)
example = next(tf.python_io.tf_record_iterator("data_tfrecord-00000-of-00001"))
result = tf.train.Example.FromString(example)

company_name_direct = result.features.feature['company'].bytes_list.value
print(company_name_direct)

result_as_dict = jfmt.MessageToDict(result)
company_name_indirect = result_as_dict['features']['feature']['company']['bytesList']['value'] 
print(company_name_indirect)
```
```
# output:
1.15.0-dev20190730
[b'Taxi Affiliation Services']
['VGF4aSBBZmZpbGlhdGlvbiBTZXJ2aWNlcw==']
```

**Other info / logs**
I have not tested this on any other build except 1.15 nightly.

**Comment by robertlugg** [comment]
[data_tfrecord-00000-of-00001.gz](https://github.com/tensorflow/tensorflow/files/3458925/data_tfrecord-00000-of-00001.gz)

**Comment by ravikyram** [comment]
I have tried on Jupyter notebook with TF version 1.15.0-dev20190802 and 1.14 was able to reproduce the issue. Please, find the zip file. Thanks!
[protobuf.tar.gz](https://github.com/tensorflow/tensorflow/files/3461295/protobuf.tar.gz)

**Comment by robertlugg** [comment]
Thanks for taking this on.  I suspect it should actually be in the https://github.com/protocolbuffers/protobuf project, but it would have been hard to create a test case which didn't use `tf.train.Example`

**Comment by kumariko** [comment]
@robertlugg We see you are using an older version of tensorflow(1.x) which is officially considered as end of life. We recommend that you upgrade to 2.6 which is latest stable version of TF and let us know if the issue still persists in newer versions.we will get you the right help.Thanks!
