### ISSUE TITLE
GPU not working on C++

### ISSUE THREAD

**Issue by dzhyeon** [tensorflow/tensorflow#3126]
I'm on working on load trained model in c++ like [this](http://stackoverflow.com/questions/34343259/is-there-an-example-on-how-to-generate-protobuf-files-holding-trained-tensorflow/34343517#34343517).
After many tries, I've manage to load trained model with its weights. But it looks like c++ version doesn't use GPU for inference. While running my code in c++, I check GPU usage using nvidia-smi and there is no change in GPU usage. After close looking at the example code in /tensorflow/cc/tutorials/example_trainer.cc and [this,](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/graph/default_device.h) I've tried assigning device to each node like below. But still, no GPU usage in nvidia-smi and actual running time is horribly slow. BTW, there is no problem using GPU if it is running on python.
`  const std::string device = "/gpu:0";

  std::vector<string> vNames;

  int node_count = graph_def.node_size();
  for (int i = 0; i < node_count; i++) {
      auto n = graph_def.node(i);
       if (n.name().find("nWeights") != std::string::npos) {
          vNames.push_back(n.name());
          std::cout << n.name() << std::endl;
      }
      auto node = graph_def.mutable_node(i);
      node->set_device(device);
  }`

My Environment:
OS: ubuntu 14.04
Graphics: GeForce GTX 980 Ti
CUDA Driver Version / Runtime Version          7.5 / 7.5
CUDA Capability Major/Minor version number:    5.2

**Comment by andydavis1** [comment]
Did you print out the GraphDef and check that the "/gpu:0" device was set in each node? Can you include a link to your C++ code which has the issue?

**Comment by dzhyeon** [comment]
Here is the code. when printing out std::cout <<  node->device() << std::endl, /gpu:0 was printed out. But no GPU was running. 

`#include <opencv2/core/core.hpp>
#include <opencv2/highgui/highgui.hpp>
#include <iostream>


#include "tensorflow/core/public/session.h"
#include "tensorflow/core/platform/env.h"
#include "tensorflow/core/graph/default_device.h"
#include "tensorflow/core/graph/graph_def_builder.h"

using namespace tensorflow;

int main(int argc, char* argv[]) {

  int width=100;
  int height=100;
  cv::Mat image = cv::imread("/home/myname/test1.jpg");
  image.convertTo(image, CV_32FC1);

  // Initialize a tensorflow session
  Session* session;
  Status status = NewSession(SessionOptions(), &session);
  if (!status.ok()) {
    std::cout << status.ToString() << "\n";
    return 1;
  }

  // Read in the protobuf graph we exported
  // (The path seems to be relative to the cwd. Keep this in mind
  // when using `bazel run` since the cwd isn't where you call
  // `bazel run` but from inside a temp folder.)'/home/daejin/test_model2', 'train.pb'
  GraphDef graph_def;


  status = ReadBinaryProto(Env::Default(), "/home/daejin/test_model2/train.pb", &graph_def);
  if (!status.ok()) {
    std::cout << status.ToString() << "\n";
    return 1;
  }

  // Add the graph to the session
  status = session->Create(graph_def);
  const std::string device = "/gpu:0";
  std::vector<string> vNames;
  int node_count = graph_def.node_size();
  for (int i = 0; i < node_count; i++) {
      auto n = graph_def.node(i);
       if (n.name().find("nWeights") != std::string::npos) {
          vNames.push_back(n.name());
      }
      auto node = graph_def.mutable_node(i);
      node->set_device(device);
      std::cout <<  node->device() << std::endl;
  }

  std::vector<tensorflow::Tensor> out1;
  session->Run({}, vNames, {}, &out1);
  Tensor input(tensorflow::DT_FLOAT, {1, height, width,3});
  Tensor learning_phase(tensorflow::DT_UINT8, TensorShape());
  learning_phase.scalar<uchar>()()=0;
  std::copy_n(image.begin<float>(), width*height,
              input.flat<float>().data());

  graph::SetDefaultDevice("/gpu:0", &graph_def);

  // The session will initialize the outputs
  std::vector<tensorflow::Tensor> outputs;

  const TensorShape expected_shape({1, height, width,1});
  cv::Mat outMat = cv::Mat::zeros(height, width, CV_32FC1);

  status = session->Run(
        {{"input1:0", input}},
        {"output1:0"}, {}, &outputs);
  if (!status.ok()) {
    std::cout << status.ToString() << "\n";
    return 1;
  }
}
`

**Comment by dzhyeon** [comment]
I've just found that when running a tensorflow python script using '$python ~.py', GPU was used. 
But if the script is built with bazel and execute binary, GPU was not used.
I've put my code on tensorflow/example/myproject directory in tensorflow source location.

**Comment by dzhyeon** [comment]
My bad. building with '-c opt --config=cuda' option solved problem.

**Comment by yaroslavvb** [comment]
BTW, in the future you can use IsCudaEnabled from
tensorflow/core/util/port.cc in your tests to catch building without GPU
options, AddDevices from tensorflow/core/common_runtime/device_factory.h to
catch cases when GPUs are missing for other reasons

**Comment by maystroh** [comment]
@dzhyeon building what ? you mean rebuilding tensorflow with cuda option?

**Comment by xiaowenhe** [comment]
@dzhyeon , I also come this problem now. I build the tensorflow using bazel build -c opt --config=cuda , but I still cannot slove this problem. Can you help me?

I do like;
1   ./configure.  I choose CUDA support, and cuda 9.1 and cudnn 7 is used.
2   bazel .   bazel build -c opt --config=cuda //tensorlfow:libtensorflow_cc.so.
At last ,complete sucessfully.

My code like:

#include <tensorflow/core/protobuf/meta_graph.pb.h>
#include <tensorflow/core/public/session.h>
#include <tensorflow/core/graph/default_device.h>
#include <tensorflow/core/graph/graph_def_builder.h>

tensorflow::GraphDef GraphDef;
tensorflow::Session* Session = nullptr;

1 void LoadGraph()
2 {
3       // Read in the protobuf graph we exported
4        tensorflow::Status Status;
5
6         Status = tensorflow::ReadBinaryProto(tensorflow::Env::Default(), "my_model.pb", &GraphDef);
7 if (!Status.ok())
8 {
9         printf("Error reading graph definition from %s: %s\n", "my_model.pb", Status.ToString().c_str());
10        return false;
11 }
12
13         Session = tensorflow::NewSession(tensorflow::SessionOptions());
14 if (Session == nullptr)
15 {
16         printf("Could not create Tensorflow session.\n");
17         return false;
18 }
19
20 graph::SetDefaultDevice("/device:GPU:0",&GraphDef); ///////// I add , for use GPU

21 // Add the graph to the session
22 Status = Session->Create(GraphDef);
23 if (!Status.ok())
24 {
25        printf("Error creating graph: %s\n", Status.ToString().c_str());
26        return false;
27 }
28 }

But the code will be get an error.  Segmentation fault(core dumped)..I do not know how to deal with it.

when I do ldd libtensorflow_cc.so, the result like :
![image](https://user-images.githubusercontent.com/28335784/39849233-d4ddbabc-543d-11e8-8793-78989d1e54ac.png)

**Comment by harendra247** [comment]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): jetpack 4.3
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below):2.0.0
- Python version: 2.7
- Bazel version (if compiling from source):0.26.1
- GCC/Compiler version (if compiling from source):7.5
- CUDA/cuDNN version:10.0/7.6.3
- GPU model and memory: tegra tx2


**Describe the current behavior**
when I try running sample application it is crashing. With error logs as "CUDA runtime implicit initialization on GPU:0 failed. Status: unknown error"

**Describe the expected behavior**
it should start session

**Standalone code to reproduce the issue**
Sample Code 
```
#include <tensorflow/core/platform/env.h>
#include <tensorflow/core/public/session.h>
#include <iostream>
using namespace std;
using namespace tensorflow;

int main()
{
    Session* session;
    Status status = NewSession(SessionOptions(), &session);
    if (!status.ok()) {
        cout << status.ToString() << "\n";
    }
    session->Close();
    cout << "Session successfully created.\n";
}

```

CMakeLists.txt
```
cmake_minimum_required(VERSION 3.10)

project(test_hello)

set(TENSORFLOW_LIBRARIES tensorflow_cc protobuf)
add_executable(example example.cpp)
set(CUDA_NVCC_FLAGS
        ${CUDA_NVCC_FLAGS};
        -O3 -gencode arch=compute_30,code=sm_30;
        --std=c++11
        )
set(CMAKE_CXX_STANDARD 11)
set(CMAKE_CXX_STANDARD_REQUIRED ON)

# Link the Tensorflow library.
# TensorFlow headers
include_directories("/usr/local/include/")
include_directories("/usr/local/include/tensorflow/")
include_directories("/usr/local/include/third-party/")
target_link_libraries(example "/usr/local/lib/libtensorflow_cc.so")

# You may also link cuda if it is available.
find_package(CUDA)
if(CUDA_FOUND)
  target_link_libraries(example ${CUDA_LIBRARIES})
endif()

```

**Other info / logs**

```
$ ./example 
2020-07-08 15:01:34.122381: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1
2020-07-08 15:01:34.127413: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:973] ARM64 does not support NUMA - returning NUMA node zero
2020-07-08 15:01:34.127566: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties: 
name: NVIDIA Tegra X2 major: 6 minor: 2 memoryClockRate(GHz): 1.3
pciBusID: 0000:00:00.0
2020-07-08 15:01:34.127608: I tensorflow/stream_executor/platform/default/dlopen_checker_stub.cc:25] GPU libraries are statically linked, skip dlopen check.
2020-07-08 15:01:34.127693: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:973] ARM64 does not support NUMA - returning NUMA node zero
2020-07-08 15:01:34.127815: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:973] ARM64 does not support NUMA - returning NUMA node zero
2020-07-08 15:01:34.127879: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0
Internal: CUDA runtime implicit initialization on GPU:0 failed. Status: unknown error
Segmentation fault (core dumped)

```

**Comment by karthickai** [comment]
is this issue resolved ?
