### ISSUE TITLE
undeclared inclusion(s) in rule '//tensorflow/lite/toco/python:toco_python_api'

### ISSUE THREAD

**Issue by jiapei100** [tensorflow/tensorflow#31266]
**System information**
- OS Platform and Distribution: 19.04
- TensorFlow installed from (source or binary): 2.0beta1
- TensorFlow version: 2.0beta1
- Python version: 3.7.3
- Bazel version: 0.26.0
- GCC/Compiler version (if compiling from source): 8.3.0
- CUDA/cuDNN version: 10.1/7.6.2
- GPU architecture: 5.2 

**Describe the problem**
```console
ERROR: ....../tensorflow/tensorflow/lite/toco/python/BUILD:22:1: undeclared inclusion(s) in rule '//tensorflow/lite/toco/python:toco_python_api':
```

Any further suggestions?

**Comment by anush-o** [comment]
@jiapei100 ,
Can you please provide the exact sequence of commands / steps that you executed before running into the problem?Thanks!

**Comment by oanush** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
