### ISSUE TITLE
How to configure Tensorflow to use a specific GPU?

### ISSUE THREAD

**Issue by rezaee** [tensorflow/tensorflow#31267]
These are the activated devices that I have:

    [name: "/device:CPU:0"
    device_type: "CPU"
    memory_limit: 268435456
    locality {
    }
    incarnation: 5415837867258701517
    , name: "/device:GPU:0"
    device_type: "GPU"
    memory_limit: 3198956339
    locality {
      bus_id: 1
      links {
      }
    }
    incarnation: 12462133041849407996
    physical_device_desc: "device: 0, name: GeForce GTX 960M, pci bus id: 0000:01:00.0, compute capability: 5.0"
    ]

What I want to do is to configure my program to use `GeForce GTX 960M` and also make this configuration permanent for all my previous/future programs if is it possible?

**Comment by pzobel** [comment]
Hi,
TensorFlow automatically places operations on a GPU, if possible. As you only have one GPU in your system, it is used by default.
Find more information here: https://www.tensorflow.org/guide/using_gpu
Make sure you have TensorFlow GPU installed:
https://www.tensorflow.org/install/gpu

**Comment by rezaee** [comment]
@pzobel : Hi and thank you,
But I have two graphic cards. The first and default card is `intel hd 540` and the second card that I want to use is `Geforce GTX 960M`.

**Comment by pzobel** [comment]
Your Intel HD 540 cannot be utilized by TensorFlow. TensorFlow requires NVIDIA GPUs with CUDA Compute Capability of at least 3.5 (https://www.tensorflow.org/install/gpu). This requirement is only met by your GTX 960M.

**Comment by rezaee** [comment]
@pzobel , Thanks again!
So, how can I find if I am using GPU or CPU? Also how can I switch between them?
I feel using GPU reduced my speed instead of increasing it!

**Comment by ymodak** [comment]
- To find out which devices your operations and tensors are assigned to
```python    
tf.debugging.set_log_device_placement(True)
```

- To switch between gpu and cpu
You can use ```tf.device```
See https://www.tensorflow.org/guide/using_gpu#manual_device_placement
