### ISSUE TITLE
I have installed "tensorflos-gpu" but it doesn't work(Asus N552VW with 2 graphic cards)

### ISSUE THREAD

**Issue by rezaee** [tensorflow/tensorflow#31262]
I just installed `tensorflow-gpu` successfully. I also installed `tensorflow` after that successfully. I tried the following code on `spyder3`:

    from tensorflow.python.client import device_lib
    print(device_lib.list_local_devices())

But the result is:

    [name: "/device:CPU:0"
    device_type: "CPU"
    memory_limit: 268435456
    locality {
    }
    incarnation: 18318063967424845606
    ]

It seems the GPU version of tensorflow doesn't work! How can I fix it?

**System information**
- OS Platform and Distribution (Windows 10):
- TensorFlow installed from (pip install tensorflow/tensorflow-gpu):
- TensorFlow version: 1.14
- Python version: 3.7.3
- Installed using virtualenv? pip
- CUDA/cuDNN version: 10.1 /  7.6.2
- GPU model and memory: Geforce GTX 960M

I also must mention that my laptop has 2 graphic cards that the second card that I installed CUDA/cuDNN for that is `Geforce GTX 960M`.

I also tried the following code:

    import tensorflow as tf
    
    # Creates a graph.
    with tf.device('/device:GPU:2'):
      a = tf.constant([1.0, 2.0, 3.0, 4.0, 5.0, 6.0], shape=[2, 3], name='a')
      b = tf.constant([1.0, 2.0, 3.0, 4.0, 5.0, 6.0], shape=[3, 2], name='b')
      c = tf.matmul(a, b)
    # Creates a session with allow_soft_placement and log_device_placement set
    # to True.
    sess = tf.Session(config=tf.ConfigProto(
          allow_soft_placement=True, log_device_placement=True))
    # Runs the op.
    print(sess.run(c))

And got this result:

    [[22. 28.]
     [49. 64.]]

**Comment by ymodak** [comment]
TF fails to recognize your GPU instance.
The reason for that is, You are using cuda 10.1 along with pre-built TF-GPU binary.
The TF-GPU 1.14 prebuilt binary supports cuda 10.0
See https://www.tensorflow.org/install/gpu#software_requirements
Therefore, you need to uninstall cuda 10.1 and install cuda 10.0
Further make sure you update environment path for cuda.
See https://www.tensorflow.org/install/gpu#windows_setup

**Comment by omidhm** [comment]
I have the same setup. 
Input:
from tensorflow.python.client import device_lib
print(device_lib.list_local_devices())
Output:
[name: "/device:CPU:0"
device_type: "CPU"
memory_limit: 268435456
locality {
}
incarnation: 13583293957510262229
, name: "/device:GPU:0"
device_type: "GPU"
memory_limit: 3181130547
locality {
  bus_id: 1
  links {
  }
}
incarnation: 2244988091806553314
physical_device_desc: "device: 0, name: GeForce GTX 960M, pci bus id: 0000:01:00.0, compute capability: 5.0"
]


BUT I try to use Pytorch and when I try:
Input:
import torch
torch.cuda.is_available()
Output:
 False
