### ISSUE TITLE
Build TFLite Model Benchmark Tool with GPU delegate for iOS?

### ISSUE THREAD

**Issue by stakemura** [tensorflow/tensorflow#31261]
**System information**
- TensorFlow version (you are using):master repogitory
- Are you willing to contribute it (Yes/No):Yes

**Describe the feature and the current behavior/state.**
I'm trying to build TFLite Model Benchmark Tool with GPU delegate on iOS devices.
@freedomtan showed us the great patches for Android and some samples on #27402. I deeply appreciate his commit.
However it is still difficult for me to build the latest TFLite model benchmark tool with the latest GPU delegate. Unfortunately, building TFLite core library `libtensorflow-lite.a` and benchmark module `benchmark-lib.a` depends on the shell script `/tensorflow/lite/tools/make/build_ios_universal_lib.sh` using CMake. On the other hand, building GPU delegate module `libmetal_delegate.a` depends on bazel `//tensorflow/lite/delegates/gpu:metal_delegate`. Hence I'm puzzled. 
Would you like to provide bazel script to build TFLite Model Benchmark Tool with GPU delegate for iOS?

**Will this change the current api? How?**
No

**Who will benefit with this feature?**
Anyone using the TFLite.

**Any Other info.**

**Comment by impjdi** [comment]
@miaout17 

Could you help @stakemura set up the TFLite model benchmark for iOS?  It's a domain I'm not familiar with...

**Comment by stakemura** [comment]
@miaout17 Would you like to give me any information?
I'm still now struggling with the build. Any information are welcome.

**Comment by yyoon** [comment]
Just made a commit (f560b2745e59ac663bb554fc75304d8d3fa9d34e) for adding GPU delegate option to the benchmark tool.

Could you follow the instructions here:
https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/tools/benchmark/ios

and let me know if it works for you?

**Comment by stakemura** [comment]
@yyoon 

I succeeded to build TensorFlowLiteBenchmarkC.framework on my environment.
I thanks a lot for the great work.
In my opinion, I wish we could build TFLiteBenchmark .ipa file with the [bazel](https://docs.bazel.build/versions/master/tutorial/ios-app.html#add-an-ios_application-rule).

**Comment by yyoon** [comment]
Great. Will consider adding a bazel rule for building the app in the future.
