### ISSUE TITLE
no such file or directory -Vs Build tools 2017 no longer available

### ISSUE THREAD

**Issue by forReason** [tensorflow/tensorflow#31269]
**System information**
- OS Platform and Distribution: Windows Server 2016
- TensorFlow installed from: trying to install from source
- TensorFlow version: Current/Master
- Python version: 3.6
- Bazel version (if compiling from source): 0.26.1
- CUDA/cuDNN version: CPU only
- GPU model and memory: CPU only

**Describe the problem**
When trying to build tensorflow with bazel, the Visual Studio 2017 Build Tools cannot be located:
    C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC (No such file or directory)  

Unfortunately the Build tools for VS 2017 could no longer be located on the Microsoft Website...
VS Build tools for VS 2019 have been installed but are not supported.

**Provide the exact sequence of commands / steps that you executed before running into the problem**
bazel build --config=opt //tensorflow/tools/pip_package:build_pip_package

**Any other info / logs**
Rather a deprecation than a bug. Is there any source for 2017 Build tools available? or possibility to build with 2019 build tools?

**Comment by gadagashwini** [comment]
@forReason Please take a look at the [Microsoft website](https://visualstudio.microsoft.com/vs/older-downloads/) for VS 2017. Let us know how it progresses. Thanks!

**Comment by forReason** [comment]
https://my.visualstudio.com/Downloads?q=visual%20studio%202017&wt.mc_id=o~msft~vscom~older-downloads

thank you, this link helped.

**Comment by gadagashwini** [comment]
Are you satisfied with the resolution of your issue?<br> [Yes](https://docs.google.com/forms/d/e/1FAIpQLSfaP12TRhd9xSxjXZjcZFNXPGk4kc1-qMdv3gc6bEP90vY1ew/viewform?entry.85265664=Yes&entry.2137816233=31269)<br> [No](https://docs.google.com/forms/d/e/1FAIpQLSfaP12TRhd9xSxjXZjcZFNXPGk4kc1-qMdv3gc6bEP90vY1ew/viewform?entry.85265664=No&entry.2137816233=31269)
