### ISSUE TITLE
[TF 2.0 API Docs] tf.keras.backend.random_uniform

### ISSUE THREAD

**Issue by mwinel** [tensorflow/tensorflow#31277]
## URL(s) with the issue:
https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/keras/backend/random_uniform

## Description of issue (what needs changing):
The function has no usage example and there are no errors raised.

### Raises listed and defined
No raises listed or defined.

### Usage example
No usage example

### Submit a pull request?
No.

**Comment by zjzh** [comment]
@mwinel , Hello, why do you think that these random function need examples?
