### ISSUE TITLE
[TF 2.0 API Docs] tf.io.extract_jpeg

### ISSUE THREAD

**Issue by dannylwe** [tensorflow/tensorflow#31275]
## URL(s) with the issue:
https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/io/encode_jpeg

## Description of issue (what needs changing):
- No link to github source code provided
- No `Raises` provided in the description
- No usage example

### Correct links

No link provided

### Raises listed and defined

Raises are not defined/listed.

### Usage example

There is no usage example

### Request visuals, if applicable

Currently, no visuals, may not be required.

**Comment by Saduf2019** [comment]
@dannylwe 
Is this still an issue.

**Comment by sushreebarsa** [comment]
@dannylwe  Could you please have a look at[ this](https://www.tensorflow.org/versions/r2./api_docs/python/tf/io/encode_jpeg) updated page of the documentation for tf.io.encode_jpeg where the source code along with the example is well mentioned. It raises A Tensor of type string which is written there as well. Thank you!
