### ISSUE TITLE
[TF.2.0 API Docs] tf.train.list_variables

### ISSUE THREAD

**Issue by KabohaJeanMark** [tensorflow/tensorflow#31278]
## URL(s) with the issue:
https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/train/list_variables

## Description of the issue (what needs changing):
Raises for exceptions to deal with any errors and a few drawings to be added to make it easier to understand.

### Raises listed and defined
No, the errors are not listed and returned.

Are there currently visuals? If not, will it clarify the content?
No, there are not any current visuals.

### Submit a pull request?

No, I am not willing to submit a pull request.

**Comment by Saduf2019** [comment]
@KabohaJeanMark 
Is this still an issue.

**Comment by ymodak** [comment]
The docs are updated with TF 2.4.1 api docs.
See https://www.tensorflow.org/api_docs/python/tf/train/list_variables 
Thanks!
