### ISSUE TITLE
tf.data.Iterator complain "Function tf_data_structured_function_wrapper_xxxx is not defined."

### ISSUE THREAD

**Issue by memeda** [tensorflow/tensorflow#31270]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): **YES**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):  CentOS release 6.3 (Final)
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: -
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 1.10.0
- Python version: 2.7.14
- Bazel version (if compiling from source): -
- GCC/Compiler version (if compiling from source): -
- CUDA/cuDNN version: - (CPU)
- GPU model and memory: - (CPU)

('v1.10.0-0-g656e7a2b34', '1.10.0')

**Describe the current behavior**

As the title said, it complains 

```
NotFoundError: Function tf_data_structured_function_wrapper_qCoCAdpVJm4 is not defined.
	 [[Node: IteratorGetNext_8 = IteratorGetNext[output_shapes=[[]], output_types=[DT_INT64], _device="/job:localhost/replica:0/task:0/device:CPU:0"](Iterator_9)]]
```

I follow the sample code of [api doc](https://www.tensorflow.org/versions/r1.10/api_docs/python/tf/data/Iterator#from_structure) , **Except that I change the `tf.data.Dataset` creating place.**

In original sample code, it creates 2 datasets before run `sess.run`, while I create 1 dataset  after the other dataset has run out, and it complains.

If it is hard to understand, I'll try to describe it after the following code section.

**Describe the expected behavior**

All is ok.

**Code to reproduce the issue**

```Python
from tensorflow.data import Dataset 
from tensorflow.data import Iterator
import tensorflow as tf

iterator = Iterator.from_structure(tf.int64, tf.TensorShape([]))

def gen():
    for i in range(30):
        yield i

def model_fn(ite):
  return (ite + 1, ite + 23)

prediction, loss = model_fn(iterator.get_next())

with tf.Session() as sess:
  dataset_range = Dataset.from_generator(gen, tf.int64)
  range_initializer = iterator.make_initializer(dataset_range)

  sess.run(range_initializer)
  while True:
    try:
      pred, loss_val = sess.run([prediction, loss])
      print pred
    except tf.errors.OutOfRangeError:
      break

  dataset_evens = Dataset.from_generator(gen, tf.int64)
  evens_initializer = iterator.make_initializer(dataset_evens)

  sess.run(evens_initializer)
  while True:
    try:
      ## <------ HERE!! OH, it complaint!
      pred, loss_val = sess.run([prediction, loss])
      print pred
    except tf.errors.OutOfRangeError:
      break
```

if I change the `dataset_evens = Dataset.from_generator(gen, tf.int64)` to the place after `dataset_range = Dataset.from_generator(gen, tf.int64)`, it also will be OK.

**Other info / logs**

Explain Why I need create after `sess.run`:
because our data is generated from a generator, and I want to shuffle it at every epoch end.
The easiest way and most clear way is change the generator (let it generates data in shuffle order) at every epoch end.

Why not `repeat()`?  => Oh, it can't report the `epoch end` signal.

Has other way? => YES, I can keep only 1 generator and change the generator's inner state to shuffle, BUT it may be tricky and cause confusion?

**Comment by gadagashwini** [comment]
@memeda This is not an issue in Tensorflow 1.14.0. Would you like give try. Thanks!

**Comment by memeda** [comment]
Oh~ I'll try it~ sorry I am too lazy
