### ISSUE TITLE
[TF 2.0 API Docs] tf.nn.log_softmax

### ISSUE THREAD

**Issue by MuhanguziDavid** [tensorflow/tensorflow#31276]
##  URL(s) with the issue:
https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/nn/log_softmax

## Description of the issue (what needs changing):
- No errors defined
- No visuals

### Are the errors defined?
- There are no errors defined

### Visuals, if applicable
- There are no visuals available. I think that visuals are needed to clarify the content.

**Comment by gadagashwini** [comment]
@MuhanguziDavid, Errors are defined [here](https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/nn/log_softmax#raises). Please take look and let us know. Thanks!

**Comment by MuhanguziDavid** [comment]
@gadagashwini , seen the errors. They are well defined. Thanks.
