### ISSUE TITLE
installation problem (version `GLIBC_2.14' not found)

### ISSUE THREAD

**Issue by arashno** [tensorflow/tensorflow#3127]
Hello,
I tried to install tensorflow using pip.
It has been installed without any error.
When I am trying to use it:
import tensorflow as tf
it gives me the following error, but the requested library exists at the /lib64/.
What should I do?!
Thanks

> Traceback (most recent call last):
>   File "<string>", line 1, in <module>
>   File "/project/EvolvingAI/mnorouzz/anaconda/lib/python2.7/site-packages/tensorflow/__init__.py", line 23, in <module>
>     from tensorflow.python import *
>   File "/project/EvolvingAI/mnorouzz/anaconda/lib/python2.7/site-packages/tensorflow/python/__init__.py", line 48, in <module>
>     from tensorflow.python import pywrap_tensorflow
>   File "/project/EvolvingAI/mnorouzz/anaconda/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 28, in <module>
>     _pywrap_tensorflow = swig_import_helper()
>   File "/project/EvolvingAI/mnorouzz/anaconda/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 24, in swig_import_helper
>     _mod = imp.load_module('_pywrap_tensorflow', fp, pathname, description)
> ImportError: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /project/EvolvingAI/mnorouzz/anaconda/lib/python2.7/site-packages/tensorflow/python/_pywrap_tensorflow.so)

### Environment info
Operating System:
Linux mmmlog2 2.6.32-573.26.1.el6.x86_64 #1 SMP Tue Apr 12 01:47:01 EDT 2016 x86_64 x86_64 x86_64 GNU/Linux Red Hat

Installed version of CUDA and cuDNN: 7.5 & 5

> -rw-rw-r-- 1 jbaker2 jbaker2 189170 May 31 08:11 /apps/CUDA/cuda-7.5/lib/libcudadevrt.a
> lrwxrwxrwx 1 jbaker2 jbaker2     16 May 31 08:11 /apps/CUDA/cuda-7.5/lib/libcudart.so -> libcudart.so.7.5
> lrwxrwxrwx 1 jbaker2 jbaker2     19 May 31 08:11 /apps/CUDA/cuda-7.5/lib/libcudart.so.7.5 -> libcudart.so.7.5.18
> -rwxrwxr-x 1 jbaker2 jbaker2 311596 May 31 08:11 /apps/CUDA/cuda-7.5/lib/libcudart.so.7.5.18
> -rw-rw-r-- 1 jbaker2 jbaker2 558020 May 31 08:11 /apps/CUDA/cuda-7.5/lib/libcudart_static.a

If installed from binary pip package, provide:

I am using conda, https://storage.googleapis.com/tensorflow/linux/gpu/tensorflow-0.9.0-cp27-none-linux_x86_64.whl

The output from `python -c "import tensorflow; print(tensorflow.__version__)"`:

> Traceback (most recent call last):
>   File "<string>", line 1, in <module>
>   File "/project/EvolvingAI/mnorouzz/anaconda/lib/python2.7/site-packages/tensorflow/__init__.py", line 23, in <module>
>     from tensorflow.python import *
>   File "/project/EvolvingAI/mnorouzz/anaconda/lib/python2.7/site-packages/tensorflow/python/__init__.py", line 48, in <module>
>     from tensorflow.python import pywrap_tensorflow
>   File "/project/EvolvingAI/mnorouzz/anaconda/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 28, in <module>
>     _pywrap_tensorflow = swig_import_helper()
>   File "/project/EvolvingAI/mnorouzz/anaconda/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 24, in swig_import_helper
>     _mod = imp.load_module('_pywrap_tensorflow', fp, pathname, description)
> ImportError: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /project/EvolvingAI/mnorouzz/anaconda/lib/python2.7/site-packages/tensorflow/python/_pywrap_tensorflow.so)

**Comment by martinwicke** [comment]
This seems to be a CentOS 6 system. Its glibc is too old for the pre-built TensorFlow packages. You may be able to install from source.

**Comment by zh19970205** [comment]
But installation from source needs Bazel

Bazel needs GLIBC_2.14

What Should I do?

@martinwicke

**Comment by martinwicke** [comment]
That's why I wrote "may be able to" :(

For C++ only, you can build using the cmake or makefile in contrib. But that doesn't give you the python (as of now).

Do you have the ability to install things (like a new glibc) on these machines?

**Comment by faruihuihui** [comment]
@zh19970205 Did you solve your problem? I have the same issue...

**Comment by zh19970205** [comment]
@faruihuihui  I have not solve it yet :(, I just run tensorflow in another machine :|

**Comment by i3v** [comment]
If anyone is still running into the same problem (like I did few days ago) - it turns out to be perfectly possible to build bazel-0.4.1 and then build tensorflow 0.12rc0 from source on CentOS6.5, with glibc-2.12. However, [some tricks](https://github.com/tensorflow/tensorflow/issues/110#issuecomment-265431453) are needed.

**Comment by Hemnepal** [comment]
I had the same problem while using the mini condo, I think it might be due to not updated version. I installed Anaconda to replace mini condo and it worked. So the best way is to update your IDE.
