### ISSUE TITLE
"TypeError: expected str, bytes or os.PathLike object, not _io.BytesIO" when trying to restore a model from a byte stream in tensorflow 2.0.0-beta0

### ISSUE THREAD

**Issue by helloIAmPau** [tensorflow/tensorflow#31282]
in tensorflow version 2.0.0-alpha0 I was able to serialize and deserialize a model in memory by using the following code:

```
    def _serializeModel(self, model):
        import h5py

        with h5py.File('does not matter', driver='core', backing_store=False) as h5file:
            model.save(h5file)
            h5file.flush()
            return h5file.id.get_file_image().hex()

    def _restoreModel(self, serialized):
        from tensorflow.keras.models import load_model
        from io import BytesIO

        return load_model(BytesIO(bytes.fromhex(serialized)))
```

from tensorflow 2.0.0-beta0, instead, the `restoreModel` function throws the error:

```
  File "/usr/local/lib/python3.6/site-packages/statwolfml/models/base_model.py", line 142, in train
    self._model = self._restoreModel(self._model)
  File "/usr/local/lib/python3.6/site-packages/statwolfml/models/base_model.py", line 165, in _restoreModel
    return load_model(BytesIO(bytes.fromhex(serialized)))
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/keras/saving/save.py", line 136, in load_model
    isinstance(filepath, h5py.File) or h5py.is_hdf5(filepath))):
  File "/usr/local/lib/python3.6/site-packages/h5py/_hl/base.py", line 41, in is_hdf5
    fname = os.path.abspath(fspath(fname))
TypeError: expected str, bytes or os.PathLike object, not _io.BytesIO
```

Did you remove the support to byte stream or is this a bug?

Thanks

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): all
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: don't know
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): >= 2.0.0-beta0
- Python version: 3.6

**Comment by gadagashwini** [comment]
@helloIAmPau Will it possible to provide the full code to reproduce the reported issue. Thanks!

**Comment by helloIAmPau** [comment]
@gadagashwini sure:

```python
#! /usr/bin/env python3

import tensorflow
from tensorflow.keras.layers import Input, Dense
from tensorflow.keras.models import Model, load_model

from io import BytesIO
import h5py

inputLayer = Input(batch_shape=(None, 5, 10))
final = Dense(10)(inputLayer)

model = Model(inputs=[ inputLayer ], outputs=[ final ])
opt = tensorflow.optimizers.get({
    'class_name': 'Adam',
    'config': {}
});
model.compile(opt, loss='mean_squared_error', metrics=['mse'])

# Serialization here works fine
with h5py.File('does not matter', driver='core', backing_store=False) as h5file:
    model.save(h5file)
    h5file.flush()
    serialized = h5file.id.get_file_image().hex()

# Deserialization here throws error for tf >= 2.0.0-beta0
restored = load_model(BytesIO(bytes.fromhex(serialized)))
```

**Comment by gadagashwini** [comment]
@helloIAmPau Thanks for reproducible code.
I am able to reproduce the issue on Colab with Tensorflow 2.0.0.beta1. Please take a look at gist [here](https://colab.research.google.com/drive/1uI3_BwH-HZ94j6LT8n_xwKNtp-Y2wDh9). Thanks!

**Comment by k-w-w** [comment]
I tried running the colab with `tensorflow==2.0.0-alpha0`, but the model was still unable to be loaded. `load_model`'s docstring states that it only supports:
```
filepath: One of the following:
          - String, path to the saved model
          - `h5py.File` object from which to load the model
```

Can you try passing the h5 File object to load_model instead?

**Comment by gadagashwini** [comment]
@helloIAmPau, Did you try @k-w-w's comment.
Please close the issue if it was already resolved for you. Thanks!

**Comment by helloIAmPau** [comment]
we changed the approach in our application. we don't need the fix anymore, thanks.
