### ISSUE TITLE
conv3d_transpose -- Error in 'python': free(): invalid pointer

### ISSUE THREAD

**Issue by KendallWeihe** [tensorflow/tensorflow#3128]
I'm running into an issue with the recently added `conv3d_transpose` -- error statement in the title. The network builds, but upon first training session it outputs the above error, runs for a second, and then `Aborted (core dumped)`.  I have verified all dimensions and data. 

I wrote a simple convolutional-deconvolutional network to reproduce the bug. This small program actually outputs a different error than the network I am trying to build, but I believe it is pointing to the same issue.

The error it is outputting is: `Error in 'python': double free or corruption (out):`

I have tried running the program on two different linux (Ubuntu 14) machines. I had to install Tensorflow from the nightly builds in order to include the `conv3d_transpose` source code. I want to try and run the program on my Mac, but there isn't a build out yet that includes the function.

```
#this is a small program to reproduce the bug
    # Error in 'python': free(): invalid pointer:
    # and
    # Error in `python': double free or corruption (out):

    #the network is designed for image segmentation
        #input and outputs have the same dimensions

import tensorflow as tf
import numpy as np
import pdb

learning_rate = 0.001

n_depth = 5
n_input_x = 200
n_input_y = 200
n_classes = 2
n_examples = 3

x = tf.placeholder(tf.float32, [n_examples, n_depth, n_input_x, n_input_y])
y = tf.placeholder(tf.float32, [n_examples, n_depth, n_input_x, n_input_y, n_classes], name="ground_truth")

#generate random data
input_data = np.random.rand(n_examples, n_depth, n_input_x, n_input_y)
label_data = np.random.rand(n_examples * n_depth * n_input_x * n_input_y, n_classes)

weights = {
    'l1': tf.Variable(tf.random_normal([5, 5, 5, 1, 32])),
    'l2': tf.Variable(tf.random_normal([3, 2, 2, 2, 32]))
}

biases = {
    'l1': tf.Variable(tf.random_normal([32])),
    'l2': tf.Variable(tf.random_normal([2]))
}

#build network
def conv(x, w, b):
    #one convolutional layer followed by one deconvolutional layer
    x = tf.reshape(x, shape=[-1, n_depth, n_input_x, n_input_y, 1])

    conv1 = tf.nn.conv3d(x, weights['l1'], strides=[1,1,1,1,1], padding="SAME")
    conv1 = tf.nn.bias_add(conv1, biases['l1'])
    conv1 = tf.nn.relu(conv1)
    conv1 = tf.nn.max_pool3d(conv1, ksize=[1,2,2,2,1], strides=[1,2,2,2,1], padding="SAME")

    output_shape = [n_examples, n_depth, n_input_x, n_input_y, n_classes]
    deconv1 = tf.nn.conv3d_transpose(conv1, weights['l2'], output_shape=output_shape, strides=[1,1,2,2,1], padding="VALID")
    deconv1 = tf.nn.bias_add(deconv1, biases['l2'])

    return deconv1

pred = conv(x, weights, biases)

#reshape for classification
temp_pred = tf.reshape(pred, [-1,n_classes])
temp_y = tf.reshape(y, [-1,n_classes])

#define loss & optimizer
cost = tf.nn.softmax_cross_entropy_with_logits(temp_pred, temp_y)
optimizer = tf.train.AdamOptimizer(learning_rate=learning_rate).minimize(cost)
init = tf.initialize_all_variables()

#train
with tf.Session() as sess:
    sess.run(init)
    sess.run(optimizer, feed_dict={x: input_data, temp_y: label_data})

```

**Comment by andydavis1** [comment]
Looks like this came in from https://github.com/tensorflow/tensorflow/pull/3049

@daeyun can you take a look?

**Comment by KendallWeihe** [comment]
Any update on this @daeyun ?

**Comment by daeyun** [comment]
@KendallWeihe I'm unable to reproduce the error, it seems to run without any error. Have you tried running a 2D version of this? Are you using GPU or CPU? I installed from sources with cuda 7.5, cuDNN 5.1.3, python 3.5 (anaconda), ubuntu 14.04.

**Comment by KendallWeihe** [comment]
I'm currently trying to install python 3.5, but the nightly builds are 404 https://github.com/tensorflow/tensorflow/issues/3196#issuecomment-230926570

**Comment by KendallWeihe** [comment]
I have installed tensorflow for python 3.4 and I'm still getting the same error `*** Error in `python3.4': free(): invalid pointer: 0x00007f98bf2eb0b0 ***` 

Still trying to install for python 3.5, but the nightly builds for 3.5 install for 3.4.

**Comment by KendallWeihe** [comment]
Ok I have successfully installed Python 3.5, but the error still exists. `*** Error in `python3.5': free(): invalid pointer: 0x00007f09bc3cde30 ***
Aborted (core dumped)`

I'm installed with the latest nightly build [here](http://ci.tensorflow.org/view/Nightly/job/nightly-python35-linux-cpu/)  for CPU, python 3.5.2, and ubuntu 14.04. Can you test this setup?

**Comment by KendallWeihe** [comment]
Pinging @daeyun again on this. @andydavis1 can you try to recreate this issue? You just need to copy and paste the example code I have given. Are you training with a CPU or a GPU?

**Comment by KendallWeihe** [comment]
@daeyun I tested on Mac OS, CPU, Python 3.5. It trains for one iteration and then seg faults. It is probably a similar problem as this issue -- memory running out because it isn't able to `free()`

**Comment by gravity1989** [comment]
Why is this issue closed?

Think this issue still persists?

**Comment by was84san** [comment]
is there any solution for this issue ?

**Comment by KendallWeihe** [comment]
I have not tested this in a while, but the last time I tested it, the bug was still present. I have since upgraded to training on a GPU and that fixed the issue. If someone can confirm that this is still a bug, then this issue needs to be reopened, or just open a new issue and reference this one.

**Comment by drpngx** [comment]
@KendallWeihe please open a new one referencing this one and CC me and @gunan on this.

We test a lot of our code with asan and msan, but if this fell through the cracks that's a really important issue for us.

**Comment by brando90** [comment]
I found this issue happened in my docker container using tensorflow 1.0.0 `gcr.io/tensorflow/tensorflow:1.0.0-devel-py3`. Is this the source of the problem? Was 1.0.0 suppose to fix it? I'm unsure what to do to fix this.

**Comment by AlexGreason** [comment]
I am also having this problem using the bleeding-edge version of theano (as of july 6)
