### ISSUE TITLE
Tensorflow graph execution does not give expected result.

### ISSUE THREAD

**Issue by asispatra** [tensorflow/tensorflow#31283]
I am using `Tesla V100-PCIE-16GB` GPU on my system and using tensorflow version 1.13.1 .
I have two python example script. `example-1.py` runs fine. `example-2.py` contains same statements as `example-1.py` but multiple times. `example-2.py` fails with GPU OOM error. Because it transfer all the matrix data to the GPU initially.

### example-1.py
```
import tensorflow as tf
import time

N=20000
m=N
n=N
k=N

tf.random.set_random_seed(1234)
with tf.device('/cpu:0'):
  a1=tf.random.normal([m, k])
  b1=tf.random.normal([k, n])

  a2=tf.random.normal([m, k])
  b2=tf.random.normal([k, n])

with tf.device('/gpu:0'):
  c1=tf.matmul(a1, b1)
  c2=tf.matmul(a2, b2)

with tf.device('/cpu:0'):
  RESULT=tf.concat([c1, c2], 0)

sess = tf.Session(config=tf.ConfigProto(log_device_placement=True))
start=time.time()
a_out=sess.run(RESULT)
print(a_out.shape)
print("Time Taken: %s" % str(time.time() - start))
```

### example-2.py
```
import tensorflow as tf
import time

N=20000
m=N
n=N
k=N

tf.random.set_random_seed(1234)
with tf.device('/cpu:0'):
  a1=tf.random.normal([m, k])
  b1=tf.random.normal([k, n])

  a2=tf.random.normal([m, k])
  b2=tf.random.normal([k, n])

with tf.device('/gpu:0'):
  c1=tf.matmul(a1, b1)
  c2=tf.matmul(a2, b2)

with tf.device('/cpu:0'):
  RESULT=tf.concat([c1, c2], 0)

with tf.device('/cpu:0'):
  a3=tf.random.normal([m, k])
  b3=tf.random.normal([k, n])

  a4=tf.random.normal([m, k])
  b4=tf.random.normal([k, n])

with tf.device('/gpu:0'):
  c3=tf.matmul(a3, b3)
  c4=tf.matmul(a4, b4)

with tf.device('/cpu:0'):
  tmp=tf.concat([c3, c4], 0)
  RESULT=tf.concat([RESULT, tmp], 0)

with tf.device('/cpu:0'):
  a5=tf.random.normal([m, k])
  b5=tf.random.normal([k, n])

  a6=tf.random.normal([m, k])
  b6=tf.random.normal([k, n])

with tf.device('/gpu:0'):
  c5=tf.matmul(a5, b5)
  c6=tf.matmul(a6, b6)

with tf.device('/cpu:0'):
  tmp=tf.concat([c5, c6], 0)
  RESULT=tf.concat([RESULT, tmp], 0)

sess = tf.Session(config=tf.ConfigProto(log_device_placement=True))
start=time.time()
a_out=sess.run(RESULT)
print(a_out.shape)
print("Time Taken: %s" % str(time.time() - start))
```

### Other Details:
```
$ python --version
Python 3.6.8 :: Anaconda, Inc.
$ python -c 'import tensorflow as tf; print(tf.__version__)'
1.13.1
$ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.2 LTS"
```

Thanks.

**Comment by ravikyram** [comment]
I have tried on colab with TF version 1.13.1 and was able to reproduce the issue.Please, find the [gist ](https://colab.research.google.com/drive/1xqa5oMMosbVUpbuNsdpyhDGrN8ql_bFG)here. Thanks!

**Comment by asispatra** [comment]
`help wanted`

**Comment by jvishnuvardhan** [comment]
@asispatra Please check the detailed description on [performance of TF](https://www.tensorflow.org/guide/performance/overview) and [`using_gpu`](https://www.tensorflow.org/guide/using_gpu) on its website. There are many other resources on GitHub, Stackoverflow and elsewhere.

This is not Build/Installation or Bug/Performance issue. Please post this kind of support questions at [Stackoverflow](https://stackoverflow.com/questions/tagged/tensorflow). There is a big community to support and learn from your questions. GitHub is mainly for addressing bugs in installation and performance. Thanks!

**Comment by asispatra** [comment]
@jvishnuvardhan, Thanks for pointing me to `performance of TF`, `using_gpu` and `Tf data pipeline`. In this issue I am not talking about `Build/Installation` or `Bug/Performance`.

Through the example i have just tried to show that in that particular case `example-2.py`, using tensorflow I may get GPU OOM error. Even this may occur for small size data where number of matrix multiplication will be more.

I have asked the same question in the `big community` 5 days back. but have not get any reply.
https://stackoverflow.com/questions/57330969/tensorflow-graph-execution-does-not-give-expected-result

Thanks.

**Comment by jvishnuvardhan** [comment]
@asispatra Your `example-2.py` needs to be modified for performance through data pipeline. Please follow example in TF website and other places. I hope community will respond to you soon or else we might answer there. I am closing the issue here. Thanks!
