### ISSUE TITLE
tf.gradients with unconnected_gradients="zero" returns wrong shape for unconnected resource variables

### ISSUE THREAD

**Issue by cooijmanstim** [tensorflow/tensorflow#31297]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): no
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux 5.2.1-arch1-1-ARCH x86_64
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): v1.14.0-rc1-22-gaf24dc91b5
- Python version: 3.6.8
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

**Describe the current behavior**
Calling `tf.gradients` with `unconnected_gradients="zero"` returns scalars for unconnected resource variables.

**Describe the expected behavior**
Calling `tf.gradients` with `unconnected_gradients="zero"` returns appropriately shaped zero tensors for unconnected resource variables.

**Code to reproduce the issue**
```python
a = tf.Variable(initial_value=[2., 3.])
b = tf.Variable(initial_value=[3., 4.], use_resource=True)
c = tf.constant(0.)
print(tf.gradients(c, [a, b], unconnected_gradients="zero"))
# => [<tf.Tensor 'zeros_like:0' shape=(2,) dtype=float32>,
#     <tf.Tensor 'zeros_like_1:0' shape=() dtype=float32>]
```

**Comment by gadagashwini** [comment]
Could able to reproduce the issue on Colab with Tensorflow 1.14.0. Please find the gist [here](https://colab.research.google.com/drive/1Kt85ANNP_7Hy1HCVcPSfgSHN0ogRuTzX). Thanks!

**Comment by alextp** [comment]
@saxenasaurabh I think you improved inferred gradient shape of variables recently in another place; is the same fix applicable here?
