### ISSUE TITLE
Lower performance when use multi gpu

### ISSUE THREAD

**Issue by HLSS-Hen** [tensorflow/tensorflow#31299]
**System information**
-Windows 10 1903 workstation x64
-ASRock X570 Taichi
-AMD Ryzen 3700x
-Corsair 8GB LPX 3000MHz RAM x4 (32GB Tot.)
-GIGABYTE RTX 2080ti Turbo 11G x2 (with out nvlink)
-SAMSUNG PM981 256GB NVMe SSD For System and DataSet
-Cuda 10.0.130, cuDNN 7.6.0
-python 3.7.4 x64

**Describe the current behavior**
When I use three examples from doc about train keras model with multi gpus, it used more time than single gpu.
Should I buy a NVLink or change the code.
On example please if need change the code.

**Code**
```
import os
import tensorflow as tf
from DataSets import Imagenet
from Models import efficientnet

tf_config = tf.ConfigProto()
tf_config.gpu_options.allow_growth = True
with tf.Session(config=tf_config) as sess:
    model = efficientnet.efficientnet_b7(1000)
    model.summary()
    model.load_weights('/Models/efficientnet_b7')
    model = tf.keras.utils.multi_gpu_model(model,2, cpu_merge=False)
    model.compile('sgd', 'sparse_categorical_crossentropy', ['accuracy'])
    train_ds, test_ds = Imagenet.classification_dataset(6,100,True,[224,224,3])
    while True:
        model.fit(train_ds,
                  epochs=int(Imagenet.train_images/50000),
                  steps_per_epoch=10000,
                  callbacks=[tf.keras.callbacks.ModelCheckpoint('/Models/efficientnet_b7','loss',save_best_only=True,save_weights_only=True,mode='min')])
        model.evaluate(test_ds,steps=int(Imagenet.test_images/5))
```

**Other info / logs**

> 2019-08-03 12:25:38.658805: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
> 2019-08-03 12:25:38.665648: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library nvcuda.dll
> 2019-08-03 12:25:39.153806: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1640] Found device 0 with properties: 
> name: GeForce RTX 2080 Ti major: 7 minor: 5 memoryClockRate(GHz): 1.545
> pciBusID: 0000:0e:00.0
> 2019-08-03 12:25:39.158542: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1640] Found device 1 with properties:
> name: GeForce RTX 2080 Ti major: 7 minor: 5 memoryClockRate(GHz): 1.545
> pciBusID: 0000:0f:00.0
> 2019-08-03 12:25:39.171135: I tensorflow/stream_executor/platform/default/dlopen_checker_stub.cc:25] GPU libraries are statically linked, skip dlopen check.
> 2019-08-03 12:25:39.174610: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1763] Adding visible gpu devices: 0, 1
> 2019-08-03 12:25:40.496910: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1181] Device interconnect StreamExecutor with strength 1 edge matrix:
> 2019-08-03 12:25:40.500248: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1187]      0 1
> 2019-08-03 12:25:40.501954: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1200] 0:   N N
> 2019-08-03 12:25:40.503661: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1200] 1:   N N
> 2019-08-03 12:25:40.506310: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1326] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 8694 MB memory) -> physical GPU (device: 0, name: GeForce RTX 2080 Ti, pci bus id: 0000:0e:00.0, compute capability: 7.5)
> 2019-08-03 12:25:40.522921: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1326] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:1 with 8695 MB memory) -> physical GPU (device: 1, name: GeForce RTX 2080 Ti, pci bus id: 0000:0f:00.0, compute capability: 7.5)

**Comment by HLSS-Hen** [comment]
Some details:
-When use mult_gpu_mode, the dataset batch doesn't distribute to two cards. The warning info shows it just copy one to another.
-In mult_gpu_mode, gpu0 cudas use about 50% and 7% to gpu1. When use single card it used about 97%.

**Comment by ppwwyyxx** [comment]
`multi_gpu_mode` is slow on multiple GPUs -- just avoid using it for multi-GPU training.
You can see at [here](https://github.com/tensorpack/benchmarks/tree/master/other-wrappers) how much speedup you can get by implementing multiple GPU training in a more efficient way.

**Comment by HLSS-Hen** [comment]
> multi_gpu_mode is slow on multiple GPUs -- just avoid using it for multi-GPU training.
> You can see at here how much speedup you can get by implementing multiple GPU training in a more efficient way.

### **Thanks, but it didn't solve the problem.**
### **Here are the warning**

### Single GPU
> 2019-08-04 10:38:50.586762: W tensorflow/core/common_runtime/bfc_allocator.cc:237] Allocator (GPU_0_bfc) ran out of memory trying to allocate 3.22GiB with freed_by_count=0. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory were available.
> 2019-08-04 10:38:50.591843: W tensorflow/core/common_runtime/bfc_allocator.cc:237] Allocator (GPU_0_bfc) ran out of memory trying to allocate 3.22GiB with freed_by_count=0. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory were available.
> 2019-08-04 10:38:50.663687: W tensorflow/core/common_runtime/bfc_allocator.cc:237] Allocator (GPU_0_bfc) ran out of memory trying to allocate 3.54GiB with freed_by_count=0. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory were available.
> 2019-08-04 10:38:50.668414: W tensorflow/core/common_runtime/bfc_allocator.cc:237] Allocator (GPU_0_bfc) ran out of memory trying to allocate 3.54GiB with freed_by_count=0. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory were available.
> 2019-08-04 10:38:50.682640: W tensorflow/core/common_runtime/bfc_allocator.cc:237] Allocator (GPU_0_bfc) ran out of memory trying to allocate 3.58GiB with freed_by_count=0. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory were available.
> 2019-08-04 10:38:50.687666: W tensorflow/core/common_runtime/bfc_allocator.cc:237] Allocator (GPU_0_bfc) ran out of memory trying to allocate 3.58GiB with freed_by_count=0. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory were available.
> 2019-08-04 10:38:50.700564: W tensorflow/core/common_runtime/bfc_allocator.cc:237] Allocator (GPU_0_bfc) ran out of memory trying to allocate 3.52GiB with freed_by_count=0. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory were available.
> 2019-08-04 10:38:50.706184: W tensorflow/core/common_runtime/bfc_allocator.cc:237] Allocator (GPU_0_bfc) ran out of memory trying to allocate 3.52GiB with freed_by_count=0. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory were available.
> 2019-08-04 10:38:50.801138: W tensorflow/core/common_runtime/bfc_allocator.cc:237] Allocator (GPU_0_bfc) ran out of memory trying to allocate 3.18GiB with freed_by_count=0. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory were available.
> 2019-08-04 10:38:50.806526: W tensorflow/core/common_runtime/bfc_allocator.cc:237] Allocator (GPU_0_bfc) ran out of memory trying to allocate 3.18GiB with freed_by_count=0. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory were available.
>    27/10000 [..............................] - ETA: 2:41:29 - loss: 6.8965 - acc: 0.1815Traceback (most recent call last):

### Multi:

> W0804 10:39:48.921536  5668 deprecation.py:323] From C:\Users\HLSS\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\ops\math_grad.py:1250: add_dispatch_support.<locals>.wrapper (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
> Instructions for updating:
> Use tf.where in 2.0, which has the same broadcast rule as np.where
> 2019-08-04 10:40:36.255884: W tensorflow/core/common_runtime/bfc_allocator.cc:237] Allocator (GPU_0_bfc) ran out of memory trying to allocate 3.55GiB with freed_by_count=0. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory were available.
> 2019-08-04 10:40:36.262362: W tensorflow/core/common_runtime/bfc_allocator.cc:237] Allocator (GPU_0_bfc) ran out of memory trying to allocate 3.55GiB with freed_by_count=0. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory were available.
> 2019-08-04 10:40:36.269665: W tensorflow/core/common_runtime/bfc_allocator.cc:237] Allocator (GPU_0_bfc) ran out of memory trying to allocate 3.55GiB with freed_by_count=0. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory were available.
> 2019-08-04 10:40:36.278412: W tensorflow/core/common_runtime/bfc_allocator.cc:237] Allocator (GPU_0_bfc) ran out of memory trying to allocate 3.55GiB with freed_by_count=0. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory were available.
> 2019-08-04 10:40:36.295469: W tensorflow/core/common_runtime/bfc_allocator.cc:237] Allocator (GPU_0_bfc) ran out of memory trying to allocate 3.52GiB with freed_by_count=0. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory were available.
> 2019-08-04 10:40:36.302160: W tensorflow/core/common_runtime/bfc_allocator.cc:237] Allocator (GPU_0_bfc) ran out of memory trying to allocate 3.52GiB with freed_by_count=0. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory were available.
> 2019-08-04 10:40:36.308701: W tensorflow/core/common_runtime/bfc_allocator.cc:237] Allocator (GPU_0_bfc) ran out of memory trying to allocate 3.52GiB with freed_by_count=0. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory were available.
> 2019-08-04 10:40:36.315426: W tensorflow/core/common_runtime/bfc_allocator.cc:237] Allocator (GPU_0_bfc) ran out of memory trying to allocate 3.52GiB with freed_by_count=0. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory were available.
> 2019-08-04 10:40:36.351322: W tensorflow/core/common_runtime/bfc_allocator.cc:237] Allocator (GPU_0_bfc) ran out of memory trying to allocate 1.36GiB with freed_by_count=0. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory were available.
> 2019-08-04 10:40:36.357775: W tensorflow/core/common_runtime/bfc_allocator.cc:237] Allocator (GPU_0_bfc) ran out of memory trying to allocate 1.36GiB with freed_by_count=0. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory were available.
>     9/10000 [..............................] - ETA: 18:53:10 - loss: 5.5566 - acc: 0.4889Traceback (most recent call last):

**Comment by rmothukuru** [comment]
@HLSS-Hen ,
Can you please provide below details.

- TensorFlow installed from (source or binary):
- TensorFlow version (use command below):

Thanks!

**Comment by rmothukuru** [comment]
@HLSS-Hen ,
Can you please let us know the Version of Tensorflow you are using so that we can reproduce the issue and can work towards its resolution.

**Comment by HLSS-Hen** [comment]
@rmothukuru 
installed from pip (alliyun source)
version:1.14.0

**Comment by HLSS-Hen** [comment]
@rmothukuru @ppwwyyxx 
I bought a nvlink and use `tf.distribute`.
Now I get recently double performance(it just about 160% performance without nvlink). 

Codes:
```
import os
import tensorflow as tf
from DataSets import CIFAR100
from Models import efficientnet

strategy = tf.distribute.MirroredStrategy(cross_device_ops=tf.distribute.HierarchicalCopyAllReduce())
with strategy.scope():
    tf_config = tf.ConfigProto()
    tf_config.gpu_options.allow_growth = True
    with tf.Session(config=tf_config) as sess:
        model =efficientnet.efficientnet_b7(1000)
        model.summary()
        model.compile(tf.keras.optimizers.Adam(), 
                      tf.keras.losses.SparseCategoricalCrossentropy(),
                      [tf.keras.metrics.SparseTopKCategoricalAccuracy(1, 'top1'), tf.keras.metrics.SparseTopKCategoricalAccuracy(5, 'top5')])
        train_ds, test_ds = CIFAR100.Basic_Dataset(10, 100, [224, 224, 3])
        while True:
            model.fit(train_ds,
                      epochs=1,
                      steps_per_epoch=int(CIFAR100.train_images/10),
                      validation_data=test_ds,
                      validation_steps=int(CIFAR100.test_images/10),
                      callbacks=[tf.keras.callbacks.ModelCheckpoint('/Models/efficientnet_b7', save_best_only=True,save_weights_only=True)])
```

**Comment by caisq** [comment]
I'm the wrong person to own this bug. Tentatively assigning the bug to @guptapriya, who leads tf.distribute.
