### ISSUE TITLE
Parallel sessions for Comp Graph editing and optimization

### ISSUE THREAD

**Issue by Uiuran** [tensorflow/tensorflow#31305]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using): 1.14
- Are you willing to contribute it (Yes/No):
yes

**Describe the feature and the current behavior/state.**
It dosnt seen to be possible to do this in Tensorflow. Ive read that pyTorch has this ability although never tested it since iam developing in Tensorflow for a couple of months now (and Tensorflow has a handful of libs and other langs api what make me not want to go test the other frame)

**Will this change the current api? How?**
Maybe, i dont know really, i wanna you opinion if it will change the API and if it is desirable.

**Who will benefit with this feature?**
Although the infra host machine has to be very powerful it's really a benefit to have a ability to change your comp graph on the fly while the other graph trains, it speeds up the researching process.

**Any Other info.**
Iam not talking about editing the same graph that is optimizing, but editing one instance diverse of graph then that one that is optimizing

**Comment by ravikyram** [comment]
@Uiuran 

Can you please elaborate the context.Will it be possible to provide related code.Can you provide more details about any use-case for this feature? Thanks!

**Comment by Uiuran** [comment]
Soon enough.

Just optimizing for initialization and signal namescope wiring (got an mkldnn error related to the comp graph wiring probably, but was unable to reproduce in a simplistic code fashion, so i think is an unexpected wiring problem, and i dont wanna to do the downgrade thing).

**Comment by Uiuran** [comment]
Update: 
1- API that encloses session must refers to diverse default var collections and graph defs. 
2- Default GraphKeys  ('__varscope',) and  ('__var_store',) is ready for that since the second element of the key tuple could be a tag or number for the different graph.

This name/graph-editing feature request is also present in the following issue

https://github.com/tensorflow/tensorflow/issues/30991#

**Comment by kkimdev** [comment]
@jaingaurav Do you know any context regrading this?

**Comment by Uiuran** [comment]
@kkimdev @jaingaurav  The following can clarify:
Although Variables are created to be shared to as much sessions are necessary (for example, distributing and saving/reloading), it still not possible to copy them with graph connectivity information, rename variable scope, add to renamed collection, add to the standard graph and then restart the session. 

That is, resuming all the said above, the variable and graph creation are not dynamical as it could be. 

It does make harder to create some small packages of graphs, say, a gated RNN, and them save it and reproduce, readd in the same graph but with diverse var scope name, such (variable_scopes,['gated_rnn_0','gated_rnn_1','gated_rnn_2',...]).

Hope this clarify what iam talking about.

**Comment by mdanatg** [comment]
@Uiuran if I correctly understand your requirements, are you looking for ways to create identical copies of the same graph, and have these copies share variables?

**Comment by Uiuran** [comment]
That's right, but i add that one of these copies would be in training session and another of the copies is being edited to give a new version (e.g a memory optimized one) or maybe a complete new arch that surpass the one being optimized. One aim achievable is to compose one Network based on the evidence of the training of another, useful if you have enough hardware to not have to wait the full validation (or you can try to early validate if you thing is meaning).

**Comment by mdanatg** [comment]
This should be achievable using tf.function. For example like so, to show a minimal example that just prints a tensor:

```
v = tf.Variable(1)

@tf.function
def f(name, v):  # helps create different subgraphs, see below
  with tf.name_scope(name):
    tf.print(v)

print(f.get_concrete_function('graph1', v).graph.as_graph_def())
print(f.get_concrete_function('graph2', v).graph.as_graph_def())  # because name has a new Python value, a second graph is created

f('graph1', v)  # invokes the first subgraph
f('graph12, v)  # invokes the second subgraph
```

See the latest [API docs](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/eager/def_function.py#L989) explaining the mechanism above in more detail.

Would this work for your purpose?

**Comment by Uiuran** [comment]
This is 2.0 feature ? 
Still have to test it.  In mean-time, my question is: Does with this function iam able to edit graph12 while changing the variable values in a session in graph1 ? Then change variable value in the graph12 (e.g. training) without changing graph1 weights.
Iam not sure that sharing variables achieve what iam asking

**Comment by mdanatg** [comment]
In that case it appears the you don't need variable sharing. Rather, something like this:

```
v1 = tf.Variable(...)
v2 = tf.Variable(...)

f('graph1', v1)
f('graph2', v2)
```

Then the two graphs operate on entirely different variables and if any sharing was needed, you'd need to manually assign values to the respective variables.

**Comment by Saduf2019** [comment]
@Uiuran
Please update as per above comment.
