### ISSUE TITLE
Change `kernel_initializer` in some `tf.keras` layers for improved performance

### ISSUE THREAD

**Issue by AakashKumarNain** [tensorflow/tensorflow#31303]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):16.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.0
- Python version: 3.6
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 10
- GPU model and memory: P100

**Describe the current behavior**
The current `Conv2D` and `dense` layers in the `tf.keras` package have `glorot_uniform` as the default kernel initializer which doesn't play well with advanced activations like `relu`, `prelu`, `selu`, etc.  Given the fact that `relu` is a default choice for modern architectures, the kernel should be initialized from a different distribution.

**Describe the expected behavior**
The `kernel initializer` should be changed to `he_uniform` in `Conv`, `SeparableConv`, `DepthwiseConv` and `Dense` layers from this

```
__init__(
    filters,
    kernel_size,
    strides=(1, 1),
    padding='valid',
    data_format=None,
    dilation_rate=(1, 1),
    activation=None,
    use_bias=True,
    kernel_initializer='glorot_uniform',
    bias_initializer='zeros',
    kernel_regularizer=None,
    bias_regularizer=None,
    activity_regularizer=None,
    kernel_constraint=None,
    bias_constraint=None,
    **kwargs
)
```

to this
```
__init__(
    filters,
    kernel_size,
    strides=(1, 1),
    padding='valid',
    data_format=None,
    dilation_rate=(1, 1),
    activation=None,
    use_bias=True,
    kernel_initializer='he_uniform',
    bias_initializer='zeros',
    kernel_regularizer=None,
    bias_regularizer=None,
    activity_regularizer=None,
    kernel_constraint=None,
    bias_constraint=None,
    **kwargs
)
```

**Other info / logs**
Here are the resources that you can look into:
1) The original paper for `Kaiming init`: https://arxiv.org/pdf/1502.01852.pdf
2) Blog post: https://towardsdatascience.com/why-default-cnn-are-broken-in-keras-and-how-to-fix-them-ce295e5e5f2
3) Blog post: https://towardsdatascience.com/weight-initialization-in-neural-networks-a-journey-from-the-basics-to-kaiming-954fb9b47c79

**Comment by robieta** [comment]
This would be backward incompatible, but it might be worth considering for 2.0 as the justification seems fairly strong. @fchollet WDYT?
