### ISSUE TITLE
bazel build benchmark_model for android_arm failed In MacOS

### ISSUE THREAD

**Issue by Mycaster** [tensorflow/tensorflow#31302]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): 
macOS
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
source
- TensorFlow version:
1.14.0
- Python version:
3.5
- Installed using virtualenv? pip? conda?:
anconda
- Bazel version (if compiling from source):
0.24.1
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
clang-1001.0.46.4
- GPU model and memory:

**Describe the problem**
bazel build benchmark_model for android_arm failed In MacOS
**Provide the exact sequence of commands / steps that you executed before running into the problem**

bazel build -c opt --config=android_arm   tensorflow/lite/tools/benchmark:benchmark_model --verbose_failures

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

it seems cannot find /bin/false,  but I found the file /usr/bin/false 
so I tried:  ln -s /bin/false /usr/bin/false ,  but It's not permitted
Then I replace  /bin/false  to /usr/bin/false in total workspace and bazel clean &&  rebuild ,
It' s still not work.
 it's only worked when I remove the  --config=android_arm

==============================================
bazel build -c opt --config=android_arm   tensorflow/lite/tools/benchmark:benchmark_model --verbose_failures
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=1 --terminal_columns=125
INFO: Reading rc options for 'build' from /Users/80256276/workspace/github/tensorflow/.bazelrc:
  'build' options: --apple_platform_type=macos --define framework_shared_object=true --define=use_fast_cpp_protos=true --define=allow_oversize_protos=true --spawn_strategy=standalone --strategy=Genrule=standalone -c opt --announce_rc --define=grpc_no_ares=true --define=PREFIX=/usr --define=LIBDIR=$(PREFIX)/lib --define=INCLUDEDIR=$(PREFIX)/include
INFO: Reading rc options for 'build' from /Users/80256276/workspace/github/tensorflow/.tf_configure.bazelrc:
  'build' options: --action_env PYTHON_BIN_PATH=/Users/80256276/workspace/anaconda3/envs/tensorflow-debug/bin/python --action_env PYTHON_LIB_PATH=/Users/80256276/workspace/anaconda3/envs/tensorflow-debug/lib/python3.5/site-packages --python_path=/Users/80256276/workspace/anaconda3/envs/tensorflow-debug/bin/python --action_env TF_CONFIGURE_IOS=0
INFO: Found applicable config definition build:android_arm in file /Users/80256276/workspace/github/tensorflow/.bazelrc: --config=android --cpu=armeabi-v7a --fat_apk_cpu=armeabi-v7a
INFO: Found applicable config definition build:android in file /Users/80256276/workspace/github/tensorflow/.bazelrc: --crosstool_top=//external:android/crosstool --host_crosstool_top=@bazel_tools//tools/cpp:toolchain
INFO: Build options --cpu, --crosstool_top, and --host_crosstool_top have changed, discarding analysis cache.
INFO: Analysed target //tensorflow/lite/tools/benchmark:benchmark_model (0 packages loaded, 1610 targets configured).
INFO: Found 1 target...
ERROR: /Users/80256276/workspace/github/tensorflow/tensorflow/lite/experimental/ruy/BUILD:136:1: C++ compilation of rule '//tensorflow/lite/experimental/ruy:blocking_counter' failed (Exit 1): false failed: error executing command 
  (cd /private/var/tmp/_bazel_80256276/20fdfdd4dfe4794de5bc0e54eeed4611/execroot/org_tensorflow && \
  exec env - \
    PATH=/Users/80256276/workspace/anaconda3/condabin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin:/usr/local/go/bin:/Users/80256276/Library/Android/sdk/platform-tools:/Users/80256276/workspace/anaconda3/bin \
    PWD=/proc/self/cwd \
    PYTHON_BIN_PATH=/Users/80256276/workspace/anaconda3/envs/tensorflow-debug/bin/python \
    PYTHON_LIB_PATH=/Users/80256276/workspace/anaconda3/envs/tensorflow-debug/lib/python3.5/site-packages \
    TF_CONFIGURE_IOS=0 \
  /bin/false -MD -MF bazel-out/armeabi-v7a-opt/bin/tensorflow/lite/experimental/ruy/_objs/blocking_counter/blocking_counter.d '-frandom-seed=bazel-out/armeabi-v7a-opt/bin/tensorflow/lite/experimental/ruy/_objs/blocking_counter/blocking_counter.o' -iquote . -iquote bazel-out/armeabi-v7a-opt/genfiles -iquote bazel-out/armeabi-v7a-opt/bin -c tensorflow/lite/experimental/ruy/blocking_counter.cc -o bazel-out/armeabi-v7a-opt/bin/tensorflow/lite/experimental/ruy/_objs/blocking_counter/blocking_counter.o)
Execution platform: @bazel_tools//platforms:host_platform
src/main/tools/process-wrapper-legacy.cc:58: "execvp(/bin/false, ...)": No such file or directory
Target //tensorflow/lite/tools/benchmark:benchmark_model failed to build
INFO: Elapsed time: 0.471s, Critical Path: 0.05s
INFO: 0 processes.
FAILED: Build did NOT complete successfully

**Comment by jdduke** [comment]
@srjoglekar246 could you take a look?

**Comment by srjoglekar246** [comment]
Apparently these errors are seen when Bazel has issues finding the right executables (I guess the NDK compiler in this case). Quoting from the answer [here](https://stackoverflow.com/questions/41487069/build-error-with-tensorflow-android-demo/42614810):

> You'll need to also edit your WORKSPACE file with your NDK and SDK settings according to the directions at https://github.com/tensorflow/tensorflow/tree/master/tensorflow/examples/android. /bin/false errors are typically seen when Bazel can't find the appropriate executable to run, in this case the ndk gcc compiler.

Could you try the suggested procedure and report if it works?

**Comment by Mycaster** [comment]
> Apparently these errors are seen when Bazel has issues finding the right executables (I guess the NDK compiler in this case). Quoting from the answer [here](https://stackoverflow.com/questions/41487069/build-error-with-tensorflow-android-demo/42614810):
> 
> > You'll need to also edit your WORKSPACE file with your NDK and SDK settings according to the directions at https://github.com/tensorflow/tensorflow/tree/master/tensorflow/examples/android. /bin/false errors are typically seen when Bazel can't find the appropriate executable to run, in this case the ndk gcc compiler.
> 
> Could you try the suggested procedure and report if it works?

Tried again as you say , /bin/false error has been solved. 
but  another error occurs. seems like  c++ version and ndk version problems .
thank you very much !
