### ISSUE TITLE
A correct way to use tf.contrib.opt.AdamWOptimizer

### ISSUE THREAD

**Issue by erikchwang** [tensorflow/tensorflow#31306]
tf.contrib.opt.AdamWOptimizer requires two arguments: weight_decay and learning_rate. Since learning_rate is usually decayed along with the training, should weight_decay also be decayed with the same schedule? Would you please provide an example?

**Comment by erikchwang** [comment]
When using warm up, do we need to warm up weight_decay together with learning_rate?

**Comment by MarkDaoust** [comment]
I can imagine implementing it either way. 

@mingxingtan appears to be the author, maybe they can help.

**Comment by mingxingtan** [comment]
Sorry, I just merged an external PR. The original PR that adds this optimizer should be this: https://github.com/tensorflow/addons/pull/164

**Comment by MarkDaoust** [comment]
Cool.

So since `tf.contrib` is being deleted, and this lives in tensorflow/addons now Lets close this bug, and anyone who's interested can continue the conversation in tensorflow/addons/issues.

Right?
