### ISSUE TITLE
Constructor for diagonal arrays (like numpy.diag)

### ISSUE THREAD

**Issue by ziofil** [tensorflow/tensorflow#31304]
**System information**
- TensorFlow version (you are using): 1.14
- Are you willing to contribute it (Yes/No): No

At the moment the diagonal matrix constructor `tf.linalg.tensor_diag` does not support a second argument to specify which diagonal to fill. Something like the second argument in `numpy.diag` would be great.

This allows to simplify the process of generating powers of super- or sub-diagonal matrices by allowing a user to compute the off-diagonal elements directly and then filling the appropriate diagonal of a new array. Useful also to generate matrix exponentials of super- and sub-diagonal arrays.

**Comment by rmlarsen** [comment]
@ziofil this functionality was recently added to tf.linalg.diag. Would that suffice?

**Comment by ziofil** [comment]
Yes, that's wonderful thank you!
