### ISSUE TITLE
string_input_producer misbehave when num_epochs is set

### ISSUE THREAD

**Issue by ylongqi** [tensorflow/tensorflow#3131]
string_input_producer doesn't seem to enqueue string when the **num_epochs** is set.

With the following code, the program print [0], which is not right.
```python
import tensorflow as tf
sess = tf.InteractiveSession()
filenames = ["1", "2", "3"]
filename_queue = tf.train.string_input_producer(filenames, num_epochs=10)
test_value = tf.convert_to_tensor(filename_queue.size())

coord = tf.train.Coordinator()
threads = tf.train.start_queue_runners(sess=sess, coord=coord)

print(sess.run([test_value]))
```

But if I take out num_epochs,

```python
import tensorflow as tf
sess = tf.InteractiveSession()
filenames = ["1", "2", "3"]
filename_queue = tf.train.string_input_producer(filenames)
test_value = tf.convert_to_tensor(filename_queue.size())

coord = tf.train.Coordinator()
threads = tf.train.start_queue_runners(sess=sess, coord=coord)

print(sess.run([test_value]))
```

It prints [3] as expected.

Is there anyone else encounter the same issue?

**Comment by ylongqi** [comment]
> 

> [](url)

**Comment by mrry** [comment]
The solution is to add the line

```python
sess.run(tf.initialize_all_variables())
```

...before starting the queue runners. The `tf.train.string_input_producer()` function creates a variable internally to track the current epoch index, and (at present) it needs to be initialized before use.

**Comment by jakepoz** [comment]
I had to run 

` sess.run(tf.initialize_local_variables())`
 
To fix this when I had the same problem. Just adding this for reference for other folks.
