### ISSUE TITLE
CUDA driver version is insufficient for CUDA runtime version

### ISSUE THREAD

**Issue by jerofad** [tensorflow/tensorflow#31319]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
kernel version 4.9.0
LInux Ubuntu 16.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
N/A
- TensorFlow installed from (source or binary):
binary
- TensorFlow version:
Tensorflow 1.14 
Tensorflow-gpu 1.14
- Python version:
Python 3.7.3
- Installed using virtualenv? pip? conda?:
conda
- Bazel version (if compiling from source):
N/A
- GCC/Compiler version (if compiling from source):
Not from source but gcc is 6.3.0
- CUDA/cuDNN version:
cuDNN : 7.6.0
- GPU model and memory:
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 410.72       Driver Version: 410.72       CUDA Version: 10.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla K80           Off  | 00000000:00:04.0 Off |                    0 |
| N/A   44C    P0    70W / 149W |      0MiB / 11441MiB |    100%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+

**Describe the problem**

So I am trying to run a tensorflow dependent code, after fixing compatibility issues with my current tensorflow version, I run into this issue raised but from Nividia website, it looks to me the cuda meets the requirement. So I am wondering if this is from tensorflow. Is there any version pf tensorflow that's compatible with my system requirements and cuda?
**Provide the exact sequence of commands / steps that you executed before running into the problem**
Not applicable. I didn't bother to install any driver so as not to break my system. I only try to run my code and got to this issue.

**Any other info / logs**
Traceback (most recent call last):
  File "TF.py", line 48, in <module>
    sess = tf.compat.v1.Session(config=sess_config)
  File "/home/jfadugba/miniconda3/envs/peexoo/lib/python3.7/site-packages/tensorf
low/python/client/session.py", line 1570, in __init__
    super(Session, self).__init__(target, graph, config=config)
  File "/home/jfadugba/miniconda3/envs/peexoo/lib/python3.7/site-packages/tensorf
low/python/client/session.py", line 693, in __init__
    self._session = tf_session.TF_NewSessionRef(self._graph._c_graph, opts)
tensorflow.python.framework.errors_impl.InternalError: cudaGetDevice() failed. St
atus: CUDA driver version is insufficient for CUDA runtime version

**Comment by ravikyram** [comment]
@jerofad 
Can you go through below link and see if it helps you.Thanks!
https://stackoverflow.com/questions/41409842/ubuntu-16-04-cuda-8-cuda-driver-version-is-insufficient-for-cuda-runtime-vers
https://docs.nvidia.com/cuda/cuda-toolkit-release-notes/index.html
Just to verify did you get chance to follow instructions from [TensorFlow](https://www.tensorflow.org/install/gpu) website .Please, let us know. Thanks!

**Comment by jerofad** [comment]
Awesome I just downgraded my tensorflow to 1.13.1 version and everything works well with my drivers. I decided to downgrade as I am not satisfied with reinstalling my cuda drivers and nvidia drivers.
All good now.
