### ISSUE TITLE
libtensorflow_framework.so No such file or directory

### ISSUE THREAD

**Issue by sjtusmartboy** [tensorflow/tensorflow#31327]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version (use command below): 1.14.0
- Python version: Py36
- Bazel version (if compiling from source): bazel release 0.26.1
- GCC/Compiler version (if compiling from source): 7.3.0
- CUDA/cuDNN version:
- GPU model and memory:

I tried to include the op in the code as follows
```
    idtable_op_module = tf.load_op_library(
    resource_loader.get_path_to_datafile('libid_table_op.so'))
```

only to get the traceback infomation:
```
Traceback (most recent call last):
  File "wide_deep.py", line 12, in <module>
    import jarvis.tensorflow as jtf
  File "/opt/ml/job/python/jarvis/tensorflow/__init__.py", line 4, in <module>
    from jarvis.tensorflow.feature_transform import *
  File "/opt/ml/job/python/jarvis/tensorflow/feature_transform.py", line 10, in <module>
    from jarvis.tensorflow import id_column
  File "/opt/ml/job/python/jarvis/tensorflow/id_column.py", line 44, in <module>
    from jarvis.tensorflow.id_table_ops import IdHashTable
  File "/opt/ml/job/python/jarvis/tensorflow/id_table_ops.py", line 29, in <module>
    resource_loader.get_path_to_datafile('libid_table_op.so'))
  File "/usr/local/lib/python3.6/site-packages/tensorflow_core/python/framework/load_library.py", line 61, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename)
tensorflow.python.framework.errors_impl.NotFoundError: libtensorflow_framework.so: cannot open shared object file: No such file or directory
```

The trackback shows that there's no `libtensorflow_framework.so`, I tried to find this file in tf 1.14.0 binary version(not compiled version) and only found `site-packages/tensorflow_core/libtensorflow_framework.so.1`, but still no `libtensorflow_framework.so`. So what's the correct way to include `so` file, is it a bug in tf 1.14?

**Comment by Spotlight0xff** [comment]
You can use `tf.sysconfig.get_link_flags()` to compile the library correctly.
They changed the naming convention recently, see e.g. https://github.com/tensorflow/tensorflow/issues/27430

**Comment by kasrayazdani** [comment]
@Spotlight0xff do you mind providing more details on how to exactly use `tf.sysconfig.get_link_flags()`?

**Comment by sjtusmartboy** [comment]
@Spotlight0xff Does it mean that the tf version that compiles the `so` file and the tf version that loading the compiled `so` file should be the same?

**Comment by Spotlight0xff** [comment]
@kasrayazdani @sjtusmartboy 
I think the docs cover this pretty good in the [guide to extend TF](https://www.tensorflow.org/guide/extend/op#compile_the_op_using_your_system_compiler_tensorflow_binary_installation).

`tf.sysconfig.get_link_flags()` provides the linker flags to pass to the compiler to compile the `.so` library.

**Comment by sjtusmartboy** [comment]
@Spotlight0xff So does it mean that the tf version that compiles the so file and the tf version that loading the compiled so file should be the same?

**Comment by kasrayazdani** [comment]
I had the same problem and ended up downgrading my tf to 1.1.0 and CUDA to 9.2 and it works now.

**Comment by masotrix** [comment]
@sjtusmartboy Seems to be the case. After failing to compile kernels on 1.14 due to #30494, I managed to compile them for tf1.13.1 but not loading them on tf1.14. From suggestion in #31335 of using same compilers for building TF and custom op, only option to build custom ops + use AMP (#26342) seems to be to get TF from source.

**Comment by sjtusmartboy** [comment]
@masotrix Thanks a lot for advice, finally I also chose to downgrade to tf1.13.1 and it worked.

**Comment by yifeif** [comment]
As @Spotlight0xff mentioned, `tf.sysconfig.get_link_flags()` should contains the correct name for libtensorflow_framework. And you should build the custom op library against the TF pip version you want to run with. Closing this issue now. Let us know if you have more questions.
