### ISSUE TITLE
Build C API with visual compiler 2010

### ISSUE THREAD

**Issue by MaramAdham7** [tensorflow/tensorflow#31321]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): source
- TensorFlow version: r1.13
- Python version: 3.6
- Installed using virtualenv? pip? conda?: conda
- Bazel version (if compiling from source): 0.21
- GCC/Compiler version (if compiling from source): Visual Studio compiler 2010
- CUDA/cuDNN version: 10
- GPU model and memory: N/A

**Describe the problem**
Hello,

I would like to build tensorflow C api dll for cpu using compiler 2010.

Is this possible? As i have tried but there are errors produced using bazel or CMake
Bazel errors is as following 
**Provide the exact sequence of commands / steps that you executed before running into the problem**

1- Run C:\ProgramData\Anaconda3\python.exe configure.py with the default configuration
2- Run bazel build -c opt --copt=-mavx --copt=-mavx2 --copt=-mfma --copt=-mfpmath=both --copt=-msse4.2 --config=monolithic //tensorflow:libtensorflow.so

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

WARNING: The following configs were expanded more than once: [monolithic]. For repeatable flags, repeats are counted twice and may lead to unexpected behavior.
WARNING: Option 'experimental_shortened_obj_file_path' is deprecated
INFO: Invocation ID: 35bf2202-8201-4eeb-8b4a-696872ec1a86
INFO: Build option --conlyopt has changed, discarding analysis cache.
INFO: Analysed target //tensorflow:libtensorflow.so (0 packages loaded, 7854 targets configured).
INFO: Found 1 target...
ERROR: C:/users/l-madham/_bazel_l-madham/enzg4re4/external/protobuf_archive/BUILD:259:1: C++ compilation of rule '@protobuf_archive//:protoc_lib' failed (Exit 2): cl.exe failed: error executing command
  cd C:/users/l-madham/_bazel_l-madham/enzg4re4/execroot/org_tensorflow
  SET INCLUDE=C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\INCLUDE;C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\ATLMFC\INCLUDE;C:\Program Files (x86)\Microsoft SDKs\Windows\v7.0A\include;
    SET PATH=C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\BIN\amd64;C:\Windows\Microsoft.NET\Framework64\v4.0.30319;C:\Windows\Microsoft.NET\Framework64\v3.5;C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\VCPackages;C:\Program Files (x86)\Microsoft Visual Studio 10.0\Common7\IDE;C:\Program Files (x86)\Microsoft Visual Studio 10.0\Common7\Tools;C:\Program Files (x86)\Microsoft SDKs\Windows\v7.0A\bin\NETFX 4.0 Tools\x64;C:\Program Files (x86)\Microsoft SDKs\Windows\v7.0A\bin\x64;C:\Program Files (x86)\Microsoft SDKs\Windows\v7.0A\bin;;C:\Windows\system32
    SET PWD=/proc/self/cwd
    SET PYTHON_BIN_PATH=C:/ProgramData/Anaconda3/python.exe
    SET PYTHON_LIB_PATH=C:/ProgramData/Anaconda3/lib/site-packages
    SET TEMP=C:\Users\l-madham\AppData\Local\Temp
    SET TF_DOWNLOAD_CLANG=0
    SET TF_NEED_CUDA=0
    SET TF_NEED_OPENCL_SYCL=0
    SET TF_NEED_ROCM=0
    SET TMP=C:\Users\l-madham\AppData\Local\Temp
  C:/Program Files (x86)/Microsoft Visual Studio 10.0/VC/bin/amd64/cl.exe /nologo /DCOMPILER_MSVC /DNOMINMAX /D_WIN32_WINNT=0x0601 /D_CRT_SECURE_NO_DEPRECATE /D_CRT_SECURE_NO_WARNINGS /bigobj /Zm500 /EHsc /wd4351 /wd4291 /wd4250 /wd4996 /Iexternal/protobuf_archive /Ibazel-out/x64_windows-opt/genfiles/external/protobuf_archive /Ibazel-out/x64_windows-opt/bin/external/protobuf_archive /Iexternal/protobuf_archive/src /Ibazel-out/x64_windows-opt/genfiles/external/protobuf_archive/src /Ibazel-out/x64_windows-opt/bin/external/protobuf_archive/src /showIncludes /MD /O2 /Oy- /DNDEBUG /wd4117 -D__DATE__="redacted" -D__TIMESTAMP__="redacted" -D__TIME__="redacted" /Gy /Gw -w -mavx -mavx2 -mfma -mfpmath=both -msse4.2 /DHAVE_PTHREAD /wd4018 /wd4514 /Fobazel-out/x64_windows-opt/bin/external/protobuf_archive/_objs/protoc_lib/plugin.obj /c external/protobuf_archive/src/google/protobuf/compiler/plugin.cc
Execution platform: @bazel_tools//platforms:host_platform
cl : Command line warning D9002 : ignoring unknown option '/Gw'
cl : Command line warning D9002 : ignoring unknown option '-mavx'
cl : Command line warning D9002 : ignoring unknown option '-mavx2'
cl : Command line warning D9002 : ignoring unknown option '-mfma'
cl : Command line warning D9002 : ignoring unknown option '-mfpmath=both'
cl : Command line warning D9002 : ignoring unknown option '-msse4.2'
external/protobuf_archive/src\google/protobuf/stubs/mutex.h(33) : fatal error C1083: Cannot open include file: 'mutex': No such file or directory
Target //tensorflow:libtensorflow.so failed to build
INFO: Elapsed time: 14.823s, Critical Path: 1.04s
INFO: 0 processes.
FAILED: Build did NOT complete successfully

**Comment by MaramAdham7** [comment]
@gadagashwini can you help me please?

**Comment by gadagashwini** [comment]
@MaramAdham7 Just verify, did you the follow the instructions mentioned in this [link](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/lib_package/README.md). Thanks!

**Comment by MaramAdham7** [comment]
@gadagashwini I haven't tried them before but i tried 
bazel test --config opt //tensorflow/tools/lib_package:libtensorflow_test now and the same issue has been produced

WARNING: The following rc files are no longer being read, please transfer their contents or import their path into one of the standard rc files:
c:\tensorflow_r10\tensorflow/.bazelrc
Starting local Bazel server and connecting to it...
WARNING: Option 'experimental_shortened_obj_file_path' is deprecated
INFO: Invocation ID: 26ce30ea-ff75-4ef8-9f87-00bdb687b600
DEBUG: C:/users/l-madham/_bazel_l-madham/enzg4re4/external/bazel_tools/tools/build_defs/pkg/pkg.bzl:246:17: @//tensorflow/tools/lib_package:libtensorflow_jni: you provided a non dictionary to the pkg_tar `files` attribute. This attribute was renamed to `srcs`. Consider renaming it in your BUILD file.
DEBUG: C:/users/l-madham/_bazel_l-madham/enzg4re4/external/bazel_tools/tools/build_defs/pkg/pkg.bzl:246:17: @//tensorflow/tools/lib_package:common_deps: you provided a non dictionary to the pkg_tar `files` attribute. This attribute was renamed to `srcs`. Consider renaming it in your BUILD file.
DEBUG: C:/users/l-madham/_bazel_l-madham/enzg4re4/external/bazel_tools/tools/build_defs/pkg/pkg.bzl:246:17: @//tensorflow/tools/lib_package:cheaders: you provided a non dictionary to the pkg_tar `files` attribute. This attribute was renamed to `srcs`. Consider renaming it in your BUILD file.
DEBUG: C:/users/l-madham/_bazel_l-madham/enzg4re4/external/bazel_tools/tools/build_defs/pkg/pkg.bzl:246:17: @//tensorflow/tools/lib_package:eager_cheaders: you provided a non dictionary to the pkg_tar `files` attribute. This attribute was renamed to `srcs`. Consider renaming it in your BUILD file.
DEBUG: C:/users/l-madham/_bazel_l-madham/enzg4re4/external/bazel_tools/tools/build_defs/pkg/pkg.bzl:246:17: @//tensorflow/tools/lib_package:clib: you provided a non dictionary to the pkg_tar `files` attribute. This attribute was renamed to `srcs`. Consider renaming it in your BUILD file.
DEBUG: C:/users/l-madham/_bazel_l-madham/enzg4re4/external/bazel_tools/tools/build_defs/pkg/pkg.bzl:246:17: @//tensorflow/tools/lib_package:clicenses: you provided a non dictionary to the pkg_tar `files` attribute. This attribute was renamed to `srcs`. Consider renaming it in your BUILD file.
INFO: Analysed target //tensorflow/tools/lib_package:libtensorflow_test (117 packages loaded, 7972 targets configured).
INFO: Found 1 test target...
ERROR: C:/users/l-madham/_bazel_l-madham/enzg4re4/external/protobuf_archive/BUILD:259:1: C++ compilation of rule '@protobuf_archive//:protoc_lib' failed (Exit 2): cl.exe failed: error executing command
  cd C:/users/l-madham/_bazel_l-madham/enzg4re4/execroot/org_tensorflow
  SET INCLUDE=C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\INCLUDE;C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\ATLMFC\INCLUDE;C:\Program Files (x86)\Microsoft SDKs\Windows\v7.0A\include;
    SET PATH=C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\BIN\amd64;C:\Windows\Microsoft.NET\Framework64\v4.0.30319;C:\Windows\Microsoft.NET\Framework64\v3.5;C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\VCPackages;C:\Program Files (x86)\Microsoft Visual Studio 10.0\Common7\IDE;C:\Program Files (x86)\Microsoft Visual Studio 10.0\Common7\Tools;C:\Program Files (x86)\Microsoft SDKs\Windows\v7.0A\bin\NETFX 4.0 Tools\x64;C:\Program Files (x86)\Microsoft SDKs\Windows\v7.0A\bin\x64;C:\Program Files (x86)\Microsoft SDKs\Windows\v7.0A\bin;;C:\Windows\system32
    SET PWD=/proc/self/cwd
    SET PYTHON_BIN_PATH=C:/ProgramData/Anaconda3/python.exe
    SET PYTHON_LIB_PATH=C:/ProgramData/Anaconda3/lib/site-packages
    SET TEMP=C:\Users\l-madham\AppData\Local\Temp
    SET TF_DOWNLOAD_CLANG=0
    SET TF_NEED_CUDA=0
    SET TF_NEED_OPENCL_SYCL=0
    SET TF_NEED_ROCM=0
    SET TMP=C:\Users\l-madham\AppData\Local\Temp
  C:/Program Files (x86)/Microsoft Visual Studio 10.0/VC/bin/amd64/cl.exe /nologo /DCOMPILER_MSVC /DNOMINMAX /D_WIN32_WINNT=0x0601 /D_CRT_SECURE_NO_DEPRECATE /D_CRT_SECURE_NO_WARNINGS /bigobj /Zm500 /EHsc /wd4351 /wd4291 /wd4250 /wd4996 /Iexternal/protobuf_archive /Ibazel-out/x64_windows-opt/genfiles/external/protobuf_archive /Ibazel-out/x64_windows-opt/bin/external/protobuf_archive /Iexternal/protobuf_archive/src /Ibazel-out/x64_windows-opt/genfiles/external/protobuf_archive/src /Ibazel-out/x64_windows-opt/bin/external/protobuf_archive/src /showIncludes /MD /O2 /Oy- /DNDEBUG /wd4117 -D__DATE__="redacted" -D__TIMESTAMP__="redacted" -D__TIME__="redacted" /Gy /Gw -w /arch:AVX /DHAVE_PTHREAD /wd4018 /wd4514 /Fobazel-out/x64_windows-opt/bin/external/protobuf_archive/_objs/protoc_lib/cpp_field.obj /c external/protobuf_archive/src/google/protobuf/compiler/cpp/cpp_field.cc
Execution platform: @bazel_tools//platforms:host_platform
cl : Command line warning D9002 : ignoring unknown option '/Gw'
external/protobuf_archive/src\google/protobuf/stubs/mutex.h(33) : fatal error C1083: Cannot open include file: 'mutex': No such file or directory
Target //tensorflow/tools/lib_package:libtensorflow_test failed to build
INFO: Elapsed time: 368.224s, Critical Path: 3.94s
INFO: 10 processes: 10 local.
FAILED: Build did NOT complete successfully

FAILED: Build did NOT complete successfully

**Comment by gadagashwini** [comment]
@MaramAdham7 Can you upgrade the Microsoft Visual studio 2017 and try build. Thanks!

**Comment by MaramAdham7** [comment]
@gadagashwini unfortunately I want the api to be used in a project using compiler 2010
So is it possible to build the api using compiler 2010?

**Comment by gadagashwini** [comment]
@MaramAdham7 Please take a look at the tested build configuration of Tensorflow 1.13. Thanks!

**Comment by MaramAdham7** [comment]
@gadagashwini i have seen this table before, and it says that the library is tested across this compiler, also says that the available pre-built api is built using MSVC15. 
My question is it possible to build tensorflow api from source using compiler version older than MSVC15 (i.e to be more specific MSVC10) ?

**Comment by angersson** [comment]
@MaramAdham7 I'm afraid the TF team does not support the MSVC10 compiler. Since this is the case, I'll close this issue to keep the tracker focused.

Thanks for your interest!
