### ISSUE TITLE
Android Studio using build.gradle appears Failed to find 'android-25'

### ISSUE THREAD

**Issue by LGXNOTLGX** [tensorflow/tensorflow#31357]
**System information**
- OS Platform and Distribution :Windows 10
- Mobile device : Xiao Mi Mix2
- TensorFlow version: 1.10.0
- Python version: 3.6

**Describe the problem**
Android Studio:

6:47:20 Gradle sync started
6:47:32 Gradle sync failed: Failed to find target with hash string 'android-25' in: D:\software\SDK
        Consult IDE log for more details (Help | Show Log)

When I use the 'build.gradle', it delivers this problem
So I change buildToolVersion to 21, it delivers as the follows:

* What went wrong:
A problem occurred evaluating root project 'cmake'.
> Plugin with id 'com.android.library' not found.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

In the past , we success build the apk(not me), but not anymore. 

relative source:
https://github.com/LGXNOTLGX/androidAudioRecg

help me please

**Comment by gadagashwini** [comment]
@LGXNOTLGX, Provide the exact sequence of commands / steps that you executed before running into the problem

**Comment by LGXNOTLGX** [comment]
ok, i will show you relevant items:
1. I run the code from the https://github.com/saturn-lab/audioPlot get the basic data
2. Then next step is from https://github.com/saturn-lab/audioNet
3. Final, the main problem, it is from https://github.com/saturn-lab/androidAudioRecg
above is the whole steps about our project, if you want to get the relevant data, you may run the "1" first.

Here's where the problem went wrong 
![problem](https://user-images.githubusercontent.com/52983152/62666970-3a046b80-b9b8-11e9-9f61-0ff77d846701.JPG)
When I open the Android Studio, it always report 'android-25' failed to find. 
I have download all of the packages from SDK manager, it stills reported
so I want to change the buildToolVersion, but I can not solve it!
Thanks!

**Comment by jdduke** [comment]
I don't believe this failure is in any way related to TensorFlow. Please file an issue against the saturn-lab projects.
