### ISSUE TITLE
TensorflowLite Runtime Installation Doesn't provide Interpreter Package

### ISSUE THREAD

**Issue by vibhatha** [tensorflow/tensorflow#31369]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution: 
[Platform 1]
NAME="Ubuntu"
VERSION="16.04.5 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.5 LTS"
VERSION_ID="16.04"

- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:

[Platform 2]
PRETTY_NAME="Mendel GNU/Linux 3 (Chef)"
NAME="Mendel GNU/Linux"
VERSION_ID="3"
VERSION="3 (chef)"
ID=mendel
ID_LIKE=debian

- TensorFlow installed from (source or binary): {Didn't install trying to use tflite_runtime} [TFLITE RUNTIME](https://www.tensorflow.org/lite/guide/python#run_an_inference_using_tflite_runtime)
- TensorFlow version: N/A
- Python version: Mendel 3.5.3 / Ubuntu 16.04 3.6.9
- Installed using virtualenv? pip? conda?: virtualenv
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source):  Mendel (gcc (Debian 6.3.0-18+deb9u1) 6.3.0 20170516), Ubuntu 16.04 (gcc (Ubuntu 5.4.0-6ubuntu1~16.04.11) 5.4.0 20160609)
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

I tried to install the TFLITE Runtime using 

https://www.tensorflow.org/lite/guide/python#run_an_inference_using_tflite_runtime

When I tried to import as follows.

`from tflite_runtime import Interpreter`

I get the following error in both devices (Ubuntu 16.04 and Mendel)

`>>> from tflite_runtime import Interpreter
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
`

But when I just do 

`import tflite_runtime`

Doesn't give me an error in either platform. 
I tried using IntelliSense and it shows me no Interpreter API. 

Am I doing something wrong? How to fix this issue? 

**Describe the problem**

**Provide the exact sequence of commands / steps that you executed before running into the problem**

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by vibhatha** [comment]
Hi I found a solution

`from tflite_runtime.interpreter import Interpreter`

Can you update your documentation? I still need to check whether this works fine.

**Comment by vibhatha** [comment]
And also 

`from tflite_runtime import load_deleget` is not working
But

`from tflite_runtime.interpreter import load_delegate` is working. 

Any reason why the API is not consistent in docs and in the package? 
Am I doing something wrong?

**Comment by martinmarek1999** [comment]
On Ubuntu Server 18.04, `from tflite_runtime import Interpreter` raises _`cannot import name 'Interpreter' from 'tflite_runtime'`_. However, `from tflite_runtime.interpreter import Interpreter` works just fine.

On the other hand, I couldn't get `interpreter` working in any way on Amazon Linux 2. `from tflite_runtime import Interpreter` raises _`cannot import name 'Interpreter' from 'tflite_runtime'`_ and `from tflite_runtime.interpreter import Interpreter` raises _`No module named '_interpreter_wrapper'`_.

Is this perhaps a related issues? Any help would be much appreciated.

**Comment by vibhatha** [comment]
Interpreter wrapper issue comes when you try to install this in a non-edge-tpu device. I also got it. 
I use the BasicEngine API to do my inference on such occasions. 
I think it is an issue with APIs, but not 100% sure. I think they are related and I am not sure how to solve it.

**Comment by martinmarek1999** [comment]
Just to clear up my issues with Amazon Linux: it seems that TensorflowLite Runtime 1.14.0 requires GLIBC_2.27, whereas Amazon Linux (2) only supports GLIBC_2.26 and lower.

It still seems to be the case that one has to from `tflite_runtime.interpreter import Interpreter`, no matter what OS.

**Comment by rajurimu** [comment]
I am facing the same issue with official install. I am running on rpi zero and trying to install tflite stand alone.

https://www.tensorflow.org/lite/guide/python#run_an_inference_using_tflite_runtime.

Error I am getting is
ModuleNotFoundError: No module named 'tflite_runtime'

**Comment by jvishnuvardhan** [comment]
@vibhatha Looks like this was resolved. The imports are updated as shown below

```
import tflite_runtime.interpreter as tflite

interpreter = tflite.Interpreter(model_path=args.model_file)
```

Please verify once and close the issue if this was resolved for you. Thanks!

**Comment by GarimaSarangal** [comment]
> On Ubuntu Server 18.04, `from tflite_runtime import Interpreter` raises _`cannot import name 'Interpreter' from 'tflite_runtime'`_. However, `from tflite_runtime.interpreter import Interpreter` works just fine.
> 
> On the other hand, I couldn't get `interpreter` working in any way on Amazon Linux 2. `from tflite_runtime import Interpreter` raises _`cannot import name 'Interpreter' from 'tflite_runtime'`_ and `from tflite_runtime.interpreter import Interpreter` raises _`No module named '_interpreter_wrapper'`_.
> 
> Is this perhaps a related issues? Any help would be much appreciated.

@martin-marek  i am getting the same issue on ubuntu 16. how was it solved?
