### ISSUE TITLE
tf.function changes behavior of += operator on tf.Tensors

### ISSUE THREAD

**Issue by ikamensh** [tensorflow/tensorflow#31363]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): MacOS 10.14
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): pip install (wheel?)
- TensorFlow version (use command below): 2.0.0-beta1
- Python version: 3.7.3
- GPU model and memory: CPU

**Describe the current behavior**
Behaviour of += operator on a tensor is different when called via tf.function and when called directly

**Describe the expected behavior**
tf.function does not change the behavior of any operations on tensors.

**Code to reproduce the issue**
```
import tensorflow as tf
print(tf.__version__)

class First:
    def __init__(self, initial: int):
        self.value = tf.constant(initial)

    def increment(self):
        self.value += 1

    def __str__(self):
        return f'Object with tensor = {self.value}'

@tf.function
def increment(obj: First):
    obj.increment()

c1 = First(100)

c1.increment()
print(c1)

increment(c1)
print(c1)
```

**Other info / logs**
output:
```
Object with tensor = 101
Object with tensor = Tensor("add:0", shape=(), dtype=int32)
```

Expected output:

```
Object with tensor = 101
Object with tensor = 102
```

**Comment by gadagashwini** [comment]
I tried the code on Colab and was able to reproduce the issue with Tensorflow 2.0.0beta1. Please see the gist [here](https://colab.research.google.com/drive/13h9wPKWxCkWP0L97VqkoIFor4N3wT8N3). Thanks!

**Comment by jvishnuvardhan** [comment]
@ikamensh I don't see any issue. You need change `increment(c1)` to `c1.increment()` in the last line . Please check the gist [here](https://colab.sandbox.google.com/gist/jvishnuvardhan/2a0462f04a6aab4ef9e98b4aa3afd10e/tf_31363.ipynb). Thanks!

**Comment by alextp** [comment]
It's not about the behavior of +=, it's about the fact that you're assigning a tensor inside a function graph to an object which outlives that function.

If you need to change the value of something inside a tf.function and you want that to persist either make it a return value or make it a tf.Variable, as otherwise tf has no way of knowing what you want.

**Comment by ikamensh** [comment]
@alextp 
Then it is a leaky abstraction. As a user, I don't want to know how tensorflow makes its magic. I am doing a simple tensor operation inside a tf.function, why should it break?

tf has a way of knowing what I want, as it works outside tf.function.
