### ISSUE TITLE
Non-tensorflow code gets executed only on the first run of tf.function

### ISSUE THREAD

**Issue by ikamensh** [tensorflow/tensorflow#31362]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): MacOS 10.14
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): pip install (wheel?)
- TensorFlow version (use command below): 2.0.0-beta1
- Python version: 3.7.3
- GPU model and memory: CPU

**Describe the current behavior**
Non-tensorflow code gets executed only on the first run of tf.function

**Describe the expected behavior**
Either exception is thrown or the code is executed every time. As it is, it just welcomes bugs.

**Code to reproduce the issue**
```
import tensorflow as tf

print(tf.__version__)

class MyObj:
    def __init__(self):
        self.value = 0

obj = MyObj()

@tf.function
def with_py_side_effect(tensorflow_stuff, o):

    # do my complex tf stuff
    ...

    o.value += 1
    return tensorflow_stuff

for i in range(5):
    print(i, obj.value)
    a = with_py_side_effect(None, obj)
```

**Other info / logs**
My output:
```
/Users/ikkamens/.pyenv/versions/3.7.3/bin/python /Users/ikkamens/Library/Preferences/PyCharmCE2019.2/scratches/tf_foo_python.py
2019-08-06 11:53:11.888584: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2.0.0-beta1
0 0
1 1
2 1
3 1
4 1

Process finished with exit code 0
```

**Comment by anush-o** [comment]
@ikamensh ,
When tried executing the given code with TF version 2.0.0beta1 I did not receive any warning, please take a look [gist](https://colab.sandbox.google.com/drive/1LDYziezlHD2QHZTq_gI-JfWpra3tCjD2#scrollTo=CRBQ-MorJb7I) of collab.Thanks!

**Comment by ikamensh** [comment]
@anush-o 
I am not complaining about a warning. My code should increment the o.value on each iteration, but as seen from the output it does so only on the first iteration. A warning would be desired, but is not shown!

Expected output:
```

2.0.0-beta1
0 0
1 1
2 2
3 3
4 4

```

**Comment by mdanatg** [comment]
@kkimdev @alextp @dynamicwebpaige @lamberta @martinwicke FYI

`tf.function` allows you to express TensorFlow computations using a subset of Python, however it is not a general-purpose execution back-end for the Python language, at least not in this version; perhaps we should call this out more clearly in the docs.

One of the side effects if this mechanism is the behavior you experienced. In general, you should try to write all computation using tf functions to make sure it's executed the way you expect.

For a bit more background, please have a loop at the [API docs](https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/function) and the [autograph reference](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/autograph/g3doc/reference/index.md).
