### ISSUE TITLE
Quantized SSD TFLite runs much slower in GPU (GTX 1080) when compared to its original model

### ISSUE THREAD

**Issue by xmuszq** [tensorflow/tensorflow#31377]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):  NO
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): 16.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: NO
- TensorFlow installed from (source or binary): NO
- TensorFlow version (use command below): 1.14
- Python version: 2.7
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 10/7.5
- GPU model and memory: GTX 1080 TI

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
I converted the SSD into the TFLite model with quantization and ran a speed comparison between the quantized SSD and the original SSD. The time used for each image: 
quantized SSD - 110 ms 
original SSD - 12 ms
the quantized SSD is almost ten times slower than the original one in GPU. 
Some additional info:
SSD is based on the mobilenet_v1, no other costumed operations. 
Codes used to do the conversion:
tflite_convert \
  --output_file=./ssd.tflite \
  --graph_def_file=./tflite_graph.pb \
  --inference_type=FLOAT \
  --input_arrays=normalized_input_image_tensor \
  --output_arrays='TFLite_Detection_PostProcess','TFLite_Detection_PostProcess:1','TFLite_Detection_PostProcess:2','TFLite_Detection_PostProcess:3' \
  --std_dev_values=128 --mean_values=128 \
  --default_ranges_min=-6 --default_ranges_max=6 \
  --input_shapes=1,300,300,3 \
  --allow_custom_ops

The two models are in the link:
https://drive.google.com/drive/folders/1Q5aOZRlxhDsMdiSYYSuWlUyQP82FJTdC?usp=sharing

Anyone can give me some suggestion?  Thank you!

**Comment by xmuszq** [comment]
Some more info:
when run the quantized ssd, although it use the GPU (the mem usage is increased to ~600M while the calculation usage is 0%, but the cpu usage is increased a lot; ) 
when run the original model, the gpu mem is also around 600M the gpu computation is 5-10%. 

So it looks like the quantized model can not use GPU?

**Comment by freedomtan** [comment]
@xmuszq Interesting. Why do you expect quantized TFLite model to be better on GTX 1080? There are some problems.
0. as far as I can remember, 1080's integer is weaker than floating point
1. There is no cuda GPU acceleration for TFLite. Although there is TFLite GPU delegate, which supports GL ES compute shader and Apple's Metal shader, it's not ported to desktop/server GPU (yet)
2. TFLite GPU delegate  was designed for floating point. So, even if you have it ported to 1080, mostly It won't help quantized TFLite model.

**Comment by kingofthebongo2008** [comment]
1080 has fp16 arithmetic very fast,

**Comment by alanchiao** [comment]
Yes, generally the quantized model is meant for running on CPU and certain hardware accelerators (e.g ones behind the NNAPI and the EdgeTPU) and not for the GPU. As Stefan said, fp16 is great on the GPUs and you may want to look at this: https://www.tensorflow.org/lite/performance/post_training_float16_quant
