### ISSUE TITLE
tf.data.experimental.make_csv_dataset header flag not working as described

### ISSUE THREAD

**Issue by gridcellcoder** [tensorflow/tensorflow#31370]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
`Custom code`
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
```os: Linux
os kernel version: #22-Ubuntu SMP Tue Jul 2 13:27:33 UTC 2019
os release version: 5.0.0-21-generic
os platform: Linux-5.0.0-21-generic-x86_64-with-debian-buster-sid
linux distribution: ('debian', 'buster/sid', '')
linux os distribution: ('debian', 'buster/sid', '')
mac version: ('', ('', '', ''), '')
uname: uname_result(system='Linux', node='dev-XPS-13-9343', release='5.0.0-21-generic', version='#22-Ubuntu SMP Tue Jul 2 13:27:33 UTC 2019', machine='x86_64', processor='x86_64')
architecture: ('64bit', '')
machine: x86_64
GNU/Linux
```
- TensorFlow installed from (source or binary):
`binary using pip`
- TensorFlow version (use command below):

```Name: tensorflow
Version: 2.0.0b1
Summary: TensorFlow is an open source machine learning framework for everyone.
Home-page: https://www.tensorflow.org/
Author-email: packages@tensorflow.org
License: Apache 2.0
Location: /home/dev/miniconda3/envs/pythonapu/lib/python3.6/site-packages
Required-by: 
```

- Python version:
```
Python 3.6.8 :: Anaconda, Inc.
python version: 3.6.8
python branch: 
python build version: ('default', 'Dec 30 2018 01:22:34')
python compiler version: GCC 7.3.0
python implementation: CPython
```
**Describe the current behavior**

`tf.data.experimental.make_csv_dataset(header=True)` includes the header data in the dataset

**Describe the expected behavior**

According to the docs:
```
header: A bool that indicates whether the first rows of provided CSV files
      correspond to header lines with column names, and should not be included
      in the data.
```
The data should not be included in the data.

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

I have a dataset in csv `/tmp/foo.csv`:
```
A,B,C
1,NA,1
1,NA,1
1,NA,1
1,NA,1
```
I can run something like with `header=True`
```
 dataset_file = tf.keras.utils.get_file("foo2" + str(uuid.uuid4()) + ".csv", "file:///tmp/foo.csv")
dataset = tf.data.experimental.make_csv_dataset(
        dataset_file, batch_size=4, header=False,
        label_name="A", na_value='NA', column_names=["A", "B", "C"],
        field_delim=',')
    for feature_batch, label_batch in dataset.take(1):
        print(label_batch)
        print("features:")
        for key, value in feature_batch.items():
            print(key + ' ' + value)
```

which gives:

```
Traceback (most recent call last):
  File "/home/xyz/workspace/pythonapi/main/services/dataloader.py", line 149, in <module>
    load()
  File "/home/xyz/workspace/pythonapi/main/services/dataloader.py", line 143, in load
    print(key + ' ' + value)
  File "/home/xyz/miniconda3/envs/pythonapu/lib/python3.6/site-packages/tensorflow/python/ops/math_ops.py", line 909, in r_binary_op_wrapper
    x = ops.convert_to_tensor(x, dtype=y.dtype.base_dtype, name="x")
  File "/home/xyz/miniconda3/envs/pythonapu/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1100, in convert_to_tensor
    return convert_to_tensor_v2(value, dtype, preferred_dtype, name)
  File "/home/xyz/miniconda3/envs/pythonapu/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1158, in convert_to_tensor_v2
    as_ref=False)
  File "/home/xyz/miniconda3/envs/pythonapu/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1237, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/home/xyz/miniconda3/envs/pythonapu/lib/python3.6/site-packages/tensorflow/python/framework/constant_op.py", line 305, in _constant_tensor_conversion_function
    return constant(v, dtype=dtype, name=name)
  File "/home/xyz/miniconda3/envs/pythonapu/lib/python3.6/site-packages/tensorflow/python/framework/constant_op.py", line 246, in constant
    allow_broadcast=True)
  File "/home/xyz/miniconda3/envs/pythonapu/lib/python3.6/site-packages/tensorflow/python/framework/constant_op.py", line 254, in _constant_impl
    t = convert_to_eager_tensor(value, ctx, dtype)
  File "/home/xyz/miniconda3/envs/pythonapu/lib/python3.6/site-packages/tensorflow/python/framework/constant_op.py", line 115, in convert_to_eager_tensor
    return ops.EagerTensor(value, handle, device, dtype)
TypeError: Cannot convert provided value to EagerTensor. Provided value: C  Requested dtype: int32
```
When C should not be in the dataset.

**Other info / logs**

With `header=False`

works fine but not as described in the documentation as this suggests the csv does not contain the header and prints 
```
tf.Tensor([b'1' b'1' b'1' b'A'], shape=(4,), dtype=string)
features:
tf.Tensor([b'B ' b'B ' b'B ' b'B B'], shape=(4,), dtype=string)
tf.Tensor([b'C 1' b'C 1' b'C 1' b'C C'], shape=(4,), dtype=string)
```

**Comment by ravikyram** [comment]
@gridcellcoder 
I have created dataset foo.csv using pandas for reproducing the issue.While executing the code i am getting below `error:ValueError: unknown url type: 'fOO.csv'`Request you to help me with the reproducable code.Thanks!

**Comment by gridcellcoder** [comment]
To reproduce:

1) Create a file in /tmp/foo.csv Note: Not `f00.csv` as in your message
2) Copy this into the file you created in 1) note: do not use pandas etc just a simple text editor

```
A,B,C
1,NA,1
1,NA,1
1,NA,1
1,NA,1
```

3) Run this in a python file after importing keras and tf beta2.0

```
dataset_file = tf.keras.utils.get_file("foo2" + str(uuid.uuid4()) + ".csv", "file:///tmp/foo.csv")
dataset = tf.data.experimental.make_csv_dataset(
        dataset_file, batch_size=4, header=False,
        label_name="A", na_value='NA', column_names=["A", "B", "C"],
        field_delim=',')
    for feature_batch, label_batch in dataset.take(1):
        print(label_batch)
        print("features:")
        for key, value in feature_batch.items():
            print(key + ' ' + value)
```

that should recreate the issue above.

**Comment by ravikyram** [comment]
I have tried on Jupyter notebook  with TF version 2.0 beta1 and 2.0.0-dev20190807 and was able to reproduce the issue.Please, find the gist in attachment.Thanks!
[test.tar.gz](https://github.com/tensorflow/tensorflow/files/3480131/test.tar.gz)

**Comment by rachellim** [comment]
Apologies for the delayed response. Since you don't provide the `column_defaults` parameter, `make_csv_dataset` tries to infer the type of your data.

When the `header=True` flag is set, it ignores the first line of data.
Therefore, it infers that column A contains ints, B contains strings, C contains ints.
The issue here is that in line 
```
print(key + ' ' + value)
```

key is a string tensor, and value is an int tensor (in the A and C case). These types cannot be added together, which is why you get the above error.


In the case where `header=False`, the first (header) line is not ignored. If you read the documentation, the header parameter is "A bool that indicates whether the first rows of provided CSV files correspond to header lines with column names, and should not be included in the data." -- so when header=False, the header line IS included in the data, i.e. it interprets the header line as regular data that's part of your dataset. Because this line has the data "A,B,C", it infers that all your columns are strings. Since string tensors can be added together, you don't get an error.

Does that make sense?
