### ISSUE TITLE
weird behavior on GPU ec2 - zero tensor instead of random one on local machine

### ISSUE THREAD

**Issue by dexter4455** [tensorflow/tensorflow#3138]
GitHub issues are for bugs / installation problems / feature requests.  
For general support from the community, see [StackOverflow](https://stackoverflow.com/questions/tagged/tensorflow).
To make bugs and feature requests more easy to find and organize, we close issues that are deemed
out of scope for GitHub Issues and point people to StackOverflow.

For bugs or installation issues, please provide the following information.
The more information you provide, the more easily we will be able to offer
help and advice.

### Environment info
Operating System: Ubuntu 14.04 
Linux ip-172-31-7-130 3.13.0-88-generic #135-Ubuntu SMP Wed Jun 8 21:10:42 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

Installed version of CUDA and cuDNN: cuda 7.5, cudnn 5.0.5
(please attach the output of `ls -l /path/to/cuda/lib/libcud*`):
-rw-r--r-- 1 root root 189170 Jun 12 02:51 /usr/local/cuda/lib/libcudadevrt.a
lrwxrwxrwx 1 root root     16 Jun 12 02:51 /usr/local/cuda/lib/libcudart.so -> libcudart.so.7.5
lrwxrwxrwx 1 root root     19 Jun 12 02:51 /usr/local/cuda/lib/libcudart.so.7.5 -> libcudart.so.7.5.18
-rwxr-xr-x 1 root root 311596 Jun 12 02:51 /usr/local/cuda/lib/libcudart.so.7.5.18
-rw-r--r-- 1 root root 558020 Jun 12 02:51 /usr/local/cuda/lib/libcudart_static.a

If installed from binary pip package, provide:

1. Which pip package you installed.
2. The output from `python -c "import tensorflow; print(tensorflow.__version__)"`.
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcublas.so.7.5 locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcudnn.so.5.0.5 locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcufft.so.7.5 locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcurand.so.7.5 locally
0.8.0

If installed from sources, provide the commit hash:
9b69ec3960cf9225df557fdc1ab673bd36bde4fb

### Steps to reproduce
1.
import tensorflow as tf
a=tf.Variable(tf.random_uniform([5], 0, 10, dtype=tf.int32, seed=10))
init = tf.initialize_all_variables()
with tf.Session() as sess:
    sess.run(init)
    result=sess.run(a)
    print(result)
    sess.close()

the result is: [0 0 0 0 0] 
2. If i run it locally (on my mac laptop where tensorflow was installed via pip - i dont have a gpu), i get: [ 33689671 570442370 201367012 671088640 671145444]
3. I have python 3.5.1 , miniconda --version = "conda 4.1.5", run on EC2 , GPU K520

### What have you tried?
1. inside miniconda, outside it..

### Logs or other output that would be helpful
(If logs are large, please upload as attachment).

**Comment by jarrydfillmore** [comment]
+1!

**Comment by dexter4455** [comment]
switched to 0.9 and things worked

**Comment by aselle** [comment]
Glad to hear that @dexter4455. Closing! We can reopen if this doesn't resolve it for @jarrydfillmore
