### ISSUE TITLE
Building tensorflow (makefile method) on arhmf Olimex A20

### ISSUE THREAD

**Issue by normads** [tensorflow/tensorflow#3139]
Building tensorflow using the makefile method, i get the below error, 

`PROTOC = "protoc"
CC_PREFIX = ""
gcc --std=c++11 -DIS_SLIM_BUILD -O0 -I/usr/local/include -I. -I/home/olimex/tf/tensorflow/tensorflow/contrib/makefile/downloads/ -I/home/olimex/tf/tensorflow/tensorflow/contrib/makefile/downloads/eigen-eigen-334b1d428283 -I/home/olimex/tf/tensorflow/tensorflow/contrib/makefile/gen/proto/ -I/home/olimex/tf/tensorflow/tensorflow/contrib/makefile/gen/proto_text/ \
        -o /home/olimex/tf/tensorflow/tensorflow/contrib/makefile/gen/bin/benchmark /home/olimex/tf/tensorflow/tensorflow/contrib/makefile/gen/obj/tensorflow/core/util/reporter.o /home/olimex/tf/tensorflow/tensorflow/contrib/makefile/gen/obj/tensorflow/tools/benchmark/benchmark_model.o /home/olimex/tf/tensorflow/tensorflow/contrib/makefile/gen/obj/tensorflow/tools/benchmark/benchmark_model_main.o \
         -Wl,--allow-multiple-definition -Wl,--whole-archive /home/olimex/tf/tensorflow/tensorflow/contrib/makefile/gen/lib/libtensorflow-core.a -L/usr/local/lib -lstdc++ -lprotobuf -lz -lm -ldl -lpthread
/usr/lib/gcc/arm-linux-gnueabihf/4.8/libgcc.a(fp16.o): In function `__gnu_h2f_ieee':
(.text+0x12a): relocation truncated to fit: R_ARM_THM_JUMP11 against symbol `__gnu_h2f_internal' defined in .text section in /usr/lib/gcc/arm-linux-gnueabihf/4.8/libgcc.a(fp16.o)
/usr/lib/gcc/arm-linux-gnueabihf/4.8/libgcc.a(fp16.o): In function `__gnu_h2f_alternative':
(.text+0x132): relocation truncated to fit: R_ARM_THM_JUMP11 against symbol `__gnu_h2f_internal' defined in .text section in /usr/lib/gcc/arm-linux-gnueabihf/4.8/libgcc.a(fp16.o)
/usr/lib/gcc/arm-linux-gnueabihf/4.8/libgcc.a(fp16.o): In function `__gnu_h2f_ieee':
(.text+0x12a): relocation truncated to fit: R_ARM_THM_JUMP11 against symbol `__gnu_h2f_internal' defined in .text section in /usr/lib/gcc/arm-linux-gnueabihf/4.8/libgcc.a(fp16.o)
/usr/lib/gcc/arm-linux-gnueabihf/4.8/libgcc.a(fp16.o): In function `__gnu_h2f_alternative':
(.text+0x132): relocation truncated to fit: R_ARM_THM_JUMP11 against symbol `__gnu_h2f_internal' defined in .text section in /usr/lib/gcc/arm-linux-gnueabihf/4.8/libgcc.a(fp16.o)
/usr/lib/gcc/arm-linux-gnueabihf/4.8/libgcc.a(fp16.o): In function `__gnu_h2f_ieee':
(.text+0x12a): relocation truncated to fit: R_ARM_THM_JUMP11 against symbol `__gnu_h2f_internal' defined in .text section in /usr/lib/gcc/arm-linux-gnueabihf/4.8/libgcc.a(fp16.o)
/usr/lib/gcc/arm-linux-gnueabihf/4.8/libgcc.a(fp16.o): In function `__gnu_h2f_alternative':
(.text+0x132): relocation truncated to fit: R_ARM_THM_JUMP11 against symbol `__gnu_h2f_internal' defined in .text section in /usr/lib/gcc/arm-linux-gnueabihf/4.8/libgcc.a(fp16.o)
collect2: error: ld returned 1 exit status`

From what i understand this appears to be an issue with the linker trying to branch on a long address, 
https://lists.gnu.org/archive/html/bug-binutils/2007-06/msg00065.html
But this issue is back from 2007, any workaround i can do on the source to avoid this?

System:
gcc version 4.8.4 (Debian 4.8.4-1)
GNU ld (GNU Binutils for Debian) 2.25

**Comment by normads** [comment]
tried with gcc version 4.9.2
same result. can i not build the benchmark model? help!

**Comment by normads** [comment]
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=71776

**Comment by petewarden** [comment]
Have you tried -mno-thumb in your compiler settings? From memory this helped when I was trying to cross-compile for the Pi (which I ended up giving up on in the end, and compiling natively on-device).

**Comment by normads** [comment]
i just tried -mno-long-calls and that appears to work so far. if it fails i'll try -mno-thumb. thanks!

**Comment by normads** [comment]
-mno-long-calls or -mlong-calls did not help. 
-mno-thumb is not an arm option (https://gcc.gnu.org/onlinedocs/gcc/ARM-Options.html)

**Comment by normads** [comment]
I managed to work around this by building gcc with --with-mode=arm
It appears to be a bug with [gcc](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=71776) but it's not confirmed yet :/
I did however run into a [different issue](https://github.com/tensorflow/tensorflow/issues/4202) right after :(

**Comment by normads** [comment]
Had some time to get to the bottom of this. The problem is with the use of --whole-archive option without a --no-whole-archive afterwards. 
Each library after --whole-archive is included completely until --no-whole-archive is specified and libgcc is automatically appended to the end of the library list, which means both libm.a and libgcc.a are included as a whole. 
There are duplicates for a lot of functions between libm and libgcc. 
so when __gnu_h2f_internal wants to link to __gnu_h2f_ieee it has two options from libm and libgcc. This would typically cause the linking to fail, but since --allow-multiple-definitions is specified the linker would link to the **first** definition. The first definition could be from the other library which would be further away from the program counter than the definition within the same library. 
This would normally be alright with 64-bit instructions or even 32-bit instructions but with ARM 32-bit THUMB instructions the specific branch instruction only has a 12bit offset range, which is 1024 words. So it would fail trying to fit the offset into those 12bits. 
The easy fix is to add --no-whole-archive after libtensorflow-core.a. I believe this also removes the need for --allow-multiple-definitions.
Or if you're silly enough you could rebuild libgcc without thumb like i first did :/
Should i send a PR for this?

**Comment by petewarden** [comment]
Thanks for your detective work on this, and for the update! It would make sense to add the -Wl,--no-whole-archive flag after every place where we use whole-archive to make sure other people don't hit this problem. A PR would be much appreciated.
