### ISSUE TITLE
Bug in tflite_convert: when converting tf.gather operation (r1.14)

### ISSUE THREAD

**Issue by paanguin** [tensorflow/tensorflow#31399]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 16.04
- TensorFlow installed from (source or binary): built from r1.14 (https://github.com/tensorflow/tensorflow/tree/r1.14)
- TensorFlow version (or github SHA if from source): 1.14

I might found a bug in tflite_convert, and I want to report this.
I am not sure whether you aware of this or not, but I will explain it for the safety.

The following converting code gives an error in making tflite model.
It complains about checking dims() during the conversion.

```
import tensorflow as tf
import numpy as np

export_dir = 'test_saved_model'
builder = tf.saved_model.builder.SavedModelBuilder(export_dir)

weight = np.random.rand(32,512)

x = tf.placeholder(tf.float32, shape=[None,512])
W = tf.constant(weight,dtype=tf.float32, name='kernel')
z = x*W

gdim = tf.constant(3,dtype=tf.int32)
gaxis = tf.constant(0,dtype=tf.int32)
Wg = tf.get_variable("kernel", [32,512])
y = tf.gather(Wg,gdim,gaxis)
res = y





with tf.Session() as sess:
        sess.run(tf.global_variables_initializer())

        builder.add_meta_graph_and_variables(sess, ["test"])
        builder.save(as_text=True)

        converter = tf.lite.TFLiteConverter.from_session(sess, [x], [res])

        # options for converter
        converter.dump_graphviz_dir="graph_dir" # outputs graph visualization file (.dot)
        converter.dump_graphviz_video=True

        tflite_model = converter.convert()

```

I found that it is caused by the resolve_constant_gather.cc
https://github.com/tensorflow/tensorflow/blob/a497fb2da9258cbfaa4e443f446c5ab039ef4a32/tensorflow/lite/toco/graph_transformations/resolve_constant_gather.cc#L42

It seems that the Gather function assumes that 'coords_array' is always 1-dim array.
However, tf.gather may accept it as 0-dim array, a scalar value, so that the checking fail if 'coords_array' became a scalar.

My solution is following modification for Gather function.
It worked for me when I personally built and installed from the modified source.

I hope someone to check about this and fix the issue if necessary.

```
// Gathers data from axis 0.
template <ArrayDataType Type>
inline void Gather(const Array& input_array, const Array& coords_array,
                   Array* output_array) {
  const Shape& input_shape = input_array.shape();
  const std::vector<DataType<Type>>& input_data =
      input_array.GetBuffer<Type>().data;
  const Shape& coords_shape = coords_array.shape();
  const std::vector<int32>& coords_data =
      coords_array.GetBuffer<ArrayDataType::kInt32>().data;

  const Shape& output_shape = output_array->shape();
  std::vector<DataType<Type>>& output_data =
      output_array->GetMutableBuffer<Type>().data;
  output_data.resize(RequiredBufferSizeForShape(output_shape));

  int stride = 1;
  for (int i = 1; i < input_shape.dimensions_count(); ++i) {
    stride *= input_shape.dims(i);
  }

  if (coords_shape.dimensions_count()==0){
        // when coords_array is 0-dim (a constant)
        CHECK_EQ(stride * 1, output_data.size());

        DCHECK_GE(coords_data[0], 0);
        DCHECK_LT(coords_data[0], input_shape.dims(0));
        DataType<Type>* out = output_data.data();
        const DataType<Type>* in = input_data.data() + coords_data[0] * stride;
        memcpy(out, in, sizeof(DataType<Type>) * stride);
  }
  else {
        // when coords_array is 1-dim array
        CHECK_EQ(coords_shape.dims(0), output_array->shape().dims(0));

        // Let's make sure we have enough space for all element in the memcpy()
        // below, which writes 'stride' elements starting at 'i * stride'.
        CHECK_EQ(stride * coords_shape.dims(0), output_data.size());

        for (int i = 0; i < coords_shape.dims(0); ++i) {
            DCHECK_GE(coords_data[i], 0);
            DCHECK_LT(coords_data[i], input_shape.dims(0));
            DataType<Type>* out = output_data.data() + i * stride;
            const DataType<Type>* in = input_data.data() + coords_data[i] * stride;
        }
  }
}

```

**Comment by haozha111** [comment]
hey, sorry for late reply..

we've released a new mlir-based tflite converter. you can try with the new converter to see if the issue still happens.

To use it, please download latest tf-nightly, and then set `converter.experimental_new_converter = True`.
thanks!

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.
