### ISSUE TITLE
how to transfer ckpt to pb or saved model?

### ISSUE THREAD

**Issue by aohan237** [tensorflow/tensorflow#31397]
as the title shows, how we do this?

tensorlfow has lots of saved format, and version issues.

there is no such document,about how we can do this.

i search the similar issues, you all said these question maybe suitalbe for stackoverflow.

but none of you have answered the question.

maybe this is an document issue or not.

thank you very much if you can give me the instructions

**Comment by ymodak** [comment]
Have you tried using ```freeze_graph.py```.
https://github.com/tensorflow/tensorflow/blob/236a77594fec644e0676ffe9144ff047cd7142fd/tensorflow/python/tools/freeze_graph.py#L26

**Comment by aohan237** [comment]
thanks ,i will try.. it seems to be able to transfer ckpt to frozen_graph as pb.

what about the solutions for transfering to saved_model?

**Comment by ymodak** [comment]
See TensorFlow Saved Model https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/saved_model/README.md
Feel free to reopen if have any further problems. Thanks!
