### ISSUE TITLE
Upgrade python version in official tensorflow docker image

### ISSUE THREAD

**Issue by rabinandan** [tensorflow/tensorflow#31403]
Using docker image from tensorflow official website
[https://www.tensorflow.org/install#run-a-tensorflow-container](url) 
Installs python2.7 default, which is planned to be deprecated near in future.

> DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support

This issue is  request to provide updated python version with docker image.

**Comment by ravikyram** [comment]
@rabinandan 
Please, go through the below link and see if it helps you.Thanks!
https://github.com/tensorflow/tensorflow/issues/30057

**Comment by rabinandan** [comment]
Yes, It helped me. 
Thank You.

**Comment by ravikyram** [comment]
Are you satisfied with the resolution of your issue?<br> [Yes](https://docs.google.com/forms/d/e/1FAIpQLSfaP12TRhd9xSxjXZjcZFNXPGk4kc1-qMdv3gc6bEP90vY1ew/viewform?entry.85265664=Yes&entry.2137816233=31403)<br> [No](https://docs.google.com/forms/d/e/1FAIpQLSfaP12TRhd9xSxjXZjcZFNXPGk4kc1-qMdv3gc6bEP90vY1ew/viewform?entry.85265664=No&entry.2137816233=31403)
