### ISSUE TITLE
What is the correct  way to compile a 'so' file without "undefined reference to..." error?

### ISSUE THREAD

**Issue by MaeThird** [tensorflow/tensorflow#31407]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):Y
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux  5.2.5-arch1-1-ARCH
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below): 1.13.1
- Python version: 3.7
- Bazel version (if compiling from source): 0.27.0- (@non-git)
- GCC/Compiler version (if compiling from source): 9.1.0
- CUDA/cuDNN version: cuda: 10.1 ,cudnn: 7.6
- GPU model and memory: 16G

I'm using the **tfcompile** to convert my trained model into object files. **Everything works fine if I compile it as** `cc_binary` with **Bazel**.
**As I must wrap all the tf-relative codes into a single part**, I compiled the converted .o files with `cc_library` and got a so file indeed.But when it was linked as a third lib in non-bazel env it issued like this:
```
/usr/bin/ld: ./libcaptchaLib.so: undefined reference to `xla::ExecutableRunOptions::set_intra_op_thread_pool(Eigen::ThreadPoolDevice const*)'
/usr/bin/ld: ./libcaptchaLib.so: undefined reference to `__xla_cpu_runtime_EigenConvF32'
/usr/bin/ld: ./libcaptchaLib.so: undefined reference to `tensorflow::XlaCompiledCpuFunction::~XlaCompiledCpuFunction()'
/usr/bin/ld: ./libcaptchaLib.so: undefined reference to `__xla_cpu_runtime_EigenMatMulF32'
/usr/bin/ld: ./libcaptchaLib.so: undefined reference to `typeinfo for tensorflow::XlaCompiledCpuFunction'
/usr/bin/ld: ./libcaptchaLib.so: undefined reference to `tensorflow::XlaCompiledCpuFunction::Run()'
```
I also tried to **add these missing objs into a static lib and passed it to the linker hand by hand.
It works but really horrible because of the linkage chain**.
Is there a novel way to this case?
here is my **BUID** file:
```
cc_library(
    name = "captchaLib",
    srcs = [
    	 "captcha_run.cc",
	 "captcha.h",
	 "captcha_model.o",
	 "captcha_helper.o",
	 ],
    copts=["-fPIC","-std=c++11","-O3"],
    deps = [
       "//tensorflow/compiler/xla:shape_util",
         "//tensorflow/compiler/tf2xla:xla_compiled_cpu_function",
         "//tensorflow/core:framework_lite",
        "//third_party/eigen3",
       "@com_google_absl//absl/strings",
      ] + [
            "//tensorflow/compiler/xla/service/cpu:runtime_conv2d",
            "//tensorflow/compiler/xla/service/cpu:runtime_key_value_sort",
            "//tensorflow/compiler/xla/service/cpu:runtime_matmul",
            "//tensorflow/compiler/xla/service/cpu:runtime_single_threaded_conv2d",
            "//tensorflow/compiler/xla/service/cpu:runtime_single_threaded_matmul",
	    ],
    linkstatic=False,
)
```

**Comment by mihaimaruseac** [comment]
This is not really a TensorFlow issue, more like a Bazel one and the best way to ask would be on StackOverflow or Bazel repo.

The undefined reference comes from an object not being present at the moment you get the error (link time or run time).
