### ISSUE TITLE
Support for Unix/Linux netpbm (.pgm/.ppm) image formats

### ISSUE THREAD

**Issue by GrHound** [tensorflow/tensorflow#31402]
As we are dealing with very large problems with millions of images, cropping small images
from hundreds of thousands of large images and then transforming the ROIs to .jpg or .png for tensorflow only, is a real resource problem. See .pdf of article on: arXiv:1904.08421
This is especially true because this is a dynamic environment with new large images coming in all the time such that any form of prepackaging data sets becomes a stumbling block in resource space. It would make a tremendous difference if TF were able to handle raw Unix/Linux NetPBM images directly (binary: .pbm, grey: .pgm, color: .ppm). See: https://sourceforge.net/projects/netpbm/  (600 package downloads per month).
On the web, proposals are made to handle NetPBM conversion in Python, but that does not appear to be the most efficient path. With our problem scale, the communication, I/O and conversion overhead is much more noticeable than in the well-known closed-data set TF examples.

**Comment by mihaimaruseac** [comment]
While this would be a good addition, I think this would have to come from the community via a chain of PRs.

**Comment by GrHound** [comment]
OK, I see. C++ versions for I/O in this format exist: (https://people.sc.fsu.edu/~jburkardt/cpp_src/pbmb_io/pbmb_io.html)
The three formats are very simple, that is why they won't disappear. It should be doable
but I don't know how complex the I/O section in TF has been organized: C++ gives humans
a lot of tempting space to generate complexity :).
I'll look in my group for volunteers to get this started.
PS our peak load was 1.3 billion files on a single fs mount point.

**Comment by mihaimaruseac** [comment]
I might get some cycles next year if there's no takers by then

**Comment by GrHound** [comment]
Dear Mihai,

what do you mean with 'cycles'? (I am not a GitHub expert user)
I suppose it is positive for the suggestion (?)

Best regards!
Lambert
________________________________

**Comment by alextp** [comment]
This should be in the [tensorflow/io](http://github.com/tensorflow/io/) repository

**Comment by yongtang** [comment]
@GrHound I added a PR tensorflow/io#599 in  [tensorflow/io](http://github.com/tensorflow/io/)  repo for PBM(PGM/PPM) support. You can take a look if you are interested.
