### ISSUE TITLE
Does the forward propagation of tensorflow code really use GPUs?

### ISSUE THREAD

**Issue by ZesenChen** [tensorflow/tensorflow#31404]
https://stackoverflow.com/questions/57372076/does-the-forward-propagation-of-tensorflow-code-really-use-gpus

**Comment by oanush** [comment]
@ZesenChen ,
Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version.Thanks!

**Comment by ZesenChen** [comment]
> @ZesenChen ,
> Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version.Thanks!

The tensorflow version is 1.12 with python=3.5, the GPU is K20, but I don't know the operating system because I run it on the ML Platform of my company. 
I think the reason for this may be that the time spent on slicing and merging data is longer than that spent on forward propagation for one batch. But I am not sure.

**Comment by oanush** [comment]
@ZesenChen ,
When tried executing the code given, error `NameError: name 'timesteps' is not define` was faced.Thanks

**Comment by oanush** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
