### ISSUE TITLE
ImportError: DLL load failed: %1 is not a valid Win32 application.

### ISSUE THREAD

**Issue by mmusil25** [tensorflow/tensorflow#31414]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Windows 10):
- TensorFlow installed from (source or binary): Binary
- TensorFlow version: 1.13.1
- Python version: 3.6.8
- Installed using virtualenv? pip? conda?: conda 
- CUDA/cuDNN version:  10.0.130/ 7.6.0
- GPU model and memory:  Running on laptop to demo a conda environment build so not using GPU, 16 GB memory 

**Describe the problem**

After building my conda environment using the environment.yml from a known working system, I encounter a "ImportError: DLL load failed: %1 is not a valid Win32 application." issue which occurs when the script attempts to import pywrap_tensorflow (see traceback below). This is strange because both the origin computer (from which the environment was copied) and the source computer are 64-bit and tensorflow is certainly not a 32-bit application. The error seems to be coming from the imp module. Has anyone else encountered a similar issue? 

**Provide the exact sequence of commands / steps that you executed before running into the problem**

conda env create -n <envname> -f  <Environment.yml>
python <main.py>

**Any other info / logs**

Traceback (most recent call last):
  File "hyperparam_grid_search.py", line 10, in <module>
    import tensorflow as tf
  File "C:\Users\mmusil\.conda\envs\AutoTune5\lib\site-packages\tensorflow\__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "C:\Users\mmusil\.conda\envs\AutoTune5\lib\site-packages\tensorflow\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Users\mmusil\.conda\envs\AutoTune5\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg).pywrap_tensorflow_internal import *
ImportError: Traceback (most recent call last):ib\site-packages\tens  File "C:\Users\mmusil\.conda\envs\AutoTune5\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *s\tens  File "C:\Users\mmusil\.conda\envs\AutoTune5\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()l', fp, pathna  File "C:\Users\mmusil\.conda\envs\AutoTune5\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper_module
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)\mmusil\.conda\envs\AutoTune5\lib\imp.py", line 343,  File "C:\Users\mmusil\.conda\envs\AutoTune5\lib\imp.py", line 243, in load_moduled(spec)
    return load_dynamic(name, filename, file)id Win32 application.
  File "C:\Users\mmusil\.conda\envs\AutoTune5\lib\imp.py", line 343, in load_dynamic
    return _load(spec)ive TensorFlow runtime.
ImportError: DLL load failed: %1 is not a valid Win32 application.

**Comment by mihaimaruseac** [comment]
Can you try with 1.13.2 please?

**Comment by mmusil25** [comment]
> Can you try with 1.13.2 please?

I can't find a 1.13.2 version avaiable for Conda anywhere. And installing via pip results in another series of 'DLL module load failure' errors.

**Comment by gadagashwini** [comment]
@mmusil25 I tried on my system its working fine.
`pip install tensorflow==1.13.2` . 
Can you provide the new error log. Thanks!

**Comment by mmusil25** [comment]
@gadagashwini 

So I did a fresh install of my environment using pip and virtualenv and encountered a similar "DLL Module failed to load error". I then installed tensorflow 1.13.2 and it seems to be working just fine. Thanks!
