### ISSUE TITLE
//tensorflow/contrib/metrics:metric_ops_test fails with Assertion error

### ISSUE THREAD

**Issue by abhay1722** [tensorflow/tensorflow#31413]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):  Linux Ubuntu 18.04 s390x
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: NA
- TensorFlow installed from (source or binary): Source
- TensorFlow version (use command below): 1.14.0
- Python version: 2.7.15
- Bazel version (if compiling from source): 0.24.1
- GCC/Compiler version (if compiling from source): gcc (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
- CUDA/cuDNN version: NA
- GPU model and memory: NA

**Describe the current behavior**
python tensorflow/contrib/metrics/python/ops/metric_ops_test.py
```
======================================================================
FAIL: testWithMultipleUpdates (__main__.AucWithConfidenceIntervalsTest)
testWithMultipleUpdates (__main__.AucWithConfidenceIntervalsTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/absl/third_party/unittest3_backport/case.py", line 37, in testPartExecutor
    yield
  File "/usr/local/lib/python2.7/dist-packages/absl/third_party/unittest3_backport/case.py", line 162, in run
    testMethod()
  File "tensorflow/contrib/metrics/python/ops/metric_ops_test.py", line 2313, in testWithMultipleUpdates
    batch_size = 50
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/test_util.py", line 1073, in decorated
    return f(*args, **kwds)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/test_util.py", line 2303, in assertAllClose
    self._assertAllCloseRecursive(a, b, rtol=rtol, atol=atol, msg=msg)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/test_util.py", line 2272, in _assertAllCloseRecursive
    (path_str, path_str, msg)))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/test_util.py", line 2207, in _assertArrayLikeAllClose
    a, b, rtol=rtol, atol=atol, err_msg="\n".join(msgs), equal_nan=True)
  File "/usr/local/lib/python2.7/dist-packages/numpy/testing/_private/utils.py", line 1501, in assert_allclose
    verbose=verbose, header=header, equal_nan=equal_nan)
  File "/usr/local/lib/python2.7/dist-packages/numpy/testing/_private/utils.py", line 827, in assert_array_compare
    raise AssertionError(msg)
AssertionError:
Not equal to tolerance rtol=1e-06, atol=1e-06
Mismatched value: a is different from b.
not close lhs = 0.753345469611
not close rhs = 0.753343403339
not close dif = 2.0662712803e-06
not close tol = 1.75334340334e-06
dtype = float64, shape = ()
Mismatch: 100%
Max absolute difference: 2.06627128e-06
Max relative difference: 2.74280132e-06
 x: array(0.753345)
 y: array(0.753343, dtype=float32)
```

**Describe the expected behavior**
The test should pass on s390x.

**Comment by abhay1722** [comment]
Hi,
As seen above, the test fails due to very small difference in `auc.auc.eval()`.
We have tried changing the `scale` value from `0.2` to `0.23` while calculating `noise` as below:-
```diff
diff --git a/tensorflow/contrib/metrics/python/ops/metric_ops_test.py b/tensorflow/contrib/metrics/python/ops/metric_ops_test.py
index aec07241e7..3ece21da96 100644
--- a/tensorflow/contrib/metrics/python/ops/metric_ops_test.py
+++ b/tensorflow/contrib/metrics/python/ops/metric_ops_test.py
@@ -2325,7 +2325,7 @@ class AucWithConfidenceIntervalsTest(test.TestCase):
       sess.run(variables.local_variables_initializer())
       for _ in xrange(num_batches):
         new_labels = np.random.randint(0, 2, size=batch_size)
-        noise = np.random.normal(0.0, scale=0.2, size=batch_size)
+        noise = np.random.normal(0.0, scale=0.23, size=batch_size)
         new_predictions = 0.4 + 0.2 * new_labels + noise
         labels = np.concatenate([labels, new_labels])
         predictions = np.concatenate([predictions, new_predictions])
```
The test passes with the above change on s390x as well as x86.
Could you please comment if this change is appropriate?

**Comment by abhay1722** [comment]
@ymodak @martinwicke Can you please comment on this?

**Comment by martinwicke** [comment]
This seems fine to me, although this "fix" passes only accidentally, I think.

I will note that the implied imprecision on BE is troubling, do we understand why this is?

**Comment by abhay1722** [comment]
@martinwicke Thanks for the reply.
We observed with scale = 0.2, the assertion fails at 55th iteration with expected auc versus evaluated auc in https://github.com/tensorflow/tensorflow/blob/v1.14.0/tensorflow/contrib/metrics/python/ops/metric_ops_test.py#L2309 with values as below:  

```
(Pdb) p expected_auc
0.7533454696106663
(Pdb) p auc.auc.eval()
0.7533434
```

Please find more information below:
 
On s390x:-
```
(Pdb) p _
55
(Pdb) sess.run(tf_labels)
array([1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1,
       1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0,
       0, 0, 0, 1, 1, 0], dtype=int32)
(Pdb) sess.run(tf_predictions)
array([0.014863  , 0.4844158 , 0.352837  , 0.54202855, 0.38126653,
       0.61508274, 0.25054544, 0.2837999 , 0.7139573 , 0.45872432,
       0.7386131 , 0.48689318, 0.9119968 , 0.33785316, 0.5350666 ,
       0.28273708, 0.5385499 , 0.36344397, 0.38391426, 0.60041904,
       0.60369414, 0.777326  , 0.24041872, 0.39783546, 0.3715972 ,
       0.62186974, 0.46711922, 0.6665319 , 0.73751754, 0.20932944,
       0.84545594, 0.357602  , 0.5856815 , 0.40968195, 0.20739971,
       0.40517867, 0.33178496, 0.8172757 , 0.51139665, 0.42816433,
       0.38682312, 0.82141477, 0.4720431 , 0.53740764, 0.83355075,
       0.25388297, 0.5596692 , 0.6266968 , 0.42656004, 0.54356265],
      dtype=float32)
(Pdb) p expected_auc
0.7533454696106663
(Pdb) p auc.auc.eval()
0.7533434
```

As we can see above, the imprecision between the `expected_auc` and `auc.auc.eval()` on BE is too big to handle at this particular iteration, hence `AssertionError` is thrown.

On x86:-
```
(Pdb) sess.run(tf_labels)
array([1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1,
       1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0,
       0, 0, 0, 1, 1, 0], dtype=int32)
(Pdb) sess.run(tf_predictions)
array([ 0.7787361 ,  0.33818543,  0.3439809 ,  0.44263282,  0.52661246,
        0.28824544,  0.9627949 ,  0.42855707,  0.16991597,  0.47528434,
        0.6176221 ,  0.21204723,  0.6784733 ,  0.41393727,  0.20120378,
        0.13405843,  0.68943506,  0.26077443,  0.4316638 ,  0.40254095,
       -0.08317755,  0.5817798 ,  0.67597103,  0.14249034,  0.33138826,
        0.5813278 ,  0.9118691 ,  0.68611795,  0.74210596,  0.42553538,
        0.51080304,  0.2921602 ,  0.7383272 ,  0.58153254,  0.22918795,
        0.7137467 ,  0.18442799,  1.0695232 ,  1.141225  ,  0.2697277 ,
        0.39005813,  0.4159579 ,  0.6735845 ,  0.51834685,  0.06926602,
        0.1939108 ,  0.5681722 ,  0.6900052 ,  0.46803212,  0.13521548],
      dtype=float32)
(Pdb) p expected_auc
0.7533454696106663
(Pdb) p auc.auc.eval()
0.75334555
```

However, when I changed the `scale` value to `0.23`, the test run passes.
So, Should I go ahead with this change and raise a PR?

**Comment by martinwicke** [comment]
My concern is that something on s390x is lowering expectations for
precision all over the place. Do we understand why that is? I'd rather
avoid increasing test tolerances. I'd also like to avoid fixes like the one
you propose, which make this test extremely brittle (I suppose using
scale=0.23 just hit a particularly lucky combination of numbers which
doesn't every hit the worst case).

You can send a PR with your proposal -- this is a fairly harmless fix. But
I will warn that this might break again at any time, and I'd feel much more
comfortable if we understood why numerics on s390x behave differently.

**Comment by abhay1722** [comment]
@martinwicke Thanks for the reply.
We are still debugging on the issue of why exactly the numerics on s390x behave differently and also we are checking if its an issue with NumPy (similar to [12963](https://github.com/tensorflow/tensorflow/pull/12963) and [14017](https://github.com/tensorflow/tensorflow/issues/14017)).

Could you please help us out, where exactly the value of `auc` gets calculated and how?

**Comment by martinwicke** [comment]
This seems to pertain to contrib/metrics, which are deprecated. The
computation you are interested in probably happens here:
https://www.tensorflow.org/api_docs/python/tf/contrib/metrics/streaming_auc

**Comment by abhay1722** [comment]
@martinwicke Thanks for the direction.
After debugging further, we were able to figure out that, for this particular test, the `auc` value gets calculated using placement values [here](https://github.com/tensorflow/tensorflow/blob/87989f69597d6b2d60de8f112e1e3cea23be7298/tensorflow/contrib/metrics/python/ops/metric_ops.py#L1230).

So, We tried printing the values of `auc`, `lower` and `upper` using below:-
```
(Pdb) l
1340          math_ops.reduce_sum(weights_0 * (1. - placement_values_0)) /
1341          (total_0 + _EPSILON))
1342      auc_1 = (
1343          math_ops.reduce_sum(weights_1 * (placement_values_1)) /
1344          (total_1 + _EPSILON))
1345 ->   auc = array_ops.where(math_ops.less(total_0, total_1), auc_1, auc_0)
1346
1347      # Calculate variance and standard error using the placement values.
1348      var_0 = (
1349          math_ops.reduce_sum(
1350              weights_0 * math_ops.square(1. - placement_values_0 - auc_0)) /
(Pdb) from tensorflow.python.ops import variables
(Pdb) sess.run(variables.local_variables_initializer())
(Pdb) sess.run(auc)
```

However, I encountered the following error:-
```
*** FailedPreconditionError: Attempting to use uninitialized value Variable
         [[node Variable/read (defined at /usr/local/lib/python2.7/dist-packages/absl/third_party/unittest3_backport/case.py:162) ]]
```

In fact, this error is displayed, whenever we try to display the values of other tensors( such as `placement_values_0` ,`placement_values_1`, `lower`, `upper`) too.

Could you please help me in finding out what exact values of these tensors are, as we might be able to find the exact reason why the values are getting computed differently.

**Comment by abhay1722** [comment]
@martinwicke Any Insights on the above issue? 
I have even tried initializing these values using `initialized_value()`, but still I encounter the same issue.

**Comment by abhay1722** [comment]
Closing this issue since, contrib folder is removed from master.
