### ISSUE TITLE
DeprecationWarning: the imp module is deprecated

### ISSUE THREAD

**Issue by carlosgalvezp** [tensorflow/tensorflow#31412]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 18.04
- **TensorFlow installed from (source or binary)**: binary (pip)
- **TensorFlow version (use command below)**: tensorflow-gpu==2.0.0b1
- **Python version**: 3.6.8
- **CUDA/cuDNN version**: 10.0.130/7.6.2
- **Exact command to reproduce**:

Create `test.py` file with the following content:
`import tensorflow as tf`

Run pytest (5.0.1) on it:
`pytest test.py`

Result:
`============================================================================================= warnings summary =============================================================================================
venv/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py:15
  venv/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py:15: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
    import imp
`

### Describe the problem
TensorFlow is using "imp" which is deprecated since Python 3.4. Are there plans to update it?
Thanks!

**Comment by mihaimaruseac** [comment]
Confirmed.

There are a few more warnings which also show when you try `python test.py` but the `imp` deprecation doesn't show up in that case.

Note that this file is automatically generated by SWIG and there's a plan to replace SWIG with pybind11: https://github.com/tensorflow/community/pull/67

**Comment by jvishnuvardhan** [comment]
@carlosgalvezp Is this still an issue? Can you check with `TF2.0` and let us know whether the issue persists with latest TF version. Thanks!

**Comment by y26805** [comment]
@jvishnuvardhan Hi I am using TF2.0 and I still get a DeprecationWarning.
(Using Python 3.7.3)
```
 /Users/xxxxxx/.yyyyy/lib/python3.7/site-packages/tensorflow_core/python/pywrap_tensorflow_internal.py:15: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
```

**Comment by aathan** [comment]
This may help:
   import warnings
   warnings.simplefilter("ignore")

**Comment by PedroNan** [comment]
Hello! Im using TF 2.1 and still the problem while import.  
DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses ModuleNotFoundError: No module named 'tensorflow.python.tools'; tensorflow.python' is not a package.
Any advice?

**Comment by Superhzf** [comment]
I'm using TF 2.3.1, I still get the same warning.

**Comment by Saduf2019** [comment]
@carlosgalvezp 
Could you please verify on tf-nightly [2.4.0-dev20201020] and let us know if you still see the warnings.

**Comment by ogencoglu** [comment]
Same warning on TF 2.3.0.

**Comment by jzhang533** [comment]
Same warning on TF 2.4.1.

**Comment by golubitsky** [comment]
I'm seeing the same warning from a different line on TF 2.5.0.

```
  /usr/local/lib/python3.8/site-packages/tensorflow/python/autograph/impl/api.py:22: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
    import imp
```

**Comment by giuseppefilitto** [comment]
same here, TF 2.5.0 native version for apple silicon MacBook 


```
./../miniforge3/envs/tf2.5/lib/python3.9/site-packages/tensorflow/python/autograph/impl/api.py:22
  /Users/giuseppefilitto/miniforge3/envs/tf2.5/lib/python3.9/site-packages/tensorflow/python/autograph/impl/api.py:22: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
    import imp

-- Docs: https://docs.pytest.org/en/stable/warnings.html

```

**Comment by ansar-sa** [comment]
Bump

**Comment by mihaimaruseac** [comment]
I think the best way forward is to send a PR

**Comment by cako** [comment]
Same here on 2.6.0

**Comment by mihaimaruseac** [comment]
> I think the best way forward is to send a PR

This is still true.

We don't see this in our CI

**Comment by yongtang** [comment]
Added a PR #51663 to get the deprecation message fixed.

**Comment by YoniChechik** [comment]
This is still happaning in TF2.7.0

**Comment by mihaimaruseac** [comment]
Please note that we don't see this in our CI. This points to an issue with your environment instead of the TF code itself. Can you post the output of `pip list` for example, to start the debugging process?

**Comment by mohantym** [comment]
Hi @carlosgalvezp !

Is this issue still valid ?  did not find issue with Python 3.7 and TF 2.7, 2.8 , 2.9 through Colab . 
Could you reply  on @mihaimaruseac's comment ?

Thank you!

**Comment by carlosgalvezp** [comment]
Hi @mohantym !

Testing on:

- Ubuntu 20.04 docker image
- Python 3.8
- TensorFlow 2.9.1

With the reproducer code of the original post of this issue, gives:

Gives:

```
root@ee5b086171df:/# pytest test.py 
======================================== test session starts ========================================
platform linux -- Python 3.8.10, pytest-7.1.2, pluggy-1.0.0
rootdir: /
collected 0 items                                                                                   

========================================= warnings summary ==========================================
usr/local/lib/python3.8/dist-packages/flatbuffers/compat.py:19
  /usr/local/lib/python3.8/dist-packages/flatbuffers/compat.py:19: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
    import imp

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
======================================== 1 warning in 2.00s =========================================
```

Here's the output of `pip list`:

```
root@ee5b086171df:/# pip list
Package                      Version
---------------------------- ---------
absl-py                      1.2.0
astunparse                   1.6.3
attrs                        21.4.0
cachetools                   5.2.0
certifi                      2022.6.15
charset-normalizer           2.1.0
flatbuffers                  1.12
gast                         0.4.0
google-auth                  2.9.1
google-auth-oauthlib         0.4.6
google-pasta                 0.2.0
grpcio                       1.47.0
h5py                         3.7.0
idna                         3.3
importlib-metadata           4.12.0
iniconfig                    1.1.1
keras                        2.9.0
Keras-Preprocessing          1.1.2
libclang                     14.0.1
Markdown                     3.4.1
MarkupSafe                   2.1.1
numpy                        1.23.1
oauthlib                     3.2.0
opt-einsum                   3.3.0
packaging                    21.3
pip                          22.2
pluggy                       1.0.0
protobuf                     3.19.4
py                           1.11.0
pyasn1                       0.4.8
pyasn1-modules               0.2.8
pyparsing                    3.0.9
pytest                       7.1.2
requests                     2.28.1
requests-oauthlib            1.3.1
rsa                          4.9
setuptools                   45.2.0
six                          1.16.0
tensorboard                  2.9.1
tensorboard-data-server      0.6.1
tensorboard-plugin-wit       1.8.1
tensorflow                   2.9.1
tensorflow-estimator         2.9.0
tensorflow-io-gcs-filesystem 0.26.0
termcolor                    1.1.0
tomli                        2.0.1
typing_extensions            4.3.0
urllib3                      1.26.11
Werkzeug                     2.2.0
wheel                        0.34.2
wrapt                        1.14.1
zipp                         3.8.1
```

It seems the problem now stems from `flatbuffers` (a dependency of TF?) instead of TensorFlow, so I'd be OK with closing this particular issue if you think it makes sense.

**Comment by mihaimaruseac** [comment]
Closing. Please open against `flatbuffers` (though they might have already fixed it in newer releases, that TF cannot use yet)

**Comment by mohantym** [comment]
Are you satisfied with the resolution of your issue?
[Yes](https://goo.gl/forms/Oe0tEvODFRoI2gJF3)
[No](https://goo.gl/forms/fUjzOfrtkFbrOT8d2)
