### ISSUE TITLE
Cannot install TF wheel file for Python3 due to functools32 dependency

### ISSUE THREAD

**Issue by ajarthurs** [tensorflow/tensorflow#31420]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 16.04 (Linux v5.1.0)
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): source
- TensorFlow version: b28755fbd2f33baaff2ce703f456513f087f8e76 (`master`)
- Python version: 3.5.2
- Installed using virtualenv? pip? conda?: pip3 19.2.1
- Bazel version (if compiling from source): 0.28.1
- GCC/Compiler version (if compiling from source): 5.4.0
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

**Describe the problem**
Since commit 82c46d74d9ece4f6b5832f27a7ae580d95e1a312, `pip3` refuses to install the tensorflow wheel file due to the missing `functools32` dependency. Since I'm running Python3, I cannot install `functools32` since it is a backport for Python2.

**Provide the exact sequence of commands / steps that you executed before running into the problem**
```
# Inside working copy of tensorflow
$ bazel build //tensorflow/tools/pip_package:build_pip_package
...
$ ./bazel-bin/tensorflow/tools/pip_package/build_pip_package /data/Packages/
INFO: Elapsed time: 61.754s, Critical Path: 33.82s
INFO: 533 processes: 533 local.
INFO: Build completed successfully, 753 total actions
Wed Aug 7 12:47:45 CDT 2019 : === Preparing sources in dir: /tmp/tmp.jkwGwPI847
...
Wed Aug 7 12:49:09 CDT 2019 : === Building wheel
warning: no files found matching '*.pyd' under directory '*'
warning: no files found matching '*.pd' under directory '*'
warning: no files found matching '*.dylib' under directory '*'
warning: no files found matching '*.dll' under directory '*'
warning: no files found matching '*.lib' under directory '*'
warning: no files found matching '*.h' under directory 'tensorflow/include/tensorflow'
warning: no files found matching '*' under directory 'tensorflow/include/third_party'
Wed Aug 7 12:49:40 CDT 2019 : === Output wheel file is in: /data/Packages/

$ pip3 install --upgrade /data/Packages/tensorflow-1.14.0-cp27-cp27mu-linux_x86_64.whl
Processing /data/Packages/tensorflow-1.14.0-cp27-cp27mu-linux_x86_64.whl
Collecting protobuf>=3.6.1 (from tensorflow==1.14.0)
  Using cached https://files.pythonhosted.org/packages/22/cb/8ca68af4233c09f2dd9833f3b9c6d8e706da2d33988dfb3732a777e15e4b/protobuf-3.9.1-cp35-cp35m-manylinux1_x86_64.whl
Collecting gast>=0.2.0 (from tensorflow==1.14.0)
Collecting tensorflow-estimator<1.15.0rc0,>=1.14.0rc0 (from tensorflow==1.14.0)
  Using cached https://files.pythonhosted.org/packages/3c/d5/21860a5b11caf0678fbc8319341b0ae21a07156911132e0e71bffed0510d/tensorflow_estimator-1.14.0-py2.py3-none-any.whl
Collecting keras-applications>=1.0.8 (from tensorflow==1.14.0)
  Using cached https://files.pythonhosted.org/packages/71/e3/19762fdfc62877ae9102edf6342d71b28fbfd9dea3d2f96a882ce099b03f/Keras_Applications-1.0.8-py3-none-any.whl
Collecting termcolor>=1.1.0 (from tensorflow==1.14.0)
Collecting opt-einsum>=2.3.2 (from tensorflow==1.14.0)
Collecting tensorboard<1.15.0,>=1.14.0 (from tensorflow==1.14.0)
  Using cached https://files.pythonhosted.org/packages/91/2d/2ed263449a078cd9c8a9ba50ebd50123adf1f8cfbea1492f9084169b89d9/tensorboard-1.14.0-py3-none-any.whl
Collecting functools32>=3.2.3 (from tensorflow==1.14.0)
  Using cached https://files.pythonhosted.org/packages/c5/60/6ac26ad05857c601308d8fb9e87fa36d0ebf889423f47c3502ef034365db/functools32-3.2.3-2.tar.gz
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-hmfnihxv/functools32/setup.py'"'"'; __file__='"'"'/tmp/pip-install-hmfnihxv/functools32/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info
         cwd: /tmp/pip-install-hmfnihxv/functools32/
    Complete output (1 lines):
    This backport is for Python 2.7 only.
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by angersson** [comment]
It looks like this package was built in Python 2.7 mode:

$ pip3 install --upgrade /data/Packages/tensorflow-1.14.0-**cp27-cp27**mu-linux_x86_64.whl

When you ran `./configure` prior to your first call to Bazel, Ubuntu 16 may have defaulted to Python 2, so the package was built in Python 2 mode. You may have to change the Python path in another call to `./configure`.

**Comment by ajarthurs** [comment]
@angersson Thanks. That makes sense. I attached my `.tf_configure.bazelrc` used throughout the build. I thought I pointed `configure` to the Python 3 executable and library (3.5). Did I miss something?

```
build --action_env PYTHON_BIN_PATH="/usr/bin/python3"
build --action_env PYTHON_LIB_PATH="/usr/lib/python3.5"
build --python_path="/usr/bin/python3"
build:xla --define with_xla_support=true
build --config=xla
build --action_env TF_NEED_OPENCL_SYCL="0"
build --action_env TF_NEED_ROCM="0"
build --action_env TF_NEED_CUDA="0"
build --action_env TF_DOWNLOAD_CLANG="0"
build:opt --copt=-march=native
build:opt --copt=-Wno-sign-compare
build:opt --host_copt=-march=native
build:opt --define with_default_optimizations=true
build:v2 --define=tf_api_version=2
test --flaky_test_attempts=3
test --test_size_filters=small,medium
test --test_tag_filters=-benchmark-test,-no_oss,-oss_serial
test --build_tag_filters=-benchmark-test,-no_oss
test --test_tag_filters=-gpu
test --build_tag_filters=-gpu
build --action_env TF_CONFIGURE_IOS="0"
```

[tf_configure.bazelrc.txt](https://github.com/tensorflow/tensorflow/files/3487645/tf_configure.bazelrc.txt)

?

**Comment by ajarthurs** [comment]
I found the culprit. I started a new working copy, ran `configure`, and noticed it generated `tools/python_bin_path.sh`, which I was missing. Lesson is re-run `configure` after a `git pull`.
```
# tools/python_bin_path.sh
export PYTHON_BIN_PATH="/usr/bin/python3"
```

The wheel builder produced `tensorflow-1.14.0-cp35-cp35m-linux_x86_64.whl`, which indicates Python 3.5. The new wheel installs without issues, so closing this issue.
