### ISSUE TITLE
SIGABRT on `tf.image.encode_png` with empty tensor

### ISSUE THREAD

**Issue by wchargin** [tensorflow/tensorflow#31429]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): gLinux (like Debian)
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): tf-nightly-2.0-preview==2.0.0.dev20190807
- TensorFlow version (use command below): v1.12.1-8193-ge7d48dc 2.0.0-dev20190807
- Python version: 3.6.6
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: N/A
- GPU model and memory: None

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**

Calling `tf.image.encode_png` kills the process with SIGABRT if you pass
a tensor that has no elements.

**Describe the expected behavior**

It should never SIGABRT.

**Code to reproduce the issue**

```python
import tensorflow as tf

image = tf.cast(tf.tile([[[0, 0, 0]]], [0, 0, 1]), tf.uint8)
# Or: = tf.cast(tf.reshape([], [0, 0, 3]))
try:
  tf.print(image)
  tf.print(tf.shape(image))
  tf.image.encode_png(image)
finally:
  print("We never get here!")
```

```
$ TF_CPP_MIN_LOG_LEVEL=1 python test.py
[]
[0 0 3]
2019-08-07 16:32:12.864303: F tensorflow/core/lib/png/png_io.cc:347] 'image' Must be non NULL
Aborted
$ echo $?
134
```

**Other info / logs**

This also affects `tf.summary.image`.

**Comment by oanush** [comment]
Issue replicating with tf-nightly-2.0-preview, please find the [gist](https://colab.sandbox.google.com/drive/1seME-cxmUIJkV6sgxGRKxPJPeROp2VcC#scrollTo=ZZmqnscz-4m5) of colab.Thanks

**Comment by Soniyanayak51** [comment]
Beginner here. Would like to work on this issue. Any leads?

**Comment by mihaimaruseac** [comment]
@Soniyanayak51 check `tensorflow/core/kernels/encode_png_op.cc`, in `Compute`, just before the `png::WriteImageToBuffer` gets called, `image.flat<..>.data()` should be checked. It currently returns nullptr which then causes the abort.

**Comment by Soniyanayak51** [comment]
Thanks for the reply. On it

**Comment by wchargin** [comment]
@oanush: Not sure what you mean. Your Colab is not publicly visible, and
I can reproduce this in a fresh virtualenv:

```
$ cd "$(mktemp -d)"
$ virtualenv -q -p python3.6 ./ve
$ . ./ve/bin/activate
(ve) $ pip install -q tf-nightly-2.0-preview==2.0.0.dev20190807
(ve) $ python
Python 3.6.7 (default, Oct 21 2018, 08:08:16) 
[GCC 8.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
>>> tf.__version__
'2.0.0-dev20190807'
>>> image = tf.cast(tf.tile([[[0, 0, 0]]], [0, 0, 1]), tf.uint8)
>>> tf.print(image)
[]
>>> tf.print(tf.shape(image))
[0 0 3]
>>> tf.image.encode_png(image)
2019-08-08 10:28:38.860641: F tensorflow/core/lib/png/png_io.cc:347] 'image' Must be non NULL
Aborted
(ve) $ echo $?
134
```

**Comment by Soniyanayak51** [comment]
@mihaimaruseac 
Sorry, I am stuck with running tests here. Any leads on how to test code easily before raising a PR?

**Comment by mihaimaruseac** [comment]
I would build a pip package, install it in a virtualenv and test with the code to reproduce posted at the beginning of the issue.

See https://www.tensorflow.org/install/source for how to build the pip package.

Then, if that works, we can continue making this either a Python integration test or converting it to a C++ test.

**Comment by yongtang** [comment]
Added a PR #33220 for the fix. /cc @mihaimaruseac please take a look.

**Comment by amahendrakar** [comment]
Was able to reproduce the issue with [TF v2.1](https://colab.research.google.com/gist/amahendrakar/855918e07fcb96fe091964a7b0c543be/2-1-template.ipynb) and [TF-nightly](https://colab.research.google.com/gist/amahendrakar/343256a8d0c24e08a95b050b90bc5942/tf-nightly.ipynb#scrollTo=ieAW-NK5iqpf) i.e. v2.2.0-dev20200327. Session crashes in both the cases. Please find the attached gist. Thanks!

**Comment by mihaimaruseac** [comment]
@amahendrakar there is no attached gist

**Comment by amahendrakar** [comment]
@mihaimaruseac,
TF 2.1 - https://colab.research.google.com/gist/amahendrakar/855918e07fcb96fe091964a7b0c543be/2-1-template.ipynb

TF-nightly - https://colab.research.google.com/gist/amahendrakar/343256a8d0c24e08a95b050b90bc5942/tf-nightly.ipynb#scrollTo=ieAW-NK5iqpf

Here are the direct links. Could you please check if these work? Thanks!

**Comment by Saduf2019** [comment]
Was able to reproduce the issue with TF v2.3 and [TF-nightly ](https://colab.research.google.com/gist/Saduf2019/007bcd1a40306bb9c57096a9c7bd1e8c/untitled359.ipynb)

**Comment by saikumarchalla** [comment]
@wchargin I tried to reproduce the issue in TF 2.5 and the session is not crashing  but facing different error. Please check the gist [here](url).Thanks!

**Comment by mihaimaruseac** [comment]
The error in the recent gist is the supposed error to prevent the crash. This is now fixed.
