### ISSUE TITLE
[TF 2.0 API Docs] tf.keras.backend.relu

### ISSUE THREAD

**Issue by mwinel** [tensorflow/tensorflow#31436]
## URL(s) with the issue:

https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/keras/backend/relu

## Description of the issue (what needs changing):

The documentation GitHub symbol link on the official `API_Docs` redirects to another symbol than the expected symbol.

### Correct links

No

### Parameters defined

No

### Returns defined

No

### Raises listed and defined
No

### Usage example

No

### Request visuals, if applicable

Yes

### Submit a pull request?

Are you planning to also submit a pull request to fix the issue? See the docs
contributor guide: https://www.tensorflow.org/community/contribute/docs and the
docs style guide: https://www.tensorflow.org/community/contribute/docs_style

**Comment by lamberta** [comment]
Pointing to the wrong place in the file. Should be here (or wherever it changes to): https://github.com/tensorflow/tensorflow/blob/r2.0/tensorflow/python/keras/backend.py#L4198

**Comment by MarkDaoust** [comment]
Hi @mwinel, thanks for reporting this.

It looks like this is caused by slippage between the contents of the 2.0b1 release that we generated the docs from, and the current state fo the 2.0 branch.

We will regenerate all the docs when 2.0rc0 is up. That will fix this and any other similar issues.
