### ISSUE TITLE
python API debugging best practices

### ISSUE THREAD

**Issue by konstantinARM** [tensorflow/tensorflow#31442]
Hi guys,

I work for ARM Ltd and we are looking into adding int16 quantization support for the TFLite format. For that, I would need to change the source code of some files, including the command-line interface implemented in /tensorflow/lite/python/tflite_convert.py. I was just wondering what is the most efficient way to debug my code and iterate quickly?

I am currently using CLIon+Google Bazel Plugin. This combination allows quick and convenient code development process. Thanks to the tools, I can place breakpoints, see variables, etc(only for CPP though). What is the most efficient way to debug python APIs?

I get, for example, I could rebuild the tflite_convert tool every time with the following command:
bazel build //tensorflow/lite/python:tflite_convert.

This is fine, but I can’t debug this executable, which is inconvenient and does not allow quick iterations.
May I ask you to share your best practices for tensorflow python APIs development?
Many thanks,
Konstantin

**Comment by Mycaster** [comment]
I prefer logging info  then setting breakpoints and debugging.
I have tried someway to debug python with cpp library, it's soo complicated

**Comment by ccnankai** [comment]
Hi @konstantinARM 
I would like to ask you which version of tensorflow, clion, can teach me the configuration process.

**Comment by gangmuk** [comment]
It has already been long time ago this is issued. But I am having hard time to build tensorflow using Clion. I want to do the exactly same thing you(issue writer) did such as adding break point in c++ files and build and debug using them. If you can see it, Could you explain how you did it? Thank you.

**Comment by sachinprasadhs** [comment]
Hi, there is a document available on Tensorflow on same topic [Post-training integer quantization with int16 activations](https://www.tensorflow.org/lite/performance/post_training_integer_quant_16x8). You can try the same.
Feel free to reopen the issue if the error still persists, Thank you.
