### ISSUE TITLE
Weird behavior with no skflow installation.

### ISSUE THREAD

**Issue by sterkhedkar** [tensorflow/tensorflow#3144]
Environment info: Pycharm-Community Editon
Operating System: Ubuntu-14.04-x64
Pip package: https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.9.0-cp27-none-linux_x86_64.whl
Tensorflow version 0.9.0 (from python -c import tensorflow)

When I was trying the text_classification examples from skflow repository (which are now moved to tensorflow), at line: `word_list = tf.unpack(word_vectors, axis=1)` it threw an error that says:
`TypeError: unpack() got an unexpected keyword argument 'axis'`

When I browsed the commit history on git, It says 

> 2 days ago: Switch from split_squeeze to tf.unpack where it makes sense.

earlier it was working fine. Also it works fine when I run it on machine with skflow installed on it.
I have used `tensorflow.contrib.learn as skflow` as directed on the tensorflow home page.But somehow it doesn't work.

I have explored the `tf.unpack()` to check if it takes `axis` as an argument, but it doesn't. When I pass some other number that 1 to the `tf.unpack()` it says `num can not infer from shape (?,50,10)`

**Comment by plaliberte** [comment]
Have you had any luck on this?  I am having the same issue.

**Comment by sterkhedkar** [comment]
Hard luck. It's not working. It's so worst that even after fresh installation it's still stuck there. And more importantly it works on the system with skflow installed on it. How's that possible?

**Comment by shawnjhenry** [comment]
I'm having the same issue as well with a fresh install.  When I remove the explicit "axis=" and just put the number in the correct position, unpack incorrectly infers that the number is the name of the op rather than the axis argument.  Any solution forthcoming?

**Comment by cslei** [comment]
I solved the problem. Update your tensorflow to 0.10.0 would help.
Just follow the document of pip-installation:
https://www.tensorflow.org/versions/r0.10/get_started/os_setup.html#pip-installation

**Comment by ilblackdragon** [comment]
It seems like this issue was just due to updated examples and old tensorflow. Updating tensorflow to any recent version would fix the issue.
Thanks!
