### ISSUE TITLE
Adding speech output for tensorflowlite apps

### ISSUE THREAD

**Issue by novice03** [tensorflow/tensorflow#31447]
Hello, I am currently building a image recognizer using tensorflow lite. I also wanted to add speech output with the prediction of the model. For example, if the model predicts that a given image is a daisy flower, it will say out loud "daisy".

**System information**
- TensorFlow version (you are using): Tensorflow lite 2.0
- Are you willing to contribute it (Yes/No): Yes

**Describe the feature and the current behavior/state.**

**Will this change the current api? How?** The api would be modified such that text to speech is involved.

**Who will benefit with this feature?** Adding speech would greatly help people with visual impairments, and benefit other app users in general.

**Any Other info.**

**Comment by JiayiFu** [comment]
It seems to be solved by recording some audios and then just playing it? The audios can be generated from TTS first. Or combine an image recognizer model and a TTS model in your apps?

**Comment by Vanrap** [comment]
@JiayiFu, that makes sense. I was thinking of that, but how exactly would I do that? Where do I add the TTS code in the tflite files? Is there a tflite documentation explaining the function of each file?

**Comment by rmothukuru** [comment]
@novice03,
Sorry for the delayed response. Can you please let us know if the [TF Lite Examples for Speech Commands](https://github.com/tensorflow/examples/tree/master/lite/examples/speech_commands/android) help you? Thanks!
