### ISSUE TITLE
Better documentation for Dataset.from_tensors/from_tensor_slices

### ISSUE THREAD

**Issue by karwa** [tensorflow/tensorflow#31440]
## URL(s) with the issue:

Please provide a link to the documentation entry, for example:
https://www.tensorflow.org/api_docs/python/tf/data/Dataset#from_tensor_slices

## Description of issue (what needs changing):

While following Google's ML crash course, I found it very difficult to understand the difference between `Dataset.from_tensors/from_tensor_slices` and when to use each. One thing that confused me was that `from_tensors` only creates a single tensor, despite the name including the plural form "tensors".

Beginners get introduced to these APIs very early, but the current documentation consists of one terse sentence about behaviour (plus a multi-line warning about memory usage):

```
FTS:
Creates a Dataset whose elements are slices of the given tensors.

FT:
Creates a Dataset with a single element, comprising the given tensors.
```

I think this would benefit from some elaboration and a clearer description of how the two are related. Given that users enocunter this API very early, the behaviour should ideally be obvious. A small example would help communicate this, e.g:

```
my_data = { "my_feature" : [ [1, 2, 3], [4, 5, 6] ] }
tf.data.Dataset.from_tensors(my_data) # Models a single, 2x3 tensor.
```

```
my_data = { "my_feature" : [ [1, 2, 3], [4, 5, 6] ] }
tf.data.Dataset.from_tensor_slices(my_data) # Splits on rows. Models two, 1x3 tensors.
```

### Correct links

Fine AFAIK

### Parameters defined

Fine AFAIK

### Returns defined

Fine AFAIK

### Raises listed and defined

Fine AFAIK

### Usage example

**There is currently no usage example, and I think the documentation would greatly benefit from one.**

### Request visuals, if applicable

There are currently no visuals. They might possibly help, but I think a usage example is probably sufficient. 

### Submit a pull request?

I'm not sure if I'll submit a PR to improve this. I'd like to, but I'm still quite new to TF and wouldn't like to introduce any inaccuracies.

**Comment by amahendrakar** [comment]
@karwa,
The documentation for both [from_tensor_slices](https://www.tensorflow.org/api_docs/python/tf/data/Dataset#from_tensor_slices) and [from_tensors](https://www.tensorflow.org/api_docs/python/tf/data/Dataset#from_tensors) has been updated with a brief description and an example.

Could you please take a look at the given link. Thanks!

**Comment by amahendrakar** [comment]
> Could you please take a look at the given link. Thanks!

@karwa,
Is this still an issue? Please feel free to close the issue if resolved. Thanks!

**Comment by amahendrakar** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
