### ISSUE TITLE
tensorflow c++ header missing ubuntu

### ISSUE THREAD

**Issue by teriterance** [tensorflow/tensorflow#31444]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): linux Ubuntu 18.04
- TensorFlow installed from (source or binary): source
- TensorFlow version: 
- Python version:3.6
- Installed using virtualenv? pip? conda?:PIP
- Bazel version (if compiling from source):0.26.

**Describe the problem**
I am using tensor flow for c++ project, but i get some problem with install, No such file or directory #include "tensorflow/core/lib/framework/graph.pb.h".
**Provide the exact sequence of commands / steps that you executed before running into the problem**
 g++ some_file.cpp   -ltensorflow -o hello_tf

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.
fatal error: tensorflow/core/lib/framework/graph.pb.h: No such file or directory #include "tensorflow/core/lib/framework/graph.pb.h"

**Comment by mihaimaruseac** [comment]
In the `g++` line there is no `-I<include_path>` to point to the include directory. If the header file is not in system paths then it won't be found.
