### ISSUE TITLE
bazel fully recompiles the codebase even though no files were changed

### ISSUE THREAD

**Issue by drsealks** [tensorflow/tensorflow#31445]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
Ubuntu 16.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
n/a
- TensorFlow installed from (source or binary):
source
- TensorFlow version:
1.14
- Python version:
3.5
- Installed using virtualenv? pip? conda?:
virtualenv
- Bazel version (if compiling from source):
Build label: 0.26.1
- GCC/Compiler version (if compiling from source):
gcc version 5.4.0 20160609
- CUDA/cuDNN version:
n/a
- GPU model and memory:
n/a

**Describe the problem**
The problem is that bazel rebuilds the whole codebase during the sequential bazel runs even though literally no files changed. I am building two targets:
`bazel run //tensorflow/lite/python:tflite_convert`
and
`bazel build //tensorflow/tools/pip_package:build_pip_package --host_force_python=PY3 PYTHON_BIN_PATH=/home/kk/tmp/tfclean/bin/python`

The thing is that if say I take the first command and run it 3 times, then the full compilation will only be performed for the first time, two remaining runs will result in no compilation steps. The same for the second command. 

However, if I run the first, then the second command, the first again - the full recompilation will happen again, even though no files were changed. 

Why is it so? No files were changed, while does bazel recompile the whole tensorflow codebase for the second time? 

**Provide the exact sequence of commands/steps that you executed before running into the problem**

These three commands will results in the full tensorflow codebase recompilation, even though no source files were changed. 

`bazel build //tensorflow/tools/pip_package:build_pip_package --host_force_python=PY3 PYTHON_BIN_PATH=/home/kk/tmp/tfclean/bin/python`
`bazel run //tensorflow/lite/python:tflite_convert`
`bazel build //tensorflow/tools/pip_package:build_pip_package --host_force_python=PY3 PYTHON_BIN_PATH=/home/kk/tmp/tfclean/bin/python`

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by mihaimaruseac** [comment]
The compile flags are changing in between the two compilations so Bazel cache is invalidated.

This is the expected behavior as changing those flags can result in files being compiled with different compiler, different compiler options, different ABI, etc.

From the point of view of Tensorflow, this is working as intended. Please open an issue on Bazel repo if you want to request a feature where some flags don't invalidate the cache, as that is not a TensorFlow issue.
