### ISSUE TITLE
python for loops in eager model yield expected results for  keras model.predict but not for saved model with multiple outputs

### ISSUE THREAD

**Issue by mckeown12** [tensorflow/tensorflow#31455]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): YES
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 16.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): NA
- TensorFlow version (use command below): 1.14.0
- Python version: 3.6.8
- Bazel version (if compiling from source): na
- GCC/Compiler version (if compiling from source): na
- CUDA/cuDNN version: na
- GPU model and memory: na

**Describe the current behavior**
tf.keras Model's predict method prediction differs from tf.saved_model's prediction
**Describe the expected behavior**
`tf.saved_model.save()` should either fail to serialize, or should yield correct predictions on reload.

**Code to reproduce the issue**
```python
import tensorflow as tf
tf.enable_eager_execution()
print(tf.__version__)
from tensorflow.keras.layers import Input, Dense, Lambda
from tensorflow.keras.models import Model
import numpy as np

in0 = Input(shape=(1,), dtype="float32", name='my_input_0')
in1 = Input(shape=(1,), dtype="float32", name='my_input_1')
concatted = Lambda(lambda inputs: tf.concat(inputs, axis=-1))([in0,in1])

outputs = Dense(3)(concatted)

#------------- way 1 (does not work)-----------------

# outs = [Lambda(lambda outputs: outputs[...,i], name=f'output_{i}')(outputs) for i in range(3)]

#------------- way 2 (does not work)-----------------

outs = []
for i in range(3):
  outs.append(Lambda(lambda outputs: outputs[...,i], name=f'output_{i}')(outputs))

#------------- way 3 (does work)-----------------

# out0 = Lambda(lambda outputs: outputs[...,0], name='my_output_0')(post_process)
# out1 = Lambda(lambda outputs: outputs[...,1], name='my_output_1')(post_process)
# out2 = Lambda(lambda outputs: outputs[...,2], name='my_output_2')(post_process)
# outs=[out0, out1, out2]

#----------------------------

my_model = Model(inputs=[in0,in1], outputs=outs)
tf.keras.backend.learning_phase = 0

my_model.predict([np.array([[.5],[.3]]), np.array([[-.1],[.2]])])
```

yields
```
1.14.0
[array([0.13002533, 0.03461001], dtype=float32),
 array([-0.45988005, -0.3892737 ], dtype=float32),
 array([-0.28218567, -0.14224575], dtype=float32)]
```
On the other hand,
```python
tf.saved_model.save(my_model, './mymodel')
reloaded = tf.saved_model.load_v2('./mymodel')
sig = reloaded.signatures['serving_default']
sig(my_input_0=tf.constant(np.array([[.5],[.3]]), dtype=tf.float32), my_input_1=tf.constant(np.array([[-.1],[.2]]), dtype=tf.float32))
```
yields
```
{'output_0': <tf.Tensor: id=316, shape=(2,), dtype=float32, numpy=array([-0.28218567, -0.14224575], dtype=float32)>,
 'output_1': <tf.Tensor: id=317, shape=(2,), dtype=float32, numpy=array([-0.28218567, -0.14224575], dtype=float32)>,
 'output_2': <tf.Tensor: id=318, shape=(2,), dtype=float32, numpy=array([-0.28218567, -0.14224575], dtype=float32)>}
```
try it for yourself here:
https://colab.research.google.com/drive/1x1eDTl-nMuhZTQYWSi_I9F_SguFZRP2i

Provide a reproducible test case that is the bare minimum necessary to generate the problem.

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by allenlavoie** [comment]
Can you try on a nightly? I think there was a similar issue fixed not too long ago with named multi-output models.

**Comment by mckeown12** [comment]
It appears to still be broken in 1.15.0-dev20190815

https://colab.research.google.com/drive/1x1eDTl-nMuhZTQYWSi_I9F_SguFZRP2i

**Comment by allenlavoie** [comment]
I see, the difference is just that saving using `Model.__call__`, which has the behavior you describe. So it's not a saving-specific issue; you can reproduce the behavior using `print(my_model([np.array([[.5],[.3]]), np.array([[-.1],[.2]])]))` before saving. Why that's different than predict() I don't know; I'll reassign to someone who works on Keras.

**Comment by allenlavoie** [comment]
Tom, please see last comment. Could you take a look or redirect?

**Comment by Saduf2019** [comment]
@mckeown12 
Is this still an issue

**Comment by mckeown12** [comment]
Yes, it is still an issue. (Sorry for the delayed response.)

https://colab.research.google.com/drive/1x1eDTl-nMuhZTQYWSi_I9F_SguFZRP2i

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.
