### ISSUE TITLE
eigen-eigen issue

### ISSUE THREAD

**Issue by danieleghisi** [tensorflow/tensorflow#3146]
Hi,

I am trying to compile an example with C++ api, and I'm running into this issue:

```
In file included from /Users/danieleghisi/max-sdk-7.0.3/source/fool/mains/dg/fool.rnn.c:53:
In file included from /Users/danieleghisi/LibrariesAndStuff/tensorflow/tensorflow/cc/ops/standard_ops.h:22:
In file included from /Users/danieleghisi/LibrariesAndStuff/tensorflow/tensorflow/cc/ops/array_ops.h:6:
In file included from /Users/danieleghisi/LibrariesAndStuff/tensorflow/tensorflow/core/framework/tensor.h:21:
In file included from /Users/danieleghisi/LibrariesAndStuff/tensorflow/tensorflow/core/framework/allocator.h:25:
In file included from /Users/danieleghisi/LibrariesAndStuff/tensorflow/tensorflow/core/framework/type_traits.h:22:
In file included from /Users/danieleghisi/LibrariesAndStuff/tensorflow/tensorflow/core/framework/types.h:23:
/Users/danieleghisi/LibrariesAndStuff/tensorflow/third_party/eigen3/unsupported/Eigen/CXX11/Tensor:1:10: fatal error: 'eigen-eigen-334b1d428283/unsupported/Eigen/CXX11/Tensor' file not found
```

I do not seem to have an "eigen-eigen-334b1d428283" folder anywhere. 
There's an eigen.BUILD file at the root level, but I am unable to bazel it with 
`bazel build eigen`
nor
`bazel build tensorflow/eigen`
(but it should be the first one, isn't it? eigen.BUILD being at the root level... Or how does bazel work in this respect?)

Should I build that file via bazel? I guess I should. (but how do I build in general a xxxx.BUILD file, given that bazel build xxxx doesn't work?)

Thanks a lot,
daniele

### Environment info
Operating System: Mac OS X 10.10
Installed version of CUDA: 7.5

**Comment by rmlarsen** [comment]
@danieleghisi Indeed, eigen-eigen-334b1d428283 is not a file, but refers to a commit timestamp in the Eigen repository.  bazel (magically) pulls a copy of Eigen when building tensorflow. The copy of Eigen ends up in bazel-tensorflow/external/eigen_archive/eigen-eigen-334b1d428283/.

However, if you are trying the to use the C++ TF API, I recommend that you start by cloning the code and build rules in tensorflow/cc.
