### ISSUE TITLE
TFLite Metal GPU delegate: crash in Mul operation

### ISSUE THREAD

**Issue by LK** [tensorflow/tensorflow#31468]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes.
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): iOS 12.3.1
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: iPhone Xr
- TensorFlow installed from (source or binary): binary, but TFLite compiled from source
- TensorFlow version (use command below): b'v1.13.2-5-g04256c89d8' 1.13.2
- Python version: 3.6.8
- Bazel version (if compiling from source): 0.26.1
- GCC/Compiler version (if compiling from source): clang-1001.0.46.4
- CUDA/cuDNN version: n/a
- GPU model and memory: iPhone Xr

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
Running the single-operation model given below using the Metal GPU delegate causes the following error:
> Execution of the command buffer was aborted due to an error during execution. Caused GPU Hang Error (IOAF code 3)

**Describe the expected behavior**
Running the model completes successfully.

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.
[model-broken.tflite.zip](https://github.com/tensorflow/tensorflow/files/3484839/model-broken.tflite.zip)

This basic model fails to run on GPU (with the error specified above), but will run fine on CPU.

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

TFLite interpreter is being run using provided sample code and the crash only occurs on GPU — the model runs correctly on CPU.

**Comment by LK** [comment]
As an update on this, it seems like this only happens if the input is large enough — for smaller inputs it works fine. For example, an 11x11x32 multiplied by a 32-wide vector works, but 12x12x32 doesn't.

**Comment by LK** [comment]
This issue reproduces on `master` (dac283f2d716b181bfe122196c91da5a8bd00159), but does not reproduce on the published `TensorFlowGpuExperimental` pod (which was last released in January)

**Comment by impjdi** [comment]
@LK

Sorry, but @NikolayChirkov switched teams and is no more working on this. We currently don't have an owner. This may take some time until we get a backfill =/

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.
