### ISSUE TITLE
tflite unsupported ops:  Log1p, SparseReorder, SegmentSum

### ISSUE THREAD

**Issue by Shine-ZhangGuomin** [tensorflow/tensorflow#31474]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- TensorFlow installed from (source or binary):
- TensorFlow version (or github SHA if from source):

**Provide the text output from tflite_convert**

```
# Copy and paste here
tflite unsupported ops:  Log1p, SparseReorder, SegmentSum
Some of the operators in the model are not supported by the standard TensorFlow Lite runtime and are not recognized by TensorFlow. If you have a custom implementation for them you can disable this error with --allow_custom_ops, or by setting allow_custom_ops=True when calling tf.lite.TFLiteConverter(). Here is a list of builtin operators you are using: ADD, CAST, CONCATENATION, EXPAND_DIMS, FILL, FULLY_CONNECTED, GATHER, LESS, LOGISTIC, MUL, RESHAPE, SELECT, SHAPE, SOFTMAX, STRIDED_SLICE, SUM, TILE, UNIQUE, ZEROS_LIKE. Here is a list of operators for which you will need custom implementations: Log1p, SparseReorder.
```

Also, please include a link to a GraphDef or the model if possible.

**Any other info / logs**

Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by ymodak** [comment]
Apologies that it doesn't work out for you. We are continuously adding new ops into tflite, in the mean time;
You can use ```TFLITE_BUILTINS``` to convert your model it will help to reduce custom implementations.
See https://www.tensorflow.org/lite/guide/ops_select
You will have to custom implement ```Log1p, SparseReorde``` ops.
See https://www.tensorflow.org/lite/guide/ops_custom
