### ISSUE TITLE
[C++] The first SessionOptions controls the "inter intra number" of all following Sessions?

### ISSUE THREAD

**Issue by JiayiFu** [tensorflow/tensorflow#31478]
**Describe the current behavior**
    I trained a model. It runs near 25 milliseconds each inference when the `inter_op_parallelism_threads=1` and `intra_op_parallelism_threads=8` and near 90 milliseconds each inference when the `inter_op_parallelism_threads=1` and `intra_op_parallelism_threads=1`.
  I found that the first `SessionOptions` will determine all the following Sessions' Options.
  For example, I created a Session with `inter=1, intra=1` and close it. Then I create another Session with `inter=1, intra=8` and run my model in the later Session. The inference speed of the model is 90ms which corresponding to `inter=1, intra=1` but not `inter=1, intra=8`. It seems the first SessionOptions still control the later Session.
 
**Code to reproduce the issue**
    
    void DoSessionAction(boost::filesystem::path model_path, unsigned inter, unsigned intra){
      std::unique_ptr<tensorflow::Session> sess_;
      tensorflow::SessionOptions sess_options_;
      sess_options_.config.set_use_per_session_threads(false);
      sess_options_.config.set_inter_op_parallelism_threads(inter);
      sess_options_.config.set_intra_op_parallelism_threads(intra);
      sess_.reset(tensorflow::NewSession(sess_options_));
      tensorflow::GraphDef graph_def;
      auto default_env = tensorflow::Env::Default();
      tensorflow::ReadBinaryProto(default_env, model_path.string(), &graph_def);
      sess_->Create(graph_def);
      sess_->Close();
    }

    // This situation the inference time is 90ms.
    int main(int argc, char **argv) {
        DoSessionAction(model_path, 1, 1);
        DoSessionAction(model_path, 1, 8);
        RunModel(); 
    }

    // This situation the inference time is 25ms.
    int main(int argc, char **argv) {
        DoSessionAction(model_path, 1, 8);
        RunModel(); 
    }
**System information**
- OS Platform and Distribution: Linux Ubuntu 16.04
- TensorFlow installed from source
- TensorFlow version: 1.14.1
- Python version: 3.5.2
- Bazel version: 0.24
- GCC/Compiler version: 5.4.0

Is there anything wrong with my usage of Session or SessionOptions?
Thanks!

**Comment by JiayiFu** [comment]
Is there any other information need me to add? I would like to share other needed codes.

**Comment by JiayiFu** [comment]
I found another problem: when I set inter=1 and intra=1, the CPU usage is still higher than 100%. Is this reasonable?

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.
