### ISSUE TITLE
Use CFFI for interfacing C functions.

### ISSUE THREAD

**Issue by robert-zaremba** [tensorflow/tensorflow#315]
[CFFI](https://cffi.readthedocs.org/en/latest/)  is a big step towards standard practices for making and distributing Python packages with C extension modules.

With CFFI the maintenance is much easier, and the code is still fast.
There are lot of benefits:
- Abstract the Python version (CPython2, CPython3, PyPy).
- Better control over when and why the C compilation occurs, and more standard ways to write distutils- or setuptools-based setup.py files.
- Keep all the Python-related logic in Python so that you don’t need to write much C code.

I'm really looking forward to use [PyPy](http://pypy.org/) with tensorflow.

**Comment by bhack** [comment]
:+1:

**Comment by bhack** [comment]
What about [pybind11](https://github.com/wjakob/pybind11)?

**Comment by michaelisard** [comment]
@sherrym is anyone in the core team thinking about this?

**Comment by aselle** [comment]
Thank you for the suggestion, but it's likely we won't do this, and it is would be undesirable to maintain two sets of Python bindings, closing for now. It also seems PyPy also now has the normal extension API available, relieving that need for this.

**Comment by robert-zaremba** [comment]
OK, I understand your motivation.
Just to clarify PyPy C-Python API  support. That's true that the compatibility is pretty high, but it comes with limitations: speed and GC (it's slow, not jitted and it goes through simulation layers).
