### ISSUE TITLE
Update TensorFlow For Poets

### ISSUE THREAD

**Issue by brettwooldridge** [tensorflow/tensorflow#31507]
It would be awesome if someone could update TensorFlow For Poets, with the latest stable TensorFlow and Inception v4.

Currently, there are lots of deprecation warnings logged when TensorFlow For Poets is run on TensorFlow 1.7.

In addition, I am unable to get TensorFlow For Poets to run using Inception v4.  The code currently downloads ``inception-2015-12-05.tgz``, which contains the training file ``classify_image_graph_def.pb``.  But when I tried to substitute ``inception_v4_2016_09_09.tar.gz``, I found that it contained a ``inception_v4.ckpt`` file instead.  I understand that ``.ckpt`` implies a checkpoint file, but I do not know how to convert a ``.ckpt`` file to the ``.pb`` file that TensorFlow For Poets is trying to load.

I am sure all of this is documented somewhere, e.g. how to swap out the code to initialize from a .ckpt instead, but given that the example is supposed to be an introduction, doing so is a bit above my head at present.  Likely so for other newcomers.

Thanks for the awesome work.  I have gotten TforP running with the old inception model and my own image classifications, but my results, while good, I think could be improved somewhat by the newer Inception v4 pre-trained model.

**Comment by ymodak** [comment]
Highly recommend trying [TensorFlow For Poets TF 2.0 version](https://colab.sandbox.google.com/github/tensorflow/examples/blob/master/community/en/flowers_tf_lite.ipynb) if haven't already.

**Comment by dynamicwebpaige** [comment]
Closing out this feature request, as TF for Poets has been updated to support TensorFlow 2.0 (see link above). Thank you for the suggestion, and thanks to the TF Lite team for creating! 😄
