### ISSUE TITLE
NotImplementedError: tf.GradientTape.gradients() does not support graph control flow operations like tf.cond or tf.while at this time. Use tf.gradients() instead. If you need this feature, please file a feature request at https://github.com/tensorflow/tensorflow/issues/new

### ISSUE THREAD

**Issue by Bakibiiiillah** [tensorflow/tensorflow#31504]
loss_object = tf.keras.losses.CategoricalCrossentropy()

def create_adversarial_pattern(input_image, input_label):
  with tf.GradientTape() as tape:
    tape.watch(input_image)
    prediction = model(input_image)
    print(prediction.shape)
    loss = loss_object(input_label, prediction)
    print('Loss:',loss)

  # Get the gradients of the loss w.r.t to the input image.
  
  gradient = tape.gradient(loss, input_image)
  print('................')
  print('Gradient tensor:',gradient)
  # Get the sign of the gradients to create the perturbation
  signed_grad = tf.sign(gradient)

  return signed_grad

perturbations = create_adversarial_pattern(new_img, y_pred1)
print(perturbations)

Hello, can anyone help me to solve the error???  Why am I not getting a tensor shape of gradient
(1,299,299,3). I followed https://www.tensorflow.org/beta/tutorials/generative/adversarial_fgsm
lnk to do my code. TIA

**Comment by oanush** [comment]
@Bakibiiiillah ,
Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version.
In order to expedite the trouble-shooting process, please provide complete code snippet to reproduce the issue reported here. Thanks!

**Comment by Bakibiiiillah** [comment]
Thanks a lot @oanush for your gentle reply, actually I am working on kaggle, the version of tensorflow I haven't checked yet, actually  I have to generate adversarial sample using fast gradient sign method for diabetic retinopathy dataset, but I got some error related with tensorflow. It's raelly very important for me too solve as it is my undergraduate thesis topic. The version of tensorflow is 1.14.0
[diabetic-retinopathy.zip](https://github.com/tensorflow/tensorflow/files/3497142/diabetic-retinopathy.zip)
Actually last three or four cells of above code snippet contains the problem related with creating adversarial sample for my diabetic retinopathy dataset using fast gradient sign method(for tensorflow).
Again many many thanks for your gentle reply , it's really very important to solve the issues, 
so I'll eagerly wait for your reply@oanush

**Comment by Bakibiiiillah** [comment]
@oanush , further for any question you can ask me any time, it's really important to solve.
TIA

**Comment by Bakibiiiillah** [comment]
@oanush 
This screenshot provides name of my kaggle dataset
![dr](https://user-images.githubusercontent.com/50144400/62947534-827eb780-be04-11e9-873c-d22742f4ed2d.PNG)

**Comment by sarsbug** [comment]
I have the same problem...anyone can help?

**Comment by Bakibiiiillah** [comment]
*typeerror:image data cannot be converted to float.*
*how to solve this problem in kaggle to show a tensor image*

**Comment by ymodak** [comment]
@Bakibiiiillah Without code snippet we can do very little to help you solve your problem.
From the error message following post may help you resolve it;
https://stackoverflow.com/questions/32302180/typeerror-image-data-can-not-convert-to-float

**Comment by maithal** [comment]
Did you get the problem resolved?

**Comment by Bakibiiiillah** [comment]
I didn't get the problem resolve but I don't need to solve it now. You may
close the conversation. Thank
