### ISSUE TITLE
Tensorflow 2.0 does not use GPU

### ISSUE THREAD

**Issue by andrey999333** [tensorflow/tensorflow#31505]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04
- TensorFlow installed from (source or binary): yes
- TensorFlow version (use command below): 2.0.0-beta1
- Python version: 3.7
- CUDA/cuDNN version: 10.1
- GPU model and memory: Nvidia MX250 4Gb

**Describe the current behavior**
I'm playing around with tf2.0 while mostly still working on tf1.14. I have created two conda environments - one for tf1.14 and the other one for tf2.0 - so all hardware and drivers are absolutely the same. Tf1.14 is working good and uses gpu as it supposed to, but tf2.0 runs on cpu.

**Code to reproduce the issue**
if i run:
```python
from tensorflow.python.client import device_lib
device_lib.list_local_devices()

i get an output with tf2.0:

[name: "/device:CPU:0"
 device_type: "CPU"
 memory_limit: 268435456
 locality {
 }
 incarnation: 9820328803404595310, name: "/device:XLA_CPU:0"
 device_type: "XLA_CPU"
 memory_limit: 17179869184
 locality {
 }
 incarnation: 7262628900557013132
 physical_device_desc: "device: XLA_CPU device", name: "/device:XLA_GPU:0"
 device_type: "XLA_GPU"
 memory_limit: 17179869184
 locality {
 }
 incarnation: 4554198733675012648
 physical_device_desc: "device: XLA_GPU device"]

and 

import tensorflow as tf
tf.test.is_gpu_available()
 
gives False. 
Same code in tf1.14 gives the following:

[name: "/device:CPU:0"
 device_type: "CPU"
 memory_limit: 268435456
 locality {
 }
 incarnation: 11125515865111208996, name: "/device:XLA_CPU:0"
 device_type: "XLA_CPU"
 memory_limit: 17179869184
 locality {
 }
 incarnation: 7071753861411904965
 physical_device_desc: "device: XLA_CPU device", name: "/device:GPU:0"
 device_type: "GPU"
 memory_limit: 3333029888
 locality {
   bus_id: 1
   links {
   }
 }
 incarnation: 17329402577157719353
 physical_device_desc: "device: 0, name: GeForce MX250, pci bus id: 0000:02:00.0, compute capability: 6.1", name: "/device:XLA_GPU:0"
 device_type: "XLA_GPU"
 memory_limit: 17179869184
 locality {
 }
 incarnation: 17993919851972383985
 physical_device_desc: "device: XLA_GPU device"]

And:

import tensorflow as tf
tf.test.is_gpu_available()

Gives True
```

**Comment by kielnino** [comment]
Are you sure your GPU matches the required CUDA® Compute Capability 3.5 or higher? I couldn't find it in the list on the [website of nvidia](https://developer.nvidia.com/cuda-gpus).

**Comment by andrey999333** [comment]
i could't find my gpu there as well. But apparently it's supported since it's working with tensorflow 1.14 - i can successfully train models and it works much faster then on cpu and i can see the gpu load. And also nvidia-smi shows cuda version:

+-----------------------------------------------------------------------------+
| NVIDIA-SMI 430.40       Driver Version: 430.40       CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce MX250       Off  | 00000000:02:00.0 Off |                  N/A |
| N/A   43C    P8    N/A /  N/A |      4MiB /  4042MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+

**Comment by ymodak** [comment]
Did you install TF 1.14, 2.0 from source or binary?
Also did you install TF-GPU version for both versions of TF?
Can you please check with ```tf.test.is_built_with_cuda``` for both TF versions?

**Comment by andrey999333** [comment]
1) I install tensorflow 2.0 using pip (since conda install is not available for this version) and tensorflow 1.14 using conda.
2) Yes, both gpu versions
3) Just did  - both return True

**Comment by ymodak** [comment]
Thanks. I suspect, you haven't added cuda path to the TF 2.0 environment. You need to manually add this after doing ```pip install```.

**Comment by andrey999333** [comment]
can you elaborate a bit more on how to do it? I've tried to google it and couldn't find any info on how to add cuda path to tensorflow

**Comment by ymodak** [comment]
Sure. Take a look at https://www.tensorflow.org/install/gpu#linux_setup

**Comment by georgesterpu** [comment]
Could this happen because @andrey999333 uses cuda 10.1, while the pip wheel was built for cuda 10.0 ?
@ymodak do you know why TensorFlow 2.0 on pypi is not yet built for cuda 10.1, library released in February ?
