### ISSUE TITLE
 module 'tensorflow._api.v2.train' has no attribute 'AdamOptimizer'

### ISSUE THREAD

**Issue by heqi8826** [tensorflow/tensorflow#31502]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version (use command below):
- Python version:
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**

**Describe the expected behavior**

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by ymodak** [comment]
Please provide all the information asked by the template. It will help us assist you better.
From the error message looks like you are trying to use adam optimizer in TF 2.0. In that case,
You may try  [```tf.optimizers.Adam()```](https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/keras/optimizers)

**Comment by mikechen66** [comment]
If I change Adam = tf.train.AdamOptimizer to  Adam = tf.optimizers.Adam(), there is the following error. 

generating GAN...

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-7-0decb4cd863c> in <module>
     66 
     67 print('generating GAN...')
---> 68 gan_feed = gan(generator, discriminator)

<ipython-input-7-0decb4cd863c> in gan(g, d)
     23 
     24     lr, b1 = 1e-4, .2 # otherwise won't converge.
---> 25     optimizer = Adam(lr,beta1=b1)
     26 
     27     grad_loss_wd = optimizer.compute_gradients(dloss, d.trainable_weights)

TypeError: 'Adam' object is not callable
