### ISSUE TITLE
TF 1.14 on AI Platform: MirroredStrategy fails on 2 GPUs with RuntimeError

### ISSUE THREAD

**Issue by sdll** [tensorflow/tensorflow#31510]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): AI Platform 1.14
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: n/a
- TensorFlow installed from (source or binary): pip
- TensorFlow version (use command below): 1.14 
- Python version: 3.5
- Bazel version (if compiling from source): n/a
- GCC/Compiler version (if compiling from source): n/a
- CUDA/cuDNN version: AI Platform
- GPU model and memory: V100 16GB

**Describe the current behavior**

I have written a custom estimator and wanted to train it on 2 GPUs using `tf.distribute.MirroredStrategy`, submitting [this job](https://github.com/sdll/psenet/blob/cc3041da4565da03f5ebe206962ee424c1f36bbb/train.sh#L4) to the AI Platform. Unfortunately, after ~900 steps, the training fails with `RuntimeError: Variable creator scope nesting error: move call to tf.distribute.set_strategy() out of `with` scope.`

**Describe the expected behavior**

The model should train on two GPUs asynchronously.

**Code to reproduce the issue**

The estimator definition starts [here](https://github.com/sdll/psenet/blob/cc3041da4565da03f5ebe206962ee424c1f36bbb/psenet/train.py#L193).

**Other info / logs**

- [the entire AI platform log](https://github.com/tensorflow/tensorflow/files/3489041/log_rc47.txt)
- another curious detail is that the estimator seems to be executed only on a single GPU.

Turning on the placement logging with a similar set-up confirmed that training just used the first GPU before failing.

Here is the usage graph, where you can see a short spike before the failure:

<img width="975" alt="Screen Shot 2019-08-10 at 6 42 35 PM" src="https://user-images.githubusercontent.com/17913919/62823852-b0fb5900-bb9e-11e9-8cd2-d4eacd73cfeb.png">

**Comment by pwais** [comment]
You can use `MirroredStrategy` with one GPU; perhaps try that to suss out other errors?

You haven't by chance tried this on a local or AWS instance, have you?  I have recently seen Google Cloud instances give me multiple GPUs but one or more of them showed 100% utilization in `nvidia-smi` even though I had no processes running in my VM at the time.  It's possible that bugs in Google Cloud are confounding the problem.

**Comment by sdll** [comment]
@pwais, thanks for your reply! I have switched to using 4 K80 Teslas instead of 2 V100 GPUs and also disabled evaluation by replacing `train_and_evaluate` with `train`, and the training started working fine. One difference between training and evaluation is that during evaluation I skip cropping the image for data augmentation, which results in a larger input. Wonder whether this is a latent OOM error.

**Comment by isaprykin** [comment]
I think that variable scope error isn't the root cause, rather this is:
```
InternalError: File contents are inconsistent for file: gs://gsoc-tfjs/weights/psenet/custom/psenet_rc47/checkpoint @ 0.
gs://gsoc-tfjs/weights/psenet/custom/psenet_rc47/checkpoint: Checkpoint ignored
Estimator is not trained yet. Will start an evaluation when a checkpoint is ready.
```

Is this failure deterministic?   Does it happen every time you run it with 2 GPUs?

**Comment by sdll** [comment]
@isaprykin, yes, this happens intermittently during the evaluation phase. I have managed to revert to `train_and_evaluate` for a multi-worker multi-gpu setup and avoid this problem by setting a humongous `eval-throttle-secs`.

**Comment by isaprykin** [comment]
Does it happen every time during the evaluation phase when using `train_and_evaluate`?

**Comment by sdll** [comment]
It failed two times in a row at about the time evaluation must have started, after which I have switched to training without evaluation, so I assume it is reproducible.

**Comment by sshrdp** [comment]
Is it possible that multiple jobs are using the same directory for their checkpoint in parallel?

**Comment by sdll** [comment]
I make sure that each job creates its own folder with weights in the bucket. 

Wonder whether setting MirroredStrategy is a bad idea as eval_strategy, or maybe keep_checkpoint_every_n_hours does not play well with save_checkpoint_secs.

**Comment by sshrdp** [comment]
Do you mind running the code with some extra logging turned on?

os.environ["TF_CPP_VMODULE"] = "gcs_file_system=2"
You might need to remove this line too:
os.environ["TF_CPP_MIN_LOG_LEVEL"] = "3"

**Comment by sdll** [comment]
I tried running the code again, reducing the time until the first evaluation, and the job failed with a simple OOM. Closing the issue, since it is not reproducible.
