### ISSUE TITLE
tensorflow 2.0 tensorflow.python.eager.function.TfMethodTarget object at could not be transformed and will be executed as-is.

### ISSUE THREAD

**Issue by zwenju** [tensorflow/tensorflow#31516]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

WARNING: Entity <bound method TensorFlowOpLayer._defun_call of <tensorflow.python.eager.function.TfMethodTarget object at 0x000001D5FA485A58>> could not be transformed and will be executed as-is. 
Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method TensorFlowOpLayer._defun_call of <tensorflow.python.eager.function.TfMethodTarget object at 0x000001D5FA485A58>>: AssertionError: W0811 12:49:24.207197  2284 ag_logging.py:145] Entity <bound method TensorFlowOpLayer._defun_call of <tensorflow.python.eager.function.TfMethodTarget object at 0x000001D5FA4A82B0>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method TensorFlowOpLayer._defun_call of <tensorflow.python.eager.function.TfMethodTarget object at 0x000001D5FA4A82B0>>: AssertionError:

**System information**
Windows 10 , Anaconda, Python 3.7  Tensorflow 2.0b1

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**

**Describe the expected behavior**

**Code to reproduce the issue**

```
import time
import math
import tensorflow as tf
import numpy as np
import tensorflow as keras
from tensorflow.keras import layers
from tensorflow import keras
from tensorflow.keras.utils import plot_model
from scipy . stats import multivariate_normal as normal

d = 10
T = 0.1
n_time = 5
n_sample = 100
batch_size = 100
n_maxstep = 400
h = (T + 0.0) / n_time
t_stamp = np.arange (0, n_time) * h

def f_tf (t, X, Y, Z):
    V =  Y - tf.math.sin (Y)
    return V

def g_tf (t, X):
    V =  tf.math.reduce_sum (X**3, 1,keepdims=True)
    return V

def k_tf ( n_sample ):
    W = np.zeros ([ n_sample, d, n_time  ], dtype = np.float64)
    X_sample  = np.zeros ([ n_sample, d, n_time+1], dtype = np.float64)
    for i in range (n_time):
        W [:, :, i  ] = np.reshape ( normal.rvs ( mean = np.zeros(d,dtype = np.float64),\
                                      cov =1, size = n_sample ), ( n_sample, d))
        X_sample  [:, :, i+1] =  W [:, :, i]
    return W, X_sample

def nn_tf(x):
    x = keras.layers.BatchNormalization(batch_size = n_sample)(x)
    x = keras.layers.Dense(d, batch_size = n_sample)(x)
    x = keras.layers.BatchNormalization(batch_size = n_sample)(x)
    return x

dW = keras.Input(shape = (d, n_time  ), batch_size=n_sample, dtype = tf.float64, name = 'dW')
XX = keras.Input(shape = (d, n_time+1), batch_size=n_sample, dtype = tf.float64, name = 'X' )
X = XX
Y = tf.zeros([n_sample, 1], dtype = tf.float64)
Z = tf.zeros([n_sample, d], dtype = tf.float64)

for it in range(n_time-1):
    with tf.name_scope(str(it+1)):
        Y = Y +  tf.math.reduce_sum( Z * dW[:,:,it],  1, keepdims=True)
        subX = tf.reshape(X[:,:,it], shape = [n_sample, d])
        Z = nn_tf(subX) / d

Y = Y + tf.math.reduce_sum (Z * dW [:, :, n_time-1], 1, keepdims=True)
model = keras.Model(inputs=[XX,dW], outputs=[Y])

optimizer = keras.optimizers.Adam(learning_rate=1e-3)
train_accuracy = tf.keras.metrics.SparseCategoricalAccuracy(name='train_accuracy')
dW_train, X_train = k_tf ( n_sample )

for epoch in range (10):
    with tf.GradientTape() as tape:
        predictions = model( [X_train, dW_train] )
        label = g_tf (T, X_train[:, :, n_time])
        loss_value = tf.reduce_sum( tf.keras.losses.MSE (label, predictions ) )
    grads = tape.gradient(loss_value,  model.trainable_variables)
    optimizer.apply_gradients( zip(grads, model.trainable_variables) )
    accuracy = train_accuracy(label, predictions)
    print("step ", epoch, "loss = ", loss_value.numpy(), "accuracy = ", accuracy.numpy())

```
**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by oanush** [comment]
@zwenju ,
I was unable execute the give code, can you please provide the code with proper indentation?Thanks

**Comment by zwenju** [comment]
Thank you,  the new code is provided

**Comment by oanush** [comment]
@zwenju ,
Thank you for the updated code,when tried executing the same I got the output as per the screenshot
![output](https://user-images.githubusercontent.com/52397990/63011334-bcec6100-bea5-11e9-967e-2f2f8ef832dd.png)

**Comment by zwenju** [comment]
Please run this code twice continuously,   I find the first run no errors,    the second run will show the errors.

**Comment by zwenju** [comment]
![QQ截图20190814194837](https://user-images.githubusercontent.com/27112868/63018929-9b52a000-becc-11e9-8a31-b6964fc3beea.png)

**Comment by zwenju** [comment]
![QQ](https://user-images.githubusercontent.com/27112868/63019179-2cc21200-becd-11e9-9273-9757bb91b459.png)

**Comment by oanush** [comment]
I tried executing the given code in both colab and Jupyter notebook,couldn't replicate the issue.

**Comment by zwenju** [comment]
Thank you，may be it a bug of Spyder?  
I am not sure why I got this error.
thanks again.

**Comment by jvishnuvardhan** [comment]
@zwenju I think there are issues with `dtype` in your code specifically related to `keras.layers.BatchNormalization`. In `keras.layers.BatchNormalization`, if you don't set `dtype`, it will use default dtype which is `tf.float32`. Most of your code user `tf.float64` except in the `keras.layers.BatchNormalization` layer. 

You can remove the errors in two ways
1. use `dtype=tf.float64` in the `keras.layers.BatchNormalization` layer.  
2. If you think you want set default `dtype` as `tf.float64` then add `tf.keras.backend.set_floatx('float64')` at the top of the program as shown in the code below. 

```
import time
import math
import tensorflow as tf
import numpy as np
import tensorflow as keras
from tensorflow.keras import layers
from tensorflow import keras
from tensorflow.keras.utils import plot_model
from scipy . stats import multivariate_normal as normal
# tf.keras.backend.set_floatx('float64') # sets dtype as tf.float64

d = 10
T = 0.1
n_time = 5
n_sample = 100
batch_size = 100
n_maxstep = 400
h = (T + 0.0) / n_time
t_stamp = np.arange (0, n_time) * h

def f_tf (t, X, Y, Z):
    V =  Y - tf.math.sin (Y)
    return V

def g_tf (t, X):
    V =  tf.math.reduce_sum (X**3, 1,keepdims=True)
    return V

def k_tf ( n_sample ):
    W = np.zeros ([ n_sample, d, n_time  ], dtype = np.float64)
    X_sample  = np.zeros ([ n_sample, d, n_time+1], dtype = np.float64)
    for i in range (n_time):
        W [:, :, i  ] = np.reshape ( normal.rvs ( mean = np.zeros(d,dtype = np.float64),\
                                      cov =1, size = n_sample ), ( n_sample, d))
        X_sample  [:, :, i+1] =  W [:, :, i]
    return W, X_sample

def nn_tf(x):
    x = keras.layers.BatchNormalization(batch_size = n_sample,dtype=tf.float64)(x)
    x = keras.layers.Dense(d, batch_size = n_sample)(x)
    x = keras.layers.BatchNormalization(batch_size = n_sample,dtype=tf.float64)(x)
    return x

dW = keras.Input(shape = (d, n_time  ), batch_size=n_sample, dtype = tf.float64, name = 'dW')
XX = keras.Input(shape = (d, n_time+1), batch_size=n_sample, dtype = tf.float64, name = 'X' )
X = XX
Y = tf.zeros([n_sample, 1], dtype = tf.float64)
Z = tf.zeros([n_sample, d], dtype = tf.float64)

for it in range(n_time-1):
    with tf.name_scope(str(it+1)):
        Y = Y +  tf.math.reduce_sum( Z * dW[:,:,it],  1, keepdims=True)
        subX = tf.reshape(X[:,:,it], shape = [n_sample, d])
        Z = nn_tf(subX) / d

Y = Y + tf.math.reduce_sum (Z * dW [:, :, n_time-1], 1, keepdims=True)
model = keras.Model(inputs=[XX,dW], outputs=[Y])

optimizer = keras.optimizers.Adam(learning_rate=1e-3)
train_accuracy = tf.keras.metrics.SparseCategoricalAccuracy(name='train_accuracy')
dW_train, X_train = k_tf ( n_sample )

for epoch in range (10):
    with tf.GradientTape() as tape:
        predictions = model( [X_train, dW_train] )
        label = g_tf (T, X_train[:, :, n_time])
        loss_value = tf.reduce_sum( tf.keras.losses.MSE (label, predictions ) )
    grads = tape.gradient(loss_value,  model.trainable_variables)
    optimizer.apply_gradients( zip(grads, model.trainable_variables) )
    accuracy = train_accuracy(label, predictions)
    print("step ", epoch, "loss = ", loss_value.numpy(), "accuracy = ", accuracy.numpy())
```

I am closing this issue as it was resolved. Feel free to reopen if the issue persists again. [Here](https://colab.sandbox.google.com/gist/jvishnuvardhan/31720e5d1d44dcb9ffeaa84c98301307/tf_31516_batchnormalization.ipynb) is the gist for your reference. Thanks!

**Comment by zwenju** [comment]
Thanks.
