### ISSUE TITLE
How to reduce the memory use of image operations

### ISSUE THREAD

**Issue by yomcoding** [tensorflow/tensorflow#31517]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 1809 x64
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 1.14.0
- Python version: 3.7.3 x64
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: cuda_10.0.130_411.31_win10 & cudnn-10.0-windows10-x64-v7.5.1.10
- GPU model and memory: GTX 1070 Max-Q 6376 MB

**Describe the current behavior**

I want to do some operations like:
1. Split the image into 12*12 squares.
2. For each sub square, split it into 6*(2*12) horizontal & 6*(12*2) vertical rectangles.
3. For each rectangle, calculate it's pixels horizontal & vertical gradient's mean and standard deviation.
So, for each sub square, i want 48 values, which is 
6*(hori_gx_mean,hori_gy_mean,hori_gx_std,hori_gy_std)----24
and
6*(vert_gx_mean,vert_gy_mean,vert_gx_std,vert_gy_std)----24

Now I have a 1920 * 1280 image with 3 chanels.
I read image by 
`tf.Session().run(tf.image.decode_image(tf.read_file(imgDir)))/255.0`

and calculate image by 

`
    for y in range(int(srcImg.shape[0]/12)-1):
        for x in range(int(srcImg.shape[1]/12)-1):
            sub12_12 = tf.image.crop_to_bounding_box(_src, y*12, x*12, 12, 12)
            # computes every 2*12 and 12*2 subSet in sub12_12
            for div in range(6):
                # height=2 width=12
                sub12_2 = tf.image.crop_to_bounding_box(
                    sub12_12, div * 2, 0, 2, 12)
                # height=12 width=2
                sub2_12 = tf.image.crop_to_bounding_box(
                    sub12_12, 0, div* 2, 12, 2)
                    
                # computes gradient, return (dy, dx)
                _dy_12_2, _dx_12_2 = tf.image.image_gradients(
                    tf.image.rgb_to_grayscale(sub12_2))
                _dy_2_12, _dx_2_12 = tf.image.image_gradients(sub2_12)

                # computes standard deviation
                _stDy12_2 = tf.math.reduce_std(_dy_12_2)
                _stDx12_2 = tf.math.reduce_std(_dx_12_2)

                _stDy2_12 = tf.math.reduce_std(_dy_2_12)
                _stDx2_12 = tf.math.reduce_std(_dx_2_12)
                # compute gradient's mean
                _uDy12_2 = tf.math.reduce_mean(_dy_12_2)
                _uDx12_2 = tf.math.reduce_mean(_dx_12_2)

                _uDy2_12 = tf.math.reduce_mean(_dy_2_12)
                _uDx2_12 = tf.math.reduce_mean(_dx_2_12)

                # 6 set of horizontal and vertical sub-rectangle feature
                feaBuf.append([_uDy12_2, _uDx12_2, _stDy12_2, _stDx12_2,
                                _uDy2_12, _uDx2_12, _stDy2_12, _stDx2_12])
            _retExp.append(feaBuf)
            feaBuf=[]
`

and cost about 0.5g of memory per line of image, and it is‘t affordable.

**Describe the expected behavior**

Reduce memory cost to about 500kB per line.

**Comment by jvishnuvardhan** [comment]
This is not Build/Installation or Bug/Performance issue. Please post this kind of support questions at [Stackoverflow](https://stackoverflow.com/questions/tagged/tensorflow). There is a big community to support and learn from your questions. GitHub is mainly for addressing bugs in installation and performance. Thanks!
