### ISSUE TITLE
TFLite Metal GPU delegate: Add operator does not support broadcasting

### ISSUE THREAD

**Issue by LK** [tensorflow/tensorflow#31526]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes.
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): iOS 12.3.1
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: iPhone Xr
- TensorFlow installed from (source or binary): binary, but TFLite compiled from source
- TensorFlow version (use command below): b'v1.13.2-5-g04256c89d8' 1.13.2
- Python version: 3.6.8
- Bazel version (if compiling from source): 0.26.1
- GCC/Compiler version (if compiling from source): clang-1001.0.46.4
- CUDA/cuDNN version: n/a
- GPU model and memory: iPhone Xr

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
Running the single-operation model given below using the Metal GPU delegate gives a different output than when executing on CPU or with the full Tensorflow interpreter.

**Describe the expected behavior**
The Metal GPU delegate gives the same output as the CPU interpreter.

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.
[model-broken.tflite.zip](https://github.com/tensorflow/tensorflow/files/3490983/model-broken.tflite.zip)

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by impjdi** [comment]
@LK 

Sorry, but @NikolayChirkov switched teams and is no more working on this.  We currently don't have an owner.  This may take some time until we get a backfill =/

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.
