### ISSUE TITLE
How to identify the input and output array of a model for  ".tflite" conversion process. 

### ISSUE THREAD

**Issue by vismayaps** [tensorflow/tensorflow#31528]
I am trying to generate quantized .tflite model from .pb file. For the process I require the 'input_arrays' and 'output_arrays' of the model.
I've tried using the below methods to identify the input array and output array. But none of them worked.

Method 1:

```
import tensorflow as tf 
 frozen='/output/freeze/frozen_inference_graph.pb'
 gf = tf.GraphDef() 
 gf.ParseFromString(open(frozen,'rb').read()) 
 [n.name + '=>' +  n.op for n in gf.node if n.op in ('Softmax','Placeholder')]   
 [n.name + '=>' +  n.op for n in gf.node if n.op in ( 'Softmax','Mul')]

```
Method 2:
```
import tensorflow as tf
gf = tf.GraphDef()   
m_file = open('/output/freeze/frozen_inference_graph.pb','rb')
gf.ParseFromString(m_file.read())
for n in gf.node:
    print( n.name )

```
tflife conversion query:
import tensorflow as tf
graph_def_file = "new/barun/frozen_inference_graph.pb"
input_arrays = ['image_tensor']
output_arrays = ['BoxPredictor_5/ClassPredictor/act_quant/FakeQuantWithMinMaxVars']

converter = tf.lite.TFLiteConverter.from_frozen_graph(
  graph_def_file, input_arrays, output_arrays,input_shapes={"image_tensor":[1,300,300,3]})
converter.inference_type = tf.lite.constants.QUANTIZED_UINT8
tflite_model = converter.convert()
open("frozen_inference_graph_fd2819_2.tflite", "wb").write(tflite_model)`

How to find out the input_array and output_array from a tensorflow model(.pb file) ?``

**Comment by ravikyram** [comment]
Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version. Also, did you compile from source or install a binary?

If you are unclear what to include see the issue template displayed in [the Github new issue template](https://github.com/tensorflow/tensorflow/issues/new/choose).

We ask for this in the issue submission template, because it is really difficult to help without that information. Thanks!

**Comment by ravikyram** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Comment by sumannelli-Ib** [comment]
@vismayaps  Did you got the solution for this? I am facing this the same issue, please help.How to get the input and output arrays from a frozen model?
