### ISSUE TITLE
Colab TF 2.0 runs out of memory if eager execution is enabled

### ISSUE THREAD

**Issue by kielnino** [tensorflow/tensorflow#31535]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Google Colab (GPU Runtime)
- TensorFlow installed from (source or binary): binary (pip)
- TensorFlow version (use command below): 2.0.0-beta1
- Python version: 3.6 (Google Colab 3.6 Environment)
- CUDA/cuDNN version:  Google Colab (GPU Runtime)
- GPU model and memory:  Google Colab (GPU Runtime)

**Describe the current behavior**
If I use a large U-net with an Inception-ResNetv2 backbone and eager execution is enabled,(default with tf 2.0), the machine runs out of memory. If eager execution is disabled (`tf.compat.v1.disable_eager_execution()`), it works fine.

Maybe this is a bug in Google colab, as the code works fine with eager execution enabled on my machine with 8 GB of RAM and a Geforce 1060.

**Describe the expected behavior**
I would expect it to work in both modes similar.

**Code to reproduce the issue**
https://colab.research.google.com/drive/1-xgkBBUqZw6rS2WhxUMBZuY6j1uxG_e-

**Comment by ravikyram** [comment]
@kielnino 
I tried to reproduce your code in Google Colab but i am getting the below error.Please, help me to reproduce the issue.
![image](https://user-images.githubusercontent.com/51902062/62949114-3c752400-be03-11e9-91ab-614ced24a032.png)

**Comment by kielnino** [comment]
@ravikyram Thank you for having a look.
I forgot the efficientnet-module in the pip-installs. The colab is updated now.

**Comment by ravikyram** [comment]
@kielnino 
I have reproduced the issue in Colab with TF 2.0 beta1 in eager mode i got the below error`OSError: [Errno 12] Cannot allocate memory`.However i tried by disabling eager execution it was stuck for more than 30 mins after 1st epoch and it is till executing. Can you please confirm? Thanks!

**Comment by kielnino** [comment]
Yes, thats another issue with the `tf.keras.utils.Sequence` class and enabled multiprocessing, which I'm investigating at the moment. I've disabled multiprocessing in the Colab now, so that it should work now with eager execution disabled.

**Comment by ravikyram** [comment]
I am able to reproduce the issue with eager execution disabled.Please, find the [gist ](https://colab.research.google.com/drive/15MT-9pG2UBiXRrkUDXW5BGoQGzw0BpBS)here.Thanks!

**Comment by jvishnuvardhan** [comment]
@kielnino I don't see any issue when I replaced `!pip install -q tensorflow-gpu==2.0.0-beta1` with `!pip install -q tf-nightly-gpu-2.0-preview`. Please check the [gist here](https://colab.sandbox.google.com/gist/jvishnuvardhan/0ef0f98f59b3496bab443546511fac02/tf_31535.ipynb). Thanks!

**Comment by kielnino** [comment]
Your are right. Thanks for the hint. So I will use the nightly build instead.
