### ISSUE TITLE
Call to build function of GRUCell object segfaults if Keras precision is set to float16

### ISSUE THREAD

**Issue by loffermann** [tensorflow/tensorflow#31536]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): 18.10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: n/a
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.0.0-beta1
- Python version: 3.6.8
- Bazel version (if compiling from source): n/a
- GCC/Compiler version (if compiling from source): n/a
- CUDA/cuDNN version: 10.0/7.5
- GPU model and memory: Nvidia RTX 2080 Ti (11 GB)

**Describe the current behavior**
A call to the build() function of an instantiated GRUCell object with recurrent_initializer set to "orthogonal" (this is the default) terminates with a segmentation fault if Keras precision is set to float16.

**Describe the expected behavior**
Call to build() should succeed.

**Code to reproduce the issue**
```
import tensorflow as tf
tf.keras.backend.set_floatx("float16")

dim = 100
cell = tf.keras.layers.GRUCell(dim, recurrent_initializer="orthogonal")
cell.build([dim])
```
Test: set a different recurrent initializer (e.g. `recurrent_initializer="glorot_uniform"`) or remove `tf.keras.backend.set_floatx("float16")`. The function should now execute successfully.

**Other info / logs**
n/a

**Comment by oanush** [comment]
@loffermann ,
Please be informed that I tried executing the given code and I did not face any error.Can you provide more info?Thanks!

**Comment by loffermann** [comment]
@oanush I tried another computer (Ubuntu 18.04 and Quadro M1000M) and could not reproduce the issue either.
However, the issue is still reproducible on my original machine. I suspect this might be due to an unfortunate combination of CUDA drivers and Ubuntu kernel. I'll check that and come back if the problem still persists.
Thanks for helping me out!
