### ISSUE TITLE
Expose ConvLSTM2DCell

### ISSUE THREAD

**Issue by loffermann** [tensorflow/tensorflow#31537]
**System information**
- TensorFlow version (you are using): 2.0.0-beta1
- Are you willing to contribute it (Yes/No): Yes

**Describe the feature and the current behavior/state.**
Expose ConvLSTM2DCell via Keras API (as is the case with LSTMCell and GRUCell).

**Will this change the current api? How?**
Yes, ConvLSTM2DCell will be added (to tf.keras.layers).

**Who will benefit with this feature?**
Anyone with an interest in machine learning with video sequences (e.g. https://github.com/tensorflow/models/tree/master/research/video_prediction) who needs a way to integrate convolutional LSTM layers into their model that is more flexible than what the current API provides.

**Comment by rmothukuru** [comment]
@loffermann ,
In Github, with Tensorflow Version 2.0, `ConvLSTM2DCell` is in `keras/layers/convolutional_recurrent.py` in this [Github link](https://github.com/tensorflow/tensorflow/blob/d90e521d71b88f469e68eb1a467606ea6d44c733/tensorflow/python/keras/layers/convolutional_recurrent.py) and `LSTMCell` is in `keras/layers/recurrent.py` in [this link](https://github.com/tensorflow/tensorflow/blob/d90e521d71b88f469e68eb1a467606ea6d44c733/tensorflow/python/keras/layers/recurrent.py). 

That is, I mean to say that both the Methods are exposed via Keras API.

In case you have different opinion, please provide more details, or the links from Tensorflow Website or from Github Site. Thanks!

**Comment by loffermann** [comment]
Thanks for your reply.
As you described, the class for ConvLSTM2DCell is there – and I am aware of that. However, a @keras_export('keras.layers.ConvLSTM2DCell') is missing (line 484 [here](https://github.com/tensorflow/tensorflow/blob/d90e521d71b88f469e68eb1a467606ea6d44c733/tensorflow/python/keras/layers/convolutional_recurrent.py)), and thus the class is currently not accessible via the Keras API.

I checked by calling tf.keras.layers.ConvLSTM2DCell in TF 2.0.0-beta1, which fails with an AttributeError stating that "'tensorflow.python.keras.api._v2.keras.layers' has no attribute 'ConvLSTM2DCell'".

**Comment by rmothukuru** [comment]
@loffermann ,
I could run the below code without any error, for `Tensorflow` Version, `2.0.0-beta1`.

```
!pip install tensorflow==2.0.0-beta1
import tensorflow as tf
from tensorflow import keras
from keras.layers import ConvLSTM2DCell
```

Please try it at your end and let me know if it helps. Thanks!

**Comment by loffermann** [comment]
This works, thank you.
Wouldn't it be nice though to just add the export decorator for consistency? I guess this would also provide an entry and documentation for [the API docs](https://www.tensorflow.org/api_docs/python/tf/keras/layers), making an already implemented feature more visible.
If this is not possible for whatever reason, feel free to close this issue.

**Comment by rmothukuru** [comment]
@loffermann ,
`ConvLSTM2D` is already present in the link mentioned by you. Closing the issue as it is resolved.

**Comment by loffermann** [comment]
The import statement proposed by @rmothukuru does not work for me anymore. I am using the following instead:
`from tensorflow.python.keras.layers.convolutional_recurrent import ConvLSTM2DCell`

**Comment by SamKnightGit** [comment]
Is it possible to make this export similar to GRUCell or LSTMCell -- exposed through keras.layers? If this is appropriate  `ConvLSTMCell` should likely also be exposed.

Expected Import: `from tensorflow.keras.layers import ConvLSTM2DCell`

Actual Import: `from tensorflow.python.keras.layers.convolutional_recurrent import ConvLSTM2DCell`
