### ISSUE TITLE
In reference with https://github.com/tensorflow/tensorflow/issues/31406

### ISSUE THREAD

**Issue by VirRajpurohit** [tensorflow/tensorflow#31533]
@jdduke 

In reference with the issue
https://github.com/tensorflow/tensorflow/issues/31406

Basically what needs to be identified and what changes needs to be done in accordance with the model.

It can be understood that TensorFlowObjectDetectionAPIModel.java will require the changes. But what are those changes. 

As it is advised to check io shape with graph. Putting its result over here will help in any way possible?

**Comment by jdduke** [comment]
> As it is advised to check io shape with graph. Putting its result over here will help in any way possible?

That's fine, but I would recommend looking at the way input shapes/types are used in TensorFlowObjectDetectionAPIModel to better understand what changes you need to make.

**Comment by oanush** [comment]
@VirRajpurohit ,
Can you please go through that [link](https://www.tensorflow.org/lite/models/object_detection/overview).Thanks!

**Comment by VirRajpurohit** [comment]
@oanush 
Thanks for sharing link. I have gone through it.

Tried to understand the theory but as I am stepping as beginner in tensorflow,.

I just want to know that

Cannot copy between a TensorFlowLite tensor with shape [1, 1917, 4] and a Java object with shape [1, 3].

What above error actually says, Does anything needs to be changed in my model, if yes than what?

**Comment by jdduke** [comment]
1917 refers to the number of detections. How did you convert/obtain your model?

In general, it's better to use StackOverflow for this kinds of basic usability questions. Please post there and provide a link here.
