### ISSUE TITLE
Add adjust_batch or (re_batch) support for tf.data

### ISSUE THREAD

**Issue by yongtang** [tensorflow/tensorflow#31548]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using): N/A
- Are you willing to contribute it (Yes/No): Yes

**Describe the feature and the current behavior/state.**

At the moment `tf.data` has both `unbatch()` and `batch(n)` support, where you can either change the output of `tf.data` from `any`-batched ones to `non`-batched ones, or from `non`-batched ones to `n`-batched ones.

What is not available is the transformation from `m`-batched ones to `n`-batched ones directly.

Indirectly it is possible to achieve the above mentioned `m`-batched => `n-batched` through:
```
dataset = dataset.unbatch().batch(n)
```

However, in case each record is small in size (e.g., one record only have one float32) then `.unbatch().batch(n)` could be costly.

It would be great to have a way to shortcut with an `adjust_batch` or `re_batch` that achieve the same thing:
```
dataset = dataset.re_batch(n) # from m-batched to n-batched
```

Note there is already a `RebatchDataset` (which archives different goal) so not sure if `re_batch(n)` could be a good naming.

**Will this change the current api? How?**

No.
**Who will benefit with this feature?**

See description above.

**Any Other info.**

**Comment by jsimsa** [comment]
Hi @yongtang, do you have evidence that suggests that a fused implementation of `unbatch().batch()` would be more efficient than the existing one (based on two separate transformations)?

If so, I would be open to implementing this fused kernel and introducing it as a static optimization. In other words, users still write `unbatch().batch()` and tf.data would automatically rewrite this to fused implementation (similar to how `map().batch()` is automatically rewritten to the fused one).

**Comment by yongtang** [comment]
Thanks @jsimsa! Static optimization makes much more sense than introducing another op of rebatch. Let me take a look and see if I can create a PR with it.

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.
