### ISSUE TITLE
can't enable --config=cuda

### ISSUE THREAD

**Issue by zhangwei0119** [tensorflow/tensorflow#3154]
I successfully built tensorflow 0.9.0 with bazel 0.3.0 on Redhat Enterprices 6.6 without cuda support. 

### but when I enable --config=cuda, the build process stopped at linking '@protobuf//:protoc'

I suspected some settings associate with both cuda and python are incorrect (from the highlighted error logs) but have no idea how to reconfigure. Can you please help to find the problem?  I am using python2.7.11 from anaconda2

Thanks,
-Wei

$ bazel build --config=cuda @protobuf//:protoc --verbose_failures --keep_going
WARNING: /root/.cache/bazel/_bazel_root/33ff58ac202e7ac02dc3ff3533effc70/external/protobuf/WORKSPACE:1: Workspace name in /root/.cache/bazel/_bazel_root/33ff58ac202e7ac02dc3ff3533effc70/external/protobuf/WORKSPACE (@__main__) does not match the name given in the repository's definition (@protobuf); this will cause a build error in future versions.
INFO: Found 1 target...
ERROR: /root/.cache/bazel/_bazel_root/33ff58ac202e7ac02dc3ff3533effc70/external/protobuf/BUILD:331:1: Couldn't build file external/protobuf/protoc: Linking of rule '@protobuf//:protoc' failed: crosstool_wrapper_driver_is_not_gcc failed: error executing command
  (cd /root/.cache/bazel/_bazel_root/33ff58ac202e7ac02dc3ff3533effc70/execroot/tensorflow.gpu && \
  exec env - \
  third_party/gpus/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc -o bazel-out/local_linux-fastbuild/bin/external/protobuf/protoc bazel-out/local_linux-fastbuild/bin/external/protobuf/_objs/protoc/external/protobuf/src/google/protobuf/compiler/main.pic.o bazel-out/local_linux-fastbuild/bin/external/protobuf/libprotoc_lib.a bazel-out/local_linux-fastbuild/bin/external/protobuf/libprotobuf.a bazel-out/local_linux-fastbuild/bin/external/protobuf/libprotobuf_lite.a -lpthread -lstdc++ -B/usr/local/bin/ -pie -fPIC -Wl,-z,relro,-z,now -no-canonical-prefixes -pass-exit-codes '-Wl,--build-id=md5' '-Wl,--hash-style=gnu' -Wl,-S): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
### ImportError: No module named site
Target @protobuf//:protoc failed to build
INFO: Elapsed time: 0.354s, Critical Path: 0.01s

**Comment by zhangwei0119** [comment]
all the output files include "protoc" already generated with third_party/gpus/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc in the cache directory.  
And I also tried adding pythonhome to LD_LIBRARY_PATH DYLD_LIBRARY_PATH and even PATH. problem still same

**Comment by zhangwei0119** [comment]
shall I try r0.6?

**Comment by aselle** [comment]
It appears the linking of the protobuf library failed. But there is no error message just an exit code one. You'll have to see if there is a more detailed error on why that failed. If you can't find it in the bazel logs you can maybe try running the command from the shell yourself (make sure to get the environment matchin)

**Comment by aselle** [comment]
Automatically closing due to lack of recent activity. Please reopen when further information becomes available.
