### ISSUE TITLE
TensorFlow for C doesn't compile - cannot open source file "tensorflow/c/tf_attrtype.h"

### ISSUE THREAD

**Issue by RochaStratovan** [tensorflow/tensorflow#31567]
My team is requesting that we use the C API for tensorflow.

I followed the instructions outlined under "Install TensorFlow for C" (https://www.tensorflow.org/install/lang_c). However, when I attempt to compile it fails with the message:

> cannot open source file "tensorflow/c/tf_attrtype.h"

I am using Windows 10 with Visual Studio 2017. The steps used for installation/compilation are as follows:

1.  Download Windows CPU zip file
2. Extract to desktop folder tf-demo
   `C:\Users\....\Desktop\tf-demo`
3. Start Visual Studio 2017
4. Create a Console application project
5. Incorporate Example program in Visual Studio's 'main' file/routine.
6. Update Project's Additional Include Directories
   6.1 Right click on project
   6.2 Select Properties
   6.3 Expand Configuration
   6.4 Expand C/C++
   6.5 Select General
   6.6 Select Additional Include Directories
   6.7 Enter the path to the include files
       `C:\Users\....\Desktop\tf-demo\include`
   6.8 [Ok]
   6.9 [Ok]
7. Disable precompiled Headers
   7.1 Right click on project
   7.2 Select Properties
   7.3 Expand Cnfiguration
   7.4 Expand C/C++
   7.5 Select Precompiled Headers
   7.6 Change "Precompiled Headers" to "Not using...."
   7.7 [OK]

After this I compile and it fails with the messages

`
Severity	Code	Description	Project	File	Line	Suppression State
Error (active)	E1696	cannot open source file "tensorflow/c/tf_attrtype.h"	DemoProg

c:\Users\....\Desktop\tf-demo\include\tensorflow\c\c_api.h	22	
Error	C1083	Cannot open include file: 'tensorflow/c/tf_attrtype.h': No such file or directory	DemoProg	c:\users\....\desktop\tf-demo\include\tensorflow\c\c_api.h	22	
`

I reviewed the contents of the tf-demo directory and there is no tf_attrtype.h anywhere in the install package.
`
C:\Users\....\Desktop\tf-demo>dir /b /s

C:\Users\....\Desktop\tf-demo\include

C:\Users\....\Desktop\tf-demo\lib

C:\Users\....\Desktop\tf-demo\include\tensorflow

C:\Users\....\Desktop\tf-demo\include\tensorflow\c

C:\Users\....\Desktop\tf-demo\include\tensorflow\c\c_api.h

C:\Users\....\Desktop\tf-demo\include\tensorflow\c\eager

C:\Users\....\Desktop\tf-demo\include\tensorflow\c\LICENSE

C:\Users\....\Desktop\tf-demo\include\tensorflow\c\eager\c_api.h

C:\Users\....\Desktop\tf-demo\lib\tensorflow.dll

C:\Users\....\Desktop\tf-demo\lib\tensorflow.lib
`

**Comment by ravikyram** [comment]
Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version. Also, did you compile from source or install a binary?

If you are unclear what to include see the issue template displayed in the Github new issue [template](https://github.com/tensorflow/tensorflow/issues/new/choose).

We ask for this in the issue submission template, because it is really difficult to help without that information. Thanks!

**Comment by RochaStratovan** [comment]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
Windows 10
Visual Studio 2017

- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
Not applicable

- TensorFlow installed from (source or binary):
Assuming it's binary. The GIT hub page did (https://www.tensorflow.org/install/lang_c) not specify. Moreover, the contents of the installed material (see earlier post, did not have any source files but did have lib and dll)

- TensorFlow version:
I'm not sure about the version of tensor flow. The installer has the following name:
libtensorflow-cpu-windows-x86_64-1.14.0.zip

I'm guessing it is 1.14.0?

The installer was downloaded from the github page at https://www.tensorflow.org/install/lang_c that provides the instructions for installing and compiling the demo program.

- Python version:
Not applicable. I am using the C version

- Installed using virtualenv? pip? conda?:
Windows Zip file

- Bazel version (if compiling from source):
N/A

- GCC/Compiler version (if compiling from source):
N/A

- CUDA/cuDNN version:
N/A

- GPU model and memory:
N/A this is a compile problem not a run time problem.



**Describe the problem**
Doesn't compile. Complains about missing header files. See original problem description for details.

**Provide the exact sequence of commands / steps that you executed before running into the problem**
See original problem description for details

**Comment by ymodak** [comment]
Can you please try with [MSVC 2015](https://visualstudio.microsoft.com/vs/older-downloads/)?
Thanks!

**Comment by RochaStratovan** [comment]
Hello @ymodak ,

I get the same result with Visual Studio 2015.

I think the root cause is that the windows installation zip file does not have the file
`tensorflow/c/tf_attrtype.h`

The failure is that this file cannot be found, and the only header files present after the install are:

C:\Users\xxxx\Desktop\tf-demo>dir /b /s include
C:\Users\xxxx\Desktop\tf-demo\include\tensorflow
C:\Users\xxxx\Desktop\tf-demo\include\tensorflow\c
C:\Users\xxxx\Desktop\tf-demo\include\tensorflow\c\c_api.h
C:\Users\xxxx\Desktop\tf-demo\include\tensorflow\c\eager
C:\Users\xxxx\Desktop\tf-demo\include\tensorflow\c\LICENSE
C:\Users\xxxx\Desktop\tf-demo\include\tensorflow\c\eager\c_api.h

**Comment by ymodak** [comment]
Yes you are right ```tensorflow/c/tf_attrtype.h``` is missing in windows package.

**Comment by ceshdelgado** [comment]
Download linux package, inside it copy `tensorflow/c/tf_attrtype.h`, then paste inside windows package. It works for me!

**Comment by RochaStratovan** [comment]
Thank you @cesarsalgado. This is a great workaround that we will use. I also look forward to the Windows installer being fixed so that it is complete.

**Comment by Saduf2019** [comment]
@RochaStratovan please confirm if your issue is resolved.

**Comment by RochaStratovan** [comment]
@Saduf2019, I can confirm that I no longer have the error when I work with 1.15.0

Thank you.

**Comment by Saduf2019** [comment]
Moving this issue to resolved status as per confirmation

**Comment by gunan** [comment]
@yifeif @av8ramit looks like some headers are missing on the windows package.

**Comment by PirateSama** [comment]
I solved the problem.  The windows package is complete. You have just to specify the path in the include like this 
#include<tensorflow/c/c_api.h>
And do not include the complete path in your project properties just stop your path in the include folder. 
Like this : $(SolutionDir)/tensorflow/include/
