### ISSUE TITLE
decode_png returns shape of 3 dimensions of question marks

### ISSUE THREAD

**Issue by HassanAlsamahi** [tensorflow/tensorflow#31562]
I am trying to read an image and convert it into tensor using the following code

```
img_path = <image directory>
img_raw = tf.io.read_file(img_path)
img_tensor = tf.image.decode_png(img_raw)
```

and when I try to print its shape 
`print(img_tensor.shape)`

it gives me 3 question marks instead of values:
`(?, ?, ?)
`

why it doesn't work and how to fix this??

**Comment by ymodak** [comment]
I guess you are using TF 1.X.  You can try couple of things
- Try using ```tf.session``` to print value of ```img_tensor.shape```
-  Simply enable eager execution and run code snippet 
```python
import tensorflow as tf
tf.enable_eager_execution()
img_path = <image directory>
img_raw = tf.io.read_file(img_path)
img_tensor = tf.image.decode_png(img_raw)
print(img_tensor.shape)
```

**Comment by HassanAlsamahi** [comment]
yeah the tf.Session solved my problem, thanks

**Comment by ymodak** [comment]
Are you satisfied with the resolution of your issue?
[Yes](https://goo.gl/forms/Oe0tEvODFRoI2gJF3)
[No](https://goo.gl/forms/fUjzOfrtkFbrOT8d2)
