### ISSUE TITLE
 tensorflow estimator doesn't need to depend on tensorflow

### ISSUE THREAD

**Issue by yurivict** [tensorflow/tensorflow#31570]
Tensorflow estimator (https://github.com/tensorflow/estimator) installs only a set of python files, and doesn't really require Tensorflow to build. However, its build looks for Tensorflow for some reason.

Please remove the build-time Tensorflow dependency in Tensorflow estimator.

Estimator should actually be either a part of Tensorflow itself, or Tensorflow should depend on it because the Tensorflow's python code imports it.

(Created a bug here because the estimator project doesn't allow issues for some reason.)

**Comment by karmel** [comment]
The Estimator package is pulled into TF proper, such that installing tensorflow includes tensorflow_estimator. The separate estimator package is not designed to be used independently per se, as it is part of the main TF package.

**Comment by mihaimaruseac** [comment]
For slightly more context: Estimator is separated from main TensorFlow for separation of concerns, to modularize code (see also https://github.com/tensorflow/community/pull/77). This allows for faster development and can make it function like a plugin.

However, Estimator is not designed to be used individually or to just do `import tensorflow_estimator` directly.

We are currently working on making this a better situation but the above context is our end goal

**Comment by yurivict** [comment]
I committed the FreeBSD port for TensorFlow but then I had to create a separate port for estimator because it was missing.
