### ISSUE TITLE
Performance issue: per-device memory usage increases with number of devices within tf.distribute strategy 

### ISSUE THREAD

**Issue by mjlbach** [tensorflow/tensorflow#31588]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 16.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: No
- TensorFlow installed from (source or binary): tf-nightly-gpu-2.0-preview==
- TensorFlow version (use command below): v1.12.1-8566-g207bd43 2.0.0-dev20190812
- Python version: 3.7.4
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 10.0/7.4.2
- GPU model and memory: (4) Titan Xp 12 gb 

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
Tensor memory allocation fails for the same batch size (determined by n_acton_samples)  as I scale the number of GPUs in my strategy.

**Describe the expected behavior**
Without the distributed strategy, I can readily pass a batch size of 300 to a given GPU, within the distributed strategy, this drops to 200 on 2 GPUs, and 70 on 4 GPUs.

**Code to reproduce the issue**
<details>
  <summary>Example code snippet</summary>

```
def tree_search(
    inputs, self_model, world_model, plan_sequence
):
    n_action_samples = 1000
    tree_value = tf.zeros([n_action_samples, 1], dtype=tf.float32)

    for idx, action in enumerate(plan_sequence):
        # print("idx: ", idx)
        if idx == 0 and action:

            candidate_actions = tf.random.uniform(
                [n_action_samples, 1, num_fingers, 7],
                minval=-1.0,
                maxval=1.0,
                dtype=tf.float32,
            )


        elif idx > 0 and action:
            pass

        elif idx > 0 and not action:
               candidate_actions = tf.zeros(
                [n_action_samples, 1, num_fingers, 7],
                dtype=tf.float32,
            )


        else:
            pass

        tree_value += policy_model(candidate_actions, inputs)
        inputs = world_model(candidate_actions, inputs)

    retval = {"action": candidate_actions, "tree_value": tree_value}

    return retval

@tf.function
def policy(
    inputs,
    policy_model,
    world_model,
    strategy
):

    take_action = [True, False, False]

    distributed_output = strategy.experimental_run_v2(
        tree_search,
        args=(
            inputs,
            self_model,
            world_model,
            plan_sequence,
        ),
    )

     distributed_output["tree_value"] = tf.concat(
            strategy.experimental_local_results(distributed_output["tree_value"]), axis=0
        )

     distributed_output["action"] = tf.concat(
            strategy.experimental_local_results(distributed_output["action"]), axis=0
        )


    action = choose_max_value_action(
       distributed_output["action"], distributed_output["tree_value"]
    )

    return action
```

</details>

**Other info / logs**
On a related note, it seems like there's a regression in the tf.summary.start_trace() based method of profiling models that is required by 2.0. The new tensorboard interface allows visualizing execution time of ops, but there doesn't seem to be a way to show memory usage.

**Comment by mjlbach** [comment]
As an update, it appears this was partly caused by the use of range instead of tf.range in both the unrolling of my dynamics model and composing keras layers (I converted pre 2.0 code that was built using Graph mode to autograph which iterated over a list containing each layer size). Swapping tf.range and switching to tensor arrays to collect loop results decreased by autograph graph construction time from 15 minutes to 5 minutes, and decreased memory usage by a factor of ~5. 

However, I'm now getting errors of the form:

```
    ctx=ctx)                                                                                                                                                                [85/7009]
  File "/home/mjlbach/.virtualenvs/physics3/lib/python3.6/site-packages/tensorflow_core/python/eager/execute.py", line 67, in quick_execute
    six.raise_from(core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.InvalidArgumentError: 4 root error(s) found.
  (0) Invalid argument:  List contains uninitialized tensor at index 0 but leading_dims has only 0 elements.
         [[node replica_2/TensorListConcatV2 (defined at home/mjlbach/.virtualenvs/physics3/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py:1748) ]]
         [[L2Loss/_890]]
  (1) Invalid argument:  List contains uninitialized tensor at index 0 but leading_dims has only 0 elements.
         [[node replica_2/TensorListConcatV2 (defined at home/mjlbach/.virtualenvs/physics3/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py:1748) ]]
  (2) Cancelled:
  (3) Cancelled:
0 successful operations.
1 derived errors ignored. [Op:__inference_distributed_train_step_743779]

Function call stack:
distributed_train_step -> distributed_train_step -> distributed_train_step -> distributed_train_step


If you suspect this is an IPython bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@python.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    %config Application.verbose_crash=True

Policy time: 10.194841623306274
Exception ignored in: <bound method Socket.__del__ of <zmq.sugar.socket.Socket object at 0x7f8048041e18>>
Traceback (most recent call last):
  File "/home/mjlbach/.virtualenvs/physics3/lib/python3.6/site-packages/zmq/sugar/socket.py", line 67, in __del__
  File "/home/mjlbach/.virtualenvs/physics3/lib/python3.6/site-packages/zmq/sugar/socket.py", line 105, in close
  File "/home/mjlbach/.virtualenvs/physics3/lib/python3.6/site-packages/zmq/sugar/context.py", line 153, in _rm_socket
TypeError: 'NoneType' object is not callable
train_3obj_2for.sh: line 50: 152409 Segmentation fault      (core dumped) python ../boxphysics/scripts/train.py --expId box_rollout_3 --config_path ../boxphysics/data/default_config
.py --train_steps 500000 --num_fingers 2 --num_objects 3 --n_action_samples 500 --scene_particles 300 --gpu 5,6,7,8 --dynamic_group --div_mass 1 --norm_relation 1 --avd_obj_mask 1 -
-use_running_mean 1 --use_materials 1 --seq_len 2 --with_coll 1 --with_act 1 --add_gloss 4 --gravity_term 9.81 --alpha 0.01 --OB1 1 --OB2 2 --room_center 0.0,0.0,0.0 --max_collision
_distance 0.3 --network_func ffhyp_result_without_rcnn --cacheDirPrefix /data3/mjlbach/models/box_physics --greedy_start 1. --greedy_end .1 --greedy_time 2000 --lr_boundary 4000,800
0,12000 --init_lr_self 1.0 --rendernode localhost --train_seed 17 --with_static 0 --history_len 300 --batches_per_gather 4 --policy_mode thom_sampling --heat .01 --forcelowerlimit 5
000. --forceupperlimit 8000. --rewardclipping 1. --wm_loss_scaling 1000. --clipping_front_factor 1. --loading_from_old True --batchsize 100
bash train_3obj_2for.sh  108395.54s user 3913.45s system 963% cpu 3:14:12.68 total
```

Eager to autograph is extremely hard to debug due to how opaque the error messages are, and the lack of comparable tools for debugging like the memory profiler and analyzer which work only in the tf1 style graph mode. I saw the recent RFC 20190815-tfdbg-v2-callbacks which may go some of the way to addressing this, but currently I don't think there is a good way to view per-tensor memory usage in a way similar to 1.0

**Comment by mdanatg** [comment]
Leaving aside the debugability issues and the support for shape_invariants for a moment, using range means that the loop is unrolled in the graph. So with range, a new subgraph is created for each loop iteration. That should explain the slow graph construction as well as the memory usage increase, because there are more temporary tensors involved. My wild guess would be that the graph construction time and memory usage is in the order of n_acton_samples * <number of devices>.

Assigning @guptapriya for the slowness question when tf.range is involved.

**Comment by guptapriya** [comment]
@mjlbach can you share the code that throws the error you mentioned above  (List contains uninitialized tensor at index 0 but leading_dims has only 0 elements). Do you get this error only when using dist strat?

**Comment by mjlbach** [comment]
I agree that the memory growth issue under dist-strat was compounded due to the for loops using range, which makes sense given the creation of additional subgraphs. However, when using tf.range, it appears to impose additional constraints on the functions called within the loop which cause the uninitialized tensor errors. The issue originated because a lot of my model involves graph operations on a flat graph of the following type:

```
outputs = list()
for i in range(iterations):
    output.append(MLP(graph[:, i]))
tf.concat(output, axis=-1)
```
While fine under tf 1.0, these constructs throw an error if wrapped in a tf.range.

If I convert to use TensorArrays and tf.range:
```
outputs = tf.TensorArray(dtype=tf.float32, size=iterations, infer_size=False
for i in tf.range(iterations):
    outputs = outputs.write(i, MLP(input[i]))
outputs = outputs.concat()
```

Are the performance reasons always in favor of using tf.range? Is there ever any reason to use range? 

I'm still investigating and I'll try to post a minimal example reproducing the issue and as a template for others with similar issues.

**Comment by mdanatg** [comment]
About range vs. tf.range: in general, when the number of iterations is fixed, the memory constraints (particularly graph size) dictate the preference for tf.range. You are correct, the tf.range version might pay some runtime overhead, but that should be extremely small. There are some situations when tf.range cannot be used, for example in a loop that builds the layers of a neural net: `for i in range(num_layers): build_layer(i)`. Otherwise, it's a good idea to use tf.range whenever possible.
