### ISSUE TITLE
parallel_for: No converter defined for Cross

### ISSUE THREAD

**Issue by djl11** [tensorflow/tensorflow#31593]
Currently PFor is not registered for tf.cross operation, as evident in [pfor.py](https://github.com/tensorflow/tensorflow/blob/21f5e55ccc42daf14e6386d1d27d0103b29f2c92/tensorflow/python/ops/parallel_for/pfor.py).

With this operation being very fundamental to linear algebra, it seems to me it would be very useful, particularly for enabling vectorization for efficient jacobain computation of functions using the cross product.

**Comment by agarwal-ashish** [comment]
A converter has been added and should make its way into the nightly.
