### ISSUE TITLE
Recursively copying elements from one graph to another

### ISSUE THREAD

**Issue by srjoglekar246** [tensorflow/tensorflow#316]
One nifty feature to have in the codebase would be allowing recursive copying of Operation/Tensor/Variable instances from one graph to another. By recursive, I mean that copying the 'top' node (say the trainer for a basic NN) would automatically copy all the required Ops and tensors in the dataflow graph.
This could allow users to easily port common components of different frameworks from an 'origin' graph to a 'target' graph. To avoid naming conflicts, we could add the copied elements under a common namespace in the target graph.

I tried writing up some code for it, and since the project doesn't accept pull request as of now, wrote up a blog post about it. I would like the community's feed back on possible issues or applications. Thanks!

Heres a link to the post: https://codesachin.wordpress.com/2015/11/20/recursively-copying-elements-from-one-graph-to-another-in-tensorflow/

**Comment by vrv** [comment]
Thanks for the feature request!  We're also experimenting with support for defining "functions" in the graph that would basically allow re-usable components to achieve the same effect.

**Comment by srjoglekar246** [comment]
Thats great! If you guys do enable PRs, you could have a look at my code to see if it can do the job.

**Comment by girving** [comment]
Looks like this fell through the cracks.  PRs have been enabled for a while.  @martinwicke: Does this seem appropriate for `contrib`?

**Comment by martinwicke** [comment]
@vrv, what's the status of graph functions? We probably should standardize to one way of doing things, although even in the presence of functions functionality like this seems valuable to extract things from an existing graph.

**Comment by vrv** [comment]
@zffchen78

**Comment by vrv** [comment]
I think we accepted this to contrib, closing.
