### ISSUE TITLE
How the embedding matrix is optimized using DNNLinearCombinedClassifier

### ISSUE THREAD

**Issue by sjtusmartboy** [tensorflow/tensorflow#31602]
From the document: https://www.tensorflow.org/api_docs/python/tf/contrib/learn/DNNLinearCombinedClassifier

We know the parameter includes linear_optimizer and dnn_optimizer that can be used to optimize the linear part and dnn part of the weights. However, it seems that the optimization of the weight of embedding matrix is not involved, such as embedding matrix of the wide and deep model. So my question is that is the optimization of the embedding matrix not involved in reality or is there any default way of optimizing the embedding matrix that I do not know

estimator = DNNLinearCombinedClassifier(
    # common settings
    n_classes=n_classes,
    weight_column_name=weight_column_name,
    # wide settings
    linear_feature_columns=[sparse_feature_a_x_sparse_feature_b],
    linear_optimizer=tf.compat.v1.train.FtrlOptimizer(...),
    # deep settings
    dnn_feature_columns=[sparse_feature_a_emb, sparse_feature_b_emb],
    dnn_hidden_units=[1000, 500, 100],
    dnn_optimizer=tf.compat.v1.train.AdagradOptimizer(...))

**Comment by Leslie-Fang** [comment]
@sjtusmartboy 
Sorry, I didn't quite understand your question.
But DNNLinearCombinedClassifier definitely can be used to build and train the Wide and Deep models.

**Comment by oanush** [comment]
@sjtusmartboy ,
Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version.
Also can you check feedback from @Leslie-Fang regarding the issue.Thanks!

**Comment by oanush** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
