### ISSUE TITLE
Auto-Configuration Error: Couldn't find undname.exe under C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\

### ISSUE THREAD

**Issue by mayadav1** [tensorflow/tensorflow#31608]
**System information**
- OS Platform : Windows 10
- TensorFlow installed from (source or binary): source
- TensorFlow version: r1.13
- Python version:  python3.6
- Installed using virtualenv? pip? conda?: conda
- Bazel version (if compiling from source): 0.21.0
- Compiler version (if compiling from source): VS2019,16.2,MSVC++=14.22

**Describe the problem**
Auto-Configuration Error: Couldn't find undname.exe under C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\, please check your VC installation and set BAZEL_VC environment variable correctly.

**Provide the exact sequence of commands / steps that you executed before running into the problem**

1)conda create -n tensorflow-1.13.1-without-mkl python=3.6 anaconda
2)conda activate tensorflow-1.13.1-without-mkl
3)Install MSYS2
set environmental variable, under PATH -> C:\msys64\usr\bin
4)Install JDK12 and set environmental variable : JAVA_HOME = C:\Program Files\Java\jdk-12
5)pacman -Syu zip unzip
6)pacman -Syuu --noconfirm patch
7)set BAZEL_VC=C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC
8) set BAZEL_SH=C:\msys64\usr\bin\bash.exe
9) git clone https://github.com/tensorflow/tensorflow.git -b r1.4
10) python ./configure.py

You have bazel 0.21.0 installed.
Please specify the location of python. [Default is C:\Users\zen2-\Anaconda2\envs\tensorflow-1.13.1-without-mkl\python.exe]:
Found possible Python library paths:
  C:\Users\zen2-\Anaconda2\envs\tensorflow-1.13.1-without-mkl\lib\site-packages
Please input the desired Python library path to use.  Default is [C:\Users\zen2-\Anaconda2\envs\tensorflow-1.13.1-without-mkl\lib\site-packages]
Do you wish to build TensorFlow with XLA JIT support? [y/N]: N
No XLA JIT support will be enabled for TensorFlow.
Do you wish to build TensorFlow with ROCm support? [y/N]: N
No ROCm support will be enabled for TensorFlow.
Do you wish to build TensorFlow with CUDA support? [y/N]: N
No CUDA support will be enabled for TensorFlow.
Please specify optimization flags to use during compilation when bazel option "--config=opt" is specified [Default is /arch:AVX]:
Would you like to override eigen strong inline for some C++ compilation to reduce the compilation time? [Y/n]: Y

11)bazel build --config=opt //tensorflow/tools/pip_package:build_pip_package

**Any other info / logs**

WARNING: Option 'experimental_shortened_obj_file_path' is deprecated
INFO: Invocation ID: ca6515c1-83e0-4ddf-a065-733711b4a9ff
ERROR: C:/users/zen2-/tensorflow/tensorflow/python/BUILD:4172:1: no such package '@local_config_def_file_filter//': Traceback (most recent call last):
        File "C:/users/zen2-/tensorflow/tensorflow/tools/def_file_filter/def_file_filter_configure.bzl", line 37
                auto_configure_fail(("Couldn't find undname.exe unde...))
        File "C:/users/zen2-/_bazel_zen2_microsoft/ldf7kfdv/external/bazel_tools/tools/cpp/lib_cc_configure.bzl", line 109, in auto_configure_fail
                fail(("\n%sAuto-Configuration Error:%...)))

Auto-Configuration Error: Couldn't find undname.exe under C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\, please check your VC installation and set BAZEL_VC environment variable correctly.
 and referenced by '//tensorflow/python:pywrap_tensorflow_filtered_def_file'
ERROR: Analysis of target '//tensorflow/tools/pip_package:build_pip_package' failed; build aborted: no such package '@local_config_def_file_filter//': Traceback (most recent call last):
        File "C:/users/zen2-/tensorflow/tensorflow/tools/def_file_filter/def_file_filter_configure.bzl", line 37
                auto_configure_fail(("Couldn't find undname.exe unde...))
        File "C:/users/zen2-/_bazel_zen2_microsoft/ldf7kfdv/external/bazel_tools/tools/cpp/lib_cc_configure.bzl", line 109, in auto_configure_fail
                fail(("\n%sAuto-Configuration Error:%...)))

Auto-Configuration Error: Couldn't find undname.exe under C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\, please check your VC installation and set BAZEL_VC environment variable correctly.
INFO: Elapsed time: 0.713s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (5 packages loaded, 20 targets configured)
    currently loading: tensorflow/lite/schema ... (3 packages)
    Fetching @cython; fetching
    Fetching @swig; fetching
    Fetching @local_config_git; Restarting.
    Fetching @grpc; fetching
    Fetching @local_config_def_file_filter; fetching
    Fetching @flatbuffers; fetching
    Fetching @eigen_archive; fetching
    Fetching @icu; fetching ... (9 fetches)

Please correct me in case wrong .

**Comment by gunan** [comment]
I do not think bazel 0.21 has any support for visual studio 2019.
AFAICR, you need at least bazel 0.26 to do anything with MSVC2019.
Adding @laszlocsomor @meteorcloudy

**Comment by laszlocsomor** [comment]
Correct.

**Comment by mayadav1** [comment]
Error After bazel 0.28.1 and tf-r1.14

ERROR: C:/users/zen2-/rev1/tensorflow/tensorflow/compiler/mlir/lite/python/BUILD:12:1: C++ compilation of rule '//tensorflow/compiler/mlir/lite/python:graphdef_to_tfl_flatbuffer' failed (Exit 2)
cl : Command line warning D9002 : ignoring unknown option '-std=c++14'
tensorflow/compiler/mlir/lite/python/graphdef_to_tfl_flatbuffer.cc(144): error C2059: syntax error: ':'
tensorflow/compiler/mlir/lite/python/graphdef_to_tfl_flatbuffer.cc(147): error C2143: syntax error: missing ';' before '}'
tensorflow/compiler/mlir/lite/python/graphdef_to_tfl_flatbuffer.cc(148): error C2065: 'pass_config': undeclared identifier
tensorflow/compiler/mlir/lite/python/graphdef_to_tfl_flatbuffer.cc(148): error C2065: 'pm': undeclared identifier
tensorflow/compiler/mlir/lite/python/graphdef_to_tfl_flatbuffer.cc(148): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
tensorflow/compiler/mlir/lite/python/graphdef_to_tfl_flatbuffer.cc(148): error C2365: 'tensorflow::AddTFToTFLConversionPasses': redefinition; previous definition was 'function'
.\tensorflow/compiler/mlir/lite/tf_tfl_passes.h(34): note: see declaration of 'tensorflow::AddTFToTFLConversionPasses'
tensorflow/compiler/mlir/lite/python/graphdef_to_tfl_flatbuffer.cc(148): error C2513: 'tensorflow::AddTFToTFLConversionPasses': no variable declared before '='
tensorflow/compiler/mlir/lite/python/graphdef_to_tfl_flatbuffer.cc(150): error C2059: syntax error: 'return'
tensorflow/compiler/mlir/lite/python/graphdef_to_tfl_flatbuffer.cc(156): error C2059: syntax error: '}'
tensorflow/compiler/mlir/lite/python/graphdef_to_tfl_flatbuffer.cc(156): error C2143: syntax error: missing ';' before '}'
Target //tensorflow/tools/pip_package:build_pip_package failed to build
INFO: Elapsed time: 3035.976s, Critical Path: 1511.08s
INFO: 10156 processes: 10156 local.
FAILED: Build did NOT complete successfully

**Comment by laszlocsomor** [comment]
Tensorflow-1.14.0 needs Bazel 0.24.1 (https://www.tensorflow.org/install/source#linux).
Sorry, looks like you can't use VS 2019 until TensorFlow supports at least Bazel 0.26

**Comment by laszlocsomor** [comment]
If you can install VS 2017 and set `BAZEL_VC` with Bazel 0.24.1, it should work.

**Comment by mayadav1** [comment]
@laszlocsomor TF-r1.14 failed with VS 2017 and Bazel 0.24.1

ERROR: C:/users/zen2-/rev2/tensorflow/tensorflow/python/keras/api/BUILD:12:1: Executing genrule //tensorflow/python/keras/api:keras_python_api_gen failed (Exit 1): bash.exe failed: error executing command
  cd C:/users/zen2-/_bazel_zen2_microsoft/z7ecj6tr/execroot/org_tensorflow
  SET PATH=C:\msys64\usr\bin;C:\msys64\bin;C:\Users\zen2-\Anaconda2\envs\tensorflow-1.13.1-without-mkl;C:\Users\zen2-\Anaconda2\envs\tensorflow-1.13.1-without-mkl\Library\mingw-w64\bin;C:\Users\zen2-\Anaconda2\envs\tensorflow-1.13.1-without-mkl\Library\usr\bin;C:\Users\zen2-\Anaconda2\envs\tensorflow-1.13.1-without-mkl\Library\bin;C:\Users\zen2-\Anaconda2\envs\tensorflow-1.13.1-without-mkl\Scripts;C:\Users\zen2-\Anaconda2\envs\tensorflow-1.13.1-without-mkl\bin;C:\Users\zen2-\Anaconda2\condabin;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\bin;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\libnvvp;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files\dotnet\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Strawberry\c\bin;C:\Strawberry\perl\site\bin;C:\Strawberry\perl\bin;C:\Program Files\Git\cmd;C:\Program Files\CMake\bin;C:\Program Files\AMD\AMDuProf\bin;C:\Program Files\NVIDIA Corporation\Nsight Compute 2019.3.0\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Ruby26-x64\bin;C:\Users\zen2-\Anaconda2;C:\Users\zen2-\Anaconda2\Library\mingw-w64\bin;C:\Users\zen2-\Anaconda2\Library\usr\bin;C:\Users\zen2-\Anaconda2\Library\bin;C:\Users\zen2-\Anaconda2\Scripts;C:\Users\zen2-\Anaconda3;C:\Users\zen2-\Anaconda3\Library\mingw-w64\bin;C:\Users\zen2-\Anaconda3\Library\usr\bin;C:\Users\zen2-\Anaconda3\Library\bin;C:\Users\zen2-\Anaconda3\Scripts;C:\Users\zen2-\AppData\Roaming\local\bin;C:\Users\zen2-\AppData\Local\Microsoft\WindowsApps;C:\Program Files (x86)\Notepad++\;C:\Strawberry\perl\bin\;C:\Program Files\Git\bin\;C:\Users\zen2-\AppData\Local\bin\NASM\;C:\Program Files\7-Zip\;C:\Users\zen2-\AppData\Local\Programs\Python\Python37-32\;C:\msvc\src\ExternalApis\Windows\10\sdk\10.0\bin\x64\;C:\Users\zen2-\.dotnet\tools;C:\msys64\usr\bin\;C:\Program Files (x86)\IntelSWTools\VTune Amplifier 2019\bin64\;C:\bazel;
    SET PYTHON_BIN_PATH=C:/Users/zen2-/Anaconda2/envs/tensorflow-1.13.1-without-mkl/python.exe
    SET PYTHON_LIB_PATH=C:/Users/zen2-/Anaconda2/envs/tensorflow-1.13.1-without-mkl/lib/site-packages
    SET TF_CONFIGURE_IOS=0
    SET TF_DOWNLOAD_CLANG=0
    SET TF_NEED_CUDA=0
    SET TF_NEED_OPENCL_SYCL=0
    SET TF_NEED_ROCM=0
  C:/msys64/usr/bin/bash.exe -c source external/bazel_tools/tools/genrule/genrule-setup.sh; bazel-out/x64_windows-opt/bin/tensorflow/python/keras/api/create_tensorflow.python_api_1_keras_python_api_gen.exe  --apidir=bazel-out/x64_windows-opt/genfiles/tensorflow/python/keras/api --apiname=keras --apiversion=1  --package=tensorflow.python,tensorflow.python.keras --output_package=tensorflow.python.keras.api bazel-out/x64_windows-opt/genfiles/tensorflow/python/keras/api/__init__.py bazel-out/x64_windows-opt/genfiles/tensorflow/python/keras/api/keras/__init__.py bazel-out/x64_windows-opt/genfiles/tensorflow/python/keras/api/keras/activations/__init__.py bazel-out/x64_windows-opt/genfiles/tensorflow/python/keras/api/keras/applications/__init__.py bazel-out/x64_windows-opt/genfiles/tensorflow/python/keras/api/keras/applications/densenet/__init__.py bazel-out/x64_windows-opt/genfiles/tensorflow/python/keras/api/keras/applications/inception_resnet_v2/__init__.py bazel-out/x64_windows-opt/genfiles/tensorflow/python/keras/api/keras/applications/inception_v3/__init__.py bazel-out/x64_windows-opt/genfiles/tensorflow/python/keras/api/keras/applications/mobilenet/__init__.py bazel-out/x64_windows-opt/genfiles/tensorflow/python/keras/api/keras/applications/mobilenet_v2/__init__.py bazel-out/x64_windows-opt/genfiles/tensorflow/python/keras/api/keras/applications/nasnet/__init__.py bazel-out/x64_windows-opt/genfiles/tensorflow/python/keras/api/keras/applications/resnet50/__init__.py bazel-out/x64_windows-opt/genfiles/tensorflow/python/keras/api/keras/applications/vgg16/__init__.py bazel-out/x64_windows-opt/genfiles/tensorflow/python/keras/api/keras/applications/vgg19/__init__.py bazel-out/x64_windows-opt/genfiles/tensorflow/python/keras/api/keras/applications/xception/__init__.py bazel-out/x64_windows-opt/genfiles/tensorflow/python/keras/api/keras/backend/__init__.py bazel-out/x64_windows-opt/genfiles/tensorflow/python/keras/api/keras/callbacks/__init__.py bazel-out/x64_windows-opt/genfiles/tensorflow/python/keras/api/keras/constraints/__init__.py bazel-out/x64_windows-opt/genfiles/tensorflow/python/keras/api/keras/datasets/__init__.py bazel-out/x64_windows-opt/genfiles/tensorflow/python/keras/api/keras/datasets/boston_housing/__init__.py bazel-out/x64_windows-opt/genfiles/tensorflow/python/keras/api/keras/datasets/cifar10/__init__.py bazel-out/x64_windows-opt/genfiles/tensorflow/python/keras/api/keras/datasets/cifar100/__init__.py bazel-out/x64_windows-opt/genfiles/tensorflow/python/keras/api/keras/datasets/fashion_mnist/__init__.py bazel-out/x64_windows-opt/genfiles/tensorflow/python/keras/api/keras/datasets/imdb/__init__.py bazel-out/x64_windows-opt/genfiles/tensorflow/python/keras/api/keras/datasets/mnist/__init__.py bazel-out/x64_windows-opt/genfiles/tensorflow/python/keras/api/keras/datasets/reuters/__init__.py bazel-out/x64_windows-opt/genfiles/tensorflow/python/keras/api/keras/estimator/__init__.py bazel-out/x64_windows-opt/genfiles/tensorflow/python/keras/api/keras/experimental/__init__.py bazel-out/x64_windows-opt/genfiles/tensorflow/python/keras/api/keras/initializers/__init__.py bazel-out/x64_windows-opt/genfiles/tensorflow/python/keras/api/keras/layers/__init__.py bazel-out/x64_windows-opt/genfiles/tensorflow/python/keras/api/keras/layers/experimental/__init__.py bazel-out/x64_windows-opt/genfiles/tensorflow/python/keras/api/keras/losses/__init__.py bazel-out/x64_windows-opt/genfiles/tensorflow/python/keras/api/keras/metrics/__init__.py bazel-out/x64_windows-opt/genfiles/tensorflow/python/keras/api/keras/mixed_precision/__init__.py bazel-out/x64_windows-opt/genfiles/tensorflow/python/keras/api/keras/mixed_precision/experimental/__init__.py bazel-out/x64_windows-opt/genfiles/tensorflow/python/keras/api/keras/models/__init__.py bazel-out/x64_windows-opt/genfiles/tensorflow/python/keras/api/keras/optimizers/__init__.py bazel-out/x64_windows-opt/genfiles/tensorflow/python/keras/api/keras/optimizers/schedules/__init__.py bazel-out/x64_windows-opt/genfiles/tensorflow/python/keras/api/keras/preprocessing/__init__.py bazel-out/x64_windows-opt/genfiles/tensorflow/python/keras/api/keras/preprocessing/image/__init__.py bazel-out/x64_windows-opt/genfiles/tensorflow/python/keras/api/keras/preprocessing/sequence/__init__.py bazel-out/x64_windows-opt/genfiles/tensorflow/python/keras/api/keras/preprocessing/text/__init__.py bazel-out/x64_windows-opt/genfiles/tensorflow/python/keras/api/keras/regularizers/__init__.py bazel-out/x64_windows-opt/genfiles/tensorflow/python/keras/api/keras/utils/__init__.py bazel-out/x64_windows-opt/genfiles/tensorflow/python/keras/api/keras/wrappers/__init__.py bazel-out/x64_windows-opt/genfiles/tensorflow/python/keras/api/keras/wrappers/scikit_learn/__init__.py
Execution platform: @bazel_tools//platforms:host_platform
Traceback (most recent call last):
  File "\\?\C:\Users\zen2-\AppData\Local\Temp\Bazel.runfiles_rjl2ejn7\runfiles\org_tensorflow\tensorflow\python\tools\api\generator\create_python_api.py", line 27, in <module>
    from tensorflow.python.tools.api.generator import doc_srcs
  File "\\?\C:\Users\zen2-\AppData\Local\Temp\Bazel.runfiles_rjl2ejn7\runfiles\org_tensorflow\tensorflow\python\__init__.py", line 83, in <module>
    from tensorflow.python import keras
  File "\\?\C:\Users\zen2-\AppData\Local\Temp\Bazel.runfiles_rjl2ejn7\runfiles\org_tensorflow\tensorflow\python\keras\__init__.py", line 32, in <module>
    from tensorflow.python.keras import datasets
  File "\\?\C:\Users\zen2-\AppData\Local\Temp\Bazel.runfiles_rjl2ejn7\runfiles\org_tensorflow\tensorflow\python\keras\datasets\__init__.py", line 25, in <module>
    from tensorflow.python.keras.datasets import imdb
  File "\\?\C:\Users\zen2-\AppData\Local\Temp\Bazel.runfiles_rjl2ejn7\runfiles\org_tensorflow\tensorflow\python\keras\datasets\imdb.py", line 25, in <module>
    from tensorflow.python.keras.preprocessing.sequence import _remove_long_seq
  File "\\?\C:\Users\zen2-\AppData\Local\Temp\Bazel.runfiles_rjl2ejn7\runfiles\org_tensorflow\tensorflow\python\keras\preprocessing\__init__.py", line 21, in <module>
    import keras_preprocessing
ModuleNotFoundError: No module named 'keras_preprocessing'
Target //tensorflow/tools/pip_package:build_pip_package failed to build
INFO: Elapsed time: 57.284s, Critical Path: 54.35s
INFO: 0 processes.
FAILED: Build did NOT complete successfully

I have tried pip install keras --user but didn't work for me.

**Comment by laszlocsomor** [comment]
So the C++ compilation succeeds, that's good news!
Sorry, but I don't know about the Python error. @gunan , does it ring a bell?

**Comment by gunan** [comment]
Looks like missing dependencies.
Please make sure you follow the guide here to install all the prerequisites:
https://www.tensorflow.org/install/source#setup_for_linux_and_macos

**Comment by AtlantaPepsi** [comment]
@mayadav1 so how did you resolve the problem eventually? I'm currently on Bazel 3.2 but still got pretty much the same problem as yours. My BAZEL_VC was set to F:\C\vs\Enterprise\VC\Tools\MSVC\14.24.28314\bin\Hostx86\x86, where there literally is a undname.exe but bazel build keeps giving me auto-config error

**Comment by maxrohleder** [comment]
@AtlantaPepsi did you make progress here? Same thing happens to me now with tf2.4.0, bazel 3.1 and MSVC 2019

**Comment by mraunak** [comment]
setting the path in following ways helped to resolve the above issue

set BAZEL_SH=C:\msys64\usr\bin\bash.exe

set BAZEL_VS=C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools

set BAZEL_VC=C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC

set BAZEL_VC_FULL_VERSION=14.29.30133
