### ISSUE TITLE
Issue with model.predict()

### ISSUE THREAD

**Issue by imbakassinn** [tensorflow/tensorflow#31600]
- **Have I written custom code - Yes I have written some custom code
- **OS Platform and Distribution - Ubuntu Server 18.04
- **TensorFlow installed from - Installed by pip
- **TensorFlow version (use command below)**: v2.0.0-beta0-16-g1d91213fe7 2.0.0-beta1
- **Python version**: 3.6.7
- **Exact command to reproduce**: 
```
        trainarray = np.array([0,0,0,0,0,0,0])
        model = tf.keras.models.Sequential([
          tf.keras.layers.Dense(7, input_shape= trainarray.shape),
          tf.keras.layers.Dense(12),
          tf.keras.layers.Dense(1)
        ])
        model.predict(np.array([0,0,0,0,0,0,0]))
```

### Describe the problem
When I try to predict with the model created above I get the following error: 

> ValueError: Error when checking input: expected dense_input to have shape (7,) but got array with shape (1,)

The input array (np.array([0,0,0,0,0,0,0])) does obviously have the shape 7, but not 1, so to me this looks like a bug. I've tried to go under the hood to see what might be causing this, but I haven't found the cause yet.

**Comment by WindQAQ** [comment]
Hi @imbakassinn, since dense layer takes `N-D` tensor (N >= 2) as input with first dimension=batch_size and obviously the `trainarray` is a `1-D` array, this is why the issue caused. So the workable example should be

```python
import numpy as np
import tensorflow as tf

# suppose batch_size=1
# trainarray is a 2-D array of shape [1, 7] of batch_size=1
trainarray = np.array([[0,0,0,0,0,0,0]])
# excluding batch_size
# for more details, please refer to the first example in
# https://www.tensorflow.org/api_docs/python/tf/keras/layers/Dense
input_shape = [trainarray.shape[1]]

model = tf.keras.models.Sequential([
  tf.keras.layers.Dense(7, input_shape=input_shape),
  tf.keras.layers.Dense(12),
  tf.keras.layers.Dense(1)
])

model.predict(np.array([[0,0,0,0,0,0,0]]))
```

https://www.tensorflow.org/api_docs/python/tf/keras/layers/Dense#input_shape

**Comment by gadagashwini** [comment]
@imbakassinn, did @WindQAQ's solution worked for you. Thanks!

**Comment by gadagashwini** [comment]
Looks like issue is resolved. Please reopen if still issue persists. Thanks!
