### ISSUE TITLE
 custom implementations: DEPTH_TO_SPACE.

### ISSUE THREAD

**Issue by jichangsheng** [tensorflow/tensorflow#31604]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 14.04):
- TensorFlow installed from (binary):
- TensorFlow version (1.14.0):

  Some of the operators in the model are not supported by the standard TensorFlow Lite runtime and are not recognized by TensorFlow. If you have a custom implementation for them you can disable this error with --allow_custom_ops, or by setting allow_custom_ops=True when calling tf.lite.TFLiteConverter(). Here is a list of builtin operators you are using: ADD, CONV_2D, TANH. Here is a list of operators for which you will need custom implementations: DEPTH_TO_SPACE.

```
# Copy and paste here
```

Also, please include a link to a GraphDef or the model if possible.

**Any other info / logs**

Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by gadagashwini** [comment]
@jichangsheng,
Provide the exact sequence of commands / steps that you executed before running into the problem. Thanks!

**Comment by jichangsheng** [comment]
i want to convert pb file to tflite file using TFliteConverter of TensorFlow 1.14.0, it is failed because SubpixelConv2d in tensorlayer contained a custom op named “DEPTH_TO_SPACE” appeared.When I set “converter.allow_custom_ops=True” it is successed to
converted to tflite file，but when i use python to reuse
the tflie file to produce model，it is still faied showing “didnot find custom op for name “DEPTH_TO_SPACE”，i wonder how to slove this issue？Thinks






--
发自我的网易邮箱手机智能版



在 2019-08-19 16:35:00，gadagashwini <notifications@github.com> 写道：


@jichangsheng,
Provide the exact sequence of commands / steps that you executed before running into the problem. Thanks!

**Comment by haozha111** [comment]
Hi,

DepthToSpace is added as built-in op recently into TF-Lite. Could you try run the conversion with the most recent tf-nightly build? Let me know if you encounter new issues, thanks!
