### ISSUE TITLE
tf-lite android so build fail

### ISSUE THREAD

**Issue by GerScau** [tensorflow/tensorflow#31612]
**System information**
- OS Platform and Distribution:  (e.g., Linux Ubuntu 18.04)
- TensorFlow installed from (source or binary):  source 
- TensorFlow version: r1.13
- Python version: 2.7
- Bazel version (if compiling from source):  0.24.1
- GCC/Compiler version (if compiling from source):  gcc version 4.8.5
NDK version 14
SDK version 24

*Describe the problem**
`bazel build -c opt //tensorflow/contrib/android:libtensorflow_inference.so    --crosstool_top=//external:android/crosstool    --host_crosstool_top=@bazel_tools//tools/cpp:toolchain    --cxxopt=-std=c++11    --cpu=arm64-v8a`

when i try the build command, it throws clang compile error. so why ndk14 use clang but not gcc g++?

The document might be confused, since some code have changed on git but doc haven't
In fact, I have try many tools version combination: ndk 14 / 12, bazel 0.20.0/ 0.21.0/ 0.24.1. Each combination throws different error

Could you show me a working tool verison combination of bazel, ndk, sdk and tf version, which is tested?

Thank you!

------------------------------------------------
**error log:**
ERROR: /home/ger/opt/tensorflow/tensorflow/core/kernels/BUILD:6575:1: C++ compilation of rule '//tensorflow/core/kernels:android_tensorflow_kernels' failed (Exit 1)
In file included from tensorflow/core/kernels/cwise_op_erf.cc:16:
In file included from ./tensorflow/core/kernels/cwise_ops_common.h:29:
In file included from ./tensorflow/core/kernels/cwise_ops.h:23:
In file included from ./third_party/eigen3/unsupported/Eigen/CXX11/Tensor:1:
In file included from external/eigen_archive/unsupported/Eigen/CXX11/Tensor:29:
In file included from external/eigen_archive/unsupported/Eigen/CXX11/../SpecialFunctions:50:
external/eigen_archive/unsupported/Eigen/CXX11/../src/SpecialFunctions/SpecialFunctionsImpl.h:415:5: error: static_assert failed "THIS_TYPE_IS_NOT_SUPPORTED"
    EIGEN_STATIC_ASSERT((internal::is_same<Scalar, Scalar>::value == false),
    ^                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
external/eigen_archive/unsupported/Eigen/CXX11/../../../Eigen/src/Core/util/StaticAssert.h:33:40: note: expanded from macro 'EIGEN_STATIC_ASSERT'
    #define EIGEN_STATIC_ASSERT(X,MSG) static_assert(X,#MSG);
                                       ^             ~
external/eigen_archive/unsupported/Eigen/CXX11/../src/SpecialFunctions/SpecialFunctionsImpl.h:2114:44: note: in instantiation of member function 'Eigen::internal::erf_impl<float>::run' requested here
  return EIGEN_MATHFUNC_IMPL(erf, Scalar)::run(x);
                                           ^
external/eigen_archive/unsupported/Eigen/CXX11/../src/SpecialFunctions/SpecialFunctionsFunctors.h:248:31: note: in instantiation of function template specialization 'Eigen::numext::erf<float>' requested here
    using numext::erf; return erf(a);
                              ^
external/eigen_archive/unsupported/Eigen/CXX11/src/Tensor/TensorEvaluator.h:434:12: note: in instantiation of member function 'Eigen::internal::scalar_erf_op<float>::operator()' requested here
    return m_functor(m_argImpl.coeff(index));
           ^
external/eigen_archive/unsupported/Eigen/CXX11/src/Tensor/TensorAssign.h:156:42: note: in instantiation of member function 'Eigen::TensorEvaluator<const Eigen::TensorCwiseUnaryOp<Eigen::internal::scalar_erf_op<float>, const Eigen::TensorMap<Eigen::Tensor<const float, 1, 1, long>, 16, MakePointer> >, Eigen::ThreadPoolDevice>::coeff' requested here
    m_leftImpl.coeffRef(i) = m_rightImpl.coeff(i);
                                         ^
external/eigen_archive/unsupported/Eigen/CXX11/src/Tensor/TensorExecutor.h:218:17: note: in instantiation of member function 'Eigen::TensorEvaluator<const Eigen::TensorAssignOp<Eigen::TensorMap<Eigen::Tensor<float, 1, 1, long>, 16, MakePointer>, const Eigen::TensorCwiseUnaryOp<Eigen::internal::scalar_erf_op<float>, const Eigen::TensorMap<Eigen::Tensor<const float, 1, 1, long>, 16, MakePointer> > >, Eigen::ThreadPoolDevice>::evalScalar' requested here
      evaluator.evalScalar(i);
                ^
external/eigen_archive/unsupported/Eigen/CXX11/src/Tensor/TensorExecutor.h:283:39: note: (skipping 2 contexts in backtrace; use -ftemplate-backtrace-limit=0 to see all)
                           EvalRange::run(&evaluator, firstIdx, lastIdx);
                                      ^
./tensorflow/core/kernels/cwise_ops_common.h:278:17: note: in instantiation of function template specialization 'Eigen::TensorDevice<Eigen::TensorMap<Eigen::Tensor<float, 1, 1, long>, 16, MakePointer>, Eigen::ThreadPoolDevice>::operator=<Eigen::TensorCwiseUnaryOp<Eigen::internal::scalar_erf_op<float>, const Eigen::TensorMap<Eigen::Tensor<const float, 1, 1, long>, 16, MakePointer> > >' requested here
  out.device(d) = rhs;
                ^
./tensorflow/core/kernels/cwise_ops_common.h:541:5: note: in instantiation of function template specialization 'tensorflow::functor::Assign<Eigen::ThreadPoolDevice, Eigen::TensorMap<Eigen::Tensor<float, 1, 1, long>, 16, MakePointer>, Eigen::TensorCwiseUnaryOp<Eigen::internal::scalar_erf_op<float>, const Eigen::TensorMap<Eigen::Tensor<const float, 1, 1, long>, 16, MakePointer> > >' requested here
    Assign(d, out, in.unaryExpr(typename Functor::func()));
    ^
./tensorflow/core/kernels/cwise_ops_common.h:249:5: note: in instantiation of member function 'tensorflow::functor::UnaryFunctor<Eigen::ThreadPoolDevice, tensorflow::functor::erf<float> >::operator()' requested here
    functor::UnaryFunctor<Device, Functor>()(
    ^
./tensorflow/core/kernels/cwise_ops_common.h:234:12: note: in instantiation of member function 'tensorflow::UnaryOp<Eigen::ThreadPoolDevice, tensorflow::functor::erf<float> >::Compute' requested here
  explicit UnaryOp(OpKernelConstruction* ctx) : OpKernel(ctx) {
           ^
tensorflow/core/kernels/cwise_op_erf.cc:19:11: note: in instantiation of member function 'tensorflow::UnaryOp<Eigen::ThreadPoolDevice, tensorflow::functor::erf<float> >::UnaryOp' requested here
REGISTER3(UnaryOp, CPU, "Erf", functor::erf, float, Eigen::half, double);
          ^
In file included from tensorflow/core/kernels/cwise_op_erf.cc:16:
In file included from ./tensorflow/core/kernels/cwise_ops_common.h:29:
In file included from ./tensorflow/core/kernels/cwise_ops.h:23:
In file included from ./third_party/eigen3/unsupported/Eigen/CXX11/Tensor:1:
In file included from external/eigen_archive/unsupported/Eigen/CXX11/Tensor:29:
In file included from external/eigen_archive/unsupported/Eigen/CXX11/../SpecialFunctions:50:
external/eigen_archive/unsupported/Eigen/CXX11/../src/SpecialFunctions/SpecialFunctionsImpl.h:415:5: error: static_assert failed "THIS_TYPE_IS_NOT_SUPPORTED"
    EIGEN_STATIC_ASSERT((internal::is_same<Scalar, Scalar>::value == false),
    ^                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
external/eigen_archive/unsupported/Eigen/CXX11/../../../Eigen/src/Core/util/StaticAssert.h:33:40: note: expanded from macro 'EIGEN_STATIC_ASSERT'
    #define EIGEN_STATIC_ASSERT(X,MSG) static_assert(X,#MSG);
                                       ^             ~
external/eigen_archive/unsupported/Eigen/CXX11/../src/SpecialFunctions/SpecialFunctionsImpl.h:2114:44: note: in instantiation of member function 'Eigen::internal::erf_impl<Eigen::half>::run' requested here
  return EIGEN_MATHFUNC_IMPL(erf, Scalar)::run(x);
                                           ^
external/eigen_archive/unsupported/Eigen/CXX11/../src/SpecialFunctions/SpecialFunctionsFunctors.h:248:31: note: in instantiation of function template specialization 'Eigen::numext::erf<Eigen::half>' requested here
    using numext::erf; return erf(a);
                              ^
external/eigen_archive/unsupported/Eigen/CXX11/src/Tensor/TensorEvaluator.h:434:12: note: in instantiation of member function 'Eigen::internal::scalar_erf_op<Eigen::half>::operator()' requested here
    return m_functor(m_argImpl.coeff(index));
           ^
external/eigen_archive/unsupported/Eigen/CXX11/src/Tensor/TensorAssign.h:156:42: note: in instantiation of member function 'Eigen::TensorEvaluator<const Eigen::TensorCwiseUnaryOp<Eigen::internal::scalar_erf_op<Eigen::half>, const Eigen::TensorMap<Eigen::Tensor<const Eigen::half, 1, 1, long>, 16, MakePointer> >, Eigen::ThreadPoolDevice>::coeff' requested here
    m_leftImpl.coeffRef(i) = m_rightImpl.coeff(i);
                                         ^
external/eigen_archive/unsupported/Eigen/CXX11/src/Tensor/TensorExecutor.h:218:17: note: in instantiation of member function 'Eigen::TensorEvaluator<const Eigen::TensorAssignOp<Eigen::TensorMap<Eigen::Tensor<Eigen::half, 1, 1, long>, 16, MakePointer>, const Eigen::TensorCwiseUnaryOp<Eigen::internal::scalar_erf_op<Eigen::half>, const Eigen::TensorMap<Eigen::Tensor<const Eigen::half, 1, 1, long>, 16, MakePointer> > >, Eigen::ThreadPoolDevice>::evalScalar' requested here
      evaluator.evalScalar(i);
                ^
external/eigen_archive/unsupported/Eigen/CXX11/src/Tensor/TensorExecutor.h:283:39: note: (skipping 2 contexts in backtrace; use -ftemplate-backtrace-limit=0 to see all)
                           EvalRange::run(&evaluator, firstIdx, lastIdx);
                                      ^
./tensorflow/core/kernels/cwise_ops_common.h:278:17: note: in instantiation of function template specialization 'Eigen::TensorDevice<Eigen::TensorMap<Eigen::Tensor<Eigen::half, 1, 1, long>, 16, MakePointer>, Eigen::ThreadPoolDevice>::operator=<Eigen::TensorCwiseUnaryOp<Eigen::internal::scalar_erf_op<Eigen::half>, const Eigen::TensorMap<Eigen::Tensor<const Eigen::half, 1, 1, long>, 16, MakePointer> > >' requested here
  out.device(d) = rhs;
                ^
./tensorflow/core/kernels/cwise_ops_common.h:541:5: note: in instantiation of function template specialization 'tensorflow::functor::Assign<Eigen::ThreadPoolDevice, Eigen::TensorMap<Eigen::Tensor<Eigen::half, 1, 1, long>, 16, MakePointer>, Eigen::TensorCwiseUnaryOp<Eigen::internal::scalar_erf_op<Eigen::half>, const Eigen::TensorMap<Eigen::Tensor<const Eigen::half, 1, 1, long>, 16, MakePointer> > >' requested here
    Assign(d, out, in.unaryExpr(typename Functor::func()));
    ^
./tensorflow/core/kernels/cwise_ops_common.h:249:5: note: in instantiation of member function 'tensorflow::functor::UnaryFunctor<Eigen::ThreadPoolDevice, tensorflow::functor::erf<Eigen::half> >::operator()' requested here
    functor::UnaryFunctor<Device, Functor>()(
    ^
./tensorflow/core/kernels/cwise_ops_common.h:234:12: note: in instantiation of member function 'tensorflow::UnaryOp<Eigen::ThreadPoolDevice, tensorflow::functor::erf<Eigen::half> >::Compute' requested here
  explicit UnaryOp(OpKernelConstruction* ctx) : OpKernel(ctx) {
           ^
tensorflow/core/kernels/cwise_op_erf.cc:19:11: note: in instantiation of member function 'tensorflow::UnaryOp<Eigen::ThreadPoolDevice, tensorflow::functor::erf<Eigen::half> >::UnaryOp' requested here
REGISTER3(UnaryOp, CPU, "Erf", functor::erf, float, Eigen::half, double);
          ^
In file included from tensorflow/core/kernels/cwise_op_erf.cc:16:
In file included from ./tensorflow/core/kernels/cwise_ops_common.h:29:
In file included from ./tensorflow/core/kernels/cwise_ops.h:23:
In file included from ./third_party/eigen3/unsupported/Eigen/CXX11/Tensor:1:
In file included from external/eigen_archive/unsupported/Eigen/CXX11/Tensor:29:
In file included from external/eigen_archive/unsupported/Eigen/CXX11/../SpecialFunctions:50:
external/eigen_archive/unsupported/Eigen/CXX11/../src/SpecialFunctions/SpecialFunctionsImpl.h:415:5: error: static_assert failed "THIS_TYPE_IS_NOT_SUPPORTED"
    EIGEN_STATIC_ASSERT((internal::is_same<Scalar, Scalar>::value == false),
    ^                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
external/eigen_archive/unsupported/Eigen/CXX11/../../../Eigen/src/Core/util/StaticAssert.h:33:40: note: expanded from macro 'EIGEN_STATIC_ASSERT'
    #define EIGEN_STATIC_ASSERT(X,MSG) static_assert(X,#MSG);
                                       ^             ~
external/eigen_archive/unsupported/Eigen/CXX11/../src/SpecialFunctions/SpecialFunctionsImpl.h:2114:44: note: in instantiation of member function 'Eigen::internal::erf_impl<double>::run' requested here
  return EIGEN_MATHFUNC_IMPL(erf, Scalar)::run(x);
                                           ^
external/eigen_archive/unsupported/Eigen/CXX11/../src/SpecialFunctions/SpecialFunctionsFunctors.h:248:31: note: in instantiation of function template specialization 'Eigen::numext::erf<double>' requested here
    using numext::erf; return erf(a);
                              ^
external/eigen_archive/unsupported/Eigen/CXX11/src/Tensor/TensorEvaluator.h:434:12: note: in instantiation of member function 'Eigen::internal::scalar_erf_op<double>::operator()' requested here
    return m_functor(m_argImpl.coeff(index));
           ^
external/eigen_archive/unsupported/Eigen/CXX11/src/Tensor/TensorAssign.h:156:42: note: in instantiation of member function 'Eigen::TensorEvaluator<const Eigen::TensorCwiseUnaryOp<Eigen::internal::scalar_erf_op<double>, const Eigen::TensorMap<Eigen::Tensor<const double, 1, 1, long>, 16, MakePointer> >, Eigen::ThreadPoolDevice>::coeff' requested here
    m_leftImpl.coeffRef(i) = m_rightImpl.coeff(i);
                                         ^
external/eigen_archive/unsupported/Eigen/CXX11/src/Tensor/TensorExecutor.h:218:17: note: in instantiation of member function 'Eigen::TensorEvaluator<const Eigen::TensorAssignOp<Eigen::TensorMap<Eigen::Tensor<double, 1, 1, long>, 16, MakePointer>, const Eigen::TensorCwiseUnaryOp<Eigen::internal::scalar_erf_op<double>, const Eigen::TensorMap<Eigen::Tensor<const double, 1, 1, long>, 16, MakePointer> > >, Eigen::ThreadPoolDevice>::evalScalar' requested here
      evaluator.evalScalar(i);
                ^
external/eigen_archive/unsupported/Eigen/CXX11/src/Tensor/TensorExecutor.h:283:39: note: (skipping 2 contexts in backtrace; use -ftemplate-backtrace-limit=0 to see all)
                           EvalRange::run(&evaluator, firstIdx, lastIdx);
                                      ^
./tensorflow/core/kernels/cwise_ops_common.h:278:17: note: in instantiation of function template specialization 'Eigen::TensorDevice<Eigen::TensorMap<Eigen::Tensor<double, 1, 1, long>, 16, MakePointer>, Eigen::ThreadPoolDevice>::operator=<Eigen::TensorCwiseUnaryOp<Eigen::internal::scalar_erf_op<double>, const Eigen::TensorMap<Eigen::Tensor<const double, 1, 1, long>, 16, MakePointer> > >' requested here
  out.device(d) = rhs;
                ^
./tensorflow/core/kernels/cwise_ops_common.h:541:5: note: in instantiation of function template specialization 'tensorflow::functor::Assign<Eigen::ThreadPoolDevice, Eigen::TensorMap<Eigen::Tensor<double, 1, 1, long>, 16, MakePointer>, Eigen::TensorCwiseUnaryOp<Eigen::internal::scalar_erf_op<double>, const Eigen::TensorMap<Eigen::Tensor<const double, 1, 1, long>, 16, MakePointer> > >' requested here
    Assign(d, out, in.unaryExpr(typename Functor::func()));
    ^
./tensorflow/core/kernels/cwise_ops_common.h:249:5: note: in instantiation of member function 'tensorflow::functor::UnaryFunctor<Eigen::ThreadPoolDevice, tensorflow::functor::erf<double> >::operator()' requested here
    functor::UnaryFunctor<Device, Functor>()(
    ^
./tensorflow/core/kernels/cwise_ops_common.h:234:12: note: in instantiation of member function 'tensorflow::UnaryOp<Eigen::ThreadPoolDevice, tensorflow::functor::erf<double> >::Compute' requested here
  explicit UnaryOp(OpKernelConstruction* ctx) : OpKernel(ctx) {
           ^
tensorflow/core/kernels/cwise_op_erf.cc:19:11: note: in instantiation of member function 'tensorflow::UnaryOp<Eigen::ThreadPoolDevice, tensorflow::functor::erf<double> >::UnaryOp' requested here
REGISTER3(UnaryOp, CPU, "Erf", functor::erf, float, Eigen::half, double);
          ^
3 errors generated.
Target //tensorflow/contrib/android:libtensorflow_inference.so failed to build

**Comment by freedomtan** [comment]
What you were trying to build `//tensorflow/contrib/android:libtensorflow_inference.so` is a part of deprecated TensorFlow Mobile. You may wanna try [TFLite](https://www.tensorflow.org/lite/guide) instead.

**Comment by GerScau** [comment]
> What you were trying to build `//tensorflow/contrib/android:libtensorflow_inference.so` is a part of deprecated TensorFlow Mobile. You may wanna try [TFLite](https://www.tensorflow.org/lite/guide) instead.

Thank you for your suggestion, actually i want to make a windows Java application running on the arm development board with ubuntu18.04. I need jar and so lib to use the python model.

**Comment by GerScau** [comment]
> What you were trying to build `//tensorflow/contrib/android:libtensorflow_inference.so` is a part of deprecated TensorFlow Mobile. You may wanna try [TFLite](https://www.tensorflow.org/lite/guide) instead.

I try to use tensorflow-lite, get the .arr file. but it load the so file fail, seems arm64-v8a so can not run on aarch64 board?

**Comment by freedomtan** [comment]
1. I don't know if Java binding works well on non-Android platforms
2. when you said "arm64-v8a so", you meant Android one right? Android's system libraries (libc and others) are different from standard Linux. That's why it doesn't work. Usually, arm64-v8a == aarch64, but that doesn't mean software compatible.
3. model is not in Python
4. You may want to start from prebuilt aarch64 binaries for Python, such as ones at [here](https://github.com/PINTO0309/Tensorflow-bin) built by @PINTO0309

**Comment by GerScau** [comment]
> 1. I don't know if Java binding works well on non-Android platforms
> 2. when you said "arm64-v8a so", you meant Android one right? Android's system libraries (libc and others) are different from standard Linux. That's why it doesn't work. Usually, arm64-v8a == aarch64, but that doesn't mean software compatible.
> 3. model is not in Python
> 4. You may want to start from prebuilt aarch64 binaries for Python, such as ones at [here](https://github.com/PINTO0309/Tensorflow-bin) built by @PINTO0309

非常感謝提供這些思路！
i try using python, then setup service for java calling

**Comment by gadagashwini** [comment]
@GerScau, Were you able to resolve the issue? Thanks!

**Comment by gadagashwini** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
