### ISSUE TITLE
fatal error LNK1201:check for insufficient disk space, invalid path, or insufficient privilege

### ISSUE THREAD

**Issue by 1shi12shi2** [tensorflow/tensorflow#31610]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Window 10
- TensorFlow installed from (source or binary): build from source
- TensorFlow version: 1.12.0
- Python version: 3.6.7
- Bazel version (if compiling from source): 0.15.0
- GCC/Compiler version (if compiling from source): VS2015 update3
- CUDA/cuDNN version:9/7
- GPU model and memory:Titan V 11G

**Describe the problem**
When I build debug version Tensorflow on windows 10。Linker error 1201 ocoured，
LINK : fatal error LNK1201: error writing to program database 'C:\users\dl\_bazel_dl\hd37h63o\execroot\org_tensorflow\bazel-out\x64_windows-dbg\bin\tensorflow\libtensorflow_cc.pdb'; check for insufficient disk space, invalid path, or insufficient privilege。

**Any other info / logs**
ERROR: D:/clone/tensorflow-1.12.0/source/tensorflow/BUILD:449:1: Linking of rule '//tensorflow:libtensorflow_cc.so' failed (Exit 1201): link.exe failed: error executing command
  cd C:/users/dl/_bazel_dl/hd37h63o/execroot/org_tensorflow
  SET INCLUDE=C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE;C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\INCLUDE;C:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\ucrt;C:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um;C:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\shared;C:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\um;C:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\winrt;
    SET LIB=C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\LIB\amd64;C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\LIB\amd64;C:\Program Files (x86)\Windows Kits\10\lib\10.0.17763.0\ucrt\x64;C:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\lib\um\x64;C:\Program Files (x86)\Windows Kits\10\lib\10.0.17763.0\um\x64;
    SET PATH=C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\amd64;C:\Windows\Microsoft.NET\Framework64\v4.0.30319;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\Tools;C:\Program Files (x86)\Windows Kits\10\bin\x64;C:\Program Files (x86)\Windows Kits\10\bin\x86;C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.6.1 Tools\x64\;;C:\Windows\system32
    SET PWD=/proc/self/cwd
    SET PYTHON_BIN_PATH=D:/clone/tensorflow-1.12.0/venv/Scripts/python.exe
    SET PYTHON_LIB_PATH=D:/clone/tensorflow-1.12.0/venv/lib/site-packages
    SET TEMP=C:\Users\DL\AppData\Local\Temp
    SET TF_DOWNLOAD_CLANG=0
    SET TF_NEED_CUDA=0
    SET TF_NEED_OPENCL_SYCL=0
    SET TF_NEED_ROCM=0
    SET TMP=C:\Users\DL\AppData\Local\Temp
    SET USE_LINKER=1
  C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/amd64/link.exe /nologo /DLL /SUBSYSTEM:CONSOLE -def:tensorflow/tf_exported_symbols_msvc.lds -defaultlib:advapi32.lib -DEFAULTLIB:advapi32.lib /MACHINE:X64 @bazel-out/x64_windows-dbg/bin/tensorflow/libtensorflow_cc.so-2.params /DEBUG:FULL /INCREMENTAL:NO
   Creating library bazel-out/x64_windows-dbg/bin/tensorflow/libtensorflow_cc.so.if.lib and object bazel-out/x64_windows-dbg/bin/tensorflow/libtensorflow_cc.so.if.exp
libtensorflow_cc.so.if.exp : warning LNK4070: /OUT:tensorflow_cc.dll directive in .EXP differs from output filename 'bazel-out/x64_windows-dbg/bin/tensorflow/libtensorflow_cc.so'; ignoring directive
pin_to_host_optimizer.lib(pin_to_host_optimizer.obj) : warning LNK4049: locally defined symbol ?DEVICE_CPU@tensorflow@@3QEBDEB (char const * const tensorflow::DEVICE_CPU) imported
collective_param_resolver_distributed.lib(collective_param_resolver_distributed.obj) : warning LNK4049: locally defined symbol ?DEVICE_CPU@tensorflow@@3QEBDEB (char const * const tensorflow::DEVICE_CPU) imported
batch_kernels.lo.lib(batch_kernels.obj) : warning LNK4049: locally defined symbol ?DEVICE_CPU@tensorflow@@3QEBDEB (char const * const tensorflow::DEVICE_CPU) imported
captured_function.lib(captured_function.obj) : warning LNK4049: locally defined symbol ?DEVICE_CPU@tensorflow@@3QEBDEB (char const * const tensorflow::DEVICE_CPU) imported
arithmetic_optimizer.lib(arithmetic_optimizer.obj) : warning LNK4049: locally defined symbol ?DEVICE_CPU@tensorflow@@3QEBDEB (char const * const tensorflow::DEVICE_CPU) imported
tfprof_show.lib(tfprof_show.obj) : warning LNK4217: locally defined symbol TF_NewStatus imported in function "protected: bool __cdecl tensorflow::tfprof::TFShow::LookUpCheckPoint(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,class std::unique_ptr<class tensorflow::tfprof::TFProfTensor,struct std::default_delete<class tensorflow::tfprof::TFProfTensor> > *)" (?LookUpCheckPoint@TFShow@tfprof@tensorflow@@IEAA_NAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEAV?$unique_ptr@VTFProfTensor@tfprof@tensorflow@@U?$default_delete@VTFProfTensor@tfprof@tensorflow@@@std@@@5@@Z)
tfprof_show.lib(tfprof_show.obj) : warning LNK4217: locally defined symbol TF_DeleteStatus imported in function "protected: bool __cdecl tensorflow::tfprof::TFShow::LookUpCheckPoint(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,class std::unique_ptr<class tensorflow::tfprof::TFProfTensor,struct std::default_delete<class tensorflow::tfprof::TFProfTensor> > *)" (?LookUpCheckPoint@TFShow@tfprof@tensorflow@@IEAA_NAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEAV?$unique_ptr@VTFProfTensor@tfprof@tensorflow@@U?$default_delete@VTFProfTensor@tfprof@tensorflow@@@std@@@5@@Z)
tfprof_show.lib(tfprof_show.obj) : warning LNK4217: locally defined symbol TF_GetCode imported in function "protected: bool __cdecl tensorflow::tfprof::TFShow::LookUpCheckPoint(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,class std::unique_ptr<class tensorflow::tfprof::TFProfTensor,struct std::default_delete<class tensorflow::tfprof::TFProfTensor> > *)" (?LookUpCheckPoint@TFShow@tfprof@tensorflow@@IEAA_NAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEAV?$unique_ptr@VTFProfTensor@tfprof@tensorflow@@U?$default_delete@VTFProfTensor@tfprof@tensorflow@@@std@@@5@@Z)
tfprof_show.lib(tfprof_show.obj) : warning LNK4217: locally defined symbol TF_Message imported in function "protected: bool __cdecl tensorflow::tfprof::TFShow::LookUpCheckPoint(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,class std::unique_ptr<class tensorflow::tfprof::TFProfTensor,struct std::default_delete<class tensorflow::tfprof::TFProfTensor> > *)" (?LookUpCheckPoint@TFShow@tfprof@tensorflow@@IEAA_NAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEAV?$unique_ptr@VTFProfTensor@tfprof@tensorflow@@U?$default_delete@VTFProfTensor@tfprof@tensorflow@@@std@@@5@@Z)
unicode_script_op.lo.lib(unicode_script_op.obj) : warning LNK4217: locally defined symbol ??0ErrorCode@icu_62@@QEAA@XZ (public: __cdecl icu_62::ErrorCode::ErrorCode(void)) imported in function "public: virtual void __cdecl tensorflow::UnicodeScriptOp::Compute(class tensorflow::OpKernelContext *)" (?Compute@UnicodeScriptOp@tensorflow@@UEAAXPEAVOpKernelContext@2@@Z)
unicode_script_op.lo.lib(unicode_script_op.obj) : warning LNK4217: locally defined symbol ??1ErrorCode@icu_62@@UEAA@XZ (public: virtual __cdecl icu_62::ErrorCode::~ErrorCode(void)) imported in function "public: virtual void __cdecl tensorflow::UnicodeScriptOp::Compute(class tensorflow::OpKernelContext *)" (?Compute@UnicodeScriptOp@tensorflow@@UEAAXPEAVOpKernelContext@2@@Z)
unicode_script_op.lo.lib(unicode_script_op.obj) : warning LNK4217: locally defined symbol ??BErrorCode@icu_62@@QEAAPEAW4UErrorCode@@XZ (public: __cdecl icu_62::ErrorCode::operator enum UErrorCode *(void)) imported in function "public: virtual void __cdecl tensorflow::UnicodeScriptOp::Compute(class tensorflow::OpKernelContext *)" (?Compute@UnicodeScriptOp@tensorflow@@UEAAXPEAVOpKernelContext@2@@Z)
unicode_script_op.lo.lib(unicode_script_op.obj) : warning LNK4217: locally defined symbol ?isSuccess@ErrorCode@icu_62@@QEBACXZ (public: signed char __cdecl icu_62::ErrorCode::isSuccess(void)const ) imported in function "public: virtual void __cdecl tensorflow::UnicodeScriptOp::Compute(class tensorflow::OpKernelContext *)" (?Compute@UnicodeScriptOp@tensorflow@@UEAAXPEAVOpKernelContext@2@@Z)
unicode_script_op.lo.lib(unicode_script_op.obj) : warning LNK4217: locally defined symbol ?reset@ErrorCode@icu_62@@QEAA?AW4UErrorCode@@XZ (public: enum UErrorCode __cdecl icu_62::ErrorCode::reset(void)) imported in function "public: virtual void __cdecl tensorflow::UnicodeScriptOp::Compute(class tensorflow::OpKernelContext *)" (?Compute@UnicodeScriptOp@tensorflow@@UEAAXPEAVOpKernelContext@2@@Z)
icuuc.lib(udata.obj) : warning LNK4049: locally defined symbol icudt62_dat imported
arithmetic_optimizer.lib(arithmetic_optimizer.obj) : warning LNK4049: locally defined symbol ?DEVICE_GPU@tensorflow@@3QEBDEB (char const * const tensorflow::DEVICE_GPU) imported
layout_optimizer.lib(layout_optimizer.obj) : warning LNK4049: locally defined symbol ?DEVICE_GPU@tensorflow@@3QEBDEB (char const * const tensorflow::DEVICE_GPU) imported
pin_to_host_optimizer.lib(pin_to_host_optimizer.obj) : warning LNK4049: locally defined symbol ?DEVICE_GPU@tensorflow@@3QEBDEB (char const * const tensorflow::DEVICE_GPU) imported
LINK : fatal error LNK1201: error writing to program database 'C:\users\dl\_bazel_dl\hd37h63o\execroot\org_tensorflow\bazel-out\x64_windows-dbg\bin\tensorflow\libtensorflow_cc.pdb'; check for insufficient disk space, invalid path, or insufficient privilege

**Comment by ravikyram** [comment]
Just to verify did you get chance to follow instructions from TensorFlow [website](https://www.tensorflow.org/install/source_windows) .Please, let us know. 
Also, Provide the exact sequence of commands / steps that you executed before running into the problem.Thanks!

**Comment by ravikyram** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Comment by sakshigoynar17** [comment]
Hi, I also ran into the same issue. I am trying to build Tensorflow sources in optimised mode, with  debug information, so that I can get some debug information in the form of pdb files. 
Information:
System : Windows 10
Tensorflow : 1.13.1
Bazel : 0.25.1
Python : 3.6.8
Microsoft Visual Studio Build Tools 2019(Not using 2017 or 2015 Build tools)
CUDA/GPU/ROCm : no
Override Eigen strong inline : Yes
Arch: AVX2

Commands:
1. python ./configure.py
2. bazel build --define=tensorflow_mkldnn_contraction_kernel=0 --local_ram_resources=2048 -c opt --copt=/Z7 --copt=/FS  --linkopt=/DEBUG --strip=never --config=opt //tensorflow/tools/pip_package:build_pip_package

Error:
LINK : fatal error LNK1201: error writing to program database 'C:\users\tensorflow\_bazel_tensorflow\a7oebymx\execroot\org_tensorflow\bazel-out\x64_windows-opt\bin\tensorflow\python\_pywrap_tensorflow_internal.pdb'; check for insufficient disk space, invalid path, or insufficient privilege
Target //tensorflow/tools/pip_package:build_pip_package failed to build
INFO: Elapsed time: 3959.292s, Critical Path: 1017.43s
INFO: 4150 processes: 4150 local.
FAILED: Build did NOT complete successfully

More info:
The size of the pdb: C:\users\tensorflow\_bazel_tensorflow\a7oebymx\execroot\org_tensorflow\bazel-out\x64_windows-opt\bin\tensorflow\python\_pywrap_tensorflow_internal.pdb was just 4GB and there was enough disk space available. 
CAn somebody help me give a better insight of the issue?

**Comment by kimivital** [comment]
how to fix it?

**Comment by paleozogt** [comment]
This is happening because the .pdb file is hitting 4.0 GB, which seems to be some kind of hard max on pdb files.  The workaround is not to use pdb's at all.  Compile with `--copt /Z7` and `--linkopt /DEBUG:FASTLINK`.

`/Z7` puts the debugging information into the obj files themselves, while `/DEBUG:FASTLINK` creates an "index" pdb into those objs.

**Comment by TonyRietwyk** [comment]
Just in case anyone else finds this article - LINK1201 can also occur if the output pdb file is in use.  I had a project open in Visual Studio 2019 that used zlibd.dll and zlibd.pdb.  At the same time I was trying to run vcpkg to recreate those files and got this error.  It was resolved by closing all instances of Visual Studio (and its zombie debugging consoles), then running vcpkg.  The zlibd.pdb file was only 1MB in size.
