### ISSUE TITLE
Licencing of TensorFlow conda distribution in miniconda docker image

### ISSUE THREAD

**Issue by rgupta2508** [tensorflow/tensorflow#31614]
I am using conda distribution of Tensorflow inside miniconda3 docker image.
miniconda3 docker image i have downloaded from below link:- 

https://hub.docker.com/r/continuumio/miniconda3

Installation of tensorflow & other dependencies in docker image:

    FROM continuumio/miniconda3
    RUN apt-get update && \
    apt-get install -y openjdk-8-jre-headless && \
    apt-get install -y ant && \
	apt-get install -y python3-tk && \
    apt-get clean;
    conda install --yes tensorflow==1.12

I created another docker image on the top of miniconda3 docker image.

Scan this final image in whitesource tool for getting information of GPL and AGPL licence. 

I am getting lot's of GPL and AGPL inside tensorflow package folder.

Below is the example of one package:-

    Slic3r-1.41.0-alpha3.1    GPL 2.0AGPL 3.0GPL    opt\conda\lib\python3.6\site-packages\tensorflow\include\Eigen\src\Core\Assign_MKL.h

Now i want to use this in our Enterprise application. is there any other way to use this in application or this the issue of tool to give GPL inside package?

**Comment by oanush** [comment]
@rgupta2508 ,
Can you please refer this [link](https://www.tensorflow.org/install/docker).Thanks!

**Comment by oanush** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
