### ISSUE TITLE
[issue]Pb convert to tflite :how to calculate output min max of concatenation layer

### ISSUE THREAD

**Issue by MasterGG** [tensorflow/tensorflow#31611]
I notice that tensorflow source code in quantized_concat_op.cc use the function of **CalculateInputAndOutputRange()** to caculate the minmax value of input and output feature maps, which just let the output min value be the minimum of the  input_mins[i], and max value be the maximum of the  input_maxes[i].
But when i convert pb file to tflite, the minmax value of output feature map of  concat layer not be the value  what it should be.

this is my convet command:
toco  \
--graph_def_file=rpn_190516.pb \
--output_file=rpn_190516_tt.tflite \
--input_shapes=1,2048,2048,3 \
--input_arrays='input_rpn' \
--output_arrays='concat' \
--inference_type=QUANTIZED_UINT8 \
--mean_values=128 \
--std_dev_values=128 \
--change_concat_input_ranges=false \
--allow_custom_ops

and the reslut screenshot:
![image](https://user-images.githubusercontent.com/13192737/63005315-d7770800-beae-11e9-9372-edd151d909dc.png)

i would appreciate it , if someone can explain the result.

**Comment by Zdahap** [comment]
Has the problem been solved? I also encountered the same problem.

**Comment by freedomtan** [comment]
@MasterGG you specified `--change_concat_input_ranges=false`

**Comment by MasterGG** [comment]
@freedomtan  thank you for reply! Do you mean that if i want to use toco to convet pb files , i should always set the flag  --change_concat_input_ranges=true?
Also i have found in tensorflow/lite/toco/graph_transformations/quantize.cc ,which has code as below :
![image](https://user-images.githubusercontent.com/13192737/63087573-1b3c4100-bf85-11e9-891e-62fc79f88128.png)
Does it means that if  the flag is true ,concatenation's output minmax just equal to the minmax of the first input arrays?

**Comment by freedomtan** [comment]
yes, but as far as I can remember the the parameters of input was changed before the code snippet you showed.

**Comment by MasterGG** [comment]
@freedomtan  Hi, i have tried some trials, if i set --change_concat_input_ranges=true, i got some tflite whoese minmax of all inputs  and outputs of  concat layers change to the same value; but some other tflite  just make the minmax of outputs be the same as the first input array,and didn't change the minmax of other inputs arrays.
So i am confused about the rules how to set the toco convert flags to get valid minmax values of concatenation layers. Can you give me some guidance about the Complete  rules?

**Comment by kumariko** [comment]
@MasterGG Could you please let us know if this issue still persists ? If it is resolved then please feel free to move this issue to close status ? refer [link](https://stackoverflow.com/questions/54830869/understanding-tf-contrib-lite-tfliteconverter-quantization-parameters) . Thanks!
