### ISSUE TITLE
fft2d on CPUs

### ISSUE THREAD

**Issue by danielzt12** [tensorflow/tensorflow#31628]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Red Hat 7.6
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.0.0-beta1
- Python version: 3.6
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
It seems like there is a performance issue when running fft2d on data with dimension > 2 (CPU only).
When running fft2d on an array of (40,40,256,256), the function correctly computes fft2d on the inner most 2 dimensions as expected. But it only uses 1 CPU core which results in poor performance.

**Describe the expected behavior**
Because it is equivalent to simultaneously computing 40x40 fft2d, I would expect parallel computation across multiple CPU cores to boost the performance.

**Code to reproduce the issue**
a=tf.cast(tf.Variable(tf.random.uniform([40,40,256,256],dtype=tf.float32)), dtype=tf.complex64)
b=tf.signal.fft2d(a)

Provide a reproducible test case that is the bare minimum necessary to generate the problem.

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by Leslie-Fang** [comment]
Please refer to this snippet of code
https://github.com/tensorflow/tensorflow/blob/dcdca11bcbab4b2474e7bf4d21d1806e6c2790a3/tensorflow/core/kernels/fft_ops.cc#L132-L141

There is no for loop. And tensorflow seems is calling "Eigen fft" to calculate the result.

**Comment by Leslie-Fang** [comment]
@danielzt12
You could do the parallel computation by appropriate use the tensorflow APIs.
Please refer to this snippet of code:
```
import tensorflow as tf
a=tf.cast(tf.Variable(tf.random.uniform([40,40,256,256],dtype=tf.float32)), dtype=tf.complex64)
res = None
for i in range(40):
    temp_out = tf.signal.fft2d(tf.slice(a,[i,0,0,0],[1,40,256,256]))
    if res is None:
        res = temp_out
    else:
        tf.concat([res,temp_out],0)
config = tf.ConfigProto(intra_op_parallelism_threads=4)
with tf.Session(config=config) as sess:
    sess.run(tf.global_variables_initializer())
    sess.run(res)
```

**Comment by danielzt12** [comment]
> @danielzt12
> You could do the parallel computation by appropriate use of the tensorflow APIs.
> Please refer to this snippet of code:
> 
> ```
> import tensorflow as tf
> a=tf.cast(tf.Variable(tf.random.uniform([40,40,256,256],dtype=tf.float32)), dtype=tf.complex64)
> res = None
> for i in range(40):
>     temp_out = tf.signal.fft2d(tf.slice(a,[i,0,0,0],[1,40,256,256]))
>     if res is None:
>         res = temp_out
>     else:
>         tf.concat([res,temp_out],0)
> config = tf.ConfigProto(intra_op_parallelism_threads=4)
> with tf.Session(config=config) as sess:
>     sess.run(tf.global_variables_initializer())
>     sess.run(res)
> ```
> 
> @Leslie-Fang

Hi Leslie, 
Thanks for helping out. I tried your code but because I am using tf 2.0 the for loop is executed in eager mode, it was only slightly faster (not even 10% I think).

Do I need to use @tf.function for this? The whole tf thing is still all very new to me, do you have a solution for tf 2.0?  Thanks

**Comment by ravikyram** [comment]
Can we close this issue since the query is been resolved. Thanks!
