### ISSUE TITLE
Support a dictionary of tensors as a CompositeTensor

### ISSUE THREAD

**Issue by novog** [tensorflow/tensorflow#31621]
- TensorFlow version (you are using): 2.0.0b1
- Are you willing to contribute it (Yes/No): No

**Describe the feature and the current behavior/state.**
The CompositeTensor base class offers a unified way of handling various types of tensors that are themselves composed of tensors. Currently, dictionaries of tensors are not supported; it would be useful if they were.

**Will this change the current api? How?**
Yes, by adding to the types of structures that can be treated as a CompositeTensor.

**Who will benefit with this feature?**
Dictionaries are one of the more convenient ways to manage collections of heterogeneous features. In issue #27679 (Passing a dictionary of tensors to py_function), it was stated that in that case, creating a subclass of CompositeTensor that can represent a dictionary would be one path to ultimately supporting dictionaries of tensors in py_function.

**Comment by edloper** [comment]
Most APIs that support composite tensors also support nested structures (as defined by [tf.nest](https://www.tensorflow.org/api_docs/python/tf/nest).  In particular, the tf.nest functions include an "expand_composites" argument that tells tf.nest that it should treat composite tensors as nested structures.

Therefore, we don't need a CompositeTensor for dictionaries -- we can just use dictionaries as is.  But what we do ned is to extend py_function to use tf.nest to do appropriate flattening and repacking of tensors at the input & output boundaries.  (Using "expand_composites=True" will ensure that this supports both "normal" nested structures and composite tensors.)

Closing this issue, but adding a similar comment to issue #27679.
