### ISSUE TITLE
GPU docker images and pip package have mismatched CuDNN versions

### ISSUE THREAD

**Issue by seanpmorgan** [tensorflow/tensorflow#31622]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 16
- TensorFlow installed from (source or binary): Docker image
- TensorFlow version: Nightly
- CUDA/cuDNN version: Docker is cudnn 7.5 or 7.4 & pip package is cudnn 7.6

**Describe the problem**
The available GPU docker images (tensorflow/tensorflow:nightly-gpu ; tensorflow/tensorflow:gpu & the others) will fail to intialize cuDNN since TF-nightly is compiled with a higher minor version

**Provide the exact sequence of commands / steps that you executed before running into the problem**
docker run --rm -it --runtime=nvidia tensorflow/tensorflow:nightly-gpu-py3 /bin/bash

```
import tensorflow as tf
import numpy as np

x = tf.placeholder(tf.float32, shape=(2,4,4,3))
layer = tf.keras.layers.Conv2D(5, (2,2), input_shape=(4,4,3))
out = layer(x)

data = np.random.random((2, 4, 4, 3))
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    print(sess.run(out, feed_dict={x: data}))

```

Fails with:
```
Loaded runtime CuDNN library: 7.4.1 but source was compiled with: 7.6.0.
Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
```

**Any other info / logs**
Related issue: https://github.com/tensorflow/addons/issues/418

cc @yifeif @av8ramit . As discussed this applies to custom-op repos as well.

**Comment by tfboyd** [comment]
On it.  Sorry I missed this, the change happened in a bit of a weird way.  There is still not excuse to be honest.

**Comment by tfboyd** [comment]
I checked the this docker `tensorflow/tensorflow:nightly-gpu-py3` and we look good for tf-nightly:  

libcudnn7/unknown,now 7.6.2.24-1+cuda10.0 amd64 [installed,upgradable to: 7.6.2.24-1+cuda10.1]
libnvinfer5/unknown,now 5.1.5-1+cuda10.0 amd64 [installed,upgradable to: 5.1.5-1+cuda10.1
