### ISSUE TITLE
the results is not reproducible

### ISSUE THREAD

**Issue by fayeshine** [tensorflow/tensorflow#3163]
the results is not reproducible due to some random factors, is there a way to reproduce the exactly same result in NN training

**Comment by aselle** [comment]
Please re-ask this question on stackoverflow. Issues are primarily for bugs.

**Comment by MartinThoma** [comment]
For people who come here:

```
import numpy as np
np.random.seed(0)  # make sure results are reproducible
import tensorflow as tf
tf.set_random_seed(0)  # make sure results are reproducible
```

The numpy part might not be necessary in your case.
