### ISSUE TITLE
There is a patch in the Eigen dir. Any plan to update it to a new commit?

### ISSUE THREAD

**Issue by JiayiFu** [tensorflow/tensorflow#31639]
I'm compiling a project with TensorFlow and Eigen and I need to use the same version Eigen source code as TensorFlow. But I found there is a git patch in the TensorFlow's Eigen dir.  I don't know which commit of Eigen I should use Bazel to download. Any plan to update the Eigen to a new commit?
Thanks!

**Comment by JiayiFu** [comment]
Does it seem like the official Eigen commits don't have already merged this patch?

**Comment by ezhulenev** [comment]
We track Eigen head pretty close, current revision is `8071cda5714d` https://github.com/tensorflow/tensorflow/blob/master/tensorflow/workspace.bzl#L178.

Are you talking about https://github.com/tensorflow/tensorflow/blob/master/third_party/eigen3/gpu_packet_math.patch? That one should probably go into Eigen main repo, if you can prepare a PR to Eigen bitbucket, you can assign it to http://bitbucket.org/rmlarsen and TF will pick it up this or next week.

**Comment by ezhulenev** [comment]
Based https://bitbucket.org/eigen/eigen/commits/ on we are just 1 commit away from head

**Comment by JiayiFu** [comment]
Thanks for your reply!
