### ISSUE TITLE
Custom OP using eigen matrix

### ISSUE THREAD

**Issue by SeanCho1996** [tensorflow/tensorflow#31634]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Win 10 pro
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): source
- TensorFlow version: 1.13.1
- Python version: 3.6.7
- Installed using virtualenv? pip? conda?: from source
- Bazel version (if compiling from source): 0.21.0
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: cuda 10.0 cudnn 7.6.2
- GPU model and memory:ROG strix geforce gtx 1080Ti, 11G

**Describe the problem**
I'm trying to develop a Tensorflow custom op using cuda. And inside the op, I need to use Eigen to run some matrix operations, but when I try to calculate the inverse of a size 8*8 matrix, I've encountered several problems.

This function is written in CUDA kernel.
In cuda kernel function file (.cu.cc), I have included
```c++
#include <Eigen\Dense>
#include <Eigen/LU>
#include "third_party/eigen3/unsupported/Eigen/CXX11/Tensor"
#include "tensorflow/core/framework/op.h"
#include "tensorflow/core/framework/op_kernel.h"
#include <stdio.h>
#include <math.h>
```
And in the kernel function, I just tried a simple test:
```c++
typedef Eigen::Matrix<float, 8, 8> Matrix8f;

__global__ void CsmToRcmKernel(Eigen::Map<const Eigen::MatrixXcf> csm_map, Eigen::Map<const Eigen::VectorXf> reg_vec,
    Eigen::Map<const MatrixXi16> offset8,       // (12160, 8, 3)
    Eigen::Map<const MatrixXi16> offset3,       // (9728, 3, 3)
    Eigen::Map<const MatrixXi16> offset4,       // (12160, 4, 3)
    Eigen::Map<const MatrixXi16> offset6,       // (9728, 6, 3)
    Eigen::Map<Eigen::MatrixXcf> rcm_map) {

    Matrix8f A = MatrixXf::Identity(8, 8);
    A(0, 0) = 2;

    // inv_A = inv(A);
    Matrix8f inv_A = A.inverse();
}
```
(You can ignore the input parameters, they aren't used in this test program.)

And when I try to build this op with bazel, I got following errors:
```
c:\users\administrator\_bazel_zhaozixiao\sr6amwum\execroot\org_tensorflow\external\eigen_archive\eigen\src/Core/SolveTriangular.h(185): 
error: function "Eigen::Block<XprType, BlockRows, BlockCols, InnerPanel>::operator=(const Eigen::Block<Eigen::Block<Eigen::Map<Eigen::Matrix<float, -1, -1, 0, -1, -1>, 0, Eigen::Stride<0, 0>>, -1, -1, false>, -1, -1, false> &) [with XprType=Eigen::Block<Eigen::Map<Eigen::Matrix<float, -1, -1, 0, -1, -1>, 0,Eigen::Stride<0, 0>>, -1, -1, false>, BlockRows=-1, BlockCols=-1, InnerPanel=false]" (declared implicitly) cannot be referenced -- it is a deleted function

c:\users\administrator\_bazel_zhaozixiao\sr6amwum\execroot\org_tensorflow\external\eigen_archive\eigen\src/Core/GenericPacketMath.h(368): 
error: asm operand type size(8) does not match type/size implied by constraint 'r'
```
And if I try to calculate the inverse of a size 4 * 4(or below) matrix, there isn't any problem. 
In fact I found that tensorflow itself can realise big size matrix operation, matrix inverse for example, but it seems like they don't use eigen structure. So I'd like to know if cuda kernel supports big size(bigger than 4 * 4) matrix operations based on eigen? Thank you!

**Comment by rmlarsen** [comment]
@SeanCho1996 could you please file a bug for the Eigen maintainers with a pure Eigen + cuda repro?

http://eigen.tuxfamily.org/bz/
