### ISSUE TITLE
ImportError: DLL load failed: The specified module could not be found.

### ISSUE THREAD

**Issue by tcratius** [tensorflow/tensorflow#31643]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Microsoft Windows 10 Pro
10.0.18362 Build 18362

- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): binary
- TensorFlow version: 1.14.0
- Python version: 3.6.6 virtual interpreter
- Installed using virtualenv? pip? conda?: pip
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: 9.0
- GPU model and memory: NVIDIA GeForce GTX 1050 Ti

**Describe the problem**

**Provide the exact sequence of commands / steps that you executed before running into the problem**
- Note: The usage of -> short for linked to.
- Downloaded and installed CUDA/cuDNN 9.0
- Downloaded and installed 10.0 (needed 10 for cudart64_100.dll) as per error message PyCharm 2019.1.3 (Professional Edition) 'cudart64_100.dll was not found' along those lines.
- Downloaded a copy of cudnn64_7.dll from the cuDNN Library and pasted into ../v9.0/bin folder
- Update windows environment paths as per recommendation https://www.tensorflow.org/install/gpu and as per issue/10033
- Found the issue where a user was recommended to run Scratch.py file via PyCharm 
[stratch-py.txt](https://github.com/tensorflow/tensorflow/files/3504373/stratch-py.txt)
- Installed protobuf 3.6.0 as per issues/28389 -> issues/28389 -> issues/25072
- Unsure if I have non-avx cpu and require non-avx built wheel as per issues/28389 -> issues/28389 -> issues/25072
    - Processor	Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz, 2801 Mhz, 4 Core(s), 8 LogPro's
- Removed CUDA/cuDNN version 10.0 (see log file removed-cuda-10-0) as per issues/22872
    - Copied cudart64_100.dll to ../v9.0/bin folder
    - Re-updated environment paths:
        - C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.0\bin
        - C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.0\extras\CUPTI\libx64
        - C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.0\include
        - C:\tools\cuda\bin
- Upgraded from 3.6.6 to 3.6.8 as per issues/29575
- Removed tensorflow-gpu and tensorflow-gpu-graphics from pycharm project interpreter settings. 
    - [output-scratch-py-minus-gpu.txt](https://github.com/tensorflow/tensorflow/files/3505544/output-scratch-py-minus-gpu.txt)
    - pip install tensorflow==1.14.0
- Updated the project interpreter to 3.6.8 non virtual interpret via pycharm
    - See output post-updated-pycharm-interp-3.6.8
    - Also current-project-interp-pkgs

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.
[pycharm-project-interpreter-pkgs.txt](https://github.com/tensorflow/tensorflow/files/3505376/pycharm-project-interpreter-pkgs.txt)
[cli-python-import-tensorflow.txt](https://github.com/tensorflow/tensorflow/files/3504377/cli-python-import-tensorflow.txt)
[tensorflow-log.txt](https://github.com/tensorflow/tensorflow/files/3504340/tensorflow-log.txt)
[pydev-debugger.txt](https://github.com/tensorflow/tensorflow/files/3504349/pydev-debugger.txt)
[removed-cuda-10-0.txt](https://github.com/tensorflow/tensorflow/files/3505369/removed-cuda-10-0.txt)
[stack-trace.pdf](https://github.com/tensorflow/tensorflow/files/3505474/stack-trace.pdf)
[stack-trace-with-debug.pdf](https://github.com/tensorflow/tensorflow/files/3505483/stack-trace-with-debug.pdf)
[post-updated-pycharm-interp-3.6.8.pdf](https://github.com/tensorflow/tensorflow/files/3505572/post-updated-pycharm-interp-3.6.8.pdf)
[current-project-interp-pkgs.txt](https://github.com/tensorflow/tensorflow/files/3505581/current-project-interp-pkgs.txt)

**Comment by ymodak** [comment]
@tcratius In reference to GitHub issue https://github.com/tensorflow/tensorflow/issues/22872 user was installing TF 1.11 thus asked to switch to cuda 9 and not cuda 10.0
However in your case you should install cuda 10.0 and not cuda 9.0.
TF 1.13 and above support cuda 10.0
See https://www.tensorflow.org/install/gpu#software_requirements
Please update your environment paths to cuda 10

**Comment by tcratius** [comment]
Sorry about that mate, tried to be thorough, but totally missed that.  I have installed cuda_10.0.130_win10_network.exe which, produces;

The installed version of TensorFlow includes GPU support.
- Python version is 3.6.
- TensorFlow is installed at: C:\Users\Two_Oriel\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow
- msvcp140.dll Found at C:\Windows\System32\msvcp140.dll
- Could not load 'cudart64_90.dll'. Download and install CUDA 9.0 from
  this URL: https://developer.nvidia.com/cuda-toolkit
- nvcuda.dll found at C:\Windows\System32\nvcuda.dll
- cuDNN Found at C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.0\bin\cudnn64_7.dll
Process finished with exit code -1

**Comment by tcratius** [comment]
Looks like that fixed it, only warnings now and can handle that. Now just have to remember what it was that I was trying to learn. Such is life.
[app-py.txt](https://github.com/tensorflow/tensorflow/files/3508771/app-py.txt)
[app-py-log.txt](https://github.com/tensorflow/tensorflow/files/3508787/app-py-log.txt)

**Comment by ymodak** [comment]
Are you satisfied with the resolution of your issue?
[Yes](https://goo.gl/forms/Oe0tEvODFRoI2gJF3)
[No](https://goo.gl/forms/fUjzOfrtkFbrOT8d2)
