### ISSUE TITLE
tf.keras.backend.function ignores input shapes?

### ISSUE THREAD

**Issue by tylerlekang** [tensorflow/tensorflow#31650]
**System information**
- Have I written custom code: Yes
- OS Platform and Distribution: Windows 10
- TensorFlow installed from (source or binary): conda install/update tensorflow
- TensorFlow version (use command below): 1.14.0
- Python version: 3.7.3
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

**Describe the current behavior**
tf.keras.backend.function seems to ignore explicitly defined input shapes, almost as if the model were defined using None shapes (dynamic reshape).

**Describe the expected behavior**
I expected an error to be thrown, as the wrong input shape was fed to the model. Instead, it seems as if the model was run using a dynamic reshape.

**Code to reproduce the issue**
```
import numpy as np
import tensorflow.keras as K
import tensorflow.keras.backend as Kb

sub_in = K.layers.Input(shape = (1,5,1))
x = K.layers.Conv2D(1, (1,1))(sub_in)
x = K.layers.Flatten()(x)
sub = K.models.Model(inputs=sub_in, outputs=x)

main_in = K.layers.Input(shape = (1,10,1))
main_in1 = K.layers.Lambda(lambda x: x[:,:,:5,:])(main_in)
main_in2 = K.layers.Lambda(lambda x: x[:,:,8:,:])(main_in)
x1 = sub(main_in1)
x2 = sub(main_in2)
x = K.layers.Concatenate()([x1,x2])
main = K.models.Model(inputs=main_in, outputs=x)

arr = np.arange(30).reshape((3,1,10,1))

pred = main.predict(arr)
print(pred.shape)

subOutFunc = Kb.function(sub.input, sub.output)
subOut = subOutFunc(arr)
print(subOut.shape)
```
Running this, you should see output shapes of (3,7) and (3,10), which in my opinion should not be possible. The sub model should only accept inputs of shape (?,1,5,1), yet in the two above examples inputs of shapes (?,1,2,1) and (?,1,10,1) are fed to it, and it works.

The first example (using the .predict method) gives it the (?,1,2,1) input, via the second Lambda split of the main input. No error. The second example calls backend.function directly on the sub model with a (?,1,10,1). Also no error.

Maybe this was/is the desired behavior of backend.function ? It is not what I expected. Hence raising up in case this is a bug. Thank you!

**Comment by oanush** [comment]
I was able to reproduce the issue for given code TF version-1.14,kindly find the [gist](https://colab.sandbox.google.com/drive/1lPtZHkiU5Y7absQsIgbsPNLF2MRkeDj-#scrollTo=WQ-ndvvGIM3m) of colab.

**Comment by yhliang2018** [comment]
The `Conv2D` layer will[ re-create the conv op](https://github.com/tensorflow/tensorflow/blob/8502c9e5c8efa59b326e5743e64b283730145f5c/tensorflow/python/keras/layers/convolutional.py#L194) if the actual input has different shape other than the specified 'Input' shape. So the shape from the actual input is used.

**Comment by EliaSchiavon** [comment]
Ok, but why? Wouldn't be useful to print at least a warning saying that there is a mismatch between the specified input at the actual input?

**Comment by chunduriv** [comment]
@EliaSchiavon, 

Can you please create a new issue on `keras-team/keras repo`.
Development of keras moved to separate repository https://github.com/keras-team/keras/issues. 
To know more see;
https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999
Thank you!
