### ISSUE TITLE
TOCO fails to handle Dilated Convolution properly with use_bias=False

### ISSUE THREAD

**Issue by olegarch** [tensorflow/tensorflow#31660]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 16.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 1.14
- Python version: 3.7
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

**Describe the current behavior**
conv1 = tf.layers.conv2d(x, 32, 3, dilation_rate=(2,2), activation=tf.nn.relu, use_bias=False)
TF will wrap this convolution into Space2Batch and Batch2Space pair. When converting to float tflite toco/tflite_convert fails to fold them back into single op. I think that happens because it doesn't match any of the patterns that identify_dilated_conv.cc analyzes.

If use_bias=True then everything works as expected.

**Describe the expected behavior**

**Code to reproduce the issue**
N/A

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by jiarenyf** [comment]
https://github.com/tensorflow/tensorflow/issues/31359

**Comment by luluka2** [comment]
If use_bias=True , When converting to float tflite toco/tflite_convert can fold them back into single op.Is that ture?why i can't fuse them to a op.thanks

**Comment by haozha111** [comment]
i've submitted a fix for dilated conv in the new mlir converter.
https://github.com/tensorflow/tensorflow/commit/f54bb6f5578b931d79884302768996ba1073f685

could you please download latest tf-nightly and then try convert your model with the new converter?

(please set converter.experimental_new_converter = True).
thanks.

**Comment by haozha111** [comment]
feel free to reopen if the issue still persists. thanks!
