### ISSUE TITLE
Models with tf.keras.layers.BatchNormalisation layers give errors when frozen, or are frozen incorrectly and cannot be loaded

### ISSUE THREAD

**Issue by geometrikal** [tensorflow/tensorflow#31668]
This issue continues on from #31331 with a more wide ranging scope

**System information**
- Have I written custom code: Yes
- OS Platform and Distribution: Windows 1903
- TensorFlow installed from: pip
- TensorFlow version: 1.13.1 / 1.14.0 / tf-nightly
- Python version: 3.7.3
- GPU model and memory: RTX 2080 Ti 

**Problem**

Freezing a model with tf.keras.layers.BatchNormalization layers either gives an error, or does not freeze correctly and gives an error when loading, depending on the tensorflow version.

**Method**

- Freezing: Save a model with tf.keras.layers.BatchNormalization layers using `tf.saved_model.simple_save` and then freeze it using `tensorflow.python.tools.freeze_graph.freeze_graph`.
- Loading: Load the frozen model using tf.import_graph_def()

**Results**

*1.13.1*
- Freezing: no error
- Loading: `ValueError: Input 0 of node batch_normalization/cond/ReadVariableOp/Switch was passed float from batch_normalization/gamma:0 incompatible with expected resource`

*1.14.0*
- Freezing: `ValueError: Tensor name 'batch_normalization/cond/ReadVariableOp/Switch:1' is invalid.`
- Loading: n/a

*tf-nightly  1.15.0-dev20190815*
- Freezing: no error
- Loading: `Node 'batch_normalization/cond/ReadVariableOp/Switch_3' has an _output_shapes attribute inconsistent with the GraphDef for output #0: Shapes must be equal rank, but are 1 and 0`

**Code to reproduce**

Colab gist is here: https://colab.research.google.com/gist/geometrikal/da64b13d8a579bc46c005e981d9bc051/tf_31331_freezing_savedmodel.ipynb

```
import tensorflow as tf
import tensorflow.keras.backend as K
import os
import datetime
import shutil
from tensorflow.python.tools import freeze_graph
from tensorflow.keras.layers import Dense, Flatten, Conv2D, Input, Activation, BatchNormalization, Lambda
from tensorflow.keras.models import Model
from tensorflow.python.platform import gfile

# Clear the session
K.clear_session()

# TF version
print("TF version is " + tf.__version__)

# Create model
print('# Creating model')
def create_model():
    inputs = Input(shape=(128, 128, 1))
    x = Conv2D(4, (3, 3))(inputs)
    x = BatchNormalization()(x)
    # x = Lambda((lambda x: tf.layers.batch_normalization(x)))(x)
    x = Activation('relu')(x)
    x = Flatten()(x)
    x = Dense(5, activation='softmax')(x)
    model = Model(inputs, x, name='test')
    model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])
    return model

model = create_model()

# Remove old frozen graph directory
if os.path.exists('/content/frozen/'):
  shutil.rmtree('/content/frozen/')

# Create saved model
print('# Saving model')
save_dir = "/content/frozen/"
tf.saved_model.simple_save(K.get_session(),
                           save_dir,
                           inputs={"input": model.inputs[0]},
                           outputs={"output": model.outputs[0]})

# Freeze graph from saved model checkpoint
print('# Freezing graph')
freeze_graph.freeze_graph(None,
                          None,
                          None,
                          None,
                          model.outputs[0].op.name,
                          None,
                          None,
                          os.path.join(save_dir, "frozen_model.pb"),
                          False,
                          "",
                          input_saved_model_dir=save_dir)

# Try to load frozen graph
print('# Loading graph')
source = "/content/frozen/frozen_model.pb"
session = K.get_session()
with gfile.Open(source, 'rb') as f:
    graph_def = tf.GraphDef()
    graph_def.ParseFromString(f.read())
    session.graph.as_default()
    tf.import_graph_def(graph_def, name='')
```

**Workaround**

Workaround is to save the weights, clear the session, `tf.keras.backend.set_learning_phase(0)`, recreate the model, restore the weights, and then freeze. https://github.com/tensorflow/tensorflow/issues/31331#issuecomment-518655879

**Comment by gargn** [comment]
This should work on the latest nightly. Please reopen if you still have issues with running the script provided above.

**Comment by TechnikEmpire** [comment]
This is happening in TF 2.x when using hub to transfer learn. I can't clear these layers when freezing either so I can't take the model outside of TF to say Open CV DNN.
