### ISSUE TITLE
Tensorflow Lite Allow Variable length sequences

### ISSUE THREAD

**Issue by Jbiloki** [tensorflow/tensorflow#31661]
**System information**
- TensorFlow version (you are using): 1.14.9
- Are you willing to contribute it (Yes/No): Yes

**Describe the feature and the current behavior/state.** 

Currently, porting a tensorflow model to tflite does not allow for variable length inputs and instead throws

```
ValueError: None is only supported in the 1st dimension. Tensor 'input_2' has invalid shape '[None, None, 1]'.
```

Many NLP applications require the second axis of the shape to allow for variable length input sequences.

**Will this change the current api? How?** N/A

**Who will benefit with this feature?** NLP/CV applications of tflite

**Comment by ArtemisZGL** [comment]
is it working in any tf version now?

**Comment by gds101054108** [comment]
is it working in any tf version now?

**Comment by siqim** [comment]
anyone?

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.
