### ISSUE TITLE
Building tflite-with-select-ops.aar library in tf v1.12

### ISSUE THREAD

**Issue by git-davi** [tensorflow/tensorflow#31664]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- TensorFlow installed from (source or binary): source
- TensorFlow version: 1.14, 1.13, 1.12
- Python version: 2.7, 3.6
- Bazel version (if compiling from source): 0.28, 0.16

**Describe the problem**
Before getting into the problem I need a little intro.
I'm trying to run a tflite model on android. The first little issue that I met was during `.pb` file conversion. One of my ops wasn't supported by tf lite builtins and so I have to export my model using the **SELECT_TF_OPS** tag as bescribed in the [official guide](https://www.tensorflow.org/lite/guide/ops_select#converting_the_model) .
No big deal. **The model was converted using tf v1.14**.
After the successful conversion I needed only to build (from source) my custom select-ops friendly library that should be imported in my project. So I configured the bazel WORKSPACE as explained in [this guide](https://www.tensorflow.org/lite/guide/android#build_tensorflow_lite_locally).
I've chosen ANDROID SDK 23 (also tried 29) and NDK 18.
Then I've built the library using the bazel (v0.28 i guess) build arguments described [here](https://www.tensorflow.org/lite/guide/ops_select#android_aar).
The build took a **long time**, I imported it into my project and I get this Error:
**This was the first real problem**
`java.lang.UnsatisfiedLinkError: No implementation found for long org.tensorflow.lite.NativeInterpreterWrapper.createErrorReporter(int) (tried Java_org_tensorflow_lite_NativeInterpreterWrapper_createErrorReporter and Java_org_tensorflow_lite_NativeInterpreterWrapper_createErrorReporter__I)`

No bad, I surfed the web and found [this fix](https://github.com/googlecodelabs/tensorflow-for-poets-2/issues/26). They say to downgrade tf back to 1.12.
Honestly I wasn't feeling really well on this, but I have to try.
Changed Gradle version to 4.1 and Plugin Version to 3.0.0.
_Before the fix I decided to try the previous aar build procedure on tf v1.13. But still this `java.lang.UnsatisfiedLinkError` appear._
Ok let's move on **tf v1.12**.
Now **Bazel is v0.16**. The WORKSPACE now was ANDROID SDK 23 and NDK 15.
**Here the second issue will come**, when building with select ops in tf 1.12 the bazel command [given by the official guide](https://www.tensorflow.org/lite/guide/ops_select#android_aar) is not working. Cause _//tensorflow/lite/java:tensorflow-lite-with-select-tf-ops_ cannot be resolved.
So I tried this, taking the idea from [here](https://www.tensorflow.org/lite/guide/ops_select#c):
`bazel build --cxxopt='--std=c++11' `
`-c opt`
`--config=android_arm` 
`--config=monolithic` 
`--jobs=1` 
`--define=with_select_tf_ops=true `
`//tensorflow/contrib/lite/java:tensorflow-lite`

The build was **really fast**. _Don't feel good about this._
Then, imported the model into android studio, run and again : 
`java.lang.UnsatisfiedLinkError: No implementation found for long org.tensorflow.lite.NativeInterpreterWrapper.createErrorReporter(int) (tried Java_org_tensorflow_lite_NativeInterpreterWrapper_createErrorReporter and Java_org_tensorflow_lite_NativeInterpreterWrapper_createErrorReporter__I)`

I really don't know what I am getting wrong.

What is this error and why does it keeps coming?

Is my bazel build command correct (for building my tflite select-ops friendly aar library in tf v1.12)? 

Should I use ANDROID NDK 17 as [described here](https://www.tensorflow.org/lite/guide/android#install_bazel_and_android_prerequisites)?

I can't find anything that could help me on the web.
Lastly : 
Should I convert the `.pb` model to `.tflite` in tf v1.12?

I will really appreciate any help.
Sorry for bad english I'm not native.

**Comment by jdduke** [comment]
Can you attach the logcat surrounding this error? And how you're using the locally built .aar in your build.gradle? What device are you using? And what version of Android are you running with? 

I should note, we're hoping to release a nightly build of this AAR in the near future, which should dramatically simplify development when using these ops. I would not recommend downgrading to 1.12 for this.

**Comment by git-davi** [comment]
Hi @jdduke and thanks for your reply.

I'm testing my app on AVD :
- Nexus 5 , Android 9.0 (API 28)
- Nexus 5, Android 7.1.1 (API 25)
They both get the same error.
Also tested on my phone Asus zenfone max pro m1 android 9.0. App crashed.

Here is my build.gradle (followed the offical tf lite guide):
`apply plugin: 'com.android.application'

android {
    compileSdkVersion 29
    buildToolsVersion "29.0.2"
    defaultConfig {
        applicationId "com.example.tflitetestsdkapi29"
        minSdkVersion 23
        targetSdkVersion 29
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    splits {
        abi {
            enable true
            reset()
            include 'x86', 'armeabi-v7a', 'x86_64'
            universalApk true
        }
    }
    aaptOptions {
        noCompress "tflite"
        noCompress "lite"
    }
}

allprojects {
    repositories {
        jcenter()
        flatDir {
            dirs 'libs'
        }
    }
}


dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation 'androidx.appcompat:appcompat:1.0.2'
    implementation 'androidx.constraintlayout:constraintlayout:1.1.3'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'androidx.test:runner:1.2.0'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.2.0'
    implementation name:'tensorflow-lite-with-select-tf-ops', ext:'aar'
    implementation files('libs\\commons-io-2.6.jar')
}
`

Now the logcat (verbose) generated from Nexus 5 API 25 :
`--------- beginning of crash
2019-08-17 19:58:17.279 6303-6303/com.example.tflitetestsdkapi29 E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.tflitetestsdkapi29, PID: 6303
    java.lang.UnsatisfiedLinkError: No implementation found for long org.tensorflow.lite.NativeInterpreterWrapper.createErrorReporter(int) (tried Java_org_tensorflow_lite_NativeInterpreterWrapper_createErrorReporter and Java_org_tensorflow_lite_NativeInterpreterWrapper_createErrorReporter__I)
        at org.tensorflow.lite.NativeInterpreterWrapper.createErrorReporter(Native Method)
        at org.tensorflow.lite.NativeInterpreterWrapper.<init>(NativeInterpreterWrapper.java:40)
        at org.tensorflow.lite.Interpreter.<init>(Interpreter.java:171)
        at org.tensorflow.lite.Interpreter.<init>(Interpreter.java:148)
        at com.example.tflitetestsdkapi29.TFLiteTester.<init>(TFLiteTester.java:66)
        at com.example.tflitetestsdkapi29.MainActivity$1.onClick(MainActivity.java:45)
        at android.view.View.performClick(View.java:5637)
        at android.view.View$PerformClick.run(View.java:22429)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6119)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)`

**Comment by git-davi** [comment]
Sorry but I have a **_FAST newbie question_**.
I can't figure out how to download the tf-nightly build source code.
It's easy to find on the web the installation: 
`$ pip install tf-nightly`
But if I would like to download the source?
**Or** to generate my `.aar` I can just navigate to the `python/dist_packages/tf-nightly` ?
(Never tried this, just assuming)

Thanks.

**Comment by jdduke** [comment]
If you're running in an emulator, the change `--config=android_arm` to `--config=android_x86`. If you want to support both in a single .aar, you can use `--config=android --fat_apk_cpu=x86,arm64-v8a,armeabi-v7a`

**Comment by git-davi** [comment]
With `--config=android_x86` i get :
`ERROR: Config value android_x86 is not defined in any .rc file`

Instead with `--config=android --fat_apk_cpu=x86,arm64-v8a,armeabi-v7a` : 
`ERROR: /home/dav/.cache/bazel/_bazel_dav/53e97091f1d0420dd55249f05e42312f/external/androidndk/BUILD.bazel:39:1: in cc_toolchain_suite rule @androidndk//:toolchain-libcpp: cc_toolchain_suite '@androidndk//:toolchain-libcpp' does not contain a toolchain for cpu 'k8'`

TF 1.14.

Already deleted the cache of previous bazel installations

**Comment by jdduke** [comment]
It sounds like you might need to re-configure your workspace for targeting Android (see https://www.tensorflow.org/lite/guide/android#configure_workspace_and_bazelrc). There's no reason you should be able to build for `--config=android_arm` but not `--config=android_x86`.

**Comment by git-davi** [comment]
Ok, right now I've removed the 
`--config=android` 
argument and leaved 
`--fat_apk_cpu=x86,arm64-v8a,armeabi-v7a`
and the build is starting correctly.
No more _toolchain issues_ :+1: 

I will update you on any the progess.

**Comment by git-davi** [comment]
After 3 hours of build i get this error:
`Linking of rule '//tensorflow/core/kernels:android_tensorflow_kernels' failed (Exit 1)`
Its a week that I'm going mad on building this tf lite `.aar`.
I'll move to tensorflow mobile

**Comment by jdduke** [comment]
Was there any additional output for the failed linkage? We haven't been able to repro that. As noted, we're hoping to have the nightly build of the select-tf-ops aar available in our nightly builds within the next week or so.

**Comment by git-davi** [comment]
Created new issue here [ #32183](https://github.com/tensorflow/tensorflow/issues/32183).
That will be a replace for this.
I moved back to tflite and tf v1.14.
I'm trying to build an `.aar` library that would run on emulator.

**Comment by bmabir17** [comment]
@jdduke can i ask if the select-tf-ops aar available in nightly build? if so can you point to which version should i use from here? 
https://bintray.com/google/tensorflow/tensorflow-lite

**Comment by jdduke** [comment]
Prebuilt libs are available @ https://bintray.com/google/tensorflow/tensorflow-lite-select-tf-ops. You can add that target in addition to the standard https://bintray.com/google/tensorflow/tensorflow-lite target.

**Comment by bmabir17** [comment]
@jdduke Thank you so much for the info :smile:
