### ISSUE TITLE
Error "swig.exe failed: error executing command" when build Tensorflow on MSVC

### ISSUE THREAD

**Issue by QuellaZhang** [tensorflow/tensorflow#31678]
Hi All,

I encountered the following error when building Tensorflow on MSVC, which looks like a configuration issue, but I don't know what was missing. Can you help me? I attached the build log. Thank you very much.

Environment: VS2017 + Windows Server 2016 +Python3

Build log: [Tensorflow_build.log](https://github.com/tensorflow/tensorflow/files/3508725/Tensorflow_build.log)

**Repro steps:**
1. git clone  https://github.com/tensorflow/tensorflow F:\tensorflow\src
2. install msys2 under F:\tensorflow\tools
3. open VS 2017 tools command
4. cd F:\tensorflow\src
5. set BAZEL_VC=C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\
6. set PATH=F:\tensorflow\tools;%path%
7. set PATH=F:\tensorflow\tools\msys64\usr\bin;%path%
8. yes "" 2>nul | python ./configure.py
9. bazel build --config=opt --subcommands //tensorflow/tools/pip_package:build_pip_package

**Failures:**
SUBCOMMAND: # //tensorflow/core/kernels:eigen_contraction_kernel_with_mkl [action 'Compiling tensorflow/core/kernels/eigen_contraction_kernel.cc']
cd C:/users/cpptestlocal/_bazel_cpptestlocal/cy65jqax/execroot/org_tensorflow
  SET INCLUDE=C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.16.27023\ATLMFC\include;C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.16.27023\include;C:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um;C:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\ucrt;C:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\shared;C:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\um;C:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\winrt;C:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\cppwinrt
    SET PATH=C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.16.27023\bin\HostX64\x64;C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\VC\VCPackages;C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\CommonExtensions\Microsoft\TestWindow;C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer;C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\bin\Roslyn;C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Team Tools\Performance Tools\x64;C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Team Tools\Performance Tools;C:\Program Files (x86)\Microsoft Visual Studio\Shared\Common\VSPerfCollectionTools\\x64;C:\Program Files (x86)\Microsoft Visual Studio\Shared\Common\VSPerfCollectionTools\;C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.6.1 Tools\x64\;C:\Program Files (x86)\HTML Help Workshop;C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\CommonExtensions\Microsoft\FSharp\;C:\Program Files (x86)\Windows Kits\10\bin\10.0.17763.0\x64;C:\Program Files (x86)\Windows Kits\10\bin\x64;C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\\MSBuild\15.0\bin;C:\windows\Microsoft.NET\Framework64\v4.0.30319;C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\;C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\Tools\;;C:\windows\system32;C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin;C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\CommonExtensions\Microsoft\CMake\Ninja
    SET PWD=/proc/self/cwd
    SET PYTHON_BIN_PATH=C:/Python/Python37/python.exe
    SET PYTHON_LIB_PATH=C:/Python/Python37/lib/site-packages
    SET RUNFILES_MANIFEST_ONLY=1
    SET TEMP=C:\Users\CPPTESTLOCAL\AppData\Local\Temp
    SET TF_CONFIGURE_IOS=0
    SET TMP=C:\Users\CPPTESTLOCAL\AppData\Local\Temp
  C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/VC/Tools/MSVC/14.16.27023/bin/HostX64/x64/cl.exe /nologo /DCOMPILER_MSVC /DNOMINMAX /D_WIN32_WINNT=0x0601 /D_CRT_SECURE_NO_DEPRECATE /D_CRT_SECURE_NO_WARNINGS /bigobj /Zm500 /EHsc /wd4351 /wd4291 /wd4250 /wd4996 /I. /Ibazel-out/x64_windows-opt/bin /Iexternal/eigen_archive /Ibazel-out/x64_windows-opt/bin/external/eigen_archive /Iexternal/local_config_sycl /Ibazel-out/x64_windows-opt/bin/external/local_config_sycl /Iexternal/mkl_dnn /Ibazel-out/x64_windows-opt/bin/external/mkl_dnn /Iexternal/eigen_archive /Ibazel-out/x64_windows-opt/bin/external/eigen_archive /Iexternal/mkl_dnn/include /Ibazel-out/x64_windows-opt/bin/external/mkl_dnn/include /Iexternal/mkl_dnn/src /Ibazel-out/x64_windows-opt/bin/external/mkl_dnn/src /Iexternal/mkl_dnn/src/common /Ibazel-out/x64_windows-opt/bin/external/mkl_dnn/src/common /Iexternal/mkl_dnn/src/cpu /Ibazel-out/x64_windows-opt/bin/external/mkl_dnn/src/cpu /Iexternal/mkl_dnn/src/cpu/gemm /Ibazel-out/x64_windows-opt/bin/external/mkl_dnn/src/cpu/gemm /Iexternal/mkl_dnn/src/cpu/xbyak /Ibazel-out/x64_windows-opt/bin/external/mkl_dnn/src/cpu/xbyak /DEIGEN_MPL2_ONLY /DEIGEN_MAX_ALIGN_BYTES=64 /DEIGEN_HAS_TYPE_TRAITS=0 /DTENSORFLOW_USE_CUSTOM_CONTRACTION_KERNEL /DTENSORFLOW_USE_MKLDNN_CONTRACTION_KERNEL /showIncludes /MD /O2 /Oy- /DNDEBUG /wd4117 -D__DATE__="redacted" -D__TIMESTAMP__="redacted" -D__TIME__="redacted" /Gy /Gw -w -DWIN32_LEAN_AND_MEAN -DNOGDI /arch:AVX /Fobazel-out/x64_windows-opt/bin/tensorflow/core/kernels/_objs/eigen_contraction_kernel_with_mkl/eigen_contraction_kernel.obj /c tensorflow/core/kernels/eigen_contraction_kernel.cc
**ERROR: F:/git_projects/tensorflow/tensorflow/tensorflow/lite/python/interpreter_wrapper/BUILD:58:1: SWIGing tensorflow/lite/python/interpreter_wrapper/interpreter_wrapper.i failed (Exit -1073741515): swig.exe failed: error executing command 
  cd C:/users/cpptestlocal/_bazel_cpptestlocal/cy65jqax/execroot/org_tensorflow**
bazel-out/x64_windows-opt/bin/external/swig/swig.exe -c++ -python -module tensorflow_wrap_interpreter_wrapper -o bazel-out/x64_windows-opt/bin/tensorflow/lite/python/interpreter_wrapper/tensorflow_wrap_interpreter_wrapper.cc -outdir bazel-out/x64_windows-opt/bin/tensorflow/lite/python/interpreter_wrapper -Iexternal/eigen_archive -Iexternal/swig -Ibazel-out/x64_windows-opt/bin -Ibazel-out/x64_windows-opt/bin/external/local_config_python -Iexternal/gemmlowp -Iexternal/com_google_absl -Iexternal/flatbuffers -Iexternal/arm_neon_2_x86_sse -Iexternal/farmhash_archive -Iexternal/swig/Lib -Iexternal/swig/Lib/cffi -Iexternal/swig/Lib/python -Iexternal/swig/Lib/std -Iexternal/swig/Lib/typemaps tensorflow/lite/python/interpreter_wrapper/interpreter_wrapper.i
Execution platform: @bazel_tools//platforms:host_platform
Target //tensorflow/tools/pip_package:build_pip_package failed to build
INFO: Elapsed time: 599.811s, Critical Path: 126.23s
INFO: 1791 processes: 1791 local.
FAILED: Build did NOT complete successfully
FAILED: Build did NOT complete successfully

**Comment by QuellaZhang** [comment]
Hello, can someone help me? This issue still blocks me, but I don't know what I should do.

**Comment by wangtz** [comment]
Looks like some environment setup causing swig to fail.

**Comment by gunan** [comment]
I actually cannot see the full failure message emitted by swig.
Could you share the full terminal output using pastebin?

**Comment by QuellaZhang** [comment]
I have attached the build log, that's all the output, does it not work? BTW, I try and I can reproduce this issue with the following step. I know it's not easy to repro since it looks like a configuration issue, if you need any info please let me know.
bazel build --config=opt --subcommands //tensorflow/lite/python/interpreter_wrapper:tensorflow_wrap_interpreter_wrapper_py_wrap

**Comment by gunan** [comment]
I can see that swig.exe failed. But I see no output from swig command itself.

@meteorcloudy @laszlocsomor any ideas?

**Comment by laszlocsomor** [comment]
@QuellaZhang : Could you try this please:
1. open `cmd.exe`
2. Run:
    ```
    md c:\tmp\gh31678

    cd C:\users\cpptestlocal\_bazel_cpptestlocal\cy65jqax\execroot\org_tensorflow

    bazel-out\x64_windows-opt\bin\external\swig\swig.exe -c++ -python -module tensorflow_wrap_interpreter_wrapper -o c:/tmp/gh31678/tensorflow_wrap_interpreter_wrapper.cc -outdir c:/tmp/gh31678 -Iexternal/eigen_archive -Iexternal/swig -Ibazel-out/x64_windows-opt/bin -Ibazel-out/x64_windows-opt/bin/external/local_config_python -Iexternal/gemmlowp -Iexternal/com_google_absl -Iexternal/flatbuffers -Iexternal/arm_neon_2_x86_sse -Iexternal/farmhash_archive -Iexternal/swig/Lib -Iexternal/swig/Lib/cffi -Iexternal/swig/Lib/python -Iexternal/swig/Lib/std -Iexternal/swig/Lib/typemaps tensorflow/lite/python/interpreter_wrapper/interpreter_wrapper.i
    ```

Does this generate `c:\tmp\gh31678\tensorflow_wrap_interpreter_wrapper.cc`? If not, what error does it print?

**Comment by QuellaZhang** [comment]
@laszlocsomor  Sorry for the late. I try the step, it run successfully and generate "C:\tmp\gh31678\tensorflow_wrap_interpreter_wrapper.cc"

**Comment by QuellaZhang** [comment]
Hello, we have find the reason. swig.exe is crash due to missing “VCRuntime140.dll”, we have install vc_redist.x64.exe and Tensorflow build successfully.
