### ISSUE TITLE
 TF-TRT: Assertion `mParams.k > 0' failed.

### ISSUE THREAD

**Issue by sgambient** [tensorflow/tensorflow#31671]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):binary
- TensorFlow version (use command below):1.14
- Python version:2.7
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:10.1
- GPU model and memory:T4

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
Seeing the following error:
```
2019-08-16 03:21:42.299651: E tensorflow/compiler/tf2tensorrt/utils/trt_logger.cc:41] DefaultLogger Parameter check failed at: ../builder/Layers.cpp::TopKLayer::2009, condition: k > 0 && k <= MAX_TOPK_K
b_engine-0: ../builder/Layers.cpp:2048: virtual bool nvinfer1::TopKLayer::validate(const std::vector<nvinfer1::TensorForm>&, const nvinfer1::NetworkLayer::ValidationContext&) const: Assertion `mParams.k > 0' failed.

```
**Describe the expected behavior**

What is this error for  ? How to stop this from happening ? 

**Code to reproduce the issue**

Try to create a snippet.

**Other info / logs**

**Comment by oanush** [comment]
@sgambient ,
In order to expedite the trouble-shooting process, please provide complete code snippet to reproduce the issue reported here. Thanks!

**Comment by sgambient** [comment]
Will try to get a code snippet to reproduce this bug.    That is a  very time consuming and laborious process. There must be better and more efficient ways.   Is  there a way to get more verbose debug message to see what exactly is causing the problem ?

**Comment by sgambient** [comment]
MAX_TOPK_K is the problem. What is this value, is there a way to adjust it ?

**Comment by sgambient** [comment]
nvinfer1::TopKLayer::validate ()  is called  when tf.nn.top_k (    input, k=1, sorted=True, name=None) is   present. Setting k  =< 3000, seems to fix the problem.

**Comment by pooyadavoodi** [comment]
@sgambient Did the problem go away when you decrease k to <=3840?

What version of TensorRT are you using?

**Comment by sgambient** [comment]
With k =3000 it worked. However, not ideal. Not sure about the exact version ( whatever comes with  the nvcr container for TF 1.14).  Is there a good way to find that out ?

**Comment by pooyadavoodi** [comment]
I think there is an environment variable you can check `echo TRT_VERSION`.

**Comment by sgambient** [comment]
TRT_VERSION=5.1.5.0

**Comment by pooyadavoodi** [comment]
I think this is fixed in TRT7.
@sgambient would you be able to verify that?

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.
