### ISSUE TITLE
Make Tensorflow lite android project using tflite of ssd_mobilenet_v1_fpn_shared_box_predictor_640x640_coco14_sync_2018_07_03 model

### ISSUE THREAD

**Issue by Wolf20199** [tensorflow/tensorflow#31670]
Hello, everyone.
Recently I try to make android project of tensorflow lite object detection.
I have successfully converted to tflite file from http://download.tensorflow.org/models/object_detection/ssd_mobilenet_v1_fpn_shared_box_predictor_640x640_coco14_sync_2018_07_03.tar.gz, which uses 640*640 input image size.
But I have memory overflow error on running my project on the android mobile.
In my previous test, I can run 300*300, 224*224 tflite model on my android mobile.
I use libtensorflowlite_gpu_jni.so and libtensorflowlite_jni.so distributed.
Could anyone tell me the maximum value of tensorflow lite input image size?
If we can run 640*640 tflite model, what should I fix the android code?
Thanks in advance.

**Comment by wangtz** [comment]
My guess is that on your mobile device, you don't have enough memory to run this model.
We don't have a formula to calculate the runtime memory usage required for each model, but it should be easy to find it out - e.g. checking the ram usage of a process?

**Comment by ravikyram** [comment]
@Wolf20199 

Looks like issue is addressed.I am closing this issue. Please, feel free to reopen if the issue still persists.Thanks!
