### ISSUE TITLE
TPUStrategy incompatibility with tf.io.read_file

### ISSUE THREAD

**Issue by jmgc** [tensorflow/tensorflow#31687]
**System information**

I am using Colaboratory and Google cloud.

- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Debian 4.9.168-1+deb9u5
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: No
- TensorFlow installed from (source or binary): unknown
- TensorFlow version (use command below): 1.14
- Python version: 3.5.3
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**

The script ends with a segmentation fault or abort.

**Describe the expected behavior**

Just a clean run.

**Code to reproduce the issue**

```python
# Importing all necessary libraries
import tensorflow as tf
import cv2
import random as rnd
import os

if int(tf.__version__.split('.')[0]) == 1:
    print(tf.__version__)
    tf.enable_eager_execution()

@tf.function
def _read_test(filename):
    img_raw = tf.io.read_file(tf.squeeze(filename))
    return img_raw

import numpy as np
image = np.array([[rnd.randint(0, 255) for _ in range(936)] for _ in range(1024)])
cv2.imwrite('0.png', image);

raw = _read_test(tf.constant('0.png'))

tf.keras.backend.clear_session()

if 'TPU_NAME' in os.environ:
    TPU_WORKER = 'grpc://' + os.environ['TPU_NAME']
    resolver = tf.contrib.cluster_resolver.TPUClusterResolver(tpu=TPU_WORKER)
    tf.config.experimental_connect_to_host(resolver.master())
    tf.contrib.distribute.initialize_tpu_system(resolver)
    strategy = tf.contrib.distribute.TPUStrategy(resolver)
elif 'COLAB_TPU_ADDR' in os.environ:
    TPU_WORKER = 'grpc://' + os.environ['COLAB_TPU_ADDR']
    resolver = tf.contrib.cluster_resolver.TPUClusterResolver(tpu=TPU_WORKER)
    tf.config.experimental_connect_to_host(resolver.master())
    tf.contrib.distribute.initialize_tpu_system(resolver)
    strategy = tf.contrib.distribute.TPUStrategy(resolver)
else:
    strategy = tf.distribute.experimental.MultiWorkerMirroredStrategy()

#print(strategy)

with strategy.scope():
    pass

print('success')
```

**Other info / logs**

The previous code is part of an image processing Neural Network. The image files are read while running the code to minimize the disk usage. The code runs smoothly in a CPU or GPU environment, however it crashes in a TPU one.

**Comment by srihari-humbarwadi** [comment]
```
All input files and the model directory must use a cloud storage
bucket path (gs://bucket-name/...), and this bucket must be accessible 
from the TPU server. Note that all data processing and model checkpointing 
is performed on the TPU server, not the local machine
```

**Comment by jmgc** [comment]
The example has been run in Colaboratory and the TPU server through a ssh connection. I am not running it on my local machine.

**Comment by srihari-humbarwadi** [comment]
@jmgc your images/ data should be stored on a GCS bucket, and then change it to something like this
```
# raw = _read_test(tf.constant('0.png'))
raw = _read_test(tf.constant('gs://your-bucket-name/0.png'))
```

**Comment by jmgc** [comment]
@srihari-humbarwadi I have tested it in a TPU server and it seems to work, however, in Colaboratory it does not find the bucket. Is it possible to access a drive in a similar way as using a bucket? If not, how can I read files in Colaboratory?

**Comment by srihari-humbarwadi** [comment]
You will have to create a service account in GCP with access to GCS bucket you intend to read data from. Then use the credentials(json) of this service account in the snippet given below
```
with tf.Session() as sess:
    with open('<YOUR CREDENTIALS JSON>', 'r') as f: 
        auth_info = json.load(f)
        tf.contrib.cloud.configure_gcs(sess, credentials=auth_info)
```

**Comment by jmgc** [comment]
Sorry, I am not able to follow all the acronyms. Can I access a drive disk from a TPU in Colaboratory?

**Comment by yongtang** [comment]
@jmgc I never used TPU before (plan to give it a try soon), but my understanding is that TPU does not give you access to a local file system so you have to use a remote file system such as GCS (with `gcs://...` scheme that TF support)

I would assume other types of remote file system such as s3 (AWS) or azfs (Azure) should work as well, as long as the TF version you use support the scheme (e.g, `s3://bucket/object`, `azfs://...`).

**Comment by gadagashwini** [comment]
@jmgc Did you try @yongtang's solution.

**Comment by jmgc** [comment]
@gadagashwini, I did not because I have tried the bucket solution, and I still have a segmentation fault in my full script. I am working on another minimal test to show the error.

**Comment by jmgc** [comment]
I modified my code, and I ended up with the segmentation fault reported in #31687.

**Comment by jmgc** [comment]
I have been working and modified my code to use a bucket. I have found the same error reported in #32043.

**Comment by frankchn** [comment]
Hi @jmgc, do you have any sample code / colab that I can look at? Also in general we are currently not supporting TPUs with 2.0 yet.

**Comment by frankchn** [comment]
Closing issue for now, feel free to reopen.
