### ISSUE TITLE
[TF 2.0] Saving model containing categorical_column_with_vocabulary_list feature_column fails

### ISSUE THREAD

**Issue by emla2805** [tensorflow/tensorflow#31686]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): MacOS
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): Binary
- TensorFlow version (use command below): v1.12.1-8794-ge36271a61d 2.0.0-dev20190814
- Python version: 3.6.8
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Describe the current behavior**

Saving a trained keras model containing a `categorical_column_with_vocabulary_list` feature_column results in the error:

 `AssertionError: Tried to export a function which references untracked object Tensor("StatefulPartitionedCall/args_1:0", shape=(), dtype=resource).TensorFlow objects (e.g. tf.Variable) captured by functions must be tracked by assigning them to an attribute of a tracked object or assigned to an attribute of the main object directly.`

**Describe the expected behavior**

It should be possible to save a model containing all types of feature_columns.

**Code to reproduce the issue**

```
import tensorflow as tf


category = tf.constant(["A", "B", "A", "C", "C", "A"])
label = tf.constant([1, 0, 1, 0, 0, 0])

ds = tf.data.Dataset.from_tensor_slices(({"category": category}, label))
ds = ds.batch(2)

fc_category = tf.feature_column.indicator_column(
    tf.feature_column.categorical_column_with_vocabulary_list(
        "category", vocabulary_list=["A", "B", "C"]
    )
)
feature_layer = tf.keras.layers.DenseFeatures([fc_category])

model = tf.keras.Sequential(
    [
        feature_layer,
        tf.keras.layers.Dense(10, activation="relu"),
        tf.keras.layers.Dense(1, activation="sigmoid"),
    ]
)

model.compile(
    optimizer="adam", loss="binary_crossentropy", metrics=["accuracy"]
)

model.fit(ds, epochs=2)

tf.keras.models.save_model(model, "model")
```

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by oanush** [comment]
@emla2805 ,
I tried executing the given code in latest TF -nightly version 2.0.0.dev20190819, I didnot face any issue. Can you please try in the latest version.Thanks

**Comment by emla2805** [comment]
@oanush you are right! It works with the latest TF-nightly, closing this issue. Thanks

**Comment by q-55555** [comment]
This error seems to be still present in stable tensorflow 2.1.0. 
@emla2805 I think it makes sense to re-open the issue ?

**Comment by rmsander** [comment]
I'm using `tf-2.2.0.dev20200315`  along with `tf_agents-0.4.0.dev20200315`, and I'm using PolicySavers for reinforcement learning.  I am calling the following: 

```
        if self.use_N_agents:
            # Get train and evaluation policies
            self.train_savers = [PolicySaver(self.collect_policies[i],
                                             batch_size=None) for i in
                                 range(self.num_agents)]
            self.eval_savers = [PolicySaver(self.eval_policies[i],
                                            batch_size=None) for i in
                                range(self.num_agents)]

        else:
            # Get train and evaluation policy savers
            self.train_saver = PolicySaver(self.collect_policy, batch_size=None)
            self.eval_saver = PolicySaver(self.eval_policy, batch_size=None)

def save_policies(self, epochs_done=0):
# Multiple PPO agents
        if self.use_N_agents:

            # Iterate through training policies and save each of them
            for i, train_saver in enumerate(self.train_savers):
                train_save_dir = os.path.join(self.policy_save_dir, "train",
                                              "epochs_{}".format(epochs_done),
                                              "agent_{}".format(i))
                if not os.path.exists(train_save_dir):
                    os.makedirs(train_save_dir, exist_ok=True)
                train_saver.save(train_save_dir)

            print("Training policies saved...")

            # Iterate through eval policies
            for i, eval_saver in enumerate(self.eval_savers):
                eval_save_dir = os.path.join(self.policy_save_dir, "eval",
                                             "epochs_{}".format(epochs_done),
                                             "agent_{}".format(i))
                if not os.path.exists(eval_save_dir):
                    os.makedirs(eval_save_dir, exist_ok=True)
                eval_saver.save(eval_save_dir)

            print("Eval policies saved...")

        # Master PPO agent
        else:
            # Save training policy
            train_save_dir = os.path.join(self.policy_save_dir, "train",
                                          "epochs_{}".format(epochs_done))
            if not os.path.exists(train_save_dir):
                os.makedirs(train_save_dir, exist_ok=True)
            self.train_saver.save(train_save_dir)

            print("Training policy saved...")

            # Save eval policy
            eval_save_dir = os.path.join(self.policy_save_dir, "eval",
                                         "epochs_{}".format(epochs_done))
            if not os.path.exists(eval_save_dir):
                os.makedirs(eval_save_dir, exist_ok=True)
            self.eval_saver.save(eval_save_dir)

            print("Eval policy saved...")

# Here's where I call the function:
    if i % self.save_interval == 0 and i == 0:
           self.save_policies(epochs_done=i)
           print("Epochs: {}".format(i))
```
This works fine if I only run it with a single PPO agent, but when I create multiple PPO agents (which I create deepcopies of to avoid overwriting/sharing parameters), I receive the following error, specifically when I try to save the training/collection policy:

```
AssertionError: Tried to export a function which references untracked object Tensor("34253:0", shape=(), dtype=resource).TensorFlow objects (e.g. tf.Variable) captured by functions must be tracked by assigning them to an attribute of a tracked object or assigned to an attribute of the main object directly.
```
Appreciate any help or input you can offer, thank you!

**Comment by emla2805** [comment]
@q-55555 I cannot reproduce this issue with the TF 2.1.0 release. What platform and python version are you using?

@rmsander I don't think your problem is related to this issue, you are not using feature_columns are you?

**Comment by q-55555** [comment]
@emla2805 I am using python 3.7.4 on Windows 10.
I have tested on pre release tensorflow 2.2.0rc3 and the problem is not present.
