### ISSUE TITLE
TFRT Built From Source does not Improve Inference Speed

### ISSUE THREAD

**Issue by PetreanuAndi** [tensorflow/tensorflow#31683]
[convertTFRT_frozenGraph.zip](https://github.com/tensorflow/tensorflow/files/3509287/convertTFRT_frozenGraph.zip)

<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 16.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: - 
- TensorFlow installed from (source or binary): built from source 
- TensorFlow version: **1.14**
- Python version: **2.7**
- Installed using virtualenv? pip? conda?: conda
- Bazel version (if compiling from source): 0.25.2
- GCC/Compiler version (if compiling from source): 5.4.0
- CUDA/cuDNN version: **10.0.0 / 7.4.2**
- GPU model and memory: 1080Ti

**Describe the problem**
I have built TensorFlow from Sources, and checked the "yes" option when asked about compiling with TensorRT. Graph builds, trt_only nodes exist, inference speed on SSD + FPN model is not optimised (actually slightly worse than the original, pre-optimization frozen_graph.pb

**Provide the exact sequence of commands / steps that you executed before running into the problem**
Build from source tensorFlow 1.14
Create optimised graph from original frozen_graph.pb
Infer over optimised graph ====> **no speedup whatsoever**

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

Uploaded conversion script.
Notice I try to get outputs from all FPN levels (not just final feature map), in order to use those in another LSTM-type network classifier.

----------------------------------------------------------------------
Prints from optimization script : 
2019-08-16 12:25:39.310289: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:716] Optimization results for grappler item: tf_graph
2019-08-16 12:25:39.310333: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:718]   constant folding: Graph size after: 2836 nodes (-1660), 4183 edges (-1854), time = 728.073ms.
2019-08-16 12:25:39.310337: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:718]   layout: Graph size after: 2880 nodes (44), 4255 edges (72), time = 143.931ms.
2019-08-16 12:25:39.310341: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:718]   constant folding: Graph size after: 2880 nodes (0), 4255 edges (0), time = 167.55ms.
2019-08-16 12:25:39.310345: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:718]   TensorRTOptimizer: Graph size after: 1907 nodes (-973), 3218 edges (-1037), time = 7242.89307ms.
graph_size(MB)(native_tf): 123.3
graph_size(MB)(trt): 336.9
num_nodes(native_tf): 4496
num_nodes(tftrt_total): 1907
**num_nodes(trt_only): 94**
time(s) (trt_conversion): 10.6979
**number of TRT ops in the converted graph :  94**

-----------------------------------------------------------------------------------------------------------------
Just tried using tf-nightly-gpu 1.15.0.dev20190816 , with Cuda 10.1 and cudnn 7.6, and the inference time is even worse! (with mode trt_only nodes as shows the print : )

graph_size(MB)(native_tf): 123.3
graph_size(MB)(trt): 159.7
num_nodes(native_tf): 4496
num_nodes(tftrt_total): 1894
num_nodes(trt_only): 102
time(s) (trt_conversion): 8.1412
number of TRT ops in the converted graph :  102

-----------------------------------------------------------------------------------------------------------------

Average [1:100] random images Inference Speeds : 
original .pb inference speed : **0.028s**
tf1.14+trt5 compiled from source inference speed : **0.029**
tf1.15+trt installed with pip : **0.032**

**None** of these had errors when building or optimizing the graph :)

**Comment by aaroey** [comment]
@PetreanuAndi you mentioned that you built from source using 1.14 branch, is that right? If so, could you share your `configure` output (the content of the `.tf_configure.bazelrc` file)? Also, I think the 1.14 branch is in a bad state now, could you try using the 1.15 branch instead?

Alternatively, both [1.15rc1](https://pypi.org/project/tensorflow-gpu/1.15.0rc1/) and [2.0rc1](https://pypi.org/project/tensorflow-gpu/2.0.0rc1/) were out and TF-TRT was enabled in both, would you please try either of them and let me know?

Thanks.

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.
