### ISSUE TITLE
Docs could mention that Dataset sharding is deterministic

### ISSUE THREAD

**Issue by anubh-v** [tensorflow/tensorflow#31698]
Hi everyone,
Thanks for your work on maintaining and developing Tensorflow.

I wish to raise a suggestion for the documentation of the `tf.data.Dataset` Python API.
In particular, I am referring to the documentation of the `shard` operation.

## URL(s) with the issue:

r1.14 docs: https://www.tensorflow.org/api_docs/python/tf/data/Dataset#shard

r2.0 docs: https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/data/Dataset#shard

### Clear description

From my understanding of the source code, the `shard` operation is **deterministic**. 
i.e. if we apply `shard` on a Dataset A with some fixed values of `num_shards` and `index`, the operation will always return the same subset of Dataset A.

Perhaps the documentation should mention that this operation is deterministic?
This will help readers understand that the sharding does not involve any randomness.
Currently, the docs do not mention this aspect of `shard`'s behaviour.

### Correct links

Is the link to the source code correct? Yes

### Parameters defined

Are all parameters defined and formatted correctly? Yes

### Returns defined

Are return values defined? Yes

### Raises listed and defined

Are the errors defined? Yes

### Usage example

Is there a usage example? Yes

### Request visuals, if applicable

Are there currently visuals? No, but this issue does not require visuals

### Submit a pull request?

I can submit a PR to update the docs - if this is indeed considered a useful fix.

Thanks for your time.

**Comment by jvishnuvardhan** [comment]
@anubh-v Can you raise a PR to update the docs? Thanks!

**Comment by anubh-v** [comment]
@jvishnuvardhan Sure, I will update the docs and raise a PR in 2-3 days. Thanks.

**Comment by jvishnuvardhan** [comment]
Automatically closing this out since I understand it to be resolved by the https://github.com/tensorflow/tensorflow/pull/31897 (merged already), but please let me know if I'm mistaken.Thanks!
