### ISSUE TITLE
ImportError: Could not find 'cudart64_100.dll'

### ISSUE THREAD

**Issue by nithrous** [tensorflow/tensorflow#31701]
Hi everyone, I installed `tensorflow-gpu==2.0.0-beta1` according official documentation, but catch this error:
`ImportError: Could not find 'cudart64_100.dll'. TensorFlow requires that this DLL be installed in a directory that is named in your %PATH% environment variable. Download and install CUDA 10.0 from this URL: https://developer.nvidia.com/cuda-90-download-archive`

I made all things from:
- official documentation: https://www.tensorflow.org/install/gpu
- from here: https://medium.com/@teavanist/install-tensorflow-gpu-on-windows-10-5a23c46bdbc7
- Checked `PATH` variable: `C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0\bin`
- also have `CUDA_PATH` : `C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0` in variables
- file `C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0\bin\cudart64_100.dll` exists
- Did system restart

How can I fix that?

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- TensorFlow installed from (source or binary): binary
- TensorFlow version: tensorflow-gpu==2.0.0-beta1
- Python version: 3.7
- Installed using virtualenv? pip? conda?: pip
- CUDA/cuDNN version: CUDA 10.0, cuDNN v7.6.2 (July 22, 2019), for CUDA 10.0
- GPU model and memory: MSI 1070 TI

**### UPD**
Windows reinstall solved the issue

**Comment by littlemountainman** [comment]
You have to add the cuda/bin and cuda/lib to your path.

**Comment by nithrous** [comment]
> You have to add the cuda/bin and cuda/lib to your path.

Already added

![Variables](https://user-images.githubusercontent.com/10476019/63215561-17e5b880-c131-11e9-89fa-793515cb9d6e.png)

**Comment by littlemountainman** [comment]
I meant you additionally need to link your cudnn. Move your inside the cudnn zip is a folder called cuda. Move that to your c:\  drive then go ahead and add c:\cuda\bin and c:\cuda\lib to your path. Reboot and you are good to go :)

**Comment by nithrous** [comment]
> I meant you additionally need to link your cudnn. Move your inside the cudnn zip is a folder called cuda. Move that to your c:\ drive then go ahead and add c:\cuda\bin and c:\cuda\lib to your path. Reboot and you are good to go :)

That didn't help :(

![Variables](https://user-images.githubusercontent.com/10476019/63215972-c9d3b380-c136-11e9-8d28-64350bf617c7.png)

**Comment by littlemountainman** [comment]
Did you reboot ? Please verify you have the right cudnn for CUDA v10.

**Comment by nithrous** [comment]
> Did you reboot ? Please verify you have the right cudnn for CUDA v10.

I have installed CUDA v10 and cudnn for that version and did reboot after each PATH change. But still have this error.

![Cuda](https://user-images.githubusercontent.com/10476019/63216080-7c584600-c138-11e9-952f-d2c9828839ff.png)

**Comment by nithrous** [comment]
Windows reinstall solved this issue

**Comment by lingyue328** [comment]
Actually, reboot windows solved this issue
