### ISSUE TITLE
keras.backend.gradients shows error as tf.gradients

### ISSUE THREAD

**Issue by zwenju** [tensorflow/tensorflow#31719]
**System information**
tensorflow 2.0b1
windows 10
anaconda python 3.7

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
![20190817164347](https://user-images.githubusercontent.com/27112868/63209122-87e34700-c10f-11e9-8040-38dbdda1d351.png)

**Describe the expected behavior**

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

```
import tensorflow as tf
import tensorflow.keras as keras
import tensorflow.keras.layers as layers
import tensorflow.keras.backend as K

tf.keras.backend.set_floatx('float64')



def grad( y, x ):
   V =  tf.keras.layers.Lambda( lambda z: K.gradients( z[ 0 ], z[ 1 ] ), output_shape = [1] )( [ y, x ] )
   return V



fixed_input = keras.Input( shape=(2,) )

a = fixed_input * fixed_input

b = grad( a, fixed_input )


model = keras.Model( inputs = [ fixed_input ], outputs = [ b ] )



c = model( tf.constant(2.0, dtype=tf.float64))
```

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

runfile('F:/2019/temp1.py', wdir='F:/2019')
WARNING: Logging before flag parsing goes to stderr.
W0817 16:46:12.144755  7996 ag_logging.py:145] Entity <bound method TensorFlowOpLayer._defun_call of <tensorflow.python.eager.function.TfMethodTarget object at 0x0000016B87200DD8>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method TensorFlowOpLayer._defun_call of <tensorflow.python.eager.function.TfMethodTarget object at 0x0000016B87200DD8>>: AssertionError: 
Reloaded modules: tmpd51tclm6
WARNING: Entity <bound method TensorFlowOpLayer._defun_call of <tensorflow.python.eager.function.TfMethodTarget object at 0x0000016B87200DD8>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method TensorFlowOpLayer._defun_call of <tensorflow.python.eager.function.TfMethodTarget object at 0x0000016B87200DD8>>: AssertionError: 
Traceback (most recent call last):

  File "<ipython-input-2-763868c416b6>", line 1, in <module>
    runfile('F:/2019/temp1.py', wdir='F:/2019')

  File "C:\Users\lenovo\Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 826, in runfile
    execfile(filename, namespace)

  File "C:\Users\lenovo\Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 110, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "F:/2019/temp1.py", line 28, in <module>
    c = model( tf.constant(2.0, dtype=tf.float64))

  File "C:\Users\lenovo\Anaconda3\lib\site-packages\tensorflow\python\keras\engine\base_layer.py", line 712, in __call__
    outputs = self.call(inputs, *args, **kwargs)

  File "C:\Users\lenovo\Anaconda3\lib\site-packages\tensorflow\python\keras\engine\network.py", line 753, in call
    return self._run_internal_graph(inputs, training=training, mask=mask)

  File "C:\Users\lenovo\Anaconda3\lib\site-packages\tensorflow\python\keras\engine\network.py", line 895, in _run_internal_graph
    output_tensors = layer(computed_tensors, **kwargs)

  File "C:\Users\lenovo\Anaconda3\lib\site-packages\tensorflow\python\keras\engine\base_layer.py", line 712, in __call__
    outputs = self.call(inputs, *args, **kwargs)

  File "C:\Users\lenovo\Anaconda3\lib\site-packages\tensorflow\python\keras\layers\core.py", line 785, in call
    return self.function(inputs, **arguments)

  File "F:/2019/temp1.py", line 12, in <lambda>
    V =  tf.keras.layers.Lambda( lambda z: K.gradients( z[ 0 ], z[ 1 ] ), output_shape = [1] )( [ y, x ] )

  File "C:\Users\lenovo\Anaconda3\lib\site-packages\tensorflow\python\keras\backend.py", line 3568, in gradients
    loss, variables, colocate_gradients_with_ops=True)

  File "C:\Users\lenovo\Anaconda3\lib\site-packages\tensorflow\python\ops\gradients_impl.py", line 158, in gradients
    unconnected_gradients)

  File "C:\Users\lenovo\Anaconda3\lib\site-packages\tensorflow\python\ops\gradients_util.py", line 504, in _GradientsHelper
    raise RuntimeError("tf.gradients is not supported when eager execution "

RuntimeError: tf.gradients is not supported when eager execution is enabled. Use tf.GradientTape instead.

**Comment by WindQAQ** [comment]
Hi @zwenju, it's because you are using functional API so the standard way to get the output from functional API is using `model.predict`. If you call the model via `__call__` the model will run eagerly, thus get the errors. So the workable example should be:
```python
import tensorflow as tf
import tensorflow.keras as keras
import tensorflow.keras.layers as layers
import tensorflow.keras.backend as K

tf.keras.backend.set_floatx('float64')


def grad(y, x):
    V = layers.Lambda(lambda z: K.gradients(
        z[0], z[1]), output_shape=[1])([y, x])
    return V


fixed_input = keras.Input(shape=(2,))
a = fixed_input * fixed_input
b = grad(a, fixed_input)

model = keras.Model(inputs=[fixed_input], outputs=[b])

# c = model(tf.constant(2.0, dtype=tf.float64))
c = model.predict(tf.constant([[2.0, 1.0]], dtype=tf.float64))
print(c)
```

If you do want to subclass a `tf.keras.Model` instead of functional API for flexibility, you could obtain the gradient in this way:
```python
class Toy(tf.keras.Model):
    def call(self, x):
        return x * x

toy = Toy()

x = tf.constant([2.0, 1.0], dtype=tf.float64)
with tf.GradientTape() as tape:
    # Remember to watch non-variable tensor
    tape.watch(x)
    y = toy(x)
print(tape.gradient(y, x))
```

Thanks

**Comment by zwenju** [comment]
Great Thanks！
I tested you solutions, It works well.
