### ISSUE TITLE
Make ConcreteFunction Compatible with Pickle

### ISSUE THREAD

**Issue by devstein** [tensorflow/tensorflow#31729]
**System information**
- TensorFlow version (you are using): `2.0.0-beta1`
- Are you willing to contribute it (Yes/No): No 

**Describe the feature and the current behavior/state.**
See [issue 31421](https://github.com/tensorflow/tensorflow/issues/31421#issue-478107883) for more details. 

A `ConcreteFunction`, specifically, a `SavedModel`'s default serving `ConcreteFunction` that is used for `SavedModel` predictions. 

```python
saved_model = tf.saved_model.load(export_dir, tags=['serve'])

# infer is not serializable (it cannot be pickled)
infer = saved_model.signatures[tf.saved_model.DEFAULT_SERVING_SIGNATURE_DEF_KEY]
```

The serialization error is 
```sh
_pickle.PickleError: can't pickle repeated message fields, convert to list first
```

**Will this change the current api? How?**
Not to my knowledge 

**Who will benefit with this feature?**
Anyone who wants to deploy a TF 2.0 `SavedModel` or use a `ConcreteFunction` in (Py)Spark or any other distributed system that relies on pickling user-defined functions 

**Any Other info.**

https://github.com/tensorflow/tensorflow/issues/31421#issuecomment-522273057

**Comment by rmothukuru** [comment]
@devstein,
Sorry for the delayed response. Can you please check the documentation for [Loading the Model with Signatures](https://www.tensorflow.org/guide/saved_model#specifying_signatures_during_export) let us know if the issue still persists? Thanks!
