### ISSUE TITLE
[lite] failed on  define=with_select_tf_ops=true

### ISSUE THREAD

**Issue by laohur** [tensorflow/tensorflow#31721]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code 
’ 
cc_binary(
    name = "Prophet.so",
    srcs = ["minimal.h", "Prophet.cc",   ],
    linkopts = tflite_linkopts() + select({
        "//tensorflow:android": [
            "-pie",  # Android 5.0 and later supports only PIE
            "-lm",  # some builtin ops, e.g., tanh, need -lm
        ],
        "//conditions:default": [],
    }),
    deps = [
        "//tensorflow/lite:framework",
        "//tensorflow/lite/delegates/flex:delegate", [ on | off]
        "//tensorflow/lite/c:c_api_internal",
        "//tensorflow/lite/kernels:builtin_ops",
        "//tensorflow/lite:builtin_op_data",
        "//tensorflow/lite/schema:schema_fbs",
    ],
    linkshared = True,
)
- OS Platform and Distribution (vmware Linux Ubuntu 18.04 x4 on window10x64):
- TensorFlow installed from (source  ):github 20190817
- TensorFlow version (): 1.14.0
- Python version:3.7.4
- Bazel version (if compiling from source):0.26
- GCC/Compiler version (if compiling from source): 7.4 binary
- CUDA/cuDNN version: cpu
- GPU model and memory: cpu

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c

**Describe the current behavior**
Target //tensorflow/lite/examples/l17:Prophet.so failed to build
**Describe the expected behavior**
build successed
**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.
 bazel build --config monolithic --cxxopt=-std=c++11 -c opt  \
  --crosstool_top=//external:android/crosstool \
  --host_crosstool_top=@bazel_tools//tools/cpp:toolchain \
--define=with_select_tf_ops=true   --cpu=armeabi-v7a  --verbose_failures\
  //tensorflow/lite/examples/l17:Prophet.so

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.
bazel cmd log
`
ERROR: /root/tensorflow-master/tensorflow/core/kernels/BUILD:6576:1: C++ compilation of rule '//tensorflow/core/kernels:android_tensorflow_kernels' failed (Exit 254): clang failed: error executing command
  (cd /root/.cache/bazel/_bazel_root/510cb3499e6983b92a09020af9102ff3/execroot/org_tensorflow && \
  exec env - \
    ANDROID_BUILD_TOOLS_VERSION=29.0.2 \
    ANDROID_NDK_API_LEVEL=18 \
    ANDROID_NDK_HOME=/root/vender/android-ndk-r17c \
    ANDROID_SDK_API_LEVEL=18 \
    ANDROID_SDK_HOME=/root/vender/android-sdk \
    PATH='~/anaconda3/bin:/root/anaconda3/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin' \
    PWD=/proc/self/cwd \
    PYTHON_BIN_PATH=/root/anaconda3/bin/python \
    PYTHON_LIB_PATH=/root/anaconda3/lib/python3.7/site-packages \
    TF_CONFIGURE_IOS=0 \
  external/androidndk/ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/clang '-D__ANDROID_API__=18' -isystemexternal/androidndk/ndk/sysroot/usr/include/arm-linux-androideabi -target armv7-none-linux-androideabi '-march=armv7-a' '-mfloat-abi=softfp' '-mfpu=vfpv3-d16' -gcc-toolchain external/androidndk/ndk/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64 -fpic -ffunction-sections -funwind-tables -fstack-protector-strong -Wno-invalid-command-line-argument -Wno-unused-command-line-argument -no-canonical-prefixes -mthumb -Os -g -DNDEBUG -MD -MF bazel-out/armeabi-v7a-opt/bin/tensorflow/core/kernels/_objs/android_tensorflow_kernels/cwise_op_not_equal_to_2.pic.d '-frandom-seed=bazel-out/armeabi-v7a-opt/bin/tensorflow/core/kernels/_objs/android_tensorflow_kernels/cwise_op_not_equal_to_2.pic.o' -fPIC -D__CLANG_SUPPORT_DYN_ANNOTATION__ -DEIGEN_MPL2_ONLY '-DEIGEN_MAX_ALIGN_BYTES=64' '-DEIGEN_HAS_TYPE_TRAITS=0' -iquote . -iquote bazel-out/armeabi-v7a-opt/bin -iquote external/com_google_absl -iquote bazel-out/armeabi-v7a-opt/bin/external/com_google_absl -iquote external/nsync -iquote bazel-out/armeabi-v7a-opt/bin/external/nsync -iquote external/com_google_protobuf -iquote bazel-out/armeabi-v7a-opt/bin/external/com_google_protobuf -iquote external/zlib_archive -iquote bazel-out/armeabi-v7a-opt/bin/external/zlib_archive -iquote external/eigen_archive -iquote bazel-out/armeabi-v7a-opt/bin/external/eigen_archive -iquote external/local_config_sycl -iquote bazel-out/armeabi-v7a-opt/bin/external/local_config_sycl -iquote external/double_conversion -iquote bazel-out/armeabi-v7a-opt/bin/external/double_conversion -iquote external/farmhash_archive -iquote bazel-out/armeabi-v7a-opt/bin/external/farmhash_archive -iquote external/fft2d -iquote bazel-out/armeabi-v7a-opt/bin/external/fft2d -iquote external/gemmlowp -iquote bazel-out/armeabi-v7a-opt/bin/external/gemmlowp -isystem external/nsync/public -isystem bazel-out/armeabi-v7a-opt/bin/external/nsync/public -isystem external/com_google_protobuf/src -isystem bazel-out/armeabi-v7a-opt/bin/external/com_google_protobuf/src -isystem external/zlib_archive -isystem bazel-out/armeabi-v7a-opt/bin/external/zlib_archive -isystem external/eigen_archive -isystem bazel-out/armeabi-v7a-opt/bin/external/eigen_archive -isystem external/double_conversion -isystem bazel-out/armeabi-v7a-opt/bin/external/double_conversion -isystem external/farmhash_archive/src -isystem bazel-out/armeabi-v7a-opt/bin/external/farmhash_archive/src '-std=c++11' -DEIGEN_AVOID_STL_ARRAY -Iexternal/gemmlowp -Wno-sign-compare -fno-exceptions '-ftemplate-depth=900' '-mfpu=neon' -DTENSORFLOW_MONOLITHIC_BUILD -DTF_LEAN_BINARY -Wno-narrowing -fomit-frame-pointer -O2 '--sysroot=external/androidndk/ndk/platforms/android-18/arch-arm' -isystem external/androidndk/ndk/sources/cxx-stl/llvm-libc++/include -isystem external/androidndk/ndk/sources/cxx-stl/llvm-libc++abi/include -isystem external/androidndk/ndk/sources/android/support/include -isystemexternal/androidndk/ndk/sysroot/usr/include -c tensorflow/core/kernels/cwise_op_not_equal_to_2.cc -o bazel-out/armeabi-v7a-opt/bin/tensorflow/core/kernels/_objs/android_tensorflow_kernels/cwise_op_not_equal_to_2.pic.o)
Execution platform: @bazel_tools//platforms:host_platform
clang: error: unable to execute command: Killed
clang: error: clang frontend command failed due to signal (use -v to see invocation)
Android (4691093 based on r316199) clang version 6.0.2 (https://android.googlesource.com/toolchain/clang 183abd29fc496f55536e7d904e0abae47888fc7f) (https://android.googlesource.com/toolchain/llvm 34361f192e41ed6e4e8f9aca80a4ea7e9856f327) (based on LLVM 6.0.2svn)
Target: armv7-none-linux-android
Thread model: posix
InstalledDir: external/androidndk/ndk/toolchains/llvm/prebuilt/linux-x86_64/bin
clang: note: diagnostic msg: PLEASE submit a bug report to http://llvm.org/bugs/ and include the crash backtrace, preprocessed source, and associated run script.
clang: note: diagnostic msg:
********************

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang: note: diagnostic msg: /tmp/cwise_op_not_equal_to_2-9cbb9b.cpp
clang: note: diagnostic msg: /tmp/cwise_op_not_equal_to_2-9cbb9b.sh
clang: note: diagnostic msg:

********************
Target //tensorflow/lite/examples/l17:Prophet.so failed to build

`

**Comment by wangtz** [comment]
It's interesting that it crashes at printf not `float re=output[0];`

Does it crash if you try to access to output[0] before invoke? And what's the value of output? Is it nullptr?

**Comment by laohur** [comment]
foud type error.
fail: 
       *result=interpreter->typed_output_tensor<int>(0)[0];  // fail
ok:
        TfLiteTensor* outputTensor=interpreter->tensor(interpreter->outputs()[0]);
        auto re=outputTensor->data.i32;
why?

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.
