### ISSUE TITLE
Pip should not install as super user in the install tutorial (sudo pip install …)

### ISSUE THREAD

**Issue by 3rd3** [tensorflow/tensorflow#3173]
Is there a particular reason it is installed as root in this case? It is usually deprecated to do it this way.

**Comment by 3rd3** [comment]
See also this SO Q/A: http://stackoverflow.com/questions/33004708/osx-el-capitan-sudo-pip-install-oserror-errno-1-operation-not-permitted/33004920#33004920

**Comment by aselle** [comment]
That stackoverflow is interesting, but the comment which suggests not using sudo pip install does not suggest a solution that works for all users globally. That is one reason that sudo pip install  could be preferred.

**Comment by aselle** [comment]
Automatically closing due to lack of recent activity. Please reopen when further information becomes available.
