### ISSUE TITLE
Guide is needed for transform of models suitable for tensorflow lite with gpu delegate

### ISSUE THREAD

**Issue by kingofthebongo2008** [tensorflow/tensorflow#31739]
Hello,
Where one can find how to transform models to be suitable for working with tensorflow lite for gpu?
What should i do to transfer images from 3 components to 4 components.
I am trying to work with mtcnn. I have converted it successfully to tflite, works fine on the cpu,

ERROR: Next operations are not supported by GPU delegate:
NEG: Operation is not supported.
First 2 operations will run on the GPU, and the remaining 40 on the CPU.
WARN: compileToBinary(256):
C:\fakepath(86,169-182): warning X3556: integer divides may be much slower, try using uints if possible.
C:\fakepath(86,246-259): warning X3556: integer modulus may be much slower, try using uints if possible.

ERROR: TfLiteGpuDelegate Invoke: ConvertToPHWC4: Input data size does not match expected size: 12288000 != 6912
ERROR: Node number 27 (TfLiteGpuDelegate) failed to invoke.

**Comment by impjdi** [comment]
@kingofthebongo2008 

Is it possible to share the model?

> First 2 operations will run on the GPU, and the remaining 40 on the CPU.

This means that you have some ops that are not compatible with GPU.  You can use visualization tools to check what the 2nd op might be.

> WARN: compileToBinary(256):

I'm not familiar with this error message.  Are you using quantized models?  They are not compatible with GPU at the moment.

> ERROR: TfLiteGpuDelegate Invoke: ConvertToPHWC4: Input data size does not match expected size: 12288000 != 6912

Are you using batch of size != 1?

**Comment by Saduf2019** [comment]
@kingofthebongo2008 
Please update as per above comment.
