### ISSUE TITLE
Seg Fault with Custom Op built with nightly (works fine with v1.14 and 2.0 Beta)

### ISSUE THREAD

**Issue by oracle3001** [tensorflow/tensorflow#31741]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution : Linux Ubuntu 16.04
- TensorFlow installed from : binary
- TensorFlow version: Nightly
- Python version: 3.7
- GCC/Compiler version (if compiling from source): 7.4.0
- CUDA/cuDNN version: 10.1
- GPU model and memory: 1080Ti

I have a series of custom ops. They build and operate perfectly fine on a Windows 10 (with v1.14, v2.0 beta and nightly).

I have just tried to build them on Linux, and they again work fine with v1.14 and v2.0 Beta. However with nightly they instantly segfault. As per the instructions I am using -D_GLIBCXX_USE_CXX11_ABI=0 flag due to using gcc 7.4.0

I have also tried building the op with g++ 4.8 and still have the same issue.

**Comment by gadagashwini** [comment]
@oracle3001,
If you are using our prebuilt pip packages, you should follow the instructions at github.com/tensorflow/custom-op to build your custom ops. Thanks!

**Comment by oracle3001** [comment]
I have followed the instructions as presented on https://www.tensorflow.org/guide/extend/op

As I say, my ops build perfectly with v1.14 and v2.0Beta. It is only with nightly build that they segfault.

**Comment by oracle3001** [comment]
I should add that I can add the ops and call them as stand alone operators. However, if I put them inside a keras model and try to optimize, that is when they segfault occurs.

**Comment by oracle3001** [comment]
I have fixed this issue. Was due to incorrect compiler flags relating to a dependant library used by the custom ops.

**Comment by gadagashwini** [comment]
Glad to know that it resolved. Thanks
