### ISSUE TITLE
ModuleNotFoundError: No module named 'tensorflow'

### ISSUE THREAD

**Issue by ediazm** [tensorflow/tensorflow#31743]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version (use command below):
- Python version:
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
It cannot import tensor flow in jupyterlab
**Describe the expected behavior**
It should import tensorflow
**Code to reproduce the issue**
import tensorflow as tf
**Other info / logs**
![Screen Shot 2019-08-18 at 5 37 12 PM](https://user-images.githubusercontent.com/20175738/63232913-1a9fe680-c1e1-11e9-9acf-e51d45600d05.png)

**Comment by Pranay144** [comment]
pip install tensorflow

**Comment by ediazm** [comment]
It is installed it appears when I do: 
pip list. But the error still appears

**Comment by oanush** [comment]
@ediazm ,
Can you please go through this [link](https://www.tensorflow.org/install/pip) ?Thanks!

**Comment by ediazm** [comment]
There was two problems, even though in the terminal it displayed that tensorflow was installed, when I did "pip list" inside a cell of jupyterlab it did not have tensor flow. So I did:
1) pip install
2) Restarted the kernel
![Screen Shot 2019-08-19 at 7 19 14 PM](https://user-images.githubusercontent.com/20175738/63312660-12b27600-c2b7-11e9-88ab-e0c8f814b46d.png)
![Screen Shot 2019-08-19 at 7 19 26 PM](https://user-images.githubusercontent.com/20175738/63312664-16de9380-c2b7-11e9-972a-b292c5234687.png)
