### ISSUE TITLE
tf.function decorator not found

### ISSUE THREAD

**Issue by pzobel** [tensorflow/tensorflow#31755]
Hi,

in the current nightly build, tf.function cannot be found.

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04.2 LTS
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): tf-nightly-gpu-2.0-preview 2.0.0.dev20190818
- Python version: 3.6

**Code to reproduce the issue**
```
import tensorflow as tf

@tf.function
def my_func():
   print(tf.__version__)
```

**Other info / logs**
AttributeError: module 'tensorflow' has no attribute 'function'

**Comment by pzobel** [comment]
Problem solved. This was an issue with my virtual environment.

**Comment by wolfiex** [comment]
What was the issue?

**Comment by pzobel** [comment]
@wolfiex TF 1.x was installed. Make sure that TF 2.0 is installed to use the tf.function decorator.

**Comment by wolfiex** [comment]
Hi, I am only employed 2.5 days of the week (mainly Tuesday and
Wednesday). This means that replies may be delayed. Thanks for
understanding.

**Comment by wolfiex** [comment]
Ah yes, just made the same mistake, Thanks!

**Comment by vital1312** [comment]
My CPU does not support TF 2.x,  but I need this decorator. Is there any proper solution?
