### ISSUE TITLE
ValueError: ('Input has undefined rank:', TensorShape(None))

### ISSUE THREAD

**Issue by zwenju** [tensorflow/tensorflow#31751]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
windows 10, anaconda python 3.7
tensorflow 2.0b1

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
![image](https://user-images.githubusercontent.com/27112868/63238990-9babbc00-c27b-11e9-9f3f-be7fd9165bdd.png)

Problem : ValueError: ('Input has undefined rank:', TensorShape(None))
when I used line 62-63 instead of 64,  there will be no errors.
I am not sure why  line 64 is not working correctly.

**Describe the expected behavior**

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

```
import time
import math
import tensorflow as tf
import numpy as np
import tensorflow as keras
from tensorflow.keras import layers
from tensorflow import keras
from tensorflow.keras.utils import plot_model
from scipy . stats import multivariate_normal as normal
tf.keras.backend.set_floatx('float64')

d = 10
T = 0.1
n_time = 5
n_sample = 10
batch_size = 10
n_maxstep = 400
h = (T + 0.0) / n_time
t_stamp = np.arange (0, n_time) * h

def f_tf (t, X, Y, Z):
    V =  Y - tf.math.pow (Y,3)
    return V

def g_tf (t, X):
    V =  0.5 / (1 + 0.2*tf.math.reduce_sum (X**2, 1, keepdims=True))
    return V

def sample_path ( n_sample ):
    dW_sample = np.zeros ([ n_sample, d, n_time  ], dtype = np.float64)
    X_sample  = np.zeros ([ n_sample, d, n_time+1], dtype = np.float64)
    for i in range (n_time):
        dW_sample [:, :, i  ] = np.reshape ( normal.rvs ( mean = np.zeros(d,dtype = np.float64),\
                                      cov =1, size = n_sample ) * np.sqrt(h), ( n_sample, d))

        X_sample  [:, :, i+1] =  X_sample  [:, :, i] + np.sqrt(2) * dW_sample [:, :, i]
    return dW_sample, X_sample

def nn_tf(x):
    x = keras.layers.BatchNormalization(batch_size = n_sample)(x)
    x = keras.layers.Dense(d+10, batch_size = n_sample)(x)

    x = keras.layers.BatchNormalization(batch_size = n_sample)(x)
    x = keras.layers.Dense(d+10, batch_size = n_sample)(x)

    x = keras.layers.BatchNormalization(batch_size = n_sample)(x)
    x = keras.layers.Dense(d, batch_size = n_sample)(x)

    x = keras.layers.BatchNormalization(batch_size = n_sample)(x)
    return x

dW = keras.Input(shape = (d, n_time  ), batch_size=n_sample, dtype = tf.float64, name = 'dW')
XX = keras.Input(shape = (d, n_time+1), batch_size=n_sample, dtype = tf.float64, name = 'X' )
X = XX
Y = tf.ones([n_sample, 1], dtype = tf.float64)
Z = tf.ones([n_sample, d], dtype = tf.float64)

for it in range(n_time-1):
    with tf.name_scope(str(it+1)):
        Y = Y - f_tf(t_stamp[it], X[:,:,it], Y, Z) * h
        Y = Y +  tf.math.reduce_sum( Z * dW[:,:,it],  1, keepdims=True)
        #subX = tf.reshape(X[:,:,it], shape = [n_sample, d])
        #Z = nn_tf(subX) / d
        Z = nn_tf(X[:,:,it]) / d

Y = Y - f_tf(t_stamp[n_time-1], X[:,:,n_time-1], Y, Z) * h
Y = Y + tf.math.reduce_sum (Z * dW [:, :, n_time-1], 1, keepdims=True)
model = keras.Model(inputs=[XX,dW], outputs=[Y])

optimizer = keras.optimizers.Adam(learning_rate=1e-3)
train_accuracy = tf.keras.metrics.SparseCategoricalAccuracy(name='train_accuracy')

for epoch in range (100):
    dW_train, X_train = sample_path ( n_sample )

    with tf.GradientTape() as tape:
        predictions = model( [X_train, dW_train] )
        label = g_tf (T, X_train[:, :, n_time])
        #print("label = ", label)
        #print("predictions = ", predictions)
        #loss_value = tf.reduce_sum( tf.keras.losses.MSE (label, predictions ) )
        loss_value = ( tf.keras.losses.MeanSquaredError() (label, predictions ) )
        #print("label = ", label)
        #print("predictions = ", predictions)
        print("lss = ", loss_value )
    grads = tape.gradient(loss_value,  model.trainable_variables)
    optimizer.apply_gradients( zip(grads, model.trainable_variables) )
    accuracy = train_accuracy(label, predictions)
    print("step ", epoch, "loss = ", loss_value.numpy(), "accuracy = ", accuracy.numpy())
```

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

runfile('C:/Users/DELL/Desktop/DP_PDE_PY/PDE_DP_1.py', wdir='C:/Users/DELL/Desktop/DP_PDE_PY')
Traceback (most recent call last):

  File "<ipython-input-42-59f0f0a64686>", line 1, in <module>
    runfile('C:/Users/DELL/Desktop/DP_PDE_PY/PDE_DP_1.py', wdir='C:/Users/DELL/Desktop/DP_PDE_PY')

  File "D:\Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 826, in runfile
    execfile(filename, namespace)

  File "D:\Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 110, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/Users/DELL/Desktop/DP_PDE_PY/PDE_DP_1.py", line 64, in <module>
    Z = nn_tf(X[:,:,it]) / d

  File "C:/Users/DELL/Desktop/DP_PDE_PY/PDE_DP_1.py", line 40, in nn_tf
    x = keras.layers.BatchNormalization(batch_size = n_sample)(x)

  File "D:\Anaconda3\lib\site-packages\tensorflow\python\keras\engine\base_layer.py", line 616, in __call__
    self._maybe_build(inputs)

  File "D:\Anaconda3\lib\site-packages\tensorflow\python\keras\engine\base_layer.py", line 1951, in _maybe_build
    self.build(input_shapes)

  File "D:\Anaconda3\lib\site-packages\tensorflow\python\keras\layers\normalization.py", line 270, in build
    raise ValueError('Input has undefined rank:', input_shape)

ValueError: ('Input has undefined rank:', TensorShape(None))

**Comment by ravikyram** [comment]
Is it possible for you to try latest TF versions(`!pip install tf-nightly-2.0-preview==2.0.0.dev20190819`) and let us know whether the issue persists? .I am not seeing any issues with latest nightly versions. Thanks!

**Comment by zwenju** [comment]
![image](https://user-images.githubusercontent.com/27112868/63347035-d51e1d80-c388-11e9-8c93-232ed238d9ff.png)

Thank you, When i try your command in anaconda python3.7,   no packages is found.
I could not find a solution,   do you know the reason?  thanks

**Comment by ravikyram** [comment]
I am able to install nightly versions in my environment. Can you check it again by creating virtual environment and install using `pip install tf-nightly-2.0-preview==2.0.0.dev20190819`.I have tried  in Colab as well and I am not seeing any issues in nightly versions.Please, find the [gist ](https://colab.research.google.com/drive/1pZVwwPhaaNs1l55tfMeF1P1xOeJ7lltt)here.Thanks!

**Comment by zwenju** [comment]
Great thanks!
