### ISSUE TITLE
How to profile in tensorflow 2.0

### ISSUE THREAD

**Issue by yxleung** [tensorflow/tensorflow#31753]
I can't find the profile method of tensorflow 2.0 in google or github. How to use profiler and timeline in tensorflow 2.0. Is there any other way profile tensorflow 2.0;

**Comment by ymodak** [comment]
You may try using tensorboard for profiling.
See https://www.tensorflow.org/tensorboard/r2/tensorboard_profiling_keras

**Comment by yxleung** [comment]
> You may try using tensorboard for profiling.
> See https://www.tensorflow.org/tensorboard/r2/tensorboard_profiling_keras

Thanks for your reply!
If I am not using keras,  just a simple matrix operation,  and then use tf.function to turn into a graph.  How to use tensorboard profiling?

**Comment by yxleung** [comment]
> > You may try using tensorboard for profiling.
> > See https://www.tensorflow.org/tensorboard/r2/tensorboard_profiling_keras
> 
> Thanks for your reply!
> If I am not using keras, just a simple matrix operation, and then use tf.function to turn into a graph. How to use tensorboard profiling?

I find some information in :[](https://www.tensorflow.org/tensorboard/r2/graphs#graphs_of_tffunctions).
Maybe I know how to do it. Thank you very much.

**Comment by JestinyJie** [comment]
> > > You may try using tensorboard for profiling.
> > > See https://www.tensorflow.org/tensorboard/r2/tensorboard_profiling_keras
> > 
> > 
> > Thanks for your reply!
> > If I am not using keras, just a simple matrix operation, and then use tf.function to turn into a graph. How to use tensorboard profiling?
> 
> I find some information in :.
> Maybe I know how to do it. Thank you very much.

Could you please tell how to do it? Thanks

**Comment by Leslie-Fang** [comment]
> > > > You may try using tensorboard for profiling.
> > > > See https://www.tensorflow.org/tensorboard/r2/tensorboard_profiling_keras
> > > 
> > > 
> > > Thanks for your reply!
> > > If I am not using keras, just a simple matrix operation, and then use tf.function to turn into a graph. How to use tensorboard profiling?
> > 
> > 
> > I find some information in :.
> > Maybe I know how to do it. Thank you very much.
> 
> Could you please tell how to do it? Thanks

@JestinyJie I find a way to do the profile in TF2.0
Please refer to this link: https://stackoverflow.com/questions/56690089/how-to-graph-tf-keras-model-in-tensorflow-2-0

**Comment by ConeyLiu** [comment]
Hi, how to use profile API and profile service? The python module can't import after tensorflow.__init__.
