### ISSUE TITLE
No tf.lite.experimental.nn.bidirectional_dynamic_rnn ops is finded

### ISSUE THREAD

**Issue by banbishan** [tensorflow/tensorflow#31754]
**System information**
- Linux Ubuntu 16.04:
- TensorFlow installed from anaconda:
- TensorFlow version 1.14:

when i from tensorflow._api.v1.lite.experimental.nn import bidirectional_dynamic_rnn, i get the error:
AttributeError: module 'tensorflow._api.v1.lite.experimental.nn' has no attribute 'bidirectional_dynamic_rnn'

but i find in https://tensorflow.google.cn/lite/convert/rnn that the ops has be supported.

by the way, tf.lite.experimental.nn.dynamic_rnn can be import as https://tensorflow.google.cn/lite/convert/rnn shows.

**Provide the text output from tflite_convert**

```
module 'tensorflow._api.v1.lite.experimental.nn' has no attribute 'bidirectional_dynamic_rnn'
```

**Comment by renjie-liu** [comment]
Hi banbishan, can you use from tensorflow.lite.experimental.examples.lstm.rnn import bidirectional_dynamic_rnn instead?

**Comment by banbishan** [comment]
> Hi banbishan, can you use from tensorflow.lite.experimental.examples.lstm.rnn import bidirectional_dynamic_rnn instead?

Hi renjie-liu, thank you for you reply. No errors occurred when I use from tensorflow.lite.experimental.examples.lstm.rnn import bidirectional_dynamic_rnn instead.
