### ISSUE TITLE
tflite: incorrect quantisation scale application in unit test utils

### ISSUE THREAD

**Issue by akarmi** [tensorflow/tensorflow#31756]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes, the bug was discovered when evaluating new quantisation modes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): discoverd on Linux Ubuntu 16.04, but should be applicable to any platform where the tests are run
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below): master branch
- Python version: Python3.6
- Bazel version (if compiling from source): 0.26.1
- GCC/Compiler version (if compiling from source): GCC 5.4.0
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

**Describe the current behavior**
The quantization scale in [PerChannelQuantizeBias()](https://github.com/tensorflow/tensorflow/blob/1f61f13f8715dc26dabe46a2686216674026d812/tensorflow/lite/kernels/test_util.h#L239) in [tensorflow/lite/kernels/test_util.h](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/kernels/test_util.h) appears to be applied incorrectly. The floating point input data are multiplied by the scale value whereas they should be divided by it. The corresponding tests in [conv_test.cc](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/kernels/conv_test.cc) and [depthwise_conv_test.cc](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/kernels/depthwise_conv_test.cc), e.g. [SimplePerChannelTest](https://github.com/tensorflow/tensorflow/blob/1f61f13f8715dc26dabe46a2686216674026d812/tensorflow/lite/kernels/conv_test.cc#L1343) appear to contain the wrong expected values.

**Describe the expected behavior**
The division operation should be used to convert the floating point to quantized fixed point value and the corresponding tests changes respectively.

**Code to reproduce the issue**
N/A

**Other info / logs**
N/A

**Comment by wangtz** [comment]
Let's continue the discussion on https://github.com/tensorflow/tensorflow/pull/31757
