### ISSUE TITLE
Create GPU Delegate failed,  dequantize error

### ISSUE THREAD

**Issue by liakopyangsir** [tensorflow/tensorflow#31762]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):  Linux Ubuntu 16.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: Samsung Galaxy S10+
- TensorFlow installed from (source or binary): source 
- TensorFlow version (use command below): r1.14.0
- Python version: 3.6.3
- Bazel version (if compiling from source): 0.24.1
- GCC/Compiler version (if compiling from source): 
- CUDA/cuDNN version:
- GPU model and memory:

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
I converted my tflite model with F16 quantilization, then I create GPU Delegate to run my model,
the source code version of tensorflow is r1.14.0. I got the following error when running the inference:
Initialized TensorFlow Lite runtime.
Internal error: Failed to apply delegate: tensorflow/lite/kernels/dequantize.cc:62 op_context.input->type == kTfLiteUInt8 || op_context.input->type == kTfLiteInt8 was not true.Node number 1 (DEQUANTIZE) failed to prepare.

**Describe the expected behavior**
Tensorflow Lite can run Float16 model with GPU Delegate correctly.

**Code to reproduce the issue**
gpuDelegate = new GpuDelegate();
tfliteOptions.addDelegate(gpuDelegate);
tfliteOptions.setAllowFp16PrecisionForFp32(true);
tflite = new Interpreter(tfliteModel,tfliteOptions);

**Other info / logs**
The code and cmd to convert the model:
python freeze_graph.py --input_graph=2d-3d-match-pointnet/model_test.pb --input_checkpoint=2d-3d-match-pointnet/model_test.ckpt --output_graph=2d-3d-match-pointnet/tmp/model.pb --output_node_names=moutput

import tensorflow as tf

graph_def_file = "./model.pb"
input_arrays = ["minput"]
output_arrays = ["moutput"]

converter = tf.lite.TFLiteConverter.from_frozen_graph(graph_def_file, input_arrays, output_arrays)
converter.optimizations = [tf.lite.Optimize.DEFAULT]
converter.target_spec.supported_types = [tf.lite.constants.FLOAT16]
tflite_model = converter.convert()
open("model_quant_f16.tflite", "wb").write(tflite_model)

 I would appreciate it if you could help check this issue. thanks again.

**Comment by impjdi** [comment]
Since we added FP16 support, the condition at tensorflow/lite/kernels/ddequantize.cc now reads:

> TF_LITE_ENSURE(context, op_context.input->type == kTfLiteUInt8 ||
>                               op_context.input->type == kTfLiteInt8 ||
>                               op_context.input->type == kTfLiteInt16 ||
>                               op_context.input->type == kTfLiteFloat16);

I'm wondering whether your inference engine is actually supporting FP16 or not.  Can you confirm that you're using master's latest snapshot?

**Comment by liakopyangsir** [comment]
Thank u, my tensorflow version is r1.14.0 which is the official release and not support FP16 yet.
the latest version maybe is not stable and I got some compile errors, so I chose r1.14.0,  I will try the latest version and check again. 

BR

**Comment by Craftsman381** [comment]
I'm having the same issue! Did anyone figure this out?
