### ISSUE TITLE
[tf.data] Listing files, sampling a subset and repeating iterates over each file when shuffling is enabled

### ISSUE THREAD

**Issue by sdll** [tensorflow/tensorflow#31761]
**System information**

- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Mac OS X Mojave 10.14.6
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: n/a
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): v1.14.0-rc1-22-gaf24dc91b5 1.14.0
- Python version: 3.7.3
- Bazel version (if compiling from source): n/a
- GCC/Compiler version (if compiling from source): n/a
- CUDA/cuDNN version: n/a
- GPU model and memory: n/a

**Describe the current behavior**

Testing the tf.data setup, I want to select a subset of the data to read from disc. Doing that with `tf.data.Dataset.list_files("*", shuffle=True).take(2)` iterates over the entire folder despite the explicit `take`.

**Describe the expected behavior**

When shuffling is enabled in `tf.data.Dataset.list_files`, I should be able to repeat the random sample indefinitely.

**Code to reproduce the issue**

First, create dummy data.

```shell
mkdir scratchpad
cd scratchpad
for i in {0..100}; do touch $i; done
```

Then, in IPython,

```python
import os
import tensorflow as tf

sess = tf.InteractiveSession()
tf.global_variables_initializer().run()

it = (
    tf.data.Dataset.list_files(os.path.join("*"))
    .take(2)
    .repeat(None)
    .make_one_shot_iterator()
    .get_next()
)

[sess.run(it) for _ in range(12)]
```

The above works as expected with shuffling disabled:

```python
import os
import tensorflow as tf

sess = tf.InteractiveSession()
tf.global_variables_initializer().run()

it = (
    tf.data.Dataset.list_files(os.path.join("*"), shuffle=False)
    .take(2)
    .repeat(None)
    .make_one_shot_iterator()
    .get_next()
)

[sess.run(it) for _ in range(12)]
```

**Comment by oanush** [comment]
Kindly find the [gist](https://colab.sandbox.google.com/drive/1lJcKSBoAtIzDfvMzRMyplRdr4MIR9n9y#scrollTo=MmMVwI7XrefD) of colab when tried executing the given codes.Thanks!

**Comment by jsimsa** [comment]
Your input pipeline is currently repeatedly picking a pair of random files. If you want to instead repeat the two randomly selected files infinitely, put `cache` between `take` and `repeat`.

**Comment by sdll** [comment]
@jsimsa, thanks for your response! I wonder whether it is ok that the example without shuffling works as expected without caching, instead of going over the consecutive pairs of files. Shouldn't caching be enabled by default if there is a repeat coming after shuffling, like it is for the in-order processing?

**Comment by jsimsa** [comment]
When shuffling is enabled, you need to list all files in order to pick two randomly. 

The input pipeline without `cache` repeatedly randomly samples two files. The input pipeline with `cache` repeats the same two (randomly sampled) files. I don't think that caching should be enabled by default because the behaviors are different (and both meaningful).

**Comment by sdll** [comment]
Agreed. Could the description of this behavior be added to the [official docs](https://www.tensorflow.org/api_docs/python/tf/data/Dataset#take) at least?

**Comment by jsimsa** [comment]
I am not sure what exactly would you like to be added (as documentation of each tf.data transformation should make sense on its own), but I am happy to review a PR with your suggestion.
