### ISSUE TITLE
Protocol "https" not supported or disabled in libcurl

### ISSUE THREAD

**Issue by snathicktechno** [tensorflow/tensorflow#31764]
Hi Guys,
 
can anyone help me with the following issue

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- TensorFlow installed from source.
- TensorFlow version: r1.11
- Python version: 2.7.12
- GCC/Compiler version (if compiling from source): GNU 5.4.0
**Describe the problem**

from top directory of tensorflow iam running the script as follows
./tensorflow/tools/ci_build/linux/cmake/run.sh 
 iam stuck with the following error

error: downloading 'https://mirror.bazel.build/ufpr.dl.sourceforge.net/project/giflib/giflib-5.1.4.tar.gz' failed
         status_code: 1
         status_string: "Unsupported protocol"
         log:
         --- LOG BEGIN ---
         Protocol "https" not supported or disabled in libcurl
like above error there are number of  files that are being not downloaded because of that iam getting build error.

this is my curl version iam using 

curl -V
curl 7.66.0-DEV (x86_64-pc-linux-gnu) libcurl/7.66.0-DEV OpenSSL/1.0.2g zlib/1.2.8
Release-Date: [unreleased]
Protocols: dict file ftp ftps gopher http https imap imaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS HTTPS-proxy IPv6 Largefile libz NTLM NTLM_WB SSL TLS-SRP UnixSockets

Thank you
Snathick

**Comment by oanush** [comment]
> Hi Guys,
> 
> can anyone help me with the following issue
> 
> **System information**
> 
> * OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
> * TensorFlow installed from source.
> * TensorFlow version: r1.11
> * Python version: 2.7.12
> * GCC/Compiler version (if compiling from source): GNU 5.4.0
>   **Describe the problem**
> 
> from top directory of tensorflow iam running the script as follows
> ./tensorflow/tools/ci_build/linux/cmake/run.sh
> iam stuck with the following error
> 
> error: downloading 'https://mirror.bazel.build/ufpr.dl.sourceforge.net/project/giflib/giflib-5.1.4.tar.gz' failed
> status_code: 1
> status_string: "Unsupported protocol"
> log:
> --- LOG BEGIN ---
> Protocol "https" not supported or disabled in libcurl
> like above error there are number of files that are being not downloaded because of that iam getting build error.
> 
> this is my curl version iam using
> 
> curl -V
> curl 7.66.0-DEV (x86_64-pc-linux-gnu) libcurl/7.66.0-DEV OpenSSL/1.0.2g zlib/1.2.8
> Release-Date: [unreleased]
> Protocols: dict file ftp ftps gopher http https imap imaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp
> Features: AsynchDNS HTTPS-proxy IPv6 Largefile libz NTLM NTLM_WB SSL TLS-SRP UnixSockets
> 
> Thank you
> Snathick

@snathicktechno ,
Can you let us know from which top directory are you running the script ?Thanks

**Comment by snathicktechno** [comment]
Hi oanush, 

I resolved the above error and i now stuck with the following error 

OS Platform and Distribution (e.g., Linux Ubuntu 16.04)
TensorFlow installing from source using cmake
TensorFlow version: r1.0
Python version: 2.7.12, 3.5 also
GCC/Compiler version (if compiling from source): GNU 5.4.0

the steps i followed 
cd tensorflow
./tensorflow/tools/ci_build/linux/cmake/run.sh which is calling CMakeLists.txt at path tensorflow-r1.0/tensorflow/contrib/cmake/CMakeLists.txt

My Environment cmake probing

+ rm -rf build
+ mkdir -p build
+ pushd build
~/Downloads/tensorflow-r1.1/build ~/Downloads/tensorflow-r1.1
+ cmake -pthread -DCMAKE_BUILD_TYPE=Release ../tensorflow/contrib/cmake
-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Performing Test COMPILER_OPT_ARCH_NATIVE_SUPPORTED
-- Performing Test COMPILER_OPT_ARCH_NATIVE_SUPPORTED - Success
-- Found PythonInterp: /usr/bin/python (found version "2.7.12") 
-- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython2.7.so (found version "2.7.12") 
-- Found SWIG: /usr/bin/swig3.0 (found version "3.0.8") 
-- Configuring done
-- Generating done
-- Build files have been written to: /home/sadiq/Downloads/tensorflow-r1.1/build

iam stuck with following error

CMakeFiles/Makefile2:79: recipe for target 'CMakeFiles/tf_python_build_pip_package.dir/rule' failed
make[1]: *** [CMakeFiles/tf_python_build_pip_package.dir/rule] Error 2
Makefile:118: recipe for target 'tf_python_build_pip_package' failed
make: *** [tf_python_build_pip_package] Error 2

can you help me to resolve this issue

Thank you
Snathick

**Comment by oanush** [comment]
@snathicktechno ,
Can you please install TF using [Bazel](https://www.tensorflow.org/install/source) and not cmake? Thanks!

**Comment by oanush** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
