### ISSUE TITLE
Build failure seems related with C++14 support of GCC 4.8 w.r.t. MLIR dependency

### ISSUE THREAD

**Issue by jackwish** [tensorflow/tensorflow#31760]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): source
- TensorFlow version: master
- Python version: 3.6
- Installed using virtualenv? pip? conda?: NA, building
- Bazel version (if compiling from source): 0.26.1
- GCC/Compiler version (if compiling from source): 4.8
- CUDA/cuDNN version: NA
- GPU model and memory: NA

**Describe the problem**

Failed to build latest TF from source with command (which works fine on branch `r1.14`, and works on `master` maybe one month ago):
```sh
bazel build --jobs=8 -c opt --copt=-mavx --copt=-mavx2 --copt=-mfma --copt=-msse4.1 --copt=-msse4.2 --config=noaws --config=nogcp --config=nohdfs --config=noignite --config=nokafka --config=nonccl //tensorflow/tools/pip_package:build_pip_package
```

Seems c++14 support is required when building TF (with MLIR dependency introduced), while I am using GCC 4.8, which doesn't include C++14 support. I am wondering what is the recommended GCC version? I see the official builds are marked with GCC 4.8. Do you guys encounter this issue?

The failed log:
```
ERROR: /home/wzh/.cache/bazel/_bazel_wzh/7830c7af24b3349eb6de8dd12d5e8378/external/local_config_mlir/BUILD:418:1: C++ compilation of rule '@local_config_mlir//:Support' failed (Exit 1)
gcc-4.8: error: unrecognized command line option '-std=c++14'
Target //tensorflow/tools/pip_package:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.
```

**Comment by jackwish** [comment]
Update: can build when switched to GCC 7. The question is can GCC 4.8 build it.

Thanks.

**Comment by angersson** [comment]
I think @av8ramit can provide more context on this, but the GCC 4.8 we're using is part of a devtoolset package which uses 4.8 as a base and pulls in newer features. Most users should start using GCC 7 if possible.

@av8ramit, do you know if we're planning to publish more information about this?

**Comment by av8ramit** [comment]
So the gcc we use as a base is 5.4, but we build our presubmits using a toolchain which has gcc 7.3.1. If you use our custom-op-gpu docker container that may resolve this.

`tensorflow/tensorflow:custom-op-ubuntu16`

Toolchain flag: 
```
--crosstool_top=//third_party/toolchains/preconfig/ubuntu16.04/gcc7_manylinux2010-nvcc-cuda10.0:toolchain
```

**Comment by nikenj** [comment]
[https://www.tensorflow.org/install/source#tested_build_configurations](url)  in this page , the tf 1.14 is assign gcc 4.8 , if you suggest gcc 7 , pls change the document, thx ;

**Comment by jackwish** [comment]
Thank you everyone, that helps a lot.

I suggest to move the toolchain related documents (tool version, ABI flags and so on) to a section maybe name as **Requirements** or **Environment Setup**, and put it around https://www.tensorflow.org/install/source#install_python_and_the_tensorflow_package_dependencies. Or maybe let the python dependency document as part of the **Requirements** or **Environment Setup**.

I remember that when I was new to TensorFlow, the Python version (3.7 is not supported at that time) and the GCC tool version made me having a bad experience.

I am not closing this issue as it is no longer a problem for me. But it will be great if the building document can improve.

Thank you.

**Comment by jwakely** [comment]
@angersson 

> but the GCC 4.8 we're using is part of a devtoolset package which uses 4.8 as a base and pulls in newer features.

That's not how devtoolset works. The devtoolset GCC is a newer compiler, period. It's not "4.8 plus new features". The clever part is that it links to the `libstdc++.so` from an older GCC and _also_ an extra `libstdc++_nonshared.a` with symbols for newer features. But the actual `g++` compiler is still not "GCC 4.8".

**Comment by angersson** [comment]
Thanks for the clarification, @jwakely! I updated my comment earlier to make sure I don't confuse anyone.
