### ISSUE TITLE
failed to build tensorflow from source

### ISSUE THREAD

**Issue by samhithaaaa** [tensorflow/tensorflow#31779]
![Screen Shot 2019-08-19 at 4 29 26 PM](https://user-images.githubusercontent.com/36496141/63307405-1fc56a00-c2a3-11e9-857f-591e054547ad.png)
![Screen Shot 2019-08-19 at 4 30 07 PM](https://user-images.githubusercontent.com/36496141/63307414-26ec7800-c2a3-11e9-9453-59ceccc56f03.png)
Tried building tensorflow from source but getting this error.This tensorflow version-1.10,bazel-0.15,aarm64 bit architecture,gcc version-7.4.Could anyone please help?

**Comment by oanush** [comment]
@samhithaaaa ,
Can you please refer this [link](https://www.tensorflow.org/install/source)?
Provide the exact sequence of commands / steps that you executed before running into the problem.
Thanks!

**Comment by samhithaaaa** [comment]
Yes I am following this link only

**Comment by oanush** [comment]
@samhithaaaa ,
Can you please downgrade gcc version to 4.8, see this [link](https://www.tensorflow.org/install/source#linux). Thanks!

**Comment by oanush** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
