### ISSUE TITLE
TensorFlow Install 'protoc' is not recognized 

### ISSUE THREAD

**Issue by AeroWRX** [tensorflow/tensorflow#31771]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10 64bit
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): pip wheel
- TensorFlow version: 1.14
- Python version: 3.7
- Installed using virtualenv? pip? conda?: PIP

I am following Tensorflow install guide, but at the step where I need to run Protobuf  i get an error.
`protoc object_detection/protos/anchor_generator.proto --python_out=.`

> 'protoc' is not recognized as an internal or external command, operable program or batch file.

I am using Python 3.7 stock (not Anaconda) with Virtualenv

**Comment by gadagashwini** [comment]
@AeroWRX,
Provide the exact sequence of commands / steps that you executed before running into the problem. Thanks!

**Comment by gadagashwini** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
