### ISSUE TITLE
[tflite] why not dynamic library for arm?

### ISSUE THREAD

**Issue by laohur** [tensorflow/tensorflow#31789]

**Comment by gadagashwini** [comment]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- TensorFlow installed from (source or binary):
- TensorFlow version (or github SHA if from source):


**Provide the text output from tflite_convert**

```
# Copy and paste here
```

Also, please include a link to a GraphDef or the model if possible.

**Any other info / logs**

Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by gadagashwini** [comment]
Please fill the template for better understanding of the issue.

**Comment by laohur** [comment]
solved，how to delete it

**Comment by gadagashwini** [comment]
@laohur. Glad it solved. 
No need to delete it. Thanks!
