### ISSUE TITLE
how to convert tflite model to float 16?

### ISSUE THREAD

**Issue by allenling** [tensorflow/tensorflow#31784]
i run tf v1.14

well, i can hardly find some easy, usable codes to convert my tflite model to fp16(int8 is easy)

i read tf official post training quantization [docs](https://www.tensorflow.org/lite/performance/post_training_quantization), but i can not run this

```
import tensorflow as tf
converter = tf.lite.TFLiteConverter.from_saved_model(saved_model_dir)
converter.optimizations = [tf.lite.Optimize.DEFAULT]
converter.target_spec.supported_types = [tf.lite.constants.FLOAT16]
tflite_quant_model = converter.convert()
```
there no FLOAT16 in tensorflow._api.v1.lite.constants, just 
```
FLOAT = dtypes.float32
INT32 = dtypes.int32
INT64 = dtypes.int64
STRING = dtypes.string
QUANTIZED_UINT8 = dtypes.uint8
INT8 = dtypes.int8
```

and i found this [article,](https://medium.com/@fanzongshaoxing/post-training-quantization-of-tensorflow-model-to-fp16-8d66b9dfa77f) which might be help, but too complicated.

if i miss something, remind me please.

**Comment by anilsathyan7** [comment]
Faced similar problem ....
Try tf-nightly (1.15.0-dev20190821)

(verified with google colab)
```
! pip uninstall -y tensorflow
! pip install -U tf-nightly
```

I tried with a keras file and the following code  worked..

```
import tensorflow as tf
converter = tf.lite.TFLiteConverter.from_keras_model_file('net.h5')
converter.optimizations = [tf.lite.Optimize.DEFAULT]
converter.target_spec.supported_types = [tf.lite.constants.FLOAT16]
tflite_model = converter.convert()
open("bilinear_fin_munet_fp16.tflite", "wb").write(tflite_model)
```

Looks like there are some operator issues (even within tf 2.0 versions) across different versions

**Comment by allenling** [comment]
@anilsathyan7 
well, master branch support fp16 conversion, checkout master and run tflite_convtert

but run gpu delegate not so easy

**Comment by michael0905** [comment]
@allenling 
same problem ! Have you solved this ?

**Comment by anilsathyan7** [comment]
Has anyone figure out how to atleast use [benchmark_tool](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/tools/benchmark#tflite-model-benchmark-tool) with gpu-fp16 on android? When i use the option allow_fp16 with a model converted to fp16 by the above methods it shows many errors due to shapes of conv, depthwise connv and dequantize operators etc. Is there a sample model(proper fp16 converted) that we can atleast test with benchmark tool?

**Comment by depthwise** [comment]
And in 2.0 there's no `tf.lite.constants.FLOAT16` at all. And no indication where it went in the documentation.

**Comment by depthwise** [comment]
`tf.float16` works fine for the above. But there's no speedup at all. In fact the numbers are so close that I strongly suspect the model inference is actually done in fp32

**Comment by ArtemisZGL** [comment]
i try to install tf2.0 and nightly, both show that there no FLOAT16 in tensorflow._api.v2.lite.constants. Even I run the code in [colab](https://colab.research.google.com/github/tensorflow/tensorflow/blob/master/tensorflow/lite/g3doc/performance/post_training_float16_quant.ipynb), it still not work. Does any one konw how to solve this ?

**Comment by depthwise** [comment]
@ArtemisZGL use tf.float16 instead. Works as intended, the model size is one half. That said, I did not get any speedup at all from fp16 when running TFLite on Google Pixel 3. Doesn't seem like fp16 is quite "there" yet.

**Comment by liyunlu0618** [comment]
@gargn 

Please advise what's the correct way of using lite.constants in tf2.0. Thanks!

**Comment by gargn** [comment]
The document describing the official changes in TFLiteConverter between 1.X and 2.0 is available [here](https://www.tensorflow.org/lite/convert/python_api#summary_of_changes_in_python_api_between_1x_and_20_). It includes a [section](https://www.tensorflow.org/lite/convert/python_api#liteconstants) on the mapping between the 1.X and 2.0 types.

**Comment by anilsathyan7** [comment]
Here is my custom fp16 converted plain keras model...
I changed the model type and weights manually; but i'am unable to convert to float16-tflite in tensorflow 1.15.0, using the aforementioned script.

It's showing error with input layer(placeholder) data type.
`I tensorflow/lite/toco/import_tensorflow.cc:193] Unsupported data type in placeholder op: 19
F tensorflow/lite/toco/import_tensorflow.cc:2679] Check failed: status.ok() Unexpected value for attribute 'T'. Expected 'DT_FLOAT'
Aborted (core dumped)`

If i try with normal float32 keras files, it is introducing 'dequantize ' operators; but the conversion works properly(input is still float32) 
Did anybody face this issue and how can it be solved? 
Will it work if i use tf/tf.keras instead?

[sm.h5.zip](https://github.com/tensorflow/tensorflow/files/3863441/sm.h5.zip)

**Comment by yongqyu** [comment]
> i try to install tf2.0 and nightly, both show that there no FLOAT16 in tensorflow._api.v2.lite.constants. Even I run the code in [colab](https://colab.research.google.com/github/tensorflow/tensorflow/blob/master/tensorflow/lite/g3doc/performance/post_training_float16_quant.ipynb), it still not work. Does any one konw how to solve this ?

In my case, `tf.compat.v1.lite.constants.FLOAT16` is worked in TF2.0

**Comment by yongqyu** [comment]
@ArtemisZGL @depthwise https://www.tensorflow.org/lite/convert/python_api#liteconstants
In here, there is no `tf.lite.constants` in tf2.0.
And Im not sure to use the `tf.compat.v1.lite.constants`. You can try it.

**Comment by alietestep** [comment]
in tensorflow 2.0:
fo float ops:
      converter = tf.lite.TFLiteConverter.from_keras_model(lite_model)
      converter.optimizations = [tf.lite.Optimize.OPTIMIZE_FOR_LATENCY]
      converter.target_spec.supported_types = [tf.compat.v1.lite.constants.FLOAT16]

      tflite_quant_model = converter.convert()
and there not so much diffrence on performance!!!

for int ops like INT8, UINT8, INT32, ...:
 needs aditional steps (represantative datasets) for finding min and max values.

     converter2 = tf.lite.TFLiteConverter.from_keras_model(lite_model) 
     converter2.optimizations = [tf.lite.Optimize.OPTIMIZE_FOR_LATENCY]
     converter2.target_spec.supported_types = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]

    converter.inference_input_type = [tf.int8] 
    converter.inference_output_type = [tf.int8]
    converter.representative_dataset=rep_data_gen

     tflite_quant_model = converter2.convert()

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.

**Comment by laisimiao** [comment]
> i run tf v1.14
> 
> well, i can hardly find some easy, usable codes to convert my tflite model to fp16(int8 is easy)
> 
> i read tf official post training quantization [docs](https://www.tensorflow.org/lite/performance/post_training_quantization), but i can not run this
> 
> ```
> import tensorflow as tf
> converter = tf.lite.TFLiteConverter.from_saved_model(saved_model_dir)
> converter.optimizations = [tf.lite.Optimize.DEFAULT]
> converter.target_spec.supported_types = [tf.lite.constants.FLOAT16]
> tflite_quant_model = converter.convert()
> ```
> 
> there no FLOAT16 in tensorflow._api.v1.lite.constants, just
> 
> ```
> FLOAT = dtypes.float32
> INT32 = dtypes.int32
> INT64 = dtypes.int64
> STRING = dtypes.string
> QUANTIZED_UINT8 = dtypes.uint8
> INT8 = dtypes.int8
> ```
> 
> and i found this [article,](https://medium.com/@fanzongshaoxing/post-training-quantization-of-tensorflow-model-to-fp16-8d66b9dfa77f) which might be help, but too complicated.
> 
> if i miss something, remind me please.

Could you tell me hoe to convert into int8?
