### ISSUE TITLE
The current session will be closed and a new session will be created. Error: Stream IDs exhausted

### ISSUE THREAD

**Issue by zhangwj0101** [tensorflow/tensorflow#31787]
**System information**
TensorFlow:
- OS Platform and Distribution (e.g., centos7):
- TensorFlow installed from ( binary):
- TensorFlow version (1.8):

in Distrubuted TensorFlow, train 38 days, we get the error " **INFO:tensorflow:An error was raised. This may be due to a preemption in a connected worker or parameter server. The current session will be closed and a new session will be created. Error: Stream IDs exhausted** " , 
any better to solve this quesution?

**Comment by ravikyram** [comment]
In order to expedite the trouble-shooting process, please provide a minimal code snippet to reproduce the issue reported here. Thanks!

**Comment by ravikyram** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Comment by zhangwj0101** [comment]
> Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

> In order to expedite the trouble-shooting process, please provide a minimal code snippet to reproduce the issue reported here. Thanks!

no other exception info, we just get the information from tensorflow log "INFO:tensorflow:An error was raised. This may be due to a preemption in a connected worker or parameter server. The current session will be closed and a new session will be created. Error: Stream IDs exhausted"

**Comment by zhangwj0101** [comment]
> In order to expedite the trouble-shooting process, please provide a minimal code snippet to reproduce the issue reported here. Thanks!

@ravikyram only get error info "The current session will be closed and a new session will be created. Error: Stream IDs exhausted"

**Comment by ravikyram** [comment]
In order to expedite the trouble-shooting process, please provide a minimal standalone code to reproduce the issue reported here.It helps us to debug your issue faster. Thanks!
