### ISSUE TITLE
Build tensorflow lite for aarch64: Error in script download_dependencies.sh 

### ISSUE THREAD

**Issue by Stormreaver** [tensorflow/tensorflow#31799]
**System information**
- OS Platform :Linux Ubuntu 16.04
- TensorFlow version: Release 1.14.0
When I run the script ./tensorflow/lite/tools/make/download_dependencies.sh  I am getting following error:

downloading http://mirror.tensorflow.org/bitbucket.org/eigen/eigen/get/a0d250e79c79.tar.gz
./tensorflow/lite/tools/make/download_dependencies.sh: line 64: curl: command not found

gzip: stdin: unexpected end of file
tar: Child returned status 1
tar: Error is not recoverable: exiting now

**Comment by jwoolston** [comment]
I have the same behavior, also trying to build Release 1.14.0

```
user@computer:~/Work/GIT/tensorflow$ ./tensorflow/lite/tools/make/download_dependencies.sh 
downloading http://mirror.tensorflow.org/bitbucket.org/eigen/eigen/get/a0d250e79c79.tar.gz

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
```

**Comment by ravikyram** [comment]
Looks like duplicate #https://github.com/tensorflow/tensorflow/issues/28926.Thanks!

**Comment by ravikyram** [comment]
@Stormreaver 

Can you please confirm if the issue still persists.Thanks!

**Comment by Stormreaver** [comment]
I fixed this issue by using master code
