### ISSUE TITLE
ImportError: cannot import name pywrap_tensorflow

### ISSUE THREAD

**Issue by wchuanghard** [tensorflow/tensorflow#3179]
### Environment info
Operating System: Mac OS X 10.10

### Steps to reproduce
1.
%matplotlib inline
%load_ext autoreload
%autoreload 2
import matplotlib
import matplotlib.pyplot as plt
import matplotlib.cm as cm
from matplotlib import gridspec
2.
import sys
sys.path.append('..')
3.
from tasks import *

input_dim=10
output_dim=10

sess = tf.InteractiveSession()

cell = NTMCell(input_dim=input_dim, output_dim=output_dim)
ntm = NTM(cell, sess, 1, 10, 100, forward_only=True)
ntm.load('../checkpoint', 'copy')

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-18-0a6f382608e4> in <module>()
----> 1 from tasks import *
      2 
      3 input_dim=10
      4 output_dim=10
      5 

/Users/William_Chuang/Documents/NTM/NTM-tensorflow-master/tasks/__init__.py in <module>()
----> 1 from copy import *
      2 from recall import *

/Users/William_Chuang/Documents/NTM/NTM-tensorflow-master/tasks/copy.py in <module>()
      2 import time
      3 import numpy as np
----> 4 import tensorflow as tf
      5 from random import randint
      6 

/Users/William_Chuang/cuting_edge/anaconda/lib/python2.7/site-packages/tensorflow/__init__.py in <module>()
     21 from __future__ import print_function
     22 
---> 23 from tensorflow.python import *

/Users/William_Chuang/cuting_edge/anaconda/lib/python2.7/site-packages/tensorflow/python/__init__.py in <module>()
     46 _default_dlopen_flags = sys.getdlopenflags()
     47 sys.setdlopenflags(_default_dlopen_flags | ctypes.RTLD_GLOBAL)
---> 48 from tensorflow.python import pywrap_tensorflow
     49 sys.setdlopenflags(_default_dlopen_flags)
     50 

ImportError: cannot import name pywrap_tensorflow

**Comment by aselle** [comment]
Please provide more information.
How did you install tensorflow? is it from binary or source? If from binary, which pip package? We typically only support and test on Mac OS X 10.11.

**Comment by aselle** [comment]
Automatically closing due to lack of recent activity. Please reopen when further information becomes available.

**Comment by Madhusakth** [comment]
Hi, 
I am trying to use tensorflow in ipython, Mac and I got the following error

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-7-836278fb1688> in <module>()
      1 import sys
      2 sys.path.append('/Users/vasanti/miniconda2/lib/python2.7/site-packages')
----> 3 from keras.utils import np_utils
      4 import theano
      5 import theano.tensor as T

/Users/vasanti/miniconda2/lib/python2.7/site-packages/keras/__init__.py in <module>()
      1 from __future__ import absolute_import
      2 
----> 3 from . import activations
      4 from . import applications
      5 from . import backend

/Users/vasanti/miniconda2/lib/python2.7/site-packages/keras/activations.py in <module>()
      2 import six
      3 import warnings
----> 4 from . import backend as K
      5 from .utils.generic_utils import deserialize_keras_object
      6 from .engine import Layer

/Users/vasanti/miniconda2/lib/python2.7/site-packages/keras/backend/__init__.py in <module>()
     71 elif _BACKEND == 'tensorflow':
     72     sys.stderr.write('Using TensorFlow backend.\n')
---> 73     from .tensorflow_backend import *
     74 else:
     75     raise ValueError('Unknown backend: ' + str(_BACKEND))

/Users/vasanti/miniconda2/lib/python2.7/site-packages/keras/backend/tensorflow_backend.py in <module>()
----> 1 import tensorflow as tf
      2 from tensorflow.python.training import moving_averages
      3 from tensorflow.python.ops import tensor_array_ops
      4 from tensorflow.python.ops import control_flow_ops
      5 from tensorflow.python.ops import functional_ops

/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tensorflow/__init__.py in <module>()
     22 
     23 # pylint: disable=wildcard-import
---> 24 from tensorflow.python import *
     25 # pylint: enable=wildcard-import
     26 

/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tensorflow/python/__init__.py in <module>()
     49 import numpy as np
     50 
---> 51 from tensorflow.python import pywrap_tensorflow
     52 
     53 # Protocol buffers

ImportError: cannot import name pywrap_tensorflow

It will be great if someone could help me with this!
Thanks in advance!

**Comment by raghavvikram** [comment]
Is it supported on mac os 10.14.5 now??

**Comment by raghavvikram** [comment]
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-18-4d957316d630> in <module>()
     13 # Import Mask RCNN
     14 sys.path.append(ROOT_DIR)  # To find local version of the library
---> 15 from mrcnn import utils
     16 import mrcnn.model as modellib
     17 from mrcnn import visualize

/Users/raghavv/Desktop/GREAT-LAKES-AIML/capstone/experiments/Mask_RCNN/mrcnn/utils.py in <module>()
     14 import random
     15 import numpy as np
---> 16 import tensorflow as tf
     17 import scipy
     18 import skimage.color

//anaconda2/lib/python2.7/site-packages/tensorflow/__init__.py in <module>()
     26 
     27 # pylint: disable=g-bad-import-order
---> 28 from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
     29 from tensorflow.python.tools import module_util as _module_util
     30 

//anaconda2/lib/python2.7/site-packages/tensorflow/python/__init__.py in <module>()
     47 import numpy as np
     48 
---> 49 from tensorflow.python import pywrap_tensorflow
     50 
     51 # Protocol buffers

ImportError: cannot import name pywrap_tensorflow
