### ISSUE TITLE
TensorFlow with Cuda 7.5 on Ubuntu 15.4?

### ISSUE THREAD

**Issue by tunguz** [tensorflow/tensorflow#318]
Hi,

I have not been able to install GPU TensorFlow on my Ubuntu 15.04 workstation because it seems to require Cuda 7.0, while I am running Cuda 7.5. As far as I can tell there are no Cuda 7.0 installs available for Ubuntu 15.04. Are there any patches/upgrades that will make it possible for me to use TensorFlow on my system? Or do I right now have to downgrade my Ubuntu in order to be able to work with it?

Thanks,

Bojan

**Comment by ebrevdo** [comment]
You can try the Ubuntu 14.04 deb, or use the tgz installer here:

https://developer.nvidia.com/cuda-toolkit-70

under the "Linux x86" tab.

**Comment by vrv** [comment]
De-duping with https://github.com/tensorflow/tensorflow/issues/20
