### ISSUE TITLE
RuntimeError: Quantization not yet supported for op: FAKE_QUANT

### ISSUE THREAD

**Issue by DocDriven** [tensorflow/tensorflow#31802]
**System information**

- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- TensorFlow installed from (source or binary): Docker image latest-gpu-py3
- TensorFlow version (use command below): 1.14
- Python version: 3.6
- GPU model and memory: RTX 2080 Ti

**Describe the current behavior**

I have trained an autoencoder and want to convert it to a tflite model. I successfully froze the graph and was able to convert the non-quantized 32-bit-float version. When trying to convert the very same frozen graph file with the uint8 option, I get an error:

RuntimeError: Quantization not yet supported for op: FAKE_QUANT

**Describe the expected behavior**

The frozen model does not seem to be corrupted because I was able to deploy the other version successfully. FAKE_QUANT should inherently be supported.

**Code to reproduce the issue**

Conversion was attempted with:

```
converter = tf.lite.TFLiteConverter.from_frozen_graph(graph_def_file, inputs, outputs)
converter.representative_dataset = representative_dataset_gen
converter.target_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
converter.inference_input_type = tf.uint8
converter.inference_output_type = tf.uint8
converter.optimizations = [tf.lite.Optimize.DEFAULT]

tflite_model = converter.convert()
```

**Other info / logs**

The error traceback:
```

INFO: Initialized TensorFlow Lite runtime.
Traceback (most recent call last):
  File "train_and_save.py", line 289, in <module>
    vae.create_tflite_model()
  File "train_and_save.py", line 249, in create_tflite_model
    tflite_model = converter.convert()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/lite/python/lite.py", line 908, in convert
    inference_output_type)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/lite/python/lite.py", line 200, in _calibrate_quantize_model
    inference_output_type, allow_float)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/lite/python/optimize/calibrator.py", line 78, in calibrate_and_quantize
    np.dtype(output_type.as_numpy_dtype()).num, allow_float)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/lite/python/optimize/tensorflow_lite_wrap_calibration_wrapper.py", line 115, in QuantizeModel
    return _tensorflow_lite_wrap_calibration_wrapper.CalibrationWrapper_QuantizeModel(self, input_py_type, output_py_type, allow_float)
RuntimeError: Quantization not yet supported for op: FAKE_QUANT
```

If it helped, I could provide the frozen graph file.

**Comment by DocDriven** [comment]
For clarification, I am not using some fancy layers, just simple dense layers:

```
def build_model(inputs):

    fc_layer = tf.compat.v1.layers.dense
    dims = [90, 40, 10]

    with tf.name_scope('model'):
        x = tf.identity(inputs, name='x')
	outputs = x

	# encoder
	for i, size in enumerate(dims[1:]):
		outputs = fc_layer(outputs, size, name=str(i + 1), activation=tf.nn.leaky_relu)
			
	# decoder
	for i, size in enumerate(dims[-2:0:-1], len(dims)):
		outputs = fc_layer(outputs, size, name=str(i), activation=tf.nn.leaky_relu)
			
	# prediction
	outputs = fc_layer(outputs, dims[0], name=str(2*(len(dims) - 1)), activation=None)
	y = tf.identity(outputs, name='y')

    with tf.name_scope('loss'):
	recon_err = tf.reduce_sum(tf.abs(x - y), axis=1)
	total_loss = tf.reduce_mean(recon_err)
```
@liyunlu0618 
I have tried this with different activation functions, as a similar keras model does seem to have problems with the leaky_relu activation function. Unfortunately, this is not the case here and I get the same error.

I have attached the frozen graph protocol buffer, so that you can try out the conversion yourself.

[frozen.tar.gz](https://github.com/tensorflow/tensorflow/files/3530849/frozen.tar.gz)

**Comment by liyunlu0618** [comment]
It's weird that you have FAKE_QUANT in your original graph. Did you use the quantization rewriter when you train you model? It's not supposed to be used together with post-training integer quantization.

Maybe try to figure out where the fake quant op comes from first and get rid of it.

**Comment by Nhiem** [comment]
Hi DocDriven, liyunlu0618, and Everyone..  Is there a solution for this issue? I have the same issue... For my experiment, I took the Keras model from the @fchollet reference model train on mnist.. During training I apply quantization aware model for all layer (image attached), then I did Post Quantization 8bit Integer only I show the error unsupport fake quantize (attached second image) 

Anyone could help for solve this issue really appreciate ??
1 image 
![image](https://user-images.githubusercontent.com/45351965/98456620-e8e6b700-21ba-11eb-9740-9b7f87fb7de3.png)

2 image 
![image](https://user-images.githubusercontent.com/45351965/98456681-880bae80-21bb-11eb-8ae7-260ef1b09991.png)

**Comment by liyunlu0618** [comment]
Since your entire model is trained with QAT, you don't need post-training quantization. Try remove all optimization related options and re-convert your model.

**Comment by Nhiem** [comment]
@liyunlu0618 Thank you a lot for your answers !!

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.
