### ISSUE TITLE
Import Tensorflow Could not find 'cudart64_100.dll' - Model repository incompatible with CUDA 10.1

### ISSUE THREAD

**Issue by AeroWRX** [tensorflow/tensorflow#31808]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10 64bit
- TensorFlow installed from (source or binary): piwheels
- TensorFlow version: 1.14
- Python version: 3.7
- Installed using virtualenv? pip? conda?: Conda
- CUDA/cuDNN version: CUDA 10.1 / cuDNN 10.1
- GPU model and memory: Nvidia P3200

>  80               "environment variable. Download and install CUDA %s from "
>      81               "this URL: https://developer.nvidia.com/cuda-90-download-archive"
> ---> 82               % (build_info.cudart_dll_name, build_info.cuda_version_number))
>      83 
>      84       if hasattr(build_info, "cudnn_dll_name") and hasattr(
> 
> ImportError: Could not find 'cudart64_100.dll'. TensorFlow requires that this DLL be installed in a directory that is named in your %PATH% environment variable. Download and install CUDA 10.0 from this URL: https://developer.nvidia.com/cuda-90-download-archive
> **Provide the exact sequence of commands / steps that you executed before running into the problem**

It seems like  C:\...\.conda\envs\tensorflow1\Lib\site-packages\tensorflow\python\platform\self_check.py runs with ".cuda_version_number" that is locked to CUDA 10.0 looking for cudart64_100.dll when the latest CUDA version is 10.1. The Tensorflow github model repository (https://github.com/tensorflow/models) is still looking for CUDA version 10.0's  cudart64_100.dll while the CUDA 10.1 has  cudart64_101.dll. Because of this code below, Import Tensorflow will fail the self check each time.

```
        try:
          ctypes.WinDLL(build_info.cudart_dll_name)
        except OSError:
          raise ImportError(
              "Could not find %r. TensorFlow requires that this DLL be "
              "installed in a directory that is named in your %%PATH%% "
              "environment variable. Download and install CUDA %s from "
              "this URL: https://developer.nvidia.com/cuda-90-download-archive"
              % (build_info.cudart_dll_name, build_info.cuda_version_number))
```

**Comment by ravikyram** [comment]
@AeroWRX 
Can you please check by installing with CUDA 10.0 .Thanks!

**Comment by ravikyram** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
