### ISSUE TITLE
AutoGraph Map Infinite Loop

### ISSUE THREAD

**Issue by ilhamfp** [tensorflow/tensorflow#31823]
**System information**
I used google colab. [Here's the link to reproduce](https://colab.research.google.com/drive/13g1AMmLsCK3dcmuUdYiDhyv9PqajFRlc)

Given:
```
import tensorflow as tf
from tensorflow.data import Dataset
tf = tf.compat.v2
tf.enable_v2_behavior()

@tf.function
def test1(ds):
  for val in ds.map(lambda x: x+1):
    print(val)
    
@tf.function
def test2(ds):
  for val in map(lambda x: x+1, ds):
    print(val)

ds = tf.data.Dataset.from_tensor_slices([1, 2, 3, 4])
```
**Describe the current behavior**
```
print('start')
test1(ds) # NOT HANG
print('end')

print('start')
test2(ds) # HANG
print('end')
```

**Describe the expected behavior**
It should not hang.

**Other info / logs**
I've been thinking about a fix much like [overriding python built-in zip function](https://github.com/tensorflow/tensorflow/pull/31290). The problem is, [tf.data.Dataset's map only applies to one dataset](https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/data/Dataset#map) while python built-in map function can accept more than 1 data. For example:
```
numbers1 = [1, 2, 3] 
numbers2 = [4, 5, 6] 
  
result = map(lambda x, y: x + y, numbers1, numbers2) 
print(list(result)) 
```

What's the solution? 
Please correct me if I'm wrong or I'm missing something. Thank you.

**Comment by oanush** [comment]
Issue replicating for TF-2.0beta1.

**Comment by mdanatg** [comment]
AutoGraph doesn't currently override `map`, but the usage you describe could be added, in a fashion similar to how we handle `zip` and `enumerate`.

**Comment by ilhamfp** [comment]
@mdanatg But how to handle if we need to apply `map` to more than 2 datasets? Unlike `Dataset.zip`, [`map` in Datasets](https://github.com/tensorflow/tensorflow/blob/r2.0/tensorflow/python/data/ops/dataset_ops.py#L1099-L1214) can only take 1 Dataset.

**Comment by mdanatg** [comment]
I think we could use a combination of `Dataset.map` and `Dataset.zip`.

In other words:

`map(fn, dataset1, dataset2)`

could translate to (pseudo-code, the exact API calls may differ):

```
def fn_wrapper(args_tuple):
  fn(*args_tuple)
Dataset.zip(dataset1, dataset2).map(fn_wrapper)
```

Would this work?

**Comment by ilhamfp** [comment]
Oh yea, you're right! Working on it right now

**Comment by ilhamfp** [comment]
I'll close this issue as #32121 has been merged.
