### ISSUE TITLE
EmptyTensorList, RandomUniform, TensorListFromTensor, TensorListReserve, TensorListStack, While ops have not be supported

### ISSUE THREAD

**Issue by banbishan** [tensorflow/tensorflow#31821]
**System information**
- Linux Ubuntu 16.04:
- TensorFlow installed from anaconda:
- TensorFlow version 1.14.0:

hi,it seems that EmptyTensorList, RandomUniform, TensorListFromTensor, TensorListReserve, TensorListStack, While ops have not be supported .

output from tflite_convert:

Exception: We are continually in the process of adding support to TensorFlow Lite for more ops. It would be helpful if you could inform us of how this conversion went by opening a github issue at https://github.com/tensorflow/tensorflow/issues/new?template=40-tflite-op-request.md
 and pasting the following:

Some of the operators in the model are not supported by the standard TensorFlow Lite runtime. If those are native TensorFlow operators, you might be able to use the extended runtime by passing --enable_select_tf_ops, or by setting target_ops=TFLITE_BUILTINS,SELECT_TF_OPS when calling tf.lite.TFLiteConverter(). Otherwise, if you have a custom implementation for them you can disable this error with --allow_custom_ops, or by setting allow_custom_ops=True when calling tf.lite.TFLiteConverter(). Here is a list of builtin operators you are using: ADD, CAST, CONCATENATION, CONV_2D, FULLY_CONNECTED, GATHER, GREATER_EQUAL, MAX_POOL_2D, MUL, RESHAPE, REVERSE_V2, SHAPE, TRANSPOSE. Here is a list of operators for which you will need custom implementations: EmptyTensorList, RandomUniform, TensorListFromTensor, TensorListReserve, TensorListStack, While.

```
import os
os.environ["TF_ENABLE_CONTROL_FLOW_V2"] = "1"
import tensorflow as tf


graph_def_file = "./vgg/frozen_graph_meta2.pb"
input_arrays = ["images_pre"]#image_widths_pre
output_arrays = ["fully_connected/transpose_time_major"]

converter = tf.lite.TFLiteConverter.from_frozen_graph(graph_def_file, input_arrays, output_arrays)
#converter.target_ops = [tf.lite.OpsSet.SELECT_TF_OPS]
tflite_model = converter.convert()
open("converted_model.tflite", "wb").write(tflite_model)
```

**Comment by haozha111** [comment]
Hi,

TOCO currently doesn't support control-flow ops and TensorList ops. We are currently working on a new converter to support all those use cases.

Are you trying to convert an RNN model?

**Comment by banbishan** [comment]
> Hi,
> 
> TOCO currently doesn't support control-flow ops and TensorList ops. We are currently working on a new converter to support all those use cases.
> 
> Are you trying to convert an RNN model?

yep, i trying to convert an rnn model. and i have use tf.lite.experimental.nn.bidirectional_dynamic_rnn instead of tf.nn.bidirectional_dynamic_rnn, use tf.lite.experimental.nn.TfLiteLSTMCell instead of tf.nn.rnn_cell.LSTMCell references https://tensorflow.google.cn/lite/convert/rnn. But it doesn't seem to be working.

**Comment by haozha111** [comment]
Hi,

I believe currently you need to add ophints in your model to make the conversion work. Could you please check out:
https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/experimental/examples/lstm/g3doc

Thanks!

**Comment by haozha111** [comment]
Hi,

Sorry for a late update. We have just released a beta TF Lite converter, you can try it with:
coverter.experimental_new_converter = True (make sure you install the latest tf-nightly).

With this converter, you can just use the native tf.nn.bidirectional_dynamic_rnn API rather than tf.lite.experimental* ones. Can you give it a try?
