### ISSUE TITLE
KeyError while loading image data

### ISSUE THREAD

**Issue by DKWIPL** [tensorflow/tensorflow#31825]
Error:
File "DataCollection.py", line 38, in caption_image
return "Image (CC BY 2.0) " + ' - '.join(attributions[str(image_rel)].split(' - ')[:-1])
KeyError: 'sunflowers\6166888942_7058198713_m.jpg'

Function:
def caption_image(image_path):
image_rel = pathlib.Path(image_path).relative_to(data_root)
return "Image (CC BY 2.0) " + ' - '.join(attributions[str(image_rel)].split(' - ')[:-1])

It gives a KeyError while returning the parameter.
And every time it gives a KeyError with different image name and path.

Any idea on this?

**Comment by gadagashwini** [comment]
Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version. Also, did you compile from source or install a binary?

Make sure you also include the exact command if possible to produce the output included in your test case. If you are unclear what to include see the issue template displayed in [the Github new issue template](https://github.com/tensorflow/tensorflow/issues/new/choose).

We ask for this in the issue submission template, because it is really difficult to help without that information. Thanks!

**Comment by DKWIPL** [comment]
Sure,
Here are the details:

I am following this tutorial - https://www.tensorflow.org/tutorials/load_data/images 
to learn about how to train the model using sets of images.

But when I started inspecting the images as shown here: https://www.tensorflow.org/tutorials/load_data/images#inspect_the_images

It is not working, it gives me the following error:
File "DataCollectionError:.py", line 38, in caption_image
return "Image (CC BY 2.0) " + ' - '.join(attributions[str(image_rel)].split(' - ')[:-1])
KeyError: 'sunflowers\6166888942_7058198713_m.jpg'

It gives a KeyError while returning the parameter.
And every time it gives a KeyError with different image name and path.

Any idea on this?

**Comment by gadagashwini** [comment]
@DKWIPL,
I tried executing the colab but i didn't get any error. Just to verify, are you executing the code in colab or jupyter notebook locally on your system. Thanks!

**Comment by DKWIPL** [comment]
NO, I am doing it on my Local System.

**Comment by DKWIPL** [comment]
And can you also help me with the tutorial to create and train the model using our own image dataset?
It will be really useful for us if can help us with this.

Thank You.

**Comment by gadagashwini** [comment]
> NO, I am doing it on my Local System.

If your doing it on local system, please verify the path of the input data. Thanks!

**Comment by DKWIPL** [comment]
Hi,

I checked my data path. It is proper. And as I skipped that step and moved forward, I started getting the following error. 

Traceback (most recent call last):
  File "C:\Program Files\Python37\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Program Files\Python37\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Program Files\Python37\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Program Files\Python37\lib\imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Program Files\Python37\lib\imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "DataCollection.py", line 3, in <module>
    import tensorflow as tf
  File "C:\Program Files\Python37\lib\site-packages\tensorflow\__init__.py", line 28, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "C:\Program Files\Python37\lib\site-packages\tensorflow\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Program Files\Python37\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "C:\Program Files\Python37\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Program Files\Python37\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Program Files\Python37\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Program Files\Python37\lib\imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Program Files\Python37\lib\imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: The specified module could not be found.


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.


I don,t know what is going on in this. It was working by Friday and its suddenly stop working on Monday.

**Comment by gadagashwini** [comment]
@DKWIPL 
`ImportError: DLL load failed: The specified module could not be found.`
Looks like the tensorflow is not installed properly, Can you uninstall tensorflow and python and reinstall both. Thanks!

**Comment by DKWIPL** [comment]
Hey,

It worked from me installing and reinstalling again. But what was the issue?
It was working before and suddenly it stopped working.

**Comment by gadagashwini** [comment]
@DKWIPL, Glad it worked. 
From the error it looks like Tensorflow and its dependencies are not installed properly. 
Closing the issue since its resolved. Thanks

**Comment by wangyifan349** [comment]
#The path problem needs to be solved under windows !!!!!!!!!!!!!!!
def caption_image(image_path):
	image_rel = pathlib.Path(image_path).relative_to(data_root)
	image_rel = str(image_rel).replace("\\","/")#################look here！
	image_rel = image_rel + " "
	return "Image (CC BY 2.0) "+ " - ".join(attributions[image_rel].split(" - ")[:-1])

**Comment by DKWIPL** [comment]
-----------------------------------------------------------
Attention: Non-Delivery Report
-----------------------------------------------------------

This report is generated by the email server at:

       gophygital.io

The message with subject:

       "Re: [tensorflow/tensorflow] KeyError while loading image data (#31825)"

and attached to this report was not delivered to 
the following recipients:

Address: ***@***.***
Reason:  User not found (550)
--------------
