### ISSUE TITLE
Using libtensorflow-core.a to enable training on Android 

### ISSUE THREAD

**Issue by ghost** [tensorflow/tensorflow#31829]
I followed : https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/makefile/README.md

to build the tensorflow library for Android. Does the lib file contain all the functionalities to enable training on Android by using c++ to call the library.

**Comment by jdduke** [comment]
This path is effectively deprecated. Is there a reason you cannot use bazel?

**Comment by kukzile** [comment]
I want the whole tensorflow library for android which includes ops for
training as well, hence trying this method. The present process of building
for Android using Android studio or bazel supports only inference, right?

**Comment by alokprasad** [comment]
try ndk14b , makefile only supports ndk14b as there are headers changes in later ndk, but there is huge performance impact using this ndk , i am trying to compile using latest ndk20 .

**Comment by jdduke** [comment]
Training support with TensorFlow Lite is in active development, @miaout17 can offer additional updates.

**Comment by mohantym** [comment]
Hi @ghost!  Have you checked the recently introduced On-Device training document from the [2.8 version](https://www.tensorflow.org/lite/examples/on_device_training/overview)?
