### ISSUE TITLE
Simple Audio Recognition sample couldn't be run in iOS swift - TFLite

### ISSUE THREAD

**Issue by KauthamMurugan** [tensorflow/tensorflow#31838]
I have successfully run the simple audio recognition sample from the examples folder and successfully generated the tensorflow model output_graph.pb. Then i successfully converted the model to TFLite using the following code.
```
import tensorflow as tf

frozen_graph = '/tmp/graph.pb'

input_arrays = ["decoded_sample_data"]
output_arrays = ["labels_softmax"]
supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS,
                                       tf.lite.OpsSet.SELECT_TF_OPS]

convertor = tf.lite.TFLiteConverter
convertor = convertor.from_frozen_graph(graph_def_file=frozen_graph,input_arrays=input_arrays,output_arrays=output_arrays)
convertor.target_ops = supported_ops

tflite_model = convertor.convert()
open("converted.tflite", "wb").write(tflite_model)
```

I have a sample iOS app and i am using the Firebase ML kit's MLModelInterpreter to run the model. I successfully complied and ran the project but at run time during the run i am get the error that "Unsupported ops". If the Decode_wave, Audiospectrogram and MFCC ops are not supported then how can the conversion be successfully? How can i run the tflite model in the iOS swift project successfully.

For iOS implementation refer- https://firebase.google.com/docs/ml-kit/ios/use-custom-models
OS - OSX - Mojave - 10.14.5
Tensorflow version - 1.14.0 stable 
Environment - Conda
Swift version - 4.2 and 5
Xcode - 10.2

[PB and Lite graphs.zip](https://github.com/tensorflow/tensorflow/files/3525438/PB.and.Lite.graphs.zip)

**Comment by juses0812** [comment]
Can you explain how to get the value of input_arrays and output_arrays?

**Comment by KauthamMurugan** [comment]
> Can you explain how to get the value of input_arrays and output_arrays?

I use the tool called "Netron" GUI interface. This tool allows you to view the layers, their names, the input and output shapes and datatypes all in a graphical flow chart. https://github.com/lutzroeder/netron

**Comment by Saduf2019** [comment]
@KauthamMurugan 
Is this still an issue

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.
