### ISSUE TITLE
[lite]  cc_library or cc_binary not including libs to build .so

### ISSUE THREAD

**Issue by laohur** [tensorflow/tensorflow#31836]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**so+.out rans ok in adb ,but DllNotFoundException in apk from unity.**
08-22 10:09:17.697 26322 26345 D Unity   : Unable to load library '/data/app/com.abc.cba-ZQdutbR1M-hRhdbPDZ25OA==/lib/arm/libProphet.so', native render plugin support disabled: java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "_ZTVN6tflite17MutableOpResolverE" referenced by "/data/app/com.abc.cba-ZQdutbR1M-hRhdbPDZ25OA==/lib/arm/libProphet.so"...

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):buid
cc_library(
    name = "Prophet",
    srcs = [
        "Prophet.cc",
        "minimal.h",
    ],
    linkopts = tflite_linkopts() + select({
        "//tensorflow:android": [
            "-pie",  # Android 5.0 and later supports only PIE
            "-lm",  # some builtin ops, e.g., tanh, need -lm
        ],
        "//conditions:default": [],
    }),
    deps = [
        "//tensorflow/lite:framework",
        "//tensorflow/lite/c:c_api_internal",
        "//tensorflow/lite/kernels:builtin_ops",
    ],
    linkstatic = False,
)

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): linux ubuntu18x64->win10x64 unity-
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:arm7
- TensorFlow installed from (source or binary):source 
- TensorFlow version (use command below):14
- Python version: 3.7
- Bazel version (if compiling from source):0.26
- GCC/Compiler version (if compiling from source):7.4
- CUDA/cuDNN version: none
- GPU model and memory: none

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
execute libc++_shared.so+example.so+example.out ok!
execute unity17+libc.so+libdl.so+ibc++_shared.so+example.so->apk，cannot find dll.
c++filt shows vtable for tflite::MutableOpResolver
**Describe the expected behavior**
apk ok!
**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.
 bazel build --config monolithic --cxxopt=-std=c++11 \
  --crosstool_top=//external:android/crosstool \
  --host_crosstool_top=@bazel_tools//tools/cpp:toolchain \
  --cpu=armeabi-v7a  --verbose_failures\
  //tensorflow/lite/examples/l17:example(so)
**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

`
08-21 21:11:24.373 16862 16884 D Unity   : UnloadTime: 6.400000 ms
08-21 21:11:24.381 16862 16884 D Unity   : UUID: a9c3ed14008066f6 => d958add90437df1f9b9cbdba44b84779
08-21 21:11:24.487 16862 16884 D Unity   : Sensor :        Accelerometer ( 1) ; 0.002396 / 0.00s ; ICM20690 Accelerometer / InvenSense 
08-21 21:11:24.512 16862 16884 D Unity   : Choreographer available: Enabling VSYNC timing
08-21 21:11:24.520 16862 16884 D Unity   : Unable to load library '/data/app/com.abc.cba-gPQU27o5p_2Y5PClNwV8OQ==/lib/arm/libProphet.so', native render plugin support disabled: java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "_ZTVN6tflite17MutableOpResolverE" referenced by "/data/app/com.abc.cba-gPQU27o5p_2Y5PClNwV8OQ==/lib/arm/libProphet.so"...
08-21 21:11:24.522 16862 16884 E Unity   : Unable to find Prophet
08-21 21:11:24.633 16862 16884 E Unity   : DllNotFoundException: Prophet
08-21 21:11:24.633 16862 16884 E Unity   :   at (wrapper managed-to-native) rlsdk.RLSDKAPI:init (byte[],int)
08-21 21:11:24.633 16862 16884 E Unity   :   at helloworld.Start () [0x00017] in D:\tflite\0821\L17online\Assets\helloworld.cs:18 
08-21 21:11:24.633 16862 16884 E Unity   :  
08-21 21:11:24.633 16862 16884 E Unity   : (Filename: D Line: 0)
`

**Comment by jdduke** [comment]
Hi @laohur. You cannot treat the .so output from a cc_library as a self-contained shared library. You need to put all of the deps into a cc_binary. See also [this build rule](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/BUILD#L454) and what it expands to.

**Comment by laohur** [comment]
finally, BUILD target cc_binrary() instead
