### ISSUE TITLE
Missing `person_detect.tflite` file

### ISSUE THREAD

**Issue by mariusz-r** [tensorflow/tensorflow#31831]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Mint 19.2 Tina
- TensorFlow installed from (source or binary): source
- TensorFlow version (or github SHA if from source): 80c04b80ad66bf95aa3f41d72a6bba5e84a99622

Files `person_detect_model_data.h/.cc` in `downloads` directory (downloaded from [here](https://storage.googleapis.com/download.tensorflow.org/data/tf_lite_micro_person_data_grayscale.zip)) mention `person_detect.tflite` file:

```c
// Automatically created from a TensorFlow Lite flatbuffer using a command like:
// xxd -i person_detect.tflite > person_detect_model_data.cc
```

Is this file available somewhere?
Is the full TF model available?

**Comment by gadagashwini** [comment]
@mariusz-r Please elaborate the issue and context. Thanks!

**Comment by mariusz-r** [comment]
I would like to experiment more with `micro_vision` example in TF lite micro and therefore I would like to have the full `person_detect` model. Is it available somewhere?

**Comment by frreiss** [comment]
The instructions for building and running that example are [here](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/experimental/micro/examples/person_detection/README.md).

Although there are some Bazel rules to compile and run tests of the `person_detect` model, it does not appear that those Bazel rules currently work. The rules to generate the missing file `person_detect_model_data.cc` is only present in the `Make`-based build [here](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/experimental/micro/tools/make/Makefile).

**Comment by mariusz-r** [comment]
Thanks! This fully answers my question and I think this issue can be closed.

**Comment by aselle** [comment]
Glad your issue is resolved. Thanks @frreiss for the quick answer.
