### ISSUE TITLE
Implement tf-slim from tensorflow/models.

### ISSUE THREAD

**Issue by TimZaman** [tensorflow/tensorflow#3183]
Feature request: Implement tf-slim from `tensorflow/models` into `tensorflow/tensorflow`.
See requests from models: https://github.com/tensorflow/models/issues/186, https://github.com/tensorflow/models/issues/203. Maybe mark for 0.9 as suggested by @sguada?

**Comment by sguada** [comment]
It is already part of 'master' take a look at contrib/slim, we plan to include more docs, nets, examples and make it part of 0.9.1
More updates would come for the 0.10

**Comment by aselle** [comment]
Does this address your need @TimZaman? If so I will close this bug.
