### ISSUE TITLE
Attempt to build with NDK only in configure.py results in invalid android.bzl

### ISSUE THREAD

**Issue by DoumanAsh** [tensorflow/tensorflow#31843]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04 (docker)
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: -
- TensorFlow installed from (source or binary): Source
- TensorFlow version: 1.14.0
- Python version: 3.7
- Installed using virtualenv? pip? conda?: pip yes
- Bazel version (if compiling from source): 0.24.1
- GCC/Compiler version (if compiling from source): Clang from NDK r17b
- CUDA/cuDNN version: -
- GPU model and memory: -

**Describe the problem**
I'm attempting to build tensorflow light using android NDK compiler, without plugging in SDK.
Therefore I set `TF_SET_ANDROID_WORKSPACE` to 0, while I have `ANDROID_NDK_HOME` pointing to location of valid NDK installation.

Attempting to perform such build results in error:
```
ERROR: /root/.cache/bazel/_bazel_root/9deba62a2f90185d207a955a930b77dc/external/local_config_android/android.bzl:10:2: indentation error
ERROR: error loading package '': Extension 'android.bzl' has errors
ERROR: error loading package '': Extension 'android.bzl' has errors
```

This happens because configure.py adds ndk location (specified in env variable) by appending to android.bzl that has only pass in body of function.
But it is added with 2 spaces, while rest of android.bzl was with 4 tabs.

This is the first problem, I have to manually remove `pass` and leave only NDK setup
Probably there should not be such difference in tabulation when generating `android.bzl`

The second issue, is whether it should be possible to build `//tensorflow/lite:libtensorflowlite.so` with NDK only.
I was able to do so after manually correcting `android.bzl`

**Provide the exact sequence of commands / steps that you executed before running into the problem**

- Environment variables:

```
PYTHON_BIN_PATH = <valid location python>
USE_DEFAULT_PYTHON_LIB_PATH = '1'
TF_ENABLE_XLA = '0'
TF_NEED_ROCM = '0'
TF_NEED_CUDA = '0'
TF_NEED_MPI = '0'
TF_DOWNLOAD_CLANG = '0'
TF_SET_ANDROID_WORKSPACE = '0'
TF_CONFIGURE_IOS = '0'
ANDROID_NDK_HOME = <valid location of NDK>
ANDROID_NDK_API_LEVEL = '18'
TF_NEED_OPENCL_SYCL = '1'
TF_NEED_COMPUTECPP = '0'
TRISYCL_INCLUDE_DIR = '<path to cloned repo of TrySYCL>/include'
HOST_CXX_COMPILER = '<NDK path>/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++'
HOST_C_COMPILER = '<NDK path>/toolchains/llvm/prebuilt/linux-x86_64/bin/clang'
CC_OPT_FLAGS = '-Wno-sign-compare'
```

- Run `python configure.py`
- Rim `bazel shutdown`
- Run build with `bazel build --config=opt --config=v2 --cxxopt='--std=c++11' --define=no_tensorflow_py_deps=true --config=android_arm64 //tensorflow/lite:libtensorflowlite.so --verbose_failures`

**Any other info / logs**
Manual correction of `android.bzl` results in successful build, but it seems there are no symbols related to GPU delegate (I guess a separate target is required?)

**Comment by jdduke** [comment]
Feel free to propose a fix that allows setting the SDK as optional.

**Comment by DoumanAsh** [comment]
There is something unclear to me currently.

Is it bazel, who requires SDK in addition to NDK in order to build android related projects, or tensorflow?

**Comment by jdduke** [comment]
I suspect you'll need to modify something in this file: https://github.com/tensorflow/tensorflow/blob/master/third_party/android/android_configure.bzl

**Comment by DoumanAsh** [comment]
Ok, thx, I'll test various approaches and will be back with PR
