### ISSUE TITLE
TFLite benchmark tool doesn't show complete Op profiling when using use_nnapi=true flag

### ISSUE THREAD

**Issue by bilalsoomro** [tensorflow/tensorflow#31840]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: All devices
- TensorFlow installed from (source or binary): Source
- TensorFlow version (use command below): Release 1.14.0
- Python version: 2.7.15+
- Bazel version (if compiling from source): 0.24.1
- GCC/Compiler version (if compiling from source): gcc (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0

**Describe the current behavior**
I am testing the benchmark tool found on this link: https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/tools/benchmark
I am building and running in Android to benchmark MobileNet V1 model on some devices. I am interested in seeing the profiling information for each of the layers/operations and I am able to do that by adding the enable_op_profiling=true flag. However, I can't see the information when I also add the flag "--use_nnapi=true".

Example with NNAPI switched off:
![image](https://user-images.githubusercontent.com/8417115/63438560-2ab00400-c435-11e9-9c11-cb518270a54e.png)

Example with NNAPI switched on:
![image](https://user-images.githubusercontent.com/8417115/63438606-41eef180-c435-11e9-9299-08dee2ad6f9f.png)

**Describe the expected behavior**
I expect that using the --use_nnapi=true flag will also display op profiling information

**Code to reproduce the issue**
Just enable --enable_op_profiling=true and --use_nnapi=true flags when running the benchmark on any model. Is it not implemented yet?

**Comment by jdduke** [comment]
This information is not yet exposed from NNAPI, sadly, and won't be available in the near future.

**Comment by ottovonzastrow** [comment]
similar issue for me
after following the instructions on the tflite benchmarking tool for desktop the tool worked but didn't show any additional information when using the --enable_op_profiling=true argument
OS: linux 19.04, built benchmarking tool with bazel 0.21 from latest tensorflow
