### ISSUE TITLE
Udacity Notebook with "None" kernel

### ISSUE THREAD

**Issue by zuoxingdong** [tensorflow/tensorflow#3185]
I use Jupyter notebook to open the .ipynb files, but it shows a red "None" kernel on top right corner and all lines of code cannot run. 

Method I use:
1. Build a new directory and extract .ipynb files from `examples/udacity` to the directory
2. In terminal, run `jupyter notebook`

**Comment by aselle** [comment]
You haven't provided sufficient information for us to help. The new issue template provides a list of information we need to help. It sounds like a installation problem where jupyter installation or tensorflow installation. If you see indication of a bug in tensorflow, please reopen.
