### ISSUE TITLE
Lite: is the "MinimumRuntimeVersion" list still under maintenance? 

### ISSUE THREAD

**Issue by jackwish** [tensorflow/tensorflow#31879]
*This is an issue "compiled by eyes in original source", so there is no templeted issue questions*.

Hi, I notice that the "[GetMinimumRuntimeVersionForModel](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/toco/tflite/op_version.cc#L26)" doesn't include **a complete list** of supported Ops of TFLite when I am adding new op. I am curious that if that list is still under maintenance? It seems that the MinimumRuntimeVersion is simply a tip string that won't block model to run on TFLite of any version. And [the min version searching logic](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/toco/tflite/op_version.cc#L198) seems restricted to regex `[0-9]\.[0-9]\.[0-9]`, which means `1.9.0` is a larger version than `1.14.0`.

As there seems no runtime check to enforce this min version, maybe we can remove it to lease the op versioning handling? Or we can improve it and enforce it (include PRs)?

Ping people who may know, sorry for the spam ;)
@haozha111 @jianlijianli @bjacob @aselle @suharshs

**Comment by haozha111** [comment]
Hi Jack,

Thanks for taking a look into this!

1) When you add a new op, you also need to update the map in op_version.cc, with 'kPendingReleaseOpVersion' as a placeholder for the actual TF version.
2) The compare logic is a bug. I will fix this soon. Sorry about that!
3) We currently don't block model from execution based on min_version, I think that's intended. It could be in the user code that checks this version and see if the application code want to execute or not. Also notice that the version map only tracks built-in ops, and we don't have any mechanism of tracking the version of custom ops.

Thanks!

**Comment by jackwish** [comment]
Thank you for the detailed explanation! I am agree you that user code may need to check that version, but the list is not complete, not sure it can really help :)

Btw, is the versioning here shall sync with schema, and/or kernel register?

**Comment by haozha111** [comment]
Hi, Jack,

Totally agree with you that the current list should keep in sync with kernel register. Otherwise the generated min version won't be reliable. I'm currently working on this.

In the meantime, I will update the comment about this method to inform the users that this is currently experimental. Thanks!

**Comment by jackwish** [comment]
Thank you Haoliang! I have added version in this list once, I understand
that is hmm... a sort annoying work, thanks for you efforts, sincerely.

Cheers


Haoliang Zhang <notifications@github.com> 于2019年8月24日周六 上午2:13写道：
