### ISSUE TITLE
Invalid Link for TensorFlow Keras Official Documentation

### ISSUE THREAD

**Issue by PatrickXYS** [tensorflow/tensorflow#31876]
## URL with the issue:
https://www.tensorflow.org/guide/keras
https://colab.research.google.com/github/tensorflow/docs/blob/master/site/en/guide/keras.ipynb
https://github.com/tensorflow/docs/blob/master/site/en/guide/keras.ipynb

## Description of issue (what needs changing):
The last two links are directed to 404, which means they don't exist with valid colab files or gitlab files.

**Comment by lamberta** [comment]
Thanks for the report. We're in the process of moving the docs around for the TF2 RC.
Those docs now live here in github:
- https://github.com/tensorflow/docs/blob/master/site/en/r1/guide/keras.ipynb
- https://colab.sandbox.google.com/github/tensorflow/docs/blob/master/site/en/r1/guide/keras.ipynb

But, really, they should point to the `r2.0rc` branch to avoid this: https://github.com/tensorflow/docs/blob/r2.0rc/site/en/guide/keras.ipynb

**Comment by lamberta** [comment]
Links in TF1 guides and tutorials have been updated to point to the `r2.0rc`branch:
- https://colab.research.google.com/github/tensorflow/docs/blob/r2.0rc/site/en/guide/keras.ipynb
- https://github.com/tensorflow/docs/blob/r2.0rc/site/en/guide/keras.ipynb
