### ISSUE TITLE
Compiling from source, error with finding cuda 

### ISSUE THREAD

**Issue by manuprasad07** [tensorflow/tensorflow#31872]
- OS Platform and Distribution: Centos 7
- TensorFlow installed from: source
- TensorFlow version: 1.15
- Python version: 2.7.5
- Installed using virtualenv: virtualenv
- Bazel version: 0.26.0
- GCC/Compiler version: 7.3.0
- CUDA version: CUDA 10.1
-cuDNN version: 7.6.2
- TensorRT: 5.1.5
- GPU: Tesla T4

I'm trying to install tensorflow from source and tried v1.14 and v1.15. When running ./configure, I select yes for CUDA and TensorRT support. I initially get an error saying no cuda.h is found, so I point the path to /usr/include/linux. The installation fails with the following error:

`Traceback (most recent call last):
  File "third_party/gpus/find_cuda_config.py", line 500, in <module>
    main()
  File "third_party/gpus/find_cuda_config.py", line 492, in main
    for key, value in sorted(find_cuda_config().items()):
  File "third_party/gpus/find_cuda_config.py", line 457, in find_cuda_config
    result.update(_find_cuda_config(cuda_paths, cuda_version))
  File "third_party/gpus/find_cuda_config.py", line 251, in _find_cuda_config
    get_header_version)
  File "third_party/gpus/find_cuda_config.py", line 238, in _find_header
    required_version, get_version)
  File "third_party/gpus/find_cuda_config.py", line 227, in _find_versioned_file
    actual_version = get_version(file)
  File "third_party/gpus/find_cuda_config.py", line 244, in get_header_version
    version = int(_get_header_version(path, "CUDA_VERSION"))
ValueError: invalid literal for int() with base 10: ''
Asking for detailed CUDA configuration...
`

Full log:

WARNING: Running Bazel server needs to be killed, because the startup options are different.
WARNING: --batch mode is deprecated. Please instead explicitly shut down your Bazel server using the command "bazel shutdown".
You have bazel 0.26.0 installed.
Please specify the location of python. [Default is /home/mltlocal/envs/Resnet50GPU/bin/python]:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: 'module' object has no attribute 'getsitepackages'
Found possible Python library paths:
  /home/mltlocal/envs/Resnet50GPU/lib/python2.7/site-packages
Please input the desired Python library path to use.  Default is [/home/mltlocal/envs/Resnet50GPU/lib/python2.7/site-packages]

Do you wish to build TensorFlow with XLA JIT support? [Y/n]: n
No XLA JIT support will be enabled for TensorFlow.

Do you wish to build TensorFlow with OpenCL SYCL support? [y/N]: n
No OpenCL SYCL support will be enabled for TensorFlow.

Do you wish to build TensorFlow with ROCm support? [y/N]: n
No ROCm support will be enabled for TensorFlow.

Do you wish to build TensorFlow with CUDA support? [y/N]: y
CUDA support will be enabled for TensorFlow.

Do you wish to build TensorFlow with TensorRT support? [y/N]: y
TensorRT support will be enabled for TensorFlow.

Could not find any cuda.h matching version '' in any subdirectory:
        ''
        'include'
        'include/cuda'
        'include/*-linux-gnu'
        'extras/CUPTI/include'
        'include/cuda/CUPTI'
of:
        '/lib64'
        '/opt/rh/devtoolset-4/root/usr/lib64/dyninst'
        '/usr'
        '/usr/lib64/atlas'
        '/usr/lib64/dyninst'
        '/usr/lib64/mysql'
        '/usr/local/cuda-10.1/targets/x86_64-linux/lib'
Asking for detailed CUDA configuration...

Please specify the CUDA SDK version you want to use. [Leave empty to default to CUDA 10]: 10.1

Please specify the cuDNN version you want to use. [Leave empty to default to cuDNN 7]: 7.6.2

Please specify the TensorRT version you want to use. [Leave empty to  default to TensorRT 5]:

Please specify the locally installed NCCL version you want to use. [Leave empty to use http://github.com/nvidia/nccl]:

Please specify the comma-separated list of base paths to look for CUDA libraries and headers. [Leave empty to use the default]: /usr/include/linux

Traceback (most recent call last):
  File "third_party/gpus/find_cuda_config.py", line 500, in <module>
    main()
  File "third_party/gpus/find_cuda_config.py", line 492, in main
    for key, value in sorted(find_cuda_config().items()):
  File "third_party/gpus/find_cuda_config.py", line 457, in find_cuda_config
    result.update(_find_cuda_config(cuda_paths, cuda_version))
  File "third_party/gpus/find_cuda_config.py", line 251, in _find_cuda_config
    get_header_version)
  File "third_party/gpus/find_cuda_config.py", line 238, in _find_header
    required_version, get_version)
  File "third_party/gpus/find_cuda_config.py", line 227, in _find_versioned_file
    actual_version = get_version(file)
  File "third_party/gpus/find_cuda_config.py", line 244, in get_header_version
    version = int(_get_header_version(path, "CUDA_VERSION"))
ValueError: invalid literal for int() with base 10: ''
Asking for detailed CUDA configuration...

**Comment by grayfall** [comment]
I am having the same issue on Ubuntu 18 with Bazel 0.24.1 and CUDA 10.1. I've tried several TF releases, including r1.13, r1.14 and r1.15.

**Comment by grayfall** [comment]
For the record, r1.12 builds just fine on the same system (I've got both CUDA 10 and 10.1 installed).

**Comment by mihaimaruseac** [comment]
Reassigning to @gunan as I don't have context here

**Comment by Saduf2019** [comment]
@manuprasad07  
Is this still an issue.

**Comment by ElhamSol** [comment]
Hi,

I'm having the same issue here.

Ubuntu 18.04
RTX 2080 ti
cuda 11.1
cudNN 8.0.4.30
TensorRT 7.2.1.6

trying to install the default TF 2.3




root@mibcat01:~/tensorflow# git checkout r2.3
Branch 'r2.3' set up to track remote branch 'r2.3' from 'origin'.
Switched to a new branch 'r2.3'
root@mibcat01:~/tensorflow# ./configure
You have bazel 3.1.0 installed.
Please specify the location of python. [Default is /usr/bin/python3]: /usr/bin/python3


Found possible Python library paths:
  /usr/lib/python3/dist-packages
  /usr/local/lib/python3.6/dist-packages
Please input the desired Python library path to use.  Default is [/usr/lib/python3/dist-packages]
/usr/lib/python3/dist-packages
Do you wish to build TensorFlow with OpenCL SYCL support? [y/N]: n
No OpenCL SYCL support will be enabled for TensorFlow.

Do you wish to build TensorFlow with ROCm support? [y/N]: n
No ROCm support will be enabled for TensorFlow.

Do you wish to build TensorFlow with CUDA support? [y/N]: y
CUDA support will be enabled for TensorFlow.

Do you wish to build TensorFlow with TensorRT support? [y/N]: y
TensorRT support will be enabled for TensorFlow.

Traceback (most recent call last):
  File "third_party/gpus/find_cuda_config.py", line 648, in <module>
    main()
  File "third_party/gpus/find_cuda_config.py", line 640, in main
    for key, value in sorted(find_cuda_config().items()):
  File "third_party/gpus/find_cuda_config.py", line 578, in find_cuda_config
    result.update(_find_cuda_config(cuda_paths, cuda_version))
  File "third_party/gpus/find_cuda_config.py", line 254, in _find_cuda_config
    get_header_version)
  File "third_party/gpus/find_cuda_config.py", line 241, in _find_header
    required_version, get_version)
  File "third_party/gpus/find_cuda_config.py", line 230, in _find_versioned_file
    actual_version = get_version(file)
  File "third_party/gpus/find_cuda_config.py", line 247, in get_header_version
    version = int(_get_header_version(path, "CUDA_VERSION"))
ValueError: invalid literal for int() with base 10: ''
Asking for detailed CUDA configuration...

Please specify the CUDA SDK version you want to use. [Leave empty to default to CUDA 10]: 11.1


Please specify the cuDNN version you want to use. [Leave empty to default to cuDNN 7]: 8.0.4.30


Please specify the TensorRT version you want to use. [Leave empty to default to TensorRT 6]: 7.2.1.6


Please specify the locally installed NCCL version you want to use. [Leave empty to use http://github.com/nvidia/nccl]:


Please specify the comma-separated list of base paths to look for CUDA libraries and headers. [Leave empty to use the default]: /lib,/lib/x86_64-linux-gnu,/usr,/usr/lib/x86_64-linux gnu/libfakeroot,/usr/local/cuda,/usr/local/cuda-11.1,/usr/local/cuda-11.1/targets/x86_64-linux/lib,/usr/local/cuda-11.1/targets/x86_64-linux/include,/root/TensorRT-7.2.1.6,/root/TensorRT-7.2.1.6/bin,/root/TensorRT-7.2.1.6/lib,/root/TensorRT-7.2.1.6/include


Traceback (most recent call last):
  File "third_party/gpus/find_cuda_config.py", line 648, in <module>
    main()
  File "third_party/gpus/find_cuda_config.py", line 640, in main
    for key, value in sorted(find_cuda_config().items()):
  File "third_party/gpus/find_cuda_config.py", line 578, in find_cuda_config
    result.update(_find_cuda_config(cuda_paths, cuda_version))
  File "third_party/gpus/find_cuda_config.py", line 254, in _find_cuda_config
    get_header_version)
  File "third_party/gpus/find_cuda_config.py", line 241, in _find_header
    required_version, get_version)
  File "third_party/gpus/find_cuda_config.py", line 230, in _find_versioned_file
    actual_version = get_version(file)
  File "third_party/gpus/find_cuda_config.py", line 247, in get_header_version
    version = int(_get_header_version(path, "CUDA_VERSION"))
ValueError: invalid literal for int() with base 10: ''
Asking for detailed CUDA configuration...

Please specify the CUDA SDK version you want to use. [Leave empty to default to CUDA 10]:
