### ISSUE TITLE
Parts of graphs are missing during tf.lite.TFLiteConverter

### ISSUE THREAD

**Issue by paanguin** [tensorflow/tensorflow#31873]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):

- OS Platform and Distribution : Linux Ubuntu 16.04
- TensorFlow version (use command below): r1.14
- Python version:
- Bazel version (if compiling from source):
- GCC/Compiler version : gcc 5.4.0 
- CUDA/cuDNN version: 10.0 / 7
- GPU model and memory: Nvidia GeForce GTX TITAN 

This is a little bit tricky to explain but I found that TFLiteConverter, which is shown above, drops a bunch of nodes in the tensorflow computation graph. 

Here is a part of my converting code.
```
    converter = tf.lite.TFLiteConverter.from_saved_model(latest,
                input_arrays=["Placeholder","Placeholder_1"],
                input_shapes={"Placeholder":[1,144000,1], "Placeholder_1":[1,500]},
                output_arrays=[output_node_names])

    # graph dump options
    converter.dump_graphviz_dir="graph_dir" # outputs graph visualization file (.dot)
    tflite_model = converter.convert()
    open("base_model.tflite", "wb").write(tflite_model)

```

The problem part of graph can be described as follows with input and output node names.
The original part of the graph looks like
```
...
Squeeze, Reshape_2 -> add (Add op)
Reshape_5, add -> add_1 (Add op)
...
```
, but the converter gave me 
```
...
add,Squeeze -> add_1 (Add op)
...
```
. The paths containing Reshape_5 and Reshapes_2 are completely missing in the converted graph. The paths containing Reshape_5 and Reshape_2 start from Const op nodes, not input nodes, so that the wrong converted graph still gives me output array in the same shape, but the output value is wrong. 

When I inspected the dumped graph such as toco_AT_IMPORT.dot, toco_AFTER_TRANSFORMATIONS.dot and toco_AFTER_ALLOCATION.dot, to find out the cause.
I found that toco_AT_IMPORT.dot, which is dumped at the importing the saved_model stage, already dropped the nodes. Thus I think that the problem occurred at the 'importing' stage, which reads the saved_model as GraphDef.

I modified the converter code to see intermediate tflite graph dump files in *.dot, as follows:
(https://github.com/tensorflow/tensorflow/blob/b431fcc28d6f905fd868d979121b8e6c80902731/tensorflow/lite/toco/import_tensorflow.cc#L2642)
```
std::unique_ptr<Model> ImportTensorFlowGraphDef(
    const ModelFlags& model_flags, const TensorFlowImportFlags& tf_import_flags,
    const GraphDef& tf_graph) {
  LogDumpGraphDef(kLogLevelModelChanged, "AT IMPORT", tf_graph);

  GraphDef inlined_graph(tf_graph);
  if (InlineAllFunctions(&inlined_graph)) {
    LogDumpGraphDef(kLogLevelModelChanged, "AFTER INLINING", inlined_graph);
  }

  // Check input and output specification.
  for (const auto& specified_input_array : model_flags.input_arrays()) {
    CHECK(!absl::EndsWith(specified_input_array.name(), ":0"))
        << "Unsupported explicit zero output index: "
        << specified_input_array.name();
  }
  for (const string& specified_output_array : model_flags.output_arrays()) {
    CHECK(!absl::EndsWith(specified_output_array, ":0"))
        << "Unsupported explicit zero output index: " << specified_output_array;
  }

  Model* model = new Model;
  internal::ConverterMapType converter_map;

  // This is used for the TFLite "Full Flex Mode" conversion. All the ops are
  // imported as `TensorFlowUnsupportedOperator`, and later all these ops are
  // converted to TFLite Flex ops.
  if (!tf_import_flags.import_all_ops_as_unsupported) {
    converter_map = internal::GetTensorFlowNodeConverterMap();
  } else {
    converter_map = internal::GetTensorFlowNodeConverterMapForFlex();
  }

  for (auto node : inlined_graph.node()) {
    StripZeroOutputIndexFromInputs(&node);
    auto status = internal::ImportTensorFlowNode(node, tf_import_flags, model,
                                                 converter_map);
    CHECK(status.ok()) << status.error_message();
  }
  //LogDump(kLogLevelModelChanged, "IN IMPORT 0", *model); // fail
  ResolveModelFlags(model_flags, model);

  //LogDump(kLogLevelModelChanged, "IN IMPORT 1", *model); // fail
  StripCaretFromArrayNames(model);
  //LogDump(kLogLevelModelChanged, "IN IMPORT 2", *model); // fail
  AddExtraOutputs(model);
  //LogDump(kLogLevelModelChanged, "IN IMPORT 3", *model); // fail
  FixNoMissingArray(model);
  LogDump(kLogLevelModelChanged, "IN IMPORT 4", *model); //
  FixNoOrphanedArray(model);
  LogDump(kLogLevelModelChanged, "IN IMPORT 5", *model); //
  FixOperatorOrdering(model);
  LogDump(kLogLevelModelChanged, "IN IMPORT 6", *model); //
  CheckInvariants(*model);
  LogDump(kLogLevelModelChanged, "IN IMPORT 7", *model); //

  // if rnn state arrays are constant, make them transient
  for (const auto& rnn_state : model->flags.rnn_states()) {
    model->GetArray(rnn_state.state_array()).buffer = nullptr;
  }

  return std::unique_ptr<Model>(model);
}
```
I want to find out the exact stage that causes the problem and fix it. The code gave me toco_IN_IMPORT_4.dot, toco_IN_IMPORT_5.dot, toco_IN_IMPORT_6.dot and toco_IN_IMPORT_7.dot, however, they were all same to toco_AT_IMPORT.dot.

I really need helps for this problem. Here are my questions.
1. What are possible causes of this problem? Is it in my tensorflow model or the converter?
2. The 'LogDumpGraphDef' function seems to dump outputs showing the graph definition, but how can I actually get its output?

**Comment by paanguin** [comment]
I found some answers for my self. I'm sorry for a premature issue making.

I could get some log messages by setting following environment variables in the converting code. 

```
import os
os.environ['TF_CPP_MIN_LOG_LEVEL']='0'
os.environ['TF_CPP_MIN_VLOG_LEVEL']='2'
```

This gives me some log messages that seems related to the converting.

Among them I found following part, says constant folding.

```
...
2019-08-22 11:57:55.662626: I tensorflow/core/grappler/optimizers/constant_folding.cc:1305] Folded node:
name: "body/model/parallel_0/body/add"
op: "Add"
input: "body/model/parallel_0/body/Reshape_5"
input: "body/model/parallel_0/body/Reshape_2"
device: "/device:GPU:0"
attr {
  key: "T"
  value {
    type: DT_FLOAT
  }
}

2019-08-22 11:57:56.049579: I tensorflow/core/grappler/optimizers/constant_folding.cc:1310] Generated constant node:
name: "ConstantFolding/body/model/parallel_0/body/add-folded"
op: "Const"
attr {
  key: "dtype"
  value {
    type: DT_FLOAT
  }
}
attr {
  key: "value"
  value {
    tensor {
      dtype: DT_FLOAT
      tensor_shape {
        dim {
          size: 1
        }
        dim {
          size: 600
        }
        dim {
          size: 512
        }
      }
      float_val: -0.0591003299
      float_val: -0.00605344772
      float_val: -0.668159962
      float_val: -0.0551900864
      float_val: 0.537890077
      float_val: -1.09977579
      float_val: 0.609119534
...
```

I didn't fully checked the correctness of 'float_val's, but it seems that the convert removes the path along Reshape_2 and Reshape_5 into 'Const' nodes. Then it performed the addition in 'add' Node, then it made final result as another 'Const' node, then it provided it as the input to add_1.

At this stage, I'm still finding the reason why the converted tflite graph gave me the different output, however, this 'missing' nodes seems not to be the reason. Thus I close this issue myself.

**Comment by ucasiggcas** [comment]
Dear,
how to set the four parameters
--mean_values
--std_dev_values
--default_ranges_min
--default_ranges_max

thx
#32611
