### ISSUE TITLE
BasicLSTMCell __call__ fails. 

### ISSUE THREAD

**Issue by chrisgrimm** [tensorflow/tensorflow#3188]
### Environment info
Operating System: 
OSX Yosemite 10.10.5

If installed from binary pip package, provide:

1. Which pip package you installed: CPU only mac-version
2. The output from `python -c "import tensorflow; print(tensorflow.__version__)": 0.9.0rc0

I've been getting a strange error when trying to use the BasicLSTM cell. Running the below code:
```
import tensorflow as tf

sess =  tf.Session()
init_state = tf.zeros([32, 6])
init_state2 = tf.zeros([32, 6])
input = tf.placeholder(tf.float32, [32, 10])
input2 = tf.placeholder(tf.float32, [32, 10])
print init_state.get_shape()
output, state = tf.nn.rnn_cell.BasicLSTMCell(3)(input, init_state)
output2, state2 = tf.nn.rnn_cell.BasicLSTMCell(3)(input2, init_state2)
```
results in a ValueError:
```
ValueError: Variable BasicLSTMCell/Linear/Matrix already exists, disallowed. Did you mean to set reuse=True in VarScope? Originally defined at:
output, state = tf.nn.rnn_cell.BasicLSTMCell(3)(input, init_state)
```
the error doesn't occur if the line generating `(output2, state2)` is omitted.

**Comment by ajaech** [comment]
I think each lstm cell should be defined in it's own named scope.

```
with tf.variable_scope('lstm1'):
  output, state = tf.nn.rnn_cell.BasicLSTMCell(3)(input, init_state)
with tf.variable_scope('lstm2'):
  output2, state2 = tf.nn.rnn_cell.BasicLSTMCell(3)(input2, init_state2)
```

**Comment by aselle** [comment]
Thank you for the response @ajaech. That should prevent the name conflict. @chrisgrimm  please close the issue if this solved your problem.

**Comment by chrisgrimm** [comment]
Thanks for clearing this up!
