### ISSUE TITLE
Can TF add a C++ kernel for PRelu? 

### ISSUE THREAD

**Issue by Zantares** [tensorflow/tensorflow#31883]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): no
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Red Hat 4.8.5-16
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: NA
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below): 1.4, master branch, commit id is c188ffcc9e8769e5c6f767b7fb1977e54cad4040
- Python version: 2.7
- Bazel version (if compiling from source): 0.24.1
- GCC/Compiler version (if compiling from source): gcc 6.3
- CUDA/cuDNN version: NA
- GPU model and memory: NA

**Describe the current behavior**
Some models(MTCC) uses PRelu as an activation layer, and it will be split to small ops including Relu, Sub(https://github.com/tensorflow/tensorflow/blob/r1.14/tensorflow/python/keras/layers/advanced_activations.py#L141). It's hard to fuse and will impact the performance .

**Describe the expected behavior**
Hope to have a TF C++ kernel for this op,  then it could call the kernel directly to get good cache locality on CPU or reduce memory access on GPU.

**Code to reproduce the issue**
NA

**Other info / logs**
NA

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.
