### ISSUE TITLE
Enabling model training on Android 

### ISSUE THREAD

**Issue by ghost** [tensorflow/tensorflow#31885]
The current support of tensorflow for Android does not include the binaries required for training. Is there a way by which we can include the required function's files ( for training basic image recognition model) in the libtensorflow-core.a?
Or any other method by which we can enable training?

**Comment by xwzhong** [comment]
I am curious why you wanna train model in Android? the Android calculation ablity is hard to support it. @kukzile

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.

**Comment by sushreebarsa** [comment]
@ghost Could you please have a look at the [TF Lite Examples ](https://www.tensorflow.org/lite/examples) and let us know if it helps?Thank you!
