### ISSUE TITLE
java.lang.IllegalArgumentException: Expects arg[0] to be float but string is provided (java)

### ISSUE THREAD

**Issue by ahvahsky2008** [tensorflow/tensorflow#31892]
I have own trained model and use label image demo code.

```
try (Graph graph = new Graph();
        Session session = new Session(graph)) {
        graph.importGraphDef(fileContent);
        
        try (Tensor<String> input = Tensors.create(imageBytes);
            Tensor output =
                session
                    .runner()
                    .feed("Placeholder", input)
                    .fetch("final_result")
                    .run()
                    .get(0)) {
          if (probabilities == null) {
            probabilities = new float[(int) output.shape()[0]];
          }
          output.copyTo(probabilities);
          int label = argmax(probabilities);
          System.out.printf(
              "%-30s --> %-15s (%.2f%% likely)\n",
              filename, labels.get(label), probabilities[label] * 100.0);
        }
```
I see error `Exception in thread "main" java.lang.IllegalArgumentException: Expects arg[0] to be float but string is provided`. This model works perfect in python, but i have issue in java

**Comment by ravikyram** [comment]
Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version. Also, did you compile from source or install a binary?

Make sure you also include the exact command if possible to produce the output included in your test case. If you are unclear what to include see the issue template displayed in [the Github new issue template](https://github.com/tensorflow/tensorflow/issues/new/choose).

We ask for this in the issue submission template, because it is really difficult to help without that information. Thanks!

**Comment by ravikyram** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Comment by atlantiswqq** [comment]
Has this problem been solved？I also encountered this problem. When I used python training and golang deployment, I reported the following error.
```
2019-11-12 10:21:43.102960: I tensorflow/cc/saved_model/reader.cc:31] Reading SavedModel from: ./static/1
2019-11-12 10:21:43.111154: I tensorflow/cc/saved_model/reader.cc:54] Reading meta graph with tags { serve }
2019-11-12 10:21:43.113390: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.2 AVX AVX2 FMA
2019-11-12 10:21:43.119036: I tensorflow/cc/saved_model/loader.cc:182] Restoring SavedModel bundle.
2019-11-12 10:21:43.158766: I tensorflow/cc/saved_model/loader.cc:132] Running initialization op on SavedModel bundle.
2019-11-12 10:21:43.163222: I tensorflow/cc/saved_model/loader.cc:285] SavedModel load for tags { serve }; Status: success. Took 60273 microseconds.
panic: Expects arg[0] to be string but uint8 is provided
```
I can provide my training and loading code, as well as all version Numbers, if needed.
