### ISSUE TITLE
Fix Tensorflow Lite Documentation

### ISSUE THREAD

**Issue by choochtech** [tensorflow/tensorflow#31903]
Hi,

On https://www.tensorflow.org/lite/guide/python the sample Interpreter code is wrong 

![image](https://user-images.githubusercontent.com/2943831/63538358-9b562f80-c4cc-11e9-8cac-d81786a1acad.png)

"from tflite_runtime import Interpreter"  should be changed to

"from tflite_runtime.interpreter import Interpreter"

Thanks

Hakan

**Comment by gadagashwini** [comment]
Similar issue [#31369](https://github.com/tensorflow/tensorflow/issues/31369).  Will close this now, we can track the solution on that thread.Thanks!
