### ISSUE TITLE
please add tensor factorization

### ISSUE THREAD

**Issue by bionicles** [tensorflow/tensorflow#31907]
**System information**
- TensorFlow version (you are using): 2b1
- Are you willing to contribute it (Yes/No): I want to but I don't think I'm qualified

**Describe the feature and the current behavior/state.**
tensorflow is about tensors but there's no built-in tensor factorization. 
i do believe this should be a core feature of the framework...what do you think?

**Will this change the current api? How?**
tf.linalg (i guess) would have something like Tucker Decomposition, higher order SVD
would this be a good 2.0 feature?

**Who will benefit with this feature?**
people who need to compress / factorize big tensors

**Any Other info.**
http://tensorly.org/stable/user_guide/quickstart.html#tensor-decomposition
https://github.com/hottbox/hottbox

**Comment by rmothukuru** [comment]
@bionicles,
Sorry for the delayed response. 

Can you please refer to the documentation of [Cholskey Factorization](https://www.tensorflow.org/probability/api_docs/python/tfp/experimental/linalg/simple_robustified_cholesky?hl=es) and [LDL Factorization](https://www.tensorflow.org/probability/api_docs/python/tfp/experimental/linalg/no_pivot_ldl?hl=es-ESpodemos&skip_cache=true) and let us know if this is what you are looking for? Thanks!

**Comment by rmlarsen** [comment]
@bionicles it is indeed a very reasonable assumption that a framework named TensorFlow should have a Tensor factorization. All the building blocks to write on should be present. Would you be able and willing to contribute such a factorization as a pull request?
