### ISSUE TITLE
[tflite] Support INT8 quantisation for UNPACK with TFLITE_BUILTINS_INT8 OpsSet

### ISSUE THREAD

**Issue by akarmi** [tensorflow/tensorflow#31902]
**System information**
- TensorFlow version (you are using): 1.14 and built from sources, master branch
- Are you willing to contribute it (Yes/No): Yes

**Describe the feature and the current behavior/state.**
The new TFLiteConverter post-training quantisation flow, as described in https://www.tensorflow.org/lite/performance/post_training_quantization#full_integer_quantization_of_weights_and_activations, does not support quantisation of UNPACK/UNSTACK operation when only integer operations are requested in the output model. When such conversion is attempted the following error is reported: 

> RuntimeError: Quantization not yet supported for op: UNPACK

For example, the script below

```
import tensorflow as tf
import numpy as np

def representative_dataset_gen():
	input = np.ones([2, 10],dtype=np.float32)
	for _ in range(10):
		yield [input]

# tf Graph Input
in_stacked = tf.compat.v1.placeholder("float32", [2, 10])
out_unstacked = tf.unstack(in_stacked, axis=0)

with tf.compat.v1.Session() as sess:
	tf.io.write_graph(tf.compat.v1.get_default_graph(), '.','unpack.pb', as_text=False)

input_name = ["Placeholder"]
output_name = ["unstack", "unstack:1"]

tflite_model_name = "int8_unpack.tflite"
converter = tf.lite.TFLiteConverter.from_frozen_graph("unpack.pb", input_name, output_name)
converter.optimizations = [tf.lite.Optimize.DEFAULT]
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
converter.representative_dataset = representative_dataset_gen
tflite_model = converter.convert()
open(tflite_model_name, "wb").write(tflite_model)

# Load TFLite model and allocate tensors.
interpreter = tf.lite.Interpreter(tflite_model_name)
interpreter.allocate_tensors()

# Get input and output tensors.
input_details = interpreter.get_input_details()
output_details = interpreter.get_output_details()

# Test model on random input data.
input_shape = input_details[0]['shape']
input_data = np.array(np.random.random_sample(input_shape), dtype=np.float32)
interpreter.set_tensor(input_details[0]['index'], input_data)
interpreter.invoke()
```

produces
```

2019-08-22 17:44:45.800226: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 3492095000 Hz
2019-08-22 17:44:45.800687: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x4c7b280 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2019-08-22 17:44:45.800705: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2019-08-22 17:44:45.805127: I tensorflow/core/grappler/devices.cc:60] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0 (Note: TensorFlow was not compiled with CUDA support)
2019-08-22 17:44:45.805220: I tensorflow/core/grappler/clusters/single_machine.cc:356] Starting new session
Traceback (most recent call last):
  File "TF_Tests/test.py", line 24, in <module>
    tflite_model = converter.convert()
  File "/home/antkac01/lab/mlt/venv-runtime/lib/python3.5/site-packages/tensorflow_core/lite/python/lite.py", line 993, in convert
    inference_output_type)
  File "/home/antkac01/lab/mlt/venv-runtime/lib/python3.5/site-packages/tensorflow_core/lite/python/lite.py", line 239, in _calibrate_quantize_model
    inference_output_type, allow_float)
  File "/home/antkac01/lab/mlt/venv-runtime/lib/python3.5/site-packages/tensorflow_core/lite/python/optimize/calibrator.py", line 78, in calibrate_and_quantize
    np.dtype(output_type.as_numpy_dtype()).num, allow_float)
  File "/home/antkac01/lab/mlt/venv-runtime/lib/python3.5/site-packages/tensorflow_core/lite/python/optimize/tensorflow_lite_wrap_calibration_wrapper.py", line 115, in QuantizeModel
    return _tensorflow_lite_wrap_calibration_wrapper.CalibrationWrapper_QuantizeModel(self, input_py_type, output_py_type, allow_float)
RuntimeError: Quantization not yet supported for op: UNPACK

```

We propose adding the required support into the TFLiteConverter as it seems to be a natural extension of the existing functionality and will make the int8 quantisation process consistent across all supported  conversion options.

It appears that the UNPACK operator for kTfLiteInt8 type is already implemented (see [unpack.cc](https://github.com/tensorflow/tensorflow/blob/186e794d71c17b52deb52ace151ec5add8525f2c/tensorflow/lite/kernels/unpack.cc#L93)). The converstion fails on the [check of "quantizable" property](https://github.com/tensorflow/tensorflow/blob/186e794d71c17b52deb52ace151ec5add8525f2c/tensorflow/lite/tools/optimize/quantize_model.cc#L561) because [GetOperatorProperty()](https://github.com/tensorflow/tensorflow/blob/186e794d71c17b52deb52ace151ec5add8525f2c/tensorflow/lite/tools/optimize/operator_property.cc#L20) does not contain a case statement for BuiltinOperator_UNPACK.

It looks like modifying GetOperatorProperty() could unlock this feature. The corresponding unit test(s) will need to be added as well.

**Will this change the current api? How?**
No

**Who will benefit with this feature?**
Anyone who attempts full 8-bit fixed point quantisation of models containinig UNPACK/UNSTACK operation, e.g. some versions of DeepSpeech.

**Any Other info.**

**Comment by akarmi** [comment]
In addition to the proposed changes in [GetOperatorProperty()](https://github.com/tensorflow/tensorflow/blob/186e794d71c17b52deb52ace151ec5add8525f2c/tensorflow/lite/tools/optimize/operator_property.cc#L20), it appears that it is also necessary to add support of the arbitrary number of operator outputs, similar to how it is done for the arbitrary number of inputs in Concatenation operator.

We will soon follow up with the patch that implements the proposed changes.

**Comment by alanchiao** [comment]
@akarmi, @MohamedNourArm: is there an effort to adding deepspeech quantized support? If so, it'd be worth creating a specific issue for that, which includes pointers to the original TF model variants.
It'd be a clear and impactful way to contribute. 

It's great that you specifically mentioned DeepSpeech as motivating this unpack int8 support. In general, it's more meaningful to create an issue based on a task/model as opposed to an individual op.

**Comment by akarmi** [comment]
@alanchiao, yes, we are trying various quantization options, including the [proposed 16-bit activations](https://github.com/tensorflow/tensorflow/pull/33343), with DeepSpeech, in its unrolled form for now. Depending on how far we get with that, we may be able to share the results of our efforts. For now, I am closing this issue as the [corresponding fix](https://github.com/tensorflow/tensorflow/pull/33971) has now been merged. Thanks!
