### ISSUE TITLE
Not able to build GPU custom op example 

### ISSUE THREAD

**Issue by alexminnaar** [tensorflow/tensorflow#31912]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 16.04
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 1.14.0
- Python version: 3.5
- CUDA/cuDNN version: 10.0
- GPU model and memory: GeForce GTX 980M

**Describe the current behavior**
Following the [instructions here](https://www.tensorflow.org/guide/extend/op#gpu_support) I navigate to ```tensorflow/tensorflow/examples/adding_an_op``` and run
```
nvcc -std=c++11 -c -o cuda_op_kernel.cu.o cuda_op_kernel.cu.cc  ${TF_CFLAGS[@]} -D GOOGLE_CUDA=1 -x cu -Xcompiler -fPIC
```

and I get the error

```
In file included from cuda_op_kernel.cu.cc:19:0:
/home/alex/.local/lib/python3.5/site-packages/tensorflow/include/tensorflow/core/util/gpu_kernel_helper.h:22:53: fatal error: third_party/gpus/cuda/include/cuda_fp16.h: No such file or directory
compilation terminated.
```

**Comment by alexminnaar** [comment]
@jvishnuvardhan sorry for the delay.  Here are some more detailed steps.

1.  Setup new venv and pip installed tensorflow-gpu
2. cloned the TensorFlow repo
3.  ran ```TF_CFLAGS=( $(python -c 'import tensorflow as tf; print("".join(tf.sysconfig.get_compile_flags()))') )```
4.  Navigated to tensorflow/tensorflow/examples/adding_an_op within the cloned TensorFlow repo.
5.  Followed the instructions outlined [here](https://www.tensorflow.org/guide/extend/op#compiling_the_kernel_for_the_gpu_device) i.e. ```nvcc -std=c++11 -c -o cuda_op_kernel.cu.o cuda_op_kernel.cu.cc
  ${TF_CFLAGS[@]} -D GOOGLE_CUDA=1 -x cu -Xcompiler -fPIC``` and received the error mentioned above.

**Comment by kzawisto** [comment]
@alexminnaar 
I've stumbled across same problem.

The file you are looking for, third_party/gpus/cuda/include/cuda_fp16.h really comes from your CUDA installation i.e. $CUDA_HOME/include/cuda_fp16.h . 

Somehow copy/link does not exist. 

How about you go there:
/home/alex/.local/lib/python3.5/site-packages/tensorflow/include/
create directory third_party/gpus/cuda
and then symlink your CUDA include dir here (/usr/local/cuda/include on my Debian box)?

**Comment by sanjoy** [comment]
Relevant comment from @Artem-B: https://github.com/tensorflow/tensorflow/issues/34428#issuecomment-564281533

**Comment by Saduf2019** [comment]
@alexminnaar
Please update as per above comment
