### ISSUE TITLE
iOS build breaks

### ISSUE THREAD

**Issue by john-difool** [tensorflow/tensorflow#3191]
git rev-parse HEAD
70de76e696c21da617fd2e6435cf7fedab220db8

ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [/Users/Shared/Develop/google/tensorflow/tensorflow/contrib/makefile/gen/host_bin/proto_text] Error 1
+ '[' 2 -ne 0 ']'
+ echo 'armv7 compilation failed.'
armv7 compilation failed.
+ exit 1

The rest of the output is here:

https://gist.github.com/john-difool/67126c4ccf5d8201cd1842ca18acc78b

**Comment by john-difool** [comment]
tensorflow/contrib/makefile/compile_ios_protobuf.sh PASSED
make -f tensorflow/contrib/makefile/Makefile TARGET=IOS IOS_ARCH=ARM64   FAILS

**Comment by fengjian0106** [comment]
I met the same problem

**Comment by duangenquan** [comment]
How did you fix this issue?

**Comment by chunfuchen** [comment]
encounter the same issue.

**Comment by petewarden** [comment]
I have a pending fix in PR #3253. It was caused by an error in the ordering of header and library paths, so the build would pull from global /usr/local installations of different versions of the protobuf library, which didn't match the results from the locally-built protoc.

**Comment by fengjian0106** [comment]
can work, cool!
