### ISSUE TITLE
[TF1.x][TPU] How to perform preprocessing steps for text classification for training on TPU?

### ISSUE THREAD

**Issue by rishabhsahrawat** [tensorflow/tensorflow#31925]
I have been trying since 5 days to train a simple text classification model on TPUs. But because of lack of documentation it is very difficult. I just can not perform tokenization, encoding, padding without `tf.py_func`. Please add some examples for doing these steps for TPU devices so that dumb people like me can understand TF. Will be greatly thankful to everyone at Google.
I am following this [tutorial](https://www.tensorflow.org/beta/tutorials/load_data/text#split_the_dataset_into_text_and_train_batches).

**Comment by rishabhsahrawat** [comment]
@jvishnuvardhan @MarkDaoust Hello, is there any update?. I am still struggling with the problem.

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.

**Comment by MarkDaoust** [comment]
We've since rewritten that tutorial. [This one](https://www.tensorflow.org/tutorials/text/solve_glue_tasks_using_bert_on_tpu) also trains a text model on TPU
