### ISSUE TITLE
 module 'tensorflow' has no attribute 'matvec'

### ISSUE THREAD

**Issue by CCHDjango** [tensorflow/tensorflow#31923]
I saw the file tensorflow/python/ops/math_ops.py  include matvec excample:

```
`# 2-D tensor `a`
  # [[1, 2, 3],
  #  [4, 5, 6]]
  a = tf.constant([1, 2, 3, 4, 5, 6], shape=[2, 3])

  # 1-D tensor `b`
  # [7, 9, 11]
  b = tf.constant([7, 9, 11], shape=[3])

  # `a` * `b`
  # [ 58,  64]
  c = tf.matvec(a, b)`
```

when I code that.

that error heppend:
`AttributeError: module 'tensorflow' has no attribute 'matvec'`

**Comment by oanush** [comment]
@CCHDjango ,
Can you please try using `tf.linalg.matvec(a,b)`,it should work fine.Thanks!

**Comment by AndrewChua85** [comment]
AttributeError: module 'tensorflow.linalg' has no attribute 'matvec'.  Can anyone advise?
