### ISSUE TITLE
Failed importing _pywrap_tensorflow

### ISSUE THREAD

**Issue by PanderBoy18** [tensorflow/tensorflow#31921]
Hi all, I have a problem.

After I installed tensorflow on my windows 10 machine with python 3.7.4
using this pip command: `pip install --user --upgrade tensorflow`

I want the CPU only version on a 64-bit version!

I was trying to verify the installation by running this command:
`python -c "import tensorflow as tf; print(tf.reduce_sum(tf.random.normal([1000, 1000])))"`

But that gives me the following error:

> Traceback (most recent call last):
>   File "C:\Users\Alexander\AppData\Local\Programs\Python\Python37-32\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 18, in swig_import_helper
>     fp, pathname, description = imp.find_module('_pywrap_tensorflow', [dirname(__file__)])
>   File "C:\Users\Alexander\AppData\Local\Programs\Python\Python37-32\lib\imp.py", line 296, in find_module
>     raise ImportError(_ERR_MSG.format(name), name=name)
> ImportError: No module named '_pywrap_tensorflow'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "C:\Users\Alexander\AppData\Local\Programs\Python\Python37-32\lib\site-packages\tensorflow\python\__init__.py", line 66, in <module>
>     from tensorflow.python import pywrap_tensorflow
>   File "C:\Users\Alexander\AppData\Local\Programs\Python\Python37-32\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 28, in <module>
>     _pywrap_tensorflow = swig_import_helper()
>   File "C:\Users\Alexander\AppData\Local\Programs\Python\Python37-32\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 20, in swig_import_helper
>     import _pywrap_tensorflow
> ModuleNotFoundError: No module named '_pywrap_tensorflow'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "<string>", line 1, in <module>
>   File "C:\Users\Alexander\AppData\Local\Programs\Python\Python37-32\lib\site-packages\tensorflow\__init__.py", line 24, in <module>
>     from tensorflow.python import *
>   File "C:\Users\Alexander\AppData\Local\Programs\Python\Python37-32\lib\site-packages\tensorflow\python\__init__.py", line 72, in <module>
>     raise ImportError(msg)
> ImportError: Traceback (most recent call last):
>   File "C:\Users\Alexander\AppData\Local\Programs\Python\Python37-32\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 18, in swig_import_helper
>     fp, pathname, description = imp.find_module('_pywrap_tensorflow', [dirname(__file__)])
>   File "C:\Users\Alexander\AppData\Local\Programs\Python\Python37-32\lib\imp.py", line 296, in find_module
>     raise ImportError(_ERR_MSG.format(name), name=name)
> ImportError: No module named '_pywrap_tensorflow'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "C:\Users\Alexander\AppData\Local\Programs\Python\Python37-32\lib\site-packages\tensorflow\python\__init__.py", line 66, in <module>
>     from tensorflow.python import pywrap_tensorflow
>   File "C:\Users\Alexander\AppData\Local\Programs\Python\Python37-32\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 28, in <module>
>     _pywrap_tensorflow = swig_import_helper()
>   File "C:\Users\Alexander\AppData\Local\Programs\Python\Python37-32\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 20, in swig_import_helper
>     import _pywrap_tensorflow
> ModuleNotFoundError: No module named '_pywrap_tensorflow'
> 
> 
> Failed to load the native TensorFlow runtime.
> 
> See https://github.com/tensorflow/tensorflow/blob/master/tensorflow/g3doc/get_started/os_setup.md#import_error
> 
> for some common reasons and solutions.  Include the entire stack trace
> above this error message when asking for help.
 
I have already tried reinstalling: Microsoft Visual C++ 2015 Redistributable Update 3, according to this issue here: [https://github.com/tensorflow/tensorflow/issues/7529](https://github.com/tensorflow/tensorflow/issues/7529)
But that didn't work....

I am not missing a the dll file called: MSVCP140.DLL!

How can I fix this?

**Comment by ymodak** [comment]
TensorFlow release binaries version 1.6 and higher are prebuilt with AVX instruction sets.
Therefore on any CPU that does not have these instruction sets, either CPU or GPU version of TF will fail to load.
What is your CPU make/model?

**Comment by PanderBoy18** [comment]
Which commando should I use to install version 1.5?

**Comment by gadagashwini** [comment]
@PanderBoy18,
Try below command to install tensorflow 1.5
`pip3 install tensorflow==1.5`
Let us know how it progresses. Thanks!

**Comment by gadagashwini** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
