### ISSUE TITLE
2019-08-23 nightlies missing `tf.summary` symbols

### ISSUE THREAD

**Issue by wchargin** [tensorflow/tensorflow#31931]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): gLinux (like Debian)
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): `tf-nightly-2.0-preview==2.0.0.dev20190823`
- TensorFlow version (use command below): `2.0.0-dev20190823`
- Python version: 3.6
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**

```
$ virtualenv -q -p python3.6 ./ve
$ . ./ve/bin/activate
(ve) $ pip install -q tf-nightly-2.0-preview==2.0.0.dev20190823
(ve) $ python
Python 3.6.7 (default, Oct 21 2018, 08:08:16) 
[GCC 8.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
>>> tf.__version__
'2.0.0-dev20190823'
>>> tf.summary.create_file_writer
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'tensorboard.summary._tf.summary' has no attribute 'create_file_writer'
>>> tf.summary.write
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'tensorboard.summary._tf.summary' has no attribute 'write'
```

**Describe the expected behavior**

These symbols should exist (they’re documented, for one).

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

See above.

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

Not due to a regression in TensorBoard; our nightlies did not ship today
because our smoke test caught this.

**Comment by wchargin** [comment]
cc @mihaimaruseac ; anything new here?

**Comment by wchargin** [comment]
Googlers: <http://b/139924752>

**Comment by mihaimaruseac** [comment]
This seems to be caused by bad interaction between virtual pip, lazy loading and relative imports.

**Comment by wchargin** [comment]
A change to TensorBoard to pick up the new APIs should fix this:
<https://github.com/tensorflow/tensorboard/pull/2593>

I’ll re-trigger today’s `tb-nightly` upload, which should resolve the
problem for future installs.

**Comment by wchargin** [comment]
Fixed:

```
$ virtualenv -q -p python3.6 ./ve
$ . ./ve/bin/activate
(ve) $ pip install -q -I tf-nightly-2.0-preview==2.0.0.dev20190823
(ve) $ pip freeze | grep -e tf-nightly -e tb-nightly
tb-nightly==1.15.0a20190823
tf-nightly-2.0-preview==2.0.0.dev20190823
(ve) $ python
Python 3.6.7 (default, Oct 21 2018, 08:08:16) 
[GCC 8.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
>>> tf.__version__
'2.0.0-dev20190823'
>>> tf.summary.create_file_writer
<function create_file_writer_v2 at 0x7fac87b68bf8>
>>> tf.summary.write
<function write at 0x7fac87b6c1e0>
```
