### ISSUE TITLE
Pip install can't find tensorflow2.0.0rc0

### ISSUE THREAD

**Issue by besirkurtulmus** [tensorflow/tensorflow#31939]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 16.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: Nope
- TensorFlow installed from (source or binary): wheel file via pip
- TensorFlow version: tensorflow==2.0.0rc0
- Python version: python3.7
- Installed using virtualenv? pip? conda?: pip
- Bazel version (if compiling from source): not source
- GCC/Compiler version (if compiling from source): not source
- CUDA/cuDNN version: not GPU
- GPU model and memory: not GPU

**Describe the problem**

**Provide the exact sequence of commands / steps that you executed before running into the problem**

When you pip install tensorflow==2.0.0rc0, you get an error message saying that pip can't find a matching version of the distribution that't given.

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

```
Step 5/11 : RUN /usr/local/bin/algorithmia-build
 ---> Running in 229b8273366c
Collecting algorithmia<2.0,>=1.0.0 (from -r requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/12/ae/38a82aae155a42261621eaba0a878959a0af93bf2d70d0ba98048ddaa3d2/algorithmia-1.2.0-py2.py3-none-any.whl
Requirement already satisfied: six in /usr/local/lib/python3.7/site-packages (from -r requirements.txt (line 2)) (1.12.0)
Collecting pip==19.2.2 (from -r requirements.txt (line 3))
  Downloading https://files.pythonhosted.org/packages/8d/07/f7d7ced2f97ca3098c16565efbe6b15fafcba53e8d9bdb431e09140514b0/pip-19.2.2-py2.py3-none-any.whl (1.4MB)
Collecting tensorflow-gpu==2.0.0rc0 (from -r requirements.txt (line 4))
[91m  Could not find a version that satisfies the requirement tensorflow-gpu==2.0.0rc0 (from -r requirements.txt (line 4)) (from versions: 1.13.0rc1, 1.13.0rc2, 1.13.1, 1.13.2, 1.14.0rc0, 1.14.0rc1, 1.14.0, 2.0.0a0, 2.0.0b0, 2.0.0b1)
[0m[91mNo matching distribution found for tensorflow-gpu==2.0.0rc0 (from -r requirements.txt (line 4))
[0m[91mYou are using pip version 18.1, however version 19.2.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
[0mRemoving intermediate container 229b8273366c
The command '/bin/sh -c /usr/local/bin/algorithmia-build' returned a non-zero code: 1
```

**Comment by besirkurtulmus** [comment]
Looks like `tensorflow2.0.0rc0` moved away from the `manylinux1` tag to the `manylinux2010` tag.

The `manylinux2010` tag is only supported w/ pip version `19` and above.

To fix this bug/issue, update pip via:

```
pip install -U pip
```

**Comment by moraywheel** [comment]
I'm using pip 19.2.2 and I get the same error.

**Comment by akanyaani** [comment]
Run this command, this worked for me.

`pip install --upgrade tensorflow-gpu==2.0.0-rc0`

**Comment by gadagashwini** [comment]
@besirkurtulmus,
For Tensorflow CPU version try,
`pip install --upgrade tensorflow==2.0.0-rc0`
Let us know if that helps. Thanks!

**Comment by besirkurtulmus** [comment]
> @besirkurtulmus,
> For Tensorflow CPU version try,
> `pip install --upgrade tensorflow==2.0.0-rc0`
> Let us know if that helps. Thanks!

This now works. Did you guys make a fix?

**Comment by Crazychicken563** [comment]
I am having this exact issue right now
OS - Windows 7 64 bit
PIP version 19.2.3
Python version 3.7.4

`pip install --upgrade tensorflow==2.0.0-rc0
Collecting tensorflow==2.0.0-rc0
  ERROR: Could not find a version that satisfies the requirement tensorflow==2.0.0-rc0 (from versions: none)
ERROR: No matching distribution found for tensorflow==2.0.0-rc0`

**Comment by mihaimaruseac** [comment]
Can you try `pip install --upgrade -v tensorflow==2.0.0rc0` and post the full log?

**Comment by Crazychicken563** [comment]
https://pastebin.com/QKMjueDJ

**Comment by mihaimaruseac** [comment]
Just to be sure, can you also try `python3 -m pip install --upgrade pip && python3 -m pip install --upgrade -v tensorflow==2.0.0rc0` and post the full log there?

I have a nagging feeling that `pip` is running from a different interpreter than the one you're installing TF from

**Comment by Crazychicken563** [comment]
Powershell says `python3` isnt a command i can run...

**Comment by Crazychicken563** [comment]
`PS C:\Users\Seva> python --version
Python 3.7.4
PS C:\Users\Seva> python3
The term 'python3' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spe
lling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:8
+ python3 <<<<
    + CategoryInfo          : ObjectNotFound: (python3:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

PS C:\Users\Seva>`

really odd

**Comment by charmscale** [comment]
Having the exact same issue.

**Comment by Crazychicken563** [comment]
I figure it's because I only have py -3 available, so running `python` is equivalent to `python3`
Regardless, I ran that command as `python3 -m pip install --upgrade pip && python3 -m pip install --upgrade -v tensorflow==2.0.0rc0` and got the same error, other than pip telling me it was already up to date

**Comment by charmscale** [comment]
Tried that too.

**Comment by mihaimaruseac** [comment]
These all seem issues with the environment. I'd suggest looking at the detailed logs from `python -m pip install --upgrade -vvv tensorflow==2.0.0rc0` (3 `v`s, the maximum verbosity level).

**Comment by gadagashwini** [comment]
@charmscale, Did you get a chance to look @mihaimaruseac's comment. Thanks!

**Comment by vibwipro** [comment]
I am also getting similar issue... 
![image](https://user-images.githubusercontent.com/49004578/64326664-a9c34180-cfca-11e9-8ffc-a678317fc67b.png)

**Comment by mihaimaruseac** [comment]
`python -m pip install --upgrade pip && python -m pip install --upgrade setuptools && python -m pip install --upgrade tensorflow`

If this still fails, add `-vvv` just before `tensorflow` and post the full log _as attachment_, not as image

**Comment by vibwipro** [comment]
Thanks for suggestion, but it didn't worked. Please find below attached logs : - 
https://pastebin.com/wmHbFzqn

**Comment by mihaimaruseac** [comment]
Try `python -c ‘import pip; print(pip.pep425tags.get_supported())`

**Comment by Indseta** [comment]
I got all the same issues as everyone else and this is the output I got.


**Microsoft** Windows [Version 10.0.18362.295]
(c) 2019 Microsoft Corporation. Med enerett.

C:\Users\[USER] > pip debug --verbose
WARNING: This command is only meant for debugging. Do not use this with automation for parsing and getting these details, since the output and options of this command may change without notice.
pip version: pip 19.2.3 from d:\program files (x86)\python 3.6.8\lib\site-packages\pip (python 3.6)
sys.version: 3.6.8 (tags/v3.6.8:3c6b436a57, Dec 23 2018, 23:31:17) [MSC v.1916 32 bit (Intel)]
sys.executable: d:\program files (x86)\python 3.6.8\python.exe
sys.getdefaultencoding: utf-8
sys.getfilesystemencoding: utf-8
locale.getpreferredencoding: cp1252
sys.platform: win32
sys.implementation:
  name: cpython
Config variable 'Py_DEBUG' is unset, Python ABI tag may be incorrect
Config variable 'WITH_PYMALLOC' is unset, Python ABI tag may be incorrect
Compatible tags: 13
  cp36-cp36m-win32
  cp36-none-win32
  py3-none-win32
  cp36-none-any
  cp3-none-any
  py36-none-any
  py3-none-any
  py35-none-any
  py34-none-any
  py33-none-any
  py32-none-any
  py31-none-any
  py30-none-any**

**Comment by mihaimaruseac** [comment]
@Indseta it's because you're using a 32 bits CPU and we're releasing for 64 bits CPUs

**Comment by vibwipro** [comment]
But by system has 64 bit OS 
![image](https://user-images.githubusercontent.com/49004578/64472489-85e53480-d15f-11e9-82c5-60d1f6ecbd12.png)

**Comment by lordvissu** [comment]
> `python -m pip install --upgrade pip && python -m pip install --upgrade setuptools && python -m pip install --upgrade tensorflow`
> 
> If this still fails, add `-vvv` just before `tensorflow` and post the full log _as attachment_, not as image

https://pastebin.com/kE0WMwzA



> pip debug --verbose

https://pastebin.com/dUTzee3Z

I am trying to install tensorflow in a virtualenvironment through anaconda prompt. I am a beginner so please suggest accordingly.

**Comment by mihaimaruseac** [comment]
I think in both of these cases you installed a 32 bits Python. Please install a 64 bits one if your CPU is 64 bits.

For 32 bits support see #32315

**Comment by vibwipro** [comment]
Thanks for your suggestion.
Will same solution also work for libraries OpenCV and face_recognition ? 
Because both libraries are having similar installation issues on my system or any other solution will work for them to get fixed. Thanks.

**Comment by mihaimaruseac** [comment]
Recommend StackOverflow for this, no idea if same solution would work there and cannot extrapolate.

**Comment by reliefs** [comment]
> Thanks for your suggestion.
> Will same solution also work for libraries OpenCV and face_recognition ?
> Because both libraries are having similar installation issues on my system or any other solution will work for them to get fixed. Thanks.

If you are having issues with face_recognition because of mtcnn module i suggest using my fix, it works for tensorflow 2.0.

https://github.com/reliefs/mtcnn-tensorflow2

https://github.com/ipazc/mtcnn/issues/47

**Comment by gadagashwini** [comment]
Looks like original issue reported here is resolved. Please feel free to reopen if issue still persists. Thanks!

**Comment by nonlin** [comment]
I reinstalled python and was able to run the two commands for upgrading pip and then installing tensorflow.

**Comment by rahulsrivastava1519** [comment]
> I think in both of these cases you installed a 32 bits Python. Please install a 64 bits one if your CPU is 64 bits.
> 
> For 32 bits support see #32315

This ans is right please check python version

**Comment by anujmca** [comment]
I was also facing the same issue, essentially the reason was tensorflow wheel file is not available for 32 bit system. They also not planning to publish 32 bit version this year, as it takes lots of effort at their end and it was not in their planning.

So, I solved it by changing my installation of python 32 bit to python 64 bit.

**Comment by mihaimaruseac** [comment]
As mentioned: if you really have a 32bits CPU (unlikely as these are very old), see #32315 

If your CPU is 64 bits, please install a 64 bits Python.

**Comment by reliefs** [comment]
https://github.com/tensorflow/tensorflow/issues/32627

**Comment by rsjain1978** [comment]
On my windows machine, I was facing same issue while running _pip install tensorflow==2.0.0-rc1_ though I was on latest version of pip and on 64-bit distribution for python.
Oddly enough, I face this issue when I am running the pip install inside a virtual environment. If i deactivate from my virtual env. I do not get this issue.

Will continue to investigate if I could find anything more.

Thanks

**Comment by mihaimaruseac** [comment]
@rsjain1978 Can you check if you have both 32 bits and 64 bits binaries in your system? It's very likely that somehow the virtualenv python is 32 bits.

Alternatively, you can compare output of `pip debug --verbose` outside and inside the virtualenv. That should point out these differences very quickly.

**Comment by aquib1011** [comment]
C:\Users\User\Desktop\number_recognition\venv\Scripts\python.exe "C:/Users/User/Desktop/number_recognition/number _recog.py"
Using TensorFlow backend.
Traceback (most recent call last):
  File "C:\Users\User\Desktop\number_recognition\venv\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\User\Desktop\number_recognition\venv\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\User\Desktop\number_recognition\venv\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Users\User\AppData\Local\Programs\Python\Python38\lib\imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\User\AppData\Local\Programs\Python\Python38\lib\imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: DLL load failed while importing _pywrap_tensorflow_internal: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/User/Desktop/number_recognition/number _recog.py", line 6, in <module>
    from keras.preprocessing.image import ImageDataGenerator
  File "C:\Users\User\AppData\Local\Programs\Python\Python38\lib\site-packages\keras\__init__.py", line 3, in <module>
    from . import utils
  File "C:\Users\User\AppData\Local\Programs\Python\Python38\lib\site-packages\keras\utils\__init__.py", line 6, in <module>
    from . import conv_utils
  File "C:\Users\User\AppData\Local\Programs\Python\Python38\lib\site-packages\keras\utils\conv_utils.py", line 9, in <module>
    from .. import backend as K
  File "C:\Users\User\AppData\Local\Programs\Python\Python38\lib\site-packages\keras\backend\__init__.py", line 1, in <module>
    from .load_backend import epsilon
  File "C:\Users\User\AppData\Local\Programs\Python\Python38\lib\site-packages\keras\backend\load_backend.py", line 90, in <module>
    from .tensorflow_backend import *
  File "C:\Users\User\AppData\Local\Programs\Python\Python38\lib\site-packages\keras\backend\tensorflow_backend.py", line 5, in <module>
    import tensorflow as tf
  File "C:\Users\User\Desktop\number_recognition\venv\lib\site-packages\tensorflow\__init__.py", line 41, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "C:\Users\User\Desktop\number_recognition\venv\lib\site-packages\tensorflow\python\__init__.py", line 50, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Users\User\Desktop\number_recognition\venv\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 69, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "C:\Users\User\Desktop\number_recognition\venv\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\User\Desktop\number_recognition\venv\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\User\Desktop\number_recognition\venv\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Users\User\AppData\Local\Programs\Python\Python38\lib\imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\User\AppData\Local\Programs\Python\Python38\lib\imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: DLL load failed while importing _pywrap_tensorflow_internal: The specified module could not be found.


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

Process finished with exit code 1
