### ISSUE TITLE
AttributeError: 'LinearClassifier' object has no attribute 'save'

### ISSUE THREAD

**Issue by Vijayenthiran** [tensorflow/tensorflow#3193]
### Environment info
Operating System:
OS X 10.11.5

Installed version of CUDA and cuDNN: 
(please attach the output of `ls -l /path/to/cuda/lib/libcud*`):
NA

If installed from binary pip package, provide:

1. Which pip package you installed.
2. The output from `python -c "import tensorflow; print(tensorflow.__version__)"`.

Tensor Flow verison: `0.9`

If installed from sources, provide the commit hash:
Commit Hash:` 70de76e696c21da617fd2e6435cf7fedab220db8`

### Steps to reproduce
1. Run the example commands give at [sklearn doc](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/contrib/learn/python/learn#linear-classifier)
2. Try to save the model with .save() function [sklearn doc](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/contrib/learn/python/learn#saving--restoring-models)

### What have you tried?
1. I tried using `tf.train.Saver()` but I guess it can save the session but not the classifier.

### Logs or other output that would be helpful
(If logs are large, please upload as attachment).

```python
Python 2.7.10 (default, Oct 23 2015, 19:19:21) 
[GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.0.59.5)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow.contrib.learn as learn
>>> from sklearn import datasets, metrics
>>> iris = datasets.load_iris()
>>> classifier = learn.LinearClassifier(n_classes=3)
>>> classifier.fit(iris.data, iris.target, steps=200, batch_size=32)
LinearClassifier()
>>> classifier.save('/tmp/tf_examples/my_model_1/')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'LinearClassifier' object has no attribute 'save'
>>> import tensorflow as tf
>>> saver = tf.train.Saver()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/Vijay/Library/Python/2.7/lib/python/site-packages/tensorflow/python/training/saver.py", line 837, in __init__
    raise ValueError("No variables to save")
ValueError: No variables to save
>>> 
```

**Comment by aselle** [comment]
Correct me if I'm wrong @martinwicke, I believe that if you specify model_dir to the classifier constructor, you will get an autosaved model i.e.
```python
import tensorflow.contrib.learn as learn

def input_fn():
    foo=tf.constant([1.,2.,3.])
    bar=tf.constant([0,1,0])
    return {"x":foo}, bar
classifier = learn.LinearClassifier(n_classes=3,model_dir="/tmp/cool-awesome-model")
classifier.fit(input_fn=input_fn, steps=200)

```
Let me know if this fixes your issue.

**Comment by Vijayenthiran** [comment]
Thanks @aselle. Providing model_dir parameter to the classifier worked. It saved 8 files in a folder. I was expecting one `.ckpt` file.
How do I restore this classifier? `learn.Estimator.restore()` does not work.

**Comment by martinwicke** [comment]
Right now that's a bit of a mess. Provide the same model_dir, call fit
again (you can pass max_steps to prevent it from actually doing anything),
then predict should work.

We're working on re-enabling proper save/restore.

**Comment by Vijayenthiran** [comment]
@martinwicke Pardon my daftness, `classifier.fit()` doesn't seems to accept `max_steps` are parameter. Can you provide an example?

**Comment by martinwicke** [comment]
Oh sorry. That is at master but not in 0.9. You should be able to use the
steps argument. Just be warned that we're in the process of changing this.

**Comment by Vijayenthiran** [comment]
Will be good if these are updated in the docs. :)

**Comment by concretevitamin** [comment]
Since Martin has provided the workaround, I am closing this.  (Please feel free to file a separate issue about updating the docs; although as already mentioned this code path is in heavy development now.)
