### ISSUE TITLE
win10 Creating a Virtual Environment

### ISSUE THREAD

**Issue by zouhanting** [tensorflow/tensorflow#31942]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):window10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):do not install 
- TensorFlow version:do not install 
- Python version:3.6
- Installed using virtualenv? pip? conda?:pip
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 10.1/7.6.3 
- GPU model and memory: Geforce GTX 1060

**Describe the problem**
the command do not run.
C:\>virtualenv --system-site-packages -p python3 ./venv
The path python3 (from --python=python3) does not exist

**Provide the exact sequence of commands / steps that you executed before running into the problem**
According to tenserflow website install tenserflow with pip in windows10 system. Python3.6 was installed in my computer.

C:\>pip3 --version
pip 19.2.2 from c:\program files\python36\lib\site-packages\pip (python 3.6)

C:\>virtualenv --version
16.7.4

C:\>virtualenv --system-site-packages -p python3 ./venv
The path python3 (from --python=python3) does not exist

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by gadagashwini** [comment]
@zouhanting,
Please follow the steps below to install Tensorflow using pip and by creating virtual env
```
pip install virtualenv 
virtualenv tensorflow     #virtual env name : tensorflow
tensorflow\Scripts\activate
tensorflow>>pip install tensorflow==1.14.0   #mention version of your interest

```
Let us know how it progresses. Thanks!

**Comment by gadagashwini** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
