### ISSUE TITLE
[TensorFlow Lite] GPU delegates on Android with GPU nightly fail to run on GPU (it seems to run on CPU)

### ISSUE THREAD

**Issue by val9299** [tensorflow/tensorflow#31948]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): 
no (for the demo APP & classification APP); 
yes (for the object detection APP), but only added GPU delegate and used a self-converted SSD float model
- Mobile device: Google Pixel 2 XL (Android 8.0.0 and Android 9)
- TensorFlow Lite version: nightly 0.0.0 + GPU nightly 0.0.0
- OS Platform and Distribution: Windows 10 64 bit
- TensorFlow installed from: binary
- TensorFlow version: 1.13.1
- Python version: 3.6.8
- CUDA/cuDNN version: 10.0 / 7.6.0
- GPU model and memory: GeForce GTX 970, AMD64

**Describe the current behavior**
I cannot get any APP to run on GPU using GPU nightly. All the APPs seem to run on CPU even though the GPU delegates are used by the interpreter and no error occurs.

**Describe the expected behavior**
The APPs should run on GPU. The models running on GPU should be faster than the models running on CPU.

**Code to reproduce the issue**
I tried the demo APP and the classification APP without changes to the code. For the object detection APP I added the GPU delegate, changed isQuantized to false, and I use a self-converted SSD mobilenet model. I wrote the delegate as described in https://www.tensorflow.org/lite/performance/gpu_advanced#android_java and I converted the model this way: https://github.com/tensorflow/tensorflow/issues/31015#issuecomment-517165233.

- Demo APP: https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/java/demo
- Classification APP: https://github.com/tensorflow/examples/tree/master/lite/examples/image_classification/android
- Object Detection APP: https://github.com/tensorflow/examples/tree/master/lite/examples/object_detection/android

**Other info / logs**
Performance results testing the APPs on Google Pixel 2 XL (with Android 8.0.0 and Android 9):

_GPU nightly:_
Current demo APP
- Quantized Model + CPU -> 75ms
- Float Model + CPU -> 135ms
- Float Model + GPU -> **135ms**

Object Detection APP 
- (self-converted) Float Model + GPU -> **100 ms**

_CPU only_:
Objekt Detection APP (I only changed targedSdkVersion to 28 to get the original code working):
- Quantized Model + CPU -> 45-50ms

Thanks in advance!

**Comment by zychen2016** [comment]
```
CPU only:
Objekt Detection APP (I only changed targedSdkVersion to 28 to get the original code working):

Quantized Model + CPU -> 45-50ms
```

could you tell me that what is the  "Quantized Model"  ? ssd_mobilenet_v1 or v2?

**Comment by val9299** [comment]
> ```
> CPU only:
> Objekt Detection APP (I only changed targedSdkVersion to 28 to get the original code working):
> 
> Quantized Model + CPU -> 45-50ms
> ```
> 
> could you tell me that what is the "Quantized Model" ? ssd_mobilenet_v1 or v2?

The model which is used automatically by the Object Detection APP without changing anything. (I don't know anymore which model it was.)

**Comment by impjdi** [comment]
My apologies that I didn't respond to this issue.  Must have slipped and then dropped off my radar completely.

According to your description of:

```
Float Model + CPU -> 135ms
Float Model + GPU -> 135ms
```

It looks like it's not benefitting from GPU at all, probably due to some incompatible op.  If you check the logs, you might see something like "only xxx ops are covered by the GPU, and rest by the CPU" or something in that line, when you call `modifyGraphWithDelegate`.   You may want to start from there.

**Comment by val9299** [comment]
Does GPU-nightly support other ops than GPU-experimental? Because with GPU-experimental the demo APP works perfectly: https://github.com/tensorflow/tensorflow/issues/31949

I'm not working on it anymore and the group decided on experimental, so nightly is not needed anymore. But thanks for the response!

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.
