### ISSUE TITLE
TPUStrategy with Keras in TF2.0.0rc0

### ISSUE THREAD

**Issue by nsantavas** [tensorflow/tensorflow#31954]
Hi,

Although the description of TF 2.0.0rc0 contains this
 _"Distribution Strategy: TF 2.0 users will be able to use the tf.distribute.Strategy API to distribute training with minimal code changes, yielding great out-of-the-box performance. It supports distributed training with Keras model.fit, as well as with custom training loops. Multi-GPU support is available, along with experimental support for multi worker and Cloud TPUs. Check out the guide for more details."_

When I try to implemented it with Keras and multiple TPU units, crashes with _"NotImplementedError: Using multiple TPUs in a single session is not yet implemented"_

So, is supported TPUStrategy with keras in this release or not?

Thank you

**Comment by gadagashwini** [comment]
@nsantavas, will it be possible to provide sample code to investigate the issue. Thanks!

**Comment by nsantavas** [comment]
@gadagashwini 
```
################ TPU Initialization ##################
tpu='tf2'
tpu1='tf2-2'

cluster_resolver = tf.distribute.cluster_resolver.TPUClusterResolver(
    tpu=[tpu, tpu1])
tf.config.experimental_connect_to_host(cluster_resolver.master())
tf.tpu.experimental.initialize_tpu_system(cluster_resolver)
strategy = tf.distribute.experimental.TPUStrategy(cluster_resolver)

######################################################
with strategy.scope():
    model=create_model()

model.fit(get_training_dataset, validation_data=get_validation_dataset, steps_per_epoch=steps_per_epoch ,validation_steps=val_steps, epochs=EPOCHS, verbose=1, initial_epoch=0, callbacks=clbk)

```

**Comment by gadagashwini** [comment]
Closing this issue since its answered. Thanks!
