### ISSUE TITLE
Documentation of Session arguments seems outdated

### ISSUE THREAD

**Issue by rizar** [tensorflow/tensorflow#3195]
In [README.md](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/public/README.md) a session is created as `tf.Session("local")`. At the same time, the [docstring](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/client/session.py#L888) says "no value other than an empty string is supported". This is clearly an inconsistency.

**Comment by aselle** [comment]
The documentation is incorrect. You should probably be using tf.Session() most of the time. so we will updates the tf.Session() docstring as well ad the README.md.
See here for another example https://www.tensorflow.org/versions/r0.9/how_tos/distributed/index.html.
