### ISSUE TITLE
Select compiler for building

### ISSUE THREAD

**Issue by ghost** [tensorflow/tensorflow#31967]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using):
1.14

- Are you willing to contribute it (Yes/No):

Yes

**Describe the feature and the current behavior/state.**
Select the compiler to use for building in configure.py

**Will this change the current api? How?**

I don't think so.

**Who will benefit with this feature?**

Everyone who needs it

**Any Other info.**

Is it possible in the python configure script to choose the compiler when building on a non-linux? On windows, I have several compilers, but the script always selects the wrong compiler. On linux, it asks for the compiler to use, but doesn't on other systems. I will try to see how the script works so it can detect the compilers and let the user select it so it won't choose the wrong compiler or version.

**Comment by ArtificialLifeforms** [comment]
[https://www.youtube.com/watch?v=jXZMvgFoqX0](url)

**Comment by gunan** [comment]
First of all, I am sorry to miss this issue.
I have a ton of github issues coming my way, and I am way behind on processing them.

These are all configured through bazel.
https://docs.bazel.build/versions/master/windows.html#using-bazel-on-windows-1

You can use environment variables to direct bazel to use different compilers.
As bazel has these configurations available more easily than python, we do not have them in the configure script.
