### ISSUE TITLE
Nightly builds 404 Not Found

### ISSUE THREAD

**Issue by KendallWeihe** [tensorflow/tensorflow#3196]
I'm getting a 404 error on trying to download all nightly builds: https://github.com/tensorflow/tensorflow#installation

**Comment by aselle** [comment]
The links here do not seem to work https://github.com/tensorflow/tensorflow#installation
The links here do work https://www.tensorflow.org/versions/r0.9/get_started/os_setup.html#optional-install-cuda-gpus-on-linux

**Comment by martinwicke** [comment]
caisq@ can you look at this? I think either the cp commands in the builds need to be updated, or we should just adjust the links.

**Comment by KendallWeihe** [comment]
@aselle I need the nightly builds. I don't see any nightly builds in the second link. I need `conv3d_transpose` added here: https://github.com/tensorflow/tensorflow/pull/3049#issuecomment-229742733

**Comment by martinwicke** [comment]
If you click on the "build history" links, you can click through to the
actual file from there.

**Comment by KendallWeihe** [comment]
@martinwicke I'm missing the "build history" link. You're saying it's on this page right? https://www.tensorflow.org/versions/r0.9/get_started/os_setup.html#optional-install-cuda-gpus-on-linux

(that's what @aselle linked) I actually just need the latest Python 3.5 build for linux

**Comment by martinwicke** [comment]
They're in the readme: 
CPU: http://ci.tensorflow.org/view/Nightly/job/nightly-python35-linux-cpu/
GPU: http://ci.tensorflow.org/view/Nightly/job/nigntly-matrix-linux-gpu/TF_BUILD_CONTAINER_TYPE=GPU,TF_BUILD_IS_OPT=OPT,TF_BUILD_IS_PIP=PIP,TF_BUILD_PYTHON_VERSION=PYTHON3.5,label=gpu-linux/

**Comment by KendallWeihe** [comment]
@martinwicke when I install that build it installs it in python 3.4?

**Comment by martinwicke** [comment]
That's the 3.5 link, so no. The top level readme contains the nightly build
history links.

**Comment by KendallWeihe** [comment]
Why would it be installing in python 3.4? When I run `python3.5 tensorflow_project.py` it gives me `no module named tensorflow` and I have confirmed it isn't in the python 3.5 directory. But I have also confirmed that when I run that installation, it refreshes my python 3.4 directory.

**Comment by martinwicke** [comment]
That probably just means your pip is setup for your Python 3.4.

**Comment by KendallWeihe** [comment]
I am unable to find any support for installing pip for python 3.5. I've tried upgrading `sudo pip -U pip` but it tells me it is already up to date. 

I've outlined everything here: http://stackoverflow.com/questions/38249961/install-pip-for-python-3-5

Any help?

**Comment by martinwicke** [comment]
You did the right thing, Stackoverflow is the place to ask these questions.

**Comment by lahwran** [comment]
http://ci.tensorflow.org/view/Nightly/job/nigntly-matrix-linux-gpu/TF_BUILD_CONTAINER_TYPE=GPU,TF_BUILD_IS_OPT=OPT,TF_BUILD_IS_PIP=PIP,TF_BUILD_PYTHON_VERSION=PYTHON2,label=gpu-linux/150/

as of build 151, the name changed from none-linux to none-any.

**Comment by gunan** [comment]
Website is also updated (many many times since this issue :) ) to point to correct URLs.
Closing this issue.
