### ISSUE TITLE
No description for / option to select non default cuda location when building TF2.0 from source

### ISSUE THREAD

**Issue by nikste** [tensorflow/tensorflow#31960]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>
commit hash:
553a3b826a55acb78de18ca6dbca8c965c7cf78e

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 16.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): source
- TensorFlow version: 2.0rc0
- Python version: 3.7.3
- Installed using virtualenv? pip? conda?: none
- Bazel version (if compiling from source): 0.26.1
- GCC/Compiler version (if compiling from source): 5.4
- CUDA/cuDNN version: 9.1 + 10.1
- GPU model and memory: various

Option/Description how to select a non-default cuda path missing.

I am working on a shared server with cuda 9.1 in /usr/local/cuda/
I want to build tensorflow 2.0 rc0 from source using a different cuda version in a different location.

Executing ./configure it automatically selects the default one and i do not have an option to select a different one.

Documentation
https://www.tensorflow.org/install/source#tensorflow_2
only says: ```If your system has multiple versions of CUDA or cuDNN installed, explicitly set the version instead of relying on the default```

**Provide the exact sequence of commands / steps that you executed before running into the problem**
`./configure`

**Comment by nikste** [comment]
sure, what kind of log do you want me to provide?
setting `TF_CUDA_PATHS` i was able to get it to chose the right path, but it will still not ask for a custom location

**Comment by angersson** [comment]
The entire shell log of executing this would be helpful:

```
$ env | grep TF_
$ ./configure (or however you've been executing it)
```

**Comment by nikste** [comment]
`$ env | grep TF_` shows nothing
output of `$ ./confgure` is attached

[logoutput_tf.txt](https://github.com/tensorflow/tensorflow/files/3562657/logoutput_tf.txt)

**Comment by nikste** [comment]
its a slurm managed cluster and I'm loading cuda 10.0 as an additional module if that helps

**Comment by angerson** [comment]
It looks like `third_party/gpus/find_cuda_config.py` eagerly assumes that having CUDA installed in the system default configuration means that you want to use that CUDA installation. Since `TF_CUDA_PATHS` can be overridden, I'm closing this as WAI.

**Comment by nikste** [comment]
I don't think this is a good solution. I'd at least mention overriding `TF_CUDA_PATHS` in the docs somewhere.
