### ISSUE TITLE
ERROR: opt-einsum requires Python '>=3.5' but the running Python is 2.7.15

### ISSUE THREAD

**Issue by honeytidy** [tensorflow/tensorflow#31964]
I want upgrade tensorflow-gpu==2.0.0-beta to  tensorflow-gpu==2.0.0-rc0. I upgrade with the following command: 
`pip install tensorflow-gpu==2.0.0-rc0 -U`

I got an error like this:

```
  Downloading http://pypi.sys.srv/root/pypi/%2Bf/8ab/a07af4cf80e86/opt_einsum-3.0.1.tar.gz (66kB)
     |████████████████████████████████| 71kB 13.6MB/s 
ERROR: opt-einsum requires Python '>=3.5' but the running Python is 2.7.15
...
```
But it is ok for last version. How to solve the problem?

**Comment by xmfbit** [comment]
`pip install opt-einsum==2.3.2` works for me.

**Comment by ravikyram** [comment]
@honeytidy 
Can you please confirm if @xmfbit 's workaround is working for you.Thanks!

**Comment by ravikyram** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Comment by honeytidy** [comment]
pip install opt-einsum==2.3.2 works for me too. Thanks @xmfbit.

**Comment by aimetrics** [comment]
> `pip install opt-einsum==2.3.2` works for me.

works for me, too
