### ISSUE TITLE
Why HLO Importer doesn't support U32 type?

### ISSUE THREAD

**Issue by Naville** [tensorflow/tensorflow#31968]
Hi:
I am learning the internal data structure of Tensorflow and MLIR.  
I first used ``tfcompile --graph=graph.pb  --config=graph.config.pbtxt   --xla_dump_to="/tmp/" --cpp_class="mynamespace::MyComputation" --xla_dump_hlo_as_text=true`` and then extracted ``module_0000.after_optimizations.txt`` which if I understood this correctly is the lowered HLO IR from input TF GraphDef.

However when I pass this file into ``tf-mlir-translate --hlo-text-to-mlir-hlo /tmp/module_0000.after_optimizations.txt`` I got greeted with an internal error says 'Unsupported Type: U32'.

Is there any reason U32 isn't supported in HLO or am I missing something obvious here?

**Comment by oanush** [comment]
@Naville ,
Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version and provide more information on the issue.Thanks!
