### ISSUE TITLE
Tensorflow 2.0 tf.function internal error

### ISSUE THREAD

**Issue by mmv** [tensorflow/tensorflow#31962]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Colab, Ubuntu, Windows
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.0-beta, 2.0-rc, 2.0-nightly (v1.12.1-9694-g006e2933 2.0.0-dev20190825)
- Python version: 3.6
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 10, also without CUDA
- GPU model and memory:

**Describe the current behavior**
Decorating the training loop that consumes a `tf.Data.Dataset` with `@tf.function` causes an internal error in tensorflow (an object is returned to Python with an error set and I'm unable to understand the actual origin of the error). Not using `@tf.function`, the code works alright.

**Describe the expected behavior**
The model gradients should be calculated well regardless of being within a `@tf.function` trace or not.

**Code to reproduce the issue**
Code is provided in the [colab notebook available here](https://colab.research.google.com/drive/1LCZqyGa8mPjBS6KXOnEH_T7VOWoFpnnB)

**Other info / logs**
While working with a rather complex module that operates on irregular data (Graphs), using `@tf.function` worsens performance in TF 2.0 due to bug #29075. While following the workaround described in that issue, I stumbled upon this issue.

Because of these issues, TF 2.0 is not a good fit for DL on irregularly shaped data.

Relevant traceback:
```
    <ipython-input-8-e24395a4965a>:137 train_step  *
        gradients = tape.gradient(loss, model.trainable_variables)
    /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/eager/backprop.py:1015 gradient
        unconnected_gradients=unconnected_gradients)
    /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/eager/imperative_grad.py:76 imperative_grad
        compat.as_str(unconnected_gradients.value))
    /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/eager/backprop.py:599 _aggregate_grads
        if len(gradients) == 1:

    SystemError: <built-in function len> returned a result with an error set
```

**Comment by oanush** [comment]
I was able to replicate the issue in TF version 2.0 preview. Thanks!

**Comment by ericzhao28** [comment]
I was also able to replicate this error in the nightly 2.0 preview.

**Comment by mdanatg** [comment]
This is a very strange error, it seems to originate in the gradient calculation. It happens inside a `Dataset.reduce`, but I don't know if that's the reason it crashes; MainModel is fairly complex, though it doesn't seem to do anything dangerous as far as I can tell.

@saxenasaurabh, could you have a closer look at the error? Perhaps we can detect its root cause and raise a more specific error?

**Comment by sseveran** [comment]
Any updates on this? I can confirm this only is happening if I use tf.function.

**Comment by mjlbach** [comment]
I'm also having this error

**Comment by mdanatg** [comment]
This looks like a bug related to `GradientTape` and `Dataset`. A few workarounds:

1. Move the @tf.function to `train_step` (so that the dataset iteration is outside the tf.function). That also seems to speed things up, which might be another bug.

2. Use `tf.gradients` instead of `GradientTape`. The downside is that tf.gradients doesn't work in eager mode:

```
def train_step(xs, ys):
    ys_hat = model(xs, training=True)
    loss = loss_fn(ys, ys_hat)
    gradients = tf.gradients(loss, model.trainable_variables)
    optimizer.apply_gradients(zip(gradients, model.trainable_variables))

    train_loss(loss)
    train_metric(ys.edges, ys_hat.edges)
```

**Comment by mjlbach** [comment]
@mdanatg For now I applied https://github.com/tensorflow/tensorflow/pull/33497 locally which fixes the problem. Currently I'm already doing 1, I can try doing 2 as well.

**Comment by mdanatg** [comment]
I checked the colab posted by @mmv against tf-nightly and it looks like #33497 resolved the issue.
