### ISSUE TITLE
vs2015: c++ dependencies

### ISSUE THREAD

**Issue by YuBicheng** [tensorflow/tensorflow#31971]
I already build a tensorflow1.13r c++ lib with bazel0.21.0 .I found a problem when I try to create the VS project.
Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK2019	unresolved external symbol "char const * __cdecl tensorflow::core::GetVarint32PtrFallback(char const *,char const *,unsigned int *)" (?GetVarint32PtrFallback@core@tensorflow@@YAPEBDPEBD0PEAI@Z) referenced in function "char const * __cdecl tensorflow::core::GetVarint32Ptr(char const *,char const *,unsigned int *)" (?GetVarint32Ptr@core@tensorflow@@YAPEBDPEBD0PEAI@Z)	tensorflowc++test	E:\c++\tensorflowc++test\tensorflowc++test\t1.obj	1	

I know it meanings I haven't finishied the dependencies.But I don't know which .lib file should be includ. There are too many .lib files in bazel-out floder.
![cut](https://user-images.githubusercontent.com/23164484/63672466-979c1300-c814-11e9-9237-6ac7246f6814.png)

**Comment by oanush** [comment]
@YuBicheng ,
Can you please go through similar issue #[24885](https://github.com/tensorflow/tensorflow/issues/24885).Thanks!

**Comment by oanush** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
