### ISSUE TITLE
add l2 regularization and dropout

### ISSUE THREAD

**Issue by rubenstern** [tensorflow/tensorflow#3197]
Hi,

Is it posible to add l2 regularization and dropout in the text_classification_cnn.py ?

Thanks

**Comment by terrytangyuan** [comment]
@rubenstern You can use `contrib.layers.regularizers` found [here](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/layers/python/layers/regularizers.py)

**Comment by aselle** [comment]
@rubenstern, does this address your need. If so please close the bug.

**Comment by aselle** [comment]
Automatically closing due to lack of recent activity. Please reopen when further information becomes available.
