### ISSUE TITLE
[TF2.0] (rc0) Mocking tf.summary.image

### ISSUE THREAD

**Issue by RaphaelMeudec** [tensorflow/tensorflow#31976]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): `pip install tensorflow==2.0.0rc0` 
- TensorFlow version (use command below):
- Python version: 3.6.8
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: CPU version
- GPU model and memory: CPU version

**Problem**

I have been using successfully `unittest.mock.patch` on `tf.summary.image` with version `2.0.0-beta1`. When upgrading to `2.0.0rc0`, the mock doesn't appear anymore and the full function is used. I couldn't find the change that breaks this. Any idea how to perform the mock?

**Sample code**

The following code is a sample of `tf.summary.image` call inside a callback, and running a simple `.fit`. It runs perfectly on `2.0.0-beta1`, but fails on `2.0.0rc0`.

To reproduce, have those 2 snippets (`tf_write_summary.py` and `test_tf_write_summary.py`) in a folder and run `python -m pytest test_tf_write_summary.py`.

**`tf_write_summary.py`**
```python
from datetime import datetime
from pathlib import Path

import tensorflow as tf
from tensorflow.keras.callbacks import Callback

class TestCallback(Callback):
    def __init__(
        self,
        images,
        output_dir=Path("./logs/activations_visualizations"),
    ):
        super(TestCallback, self).__init__()
        self.images = images
        self.output_dir = Path(output_dir) / datetime.now().strftime("%Y%m%d-%H%M%S.%f")
        Path.mkdir(Path(self.output_dir), parents=True, exist_ok=True)

        self.file_writer = tf.summary.create_file_writer(str(self.output_dir))

    def on_epoch_end(self, epoch, logs=None):
        with self.file_writer.as_default():
            # tf.summary.image should be a MagicMock object
            tf.summary.image(
                "Test Callback",
                self.images,
                step=epoch,
            )
```

**`test_tf_write_summary.py`**
```python
import numpy as np
import tensorflow as tf

import tf_write_summary


def test_callback(mocker):
    mock_image_summary = mocker.patch('tf_write_summary.tf.summary.image')
    fake_image_values = [0]
    callback = tf_write_summary.TestCallback(fake_image_values)

    model = tf.keras.Sequential(
        [
            tf.keras.layers.Conv2D(
                16,
                (3, 3),
                activation=None,
                name="conv_1",
                input_shape=(28, 28, 3),
            ),
            tf.keras.layers.ReLU(name="activation_1"),
            tf.keras.layers.Flatten(),
            tf.keras.layers.Dense(2, activation="softmax"),
        ]
    )

    model.compile(optimizer="adam", loss="categorical_crossentropy")

    y = np.array([1, 0] * 4).reshape((4, 2))
    model.fit(np.random.random((4, 28, 28, 3)), y, epochs=1, batch_size=2, callbacks=[callback])

    mock_image_summary.assert_called_once_with("Test Callback", [0], step=0)
```

Thanks for your time!

**Comment by Saduf2019** [comment]
@RaphaelMeudec 
could you please update on the above comment

**Comment by mihaimaruseac** [comment]
I think the 2.2.0-rc0 should also be ok, can you check, @RaphaelMeudec ?

**Comment by RaphaelMeudec** [comment]
@Saduf2019 @mihaimaruseac Just tested against 2.1.0 and it's working. Thanks for the update! I'm closing the issue.
