### ISSUE TITLE
[TF 2.0.0rc0] Installation on Travis CI

### ISSUE THREAD

**Issue by RaphaelMeudec** [tensorflow/tensorflow#31987]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Xenial 16.04 (xenial distribution on Travis CI)
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): `pip`
- TensorFlow version: `2.0.0rc0`
- Python version: 3.6, 3.7
- Installed using virtualenv? pip? conda?: pip
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: No
- GPU model and memory: No

Tox on Travis CI does not seem to be able to fetch Tensorflow 2.0.0rc0 using pip. Corresponding build is here : https://travis-ci.org/sicara/tf-explain/jobs/576955077
Everything is running fine locally. Any idea what is wrong with the build?

**Comment by RaphaelMeudec** [comment]
@ymodak I'm not sure there is an hyphen (it's working without it locally with `pip`). Tried it, and execution still fails : [Related Travis Build](https://travis-ci.org/sicara/tf-explain/jobs/578062183)

**Comment by av8ramit** [comment]
So there is no hyphen.
```
pip install tensorflow==2.0.0rc0
```
The above command should work. 

Perhaps you're not updating the pip version that you are actually using? Can you comment back with the pip version after the upgrade?

Are you using a virtualenv? I tried using Python3.6 in a virtual environment and with both the latest pip and 19.0.3 (the one from your logs) and it seems to install correctly. The only other notable difference between our setups is I'm on Python3.6.8 which shouldn't matter.

**Comment by av8ramit** [comment]
Also your [logs](https://travis-ci.org/sicara/tf-explain/jobs/578062183) expanded out show an error. Line 205 runs (pip install tensorflow==2.0.0rc0) but line 246 says ```ERROR: tb-nightly 1.15.0a20190806 has requirement setuptools>=41.0.0, but you'll have setuptools 40.8.0 which is incompatible.```

Also line 319 seems to add the hyphen.
```py36 installdeps: pip, pytest, pytest-cov, pytest-mock, tensorflow==2.0.0-rc0```

**Comment by RaphaelMeudec** [comment]
In the end, this seems to be related to `tox` more than tensorflow. I have moved the `tensorflow==2.0.0rc0` requirements from `deps` to `commands` in the `tox.ini` file and everything is running fine. Sorry for the bother and thanks for your time @av8ramit @ymodak @mihaimaruseac

**Comment by av8ramit** [comment]
Hey @RaphaelMeudec not a bother at all! It happens all the time! This is a good data point for anyone else who may run into this issue.
