### ISSUE TITLE
All weights become nan after training more than about 20000+10000 times

### ISSUE THREAD

**Issue by lykaust15** [tensorflow/tensorflow#3199]
Operating System: CentOS 7
Installed version of CUDA and cuDNN: cuda 7.5.18, cudnn4

When I run my own project, I found that all weights would become nan after training more than 20000+10000 times (That means I first trained the model for 20000 times, and then I continued training the model for 10000 times). The accuracy would suddenly change from 0.8 to 0.5. I thought that might be my own problem of setting weights and they become divergent after a certain point.

But we I rerun the Tensorflow tutorial: "Deep MNIST for Experts", I got the same problem.
Follow the instruction, I run the following script:

for i in range(20000):
  batch = mnist.train.next_batch(50)
  if i%100 == 0:
    train_accuracy = accuracy.eval(feed_dict={
        x:batch[0], y_: batch[1], keep_prob: 1.0})
    print("step %d, training accuracy %g"%(i, train_accuracy))
  train_step.run(feed_dict={x: batch[0], y_: batch[1], keep_prob: 0.5})

Everything is perfect until now, and the training accuracy is as high as 0.99.

However, when I rerun the above script, something strange happened. The training accuracy suddenly become around 0.1 and all weights become nan. Like following: 
<img width="372" alt="screen shot 2016-07-06 at 02 19 17" src="https://cloud.githubusercontent.com/assets/19503832/16603033/79ca3a3a-4321-11e6-92b7-19750de858c9.png">
<img width="775" alt="screen shot 2016-07-06 at 02 20 15" src="https://cloud.githubusercontent.com/assets/19503832/16603036/8074b87e-4321-11e6-9736-6ff2a98f5a4c.png">

To reproduce the problem, first train the model for 20000 times, and then continue training the module for 20000 times, using another for loop.

**Comment by lykaust15** [comment]
I tried again, training 40000 times continuously. I got the same problem at training step 32400.
<img width="295" alt="screen shot 2016-07-06 at 12 52 28" src="https://cloud.githubusercontent.com/assets/19503832/16614456/0917f60c-437a-11e6-8c49-c6b3e888a190.png">

**Comment by lykaust15** [comment]
I do not know that's a hardware problem or software problem. However, at the end, I indeed got some warning of running out of memory.
<img width="1009" alt="screen shot 2016-07-06 at 12 53 51" src="https://cloud.githubusercontent.com/assets/19503832/16614604/d82f2e38-437a-11e6-9f8e-afea48f5e5b9.png">

**Comment by yaroslavvb** [comment]
NaN's are a common situation with neural network training. If the dataset
is easy enough, then SGD will drive your log loss to negative infinity,
which will overflow at some point and cause NaNs.

An indication of a problem is when you run the same network on two
different versions of tensorflow, and it only diverges on one, but not the
other.

**Comment by lykaust15** [comment]
@yaroslavvb , thank you!

I found a solution to this problem just now. http://stackoverflow.com/questions/33712178/tensorflow-nan-bug?newreg=c7e31a867765444280ba3ca50b657a07.
