### ISSUE TITLE
import tensorflow as tf issue 

### ISSUE THREAD

**Issue by khaliltalib277** [tensorflow/tensorflow#31996]
I tried many times, but still the same issue. 

```
ImportError                               Traceback (most recent call last)
~\Miniconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow.py in <module>
     57 
---> 58   from tensorflow.python.pywrap_tensorflow_internal import *
     59   from tensorflow.python.pywrap_tensorflow_internal import __version__

~\Miniconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py in <module>
     27             return _mod
---> 28     _pywrap_tensorflow_internal = swig_import_helper()
     29     del swig_import_helper

~\Miniconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py in swig_import_helper()
     23             try:
---> 24                 _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
     25             finally:

~\Miniconda3\lib\imp.py in load_module(name, file, filename, details)
    241         else:
--> 242             return load_dynamic(name, filename, file)
    243     elif type_ == PKG_DIRECTORY:

~\Miniconda3\lib\imp.py in load_dynamic(name, path, file)
    341             name=name, loader=loader, origin=path)
--> 342         return _load(spec)
    343 

ImportError: DLL load failed: A dynamic link library (DLL) initialization routine failed.

During handling of the above exception, another exception occurred:

ImportError                               Traceback (most recent call last)
<ipython-input-2-64156d691fe5> in <module>
----> 1 import tensorflow as tf

~\Miniconda3\lib\site-packages\tensorflow\__init__.py in <module>
     26 
     27 # pylint: disable=g-bad-import-order
---> 28 from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
     29 from tensorflow.python.tools import module_util as _module_util
     30 

~\Miniconda3\lib\site-packages\tensorflow\python\__init__.py in <module>
     47 import numpy as np
     48 
---> 49 from tensorflow.python import pywrap_tensorflow
     50 
     51 # Protocol buffers

~\Miniconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow.py in <module>
     72 for some common reasons and solutions.  Include the entire stack trace
     73 above this error message when asking for help.""" % traceback.format_exc()
---> 74   raise ImportError(msg)
     75 
     76 # pylint: enable=wildcard-import,g-import-not-at-top,unused-import,line-too-long

ImportError: Traceback (most recent call last):
  File "C:\Users\Khalil\Miniconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\Khalil\Miniconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\Khalil\Miniconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Users\Khalil\Miniconda3\lib\imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\Khalil\Miniconda3\lib\imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: A dynamic link library (DLL) initialization routine failed.


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.
```
​

**Comment by khaliltalib277** [comment]
but before this issue, I was using TF version 1.13.1 on the same PC. Just I have installed my window and I'm facing this issue.

**Comment by michelucci** [comment]
Possibly you can check this... 

https://stackoverflow.com/questions/49932993/importerror-dll-load-failed-a-dynamic-link-library-dll-initialization-routin

Best of luck, Umberto

**Comment by khaliltalib277** [comment]
> Possibly you can check this...
> 
> https://stackoverflow.com/questions/49932993/importerror-dll-load-failed-a-dynamic-link-library-dll-initialization-routin
> 
> Best of luck, Umberto
let me check, thank you!

**Comment by michelucci** [comment]
You are welcome. I think you could try to install a previous version that does not have pre-built AVX instructions...

**Comment by khaliltalib277** [comment]
> You are welcome. I think you could try to install a previous version that does not have pre-built AVX instructions...

I think I can use version 1.5, buts its older version so what do say should I install?

**Comment by khaliltalib277** [comment]
and please let me know how do we check AVX instruction sets? will be appreciated!

**Comment by michelucci** [comment]
> > You are welcome. I think you could try to install a previous version that does not have pre-built AVX instructions...
> 
> I think I can use version 1.5, buts its older version so what do say should I install?

Well that depends on what features you want to use... Unless you want to work with specific features (for example from TF2.0) you can safely install an older version. For example I have several projects that runs on the version 1.13...

Best of luck, Umberto

**Comment by michelucci** [comment]
> and please let me know how do we check AVX instruction sets? will be appreciated!

Well that depends what you mean. If you mean how to check if your CPU support specific instructions you could check coreinfo (you are on windows10 right?). Check this

https://superuser.com/questions/1251865/is-there-a-way-to-tell-if-my-hardware-supports-specific-instructions

Best of luck, Umberto

**Comment by khaliltalib277** [comment]
> > and please let me know how do we check AVX instruction sets? will be appreciated!
> 
> Well that depends what you mean. If you mean how to check if your CPU support specific instructions you could check coreinfo (you are on windows10 right?). Check this
> 
> https://superuser.com/questions/1251865/is-there-a-way-to-tell-if-my-hardware-supports-specific-instructions
> 
> Best of luck, Umberto

Yes, I have window 10

**Comment by khaliltalib277** [comment]
> > and please let me know how do we check AVX instruction sets? will be appreciated!
> 
> Well that depends what you mean. If you mean how to check if your CPU support specific instructions you could check coreinfo (you are on windows10 right?). Check this
> 
> https://superuser.com/questions/1251865/is-there-a-way-to-tell-if-my-hardware-supports-specific-instructions
> 
> Best of luck, Umberto

thank you so much for your kind help.

**Comment by gadagashwini** [comment]
@khaliltalib277, Did you check your CPU supports AVX instruction sets or not.

**Comment by gadagashwini** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
