### ISSUE TITLE
Connectionist Temporal Classification example

### ISSUE THREAD

**Issue by trungnt13** [tensorflow/tensorflow#32]
I found these lines in _array_grad.py_
```python
# Edit Distance has no gradient (but can be used to eval seq2seq or CTC).
ops.NoGradient("EditDistance")
```

Is there any implementation of CTC cost function in tensorflow, or any example concern CTC ?

**Comment by ebrevdo** [comment]
Thank you for inquiring.  We are working on an implementation.  It will be released if/when we are happy with its performance, API, and documentation.

**Comment by mschonwe** [comment]
Here's another request for a CTC layer / objective.  I'm working on speech modeling, and CTC is pretty much essential to this.

**Comment by kdavis-mozilla** [comment]
Here here, I'm working on speech modeling too. A CTC implementation will help my effort greatly.

**Comment by ebrevdo** [comment]
Just an update on timelines: we're getting closer but it won't happen before January sometime at the earliest.

**Comment by ekelsen** [comment]
Baidu has just released a fast open source implementation of CTC for CPUs and GPUs. 
https://github.com/baidu-research/warp-ctc

It has a very simple C interface and it should hopefully be fairly easy to create Tensorflow bindings (we're happy to help).  The release includes Torch bindings.

**Comment by tjacobs** [comment]
China is out silicon valleying silicon valley!

**Comment by qingzew** [comment]
what's the timeline now @ebrevdo

**Comment by ebrevdo** [comment]
We're closer. Still cleaning up code for release.

**Comment by drdozer** [comment]
Hi Ebrevdo,

A CTC implementation would be really useful to me for some genome analysis tasks that are handled poorly by HMM approaches.

Matthew

**Comment by raindeer** [comment]
@ebrevdo any progress? :)

**Comment by bmilde** [comment]
Also highly interested in this and I hope that you can release your implementation soon! @ebrevdo

**Comment by ebrevdo** [comment]
Coming very soon (I hope).

**Comment by ebrevdo** [comment]
The CTC loss and two decoders (greedy & beam search for CTC) should be in the next push.

**Comment by ebrevdo** [comment]
(it'll be accessible via tf.contrib.ctc.ctc_loss etc.)

**Comment by kdavis-mozilla** [comment]
Awesome!

**Comment by aidangomez** [comment]
Very Awesome

**Comment by Duum** [comment]
very very awesome!

**Comment by vrv** [comment]
https://github.com/tensorflow/tensorflow/commit/8509f88ade3fc65f4cc530780d06100f0b1ea108

ctc_loss and friends is now part of contrib directory -- once it matures and we fix any issues, we'll add it to the core.
