### ISSUE TITLE
__ldg intrinsic unavailable on compute capability <3.2

### ISSUE THREAD

**Issue by levskaya** [tensorflow/tensorflow#320]
I'm not sure if supporting compute 3.0 capability will ever be a priority for the project, it's mainly useful for people who want to train small convnets on AWS g2.2x and g2.8x boxes as they're learning the framework.

A very recent commit 9c3043ff added the read-only data cache load function intrinsic __ldg to two operation defs: conv_ops_gpu_3.cu.cc and bias_op_gpu.cu.cc

All that's needed to maintain 3.0 support is to pass through __ldg(x) as a pointer -->  *x (I've confirmed this compiles and runs fine on the AWS GPU instances)  One could do this properly in theory with e.g. a generic wrapper:  (this is way too simplistic I'm sure...)
```
template<typename T>
__device__ __forceinline__ T ldg(const T* ptr) {
#if __CUDA_ARCH__ >= 320
    return __ldg(ptr);
#else
    return *ptr;
#endif
}
```

Again, it's mainly an issue if you want to keep the unsupported TF_UNOFFICIAL_SETTING=1 option working for people who happen to be working with slightly older GPUs.  (BTW thanks for all the amazing work!)

**Comment by vrv** [comment]
https://github.com/tensorflow/tensorflow/commit/854f49bd43588c062b046384f239f64a3d819702 Fixed this a while ago, I believe.
