### ISSUE TITLE
[C++] The SessionOptions doesn't control the usage of CPU ?

### ISSUE THREAD

**Issue by JiayiFu** [tensorflow/tensorflow#32009]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No, only use C++ API
- OS Platform and Distribution: Linux Ubuntu 16.04
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below): 1.14
- Bazel version (if compiling from source): 0.24.1
- GCC/Compiler version (if compiling from source): GCC 5.5
- CUDA/cuDNN version: only CPU
- GPU model and memory: only CPU

**Describe the current behavior**
I created a session option with inter=1 and intra=1. Then I used this option to create a session and load a model.
When I run the model, the program used almost all the CPUs in my server(the CPU usage is more than 5000%).
And No matter what value I set to "inter" and "intra", the CPU usage is more than 5000%.

**Describe the expected behavior**
When I set inter=1 and intra=1, I expect the usage of CPU is limited to <= 100%.

**Code to reproduce the issue**

    std::unique_ptr<tensorflow::Session> sess_;
    tensorflow::SessionOptions sess_options_;
    sess_options_.config.set_use_per_session_threads(false);
    sess_options_.config.set_intra_op_parallelism_threads(1);
    sess_options_.config.set_inter_op_parallelism_threads(1);
    sess_.reset(tensorflow::NewSession(sess_options_));
    tensorflow::GraphDef graph_def;
    auto default_env = tensorflow::Env::Default();
    tensorflow::ReadBinaryProto(default_env, model_path, &graph_def);
    sess_->Create(graph_def);
    run_model();

**Other info / logs**
When I use the python API of TensorFlow 1.14 do the same thing, it seems like the CPU usage can be controlled by the inter and intra parameter.

Why did this happen? What's the right way to control the computing resources used by tensorflow?

**Comment by JiayiFu** [comment]
I found some other problems in my environment, and I will reopen this when I have confirmed the problem.

**Comment by Binbin16** [comment]
> I found some other problems in my environment, and I will reopen this when I have confirmed the problem.

Hi JiayiFu, have you solved the issue? If it is solved, could you please let me know what changes did you make? Thanks.

**Comment by JiayiFu** [comment]
> > I found some other problems in my environment, and I will reopen this when I have confirmed the problem.
> 
> Hi JiayiFu, have you solved the issue? If it is solved, could you please let me know what changes did you make? Thanks.

@Binbin16 I saw your email and write a reply to you.
