### ISSUE TITLE
Tensorflow Lite compute library for hardware acceleration 

### ISSUE THREAD

**Issue by AaronLiu92** [tensorflow/tensorflow#32002]
Does Tensorflow lite has their own compute library for hardware(arm cpu, gpu, fpga, etc.) acceleration? If they have it, where is it located at? which directory? Thanks!

**Comment by ymodak** [comment]
See https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/delegates/gpu for using TFLite on GPU

**Comment by ymodak** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
