### ISSUE TITLE
Python/C++ API interpreter example for hybrid models

### ISSUE THREAD

**Issue by DocDriven** [tensorflow/tensorflow#32004]
I have a hybrid tflite model, e.g. was converted with the option

`converter.target_ops = [tf.lite.OpsSet.TFLITE_BUILTINS, tf.lite.OpsSet.SELECT_TF_OPS]`

So it contains both tflite ops and normal ops. I test a lot, so this is quicker than implementing the missing parts myself. When trying to load the model with an interpreter, either with the Python or the C++ API, I get errors:

Python
```
RuntimeError: Regular TensorFlow ops are not supported by this interpreter. Make sure you invoke the Flex delegate before inference.Node number 4 (Flex) failed to prepare.
```
C++
```
INFO: Initialized TensorFlow Lite runtime.
ERROR: Regular TensorFlow ops are not supported by this interpreter. Make sure you invoke the Flex delegate before inference.
ERROR: Node number 4 (FlexSoftplus) failed to prepare.
```

It doesn't seem there are docs that cover how to treat this error and load such hybrid models correctly. If I have missed any docs by any chance, please share the link!

**Comment by tpeet** [comment]
You probably need to build the C++ code with bazel, using  tensorflow/lite/delegates/flex:delegate as dependency:
https://www.tensorflow.org/lite/guide/ops_select#c

For Python, it is stated that it's under active development. +1 for that feature. It would simplify writing tests. If there's any documentation or idea how to TFLite with select ops interference working in python, I'd be very grateful :)

**Comment by edurenye** [comment]
Any idea how to make that work on python? It's been a long time under active development now

**Comment by JonathanDZiegler** [comment]
+1 for that feature

**Comment by yaysummeriscoming** [comment]
Haven't tried it myself, but there's now a build flag to enable the delegate:
tflite_pip_with_flex

Instructions can be found in: tensorflow/lite/tools/pip_package/README.md

Note that is only a few days old (see commit 865127af8a), so you'll need to build from master.

**Comment by JonathanDZiegler** [comment]
@yaysummeriscoming thanks for the hint! Looks promising. At least we know that some progress is being made 👍

**Comment by FlorentijnD** [comment]
See #40157 for updates on this thread

**Comment by terryheo** [comment]
With tf-nightly, now you can use TF ops without any issue.

**Comment by suraj-maniyar** [comment]
> You probably need to build the C++ code with bazel, using tensorflow/lite/delegates/flex:delegate as dependency:
> https://www.tensorflow.org/lite/guide/ops_select#c
> 
> For Python, it is stated that it's under active development. +1 for that feature. It would simplify writing tests. If there's any documentation or idea how to TFLite with select ops interference working in python, I'd be very grateful :)

Hello @tpeet 
Could you please provide the detailed instructions on how to build TFLite C++ API , using tensorflow/lite/delegates/flex:delegate as dependency?

From the link you shared I don't know where to specify the build dependencies.

Thanks.
