### ISSUE TITLE
.a library file is not working on android platform while using tf lite with c++ api.

### ISSUE THREAD

**Issue by devin730** [tensorflow/tensorflow#32007]
I am trying to make an android project using tensorflow lite, I want to use lite api in c++ level, however the examples in the repository are all using java api.

As the guidance tf lite can be applied in both java level and c++ level, but the .a library is not working. 

I built the libtensorflow-lite.a following the https://tensorflow.google.cn/lite/guide/build_arm64, but it seems this .a file is not working on android platform. Anyone can give me some advices about how to build a available .so library file for me to use c++ api in a android project?

Thanks a lot!

**Comment by oanush** [comment]
@devin730 ,
Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version.

In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here or Error being faced.Thanks!

**Comment by devin730** [comment]
> 
> 
> @devin730 ,
> Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version.
> 
> In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here or Error being faced.Thanks!

Thanks for your reply, I am making android app with Android Studio on windows 10 system. The target is an Arm64 developing board(however I think it does not matter because built failed not runing failed on board). The TesorFlow version I used is the latest code in github, and I built the libtensorflow-lite.a following the https://tensorflow.google.cn/lite/guide/build_arm64. The library file .a is obtained successfully, my code is exactly done as the tensorflow/tensorflow/lite/examples/minimal.cc and tensorflow/tensorflow/lite/examples/label_image.cc shows.

 However, when I build my project, I meet errors shown below:

`Build command failed.
Error while executing process F:\Sdk\Sdk\cmake\3.6.4111459\bin\cmake.exe with arguments {--build F:\AIgroup\app\.externalNativeBuild\cmake\debug\arm64-v8a --target AgeGenderEstimation}
[1/2] Building CXX object CMakeFiles/AgeGenderEstimation.dir/AgeGenderEstimation/age_gender_estimation.cpp.o
clang++.exe: warning: -Z-reserved-lib-stdc++: 'linker' input unused [-Wunused-command-line-argument]

[2/2] Linking CXX shared library F:\AIgroup\app\build\intermediates\cmake\debug\obj\arm64-v8a\libAgeGenderEstimation.so
FAILED: cmd.exe /C "cd . && F:\Sdk\Sdk\ndk-bundle\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe  --target=aarch64-none-linux-android21 --gcc-toolchain=F:/Sdk/Sdk/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64 --sysroot=F:/Sdk/Sdk/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/sysroot -fPIC -g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -fno-addrsig -Wa,--noexecstack -Wformat -Werror=format-security -stdlib=libc++ -std=c++11 -fexceptions -frtti -lstdc++ -O0 -fno-limit-debug-info  -Wl,--exclude-libs,libgcc.a -Wl,--exclude-libs,libatomic.a -static-libstdc++ -Wl,--build-id -Wl,--warn-shared-textrel -Wl,--fatal-warnings -Wl,--no-undefined -Qunused-arguments -Wl,-z,noexecstack -Wl,-z,relro -Wl,-z,now -shared -Wl,-soname,libAgeGenderEstimation.so -o F:\AIgroup\app\build\intermediates\cmake\debug\obj\arm64-v8a\libAgeGenderEstimation.so CMakeFiles/AgeGenderEstimation.dir/AgeGenderEstimation/age_gender_estimation.cpp.o  F:/AIgroup/libfacedetection_tengine/app/src/main/cpp/../../../../app/src/main/jniLibs/arm64-v8a/libtensorflow-lite.a F:/AIgroup/libfacedetection_tengine/app/src/main/cpp/../../../../app/src/main/jniLibs/arm64-v8a/libopencv_java4.so F:/AIgroup/libfacedetection_tengine/app/build/intermediates/cmake/debug/obj/arm64-v8a/liblogger.so -llog -latomic -lm && cd ."
F:/AIgroup/libfacedetection_tengine/app/src/main/cpp/../../../../app/src/main/jniLibs/arm64-v8a/libtensorflow-lite.a(activations.o): In function `void tflite::ops::builtin::activations::(anonymous namespace)::PopulateLookupTable<unsigned char>(tflite::ops::builtin::activations::OpData*, TfLiteTensor const*, TfLiteTensor*, std::function<float (float)> const&) [clone .isra.60]':

activations.cc:(.text.unlikely+0x88): undefined reference to `std::__throw_bad_function_call()'

F:/AIgroup/libfacedetection_tengine/app/src/main/cpp/../../../../app/src/main/jniLibs/arm64-v8a/libtensorflow-lite.a(activations.o): In function `void tflite::ops::builtin::activations::(anonymous namespace)::PopulateLookupTable<signed char>(tflite::ops::builtin::activations::OpData*, TfLiteTensor const*, TfLiteTensor*, std::function<float (float)> const&) [clone .isra.61]':

activations.cc:(.text.unlikely+0x19c): undefined reference to `std::__throw_bad_function_call()'

F:/AIgroup/libfacedetection_tengine/app/src/main/cpp/../../../../app/src/main/jniLibs/arm64-v8a/libtensorflow-lite.a(activations.o): In function `_GLOBAL__sub_I_activations.cc':

activations.cc:(.text.startup+0x18): undefined reference to `std::ios_base::Init::Init()'

activations.cc:(.text.startup+0x1c): undefined reference to `std::ios_base::Init::~Init()'

activations.cc:(.text.startup+0x2c): undefined reference to `std::ios_base::Init::~Init()'`

**Comment by devin730** [comment]
Hi, this problem is solved,

my college used android NDK to compile a .so library file with provided source files in tf-lite reposity.
