### ISSUE TITLE
The title is the shared_embeddings module，but the document introduces shared_embedding_columns module

### ISSUE THREAD

**Issue by yecphaha** [tensorflow/tensorflow#32001]
Thank you for submitting a TensorFlow documentation issue. Per our GitHub
policy, we only address code/doc bugs, performance issues, feature requests, and
build/installation issues on GitHub.

The TensorFlow docs are open source! To get involved, read the documentation
contributor guide: https://www.tensorflow.org/community/contribute/docs

## URL(s) with the issue:

Please provide a link to the documentation entry, for example:
https://tensorflow.google.cn/versions/r2.0/api_docs/python/tf/feature_column/shared_embeddings

## Description of issue (what needs changing):

The description in the document is a way to use the shared_embedding_columns module, but the title is the shared_embeddings module, and the shared_embedding_columns module has been removed in tensorflow2.0.

**Comment by ymodak** [comment]
This is fixed with TF 2.4.1 api docs. Thanks!
https://www.tensorflow.org/api_docs/python/tf/feature_column/shared_embeddings
