### ISSUE TITLE
hi  i want to freeze east text a  pretrained model    the ckpt.meta data file  exist in the model folder but i get this error can any one help me please !!!!                                              

### ISSUE THREAD

**Issue by amal268** [tensorflow/tensorflow#32019]
re_fusion/Conv_7/Sigmoid,model_0/feature_fusion/concat_3
Traceback (most recent call last):
  File "freez2.py", line 66, in <module>
    freeze_graph(args.model_dir, args.output_node_names)
  File "freez2.py", line 41, in freeze_graph
    saver = tf.train.import_meta_graph(input_checkpoint + '.meta', clear_devices
=clear_devices)
  File "C:\Users\DeLl\Anaconda3\lib\site-packages\tensorflow\python\training\sav
er.py", line 1435, in import_meta_graph
    meta_graph_or_file, clear_devices, import_scope, **kwargs)[0]
  File "C:\Users\DeLl\Anaconda3\lib\site-packages\tensorflow\python\training\sav
er.py", line 1447, in _import_meta_graph_with_return_elements
    meta_graph_def = meta_graph.read_meta_graph_file(meta_graph_or_file)
  File "C:\Users\DeLl\Anaconda3\lib\site-packages\tensorflow\python\framework\me
ta_graph.py", line 633, in read_meta_graph_file
    raise IOError("File %s does not exist." % filename)
OSError: File /tmp/east_icdar2015_resnet_v1_50_rbox/model.ckpt-49491.meta does n
ot exist.

(base) C:\Users\DeLl\Documents\east>

**Comment by oanush** [comment]
@amal268 ,
Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version.
In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thanks!

**Comment by amal268** [comment]
hi @oanush  thank you 
i'am using 
-windows 7 
-python 3.6 under anaconda 
-tensorflow 1;13.1
my problem is solved but i'am facing new one 
my goal is to freeze this pretrained model " https://github.com/argman/EAST "
this model is trained on GPU and i'am using it with CPU 
detection work normaly but i can't freeze it 
can u help please ? 

"
"
InvalidArgumentError (see above for traceback): Restoring from checkpoint failed
. This is most likely due to a mismatch between the current graph and the graph
from the checkpoint. Please ensure that you have not altered the graph expected
based on the checkpoint. Original error:

Cannot assign a device for operation model_0/split: node model_0/split (defined
at freez.py:16) was explicitly assigned to /device:GPU:0 but available devices a
re [ /job:localhost/replica:0/task:0/device:CPU:0 ]. Make sure the device specif
ication refers to a valid device. The requested device appears to be a GPU, but
CUDA is not enabled.
         [[node model_0/split (defined at freez.py:16) ]]

**Comment by ymodak** [comment]
The below error says you have have explicit device allocations made to GPU which is not available.
You may try removing these device allocations. You can use ```tf.train.import_meta_graph``` with ```clear_devices``` option.
```python
Cannot assign a device for operation model_0/split: node model_0/split (defined
at freez.py:16) was explicitly assigned to /device:GPU:0 but available devices a
re [ /job:localhost/replica:0/task:0/device:CPU:0 ]. Make sure the device specif
ication refers to a valid device. The requested device appears to be a GPU, but
CUDA is not enabled.
```

**Comment by amal268** [comment]
thank u very much @ymodak it works for me now

**Comment by anknam1012** [comment]
> cảm ơn bạn rất nhiều @ymodak nó làm việc cho tôi bây giờ

Can you guide me to freeze with the EAST model. Thank you
