### ISSUE TITLE
tf.keras.layers.Concatenate layer has unexpected behavior since 1.13

### ISSUE THREAD

**Issue by noahtren** [tensorflow/tensorflow#32023]
`tf.keras.layers.Concatenate` used to operate in a very straightforward way with the Keras functional API for building DenseNet-esque feedforward networks.

The code below works in TF 1.13 but fails in 1.14, 2.0.0a0 and beyond.
 
I also tested replacing the `Concatenate` layer with its functional alternative, `concatenate`, and produced the same error.
```python
from tensorflow.keras.layers import Dense, Input, Concatenate
from tensorflow.keras.models import Model

inputs = Input(shape=(10,))

all_layers = []

x1 = Dense(512)(inputs)
all_layers.append(x1)

# all layers: [x1]
x2 = Dense(256, activation='relu')(x1)
all_layers.append(x2)

# all layers: [x1, x2]
conc = Concatenate()(all_layers)
x3 = Dense(128, activation='relu')(conc)
all_layers.append(x3)

# all layers: [x1, x2, x3]
conc = Concatenate()(all_layers)
prediction = Dense(1)(conc)
model = Model(inputs=inputs, outputs=prediction)
```
The error output is 
```
ValueError: Graph disconnected: cannot obtain value for tensor Tensor("dense_2/Identity:0", shape=(None, 128), dtype=float32) at layer "concatenate". The following previous layers were accessed without issue: ['input_1', 'dense', 'dense_1']
```
Visualization of model
![](https://i.imgur.com/17UNrSk.png)

**Comment by WindQAQ** [comment]
Interestingly, if doing the same thing in the following way, then it works.
```python
from tensorflow.keras.layers import Dense, Input, Concatenate
from tensorflow.keras.models import Model

inputs = Input(shape=(10,))

all_layers = []

x1 = Dense(512)(inputs)
all_layers.append(x1)

# all layers: [x1]
x2 = Dense(256, activation='relu')(x1)
all_layers.append(x2)

# all layers: [x1, x2]
conc = Concatenate()(list(all_layers))
x3 = Dense(128, activation='relu')(conc)
all_layers.append(x3)

# all layers: [x1, x2, x3]
conc = Concatenate()(list(all_layers))
prediction = Dense(1)(conc)
model = Model(inputs=inputs, outputs=prediction)
```

**Comment by DevarakondaV** [comment]
Is someone working on this?

**Comment by jvishnuvardhan** [comment]
@noahtren I think this was resolved in `tf-nightly`. I was not able to reproduce the issue with `tf-nightly`. Please check the [gist here](https://colab.sandbox.google.com/gist/jvishnuvardhan/747b7ec0bc45a54dfcb227dd47b7b6dd/untitled114.ipynb). Thanks.

Please close the issue if this was resolved for you. Thanks!

**Comment by noahtren** [comment]
Yep, it looks like this was fixed! Thanks @jvishnuvardhan
