### ISSUE TITLE
I need more accuracy

### ISSUE THREAD

**Issue by yiliu9090** [tensorflow/tensorflow#32025]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using):
 1.13 and 2.0
- Are you willing to contribute it (Yes/No): 
Yes

**Describe the feature and the current behavior/state.**
Tensorflow has been used to compute images but I want to use Tensorflow to compute Biological Models. However, the biological model requires big division and this causes numerical instability. I want to have tensorflow that supports more numerically stablility.  
**Will this change the current api? How?**
I don't know
**Who will benefit with this feature?**
A biologist who wants to use tensorflow as a means to compute gene expression models with high degree of accuracy.
**Any Other info.**
This is based on my recent work in 
https://www.biorxiv.org/content/10.1101/655639v1

**Comment by oanush** [comment]
This is not Build/Installation or Bug/Performance issue. Please post this kind of support questions at Stackoverflow. There is a big community to support and learn from your questions. GitHub is mainly for addressing bugs in installation and performance. Thanks!
