### ISSUE TITLE
Tensorflow r2.0 will not build successfully on skylake machines

### ISSUE THREAD

**Issue by dbonner** [tensorflow/tensorflow#32026]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04
- TensorFlow installed from (source or binary): not installed (attempting to build from source)
- TensorFlow version: attempting to build from branch r2.0
- Python version: 3.7.4
- Installed using virtualenv? pip? conda?: Anaconda conda virtual environment 
- Bazel version (if compiling from source): 0.26.0
- GCC/Compiler version (if compiling from source): 7.4.0
- CUDA/cuDNN version: CUDA 10, cuDNN 7.6.2
- GPU model and memory: NVidia RTX 2080 Ti (MSI Sea Hawk X, 11 GB)

**Describe the problem**
bazel build is unsuccessful yielding error in tensorflow/lite/experimental/ruy/kernel_avx512.cc
Please see [Issue 31187](https://github.com/tensorflow/tensorflow/issues/31187) for background leading to the same bug being resolved on the master branch.  I don't know how they fixed it on master.  The fix needs to be ported from master to r2.0 branch.

Please also note that you can bypass using AVX-512 and get a successful build by changing:
~/tensorflow/tensorflow/lite/experimental/ruy/platform.h
Comment out:
// TODO(b/138433137) Select AVX-512 at runtime rather than via compile options.
// #if defined(__AVX512F__) && defined(__AVX512DQ__) && defined(__AVX512CD__) && \
    defined(__AVX512BW__) && defined(__AVX512VL__)
// #define RUY_DONOTUSEDIRECTLY_AVX512 1
// #else
#define RUY_DONOTUSEDIRECTLY_AVX512 0
// #endif

**Provide the exact sequence of commands / steps that you executed before running into the problem**

git clone https://github.com/tensorflow/tensorflow.git
cd tensorflow
git checkout r2.0
./configure
Accept defaults initially
When asked for CUDA support, type "y"
When asked for TensorRT support, type "y"
When asked for compute capabilities, type 7.0,7.5
Accept defaults thereafter
bazel build --explain=verbose_explanations.txt --verbose_explanations --verbose_failures --subcommands=pretty_print --config=opt --config=cuda --config=v2 --cxxopt="-D_GLIBCXX_USE_CXX11_ABI=0" //tensorflow/tools/pip_package:build_pip_package

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.
This error does not occur on machines that do not have Skylake support for AVX-512 (I know because I can build it fine on my laptop and other users report this bug is particular to Skylake).

I have attached a dump of the terminal output of the bazel build command (cleaned-capture.txt) and verbose_explanations.txt:

[cleaned-capture.txt](https://github.com/tensorflow/tensorflow/files/3548002/cleaned-capture.txt)
[verbose_explanations.txt](https://github.com/tensorflow/tensorflow/files/3548006/verbose_explanations.txt)

Full error message:
ERROR: /home/daniel/tensorflow/tensorflow/lite/experimental/ruy/BUILD:271:1: C++ compilation of rule '//tensorflow/lite/experimental/ruy:kernel' failed (Exit 1): crosstool_wrapper_driver_is_not_gcc failed: error executing command 
  (cd /home/daniel/.cache/bazel/_bazel_daniel/79db702fc9f94af7d11e11c5d64854d0/execroot/org_tensorflow && \
  exec env - \
    LD_LIBRARY_PATH=:/usr/local/cuda/extras/CUPTI/lib64:/usr/local/cuda/extras/CUPTI/lib64 \
    PATH=/home/daniel/anaconda3/envs/tfgpu/bin:/home/daniel/anaconda3/condabin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/local/cuda/bin \
    PWD=/proc/self/cwd \
  external/local_config_cuda/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc -MD -MF bazel-out/host/bin/tensorflow/lite/experimental/ruy/_objs/kernel/kernel_avx512.pic.d '-frandom-seed=bazel-out/host/bin/tensorflow/lite/experimental/ruy/_objs/kernel/kernel_avx512.pic.o' -iquote . -iquote bazel-out/host/bin -iquote external/gemmlowp -iquote bazel-out/host/bin/external/gemmlowp '-std=c++11' -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -fPIC -U_FORTIFY_SOURCE '-D_FORTIFY_SOURCE=1' -fstack-protector -Wall -fno-omit-frame-pointer -no-canonical-prefixes -fno-canonical-system-headers -DNDEBUG -g0 -O2 -ffunction-sections -fdata-sections -g0 '-march=native' -g0 -c tensorflow/lite/experimental/ruy/kernel_avx512.cc -o bazel-out/host/bin/tensorflow/lite/experimental/ruy/_objs/kernel/kernel_avx512.pic.o)
Execution platform: @bazel_tools//platforms:host_platform
In file included from tensorflow/lite/experimental/ruy/kernel_avx512.cc:18:0:
./tensorflow/lite/experimental/ruy/kernel.h:613:9: warning: multi-line comment [-Wcomment]
 #endif  // (RUY_PLATFORM(NEON_64) || RUY_PLATFORM(NEON_32) || \
         ^
In file included from external/gemmlowp/fixedpoint/fixedpoint.h:895:0,
                 from ./tensorflow/lite/experimental/ruy/kernel.h:22,
                 from tensorflow/lite/experimental/ruy/kernel_avx512.cc:18:
external/gemmlowp/fixedpoint/./fixedpoint_sse.h:43:39: warning: ignoring attributes on template argument ‘__m128i {aka __vector(2) long long int}’ [-Wignored-attributes]
 struct FixedPointRawTypeTraits<__m128i> {
                                       ^
In file included from tensorflow/lite/experimental/ruy/kernel_avx512.cc:18:0:
./tensorflow/lite/experimental/ruy/kernel.h: In function ‘void ruy::MakeKernelParamsFloat(const ruy::PackedMatrix<float>&, const ruy::PackedMatrix<float>&, const ruy::BasicSpec<float, float>&, int, int, int, int, ruy::Matrix<float>*, ruy::KernelParamsFloat<LhsCols, RhsCols>*)’:
./tensorflow/lite/experimental/ruy/kernel.h:456:53: warning: typedef ‘using Params = struct ruy::KernelParamsFloat<LhsCols, RhsCols>’ locally defined but not used [-Wunused-local-typedefs]
   using Params = KernelParamsFloat<LhsCols, RhsCols>;
                                                     ^
tensorflow/lite/experimental/ruy/kernel_avx512.cc: In function ‘void ruy::Kernel8bitAvx512(const ruy::KernelParams8bit<16, 16>&)’:
tensorflow/lite/experimental/ruy/kernel_avx512.cc:111:34: error: ‘_mm512_loadu_epi8’ was not declared in this scope
         const __m512i lhs_data = _mm512_loadu_epi8(lhs_ptr);
                                  ^~~~~~~~~~~~~~~~~
tensorflow/lite/experimental/ruy/kernel_avx512.cc:111:34: note: suggested alternative: ‘_mm512_add_epi8’
         const __m512i lhs_data = _mm512_loadu_epi8(lhs_ptr);
                                  ^~~~~~~~~~~~~~~~~
                                  _mm512_add_epi8
tensorflow/lite/experimental/ruy/kernel_avx512.cc:161:32: error: ‘_mm512_loadu_epi32’ was not declared in this scope
                                _mm512_loadu_epi32(&params.lhs_sums[row]));
                                ^~~~~~~~~~~~~~~~~~
tensorflow/lite/experimental/ruy/kernel_avx512.cc:161:32: note: suggested alternative: ‘_mm512_load_epi32’
                                _mm512_loadu_epi32(&params.lhs_sums[row]));
                                ^~~~~~~~~~~~~~~~~~
                                _mm512_load_epi32
tensorflow/lite/experimental/ruy/kernel_avx512.cc:170:32: error: ‘_mm512_loadu_epi32’ was not declared in this scope
                                _mm512_loadu_epi32(&params.rhs_sums[col]));
                                ^~~~~~~~~~~~~~~~~~
tensorflow/lite/experimental/ruy/kernel_avx512.cc:170:32: note: suggested alternative: ‘_mm512_load_epi32’
                                _mm512_loadu_epi32(&params.rhs_sums[col]));
                                ^~~~~~~~~~~~~~~~~~
                                _mm512_load_epi32
tensorflow/lite/experimental/ruy/kernel_avx512.cc:277:13: error: ‘_mm_storeu_epi8’ was not declared in this scope
             _mm_storeu_epi8(tmp_ptr, _mm512_cvtepi32_epi8(accum_data_v[j]));
             ^~~~~~~~~~~~~~~
tensorflow/lite/experimental/ruy/kernel_avx512.cc:277:13: note: suggested alternative: ‘_mm_store_epi64’
             _mm_storeu_epi8(tmp_ptr, _mm512_cvtepi32_epi8(accum_data_v[j]));
             ^~~~~~~~~~~~~~~
             _mm_store_epi64
tensorflow/lite/experimental/ruy/kernel_avx512.cc:293:13: error: ‘_mm_storeu_epi8’ was not declared in this scope
             _mm_storeu_epi8(tmp_ptr, _mm512_cvtepi32_epi8(accum_data_v[j]));
             ^~~~~~~~~~~~~~~
tensorflow/lite/experimental/ruy/kernel_avx512.cc:293:13: note: suggested alternative: ‘_mm_store_epi64’
             _mm_storeu_epi8(tmp_ptr, _mm512_cvtepi32_epi8(accum_data_v[j]));
             ^~~~~~~~~~~~~~~
             _mm_store_epi64
tensorflow/lite/experimental/ruy/kernel_avx512.cc:309:13: error: ‘_mm256_storeu_epi16’ was not declared in this scope
             _mm256_storeu_epi16(tmp_ptr,
             ^~~~~~~~~~~~~~~~~~~
tensorflow/lite/experimental/ruy/kernel_avx512.cc:309:13: note: suggested alternative: ‘_mm256_store_epi64’
             _mm256_storeu_epi16(tmp_ptr,
             ^~~~~~~~~~~~~~~~~~~
             _mm256_store_epi64
tensorflow/lite/experimental/ruy/kernel_avx512.cc:326:13: error: ‘_mm512_storeu_epi32’ was not declared in this scope
             _mm512_storeu_epi32(tmp_ptr, accum_data_v[j]);
             ^~~~~~~~~~~~~~~~~~~
tensorflow/lite/experimental/ruy/kernel_avx512.cc:326:13: note: suggested alternative: ‘_mm512_store_epi32’
             _mm512_storeu_epi32(tmp_ptr, accum_data_v[j]);
             ^~~~~~~~~~~~~~~~~~~
             _mm512_store_epi32
Target //tensorflow/tools/pip_package:build_pip_package failed to build
INFO: Elapsed time: 35.925s, Critical Path: 10.04s
INFO: 282 processes: 282 local.
FAILED: Build did NOT complete successfully

**Comment by jalexstark** [comment]
This should now be fixed.
