### ISSUE TITLE
Creating a boolean constant prints a deprecation warning

### ISSUE THREAD

**Issue by guillaumekln** [tensorflow/tensorflow#32049]
**System information**
- Have I written custom code: Yes
- OS Platform and Distribution: Ubuntu 16.04
- TensorFlow installed from: binary
- TensorFlow version: 2.0.0rc0
- Python version: 3.6

**Describe the current behavior**

Creating a boolean constant prints a deprecation warning:

> W0828 15:45:36.142576 139852094695168 deprecation.py:323] From /lib/python3.6/site-packages/tensorflow_core/python/framework/constant_op.py:253: _EagerTensorBase.cpu (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.identity instead.

**Describe the expected behavior**

No deprecation warning.

**Code to reproduce the issue**

```python
import tensorflow as tf
tf.zeros([10], dtype=tf.bool)
```

**Comment by oanush** [comment]
Please find the Gist of Colab for [TF 2.0rc0](https://colab.research.google.com/drive/1CsJ8P2y9t7FzidogHvDiO4Ti66jVk7Xg).Thanks!

**Comment by cossio** [comment]
I am still getting this warning on the current version of Tensorflow (I just installed it yesterday). When will this be fixed for mainstream users?

**Comment by jakkes** [comment]
Although far from satisfactory, I managed to avoid the warning through
`tf.cast(tf.zeros((10, )), tf.bool)`
