### ISSUE TITLE
Knights Landing feature request

### ISSUE THREAD

**Issue by BenjaminHess** [tensorflow/tensorflow#3204]
It would be nice to see a tensorflow binary compatible with Knights Landing for AWS.

**Comment by Mistobaan** [comment]
What would be the benefit ?

**Comment by tfboyd** [comment]
We now have MKL support and you will need to build from source.  I will also be updating the performance guide.  Here are the basic command, which will work starting at TF 1.2 RC2.  

```bash
1.       Configure tensorflow
./configure
MKL -> yes
everything else -> default

2.       Build
bazel build --config=mkl --copt="-DEIGEN_USE_VML" -c opt //tensorflow/tools/pip_package:build_pip_package
```

This will provide a signifiant boost and Intel is actively working on improving edge cases as they are found.  

Is KNL available on AWS?  I would like to use it can you provide a link.
