### ISSUE TITLE
static int64 GetDirectConvCost - Integer overflow

### ISSUE THREAD

**Issue by iurii-kvasniuk** [tensorflow/tensorflow#32045]
/tensorflow/core/kernels/deep_conv2d.cc: ln 74,
static int64 GetDirectConvCost(int filter_rows, int filter_cols, int in_depth,
int out_depth, int out_rows, int out_cols) {
return filter_rows * filter_cols * in_depth * out_depth * out_rows * out_cols;
}

Can lead to integer overflow and weird results
I think, it should be smth like that
return (int64)filter_rows * (int64)filter_cols * (int64)in_depth * (int64)out_depth * (int64)out_rows * (int64)out_cols;

**Comment by iur-kvasniuk** [comment]
Ok, I will create a PR tomorrow morning. Thanks for reply!

Ср, 28 авг. 2019 г. в 18:24, Yong Tang <notifications@github.com>:

**Comment by ravikyram** [comment]
Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version. Also, did you compile from source or install a binary?

Make sure you also include the exact command if possible to produce the output included in your test case. If you are unclear what to include see the issue template displayed in [the Github new issue template](https://github.com/tensorflow/tensorflow/issues/new/choose).

We ask for this in the issue submission template, because it is really difficult to help without that information. Thanks!

**Comment by iur-kvasniuk** [comment]
- OS Platform and Distribution: Linux Ubuntu 16.04 LTS
- TensorFlow built from source (tf_nightly-1.14.0-cp35-cp35m-linux_x86_64)
- For Conv2D parameters
in_depth = 4, input_cols = 1920, filter_cols = 3, input_rows = 1080, filter_rows = 3, out_depth = 32
output of GetDirectConvCost function: -1906180096, but should be 2388787200
- For Conv2D parameters
in_depth = 32, input_cols = 1920, filter_cols = 3, input_rows = 1080, filter_rows = 3, out_depth = 32
output of CanUseDeepConv2D function - false (deep_direct_ratio: 7.14965), but should be true (deep_direct_ratio: 0.722222)

**Comment by mihaimaruseac** [comment]
The function clearly overflows, but the fix suggested is not enough.

**Comment by iurii-kvasniuk** [comment]
created new PR with additional checks

**Comment by mihaimaruseac** [comment]
The caller should check, this is defined behavior. It's very probable that the caller already has all checks in place, if not, that's where they should go

**Comment by mihaimaruseac** [comment]
There are more issues in that file. I'll handle those changes this week

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.
