### ISSUE TITLE
RMSprop can‘t convergence.

### ISSUE THREAD

**Issue by jiawei6636** [tensorflow/tensorflow#32050]
When I use a Adam optimizer, it can convergence. But when I use the RMSprop, it can't convergence. Maybe there is a bug in the keras.optimizers.RMSprop.

**Comment by jiawei6636** [comment]
Addition: I am optimizing a bid-lstm model.

**Comment by jiawei6636** [comment]
Addition: I am using the tensorflow-gpu==2.0.0rc0

**Comment by jiawei6636** [comment]
> Can you please provide a code snippet that repros the issue ?

https://github.com/jiawei6636/Bioinfor_DanQ  this is my project, when i change the optimizer in the **main_DanQ.py** to RMSProp, my result is not good as the original paper shows(The paper use RMSProp optimizer), but when i use the Adam optimizer,  the result is alright. So i think there is a bug in the tf.keras.optimizers.RMSProp.  And the issue #30263 is still trouble me in the tensorflow2.0rc0.

**Comment by jiawei6636** [comment]
> Can you please provide a code snippet that repros the issue ?

I write a custom training loop in the **trainer.py**.

**Comment by goldiegadde** [comment]
HI Jiawei Li, 
can you please provide a link to minimum repro code that can reproduce the issue you described above ?

**Comment by jiawei6636** [comment]
> HI Jiawei Li,
> can you please provide a link to minimum repro code that can reproduce the issue you described above ?

OK, i will do it as soon as possible.

**Comment by gowthamkpr** [comment]
@jiawei6636 As mentioned Can you please provide a minimum reproducible code as mentioned.

**Comment by gowthamkpr** [comment]
Closing this issue as this has been inactive for more than 2 weeks. Please add additional comments and we can open the issue again. Thanks!
