### ISSUE TITLE
I have trained a .pb model which is in tf1.2 and I want to use it in the environment of tf2.0, but I fail to use it successfully. Anyone knows how to solve the problem

### ISSUE THREAD

**Issue by Govan111** [tensorflow/tensorflow#32068]
from __future__ import division
from __future__ import print_function

try:
    import tensorflow.compat.v1 as tf
    tf.disable_v2_behavior()
except (ImportError, AttributeError):
    import tensorflow as tf

import tensorflow as tf
import numpy as np
import os

        with tf.Graph().as_default():

            output_graph_def = tf.GraphDef()

            with open('./myModel.pb', "rb") as f:
                output_graph_def.ParseFromString(f.read())
                tf.import_graph_def(output_graph_def, name="")

            gpu_options = tf.GPUOptions(
                per_process_gpu_memory_fraction=self.gpu_memory_fraction,
                visible_device_list=self.visible_device_list,
                allow_growth=self.allow_growth)
            tfconfig = tf.ConfigProto(gpu_options=gpu_options, allow_soft_placement=False)
            tfconfig.gpu_options.allow_growth = True

            with tf.Session(config=tfconfig) as sess:
                sess.run(tf.global_variables_initializer())
                input_photo = sess.graph.get_tensor_by_name('placeholder/photo:0')
                output_photo = sess.graph.get_tensor_by_name('decoder/Sigmoid:0')

################################## erros are as follows:
Traceback (most recent call last):
File "/Users/govan/Project/test.py", line 31, in __call__
    output_graph_def = tf.GraphDef()
AttributeError: module 'tensorflow' has no attribute 'GraphDef'

**Comment by gadagashwini** [comment]
@Govan111,
Did you follow the instructions mentioned in the [Tensorflow website](https://www.tensorflow.org/beta/guide/upgrade) to upgrade from 1.x to 2.x. Thanks

**Comment by gadagashwini** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
