### ISSUE TITLE
Installers for C-API do not include copyright/license information for Tensorflow

### ISSUE THREAD

**Issue by RochaStratovan** [tensorflow/tensorflow#32064]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
Windows, Linux and OSX

- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
N/A

- TensorFlow installed from (source or binary):
Binary, using the instructions from C-API page at:
(https://www.tensorflow.org/install/lang_c)

- TensorFlow version: 
1.14.0

- Python version:
N/A

- Installed using virtualenv? pip? conda?:
Installed by following instructions at C-API page (https://www.tensorflow.org/install/lang_c)
, basically extracting from tarball or zip file.

- Bazel version (if compiling from source):
N/A

- GCC/Compiler version (if compiling from source):
N/A

- CUDA/cuDNN version:
N/A 

- GPU model and memory:
N/A

**Describe the problem**

The problem I see is that there is no COPYRIGHT or LICENSE information for the TENSORFLOW library itself. There is a LICENSE file under \include\tensorflow\c\LICENSE, but that gives all of the LICENSE information for the 3rd party libraries that tensorflow uses, but there is nothing for tensorflow itself.

**Provide the exact sequence of commands / steps that you executed before running into the problem**
Windows:
Unzip the zip file

LINUX/Darwin
Detar the compressed tarballs

**Any other info / logs**
None

**Comment by gadagashwini** [comment]
@RochaStratovan, Are you looking for [this](https://github.com/tensorflow/tensorflow/blob/master/LICENSE).

**Comment by RochaStratovan** [comment]
Hello @gadagashwini ,

Yes I believe that would be correct. However, I'm not a TF dev. The installers typically have the licensing information included with the installation. This is actually the first one I've encountered that does not.

Thank you.

**Comment by gadagashwini** [comment]
@RochaStratovan, You can get the Tensorflow license info by using the command `pip show tensorflow` . Please take a look at screenshot below. Thanks!
![Screenshot from 2019-09-04 15-42-55](https://user-images.githubusercontent.com/48476109/64246722-f6efd680-cf2a-11e9-9511-f701afdacaa9.png)

**Comment by RochaStratovan** [comment]
Thank you for the workaround @gadagashwini . This will work for folks that have PIP, python, etc. installed. We are using the C-API, Binary distribution specifically because we don't want/need, all of that underlying stuff that we don't actually need. We just use the Binaries.

We are trying to ensure that we follow appropriate licensing requests/guidelines. However, the distribution for the C-API binaries does not have any licensing information for Tensorflow itself included in it. So technically those distros could be viewed as unlicensed.

I'm pointing out an enhancement that should be made to those binary distributions so that the Tensorflow products and licenses are protected.

Thank you for your consideration.

**Comment by alextp** [comment]
@gunan can you triage this?

**Comment by gunan** [comment]
Thank you very much for reporting this.
You are correct, the license file was missing in some of the distributables.
The fixes are merged into master. https://github.com/tensorflow/tensorflow/pull/32852 will fix this in 2.0 branch. https://github.com/tensorflow/tensorflow/pull/32853 will fix this in 1.15 branch. We will push new binaries with the fixes within 1 week.

**Comment by ymodak** [comment]
Closing this issue since associated PR has been merged. Thanks!
