### ISSUE TITLE
OP_REQUIRES failed at save_restore_v2_ops.cc:109 : Not found: Failed to create a NewWriteableFile

### ISSUE THREAD

**Issue by swy0915** [tensorflow/tensorflow#32070]
my os is win10:
when i use tf.estimator.BestExporter, i find a bug.

in saver.py 
_SHARDED_SUFFIX = "_temp_%s/part" % uuid.uuid4().hex
path ='aaa\bbb\_temp_xxx/part....' 

i think to change code:
    _SHARDED_SUFFIX_temp = "_temp_%s" % uuid.uuid4().hex
    _SHARDED_SUFFIX = os.path.join(_SHARDED_SUFFIX_temp, 'part')

**Comment by Ashtonoid** [comment]
Try to reduce your path length. The best you can try with this `testA = os.path.normpath('C:/)`
