### ISSUE TITLE
TF2.0rc0: experimental_distribute_datasets_from_function() does not respect end of iteration

### ISSUE THREAD

**Issue by tridemax** [tensorflow/tensorflow#32076]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution: Linux Ubuntu 16.04
- TensorFlow installed from: binary
- TensorFlow version: v2.0.0-beta1-5101-gc75bb66 2.0.0-rc0
- Python version: 3.6.8
- CUDA/cuDNN version: 10.0 CUDA, 7.6.3.30-1+cuda10.0 cuDNN
- GPU model and memory: 3x TitanX Pascal 12Gb

**Describe the current behavior**
Note: code worked fine with Tensorflow 2.0 Beta1. Changes introduced in RC0 caused this.

I've created a function, that reads large file and return batches of needed size, considering the number of replicas. At the end of the file it return None (end of iteration). This function is then submitted to `tf.data.Dataset.from_generator()`:
```
def dataset_fn(input_context):
  bs = input_context.get_per_replica_batch_size(self._config.train.batch_size)
  ds = tf.data.Dataset.from_generator(lambda: parallel_map_and_batch(data_file, bs))
  ds = ds.shard(input_context.num_input_pipelines, input_context.input_pipeline_id)
  return ds
```

`tf.distribute.MirroredStrategy.experimental_distribute_datasets_from_function(dataset_fn)` is used to get the dataset and create iterator from it.

`tf.distribute.MirroredStrategy.experimental_run_v2(..., next(iterator))` is used to call a model on each replica.

I've printed a batch size for each call of the model and I see something like:
```
Replica0: batch size 128
Replica1: batch size 128
Replica2: batch size 128
...
Replica0: batch size 107  (this was a last batch)
Replica1: batch size 0  (generator returned None)
Replica2: batch size 0
```

Which causes `Check failed: work_element_count > 0 (0 vs. 0)` inside the model call because of the empty batch.

**Describe the expected behavior**

Replicas shouldn't peek empty batches from dried out iterator. Beta1 used to throw an exception in this case.

P.S. Or `experimental_distribute_datasets_from_function` expects generator to always return number of batches dividable by number of replicas?

**Comment by tridemax** [comment]
Fix for this problem is pretty simple (a bit of work, of course).

Let your generator know about the global batch size and the number of replicas, then force it to output `num_replicas` number of batches on yield, like:
```
global_batch = read_batch(global_batch_size)
for replica in range(num_replicas):
  replica_batch = global_batch[replica_start:replica_end]
  yield replica_batch
```

**Comment by tridemax** [comment]
And even with this fix I'm still sometimes getting a error:
```
tensorflow.python.framework.errors_impl.CancelledError: 3 root error(s) found.
  (0) Cancelled:  Operation was cancelled
         [[{{node cond_5/else/_71/IteratorGetNext}}]]
  (1) Out of range:  End of sequence
         [[{{node cond_3/else/_37/IteratorGetNext}}]]
         [[Identity_4/_144]]
  (2) Out of range:  End of sequence
         [[{{node cond_3/else/_37/IteratorGetNext}}]]
0 successful operations.
1 derived errors ignored. [Op:__inference_mgpu_run_eval_step_graph_6335388]
```

I'm not really sure `next(iterator)` is supposed to work under `@tf.function` as I've read somewhere.

**Comment by oanush** [comment]
@tridemax ,
In order to expedite the trouble-shooting process, please provide complete code snippet to reproduce the issue reported here. Thanks!

**Comment by tridemax** [comment]
Cannot reproduce it on a small sample - StopIteration is properly thrown. I'll try to figure out what causes this in my large model.
