### ISSUE TITLE
iOS GestureClassification (Type 'Interpreter' has no member 'Options')

### ISSUE THREAD

**Issue by t104360088** [tensorflow/tensorflow#32072]
When I build this project, I got the error
Type 'Interpreter' has no member 'Options'
Maybe changed class name recently, but the change is not complete
The file name is ModelDataHandler.swift and the line is 99

This is error message
![螢幕快照 2019-08-29 下午1 53 17](https://user-images.githubusercontent.com/32124047/63915118-bf36e980-ca67-11e9-8c32-6562128c73f5.png)

And I try this to fix
![螢幕快照 2019-08-29 下午1 57 12](https://user-images.githubusercontent.com/32124047/63915166-dd044e80-ca67-11e9-9381-7360a7685c5a.png)

**Comment by gadagashwini** [comment]
@t104360088,
Please provide the information asked in the [Template](https://github.com/tensorflow/tensorflow/issues/new?template=40-tflite-op-request.md). Thanks!

**Comment by sheehanm** [comment]
@gadagashwini this commit https://github.com/tensorflow/examples/commit/751f4648e3917178b0e67454422477fe5d81d611#diff-7e5803a55f12fc06d7347d59eb7d0f99 
Should have a corresponding change to Interpreter which is here https://github.com/tensorflow/tensorflow/blob/c3a9eb7c28107574872c77237670cc174ef45d9f/tensorflow/lite/experimental/swift/Sources/Interpreter.swift

**Comment by t104360088** [comment]
**System information**
- OS Platform and Distribution : macOS 10.14
- TensorFlow installed from (source or binary): google colab
- TensorFlow version (or github SHA if from source): 1.13.1

**Comment by gadagashwini** [comment]
@t104360088, Please provide the google colab gist to expedite the trouble-shooting process. Thanks!

**Comment by t104360088** [comment]
@gadagashwini , I think this issue is not related to ml model.

https://gist.github.com/t104360088/d9a0904b1fdde0b326692c994d1028f6

**Comment by yyoon** [comment]
I believe this was fixed by 53afd4e200942a4b05b8f4d2982cb5e7c8c0a44d. Feel free to re-open or file a new bug if this is still an issue.
