### ISSUE TITLE
build error tensorflow lite for ARM64

### ISSUE THREAD

**Issue by Huadalao** [tensorflow/tensorflow#32073]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):18.04
- TensorFlow version (or github SHA if from source):master
- GCC/Compiler version (if compiling from source): 7.4.0

**problem:**
i want to build the label_image,and i change the makefile,add label_image like minimal:
```
MINIMAL_SRCS := \
	tensorflow/lite/examples/minimal/minimal.cc
LABEL_IMAGE_SRCS := \
	tensorflow/lite/examples/label_image/label_image.cc \
	tensorflow/lite/examples/label_image/bitmap_helpers.cc
```

```
$(MINIMAL_SRCS) \
$(LABEL_IMAGE_SRCS)
```

```
ALL_SRCS := \
	$(MINIMAL_SRCS) \
        $(LABEL_IMAGE_SRCS) \
```

```
MINIMAL_BINARY := $(BINDIR)minimal
LABEL_IMAGE_BINARY := $(BINDIR)label_image
```

```
MINIMAL_OBJS := $(addprefix $(OBJDIR), \
$(patsubst %.cc,%.o,$(patsubst %.c,%.o,$(MINIMAL_SRCS))))
LABEL_IMAGE_OBJS := $(addprefix $(OBJDIR), \
$(patsubst %.cc,%.o,$(patsubst %.c,%.o,$(LABEL_IMAGE_SRCS))))
```

`all: $(LIB_PATH)  $(MINIMAL_BINARY) $(BENCHMARK_BINARY) $(LABEL_IMAGE_BINARY)`

```
$(MINIMAL_BINARY): $(MINIMAL_OBJS) $(LIB_PATH)
	@mkdir -p $(dir $@)
	$(CXX) $(CXXFLAGS) $(INCLUDES) \
	-o $(MINIMAL_BINARY) $(MINIMAL_OBJS) \
	$(LIBFLAGS) $(LIB_PATH) $(LDFLAGS) $(LIBS)

minimal: $(MINIMAL_BINARY)

$(LABEL_IMAGE_BINARY): $(LABEL_IMAGE_OBJS) $(LIB_PATH)
	@mkdir -p $(dir $@)
	$(CXX) $(CXXFLAGS) $(INCLUDES) \
	-o $(LABEL_IMAGE_BINARY) $(LABEL_IMAGE_OBJS) \
	$(LIBFLAGS) $(LIB_PATH) $(LDFLAGS) $(LIBS)

label_image: $(LABEL_IMAGE_BINARY)
```
i got a build error：label_image.cc
undefined reference："tflite::evaluation::CreateGPUDelegate(tflite::FlateBufferModel)"
undefined reference："tflite::evaluation::CreateNNAPIDelegate()"

**Comment by freedomtan** [comment]
They are in `tensorflow/lite/tools/evaluation/utils.cc`. Either add it to `$LABEL_IMAGE_SRCS` or replace them with `Interpreter::TfLiteDelegatePtr(nullptr, [](TfLiteDelegate*) {});`

**Comment by Huadalao** [comment]
> They are in `tensorflow/lite/tools/evaluation/utils.cc`. Either add it to `$LABEL_IMAGE_SRCS` or replace them with `Interpreter::TfLiteDelegatePtr(nullptr, [](TfLiteDelegate*) {});`

thanks for you reply ! this is very helpful to me and successfully solved the problem.

**Comment by ravikyram** [comment]
I am closing the issue since the query is been resolved. Please, feel free to reopen if the issue still persists. Thanks!

**Comment by jonpsy** [comment]
Hi @ravikyram, I'm facing the same issue but I want to use the bazel outputted static library. So I used the bazel-bin/tensorflow/lite/tools/evaluation/libutils and linked against it, but I still get undefined reference error. Any help?

**Comment by jonpsy** [comment]
My error is

Undefined reference to "tflite::evaluation::CreateGPUDelegate(TfLiteGpuDelegateOptionsV2*) "
