### ISSUE TITLE
Ragged tensor with start and end indices

### ISSUE THREAD

**Issue by FlorianUekermann** [tensorflow/tensorflow#32086]
**System information**
- TensorFlow version (you are using):
nightly

**Describe the feature and the current behavior/state.**
Ragged tensors are currently defined by specifying the boundaries between subtensors in the ragged dimension. If the elements at the end/beginning of consecutive subtensors in the ragged dimension are shared, defining both the start and end of each such subtensor could reduce the total size of the ragged tensor dramatically.

To make the implementation more straightforward, both starts and ends could be required to increase monotonically .

**Will this change the current api? How?**
No. This would only require adding a construction function to the API.

**Who will benefit with this feature?**
This feature could be used to compress overlapping tensors with overlapping sequences by a large margin. This is useful for training data containing words, tokens, transactions etc.
Furthermore, this would allow slicing the underlying data tensor while using gaps, potentially reducing the number of necessary copies.

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.
