### ISSUE TITLE
Documentation for ./configure environment variables

### ISSUE THREAD

**Issue by sjdrc** [tensorflow/tensorflow#32085]
I'm looking for documentation with all of the `TF_*` environment variables that can be set to make `./configure` unattended. All I can find are various github issues or random articles using them, but is there a definitive official list somewhere?

**Comment by oanush** [comment]
@sjdrc ,
Can you please check if this [link](https://tensorflow.google.cn/install/source_windows?hl=en#configure_the_build) helps.Thanks!

**Comment by sjdrc** [comment]
No. This describes using the script interactively. I want to set environment variables such as `TF_NEED_CUDA` and `TF_NEED_AWS` to make the process unattended.

**Comment by sjdrc** [comment]
Just want to bump you on this. There are various pieces of information for this all over the place. All we need is a single official source listing and explaining the variables.

**Comment by sjdrc** [comment]
Hello? I have been waiting for quite some time for a response on this. Surely this is documented somewhere.

**Comment by jrefi** [comment]
Still no answer to this? I am trying to build TF inside a Docker image so an interactive script isn't going to work. 

I gotta say, for such a large and well-supported project, TF's documentation and developer tooling is pretty bad.

**Comment by mihaimaruseac** [comment]
I was able to build TF inside Docker via `yes "" | python configure.py`

**Comment by sjdrc** [comment]
It just seems like if they just had a list of all the variables you could configure it would make this easier for a lot of people. Why is this documentation missing, and can a tensorflower please comment on this?

**Comment by mihaimaruseac** [comment]
The `configure.py` script is extremely convoluted and grew organically.

If someone were to provide a PR documenting the features I think it can be accepted.

**Comment by mohantym** [comment]
Hi @sjdrc !
We are checking whether you are still looking for any assistance or not. All the details about dependencies like Cuda,Android/IOS details are mentioned in sample session . You can use flags like nogcp,noccl ,rocm ,v1 to create a custom build. 

Created PR #2127 to update the session with new output. 
Can you comment or update the above PR to give some inputs from your end.

Thank you!

**Comment by mihaimaruseac** [comment]
Note that since 2 years ago we no longer use `./configure` / `configure.py` for the standard builds. These options are now in `.bazelrc` by default and you should only use `configure.py` if they don't work for you (in which case you might also need to edit `.bazelrc` to remove contradictions).

**Comment by MarkDaoust** [comment]
> since 2 years ago we no longer use ./configure / configure.py for the standard builds

Oh! So I guess we need an update to the build from source instructions. To say... "only `configure` the build if you need to"?

**Comment by mohantym** [comment]
@MarkDaoust @mihaimaruseac !
Can i put below statement under this section "Configure the build" . 

> For a standard build, Running ./configure is not necessary. But for a custom build, one should do it at root of Tensorflow source tree. It will prompt you for the location of TensorFlow dependencies and asks for additional build configuration options (compiler flags, for example). Please refer "Sample session" section for details.  

instead of 

> Configure your system build by running the ./configure at the root of your TensorFlow source tree. This script prompts you for the location of TensorFlow dependencies and asks for additional build configuration options (compiler flags, for example). Please refer "Sample session" section for details.

**Comment by MarkDaoust** [comment]
I'm merging your PR, I'll update that in the merge commit.

**Comment by mohantym** [comment]
@sjdrc !
Moving this to closed status , As the concerned PR for this has updated the session details with relevant documentation.
Thank you!

**Comment by mohantym** [comment]
@sjdrc !
Moving this to closed status , As the concerned PR for this has updated the session details with relevant documentation.
Thank you!
