### ISSUE TITLE
TF2.0 RC tf.keras.model.Evaluate has display bug

### ISSUE THREAD

**Issue by gaborchris** [tensorflow/tensorflow#32089]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No. This is the code from https://www.tensorflow.org/beta/tutorials/quickstart/beginner
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Google Colab and Ubuntu 18.04
- TensorFlow version (use command below): pip install tensorflow==2.0.0-rc0
- Python version: 3.6

**Describe the current behavior**

When I run model.evaluate with verbose=True, I get too many "=======" signs. I noticed this on Ubuntu 18.04 when I upgraded from TF2.0-beta to TF2.0.0-rc0. This is a mild annoyance when I am running models with soft-warp enabled on the command line.

**Describe the expected behavior**

There should only be this many equal signs:
[==============================]
Not
[===========================............................................

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.
``` from __future__ import absolute_import, division, print_function, unicode_literals

# Install TensorFlow
try:
  # %tensorflow_version only exists in Colab.
  %tensorflow_version 2.x
except Exception:
  pass

import tensorflow as tf

mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10, activation='softmax')
])

model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])
model.fit(x_train, y_train, epochs=1)

model.evaluate(x_test, y_test)
```

**Other info / logs**
This issue may be due to the denominator of the number of evaluated samples completed. It should be 10000/10000, not 10000/1.
Instead of 10000/1 [====

**Comment by gowthamkpr** [comment]
Was able to reproduce the issue. Please find the github gist [here](https://colab.research.google.com/gist/gowthamkpr/a34035feed7b076e62a8fd51467394a9/untitled116.ipynb).

**Comment by jvishnuvardhan** [comment]
@gaborchris This was resolved in `tf-nightly`. Please take a look at the [gist](https://colab.sandbox.google.com/gist/jvishnuvardhan/9cf040a428c59f8efbd1e17f70d51a34/untitled116.ipynb). Thanks!

I am closing this issue as this was resolved. Please feel free to reopen if the issue persists for you. Thanks!
