### ISSUE TITLE
Unable to create TF-TRT model using docker image tensorflow/tensorflow:nightly-gpu-py3

### ISSUE THREAD

**Issue by jtressle** [tensorflow/tensorflow#32098]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):  Yes, my model is custom.
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version (use command below): 1.14
- Python version: 3.6.8
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 10.1 Cuda Drivers
- GPU model and memory: T4, 12GB

**Describe the current behavior**

When I run the following code from the latest python3 gpu build, nothing happens.  When I run it from the nightly build, I'm able to get a model with 1 TRT Engine node.

```
	converter = trt.TrtGraphConverter(
		input_saved_model_dir = str(saved_model_dir),
		max_batch_size = batch_size,
		precision_mode = precision )
	converter.convert()
	converter.save(output_saved_model_dir = str(output_saved_model_dir))
```

Is there an issue with the latest gpu build?  

Thanks,

**Describe the expected behavior**

Should be able to create a TRT model using the latest docker build.

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by jvishnuvardhan** [comment]
@jtressle Sorry for the delay. Could you try using TF1.15.0rc1 that was released recently and let us know if the issue persists. Thanks!

**Comment by jvishnuvardhan** [comment]
Closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
