### ISSUE TITLE
Problems with Tensorboard on Ubuntu 16.04

### ISSUE THREAD

**Issue by zhaopku** [tensorflow/tensorflow#3209]
I'm running code from https://github.com/MorvanZhou/tutorials/blob/master/tensorflowTUT/tf15_tensorboard/full_code.py on my own computer, which is a sample of how to use Tensorboard, however, I see nothing from the Tensor board from my computer: every tab of the Tensorflow is empty, saying no XX data is found.

I tried the '--inspect option':

> zhao@zhao-ubuntu:~/Desktop/samples$ tensorboard --logdir = 'logs' --inspect ====================================================================== Processing event files... (this can take a few minutes) ======================================================================
> 
> No event files found within logdir =
> 

and the '--debug' option:

> 
zhao@zhao-ubuntu:~/Desktop/samples$ tensorboard --logdir = 'logs' --debug INFO:tensorflow:TensorBoard is in debug mode. INFO:tensorflow:Starting TensorBoard in directory /home/zhao/Desktop/samples
INFO:tensorflow:TensorBoard path_to_run is: {'/home/zhao/Desktop/samples/=': None} 
INFO:tensorflow:Multiplexer done loading. Load took 0.0 secs INFO:tensorflow:TensorBoard is tag:b'22' 
Starting TensorBoard b'22' on port 6006 (You can navigate to http://0.0.0.0:6006)

BTW, I'm using python3.5.1 on my ubuntu machine.

**Comment by danmane** [comment]
Just checking, do you have a directory called 'logs' within your ~/Desktop/samples directory?
If so, can you try passing a logdir as a full path (eg `logdir=$(pwd)/logs`)

**Comment by danmane** [comment]
Oh, you can't have a space before the equals. It is looking for "/home/zhao/Desktop/samples/=' because you have `logdir = X`, which it parses as `logdir == '='`. 

Please use `logdir=X` or `logdir X`, the space is equivalent to an equals sign.

**Comment by zhaopku** [comment]
Oh, so stupid I am.
Thanks!
