### ISSUE TITLE
[lite] how to build example label_image for ios (library+binary)?

### ISSUE THREAD

**Issue by laohur** [tensorflow/tensorflow#32091]
[https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/examples/label_image/label_image.md
](url)
this project provide an example for ubuntu+macos+android(32+64), only lack ios(library+binary).

**Comment by freedomtan** [comment]
@laohur label_image is a command line program. You probably want to start from the iOS [classification example](https://github.com/tensorflow/examples/tree/master/lite/examples/image_classification/ios) first.

**Comment by laohur** [comment]
> 
> 
> @laohur label_image is a command line program. You probably want to start from the iOS [classification example](https://github.com/tensorflow/examples/tree/master/lite/examples/image_classification/ios) first.

that means that you cannot build ios(lib) project from connand line ?

**Comment by freedomtan** [comment]
@laohur Nope, it's possible to run command line program on iOS, but it's complicated. And surely you can share C++ source code.

**Comment by laohur** [comment]
Here is my code:
build
> cc_binary(
    name = "libProphet.so",
    srcs = ["Prophet.cc",],
    copts = tflite_copts(),
    linkopts = tflite_linkopts() + select({
        "//tensorflow:android": [
            "-pie",  # Android 5.0 and later supports only PIE
            "-lm",  # some builtin ops, e.g., tanh, need -lm
        ],
        "//conditions:default": [],
    }),
    deps = [
        "//tensorflow/lite:framework",
        "//tensorflow/lite/c:c_api_internal",
        "//tensorflow/lite/kernels:builtin_ops",
        "//tensorflow/lite:builtin_op_data",
        "//tensorflow/lite/schema:schema_fbs",
    ],
    linkshared = True,
)
.cc:
> extern "C"{
int init(const char* modelBuffer,int bufferSize){
 std::unique_ptr<tflite::FlatBufferModel> model=tflite::FlatBufferModel::VerifyAndBuildFromBuffer(_modelBuffer,modelSize);
return 0;
}
int predict(float* example, int size ){
    return -1;
}
}

I just want to get a lib of android & ios.
" https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/examples/label_image/BUILD " is easy to build android library.  How about test this example?
And what is the  elegant way to build ios library ?

**Comment by laohur** [comment]
it quiet different between android and xcode. thanks!
