### ISSUE TITLE
Feature request: linspace can accept tensors for start and stop

### ISSUE THREAD

**Issue by hristo-vrigazov** [tensorflow/tensorflow#32093]
**System information**
- TensorFlow version (you are using): 1.14.0
- Are you willing to contribute it (Yes/No): Yes

**Describe the feature and the current behavior/state.**

Currently, [`tf.linspace`](https://www.tensorflow.org/api_docs/python/tf/linspace) accepts only single numbers (0-D tensor) for start and stop. Numpy recently added support for ndarrays for the `start` and `stop` parameters (since 1.16, see [np.linspace](https://docs.scipy.org/doc/numpy/reference/generated/numpy.linspace.html) ). It would be very useful (especially when writing vectorized implementations) to have the possibility to call this function for multi dimensional tensors with behavior matching the one in Numpy.

**Will this change the current api? How?** 

It will be a backward-compatible change. Only the behaviour of the function will be changed (for certain sets of inputs) and the dimension checking at the start of the function.

**Who will benefit with this feature?**

Mostly when vectorizing different algorithms. One possible application is when doing a body pose estimation postprocessing pairwise connections per limb, we have all possible combinations of points in a multi dimensional tensor and we want to be able to call `tf.linspace` for the Monte Carlo sampling directly on the tensors to avoid slow iterative solutions.

**Any Other info.**
I have already implemented a function locally, that behaves in the same way. I have not checked if there would be problems in integration though.

**Comment by hristo-vrigazov** [comment]
So how should we proceed, do you want me to contribute this or you prefer a tensorflower to work on it?

**Comment by jvishnuvardhan** [comment]
@hristo-vrigazov As you have implemented the function locally, You could create a [Pull-Request](https://github.com/tensorflow/tensorflow/pulls) to add the feature. Thanks!

**Comment by hristo-vrigazov** [comment]
Awesome, I will see where is the exact point to integrate the code, will add tests and update here when I am done.

**Comment by jvishnuvardhan** [comment]
@hristo-vrigazov When you create a PR, post a link here so that we can close this issue when your PR approves/merges. Thanks!

**Comment by Leslie-Fang** [comment]
Hi @hristo-vrigazov, I am also interested in  this feature. Could we work together?

**Comment by hristo-vrigazov** [comment]
@Leslie-Fang Sure, you can send me a message on [Gitter](https://gitter.im) and we can have a discussion there. I will show you what I have done so far and what is left (I think), while I am waiting for the build to finish. I am in Sofia, Bulgaria time, so I think we have quite a lot of overlap (assuming you are in Shanghai).

**Comment by hristo-vrigazov** [comment]
Hello @jvishnuvardhan , I think I am ready with the implementation, I have opened a pull request. Not sure who should I add for reviewers though, since I do have some doubts (it's explained in the pull request).

**Comment by Leslie-Fang** [comment]
@hristo-vrigazov It seems you have a python implementation.
But as my understanding, it should also have the cpp implementation.
Please refer to this snippet of code
https://github.com/tensorflow/tensorflow/blob/ff8147d950d8dbc9866edb9e039280fe603698dc/tensorflow/core/kernels/sequence_ops.cc#L35-L78

**Comment by hristo-vrigazov** [comment]
@Leslie-Fang 
Yes, this is the original implementation, but it assumes scalar `start` and `stop`. The idea is to support tensors, so I am internally doing it using `range` and elementwise multiplication - in a similar way that `numpy` is doing it: https://github.com/numpy/numpy/blob/v1.17.0/numpy/core/function_base.py#L37-L179
The only difference is that `numpy` is operating on the axis 0 and then does transpose, while I am operating directly on the given axis to avoid one additional transpose.

**Comment by Leslie-Fang** [comment]
@hristo-vrigazov Thanks, So numpy also implement this feature with python instead of cpp.

**Comment by hristo-vrigazov** [comment]
@Leslie-Fang Yep, I think so :) The unit tests from before still pass - so it looks like I have not broken anything for the legacy case. Let's see when the reviewers can comment on this

**Comment by yongtang** [comment]
@hristo-vrigazov @Leslie-Fang It is possible to pass a 1-d tensor as well in C++. Just need to remove the requirement of `IsLegacyScalar` line. The shape constraint in `tensorflow/core/ops//math_ops.cc` will also need to be removed as well.

**Comment by hristo-vrigazov** [comment]
@yongtang Thanks for the information. I guess the question is do we want to, since this operation can already be expressed by other operations? We would have to reuse some of the Python operations in C++ to implement this, which I thought would not be as easy as in Python, where they are already generated and implemented (I may be wrong here). I feel like this version is very easy to maintain, since it closely follows the Numpy one and it should not be much slower in terms of performance compared to the kernel one, but if TF developers want to keep it as a C++ kernel, then maybe I can decline this PR and this can be implemented it in the kernel by someone else.

**Comment by yongtang** [comment]
@hristo-vrigazov I don't have a preference over python or c++ for this case. I think python would be fine as long as there is not a big hit on performance.

**Comment by vigician** [comment]
It's a nice to have feature, what's the status of this feature?

**Comment by hristo-vrigazov** [comment]
The pull request is currently being reviewed.

**Comment by hristo-vrigazov** [comment]
The pull request was recently into master, so this one is ready! Awesome!

**Comment by ravikyram** [comment]
@hristo-vrigazov 

Please close this thread if it solves your question. Thanks!
