### ISSUE TITLE
TF2.0-rc0 ValueError on tensor comparison with None using ==

### ISSUE THREAD

**Issue by Ryandry1st** [tensorflow/tensorflow#32100]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version (use command below): 2.0-rc0
- Python version:
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Describe the current behavior**
Previously when running the code from the CVAE tutorial https://www.tensorflow.org/beta/tutorials/generative/cvae, I used in the sample function
`if eps == None:`
Which worked fine, however with rc0 it now throws an error from comparing a tensor to None and only works if the following is used
`if eps is None`

**Describe the expected behavior**
Comparing if something == None and is None should have the same behavior

**Code to reproduce the issue**
See https://www.tensorflow.org/beta/tutorials/generative/cvae and change the sample function as described.

**Comment by gadagashwini** [comment]
@Ryandry1st, I tried both the case in colab with Tensorflow 2.0.0.rc0. It works, Please take a look at colab gist [here](https://colab.sandbox.google.com/gist/gadagashwini/029f514c526c246f41f0c177cb2cb906/untitled116.ipynb). Let us know this is the expected behavior. Thanks!

**Comment by Ryandry1st** [comment]
Did you make sure to update to TF 2.0-rc0 and replace the line specified? I am still able to get the error on a colab on my end.

**Comment by Ryandry1st** [comment]
In your colab you did not use the tensorflow comparison because you were not using any tensors. Converting your code to make eps a tensor, especially a tensor with some values, will throw the error

**Comment by goldiegadde** [comment]
here is a minimum repro [colab](https://colab.sandbox.google.com/drive/187REdqdMP1N94_sToSnvwABdDdY2LlhH#scrollTo=NyBS6UeSe0C3) for the issue reported.

**Comment by Ryandry1st** [comment]
> here is a minimum repro [colab](https://colab.sandbox.google.com/drive/187REdqdMP1N94_sToSnvwABdDdY2LlhH#scrollTo=NyBS6UeSe0C3) for the issue reported.

You will need to change the sharing settings as each person will have to request access to see that btw.

**Comment by goldiegadde** [comment]
here is the [colab gist](https://colab.research.google.com/gist/goldiegadde/30db42737c2140e2b4bd43403f4a04a7/git_issue_32100.ipynb)

**Comment by jaingaurav** [comment]
Please see the following section in PEP8: https://www.python.org/dev/peps/pep-0008/#programming-recommendations

In Python comparing with `None` using `==` is considered an anti-pattern. `==` implies the values are equal vs `is` checks if the two objects are the same object. Often you can get away with using `==` with `None` since `None is None` as they are the same object. However, this is not recommended and or supported for TensorFlow.

Note, the equality operator has been changed in 2.0 to do element-wise comparison. So `==` triggers a `tf.math.equal` function which is what causes the code to try (and fail) to convert `None` to a Tensor.

**Comment by Ryandry1st** [comment]
I agree with the premise, as it is the recommended/agreed-upon method. The main issue is that this seems to raise some compatibility issues, considering the operation has been changed in 2.0 and is an overloaded operator so it does not have documentation to reference. A suggestion might be to include a simple check with a warning/error handling. That would make more sense than quietly changing the functionality.

**Comment by jaingaurav** [comment]
@Ryandry1st: Thanks for the feedback. The compatibility issue is known, but from what has been seen, it has actually uncovered more bugs in the application code where developers expected a different behavior than what they wrote.

I agree the change has had limited documentation. We'll see what we can do to improve that for the release.
