### ISSUE TITLE
FATAL error when using TF_CUDNN_USE_AUTOTUNE=0

### ISSUE THREAD

**Issue by ppwwyyxx** [tensorflow/tensorflow#32105]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): ubuntu 16.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: n/a
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below): v1.12.1-10080-g6e0893c79c 1.14.0
- Python version: 3.7
- Bazel version (if compiling from source): 0.24.1
- GCC/Compiler version (if compiling from source): 7.4
- CUDA/cuDNN version: 10.0 / 7.6.2
- GPU model and memory: V100 16G

**Describe the current behavior**
I have a model which runs fine. However, after I use
```
export TF_CUDNN_USE_AUTOTUNE=0
```
in order to save some autotuning time, it starts to crash with this error in the first iteration:
```
019-08-30 00:05:05.705707: F tensorflow/stream_executor/cuda/cuda_dnn.cc:262] Unsupported Cudnn convolution backward algorithm for filter: 6
zsh: abort (core dumped)  python3 xx.py
```

**Code to reproduce the issue**
Can try to provide one but I think the information is probably already enough to pin down the problem.

**Other info / logs**
The algorithm 6, mentioned in the error message, corresponds to `CUDNN_CONVOLUTION_BWD_FILTER_ALGO_FFT_TILING`, which is explictly disabled in tensorflow: 
https://github.com/tensorflow/tensorflow/blob/a4bfabe12869a00138173afe739733065b39f4a0/tensorflow/stream_executor/cuda/cuda_dnn.cc#L258-L265

When I set AUTOTUNE=0, cudnn will choose the best algorithm with its own heuristics, and I suspect that TensorFlow crashes because cudnn chooses this algorithm that TF has disabled.

cc @chsigg

**Comment by ravikyram** [comment]
In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thanks!

**Comment by ppwwyyxx** [comment]
I understand you have a templated response to ask for repro, which is good for filtering out a large portion of issues which are more likely due to user error than a tensorflow bug. But I think I already pointed out the root cause of the issue, and a repro isn't quite necessary to investigate the issue.

In fact, the issue probably requires a very specific version of cudnn to reproduce anyway, so it's unlikely that whatever I provided would be useful.

**Comment by AntonDovhulia** [comment]
I have the same issue. Did you find any way how to bypass this?

**Comment by sanjoy** [comment]
@ppwwyyxx, would you be willing to send a fix for this?  Probably the easiest thing to do is allow the user to pick something other than `CUDNN_CONVOLUTION_BWD_FILTER_ALGO_FFT_TILING` (if there is a safe choice) when `TF_CUDNN_USE_AUTOTUNE` is `0`.

**Comment by Saduf2019** [comment]
@ppwwyyxx 
Please update as per above comment, if this is not an issue now, please move this to closed status.

**Comment by ppwwyyxx** [comment]
The issue should still exist since `CUDNN_CONVOLUTION_BWD_FILTER_ALGO_FFT_TILING` is still disabled. Unfortunately I'm not able to send a fix.

**Comment by lamhoangtung** [comment]
I have the same issue. Did you find any way how to bypass this?

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.
