### ISSUE TITLE
How to break tf.while_loop inside body function?

### ISSUE THREAD

**Issue by zepen** [tensorflow/tensorflow#32108]
The issues like this, i write py code for segment chinese sentence, it's easy. But when i use tf do this thing, it' s unlucky ! Specific issues are as follows: 

- py code
 
``` python
x = list("我是算法工程师")
y = [3, 3, 0, 2, 0, 1, 2]
def func(x, y):
    res = []
    for i in range(len(x)):
        if y[i] == 3:
            res.append(x[i])
        elif y[i] == 0:
            str_ = ""
            while i < len(x):
                str_ += x[i]
                if y[i] == 2:
                    break
                i += 1
            res.append(str_)
    return res
```

##### call func
func(x, y)
['我', '是', '算法', '工程师']

- tf code

``` python 
x = tf.constant(list("我是算法工程师"))
y = tf.constant([3, 3, 0, 2, 0, 1, 2, 3, 3])

i = tf.constant(0)
label = tf.constant(0)
out = tf.constant([], dtype=tf.string)

def cond(i, label, out):
    return tf.not_equal(i, x.shape[0])

def body(i, label, out):
    
    str_ = tf.constant("")
    
    def cond(i, label, str_):
        return tf.not_equal(i, x.shape[0])
    
    def body(i, label, str_):
        
        str_ = str_ + x[i]
            
        def _continue(str_):
            def func_1():
                return str_
            return func_1
        
        def _break():
            def func_2():
                return str_
            return func_2
        
        str_ = tf.cond(
            tf.equal(y[i], 2),
            _break(),
            _continue(str_)
        )
        return [tf.add(i, 1), y[i], str_]
    
    _, _, str_ = tf.while_loop(cond, body, [i, label, str_], shape_invariants=[i.get_shape(), label.get_shape(), tf.TensorShape(None)])
        
    return [tf.add(i, 1), y[i], tf.cond(tf.equal(y[i], 3), lambda: tf.concat((out, x[i:i+1]), axis=0), lambda: tf.cond(tf.equal(y[i], 0), lambda: tf.concat((out, [str_]), axis=0), lambda: out))]

i, label, out = tf.while_loop(cond, body, [i, label, out], shape_invariants=[i.get_shape(), label.get_shape(), tf.TensorShape([None])])
```

##### session run
``` python
with tf.Session() as sess:
    o_i, o_label, o_out = sess.run([i, label, out])
```

i want to same result from py to tf,  and i know what 's problem cause this result . But i can't break tf.while_loop inside body function, i have no idea for this. Could you give me some advice？

- My env
  - tensorflow: 1.13.1
  - os:  win10
  - python: 3.5

**Comment by ravikyram** [comment]
I have tried on colab with TF version 1.13.1 and was able to reproduce the issue.Please, find the [gist ](https://colab.sandbox.google.com/gist/ravikyram/cf54250e8963f686dcc73ad1a0b3d16f/untitled151.ipynb) here.Thanks!

**Comment by jvishnuvardhan** [comment]
This is not Build/Installation or Bug/Performance issue. Please post this kind of support questions at [Stackoverflow](https://stackoverflow.com/questions/tagged/tensorflow). There is a big community to support and learn from your questions. GitHub is mainly for addressing bugs in installation and performance. Thanks!

**Comment by zepen** [comment]
> I have tried on colab with TF version 1.13.1 and was able to reproduce the issue.Please, find the [gist ](https://colab.sandbox.google.com/gist/ravikyram/cf54250e8963f686dcc73ad1a0b3d16f/untitled151.ipynb) here.Thanks!

As you can see,  we can't break inner loop on tf version code. we expect ‘ai’，but return ‘b'airam‘.  The problem is inner loop can't break even if we already get result.

**Comment by jvishnuvardhan** [comment]
@zepen Please check with TF1.15.0rc1 and post the issue in Stackoverflow. You might get quick response from the community as it is more of a support question.

I am closing the issue here. Please feel free to open a new issue when you notice a bug in TF. Thanks!
