### ISSUE TITLE
ValueError: Shape (?, ?) must have rank 1

### ISSUE THREAD

**Issue by trunerd** [tensorflow/tensorflow#3211]
r9.0

code:
```
tensor_shape = tf.reshape(tf.shape(tensor), shape=[2])
indexes = tf.reshape(sparse_tensor.indices, shape=tensor_shape)

tf.slice(indexes, one, two)
// Where one and two are tensor constants
OR
tf.slice(sparse_tensor.indices, one, two)
```

Stack trace:

 ```
minus_1_index = tf.slice(indexes, minus_1, one)
  File "/Library/Python/2.7/site-packages/tensorflow/python/ops/array_ops.py", line 251, in slice
    return gen_array_ops._slice(input_, begin, size, name=name)
  File "/Library/Python/2.7/site-packages/tensorflow/python/ops/gen_array_ops.py", line 1634, in _slice
    name=name)
  File "/Library/Python/2.7/site-packages/tensorflow/python/ops/op_def_library.py", line 704, in apply_op
    op_def=op_def)
  File "/Library/Python/2.7/site-packages/tensorflow/python/framework/ops.py", line 2262, in create_op
    set_shapes_for_outputs(ret)
  File "/Library/Python/2.7/site-packages/tensorflow/python/framework/ops.py", line 1702, in set_shapes_for_outputs
    shapes = shape_func(op)
  File "/Library/Python/2.7/site-packages/tensorflow/python/ops/array_ops.py", line 1054, in _SliceShape
    input_shape.assert_has_rank(ndims)
  File "/Library/Python/2.7/site-packages/tensorflow/python/framework/tensor_shape.py", line 621, in assert_has_rank
    raise ValueError("Shape %s must have rank %d" % (self, rank))
ValueError: Shape (?, ?) must have rank 1
```

Obviously it does have a rank of 1 but the dim itself is unknown

**Comment by ibab** [comment]
Are your tensors `one` and `two` scalars?
In that case, the error would make sense, as sparse tensor indices have rank 2 (The shape is `[N, ndims]`, where `N` is the number of non-zero elements and `ndims` the rank of the underlying tensor).

**Comment by aselle** [comment]
Automatically closing due to lack of recent activity. Please reopen when further information becomes available.

**Comment by gallupliu** [comment]
Traceback (most recent call last):
  File "beginner.py", line 217, in <module>
    y = tf.nn.softmax(tf.matmul(x, w_2) + b_2)
  File "/Users/gallupliu/anaconda/lib/python2.7/site-packages/tensorflow/python/ops/math_ops.py", line 1209, in matmul
    name=name)
  File "/Users/gallupliu/anaconda/lib/python2.7/site-packages/tensorflow/python/ops/gen_math_ops.py", line 1178, in _mat_mul
    transpose_b=transpose_b, name=name)
  File "/Users/gallupliu/anaconda/lib/python2.7/site-packages/tensorflow/python/ops/op_def_library.py", line 704, in apply_op
    op_def=op_def)
  File "/Users/gallupliu/anaconda/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2262, in create_op
    set_shapes_for_outputs(ret)
  File "/Users/gallupliu/anaconda/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1702, in set_shapes_for_outputs
    shapes = shape_func(op)
  File "/Users/gallupliu/anaconda/lib/python2.7/site-packages/tensorflow/python/ops/common_shapes.py", line 86, in matmul_shape
    a_shape = op.inputs[0].get_shape().with_rank(2)
  File "/Users/gallupliu/anaconda/lib/python2.7/site-packages/tensorflow/python/framework/tensor_shape.py", line 641, in with_rank
    raise ValueError("Shape %s must have rank %d" % (self, rank))
ValueError: Shape (50, ?, 28) must have rank 2




my code as fellow:

training_data_count = len(X_train)  # training series (with 50% overlap between each serie)
test_data_count = len(X_test)  #  testing series
n_steps = len(X_train[0])  # 50 timesteps per series
n_input = len(X_train[0][0])  # 3 input parameters per timestep

print(type(X_train))
print(type(X_train[0]))
print(type(X_train[0][0]))
print("n_steps:",n_steps)
print("n_input",n_input)
# LSTM Neural Network's internal structure

n_hidden = 28 # Hidden layer num of features
n_classes = 6 # Total classes (should go up, or should go down)
num_layers = 2 # the numerof layer


# Training 

learning_rate = 0.0015
training_iters = training_data_count * 80  # Loop 100 times on the dataset, for a total of 7352000 iterations
batch_size = 1500
display_iter = 15000  # To show test set accuracy during training


# Some debugging info

print "Some useful info to get an insight on dataset's shape and normalisation:"
print "(X shape, y shape, every X's mean, every X's standard deviation)"
print (X_test.shape, y_test.shape, np.mean(X_test), np.std(X_test))
print "The dataset is therefore properly normalised, as expected, but not yet one-hot encoded."

    
    
def extract_batch_size(_train, step, batch_size):
    # Function to fetch a "batch_size" amount of data from "(X|y)_train" data. 
    
    shape = list(_train.shape)
    shape[0] = batch_size
    batch_s = np.empty(shape)

    for i in range(batch_size):
        # Loop index
        index = ((step-1)*batch_size + i) % len(_train)
        batch_s[i] = _train[index] 

    return batch_s


def one_hot(y_):
    # Function to encode output labels from number indexes 
    # e.g.: [[5], [0], [3]] --> [[0, 0, 0, 0, 0, 1], [1, 0, 0, 0, 0, 0], [0, 0, 0, 1, 0, 0]]
    
    y_ = y_.reshape(len(y_))
    n_values = np.max(y_) + 1
    return np.eye(n_values)[np.array(y_, dtype=np.int32)]  # Returns FLOATS


g = tf.Graph()
with g.as_default():
    # Create the model

    x = tf.placeholder("float", [None, n_steps, n_input])
    #x = tf.transpose(x, [1, 0, 2])  # permute n_steps and batch_size
    # Reshape to prepare input to hidden activation
    #x = tf.reshape(x, [-1, n_input]) # (n_steps*batch_size, n_input)

    w_1 = tf.Variable(tf.random_normal([n_input,  n_hidden])) 
    b_1 = tf.Variable(tf.zeros([n_hidden]))

    #x_2 = tf.matmul(x, w_1) + b_1
    x = tf.matmul(tf.reshape(tf.transpose(x, [1, 0, 2]), [-1, n_input]), w_1) + b_1

    x = tf.split(0, n_steps, x) 


    w_2 = tf.Variable(tf.random_normal([n_hidden, n_classes]))
    b_2 = tf.Variable(tf.random_normal([n_classes]))

    #print("x_2",len(x_2),x_2[0].get_shape())
    y = tf.nn.softmax(tf.matmul(x, w_2) + b_2)
   

    # Define loss and optimizer
    y_ = tf.placeholder("float", [None, n_classes ])
    #y_ = tf.Variable(tf.random_normal([ n_classes]))
   
    # Loss, optimizer and evaluation
    #cost = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits(y, y_)) # Softmax loss
    #optimizer = tf.train.AdamOptimizer(learning_rate=learning_rate).minimize(cost) # Adam Optimizer
    print("y,y_",y.get_shape(),y_.get_shape())

    cost = -tf.reduce_sum(y_ * tf.log(y))
    optimizer = tf.train.GradientDescentOptimizer(0.01).minimize(cost)
    #optimizer = tf.train.AdamOptimizer(learning_rate=learning_rate).minimize(cost) # Adam Optimizer
    
    correct_pred = tf.equal(tf.argmax(y,1), tf.argmax(y_,1))
    accuracy = tf.reduce_mean(tf.cast(correct_pred, tf.float32))


    sess = tf.Session()
    # Train
    init = tf.initialize_all_variables()
    sess.run(init)
    print("g_graph_8")
    step = 1
    while step * batch_size <= training_iters:
        batch_xs = extract_batch_size(X_train, step, batch_size)
        batch_ys = one_hot(extract_batch_size(y_train, step, batch_size))
        print("g_graph_8",batch_xs.shape,batch_ys.shape)
        print("g_graph_6",y.get_shape())


        # Fit training using batch data
        _, loss, acc = sess.run(
            [optimizer, cost, accuracy],
            feed_dict={
                x: batch_xs, 
                y_: batch_ys 
            }
        )

**Comment by adrianhust** [comment]
update tf to 0.10, then fix it
