### ISSUE TITLE
tf.Keras.fit() runs forever with 0 samples

### ISSUE THREAD

**Issue by bersbersbers** [tensorflow/tensorflow#32117]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- TensorFlow installed from (source or binary): pip
- TensorFlow version (use command below): `v2.0.0-beta1-5101-gc75bb66a99 2.0.0-rc0`
- Python version: 3.7.4
- CUDA/cuDNN version: n/a (CPU)

**Describe the current behavior**
Code runs forever although nothing is to be trained (no parameters, no data).
```
2019-08-30 15:50:26.413745: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
Epoch 1/2
WARNING:tensorflow:The list of trainable weights is empty. Make sure that you are not setting model.trainable to False before compiling the model.
```

**Describe the expected behavior**
Code stops pretty soon.

**Code to reproduce the issue**
```
import numpy as np
from tensorflow.keras import layers, models

shape = (10, 10, 1)
layer = layers.Input(shape)
model = models.Model(layer, layer)
model.compile(loss='mse')
data = np.zeros((0, *shape))
model.fit(x=data, y=data, epochs=2, verbose=2)
```

**Other info / logs**
It's somewhat annoying if you set the number of training samples to 0 by mistake before starting to train - you might not notice it for a while.

**Comment by gowthamkpr** [comment]
Was able to reproduce the issue [here](https://colab.sandbox.google.com/gist/gowthamkpr/9c6f9b830da370ac1bf8774b3516b32e/untitled124.ipynb) Thanks for reporting @bersbersbers

**Comment by imskr** [comment]
I want to work on this issue!  Please assign me!

**Comment by jvishnuvardhan** [comment]
@bersbersbers I agree with you that there is an issue with `TF2.0rc0`. However, it was resolved in the `tf-nightly-2.0-preview`. Please take a look at the [gist here](https://colab.sandbox.google.com/gist/jvishnuvardhan/4ee3cac706b982b4a5b80328a764e224/tf_32117.ipynb). It clearly throws `ValueError: Empty training data.` within 2 seconds. 

I am closing the issue here. Please feel free to reopen if the issue persists again in the `tf-nightly-2.0-preview`. Thanks!

**Comment by bersbersbers** [comment]
This problem is not fixed in 2.0.0rc1. This may be expected, but I wanted to point it out.

**Comment by omalleyt12** [comment]
@imskr Please feel free to submit a PR for this issue, thanks!

**Comment by imskr** [comment]
@omalleyt12 Thank you, I'm working on it

**Comment by Saduf2019** [comment]
@bersbersbers Could you please confirm if you are still facing any issues.
As i have tried running the same code on tf-nightly and TF 2.1-rc1 please find the [gist](https://colab.sandbox.google.com/drive/1pQn6GLmHo6eyOngJKJUcGkXtX8yRRGkn#scrollTo=YsqkNpZ5TEdW).

**Comment by bersbersbers** [comment]
With `tensorflow==2.1.0`, I get an error, as expected:

```
...
  File "training_utils.py", line 144, in finalize
    raise ValueError('Empty training data.')
ValueError: Empty training data.

During handling of the above exception, another exception occurred:

...
  File "keras/engine/training_v2.py", line 772, in on_epoch
    self.progbar.on_epoch_end(epoch, epoch_logs)
  File "keras/callbacks.py", line 789, in on_epoch_end
    self.progbar.update(self.seen, self.log_values)
  File "keras/utils/generic_utils.py", line 579, in update
    numdigits = int(np.log10(self.target)) + 1
OverflowError: cannot convert float infinity to integer
```

**Comment by bersbersbers** [comment]
With TF 2.3, I don't get "Empty training data." any longer - I now get "UnboundLocalError: local variable 'logs' referenced before assignment" (see #38064).
