### ISSUE TITLE
Why is the inference for the first time longer than later ones?

### ISSUE THREAD

**Issue by RoyIronGrey** [tensorflow/tensorflow#32114]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- OS Platform and Distribution : Windows 10 and Android 9.0
- Mobile device : Xiaomi 8
- TensorFlow version : org.tensorflow:tensorflow-lite:0.0.0-nightly (using 1.11.0 has the same problem)
- Model: ResNet152, ResNet18  convert from Pytorch and MobileNet-V1 from [tensorflow-lite demo](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/java/demo)

if you wanna know how I convert  ResNet152 and ResNet18, you can get the information from  [#issue 27807](https://github.com/tensorflow/tensorflow/issues/27807)

**logs from Android 9.0**
Load ResNet-152 (222 MB)
D/TimeCost: Timecost to load model file: **0 ms**
D/TimeCost: Created a Tensorflow Lite Image Classifier.
Load MobileNet-V1 (16.1 MB)
D/TimeCost: Timecost to load model file: **0 ms** 
D/TimeCost: Created a Tensorflow Lite Image Classifier.
Load ResNet-18 (42.8MB)
D/TimeCost: Timecost to load model file: **0 ms** 
D/TimeCost: Created a Tensorflow Lite Image Classifier.

Inference ResNet-152 for the first time 
D/TimeCost: Timecost to put values into ByteBuffer: **29 ms**
D/TimeCost: Timecost to run model inference: **1681 ms** 
Inference ResNet-152 for the second time 
D/TimeCost: Timecost to put values into ByteBuffer: **3 ms** 
D/TimeCost: Timecost to run model inference: **589 ms** 
Inference ResNet-152 for the third time 
D/TimeCost: Timecost to put values into ByteBuffer: **3 ms** 
D/TimeCost: Timecost to run model inference: **591 ms** 

Inference MobileNet-V1 for the first time
D/TimeCost: Timecost to put values into ByteBuffer: **34 ms**
D/TimeCost: Timecost to run model inference: **134 ms** 
Inference MobileNet-V1 for the second time
D/TimeCost: Timecost to put values into ByteBuffer: **3 ms** 
D/TimeCost: Timecost to run model inference: **56 ms** 
Inference MobileNet-V1 for the third time 
D/TimeCost: Timecost to put values into ByteBuffer: **4 ms**
D/TimeCost: Timecost to run model inference: **58 ms** 

Inference ResNet-18 for the first time 
D/TimeCost: Timecost to put values into ByteBuffer: **10 ms** 
D/TimeCost: Timecost to run model inference: **396 ms**
Inference ResNet-18 for the second time
D/TimeCost: Timecost to put values into ByteBuffer: **2 ms**
D/TimeCost: Timecost to run model inference: **108 ms**
Inference ResNet-18 for the third time
D/TimeCost: Timecost to put values into ByteBuffer: **2 ms**
D/TimeCost: Timecost to run model inference: **85 ms**

**Comment by RoyIronGrey** [comment]
Below is the code of loading model and inference 

**Load Model**
```java
private MappedByteBuffer loadModelFile(Activity activity) throws IOException {
        AssetFileDescriptor fileDescriptor = activity.getAssets().openFd(getModelPath());
        AssetFileDescriptor fileDescriptor = activity.getAssets().openFd(getLabelPath());
        FileInputStream inputStream = new FileInputStream(fileDescriptor.getFileDescriptor());
        FileChannel fileChannel = inputStream.getChannel();
        long startOffset = fileDescriptor.getStartOffset();
        long declaredLength = fileDescriptor.getDeclaredLength();
        return fileChannel.map(FileChannel.MapMode.READ_ONLY, startOffset, declaredLength);
    }
long startTime = SystemClock.uptimeMillis();
tfliteModel = loadModelFile(activity);
long endTime = SystemClock.uptimeMillis();
Log.d(TAG, "Timecost to load model file: " + Long.toString(endTime - startTime));
```

**inference**
```java
protected float[] runInference() {
   tflite.run(Data, labelProbArray);
   return  labelProbArray[0];
}
public float[] classifyFrame(float input[]) {
   if (tflite == null) {
       Log.e(TAG, "Image classifier has not been initialized; Skipped.");
    }
   convertArrayToByteBuffer(input);
   // Here's where the magic happens!!!
   long startTime = SystemClock.uptimeMillis();
   float[] result = runInference();
   long endTime = SystemClock.uptimeMillis();
   Log.d(TAG, "Timecost to run model inference: " + Long.toString(endTime - startTime));
   return result;
}
```
Since the code that loads the model takes very little time, I think the first inference actually includes the time to copy the model into memory, but this is just a guess. Does anyone know why in details and what happened in the codes?

**Comment by freedomtan** [comment]
Think about how a computer works. This `fileChannel.map(FileChannel.MapMode.READ_ONLY, startOffset, declaredLength);` means `mmap()` or something similar is used. Its default behavior could be on-demand loading. So your measured time to load a model probably is not what you intended to measure. And there are TLBs and caches between DRAM and CPUs, for the very first time, cache hit ratio should be relative low.

**Comment by RoyIronGrey** [comment]
> Think about how a computer works. This `fileChannel.map(FileChannel.MapMode.READ_ONLY, startOffset, declaredLength);` means `mmap()` or something similar is used. Its default behavior could be on-demand loading. So your measured time to load a model probably is not what you intended to measure. And there are TLBs and caches between DRAM and CPUs, for the very first time, cache hit ratio should be relative low.

Thank you. I did some research on [how MappedByteBuffer works](https://docs.oracle.com/en/java/javase/12/docs/api/java.base/java/nio/MappedByteBuffer.html) and some experiments on how the memory changes during the whole process according to your suggestions and source code. I may find some clues. Thanks again.

**Comment by ravikyram** [comment]
@RoyIronGrey 
Can you please confirm if @freedomtan's workaround is working for you.Thanks!

**Comment by ravikyram** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
