### ISSUE TITLE
Sessions that are closed and reset and all inputs and outputs are out of scope, do not release GPU memory.

### ISSUE THREAD

**Issue by samhodge** [tensorflow/tensorflow#32128]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):MacOS 10.13
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):source 1.12.0
- TensorFlow version (use command below):
- Python version:NA
- Bazel version (if compiling from source):0.19.2
- GCC/Compiler version (if compiling from source):Apple LLVM version 9.1.0 (clang-902.0.39.2)
- CUDA/cuDNN version:10.0.130
- GPU model and memory:GTX 1060

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
Memory from tensorflow sessions is not freed when a session is closed and no variables are in scope, memory is only freed on program exit
**Describe the expected behavior**
Memory should be freed from the GPU on calling close and reset in C++, or some other way to release GPU resources without forking a process.
**Code to reproduce the issue**

```
#include <stdlib.h>     /* getenv */
#include <iostream>		
#include <tensorflow/core/platform/init_main.h>
#include <tensorflow/core/public/session.h>
#include <tensorflow/core/framework/tensor_shape.h>
#include <string>
#include "cuda_runtime_api.h"
#include <cuda.h>


int freeCudaMem(){
		int gpuCount, i;
		CUresult res;
		CUdevice dev;
		CUcontext ctx;
		int result;
		cuInit(0);
		cuDeviceGetCount(&gpuCount);
		size_t curClockRate = 0;
		size_t curMaxMem = 0;

		for (int i = 0; i < gpuCount; i++) {
			cudaSetDevice(i);
			cudaDeviceProp curDeviceProp;
			cudaError_t err = cudaGetDeviceProperties(&curDeviceProp, i);
			if (err != cudaSuccess) {
				continue;
			}
			size_t free_mem, total_mem;
			cuDeviceGet(&dev, i);
			cuCtxCreate(&ctx, 0, dev);
			res = cuMemGetInfo(&free_mem, &total_mem);
			result= (int)free_mem;
		}
		return result;
}


int main (int argc, char *argv[]) { 
	setenv("TF_CPP_MIN_VLOG_LEVEL", "3", 1);
	setenv("TF_CPP_MIN_LOG_LEVEL", "3", 1);

	{
		std::cout << "Start of program:  " << freeCudaMem() << std::endl;
		tensorflow::SessionOptions options;
		tensorflow::ConfigProto &config = options.config;
		config.mutable_gpu_options()->set_allow_growth(true);
		auto* device_count = options.config.mutable_device_count();
		device_count->insert({ "GPU", 1 });
		device_count->insert({ "CPU", 1 });

		std::unique_ptr<tensorflow::Session> session = std::unique_ptr<tensorflow::Session>(tensorflow::NewSession(options));	

		tensorflow::GraphDef graph_def;
		std::string graphFile("/path/to/large/frozen_model.pb");
		tensorflow::Status graphLoadedStatus = ReadBinaryProto(tensorflow::Env::Default(),graphFile.c_str(),&graph_def);
		auto inputTensor2 = tensorflow::Tensor(tensorflow::DT_UINT8, { 1, 2048, 2048, 3 });
		std::vector<tensorflow::Tensor> outputs;
		tensorflow::Status session_create_status = session->Create(graph_def);                                                        
		tensorflow::Status run_status = session->Run({ { "InputTensor", inputTensor2 } }, { { "OutputTensor" } },{},&outputs);
		outputs.clear();	
		int number3;
		std::cout << "After session:     " << freeCudaMem() << std::endl;
		tensorflow::Status closeStatus3  = session	->Close();
		std::cout << "Close Status: " << closeStatus3 << std::endl;  
		std::cout << "After close:       " << freeCudaMem() << std::endl;                                                                                                        
		session.reset();
		std::cout << "After reset:       " << freeCudaMem() << std::endl;
	}
	{
		std::cout << "Start of program2: " << freeCudaMem() << std::endl;
		tensorflow::SessionOptions options2;
		tensorflow::ConfigProto &config2 = options2.config;
		config2.mutable_gpu_options()->set_allow_growth(true);
		auto* device_count2 = options2.config.mutable_device_count();
		device_count2->insert({ "GPU", 1 });
		device_count2->insert({ "CPU", 1 });

		std::unique_ptr<tensorflow::Session> session2 = std::unique_ptr<tensorflow::Session>(tensorflow::NewSession(options2));	


		tensorflow::GraphDef graph_def2;
		std::string graphFile2("/path/to/large/frozen_model.pb");
		tensorflow::Status graphLoadedStatus2 = ReadBinaryProto(tensorflow::Env::Default(),graphFile2.c_str(),&graph_def2);
		auto inputTensor22 = tensorflow::Tensor(tensorflow::DT_UINT8, { 1, 2048, 2048, 3 });
		std::vector<tensorflow::Tensor> outputs2;
		tensorflow::Status session_create_status2 = session2->Create(graph_def2);                                                        
		tensorflow::Status run_status2 = session2->Run({ { "InputTensor", inputTensor22 } }, { { "OutputTensor" } },{},&outputs2);
		outputs2.clear();	
	
		int number2;
		std::cout << "After session2:    " << freeCudaMem() << std::endl;
		tensorflow::Status closeStatus2  = session2->Close();
		std::cout << "Close Status2: " << closeStatus2 << std::endl;  
		std::cout << "After close2:      " << freeCudaMem() << std::endl;                                                                                                        
		session2.reset();
		std::cout << "After reset2:      " << freeCudaMem() << std::endl;
	}
	{
		std::cout << "Start of program3: " << freeCudaMem() << std::endl;
		tensorflow::SessionOptions options3;
		tensorflow::ConfigProto &config3 = options3.config;
		config3.mutable_gpu_options()->set_allow_growth(true);
		auto* device_count3 = options3.config.mutable_device_count();
		device_count3->insert({ "GPU", 1 });
		device_count3->insert({ "CPU", 1 });
		std::unique_ptr<tensorflow::Session> session3 = std::unique_ptr<tensorflow::Session>(tensorflow::NewSession(options3));	
		tensorflow::GraphDef graph_def3;
		std::string graphFile3("/path/to/large/frozen_model.pb");
		tensorflow::Status graphLoadedStatus3 = ReadBinaryProto(tensorflow::Env::Default(),graphFile3.c_str(),&graph_def3);
		auto inputTensor32 = tensorflow::Tensor(tensorflow::DT_UINT8, { 1, 2048, 2048, 3 });
		std::vector<tensorflow::Tensor> outputs3;
		tensorflow::Status session_create_status3 = session3->Create(graph_def3);                                                        
		tensorflow::Status run_status3 = session3->Run({ { "InputTensor", inputTensor32 } }, { { "OutputTensor" } },{},&outputs3);
		outputs3.clear();	
		int number3;
		std::cout << "After session3:    " << freeCudaMem() << std::endl;
		tensorflow::Status closeStatus3  = session3->Close();
		std::cout << "Close Status3: " << closeStatus3 << std::endl;  
		std::cout << "After close3:      " << freeCudaMem() << std::endl;                                                                                                        
		session3.reset();
		std::cout << "After reset3:      " << freeCudaMem() << std::endl;
	}

}
```

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

Here is the output from the program above:
```
Start of program:  1031380992
After session:     700043264
Close Status: OK
After close:       635219968
After reset:       570400768
Start of program2: 505581568
After session2:    440766464
Close Status2: OK
After close2:      375943168
After reset2:      311111680
Start of program3: 246292480
After session3:    181473280
Close Status3: OK
After close3:      116654080
After reset3:      1013313536
```

Note the GPU memory available keeps going down even though the session has been closed and reset and all variables are out of scope.

**Comment by ymodak** [comment]
By default TensorFlow allocates GPU memory for the lifetime of the process, not the lifetime of the session object. More details at: https://www.tensorflow.org/programmers_guide/using_gpu#allowing_gpu_memory_growth

Thus, if you want memory to be freed, you'll have to exit the program, not just close the session.

Hope that helps.

**Comment by samhodge** [comment]
That does not help, the tensorflow library is embedded as a plugin to a parent application.

Either that process will need to fork a subprocess so that application can terminate the entire subprocess.

But at that point I will basically have a client server architecture to a plugin in a parent application, with is not the intended design.

Surely the memory for the session can be managed without shutting down the application.

**Comment by samhodge** [comment]
The request to clear the memory without shutting down the application has been a request from at least two users in the last six months, I cannot deliver on this user story without changing the architecture of the application dramatically, which will be different on Windows, OSX and Linux, because I would be spawning subprocesses so they could terminate just to release memory.

**Comment by samhodge** [comment]
Any update on this?

**Comment by samhodge** [comment]
Any eyes on this?

**Comment by samhodge** [comment]
A response would be great

**Comment by aaroey** [comment]
@samhodge sorry for late reply. As mentioned by @ymodak above, there is currently no way to reset the memory allocator without exiting the program. There is a [test-only method](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/common_runtime/gpu/gpu_process_state.h#L130) that can help to reset the memory owned by the process but that is not exposed.

**Comment by samhodge** [comment]
Sorry for the lack of results reply. It seems odd to be that an API with so many features lacks a tear down function apart from at the operating system level.

**Comment by sanjoy** [comment]
Hi @samhodge,

We don't have cycles to investigate this in the near term.  Are you open to contributing a patch to implement this hook?

**Comment by samhodge** [comment]
I would be more inclined to move away from Tensorflow or to have a subprocess architecture to work around the problem but the possibility to fix it is something I might entertain.

Sam

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.
