### ISSUE TITLE
[TF.2.0 API Docs] tf.ones_like

### ISSUE THREAD

**Issue by JoelTsui** [tensorflow/tensorflow#32129]
# URL(s) with the issue:
https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/ones_like

# Description of the issue (what needs changing):
change "Creates a tensor with all elements set to zero." to "Creates a tensor with all elements set to one."

**Comment by jvishnuvardhan** [comment]
Automatically closing this out since I understand it to be resolved by the https://github.com/tensorflow/docs/pull/987 (merged already), but please let me know if I'm mistaken.Thanks!
