### ISSUE TITLE
Accompany TF_LoadLibrary with TF_DeleteLibrary

### ISSUE THREAD

**Issue by IvanUkhov** [tensorflow/tensorflow#3213]
The C API provides the [following function](https://github.com/tensorflow/tensorflow/blob/r0.9/tensorflow/core/public/tensor_c_api.h#L357) for loading libraries:

```c
extern TF_Library* TF_LoadLibrary(const char* library_filename, TF_Status* status);
```

The documentation says that “the caller owns the library handle” returned by the function. Unlike other functions allocating memory and returning pointers, `TF_LoadLibrary` doesn’t have a counterpart for properly freeing the memory. Note that it’s not about unloading the library but about deallocating the `TF_Library` struct; although, a function for unloading the library would also be nice. Thanks!

Regards,
Ivan

**Comment by aselle** [comment]
I suppose it is possible that the caller cannot know what free-store the memory of TF_LoadLibrary was allocated from. Unloading libraries is generally unreliable as dlclose isn't really required by POSIX to do much except invalidate the handle.
