### ISSUE TITLE
The function tf.graph_util.remove_training_nodes doesn't work as expected

### ISSUE THREAD

**Issue by haifenghan** [tensorflow/tensorflow#32145]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: No
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 1.14.0
- Python version: Python 3.6.8
- Bazel version (if compiling from source): NO
- GCC/Compiler version (if compiling from source): NO
- CUDA/cuDNN version: NA
- GPU model and memory: NA

**Describe the current behavior**
When I trying to remove training node with the function tf.graph_util.remove_training_nodes, a Identity node named "FeatureExtractor/MobilenetV2/expanded_conv_13/expansion_output
" is not removed.

![image](https://user-images.githubusercontent.com/4157827/64088048-358e6100-cd72-11e9-93c3-8dfbdab3fc14.png)

**Describe the expected behavior**
I tried this in Python2 and there is no such issue. Could you look into it?
**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.
You can get the model from http://download.tensorflow.org/models/object_detection/ssd_mobilenet_v2_coco_2018_03_29.tar.gz
After untar, you'll see ssd_mobilenet_v2_coco_2018_03_29/frozen_inference_graph.pb.
```python
import tensorflow as tf
input_graph_def = tf.GraphDef()
with open("ssd_mobilenet_v2_coco_2018_03_29/frozen_inference_graph.pb", "rb") as f:
    input_graph_def.ParseFromString(f.read())
    out_graph_def = tf..graph_util.remove_training_nodes(input_graph_def)
    tf.io.write_graph(out_graph_def, "./", "fused.pb", as_text=False)
```
 Then you can review it in https://lutzroeder.github.io/netron/

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.
NA

**Comment by ymodak** [comment]
I was able to reproduce the behavior using TF 1.15.2
However unfortunately [`tf.graph_util.remove_training_nodes`](https://www.tensorflow.org/api_docs/python/tf/graph_util/import_graph_def) is deprecated and no longer part of TF 2.
