### ISSUE TITLE
vs2015 build tensorflow failed on windows

### ISSUE THREAD

**Issue by YoungSharp** [tensorflow/tensorflow#32146]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): win7 64
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: no
- TensorFlow installed from (source or binary):  source
- TensorFlow version: 1.12.0
- Python version: 3.6
- Installed using virtualenv? pip? conda?: compile
- Bazel version (if compiling from source): cmake 3.15.0
- GCC/Compiler version (if compiling from source):  vs2015 update3
- CUDA/cuDNN version:  no
- GPU model and memory: no

**Describe the problem**
When using vs 2015 update3 to build tensorflow, got following error(see detail in log). 
operator system：windows7 x64
tensorflow versiono: 1.12.0 - cpu

**Provide the exact sequence of commands / steps that you executed before running into the problem**
1. cmake 
2. vs 2015 update3 (build icu and abseil-cpp by myself, and linked to tensorflow project)
3. build

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

85>tf_session_helper.obj : error LNK2019: unresolved external symbol "public: __cdecl tensorflow::SessionRef::SessionRef(class tensorflow::Session *)" (??0SessionRef@tensorflow@@QEAA@PEAVSession@1@@Z) referenced in function "struct TF_Session * __cdecl tensorflow::TF_NewSessionRef(struct TF_Graph *,struct TF_SessionOptions const *,struct TF_Status *)" (?TF_NewSessionRef@tensorflow@@YAPEAUTF_Session@@PEAUTF_Graph@@PEBUTF_SessionOptions@@PEAUTF_Status@@@Z)
85>c_api.cc.obj : error LNK2019: unresolved external symbol "void __cdecl tensorflow::NewRemoteDevices(class tensorflow::Env *,class tensorflow::WorkerCacheInterface *,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,class std::function<void __cdecl(class tensorflow::Status const &,class std::vector<class tensorflow::Device *,class std::allocator<class tensorflow::Device *> > *)>)" (?NewRemoteDevices@tensorflow@@YAXPEAVEnv@1@PEAVWorkerCacheInterface@1@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@V?$function@$$A6AXAEBVStatus@tensorflow@@PEAV?$vector@PEAVDevice@tensorflow@@V?$allocator@PEAVDevice@tensorflow@@@std@@@std@@@Z@5@@Z) referenced in function "class tensorflow::Status __cdecl `anonymous namespace'::GetAllRemoteDevices(class std::vector<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,class std::allocator<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > > > const &,class tensorflow::WorkerCacheInterface *,class std::unique_ptr<class tensorflow::DeviceMgr,struct std::default_delete<class tensorflow::DeviceMgr> > *)" (?GetAllRemoteDevices@?A0xdd98b8cf@@YA?AVStatus@tensorflow@@AEBV?$vector@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@V?$allocator@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@2@@std@@PEAVWorkerCacheInterface@3@PEAV?$unique_ptr@VDeviceMgr@tensorflow@@U?$default_delete@VDeviceMgr@tensorflow@@@std@@@5@@Z)
85>c_api.cc.obj : error LNK2019: unresolved external symbol "public: class tensorflow::Status __cdecl tensorflow::SessionMgr::CreateSession(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,class tensorflow::ServerDef const &,bool)" (?CreateSession@SessionMgr@tensorflow@@QEAA?AVStatus@2@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEBVServerDef@2@_N@Z) referenced in function "class tensorflow::Status __cdecl `anonymous namespace'::UpdateTFE_ContextWithServerDef(int,class tensorflow::ServerDef const &,struct TFE_Context *)" (?UpdateTFE_ContextWithServerDef@?A0xdd98b8cf@@YA?AVStatus@tensorflow@@HAEBVServerDef@3@PEAUTFE_Context@@@Z)
85>c_api.cc.obj : error LNK2019: unresolved external symbol "public: class tensorflow::Status __cdecl tensorflow::SessionMgr::WorkerSessionForSession(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,class std::shared_ptr<struct tensorflow::WorkerSession> *)" (?WorkerSessionForSession@SessionMgr@tensorflow@@QEAA?AVStatus@2@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEAV?$shared_ptr@UWorkerSession@tensorflow@@@5@@Z) referenced in function "class tensorflow::Status __cdecl `anonymous namespace'::UpdateTFE_ContextWithServerDef(int,class tensorflow::ServerDef const &,struct TFE_Context *)" (?UpdateTFE_ContextWithServerDef@?A0xdd98b8cf@@YA?AVStatus@tensorflow@@HAEBVServerDef@3@PEAUTFE_Context@@@Z)
85>c_api.cc.obj : error LNK2019: unresolved external symbol "class tensorflow::eager::EagerClientCache * __cdecl tensorflow::eager::NewGrpcEagerClientCache(class std::shared_ptr<class tensorflow::GrpcChannelCache>)" (?NewGrpcEagerClientCache@eager@tensorflow@@YAPEAVEagerClientCache@12@V?$shared_ptr@VGrpcChannelCache@tensorflow@@@std@@@Z) referenced in function "class tensorflow::Status __cdecl `anonymous namespace'::UpdateTFE_ContextWithServerDef(int,class tensorflow::ServerDef const &,struct TFE_Context *)" (?UpdateTFE_ContextWithServerDef@?A0xdd98b8cf@@YA?AVStatus@tensorflow@@HAEBVServerDef@3@PEAUTFE_Context@@@Z)

**Comment by YoungSharp** [comment]
i have noticed that there is an issue just as the same as this one, but it seems like there is no solution for it. especially build under cmake.

**Comment by gadagashwini** [comment]
@YoungSharp, 
The TensorFlow team does not officially support cmake, sorry. Please try out building from source with Bazel. Thanks!

**Comment by YoungSharp** [comment]
i had solved it by adding some file(find those unrecognized function in tensorflow folder) into project tensorflow and comment "WorkerSessionForSession" function then build succeeded.

**Comment by BigPandaCPU** [comment]
> i had solved it by adding some file(find those unrecognized function in tensorflow folder) into project tensorflow and comment "WorkerSessionForSession" function then build succeeded.

Hi，I get the same error,and I haven't found the solutions.Could you please tell me how to solve it ?Thanks
