### ISSUE TITLE
tf.gather should support batch_dims == rank(indices)

### ISSUE THREAD

**Issue by mpdn** [tensorflow/tensorflow#32158]
**System information**
- TensorFlow version (you are using): 2.0
- Are you willing to contribute it (Yes/No): Yes, if it's just overzealous checks.

**Describe the feature and the current behavior/state.**

Currently, `tf.gather` requires that `batch_dim` is less than `rank(indices)`, but it seems like `batch_dim == rank(indices)` should logically be supported as well. This would be equivalent to a scalar lookup in the last axis of `params`.

Supporting this should come pretty natural and I think that, for the CPU code at least, it is already supported; the checks just need to be changed from `<` to `<=`.

**Will this change the current api? How?**

No.

**Comment by MattShannon** [comment]
+1. I just hit this issue as well. Note that it can be worked around by artificially adding an axis before the gather then removing it after the gather.

**Comment by yongtang** [comment]
@mpdn @MattShannon This issue has been fixed in https://github.com/tensorflow/tensorflow/commit/93ef77d971716636f88c39bff6a82cfad6a24000#diff-0a1b05e2252bef657373e11f17bfa5d3

I will close this issue for now, but feel free to reopen if the issue persists.
