### ISSUE TITLE
Failed to build tensorflow pip package (Python 2.7.15+) inside of the docker image tensorflow/tensorflow:devel

### ISSUE THREAD

**Issue by wwwind** [tensorflow/tensorflow#32152]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: none
- TensorFlow installed from (source or binary): docker image tensorflow/tensorflow:devel
- TensorFlow version: 1.14
- Python version: 2.7.15+
- Installed using virtualenv? pip? conda?:
- Bazel version (if compiling from source): 0.26.1
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: none
- GPU model and memory: none

**Describe the problem**

Unable to build tensorflow pip package inside of the provided docker image **tensorflow/tensorflow:devel** for the tensorflow development using Python 2.7+.

The errors are:
```
Traceback (most recent call last):
File "/usr/lib/python2.7/site.py", line 554, in <module>
main()
File "/usr/lib/python2.7/site.py", line 536, in main
known_paths = addusersitepackages(known_paths)
File "/usr/lib/python2.7/site.py", line 272, in addusersitepackages
user_site = getusersitepackages()
File "/usr/lib/python2.7/site.py", line 247, in getusersitepackages
user_base = getuserbase() # this will also set USER_BASE
File "/usr/lib/python2.7/site.py", line 237, in getuserbase
USER_BASE = get_config_var('userbase')
File "/usr/lib/python2.7/sysconfig.py", line 587, in get_config_var
return get_config_vars().get(name)
File "/usr/lib/python2.7/sysconfig.py", line 538, in get_config_vars
_CONFIG_VARS['userbase'] = _getuserbase()
File "/usr/lib/python2.7/sysconfig.py", line 215, in _getuserbase
return env_base if env_base else joinuser("~", ".local")
File "/usr/lib/python2.7/sysconfig.py", line 201, in joinuser
return os.path.expanduser(os.path.join(*args))
File "/usr/lib/python2.7/posixpath.py", line 262, in expanduser
userhome = pwd.getpwuid(os.getuid()).pw_dir
KeyError: 'getpwuid(): uid not found: 2308'
Target //tensorflow/tools/pip_package:build_pip_package failed to build
```

**Provide the exact sequence of commands / steps that you executed before running into the problem**

```
docker run  -u $(id -u):$(id -g) -v $PWD:$PWD -i --env USER=$USER -w $PWD/repo --env HOME=$PWD  tensorflow/tensorflow:devel bazel build -c opt //tensorflow/tools/pip_package:build_pip_package
```

When I run it without   `-u $(id -u):$(id -g)`, it works fine, but this is not the recommended way.

**Any other info / logs**
If I run the image tensor/tensorflow:devel like this:

```
docker run -it -u $(id -u):$(id -g) tensorflow/tensorflow:devel bash
```

and then I call this command inside of the docker image:
```
whoami
```
The result is "cannot find name for user ID"

The possible solution is put this line inside of the docker file: devel-cpu.Dockerfiles
RUN chmod g+w /etc/passwd /etc/group

Then this file /etc/passwd will be writable inside of the docker and it will be possible to 
- add passwd file entry for $(id -u)
- add passwd file entry for $(id -g)

This is an issue only for some packages of Python 2.7, but not for Python 3.0

**Comment by angersson** [comment]
Thanks for reporting this. I've verified it and would welcome a PR to fix the issue.

Unfortunately, since this only affects Python 2.7, it's not as high of a priority right now (AFAIK, TensorFlow will stop supporting Python 2.7 on January 1, when Python 2.7 is EOL), so I don't have the time to fix it myself this week.

**Comment by wwwind** [comment]
@angersson I opened a PR for this issue.
