### ISSUE TITLE
build_pip_package => no such package '@iron_range_behavior//'

### ISSUE THREAD

**Issue by timotheecour** [tensorflow/tensorflow#3215]
bazel build -c opt --config=cuda //tensorflow/cc:tutorials_example_trainer
works (and runs)
bazel build -c opt --config=cuda //tensorflow/tools/pip_package:build_pip_package
fails:

ERROR: ~/git_clone/tensorflow/tensorflow/tensorboard/bower/BUILD:5:1: no such package '@iron_range_behavior//': Error cloning repository: https://github.com/polymerelements/iron-range-behavior.git: cannot open git-upload-pack caused by https://github.com/polymerelements/iron-range-behavior.git: cannot open git-upload-pack caused by https://github.com/polymerelements/iron-range-behavior.git: cannot open git-upload-pack and referenced by '//tensorflow/tensorboard/bower:bower'.
ERROR: Loading failed; build aborted.

### Environment info
Operating System: ubuntu 16.04

Installed version of CUDA and cuDNN: 
(please attach the output of `ls -l /path/to/cuda/lib/libcud*`):
/usr/local/cuda/lib64/libcudart.so.8.0.2

If installed from sources, provide the commit hash:
71f6bb336e5e11d6da2cedac6ba1c992ad9992bd

**Comment by aselle** [comment]
Make sure you can actually git clone thoise packages manually. 
See https://github.com/bazelbuild/bazel/issues/587 for information about bazel behind a proxy.

**Comment by aselle** [comment]
Automatically closing due to lack of recent activity. Please reopen when further information becomes available.
