### ISSUE TITLE
[lite doc] broken link in`TensorFlow Lite and TensorFlow operator compatibility`

### ISSUE THREAD

**Issue by csukuangfj** [tensorflow/tensorflow#32162]
The link for `tf.transpose` on page https://www.tensorflow.org/lite/guide/ops_compatibility#compatible_operations
is broken.

**Comment by lamberta** [comment]
Thanks. Looks like this only exists in TF2: https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/transpose
It will (eventually) sort itself out, but it shouldn't be linked in TF1

**Comment by lamberta** [comment]
Ehh, the links on that page should all use backticks for API symbols and not absolute URLs. I'll fix it
