### ISSUE TITLE
after freezing a graph the inference time is slower than when restoring variables from checkpoint 

### ISSUE THREAD

**Issue by laurentk67** [tensorflow/tensorflow#3216]
I'm using the  freeze_graph.py script that takes a graph definition and the corresponding checkpoint to combine them them into a single file (variables are replaced by constants). On my system (Linux, titanx tensorflow R0.9) I'm measuring aprox 50% slower inference time compared to the same graph running with  variables restored from the checkpoint file. 
Is it normal?
Thanks
Laurent

**Comment by yaroslavvb** [comment]
Freezing graph inlines variable values into Graph definition, while checkpoint restore stores the values in Containers. Graph isn't optimized for storing large tensors so there may be some slowness introduced by this method. I would run under cProfile and visualize using snakeviz to see where the time is going

**Comment by aselle** [comment]
@yaroslavvb's response seems most plausible. Please let us know if it seems to be some other bug rather than performance implications of the strategy. Thanks!

**Comment by aselle** [comment]
Automatically closing due to lack of recent activity. Please reopen when further information becomes available.
