### ISSUE TITLE
[1.14] Cannot use a custom op with `TPUStrategy` that works with `MirroredStrategy`

### ISSUE THREAD

**Issue by suyash** [tensorflow/tensorflow#32163]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes.
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): colab
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: no
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): v1.14.0-rc1-22-gaf24dc91b5 1.14.0
- Python version: Python 3.6.8
- Bazel version (if compiling from source): n/a
- GCC/Compiler version (if compiling from source): n/a
- CUDA/cuDNN version: 10
- GPU model and memory: n/a

**Describe the current behavior**

Copied from https://github.com/google/sentencepiece/issues/390 since this might be a `TPUStrategy` issue, since things work with `MirroredStrategy`.

[SentencePiece](https://github.com/google/sentencepiece) is a library that provides extremely fast and efficient utilities for text encoding during training. It accomplishes this by providing custom ops written in C++, instead of userland code. The custom ops are detected and work with regular TensorFlow and in distributed GPU mode with `MirroredStrategy`, but are not getting detected when using `TPUStrategy`. The custom op makes training ~3x faster, compared to using something like [SubwordTextEncoder](https://www.tensorflow.org/datasets/api_docs/python/tfds/features/text/SubwordTextEncoder).

**Describe the expected behavior**

The custom ops themselves should work with TPUs so I can train on TPUs without compromising the performance of my data pipeline.

**Code to reproduce the issue**

https://colab.research.google.com/gist/suyash/286ba54a1cd6d51fba5c2f091b4900ce

**Comment by frankchn** [comment]
Unfortunately, custom ops are not supported on TPUs right now, since end users cannot control the custom TensorFlow instance that is running on the TPUs.

We are investigating various ways to overcome this limitation, but don't have anything to announce right now.
