### ISSUE TITLE
ImportError: cannot import name pywrap_tensorflow

### ISSUE THREAD

**Issue by xinyuwuhenZZ** [tensorflow/tensorflow#3217]
I followed the TensorFlow installation instructions for Mac OS X.(Mac OS X, CPU only, Python 2.7):
export TF_BINARY_URL=https://storage.googleapis.com/tensorflow/mac/tensorflow-0.9.0rc0-py2-none-any.whl
sudo pip install --upgrade $TF_BINARY_URL

Got this error:

In [2]: import tensorflow
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-2-a649b509054f> in <module>()
----> 1 import tensorflow

/usr/local/lib/python2.7/site-packages/tensorflow/__init__.py in <module>()
     21 from __future__ import print_function
     22 
---> 23 from tensorflow.python import *

/usr/local/lib/python2.7/site-packages/tensorflow/python/__init__.py in <module>()
     46 _default_dlopen_flags = sys.getdlopenflags()
     47 sys.setdlopenflags(_default_dlopen_flags | ctypes.RTLD_GLOBAL)
---> 48 from tensorflow.python import pywrap_tensorflow
     49 sys.setdlopenflags(_default_dlopen_flags)
     50 

ImportError: cannot import name pywrap_tensorflow

Any help would be appreciated.

**Comment by Waffleboy** [comment]
You're running the script in the same directory as tensorflow. Move it out and you should be fine.

**Comment by aselle** [comment]
Thanks for the response @Waffleboy. @xinyuwuhenZZ , please close the issue if this resolves installation for you.

**Comment by XianXing** [comment]
Similar problem was asked and addressed in #1013.

**Comment by xinyuwuhenZZ** [comment]
@Waffleboy @aselle, Thanks for help! I did run script in other directory rather than installation directory.  
@XianXing, not exactly the same issue, #1013

**Comment by aselle** [comment]
Did that resolve the issue @xinyuwuhenZZ. If so, please close the issue.

**Comment by xinyuwuhenZZ** [comment]
Not yet.

**Comment by Waffleboy** [comment]
Can you post the full traceback (in proper code annotation format) after you have moved it to a completely different directory?

**Comment by xinyuwuhenZZ** [comment]
In [1]: import tensorflow as tf
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-1-41389fad42b5> in <module>()
----> 1 import tensorflow as tf

/usr/local/lib/python2.7/site-packages/tensorflow/__init__.py in <module>()
     21 from __future__ import print_function
     22 
---> 23 from tensorflow.python import *

/usr/local/lib/python2.7/site-packages/tensorflow/python/__init__.py in <module>()
     63 from tensorflow.core.util.event_pb2 import *
     64 # Import things out of contrib
---> 65 import tensorflow.contrib as contrib
     66 
     67 # Framework

/usr/local/lib/python2.7/site-packages/tensorflow/contrib/__init__.py in <module>()
     26 from tensorflow.contrib import grid_rnn
     27 from tensorflow.contrib import layers
---> 28 from tensorflow.contrib import learn
     29 from tensorflow.contrib import linear_optimizer
     30 from tensorflow.contrib import lookup

/usr/local/lib/python2.7/site-packages/tensorflow/contrib/learn/__init__.py in <module>()
     70 
     71 # pylint: disable=wildcard-import
---> 72 from tensorflow.contrib.learn.python.learn import *
     73 from tensorflow.python.util.all_util import make_all
     74 

/usr/local/lib/python2.7/site-packages/tensorflow/contrib/learn/python/__init__.py in <module>()
     21 
     22 # pylint: disable=wildcard-import
---> 23 from tensorflow.contrib.learn.python.learn import *

/usr/local/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/__init__.py in <module>()
     23 
     24 from tensorflow.contrib.learn.python.learn import datasets
---> 25 from tensorflow.contrib.learn.python.learn import estimators
     26 from tensorflow.contrib.learn.python.learn import graph_actions
     27 from tensorflow.contrib.learn.python.learn import io

/usr/local/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/estimators/__init__.py in <module>()
     21 
     22 from tensorflow.contrib.learn.python.learn.estimators._sklearn import NotFittedError
---> 23 from tensorflow.contrib.learn.python.learn.estimators.autoencoder import TensorFlowDNNAutoencoder
     24 from tensorflow.contrib.learn.python.learn.estimators.base import TensorFlowBaseTransformer
     25 from tensorflow.contrib.learn.python.learn.estimators.base import TensorFlowEstimator

/usr/local/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/estimators/autoencoder.py in <module>()
     23 
     24 from tensorflow.contrib.learn.python.learn import models
---> 25 from tensorflow.contrib.learn.python.learn.estimators.base import TensorFlowBaseTransformer
     26 from tensorflow.python.ops import nn
     27 

/usr/local/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/estimators/base.py in <module>()
     32 from tensorflow.contrib import layers
     33 from tensorflow.contrib.learn.python.learn.estimators import _sklearn
---> 34 from tensorflow.contrib.learn.python.learn.estimators import estimator
     35 from tensorflow.contrib.learn.python.learn.estimators._sklearn import NotFittedError
     36 from tensorflow.contrib.learn.python.learn.io.data_feeder import setup_train_data_feeder

/usr/local/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/estimators/estimator.py in <module>()
     36 from tensorflow.contrib.learn.python.learn.estimators import tensor_signature
     37 from tensorflow.contrib.learn.python.learn.estimators._sklearn import NotFittedError
---> 38 from tensorflow.contrib.learn.python.learn.io import data_feeder
     39 from tensorflow.contrib.learn.python.learn.utils import checkpoints
     40 

/usr/local/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/io/__init__.py in <module>()
     26 from tensorflow.contrib.learn.python.learn.io.graph_io import read_batch_features
     27 from tensorflow.contrib.learn.python.learn.io.graph_io import read_batch_record_features
---> 28 from tensorflow.contrib.learn.python.learn.io.pandas_io import extract_pandas_data
     29 from tensorflow.contrib.learn.python.learn.io.pandas_io import extract_pandas_labels
     30 from tensorflow.contrib.learn.python.learn.io.pandas_io import extract_pandas_matrix

/usr/local/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/io/pandas_io.py in <module>()
     22 try:
     23   # pylint: disable=g-import-not-at-top
---> 24   import pandas as pd
     25   HAS_PANDAS = True
     26 except ImportError:

/usr/local/lib/python2.7/site-packages/pandas/__init__.pyc in <module>()
     37 import pandas.core.config_init
     38 
---> 39 from pandas.core.api import *
     40 from pandas.sparse.api import *
     41 from pandas.stats.api import *

/usr/local/lib/python2.7/site-packages/pandas/core/api.py in <module>()
      8 from pandas.core.common import isnull, notnull
      9 from pandas.core.categorical import Categorical
---> 10 from pandas.core.groupby import Grouper
     11 from pandas.formats.format import set_eng_float_format
     12 from pandas.core.index import (Index, CategoricalIndex, Int64Index,

/usr/local/lib/python2.7/site-packages/pandas/core/groupby.py in <module>()
     16                               DataError, SpecificationError)
     17 from pandas.core.categorical import Categorical
---> 18 from pandas.core.frame import DataFrame
     19 from pandas.core.generic import NDFrame
     20 from pandas.core.index import (Index, MultiIndex, CategoricalIndex,

/usr/local/lib/python2.7/site-packages/pandas/core/frame.py in <module>()
     37                                    create_block_manager_from_arrays,
     38                                    create_block_manager_from_blocks)
---> 39 from pandas.core.series import Series
     40 from pandas.core.categorical import Categorical
     41 import pandas.computation.expressions as expressions

/usr/local/lib/python2.7/site-packages/pandas/core/series.py in <module>()
   2942 # Add plotting methods to Series
   2943 
-> 2944 import pandas.tools.plotting as _gfx  # noqa
   2945 
   2946 Series.plot = base.AccessorProperty(_gfx.SeriesPlotMethods,

/usr/local/lib/python2.7/site-packages/pandas/tools/plotting.py in <module>()
     25 from pandas.util.decorators import Appender
     26 try:  # mpl optional
---> 27     import pandas.tseries.converter as conv
     28     conv.register()  # needs to override so set_xlim works with str/number
     29 except ImportError:

/usr/local/lib/python2.7/site-packages/pandas/tseries/converter.py in <module>()
      5 from dateutil.relativedelta import relativedelta
      6 
----> 7 import matplotlib.units as units
      8 import matplotlib.dates as dates
      9 

/usr/local/lib/python2.7/site-packages/matplotlib/__init__.py in <module>()
   1129 
   1130 # this is the instance used by the matplotlib classes
-> 1131 rcParams = rc_params()
   1132 
   1133 if rcParams['examples.directory']:

/usr/local/lib/python2.7/site-packages/matplotlib/__init__.py in rc_params(fail_on_error)
    973         return ret
    974 
--> 975     return rc_params_from_file(fname, fail_on_error)
    976 
    977 

/usr/local/lib/python2.7/site-packages/matplotlib/__init__.py in rc_params_from_file(fname, fail_on_error, use_default_template)
   1098         parameters specified in the file. (Useful for updating dicts.)
   1099     """
-> 1100     config_from_file = _rc_params_in_file(fname, fail_on_error)
   1101 
   1102     if not use_default_template:

/usr/local/lib/python2.7/site-packages/matplotlib/__init__.py in _rc_params_in_file(fname, fail_on_error)
   1016     cnt = 0
   1017     rc_temp = {}
-> 1018     with _open_file_or_url(fname) as fd:
   1019         try:
   1020             for line in fd:

/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/contextlib.pyc in __enter__(self)
     15     def __enter__(self):
     16         try:
---> 17             return self.gen.next()
     18         except StopIteration:
     19             raise RuntimeError("generator didn't yield")

/usr/local/lib/python2.7/site-packages/matplotlib/__init__.py in _open_file_or_url(fname)
    998     else:
    999         fname = os.path.expanduser(fname)
-> 1000         encoding = locale.getdefaultlocale()[1]
   1001         if encoding is None:
   1002             encoding = "utf-8"

/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/locale.pyc in getdefaultlocale(envvars)
    541     else:
    542         localename = 'C'
--> 543     return _parse_localename(localename)
    544 
    545 

/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/locale.pyc in _parse_localename(localename)
    473     elif code == 'C':
    474         return None, None
--> 475     raise ValueError, 'unknown locale: %s' % localename
    476 
    477 def _build_localename(localetuple):

ValueError: unknown locale: UTF-8

**Comment by xinyuwuhenZZ** [comment]
I just followed the official instruction, and run it in other directory.

**Comment by xinyuwuhenZZ** [comment]
Maybe it is a little mess up. I can try it in pycharm.

**Comment by Waffleboy** [comment]
Well now you have a different error, try this.

https://coderwall.com/p/-k_93g/mac-os-x-valueerror-unknown-locale-utf-8-in-python

**Comment by xinyuwuhenZZ** [comment]
https://coderwall.com/p/-k_93g/mac-os-x-valueerror-unknown-locale-utf-8-in-python
That's the nub of the matter, thanks for your patience.

**Comment by javadba** [comment]
It's strange that disallowing a  script to be run in the TF directory were considered a non-bug.

**Comment by Serhiy-Shekhovtsov** [comment]
Had the same issue. Solved by running:
```
pip uninstall tensorflow
pip install tensorflow
```

**Comment by medoria07** [comment]
> You're running the script in the same directory as tensorflow. Move it out and you should be fine.

can you explain how u do that ???
