### ISSUE TITLE
Can not build tf from source - no such package '@grpc//': Error c loning repository

### ISSUE THREAD

**Issue by Samurais** [tensorflow/tensorflow#3218]
# description

Try to build&install tf from source. But it does not work with the guide.
I think it is because I am working in China and it has Great Fire Wall.

Built with commit id: 71f6bb336e5e11d6da2cedac6ba1c992ad9992bd
And OS: Mac OSX EI

```
$ bazel build -c opt --config=cuda //tensorflow/tools/pip_package:build_pip_package

WARNING: /private/var/tmp/_bazel_hain/13b9e8642207ccdb0c7f56a5c17d327c/external/protobuf/WORKSPACE:1: Workspace name in /priv
ate/var/tmp/_bazel_hain/13b9e8642207ccdb0c7f56a5c17d327c/external/protobuf/WORKSPACE (@__main__) does not match the name give
n in the repository's definition (@protobuf); this will cause a build error in future versions.
ERROR: /Users/hain/glory/ai/tensorflow/tensorflow/core/distributed_runtime/rpc/BUILD:87:1: no such package '@grpc//': Error c
loning repository: Unexpected end of file from server caused by Unexpected end of file from server caused by Unexpected end o
f file from server and referenced by '//tensorflow/core/distributed_runtime/rpc:grpc_channel'.
ERROR: Loading failed; build aborted.
INFO: Elapsed time: 639.082s
```

Other related issues -
https://github.com/tensorflow/tensorflow/issues/1387
https://github.com/tensorflow/tensorflow/issues/1413

@fayeshine 
@melody-rain

**Comment by Samurais** [comment]
Also, I am running Proxy in Global Mode. And I verified, git can clone repo from googlesource.

**Comment by Samurais** [comment]
I dont know why, but after running several times, the problem disappear.

**Comment by aselle** [comment]
Ok, closing for now since it seems like a network caching issue.

**Comment by JDavisCrowdOptic** [comment]
I'm seeing this same behavior three years later. When I run the command again, it finds grpc but then fails on another package. The build command succeeded the fourth time I ran it.

If this happens to a lot of people, it might be good idea to add a note to the build guide to let people know that if they get the error it's because of a network caching issue and to just run the command again until they no longer see the error.
