### ISSUE TITLE
Efficient band matrix multiplication

### ISSUE THREAD

**Issue by ekuznetsov139** [tensorflow/tensorflow#32188]
Tensorflow appears to lack an efficient way to do a multiplication by band matrix.

By this I mean calculating 

C[i,j] = sum_k A[i,j+k] B[i, k] 

For example, if B is

[ b00 b01 b02 .. b07]
[ b10 b11 b12 .. b17]
[ b20 b21 b22 .. b27]

this is equivalent to multiplying A by

[ b00  0   0 ...
[ b10 b01 0 ...
[ b20 b11 b02 ...
[ 0     b21 b12 ... ]
[ 0     0     b22 ... ]
...
[0   0 ...    b27]

This arises as part of the implementation of keras.layers.LocallyConnected1D(), which provides two possible implementations for it; both implementations are suboptimal. One creates a tensorflow op for every column, which means a lot of framework overhead, and the other expands B to the full form, which is inefficient and also seems to incur some overhead. (If B is 512x16, it should take one tensorflow op with 512x16 FMAs; implementation 1 would do 512 ops with 16 FMAs each;  implementation 2 would perform two ops, one with 512x529 float multiplications, and one with 512x529 FMAs less however much is saved internally by sparse_matmul().)

I tried to replace some dense layers with LocallyConnected1D() layers in @tensor2tensor transformer. It would not load at all with implementation 1 (it was still trying to build the graph after 10 minutes) and it ran significantly slower than with dense() (despite doing fewer FMAs) with implementation 2. 

The convolution would be easy to implement if one had direct access to tensor strides. (You simply set the second-to-last stride of A to stride[-2]+stride[-1] and do a regular matrix multiplication call.) And there is some internal support for it in the form of methods called Stream::ThenBlasGbmv() in stream_executor/stream.cc. But I don't see how to change strides from python, and ThenBlasGbmv() is never used in 1.x master.

**Comment by ekuznetsov139** [comment]
I did some profiling of implementation 2 and it looks like it is slower because it is partly done on the CPU, necessitating lots of CPU<->GPU traffic. The following snapshot

```
import tensorflow as tf
import numpy as np
from tensorflow.python.keras import backend as K
tf.enable_eager_execution()

with tf.device('/gpu:0'):
	input = tf.convert_to_tensor(np.random.random([1024,1024]),dtype=tf.float32)
	kernel = [[(np.random.random() if abs(x-y)<10 else 0) for x in range(1024)] for y in range(1024)]
	kernel = tf.convert_to_tensor(kernel, dtype=tf.float32)
	output = tf.sparse_matmul(input, kernel, b_is_sparse=True)
```

fails with
```
2019-09-03 14:41:49.641175: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1326] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 9654 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1080 Ti, pci bus id: 0000:04:00.0, compute capability: 6.1)
2019-09-03 14:41:49.643464: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1326] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:1 with 10468 MB memory) -> physical GPU (device: 1, name: GeForce GTX 1080 Ti, pci bus id: 0000:81:00.0, compute capability: 6.1)
Traceback (most recent call last):
  File "../sparse_perf.py", line 12, in <module>
    output = tf.sparse_matmul(input, kernel, b_is_sparse=True)
  File "/home/aidev/.local/lib/python2.7/site-packages/tensorflow/python/ops/gen_math_ops.py", line 9745, in sparse_mat_mul
    _six.raise_from(_core._status_to_exception(e.code, message), None)
  File "/home/aidev/.local/lib/python2.7/site-packages/six.py", line 737, in raise_from
    raise value
tensorflow.python.framework.errors_impl.NotFoundError: No registered 'SparseMatMul' OpKernel for GPU devices compatible with node {{node SparseMatMul}}
	.  Registered:  device='XLA_GPU'; Tb in [DT_FLOAT, DT_BFLOAT16]; Ta in [DT_FLOAT, DT_BFLOAT16]
  device='XLA_CPU'; Tb in [DT_FLOAT, DT_BFLOAT16]; Ta in [DT_FLOAT, DT_BFLOAT16]
  device='XLA_CPU_JIT'; Tb in [DT_FLOAT, DT_BFLOAT16]; Ta in [DT_FLOAT, DT_BFLOAT16]
  device='XLA_GPU_JIT'; Tb in [DT_FLOAT, DT_BFLOAT16]; Ta in [DT_FLOAT, DT_BFLOAT16]
  device='CPU'; Ta in [DT_FLOAT]; Tb in [DT_FLOAT]
  device='CPU'; Ta in [DT_BFLOAT16]; Tb in [DT_FLOAT]
  device='CPU'; Ta in [DT_FLOAT]; Tb in [DT_BFLOAT16]
  device='CPU'; Ta in [DT_BFLOAT16]; Tb in [DT_BFLOAT16]
 [Op:SparseMatMul]
```

**Comment by gadagashwini** [comment]
@ekuznetsov139, Which Tensorflow version are you using.
I could reproduce the issue on Colab with Tensorflow 1.14.0. Please see the [gist here](https://colab.sandbox.google.com/gist/gadagashwini/b8020ae709122ca33858f638b93065eb/untitled123.ipynb). Thanks!

**Comment by ekuznetsov139** [comment]
I am using master.

**Comment by ymodak** [comment]
Perhaps you can use soft device placement instead to solve the error message;
```python
import tensorflow as tf
import numpy as np
from tensorflow.python.keras import backend as K
#tf.enable_eager_execution()
with tf.device('/gpu:0'):
	input = tf.convert_to_tensor(np.random.random([1024,1024]),dtype=tf.float32)
	kernel = [[(np.random.random() if abs(x-y)<10 else 0) for x in range(1024)] for y in range(1024)]
	kernel = tf.convert_to_tensor(kernel, dtype=tf.float32)
	output = tf.sparse_matmul(input, kernel, b_is_sparse=True)
 

with tf.Session(config=tf.ConfigProto(allow_soft_placement=True)) as sess:
   sess.run(tf.global_variables_initializer())
   print(sess.run(output))
```
output:
```python
[[1.9552021 2.6956174 2.7000577 ... 5.2015905 4.306609  3.1939871]
 [2.8889682 3.0871844 2.7817092 ... 4.8683367 4.3100066 3.0557048]
 [2.7225637 3.5055962 3.1739452 ... 3.5228992 3.0882854 2.1134665]
 ...
 [2.9096322 3.844394  4.0538597 ... 3.5110736 2.2325637 2.1976418]
 [2.8388832 4.240377  3.5652244 ... 3.7165935 3.3939593 2.4490907]
 [2.362702  4.143541  3.2684267 ... 3.440366  3.225929  2.0782244]]
```

**Comment by ekuznetsov139** [comment]
Allow me to direct your attention at the title of the issue. It contains the word "efficient". Soft placement is not efficient.

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.
