### ISSUE TITLE
micro_speech preprocessing

### ISSUE THREAD

**Issue by piisku78** [tensorflow/tensorflow#32194]
**System information**
- TensorFlow version (you are using): 1.14
- Are you willing to contribute it (Yes/No): yes

tensorflow/examples/speech_commands project defines 3 different preprocessing modes. It is possible to train a ML model using all of them. 

Then there is an experimental project which will use the ML model from the 1st project on a micro-controller: tensorflow/lite/experimental/micro/examples/micro_speech/
This project ignores the preprocessing modes from the first project. By looking at the code in the micro_speech project it assumes the preprocessing mode always to be 'micro'.  The preprocessing includes some scaling operations and it looks like those operations are done inside 'micro_features_generator.cc' 
tensorflow/lite/experimental/micro/examples/micro_speech/micro_features/micro_features_generator.cc
There is an comment related to this: 'These scaling values are derived from those used in input_data.py in the training pipeline.'

The problems I see at the moment:
1 .It is very unclear how those magic scaling numbers in micro_features_generator.cc are derived from training pipeline. What if my pipeline parameters are not exactly the same as they were when those magic numbers where defined.   
2. It is impossible to use another preprocessing mode as 'micro' because it is not implemented on micro_speech project.
3. There is suspicious operation where pointer is always moved 160 steps forward. Why hardcoded 160? From where does this number come and why buffer pointer is always moved 160.  'frontend_input = input + 160; ' 
4. Documentation of the all preprocessing modes is lacking.

So at the moment if somebody use 'average' or 'mfcc' preprocessing mode then the input to the model is not correctly prepared in micro_speech project and it will fail to detect sounds. One should to implement all preprocessing modes in micro_features_generator.cc.

I am also not sure if 'micro' works always correctly because there is that hardcoded 160 which is obviously depend on some ML model input parameters.

**Comment by piisku78** [comment]
@petewarden Could you please give your input to this issue.

I find it weird that ML model has a good accuracy after training but it performs badly on target micro controller HW. Preprocessing might be the reason for that. If the input to the model is not exactly similar preprocessed during training and inferencing then the model wont work good on target HW.

**Comment by piisku78** [comment]
3. Pointer is always moved 160 is maybe wrong. It should be 320 because stride in the example is defined as 20ms and sampling rate 16000Hz. So if we want to go forward always 20ms then it means 320 samples.

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.

**Comment by wenwu-glagle** [comment]
I have the same confusion, and after read the source code. I got the reason for "frontend_input = input + 160; ".

I think this is because we reuse 10 ms history audio data, it means 160 sample when sample rate is 16000.

At the first time WindowProcessSamples() will read the whole 480 samples (30ms),  and 320 samples following (20 ms), just the new samples. Log like below:

```
num_samples_read 480, audio_samples_size 512, output_slice_size 40  

num_samples_read 320, audio_samples_size 512, output_slice_size 40  

num_samples_read 320, audio_samples_size 512, output_slice_size 40  

num_samples_read 320, audio_samples_size 512, output_slice_size 40  

num_samples_read 320, audio_samples_size 512, output_slice_size 40  
```
If see the source code of WindowProcessSamples(), we can konw that windows state keeps the history 160 samples in itself buffer.
```
 memmove(state->input, state->input + state->step,
          sizeof(*state->input) * (state->size - state->step));
  state->input_used -= state->step;
```
So the 'frontend_input = input + 160;' is correct.

I write this if it could help anyone.
