### ISSUE TITLE
Allow adding and deleting graph nodes and edges in Tensorboard

### ISSUE THREAD

**Issue by pirate** [tensorflow/tensorflow#322]
Generating the graph from Python is not an expensive process.  It would greatly lower the barrier to entry if new users & data scientists who are more comfortable with GUIs could modify graph parameters directly from Tensorboard.

If I understand correctly (per a short tutorial from @rsepassi) you currently cant delete nodes from the graph without regenerating it, however regenerating the graph takes seconds, so it would be nice to allow creation of nodes and edges via the GUI (like Cafe).

I know this is a really high-level feature request, and probably requires a fair amount of work.  Feel free to close it if this would be better discussed on a mailing list instead of Github Issues.

**Comment by srjoglekar246** [comment]
Creation won't be a problem atleast on the library's end I guess. As far as deletion is concerned, I have tried hacking around to see if its possible. Technically, it may be simple enough to delete all references to the node in question by deleting it from all graph collections and the Graph instance's inner dictionaries (which are used for methods like 'get_operation_by_name'). However, for complicated structures, you would first have to check if any other Ops depend on the node in question. If yes, deleting it would cause major issues. But I agree its a feature worth having (but with proper checking for dependencies ofcourse).

**Comment by girving** [comment]
I'll leave it open for tracking purposes, but if someone wants to tackle this it's probably better to start off as a separate repo.  I'm not sure it makes sense to integrate it into TensorBoard at first, but @danmane may have further thoughts.

If someone does give this a try, please comment here!

**Comment by danmane** [comment]
Yeah, we've talked about this internally - it would be really cool to have a GUI for modifying the graph, but it seems like a lot of work and I suspect it would still not be powerful enough for most use cases. For it to be really useful it would need to be embedded in a broader gui-based execution system for TensorFlow, which also sounds very challenging to get right.

An easier path to fast-feedback graph creation would be to embed the graph visualizer into iPython notebook - you'd still be modifying the graph with code, but with a tighter feedback cycle.

Of course, if someone wants to try building the GUI graph builder, they're welcome to :) and I'd love to see what comes of it.

**Comment by pirate** [comment]
This seems much higher level than what I was thinking of, but still worth taking inspiration from [Tensorflow Playground](http://playground.tensorflow.org/#activation=tanh&batchSize=10&dataset=circle&regDataset=reg-plane&learningRate=0.03&regularizationRate=0&noise=0&networkShape=8,2&seed=0.82019&showTestData=true&discretize=false&percTrainData=50&x=true&y=true&xTimesY=true&xSquared=true&ySquared=true&cosX=false&sinX=true&cosY=false&sinY=true&collectStats=false&problem=classification).

**Comment by kuza55** [comment]
Even if there wasn't a GUI for this, having some utility functions for making modified copies of graphs would be useful.

I'm currently trying to use a model that was retrained from the inception model using the image_retraining example and I'm running into issues since there is a totally unnecessary DecodeJpeg Op in the model that isn't supported on android atm (#2570).

If no-one else volunteers to make these, I might see if I can hack some changes to the copying code, but I'm almost definitely the wrong person to be doing this.

**Comment by chihuahua** [comment]
We do not plan to make the graph explorer editable unless compelling reasons arise. One can run TensorFlow in colab and get quick feedback on how the graph looks like.
