### ISSUE TITLE
TensorFlow Lite softmax error if dims >4  (num_dims >= 1 && num_dims <= 4)

### ISSUE THREAD

**Issue by garspace** [tensorflow/tensorflow#32209]
**System information**
- OS Platform and Distribution (Linux Ubuntu 16.04):
- TensorFlow installed from ( binary):
- TensorFlow version (1.13.1):
- Python version (3.7)

my model graph contain reshape op as follows:
self. pixel_link_logits = tf.reshape(self.pixel_link_logits,[shape[0], shape[1], shape[2], 16, 2])
self.pixel_link_scores = tf.nn.softmax(self.pixel_link_logits)

**this is my  tflite_convert code**

```
  6 graph_def_file = "./model_v4.pb"
  7 input_arrays = ["evaluation_768x768/Placeholder"]
  8 output_arrays = ["evaluation_768x768/Squeeze","evaluation_768x768/Squeeze_1"]
  9 converter = tf.lite.TFLiteConverter.from_frozen_graph(graph_def_file, input_arrays, output_arrays)
 10
 11 converter.post_training_quantize=True
 12
 13 tflite_model = converter.convert()
 14 with open("converted_model.tflite", "wb") as f:
 15     f.write(tflite_model)
 16 interpreter = tf.lite.Interpreter(model_path="converted_model.tflite")
 17 interpreter.allocate_tensors()
 18 input_details = interpreter.get_input_details()
 19 output_details = interpreter.get_output_details()
 20 input_shape = input_details[0]['shape']
 21
 22 input_data = np.array(np.random.random_sample(input_shape), dtype=np.float32)
 23 interpreter.set_tensor(input_details[0]['index'], input_data)
 24 interpreter.invoke()
 25 output_data = interpreter.get_tensor(output_details[0]['index'])
 26 print(output_data)
```

I counter the error on softmax about num_dims >= 1 && num_dims <= 4, how can I resolver it @ry ,
**this is the error  logs**

when I interpreter the tflite model, counter the dimentions error, the infor:
Traceback (most recent call last):
  File "interpreter.py", line 17, in <module>
    interpreter.allocate_tensors()
  File "/home/xxx/miniconda3/lib/python3.6/site-packages/tensorflow/lite/python/interpreter.py", line 73, in allocate_tensors
    return self._interpreter.AllocateTensors()
  File "/home/dengjie/miniconda3/lib/python3.6/site-packages/tensorflow/lite/python/interpreter_wrapper/tensorflow_wrap_interpreter_wrapper.py", line 106, in AllocateTensors
    return _tensorflow_wrap_interpreter_wrapper.InterpreterWrapper_AllocateTensors(self)
RuntimeError: tensorflow/lite/kernels/activations.cc:216 num_dims >= 1 && num_dims <= 4 was not true.Node number 146 (SOFTMAX) failed to prepare

I found the tensorflow source code about softmax  only surpport 4 dimensions:
the code: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/kernels/activations.cc
![image](https://user-images.githubusercontent.com/12806623/64256590-5ca58800-cf56-11e9-8541-15446005d58a.png)
how can i solve it， who help me？

**Comment by liyunlu0618** [comment]
This is a known limitation for softmax().
