### ISSUE TITLE
[tflite] how to build tflite project to library for ios  bazel, swift, pod, make?

### ISSUE THREAD

**Issue by laohur** [tensorflow/tensorflow#32200]
I want to build tflite project library to shared with other projects on android & ios.
It is easy to build android project library via bazel (cc_binary) and test it via adb. 
How about ios, use bazel, swift, pod, make,c++/objectc? how to test it? is there any example?

**Comment by gadagashwini** [comment]
@laohur, Did you get a chance to look [Tensorflow official website](https://www.tensorflow.org/lite/guide/build_ios) to build Tf lite on iOS. Thanks

**Comment by laohur** [comment]
> official

yeah. and how to build a library including tflite?

**Comment by gadagashwini** [comment]
@laohur, Can you please let us know if you are happy to close if no issue persists. Thanks!
