### ISSUE TITLE
KeyError: u'BatchMatMulV2'

### ISSUE THREAD

**Issue by taiftahmid** [tensorflow/tensorflow#32205]
Trying to generate a .pb file from .meta file but encountered this error when running in tensorflow 1.13.1. 
Works after changing tensorflow version to 1.14.0
But I need to generate .pb file using tensorflow 1.13.1 or below versions. 

Here's the code: 

```
import tensorflow as tf

meta_path = 'fns.ckpt.meta' # Your .meta file
output_node_names = ['add_37']    # Output nodes

with tf.Session() as sess:

    # Restore the graph
    saver = tf.train.import_meta_graph(meta_path)

    # Load weights
    saver.restore(sess,"checkpoints/fns.ckpt")

    # Freeze the graph
    frozen_graph_def = tf.graph_util.convert_variables_to_constants(
        sess,
        sess.graph_def,
        output_node_names)

    # Save the frozen graph
    with open('output_graph.pb', 'wb') as f:
      f.write(frozen_graph_def.SerializeToString())
```

**Comment by jvishnuvardhan** [comment]
@taiftahmid I think you can check the source code of 1.13.1 and 1.14 and find the file that is helping in generating a .pb file from .meta file. Once you find that file, then update your forked version of 1.13.1. Thanks!

Please close the issue.
This is not Build/Installation or Bug/Performance issue. Please post this kind of support questions at [Stackoverflow](https://stackoverflow.com/questions/tagged/tensorflow). There is a big community to support and learn from your questions. GitHub is mainly for addressing bugs in installation and performance. Thanks!
