### ISSUE TITLE
Bug in the Tensorflow .pb to .tflite conversion using TFLiteConverter

### ISSUE THREAD

**Issue by akssieg** [tensorflow/tensorflow#32201]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 16.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: No
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 1.13 (CPU version)
- Python version: 3.6.9

**Describe the current behavior**
TFLiteConverter converts the first convolutional layer of tensorflow model into depthwise convolutional layer if the input to the model has single channel (In my case grey scale images with channel =1).

**Describe the expected behavior**

Convolutional layer in the tensorflow model should remain the same even after TFLiteConverter.

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

link to tensorflow model: https://drive.google.com/open?id=14R84txljdYdTIZRmHAD1Rkfl-_n9fCGb

link to the generated tflite model: https://drive.google.com/open?id=1WlmWhJYjxfLIjwZcUJ9vLq8ZB5oBmaUD

Code used to generate tflite file from tensorflow model:

```
import tensorflow as tf
graph_def_file = "single_layer.pb"
input_arrays =['s']
output_arrays =['conv/Relu']
output_file = "single_layer.tflite"

converter = tf.lite.TFLiteConverter.from_frozen_graph(graph_def_file, input_arrays, output_arrays)
tflite_model = converter.convert()
open(output_file, "wb").write(tflite_model)

```

I used netron to visualise the .pb and .tflite graph, link: https://github.com/lutzroeder/netron

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

Tensorflow graph:
![1](https://user-images.githubusercontent.com/32209750/64239177-0e659a00-cf00-11e9-9d99-67809d639104.PNG)

Tflite graph after TFLiteConverter:
![image](https://user-images.githubusercontent.com/32209750/64239288-45d44680-cf00-11e9-9fb4-18eddf063b4f.png)

**Comment by akssieg** [comment]
@ymodak

**Comment by blairhan** [comment]
seems the bug comes from here: https://github.com/tensorflow/tensorflow/blob/04256c89d8783c5cfd7e550f9512e9478beb6454/tensorflow/lite/toco/graph_transformations/convert_pure_conv_to_depthwise.cc#L49

**Comment by haozha111** [comment]
Hi,

The convert to depthwiseconv is by design. I'm curious if this causes an issue for you (correctness/performance regression)?

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.
