### ISSUE TITLE
tf.signal.fft2d speed is slow and unstable in RTX2080Ti

### ISSUE THREAD

**Issue by YichengWu** [tensorflow/tensorflow#32218]
**System information**
- OS Platform: Linux Ubuntu 18.04 (server)
- TensorFlow installed from: docker tensorflow/tensorflow  1.14.0-gpu-py3-jupyter 
- TensorFlow version: 1.14.0
- Python version: 3.6.8
- CUDA:  v10.0
- GPU model: RTX 2080Ti 

**Describe the current behavior**
The speed of fft2d operation `tf.signal.fft2d` is very unstable at different iterations. Here is an example output of time every 100 iterations (code is shown below):
```
2019-09-04 19:03:57.731947
2019-09-04 19:04:33.715335
2019-09-04 19:05:10.976109
2019-09-04 19:05:44.012072
2019-09-04 19:06:15.616308
2019-09-04 19:07:14.961716
2019-09-04 19:08:12.324199
2019-09-04 19:09:11.560423
2019-09-04 19:10:08.877960
2019-09-04 19:11:08.102977
```
During the training, there is no other programs running.

Bur when running the same code in my local machine (GTX 1080Ti) with the same TensorFlow docker image. The speed is fast and stable.
```
2019-09-04 14:12:00.387114
2019-09-04 14:12:07.363174
2019-09-04 14:12:14.355784
2019-09-04 14:12:21.384377
2019-09-04 14:12:28.378524
```

**Describe the expected behavior**
The speed should be always very fast (about 7s/100iterations).

**Code to reproduce the issue**
```
import os
import datetime
import tensorflow as tf
import numpy as np

os.environ["CUDA_DEVICE_ORDER"] = "PCI_BUS_ID"
os.environ["CUDA_VISIBLE_DEVICES"] = "1"

def main(_):
    dp_train = tf.placeholder(tf.float32, shape=(41, 300, 300, 1))
    dp = tf.complex(dp_train, 0.0)
    dp_fft = tf.abs(tf.signal.fft2d(dp))
    W = tf.get_variable('W_conv', [1, 1, 1, 1])  # not important, just want to make the training process to run.
    cost_train = tf.reduce_mean(tf.nn.conv2d(dp_fft, W, strides=[1, 1, 1, 1], padding='SAME'))

    opt = tf.train.AdamOptimizer(1e-4)
    update_ops = tf.get_collection(tf.GraphKeys.UPDATE_OPS)
    with tf.control_dependencies(update_ops):
        train_op = opt.minimize(cost_train)  # var_list=vars_digital

    with tf.Session() as sess:
        sess.run(tf.global_variables_initializer())
        sess.run(tf.local_variables_initializer())
        coord = tf.train.Coordinator()
        threads = tf.train.start_queue_runners(sess=sess, coord=coord)

        for i in range(0, 5000):
            data = np.random.rand(41,300,300,1)
            sess.run(train_op, feed_dict={dp_train:data})
            if i % 100 ==0:
                old_time = datetime.datetime.now()
                print(old_time)

        coord.request_stop()
        coord.join(threads)

if __name__ == '__main__':
    tf.app.run()

```

**Comment by gadagashwini** [comment]
I was able to reproduce the issue with Tensorflow 1.14.0. Please see the gist [here](https://colab.sandbox.google.com/gist/gadagashwini/63fded2fb0049ecf0e1a8de505856559/untitled125.ipynb). Thanks

**Comment by rryan** [comment]
Thanks for the report! Note that in your example, `tf.signal.fft2d` operates over the inner-most 2 dimensions (`[300, 1]`) so this is likely even slower than you measure.

**Comment by rryan** [comment]
> I was able to reproduce the issue with Tensorflow 1.14.0. Please see the gist [here](https://colab.sandbox.google.com/gist/gadagashwini/63fded2fb0049ecf0e1a8de505856559/untitled125.ipynb). Thanks

Thanks for the Colab! The CUDA device filter 
```python
os.environ["CUDA_DEVICE_ORDER"] = "PCI_BUS_ID"
os.environ["CUDA_VISIBLE_DEVICES"] = "1"
```
is causing TensorFlow to ignore its GPU, running the FFT on CPU:

```python
tf.config.experimental.get_visible_devices()
> [PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU')]
```

When I remove the device filters I get consistent timing:
```
2019-09-20 06:24:40.498802
2019-09-20 06:24:45.739194
2019-09-20 06:24:51.046707
2019-09-20 06:24:56.424465
2019-09-20 06:25:01.734107
2019-09-20 06:25:07.108748
2019-09-20 06:25:12.504023
2019-09-20 06:25:17.908167
2019-09-20 06:25:23.324278
2019-09-20 06:25:28.803539
2019-09-20 06:25:34.155487
2019-09-20 06:25:39.518539
2019-09-20 06:25:44.901134
2019-09-20 06:25:50.260070
2019-09-20 06:25:55.723608
2019-09-20 06:26:01.048212
```

@YichengWu are you certain your example code is actually running on GPU?

**Comment by YichengWu** [comment]
@rryan , thank you so much for your help! Yes, my code is running on GPU. And the speed is varying from day to day even there is nothing else running on the cluster, sometimes 60s/100iter, sometimes 7s/100iter.

**Comment by rryan** [comment]
> @rryan , thank you so much for your help! Yes, my code is running on GPU. And the speed is varying from day to day even there is nothing else running on the cluster, sometimes 60s/100iter, sometimes 7s/100iter.

Gotcha, what happens when you run this on the machine with the RTX2080Ti?

```
import tensorflow as tf
import os
os.environ["CUDA_DEVICE_ORDER"] = "PCI_BUS_ID"
os.environ["CUDA_VISIBLE_DEVICES"] = "1"
tf.config.experimental.get_visible_devices()
```

**Comment by rryan** [comment]
If this is a cluster, is it possible that your job is switching between multiple machines -- some of which have a PCI_BUS_ID 1 for the RTX2080Ti, some of which don't?

**Comment by rryan** [comment]
One way to make sure in the code is to add this after you set CUDA_VISIBLE_DEVICES:

```python
# Check there is a GPU available.
assert len(tf.config.experimental.get_visible_devices("GPU")) > 0
```

and then later in your code:

```python
with tf.device('/gpu:0'):
  dp_fft = tf.abs(tf.signal.fft2d(dp))
```
That way, TensorFlow will throw an error if it can't put the FFT on a GPU.

We definitely could have a bug leading to unstable performance, but I just want to sanity check and make sure that the FFTs are definitely running on the GPU in your cluster environment.

**Comment by YichengWu** [comment]
Hey RJ, I just checked my code and the code is running on the GPU. Just want to let you know that there were several times that the speed changed a lot for one running (without stopping the code)

**Comment by rryan** [comment]
Thanks for double-checking and the additional info (the speed changes within the same training run). I don't know what could be causing this.

When you hit a period of slowness, what happens if you kill training and re-start? Does it return to fast execution immediately or does the slowness persist?

**Comment by YichengWu** [comment]
If I restart, the code is still slow. After a random period of time, the code becomes fast.

**Comment by YichengWu** [comment]
This is what I saw just now, the speed changed from 40s/100iter to 6s/100iter.
2019-09-30 01:50:45.808665
2019-09-30 01:51:25.043709
2019-09-30 01:52:04.264984
2019-09-30 01:52:44.757427
2019-09-30 01:53:25.178119
2019-09-30 01:54:04.592331
2019-09-30 01:54:44.897020
2019-09-30 01:55:24.013882
2019-09-30 01:56:03.740308
2019-09-30 01:56:43.617144
2019-09-30 01:57:23.751177
2019-09-30 01:58:04.228672
2019-09-30 01:58:45.134902
2019-09-30 01:59:24.387479
2019-09-30 01:59:57.731981
2019-09-30 02:00:03.707638
2019-09-30 02:00:09.638930
2019-09-30 02:00:15.949742
2019-09-30 02:00:22.020293
2019-09-30 02:00:28.099341

**Comment by rryan** [comment]
Could you please post the output of `nvidia-smi` when the issue is occurring and when the issue not occurring? I'd like to see the difference between the two.

**Comment by YichengWu** [comment]
The  GPU-Util is very low when the code is slow. Output from `nvidia-smi`:
Here is when the code is slow
```
|   4  GeForce RTX 208...  Off  | 00000000:88:00.0 Off |                  N/A |
| 30%   40C    P2    54W / 250W |  10903MiB / 11019MiB |      0%      Default |

|    4      4009      C   python                                     10893MiB |
```

Here is when the code is fast
```
|   4  GeForce RTX 208...  Off  | 00000000:3E:00.0 Off |                  N/A |
| 31%   43C    P2    74W / 250W |  10942MiB / 11019MiB |      6%      Default |

|    4     19222      C   python                                     10151MiB |
```

**Comment by rryan** [comment]
Thanks @YichengWu! 

Could you please instrument your code to take TensorFlow traces and save them? 

You can use [tf.train.ProfilerHook](https://www.tensorflow.org/versions/r1.14/api_docs/python/tf/train/ProfilerHook), which would require you to update your code to use `tf.train.MonitoredSession`, or you could capture a trace manually using [this approach](https://gist.githubusercontent.com/ikhlestov/80ee9abee427b13bf9d9c5103ebb2e6e/raw/c744f959769f7bde374856565922132a86991dee/01_simple_example.py
).

**Comment by rryan** [comment]
Ideally, please post a JSON trace file for both the slow behavior and fast behavior.

**Comment by YichengWu** [comment]
The files are attached.
[json_files.zip](https://github.com/tensorflow/tensorflow/files/3674021/json_files.zip)

**Comment by rryan** [comment]
Thanks! What the trace shows is that the actual kernel execute time (on `/device:GPU:0/stream:all`) is comparable between the two:

Fast (0.137 ms):
<img width="1190" alt="Screen Shot 2019-09-30 at 11 26 13 PM" src="https://user-images.githubusercontent.com/26527/65939139-de63c680-e3d9-11e9-8536-a2a1f9b18e37.png">

Slow (0.143 ms):
<img width="1315" alt="Screen Shot 2019-09-30 at 11 26 44 PM" src="https://user-images.githubusercontent.com/26527/65939144-e0c62080-e3d9-11e9-84ba-32a58419989c.png">

Yet the FFT2D op execution itself (`/job:localhost/replica:0/task:0/device:GPU:0` [1]) takes a lot longer in the slow profile (346 ms vs. 2552 ms). 

So this suggests that in periods of slowness, something about the CPU side of the FFT op is taking a lot longer. 

The Conv2DBackpropFilter op has the same discrepancy in timing -- in the fast trace it takes 2002 ms, and in the slow trace it takes 24072 ms. If you look at the actual Conv2DBackpropFilter ops in `/device:GPU:0/stream:all`, they are the same speed between the two traces.

This suggests that the issue isn't related to FFT ops specifically, and it's probably not related to the GPU either since the ops appear to be executing efficiently on device.

What's the CPU load of the machine during periods of slowness? How about RAM usage? Does the machine have virtual memory enabled and is it possible it's swapping? Just trying to think of things that could change over time that could cause the CPU to run a lot more slowly, or for TensorFlow to have reduced access to cores on the machine (higher priority processes?).

[1] This is a "logical" GPU device, which represents the execution of the FFT from start to finish -- including CPU-based logic to prepare the GPU for the FFT, then the FFT kernel itself, and any cleanup that must be done. The `stream` GPU devices represent actual time on the device.

**Comment by rryan** [comment]
@YichengWu we are discussing this internally and don't really know what could be causing it. We may have seen similar issues on V100/P100 GPUs -- in those cases, profiling suggests all the time is spent within the CUDA API (in the request to launch the kernel).

One hypothesis is that due to an architecture mismatch between the bundled kernels and your GPU, CUDA may be JIT'ing a specialized kernel on the fly. There is a cache for JIT'ed kernels, and we are wondering if something is causing CUDA to need to regularly re-compile the kernels needed for your program.

There are some configuration options for the JIT and cache here:
https://devblogs.nvidia.com/cuda-pro-tip-understand-fat-binaries-jit-caching/

In particular, I'm wondering what happens when you set `CUDA_CACHE_DISABLE=1` and `CUDA_FORCE_PTX_JIT=1`. If that reproduces the slow behavior then we can probably conclude that something is causing your CUDA kernel cache to churn.

**Comment by YichengWu** [comment]
@rryan I added the code as you suggested (shown below). But the speed is the same with/without the following code (both are slow or fast):
```
CUDA_CACHE_DISABLE=1
CUDA_FORCE_PTX_JIT=1
```
Please let me know if there is anything wrong in my implementation.

The completed code is here:
```
import os
import datetime
import tensorflow as tf
import numpy as np
from tensorflow.python.client import timeline


os.environ["CUDA_DEVICE_ORDER"] = "PCI_BUS_ID"
os.environ["CUDA_VISIBLE_DEVICES"] = "7"
CUDA_CACHE_DISABLE=1
CUDA_FORCE_PTX_JIT=1

# Check there is a GPU available.
assert tf.config.experimental.get_visible_devices("GPU")

def main(_):
    dp_train = tf.placeholder(tf.float32, shape=(41, 300, 300, 1))
    dp = tf.complex(dp_train, 0.0)
    with tf.device('/gpu:0'):
      dp_fft = tf.abs(tf.signal.fft2d(dp))
    W = tf.get_variable('W_conv', [1, 1, 1, 1])  # not important, just want to make the training process to run.
    cost_train = tf.reduce_mean(tf.nn.conv2d(dp_fft, W, strides=[1, 1, 1, 1], padding='SAME'))

    opt = tf.train.AdamOptimizer(1e-4)
    update_ops = tf.get_collection(tf.GraphKeys.UPDATE_OPS)
    with tf.control_dependencies(update_ops):
        train_op = opt.minimize(cost_train)  # var_list=vars_digital

    with tf.Session() as sess:
        options = tf.RunOptions(trace_level=tf.RunOptions.FULL_TRACE)
        run_metadata = tf.RunMetadata()
        sess.run(tf.global_variables_initializer())
        sess.run(tf.local_variables_initializer())
        coord = tf.train.Coordinator()
        threads = tf.train.start_queue_runners(sess=sess, coord=coord)
        
        for i in range(0, 1000):
            data = np.random.rand(41,300,300,1)
            sess.run(train_op, feed_dict={dp_train:data})

            if i % 100 ==0:
                old_time = datetime.datetime.now()
                print(old_time)
                


        coord.request_stop()
        coord.join(threads)

if __name__ == '__main__':
    tf.app.run()
```

**Comment by rryan** [comment]
> os.environ["CUDA_DEVICE_ORDER"] = "PCI_BUS_ID"
> os.environ["CUDA_VISIBLE_DEVICES"] = "7"
> CUDA_CACHE_DISABLE=1
> CUDA_FORCE_PTX_JIT=1

Thanks! It would need to be set as an environment variable like CUDA_DEVICE_ORDER:

```python
os.environ["CUDA_CACHE_DISABLE"] = "1"
os.environ["CUDA_FORCE_PTX_JIT"] = "1"
```

**Comment by YichengWu** [comment]
I did one test several days ago. First I didn't have these two lines and the code ran fast (7s/100iter). After adding these two lines, the code loading process was really slow (took about 30mins) and the running process was slow (65s/100iter). I am not sure if it proves that cache is the reason because the code was slow (60s/iter, not the loading part) after I commented out these two lines. I can try more tests but the code is always slow for several days.

```
2019-10-17 18:28:39.065277: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcufft.so.10.0

2019-10-17 18:30:39.189080: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcudnn.so.7

2019-10-17 18:58:12.048244
2019-10-17 18:59:17.135890
2019-10-17 19:00:21.047744
2019-10-17 19:01:26.743846
```

**Comment by jjqtony** [comment]
I have the same problem when using 3080 and tf2.5

**Comment by vsimkus** [comment]
I have a similar issue here with TF2.5 and `tf.signal.rfft2d` and `tf.signal.irfft2d` methods, on one GPU (RTX 3090) the CUDA kernel launch times are minimal (about 0.05x of the device compute), but on another machine's GPU (Titan X) the CUDA kernel launch times are terrible (about 2-7x the device compute). The kernel launch times for other operations are also higher on the slow machine (0.2x (slow) vs 0.05x (fast-machine) of the device compute) but it is particularly bad for the `fft` ops. 

I suspect that it's a similar issue as mentioned in https://github.com/tensorflow/tensorflow/issues/32218#issuecomment-542520818. 

Unfortunately, I have very limited access to the packages on the slow machine, but I will try to see if different TF versions make a change.

**Comment by avirajBevli** [comment]
I profile tf.signal.fft2d() operation in nsight-systems. I observe that when this operation is to be launched, there is a period of inactivity in CUDA API section before the kernel is launched by the CUDA API. Seems like the CPU activity is also zero during this time. Once the kernel is launched by the CUDA API, the kernel begins execution on the GPU almost immediately.
Any ideas how to solve this?   

PS:
From the CUDA API trace, it seems like tf.signal.fft operations (eg: tf.signal.fftshift(), tf.signal.ifftshift(), tf.signal.fft2d(), tf.signal.ifft2d()) all launch multiple cuda API calls to call the kernel. Don't know if this is relevant to the discussion or not
for example: fft shift operation issues 3 cudaMemcpyAsync, followed by a call to kernel followed by 3 cudaStreamAddCallback. fft2d operation issues cudaFree -> 4 cudaGetFuncBySymbol -> cudaStreamIsCapturing...
Why are these multiple cuda api calls being called for each tf.signal.fft<> operation?
