### ISSUE TITLE
 Error installing tensorflow centos 7

### ISSUE THREAD

**Issue by dieinimymaganha** [tensorflow/tensorflow#32214]
hi guys, i'm trying to install tensorflow on centos 7, i have python 3.7.4 installed.

When trying to give the pip looks like the message:
Could not find a version that satisfies the requirement tensorflow (from versions:) No matching distribution found for tensorflow

Could you please help me?

**Comment by mihaimaruseac** [comment]
What version of pip?

**Comment by dieinimymaganha** [comment]
Version 19.2.3

**Comment by mihaimaruseac** [comment]
Can you post the full log of `python -m pip install --upgrade pip && python -m pip install --upgrade tensorflow`?

**Comment by dieinimymaganha** [comment]
![MJ9oUp1SML](https://user-images.githubusercontent.com/38332691/64284614-5ef4eb80-cf30-11e9-979f-e793b45a8d53.png)

**Comment by mihaimaruseac** [comment]
Add in a `-v` on the second `pip install` so we get more detailed logs.

Most likely this is an issue with your environment, not a bug in TF.

**Comment by mihaimaruseac** [comment]
Also, try `pip install --upgrade setuptools`

**Comment by dieinimymaganha** [comment]
I did the procedure, and gave this message:

![UPoJ9ARnws](https://user-images.githubusercontent.com/38332691/64287141-50f59980-cf35-11e9-9983-8ac523668ae3.png)

I also upgraded setuptools, then tried again and presented the same message

I am suspecting it to be some limitation for the centos 7 version I am using.

The version I use is Centos Linux release 7.4.1708 (AltArch)

**Comment by dieinimymaganha** [comment]
On windows and Ubuntu it worked normally

**Comment by mihaimaruseac** [comment]
Probably the c++ compiler or some standard library.

Please try with `-vvv`.

Also, it's harder to read from the images, can you copy-paste instead?

**Comment by dieinimymaganha** [comment]
Hello,

I will try to perform this procedure.

I am updating the centos and it is a bit slow.

**Comment by dieinimymaganha** [comment]
I had to do it all over again.

I had to attach the error log as it exceeded the character limit
[error.txt](https://github.com/tensorflow/tensorflow/files/3580706/error.txt)

**Comment by dieinimymaganha** [comment]
Hello, can anyone help me?

**Comment by mihaimaruseac** [comment]
Can you also post the output of `pip debug --verbose`? Sorry for the delay in answering

**Comment by dieinimymaganha** [comment]
(tensorflowteste01) [root@localhost ~]# pip debug --verbose
WARNING: This command is only meant for debugging. Do not use this with automation for parsing and getting these details, since the output and options of this command may change without notice.
pip version: pip 19.2.3 from /root/.pyenv/versions/3.7.4/envs/tensorflowteste01/lib/python3.7/site-packages/pip (python 3.7)
sys.version: 3.7.4 (default, Sep  5 2019, 14:57:56) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
sys.executable: /root/.pyenv/versions/3.7.4/envs/tensorflowteste01/bin/python3.7
sys.getdefaultencoding: utf-8
sys.getfilesystemencoding: utf-8
locale.getpreferredencoding: UTF-8
sys.platform: linux
sys.implementation:
  name: cpython
Compatible tags: 38
  cp37-cp37m-manylinux2010_i686
  cp37-cp37m-manylinux1_i686
  cp37-cp37m-linux_i686
  cp37-abi3-manylinux2010_i686
  cp37-abi3-manylinux1_i686
  cp37-abi3-linux_i686
  cp37-none-manylinux2010_i686
  cp37-none-manylinux1_i686
  cp37-none-linux_i686
  cp36-abi3-manylinux2010_i686
  cp36-abi3-manylinux1_i686
  cp36-abi3-linux_i686
  cp35-abi3-manylinux2010_i686
  cp35-abi3-manylinux1_i686
  cp35-abi3-linux_i686
  cp34-abi3-manylinux2010_i686
  cp34-abi3-manylinux1_i686
  cp34-abi3-linux_i686
  cp33-abi3-manylinux2010_i686
  cp33-abi3-manylinux1_i686
  cp33-abi3-linux_i686
  cp32-abi3-manylinux2010_i686
  cp32-abi3-manylinux1_i686
  cp32-abi3-linux_i686
  py3-none-manylinux2010_i686
  py3-none-manylinux1_i686
  py3-none-linux_i686
  cp37-none-any
  cp3-none-any
  py37-none-any
  py3-none-any
  py36-none-any
  py35-none-any
  py34-none-any
  py33-none-any
  py32-none-any
  py31-none-any
  py30-none-any

**Comment by mihaimaruseac** [comment]
None of those tags show up on the [released wheels page](https://pypi.org/project/tensorflow/2.0.0rc0/). Is your CPU or Python on 32 bits? Then, this is a case of #32315, we don't have support for 32 bits at the moment.

**Comment by dieinimymaganha** [comment]
I will change my system to 64 bits and see if it will work.

Thanks for your help, I will leave it open even if I encounter any difficulty.

**Comment by mihaimaruseac** [comment]
Any updates? Is this issue fixed?

**Comment by dieinimymaganha** [comment]
I am waiting for the infrastructure to change to 64 bits.

For now I will mark as solved the problem, and anything I mention again.

Thanks a lot for the help. Have a great day

**Comment by reliefs** [comment]
https://github.com/tensorflow/tensorflow/issues/32627
