### ISSUE TITLE
[micro] TFLite optimization failed with TFLite micro interpreter

### ISSUE THREAD

**Issue by ehirdoy** [tensorflow/tensorflow#32213]
**System information**
- custom code: Modified TFLite micro example, **hello_world**, to use MNIST.
- OS Platform and Distribution: Linux Ubuntu 18.04
- TensorFlow installed from: binary
- TensorFlow version: v1.12.1-3259-gf59745a381 2.0.0-beta0
- Python version: 3.6.8

**Describe the current behavior**
Without TFL converter optimization, prediction on **micro interpreter** works.
With any TFL converter optimization, prediction on **micro interpreter** gets wild and produce **random** values.
For example,
`converter.optimizations = [tf.lite.Optimize.DEFAULT]`

**Describe the expected behavior**
Regardless of TFL converter optimization, prediction on **micro interpreter** should work.

**Code to reproduce the issue**
https://github.com/ehirdoy/tflm-helloworld/tree/bug

NG: https://github.com/ehirdoy/tflm-helloworld/commit/13fd1c39e368729f574f44daf93299470ec1649d HEAD
OK: https://github.com/ehirdoy/tflm-helloworld/commit/a025d2a5f5c2487b551b6bfd8414926ebf864bfb HEAD^

> $ git checkout -f bug
> $ make input_data.h
> $ make
> $ ./hello_world # NG
> $ git checkout HEAD^
> $ make
> $ ./hello_world # OK

**Other info / logs**
Logs are in the git commit mesage in the above, {OK,NG} commits.

> commit 13fd1c39e368729f574f44daf93299470ec1649d (HEAD, origin/bug, github/bug)
> Author: Hiroshi Doyu <hiroshi.doyu@ericsson.com>
> Date:   Wed Sep 4 14:14:33 2019 +0300
> 
>     [BUG?] store TFLite file optimized for size
> 
>     Without the following
>       'converter.optimizations = [tf.lite.Optimize.OPTIMIZE_FOR_SIZE]',
>     MNIST prediction works OK as seen in the previous commit log.
> 
>     With the above OPTIMIZE_FOR_SIZE inserted right before convert(),
>     MNIST prediction seems to go wild with random values as seen below:
> 
>       $ touch train-mnist-tflite.py
>       $ make
>       $ ./hello_world
> 
>           ......
>           ................
>           ................
>                ...........
>                       ....
>                      ....
>                      ....
>                     ....
>                     ....
>                    ....
>                    ...
>                   ....
>                  ....
>                 .....
>                 ....
>                .....
>                ....
>               .....
>               .....
>               ....
> 
>     0: 0.096435
>     1: 0.083848
>     2: 0.109924
>     3: 0.096781
>     4: 0.103029
>     5: 0.100698
>     6: 0.095319
>     7: 0.095055
>     8: 0.114907
>     9: 0.104004
>
>     0: 0.000000
>     1: 0.000000
>     2: 0.000000
>     3: 0.000000
>     4: 0.000000
>     5: 0.000000
>     6: 0.000000
>     7: 0.000000
>     8: 1.000000
>     9: 0.000000
>

**Comment by jvishnuvardhan** [comment]
@ehirdoy Is this still an issue? Can you check with `TF2.0` and let us know whether the issue persists with latest TF version. If this was not resolved with `TF2.0` or `tf-nightly`, please update [the gist](https://colab.sandbox.google.com/gist/jvishnuvardhan/ea39638fcb8ad1294985631e25f4567e/untitled546.ipynb) and share. Thanks!

**Comment by jvishnuvardhan** [comment]
@ehirdoy Did you had time to review my shared gist? Thanks!

**Comment by jvishnuvardhan** [comment]
Automatically closing this out since I understand it to be resolved, but please let me know if I'm mistaken.Thanks!
