### ISSUE TITLE
[TF 2.0.0-rc0] Keras layer dependency tracking behaviour changed in 2.0.0-rc0

### ISSUE THREAD

**Issue by lgeiger** [tensorflow/tensorflow#32210]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): macOS, Linux Ubuntu 16.04
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.0.0-rc0
- Python version: Python 3.6/3.7

We are developing an open source library for training binarized and other extremely quantized networks at http://larq.dev that heavily relies on `tf.keras`. For this we are adding custom layers that modify (i.e. quantize) the layers kernel (and activations) prior to the computation.

## Expected Behaviour

A simplified version of what we are doing is here:
```python
from tensorflow import keras

# For our use case this would be a quantizer with a custom gradient
def projection(x):
    return 2 * x

class CustomDense(keras.layers.Dense):
    def call(self, inputs):
        original_kernel = self.kernel
        self.kernel = projection(self.kernel)
        outputs = super().call(inputs)
        self.kernel = original_kernel  # reset the original kernel to make this work in eager mode
        return outputs

model = keras.models.Sequential([CustomDense(32, input_shape=(32,))])

assert model.layers[0].kernel in model.layers[0].trainable_weights
```

This worked well for TensorFlow 1.13, 1.14 in graph and eager as well as for `2.0.0-beta0` and `2.0.0-beta1`.

## Current Behaviour

It looks like TensorFlow `2.0.0-rc0` changed the automatic dependency tracking which makes the above code fail on the last line. The same is true for `2.0.0.dev20190904`:
```python-traceback
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-1-e416b6b97b33> in <module>
     40 model = keras.models.Sequential([CustomDense(32, input_shape=(32,))])
     41 
---> 42 assert model.layers[0].kernel in model.layers[0].trainable_weights

~/miniconda3/envs/tf2/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py in __bool__(self)
    874 
    875   def __bool__(self):
--> 876     return bool(self._numpy())
    877 
    878   __nonzero__ = __bool__

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```

Ignoring the automatic dependency tracking by using the following makes the above code work.
```python
from tensorflow import keras
from tensorflow.python.training.tracking.base import (
         no_automatic_dependency_tracking_scope,
     )

def projection(x):
    return 2 * x

class CustomDense(keras.layers.Dense):
    def call(self, inputs):
        original_kernel = self.kernel
        with no_automatic_dependency_tracking_scope(self):
            self.kernel = projection(self.kernel)
        outputs = super().call(inputs)
        with no_automatic_dependency_tracking_scope(self):
            self.kernel = original_kernel
        return outputs

model = keras.models.Sequential([CustomDense(32, input_shape=(32,))])

assert model.layers[0].kernel in model.layers[0].trainable_weights
```

## Questions

Is this behaviour change expected or is it a bug in `2.0.0-rc0`?

Is there a better way to achieve this, without needing to temporarily overwrite `layer.kernel`?

If this change is expected, is it save to use the private `no_automatic_dependency_tracking_scope` to workaround this issue?

@dynamicwebpaige Is this issue better posted at the TensorFlow 2.0 testing mailing list?

**Comment by jaingaurav** [comment]
@lgeiger: Thanks for the bug report. Recently we changed the behavior of equality in 2.0 such that Variables & Tensors are no longer hashable. As an unfortunate side-effect `model.layers[0].kernel in model.layers[0].trainable_weights` does not work as you probably intended since it is trying to do an element-wise equality comparison of `model.layers[0].kernel` with each of the trainable weights. Instead, please try changing your code to `any(model.layers[0].kernel is w for w in model.layers[0].trainable_weights)`

We'd received a couple of reports with people running into obscure errors with this change and will look into improving the communication of this change.

**Comment by lgeiger** [comment]
@jaingaurav Thanks for the info, I agree more documentation about this change would help. 

Do you know why the comparison when ignoring the dependency tracking with `no_automatic_dependency_tracking_scope` works? Following your argument, I intuitively would expect it to fail as well.
