### ISSUE TITLE
AttributeError: 'Tensor' object has no attribute ['order', 'degree', 'rank']

### ISSUE THREAD

**Issue by bionicles** [tensorflow/tensorflow#32221]
**System information**
- TensorFlow version (you are using): 1.14
- Are you willing to contribute it (Yes/No): Yes. `return len(self.shape) - 1`

**Describe the feature and the current behavior/state.**

from wikipedia:
> The order (also degree or rank) of a tensor is thus the sum of the orders of its arguments plus the order of the resulting tensor. This is also the dimensionality of the array of numbers needed to represent the tensor with respect to a specific basis, or equivalently, the number of indices needed to label each component in that array.

I assumed I could do x.rank ; x.order, x.degree to get this value for a tensor. This is useful when we build a layer we need to do different functions for different order of tensors (e.g. image vs sequence data) 

**Will this change the current api? How?**
User can quickly access the rank of a tensor without having to recalculate it for each tensor. Tensors by definition have an order, so this change allows TF tensors to have the normal attributes a tensor would have in linear algebra discussion

**Who will benefit with this feature?**
Users making custom layers often need to do boilerplate: `x_rank = len(x.shape) - 1 or such, and  might do it wrong. 

I made some neural interfaces to resize/reshape data to a common code, but convolution is a lot more effective if you concat coords to the tensor (https://arxiv.org/abs/1807.03247); logic often differs for different tensor ranks, so rather than users rewrite the 'len(x.shape) - N' 123456789 times, maybe we can just add this attribute to the Tensor class?   

**Any Other info.**
tf.keras.layers.Input mutates input shape to add batch size. I'm not sure how to handle the [mandatory] shape mutation in keras, I personally detest that, but it's not going away, guess we can just increment the rank, or not, you guys r smart, what do you think, is a batch of tensors a 1-higher-rank tensor? cc @alextp @fchollet

Note: TFP lib has a "batch_shape" tuple, not integer, not sure if that causes issues, they have a 'param_shape' or such function to help with it 

example with image data sort of shape
```
import tensorflow as tf
import numpy as np

print('tf:', tf.__version__)
print('np:', np.__version__)

SHAPE_AFTER_KERAS_MUTATES_IT = (1, 123, 123, 4)
y = tf.random.normal(SHAPE_AFTER_KERAS_MUTATES_IT)

SHAPE_WITHOUT_BATCH_OR_CHANNELS = y.shape[1:-1]
coords_np = np.indices(SHAPE_WITHOUT_BATCH_OR_CHANNELS)   # no tf.indices ? :(
coords = tf.convert_to_tensor(coords_np, dtype=tf.float32)

if y.rank is 3:  # <--- this fails and we have to manually compute rank
     coords = tf.transpose(coords, [1, 2, 0])
     coords = tf.expand_dims(coords, 0)
     coords.shape

y_with_coords = tf.concat([y, coords], -1)
```

**Comment by alextp** [comment]
This is by design, use len(tensor.shape) instead, or tf.rank(tensor), etc.
