### ISSUE TITLE
Build error C2589 on x64-Windows-static

### ISSUE THREAD

**Issue by JackBoosY** [tensorflow/tensorflow#32228]
Hi Developers,

I recently tried to build tensorflow using vcpkg, and I have encountered some compilation errors.
After two days of research this issue, I gave up. And I am not familiar with the bazel compiler.
So can someone help me?

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): **Windows 10 x64 build 1903**
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: **N/A**
- TensorFlow installed from (source or binary): **source**
- TensorFlow version: **v1.14.0**
- Python version: **3.7.3**
- Installed using virtualenv? pip? conda?: **vcpkg**
- Bazel version (if compiling from source): **0.25.2**
- GCC/Compiler version (if compiling from source): **Visual Studio 2017 ver 15.9.13**
- CUDA/cuDNN version:  **N/A**
- GPU model and memory: **CPU model, 32GB Memory**

**Describe the problem**
First build, error like:
`.\tensorflow/stream_executor/rng.h(66): error C2589: 'constant': illegal token on right side of '::'`
Tried to build **again**, the build was **successful**. I don't know why. 

**Provide the exact sequence of commands / steps that you executed before running into the problem**
1. Clone vcpkg from `https://github.com/microsoft/vcpkg.git`.
2. Build vcpkg with command `.\bootstrap.bat`.
3. Install tensorflow with command `.\vcpkg.exe install tensorflow-cc:x64-windows-static`.

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.
[build-x64-windows-static-err.log](https://github.com/tensorflow/tensorflow/files/3577942/build-x64-windows-static-err.log)
[build-x64-windows-static-out.log](https://github.com/tensorflow/tensorflow/files/3577943/build-x64-windows-static-out.log)
[config-x64-windows-static-err.log](https://github.com/tensorflow/tensorflow/files/3577944/config-x64-windows-static-err.log)
[config-x64-windows-static-out.log](https://github.com/tensorflow/tensorflow/files/3577945/config-x64-windows-static-out.log)

Thanks.

**Comment by JackBoosY** [comment]
Related: [#7995](https://github.com/microsoft/vcpkg/issues/7995).

**Comment by gunan** [comment]
@vitong I think is looking into this.

**Comment by Saduf2019** [comment]
@ JackBoosY 
Is this still an issue.

**Comment by JackBoosY** [comment]
After updating the version, there are some errors in the configuration, waiting for the solution to try to reproduce this issue.

**Comment by JackBoosY** [comment]
I will reopen this issue if this issue still happened.
