### ISSUE TITLE
`tf.strings.regex_replace` cannot add special characters on rewrite pattern

### ISSUE THREAD

**Issue by danielwatson6** [tensorflow/tensorflow#32227]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): macOS 10.13.4
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.0.0b1 (CPU version)
- Python version: 3.7.4

**Describe the current behavior**
Google's re2 library seems to be unable to handle rewrite patterns with characters like `\n`, `\t`, etc.

**Describe the expected behavior**
The expected output of the code below should be `<tf.Tensor: id=4, shape=(), dtype=string, numpy=b'hello\tworld'>`

**Code to reproduce the issue**
```
>>> s = "hello world"
>>> tf.strings.regex_replace(s, r" ", r"\t")
external/com_googlesource_code_re2/re2/re2.cc:925: invalid rewrite pattern: \t
<tf.Tensor: id=4, shape=(), dtype=string, numpy=b'helloworld'>
```

**Comment by oanush** [comment]
@danielwatson6 ,
Please be informed that Its the existing functionality explainedi in [link](https://github.com/google/re2/wiki/Syntax).Thanks!

**Comment by oanush** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
