### ISSUE TITLE
AttributeError: module 'tensorflow' has no attribute 'indices'

### ISSUE THREAD

**Issue by bionicles** [tensorflow/tensorflow#32222]
**System information**
- TensorFlow version (you are using): 1.14 (colab)
- Are you willing to contribute it (Yes/No): not sure how

**Describe the feature and the current behavior/state.**
np.indices is useful to quickly get coordinates for each element in a shape, tensorflow doesn't have this so user must import numpy for this

**Will this change the current api? How?**
sure, `coordinates = tf.indices(x.shape[1:-1], dtype=DTYPE)` would allow one to get coordinates for a tensor. Ideally it would have a `normalize=True` kwarg where user can get normalized coordinates for coordinate convolution https://arxiv.org/abs/1807.03247

**Who will benefit with this feature?**
anyone who uses convolution, and wants code to run faster (i.e. by not importing numpy)

**Any Other info.**
```
import tensorflow as tf
import numpy as np
coordinates_np = np.indices((28, 28))  # works
coordinates_tf = tf.indices((28, 28))  # crashes
```

> AttributeError: module 'tensorflow' has no attribute 'indices'

[https://docs.scipy.org/doc/numpy/reference/generated/numpy.indices.html](np.indices docs)

**Comment by brilhana** [comment]
Up for grabs?

**Comment by mihaimaruseac** [comment]
Sure

**Comment by bionicles** [comment]
```
# https://github.com/titu1994/keras-coordconv/blob/master/coord.py
import tensorflow as tf

from tools import normalize, log

K, L, B = tf.keras, tf.keras.layers, tf.keras.backend


def Coordinator(shape):
    log("build coordinator with shape:", shape, debug=True, color='green')
    if len(shape) is 2:
        return ConcatCoords2D()
    elif len(shape) is 3:
        return ConcatCoords3D()
    elif len(shape) is 4:
        return ConcatCoords4D()
    else:
        raise Exception(f"{shape} not supported by coordinator")


class ConcatCoords2D(L.Layer):
    def __init__(self):
        super(ConcatCoords2D, self).__init__()
        self.handler = ConcatCoords3D()
        self.built = True

    @tf.function
    def call(self, x):
        x = tf.expand_dims(x, -1)
        return self.handler(x)

    def compute_output_shape(self, input_shape):
        output_shape = list(input_shape)
        output_shape.append(1)
        output_shape[-1] = output_shape[-1] + 1
        return tuple(output_shape)


class ConcatCoords3D(L.Layer):
    def __init__(self):
        super(ConcatCoords3D, self).__init__()
        self.built = True

    @tf.function
    def call(self, x):
        shape = tf.shape(x)
        coords = tf.range(shape[1])
        coords = tf.expand_dims(coords, 0)
        coords = tf.expand_dims(coords, -1)
        coords = tf.tile(coords, [shape[0], 1, 1])
        coords = tf.cast(coords, tf.float32)
        coords = normalize(coords)
        return tf.concat([x, coords], -1)

    def compute_output_shape(self, input_shape):
        output_shape = list(input_shape)
        output_shape[-1] = output_shape[-1] + 1
        return tuple(output_shape)


class ConcatCoords4D(L.Layer):
    def __init__(self):
        super(ConcatCoords4D, self).__init__()

    def build(self, shape):
        h = tf.range(shape[1], dtype=tf.float32)
        w = tf.range(shape[2], dtype=tf.float32)
        h, w = normalize(h), normalize(w)
        hw = tf.stack(tf.meshgrid(h, w, indexing='ij'), axis=-1)
        hw = tf.expand_dims(hw, 0)
        self.hw = tf.tile(hw, [shape[0], 1, 1, 1])
        super().build(shape)

    @tf.function
    def call(self, x):
        return tf.concat([x, self.hw], -1)

    def compute_output_shape(self, input_shape):
        output_shape = list(input_shape)
        output_shape[-1] = output_shape[-1] + 2
        return tuple(output_shape)
```

**Comment by rytisss** [comment]
Hi all! I'm writing regarding the CoordConv layers in native Tensorflow API. I saw this ISSUE as a possible related to my question :) Is CoordConv considered a feature in a future release? I am using a nice implementation from the following repo: [https://github.com/mvoelk/keras_layers ](url) . However, it would nice to see CoordConv as a native Layer in Tensorflow :)

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.
