### ISSUE TITLE
Why tfrecord only support Int64, Float, Bytes, not support Int32 or Double？

### ISSUE THREAD

**Issue by youw3** [tensorflow/tensorflow#32233]
for example， i only need Int32 ， it seems to need more space to store the Int64 data？ also i need Double but using Float will cut off the precision of data.

**Comment by jsimsa** [comment]
These are proto types not Python types, which means a) integers are encoded as varints which means small values will not use 8 bytes (see https://developers.google.com/protocol-buffers/docs/encoding) b) the `float` type can represent both 32-bit and 64-bit values (see https://developers.google.com/protocol-buffers/docs/proto).

**Comment by ptxmac** [comment]
> b) the `float` type can represent both 32-bit and 64-bit values (see https://developers.google.com/protocol-buffers/docs/proto).

I don't think that's true - protobuf have a `double` type, and the `float` type maps to a 32-bit in any language that have different types:

![image](https://user-images.githubusercontent.com/56919/111143236-d70c8a80-8585-11eb-9146-e6da70e91d1d.png)
