### ISSUE TITLE
boolean_mask does not accept a Tensor as axis

### ISSUE THREAD

**Issue by javidcf** [tensorflow/tensorflow#32236]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10 x64
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: NA
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): unknown 1.14.0
- Python version: 3.6.8 (Anaconda)
- Bazel version (if compiling from source): NA
- GCC/Compiler version (if compiling from source): NA
- CUDA/cuDNN version: NA
- GPU model and memory: NA

**Describe the current behavior**

[`tf.boolean_mask`](https://www.tensorflow.org/api_docs/python/tf/boolean_mask) does not accept a scalar [`tf.Tensor`](https://www.tensorflow.org/api_docs/python/tf/Tensor) object as axis parameter.

**Describe the expected behavior**

As per the docs, [`tf.boolean_mask`](https://www.tensorflow.org/api_docs/python/tf/boolean_mask) should accept a scalar  [`tf.Tensor`](https://www.tensorflow.org/api_docs/python/tf/Tensor) object as axis parameter.

> * `axis`: A 0-D int Tensor representing the axis in `tensor` to mask from. By default, axis is 0 which will mask from the first dimension. Otherwise K + axis <= N.

**Code to reproduce the issue**

The following snippet:

```py
import tensorflow as tf
tf.boolean_mask([1, 2, 3], [True, False, True], axis=tf.constant(0, dtype=tf.int32))
```

Causes the exception:

```none
TypeError: slice indices must be integers or None or have an __index__ method
```

For comparison, the equivalent operation with [`tf.gather`](https://www.tensorflow.org/api_docs/python/tf/gather) works correctly:

```py
import tensorflow as tf
with tf.Session() as sess:
    print(sess.run(tf.gather([1, 2, 3], [0, 1], axis=tf.constant(0, dtype=tf.int32))))
    # [1 2]
```

**Other info / logs**

Full traceback:

```none
TypeError                                 Traceback (most recent call last)
<ipython-input-3-4beb5ed72842> in <module>
      1 import tensorflow as tf
----> 2 tf.boolean_mask([1, 2, 3], [True, False, True], axis=tf.constant(0, dtype=tf.int32))

~\AppData\Local\Continuum\anaconda3\envs\tf_test\lib\site-packages\tensorflow\python\ops\array_ops.py in boolean_mask(tensor, mask, name, axis)
   1369           " are None.  E.g. shape=[None] is ok, but shape=None is not.")
   1370     axis = 0 if axis is None else axis
-> 1371     shape_tensor[axis:axis + ndims_mask].assert_is_compatible_with(shape_mask)
   1372
   1373     leading_size = gen_math_ops.prod(shape(tensor)[axis:axis + ndims_mask], [0])

~\AppData\Local\Continuum\anaconda3\envs\tf_test\lib\site-packages\tensorflow\python\framework\tensor_shape.py in __getitem__(self, key)
    861     if self._dims is not None:
    862       if isinstance(key, slice):
--> 863         return TensorShape(self._dims[key])
    864       else:
    865         if self._v2_behavior:

TypeError: slice indices must be integers or None or have an __index__ method
```

**Comment by oanush** [comment]
Issue replicating for the TF version-1.14, kindly find the [gist](https://colab.sandbox.google.com/gist/oanush/8f7790e5d292c7d84482bd3c9629d2e0/32236.ipynb) of colab.Thanks!

**Comment by yongtang** [comment]
@javidcf I tried with latest TF and the issue should have been fixed. I will close this issue but feel free to reopen if issue persists.

**Comment by javidcf** [comment]
@yongtang Thanks for having a look. Unfortunately, this still happens in graph mode, e.g. with `tf.function`:

```python
@tf.function
def f():
    return tf.boolean_mask([1, 2, 3], [True, False, True],
                           axis=tf.constant(0, dtype=tf.int32))
f()
# TypeError: slice indices must be integers or None or have an __index__ method
```

Tested in TensorFlow 2.2.0-rc4.

**Comment by yongtang** [comment]
@javidcf  Added a PR for the fix.

**Comment by yongtang** [comment]
@javidcf Update:  Added a PR #39159 for the fix.
