### ISSUE TITLE
tf.scatter_nd sums updates if indices are duplicated

### ISSUE THREAD

**Issue by RichardArendsen71** [tensorflow/tensorflow#32235]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): no
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version (use command below): tensorflow-gpu==2.0.0rc0
- Python version: 3.6.8
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
tf.scatter_nd sums update values if indices are present multiple times. I use this function for moving pixels in an image. Some pixels are present twice and this gives wrong pixel values in scatter.

tf.Tensor([ 0 11  0 10  9  0  0 12], shape=(8,), dtype=int32)
tf.Tensor([ 0 11  0 10  9  0  0 24], shape=(8,), dtype=int32)
tf.Tensor([ 0 11  0 10  9  0  0 36], shape=(8,), dtype=int32)
**Describe the expected behavior**
I expect this behavior:

tf.Tensor([ 0 11  0 10  9  0  0 12], shape=(8,), dtype=int32)
tf.Tensor([ 0 11  0 10  9  0  0 12], shape=(8,), dtype=int32)
tf.Tensor([ 0 11  0 10  9  0  0 12], shape=(8,), dtype=int32)

Otherwise I need to find unique indices and delete multiples. And why it is adding? Maybe other options are possible then too.

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.
indices1 = tf.constant([[4], [3], [1], [7]])
updates1 = tf.constant([9, 10, 11, 12])

indices2 = tf.constant([[4], [3], [1], [7], [7]])
updates2 = tf.constant([9, 10, 11, 12, 12])

indices3 = tf.constant([[4], [3], [1], [7], [7], [7]])
updates3 = tf.constant([9, 10, 11, 12, 12, 12])

shape = tf.constant([8])

scatter1 = tf.scatter_nd(indices1, updates1, shape)
scatter2 = tf.scatter_nd(indices2, updates2, shape)
scatter3 = tf.scatter_nd(indices3, updates3, shape)

print(scatter1)
print(scatter2)
print(scatter3)

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by oanush** [comment]
@RichardArendsen71 ,
The present functionality is for summation only as per the [link](https://tensorflow.google.cn/versions/r2.0/api_docs/python/tf/scatter_nd?hl=en) `If indices contains duplicates, then their updates are accumulated (summed).` 
Can you please let us know the use cases where the other operations can be applied,so that we can consider it as a feature request?Thanks!

**Comment by RichardArendsen71** [comment]
Thanks for the answer. I missed that part. Actually I wanted to use:

`image_rotate=tf.keras.preprocessing.image.apply_affine_transform(
            image, theta=-angle*180/math.pi, fill_mode='constant', cval=0.0, order=1)`

I works in eager execution, but with `@tf.function` it returns an error:

> NotImplementedError: in converted code:
    relative to /home/face:

    projects/tensorflow2/facenettf2/crop_compare.py:27 crop_eyes_fixed1  *
        image_rotate=tf.keras.preprocessing.image.apply_affine_transform(
    .virtualenvs/tensorflow2/lib/python3.6/site-packages/keras_preprocessing/image/affine_transformations.py:285 apply_affine_transform  *
        theta = np.deg2rad(theta)
    .virtualenvs/tensorflow2/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py:736 __array__
        " array.".format(self.name))

    NotImplementedError: Cannot convert a symbolic Tensor (truediv_4:0) to a numpy array.

If this can be fixed I am also happy. For a sort term solution I tried to write my own rotation code and needed the function tf.scatter_nd, to set the pixel values of the rotated images.

So, main reason. I want to rotate an image at an given angle. I found [https://tensorflow.google.cn/versions/r2.0/api_docs/python/tf/image/rot90?hl=en](url) , but this is only 90 degrees.

What is the best way to go? I really want to use tensorflow 2.0.

**Comment by ymodak** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.
Thanks!

**Comment by RichardArendsen71** [comment]
When will this function be available for tensorflow 2.0? https://www.tensorflow.org/api_docs/python/tf/contrib/image/transform

**Comment by ymodak** [comment]
Unfortunately TF 2.0 won't have this functionality. However we have added many other functions to ```tf.image``` module. See https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/image#functions

You may use ```transform``` function from tensorflow addons package if necessary.
For this you have to install ```tensorflow-addons``` separately.
See https://github.com/tensorflow/addons#maintainers
Thanks!

**Comment by RichardArendsen71** [comment]
I tried addons before, but that did not work with the latest TF 2.0 version. Now, I tried it again and it works, also with AutoGraph. So, I can do now what I needed. Thanks.
