### ISSUE TITLE
iOS framework build of tf_lite has missing _TFLGpuDelegateCreate object

### ISSUE THREAD

**Issue by nidegen** [tensorflow/tensorflow#32237]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- TF Version: b50852ccac3d9e90af0568391ace90fc1da440e1 (master on Sep. 5 2019)
- build type: built with `sh tensorflow/lite/tools/make/build_ios_universal_lib.sh`
- trying to compile for iOS on Xcode 10.2

**Describe the problem**

- Add TensorFlow_lite.framework to target, link and add header search path as no module header avaiable
- Following error on build: `"Undefined symbols for architecture arm64:
  "_TFLGpuDelegateCreate", referenced from:"` in `.mm` class calling `TFLGpuDelegateCreate(&options)`

**Comment by stakemura** [comment]
#31261 I struggle the same problem too. I think tensorflow should integrate the iOS build method into bazel.

**Comment by stakemura** [comment]
Any news?
Converting `/tensorflow/lite/tools/make/build_ios_universal_lib.sh` to bazel is too difficult for me.

**Comment by yyoon** [comment]
Hi, sorry for the late reply.
Currently, the GPU delegate should be part of the nightly builds of `TensorFlowLiteSwift` frameworks distributed via CocoaPods. See https://www.tensorflow.org/lite/guide/ios#cocoapods_developers for more details.
Would that resolve your issue?

**Comment by yyoon** [comment]
I'm closing the issue for now. Feel free to open a new issue if you're still having problems.

**Comment by nidegen** [comment]
ok thanks, i guess it works, haven't tried as current hack is working;)
