### ISSUE TITLE
Is tensorflow lite malloc free?

### ISSUE THREAD

**Issue by mlostekk** [tensorflow/tensorflow#32249]
I read that TFL Micro is malloc free, but is Tensorflow Lite also malloc free? I wondering if its safe to use inside an audio thread?

**Comment by aselle** [comment]
TensorFlow lite for fixed shape inference minimizes mallocs needed when running repeated inferences. In cases of fixed shapes after AllocateTensors() there should be no more mallocs. However, malloc is thread safe,  so you can just try and make sure it works well for your use case.
