### ISSUE TITLE
Please modify cuda-bin in cuda_configure.bzl to copy just needed files instead of directory

### ISSUE THREAD

**Issue by skeydan** [tensorflow/tensorflow#32244]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Fedora 30
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): source
- TensorFlow version: master branch 
- Python version: 3.7
- Installed using virtualenv? pip? conda?: N/A
- Bazel version (if compiling from source): 0.25.2
- GCC/Compiler version (if compiling from source): 7.4.1
- CUDA/cuDNN version: 10.1 / 7.6
- GPU model and memory: Quadro M2200

If you don't have CUDA installed in `/usr/local/cuda`, but in the "normal RPM way" (so that binaries end up in `/usr/bin`, libraries in `/usr/lib64` etc), the following `cuda-bin` rule

```
# in third_party/gpus/cuda_configure.bzl
copy_rules.append(make_copy_dir_rule(
    repository_ctx,
    name = "cuda-bin",
    src_dir = cuda_config.cuda_toolkit_path + "/bin",
    out_dir = "cuda/bin",
))
```

will end up trying to copy all the binaries in `/usr/bin`, which on some systems (where these commands are not other-readable) may lead to errors like this one:

```
ERROR: /home/key/.cache/bazel/_bazel_key/8de93c72df6c3fec3e289f10fadff72b/external/local_config_cuda/cuda/BUILD:1399:1: Executing genrule @local_config_cuda//cuda:cuda-bin failed (Exit 1)
cp: cannot open '/usr/bin/./sudoedit' for reading: Permission denied
cp: cannot open '/usr/bin/./locate' for reading: Permission denied
cp: cannot open '/usr/bin/./sudo' for reading: Permission denied
cp: cannot open '/usr/bin/./sudoreplay' for reading: Permission denied
cp: cannot open '/usr/bin/./chsh' for reading: Permission denied
cp: cannot open '/usr/bin/./chfn' for reading: Permission denied

```

Evidently these files should in fact not be copied ... looking for what binaries really are wanted, I found this:

```
# in nccl/build_defs.bzl.tpl
_device_link = rule(
    implementation = _device_link_impl,
    attrs = {
        "deps": attr.label_list(),
        "out": attr.output(mandatory = True),
        "gpu_archs": attr.string_list(),
        "nvlink_args": attr.string_list(),
        "_nvlink": attr.label(
            default = Label("@local_config_cuda//cuda:cuda/bin/nvlink"),
            allow_single_file = True,
            executable = True,
            cfg = "host",
        ),
        "_fatbinary": attr.label(
            default = Label("@local_config_cuda//cuda:cuda/bin/fatbinary"),
            allow_single_file = True,
            executable = True,
            cfg = "host",
        ),
        "_bin2c": attr.label(
            default = Label("@local_config_cuda//cuda:cuda/bin/bin2c"),
            allow_single_file = True,
            executable = True,
            cfg = "host",
        ),
        "_link_stub": attr.label(
            default = Label("@local_config_cuda//cuda:cuda/bin/crt/link.stub"),
            allow_single_file = True,
        ),
    },
```

In fact when I hard-code these 4 files, modifying the `cuda-bin` rule like this

```
copy_rules.append(make_copy_files_rule(
         repository_ctx,
         name = "cuda-bin",
         srcs = [
            cuda_config.cuda_toolkit_path + "/bin/" + "crt/link.stub",
            cuda_config.cuda_toolkit_path + "/bin/" + "nvlink",
            cuda_config.cuda_toolkit_path + "/bin/" + "fatbinary",
            cuda_config.cuda_toolkit_path + "/bin/" + "bin2c"
        ],
        outs = [
            "cuda/bin/" + "crt/link.stub",
            "cuda/bin/" + "nvlink",
            "cuda/bin/" + "fatbinary",
            "cuda/bin/" + "bin2c"
        ],
     ))
```

all works great.

Would you be interested in adapting the build rule accordingly? Not only would it not fail, it'd be also cleaner not to try to copy files like `sudo` :-)

I'd be happy to submit a PR but would probably need some guidance (assuming you don't want the file names hard coded as I'm doing for my workaround). Thanks!

**Comment by angerson** [comment]
Your suggestion looks like a good idea -- would you mind preparing a PR with the same changes as worked for you?

Creating a PR would initiate more tests for your change, which would help catch any potential problems of changing the list of binaries.

**Comment by skeydan** [comment]
Great, I will do that!

**Comment by skeydan** [comment]
Here it is: https://github.com/tensorflow/tensorflow/pull/32838

thanks!

**Comment by mohantym** [comment]
Hi! @skeydan ! Could you close this issue then?

**Comment by mihaimaruseac** [comment]
closing as #32838 landed a while ago

**Comment by skeydan** [comment]
thanks!
