### ISSUE TITLE
tf.train.SingularMonitoredSession() Error:tensorflow.python.framework.errors_impl.NotFoundError: Failed to create a NewWriteableFile

### ISSUE THREAD

**Issue by anjul1008** [tensorflow/tensorflow#32246]
hi,
I'm new with tensorflow, I'm facing an issue while executing a [project](https://github.com/hcmlab/vadnet/blob/master/train/code/main.py) on window 10.

Using :
python-3.5.4
tensorboard-gpu=1.14.0
cuda-10

ERROR:
tensorflow.python.framework.errors_impl.NotFoundError: Failed to create a NewWriteableFile: C:\Users\MY-PC\Desktop\tools\vadnet\train\nets\vad_Model[48000,48000,24000,512,None]_Conv7[2,True,False,4,2]_SceAdam[1e-04,0.9,0.999,1e-08]\ckpt\model.ckpt-0_temp_df1af0f684d24212bc1ebde45848fe3f/part-00000-of-00001.data-00000-of-00001.tempstate18107421248045726006 : The system cannot find the path specified.

path is correct and directory is created "nets\vad_Model[48000,48000,24000,512,None]_Conv7[2,True,False,4,2]_SceAdam[1e-04,0.9,0.999,1e-08]\ckpt" 
by script but 
"part-00000-of-00001.data-00000-of-00001.tempstate18107421248045726006" 
file not creating.

I read somewhere, need to use an absolute path. I had tried that also but still facing the same error.
thank you!

**Comment by ravikyram** [comment]
In order to expedite the trouble-shooting process, please provide a minimal standalone code to reproduce the issue reported here. Thanks!

**Comment by anjul1008** [comment]
hi ravikyram,
it's itself a complete project, thats why i gave the link.

**Comment by jvishnuvardhan** [comment]
This is not Build/Installation or Bug/Performance issue. Please post this kind of support questions at [Stackoverflow](https://stackoverflow.com/questions/tagged/tensorflow). There is a big community to support and learn from your questions. GitHub is mainly for addressing bugs in installation and performance. Thanks!

Please post the issue in [that repo](https://github.com/hcmlab/vadnet/issues) or in stackoverflow. Thanks!
