### ISSUE TITLE
TPU with tensorflow 2.0 -- 'DeleteIterator' OpKernel missing

### ISSUE THREAD

**Issue by youngalou** [tensorflow/tensorflow#32255]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): YES
- OS Platform and Distribution: Debian GNU/Linux 9
- TensorFlow installed from (source or binary): /usr/bin/pip3
- TensorFlow version (use command below): 2.0.0b1
- Python version: 3.5.3
- TPU type: v2-8
- TPU software version: 1.14 

**Describe the current behavior**
I am running a TPU allocated by `ctpu up` in tensorflow 2.0 (I'm aware this isn't fully supported atm). I have a simple training loop functioning mostly following the guidelines here:
https://www.tensorflow.org/beta/guide/distribute_strategy#using_tfdistributestrategy_with_custom_training_loops

To my surprise I have encountered few issues along the way, but one that I can't seem to remedy on my end is this:
`tensorflow.python.framework.errors_impl.NotFoundError: No registered 'DeleteIterator' OpKernel for TPU devices compatible with node {{node DeleteIterator}}`

This error doesn't seem to actually break anything, but I'm worried there could be a TPU memory leak or something and that is difficult to verify without any useable TPU profiling tools for TF 2.0.
EDIT: The bug does actually cause the program to crash after a few iterations.

**Describe the expected behavior**
I expect to be able to delete the iterator object within the TPU strategy scope.

**Code to reproduce the issue**
```
for epoch in range(self.train_epochs):
    with tf.device(self.device), self.distribution_strategy.scope():
        dataset = self.fill_experience_buffer()
        exp_buff = iter(dataset)

        for step in tqdm(range(self.train_steps), "Training epoch {}".format(epoch)):
            train_step(next(exp_buff))
```

The issue occurs the second time around in the loop when the `exp_buff` variable is rewritten with `iter(dataset)`. I've tried explicitly freeing the object with 'del exp_buff' within and outside of the scope():, but the same error occurs regardless.

**Other info / logs**
Full error message here (the message appears 8 times, once for each TPU device, but the messages are identical:
```
Exception ignored in: <bound method IteratorResourceDeleter.__del__ of <tensorflow.python.data.ops.iterator_ops.IteratorResourceDeleter object at 0x7f0bac1883c8>>
Traceback (most recent call last):
  File "/home/youngalou/.local/lib/python3.5/site-packages/tensorflow/python/data/ops/iterator_ops.py", line 531, in __del__
    handle=self._handle, deleter=self._deleter)
  File "/home/youngalou/.local/lib/python3.5/site-packages/tensorflow/python/ops/gen_dataset_ops.py", line 800, in delete_iterator
    _six.raise_from(_core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.NotFoundError: No registered 'DeleteIterator' OpKernel for TPU devices compatible with node {{node DeleteIterator}}
        .  Registered:  device='CPU'
  device='GPU'

Additional GRPC error information:
{"created":"@1567559533.240191338","description":"Error received from peer","file":"external/grpc/src/core/lib/surface/call.cc","file_line":1039,"grpc_message":"No registered 'DeleteIterator' OpKernel for TPU devices compatible with node {{node DeleteIterator}}\n\t.  Registered:  device='CPU'\n  device='GPU'\n","grpc_status":5} [Op:DeleteIterator]
Exception ignored in: <bound method IteratorResourceDeleter.__del__ of <tensorflow.python.data.ops.iterator_ops.IteratorResourceDeleter object at 0x7f0bac188518>>
Traceback (most recent call last):
  File "/home/youngalou/.local/lib/python3.5/site-packages/tensorflow/python/data/ops/iterator_ops.py", line 531, in __del__
    handle=self._handle, deleter=self._deleter)
  File "/home/youngalou/.local/lib/python3.5/site-packages/tensorflow/python/ops/gen_dataset_ops.py", line 800, in delete_iterator
    _six.raise_from(_core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.NotFoundError: No registered 'DeleteIterator' OpKernel for TPU devices compatible with node {{node DeleteIterator}}
        .  Registered:  device='CPU'
  device='GPU'
```

**Comment by ravikyram** [comment]
Looks like the code is incomplete.Can you please provide full code snippet to reproduce it on our environment.Thanks!

**Comment by youngalou** [comment]
Sorry about that! First time submitting a bug report.
I've recreated a small standalone script that demonstrates the bug.

```
import numpy as np
import tensorflow as tf

tpu_address = 'youngalou'
device = '/job:worker'
train_epochs = 100
train_steps = 100
dataset_size = 1000
batch_size = 256

cluster_resolver = tf.distribute.cluster_resolver.TPUClusterResolver(tpu=tpu_address)
tf.config.experimental_connect_to_host(cluster_resolver.master())
tf.tpu.experimental.initialize_tpu_system(cluster_resolver)
tpu_strategy = tf.distribute.experimental.TPUStrategy(cluster_resolver)

def get_dataset():
    dataset = tf.data.Dataset.from_tensor_slices((np.zeros((dataset_size,128),dtype=np.float32), np.zeros((dataset_size,1),dtype=np.float32)))
    dataset = dataset.shuffle(dataset_size).repeat().batch(batch_size)
    return tpu_strategy.experimental_distribute_dataset(dataset)

for _ in range(train_epochs):
    with tf.device(device), tpu_strategy.scope():
        dataset = get_dataset()
        exp_buff = iter(dataset)

        for _ in range(train_steps):
            train_batch = next(exp_buff)
```

**Comment by ravikyram** [comment]
I have tried on colab with TF version 2.0 beta1 and was able to reproduce the issue.Please, find the gist [here](https://colab.sandbox.google.com/gist/ravikyram/49dc704bebc4b101f2eddd0169c9e15c/untitled167.ipynb).Thanks!

**Comment by captain-pool** [comment]
> 
> 
> Sorry about that! First time submitting a bug report.
> I've recreated a small standalone script that demonstrates the bug.
> 
> ```
> import numpy as np
> import tensorflow as tf
> 
> tpu_address = 'youngalou'
> device = '/job:worker'
> train_epochs = 100
> train_steps = 100
> dataset_size = 1000
> batch_size = 256
> 
> cluster_resolver = tf.distribute.cluster_resolver.TPUClusterResolver(tpu=tpu_address)
> tf.config.experimental_connect_to_host(cluster_resolver.master())
> tf.tpu.experimental.initialize_tpu_system(cluster_resolver)
> tpu_strategy = tf.distribute.experimental.TPUStrategy(cluster_resolver)
> 
> def get_dataset():
>     dataset = tf.data.Dataset.from_tensor_slices((np.zeros((dataset_size,128),dtype=np.float32), np.zeros((dataset_size,1),dtype=np.float32)))
>     dataset = dataset.shuffle(dataset_size).repeat().batch(batch_size)
>     return tpu_strategy.experimental_distribute_dataset(dataset)
> 
> for _ in range(train_epochs):
>     with tf.device(device), tpu_strategy.scope():
>         dataset = get_dataset()
>         exp_buff = iter(dataset)
> 
>         for _ in range(train_steps):
>             train_batch = next(exp_buff)
> ```

Hey! @youngalou , You don't need to open the strategy and device scope everytime. This produces different context ID, while training the model.
So, I'ld ask you to shift the `tf.device()` and `strategy.scope()` outside the loop.
```python3
with tf.device(device), tpu_strategy.scope():
    for _ in range(train_epochs):
        dataset = get_dataset()
        exp_buff = iter(dataset)

        for _ in range(train_steps):
            train_batch = next(exp_buff)
```
This is supposed to work.

**Comment by captain-pool** [comment]
And about `{{DeleteIterator}}` issue, This issue is raised when the code suddenly crashes and kills the execution. So while debugging TPU code, these errors are to be ignored (unless there's nothing else in the traceback, apart from these). Scroll up to find out what killed the code.
In your case there's a high chance, The TPU cannot process it since 2 different context IDs are produced for the same training graph.

**Comment by guptapriya** [comment]
+1 to @captain-pool's recommendations. You should not enter the strategy scope in a loop, but move the loop inside the scope. Let us know if that fixes the issue.

**Comment by rxsang** [comment]
Hi Louis,

Could you try to call
"tf.config.experimental_connect_to_cluster(cluster_resolver)"? In that way you don't need to enter the device scope as well.

**Comment by youngalou** [comment]
@captain-pool Exactly as you said. Moved the scope outside of the loop and am having no problems. Thanks so much for the quick response!

**Comment by youngalou** [comment]
@captain-pool Thanks for the quick response! I tried moving the scope outside of the loop as you 
 suggested but that doesn't seem to fix the problem.

**Comment by youngalou** [comment]
@rxsang It doesn't look like that method exists in this version of tensorflow (2.0.0b1).
`AttributeError: module 'tensorflow._api.v2.config' has no attribute 'experimental_connect_to_cluster'`

**Comment by captain-pool** [comment]
https://github.com/captain-pool/GSOC/blob/master/E1_TPU_Sample/image_retraining_tpu_strategy.py

This is a sample i wrote for GSoC. I guess this can serve as a reference.

**Comment by youngalou** [comment]
@captain-pool In the code sample you provided you don't delete or rewrite the iterator so the same problem isn't present.

**Comment by captain-pool** [comment]
Hey @younglou, why do you need to delete the iterator? In TPUs this problem is still persistent. You can't just iterate to the end of the dataset and wait for `StopIteration`. You have to provide the total number of steps to iterate for.
So your code should be like.
```python3
with tf.device(device), tpu_strategy.scope():
  dataset = iter(get_dataset().repeat())
  for i in range(epochs * train_steps):
    train_batch = next(dataset)
```

**Comment by youngalou** [comment]
@captain-pool I need to create new iterators because I'm using this for a reinforcement learning training loop. Specifically I'm training a DQN and the dataset is an experience buffer that changes over time. In the code snippet I created originally, there is a `train_steps` variable that provides the total number of iterations.

**Comment by rxsang** [comment]
Hi, when the issue was created, TF2 TPU hasn't been enabled yet. And it has been launched in TF2.1. Could you try the same code again using TF2.2?

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this issue, as you are using an older version of tensorflow(1.x) which is officially considered as end of life. We recommend that you upgrade to 2.4 or later version and let us know if the issue still persists in newer versions. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, Please open a new issue for any help you need against 2.x, and we will get you the right help.

**Comment by ymodak** [comment]
Please test with latest version of TF 2.5 and verify if fixed. Thanks!
