### ISSUE TITLE
tf.saved_model.save() broken for my subclassed model in tf-2.0.0rc0

### ISSUE THREAD

**Issue by DavidKWH** [tensorflow/tensorflow#32250]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04.02 LTS
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): tf2.0.0rc0
- Python version: 3.6.7
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

n [4]: tf.version.GIT_VERSION                                                           
Out[4]: 'v2.0.0-beta1-5101-gc75bb66'

In [5]: tf.version.VERSION                                                               
Out[5]: '2.0.0-rc0'

**Describe the current behavior**

I have a subclassed model that I have been saving and deploying since tf-2.0.0b0 and after upgrading to rc0, it errored out with this message.

[save.py:136] Skipping full serialization of object <__main__.MyModel object at 0x7f76815add30> because an error occurred while tracing layer functions. Error message: in converted code:

TypeError: tf__call() takes from 2 to 3 positional arguments but 4 were given

This is how the call method is defined in my class.  Can someone tell me what went wrong, or what I need to change to make this work?

Thanks, David

class MyModel(Model):

    def __init__(self, n_layers, h_dim, b_dim,
                       activation_fn,
                       kernel_init,
                       batch_norm):
        super().__init__()
        ... skipping ...

    @tf.function
    def call(self, inputs, training=False):
        y = inputs[0]
        h = inputs[1]
        n_var = inputs[2]
        x = layers.concatenate([y, h])
        if self.n_layers >= 1: x = self.d_hidden_1(x,training=training)
        if self.n_layers >= 2: x = self.d_hidden_2(x,training=training)
        if self.n_layers >= 3: x = self.d_hidden_3(x,training=training)
        if self.n_layers >= 4: x = self.d_hidden_4(x,training=training)
        if self.n_layers >= 5: x = self.d_hidden_5(x,training=training)
        # scale output by 1/n_var
        #return self.d_out(x) / n_var
        return self.d_out(x,training=training)

**Describe the expected behavior**
It should just work

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.
See above

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by ymodak** [comment]
@DavidKWH Can you please assemble a minimal reproducible code snippet to reflect this issue? Thanks!

**Comment by DavidKWH** [comment]
This has been resolved in the discuss forum.  It has been reproduced and a fixed has been proposed by Kathy.  Please see 

https://groups.google.com/a/tensorflow.org/forum/#!topic/discuss/wlwLvWnD4BI

**Comment by goldiegadde** [comment]
This issue has been resolved in the nightly and cherrypicked to the 2.0 branch. Please let us know if it is ok to close the issue. 

Thanks!

**Comment by goldiegadde** [comment]
Closing issue, please feel free to reopen if you continue to see issues.
