### ISSUE TITLE
Input placeholder with shape [1] of saved_model.pb accepts scaler input but throws error in later graph.

### ISSUE THREAD

**Issue by Mickky666** [tensorflow/tensorflow#32254]
Env:
* Mac OS
* python 2.7
* tensorflow 1.13.1 installed from pip

Description:
I'm using estimator API to build model. Inside serving input function, my model has an int64 input placeholder with shape [1]. And this placeholder is later concatenated with another tensor. Then I trained the model and saved it to `*.pb` graph. However during serving time I mistakenly feed a scaler value to this placeholder:
```
dtype: DT_INT64
tensor_shape {
}
int64_val: 182
```
As you can see, there is no dimension info in this proto. It didn't immediately throw an error and it seems that the placeholder with shape [1] is compatible with it. However later during concatenating op I got the error:
```
*** _Rendezvous: <_Rendezvous of RPC that terminated with:
        status = StatusCode.INVALID_ARGUMENT
        details = "ConcatOp : Expected concatenating dimensions in the range [0, 0), but got 0
         [[{{node concat_77}}]]"
        debug_error_string = "{"created":"@1567706789.859604000","description":"Error received from peer ipv6:[::1]:9000","file":"src/core/lib/surface/call.cc","file_line":1041,"grpc_message":"ConcatOp : Expected concatenating dimensions in the range [0, 0), but got 0\n\t [[{{node concat_77}}]]","grpc_status":3}"
```
Later I realized I did something wrong in the dimension so I add the shape info to my input proto. The error is gone. The correct proto looks like:
```
dtype: DT_INT64
tensor_shape {
  dim {
    size: 1
  }
}
int64_val: 182
```
In one word, a `saved_model.pb` with input placeholder of shape [1] accepts a scaler input and not throwing any error. However later in the concat operation, since we are doing `tf.concat([scaler, tf.constant([1])], axis=0)`, it throws an error since the scaler has 0 dimension.

Code to reproduce the error:
```
def serve_input_fn():
    receiver_tensor = {}
    serving_features = {}
    receiver_tensor['my_input'] = tf.placeholder(shape=[1], dtype=tf.int64)
    serving_features['my_feature'] = tf.concat([receiver_tensor['my_input'], [1]], axis=0)
    return tf.estimator.export.ServingInputReceiver(serving_features, receiver_tensors)

# create any estimater
estimator.export("/tmp/my_model", "serve_input_fn", mode="infer")

# serve the model and feed in the following input
request.inputs['my_input'].CopyFrom(tf.contrib.util.make_tensor_proto(100, dtype=tf.int64))
output = stup.Predict(request, 10)
```

**Comment by ravikyram** [comment]
@Mickky666 
This issue is more suitable for TensorFlow Serving repo. Please post it on Serving repo from [here](https://github.com/tensorflow/serving/issues). Thanks!

**Comment by Mickky666** [comment]
> @Mickky666
> This issue is more suitable for TensorFlow Serving repo. Please post it on Serving repo from [here](https://github.com/tensorflow/serving/issues). Thanks!

Sure, thanks.

**Comment by ravikyram** [comment]
I am closing this issue and we can track the issue in TensorFlow Serving repo. Thanks!
