### ISSUE TITLE
TF2.0 : Tensorflow object detection model zoo inference not working on gpu

### ISSUE THREAD

**Issue by wazeerzulfikar** [tensorflow/tensorflow#32262]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):Linux Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.0.0-rc0
- Python version: 3.6.8
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: CUDA 10.0
- GPU model and memory: GeForce RTX 2080 Ti

**Describe the current behavior**
Running any of the saved models from [tensorflow model zoo](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/detection_model_zoo.md) leads to a segmentation fault.

**Code to reproduce the issue**
```
import os
import tensorflow as tf
import numpy as np

os.system('wget http://download.tensorflow.org/models/object_detection/ssd_mobilenet_v2_coco_2018_03_29.tar.gz')
os.system('tar -xvf ssd_mobilenet_v2_coco_2018_03_29.tar.gz')

with tf.device('/device:GPU:0'):
    loaded_model = tf.saved_model.load('ssd_mobilenet_v2_coco_2018_03_29/saved_model')
    infer = loaded_model.signatures['serving_default']
    sample_img = np.zeros((1,128,128,3))
    predicted = infer(tf.constant(sample_img, tf.uint8))
    print(predicted)
```

**gdb output**
```
Thread 89 "python3" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7ffbfbfff700 (LWP 7857)]
0x00007fff4372b741 in tensorflow::NonMaxSuppressionV2GPUOp::Compute(tensorflow::OpKernelContext*) ()
   from /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/_pywrap_tensorflow_internal.so
```

**Comment by ymodak** [comment]
duplicate #32261
