### ISSUE TITLE
tf.keras.datasets.cifar10.load_data() cannot load lcoal files when cifar-10-batches-py mannully put to ~/.keras/dataset/

### ISSUE THREAD

**Issue by kolingv** [tensorflow/tensorflow#32278]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): NO
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: No
- TensorFlow installed from (source or binary): pip
- TensorFlow version (use command below): 2.0.0-beta1
- Python version: 3.6.9
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
- tf.keras.datasets.cifar10.load_data() cannot load lcoal files when cifar-10-batches-py mannully put to ~/.keras/dataset/. 
- It still try to download dataset online, while my network connection is restricted.
- similar behaviour happens when using tfds.load with data_dir setted
**Describe the expected behavior**
Load local cifarl dataset to numpy array without reporting any errors
**Code to reproduce the issue**
1. put downloaded  cifar-10-batches-py to ~/.keras/datasets/
2. code:
import tensorflow as tf
(train_images,train_labels), (_, _) = tf.keras.datasets.cifar10.load_data()

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by gadagashwini** [comment]
@kolingv, Could you provide the sample standalone code to reproduce the reported issue here. Thanks!

**Comment by kolingv** [comment]
@gadagashwini code is easy. Updted.

**Comment by kolingv** [comment]
@ymodak 
Again, my internet connection is restricted, I am not able to download cifar10 dataset from 'tf.keras.datasets.cifar10.load_data()'. The downloaed IP was blocked.
I can only access it somewhere and put it locally. 

Can't they just add a few line codes to check wether it is already downloaded locally?

Anyway, there are plenty codes on git to deal with cifar10, I downloaed and fixed it. 

ps:  'tf.keras.utils.get_file' requires original url. just a file path cannot make it. I didn't try it since it's a waste of time

**Comment by Violainewei** [comment]
You can do the following:
1. download it from https://www.cs.toronto.edu/~kriz/cifar-10-python.tar.gz
2. rename it as cifar-10-batches-py.tar.gz
3. copy it to ～./keras/datasets/

**Comment by rushirajsherlocked** [comment]
> You can do the following:
> 
> 1. download it from https://www.cs.toronto.edu/~kriz/cifar-10-python.tar.gz
> 2. rename it as cifar-10-batches-py.tar.gz
> 3. copy it to ～./keras/datasets/

This works perfectly! Anyone facing the same issue, please try renaming the file! Btw the download speed is too slow when you try downloading the dataset locally to your computer

**Comment by sp7412** [comment]
> You can do the following:
> 
> 1. download it from https://www.cs.toronto.edu/~kriz/cifar-10-python.tar.gz
> 2. rename it as cifar-10-batches-py.tar.gz
> 3. copy it to ～./keras/datasets/

I think step 3 was intended to be `cp ~/.keras/datasets/

**Comment by Hailprob** [comment]
change the name and copy it to ～./keras/datasets/ works perfect, thanks

**Comment by HoussemNeuer** [comment]
how i can find ～./keras/datasets/ ?

**Comment by ea123321** [comment]
> 
If you are using anaconda then maybe can find it in C
C:\Users\LWU3\anaconda3\Lib\site-packages\keras\datasets

**Comment by ea123321** [comment]
> how i can find ～./keras/datasets/ ?

If you are using anaconda then maybe can find it in C
C:\Users\LWU3\anaconda3\Lib\site-packages\keras\datasets

**Comment by byerose** [comment]
> > how i can find ～./keras/datasets/ ?
> 
> the path is `～/.keras/datasets/`

OK. Get it.

**Comment by ea123321** [comment]
> > > how i can find ～./keras/datasets/ ?
> > 
> > 
> > the path is `～/.keras/datasets/`
> 
> OK. Get it.

I tried the method in this post didn't work for me...Then I found solution from other post. In case it does not work for you you can run these 2 cmd below before you run the .load_data(). Good luck!

import ssl
ssl._create_default_https_context = ssl._create_unverified_context

**Comment by xdrl1** [comment]
The file name shall be exactly `cifar-10-batches-py-target_archive` (no `.tar.gz`) for `tensorflow==2.21.0`. The path is still `~/.keras/datasets/`. As this naming is kinda random, you can always check the following two files to figure out what file name is expected...

> keras/src/datasets/cifar10.py
> keras/src/utils/file_utils.py
