### ISSUE TITLE
`tf.estimator` missing in 2019-09-05 nightlies (and broken in 2019-09-04)

### ISSUE THREAD

**Issue by wchargin** [tensorflow/tensorflow#32270]
#### System information

- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): gLinux (like Debian)
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): `v1.12.1-10423-g11e22c0 2.0.0-dev20190905` (`tf-nightly-2.0-preview==2.0.0.dev20190905`)
- Python version: 3.6.8rc1
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

#### Describe the current behavior

The `tf.estimator` module appears not to exist:

```python
>>> import tensorflow as tf
>>> tf.estimator
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'tensorflow' has no attribute 'estimator'
>>> tf.compat.v2.estimator
<module 'tensorflow_estimator.python.estimator.api._v2.estimator' from '/tmp/tmp.hdyrTvpKDw/ve/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/api/_v2/estimator/__init__.py'>
>>> tf.compat.v1.estimator
<module 'tensorflow_estimator.python.estimator.api._v1.estimator' from '/tmp/tmp.hdyrTvpKDw/ve/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/api/_v1/estimator/__init__.py'>
>>> tf.estimator
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'tensorflow' has no attribute 'estimator'
```

#### Describe the expected behavior

The `tf.estimator` module should exist, given that it [is documented in
the TF 2.x APIs][1] and has been in previous nightlies.

[1]: https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/estimator

#### Code to reproduce the issue

```
python -c '__import__("tensorflow").estimator`
```

#### Other info / logs

N/A

**Comment by wchargin** [comment]
cc @mihaimaruseac @annarev ; this is blocking TensorBoard nightlies
because it causes our smoke tests to fail.

**Comment by annarev** [comment]
Sorry for the breakage! Tomorrow the issue should be fixed (thanks to Mihai).

Also today's pip packages have been removed today morning.

**Comment by wchargin** [comment]
Great—presumably that’s this commit, then:
<https://github.com/tensorflow/tensorflow/commit/18c2cf989a2263ee212fbd5ac0b3085d9450b80a>

Thanks @mihaimaruseac and @annarev!

**Comment by mihaimaruseac** [comment]
Just tested the new nightly now:

```console
(9) mihaimaruseac@ankh:/tmp/gh/9$ python -c "import tensorflow as tf; print('__'); print(tf.__version__); print('---'); print(tf.keras); print('~~~'); print(tf.estimator)"
__
2.0.0-dev20190906
---
<module 'tensorflow_core.keras' from '/tmp/gh/9/lib/python3.6/site-packages/tensorflow_core/python/keras/api/_v2/keras/__init__.py'>
~~~
<module 'tensorflow_core.estimator' from '/tmp/gh/9/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/api/_v2/estimator/__init__.py'>
```

All seems good

**Comment by wchargin** [comment]
Yep, and TensorBoard nightlies look good—thanks again! :-)
