### ISSUE TITLE
Memory keeps increasing with GradientTape

### ISSUE THREAD

**Issue by ChenYang-ChenYang** [tensorflow/tensorflow#32276]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 16.04.5
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: No
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.0.0rc
- Python version: 3.6
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: CUDA 10.0.130
- GPU model and memory: GeForce RTX 208, memory 10G

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
I create a subclass model with a encoder layer and decoder layer. Encoder is to call tf bidirectional LSTM and decoder is just a dense layer. I train the model with GradientTape, looping to pass data with generator. The GPU memory keep increasing.  

**Describe the expected behavior**
The GPU memory usage should be stable after the 1st epoch.

**Code to reproduce the issue**
I minimize my code and save it to https://github.com/ChenYang-ChenYang/tf-memory-increase
You can just run train.py to reproduce.

The memory increase from 700M at epoch 1 to 1080M at epoch 6 in the sample project. My actual project have much more data and more complex model. The memory increase to 10G after some epochs and OOM, so I can't continue to train.

**Other info / logs**
If I change the sample project to use model.compile() and then fit(), instead of using GradientTape, the memory is stable.  But my actual project is complex, including seq2seq addons, multiple outputs and losses, so it is very difficult to change to use model.compile() and fit(). I have to use GradientTape.
It seems the memory is re-created and not released in each epoch or step.
By the way, I searched most of the tf memory issues, like https://github.com/tensorflow/tensorflow/issues/32052, https://github.com/tensorflow/tensorflow/issues/19385, https://github.com/tensorflow/tensorflow/issues/19671, none of them are the same or the solution doesn't work. The most common solution to release memory cache is to call tf.set_random_seed(1) in tf version 1.x. I tried to call tf.random.set_seed(1) in tf 2.0 but it didn't work.

**Comment by ymodak** [comment]
I tried to execute your code with TF 2.0 rc1 and was not able to reproduce it.
Following is the stack trace;
```python
----> 7     while eindex < len(inputs):
      8         batch_input = inputs[sindex:eindex]
      9         batch_target = targets[sindex:eindex]

TypeError: object of type 'Tensor' has no len()
```
Can you please confirm? Thanks!

**Comment by ChenYang-ChenYang** [comment]
@ymodak Thanks for the reply. how did you run the code? I tried again just now to download the project https://github.com/ChenYang-ChenYang/tf-memory-increase, activate my virtual environment in anaconda with tf 2.0rc, and can run 'python train.py' successfully. 
The len() is called in get_batch() in train.py to create data generator. It should work in eager mode.

**Comment by ChenYang-ChenYang** [comment]
any update on the issue?

**Comment by kkimdev** [comment]
Hi, sorry for the last response.  I just tried but couldn't reproduce.  Possibly it's already fixed.

https://colab.corp.google.com/drive/1-AN8UK9fdufKc_S94gq9e5SyITRvbYh7#scrollTo=W44iBKEPMIF8

```
Iteration 1   1049.54mb
Iteration 2   1057.66mb
Iteration 3   1056.96mb
Iteration 4   1063.93mb
Iteration 5   1059.28mb
Iteration 6   1067.30mb
Iteration 7   1061.53mb
Iteration 8   1068.94mb
Iteration 9   1064.90mb
Iteration 10  1072.23mb
Iteration 11  1066.85mb
Iteration 12  1074.11mb
Iteration 13  1070.71mb
Iteration 14  1075.72mb
Iteration 15  1071.78mb
Iteration 16  1077.85mb
Iteration 17  1073.74mb
Iteration 18  1079.09mb
Iteration 19  1074.56mb
Iteration 20  1080.32mb
```


Could you try tf-nightly to confirm? https://pypi.org/project/tf-nightly/

**Comment by kkimdev** [comment]
Public colab: https://colab.sandbox.google.com/gist/kkimdev/11ab2ccc36859092d4b2384fd7d0ecbe/memory-keeps-increasing-with-gradienttape-github-32276-public.ipynb#scrollTo=eACARpHcscHi

```
Iteration 0   1076.60mb
Iteration 1   2019.26mb
Iteration 2   2031.22mb
Iteration 3   2031.58mb
Iteration 4   2031.50mb
Iteration 5   2031.49mb
Iteration 6   2031.49mb
Iteration 7   2031.49mb
Iteration 8   2031.48mb
Iteration 9   2031.48mb
Iteration 10  2031.47mb
Iteration 11  2031.46mb
Iteration 12  2031.46mb
Iteration 13  2031.46mb
Iteration 14  2031.45mb
Iteration 15  2031.45mb
Iteration 16  2031.46mb
Iteration 17  2031.46mb
Iteration 18  2031.43mb
Iteration 19  2031.43mb
Iteration 20  2031.43mb
```

**Comment by ChenYang-ChenYang** [comment]
@kkimdev I verified with the same code on TF 2.0 stable version and the memory didn't increase after 9 epochs. The issue should have been resolved. I will close the case. Thanks.
