### ISSUE TITLE
Training a trivial keras model is not even close to deterministic despite call to set_random_seed.

### ISSUE THREAD

**Issue by drewm1980** [tensorflow/tensorflow#32289]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04
- TensorFlow installed from (source or binary): pip (binary)
- TensorFlow version (use command below): 1.14.0
- Python version: 3.6.5
- CUDA/cuDNN version:
- GPU model and memory:
output of tf_env_collect.sh:
[tf_env.txt](https://github.com/tensorflow/tensorflow/files/3584142/tf_env.txt)

**Describe the current behavior**
Training a trivial one layer keras model is not deterministic.

**Describe the expected behavior**
I would like to initialize the seeds and train deterministically, at least up to floating point precision. 

We are having severe problems with non-deterministic network behavior with more complex models (for both training an inference), and I minimized my example all the way down to a single layer. 

I have included a failing test case:

**Code to reproduce the issue**

```
import numpy
import tensorflow
from tensorflow import Session, global_variables_initializer, local_variables_initializer
from tensorflow.python import debug as tf_debug
from tensorflow.compat.v1 import Session
from tensorflow.compat.v1.keras.backend import set_session
from tensorflow.keras.layers import Conv2D, Input
from tensorflow.keras.models import Model

def call_in_new_session():
    import random
    random.seed(0)

    tensorflow.set_random_seed(1234)

    config = tensorflow.ConfigProto(
        device_count={'CPU': 1},
      intra_op_parallelism_threads=1,
      inter_op_parallelism_threads=1)
    session = Session(config=config)

    set_session(session)
    with session.as_default():
        print('---------------New Tensorflow Sesssion--------------------')
        model_shape = [1024,1024,3]

        numpy.random.seed(0)
        X = numpy.random.randn(1,*model_shape) # batch dimension 1
        y = numpy.random.randn(1,*model_shape)
        #print(X.sum()) # Numpy is determinisic here.

        tensorflow.compat.v1.random.set_random_seed(1234)

        i = Input(shape=model_shape, name='i')
        c = Conv2D(filters=1,kernel_size=(1,1))(i)
        model_2d = Model(inputs=i,outputs=c)

        model_2d.compile(loss='mean_squared_error', optimizer='adam')
        # Weights still not initialized; contain garbage data.
        
        loss = model_2d.train_on_batch([X,y])
        # loss is not determinisic here.

        weights = model_2d.get_weights()[0]
        print("OOOOOO weights sum:",weights.sum())
        print("OOOOOO loss sum:",loss.sum())

        return model_2d.predict_on_batch(X)

def test_deterministic_between_sessions():
    result1 = call_in_new_session()
    result2 = call_in_new_session()
    assert numpy.allclose(result1, result2, atol=1e-5), "Results were different when run in a fresh session!"

if __name__=='__main__':
    test_deterministic_between_sessions()

```

**Comment by gadagashwini** [comment]
@drewm1980, 
I tried executing the given code on colab but it results in an error. Please see the colab [gist](https://colab.sandbox.google.com/gist/gadagashwini/44863a1cb686dae7db585d9f86ef22cc/untitled134.ipynb) and confirm on the same. Thanks!

**Comment by gadagashwini** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
