### ISSUE TITLE
Dockerhub image tags naming inconsistency

### ISSUE THREAD

**Issue by cgarciae** [tensorflow/tensorflow#3228]
Hi,

I see on dockerhub that the image for version `r0.8` is the tag `0.8.0` but for version `r0.9` is `r0.9`. It would be nice if they were consistent so you don't have to look up every time you want to update.

**Comment by martinwicke** [comment]
Yes. r0.9 should be 0.9.0. We should update our scripts.

**Comment by gunan** [comment]
I have fixed the process generating our docker images, and rerunning our release script for 0.9.0.
Sorry for taking so long to fix this simple issue. I will Close the issue once I verify the images are uploaded with the correct tags.

**Comment by cgarciae** [comment]
Thanks!
