### ISSUE TITLE
how to use java implement functions,such as:Tensor、Graph、Operation etc.

### ISSUE THREAD

**Issue by awsssix** [tensorflow/tensorflow#32284]
@ry Could I implement funtions（Tensor） using java?
If yes, would you like to give me an example.
Thanks very much!

**Comment by gadagashwini** [comment]
@awsssix, Please refer the [Tensorflow official doc](https://www.tensorflow.org/api_docs/java/reference/org/tensorflow/package-summary) for Java  implementation.  Thanks!

**Comment by gadagashwini** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
