### ISSUE TITLE
UnsatisfiedLinkError for libtensorflow_jni.so when trying to load a newer model 

### ISSUE THREAD

**Issue by tastyminerals** [tensorflow/tensorflow#32290]
### System information
See attached [tf_env.txt](https://github.com/tensorflow/tensorflow/files/3584174/tf_env.txt) generated by `tf_env_collect.sh`.

tf.version.VERSION **1.14.0**
tf.version.GIT_VERSION unknown

### Describe the problem
We have been successfully training Tensorflow models and loading them into Java project for inference. We have been training models using Tensorflow [1.8.0 - 1.10.0] and loading them into a gradle project compiled with 1.8.0. It worked.
```
dependencies {

    compile(
            "org.tensorflow:tensorflow:" + "1.8.0",
            "com.google.guava:guava:" + guavaVersion,
            "com.opencsv:opencsv:" + openCSVVersion,
    )
```
Recently we have retrained the models using Tensorflow **1.14.0**. After replacing the older models and raising the gradle version number to 1.14.0
```
dependencies {

    compile(
            "org.tensorflow:tensorflow:" + "1.14.0",
            "com.google.guava:guava:" + guavaVersion,
            "com.opencsv:opencsv:" + openCSVVersion,
    )
```

one of the tests that attempts to load the model started throwing the following exception below:
```
java.lang.UnsatisfiedLinkError: /tmp/tensorflow_native_libraries-1567776737834-0/libtensorflow_jni.so: /tmp/tensorflow_native_libraries-1567776737834-0/libtensorflow_jni.so: undefined symbol: _ZN11tensorflow10FileSystem20RecursivelyCreateDirERKSs

	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1824)
	at java.lang.Runtime.load0(Runtime.java:809)
	at java.lang.System.load(System.java:1086)
	at org.tensorflow.NativeLibrary.load(NativeLibrary.java:101)
	at org.tensorflow.TensorFlow.init(TensorFlow.java:66)
	at org.tensorflow.TensorFlow.<clinit>(TensorFlow.java:70)
	at org.tensorflow.SavedModelBundle.<clinit>(SavedModelBundle.java:170)
```

This does not look like a bug issue but it would be nice if you could provide some tips on how to fix this on our end. Thank you.

**Comment by tastyminerals** [comment]
closing, this is a duplicate of https://github.com/tensorflow/tensorflow/issues/30635

**Comment by tastyminerals** [comment]
Reopening since the referred issue appears to be not connected with the current exception.

**Comment by tastyminerals** [comment]
Duplicate of https://github.com/tensorflow/tensorflow/issues/30635

**Comment by gautamk175** [comment]
waiting for answer
