### ISSUE TITLE
[TF.1.14] Train on TPU Pod with tf.keras 

### ISSUE THREAD

**Issue by nsantavas** [tensorflow/tensorflow#32291]
Can I train on a TPU Pod -not a single device- with tf.keras and how on TF1.14?

Thank you

**Comment by ymodak** [comment]
Yes you can train on cloud tpu with tf.keras https://www.tensorflow.org/guide/using_tpu
For more context see https://github.com/tensorflow/tensorflow/issues/27339#issuecomment-482716960

**Comment by nsantavas** [comment]
@ymodak Thanks for the response, but the link contains documentation only for tpu.estimator, not tf.keras.  Could you provide a mini example of tf.keras code that runs on TPU Pod using tf.1.14?

Thank you

**Comment by ymodak** [comment]
Here is a colab for tf.keras executing on tpu.
https://colab.sandbox.google.com/github/tensorflow/tpu/blob/master/tools/colab/fashion_mnist.ipynb
