### ISSUE TITLE
AttributeError: 'str' object has no attribute 'keys'

### ISSUE THREAD

**Issue by christk1** [tensorflow/tensorflow#32318]
**System information**
- Have I written custom code: yes
- OS Platform and Distribution: Ubuntu 18.04
- TensorFlow installed from: binary
- TensorFlow version: v2.0.0-beta1-5101-gc75bb66 2.0.0-rc0
- Python version: 3.7
- CUDA/cuDNN version: 10.0
- GPU model and memory: Nvidia rtx 2070

**Describe the current behavior**
I want to visualize the embeddings of my model but when i add:
```
embeddings_freq=1,
embeddings_metadata='metadata.tsv'
```
in the tensorboard callbacks
i am getting an error.

**Code to reproduce the issue**
```
import tensorflow as tf
from os import makedirs
from os.path import exists
import numpy as np

model_dir = "tmp/model_mnist/"
log_dir = "logs_mnist/"
if not exists(log_dir):
    makedirs(log_dir)
data_format = ('channels_first' if tf.test.is_built_with_cuda() else 'channels_last')

batch_size = 128
num_classes = 10
epochs = 12

# input image dimensions
img_rows, img_cols = 28, 28

# the data, split between train and test sets
(x_train, y_train), (x_test, y_test) = tf.keras.datasets.mnist.load_data()

if data_format == 'channels_first':
    x_train = x_train.reshape(x_train.shape[0], 1, img_rows, img_cols)
    x_test = x_test.reshape(x_test.shape[0], 1, img_rows, img_cols)
    input_shape = (1, img_rows, img_cols)
else:
    x_train = x_train.reshape(x_train.shape[0], img_rows, img_cols, 1)
    x_test = x_test.reshape(x_test.shape[0], img_rows, img_cols, 1)
    input_shape = (img_rows, img_cols, 1)

x_train = x_train.astype('float32')
x_test = x_test.astype('float32')
x_train /= 255
x_test /= 255
print('x_train shape:', x_train.shape)
print(x_train.shape[0], 'train samples')
print(x_test.shape[0], 'test samples')

# save class labels to disk to color data points in TensorBoard accordingly
with open(log_dir + 'metadata.tsv', 'w') as f:
    np.savetxt(f, y_test, fmt="%d")

# convert class vectors to binary class matrices
y_train = tf.keras.utils.to_categorical(y_train, num_classes)
y_test = tf.keras.utils.to_categorical(y_test, num_classes)

model = tf.keras.models.Sequential()
model.add(tf.keras.layers.Conv2D(32, kernel_size=(3, 3),
                                 activation='relu',
                                 input_shape=input_shape))
model.add(tf.keras.layers.Conv2D(64, (3, 3), activation='relu'))
model.add(tf.keras.layers.MaxPooling2D(pool_size=(2, 2)))
model.add(tf.keras.layers.Dropout(0.25))
model.add(tf.keras.layers.Flatten())
model.add(tf.keras.layers.Dense(128, activation='relu'))
model.add(tf.keras.layers.Dropout(0.5))
model.add(tf.keras.layers.Dense(num_classes, activation='softmax'))

model.compile(loss=tf.keras.losses.categorical_crossentropy,
              optimizer=tf.keras.optimizers.Adadelta(lr=1.),
              metrics=['accuracy'])

callbacks = tf.keras.callbacks.TensorBoard(log_dir=log_dir,
                                           embeddings_freq=1,
                                           embeddings_metadata='metadata.tsv')

model.fit(x_train, y_train,
          batch_size=batch_size,
          callbacks=[callbacks],
          epochs=epochs,
          verbose=1,
          validation_data=(x_test, y_test))
score = model.evaluate(x_test, y_test, verbose=0)
print('Test loss:', score[0])
print('Test accuracy:', score[1])

```

**Other info / logs**

> Traceback (most recent call last):
  File "/home/chris/Desktop/tests/mnist.py", line 75, in <module>
    validation_data=(x_test, y_test))
  File "/home/chris/miniconda3/envs/mdl/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training.py", line 734, in fit
    use_multiprocessing=use_multiprocessing)
  File "/home/chris/miniconda3/envs/mdl/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training_v2.py", line 292, in fit
    mode=ModeKeys.TRAIN)
  File "/home/chris/miniconda3/envs/mdl/lib/python3.7/site-packages/tensorflow_core/python/keras/callbacks.py", line 103, in configure_callbacks
    callback_list.set_model(callback_model)
  File "/home/chris/miniconda3/envs/mdl/lib/python3.7/site-packages/tensorflow_core/python/keras/callbacks.py", line 217, in set_model
    callback.set_model(model)
  File "/home/chris/miniconda3/envs/mdl/lib/python3.7/site-packages/tensorflow_core/python/keras/callbacks.py", line 1509, in set_model
    self._configure_embeddings()
  File "/home/chris/miniconda3/envs/mdl/lib/python3.7/site-packages/tensorflow_core/python/keras/callbacks.py", line 1536, in _configure_embeddings
    'argument: ' + str(self.embeddings_metadata.keys()))
AttributeError: 'str' object has no attribute 'keys'

**Comment by humza3656** [comment]
@christk1, were you able to resolve this issue? I'm getting the same one
