### ISSUE TITLE
tensorflow.python.framework.errors_impl.FailedPreconditionError: TensorRT is not enabled!

### ISSUE THREAD

**Issue by li829** [tensorflow/tensorflow#32313]
I am trying to use tensorflow-1.10 to optimize my pb model.
trt_graph = trt.create_inference_graph(
   input_graph_def = graph_def,
   outputs = outputs,
   max_batch_size=1,
   max_workspace_size_bytes=workspace_size,
   precision_mode='INT8',
   minimum_segment_size=3)

**Comment by gadagashwini** [comment]
@li829, Please elaborate the issue with context. And also, provide the code snippet to reproduce the issue. Thanks!

**Comment by gadagashwini** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
