### ISSUE TITLE
ModuleNotFoundError: No module named 'tensorflow' 

### ISSUE THREAD

**Issue by sharonevarghese** [tensorflow/tensorflow#32310]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): WIndows 7 64 bit
- TensorFlow installed from (source or binary): from : https://www.tensorflow.org/install/pip
------------------------------------------------------------------------------------------------------
the error generated while running -python -c "import tensorflow as tf;print(tf.reduce_sum(tf.random.normal([1000, 1000])))"- code mentioned in the site to verify the install. 

tensorflow —Latest stable release for CPU-only (recommended for beginners), from tesnorflow website
- TensorFlow version (or github SHA if from source):

**Provide the text output from tflite_convert**

```
# Copy and paste here

(venv) C:\Users\sharone\AppData\Local\Programs\Python\Python36>python -c "import
 tensorflow as tf;print(tf.reduce_sum(tf.random.normal([1000, 1000])))"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'tensorflow'
```

Also, please include a link to a GraphDef or the model if possible.

**Any other info / logs**

Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by mihaimaruseac** [comment]
Please post the full output of `pip debug --verbose` and `python -m pip --version` and `python -m pip install --upgrade pip && pyhon -m pip install -vvv tensorflow && pyhon -c "import tensorflow"` (please use them exactly as written)

**Comment by sharonevarghese** [comment]
> Please post the full output of `pip debug --verbose` and `python -m pip --version` and `python -m pip install --upgrade pip && pyhon -m pip install -vvv tensorflow && pyhon -c "import tensorflow"` (please use them exactly as written)


(venv) C:\Users\sharone\AppData\Local\Programs\Python\Python36>pip debug --verbo
se
WARNING: This command is only meant for debugging. Do not use this with automati
on for parsing and getting these details, since the output and options of this c
ommand may change without notice.
pip version: pip 19.2.3 from c:\users\sharone\appdata\local\programs\python\pyth
on36\venv\lib\site-packages\pip (python 3.6)
sys.version: 3.6.7 (v3.6.7:6ec5cf24b7, Oct 20 2018, 13:35:33) [MSC v.1900 64 bit
 (AMD64)]
sys.executable: c:\users\sharone\appdata\local\programs\python\python36\venv\scr
ipts\python.exe
sys.getdefaultencoding: utf-8
sys.getfilesystemencoding: utf-8
locale.getpreferredencoding: cp1252
sys.platform: win32
sys.implementation:
  name: cpython
Config variable 'Py_DEBUG' is unset, Python ABI tag may be incorrect
Config variable 'WITH_PYMALLOC' is unset, Python ABI tag may be incorrect
Compatible tags: 13
  cp36-cp36m-win_amd64
  cp36-none-win_amd64
  py3-none-win_amd64
  cp36-none-any
  cp3-none-any
  py36-none-any
  py3-none-any
  py35-none-any
  py34-none-any
  py33-none-any
  py32-none-any
  py31-none-any
  py30-none-any
-----------------------------------------------------------------------------------------------------------
(venv) C:\Users\sharone\AppData\Local\Programs\Python\Python36>python -m pip --v
ersion
pip 19.2.3 from C:\Users\sharone\AppData\Local\Programs\Python\Python36\lib\site
-packages\pip (python 3.6)
-----------------------------------------------------------------------------------------------------------
(venv) C:\Users\sharone\AppData\Local\Programs\Python\Python36>python -m pip ins
tall --upgrade pip && pyhon -m pip install -vvv tensorflow && pyhon -c "import t
ensorflow"
Requirement already up-to-date: pip in c:\users\sharone\appdata\local\programs\p
ython\python36\lib\site-packages (19.2.3)
'pyhon' is not recognized as an internal or external command,
operable program or batch file.

**Comment by sharonevarghese** [comment]
> Please post the full output of `pip debug --verbose` and `python -m pip --version` and `python -m pip install --upgrade pip && pyhon -m pip install -vvv tensorflow && pyhon -c "import tensorflow"` (please use them exactly as written)

**_another set of execution results._** 
Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

C:\Windows\system32>cd C:\Users\sharone\AppData\Local\Programs\Python\Python36

C:\Users\sharone\AppData\Local\Programs\Python\Python36>.\venv\Scripts\activate

(venv) C:\Users\sharone\AppData\Local\Programs\Python\Python36>pip install --upg
rade tensorflow
Requirement already up-to-date: tensorflow in c:\users\sharone\appdata\local\pro
grams\python\python36\venv\lib\site-packages (1.14.0)
Requirement already satisfied, skipping upgrade: wheel>=0.26 in c:\users\sharone
\appdata\local\programs\python\python36\venv\lib\site-packages (from tensorflow)
 (0.33.6)
Requirement already satisfied, skipping upgrade: keras-preprocessing>=1.0.5 in c
:\users\sharone\appdata\local\programs\python\python36\venv\lib\site-packages (f
rom tensorflow) (1.1.0)
Requirement already satisfied, skipping upgrade: tensorboard<1.15.0,>=1.14.0 in
c:\users\sharone\appdata\local\programs\python\python36\venv\lib\site-packages (
from tensorflow) (1.14.0)
Requirement already satisfied, skipping upgrade: protobuf>=3.6.1 in c:\users\sha
rone\appdata\local\programs\python\python36\venv\lib\site-packages (from tensorf
low) (3.9.1)
Requirement already satisfied, skipping upgrade: google-pasta>=0.1.6 in c:\users
\sharone\appdata\local\programs\python\python36\venv\lib\site-packages (from ten
sorflow) (0.1.7)
Requirement already satisfied, skipping upgrade: numpy<2.0,>=1.14.5 in c:\users\
sharone\appdata\local\programs\python\python36\venv\lib\site-packages (from tens
orflow) (1.17.2)
Requirement already satisfied, skipping upgrade: termcolor>=1.1.0 in c:\users\sh
arone\appdata\local\programs\python\python36\venv\lib\site-packages (from tensor
flow) (1.1.0)
Requirement already satisfied, skipping upgrade: wrapt>=1.11.1 in c:\users\sharo
ne\appdata\local\programs\python\python36\venv\lib\site-packages (from tensorflo
w) (1.11.2)
Requirement already satisfied, skipping upgrade: gast>=0.2.0 in c:\users\sharone
\appdata\local\programs\python\python36\venv\lib\site-packages (from tensorflow)
 (0.2.2)
Requirement already satisfied, skipping upgrade: six>=1.10.0 in c:\users\sharone
\appdata\local\programs\python\python36\venv\lib\site-packages (from tensorflow)
 (1.12.0)
Requirement already satisfied, skipping upgrade: keras-applications>=1.0.6 in c:
\users\sharone\appdata\local\programs\python\python36\venv\lib\site-packages (fr
om tensorflow) (1.0.8)
Requirement already satisfied, skipping upgrade: grpcio>=1.8.6 in c:\users\sharo
ne\appdata\local\programs\python\python36\venv\lib\site-packages (from tensorflo
w) (1.23.0)
Requirement already satisfied, skipping upgrade: absl-py>=0.7.0 in c:\users\shar
one\appdata\local\programs\python\python36\venv\lib\site-packages (from tensorfl
ow) (0.8.0)
Requirement already satisfied, skipping upgrade: tensorflow-estimator<1.15.0rc0,
>=1.14.0rc0 in c:\users\sharone\appdata\local\programs\python\python36\venv\lib\
site-packages (from tensorflow) (1.14.0)
Requirement already satisfied, skipping upgrade: astor>=0.6.0 in c:\users\sharon
e\appdata\local\programs\python\python36\venv\lib\site-packages (from tensorflow
) (0.8.0)
Requirement already satisfied, skipping upgrade: werkzeug>=0.11.15 in c:\users\s
harone\appdata\local\programs\python\python36\venv\lib\site-packages (from tenso
rboard<1.15.0,>=1.14.0->tensorflow) (0.15.6)
Requirement already satisfied, skipping upgrade: markdown>=2.6.8 in c:\users\sha
rone\appdata\local\programs\python\python36\venv\lib\site-packages (from tensorb
oard<1.15.0,>=1.14.0->tensorflow) (3.1.1)
Requirement already satisfied, skipping upgrade: setuptools>=41.0.0 in c:\users\
sharone\appdata\local\programs\python\python36\venv\lib\site-packages (from tens
orboard<1.15.0,>=1.14.0->tensorflow) (41.2.0)
Requirement already satisfied, skipping upgrade: h5py in c:\users\sharone\appdat
a\local\programs\python\python36\venv\lib\site-packages (from keras-applications
>=1.0.6->tensorflow) (2.10.0)


(venv) C:\Users\sharone\AppData\Local\Programs\Python\Python36>python -c "import
 tensorflow as tf;print(tf.reduce_sum(tf.random.normal([1000, 1000])))"
Traceback (most recent call last):
  File "C:\Users\sharone\AppData\Local\Programs\Python\Python36\lib\site-package
s\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\sharone\AppData\Local\Programs\Python\Python36\lib\site-package
s\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\sharone\AppData\Local\Programs\Python\Python36\lib\site-package
s\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_help
er
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, descript
ion)
  File "C:\Users\sharone\AppData\Local\Programs\Python\Python36\lib\imp.py", lin
e 243, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\sharone\AppData\Local\Programs\Python\Python36\lib\imp.py", lin
e 343, in load_dynamic
    return _load(spec)
ImportError: DLL load failed with error code -1073741795

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\sharone\AppData\Local\Programs\Python\Python36\lib\site-package
s\tensorflow\__init__.py", line 28, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-im
port
  File "C:\Users\sharone\AppData\Local\Programs\Python\Python36\lib\site-package
s\tensorflow\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Users\sharone\AppData\Local\Programs\Python\Python36\lib\site-package
s\tensorflow\python\pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "C:\Users\sharone\AppData\Local\Programs\Python\Python36\lib\site-package
s\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\sharone\AppData\Local\Programs\Python\Python36\lib\site-package
s\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\sharone\AppData\Local\Programs\Python\Python36\lib\site-package
s\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_help
er
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, descript
ion)
  File "C:\Users\sharone\AppData\Local\Programs\Python\Python36\lib\imp.py", lin
e 243, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\sharone\AppData\Local\Programs\Python\Python36\lib\imp.py", lin
e 343, in load_dynamic
    return _load(spec)
ImportError: DLL load failed with error code -1073741795


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

(venv) C:\Users\sharone\AppData\Local\Programs\Python\Python36>

**Comment by gadagashwini** [comment]
@sharonevarghese,
TensorFlow release binaries version 1.6 and above are prebuilt with AVX instruction sets.
Therefore on any CPU that does not have these instruction sets either CPU or GPU version of TF will fail to load.
Can you check once, does your CPU supports AVX instruction set or not. Thanks!

**Comment by sharonevarghese** [comment]
> @sharonevarghese,
> TensorFlow release binaries version 1.6 and above are prebuilt with AVX instruction sets.
> Therefore on any CPU that does not have these instruction sets either CPU or GPU version of TF will fail to load.
> Can you check once, does your CPU supports AVX instruction set or not. Thanks!

Intel(R) Core(TM) i3 CPU M380 @2.53GHz, 2533Mhz, 2 Core(s), 4 Logic - is my processor details. i'm not sure whether this supports AVX instruction set. Could you provide with the details on how to check whether the processor supports the AVX instruction set or not.

**Comment by sharonevarghese** [comment]
> @sharonevarghese,
> TensorFlow release binaries version 1.6 and above are prebuilt with AVX instruction sets.
> Therefore on any CPU that does not have these instruction sets either CPU or GPU version of TF will fail to load.
> Can you check once, does your CPU supports AVX instruction set or not. Thanks!

details of my processor, kindly advise whether the processor supports AVX instruction set, if no is there any way to run TensorFlow of my CPU
CPU-Z TXT Report
-------------------------------------------------------------------------

Binaries
-------------------------------------------------------------------------

CPU-Z version			1.90.0.x64

Processors
-------------------------------------------------------------------------

Number of sockets		1
Number of threads		4

APICs
-------------------------------------------------------------------------

Socket 0	
	-- Core 0 (ID 0)	
		-- Thread 0	0
		-- Thread 1	1
	-- Core 1 (ID 2)	
		-- Thread 2	4
		-- Thread 3	5

Timers
-------------------------------------------------------------------------

	ACPI timer		3.580 MHz
	Perf timer		2.468 MHz
	Sys timer		1.000 KHz


Processors Information
-------------------------------------------------------------------------

Socket 1			ID = 0
	Number of cores		2 (max 2)
	Number of threads	4 (max 4)
	Manufacturer		GenuineIntel
	Name			Intel Core i3 380M
	Codename		Arrandale
	Specification		Intel(R) Core(TM) i3 CPU       M 380  @ 2.53GHz
	Package (platform ID)	Socket 989 rPGA (0x4)
	CPUID			6.5.5
	Extended CPUID		6.25
	Core Stepping		K0
	Technology		32 nm
	TDP Limit		25.0 Watts
	Core Speed		1596.2 MHz
	Multiplier x Bus Speed	12.0 x 133.0 MHz
	Base frequency (cores)	133.0 MHz
	Base frequency (ext.)	133.0 MHz
	Rated Bus speed		2394.3 MHz
	Stock frequency		2533 MHz
	Instructions sets	MMX, SSE, SSE2, SSE3, SSSE3, SSE4.1, SSE4.2, EM64T, VT-x
	Microcode Revision	0x2
	L1 Data cache		2 x 32 KBytes, 8-way set associative, 64-byte line size
	L1 Instruction cache	2 x 32 KBytes, 4-way set associative, 64-byte line size
	L2 cache		2 x 256 KBytes, 8-way set associative, 64-byte line size
	L3 cache		3 MBytes, 12-way set associative, 64-byte line size
	Max CPUID level		0000000Bh
	Max CPUID ext. level	80000008h
	Cache descriptor	Level 1, D, 32 KB, 2 thread(s)
	Cache descriptor	Level 1, I, 32 KB, 2 thread(s)
	Cache descriptor	Level 2, U, 256 KB, 2 thread(s)
	Cache descriptor	Level 3, U, 3 MB, 16 thread(s)
	FID/VID Control		yes


	Turbo Mode		not supported
	Max turbo frequency	2533 MHz
	Max non-turbo ratio	19x
	Max turbo ratio		19x
	Max efficiency ratio	7x
	TDC Limit		25 Amps
	Max bus number		255
	Attached device		PCI device at bus 255, device 2, function 1

	Temperature 0		62 degC (143 degF) (Core #0)
	Temperature 1		65 degC (149 degF) (Core #1)
	Power 00		6.30 W (Package)
	Clock Speed 0		1596.19 MHz (Core #0)
	Clock Speed 1		1596.19 MHz (Core #1)
	Core 0 max ratio	19.0 (effective 19.0)
	Core 1 max ratio	19.0 (effective 19.0)

**Comment by gadagashwini** [comment]
@sharonevarghese, Did you try the @mihaimaruseac's suggestion.

**Comment by sharonevarghese** [comment]
> 
> 
> @sharonevarghese, Did you try the @mihaimaruseac's suggestion.

trying to install. but not able to install the  install Bazel 0.23.0 as per the https://www.tensorflow.org/install/source_windows. kindly guide me through it

**Comment by gadagashwini** [comment]
@sharonevarghese,
Please follow the instructions mentioned in the [bazel website](https://docs.bazel.build/versions/0.24.0/install-windows.html). This [link](https://github.com/bazelbuild/bazel/releases/tag/0.23.0) provide the bazel 0.23.0.exe file for windows. Let us know how it progresses. Thanks!

**Comment by sharonevarghese** [comment]
> 
> 
> @sharonevarghese, Did you try the @mihaimaruseac's suggestion.

trying bot cannot complete as held up in the previous replies

**Comment by gadagashwini** [comment]
@sharonevarghese, Did you install bazel using the instructions mentioned in the [bazel website](https://docs.bazel.build/versions/0.24.0/install-windows.html). OR if you are getting any error, please attach the error log here for faster move. Thanks!

**Comment by sharonevarghese** [comment]
### these are the steps i followed as per the bazel website
![1](https://user-images.githubusercontent.com/55018635/65230672-e4110080-daeb-11e9-87c7-03221fb1af34.jpg)
![2](https://user-images.githubusercontent.com/55018635/65230677-e7a48780-daeb-11e9-9945-0843a7ca189b.jpg)
![3](https://user-images.githubusercontent.com/55018635/65230680-e8d5b480-daeb-11e9-9e80-c238354dba8f.jpg)

### guide me through the installation

**Comment by sharonevarghese** [comment]
> 
> 
> @sharonevarghese, Did you install bazel using the instructions mentioned in the [bazel website](https://docs.bazel.build/versions/0.24.0/install-windows.html). OR if you are getting any error, please attach the error log here for faster move. Thanks!

![4](https://user-images.githubusercontent.com/55018635/65231323-09523e80-daed-11e9-9e41-569fd1f46f37.jpg)
### how to find the "binary" file mentioned

**Comment by gadagashwini** [comment]
@sharonevarghese,
In this [link](https://github.com/bazelbuild/bazel/releases/tag/0.23.0), click on the Assets. There you can find the bazel binaries. Download the bazel-0.23.0-windows-x86_64.exe from it. Thanks!

**Comment by sharonevarghese** [comment]
![5](https://user-images.githubusercontent.com/55018635/65237532-71f2e880-daf8-11e9-8270-2425bb30567d.jpg)
kindly help

**Comment by gadagashwini** [comment]
@sharonevarghese, 
Please follow the steps mentioned in here https://docs.bazel.build/versions/0.24.0/install-windows.html. Thanks!

**Comment by gadagashwini** [comment]
@sharonevarghese,
Did you build the Tensorflow using bazel. Thanks!

**Comment by gadagashwini** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
