### ISSUE TITLE
I don't like TensorFlow

### ISSUE THREAD

**Issue by Ahwar** [tensorflow/tensorflow#32327]
This template is for miscellaneous issues not covered by the other issue categories.

For questions on how to work with TensorFlow, or support for problems that are not verified bugs in TensorFlow, please go to [StackOverflow](https://stackoverflow.com/questions/tagged/tensorflow).

If you are reporting a vulnerability, please use the [dedicated reporting process](https://github.com/tensorflow/tensorflow/blob/master/SECURITY.md).

For high-level discussions about TensorFlow, please post to discuss@tensorflow.org, for questions about the development or internal workings of TensorFlow, or if you would like to know how to contribute to TensorFlow, please post to developers@tensorflow.org.
I used tensorflow and PyTorch and Facebook is the winner of this race
PyTorch is the most simple library and tensorFlow is the most difficult

**Comment by mihaimaruseac** [comment]
Closing as not a developer related issue. Please use feature request issues to suggest improvements and open new issues in case a bug is impeding your usage of TensorFlow.

**Comment by ucasiggcas** [comment]
torch is not easy,either
NO easy except Keras
