### ISSUE TITLE
ImportError: cannot import name pywrap_tensorflow

### ISSUE THREAD

**Issue by wwfeng2** [tensorflow/tensorflow#3232]
Operating System: MAC ISO 10.11

**Comment by Waffleboy** [comment]
See https://github.com/tensorflow/tensorflow/issues/3217

**Comment by aselle** [comment]
Thanks for the reply @Waffleboy. @wwfeng2 please close the issue if this suggestion resolves your problem.

**Comment by aselle** [comment]
Automatically closing due to lack of recent activity. Please reopen when further information becomes available.

**Comment by wwfeng2** [comment]
thanks,
