### ISSUE TITLE
TensorFlow installation apt commands is wrong

### ISSUE THREAD

**Issue by LucienZhang** [tensorflow/tensorflow#32329]
## URL(s) with the issue:

https://www.tensorflow.org/install/gpu

## Description of issue (what needs changing):

1. change your language to chinese simplified from the upright corner.
2. in the apt installation commands for Ubuntu 18.04 (CUDA 10), last step shown below is wrong:

```
  # Install TensorRT. Requires that libcudnn7 is installed above.
    sudo apt-get update && \
            && sudo apt-get install -y --no-install-recommends libnvinfer-dev=5.1.5-1+cuda10.0
```

1.  there is a syntax error--> && \ &&
2.  libnvinfer5=5.1.5-1+cuda10.0  should be installed first before libnvinfer-dev=5.1.5-1+cuda10.0
3.  just change the commands to the same as what is shown in english-language website.

**Comment by lamberta** [comment]
Thanks. Direct link to zh-cn page: https://tensorflow.google.cn/install/gpu?hl=zh-cn

This has been fixed in [the source file](https://github.com/tensorflow/docs/blob/master/site/en/install/gpu.md) but translations lag behind. Will be updated on next translation job.
