### ISSUE TITLE
cannot import tensorflow

### ISSUE THREAD

**Issue by game-sys** [tensorflow/tensorflow#32326]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): `import tensorflow as tf`
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): `pip install tensorflow`
- TensorFlow version (use command below): 
- Python version: 3.7
- CUDA/cuDNN version:cuda 8.0
- GPU model and memory:quadro 4000

**Describe the current behavior**
i have installed cuda 8.0 because my GPU support 8.0 but i think this version of tensor flow require cuda 10.0 so i want to downgrade my tensorflow which support cuda 8.0
**Describe the expected behavior**

**Code to reproduce the issue**
ImportError: Could not find 'cudart64_100.dll'. TensorFlow requires that this DLL be installed in a directory that is named in your %PATH% environment variable. Download and install CUDA 10.0 from this URL: https://developer.nvidia.com/cuda-90-download-archive

Provide a reproducible test case that is the bare minimum necessary to generate the problem.

**Other info / logs**
```
Traceback (most recent call last):
  File "C:\Users\Mohsin Ali\Anaconda3\envs\first\lib\site-packages\tensorflow\python\platform\self_check.py", line 75, in preload_check
    ctypes.WinDLL(build_info.cudart_dll_name)
  File "C:\Users\Mohsin Ali\Anaconda3\envs\first\lib\ctypes\__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] The specified module could not be found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/Mohsin Ali/PycharmProjects/first/tensor.py", line 1, in <module>
    import tensorflow as tf
  File "C:\Users\Mohsin Ali\Anaconda3\envs\first\lib\site-packages\tensorflow\__init__.py", line 28, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "C:\Users\Mohsin Ali\Anaconda3\envs\first\lib\site-packages\tensorflow\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Users\Mohsin Ali\Anaconda3\envs\first\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 30, in <module>
    self_check.preload_check()
  File "C:\Users\Mohsin Ali\Anaconda3\envs\first\lib\site-packages\tensorflow\python\platform\self_check.py", line 82, in preload_check
    % (build_info.cudart_dll_name, build_info.cuda_version_number))
ImportError: Could not find 'cudart64_100.dll'. TensorFlow requires that this DLL be installed in a directory that is named in your %PATH% environment variable. Download and install CUDA 10.0 from this URL: https://developer.nvidia.com/cuda-90-download-archive
```

**Comment by mihaimaruseac** [comment]
TensorFlow 1.13.0 and above needs CUDA 10.

**Comment by game-sys** [comment]
So what is version that uses cuda 8.0 and how to uninstall this tensor flow and reinstall version that uses 8.0

**Comment by mihaimaruseac** [comment]
Check [`pip uninstall`](https://pip.pypa.io/en/stable/reference/pip_uninstall/) and [tested build configurations on TensorFlow website](https://www.tensorflow.org/install/source#tested_build_configurations)

Seems you need TF 1.4 which is extremely old and not updated anymore

**Comment by game-sys** [comment]
OK I HAVE CREATED A NEW ENVIRONMENT WITH NO TENSORFLOW I WANT TO NOW INSTALL TENSORFLOW 1.4 SO IS THERE ANY PIP COMMAND TO INSTALL IT 
AS THIS COMMAND IS GIVING ERROR
(sec) C:\Users\Mohsin Ali\PycharmProjects\sec>pip install tensorflow==1.4
Collecting tensorflow==1.4
  ERROR: Could not find a version that satisfies the requirement tensorflow==1.4 (from versions: 1.13.0rc1, 1.13.0rc2, 1.13.1, 1.13.2, 1.14.0rc0, 1.14.0rc1, 1.14.0, 2.0.0a0, 2.0.0b0, 2.0.0b1, 2.0.0
rc0)
ERROR: No matching distribution found for tensorflow==1.4

**Comment by mihaimaruseac** [comment]
Please use `pip debug --verbose` to get the tags supported by your environment, then check against [those supported on PyPi](https://pypi.org/project/tensorflow/1.4.0/#files)

**Comment by gadagashwini** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
