### ISSUE TITLE
java.lang.IllegalArgumentException: Internal error: Failed to run on the given Interpreter: TfLiteGpuDelegate Invoke: Delegate should run on the same thread where it was initialized.Node number 175 (TfLiteGpuDelegate) failed to invoke

### ISSUE THREAD

**Issue by mgarbade** [tensorflow/tensorflow#32330]
In the android image classifier demo, I tried to run the Interpreter with GPU from start so I changed [this line](https://github.com/tensorflow/examples/blob/master/lite/examples/image_classification/android/app/src/main/java/org/tensorflow/lite/examples/classification/tflite/Classifier.java#L175-L189):

```
  protected Classifier(Activity activity, Device device, int numThreads) throws IOException {
    tfliteModel = loadModelFile(activity);
    switch (device) {
      case NNAPI:
        tfliteOptions.setUseNNAPI(true);
        break;
      case GPU:
        gpuDelegate = new GpuDelegate();
        tfliteOptions.addDelegate(gpuDelegate);
        break;
      case CPU:
        break;
    }

    tfliteOptions.setNumThreads(numThreads);
    tflite = new Interpreter(tfliteModel, tfliteOptions);
```

to this:

```
  protected Classifier(Activity activity, Device device, int numThreads) throws IOException {
    tfliteModel = loadModelFile(activity);
    gpuDelegate = new GpuDelegate();
    tfliteOptions.addDelegate(gpuDelegate);
    tfliteOptions.setNumThreads(numThreads);
    tflite = new Interpreter(tfliteModel, tfliteOptions);
```

sounds simple, but it crashes with the above mentioned error.
Weirdly: When I start the app in CPU mode and switch to GPU while running (via the options-sheet) it does work.

Is the GpuDelegate class using some custom thread?

**Comment by jdduke** [comment]
In the sample, the Interpreter is run on a separate thread. When using the GPU, you must create/apply the delegate on the same thread as the one you use to run inference.

**Comment by mgarbade** [comment]
This is not fixing it. I did not change the thread or anything. I just removed the switch-case, so the threads should be the same as before. Anyone else dealing with the same problem?

**Comment by mgarbade** [comment]
Also strange: If I add a `SystemClock.sleep(500);` after the call for initializing tflite and before running inference, it doesn't crash anymore. This hints to the fact, that the "thread" is not the problem at all.

Rather it seems that the system is not yet ready for running the classifier, although the "classifier != null" check passes successfully.

Is there a way to tell, when exactly the initialization of the tflite classifer with gpu delegate has completed?

**Comment by jdduke** [comment]
Ah, I think this may just be a function of the fact that the very first time we create the Interpreter, it happens to be on the UI thread, and in all such cases we default to CPU execution, not GPU. Subsequent requests to enable GPU are done on the inference thread. We should fix this in the examples.
