### ISSUE TITLE
pip install tensorflow from .whl not working

### ISSUE THREAD

**Issue by jassykatz** [tensorflow/tensorflow#32336]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- Windows 7
- TensorFlow installed from .whl file downloaded: tensorflow-1.14.0-cp36-cp36m-win_amd64.whl
- I am behind a firewall (hence downloaded .whl)
- Python version 3.6.4
- Anaconda navigator environment

**Describe the problem**
I am now getting the error:
Could not find a version that satisfies the requirement keras-preprocessing >=1.0.5 (from tensorflow ==1.14.0) (from versions: )
No matching distribution found for keras-preprocessing >= 1.0.5 (from tensorflow == 1.14.0)

**Provide the exact sequence of commands / steps that you executed before running into the problem**
I tried 'pip install tensorflow-1.14.0-cp36-cp36m-win_amd64.whl'

**Any other info / logs**
Before I was getting an error about google-pasta instead of keras-preprocessing.

**Comment by mihaimaruseac** [comment]
You will need to download a wheel for keras-preprocessing, as well as for all other dependencies. Might also want to check if `cp36m-win_amd64` shows up for you on `pip debug --verbose`

This is not exactly a TensorFlow code issue, more an issue with your own environment. Thus, closing, but please reopen if it becomes an issue with the actual code.

**Comment by mihaimaruseac** [comment]
w

**Comment by reliefs** [comment]
https://github.com/tensorflow/tensorflow/issues/32315 another one bits the dist

**Comment by mihaimaruseac** [comment]
I don't think it's related, @reliefs. This one seems to be not having the keraps-preprocessing wheel behind the firewall. Let's not jump to conclusions.

**Comment by reliefs** [comment]
https://github.com/tensorflow/tensorflow/issues/32627
