### ISSUE TITLE
[lite/micro] incorrect link of pre-generated files for STM32F746G Discovery Board

### ISSUE THREAD

**Issue by csukuangfj** [tensorflow/tensorflow#32347]
The link <https://drive.google.com/open?id=1u46mTtAMZ7Y1aD-He1u3R8AE4ZyEpnOl>
on page `tensorflow/lite/experimental/micro/README.md` for `STM32F746G Discovery Board` links to keil project based files instead of `Make/GCC` based files.

**Comment by gadagashwini** [comment]
@csukuangfj Thanks for reporting the issue. 
On the [page](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/experimental/micro/README.md#pre-generated-project-files) for `STM32F746G Discovery Board` links to `disco_keil project` instead of `Make/GCC` .

**Comment by rockyrhodes** [comment]
Thanks for reporting the issue.  We'll find the proper link and fix it up.

**Comment by rockyrhodes** [comment]
Dan, I believe this fix has now been checked in, right?

**Comment by csukuangfj** [comment]
Yes, it has been fixed.
