### ISSUE TITLE
Unable to load model with custom loss function with tf.keras.models.load_model

### ISSUE THREAD

**Issue by simonnanty** [tensorflow/tensorflow#32348]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): 
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: No
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): tensorflow==2.0.0rc0
- Python version: 2.6
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: None
- GPU model and memory: None

**Describe the current behavior**

I have saved a simple feed-forward Keras model. When I try to load it with the following code, I get an error. 
```
from tensorflow import keras
from tensorflow.keras import layers

inputs = keras.Input(shape=(784,), name='digits')
x = layers.Dense(64, activation='relu', name='dense_1')(inputs)
x = layers.Dense(64, activation='relu', name='dense_2')(x)
outputs = layers.Dense(10, activation='softmax', name='predictions')(x)
model = keras.Model(inputs=inputs, outputs=outputs, name='3_layer_mlp')

# Useless custom loss here
def custom_loss(y_true, y_pred):
    return keras.backend.mean(keras.backend.square(y_true - y_pred), axis=-1)

model.compile(loss=custom_loss, optimizer=keras.optimizers.RMSprop())

model.save("model/", save_format='tf')

# Here comes the bug:
new_model = keras.models.load_model('model/', custom_objects={'loss': custom_loss})
```
The error:
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File ".env/lib/python3.6/site-packages/tensorflow_core/python/keras/saving/save.py", line 147, in load_model
>     return saved_model_load.load(filepath, compile)
>   File ".env/lib/python3.6/site-packages/tensorflow_core/python/keras/saving/saved_model/load.py", line 93, in load
>     model._training_config))  # pylint: disable=protected-access
>   File ".env/lib/python3.6/site-packages/tensorflow_core/python/training/tracking/base.py", line 457, in _method_wrapper
>     result = method(self, *args, **kwargs)
>   File ".env/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training.py", line 340, in compile
>     self.loss, self.output_names)
>   File ".env/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training_utils.py", line 1350, in prepare_loss_functions
>     loss_functions = [get_loss_function(loss) for _ in output_names]
>   File ".env/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training_utils.py", line 1350, in <listcomp>
>     loss_functions = [get_loss_function(loss) for _ in output_names]
>   File ".env/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training_utils.py", line 1086, in get_loss_function
>     loss_fn = losses.get(loss)
>   File ".env/lib/python3.6/site-packages/tensorflow_core/python/keras/losses.py", line 1166, in get
>     return deserialize(identifier)
>   File ".env/lib/python3.6/site-packages/tensorflow_core/python/keras/losses.py", line 1157, in deserialize
>     printable_module_name='loss function')
>   File ".env/lib/python3.6/site-packages/tensorflow_core/python/keras/utils/generic_utils.py", line 210, in deserialize_keras_object
>     raise ValueError('Unknown ' + printable_module_name + ':' + object_name)
> ValueError: Unknown loss function:loss

**My understanding of the issue**

I checked in the TF code and I found the following:
- The function `deserialize_keras_object` from [generic_utils.py](https://github.com/tensorflow/tensorflow/blob/r2.0/tensorflow/python/keras/utils/generic_utils.py#L169-L218) has indeed a `custom_objects` argument
- `deserialize` from [losses.py](https://github.com/tensorflow/tensorflow/blob/r2.0/tensorflow/python/keras/losses.py#L1169-L1174) has this argument too
- `get` (from [losses.py](https://github.com/tensorflow/tensorflow/blob/r2.0/tensorflow/python/keras/losses.py#L1177-L1190)), the function that calls `deserialize` does not fills in this argument
- So that, even though I give `custom_objects` to `load_model` function, it is not passed to `deserialize_keras_object` at the end.

Could someone check this issue and implement the needed changes for this to work?

Thank you for your help!

**Comment by simonnanty** [comment]
I found a workaround: calling `load_model` with `compile=False` and compile the model separately afterwards.

However, it would be nice that this works directly, too

**Comment by ravikyram** [comment]
I have tried on colab with TF version 2.0.0rc0 ,2.0.0-dev20190909 and was able to reproduce the issue.Please, find the gist [here.](https://colab.sandbox.google.com/gist/ravikyram/3f894e9b9800a3548a414f024eecfa74/untitled169.ipynb)Thanks!

**Comment by jvishnuvardhan** [comment]
@simonnanty When you have any `custom_objects`, you can save the model and compile. Then load model with the `custom_objects`. So you need to move only one line `model.save("model/", save_format='tf')` above `model.compile`. Complete code is as follows.
```
from tensorflow import keras
from tensorflow.keras import layers

inputs = keras.Input(shape=(784,), name='digits')
x = layers.Dense(64, activation='relu', name='dense_1')(inputs)
x = layers.Dense(64, activation='relu', name='dense_2')(x)
outputs = layers.Dense(10, activation='softmax', name='predictions')(x)
model = keras.Model(inputs=inputs, outputs=outputs, name='3_layer_mlp')

# Useless custom loss here
def custom_loss(y_true, y_pred):
    return keras.backend.mean(keras.backend.square(y_true - y_pred), axis=-1)

model.save("model", save_format='tf')
model.compile(loss=custom_loss, optimizer=keras.optimizers.RMSprop())
# Here comes the bug (no bug)
new_model = keras.models.load_model('model', custom_objects={'loss': custom_loss})
```

Please check the [gist here](https://colab.sandbox.google.com/gist/jvishnuvardhan/d8e1ade42ea9493beb1c797ed3a5cb10/untitled550.ipynb). Thanks!

I am closing this issue. Please feel free to open it if the issue persists again. Thanks!

**Comment by Shubham3101** [comment]
@jvishnuvardhan, I like to save the model after training is done, therefore I have to compile it first.

**Comment by jvishnuvardhan** [comment]
@Shubham3101 Custom functions are not serializable as they are not compatible. If you want to save after training, then follow this [workaround](https://github.com/tensorflow/tensorflow/issues/32348#issuecomment-529467228). You could also get around this error by defining  a custom Metric/loss object, and overwriting the get_config() . Check the [link](https://www.tensorflow.org/beta/guide/keras/training_and_evaluation) for more details. 

There is another [similar issue](https://github.com/tensorflow/tensorflow/issues/32612) that we will use to track the progress. Thanks!

**Comment by Danfoa** [comment]
Even when inheriting the Keras Loss class this does not seems to work out of the box. 

If I am using a loss like :

```
class WeightedBinaryCrossentropy(tf.keras.losses.Loss):

def __init__(self, pos_weight, name='WeightedBinaryCrossentropy'):
    super().__init__(name=name)
    self.pos_weight = pos_weight

def call(self, y_true, y_pred):
    # For numerical stability clip predictions to log stable numbers
    y_pred = tf.keras.backend.clip(y_pred,
                                   tf.keras.backend.epsilon(),
                                   1 - tf.keras.backend.epsilon())
    # Compute weighted binary cross entropy
    wbce = y_true * -tf.math.log(y_pred) * self.pos_weight + (1 - y_true) * -tf.math.log(1 - y_pred)
    # Reduce by mean
    return tf.reduce_mean(wbce)
```

Is there a way to provide the class implementation so compilation is done automatically?

**Comment by jvishnuvardhan** [comment]
@Danfoa Please create a new issue with details related to issue and a standalone code to reproduce the issue. Thanks!

**Comment by oumazou** [comment]
how can i use the model after the loading on sample image
