### ISSUE TITLE
Distributed strategy TF2.0 rc0 error

### ISSUE THREAD

**Issue by DAEHEESHIN** [tensorflow/tensorflow#32349]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): linux
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):tf 2.0.0 rc0
- TensorFlow version (use command below):tf 2.0.0 rc
- Python version:3.6.8
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 10
- GPU model and memory: tesla v100

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**

i run training code with 4 gpus using Distributed stratage..
when i finish 1 epoch.. end of epoch.. always got the mesage.
but if i run this code in local cpu.., everythings is okay..
i don't understand what's wrlong

epoch: 0, step: 19, loss = 51.801109313964844
epoch: 0, step: 20, loss = 51.188865661621094
epoch: 0, step: 21, loss = 51.24317932128906
epoch: 0, step: 22, loss = 51.97450256347656
Traceback (most recent call last):
  File "/root/arcface_test/train_multigpu.py", line 259, in <module>
    main()
  File "/root/arcface_test/train_multigpu.py", line 211, in main
    loss = distributed_train_step(images,labels)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/eager/def_function.py", line 415, in __call__
    return self._stateless_fn(*args, **kwds)  # pylint: disable=not-callable
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/eager/function.py", line 1821, in __call__
    graph_function, args, kwargs = self._maybe_define_function(args, kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/eager/function.py", line 2147, in _maybe_define_function
    graph_function = self._create_graph_function(args, kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/eager/function.py", line 2038, in _create_graph_function
    capture_by_value=self._capture_by_value),
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/func_graph.py", line 915, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/eager/def_function.py", line 320, in wrapped_fn
    return weak_wrapped_fn().__wrapped__(*args, **kwds)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/func_graph.py", line 905, in wrapper
    raise e.ag_error_metadata.to_exception(e)
ValueError: in converted code:

    /root/arcface_test/train_multigpu.py:187 distributed_train_step  *
        per_replica_losses = strategy.experimental_run_v2(train_step, args=(images,labels))
    /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/distribute/distribute_lib.py:760 experimental_run_v2
        return self._extended.call_for_each_replica(fn, args=args, kwargs=kwargs)
    /root/arcface_test/train_multigpu.py:173 train_step  *
        prelogits,  norm_dense = model(images, training=True)
    /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/engine/base_layer.py:807 __call__
        outputs = call_fn(cast_inputs, *args, **kwargs)
    /root/arcface_test/models/model.py:36 call  *
        prelogits = self.backbone(inputs, training=training)
    /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/engine/base_layer.py:807 __call__
        outputs = call_fn(cast_inputs, *args, **kwargs)
    /root/arcface_test/backbones/L_resnet_E_IR.py:118 call  *
        x = self.conv(inputs)
    /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/engine/base_layer.py:772 __call__
        self.name)
    /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/engine/input_spec.py:213 assert_input_compatibility
        ' but received input with shape ' + str(shape))

    ValueError: Input 0 of layer conv2d is incompatible with the layer: expected axis -1 of input shape to have value 3 but received input with shape [0, 112, 112, 0]

**Describe the expected behavior**

**Code to reproduce the issue**
from __future__ import absolute_import, division, print_function, unicode_literals

import argparse
import datetime
import os
import platform
import sys
import time
import math
import tensorflow as tf
import yaml

from backbones.L_resnet_E_IR import ResNet_v1_101_IR
from data.generate_data import GenerateData
from models.model import MyModel
from valid import Valid_Data

tf.executing_eagerly()

def parse_args(argv):
    parser = argparse.ArgumentParser(description='Train face network')
    parser.add_argument('--config_path', type=str, help='path to config path', default='configs/config_local.yaml')

    args = parser.parse_args(argv)

    return args

#lr decay 설정...
def decay(step):
    if step < 100000:
        return 0.1
    if step >= 100000 and step < 160000:
        return 0.01
    if step >= 160000:
        return 0.001
def main():

    args = parse_args(sys.argv[1:])
    # logger.info(args)

    with open(args.config_path) as cfg:
        config = yaml.load(cfg, Loader=yaml.FullLoader)

    num_of_gpu = config['num_of_gpu']

    print(num_of_gpu)
    strategy = tf.distribute.MirroredStrategy()
    print ('Number of devices: {}'.format(strategy.num_replicas_in_sync))

    epoch_num = config['epoch_num']
    image_size_width = config['image_size_width']
    image_size_height = config['image_size_height']
    image_channel = config['image_channel']

    m3 = config['logits_margin3']
    s = config['logits_scale']
    below_fpr = config['below_fpr']
    learning_rate = config['learning_rate']
    batch_size = config['batch_size']

    with strategy.scope():

        gd = GenerateData(config)

        train_data, cat_num = gd.get_train_data()

        print(cat_num)

        model = MyModel(ResNet_v1_101_IR, embedding_size=config['embedding_size'], classes=cat_num)

        #model.build((None, image_size_height , image_size_width, image_channel))

        valid_data = gd.get_val_data(num=config['valid_num'], valid_data_type=config['valid_data_type'])

        ckpt_dir = os.path.expanduser(config['ckpt_dir'])

        summary_dir = os.path.expanduser(config['summary_dir'])
        current_time = datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
        train_log_dir = os.path.join(summary_dir, current_time, 'train')
        valid_log_dir = os.path.join(summary_dir, current_time, 'valid')
        # self.graph_log_dir = os.path.join(summary_dir, current_time, 'graph')

        if platform.system() == 'Windows':
            train_log_dir = train_log_dir.replace('/', '\\')
            valid_log_dir = valid_log_dir.replace('/', '\\')
            # self.graph_log_dir = self.graph_log_dir.replace('/', '\\')

        # self.train_summary_writer = tf.summary.create_file_writer(train_log_dir)
        # self.valid_summary_writer = tf.summary.create_file_writer(valid_log_dir)
        train_summary_writer = tf.compat.v2.summary.create_file_writer(train_log_dir)
        valid_summary_writer = tf.compat.v2.summary.create_file_writer(valid_log_dir)

        #self.graph_writer = tf.compat.v2.summary.create_file_writer(self.graph_log_dir)
        #tf.compat.v2.summary.trace_on(graph=True, profiler=True)
        #with self.graph_writer.as_default():
        #    tf.compat.v2.summary.trace_export(name="graph_trace", step=0, profiler_outdir=graph_log_dir)

        optimizer = config['optimizer']

        #boundaries = [2000, 100000, 1000000, 160000]
        #values = [0.05, 0.01, 0.001, 0.005, 0.0001]
        #learning_rate_fn = tf.keras.optimizers.schedules.PiecewiseConstantDecay(
        #    boundaries, values)

        if optimizer == 'ADADELTA':
            optimizer = tf.keras.optimizers.Adadelta(learning_rate)
        elif optimizer == 'ADAGRAD':
            optimizer = tf.keras.optimizers.Adagrad(learning_rate)
        elif optimizer == 'ADAM':
            optimizer = tf.keras.optimizers.Adam(learning_rate)
        elif optimizer == 'ADAMAX':
            optimizer = tf.keras.optimizers.Adamax(learning_rate)
        elif optimizer == 'FTRL':
            optimizer = tf.keras.optimizers.Ftrl(learning_rate)
        elif optimizer == 'NADAM':
            optimizer = tf.keras.optimizers.Nadam(learning_rate)
        elif optimizer == 'RMSPROP':
            optimizer = tf.keras.optimizers.RMSprop(learning_rate)
        elif optimizer == 'SGD':
            optimizer = tf.keras.optimizers.SGD(learning_rate, momentum=0.9)
            #optimizer = tf.compat.v1.train.MomentumOptimizer(learning_rate, momentum=0.90)
        else:
            raise ValueError('Invalid optimization algorithm')

        ckpt = tf.train.Checkpoint(backbone=model.backbone, model=model, optimizer=optimizer)
        ckpt_manager = tf.train.CheckpointManager(ckpt, ckpt_dir, max_to_keep=5, checkpoint_name='mymodel')

        if ckpt_manager.latest_checkpoint:
            ckpt.restore(ckpt_manager.latest_checkpoint)
            print("Restored from {}".format(ckpt_manager.latest_checkpoint))
        else:
            print("Initializing from scratch.")
        loss_object = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True,reduction=tf.losses.Reduction.NONE)

        def arcface_loss_multi(x, normx_cos, labels, batch_size, m=0.5, s=64):
            norm_x = tf.norm(x, axis=1, keepdims=True)
            cos_theta = normx_cos / norm_x
            theta = tf.acos(cos_theta)
            mask = tf.one_hot(labels, depth=normx_cos.shape[-1])
            zeros = tf.zeros_like(mask)
            cond = tf.where(tf.greater(theta + m, math.pi), zeros, mask)
            cond = tf.cast(cond, dtype=tf.bool)
            m1_theta_plus_m3 = tf.where(cond, theta + m, theta)
            cos_m1_theta_plus_m3 = tf.cos(m1_theta_plus_m3)
            prelogits = tf.where(cond, cos_m1_theta_plus_m3, cos_m1_theta_plus_m3) * s

            loss = loss_object(labels, prelogits)

            #return tf.reduce_sum(loss) * (1. / batch_size)
            return tf.nn.compute_average_loss(loss, global_batch_size=batch_size)
        #test_accuracy = tf.keras.metrics.SparseCategoricalAccuracy(
        #    "test_accuracy", dtype=tf.float32)

        def train_step(images,labels):

            with tf.GradientTape() as tape:
                prelogits,  norm_dense = model(images, training=True)

                loss = arcface_loss_multi(prelogits, norm_dense, labels, batch_size, m3, s)

            gradients = tape.gradient(loss, model.trainable_variables)

            optimizer.apply_gradients(zip(gradients, model.trainable_variables))
            return loss

        @tf.function
        def distributed_train_step(images,labels):
            per_replica_losses = strategy.experimental_run_v2(train_step, args=(images,labels))
            return strategy.reduce(tf.distribute.ReduceOp.SUM, per_replica_losses, axis=None)

        train_dist_dataset = strategy.experimental_distribute_dataset(train_data)

        vd = Valid_Data(model, valid_data)
        max_step = 0
        for epoch in range(epoch_num):

            start = time.time()
            # Train
            print("Starting epoch {}".format(epoch))
            total_loss = 0.0
            num_batches = 0

            for step, (images, labels) in enumerate(train_dist_dataset):

                if step > max_step:
                    max_step = step

                optimizer.learning_rate = decay((max_step*epoch) + step)

                loss = distributed_train_step(images,labels)

                with train_summary_writer.as_default():
                    tf.compat.v2.summary.scalar('loss', loss, step=((max_step*epoch) + step))

                    print('epoch: {}, step: {}, loss = {}'.format(epoch, ((max_step*epoch) + step), loss))
                total_loss += loss
                num_batches += 1

            train_loss = total_loss / num_batches

            print("Training loss: {:0.4f}".format(train_loss))

            with train_summary_writer.as_default():
                tf.compat.v2.summary.scalar('loss_epoch', train_loss, step=epoch)

            #if epoch % 1 == 0:
            # valid

            #with tf.device('/CPU:0'):
            '''
            acc, p, tpr, fpr, thresh, acc_fpr, p_fpr, tpr_fpr, thresh_fpr = vd.get_metric(below_fpr)

            with valid_summary_writer.as_default():
                tf.compat.v2.summary.scalar('acc', acc, step=epoch)
                tf.compat.v2.summary.scalar('p', p, step=epoch)
                tf.compat.v2.summary.scalar('tpr', tpr, step=epoch)
                tf.compat.v2.summary.scalar('fpr', fpr, step=epoch)
                tf.compat.v2.summary.scalar('thresh', thresh, step=epoch)
                tf.compat.v2.summary.scalar('acc_fpr', acc_fpr, step=epoch)
                tf.compat.v2.summary.scalar('p_fpr', p_fpr, step=epoch)
                tf.compat.v2.summary.scalar('tpr_fpr', tpr_fpr, step=epoch)
                tf.compat.v2.summary.scalar('thresh_fpr', thresh_fpr, step=epoch)
            print('epoch: {}, acc: {:.3f}, p: {:.3f}, r=tpr: {:.3f}, fpr: {:.3f} \n'
                  ',thresh: {:.3f}fix fpr <= {}, acc: {:.3f}, p: {:.3f}, r=tpr: {:.3f}, thresh: {:.3f}'
                  .format(epoch, acc, p, tpr, fpr, thresh, below_fpr, acc_fpr, p_fpr, tpr_fpr, thresh_fpr))
            '''
        # ckpt
        # if epoch % 5 == 0:
            save_path = ckpt_manager.save()
            print('Saving checkpoint for epoch {} at {}'.format(epoch, save_path))

            print('Time taken for epoch {} is {} sec\n'.format(epoch, time.time() - start))

if __name__ == '__main__':

    main()

Provide a reproducible test case that is the bare minimum necessary to generate the problem.

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by ymodak** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.
