### ISSUE TITLE
[Tensorflow 2.0.0-rc0] Hyperparameter tuning with Keras fails 

### ISSUE THREAD

**Issue by flooreigenhuis** [tensorflow/tensorflow#32343]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): iOs 10.14.6, but trying to do hyperparameter tuning on Google AI platform
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): Tensorflow 2.0.0-rc0
- Python version: 3.5
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
When I try to run a hyperparameter tuning job on AI Platform, the job fails. I use tensorflow callbacks: `callbacks = [
		keras.callbacks.TensorBoard(log_dir=params["output_dir"],
									   histogram_freq=1)]`. Tensorboard runs just fine. However, I get the error: 
```AttributeError: module 'tensorflow._api.v2.train' has no attribute 'SummaryWriter' ```. Is there another way in Tensorflow 2.0 to use hyperparameter tuning?

**Describe the expected behavior**
Able to do hyperparameter tuning. 

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

Just simply trying to do hyperparameter tuning on AI platform with the callback in the model above. 

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

```Hyperparameter Tuning Trial #1 Failed before any other successful trials were completed. The failed trial had parameters: amsgrad=0, batch_size=16, beta_1=0.85743346214294436, learning_rate=0.037045532170408492, . The trial's error message was: The replica master 0 exited with a non-zero status of 1. Traceback (most recent call last): [...] During handling of the above exception, another exception occurred: Traceback (most recent call last): File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main "__main__", mod_spec) File "/usr/lib/python3.5/runpy.py", line 85, in _run_code exec(code, run_globals) File "/root/.local/lib/python3.5/site-packages/model/task.py", line 11, in <module> from . import model File "/root/.local/lib/python3.5/site-packages/model/model.py", line 7, in <module> import tensorflow as tf File "<frozen importlib._bootstrap>", line 969, in _find_and_load File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked File "<frozen importlib._bootstrap>", line 664, in _load_unlocked File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible File "/usr/local/lib/python3.5/dist-packages/wrapt/importer.py", line 158, in load_module notify_module_loaded(module) File "/usr/local/lib/python3.5/dist-packages/wrapt/decorators.py", line 440, in _synchronized return wrapped(*args, **kwargs) File "/usr/local/lib/python3.5/dist-packages/wrapt/importer.py", line 136, in notify_module_loaded hook(module) File "/var/sitecustomize/sitecustomize.py", line 192, in run_post_import_hook self.new_add_summary) File "/usr/local/lib/python3.5/dist-packages/wrapt/wrappers.py", line 827, in wrap_function_wrapper return wrap_object(module, name, FunctionWrapper, (wrapper,)) File "/usr/local/lib/python3.5/dist-packages/wrapt/wrappers.py", line 773, in wrap_object (parent, attribute, original) = resolve_path(module, name) File "/usr/local/lib/python3.5/dist-packages/wrapt/wrappers.py", line 765, in resolve_path original = getattr(original, attribute) File "/root/.local/lib/python3.5/site-packages/tensorflow_core/python/util/module_wrapper.py", line 169, in __getattr__ attr = getattr(self._tfmw_wrapped_module, name) AttributeError: module 'tensorflow._api.v2.train' has no attribute 'SummaryWriter' To find out more about why your job exited please check the logs: https://console.cloud.google.com/logs/viewer?project=675828645530&resource=ml_job%2Fjob_id%2Frgs_ml_hyper_v1_1567614786&advancedFilter=resource.type%3D%22ml_job%22%0Aresource.labels.job_id%3D%22rgs_ml_hyper_v1_1567614786%22```

**Comment by gowthamkpr** [comment]
Can you please refer to the following [link](https://www.tensorflow.org/tensorboard/r2/get_started) and also this [link](https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/summary/SummaryWriter) and let me  know if it helps. Can you also please share a minimal reproducible code as I am unable to figure out whats exactly causing the exception here. Thanks!

**Comment by flooreigenhuis** [comment]
@gowthamkpr Yes, of course! The links didn't help. I wrote a custom model but the problem also persists when trying to do hyperparameter tuning on AI Platform using [this](https://colab.research.google.com/github/GoogleCloudPlatform/cloudml-samples/blob/master/notebooks/tensorflow/getting-started-keras.ipynb#scrollTo=K0UXLWaBJnrY) tutorial. As I said, it's weird because Tensorboard runs just fine but it seems the keras tensorboard callbacks for HP tuning don't seem to work because there is no module SummaryWriter in Tensorflow 2.0?

**Comment by flooreigenhuis** [comment]
I figured out that the error was most likely due to me trying to save a tensorflow 2.0 model on AI platform while AI platform doesn't support tensorflow 2.0 yet.
