### ISSUE TITLE
AttributeError: 'RefVariable' object has no attribute 'ref'

### ISSUE THREAD

**Issue by debadityamandal** [tensorflow/tensorflow#32340]
with tf.device('/cpu:0'):
  activations = tf.Variable(tf.zeros([ACT_LEN, FLAGS.wvs, 1], FTYPE), name='activations',
                            trainable=False)
logits = batch_logits(i_ss, activations.ref())
AttributeError: 'RefVariable' object has no attribute 'ref'

**Comment by oanush** [comment]
@debadityamandal ,
Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version.
Can you share a simple and standalone code to reproduce the issue?Thanks!

**Comment by debadityamandal** [comment]
@oanush ,
I am executing the code in google colab and tensorflow version is 1.14.0.This is the code snippet.
Thank You

**Comment by oanush** [comment]
@debadityamandal ,
Thank you for the response,but I don't see the code attached.

**Comment by oanush** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
