### ISSUE TITLE
[Tensorflow 2.0.0-rc0] Cannot save model on AI Platform: Not JSON Serializable

### ISSUE THREAD

**Issue by flooreigenhuis** [tensorflow/tensorflow#32344]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes 
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Google AI Platform
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): binary 
- TensorFlow version (use command below): Tensorflow 2.0.0-rc0
- Python version: 3.5
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
When I try to save a trained model (Keras) locally with `keras.models.save_model(model, params['output_dir'] + '/savedmodel', save_format='tf')` it runs like expected. However, when I try to do the same on AI platform, it fails: `Not JSON Serializable`.

**Describe the expected behavior**
To be able to save a model on AI platform. 

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

```The replica master 0 exited with a non-zero status of 1. Traceback (most recent call last): [...] File "/root/.local/lib/python3.5/site-packages/model/model.py", line 204, in start train_and_evaluate_model(data, params) File "/root/.local/lib/python3.5/site-packages/model/model.py", line 153, in train_and_evaluate_model '/savedmodel', save_format='tf') File "/root/.local/lib/python3.5/site-packages/tensorflow_core/python/keras/saving/save.py", line 112, in save_model signatures) File "/root/.local/lib/python3.5/site-packages/tensorflow_core/python/keras/saving/saved_model/save.py", line 92, in save save_lib.save(model, filepath, signatures) File "/root/.local/lib/python3.5/site-packages/tensorflow_core/python/saved_model/save.py", line 874, in save saveable_view, asset_info.asset_index) File "/root/.local/lib/python3.5/site-packages/tensorflow_core/python/saved_model/save.py", line 629, in _serialize_object_graph _write_object_proto(obj, obj_proto, asset_file_def_index) File "/root/.local/lib/python3.5/site-packages/tensorflow_core/python/saved_model/save.py", line 668, in _write_object_proto metadata=obj._tracking_metadata) File "/root/.local/lib/python3.5/site-packages/tensorflow_core/python/keras/engine/training.py", line 2839, in _tracking_metadata metadata = json.loads(super(Model, self)._tracking_metadata) File "/root/.local/lib/python3.5/site-packages/tensorflow_core/python/keras/engine/base_layer.py", line 2410, in _tracking_metadata return json.dumps(metadata, default=serialization.get_json_type) File "/usr/lib/python3.5/json/__init__.py", line 237, in dumps **kw).encode(obj) File "/usr/lib/python3.5/json/encoder.py", line 198, in encode chunks = self.iterencode(o, _one_shot=True) File "/usr/lib/python3.5/json/encoder.py", line 256, in iterencode return _iterencode(o, 0) File "/root/.local/lib/python3.5/site-packages/tensorflow_core/python/util/serialization.py", line 68, in get_json_type raise TypeError('Not JSON Serializable:', obj) TypeError: ('Not JSON Serializable:', b'011') To find out more about why your job exited please check the logs: https://console.cloud.google.com/logs/viewer?project=675828645530&resource=ml_job%2Fjob_id%2Frgs_ml_v1_1567614514&advancedFilter=resource.type%3D%22ml_job%22%0Aresource.labels.job_id%3D%22rgs_ml_v1_1567614514%22```

**Comment by gadagashwini** [comment]
@flooreigenhuis,
In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thanks!

**Comment by flooreigenhuis** [comment]
@gadagashwini hi! Yes, of course. Although I made a custom model, you can find the tutorial I followed [here](https://colab.research.google.com/github/GoogleCloudPlatform/cloudml-samples/blob/master/notebooks/tensorflow/getting-started-keras.ipynb#scrollTo=mHF9VCProKJN) but then with custom code. The tensorflow version I used is version 2.0 instead of 1.x of course. Is there a known problem with serializing keras tensorflow models?

**Comment by gadagashwini** [comment]
@flooreigenhuis, Will it be possible to provide the colab link with your custom code to replicate the issue reported here. It will indeed help us to move faster.Thanks!

**Comment by gadagashwini** [comment]
@flooreigenhuis, Any update on reproducible code snippet. Thanks!

**Comment by flooreigenhuis** [comment]
@gadagashwini Sorry for the late response! I figured out that the error was most likely due to me trying to save a tensorflow 2.0 model on AI platform while AI platform doesn't support tensorflow 2.0 yet. I reverted my model back to tensorflow 1.14 and everything worked fine!
