### ISSUE TITLE
[TPU][TF 1.14]Can not reload the trained model for training on Colab TPU.

### ISSUE THREAD

**Issue by rishabhsahrawat** [tensorflow/tensorflow#32359]
I trained a model on Colab TPU and then saved it using callbacks in `model.fit()`. Now, I want to continue training model after restoring it from the last checkpoint saved as h5 format. This file has layer weights and optimizer weights i.e. also the architecture. On loading the model inside `TPUStrategy scope()` as follows-
````
TPU_WORKER = 'grpc://' + os.environ['COLAB_TPU_ADDR']# Name or Address of TPU
resolver = tf.contrib.cluster_resolver.TPUClusterResolver(TPU_WORKER)
tf.contrib.distribute.initialize_tpu_system(resolver)
strategy = tf.contrib.distribute.TPUStrategy(resolver)

with strategy.scope():
  saved_model_file_name = os.path.join("/content/gdrive/My Drive/data", 'GDmodel09.h5')# saved model is on my Google Drive
  model = tf.keras.models.load_model(saved_model_file_name)
````
the last line throws following error-
`AttributeError: 'NoneType' object has no attribute 'merge_call'`
However, if I load the model outside scope then it gets loaded without any error.
Please help. Thank you!

**Comment by gadagashwini** [comment]
@rishabhsahrawat, Please provide the saved h5 model to reproduce the issue. Thanks!

**Comment by rishabhsahrawat** [comment]
@gadagashwini thank you for your reply. Can we share it privately?

**Comment by gadagashwini** [comment]
I could able to reproduce the issue with Tensorflow 1.14.0 on Colab. Please see the colab [gist](https://colab.sandbox.google.com/gist/gadagashwini/a1e60ce8884f65a15ad38b169bddfd46/untitled136.ipynb). Thanks!

**Comment by captain-pool** [comment]
Hi!
Can you try loading the modele outside Cross Replica Context? I mean, outside strategy.scope() ?

Checkout point #2 of https://www.tensorflow.org/api_docs/python/tf/distribute/get_replica_context#note_that_execution

**Comment by rishabhsahrawat** [comment]
Hi @captain-pool , as I already mentioned, this model can be loaded easily outside `scope()`, but then it doesn't use TPU and starts training on CPU which very very slow.
I am sorry, I did not understand how your provided link is helpful. Could you please elaborate a bit?
Thank you!

**Comment by rishabhsahrawat** [comment]
Hello @jvishnuvardhan @gadagashwini , any updates on this issue.?
Or is there any other way which I can try for reloading the saved model on Colab TPU?. I just want to train the model for near around 30 epochs but bc of the time limitation on Colab, I can only train until 13-14 Epochs. Please help, I am stuck. 
Thank you again.
-Rishabh Sahrawat

**Comment by srihari-humbarwadi** [comment]
As a workaround, you can you tf.train.saver to save and restore models. I have been using this for quite some time. 
```
    model_checkpoint_path = 'gs:<bucket name>/ckpt'
    saver = tf.train.Saver(model.variables)
    sess = K.get_session()
    callback_list = [
        tf.keras.callbacks.LambdaCallback(on_epoch_end=lambda epoch, logs : \
                                          saver.save(sess,
                                                     model_checkpoint_path,
                                                     global_step=epoch+1))
    ]

with strategy.scope():
    latest_checkpoint = tf.train.latest_checkpoint(''gs:<bucket name>')
    resume_from = 0
    if latest_checkpoint:
        resume_from = int(latest_checkpoint.split('/')[-1].split('-')[-1])
        saver.restore(sess, latest_checkpoint)
    model.fit(train_dataset,
              epochs=EPOCHS,
              initial_epoch=resume_from,
              steps_per_epoch=training_steps,
              validation_data=val_dataset,
              validation_steps=val_steps,
              validation_freq=5,
              callbacks=callback_list)
```

**Comment by rishabhsahrawat** [comment]
Hi @srihari-humbarwadi , since I am using Google TPU, how to get bucket name?

**Comment by rishabhsahrawat** [comment]
Hi @srihari-humbarwadi , where do I define the actual model structure? inside the scope or outside?

**Comment by srihari-humbarwadi** [comment]
Inside the scope

**Comment by rishabhsahrawat** [comment]
okay, so this is how I am defining it. But on executing I am receving an error at the end of epoch in `calbacks` inside `.fit()`

````
model_checkpoint_path = os.path.join("/content/gdrive/My Drive/data/",'model_ckpt')
sess = K.get_session()

#steps = int(16450928/BATCH_SIZE)
steps = 20
print ('# of steps: ',steps)
with tf.Session() as sess:
  sess.run(init_op)
with strategy.scope():
  model = tf.keras.Sequential()
  model.add(tf.keras.layers.Embedding(vocab_size, 150, input_length = 4))
  model.add(tf.keras.layers.Bidirectional(tf.keras.layers.LSTM(128,dropout = 0.7, recurrent_dropout = 0.7,kernel_regularizer = keras.regularizers.l2(0.00001))))
  model.add(tf.keras.layers.Dense(685731, activation='softmax'))
  model.compile(optimizer=tf.keras.optimizers.Adam(), 
                loss='sparse_categorical_crossentropy',
                metrics=['accuracy'])
  saver = tf.train.Saver(model.variables)
  callback_list = [
      tf.keras.callbacks.LambdaCallback(on_epoch_end=lambda epoch, logs : saver.save(sess, model_checkpoint_path, global_step=epoch+1))
  ]
  latest_checkpoint = tf.train.latest_checkpoint(model_checkpoint_path)
  resume_from = 0
  if latest_checkpoint:
      resume_from = int(latest_checkpoint.split('/')[-1].split('-')[-1])
      saver.restore(sess, latest_checkpoint)
  print (model.summary())
  model.fit(all_encoded_data,
            epochs=30,
            initial_epoch=resume_from,
            steps_per_epoch=steps,
            callbacks=callback_list, validation_freq=1)
````

**Comment by srihari-humbarwadi** [comment]
What's the error? works fine for me on 1.14.0

**Comment by rishabhsahrawat** [comment]
Following is the error I am receiving. As I said, it originates from `callbacks` in `.fit()`-
````
InvalidArgumentError: No OpKernel was registered to support Op 'TPUReplicatedInput' used by node input0 (defined at <ipython-input-2-d6d8345ba1f0>:195) with these attrs: [N=8, T=DT_INT32]
Registered devices: [CPU, XLA_CPU]
Registered kernels:
  <no registered kernels>

	 [[input0]]
````

**Comment by rishabhsahrawat** [comment]
Hello @jvishnuvardhan @jhseu , any updates on this issue? At least please confirm that this is coming from TF's end!?

**Comment by ismael-elatifi** [comment]
> Hello @jvishnuvardhan @jhseu , any updates on this issue? At least please confirm that this is coming from TF's end!?

I opened a related issue (more general because not only for TPU) : 
https://github.com/tensorflow/tensorflow/issues/38423

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.
