### ISSUE TITLE
Does tf consider to support mac os + amd gpu?

### ISSUE THREAD

**Issue by jielyu** [tensorflow/tensorflow#32358]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Mac OS, Mojave, 10.14.6
- TensorFlow installed from (source or binary): source
- TensorFlow version: 2.0.0-rc0
- Python version: python 3.7

**Describe the problem**
I try to compile tensorflow from source code with opencl, while it requires computecpp support. However, the official website of computecpp shows that it does not mac os.
Thus, as described by tf official docs, the gpu version cannot run on mac os. 
I just want to ask whether tf considers to add gpu support for mac os, now I can only develop models by keras with plaidml backend, or run tf on cpu.

**Comment by mihaimaruseac** [comment]
I think @gunan is a better assignee here as this is a request for a new architecture.

**Comment by jielyu** [comment]
> I think @gunan is a better assignee here as this is a request for a new architecture.

@mihaimaruseac  thank you

**Comment by gunan** [comment]
Our GPU support runs through CUDA library, which is supported by NVIDIA themselves.
Until there is an AMD (ROCM)or community supported (for example OpenCL, SYCL) solution for macos, we cannot support this ourselves.

**Comment by bgbutler** [comment]
Use the library PlaidML; works fine for more models on a Mac OS with AMD GPU.
