### ISSUE TITLE
Issue with basic_classification tutorial

### ISSUE THREAD

**Issue by nfgallimore** [tensorflow/tensorflow#32353]
## URL(s) with the issue:

https://colab.research.google.com/github/tensorflow/docs/blob/r2.0rc/site/en/tutorials/keras/basic_classification.ipynb#scrollTo=9ODch-OFCaW4&line=2&uniqifier=1
## Description of issue (what needs changing):

I was browsing the beginner tutorial for basic_classification. It was at the above link. In the section **Setup the Layers** it is throwing a warning when running:

`WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/init_ops.py:1251: calling VarianceScaling.__init__ (from tensorflow.python.ops.init_ops) with dtype is deprecated and will be removed in a future version.
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor`

**Comment by gadagashwini** [comment]
@nfgallimore,
Deprecation messages are needed to inform people who want to use an actual version of TensorFlow what is going to happen in the future, and give them time to adapt.

**Comment by nfgallimore** [comment]
Yes so the tutorial shouldn't use deprecated code.

**Comment by nfgallimore** [comment]
I was just expecting some sort of response from that line of code for *Setup the Layers* if none is supposed to occur then I could see this being okay. But the deprecated message just leads to confusion, so I would suggest to update the tutorial to not use deprecated functions.

**Comment by ymodak** [comment]
@nfgallimore The google colab hosts TF version 1.15 currently. In future we are moving to TF 2.X workflow therefore if you execute the same tutorial with TF 2.0 RC1 version you won't see those deprecation warnings.
The current tutorial contains the updated TF code and alerts you with the deprecated functionality from TF 1.X
