### ISSUE TITLE
Keras 'fit_generator' - Zip object is not considered generator or sequence in 

### ISSUE THREAD

**Issue by kevinkepp** [tensorflow/tensorflow#32357]
**Description**
Keras Model `fit_generator` does not work with `zip` objects.
I followed the image segmentation example from https://keras.io/preprocessing/image/ of loading and transforming images and masks together and then training a model with `fit_generator`.

I'm getting `AttributeError: 'zip' object has no attribute 'shape'` (see stack trace below)

**System information**
- TensorFlow version: 1.14.0 and 2.0.0-RC
- Python version: 3.7.3
- Occurs on both CPU and GPU execution

**Code to reproduce the issue**
Code taken from https://keras.io/preprocessing/image/

```
# we create two instances with the same arguments
data_gen_args = dict(featurewise_center=True,
                     featurewise_std_normalization=True,
                     rotation_range=90,
                     width_shift_range=0.1,
                     height_shift_range=0.1,
                     zoom_range=0.2)
image_datagen = ImageDataGenerator(**data_gen_args)
mask_datagen = ImageDataGenerator(**data_gen_args)

# Provide the same seed and keyword arguments to the fit and flow methods
seed = 1
image_datagen.fit(images, augment=True, seed=seed)
mask_datagen.fit(masks, augment=True, seed=seed)

image_generator = image_datagen.flow_from_directory(
    'data/images',
    class_mode=None,
    seed=seed)

mask_generator = mask_datagen.flow_from_directory(
    'data/masks',
    class_mode=None,
    seed=seed)

# combine generators into one which yields image and masks
train_generator = zip(image_generator, mask_generator)

model.fit_generator(
    train_generator,
    steps_per_epoch=2000,
    epochs=50)
```

**Stacktrace**
```
File "/home/kevin/dev/code/image-gen/src/train.py", line 47, in main
    validation_steps=1)
  File "/home/kevin/dev/venvs/image-gen/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training.py", line 1303, in fit_generator
    steps_name='steps_per_epoch')
  File "/home/kevin/dev/venvs/image-gen/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training_generator.py", line 144, in model_iteration
    shuffle=shuffle)
  File "/home/kevin/dev/venvs/image-gen/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training_generator.py", line 477, in convert_to_generator_like
    num_samples = int(nest.flatten(data)[0].shape[0])
AttributeError: 'zip' object has no attribute 'shape'
```

**Workaround**:
Create generator from zip object
`train_generator = (pair for pair in zip(image_generator, mask_generator))`

**Comment by MostafaGazar** [comment]
I think `fit_generator` used to support python iterators and it no longer does, I believe that changed in v1.13. 

This doc page seem to be out of date: https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/keras/preprocessing/image/ImageDataGenerator

**Comment by YasineNifa** [comment]
hello,

Please did you solve this error
because I am getting the same error while I excute this function
`model.fit_generator(train_generator, steps_per_epoch=135, epochs=20, validation_data=validation_generator,validation_steps=16, callbacks=callbacks, workers=2)`

**Comment by kevinkepp** [comment]
@Loner233 @YasineNifa 
Have you tried the workaround that I mentioned above?
`train_generator = (pair for pair in zip(image_generator, mask_generator))`

**Comment by Loner233** [comment]
> @Loner233 @YasineNifa
> Have you tried the workaround that I mentioned above?
> `train_generator = (pair for pair in zip(image_generator, mask_generator))`

Yes, I tried, and solved my problem. This created a python generator which should work, but I still dont know what changes this framework makes that causes this problem

**Comment by joshleiph** [comment]
I've also ran into this problem as well. I tried the zip workaround and it does seem to fix that problem when using model.fit_generator(). But now the error I am getting from model.fit_generator() is:

Error when checking model target: the list of Numpy arrays that you are passing to your model is not the size the model expected. Expected to see 1 array(s), but instead got the following list of 2 arrays

I believe this is because the batches from the zipped generator are adding an extra array onto it for some reason. I am not sure how to fix this issue..

**Comment by mostafafazeli** [comment]
Hi. While implementing the codes above, I faced to the following error;

ValueError: Layer sequential expects 1 inputs, but it received 2 input tensors. Inputs received: [<tf.Tensor 'IteratorGetNext:0' shape=(None, None, None, None) dtype=float32>, <tf.Tensor 'IteratorGetNext:1' shape=(None, None) dtype=float32>]

Can some one help solve this issue?

**Comment by odinsbane** [comment]
The amount of work this will take to suddenly migrate my api from fit_generator to fit is too much. I am definitely recommending moving away from tensorflow / keras.

**Comment by saikumarchalla** [comment]
Closing this issue since the original issue was resolved.  Please feel free to reopen the issue  if necessary.
@mostafafazeli  @joshleiph  Could you please open the new issues and we can track it separately. Thanks!
