### ISSUE TITLE
Error building tensorflow graph transform tools from source using bazel

### ISSUE THREAD

**Issue by rajatpaliwal** [tensorflow/tensorflow#32363]
**System information**
**- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):**
Microsoft Windows [Version 10.0.17763.615]
- **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:**
No
- **TensorFlow installed from (source or binary):**
Source
- TensorFlow version:

- **Python version**:
3.6
- **Installed using virtualenv? pip? conda?:**
No
- **Bazel version (if compiling from source):**
0.26.1
- GCC/Compiler version (if compiling from source):

- CUDA/cuDNN version:
10.1/7
- GPU model and memory:
Nvidia GeForce GTX 1050, 10123MB
**Describe the problem**
Trying to use tensorflow graph transform tools by building it using bazel. Configuration is done fine, but while building it using the command :
`bazel build tensorflow/tools/graph_transforms:transform_graph`

**receiving the error**;
`INFO: Options provided by the client:
  Inherited 'common' options: --isatty=1 --terminal_columns=120
INFO: Options provided by the client:
  'build' options: --python_path=C:/Windows/system32/python.exe
INFO: Reading rc options for 'build' from c:\users\rajat\tensorflow\.bazelrc:
  'build' options: --apple_platform_type=macos --define framework_shared_object=true --define open_source_build=true --define=use_fast_cpp_protos=true --define=allow_oversize_protos=true --spawn_strategy=standalone --strategy=Genrule=standalone -c opt --cxxopt=-std=c++14 --host_cxxopt=-std=c++14 --announce_rc --define=grpc_no_ares=true --define=PREFIX=/usr --define=LIBDIR=$(PREFIX)/lib --define=INCLUDEDIR=$(PREFIX)/include
INFO: Reading rc options for 'build' from c:\users\rajat\tensorflow\.tf_configure.bazelrc:
  'build' options: --action_env PYTHON_BIN_PATH=C:/Windows/system32/python.exe --action_env PYTHON_LIB_PATH=C:/Users/Rajat/AppData/Local/Programs/Python/Python36/lib/site-packages --python_path=C:/Windows/system32/python.exe --action_env CUDA_TOOLKIT_PATH=C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.1 --action_env TF_CUDA_COMPUTE_CAPABILITIES=6.1 --config=cuda --config monolithic --copt=-w --host_copt=-w --copt=-DWIN32_LEAN_AND_MEAN --host_copt=-DWIN32_LEAN_AND_MEAN --copt=-DNOGDI --host_copt=-DNOGDI --verbose_failures --distinct_host_configuration=false --define=override_eigen_strong_inline=true --action_env TF_CONFIGURE_IOS=0
INFO: Found applicable config definition build:cuda in file c:\users\rajat\tensorflow\.bazelrc: --config=using_cuda --define=using_cuda_nvcc=true
INFO: Found applicable config definition build:using_cuda in file c:\users\rajat\tensorflow\.bazelrc: --define=using_cuda=true --action_env TF_NEED_CUDA=1 --crosstool_top=@local_config_cuda//crosstool:toolchain
INFO: Found applicable config definition build:monolithic in file c:\users\rajat\tensorflow\.bazelrc: --define framework_shared_object=false
INFO: Call stack for the definition of repository 'local_config_cuda' which is a cuda_configure (rule definition at C:/users/rajat/tensorflow/third_party/gpus/cuda_configure.bzl:1268:18):
 - C:/users/rajat/tensorflow/tensorflow/workspace.bzl:70:5
 - C:/users/rajat/tensorflow/WORKSPACE:27:1
ERROR: An error occurred during the fetch of repository 'local_config_cuda':
   Traceback (most recent call last):
        File "C:/users/rajat/tensorflow/third_party/gpus/cuda_configure.bzl", line 1266
                _create_local_cuda_repository(repository_ctx)
        File "C:/users/rajat/tensorflow/third_party/gpus/cuda_configure.bzl", line 988, in _create_local_cuda_repository
                _get_cuda_config(repository_ctx)
        File "C:/users/rajat/tensorflow/third_party/gpus/cuda_configure.bzl", line 714, in _get_cuda_config
                find_cuda_config(repository_ctx, ["cuda", "cudnn"])
        File "C:/users/rajat/tensorflow/third_party/gpus/cuda_configure.bzl", line 694, in find_cuda_config
                auto_configure_fail(("Failed to run find_cuda_config...))
        File "C:/users/rajat/tensorflow/third_party/gpus/cuda_configure.bzl", line 325, in auto_configure_fail
                fail(("\n%sCuda Configuration Error:%...)))

Cuda Configuration Error: Failed to run find_cuda_config.py:
ERROR: Skipping 'tensorflow/tools/graph_transforms:transform_graph': error loading package 'tensorflow/tools/graph_transforms': in C:/users/rajat/tensorflow/tensorflow/tensorflow.bzl: Encountered error while reading extension file 'cuda/build_defs.bzl': no such package '@local_config_cuda//cuda': Traceback (most recent call last):
        File "C:/users/rajat/tensorflow/third_party/gpus/cuda_configure.bzl", line 1266
                _create_local_cuda_repository(repository_ctx)
        File "C:/users/rajat/tensorflow/third_party/gpus/cuda_configure.bzl", line 988, in _create_local_cuda_repository
                _get_cuda_config(repository_ctx)
        File "C:/users/rajat/tensorflow/third_party/gpus/cuda_configure.bzl", line 714, in _get_cuda_config
                find_cuda_config(repository_ctx, ["cuda", "cudnn"])
        File "C:/users/rajat/tensorflow/third_party/gpus/cuda_configure.bzl", line 694, in find_cuda_config
                auto_configure_fail(("Failed to run find_cuda_config...))
        File "C:/users/rajat/tensorflow/third_party/gpus/cuda_configure.bzl", line 325, in auto_configure_fail
                fail(("\n%sCuda Configuration Error:%...)))

Cuda Configuration Error: Failed to run find_cuda_config.py:
WARNING: Target pattern parsing failed.
ERROR: error loading package 'tensorflow/tools/graph_transforms': in C:/users/rajat/tensorflow/tensorflow/tensorflow.bzl: Encountered error while reading extension file 'cuda/build_defs.bzl': no such package '@local_config_cuda//cuda': Traceback (most recent call last):
        File "C:/users/rajat/tensorflow/third_party/gpus/cuda_configure.bzl", line 1266
                _create_local_cuda_repository(repository_ctx)
        File "C:/users/rajat/tensorflow/third_party/gpus/cuda_configure.bzl", line 988, in _create_local_cuda_repository
                _get_cuda_config(repository_ctx)
        File "C:/users/rajat/tensorflow/third_party/gpus/cuda_configure.bzl", line 714, in _get_cuda_config
                find_cuda_config(repository_ctx, ["cuda", "cudnn"])
        File "C:/users/rajat/tensorflow/third_party/gpus/cuda_configure.bzl", line 694, in find_cuda_config
                auto_configure_fail(("Failed to run find_cuda_config...))
        File "C:/users/rajat/tensorflow/third_party/gpus/cuda_configure.bzl", line 325, in auto_configure_fail
                fail(("\n%sCuda Configuration Error:%...)))

Cuda Configuration Error: Failed to run find_cuda_config.py:
INFO: Elapsed time: 0.238s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
    currently loading: tensorflow/tools/graph_transforms
`

No ideas to go any further, kindly suggest any solution.

Thanks

**Comment by ravikyram** [comment]
@rajatpaliwal 
Can you please let us know the TensorFlow version you are using?.Thanks!

**Comment by rajatpaliwal** [comment]
Hi @ravikyram ,
I am using tensorflow version 1.14.0

**Comment by ymodak** [comment]
I suspect the error is raised by incompatible cuda and cudnn versions.
Please see check compatible cuda and cudnn versions from https://developer.nvidia.com/rdp/cudnn-archive
Also did you specify cuda 10.1 and cudnn version correctly while building TF from sources?
Thanks!

**Comment by rajatpaliwal** [comment]
Yes, the Cuda and cudnn version specified are correct

CUDA/cuDNN version:
10.1/7

**Comment by ymodak** [comment]
What is the minor version of cudnn? It should be 7.6.X or 7.5.X

**Comment by ymodak** [comment]
Is this still an issue?

**Comment by rajatpaliwal** [comment]
It is solved. Thanks for replying.
