### ISSUE TITLE
load custom op library when using c++?

### ISSUE THREAD

**Issue by 7oud** [tensorflow/tensorflow#32361]
I have build a very simple custom op `zero_out.dll` with bazel, it works when using python.
```
import tensorflow as tf
zero_out_module = tf.load_op_library('./zero_out.dll')
with tf.Session(''):
  zero_out_module.zero_out([[1, 2], [3, 4]]).eval()
```
However I have to run the inference using C++, is there any c++ api which has the similar function as `tf.load_op_library`, or it seems that a lot of registeration work has been done in `tf.load_op_library`, TF has not counterpart c++ API?

**Comment by oanush** [comment]
@7oud ,
Can you let us know which TF version you are using ?

**Comment by 7oud** [comment]
@oanush 
TF version: 1.13.1
Bazel: 0.21.0
GPU: 2080Ti
Some reference of build tf src on Windows: [tf-windows-build-script](https://github.com/guikarist/tensorflow-windows-build-script)
cmd of build custom op lib
```
bazel build --config opt //tensorflow/core/user_ops:zero_out.dll
```
BUILD file
```
load("//tensorflow:tensorflow.bzl", "tf_custom_op_library")

tf_custom_op_library(
    name = "zero_out.dll",
    srcs = ["zero_out.cc"],
)
```
Now I try to load op dll using `TF_LoadLibrary` in `c/c_api.h`, but it returns `TF_NOT_FOUND = 5`, the dll is not found. May some dependency dll are needed? I placed built tensorflow_cc.dll with zero_out.dll in the same folder.

**Comment by wangyunxiaa** [comment]
I have also meet this problem, when I load the added op's *.so with 
`TF_Library* lib_handle = TF_LoadLibrary("./my_forward.so", status);
printf("Can't encode string: %s\n", TF_Message(status));` 
I got an error as followings :
`F tensorflow/core/framework/variant_op_registry.cc:104] Check failed: existing == nullptr (0x21ee038 vs. nullptr)Unary VariantDecodeFn for type_name: tensorflow::Tensor already registered`
there is no document abut how to use added_op in C API.
I want to  use the graph.pb whit my custom op, how to load the grapn in C API?
thaks for advance~

**Comment by qin2294096** [comment]
I have built an custom op 'my_add.dll' on windows with vs2015, and this 'my_add.dll' can be loaded by TF_LoadLibrary("my_add.dll", status) successfully. However, if I use the 'my_add.dll' generated by bazel build, the load status will tell me that 'my_add.dll' is not found.

**Comment by 7oud** [comment]
@qin2294096 Could you tell your tf build process on Windows, using cmake? and which tf version?
After loading the custom op library, How to invoke the op function using C++? Some link will be better.
Thanks very much!

**Comment by qin2294096** [comment]
I use guikarist's scipt (https://github.com/guikarist/tensorflow-windows-build-script) to build tensorflow_cc.dll. I don't have links, so I write my process here simply.
The tf version is 1.12.0. 
To invoke custom op in C++:
1.build a graph in python with custom op, and save it.
```
# this `my_add.dll` should be built by 'bazel build --config opt //tensorflow/core/user_ops:my_add.dll'
my_add_module = tf.load_op_library('./deformable_conv2d_op/my_add.dll')  

a = my_add_module.my_add(1, 2)
frozen_graph_def = tf.get_default_graph().as_graph_def()
with tf.gfile.GFile('my_add_graph.pb', 'wb') as f:
    f.write(frozen_graph_def .SerializeToString())
```
 2. load 'my_add.dll' in c++
```
 # this `my_add.dll` should be built by vs project
 TF_Status* status = TF_NewStatus();
 TF_LoadLibrary("my_add.dll", status);
 if (TF_GetCode(status) != TF_OK) {
      LOG(INFO)<<(TF_Message(status));
      return tensorflow::errors::NotFound("Failed to load my_add.dll");
 }
 TF_DeleteStatus(status);
```
3. load the graph in a session, and run it.

**Comment by gowthamkpr** [comment]
Closing this issue as it has been resolved. Thanks!
