### ISSUE TITLE
LINK : fatal error LNK1201: error writing to program database "..\x64_windows-opt\bin\tensorflow\python\_pywrap_tensorflow_internal.pdb'; check for insufficient disk space, invalid path, or insufficient privilege

### ISSUE THREAD

**Issue by sakshigoynar17** [tensorflow/tensorflow#32366]
#31610 : The same kind of issue. 

**System information**
- OS Platform and Distribution:  Windows 10
- TensorFlow installed from (source or binary): Source. Master branch. SHA Key: 97ff26f
- TensorFlow version: 1.13.1
- Python version: 3.6.8
- Installed using virtualenv? pip? conda?: Pip
- Bazel version (if compiling from source): 0.25.1 (I modified the configure.py to support 0.25.1 Bazel version)
- GCC/Compiler version (if compiling from source): Using Microsoft Visual Studio 2019(No 2017 or 2015 Build tools)
- CUDA/cuDNN version: None
- GPU model and memory: None

**Describe the problem**
 I am trying to build Tensorflow sources in optimised mode, with debug information, so that I can get some debug information in the form of pdb files. However, I am getting the error:
LINK : fatal error LNK1201: error writing to program database 'C:\users\tensorflow_bazel_tensorflow\a7oebymx\execroot\org_tensorflow\bazel-out\x64_windows-opt\bin\tensorflow\python_pywrap_tensorflow_internal.pdb'; check for insufficient disk space, invalid path, or insufficient privilege
Target //tensorflow/tools/pip_package:build_pip_package failed to build
INFO: Elapsed time: 3959.292s, Critical Path: 1017.43s
INFO: 4150 processes: 4150 local.
FAILED: Build did NOT complete successfully

**Provide the exact sequence of commands / steps that you executed before running into the problem**
1. python ./configure.py
2. bazel build --define=tensorflow_mkldnn_contraction_kernel=0 --local_ram_resources=2048 -c opt --copt=/Z7 --copt=/FS --linkopt=/DEBUG --strip=never --config=opt //tensorflow/tools/pip_package:build_pip_package

**Any other info / logs**
The size of the pdb: C:\users\tensorflow_bazel_tensorflow\a7oebymx\execroot\org_tensorflow\bazel-out\x64_windows-opt\bin\tensorflow\python\_pywrap_tensorflow_internal.pdb was just 4GB and there was enough disk space available.
CAn somebody help me give a better insight of the issue?

**Comment by ymodak** [comment]
Apparently this is an issue of visual Studio. Please take a look at this thread for workarounds
https://software.intel.com/en-us/forums/intel-visual-fortran-compiler-for-windows/topic/362147
Thanks!

**Comment by sakshigoynar17** [comment]
Thanks for the link. Yes, surely, it is an issue with Visual Studio.

**Comment by achnagann** [comment]
and how do you fix it?
