### ISSUE TITLE
Reduce sum should work on heterogeneous shapes

### ISSUE THREAD

**Issue by bionicles** [tensorflow/tensorflow#32365]
**System information**
- TensorFlow version (you are using): 2 rc
- Are you willing to contribute it (Yes/No): Not sure how

**Describe the feature and the current behavior/state.**
tf.math.reduce_sum fails if given an array of differently shaped tensors

**Will this change the current api? How?**
reduce sum should "just work" in the case where user wants to total a bunch of different shapes. 

**Who will benefit with this feature?**
anyone who wants to tally the losses

**Any Other info.**
just want to tally my losses, but this doesn't work:
`total = tf.math.reduce_sum(LIST_OF_TENSORS)`
```
    @tf.function
    def tally(losses):
        total = 0.
        for loss in losses:
            current = tf.math.reduce_sum(loss)
            tf.print(tf.shape(current))
            total = total + current
        return total
```
this is a simple common task, `total = tf.math.reduce_sum(LIST_OF_TENSORS)` should just work even if the tensors are differently shaped

>     ValueError: Shapes must be equal rank, but are 3 and 0

**Comment by rohan100jain** [comment]
the axis argument makes this quite complicated and not possible to work. Also, numpy fails with this kind of input

```
a1 = np.random.rand(2, 3)
a2 = np.random.rand(3, 4)

b = np.sum([a1, a2])
```

So I'm inclined to say that is isn't desirable from an API standpoint.
