### ISSUE TITLE
TF2.0  AutoGraph issue

### ISSUE THREAD

**Issue by nanguatou9** [tensorflow/tensorflow#32377]
OS:Ubuntu 18.04
TensorFlow Version:tensorflow-gpu == 2.0.0-rc0
issue:AutoGraph
WARNING:tensorflow:Entity <function Function._initialize_uninitialized_variables.<locals>.initialize_variables at 0x7fd89803cef0> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: module 'gast' has no attribute 'Num'
WARNING: Entity <function Function._initialize_uninitialized_variables.<locals>.initialize_variables at 0x7fd89803cef0> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: module 'gast' has no attribute 'Num'
[tf_env.txt](https://github.com/tensorflow/tensorflow/files/3594563/tf_env.txt)

**Comment by nanguatou9** [comment]
CUDA Version: CUDA 10.0

**Comment by 2649** [comment]
You should add your code as well. I had the same Issue, but the cause was bug in my code, not of tensorflow.

**Comment by ravikyram** [comment]
You can try  `pip install gast==0.2.2` and see if it resolves your issue.

Please, go through the below link and see if it helps you.Thanks!
#32319

**Comment by nanguatou9** [comment]
@ravikyram @2649 
The problem has been resolved after installing gast. Thanks!

**Comment by che-shr-cat** [comment]
Got the same issue, it was resolved after installing gast 0.2.2. Previous gast version was 0.3.2

**Comment by TommeyChang** [comment]
OS:Ubuntu 16.04
TensorFlow Version:tensorflow-gpu == 2.0.0-rc1
CUDA:10.0
issue:AutoGraph

INFO:tensorflow:Converted call: <function simple_nn_layer at 0x7f6de177c598>
    args: (<tf.Tensor 'x:0' shape=(3, 3) dtype=float32>, <tf.Tensor 'y:0' shape=(3, 3) dtype=float32>)
    kwargs: {}

Converted call: <function simple_nn_layer at 0x7f6de177c598>
    args: (<tf.Tensor 'x:0' shape=(3, 3) dtype=float32>, <tf.Tensor 'y:0' shape=(3, 3) dtype=float32>)
    kwargs: {}

INFO:tensorflow:Entity <function simple_nn_layer at 0x7f6de177c598> is not cached for key <code object simple_nn_layer at 0x7f6e085cf540, file "<ipython-input-2-15699e84f48b>", line 1> subkey (<tensorflow.python.autograph.core.converter.ConversionOptions object at 0x7f6d9a2547f0>, frozenset())
Entity <function simple_nn_layer at 0x7f6de177c598> is not cached for key <code object simple_nn_layer at 0x7f6e085cf540, file "<ipython-input-2-15699e84f48b>", line 1> subkey (<tensorflow.python.autograph.core.converter.ConversionOptions object at 0x7f6d9a2547f0>, frozenset())
INFO:tensorflow:Converting <function simple_nn_layer at 0x7f6de177c598>
Converting <function simple_nn_layer at 0x7f6de177c598>
INFO:tensorflow:Source code of <function simple_nn_layer at 0x7f6de177c598>:

from __future__ import absolute_import
from __future__ import division
from __future__ import print_function
@tf.function
def simple_nn_layer(x, y):
    return tf.nn.relu(tf.matmul(x, y))


Source code of <function simple_nn_layer at 0x7f6de177c598>:

from __future__ import absolute_import
from __future__ import division
from __future__ import print_function
@tf.function
def simple_nn_layer(x, y):
    return tf.nn.relu(tf.matmul(x, y))


INFO:tensorflow:Error transforming entity <function simple_nn_layer at 0x7f6de177c598>
Traceback (most recent call last):
  File "/home/tommey/anaconda3/envs/tf2.0/lib/python3.6/site-packages/tensorflow_core/python/autograph/impl/api.py", line 506, in converted_call
    converted_f = conversion.convert(target_entity, program_ctx)
  File "/home/tommey/anaconda3/envs/tf2.0/lib/python3.6/site-packages/tensorflow_core/python/autograph/impl/conversion.py", line 322, in convert
    free_nonglobal_var_names)
  File "/home/tommey/anaconda3/envs/tf2.0/lib/python3.6/site-packages/tensorflow_core/python/autograph/impl/conversion.py", line 240, in _convert_with_cache
    entity, program_ctx)
  File "/home/tommey/anaconda3/envs/tf2.0/lib/python3.6/site-packages/tensorflow_core/python/autograph/impl/conversion.py", line 469, in convert_entity_to_ast
    nodes, name, entity_info = convert_func_to_ast(o, program_ctx)
  File "/home/tommey/anaconda3/envs/tf2.0/lib/python3.6/site-packages/tensorflow_core/python/autograph/impl/conversion.py", line 669, in convert_func_to_ast
    node = node_to_graph(node, context)
  File "/home/tommey/anaconda3/envs/tf2.0/lib/python3.6/site-packages/tensorflow_core/python/autograph/impl/conversion.py", line 699, in node_to_graph
    node = converter.apply_(node, context, function_scopes)
  File "/home/tommey/anaconda3/envs/tf2.0/lib/python3.6/site-packages/tensorflow_core/python/autograph/core/converter.py", line 409, in apply_
    node = converter_module.transform(node, context)
  File "/home/tommey/anaconda3/envs/tf2.0/lib/python3.6/site-packages/tensorflow_core/python/autograph/converters/function_scopes.py", line 120, in transform
    return FunctionBodyTransformer(ctx).visit(node)
  File "/home/tommey/anaconda3/envs/tf2.0/lib/python3.6/site-packages/tensorflow_core/python/autograph/core/converter.py", line 346, in visit
    return super(Base, self).visit(node)
  File "/home/tommey/anaconda3/envs/tf2.0/lib/python3.6/site-packages/tensorflow_core/python/autograph/pyct/transformer.py", line 480, in visit
    result = super(Base, self).visit(node)
  File "/home/tommey/anaconda3/envs/tf2.0/lib/python3.6/ast.py", line 253, in visit
    return visitor(node)
  File "/home/tommey/anaconda3/envs/tf2.0/lib/python3.6/site-packages/tensorflow_core/python/autograph/converters/function_scopes.py", line 87, in visit_FunctionDef
    node = self.generic_visit(node)
  File "/home/tommey/anaconda3/envs/tf2.0/lib/python3.6/ast.py", line 308, in generic_visit
    value = self.visit(value)
  File "/home/tommey/anaconda3/envs/tf2.0/lib/python3.6/site-packages/tensorflow_core/python/autograph/core/converter.py", line 346, in visit
    return super(Base, self).visit(node)
  File "/home/tommey/anaconda3/envs/tf2.0/lib/python3.6/site-packages/tensorflow_core/python/autograph/pyct/transformer.py", line 480, in visit
    result = super(Base, self).visit(node)
  File "/home/tommey/anaconda3/envs/tf2.0/lib/python3.6/ast.py", line 253, in visit
    return visitor(node)
  File "/home/tommey/anaconda3/envs/tf2.0/lib/python3.6/site-packages/tensorflow_core/python/autograph/converters/function_scopes.py", line 44, in visit_Return
    value=node.value)
  File "/home/tommey/anaconda3/envs/tf2.0/lib/python3.6/site-packages/tensorflow_core/python/autograph/pyct/templates.py", line 261, in replace
    replacements[k] = _convert_to_ast(replacements[k])
  File "/home/tommey/anaconda3/envs/tf2.0/lib/python3.6/site-packages/tensorflow_core/python/autograph/pyct/templates.py", line 223, in _convert_to_ast
    return gast.Name(id=n, ctx=None, annotation=None)
  File "/home/tommey/anaconda3/envs/tf2.0/lib/python3.6/site-packages/gast/gast.py", line 19, in create_node
    format(Name, nbparam, len(Fields))
AssertionError: Bad argument number for Name: 3, expecting 4
Error transforming entity <function simple_nn_layer at 0x7f6de177c598>
WARNING:tensorflow:Entity <function simple_nn_layer at 0x7f6de177c598> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: Bad argument number for Name: 3, expecting 4
WARNING: Entity <function simple_nn_layer at 0x7f6de177c598> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: Bad argument number for Name: 3, expecting 4

**Comment by bionicles** [comment]
same issue fixed with `pip install gast=0.2.2`

**Comment by zero1666** [comment]
> OS:Ubuntu 16.04
> TensorFlow Version:tensorflow-gpu == 2.0.0-rc1
> CUDA:10.0
> issue:AutoGraph
> 
> INFO:tensorflow:Converted call: <function simple_nn_layer at 0x7f6de177c598>
> args: (<tf.Tensor 'x:0' shape=(3, 3) dtype=float32>, <tf.Tensor 'y:0' shape=(3, 3) dtype=float32>)
> kwargs: {}
> 
> Converted call: <function simple_nn_layer at 0x7f6de177c598>
> args: (<tf.Tensor 'x:0' shape=(3, 3) dtype=float32>, <tf.Tensor 'y:0' shape=(3, 3) dtype=float32>)
> kwargs: {}
> 
> INFO:tensorflow:Entity <function simple_nn_layer at 0x7f6de177c598> is not cached for key <code object simple_nn_layer at 0x7f6e085cf540, file "", line 1> subkey (<tensorflow.python.autograph.core.converter.ConversionOptions object at 0x7f6d9a2547f0>, frozenset())
> Entity <function simple_nn_layer at 0x7f6de177c598> is not cached for key <code object simple_nn_layer at 0x7f6e085cf540, file "", line 1> subkey (<tensorflow.python.autograph.core.converter.ConversionOptions object at 0x7f6d9a2547f0>, frozenset())
> INFO:tensorflow:Converting <function simple_nn_layer at 0x7f6de177c598>
> Converting <function simple_nn_layer at 0x7f6de177c598>
> INFO:tensorflow:Source code of <function simple_nn_layer at 0x7f6de177c598>:
> 
> from **future** import absolute_import
> from **future** import division
> from **future** import print_function
> @tf.function
> def simple_nn_layer(x, y):
> return tf.nn.relu(tf.matmul(x, y))
> 
> Source code of <function simple_nn_layer at 0x7f6de177c598>:
> 
> from **future** import absolute_import
> from **future** import division
> from **future** import print_function
> @tf.function
> def simple_nn_layer(x, y):
> return tf.nn.relu(tf.matmul(x, y))
> 
> INFO:tensorflow:Error transforming entity <function simple_nn_layer at 0x7f6de177c598>
> Traceback (most recent call last):
> File "/home/tommey/anaconda3/envs/tf2.0/lib/python3.6/site-packages/tensorflow_core/python/autograph/impl/api.py", line 506, in converted_call
> converted_f = conversion.convert(target_entity, program_ctx)
> File "/home/tommey/anaconda3/envs/tf2.0/lib/python3.6/site-packages/tensorflow_core/python/autograph/impl/conversion.py", line 322, in convert
> free_nonglobal_var_names)
> File "/home/tommey/anaconda3/envs/tf2.0/lib/python3.6/site-packages/tensorflow_core/python/autograph/impl/conversion.py", line 240, in _convert_with_cache entity, program_ctx) File "/home/tommey/anaconda3/envs/tf2.0/lib/python3.6/site-packages/tensorflow_core/python/autograph/impl/conversion.py", line 469, in convert_entity_to_ast nodes, name, entity_info = convert_func_to_ast(o, program_ctx) File "/home/tommey/anaconda3/envs/tf2.0/lib/python3.6/site-packages/tensorflow_core/python/autograph/impl/conversion.py", line 669, in convert_func_to_ast node = node_to_graph(node, context) File "/home/tommey/anaconda3/envs/tf2.0/lib/python3.6/site-packages/tensorflow_core/python/autograph/impl/conversion.py", line 699, in node_to_graph node = converter.apply_(node, context, function_scopes)
> File "/home/tommey/anaconda3/envs/tf2.0/lib/python3.6/site-packages/tensorflow_core/python/autograph/core/converter.py", line 409, in apply_
> node = converter_module.transform(node, context)
> File "/home/tommey/anaconda3/envs/tf2.0/lib/python3.6/site-packages/tensorflow_core/python/autograph/converters/function_scopes.py", line 120, in transform
> return FunctionBodyTransformer(ctx).visit(node)
> File "/home/tommey/anaconda3/envs/tf2.0/lib/python3.6/site-packages/tensorflow_core/python/autograph/core/converter.py", line 346, in visit
> return super(Base, self).visit(node)
> File "/home/tommey/anaconda3/envs/tf2.0/lib/python3.6/site-packages/tensorflow_core/python/autograph/pyct/transformer.py", line 480, in visit
> result = super(Base, self).visit(node)
> File "/home/tommey/anaconda3/envs/tf2.0/lib/python3.6/ast.py", line 253, in visit
> return visitor(node)
> File "/home/tommey/anaconda3/envs/tf2.0/lib/python3.6/site-packages/tensorflow_core/python/autograph/converters/function_scopes.py", line 87, in visit_FunctionDef
> node = self.generic_visit(node)
> File "/home/tommey/anaconda3/envs/tf2.0/lib/python3.6/ast.py", line 308, in generic_visit
> value = self.visit(value)
> File "/home/tommey/anaconda3/envs/tf2.0/lib/python3.6/site-packages/tensorflow_core/python/autograph/core/converter.py", line 346, in visit
> return super(Base, self).visit(node)
> File "/home/tommey/anaconda3/envs/tf2.0/lib/python3.6/site-packages/tensorflow_core/python/autograph/pyct/transformer.py", line 480, in visit
> result = super(Base, self).visit(node)
> File "/home/tommey/anaconda3/envs/tf2.0/lib/python3.6/ast.py", line 253, in visit
> return visitor(node)
> File "/home/tommey/anaconda3/envs/tf2.0/lib/python3.6/site-packages/tensorflow_core/python/autograph/converters/function_scopes.py", line 44, in visit_Return
> value=node.value)
> File "/home/tommey/anaconda3/envs/tf2.0/lib/python3.6/site-packages/tensorflow_core/python/autograph/pyct/templates.py", line 261, in replace
> replacements[k] = _convert_to_ast(replacements[k])
> File "/home/tommey/anaconda3/envs/tf2.0/lib/python3.6/site-packages/tensorflow_core/python/autograph/pyct/templates.py", line 223, in _convert_to_ast
> return gast.Name(id=n, ctx=None, annotation=None)
> File "/home/tommey/anaconda3/envs/tf2.0/lib/python3.6/site-packages/gast/gast.py", line 19, in create_node
> format(Name, nbparam, len(Fields))
> AssertionError: Bad argument number for Name: 3, expecting 4
> Error transforming entity <function simple_nn_layer at 0x7f6de177c598>
> WARNING:tensorflow:Entity <function simple_nn_layer at 0x7f6de177c598> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: Bad argument number for Name: 3, expecting 4
> WARNING: Entity <function simple_nn_layer at 0x7f6de177c598> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: Bad argument number for Name: 3, expecting 4
-----------------------------
I meet the same problem, did anyone resolve it in tensorflow2-rc1?

**Comment by hagianga21** [comment]
> > OS:Ubuntu 16.04
> > TensorFlow Version:tensorflow-gpu == 2.0.0-rc1
> > CUDA:10.0
> > issue:AutoGraph
> > INFO:tensorflow:Converted call: <function simple_nn_layer at 0x7f6de177c598>
> > args: (<tf.Tensor 'x:0' shape=(3, 3) dtype=float32>, <tf.Tensor 'y:0' shape=(3, 3) dtype=float32>)
> > kwargs: {}
> > Converted call: <function simple_nn_layer at 0x7f6de177c598>
> > args: (<tf.Tensor 'x:0' shape=(3, 3) dtype=float32>, <tf.Tensor 'y:0' shape=(3, 3) dtype=float32>)
> > kwargs: {}
> > INFO:tensorflow:Entity <function simple_nn_layer at 0x7f6de177c598> is not cached for key <code object simple_nn_layer at 0x7f6e085cf540, file "", line 1> subkey (<tensorflow.python.autograph.core.converter.ConversionOptions object at 0x7f6d9a2547f0>, frozenset())
> > Entity <function simple_nn_layer at 0x7f6de177c598> is not cached for key <code object simple_nn_layer at 0x7f6e085cf540, file "", line 1> subkey (<tensorflow.python.autograph.core.converter.ConversionOptions object at 0x7f6d9a2547f0>, frozenset())
> > INFO:tensorflow:Converting <function simple_nn_layer at 0x7f6de177c598>
> > Converting <function simple_nn_layer at 0x7f6de177c598>
> > INFO:tensorflow:Source code of <function simple_nn_layer at 0x7f6de177c598>:
> > from **future** import absolute_import
> > from **future** import division
> > from **future** import print_function
> > @tf.function
> > def simple_nn_layer(x, y):
> > return tf.nn.relu(tf.matmul(x, y))
> > Source code of <function simple_nn_layer at 0x7f6de177c598>:
> > from **future** import absolute_import
> > from **future** import division
> > from **future** import print_function
> > @tf.function
> > def simple_nn_layer(x, y):
> > return tf.nn.relu(tf.matmul(x, y))
> > INFO:tensorflow:Error transforming entity <function simple_nn_layer at 0x7f6de177c598>
> > Traceback (most recent call last):
> > File "/home/tommey/anaconda3/envs/tf2.0/lib/python3.6/site-packages/tensorflow_core/python/autograph/impl/api.py", line 506, in converted_call
> > converted_f = conversion.convert(target_entity, program_ctx)
> > File "/home/tommey/anaconda3/envs/tf2.0/lib/python3.6/site-packages/tensorflow_core/python/autograph/impl/conversion.py", line 322, in convert
> > free_nonglobal_var_names)
> > File "/home/tommey/anaconda3/envs/tf2.0/lib/python3.6/site-packages/tensorflow_core/python/autograph/impl/conversion.py", line 240, in _convert_with_cache entity, program_ctx) File "/home/tommey/anaconda3/envs/tf2.0/lib/python3.6/site-packages/tensorflow_core/python/autograph/impl/conversion.py", line 469, in convert_entity_to_ast nodes, name, entity_info = convert_func_to_ast(o, program_ctx) File "/home/tommey/anaconda3/envs/tf2.0/lib/python3.6/site-packages/tensorflow_core/python/autograph/impl/conversion.py", line 669, in convert_func_to_ast node = node_to_graph(node, context) File "/home/tommey/anaconda3/envs/tf2.0/lib/python3.6/site-packages/tensorflow_core/python/autograph/impl/conversion.py", line 699, in node_to_graph node = converter.apply_(node, context, function_scopes)
> > File "/home/tommey/anaconda3/envs/tf2.0/lib/python3.6/site-packages/tensorflow_core/python/autograph/core/converter.py", line 409, in apply_
> > node = converter_module.transform(node, context)
> > File "/home/tommey/anaconda3/envs/tf2.0/lib/python3.6/site-packages/tensorflow_core/python/autograph/converters/function_scopes.py", line 120, in transform
> > return FunctionBodyTransformer(ctx).visit(node)
> > File "/home/tommey/anaconda3/envs/tf2.0/lib/python3.6/site-packages/tensorflow_core/python/autograph/core/converter.py", line 346, in visit
> > return super(Base, self).visit(node)
> > File "/home/tommey/anaconda3/envs/tf2.0/lib/python3.6/site-packages/tensorflow_core/python/autograph/pyct/transformer.py", line 480, in visit
> > result = super(Base, self).visit(node)
> > File "/home/tommey/anaconda3/envs/tf2.0/lib/python3.6/ast.py", line 253, in visit
> > return visitor(node)
> > File "/home/tommey/anaconda3/envs/tf2.0/lib/python3.6/site-packages/tensorflow_core/python/autograph/converters/function_scopes.py", line 87, in visit_FunctionDef
> > node = self.generic_visit(node)
> > File "/home/tommey/anaconda3/envs/tf2.0/lib/python3.6/ast.py", line 308, in generic_visit
> > value = self.visit(value)
> > File "/home/tommey/anaconda3/envs/tf2.0/lib/python3.6/site-packages/tensorflow_core/python/autograph/core/converter.py", line 346, in visit
> > return super(Base, self).visit(node)
> > File "/home/tommey/anaconda3/envs/tf2.0/lib/python3.6/site-packages/tensorflow_core/python/autograph/pyct/transformer.py", line 480, in visit
> > result = super(Base, self).visit(node)
> > File "/home/tommey/anaconda3/envs/tf2.0/lib/python3.6/ast.py", line 253, in visit
> > return visitor(node)
> > File "/home/tommey/anaconda3/envs/tf2.0/lib/python3.6/site-packages/tensorflow_core/python/autograph/converters/function_scopes.py", line 44, in visit_Return
> > value=node.value)
> > File "/home/tommey/anaconda3/envs/tf2.0/lib/python3.6/site-packages/tensorflow_core/python/autograph/pyct/templates.py", line 261, in replace
> > replacements[k] = _convert_to_ast(replacements[k])
> > File "/home/tommey/anaconda3/envs/tf2.0/lib/python3.6/site-packages/tensorflow_core/python/autograph/pyct/templates.py", line 223, in _convert_to_ast
> > return gast.Name(id=n, ctx=None, annotation=None)
> > File "/home/tommey/anaconda3/envs/tf2.0/lib/python3.6/site-packages/gast/gast.py", line 19, in create_node
> > format(Name, nbparam, len(Fields))
> > AssertionError: Bad argument number for Name: 3, expecting 4
> > Error transforming entity <function simple_nn_layer at 0x7f6de177c598>
> > WARNING:tensorflow:Entity <function simple_nn_layer at 0x7f6de177c598> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: Bad argument number for Name: 3, expecting 4
> > WARNING: Entity <function simple_nn_layer at 0x7f6de177c598> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: Bad argument number for Name: 3, expecting 4
> 
> I meet the same problem, did anyone resolve it in tensorflow2-rc1?

I also met that problem

**Comment by ashwin17083** [comment]
I am facing a similar issue. I tried to downgrade gast version 0.2.2.
OS:CentOS Linux release 7.7.1908 (Core)
tensorflow version: 1.15.0-dev20190718

The issue aeries when saving the lstm model as:
final_model.save("complete_model",save_format='tf') whereas it is doesnt throw an error upon saving it as final_model.save("complete_model.h5")

The error message is as follows:

W0127 16:22:09.873542 140113418938176 ag_logging.py:146] Entity <function Function._initialize_uninitialized_variables.<locals>.initialize_variables at 0x7f6de43a8048> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: No module named 'tensorflow_core.estimator'
W0127 16:22:09.882860 140113418938176 ag_logging.py:146] Entity <function _wrap_call_and_conditional_losses.<locals>.call_and_return_conditional_losses at 0x7f6de41e8048> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: No module named 'tensorflow_core.estimator'
W0127 16:22:09.911009 140113418938176 save.py:129] Skipping full serialization of object <tensorflow.python.keras.layers.recurrent.LSTM object at 0x7f6e00539f60>, because an error occurred while tracing layer functions. Error message: in converted code:
    relative to /usr/local/lib/python3.4/site-packages/tensorflow_core/python/keras:

    saving/saved_model/save.py:535 call_and_return_conditional_losses
        return layer_call(inputs, training=training), layer.get_losses_for(inputs)
    layers/recurrent.py:2535 call
        inputs, mask=mask, training=training, initial_state=initial_state)
    layers/recurrent.py:745 call
        zero_output_for_mask=self.zero_output_for_mask)
    backend.py:3794 rnn
        input_time_zero, tuple(initial_states) + tuple(constants))
    layers/recurrent.py:730 step
        output, new_states = self.cell.call(inputs, states, **kwargs)

    TypeError: wrapped_call() takes 1 positional argument but 2 were given

W0127 16:22:09.916115 140113418938176 ag_logging.py:146] Entity <function _wrap_call_and_conditional_losses.<locals>.call_and_return_conditional_losses at 0x7f6de41e8488> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: No module named 'tensorflow_core.estimator'
W0127 16:22:09.943473 140113418938176 save.py:129] Skipping full serialization of object <tensorflow.python.keras.engine.training.Model object at 0x7f6dff6e65c0>, because an error occurred while tracing layer functions. Error message: in converted code:
    relative to /usr/local/lib/python3.4/site-packages/tensorflow_core/python/keras:

    saving/saved_model/save.py:535 call_and_return_conditional_losses
        return layer_call(inputs, training=training), layer.get_losses_for(inputs)
    engine/network.py:737 call
        return self._run_internal_graph(inputs, training=training, mask=mask)
    engine/network.py:879 _run_internal_graph
        output_tensors = layer(computed_tensors, **kwargs)
    layers/recurrent.py:621 __call__
        return super(RNN, self).__call__(inputs, **kwargs)
    engine/base_layer.py:713 __call__
        outputs = call_fn(inputs, *args, **kwargs)
    layers/recurrent.py:2535 call
        inputs, mask=mask, training=training, initial_state=initial_state)
    layers/recurrent.py:745 call
        zero_output_for_mask=self.zero_output_for_mask)
    backend.py:3794 rnn
        input_time_zero, tuple(initial_states) + tuple(constants))
    layers/recurrent.py:730 step
        output, new_states = self.cell.call(inputs, states, **kwargs)

    TypeError: wrapped_call() takes 1 positional argument but 2 were given

2020-01-27 16:22:09.957051: W tensorflow/python/util/util.cc:288] Sets are not currently considered sequences, but this may change in the future, so consider avoiding using them.
W0127 16:22:09.982703 140113418938176 ag_logging.py:146] Entity <function Layer._handle_weight_regularization.<locals>._loss_for_variable at 0x7f6e017b6d90> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: No module named 'tensorflow_core.estimator'
W0127 16:22:09.992292 140113418938176 ag_logging.py:146] Entity <function Function._initialize_uninitialized_variables.<locals>.initialize_variables at 0x7f6de43a8400> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: No module named 'tensorflow_core.estimator'
