### ISSUE TITLE
[TF2.0]Shuffle function on tf.data fills up RAM memory.

### ISSUE THREAD

**Issue by rishabhsahrawat** [tensorflow/tensorflow#32376]
In TF2.0rc, using `shuffle(buffer_size= #_of_elements)` on `tf.data.Dataset` type dataset, it fills up shuffle buffer which also fills up RAM memory so if the data is huge and RAM is not enough then it hangs up the system which leads to system restart. This memory filling happens before every epoch. It of course releases the memory once the epoch is done. To reproduce this problem, I followed [this](https://www.tensorflow.org/beta/tutorials/load_data/text#split_the_dataset_into_text_and_train_batches) TF tutorial but with more amount of data.
Since `tf.data` is for handling the dataset  that can not be filled up in the memory then why does shuffle function shows this behaviour and fills up the memory.?

**Comment by jsimsa** [comment]
The behavior you are seeing is expected. If your data is such that it cannot be all loaded into memory, then you cannot perform a "perfect" shuffle (i.e. using a shuffle buffer size that matches the cardinality of your dataset) and should instead use a smaller buffer size.

In other words, tf.data currently does not support "perfect" shuffle for dataset that do not fit into memory.

**Comment by ChaooMa** [comment]
@jsimsa 
How to avoid this problem? Thank you.

**Comment by jsimsa** [comment]
Use a smaller buffer size.

**Comment by ChaooMa** [comment]
Thanks a lot!
You're answering so quickly, ths!
