### ISSUE TITLE
TF 2.0 save-load SequenceFeatures layer issue

### ISSUE THREAD

**Issue by EgorBEremeev** [tensorflow/tensorflow#32385]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): **yes**
- OS Platform and Distribution: **WIndows 10 Pro build 1903**
- TensorFlow installed from (source or binary): **binary**
- TensorFlow version (use command below): **2.0.0-alpha0**, **2.0.0-beta0**, **2.0.0-beta1**, **2.0.0-rc0**
- Python version: **Python 3.7.3**

**Describe the current behavior**

1. I create model using Keras Functional API. The model includes `tf.keras.experimental.SequenceFeatures` layer and `sequence_categorical_column_with_vocabulary_list` feature_column.
2. Then I save model by `tf.keras.models.model.save('path_to_model.h5')`. 
3. Finally, I load model by `tf.keras.models.load_model(path_to_model.h5)`. While loading I get the error message :

> Unknown layer: SequenceFeatures

**Describe the expected behavior**
The model containing SequenceFeatures layer and any corresponding feature_columns is loaded by `tf.keras.models.load_model(MODEL_PATH.h5)` without errors.

**Code to reproduce the issue**
```
import tensorflow as tf
from tensorflow import feature_column

print(tf.__version__)

!python -V

# Define categorical colunm for our text feature, which is preprocessed into sequence of tokens
text_column = feature_column.sequence_categorical_column_with_vocabulary_list(key='text', 
                                                                     vocabulary_list=list(['asd', 'asdf']))

text_embedding = feature_column.embedding_column(text_column, dimension=8)

# Then define the layers and model it self
# This example uses Keras Functional API instead of Sequential just for more generallity

# Define SequenceFeatures layer to pass feature_columns into Keras model
sequence_feature_layer = tf.keras.experimental.SequenceFeatures(text_embedding)

max_length = 6
# Define inputs for each feature column. See
# см. https://github.com/tensorflow/tensorflow/issues/27416#issuecomment-502218673
sequence_feature_layer_inputs = {}
sequence_feature_layer_inputs['text'] = tf.keras.Input(shape=(max_length,), name='text', dtype=tf.string)

sequence_feature_layer_outputs, _ = sequence_feature_layer(sequence_feature_layer_inputs)
print(sequence_feature_layer_outputs)

# Define outputs of SequenceFeatures layer 
# And accually use them as first layer of the model

# note here that SequenceFeatures layer produce tuple of two tensors as output. We need just first to pass next.
sequence_feature_layer_outputs, _ = sequence_feature_layer(sequence_feature_layer_inputs)

x = tf.keras.layers.Conv1D(8,4)(sequence_feature_layer_outputs)
x = tf.keras.layers.MaxPooling1D(2)(x)
x = tf.keras.layers.Dense(256, activation='relu')(x)
x = tf.keras.layers.Dropout(0.2)(x)
x= tf.keras.layers.GlobalAveragePooling1D()(x)
# This example supposes binary classification, as labels are 0 or 1
x = tf.keras.layers.Dense(1, activation='sigmoid')(x)

model = tf.keras.models.Model(inputs=[v for v in sequence_feature_layer_inputs.values()], outputs=x)

model.summary()

# This example supposes binary classification, as labels are 0 or 1
model.compile(optimizer='adam',
              loss='binary_crossentropy',
              metrics=['accuracy']
              #run_eagerly=True
             )

model.save('model.h5')
model_loaded = tf.keras.models.load_model('model.h5')

model_loaded.summary()
# expected result: model_loaded is instantinated
# actual result: exception with text: "Unknown layer: SequenceFeatures"

#other way to save model structure also finishes with error

model_json_string = model.to_json()
# import pprint
# pprint.pprint(json.loads(model_json_string))
fresh_model = tf.keras.models.model_from_json(model_json_string)
fresh_model.summary()
# expected result: model_loaded is instantinated
# actual result: exception with text: "Unknown layer: SequenceFeatures"
```

**Other info / logs**
I have found that this problem is fixed by changes in commit [a29555a8fed1b2a1eb495e220eca7b3e3161ea26](https://github.com/tensorflow/tensorflow/commit/a29555a8fed1b2a1eb495e220eca7b3e3161ea26#diff-66f6b57cc123613d5703a087b48cdb48) and do not reproduced in **tf-nightly-2.0-preview** build. But it still reproduced in **2.0.0-alpha0**, **2.0.0-beta0**, **2.0.0-beta1**, **2.0.0-rc0**

**Comment by k-w-w** [comment]
@EgorBEremeev The recommended format for saving is SavedModel. Can you try using that instead of Hdf5? To save to SavedModel, specify a path without the ".h5" extension, or set the `save_format` option to `tf`.

tf-nightly is more up to date than 2.0.0-alpha/beta/rc0, so the issue should be fixed in the next release.

**Comment by EgorBEremeev** [comment]
@k-w-w , I have tried SavedModel in stable release 2.0 and althogh save\load methods finishes without error the loaded model is corrupted. Specifically
`model_loaded.summary()` aborted with 

> ValueError: You tried to call `count_params` on text, but the layer isn't built. You can build it manually via: `text.build(batch_input_shape)`

If I add
`model_loaded.compile()` it is aborted with 

> ValueError: The model cannot be compiled because it has no loss to optimize. 

I reproduced this with the code I gave above, where I just replace
```
model.save('model.h5')
model_loaded = tf.keras.models.load_model('model.h5')
```

with
```
model.save('model_as_SavedModel', save_format='tf')
model_loaded = tf.keras.models.load_model('model_as_SavedModel')
```
However, in the last nightly build it is not reproduced. Is there a way to push working code for SequenceFeatures layer at least to alpha or beta releases, and so it become available on the google cloud platform?

**Comment by haifengkao** [comment]
I tried your code on TF 2.2 without any problems
