### ISSUE TITLE
tf Function could not able to transformed into graph.

### ISSUE THREAD

**Issue by hussain7** [tensorflow/tensorflow#32383]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version (use command below):
- Python version:
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**

**Describe the expected behavior**

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by hussain7** [comment]
WARNING:tensorflow:Entity <function train.<locals>.train_step at 0x000002B43293D0D0> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <function train.<locals>.train_step at 0x000002B43293D0D0>: AssertionError: Bad argument number for Name: 3, expecting 4
WARNING:tensorflow:Entity <function Function._initialize_uninitialized_variables.<locals>.initialize_variables at 0x000002B94351E598> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <function Function._initialize_uninitialized_variables.<locals>.initialize_variables at 0x000002B94351E598>: AttributeError: module 'gast' has no attribute 'Num'
WARNING:tensorflow:Entity <function train.<locals>.train_step at 0x000002B43293D0D0> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <function train.<locals>.train_step at 0x000002B43293D0D0>: AssertionError: Bad argument number for Name: 3, expecting 4
Step 3078/40000 - training_loss 0.61717

**Comment by hussain7** [comment]
== check python ===================================================
python version: 3.6.8
python branch: tags/v3.6.8
python build version: ('tags/v3.6.8:3c6b436a57', 'Dec 24 2018 00:16:47')
python compiler version: MSC v.1916 64 bit (AMD64)
python implementation: CPython


== check os platform ===============================================
os: Windows
os kernel version: 10.0.17134
os release version: 10
os platform: Windows-10-10.0.17134-SP0
linux distribution: ('', '', '')
linux os distribution: ('', '', '')
mac version: ('', ('', '', ''), '')
uname: uname_result(system='Windows', node='DONTCARE', release='10', version='10.0.17134', machine='AMD64', processor='Intel64 Family 6 Model 79 Stepping 1, GenuineIntel')
architecture: ('64bit', 'WindowsPE')
machine: AMD64


== are we in docker =============================================
No

== compiler =====================================================
bash: c++: command not found

== check pips ===================================================
numpy                1.17.2              
protobuf             3.9.1               
tensorflow           2.0.0rc0            
tensorflow-gpu       2.0.0b1             

== check for virtualenv =========================================
True

== tensorflow import ============================================
tf.version.VERSION = 2.0.0-beta1
tf.version.GIT_VERSION = unknown
tf.version.COMPILER_VERSION = MSVC 190024215
C:\Users\MHN9\.virtualenvs\src-wzStTweO\lib\site-packages\tensorflow\python\framework\dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\Users\MHN9\.virtualenvs\src-wzStTweO\lib\site-packages\tensorflow\python\framework\dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
C:\Users\MHN9\.virtualenvs\src-wzStTweO\lib\site-packages\tensorflow\python\framework\dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
C:\Users\MHN9\.virtualenvs\src-wzStTweO\lib\site-packages\tensorflow\python\framework\dtypes.py:519: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
C:\Users\MHN9\.virtualenvs\src-wzStTweO\lib\site-packages\tensorflow\python\framework\dtypes.py:520: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
C:\Users\MHN9\.virtualenvs\src-wzStTweO\lib\site-packages\tensorflow\python\framework\dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
C:\Users\MHN9\.virtualenvs\src-wzStTweO\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:541: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\Users\MHN9\.virtualenvs\src-wzStTweO\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:542: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
C:\Users\MHN9\.virtualenvs\src-wzStTweO\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:543: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
C:\Users\MHN9\.virtualenvs\src-wzStTweO\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:544: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
C:\Users\MHN9\.virtualenvs\src-wzStTweO\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:545: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
C:\Users\MHN9\.virtualenvs\src-wzStTweO\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:550: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])

== env ==========================================================
LD_LIBRARY_PATH is unset
DYLD_LIBRARY_PATH is unset

== nvidia-smi ===================================================
Tue Sep 10 16:26:43 2019       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 431.70       Driver Version: 431.70       CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name            TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Quadro P6000       WDDM  | 00000000:03:00.0 Off |                  Off |
| 26%   46C    P8    10W / 250W |   1667MiB / 24576MiB |      6%      Default |
+-------------------------------+----------------------+----------------------+
|   1  Quadro P6000       WDDM  | 00000000:04:00.0 Off |                  Off |
| 26%   45C    P8     8W / 250W |    152MiB / 24576MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0       524    C+G   ...x64__8wekyb3d8bbwe\Microsoft.Photos.exe N/A      |
|    0      1652    C+G   Insufficient Permissions                   N/A      |
|    0      1852    C+G   Insufficient Permissions                   N/A      |
|    0      1864    C+G   Insufficient Permissions                   N/A      |
|    0      4516    C+G   Insufficient Permissions                   N/A      |
|    0      6488    C+G   Insufficient Permissions                   N/A      |
|    0      6584    C+G   Insufficient Permissions                   N/A      |
|    0      7192    C+G   C:\Windows\explorer.exe                    N/A      |
|    0      7996    C+G   Insufficient Permissions                   N/A      |
|    0      9940    C+G   Insufficient Permissions                   N/A      |
|    0     10780    C+G   ...51.72.0_x64__kzf8qxf38zg5c\SkypeApp.exe N/A      |
|    0     11372    C+G   Insufficient Permissions                   N/A      |
|    0     11736    C+G   Insufficient Permissions                   N/A      |
|    0     12188    C+G   ...dows.Cortana_cw5n1h2txyewy\SearchUI.exe N/A      |
|    0     12668    C+G   ...t_cw5n1h2txyewy\ShellExperienceHost.exe N/A      |
|    0     12808    C+G   Insufficient Permissions                   N/A      |
|    0     13240    C+G   Insufficient Permissions                   N/A      |
|    0     13248    C+G   Insufficient Permissions                   N/A      |
|    0     13352    C+G   Insufficient Permissions                   N/A      |
|    0     14160    C+G   Insufficient Permissions                   N/A      |
|    0     15076    C+G   Insufficient Permissions                   N/A      |
|    0     16148    C+G   Insufficient Permissions                   N/A      |
|    0     16644    C+G   ...Files (x86)\Mozilla Firefox\firefox.exe N/A      |
|    0     17172    C+G   ...Files (x86)\Mozilla Firefox\firefox.exe N/A      |
|    0     17920    C+G   ...Files (x86)\Mozilla Firefox\firefox.exe N/A      |
|    0     18840    C+G   Insufficient Permissions                   N/A      |
|    0     20572    C+G   ...sktop App\AcWebBrowser\AcWebBrowser.exe N/A      |
|    0     21096    C+G   Insufficient Permissions                   N/A      |
|    0     21276    C+G   ...x86)\Microsoft Office\Office16\lync.exe N/A      |
|    0     21464    C+G   Insufficient Permissions                   N/A      |
|    0     24792    C+G   Insufficient Permissions                   N/A      |
|    0     24976    C+G   Insufficient Permissions                   N/A      |
|    0     28100    C+G   Insufficient Permissions                   N/A      |
|    0     28564    C+G   Insufficient Permissions                   N/A      |
|    0     28624    C+G   Insufficient Permissions                   N/A      |
|    0     28800    C+G   Insufficient Permissions                   N/A      |
|    0     30628    C+G   Insufficient Permissions                   N/A      |
|    0     31052    C+G   Insufficient Permissions                   N/A      |
|    0     31064    C+G   Insufficient Permissions                   N/A      |
|    0     31252    C+G   Insufficient Permissions                   N/A      |
|    0     32148    C+G   Insufficient Permissions                   N/A      |
|    0     32392    C+G   Insufficient Permissions                   N/A      |
|    0     32656    C+G   Insufficient Permissions                   N/A      |
|    0     33036    C+G   F:\software\Microsoft VS Code\Code.exe     N/A      |
|    0     35172    C+G   ...Files (x86)\Mozilla Firefox\firefox.exe N/A      |
+-----------------------------------------------------------------------------+

== cuda libs  ===================================================

== tensorflow installed from info ==================
Name: tensorflow
Version: 2.0.0rc0
Summary: TensorFlow is an open source machine learning framework for everyone.
Home-page: https://www.tensorflow.org/
Author-email: packages@tensorflow.org
License: Apache 2.0
Location: c:\users\mhn9\.virtualenvs\src-wzsttweo\lib\site-packages
Required-by: 

== python version  ==============================================
(major, minor, micro, releaselevel, serial)
(3, 6, 8, 'final', 0)

== bazel version  ===============================================

**Comment by daniel-falk** [comment]
I have the same problem when trying  a simple AutoGraph example form the 2.0 documentation.

I have tested in both python 3.7.2 and 3.5.6 both with tensorflow==2.0.0rc0.

A working colab example is found here:
https://colab.research.google.com/drive/1uDkPGwGd3l7Gv3-CCmELVsStlE4n-ndL

I tried to run the exact same python code locally, giving same issue with
"Cause: Bad argument number for Name: 3, expecting 4"
"OperatorNotAllowedInGraphError: iterating over `tf.Tensor` is not allowed: AutoGraph did not convert this function. Try decorating it directly with @tf.function."

See appended files for source code and full stdout + stderr.

[err.txt](https://github.com/tensorflow/tensorflow/files/3599222/err.txt)

[test_autograph.py.txt](https://github.com/tensorflow/tensorflow/files/3599230/test_autograph.py.txt)

**Comment by gadagashwini** [comment]
@hussain7 and @daniel-falk, Thanks for reporting the issue.
I could replicate the issue on my local system while it is working as expected on Colab.

**Comment by claverru** [comment]
Same is happening to me (on Colab but not on local):

WARNING:tensorflow:Entity <..> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: Bad argument number for Name: 3, expecting 4
WARNING: Entity <...> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: Bad argument number for Name: 3, expecting 4
[...] Repeated on sucesive functions

**Comment by tsimons89** [comment]
I am also experiencing this issue on my local machine.

**Comment by tsimons89** [comment]
My problem looks like it is originating from `tensorflow_core/python/autograph/pyct/templates.py` in the following function

```python
def _convert_to_ast(n):
  """Converts from a known data type to AST."""
  # Note: When generating AST nodes from strings/QNs in isolation, ctx is
  # unknown. ctx must be filled in according to the template being used.
  # See ReplaceTransformer.visit_Name.
  if isinstance(n, str):
    return gast.Name(id=n, ctx=None, annotation=None)
  if isinstance(n, qual_names.QN):
    return n.ast()
  if isinstance(n, list):
    return [_convert_to_ast(e) for e in n]
  if isinstance(n, tuple):
    return tuple(_convert_to_ast(e) for e in n)
  return n
```
Problematic line: 
```python
 return gast.Name(id=n, ctx=None, annotation=None)
```
The `gast.Name()` call (I have no prior experience with `gast`) seems to be complaining because it expects `type_comment` argument. It is checking for 4 arguments (`'id', 'ctx', 'annotation', 'type_comment'`) but it is only getting three.

This is from my `gast.py` where it states which arguments `gast.Name` should recive
```python
    'Name': (('id', 'ctx', 'annotation', 'type_comment'),
```

**Comment by hussain7** [comment]
right, switching to gast 0.2 version seems work for me as well.

**Comment by martinXie** [comment]
use gast 0.2.2 sovle my issue as well.

**Comment by lidar-nevermore** [comment]
I also experienced this bug and finnally sovled by switching to gast 0.2.2.

**Comment by datdinhquoc** [comment]
I face this error `Bad argument number for Name: 3, expecting 4` too.
It happens to me when using this on Colab:

```
%tensorflow_version 2.x
```

It works when using:

```
!pip install -q tensorflow==2.0.0-rc0
!pip freeze
```

**Comment by Jonathan-Oehley** [comment]
Similar error, gast 0.2.2 also solved for me

**Comment by lrxiao** [comment]
> I was using `gast 0.3.1` but switching to version `0.2.2` seems to have fixed this for me.
Could you tell me how to switch the version？

**Comment by hussain7** [comment]
pip install gast==0.2.2

**Comment by tpanza** [comment]
Duplicate of #32319 , which was fixed by c72125bd59858ec82a9238b232bbd77c45889c5a#diff-739fc4f018f5288972ae5826b15c36e7

However, [according to](https://github.com/tensorflow/tensorflow/issues/32319#issuecomment-537568070) @mihaimaruseac :
> New update:
> 
> `gast` has been pinned to 0.2.2 for 1.15 and 2.0 and later releases as well as nightly.
> TF 1.14 or earlier don't have `gast` pinned and won't get it as we are not doing more releases there (except for security vulnerabilities).
> 
> If you encounter this issue on 1.14 or earlier, please install gast==0.2.2 using pip before installing tensorflow.

**Comment by mihaimaruseac** [comment]
Closing as duplicate

**Comment by Carolyn95** [comment]
switch to gast==0.2.2 solve the problem for me as well.

**Comment by dgrahn** [comment]
I can confirm a switch to `gast==0.2.2` works. Is there additional information which would help debugging and resolving this?

**Comment by lrxiao** [comment]
I have solved this problem,thank you!




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Dan Grahn"<notifications@github.com&gt;;
发送时间:&nbsp;2019年10月31日(星期四) 晚上6:29
收件人:&nbsp;"tensorflow/tensorflow"<tensorflow@noreply.github.com&gt;;
抄送:&nbsp;"枭龙"<1447421123@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [tensorflow/tensorflow] tf Function could not able to transformed into graph. (#32383)




I can confirm a switch to gast==0.2.2 works. Is there additional information which would help debugging and resolving this?

**Comment by chandu8542** [comment]
Even after upgrading `gast` does not solve my issue.

> pip install gast==0.2.2
> Requirement already satisfied: gast==0.2.2 in /home/chandu/ckm/py3/lib/python3.5/site-packages (0.2.2)
> WARNING: You are using pip version 19.3.1; however, version 20.0.2 is available.
> You should consider upgrading via the 'pip install --upgrade pip' command.
> (py3) chandu@chandu-lenovo:~/ckm/code/text-mining/chandresh-code$ python
> Python 3.5.2 (default, Oct  8 2019, 13:06:37) 
> [GCC 5.4.0 20160609] on linux
> Type "help", "copyright", "credits" or "license" for more information.
> >>> import tensorflow as tf
> >>> tf.__version__
> '2.0.0'
>

**Comment by mihaimaruseac** [comment]
Can you reopen a new issue and fill in template, please? This issue has been closed and won't get updated anymore, since there are so many opened issue
