### ISSUE TITLE
The SessionOptions doesn't control the usage of CPU or Thread

### ISSUE THREAD

**Issue by Binbin16** [tensorflow/tensorflow#32396]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No, only use C++ API
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): SUSE 12.4
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below): 1.14.0
- Python version: 3.5
- Bazel version (if compiling from source): 0.24.1
- GCC/Compiler version (if compiling from source): gcc 4.8
- CUDA/cuDNN version: only CPU
- GPU model and memory: only CPU

**Describe the current behavior**
I created a session option with inter=1 and intra=1. Then I used this option to create a session and load a model.
When I run the model, the program used almost all the CPU cores on my server, and thread spawned to several hundreds.
And No matter what value I set to "inter" and "intra", there are still many CPU cores were used and many threads were created.

**Describe the expected behavior**
TF only use 1 thread and 1 cpu core

**Code to reproduce the issue**
  std::unique_ptr<tensorflow::Session> session;
  tensorflow::SessionOptions options;
  tensorflow::ConfigProto & config = options.config;
  int coresToUse = 1;
  if (coresToUse > 0)
    {
		config.set_use_per_session_threads(false);
		config.set_inter_op_parallelism_threads(coresToUse);
                config.set_intra_op_parallelism_threads(coresToUse);	
    }
  status = tensorflow::NewSession(options, session);
tensorflow::MetaGraphDef graph_def;
tensorflow::ReadBinaryProto(tensorflow::Env::Default(), metamodel_path, &graph_def);
session->Create(graph_def.graph_def());
run_model();

**Other info / logs**
When I use the python API of TensorFlow 1.14 do the same thing, it seems like the CPU and thread usage can be controlled by the inter and intra parameter.

How to control the computing resources used by tensorflow C++ API?

#32009 @JiayiFu @ezhulenev I saw the similar problem described here, but don't know its solution.

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.
