### ISSUE TITLE
TensorBoard Documentation - Confusing and Incorrect in places. (Need End to End Example)

### ISSUE THREAD

**Issue by mchirico** [tensorflow/tensorflow#324]
It would be nice to have a complete, end-to-end working example using TensorBoard.  In addition, some of the documentation appears to be incorrect.

Possible Incorrect Documentation:
http://tensorflow.org/how_tos/summaries_and_tensorboard/index.md

<img width="731" alt="screenshot 2015-11-22 10 42 18" src="https://cloud.githubusercontent.com/assets/755710/11324647/bc5560d8-9105-11e5-8293-ddd36cf7c946.png">

A concise, completely coded example may help. Note, more detail is shown here, but it's still have hard to grasp the full picture.  A complete coded example may help.

```python

...
sess.run(init)

# Build the summary operation based on the TF collection of Summaries.
tf.train.write_graph(sess.graph_def, './tenIrisSave/logsd','graph.pbtxt')

tf.scalar_summary("Accuracy:", tf_accuracy)
tf.histogram_summary('weights', tf_weight)
tf.histogram_summary('bias', tf_bias)
tf.histogram_summary('softmax', tf_softmax)
tf.histogram_summary('accuracy', tf_accuracy)


summary_op = tf.merge_all_summaries()
summary_writer = tf.train.SummaryWriter('./tenIrisSave/logs',sess.graph_def)

# This will not work. You need the full path.
# tensorboard --logdir=./tenIrisSave/   # BAD!
# tensorboard --logdir=$(pwd)/tenIrisSave/  # Good!
...
for i in range(100):
   ...
    summary_str = sess.run(summary_op,feed_dict={tf_in: x_test, tf_softmax_correct: y_test_onehot})
    summary_writer.add_summary(summary_str, i)


```

The complete example can be seen here:
https://gist.github.com/mchirico/bcc376fb336b73f24b29

Agreed. The example needs to be cleaned up. The point is to give the user a complete working example that can be run and verified.

**Comment by facadev** [comment]
You are right. sess.graph is a typo there, which should be corrected with sess.graph_def, and sess.run() for session.run(). Actually you can also find some other inconsistencies here and there in the documentation. It takes patience to figure them out yourself. :)

**Comment by ascenator** [comment]
"It takes patience to figure them out yourself": definitely! This is especially frustrating for beginners. Why doesn't Google test the code supplied in the documentation first? I spent hours for figuring out those inconsistencies :/

**Comment by danmane** [comment]
Fixed, the current version of the doc doesn't have these typos and has a full, runnable code example.
(And the code example is even tested.)

**Comment by CharlesJQuarra** [comment]
can you link the commit that fixed this issue?

**Comment by CharlesJQuarra** [comment]
also why has all these 'summaries' be added to display the already existing graph? supposedly the graph exists even with no summaries added, why can't the underlying graph be rendered without summaries?
