### ISSUE TITLE
Possible issue in tf.scatter_nd documentation.

### ISSUE THREAD

**Issue by praveenjune17** [tensorflow/tensorflow#32410]
Thank you for explaining about tf.scatter_nd using some wonderful visualizations. I have a doubt whether the cubes used for the higher dimensional explanation of tf.scatter_nd is right or not.
Please check the visualization of the Cube tagged as 'output' in [tf.scatter_nd](https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/scatter_nd#) documentation, the second and fourth indices are shaded whereas the given indices according to the example is tf.constant([[0], [2]]) so the first and third indices (0 , 2) should be shaded instead of second and fourth. Please correct me if I'm wrong

**Comment by praveenjune17** [comment]
Instead of changing the cube, it would be better if we change indices 
From
indices = tf.constant([[0], [2]]) 
To 
indices = tf.constant([[1], [3]])

**Comment by rmothukuru** [comment]
@praveenjune17,
Sorry for the delayed response. I think it's a [good idea](https://github.com/tensorflow/tensorflow/issues/32410#issuecomment-530669422).  

Created [a CL](https://critique-ng.corp.google.com/cl/370902959) to fix it.

**Comment by mohantym** [comment]
Hi @praveenjune17 @MarkDaoust @yashk2810 
Created Fresh [CL](https://critique.corp.google.com/cl/469640409) by Patching above [CL](https://critique.corp.google.com/cl/370902959) . 
Thank you!

**Comment by MarkDaoust** [comment]
LGTM, thanks.

**Comment by mohantym** [comment]
Hi @MarkDaoust !
Changes has not reflected yet in documentation though. Will it take some time to reflect or Shall I create a PR through Github .
