### ISSUE TITLE
[lite/micro] missing delete() in GreedyMemoryPlanner

### ISSUE THREAD

**Issue by csukuangfj** [tensorflow/tensorflow#32416]
https://github.com/tensorflow/tensorflow/blob/8c0df1fa0b0490d8b1e54d7b019e2b2242ad6718/tensorflow/lite/experimental/micro/memory_planner/greedy_memory_planner.h#L43

does not override `void operator delete(void *p)` which results in link time error.

**Comment by jvishnuvardhan** [comment]
@csukuangfj Is this resolved or still an issue? Thanks!

**Comment by csukuangfj** [comment]
@jvishnuvardhan 
when this pullrequest https://github.com/tensorflow/tensorflow/pull/32417 is merged,
this issue should be closed by GitHub automatically; but more than 3 months have passed,
it is still not merged.

**Comment by jvishnuvardhan** [comment]
@csukuangfj I see the reviewer approved the PR. So it will be merged soon. Thanks!

**Comment by csukuangfj** [comment]
@jvishnuvardhan 

Things are not always that easy like you thought. You can see that the pullrequest
has been approved for multiple times, but nothing happens when  the`ready to pull`
label is added.
