### ISSUE TITLE
TF2.0 - Multiple calls to Keras .fit and .evaluate makes RAM explode and is 25x slower

### ISSUE THREAD

**Issue by grananqvist** [tensorflow/tensorflow#32420]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): MacOS Mojave
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): pip
- TensorFlow version (use command below): 2.0.0-dev20190909
- Python version: 3.6.5
- Bazel version (if compiling from source): -
- GCC/Compiler version (if compiling from source): -
- CUDA/cuDNN version: -
- GPU model and memory: -

**Describe the current behavior**
(Everything is done on the CPU)
Consecutive calls to either `.fit()` or `.evaluate()` increase the RAM used, even if calling with the same data. The calls takes approximately 10 times longer than with TF1.x

**Describe the expected behavior**
I expect the RAM usage to remain constant just like in TF1.x

**Code to reproduce the issue**

```python
from memory_profiler import profile
from time import time
import numpy as np
import tensorflow as tf

model = tf.keras.Sequential([tf.keras.layers.Dense(100, activation=tf.nn.softmax)])
model.compile(loss='mse', optimizer='sgd')

@profile
def eval(x, y):
    model.evaluate(x, y)

x = np.random.normal(size=(1,100))
y = np.random.normal(size=(1,100))

for i in range(100000):
    print('iteration', i)
    tic = time()
    eval(x, y)
    print('timeit', time() - tic)
```

Using TF2.0. 229MB RAM used and evaluate completed in 99ms
```
iteration 20
Train on 1 samples
1/1 [==============================] - 0s 10ms/sample - loss: 1.0597
Filename: reproduce_keras_oom.py

Line #    Mem usage    Increment   Line Contents
================================================
     9    228.8 MiB    228.8 MiB   @profile
    10                             def eval(x, y):
    11    229.1 MiB      0.2 MiB       model.evaluate(x, y)

timeit 0.09978580474853516
```

Using TF2.0 1508MB RAM used after calling `.evaluate()` 3312 times.
```
iteration 3312
1/1 [==============================] - 0s 4ms/sample - loss: 1.0205
Filename: reproduce_keras_oom.py

Line #    Mem usage    Increment   Line Contents
================================================
     9   1508.3 MiB   1508.3 MiB   @profile
    10                             def eval(x, y):
    11   1508.7 MiB      0.4 MiB       model.evaluate(x, y)

timeit 0.09004998207092285
```

Using TF1.x, the RAM used is not increasing over consecutive calls of `.evaluate()`. RAM stays at 176MB indefinitely (iteration 5100 below). **Also note that it is 25 times faster!**
```
iteration 5100
1/1 [==============================] - 0s 1ms/sample - loss: 1.2716
Filename: reproduce_keras_oom.py

Line #    Mem usage    Increment   Line Contents
================================================
     9    176.0 MiB    176.0 MiB   @profile
    10                             def eval(x, y):
    11    176.0 MiB      0.0 MiB       model.evaluate(x, y)

timeit 0.004405021667480469
```

I just discovered that wrapping `(x, y)` into a `tf.data.Dataset` does not have this issue!
Modified code:
```python
from memory_profiler import profile
from time import time
import numpy as np
import tensorflow as tf

model = tf.keras.Sequential([tf.keras.layers.Dense(100, activation=tf.nn.softmax)])
model.compile(loss='mse', optimizer='sgd')

@profile
def eval(dataset):
    model.evaluate(dataset)

x = np.random.normal(size=(1,100))
y = np.random.normal(size=(1,100))

dataset = tf.data.Dataset.from_tensor_slices((x, y))
dataset = dataset.batch(1)

for i in range(100000):
    print('iteration', i)
    tic = time()
    eval(dataset)
    print('timeit', time() - tic)
```

Using `tf.data.Dataset`, there is no exploding RAM. 217 MB RAM used after calling `.evaluate()` 8154 times. It is also only 2.5 times slower than TF1.x
```
iteration 8154
1/1 [==============================] - 0s 3ms/step - loss: 0.9972
Filename: reproduce_keras_oom.py

Line #    Mem usage    Increment   Line Contents
================================================
     9    217.6 MiB    217.6 MiB   @profile
    10                             def eval(dataset):
    11    217.6 MiB      0.0 MiB       model.evaluate(dataset)

timeit 0.010456085205078125
```

**Comment by grananqvist** [comment]
From what I see in the notebook, using profile to measure the RAM consumption does not work in jupyter

**Comment by jvishnuvardhan** [comment]
@grananqvist Sorry for the delay in response. Can you please try `tf-nightly` and compare that with `TF1.15.0rc3`. I see similar runtime (~0.004) with `tf-nightly` and `TF1.15.0rc3`. Please let us know what you think. Thanks!

**Comment by jvishnuvardhan** [comment]
@grananqvist Did you had time to review my comments? Thanks!

**Comment by grananqvist** [comment]
Sorry I have not had the time to test this yet.

**Comment by jvishnuvardhan** [comment]
Automatically closing this out since I understand it to be resolved, but please let me know if I'm mistaken.Thanks!

**Comment by khatchad** [comment]
Would using `tf.function` help in this situation?
