### ISSUE TITLE
undefined reference to `tensorflow::str_util::EndsWith

### ISSUE THREAD

**Issue by dibet** [tensorflow/tensorflow#32425]
On Kubuntu 18.08 
TensorFlow 1.13 installed from source.
Python 3.6
Bazel 19.2
GCC 7.4.0
 
In the past, i have a tested program in ubuntu 16.04 and it run fine. I make the migration to ubuntu 18.04, recompile tensorflow for c++ and obtain the libraries libtensorflow_cc.so and libtensorflow_framework.so.
When i tried to compile my program using "cmake .. && make"  see the following messages:

tensorflowlabelimageclassification.cpp:(.text+0x2bff): undefined reference to `tensorflow::str_util::EndsWith(std::basic_string_view<char, std::char_traits<char> >, std::basic_string_view<char, std::char_traits<char> >)'
tensorflowlabelimageclassification.cpp:(.text+0x2d3c): undefined reference to `tensorflow::str_util::EndsWith(std::basic_string_view<char, std::char_traits<char> >, std::basic_string_view<char, std::char_traits<char> >)'
tensorflowlabelimageclassification.cpp:(.text+0x2ee3): undefined reference to `tensorflow::str_util::EndsWith(std::basic_string_view<char, std::char_traits<char> >, std::basic_string_view<char, std::char_traits<char> >)'

Any help?
Thanks.
Dibet

**Describe the problem**

**Provide the exact sequence of commands / steps that you executed before running into the problem**

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by gadagashwini** [comment]
@dibet, The TensorFlow team does not officially support cmake, sorry. Please try out with Bazel.

**Comment by dibet** [comment]
Hi, i just write to inform how i resolve my problem.
In the past (ubuntu 16.04 and gcc 5) i was compiling using  -std=c++17.
Now, on ubuntu 18.04 and gcc 7 i need to use  -std=c++14 
I don't know the reason but i fix it in that way.
Thanks.

**Comment by ymodak** [comment]
Thanks for sharing your resolution. Closing since its resolved. Thanks!
