### ISSUE TITLE
No rule to make target '/home/ai002/tensorflow_Cpp/add0/tensorflow_cpp2/tensorflow-1.11.0/tensorflow/contrib/makefile/gen/proto/tensorflow/core/util/test_log.pb.cc', needed by '/home/ai002/tensorflow_Cpp/add0/tensorflow_cpp2/tensorflow-1.11.0/tensorflow/contrib/makefile/gen/obj/tensorflow/contrib/boosted_trees/proto/learner.pb.o'.  Stop.

### ISSUE THREAD

**Issue by BlackDeal** [tensorflow/tensorflow#32424]
tensorflow 1.11.0
bazel 0.18.0
When i run sudo ./tensorflow/contrib/makefile/build_all_linux.sh...... help me ! thank you hardly!!!
No rule to make target '/home/ai002/tensorflow_Cpp/add0/tensorflow_cpp2/tensorflow-1.11.0/tensorflow/contrib/makefile/gen/proto/tensorflow/core/util/test_log.pb.cc', needed by '/home/ai002/tensorflow_Cpp/add0/tensorflow_cpp2/tensorflow-1.11.0/tensorflow/contrib/makefile/gen/obj/tensorflow/contrib/boosted_trees/proto/learner.pb.o'.  Stop.

**Comment by oanush** [comment]
@BlackDeal ,
Provide the exact sequence of commands / steps that you executed before running into the problem.Thanks!

**Comment by oanush** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
