### ISSUE TITLE
Int32 overflow in sparse_reshape on Windows

### ISSUE THREAD

**Issue by ThomasOerkild** [tensorflow/tensorflow#32434]
**System information**
- OS Platform and Distribution: Windows 10 64-bit
- TensorFlow installed from: Source
- TensorFlow version: 1.14.0
- Python version: 3.6.7

**Describe the current behavior**
When a large sparse tensor is reshaped using `sparse_reshape` on Windows it fails, due to the fact that it uses `np.prod` to determine whether the number of elements in the old and new SparseTensor are the same. This can fail on Windows, due to the fact that numpy converts python ints to dtype np.int32 on Windows, which will overflow for large dimensions.

**Describe the expected behavior**
`sparse_reshape` should work similarly on both Windows and Unix-based systems.

**Code to reproduce the issue**
```python
import tensorflow as tf
tf.enable_eager_execution()

idxs = tf.constant([[1, 0, 1],
                             [1, 4, 2]], dtype=tf.int64)
values = tf.constant([12, 42])

A = tf.sparse.SparseTensor(idxs, values, (8, 42000, 40000))
tf.sparse.reshape(A, (8, 40000, 42000))
```

Output:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\thomasoerkild\Anaconda3\envs\tf_gpu\lib\site-packages\tensorflow\python\ops\sparse_ops.py", line 769, in sparse_reshape
    reshaped_size))
ValueError: Cannot reshape a tensor with 555098112 elements to shape [8, 40000, 42000] (13440000000 elements).
```

**Other info / logs**
The issue might be resolved, by forcing the shape inputted to `np.prod` to be of type np.int64.

**Comment by chunduriv** [comment]
@ThomasOerkild,

Sorry for the late response. This issue was fixed. 

```
import tensorflow as tf

idxs = tf.constant([[1, 0, 1],
                             [1, 4, 2]], dtype=tf.int64)
values = tf.constant([12, 42])

A = tf.sparse.SparseTensor(idxs, values, (8, 42000, 40000))

B = tf.sparse.reshape(A, (8, 40000, 42000))

print(B)

```
Output:
```
SparseTensor(indices=tf.Tensor(
[[    1     0     1]
 [    1     3 34002]], shape=(2, 3), dtype=int64), values=tf.Tensor([12 42], shape=(2,), dtype=int32), dense_shape=tf.Tensor([    8 40000 42000], shape=(3,), dtype=int64))
```






Thank You.
