### ISSUE TITLE
TFRecordWriter doesn't work from TFRecordsDataset

### ISSUE THREAD

**Issue by SumNeuron** [tensorflow/tensorflow#32459]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): barely
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): 16.04 LTS
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: n/a
- TensorFlow installed from (source or binary): conda
- TensorFlow version (use command below): 1.14
- Python version: 3.6
- Bazel version (if compiling from source): n/a
- GCC/Compiler version (if compiling from source): n/a
- CUDA/cuDNN version: 10
- GPU model and memory: quadro 16gb

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**

Would like to write `TFRecordsDataset` to files using [`TFRecordWriter`](https://github.com/tensorflow/tensorflow/blob/r1.14/tensorflow/python/data/experimental/ops/writers.py#L30-L61), however it complains that it does not match the right format... which is odd as given the [tutorial](https://www.tensorflow.org/tutorials/load_data/tf_records) one would think this is possible

**Describe the expected behavior**

It "just works"

**Code to reproduce the issue**

```python
files = ['file_with_n.tfrecords', 'aother_file_with.tfrecords', ...]
n_records = # 

ds = tf.data.TFRecordDataset(files)
# pre-shuffle all data and then use smaller shuffle buffer size and shuffle files during training
ds = ds.shuffle(n_records)
ds = ds.batch(records_per_file)
for i, batch in enumerate(ds):
    o_file = 'part_{}.tfrecord'.format(i)   
    batch_ds = tf.data.Dataset.from_tensors(batch) # <--- batch is back as a DataSet
    batch_ds = batch_ds.batch(1).map(lambda e: tf.reshape(e,(-1,)))
    writer = tf.data.experimental.TFRecordWriter(o_file)
    writer.write(batch_ds)
```
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by ravikyram** [comment]
Please, help us to provide standalone code snippet to reproduce the issue in our environment.Thanks!

**Comment by SumNeuron** [comment]
@ravikyram not really needed as it I link to the tutorial and all I did was batch and iterator over the sequences....

that said, I found _my_ mistake. 

replace `tf.data.Dataset.from_tesnors(batch)` with `tf.data.Dataset.from_tensor_slices(batch)` and it works.
