### ISSUE TITLE
TensorShapeBase parameter list in .so differs from header, undefined reference 

### ISSUE THREAD

**Issue by Randryn0** [tensorflow/tensorflow#32461]
**System information**
- Have I written custom code: yes
- OS Platform and Distribution: Linux Mint 18.3 Xfce 64-bit, 4.15.0-45-generic #48~16.04.1-Ubuntu
- TensorFlow installed from: source
- TensorFlow version: r1.10 and r1.12
- Python version: Python 2.7.12
- Bazel version: 0.19.2
- GCC/Compiler version: gcc (Ubuntu 5.4.0-6ubuntu1~16.04.11) 5.4.0 20160609
- GPU model and memory: Integrated Intel HD inside a virtual machine

I have compiled the tensorflow C++ api libraries from source for versions r1.10 and r1.12 on my Linux machine, thus I get a libtensorflow_cc.so (or libtensorflow.so) and libtensorflow_framework.so. I simply used `bazel build --config=opt //tensorflow:libtensorflow_cc.so` to do this.

The problem arises when I try to include the libraries in a project of mine. When compiling I get the following linker errors:
`mydir/myfile.o: In function 'tensorflow::TensorShapeBase<tensorflow::TensorShape>::TensorShapeBase(std::initializer_list<long long>)':
~/myproject/include/tensorflow/tensorflow/core/framework/tensor_shape.h:172: undefined reference to 'tensorflow::TensorShapeBase<tensorflow::TensorShape>::TensorShapeBase(tensorflow::gtl::ArraySlice<long long>)'
~/myproject/include/tensorflow/tensorflow/core/framework/tensor_shape.h:172: undefined reference to 'tensorflow::TensorShapeBase<tensorflow::TensorShape>::TensorShapeBase(tensorflow::gtl::ArraySlice<long long>)'
~/myproject/include/tensorflow/tensorflow/core/framework/tensor_shape.h:172: undefined reference to 'tensorflow::TensorShapeBase<tensorflow::TensorShape>::TensorShapeBase(tensorflow::gtl::ArraySlice<long long>)'
collect2: error: ld returned 1 exit status`

And it's true. When I do
`nm -D libtensorflow_cc.so | c++filt | grep TensorShapeBase`
I get
`U tensorflow::TensorShapeBase<tensorflow::TensorShape>::TensorShapeBase(absl::Span<long long const>)`
and the same for `libtensorflow_framework.so`:
`000000000049deb0 W tensorflow::TensorShapeBase<tensorflow::TensorShape>::TensorShapeBase(absl::Span<long long const>)`.

However, when looking in `tensorflow/core/framework/tensor_shape.h` it does say starting at line 171:
`TensorShapeBase(std::initializer_list<int64> dim_sizes)
: TensorShapeBase(gtl::ArraySlice<int64>(dim_sizes)) {}` 

How can this issue be fixed? Why does it compile the library with different parameters than what is inside the header?

Cheers

btw: I also compiled a 800 MB libtensorflow.so with cmake but it doesn't work due to runtime problems concerning some estimator - from what I can see, though, it does have the correct parameter in the call.

**Comment by ymodak** [comment]
I suspect tensorflow failed to build successfully. Can you use Bazel 0.15.0 to build TF and try again?
https://www.tensorflow.org/install/source#tested_build_configurations
