### ISSUE TITLE
[tflite] Support INT8 quantisation for SPLIT with TFLITE_BUILTINS_INT8 OpsSet

### ISSUE THREAD

**Issue by MohamedNourArm** [tensorflow/tensorflow#32464]
**System information**
- TensorFlow version (you are using): 1.14 and built from sources, master branch
- Are you willing to contribute it (Yes/No): Yes

**Describe the feature and the current behavior/state.**

The new TFLiteConverter post-training quantisation flow, as described in https://www.tensorflow.org/lite/performance/post_training_quantization#full_integer_quantization_of_weights_and_activations, does not support quantisation of SPLIT operation when only integer operations are requested in the output model. When this conversion is forced, the Runtime Error "Quantization not yet supported for op: SPLIT" is raised. The following code can be used to recreate the error
```
import tensorflow as tf
import numpy as np

def representative_dataset_gen():
	input = np.array(np.random.random_sample([2,10]), dtype=np.float32)
	for _ in range(10):
		yield [input]

# tf Graph Input 
in_intact = tf.compat.v1.placeholder("float32", [2, 10])
out_split = tf.split(in_intact,2,axis=0)

with tf.compat.v1.Session() as sess:
	tf.io.write_graph(tf.compat.v1.get_default_graph(), '.','split.pb', as_text=False)

input_name = ["Placeholder"]
output_name = ["split", "split:1"]

tflite_model_name = "int8_split.tflite"
converter = tf.lite.TFLiteConverter.from_frozen_graph("split.pb", input_name, output_name)
converter.optimizations = [tf.lite.Optimize.DEFAULT]
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
converter.representative_dataset = representative_dataset_gen
tflite_model = converter.convert()
open(tflite_model_name, "wb").write(tflite_model)
```

**Will this change the current api? How?**
No

**Who will benefit with this feature?**
Anyone who attempts full 8-bit fixed point quantisation of models containinig SPLIT operation, present in some versions of Deepspeech.

**Any Other info.**
Note that there are separate TFLite implementations, SPLIT and SPLIT_V, for two different behaviors of Tensorflow's tf.split. This request is related only to SPLIT, although after implementing it, SPLIT_V can probably similarly be implemented.

**Comment by MohamedNourArm** [comment]
This was resolved by commit [3c2be61e68acea533030b8f70fa0db3339b19f93](https://github.com/tensorflow/tensorflow/commit/3c2be61e68acea533030b8f70fa0db3339b19f93#diff-69178ece8d1001b2ef7f9b329e9a525b)

**Comment by JohannSchumann** [comment]
Hi,

I got into some problem there: My TF model has split.
*) conversion/post-training quantization with TF 1.14 and TF 1.15 fails with error above
*) conversion/post-training quantization with TF 2.2 works, but the edgetpu_compiler crashes with "internal compiler error". 
It looks like I would need to use TF 1.X if I want to use edgetpu_compiler, but can't because the SPLIT isn't
fixed on that.
Any ideas would be helpful!

Thanks!

**Comment by MohamedNourArm** [comment]
Hi Johann, Sorry for the late reply.

To your first (and first half of the second) point, the SPLIT operator support was only incorporated into the main release starting TF version 2.1, so that is the expected behaviour. The second issue comes from the [edgetpu](https://github.com/google-coral/edgetpu) compiler, which is not related to this issue and the relevant commit. 

According to the [coral supported ops documentation](https://coral.ai/docs/edgetpu/models-intro/#supported-operations) SPLIT is supported except for the batch dimension, so that could be the problem. If you are not attempting to split along the batch dimension, consider raising an issue in the edgetpu repo (also worth debugging to make sure it is in fact caused by this particular operator in the first place; if not, raise a general issue on the problem, or preferably having isolated what exactly causes it).

Hope this helps!

**Comment by JohannSchumann** [comment]
Hi,

Thanks for your response.
I was able to narrow down the error, where the edgetpu_compiler crashes: it
was in the "reshape" operation (not in
the split). Following your advice, I posted an issue to the edgetpu repo
(#173)

Thanks!
-johann
