### ISSUE TITLE
[TF 2.0] AutoGraph: Jacobian docs example could not be transformed

### ISSUE THREAD

**Issue by matsen** [tensorflow/tensorflow#32479]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): no
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Debian stretch in Crostini ❤️ 
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): `pip install --upgrade tf-nightly-2.0-preview`
- TensorFlow version (use command below): v1.12.1-10936-g3c7062c 2.0.0-dev20190912
- Python version: 3.7.4

**Describe the current behavior**

When I run the example code from https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/GradientTape#example_usage_2

I get this: 

```
(libsbn) x86_64-conda_cos6-linux-gnu libsbn/python ‹103-branch-length*› » export AUTOGRAPH_VERBOSITY=10 && python autograph_issue.py 
2019-09-12 14:14:23.681818: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2019-09-12 14:14:23.689486: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 1607975000 Hz
2019-09-12 14:14:23.689916: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x5c529e0a3cf0 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2019-09-12 14:14:23.689979: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
WARNING:tensorflow:Entity <function pfor.<locals>.f at 0x7ebbe2511e60> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: No module named 'tensorflow_core.estimator'
```

**Describe the expected behavior**

To compute the Jacobian without complaining.

**Code to reproduce the issue**

From the example, 

```python
import tensorflow.compat.v2 as tf
tf.enable_v2_behavior()

with tf.GradientTape() as g:
    x  = tf.constant([1.0, 2.0])
    g.watch(x)
    y = x * x
jacobian = g.jacobian(y, x)
```

**Other info / logs**

**Comment by matsen** [comment]
Thanks for having a look @gadagashwini ! 

I am also using `tfp-nightly`. When I add that to the pip install line in the colab notebook it does indeed throw an error.

It does give the correct answer, but does it not come with a speed penalty or something?

**Comment by matsen** [comment]
I just did some testing and this does come with a performance penalty.

To clarify the issue:
```
pip install --upgrade tf-nightly-2.0-preview
```
works great with no errors, while
```
pip install --upgrade tf-nightly-2.0-preview tfp-nightly
```
throws errors and is slower.

**Comment by csuter** [comment]
I can't repro this with current nightlies in the given colab. I tried pinning the tf nightly to 20190912 and it still doesn't cause any errors. Is there still a reproducible example of this issue?

There were some bad tf-nightly-2.0-preview pushes in the last week, causing estimator not to be importable. It's possible that this only manifested alongside TFP because TF lazily loads modules and importing TFP was somehow causing TF to try to non-lazily load estimator.

It sounds like the failure to import estimator was causing issues for pfor/autograph/xla compilation, which could explain the slowness.

If someone can share a reproducible-as-of-today example (possibly pinning pip packages to earlier versions?) I'm happy to try to help debug.

**Comment by matsen** [comment]
I just re-pulled from nightly and ISSUE FIXED! 🎉 

Thanks for making my day, @csuter ! I owe you a 🍺 , wherever you are.
