### ISSUE TITLE
tensorflow does not detect 2nd GPU

### ISSUE THREAD

**Issue by cyrus2018** [tensorflow/tensorflow#32489]
Hi,

I am trying to use 2 GPUs, tensorflow does not recognise the 2nd one. the 2nd GPU is working fine (in widows environment).

using tensorflow example: tf.keras.utils.multi_gpu_model, https://www.tensorflow.org/api_docs/python/tf/keras/utils/multi_gpu_model

I see the follwing error

ValueError: To call `multi_gpu_model` with `gpus=2`, we expect the following devices to be available: ['/cpu:0', '/gpu:0', '/gpu:1']. However this machine only has: ['/cpu:0', '/gpu:0']. Try reducing `gpus`.

I can switch between the two graphic cards, with CUDA VISIBLE DEVICE , which sets one of the GPUs to GPU 0. however both can not be used. device 0 and device 1 are recognised however one GPU is only recognised.

The main GPU is RTX2070 (8GB) and 2nd GPU is GTX1050 (2GB). Before i submit i spent sometime searching for solution and did whatever I could find on the internet. drivers are up to date, 64bit version and latest versions of the software are installed. I dont see any issue, beside not appearing the 2nd GPU. The codes are working fine on first GPU, both have > 3.5 computational capacity.

**Comment by oanush** [comment]
@cyrus2018 ,
Can you please mention the TF version being used and also provide a simple standalone code to replicate the issue.Thanks!

**Comment by cyrus2018** [comment]
TF GPU version is 1.13.1 , I had downgraded from  1.14 (due to seeing another error running the same code).

below is the exact code I use. Regradless of number of GPUs, you see the same error (I have actually 2 installed).

import tensorflow as tf
from keras.applications import Xception
from keras.utils import multi_gpu_model
import numpy as np

num_samples = 1000
height = 224
width = 224
num_classes = 1000

with tf.device('/cpu:0'):
       model = Xception(weights=None,
                         input_shape=(height, width, 3),
                         classes=num_classes)

parallel_model = multi_gpu_model(model, gpus=2)
parallel_model.compile(loss='categorical_crossentropy',
                           optimizer='rmsprop')

x = np.random.random((num_samples, height, width, 3))
y = np.random.random((num_samples, num_classes))


parallel_model.fit(x, y, epochs=20, batch_size=256)

model.save('my_model.h5')

ValueError: To call `multi_gpu_model` with `gpus=2`, we expect the following devices to be available: ['/cpu:0', '/gpu:0', '/gpu:1']. However this machine only has: ['/cpu:0', '/gpu:0']. Try reducing `gpus`.


![TF version](https://user-images.githubusercontent.com/45702408/64855383-5730f780-d652-11e9-8378-d98162f75ed4.JPG)

**Comment by jvishnuvardhan** [comment]
@cyrus2018 I don't think this is a bug in Tensorflow. 
Can you try to run the following lines to see how many gpus are visible to TF.
```
import tensorflow as tf
tf.test.gpu_device_name()
```
Please check this [resource](https://www.quora.com/If-you-have-2-graphics-cards-and-1-computer-how-can-you-use-them-at-the-same-time). 
TL/DR: this resource mentions that you need `SLI bridge` for cooperation between GPUs. Also, expects `your graphics cards are the same model` and mentions `Older boards often did not allow the presence of a second graphic card.`. Please go through that resource.

Thanks!

**Comment by cyrus2018** [comment]
Thanks for the info, please see below:
I checked the link you shared. I dont think to use TF, the GPUs should be the same exact model/brand. Is that the case? I have Gigabyte Z390M gaming motherboard, with two PCIs. the thing is, I can run my models right now on any of the GPUs below, with TF, no issues at all. both GPUs are pretty good..

but when it comes to using two GPUs the system does not identify the 2nd one...which is weird.. can not get GPU:1 recognised. 

In [1]: import tensorflow as tf
   ...: tf.test.gpu_device_name()
Out[1]: '/device:GPU:0'


Also when i set:
os.environ["CUDA_VISIBLE_DEVICES"]='0'
physical_device_desc: "device: 0, name: GeForce RTX 2070, pci bus id: 0000:01:00.0, compute capability: 7.5

os.environ["CUDA_VISIBLE_DEVICES"]='1'
physical_device_desc: "device: 0, name: GeForce GTX 1050, pci bus id: 0000:04:00.0, compute capability: 6.1"

**Comment by cyrus2018** [comment]
Please see the attachments. 

now using TF 1.9, setting os.environ["CUDA_VISIBLE_DEVICES"]='1' casues no reaction from Tpython/TF.. i changed os.environ["CUDA_VISIBLE_DEVICES"]to different digits and combination, any attempt to input 1, causes the Tf stop responding. 

![1](https://user-images.githubusercontent.com/45702408/65198559-228bc880-dab6-11e9-831f-10d81522fe5a.JPG)
[Qyarry.docx](https://github.com/tensorflow/tensorflow/files/3628814/Qyarry.docx)

**Comment by aaroey** [comment]
@cyrus2018 could you share the printed log messages when you run `tf.test.gpu_device_name()`?

**Comment by aaroey** [comment]
Also could you try with TF 1.15.0rc1?

**Comment by cyrus2018** [comment]
> @cyrus2018 could you share the printed log messages when you run `tf.test.gpu_device_name()`?

The thing is my TF works and recognises with 1 GPU (GPU 0) it can either be the RTX1070 or GTX1050 (both workwith no issue). so single GPU no problem, GPU 1 never recognised.
![2](https://user-images.githubusercontent.com/45702408/65289208-647f4200-db7c-11e9-93f3-b96b8ccc1c65.JPG)

**Comment by cyrus2018** [comment]
> TF 1.15.0rc1

![3](https://user-images.githubusercontent.com/45702408/65289838-fb4cfe00-db7e-11e9-8a0a-d66137f55c1c.JPG)

**Comment by aaroey** [comment]
@cyrus2018 did you disable TF logging? Normally it should print something like:
```
2019-09-20 06:59:20.328108: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1304] Created TensorFlow device (/device:GPU:0 with 11161 MB memory) -> physical GPU ...
```

**Comment by cyrus2018** [comment]
Added below to top of the codes, issue is resolved
NOTE:: TF_MIN_GPU_MULTIPROCESSOR_COUNT defauls value is 8


import os
os.environ["TF_MIN_GPU_MULTIPROCESSOR_COUNT"]="2"
os.environ["CUDA_VISIBLE_DEVICES"]="0,1"

**Comment by bracagranda** [comment]
@cyrus2018 I am currently facing the same issue where tensorflow is actually running with the GPU:0 that is an Intel Graphic one, while it is not recognizing the NVIDIA one which is the GPU:1. Could you please share the code?

**Comment by U-Abhishek** [comment]
@cyrus2018  still facing the same issue

**Comment by Ling-Jun** [comment]
same issue,  tensorflow is actually running with the GPU:0 that is an Intel Graphic one, while it is not recognizing the NVIDIA one which is the GPU:2
