### ISSUE TITLE
ODR violations between cuDNN and TensorRT

### ISSUE THREAD

**Issue by sanjoy** [tensorflow/tensorflow#32480]
_This reports an issue with an NVIDIA library and **not** a bug in TensorFlow. This issue serves as a public description and permalink._

There are [One Definition Rule (ODR)](https://en.wikipedia.org/wiki/One_Definition_Rule) violations between TensorRT and cuDNN that can cause binaries that link in both these libraries to crash or misbehave.  We observed this with the combination of TensorRT 5.1.5 and cuDNN 7.6.2 linked statically. We don’t know if builds that use shared libraries are affected.

For instance, both TensorRT 5.1.5 and cuDNN 7.6.2 define `_Z22first_layer_fwd_kernelILi4ELi7ELi7ELi64EEv19FirstLayerFwdParams` (demangled: `void first_layer_fwd_kernel<4, 7, 7, 64>(FirstLayerFwdParams)`) but SASS blobs corresponding to these kernels are not the same in TensorRT and cuDNN.  This means that in an application that links in both TensorRT and cuDNN, one of the two libraries will launch the incorrect kernel.  Observed failures manifest as GPU side crash due to misaligned memory access or data corruption.

We have informed NVIDIA and they are investigating the issue.

**Comment by cliffwoolley** [comment]
TensorRT 6.0.1, which was released this week, and cuDNN 7.6.4, which is coming soon, both have fixes for this issue.  Thanks for reporting it!

**Comment by sanjoy** [comment]
> TensorRT 6.0.1, which was released this week, and cuDNN 7.6.4, which is coming soon, both have fixes for this issue. Thanks for reporting it!

Closing as per this comment.
