### ISSUE TITLE
Memory continues to grow after repeated calls to model.predict(tf.one_hot(states, dtype='float32', depth=3))

### ISSUE THREAD

**Issue by LuisSaybe** [tensorflow/tensorflow#32500]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): MacOS Mojave 10.14.6
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): tensorflow==2.0.0-rc1
- TensorFlow version (use command below): v2.0.0-rc0-101-gd2d2566 2.0.0-rc1
- Python version: 3.7.4
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory: Intel Iris Plus Graphics 640 1536 MB

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**

Running the below code in Docker (version 19.03.2) causes the memory to grow without limit. This is visible in `docker stats`, eventually crashing docker.

**Describe the expected behavior**

The memory should not grow indefinitely

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

```python3
import tensorflow as tf

rows = 6
columns = 7

model = tf.keras.Sequential([
  tf.keras.layers.Flatten(input_shape=[rows * columns, 3]),
  tf.keras.layers.Dense(7, input_shape=[rows * columns * 3]),
])

model.compile(
  optimizer=tf.keras.optimizers.SGD(lr=0.01),
  loss='mean_squared_error',
  metrics=['accuracy']
)

states = [ [ 1 ] * rows * columns for i in range(20) ]

for iteration in range(1000000):
    print('iteration', iteration)
    model.predict(tf.one_hot(states, dtype='float32', depth=3))

```

The aforementioned code runs in an image generated by the following Dockerfile

```Dockerfile
FROM centos:7

ENV SOURCE_DIRECTORY /tmp/tf-connect4

ENV PYTHON_VERSION 3.7.4

RUN yum -y groupinstall -y "Development Tools" && \
    yum -y update && \
    yum -y install openssl-devel zlib-devel libffi libffi-devel wget && \
    wget https://www.python.org/ftp/python/$PYTHON_VERSION/Python-$PYTHON_VERSION.tar.xz && \
    tar -xJf Python-$PYTHON_VERSION.tar.xz && \
    cd Python-$PYTHON_VERSION && \
    ./configure && \
    make && \
    make install && \
    pip3 install --upgrade pip && \
    pip3 install tensorflow==2.0.0-rc1 tensorflow_probability==0.8.0-rc0 numpy falcon jsonschema
```

**Comment by gadagashwini** [comment]
I replicated the issue on colab with Tf 2.0.0.rc1. Please take a look at colab [gist](https://colab.sandbox.google.com/gist/gadagashwini/cc35a1c57a228661157480b1ba307116/untitled150.ipynb). Thanks!

**Comment by HubberDev** [comment]
I can reproduce this issue with the same setting. If I add keras.backend.clear_session() after each call to model.predict(), it is getting super slow.

**Comment by LuisSaybe** [comment]
still a bug after upgrading to `tensorflow==2.0.0`

**Comment by brandonschabell** [comment]
@LuisSaybe Thank you for the repro case- I added some memory tracking to it and found a pretty clear linear increase in memory utilization of the model object you've defined. It does seem to be fixed in TF 2.1.0, so I guess I'll be waiting until that's released to move off of 1.14.
![memoryleak](https://user-images.githubusercontent.com/16674595/68467202-65773c00-01db-11ea-907d-d15d133654b7.png)
![memoryleak21](https://user-images.githubusercontent.com/16674595/68467208-6a3bf000-01db-11ea-97e5-c9cc00d5eb61.png)

**Comment by yhliang2018** [comment]
This issue has been fixed recently. Could you try tf-nightly to verify it? Thanks!

**Comment by jvishnuvardhan** [comment]
@LuisSaybe Is this still an issue. I ran it in colab for 25000 iterations without any issue. Thanks!

**Comment by LuisSaybe** [comment]
will check today, sorry was on vacation

**Comment by LuisSaybe** [comment]
@yhliang2018 yes it is fixed now in tf-nightly, thanks
