### ISSUE TITLE
DefaultLogger Internal error: could not find any implementation for node (Unnamed Layer* 1) [TopK], try increasing the workspace size with IBuilder::setMaxWorkspaceSize()

### ISSUE THREAD

**Issue by sgambient** [tensorflow/tensorflow#32518]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):binary
- TensorFlow version (use command below):1.14
- Python version:2.7
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:10.1
- GPU model and memory: RTX 2080 , 8 GB

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
See the following error.  

2019-09-13 20:44:30.298493: E tensorflow/compiler/tf2tensorrt/utils/trt_logger.cc:41] DefaultLogger Internal error: could not find any implementation for node (Unnamed Layer* 1) [TopK], try increasing the workspace size with IBuilder::setMaxWorkspaceSize()
2019-09-13 20:44:30.301481: E tensorflow/compiler/tf2tensorrt/utils/trt_logger.cc:41] DefaultLogger ../builder/tacticOptimizer.cpp (1330) - OutOfMemory Error in computeCosts: 0

**Describe the expected behavior**
Work around  so as to not see this error. 

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by ravikyram** [comment]
In order to expedite the trouble-shooting process, please provide a minimal standalone code to reproduce the issue reported here. Thanks!

**Comment by sgambient** [comment]
Looks like  the error goes away when the workpspace memory size is increased.   Wondering, if the native segment fallback  works well transparently.  Preliminary observation is that it does not. 

```
2904:2019-09-16 16:22:44.847590: E tensorflow/compiler/tf2tensorrt/utils/trt_logger.cc:41] DefaultLogger Internal error: could not find any implementation for node (Unnamed Layer* 1) [TopK], try increasing the workspace size with IBuilder::setMaxWorkspaceSize()                                                                                                                                                  
2911:2019-09-16 16:22:44.850941: E tensorflow/compiler/tf2tensorrt/utils/trt_logger.cc:41] DefaultLogger ../builder/tacticOptimizer.cpp (1330) - OutOfMemory Error in computeCosts: 0 
2912:2019-09-16 16:22:44.851015: W tensorflow/compiler/tf2tensorrt/kernels/trt_engine_op.cc:647] Engine creation for xxx/TRTEngineOp_4 failed. The native segment will be used instead. Reason: Internal: Failed to build TensorRT engine   
```

**Comment by ravikyram** [comment]
Please, provide simple standalone code, then it is easy for localizing the issue faster. Thanks again.!

**Comment by sgambient** [comment]
That is easier said than done, when dealing with complex networks.  As a general observation, it is  not possible to create a sample code for every issue.   A  suggestion  would be to collect more metrics,  and log more and better  traces.  Most other complex pieces  of software uses such techniques rather than relying on  samples codes from developers.

**Comment by aaroey** [comment]
@sgambient as you said please try to increase the workspace size. Also @pooyadavoodi .
If it fails to build the engine, the fallback should work transparently. If not please reopen or file another issue.
