### ISSUE TITLE
Expand checkpoint + SavedModel file formats to include provenance (origin) meta data

### ISSUE THREAD

**Issue by jxtps** [tensorflow/tensorflow#32512]
I wrote a really nice issue description. Then github made it all disappear when I clicked their shiny new "Similar issues - Try it!" feature. I'm too frustrated to retype it. The gist is really in the title: current provenance practice is basically in the filename of the model, which sucks. 

We should add a field (that should get as auto-populated as possible) to the model outputs to keep track of the story behind the model.

**Comment by gadagashwini** [comment]
Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version. Also, did you compile from source or install a binary?

Make sure you also include the exact command if possible to produce the output included in your test case. If you are unclear what to include see the issue template displayed in [the Github new issue template](https://github.com/tensorflow/tensorflow/issues/new/choose).

We ask for this in the issue submission template, because it is really difficult to help without that information. Thanks!

**Comment by jxtps** [comment]
While I'm on Windows 10, Intel 64-bit, TF 1.14, `conda install tensorflow-gpu`, this feature request applies across platforms and future versions. 

What I'm thinking is basically expanding on the data that goes into the `history` object returned by `model.fit`, and to retain that information when doing checkpoint saves/restores and when exporting a SavedModel. 

The expanded information would include:
1. The `optimizer` settings: 
    1. Type
    1. Parameters
    1. Any epoch-specific information the optimizer implementer deems relevant
1. The ability to provide a note for what the training data is / where it came from
    1. This probably has to be manually entered as part of the training script, could I guess try to include any path/directory type information automatically? 
1. Any log entries collected from any `model.fit` `callbacks`
1. Some general field(s) where additional notes about the data can be entered. 

With detailed training information like this included in the file, and with e.g. a command line tool to allow inspection + presumably tensorboard support, then there would be much less uncertainty about how a specific set of weights came to be, and best practice would become the effortless default rather than an uphill battle.

**Comment by allenlavoie** [comment]
I don't think we have access to most of this from `tf.saved_model.save` without special-casing Keras there, which is something we don't want to do. But some of this sounds reasonable for `Model.save`.

CC @k-w-w ; any interest/guidance?

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.
