### ISSUE TITLE
EstimatorSpec documentation removed from 1.14, 1.15

### ISSUE THREAD

**Issue by sharvil** [tensorflow/tensorflow#32528]
Looks like the documentation for tf.estimator.EstimatorSpec got lost along the way from 1.13 to 1.14. Can we please add it back in?

## URL(s) with the issue: https://www.tensorflow.org/versions/r1.14/api_docs/python/tf/estimator/EstimatorSpec
https://www.tensorflow.org/versions/r1.15/api_docs/python/tf/estimator/EstimatorSpec

### Submit a pull request? no

**Comment by MarkDaoust** [comment]
We're not going to go back and fit the 1.14 and older docs. But this is fixed in 1.15+. The fix will be published early next week.
