### ISSUE TITLE
 Config value android_arm is not defined in any .rc file

### ISSUE THREAD

**Issue by mmmmayi** [tensorflow/tensorflow#32522]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 16.04
- TensorFlow installed from (source or binary): conda
- TensorFlow version: Tensorflow 1.13.1
- Python version: 3.6
- Installed using virtualenv? pip? conda?: conda
- Bazel version (if compiling from source): 0.19.2

When I convert my TensorFlow model into TFLite model, as suggested from:https://github.com/tensorflow/tensorflow/issues/32112, I use tf.lite.OpsSet.SELECT_TF_OPS to covert it, then according to 
[running the model](https://www.tensorflow.org/lite/guide/ops_select#running_the_model), i installed bazel to get Android AAR:
```
bazel build --cxxopt='--std=c++11' -c opt             \
  --config=android_arm --config=monolithic          \
  //tensorflow/lite/java:tensorflow-lite-with-select-tf-ops
```
But a error occurs although I have already set up my environment by `export PATH="$PATH:$HOME/bin"`:
```
ERROR: Config value android_arm is not defined in any .rc file
```
Thanks for you reading

**Comment by jdduke** [comment]
The `--config=android_arm` config should be defined in [tensorflow/.bazelrc. ](https://github.com/tensorflow/tensorflow/blob/master/.bazelrc#L6). Are you not seeing that in your checkout?

**Comment by mmmmayi** [comment]
> The `--config=android_arm` config should be defined in [tensorflow/.bazelrc. ](https://github.com/tensorflow/tensorflow/blob/master/.bazelrc#L6). Are you not seeing that in your checkout?

Thanks for your response, but how can i find the file if i installed through conda？

**Comment by jdduke** [comment]
I'm not familiar with the conda build, but as a workaround you can manually supply the appropriate build flags listed from @ https://github.com/tensorflow/tensorflow/blob/539de53a75d9daebda8f3fc8e5ad0e04d1dfa06e/.bazelrc#L6.
