### ISSUE TITLE
Training stuck on Allocation exceeds 10% of system memory

### ISSUE THREAD

**Issue by ychen404** [tensorflow/tensorflow#32520]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 16.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 1.9.0
- Python version: 3.5
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: running on CPU
- GPU model and memory:

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
The training is stuck after throwing the following warning: 
2019-09-13 23:25:57.221146: W tensorflow/core/framework/allocator.cc:108] Allocation of 603979776 exceeds 10% of system memory.
start training iteration: 0 elapse: 1568442370.016824
2019-09-13 23:26:10.230583: W tensorflow/core/framework/allocator.cc:108] Allocation of 2147483648 exceeds 10% of system memory.
2019-09-13 23:26:11.860365: W tensorflow/core/framework/allocator.cc:108] Allocation of 2147483648 exceeds 10% of system memory.

**Describe the expected behavior**
Expect the training to slowly progress given the memory is not big enough to hold the tensors then the swap should be able to help. 

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

MN_REDUCED.py
    
    import tensorflow as tf
    from tensorflow.python.framework import ops
    from tensorflow.python.framework import dtypes
    import random
    import numpy as np
      
    BATCH_SIZE = 128
    OUTPUT=4096
    NUM_CLASSES = OUTPUT
    
    class MN_REDUCED(object):
     
          def __init__(self, trainable=True, dropout=0.5):
              self.trainable = trainable
              self.dropout = dropout
              self.parameters = []
    
          def build(self,rgb,train_mode=None):
              with tf.name_scope('conv_1') as scope:
                  kernel = tf.Variable(tf.truncated_normal([3, 3, 3, OUTPUT], dtype=tf.float32,
                                          stddev=1e-2), name='weights')
                  conv = tf.nn.conv2d(rgb, kernel, [1, 1, 1, 1], padding='SAME')
                  biases = tf.Variable(tf.constant(0.0, shape=[OUTPUT], dtype=tf.float32),
                                           trainable=True, name='biases')
                  conv1 = tf.nn.bias_add(conv, biases)
               #   shape = int(np.prod(out.get_shape()))
               #   flat = tf.reshape(out, [BATCH_SIZE, -1])
               #   self.out_0 = flat[:,0:OUTPUT]
              with tf.name_scope('conv_2') as scope:
                  kernel = tf.Variable(tf.truncated_normal([3, 3, OUTPUT, OUTPUT], type=tf.float32,
                                          stddev=1e-2), name='weights')
                  conv = tf.nn.conv2d(conv1, kernel, [1, 1, 1, 1], padding='SAME')
                  biases = tf.Variable(tf.constant(0.0, shape=[OUTPUT], dtype=tf.float32),
                                           trainable=True, name='biases')
                  out = tf.nn.bias_add(conv, biases)
                  shape = int(np.prod(out.get_shape()))
                  flat = tf.reshape(out, [BATCH_SIZE, -1])
                  self.out_0 = flat[:,0:OUTPUT]
     
          def loss(self, labels):
              labels = tf.cast(labels, tf.int32)
              oneHot = tf.one_hot (labels, NUM_CLASSES)
              loss = tf.reduce_mean(tf.square(self.out_0 - oneHot), name='loss')
              return loss
     
          def training(self, loss):
              optimizer = tf.train.GradientDescentOptimizer(0.001)
              train_op = optimizer.minimize(loss);
              return train_op

main.py

     import tensorflow as tf
     import random
     import os
     from DataInput import DataInput
     #from CNN_FULL_CPU import CNN_FULL_CPU
     from MN_REDUCED import MN_REDUCED
     import pdb
     from tensorflow.python.tools.inspect_checkpoint import print_tensors_in_checkpoint_file
     import time
     import numpy as np
     
     dataset_path = "./"
     train_labels_file = "dataset.txt"
     
     IMAGE_HEIGHT = 32
     IMAGE_WIDTH = 32
     NUM_CHANNELS = 3
     BATCH_SIZE = 128
     NUM_ITERATIONS = 1000
     #NUM_ITERATIONS = 10
     LEARNING_RATE = 0.001
     SUMMARY_LOG_DIR="./summary-log"
     lasttime = 0
   
       def placeholder_inputs(batch_size):
               images_placeholder = tf.placeholder(tf.float32,
                                                                       shape=(batch_size, IMAGE_HEIGHT,
                                                                                  IMAGE_WIDTH, NUM_CHANNELS))
               labels_placeholder = tf.placeholder(tf.int32,
                                                                       shape=(batch_size))
       
               return images_placeholder, labels_placeholder
   
     def fill_feed_dict(images_pl, labels_pl, sess):
               #images_feed, labels_feed = sess.run([data_input.example_batch, data_input.label_batch])
       
       
               #feed_dict = {
               #       images_pl: images_feed,
               #       labels_pl: labels_feed,
               #}
               n = BATCH_SIZE * IMAGE_WIDTH * IMAGE_HEIGHT * NUM_CHANNELS
               k = IMAGE_WIDTH
               a = np.empty(n, dtype=np.float32)
               np.random.seed(0)
       
           for i in range(0, n, k):
                   a[i:i+k] = np.random.normal(loc=0, scale=1, size=k)
               rand = np.reshape(a, (BATCH_SIZE, IMAGE_WIDTH, IMAGE_HEIGHT, NUM_CHANNELS))
       
       
               n1 = BATCH_SIZE
               a1 = np.empty(n1, dtype=np.float32)
               for i in range(0, n1):
                   a1[i] = np.random.normal(loc=0, scale=1)
       
       
               feed_dict = {
                       images_pl: rand,
                       labels_pl: a1,
               }
       
               return feed_dict
   
       def do_eval(sess,
                           eval_correct,
                           logits,
                           images_placeholder,
                           labels_placeholder,
                           dataset):
   
           true_count = 0
           # // is flooring division
           steps_per_epoch = dataset.num_examples // BATCH_SIZE
           num_examples = steps_per_epoch * BATCH_SIZE
   
           for step in xrange(steps_per_epoch):
                   #feed_dict = fill_feed_dict(dataset, images_placeholder,        labels_placeholder)
                   feed_dict = fill_feed_dict(dataset, images_placeholder, labels_placeholder,sess)
                   count = sess.run(eval_correct, feed_dict=feed_dict)
                   true_count = true_count + count
   
           precision = float(true_count) / num_examples
           print ('  Num examples: %d, Num correct: %d, Precision @ 1: %0.04f' %
                           (num_examples, true_count, precision))

    def placeholder_inputs(batch_size):
        images_placeholder = tf.placeholder(tf.float32,
        shape=(batch_size, IMAGE_HEIGHT,
        IMAGE_WIDTH, NUM_CHANNELS))
        labels_placeholder = tf.placeholder(tf.int32,
        shape=(batch_size))  
       def main():
               with tf.Graph().as_default():
   
                   #data_input = DataInput(dataset_path, train_labels_file, BATCH_SIZE)
                   images_placeholder, labels_placeholder = placeholder_inputs(BATCH_SIZE)
                   cnn_full_cpu = MN_REDUCED()
                   cnn_full_cpu.build(images_placeholder)
   
                   summary = tf.summary.merge_all()
                   saver = tf.train.Saver()
                   sess = tf.Session()
                   #sess = tf.Session(config=tf.ConfigProto(log_device_placement=True))
                   summary_writer = tf.summary.FileWriter(SUMMARY_LOG_DIR, sess.graph)
                   coord = tf.train.Coordinator()
                   threads = tf.train.start_queue_runners(sess=sess, coord=coord)
   
                   loss = cnn_full_cpu.loss(labels_placeholder)
                   train_op = cnn_full_cpu.training(loss)
   
                   init = tf.global_variables_initializer()
                   sess.run(init)
                   eval_correct = evaluation(cnn_full_cpu.out_0, labels_placeholder)
   
                   try:
                           for i in range(NUM_ITERATIONS):
                                   feed_dict = fill_feed_dict(images_placeholder,
                                                                   labels_placeholder, sess)
                                   _, loss_value = sess.run([train_op, loss], feed_dict=feed_dict)
   
                                   print ('Step %d: loss = %.6f' % (i, loss_value))
   
                           coord.request_stop()
                           coord.join(threads)
                   except Exception as e:
                           print(e)
                   infer = sess.run([cnn_full_cpu.out_0], feed_dict=feed_dict)
           sess.close().   

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

I checked the memory utilization of the virtual machine. 
Although the memory is almost fully utilized, but there is still swap area. The program should run at a cost of performance. 
              total        used        free      shared  buff/cache   available
Mem:           3945        3712         178           0          54          79
Swap:          4092        2169        1923

In order to simulate a memory constrained environment, I setup a VirtualBox with 4GB memory and 4 GB swap size. Only one cpu core.

**Comment by ravikyram** [comment]
In order to expedite the trouble-shooting process, please provide a minimal standalone code to reproduce the issue reported here. Thanks!

**Comment by ychen404** [comment]
Those two files I put in the question (MN_REDUCED.py and main.py) are the code for reproducing the error. You should be able to run it as long as the TensorFlow version is the same.

**Comment by ravikyram** [comment]
@ychen404 
I tried to reproduce the issue. However i am getting the below error `ModuleNotFoundError: No module named 'DataInput'`.Please, find the gist [here](https://colab.sandbox.google.com/gist/ravikyram/1dafc3287f80876abd20efd34b48149f/untitled189.ipynb).Kindly, help me to reproduce the issue.Thanks!

**Comment by ychen404** [comment]
@ravikyram 
The code is running now from the link you sent me. I don't know how to import module in Colab so I just merge the two files i posted above into one. 

The idea is to change the global variable OUTPUT and see how the training behaves.
The OUTPUT defines the output dimensions of both the convolution layers in the model.

**Comment by ravikyram** [comment]
@ychen404 
Any changes you have made to the gist file, i have shared. I am not seeing any changes in that file. Thanks!

**Comment by ychen404** [comment]
```
import tensorflow as tf
import random
import os
import pdb
from tensorflow.python.tools.inspect_checkpoint import print_tensors_in_checkpoint_file
import time
import numpy as np

from tensorflow.python.framework import ops
from tensorflow.python.framework import dtypes

import random

dataset_path = "./"
train_labels_file = "dataset.txt"

IMAGE_HEIGHT = 32
IMAGE_WIDTH = 32
NUM_CHANNELS = 3
BATCH_SIZE = 128
NUM_ITERATIONS = 1000
#NUM_ITERATIONS = 10
LEARNING_RATE = 0.001
SUMMARY_LOG_DIR="./summary-log"
lasttime = 0
#IMAGE_HEIGHT = 100
#IMAGE_HEIGHT = 224
#IMAGE_WIDTH = 100
#IMAGE_WIDTH = 224
#BATCH_SIZE = 25
#NUM_CHANNELS = 3
#LEARNING_RATE = 0.0001
BATCH_SIZE = 128
OUTPUT=4096
NUM_CLASSES = OUTPUT


class MN_REDUCED(object):

    def __init__(self, trainable=True, dropout=0.5):
        self.trainable = trainable
        self.dropout = dropout
        self.parameters = []


    def build(self,rgb,train_mode=None):
        with tf.name_scope('conv_1') as scope:
            kernel = tf.Variable(tf.truncated_normal([3, 3, 3, OUTPUT], dtype=tf.float32,
                                    stddev=1e-2), name='weights')
            conv = tf.nn.conv2d(rgb, kernel, [1, 1, 1, 1], padding='SAME')
            biases = tf.Variable(tf.constant(0.0, shape=[OUTPUT], dtype=tf.float32),
                                     trainable=True, name='biases')
            conv1 = tf.nn.bias_add(conv, biases)
         #   shape = int(np.prod(out.get_shape()))
         #   flat = tf.reshape(out, [BATCH_SIZE, -1])
         #   self.out_0 = flat[:,0:OUTPUT]

        with tf.name_scope('conv_2') as scope:
            kernel = tf.Variable(tf.truncated_normal([3, 3, OUTPUT, OUTPUT], dtype=tf.float32,
                                    stddev=1e-2), name='weights')
            conv = tf.nn.conv2d(conv1, kernel, [1, 1, 1, 1], padding='SAME')
            biases = tf.Variable(tf.constant(0.0, shape=[OUTPUT], dtype=tf.float32),
                                     trainable=True, name='biases')
            out = tf.nn.bias_add(conv, biases)
            shape = int(np.prod(out.get_shape()))
            flat = tf.reshape(out, [BATCH_SIZE, -1])
            self.out_0 = flat[:,0:OUTPUT]

    def loss(self, labels):
        labels = tf.cast(labels, tf.int32)
        oneHot = tf.one_hot (labels, NUM_CLASSES)
        loss = tf.reduce_mean(tf.square(self.out_0 - oneHot), name='loss')
        return loss

    def training(self, loss):
        optimizer = tf.train.GradientDescentOptimizer(0.001)
        train_op = optimizer.minimize(loss);
        return train_op


def placeholder_inputs(batch_size):
        images_placeholder = tf.placeholder(tf.float32,
                                                                shape=(batch_size, IMAGE_HEIGHT,
                                                                           IMAGE_WIDTH, NUM_CHANNELS))
        labels_placeholder = tf.placeholder(tf.int32,
                                                                shape=(batch_size))

        return images_placeholder, labels_placeholder

def fill_feed_dict(images_pl, labels_pl, sess):
        #images_feed, labels_feed = sess.run([data_input.example_batch, data_input.label_batch])


        #feed_dict = {
        #       images_pl: images_feed,
        #       labels_pl: labels_feed,
        #}
        n = BATCH_SIZE * IMAGE_WIDTH * IMAGE_HEIGHT * NUM_CHANNELS
        k = IMAGE_WIDTH
        a = np.empty(n, dtype=np.float32)
        np.random.seed(0)

        for i in range(0, n, k):
            a[i:i+k] = np.random.normal(loc=0, scale=1, size=k)
        rand = np.reshape(a, (BATCH_SIZE, IMAGE_WIDTH, IMAGE_HEIGHT, NUM_CHANNELS))


        n1 = BATCH_SIZE
        a1 = np.empty(n1, dtype=np.float32)
        for i in range(0, n1):
            a1[i] = np.random.normal(loc=0, scale=1)


        feed_dict = {
                images_pl: rand,
                labels_pl: a1,
        }

        return feed_dict

def do_eval(sess,
                        eval_correct,
                        logits,
                        images_placeholder,
                        labels_placeholder,
                        dataset):

        true_count = 0
        # // is flooring division
        steps_per_epoch = dataset.num_examples // BATCH_SIZE
        num_examples = steps_per_epoch * BATCH_SIZE

        for step in xrange(steps_per_epoch):
                #feed_dict = fill_feed_dict(dataset, images_placeholder,        labels_placeholder)
                feed_dict = fill_feed_dict(dataset, images_placeholder, labels_placeholder,sess)
                count = sess.run(eval_correct, feed_dict=feed_dict)
                true_count = true_count + count

        precision = float(true_count) / num_examples
        print ('  Num examples: %d, Num correct: %d, Precision @ 1: %0.04f' %
                        (num_examples, true_count, precision))

def evaluation(logits, labels):
        correct = tf.nn.in_top_k(logits, labels, 1)
        pred = tf.argmax(logits, 1)

        return tf.reduce_sum(tf.cast(correct, tf.int32))


def myTimer( str,iteration ):
        global lasttime
        start = time.time()
        elapse = start -lasttime
        lasttime = time.time()
        print ("%s iteration: %d elapse: %f" % (str,iteration, elapse))
        return;


def main():
        with tf.Graph().as_default():

                #data_input = DataInput(dataset_path, train_labels_file, BATCH_SIZE)
                images_placeholder, labels_placeholder = placeholder_inputs(BATCH_SIZE)
                cnn_full_cpu = MN_REDUCED()
                cnn_full_cpu.build(images_placeholder)

                summary = tf.summary.merge_all()
                saver = tf.train.Saver()
                sess = tf.Session()
                #sess = tf.Session(config=tf.ConfigProto(log_device_placement=True))
                summary_writer = tf.summary.FileWriter(SUMMARY_LOG_DIR, sess.graph)
                coord = tf.train.Coordinator()
                threads = tf.train.start_queue_runners(sess=sess, coord=coord)

                loss = cnn_full_cpu.loss(labels_placeholder)
                train_op = cnn_full_cpu.training(loss)

                init = tf.global_variables_initializer()
                sess.run(init)
                eval_correct = evaluation(cnn_full_cpu.out_0, labels_placeholder)

                try:
                        for i in range(NUM_ITERATIONS):
                                feed_dict = fill_feed_dict(images_placeholder,
                                                                labels_placeholder, sess)

                                myTimer("start training", i)
                                _, loss_value = sess.run([train_op, loss], feed_dict=feed_dict)
                                myTimer("end training", i)

                                print ('Step %d: loss = %.6f' % (i, loss_value))

                        coord.request_stop()
                        coord.join(threads)
                except Exception as e:
                        print(e)
                myTimer("start inference", i)
                infer = sess.run([cnn_full_cpu.out_0], feed_dict=feed_dict)
                myTimer("end inference", i)
        sess.close()

if __name__ == '__main__':
        main()
```

I did modify the code yesterday, but the modification is all gone today. 
It seems that I can't directly save the changes on gist under your account. It will automatically create a copy connects with my github account. 
Anyway, you can just copy the above code and paste in a notebook. It should work. 
The notebook does not allow me to call modules from other file so I merge them into one.

**Comment by ravikyram** [comment]
I tried on colab with TF version 1.9 ,1.15.0-rc0 and able to reproduce the issue.Please, find the gist [here](https://colab.sandbox.google.com/gist/ravikyram/9ce500f74fa9d12d83206dc24da08caf/untitled204.ipynb#scrollTo=uI17CXoWzAai).Thanks!

**Comment by jvishnuvardhan** [comment]
@ychen404 Can you try `TF1.15.0rc1` and let us know whether the issue persists? Another request to you is "please provide small standalone code". Thanks!

**Comment by ychen404** [comment]
@jvishnuvardhan 
Sorry for the delay. I was working on some deadlines in the past week. 
I tried on TF1.15.0rc1 as well. The issue persists. 
Not quite sure what did you mean by "small standalone code". The code that shared in the gist can run out-of-the-box and everything is in one python fie.

**Comment by jvishnuvardhan** [comment]
@ychen404 I checked the code and ran it for 1 iteration with `BATCH_SIZE = 32`. Code runs without any issues. Please check the output after i iteration.

```
WARNING:tensorflow:From <ipython-input-1-2b91e330c2c9>:173: start_queue_runners (from tensorflow.python.training.queue_runner_impl) is deprecated and will be removed in a future version.
Instructions for updating:
To construct input pipelines, use the `tf.data` module.
WARNING:tensorflow:`tf.train.start_queue_runners()` was called when no queue runners were defined. You can safely remove the call to this deprecated function.
start training iteration: 0 elapse: 1569524116.256695
end training iteration: 0 elapse: 641.337531
Step 0: loss = 0.002209
start inference iteration: 0 elapse: 0.000627
end inference iteration: 0 elapse: 153.733750
```

You need to select optimum parameters for your configuration. I don't thing this is related to bug in TF. Please let us know what you think? As it is not related to TF, it is better to post in Stackoverflow where the issues like these will get lot of attention. Thanks!

**Comment by ychen404** [comment]
@jvishnuvardhan 
I understand that too big a network model may not run given a certain configuration. 
But should tensorflow let users know that the model is too big to run if that's the case? 
For the case of batch 128, I still don't know if  1) the code is stuck somewhere because the memory allocation cannot go through or 2) the code is actually fine just taking too much time. 
Is there a way that at least I can narrow down the possibilities of the above two options?

**Comment by Shuhaoalex** [comment]
Hi, I am facing a similar issue. However, in my case, this error has nothing to do with batch size.
Here is my code:
 ```
import tensorflow as tf
from functools import reduce
from tensorflow.keras import layers, Sequential, datasets
import numpy as np
tf.random.set_seed(123)




(train_images, train_labels), (test_images, test_labels) = datasets.cifar10.load_data()


train_images, test_images = train_images / 255.0, test_images / 255.0


class Model():
    weights = []
    biases = []

    def weights_collect(self):
        for l in self.layers:
            try:
                self.weights.append(l.kernel)
                self.biases.append(l.bias)
            except:
                pass

    def __init__(self):
        self.layers = [
            layers.Conv2D(32, (3, 3), activation='relu', input_shape=(32, 32, 3)),
            layers.MaxPool2D((2, 2)),
            layers.Conv2D(64, (3, 3), activation='relu'),
            layers.MaxPool2D((2, 2)),
            layers.Conv2D(64, (3, 3), activation='relu'),
            layers.MaxPool2D((2, 2)),
            layers.Flatten(),
            layers.Dense(1024, activation='relu'),
            layers.Dense(10)
        ]
        self.model = Sequential(self.layers)
        self.weights_collect()

    @tf.function
    def predict_logits(self, X):
        return self.model(X)
    

    @tf.function
    def __call__(self, X):
        return tf.nn.softmax(self.model(X))


@tf.function
def loss(m:Model, x:np.ndarray, t:np.ndarray):
    logits = m.predict_logits(x)
    tar = tf.one_hot(t, 10)
    return tf.math.reduce_mean(tf.nn.softmax_cross_entropy_with_logits(tar, logits))

@tf.function
def acc(m, X, T):
    logits = m.predict_logits(X)
    target = tf.reshape(tf.dtypes.cast(T, tf.dtypes.int32), [-1])
    pred = tf.math.argmax(logits, axis=1, output_type=tf.dtypes.int32)
    return tf.math.reduce_sum(tf.dtypes.cast(pred==target, tf.dtypes.int32))/tf.shape(X)[0]


BATCH_SIZE = 64
dataset = tf.data.Dataset.from_tensor_slices((train_images, train_labels)).batch(BATCH_SIZE)


m = Model()
opt = tf.keras.optimizers.Adam()
EPOCHS = 20
print(float(loss(m, test_images, test_labels)))
print(float(acc(m, test_images, test_labels)))
iters = 0
for i in range(EPOCHS):
    for x, t in dataset:
        with tf.GradientTape() as tape:
            loss_value = loss(m, x, t)
        grads = tape.gradient(loss_value, m.model.trainable_weights)
        opt.apply_gradients(zip(grads, m.model.trainable_weights))
        print(iters)
        iters += 1
    print(float(loss(m, test_images, test_labels)))
    print(float(acc(m, test_images, test_labels)))
```


It seems that TensorFlow keeps consuming system memory and never release them. After several iterations, it used up system memory and got stuck.
These are the relevant output during runtime.


```
2019-10-25 00:23:46.401544: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cublas64_100.dll
2019-10-25 00:23:46.679882: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudnn64_7.dll
2019-10-25 00:23:47.724957: W tensorflow/stream_executor/cuda/redzone_allocator.cc:312] Internal: Invoking ptxas not supported on Windows
Relying on driver to perform ptx compilation. This message will be only logged once.
2.3032631874084473
0.0896
2019-10-25 00:23:48.598823: W tensorflow/core/framework/cpu_allocator_impl.cc:81] Allocation of 1228800000 exceeds 10% of system memory.
0
1
2
3
4
5
6
7
```

**Comment by Crispy13** [comment]
I have the same error message.
"Allocation of 18717081600 exceeds 10% of system memory."

It didn't happen when i didn't use tf.distribute.mirroredstrategy() as a context when creating and compiling a model. But when i used the context(mirrorstrategy), the message displayed and training process was stuck.

**Comment by vusalismayilovx** [comment]
Any updates so far?

**Comment by vusalismayilovx** [comment]
The minimum requirements for such training about the RAM was 16 GB (at least). I have increased the total RAM amount to 25 after that, and it started working successfully.

**Comment by tishka04** [comment]
> The minimum requirements for such training about the RAM was 16 GB (at least). I have increased the total RAM amount to 25 after that, and it started working successfully.

Hi woosal I'm currently having the same kind of issue with error message Allocation of 33867777024 exceeds 10% of system memory.

I'm trying to compile a two hidden layers LSTM model with a single time series variable, with training set size = 46 008, and I get this error message. I'm using the R keras interface, with an average laptop (8 GB RAM, Intel i5 2.1GHz, standard GPU etc..)

I already tried to reduce the batch_size to 1 and got the same issue. Since I already tested to compile the model with less input data (below 6 000 training data it works perfectly), I strongly suspect the model is just to big for my memory, but I wonder how big it has to be to fit. So do you know is there's a way to know how much memory is needed to handle the model ?

I can provide code if needed. 

Thanks in advance !

**Comment by franciellemdn** [comment]
We had the same problem. We need to add a new dimension, as the 3D tensor receives 4D. 
list_x.append (image [:, np.newaxis])

Insert a new axis that will appear at the axis position in the expanded array shape.

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.
