### ISSUE TITLE
iOS `TensorFlowLiteC` using old C API

### ISSUE THREAD

**Issue by truongsinh** [tensorflow/tensorflow#32523]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): iOS 13
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: iPhone 6
- TensorFlow installed from (source or binary): binary (TensorFlowLiteC)
- TensorFlow version: 1.14.0

**Describe the problem**
https://github.com/tensorflow/tensorflow/blob/v1.15.0-rc0/tensorflow/lite/experimental/ios/TensorFlowLiteC.podspec does not have the pre-compiled binary yet, considering we have a significant backward compatible API change introduce by https://github.com/tensorflow/tensorflow/commit/4cc4425aee000b6358fbf219fa3dd64710b7aed4

Currently, it's a problem for us at https://github.com/dart-lang/tflite_native/pull/22

**Comment by yyoon** [comment]
Is this still an issue for you? We have recently published both v2.0.0 and v1.15.0 of the TensorFlowLiteC framework via CocoaPods. Let me know if there's anything I can help with.

**Comment by truongsinh** [comment]
@yyoon looking at https://github.com/tensorflow/tensorflow/blob/v1.15.0/tensorflow/lite/experimental/ios/TensorFlowLiteC.podspec, it's still pointing to `1.14.0`. So does https://github.com/tensorflow/tensorflow/blob/v2.0.0/tensorflow/lite/experimental/ios/TensorFlowLiteC.podspec

**Comment by yyoon** [comment]
I see how that could confuse you, but the actual process we take for releasing TensorFlowLiteC is:
 - Build the TensorFlowLiteC binary by checking out the release branch
 - Publish the binary to a publicly downloadable place
 - Update the podspec to bump up the version and point to the new binary, and publish the new podspec to CocoaPods *after the fact*.

So, it's somewhat irrelevant to what the podspec file is pointing to, in the specific release branch. Instead, I think you should be looking at the actual history of the C API directory in both branches.

https://github.com/tensorflow/tensorflow/commits/v2.0.0/tensorflow/lite/experimental/c
https://github.com/tensorflow/tensorflow/commits/v1.15.0/tensorflow/lite/experimental/c

You can see that the API style change commit is included in v1.15.0.
If you want to download v1.15.0 without going through CocoaPods, you can use this link directly:
https://dl.google.com/dl/cpdc/559f7884827d4af4/TensorFlowLiteC-1.15.0.tar.gz

**Comment by truongsinh** [comment]
ah thanks, I can see v2.0.0 on https://cocoapods.org/pods/TensorFlowLiteObjC now
