### ISSUE TITLE
Build TensorFlow Lite for Raspberry Pi with SELECT_TF_OPS

### ISSUE THREAD

**Issue by liushengzhong1023** [tensorflow/tensorflow#32535]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Raspbian GNU/Linux 9.1 (stretch)
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): source
- TensorFlow version: 1.14
- Python version:
- Installed using virtualenv? pip? conda?:
- Bazel version (if compiling from source): 0.26.1
- GCC/Compiler version (if compiling from source): 
- CUDA/cuDNN version:
- GPU model and memory:

**Describe the problem**

Hi, I am trying to use TF Lite with SELECT_TF_OPS on my Raspberry Pi 3B. According to your docs, Python API is currently not fully supported, so I tried to use the C++ API. Then I have to compile a static library for TF Lite [https://www.tensorflow.org/lite/guide/build_rpi#cross-compile_for_raspberry_pi](url) . The problem is how can I config it to support SELECT_TF_OPS? The only information I found is on [https://www.tensorflow.org/lite/guide/ops_select#c](url), but it is about compiling using Bazel, which is not compatible with the compiling instructions on Raspberry Pi? Does anyone has any suggestions or ideas about this issue?

Thanks!

**Comment by terryheo** [comment]
Recently this issue is fixed with the master branch.
Now, you can use SELECT_TF_OPS with Python tf.lite.Interpreter API.

Thanks.
