### ISSUE TITLE
Chief-worker should waitting for all other workers.

### ISSUE THREAD

**Issue by shanshanpt** [tensorflow/tensorflow#32549]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using): tensorflow1.12
- Are you willing to contribute it (Yes/No): No

**Describe the feature and the current behavior/state.**
Use Ps-worker mode.
When I use Estimator or MonitoredTrainingSession, I should have a chief-worker.
Chief-worker will do some chief-only hooks, like CheckpointSaverHook.
But now, I can't guarantee that chief-worker will quit before all other workers.
If chief-worker is quitted before all others workers, nobody will do the CheckpointSaverHook.

**Will this change the current api? How?**
I have no elegant idea so far.

**Who will benefit with this feature?**
All.

**Any Other info.**
So how can I fix the problem? Maybe you can offer some good ideas. 

Thanks so much :)

**Comment by shanshanpt** [comment]
@rchao Hi rchao，sorry to trouble you, can you help?  :) 
Thanks ~

**Comment by rchao** [comment]
@shanshanpt, thanks for the question. If you're using Estimator, you can specify the hooks to run on workers in the `tf.estimator.EstimatorSpec` object you construct to return from your `model_fn`. If you're using `tf.compat.v1.train.MonitoredTrainingSession`, you can directory pass in the hooks. Hopefully this helps.

**Comment by shanshanpt** [comment]
> @shanshanpt, thanks for the question. If you're using Estimator, you can specify the hooks to run on workers in the `tf.estimator.EstimatorSpec` object you construct to return from your `model_fn`. If you're using `tf.compat.v1.train.MonitoredTrainingSession`, you can directory pass in the hooks. Hopefully this helps.

I'm Sorry, maybe I didn't describe it clearly.
This is what my codes like:

```
sess = MonitoredTrainingSession(...)
while not sess.should_stop():
    do something ...
```

And only chief-worker can do the CheckpointSaverHook. If chief-worker is quitted before all others workers, no other workers will do the CheckpointSaverHook. But other workers are still doing the training-task. No worker will save the checkpoint now.
So I think there should a function to promise that chief-worker exit after all other workers.
: )

**Comment by severussong** [comment]
> > @shanshanpt, thanks for the question. If you're using Estimator, you can specify the hooks to run on workers in the `tf.estimator.EstimatorSpec` object you construct to return from your `model_fn`. If you're using `tf.compat.v1.train.MonitoredTrainingSession`, you can directory pass in the hooks. Hopefully this helps.
> 
> I'm Sorry, maybe I didn't describe it clearly.
> This is what my codes like:
> 
> ```
> sess = MonitoredTrainingSession(...)
> while not sess.should_stop():
>     do something ...
> ```
> 
> And only chief-worker can do the CheckpointSaverHook. If chief-worker is quitted before all others workers, no other workers will do the CheckpointSaverHook. But other workers are still doing the training-task. No worker will save the checkpoint now.
> So I think there should a function to promise that chief-worker exit after all other workers.
> : )

Have you figured out how to solve this problem
