### ISSUE TITLE
tf.keras.layers.Add can add tensors with dimension ()

### ISSUE THREAD

**Issue by breadbread1984** [tensorflow/tensorflow#32545]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.0.0-dev20190731
- Python version: 3.6.7
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**

when I add multiple tensors with shape (), tf.keras.layers.Add complains that
>  File "/home/xieyi/.local/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/base_layer.py", line 680, in __call__
    self._maybe_build(inputs)
  File "/home/xieyi/.local/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/base_layer.py", line 1905, in _maybe_build
    self.build(input_shapes)
  File "/home/xieyi/.local/lib/python3.6/site-packages/tensorflow_core/python/keras/utils/tf_utils.py", line 299, in wrapper
    output_shape = fn(instance, input_shape)
  File "/home/xieyi/.local/lib/python3.6/site-packages/tensorflow_core/python/keras/layers/merge.py", line 95, in build
    batch_sizes = [s[0] for s in input_shape if s is not None]
  File "/home/xieyi/.local/lib/python3.6/site-packages/tensorflow_core/python/keras/layers/merge.py", line 95, in <listcomp>
    batch_sizes = [s[0] for s in input_shape if s is not None]
IndexError: tuple index out of range

**Describe the expected behavior**

I expect tf.keras.layers.Add can process tensors of any dimension.

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

```python
#!/usr/bin/python3

import tensorflow as tf;

a = tf.constant(1);
b = tf.constant(2);
c = tf.constant(3);
d = tf.keras.layers.Add()([a,b,c]);
```

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by ravikyram** [comment]
I have tried on colab with TF version 2.0.0-dev20190731, 2.0.0.dev20190915 ,2.0.0-rc1 and was able to reproduce the issue.Please, find the gist [here](https://colab.sandbox.google.com/gist/ravikyram/4d2dbc41b14058292781f56e3bbfb225/untitled185.ipynb).Thanks!

**Comment by jvishnuvardhan** [comment]
@breadbread1984 I think this was resolved in recent `tf-nightly`. I ran it without any issues. Please take a look at the [colab gist](https://colab.research.google.com/gist/jvishnuvardhan/2447d8ec4f353efa284642210c74ab39/untitled66.ipynb). 

Can you please verify once and close the issue if this was resolved for you. thanks!
