### ISSUE TITLE
Cannot see summaries after running "mnist_with_summaries" exmaple

### ISSUE THREAD

**Issue by lan2720** [tensorflow/tensorflow#3254]
Hi, I'm learning something about tensorboard and summaries. After I run the code from /tensorflow/examples/tutorials/mnist/mnist_with_summaries.py, open the tensorboard, I can't see any histograms or scalar summaries. All are blank. It's wired.
![](http://ww3.sinaimg.cn/large/901f9a6fjw1f5on9oq9tnj20a90m5wft.jpg)
![](http://ww1.sinaimg.cn/large/901f9a6fjw1f5on9xq4npj20iy0gt0uw.jpg)

operation system: ubuntu14.04
gpu: gtx1080
cuda 7.5
cudnn 4.0.7
install tensorflow from sources

Another thing I should mention is that I cannot run the mnist_with_summaries.py directly in Pycharm. Its log like that
```
/usr/bin/python2.7 /home/lan/Packages/tensorflow/tensorflow/examples/tutorials/mnist/mnist_with_summaries.py
Traceback (most recent call last):
  File "/home/lan/Packages/tensorflow/tensorflow/examples/tutorials/mnist/mnist_with_summaries.py", line 27, in <module>
    import tensorflow as tf
  File "/home/lan/Packages/tensorflow/tensorflow/__init__.py", line 23, in <module>
    from tensorflow.python import *
  File "/home/lan/Packages/tensorflow/tensorflow/python/__init__.py", line 48, in <module>
    from tensorflow.python import pywrap_tensorflow
ImportError: cannot import name pywrap_tensorflow

Process finished with exit code 1
```
So I run the code in terminal by `python mnist_with_summaries.py`. It do run successfully, but there are warnings (or sth?): Unhandled API Callback
![](http://ww3.sinaimg.cn/large/901f9a6fjw1f5onjmkjoaj20lx07y77z.jpg)
I'm not sure if this warning influences summaries.

**Comment by danmane** [comment]
This was fixed in a recent commit (but hasn't made it into a release branch yet) - see:
https://github.com/tensorflow/tensorflow/commit/cf7f7de701874a091156cd76286c0ead6dc98be1
