### ISSUE TITLE
[autograph List comprehension issue] OperatorNotAllowedInGraphError error in Tensorflow 2.0

### ISSUE THREAD

**Issue by payne4handsome** [tensorflow/tensorflow#32546]
**System information**
- OS Platform and Distribution 
Mac os (10.14.6)
- TensorFlow installed from (source or binary):
binary
- TensorFlow version (use command below):
 2.0.0rc1
- Python version:
Python 3.6.4

I'm learn tensorflow2.0 from [official tutorials](https://www.tensorflow.org/beta/guide/autograph#batching).I can understand the result from below code.
```
def square_if_positive(x):
  return [i ** 2 if i > 0 else i for i in x]
square_if_positive(range(-5, 5))

# result
[-5, -4, -3, -2, -1, 0, 1, 4, 9, 16]
```
But if I change the inputs with tensor not python code, just like this, I got a error
```
@tf.function
def square_if_positive(x):
  return [i ** 2 if i > 0 else i for i in x]
square_if_positive(tf.range(-5, 5))
```
```

~/tf2_workspace/tf2.0/lib/python3.6/site-packages/tensorflow_core/python/eager/function.py in _create_graph_function(self, args, kwargs, override_flat_arg_shapes)
   1984             arg_names=arg_names,
   1985             override_flat_arg_shapes=override_flat_arg_shapes,
-> 1986             capture_by_value=self._capture_by_value),
   1987         self._function_attributes,
   1988         # Tell the ConcreteFunction to clean up its graph once it goes out of

~/tf2_workspace/tf2.0/lib/python3.6/site-packages/tensorflow_core/python/framework/func_graph.py in func_graph_from_py_func(name, python_func, args, kwargs, signature, func_graph, autograph, autograph_options, add_control_dependencies, arg_names, op_return_value, collections, capture_by_value, override_flat_arg_shapes)
    851                                           converted_func)
    852 
--> 853       func_outputs = python_func(*func_args, **func_kwargs)
    854 
    855       # invariant: `func_outputs` contains only Tensors, CompositeTensors,

~/tf2_workspace/tf2.0/lib/python3.6/site-packages/tensorflow_core/python/eager/def_function.py in wrapped_fn(*args, **kwds)
    323         # __wrapped__ allows AutoGraph to swap in a converted function. We give
    324         # the function a weak reference to itself to avoid a reference cycle.
--> 325         return weak_wrapped_fn().__wrapped__(*args, **kwds)
    326     weak_wrapped_fn = weakref.ref(wrapped_fn)
    327 

~/tf2_workspace/tf2.0/lib/python3.6/site-packages/tensorflow_core/python/framework/func_graph.py in wrapper(*args, **kwargs)
    841           except Exception as e:  # pylint:disable=broad-except
    842             if hasattr(e, "ag_error_metadata"):
--> 843               raise e.ag_error_metadata.to_exception(type(e))
    844             else:
    845               raise

OperatorNotAllowedInGraphError: in converted code:

    <ipython-input-37-6c17f29a3443>:3 square_if_positive  *
        return [i**2 if i > 0 else i for i in x]
    /Users/zhangpan/tf2_workspace/tf2.0/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py:547 __iter__
        self._disallow_iteration()
    /Users/zhangpan/tf2_workspace/tf2.0/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py:540 _disallow_iteration
        self._disallow_when_autograph_enabled("iterating over `tf.Tensor`")
    /Users/zhangpan/tf2_workspace/tf2.0/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py:518 _disallow_when_autograph_enabled
        " decorating it directly with @tf.function.".format(task))

    OperatorNotAllowedInGraphError: iterating over `tf.Tensor` is not allowed: AutoGraph did not convert this function. Try decorating it directly with @tf.function.
```
I can't find any specifications about this error. I think the real reason is not "iterating over tf.Tensor is not allowed" . Becase I can write like this.

```
@tf.function
def square_if_positive(x):
    for i in x:
        if i>0:
            tf.print(i**2)
        else:
            tf.print(i)

square_if_positive(tf.range(10))
```
iterate over tensor just like above code.
So my question is what's the real reason about this error? Any suggestions will help me. I really can't understand this error through I read a lot of materials.

**Comment by oanush** [comment]
@payne4handsome ,
When tried executing the code for TF-2.0rc1 output is received as follows(no error is faced),
```
def square_if_positive(x):
  return [i ** 2 if i > 0 else i for i in x]
square_if_positive(tf.range(-5, 5)
##prints 
[<tf.Tensor: id=169, shape=(), dtype=int32, numpy=-5>,
 <tf.Tensor: id=175, shape=(), dtype=int32, numpy=-4>,
 <tf.Tensor: id=181, shape=(), dtype=int32, numpy=-3>,
 <tf.Tensor: id=187, shape=(), dtype=int32, numpy=-2>,
 <tf.Tensor: id=193, shape=(), dtype=int32, numpy=-1>,
 <tf.Tensor: id=199, shape=(), dtype=int32, numpy=0>,
 <tf.Tensor: id=209, shape=(), dtype=int32, numpy=1>,
 <tf.Tensor: id=217, shape=(), dtype=int32, numpy=4>,
 <tf.Tensor: id=225, shape=(), dtype=int32, numpy=9>,
 <tf.Tensor: id=233, shape=(), dtype=int32, numpy=16>]
```
if you want a clearer output please try using the below code-
```
def square_if_positive(x):
  return tf.where(x>0,x**2,x)
square_if_positive(tf.range(-5, 5))
##prints
<tf.Tensor: id=263, shape=(10,), dtype=int32, numpy=array([-5, -4, -3, -2, -1,  0,  1,  4,  9, 16], dtype=int32)>
```
Thanks!

**Comment by payne4handsome** [comment]
@oanush  sorry, I made a mistake. I got errors from below code. I annotate a function with @tf.function that will be compiled into a graph.
```
@tf.function
def square_if_positive(x):
  return [i ** 2 if i > 0 else i for i in x]
square_if_positive(tf.range(-5, 5))
```
I got errors like I explained above

**Comment by oanush** [comment]
Issue replicating for TF-2.0rc1,please find the [gist](https://colab.sandbox.google.com/gist/oanush/0983d6584c1c687c0456fff142db4ad4/32546.ipynb) of colab.Thanks!

**Comment by ymodak** [comment]
The issues exists with tf-nightly version ```'2.1.0-dev20191004'```

**Comment by mdanatg** [comment]
@kkimdev FYI

The root cause is that autograph doesn't yet support list comprehensions (primarily because it's difficult to determine the dtype of the result in all cases).

As a workaround, you can use `tf.map_fn` for the comprehension:

```
return tf.map_fn(lambda i: i ** 2 if i > 0 else i, x)
```

Or an explicit loop (which is a bit more verbose):

```
r = tf.TensorArray(x.dtype, 0, dynamic_size=True)
for i in x:
  r = r.write(r.size(), i ** 2 if i > 0 else i)
return r.stack()
```

We also need to raise a better error message about this and either update the documentation, until this is resolved.

**Comment by GeorgyZhou** [comment]
I am interested to look into it deeper and to see if we can support this list comprehensions. Will send a PR if possible.

**Comment by payne4handsome** [comment]
@mdanatg Thanks for your explains. Looking forward to your better solution

**Comment by nikhilrana015** [comment]
Hello Everyone I am getting this error
**OperatorNotAllowedInGraphError: using a `tf.Tensor` as a Python `bool` is not allowed in Graph execution. Use Eager execution or decorate this function with _@tf.function**

I am trying to implement Neural style transfer. Please help me with this. Here is the collab link Please take a look into it. I tried everything still It does not resolved.

**Comment by mdanatg** [comment]
@nikhilrana015 please use the updated tutorial at https://www.tensorflow.org/tutorials/generative/style_transfer. The notebook you linked uses a method of extracting intermediate layers that's unsupported in eager execution (`model.get_layer(i).get_output_at(1)`).

cc @omalleyt12

**Comment by nikhilrana015** [comment]
@mdanatg  I tried to replace `model.get_layer(i).get_output_at(1)` `with model.get_layer(i).output` but it gives me an error **Attribute Error: Layer block4_conv2 has multiple inbound nodes, hence the notion of "layer output" is ill-defined. Use `get_output_at(node_index)` instead.**

I figured out the error but I don't know how to resolve it. In my code Total loss is tensor but when I extract the value by using .numpy() it gives me an error that there is no attribute. 

The if statement In the last cell before Checking the Code Markdown gives me an error of operation Not allowed in Graph error. Please Help me in this.

**Comment by mdanatg** [comment]
Sorry for the delay. @omalleyt12, any thoughts on that error?

**Comment by amahendrakar** [comment]
Was able to reproduce the issue with TF v2.2 and TF-nightly (i.e. v2.3.0-dev20200625). Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/c8ec17433c4e4ae8dbdd0291bc34d7d6/32546.ipynb). Thanks!

**Comment by marchss** [comment]
same issue, here.

**Comment by tomerk** [comment]
This is not a particularly meaningful issue thread at this point because it's got a few different user requests for help at this point.

1. The original issue (& the gist above) are for this reason that @mdanatg mentioned (@mdanatg I know we track this issue internally, should we make a separate github issue that's clearer to users?)

> The root cause is that autograph doesn't yet support list comprehensions (primarily because it's difficult to determine the dtype of the result in all cases).

> As a workaround, you can use tf.map_fn for the comprehension:

> return tf.map_fn(lambda i: i ** 2 if i > 0 else i, x)
> Or an explicit loop (which is a bit more verbose):

> r = tf.TensorArray(x.dtype, 0, dynamic_size=True)
> for i in x:
>   r = r.write(r.size(), i ** 2 if i > 0 else i)
> return r.stack()
> We also need to raise a better error message about this and either update the documentation, until this is resolved.

2. @nikhilrana015 I don't run into the issue you mentioned when I try running your colab. If you're still running problems please make a separate github issue so that we can triage more effectively. My guess is the issue you were running into probably had something to do with using a layer multiple times to construct different functional models, and probably trying to grab the wrong symbolic outputs.

For anyone else seeing this thread: please make a different github issue unless you're specifically having problems w/ the list comprehension issue @mdanatg mentioned.

**Comment by saikumarchalla** [comment]
I can able to reproduce the error and the issue still exists in 2.6 nightly as well. Thanks!

**Comment by miguelCalado** [comment]
Hi,

I have a similar problem where I'm trying to iterate over a tensor in eager mode but I can't.

Naturally, you would do something like:

```
probs = tf.convert_to_tensor(np.array([[1,2,3], [4,5,6], [7,8,9]]))
indexs = tf.convert_to_tensor(np.array([1, 2, 3]))

@tf.function
def iterate_tensor(probs, indexs):
    return [output[label] for output, label in zip(probs, indexs)]
iterate_tensor(probs, indexs)
```

But this gives the error ```OperatorNotAllowedInGraphError: iterating over `tf.Tensor` is not allowed:```

Another thing that I tried was:

```
probs = tf.convert_to_tensor(np.array([[1,2,3], [4,5,6], [7,8,9]]))
indexs = tf.convert_to_tensor(np.array([1, 2, 3]))

@tf.function
def iterate_tensor(probs, indexs):
    return tf.map_fn(lambda i: i[0][i[1]], (probs, indexs), dtype=(tf.int64, tf.int64))

iterate_tensor(probs, indexs)
```

Gives the error ```ValueError: The two structures don't have the same nested structure.```

**Comment by kumariko** [comment]
Was able to reproduce the issue with TF v2.7. Please find the gist of it [here](https://colab.sandbox.google.com/gist/kumariko/5538aa31a851e93eb0f25a6039eca116/32546.ipynb#scrollTo=IgffAbk23Qbd). Thanks!

**Comment by mohantym** [comment]
Hi @payne4handsome ! I was able to resolve this issue by replacing **tf.range() with range()**. Attaching [Gist](https://colab.sandbox.google.com/gist/mohantym/87dd7e3abd2540dc5b0ec6124af7d1d9/32546.ipynb#scrollTo=iT1EKzzHdWZk) for [reference](https://github.com/tensorflow/tensorflow/issues/33308).
