### ISSUE TITLE
CUDNN_STATUS_ALLOC_FAILED with minimal network and data using CUDA 10.0 and CuDNN 7.6.x

### ISSUE THREAD

**Issue by bersbersbers** [tensorflow/tensorflow#32552]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes, see below
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- TensorFlow installed from (source or binary): binaries from pip
- TensorFlow version (use command below):1.13.1 through 2.0.0rc1 (e.g., v2.0.0-rc0-101-gd2d2566eef 2.0.0-rc1)
- Python version: 3.6.8 and 3.7.4
- Bazel version (if compiling from source): none
- GCC/Compiler version (if compiling from source): none
- CUDA/cuDNN version: 10.0 with any 7.6.x
- GPU model and memory: Geforce RTX 2060 (Laptop)

**Describe the current behavior**
Code stops with CUDNN_STATUS_ALLOC_FAILED if using CuDNN 7.6 on CUDA 10.0.
Code works fine if using CuDNN <=7.5 or if using CUDA 9.0 or on different computer (Quadro M5000).
(But TF 2.0 binaries require CUD 10.0, CuDNN >= 7.6.)
Code also works when adding a dense layer (`model.add(layers.Dense(1))`) or changing the input shape to `(3,1)`.

**Describe the expected behavior**
Code finishes.

**Code to reproduce the issue**
```
import numpy as np
from tensorflow.keras import layers, models, optimizers

model = models.Sequential()
model.add(layers.Conv1D(1, 3, input_shape=(8, 1)))


optimizer = optimizers.Adam(lr=1e-6)
model.compile(optimizer=optimizer, loss='mse')
x = np.zeros((1, *model.input.shape[1:]))
y = np.zeros((1, *model.output.shape[1:]))
model.fit(x, y)
```

**Other info / logs**
Here is some more detailed information: https://stackoverflow.com/questions/57872336/should-i-be-able-to-use-precompiled-tensorflow-2-on-a-laptop-geforce-rtx-2060-gp

**Comment by babytut** [comment]
you should add 
`
config = tf.ConfigProto()
config.gpu_options.allow_growth = True  
tf.keras.backend.set_session(tf.Session(config=config))`

**Comment by bersbersbers** [comment]
@babytut this I had tried before, without success. I do not believe this is related to GPU memory.

Again cleaning all drivers, and again installing the most current drivers (436.30) seems to have fixed this for now, I'll reopen if it ever comes back.
