### ISSUE TITLE
Can't import from subpackages

### ISSUE THREAD

**Issue by novog** [tensorflow/tensorflow#32555]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10 Enterprise
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): v2.0.0rc1
- Python version: 3.7.2
- CUDA/cuDNN version: 10.0/7.5
- GPU model and memory: GeForce GTX Titan X, 12GB

**Describe the current behavior**

As of v2.0.0rc1, I can't import anything from subpackages. Attempting to do so results in the error "ModuleNotFoundError: No module named ...".

I had upgraded to rc1 using pip. Uninstalling and reinstalling tensorflow did not help. The issue is present in both tensorflow and tensorflow-gpu. This issue is not present in v2.0.0-rc0, including after reverting to it.

**Describe the expected behavior**

Previously, it has always been possible to import definitions directly from subpackages.

**Code to reproduce the issue**

Imports like the following previously worked and now both result in the error specified above:

    from tensorflow.data import *
    from tensorflow.io import TFRecordWriter

The following approaches still work:

    import tensorflow as tf
    writer = tf.io.TFRecordWriter

    from tensorflow import io
    writer = io.TFRecordWriter

**Comment by mihaimaruseac** [comment]
The only supported way to use TensorFlow is `import tensorflow as tf` and then access the API via `tf....` attribute lookup. All the other ways that are possible are not supported, artifacts of Python's quirks, and can and will break with no rollback.

In this case, the only case that is always guaranteed to work is

```python
import tensorflow as tf
writer = tf.io.TFRecordWriter
```

**Comment by mihaimaruseac** [comment]
Closing due to no further activity.
