### ISSUE TITLE
Timeline reports incorrect GPU memory usage

### ISSUE THREAD

**Issue by smr97** [tensorflow/tensorflow#32550]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): conda (binary)
- TensorFlow version (use command below): 1.14 gpu
- Python version: 3.6.7
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 10.0
- GPU model and memory:

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**

My objective is to measure the amount of GPU memory needed by BERT during the inference process. I have already set the TF_FORCE_GPU_ALLOW_GROWTH (or a paraphrase thereof, I don't remember the exact flag) to true. NVIDIA-SMI shows a usage of ~2500 MB for a batch size of 227. 

1. Even if the allow growth is true, the tensorflow allocation is taking place in steps. I see the same peak usage in nvidia-smi for batch sizes 16, 32, 64 and then it jumps up suddenly. Usage for batch sizes 128 through 227 is as above, while for batch size 228, it is suddenly 4495MB. Hence, this measurement does not serve my purpose. It clearly depends more on the allocator behaviour than the network size + activations size.

2. Timeline visualisation in chrome trace format shows a peak allocation on GPU_0_bfc as ~418MB for a batch size of 227. This is way too low. If I compare it with nvidia-smi trace (peaking at ~2500MB) this makes no sense.

3. Tensorboard visualisation somehow shows the BERT node as using 175MB. Again, it makes no sense.

**Describe the expected behavior**
Please help me get an accurate measurement of how much memory my current model and batch size is really taking to run on a GPU with TF. The only trustworthy metric I see in this labyrinth is nvidia-smi, but only for the batch sizes at which it suddenly steps up.

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.
Can use the google research bert and profile for memory using ProfilerHooks.

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by gadagashwini** [comment]
@smr97, In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thanks!

**Comment by smr97** [comment]
This can be reproduced with [this](https://github.com/google-research/bert) repository. You just need to add the hooks for profiling. I have a modified model which is unfortunately proprietary, but this issue is definitely generic, and can be reproduced as above.

**Comment by shreyanair01** [comment]
Any update on this issue? I am also trying to find the accurate GPU memory usage by models. I am loading a resnet(99MB) and inception v3(92MB) model with a tf serving docker image, with the TF_FORCE_GPU_ALLOW_GROWTH flag. Based on reports of nvidia-smi, the GPU usage differs on machines with different capacity. You can find my observations in a comment [here](https://github.com/tensorflow/serving/issues/1496)

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.
