### ISSUE TITLE
Survey on Pull Request Prioritization

### ISSUE THREAD

**Issue by IlyasAzeem** [tensorflow/tensorflow#32554]
Dear Pull Requests integrators,
We are an international group of researchers investigating Pull Requests management activities. We implemented an automated approach, named CARTESIAN, for prioritizing Pull Requests (PRs) received by an open-source project according to the likelihood of acceptance/response. We would like to evaluate whether CARTESIAN can help integrators when reviewing PRs. 
As we noticed that your project receives many PRs daily, we have taken the liberty of contacting you. Thus, we experimented CARTESIAN on Your projects, to help you in prioritizing PRs. To know more about these results, please fill in the form below. 
Survey form link: https://forms.gle/bGkj3nRH9i6ArjUx8 
Your participation is voluntary and confidential. We kindly request you, ONLY to INTEGRATORS, to participate in this study which is expected to take about 15 minutes of your time. You might withdraw at any time.
Best regards,
Muhammad Ilyas Azeem, National Engineering Research Center of Fundamental Software, Chinese Academy of Sciences, China
Andrea Di Sorbo, University of Sannio, Italy
Sebastiano Panichella, Zurich University of Applied Science, Switzerland
Alexander Serebrenik, Eindhoven University of Technology, The Netherlands

**Comment by martinwicke** [comment]
Thank you for note. We generally respond to all PRs (except obviously fraudulent ones) so I am not sure we'd deliver meaningful input data. TensorFlow is also too large to deal with for a single person, so we have a hierarchical triage process that identifies the best person to decide on any specific PR. 

Consequently, I could not properly fill out your survey, and I don't know that anyone else can.

I will close this issue. This is fantastic research!
