### ISSUE TITLE
[feature request]copy lstm parameters

### ISSUE THREAD

**Issue by Damcy** [tensorflow/tensorflow#3256]
I'm using tensorflow to implement DQN network and use LSTM at the bottom layer. 

But in DQN, a target network is used(coping the main network and keep it for a while, and at the mean time update the original network), when use the `tf.Variable` as parameter A, I can use `tf.Variable.assign` to copy A to A', but when I use LSTM, it seems like there is no way to do this copy operation.

Or maybe there is a way to copy the whole graph include its variable weights?

**Comment by jmchen-g** [comment]
@ebrevdo Could you take a look at this please?

**Comment by ebrevdo** [comment]
You can access the underlying variables using tf.get_ variable() or, alternatively, by looking through tf.trainable_variables().  E.g.

print [v.name for v in tf.trainable_variables))]

**Comment by Damcy** [comment]
@ebrevdo It can serve my needs, though I need to see what variables have been created by LSTMCell or other interface and their names. Thank you very much!
cc to @jmchen-g

**Comment by Damcy** [comment]
closed

**Comment by Damcy** [comment]
closed #3256

**Comment by Tomakko** [comment]
If i have those ema variables, how can i load them into another lstm cell?
