### ISSUE TITLE
TF GPU doesn't recognise 2nd GPUs

### ISSUE THREAD

**Issue by cyrus2018** [tensorflow/tensorflow#32569]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10 pro
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version (use command below): 1.14 GPU
- Python version: 3.7 64 bit
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 10.1
- GPU model and memory: RTX 1070 (8GB) and GTX 1050 (2GB) , 32 GB Ram, Core i7 9700 k

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
TF GPu wont identify two GPUs, only GPU 0 appears

**Describe the expected behavior**
I want to see GPU0 and GPU 1 when run the device list command

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

After I install all, The TF GPU does not recognise my 2nd GPU (Nvidia GTX 1050) as GPU:01
![1](https://user-images.githubusercontent.com/45702408/65003983-57204880-d92d-11e9-8706-45c0f98179b1.JPG)
I can switch to that GPU, using Cuda visible devices, however can not use two GPUs  (for multi GPU calculations), any recommendations?

**Comment by gadagashwini** [comment]
@cyrus2018,
Please try the following code snippet to see the gpu divices:
```
import tensorflow as tf
gpus = tf.config.experimental.list_physical_devices('GPU')
for gpu in gpus:
    print("Name:", gpu.name, "  Type:", gpu.device_type)
```
Thanks!

**Comment by cyrus2018** [comment]
![1](https://user-images.githubusercontent.com/45702408/65046981-2cb5a600-d994-11e9-9f3e-4fd16a259d5e.JPG)

**Comment by cyrus2018** [comment]
![image](https://user-images.githubusercontent.com/45702408/65123520-03455a80-da26-11e9-9584-ffb985e766d5.png)

**Comment by gadagashwini** [comment]
@cyrus2018, 
Please provide the result of nvidia-smi. Thanks!

**Comment by cyrus2018** [comment]
![1](https://user-images.githubusercontent.com/45702408/65138605-cdac6b80-da3d-11e9-86f8-f795825b4662.JPG)

**Comment by ymodak** [comment]
I suspect you have multiple cuda versions installed on your system. TF 1.14 prebuilt binary supports cuda 10.0 that can be one plausible explanation.

**Comment by ymodak** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Comment by cyrus2018** [comment]
The issue has not been resolves, any suggestions?

**Comment by cyrus2018** [comment]
Mutli GPU usage on TF works in Windows platform right? (Windows 10 pro to be more specific)

Another question: RTX 1070, has separate power input. GTX 1050 draws the power from the motherboard, but i haven't connected the auxiliary power input into the mother board. is there any known hardware configurations that may cause this issue? (to prevent usage of two gpus at the same time?

**Comment by cyrus2018** [comment]
Added below to top of the codes, issue is resolved
NOTE:: TF_MIN_GPU_MULTIPROCESSOR_COUNT defauls value is 8


import os
os.environ["TF_MIN_GPU_MULTIPROCESSOR_COUNT"]="2"
os.environ["CUDA_VISIBLE_DEVICES"]="0,1"

**Comment by gowthamkpr** [comment]
Closing this issue as it has been resolved. Thanks!
