### ISSUE TITLE
can't interpret primitive type objects correctly

### ISSUE THREAD

**Issue by breadbread1984** [tensorflow/tensorflow#32563]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):ubuntu18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:N/A
- TensorFlow installed from (source or binary):binary
- TensorFlow version (use command below):2.0.0-dev20190915
- Python version:3.6.7
- Bazel version (if compiling from source):N/A
- GCC/Compiler version (if compiling from source):N/A
- CUDA/cuDNN version:N/A
- GPU model and memory:N/A

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**

when i use primitive type objects during building model with tf.keras functional api. tensorflow mistake primtive type objects as tensors.

**Describe the expected behavior**

interpret primitive type as tensor at the right time.

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

```python
import tensorflow as tf;
import numpy as np;

def Model(shape):
  input_shapes = [np.array(shape,dtype=np.int32), np.array(shape,dtype=np.int32) // 2, np.array(shape,dtype=np.int32) // 4];
  print(input_shapes)
  inputs = [tf.keras.Input(input_shape) for input_shape in input_shapes];
  outputs = list();
  for input in inputs:
    output = tf.keras.layers.Conv2D(filters=10,kernel_size=(3,3), padding='same')(input);
    outputs.append(output);
  return tf.keras.Model(inputs = inputs, outputs = outputs);
  
model = Model([32,32,32]);
model.save('model.h5');
```

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

>Traceback (most recent call last):            File "test.py", line 14, in <module>
    model = Model([32,32,32]);
  File "test.py", line 7, in Model
    inputs = [tf.keras.Input(input_shape) for input_shape in input_shapes];               File "test.py", line 7, in <listcomp>
    inputs = [tf.keras.Input(input_shape) for input_shape in input_shapes];
  File "/home/xieyi/.local/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/input_layer.py", line 251, in Input
    if shape and batch_input_shape:
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

**Comment by WindQAQ** [comment]
Hi @breadbread1984 It's because you try to use `np.array` as shape, which results in errors.
```python
# work
if [1, 2, 3]:
    print(123)
# not work
# ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
if np.array([1, 2, 3]):
    print(123)
```

So the workable approach is to convert `np.array` back to list:
```python
import tensorflow as tf;
import numpy as np;

def Model(shape):
  input_shapes = [np.array(shape,dtype=np.int32), np.array(shape,dtype=np.int32) // 2, np.array(shape,dtype=np.int32) // 4];
  print(input_shapes)
  inputs = [tf.keras.Input(list(input_shape)) for input_shape in input_shapes];
  outputs = list();
  for input in inputs:
    output = tf.keras.layers.Conv2D(filters=10,kernel_size=(3,3), padding='same')(input);
    outputs.append(output);
  return tf.keras.Model(inputs = inputs, outputs = outputs);
  
model = Model([32,32,32]);
model.save('model.h5');
```
