### ISSUE TITLE
Ungooglable error: dataset map over dictionaries with multiple input paths and float outputs

### ISSUE THREAD

**Issue by caseybasichis** [tensorflow/tensorflow#32562]
The error in TF2b: "ValueError: elems must be a 1+ dimensional Tensor, not a scalar"

A StackOverflow bounty is a few days from expiring; docs and code.  At my wits' end.

[SO 100+ bounty and gunga galunga](https://stackoverflow.com/questions/57894869/tf-dataset-multiple-path-inputs-and-mapping-per-batch-to-load-images)

**Comment by pandrey-fr** [comment]
Hi,
I posted a suggested fix on the SO issue (which works as far as your `load_image` function is concerned.
Long story short: as indicated in the exception message, you were trying to feed float values as argument to a function expected tensor(s) :-)

**Comment by oanush** [comment]
@caseybasichis ,
Can you please refer the suggestion provided by @pandrey-fr , kindly find the [link](https://stackoverflow.com/questions/57894869/tf-dataset-multiple-path-inputs-and-mapping-per-batch-to-load-images) for the same.Thanks!

**Comment by oanush** [comment]
@caseybasichis ,
Any update on the issue ?Thanks!

**Comment by oanush** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
