### ISSUE TITLE
Assertion error when using mask with unrolled stacked LSTM

### ISSUE THREAD

**Issue by neonrights** [tensorflow/tensorflow#32570]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: n/a
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below): 1.14
- Python version: 3.6
- Bazel version (if compiling from source): n/a
- GCC/Compiler version (if compiling from source): n/a
- CUDA/cuDNN version: n/a
- GPU model and memory: no GPU, 32 GB ram

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
I receive an assertion error when creating a forward pass for an unrolled multi-layer LSTM while using a mask.

**Describe the expected behavior**
No assertion error, or at least a better explanation as to the cause.

**Code to reproduce the issue**
```python
import tensorflow as tf

inputs = tf.placeholder(tf.float32, (3,4,5))
mask = tf.placeholder(tf.bool, (3,4))

single_cells = [tf.keras.layer.LSTMCell(10) for _ in range(3)]
multi_cell = tf.keras.layers.StackedRNNCell(cells=single_cells)
lstm = tf.keras.layers.RNN(cell=multi_cell, unroll=True)
output, state = lstm(inputs=inputs, mask=mask)  # <- assertion error occurs here
```

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by ravikyram** [comment]
@neonrights 
I tried in colab with TF version 1.14 and 1.15.0-rc0 and i am getting the below error`.AttributeError: module 'tensorflow.python.keras.api._v1.keras' has no attribute 'layer'` . I am attaching the [gist ](https://colab.sandbox.google.com/gist/ravikyram/9603c7f3d9814aa73513ef4db56f94b0/untitled193.ipynb)for your reference. Thanks!

**Comment by neonrights** [comment]
Sorry I have a typo in my code, try this instead

```python
import tensorflow as tf

inputs = tf.placeholder(tf.float32, (3,4,5))
mask = tf.placeholder(tf.bool, (3,4))

single_cells = [tf.keras.layers.LSTMCell(10) for _ in range(3)]
multi_cell = tf.keras.layers.StackedRNNCells(cells=single_cells)
lstm = tf.keras.layers.RNN(cell=multi_cell, unroll=True)
output, state = lstm(inputs=inputs, mask=mask)  # <- assertion error occurs here
```

**Comment by ravikyram** [comment]
I have tried on colab with TF version 1.14 ,1.15.0-rc0 and was able to reproduce the issue.Please, find the gist [here](https://colab.sandbox.google.com/gist/ravikyram/e202ba52a64cfd2a3fb1f51bd50f9b67/untitled200.ipynb).Thanks!
