### ISSUE TITLE
Unable to find pip package

### ISSUE THREAD

**Issue by SundeepPidugu** [tensorflow/tensorflow#32577]
I have been using bazel build for my im2txt model from TensorFlow and it shows me

`ModuleNotFoundError: No module named 'nltk'`

I have installed the package nltk and tried to even create an environment and run the bazel script

Is there anyway i need to link my python to bazel for the python modules to be installed separately on an environment ?

Repo i am trying to run : im2txt

Code sample which iam running :
```
# Location to save the MSCOCO data.
MSCOCO_DIR="${HOME}/im2txt/data/mscoco"

# Build the preprocessing script.
cd research/im2txt
bazel build //im2txt:download_and_preprocess_mscoco

# Run the preprocessing script.
bazel-bin/im2txt/download_and_preprocess_mscoco "${MSCOCO_DIR}"   ##Error here <----
```

**Comment by mihaimaruseac** [comment]
Are `nltk` and `tensorflow` installed in the same environment?

**Comment by SundeepPidugu** [comment]
You mean the bazel environment ? If so please let me know how can I do that, I tried by creating a python virtual environment and tried running but I had no luck.

**Comment by oanush** [comment]
@SundeepPidugu ,
Just verifying, have you installed `bazel` `nltk` and `tensorflow` in the same environment ? try running the repo from the environment where all three are installed. Thanks!

**Comment by SundeepPidugu** [comment]
@oanush i created the virtual env in python and installed nltk and tensorflow, but bazel is installed on my machine and not in the environment, I never used bazel and i have no idea on that please help me on what exactly i need to do.

**Comment by oanush** [comment]
@SundeepPidugu ,
Can you please refer the [link](https://gist.github.com/kmhofmann/e368a2ebba05f807fa1a90b3bf9a1e03) and let us know if it helps.Thanks!

**Comment by SundeepPidugu** [comment]
Thanks @oanush will try and update you ASAP.

**Comment by SundeepPidugu** [comment]
Unable to run `bash ./compile.sh` it throws me an error despite having `1.8.0_22`.

**Comment by oanush** [comment]
@SundeepPidugu ,
Can you please provide us the error logs which is faced?Thanks!

**Comment by oanush** [comment]
@SundeepPidugu ,
Hi,Any update on the issue ?Thanks!

**Comment by oanush** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
