### ISSUE TITLE
TF2.0RC1/RC0  the output shape of  custom layer is None. The same code works in TF2.0 Beta1

### ISSUE THREAD

**Issue by KANGRuipeng** [tensorflow/tensorflow#32575]
**System information**
- TensorFlow installed from (source or binary): Binary
- TensorFlow version (use command below): TF2.0.0beta1/rc0/rc1
- Python version: 3.6
- CUDA/cuDNN version: 10.0
- GPU model and memory: TitanV

**Comment by KANGRuipeng** [comment]
We use a custom c++ op writen by ourself.

**Comment by jvishnuvardhan** [comment]
@KANGRuipeng If you have developed custom c++ op that works for `TF2.0b1`, then you can update the same for `TF2.0rc1`. 

[Here](https://github.com/tensorflow/custom-op) is a seperate repository under tensorflow for developing custom op. Thanks!

This is not Build/Installation or Bug/Performance issue. Please post this kind of support questions at [Stackoverflow](https://stackoverflow.com/questions/tagged/tensorflow). There is a big community to support and learn from your questions. GitHub is mainly for addressing bugs in installation and performance. Thanks!

**Comment by KANGRuipeng** [comment]
@jvishnuvardhan I'll add an example. I think this is a bug of TF.

**Comment by KANGRuipeng** [comment]
@jvishnuvardhan From TF2.0.0RC0，TensorFlow 2.0.0 is built using GCC7, however, you didn't say this in TF2.0.0RC0's  release notes.(You metioned this in TF2.0.0RC1's release notes) .

**Comment by jvishnuvardhan** [comment]
@KANGRuipeng Please post custom_ops related issue in that repo. When you post a new issue, please add a small standalone example to reproduce the issue. If the issue is more related to TF Core then post it in this repo. Thanks again.

**Comment by KANGRuipeng** [comment]
The problem is caused by GCC Version. Thks!
