### ISSUE TITLE
sparse_softmax_cross_entropy_with_logits fails for symbolic tensors in eager mode

### ISSUE THREAD

**Issue by mpdn** [tensorflow/tensorflow#32578]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): MacOS
- TensorFlow installed from (source or binary): pip
- TensorFlow version (use command below): 2.0.0-rc0
- Python version: 3.6

This code:
```
tf.nn.sparse_softmax_cross_entropy_with_logits(
    tf.keras.layers.Input((None,), dtype=tf.int32),
    tf.keras.layers.Input((None,None)))
```

Fails with this exception:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/ops/nn_ops.py", line 3477, in sparse_softmax_cross_entropy_with_logits_v2
    labels=labels, logits=logits, name=name)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/ops/nn_ops.py", line 3410, in sparse_softmax_cross_entropy_with_logits
    array_ops.shape(logits)[:-1]))
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/ops/check_ops.py", line 506, in assert_equal
    if not condition:
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/ops.py", line 765, in __bool__
    self._disallow_bool_casting()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/ops.py", line 534, in _disallow_bool_casting
    self._disallow_in_graph_mode("using a `tf.Tensor` as a Python `bool`")
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/ops.py", line 523, in _disallow_in_graph_mode
    " this function with @tf.function.".format(task))
tensorflow.python.framework.errors_impl.OperatorNotAllowedInGraphError: using a `tf.Tensor` as a Python `bool` is not allowed in Graph execution. Use Eager execution or decorate this function with @tf.function.
```

But this works:
```
tf.compat.v1.disable_eager_execution()
tf.nn.sparse_softmax_cross_entropy_with_logits(
    tf.keras.layers.Input((None,), dtype=tf.int32),
    tf.keras.layers.Input((None,None)))
```

Seems similar to #31848, although the underlying issue here is `assert_equal` not faring well with symbolic tensors in eager mode. The issue seems to be from here:

https://github.com/tensorflow/tensorflow/blob/d5efc0e9fd431586e4ebd63a9716577f6a59ba02/tensorflow/python/ops/check_ops.py#L330-L334

Here a tensor is cast to a boolean in eager mode, but that is not possible in the case of a symbolic keras tensor - even though tensorflow is executing eagerly.

**Comment by ravikyram** [comment]
I have tried on colab with TF version 2.0.0-rc0, 2.0.0-rc1 and was able to reproduce the issue.Please, find the gist [here](https://colab.sandbox.google.com/gist/ravikyram/662cb67709e65d8df22e61fe73232033/untitled198.ipynb).Thanks!

**Comment by jvishnuvardhan** [comment]
@noctune Can you try this way and let me know what you think. Thanks!

```
import tensorflow as tf 
tf.__version__
a = tf.keras.layers.Input((None,), dtype=tf.int32)
b = tf.keras.layers.Input((None,None))
@tf.function
def crossEntropy_estimate(a,b):
  return tf.nn.sparse_softmax_cross_entropy_with_logits(a, b)

tf.keras.layers.Lambda(crossEntropy_estimate,arguments={'a':a, 'b':b})
```

**Comment by noctune** [comment]
What I ended up using is slightly different:

```
import tensorflow as tf
a = tf.keras.layers.Input((None,), dtype=tf.int32)
b = tf.keras.layers.Input((None,None))
tf.keras.layers.Lambda(lambda args: tf.nn.sparse_softmax_cross_entropy_with_logits(*args))((a,b))
```

It's a weird workaround, but it works. Thanks!

**Comment by jvishnuvardhan** [comment]
I am closing the issue as it was resolved. Please feel free to open it if the issue persists again. Thanks!

**Comment by noctune** [comment]
> I am closing the issue as it was resolved.

A workaround was presented, but it seems to me like the underlying issue is still not resolved. Shouldn't `sparse_softmax_cross_entropy_with_logits` work with symbolic tensors?

**Comment by pavithrasv** [comment]
@mpdn how are you using this? You can combine tf ops with Keras layers in a model created in the Keras functional style.

**Comment by mpdn** [comment]
I was trying to create a custom loss that had a dependency on the input data, similar to this stackoverflow answer: https://stackoverflow.com/a/57919819/798414

I don't quite get what you mean by the "you can combine tf ops with Keras layers...", as this issue is a bug when trying to do exactly that.

**Comment by pavithrasv** [comment]
Thank you for the response. You can create a custom loss that depends on the label by using `add_loss` API in a custom layer. Please see the add_loss examples here. The VAE example is close to what you are looking for: https://www.tensorflow.org/guide/keras/custom_layers_and_models

Here is another small [colab](https://colab.research.google.com/drive/1mz1vtC-iVAkgMQLRZGNBSDTUqTowgSNK) example.
