### ISSUE TITLE
RNN does not forward the training flag to StackedRNNCells

### ISSUE THREAD

**Issue by guillaumekln** [tensorflow/tensorflow#32586]
**System information**
- Have I written custom code: Yes
- OS Platform and Distribution: Ubuntu 16.04
- TensorFlow installed from: binary
- TensorFlow version: 2.0.0rc0
- Python version: 3.6.6

**Describe the current behavior**

When using `tf.keras.layers.StackedRNNCells` with `tf.keras.layers.RNN`, the RNN layer does not forward the `training` flag to the cell. This is because the RNN code checks that cell explictly defines the `training` flag as argument, which `tf.keras.layers.StackedRNNCells` does not.

https://github.com/tensorflow/tensorflow/blob/r2.0/tensorflow/python/keras/layers/recurrent.py#L709-L710

**Describe the expected behavior**

The `training` flag should be passed to `tf.keras.layers.StackedRNNCells`, and to each stacked cell.

**Code to reproduce the issue**

The code below should not raise the `AssertionError`:

```python
import tensorflow as tf

class CellWrapper(tf.keras.layers.AbstractRNNCell):

    def __init__(self, cell):
        super(CellWrapper, self).__init__()
        self.cell = cell

    @property
    def state_size(self):
        return self.cell.state_size

    @property
    def output_size(self):
        return self.cell.output_size

    def get_initial_state(self, inputs=None, batch_size=None, dtype=None):
        return self.cell.get_initial_state(
            inputs=inputs, batch_size=batch_size, dtype=dtype)

    def call(self, inputs, states, training=None, **kwargs):
        assert training is not None


cell = tf.keras.layers.LSTMCell(32)
cell = CellWrapper(cell)
cell = tf.keras.layers.StackedRNNCells([cell])

rnn = tf.keras.layers.RNN(cell)
inputs = tf.random.uniform([4, 7, 16])
rnn(inputs, training=True)
```

**Comment by gowthamkpr** [comment]
Was able to reproduce this issue. Please find the attachment of github gist [here](https://colab.sandbox.google.com/gist/gowthamkpr/6e1f7a532de56ec863606e7f1657f1c3/untitled144.ipynb).
