### ISSUE TITLE
Horrible Energy Impact when opening tensorflow.org with Safari

### ISSUE THREAD

**Issue by gitfourteen** [tensorflow/tensorflow#32585]
<img width="801" alt="image" src="https://user-images.githubusercontent.com/22335780/65037849-25d16800-d981-11e9-8167-e17cbdae72d0.png">

Not sure it appropriate issue this kind problem here, but got nothing with google. 
Every time opening https://www.tensorflow.org, the battery consuming speed is unreasonably high, why?

**Comment by ymodak** [comment]
This question is better suited on Apple Support forums.
See https://discussions.apple.com/welcome
I was not able to repro the energy consumption as reported. Energy impact was 66.2 for me using Google Chrome browser.
Perhaps you can try using other browsers and reach out to the support forums to seek additional help.
Thanks!
