### ISSUE TITLE
tf.contrib.summary.scalar does not record anything outside of always_record_summaries in eager execution

### ISSUE THREAD

**Issue by yunabe** [tensorflow/tensorflow#32587]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Colab
- TensorFlow installed from (source or binary): Colab builtin
- TensorFlow version (use command below): 1.14.0
- Python version: 3.6.8
- GCC/Compiler version (if compiling from source): [GCC 8.0.1 20180414 (experimental) [trunk revision 259383]]

**Describe the current behavior**

https://colab.research.google.com/drive/1c1SUEet_jCxvW8D_ZlmOCPJvutB3PhCD
This code does not record anything in eager execution mode.

```
writer = tf.contrib.summary.create_file_writer(os.path.join(logdir, 'contrib'))
with writer.as_default():
  for i in range(1000):
    if i % 10 == 0:
      tf.contrib.summary.scalar('sin', math.sin(2*math.pi/500), step=i+1)
writer.close()
```

**Describe the expected behavior**

`tf.contrib.summary.scalar` should save records even out side of `always_record_summaries()`  by default.

It's very unnatural that we need to call `always_record_summaries` or `record_summaries_every_n_global_steps` to save records in eager execution mode.

https://www.tensorflow.org/guide/eager#summaries_and_tensorboard

**Code to reproduce the issue**
https://colab.research.google.com/drive/1c1SUEet_jCxvW8D_ZlmOCPJvutB3PhCD

**Comment by nfelt** [comment]
We're no longer making changes to the contrib summary API, but if you try the TF 2.0 `tf.summary` API, it should look similar to contrib, but doesn't require calling `always_record_summaries()` - summaries are on by default.
