### ISSUE TITLE
Need to save tf model in .h5 format

### ISSUE THREAD

**Issue by Harikrishnah007** [tensorflow/tensorflow#32581]
I have a trained model in ONNX and i have ported that to TF using below code programmaticaly.
(TensorflowRep). (onnx_tf.backend.prepare ).
A TensorflowRep class object representing the ONNX model
onnx_tf.backend_rep.TensorflowRep.export_graph
How can I save the model to disk?
Can I save this in .h5 format.

**Comment by gowthamkpr** [comment]
@Harikrishnah007 Please take a look at this [issue](https://github.com/onnx/onnx-tensorflow/issues/490)  and let me know if it helps. Also create an issue in the [onnx/onnx-tensorflow](https://github.com/onnx/onnx-tensorflow/issues) repo as this issue is more suitable to that repo. Thanks!
