### ISSUE TITLE
tf.compat.v2.summary should be used in /guide/eager#summaries_and_tensorboard

### ISSUE THREAD

**Issue by yunabe** [tensorflow/tensorflow#32588]
## URL(s) with the issue:

https://www.tensorflow.org/guide/eager#summaries_and_tensorboard

## Description of issue (what needs changing):

We should not recommend the usage of `tf.contrib.summary` in eager mode.
`tf.compat.v2.summary` (or `tf.summary` in TF2) should be used in this section.

With `tf.contrib.summary`, we need to use `always_record_summaries()` or `record_summaries_every_n_global_steps()` (#32587) to record events even in eager mode. This is very unnatural and confusing.

When I read this section, I thought `record_summaries_every_n_global_steps()` is optional and spent a lot of time to notice why `tf.contrib.summary.scalar` operations in my code was no-op.

In eager mode, I think we should recommend code like:

```
for i in range(num_steps):
  loss = train_one_step()
  step = i + 1
  if step % 100 == 0:
    tf_summary.scalar('loss', loss, step=step)
```

with `tf.compat.v2.summary`.

### Submit a pull request?

Are you planning to also submit a pull request to fix the issue? 

**Yes**

See the docs
contributor guide: https://www.tensorflow.org/community/contribute/docs and the
docs style guide: https://www.tensorflow.org/community/contribute/docs_style

**Comment by jvishnuvardhan** [comment]
@yunabe `tf.contrib` won't be there is `TF2.0`. The current doc is for `TF1.x`. TF community is working on `TF2.0` docs and will be updated in the near future. If you want to contribute, please raise a PR to update the docs for `TF2.0`. Please let us know what you think?. Thanks!

**Comment by yunabe** [comment]
I'm happy to contribute to the doc. I'm sending a PR for the section.

**Comment by yunabe** [comment]
I noticed the section about Tensorboard and summary was deleted in `master` branch by [this commit](https://github.com/tensorflow/docs/commit/b1658ccbdd86e19251c5fd58ce962e78437e95ff#diff-32b6b3f97f424a88c5360b84619e5257).

Does this means we will not explain about tf.summary in eager.md after TF2 launch?

**Comment by yunabe** [comment]
Anyway, I sent a PR to `master` branch: https://github.com/tensorflow/docs/pull/1044

**Comment by yunabe** [comment]
According to the discussion of https://github.com/tensorflow/docs/pull/1044, it seems like that the live site won't be updated until TF2 launch.

I'm not very happy about the fact that TensoFlow guide aren't updated for a while though many people are interested to learn TF2.0. But I understand TF team is busy for TF2 releases.

I'm closing this bug because I added a tf.summary section to the new TF2 tutorial and we can not fix this issue on the site until TF2 release.
