### ISSUE TITLE
Deep Dream Tutorial with UnsupportedOperation: fileno

### ISSUE THREAD

**Issue by zuoxingdong** [tensorflow/tensorflow#3260]
When running Deep Dream Tutorial on Jupyter Notebook, for the section of Naive feature visualization, it shows following

`UnsupportedOperation: fileno`

backtracked up from 

`PIL.Image.fromarray(a).save(f, fmt)`

upto  `PIL/ImageFile.pyc in _save(im, fp, tile)`

```
    475     try:
--> 476         fh = fp.fileno()
    477         fp.flush()
    478     except AttributeError:
```

The TensorFlow is installed under Anaconda and created an environment with internal installation of PIL package. 
```
source activate tensorflow
conda install PIL
```

**Comment by jmchen-g** [comment]
Please provide operating system, GPU version if used, tensorflow version, etc...

**Comment by zuoxingdong** [comment]
Ubuntu 16.04 LTS
CPU only
TensorFlow 0.9

**Comment by martinwicke** [comment]
That's weird, is the jupyter notebook running on something that doesn't allow for file i/o?

**Comment by zjharper** [comment]
Running Jupyter with a Python3 kernel resolved this for me. Noting that fileno() for [Python3](https://docs.python.org/3/library/io.html#io.IOBase.fileno) raises a different exception than [Python2](https://docs.python.org/2/library/io.html#io.IOBase.fileno), there may be something fishy in the stream.

**Comment by martinwicke** [comment]
Ok. I have no idea what this is, I'm glad there's a workaround. I'll close this issue, this doesn't feel like something we can fix in TensorFlow.
