### ISSUE TITLE
"node optimization/gradients has inputs from different frames" on GPU, but works fine on CPU

### ISSUE THREAD

**Issue by myy920213** [tensorflow/tensorflow#32607]
------------------------

### System information
- **I'm writing a customer LSTMCell, I referred the source code in tensorflow/python/ops/rnn_cell_impl.py. I only add one line of operations on top of the source code.**:
- **Linux Ubuntu**: 16.04
- **TensorFlow version**: 1.13.1
- **Python version**: 3.5.2
- **CUDA/cuDNN version**: v10.1.168
- **GPU**: Tesla v100

### Describe the problem
I'm writing a customer LSTMCell, I followed the source code in tensorflow/python/ops/rnn_cell_impl.py, just add one more line "d = tf.multiply(f, (tf.ones_like(f)-f))". Everything works fine on CPU, but raise "node optimization/gradients has inputs from different frames" error while running on GPU. I didn't use any operation that's invalid on CUDA, only regular tensor operations like multiplication.

### Source code / logs
"defined customer LSTM Cell":

    from __future__ import absolute_import
    from __future__ import division
    from __future__ import print_function

    from tensorflow.python.framework import constant_op
    from tensorflow.python.framework import dtypes

    from tensorflow.python.layers import base as base_layer
    from tensorflow.python.ops import array_ops

    from tensorflow.python.ops import init_ops
    from tensorflow.python.ops import math_ops
    from tensorflow.python.ops import nn_ops
    from tensorflow.python.platform import tf_logging as logging
    from tensorflow.contrib.rnn import BasicLSTMCell as BasicLSTMCell
    from tensorflow.contrib.rnn import LSTMStateTuple
    import tensorflow as tf

    _BIAS_VARIABLE_NAME = "bias"
    _WEIGHTS_VARIABLE_NAME = "kernel"

    class ProxLSTMCell(BasicLSTMCell):

      def __init__(self, num_units, forget_bias=1.0,
                   state_is_tuple=True, activation=None, reuse=None, name='basic_lstm_cell', lamb 
          = 1.0, delta = 1.0):
          super(ProxLSTMCell, self).__init__(num_units = num_units, reuse=reuse, name=name)
          if not state_is_tuple:
          logging.warn("%s: Using a concatenated state is slower and will soon be "
                       "deprecated.  Use state_is_tuple=True.", self)

         # Inputs must be 2-dimensional.
         self.input_spec = base_layer.InputSpec(ndim=2)

         self._num_units = num_units
         self._forget_bias = forget_bias
         self._state_is_tuple = state_is_tuple
         self.lamb = lamb
         self.delta = delta

     @property
     def state_size(self):
       return (LSTMStateTuple(self._num_units, self._num_units)
              if self._state_is_tuple else 2 * self._num_units)

      @property
      def output_size(self):
        return self._num_units

      def build(self, inputs_shape):
        if inputs_shape[1].value is None:
         raise ValueError("Expected inputs.shape[-1] to be known, saw shape: %s"
                       % inputs_shape)

         input_depth = inputs_shape[1].value
         self.input_size = input_depth
         h_depth = self._num_units
         self._kernel = self.add_variable(
         _WEIGHTS_VARIABLE_NAME,
         shape=[input_depth + h_depth, 4 * self._num_units])
         self._bias = self.add_variable(
         _BIAS_VARIABLE_NAME,
         shape=[4 * self._num_units],
         initializer=init_ops.zeros_initializer(dtype=self.dtype))

         self.built = True

      def call(self, inputs, state):
                 """Long short-term memory cell (LSTM).
    sigmoid = math_ops.sigmoid
    one = constant_op.constant(1, dtype=dtypes.int32)
    # Parameters of gates are concatenated into one multiply for efficiency.
    if self._state_is_tuple:
      c, h = state
    else:
      c, h = array_ops.split(value=state, num_or_size_splits=2, axis=one)

    gate_inputs = math_ops.matmul(
        array_ops.concat([inputs, h], 1), self._kernel)
    gate_inputs = nn_ops.bias_add(gate_inputs, self._bias)

    # i = input_gate, j = new_input, f = forget_gate, o = output_gate
    i, j, f, o = array_ops.split(
        value=gate_inputs, num_or_size_splits=4, axis=one)

    forget_bias_tensor = constant_op.constant(self._forget_bias, dtype=f.dtype)
    # Note that using `add` and `multiply` instead of `+` and `*` gives a
    # performance improvement. So using those at the cost of readability.
    add = math_ops.add
    multiply = math_ops.multiply
    new_c = add(multiply(c, sigmoid(add(f, forget_bias_tensor))),
                multiply(sigmoid(i), self._activation(j)))
    new_h = multiply(self._activation(new_c), sigmoid(o))
    d = multiply(f, (tf.ones_like(f)-f))

    new_c = new_c + d
    if self._state_is_tuple:
      new_state = LSTMStateTuple(new_c, new_h)
    else:
      new_state = array_ops.concat([new_c, new_h], 1)
    return new_h, new_state

''Calling defined LSTM Cell'':
```
def LSTM_graph():

........

prox_cell = ProxLSTM.ProxLSTMCell(
        num_units=self.cell_size,
        forget_bias=0.0,
        reuse=tf.get_variable_scope().reuse,
        lamb=FLAGS.lamb,
        delta=FLAGS.delta)
cell = tf.contrib.rnn.MultiRNNCell([
              prox_cell
              for _ in xrange(self.num_layers)
          ])

lstm_out, next_state = tf.nn.dynamic_rnn(
          cell, x, initial_state=initial_state, sequence_length=seq_length)

return lstm_out, next_state



"Error message":

tensorflow.python.framework.errors_impl.InvalidArgumentError: node optimization/gradients/LSTM/rnn/while/rnn/multi_
rnn_cell/cell_0/basic_lstm_cell/MatMul_grad/MatMul (defined at /workspace/adversarial_text/layers.py:327)  has inpu
ts from different frames. The input node optimization/gradients/LSTM/rnn/while/rnn/multi_rnn_cell/cell_0/basic_lstm
_cell/split_grad/concat (defined at /workspace/adversarial_text/layers.py:327)  is in frame ''. The input node opti
mization/gradients/LSTM/rnn/while/rnn/multi_rnn_cell/cell_0/basic_lstm_cell/MatMul_grad/MatMul/Enter (defined at /w
orkspace/adversarial_text/layers.py:327)  is in frame 'optimization/gradients/LSTM/rnn/while/while_context'.
```

**Comment by oanush** [comment]
@myy920213 ,
Looks like the code provided is incomplete,can you please share a simple standalone code to reproduce the issue reported here ? Thanks!

**Comment by myy920213** [comment]
Sorry for the late response. I write up a simple test case to reproduce this error. I uploaded the python file as zip, run simple_test.py will reproduce the error. newLSTM class defines the customer LSTM layer, mainly copied from tensorflow/python/ops/rnn_cell_impl.py, only ''d = multiply(f, (tf.ones_like(f)-f))'' is newly added.
Apparently, change the gradient aggregation_method to tf.AggregationMethod.EXPERIMENTAL_TREE or tf.AggregationMethod.ADD_N  will fix this error but will take too much memory space. I'm just very confusing why this error occurs by just adding one line of code and I didn't use any operations other than multiply, +, - in this line.
Thanks!

[simple_test.py.zip](https://github.com/tensorflow/tensorflow/files/3672233/simple_test.py.zip)




> @myy920213 ,
> Looks like the code provided is incomplete,can you please share a simple standalone code to reproduce the issue reported here ? Thanks!

**Comment by oanush** [comment]
@myy920213 ,
When tried executing the given code i got the as present in the [gist](https://colab.sandbox.google.com/gist/oanush/5a89ff690cd4c5e9ad5f75d4e53f6b61/32607.ipynb) of colab.Thanks!

**Comment by myy920213** [comment]
> @myy920213 ,
> When tried executing the given code i got the as present in the [gist](https://colab.sandbox.google.com/gist/oanush/5a89ff690cd4c5e9ad5f75d4e53f6b61/32607.ipynb) of colab.Thanks!

Thanks for your response.
This code used to work on my own laptop, but will show the same error when running on Google cloud or AWS GPU instances. So I guessed the problem was running with GPU. 
After running the colab notebook you provided, I realized this problem may not be running with GPU, as I created a new colab notebook and run this code without using GPU, this error occur again. Here is the colab page: (https://colab.research.google.com/drive/1qWh8F2iFfM64seNESDUrnIuofWrev1Kv#scrollTo=zuetCbHVoKZA)

**Comment by oanush** [comment]
> > @myy920213 ,
> > When tried executing the given code i got the as present in the [gist](https://colab.sandbox.google.com/gist/oanush/5a89ff690cd4c5e9ad5f75d4e53f6b61/32607.ipynb) of colab.Thanks!
> 
> Thanks for your response.
> This code used to work on my own laptop, but will show the same error when running on Google cloud or AWS GPU instances. So I guessed the problem was running with GPU.
> After running the colab notebook you provided, I realized this problem may not be running with GPU, as I created a new colab notebook and run this code without using GPU, this error occur again. Here is the colab page: (https://colab.research.google.com/drive/1qWh8F2iFfM64seNESDUrnIuofWrev1Kv#scrollTo=zuetCbHVoKZA)

@myy920213 ,
Can you please provide access to the colab gist? Thanks!

**Comment by myy920213** [comment]
> > > @myy920213 ,
> > > When tried executing the given code i got the as present in the [gist](https://colab.sandbox.google.com/gist/oanush/5a89ff690cd4c5e9ad5f75d4e53f6b61/32607.ipynb) of colab.Thanks!
> > 
> > 
> > Thanks for your response.
> > This code used to work on my own laptop, but will show the same error when running on Google cloud or AWS GPU instances. So I guessed the problem was running with GPU.
> > After running the colab notebook you provided, I realized this problem may not be running with GPU, as I created a new colab notebook and run this code without using GPU, this error occur again. Here is the colab page: (https://colab.research.google.com/drive/1qWh8F2iFfM64seNESDUrnIuofWrev1Kv#scrollTo=zuetCbHVoKZA)
> 
> @myy920213 ,
> Can you please provide access to the colab gist? Thanks!

Sorry about that, I updated the share access. Could you please try again? (https://colab.research.google.com/drive/1qWh8F2iFfM64seNESDUrnIuofWrev1Kv)

**Comment by oanush** [comment]
@myy920213 ,
When tried executing the code in TF-1.15rc1, i didn't faced any error. Take a look at the [gist](https://colab.sandbox.google.com/gist/oanush/8b5a7733bef89bc0c729d1850945e14f/git_test.ipynb#scrollTo=Kaj240A0Yrty) of colab.Thanks!

**Comment by oanush** [comment]
@myy920213,
Any update on the issue ?Thanks!

**Comment by myy920213** [comment]
> @myy920213,
> Any update on the issue ?Thanks!

Thanks! I will close this issue now.
