### ISSUE TITLE
Support for TensorForest

### ISSUE THREAD

**Issue by gd12345** [tensorflow/tensorflow#32609]
**System information**
- OS Platform and Distribution Linux Ubuntu 18.04
- TensorFlow installed from binary
- TensorFlow version 1.14

Text from TFLite converter:

Some of the operators in the model are not supported by the standard TensorFlow Lite runtime. If those are native TensorFlow operators, you might be able to use the extended runtime by passing --enable_select_tf_ops, or by setting target_ops=TFLITE_BUILTINS,SELECT_TF_OPS when calling tf.lite.TFLiteConverter(). Otherwise, if you have a custom implementation for them you can disable this error with --allow_custom_ops, or by setting allow_custom_ops=True when calling tf.lite.TFLiteConverter(). Here is a list of builtin operators you are using: ARG_MAX, DIV, PACK, SUM. Here is a list of operators for which you will need custom implementations: DecisionTreeResourceHandleOp, TreePredictionsV4.

**Comment by ravikyram** [comment]
Can you please elaborate about the issue & the context.Will it be possible to provide related code.Thanks!

**Comment by gd12345** [comment]
I have build a tensor_forest model in tensorflow and have saved it as "saved_model.ckpt". I want to use this model in Android, for which below steps are followed:

1. The freeze graph is created using:
from tensorflow.python.tools import freeze_graph
graph = tf.get_default_graph()
input_graph_def = graph.as_graph_def()

saver.restore(sess, "./saved_model.ckpt")
node_names = [node.name for node in input_graph_def.node]

2.  Frozen model .pb file is created using below code:

output_node_names = "The node names"
output_graph_def = tf.graph_util.convert_variables_to_constants(
            sess, # The session
            input_graph_def, # input_graph_def is useful for retrieving the nodes 
            output_node_names.split(",")  
output_graph="./saved_Frozen_Model.pb"
with tf.gfile.GFile(output_graph, "wb") as f:
    f.write(output_graph_def.SerializeToString())
sess.close()

3. The forzen model is converted into TFLite model
converter = tf.lite.TFLiteConverter.from_saved_model(".")
converter_new.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS, tf.lite.OpsSet.SELECT_TF_OPS]
tflite_model = converter.convert()

While doing this conversion, I get the error messages
Converting unsupported operation: DecisionTreeResourceHandleOp
Unable to determine output type for op: DecisionTreeResourceHandleOp

And towards the end it asks to log an error in github and paste the below message:
Some of the operators in the model are not supported by the standard TensorFlow Lite runtime. If those are native TensorFlow operators, you might be able to use the extended runtime by passing --enable_select_tf_ops, or by setting target_ops=TFLITE_BUILTINS,SELECT_TF_OPS when calling tf.lite.TFLiteConverter(). Otherwise, if you have a custom implementation for them you can disable this error with --allow_custom_ops, or by setting allow_custom_ops=True when calling tf.lite.TFLiteConverter(). Here is a list of builtin operators you are using: ARG_MAX, DIV, PACK, SUM. Here is a list of operators for which you will need custom implementations: DecisionTreeResourceHandleOp, TreePredictionsV4.
Tensor forest  I tried to convert the tensor_forest model into TFLite model using TFLite converter. The code for the same is as below:

**Comment by gd12345** [comment]
Request a reply on this. Will tensor-forest be supported in tensor-flow lite?

**Comment by haozha111** [comment]
Hi gd12345,

I checked that the missing ops 'TreePredictionsV4' is under tensorflow/contrib directory, unfortunately this op can't be supported by TF Lite right now. Could you manage to find a replacement for the op outside of contrib/? (since contrib is going to be deprecated).

**Comment by gd12345** [comment]
How to manage it outside contrib?

What is the alternative of tensor forest in TFLite?

**Comment by haozha111** [comment]
Sorry. I was meaning if you could find an API for TensorForest outside of tf.contrib, since that's being deprecated. I think tensor_forest is still under migration (which will eventually be moved to core):
https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md

However, before that happens, I think there is no easy way to support TensorForest ops in TF Lite. Sorry about that.

**Comment by Saduf2019** [comment]
@gd12345  
Can you please update as per above comment

**Comment by gd12345** [comment]
Hi Haoza111,

Are there any near future plans to update tensorforest in the latest tensorflow versions? If so, we would like to et an update on it, as and when it happens.

**Comment by haozha111** [comment]
@jdduke ,do you know if there are timelines to support tensorforest?

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.

**Comment by gd12345** [comment]
Thanks for the reply.

We will try with tensorflow 2.0 and get back to you on this.

Regards,
Gauri

**Comment by AndrewWilliams3142** [comment]
Hi there,

Also wondering whether `tensor_forest` will be moved to `core` any time soon? It seems like this was the [original intent](https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md)? 

It would be great to have this functionality back :)

Thanks
Andrew
