### ISSUE TITLE
Failed to convert an RNN built with tf.keras by TFLiteConverter

### ISSUE THREAD

**Issue by bbb00437** [tensorflow/tensorflow#32608]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 7
- TensorFlow installed from (source or binary): binary
- TensorFlow version (or github SHA if from source): tensorflow-gpu 2.0.0rc1

**Provide the text output from tflite_convert**

```
Some of the operators in the model are not supported by the standard TensorFlow Lite runtime. If those are native TensorFlow operators, you might be able to use the extended runtime by passing --enable_select_tf_ops, or by setting target_ops=TFLITE_BUILTINS,SELECT_TF_OPS when calling tf.lite.TFLiteConverter(). Otherwise, if you have a custom implementation for them you can disable this error with --allow_custom_ops, or by setting allow_custom_ops=True when calling tf.lite.TFLiteConverter(). Here is a list of builtin operators you are using: RESHAPE, TRANSPOSE. Here is a list of operators for which you will need custom implementations: TensorListFromTensor, TensorListReserve, TensorListStack, While.
```

Also, please include a link to a GraphDef or the model if possible.

Code which would reproduce the error log:
```
from tensorflow.keras import layers, models
import tensorflow as tf

ipt = layers.Input((10, 5))
x = layers.SimpleRNN(1, return_sequences=True)(ipt)
model = models.Model(ipt, x)

cvt = tf.lite.TFLiteConverter.from_keras_model(model)
tflite_model = cvt.convert()
```

Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by haozha111** [comment]
Hi,

We are working on a new converter that can convert keras lstm/rnn into tflite. Please stay tuned!

**Comment by jvishnuvardhan** [comment]
@bbb00437 Can you check the with the new converter with an experimental flag `cvt.experimental_new_converter = True`. I ran your code with the experimental flag and works without any issue. Please take a look at the [gist here](https://colab.sandbox.google.com/gist/jvishnuvardhan/82af131c5bb275fbe683458510ca833a/untitled635.ipynb).

I am closing the issue as it was resolved with the new converter. Please feel free to reopen the issue if it persists again. thanks!
