### ISSUE TITLE
tensorrt6 compatibility

### ISSUE THREAD

**Issue by alanpurple** [tensorflow/tensorflow#32602]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):  Ubuntu 18.04.3 x64
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): source
- TensorFlow version: 2.0.0-rc2
- Python version: 3.7.4 x64
- Installed using virtualenv? pip? conda?: N/A
- Bazel version (if compiling from source): 0.26.1
- GCC/Compiler version (if compiling from source): 7.4.0
- CUDA/cuDNN version: 10.1, 7.6
- GPU model and memory:
GTX1080Ti GDDR5X 11GB X 7

**Describe the problem**
bazel build failed

**Provide the exact sequence of commands / steps that you executed before running into the problem**
./configure
add cuda,tensorrt
bazel build --config=opt --config=v2 //tensorflow/tools/pip_package:build_pip_package

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

```
ERROR: /home/wmind/.cache/bazel/_bazel_wmind/a0a15f0a32d3688786619e94912711cf/external/local_config_tensorrt/BUILD:43:1: Executing genrule @local_config_tensorrt//:tensorrt_include failed (Exit 1)
cp: cannot stat '/usr/include/x86_64-linux-gnu/NvInferPlugin.h': No such file or directory
```

**Comment by gadagashwini** [comment]
@alanpurple,
Provide the exact sequence of commands / steps that you executed before running into the problem.

**Comment by alanpurple** [comment]
@gadagashwini 
added

**Comment by angerson** [comment]
Can you include a full log from ./configure, as well as a list of the contents of the TensorRT directory you configured?

**Comment by alanpurple** [comment]
successfully build tensorflow 2.0 GA with tensorrt6

looks resolved
