### ISSUE TITLE
Tensorflow seems lost some module No module named 'numpy.core._multiarray_umath'

### ISSUE THREAD

**Issue by david2588e** [tensorflow/tensorflow#32600]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version (use command below):
- Python version:
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**

Requirement already satisfied: markdown>=2.6.8 in c:\programdata\anaconda3\lib\site-packages (from tensorboard<1.15.0,>=1.14.0->tensorflow) (3.1.1)
Requirement already satisfied: setuptools>=41.0.0 in c:\programdata\anaconda3\lib\site-packages (from tensorboard<1.15.0,>=1.14.0->tensorflow) (41.0.1)
Requirement already satisfied: h5py in c:\programdata\anaconda3\lib\site-packages (from keras-applications>=1.0.6->tensorflow) (2.8.0)
Installing collected packages: tensorflow
Successfully installed tensorflow-1.14.0

(base) C:\Users\Liu>python
Python 3.7.3 (default, Apr 24 2019, 15:29:51) [MSC v.1915 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'
ImportError: numpy.core.multiarray failed to import

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 980, in _find_and_load
SystemError: <class '_frozen_importlib._ModuleLockManager'> returned a result with an error set
ImportError: numpy.core._multiarray_umath failed to import
ImportError: numpy.core.umath failed to import
2019-09-18 08:38:07.989471: F tensorflow/python/lib/core/bfloat16.cc:675] Check failed: PyBfloat16_Type.tp_base != nullptr

**Describe the expected behavior**

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by gadagashwini** [comment]
@david2588e, 
Please provide the numpy version that you are using.
```
import numpy as np
np.__version__
```

**Comment by david2588e** [comment]
Thanks

>>> import numpy as np
>>> np.__version__
'1.15.1'

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: gadagashwini <notifications@github.com>
发送时间: Wednesday, September 18, 2019 5:19:52 PM
收件人: tensorflow/tensorflow <tensorflow@noreply.github.com>
抄送: david2588e <liujinyi@hotmail.com>; Mention <mention@noreply.github.com>
主题: Re: [tensorflow/tensorflow] Tensorflow seems lost some module No module named 'numpy.core._multiarray_umath' (#32600)


@david2588e<https://github.com/david2588e>,
Please provide the numpy version that you are using.

import numpy as np
np.__version__


―

**Comment by gadagashwini** [comment]
@david2588e, Please install numpy with 1.16.5 version. Let us know how it progresses. Thanks!

**Comment by david2588e** [comment]
Hallo Sir:

After install the numpy 1.16.5, now it is fine

Thanks

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: gadagashwini <notifications@github.com>
发送时间: Wednesday, September 18, 2019 7:55:21 PM
收件人: tensorflow/tensorflow <tensorflow@noreply.github.com>
抄送: david2588e <liujinyi@hotmail.com>; Mention <mention@noreply.github.com>
主题: Re: [tensorflow/tensorflow] Tensorflow seems lost some module No module named 'numpy.core._multiarray_umath' (#32600)


@david2588e<https://github.com/david2588e>, Please install numpy with 1.16.5 version. Let us know how it progresses. Thanks!

―

**Comment by gadagashwini** [comment]
@david2588e,
Glad it worked. 
Closing the issue. Thanks!
