### ISSUE TITLE
EmptyTensorList, TensorListFromTensor, TensorListReserve, TensorListStack, While.

### ISSUE THREAD

**Issue by LLLLLLoki** [tensorflow/tensorflow#32604]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- TensorFlow installed from (source or binary):
- TensorFlow version (or github SHA if from source):

**Provide the text output from tflite_convert**

```
# Copy and paste here
```

Also, please include a link to a GraphDef or the model if possible.

**Any other info / logs**

Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by gadagashwini** [comment]
@LLLLLLoki, Please provide the information asked in the above template. Thanks!

**Comment by gadagashwini** [comment]
@LLLLLLoki, Please fill the template.

**Comment by gadagashwini** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
