### ISSUE TITLE
Is there any documents of TF Core

### ISSUE THREAD

**Issue by KANGRuipeng** [tensorflow/tensorflow#32601]
Such as:

1. Global Flow Chart of Tensorflow
2. Graph modify for Model Optimization(Insert an op in backend)
3.  Basic Data Structure(Data management)
4. Detail of Communication for Distribute Strategy

**Comment by ravikyram** [comment]
Please, go through [distribution strategy ](https://www.tensorflow.org/beta/guide/distribute_strategy#examples_and_tutorials)tutorials and see if it helps you. Thanks!

**Comment by KANGRuipeng** [comment]
@ravikyram the distribution strategy tutorials only tell use how to use the strategy rather than how to optimize our distributed task

**Comment by KANGRuipeng** [comment]
@MarkDaoust  any feedback?

**Comment by MarkDaoust** [comment]
Aside from the "Global overview of tensorflow" I think we're doing okay here.

> Graph modify for Model Optimization(Insert an op in backend)
> Basic Data Structure(Data management)
> Detail of Communication for Distribute Strategy

Most of this is in the ["customzation" section of the guide](https://www.tensorflow.org/guide/eager). Which I think covers "add an op" and "basic data-structures".

For "Graph modifications" the team has opted not to document things like [Graph Transform tool](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/tools/graph_transforms) because we really don't think this is the future of the platform, everything's moving towards MLIR. 

> Detail of Communication for Distribute Strategy
> The distribution strategy tutorials only tell use how to use the strategy

The video linked from the guide  gives some more detail:  https://www.youtube.com/watch?v=jKV53r9-H14

**Comment by KANGRuipeng** [comment]
Here I give another example: 
In TF2.0, I have a keras model, if I use the **tf.keras.model.fit API**, my model will run in non-eager mode, if I use the **tf.keras.model.fit_generator** API, my model will run in eager mode. 
There is no docs tell us this. Most users may not care about this but there still some users interested in. The develop of TF want to hide the complexity but some users want to know more details.

**Comment by MarkDaoust** [comment]
> tf.keras.model.fit API, my model will run in non-eager mode, if I use the tf.keras.model.fit_generator.

Interesting. I was not aware of this. How did you come to this conclusion? 

It may be worth adding a note to the relavant tutorials over in https://github.com/tensorflow/docs

**Comment by jvishnuvardhan** [comment]
@KANGRuipeng Just a point to note. `model.fit` runs eagerly for performance related reasons, in case you want to run eagerly, you can use run_eagerly=True. On TF website, there is a place where it mentions about the eager mode as follows.

> Additionally, to make sure the model trains and evaluates eagerly, you can make sure to pass run_eagerly=True as a parameter to compile.

The above statement is in this TF [webpage](https://www.tensorflow.org/guide/keras/overview#train_and_evaluate). I think may be it is better to add little more info in that page. Thanks!

**Comment by KANGRuipeng** [comment]
@jvishnuvardhan I know this and I have read related docs.

**Comment by KANGRuipeng** [comment]
@MarkDaoust I found this when we move our code ti TF2.0

**Comment by nikitamaia** [comment]
Closing this issue now as many changes have been made to the docs in the last year. 

A few notes
`tf.keras.model.fit_generator` is now deprecated
There are new guides on basics of [graphs](https://www.tensorflow.org/guide/intro_to_graphs) and [performance with tf.function.](https://www.tensorflow.org/guide/function) There is also a [guide on optimizing GPU ](https://www.tensorflow.org/guide/gpu_performance_analysis)(including multi gpu) training.
