### ISSUE TITLE
How to set the four parameters in toco

### ISSUE THREAD

**Issue by ucasiggcas** [tensorflow/tensorflow#32611]
Linux Ubuntu 18.04:
- TensorFlow installed from `pip install tensorflow-gpu`:
- TensorFlow version 1.12.0:

In ckpt to pb I have used the 
`tf.contrib.quantize.create_eval_graph()`
So I use the type QUANTIZED_UINT8 in toco as 
`toco --graph_def_file=./my_freeze_graph_stft.pb --output_file=my_stft.tflite --output_format=TFLITE --input_shape=1024 --input_array=x_mixed --output_array=y_out2 --inference_type=QUANTIZED_UINT8 --inference_input_type=QUANTIZED_UINT8`

but I find the error
`    input_array.mean_value, input_array.std_value = quantized_input_stats[idx]
TypeError: 'NoneType' object is not subscriptable`
SO I must set the four parameters
`--std_dev_values`
`--mean_values`
`--default_ranges_min`
`--default_ranges_max`

SO how to set them ?any idea or advice/suggestuion ?

thx

**Comment by ucasiggcas** [comment]
another problem

if I use
`--std_dev_values=1 --mean_values=0`
then comes 
`b'2019-09-18 18:06:25.827623: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1080] Converting unsupported operation: TensorArrayV3\n2019-09-18 18:06:25.827705: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1127] Op node missing output type attribute: rnn/TensorArray\n2019-09-18 18:06:25.827723: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1080] Converting unsupported operation: TensorArrayV3\n2019-09-18 18:06:25.827734: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1127] Op node missing output type attribute: rnn/TensorArray_1\n2019-09-18 18:06:25.827766: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1080] Converting unsupported operation: TensorArrayScatterV3\n2019-09-18 18:06:25.827796: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1127] Op node missing output type attribute: rnn/TensorArrayUnstack/TensorArrayScatter/TensorArrayScatterV3\n2019-09-18 18:06:25.827815: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1080] Converting unsupported operation: Enter\n2019-09-18 18:06:25.827834: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1080] Converting unsupported operation: Enter\n2019-09-18 18:06:25.827846: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1080] Converting unsupported operation: Enter\n2019-09-18 18:06:25.827857: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1080] Converting unsupported operation: Enter\n2019-09-18 18:06:25.827867: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1080] Converting unsupported operation: Enter\n2019-09-18 18:06:25.827878: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1080] Converting unsupported operation: Enter\n2019-09-18 18:06:25.827898: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1080] Converting unsupported operation: Enter\n2019-09-18 18:06:25.827910: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1080] Converting unsupported operation: Enter\n2019-09-18 18:06:25.827923: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1080] Converting unsupported operation: LoopCond\n2019-09-18 18:06:25.827933: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1127] Op node missing output type attribute: rnn/while/LoopCond\n2019-09-18 18:06:25.827965: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1080] Converting unsupported operation: Enter\n2019-09-18 18:06:25.827976: I tensorflow/contrib/lite/toco/import_tensorflow.cc:189] Unsupported data type in placeholder op: 20\n2019-09-18 18:06:25.827985: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1080] Converting unsupported operation: Enter\n2019-09-18 18:06:25.827996: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1080] Converting unsupported operation: TensorArrayReadV3\n2019-09-18 18:06:25.828442: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1080] Converting unsupported operation: Enter\n2019-09-18 18:06:25.828462: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1080] Converting unsupported operation: Enter\n2019-09-18 18:06:25.828488: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1080] Converting unsupported operation: Enter\n2019-09-18 18:06:25.828523: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1080] Converting unsupported operation: Enter\n2019-09-18 18:06:25.828989: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1080] Converting unsupported operation: Enter\n2019-09-18 18:06:25.829024: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1080] Converting unsupported operation: Enter\n2019-09-18 18:06:25.829051: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1080] Converting unsupported operation: Enter\n2019-09-18 18:06:25.829066: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1080] Converting unsupported operation: Enter\n2019-09-18 18:06:25.829437: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1080] Converting unsupported operation: Enter\n2019-09-18 18:06:25.829475: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1080] Converting unsupported operation: Enter\n2019-09-18 18:06:25.829516: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1080] Converting unsupported operation: Enter\n2019-09-18 18:06:25.829531: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1080] Converting unsupported operation: Enter\n2019-09-18 18:06:25.829555: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1080] Converting unsupported operation: Enter\n2019-09-18 18:06:25.829566: I tensorflow/contrib/lite/toco/import_tensorflow.cc:189] Unsupported data type in placeholder op: 20\n2019-09-18 18:06:25.829576: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1080] Converting unsupported operation: TensorArrayWriteV3\n2019-09-18 18:06:25.829590: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1127] Op node missing output type attribute: rnn/while/TensorArrayWrite/TensorArrayWriteV3\n2019-09-18 18:06:25.829611: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1080] Converting unsupported operation: Exit\n2019-09-18 18:06:25.829630: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1080] Converting unsupported operation: TensorArraySizeV3\n2019-09-18 18:06:25.829647: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1127] Op node missing output type attribute: rnn/TensorArrayStack/TensorArraySizeV3\n2019-09-18 18:06:25.829667: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1080] Converting unsupported operation: TensorArrayGatherV3\n2019-09-18 18:06:25.830001: F tensorflow/contrib/lite/toco/tooling_util.cc:1382] Check failed: batch == 1 (2 vs. 1)\nAborted\n'`


any one has this problem ?

**Comment by liyunlu0618** [comment]
We're in the process of deprecating the old quantization rewriter. Our new keras based quantization-aware training API is on the way and welcome to try it out when it's released!

Meanwhile, you can look into post-training integer quantization to quantize your model:
https://medium.com/tensorflow/tensorflow-model-optimization-toolkit-post-training-integer-quantization-b4964a1ea9ba

Feel free to open separate issues when you run into problem with that. Thanks!
