### ISSUE TITLE
Use of fit_generator and evaluate_generator result in "builtins.TypeError: 'NoneType' object is not subscriptable"

### ISSUE THREAD

**Issue by isaacgerg** [tensorflow/tensorflow#32618]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
https://colab.research.google.com/gist/isaacgerg/03717f55f020f36aa7b5138fc04cfc43/tf-keras-generator-issue.ipynb

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
Windows 7, Python 3.7, tensorflow 1.13.1

- TensorFlow installed from (source or binary):
via pip

- TensorFlow version (use command below): 1.13,1

- Python version: 3.7
- CUDA/cuDNN version: 10
- GPU model and memory: RTX

**Describe the current behavior**
```
The code in the colab, when run on a GPU, results in teh following error:
File "c:\python37\Lib\threading.py", line 885, in _bootstrap
  self._bootstrap_inner()
File "c:\python37\Lib\threading.py", line 917, in _bootstrap_inner
  self.run()
File "c:\python37\Lib\threading.py", line 865, in run
  self._target(*self._args, **self._kwargs)
File "c:\python37\Lib\multiprocessing\pool.py", line 121, in worker
  result = (True, func(*args, **kwds))
File "c:\python37\Lib\site-packages\tensorflow\python\keras\utils\data_utils.py", line 445, in get_index
  return _SHARED_SEQUENCES[uid][i]

builtins.TypeError: 'NoneType' object is not subscriptable
```

**Describe the expected behavior**
No error

**Code to reproduce the issue**
See colab link in description.  This is the offending code.  It only appears to happen on windows.  I am unsure in colab how to select a windows based environment.

EDIT 1: Added windows caveat.

**Comment by gadagashwini** [comment]
I tried on colab it kept running for long time. Please see the colab [gist](https://colab.sandbox.google.com/gist/gadagashwini/a3a781843e4182513151e73121d0d307/tf-keras-generator-issue.ipynb). Thanks!

**Comment by isaacgerg** [comment]
@gadagashwini Same happened for me.  Please run it in windows, the error occurs after the first loop.

**Comment by jvishnuvardhan** [comment]
@isaacgerg This is a big model with almost ~2 million parameters to optimize, 62 steps per training epoch and 9999 total epochs. I reduced number of epochs and the code is running without any error but loss was `nan`.

I would suggested run for couple of 1 or 2 iterations on GPU, then save weights and make the model as `trainable = False` , then work on the code. There might be some coding issue which is why it is showing loss as `nan`.

Another things to consider here is installing TF1.15 which was running faster than 1.13. There were lots of performance improvements over the time so I would suggest to use `TF1.15.

I am closing the issue here. Please feel free to open a new issue if you notice any issue with TF. Thanks!

**Comment by isaacgerg** [comment]
@jvishnuvardhan Can you reopen this?  The code producing the error is on colab but it happens in the windows enviroment.  You have to change your colab environment to run under winows (is that even possible?)  

The Nan's arent the issue and are expected as I trimmed down my code to the minimal form to reporduce the error.  The problem is when you run in windows, i get the following error:

```
File "c:\python37\Lib\threading.py", line 885, in _bootstrap
  self._bootstrap_inner()
File "c:\python37\Lib\threading.py", line 917, in _bootstrap_inner
  self.run()
File "c:\python37\Lib\threading.py", line 865, in run
  self._target(*self._args, **self._kwargs)
File "c:\python37\Lib\multiprocessing\pool.py", line 121, in worker
  result = (True, func(*args, **kwds))
File "c:\python37\Lib\site-packages\tensorflow\python\keras\utils\data_utils.py", line 445, in get_index
  return _SHARED_SEQUENCES[uid][i]

builtins.TypeError: 'NoneType' object is not subscriptable
```

**Comment by jvishnuvardhan** [comment]
@isaacgerg As mentioned in another issue of your's, this code also running in Windows10 without any issue. 
https://github.com/tensorflow/tensorflow/issues/32697#issuecomment-655193838


Please close the issue if this was resolved for you. Thanks!

**Comment by isaacgerg** [comment]
Adding the argument workers=0 to model.eval() and model.fit() fixed this issue.
