### ISSUE TITLE
Use tf.Tensor as input to tf.io.gfile.GFile

### ISSUE THREAD

**Issue by remydubois** [tensorflow/tensorflow#32620]
**System information**
- TensorFlow version (you are using): 2.0.0rc1

**Describe the feature and the current behavior/state.**
Currently, file readers such as `tf.io.gfile.GFile` expect plain strings as input. As a consequence, one can hardly use those file readers inside `tf.data.Dataset` pipelines which yield string Tensors (typically through `tf.data.Dataset.list_files`)

Doing so raises `TypeError: Expected binary or unicode string, got <tf.Tensor 'EagerPyFunc:0' shape=<unknown> dtype=string>`, at the line `compat.as_bytes(self.__name)` (tensorflow_core/python/lib/io/file_io.py:84).

**Will this change the current api? How?**
From a user point of view, the current API would not see any significant changes.

**Who will benefit with this feature?**
Any one eager to read custom file formats, where it is for instance needed to decode part of the header file (first few bytes) to decode the actual content. For instance, image formats such as TIFF where the dtype and the image shape are encoded inside the header.

Below pipelines would then be easier to build:
```
files = tf.data.Dataset.list_files('/**/regex*')
tensors = files.map(MyCustomReader)
```

**Any Other info.**
See below an example of such custom format file reader:

```
import tensorflow as tf

@tf.function
def CustomReader(path):
    # path must here a string in the current API
    with tf.io.gfile.GFile(name=path, mode='rb') as f:
        
        # Shape information is encoded  on 16 bytes starting at position 40
        f.seek(40)
        shape = tf.io.decode_raw(f.read(16), out_type=tf.int16)
        shape = tf.cast(shape, tf.int32)
       
        # dtype information is encoded on 2 bytes at position 70
        f.seek(70)
        dtype = tf.io.decode_raw(f.read(2), out_type=tf.int16)[0]

        # tensor values populate the  rest of the buffer
        values = tf.io.decode_raw(f.read(-1), out_type=dtype)
        tensor = tf.reshape(values, shape)

        return tensor
```

**Comment by mihaimaruseac** [comment]
This likely is related to #33563

**Comment by noahtren** [comment]
Inasmuch as this is an issue, it also exists for the methods of the `tf.io.gfile.GFile` class. For example, I cannot pass a `tf.Tensor` as `offset` for `f.seek(offset)`. Supporting tensors here would make it easier to integrate into `tf.data`.

**Comment by angeligareta** [comment]
Actually, now you can simply use tf.io.read_file() with a gs file and it would be able to read it even from a tensor. 😄

**Comment by rmothukuru** [comment]
@remydubois,
Can you please let us know if [this comment](https://github.com/tensorflow/tensorflow/issues/32620#issuecomment-811044008) helped you to resolve this issue, so that we can close it? Thanks!

**Comment by mhorlacher** [comment]
This is still an issue. To be honest, it baffles me that there is current no (obvious) way to random-access bytes from a file on the disk. There are countless of datasets that exist as indexed binary files. 

E.g., is there any way to do something like this (pseudo-code-ish):

```
class GFileTFRecord:
    def __init__(self, filepath):
        self._gfile_tfrecord = tf.io.gfile.GFile(filepath, 'rb')
    
    def read_proto(self, offset, length):
        self._gfile_tfrecord.seek(offset)
        return self._gfile_tfrecord.read(length)

gfile_tfrecord = GFileTFRecord('file.tfrecord')

dataset = dataset_from_index('file.tfrecord.idx')
dataset = dataset.map(lambda offset, length: gfile_tfrecord.read_proto(offset, length))
dataset = dataset.map(...) # <-- e.g. decode proto
```

@angeligareta's suggestion doesn't apply - it reads the whole file's content into memory. 

@rmothukuru Do you have a suggestion?
