### ISSUE TITLE
tflite_runtime supports for arm (pi3 model b+)

### ISSUE THREAD

**Issue by Namburger** [tensorflow/tensorflow#32629]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
Linuz rpi 4.19.66-v7+ #1253 SMP Thu Ag 15 11:49:46 BST 2019 arm71 GNU/Linux
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: n/a
- TensorFlow installed from (source or binary):
I installed tflite_runtime via 
pip3 install tflite_runtime-1.15.0rc0-cp35-cp35m-linux_armv7l.whl package
- TensorFlow version:
1.15.0
- Python version:
3.5.3
- Installed using virtualenv? pip? conda?: pip
- Bazel version (if compiling from source): n/a
- GCC/Compiler version (if compiling from source): n/a
- CUDA/cuDNN version: n/a
- GPU model and memory: n/a

**Describe the problem**
$ pip3 install tflite_runtime-1.15.0rc0-cp35-cp35m-linux_armv7l.whl
in my script, I have:

from tflite_runtime.interpreter import Interpreter
from tflite_runtime.interpreter import load_delegate
// more codes here
file_name = 'my_model.tflite'
interpreter = Interpreter(file_name, experimental_delegates=[load_delegate('libedgetpu.so.1.0')])

Running the script:
$ python3 script.py
...
OSError: /usr/bin/arm-linux-gnueabihf/libc++abi.so.1: undefined symbol: _Unwind_SetIP
Exception ignored in: <bound method Delegate.__del__ of <tflite_runtime.interpreter..Delegate object at 0x769be550>>
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.5/site-packages/tflite_runtime/iterpreter.py", line 124, in __del__
    if self.__library is not None:
AttributeError: 'Delegate' object has no attribute '_library'

Keep in mind that I've been able to run the same exact code on my x86_64 Ubunbu 18.10 host machine, downloading the package from here:
https://www.tensorflow.org/lite/guide/python#install_just_the_interpreter
and ran pip install on the package.whl

**Comment by Namburger** [comment]
Hi guys - any updates on this? 
This issue isn't for me, personally but I know some people are waiting to get load_delegate working on their pi. Thanks!

**Comment by besherh** [comment]
I have the same exact issue!

**Comment by andcarnivorous** [comment]
Same issue here

**Comment by besherh** [comment]
@andcarnivorous 
I have already tried it on Raspberry Pi 3, Stretch Lite, Edgetpu 2.11.1, but not worked for me.

**Comment by Namburger** [comment]
@andcarnivorous are you using the edgetpu api or the tflite_runtime api?
I have not been able to use the tflite_runtime api at all on the pi3 b+

**Comment by andcarnivorous** [comment]
> @andcarnivorous are you using the edgetpu api or the tflite_runtime api?
> I have not been able to use the tflite_runtime api at all on the pi3 b+
@Namburger Oops, I was running the edgetpu api, tflite_runtime is still not working even on the images.

**Comment by batulrangwala** [comment]
Hi
I am using a Google Coral Mini PCIe on Banana PI 64 and have a similiar issue
My linux distribution is
Linux bpi-iot-ros-ai 5.4.0-bpi-r64 #1 SMP PREEMPT Mon Dec 16 16:00:08 IST 2019 aarch64 aarch64 aarch64 GNU/Linux
TensorFlow installed
tflite_runtime-1.14.0-cp35-cp35m-linux_aarch64.whl
Python3 Version : 3.5.2

I have loaded the libedgetpu as per the instructions here https://coral.ai/news/updates-04-2019/.
I am running the Demo model https://coral.ai/docs/m2/get-started/#4-run-a-model-using-the-tensorflow-lite-api which gives me the following error


```
Traceback (most recent call last):
  File "classify_image.py", line 122, in <module>
    main()
  File "classify_image.py", line 98, in main
    interpreter = make_interpreter(args.model)
  File "classify_image.py", line 71, in make_interpreter
    {'device': device[0]} if device else {})
  File "/usr/local/lib/python3.5/dist-packages/tflite_runtime/interpreter.py", line 165, in load_delegate
    delegate = Delegate(library, options)
  File "/usr/local/lib/python3.5/dist-packages/tflite_runtime/interpreter.py", line 89, in __init__
    self._library = ctypes.pydll.LoadLibrary(library)
  File "/usr/lib/python3.5/ctypes/__init__.py", line 425, in LoadLibrary
    return self._dlltype(name)
  File "/usr/lib/python3.5/ctypes/__init__.py", line 347, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /usr/lib/aarch64-linux-gnu/libc++abi.so.1: undefined symbol: _Unwind_GetRegionStart
Exception ignored in: <bound method Delegate.__del__ of <tflite_runtime.interpreter.Delegate object at 0x7f99af6550>>
Traceback (most rent call last):
  File "/usr/local/lib/python3.5/dist-packages/tflite_runtime/interpreter.py", line 124, in __del__
    if self._library is not None:
AttributeError: 'Delegate' object has no attribute '_library'
```

I have updated the g++ and gcc to version 6 and installed libunwind8. but the same error is still present.

**Comment by amitdingareNovelis** [comment]
same here. My setup: Raspberry pi 4, Raspbian,  tflite_runtime-1.14.0-cp37-cp37m-linux_armv7l.whl for tflite and Google Coral.

Any leads will be appreciated.

**Comment by besherh** [comment]
I managed to install tf2 from here (
https://github.com/PINTO0309/Tensorflow-bin  ), and it's working :)
*            Best Regards*

**Comment by matiasSaavedra** [comment]
Same problem on a rpi 3B+, buster raspbian, running on this docker (python 3.5.3) https://hub.docker.com/r/sgtwilko/rpi-raspbian-opencv, with tflite_runtime-1.14.0-cp35-cp35m-linux_armv7l.whl

**Comment by matiasSaavedra** [comment]
> Same problem on a rpi 3B+, buster raspbian, running on this docker (python 3.5.3) https://hub.docker.com/r/sgtwilko/rpi-raspbian-opencv, with tflite_runtime-1.14.0-cp35-cp35m-linux_armv7l.whl

Solved it using: 
apt-get install apt-transport-https
apt-get install usbutils (check if you detect Google Inc. with lsusb)
apt-get update
apt-get install curl
echo "deb https://packages.cloud.google.com/apt coral-edgetpu-stable main" | tee /etc/apt/sources.list.d/coral-edgetpu.list
curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add -
apt-get update
apt-get install libedgetpu1-std

**Comment by Namburger** [comment]
Hey guys, sorry for not checking this sooner...
Updating the `tflite_runtime` package from [here](https://www.tensorflow.org/lite/guide/python) fixed it. 
The current package is `tflite_runtime-2.1.0-cp37-cp37m*.whl`, my rpi run consistently with no issues.
