### ISSUE TITLE
Inference in C++ Tensorflow: Session->Run hangs when ran with input and output parameters supplied

### ISSUE THREAD

**Issue by amitpandey2194** [tensorflow/tensorflow#32624]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 18.04):
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): Source C++ API
- TensorFlow version (use command below):1.12.0
- Python version:3.6.7
- Bazel version (if compiling from source):0.18.1
- GCC/Compiler version (if compiling from source):7.4.0
- CUDA/cuDNN version:
- GPU model and memory:

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
I trained a FasterRCNN for point detection using TensorFlow and its python API. I was able to do the inference successfully in the same without any issues.
Now for production requirements, I need to build a standalone application or library which can perform the inference in C++.

In order to achieve that I successfully managed to build the TensorFlow library from scratch for C++ API and ran a few test programs.

Steps followed for inference on my trained model:

 1. Method #1: freeze the graph to *.pb file using modified [freeze_graph.py][1] and restore it.
 2. Method #2: Directly restore from checkpoint using MetaGraphDef and ReadBinaryProto.

I tried both the methods and the loading of the model seems to happen without any error. I printed the node names as well.

After loading the graph I created a handler for image input, previously the input during training was getting handled by QueueRunner, but because it's just inference I created the handler myself with appropriate modifications to it as can be seen below.

        Status fasterRcnn::CreateGraphForImage(bool unstack)
    {
        fileNameVar=Placeholder(iRoot.WithOpName("input"),DT_STRING);
        auto fileReader=ReadFile(iRoot.WithOpName("fileReader"),fileNameVar);
        auto imageReader=DecodeJpeg(iRoot.WithOpName("jpegReader"),fileReader,DecodeJpeg::Channels(imageChannels));
        auto floatCaster=Cast(iRoot.WithOpName("floatCaster"),imageReader,DT_FLOAT);
        auto dimsExpander=ExpandDims(iRoot.WithOpName("dim"),floatCaster,0);
        //auto resized=ResizeBilinear(iRoot.WithOpName("size"),dimsExpander,Const(iRoot,{imageSide,imageSide}));
        //auto div=Div(iRoot.WithOpName("normalized"),resized,{255.f});
        imageTensorVar=dimsExpander;//div;
        return iRoot.status();

    }
NOTE: iRoot is the private variable of fasterRcnn class-> Scope used by the graph for loading images into tensors

 

       class fasterRcnn
    {
    private:
        Scope iRoot;//graph for loading images into tensors
        const int imageSide;
        const int imageChannels;//rgb
        //load image vars
        Output fileNameVar;
        Output imageTensorVar;
        //
        std::unique_ptr<Session> fSession;//file session
        std::unique_ptr<GraphDef> graphDef;
    public:
        fasterRcnn(int side,int channels):iRoot(Scope::NewRootScope()),imageSide(side),imageChannels(channels){}
        Status CreateGraphForImage(bool unstack);
        Status LoadSavedModel(string &fileName);//via frozen graph
        Status LoadSavedModel(std::string graph_fn,std::string checkpoint_fn);//via checkpoints
        Status PredictFromFrozen(Tensor &image,int&results);//
        Status ReadTensorFromImageFile(string& file_name, Tensor& outTensor);
        Status ReadFileTensors(string& folder_name,vector<Tensor>& file_tensors);
    
    };

**Now the when the time comes for Prediction when I run Session->Run with particular input node name and output node name the program hangs**:

    Status fasterRcnn::PredictFromFrozen(Tensor& image, int& result)
    {
        vector<Tensor> outTensors;
        cout<<"Prediction about to start"<<endl;
        TF_CHECK_OK(fSession->Run({{"fasterrcnn/truncated_base_network/sub",image}},{"fasterrcnn/rcnn/rcnn_proposal/GatherV2_1"},{},&outTensors));
        cout<<"Prediction done"<<endl;
        auto output_c = outTensors[0].scalar<float>();
        for (int i=0;i<outTensors.size();i++)
        {
            cout << "Output dimension of the image" << outTensors[i].DebugString()<<"\n";
        }
        cout << "Output dimension of the image" << outTensors[0].DebugString()<<"\n";
        return Status::OK();
    }

**TF_CHECK_OK(fSession->Run({{"fasterrcnn/truncated_base_network/sub",image}},{"fasterrcnn/rcnn/rcnn_proposal/GatherV2_1"},{},&outTensors));**

***It hangs at the above statement.***

**Up until a few Debug thoughts:**

 1. I thought maybe the QueueRunner might be creating the issue, but according to [this answer][2] I handled that as I created the image handler graph.
 2. I thought maybe I didn't freeze the graph well, that's I loaded directly from the checkpoints, but still, it hangs.
 3. The input to the VGG_16 truncated network in graph expects a 4D float tensor, which I am providing, double-checked that.

**Links to Code and Graph:**

 1. [CodeBase and GraphPng and GIF hosted on GDrive][3]

**Question:**

 1. Is there any step that I missing, for successful inferencing in C++.
 2. How to verify if my input and output node names are correct? I referred to the python code and they seem right.
 3. Any steps for debugging that I should follow to provide more info on this?

  [1]: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/tools/freeze_graph.py
  [2]: https://stackoverflow.com/a/35346656/8250471
  [3]: https://drive.google.com/drive/folders/1iO7JIitD_BfHnnLqgzvUygFwAAW6v_5G?usp=sharing

**Describe the expected behavior**

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by oanush** [comment]
@amitpandey2194 ,
Thanks for reporting the issue, can you please provide a standalone code so that we can replicate the  same from our end ?Thanks!

**Comment by amitpandey2194** [comment]
predicting.h #headerfile
```
#include <iostream>
#include <map>
#include <string>
#include <fstream>
#include "tensorflow/cc/client/client_session.h"
#include "tensorflow/cc/ops/standard_ops.h"
#include "tensorflow/cc/framework/gradients.h"
#include "tensorflow/core/framework/tensor.h"
#include "tensorflow/core/public/session.h"
#include "tensorflow/core/lib/io/path.h"
#include "tensorflow/contrib/tensorboard/db/summary_file_writer.h"
#include "tensorflow/cc/tools/freeze_saved_model.h"
#include "tensorflow/cc/ops/image_ops.h"
#include <tensorflow/core/protobuf/meta_graph.pb.h>
using namespace std;
using namespace tensorflow;
using namespace tensorflow::ops;

class fasterRcnn
{
private:
    Scope iRoot;//graph for loading images into tensors
    const int imageSide;
    const int imageChannels;//rgb
    //load image vars
    Output fileNameVar;
    Output imageTensorVar;
    //
    std::unique_ptr<Session> fSession;//file session
    std::unique_ptr<GraphDef> graphDef;
public:
    fasterRcnn(int side,int channels):iRoot(Scope::NewRootScope()),imageSide(side),imageChannels(channels){}
    Status CreateGraphForImage(bool unstack);
    Status LoadSavedModel(string &fileName);//via frozen graph
    Status LoadSavedModel(std::string graph_fn,std::string checkpoint_fn);//via checkpoints
    Status PredictFromFrozen(Tensor &image,int&results);//
    Status ReadTensorFromImageFile(string& file_name, Tensor& outTensor);
    Status ReadFileTensors(string& folder_name,vector<Tensor>& file_tensors);

};

```
#predicting.cpp #definition file
```
#include "predicting.h"
typedef std::vector<std::pair<std::string, tensorflow::Tensor>> tensor_dict;
Status fasterRcnn::CreateGraphForImage(bool unstack)
{
    fileNameVar=Placeholder(iRoot.WithOpName("input"),DT_STRING);
    auto fileReader=ReadFile(iRoot.WithOpName("fileReader"),fileNameVar);
    auto imageReader=DecodeJpeg(iRoot.WithOpName("jpegReader"),fileReader,DecodeJpeg::Channels(imageChannels));
    auto floatCaster=Cast(iRoot.WithOpName("floatCaster"),imageReader,DT_FLOAT);
    auto dimsExpander=ExpandDims(iRoot.WithOpName("dim"),floatCaster,0);
    //auto resized=ResizeBilinear(iRoot.WithOpName("size"),dimsExpander,Const(iRoot,{imageSide,imageSide}));
    //auto div=Div(iRoot.WithOpName("normalized"),resized,{255.f});
    imageTensorVar=dimsExpander;//div;
    return iRoot.status();
}
Status fasterRcnn::LoadSavedModel(string& fileName)
{

    SessionOptions options;
    fSession.reset(NewSession(options));
    graphDef.reset(new GraphDef);
    TF_CHECK_OK(ReadBinaryProto(Env::Default(),fileName,graphDef.get()));
    return fSession->Create(*graphDef.get());
}
Status fasterRcnn::LoadSavedModel(std::string graph_fn,std::string checkpoint_fn)
{
  tensorflow::Status status;
  SessionOptions options;
  fSession.reset(NewSession(options));
     // Read in the protobuf graph we exported
  tensorflow::MetaGraphDef graph_def;
  status = ReadBinaryProto(tensorflow::Env::Default(), graph_fn, &graph_def);
  if (status != tensorflow::Status::OK()) return status;

  // create the graph in the current session
  status = fSession->Create(graph_def.graph_def());
  if (status != tensorflow::Status::OK()) return status;

  // restore model from checkpoint, iff checkpoint is given
  if (checkpoint_fn != "") {
    const std::string restore_op_name = graph_def.saver_def().restore_op_name();
    const std::string filename_tensor_name =
        graph_def.saver_def().filename_tensor_name();

    tensorflow::Tensor filename_tensor(tensorflow::DT_STRING,
                                       tensorflow::TensorShape());
    filename_tensor.scalar<std::string>()() = checkpoint_fn;

    tensor_dict feed_dict = {{filename_tensor_name, filename_tensor}};
    status = fSession->Run(feed_dict, {}, {restore_op_name}, nullptr);
    if (status != tensorflow::Status::OK()) return status;
  } else {
    // virtual Status Run(const std::vector<std::pair<string, Tensor> >& inputs,
    //                  const std::vector<string>& output_tensor_names,
    //                  const std::vector<string>& target_node_names,
    //                  std::vector<Tensor>* outputs) = 0;
    status = fSession->Run({}, {}, {"init"}, nullptr);
    if (status != tensorflow::Status::OK()) return status;
  }

  return tensorflow::Status::OK();
}
Status fasterRcnn::PredictFromFrozen(Tensor& image, int& result)
{
    //auto inputlayer = graphDef->node(0).name();
    //auto outputlayer = graphDef->node(graphDef->node_size()-2).name();
    //cout<<inputlayer<<endl;
    //cout<<outputlayer<<endl;
    //get the appropriate input and out layer names from the graph/mode to execute
    vector<Tensor> outTensors;
    cout<<"Prediction about to start"<<endl;
    TF_CHECK_OK(fSession->Run({{"fasterrcnn/truncated_base_network/sub",image}},{"fasterrcnn/rcnn/rcnn_proposal/GatherV2_1"},{},&outTensors));
    cout<<"Prediction done"<<endl;
    auto output_c = outTensors[0].scalar<float>();
    for (int i=0;i<outTensors.size();i++)
    {
        cout << "Output dimension of the image" << outTensors[i].DebugString()<<"\n";
    }
    cout << "Output dimension of the image" << outTensors[0].DebugString()<<"\n";
    return Status::OK();
}
Status fasterRcnn::ReadTensorFromImageFile(string& file_name, Tensor& outTensor)
{
    if(!iRoot.ok())
        return iRoot.status();
    if (!str_util::EndsWith(file_name, ".jpg") && !str_util::EndsWith(file_name, ".jpeg"))
    {
        return errors::InvalidArgument("Image must be jpeg encoded");
    }
    vector<Tensor> out_tensors;
    ClientSession session(iRoot);
    cout<<"About to do Session.Run"<<endl;
    TF_CHECK_OK(session.Run({{fileNameVar, file_name}}, {imageTensorVar}, &out_tensors));

    outTensor = out_tensors[0]; // shallow copy
    cout<<"done Session.Run"<<endl;
    return Status::OK();
}
Status fasterRcnn::ReadFileTensors(string& base_folder_name,vector<Tensor>& file_tensors)
{
    //validate the folder
    Env* penv = Env::Default();//from tensorflow
    TF_RETURN_IF_ERROR(penv->IsDirectory(base_folder_name));
    //get the files
    bool b_shuffle = false;

    string folder_name = io::JoinPath(base_folder_name, "");
    TF_RETURN_IF_ERROR(penv->IsDirectory(folder_name));
    vector<string> file_names;
    TF_RETURN_IF_ERROR(penv->GetChildren(folder_name, &file_names));
    for(string file: file_names)
    {
        string full_path = io::JoinPath(folder_name, file);
        Tensor i_tensor;
        cout<<full_path<<endl;
        TF_RETURN_IF_ERROR(ReadTensorFromImageFile(full_path, i_tensor));
        size_t s = file_tensors.size();
        if(b_shuffle)
        {
            //suffle the images
            int i = rand() % s;
            file_tensors.emplace(file_tensors.begin()+i, i_tensor);
        }
        else
            file_tensors.push_back(i_tensor);
    }
    b_shuffle = true;
    return Status::OK();
}

```

#main.cpp 
```
#include "predicting.h"
#include <chrono>
#include <iomanip>
using namespace std;
using namespace chrono;
using namespace tensorflow;
using namespace tensorflow::ops;
int main(int argc,const char*argv[])
{
    int imageSide=512;
    int imageChannels=3;
    fasterRcnn model(imageSide,imageChannels);
    Status s;
    string protoName="frozen/frozen_model.pb";
    const std::string graph_fn = "model/model.ckpt-14260114.meta";
    const std::string checkpoint_fn = "model/model.ckpt-14260114";
    s=model.LoadSavedModel(graph_fn,checkpoint_fn);
    TF_CHECK_OK(s);
    s = model.CreateGraphForImage(false);//rebuild the image loading model without unstacking
    TF_CHECK_OK(s);
    string base_folder = "data";
    vector<Tensor> all_files_tensors;
    s = model.ReadFileTensors(base_folder, all_files_tensors);
    TF_CHECK_OK(s);
    int result;
    s=model.PredictFromFrozen(all_files_tensors[0],result);
    TF_CHECK_OK(s);
    cout<<"All Good"<<endl;
}
```
Links to Code and Graph:

[CodeBase and GraphPng and GIF hosted on GDrive
](https://drive.google.com/drive/folders/1iO7JIitD_BfHnnLqgzvUygFwAAW6v_5G)



Thanks @oanush for responding to this. Let me know if you need anything else. The graph on the drive would show you appropriate inputs and outputs.

Note: In my python code I was using QueueRunners for training, but for inference, I was not using it.
Similarly, on the C++ side, I managed my own input pipeline without using the QueueRunner, as mentioned in this answer by @mrry [answer](https://stackoverflow.com/q/35346117/8250471)

**Comment by amitpandey2194** [comment]
Hey, @jvishnuvardhan or @ezhulenev any update or suggestions on this?

**Comment by fisakhan** [comment]
Don't call PredictFromFrozen(). Instead replace s=model.PredictFromFrozen(all_files_tensors[0],result); by contents of PredictFromFrozen() into main.cpp.

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.
