### ISSUE TITLE
IOS Makefile Problem

### ISSUE THREAD

**Issue by rajisme** [tensorflow/tensorflow#3262]
I followed the steps given in https://github.com/tensorflow/tensorflow/tree/master/tensorflow/contrib/makefile but ran into problems when running the command  make -f tensorflow/contrib/makefile/Makefile  TARGET=IOS  IOS_ARCH=ARM64. 
### Environment info

Operating System:
MacBook Pro (Retina, 13-inch, Mid 2014), 10.11.5 El Capitan
Xcode 7.3.1 

[make_file_errors.txt](https://github.com/tensorflow/tensorflow/files/356308/make_file_errors.txt)
### Steps to reproduce
1.  make -f tensorflow/contrib/makefile/Makefile  TARGET=IOS  IOS_ARCH=ARM64 (in the root tensorflow directory)
### What have you tried?
1. Recloning and following steps in https://github.com/tensorflow/tensorflow/tree/master/tensorflow/contrib/makefile  again  
2. Trying to resolve using Stackoverflow  
### Logs or other output that would be helpful

Attaced below 
Thank You!

**Comment by raj4** [comment]
The error message:
[make_file_errors.txt](https://github.com/tensorflow/tensorflow/files/356312/make_file_errors.txt)

**Comment by jmchen-g** [comment]
@petewarden Could you take a look at this please?

**Comment by petewarden** [comment]
Can you try this again using the new tensorflow/contrib/makefile/build_all_ios.sh script? I believe this should now fix this issue.

**Comment by gunan** [comment]
Closing the issue, as there seems to be a resolution now.
Please reopen if you still run into it.
