### ISSUE TITLE
add new variables to a pretrain model in keras

### ISSUE THREAD

**Issue by Womcos-Shu** [tensorflow/tensorflow#32628]
I encounter some problems when using keras. I get a network which has been pretrained, such as vgg16 or resnet34. The network use the keras default naming for all variables. Now i want to change some layers of the network which will change the variables of current layers. But when i directly change the layers, the name of variables in other layers change, too. Then i can not load the variables from the pretrained model. Can anyone tell me how to solve the problem.

**Comment by gowthamkpr** [comment]
@Womcos-Shu Please take a look at this [issue](https://github.com/keras-team/keras/issues/3465) which should be able to answer your questions and let me know if it helps. Thanks!

**Comment by gowthamkpr** [comment]
Closing this issue as it has been inactive for more than 5 days. Please add additional comments and we can open the issue again.
