### ISSUE TITLE
No such file or directory in bazel build

### ISSUE THREAD

**Issue by ucasiggcas** [tensorflow/tensorflow#32637]
- OS Platform and Distribution ( Linux Ubuntu 18.04, python3.5):
- TensorFlow installed from (tensorflow-master,that is, I download the https://github.com/tensorflow/tensorflow)
- TensorFlow version (source,I don't know, this is the link https://github.com/tensorflow/tensorflow):

`tensorflow-master$ bazel build tensorflow/lite/toco:toco`
`Starting local Bazel server and connecting to it...
FATAL: Cannot get start time of process 0: (error: 2): No such file or directory`

So what's wrong ??
thx

**Comment by ucasiggcas** [comment]
in another platform and same OS,
same `tensorflow-master$ bazel build tensorflow/lite/toco:toco`
but ups
`INFO: Options provided by the client:
  Inherited 'common' options: --isatty=1 --terminal_columns=107
INFO: Reading rc options for 'build' from /./tensorflow-master/.bazelrc:
  'build' options: --apple_platform_type=macos --define framework_shared_object=true --define open_source_build=true --define=use_fast_cpp_protos=true --define=allow_oversize_protos=true --spawn_strategy=standalone --strategy=Genrule=standalone -c opt --cxxopt=-std=c++14 --host_cxxopt=-std=c++14 --announce_rc --define=grpc_no_ares=true --define=PREFIX=/usr --define=LIBDIR=$(PREFIX)/lib --define=INCLUDEDIR=$(PREFIX)/include
WARNING: Download from https://storage.googleapis.com/mirror.tensorflow.org/github.com/bazelbuild/bazel-toolchains/archive/92dd8a7a518a2fb7ba992d47c8b38299fe0be825.tar.gz failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException GET returned 404 Not Found
DEBUG: Rule 'io_bazel_rules_docker' indicated that a canonical reproducible form can be obtained by modifying arguments shallow_since = "1556410077 -0400"
DEBUG: Call stack for the definition of repository 'io_bazel_rules_docker' which is a git_repository (rule definition at /home/./.cache/bazel/_bazel_xulm1/b172144b72497b6793e5891257276c30/external/bazel_tools/tools/build_defs/repo/git.bzl:195:18):
 - /home/./.cache/bazel/_bazel_xulm1/b172144b72497b6793e5891257276c30/external/bazel_toolchains/repositories/repositories.bzl:37:9
 - /./tensorflow-master/WORKSPACE:35:1
WARNING: Download from https://storage.googleapis.com/mirror.tensorflow.org/github.com/protocolbuffers/protobuf/archive/310ba5ee72661c081129eb878c1bbcec936b20f0.tar.gz failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException GET returned 404 Not Found
Traceback (most recent call last):
  File "/home/./.cache/bazel/_bazel_xulm1/b172144b72497b6793e5891257276c30/external/org_tensorflow/tensorflow/tools/git/gen_git_source.py", line 29, in <module>
    from builtins import bytes  # pylint: disable=redefined-builtin
ImportError: No module named builtins
INFO: Call stack for the definition of repository 'local_config_git' which is a git_configure (rule definition at /data/rnnoise/src/data/mss/pb2tflite/tensorflow-master/third_party/git/git_configure.bzl:63:17):
 - /./tensorflow-master/tensorflow/workspace.bzl:74:5
 - /./tensorflow-master/WORKSPACE:19:1
ERROR: An error occurred during the fetch of repository 'local_config_git':
   Traceback (most recent call last):
	File "/./tensorflow-master/third_party/git/git_configure.bzl", line 61
		_fail(result.stderr)
	File "/./tensorflow-master/third_party/git/git_configure.bzl", line 14, in _fail
		fail(("%sGit Configuration Error:%s %...)))
Git Configuration Error: Traceback (most recent call last):
  File "/home/./.cache/bazel/_bazel_xulm1/b172144b72497b6793e5891257276c30/external/org_tensorflow/tensorflow/tools/git/gen_git_source.py", line 29, in <module>
    from builtins import bytes  # pylint: disable=redefined-builtin
ImportError: No module named builtins

INFO: Call stack for the definition of repository 'gemmlowp' which is a tf_http_archive (rule definition at /./tensorflow-master/third_party/repo.bzl:121:19):
 - /./tensorflow-master/tensorflow/workspace.bzl:239:5
 - /./tensorflow-master/WORKSPACE:19:1
INFO: Repository 'gemmlowp' used the following cache hits instead of downloading the corresponding file.
 * Hash '6678b484d929f2d0d3229d8ac4e3b815a950c86bb9f17851471d143f6d4f7834' for https://storage.googleapis.com/mirror.tensorflow.org/github.com/google/gemmlowp/archive/12fed0cd7cfcd9e169bf1925bc3a7a58725fdcc3.zip
If the definition of 'gemmlowp' was updated, verify that the hashes were also updated.
INFO: Call stack for the definition of repository 'fft2d' which is a tf_http_archive (rule definition at /./tensorflow-master/third_party/repo.bzl:121:19):
 - /./tensorflow-master/tensorflow/workspace.bzl:605:5
 - /./tensorflow-master/WORKSPACE:19:1
INFO: Call stack for the definition of repository 'zlib_archive' which is a tf_http_archive (rule definition at /./tensorflow-master/third_party/repo.bzl:121:19):
 - /./tensorflow-master/tensorflow/workspace.bzl:593:5
 - /./tensorflow-master/WORKSPACE:19:1
ERROR: /./tensorflow-master/tensorflow/core/BUILD:2741:1: //tensorflow/core:version_info_gen depends on @local_config_git//:gen/spec.json in repository @local_config_git which failed to fetch. no such package '@local_config_git//': Traceback (most recent call last):
	File "/./tensorflow-master/third_party/git/git_configure.bzl", line 61
		_fail(result.stderr)
	File "/./tensorflow-master/third_party/git/git_configure.bzl", line 14, in _fail
		fail(("%sGit Configuration Error:%s %...)))
Git Configuration Error: Traceback (most recent call last):
  File "/home/./.cache/bazel/_bazel_xulm1/b172144b72497b6793e5891257276c30/external/org_tensorflow/tensorflow/tools/git/gen_git_source.py", line 29, in <module>
    from builtins import bytes  # pylint: disable=redefined-builtin
ImportError: No module named builtins

ERROR: /./tensorflow-master/tensorflow/core/BUILD:2741:1: //tensorflow/core:version_info_gen depends on @local_config_git//:gen/head in repository @local_config_git which failed to fetch. no such package '@local_config_git//': Traceback (most recent call last):
	File "/./tensorflow-master/third_party/git/git_configure.bzl", line 61
		_fail(result.stderr)
	File "/./tensorflow-master/third_party/git/git_configure.bzl", line 14, in _fail
		fail(("%sGit Configuration Error:%s %...)))
Git Configuration Error: Traceback (most recent call last):
  File "/home/./.cache/bazel/_bazel_xulm1/b172144b72497b6793e5891257276c30/external/org_tensorflow/tensorflow/tools/git/gen_git_source.py", line 29, in <module>
    from builtins import bytes  # pylint: disable=redefined-builtin
ImportError: No module named builtins

ERROR: /./tensorflow-master/tensorflow/core/BUILD:2741:1: //tensorflow/core:version_info_gen depends on @local_config_git//:gen/branch_ref in repository @local_config_git which failed to fetch. no such package '@local_config_git//': Traceback (most recent call last):
	File "/./tensorflow-master/third_party/git/git_configure.bzl", line 61
		_fail(result.stderr)
	File "/./tensorflow-master/third_party/git/git_configure.bzl", line 14, in _fail
		fail(("%sGit Configuration Error:%s %...)))
Git Configuration Error: Traceback (most recent call last):
  File "/home/./.cache/bazel/_bazel_xulm1/b172144b72497b6793e5891257276c30/external/org_tensorflow/tensorflow/tools/git/gen_git_source.py", line 29, in <module>
    from builtins import bytes  # pylint: disable=redefined-builtin
ImportError: No module named builtins

WARNING: Download from https://storage.googleapis.com/mirror.tensorflow.org/github.com/abseil/abseil-cpp/archive/43ef2148c0936ebf7cb4be6b19927a9d9d145b8f.tar.gz failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException GET returned 404 Not Found
ERROR: Analysis of target '//tensorflow/lite/toco:toco' failed; build aborted: no such package '@local_config_git//': Traceback (most recent call last):
	File "/./tensorflow-master/third_party/git/git_configure.bzl", line 61
		_fail(result.stderr)
	File "/./tensorflow-master/third_party/git/git_configure.bzl", line 14, in _fail
		fail(("%sGit Configuration Error:%s %...)))
Git Configuration Error: Traceback (most recent call last):
  File "/home/./.cache/bazel/_bazel_xulm1/b172144b72497b6793e5891257276c30/external/org_tensorflow/tensorflow/tools/git/gen_git_source.py", line 29, in <module>
    from builtins import bytes  # pylint: disable=redefined-builtin
ImportError: No module named builtins

INFO: Elapsed time: 0.588s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (1 packages loaded, 0 targets configured)`

**Comment by ucasiggcas** [comment]
the` /./` is some path in my dirs

**Comment by jdduke** [comment]
Doesn't appear to be specific to TensorFlow Lite:

> ERROR: /./tensorflow-master/tensorflow/core/BUILD:2741:1: //tensorflow/core:version_info_gen depends on @local_config_git//:gen/spec.json in repository @local_config_git which failed to fetch. no such package '@local_config_git//': Traceback (most recent call last):
> File "/./tensorflow-master/third_party/git/git_configure.bzl", line 61
> _fail(result.stderr)

**Comment by gunan** [comment]
This is a download issue:
```
https://storage.googleapis.com/mirror.tensorflow.org/github.com/bazelbuild/bazel-toolchains/archive/92dd8a7a518a2fb7ba992d47c8b38299fe0be825.tar.gz failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException GET returned 404 Not Found
```

**Comment by ucasiggcas** [comment]
have solved the ups
but get the down,
`tensorflow-master$ bazel-bin/tensorflow/lite/toco/toco 
--graph_def_file=../my_freeze12xshell.pb --output_file=../my12.tflite 
--output_format=TFLITE --input_shape=2,4,513 --input_array=x_mixed 
--output_array=y_out1,y_out2 --inference_type=QUANTIZED_UINT8 
--inference_input_type=QUANTIZED_UINT8 --std_dev_values=1 --mean_values=0
 
-bash: bazel-bin/tensorflow/lite/toco/toco: No such file or directory`

when I deal the up,and get the https://github.com/tensorflow/tensorflow/issues/32650,
how to ?

**Comment by gunan** [comment]
Looks like you solved the build issue reported here?
I see that the issue you linked, you were able to run toco.

**Comment by gunan** [comment]
Closing the issue, because after the updates I see that original issue was resolved.
Will let the new issue be handled in the linked github issue.
