### ISSUE TITLE
How to build tf1.14 then build tf2.0?

### ISSUE THREAD

**Issue by jinfagang** [tensorflow/tensorflow#32640]
I try to build 2 different pip package with 2 versions. First:

```
bazel build --config=opt  //tensorflow/tools/pip_package:build_pip_package
# this generates 1.14 by default
./bazel-bin/tensorflow/tools/pip_package/build_pip_package /tmp/tensorflow_pkg

# then I try build v2
bazel build --config=v2 //tensorflow/tools/pip_package:build_pip_package
./bazel-bin/tensorflow/tools/pip_package/build_pip_package /tmp/tensorflow_pkg

```

But anyway it generates only 1.14, not 2.0 in the next step......

**Comment by mihaimaruseac** [comment]
1.14 comes from the `r1.14` branch, 2.0 from the `r2.0` one so you need to switch branches using `git checkout`.

`--config=v2` just enables 2.0 behavior but the version number stays the same

**Comment by gadagashwini** [comment]
@jinfagang, Did you try the @mihaimaruseac's solution and also please follow the instructions mentioned [here](https://www.tensorflow.org/install/source#download_the_tensorflow_source_code). Thanks!

**Comment by gadagashwini** [comment]
@jinfagang, Is this still an issue?

**Comment by gadagashwini** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
