### ISSUE TITLE
[TF1.14][TPU]Can not use custom TFrecord dataset on Colab using TPU

### ISSUE THREAD

**Issue by rishabhsahrawat** [tensorflow/tensorflow#32651]
I have created a TFRecord dataset file consisting elements and their corresponding labels. I want to use it for training model on Colab using free TPU. I can load the TFRecord file and even run an iterator just to see the contents however, before the beginning of the epoch it throws following error- 
````
UnimplementedError: From /job:worker/replica:0/task:0:
File system scheme '[local]' not implemented (file: '/content/gdrive/My Drive/data/encodeddata_inGZIP.tfrecord')
	 [[{{node MultiDeviceIteratorGetNextFromShard}}]]
	 [[RemoteCall]]
	 [[IteratorGetNextAsOptional_1]]
````
In my understanding, it wants the TFRecord file on the TPU bucket, I don't know how to do that on Colab. How can one use a TFRecord file directly on Colab TPU?

**Comment by oanush** [comment]
@rishabhsahrawat ,
Thanks for reporting the issue, Can you please provide a simple standalone code to reproduce the issue  or share us your colab gist. Also mention the TF version being used.Thanks!

**Comment by rishabhsahrawat** [comment]
HELLO @oanush , here is the Colab file [link.](https://drive.google.com/open?id=1nQi-DkqpaXj4NCNR3_EBbx_kNJr1BLV2) 
Please have a look and help me as soon as possible. Thank you!

**Comment by oanush** [comment]
Issue replicating for TF-1.14.

**Comment by rishabhsahrawat** [comment]
Hello @ymodak @oanush , any updates on this?. It is a major issue but no one is responding. Please  help me with this issue or just share a time window for which I must wait.
Thank you!

**Comment by frankchn** [comment]
Hello! Yeah, we don't allow local filesystem access on TPUs right now, and we recommend that you read and write checkpoints and other files on GCS. See our [MNIST on TPU colab](https://colab.sandbox.google.com/github/tensorflow/tpu/blob/master/tools/colab/keras_mnist_tpu.ipynb#scrollTo=Hd5zB1G7Y9-7) for an example.

With future TensorFlow and TPU releases (2.1+), you will be able to use the `ram://` file system to write temporary files that you don't need to access.

**Comment by rishabhsahrawat** [comment]
Hello @frankchn , thank you for your response. In your example link for MNIST data, it uses GCS bucket for storing image and label files, but I do not have a GCS bucket since I am using Google Colab free TPU or, maybe there is a way for free users to access and load the data to GCS.
Also, you talked about Checkpoints, checkpoints will be created once the model starts training which will require the dataset first.
So, my question is if there is a way I can use my TFRecord data directly to train a model on Colab using TPU?

**Comment by frankchn** [comment]
@rishabhsahrawat Unfortunately you have to use GCS to store data going into and out of TPUs. This is a current design limitation for the platform that we are working to resolve, but we don't have anything to announce at the moment.

You can sign up for a Google Cloud Platform account with 5GB of free storage and $300 in credits at https://cloud.google.com/free/, so that should be able to provide you with enough credits to get started.

**Comment by rishabhsahrawat** [comment]
@frankchn alright, thank you for your answer.
