### ISSUE TITLE
Unable to load tensorflow model in Java that was originally created in python (file not found exception)

### ISSUE THREAD

**Issue by maxx2803** [tensorflow/tensorflow#32655]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): _Yes_
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): _Windows 10 Version 1903_
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: _/_
- TensorFlow installed from (source or binary): _installed via pip in virtualenv_
- TensorFlow version (use command below): _1.14_
- Python version: _3.7_
- Bazel version (if compiling from source): _/_
- GCC/Compiler version (if compiling from source): _/_
- CUDA/cuDNN version: 10.0
- GPU model and memory: Nvidia GTX 1050 Ti (3 GB)

**Describe the current behavior**
I train a neural network. After training, I want to export my model in order to use it in Java for predictions. Unfortunately, it always displays an error while trying to load the model in Java, saying the file cannot be found (see error message below). I checked the path a hundred times and made sure via the built-in Java methods that the files exist and I have the rights to read them.

**Describe the expected behavior**
I expect the model to be loaded in order to use it for predictions within my native Java code.

**Code to reproduce the issue**
Below this you can see the Python code to export the model.

```
tf.saved_model.simple_save(sess,
                           path_graph_model_export_dir,
                           inputs=model_inputs, outputs={'sim': similarity})
```

This is the structure of the exported directory.

```
saved_model
---- saved_model.pb
---- variables
-------- variables.data-00000-of-00001
-------- variables.index
```

And the code in Java to load the model..

```
SavedModelBundle model = SavedModelBundle.load(modelPath, "serve")
```

results in this exception.

```
2019-09-17 10:59:03.905538: I tensorflow/cc/saved_model/reader.cc:31] Reading SavedModel from: saved_model
2019-09-17 10:59:03.905997: I tensorflow/cc/saved_model/loader.cc:311] SavedModel load for tags { serve }; Status: fail. Took 457 microseconds.
org.tensorflow.TensorFlowException: Could not find SavedModel .pb or .pbtxt at supplied export directory path: saved_model
```

**Other info / logs**
I use a tensorflow graph built with Sonnet (version 1.34) but I don't think this is an issue as Sonnet only assists in building more complex graphs.
Tensorboard model log: [tensorboard.zip](https://github.com/tensorflow/tensorflow/files/3631054/tensorboard.zip)
Saved model folder: [saved_model.zip](https://github.com/tensorflow/tensorflow/files/3631055/saved_model.zip)

**Comment by jvishnuvardhan** [comment]
@maxx2803 One question. Can you confirm whether `path_graph_model_export_dir` and `modelPath` are same? Can you try TF1.15.0rc1 and let us know whether the issue persists.

Can you also share a simple standalone code to reproduce the issue. You can use public data.  Thanks!

**Comment by maxx2803** [comment]
@jvishnuvardhan These two paths definitely link to the same folder. I checked it multiple times.
I also tested the new version 1.15.0-rc1 but the issue persists.

I put together some code to reproduce the issue.

First a maven repository that simply loads the model saved with python ([maven_repo.zip](https://github.com/tensorflow/tensorflow/files/3657870/maven_repo.zip)). You can run the class after first importing all dependencies included in the pom.xml and building the project (I use IntelliJ IDEA for this). For simplicity reasons, I included an exported model in this repository. This is the model that was exported by this python file ([python_code.zip](https://github.com/tensorflow/tensorflow/files/3657884/python_code.zip)). 

I use this python code together with the requirements to train a network and export the model. Unfortunately, I was not able to provide a shorter example. The code is taken from this repository (https://github.com/deepmind/deepmind-research/tree/master/graph_matching_networks) and my original code (that I cannot share here due to privacy restrictions) uses this code as well.

You can run the python file to export your own model folder that can then be inserted into the maven repository to be imported by Java. For me, this leads to the exception shown in my first post. I hope this helps in reproducing the issues. Thanks a lot!

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.

**Comment by mxhffmn** [comment]
Eventually, it worked for me. I am not entirely sure why, but I think my problem was caused by the paths that reference my models. I use Windows and I found that it makes a difference if you try to load a model at the path `C:\Users\testuser\model` or at `\C:\Users\testuser\model`. Apparently, this is a difference for TF. Also remember that the saved_model format always is a directory. So you have to load this directory as a model.
