### ISSUE TITLE
Broken link in https://www.tensorflow.org/versions/r2.0/api_docs

### ISSUE THREAD

**Issue by rodrigob** [tensorflow/tensorflow#32657]
In
https://www.tensorflow.org/versions/r2.0/api_docs
the `Swift (Early Release)`  link points to `https://www.tensorflow.org/versions/r2.0/swift` which shows a 404 page.

**Comment by jvishnuvardhan** [comment]
@rodrigob Thanks for pointing that "404" error. TensorFlow website is getting updated for TF2.0. Please wait for couple of days to update the links. Thanks!
