### ISSUE TITLE
Attention layer not serializable because it takes init args but doesn't implement get_config

### ISSUE THREAD

**Issue by currivan** [tensorflow/tensorflow#32662]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): MacOS 10.14.5 
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): v2.0.0-rc0-101-gd2d2566eef 2.0.0-rc1
- Python version: Python 3.6.8 :: Anaconda, Inc.
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Describe the current behavior**

Trying to save a model with a tensorflow.keras.layers.Attention layer throws because it doesn't implement get_config().

NotImplementedError: Layers with arguments in `__init__` must override `get_config`.

**Describe the expected behavior**

Model.save() should save the model.

**Code to reproduce the issue**

a = Input(shape=(None, 10))
attn = Attention()([a,a])
model = Model(a, attn)
model(np.zeros((50,10), dtype=np.float32))
model.save('my_model.h5')

**Other info / logs**

~/miniconda3/envs/tf20/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/base_layer.py in get_config(self)
    571     # or that `get_config` has been overridden:
    572     if len(extra_args) > 1 and hasattr(self.get_config, '_is_default'):
--> 573       raise NotImplementedError('Layers with arguments in `__init__` must '
    574                                 'override `get_config`.')
    575     # TODO(reedwm): Handle serializing self._dtype_policy.

NotImplementedError: Layers with arguments in `__init__` must override `get_config`.

**Comment by gowthamkpr** [comment]
Was able to reproduce the issue. Please find the github gist [here](https://colab.sandbox.google.com/gist/gowthamkpr/d79de99944192c0f8195b975718809b5/untitled147.ipynb). In the mean while, I was able to save the weights and load them. You can find it in the gist above.

**Comment by qlzh727** [comment]
The issue was recently fixed in https://github.com/tensorflow/tensorflow/commit/498e815097e74aff7fefdbbae69ba9daf6e9c023, but we haven't cherrypick it into 2.0 rc yet. I verified the code against nightly and it works.

Could you try to save it as tf format as a workaround?

**Comment by XXZhou25** [comment]
same problem in tensorflow 2.0 right now. Actually I don't know what triggers this issue.
