### ISSUE TITLE
ERROR: Cannot find './util/python/python_lib

### ISSUE THREAD

**Issue by pjoz** [tensorflow/tensorflow#3266]
### Environment info
Operating System:
OSX El Capitan 10.11.5

Installed version of CUDA and cuDNN: 
N/A

If installed from sources, provide the commit hash:
a4b7bb9

### Steps to reproduce
1. `git clone --recursive https://github.com/tensorflow/models.git`
2. `cd models/syntaxnet/tensorflow`
3. `./configure`
4. `cd ..`
5. `bazel build syntaxnet/...`

### What have you tried?
1. Confirmed that bazel version is 0.2.2
2. Confirmed that configure has been run

### Logs or other output that would be helpful
(If logs are large, please upload as attachment).
`INFO: Found 74 targets...
ERROR: /private/var/tmp/_bazel_pberkman/64f225994fec6ff696f44dfe0caf6bfc/external/org_tensorflow/util/python/BUILD:14:1: Executing genrule @org_tensorflow//util/python:python_check failed: bash failed: error executing command /bin/bash -c ... (remaining 1 argument(s) skipped): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
ERROR: Cannot find 'external/org_tensorflow/util/python/python_lib'.  Did you run configure?`

Seems that this issue is consistent with error https://github.com/tensorflow/tensorflow/issues/2703

**Comment by jmchen-g** [comment]
Duplicate to https://github.com/tensorflow/models/issues/266
