### ISSUE TITLE
Documentation about XLA backend is incomplete and inaccurate

### ISSUE THREAD

**Issue by yurivict** [tensorflow/tensorflow#32661]
Looking at ```Scenario 3``` in https://github.com/tensorflow/tensorflow/issues/new?labels=type%3Adocs&template=20-documentation-issue.md

It has a link to the class ```StreamExecutor``` but the link leads to the empty class with comments suggesting that it has been removed (?)

**Comment by gadagashwini** [comment]
@yurivict,
Please provide the correct link of documentation where the problem persists. Thanks!

**Comment by yurivict** [comment]
I fixed the link, sorry for  the mishap.

**Comment by gadagashwini** [comment]
@yurivict,
Good to know that its fixed. 
I am closing the issue now. Please feel free to reopen if the issue still persists. Thanks!
