### ISSUE TITLE
Broken link in https://www.tensorflow.org/guide/eager#top_of_page

### ISSUE THREAD

**Issue by rodrigob** [tensorflow/tensorflow#32664]
https://www.tensorflow.org/guide/eager#top_of_page
says
"For a collection of examples running in eager execution, see: tensorflow/contrib/eager/python/examples."

The link to `https://github.com/tensorflow/tensorflow/tree/master/tensorflow/contrib/eager/python/examples` returns a 404 error.

**Comment by jvishnuvardhan** [comment]
@rodrigob TensorFlow website is getting updated for `TF2.0`. Please wait for couple of days to update the links. For now you can find those file at this [location](https://github.com/tensorflow/tensorflow/tree/r1.15/tensorflow/contrib/eager/python/examples). Thanks!

**Comment by rodrigob** [comment]
why are we deploying websites with broken links ?
in 2019 automated links checking should be part of the deployment/testing process.
