### ISSUE TITLE
Performance of tf.io.read_file in graph mode

### ISSUE THREAD

**Issue by remydubois** [tensorflow/tensorflow#32660]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 16.04
- TensorFlow installed from (source or binary): Binary
- TensorFlow version (use command below): 2.0.0rc1
- Python version: 3.6.0
- Bazel version (if compiling from source): NA
- GCC/Compiler version (if compiling from source): NA
- CUDA/cuDNN version: NA
- GPU model and memory: NA

**Current behavior**
I observed surprising performances of the different ways to read a file, especially when comparing graph mode (by `tf.function`) versus eager mode. I compared two ways to read a file:
`tf.io.gfile.GFile(filepath).read(-1)` versus  `tf.io.read_file(filepath)`.
If the two have similar performances in eager mode, the first option gains a close to 50% speedup when using it in graph mode (wrapped into a `tf.function` call), while the latter one do not show any speed improvement, rather a slowdown.

**Expected behavior**
I do not  understand why such a speed up is observed on `tf.io.gfile.GFile` while `tf.io.read_file` does not benefit any. This is crucial because my data pipeline yields filepaths through `tf.data.Dataset.list_files()`, which are further read and decoded, but tf.io.gfile.GFile does not accept string tensors as input. Hence I am forced to use `tf.io.read_file` (see  [issue](https://github.com/tensorflow/tensorflow/issues/32620))

**Code to reproduce the issue**
See below a MVCE:

```
import numpy as np
import tensorflow as tf
import timeit
import os

filepath = '/tmp/array.npy'
np.save(filepath, np.ones(shape=(400, ) * 3))

def read_Gfile(path):
    f = tf.io.gfile.GFile(name=path, mode='rb')
    s = f.read(-1)
    f.close()
    return s

read_io = lambda x: tf.io.read_file(x)

graph_read_io = tf.function(read_io)
graph_read_Gfile = tf.function(read_Gfile)

print('Reading with numpy: %.3f ms' % (timeit.Timer(lambda: np.load(filepath)).timeit(number=10) * 1000 / 10))
print('Reading in eager mode with GFile: %.3f ms' % (timeit.Timer(lambda: read_Gfile(filepath)).timeit(number=10) * 1000 / 10))
print('Reading in eager mode with io.read_file: %.3f ms' % (timeit.Timer(lambda: read_io(filepath)).timeit(number=10) * 1000 / 10))
print('Reading in graph mode with GFile: %.3f ms' % (timeit.Timer(lambda: graph_read_Gfile(filepath)).timeit(number=10) * 1000 / 10))
print('Reading in graph mode with io.read_file: %.3f ms' % (timeit.Timer(lambda: graph_read_io(filepath)).timeit(number=10) * 1000/ 10))

os.remove(filepath)
```
This code produces the following performances:
```
Reading with numpy: 175.189 ms
Reading in eager mode with GFile: 826.163 ms
Reading in eager mode with io.read_file: 767.376 ms
Reading in graph mode with GFile: 509.069 ms
Reading in graph mode with io.read_file: 864.643 ms
```

**Comment by gadagashwini** [comment]
@remydubois, Will it be possible to share the .npy file that you are using. Thanks!

**Comment by remydubois** [comment]
Thanks for looking into that,

the np array is created and saved at the beginning of the MVCE `np.save(filepath, np.ones(shape=(400, ) * 3))`. It creates a ~200MB file on disk, used later for benchmarking.
It is as well deleted at the end of the script, that might be the reason why you don't find it once the MVCE has run.

**Comment by gadagashwini** [comment]
@remydubois,
When i tried executing the code on colab i got the following error. Please see the colab [gist](https://colab.sandbox.google.com/gist/gadagashwini/f336c6860e2884b5a281dc7ff9ea3c7f/untitled.ipynb). 
`NameError: name 'path' is not defined.`
Thanks!

**Comment by remydubois** [comment]
My bad, MVCE updated, there was a small typo.
Thanks for reporting, it should be running fine now, I updated the _timeit_s as well

**Comment by gadagashwini** [comment]
@remydubois, 
Thanks for the update. Please take a look at the colab [gist](https://colab.sandbox.google.com/gist/gadagashwini/f336c6860e2884b5a281dc7ff9ea3c7f/untitled.ipynb#scrollTo=Ira0XqRn-IJ1). Thanks!

**Comment by gadagashwini** [comment]
@remydubois, Did you get chance to look attached colab gist. Thanks!

**Comment by remydubois** [comment]
Thanks for looking into that.

I looked at your benchmarks, it seems that the speed evaluations are highly non-reproducible, depending on the machine.
Without any further insights, I think we can consider this issue closed, because the problem is hard to identify.

Feel free to reopen it if you think it necessary

**Comment by gadagashwini** [comment]
@remydubois, Closing the issue, feel free to comment/reopen the issue if issue still persists. Thanks!
