### ISSUE TITLE
Tensorflow Java API and @tf.function signatures

### ISSUE THREAD

**Issue by bqm** [tensorflow/tensorflow#32674]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes.
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): CentOS 7
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below): 1.14
- Python version: 3.7
- Bazel version (if compiling from source): 25.1
- GCC/Compiler version (if compiling from source): 7.3

**Describe the current behavior**

The current Tensorflow Java API (1.14 or 2.0) doesn't seem to be able to do inference on Tensorflow nodes created within a `@tf.function` signature. 

On a related note, https://github.com/tensorflow/community/blob/master/rfcs/20180918-functions-not-sessions-20.md mentions that Java is planning to stay `Session` centric. Ideally, a signature inference centric API would be a good way to solve this issue and would be a good addition to the existing Java API.

Concretely, here is the Python snippet defining a `request` and `response` (full Python code attached at the bottom of this ticket):
```
  @tf.function(input_signature=[tf.TensorSpec(shape=[None, None], name="serving")])
  def serve(self, request):
    features = tf.identity(self.input_receiver(request), name='request')
    output = self.call(features)
    response = tf.identity(self.response_receiver(output), name='response')
    return response
```
After exporting my model to a `SavedModelBundle` and  trying to do some prediction in Java via the `Session.runner()` API, I am getting:
```
java.lang.IllegalArgumentException: No Operation named [request] in the Graph
  at org.tensorflow.Session$Runner.operationByName(Session.java:380)
  at org.tensorflow.Session$Runner.parseOutput(Session.java:394)
  at org.tensorflow.Session$Runner.feed(Session.java:131)
  ... 34 elided
```
where `request` is defined within a `@tf.function`.

**Describe the expected behavior**

I would expect to not have a runtime failure at inference time on the JVM: either `operationByName` would recognize the `request:0` node or another Java API would exist to fulfill my requirements.

**Code to reproduce the issue**

Python code (model creation):
```
import tensorflow as tf
from tensorflow.keras import layers


class MnistModel(tf.keras.Model):
  def __init__(self):
    super().__init__()
    self.first_dense = layers.Dense(64, input_shape=(784,), activation='relu', name='dense_1')
    self.out = layers.Dense(10, activation='softmax', name='predictions')

  def call(self, inp):
    f_dense = self.first_dense(inp)
    s_dense = self.out(f_dense)
    return s_dense

  def input_receiver(self, inp):
    return inp

  def response_receiver(self, output):
    return output

  @tf.function(input_signature=[tf.TensorSpec(shape=[None, None], name="serving")])
  def serve(self, request):
    features = tf.identity(self.input_receiver(request), name='request')
    output = self.call(features)
    response = tf.identity(self.response_receiver(output), name='response')
    return response

model = MnistModel()

(x_train, y_train), (x_test, y_test) = keras.datasets.mnist.load_data()
x_train = x_train.reshape(60000, 784).astype('float32') / 255
x_test = x_test.reshape(10000, 784).astype('float32') / 255

model.compile(loss='sparse_categorical_crossentropy',
              optimizer=keras.optimizers.RMSprop())
history = model.fit(x_train, y_train,
                    batch_size=64,
                    epochs=1)

keras.experimental.export_saved_model(model, 'local_path', serving_only=True)
```

JVM / Scala code (inference code):
```
import org.tensorflow.{SavedModelBundle, Session, Tensor}
import java.nio.ByteBuffer
import java.lang.{Float => JFloat}

val savedModelBundle = SavedModelBundle.load("local_path", "serve")

val session = savedModelBundle.session()

val byteBuffer = ByteBuffer.allocate(784*4)

val tensor = Tensor.create(
    classOf[JFloat],
    Array(784),
    byteBuffer)

session.runner()
  .feed("request:0", tensor)
  .fetch("output:0")
  .run()

tensor.close()
byteBuffer.close()
```

I am getting the following error:
```
java.lang.IllegalArgumentException: No Operation named [request] in the Graph
  at org.tensorflow.Session$Runner.operationByName(Session.java:380)
  at org.tensorflow.Session$Runner.parseOutput(Session.java:394)
  at org.tensorflow.Session$Runner.feed(Session.java:131)
  ... 34 elided
```

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by jvishnuvardhan** [comment]
@bqm Can you try TF1.15.0rc1 and let us know whether the issue persists or not? Thanks!

**Comment by bqm** [comment]
Hello @jvishnuvardhan, thank you for your answer.

Using the 1.15.0rc1 JAR provided in https://storage.googleapis.com/tensorflow/, I was able to confirm that the issue also exists on TF1.15.0rc1.

**Comment by bqm** [comment]
I've updated a protobuf text format of the created SavedModel - can be seen at https://gist.github.com/bqm/88c62df65d76832108de2ec0f9b853cc.

The `request:0` and `response:0` nodes are stored in the `Library`
protobuf object (which starts line 1306). My guess is that the current Tensorflow API ignores that Library object. Thoughts?

Definition of the Protobuf Library object below:
https://github.com/tensorflow/tensorflow/blob/9590c4c32dd4346ea5c35673336f5912c6072bf2/tensorflow/core/framework/graph.proto#L55

**Comment by bqm** [comment]
@saxenasaurabh - https://groups.google.com/a/tensorflow.org/forum/#!topic/jvm/685y-ou__PU mentions that you might be working on a C API relating to this issue. Can you let us know if that's the case? And if so, what's the best way to track the progress?

**Comment by saxenasaurabh** [comment]
Feeding values and fetching values of tensors defined inside tf.function is not allowed.
cc: @k-w-w @allenlavoie

**Comment by bqm** [comment]
@saxenasaurabh Thank you for your answer! I have a bunch of follow-up questions, some of which I am planning to investigate more next week but would love your input if you know the answers off-hand (no worries if you have answers only to a few, that would still be really helpful!):
* 'Not allowed' - is this a design decision / would it make sense to change it? (would love if you know of a link / documentation explaining this)
* If you are not planning to change it, what would be an alternative? Assuming the `serving:0` is accessible to the JVM API (input node of tf.function), what would be the right output node to use?
* This doesn't seem to be specific to the JVM API, is that correct? For instance, do you know how TF Serving would behave? (I will dive more into this one but if you know off-hand, response appreciated :))

**Comment by bqm** [comment]
After more investigations, it seems that using `tf.saved_model.save` for exporting with `signatures` provided seem to add the missing input and output tensors **for the outer tensors**.

So the export call becomes:
```
tf.saved_model.save(model, 'local_path', signatures={"serve": model.serve})
```
This will have the effect of adding new TF tensors which can be feed and retrieved via the Session JVM API:
```
!saved_model_cli show --dir local_path --all

signature_def['__saved_model_init_op']:
  The given SavedModel SignatureDef contains the following input(s):
  The given SavedModel SignatureDef contains the following output(s):
    outputs['__saved_model_init_op'] tensor_info:
        dtype: DT_INVALID
        shape: unknown_rank
        name: NoOp
  Method name is:

signature_def['serve']:
  The given SavedModel SignatureDef contains the following input(s):
    inputs['serve'] tensor_info:
        dtype: DT_FLOAT
        shape: unknown_rank
        name: serve_serve:0
  The given SavedModel SignatureDef contains the following output(s):
    outputs['output_0'] tensor_info:
        dtype: DT_FLOAT
        shape: unknown_rank
        name: PartitionedCall:0
  Method name is: tensorflow/serving/predict
```
The right JVM tensor to feed is `serve_serve:0` for the input and `PartitionedCall:0` for the output in that example.

This setup doesn't give me access to the `request:0` and `response:0` tensors but I think that's fine - one can create new `@tf.function` and add the relevant signatures for that.

The user experience is not great because the user doesn't have control on the tensor names (`serve_serve:0` and `PartitionedCall:0` in my previous example) but it does the job.

My proposal would be to close this issue based on the findings above. I can reopen a new github issue in https://github.com/tensorflow/java directly to improve the user experience (for instance via providing a signature API on the JVM).

@sjamesr any thoughts?

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.
