### ISSUE TITLE
A keras model containing a tf.tile op layer with a tensor in the `multiples` arg fails when saving to hdf5

### ISSUE THREAD

**Issue by currivan** [tensorflow/tensorflow#32672]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): MacOS 10.14.5
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): v2.0.0-rc0-101-gd2d2566eef 2.0.0-rc1
- Python version: Python 3.6.8 :: Anaconda, Inc.
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**

A keras model containing a tf.tile op layer with a tensor in the `multiples` arg throws an exception when saving to hdf5.

(I'm using tf.tile because RepeatVector(n) doesn't accept a tensor for n. The goal is to stack a 2d feature batch so it can be concatenated to a variable length 3d batch of sequence features.)

**Describe the expected behavior**

Model.save() should save the model.

**Code to reproduce the issue**

import numpy as np
import tensorflow as tf
from tensorflow.keras.layers import Input
from tensorflow.keras import Model

a = Input(shape=(10,))
out = tf.tile(a, (1, tf.shape(a)[0]))
model = Model(a, out)

x = np.zeros((50,10), dtype=np.float32)
print(model(x).numpy())

model.save('my_model.h5')

**Other info / logs**

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-2-9b1429243599> in <module>
     11 print(model(x).numpy())
     12 
---> 13 model.save(model_dir + '/my_model.h5')

~/miniconda3/envs/tf20/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/network.py in save(self, filepath, overwrite, include_optimizer, save_format, signatures, options)
   1187     """
   1188     saving.save_model(self, filepath, overwrite, include_optimizer, save_format,
-> 1189                       signatures, options)
   1190 
   1191   def save_weights(self, filepath, overwrite=True, save_format=None):

~/miniconda3/envs/tf20/lib/python3.6/site-packages/tensorflow_core/python/keras/saving/save.py in save_model(model, filepath, overwrite, include_optimizer, save_format, signatures, options)
    110           'or using `save_weights`.')
    111     hdf5_format.save_model_to_hdf5(
--> 112         model, filepath, overwrite, include_optimizer)
    113   else:
    114     saved_model_save.save(model, filepath, overwrite, include_optimizer,

~/miniconda3/envs/tf20/lib/python3.6/site-packages/tensorflow_core/python/keras/saving/hdf5_format.py in save_model_to_hdf5(model, filepath, overwrite, include_optimizer)
    107     model_weights_group = f.create_group('model_weights')
    108     model_layers = model.layers
--> 109     save_weights_to_hdf5_group(model_weights_group, model_layers)
    110 
    111     # TODO(b/128683857): Add integration tests between tf.keras and external

~/miniconda3/envs/tf20/lib/python3.6/site-packages/tensorflow_core/python/keras/saving/hdf5_format.py in save_weights_to_hdf5_group(f, layers)
    623 
    624   for layer in layers:
--> 625     g = f.create_group(layer.name)
    626     weights = _legacy_weights(layer)
    627     weight_values = K.batch_get_value(weights)

~/miniconda3/envs/tf20/lib/python3.6/site-packages/h5py/_hl/group.py in create_group(self, name, track_order)
     66             name, lcpl = self._e(name, lcpl=True)
     67             gcpl = Group._gcpl_crt_order if track_order else None
---> 68             gid = h5g.create(self.id, name, lcpl=lcpl, gcpl=gcpl)
     69             return Group(gid)
     70 

h5py/_objects.pyx in h5py._objects.with_phil.wrapper()

h5py/_objects.pyx in h5py._objects.with_phil.wrapper()

h5py/h5g.pyx in h5py.h5g.create()

ValueError: Unable to create group (name already exists)

**Comment by oanush** [comment]
I was able to replicate the issue with given code for TF-2.0rc1, please find the [gist](https://colab.sandbox.google.com/gist/oanush/8ee3a61919408dadf12499d2d95792ca/32672.ipynb) of colab.Thanks!

**Comment by jvishnuvardhan** [comment]
@currivan I Don't see any issue if you remove the ".h5" from the `model.save`. I changed only last line from your code as follows.

```
import numpy as np
import tensorflow as tf
from tensorflow.keras.layers import Input
from tensorflow.keras import Model

a = Input(shape=(10,))
out = tf.tile(a, (1, tf.shape(a)[0]))
model = Model(a, out)

x = np.zeros((50,10), dtype=np.float32)
print(model(x).numpy())

model.save('./my_model')
```
Please check the [gist here](https://colab.sandbox.google.com/gist/jvishnuvardhan/9348e139288b969517ed527334e5fb57/32672.ipynb). Thanks!

I am closing this issue as it was resolved. Please feel free to open it if the issue persists again. Thanks!

**Comment by currivan** [comment]
This should not have been closed. Throwing an exception here is a bug, and the solution is unacceptable. Saving this type of model with h5 takes a second, and the proposed way it takes over a minute. Loading is also unacceptably slow.

**Comment by jvishnuvardhan** [comment]
@currivan In case If i need to use an op like `tf.tile` as in your case, I will call it with a lambda layer. So the code is as follows

```
import numpy as np
import tensorflow as tf
from tensorflow.keras.layers import Input, Lambda
from tensorflow.keras import Model

def my_fun(a):
  out = tf.tile(a, (1, tf.shape(a)[0]))
  return out

a = Input(shape=(10,))
#out = tf.tile(a, (1, tf.shape(a)[0]))
out = Lambda(lambda x : my_fun(x))(a)
model = Model(a, out)

x = np.zeros((50,10), dtype=np.float32)
print(model(x).numpy())

model.save('my_model.h5')

#load the model
new_model=tf.keras.models.load_model("my_model.h5")

```
Please let me know what you think? Thanks!

**Comment by currivan** [comment]
@jvishnuvardhan thanks, I was also able to create a custom layer. In general I feel if a model can be executed, it should be savable by all standard methods without throwing an opaque exception. Someone should still fix the bug with saving op layers. "ValueError: Unable to create group (name already exists)" isn't the right way to handle this even if it's unsupported.

**Comment by jvishnuvardhan** [comment]
@currivan I agree. May be we need to update the error description. Please note that fixing this is not simple.

@k-w-w Could you please take a look at this issue?

**Comment by ELind77** [comment]
I believe that this is the same issue as #12195.  When adding a `tf.tile` operation the keras model gets a `tf_op_layer_Title/multiples` layer added _before_ a `tf_op_layer_Tile` layer which I believe is what causes the problem.

**Comment by SudoMike** [comment]
@ELind77 : #12195 seems totally unrelated to this. Did you mean to link to a different issue?

@currivan : One problem with using Lambda is that your layer won't have a proper shape defined in case following layers need that.

**Comment by fonnesbeck** [comment]
This issue was closed prematurely. A fix needs to be implemented so that the exception is not thrown. Should I open a new issue?

**Comment by jvishnuvardhan** [comment]
@currivan I think this was resolved recently in `tf-nightly`. I ran it with `tf-nightly` without any issue. Please check the [gist here](https://colab.sandbox.google.com/gist/jvishnuvardhan/15f06ff402a678a77d0c47592a290701/32672.ipynb). Thanks!

I am closing this issue as it was resolved. Please feel free to reopen. Thanks!

**Comment by jsilter** [comment]
I have a similar problem. I'm not using tf.tile, I have a custom layer which uses tf.concat, tf.map_fn, and tf.cast. The latest nightly (tf-nightly-2.2.0.dev20200226) seems to crash on my machine so I'm not able to test it fully.

The error message is the same (I found this issue by googling it).

**Comment by jvishnuvardhan** [comment]
@jsilter Can you please create  new issue with a standalone code to reproduce the issue? Thanks!

**Comment by markemus** [comment]
This issue is happening for me with tf.clip_by_value(). I haven't tested the nightly build.

**Comment by fzyzcjy** [comment]
> This should not have been closed. Throwing an exception here is a bug, and the solution is unacceptable. Saving this type of model with h5 takes a second, and the proposed way it takes over a minute. Loading is also unacceptably slow.

Same here. For a resnet-like architecture, saving using the `tf` format will lead to about 45 seconds...
