### ISSUE TITLE
Arguments formatting error in 1.15 keras.model.save docs + incorrect model format info/docstring mismatch?

### ISSUE THREAD

**Issue by jubjamie** [tensorflow/tensorflow#32684]
## Description of issue (what needs changing):
[1.15 branch]
It appears that the docstring of keras.model.save does not match the docs in 1.15.

Content is different I think.

The bullet points for the input arguments for the save method are not formatted making it hard to read (although this may be poor formatting on the current source for the documentation as the docstring appears to be correctly formatted.).

A side effect of this is that it also appears that the docs conflicts with the release notes that say the default format is as a `Tensorflow SavedModel ('tf')` however the docs say that the `tf` option is disabled implying that only `.h5` formats can be saved which is contradictory. An update of the docs from the seemingly correct docstring may fix this.

### Correct links

The source code link appears to be correct despite the docstring not matching that of the website docs.

### Parameters defined

Formatting issue and also not updated.

### Returns defined

Depends on model format.

### Raises listed and defined

Depends on model format.

### Submit a pull request?

I don't quite understand why this has happened so no.

**Comment by jvishnuvardhan** [comment]
@jubjamie I updated the doc on TF website. It is now reflecting correctly on the [TF website](https://www.tensorflow.org/api_docs/python/tf/keras/Model?authuser=1#save). 

I am closing this issue as this was resolved. Please feel free to reopen if I am mistaken. Thanks!
