### ISSUE TITLE
Tensorflow 2.0 tf.lite.TFLiteConverter.from_keras_model giving 'str' object has no attribute 'call'

### ISSUE THREAD

**Issue by alokmalik** [tensorflow/tensorflow#32693]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 16.04 on Amazon EC2
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: no
- TensorFlow installed from (source or binary): pip 
- TensorFlow version (use command below): tensorflow 2.0 rc1
- Python version: 3.6.8
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: On CPU and on google colab also
- GPU model and memory: On google colab, 

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**

It's not able to convert the LSTM model to tflite format

**Describe the expected behavior**
it should be able to convert the model to tflite format.

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

import tensorflow as tf
converter = tf.lite.TFLiteConverter.from_keras_model("language_small_adam-01.hdf5")
tflite_model = converter.convert()
open("converted_model.tflite", "wb").write(tflite_model)

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-58-c5d53462d122> in <module>
      1 import tensorflow as tf
----> 2 converter = tf.lite.TFLiteConverter.from_keras_model("language_small_adam-01.hdf5")
      3 tflite_model = converter.convert()
      4 open("converted_model.tflite", "wb").write(tflite_model)

~/anaconda3/envs/test/lib/python3.6/site-packages/tensorflow_core/lite/python/lite.py in from_keras_model(cls, model)
    380       TFLiteConverter object.
    381     """
--> 382     func = _saving_utils.trace_model_call(model)
    383     concrete_func = func.get_concrete_function()
    384     return cls([concrete_func])

~/anaconda3/envs/test/lib/python3.6/site-packages/tensorflow_core/python/keras/saving/saving_utils.py in trace_model_call(model, input_signature)
    122   """
    123   if input_signature is None:
--> 124     if isinstance(model.call, def_function.Function):
    125       input_signature = model.call.input_signature
    126 

AttributeError: 'str' object has no attribute 'call'

**Comment by gargn** [comment]
LSTMs are currently a [work in progress](https://www.tensorflow.org/lite/r2/convert/python_api#liteophint).

As we work on adding support, can you provide a minimal repro of your issue. Either provide the model or a modified version of the model / model code to help investigate the issue.

**Comment by alokmalik** [comment]
hi @gargn ,

Thanks for such a quick reply. Below is the code i used to generate the model. I used tf.keras for all the functions. Please find the model file below.

[language_adam-01.zip](https://github.com/tensorflow/tensorflow/files/3647337/language_adam-01.zip)



`inputs1 = Input(shape=(2048,))
fe1 = Dropout(0.5)(inputs1)
fe2 = Dense(256, activation='relu')(fe1)

inputs2 = Input(shape=(5,))
se1 = Embedding(vocab_size, embedding_dim, mask_zero=True)(inputs2)
se2 = Dropout(0.5)(se1)
se3 = LSTM(256)(se2)

decoder1 = add([fe2, se3])
decoder2 = Dense(256, activation='relu')(decoder1)
outputs = Dense(vocab_size, activation='softmax')(decoder2)


model = Model(inputs=[inputs1, inputs2], outputs=outputs)`

Please let me know if you need any further inputs from my side.

**Comment by alokmalik** [comment]
@gargn I tried replacing LSTM in above code with GRU, it's giving same error.

**Comment by haozha111** [comment]
Hi,

Keras LSTM/GRU will not be supported in the current TOCO converter. We are working on a new TF Lite converter that could convert LSTMs nicely. Please stay tuned. Thanks!

**Comment by egealpay** [comment]
Any update?

**Comment by gargn** [comment]
To try the new converter, use the `tf-nightly` pip package and then try:

```
converter = tf.lite.TFLiteConverter.from_keras_model(model)
converter.experimental_new_converter = True
tflite_model = converter.convert()
```

**Comment by egealpay** [comment]
Even with the tf-nightly package, I am getting the same error

**Comment by jvishnuvardhan** [comment]
@alokmalik I have updated your code with an `experimental_new_convereter`, then everything works as expected. Please take a look at the [gist here](https://colab.sandbox.google.com/gist/jvishnuvardhan/4db22181f32e76dd28619c33ba79c10d/untitled636.ipynb). Thanks!

```
import tensorflow as tf
model=tf.keras.models.load_model("./language_adam-01.hdf5")
converter = tf.lite.TFLiteConverter.from_keras_model(model)
converter.experimental_new_converter = True
tflite_model = converter.convert()
open("converted_model.tflite", "wb").write(tflite_model)  
```

I am closing this issue as it was resolved by the new converter. Please feel free to reopen if the issue persists again. Thanks!

**Comment by alokmalik** [comment]
thanks @gargn @jvishnuvardhan , it's working now. I'll comment back if it doesn't work in mobile.

**Comment by kazuimotn** [comment]
`converter.experimental_new_converter = True`
is is what I have been waiting for!
I can convert my model from .h5 to .tflite.
However, when I try to load this model to my Android APK, There are some problem:

I have class that loads .tflite model as byteBuffer and predict probabilities as following:

`public class TensorFlowLiteClassifier {

    private Interpreter interpreter;
    public static final String MODEL_FILE = "LSTM.tflite";
    public static final int LABEL_NUM = 2;

    /**
     * Registers interpreter
     * インタプリタの登録
     */
    private TensorFlowLiteClassifier(Interpreter interpreter) {
        this.interpreter = interpreter;
    }

    /**
     * Loads model into interpreter
     * インタプリタにモデルを読み込み
     */
    public static TensorFlowLiteClassifier classifier(AssetManager assetManager, String modelPath) throws IOException {
        ByteBuffer byteBuffer = loadModelFile(assetManager, modelPath);
        Interpreter interpreter = new Interpreter(byteBuffer);
        return new TensorFlowLiteClassifier(interpreter);
    }

    /**
     * Loads model
     * モデルの読み込み
     */
    private static MappedByteBuffer loadModelFile(AssetManager assets, String path) throws IOException {
        AssetFileDescriptor file = assets.openFd(path);
        FileInputStream stream = new FileInputStream(file.getFileDescriptor());
        FileChannel channel = stream.getChannel();
        long startOffset = file.getStartOffset();
        long declaredLength = file.getDeclaredLength();
        return channel.map(FileChannel.MapMode.READ_ONLY, startOffset, declaredLength);
    }

    /**
     * Function that actually performs inference
     * 実際に推論を実行する関数
     */
    public float[][] predictProbabilities(float[][] input) {
        float[][] output = new float[1][LABEL_NUM];
        interpreter.run(input, output);
        return output;
    }
}`

An error occurred when creating a new intepreter from byteBuffer.
`Interpreter interpreter = new Interpreter(byteBuffer);`

Logcat is following:
`2019-11-15 20:43:04.897 19973-19973/iis.kmjlab.kazuimotn.sartips A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0x70 in tid 19973 (zuimotn.sartips)`

How can I deal with this unknown error?

**Comment by jvishnuvardhan** [comment]
@kazuimotn Can you please create a new issue so that it will be easy for others  to follow who have similar issue like to you. Thanks!

**Comment by kazuimotn** [comment]
opened [here](https://github.com/tensorflow/tensorflow/issues/34313#issue-523552107)

**Comment by prerna-khanna** [comment]
> @alokmalik I have updated your code with an `experimental_new_convereter`, then everything works as expected. Please take a look at the [gist here](https://colab.sandbox.google.com/gist/jvishnuvardhan/4db22181f32e76dd28619c33ba79c10d/untitled636.ipynb). Thanks!
> 
> ```
> import tensorflow as tf
> model=tf.keras.models.load_model("./language_adam-01.hdf5")
> converter = tf.lite.TFLiteConverter.from_keras_model(model)
> converter.experimental_new_converter = True
> tflite_model = converter.convert()
> open("converted_model.tflite", "wb").write(tflite_model)  
> ```
> 
> I am closing this issue as it was resolved by the new converter. Please feel free to reopen if the issue persists again. Thanks!

Hi,
I have a Bi-directional LSTM model and I want to use it with tflite. I get the following error while saving the model: TypeError: 'int' object is not callable.
I have tried the experimental converter, but nothing works.
Currently, I am using the tf_nightly-2.6.0.dev20210614 release. The same code worked for me with "tf-nightly-2.5.0-dev20201111" release. 
Any leads on how to proceed further?

**Comment by alokmalik** [comment]
@prerna-khanna I think you'll have to use regular tensorflow version now, it's a 2 year old issue and the feature is out of beta testing(nightly build).

**Comment by KHariHaraChaitanya** [comment]
I am facing this kind of issue. tf-nightly and converter.experimental_new_converter = True are not solving the problem. 
This is the error:
AttributeError                            Traceback (most recent call last)
[<ipython-input-19-ef83db20ca6f>](https://localhost:8080/#) in <cell line: 7>()
      5 converter.optimizations = [tf.lite.Optimize.DEFAULT]
      6 #converter.experimental_new_converter = True
----> 7 q_aware_tflite_model = converter.convert()

5 frames
[/usr/local/lib/python3.10/dist-packages/tensorflow/lite/python/lite.py](https://localhost:8080/#) in _freeze_keras_model(self)
   1541     # to None.
   1542     # Once we have better support for dynamic shapes, we can remove this.
-> 1543     if not isinstance(self._keras_model.call, _def_function.Function):
   1544       # Pass `keep_original_batch_size=True` will ensure that we get an input
   1545       # signature including the batch dimension specified by the user.
AttributeError: 'float' object has no attribute 'call'
