### ISSUE TITLE
Tensorflow v2.0rc* is impossible to install with pip 18.1

### ISSUE THREAD

**Issue by Ark-kun** [tensorflow/tensorflow#32698]
I'm installing TF on Debian 10 with python 3.6: `Debian 4.19.37-5+deb10u1rodete2 (2019-08-06 > 2018) x86_64 GNU/Linux`

TF 2.0beta1 had support for the manylinux1 tag which allowed me to successfully install it.
TF 2.0rc1 switched to the `manylinux2010` tag which is not supported on my Debian installation with pip 18.1 and rc1 cannot be installed.

Can TF not require upgrading pip to install?

```
https://pypi.org/simple/tensorflow/ :
tensorflow-2.0.0b1-cp36-cp36m-manylinux1_x86_64.whl
tensorflow-2.0.0rc0-cp36-cp36m-manylinux2010_x86_64.whl

```

```
python3 -c "import wheel.pep425tags as w; print(w.get_supported())" | tr '\n' '\0' | sed -E 's/\),/),\n/g'
[('cp36', 'cp36m', 'linux_x86_64'),
 ('cp36', 'abi3', 'linux_x86_64'),
 ('cp36', 'none', 'linux_x86_64'),
 ('cp35', 'abi3', 'linux_x86_64'),
 ('cp34', 'abi3', 'linux_x86_64'),
 ('cp33', 'abi3', 'linux_x86_64'),
 ('cp32', 'abi3', 'linux_x86_64'),
 ('cp36', 'none', 'any'),
 ('cp3', 'none', 'any'),
 ('cp35', 'none', 'any'),
 ('cp34', 'none', 'any'),
 ('cp33', 'none', 'any'),
 ('cp32', 'none', 'any'),
 ('cp31', 'none', 'any'),
 ('cp30', 'none', 'any'),
 ('py3', 'none', 'linux_x86_64'),
 ('py36', 'none', 'any'),
 ('py3', 'none', 'any'),
 ('py35', 'none', 'any'),
 ('py34', 'none', 'any'),
 ('py33', 'none', 'any'),
 ('py32', 'none', 'any'),
 ('py31', 'none', 'any'),
 ('py30', 'none', 'any')]
```

**Comment by mihaimaruseac** [comment]
Unfortunately, no, we need to be manylinux2010 compatible if we want our pips to reside on PyPi.

Please update your pip via `python -m pip install --upgrade pip` or similar.

Closing this issue as there is a fix (upgrade pip) and there is no way to not use the `manylinux2010` tag.

**Comment by Ark-kun** [comment]
> we need to be manylinux2010 compatible if we want our pips to reside on PyPi.

Can you please elaborate a bit more on that or point me to the relevant document?
The official python [doc](https://packaging.python.org/specifications/platform-compatibility-tags/) just mentions that "manylinux2010 is not yet widely recognised by install tools." 
TF Model analysis does not publish `manylinux2010` wheels and neither does `numpy` (https://pypi.org/simple/numpy/), so I'm not sure what the issue is.

**Comment by reliefs** [comment]
Read more about it here

https://github.com/tensorflow/tensorflow/issues/32627

All the Google employees in this repo will not take your issue serious, pls avoid talking to them and only talk to core TensorFlow devs.

**Comment by mihaimaruseac** [comment]
Hi there @reliefs 

This issue has no relationship with 32 bits support. Please don't spam inadvertently.

**Comment by mihaimaruseac** [comment]
Pinging @gunan and @angersson for more details about manylinux2010 issue.

**Comment by mihaimaruseac** [comment]
Hi @Ark-kun 

Our manylinux1 wheels were incompatible since a long time ago, see for example #8802 and https://github.com/tensorflow/tensorflow/issues/5033#issuecomment-263681255

In the end, it all boils down to the standard C/C++ library used to provide symbols in precompiled code that is then used by Python. Maybe the other packages you mentioned above don't run into these issues.

Regarding the need to update tag to stay on PyPi, see https://github.com/pypa/warehouse/issues/5420
