### ISSUE TITLE
How to find <Python.h> ? compile with bazel will fail not find Python.h

### ISSUE THREAD

**Issue by chenghuige** [tensorflow/tensorflow#327]
INFO: Found 1 target...
INFO: From Compiling tensorflow/python/client/tf_session_helper.cc:
In file included from tensorflow/python/client/tf_session_helper.cc:16:0:
./tensorflow/python/client/tf_session_helper.h:19:20: fatal error: Python.h: No such file or directory
 #include <Python.h>

Acutally I have Python.h in   /SomePath/python2.7/
But how to tell bazel ? I tried
export CPLUS_INCLUDE_PATH= /SomePath/python2.7/
Still not work, any suggestions ?

**Comment by ebrevdo** [comment]
See #187.  I think for now you can modify this line:

https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/BUILD#L702

to point to your python headers folder.  Please confirm this works for you.  We're working on a fix.

**Comment by chenghuige** [comment]
Well seems not work for me. Looks like due to I install bazel as root user ? 
But  ./bazel-0.1.1-installer-linux-x86_64.sh seems only can be installed using root user.

bazel build -c opt //tensorflow/tools/pip_package:build_pip_package
WARNING: Sandboxed execution is not supported on your system and thus hermeticity of actions cannot be guaranteed. See http://bazel.io/docs/bazel-user-manual.html#sandboxing for more information. You can turn off this warning via --ignore_unsupported_sandboxing.
ERROR: /home/users/chenghuige/other/tensorflow/tensorflow/tensorflow.bzl:225:3: in cc_library rule //tensorflow/python:tf_session_helper: The include path '/home/users/chenghuige/.jumbo/include/python2.7' references a path outside of the execution root..
ERROR: /home/users/chenghuige/other/tensorflow/tensorflow/tensorflow.bzl:225:3: in cc_library rule //tensorflow/python:tf_session_helper: The include path '/home/users/chenghuige/.jumbo/include/python2.7' references a path outside of the execution root..
ERROR: Analysis of target '//tensorflow/tools/pip_package:build_pip_package' failed; build aborted.

**Comment by chenghuige** [comment]
Anyway, I just copied python2.7 to /usr/inlude path. 
And then will face PyArray_SHAPE not find problem, I took the work around as described in #109 
Now thie step is ok..
But after that

 bazel-bin/tensorflow/tools/pip_package/build_pip_package /tmp/tensorflow_pkg
Mon Nov 23 14:16:04 CST 2015 : === Using tmpdir: /tmp/tmp.MWtBU7R88K
/tmp/tmp.MWtBU7R88K /home/users/chenghuige/other/tensorflow
Mon Nov 23 14:16:04 CST 2015 : === Building wheel
usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help

error: invalid command 'bdist_wheel'

How to solve this?

**Comment by chenghuige** [comment]
Well, after  "pip install wheel" everything is fine.

**Comment by chenghuige** [comment]
Another thing, import tesnsorflow, seems not tensorflow.__version__ exists.

**Comment by ebrevdo** [comment]
@chenghuige we're working on providing something like tensorflow.version or tensorflow.__version__.

Looks like your other problem has been resolved, so I'm closing this issue.

**Comment by Michael-Jing** [comment]
I noticed that this issue is closed and the problem should be fixed, however, I encountered the same poblem today when trying to build tensorflow serving, and  the solution is set environment variables before running configure. The environment variable is:
PYTHON_INCLUDE_PATH
which sholud be set to where Python.h resides.

**Comment by lancedeng** [comment]
In my case on CentOS 7.2 (bazel-dist 0.5.3 and tensorflow v1.3.0-rc2), also met this issue, thanks for the sharing above, it did save time. 
BTW, after the related python libraries installed and PYTHON_INCLUDE_PATH exported, the Bazel needs to be recompiled to include the changes.
Following packages have been installed via yum before compiling bazel and tensorflow: java-1.8.0-openjdk-devel, patch, python-devel, python-psycopg2 and numpy.x86_64.

**Comment by claynerobison** [comment]
I also had this issue and resolved it by uninstalling bazel (which was installed system-wide) and reinstalling as --user.

**Comment by roastduck** [comment]
Same here, even after setting `PYTHON_INCLUDE_PATH` and re-compile bazel. Built with tensorflow at master (1521eeb) branch with bazel 0.14.0 and bazel 0.10.1.

**Comment by roastduck** [comment]
Solved it as follows: Do not fill in a soft link when `./configure` asks where your python is. Answer the real python location.

**Comment by oscarriddle** [comment]
@Michael-Jing 
I encountered the same issue when compiling the tensorflow-serving 1.7.
```
ERROR: /home/web_server/.cache/bazel/_bazel_web_server/7039d45003118564d66f2b06f1b7ea68/external/org_tensorflow/tensorflow/python/BUILD:4855:1: C++ compilation of rule '@org_tensorflow//tensorflow/python:framework/fast_tensor_util.so' failed (Exit 1)
bazel-out/k8-opt/genfiles/external/org_tensorflow/tensorflow/python/framework/fast_tensor_util.cpp:4:20: fatal error: Python.h: No such file or directory
 #include "Python.h"
                    ^
compilation terminated.
INFO: Elapsed time: 17.580s, Critical Path: 12.44s
FAILED: Build did NOT complete successfully
```
Even after setting the path to Python.h, the error still exists.
```
$ echo $PYTHON_INCLUDE_PATH
/home/web_server/dlpy72/py2.7/include/python2.7
$ ls $PYTHON_INCLUDE_PATH | grep Python
Python-ast.h
Python.h
```

**Comment by brave-hannah** [comment]
> Solved it as follows: Do not fill in a soft link when ./configure asks where your python is. Answer the real python location.
Thank you. Changing the /usr/bin/python3 to /usr/bin/python3.4m of configure path resolve my problem as I installed python3.4 in the centos7.

**Comment by TomorrowIsAnOtherDay** [comment]
> > Solved it as follows: Do not fill in a soft link when ./configure asks where your python is. Answer the real python location.
> 
> Thank you. Changing the /usr/bin/python3 to /usr/bin/python3.4m of configure path resolve my problem as I installed python3.4 in the centos7.

This does solve my problem in centos7. Thanks a lot.
