### ISSUE TITLE
Loading Multiple models into the same session of tensorflow

### ISSUE THREAD

**Issue by suraj1990** [tensorflow/tensorflow#3270]
I have trained two models. en-fr and fr-en models. The fr-en model has different vocab size compared to the en-fr model. The first model is being loaded properly. It crashes while loading the second one. I have trained both the models separately. Please check the log file attached to see the error logs. kindly tell me the right way to go ahead.

I want to create a webservice for en-rf and fr-en translation. I ahve to load the models in a session for this, which is causing the problem. below is the piece of code. I am using the translate.py provided by tensorflow and the methods available in it.

    `global en_fr_sess

     if en_fr_sess==None:
     en_fr_sess = tf.Session()

     global en_fr_model
     global en_fr_en_vocab_path
     global en_fr_fr_vocab_path

     en_fr_model = create_model(en_fr_sess, True)
     en_fr_model.batch_size = 1  
     fr_en_model = fr_en_create_model(en_fr_sess, True)
     fr_en_model.batch_size = 1`

I am able to run both the models separately and generate the translations. However, when I try to load both the models in the same session or even a different session one after the other, I get the following error

    `ValueError: Variable embedding_attention_seq2seq/RNN/EmbeddingWrapper/embedding already exists, disallowed. Did you mean to set reuse=True in VarScope? Originally defined at:`
    `File "/usr/local/lib/python2.7/dist-packages/tensorflow/models/rnn/translate/seq2seq_model.py", line 113, in seq2seq_f
    feed_previous=do_decode)`
    `File "/usr/local/lib/python2.7/dist-packages/tensorflow/models/rnn/translate/seq2seq_model.py", line 136, in <lambda>
    self.target_weights, buckets, lambda x, y: seq2seq_f(x, y, True),`
    `File "/usr/local/lib/python2.7/dist-packages/tensorflow/models/rnn/translate/seq2seq_model.py", line 137, in __init__
    softmax_loss_function=softmax_loss_function)`

Please find the detailed log file attached too. Kindly give me the inputs on how to proceed further. 
[out.txt](https://github.com/tensorflow/tensorflow/files/357036/out.txt)

**Comment by suraj1990** [comment]
@lukaszkaiser any inputs?

**Comment by lukaszkaiser** [comment]
As said in the other thread -- you want separate variables for each model. So you need to use "with tf.variable_scope(...)" before creating each model. And since you didn't do this before training, you'll have to re-name the variables you restore from the checkpoint. This can be done by passing a dict to the Saver object, rather than just a list of variables (as is done now). Let me know if you have more specific questions, I'll be happy to help, but here is the overview.

(0) Currently both your models are trying to share parameters, that's where the error comes from (they cannot share because vocab sizes are different, but it's just a consequence of a different problem: you don't want to share the variables, you want 2 separate sets of them).

(1) You cannot create 2 separate sets just with 2 sessions, you need to put them in variable_scopes. Just before calling create_model, open a scope, for example:
  with tf.variable_scope('en_fr'):
    en_fr_model = create_model(...)
  with tf.variable_scope('fr_en'):
    fr_en_model = create_model(...)

(2) Now you have 2 sets of variables, but their names don't correspond to the names you've saved in checkpoints during training, because your names are now prefixed with 'en_fr/' and 'fr_en/' and those in checkpoint are not. So you need to add some logic to the Saver object in the model to tell it to prefix the variables from the checkpoint in the right way. This can be done by passing a dict to the Saver, see [here](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/training/saver.py#L791)

**Comment by suraj1990** [comment]
Thanks for your quick response @lukaszkaiser 
my doubts may be very trivial but I will go ahead and ask.
I have trained two models. you rightly pointed out that I have not used tf.varaible_scope during the training stage. When you say I need to rename variables that I restore from the checkpoint, 

    `ckpt = tf.train.get_checkpoint_state(FLAGS.train_dir)
     if ckpt and tf.gfile.Exists(ckpt.model_checkpoint_path):
        print("Reading model parameters from %s" % ckpt.model_checkpoint_path)
        model.saver.restore(session, ckpt.model_checkpoint_path)
     else:
        print("Created model with fresh parameters.")
        session.run(tf.initialize_all_variables())
    return model`
     
This is the place where the restoring is done, from the trained model cptk file. What are all the variables that I need to rename? 

Also by using the tf.variable_scope(), will the variables be prefixed with the string given, en_fr or fr_en automatically. ?

is retraining both the models with tf.variable_scope a better option?

**Comment by suraj1990** [comment]
I trained two new models with fewer steps. While training the new models, I used with tf.variable_scope("en_fr") for en-fr translator and with tf.variable_scope("fr_en") for fr-en translator. 

For training : 
    `with tf.variable_scope('fr_en'):
      model = create_model(sess, False)`

    with tf.variable_scope('en_fr'):
      model = create_model(sess, False)

**Comment by lukaszkaiser** [comment]
I think what you did is good and you're almost there. The one problem you see is due to [this line](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/models/rnn/translate/seq2seq_model.py#L166). The Saver() object takes a list of variables, and it's tf.all_variables(), so it's trying to restore them all. While your checkpoint only has a subset of them (not the en_fr ones), so you get an error.

I think you can, for example, just create 2 savers and filter the variables to only include the relevant ones, e.g, `self.saver_en-fr = Saver([v for v in tf.all_variables() if 'en_fr' in v.name])`. And then call restore twice, on both savers. Hope that works, let me know!

**Comment by suraj1990** [comment]
With your inputs, I made the modifications in seq2seq_model.py 

    `all_vars = tf.all_variables()
    model_one_vars = [k for k in all_vars if k.name.startswith("en_fr")]
    model_two_vars = [k for k in all_vars if k.name.startswith("fr_en")]
    
    if not model_two_vars:
       self.saver_en_fr = tf.train.Saver(model_one_vars)
    else:
       self.saver_fr_en = tf.train.Saver(model_two_vars)`

in place of 
    `self.saver = tf.train.Saver(tf.all_variables())`

Things are working fine now. I have successfully loaded two models. Thanks a lot for your inputs :-)

**Comment by anguyen8** [comment]
Thanks to @lukaszkaiser and @suraj1990 , I've run into the same issue and the suggestion works for me.

**Comment by iamgroot42** [comment]
Does the variable scope method work when working with Keras? Even while using different variable scopes, the models seem to be sharing weights.

**Comment by lukaszkaiser** [comment]
When using objects, the idea is that same-object=shared-weights and different-objects=non-shared-weights. But it should be very simple to not share, just create the object twice. Or am I missing something?

**Comment by iamgroot42** [comment]
@lukaszkaiser that's what I did, but it doesn't seem to work. I have two models (in 2 different objects), A and B in the same session. Training only A gives 90% of so accuracy, while training B after A and then evaluating A gives less than random accuracy. This issue disappears when I run them in different threads, so it's probably something to do with two models in the same session (probably sharing weoghts of some layers).

**Comment by lukaszkaiser** [comment]
This sounds like a bug. Could you create a small test file where this problem appears and attach here, so we can reproduce and try to correct it? Thanks!

**Comment by chrisrn** [comment]
Same problem here. The restoration is working on both models but the results are bad. Take a look:

```
with tf.variable_scope('localization'):
            binarylogits, logits, softmax_weights, convoluted = inception.inference(images, num_classes, 
                                                                 restore_loc=True, restore_rec=False)  
        
with tf.variable_scope('recognition'):
            binarylogits, logits, softmax_weights, convoluted = inception.inference(images, num_classes, 
                                                                 restore_loc=False, restore_rec=True)

variables_to_restore = tf.get_collection(
            slim.variables.VARIABLES_TO_RESTORE)
loc_varlist = {v.name[13:][:-2]: v 
                        for v in variables_to_restore if v.name[:12]=='localization'}
rec_varlist = {v.name[12:][:-2]: v 
                        for v in variables_to_restore if v.name[:11]=='recognition'}
        
loc_saver = tf.train.Saver(var_list=loc_varlist)
rec_saver = tf.train.Saver(var_list=rec_varlist)
        
loc_saver.restore(sess, FLAGS.localization_model_checkpoint_path)
print('%s: Pre-trained model restored from %s' %
                    (datetime.now(), FLAGS.localization_model_checkpoint_path))

rec_saver.restore(sess, FLAGS.recognition_model_checkpoint_path)
print('%s: Pre-trained model restored from %s' %
                    (datetime.now(), FLAGS.recognition_model_checkpoint_path))
```

The localization model doesn't give the results I am receiving when I run it without the recognition model.

**Comment by chrisrn** [comment]
I updated the above code take a look. Finally the second model (recognition) cannot produce the right predictions, but in a script without the first model it works fine.

**Comment by Yuliang-Zou** [comment]
@chrisrn Have you fixed this problem?

**Comment by chrisrn** [comment]
@Yuliang-Zou  Yes finally it works. Probably there was a tensorflow bug in the past.

**Comment by Yuliang-Zou** [comment]
@chrisrn So you just updated the version of tensorflow, and it works now?

**Comment by Raj-08** [comment]
@suraj1990 @lukaszkaiser @anguyen8 @iamgroot42 @chrisrn 

I am facing the same issue.

I have trained two models separately . The output of 1st model is used as output of 2nd model . 
When i run the two models individually , i save the output of 1st model in a numpy array and then later feed that to 2nd model , results are as expected , but when i combine them in a single graph , the output of 2nd model is horrendously bad. I have made sure that there is no name conflict. 

Any advice on how anyone overcame this ?

Thanks

**Comment by Raj-08** [comment]
@iamgroot42 how did you run it on two threads?

**Comment by Raj-08** [comment]
@chrisrn how did it work?

**Comment by Raj-08** [comment]
which tensorflow version are you using?

**Comment by Raj-08** [comment]
@chrisrn Thanks man , but i have tried to restore it as you mentioned , but no luck .

**Comment by Raj-08** [comment]
i am using tensorflow version 1.4

**Comment by Raj-08** [comment]
@iamgroot42 had mentioned that the two models might be sharing same variables , i have checked all the variables in tf.global_variables () , there is no conflict i could find.

**Comment by chrisrn** [comment]
@Raj-08 The above technique with the scopes is referring to models that have the variables with the same names, so you are using the scopes to avoid that. If your models do not have same variable names then it's easier to load them. Pay attention on where you place the savers and also the variables that you feed to them!

**Comment by Raj-08** [comment]
`  with tf.Graph().as_default():

    C = tf.constant([0],shape=[30,30,1])

    D = tf.constant([0],shape=[40,40,1])
    input_image = tf.placeholder(tf.uint8, [1, None, None, 3], name=_INPUT_NAME)
    image_size = tf.shape(input_image)[1:3]
    image = tf.squeeze(input_image, axis=0)
    image = tf.expand_dims(image, 0)
    model_options = common.ModelOptions(
        outputs_to_num_classes={common.OUTPUT_TYPE: FLAGS.num_classes},
        crop_size=[481,481],
        atrous_rates=FLAGS.atrous_rates,
        output_stride=FLAGS.output_stride)
    with tf.variable_scope('segmentation'):
        if tuple(FLAGS.inference_scales) == (1.0,):
          tf.logging.info('Exported model performs single-scale inference.')
          predictions = model_deeplab.predict_labels(
              image,
              model_options=model_options,
              image_pyramid=FLAGS.image_pyramid)
        else:
          tf.logging.info('Exported model performs multi-scale inference.')
          predictions = model_deeplab.predict_labels_multi_scale(
              image,
              model_options=model_options,
              eval_scales=FLAGS.inference_scales,
              add_flipped_images=FLAGS.add_flipped_images)
   
    
        predictions = predictions['semantic']

        logits_deeplab = tf.scalar_mul(255,predictions)
        logits_deeplab = tf.squeeze(logits_deeplab)
        logits_deeplab = tf.expand_dims(logits_deeplab, axis=0)
        logits_deeplab = tf.expand_dims(logits_deeplab, axis=3)
        eroded = tf.nn.erosion2d(tf.cast(logits_deeplab,dtype=tf.int32),C,[1,1,1,1],[1,1,1,1],'SAME')

        dilated = tf.nn.dilation2d(tf.cast(logits_deeplab,dtype=tf.int32),D,[1,1,1,1],[1,1,1,1],'SAME')



        dilated =  tf.where(tf.equal(dilated,255),tf.fill([1,481,481,1],127),dilated)

        trimap =  tf.where(tf.equal(eroded,255),tf.fill([1,481,481,1],255),dilated)
        trimap_inp = tf.concat([tf.cast(image,dtype=tf.float32),tf.cast(trimap,dtype=tf.float32)],axis=3,name='new')
        model_options = common.ModelOptions(
        outputs_to_num_classes={common.OUTPUT_TYPE: 64},
        crop_size=[481,481],
        atrous_rates=[12,24,36],
        output_stride=FLAGS.output_stride)
    mod_vars = tf.model_variables()
    print('l1',len(mod_vars))
    with tf.variable_scope('matting'):
        logits= model.multi_scale_logits(
              trimap_inp,
              model_options=model_options,
              image_pyramid = [1.0])
        
        mod_vars = tf.model_variables()
        print('l2',len(mod_vars))
        all_trainables = tf.trainable_variables()
        logits=logits['semantic']
        logits_p=logits['merged_logits_matting'] 
        upsample_logits=True
        logits_p=upsample_layer(logits_p,64,'up_matting',upscale_factor=4)
        print('LP',logits_p)
        logits_p = create_new_conv_layer(logits_p,64,1,'pred')
        deeplab_op_255 = tf.scalar_mul(255.0,logits_p)
        concat_inp = tf.concat([tf.cast(image,dtype=tf.float32),deeplab_op_255],axis=3)
        conv1 = create_new_conv_layer(concat_inp,4,64,'conv1')
        conv2 = create_new_conv_layer(conv1,64,64,'conv2')
        conv3 = create_new_conv_layer(conv2,64,64,'conv3')
        logits_al = create_new_conv_layer(conv3,64,1,'pred1')
        logits_al = tf.nn.sigmoid(logits_al)
    variables_to_restore = tf.get_collection(
            tf.GraphKeys.MODEL_VARIABLES)
    print(len(variables_to_restore))

    loc_varlist = {v.name[13:][:-2]: v 
                        for v in variables_to_restore if v.name[:12]=='segmentation'}
    rec_varlist = {v.name[8:][:-2]: v 
                        for v in variables_to_restore if v.name[:7]=='matting'}
    print('L1',len(loc_varlist))
    print('L2',len(rec_varlist))
    f = open('/home/ubuntu/all_data_seg/train_mat_25_08.txt')
    message = f.read()
    lines = message.split('\n')

    saver_restore_1 = tf.train.Saver(loc_varlist)   
    saver_restore_2 = tf.train.Saver(rec_varlist)`

**Comment by Raj-08** [comment]
Here is my code , tried eveything , doesnt seem to work !

**Comment by GarimaZe** [comment]
While loading multiple trained files i am facing this issue.

ValueError: Variable character_embedding_en/character_embedding_weights_en already exists, disallowed. Did you mean to set reuse=True or reuse=tf.AUTO_REUSE in VarScope? 
Even though i have autonmated the model for different language (as i have to train for 3 -4 languages) and have done whatever was recommended, but i am till facing this issue. It would be great if someone could just help me here. 
Thank you in advance :)

[entity_lstm.zip]
(https://github.com/tensorflow/tensorflow/files/6606424/entity_lstm.zip)
