### ISSUE TITLE
GPU never in use with Java API

### ISSUE THREAD

**Issue by itsucks** [tensorflow/tensorflow#32706]
Hi, I followed the instructions with (this)(https://www.tensorflow.org/install/lang_java?hl=zh-cn).
And I add my implementations with bert pb model, but the GPUs are never used
![image](https://user-images.githubusercontent.com/7105813/65370990-769ed480-dc91-11e9-80db-244ed652ff9d.png).
I got Tesla K80, and cuda 9.0 
![image](https://user-images.githubusercontent.com/7105813/65371023-bd8cca00-dc91-11e9-98e2-74f53302ed3e.png)
![image](https://user-images.githubusercontent.com/7105813/65371031-e0b77980-dc91-11e9-8b45-3a2a8746b0bf.png)

Any suggestions?

**Comment by gadagashwini** [comment]
@itsucks,
Provide the exact sequence of commands / steps that you executed before running into the problem. Thanks!

**Comment by itsucks** [comment]
> @itsucks,
> Provide the exact sequence of commands / steps that you executed before running into the problem. Thanks!

Well. the system is CentOS Linux release 7.2.1511,
I add the dependency with maven  

![image](https://user-images.githubusercontent.com/7105813/65474401-408a6c00-deae-11e9-94fc-e5a63eb5a632.png)  

the code  
![image](https://user-images.githubusercontent.com/7105813/65474446-7596be80-deae-11e9-8d63-116a35d1c7c0.png)  

the results are right, but it never use the GPU
The whole platform works fine in python

**Comment by itsucks** [comment]
the command is `mvn -q compile exec:java`

**Comment by yangxudong** [comment]
Is your problem fixed?  how ?
