### ISSUE TITLE
Reset tf.metrics.mean

### ISSUE THREAD

**Issue by wzm2256** [tensorflow/tensorflow#32705]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using):1.8
- Are you willing to contribute it (Yes/No):yes

**Describe the feature and the current behavior/state.**
Current usage:
m, op_update = tf.metrics.mean(x)
m is the mean of the stream of x. op_update is the update op of local variable "count" and "total".

However, it's natural to reset all history of the stream, that is, to reset "count" and "total" to 0. It could look like:
m, op_update, op_reset = tf.metrics.mean(x).

**Will this change the current api? How?**
Yes, tf.metrics.mean will have one more output variable.
Maybe other tf.metrics functions should be alike.

**Who will benefit with this feature?**
I think this feature is natural.
For example, those who need to measure the mean accuracy in every 20 iterations, all accuracy 
data before these 20 iterations should be discarded.

**Any Other info.**

**Comment by ravikyram** [comment]
Do you have any use case that requires the feature you are interested in? Please feel free to submit a PR if you have use cases that supports that feature.Thanks!

**Comment by wzm2256** [comment]
I decide to close the issue, because I've thinked about it, maybe it's not a good ideal to change the output of a function, that will cause an error for all older versions. Altough this feature is quite natural: just like all calculators has a 'clear' button.

For anyone who read this. This 'reset' operation can be easily done outside a session without using tf.metrics.mean, although using it within a session with tf.summary would be more elegant.
