### ISSUE TITLE
Keras casts targets to incorrect dtype

### ISSUE THREAD

**Issue by drasmuss** [tensorflow/tensorflow#32702]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.0.0rc1
- Python version: 3.6.8
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

**Describe the current behavior**

Keras tries to cast targets to the dtypes of the model outputs. Currently it assumes that every model output has a corresponding target, so when doing this casting it just matches outputs and targets up one-to-one. But in the case where some outputs are not part of the loss function (i.e. they were missing from the loss dictionary passed to `compile`), this may match outputs to the wrong targets. Then it casts targets to the wrong dtype, causing errors.

**Describe the expected behavior**

Keras should match up targets with the correct output when casting, according to the loss dictionary defined in `compile`.  If a model output is not part of the loss function, then it should be ignored when casting targets.

**Code to reproduce the issue**

``` python
import tensorflow as tf
import numpy as np

inp = tf.keras.layers.Input(shape=(1,))
out0 = tf.cast(inp, tf.int32)
out1 = tf.cast(inp, tf.float64)

model = tf.keras.Model(inputs=inp, outputs=[out0, out1])

model.compile(loss={model.output_names[1]: tf.losses.mse})

model.evaluate(
    np.ones((1, 1), dtype=np.float32),
    {model.output_names[1]: np.ones((1, 1), dtype=np.float32)},
)
```

This results in the error
```
TypeError: Value passed to parameter 'x' has DataType int32 not in list of allowed values: float16, float32, float64, complex64, complex128
```

**Comment by drasmuss** [comment]
Haven't had a chance to look into this in detail, but it might be fixed by adding
```
outs = [out for out, e in zip(outs, model._training_endpoints) if not e.should_skip_target()]
```
here https://github.com/tensorflow/tensorflow/blob/r2.0/tensorflow/python/keras/engine/training_eager.py#L129

**Comment by oanush** [comment]
Issue replicating for TF-2.0rc1, please find the [gist](https://colab.sandbox.google.com/gist/oanush/b796d39a08fb5c287034ece6853834d3/32702.ipynb) of colab.Thanks!

**Comment by joshz123** [comment]
Is this issue still open?

**Comment by jvishnuvardhan** [comment]
@drasmuss can you please check this issue with `tf-nightly`. When I ran your code with `tf-nightly`, i see the following output.

```
1/1 [==============================] - 0s 1ms/step - loss: 0.0000e+00 - tf_op_layer_Cast_1_loss: 0.0000e+00
[0.0, 0.0]
```

Please close the issue if this issue was resolved for you. Thanks!

**Comment by drasmuss** [comment]
Yep looks like this is fixed in `tf-nightly`.
