### ISSUE TITLE
Segmentation Fault (core dumped) while training on 1.14

### ISSUE THREAD

**Issue by allangelman** [tensorflow/tensorflow#32701]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Running a public github repo
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04.2 LTS
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): 1.14.0
- TensorFlow version (use command below): 1.14.0
- Python version: 2.7
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: N/A
- GPU model and memory: NVIDIA TITAN

**Describe the current behavior**

I am attempting to train the neural network in this repo, [sketch2normal](https://github.com/Ansire/sketch2normal)

Every time I attempt to train the model, it always gives me an error message `Segmentation fault (core dumped)` at Epoch 0 sometime between 10/449 -  90/449. I'm also getting many warning messages saying that many of the methods being called, like `tf.summary.FileWriter`, `tf.summary.merge`, and more are deprecated.  

After attempting to train with multiple print statements, I found that the place where the code seg faults is in the train function:
```
      def train(self, args):

        self.d_optim = tf.train.RMSPropOptimizer(learning_rate=args.lr).minimize(self.d_loss, var_list=self.d_vars)
        self.g_optim = tf.train.RMSPropOptimizer(learning_rate=args.lr).minimize(self.g_loss, var_list=self.g_vars)
        self.clip_d_vars_ops = [val.assign(tf.clip_by_value(val, -self.clamp, self.clamp)) for val in self.d_vars]
        tf.global_variables_initializer().run()

        init_op = tf.global_variables_initializer()
        self.sess.run(init_op)

        self.g_summary = tf.summary.merge([self.fake_B_sum, self.real_B_sum,self.d_loss_fake_sum, self.g_loss_sum])
        self.d_summary = tf.summary.merge([self.d_loss_real_sum, self.d_loss_sum])
        self.visual_loss_summary = tf.summary.merge([self.pixel_wised_loss_sum, self.masked_loss_sum])
        self.writer = tf.summary.FileWriter("./logs", self.sess.graph)

        counter = 1
        start_time = time.time()

        if self.load(args.checkpoint_dir):
            print(" [*] Load SUCCESS")
        else:
            print(" [!] Load failed...")

        for epoch in xrange(args.epoch):
            data = glob('./datasets/{}/train/*.png'.format(self.dataset_name))
            np.random.shuffle(data)
            batch_idxs = min(len(data), 1e8) // (self.batch_size*self.n_critic)
            print('[*] run optimizor...')

            for idx in xrange(0, batch_idxs):
                errD=.0
                batch_list = [self.load_training_imgs(data, idx+i) for i in xrange(self.n_critic)]
                for j in range(self.n_critic):
                    batch_images = batch_list[j]
                    _, errD, errd_real, errd_fake, errVis_sum, summary_str = self.sess.run([self.d_optim, self.d_loss,
                                                                                self.d_loss_real, self.d_loss_fake,
                                                                                            self.visual_loss_summary,
                                                                                            self.d_summary],
                                                                                           feed_dict={self.real_data: batch_images})
                    self.sess.run(self.clip_d_vars_ops)
                    self.writer.add_summary(summary_str, counter)
                    self.writer.add_summary(errVis_sum, counter)

                # Update G network
                _, errG, summary_str = self.sess.run([self.g_optim, self.g_loss, self.g_summary],
                                               feed_dict={self.real_data: batch_list[np.random.randint(0, self.n_critic, size=1)[0]]})
                self.writer.add_summary(summary_str, counter)

                current = time.time()
                print("Epoch: [%2d] [%4d/%4d] time: %4.4f, d_loss: %.8f, g_loss: %.8f" \
                      % (epoch, idx, batch_idxs, current - start_time, errD, errG))
                start_time = current

                if np.mod(counter, 100) == 1:
                    self.sample_model(args.sample_dir, epoch, idx)

                if np.mod(counter, 1000) == 2:
                    self.save(args.checkpoint_dir, counter)
                counter += 1
```

Specifically on this line, where self.sess.run is called:
```
                    _, errD, errd_real, errd_fake, errVis_sum, summary_str = self.sess.run([self.d_optim, self.d_loss,
                                                                                self.d_loss_real, self.d_loss_fake,
                                                                                            self.visual_loss_summary,
                                                                                            self.d_summary],
                                                                                           feed_dict={self.real_data: batch_images})
```
**Describe the expected behavior**
The expected behavior is that it would finish training. Can you provide any recommendations as to how to stop it from seg faulting during training (and why it stops at a different point each time)? I'm wondering if the warnings could have to do with it?  I also have seen other people online having issues with tf.Session, so I'm wondering if that could be it?

**Comment by gadagashwini** [comment]
@allangelman,
In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thanks!

**Comment by mihaimaruseac** [comment]
I would also suggest to try on 1.15 or 2.0 instead of 1.14

**Comment by allangelman** [comment]
> @allangelman,
> In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thanks!

I just updated my comment with the link to the repo I am trying to run, and the code snippet where I know it is seg faulting! Thank you!

**Comment by gadagashwini** [comment]
@allangelman,
Please provide the simple standalone code to replicate the issue and indeed it will help us to move faster. Thanks!

**Comment by allangelman** [comment]
Thank you for all the help! I was able to resolve the issue! The problem was that I hadn't installed the tensorflow-gpu package, so the entire time I was actually not even using my GPU! Running `nvidia-smi` helped me figure this out, as I was able to see the usage of my GPU.

**Comment by mihaimaruseac** [comment]
Closing as issue is fixed
