### ISSUE TITLE
module 'tensorflow' has no attribute 'enable_eager_execution'

### ISSUE THREAD

**Issue by iperov** [tensorflow/tensorflow#32708]
I installed *tensorflow-gpu==2.0.0rc1* from pip

```
>>> tf.enable_eager_execution()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'tensorflow' has no attribute 'enable_eager_execution'
```

**Comment by mihaimaruseac** [comment]
Eager execution is enabled by default in 2.0 and onwards, hence the symbol to enable it is no longer needed nor provided.

**Comment by witoldszejgis** [comment]
You use enable_eager_execution with earlier versions of tensorflow

**Comment by induraj2020** [comment]
Put these lines at the starting of the program
import tensorflow as tf
tf.enable_eager_execution()
tf.executing_eagerly()

**Comment by iperov** [comment]
I am working with deep learning frameworks for 2 years.
And I am saying 

GRAPH SYSTEM IS THE BEST.

pytorch sucks and only good for research.
So I cannot understand why to copy pytorch and enabling eager by default.
