### ISSUE TITLE
About FGSM implementation in the tutorial

### ISSUE THREAD

**Issue by Catminusminus** [tensorflow/tensorflow#32715]
## URL(s) with the issue:

https://www.tensorflow.org/beta/tutorials/generative/adversarial_fgsm
## Description of issue (what needs changing):

The FGSM  implementaiton in the documentation seems to be incorrect.

### Clear description

In the doc, `image_probs` which is equal to the value `model.predict(image)`,  is used to calculate the perturbation.
```python
perturbations = create_adversarial_pattern(image, image_probs)
```

The `create_adversarial_pattern` function takes `input_image` and `input_label`. So the above code is the same as the blow code.
```python
perturbations = create_adversarial_pattern(input_image=image, input_label=model.predict(image))
```

However, `input_label` must be not the predicted _probability_ of the model, but the (one hot encoded) correct _label_ of input_image, I think. In fact, it is calculated that
```python
prediction = pretrained_model(input_image)
loss = loss_object(input_label, prediction)
```
in the `create_adversarial_pattern` function.

Sorry if I have misunderstood.

ref. "EXPLAINING AND HARNESSING ADVERSARIAL EXAMPLES," https://arxiv.org/pdf/1412.6572.pdf, p3.

### ### Submit a pull request?
If my understanding is correct, I will submit a PR. But I do not have confidence that my understanding is correct yet.

**Comment by MarkDaoust** [comment]
You're right about the error.

> Submit a pull request?

Yes please.
