### ISSUE TITLE
Ussage via JNI (libtensorflow-1.14.0.jar+libtensorflow-src.jar+tensorflow_jni.dll)  JDK=1.8

### ISSUE THREAD

**Issue by Yrij-Zhavoronkov** [tensorflow/tensorflow#32713]
Hello! Append lib (libtensorflow-1.14.0.jar) as User library on Eclipse, include libtensorflow-src.jar as source for this user lib, try to build examle and java take me:
`Exception in thread "main" java.lang.UnsatisfiedLinkError: Cannot find TensorFlow native library for OS: windows, architecture: x86_64.`

why resoure name is `org/tensorflow/native/windows-x86_64/tensorflow_jni.dll`?

Note: 
libtensorflow-1.14.0.jar+libtensorflow-src.jar+tensorflow_jni.dll  in project folder.

WTD?

**Comment by gadagashwini** [comment]
@Yrij-Zhavoronkov,
Provide the exact sequence of commands / steps that you executed before running into the problem. Thanks!

**Comment by Yrij-Zhavoronkov** [comment]
1) Go to: https://www.tensorflow.org/install/lang_java and download libtensorflow.jar and Java Native Interface (JNI) file, save it to project root
2) In Eclipse:  Menu of project -> build Path -> Configure -> Libraries
3) Create new user lib, set libtensorflow-1.14.0.jar as jar for lib, Apply, Finish,
3) Copy Example code from https://www.tensorflow.org/install/lang_java and try to run/debug

**Comment by Yrij-Zhavoronkov** [comment]
Any ideas?
