### ISSUE TITLE
Reverse for complex numbers

### ISSUE THREAD

**Issue by el3ment** [tensorflow/tensorflow#3271]
tf.reverse does not seem to be implemented for complex numbers

```
w_real = tf.Variable(tf.truncated_normal([10], stddev=0.1, dtype=tf.float32))
w_imag = tf.Variable(tf.truncated_normal([10], stddev=0.1, dtype=tf.float32))
w = tf.complex(w_real, w_imag)
w_rev = tf.reverse(w, [True])
```

I came across this needing to construct a matrix that is conjugate symmetric, but this was also referenced on StackOverflow : [http://stackoverflow.com/questions/38145235/why-cant-i-reverse-a-sequence-of-complex-numbers-in-tensorflow](http://stackoverflow.com/questions/38145235/why-cant-i-reverse-a-sequence-of-complex-numbers-in-tensorflow)

**Comment by sjperkins** [comment]
Related to https://github.com/tensorflow/tensorflow/issues/2577 which tracks general support for complex numbers in tensor transformation functions.

**Comment by ibab** [comment]
I've enabled `reverse` for complex numbers in #3281, so this can be closed if everyone agrees.
