### ISSUE TITLE
How to avoid tensorflow@gpu copy outputs to cpu?

### ISSUE THREAD

**Issue by lovickie** [tensorflow/tensorflow#32726]
I use tensorflow 1.7.0 at gpu. I call Session::Run function, the inputs Tensor is already gpu Tensor, so input and forward calculate is well. But before output, I see that every outputs has been copied from gpu to cpu, and this is not what I hope. I just want the outputs are all gpu Tensor. How can I do?

```
// tensorflow/core/public/session.h
class Session {
...
  virtual Status Run(const std::vector<std::pair<string, Tensor> >& inputs,
                     const std::vector<string>& output_tensor_names,
                     const std::vector<string>& target_node_names,
                     std::vector<Tensor>* outputs) = 0;
...
};
```

**Comment by lovickie** [comment]
the outputs, include target and gradients. MEMCPYDtoH in tensorflow is slow very much, so we hope outputs is gpu Tensors. But I don't know how to ...

**Comment by lovickie** [comment]
I try MakeCallable/RunCallable in tensorflow 1.14, but the sad story is:

```
tf session MakeCallable failed, errormsg:Cannot feed or fetch tensor '4_d/fc/bias:0' from device /job:localhost/replica:0/task:0/device:GPU:0 as feeding/fetching from GPU devices is not yet supported for float_ref tensors
```

Then I see https://github.com/tensorflow/tensorflow/issues/5902

Can anyone help me ?

**Comment by lovickie** [comment]
> DT_FLOAT_REF

Then I change output, the result changed to 

```
Cannot feed or fetch tensor 'Placeholder:0' from device /job:localhost/replica:0/task:0/device:GPU:0 as feeding/fetching from GPU devices is not yet supported for int32 tensors
```

**Comment by lovickie** [comment]
> > I try MakeCallable/RunCallable in tensorflow 1.14, but the sad story is:
> > ```
> > tf session MakeCallable failed, errormsg:Cannot feed or fetch tensor '4_d/fc/bias:0' from device /job:localhost/replica:0/task:0/device:GPU:0 as feeding/fetching from GPU devices is not yet supported for float_ref tensors
> > ```
> > 
> > 
> > Then I see #5902
> > Can anyone help me ?
> 
> And, intput tensors data type is tensorflow::DT_FLOAT, not tensorflow::DT_FLOAT_REF

I found that _REF is because variable definition (fc/bias, fc/kernel, etc), even thought I don't put them into output...

**Comment by alextp** [comment]
The issue you're seeing is because of ref variables. Instead of fetching ref variables, fetch the result of tf.identity(ref_variable) (or use tf.enable_resource_variables() when building your graph to stop using the deprecated ref variables).

**Comment by JadeRay** [comment]
When I call session MakeCallable, same message comes out. Seems like TensorFlow disallow feeding Variable from gpu device?
