### ISSUE TITLE
model.ckpt-180000.data-00000-of-00001.tempstate5599057054002993368 appeared

### ISSUE THREAD

**Issue by bit-pku-zdf** [tensorflow/tensorflow#32723]
I am running a image resnet152 model in imagenet dataset, However, when 18W step, a strange file named model.ckpt-180000.data-00000-of-00001.tempstate5599057054002993368 appeared, then my validation is wrong like  

OP_REQUIRES failed at save_restore_v2_ops.cc:134 : Unknown: output/checkpoint/model.ckpt-180000.data-00000-of-00001.tempstate5599057054002993368; Input/output error .

It troubled me many days , is there anyone meet the same problem? hope someone can help me. thank you!!

**Comment by ymodak** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.
