### ISSUE TITLE
1.15.0 release candidates missing from Docker Hub

### ISSUE THREAD

**Issue by berendo** [tensorflow/tensorflow#32736]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): N/A
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): N/A
- TensorFlow version: 1.15.0-rc1
- Python version: Python 2 or 3
- Installed using virtualenv? pip? conda?: N/A
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

**Describe the problem**

There does not appear to be a tagged container which matches the `1.15.0-rc1` (or _any_ `1.15`) release at https://hub.docker.com/r/tensorflow/tensorflow.

**Provide the exact sequence of commands / steps that you executed before running into the problem**

I navigated to https://hub.docker.com/r/tensorflow/tensorflow/tags and entered 1.15 into the "Filter Tags" search box as illustrated [here](https://hub.docker.com/r/tensorflow/tensorflow/tags?page=1&name=1.15). I understand that _currently_ the `nightly-` builds are based on `1.15.0-devX`, but I would have expected there to be a specific tag for the release candidate (like there is for 2.0.0).

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by angerson** [comment]
Thanks for reporting this! We have automation to build our new images automatically; since TF 2.0 is the "newest", these images weren't being triggered properly. I've verified that the 1.15rc1 images are now available as intended.

**Comment by berendo** [comment]
Thank you, @angerson!

**Comment by patzm** [comment]
@angerson: quick ping regarding the latest 1.15 release. Was this also skipped due to latest pointing to 2.0?
