### ISSUE TITLE
Failed to load delegate from libedgetpu.so.1.0 with tflite_runtime 1.14

### ISSUE THREAD

**Issue by Namburger** [tensorflow/tensorflow#32743]
**System information**
- Have I written code (based on the docs):
```
from tflite_runtime.interpreter import Interpreter
from tflite_runtime.interpreter import load_delegate
model_path='my_compiled_model.tflite'
interpreter = Interpreter(model_path,
  experimental_delegates=[load_delegate('libedgetpu.so.1.0')])
```
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
```
  Operating System: Ubuntu 18.04.3 LTS
            Kernel: Linux 4.15.0-60-generic
      Architecture: x86-64
```
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: laptop
- TensorFlow installed from (source or binary):
`pip3 install tflite_runtime-1.14.0-cp36-cp36m-linux_x86_64.whl`
- TensorFlow version (use command below): tflite_runtime 1.14
- Python version: `Python 3.6.5 :: Anaconda, Inc.`
- Bazel version (if compiling from source): n/a
- GCC/Compiler version (if compiling from source): n/a
- CUDA/cuDNN version: n/a
- GPU model and memory: n/a

This is the code that I ran:
```
from tflite_runtime.interpreter import Interpreter
from tflite_runtime.interpreter import load_delegate
model_path='my_compiled_model.tflite'
interpreter = Interpreter(model_path,
  experimental_delegates=[load_delegate('libedgetpu.so.1.0')])
```
following this tutorial:
https://www.tensorflow.org/lite/guide/python

This was working before, but somehow broken with this error:
```
Traceback (most recent call last):
  File "/home/nam/anaconda3/lib/python3.6/site-packages/tflite_runtime/interpreter.py", line 165, in load_delegate
    delegate = Delegate(library, options)
  File "/home/nam/anaconda3/lib/python3.6/site-packages/tflite_runtime/interpreter.py", line 119, in __init__
    raise ValueError(capture.message)
ValueError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "evaluate_edgetpu_cifar10.py", line 51, in <module>
    interpreter = Interpreter(file_name,experimental_delegates=[load_delegate('libedgetpu.so.1.0')])
  File "/home/nam/anaconda3/lib/python3.6/site-packages/tflite_runtime/interpreter.py", line 168, in load_delegate
    library, str(e)))
ValueError: Failed to load delegate from libedgetpu.so.1.0
```
I have been messing around a lot with my machine since by installing different versions of tf. But for the purpose of using the tflite_runtime.interpreter's load_delegate function, shouldn't just the pip install works? 
Very weird behavior :/
also I do have `libedgetpu.so.1.0` installed here:
```
% ls /usr/lib/x86_64-linux-gnu/libedgetpu.so.1.0
/usr/lib/x86_64-linux-gnu/libedgetpu.so.1.0
```

Thanks in advance for the help!

**Comment by EdjeElectronics** [comment]
Hi @Namburger , I had the same issue!

Make sure your Coral USB Accelerator is plugged in when you run your code. If the USB Accelerator isn't plugged in when you call the 'load_delegate' function, it will result in that error. If it IS plugged in, that error won't occur.

**Comment by programmer290399** [comment]
I am facing the same issue , even when the USB accelerator is plugged in and the LED in it is shining bright ........

**Comment by Namburger** [comment]
@EdjeElectronics wow... you were correct... thanks.

**Comment by profintegra** [comment]
I'm facing the same issue (with exactly the same error trace), but with PCI version of the Coral with M.2 B+M connector.
Followed the instructions
https://coral.withgoogle.com/docs/m2/get-started/

`lspci -x | grep 089a`
shows:
`0a:00.0 Non-VGA unclassified device: Device 1ac1:089a`

the `/dev/apex_0` is present.

Ubuntu 18.4 
`uname -a` 
`Linux 4.18.20-041820-generic #201812030624 SMP Mon Dec 3 11:25:55 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by Namburger** [comment]
> I am facing the same issue , even when the USB accelerator is plugged in and the LED in it is shining bright ........
@programmer290399 you might need to add your linux user to plugdev group:
```
$ sudo usermod -aG plugdev [your username]
```

**Comment by krishna-nag** [comment]
> > I am facing the same issue , even when the USB accelerator is plugged in and the LED in it is shining bright ........
> 
> @programmer290399 you might need to add your linux user to plugdev group:
> 
> ```
> $ sudo usermod -aG plugdev [your username]
> ```

I plugged in the device, and I did this too, it still is showing the same error. I am using ubuntu installed on a virtualbox in Mac. The USB device is getting attached, but load_delegate is giving error

**Comment by Namburger** [comment]
@krishna-nag ahh, I see, most likely the usb device isn't detected in your VM. Possibly this will help: https://dev.to/kojikanao/coral-edgetpu-usb-with-virtualbox-57e1

**Comment by jiayiliu** [comment]
I got the same problem in native Ubuntu.  Reboot helps.

**Comment by cruzzer** [comment]
There where two issues that needed resolving on my setup, coming from a fresh installed Pi 4 + fresh installed edge TPU.

1. A udev rules needs to be added for the TPU, which according to the "[Getting Started](https://coral.ai/docs/accelerator/get-started/#3-run-a-model-using-the-tensorflow-lite-api)" page should have happened when installing the libedgetpu1-* package.
```
/etc/udev/rules.d/99-edgetpu-accelerator.rules
SUBSYSTEM=="usb",ATTRS{idVendor}=="1a6e",GROUP="plugdev"
SUBSYSTEM=="usb",ATTRS{idVendor}=="18d1",GROUP="plugdev"
```

2. The user needs to be part of the plugdev group as mentioned by @Namburger .
`  sudo usermod -aG plugdev [your username]`

This seems to be a bug with the libedgetpu1-* packages. I tried both -std and -max versions (v12-1).

**Comment by adr-arroyo** [comment]
Thanks @cruzzer for the suggestions!

Does anyone have tried to use the TPU with a program in a Docker container?
I am getting the same `Failed to load delegate from libedgetpu.so.1.0` error when running my docker container.

**Comment by Namburger** [comment]
@adr-arroyo you can check this out :)
https://github.com/google-coral/tflite/issues/3#issuecomment-547942348

**Comment by Wonfee** [comment]
OS env:
======
# lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.6 LTS
Release:	14.04
Codename:	trusty

# python3 -V
Python 3.5.3

runtime error message:
==================
# python3 coral/tflite/python/examples/classification/classify_image.py --model edgetpu/classify/models/output_tflite_graph_edgetpu.tflite --labels edgetpu/classify/models/labels.txt --input edgetpu/classify/flower.jpg 
Traceback (most recent call last):
  File "e-AI/coral/tflite/python/examples/classification/classify_image.py", line 118, in <module>
    main()
  File "e-AI/coral/tflite/python/examples/classification/classify_image.py", line 95, in main
    interpreter = make_interpreter(args.model)
  File "e-AI/coral/tflite/python/examples/classification/classify_image.py", line 69, in make_interpreter
    {'device': device[0]} if device else {})
  File "/usr/local/lib/python3.5/dist-packages/tflite_runtime/interpreter.py", line 165, in load_delegate
    delegate = Delegate(library, options)
  File "/usr/local/lib/python3.5/dist-packages/tflite_runtime/interpreter.py", line 89, in __init__
    self._library = ctypes.pydll.LoadLibrary(library)
  File "/usr/lib/python3.5/ctypes/__init__.py", line 425, in LoadLibrary
    return self._dlltype(name)
  File "/usr/lib/python3.5/ctypes/__init__.py", line 347, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /usr/lib/x86_64-linux-gnu/libedgetpu.so.1: symbol _ZTTNSt7__cxx1119basic_ostringstreamIcSt11char_traitsIcESaIcEEE, version GLIBCXX_3.4.21 not defined in file libstdc++.so.6 with link time reference
Exception ignored in: <bound method Delegate.__del__ of <tflite_runtime.interpreter.Delegate object at 0x7f7a5ff57438>>
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/tflite_runtime/interpreter.py", line 124, in __del__
    if self._library is not None:
AttributeError: 'Delegate' object has no attribute '_library'

checked as below:
==============
# strings /usr/lib/x86_64-linux-gnu/libedgetpu.so.1.0 |grep GLIBCXX
GLIBCXX_3.4
GLIBCXX_3.4.11
GLIBCXX_3.4.21
GLIBCXX_3.4.9
GLIBCXX_3.4.14
GLIBCXX_3.4.15
GLIBCXX_3.4.18
GLIBCXX_3.4.17
GLIBCXX_3.4.5
GLIBCXX_3.4.20
GLIBCXX_3.4.19

# strings /usr/lib/x86_64-linux-gnu/libstdc++.so.6 |grep GLIBCXX
GLIBCXX_3.4
GLIBCXX_3.4.1
GLIBCXX_3.4.2
GLIBCXX_3.4.3
GLIBCXX_3.4.4
GLIBCXX_3.4.5
GLIBCXX_3.4.6
GLIBCXX_3.4.7
GLIBCXX_3.4.8
GLIBCXX_3.4.9
GLIBCXX_3.4.10
GLIBCXX_3.4.11
GLIBCXX_3.4.12
GLIBCXX_3.4.13
GLIBCXX_3.4.14
GLIBCXX_3.4.15
GLIBCXX_3.4.16
GLIBCXX_3.4.17
GLIBCXX_3.4.18
GLIBCXX_3.4.19
GLIBCXX_3.4.20
GLIBCXX_3.4.21
GLIBCXX_3.4.22
GLIBCXX_3.4.23
GLIBCXX_3.4.24
GLIBCXX_3.4.25
GLIBCXX_3.4.26
GLIBCXX_3.4.27
GLIBCXX_3.4.28
GLIBCXX_DEBUG_MESSAGE_LENGTH

**Comment by adr-arroyo** [comment]
Thanks @Namburger !

Now my program is able to use the TPU from docker, I had to add `-v /dev/bus/usb:/dev/bus/usb` along with the `--priviledge` flag to the docker run command so that it works.

**Comment by adr-arroyo** [comment]
I have another question for you guys,
Regarding the output of the TPU, it is returned as type uint8 (mandatory and set in the post-training quantization, as well as the input). How do you cast it back to your original type? 

In my case I cast float32 values between (0 and 1) to uint8, then I need this cast back to a proper float32 values to use my scaler and descale the results.

**Comment by taf2** [comment]
same issue on a raspberry pi 

```
pi@raspberrypi:~/coral/google-coral/examples-camera/raspicam \> lsb_release -a
No LSB modules are available.
Distributor ID:	Raspbian
Description:	Raspbian GNU/Linux 10 (buster)
Release:	10
Codename:	buster

pi@raspberrypi:~/coral \> ls
tflite  tflite_runtime-1.14.0-cp37-cp37m-linux_armv7l.whl
pi@raspberrypi:~/coral \> pip3 install tflite_runtime-1.14.0-cp37-cp37m-linux_armv7l.whl
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Requirement already satisfied: tflite-runtime==1.14.0 from file:///home/pi/coral/tflite_runtime-1.14.0-cp37-cp37m-linux_armv7l.whl in /usr/local/lib/python3.7/dist-packages (1.14.0)
pi@raspberrypi:~/coral \> ls
tflite  tflite_runtime-1.14.0-cp37-cp37m-linux_armv7l.whl
pi@raspberrypi:~/coral \> git clone https://github.com/tensorflow/examples --depth 1
Cloning into 'examples'...
remote: Enumerating objects: 1293, done.
remote: Counting objects: 100% (1293/1293), done.
remote: Compressing objects: 100% (836/836), done.
remote: Total 1293 (delta 369), reused 994 (delta 250), pack-reused 0
Receiving objects: 100% (1293/1293), 8.28 MiB | 2.15 MiB/s, done.
Resolving deltas: 100% (369/369), done.
pi@raspberrypi:~/coral \> cd examples/lite/examples/image_classification/raspberry_pi
pi@raspberrypi:~/coral/examples/lite/examples/image_classification/raspberry_pi \> bash download.sh /tmp
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Requirement already satisfied: numpy in /usr/lib/python3/dist-packages (from -r requirements.txt (line 2)) (1.16.2)
Requirement already satisfied: picamera in /usr/lib/python3/dist-packages (from -r requirements.txt (line 3)) (1.13)
Requirement already satisfied: Pillow in /usr/lib/python3/dist-packages (from -r requirements.txt (line 4)) (5.4.1)
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 2997k  100 2997k    0     0  1761k      0  0:00:01  0:00:01 --:--:-- 1762k
Archive:  mobilenet_v1_1.0_224_quant_and_labels.zip
  inflating: /tmp/labels_mobilenet_quant_v1_224.txt  
   creating: /tmp/__MACOSX/
  inflating: /tmp/__MACOSX/._labels_mobilenet_quant_v1_224.txt  
  inflating: /tmp/mobilenet_v1_1.0_224_quant.tflite  
  inflating: /tmp/__MACOSX/._mobilenet_v1_1.0_224_quant.tflite  
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 4428k  100 4428k    0     0  1917k      0  0:00:02  0:00:02 --:--:-- 1916k
Downloaded files are in /tmp
pi@raspberrypi:~/coral/examples/lite/examples/image_classification/raspberry_pi \> python3 classify_picamera.py \
>   --model /tmp/mobilenet_v1_1.0_224_quant.tflite \
>   --labels /tmp/labels_mobilenet_quant_v1_224.txt
INFO: Initialized TensorFlow Lite runtime.
^CTraceback (most recent call last):
  File "classify_picamera.py", line 96, in <module>
    main()
  File "classify_picamera.py", line 82, in main
    Image.ANTIALIAS)
  File "/usr/lib/python3/dist-packages/PIL/Image.py", line 1806, in resize
    return self._new(self.im.resize(size, resample, box))
KeyboardInterrupt
pi@raspberrypi:~/coral/examples/lite/examples/image_classification/raspberry_pi \> cd
pi@raspberrypi:~ \> cd coral/
pi@raspberrypi:~/coral \> ls
examples  tflite  tflite_runtime-1.14.0-cp37-cp37m-linux_armv7l.whl
pi@raspberrypi:~/coral \> mv examples/ obj-example
pi@raspberrypi:~/coral \> mkdir google-coral && cd google-coral
pi@raspberrypi:~/coral/google-coral \> git clone https://github.com/google-coral/examples-camera.git --depth 1
Cloning into 'examples-camera'...
remote: Enumerating objects: 37, done.
remote: Counting objects: 100% (37/37), done.
remote: Compressing objects: 100% (35/35), done.
remote: Total 37 (delta 12), reused 14 (delta 1), pack-reused 0
Unpacking objects: 100% (37/37), done.
pi@raspberrypi:~/coral/google-coral \> cd examples-camera
pi@raspberrypi:~/coral/google-coral/examples-camera \> sh download_models.sh
--2020-01-17 20:23:10--  https://dl.google.com/coral/canned_models/all_models.tar.gz
Resolving dl.google.com (dl.google.com)... 172.217.7.206, 2607:f8b0:4004:802::200e
Connecting to dl.google.com (dl.google.com)|172.217.7.206|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 184961153 (176M) [application/octet-stream]
Saving to: ‘all_models.tar.gz’

all_models.tar.gz               100%[=======================================================>] 176.39M  3.01MB/s    in 77s     

2020-01-17 20:24:27 (2.30 MB/s) - ‘all_models.tar.gz’ saved [184961153/184961153]

./
./mobilenet_v2_1.0_224_inat_bird_quant_edgetpu.tflite
./mobilenet_v2_1.0_224_inat_bird_quant.tflite
./inception_v3_299_quant_edgetpu.tflite
./mobilenet_v2_1.0_224_quant_edgetpu.tflite
./inat_insect_labels.txt
./inception_v2_224_quant_edgetpu.tflite
./mobilenet_v1_1.0_224_quant.tflite
./mobilenet_v2_1.0_224_inat_insect_quant_edgetpu.tflite
./mobilenet_v1_1.0_224_quant_embedding_extractor_edgetpu.tflite
./mobilenet_v2_1.0_224_quant.tflite
./inception_v2_224_quant.tflite
./imagenet_labels.txt
./mobilenet_ssd_v2_face_quant_postprocess_edgetpu.tflite
./coco_labels.txt
./inception_v1_224_quant_edgetpu.tflite
./mobilenet_v2_1.0_224_inat_plant_quant.tflite
./inat_bird_labels.txt
./mobilenet_v1_1.0_224_quant_edgetpu.tflite
./mobilenet_ssd_v1_coco_quant_postprocess.tflite
./inception_v4_299_quant.tflite
./pet_labels.txt
./inception_v3_299_quant.tflite
./mobilenet_ssd_v2_coco_quant_postprocess_edgetpu.tflite
./mobilenet_ssd_v2_coco_quant_postprocess.tflite
./mobilenet_ssd_v1_coco_quant_postprocess_edgetpu.tflite
./inat_plant_labels.txt
./mobilenet_v2_1.0_224_inat_insect_quant.tflite
./inception_v1_224_quant.tflite
./inception_v4_299_quant_edgetpu.tflite
./mobilenet_ssd_v2_face_quant_postprocess.tflite
./mobilenet_v1_1.0_224_quant_embedding_extractor.tflite
./mobilenet_v2_1.0_224_inat_plant_quant_edgetpu.tflite
pi@raspberrypi:~/coral/google-coral/examples-camera \> cd raspicam
pi@raspberrypi:~/coral/google-coral/examples-camera/raspicam \> bash install_requirements.sh
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Requirement already satisfied: picamera in /usr/lib/python3/dist-packages (1.13)
pi@raspberrypi:~/coral/google-coral/examples-camera/raspicam \> python3 classify_capture.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/tflite_runtime/interpreter.py", line 165, in load_delegate
    delegate = Delegate(library, options)
  File "/usr/local/lib/python3.7/dist-packages/tflite_runtime/interpreter.py", line 119, in __init__
    raise ValueError(capture.message)
ValueError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "classify_capture.py", line 91, in <module>
    main()
  File "classify_capture.py", line 55, in main
    interpreter = common.make_interpreter(args.model)
  File "/home/pi/coral/google-coral/examples-camera/raspicam/common.py", line 27, in make_interpreter
    {'device': device[0]} if device else {})
  File "/usr/local/lib/python3.7/dist-packages/tflite_runtime/interpreter.py", line 168, in load_delegate
    library, str(e)))
ValueError: Failed to load delegate from libedgetpu.so.1

pi@raspberrypi:~/coral/google-coral/examples-camera/raspicam \> sudo usermod -aG plugdev pi
pi@raspberrypi:~/coral/google-coral/examples-camera/raspicam \> python3 classify_capture.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/tflite_runtime/interpreter.py", line 165, in load_delegate
    delegate = Delegate(library, options)
  File "/usr/local/lib/python3.7/dist-packages/tflite_runtime/interpreter.py", line 119, in __init__
    raise ValueError(capture.message)
ValueError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "classify_capture.py", line 91, in <module>
    main()
  File "classify_capture.py", line 55, in main
    interpreter = common.make_interpreter(args.model)
  File "/home/pi/coral/google-coral/examples-camera/raspicam/common.py", line 27, in make_interpreter
    {'device': device[0]} if device else {})
  File "/usr/local/lib/python3.7/dist-packages/tflite_runtime/interpreter.py", line 168, in load_delegate
    library, str(e)))
ValueError: Failed to load delegate from libedgetpu.so.1

```

**Comment by taf2** [comment]
rebooting my pi - fixed the issue for me

**Comment by gblue1223** [comment]
In my case, Coral USB accelerator works on USB3.0 so, I've changed USB compatibility option to USB 3.0 and it solved.

**Comment by Namburger** [comment]
by the way guys, please also upgrading the [tflite_runtime](https://www.tensorflow.org/lite/guide/python) package.

**Comment by Syirrus** [comment]
> USB compatibility option

Can you explain how you did that?  
How you set (assuming raspberry pi 4) to USB3.0 compatibility mode/option?

**Comment by Namburger** [comment]
@Syirrus are you still having the same issue?
this all fixed now if you upgrade to tflite_runtime-2.1.0.post1 instead of 1.14.
I don't think USB2.0 or USB3.0 matter because it works consistently on my RPI3 b+ (2.0).
Anyways, to answer your question, the pi4 has 2 USB2.0 ports and 2 USB3.0 ports,  just switch it to the correct port.

**Comment by Syirrus** [comment]
> tflite_runtime-2.1.0.post1

I installed the tflite_runtime-2.1.0 (tflite_runtime-2.1.0.post1-cp37-cp37m-linux_armv7l.whl).  I still get the same behavior on a RPI4.  However, if I plug the coral USB stick in to a USB 2.0 port, instead of the USB3.0 port it works.  When I switch to the native 3.0 USB port on the RPI4 I get the same error as above.

In fact, after I run the classification script and they run a lsusb, the Coral USB stick is no longer attached logically to the system, though physically it is still plugged in.

**Comment by Syirrus** [comment]
> @Syirrus are you still having the same issue?
> this all fixed now if you upgrade to tflite_runtime-2.1.0.post1 instead of 1.14.
> I don't think USB2.0 or USB3.0 matter because it works consistently on my RPI3 b+ (2.0).
> Anyways, to answer your question, the pi4 has 2 USB2.0 ports and 2 USB3.0 ports, just switch it to the correct port.

Does that make sense?

**Comment by Namburger** [comment]
@Syirrus Ahh, I see.
So it's working in USB 2.0 but not 3.0? That's annoying, because with 2.0, data transferring speed is going to be a bottle neck. But this looks like a rpi4 issue, check [here](https://www.raspberrypi.org/documentation/hardware/raspberrypi/usb/README.md).
For my pi3 b+, this isn't even an option since it only has 2.0 :/, good luck with yours

**Comment by Syirrus** [comment]
> @Syirrus Ahh, I see.
> So it's working in USB 2.0 but not 3.0? That's annoying, because with 2.0, data transferring speed is going to be a bottle neck. But this looks like a rpi4 issue, check [here](https://www.raspberrypi.org/documentation/hardware/raspberrypi/usb/README.md).
> For my pi3 b+, this isn't even an option since it only has 2.0 :/, good luck with yours

Exactly, it is working on USB 2.0, but NOT USB 3.0 which is a bottleneck :(. I will check out the link to RPI4 issues.  Thank you so much!

**Comment by Namburger** [comment]
No problems!

**Comment by Syirrus** [comment]
> No problems!

After spending many hours on and off thinking about this problem and combing the net, I finally solved this problem with this "Failed to load delegate from libedgetpu.so.1.0 error". Essentially, the cable that Google provided with my Coral USB TPU stinks.  I broke down and purchased a USB 3.1 (10Gbps) (NOT 5Gbps) cable and everything worked perfectly on the USB 3.0 port for the Raspberry Pi 4b (4GB). I hope this helps someone else in the same situation I was in.

**Comment by bmachin** [comment]
Weird as it may seem, I can confirm what @Syirrus reports. After many hours of fighting this error, it finally worked when I changed the USB cable. Thanks!

**Comment by pliablepixels** [comment]
@bmachin @Syirrus I recently moved from a USB 2.0 system to USB 3.0 and am noticing the same issue. It is intermittent, so it's not a plugdev issue.

Which cable did you buy? I was looking at [this cable](https://www.amazon.com/Anker-Powerline-Certified-Samsung-MacBook/dp/B07213D35X/ref=sr_1_4?dchild=1&keywords=usb+3.1+anker+usb+c&qid=1611410490&sr=8-4), but given USB-C standards seem to be evolving (pD/etc.) not sure if this is the best one to buy.

**Comment by TurboTronix** [comment]
I am getting the same error, running a docker in win10...

**Comment by pliablepixels** [comment]
I'm going to leave another finding here:

1. Replacing the cable eliminates _most_ problems related to  intermittent loading libedgetpu issues
2. However, there are times this happens, and especially if I interrupt an ongoing TPU operation 
3. When this happens, a reboot usually fixes, but I recently found [this script](http://billauer.co.il/blog/2013/02/usb-reset-ehci-uhci-linux/) that works very well (I'm on ubuntu 20) which makes coral work again without a reboot

**Comment by TE-KensakuOgata** [comment]
To close this issue, it is necessary to recover from the error and take measures for error detection. 

There is information that the Coral will be recognized again when the USB is fully reset. 
https://github.com/tensorflow/tensorflow/issues/32743

**Comment by joefernandez** [comment]
**USB Accelerator connected to a Proxmox VM failure scenario (FIXED)**

I experienced a similar but different problem when connecting the USB Accelerator to a VM hosted on proxmox:

When I plugged the USB Accelerator into the physical machine (proxmox physical host), it showed up like this:

```
root@proxmox:~# lsusb
...
Bus 001 Device 008: ID 1a6e:089a Global Unichip Corp. 
...
```
So added device to the VM where I want to work with Coral:

```
root@proxmox:~# qm set 202 -usb0 host=1a6e:089a
update VM 202: -usb0 host=1a6e:089a
```
And rebooted the VM. The `1a6e:089a` device showed up in the `lsusb` command in side the VM. Yay! Now the fun begins! I try to run the sample, and I get loooooong pause then the error at the top of this bug:

```
jfernandez@docker:~/dev/coral/pycoral$ python3 examples/classify_image.py --model test_data/mobilenet_v2_1.0_224_inat_bird_quant_edgetpu.tflite --labels test_data/inat_bird_labels.txt --input test_data/parrot.jpg
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/tflite_runtime/interpreter.py", line 152, in load_delegate
    delegate = Delegate(library, options)
  File "/usr/lib/python3/dist-packages/tflite_runtime/interpreter.py", line 111, in __init__
    raise ValueError(capture.message)
ValueError
 
During handling of the above exception, another exception occurred:
 
Traceback (most recent call last):
  File "examples/classify_image.py", line 84, in <module>
    main()
  File "examples/classify_image.py", line 61, in main
    interpreter = make_interpreter(*args.model.split('@'))
  File "/usr/lib/python3/dist-packages/pycoral/utils/edgetpu.py", line 66, in make_interpreter
    delegates = [load_edgetpu_delegate({'device': device} if device else {})]
  File "/usr/lib/python3/dist-packages/pycoral/utils/edgetpu.py", line 42, in load_edgetpu_delegate
    return tflite.load_delegate(_EDGETPU_SHARED_LIB, options or {})
  File "/usr/lib/python3/dist-packages/tflite_runtime/interpreter.py", line 154, in load_delegate
    raise ValueError('Failed to load delegate from {}\n{}'.format(
ValueError: Failed to load delegate from libedgetpu.so.1
```

After trying a bunch of fixes from this thread, I noticed the USB Accelerator device **_had changed_**:

```
root@proxmox:~# lsusb
...
Bus 001 Device 012: ID 18d1:9302 Google Inc.
...
```
What?! Looks like running the example changed the device host ID of the USB Accelerator (was: `1a6e:089a`,  is now:`18d1:9302`). A side effect of loading a USB driver for it? Only the USB driver daemons know... Point is, now the VM can't talk to the USB device anymore, so I have to re-connect the USB device to the VM with the new device ID:

```
root@proxmox:~# qm set 202 -usb0 host=18d1:9302
update VM 202: -usb0 host=18d1:9302
```
Reboot my VM again. And the sample runs!

Also, at one point, I ran this to add myself to the plugdev group, but I'm not sure it this had any effect:
```
sudo usermod -aG plugdev [your username]
```

Hope this saves someone a bit of time.

\\\\Joe

**Comment by kiteklan** [comment]
> **USB Accelerator connected to a Proxmox VM failure scenario (FIXED)**
> 
> I experienced a similar but different problem when connecting the USB Accelerator to a VM hosted on proxmox:
> 
> When I plugged the USB Accelerator into the physical machine (proxmox physical host), it showed up like this:
> 
> ```
> root@proxmox:~# lsusb
> ...
> Bus 001 Device 008: ID 1a6e:089a Global Unichip Corp. 
> ...
> ```
> 
> So added device to the VM where I want to work with Coral:
> 
> ```
> root@proxmox:~# qm set 202 -usb0 host=1a6e:089a
> update VM 202: -usb0 host=1a6e:089a
> ```
> 
> And rebooted the VM. The `1a6e:089a` device showed up in the `lsusb` command inside the VM. Yay! Now the fun begins! I try to run the sample, and I get loooooong pause then the error at the top of this bug:
> 
> ```
> jfernandez@docker:~/dev/coral/pycoral$ python3 examples/classify_image.py --model test_data/mobilenet_v2_1.0_224_inat_bird_quant_edgetpu.tflite --labels test_data/inat_bird_labels.txt --input test_data/parrot.jpg
> Traceback (most recent call last):
>   File "/usr/lib/python3/dist-packages/tflite_runtime/interpreter.py", line 152, in load_delegate
>     delegate = Delegate(library, options)
>   File "/usr/lib/python3/dist-packages/tflite_runtime/interpreter.py", line 111, in __init__
>     raise ValueError(capture.message)
> ValueError
>  
> During handling of the above exception, another exception occurred:
>  
> Traceback (most recent call last):
>   File "examples/classify_image.py", line 84, in <module>
>     main()
>   File "examples/classify_image.py", line 61, in main
>     interpreter = make_interpreter(*args.model.split('@'))
>   File "/usr/lib/python3/dist-packages/pycoral/utils/edgetpu.py", line 66, in make_interpreter
>     delegates = [load_edgetpu_delegate({'device': device} if device else {})]
>   File "/usr/lib/python3/dist-packages/pycoral/utils/edgetpu.py", line 42, in load_edgetpu_delegate
>     return tflite.load_delegate(_EDGETPU_SHARED_LIB, options or {})
>   File "/usr/lib/python3/dist-packages/tflite_runtime/interpreter.py", line 154, in load_delegate
>     raise ValueError('Failed to load delegate from {}\n{}'.format(
> ValueError: Failed to load delegate from libedgetpu.so.1
> ```
> 
> After trying a bunch of fixes from this thread, I noticed the USB Accelerator device **_had changed_**:
> 
> ```
> root@proxmox:~# lsusb
> ...
> Bus 001 Device 012: ID 18d1:9302 Google Inc.
> ...
> ```
> 
> What?! Looks like running the example changed the device host ID of the USB Accelerator (was: `1a6e:089a`, is now:`18d1:9302`). A side effect of loading a USB driver for it? Only the USB driver daemons know... Point is, now the VM can't talk to the USB device anymore, so I have to re-connect the USB device to the VM with the new device ID:
> 
> ```
> root@proxmox:~# qm set 202 -usb0 host=18d1:9302
> update VM 202: -usb0 host=18d1:9302
> ```
> 
> Reboot my VM again. And the sample runs!
> 
> Also, at one point, I ran this to add myself to the plugdev group, but I'm not sure it this had any effect:
> 
> ```
> sudo usermod -aG plugdev [your username]
> ```
> 
> Hope this saves someone a bit of time.
> 
> \\Joe

I have the same setup using the tpu on a proxmox VM , added the as a pci device with an adapter. 
In my case the resetting device works. 
with lspci get device id:
**02:00.0 System peripheral: Device 1ac1:089a**
find the corresponding  the device folder:
**sys/bus/pci/devices/0000:02:00.0/uevent:PCI_ID=1AC1:089A**
and reset the device:
**echo 1 >/sys/bus/pci/devices/0000\:02\:00.0/remove
echo 1 >/sys/bus/pci/rescan**
 

I believe resetting the USB will also work as mentioned above.

**Comment by aslanpour** [comment]
> > I am facing the same issue , even when the USB accelerator is plugged in and the LED in it is shining bright ........
> 
> @programmer290399 you might need to add your linux user to plugdev group:
> 
> ```
> $ sudo usermod -aG plugdev [your username]
> ```

This works for me when my application inside the container is not running as root user.

**Comment by lang02** [comment]
@pliablepixels in your _usb_reset_all.sh_ script should the return value below be **1** (instead of **0**) ?
```
        if [[ -z `lsusb | grep -i google` ]] ; then
                echo "${now}:lsusb check failed" >> ${filename}

                return 0
        fi
```
I also found that your _restart_usb()_ did not work for my case but this worked 
```
restart_usb() {
        echo "${now}:Restarting USB" >> ${filename}
        echo "${now}:Disabling TPU device on 8-1.1..." >> ${filename}
        echo -n "0" > /sys/bus/usb/devices/8-1.1/authorized 2>/dev/null
        echo "${now}:Enabling TPU device on 8-1.1..." >> ${filename}
        echo -n "1" > /sys/bus/usb/devices/8-1.1/authorized 2>/dev/null
        echo "${now}:Completed operation" >> ${filename}
}
```
where 8-1.1 is the USB bus(?) id that my Coral TPU connected to

I found my solution here @ssokolow [https://askubuntu.com/questions/645/how-do-you-reset-a-usb-device-from-the-command-line](url)
