### ISSUE TITLE
Bincount Op test "test_negative" fails with TF 2.0

### ISSUE THREAD

**Issue by MattConley** [tensorflow/tensorflow#32755]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): **No**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): **Linux Ubuntu 16.04**
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: **N/A**
- TensorFlow installed from (source or binary): **Binary**
- TensorFlow version (use command below): **2.0.0-rc1**
- Python version: **3.6**
- Bazel version (if compiling from source): **N/A**
- GCC/Compiler version (if compiling from source): **N/A**
- CUDA/cuDNN version: **10.0**
- GPU model and memory: **RTX 2080 Ti**, **11G**

**Describe the current behavior**
The test_negative test in `tensorflow/python/kernel_tests/bincount_op_test.py` fails, as the bincount call with negative values does not throw an InvalidArgumentError. 

This behavior might be the result of the op being called on the GPU, as only the CPU call is expected to throw the error, as per the comment here: https://github.com/tensorflow/tensorflow/blob/r2.0/tensorflow/python/kernel_tests/bincount_op_test.py#L107.

Setting CUDA_VISIBLE_DEVICES to be empty forces the op to run on CPU and the test passes (the invalid argument error is successfully thrown), but passing `use_gpu=False` as an option to the session wrapper does not have this effect.

**Describe the expected behavior**
The test_negative test should pass, as the call to bincount with a negative input value is expected to throw an InvalidArgumentError. 

**Code to reproduce the issue**
Run the python test `tensorflow/python/kernel_tests/bincount_op_test.py`.

**Comment by gadagashwini** [comment]
@MattConley, Will it be possible to provide the sample standalone code to replicate the issue. Thanks!

**Comment by MattConley** [comment]
@gadagashwini Unfortunately the minimal repro I have at the moment is the bincount_op_test itself, specifically `test_negative` (https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/kernel_tests/bincount_op_test.py#L106-L110).
The issue might be with the test framework itself, as internal session wrappers are used even with TF 2.0.

Also, setting CUDA_VISIBLE_DEVICES to be empty forces the op to run on CPU and the test passes (the invalid argument error is successfully thrown), but passing `use_gpu=False` as an option to the session wrapper does not have this effect.

**Comment by ymodak** [comment]
I was able to reproduce the error reported in TF 2.0 nightly version ```'2.0.0-dev20190924'```
```python
OP_REQUIRES failed at bincount_op.cc:111 : Invalid argument: Input arr must be non-negative!
```

**Comment by nluehr** [comment]
@reedwm can you take a look at this?
