### ISSUE TITLE
call custom op using c++

### ISSUE THREAD

**Issue by 7oud** [tensorflow/tensorflow#32759]
I built a very simple custom op `zero_out` and try to run it using c++, the question is how to call this op, there is no doc about it.

code of custom op `zero_out`
```
#include "tensorflow/core/framework/op.h"
#include "tensorflow/core/framework/shape_inference.h"
#include "tensorflow/core/framework/op_kernel.h"
using namespace tensorflow;

REGISTER_OP("ZeroOut")
.Input("to_zero: float")
.Output("zeroed: float")
.SetShapeFn([](::tensorflow::shape_inference::InferenceContext* c) {
c->set_output(0, c->input(0));
return Status::OK();
});

class ZeroOutOp : public OpKernel {
public:
    explicit ZeroOutOp(OpKernelConstruction* context) : OpKernel(context) {}

    void Compute(OpKernelContext* context) override {
        const Tensor& input_tensor = context->input(0);
        auto input = input_tensor.flat<float>();
        Tensor* output_tensor = NULL;
        OP_REQUIRES_OK(context, context->allocate_output(0, input_tensor.shape(),                                                     &output_tensor));
        auto output_flat = output_tensor->flat<float>();
        const int N = input.size();
        for (int i = 1; i < N; i++)
            output_flat(i) = 0;
        if (N > 0) output_flat(0) = input(0);
    }
};

REGISTER_KERNEL_BUILDER(Name("ZeroOut").Device(DEVICE_CPU), ZeroOutOp);
```
After building, I got `zero_out.so`, then I load the lib using c++
```
    TF_Status* status_load = TF_NewStatus();
    TF_Library* lib_handle = TF_LoadLibrary("libzero_out.so", status_load);
    TF_Code code = TF_GetCode(status_load);
    cout << "code: " << code << endl;  // output: 0

    TF_Buffer op_list_buf = TF_GetOpList(lib_handle);
    tensorflow::OpList op_list;
    op_list.ParseFromArray(op_list_buf.data, op_list_buf.length);
    cout << "oplist size = " << op_list.op_size() << endl;    // output: 1
    cout << "oplist name = " << op_list.op(0).name() << endl;    // output: ZeroOut
```
I think the op should have been registered, then how to invoke the op function, Could you give some examples or code snippet?

**Comment by ymodak** [comment]
To use the op in Python, See https://www.tensorflow.org/guide/extend/op#use_the_op_in_python
For invoking the op in c++, you may refer this [thread](https://stackoverflow.com/questions/50799510/how-to-run-custom-gpu-tensorflowop-from-c-code)

**Comment by 7oud** [comment]
@ymodak yes, it is worked when using python, but how to invoke the op in C++ is not solved in your link. In short, when you add and register an op, there is no header file to include, how to call the op function, maybe parsed in `TF_GetOpList`, but no clear doc or example for that

**Comment by zh794390558** [comment]
core dump when using SetShapeFn under tf2.0.

**Comment by yifeif** [comment]
I don't think you are supposed to directly call any of the c++ ops, custom ops or not. But you can call it through the `Session` API, following https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/public/README.md#c-api-example

You might also be able to use eager's API `TFE_Execute`, but you'll still need to create context manually.

**Comment by yifeif** [comment]
Closing this issue. Feel free to re-open if you have further questions!
