### ISSUE TITLE
Trouble building from source: import tensorflow fails (from any directory)

### ISSUE THREAD

**Issue by reesepathak** [tensorflow/tensorflow#3276]
### Environment info
Operating System: Ubuntu 14.04

Installed version of CUDA and cuDNN: 7.5/5
(please attach the output of `ls -l /path/to/cuda/lib/libcud*`):
-rw-r--r-- 1 root root 189170 Oct  8  2015 /usr/local/cuda/lib/libcudadevrt.a
lrwxrwxrwx 1 root root     16 Oct  8  2015 /usr/local/cuda/lib/libcudart.so -> libcudart.so.7.5
lrwxrwxrwx 1 root root     19 Oct  8  2015 /usr/local/cuda/lib/libcudart.so.7.5 -> libcudart.so.7.5.18
-rwxr-xr-x 1 root root 311596 Oct  8  2015 /usr/local/cuda/lib/libcudart.so.7.5.18
-rw-r--r-- 1 root root 558020 Oct  8  2015 /usr/local/cuda/lib/libcudart_static.a

2. The output from `python -c "import tensorflow; print(tensorflow.__version__)"`.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named tensorflow
If installed from sources, provide the commit hash: (most recent: b62f19cdc7672ff31b90b4f2b7aad870849be3e0)

### Steps to reproduce
1.  Created an empty conda environment only seeded w/ python 2.7.5 + anaconda
2. Installed numpy scipy
3. Correctly configured w/ ./configure
4. Ran the exact bazel build command provided on the site from root of tensorflow cloned directory
5. import tensorflow fails (from any directory) AND conda list or pip list do not show tensorflow after installation.  (Yes, I checked to make sure that the ./configure had the right address matching the output of which python)

### What have you tried?
1. Creating new conda env, to see if it would help. Don't have access to virtualenv on my machine nor do I have sudo access.

**Comment by jmchen-g** [comment]
This is a question better suited for StackOverflow. Please ask it there and tag it with the `tensorflow` tag.
