### ISSUE TITLE
Sym-links in nvcc C compiler path causes "undeclared inclusion(s) in rule '//tensorflow/core:lib_hash_crc32c_accelerate_internal'"

### ISSUE THREAD

**Issue by owainkenwayucl** [tensorflow/tensorflow#32776]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Redhat Enterprise Linux 7.x
- TensorFlow installed from (source or binary): source
- TensorFlow version: 1.14.0
- Python version: 3.7.4
- Installed using virtualenv? pip? conda?: virtualenv
- Bazel version (if compiling from source): 0.24.1
- GCC/Compiler version (if compiling from source): 4.9.2
- CUDA/cuDNN version: 10.0.130/7.4.2.24
- GPU model and memory: Tesla P100

**Describe the problem**

We have compilers installed in `/shared/ucl/apps/gcc/4.9.2`.  Unfortunately `/shared` is a sym-link to `/lustre/shared`.  Attempting to build Tensorflow with Cuda support results in this sym-link being inconsistently de-referenced meaning that some rules refer to the `/shared` location while the system include paths refer to `/lustre/shared`.  This seems to be an issue only with the C compiler used by nvcc, not with the one used to build the rest of the code.

Telling the configure script to use `/lustre/shared/ucl/apps/gcc/4.9.2/bin/gcc` as the nvcc c compiler *works around the problem* but is less than ideal as this path is different on different clusters. It culd also be an issue if a user on a mult-user system uses their own install of GCC in `/home`where `/home` is a sym-link. This appears to be a bug in the way the configure script and/or bazel deals with sym-links.

**Provide the exact sequence of commands / steps that you executed before running into the problem**

The script at https://github.com/owainkenwayucl/install-scripts/blob/master/scripts/tensorflow/tensorflow-1.14.0-py37-gpu_install

But effectively:

```
CONFIG_OPTS="--config=cuda --copt=-march=broadwell --cxxopt=-D_GLIBCXX_USE_CXX11_ABI=0 --copt=-O3"
export TF_CUDA_PATHS=/shared/ucl/apps/cuda/10.0.130/gnu-4.9.2,/shared/ucl/apps/cudnn/7.4.2.24/10.0/cuda
./configure

bazel build --verbose_failures $CONFIG_OPTS //tensorflow/tools/pip_package:build_pip_package 
```

Answering "yes" to build with cuda and selecting defaults for compute capability, nccl etc.

**Comment by owainkenwayucl** [comment]
Actions I took at configure stage:

```
You have bazel 0.24.1 installed.
Do you wish to build TensorFlow with XLA JIT support? [Y/n]: 
XLA JIT support will be enabled for TensorFlow.

Do you wish to build TensorFlow with OpenCL SYCL support? [y/N]: 
No OpenCL SYCL support will be enabled for TensorFlow.

Do you wish to build TensorFlow with ROCm support? [y/N]: 
No ROCm support will be enabled for TensorFlow.

Do you wish to build TensorFlow with CUDA support? [y/N]: y
CUDA support will be enabled for TensorFlow.

Do you wish to build TensorFlow with TensorRT support? [y/N]: 
No TensorRT support will be enabled for TensorFlow.

Found CUDA 10.0 in:
    /shared/ucl/apps/cuda/10.0.130/gnu-4.9.2/lib64
    /shared/ucl/apps/cuda/10.0.130/gnu-4.9.2/include
Found cuDNN 7 in:
    /shared/ucl/apps/cudnn/7.4.2.24/10.0/cuda/lib64
    /shared/ucl/apps/cudnn/7.4.2.24/10.0/cuda/include


Please specify a list of comma-separated CUDA compute capabilities you want to build with.
You can find the compute capability of your device at: https://developer.nvidia.com/cuda-gpus.
Please note that each additional compute capability significantly increases your build time and binary size, and that TensorFlow only supports compute capabilities >= 3.5 [Default is: 3.5,7.0]: 


Do you want to use clang as CUDA compiler? [y/N]: 
nvcc will be used as CUDA compiler.

Please specify which gcc should be used by nvcc as the host compiler. [Default is /shared/ucl/apps/gcc/4.9.2/bin/gcc]: 

Do you wish to build TensorFlow with MPI support? [y/N]:
```

**Comment by owainkenwayucl** [comment]
Build failure:
```
ERROR: /dev/shm/tensorflow/tmp.6ooBek4IW8/tensorflow/tensorflow/core/BUILD:2499:1: undeclared inclusion(s) in rule '//tensorflow/core:lib_hash_crc32c_accelerate_internal':
this rule is missing dependency declarations for the following files included by 'tensorflow/core/lib/hash/crc32c_accelerate.cc':
  '/shared/ucl/apps/gcc/4.9.2/lib/gcc/x86_64-unknown-linux-gnu/4.9.2/include/stddef.h'
  '/shared/ucl/apps/gcc/4.9.2/lib/gcc/x86_64-unknown-linux-gnu/4.9.2/include/stdint.h'
  '/shared/ucl/apps/gcc/4.9.2/lib/gcc/x86_64-unknown-linux-gnu/4.9.2/include/nmmintrin.h'
  '/shared/ucl/apps/gcc/4.9.2/lib/gcc/x86_64-unknown-linux-gnu/4.9.2/include/smmintrin.h'
  '/shared/ucl/apps/gcc/4.9.2/lib/gcc/x86_64-unknown-linux-gnu/4.9.2/include/tmmintrin.h'
  '/shared/ucl/apps/gcc/4.9.2/lib/gcc/x86_64-unknown-linux-gnu/4.9.2/include/pmmintrin.h'
  '/shared/ucl/apps/gcc/4.9.2/lib/gcc/x86_64-unknown-linux-gnu/4.9.2/include/emmintrin.h'
  '/shared/ucl/apps/gcc/4.9.2/lib/gcc/x86_64-unknown-linux-gnu/4.9.2/include/xmmintrin.h'
  '/shared/ucl/apps/gcc/4.9.2/lib/gcc/x86_64-unknown-linux-gnu/4.9.2/include/mmintrin.h'
  '/shared/ucl/apps/gcc/4.9.2/lib/gcc/x86_64-unknown-linux-gnu/4.9.2/include/mm_malloc.h'
  '/shared/ucl/apps/gcc/4.9.2/lib/gcc/x86_64-unknown-linux-gnu/4.9.2/include/popcntintrin.h'
Target //tensorflow/tools/pip_package:build_pip_package failed to build
INFO: Elapsed time: 108.730s, Critical Path: 1.51s
INFO: 42 processes: 42 local.
FAILED: Build did NOT complete successfully
```

**Comment by owainkenwayucl** [comment]
If I change the answer at `Please specify which gcc should be used by nvcc as the host compiler. [Default is /shared/ucl/apps/gcc/4.9.2/bin/gcc]: ` to `/lustre/shared/ucl/apps/gcc/4.9.2/bin/gcc` then Tensorflow build successfully.

**Comment by ravikyram** [comment]
Can we close this issue since the query is been resolved.Thanks!

**Comment by owainkenwayucl** [comment]
It's not been resolved.  There's a workaround which I found in this case but that's only because I've a great deal of familiarity with the system.  

If I were a user of a system where I were trying to install things in my home directory and i did not know how things were set up underneath it would cause problems.  Googling the error finds other people stuck at this point (e.g. https://github.com/bazelbuild/bazel/issues/4573 where it's clear that the path of the user's conda tools is likely to be under a sym-link) so it should really be resolved properly.

**Comment by angerson** [comment]
Just to be clear, you think this would be solved if our `./configure` script resolved symlinks, right?

**Comment by owainkenwayucl** [comment]
I think so.  However it works it out, it needs to be consistent with how Bazel writes its rules (which I'm really not an expert in!).

**Comment by owainkenwayucl** [comment]
Having looked at `configure.py` I believe it's as simple as adding:

```python
gcc_host_compiler_path = os.path.realpath(gcc_host_compiler_path)
```

at line 842.

I'm happy to do this and do a pull request if you prefer?

**Comment by angerson** [comment]
Yes, that would be very helpful, thank you!

**Comment by njzjz** [comment]
I face this problem too. After I use the patch, I still face a similar problem with CUDA includes path.

**Comment by owainkenwayucl** [comment]
Ok, that's weird - our CUDA includes are also under the sym-link and we don't get that problem.  What error do you get?

**Comment by njzjz** [comment]
> Ok, that's weird - our CUDA includes are also under the sym-link and we don't get that problem. What error do you get?

```
ERROR: /cache/home/jz748/.cache/bazel/_bazel_jz748/9a5804611367d5a3465d7ad3decb2864/external/nccl_archive/BUILD.bazel:67:1: undeclared inclusion(s) in rule '@nccl_archive//:device_lib':
this rule is missing dependency declarations for the following files included by 'external/nccl_archive/collectives/device/max_all_gather.cu.cc':       '/scratch/jz748/cuda-10.1/targets/x86_64-linux/include/cuda_runtime.h'
  '/scratch/jz748/cuda-10.1/targets/x86_64-linux/include/crt/host_config.h'
  '/scratch/jz748/cuda-10.1/targets/x86_64-linux/include/builtin_types.h'
  '/scratch/jz748/cuda-10.1/targets/x86_64-linux/include/device_types.h'
  '/scratch/jz748/cuda-10.1/targets/x86_64-linux/include/crt/host_defines.h'
  '/scratch/jz748/cuda-10.1/targets/x86_64-linux/include/driver_types.h'
  '/scratch/jz748/cuda-10.1/targets/x86_64-linux/include/vector_types.h'
  '/scratch/jz748/cuda-10.1/targets/x86_64-linux/include/surface_types.h'
  '/scratch/jz748/cuda-10.1/targets/x86_64-linux/include/texture_types.h'
  '/scratch/jz748/cuda-10.1/targets/x86_64-linux/include/library_types.h'
  '/scratch/jz748/cuda-10.1/targets/x86_64-linux/include/channel_descriptor.h'
  '/scratch/jz748/cuda-10.1/targets/x86_64-linux/include/cuda_runtime_api.h'
  '/scratch/jz748/cuda-10.1/targets/x86_64-linux/include/cuda_device_runtime_api.h'
  '/scratch/jz748/cuda-10.1/targets/x86_64-linux/include/driver_functions.h'
  '/scratch/jz748/cuda-10.1/targets/x86_64-linux/include/vector_functions.h'
  '/scratch/jz748/cuda-10.1/targets/x86_64-linux/include/vector_functions.hpp'
  '/scratch/jz748/cuda-10.1/targets/x86_64-linux/include/crt/common_functions.h'
  '/scratch/jz748/cuda-10.1/targets/x86_64-linux/include/crt/math_functions.h'
  '/scratch/jz748/cuda-10.1/targets/x86_64-linux/include/crt/math_functions.hpp'
  '/scratch/jz748/cuda-10.1/targets/x86_64-linux/include/cuda_surface_types.h'
  '/scratch/jz748/cuda-10.1/targets/x86_64-linux/include/cuda_texture_types.h'
  '/scratch/jz748/cuda-10.1/targets/x86_64-linux/include/crt/device_functions.h'
  '/scratch/jz748/cuda-10.1/targets/x86_64-linux/include/crt/device_functions.hpp'
  '/scratch/jz748/cuda-10.1/targets/x86_64-linux/include/device_atomic_functions.h'
  '/scratch/jz748/cuda-10.1/targets/x86_64-linux/include/device_atomic_functions.hpp'
  '/scratch/jz748/cuda-10.1/targets/x86_64-linux/include/crt/device_double_functions.h'
  '/scratch/jz748/cuda-10.1/targets/x86_64-linux/include/crt/device_double_functions.hpp'
  '/scratch/jz748/cuda-10.1/targets/x86_64-linux/include/sm_20_atomic_functions.h'
  '/scratch/jz748/cuda-10.1/targets/x86_64-linux/include/sm_20_atomic_functions.hpp'
  '/scratch/jz748/cuda-10.1/targets/x86_64-linux/include/sm_32_atomic_functions.h'
  '/scratch/jz748/cuda-10.1/targets/x86_64-linux/include/sm_32_atomic_functions.hpp'
  '/scratch/jz748/cuda-10.1/targets/x86_64-linux/include/sm_35_atomic_functions.h'
  '/scratch/jz748/cuda-10.1/targets/x86_64-linux/include/sm_60_atomic_functions.h'
  '/scratch/jz748/cuda-10.1/targets/x86_64-linux/include/sm_60_atomic_functions.hpp'
  '/scratch/jz748/cuda-10.1/targets/x86_64-linux/include/sm_20_intrinsics.h'
  '/scratch/jz748/cuda-10.1/targets/x86_64-linux/include/sm_20_intrinsics.hpp'
  '/scratch/jz748/cuda-10.1/targets/x86_64-linux/include/sm_30_intrinsics.h'
  '/scratch/jz748/cuda-10.1/targets/x86_64-linux/include/sm_30_intrinsics.hpp'
  '/scratch/jz748/cuda-10.1/targets/x86_64-linux/include/sm_32_intrinsics.h'
  '/scratch/jz748/cuda-10.1/targets/x86_64-linux/include/sm_32_intrinsics.hpp'
  '/scratch/jz748/cuda-10.1/targets/x86_64-linux/include/sm_35_intrinsics.h'
  '/scratch/jz748/cuda-10.1/targets/x86_64-linux/include/sm_61_intrinsics.h'
  '/scratch/jz748/cuda-10.1/targets/x86_64-linux/include/sm_61_intrinsics.hpp'
  '/scratch/jz748/cuda-10.1/targets/x86_64-linux/include/crt/sm_70_rt.h'
  '/scratch/jz748/cuda-10.1/targets/x86_64-linux/include/crt/sm_70_rt.hpp'
  '/scratch/jz748/cuda-10.1/targets/x86_64-linux/include/surface_functions.h'
  '/scratch/jz748/cuda-10.1/targets/x86_64-linux/include/texture_fetch_functions.h'
  '/scratch/jz748/cuda-10.1/targets/x86_64-linux/include/texture_indirect_functions.h'
  '/scratch/jz748/cuda-10.1/targets/x86_64-linux/include/surface_indirect_functions.h'
  '/scratch/jz748/cuda-10.1/targets/x86_64-linux/include/device_launch_parameters.h'
  '/scratch/jz748/cuda-10.1/targets/x86_64-linux/include/cuda_fp16.h'
  '/scratch/jz748/cuda-10.1/targets/x86_64-linux/include/cuda_fp16.hpp'
```
Do you think it is a different issue? If so, I'll create another issue.

**Comment by shubham769** [comment]
@njzjz facing the same error and i think this error is related to this issue only

**Comment by njzjz** [comment]
> @njzjz facing the same error and i think this error is related to this issue only

Downgrading from CUDA 10.1 to CUDA 10.0 solves the issue. Something wrong with CUDA 10.1?

**Comment by angerson** [comment]
@owainkenwayucl, 58b236b235ce57808c917feb19b9f895f628710c should solve the original problem here. Thank you for your patience with the CLA issue in your PR.

For others -- please file a separate issue if you're still running into problems.

**Comment by owainkenwayucl** [comment]
No problem - thanks for solving the issue.

**Comment by byronyi** [comment]
> > @njzjz facing the same error and i think this error is related to this issue only
> 
> Downgrading from CUDA 10.1 to CUDA 10.0 solves the issue. Something wrong with CUDA 10.1?

I guess it is because in CUDA 10.1, `/usr/local/cuda-10.1/include` is now a symlink to `/usr/local/cuda-10.1/targets/x86_64-linux/include` and `/usr/local/cuda-10.1/lib64` is a symlink to `/usr/local/cuda-10.1/targets/x86_64-linux/lib`. This is different from CUDA 10.0, where both are real directories.

Ping @buchgr who seems to work on this recently. I hit the same issue setting up RBE builds with NCCL complaining missing dependency declaration. Might worth taking a look.

**Comment by njzjz** [comment]
> > > @njzjz facing the same error and i think this error is related to this issue only
> > 
> > 
> > Downgrading from CUDA 10.1 to CUDA 10.0 solves the issue. Something wrong with CUDA 10.1?
> 
> I guess it is because in CUDA 10.1, `/usr/local/cuda-10.1/include` is now a symlink to `/usr/local/cuda-10.1/targets/x86_64-linux/include` and `/usr/local/cuda-10.1/lib64` is a symlink to `/usr/local/cuda-10.1/targets/x86_64-linux/lib`. This is different from CUDA 10.0, where both are real directories.
> 
> Ping @buchgr who seems to work on this recently. I hit the same issue setting up RBE builds with NCCL complaining missing dependency declaration. Might worth taking a look.

See here https://github.com/tensorflow/tensorflow/issues/35122#issuecomment-589858889. I have a temporary solution: resolving symbolic links for all CUDA paths.

**Comment by byronyi** [comment]
@njzjz You are welcomed to submit a PR and ping @angerson to see if he'd like to review.
