### ISSUE TITLE
TensorFlow is broken, unusable on Raspberry Pi

### ISSUE THREAD

**Issue by FlorinAndrei** [tensorflow/tensorflow#32771]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes, code is pasted below
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Raspbian Buster
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: Raspberry Pi 4 with 4 GB RAM
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 1.13.1
- Python version: 3.7.3
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

On Windows I use python-3.7.4 with TensorFlow 1.13.1, 1.14.0 and 2.0.0rc1

**Describe the current behavior**
I train a model on Windows (gen_test_train_data.py, then train_model.py), using the same TF version that's available on RPi. I can test the model on Windows just fine using model_visual_test.py.
If I transfer the model to the RPi, I cannot load it. I get mysterious errors when running model_visual_test.py:

```
Traceback (most recent call last):
  File "model_visual_test.py", line 16, in <module>
    model = keras.models.load_model('saved_model.h5')
  File "/home/pi/.local/lib/python3.7/site-packages/tensorflow_core/python/keras/saving/save.py", line 140, in load_model
    loader_impl.parse_saved_model(filepath)
  File "/home/pi/.local/lib/python3.7/site-packages/tensorflow_core/python/saved_model/loader_impl.py", line 83, in parse_saved_model
    constants.SAVED_MODEL_FILENAME_PB))
OSError: SavedModel file does not exist at: saved_model.h5/{saved_model.pbtxt|saved_model.pb}
```

It doesn't work even if I train the model on the RPi, by running gen_test_train_data.py, then run train_model.py, which takes forever. It completes training, but then it fails to load with

```
Train on 8000 samples
8000/8000 [==============================] - 1305s 163ms/sample - loss: 0.5675 - acc: 0.8609
Traceback (most recent call last):
  File "train_model.py", line 122, in <module>
    keras.models.save_model(model, 'saved_model.h5')
  File "/home/pi/.local/lib/python3.7/site-packages/tensorflow_core/python/keras/saving/save.py", line 104, in save_model
    model, filepath, overwrite, include_optimizer)
  File "/home/pi/.local/lib/python3.7/site-packages/tensorflow_core/python/keras/saving/hdf5_format.py", line 73, in save_model_to_hdf5
    raise ImportError('`save_model` requires h5py.')
ImportError: `save_model` requires h5py.
```

No, that's wrong. I do have the h5 module installed on the Raspberry Pi:

```
$ pip3 list --user | grep h5
h5py                 2.10.0
```

In other words, a model trained on the RPi fails to load on the RPi. A model trained on Win10 runs fine on Win10, but fails to load on the RPi. This is with a code that works perfect on Windows 10 and macOS with all kinds of TF versions between 1.13.1 and 2.0.0rc1, GPU or CPU versions.

**Describe the expected behavior**
I mean, it should just work, shouldn't it? Why is this so hard?

**Code to reproduce the issue**
https://github.com/FlorinAndrei/TensorAim/tree/tf-bug-report
Run gen_test_train_data.py. Then on that run train_model.py. It fails to run its own model, generated on RPi.
Or run gen_test_train_data.py on Windows, run train_model.py on Windows, transfer the model on the RPi, then run model_visual_test.py on it. It will fail to load.
I will leave this branch untouched so you can test the bug report.

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by WilianZilv** [comment]
Any clue on what is happening?

**Comment by terryheo** [comment]
@FlorinAndrei  Is this still happening with TF 2.2 release?

**Comment by FlorinAndrei** [comment]
I have no time to test it nowadays, sorry. Maybe in a few weeks.

**Comment by JosimarReis** [comment]
The same is happening to me.

**Comment by 8bitmp3** [comment]
@JosimarReis @FlorinAndrei I have a RasPi Zero, so it'd be hard to reproduce this for me but, take a look at https://github.com/tensorflow/tensorflow/issues/35909. They may have had a similar issue with loading H5 models. The solution that worked there was getting the h5py package via the APT package manager: `sudo apt-get install python3-h5py`. Judging by your bug report, @FlorinAndrei, you installed h5py with `pip`.

Note that this was performed in Linux Raspbian and @FlorinAndrei you have Raspbian Buster (not an expert in the diff of those distros).

> ... From the error log i can see that saved_model- face_recognition_model.h5 does not exist, make sure you import the file to the right path and then try loading the model using load_model...

@niccle27 said:
> ... the path was alright. The problem concern the h5py package installed using pip on the raspberry pi. Apparently there seem to be some issue with it. I managed to fix it by installing using the debian repository : sudo apt-get install python3-h5py.

However, this solution didn't seem to work for some others, like @JinkaiGUAN.

@petewarden Maybe you or someone from the TF Lite team can confirm this is an outstanding bug and `apt-get` is the preferred package installer for now? cc @dynamicwebpaige

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.
