### ISSUE TITLE
Incorrect number of weights in custom layer containing keras layer

### ISSUE THREAD

**Issue by fferroni** [tensorflow/tensorflow#32778]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below): 1.12.0
- Python version: 3.6
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 9.0, 7.1
- GPU model and memory: Quadro

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
```
class CustomLayer(tf.keras.layers.Layer):
    def __init__(self, dims, **kwargs):
        super(CustomLayer, self).__init__(**kwargs)
        self.dims = dims
        self.dense = tf.keras.layers.Dense(units=self.dims)
        
    def call(self, x, mask=None):
        return self.dense(x)
    
    def get_config(self):
        return {"dims": self.dims}
    
inp = tf.keras.layers.Input(shape=(10,))
x = CustomLayer(32)(inp)
model = tf.keras.models.Model(inp, x)
print(model.summary())
```

The summary contains no weights:
```
Layer (type)                 Output Shape              Param #   
=================================================================
input_5 (InputLayer)         (None, 10)                0         
_________________________________________________________________
custom_layer_2 (CustomLayer) (None, 32)                0         
=================================================================
Total params: 0
Trainable params: 0
Non-trainable params: 0
```

If I try to train, it doesn't seem to do anything
```
model.compile("sgd","mse")
X,Y = np.random.rand(1000,10), np.zeros((1000, 32))
model.fit(X,Y, epochs=20)
```
```
Epoch 1/20
1000/1000 [==============================] - 0s 28us/step - loss: 0.1625
Epoch 2/20
1000/1000 [==============================] - 0s 25us/step - loss: 0.1625
Epoch 3/20
1000/1000 [==============================] - 0s 29us/step - loss: 0.1625
Epoch 4/20
1000/1000 [==============================] - 0s 28us/step - loss: 0.1625
Epoch 5/20
1000/1000 [==============================] - 0s 24us/step - loss: 0.1625
Epoch 6/20
1000/1000 [==============================] - 0s 24us/step - loss: 0.1625
Epoch 7/20
1000/1000 [==============================] - 0s 26us/step - loss: 0.1625
Epoch 8/20
1000/1000 [==============================] - 0s 22us/step - loss: 0.1625
Epoch 9/20
1000/1000 [==============================] - 0s 22us/step - loss: 0.1625
Epoch 10/20
1000/1000 [==============================] - 0s 25us/step - loss: 0.1625
Epoch 11/20
1000/1000 [==============================] - 0s 22us/step - loss: 0.1625
Epoch 12/20
1000/1000 [==============================] - 0s 25us/step - loss: 0.1625
Epoch 13/20
1000/1000 [==============================] - 0s 23us/step - loss: 0.1625
Epoch 14/20
1000/1000 [==============================] - 0s 26us/step - loss: 0.1625
Epoch 15/20
1000/1000 [==============================] - 0s 23us/step - loss: 0.1625
Epoch 16/20
1000/1000 [==============================] - 0s 26us/step - loss: 0.1625
Epoch 17/20
1000/1000 [==============================] - 0s 23us/step - loss: 0.1625
Epoch 18/20
1000/1000 [==============================] - 0s 23us/step - loss: 0.1625
Epoch 19/20
1000/1000 [==============================] - 0s 23us/step - loss: 0.1625
Epoch 20/20
1000/1000 [==============================] - 0s 23us/step - loss: 0.1625
```

**Describe the expected behavior**

I would like to use Keras layers within the custom layer, and have them trainable.

**Comment by ravikyram** [comment]
Is it possible for you to try latest TF versions (`!pip install tensorflow-gpu==1.15.0-rc1`)and let us know whether the issue persists? There were lots of performance improvements in the latest versions. Thanks!

**Comment by fferroni** [comment]
Seems to work appropriately in 1.15. Thanks!
