### ISSUE TITLE
Building TF 2.0 from source returns 1.14 wheel

### ISSUE THREAD

**Issue by chris0914** [tensorflow/tensorflow#32782]
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- TensorFlow installed from (source or binary): source
- TensorFlow version: 2.0 (master branch)
- Python version: 3.6.8
- Installed using virtualenv? pip? conda?: pip
- Bazel version (if compiling from source): 0.26.1
- GCC/Compiler version (if compiling from source): 7.4.0
- CUDA/cuDNN version: 10.1/7.6.3
- GPU model and memory: RTX2080TI

I am trying to build tensorflow 2.0 with GPU support. During the ./configure I enable CUDA (the locations are properly found). Afterwards I start the build with:

bazel build --config=v2 //tensorflow/tools/pip_package:build_pip_package

I had to link python to python3, since Ubuntu 18 has no python 2 and bazel has problems, when no python link is available. The build finishes without any fails.

./bazel-bin/tensorflow/tools/pip_package/build_pip_package --nightly_flag /tmp/tensorflow_pkg

After building the wheel with the above line I can only build tensorflow 1.14

$ ls /tmp/tensorflow_pkg/
tf_nightly-1.14.0-cp36-cp36m-linux_x86_64.whl

Have been trying it multiple times now, even on a clean and fresh Ubuntu 18 setup.

Cheers

**Comment by ayman-saleh** [comment]
This is because you are compiling the master branch which is the stable version of `tensorflow` version `1.14`. Your gonna need to checkout to the `r2.0` branch and recompile.

Run `git checkout r2.0` inside the tensorflow repo.

**Comment by mihaimaruseac** [comment]
We will change version number in master after 2.0 is released.

**Comment by chris0914** [comment]
Thanks to both of you. Expected the master to be the nightly TF2.0 version. With the correct branch everything worked out fine.

Cheers
