### ISSUE TITLE
GELU activation Functions?

### ISSUE THREAD

**Issue by bwindsor22** [tensorflow/tensorflow#32783]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using): TF 2.0.

- Are you willing to contribute it (Yes/No):
Yes, pending review, I would be happy to write this in.

**Describe the feature and the current behavior/state.**
Create a high-level API implementing the GELU activation function.  This was the activation function used in BERT[0], and the GELU authors prove its success on  a number of benchmarks like CIFAR-10[1].

Gelu is not mentioned in a search on tensorflow.org[2]. 

[0] "We use a gelu activation (Hendrycks and Gimpel, 2016) rather than the standard relu, following OpenAI GPT." https://arxiv.org/pdf/1810.04805.pdf
[1]"Ultimately, the GELU obtains a median error rate of 7.89%, the ReLU obtains 8.16%, and the ELU obtains 8.41%."  https://arxiv.org/pdf/1606.08415.pdf
[2] https://www.tensorflow.org/s/results?q=gelu

**Will this change the current api? How?**
Yes, this would expand the API. A good way to implement it would be adding to activations.py [3] The implementation used in BERT, which may need some modification, is here [4].

[3] https://github.com/tensorflow/tensorflow/blob/00fad90125b18b80fe054de1055770cfb8fe4ba3/tensorflow/python/keras/activations.py
[4] https://github.com/google-research/bert/blob/master/modeling.py#L264

**Who will benefit with this feature?**
All developers writing custom layers, particularly those using keras.layers.Dense. 

After implementing, we will not have to worry about any optimization problems which may come from mixing activation functions training on top of BERT models.

**Any Other info.**

**Comment by bionicles** [comment]
```
from math import pi
B = tf.keras.backend


SQRT_2_D_PI = B.sqrt(2 / pi)


@tf.function
def gelu(x):
    right = B.tanh(SQRT_2_D_PI * (x + 0.044715 * B.pow(x, 3)))
    return 0.5 * x * (1 + right)
```

**Comment by fchollet** [comment]
Hello,

Gelu has about 100 hits on ArXiv and has been used in at least one popular model. Given that it would be easy to add and easy to maintain, we can definitely add it to `activations.py`. Feel free to open a PR and assign me as a reviewer.

**Comment by WindQAQ** [comment]
Hi @fchollet, greetings from SIG-Addons. Addons has already had C++/CUDA kernel for gelu activation, which is much faster than Python op. We would like to migrate our implementation to core. Wonder if we should issue a PR for `tf.nn.gelu` first or put all things into one? Thanks!

https://github.com/tensorflow/addons/blob/master/tensorflow_addons/custom_ops/activations/cc/kernels/gelu_op.h
https://github.com/tensorflow/addons/blob/master/tensorflow_addons/activations/gelu.py

**Comment by facaiy** [comment]
@bwindsor22 Hi, Brad. Gelu activation has been implemented in Addons, you might be interested in it: https://github.com/tensorflow/addons/blob/master/tensorflow_addons/activations/README.md

> Feel free to open a PR and assign me as a reviewer.

@fchollet @karmel  Hi, François, Karmel. Is it time to port gelu from addons to tf-core? I believe Tzu-Wei @WindQAQ would like to help it.

**Comment by fchollet** [comment]
@facaiy sounds good, we should port the Addons Gelu to core. Please open a PR.

**Comment by dynamicwebpaige** [comment]
Tagging in @karmel and @seanpmorgan, RE: graduation from `addons` to core.

**Comment by seanpmorgan** [comment]
cc @Windqaq who will be submitting the PR in ~two weeks after exams. There was some discussion about whether or not we should use the C++ implementation or just composite python ops, but the reported speed up looks to be ~3x so IMO we should use the op implementation (which is pretty straight forward):
https://github.com/tensorflow/addons/blob/master/tensorflow_addons/custom_ops/activations/cc/kernels/gelu_op.h#L37

**Comment by bwindsor22** [comment]
Just observing ALBERT followed the GELU trend too. Thanks a million folks!
https://arxiv.org/pdf/1909.11942.pdf

**Comment by bhack** [comment]
Gelu is in Tensorflow now: https://github.com/tensorflow/tensorflow/pull/41178. Can we close this?

**Comment by bwindsor22** [comment]
Looks good to me! Thanks!
