### ISSUE TITLE
Keras Layer.compute_output_shape calls `build` with wrong input shape

### ISSUE THREAD

**Issue by drasmuss** [tensorflow/tensorflow#32786]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.0.0rc2
- Python version: 3.6.8
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

**Describe the current behavior**

When using `Layer.compute_output_shape` or `Layer.compute_output_signature` on a Layer with a `build` function, the `build(input_shape=...)` argument is always set to None.

**Describe the expected behavior**

The `input_shape` should be set to the shape passed to `compute_output_shape`.

**Code to reproduce the issue**
``` python
import tensorflow as tf

shape = (1, 2)


class MyLayer(tf.keras.layers.Layer):
    def build(self, input_shape):
        print(input_shape)
        assert input_shape == shape

    def call(self, inputs):
        return inputs


layer = MyLayer()
layer.compute_output_shape(shape)
```

**Comment by ravikyram** [comment]
I have tried on colab with TF version 2.0.0-rc2 , 2.0.0-dev20190924 and was able to reproduce the issue.Please, find the gist [here](https://colab.sandbox.google.com/gist/ravikyram/4071357c68ee4ac7295198754d9489a0/untitled219.ipynb). Thanks!

**Comment by Saduf2019** [comment]
issue still exist in [nightly and in tensorflow 2.1](https://colab.sandbox.google.com/gist/Saduf2019/8f56913030e3bf31cd3344a9076d6b2d/32786.ipynb)

**Comment by jvishnuvardhan** [comment]
@drasmuss I updated your code to build the layer correctly. With that update, code is not throwing any error. Please check the [gist here](https://colab.research.google.com/gist/jvishnuvardhan/00a883bdcb7bcd40f9f1007176d99df4/32786.ipynb).

```
import tensorflow as tf

shape = (1, 2)


class MyLayer(tf.keras.layers.Layer):

  def __init__(self, **kwargs):
        super(MyLayer, self).__init__(**kwargs)
        
  def build(self, input_shape):
      print(input_shape)
      super(MyLayer, self).build(input_shape)
      assert input_shape == shape

  def call(self, inputs):
      return inputs


layer = MyLayer()
layer.build(shape)
layer.compute_output_shape(shape)
```

Please close the issue if this was resolved for you. Thanks!

**Comment by drasmuss** [comment]
I don't think that solves the issue, it just avoids it by explicitly calling `build` ahead of time (with the correct shape). The problem that is being highlighted in this issue is that when `compute_output_shape` calls `build` automatically, it calls it with the wrong shape.

It says right in the docstring of `compute_output_shape` that it shouldn't be necessary to manually call `build`, so I don't think this is expected behaviour:
> Computes the output shape of the layer.
>
>If the layer has not been built, this method will call build on the layer. This assumes that the layer will later be used with inputs that match the input shape provided here.

https://www.tensorflow.org/api_docs/python/tf/keras/layers/Layer#compute_output_shape

**Comment by tanzhenyu** [comment]
Re-assigning to Yanhui

**Comment by yhliang2018** [comment]
Hi @drasmuss there is a fix just submitted, and you may verify it with tf-nightly later. Close this for now, and feel free to reopen it if needed. Thanks.
