### ISSUE TITLE
Implement 3D data for LSTM RNN -- request

### ISSUE THREAD

**Issue by KendallWeihe** [tensorflow/tensorflow#3278]
I'm new to this, and I'm not sure where is the appropriate place to make a dev requests. If I am in the wrong place, can someone please redirect me?

I am not an experienced Tensorflow dev or I would try to build this myself, but I think it is a really interesting idea and I would love for another dev to build it. 

The idea is for an LSTM RNN to accept 3D data -- such as video frames. I'm interested in papers such as [this](http://cvgl.stanford.edu/papers/CVPR16_Social_LSTM.pdf), where LSTM RNN's are used for object tracking. Also [this](http://mediatum.ub.tum.de/doc/1138498/100891.pdf) paper.

Is there a way to do this already in Tensorflow?

I know I can flatten data, but that kind of defeats the point. I want a 3D network. In other words, please look at the attached picture for what I am envisioning. 

![file_000](https://cloud.githubusercontent.com/assets/3602993/16751849/9e9e25fa-47aa-11e6-89b3-ed4fe4b6b174.jpeg)

Each frame is a full layer (in a horizontal direction). The second layer has inputs from both the second frame and the outputs from the first frame.

**Comment by jmchen-g** [comment]
@ebrevdo Could you take a look at this please?

**Comment by ebrevdo** [comment]
Perhaps you want each frame convolved with some trainable kernel. See the cell types in tf.contrib.rnn and tf.contrib.grid_rnn.  perhaps something there already does what you want.

**Comment by KendallWeihe** [comment]
Grid LSTM RNNs support n-dimensional inputs in theory, but since the Tensorflow implementation uses the `RNNCell` object, the network requires a list of inputs, as opposed to say a 3D volume.

**Comment by KendallWeihe** [comment]
I posted [this](http://stackoverflow.com/questions/38855807/tensorflow-grid3lstmcell-visualization) to SO, it may be way I'm looking for. In which case we can close this issue.

**Comment by ebrevdo** [comment]
Closed per @KendallWeihe as this does sound like more of a design discussion, rather than a bug.
