### ISSUE TITLE
tf.config namespace not available in rc1/2 (was available in beta0)

### ISSUE THREAD

**Issue by speediedan** [tensorflow/tensorflow#32795]
**System information**
tf_env.txt attached

**The Issue**
tf.config namespace is not available in TF 2.0 rc1 and rc2 while it was available in beta0 releases and before. I see no indication that this namespace is being deprecated or changed in the documentation.

```
AttributeError Traceback (most recent call last)
<ipython-input-1-a65a6ef9c8ca> in <module>
      1 import tensorflow as tf
----> 2 print(tf.config.experimental.list_physical_devices('CPU'))
AttributeError: module 'tensorflow' has no attribute 'config'
```

**Expected behavior**
API functionality under tf.config namespace should be available unless otherwise indicated in the documentation. The latest API info says it should be there:
https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/config/experimental/list_physical_devices

**Code to reproduce the issue**
```python
import tensorflow as tf
print(tf.config.experimental.list_physical_devices('CPU'))
```
[tf_env.txt](https://github.com/tensorflow/tensorflow/files/3650032/tf_env.txt)

**Comment by foxik** [comment]
The `tf.config` works just fine for me with TF 2.0 rc2. Looking into `tf_env.txt`, I contains the following:
```
== check pips ===================================================
numpy                    1.17.2              
protobuf                 3.9.2               
tensorflow               2.0.0rc2            

...

== tensorflow import ============================================
tf.version.VERSION = 1.13.1
```
so it seems you have both TF 2.0.0rc2 and 1.13.1 installed, and `import tensorflow` actually imports the 1.13.1 version, which of course does not have `tf.config`.

**Comment by speediedan** [comment]
:: slaps forehead :: I've been upgrading from one tf2.0 pre-release version to the next without issue for months but still can't believe I overlooked this possibility! tensorflow 1.13 was apparently a dependency of a conda-forge package I had installed long ago that I inadvertently reinstalled. SMH. Thanks!
