### ISSUE TITLE
can not watch the version of tensorflow 1.14.0 by tensorflow.__version__

### ISSUE THREAD

**Issue by smartcatdog** [tensorflow/tensorflow#32798]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version:
- Python version:
- Installed using virtualenv? pip? conda?:
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Describe the problem**

**Provide the exact sequence of commands / steps that you executed before running into the problem**

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.
here are some information about installing some packages like python and tensorflow[CPU] 
```
Python 3.7.4 [Clang 10.0.0 (clang-1000.11.45.5)] 
tensorflow                       1.14.0
tensorflow-estimator             1.14.0
tensorflow-federated             0.7.0
tensorflow-model-optimization    0.1.2
```
`import tensorflow as tf` is ok, however, i want to check tensorflow version by `tf.__version__` , errors happened:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Python/3.7/lib/python/site-packages/tensorflow_core/python/util/module_wrapper.py", line 171, in __getattr__
    raise e
  File "/Library/Python/3.7/lib/python/site-packages/tensorflow_core/python/util/module_wrapper.py", line 168, in __getattr__
    attr = getattr(self._tfmw_wrapped_module, name)
AttributeError: module 'tensorflow' has no attribute '__version__'
```

**Comment by ravikyram** [comment]
Can you please go through #32768 and see if it helps you.Thanks!

**Comment by mihaimaruseac** [comment]
Can you also fill in the template in the bug please? In particular operating system, python version and the way you obtained tensorflow (pip, conda, from source, in a virtualenv or global?)

**Comment by ravikyram** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
