### ISSUE TITLE
ModuleNotFoundError: No module named 'tensorflow.examples.tutorials'

### ISSUE THREAD

**Issue by hassanshallal** [tensorflow/tensorflow#32790]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (macOS Mojave 10.14.6):
- TensorFlow installed from (source):
- TensorFlow version: 2.0.0-rc1
- Python version: Python 3.7.4
- Installed using virtualenv? pip? conda?: pip

**Describe the problem**
I am trying to run a basic mnist classifier tutorial using tensorflow (without keras) and I am getting the following error:
Upon running:
`from tensorflow.examples.tutorials.mnist import input_data`
I get the following error:
ModuleNotFoundError: No module named 'tensorflow.examples.tutorials'

Any help of how to fix this issue is highly appreciated.

**Comment by boegel** [comment]
@hassanshallal I'm hitting the same problem, did you figure out a fix for this?

**Comment by hassanshallal** [comment]
I ended up using tfds:

```
import tensorflow_datasets as tfds
# Construct a tf.data.Dataset
dataset = tfds.load(name="mnist", split=tfds.Split.TRAIN)
```

**Comment by angelandy** [comment]
do you install tf using docker?

**Comment by boegel** [comment]
I didn't (and I don't think it matters)

**Comment by JenniferOH** [comment]
I'm also having exactly the same problem with Tensorflow 2.0.0
I changed the TensorFlow version to 1.14.0 and I was able to import tensorflow.examples.tutorials.mnist

I don't know why this is happening. There seems to be no change in the examples package code.

**Comment by RedemptionOfRoad** [comment]
I think the Tensorflow 2.0.0 can't support to import tensorflow.examples.tutorials. Beacause I found the packages of tensorflow-core/examples had no the module named by turorials under my environment of anaconda installation. Finally, I changed the Tensorflow version to 1.14.0 and it did work! I'm very confused.

**Comment by DBernardes** [comment]
I found a solution at this link: https://blog.csdn.net/weixin_41663570/article/details/102512468

You just need to download the lost files and copy them to the tensorflow-core/ examples.

**Comment by HumorLogic** [comment]
I met

> I found a solution at this link: https://blog.csdn.net/weixin_41663570/article/details/102512468
> 
> You just need to download the lost files and copy them to the tensorflow-core/ examples.

I use this method to solve the problem

**Comment by asears** [comment]
This breaks a bunch of community code and tutorials.  Could the issue be reopened and fixed as part of the tensorflow or datasets packages?  A straight install of conda install tensorflow and conda install tensorflow-datasets didn't solve the issue.  

Why not conda/pip install tensorflow-examples?  Copying lost files manually doesn't seem like a good approach.  Examples should probably state that they use older version code.

**Comment by rooivalk-lang** [comment]
I don't get it, I buy a book called Deep Learning for Games, and know half of all the codes within the book doesn't with tensorflow 2.0, what is the use if you want to learn deep programming?????
Idiots need to up their brains.

**Comment by mehdishafiei** [comment]
I had the same problem with TF2. In the tutorial that I had the following codes:

```
from tensorflow.examples.tutorials.mnist import input_data
mnist = input_data.read_data_sets("/tmp/data/", one_hot=False)
```
In in tf2, it turns out that **I don't need** that turorial package, just  write:

`mnist = tf.keras.datasets.mnist`

**Comment by uroosehar1** [comment]
> I had the same problem with TF2. In the tutorial that I had the following codes:
> 
> ```
> from tensorflow.examples.tutorials.mnist import input_data
> mnist = input_data.read_data_sets("/tmp/data/", one_hot=False)
> ```
> 
> In in tf2, it turns out that **I don't need** that turorial package, just write:
> 
> `mnist = tf.keras.datasets.mnist`

but because of this it doesnot act like a dataset. Now it act like a module

**Comment by uroosehar1** [comment]
For this perticular problem of not getting ModuleNotFoundError: No module named 'tensorflow.examples.tutorials, i followed the following way to solve this issue.. and it solved in my case.
URL for Solution: https://www.youtube.com/watch?v=CH8uW3abI9A&feature=youtu.be

**Comment by uroosehar1** [comment]
> _Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template_
> 
> **System information**
> 
> * OS Platform and Distribution (macOS Mojave 10.14.6):
> * TensorFlow installed from (source):
> * TensorFlow version: 2.0.0-rc1
> * Python version: Python 3.7.4
> * Installed using virtualenv? pip? conda?: pip
> 
> **Describe the problem**
> I am trying to run a basic mnist classifier tutorial using tensorflow (without keras) and I am getting the following error:
> Upon running:
> `from tensorflow.examples.tutorials.mnist import input_data`
> I get the following error:
> ModuleNotFoundError: No module named 'tensorflow.examples.tutorials'
> 
> Any help of how to fix this issue is highly appreciated.

For this perticular problem of not getting ModuleNotFoundError: No module named 'tensorflow.examples.tutorials, i followed the following way to solve this issue.. and it solved in my case.
URL for Solution: https://www.youtube.com/watch?v=CH8uW3abI9A&feature=youtu.be

**Comment by BobTsang1995** [comment]
> 我在此链接上找到了解决方案：[https](https://blog.csdn.net/weixin_41663570/article/details/102512468) : [//blog.csdn.net/weixin_41663570/article/details/102512468](https://blog.csdn.net/weixin_41663570/article/details/102512468)
> 
> 您只需要下载丢失的文件并将它们复制到tensorflow-core /示例。

I use this way 

> I found a solution at this link: https://blog.csdn.net/weixin_41663570/article/details/102512468
> 
> You just need to download the lost files and copy them to the tensorflow-core/ examples.

i use this way to copy the 'tutorials' file into the tensorflow_core/example file. but it seems not work. my ide sent me this error:ImportError: cannot import name 'tutorials' from 'tensorflow_core.examples'

**Comment by BobTsang1995** [comment]
> I found a solution at this link: https://blog.csdn.net/weixin_41663570/article/details/102512468
> 
> You just need to download the lost files and copy them to the tensorflow-core/ examples.

i use this way to copy the 'tutorials' file into the tensorflow_core/example file. but it seems not work. my ide sent me this error:ImportError: cannot import name 'tutorials' from 'tensorflow_core.examples'

**Comment by unexposed7** [comment]
After cloning all git repo, and made it run ... had the following warning:

tensorflow:
read_data_sets (from tensorflow.examples.tutorials.mnist.input_data) 
is deprecated and will be removed in a future version.

Please use alternatives such as: tensorflow_datasets.load('mnist')

**Comment by uroosehar1** [comment]
OK :)




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Nikolaos M Petridis"<notifications@github.com&gt;; 
发送时间: 2020年4月22日(星期三) 上午9:18
收件人: "tensorflow/tensorflow"<tensorflow@noreply.github.com&gt;; 
抄送: "1505253990"<1505253990@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [tensorflow/tensorflow] ModuleNotFoundError: No module named &#39;tensorflow.examples.tutorials&#39; (#32790)





 
After cloning all git repo, and made it run ... had the following warning:
 
tensorflow:
 read_data_sets (from tensorflow.examples.tutorials.mnist.input_data)
 is deprecated and will be removed in a future version.
 
Please use alternatives such as: tensorflow_datasets.load('mnist')

**Comment by yzwer** [comment]
**The tf1 API be used under the tf2 env：**
`import tensorflow.compat.v1 as tf`
`tf.disable_v2_behavior()`

**Comment by yanxg** [comment]
Two options:

1) use pip show tensorflow in somewhere you have already imported tensorflow; then you will find the location of your tensorflow under the name of Location; then go to the location; and then go to tensorflow_core under the location and then go to the examples; under the examples, download tutorials in https://github.com/tensorflow/tensorflow/tree/master/tensorflow/examples/tutorials; then copy the tutorials to the previous location.

2) use the minist in keras that is included in tensorflow 2.0 to get MNIST dataset

**Comment by bhkgrwl11** [comment]
Just downgrade the version of tensorflow to 1.14 will resolve this, if you are using navigator then you can directly downgrade there if you have already created and installed the tensorflow environment. Just click the check option and mark for specific version to apply.

**Comment by sachinkm308** [comment]
> For this perticular problem of not getting ModuleNotFoundError: No module named 'tensorflow.examples.tutorials, i followed the following way to solve this issue.. and it solved in my case.
> URL for Solution: https://www.youtube.com/watch?v=CH8uW3abI9A&feature=youtu.be

This worked! Thanks a ton!!

**Comment by amardeep-singh97** [comment]
TF2 does not support from `tensorflow.examples.tutorials.mnist import input_data`
Instead using older version of Tensorflow just go ahead with
`pip install tensorflow-datasets` or `conda install tensorflow-datasets`
Use the data set by following code
`import tensorflow_datasets as datasets`
`mnist = datasets.load(name='mnist')`

**Comment by purosh96** [comment]
Check the TensorFlow version. 
>>> tf.__version__
This may help:
https://github.com/purosh96/NeuralNetwork/blob/main/MNIST_Tensorflow_1X_ShallowNN.ipynb

**Comment by prasanjitdash** [comment]
> I found a solution at this link: https://blog.csdn.net/weixin_41663570/article/details/102512468
> 
> You just need to download the lost files and copy them to the tensorflow-core/ examples.

Are you sure of the link? It shows something in a different non-Latin script language.

**Comment by fgmn** [comment]
> I'm also having exactly the same problem with Tensorflow 2.0.0 I changed the TensorFlow version to 1.14.0 and I was able to import tensorflow.examples.tutorials.mnist
> 
> I don't know why this is happening. There seems to be no change in the examples package code.

require the least things to do
