### ISSUE TITLE
When does tensorflow lite support 3d cnn?

### ISSUE THREAD

**Issue by Jessespace** [tensorflow/tensorflow#32796]
I trained 3d cnn network on tensorflow, now I want to port to Android phone, but browsed the document and found that tensorflow-lite does not support 3d cnn operation, when will it support it?

**Comment by liyunlu0618** [comment]
Can you tell us more about your use case to help us prioritize? For example, what kind of task this model is trying to do, its application scenarios, etc. Thanks!

**Comment by hyperfraise** [comment]
For me, it's video classifiction and temporal detection.

**Comment by rmothukuru** [comment]
@Jessespace,
Can you please refer [this Tutorial](https://www.tensorflow.org/hub/tutorials/action_recognition_with_tf_hub) which demonstrates the use of **`3D CNN`** and let us know if it helps? Thanks!

**Comment by hyperfraise** [comment]
This tutorial isn't about tensorflow-lite, is it ?

I see here that still no 3d ops are supported https://www.tensorflow.org/mlir/tfl_ops

I see in quantization schemes that 3D conv still isn't supported https://www.tensorflow.org/lite/performance/quantization_spec

**Comment by mohantym** [comment]
Hi @Jessespace !
Could you check this [Kaggle code](https://www.kaggle.com/code/widhiwinata/cnn-model-into-tf-lite-model) on CNN to TFlite ( channel is 3 in this code).
Thank you!

**Comment by hyperfraise** [comment]
> Hi @Jessespace !
> Could you check this [Kaggle code](https://www.kaggle.com/code/widhiwinata/cnn-model-into-tf-lite-model) on CNN to TFlite ( channel is 3 in this code).
> Thank you!

I don't see any 3d conv on this link.

**Comment by hyperfraise** [comment]
This is still relevant.

**Comment by mohantym** [comment]
@Jessespace @hyperfraise !
I do see Conv3D, Conv3Dbackprop  in select ops allow list for which you can use select ops syntax during model-lite file conversion.
Could your provide a stand alone with [select ops syntax ](https://www.tensorflow.org/lite/guide/ops_select#convert_a_model)to replicate this issue 
Thank you!

**Comment by hyperfraise** [comment]
Hey. I don't know when it happened, but you're right. I successfully converted from onnx to tensorflow lite a 3d conv model and ran inferences. Thanks !

**Comment by mohantym** [comment]
Ok @hyperfraise !

Thank you for your confirmation . Moving this to closed status for now.
Feel free to create a new ticket if you need further assistance.

Thank you!

**Comment by mohantym** [comment]
Are you satisfied with the resolution of your issue?
[Yes](https://goo.gl/forms/Oe0tEvODFRoI2gJF3)
[No](https://goo.gl/forms/fUjzOfrtkFbrOT8d2)
