### ISSUE TITLE
initializing seq2seq embedding with pretrained w2v

### ISSUE THREAD

**Issue by kienwei** [tensorflow/tensorflow#328]
Hi, is there a straightforward way to initialize seq2seq embedding with pretrained w2v?

the embedding variable is in the embedding_tied_seq2seq (the model I am using). is there anyway to access this variable from translate.py and call .assign() to assign it after random initialisation with all other variables?? is there a global variable name I could call for this embedding?

**Comment by cinjon** [comment]
Check out the answer on the google groups here: https://groups.google.com/a/tensorflow.org/forum/#!topic/discuss/bH6S98NpIJE

The short answer given by Rafal is:
```
You can initialize it randomly and afterwards do:
session.run(embedding.assign(my_word2vec_matrix))

You need to do separate assigns for the encoder and decoder.
```

**Comment by girving** [comment]
Closing.  For future reference, this kind of question is better on stackoverfow.
