### ISSUE TITLE
Why the communication of distributed training not hidden when using XLA?

### ISSUE THREAD

**Issue by zhuhong** [tensorflow/tensorflow#32808]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): None
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): nvcr.io/nvidia/tensorflow:19.03-py3 ; 
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): 

- TensorFlow version (use command below):  tf 1.13.1 ; 
- Python version:
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**

 Recently, we have designed a tool to monitor the communication of distributed training process in microsecond. As we all know that the commnuication is hidden in the back-propagation progress; and that's true in my monitoring, like the yellow line in the figure below, that is with XLA disabled. But when we enable the XLA, the traffic between GPU is suspend until the finish of the back-propagation in my figure (blue line). So, is there anyone can help me to figure out the principle behind this phenomenon. Since the traffic can not be hidden in the back-propagation progress, the requirement of the bandwidth for the hardware, like nv-link in the server or infiniband network between servers goes up a lot. 

![下载 (3)](https://user-images.githubusercontent.com/5318606/65588391-0ad2a980-dfba-11e9-8c70-1815edc17bce.png)

**Describe the expected behavior**

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by sanjoy** [comment]
This is probably because of bad clustering decisions that is decreasing concurrency / overlapped execution.  Can you give us instructions on how to reproduce this?

CC @trentlo @cheshire @tpopp

**Comment by trentlo** [comment]
Looks like a similar issue as the description about the HorovodAllReduce nodes in this [report](https://docs.google.com/document/d/1q1UPN2CRRNBoUXM0zORT-cTG9m7ctQRB2xfUPhaK1Ek/edit?usp=sharing).

Wondering which model you are running? Is it with Horovod?

**Comment by zhuhong** [comment]
hi，trentlo；
1. I find this phenomenon using horovod and also in tensorflow distributed strategy.  
2. I find this phenomenon training resnet50 and also bert-large squad. 
So, I think this is a XLA internal issue.

**Comment by zhuhong** [comment]
> This is probably because of bad clustering decisions that is decreasing concurrency / overlapped execution. Can you give us instructions on how to reproduce this?
> 
> CC @trentlo @cheshire @tpopp

Hi, trentlo

using nvcr.io/nvidia/tensorflow:19.03-py3  + tf_benchmark 1.13 + resnet50 or other cnn models + xla

**Comment by zhuhong** [comment]
hi， guys； any update？

**Comment by sanjoy** [comment]
@zhuhong realistically, I won't have time for this anytime soon.  Can you try using the [TensorBoard profiler](https://www.tensorflow.org/tensorboard/tensorboard_profiling_keras) on your model to see something obvious shows up?
