### ISSUE TITLE
Problem to transform an custom efficient-net with an unofficial API to tf-lite version

### ISSUE THREAD

**Issue by momo1986** [tensorflow/tensorflow#32802]
**System information**
- OS Platform and Distribution (Linux Ubuntu 18.04):
- TensorFlow installed from source:
- TensorFlow version (1.12):
- Keras version (2.2.4)

Hello, I use this Keras-repository to deploy my efficient-net-model for specific application.
https://github.com/titu1994/keras-efficientnets

I want to transform the h5-file to tflite and met some problems.

My code is:
```
import tensorflow as tf
import keras
import h5py
import keras_efficientnets
from custom_objects import EfficientNetConvInitializer
from custom_objects import EfficientNetDenseInitializer
from custom_objects import Swish, DropConnect
if __name__ == "__main__":
    debugger = EfficientNetConvInitializer()
    converter = tf.contrib.lite.TFLiteConverter.from_keras_model_file("efficient_net_v1_190925.h5")
    converter.optimizations = [tf.contrib.lite.Optimize.OPTIMIZE_FOR_SIZE]
    tflite_model = converter.convert()
    open("efficient_net_wrap_finger.tflite", "wb").write(tflite_model)
```
My problem is:

> Using TensorFlow backend.
> Traceback (most recent call last):
>   File "model_convert.py", line 10, in <module>
>     converter = tf.contrib.lite.TFLiteConverter.from_keras_model_file("efficient_net_v1_190925.h5")
>   File "/root/anaconda3/lib/python3.6/site-packages/tensorflow/contrib/lite/python/lite.py", line 368, in from_keras_model_file
>     keras_model = _keras.models.load_model(model_file)
>   File "/root/anaconda3/lib/python3.6/site-packages/tensorflow/python/keras/engine/saving.py", line 230, in load_model
>     model = model_from_config(model_config, custom_objects=custom_objects)
>   File "/root/anaconda3/lib/python3.6/site-packages/tensorflow/python/keras/engine/saving.py", line 310, in model_from_config
>     return deserialize(config, custom_objects=custom_objects)
>   File "/root/anaconda3/lib/python3.6/site-packages/tensorflow/python/keras/layers/serialization.py", line 64, in deserialize
>     printable_module_name='layer')
>   File "/root/anaconda3/lib/python3.6/site-packages/tensorflow/python/keras/utils/generic_utils.py", line 173, in deserialize_keras_object
>     list(custom_objects.items())))
>   File "/root/anaconda3/lib/python3.6/site-packages/tensorflow/python/keras/engine/network.py", line 1292, in from_config
>     process_layer(layer_data)
>   File "/root/anaconda3/lib/python3.6/site-packages/tensorflow/python/keras/engine/network.py", line 1278, in process_layer
>     layer = deserialize_layer(layer_data, custom_objects=custom_objects)
>   File "/root/anaconda3/lib/python3.6/site-packages/tensorflow/python/keras/layers/serialization.py", line 64, in deserialize
>     printable_module_name='layer')
>   File "/root/anaconda3/lib/python3.6/site-packages/tensorflow/python/keras/utils/generic_utils.py", line 175, in deserialize_keras_object
>     return cls.from_config(config['config'])
>   File "/root/anaconda3/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer.py", line 1606, in from_config
>     return cls(**config)
>   File "/root/anaconda3/lib/python3.6/site-packages/tensorflow/python/keras/layers/convolutional.py", line 488, in __init__
>     kernel_initializer=initializers.get(kernel_initializer),
>   File "/root/anaconda3/lib/python3.6/site-packages/tensorflow/python/keras/initializers.py", line 155, in get
>     return deserialize(identifier)
>   File "/root/anaconda3/lib/python3.6/site-packages/tensorflow/python/keras/initializers.py", line 147, in deserialize
>     printable_module_name='initializer')
>   File "/root/anaconda3/lib/python3.6/site-packages/tensorflow/python/keras/utils/generic_utils.py", line 163, in deserialize_keras_object
>     raise ValueError('Unknown ' + printable_module_name + ': ' + class_name)
> ValueError: Unknown initializer: EfficientNetConvInitializer

What is the root-cause for this problem?

Can I clarify that keras-efficient-net API is not compatible with official tensorflow lite support?
Is there any work-around that I can build an efficent-net and depoly on my mobile device?

Thanks & Regards!

**Comment by jdduke** [comment]
Over to @xunkai55 who has experience with EfficientNet.

**Comment by momo1986** [comment]
Same problem when I refer to some Keras MobileNetv3 customed model for tf-lite transorfmation:

> Traceback (most recent call last):
>   File "model_converter.py", line 14, in <module>
>     converter = tf.lite.TFLiteConverter.from_keras_model_file(keras_model_path)
>   File "E:\Users\Admin\Anaconda3\envs\converter_from_cloud_to_cpu\lib\site-packages\tensorflow\lite\python\lite.py", line 747, in from_keras_model_file
>     keras_model = _keras.models.load_model(model_file, custom_objects)
>   File "E:\Users\Admin\Anaconda3\envs\converter_from_cloud_to_cpu\lib\site-packages\tensorflow\python\keras\saving\save.py", line 146, in load_model
>     return hdf5_format.load_model_from_hdf5(filepath, custom_objects, compile)
>   File "E:\Users\Admin\Anaconda3\envs\converter_from_cloud_to_cpu\lib\site-packages\tensorflow\python\keras\saving\hdf5_format.py", line 212, in load_model_from_hdf5
>     custom_objects=custom_objects)
>   File "E:\Users\Admin\Anaconda3\envs\converter_from_cloud_to_cpu\lib\site-packages\tensorflow\python\keras\saving\model_config.py", line 55, in model_from_config
>     return deserialize(config, custom_objects=custom_objects)
>   File "E:\Users\Admin\Anaconda3\envs\converter_from_cloud_to_cpu\lib\site-packages\tensorflow\python\keras\layers\serialization.py", line 89, in deserialize
>     printable_module_name='layer')
>   File "E:\Users\Admin\Anaconda3\envs\converter_from_cloud_to_cpu\lib\site-packages\tensorflow\python\keras\utils\generic_utils.py", line 192, in deserialize_keras_object
>     list(custom_objects.items())))
>   File "E:\Users\Admin\Anaconda3\envs\converter_from_cloud_to_cpu\lib\site-packages\tensorflow\python\keras\engine\network.py", line 1121, in from_config
>     process_layer(layer_data)
>   File "E:\Users\Admin\Anaconda3\envs\converter_from_cloud_to_cpu\lib\site-packages\tensorflow\python\keras\engine\network.py", line 1105, in process_layer
>     layer = deserialize_layer(layer_data, custom_objects=custom_objects)
>   File "E:\Users\Admin\Anaconda3\envs\converter_from_cloud_to_cpu\lib\site-packages\tensorflow\python\keras\layers\serialization.py", line 89, in deserialize
>     printable_module_name='layer')
>   File "E:\Users\Admin\Anaconda3\envs\converter_from_cloud_to_cpu\lib\site-packages\tensorflow\python\keras\utils\generic_utils.py", line 194, in deserialize_keras_object
>     return cls.from_config(cls_config)
>   File "E:\Users\Admin\Anaconda3\envs\converter_from_cloud_to_cpu\lib\site-packages\tensorflow\python\keras\engine\base_layer.py", line 446, in from_config
>     return cls(**config)
>   File "E:\Users\Admin\Anaconda3\envs\converter_from_cloud_to_cpu\lib\site-packages\tensorflow\python\keras\layers\core.py", line 357, in __init__
>     self.activation = activations.get(activation)
>   File "E:\Users\Admin\Anaconda3\envs\converter_from_cloud_to_cpu\lib\site-packages\tensorflow\python\keras\activations.py", line 306, in get
>     return deserialize(identifier)
>   File "E:\Users\Admin\Anaconda3\envs\converter_from_cloud_to_cpu\lib\site-packages\tensorflow\python\keras\activations.py", line 297, in deserialize
>     printable_module_name='activation function')
>   File "E:\Users\Admin\Anaconda3\envs\converter_from_cloud_to_cpu\lib\site-packages\tensorflow\python\keras\utils\generic_utils.py", line 211, in deserialize_keras_object
>     raise ValueError('Unknown ' + printable_module_name + ':' + object_name)
> ValueError: Unknown activation function:_hard_swish

The code is defined in this repository:
https://github.com/xiaochus/MobileNetV3

```
    def _hard_swish(self, x):
        """Hard swish
        """
        return x * K.relu(x + 3.0, max_value=6.0) / 6.0
```

I try to import the header file, e.g.
`from mobilenetv3_model.mobilenet_base import MobileNetBase`

Failure to tf-lite transformation.

It looks same with the problem of efficientnet model, tf-lite authorities do not support the customed Keras activation function or kernel function.

How to resolve the problem?

Thanks & Regards！

**Comment by xunkai55** [comment]
Hi Momo1986, sorry I've been in traveling and vacation for a while. I'll take a look and get back to you soon.

**Comment by renjie-liu** [comment]
it seems it hasn't come down to tflite yet, I think you need to make your function serializable by keras

**Comment by momo1986** [comment]
> it seems it hasn't come down to tflite yet, I think you need to make your function serializable by keras

Hello，@renjie-liu. I use keras.models.Sequential(model) for saving to realize the goal of serialization.
Problem still have.

Thanks & Regards!

**Comment by renjie-liu** [comment]
Hi Momo,

I mean your function needs to be serializable by Keras.

Also added Tiezhen who is the expert in Keras model.

**Comment by momo1986** [comment]
Hello, @renjie-liu .
It looks like questionable modules are defined by developer themselves rather than official Keras team.
EfficientNetConvInitializer is such a customed object.
https://github.com/titu1994/keras-efficientnets/blob/master/keras_efficientnets/custom_objects.py
```
get_custom_objects().update({
    'EfficientNetConvInitializer': EfficientNetConvInitializer,
    'EfficientNetDenseInitializer': EfficientNetDenseInitializer,
    'DropConnect': DropConnect,
    'Swish': Swish,
})
```

Customed API is called by EfficientNet and EfficientNet will be trained on specific dataset. It is OK in server to be saved with hdf5 file. However, it cannot be converted to tf-lite.

Thanks & Regards!

**Comment by wangtz** [comment]
Looking at the traceback, it did hit tflite converter codepath.

converter = tf.contrib.lite.TFLiteConverter.from_keras_model_file("efficient_net_v1_190925.h5")
File "/root/anaconda3/lib/python3.6/site-packages/tensorflow/contrib/lite/python/lite.py", line 368, in from_keras_model_file

Assigning the bug to Haoliang to help identify if it's a problem with the converter.

**Comment by haozha111** [comment]
Can you try with the new TF Lite converter?

Install latest tf-nightly, and then try:
converter.experimental_new_converter = True.

(The tensorflow version you use is a bit old, please try with tf-nightly to see if your issue persists).

**Comment by momo1986** [comment]
Hello, I found a workaround.

1. Using tensorflow2.0
2. Using custom object corresponding APIs.

Here is a guide in Chines to convert efficient_net to tensorflow-lite.
https://zhuanlan.zhihu.com/p/89599048
Regards.
Jun Yan

**Comment by y26805** [comment]
Translation & code snippet from https://zhuanlan.zhihu.com/p/89599048 for friends who do not read Chinese:

Requirements:
- tensorflow 2.x
- if model is trained in native Keras, do `import tf.keras as keras`

Code snippet:
```
import functools
import keras
import os
from efficientnet import model
from tensorflow.python.keras.utils import CustomObjectScope, get_custom_objects

def inject_keras_modules(func):
    @functools.wraps(func)
    def wrapper(*args, **kwargs):
        kwargs['backend'] = keras.backend
        kwargs['layers'] = keras.layers
        kwargs['models'] = keras.models
        kwargs['utils'] = keras.utils
        return func(*args, **kwargs)

    return wrapper
def init_keras_custom_objects():
    custom_objects = {
        'swish': inject_keras_modules(model.get_swish)(),
        'FixedDropout': inject_keras_modules(model.get_dropout)()
    }

    get_custom_objects().update(custom_objects)

init_keras_custom_objects()
keras_model_path = './some_model.h5'
save_model = tf.keras.models.load_model(keras_model_path)
export_dir='save'
tf.saved_model.save(save_model, export_dir)
new_model = tf.saved_model.load(export_dir)

IMAGE_WIDTH = 64 # example
with CustomObjectScope({'swish': inject_keras_modules(model.get_swish)(),
                        'FixedDropout': inject_keras_modules(model.get_dropout)()}):
    concrete_func = new_model.signatures[
        tf.saved_model.DEFAULT_SERVING_SIGNATURE_DEF_KEY]
    concrete_func.inputs[0].set_shape([1, IMAGE_WIDTH, IMAGE_WIDTH, 3])
    converter = tf.lite.TFLiteConverter.from_concrete_functions([concrete_func])

concrete_func = new_model.signatures[
        tf.saved_model.DEFAULT_SERVING_SIGNATURE_DEF_KEY]
concrete_func.inputs[0].set_shape([1, IMAGE_WIDTH, IMAGE_WIDTH, 3])
converter = tf.lite.TFLiteConverter.from_concrete_functions([concrete_func])

MODEL_OUTPUT_PATH = "efficient_net_b0.tflite"
converter.optimizations = [tf.lite.Optimize.OPTIMIZE_FOR_SIZE]
converter.allow_custom_ops = True
tflite_model = converter.convert()
open(MODEL_OUTPUT_PATH, "wb").write(tflite_model)


```

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.
