### ISSUE TITLE
Default env python maybe different from python selected in config step

### ISSUE THREAD

**Issue by gbkedar** [tensorflow/tensorflow#3280]
Python that is default in the environment maybe different from the one selected in the  configure step. [File](https://github.com/tensorflow/tensorflow/blob/master/third_party/gpus/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc)
calls ``#!/usr/bin/env python``, it should instead be the one defined in the configuration step.

**Comment by jmchen-g** [comment]
Thanks for reporting. 
@vrv Could you take a look at this please?

**Comment by vrv** [comment]
I'm really not sure what we can do here, short of rewriting all python files during configure (which would be insane) -- I would suggest using an environment where the python you use in your configure step matches the environment.  If someone else has any suggestions, please let us know.
