### ISSUE TITLE
UpSampling2D doesn't support bfloat16

### ISSUE THREAD

**Issue by fsx950223** [tensorflow/tensorflow#32801]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): no
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version (use command below): nightly
- Python version: 3.6.8
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
TypeError: Value passed to parameter 'images' has DataType bfloat16 not in list of allowed values: int8, uint8, int16, uint16, int32, int64, float16, float32, float64
**Describe the expected behavior**
support bfloat16
**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.
``` python
import tensorflow as tf
input = tf.keras.Input(shape=(28, 28, 1), name='img',dtype=tf.bfloat16)
x = tf.keras.layers.UpSampling2D(3)(input)
```
**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by jvishnuvardhan** [comment]
@fsx950223 I could reproduce the issue with `TF1.15.0`. Here is the [gist](https://colab.sandbox.google.com/gist/jvishnuvardhan/371cabae8a54797e13b887103170f6c6/untitled629.ipynb) with `TF1.15.0`.

However, your code works without an issue using `TF2.0`. Please take a look at the [gist](https://colab.sandbox.google.com/gist/jvishnuvardhan/701fd556c91f231b7cc2316fe53d62d4/untitled628.ipynb). 

I think there may not be any updates to `TF1.15.0` unless the issue is related to security. Are you willing to upgrade to `TF2.0`? Thanks!

**Comment by fsx950223** [comment]
> @fsx950223 I could reproduce the issue with `TF1.15.0`. Here is the [gist](https://colab.sandbox.google.com/gist/jvishnuvardhan/371cabae8a54797e13b887103170f6c6/untitled629.ipynb) with `TF1.15.0`.
> 
> However, your code works without an issue using `TF2.0`. Please take a look at the [gist](https://colab.sandbox.google.com/gist/jvishnuvardhan/701fd556c91f231b7cc2316fe53d62d4/untitled628.ipynb).
> 
> I think there may not be any updates to `TF1.15.0` unless the issue is related to security. Are you willing to upgrade to `TF2.0`? Thanks!

Yes

**Comment by LambertMark** [comment]
I'm getting this same issue in TF2.1:

`import tensorflow as tf

tf.keras.mixed_precision.experimental.set_policy('mixed_bfloat16')

optimizer = tf.optimizers.SGD(learning_rate=0.1, momentum=0.9)

input=tf.keras.layers.Input(shape=(256, 256, 3))

x=tf.keras.layers.Conv2D(32,(3,3))(input)
x=tf.keras.layers.UpSampling2D()(x)

x=tf.keras.layers.Conv2D(32,(3,3))(x)
out=tf.keras.layers.Activation('sigmoid', dtype='float32')(x)

my_model = tf.keras.models.Model(inputs=input, outputs=out)

optimizer = tf.keras.optimizers.RMSprop()`

**Comment by jvishnuvardhan** [comment]
@LambertMark Please create a new issue with details and a simple standalone code to reproduce the issue. Thanks!
