### ISSUE TITLE
keras.Model.fit does not work with custom layers in Tensorflow 2.0

### ISSUE THREAD

**Issue by yunabe** [tensorflow/tensorflow#32806]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Colab
- TensorFlow installed from (source or binary): Colab
- TensorFlow version (use command below): 2.0.0-rc1
- Python version: 3.6.8 (default, Jan 14 2019, 11:02:34) 
[GCC 8.0.1 20180414 (experimental) [trunk revision 259383]]

**Describe the current behavior**
https://colab.research.google.com/drive/1dUGcOfRIXkP6ZaI-9xKRXAntf8ZzS6bp

```python
class DualLayer(keras.layers.Layer):
  def __init__(self, units):
    super().__init__(self)
    self.first_layer = keras.layers.Dense(units, 'relu')
    self.second_layer = keras.layers.Dense(units, 'relu')
  
  def call(self, input):
    return self.second_layer(self.first_layer(input))

model = keras.Sequential([keras.layers.Flatten(), DualLayer(128), keras.layers.Dense(10, activation='softmax')])
model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])
history = model.fit(train_images, train_labels, batch_size=32, epochs=5)
```

This code dies at model.compile with `RecursionError: maximum recursion depth exceeded while calling a Python object`.According to the stack trace, it seems like it falls into an infinite loop with `hasattr` and `layer.trainable = value`.
``` hasattr(self.__class__, name)):
   2255       try:
-> 2256         super(tracking.AutoTrackable, self).__setattr__(name, value)
   2257       except AttributeError:
   2258         raise AttributeError(

/tensorflow-2.0.0-rc1/python3.6/tensorflow_core/python/keras/engine/base_layer.py in trainable(self, value)
    915     self._trainable = value
    916     for layer in getattr(self, '_layers', []):
--> 917       layer.trainable = value
    918 
    919   @property

/tensorflow-2.0.0-rc1/python3.6/tensorflow_core/python/keras/engine/base_layer.py in __setattr__(self, name, value)
   2254         hasattr(self.__class__, name)):
   2255       try:
-> 2256         super(tracking.AutoTrackable, self).__setattr__(name, value)
   2257       except AttributeError:
   2258         raise AttributeError(
```
**Describe the expected behavior**
Tensorflow 2.x should work with a custom nested layer as Tensorflow 1.x can.

**Code to reproduce the issue**

2.0.0-rc1:https://colab.research.google.com/drive/1dUGcOfRIXkP6ZaI-9xKRXAntf8ZzS6bp
1.14.0:
https://colab.research.google.com/drive/1DeOxKVDM8xEJmU_8GZo-h0iJkWGA4De8

**Comment by Saptarshi-Ghosh-98** [comment]
1. Use gast==0.2.2 for now. gast 0.3.x will give Attribute Missing Error. This hasn't been fixed as of rc2.

2. You need to use 
`super().__init__()`
or 
`super(DualLayer, self).__init__()`

The code runs otherwise.

**Comment by yunabe** [comment]
> 1. Use gast==0.2.2 for now. gast 0.3.x will give Attribute Missing Error. This hasn't been fixed as of rc2.

Do you mean `gast 0.3.x` will improve the error message and I will be able to notice such a silly mistake more easily?

> 2. You need to use
>    `super().__init__()`
>    or
>    `super(DualLayer, self).__init__()`
> 

Oops... I assigned `self` as `trainable` of `__init__` of `keras.layers.Layer`. I'm very ashamed.

**Comment by ravikyram** [comment]
@yunabe 
Please,let me know if we can close this issue since it looks to be fixed. Thanks!

**Comment by yunabe** [comment]
Sure, it was due to my silly typo, which did not cause any problem in tf1.
It would be great I could get a more readable error message.

**Comment by Saptarshi-Ghosh-98** [comment]
@yunabe Gast 0.3.x won't help error message. I recommend to use gast 0.2.2 for now, atleast until the stable version is released. If you ever need custom Models, gast 0.3.x will give attribute missing error. (See this Issue: #32319)
