### ISSUE TITLE
model_pruning: Why 50%  and 90% zeros of the stripped models are the same size?

### ISSUE THREAD

**Issue by wxquare** [tensorflow/tensorflow#32805]
1. I'm trying tensorflow/contrib/model_pruning/examples/cifar10.  I use strip_pruning_vars to  remove pruning ops from the trained graph, strip_pruning_vars  shows 50% and 90% zeros respectively, but their final model are the same size.

2.  As described in the doc，“For now, it is assumed that the underlying hardware platform will provide mechanisms for compressing the sparse tensors and/or accelerating the sparse tensor computations“
   Does it mean that model pruning requires hardware or inference engine support in sparse matrices? 
   In the current version, can I implement inference acceleration on x86 or GPU with the model pruning?

**Comment by ymodak** [comment]
Apologies for the delay in response.
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.
