### ISSUE TITLE
Add function to gather custom objects - easy pickling for models

### ISSUE THREAD

**Issue by beasteers** [tensorflow/tensorflow#32818]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using): 1.14.0
- Are you willing to contribute it (Yes/No): idk

**Describe the feature and the current behavior/state.**
Keras models should be able to iterate through their config and find any layers/functions that would be considered `custom_objects`. Currently, you need to handle them manually.

My goal is to be able to do:
```python
with open('custom_objects.pkl', 'wb') as f:
    pickle.dump(gather_custom_objects(model), f)

with open('model_spec.pkl', 'wb') as f:
    pickle.dump(model.get_config(), f)

...

with open('custom_objects.pkl', 'rb') as f:
    custom_objects = pickle.load(f)

with open('model_spec.pkl', 'rb') as f:
    model = model_from_config(pickle.load(f), custom_objects=custom_objects)
```

**Will this change the current api? How?**
It would add a utility function `gather_custom_objects(model)`

**Who will benefit with this feature?**
People who want to not have to think about custom objects in their models.

**Any Other info.**
I realize it might not be trivial to do in all cases (non-standard layer configs, for example) which is probably why it's not implemented yet.

**Comment by fchollet** [comment]
Hello,

It is unsafe to pickle a Keras model. Rather than doing this, consider using `model.save(path, format='tf')`, which will use the SavedModel format and which will also include the custom objects.

**Comment by jvishnuvardhan** [comment]
Automatically closing this out since I understand it to be resolved by @fchollet comment, but please let me know if I'm mistaken.Thanks!
