### ISSUE TITLE
tf.io.gfile.copy and tf.gfile.Copy input and output same path with overwrite removes all contents

### ISSUE THREAD

**Issue by prats226** [tensorflow/tensorflow#32815]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): no
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 16.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below): 1.14.0
- Python version: 2.7.15
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
`cat label.pbtxt`
> Some txt in the file

`tf.io.gfile.Copy('label.pbtxt', 'label.pbtxt', overwrite=True)`

`cat label.pbtxt`
> <Empty text file>

**Describe the expected behavior**
`cat label.pbtxt`
> Some txt in the file

`tf.io.gfile.Copy('label.pbtxt', 'label.pbtxt', overwrite=True)`

`cat label.pbtxt`
> Some txt in the file

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.
`import tensorflow as tf `
`tf.io.gfile.Copy('label.pbtxt', 'label.pbtxt', overwrite=True)`

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by oanush** [comment]
Issue replicating with TF-1.14, also in TF-2.0rc2. kindly find the [gist](https://colab.sandbox.google.com/gist/oanush/5a040c1b1f4af41b5e3f1d51f3f3d9e4/untitled8.ipynb#scrollTo=CMr3psVURw-5) of colab.Thanks!

**Comment by mihaimaruseac** [comment]
This is kind of working as intended. The same behavior happens on the operating system level:

```console
mihaimaruseac@ankh:/tmp$ cat x
1
2
3
mihaimaruseac@ankh:/tmp$ cat x > x
mihaimaruseac@ankh:/tmp$ cat x
mihaimaruseac@ankh:/tmp$
```

In the end, you are opening the file twice, once for reading and once for writing on it from scratch (thus truncating it to size 0). Then the copy reads a chunk from the beginning and writes it on the output. However, as the file on disk has been cleared, the first chunk is empty so nothing gets written.
