### ISSUE TITLE
Support TRANSPOSE on GPU Delegate

### ISSUE THREAD

**Issue by liakopyangsir** [tensorflow/tensorflow#32832]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Android 
- TensorFlow installed from (source or binary): binary(tensorflow-lite-gpu:0.0.0-nightly)
- TensorFlow version (or github SHA if from source):

**Provide the text output from tflite_convert**

```
# Copy and paste here
```

Also, please include a link to a GraphDef or the model if possible.

My model is quantilized to FP16.

**Any other info / logs**
05-19 15:05:29.819 +0000 21043 21043 W TFLiteInfer: java.lang.IllegalArgumentException: Internal error: Failed to apply delegate: Next operations are not supported by GPU delegate:
05-19 15:05:29.819 +0000 21043 21043 W TFLiteInfer: TRANSPOSE: Operation is not supported.
05-19 15:05:29.819 +0000 21043 21043 W TFLiteInfer: First 129 operations will run on the GPU, and the remaining 175 on the CPU.tensorflow/lite/kernels/fully_connected.cc:110 is_optional_bias_float != true (0 != 1)Node number 35 (FULLY_CONNECTED) failed to prepare.
05-19 15:05:29.819 +0000 21043 21043 W TFLiteInfer: tensorflow/lite/kernels/conv.cc:259 bias->type != input_type (10 != 1)Node number 3 (CONV_2D) failed to prepare.

**Comment by oanush** [comment]
@liakopyangsir ,
Provide the exact sequence of commands / steps that you executed before running into the problem.Thanks!

**Comment by oanush** [comment]
@liakopyangsir ,
Any update on the issue ?Thanks!

**Comment by oanush** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Comment by qbit-** [comment]
Same issue here, please reopen
