### ISSUE TITLE
TF doesn't build anymore with Bazel's --incompatible_remove_legacy_whole_archive

### ISSUE THREAD

**Issue by hlopko** [tensorflow/tensorflow#32835]
Some time ago we migrated Tensorflow to build with this flag flipped, but it regressed again (https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/1207#d1e5940d-bde3-46cd-8734-1b6f2fddabf5).

The incompatible flag: https://github.com/bazelbuild/bazel/issues/7362

I'm looking into it. This is a tracking issue for this effort :)

**Comment by angerson** [comment]
(Assigning to @hlopko to detach this issue from our auto-assignment pipeline. Thanks for tracking this!)

**Comment by laszlocsomor** [comment]
I have a fix for this.
