### ISSUE TITLE
TF 2.0 RC Image Segmentation Tutorial

### ISSUE THREAD

**Issue by calciver** [tensorflow/tensorflow#32833]
The tutorial is found here: https://www.tensorflow.org/beta/tutorials/images/segmentation

In cell 10, the provided Google Colab Notebook has the following error:
OperatorNotAllowedInGraphError: using a `tf.Tensor` as a Python `bool` is not allowed: AutoGraph did not convert this function. Try decorating it directly with @tf.function.

**Comment by oanush** [comment]
@calciver ,
I tried executing the tutorial using TF-2.0rc2 and it worked fine. Kindly find the [gist](https://colab.sandbox.google.com/gist/oanush/621fbdbda1301e9e3ffeb4479916583e/untitled11.ipynb) of colab.Thanks!

**Comment by calciver** [comment]
Thanks, that helped. Glad to know this was resolved in TF-2.0rc2.
Hope google colab supports the latest version of TF 2.0 in time.
