### ISSUE TITLE
tensorboard connection problem

### ISSUE THREAD

**Issue by spiegelss** [tensorflow/tensorflow#32845]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): **Ubuntu 18.04**
- TensorFlow installed from (source or binary): pip (docker)
- TensorFlow version: 1.13.2
- Python version: 3
- Installed using virtualenv? pip? conda?: pip
- CUDA/cuDNN version:10.1
- GPU model and memory: Quadro P3000

Good afternoon!

I am using the tensorflow image from [docker](https://hub.docker.com/r/tensorflow/tensorflow/tags?page=1&name=1.13) and am having trouble getting tensorboard to run in my container.  I run the following command to start the container:

`
sudo docker container run -p 8888:8888 -p 6006:6006 -it --rm --runtime=nvidia -v $(pwd):/opt/ -v $(pwd)/:/tf/ '$image-name
`
When I run my trial notebook, I get the following error image (see attached file).  I'm not sure what I'm doing wrong.  If I need to provide more I will.  Thank you!

![issue](https://user-images.githubusercontent.com/40045042/65709154-cac10480-e055-11e9-88d1-f4d7dfe00351.png)

**Comment by gowthamkpr** [comment]
@spiegelss What browser are you using?

**Comment by spiegelss** [comment]
I am using firefox.  I will check if it's my ad block.  I forgot I had that on.

**Comment by gowthamkpr** [comment]
@spiegelss Does your issue still persists or is it resolved?

**Comment by gowthamkpr** [comment]
Closing this issue as it has been resolved
