### ISSUE TITLE
TFLite Different behaviour after upgrading gradle

### ISSUE THREAD

**Issue by tgpsantos** [tensorflow/tensorflow#32840]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: Samsung S9
- TensorFlow version (use command below): tensorflow-lite and tensorflow-lite-gpu nightly

**Describe the current behavior**
I have a project that uses the android camera and every 500ms processes a frame in the background thread. I'm using a GPU delegate.  

I recently upgraded the gradle-wrapper from `5.1.1` to `5.6.2`. After this everything seemed to remain the same, except for:
1. model is inferring much faster (15%-30% faster)
2. model is taking much more time to initialize inferences (about 8 seconds, before it was around 1 second)

Even though I'm pleased with the apparent improved inference times, the 7 second waiting to start running inferences is a pain.. Is there any reason for that?

I've checked the logs (which I attach) and realized I have - at least - a new additional print in the 5.6.2 version:
`Initialized OpenCL-based API.`
The inferences only start after this print so I imagine it might have to due with the delay mentioned.

Thank you for your help!

PS: I've attached the logs but I don't know how much of an help they could be

[android-debug 5.1.1.log](https://github.com/tensorflow/tensorflow/files/3658022/android-debug.5.1.1.log)
[android-debug 5.6.2.log](https://github.com/tensorflow/tensorflow/files/3658023/android-debug.5.6.2.log)

**Comment by tgpsantos** [comment]
Any ideia on what might be happening? In a Xiaomi Redmi Note 4 the performance decreased from 230 to +400ms and there is no information about `OpenCL-based API`

**Comment by tgpsantos** [comment]
@impjdi any clue on what's happening? 
I've started to use tflite gpu in may/june and haven't since updated anything on jcenter or maven, do you think it might have to due with that? I've also seen you and @jdduke speaking about a v1 and v2 versions of delegate (opengl and opencl), is it possible I might be stuck in between?

**Comment by impjdi** [comment]
@tgpsantos 

The reason why things may be faster now, may be due to our OpenCL backend.  While the OpenCL code may be executed behind the scenes when you're using the `TfLiteGpuDelegate`, we haven't publicly announced because documentation is missing; we'll prepare them soon.

The slow startup time may be also related to OpenCL, but it's difficult to say at the moment.  Can you track down the whether OpenGL is executed or OpenCL?

**Comment by qppp558** [comment]
Similar things happen to me, the model initialization time tooks 17 seconds when gpuDelegate is used, 500ms for using CPU only. I tryed tensorflow-lite-nightly, 2.0.0 and 1.15.0, they work the same. The gradle version is 5.4.1 and android gradle version is 3.5.2.

**Comment by tgpsantos** [comment]
> 
> 
> @tgpsantos
> 
> The reason why things may be faster now, may be due to our OpenCL backend. While the OpenCL code may be executed behind the scenes when you're using the `TfLiteGpuDelegate`, we haven't publicly announced because documentation is missing; we'll prepare them soon.
> 
> The slow startup time may be also related to OpenCL, but it's difficult to say at the moment. Can you track down the whether OpenGL is executed or OpenCL?

In my log I got: 
> Initialized OpenCL-based API

Is there a more reliable way of confirming this?

**Comment by impjdi** [comment]
@tgpsantos 

Unless you see "Falling back to OpenGL", you are on OpenCL land :)

**Comment by tgpsantos** [comment]
According to those logs then I am on OpenCL land :)

Regarding the slowdown to start doing inferences, any clue on what might be happening? This is a huge pain :( In Samsung S9 (Mali-G72) I've seen an increase in performance but the slowdown to start inferences kills me... In a different smartphone (Xiaomi Redmi Note 4 - Adreno 506 - OpenCL 2.0) not only have a slowdown to start but there is also a significant drop in performance.

**Comment by impjdi** [comment]
8 secs load time sounds indeed ridiculous.  Do you have a TFLite model you can share?

**Comment by tgpsantos** [comment]
Sorry for just reporting back now. Can I send you an email with the tflite model?

**Comment by impjdi** [comment]
Sure.

**Comment by tgpsantos** [comment]
Where can I find it ? :)

**Comment by impjdi** [comment]
at google dot com :)

**Comment by RobertBiehl** [comment]
We seem to encounter the same issue. With OpenCL the load times are extremely long often in the 10s range.
Do you have an update on this?

**Comment by impjdi** [comment]
We continued the discussion on an email thread.   You can use `TFLITE_GPU_INFERENCE_PREFERENCE_FAST_SINGLE_ANSWER` for faster initialization.

**Comment by RobertBiehl** [comment]
thx, will try
