### ISSUE TITLE
"/device:GPU:0" or "/device:XLA_GPU:0"  ? 

### ISSUE THREAD

**Issue by sgambient** [tensorflow/tensorflow#32851]
When XLA is enabled with  TF_XLA_FLAGS=--tf_xla_auto_jit=2, should I see "/device:GPU:0" or "/device:XLA_GPU:0" in  Tensorflow output ?

**Comment by sanjoy** [comment]
You should ignore the XLA_GPU devices in the log output.  They are a legacy way to use XLA that we don't recommend for end users.

If TF detected a `/device:GPU:0` then you're good to go.  If not, TF (with or without `TF_XLA_FLAGS=--tf_xla_auto_jit=2`) will not use a GPU.

**Comment by ymodak** [comment]
@sgambient Please close this thread if it solves your question. Thanks!

**Comment by sgambient** [comment]
Thanks, that  addresses by concern.
