### ISSUE TITLE
when will tensor flow support python3.7 ?

### ISSUE THREAD

**Issue by devitnow15** [tensorflow/tensorflow#32858]
when will tenor flow support python 3.7 ? tried the installation with 2.0 , which also does not support python 3.7.

**Comment by ravikyram** [comment]
@devitnow15 

Please, go through #32718 and see if it helps you. Thanks!

**Comment by devitnow15** [comment]
As given in #32718 , tried pip3 install tensorflow==2.0.0rc2 , it does not work.
I am using windows10 with Pythin 3.7 , is this issue fixed for windows in tensorflow2.0 or is this fixed only for mac ?

**Comment by Saptarshi-Ghosh-98** [comment]
tf rc2 is available for py 3.7. What's your pip version?

**Comment by devitnow15** [comment]
using 19.2.3. , please view the attachment
![tensor_flow](https://user-images.githubusercontent.com/55172847/65749660-28bc1d80-e124-11e9-9f45-ef68c6109a86.PNG)

**Comment by Saptarshi-Ghosh-98** [comment]
Is that 32-bit python? Tensorflow 2 is available for only 64-bit python.

**Comment by devitnow15** [comment]
Thanks for pointing out , it worked.
