### ISSUE TITLE
TFLite Reshape not supporting resizeInputTensor with -1

### ISSUE THREAD

**Issue by tobyclh** [tensorflow/tensorflow#32857]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: Pixel 3, Pixel 2
- TensorFlow installed from (source or binary): Anaconda
- TensorFlow version (use command below): 1.14
- Python version: 3.7
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 10
- GPU model and memory:

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
I am trying to deploy Deepspeech 2 with `tf.lite.experimental.nn.bidirectional_dynamic_rnn` on android. Inside the inference since the input audio is of dynamic length, I try to call `resizeInputTensor` in the c++ api on Android to match the length of the audio, which throws 
`tensorflow/contrib/lite/kernels/reshape.cc:58 num_input_elements != num_output_elements`
similar to #23600. In the inference code there is a line of `reshape` which is from [-1, 1, 38, 25] to   [-1, 1, 38*25], (note that it collapses the fourth dimension but doesn't do anything with the batch dimension. After reading the source code for `reshape.cc` it seems like even if the batch size is indicated as -1, during conversion the batch size is explicitly computed and stored in the model, which is the main cause of this bug.

**Describe the expected behavior**
`reshape` conversion recomputes the reshape size whenever `resizeInputTensor` is called. 
 
**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.
```
std::vector<int> sizes = {1, 240, 240, 3};

interpreter_->ResizeInputTensor(interpreter_->inputs()[0], sizes);

if (interpreter_->AllocateTensors() != kTfLiteOk) {
    LOG(INFO) << "Failed to allocate tensors!" << "\n";
    return false;
```
Given that interpreter_ contains resizeops with -1 specified.

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by Tanya-Motwani** [comment]
Is a solution available for the same??

**Comment by korabelnikov** [comment]
@liyunlu0618  any updates?

**Comment by pkubik** [comment]
I think that the latest `2.3.1` version "resolves" the issue. When `-1` occurs in the `Reshape` parameter a chain of shapes, gathers, reshapes and concatenations is injected to dynamically compute the correct shape.
- Shape to get the shape of the input tensor
- Gather and Reshape to extract the batch size
- Concatenate to join the extracted batch size with the other specified dimensions
- Again Reshape to do an actual reshape with the dynamically computed shape

**UNFORTUNATELY**
This also introduce some weird combination of `Where`, `SparseToDense` and `AddV2`, that I am yet to understand. The last op is the issue here because it is **not supported by TFLite** - this is a special version of `Add` used for `int64`.

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.

**Comment by hyungui** [comment]
Still, in `2.4.1`, there is a bug of `Reshape` with `-1`. I just changed a specific number instead of `-1` and it works.
