### ISSUE TITLE
fit_generator validation steps running on CPU?

### ISSUE THREAD

**Issue by simoncozens** [tensorflow/tensorflow#32865]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes, see below.
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):Nvidia L4T 32.2.1 (based on Ubuntu 18.04) running on Jetson Nano
- TensorFlow installed from (source or binary): binary from Nvidia Jetson repo.
- TensorFlow version (use command below): unknown 1.14.0 (Also seen on 1.13.0)
- Python version: 3.6.8
- CUDA/cuDNN version: CUDA 10.0.326, cuDNN 7.5.0.56-1+cuda10.0
- GPU model and memory: NVIDIA Jetson NANO/TX1, 4Gb (shared)

**Describe the current behavior**

Training steps use 100% of GPU as reported by tegrastats; validation steps use 0% of GPU and 350% CPU. 3.4Gb of memory is used and 338k is free. 

**Describe the expected behavior**

Validation steps should also be run on GPU.

**Code to reproduce the issue**

Full code at  https://github.com/simoncozens/atokern/blob/master/badkerndetector.py and https://github.com/simoncozens/atokern/blob/master/nntools.py . Relevant portion:

```
    checkpointer = tf.keras.callbacks.ModelCheckpoint(filepath=output_dir+'/output/kernmodel-cp-val.hdf5', verbose=0, save_best_only=True, monitor="val_loss")
    reduce_lr = tf.keras.callbacks.ReduceLROnPlateau(monitor='val_loss', factor=lr_decay, patience=20, verbose=1, mode='auto', min_delta=1e-6, cooldown=100, min_lr=0)
    tensorboard = tf.keras.callbacks.TensorBoard(log_dir=output_dir+"/output", histogram_freq=1,
    write_graph=False, write_grads=False,batch_size=self.batch_size,update_freq='batch',
    write_images=False,profile_batch=0 )

    callback_list = [
      checkpointer,
      reduce_lr,
      tensorboard,
    ]

    history = self.model.fit_generator(
      generator = self.generator,
      validation_data = self.validation_generator,
      steps_per_epoch = steps_per_epoch,
      validation_steps = validation_steps,
      epochs=epochs, verbose=1, callbacks=callback_list,
      max_queue_size=30
    )
```

**Other info / logs**

My suspicion is that this is memory allocation related, as I've had to reduce the batch size - with larger batch sizes, the training will run all training steps and then OOM when it enters the validation stage.

Is it possible that the validation step can't allocate something on the GPU and so uses CPU instead?

**Comment by gadagashwini** [comment]
@simoncozens, Will it be possible to provide the simple standalone code to replicate the reported issue here. Thanks!

**Comment by gadagashwini** [comment]
@simoncozens, Provide us the standalone code snippet. It will indeed help us to move faster.

**Comment by simoncozens** [comment]
OK, I think this is actually not a TF bug, but my problem with tuning the generator queues: the CPU was spending more time making data than the GPU spent consuming it. I don't know why this only happened on validation, but I think the training was actually running on GPU.
