### ISSUE TITLE
scientific research on the evaluation of Tensorflow

### ISSUE THREAD

**Issue by Karinsapple** [tensorflow/tensorflow#32874]
Hello, everyone!
We are students from Linkoping University, Sweden. We are doing research on evaluation of Tensorflow, so we need help!
There is a questionnaire we need you to answer! Just 1-2 minutes!
Thank you so much for your patience and kindness!

https://docs.google.com/forms/d/e/1FAIpQLSfvqIUxxI5mm82dr_M8Ja7y_eGG0mqXzfCLQ0c6ehjqSjAQkA/viewform?usp=sf_link

**Comment by martinwicke** [comment]
The issue tracker is for bug reports, and I assume your post will not be widely read here. You can try posting to discuss@tensorflow.org.
