### ISSUE TITLE
When importing TensorFlow, error loading Hadoop

### ISSUE THREAD

**Issue by wchargin** [tensorflow/tensorflow#32885]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): gLinux (like Debian)
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): v1.12.1-12014-gab20de6 2.0.0-dev20190927
- Python version: 3.6.8
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

**Describe the current behavior**

Importing TensorFlow prints an error:

> 2019-09-27 13:51:34.191065: E tensorflow/core/platform/hadoop/hadoop_file_system.cc:132] HadoopFileSystem load error: libhdfs.so: cannot open shared object file: No such file or directory

**Describe the expected behavior**

Importing TensorFlow should not print errors about Hadoop. I don’t have
Hadoop installed and am not interested in using it.

**Code to reproduce the issue**

```
$ cd "$(mktemp -d)"
$ virtualenv -q -p python3.6 ./ve
$ . ./ve/bin/activate
(ve) $ pip install -q tf-nightly-2.0-preview==2.0.0.dev20190927
(ve) $ python -c 'import tensorflow as tf; print(tf.__version__)'
2019-09-27 13:51:21.263111: E tensorflow/core/platform/hadoop/hadoop_file_system.cc:132] HadoopFileSystem load error: libhdfs.so: cannot open shared object file: No such file or directory
2.0.0-dev20190927
```

**Other info / logs**

Probably relevant: <https://github.com/tensorflow/tensorflow/pull/32649>

**Comment by fsx950223** [comment]
Maybe the lazy load is a better solution

**Comment by wchargin** [comment]
Yes, Hadoop should probably be lazy-loaded. Even users who have it
installed may well not want to use it in _every_ TensorFlow process;
forcing them to pay the load cost doesn’t make much sense to me.

**Comment by jhseu** [comment]
Yep, sending out a change to lazy load.

**Comment by srinivasgln** [comment]
I get the same error  as well ( in Tensorflow 2.0.0 and Python 3.5.2).

> E tensorflow/core/platform/hadoop/hadoop_file_system.cc:132] HadoopFileSystem load error: libhdfs.so: cannot open shared object file: No such file or directory

**Comment by wchargin** [comment]
@srinivasgln: @jhseu has a fix in the works; stay tuned.

**Comment by wchargin** [comment]
Confirmed fixed in nightly; thanks!

**Comment by dhumal436** [comment]
how to solve this error

**Comment by mihaimaruseac** [comment]
@dhumal436 please refer to #36141 and if that doesn't solve your issue please open a new one.
