### ISSUE TITLE
image classification code sample error

### ISSUE THREAD

**Issue by elizabethsiegle** [tensorflow/tensorflow#32886]
Thank you for submitting a TensorFlow documentation issue. Per our GitHub
policy, we only address code/doc bugs, performance issues, feature requests, and
build/installation issues on GitHub.

The TensorFlow docs are open source! To get involved, read the documentation
contributor guide: https://www.tensorflow.org/community/contribute/docs

## URL(s) with the issue:
https://www.tensorflow.org/beta/tutorials/images/classification

## Description of issue (what needs changing):
```
acc = history.history['accuracy']
val_acc = history.history['val_accuracy']
```
should be
```
acc = history.history['acc']
val_acc = history.history['val_acc']
```
### Clear description
When I copy and paste the code and run it directly, the model is trained for a few minutes/a while but I get KeyError: 'accuracy' and then when I change that, get KeyError: 'val_accuracy'

Someone would use this to perform image recognition with code they take directly from the Tensorflow docs on this page.

### Correct links
It is not correct yet. I am thinking of making a PR to the docs repo

### Parameters defined
n/a

### Returns defined

n/a

### Raises listed and defined

n/a

### Usage example

to train images

### Request visuals, if applicable

There's a few.

### Submit a pull request?

Are you planning to also submit a pull request to fix the issue? See the docs
contributor guide: https://www.tensorflow.org/community/contribute/docs and the
docs style guide: https://www.tensorflow.org/community/contribute/docs_style

I am!

**Comment by jvishnuvardhan** [comment]
@elizabethsiegle Thanks for reporting this issue. The code in the tutorial is correct for TF2.0. If you want to run it in TF1.x, you need to change those two lines from
```
acc = history.history['accuracy']
val_acc = history.history['val_accuracy']
```
to
```
acc = history.history['acc']
val_acc = history.history['val_acc']
```
Thanks! Please close this issue if it was resolved? Thanks!

**Comment by jvishnuvardhan** [comment]
I am closing the issue as it was resolved. Please feel free to open it if the issue persists again. Thanks!
