### ISSUE TITLE
Tensorflow device indexes mismatch with nvidia-smi

### ISSUE THREAD

**Issue by iperov** [tensorflow/tensorflow#32881]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 7
- TensorFlow installed from (source or binary): pip
- TensorFlow version (use command below): 2.0rc1
- Python version: 3.7.4
- CUDA/cuDNN version: 10.0 / 7.6.0
- GPU model and memory: RTX 2080 TI  11GB

**Describe the current behavior**

I have two gpus.
My code is designed to determine GPUs info and their indexes before import tensorflow by using nvidia-smi
but tensorflow device indexes mismatch nvidia-smi indexes.

tensorflow log:
```
2019-09-27 21:10:02.247000: I tensorflow/stream_executor/platform/default/dso_lo
ader.cc:44] Successfully opened dynamic library cudart64_100.dll
2019-09-27 21:10:04.473000: I tensorflow/stream_executor/platform/default/dso_lo
ader.cc:44] Successfully opened dynamic library nvcuda.dll
2019-09-27 21:10:04.550000: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1

618] Found device 0 with properties:
name: GeForce RTX 2080 Ti major: 7 minor: 5 memoryClockRate(GHz): 1.545
pciBusID: 0000:03:00.0
2019-09-27 21:10:04.555000: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1

618] Found device 1 with properties:
name: GeForce GT 730 major: 3 minor: 5 memoryClockRate(GHz): 0.9015
pciBusID: 0000:01:00.0

2019-09-27 21:10:04.559000: I tensorflow/stream_executor/platform/default/dlopen
_checker_stub.cc:25] GPU libraries are statically linked, skip dlopen check.
2019-09-27 21:10:04.566000: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1
746] Adding visible gpu devices: 0, 1
```

nvidia-smi log:
```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 436.30       Driver Version: 436.30       CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name            TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GT 730     WDDM  | 00000000:01:00.0 N/A |                  N/A |
| 61%   69C    P0    N/A /  N/A |    959MiB /  2048MiB |     N/A      Default |
+-------------------------------+----------------------+----------------------+
|   1  GeForce RTX 208... WDDM  | 00000000:03:00.0 Off |                  N/A |
| 40%   78C    P2   143W / 250W |  10992MiB / 11264MiB |     89%      Default |
+-------------------------------+----------------------+----------------------+
```

**Describe the expected behavior**

expected tensorflow match nvidia-smi device indexes

**Code to reproduce the issue**

no code required. Just launch tensorflow initialization to show the info of the devices.

**Comment by iperov** [comment]
it seems like nvcuda.dll device order differs from nvsmi device order

**Comment by ahtik** [comment]
@iperov CUDA tries to order the GPUs based on their computing power, nvidia-smi by pci bus id.

Try running with `CUDA_DEVICE_ORDER=PCI_BUS_ID` to get the nvidia-smi indices.

**Comment by gadagashwini** [comment]
@iperov, Did you try the @ahtik's suggestion. Please let us know if that solves your issue. Thanks!

**Comment by iperov** [comment]
I got rid of using pynvml.
Now I am using cuda lib directly to determine devices and indexes that match tensorflow. Works windows and linux perfectly.

```
def getDevices():
    if Devices.devices is None:        
        min_cc = int(os.environ.get("TF_MIN_REQ_CAP", 35)) 
        libnames = ('libcuda.so', 'libcuda.dylib', 'nvcuda.dll')
        for libname in libnames:
            try:
                cuda = ctypes.CDLL(libname)
            except:
                continue
            else:
                break
        else:
            return Devices([])
        nGpus = ctypes.c_int()
        name = b' ' * 200
        cc_major = ctypes.c_int()
        cc_minor = ctypes.c_int()
        freeMem = ctypes.c_size_t()
        totalMem = ctypes.c_size_t()
        result = ctypes.c_int()
        device = ctypes.c_int()
        context = ctypes.c_void_p()
        error_str = ctypes.c_char_p()
        devices = []
        if cuda.cuInit(0) == 0 and \
           cuda.cuDeviceGetCount(ctypes.byref(nGpus)) == 0:
            for i in range(nGpus.value):
                if cuda.cuDeviceGet(ctypes.byref(device), i) != 0 or \
                   cuda.cuDeviceGetName(ctypes.c_char_p(name), len(name), device) != 0 or \
                   cuda.cuDeviceComputeCapability(ctypes.byref(cc_major), ctypes.byref(cc_minor), device) != 0:
                    continue
                if cuda.cuCtxCreate_v2(ctypes.byref(context), 0, device) == 0:
                    if cuda.cuMemGetInfo_v2(ctypes.byref(freeMem), ctypes.byref(totalMem)) == 0:
                        cc = cc_major.value * 10 + cc_minor.value
                        if cc >= min_cc:
                            devices.append ( Device(index=i,
                                                    name=name.split(b'\0', 1)[0].decode(),                       
                                                    total_mem=totalMem.value,
                                                    free_mem=freeMem.value,
                                                    cc=cc) )
                    cuda.cuCtxDetach(context)
        Devices.devices = Devices(devices)
    return Devices.devices
```

**Comment by ahtik** [comment]
@iperov I would be a bit cautious using your snuppet as it's likely not deterministic.
Have a look at https://docs.nvidia.com/deploy/nvml-api/group__nvmlDeviceQueries.html#group__nvmlDeviceQueries_1g52677ecb45f937c5005124608780a3f4

`The order in which NVML enumerates devices has no guarantees of consistency between reboots. For that reason it is recommended that devices be looked up by their PCI ids or UUID`

Btw, nvidia-smi is also using nvml behind the scenes, but likely just orders by pci bus id internally by itself to ensure consistency.

https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#env-vars has a bit more details on CUDA ordering with `CUDA_​DEVICE_​ORDER`: https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#env-vars Note that only the fastest is put at index 0 and the rest is not ordered.

**Comment by iperov** [comment]
@ahtik  

sometimes nvml does not come with video drivers on some notebook cards, even high-end cards like 1080. There is no ```NVIDIA Corporation\NVSMI``` folder that contains nvml.dll on such systems.

so I think using direct cuda lib is the best choice
because
1) indexes are always match tensorflow indexes
2) works everywhere, tested on google colab.

**Comment by iperov** [comment]
also I tried to set 
```
os.environ['CUDA_​DEVICE_​ORDER'] = 'PCI_BUS_ID'
```
but it did not fixed the issue when using pynvml

**Comment by jvishnuvardhan** [comment]
@iperov Is this still an issue or resolved? Please close the issue if it was resolved already. Thanks!

**Comment by jvishnuvardhan** [comment]
Closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
