### ISSUE TITLE
Broken Link for API Development Recommendations

### ISSUE THREAD

**Issue by kfrncs** [tensorflow/tensorflow#32892]
[This page](https://www.tensorflow.org/community/contribute/docs) links to https://www.tensorflow.org/customize, which doesn't exist.

("We encourage the community to develop and maintain support for other languages with the approach recommended by the TensorFlow maintainers.")

**Comment by ichisadashioko** [comment]
I believe that https://www.tensorflow.org/customize is no longer existed in https://www.tensorflow.org/community/contribute/docs.

I wrote the snippet below to check in Developer console and nothing has been printed out. Maybe the problem has been fixed?

```javascript
var anchors = document.getElementsByTagName('a')
for (let i = 0; i < anchors.length; i++) {
  let href_attr = anchors[i].getAttribute('href')
  if (href_attr) {
    let s = href_attr.search('customize')
    if (s >= 0) {
      console.log(`href_attr: ${href_attr}`)
      console.log(anchors[i])
    }
  }
}
```

![https://imgur.com/a/qdWWoWA](https://i.imgur.com/mGQEiyc.png)

**Comment by gadagashwini** [comment]
@kfrncs,
In [this link](https://www.tensorflow.org/community/contribute/docs), https://www.tensorflow.org/customize is not available. Could you please provide the exact position of the broken link. Thanks!

**Comment by kfrncs** [comment]
It looks as though it's already fixed. I can't find the part I was referring to, so I guess whatever restructuring is done now.

**Comment by gadagashwini** [comment]
@kfrncs, Glad it fixed.
Closing this issue. Please feel free to reopen if the issue still persists. Thanks!
