### ISSUE TITLE
How to get cublas handle to run cublas function?

### ISSUE THREAD

**Issue by 7oud** [tensorflow/tensorflow#32896]
I write a custom op using cublas function `cublasCgetrfBatched` and `cublasCgetriBatched`, the functions use cublas handle as a input param, however the `cublasCreate(&handle);` cost nearly 100ms. 
I think the TF has already integrate CUBLAS module, `cublasCreate(&handle)` muse have been invoked in the init process, then how to get the handle? An example may be the best!

**Comment by ymodak** [comment]
Perhaps you may find this [page useful](https://developer.nvidia.com/cublas) 
Also see [cublas examples](https://developer.nvidia.com/sites/default/files/akamai/cuda/files/Misc/mygpu.pdf)

**Comment by 7oud** [comment]
@ymodak Thanks! But my question is how the get the cublas handle from TF, I know the the usage of `cublas` and have run the custom op using cublas already, but the `handle` need be created with `cublasCreate(&handle)`, if run the op multi-times, then the handle is created multi-times, that's unreasonable. However I can't save the handle in an op and reuse it, as it is a global variable.
It seems that TF using steam_executor to wrap gpu device, maybe cublas handle has already created in the TF init process, and may get it from some TF C++ API.

**Comment by timshen91** [comment]
As of today cublas handle is for Tensorflow internal use only. It's not exposed to the public C++ API. See `tensorflow/stream_executor/cuda/cuda_blas.h` that no getters are there for getting the handle `blas_`.

I don't know much about TF custom ops, but I'd expect somewhere in the executor to have a place for users to keep a handle there.

**Comment by 7oud** [comment]
@timshen91 Very useful info! Is there any sample code that use stream executor to do BLAS ops with cuBLAS. If I modify the src code to export a getter of `blas_` and use it in some custom op, will it affect releasing resource?

**Comment by timshen91** [comment]
@7oud For your own debugging and understanding, it's probably fine to add a getter for blas_.

For a real solution, I suggest you to:
* Find a way to transport arbitrary data from your application to the execution of your custom op
* Create your permanent BLAS handle before executing the graph, and expose it to the custom op executor
* In the custom op executor, use the permanent BLAS handle you created.

Unfortunately I don't know TF enough to tell you where those places are in code.

**Comment by ymodak** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
