### ISSUE TITLE
[TF 2.0 API Docs] tf.nn.batch_normalization

### ISSUE THREAD

**Issue by prabindh** [tensorflow/tensorflow#32890]
## URL(s) with the issue:
https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/nn/batch_normalization

## Description of issue (what needs changing):
Documentation

### Clear description
Yes
### Correct links
Yes
Is the link to the source code correct?
Yes
### Parameters defined
Yes
Are all parameters defined and formatted correctly?
No.

- tf.nn.moments(..., keep_dims=True) 

In TF2 version of tf.nn.moments, keep_dims keyword should be "keepdims" instead

- Does not implement the equation as given, but the equation 11 in Algorithm 2 of the paper.
![image](https://user-images.githubusercontent.com/1215029/65819369-429b5480-e239-11e9-98e7-07bbf34f18d9.png)

### Returns defined
Are return values defined?
Yes
### Raises listed and defined
No
### Usage example
Is there a usage example?
No
### Request visuals, if applicable
No
Are there currently visuals? If not, will it clarify the content?
No
### Submit a pull request?
Yes
Are you planning to also submit a pull request to fix the issue? See the docs
contributor guide: https://www.tensorflow.org/community/contribute/docs and the
docs style guide: https://www.tensorflow.org/community/contribute/docs_style

**Comment by ymodak** [comment]
Closing this issue since the associated PR has been merged. Thanks!
