### ISSUE TITLE
TF2: tfp.distributions.Normal in tf.keras.Model issue

### ISSUE THREAD

**Issue by BlueFisher** [tensorflow/tensorflow#32897]
I just found that if I returned a distribution in `call` not a tensor and called `self(tf.keras.Input())` in `__init__`, it would throw an exception `'Normal' object has no attribute 'shape'`
```python
class MyModel(tf.keras.Model):
    def __init__(self):
        super(MyModel, self).__init__()

        self.l = tf.keras.layers.Dense(2)
        self(tf.keras.Input(shape=(3,)))

    def call(self, inputs):
        x = self.l(inputs)

        policy = tfp.distributions.Normal(loc=x, scale=x)
        return policy


model = MyModel()
```

**Comment by oanush** [comment]
Tried given code forTF-1.15rc1 and 2.0rc2 i was able to replicate the error. Kindly find the [gist](https://colab.sandbox.google.com/gist/oanush/ccc142acb65fd5d7f519c2deea5b7893/32897.ipynb) of colab.Thanks!

**Comment by jvishnuvardhan** [comment]
@BlueFisher This is more related to `tfb` repository. Can you open the issue [here](https://github.com/tensorflow/probability/issues). Thanks!

**Comment by BlueFisher** [comment]
> @BlueFisher This is more related to `tfb` repository. Can you open the issue [here](https://github.com/tensorflow/probability/issues) and then close this issue. Thanks!

Thanks for reminding
