### ISSUE TITLE
whether cuda toolkit 10.1 version supports tensorflow 1.14Version?

### ISSUE THREAD

**Issue by WrathofBhuvan11** [tensorflow/tensorflow#32901]
trying to install tensorflow 2.0 in windows 10. Already installed CUDA toolkit 10.1 and cudNN

**Comment by ahtik** [comment]
Yes and no.

You're better off installing `cuda_10.0.130_411.31_win10` and `cudnn-10.0-windows10-x64-v7.6.4.38`.

cudNN installation is just about extracting it to `C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0`.

You can still have the latest NVIDIA drivers, so there is no need to go through all the trouble and timesink of compiling Tensorflow 2.0 by yourself in Windows. If you want to spend time with this, https://github.com/tensorflow/tensorflow/issues/28086 might be a good start.

There are no public precompiled tf binaries for CUDA 10.1.

**Comment by gadagashwini** [comment]
@WrathofBhuvan11,
Please take a look at [software requirements](https://www.tensorflow.org/install/gpu#software_requirements) for Tensorflow. Thanks!

**Comment by gadagashwini** [comment]
@WrathofBhuvan11, Were you able to resolve this issue. Thanks!

**Comment by WrathofBhuvan11** [comment]
currently i have installed cudatoolkit 10.1 and cudnn recent one but having
path error... i have added these to environmental variables... yet while
importing tf i'm getting

**Comment by ahtik** [comment]
@WrathofBhuvan11 If you want to use cuda 10.1 then you must compile the whole tensorflow by yourself on Windows.

Unless you have a very specific reason to use cuda 10.1, I'd strongly recommended to use cuda 10.0, which works great with the tensorflow binary package. Please note that GPU drivers themselves can be still the latest.

Latest compatible versions as of last week are `cuda_10.0.130_411.31_win10` and `cudnn-10.0-windows10-x64-v7.6.4.38`.

**Comment by salman222-1** [comment]
شكرا ولاكني استخدم جوال هواوي q20ارجو الرد والائيفادههل تقصد للمحفظه ام لتسريع التعدين وماهي افظل برامج هواوي لتسريع التعدين وابقا الجوال بحاله مستمره لتعدينمُرسل من 📱 android is Huawei الخاص بي-------- الرسالة الأصلية --------الموضوع: Re: [tensorflow/tensorflow] whether cuda toolkit 10.1 version supports tensorflow 1.14Version? (#32901)من: Ahti Kitsik إلى: tensorflow/tensorflow نسخة إلى: salman222-1 ,Manual @WrathofBhuvan11 If you want to use cuda 10.1 then you must compile the whole tensorflow by yourself on Windows.
Unless you have a very specific reason to use cuda 10.1, I'd strongly recommended to use cuda 10.0, which works great with the tensorflow binary package. Please note that GPU drivers themselves can be still the latest.
Latest compatible versions as of last week are cuda_10.0.130_411.31_win10 and cudnn-10.0-windows10-x64-v7.6.4.38.

**Comment by gadagashwini** [comment]
@WrathofBhuvan11,
Did you try the suggestion of @ahtik's. Thanks!

**Comment by gadagashwini** [comment]
@WrathofBhuvan11, Were you able to resolve this issue. Thanks

**Comment by gadagashwini** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Comment by Donald-Su** [comment]
same issue, I can't use the GPU when I used the follow command:

```shell
from tensorflow.python.client import device_lib
print(device_lib.list_local_devices())
```

my environment:
```shell
#cuda version
Cuda compilation tools, release 10.1, V10.1.243

#tensorflow version
tensorflow (1.14.0)
tensorflow-gpu (1.14.0)

#OS version
CentOS Linux release 7.6.1810 (Core)

#kernel version
3.10.0-957.el7.x86_64

```

**Comment by gadagashwini** [comment]
@Donald-Su ,
Please post a new issue and provide all the information asked by the template. We ask this because it's more efficient to have one thread dedicated to one issue. Thanks!
