### ISSUE TITLE
 "tf.train.experimental.enable_mixed_precision_graph_rewrite(opt)" is not compatible with "tf.keras.LearningRateScheduler" and "tf.keras.ReduceLROnPlateau"

### ISSUE THREAD

**Issue by joe1chief** [tensorflow/tensorflow#32905]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**Ubuntu 18.04**
- TensorFlow version (you are using): 1.14.0
- Are you willing to contribute it (Yes/No): No

After calling "opt = tf.train.experimental.enable_mixed_precision_graph_rewrite(opt)", the returned opt lost its attribute "lr".

**Comment by byronyi** [comment]
I believe it’s fixed in latest master. Could you try with the latest nightly packages again?

**Comment by gadagashwini** [comment]
@joe1chief,
Can you try the @byronyi's suggestion and let us if that resolves your issue. Thanks!

**Comment by gadagashwini** [comment]
@joe1chief, Did you try with the latest TF nightly build version. Thanks

**Comment by gadagashwini** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
