### ISSUE TITLE
Wrong links in API document and search results

### ISSUE THREAD

**Issue by canasta** [tensorflow/tensorflow#32915]
Items in TensorFlow Core r1.14 is linked to r2.0.
In search results, all informations are correct except the link.
All links point to RC version, not r1.14.

I checked tf.nn.dynamic_rnn and tf.nn.fused_batch_norm.
dynamic_rnn is linked to [https://www.tensorflow.org/api_docs/python/tf/nn/dynamic_rnn](https://www.tensorflow.org/api_docs/python/tf/nn/dynamic_rnn) now.
But [https://www.tensorflow.org/versions/r1.14/api_docs/python/tf/nn/dynamic_rnn](https://www.tensorflow.org/versions/r1.14/api_docs/python/tf/nn/dynamic_rnn) is right.

**Comment by jvishnuvardhan** [comment]
@canasta Can you explain the issue with little more details. I checked the links you provided and both points to same page. Are you seeing different page? Please let us know. Thanks!

**Comment by canasta** [comment]
When I write this issue, the link(first result in [https://www.tensorflow.org/s/results?q=dynamic_rnn](this) page) moves me to [https://www.tensorflow.org/api_docs/python/tf/nn/dynamic_rnn](https://www.tensorflow.org/api_docs/python/tf/nn/dynamic_rnn) and it shows 404 ERROR.
And I tried again with another module which exist in r2.0 and r1.14 both, than search result moves me to r2.0 page, not 404 and r1.14 page.

But it seems fixed now, so I'll close this.

**Comment by jvishnuvardhan** [comment]
@canasta Actually team is working hard on updating the docs. Updating many docs from 1.x to 2.x is a huge task. Still there are some links are not working in TF website but are updated in master branch. So, in the near future TF website will be updated completely.

Please let us know If you see any link that is not working as intended. Thanks!
