### ISSUE TITLE
local variable 'nccl_lib_path' referenced before assignment

### ISSUE THREAD

**Issue by Julius-ZCJ** [tensorflow/tensorflow#32916]
When I compile the tensorflow-1.12.0 version , I process command :
./configure

and then I got this error:
  File "./configure.py", line 1693, in <module>
    main()
  File "./configure.py", line 1612, in main
    set_tf_nccl_install_path(environ_cp)
  File "./configure.py", line 1208, in set_tf_nccl_install_path
    nccl_lib_path = os.path.join(nccl_install_path, nccl_lib_path)
UnboundLocalError: local variable 'nccl_lib_path' referenced before assignment

my bazel version is 0.15.0,  gcc is 5.4.0

**Comment by gowthamkpr** [comment]
Please take a look at the similar issue [here](https://github.com/FloopCZ/tensorflow_cc/issues/147) and let me know if it helps. Thanks!

**Comment by gowthamkpr** [comment]
@Julius-ZCJ Did you solve the issue or are you still facing the same issue?

**Comment by Julius-ZCJ** [comment]
Yes, I solved this problem, but have some other issues raise. I'm now fight against that.

**Comment by gowthamkpr** [comment]
Closing this issue as it has been resolved.
