### ISSUE TITLE
Attention :module 'tensorflow.python.keras.api._v2.keras.layers' has no attribute 'Attention'

### ISSUE THREAD

**Issue by ares5221** [tensorflow/tensorflow#32913]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):Win10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):source
- TensorFlow version (use command below):2.0.0a0
- Python version:3.6
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`
model = keras.Sequential()
model.add(tf.keras.layers.Embedding(max_words, embed_size))
model.add(tf.keras.layers.Bidirectional(tf.keras.layers.LSTM(128, return_sequences=True)))
model.add(tf.keras.layers.Attention())
**Describe the current behavior**
AttributeError: module 'tensorflow.python.keras.api._v2.keras.layers' has no attribute 'Attention'
**Describe the expected behavior**

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by ahtik** [comment]
@ares5221 Could you try with 2.0.0rc1 or 2.0.0rc2 instead of 2.0.0a0? There it's all good for me.

**Comment by mihaimaruseac** [comment]
2.0.0a0 is extremely old, please switch to 2.0.0rc2

**Comment by gowthamkpr** [comment]
@ares5221 Please find the github gist [here](https://colab.sandbox.google.com/gist/gowthamkpr/62089d4044afed594e0c08e5ad6b4c8e/untitled152.ipynb). Attention layer does exist in tensorflow 2.0.0-rc2.

**Comment by jvishnuvardhan** [comment]
@ares5221 As mentioned by others, attention layer exists in recent versions of tensorflow (`TF2.0.0` and others). Please check the more details and code examples of attention layer [here](https://www.tensorflow.org/api_docs/python/tf/keras/layers/Attention).

I am closing this issue as this was resolved. Please feel free to open the issue if the issue persists in `TF2.0`. Thanks!

**Comment by ares5221** [comment]
> @ares5221 Could you try with 2.0.0rc1 or 2.0.0rc2 instead of 2.0.0a0? There tf.keras.layers.Attention does exist.

i try in win10，2.0.0rc2 it works, and ubuntu18.04 only support 2.0.0b1,and it works too
thanks very much

**Comment by mihaimaruseac** [comment]
2.0.0 should be supported by every OS. Please make sure you have the latest `pip` though.

**Comment by ares5221** [comment]
> 2.0.0 should be supported by every OS. Please make sure you have the latest `pip` though.

yes，thks
