### ISSUE TITLE
No `libtensorflow_framework.so`

### ISSUE THREAD

**Issue by netw0rkf10w** [tensorflow/tensorflow#32910]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 16.04.6 LTS (GNU/Linux 4.15.0-55-generic x86_64)
- TensorFlow installed from (source or binary): `pip install tensorflow-gpu==2.0.0rc2`
- TensorFlow version (use command below): v2.0.0-rc1-51-g2646d23 2.0.0-rc2
- Python version: 3.5.2
- CUDA/cuDNN version: 10.0/7.6.4.38
- GPU model and memory: GTX 1080 Ti 11GB

**Describe the current behavior**
No `libtensorflow_framework.so` inside `/home/username/.env/python3/lib/python3.5/site-packages/tensorflow_core`. Only `libtensorflow_framework.so.2` is present.

**Describe the expected behavior**
Both `libtensorflow_framework.so.2` and `libtensorflow_framework.so` should be present in `/home/username/.env/python3/lib/python3.5/site-packages/tensorflow_core`.

**Comment by Leslie-Fang** [comment]
Hi @netw0rkf10w , But why must libtensorflow_framework.so exsit?

**Comment by netw0rkf10w** [comment]
Hi @Leslie-Fang. Good question!
I am not sure if `libtensorflow_framework.so` must exist, but there are 2 reasons why I thought it should exist:

- It was existing before in previous versions. When compiling a custom TF operator in 2.0.0rc2, I obtained `ltensorflow_framework` linking error (it was working in TF 1.14). I had to create a symbolic link `libtensorflow_framework.so` pointing to `libtensorflow_framework.so.2` for it to work.

- When I checked on my Mac (TF 2.0.0rc2), in `/Users/username/.env/python3/lib/python3.7/site-packages/tensorflow_core` there are 3 files:
`libtensorflow_framework.2.0.0.dylib,	lnsorflow_framework.2.dylib				libtensorflow_framework.dylib

**Comment by jvishnuvardhan** [comment]
This is not Build/Installation or Bug/Performance issue. Please post this kind of support questions at [Stackoverflow](https://stackoverflow.com/questions/tagged/tensorflow). There is a big community to support and learn from your questions. GitHub is mainly for addressing bugs in installation and performance. Thanks!

**Comment by netw0rkf10w** [comment]
I have updated the CMakeLists of my project by making use of `tf.sysconfig.get_link_flags(), tf.sysconfig.get_compile_flags()` and it works.

The conclusion is that it is not necessary to have `libtensorflow_framework.so`. Thanks.

**Comment by mihaimaruseac** [comment]
Yes, it is recommended to use `tf.sysconfig.get_*_flags()` instead of manually specifying the filepaths.

**Comment by netw0rkf10w** [comment]
@mihaimaruseac Thanks. Building was successful, but then I obtained an `undefined symbol: _ZTIN10tensorflow8OpKernelE` error :( I'm posing a question to StackOverflow...

**Comment by netw0rkf10w** [comment]
@mihaimaruseac Could you kindly help: https://stackoverflow.com/questions/58174643/issues-when-compiling-tensorflow-custom-operator-tf-2-0-0? Thank you so much!

**Comment by mihaimaruseac** [comment]
Why not use the bazel build? Makefile build is not supported and most likely you're missing a dependency.

**Comment by netw0rkf10w** [comment]
@mihaimaruseac Sorry I wanted to reply yesterday but the page was not reachable (probably because of the release). What do you mean by THE bazel build? I'm not building TensorFlow from source, I'm just building a custom operator.
