### ISSUE TITLE
model.fit with tf.data.Dataset.from_generator can't infer shape

### ISSUE THREAD

**Issue by matpalm** [tensorflow/tensorflow#32912]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): MacOs 10.13.6
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): v2.0.0-beta1-5101-gc75bb66a99 2.0.0-rc0
- Python version: 3.6.4 
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

**Describe the current behavior**

`model.fit` when given a `tf.data` dataset (that uses a `from_generator`) throws `ValueError: as_list() is not defined on an unknown TensorShape.` 

see https://gist.github.com/matpalm/779c2c67d5ec195845ae2ab01570d883 for full traceback

**Describe the expected behavior**

model.fit should be able to infer the shape of the input.

**Code to reproduce the issue**

```
import tensorflow as tf
from tensorflow.keras.layers import *
from tensorflow.keras.models import Model
from tensorflow.keras.optimizers import Adam

inp = Input(shape=(3,))
output = Dense(1, activation='sigmoid')(inp)
model = Model(inp, output)
model.compile(optimizer=Adam(1e-2), loss='binary_crossentropy')

def simple_generator():
    while True:
        yield [0.5, 0.2, -0.3], 0.0
        yield [-0.5, 0.3, -0.1], 1.0
        
dataset = tf.data.Dataset.from_generator(simple_generator,
                                         output_types=(tf.float32,
                                                       tf.float32))
dataset = dataset.batch(4).prefetch(1)

model.fit(dataset)
```

throws `ValueError: as_list() is not defined on an unknown TensorShape.`

note: the following works...

```
for X, y in dataset:
  model.fit(X, y)
  break
```

**Other info / logs**

see https://gist.github.com/matpalm/779c2c67d5ec195845ae2ab01570d883 for full traceback

**Comment by gowthamkpr** [comment]
Was able to reproduce this issue. Please find the github gist [here](https://colab.sandbox.google.com/gist/gowthamkpr/ca54b9920fba141a43b2ecfa87af9232/untitled154.ipynb).

**Comment by dangerden** [comment]
I see the same behaviour with dataset created from tf.data.Dataset.list_files and then mapped into X,Y tensors dataset

**Comment by borarak** [comment]
I also see the same behavior, downgrading to `2.0b1` makes the problem go away. Seems like a problem with the `2.0.0` stable release?

**Comment by JacobJeppesen** [comment]
I just tested with the docker images (py3-gpu), and the bug started occurring between 2.0.0b1 and 2.0.0rc0.

**Comment by caesarnine** [comment]
Ran into the same issue when trying to use model.fit() with a tf.data.dataset initialized from a generator of 2.0.0 stable. 

For now as a workaround model.fit_generator() seems to work on the same dataset object.

**Comment by SR-Artrya** [comment]
I have a similar issue pulling multidimensional arrays from TFRecords datapipeline after parsing/serializing. As others have tested change occurs between 2.0.0b1 and 2.0.0rc0.

**Comment by optiluca** [comment]
Having the same issue, using model.fit_generator() also seems to be a valid workaround.  In tf.keras the line between model.fit and model.fit_generator seems quite blurred, particularly when working with tf.data.Dataset inputs.  Which one are we actually meant to be using?

**Comment by optiluca** [comment]
> Having the same issue, using model.fit_generator() also seems to be a valid workaround. In tf.keras the line between model.fit and model.fit_generator seems quite blurred, particularly when working with tf.data.Dataset inputs. Which one are we actually meant to be using?

Replying to myself, seemingly .fit since .fit_generator doesn't even support distributed training via a tf.distribute strategy.

**Comment by vicpara** [comment]
I have the same problem and I confirm `fit_generator` solves the problem while `fit` fails with 
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-1-80f4363a81b7> in <module>
     42 
     43 print(model.summary())
---> 44 model.fit(dataset, epochs=EPOCHS, verbose=2)

~/.pyenv/versions/3.7.4/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training.py in fit(self, x, y, batch_size, epochs, verbose, callbacks, validation_split, validation_data, shuffle, class_weight, sample_weight, initial_epoch, steps_per_epoch, validation_steps, validation_freq, max_queue_size, workers, use_multiprocessing, **kwargs)
    726         max_queue_size=max_queue_size,
    727         workers=workers,
--> 728         use_multiprocessing=use_multiprocessing)
    729 
    730   def evaluate(self,

~/.pyenv/versions/3.7.4/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training_v2.py in fit(self, model, x, y, batch_size, epochs, verbose, callbacks, validation_split, validation_data, shuffle, class_weight, sample_weight, initial_epoch, steps_per_epoch, validation_steps, validation_freq, **kwargs)
    322                 mode=ModeKeys.TRAIN,
    323                 training_context=training_context,
--> 324                 total_epochs=epochs)
    325             cbks.make_logs(model, epoch_logs, training_result, ModeKeys.TRAIN)
    326 

~/.pyenv/versions/3.7.4/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training_v2.py in run_one_epoch(model, iterator, execution_function, dataset_size, batch_size, strategy, steps_per_epoch, num_samples, mode, training_context, total_epochs)
    121         step=step, mode=mode, size=current_batch_size) as batch_logs:
    122       try:
--> 123         batch_outs = execution_function(iterator)
    124       except (StopIteration, errors.OutOfRangeError):
    125         # TODO(kaftan): File bug about tf function and errors.OutOfRangeError?

~/.pyenv/versions/3.7.4/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training_v2_utils.py in execution_function(input_fn)
     84     # `numpy` translates Tensors to values in Eager mode.
     85     return nest.map_structure(_non_none_constant_value,
---> 86                               distributed_function(input_fn))
     87 
     88   return execution_function

~/.pyenv/versions/3.7.4/lib/python3.7/site-packages/tensorflow_core/python/eager/def_function.py in __call__(self, *args, **kwds)
    455 
    456     tracing_count = self._get_tracing_count()
--> 457     result = self._call(*args, **kwds)
    458     if tracing_count == self._get_tracing_count():
    459       self._call_counter.called_without_tracing()

~/.pyenv/versions/3.7.4/lib/python3.7/site-packages/tensorflow_core/python/eager/def_function.py in _call(self, *args, **kwds)
    501       # This is the first call of __call__, so we have to initialize.
    502       initializer_map = object_identity.ObjectIdentityDictionary()
--> 503       self._initialize(args, kwds, add_initializers_to=initializer_map)
    504     finally:
    505       # At this point we know that the initialization is complete (or less

~/.pyenv/versions/3.7.4/lib/python3.7/site-packages/tensorflow_core/python/eager/def_function.py in _initialize(self, args, kwds, add_initializers_to)
    406     self._concrete_stateful_fn = (
    407         self._stateful_fn._get_concrete_function_internal_garbage_collected(  # pylint: disable=protected-access
--> 408             *args, **kwds))
    409 
    410     def invalid_creator_scope(*unused_args, **unused_kwds):

~/.pyenv/versions/3.7.4/lib/python3.7/site-packages/tensorflow_core/python/eager/function.py in _get_concrete_function_internal_garbage_collected(self, *args, **kwargs)
   1846     if self.input_signature:
   1847       args, kwargs = None, None
-> 1848     graph_function, _, _ = self._maybe_define_function(args, kwargs)
   1849     return graph_function
   1850 

~/.pyenv/versions/3.7.4/lib/python3.7/site-packages/tensorflow_core/python/eager/function.py in _maybe_define_function(self, args, kwargs)
   2148         graph_function = self._function_cache.primary.get(cache_key, None)
   2149         if graph_function is None:
-> 2150           graph_function = self._create_graph_function(args, kwargs)
   2151           self._function_cache.primary[cache_key] = graph_function
   2152         return graph_function, args, kwargs

~/.pyenv/versions/3.7.4/lib/python3.7/site-packages/tensorflow_core/python/eager/function.py in _create_graph_function(self, args, kwargs, override_flat_arg_shapes)
   2039             arg_names=arg_names,
   2040             override_flat_arg_shapes=override_flat_arg_shapes,
-> 2041             capture_by_value=self._capture_by_value),
   2042         self._function_attributes,
   2043         # Tell the ConcreteFunction to clean up its graph once it goes out of

~/.pyenv/versions/3.7.4/lib/python3.7/site-packages/tensorflow_core/python/framework/func_graph.py in func_graph_from_py_func(name, python_func, args, kwargs, signature, func_graph, autograph, autograph_options, add_control_dependencies, arg_names, op_return_value, collections, capture_by_value, override_flat_arg_shapes)
    913                                           converted_func)
    914 
--> 915       func_outputs = python_func(*func_args, **func_kwargs)
    916 
    917       # invariant: `func_outputs` contains only Tensors, CompositeTensors,

~/.pyenv/versions/3.7.4/lib/python3.7/site-packages/tensorflow_core/python/eager/def_function.py in wrapped_fn(*args, **kwds)
    356         # __wrapped__ allows AutoGraph to swap in a converted function. We give
    357         # the function a weak reference to itself to avoid a reference cycle.
--> 358         return weak_wrapped_fn().__wrapped__(*args, **kwds)
    359     weak_wrapped_fn = weakref.ref(wrapped_fn)
    360 

~/.pyenv/versions/3.7.4/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training_v2_utils.py in distributed_function(input_iterator)
     64     """A single step of the distributed execution across replicas."""
     65     x, y, sample_weights = _prepare_feed_values(
---> 66         model, input_iterator, mode)
     67     # Call `Model.{train,test,predict}_on_batch` on every replica passing
     68     # PerReplicas as arguments.  On every replica inside this call, each

~/.pyenv/versions/3.7.4/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training_v2_utils.py in _prepare_feed_values(model, inputs, mode)
    110     for inputs will always be wrapped in lists.
    111   """
--> 112   inputs, targets, sample_weights = _get_input_from_iterator(inputs)
    113 
    114   # When the inputs are dict, then we want to flatten it in the same order as

~/.pyenv/versions/3.7.4/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training_v2_utils.py in _get_input_from_iterator(iterator)
    147   # Validate that all the elements in x and y are of the same type and shape.
    148   dist_utils.validate_distributed_dataset_inputs(
--> 149       distribution_strategy_context.get_strategy(), x, y, sample_weights)
    150   return x, y, sample_weights
    151 

~/.pyenv/versions/3.7.4/lib/python3.7/site-packages/tensorflow_core/python/keras/distribute/distributed_training_utils.py in validate_distributed_dataset_inputs(distribution_strategy, x, y, sample_weights)
    309 
    310   if y is not None:
--> 311     y_values_list = validate_per_replica_inputs(distribution_strategy, y)
    312   else:
    313     y_values_list = None

~/.pyenv/versions/3.7.4/lib/python3.7/site-packages/tensorflow_core/python/keras/distribute/distributed_training_utils.py in validate_per_replica_inputs(distribution_strategy, x)
    354     if not context.executing_eagerly():
    355       # Validate that the shape and dtype of all the elements in x are the same.
--> 356       validate_all_tensor_shapes(x, x_values)
    357     validate_all_tensor_types(x, x_values)
    358 

~/.pyenv/versions/3.7.4/lib/python3.7/site-packages/tensorflow_core/python/keras/distribute/distributed_training_utils.py in validate_all_tensor_shapes(x, x_values)
    371 def validate_all_tensor_shapes(x, x_values):
    372   # Validate that the shape of all the elements in x have the same shape
--> 373   x_shape = x_values[0].shape.as_list()
    374   for i in range(1, len(x_values)):
    375     if x_shape != x_values[i].shape.as_list():

~/.pyenv/versions/3.7.4/lib/python3.7/site-packages/tensorflow_core/python/framework/tensor_shape.py in as_list(self)
   1169     """
   1170     if self._dims is None:
-> 1171       raise ValueError("as_list() is not defined on an unknown TensorShape.")
   1172     return [dim.value for dim in self._dims]
   1173 

ValueError: as_list() is not defined on an unknown TensorShape.
```

Below my full code that reproduces the problem:  
```
import numpy as np
import pandas as pd
import random
import tensorflow as tf
import time as tm

INPUT_SHAPE=[7, 9]
NUM_POINTS=2000
BATCH_SIZE=32
BUFFER_SIZE=32
EPOCHS=2

def gen():
    for i in range(1000):
        x = np.random.rand(INPUT_SHAPE[0],INPUT_SHAPE[1])
        y = np.random.randint(1, 3, size=1)
        yield x,y
    
dataset = tf.data.Dataset.from_generator(gen, 
                                         (tf.float32, tf.int16),
                                         output_shapes=(tf.TensorShape(INPUT_SHAPE), tf.TensorShape(None))
                                        ).batch(BATCH_SIZE)

def create_model(input_shape):
    model = tf.keras.models.Sequential([
        tf.keras.layers.Dense(100, activation="tanh", input_shape=input_shape),
        tf.keras.layers.Flatten(),
        tf.keras.layers.Dense(3, activation="softmax")
    ])
    return model

model = create_model(input_shape=INPUT_SHAPE)
model.compile(
    optimizer=tf.keras.optimizers.Adam(learning_rate=1e-4, clipvalue=1.0),
    loss= tf.keras.losses.CategoricalCrossentropy(),
    )

iterator = dataset.make_one_shot_iterator()
x,y = iterator.get_next()
print("X.shape", x.shape, y.shape)
print("Predicted", model.predict(x).shape)

print(model.summary())
model.fit_generator(dataset, epochs=EPOCHS, verbose=2)
model.fit(dataset, epochs=EPOCHS, verbose=2)
```

**Comment by stefanondisponibile** [comment]
I can confirm that `fit_generator` works around the issue, but I experienced it **wihout** making the dataset `from_generator`. I was actually working with with a `tf.data.TFRecordDataset`, but the following code reproduces the issue with `fom_tensor_slices`:

```python
import tensorflow as tf               # 2.0.0
import tensorflow_datasets as tfds    # 1.3.0

# Dummy data.
text = [
  "the quick",
  "brown fox",
  "jups over",
  "the lazy",
  "dog."
]
target = [
  "class_1,class_2",
  "class_1",
  "class_2",
  "class_1",
  "class_1,class_2"
]

batch_size = 2

# Make dataset.
dataset = tf.data.Dataset.from_tensor_slices((text, target))

# Text (features) encoder.
corpus_generator = (t[0].numpy() for t in dataset) 
encoder = tfds.features.text.SubwordTextEncoder.build_from_corpus(
  corpus_generator, 
  target_vocab_size=500
)

# Targets lookup.
targets = tf.lookup.StaticHashTable(tf.lookup.KeyValueTensorInitializer(
  keys=["class_1", "class_2"], 
  values=[1,2], 
  value_dtype=tf.int64), default_value=-1
)

vocab_size = encoder.vocab_size
n_targets = targets.size().numpy()
print(f"vocab_size: {vocab_size}\tn_targets: {n_targets}")

# Map fn.
encode = lambda x: [encoder.encode(x.numpy())]
tf_encode = lambda x: tf.reduce_sum(
  tf.one_hot(
    tf.py_function(encode, [x], tf.int64), 
    depth=vocab_size, 
    axis=None, 
    dtype=tf.int64), 
  axis=0, 
  keepdims=False
)

lookup_targets = lambda x: tf.reduce_sum(
  tf.one_hot(
    targets.lookup(tf.strings.split(x, sep=",")),
    depth=n_targets,
    axis=None,
    dtype=tf.float32), 
  axis=0, 
  keepdims=False
)

parse_fn = lambda x, y: (tf_encode(x), lookup_targets(y))
dataset = dataset.map(parse_fn)
dataset = dataset.batch(batch_size)

for batch_x, batch_y in dataset:
  print("*** BATCH ***")
  for i, (x, y) in enumerate(zip(batch_x, batch_y)):
    print(f"> EXAMPLE {i + 1}")
    print(f"text   : {x.numpy()} => shape: {x.shape}")
    print(f"target : {y.numpy()} => shape:{y.shape}")
    print()
  print()

inputs = tf.keras.layers.Input(shape=(vocab_size,))
outputs = tf.keras.layers.Dense(units=n_targets)(inputs)  # no activation!

model = tf.keras.Model(
  inputs=[inputs], 
  outputs=[outputs], 
)

print(f"Sample prediction: {model.predict(dataset.take(1))}\n")

loss = tf.keras.losses.BinaryCrossentropy()
optimizer = tf.keras.optimizers.Adam()

model.compile(optimizer=optimizer, loss=loss, metrics=["accuracy"])

history = model.fit(
  dataset,
  epochs=5,
)
```

**Comment by jpambrun** [comment]
Adding the following after batching allowed me to work around this issue:
```python
def _fixup_shape(images, labels, weights):
    images.set_shape([None, None, None, 3])
    labels.set_shape([None, 19]) # I have 19 classes
    weights.set_shape([None])
    return images, labels, weights
dataset = dataset.map(_fixup_shape)
```

**Comment by stefanondisponibile** [comment]
> Adding the following after batching allowed me to work around this issue:
> 
> ```python
> def _fixup_shape(images, labels, weights):
>     images.set_shape([None, None, None, 3])
>     labels.set_shape([None, 19]) # I have 19 classes
>     weights.set_shape([None])
>     return images, labels, weights
> dataset = dataset.map(_fixup_shape)
> ```

This works for me too.

**Comment by jjedele** [comment]
Also seeing this issue. For me it's happening with a FixedSizeRecordDataset with an explicit reshape at the end:

```
ds = tf.data.FixedLengthRecordDataset(
        path,
        record_bytes=28 * 28, # rows * cols
        header_bytes=4 + 4 + 4 + 4, # magic number + record count + rows + cols
        compression_type="GZIP"
    )

ds = ds.map(lambda x: tf.io.decode_raw(x, tf.uint8))
ds = ds.map(lambda x: tf.reshape(x, (28, 28)))
ds = ds.map(lambda x: tf.ensure_shape(x, (28, 28)))
```

.fit_generator() works.

**Comment by venter-zhu** [comment]
same problem,mark

**Comment by ding-c3** [comment]
Running into the same issue. `fit_generator` is not an option for us due to need for DistributionStrategy.

**Comment by vicpara** [comment]
Managed to fix this like this: https://gist.github.com/vicpara/5c23c78d0f3105af53798272e628d2ad .
My guess is that this is a problem related to deserialized tensors.

**Comment by Saduf2019** [comment]
@matpalm 
Is this still an issue.

**Comment by chrismaliszewski** [comment]
In my case problem was in using many metrics out of the ones specified inside compile_utils.py line 453 which require IteratorGetNext shape which I didn't have.

> ```python
> def _fixup_shape(images, labels, weights):
>     images.set_shape([None, None, None, 3])
>     labels.set_shape([None, 19]) # I have 19 classes
>     weights.set_shape([None])
>     return images, labels, weights
> dataset = dataset.map(_fixup_shape)
> ```

@jpambrun's solution worked for me! 

NOTE: it doesn't matter whether you first do batch or map. But you'll need two map functions! The first is used for getting data, the other one setting the shape. Doing everything in one function fails, I don't know why exactly, even if you convert data to Tensor and set_shape before returning it. So I have the following order
```dataset.batch.map(get_data).map(fix_shape).prefetch``` 
and everything goes smoothly.

**Comment by BlueskyFR** [comment]
Any update on this?
I am having this problem after setting some `output_signature` params to None since the last batch is smaller than the previous ones (for example, training with 14 000 elements with a batch size of 32 gives a last batch of 16 elements only.
```python
Dataset.from_generator(
    gen,
    output_signature=(
        tf.TensorSpec(shape=(None, 32, 32, 3), dtype=tf.float32),
        tf.TensorSpec(shape=None, dtype=tf.float32)
    )
)
```
What has been done so far?

**Comment by chrismaliszewski** [comment]
@BlueskyFR, shouldn't you set the output params to (None, 1)? The None shape is used for batch_size, right?

**Comment by matpalm** [comment]
@BlueskyFR for small last batch size i always give up trying to get shapes right and just use `drop_remainder=True`

https://www.tensorflow.org/api_docs/python/tf/data/Dataset#batch

**Comment by BlueskyFR** [comment]
Thanks @chrismaliszewski and @matpalm for your answers!
Yeah I could have used `drop_remainder=True` but I was trying to learn the right way to keep all the values no matter what :)

However, I managed to find the solution to my problem, for those interested: a comma was missing :)
```diff
Dataset.from_generator(
    gen,
    output_signature=(
        tf.TensorSpec(shape=(None, 32, 32, 3), dtype=tf.float32),
-       tf.TensorSpec(shape=None, dtype=tf.float32)
+       tf.TensorSpec(shape=(None,), dtype=tf.float32)
    )
)
```

When using a batch size which is not a multiple of the total training elements count (so when `train_ds_element_count % batch_size != 0`), the `batch_size` in the `tf.TensorSpec(...)` must be set to None to be considered as dynamic.
Also, my error was to specify the output shape as `None` or `(None)` instead of `(None,)` which is considered as a **tuple** when the comma is added.

Hope it helps!

**Comment by iheonyeac** [comment]
> Adding the following after batching allowed me to work around this issue:
> 
> ```python
> def _fixup_shape(images, labels, weights):
>     images.set_shape([None, None, None, 3])
>     labels.set_shape([None, 19]) # I have 19 classes
>     weights.set_shape([None])
>     return images, labels, weights
> dataset = dataset.map(_fixup_shape)
> ```

Thank you so much jpambrun!! This worked well for me.

**Comment by phunc20** [comment]
Hi. I cannot manage to get the same tf version (2.0.0-rc0) on conda, but I tried the closest one I can find, which is version 2.0.0. I guess one workaround for this problem might be

- not only should we specify `output_types`
- **but also `output_shapes`**

The following snippets ran fine on an IPython session on my machine (Python3.6.13):
```python
import tensorflow as tf
from tensorflow.keras.layers import *
from tensorflow.keras.models import Model
from tensorflow.keras.optimizers import Adam

inp = Input(shape=(3,))
output = Dense(1, activation='sigmoid')(inp)
model = Model(inp, output)
model.compile(optimizer=Adam(1e-2),
              loss='binary_crossentropy',
)

def simple_generator():
    while True:
        yield [0.5, 0.2, -0.3], 0.0
        yield [-0.5, 0.3, -0.1], 1.0

dataset = tf.data.Dataset.from_generator(
    simple_generator,
    output_types=(tf.float32, tf.float32),
    output_shapes=((3,), (),)
)

dataset = dataset.batch(4).prefetch(1)

model.fit(dataset)
```
With output as follows:
```
   1591/Unknown - 6s 4ms/step - loss: 0.1298
```

**Comment by sushreebarsa** [comment]
@matpalm Could you please try on latest stable version of tf 2.5 or 2.4.1 and let us know if this is still an issue.Thanks!

**Comment by matpalm** [comment]
happy to close, thought i actually had over a year ago sorry!

**Comment by geometrikal** [comment]
@sushreebarsa 

This is still an issue if you are creating a dataset from filenames - e.g. from_generator creating the dataset from filenames, then using map and tf.io.decode_image to create the actual files

**Comment by Cyberface** [comment]
> ```
>    1591/Unknown - 6s 4ms/step - loss: 0.1298
> ```

I am creating a dataset from filenames and also see this "/Unknown" text when calling `model.fit`. Does anyone know why this happens?

**Comment by matpalm** [comment]
@cyberface it wouldn't be the dataset size, it's just that a generator doesn't have a length. i.e. you would have seen this with a tiny dataset. if you are just dealing with a fixed set of filenames you could just use `from_tensor_slices`

**Comment by Cyberface** [comment]
@matpalm ah ok thank you for the clarification, very helpful!

**Comment by mchlsdrv** [comment]
Thanks @jpambrun  - 

```
def _fixup_shape(images, labels, weights):
    images.set_shape([128, 128, 1])
    labels.set_shape([]) # I have 19 classes
    return images, labels, weights

dataset = dataset.map(_fixup_shape)

```
Worked for me.

Though it would be interesting to figure out the cause of this issue - i.e., is it a bug in TF 2.0, or is it an expected behavior?

**Comment by MarkDaoust** [comment]
This is expected behavior.

Normally TensorFlow can handle shapes with unknown dimensions. It really can't handle shapes with an unknown **number of dimensions**. 

`from_generator` has the option of setting the shapes in the arguments.  

Even if you don't fully know the shape, just setting the rank will often fix this. Fpr example, if you know the output is 3d but you don't know the sizes, set: `tf.data.Dataset.from_generator(..., output_shapes=[None, None, None])`.

**Comment by abiwaring** [comment]
Was the a one-size-fits-all fix to this ?
I have data generator tile shapes of 1,48,48,1 separated into train and val for day and night time temp data

import tensorflow as tf
dg = tf.data.Dataset.from_generator(data_generator, args=(0.2,0), output_types=(tf.float64, tf.float64))
val_dg = tf.data.Dataset.from_generator(data_generator, args=(0.2,1), output_types=(tf.float64, tf.float64))

dg = dg.unbatch().batch(2)

# use train gen, no of epochs, use val_gen to validate (specify separate data)
history = model.fit_generator(dg,epochs=3, validation_data=val_dg, callbacks=[checkpoint])

This is giving me:
   ValueError: as_list() is not defined on an unknown TensorShape.
