### ISSUE TITLE
How to create an op like conv_ops in tensorflow?

### ISSUE THREAD

**Issue by wishforgood** [tensorflow/tensorflow#3291]
Notice that I'm not looking for a tutorial like [this](https://github.com/jikexueyuanwiki/tensorflow-zh/blob/master/SOURCE/how_tos/adding_an_op/index.md).
**What I'm trying to do**

I'm new to C++ and bazel and I want to make some change on the convolution operation in tensorflow, so I decide that my first step is to create an ops just like it.

**What I have done**

I copied conv_ops.cc from //tensorflow/core/kernels and change the name of the ops registrated in my new_conv_ops.cc. I also changed some name of the functions in the file to avoid duplication. And here is my BUILD file. 
![qq 20160713201655](https://cloud.githubusercontent.com/assets/9963412/16803076/c495f610-4936-11e6-9e28-9aa27dd55e4d.png)

As you can see, I copy the deps attributes of conv_ops from //tensorflow/core/kernels/BUILD. Then I use "bazel build -c opt //tensorflow/core/user_ops:new_conv_ops.so" to build the new op.

**What my problem is**

Then I got this error.
![](https://cloud.githubusercontent.com/assets/9963412/16803048/9b960250-4936-11e6-90ab-7e7cd3b81b96.png)

I tried to delete bounds_check and got same error for the next deps. Then I realize that there is some problem for including h files in //tensorflow/core/kernels from //tensorflow/core/user_ops. So how can I perfectely create a new op excatcly like conv_ops?
****

**Comment by jmchen-g** [comment]
I suggest you just create a new conv_op in the same file to avoid all such issues.

Please redirect such questions to stackoverflow.
