### ISSUE TITLE
Unable to input categorical columns in my preprocessing layer for keras

### ISSUE THREAD

**Issue by Odera-Dim** [tensorflow/tensorflow#32921]
Hi All,

I am trying to use python to run the [example](https://www.tensorflow.org/tutorials/load_data/csv) which is given on the tensorflow website on working with .CSV data. This example is meant to use some features to predict if a passenger is labeled dead or alive on the titanic. Everything goes well until the point where I attempt to run a fit on the training data data. The error below is generated:

FailedPreconditionError: Table already initialized.
	 [[{{node sequential_9/dense_features_17/embark_town_indicator/embark_town_lookup/hash_table/table_init/LookupTableImportV2}}]] [Op:__inference_keras_scratch_graph_11639]

If I attempt to use the numeric features alone the code runs to completion. I have output the layers from a batch (small size batch of 3 - 5) and it makes sense to the data which is input.   Has anyone had similar experience or would anyone kindly help with this? Thank you. I have added the link to the website so that it can be accessed by anyone checking but if you need the ipython file, I can provide that too. Thanks in advance.

**Comment by gowthamkpr** [comment]
I tried runningthe same example on google colab and its working finr foe me without any errors. Please take a look at my github gist [here](https://colab.sandbox.google.com/gist/gowthamkpr/236357c898cebaa78bfd470f953baf56/titanic.ipynb).

**Comment by Odera-Dim** [comment]
I looked through the example on google colab and and it works fine as you said, however mine still doesn't work. I have pretty much everything exact same besides the way I import the data. I have downloaded the training and testing (eval) data unto my google drive. The reason I have it this way is that I want to familiarize myself with working with data on drive. So that in future when I have personal data I am working with it will be easy for me to work straight from drive. Would you mind looking at my .ipynb file to see if the error I am making stands out to you? I have attached a  [link](https://drive.google.com/file/d/13m1MuxJhcTc4xokiaR-NF3DP0ToCSdA8/view?usp=sharing) to my version of the example on colab.

**Comment by Odera-Dim** [comment]
Hi all,

So my version of the example now runs to completion. Excluding the code below seemed to cause the issue I was having. But I have an observation which I will like to clarify. The example only runs to completion if the below code statement is included:

```
try:
  # %tensorflow_version only exists in Colab.
  %tensorflow_version 2.x
except Exception:
  pass

```

The comment written on it states it only exist on google colab. If its not included the Titanic code fails at any point where a tensor is is being converted to numpy. If all I have said so far hold true, how do we implement something similar on Jupyter notebook?  I have read that eager execution can achieve this but I don't know how to implement correctly and how it may differ between Jupyter and google collab. Thanks in advance.

**Comment by gowthamkpr** [comment]
@Odera-Dim You can find my github_gist [here](https://colab.sandbox.google.com/gist/gowthamkpr/a91990922687e78065a089425eb25b5b/untitled157.ipynb). This command `%tensorflow_version 2.x` is installing the latest version of tensorflow 2.x and the example only works in Tensorflow 2.0. 

> how do we implement something similar on Jupyter notebook?

Install tensorflow 2.0.0.rc2 using pip
`pip install tensorflow==2.0.0.rc2`

and the rest you can follow the same steps as given in colab

**Comment by Odera-Dim** [comment]
Thanks a lot,  that went well and the example now works on Jupyter too. Below is a screenshot showing that TF is now updated to version 2.0. Thanks again for spending your time to walk me through this. Cheers.

![TF_Update](https://user-images.githubusercontent.com/43386043/65965260-51962880-e42c-11e9-91d1-9b0c4d734d44.png)
