### ISSUE TITLE
How to explitly save the values of every buffer in a tflite model?

### ISSUE THREAD

**Issue by bwang-delft** [tensorflow/tensorflow#32920]
When using interpreter.get_tensor() to get the values in a tensor after calling interpreter.invoke(), some values seem to be overwritten. If I understand correctly, to explicitly prevent those values from being overwritten, we have to append the names of the tensors we care about in the "output_arrays" argument when calling tf.lite.TFLiteConverter.from_saved_model(). However, some tensors in a tflite model are called "xx_int8" and they don't exist in the original saved model. In this case, how do we include them in "output_arrays"?

**Comment by tilakrayal** [comment]
@bwang-delft ,
Is this still an issue?
Could you please update TensorFlow to the latest stable version v.2.6 and let us know if you are facing the same error. Thanks!
