### ISSUE TITLE
No documentation for tf.strings.reduce_join

### ISSUE THREAD

**Issue by sharvil** [tensorflow/tensorflow#32923]
Thank you for submitting a TensorFlow documentation issue. Per our GitHub
policy, we only address code/doc bugs, performance issues, feature requests, and
build/installation issues on GitHub.

The TensorFlow docs are open source! To get involved, read the documentation
contributor guide: https://www.tensorflow.org/community/contribute/docs

## URL(s) with the issue:
https://www.tensorflow.org/api_docs/python/tf/strings/reduce_join

## Description of issue (what needs changing):
Add documentation for this method.

### Correct links

Is the link to the source code correct?

### Parameters defined

Are all parameters defined and formatted correctly?

### Returns defined

Are return values defined?

### Raises listed and defined

Are the errors defined? For example,
https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/feature_column/categorical_column_with_vocabulary_file#raises

### Usage example

Is there a usage example?

### Request visuals, if applicable

Are there currently visuals? If not, will it clarify the content?

### Submit a pull request?

Are you planning to also submit a pull request to fix the issue? See the docs
contributor guide: https://www.tensorflow.org/community/contribute/docs and the
docs style guide: https://www.tensorflow.org/community/contribute/docs_style

**Comment by MarkDaoust** [comment]
Thanks for the report.

@sharvil this page4 is generated from the [source here](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/ops/string_ops.py#L347-L363).

Any chance you could send me a PR to fix it? 

Note that we support [python doctest for code examples](https://www.tensorflow.org/community/contribute/docs_ref) now.

**Comment by sharvil** [comment]
Sorry Mark, I have neither the setup nor the process know-how to send a PR for this issue. It would be more efficient for someone else to take this on.

On another note, you mentioned in another doc issue that it's not worth the effort to go back and fix documentation bugs for non-current TF releases. Instead, is it possible to add a regression test to make sure that documentation doesn't get dropped in new TF releases (like what happened in this issue and  https://github.com/tensorflow/tensorflow/issues/32528)?

**Comment by MarkDaoust** [comment]
I'll take care of this one. 

For simple things you can often just hit the little "edit" button (pencil button). Spend 5 or 10 minutes trying it out to find useful examples. Paste them in using doctest format. Follow the pattern of other docstrings.

Do try it sometime.

> add a regression test to make sure that documentation doesn't get dropped in new TF releases.

The problem with this sort of test, how can you tell what's right?
When I caused the error in #32528, I rebuilt the docs: ~1000 files changed. The computer can't tell what's right. Not many use a `__new__` constructor. I didn't see it.
