### ISSUE TITLE
tensorflow 2 rc2 + tensorrt6 compile error

### ISSUE THREAD

**Issue by Kevin-Delnoije** [tensorflow/tensorflow#32925]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): source V2.0.0-rc2
- TensorFlow version:
- Python version: 3.6.8
- Installed using virtualenv? pip? conda?:
- Bazel version (if compiling from source): 26.1
- GCC/Compiler version (if compiling from source):7.4..0
- CUDA/cuDNN version:10.1.243 / 7.6.4
- GPU model and memory: rtx 2060 6GB

**Describe the problem**
during compilation the file '/usr/include/x86_64-linux-gnu/NvInferRTSafe.h' can not be found, i suspect this is a path issue. I installed tensorRT using a debian local repo using the nvidia instructions. 

**seems to work without tensorrt in config [still compiling]**

**Provide the exact sequence of commands / steps that you executed before running into the problem**

bazel build --verbose_failures --config=v2 //tensorflow/tools/pip_package:build_pip_package

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

important line (i think): cp: cannot stat '/usr/include/x86_64-linux-gnu/NvInferRTSafe.h': No such file or directory

WARNING: The following configs were expanded more than once: [v2]. For repeatable flags, repeats are counted twice and may lead to unexpected behavior.
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=1 --terminal_columns=204
INFO: Reading rc options for 'build' from /home/kevin/Documents/tensorflow/.bazelrc:
  'build' options: --apple_platform_type=macos --define framework_shared_object=true --define open_source_build=true --define=use_fast_cpp_protos=true --define=allow_oversize_protos=true --spawn_strategy=standalone --strategy=Genrule=standalone -c opt --announce_rc --define=grpc_no_ares=true --define=PREFIX=/usr --define=LIBDIR=$(PREFIX)/lib --define=INCLUDEDIR=$(PREFIX)/include --config=v2
INFO: Reading rc options for 'build' from /home/kevin/Documents/tensorflow/.tf_configure.bazelrc:
  'build' options: --action_env PYTHON_BIN_PATH=/home/kevin/bin/python --action_env PYTHON_LIB_PATH=/usr/local/lib/python3.6/dist-packages --python_path=/home/kevin/bin/python --config=xla --config=tensorrt --action_env CUDA_TOOLKIT_PATH=/usr/local/cuda --action_env TF_CUDA_COMPUTE_CAPABILITIES=7.0,7.5 --action_env LD_LIBRARY_PATH=/usr/local/cuda-10.1/lib64 --action_env GCC_HOST_COMPILER_PATH=/usr/bin/gcc --config=cuda --action_env TF_CONFIGURE_IOS=0
INFO: Found applicable config definition build:v2 in file /home/kevin/Documents/tensorflow/.bazelrc: --define=tf_api_version=2
INFO: Found applicable config definition build:xla in file /home/kevin/Documents/tensorflow/.tf_configure.bazelrc: --define with_xla_support=true
INFO: Found applicable config definition build:tensorrt in file /home/kevin/Documents/tensorflow/.bazelrc: --action_env TF_NEED_TENSORRT=1
INFO: Found applicable config definition build:cuda in file /home/kevin/Documents/tensorflow/.bazelrc: --config=using_cuda --define=using_cuda_nvcc=true
INFO: Found applicable config definition build:using_cuda in file /home/kevin/Documents/tensorflow/.bazelrc: --define=using_cuda=true --action_env TF_NEED_CUDA=1 --crosstool_top=@local_config_cuda//crosstool:toolchain
INFO: Found applicable config definition build:v2 in file /home/kevin/Documents/tensorflow/.bazelrc: --define=tf_api_version=2
DEBUG: /home/kevin/.cache/bazel/_bazel_kevin/7795dc8f03c6c042206d41951ce00a84/external/bazel_tools/tools/cpp/lib_cc_configure.bzl:115:5: 
Auto-Configuration Warning: 'TMP' environment variable is not set, using 'C:\Windows\Temp' as default
WARNING: /home/kevin/Documents/tensorflow/tensorflow/core/BUILD:2441:12: in srcs attribute of cc_library rule //tensorflow/core:lib_internal: please do not import '//tensorflow/core/platform:abi.h' directly. You should either move the file to this package or depend on an appropriate rule there
WARNING: /home/kevin/Documents/tensorflow/tensorflow/core/BUILD:2441:12: in srcs attribute of cc_library rule //tensorflow/core:lib_internal: please do not import '//tensorflow/core/platform:annotation.h' directly. You should either move the file to this package or depend on an appropriate rule there
... this warning continues a lot of times

ERROR: /home/kevin/.cache/bazel/_bazel_kevin/7795dc8f03c6c042206d41951ce00a84/external/local_config_tensorrt/BUILD:43:1: Executing genrule @local_config_tensorrt//:tensorrt_include failed (Exit 1): bash failed: error executing command 
  (cd /home/kevin/.cache/bazel/_bazel_kevin/7795dc8f03c6c042206d41951ce00a84/execroot/org_tensorflow && \
  exec env - \
    LD_LIBRARY_PATH=/usr/local/cuda-10.1/lib64 \
    PATH=/usr/local/cuda-10.1/bin:/usr/local/cuda-10.1/NsightCompute-2019.1:/home/kevin/bin:/home/kevin/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin \
  /bin/bash -c 'source external/bazel_tools/tools/genrule/genrule-setup.sh; cp -f "/usr/include/x86_64-linux-gnu/NvInfer.h" "bazel-out/host/bin/external/local_config_tensorrt/tensorrt/include/NvInfer.h" && cp -f "/usr/include/x86_64-linux-gnu/NvUtils.h" "bazel-out/host/bin/external/local_config_tensorrt/tensorrt/include/NvUtils.h" && cp -f "/usr/include/x86_64-linux-gnu/NvInferPlugin.h" "bazel-out/host/bin/external/local_config_tensorrt/tensorrt/include/NvInferPlugin.h" && cp -f "/usr/include/x86_64-linux-gnu/NvInferVersion.h" "bazel-out/host/bin/external/local_config_tensorrt/tensorrt/include/NvInferVersion.h" && cp -f "/usr/include/x86_64-linux-gnu/NvInferRTSafe.h" "bazel-out/host/bin/external/local_config_tensorrt/tensorrt/include/NvInferRTSafe.h" && cp -f "/usr/include/x86_64-linux-gnu/NvInferRTExt.h" "bazel-out/host/bin/external/local_config_tensorrt/tensorrt/include/NvInferRTExt.h" && cp -f "/usr/include/x86_64-linux-gnu/NvInferPluginUtils.h" "bazel-out/host/bin/external/local_config_tensorrt/tensorrt/include/NvInferPluginUtils.h" ')
Execution platform: @bazel_tools//platforms:host_platform
cp: cannot stat '/usr/include/x86_64-linux-gnu/NvInferRTSafe.h': No such file or directory
Target //tensorflow/tools/pip_package:build_pip_package failed to build

**Comment by oanush** [comment]
@Kevin-Delnoije ,
Thank you for reporting the issue ,Can you provide `./Config `output ?Thanks!

**Comment by goldiegadde** [comment]
@aaroey I believe this issue is fixed by https://github.com/tensorflow/tensorflow/commit/6ce88bc983a98120c080a6a7a8b87d4e3416ea03

If so can we mark this as fixed please.

**Comment by aaroey** [comment]
@pooyadavoodi could you please help to confirm if #32823 fixed the problem?

**Comment by pooyadavoodi** [comment]
Yes, the error `cp: cannot stat '/usr/include/x86_64-linux-gnu/NvInferRTSafe.h': No such file or directory` is fixed by https://github.com/tensorflow/tensorflow/commit/6ce88bc983a98120c080a6a7a8b87d4e3416ea03

**Comment by aaroey** [comment]
Thanks Pooya, I'm closing this. Feel free to reopen if necessary.
