### ISSUE TITLE
"Upgrading your code to TensorFlow 2.0" is behind a Medium paywall

### ISSUE THREAD

**Issue by jayschwa** [tensorflow/tensorflow#32926]
## URL(s) with the issue:

https://medium.com/tensorflow/upgrading-your-code-to-tensorflow-2-0-f72c3a4d83b5

## Description of issue (what needs changing):

This upgrade guide is linked from the TensorFlow 2.0 release notes. If the viewer has exceeded their quota on Medium, they are blocked by a paywall and cannot read the upgrade guide. Is this intentional?

![image](https://user-images.githubusercontent.com/475017/65907458-68883c80-e392-11e9-82d0-edf8ad7efbe0.png)

**Comment by ravikyram** [comment]
@jayschwa 
Did you get a chance to go through Tensorflow official website.
https://www.tensorflow.org/guide/upgrade

**Comment by jayschwa** [comment]
I suggest updating the release notes to link to https://www.tensorflow.org/guide/upgrade instead of the Medium post.

**Comment by MarkDaoust** [comment]
Yes we're working on moving the blog because of this sort of thing.

If you think this change is important you can send a PR to update: https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md

**Comment by random-forests** [comment]
Ugh, sorry to see that. There's a switch I think we can flip on articles to prevent it - perhaps we missed it. Will take a look.

**Comment by random-forests** [comment]
Should be fixed now, thanks again for flagging!
