### ISSUE TITLE
morphological layer

### ISSUE THREAD

**Issue by mevalle** [tensorflow/tensorflow#32928]
How can I implement efficiently a layer of morphological neurons (see the papers DOI: [10.1109/ICPR.1996.547657](https://doi.org/10.1109/ICPR.1996.547657) or DOI: [10.1109/TNN.2003.809427](https://doi.org/10.1109/TNN.2003.809427)) in tensorflow? Morphological neurons are obtained by replacing the product by the sum and the sum by either the maximum or the minimum operations. In its simplest form, the morphological neurons are given by

![image](https://user-images.githubusercontent.com/51181168/65959161-abe0ba80-e427-11e9-93f7-f7d72756a0bd.png)  or ![image](https://user-images.githubusercontent.com/51181168/65959172-b307c880-e427-11e9-9d8e-651cecbe87dc.png) , for all i=1,...,m,

where  is the synaptic weight, x =  is the input vector and  is the output. The mathematical background for morphological neurons is lattice theory, which also the mathematical background for fuzzy sets and mathematical morphology - a theory widely used for image processing and analysis.

**Comment by gowthamkpr** [comment]
Closing this issue due to the lack of context. Please create an other issue with full details as shown by the following [template](https://github.com/tensorflow/tensorflow/issues/new/choose).

**Comment by gadagashwini** [comment]
@mevalle, Please provide the information asked in the [template](https://github.com/tensorflow/tensorflow/issues/new/choose). Thanks!

**Comment by mevalle** [comment]
How can I implement efficiently a layer of morphological neurons (see the papers DOI: 10.1109/ICPR.1996.547657 or DOI: 10.1109/TNN.2003.809427) in tensorflow? Morphological neurons are obtained by replacing the product by the sum and the sum by either the maximum or the minimum operations. In its simplest form, the morphological neurons are given by

image
![image](https://user-images.githubusercontent.com/51181168/65959322-0712ad00-e428-11e9-99cf-e3b672f74b15.png)  or ![image](https://user-images.githubusercontent.com/51181168/65959301-fe21db80-e427-11e9-8599-8e5d782130c2.png), for all i=1,...,m,

where is the synaptic weight, x = is the input vector and is the output. The mathematical background for morphological neurons is lattice theory, which also the mathematical background for fuzzy sets and mathematical morphology - a theory widely used for image processing and analysis.

**Comment by gowthamkpr** [comment]
@mevalle I am not sure on how to implement morphological layer but you can go through this [link](https://www.tensorflow.org/tutorials/customization/custom_layers) on how you can write your own custom layer and try to implement it by yourself.

**Comment by mevalle** [comment]
Thank you very much for the link. I shall try to implement it!

**Comment by gowthamkpr** [comment]
@mevalle I am going to close this issue as of now. But feel free to  add additional comments and we can reopen the issue again
