### ISSUE TITLE
BatchMatMul for TFLite

### ISSUE THREAD

**Issue by TimCapes** [tensorflow/tensorflow#32932]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using):tf2.0.0-rc1
- Are you willing to contribute it (Yes/No):No

**Describe the feature and the current behavior/state.**
Currently tf.matmul hides batch matmuls in code and this means seemingly benign operations (tf.matmul is listed as supported) will cause a model to not be convertable to TFLite without using TF_SELECT_OPS and compiling a custom interpreter.
**Will this change the current api? How?** No

**Who will benefit with this feature?** All users who wish to convert models to TFLite models and use matmul for batch multiplication.

**Any Other info.**

**Comment by TianHongZXY** [comment]
Is this problem solved?

**Comment by TimCapes** [comment]
This is fixed. Thanks.

**Comment by rmothukuru** [comment]
@TimCapes,
Sorry for the delayed response. As per [this comment](https://github.com/tensorflow/tensorflow/issues/42937#issuecomment-686795072), 

> BatchMatMul can be supported via Select TF ops and we offer a selective build mechanism for Select TF ops for slim binary size deployment.

Can you please take a look? Thanks!
