### ISSUE TITLE
Documentation for streaming training data from disk.

### ISSUE THREAD

**Issue by invencode** [tensorflow/tensorflow#32938]
I think we need more detailed description and example for streaming training data from disk on
https://www.tensorflow.org/guide/data#basic_mechanics.

It is mentioned on other documents, but no how-tos. It would be helpful if we add how to implement streaming data from disk and improvements on TF2.0, if any.

> When iterating over training data that fits in memory, feel free to use regular Python iteration. Otherwise, tf.data.Dataset is the best way to stream training data from disk. https://www.tensorflow.org/guide/effective_tf2

> For large datasets (> 1 GB), this can waste memory and run into byte limits of graph serialization. If tensors contains one or more large NumPy arrays, consider the alternative described in this guide.
https://www.tensorflow.org/api_docs/python/tf/data/Dataset#from_tensor_slices
** The link to "this guide" is broken.

> The tf.data API supports a variety of file formats so that you can process large datasets that do not fit in memory. For example, the TFRecord file format is a simple record-oriented binary format that many TensorFlow applications use for training data. The tf.data.TFRecordDataset class enables you to stream over the contents of one or more TFRecord files as part of an input pipeline.
https://www.tensorflow.org/guide/data#consuming_tfrecord_data

Also, it would be helpful if we make it clear...
- If the tf.data.TFRecordDataset is the only class that supports streaming.
- If the TFRecord is the only file format that supports streaming.
- If the user needs to convert their dataset to TFRecord format.
- If the trained model can be used with TFLite. 
- etc...

**Comment by summa-code** [comment]
I have no idea how to do, There is no documentation.

**Comment by summa-code** [comment]
Is this thread dead ?

**Comment by Saduf2019** [comment]
@invencode 
Is this still an issue.
