### ISSUE TITLE
Error converting .pb model to .tflite

### ISSUE THREAD

**Issue by mohitranawat** [tensorflow/tensorflow#32946]
System information
- OS Platform and Distribution : Windows 10 64-bit
- TensorFlow installed from (source or binary): Binary
-TensorFlow Version - 1.13.1
-Onnx Version - 1.6.0

I have pytorch model and I have to deploy it into android, so I saved the model in onnx and then converted the model in .pb
But not able to convert the model in tensorflowlite.

` import tensorflow as tf

graph_def_file = "tensorf.pb"
input_arrays = ['Const']
output_arrays = ['concat_98']

converter = tf.lite.TFLiteConverter.from_frozen_graph(graph_def_file, input_arrays, output_arrays)
tflite_model = converter.convert()
open("tensorf_lite.tflite", "wb").write(tflite_model) `

Error log -

`Traceback (most recent call last): File "tfliteconvertor.py", line 8, in <module> tflite_model = converter.convert() File "C:\Program Files\Python37\lib\site-packages\tensorflow\lite\python\lite.py", line 455, in convert **converter_kwargs) File "C:\Program Files\Python37\lib\site-packages\tensorflow\lite\python\convert.py", line 442, in toco_convert_impl input_data.SerializeToString()) File "C:\Program Files\Python37\lib\site-packages\tensorflow\lite\python\convert.py", line 205, in toco_convert_protos "TOCO failed. See console for info.\n%s\n%s\n" % (stdout, stderr)) tensorflow.lite.python.convert.ConverterError: TOCO failed. See console for info. 2019-10-01 12:18:57.243087: I tensorflow/lite/toco/import_tensorflow.cc:1324] Converting unsupported operation: PyFunc 2019-10-01 12:18:57.243738: E tensorflow/core/framework/op_kernel.cc:1325] OpKernel ('op: "WrapDatasetVariant" device_type: "CPU"') for unknown op: WrapDatasetVariant 2019-10-01 12:18:57.244227: E tensorflow/core/framework/op_kernel.cc:1325] OpKernel ('op: "WrapDatasetVariant" device_type: "GPU" host_memory_arg: "input_handle" host_memory_arg: "output_handle"') for unknown op: WrapDatasetVariant 2019-10-01 12:18:57.244653: E tensorflow/core/framework/op_kernel.cc:1325] OpKernel ('op: "UnwrapDatasetVariant" device_type: "CPU"') for unknown op: UnwrapDatasetVariant 2019-10-01 12:18:57.245022: E tensorflow/core/framework/op_kernel.cc:1325] OpKernel ('op: "UnwrapDatasetVariant" device_type: "GPU" host_memory_arg: "input_handle" host_memory_arg: "output_handle"') for unknown op: UnwrapDatasetVariant 2019-10-01 12:18:57.245590: F tensorflow/lite/toco/import_tensorflow.cc:114] Check failed: attr.value_case() == AttrValue::kType (1 vs. 6)`

**Comment by renato-junior** [comment]
I am facing this same error, in tensorflow 1.14.0.

Converted a Pytorch ResNet-50 model to ONNX, then from ONNX to save graph (.pb). The execution of tf.lite.TFLiteConverter.from_frozen_graph is aborted with the following erros:

`2019-10-02 17:21:46.869078: I tensorflow/lite/toco/import_tensorflow.cc:1336] Converting unsupported operation: PyFunc
2019-10-02 17:21:46.876495: F tensorflow/lite/toco/import_tensorflow.cc:114] Check failed: attr.value_case() == AttrValue::kType (1 vs. 6)`

**Comment by oanush** [comment]
@mohitranawat,
Please refer this [link](https://github.com/tensorflow/tensorflow/issues/24491) of similar issue.Thanks!

**Comment by mohitranawat** [comment]
@oanush  I am not facing this issue. My model is saved in cpu only, nowhere GPU comes into picture.
Hope you can give another solution or suggestion.Thanks!

**Comment by oanush** [comment]
@mohitranawat ,
Did you try using [TFLITE_BUILTINS, SELECT_TF_OPS](https://www.tensorflow.org/lite/guide/ops_select) to convert your model?Thanks!

**Comment by mohitranawat** [comment]
@oanush Tried, not working. Thanks!

**Comment by AbhinavKoul** [comment]
same issue with me on windows 10
the following error pops up :

  File "e:/Projects/Toolkits-for-me-by-me/Convert_Tensorflow_model_to_TfLite/Tflite_converter.py", line 5, in <module>
    tflite_model = converter.convert()
  File "C:\Users\abhin\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\lite\python\lite.py", line 428, in convert
    "invalid shape '{1}'.".format(_get_tensor_name(tensor), shape_list))
**ValueError: None is only supported in the 1st dimension. Tensor 'image_tensor' has invalid shape '[None, None, None, 3]'.**

**Comment by weilaiguang** [comment]
> same issue with me on windows 10
> the following error pops up :
> 
> File "e:/Projects/Toolkits-for-me-by-me/Convert_Tensorflow_model_to_TfLite/Tflite_converter.py", line 5, in
> tflite_model = converter.convert()
> File "C:\Users\abhin\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\lite\python\lite.py", line 428, in convert
> "invalid shape '{1}'.".format(_get_tensor_name(tensor), shape_list))
> **ValueError: None is only supported in the 1st dimension. Tensor 'image_tensor' has invalid shape '[None, None, None, 3]'.**

I have the same problem.I just try to fix the size of the input node before frozen the graph.You can use the Netron to visualize your graph file.

**Comment by uchihaltachi** [comment]
Now I have the same problem. How did you solve it，please

**Comment by weilaiguang** [comment]
> Now I have the same problem. How did you solve it，please

this problem is about the model of faster rcnn.l can not solve it.l think it can not be solved because this version of tensorflow do not support mlir model.

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.
