### ISSUE TITLE
tf2.0 model issue on conv3D with activation relu

### ISSUE THREAD

**Issue by tiru1930** [tensorflow/tensorflow#32948]
== tensorflow installed from info ==================
Name: tensorflow
Version: 2.0.0
Summary: TensorFlow is an open source machine learning framework for everyone.
Home-page: https://www.tensorflow.org/
Author-email: packages@tensorflow.org
License: Apache 2.0
Location: /home/tbaggu/Desktop/pose-anomaly-detection/env/lib/python3.6/site-packages
Required-by:
`class C3Dmodel(Model):
  
    def __init__(self):
        super(C3Dmodel, self).__init__()
        self.conv1 = tf.keras.layers.Conv3D(filters=64,kernel_size=3,padding='SAME',activation=tf.keras.layers.ReLU)
        self.conv2 = tf.keras.layers.Conv3D(filters=128,kernel_size=3,padding='SAME',activation=tf.keras.layers.ReLU)
        self.conv3 = tf.keras.layers.Conv3D(filters=256,kernel_size=3,padding='SAME',activation=tf.keras.layers.ReLU)
        self.conv4 = tf.keras.layers.Conv3D(filters=512,kernel_size=3,padding='SAME',activation=tf.keras.layers.ReLU)
        self.pool1 = tf.keras.layers.MaxPool3D(pool_size=(1,2,2),strides=(1,2,2),padding='SAME')
        self.pool2 = tf.keras.layers.MaxPool3D(pool_size=2,strides=2,padding='SAME')
        self.fc1   = tf.keras.layers.Dense(4096,activation=tf.keras.layers.ReLU)
        self.fc2   = tf.keras.layers.Dense(512,activation=tf.keras.layers.ReLU)
        self.fc3   = tf.keras.layers.Dense(32,activation=tf.keras.layers.ReLU)
        self.fc4   = tf.keras.layers.Dense(1)
        self.dropout = tf.keras.layers.Dropout(0.5)
        self.flatten = tf.keras.layers.Flatten()

    def call(self,x):
        x = self.conv1(x)
        x = self.pool1(x)
        x = self.conv2(x)
        x = self.pool2(x)
        x = self.conv3(x)
        x = self.conv3(x)
        x = self.pool2(x)
        x = self.conv4(x)
        x = self.conv4(x)
        x = self.pool2(x)
        x = tf.pad(x, [[0, 0], [1, 1], [1, 1], [1, 1], [0, 0]])
        x = self.conv4(x)
        x = tf.pad(x, [[0, 0], [1, 1], [1, 1], [1, 1], [0, 0]])
        x = self.conv4(x)
        x = self.pool2(x)

        x = self.flatten(x)
        x = self.fc1(x)
        x = self.dropout(x)
        x = self.fc2(x)
        x = self.dropout(x)
        x = self.fc3(x)
        x = self.dropout(x)
        return self.fc4(x)
`

Input shape : (2, 16, 240, 320, 3)

Error:
`Traceback (most recent call last):
  File "train.py", line 45, in <module>
    main()
  File "train.py", line 43, in main
    tN.train()
  File "train.py", line 39, in train
    print(self.model(batch))
  File "#HOME/env/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/base_layer.py", line 891, in __call__
    outputs = self.call(cast_inputs, *args, **kwargs)
  File "#HOME/src/model.py", line 68, in call
    x = self.conv1(x)
  File "#HOME/env/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/base_layer.py", line 891, in __call__
    outputs = self.call(cast_inputs, *args, **kwargs)
  File "#HOME/env/lib/python3.6/site-packages/tensorflow_core/python/keras/layers/convolutional.py", line 211, in call
    return self.activation(outputs)
  File "#HOME/env/lib/python3.6/site-packages/tensorflow_core/python/keras/layers/advanced_activations.py", line 299, in __init__
    if max_value is not None and max_value < 0.:
  File "#HOME/env/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py", line 876, in __bool__
    return bool(self._numpy())
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()`

**Comment by gowthamkpr** [comment]
@tiru1930 Can you please provide the github gist of this issue inorder to expedite the process. Thanks!

**Comment by tiru1930** [comment]
@gowthamkpr 

code not pushed to git at, here is the complete code file 

`from __future__ import absolute_import, division, print_function, unicode_literals
import tensorflow as tf
from tensorflow.keras import Model
import numpy as np 

class DetectionModel(object):
    
    def __init__(self):
        super(DetectionModel, self).__init__()

    def model(self,inputs,training=True):
        
        net = tf.layers.conv3d(inputs=inputs, filters=64, kernel_size=3, padding='SAME', activation=tf.nn.relu)
        net = tf.layers.max_pooling3d(inputs=net, pool_size=(1, 2, 2), strides=(1, 2, 2), padding='SAME')

        net = tf.layers.conv3d(inputs=net, filters=128, kernel_size=3, padding='SAME', activation=tf.nn.relu)
        net = tf.layers.max_pooling3d(inputs=net, pool_size=2, strides=2, padding='SAME')

        net = tf.layers.conv3d(inputs=net, filters=256, kernel_size=3, padding='SAME', activation=tf.nn.relu)
        net = tf.layers.conv3d(inputs=net, filters=256, kernel_size=3, padding='SAME', activation=tf.nn.relu)
        net = tf.layers.max_pooling3d(inputs=net, pool_size=2, strides=2, padding='SAME')

        net = tf.layers.conv3d(inputs=net, filters=512, kernel_size=3, padding='SAME', activation=tf.nn.relu)
        net = tf.layers.conv3d(inputs=net, filters=512, kernel_size=3, padding='SAME', activation=tf.nn.relu)
        net = tf.layers.max_pooling3d(inputs=net, pool_size=2, strides=2, padding='SAME')
        net = tf.pad(net, [[0, 0], [1, 1], [1, 1], [1, 1], [0, 0]])  

        net = tf.layers.conv3d(inputs=net, filters=512, kernel_size=3, activation=tf.nn.relu, padding='VALID')
        net = tf.pad(net, [[0, 0], [1, 1], [1, 1], [1, 1], [0, 0]])  
        net = tf.layers.conv3d(inputs=net, filters=512, kernel_size=3, activation=tf.nn.relu, padding='VALID')
        net = tf.layers.max_pooling3d(inputs=net, pool_size=2, strides=2, padding='SAME')

        net = tf.layers.flatten(net)
        net = tf.layers.dense(inputs=net, units=4096, activation=tf.nn.relu)
        net = tf.identity(net, name='fc1')
        net = tf.layers.dropout(inputs=net, rate=0.5, training=training)

        net = tf.layers.dense(inputs=net, units=512, activation=tf.nn.relu)
        net = tf.identity(net, name='fc2')
        net = tf.layers.dropout(inputs=net, rate=0.5, training=training)

        net = tf.layers.dense(inputs=net, units=32, activation=tf.nn.relu)
        net = tf.identity(net, name='fc2')
        net = tf.layers.dropout(inputs=net, rate=0.5, training=training)

        net = tf.layers.dense(inputs=net, units=1, activation=None)
        net = tf.identity(net, name='logits')
        return net


class C3Dmodel(Model):
 
    def __init__(self):
        super(C3Dmodel, self).__init__()
        self.conv1 = tf.keras.layers.Conv3D(filters=64,kernel_size=3,padding='SAME',activation=tf.keras.layers.ReLU)
        self.conv2 = tf.keras.layers.Conv3D(filters=128,kernel_size=3,padding='SAME',activation=tf.keras.layers.ReLU)
        self.conv3 = tf.keras.layers.Conv3D(filters=256,kernel_size=3,padding='SAME',activation=tf.keras.layers.ReLU)
        self.conv4 = tf.keras.layers.Conv3D(filters=512,kernel_size=3,padding='SAME',activation=tf.keras.layers.ReLU)
        self.pool1 = tf.keras.layers.MaxPool3D(pool_size=(1,2,2),strides=(1,2,2),padding='SAME')
        self.pool2 = tf.keras.layers.MaxPool3D(pool_size=2,strides=2,padding='SAME')
        self.fc1   = tf.keras.layers.Dense(4096,activation=tf.keras.layers.ReLU)
        self.fc2   = tf.keras.layers.Dense(512,activation=tf.keras.layers.ReLU)
        self.fc3   = tf.keras.layers.Dense(32,activation=tf.keras.layers.ReLU)
        self.fc4   = tf.keras.layers.Dense(1)
        self.dropout = tf.keras.layers.Dropout(0.5)
        self.flatten = tf.keras.layers.Flatten()

    def call(self,x):
        x = self.conv1(x)
        x = self.pool1(x)
        x = self.conv2(x)
        x = self.pool2(x)
        x = self.conv3(x)
        x = self.conv3(x)
        x = self.pool2(x)
        x = self.conv4(x)
        x = self.conv4(x)
        x = self.pool2(x)
        x = tf.pad(x, [[0, 0], [1, 1], [1, 1], [1, 1], [0, 0]])
        x = self.conv4(x)
        x = tf.pad(x, [[0, 0], [1, 1], [1, 1], [1, 1], [0, 0]])
        x = self.conv4(x)
        x = self.pool2(x)

        x = self.flatten(x)
        x = self.fc1(x)
        x = self.dropout(x)
        x = self.fc2(x)
        x = self.dropout(x)
        x = self.fc3(x)
        x = self.dropout(x)
        return self.fc4(x)

def main():
    sample = np.random.rand(1,16,240,320,3)
    print(sample.shape)
    model = C3Dmodel()
    print(model(sample))
    
if __name__ == '__main__':
    main()

`

**Comment by gowthamkpr** [comment]
Was able to reproduce this issue. Heres my [github gist](https://colab.sandbox.google.com/gist/gowthamkpr/4c32d6ba0d3126e73c2e41340a9c2309/untitled187.ipynb).

**Comment by tiru1930** [comment]
Any update on this error?

**Comment by yhliang2018** [comment]
@tiru1930  `tf.keras.layers.ReLU` should be used as Keras layers rather than an activation function in other layers. For activation, you may use either the string `relu` or [`tf.keras.activations.relu`](//www.tensorflow.org/api_docs/python/tf/keras/activations/relu).
