### ISSUE TITLE
TensorFlow 2.0 doesn't detect the GPU when rerunning the same program

### ISSUE THREAD

**Issue by schmidtdominik** [tensorflow/tensorflow#32967]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): /
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: /
- TensorFlow installed from (source or binary): /
- TensorFlow version (use command below): tensorflow-gpu==2.0.0
- Python version: 3.6.8
- Bazel version (if compiling from source): /
- GCC/Compiler version (if compiling from source): /
- CUDA/cuDNN version: 10.0
- GPU model and memory: GeForce RTX 2080 Ti, ~11GB

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
When running a tensorflow program for the first time (in a fresh docker instance) it detects the GPU as expected. When running the same program again (after stopping the previous run) it doesn't detect any GPU devices.
This works as expected in tensorflow-gpu==2.0.0rc1 however.

**Describe the expected behavior**
Tensorflow should always detect all attached GPUs, even on subsequent runs.

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.
```
import tensorflow as tf
(train_images, train_labels), (_, _) = tf.keras.datasets.mnist.load_data()
train_images = train_images.reshape(train_images.shape[0], 28, 28, 1).astype('float32')
train_images = (train_images - 127.5) / 127.5
train_dataset = tf.data.Dataset.from_tensor_slices(train_images).shuffle(100).batch(32)
from tensorflow.python.client import device_lib 
print(device_lib.list_local_devices())
```

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

Devices detected by tensorflow on the first run:
```
[name: "/device:CPU:0"
device_type: "CPU"
memory_limit: 268435456
locality {
}
incarnation: 2693156956587076928
, name: "/device:XLA_CPU:0"
device_type: "XLA_CPU"
memory_limit: 17179869184
locality {
}
incarnation: 7803384591284859902
physical_device_desc: "device: XLA_CPU device"
, name: "/device:XLA_GPU:0"
device_type: "XLA_GPU"
memory_limit: 17179869184
locality {
}
incarnation: 8169967461022885217
physical_device_desc: "device: XLA_GPU device"
, name: "/device:GPU:0"
device_type: "GPU"
memory_limit: 10742700442
locality {
  bus_id: 1
  links {
  }
}
incarnation: 643882925305723598
physical_device_desc: "device: 0, name: GeForce RTX 2080 Ti, pci bus id: 0000:0b:00.0, compute capability: 7.5"
]
```

Devices detected by tensorflow on the second run:
```
[name: "/device:CPU:0"
device_type: "CPU"
memory_limit: 268435456
locality {
}
incarnation: 13203723707335455513
, name: "/device:XLA_CPU:0"
device_type: "XLA_CPU"
memory_limit: 17179869184
locality {
}
incarnation: 6024229839119595332
physical_device_desc: "device: XLA_CPU device"
]
```

**Comment by schmidtdominik** [comment]
Update:
it works as expected when installing `tensorflow-gpu==2.0.0rc1` and also `tensorflow-gpu==2.0.0`. It doesn't work with `tensorflow-gpu` (without the version specification).
This might be related to [this](https://github.com/tensorflow/tensorflow/issues/12388) previous issue where `pip install tensorflow-gpu` installed the tensorflow cpu version as well which messed something up.

**Comment by ravikyram** [comment]
@schmidtdominik  
I tried with installing `!pip install tensorflow-gpu` on colab it works as expected.Please, find the gist [here](https://colab.sandbox.google.com/gist/ravikyram/ba52702209851454ee6b8261772ccb01/untitled239.ipyn).
Can we close this issue since it looks like it is resolved. Please, let us know if i am mistaken. Thanks!

**Comment by schmidtdominik** [comment]
I originally ran it in a Jupyter notebook in a nightly-gpu-py3 docker instance
But now I'm having difficulty to reproduce it so I guess it's resolved, thanks

**Comment by pritamqu** [comment]
> Update:
> it works as expected when installing `tensorflow-gpu==2.0.0rc1` and also `tensorflow-gpu==2.0.0`. It doesn't work with `tensorflow-gpu` (without the version specification).
> This might be related to [this previous issue](https://github.com/tensorflow/tensorflow/issues/12388) where `pip install tensorflow-gpu` installed the tensorflow cpu version as well which messed something up.

Hey man!! you are a lifesaver, I wasted like 2/3 days to figure out this.. then finally your trick worked.. thanks a lot.

**Comment by ihayet** [comment]
> Update:
> it works as expected when installing `tensorflow-gpu==2.0.0rc1` and also `tensorflow-gpu==2.0.0`. It doesn't work with `tensorflow-gpu` (without the version specification).
> This might be related to [this previous issue](https://github.com/tensorflow/tensorflow/issues/12388) where `pip install tensorflow-gpu` installed the tensorflow cpu version as well which messed something up.

Confirmed as working. I've been trying different solutions. But, this one worked. Thank you.

**Comment by BichengWang** [comment]
`pip install tf-nightly-gpu` work for me

**Comment by Ynjxsjmh** [comment]
My confusion is [Install TensorFlow 2](https://www.tensorflow.org/install) says

> TensorFlow 2 packages are available
>
> - `tensorflow` —Latest stable release with CPU and GPU support (Ubuntu and Windows)
> - `tf-nightly` —Preview build (unstable). Ubuntu and Windows include GPU support.
>
> For TensorFlow 1.x, CPU and GPU packages are separate:

According to that, I think `pip install tensorflow` will support GPU. I try to execute the following code provided by [Use a GPU | TensorFlow Core](https://www.tensorflow.org/guide/gpu):

```python
import tensorflow as tf
print("Num GPUs Available: ", len(tf.config.experimental.list_physical_devices('GPU')))
```

It gives me `Num GPUs Available:  0`. Also `tf.test.is_gpu_available()` is False.

Then I try to remove the preciously installed tensorflow by `pip unintall tensorflow` and install gpu version like `pip install tf-nightly-gpu`.

Now the result is `Num GPUs Available:  4`.

Why the doc says `Latest stable release of tensorflow 2 has CPU and GPU support (Ubuntu and Windows)`?
