### ISSUE TITLE
Automatic gradient for numpy functions/external functions

### ISSUE THREAD

**Issue by zhulingchen** [tensorflow/tensorflow#32964]
I am thinking of the following scenarios and want to see if TensorFlow could do Automatic Differentiation for them:

1. There would be a numpy function that accepts numpy array(s) as input(s) and numpy array(s) as output(s);

2. There would be an external executable that accepts numpy array(s) as input(s) and numpy array(s) as output(s).

I know TensorFlow has `tf.numpy_function` (with the v2 context, and equivalently, it was `tf.py_func` in the v1 context) can "convert" a numpy function to a tensor function and inject it into the graph but unfortunately it cannot support Automatic Differentiation; also, `tf.py_function` must accept a tensor function and tensor inputs to inject the function into the graph and fortunately it can support Automatic Differentiation. I cannot think of a way to inject an external executable to be part of the graph and possibly get its differentiation.

If there is no way to achieve scenario 1 and/or 2, is there any workaround?

**Comment by pandrey-fr** [comment]
Hi,

What you are asking would require some kind of AutoGraph for numpy functions, _i.e._ a generic translator of "numpy functions" into tensorflow operations, which would perhaps be possible to implement but would require a lot of effort, and would probably induce some heavy over-head (AutoGraph is already creating some significant overhead on some cases, and it is attached to a set of Python control flows way more limited than the set of numpy operations - and it already represents a massive and honestly quite impressive work).

As a matter of fact, what `tf.numpy_function` does is (benefitting from Eager execution) that it extracts EagerTensors' values as numpy arrays, and then simply runs these arrays through the wrapped function and converts the outputs to Tensors again. So, it just allows pipelining numpy functions in the process, but does not do any code translation into tensorflow operations.

In my humble opinion, your question is interesting in that it touches to common frustrations one may encounter regarding the possibility to re-use existing numpy-based code, but I do not believe it can or will be solved, at least not on the short run (who knows, perhaps there is work on it). The only alternative I can think of to the solution I described would be to add up some automatic differentiation in numpy, and then make it compatible with tensorflow (enabling a cross-framework automatic differentiation), but I would not really bet on that happening (at least not soon, but again I do not have an ominous knowledge of what people might be working on).

The best "workaround" you have it to actually re-implement the numpy-based functions you want to use in tensorflow, which can be tedious for large pieces of code but should be achievable as most numpy operations have a tensorflow equivalent (and AutoGraph could allow to leave some python control flows as-is).

**Comment by rmothukuru** [comment]
@zhulingchen,
Sorry for the delayed response. Can you please refer the Documentation for [Gradients Calculation for Numpy Arrays](https://www.tensorflow.org/guide/tf_numpy#gradients_and_jacobians_tfgradienttape) and let us know if this is what you are looking for? Thanks!
