### ISSUE TITLE
tf.io.gfile.GFile does not work with Python zipfile

### ISSUE THREAD

**Issue by eirism** [tensorflow/tensorflow#32975]
**System information**

-  Have I written custom code: Yes
- OS Platform and Distribution: Linux Ubuntu 18.04
- TensorFlow installed from: binary
- TensorFlow version: v1.14.0-rc1-22-gaf24dc9 1.14.0
- Python version: 3.6

**Describe the current behavior**
`tf.io.gfile.GFile` does not work correctly with the Python built in `zipfile` module. When writing to a ZipFile where `file=GFile()` the resulting ZIP file is corrupt.

**Describe the expected behavior**
ZipFiles written with `file=GFile()` should be not be corrupt and equal to those written with `file=<other_type_fd>`.

**Code to reproduce the issue**

```
import tensorflow as tf
import zipfile
import filecmp


normal_fd = open("normal.zip", "wb")
normal2_fd = open("normal2.zip", "wb")
open("gfile.zip", "w").close()  # "touch" file so that it exists, issue #32090
gfile_fd = tf.io.gfile.GFile("gfile.zip", "w+b")  # need +, issue #32122

for fd in (normal_fd, normal2_fd, gfile_fd):
    with zipfile.ZipFile(file=fd, "w") as zipfd:
        with zipfd.open("test.txt", "w") as fid:
            fid.write("Hello, World!".encode())
    fd.close()

print("Normal zips equal?", filecmp.cmp("normal.zip", "normal2.zip"))
print("GFile zip equal normal?", filecmp.cmp("normal.zip", "gfile.zip"))

```

**Comment by oanush** [comment]
Issue replicating for TF-1.14, kindly fins the khttps://colab.sandbox.google.com/gist/oanush/c9c779a326c8e55b7ad6f50b726774cf/32975.ipynb of colab.Thanks!

**Comment by mihaimaruseac** [comment]
Will handle this after refactoring entailed by tensorflow/community#101

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.
