### ISSUE TITLE
tf.io.gfile.mkdir does not throw exception if path exists

### ISSUE THREAD

**Issue by eirism** [tensorflow/tensorflow#32972]
**System information**

-  Have I written custom code: Yes
- OS Platform and Distribution: Linux Ubuntu 18.04
- TensorFlow installed from: binary
- TensorFlow version: v1.14.0-rc1-22-gaf24dc9 1.14.0
- Python version: 3.6

**Describe the current behavior**
`tf.io.gfile.mkdir()` on Linux does not throw an exception if the path exists. This can cause problems if the path is a file, as you would assume that the path is a directory after calling `mkdir()`. See the code below for an example.

**Describe the expected behavior**
`mkdir()` should throw an exception if the path exists, like the Python built in [`os.mkdir()`](https://docs.python.org/3/library/os.html#os.mkdir) does.

**Code to reproduce the issue**

```
import tensorflow as tf

test_path = "test"

# Create a file at <test_path>
with open(test_path, "w") as f:
    f.write("Hello, World!")

# No error when creating dir
tf.io.gfile.mkdir(test_path)
with tf.io.gfile.GFile(test_path + "/test_file.txt", "w") as f:
    # .write throws exception since the <test_path> directory does not exist
    f.write("Hello")
```

**Comment by oanush** [comment]
Issue replicating for TF-1.14, kindly find the [gist](https://colab.sandbox.google.com/gist/oanush/3d836d2cc2a89f8618022f9095d42363/32972.ipynb) of colab.Thanks!

**Comment by mihaimaruseac** [comment]
This is a bug in C++ filesystem support too. I will fix this after https://github.com/tensorflow/community/pull/101

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.
