### ISSUE TITLE
java.nio.BufferOverflowException TensorFlowYoloDetector

### ISSUE THREAD

**Issue by mkulisic** [tensorflow/tensorflow#32970]
Hello, 
I am using Yolov2-tiny to detect a single class a running this on this example app. Because I only need a single class, I have been experimenting by reducing layers on yolov2-tiny and the filter sizes.  After a second reduction of the model, I have ran into the error "java.nio.BufferOverflowException". 

**Full Error**
E/AndroidRuntime: FATAL EXCEPTION: inference
    Process: org.tensorflow.demo, PID: 32033
    java.nio.BufferOverflowException
        at java.nio.HeapFloatBuffer.put(HeapFloatBuffer.java:180)
        at org.tensorflow.Tensor.writeTo(Tensor.java:488)
        at org.tensorflow.contrib.android.TensorFlowInferenceInterface.fetch(TensorFlowInferenceInterface.java:488)
        at org.tensorflow.contrib.android.TensorFlowInferenceInterface.fetch(TensorFlowInferenceInterface.java:442)
        at org.tensorflow.demo.TensorFlowYoloDetector.recognizeImage(TensorFlowYoloDetector.java:168)
        at org.tensorflow.demo.DetectorActivity$3.run(DetectorActivity.java:330)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:214)
        at android.os.HandlerThread.run(HandlerThread.java:65)
I/Process: Sending signal. PID: 32033 SIG: 9

**Here is my setup** 

- **Hardware**: Samsung S8
- **System**: Windows
-**Models**: Trained inside Linux VM and converted to .pb file using darknet.
- **Preview Size**: Changed from 640x480 to 1920x1080

**Models**

- **Trial 1**
     - **Model**: Yolov2-tiny (no modifications)
     - **Model size**: 43MB
     -**Inference Time**: ~600ms
     -**Status**: Works with no issues

- **Trial 2**
     - **Model**: Yolov2-tiny (Removed a convolutional layer and scaled down filters)
     - **Model size**: 10MB
     -**Inference Time**: ~400ms
     -**Status**: Works with no issues

- **Trial 3**
     - **Model**: Yolov2-tiny (removed 2 convolutional layers and scaled down filters)
     - **Model size**: 2.7MB
     -**Inference Time**: None
     -**Status**: Throws the exception status above
     -**Note**: This version works if I lower the parameter YOLO_BLOCK_SIZE in 
                      DetectorActivitty.java from 32 to 16. The problem with this is that it gives me an 
                      inference time of 600MS and that negates the purpose of scaling down the model

All three of these model work well when used with darknet and were converted using darkflow in the exact same environment and commands. 

As mentioned by  @UsamaIslam in #12649 , he fixed this issue by changing the MAX_RESULTS parameter when using fast rcnn with this example app. I tried doing the same, but it didn't work. I don't fully understand this exception so I need help understanding why this fails with **Trial 3** and not the other two trials. 

I would appreciate any suggestions on how I could make this work.

**Comment by jdduke** [comment]
Is there a reason you cannot use TensorFlow Lite? See also https://blog.francium.tech/real-time-object-detection-on-mobile-with-flutter-tensorflow-lite-and-yolo-android-part-a0042c9b62c6. Note that the TensorFlow Mobile library/bindings are deprecated.

**Comment by mkulisic** [comment]
@jdduke I originally tried to use TF LIte. I tried to build the sample application in https://blog.francium.tech/real-time-object-detection-on-mobile-with-flutter-tensorflow-lite-and-yolo-android-part-a0042c9b62c6 a couple of times, but I could not make it work. Ran into multiple issues when using flutter and I found no solution for the problems online. I used a different flutter example with TF Lite and yolo2, but this one did not feature detection on a video feed. Because I need to make progress on other parts of the project I didn't have time to figure out how to figure out how to add this.

If you could refer me to a project that implements yolo2-tiny in TF Lite with real time detection that would be a best case scenario.

**Comment by jdduke** [comment]
I see. In theory you should be able to swap out your use of `TensorFlowInferenceInterface` with the standard TensorFlow Lite `Interpreter`, assuming you have the .tflite model available. Can you provide a link to the .tflite model you tried using? Note that we're also working on YoloV3 compat (see https://github.com/YunYang1994/tensorflow-yolov3/pull/312).

**Comment by mkulisic** [comment]
Hello @jdduke, 
I will try changing the the app to use TF lite interpreter. I'll give an update once I do. 

Thank you,
Miguel

**Comment by renjie-liu** [comment]
Tei has made Yolo-v3 work. 

Hi Miguel, is it possible to attach the problematic model for us to debug? thanks

**Comment by Saduf2019** [comment]
@mkulisic 
Is this still an issue.

**Comment by mkulisic** [comment]
@Saduf2019 I eventually managed to solve the problem.

**Comment by Saduf2019** [comment]
@mkulisic 
Please move this to closed status if resolved.
