### ISSUE TITLE
The simple model converted by TFLiteConverter not accelerates by Coral USB Accelerator

### ISSUE THREAD

**Issue by mirth** [tensorflow/tensorflow#32988]
**Code to reproduce the issue**
Code to convert the model on Macbook Pro:

```
import tensorflow as tf

inputs = tf.keras.Input(shape=(256, 256, 3), name='model_input')
outputs = tf.keras.layers.Conv2D(filters=32, kernel_size=3)(inputs)
model = tf.keras.Model(inputs, outputs)
converter = tf.lite.TFLiteConverter.from_keras_model(model)

tflite_model = converter.convert()
open("test_model_tf2.0_by_from_keras_model.tflite", "wb+").write(tflite_model)
```

Code to inference the model on Raspberry Pi:
```
import tqdm

def tensorflow_lite():
    from tflite_runtime.interpreter import Interpreter
    from tflite_runtime.interpreter import load_delegate

    import numpy as np

    interpreter = Interpreter(
            'test_model_tf2.0_by_from_keras_model.tflite',
            experimental_delegates=[load_delegate('libedgetpu.so.1.0')], #with or without it
        )
    interpreter.allocate_tensors()
   
    input_details = interpreter.get_input_details()
    output_details = interpreter.get_output_details()

    _, height, width, _ = interpreter.get_input_details()[0]['shape']

    for _ in tqdm.tqdm(range(100000)):
        image = np.zeros((1, 256, 256, 3,), dtype=np.float32)
        set_input_tensor(interpreter, image)
        interpreter.invoke()
        output = np.squeeze(interpreter.get_tensor(output_details[0]['index']))

def main():
    tensorflow_lite()
if __name__ == '__main__':
    main()
```

**System information**
About machine that model had been converted on:
- Macbook Pro Mid 2014, macOS Mojave 10.14.6
- TensorFlow installed by `sudo pip install -U tensorflow`
- TensorFlow version: v2.0.0-rc2-26-g64c3d382ca 2.0.0

About machine that tflite model had been run on:
- `Raspberry Pi 3B` + `Coral USB Accelerator`
```
$ cat /etc/debian_version
10.1

$ cat /etc/os-release
PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
...

$ uname -a
Linux raspberrypi 4.19.75-v7+ #1270 SMP Tue Sep 24 18:45:11 BST 2019 armv7l GNU/Linux
```

To set up Coral USB Accelerator i was guided by [https://coral.withgoogle.com/docs/accelerator/get-started/](url) with `libedgetpu1-std` variant.
Tflite had been installed by:
`pip3 install tflite_runtime-1.14.0-cp37-cp37m-linux_armv7l.whl`

**Current behavior**
The inference code on `Raspberry Pi 3B` + `Coral USB Accelerator` shows  ~12it/s and **no white led signaling on `Coral USB Accelerator` observed.**

**Expected behavior**
I expect at least x5-10 it/s from what i observe now. Also i expect the led signaling on inference because that is what i'm observing while running the `tflite/python/examples/classify_image.py` example.

Also here is my text output for `classify_image.py` example:
```
$ python3 classify_image.py --model models/mobilenet_v2_1.0_224_inat_bird_quant_edgetpu.tflite --labels models/inat_bird_labels.txt --image images/parrot.jpg

Initializing TF Lite interpreter...
INFO: Initialized TensorFlow Lite runtime.
----INFERENCE TIME----
Note: The first inference on Edge TPU is slow because it includes loading the model into Edge TPU memory.
120.6ms
13.5ms
13.5ms
13.8ms
13.6ms
-------RESULTS--------
923 Ara macao (Scarlet Macaw): 0.76562
```

I also tried to convert the model with tf-14.0.0 (on MacOS) and got the same result.

**Comment by freedomtan** [comment]
@mirth did you [compile](https://coral.withgoogle.com/docs/edgetpu/compiler/) your tflite models into Edge TPU enabled tflite models.

**Comment by mirth** [comment]
@freedomtan i didn't. i think it explains everything
