### ISSUE TITLE
BoostedTreesClassifier double free or corruption (!prev)

### ISSUE THREAD

**Issue by sockfish** [tensorflow/tensorflow#32983]
I am running the BoostedTreesClassifier tutorial (https://www.tensorflow.org/tutorials/estimator/boosted_trees) on tf2.0 

During the training call:

> # Train model.
> linear_est.train(train_input_fn, max_steps=100)
> 

a "double free or corruption (!prev)" is logged and the python process crashes

TF 2.0.0 (pip installed)
Ubuntu 19.04
python 3.7
cuda 10.0.130
GPU: RTX 2080 Ti

Other tensorflow components (ie keras) work fine

**Comment by gowthamkpr** [comment]
I am unable to reproduce the above error in colab. The github gist is [here](https://colab.sandbox.google.com/gist/gowthamkpr/e795c91a7fdaa9c7766c5a9381da474e/copy-of-boosted_trees.ipynb). 

But I think this is a duplicate of this [issue](https://github.com/tensorflow/tensorflow/issues/6968). Go through the issue and it should help you in resolving it.

**Comment by sockfish** [comment]
The malloc trick did not work for me:
```
sudo apt-get install libtcmalloc-minimal4
export LD_PRELOAD="/usr/lib/libtcmalloc_minimal.so.4"
```
And neither did the numpy trick:
```
pip3 install --user --no-binary=:all: --force-reinstall numpy
```

**Comment by gowthamkpr** [comment]
@sockfish As mentioned in this comment [here](https://github.com/tensorflow/tensorflow/issues/7268#issuecomment-278130615) this is unlikely a Tensorflow issue. For more details, you can refer to the issue [here](https://github.com/tensorflow/tensorflow/issues/7268).

**Comment by wayne003** [comment]
I got same error

Docker container: 2.0.0-gpu-py3-jupyter
GPU: Nvidia GeForce GTX 1660 Ti
Driver: 418.87.00_linux
Host: Ubuntu 18.04 LTS
