### ISSUE TITLE
Frequent dynamic memory allocation in tensorflow/core/kernels/conv_ops.cc?

### ISSUE THREAD

**Issue by changyun79** [tensorflow/tensorflow#3299]
I am looking at the code in tensorflow/core/kernels/conv_ops.cc, Compute(OpKernelContext* context)  function:
`
  // Output tensor is of the following dimensions:                          
  // [ in_batch, out_rows, out_cols, out_depth ]                            
  Tensor* output = nullptr;                                                 
  OP_REQUIRES_OK(context, context->allocate_output(0, out_shape, &output)); 
`
Does it mean each CONV OP will always dynamic allocate output tensor (including the buffer as the size of in_batch x out_rows x out_cols x out_depth) even if I load the graph once but iterate multiple times to inference multiple images? Where the memory was freed? 

Thanks.

**Comment by zheng-xq** [comment]
Yes. All tensors in TensorFlow are refcounted, dynamically allocated and freed. On GPU, this goes through its own non-blocking BFC memory allocator. All the tensors are freed when their refcount goes to zero. For temporary tensors, that is often when "Compute" finishes. For output tensors, that is when they finish being used as input tensors.

**Comment by changyun79** [comment]
Thanks, @zheng-xq . Any theory behind this design? To me, make memory static is important for both performance and memory fragmentation. I am basically looking to optimize the inference time and wondering whether it is doable on top of tensorflow. Thanks.

**Comment by zheng-xq** [comment]
For CPU, the allocation/free overhead is not an issue because we use tcmalloc internally. 

http://goog-perftools.sourceforge.net/doc/tcmalloc.html

There is a discussion on whether we should enable tcmalloc by default for the open-source build. Meanwhile, feel free to try tcmalloc yourself and it should improve things a lot.

**Comment by changyun79** [comment]
Thanks for the quick response, @zheng-xq I can close this ticket and will play with tcmalloc then.

**Comment by Joeyzhouqihui** [comment]
Hi, sorry for bothering. I have a question that when using dynamic memory allocation with multiple streams, are those memory blocks shared across different streams? Or each stream has its own memory pool?
