### ISSUE TITLE
tf.linalg.inv() on GPU

### ISSUE THREAD

**Issue by minaskar** [tensorflow/tensorflow#32996]
Hi all,

It seems that running tf.linalg.inv() on a GPU has no difference in terms of speed with respect to the CPU.

Is there a way to use GPU acceleration to compute the matrix inverse faster?

Cheers,

**Comment by oanush** [comment]
@minaskar ,
Can you please provide a sample code ? Thanks!

**Comment by minaskar** [comment]
I'm using the following code as a benchmark:
```
import numpy as np
import tensorflow as tf

def Covariance(ndim):
  
  a = 2.0
  A = np.array([np.random.randn(ndim) + np.random.randn(1)*a for i in range(ndim)])
  A = np.dot(A,np.transpose(A))
  D_half = np.diag(np.diag(A)**(-0.5))
  return np.dot(np.dot(D_half,A),D_half).astype('float32')

C = Covariance(10000)

%timeit tf.linalg.inv(C)
```

It seems that setting the dtype of the input matrix to `float32` did the trick.
So now, GPU performs better than the CPU. However, both GPU and CPU seem to perform better than a TPU.

I'm using tensorflow 2.0.

**Comment by oanush** [comment]
@minaskar ,
Please find the result when tried from our end performance in GPU TPU and CPU in the [gist](https://colab.sandbox.google.com/gist/oanush/ab9ebcc4becb2d720951b4aee2a129b7/32996.ipynb) of colab attached. 


> I'm using the following code as a benchmark:
> 
> ```
> import numpy as np
> import tensorflow as tf
> 
> def Covariance(ndim):
>   
>   a = 2.0
>   A = np.array([np.random.randn(ndim) + np.random.randn(1)*a for i in range(ndim)])
>   A = np.dot(A,np.transpose(A))
>   D_half = np.diag(np.diag(A)**(-0.5))
>   return np.dot(np.dot(D_half,A),D_half).astype('float32')
> 
> C = Covariance(10000)
> 
> %timeit tf.linalg.inv(C)
> ```
> 
> It seems that setting the dtype of the input matrix to `float32` did the trick.
> So now, GPU performs better than the CPU. However, both GPU and CPU seem to perform better than a TPU.
> 
> I'm using tensorflow 2.0.
let us know if the issue resolved using `Flaot32`?
Thanks!

**Comment by oanush** [comment]
@minaskar ,
Please let us know if there is any update on the issue ? Thanks!

**Comment by oanush** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
