### ISSUE TITLE
Run sample of experts is not work on local

### ISSUE THREAD

**Issue by yangzhuoran** [tensorflow/tensorflow#32993]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:no
- TensorFlow installed from (source or binary):pip install tensorflow-gpu
- TensorFlow version:2.0.0
- Python version:Python 3.6.8
- Installed using virtualenv? pip? conda?: pip
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:V10.0.130
- GPU model and memory:GTX1080TI

**Describe the problem**
I can obtain the TensorFlow version with
python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)" . But when running sample of experts, is not work on local. ModuleNotFoundError: No module named 'tensorflow.keras'; 'tensorflow' is not a package
source file is following:
```
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function
from __future__ import unicode_literals

import tensorflow as tf

from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Conv2D
from tensorflow.keras.layers import Flatten
from tensorflow.keras import Model

mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

x_train = x_train[..., tf.newaxis]
x_test = x_test[..., tf.newaxis]

train_ds = tf.data.Dataset.from_tensor_slices(
  (x_train, y_train)).shuffle(10000).batch(32)
test_ds = tf.data.Dataset.from_tensor_slices(
  (x_test, y_test)).batch(32)


class MyModel(Model):
  def __init__(self):
    super(MyModel, self).__init__()
    self.conv1 = Conv2D(32, 3, activation='relu')
    self.flatten = Flatten()
    self.d1 = Dense(128, activation='relu')
    self.d2 = Dense(10, activation='softmax')

  def call(self, x):
    x = self.conv1(x)
    x = self.flatten(x)
    x = self.d1(x)
    return self.d2(x)


model = MyModel()

loss_object = tf.keras.losses.SparseCategoricalCrossentropy()
optimizer = tf.keras.optimizers.Adam()

train_loss = tf.keras.metrics.Mean(name='train_loss')
train_accuracy = tf.keras.metrics.SparseCategoricalCrossentropy()

test_loss = tf.keras.metrics.Mean(name='test_loss')
test_accuracy = tf.keras.metrics.SparseCategoricalCrossentropy(name='test_accuracy')


@tf.function
def train_step(images, labels):
  with tf.GradientTape() as tape:
    predications = model(images)
    loss = loss_object(labels, predications)
  gradients = tape.gradient(loss, model.trainable_variables)
  optimizer.apply_gradients(zip(gradients, model.trainable_variables))

  train_loss(loss)
  train_accuracy(labels, predications)


@tf.function
def test_step(images, labels):
  predictions = model(images)
  t_loss = loss_object(labels, predictions)

  test_loss(t_loss)
  test_accuracy(labels, predictions)


EPOCHS = 5


for epoch in range(EPOCHS):
    for images, labels in train_ds:
      train_step(images, labels)

    for test_images, test_labels in test_ds:
      test_step(test_images, test_labels)

    template = 'Epoch: {}, Loss: {}, Accuracy: {}, Test Loss: {}, Test Accuracy: {}'
    print (template.format(epoch+1,
                           train_loss.result(),
                           train_accuracy.result()*100,
                           test_loss.result(),
                           test_accuracy.result()*100))

```

**Provide the exact sequence of commands / steps that you executed before running into the problem**
python tensorflow.py (tensorflow.py is source code file)

**Comment by gowthamkpr** [comment]
Tried to reproduce it on google colab but I don't face any error. Heres the [gist](https://colab.sandbox.google.com/gist/gowthamkpr/60b42fb040fd50cb8652a1b11264fc70/untitled159.ipynb). Looks like the issue is that tensorflow is not installed well. 

I cannot really find the rot cause of this issue but you can take a look at this [issue](https://github.com/tensorflow/tensorflow/issues/6548) and let me know if you can figure out. Thanks!

**Comment by gowthamkpr** [comment]
@yangzhuoran Were you able to solve the issue?

**Comment by yangzhuoran** [comment]
> @yangzhuoran Were you able to solve the issue?

when I run it on jupyter notebook , I don't face any error. But when I run it in local file by command 'python sourcefile.py', I face this error. I don't understand what happened. I think reinstall tensorflow in local compute.

**Comment by gowthamkpr** [comment]
Please install all the dependencies in the fresh environment and it should work. Let me know if you are still facing the same issue?

**Comment by gowthamkpr** [comment]
@yangzhuoran Are you still facing the issue?

**Comment by yangzhuoran** [comment]
Yes, But I can find .pyc file in __pycache__ folder. I can run .pyc using python command. I’m thinking the reason of this situation.

**Comment by gowthamkpr** [comment]
@yangzhuoran Can I see your` pip list`

**Comment by yangzhuoran** [comment]
My pip list as follows:
Package               Version            
--------------------- -------------------
absl-py               0.8.0              
apturl                0.5.2              
asn1crypto            0.24.0             
astor                 0.8.0              
bleach                2.1.2              
Brlapi                0.6.6              
certifi               2018.1.18          
chardet               3.0.4              
chrome-gnome-shell    0.0.0              
command-not-found     0.3                
cryptography          2.1.4              
cupshelpers           1.0                
cycler                0.10.0             
decorator             4.1.2              
defer                 1.0.6              
distro-info           0.18ubuntu0.18.04.1
entrypoints           0.2.3.post1        
gast                  0.2.2              
google-pasta          0.1.7              
grpcio                1.24.0             
h5py                  2.10.0             
html5lib              0.999999999        
httplib2              0.9.2              
idna                  2.6                
ipykernel             4.8.2              
ipython               5.5.0              
ipython-genutils      0.2.0              
ipywidgets            6.0.0              
Jinja2                2.10               
jsonschema            2.6.0              
jupyter-client        5.2.2              
jupyter-console       5.2.0              
jupyter-core          4.4.0              
Keras-Applications    1.0.8              
Keras-Preprocessing   1.1.0              
keyring               10.6.0             
keyrings.alt          3.0                
kiwisolver            1.1.0              
language-selector     0.1                
launchpadlib          1.10.6             
lazr.restfulclient    0.13.5             
lazr.uri              1.0.3              
linecache2            1.0.0              
louis                 3.5.0              
macaroonbakery        1.1.3              
Mako                  1.0.7              
Markdown              3.1.1              
MarkupSafe            1.0                
matplotlib            3.1.1              
mistune               0.8.3              
nbconvert             5.3.1              
nbformat              4.4.0              
notebook              5.2.2              
numpy                 1.17.2             
oauth                 1.0.1              
olefile               0.45.1             
opt-einsum            3.1.0              
pandas                0.25.1             
pandocfilters         1.4.2              
pbr                   3.1.1              
pexpect               4.2.1              
pickleshare           0.7.4              
Pillow                5.1.0              
pip                   19.3               
prompt-toolkit        1.0.15             
protobuf              3.9.2              
pycairo               1.16.2             
pycrypto              2.6.1              
pycups                1.9.73             
Pygments              2.2.0              
pygobject             3.26.1             
pymacaroons           0.13.0             
PyNaCl                1.1.2              
pyparsing             2.4.2              
pyRFC3339             1.0                
python-apt            1.6.4              
python-dateutil       2.8.0              
python-debian         0.1.32             
pytz                  2018.3             
pyxdg                 0.25               
PyYAML                3.12               
pyzmq                 16.0.2             
reportlab             3.4.0              
requests              2.18.4             
requests-unixsocket   0.1.5              
scipy                 1.3.1              
SecretStorage         2.3.1              
setuptools            41.2.0             
simplegeneric         0.8.1              
simplejson            3.13.2             
six                   1.11.0             
ssh-import-id         5.7                
system-service        0.3                
systemd-python        234                
tensorboard           2.0.0              
tensorflow            2.0.0              
tensorflow-estimator  2.0.0              
tensorflow-gpu        2.0.0              
termcolor             1.1.0              
terminado             0.7                
testpath              0.3.1              
testresources         2.0.0              
tornado               4.5.3              
traceback2            1.4.0              
traitlets             4.3.2              
ubuntu-drivers-common 0.0.0              
ufw                   0.36               
unattended-upgrades   0.1                
unittest2             1.1.0              
urllib3               1.22               
usb-creator           0.3.3              
wadllib               1.3.2              
wcwidth               0.1.7              
webencodings          0.5                
Werkzeug              0.16.0             
wheel                 0.30.0             
wrapt                 1.11.2             
xkit                  0.0.0              
zope.interface        4.3.2

**Comment by gowthamkpr** [comment]
@yangzhuoran I think the installation is not done well. Try uninstalling Tensorflow and installing ot back.
Inorder just to test, you can create a clean virtual environment and try installing tensorflow and running this code.
