### ISSUE TITLE
Test //tensorflow/lite/python:tflite_convert_test is broken

### ISSUE THREAD

**Issue by wwwind** [tensorflow/tensorflow#32991]
I run Python tests for TFLite converter using this command 
`//tensorflow/lite/python:tflite_convert_test`

and I have error:
`ERROR: missing input file '//tensorflow/lite/python:tflite_convert.par'`

Please take a look and include this test data or maybe I run it wrong way ?
Thanks

**Comment by wwwind** [comment]
@gargn Could you please take a look ? Thanks

**Comment by gadagashwini** [comment]
@wwwind,
Provide the exact sequence of commands / steps that you executed before running into the problem. Thanks!

**Comment by gargn** [comment]
The test is not expected to work in open source currently.

**Comment by karimnosseir** [comment]
@wwwind Can you please retry from the main branch and let me know if it is still failing

Thanks

**Comment by karimnosseir** [comment]
Marking as fixed. Please feel free to reopen and assign to me if anything is needed.

Thanks
