### ISSUE TITLE
Error while installing tensorflow using pip on Ubuntu 14.04 32-bit system

### ISSUE THREAD

**Issue by maniteja123** [tensorflow/tensorflow#33]
Hi devs,

I was trying to install the package in Ubuntu when this error is occurring. I am not sure what the reason is since I am using Python 2.7.6 and already have numpy and six installed. 

    /usr/local/bin/pip run on Tue Nov 10 12:44:29 2015
    tensorflow-0.5.0-cp27-none-linux_x86_64.whl is not a supported wheel on this platform.
    Exception information:
    Traceback (most recent call last):
     File "/usr/local/lib/python2.7/dist-packages/pip/basecommand.py", line 122, in main
      status = self.run(options, args)
     File "/usr/local/lib/python2.7/dist-packages/pip/commands/install.py", line 257, in run
      InstallRequirement.from_line(name, None))
     File "/usr/local/lib/python2.7/dist-packages/pip/req.py", line 167, in from_line
       raise UnsupportedWheel("%s is not a supported wheel on this platform." % wheel.filename
    UnsupportedWheel: tensorflow-0.5.0-cp27-none-linux_x86_64.whl is not a supported wheel on    this  platform.

Apologies if this is a common problem. Thanks in advance :)

**Comment by mrry** [comment]
Hi there! We've only released binaries for (and tested TensorFlow with) 64-bit platforms so far. You might have more luck building from sources: http://tensorflow.org/get_started/os_setup.md#installing_from_sources

**Comment by maniteja123** [comment]
Hi, thanks a lot for the reply. I will try installing from the sources and let you know. Sorry for my ignorance since I didnt clearly understand meaning of x86_64.
