### ISSUE TITLE
Link to next tutorial at the bottom of the first tutorial leads to the home page

### ISSUE THREAD

**Issue by endobson** [tensorflow/tensorflow#330]
On: http://www.tensorflow.org/tutorials/mnist/beginners/index.md
The last paragraph:
What matters is that we learned from this model. Still, if you're feeling a bit down about these results, check out the next tutorial where we do a lot better, and learn how to build more sophisticated models using TensorFlow!

'The next tutorial' links to http://www.tensorflow.org/tutorials/index.md which ends up showing me the home page.

**Comment by martinwicke** [comment]
Not any more.
