### ISSUE TITLE
deepspeech running issue

### ISSUE THREAD

**Issue by samhithaaaa** [tensorflow/tensorflow#33007]
![image](https://user-images.githubusercontent.com/36496141/66105607-bd81a980-e570-11e9-8b01-77e08a7f27d4.png)
Facing this issue,any help would be appreciated.
Thanks

**Comment by gowthamkpr** [comment]
@samhithaaaa Its too vague for me to respond to this issue but you can take a look at this [issue](https://github.com/tensorflow/tensorflow/issues/17702) which should help you in solving the problem.

**Comment by samhithaaaa** [comment]
> @samhithaaaa Its too vague for me to respond to this issue but you can take a look at this [issue](https://github.com/tensorflow/tensorflow/issues/17702) which should help you in solving the problem.
> 
> Also if that issue doesn't help you in solving the problem,
> Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version. Also, did you compile from source or install a binary?
> 
> Make sure you also include the exact command if possible to produce the output included in your test case. If you are unclear what to include see the issue template displayed in the Github new issue template.
> 
> We ask for this in the issue submission template, because it is really difficult to help without that information. Thanks!

I am using ubuntu with arm v8 architecture.My tensorflow version is 1.14.I compiled this tensorflow from source .while implementing deepspeech :https://github.com/tensorflow/models/tree/master/research/deep_speech this link after donwloading data I am facing this issue while training.python deepspeech.py

**Comment by gowthamkpr** [comment]
Can you provide me the series of commands that you followed before running into this issuse?

**Comment by samhithaaaa** [comment]
1.export PYTHONPATH="$PYTHONPATH:/path/to/models"
<https://github.com/tensorflow/models/tree/master/research/deep_speech#install-dependencies>
2.pip3 install -r requirements.txt
3.python data/download.py
4.python deep_speech.py


I am stuck at this step.

5.sh run_deep_speech.sh

**Comment by conqueror7** [comment]
Hi,
I'm also facing the "UnrecognizedFlagError" issue of Abseil library while running below command 
`python3 deep_speech.py`

I'm using following system config -
OS - Debian GNU/Linux 9.9 (stretch)
Python 3.5.3
Tensorflow 1.14.0

And ran below commands in order
1. export PYTHONPATH="$PYTHONPATH:/path/to/models"
2. pip3 install -r requirements.txt
3. python data/download.py
4. sh run_deep_speech.sh

![image](https://user-images.githubusercontent.com/24800950/66310270-64779400-e929-11e9-9793-3b0125febcf8.png)

**Comment by gowthamkpr** [comment]
Can you try it with Tensorflow 1.13 and let me know if it works?

**Comment by samhithaaaa** [comment]
I have already tried with 1.13 too but that doesn’t help either

**Comment by conqueror7** [comment]
Hi @samhithaaaa ,
I debugged the issue, I found that in file- https://github.com/tensorflow/models/blob/master/official/utils/flags/_base.py
In below function, train_epochs=False by default.
`def define_base(data_dir=True, model_dir=True, clean=False, train_epochs=False,
                epochs_between_evals=False, stop_threshold=False,
                batch_size=True, num_gpu=False, hooks=False, export_dir=False,
                distribution_strategy=False, run_eagerly=False):
 `
whereas while calling the same function in https://github.com/conqueror7/models/blob/master/research/deep_speech/deep_speech.py
In Line 303, flags_core.define_base(), train_epochs is not set to True. Thus, it not getting defined in flag obj and not recognised later.
`def define_deep_speech_flags():
  """Add flags for run_deep_speech."""
  # Add common flags
  flags_core.define_base(
      data_dir=False  # we use train_data_dir and eval_data_dir instead
  )`
So, you can edit the code in deep_speech.py as follows-
`def define_deep_speech_flags():
  """Add flags for run_deep_speech."""
  # Add common flags
  flags_core.define_base(
      train_epochs=True,
      data_dir=False  # we use train_data_dir and eval_data_dir instead
  )`

**Comment by gowthamkpr** [comment]
Glad that you were able to reslove the issue. 
@samhithaaaa Can you please try the recommendation given by @conqueror7 and let me know if that helps you in solving the issue.

**Comment by gowthamkpr** [comment]
Closing this issue as it has been resolved. Please add additional comments and we can open the issue again. Thanks!
