### ISSUE TITLE
Stop inheriting `tf.keras.Model` to build custom layers in tutorials and guides.

### ISSUE THREAD

**Issue by yunabe** [tensorflow/tensorflow#33006]
## URL(s) with the issue:
- https://www.tensorflow.org/tutorials/text/nmt_with_attention
`Encoder`, `BahdanauAttention` and `Decoder` inherit `tf.keras.Model`.
- https://www.tensorflow.org/guide/eager#variables_and_optimizers
Model does not need to be a subclass of `tf.keras.Model` because we don't use `Model`'s utility methods.
- https://www.tensorflow.org/tutorials/customization/custom_layers#models_composing_layers
  > The main class used when creating a layer-like thing which contains other layers is tf.keras.Model. Implementing one is done by inheriting from tf.keras.Model.

  This is not accurate since TF 1.13 (and standalone keras 2.3.0)

There are other tutorials which use `tf.keras.Model` when `tf.keras.layers.Layer` is sufficient.

## Description of issue (what needs changing):

We should stop inheriting `tf.keras.Model` in tutorials when we don't use utility functions of `Model`.

### Clear description

Since tf1.13 and [standalone keras 2.3.0](https://github.com/keras-team/keras/releases/tag/2.3.0), *Layers set as attributes of a Layer are now tracked*.
Also, [Writing custom layers and models with Keras](https://www.tensorflow.org/guide/keras/custom_layers_and_models) says *A Model is just like a Layer, but with added training and serialization utilities.*

We don't need to inherit `Model` unless we use "utility methods" of `Model`. I think the idea like *"Always extend Model because Model has more features"* is not correct because utilities of Model work only with special subsets of Layer ([Layers whose call receive only one input](https://github.com/tensorflow/tensorflow/blob/c8ef33dd913463ced8cc347c03945a88b34da7f8/tensorflow/python/keras/engine/training.py#L1461)).

Thus, I think we should stop inheriting `tf.keras.Model` in tutorials when `tf.keras.layers.Layer` is enough.

My original question on stackoverflow as a context of this bug:
https://stackoverflow.com/questions/58118334/when-should-we-inherits-keras-model-instead-of-keras-layers-layer-even-if-we-don
### Submit a pull request?

I'm sending a pull requests to fix them.

**Comment by MarkDaoust** [comment]
The above PR resolves these questions.
