### ISSUE TITLE
Using Tflite in Java for getting image as float array

### ISSUE THREAD

**Issue by ArtyomMashkin** [tensorflow/tensorflow#33011]
I have own tranied model and it works right(already implemented on Swift). My inputs for Tflite in Java - two float one-dimensional arrays with size 1*512*512*3 with values from 0.0 to 1.0. They are images and I have to insert them sequentially in Tflite and get new image as one-dimensional float array with the same size. The Tflite docs give only common info about input and output and tell that it should be either ByteBuffer or one-dimensional or multidimensional array of primitive. In examples and internet I have found the task with classification of objects from bitmap or I have found the example with multidimensional array as inputs and outputs, but it seems they are not my cases. The main problem is - I always get bad result because I definitely can’t figure out how to properly configure the inputs and outputs, because he documentation gives very little information and I do not see my case in all examples because I have two float one-dimensional arrays as inputs and float one-dimensional array as output as I said previously.

I try to implement in Java on Android Studio 3.4 on Ubuntu 18.04.

Note: Also I use C++ code in my project. And for set up image from float[] I convert float[] to opentCv Mat, after this I convert Mat into Bitmap. For all this I have method with name:

initializeSecond()
I have checked this method with other images as float[] and it works fine.

So I tried many cases and I will show the main of them:

1)

float masked[] = coreResult.getMasked();
            float inverted[] = coreResult.getInverted();
            float output[]= new float[1*512*512*3];
            Object[] inputs = new Object[]{masked, inverted};
            Map<Integer, Object> outputs = new HashMap();
            outputs.put(0, output);
            interpreter.runForMultipleInputsOutputs(inputs, outputs);
            initializeSecond(coreRequest, output);
2)

float masked[] = coreResult.getMasked();
            float inverted[] = coreResult.getInverted();
            float output[]= new float[1*512*512*3];
            ByteBuffer byteBufferMasked = ByteBuffer.allocateDirect(masked.length*4);
            byteBufferMasked.order(ByteOrder.nativeOrder());
            byteBufferMasked.asFloatBuffer().put(masked);

            ByteBuffer byteBufferInverted = ByteBuffer.allocateDirect(inverted.length*4);
            byteBufferInverted.order(ByteOrder.nativeOrder());
            byteBufferInverted.asFloatBuffer().put(inverted);
            Object[] inputs = new Object[]{byteBufferMasked, byteBufferInverted};
            Map<Integer, Object> outputs = new HashMap();
            outputs.put(0, output);
            interpreter.runForMultipleInputsOutputs(inputs, outputs);
            initializeSecond(coreRequest, output);
3)

float masked[] = coreResult.getMasked();
            float inverted[] = coreResult.getInverted();
            float output[]= new float[1*512*512*3];
            ByteBuffer byteBufferOutput = ByteBuffer.allocateDirect(output.length*4);
            byteBufferOutput.order(ByteOrder.nativeOrder());
            ByteBuffer byteBufferMasked = ByteBuffer.allocateDirect(masked.length*4);
            byteBufferMasked.order(ByteOrder.nativeOrder());
            byteBufferMasked.asFloatBuffer().put(masked);

            ByteBuffer byteBufferInverted = ByteBuffer.allocateDirect(inverted.length*4);
            byteBufferInverted.order(ByteOrder.nativeOrder());
            byteBufferInverted.asFloatBuffer().put(inverted);
            Object[] inputs = new Object[]{byteBufferMasked, byteBufferInverted};
            Map<Integer, Object> outputs = new HashMap();
            outputs.put(0, byteBufferOutput);
            interpreter.runForMultipleInputsOutputs(inputs, outputs);
            output = byteBufferOutput.asFloatBuffer().array();
            initializeSecond(coreRequest, output);
4) I put in code from 3 case

for (int i = 0; i < output.length; i++) {
                output[i] = byteBufferOutput.getFloat(i);
            }
instead

 output = byteBufferOutput.asFloatBuffer().array();
The results of cases:

1) Internal error: Unexpected failure when preparing tensor allocations: tensorflow/lite/kernels/conv.cc:235 input->dims->size != 4 (1 != 4) Node number 2 (CONV_2D) failed to prepare.

2) Cannot copy between a TensorFlowLite tensor with shape [1, 512, 512, 3] and a Java object with shape [786432].

3) java.lang.UnsupportedOperationException. It is the result of byteBufferOutput.asFloatBuffer().array(). It seems I can not get the array by this

4) I have not errors, but it works very slowly and I have the bad result: image with black background and colorful dots

**Comment by jdduke** [comment]
(3) and (4) both look reasonable. I actually have an in-flight CL that will allow feeding/fetching FloatBuffers directly, which should make interop a little less awkward.  You can also use the get(float[]) overload of FloatBuffer to put into an output float array.

However, one thing you should try doing is caching the ByteBuffers, that is, only create them once, and reuse them across inference calls.

**Comment by ArtyomMashkin** [comment]
When I try byteBufferOutput.asFloatBuffer().get(output)  I get BufferUnderflowException. What CL do you have? And how can I try to caching the ByteBuffers if I use three in one moment(for two inputs and one output)? Or do you mean than I should use consistently buffer.run(input, output) instead runForMultipleInputsOutputs?

**Comment by jdduke** [comment]
For the BufferUnderflowException, make sure you rewind your `byteBufferOutput` before you extract the array from it, e.g.,
```
byteBufferOutput.rewind();
output = byteBufferOutput.asFloatBuffer().array();
```

**Comment by ArtyomMashkin** [comment]
About byteBufferOutput.rewind(); Yes! it works. Thanks! I also have find the solution - use

**Comment by jdduke** [comment]
We'll be sure to update the documentation to make this behavior more clear. Cheers.

**Comment by ArtyomMashkin** [comment]
About byteBufferOutput.rewind(); Yes! it works. Thanks! I also have found the solution - use `byteBufferOutput.flip();
            for (int i = 0; i < masked.length; i++) {
                output[i] = byteBufferOutput.getFloat();
            }  `  Now my code above works I get the result and convert it as bitmap. One problem - very slowly. About 15 sec. I need at least 4-5. Okay, I will think about context class for them. For example in My MainActivity. But anyway it is about creating them and allocate, righ? And I need to use three ByteBuffer in one moment and every time put new arrays in them(it's not fast too). I understand that I work with three arrays and they are big arrays but can I do it more fastly also in other ways? Need I use ByteArray anyway? Can I put as inputs my array considering that Tflite doc says tha input may be primitive array.

**Comment by jdduke** [comment]
What device are you running this on? Have you tried using our [benchmark tooling](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/tools/benchmark#on-android) to profile the model itself? It's possible this model isn't well-suited for mobile, or it may benefit from using an accelerator like the [GPU](https://www.tensorflow.org/lite/performance/gpu_advanced) or from using [quantization](https://www.tensorflow.org/lite/performance/model_optimization). See also [this guide on performance](https://www.tensorflow.org/lite/performance/best_practices).
