### ISSUE TITLE
ERROR: Config value android_arm64 is not defined in any .rc file

### ISSUE THREAD

**Issue by Davari393** [tensorflow/tensorflow#33013]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):source
- TensorFlow version:1.15
- Python version:3.6
- Installed using virtualenv? pip? conda?:virtual.pip
- Bazel version (if compiling from source):0.26
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

when run this:

bazel build -c opt \
  --config=android_arm64 \
  --cxxopt='--std=c++11' \
  //tensorflow/lite/tools/evaluation/tasks/coco_object_detection:run_eval

get error:

ERROR: Config value android_arm64 is not defined in any .rc file

how can I fix it?

**Comment by jdduke** [comment]
Have you run the `/.configure` script from the root directory, and set up your build environment against your local Android SDK/NDK directories?

**Comment by jdduke** [comment]
The `android_arm64` config should be defined in the root TensorFlow checkout's `.bazelrc` file, see https://github.com/tensorflow/tensorflow/blob/master/.bazelrc#L9.
