### ISSUE TITLE
No module named `tensorflow.data`

### ISSUE THREAD

**Issue by MadsAdrian** [tensorflow/tensorflow#33022]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution: Linux Ubuntu 18.04.3 using the official tf docker image (local: macOS High Sierra v10.13.6)
- TensorFlow installed from: Official docker image
- TensorFlow version: v2.0.0-rc2-26-g64c3d38 2.0.0
- Python version: 3.6.8

**Describe the current behavior**
`'import tensorflow.data'` yields `ModuleNotFoundError: No module named 'tensorflow.data'`.

**Describe the expected behavior**
Import the submodule as rc0 did.

**Code to reproduce the issue**
For the release candidate,
`docker run tensorflow/tensorflow:2.0.0rc0-gpu-py3 python -c 'import tensorflow.data'` works fine.
`docker run tensorflow/tensorflow:2.0.0-gpu-py3 python -c 'import tensorflow.data'` yields `ModuleNotFoundError: No module named 'tensorflow.data'`.

**Comment by mihaimaruseac** [comment]
Expected behavior. The only supported way is to `import tensorflow as tf` and access the rest of the API via `tf`'s attributes. All other ways of importing might break.

```
>>> import tensorflow as tf
>>> tf.__version__
'2.0.0'
>>> tf.data
<module 'tensorflow_core._api.v2.data' from '/tmp/20/1/lib/python3.6/site-packages/tensorflow_core/_api/v2/data/__init__.py'>
>>> import tensorflow.data
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'tensorflow.data'
>>> 
```
