### ISSUE TITLE
optimize gfile for sequential reading

### ISSUE THREAD

**Issue by ustcwlin** [tensorflow/tensorflow#33023]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using): 1.12 and 2.0
- Are you willing to contribute it (Yes/No): Yes

**Describe the feature and the current behavior/state.**
The current gfile only contain one buffer and most of behave is sequential reading, I think it is worthwhile to let gfile to contain double buffers to overlap reading and processing completely. I will make sure there is no performance regression even the handle is used for random access（seek or other interface）. The feature will be very useful especially when use tensorflow in cloud environment and IO has a very long latency.

**Will this change the current api? How?**
I maybe will introduce additonal optional argument to let user to tell if the handle will be used as sequential reading or random reading.

**Who will benefit with this feature?**
anyone who will use the gfile, and most of behave is sequential reading, and the read latency is a little long.

**Any Other info.**
I will prepare the change and send CR

**Comment by mihaimaruseac** [comment]
Please tag me in any PRs related to this.

**Comment by ustcwlin** [comment]
> Please tag me in any PRs related to this.

so you agree it is worthwhile to develop. Sure, i will tag you in the related PRs

**Comment by qiuxiafei** [comment]
hey guys, the PR has been submitted. https://github.com/tensorflow/tensorflow/pull/35670

**Comment by rmothukuru** [comment]
@ustcwlin,
Can you please confirm if we can close this issue with respect to [this comment](https://github.com/tensorflow/tensorflow/pull/35670#issuecomment-597154748) from Mihai in #35670? Thanks!
