### ISSUE TITLE
[Tensorboard] Make long column names in "Images" tab more readable

### ISSUE THREAD

**Issue by neocxi** [tensorflow/tensorflow#3302]
Currently it's difficult to read long experiment names in "Images" tab due to the lack of word-break and adaptive cell height: 
![image](https://cloud.githubusercontent.com/assets/1441616/16820454/e5bbb9c8-4905-11e6-908f-25caa0ba9027.png)

Adding `word-break: break-all;` to and removing `height: 30px;` from the css class `.run-name-cell.tf-image-grid` will make it easier to read: 
![image](https://cloud.githubusercontent.com/assets/1441616/16820551/852360ba-4906-11e6-9a93-af92ae1060e1.png)

**Comment by jmchen-g** [comment]
Sounds good. @danmane Could you take a look at this please?

**Comment by danmane** [comment]
Thanks for the suggestion. I've implemented the change and it's working its way through our internal review system.
