### ISSUE TITLE
Silent end of the estimator's train_and_evaluate method but exit code != 0

### ISSUE THREAD

**Issue by LoicDagnas** [tensorflow/tensorflow#33020]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): light adaptation in the estimator paradigm of the TensorFlow 2.0 [BERT pretraining code](https://github.com/tensorflow/models/tree/master/official/nlp)
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: None
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.0
- Python version: 3.6.8
- Bazel version (if compiling from source): None
- GCC/Compiler version (if compiling from source): None
- CUDA/cuDNN version: None
- GPU model and memory: only CPU for now

**Current behavior**
Running a BERT pretraining (but I don't think it is tied to my issue) in the TensorFlow estimator paradigm (using `train_and_evaluate` method), everything sounds to be ok, one checkpoint is written and script terminate without any apparent error. However, regarding at the final exit code, we realize that it is not 0 but the very generic Windows one `-1073741819 (0xC0000005)`.

**Describe the expected behavior**
If every thing really went well, the expected error code is logically zero.

**Other info / logs**
Just before crashing silently, in the cpp logs we have:
```
2019-10-01 13:13:14.853411: I .\tensorflow/core/common_runtime/executor.h:229] ExecutorBarrier finished with bad status: Invalid argument: NewRandomAccessFile failed to Create/Open: 
�
�
	input_ids��
�e��
�������:����g������gg�gf�����'g�1� �l��0g������g�Hg��E��������������u�x����5���������4�����g�x���f

```
Please find attached two log files of my failing scripts: one with only python logs and another one with cpp log level set to maximum verbosity.

[logs.zip](https://github.com/tensorflow/tensorflow/files/3686288/logs.zip)

**Comment by oanush** [comment]
@LoicDagnas ,
Thank you for reporting the issue, Can you share a simple and standalone code to reproduce the issue reported here?

**Comment by LoicDagnas** [comment]
@oanush here is one, it not really light but most of the codes comes from [TensorFlow code](https://github.com/tensorflow/models/tree/master/official/nlp).
[bert_pretraining_test.zip](https://github.com/tensorflow/tensorflow/files/3690007/bert_pretraining_test.zip)

**Comment by LoicDagnas** [comment]
@oanush do you have any news ? Thank you :)

**Comment by gowthamkpr** [comment]
@LoicDagnas Can you try running it in google colab and let me know if the issue still persists. I guess the error is occuring due to thw windows platform. Thanks!

**Comment by LoicDagnas** [comment]
Hello @gowthamkpr,
Thank you for helping me!

Actually I have, more or less, identified the problem. It sounds to come from my use of `Dataset.interleave`. Here is a new minimal example which fails both in Windows and google Colab (not silently this time):

```
import tensorflow as tf

tf_records = [
        '/content/drive/My Drive/models/bert_pretraining/input_files/bert_input1.tfrecord',
        '/content/drive/My Drive/models/bert_pretraining/input_files/bert_input1.tfrecord']

dataset = tf.data.TFRecordDataset(tf_records)

num_cpu_threads = 4
cycle_length = min(num_cpu_threads, len(tf_records))
dataset = dataset.interleave(
    tf.data.TFRecordDataset,
    cycle_length=cycle_length,
    num_parallel_calls=tf.data.experimental.AUTOTUNE)

for raw_record in dataset:
    example = tf.train.Example()
    example.ParseFromString(raw_record.numpy())
```
with Stack Trace:
```
2019-10-15 11:57:30.322354: W tensorflow/core/framework/op_kernel.cc:1622] OP_REQUIRES failed at iterator_ops.cc:929 : Invalid argument: NewRandomAccessFile failed to Create/Open: 
,

feature

ff�?���@

label

true : The filename, directory name, or volume label syntax is incorrect.
; Unknown error


Ran 1 test in 1.568s

FAILED (errors=1)

Error
Traceback (most recent call last):
  File "C:\dev\ice\helium.ice\python\language\windows\python3.6\Lib\unittest\case.py", line 59, in testPartExecutor
    yield
  File "C:\dev\ice\helium.ice\python\language\windows\python3.6\Lib\unittest\case.py", line 605, in run
    testMethod()
  File "C:\dev\ice\helium.ml\tensorflow\sinequa-tensorflow\tests\data\test_datasets.py", line 46, in test_raw_loading_bis
    for raw_record in dataset:
  File "C:\dev\ice\helium.ml\tensorflow\virtualenv\lib\site-packages\tensorflow_core\python\data\ops\iterator_ops.py", line 622, in __next__
    return self.next()
  File "C:\dev\ice\helium.ml\tensorflow\virtualenv\lib\site-packages\tensorflow_core\python\data\ops\iterator_ops.py", line 666, in next
    return self._next_internal()
  File "C:\dev\ice\helium.ml\tensorflow\virtualenv\lib\site-packages\tensorflow_core\python\data\ops\iterator_ops.py", line 651, in _next_internal
    output_shapes=self._flat_output_shapes)
  File "C:\dev\ice\helium.ml\tensorflow\virtualenv\lib\site-packages\tensorflow_core\python\ops\gen_dataset_ops.py", line 2659, in iterator_get_next_sync
    "output_types", output_types, "output_shapes", output_shapes)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa6 in position 64: invalid start byte
```

Please not that commenting the interleave part, everything is ok.

**Comment by gowthamkpr** [comment]
Can I have the gist of the colab notebook that you have used to identify this issue @LoicDagnas. Thanks!

**Comment by LoicDagnas** [comment]
@gowthamkpr 
here is the gist https://colab.research.google.com/gist/LoicDagnas/22e522fd0355e4c337a5dae325476703/tensorflow_interleave_bug.ipynb

The data I used are the two tf records in this zip:
[tfrecords.zip](https://github.com/tensorflow/tensorflow/files/3749465/tfrecords.zip)

**Comment by gowthamkpr** [comment]
@LoicDagnas  I don't think the issue is with `Dataset.interleave`. Can you please go through this [tutorial](https://towardsdatascience.com/practical-coding-in-tensorflow-2-0-fafd2d3863f6) on reading back tfrecords in Tensorflow 2.0 and let me know if it helps!

**Comment by LoicDagnas** [comment]
@gowthamkpr yessss, it helps much. I made a big mistake reading twice the dataset with `tf.data.TFRecordDataset`. I close this issue, however the only weird thing remaining is the silent failure.

Thank you.
