### ISSUE TITLE
radon and inverse radon transform, Projection and back_projection function in CT

### ISSUE THREAD

**Issue by wangwei-cmd** [tensorflow/tensorflow#33037]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using):  tf 1.14
- Are you willing to contribute it (Yes/No):  no
   When training a CT-reconstructed model, the projection and back_projection functions are usually used. However, to my knowledge, there is no api  to implement the above functions.

**Describe the feature and the current behavior/state.**
  Like in the scikit-image package, the projection function is the radon transform (skimage.transform.radon) while the back-projection is the dual operator of projection.

**Will this change the current api? How?**
Will add two maybe three apis.

**Who will benefit with this feature?**
anyone uses these functions to train CT-reconstruction moedl.

**Any Other info.**

**Comment by Priwinn** [comment]
I would like to see this feature, though in latest stable releases, should I open another issue or can we add it here?

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.

**Comment by jaweriaamjad** [comment]
Hi, has this feature been added as a tensorflow layer?
