### ISSUE TITLE
Illegal Instruction on importing tensorflow

### ISSUE THREAD

**Issue by Xavier449446** [tensorflow/tensorflow#33040]
Tensorflow version = 1.14
OS : Kali Linux Rolling (2018.2)
Output on cat /proc/cpuinfo : 
processor : 0
vendor_id : GenuineIntel
cpu family : 6
model : 23
model name : Intel(R) Core(TM)2 Duo CPU E7500 @ 2.93GHz
stepping : 10
microcode : 0xa0b
cpu MHz : 2546.724
cache size : 3072 KB
physical id : 0
siblings : 2
core id : 0
cpu cores : 2
apicid : 0
initial apicid : 0
fpu : yes
fpu_exception : yes
cpuid level : 13
wp : yes
flags : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx lm constant_tsc arch_perfmon pebs bts rep_good nopl cpuid aperfmperf pni dtes64 monitor ds_cpl vmx est tm2 ssse3 cx16 xtpr pdcm sse4_1 xsave lahf_lm pti tpr_shadow vnmi flexpriority dtherm
bugs : cpu_meltdown spectre_v1 spectre_v2
bogomips : 5850.33
clflush size : 64
cache_alignment : 64
address sizes : 36 bits physical, 48 bits virtual
power management:

processor : 1
vendor_id : GenuineIntel
cpu family : 6
model : 23
model name : Intel(R) Core(TM)2 Duo CPU E7500 @ 2.93GHz
stepping : 10
microcode : 0xa0b
cpu MHz : 2231.318
cache size : 3072 KB
physical id : 0
siblings : 2
core id : 1
cpu cores : 2
apicid : 1
initial apicid : 1
fpu : yes
fpu_exception : yes
cpuid level : 13
wp : yes
flags : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx lm constant_tsc arch_perfmon pebs bts rep_good nopl cpuid aperfmperf pni dtes64 monitor ds_cpl vmx est tm2 ssse3 cx16 xtpr pdcm sse4_1 xsave lahf_lm pti tpr_shadow vnmi flexpriority dtherm
bugs : cpu_meltdown spectre_v1 spectre_v2
bogomips : 5850.33
clflush size : 64
cache_alignment : 64
address sizes : 36 bits physical, 48 bits virtual
power management:

**Comment by Xavier449446** [comment]
![Screenshot from 2019-10-04 09-26-33](https://user-images.githubusercontent.com/47718724/66202206-c7b3bd00-e6c2-11e9-8a78-83d895963221.png)

**Comment by gadagashwini** [comment]
@Xavier449446, Does your CPU supports AVX instruction set or not.
Please refer this [link](https://superuser.com/questions/1251865/is-there-a-way-to-tell-if-my-hardware-supports-specific-instructions) to know the CPU instructions set. Thanks!

**Comment by mihaimaruseac** [comment]
Based on the cpuinfo provided, your CPU doesn't support AVX. See #19584

**Comment by gadagashwini** [comment]
@Xavier449446, Try to build the Tensorflow from source. Please follow the instructions mentioned in the [website](https://www.tensorflow.org/install/source). Thanks!

**Comment by mihaimaruseac** [comment]
Closing as issue has been identified to be AVX support lacking
