### ISSUE TITLE
TPU support in tensorflow 2.0 release

### ISSUE THREAD

**Issue by georgealexandruvlad** [tensorflow/tensorflow#33045]
From the following link https://www.tensorflow.org/guide/distributed_training I understand that TPU training is supported in tensorflow 2.0.

I followed the snippet code provided in the same page:

cluster_resolver = tf.distribute.cluster_resolver.TPUClusterResolver(
    tpu=tpu_address)
tf.config.experimental_connect_to_cluster(cluster_resolver)
tf.tpu.experimental.initialize_tpu_system(cluster_resolver)
tpu_strategy = tf.distribute.experimental.TPUStrategy(cluster_resolver)

And I got the following error:
InvalidArgumentError: Unable to find a context_id matching the specified one (-7989870214237460624). Perhaps the worker was restarted, or the context was GC'd?
Additional GRPC error information:
{"created":"@1570180842.964900283","description":"Error received from peer","file":"external/grpc/src/core/lib/surface/call.cc","file_line":1039,"grpc_message":"Unable to find a context_id matching the specified one (-7989870214237460624). Perhaps the worker was restarted, or the context was GC'd?","grpc_status":3}

Same error was thrown when I didn't provide the tpu_address as it is stated in the above link.

> The TPUClusterResolver instance helps locate the TPUs. In Colab, you don't need to specify any arguments to it.

The test was done in google colab and I selected the TPU accelerator. I installed tensorflow-gpu with !pip install tensorflow-gpu.

If TPU is not yet supported in tf 2.0 when it is planed to be added?

**Comment by gadagashwini** [comment]
@georgealexandruvlad, Please provide the complete code to reproduce the issue reported issue here. Thanks!

**Comment by georgealexandruvlad** [comment]
The code can be found in following link: https://colab.research.google.com/drive/1CfY-bW-sRjZbvkQDjjl1CMiIzN6bJhQn

Basically I just try to initialize the TPU.
```
!pip install tensorflow-gpu
import tensorflow as tf
tf.__version__
# tpu_address = 'grpc://' + os.environ['COLAB_TPU_ADDR']

cluster_resolver = tf.distribute.cluster_resolver.TPUClusterResolver()
tf.config.experimental_connect_to_cluster(cluster_resolver)
tf.tpu.experimental.initialize_tpu_system(cluster_resolver)
tpu_strategy = tf.distribute.experimental.TPUStrategy(cluster_resolver)
```

Full error message:

```
INFO:tensorflow:Initializing the TPU system: 10.20.247.218:8470
INFO:tensorflow:Initializing the TPU system: 10.20.247.218:8470
---------------------------------------------------------------------------
InvalidArgumentError                      Traceback (most recent call last)
<ipython-input-1-9d9ec86e8e0b> in <module>()
      5 cluster_resolver = tf.distribute.cluster_resolver.TPUClusterResolver()
      6 tf.config.experimental_connect_to_cluster(cluster_resolver)
----> 7 tf.tpu.experimental.initialize_tpu_system(cluster_resolver)
      8 tpu_strategy = tf.distribute.experimental.TPUStrategy(cluster_resolver)

8 frames
/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/eager/context.py in add_function(self, fn)
    987     """
    988     self.ensure_initialized()
--> 989     pywrap_tensorflow.TFE_ContextAddFunction(self._handle, fn)
    990 
    991   def add_function_def(self, fdef):

InvalidArgumentError: Unable to find a context_id matching the specified one (477754036002299890). Perhaps the worker was restarted, or the context was GC'd?
Additional GRPC error information:
{"created":"@1570430673.362553023","description":"Error received from peer","file":"external/grpc/src/core/lib/surface/call.cc","file_line":1039,"grpc_message":"Unable to find a context_id matching the specified one (477754036002299890). Perhaps the worker was restarted, or the context was GC'd?","grpc_status":3}
```

**Comment by jvishnuvardhan** [comment]
@georgealexandruvlad Thanks for testing TF2.0 TPUs. This seems to be a known issue as https://github.com/huan/tensorflow-handbook-tpu/issues/1 which the colab kernel on tpu worker is out dated, Team is working on the fix. Thanks!

**Comment by georgealexandruvlad** [comment]
@jvishnuvardhan Thank you. Is there any way to follow the progress on the matter or do you happen to know when the issue might be resolved. Thanks!

**Comment by georgealexandruvlad** [comment]
@jvishnuvardhan I checked it today and it looks like the issue has been solved. Thanks.

**Comment by scheng123** [comment]
Uhh I don't it's fixed yet. Initializing works, but not fitting.

First off, you installed '1.15.0-rc3', not tensorflow 2.0.

Second, you need to fit under tpu_strategy.scope() to train it under the TPU

Do that, and you get an error.

Bottom line: TPU is not ready for Tensorflow 2.0 yet

**Comment by Santosh-Gupta** [comment]
I am wondering if there's still issues with TPU support in tf 2.0. I have a model that runs just fine in GPU, but I am getting an 

```
    AttributeError: Tensor.name is meaningless when eager execution is enabled.
```

Error at `self.optimizer.apply_gradients(zip(gradients, trainable_vars))`.

Link

https://github.com/tensorflow/tensorflow/issues/34635#issuecomment-650667602
