### ISSUE TITLE
Kernel restating while importing tensorflow on Old Macs, works OK on new one.

### ISSUE THREAD

**Issue by Tj85710** [tensorflow/tensorflow#33047]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version (use command below):
- Python version:
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**

**Describe the expected behavior**

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by Tj85710** [comment]
Hello, 
I am installing Tensorflow according to the Jeff Heaton. On an iMac mid-2010 with 2,93 GHz Core i7, 12GB RAM, the installation of the whole packages is OK, I can start jupyter. Than, when I want to import tensorflow as tf, the kernel restarts... I have tried it on the same host in a Parallels Virtual Machine configured with MacOS 10.13.6, same behavior. Than I have installed the same softare stack in a clean VM (VirtualBox) running Ubuntu 18.04, same behavior.
On a MacBook Pro Retina 2012, everything works. On an older MacBook Pro 17" mid-2010, Core i5, the problem is present too.
Any clue ?
Thanks for you help,
Thierry

**Comment by gadagashwini** [comment]
@Tj85710, Please follow the instructions mentioned in the [Tensorflow](https://www.tensorflow.org/install/pip) website to install Tensorflow,select the mac os.Thanks!

**Comment by Tj85710** [comment]
I have found references to this behaviour : My processors are too old, they don't support the AVX instruction set. I am building a VM with Ubuntu, 8 Xeon cores, 40 GB RAM and try to build a custom version with the correct --march flag.
Cross fingers !
Thanks for your answer,

Thierry
