### ISSUE TITLE
EdgeTPU library is not updating for coral dev board 

### ISSUE THREAD

**Issue by sanchitjain04** [tensorflow/tensorflow#33041]
* Doc you were trying to follow: https://coral.withgoogle.com/news/updates-07-2019/
* Your host OS: Ubuntu 16.04
Python3 version: 3.5.3

# What I ran

I executed the commands as mentioned in the post as mentioned above :

sudo apt-get update

sudo apt-get dist-upgrade

this automatically updates the edgetpu library along with other Mendel system software.

# What the docs said should happen:

As per the post it should have updated the library but after updates were done the edgetpu library version is still been shown as 1.2.0

But our expectations were to be updated to newest 2.11.1 version

# What actually happened

EdgeTPU library version is still been shown as 1.2.0

Kindly help in resolving the issue.

**Comment by ymodak** [comment]
Edge TPU Python library is deprecated and [PyCoral](https://coral.ai/software/#pycoral-api) is the new library for Python development with the Edge TPU.
