### ISSUE TITLE
Build Tensorflow  from sources  for Android x86_64

### ISSUE THREAD

**Issue by dimitryn** [tensorflow/tensorflow#33051]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
Ubunutu
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
Master, 1.14
- TensorFlow version:
- Python version:
2.7
- Installed using virtualenv? pip? conda?:
- Bazel version (if compiling from source):
25
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:
NDK 17,18

**Describe the problem**
Hi , I am trying to build tensorflow shared library from sources for our device CPU Appolo Lake with Android OS .
**Provide the exact sequence of commands / steps that you executed before running into the problem**
build command 
bazel build  //tensorflow:tensorflow  --cpu=x86_64 --crosstool_top=//external:android/crosstool --host_crosstool_top=@bazel_tools//tools/cpp:toolchain --cxxopt="-std=c++11"

output
From Compiling tensorflow/core/kernels/string_split_op.cc:
tensorflow/core/kernels/string_split_op.cc:129:15: warning: 'RemoveLeadingWhitespace' is deprecated: Use absl::StripLeadingAsciiWhitespace instead. [-Wdeprecated-declarations]
    str_util::RemoveLeadingWhitespace(&text);
              ^
./tensorflow/core/lib/strings/str_util.h:55:1: note: 'RemoveLeadingWhitespace' has been explicitly marked deprecated here
ABSL_DEPRECATED("Use absl::StripLeadingAsciiWhitespace instead.")
^
external/com_google_absl/absl/base/macros.h:148:49: note: expanded from macro 'ABSL_DEPRECATED'
#define ABSL_DEPRECATED(message) __attribute__((deprecated(message)))
                                                ^
tensorflow/core/kernels/string_split_op.cc:133:17: warning: 'RemoveLeadingWhitespace' is deprecated: Use absl::StripLeadingAsciiWhitespace instead. [-Wdeprecated-declarations]
      str_util::RemoveLeadingWhitespace(&text);
                ^
./tensorflow/core/lib/strings/str_util.h:55:1: note: 'RemoveLeadingWhitespace' has been explicitly marked deprecated here
ABSL_DEPRECATED("Use absl::StripLeadingAsciiWhitespace instead.")
^
external/com_google_absl/absl/base/macros.h:148:49: note: expanded from macro 'ABSL_DEPRECATED'
#define ABSL_DEPRECATED(message) __attribute__((deprecated(message)))
                                                ^
2 warnings generated.
ERROR: /home/dnozik/.cache/bazel/_bazel_dnozik/0d8e3d5d91fa64e88329b83a7165efc6/external/lmdb/BUILD.bazel:8:1: C++ compilation of rule '@lmdb//:lmdb' failed (Exit 1)
external/lmdb/mdb.c:4859:53: error: use of undeclared identifier 'PTHREAD_MUTEX_ROBUST'
                if (!rc) rc = pthread_mutexattr_setrobust(&mattr, PTHREAD_MUTEX_ROBUST);
                                                                  ^
1 error generated.
Target //tensorflow:tensorflow failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 1894.656s, Critical Path: 288.31s
INFO: 628 processes: 628 local.
FAILED: Build did NOT complete successfully

Please help

**Comment by gadagashwini** [comment]
@dimitryn, You would like to try Tensorflow lite on Android. Please take a look at the instructions mentioned in this [link](https://www.tensorflow.org/lite/guide/android).Thanks!

**Comment by gadagashwini** [comment]
@dimitryn, Is this still an issue?

**Comment by dimitryn** [comment]
no, thanks
