### ISSUE TITLE
No stat cache for s3 file system

### ISSUE THREAD

**Issue by ziliangpeng** [tensorflow/tensorflow#33057]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using): 1.14
- Are you willing to contribute it (Yes/No): Yes

**Describe the feature and the current behavior/state.**

In gcs file system there's a cache for object `stat` where you don't have to repeatedly send `stat` call to remote server to get stat of the same object. This is a nice performance gain but not available in s3 file system.

As s3 share the same nature as gcs, the same cache can be applied to s3 file system for the performance gain.

**Will this change the current api? How?**

No.

**Who will benefit with this feature?**

User of s3 file system, whose use pattern send rapid api calls.

**Any Other info.**

**Comment by ziliangpeng** [comment]
Thanks for looking into this.

I'm not familiar with the lifecycle of a tensorflow issue ticket. Will there be an ETA or anything I can expect next?

I'm happy to help too.

It looks like there's already a lru_cache implemented and used by gcs, it'll be a straightforward change to apply to s3 too. I've internally patched it this way for our systems.

**Comment by mihaimaruseac** [comment]
Can you submit a PR?

I won't be able to get into this until after https://github.com/tensorflow/community/pull/101 work is fully done, when I'll be converting the s3 filesystem to that API.

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.
