### ISSUE TITLE
Keras RNN training speed significantly slower with eager execution/control flow v2

### ISSUE THREAD

**Issue by drasmuss** [tensorflow/tensorflow#33052]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below): 2.0.0
- Python version: 3.6.8
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: 10.0/7.6
- GPU model and memory: GTX 980 Ti

**Describe the current behavior**

Enabling eager execution or control flow v2 causes RNN training speed to decrease significantly.

**Describe the expected behavior**

Enabling eager mode or control flow v2 should not affect the training time (or improve it, ideally).

**Code to reproduce the issue**

``` python
import tensorflow as tf
import numpy as np
import timeit

use_eager = False
use_v2 = False

if not use_eager:
    tf.compat.v1.disable_eager_execution()
if not use_v2:
    tf.compat.v1.disable_control_flow_v2()


n_steps = 1000
n_input = 100
n_hidden = 1000
batch_size = 64

inputs = tf.keras.Input((n_steps, n_input))
outputs = tf.keras.layers.SimpleRNN(units=n_hidden, return_sequences=True)(inputs)
outputs = tf.keras.layers.Dense(units=n_input)(outputs)
model = tf.keras.Model(inputs=inputs, outputs=outputs)

model.compile(optimizer=tf.optimizers.SGD(0.1), loss="mse")

x = np.ones((batch_size, n_steps, n_input))
y = np.ones((batch_size, n_steps, n_input))

# warmup
model.fit(x, y, epochs=1)

start = timeit.default_timer()
model.fit(x, y, epochs=10)
print("Execution time:", timeit.default_timer() - start)

```

**Other info / logs**
On my machine the results look like:
- use_eager=False, use_v2=False: 5.90s
- use_eager=False, use_v2=True: 8.08s
- use_eager=True, use_v2=False: 9.81s
- use_eager=True, use_v2=True: 10.10s

So, overall a >60% increase in training time comparing no eager and no v2 to the current defaults.

**Comment by gadagashwini** [comment]
@drasmuss, I tried replicating the code on colab with Tf 2.0.0.rc2 but i didn't see increase in the training time. Please take a look at the colab [gist](https://colab.sandbox.google.com/gist/gadagashwini/63e56c1793622ad377705725f555482e/untitled179.ipynb). Let me know the expected result. Thanks!

**Comment by drasmuss** [comment]
A couple problems with the gist. One is that the `use_v2`/`use_eager` logic won't work properly when it's copy-pasted multiple times like that. It only runs the disable command when flag=False, so e.g. if you run once with `use_v2=False` and then again with `use_v2=True`, it's actually disabled for both of those runs.  I don't think it's possible to re-enable those things after disabling them (you'll get an error like "`tf.enable_eager_execution must be called at program startup.`"). So you need to just edit the values and then restart the notebook to collect the different timing values. 

If you fix that, you should see a difference (although not as significant). But to see the significant differences you'll need to be running things on GPU, I'm not sure if it's possible to do that through the colab gists or not.

This is also on 2.0.0 release, not rc2. I haven't checked if that makes a difference or not though.

**Comment by drasmuss** [comment]
Here's a script you can use if you'd like to see the overall effect within one script (this works because it runs first with the defaults, and then again after disabling eager mode and control flow v2).
``` python
import tensorflow as tf
import numpy as np
import timeit


n_steps = 1000
n_input = 100
n_hidden = 1000
batch_size = 64
with tf.device("/gpu:0"):
    inputs = tf.keras.Input((n_steps, n_input))
    outputs = tf.keras.layers.SimpleRNN(units=n_hidden, return_sequences=True)(inputs)
    outputs = tf.keras.layers.Dense(units=n_input)(outputs)
    model = tf.keras.Model(inputs=inputs, outputs=outputs)

    model.compile(optimizer=tf.optimizers.SGD(0.1), loss="mse")

    x = np.ones((batch_size, n_steps, n_input))
    y = np.ones((batch_size, n_steps, n_input))

    # warmup
    model.fit(x, y, epochs=1)

    start = timeit.default_timer()
    model.fit(x, y, epochs=10)
    print("Execution time (defaults):", timeit.default_timer() - start)


tf.compat.v1.disable_eager_execution()
tf.compat.v1.disable_control_flow_v2()

with tf.device("/gpu:0"):
    inputs = tf.keras.Input((n_steps, n_input))
    outputs = tf.keras.layers.SimpleRNN(units=n_hidden, return_sequences=True)(inputs)
    outputs = tf.keras.layers.Dense(units=n_input)(outputs)
    model = tf.keras.Model(inputs=inputs, outputs=outputs)

    model.compile(optimizer=tf.optimizers.SGD(0.1), loss="mse")

    x = np.ones((batch_size, n_steps, n_input))
    y = np.ones((batch_size, n_steps, n_input))

    # warmup
    model.fit(x, y, epochs=1)

    start = timeit.default_timer()
    model.fit(x, y, epochs=10)
    print("Execution time (no eager, no v2):", timeit.default_timer() - start)
```

**Comment by gadagashwini** [comment]
I could reproduce the issue. Please take a look at the [gist here](https://colab.sandbox.google.com/gist/gadagashwini/54c7b0895c0c116e2019512e64bd7f1d/untitled188.ipynb). Thanks!

**Comment by qlzh727** [comment]
Seems to be a generic performance issue for eager runtime. Adding performance expert @robieta here.

**Comment by qlzh727** [comment]
Also note that I have tried with compile(experimental_run_tf_function=False) and still produce the same result, which indicates that somehow the slowness is caused by runtime.

**Comment by qlzh727** [comment]
With all the recent update for performance, the v1/v2 and eager/graph training time is almost identical to each other.

Please see the results in https://colab.research.google.com/gist/qlzh727/5bf1e16285bfcf2b3c2aea506fffd2e8/untitled188.ipynb

I update the original test script to fit on 10 batches instead of 1 batch in each epoch, which should simulate more standard use case.
