### ISSUE TITLE
image_gradients: 'Tensor' object has no attribute 'get_shape'

### ISSUE THREAD

**Issue by SaraAlthubaiti** [tensorflow/tensorflow#33061]
Hi all,

While I'm trying to feed my tensor to `image_gradients`, this error arises:

`AttributeError: 'Tensor' object has no attribute 'get_shape'`

The type of this tensor is: `torch.cuda.floattensor`

And its size: `torch.Size([2, 1, 128, 128])`

Any help, please.

**Comment by SamuelMarks** [comment]
Is this pytorch or TensorFlow?

**Comment by SaraAlthubaiti** [comment]
@SamuelMarks It's PyTorch

**Comment by SamuelMarks** [comment]
This is the TensorFlow GitHub. Anyway, checking it out:
https://pytorch.org/docs/stable/tensors.html

I do not see a `get_shape` available.

Maybe you want `.size()`?
 https://pytorch.org/docs/stable/tensors.html?highlight=size#torch.Tensor.size

**Comment by SaraAlthubaiti** [comment]
@SamuelMarks Yes, that's what I notice. 

It seems that `image_gradients` function implementation call `get_shape`, in which it's not available for `tensor`. And yes you're right tensor has `.size` instead (but the problem is within `image_gradients` function), I cannot call `.size` within `image_gradients` function!

**Comment by gadagashwini** [comment]
@SaraAlthubaiti, Looks like the issue is not related to Tensorflow. Can please post this issue in relevant Repo. Thanks!

**Comment by SaraAlthubaiti** [comment]
@gadagashwini I think so, thanks for your help!
