### ISSUE TITLE
.Save, .Restore for contrib.learn.DNNClassifier

### ISSUE THREAD

**Issue by jah456** [tensorflow/tensorflow#3306]
The older functions like skflow.TensorFlowDNNClassifier had methods .save and .restore.  These were supposedly migrated over to the contrib.learn functions, but there are no longer save and restore methods that I can find.  Is there a new protocol for saving the graph and variables with the new contrib.learn package?

**Comment by jmchen-g** [comment]
@ispirmustafa Could you take a look at this please?

**Comment by llealgt** [comment]
Hi, any news on this , im having hard times trying to save  a DNNClassifier , followed some examples using train.Saver() but it says (No variables to save)

**Comment by michaelisard** [comment]
@ispirmustafa any thoughts? Assigning @martinwicke since @ispirmustafa is not in the TensorFlow org.

**Comment by martinwicke** [comment]
Checkpoints are saved automatically, and if you specify the same directory when you create another Estimator (of the same kind/same parameters), it will load the checkpoints and you can continue training. 

There is currently a bug which prevents you from using the restored Estimator for inference without running at least one step of training.

I will close this issue -- for detailed questions, please ask on StackOverflow, we can track questions and answers better over there.
