### ISSUE TITLE
tf.gather can't perform real values but op while using sess.run()

### ISSUE THREAD

**Issue by LuciusPennyworth** [tensorflow/tensorflow#33067]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):Custom Code 
- OS Platform and Distribution : Linux Ubuntu 16.04
- TensorFlow installed from (source or binary):binary
- TensorFlow version (use command below):tensorflow-gpu 1.12.0
- Python version:3.6
- CUDA/cuDNN version: CUDA 9.0

**Describe the current behavior**
I 'm a beginner of TF.In my code ,I have a `myinput['point']`  matrix(shape:500x3  500 for the number of points,3 for 3-D) which stores the whole point set. I also have a `myinput['neigh']`  matirx(500x10  10 indicates each point have 10 neighbors ) which stores the **idx** of each point's neighs. When I want to get the neighs of each point , I use `tf.gather(myinput['point'],myinput['neigh'])`  .However, when I want to get the neighs of neighs,
I use the code as follow:
```
neigh_neigh_idx=tf.gather(myinput['neigh'],myinput['neigh'])
neigh_neigh=tf.gather(myinput['point'],neigh_neigh_idx)
with tf.Session() as sess:
    n_n_idx=sess.run(neigh_neigh_idx)
```
after evaluate this code, I only get `neigh_neigh_idx` and  `neigh_neigh` in console and I can't find any information but this about n_n_idx.I wander how to get ther real value of  `n_n_idx` instead of some ops.
```
[[node PointNetwork/layer_2/conv2/GatherV2_22 (defined at <string>:1)  = GatherV2[Taxis=DT_INT32, Tindices=DT_INT32, Tparams=DT_INT32, _device="/job:localhost/replica:0/task:0/device:CPU:0"](PointNetwork/layer_2/conv2/GatherV2_22/params, PointNetwork/layer_2/conv2/GatherV2_22/params, PointNetwork/layer_2/conv2/GatherV2_22/axis)]]
```
THX~

**Comment by gadagashwini** [comment]
@LuciusPennyworth, Any update on code. Thanks!

**Comment by LuciusPennyworth** [comment]
The code I post above is a brief description of my question. And it 's difficult for me to provide the complete code because they scattered in various files.However, I have figured out a way to advoid this problem and I will close this issue .Thanks for your concern.
