### ISSUE TITLE
TypeError: Input 'y' of 'Mul' Op has type float32 that does not match type float16 of argument 'x'.

### ISSUE THREAD

**Issue by wpf19911118** [tensorflow/tensorflow#33077]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution ( Linux Ubuntu 16.04):
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):binary
- TensorFlow version (use command below):1.14
- Python version:2.7
- Bazel version (if compiling from source):0.19
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:10.0  7
- GPU model and memory: V100 32G

You can collect some of this information using our environment capture

NGC images 1904

**Describe the current behavior**
TypeError: Input 'y' of 'Mul' Op has type float32 that does not match type float16 of argument 'x'.
**Describe the expected behavior**

**Code to reproduce the issue**

def _train(total_loss, global_step):
  """Train CIFAR-10 model.

  Create an optimizer and apply to all trainable variables. Add moving
  average for all trainable variables.

  Args:
    total_loss: Total loss from loss().
    global_step: Integer Variable counting the number of training steps
      processed.
  Returns:
    train_op: op for training.
  """
  # Variables that affect learning rate.
  num_batches_per_epoch = NUM_EXAMPLES_PER_EPOCH_FOR_TRAIN / FLAGS.batch_size
  decay_steps = int(num_batches_per_epoch * NUM_EPOCHS_PER_DECAY)

  # Decay the learning rate exponentially based on the number of steps.
  lr = tf.train.exponential_decay(INITIAL_LEARNING_RATE,
                                  global_step,
                                  decay_steps,
                                  LEARNING_RATE_DECAY_FACTOR,
                                  staircase=True)
  tf.summary.scalar('learning_rate', lr)

  # Generate moving averages of all losses and associated summaries.
  #loss_averages_op = _add_loss_summaries(total_loss)
  loss_averages_op = total_loss

  # Compute gradients.
  with tf.control_dependencies([loss_averages_op]):
    opt = tf.train.GradientDescentOptimizer(lr)
    opt = tf.train.experimental.enable_mixed_precision_graph_rewrite(opt)
    grads = opt.compute_gradients(total_loss)

  # Apply gradients.
  apply_gradient_op = opt.apply_gradients(grads, global_step=global_step)
  #apply_gradient_op=opt.minimize(total_loss)
  #apply_gradient_op = tf.train.GradientDescentOptimizer(lr).minimize(total_loss,global_step=global_step)

  # Add histograms for trainable variables.
  for var in tf.trainable_variables():
    tf.summary.histogram(var.op.name, var)

  # Add histograms for gradients.
  #for grad, var in grads:
  #  if grad is not None:
  #    tf.summary.histogram(var.op.name + '/gradients', grad)

  # Track the moving averages of all trainable variables.
  variable_averages = tf.train.ExponentialMovingAverage(
      MOVING_AVERAGE_DECAY, global_step)
  with tf.control_dependencies([apply_gradient_op]):
    variables_averages_op = variable_averages.apply(tf.trainable_variables())

  return variables_averages_op
**Other info / logs**

Traceback (most recent call last):
  File "cifar_for_common_cnn.py", line 566, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/usr/local/lib/python2.7/dist-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/usr/local/lib/python2.7/dist-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "cifar_for_common_cnn.py", line 562, in main
    train()
  File "cifar_for_common_cnn.py", line 495, in train
    train_op = _train(loss, global_step)
  File "cifar_for_common_cnn.py", line 421, in _train
    grads = opt.compute_gradients(total_loss)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/experimental/loss_scale_optimizer.py", line 116, in compute_gradients
    loss = self._scale_loss(loss)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/experimental/loss_scale_optimizer.py", line 134, in _scale_loss
    return loss * loss_scale
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/math_ops.py", line 897, in binary_op_wrapper
    return func(x, y, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/math_ops.py", line 1180, in _mul_dispatch
    return gen_math_ops.mul(x, y, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_math_ops.py", line 6490, in mul
    "Mul", x=x, y=y, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.py", line 563, in _apply_op_helper
    inferred_from[input_arg.type_attr]))
TypeError: Input 'y' of 'Mul' Op has type float32 that does not match type float16 of argument 'x'.

**Comment by gadagashwini** [comment]
@wpf19911118, Please provide the standalone code to reproduce the reported issue. Thanks!

**Comment by gadagashwini** [comment]
@wpf19911118, Please provide more information to reproduce the reported issue. Thanks!

**Comment by mattbernardini** [comment]
import tensorflow as tf
import numpy as np
from tensorflow.keras.datasets import mnist

gpus = tf.config.experimental.list_physical_devices('GPU')
if gpus:
    try:
        for gpu in gpus:
            tf.config.experimental.set_memory_growth(gpu, True)
        logical_gpus = tf.config.experimental.list_logical_devices('GPU')
        print(len(gpus), "Physical GPUS,", len(logical_gpus), "Logical GPUS")
    except RuntimeError as e:
        print(e)

tf.keras.backend.set_floatx('float16')
tf.keras.backend.set_epsilon(1e-4)

model = tf.keras.models.Sequential()
model.add(tf.keras.layers.Conv2D(32, (3, 3), activation='relu', input_shape=(28, 28, 1)))
model.add(tf.keras.layers.MaxPooling2D((2, 2), padding="same"))
model.add(tf.keras.layers.Conv2D(64, (3, 3), activation='relu', padding="same"))

model.add(tf.keras.layers.Flatten())
model.add(tf.keras.layers.Dense(64, activation='relu'))
model.add(tf.keras.layers.Dense(10, activation='softmax'))

model.summary()

(train_images, train_labels), (test_images, test_labels) = mnist.load_data()

train_images = train_images.reshape((60000, 28, 28, 1))
train_images = train_images.astype(np.float16) / 255

test_images = test_images.reshape((10000, 28, 28, 1))
test_images = test_images.astype(np.float16) / 255

train_labels = tf.keras.utils.to_categorical(train_labels, dtype='float16')
test_labels = tf.keras.utils.to_categorical(test_labels, dtype='float16')

opt = tf.keras.optimizers.RMSprop()
opt = tf.keras.mixed_precision.experimental.LossScaleOptimizer(opt, "dynamic")

model.compile(optimizer=opt,
              loss='categorical_crossentropy',
              metrics=['accuracy'])
model.fit(tf.dtypes.cast(train_images, tf.float16), tf.dtypes.cast(train_labels, tf.float16), epochs=50, batch_size=64, steps_per_epoch=200)

test_loss, test_acc = model.evaluate(test_images, test_labels)

test_acc

**Comment by gadagashwini** [comment]
@mattbernardini, Is this similar issue [#33484](https://github.com/tensorflow/tensorflow/issues/33484). Thanks

**Comment by mattbernardini** [comment]
I simply commented the code twice to make sure it got seen.  Other than that i am not sure.

**Comment by baliakanksha** [comment]
Args:
    x: A Tensor. Must be one of the following types: `bfloat16`,
      `half`, `float32`, `float64`, `uint8`, `int8`, `uint16`,
      `int16`, `int32`, `int64`, `complex64`, `complex128`.
    y: A `Tensor`. Must have the same type as `x`.
    name: A name for the operation (optional).
  Returns:
  A `Tensor`.  Has the same type as `x`.
  Raises:
   * InvalidArgumentError: When `x` and `y` have incompatible shapes or types

This means that -y_true is 'y' and K.log(y_pred) is 'x'. To perform this operations you'll have to cast -y_true to a float32 or cast K.log(y_pred) to an int64 or cast them both into any other type as long as they match. .

**Comment by baliakanksha** [comment]
> The error points to this line of code:
> 
> cross_entropy = -y_true * K.log(y_pred)
> and is being thrown from the multiply function in math_ops.py within the tensorflow package. Digging into that file it is found that this summary for the argument requirements.
> 
> Args:
> x: A Tensor. Must be one of the following types: `bfloat16`,
> `half`, `float32`, `float64`, `uint8`, `int8`, `uint16`,
> `int16`, `int32`, `int64`, `complex64`, `complex128`.
> y: A `Tensor`. Must have the same type as `x`.
> name: A name for the operation (optional).
> Returns:
> A `Tensor`. Has the same type as `x`.
> Raises:
> 
> * InvalidArgumentError: When `x` and `y` have incompatible shapes or types
> 
> This means that -y_true is 'y' and K.log(y_pred) is 'x'. To perform this operations you'll have to cast -y_true to a float32 or cast K.log(y_pred) to an int64 or cast them both into any other type as long as they match. .
> 
> It is Working now by doing `y_true = tf.cast(y_true, tf.float32)` >

**Comment by nisfanef** [comment]
> > The error points to this line of code:
> > cross_entropy = -y_true * K.log(y_pred)
> > and is being thrown from the multiply function in math_ops.py within the tensorflow package. Digging into that file it is found that this summary for the argument requirements.
> > Args:
> > x: A Tensor. Must be one of the following types: `bfloat16`,
> > `half`, `float32`, `float64`, `uint8`, `int8`, `uint16`,
> > `int16`, `int32`, `int64`, `complex64`, `complex128`.
> > y: A `Tensor`. Must have the same type as `x`.
> > name: A name for the operation (optional).
> > Returns:
> > A `Tensor`. Has the same type as `x`.
> > Raises:
> > 
> > * InvalidArgumentError: When `x` and `y` have incompatible shapes or types
> > 
> > This means that -y_true is 'y' and K.log(y_pred) is 'x'. To perform this operations you'll have to cast -y_true to a float32 or cast K.log(y_pred) to an int64 or cast them both into any other type as long as they match. .
> > It is Working now by doing `y_true = tf.cast(y_true, tf.float32)` >

I try to cast K.log(y_pred) to int32 but it did not work. here is the error message
SyntaxError: can't assign to function call

anybody knows why? please i need help
