### ISSUE TITLE
inconsistent behavior of model after creation vs. after loading from save file

### ISSUE THREAD

**Issue by WildTangles** [tensorflow/tensorflow#33088]
**System information**
- Have I written custom code: yes
- OS Platform and Distribution: Linux Ubuntu 18.04.2 LTS (Bionic Beaver)
- TensorFlow installed from (source or binary): pip install (binary?)
- TensorFlow version (use command below): 1.14.0
- Python version: 3.5.2
- Bazel version (if compiling from source): - 
- GCC/Compiler version (if compiling from source): - 
- CUDA/cuDNN version: - (running on cpu only)
- GPU model and memory: - (running on cpu only)

**Describe the current behavior**
When using lambda layers with parameters generated in a loop, creation-time behavior of model is different from behavior of model re-loaded from a save file.

**Describe the expected behavior**
Consistent behavior at creation-time of model and after re-loading from a save file.

**Code to reproduce the issue**
please see the short example test case here: https://github.com/WildTangles/tf-issues/blob/master/tensorflow_bug_lambdas/bug_demo.ipynb

(alternatively, please see the same notebook rendered on a different site here: https://nbviewer.jupyter.org/github/WildTangles/tf-issues/blob/master/tensorflow_bug_lambdas/bug_demo.ipynb)

In particular, see: 
cell 6 (expected output plotted by hand) vs. 
cell 7 (model behavior right after being created, matches expected) vs.
cell 10 (model behavior after being saved and re-loaded, does not match expected)

cell 4 (model definition, in particular, see first few lines with lambda layer parameters defined in a loop)

**Other info / logs**
Happy to provide if necessary.

**Comment by rmothukuru** [comment]
@WildTangles,
When trying to open the ipynb notebook, I am encountering the error as shown in the screenshot below:

![image](https://user-images.githubusercontent.com/48206667/66305817-c9c58800-e91d-11e9-9c70-bd952d3586a7.png)

Can you please link the notebook correctly and share it. Thanks!

**Comment by WildTangles** [comment]
> @WildTangles,
> When trying to open the ipynb notebook, I am encountering the error as shown in the screenshot below:
> 
> ![image](https://user-images.githubusercontent.com/48206667/66305817-c9c58800-e91d-11e9-9c70-bd952d3586a7.png)
> 
> Can you please link the notebook correctly and share it. Thanks!

Please see: https://nbviewer.jupyter.org/github/WildTangles/tf-issues/blob/master/tensorflow_bug_lambdas/bug_demo.ipynb

It's the same notebook, just now rendered on https://nbviewer.jupyter.org/.

**Comment by rmothukuru** [comment]
Could reproduce this issue with TF Version 1.15. Here is the [Gist](https://colab.sandbox.google.com/gist/rmothukuru/accc8dc92583c4dfc72280a95fa08734/33088.ipynb).

**Comment by gowthamkpr** [comment]
@WildTangles Thank you! Was able to reproduce the issue. Here are my github giste [[1]](https://colab.sandbox.google.com/gist/gowthamkpr/6f64fee3d7335016ae2b9bcb2d76b461/bug_demo.ipynb) and [[2]](https://colab.sandbox.google.com/gist/gowthamkpr/f19f60a8d5954c18531dee8595d22ba0/bug_demo.ipynb)

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.
