### ISSUE TITLE
tf silently rounding to integer when converting to PIL format

### ISSUE THREAD

**Issue by WildTangles** [tensorflow/tensorflow#33089]
**System information**
- Have I written custom code: not really, no.
- OS Platform and Distribution: Linux Ubuntu 18.04.2 LTS (Bionic Beaver)
- TensorFlow installed from (source or binary): pip install (binary?)
- TensorFlow version (use command below): 1.14.0
- Python version: 3.5.2
- Bazel version (if compiling from source): - 
- GCC/Compiler version (if compiling from source): - 
- CUDA/cuDNN version: - (running on cpu only)
- GPU model and memory: - (running on cpu only)

**Describe the current behavior**
When converting to PIL format from array and back, tf silently rounds values to integers. (see https://www.tensorflow.org/api_docs/python/tf/keras/preprocessing/image/array_to_img, https://www.tensorflow.org/api_docs/python/tf/keras/preprocessing/image/img_to_array)

**Describe the expected behavior**
Throw a warning when silently rounding. maybe convert to float instead of integer if input is a float dtype?

**Code to reproduce the issue**
please see the short example test case here: https://github.com/WildTangles/tf-issues/blob/master/tensorflow_bug_conversions/bug_demo.ipynb

In particular, see: 
cell 4 (random noise image, 4800 unique values) vs. 
cell 6 (image after conversion to PIL and back, 256 unique values)

**Other info / logs**
Happy to provide if necessary.

**Comment by rmothukuru** [comment]
@WildTangles,
The Notebook in the link, https://github.com/WildTangles/tf-issues/blob/master/tensorflow_bug_conversions/bug_demo.ipynb couldn't be opened.  It is resulting in an error as shown below. Can you please share the attachment. Thanks!

![image](https://user-images.githubusercontent.com/48206667/66914789-3125bb00-f035-11e9-8c19-8b7c0f126158.png)

**Comment by WildTangles** [comment]
@rmothukuru 
please see: https://nbviewer.jupyter.org/github/WildTangles/tf-issues/blob/master/tensorflow_bug_conversions/bug_demo.ipynb

It's the same notebook, just hosted on nbbiewer.jupyter.org.

**Comment by jvishnuvardhan** [comment]
@WildTangles I agree that there are only 256 unique values after conversion. However, there is not much information lost during conversion. [Here](https://colab.research.google.com/gist/jvishnuvardhan/4f8fb11eb5979db06468b1d277e9e439/untitled89.ipynb) is a gist for y/our reference. Thanks!

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.
