### ISSUE TITLE
hub.module_v2.load() returns a non-callable object

### ISSUE THREAD

**Issue by ifsheldon** [tensorflow/tensorflow#33083]
**System information**
- tf version: 2.0.0 gpu
- tf_hub version: 0.6
- python: 3.7 with Anaconda

```python
model = "https://tfhub.dev/google/imagenet/mobilenet_v2_140_224/feature_vector/3" # MobileNetV2
# both lines below cannot work
layer = hub.KerasLayer(model)
layer = hub.KerasLayer(model, tags="train")
```
Error messages are long, but those related to the issue are below:
```python
~\anaconda\envs\tf2\lib\site-packages\tensorflow_hub\keras_layer.py in __init__(self, handle, trainable, arguments, **kwargs)
    102       self._func = handle
    103     else:
--> 104       self._func = module_v2.load(handle)
    105       if not callable(self._func):
    106         raise ValueError("Non-callable result from hub.load('%s')" %
```
```python
ValueError: Importing a SavedModel with tf.saved_model.load requires a 'tags=' argument if there is more than one MetaGraph. Got 'tags=None', but there are 2 MetaGraphs in the SavedModel with tag sets [[], ['train']]. Pass a 'tags=' argument to load this SavedModel.
```
then I realized if we just directly use `hub.KerasLayer()`, the `'tags='` argument will not be passed to `module_v2.load()`, which causes this error.
So then I modified the codes as below:
```python
model = "https://tfhub.dev/google/imagenet/mobilenet_v2_140_224/feature_vector/3"
mod = hub.module_v2.load(model,tags=['train']) # this line works fine
layer = hub.KerasLayer(mod) # error here
```
Howerver, this won't work, either. The error messages related to the error are:
```
~\anaconda\envs\tf2\lib\site-packages\tensorflow_hub\keras_layer.py in __init__(self, handle, trainable, arguments, **kwargs)
    102       self._func = handle
    103     else:
--> 104       self._func = module_v2.load(handle)
    105       if not callable(self._func):
    106         raise ValueError("Non-callable result from hub.load('%s')" %
```
and
```python
AttributeError: 'AutoTrackable' object has no attribute 'startswith'
```
It seems that it is related to the code in `keras_layer.py` and specificly codes below:
```python
def __init__(self, handle, trainable=False, arguments=None, **kwargs):
    self._handle = handle
    # Resolve the handle to a callable `func`.
    if callable(handle):
      self._func = handle
    else:
      self._func = module_v2.load(handle)
      if not callable(self._func):
           raise ValueError("Non-callable result from hub.load('%s')" %
                         str(handle))
```
When I pass the `mod` object to `hub.KerasLayer()`, the code in `if` branch is expected to be executed, but the code in `else` branch is executed, which means the `mod` object returned by  `module_v2.load()` is not `callable`. That doesn't make sense. 
So I wonder maybe it is a bug or there's something wrong with the `MobileNet` model or it just that the model doesn't fit in TF2.0.

**Comment by rmothukuru** [comment]
@ifsheldon,
This issue is not related to Tensorflow, but it is related to Tensorflow Hub. Request you to raise an issue in [Tensorflow Hub Repo](https://github.com/tensorflow/hub/issues).  Thanks!

**Comment by ifsheldon** [comment]
> @ifsheldon,
> This issue is not related to Tensorflow, but it is related to Tensorflow Hub. Request you to raise an issue in [Tensorflow Hub Repo](https://github.com/tensorflow/hub/issues). Thanks!

Sorry, and thanks.
