### ISSUE TITLE
tf.data.Dataset.from_generator is not executing eagerly 

### ISSUE THREAD

**Issue by muleyprasad** [tensorflow/tensorflow#33082]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Colab
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version (use command below): 2
- Python version: 3

**Describe the current behavior**

`tf.data.Dataset.from_generator` method is not hydrating the dataset eagerly.  When a dataset is created using this method an instance of `DatasetV1Adapter` is returned rather than `DataSet`. 

**Describe the expected behavior**

Should return a `Dataset` [Reference](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/data/ops/dataset_ops.py#L510)

**Code to reproduce the issue**

[Colab link](https://colab.research.google.com/drive/1jPS1oVrFlWOzJmUFCaDMFwVUVbg9V1NK)

```

# Set up and ensure tf is executing eagerly


import tensorflow as tf

print(tf.__version__)
print(tf.executing_eagerly())

# Define a generator function and create dataset
# you would expect ds have data after from_generator method as it's expected to execute eagerly, but data generation logs are not printed

def gen():
  print('Log: generating data')
  for i in range(0,5):
    yield (i, [1] * i)

ds = tf.data.Dataset.from_generator(gen, (tf.int64, tf.int64), (tf.TensorShape([]), tf.TensorShape([None])))
tf.print(ds)

# Use dataset
# Logs are printed here

for (x,y) in ds:
  tf.print(x, y)

# Use ds one more time
# Now ds is hydrated but generator function is invoked again

x = ds.take(3)
print(x)
for value in x:
  tf.print(value)

```

**Comment by rmothukuru** [comment]
@muleyprasad,
`DatasetV1Adapter` is representation of `Dataset`.

Please refer [this code](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/data/ops/dataset_ops.py#L1916-L1918),  Thanks!

**Comment by muleyprasad** [comment]
Ok. Then I believe DatasetV1Adapter is just holding the reference of the generator function so data can be generated for any iter like operation rather than loading it eagerly inline as other load data methods would do, is it correct?

**Comment by rmothukuru** [comment]
Could reproduce with Tensorflow Version 2.0. Here is the [Gist](https://colab.sandbox.google.com/gist/rmothukuru/0a08de564446dddc5d3f519ec4460e54/33082.ipynb#scrollTo=wTIeK-qM8wox).

**Comment by gowthamkpr** [comment]
@muleyprasad `tf.data.Dataset.from_generator ` Creates a Dataset whose elements are generated by generator. And Dataset is always loaded lazily as you can see [here](# Loaded lazily due to a circular dependency (roughly). So, its not a surprise here and the answer for your question is "yes".
