### ISSUE TITLE
possible file name typo in raspberry pi example

### ISSUE THREAD

**Issue by glw** [tensorflow/tensorflow#33099]
## URL(s) with the issue:
https://github.com/tensorflow/examples/tree/master/lite/examples/object_detection/raspberry_pi

## Description of issue (what needs changing):
Near the bottom of the instruction on speeding up inference it reads
```python3 classify_picamera.py \```

Based on the files in that example folder should that instead read
```python3 detect_picamera.py \```

### Clear description
If my assumption above is incorrect, then its unclear where the file ```classify_pycamera.py``` is coming from, and should maybe be explicitly mentioned.

### Submit a pull request?
I didnt plan to since its possibly a simple typo. But I can if you'd like.

**Comment by MarkDaoust** [comment]
Thanks @glw, 

I'm sending a fix, but in the future remember that you can too. Github's edit button makes  PRs for simple fixes like this with out leaving your browser.

**Comment by glw** [comment]
@MarkDaoust - ahh I wasnt aware of that. Thanks! I will do that for future minor issues.

**Comment by dubesar** [comment]
@MarkDaoust this issue seems to be solved.

**Comment by MarkDaoust** [comment]
Thanks.
