### ISSUE TITLE
Prebuilt libtensorflow (C API)

### ISSUE THREAD

**Issue by jtavrisov** [tensorflow/tensorflow#33092]
The link in 
https://www.tensorflow.org/install/lang_c

contain the 1.14 library. Are there any prebuilt link for the C API for 2.0 stable?

This also holds true for the install for java page

**Comment by joaquimvila** [comment]
When it is expected for the C API to be supported for 2.0? Is there any scheduling about it? Thanks.

**Comment by grantstephens** [comment]
Also run into this. With the recent security issue with 1.13 we now want to upgrade but can't due to there being no libtensorflow for v2.0 and its not worth all the change to go stay on v1.
We tried to compile it ourselves, but that failed too.
I also don't know if this should have the docs label.

**Comment by JustinWick** [comment]
Multiple teams I work with at my employer require the C API, either to use in a native project, or for the Java API. We are also all wondering when the C API support will be added to TF 2.x. I've been unable to find out where this status information is kept.

Does anyone know what's broken, or what's holding this up? Are there any concrete plans on fixing those issues? I don't mind compiling myself, but I would hate to deploy something to a customer only to find out that the TensorFlow team does not support the C API officially.

**Comment by gunan** [comment]
Thanks for raising this.
Our guarantees on our APIs are outlined here:
https://www.tensorflow.org/guide/versions

To summarize the C\C++ aspect.
The headers under `tensorflow/c`, except the ones that have `internal` in the name are not expected to change. Only in cases of bugs, or extraordinary changes we expect changes here.
We are working to expand this, and add more features there.
Any other headers in TF currently are not under any compatibility guarantees. While we understand that a lot of our users need to use them, they may change.

For the prebuilt packages, it is in our short term plans to fix them. Hopefully, soon after 2.2 final is released we can get to them, and push them out.

**Comment by JustinWick** [comment]
@gunan:
Thanks for your comprehensive reply. We look forward to the next prepackaged update!

Is the C API otherwise working for 2.0 and 2.1 if  one builds it themselves? We build TF from source for some of our projects, and as long as it's still functional we don't have to wait for the prepackaged version, though some teams do prefer those as they are standard.

**Comment by gunan** [comment]
In theory, it should. We do run the tests on C API headers in our CI.
If there are any bugs, or issues  you run into, we would love to hear about them and fix them.

**Comment by kumariko** [comment]
@jtavrisov We are checking to see if you still need help on this issue. Could you please check with latest stable version of TF which is `TF2.7` ? please check document [link](https://www.tensorflow.org/install/lang_c) and https://github.com/tensorflow/tensorflow/issues/33092#issuecomment-613804129 . Thanks
