### ISSUE TITLE
1:1 between internal and external commits

### ISSUE THREAD

**Issue by davidzchen** [tensorflow/tensorflow#331]
Currently, it seems that the internal commits to TensorFlow are generally exported to the GitHub repository in batches.

We have some infrastructure set up for bazelbuild/bazel for both importing external patches into the internal repository and pushing internal commits to the GitHub repository, scrubbing any sensitive information from commit messages. Perhaps we can sync offline to see if we can use the tools for TensorFlow and then rewrite the Git history, especially given #294.

Related: #26

**Comment by vrv** [comment]
Thanks -- we're working on this internally and we're pretty close to something that works for us. De-duping with https://github.com/tensorflow/tensorflow/issues/26

**Comment by davidzchen** [comment]
Ah got it. Good to hear!

**Comment by vrv** [comment]
FYI, we're now writing individual commits for each of our internal changes -- it's working reasonably well so far.
