### ISSUE TITLE
Tensorflow 2.0 - bazel build from source fails (can't exec cc1plus)

### ISSUE THREAD

**Issue by lutel** [tensorflow/tensorflow#33108]
**System information**
System: Gentoo
Tensorflow 2.0, 1.14
Python 3.6
Installed from source
Bazel 0.26.1
GCC 8.3.0, 7.4.0 (both fails, both have c++ installed - /usr/libexec/gcc/x86_64-pc-linux-gnu/8.3.0/cc1plus)
CUDA 10.1
CuDNN 7.6.4

```
# bazel build --config=v2 //tensorflow/tools/pip_package:build_pip_package

...

INFO: Analyzed target //tensorflow/tools/pip_package:build_pip_package (278 packages loaded, 21924 targets configured).
INFO: Found 1 target...
ERROR: /w/pip/.cache/bazel/_bazel_pip/667008e4969ed3eba4f1f491903cb254/external/com_google_protobuf/BUILD:106:1: C++ compilation of rule '@com_google_protobuf//:protobuf_lite' failed (Exit 1)
gcc: error trying to exec 'cc1plus': execvp: No such file or directory
Target //tensorflow/tools/pip_package:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.

```

g++ is installed on system...

```
 # g++ --print-prog-name=cc1plus
/usr/libexec/gcc/x86_64-pc-linux-gnu/8.3.0/cc1plus
```

Please help, I get the same error for every other release.

**Comment by mihaimaruseac** [comment]
Most likely `cc1plus` is not on a path that is visible in `PATH` envvar that Bazel uses. To check, compare the output of `which cc1plus` with the output that you'd get from running `bazel run :test_path` on a new project with

```bazel
sh_binary(name="test_path", srcs=["test_path.sh"])
```

and

```bash
#!/bin/bash
echo $PATH
```

**Comment by lutel** [comment]
Thanks! I've added /usr/libexec/gcc/x86_64-pc-linux-gnu/8.3.0 to the PATH, but now I'm getting errors for header files, should I set some environment variable or set it during ./configuration? 

```
ERROR: /w/pip/.cache/bazel/_bazel_pip/667008e4969ed3eba4f1f491903cb254/external/com_googlesource_code_re2/BUILD:26:1: C++ compilation of rule '@com_googlesource_code_re2//:re2' failed (Exit 1): crosstool_wrapper_driver_is_not_gcc failed: error executing command
  (cd /w/pip/.cache/bazel/_bazel_pip/667008e4969ed3eba4f1f491903cb254/execroot/org_tensorflow && \
  exec env - \
    LD_LIBRARY_PATH=/usr/lib64/gcc/x86_64-pc-linux-gnu/8.3.0/include/g++-v8 \
    PATH=/usr/lib/llvm/8/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/bin:/opt/cuda/bin:/opt/cuda/libnvvp:/usr/libexec/gcc/x86_64-pc-linux-gnu/8.3.0:/usr/lib64/gcc/x86_64-pc-linux-gnu/8.3.0/include/g++-v8/ \
    PWD=/proc/self/cwd \
  external/local_config_cuda/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc -MD -MF bazel-out/host/bin/external/com_googlesource_code_re2/_objs/re2/bitstate.pic.d '-frandom-seed=bazel-out/host/bin/external/com_googlesource_code_re2/_objs/re2/bitstate.pic.o' -D__CLANG_SUPPORT_DYN_ANNOTATION__ -iquote external/com_googlesource_code_re2 -iquote bazel-out/host/bin/external/com_googlesource_code_re2 -iquote external/com_google_absl -iquote bazel-out/host/bin/external/com_google_absl '-std=c++11' -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -fPIC -U_FORTIFY_SOURCE '-D_FORTIFY_SOURCE=1' -fstack-protector -Wall -fno-omit-frame-pointer -no-canonical-prefixes -fno-canonical-system-headers -DNDEBUG -g0 -O2 -ffunction-sections -fdata-sections -g0 -g0 -pthread -c external/com_googlesource_code_re2/re2/bitstate.cc -o bazel-out/host/bin/external/com_googlesource_code_re2/_objs/re2/bitstate.pic.o)
Execution platform: @bazel_tools//platforms:host_platform
external/com_googlesource_code_re2/re2/bitstate.cc:20:10: fatal error: stddef.h: No such file or directory
 #include <stddef.h>
          ^~~~~~~~~~
compilation terminated.
Target //tensorflow/tools/pip_package:build_pip_package failed to build
```

**Comment by mihaimaruseac** [comment]
I think it's better to set everything up during `./configure`. Otherwise you have to set up all kind of env vars for binaries, include paths, library paths, etc. In that case, this is not a supported usecase and would be better to continue that approach on StackOverflow as it is all a configuration issue.

**Comment by lutel** [comment]
I couldn't set it during configure, I've tried to set it through CPATH or CPLUS_INCLUDE_PATH but to no success.

**Comment by mihaimaruseac** [comment]
Unfortunately, you'll have to ask for help on StackOverflow, as we cannot support all build configurations.

**Comment by lutel** [comment]
I could build Tensorflow on Gentoo, isn't this problem with bazel or some build scripts? Could your post what are your environmental variables set for building TF from source?

**Comment by lutel** [comment]
I've tried to pass path through CPATH, C_INCLUDE_PATH, CPLUS_INCLUDE_PATH, LD_LIBRARY_PATH, TF_CUDA_PATHS - it doesn't work. Build fails because header files can not be found, although they are all present in /usr/lib64/gcc/x86_64-pc-linux-gnu/8.3.0/include/g++-v8. Also gcc is compiled to include this path:
```

sing built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-pc-linux-gnu/8.3.0/lto-wrapper
Target: x86_64-pc-linux-gnu
Configured with: /tmp/portage/sys-devel/gcc-8.3.0-r1/work/gcc-8.3.0/configure --host=x86_64-pc-linux-gnu --build=x86_64-pc-linux-gnu --prefix=/usr --bindir=/usr/x86_64-pc-linux-gnu/gcc-bin/8.3.0 --includedir=/usr/lib/gcc/x86_64-pc-linux-gnu/8.3.0/include --datadir=/usr/share/gcc-data/x86_64-pc-linux-gnu/8.3.0 --mandir=/usr/share/gcc-data/x86_64-pc-linux-gnu/8.3.0/man --infodir=/usr/share/gcc-data/x86_64-pc-linux-gnu/8.3.0/info **--with-gxx-include-dir=/usr/lib/gcc/x86_64-pc-linux-gnu/8.3.0/include/g++-v8** --with-python-dir=/share/gcc-data/x86_64-pc-linux-gnu/8.3.0/python --enable-languages=c,c++,fortran --enable-obsolete --enable-secureplt --disable-werror --with-system-zlib --enable-nls --without-included-gettext --enable-checking=release --with-bugurl=https://bugs.gentoo.org/ --with-pkgversion='Gentoo Hardened 8.3.0-r1 p1.1' --enable-esp --enable-libstdcxx-time --disable-libstdcxx-pch --enable-shared --enable-threads=posix --enable-__cxa_atexit --enable-clocale=gnu --disable-multilib --with-multilib-list=m64 --disable-altivec --disable-fixed-point --enable-targets=all --enable-libgomp --disable-libmudflap --disable-libssp --disable-libmpx --disable-systemtap --enable-vtable-verify --enable-lto --without-isl --enable-default-pie --enable-default-ssp
Thread model: posix
gcc version 8.3.0 (Gentoo Hardened 8.3.0-r1 p1.1)
```
I've tried passing -I /usr/lib64/gcc/x86_64-pc-linux-gnu/8.3.0/include/g++-v8 as optimization flag to gcc - still doesn't work. It looks like the wrapper doesn't know how to handle Gentoo toolchain properly. 

```
ERROR: /w/pip/.cache/bazel/_bazel_pip/667008e4969ed3eba4f1f491903cb254/external/zlib_archive/BUILD.bazel:5:1: C++ compilation of rule '@zlib_archive//:zlib' failed (Exit 1): crosstool_wrapper_driver_is_not_gcc failed: error executing command
  (cd /w/pip/.cache/bazel/_bazel_pip/667008e4969ed3eba4f1f491903cb254/execroot/org_tensorflow && \
  exec env - \
    LD_LIBRARY_PATH=/usr/lib64/gcc/x86_64-pc-linux-gnu/8.3.0/include/g++-v8 \
    PATH=/usr/lib/llvm/8/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/bin:/opt/cuda/bin:/opt/cuda/libnvvp:/usr/libexec/gcc/x86_64-pc-linux-gnu/8.3.0 \
    PWD=/proc/self/cwd \
  external/local_config_cuda/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc -MD -MF bazel-out/host/bin/external/zlib_archive/_objs/zlib/crc32.d '-frandom-seed=bazel-out/host/bin/external/zlib_archive/_objs/zlib/crc32.o' -iquote external/zlib_archive -iquote bazel-out/host/bin/external/zlib_archive -isystem external/zlib_archive -isystem bazel-out/host/bin/external/zlib_archive -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -fPIE -U_FORTIFY_SOURCE '-D_FORTIFY_SOURCE=1' -fstack-protector -Wall -fno-omit-frame-pointer -no-canonical-prefixes -fno-canonical-system-headers -DNDEBUG -g0 -O2 -ffunction-sections -fdata-sections -g0 '-march=native' -Wno-shift-negative-value -DZ_HAVE_UNISTD_H -c external/zlib_archive/crc32.c -o bazel-out/host/bin/external/zlib_archive/_objs/zlib/crc32.o)
Execution platform: @bazel_tools//platforms:host_platform
In file included from external/zlib_archive/zlib.h:34,
                 from external/zlib_archive/zutil.h:22,
                 from external/zlib_archive/crc32.c:31:
external/zlib_archive/zconf.h:247:14: fatal error: stddef.h: No such file or directory
```

I ran out of ideas how can I compile Tensorflow.

**Comment by mihaimaruseac** [comment]
Adding @perfinion in case he or SIG Build can help

**Comment by lutel** [comment]
Please help Allmighty Devs

**Comment by paulbors** [comment]
Also see:
https://forums.gentoo.org/viewtopic-t-1104292.html

The version of Bazel that Tensorflow requires is not AMD64 stable as per:
https://packages.gentoo.org/packages/dev-util/bazel

Bug report around Bazel:
https://bugs.gentoo.org/buglist.cgi?quicksearch=bazel

**Comment by paulbors** [comment]
This has been patched in Gentoo Linux on top of Bazel v1.2.0 here:
https://gitweb.gentoo.org/repo/gentoo.git/tree/dev-util/bazel/files/1.2.0-grpc-gettid.patch?id=27d3e4549dfcbc89442c54b4e5c602b274284203

Backported to Bazel v0.29.1 here:
https://github.com/paulbors/gentoo-localrepo/tree/master/dev-util/bazel

If you're not running Gentoo, a similar patch can be ported over to your distro if one hasn't been created already.

**Comment by perfinion** [comment]
Whoops, sorry I didn't see this issue earlier. I maintain the Gentoo TF package too.
If you're on gentoo, you should just `emerge sci-libs/tensorflow`, is there some specific reason you're trying to build manually not just using the one in portage? The package for it should handle all the right versions of bazel and cuda and everything else. If you need other features that are not in the package let me know and I might be able to add them :)

As for actually building yourself. You shouldnt need to do anything strange with the linker flags or anything like that. If you're doing a cpu build everything will just work with the defaults from the `./configure` script. If you're doing a cuda build, you'll need to set the gcc path to the full one:

`export GCC_HOST_COMPILER_PATH="/usr/x86_64-pc-linux-gnu/gcc-bin/8.3.0/x86_64-pc-linux-gnu-gcc"` before `./configure` then it'll work. (cuda isnt compatible with gcc9 yet so you've gotta use gcc8). `/usr/bin/gcc` is a link to that longer gcc path and nvcc has issues with it, so pass that long one and everything works fine. (this should only apply for cuda builds, non-cuda are much easier)

**Comment by paulbors** [comment]
Read above comments and please update Gentoo's ebuild to use latest stable version of Bazel v1.2.0+

This has been patched in Gentoo Linux on top of Bazel v1.2.0 here:
https://gitweb.gentoo.org/repo/gentoo.git/tree/dev-util/bazel/files/1.2.0-grpc-gettid.patch

**Comment by paulbors** [comment]
To clarify, Gentoo builsd from source via the ebuld file (no need to go through your manual steps as per your latest instrustions). After all you gave us an ebuild ;)

The problem is a dependency of Tensorflow on an older buggy version of Bazel (which is no longer the right bersion at older v0.29.1 as that's super old).

Here's the direct link on how to patch the bug reported in this ticket in Bazel v0.29.1:
https://github.com/paulbors/gentoo-localrepo/blob/master/dev-util/bazel/files/0.29.1-grpc-gettid.patch

However, Tensorflow should move on and catch up with its build system and use the latest stable version of Bazel.

Alao, I don't understand why Tensorflow is packaging 3rd party libraries? Did you guys modify the source code of said 3rd party libraries? Why not use a dependency management library? What happens when a 3rd party library has a defect (such as Bazel v0.29.1 which is causing this "can't exec cc1plus")? Are you guys going to patch the 3rd party library for your users?

**Comment by mohantym** [comment]
Hi @lutel! , we are  checking to see if you are still looking for assistance in this issue.
Could  you try with [tested configurations ](https://www.tensorflow.org/install/source#tested_build_configurations)again ?
