### ISSUE TITLE
warning when running commands with bazel

### ISSUE THREAD

**Issue by Su-Jin2** [tensorflow/tensorflow#3310]
Hello, I'm installing tensorflow following instructions of
https://www.tensorflow.org/versions/r0.9/get_started/os_setup.html
especially in "Installing from sources"

I almost encountered the below warnings when running commands with bazel
Among the warnings, I'd like to resolve the warning which says 'in includes attribute of cc_library rule //****' resolves to '****' not in 'third_party'. This will be an error in the future.'

btw, what does the above warnings mean and why was the warnings occurred?
As I saw other person's console outputs through googling, many people also went through the warnings. However, many of them seem to ignore them.
I'm a little concerned because of the final sentence saying 'This will be an error in the future'
I'd appreciate any reply, thank you very much

### Environment info
Operating System: Ubuntu 14.04
Linux seslab86 3.16.0-76-generic #98~14.04.1-Ubuntu SMP Fri Jun 24 17:04:54 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

Installed version of CUDA and cuDNN: 7.5
(please attach the output of `ls -l /path/to/cuda/lib/libcud*`):
  316 -rw-r--r-- 1 root root   322936  8월 16  2015 /usr/local/cuda/lib64/libcudadevrt.a
    0 lrwxrwxrwx 1 root root       16  8월 16  2015 /usr/local/cuda/lib64/libcudart.so -> libcudart.so.7.5
    0 lrwxrwxrwx 1 root root       19  8월 16  2015 /usr/local/cuda/lib64/libcudart.so.7.5 -> libcudart.so.7.5.18
  376 -rwxr-xr-x 1 root root   383336  8월 16  2015 /usr/local/cuda/lib64/libcudart.so.7.5.18
  704 -rw-r--r-- 1 root root   720192  8월 16  2015 /usr/local/cuda/lib64/libcudart_static.a
    0 lrwxrwxrwx 1 root root       13  4월 11 01:10 /usr/local/cuda/lib64/libcudnn.so -> libcudnn.so.5
60020 -rwxr-xr-x 1 root root 61453024  6월  1 22:42 /usr/local/cuda/lib64/libcudnn.so.4
60020 -rwxr-xr-x 1 root root 61453024  6월  1 22:42 /usr/local/cuda/lib64/libcudnn.so.4.0.7
    0 lrwxrwxrwx 1 root root       17  4월 11 01:10 /usr/local/cuda/lib64/libcudnn.so.5 -> libcudnn.so.5.0.4
60016 -rwxr-xr-x 1 root root 61453024  6월  1 22:42 /usr/local/cuda/lib64/libcudnn.so.5.0.4
60576 -rw-r--r-- 1 root root 62025862  6월  1 22:42 /usr/local/cuda/lib64/libcudnn_static.a

If installed from binary pip package, provide:

1. Which pip package you installed.
2. The output from `python -c "import tensorflow; print(tensorflow.__version__)"`.

If installed from sources, provide the commit hash:

### Steps to reproduce
1.
2.
3.

### What have you tried?
1. bazel build -c opt --config=cuda //tensorflow/tools/pip_package:build_pip_package

### Logs or other output that would be helpful
(If logs are large, please upload as attachment).

WARNING: /home/sujin/.cache/bazel/_bazel_sujin/a8907e64af45524f9c5b5e83198958ce/external/grpc/WORKSPACE:1: Workspace name in /home/sujin/.cache/bazel/_bazel_sujin/a8907e64af45524f9c5b5e83198958ce/external/grpc/WORKSPACE (@__main__) does not match the name given in the repository's definition (@grpc); this will cause a build error in future versions.
WARNING: /home/sujin/.cache/bazel/_bazel_sujin/a8907e64af45524f9c5b5e83198958ce/external/re2/WORKSPACE:1: Workspace name in /home/sujin/.cache/bazel/_bazel_sujin/a8907e64af45524f9c5b5e83198958ce/external/re2/WORKSPACE (@__main__) does not match the name given in the repository's definition (@re2); this will cause a build error in future versions.

WARNING: /home/sujin/Desktop/tensorflow/util/python/BUILD:11:16: in includes attribute of cc_library rule //util/python:python_headers: 'python_include' resolves to 'util/python/python_include' not in 'third_party'. This will be an error in the future.
WARNING: /home/sujin/Desktop/tensorflow/google/protobuf/BUILD:59:16: in includes attribute of cc_library rule //google/protobuf:protobuf_lite: 'src/' resolves to 'google/protobuf/src' not in 'third_party'. This will be an error in the future.
WARNING: /home/sujin/Desktop/tensorflow/google/protobuf/BUILD:124:16: in includes attribute of cc_library rule //google/protobuf:protobuf: 'src/' resolves to 'google/protobuf/src' not in 'third_party'. This will be an error in the future.
WARNING: /home/sujin/Desktop/tensorflow/google/protobuf/BUILD:546:16: in includes attribute of cc_binary rule //google/protobuf:pyext/_message.so: 'python/' resolves to 'google/protobuf/python' not in 'third_party'. This will be an error in the future.
WARNING: /home/sujin/Desktop/tensorflow/google/protobuf/BUILD:546:16: in includes attribute of cc_binary rule //google/protobuf:pyext/_message.so: 'src/' resolves to 'google/protobuf/src' not in 'third_party'. This will be an error in the future.
WARNING: /home/sujin/Desktop/tensorflow/google/protobuf/BUILD:266:16: in includes attribute of cc_library rule //google/protobuf:protoc_lib: 'src/' resolves to 'google/protobuf/src' not in 'third_party'. This will be an error in the future.

**Comment by jmchen-g** [comment]
@martinwicke Could you take a look at this please?

**Comment by martinwicke** [comment]
I would not worry about these just yet. We'll have to change things in order to conform to future bazel versions. @damienmg, is this something we can change now (or do we have to change things in protobuf?)
