### ISSUE TITLE
How can I update my existing tensorflow to 2.0?

### ISSUE THREAD

**Issue by AllenWu18** [tensorflow/tensorflow#33102]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): macOS 10.14.6
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): source
- TensorFlow version:1.13.0-rc2 --->2.0
- Python version:3.7.1
- Installed using virtualenv? pip? conda?:pip/conda
- Bazel version (if compiling from source):\
- GCC/Compiler version (if compiling from source):\
- CUDA/cuDNN version:\
- GPU model and memory:\

**Describe the problem**
 
Well, I have installed the tensorflow 1.13 before, and since the newest version 2.0 is open, I wanna to update my old tf to the new one, but I do not know how to do it stably. 
Can you help me?
Very THX! :)

**Comment by pandrey-fr** [comment]
You should be able to simply `pip install --user tensorflow==2.0.0` (or `tensorflow-gpu==2.0.0`).

That being said, if you have some code depending on the former TF1.13 version, you might not want to wipe the latter out entirely. It may therefore be useful to set up a virtual environment (`python3 -m venv your_venv_path`), activate it (`source your_venv_path/bin/activate`) and then pip install any version of tensorflow within this environment. This way you can have multiple TF versions on your computer, and use whichever is suited for you current project by switching between venvs.

**Comment by rmothukuru** [comment]
Thank you @pandrey-fr for pitching in. 
@AllenWu18,
Can you please let us know if @pandrey-fr's comment has helped you. Thanks!

**Comment by mihaimaruseac** [comment]
You can also see the [`tf_upgrade_v2` script](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/tools/compatibility) to upgrade existing code

**Comment by AllenWu18** [comment]
OK I'll have a try under the advice of @pandrey-fr, and I wanna to build a virtual python environment firstly. Should I build it in the Anaconda environment?

**Comment by AllenWu18** [comment]
> You can also see the [`tf_upgrade_v2` script](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/tools/compatibility) to upgrade existing code

Most of my code was written under Keras, and I want to know has Keras been updated at the same time the TF 2.0 was opened??

**Comment by pandrey-fr** [comment]
> Most of my code was written under Keras, and I want to know has Keras been updated at the same time the TF 2.0 was opened??

In 2.0, tensorflow embarks an implementation of the keras API under the `tensorflow.keras` submodule, thus you no longer need to use the separate keras package, and should simply adjust your code to use the embarked API.

> I wanna to build a virtual python environment firstly. Should I build it in the Anaconda environment?
You can either use `conda` or `venv` (or other virtual environment management tools) to create your virtual environment. If you usually use anaconda to install packages, using it to manage virtual environments seems logical ; at any rate, do not mix the ways you manage your environments and pacakge, otherwise it may be hard to keep track of what is installed where :-)

**Comment by gadagashwini** [comment]
@AllenWu18, Follow these steps to install tensorflow 2.0 with PIP virtualenv
```
$pip install virtualenv
$virtualenv tf_2.0.0   # tf_2.0.0 is virtual env name
$source tf_2.0.0/bin/activate
tf_2.0.0 $ pip install tensorflow==2.0.0

```

**Comment by AllenWu18** [comment]
Sorry I forgot to reply.It works. Thank you very much!
:)


| |
allenwu18
邮箱：allenwu18@163.com
|

Signature is customized by Netease Mail Master

On 10/24/2019 17:30, gadagashwini wrote:

@AllenWu18, Is this still an issue? Thanks

**Comment by mihaimaruseac** [comment]
Thank you. closing

**Comment by bozcani** [comment]
You can also follow these steps to install tensorflow2.0 (GPU version) for conda environment.

```
$conda create -n new_tf2_env python=3.7
$conda activate new_tf2_env
$pip install tf-nightly-gpu-2.0-preview==2.0.0.dev20190526
```
