### ISSUE TITLE
Object Detection API Training fails with: Cuda call failed with an illegal memory access on TF1.15rc3

### ISSUE THREAD

**Issue by Atharex** [tensorflow/tensorflow#33117]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Using legacy train.py script from Object Detection API
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux CentOS 7.6
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below):  v1.15.0-rc2-8-g776451109a 1.15.0-rc3
- Python version: 3.6.8
- Bazel version (if compiling from source): "https://github.com/bazelbuild/bazel/releases/download/0.24.1/bazel-0.24.1-installer-linux-x86_64.sh"
- GCC/Compiler version (if compiling from source): GCC 6.5.0
- CUDA/cuDNN version: CUDA "10.0", cuDNN "7-7.6.4.38-1.cuda10.0"
- GPU model and memory: "NVIDIA Tesla K80, 11441MiB"

**Describe the current behavior**
The training from this source compiled binary starts successfully, but dies after some iterations.

**Describe the expected behavior**
The training commences and finishes normally.

**Code to reproduce the issue**
Compile the current r1.15 release candidate and use the train.py script from the OD API to train a model.

**Other info / logs**
The training works with an official pip release of tensorflow 1.14 package, but fails with the compiled new version. Here is the log output of the run: Also start up seems to be incredibly slow (almost 60 seconds for the first iteration)
[tf_err_log.txt](https://github.com/tensorflow/tensorflow/files/3698811/tf_err_log.txt)

**Comment by gowthamkpr** [comment]
@Atharex Can you please provide a github gist for us to reproduce the issue? Thanks!

**Comment by Atharex** [comment]
Sorry for the late response, had a bad case of the flu this week.

Not sure how to do this on gist, but I can give you the Dockerfile to build the same image as I'm using and the log output of the OD API train script.

[Dockerfile.txt](https://github.com/tensorflow/tensorflow/files/3724535/Dockerfile.txt) (the nvidia files you would have to put in manually)
[tf_err_log.txt](https://github.com/tensorflow/tensorflow/files/3724537/tf_err_log.txt)

I'm using the [SSD Mobilenet v2 config](https://github.com/tensorflow/models/blob/master/research/object_detection/samples/configs/ssd_mobilenet_v2_coco.config) model for the training (works normally on official TF1.14 pip installation) 

And the training script is invoked like this:
`python3 /tensorflow/train.py --logtostderr --train_dir=/training_dataset/ --pipeline_config_path=/training_dataset/model.config`

**Comment by Atharex** [comment]
Still happening with the official 1.15.0 release :/

**Comment by Atharex** [comment]
@gowthamkpr were you able to reproduce the issue? Do you need more info?

**Comment by gowthamkpr** [comment]
@Atharex I was not able to reproduce the issue. Will look into it further and will get back to you. If you can implement this using google colab and share a github gist, it would be helpful. thanks!

**Comment by Atharex** [comment]
Is it possible to install a custom built tensorflow package onto google colab? 
Sadly I'm not familiar with gists :/ What should I put in there, besides my build steps?

**Comment by gowthamkpr** [comment]
@Atharex you can try following the steps from this [tutorial](https://medium.com/@moshe.livne/training-tensorflow-for-free-pet-object-detection-api-sample-trained-on-google-collab-c2e65f4a9949) and just test it on 1.15rc3 and let me know if its still an issue. Thanks!

**Comment by gowthamkpr** [comment]
Closing this issue as it has been inactive for almost a week. Please add additional comments and we can open this issue again. Thanks!
