### ISSUE TITLE
Link broken

### ISSUE THREAD

**Issue by wardVD** [tensorflow/tensorflow#33112]
The link on the following line is broken: https://github.com/tensorflow/docs/blob/master/site/en/tutorials/load_data/csv.ipynb?short_path=443a7a7#L360

**Comment by mihaimaruseac** [comment]
Seems to be working for me.

**Comment by gowthamkpr** [comment]
Its working for me too.

**Comment by gowthamkpr** [comment]
Closing this issue as its not an issue. Please add additional comments and we can open this issue again. Thanks!
