### ISSUE TITLE
drawing random numbers in a loop

### ISSUE THREAD

**Issue by matthiasreisser** [tensorflow/tensorflow#3312]
Hey tf-community,

Please consider the following example:
`import tensorflow as tf`
`x = tf.random_normal(shape=(1,), mean=0.0, stddev=1.0)`
`sess = tf.Session()`
`sess.run([x for _ in xrange(4)])`

This results in a list of four identical numbers. What I would expect, however, is a list of 4 independently drawn numbers. Is this behaviour by design? And if so, is there a way to specify that I would like to have four different numbers? 

Drawing a vector of numbers is not applicable to my situation...

Thx,
Mat

**Comment by jmchen-g** [comment]
Can you give it a different seed everytime you call it? Maybe related to the time.

**Comment by shekkizh** [comment]
You are just fetching the value for **x** 4 times when you running the session. The session run is not sampling from the normal distribution every time.

Instead something like below will work?!
`x = tf.random_normal(shape=(4,), mean=0.0, stddev=1.0)
sess = tf.Session()
sess.run(x)`

**Comment by ptc-swalk** [comment]
For completeness, if you were to draw actually multiple times in different calls to sess.run like in `[sess.run(x) for _ in xrange(4)]`, you'd also get four different random numbers, or if you had different tensors (`x = [tf.random_normal(shape=(1,), mean=0.0, stddev=1.0) for _ in xrange(4)]; sess.run(x)`) - like @shekkizh says you have just one tensor (which has exactly one value during a computation) and read out its value 4 times.

**Comment by matthiasreisser** [comment]
Thx for the replies. Although they explain what is happening, they do not provide me with a solution to my problem.  
What I am trying to do is to sample repeatedly from a model I trained and to compute, for example, the average of the individual results. For simplicity and maybe efficiency in my code, I thought it might be possible to avoid doing a '[sess.run(x) for _ in xrange(4)]' call, which is what I have been doing so far.
