### ISSUE TITLE
TensorflowLite Upsampling2D does not change output shape when resize_input_tensor is called

### ISSUE THREAD

**Issue by stephen-systemfriend** [tensorflow/tensorflow#33127]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes (code can be found here https://github.com/benjamintanweihao/YOLOv3)
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows, but probably all
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 1.14.0
- Python version: 3.7.3
- CUDA/cuDNN version: 10.0
- GPU model and memory: NVIDIA GTX 1070 8GB

**Describe the current behavior**
Upsampling 2D set to twice the size of the input always outputs the size set at convert time, even when resize inputs are called.

**Describe the expected behavior**
Upsampling2D outputs size times the size of the new input

**Code to reproduce the issue**

```
import tensorflow.keras as keras
from tensorflow.lite.python import lite, interpreter

#define model that uses upsampling 2D and depends on it's output changing with the input size
def DemoModel():
  inputs = keras.layers.Input(shape=[None,None, 3], name="input_1")
  a = keras.layers.MaxPooling2D((2,2))(inputs)
  b = keras.layers.UpSampling2D(size=(2,2))(a)
  c = keras.layers.Concatenate()([b, inputs])
  return keras.models.Model(inputs=[inputs], outputs=[a, c])

#convert to tflite
model = DemoModel()
model.compile(optimizer="sgd", loss="mean_squared_error")
model.save("testModel.h5")

converter = lite.TFLiteConverter.from_keras_model_file("testModel.h5", input_shapes={'input_1': [1,32,64,3]})
tflite_model=converter.convert()


#run the tflite model

inter = interpreter.Interpreter(model_content=tflite_model)
print(inter.get_input_details())
inter.resize_tensor_input(1, [1,16,32,3])
inter.allocate_tensors()
print(inter.get_input_details())


```

**Comment by stephen-systemfriend** [comment]
Is there a workaround for this or any fix in any of the 2.x releases?

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.

**Comment by stephen-systemfriend** [comment]
The above code run on tf 2.4.0 gives the following runtime error:

RuntimeError: Attempting to resize a fixed-size tensor.

I guess that this probably indicates that tensorflow lite doesn't support changing the input size at runtime then?
