### ISSUE TITLE
[TF2.0] Keras layers with custom tensors as variables

### ISSUE THREAD

**Issue by alshedivat** [tensorflow/tensorflow#33125]
(I've asked this question on [StackOverflow](https://stackoverflow.com/questions/58275253/tensorflow-2-0-keras-layers-with-custom-tensors-as-variables), but after looking closer into the source code, I'm not sure if a clean solution exits yet, so re-posting it here.)

In TF 1.x, it was possible to build layers with custom variables. Here's an example:

```python
import numpy as np
import tensorflow as tf

def make_custom_getter(custom_variables):
    def custom_getter(getter, name, **kwargs):
        if name in custom_variables:
            variable = custom_variables[name]
        else:
            variable = getter(name, **kwargs)
        return variable
    return custom_getter

# Make a custom getter for the dense layer variables.
# Note: custom variables can result from arbitrary computation;
#       for the sake of this example, we make them just constant tensors.
custom_variables = {
    "model/dense/kernel": tf.constant(
        np.random.rand(784, 64), name="custom_kernel", dtype=tf.float32),
    "model/dense/bias": tf.constant(
        np.random.rand(64), name="custom_bias", dtype=tf.float32),
}
custom_getter = make_custom_getter(custom_variables)

# Compute hiddens using a dense layer with custom variables.
x = tf.random.normal(shape=(1, 784), name="inputs")
with tf.variable_scope("model", custom_getter=custom_getter):
    Layer = tf.layers.Dense(64)
    hiddens = Layer(x)

print(Layer.variables)
```
The printed variables of the constructed dense layer will be custom tensors we specified in the `custom_variables` dict:
```python
[<tf.Tensor 'custom_kernel:0' shape=(784, 64) dtype=float32>, <tf.Tensor 'custom_bias:0' shape=(64,) dtype=float32>]
```
This allows us to create layers/models that use provided tensors in `custom_variables` directly as their weights, so that we could further differentiate the output of the layers/models with respect to any tensors that `custom_variables` may depend on (particularly useful for implementing functionality in [modulating sub-nets](https://distill.pub/2018/feature-wise-transformations/), [parameter generation](https://arxiv.org/abs/1705.10301), [meta-learning](https://github.com/deepmind/learning-to-learn), etc.).

Variable scopes used to make it easy to nest all off graph-building inside scopes with custom getters and build models that used the provided tensors as their parameters. Since sessions and variable scopes are no longer advisable in TF 2.0 (and all of that low-level stuff is moved to `tf.compat.v1`), what would be **the best practice** to implement the above using Keras and TF 2.0?

**Note:** It looks like `tf.keras.layers.Layer` supports custom getters, but I'm running into issues passing arbitrary tensors instead of variables (e.g., the getter [gets wrapped internally](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/keras/engine/base_layer.py#L412-L416) which I'm not sure how affects non-variable tensors). So, not sure the use-case I outlined above is properly supported. What's the best way to go about it?

**Comment by gowthamkpr** [comment]
@alshedivat Go through this [documentation](https://www.tensorflow.org/guide/effective_tf2) and try ti convert your code and let me know if you are facing any challenges. Thanks!

**Comment by alshedivat** [comment]
@gowthamkpr, yes, I've gone through the Effective TF2 docs, but building layers/models on top of custom tensors as variables seems to be outside the scope of what it covers.

My code above doesn't need any changes until the line `with tf.variable_scope` (it all works in the eager mode and all that). Starting that line, I'm not sure how the `custom_getter` is supposed to be passed to `tf.keras.layers.Dense` so that it internally uses the specified tensors without variable scopes. Any ideas?

**Comment by alshedivat** [comment]
@fchollet, what's be the best practice here?

**Comment by gowthamkpr** [comment]
@alshedivat Will look into it and will get back to you

**Comment by alshedivat** [comment]
@gowthamkpr, the stackoverflow answer provides a hacky solution customized for the Dense layer. Following that approach, I'd need to write a whole library of such lambda layers for each layer type in Keras. Using `tf.variable_scope` in TF 1.x doesn't require that.

I'd like to see if there is a nice way to implement a Layer or Model wrapper in TF 2.0 that can take care of building the model graph on top of the provided custom tensors used as weights. If there is no clean way to do it now, I'd be happy to help upgrade Layer/Model/Wrapper API that allows this. Thanks.

**Comment by gowthamkpr** [comment]
@alshedivat Rightnow, we don't have a clean way to do this.

**Comment by gowthamkpr** [comment]
I am closing this issue for now. If there are any updates, will keep you posted. Thanks!

**Comment by alshedivat** [comment]
Just FYI, I have implemented [context manager](https://github.com/alshedivat/meta-blocks/blob/master/meta_blocks/adaptation/maml_utils.py#L21-L93) that allows building arbitrary Keras models with custom tensors as variables. It works well, and the only downside is that I have to monkey patch/unpatch internal `tensorflow.python.keras.engine.base_layer_utils.make_variable`.

@gowthamkpr, as a feature request, is it possible to expose some public API for customizing variable getters in TF2, so that my solution does not have to tweak Keras internals?
