### ISSUE TITLE
Roll of absl breaks TFLite builds (absl::MakeTaggedSeedSeq)

### ISSUE THREAD

**Issue by powderluv** [tensorflow/tensorflow#33122]
Build Top of master with 

./tensorflow/lite/tools/make/download_dependencies.sh                                                                                                                                                                  
./tensorflow/lite/tools/make/build_lib.sh    

Fails with:

tensorflow/lite/tools/make/downloads/absl/absl/random/internal/named_generator.cc: In function ‘int main()’:                                                                                                                  │····
tensorflow/lite/tools/make/downloads/absl/absl/random/internal/named_generator.cc:23:25: error: ‘MakeTaggedSeedSeq’ is not a member of ‘absl’                                                                                 │····
   auto seed_seq = absl::MakeTaggedSeedSeq("TEST_GENERATOR", std::cerr);                                                                                                                                                      │····
                         ^~~~~~~~~~~~~~~~~                              

This has been fixed in top of master absl by deleting the file. 

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 19.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): source 
- TensorFlow version: master
- Python version:
- Installed using virtualenv? pip? conda?:
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Comment by alexryan** [comment]
I have this problem as well on debian stretch.

```
tensorflow/lite/tools/make/downloads/absl/absl/random/internal/named_generator.cc: In function ‘int main()’:
tensorflow/lite/tools/make/downloads/absl/absl/random/internal/named_generator.cc:23:19: error: ‘MakeTaggedSeedSeq’ is not a member of ‘absl’
   auto seed_seq = absl::MakeTaggedSeedSeq("TEST_GENERATOR", std::cerr);
                   ^~~~
arm-linux-gnueabihf-g++ -O3 -DNDEBUG -fPIC  --std=c++11 -march=armv7-a -mfpu=neon-vfpv4 -funsafe-math-optimizations -ftree-vectorize -fPIC -I. -I/home/pi/tensorflow/tensorflow/lite/tools/make/../../../../../ -I/home/pi/tensorflow/tensorflow/lite/tools/make/../../../../../../ -I/home/pi/tensorflow/tensorflow/lite/tools/make/downloads/ -I/home/pi/tensorflow/tensorflow/lite/tools/make/downloads/eigen -I/home/pi/tensorflow/tensorflow/lite/tools/make/downloads/absl -I/home/pi/tensorflow/tensorflow/lite/tools/make/downloads/gemmlowp -I/home/pi/tensorflow/tensorflow/lite/tools/make/downloads/neon_2_sse -I/home/pi/tensorflow/tensorflow/lite/tools/make/downloads/farmhash/src -I/home/pi/tensorflow/tensorflow/lite/tools/make/downloads/flatbuffers/include -I -I/usr/local/include -c tensorflow/lite/tools/make/downloads/absl/absl/random/internal/seed_salting_sequence_generator.cc -o /home/pi/tensorflow/tensorflow/lite/tools/make/gen/rpi_armv7l/obj/tensorflow/lite/tools/make/downloads/absl/absl/random/internal/seed_salting_sequence_generator.o
tensorflow/lite/tools/make/downloads/absl/absl/random/internal/pool_urbg.cc: In static member function ‘static void absl::lts_2019_08_08::random_internal::RandenPool<T>::Fill(absl::lts_2019_08_08::Span<T>) [with T = long long unsigned int]’:
tensorflow/lite/tools/make/downloads/absl/absl/random/internal/pool_urbg.cc:241:6: note: parameter passing for argument of type ‘absl::lts_2019_08_08::Span<long long unsigned int>’ will change in GCC 7.1
 void RandenPool<T>::Fill(absl::Span<result_type> data) {
      ^~~~~~~~~~~~~
tensorflow/lite/tools/make/Makefile:251: recipe for target '/home/pi/tensorflow/tensorflow/lite/tools/make/gen/rpi_armv7l/obj/tensorflow/lite/tools/make/downloads/absl/absl/random/internal/named_generator.o' failed
make: *** [/home/pi/tensorflow/tensorflow/lite/tools/make/gen/rpi_armv7l/obj/tensorflow/lite/tools/make/downloads/absl/absl/random/internal/named_generator.o] Error 1
make: *** Waiting for unfinished jobs....
make: Leaving directory '/home/pi/tensorflow'
```
Is a work-around available?

**Comment by jdduke** [comment]
@multiverse-tf has a bit more experience with the Raspberry Pi build pipeline and can offer an update.

**Comment by powderluv** [comment]
This is not rpi specific. All of TFlite is affected. 

Also the software engineer in me cringes when I see a name space like absl::lts_2019_08_08:: Maybe we can a git sha in the name space next. 😜

**Comment by multiverse-tf** [comment]
Indeed. This specific absl version is defined in https://github.com/tensorflow/tensorflow/blob/master/tensorflow/workspace.bzl and was introduced in https://github.com/tensorflow/tensorflow/commit/7c2f3e2f88523dd016f36484646c7e5a14c2da38#diff-455a4c7f8e22d7c514e8c2caa27506c5

A rollback of the above commit is underway.

**Comment by powderluv** [comment]
@multiverse-tf thanks for the rollback. Is there any way you can setup a TFLite CI builder or something so such a rollout doesn't rollin in the first place :)

**Comment by powderluv** [comment]
resolved now
