### ISSUE TITLE
[tf1.14][TPU] Can not save model trained on TPU using tf.saved_model.save

### ISSUE THREAD

**Issue by rishabhsahrawat** [tensorflow/tensorflow#33136]
I want to deploy the model using TF serving, for which I require to save the model using low level API `tf.saved_model.save()`. I am using [this](https://colab.research.google.com/drive/1C2JLKR3Rn1j2cZ_z_ZrTIc36Ou2s1H0-) exact tutorial on TPU with everything default. In found this tutorial [here](https://cloud.google.com/tpu/docs/colabs). After `model.fit()` if I try to save the model using `tf.saved_model.save()`, it throws the error `AttributeError: 'TPUMirroredVariable' object has no attribute '_constraint'`

However, this works fine with GPU strategies. Please help, or share some info. on how to deploy model which is trained on TPU.

Thank you,
Rishabh Sahrawat

**Comment by lufol** [comment]
Hi, in the first notebook you [linked](https://colab.research.google.com/github/tensorflow/tpu/blob/master/tools/colab/shakespeare_with_tpu_and_keras.ipynb#scrollTo=ExQ922tfzSGA&line=20&uniqifier=1) in the 6th cell it says `training_model.save_weights('/tmp/bard.h5', overwrite=True`.
When I run this notebook for me the saving works fine. 
Could you please share the code that throws the error? (Ideally as an colab notebook)

**Comment by rishabhsahrawat** [comment]
Hello, I am sorry, I did not make any changes to it but here is the edited file(https://colab.research.google.com/drive/1sQzyrz2zFOUVUTByqshJE__dhirxPYzd). I added two line for saving the model using `tf.saved_model.save()`. Thank you!

**Comment by lufol** [comment]
I can reproduce your error. It seems that there are still incompatibilites with tensorflow 2.0 and TPU´s. Officially TPU´s only support tensorflow 1.14 [link](https://cloud.google.com/tpu/docs/supported-versions)

**Comment by rishabhsahrawat** [comment]
Yes, I am aware of that. But I am not using TF2.0, I am using TF1.14. I also mentioned this in the title.
I hope there is a solution, otherwise, what is the meaning of training models on TPUs if they can't be deployed. :(

**Comment by rishabhsahrawat** [comment]
Hello @oanush , @gowthamkpr , is there anyone looking on this issue?. Please update!
Thank you.

**Comment by gowthamkpr** [comment]
It looks like a bug. Thanks for reporting @rishabhsahrawat

**Comment by rishabhsahrawat** [comment]
Hello @gowthamkpr , have we fixed the bug? Thanks.

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.
