### ISSUE TITLE
How to replace Keras' gradients() function with GradientTape in TF2.0?

### ISSUE THREAD

**Issue by haimat** [tensorflow/tensorflow#33135]
With the "old" Keras library I created heatmaps for my CNNs using the `keras.backend.gradients()` function, like this:

    # load model and image, then predict the class this image belongs to
    model = load_model(os.path.join(model_folder, "custom_model.h5"))
    image = image.load_img(image_path)
    img_tensor = image.img_to_array(image)
    img_tensor = np.expand_dims(img_tensor, axis=0)
    img_tensor = preprocess_input(img_tensor)

    preds = model.predict(img_tensor)
    model_prediction = model.output[:, np.argmax(preds[0])]

    # Calculate pooled grads for heatmap
    conv_layer = model.get_layer("block5_conv3")  # last conv. layer
    grads = K.gradients(model_prediction, conv_layer.output)[0]
    pooled_grads = K.mean(grads, axis=(0, 1, 2))

    # Get values of pooled grads and model conv. layer output as Numpy arrays
    input_layer = model.get_layer("model_input")
    iterate = K.function([input_layer], [pooled_grads, conv_layer.output[0]])
    pooled_grads_value, conv_layer_output_value = iterate([img_tensor])

    # Continue with heatmap generation ...

Now I switched to TF2.0 and it's built-in Keras implementation. Everything works fine, however, using that code I get the following error when calling `K.gradients()`:

    tf.gradients is not supported when eager execution is enabled. Use tf.GradientTape instead.

I did some research and tried to understand how I can make use of `GradientTape`, but unfortunately I don't know much about TF nor TF2.0 - I always worked with Keras. Can you guys guide me how I can make this gradient calculation work again with my setup?

**Comment by lufol** [comment]
Hi, please have a look at [this](https://www.tensorflow.org/guide/eager#computing_gradients) doc. The use of GradientTape is described there. 
Maybe these lines will already solve your problem:
```
w = tf.Variable([[1.0]])
with tf.GradientTape() as tape:
  loss = w * w

grad = tape.gradient(loss, w)
print(grad)  # => tf.Tensor([[ 2.]], shape=(1, 1), dtype=float32)
```

**Comment by haimat** [comment]
> Hi, please have a look at [this](https://www.tensorflow.org/guide/eager#computing_gradients) doc. The use of GradientTape is described there.
> Maybe these lines will already solve your problem:
> 
> ```
> w = tf.Variable([[1.0]])
> with tf.GradientTape() as tape:
>   loss = w * w
> 
> grad = tape.gradient(loss, w)
> print(grad)  # => tf.Tensor([[ 2.]], shape=(1, 1), dtype=float32)
> ```

Sorry, but I can't see how these iines will solve my issue. That's my problem - I guess the `GradientTape` can help me, but I don't **how exactly** I need to use it in my case to achieve the same result as before with Keras' `backend.gradients()` function, as shown in my original post.

**Comment by lufol** [comment]
Have you tried disabling the eager mode `tf.compat.v1.disable_eager_execution()`?

**Comment by haimat** [comment]
> Have you tried disabling the eager mode `tf.compat.v1.disable_eager_execution()`?

Yes, I did so and that worked.
However, that is my plan B. I would rather stick to TF2 eager execution if possible.

**Comment by gowthamkpr** [comment]
Can you please take a look at this [issue](https://stackoverflow.com/questions/56478454/in-tensorflow-2-0-with-eager-execution-how-to-compute-the-gradients-of-a-networ) and let me know if it helps. Thanks!

**Comment by haimat** [comment]
> Can you please take a look at this [issue](https://stackoverflow.com/questions/56478454/in-tensorflow-2-0-with-eager-execution-how-to-compute-the-gradients-of-a-networ) and let me know if it helps. Thanks!

That thread might help indeed, thanks. However, I was not able to fully solve my problem yet. I tried Fantasty's answer from the StackOverflow thread, i.e. copied the `watch_layer()` function from his solution over to my program, then updated my code (as shown above) accordingly:

    # Full code for model generation and data loading & processing see orig. posting above
    model_prediction = model.output[:, np.argmax(preds[0])]

    with tf.GradientTape() as gtape:
        watch_layer(conv_layer, gtape)
        preds = model.predict(image_data)
        model_prediction = model.output[:, np.argmax(preds[0])]
        grads = gtape.gradient(model_prediction, conv_layer.result)

But now the call `preds = model.predict(image_data)` does lead to the following error:

    LookupError: No gradient defined for operation 'IteratorGetNext' (op type: IteratorGetNext)

If I remove the `with tf.GradientTape() as gtape` statement and call `predict()` without it, then that call works fine agan (even though then obviously my original problem comes again).

**Comment by haimat** [comment]
> Could you try out the version linked by @gowthamkpr above?
> You seem to call `model.predict(input)` however in the stackoverflow answer they use `model(input)`. Additionaly they only use the prediction inside the `with tf.GradientTape() as tape`. Please try to stick to the stackoverflow version.
> Maybe this will already solve your problem.

I **did** try to predict from within the `with` block, please see my last posting. I moved the call to `.predict()` into that block. Moreover, when I just call `model(image_data)`, as in the StackOverflow version, then the last line

    grads = gtape.gradient(model_prediction, conv_layer.result)

leads to `grads` equals `None`, which also does not solve my issue.

**Comment by lufol** [comment]
In order to help you it would be required to see the whole file you are working on. Either you upload it on google colab and we can try to sovle your problem, or you ask your question on stackoverflow.

**Comment by haimat** [comment]
> In order to help you it would be required to see the whole file you are working on. Either you upload it on google colab and we can try to sovle your problem, or you ask your question on stackoverflow.

Absolutely, please find full source code of a minimal working example here:
[https://gist.github.com/haimat/10a53ad9675f8f5ac1290f06c3e4f973](https://gist.github.com/haimat/10a53ad9675f8f5ac1290f06c3e4f973)

**Comment by haimat** [comment]
I was able to solve this issue [as described here](https://stackoverflow.com/questions/58322147/how-to-generate-cnn-heatmaps-using-built-in-keras-in-tf2-0-tf-keras).

**Comment by generationXcode** [comment]
Thanks! I was having this exact same issue. 🖖🖖🖖🖖🖖🖖🖖🖖🖖🖖😊😊😊😊😊😊😎

**Comment by lucone83** [comment]
Hi! I tried to follow the example linked by @haimat but I'm still getting a problem:

```
image = preprocessing.image.load_img(IMG_PATH, target_size=(150, 150))
img_tensor = preprocessing.image.img_to_array(image)
img_tensor = np.expand_dims(img_tensor, axis=0)
img_tensor = vgg16.preprocess_input(img_tensor)

conv_layer = model.get_layer("block3_conv1")
heatmap_model = models.Model([model.inputs], [conv_layer.output, model.output])

with tf.GradientTape() as gtape:
    conv_output, predictions = heatmap_model(img_tensor)
    loss = predictions[:, np.argmax(predictions[0])]
    grads = gtape.gradient(loss, conv_output)
```

When trying to calculate the loss I got

```
InvalidArgumentError: slice index 5406 of dimension 1 out of bounds. [Op:StridedSlice] name: strided_slice/
```

**Comment by yumaloop** [comment]
see this: https://keras.io/examples/vision/integrated_gradients/
