### ISSUE TITLE
TFLiteLSTMCell and TfLiteRNNCell has large error with high hidden unit

### ISSUE THREAD

**Issue by tobyclh** [tensorflow/tensorflow#33142]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): Pixel 3
- TensorFlow version (use command below): 1.14
- Python version:
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
Bidirectional RNN with LSTM and RNN perform significantly poorer on Android compared to running on Linux with high `n_hidden` (e.g. >300)
In our testings, we see that the amount of parameter has a positive relationship with error, we suspect it is some sort of rounding error in the Lite implementation.

Also, please fix the inconsistent capitalization of `TFLiteLSTMCell` and `TfliteRNNCell`.

**Comment by gadagashwini** [comment]
@tobyclh,
Please provide the code snippet to reproduce the issue. Thanks!

**Comment by tobyclh** [comment]
Hi, thanks for coming back,
I realize it was a bug at our side, sorry about that.
