### ISSUE TITLE
tensorflow (cpu only) with mkl is much slower than without mkl! 

### ISSUE THREAD

**Issue by goldbalance** [tensorflow/tensorflow#33146]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Red Hat 4.8.5-4
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below): 1.8
- Python version: 2.7
- Bazel version (if compiling from source): 0.10.0
- GCC/Compiler version (if compiling from source): 4.8.5
- CUDA/cuDNN version:
- GPU model and memory:

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
I compile tensorflow 1.8 with mkl, and I use c api session to predict wide and deep model.
The Parallel Performance is very slow, avg reponse time is 40 microsecond in 60 qps, cpu load is only 200%

export KMP_BLOCKTIME=0
export KMP_AFFINITY=granularity=fine,verbose,compact,1,0
export OMP_NUM_THREADS=64
export KMP_SETTINGS=1
export MKLDNN_VERBOSE=1

in the opposite， without mkl, The Parallel Performance is ok, avg reponse time is 9 microsecond in 60 qps. I don't know why.Maybe I use wrong!

**Describe the expected behavior**

**Code to reproduce the issue**

    SessionOptions session_options;
    ConfigProto& cp = session_options.config;
    cp.set_intra_op_parallelism_threads(64);

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by preethivenkatesh** [comment]
@goldbalance is there as a reason you are using a much older version of Tensorflow? We have most of our optimizations for W&D in 1.14

**Comment by penpornk** [comment]
Also looping in @wei-v-wang and @agramesh1 for settings.

**Comment by wei-v-wang** [comment]
Thanks @penpornk  

@goldbalance  As a quick suggestion, is it possible to try setting  export OMP_NUM_THREADS=1 and check the performance? Wide & Deep according to my understand, will benefit more from inter_op setting (graph parallelism) than from intra_op (data parallelism). 

We are still identifying the gap with Eigen though.

**Comment by goldbalance** [comment]
> @goldbalance is there as a reason you are using a much older version of Tensorflow? We have most of our optimizations for W&D in 1.14

thank you for your advise, i will try later. I have to consider upgrade our framework software in order to use 1.14

**Comment by goldbalance** [comment]
> Also looping in @wei-v-wang and @agramesh1 for settings.

Hi, I ever knew from your reply about using mkl may lead to much more threads running. As decresing inter threads pool size,  My App runtime cannot use more cpu

> Thanks @penpornk
> 
> @goldbalance As a quick suggestion, is it possible to try setting export OMP_NUM_THREADS=1 and check the performance? Wide & Deep according to my understand, will benefit more from inter_op setting (graph parallelism) than from intra_op (data parallelism).
> 
> We are still identifying the gap with Eigen though.

Hi, I ever knew about using mkl may lead to use much more threads running. In 1 qps, mkl is slower then without mkl.  In 60qps, when decreasing inter threads pool size,  My App runtime cannot use more cpu. When adding the size, there are too many threads to running. I try serveral times from 1 to 64, finally, for the best performance, I set just 1 thread pool size  . Therefore, i give up to mkl tf 1.8

**Comment by goldbalance** [comment]
> Thanks @penpornk
> 
> @goldbalance As a quick suggestion, is it possible to try setting export OMP_NUM_THREADS=1 and check the performance? Wide & Deep according to my understand, will benefit more from inter_op setting (graph parallelism) than from intra_op (data parallelism).
> 
> We are still identifying the gap with Eigen though.

I wanna to know when mkl-dnn can adapt for eigen thread pool

**Comment by goldbalance** [comment]
> Thanks @penpornk
> 
> @goldbalance As a quick suggestion, is it possible to try setting export OMP_NUM_THREADS=1 and check the performance? Wide & Deep according to my understand, will benefit more from inter_op setting (graph parallelism) than from intra_op (data parallelism).
> 
> We are still identifying the gap with Eigen though.

OP_NUM_THREAD=1
SessionOptions session_options;
ConfigProto& cp = session_options.config;
cp.set_inter_op_parallelism_threads(64);
cp.set_intra_op_parallelism_threads(64);

sorry, i met the worst performance using above settting, cpu load also is low

**Comment by wei-v-wang** [comment]
@goldbalance Sorry to hear that. The above setting would generate 64 OMP threads though, eventually. Can you set inter op to e.g. 8 or 16, and then intra_op set to 64 - 8 (or 16)? 
Hopefully this does not give you worse performance than worst :)

**Comment by goldbalance** [comment]
> @goldbalance Sorry to hear that. The above setting would generate 64 OMP threads though, eventually. Can you set inter op to e.g. 8 or 16, and then intra_op set to 64 - 8 (or 16)?
> Hopefully this does not give you worse performance than worst :)

export KMP_BLOCKTIME=0
export KMP_AFFINITY=granularity=fine,verbose,compact,1,0
export OMP_NUM_THREADS=1
export KMP_SETTINGS=1
export MKLDNN_VERBOSE=1
export OMP_STACKSIZE=1G

SessionOptions session_options;
ConfigProto& cp = session_options.config;
cp.set_inter_op_parallelism_threads(8);
cp.set_intra_op_parallelism_threads(64);

Sorry, the performance is also low, 100ms

best performance is 25ms, when inter op is 1 and omp thread is setted 64. 
without mkl is only 10ms. 

I guess that it is blocked, because cpu is low with mkl.

**Comment by wei-v-wang** [comment]
Ok, thank you for trying. Yes, it seems there are fundamental issues that needs to be resolved on our side to bring up the performance.

**Comment by pigubaoza** [comment]
Hi I am also experiencing slowness with 1.14 with mkl. It is slower than 1.14 without MKL. 
I'm using the intelaipg/intel-optimized-tensorflow:1.14.0-mkl-py3 docker image rather than building it myself, running darknet based yolov3. 
Any updates regarding these fundamental issues?

**Comment by wei-v-wang** [comment]
@pigubaoza  We are testing and will be rolling out some new features. Regarding your Darknet based YoloV3, have you tuned OMP_NUM_THREADS, inter_op_parallelism_threads and intra_op_parallelism threads, KMP_BLOCKTIME setting?  Also, what CPU are you testing with?

As a last resort, can you try "export TF_DISALBE_MKL=1" and rerun your model and see if it recovers the performance similar to 1.14 w/o MKL?

**Comment by pigubaoza** [comment]
> @pigubaoza We are testing and will be rolling out some new features. Regarding your Darknet based YoloV3, have you tuned OMP_NUM_THREADS, inter_op_parallelism_threads and intra_op_parallelism threads, KMP_BLOCKTIME setting? Also, what CPU are you testing with?
> 
> As a last resort, can you try "export TF_DISALBE_MKL=1" and rerun your model and see if it recovers the performance similar to 1.14 w/o MKL?

Thanks wei-v-wang. After some testing I found out OMP_NUM_THREADS and KMP_BLOCKTIME should be as recommended. OMP_NUM_THREADS=4 (I am running an i7 6700K), and KMP_BLOCKTIME=0 (Running CNNs), intra_op_parallelism_threads=4, inter_op_parallelism_threads=2. I previously did not use these values. 

Running with TF_DISABLE_MKL=1, my average latency is insignificantly different. ~0.01s

Could it be that because I am running a 6700K, the benefits are not as obvious as running Xeon, or multiple Xeons? 

Also, what are these new features that would be rolled out and where can I follow them?
