### ISSUE TITLE
tflite_runtime standalone always results in "ModuleNotFoundError: No module named '_interpreter_wrapper'"

### ISSUE THREAD

**Issue by wmol4** [tensorflow/tensorflow#33153]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): openSUSE Leap 15.1
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): 
- TensorFlow version: tflite_runtime 1.14.0
- Python version: 3.6.5
- Installed using virtualenv? pip? conda?: pip3 (followed the instructions from https://www.tensorflow.org/lite/guide/python)
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 10.0
- GPU model and memory: NVIDIA 2080ti 11GB

**Describe the problem**
When trying to install just the TensorFlow Lite interpreter, I'm able to install everything with no errors and I can even import tflite_runtime, but when I put in "from tflite_runtime.interpreter import Interpreter", I always run into a ModuleNotFoundError
**Provide the exact sequence of commands / steps that you executed before running into the problem**

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

I also installed Miniconda, installed python 3.7, pip3 installed the correct tflite_runtime for python 3.7, and ran into the exact same ModuleNotFoundError.

**Comment by wmol4** [comment]
I got it to work when I had full tensorflow also installed, but then I did a full reinstall of openSUSE and ran into the same error. I was hoping to only install the Lite Interpreter instead of a full TF.

**Comment by oanush** [comment]
@wmol4 ,
Can you please try `pip install tf-nightly.`
You may also need to change `tf.contrib.lite.Interpreter to tf.lite.Interpreter`
Kindly refer this [link](https://github.com/tensorflow/tensorflow/issues/26422) for more information.

**Comment by wmol4** [comment]
@oanush 
The hope is to only need to install "tflite_runtime" as per this page: 
https://www.tensorflow.org/lite/guide/python#install_just_the_tensorflow_lite_interpreter

The issue is that I can only get the tflite_runtime library to work if I also have full tensorflow installed, which defeats the whole purpose. 

It works when I am running both TF 2.0 and tflite_runtime 1.14. I run into the ModuleNotFoundError when I only install tflite_runtime 1.14. Any ideas how I can get tflite_runtime working without needing to install the full tensorflow as well?

**Comment by wmol4** [comment]
Is anyone else getting this issue or is it just me??

**Comment by Helmars** [comment]
I'm trying to deploy AWS Lambda package containing tflite_runtime and getting the same error. Locally it is working correctly.

**Comment by wmol4** [comment]
Interesting. Full disclosure, I was trying it on Ubuntu and OpenSUSE 15.1 via Windows Subsystem for Linux. But after reading @Helmars message, I decided to try it on a Fedora laptop I have laying around, and it was able to install just fine.

**Comment by Helmars** [comment]
It seems there is a workaround to copy _interpreter_wrapper.so file from tflite_runtime one directory out (to site-packages or current directory). This didn't help for AWS Lambda though, because Amazon Linux uses older version of glibc. I ended up creating minimal C program instead of using TF Lite Python package.

**Comment by Jaftem** [comment]
Any updates on this? Running into this issue with a RPi3.

**Comment by s-nt-s** [comment]
Same problem in AWS Lambda. Any news about this?

**Comment by teijeong** [comment]
Hi, the interpreter_wrapper is migrated to pybind11 from SWIG, and the cause of the error might be different. Can you give more details &
 steps to reproduce?

**Comment by hematogender** [comment]
Facing the same problem using the wheel on Android. It tries to lazy-load the full TensorFlow module, which surely fails. I need to bundle only the tflite_runtime... The import is on line 30 in interpreter.py

**Comment by teijeong** [comment]
Hi hematogender, as I commented above the backend for _interpreter_wrapper has changed, and it might be a different bug. Can you file a separate bug with steps to reproduce?

Seems you're trying to use python over Android rather than using it directly. If importing .aar works it would be great, but seems not so far :(

Can you try with arm64 and see if the same error happens? Also, can you share why cross-compile is not an option? You can crossbuild whl from your machine, following https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/tools/pip_package

**Comment by ambigus9** [comment]
Same Error for AWS lambda

```
Response:
{
  "errorMessage": "Unable to import module 'lambda_function': No module named '_interpreter_wrapper'",
  "errorType": "Runtime.ImportModuleError"
}
```

What i did:

```
## create docker container from python image ##
docker pull python:3.7-slim-buster
docker run -it python:3.7-slim-buster bash
cd home

## zip layer ##
layer=tensorflowLite2
mkdir -p $layer/python/lib/python3.7/site-packages/
cd $layer/python/lib/python3.7/site-packages/
pip install -t . https://dl.google.com/coral/python/tflite_runtime-2.1.0.post1-cp37-cp37m-linux_x86_64.whl
rm -r *.dist-info
rm -r __pycache__/
cd ../../../../
apt-get update
apt-get install zip -y
zip -r9 ../$layer.zip .

```

Any progress?

**Comment by ofekray** [comment]
This stackoverflow thread solved my problem with AWS Lambda:
https://stackoverflow.com/questions/59570081/how-to-use-tensorflow-lite-on-aws-lambda

**Comment by adamp87** [comment]
I was running into the same issue `ModuleNotFoundError: No module named '_interpreter_wrapper'` on **Ubuntu 16.04 x86-64**. The problem was, as the complete error message writes `ImportError: /lib/x86_64-linux-gnu/libm.so.6: version 'GLIBC_2.27' not found`, that Ubuntu 16.04 is delivered with GLIBC 2.23. You can get your version by writing: `ldd --version`.

For me the solution was to use Ubuntu 18.04, which is delivered with GLIBC 2.27.

It might worth considering to write a note for Linux users at page https://www.tensorflow.org/lite/guide/python that Ubuntu 16.04 is not supported.

Hope this helps

**Comment by e-remington-lee** [comment]
> It seems there is a workaround to copy _interpreter_wrapper.so file from tflite_runtime one directory out (to site-packages or current directory). This didn't help for AWS Lambda though, because Amazon Linux uses older version of glibc. I ended up creating minimal C program instead of using TF Lite Python package.

This worked for me. It required me to remove "tensorflow_wrap_interpreter_wrapper.pyo, tensorflow_wrap_interpreter_wrapper.py, _tensorflow_wrap_interpreter_wrapper.pyd out of tflite_runtime" from the tflite_runtime folder and put them one directory up.

**Comment by asheesh123** [comment]
> > It seems there is a workaround to copy _interpreter_wrapper.so file from tflite_runtime one directory out (to site-packages or current directory). This didn't help for AWS Lambda though, because Amazon Linux uses older version of glibc. I ended up creating minimal C program instead of using TF Lite Python package.
> 
> This worked for me. It required me to remove "tensorflow_wrap_interpreter_wrapper.pyo, tensorflow_wrap_interpreter_wrapper.py, _tensorflow_wrap_interpreter_wrapper.pyd out of tflite_runtime" from the tflite_runtime folder and put them one directory up.



How did you do this.. I am getting same error..
I created a virtual env and installed necessary packages (tflite and other).. then zipped the site-packages to a folder.. now in the zipped folder i placed the lambda_function.py.. when I am running this on lambda console.. getting the same error for tflite... other dependencies are imported smoothly..
Thanks in advance..

**Comment by e-remington-lee** [comment]
virtualenv->Lib->site packages, find TFlite and remove the above-mentioned
files up one directory. to be the same directory as the TFlite folder.

**Comment by satya2343** [comment]
Hi, i had this similar issue when running my application on docker. I was using python:3.6.8 at that time. And by changing the python image to 3.6.11 solves my problem. Something that i notice is that there is a difference in gcc version that is being used by them (6.3 and 8.3 as i recall).

**Comment by wenzhaojie** [comment]
> > > It seems there is a workaround to copy _interpreter_wrapper.so file from tflite_runtime one directory out (to site-packages or current directory). This didn't help for AWS Lambda though, because Amazon Linux uses older version of glibc. I ended up creating minimal C program instead of using TF Lite Python package.
> > 
> > 
> > This worked for me. It required me to remove "tensorflow_wrap_interpreter_wrapper.pyo, tensorflow_wrap_interpreter_wrapper.py, _tensorflow_wrap_interpreter_wrapper.pyd out of tflite_runtime" from the tflite_runtime folder and put them one directory up.
> 
> How did you do this.. I am getting same error..
> I created a virtual env and installed necessary packages (tflite and other).. then zipped the site-packages to a folder.. now in the zipped folder i placed the lambda_function.py.. when I am running this on lambda console.. getting the same error for tflite... other dependencies are imported smoothly..
> Thanks in advance..

After copy files in tflite_runtime to the ../, there turn out to be:
{
  "errorMessage": "Unable to import module 'handler': /lib64/libm.so.6: version `GLIBC_2.27' not found (required by /var/task/_interpreter_wrapper.so)",
  "errorType": "Runtime.ImportModuleError"
}

**Comment by Bhanuchander210** [comment]
Having same issue... Any one better solution for this ?

**Comment by mpizosdim** [comment]
Have same error "Unable to import module 'handler': /lib64/libm.so.6: version `GLIBC_2.27' not found .." on AWS lambda. Building it locally on Ubunt18.04 works fine though.

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.

**Comment by Lucky94** [comment]
This issue still exits with tf2.x
tflite runtime needs GLIBC_2.27 which ubuntu16.04 does not come shipped with (it comes with GLIBC_2.23)
Is there a hard requirement of tflite runtime interpreter for GLIB_2.27 ? Is there any workaround for ubuntu16.04, please let know.

**Comment by GarimaSarangal** [comment]
@Lucky94 did you find any solution for this. I am in same situation
