### ISSUE TITLE
issue with reuse embedding module

### ISSUE THREAD

**Issue by zhezhe123** [tensorflow/tensorflow#33156]
I was using the universal sentence encoder transformer module for some developments and had no issue before. But when I try to reuse the module today, I got an error, wondering if anyone had similar experience and solution with this?

script: embed = hub.Module("https://tfhub.dev/google/universal-sentence-encoder-large/3")

error: variable_scope module_20/ was unused but the corresponding name_scope was already taken.

Thanks.

**Comment by gowthamkpr** [comment]
What version of Tensorflow and Tensorflow Hub are you using? Also I am unable to reproduce this error wit Tensorflow 1.15rc3 and Tensorflow Hub 0.6. Please find the github gist [here](https://colab.sandbox.google.com/gist/gowthamkpr/382e0579776b389e1ada66c73b84863a/copy-of-semantic-similarity-with-tf-hub-universal-encoder.ipynb).
