### ISSUE TITLE
Build fails to create GPU target ( nvptx64-nvidia-cuda ) for CUDA10.0/CUDNN7.0/VT100

### ISSUE THREAD

**Issue by gosha1128** [tensorflow/tensorflow#33158]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):  Debian GNU/Linux 9 \n \l
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: None
- TensorFlow installed from (source or binary): source
- TensorFlow version: 2.x
- Python version:  2.7
- Installed using virtualenv? pip? conda?:  pip
- Bazel version (if compiling from source): 26.1
- GCC/Compiler version (if compiling from source): g++ (Debian 6.3.0-18+deb9u1) 6.3.0 20170516
- CUDA/cuDNN version: 10.0/7.0
- GPU model and memory: Tesla V100-SXM2, 16130MiB 

**Describe the problem**

Build Fails

**Provide the exact sequence of commands / steps that you executed before running into the problem**

bazel build //tensorflow/tools/pip_package:build_pip_package

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

ERROR: /home/george/tensorflow/tensorflow/core/kernels/BUILD:4675:1: C++ compilation of rule '//tensorflow/core/kernels:fake_quant_ops_gpu' failed (Exit 1)
error: unable to create target: 'No available targets are compatible with triple "nvptx64-nvidia-cuda"'
1 error generated when compiling for sm_70.
Target //tensorflow/tools/pip_package:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 4036.064s, Critical Path: 83.02s
INFO: 4647 processes: 4647 local.
FAILED: Build did NOT complete successfully

**Comment by angerson** [comment]
Thanks for your report. Can you please attach a complete log of ./configure and bazel build starting from a fresh environment on the master branch?

**Comment by gosha1128** [comment]
So, I ended up switching over to Python 3 ( Conda based ) and it looks like
everything worked.

I would be happy to try to debug the Python 2 issue I had again, and report
back, but I'll need to redo the installation from scratch.

I am renting my own GCP instance to do this - and its pretty expensive to
run a tensorflow build from scratch because it takes so long.

Can you recommend any free or cheap resources with GPUs attached ?

**Comment by angerson** [comment]
Cool, glad to hear it. We'll be deprecating Python 2.7 support in TensorFlow when Python 2.7 reaches EOL in January 2020, so you don't need to worry about extra debugging for Python 2. Thanks! I'll go ahead and close this issue for now.

Unfortunately, I'm not aware of better resources for GPUs on GCP, aside from doing your own comparison of [the GPU prices](https://cloud.google.com/compute/gpus-pricing) or receiving GCP credits from some other source (Google sometimes runs promotions for this, but I'm not sure of any specific ones right now).
