### ISSUE TITLE
Inference On-Cloud for Object Detection

### ISSUE THREAD

**Issue by giannisfourfouris** [tensorflow/tensorflow#33151]
Hello, 
I built an android app for object detection using tensorflow lite and on-Device inference. I want to make inference on-Cloud and saw that the tensorflow serving client is still unavaliable for android. Do you know a way to use cloud for inference at my object detection mobile app? Thanks an advance.

**Comment by gowthamkpr** [comment]
@giannisfourfouris Follow this [article](https://medium.com/tensorflow/training-and-serving-a-realtime-mobile-object-detector-in-30-minutes-with-cloud-tpus-b78971cf1193) and it should help you in soving your problem.
