### ISSUE TITLE
TF1.13.1 Bazel Build Error

### ISSUE THREAD

**Issue by zzh123123ise** [tensorflow/tensorflow#33165]
**System information**
- OS Platform and Distribution :Windows 10
- TensorFlow installed from: source
- TensorFlow version: 1.13.1
- Python version: 3.5.2
- Bazel version :  0.20.0
- CUDA/cuDNN version: 10.0/7.6.4

**Describe the problem**

ERROR: Skipping '//tensorflow:libtensorflow_cc.so': error loading package 'tensorflow': Encountered error while reading extension file 'cuda/build_defs.bzl': no such package '@local_config_cuda//cuda': Traceback (most recent call last):
        File "C:/d/tensorflow-1.13.1/source/third_party/gpus/cuda_configure.bzl", line 1556
                _create_local_cuda_repository(repository_ctx)
        File "C:/d/tensorflow-1.13.1/source/third_party/gpus/cuda_configure.bzl", line 1395, in _create_local_cuda_repository
                find_cc(repository_ctx)
        File "C:/d/tensorflow-1.13.1/source/third_party/gpus/cuda_configure.bzl", line 239, in find_cc
                _get_msvc_compiler(repository_ctx)
        File "C:/d/tensorflow-1.13.1/source/third_party/gpus/cuda_configure.bzl", line 156, in _get_msvc_compiler
                find_msvc_tool(repository_ctx, vc_path, "cl.exe").replace("\\", "/")
type 'NoneType' has no method replace(string, string)
WARNING: Target pattern parsing failed.
ERROR: error loading package 'tensorflow': Encountered error while reading extension file 'cuda/build_defs.bzl': no such package '@local_config_cuda//cuda': Traceback (most recent call last):
        File "C:/d/tensorflow-1.13.1/source/third_party/gpus/cuda_configure.bzl", line 1556
                _create_local_cuda_repository(repository_ctx)
        File "C:/d/tensorflow-1.13.1/source/third_party/gpus/cuda_configure.bzl", line 1395, in _create_local_cuda_repository
                find_cc(repository_ctx)
        File "C:/d/tensorflow-1.13.1/source/third_party/gpus/cuda_configure.bzl", line 239, in find_cc
                _get_msvc_compiler(repository_ctx)
        File "C:/d/tensorflow-1.13.1/source/third_party/gpus/cuda_configure.bzl", line 156, in _get_msvc_compiler
                find_msvc_tool(repository_ctx, vc_path, "cl.exe").replace("\\", "/")
type 'NoneType' has no method replace(string, string)

**Comment by ravikyram** [comment]
@zzh123123ise 
Just to verify, did you follow the steps mentioned in the [Tensorflow build ](https://www.tensorflow.org/install/source_windows)official website. If not please follow the steps. Let us know how it progresses.Which protobuf version are you using? Thanks!

**Comment by zzh123123ise** [comment]
Thanks!Now I followed the official document but failed too.

`bazel build --config=opt --config=cuda --copt=-nvcc_options=disable-warnings`
the error occured like this:
```
ERROR: no such package '@local_config_cuda//crosstool': Traceback (most recent call last):
        File "C:/d/tensorflow-1.13.1/source/third_party/gpus/cuda_configure.bzl", line 1556
                _create_local_cuda_repository(repository_ctx)
        File "C:/d/tensorflow-1.13.1/source/third_party/gpus/cuda_configure.bzl", line 1395, in _create_local_cuda_repository
                find_cc(repository_ctx)
        File "C:/d/tensorflow-1.13.1/source/third_party/gpus/cuda_configure.bzl", line 239, in find_cc
                _get_msvc_compiler(repository_ctx)
        File "C:/d/tensorflow-1.13.1/source/third_party/gpus/cuda_configure.bzl", line 156, in _get_msvc_compiler
                find_msvc_tool(repository_ctx, vc_path, "cl.exe").replace("\\", "/")
type 'NoneType' has no method replace(string, string)
```
It seems bazel doesn't recognize @local_config_cuda//crosstool as a package,the same error
with the previous one.

I got protoc-3.10.0-win64 in my computer.

**Comment by angerson** [comment]
Thanks for your report. Can you please attach a complete log of `./configure` and `bazel build` starting from a fresh environment on the `master` branch?

**Comment by zzh123123ise** [comment]
./configuire:

```
C:\D\tensorflow-1.13.1\source>python ./configure.py
WARNING: The following rc files are no longer being read, please transfer their contents or import their path into one of the standard rc files:
nul
WARNING: Running Bazel server needs to be killed, because the startup options are different.
WARNING: --batch mode is deprecated. Please instead explicitly shut down your Bazel server using the command "bazel shutdown".
INFO: Invocation ID: c5e9770e-6eec-4f79-b491-5e0bda52f691
You have bazel 0.20.0 installed.
Please specify the location of python. [Default is C:\Users\Administrator\Anaconda3\python.exe]:


Found possible Python library paths:
  C:\Users\Administrator\Anaconda3\lib\site-packages
Please input the desired Python library path to use.  Default is [C:\Users\Administrator\Anaconda3\lib\site-packages]

Do you wish to build TensorFlow with XLA JIT support? [y/N]: N
No XLA JIT support will be enabled for TensorFlow.

Do you wish to build TensorFlow with ROCm support? [y/N]: N
No ROCm support will be enabled for TensorFlow.

Do you wish to build TensorFlow with CUDA support? [y/N]: y
CUDA support will be enabled for TensorFlow.

Please specify the CUDA SDK version you want to use. [Leave empty to default to CUDA 10.0]:


Please specify the location where CUDA 10.0 toolkit is installed. Refer to README.md for more details. [Default is C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.0]:


Please specify the cuDNN version you want to use. [Leave empty to default to cuDNN 7]:


Please specify the location where cuDNN 7 library is installed. Refer to README.md for more details. [Default is C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.0]:


Please specify a list of comma-separated Cuda compute capabilities you want to build with.
You can find the compute capability of your device at: https://developer.nvidia.com/cuda-gpus.
Please note that each additional compute capability significantly increases your build time and binary size. [Default is: 3.5,7.0]: 5.2


Please specify optimization flags to use during compilation when bazel option "--config=opt" is specified [Default is /arch:AVX]:


Would you like to override eigen strong inline for some C++ compilation to reduce the compilation time? [Y/n]: y
Eigen strong inline overridden.

Preconfigured Bazel build configs. You can use any of the below by adding "--config=<>" to your build command. See .bazelrc for more details.
        --config=mkl            # Build with MKL support.
        --config=monolithic     # Config for mostly static monolithic build.
        --config=gdr            # Build with GDR support.
        --config=verbs          # Build with libverbs support.
        --config=ngraph         # Build with Intel nGraph support.
        --config=dynamic_kernels        # (Experimental) Build kernels into separate shared objects.
Preconfigured Bazel build configs to DISABLE default on features:
        --config=noaws          # Disable AWS S3 filesystem support.
        --config=nogcp          # Disable GCP support.
        --config=nohdfs         # Disable HDFS support.
        --config=noignite       # Disable Apacha Ignite support.
        --config=nokafka        # Disable Apache Kafka support.
        --config=nonccl         # Disable NVIDIA NCCL support.

```
bazel build:

```
C:\D\tensorflow-1.13.1\source>bazel build --config=opt --config=cuda --copt=-nvcc_options=disable-warnings
WARNING: The following rc files are no longer being read, please transfer their contents or import their path into one of the standard rc files:
c:\d\tensorflow-1.13.1\source/.bazelrc
Starting local Bazel server and connecting to it...
WARNING: The following configs were expanded more than once: [cuda]. For repeatable flags, repeats are counted twice and may lead to unexpected behavior.
WARNING: Option 'experimental_shortened_obj_file_path' is deprecated
INFO: Invocation ID: 60bcaa7e-ab7d-433b-a1dc-207e4838d15c
ERROR: no such package '@local_config_cuda//crosstool': Traceback (most recent call last):
        File "C:/d/tensorflow-1.13.1/source/third_party/gpus/cuda_configure.bzl", line 1556
                _create_local_cuda_repository(repository_ctx)
        File "C:/d/tensorflow-1.13.1/source/third_party/gpus/cuda_configure.bzl", line 1395, in _create_local_cuda_repository
                find_cc(repository_ctx)
        File "C:/d/tensorflow-1.13.1/source/third_party/gpus/cuda_configure.bzl", line 239, in find_cc
                _get_msvc_compiler(repository_ctx)
        File "C:/d/tensorflow-1.13.1/source/third_party/gpus/cuda_configure.bzl", line 156, in _get_msvc_compiler
                find_msvc_tool(repository_ctx, vc_path, "cl.exe").replace("\\", "/")
type 'NoneType' has no method replace(string, string)
INFO: Elapsed time: 10.476s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
    Fetching @local_config_cuda; fetching

```

**Comment by angerson** [comment]
Just to double check: you're building on `master`, right? If so, you'll need to install one of the versions of bazel we support at `master`, which you can find in `configure.py` (this is currently 0.24.1 through 0.29.1).

**Comment by zzh123123ise** [comment]
Thanks for your repilies! But I've already build TF 1.13.1 successful.An incomplete install of Visual Studio and Visual C++ leads to this.I should check my environment first before I asked questions,sorry about that.

**Comment by VCBE123** [comment]
When installing VS2015, we need to choose c++, that solved this problem for me
