### ISSUE TITLE
[2.0] Disable usage of GPU using the new config APIs

### ISSUE THREAD

**Issue by llan-ml** [tensorflow/tensorflow#33168]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using): 2.0

**Describe the feature and the current behavior/state.**
For 2.0, there are some new APIs to configure GPU devices (https://www.tensorflow.org/api_docs/python/tf/config/experimental).

However, by using the current APIs, we have to select at least one GPU to be visible [[source code](https://github.com/tensorflow/tensorflow/blob/1cf0898dd4331baf93fe77205550f2c2e6c90ee5/tensorflow/python/eager/context.py#L1174-L1202)].

A similar report is [here](https://github.com/tensorflow/tensorflow/issues/26460#issuecomment-515707199).

It would be useful if we can completely disable the usage of GPUs for `tensorflow-gpu` release.

**Comment by novog** [comment]
Does executing your code from within the cotext of a `tf.device` statement work for you? Example:

    with tf.device('/CPU:0'):
        #your code here

**Comment by llan-ml** [comment]
TF will occupy 300~400 MB of GPU memory for each GPU when it does initialization. It's a great waste in a multi-gpu machine.

**Comment by llan-ml** [comment]
One way is that we can set the environment variable `CUDA_VISIBLE_DEVICES=""` to disable the GPU initialization. But in my case, a cluster (typically, [ray](https://github.com/ray-project/ray)) reads `CUDA_VISIBLE_DEVICES` and then allocates GPUs to different remote processes.

Since TF has provided some experimental APIs to configure GPU, it would be great to also support for the disability of GPUs.

**Comment by tgaddair** [comment]
Any update on this?  I would have expected `tf.config.experimental.set_visible_devices([], 'GPU')` to do this, but it just ends up allocating memory on all available devices.

**Comment by llan-ml** [comment]
@jvishnuvardhan @aaroey

**Comment by aaroey** [comment]
@jaingaurav could you help to take a look? Thanks.

**Comment by jaingaurav** [comment]
`tf.config.experimental.set_visible_devices([], 'GPU')` seems to work for me. What does the output of `tf.config.experimental.list_logical_devices()` return? If you are seeing a GPU there, then the visible devices configuration did not properly apply.

**Comment by jaingaurav** [comment]
Actually hold on, I was using a different build. It seems like memory is still being used even if no visible devices are being set.

**Comment by jaingaurav** [comment]
We were able to confirm that a small amount of memory is being used by XLA. We're working on a fix now.

**Comment by jaingaurav** [comment]
As per the commits referenced above, I believe this issue has already been fixed.

**Comment by llan-ml** [comment]
Hi @jaingaurav It seems that this issue still exists. Please refer to this [notebook](https://colab.research.google.com/drive/1DiSO-TWlph6lHteWnPrOfoGytfCHs0IS).

**Comment by jaingaurav** [comment]
@llan-ml: Please try testing with the nightly by running `!pip install tf-nightly-gpu` first. Most of the memory is gone (though I still saw 10 MB on my end).

**Comment by tgaddair** [comment]
Hey @jaingaurav, thanks for the fix!  To clarify, this feature will be available in TensorFlow 2.2?

Also, to disable GPU usage is, as suggested:

```
tf.config.experimental.set_visible_devices([], 'GPU')
```

Is that right?

**Comment by jaingaurav** [comment]
@tgaddair: Yes that is correct, we'll be cutting 2.2 in the next few days. And yes again, the tf.config API is the the way to go. Note that as of 2.1 the API is no longer experimental so you should be able to do:
```
tf.config.set_visible_devices([], 'GPU')
```

**Comment by tgaddair** [comment]
Thanks for clarifying @jaingaurav, that sounds good.

**Comment by black-SP** [comment]
Hi, I was looking for a command to disable the gpu temporarily but this (tf.config.set_visible_devices([], 'GPU')) still doesn't work, GPU is still seen and recognized.

Staring with a kernel reset and outputs cleared with and without this command I get the following output plus my LSTM is taking exactly 2 seconds per epoch (which is really fast indicating the GPU is being used.

in:
from tensorflow.python.client import device_lib
print(device_lib.list_local_devices())

out:
2.1.0
[name: "/device:CPU:0"
device_type: "CPU"
memory_limit: 268435456
locality {
}
incarnation: 1101021068840087635
, name: "/device:XLA_CPU:0"
device_type: "XLA_CPU"
memory_limit: 17179869184
locality {
}
incarnation: 4860144077117132374
physical_device_desc: "device: XLA_CPU device"
, name: "/device:GPU:0"
device_type: "GPU"
memory_limit: 7321806439
locality {
  bus_id: 1
  links {
  }
}
incarnation: 9454423434461393270
physical_device_desc: "device: 0, name: GeForce RTX 2080 SUPER, pci bus id: 0000:2d:00.0, compute capability: 7.5"
, name: "/device:XLA_GPU:0"
device_type: "XLA_GPU"
memory_limit: 17179869184
locality {
}
incarnation: 105405715844467737
physical_device_desc: "device: XLA_GPU device"
]
