### ISSUE TITLE
Continue training on SavedModel or load checkpoint from SavedModel

### ISSUE THREAD

**Issue by davislf2** [tensorflow/tensorflow#33162]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using): 1.14
- Are you willing to contribute it (Yes/No): Yes

**Describe the feature and the current behavior/state.**
In tensorflow 1.14, it's obvious that tf.compat.v1.train.init_from_checkpoint can load ckpt to continue training (or to warm start). However, I couldn't find any corresponding approaches in SavedModel, and tf.estimator.WarmStartSetting only supports ckpt as well. It would be helpful if we could either load checkpoint in SavedModel or warm-start training from SavedModel.

**Will this change the current api? How?**
1. train.init_from_checkpoint could load SavedModel 
2. tf.estimator.WarmStartSettings could load SavedModel

**Who will benefit with this feature?**
Those who store models in SavedModel format and want to keep training (or warm start).

**Any Other info.**

**Comment by ravikyram** [comment]
@davislf2 
Do you have any use case that requires the feature you are interested in? Please feel free to submit a PR if you have use cases that supports that feature.

**Comment by davislf2** [comment]
@ravikyram 
In our use case, we serve our model with SavedModel format. For a live product, it's possible that we might want to add some new data without retraining the model from scratch, and init_checkpoint can save time. Since deploying and serving SavedModel is more encouraged, I think it might be more convenient if we can also warm start from SavedModel rather than checkpoints.

**Comment by ekaakurniawan** [comment]
Can we set it from `initial_value` of `tf.Variable`? If yes, then the question will be how to get the value from `tf.train.Saver().restore()`?

How does transfer learning do it? Does it load the model from `hdf5` and performs training?

**Comment by devdev999** [comment]
Are there any plans for work on this in the future?

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.
