### ISSUE TITLE
Can we set a proper range of bazel?

### ISSUE THREAD

**Issue by jinfagang** [tensorflow/tensorflow#33169]
```
[17:01:55] fagn:tensorflow git:(master) $ ./configure
WARNING: Running Bazel server needs to be killed, because the startup options are different.
WARNING: --batch mode is deprecated. Please instead explicitly shut down your Bazel server using the command "bazel shutdown".
You have bazel 0.23.0 installed.
Please upgrade your bazel installation to version 0.24.1 or higher to build TensorFlow!
[17:02:35] fan:tensorflow git:(master) $ ./configure
Extracting Bazel installation...
WARNING: --batch mode is deprecated. Please instead explicitly shut down your Bazel server using the command "bazel shutdown".
You have bazel 0.29.1 installed.
Please downgrade your bazel installation to version 0.26.1 or lower to build TensorFlow! To downgrade: download the installer for the old version (from https://github.com/bazelbuild/bazel/releases) then run the installer.

```

Messages said higher..... but not upper bounds.... then installed newest version got need lower....

Why one sentence can not said in one line?

**Comment by gadagashwini** [comment]
@jinfagang, Tensorflow 1.14.0 supports 0.24.1 Bazel version and Tensorflow 2.0.0 supports 0.26.1 Bazel version. Please take a look at [tested build configurations](https://www.tensorflow.org/install/source#tested_build_configurations). Thanks!

**Comment by gadagashwini** [comment]
@jinfagang, Did you get a chance to look at the [link](https://www.tensorflow.org/install/source#tested_build_configurations). Thanks!

**Comment by gadagashwini** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
