### ISSUE TITLE
op name couldn't contain '_', '/' ?

### ISSUE THREAD

**Issue by haolujun** [tensorflow/tensorflow#33176]
Hi :

```
Name of the node - tower_0/Concat/concat/axis
Name of the node - tower_0/Concat/concat
Name of the node - tower_0/MatMul
Name of the node - tower_0/Add
Name of the node - tower_0/MatMul_1
Name of the node - tower_0/Add_1
Name of the node - tower_0/MatMul_2
Name of the node - tower_0/Add_2
Name of the node - tower_0/Sigmoid
Name of the node - tower_0/pre_2/shape
Name of the node - tower_0/pre_2
Name of the node - tower_0/MatMul_3
Name of the node - tower_0/Add_3
Name of the node - tower_0/MatMul_4
Name of the node - tower_0/Add_4
Name of the node - tower_0/MatMul_5
```

The above is part of op names in my model. When I use tensorflow c api:TF_GraphGetOpDef to get op detail, I found a problem: 
The op name which contain '_' or '/' couldn't be found, the message is ：`Op type not registered 'tower_0/Add_4' in binary running on xxx. Make sure the Op and Kernel are registered in the binary running in this process. Note that if you are loading a saved graph which used ops from tf.contrib, accessing (e.g.) `tf.contrib.resampler` should be done before importing the graph, as contrib ops are lazily registered when the module is first accessed.`

The op name which do not contain '_' or '/' could be found.  Why?

**Comment by mihaimaruseac** [comment]
Both `_` and `/` are reserved characters.

**Comment by haolujun** [comment]
Because some node names were generated by tensorflow self, How c api access these node with name contain '_' or '/' ?

**Comment by gowthamkpr** [comment]
@haolujun Can you please provide some reproducible code for us to expedite the process. Thanks!

**Comment by gowthamkpr** [comment]
@hajuho Are you still facing the issue?

**Comment by gowthamkpr** [comment]
Closing this issue as it has been inactive for more than two weeks. Please add additional comments and we can open this issue again. Thanks!
