### ISSUE TITLE
handling multiple graphs

### ISSUE THREAD

**Issue by mbz** [tensorflow/tensorflow#3317]
In numerous locations in the documentation, it has been mentioned that it is possible to handle multiple `Graph`s, but I couldn't find any example. 

Since `Session` only support a single `Graph`, it seems the only way of doing it is to create multiple `Session` instances. 

Is it **safe** to have multiple instances `Session` at the same time? 
if not, what is the proper way of handling multiple `Graph`s? 

Thanks

**Comment by jmchen-g** [comment]
You can do both ways:
1. Create multiple sessions;
2. Create a big graph which includes multiple small graphs.

And they can share the same set of variables and you just need to make sure it picks the right graph/session to run.

**Comment by michaelisard** [comment]
Please reopen if you have further questions.

**Comment by brando90** [comment]
Did anyone actually create an explicit (maybe small) example using either of the two suggestions?

**Comment by soloice** [comment]
I want an example, too. In principle I know how it works, but what's the details?
