### ISSUE TITLE
Module Not Found in docker build: tensorflow_datasets

### ISSUE THREAD

**Issue by intrepidOlivia** [tensorflow/tensorflow#33179]
I have been following the Docker instructions on the Tensorflow website (https://www.tensorflow.org/install/docker).
Trying to run the Jupyter notebook provided in the tensorflow docker images, specifically trying to run the tutorial here: https://github.com/tensorflow/docs/blob/master/site/en/tutorials/keras/text_classification.ipynb

But when I run the code segments in sequence, I get the following error:

```
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-3-7eaaf952f6e2> in <module>
      1 from tensorflow import keras
      2 
----> 3 import tensorflow_datasets as tfds
      4 tfds.disable_progress_bar()
      5 

ModuleNotFoundError: No module named 'tensorflow_datasets'
```

This would seem to be an issue with the Docker image since I would expect that module to be installed by default. 

**System information**
- OS Platform and Distribution: MacOS 10.15
- TensorFlow installed from (source or binary): 
`docker run -it -p 8888:8888 tensorflow/tensorflow:nightly-py3-jupyter`

**Comment by gowthamkpr** [comment]
@intrepidOlivia 
TensorFlow datasets is a standalone package. You need to install it separately.
Try,
`pip install tensorflow_datasets` before executing the script.
Feel free to reopen if problem still persists. Thanks!

**Comment by intrepidOlivia** [comment]
I can certainly try it, but the instructions do not indicate that this should be necessary. 

The instructions say this:
```
Start a Jupyter Notebook server using TensorFlow's nightly build with Python 3 support:
docker run -it -p 8888:8888 tensorflow/tensorflow:nightly-py3-jupyter
Follow the instructions and open the URL in your host web browser: http://127.0.0.1:8888/?token=...
```

Nowhere in the instructions or in the notebook is it mentioned that there are any additional dependencies.  Nor do they make it very clear how to install a dependency inside of the Docker container. Since this is a guide for beginners, perhaps a section should be added for instructing newbies on how to install additional dependencies inside of the docker container?  And perhaps the [tutorial text](https://github.com/tensorflow/docs/blob/master/site/en/tutorials/keras/text_classification.ipynb) should include some statement about its dependencies as well.

I'd be willing to do a PR to include this information, but I'm one of the aforementioned newbies and would need the information first.

**Comment by gowthamkpr** [comment]
I agree with you. Can you please try it and let me know if it helps in solving your issue. Thanks!

**Comment by intrepidOlivia** [comment]
Okay... I apologize, I'm new to all this.. What route do you think I should take? Should I try to modify the docker command to open a shell inside the docker container and pip install from there? That seems to defeat the purpose of having a docker container in the first place, especially one that has these notebooks installed. 

Should I maybe try to find and modify the Dockerfile associated with the `jupyter` tag instead to install its necessary dependencies? I found a description of the docker image here: https://hub.docker.com/layers/tensorflow/tensorflow/nightly-py3-jupyter/images/sha256-6fb0905855a23e4b202dd03535a0575b6b3ffd682cc27f1d99ab3d8be492b484
but I'm unsure how to extract or modify or make a pull request on it.

**Comment by gowthamkpr** [comment]
Unfortunately, you have to do it yourself @intrepidOlivia. You can follow the answer to this [question](https://www.quora.com/How-do-you-install-packages-in-a-Docker-container) to add a command to your docker file and build again to create a new image file. For more specific questions, you can post it on stackoverflow.

**Comment by intrepidOlivia** [comment]
I think maybe you are not understanding the scenario. I do not have my own Dockerfile, I am installing tensorflow jupyter files with the following command:

`docker run -it -p 8888:8888 tensorflow/tensorflow:nightly-py3-jupyter`

The docker container that is installed from this command does not have the necessary dependencies to operate the  included notebooks. I believe that the docker container should have the necessary dependencies to run the notebooks that it is installing. Please let me know which part of this is unclear, or if there is some other issue.

**Comment by gadagashwini** [comment]
I could reproduce the issue with nightly-py3-jupyter and latest-py3-jupyter Tensorflow docker images.

**Comment by gowthamkpr** [comment]
@intrepidOlivia Try using the previous versions of docker and let me know if you are still facing the same issue?

**Comment by wdirons** [comment]
Inside of the notebook you can run `!pip install tensorflow_datasets` before the code that imports tensorflow_datasets. Similar to how `!pip install seaborn` is done in regression.ipynb.

That change could be submitted as a pull request to https://github.com/tensorflow/docs

**Comment by gowthamkpr** [comment]
@intrepidOlivia Please follow the above recommendation and let me know if it helps.!

**Comment by mangeshw** [comment]
I am getting error No module named 'tensorflow_datasets'
Following is the code:
```
import matplotlib.pyplot as plt
import numpy as np
import tensorflow as tf
!pip install tensorflow_datasets
import tensorflow_datasets as tfds
```

**Comment by wdirons** [comment]
Sorry, for the pip package name it should have been a hyphen and not an underscore.

`!pip install tensorflow-datasets`

**Comment by wdirons** [comment]
A fix for this problem was merged yesterday in: https://github.com/tensorflow/docs/pull/1124

All docker containers created from that point on will contain this fix.

Just ensure you pull the latest image: `docker pull tensorflow/tensorflow:nightly-py3-jupyter`

**Comment by gowthamkpr** [comment]
Thanks @wdirons

**Comment by gowthamkpr** [comment]
Closing this issue as it has been resolved. Please add additional comments and we can open this issue again.

**Comment by zolon-zz** [comment]
Reproduced issue with docker latest-py3-jupyter

adding the above pip to the tutorial code works as a workaround.
