### ISSUE TITLE
tf1.12 keras input shape does not match the correct data feed

### ISSUE THREAD

**Issue by xuehuachunsheng** [tensorflow/tensorflow#33175]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): ubuntu16.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): 
- TensorFlow version (use command below): 1.12
- Python version: 3.6.9
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 9.0.176
- GPU model and memory:

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
```
import tensorflow as tf
from tensorflow.python import keras
import numpy as np
r_input = keras.layers.Input(shape=(), dtype=tf.float32, name='input_tensor')
r_output = keras.layers.Lambda(lambda x: x+1.)(r_input)
final_model = keras.models.Model(r_input, r_output)
c_input = np.asarray([1.])
ret = final_model.predict(c_input)
print(ret)
```
Raise `ValueError: Error when checking input: expected input_tensor to have 1 dimensions, but got array with shape (1, 1)`

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

In TF2.0, the code listed above can be run correctly. So I think it is a bug in tf1.12.

How to fix in tf1.12?
Line `r_input = keras.layers.Input(shape=(), dtype=tf.float32, name='input_tensor')`
can be replaced to `r_input = keras.layers.Input(shape=(1, ), dtype=tf.float32, name='input_tensor')` to fix this problem.

**Comment by gowthamkpr** [comment]
@This is a bug in Tensorflow 1.12 but has been fixed in later versions. Please find the github gist [here](https://colab.sandbox.google.com/gist/gowthamkpr/24c4c51235dbc238dc0314fd950d3d1e/untitled172.ipynb).
