### ISSUE TITLE
_list_all_concrete_functions_for_serialization doubles the trace count when called? 

### ISSUE THREAD

**Issue by cottrell** [tensorflow/tensorflow#33180]
I'm seeing the new warning "triggered tf.function retracing. Tracing is expensive and the excessive number of tracings" and was digging into it. When I printed *everything* that went through the offending function I only saw two tensors by (type, shape). This lead me to notice the following weird event that bumps (doubles) the trace count.

Is there some reason for this? If this is normal, I will try a minimal reproduction of the warning message that seems to not make sense.

```
import numpy as np
import tensorflow as tf

@tf.function
def f(a):
    tf.print(a.shape)
    return a


f(tf.convert_to_tensor(np.random.randn(4, 3).astype(np.float32))); print(f._get_tracing_count())
f(tf.convert_to_tensor(np.random.randn(4, 3).astype(np.float32))); print(f._get_tracing_count())
f(tf.convert_to_tensor(np.random.randn(4, 3).astype(np.float32))); print(f._get_tracing_count())
f(tf.convert_to_tensor(np.random.randn(4, 2).astype(np.float32))); print(f._get_tracing_count())
f(tf.convert_to_tensor(np.random.randn(4, 1).astype(np.float32))); print(f._get_tracing_count())
print(f._list_all_concrete_functions_for_serialization())
print(f._get_tracing_count())
```

Results in 

```
TensorShape([4, 3])
1
TensorShape([4, 3])
1
TensorShape([4, 3])
1
TensorShape([4, 2])
2
TensorShape([4, 1])
3
[<tensorflow.python.eager.function.ConcreteFunction object at 0x7fa32c03b438>, <tensorflow.python.eager.function.ConcreteFunction object at 0x7fa3247f4438>, <tensorflow.python.eager.function.ConcreteFunction object at 0x7fa3247f4f60>]
6
```

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.0.0
- Python version: 3.7
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**

**Describe the expected behavior**

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by ravikyram** [comment]
I have tried on colab with TF version 2.0.0 ,2.0.0-dev20191002 and was able to reproduce the issue.Please, find the gist [here](https://colab.sandbox.google.com/gist/ravikyram/39c39a352dfea0cd9375a6b6235ce995/untitled252.ipynb).Thanks!

**Comment by ravikyram** [comment]
@cottrell 
Can you please let us know is this the expected behavior in the attached [colab](https://colab.sandbox.google.com/gist/ravikyram/39c39a352dfea0cd9375a6b6235ce995/untitled252.ipynb#scrollTo=x89GS3WvYGAK). I am not seeing any warning message . Can you please elaborate the issue with the context. Thanks!

**Comment by cottrell** [comment]
I think you just need a few more calls to trigger the tracing warning (see more below).

The tracing warning is mererly *why* I was looking into this. The doubling of the tracing count is something I don't understand at this point. Could be a feature not sure.

```
import numpy as np
import tensorflow as tf

@tf.function
def f(a):
    tf.print(a.shape)
    return a


f(tf.convert_to_tensor(np.random.randn(4, 3).astype(np.float32))); print(f._get_tracing_count())
f(tf.convert_to_tensor(np.random.randn(4, 3).astype(np.float32))); print(f._get_tracing_count())
f(tf.convert_to_tensor(np.random.randn(4, 3).astype(np.float32))); print(f._get_tracing_count())
f(tf.convert_to_tensor(np.random.randn(4, 2).astype(np.float32))); print(f._get_tracing_count())
f(tf.convert_to_tensor(np.random.randn(4, 1).astype(np.float32))); print(f._get_tracing_count())

f(tf.convert_to_tensor(np.random.randn(4, 12).astype(np.float32))); print(f._get_tracing_count())

f(tf.convert_to_tensor(np.random.randn(4, 11).astype(np.float32))); print(f._get_tracing_count())
f(tf.convert_to_tensor(np.random.randn(4, 15).astype(np.float32))); print(f._get_tracing_count())
f(tf.convert_to_tensor(np.random.randn(4, 18).astype(np.float32))); print(f._get_tracing_count())
print(f._list_all_concrete_functions_for_serialization())
print(f._get_tracing_count())
```

**Comment by kkimdev** [comment]
Hi,

`f._get_tracing_count()` counts the number of times that the function is traced. When `f._list_all_concrete_functions_for_serialization()` is called, the function is actually traced again 3 times in your example.  You can verify that by inserting `print('Traced')` in the `f`'s function body.

For the warning message, it doesn't use `f._get_tracing_count()`, it uses `f._call_counter.get_tracing_count()` to count the tracing and that's not increased with `f._list_all_concrete_functions_for_serialization()`
