### ISSUE TITLE
Build TF 2.0 Windows

### ISSUE THREAD

**Issue by sonfiree** [tensorflow/tensorflow#33181]
` C++ compilation of rule '//tensorflow/core/kernels:eigen_contraction_kernel_with_mkl' failed (Exit 2): python.exe failed: error executing command
`

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): windows 10
- Python version: 3.7
- Installed using virtualenv? pip? conda?: pip
- Bazel version (if compiling from source): 0.26.1
- GCC/Compiler version (if compiling from source): vs 2017
- CUDA/cuDNN version: 7.4
- GPU model and memory: 1060 6GB

**Describe the problem**

**Provide the exact sequence of commands / steps that you executed before running into the problem**

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by feranick** [comment]
Does the command `python.exe` actually run in the console?

**Comment by sonfiree** [comment]
> Does the command `python.exe` actually run in the console?

yeap

**Comment by gadagashwini** [comment]
@sonfiree, Did you follow the instructions mentioned in [this link](https://www.tensorflow.org/install/source_windows). And also provide the exact sequence of commands / steps that you executed before running into the problem. Thanks!

**Comment by sonfiree** [comment]
```
git clone https://github.com/tensorflow/tensorflow.git
cd tensorflow
python ./configure.py 
       def all, Cuda try
bazel build --config=opt --config=cuda --define=no_tensorflow_py_deps=true //tensorflow/tools/pip_package:build_pip_package

```

TF 1.14 it`s work

**Comment by gadagashwini** [comment]
@sonfiree, Please provide the CUDA version. Thanks!

**Comment by sonfiree** [comment]
CUDA 10.0 not work
CUDA 10.1 not work

**Comment by mihaimaruseac** [comment]
Please provide full log. I suggest `bazel clean --expunge; bazel build --config=cuda //tensorflow/tools/pip_package:build_pip_package`

**Comment by sonfiree** [comment]
The question can probably be hidden. I stayed at 1.4 and no longer plan to use TF. I turn to pytorch

**Comment by mihaimaruseac** [comment]
Well, you offered no information that could have helped in debugging and allowing us to help you
