### ISSUE TITLE
TF-TRT batchSize > 0 && batchSize <= MAX_BATCH_SIZE

### ISSUE THREAD

**Issue by sgambient** [tensorflow/tensorflow#33184]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below):1.14.0
- Python version:2.7
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:10.1
- GPU model and memory:T4

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
Seeing the following error.

```
2019-10-09 22:38:11.629630: I tensorflow/compiler/tf2tensorrt/kernels/trt_engine_op.cc:632] Building a new TensorRT engine for XXX input shapes: [[0,28,28,128]]
2019-10-09 22:38:11.629841: E tensorflow/compiler/tf2tensorrt/utils/trt_logger.cc:41] DefaultLogger Parameter check failed at: ../builder/builder.cpp::setMaxBatchSize::113, condition: batchSize > 0 && batchSize <= MAX_BATCH_SIZE
```

**Describe the expected behavior**
Ideally, would not like to see the error.   As currently seeing  the error,  more information along the following line will help a lot determining the root cause.

1.  See more detailed  log on what the offending  layers and tensors are. 
2.  What  exactly is the value that is the issue, in this case batchSize ? 
3. Where  in  code this is  occurring - do not see any file called builder* in TF 1.14 source. 
    If error in happening elsewhere in third-party code ( in this case , may be in NVIDIA  TensorRT closed source )  - making that explicit. 
4. In this case, where is it getting 0 for batch size. 

**Code to reproduce the issue**
It is not possible to provide code for every issue.  Better logging is a much more  efficient way to root cause and resolve issues. 

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by rmothukuru** [comment]
@sgambient,
You have mentioned, 

> See more detailed log on what the offending layers and tensors are.

 Can you please provide detailed log, as mentioned above.

**Comment by sgambient** [comment]
Would not be possible for me to spend time to get you a toy code.  You should add more logs or traces.

**Comment by jvishnuvardhan** [comment]
@sgambient Sorry for the delay in my response. Can you try with TF1.15 stable version as there were some known issues with TF1.14.0? Thanks!

**Comment by aaroey** [comment]
@sgambient Based on the log it seems the model gets an input with 0 elements, could you help to confirm that?

Also @pooyadavoodi

**Comment by aaroey** [comment]
Also @sanjoy

**Comment by pooyadavoodi** [comment]
This is probably a bug in TF-TRT. Somehow it generates a tensor with 0 batch size as the input to TRT. I am assuming the input to the graph has a valid shape.

I also agree that the log can be improved. It needs to be improved inside TRT. I'll report that.

**Comment by pooyadavoodi** [comment]
> I also agree that the log can be improved. It needs to be improved inside TRT. I'll report that.
This is already improved in the future versions of TRT.

**Comment by aalugore** [comment]
I am also seeing this while using TF2.1 and TensorRT 7. Not sure where this should be reported, but maybe someone here knows. Here's what mine looks like:
`2020-01-23 21:07:28.087833: I tensorflow/compiler/tf2tensorrt/kernels/trt_engine_op.cc:736] Building a new TensorRT engine for StatefulPartitionedCall/BatchMultiClassNonMaxSuppression_1/map/while/MultiClassNonMaxSuppression/ClipToWindow_87/TRTEngineOp_88 with
input shapes: [[0,4]]
2020-01-23 21:07:28.096508: E tensorflow/compiler/tf2tensorrt/utils/trt_logger.cc:42] DefaultLogger Parameter check failed at: ../builder/builder.cpp::setMaxBatchSize::135, condition: batchSize > 0 && batchSize <= MAX_BATCH_SIZE`

**Comment by aalugore** [comment]
System information

Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
OS Platform and Distribution (e.g., Linux Ubuntu 16.04): RHEL 7.6
Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
TensorFlow installed from (source or binary): binary
TensorFlow version (use command below):2.1
Python version:3.6
Bazel version (if compiling from source): N/A
GCC/Compiler version (if compiling from source): N/A
CUDA/cuDNN version:10.2/7.6
GPU model and memory:Nvidia Tesla V100

Recreate steps:
-Clone repository below and follow instructions
https://github.com/tensorflow/tensorrt/tree/master/tftrt/examples/object_detection
-Models used came from here https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/detection_model_zoo.md
For my specific examples i tried mask_rcnn_inception_v2_coco and faster_rcnn_inception_v2_coco

**Comment by aaroey** [comment]
@bixia1 could you help to take a look at the repro above? Thanks.

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.
