### ISSUE TITLE
TFTRT:  Huge events file generated.

### ISSUE THREAD

**Issue by sgambient** [tensorflow/tensorflow#33189]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):binary
- TensorFlow version (use command below):1.14
- Python version:2.7
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:10.1
- GPU model and memory:T4

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
Very very large events files  are generated  when TF-TRT is enabled.  These files are so big that Tensorboard is able to handle those.  For example,  in one network, TF produces an event file of 4.6 MB size. The  same network after TF-TRT compile, generates an event file of 1.3 GB !! 

**Describe the expected behavior**

A reasonable size. 

**Code to reproduce the issue**
Not able to provide any code at this point.   However, the sympton is possibly reproducible with any large network such as ResNet1XX . 

**Other info / logs**

**Comment by jvishnuvardhan** [comment]
@sgambient Could you provide more details on TF-TRT compile so that we can find root-cause of the issue. If you can provide any standalone code would be better. Thanks!

**Comment by jvishnuvardhan** [comment]
@sgambient Is this still an issue? Please close the issue if this was resolved already. Thanks!

**Comment by jvishnuvardhan** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
