### ISSUE TITLE
Why my tensorflow-gpu runs only on  GPU?

### ISSUE THREAD

**Issue by sonfiree** [tensorflow/tensorflow#33194]
Not work TF 2.0
```
config = tf.compat.v1.ConfigProto(
        device_count = {'GPU': 0}
    )
sess = tf.compat.v1.Session(config=config)
tf.compat.v1.keras.backend.set_session(sess)
```

**Comment by gadagashwini** [comment]
@sonfiree, Could you please elaborate the issue and also describe the expected behavior and current behavior. Thanks!

**Comment by sonfiree** [comment]
Using the code above, I run the execution on the CPU. But in version 2.0, it does not work.
I have a version for the GPU, but sometimes I want to run code on the CPU for texts

**Comment by sonfiree** [comment]
The network still runs on the GPU

**Comment by ymodak** [comment]
@sonfiree Is this still an issue? TF 2.0 requires CUDA 10.0. What version of cuda have you intsalled?
Also can you please print the o/p of ;
```python
import tensorflow as tf
tf.test.is_built_with_gpu_support()
```

**Comment by sonfiree** [comment]
> @sonfiree Is this still an issue? TF 2.0 requires CUDA 10.0. What version of cuda have you intsalled?
> Also can you please print the o/p of ;
> 
> ```python
> import tensorflow as tf
> tf.test.is_built_with_gpu_support()
> ```


Unfortunately there was a wrong question.
I want to run cpu code installed version for gpu

**Comment by ymodak** [comment]
If a TensorFlow operation has both CPU and GPU implementations, by default the GPU devices will be given priority when the operation is assigned to a device.

You can do manual placement of devices and execute ops on cpu.
See https://www.tensorflow.org/guide/gpu#manual_device_placement
For example;
```python
tf.debugging.set_log_device_placement(True)

# Place tensors on the CPU
with tf.device('/CPU:0'):
  a = tf.constant([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]])
  b = tf.constant([[1.0, 2.0], [3.0, 4.0], [5.0, 6.0]])
  c = tf.matmul(a, b)
print(c)
```
Output:
```python
Tensor("MatMul_1:0", shape=(2, 2), dtype=float32, device=/device:CPU:0)
```

**Comment by sonfiree** [comment]
And how to use this together with the tf.keras API?
```
with tf.device('/CPU:0'):
   code...

```

**Comment by adragoset** [comment]
This is broken in tf 1.14 as well 
device_count = {'GPU': 0} is ignored and gpu is prioritized anyway.

**Comment by sonfiree** [comment]
device_count = {'GPU': 0}, it`s work for me in tf1.14

**Comment by adragoset** [comment]
Not sure about that my tests were passing in 1.12 but broke when i upgraded to 1.14 and im seeing TF forced to gpu where it breaks tensorrt libraries im using. At any rate setting CUDA_VISIBLE_DEVICES=0 should force to CPU in 1.14 and that isnt working either.

**Comment by sonfiree** [comment]
I launched two identical models.
I launched the first one on GPU (1060) and loaded the memory to the maximum
The second on the CPU and downloaded 2x from the GPU.
Departures weren’t working.

**Comment by ymodak** [comment]
> And how to use this together with the tf.keras API?
> 
> ```
> with tf.device('/CPU:0'):
>    code...
> ```

Apologies for the delay in response. Yes that approach will do.
