### ISSUE TITLE
About a function ： tf.train.slice_input_producer()

### ISSUE THREAD

**Issue by Libaididi** [tensorflow/tensorflow#33197]
when I use the function ：input_queue = tf.train.slice_input_producer([image, label]).
A error come to me:AttributeError: module 'tensorflow_core._api.v2.train' has no attribute 'slice_input_producer'

I want to know how can I solve the problem.

is there anyone who can help me.

**Comment by oanush** [comment]
@Libaididi ,
Can you try using input_queue = `tf.data.Dataset.from_tensor_slices([image, label]) `as `tf.train.slice_input_producer` is depreciated in the Latest version? Thanks!

**Comment by oanush** [comment]
@Libaididi ,
Hi, Any update on the issue ?Thanks!

**Comment by oanush** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Comment by qli51** [comment]
can't work cause InvalidArgumentError: cannot compute Pack as input #1(zero-based) was expected to be a string tensor but is a int32 tensor [Op:Pack] name: component_0

**Comment by aviniciux** [comment]
I've successfully solve this error by replacing from:

`tf.train.slice_input_producer`

to

` tf.compat.v1.train.slice_input_producer`

in tensorflow version 2.1.0

**Comment by aviniciux** [comment]
> @Libaididi ,
> Hi, Any update on the issue ?Thanks!

I've successfully solve this error by replacing from:

tf.train.slice_input_producer

to

tf.compat.v1.train.slice_input_producer

in tensorflow version 2.1.0

**Comment by GaganaB** [comment]
tf.compat.v1.train.slice_input_producer works for me.
