### ISSUE TITLE
Tensorflow 2.0, feature_column and input_layer

### ISSUE THREAD

**Issue by aszalucha** [tensorflow/tensorflow#33198]
Documentation for tf.feature_column like for example:
https://www.tensorflow.org/api_docs/python/tf/feature_column/categorical_column_with_vocabulary_file

uses input_layer, which is not available in v2
```
columns = [embedding_column(states, 3),...]
features = tf.io.parse_example(..., features=make_parse_example_spec(columns))
dense_tensor = input_layer(features, columns)
```

**Comment by gadagashwini** [comment]
@aszalucha, 
The document which you are referring is related to Tf 2.0. `input_layer` is available in v2. 
Let us know if I misunderstood your issue. Thanks!

**Comment by aszalucha** [comment]
It is available as a `tf.compat.v1.feature_column.input_layer` so as I understand it is not "native" to TF 2.0. Or I misunderstood sth?

**Comment by gadagashwini** [comment]
@aszalucha, `tf.compat.v1.feature_column.input_layer` is available in Tf 2.0. The tf_upgrade_v2 script includes the compat.v1 module. This module replaces Tf 1.x symbols to tf.compat.v1 compatibility module in Tf 2.0. Please refer [this link](https://www.tensorflow.org/guide/upgrade#compatibility_modules) for more info. Thanks!

**Comment by aszalucha** [comment]
So that link exactly proves my point "While the compatibility module is nice, we recommend that you manually proofread replacements and migrate them to new APIs in the tf.* namespace instead of tf.compat.v1 namespace as quickly as possible."

If documentation recommends to replace` tf.compat.v1.*`, why documentation for TF 2.0 uses those symbols?

**Comment by jvishnuvardhan** [comment]
@aszalucha It is suggested for users who have used TF1.x and are trying to use TF2.x. Once the user get familiarize with TF2.x style, they can use the log generated while conversion to update the codes by replacing `tf.compat.v1.*` with correct symbols. Please read the [migration guide](https://www.tensorflow.org/guide/migrate) for more details. If you face any issues, please post them here. Thanks!

I am closing the issue. Please open a new issue if you face any conversion related problems.  Thanks!
