### ISSUE TITLE
Link error using c api: undefined reference to symbol 'powf@@GLIBC_2.2.5'

### ISSUE THREAD

**Issue by chenghuige** [tensorflow/tensorflow#332]
http://theyoungcoder.com/loading-a-tensorflow-graph-with-the-c-api/
I followed this acticle. 

1	cc_binary(
2	name = "loader",
3	srcs = ["loader.cc"],
4	deps = [
5	"//tensorflow/core:tensorflow",
6	]
7	)
Here’s the final directory structure:
• tensorflow/tensorflow/loader/
• tensorflow/tensorflow/loader/loader.cc
• tensorflow/tensorflow/loader/BUILD
Compile & Run
• From inside the project folder call bazel build :loader.
• From the repository root, go into bazel-bin/tensorflow/loader.
• Copy the graph protobuf to models/train.pb.

Then run ./loader and check the output!

But when building I got link error
Slow read: a 551318010-byte read from /home/users/chenghuige/.cache/bazel/_bazel_chenghuige/56e262ed5e70da1d7ac42e55562c6970/tensorflow/bazel-out/local_linux-fastbuild/bin/tensorflow/core/libkernels.lo took 6143ms.
INFO: From Linking tensorflow/loader/loader:
/usr/bin/ld: bazel-out/local_linux-fastbuild/bin/tensorflow/core/libkernels.lo(cwise_op_pow.pic.o): undefined reference to symbol 'powf@@GLIBC_2.2.5'
/usr/bin/ld: note: 'powf@@GLIBC_2.2.5' is defined in DSO /top/lib/libm.so.6 so try adding it to the linker command line
/top/lib/libm.so.6: could not read symbols: Invalid operation
collect2: error: ld returned 1 exit status
ERROR: /home/users/chenghuige/other/tensorflow/tensorflow/loader/BUILD:1:1: Linking of rule '//tensorflow/loader:loader' failed: gcc failed: error executing command /usr/bin/gcc -o bazel-out/local_linux-fastbuild/bin/tensorflow/loader/loader bazel-out/local_linux-fastbuild/bin/tensorflow/loader/_objs/loader/tensorflow/loader/loader.pic.o -Wl,-whole-archive ... (remaining 45 argument(s) skipped): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
Target //tensorflow/loader:loader failed to build
Use --verbose_failures to see the command lines of failed build steps.

**Comment by mrry** [comment]
It sounds like you're using an older version of glibc than we support (2.2.5, rather than 2.17). You could try adding `"-lm"` to the returned value from `tf_copts()` in `tensorflow.bzl` (see [here](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tensorflow.bzl#L40)), but there might be other problems that arise afterwards.

I'd recommend trying to update the version of libc on your machine, or using a Docker container to experiment with a different operating system in a known-good configuration.

**Comment by chenghuige** [comment]
@mrry Actually on my platform, we have 
/opt/compiler/gcc-4.8.2/lib/libm.so.6  which is of version 2.18 glibc
How can I let the program using this one instead of  /top/lib/libm.so.6 ?

**Comment by girving** [comment]
@mrry: Should we close as won't fix due to the version issue?

**Comment by mrry** [comment]
I think so. It sounds like a Bazel issue, not picking up the appropriate libraries from a non-standard location.
