### ISSUE TITLE
KMP_AFFINITY problem when doing import from keras (backend: TF) and using sklearn

### ISSUE THREAD

**Issue by idohi** [tensorflow/tensorflow#33209]
Have a problem when doing import from keras (backend: TensorFlow) and using sklearn.preprocessing.StandardScaler
details:
Windows10
TensorFlow 1.14 (working with CPU)
keras 2.2.4
pycharm 2019.2.2 (community edition)

To reproduce:
Run(python)-
`from sklearn.preprocessing import StandardScaler`
`import numpy as np`
`from keras.models import Sequential`
`A = np.random.rand(4001,2)`
`scaler = StandardScaler()`
`scaler.fit(X=A)`
`B = scaler.transform(A)`

Resuls:
1. if `from keras.models import Sequential` removed works fine.
2. if the sized of `A` reduce (for 4000 x 2 as example) works fine.
3. else the last step `B = scaler.transform(A)` resulted with-
> Using TensorFlow backend.
> OMP: Info #212: KMP_AFFINITY: decoding x2APIC ids.
> OMP: Info #210: KMP_AFFINITY: Affinity capable, using global cpuid leaf 11 info
> OMP: Info #154: KMP_AFFINITY: Initial OS proc set respected: 0-7
> OMP: Info #156: KMP_AFFINITY: 8 available OS procs
> OMP: Info #157: KMP_AFFINITY: Uniform topology
> OMP: Info #179: KMP_AFFINITY: 1 packages x 4 cores/pkg x 2 threads/core (4 total cores)
> OMP: Info #214: KMP_AFFINITY: OS proc to physical thread map:
> OMP: Info #171: KMP_AFFINITY: OS proc 0 maps to package 0 core 0 thread 0 
> OMP: Info #171: KMP_AFFINITY: OS proc 1 maps to package 0 core 0 thread 1 
> OMP: Info #171: KMP_AFFINITY: OS proc 2 maps to package 0 core 1 thread 0 
> OMP: Info #171: KMP_AFFINITY: OS proc 3 maps to package 0 core 1 thread 1 
> OMP: Info #171: KMP_AFFINITY: OS proc 4 maps to package 0 core 2 thread 0 
> OMP: Info #171: KMP_AFFINITY: OS proc 5 maps to package 0 core 2 thread 1 
> OMP: Info #171: KMP_AFFINITY: OS proc 6 maps to package 0 core 3 thread 0 
> OMP: Info #171: KMP_AFFINITY: OS proc 7 maps to package 0 core 3 thread 1 
> OMP: Info #250: KMP_AFFINITY: pid 17364 tid 16076 thread 0 bound to OS proc set 0

**Comment by Rudra51299** [comment]
I ran code in python and it works fine for me. Can you be more specific about where is the problem coming?

**Comment by idohi** [comment]
These Info messages arose when running the last command `B = scaler.transform(A)` 
details:
Windows10
TensorFlow 1.14 (working with CPU)
keras 2.2.4
pycharm 2019.2.2 (community edition)
Anaconda 2018.12
Python 3.6
scipy 1.2.1
sklearn 0.21.2

What other information would be useful?

**Comment by oanush** [comment]
@idohi ,
When tried executing the code in colab for latest version TF-1.15rc3 and TF-1.14, it worked fine without any issues. Take a look at [gist](https://colab.sandbox.google.com/gist/oanush/6289916ffe824317e0295ec57f774524/33209.ipynb) of colab.Thanks!

**Comment by idohi** [comment]
@oanush ,
Running on colab works fine for me, but the issue is occur on the environment of my computer.

**Comment by jvishnuvardhan** [comment]
@idohi I think this is not related to Tensorflow.
This is not Build/Installation or Bug/Performance issue. Please post this kind of support questions at [Stackoverflow](https://stackoverflow.com/questions/tagged/tensorflow). There is a big community to support and learn from your questions. GitHub is mainly for addressing bugs in installation and performance. Thanks!
