### ISSUE TITLE
compile tensorflow r1.14 with tensorrt error

### ISSUE THREAD

**Issue by ltm920716** [tensorflow/tensorflow#33207]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): centos 7.3
- TensorFlow installed from (source or binary):source
- TensorFlow version:1.14
- Python version:3.6
- Bazel version (if compiling from source):0.24.1
- GCC/Compiler version (if compiling from source):6.5
- CUDA/cuDNN version:10.0/7.6.1
- GPU model and memory:tesla V100

**Describe the problem**
Tensorrt 5.1.5
nccl 2.4.8
when i compile tensorflow use  ./configure ,the log is bellow:

Please specify the CUDA SDK version you want to use. [Leave empty to default to CUDA 10]:

Please specify the cuDNN version you want to use. [Leave empty to default to cuDNN 7]:

Please specify the TensorRT version you want to use. [Leave empty to  default to TensorRT 5

Please specify the locally installed NCCL version you want to use. [Leave empty to use http

Please specify the comma-separated list of base paths to look for CUDA libraries and header

Could not find any NvInferVersion.h matching version '5' in any subdirectory:
        ''
        'include'
        'include/cuda'
        'include/*-linux-gnu'
        'extras/CUPTI/include'
        'include/cuda/CUPTI'
of:
        '/lib64'
        '/usr'
        '/usr/lib64/dyninst'
        '/usr/local/cuda'
        '/usr/local/cuda-10.0/targets/x86_64-linux/lib'
Asking for detailed CUDA configuration...

are some versions wrong？

**Comment by gadagashwini** [comment]
@ltm920716, Just to verify, Did you set the path of TensorRT and NCCL during ./configure. Thanks!

**Comment by ltm920716** [comment]
> @ltm920716, Just to verify, Did you set the path of TensorRT and NCCL during ./configure. Thanks!

Thanks

**Comment by superhg2012** [comment]
I met same issue ! how did you solve it? @ltm920716

**Comment by hudengjunai** [comment]
> I met same issue ! how did you solve it? @ltm920716
I alose met the same issue, have you solved the problem?

**Comment by tuxxi** [comment]
I was having the same issue. The crux of my problem was that the error message says the configuration was looking for `NvInferVersion.h`, which I couldn't find anywhere (using `locate NvInferVersion.h`). I looked into the configuration and it seems it tries to find `NvInferVersion.h` *after failing to find* `NvInfer.h`.
```python

  try:
    header_path, header_version = _find_header(base_paths, "NvInfer.h",
                                               required_version,
                                               get_header_version)
  except ConfigError:
    # TensorRT 6 moved the version information to NvInferVersion.h.
    header_path, header_version = _find_header(base_paths, "NvInferVersion.h",
                                               required_version,
                                               get_header_version)
```

Thus, all I needed to do was pass the correct path to `NvInfer,h`, which can be found using `locate NvInfer.h`. I thought I had done this already, but alas, I had not...

FWIW, Building for TensorRT 5, cuDNN 7, and CUDA 10.0 on Ubuntu 16.04, this is my full list of paths: 
```
/usr/local/cuda-10.0/targets/x86_64-linux/include/,/usr/local/cuda-10.0/targets/x86_64-linux/lib/,/usr/local/cuda-10.0/bin/,/usr/local/cuda-10.0/,/usr/include/,/usr/lib/x86_64-linux-gnu/,/usr/include/x86_64-linux-gnu/
```
