### ISSUE TITLE
TF 2.0: Functions and packages autocomplete broken in PyCharm

### ISSUE THREAD

**Issue by georgealexandruvlad** [tensorflow/tensorflow#33218]
from tensorflow.**_keras_** import **_callbacks_**
from tensorflow._**keras.optimizers**_ import **_Adam_**

The packages in bold are just a few examples that are not recognized in PyCharm. The issue was first spotted and reported in rc release. At that time we've been told to wait for the release of 2.0 because the issue is a bit more complex. The 2.0 is now here and as far as I am concerned the issue still persists. There are any configurations to be made in order to work or this problem is still an unresolved issue?

PyCharm gives the following complaint: 
```Cannot find reference 'keras' in '__init__.py'```

**Comment by ravikyram** [comment]
@georgealexandruvlad 

Looks like similar issue  #31973.Please let us know. Thanks!

**Comment by georgealexandruvlad** [comment]
@ravikyram Yes, it's similar, but there the title contains "[TF 2.0.0-rc0]" which I find confusing for people searching for this exact issue. There are different releases and I thought the issue should refer to the current one. If you consider this is redundant feel free to close it and I will follow the other one.
Also, there is any date by which we could expect this to be solved or it's ASAP?

**Comment by angeliand** [comment]
The recommended way to import is the following:
```
import tensorflow as tf
....
#usage
tf.keras.callbacks.—
tf.keras.optimizers.—
```
Also for me the PyCharm 2019.3 EAP helped with resolving the references in the stable release, and since using it, I had no further issue. That said, I use the format from above.

**Comment by Mulns** [comment]
Try this simple solution for current situation (tf: 2.0) :

- Go to dir `/python3/site-packages/` and change the name of `/tensorflow/` to `/tensorflow_back`, then change the name of `/tensorflow_core/` to `/tensorflow/` (only use core api)

- Go to file `/tensorflow/__init__.py` (which was in `/tensorflow_core/` ), add the following codes:
`from .python.keras.api._v2 import keras`
`from tensorflow_estimator.python.estimator.api._v2 import estimator`

TF2.0 use lazy import, so this solution works in vscode, and maybe works in pycharm.
(https://github.com/tensorflow/tensorflow/issues/32982#issuecomment-541286669)

**Comment by georgealexandruvlad** [comment]
The issue was resolved by using @angeliand 's solution. It seems PyCharm EAP works with tf2.0. @Mulns  thank you for your response as well, if I will encounter the same issue in the future I will consider trying your solution. As the problem has been solved I will close the issue.

**Comment by KimRasak** [comment]
> That said, I use the format from above.



> The recommended way to import is the following:
> 
> ```
> import tensorflow as tf
> ....
> #usage
> tf.keras.callbacks.—
> tf.keras.optimizers.—
> ```
> 
> Also for me the PyCharm 2019.3 EAP helped with resolving the references in the stable release, and since using it, I had no further issue. That said, I use the format from above.

Thanks man, that really worked for me.

**Comment by xggIoU** [comment]
PyCharm 2019.3 EAP version worked! 
https://www.jetbrains.com/pycharm/nextversion/?_ga=2.221720863.623821984.1573808626-1607002874.1573808626

**Comment by jnd77** [comment]
Even with latest PyCharm, some of the TF 1.15 imports are still not recognized, such as tf.saved_model, tf.error, ...

**Comment by ulken94** [comment]
try import keras like this:### 

`import tensorflow.keras as keras

# usage
keras.layers.Dense`

it works for me :)

**Comment by ulken94** [comment]
`<python>
asd
</python>`

**Comment by ulken94** [comment]
`
import tensorflow.keras as keras

keras.layers.Dense(..)
`

**Comment by brotherofken** [comment]
@jnd77 
> Even with latest PyCharm, some of the TF 1.15 imports are still not recognized, such as tf.saved_model, tf.error, ...

I found that this hack makes PyCharm somehow happy with tensorflow 1.15.
```
from typing import TYPE_CHECKING
if TYPE_CHECKING:
    import tensorflow_core.python as tf
else:
    import tensorflow as tf
```
However, this way has a lot of cons.
