### ISSUE TITLE
Tensorflow with GPU on Mac OSX: Works in Python but NOT IPython

### ISSUE THREAD

**Issue by xjdeng** [tensorflow/tensorflow#3321]
GitHub issues are for bugs / installation problems / feature requests.  
For general support from the community, see [StackOverflow](https://stackoverflow.com/questions/tagged/tensorflow).
To make bugs and feature requests more easy to find and organize, we close issues that are deemed
out of scope for GitHub Issues and point people to StackOverflow.

For bugs or installation issues, please provide the following information.
The more information you provide, the more easily we will be able to offer
help and advice.

### Environment info
Operating System: Mac OSX 10.11.5

Installed version of CUDA and cuDNN: 
(please attach the output of `ls -l /path/to/cuda/lib/libcud*`): 7.5

lrwxr-xr-x  1 root  admin    13 Jul 14 13:25 /usr/local/cuda/lib/libcuda.1.dylib -> libcuda.dylib
-rwxr-xr-x  1 root  wheel  8280 Apr 12 23:02 /usr/local/cuda/lib/libcuda.dylib
lrwxr-xr-x  1 root  wheel    45 Apr 12 23:03 /usr/local/cuda/lib/libcudadevrt.a -> /Developer/NVIDIA/CUDA-7.5/lib/libcudadevrt.a
lrwxr-xr-x  1 root  wheel    50 Apr 12 23:03 /usr/local/cuda/lib/libcudart.7.5.dylib -> /Developer/NVIDIA/CUDA-7.5/lib/libcudart.7.5.dylib
lrwxr-xr-x  1 root  wheel    46 Apr 12 23:03 /usr/local/cuda/lib/libcudart.dylib -> /Developer/NVIDIA/CUDA-7.5/lib/libcudart.dylib
lrwxr-xr-x  1 root  wheel    49 Apr 12 23:03 /usr/local/cuda/lib/libcudart_static.a -> /Developer/NVIDIA/CUDA-7.5/lib/libcudart_static.a
lrwxr-xr-x  1 root  admin    47 Jul 14 12:37 /usr/local/cuda/lib/libcudnn.5.dylib -> /Developer/NVIDIA/CUDA-7.5/lib/libcudnn.5.dylib
lrwxr-xr-x  1 root  admin    45 Jul 14 12:37 /usr/local/cuda/lib/libcudnn.dylib -> /Developer/NVIDIA/CUDA-7.5/lib/libcudnn.dylib
lrwxr-xr-x  1 root  admin    48 Jul 14 12:37 /usr/local/cuda/lib/libcudnn_static.a -> /Developer/NVIDIA/CUDA-7.5/lib/libcudnn_static.a

If installed from binary pip package, provide:

1. Which pip package you installed.  tensorflow
2. The output from `python -c "import tensorflow; print(tensorflow.__version__)"`.

I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcublas.7.5.dylib locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcudnn.5.dylib locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcufft.7.5.dylib locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcuda.1.dylib locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcurand.7.5.dylib locally
0.9.0

If installed from sources, provide the commit hash:

### Steps to reproduce
1. Install Anaconda 64-bit Python 2.7
2. Install Tensorflow for Mac with GPU support according to [these instructions](https://www.tensorflow.org/versions/r0.9/get_started/os_setup.html#installation-for-mac-os-x). Make sure to fix the [segmentation fault bug](https://github.com/tensorflow/tensorflow/issues/3263) as well.
3. Open up ipython (not python) and import tensorflow

It works in Python:
```
Xiaojians-MacBook-Pro:lib xjdeng$ python
Python 2.7.11 |Anaconda 4.0.0 (x86_64)| (default, Dec  6 2015, 18:57:58) 
[GCC 4.2.1 (Apple Inc. build 5577)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://anaconda.org
>>> import tensorflow
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcublas.7.5.dylib locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcudnn.5.dylib locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcufft.7.5.dylib locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcuda.1.dylib locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcurand.7.5.dylib locally
>>> 
```

But not iPython:
```
Xiaojians-MacBook-Pro:lib xjdeng$ ipython
Python 2.7.11 |Anaconda 4.0.0 (x86_64)| (default, Dec  6 2015, 18:57:58) 
Type "copyright", "credits" or "license" for more information.

IPython 4.1.2 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: import tensorflow
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-a649b509054f> in <module>()
----> 1 import tensorflow

/Users/xjdeng/anaconda/lib/python2.7/site-packages/tensorflow/__init__.py in <module>()
     21 from __future__ import print_function
     22 
---> 23 from tensorflow.python import *

/Users/xjdeng/anaconda/lib/python2.7/site-packages/tensorflow/python/__init__.py in <module>()
     46 _default_dlopen_flags = sys.getdlopenflags()
     47 sys.setdlopenflags(_default_dlopen_flags | ctypes.RTLD_GLOBAL)
---> 48 from tensorflow.python import pywrap_tensorflow
     49 sys.setdlopenflags(_default_dlopen_flags)
     50 

/Users/xjdeng/anaconda/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow.py in <module>()
     19         except ImportError:
     20             return importlib.import_module('_pywrap_tensorflow')
---> 21     _pywrap_tensorflow = swig_import_helper()
     22     del swig_import_helper
     23 elif _swig_python_version_info >= (2, 6, 0):

/Users/xjdeng/anaconda/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow.py in swig_import_helper()
     18             return importlib.import_module(mname)
     19         except ImportError:
---> 20             return importlib.import_module('_pywrap_tensorflow')
     21     _pywrap_tensorflow = swig_import_helper()
     22     del swig_import_helper

/Users/xjdeng/anaconda/lib/python2.7/importlib/__init__.pyc in import_module(name, package)
     35             level += 1
     36         name = _resolve_name(name[level:], package, level)
---> 37     __import__(name)
     38     return sys.modules[name]

ImportError: No module named _pywrap_tensorflow

In [2]: import pywrap_tensorflow
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-2-6e414ae7ae75> in <module>()
----> 1 import pywrap_tensorflow

ImportError: No module named pywrap_tensorflow


```

### What have you tried?
1. I've googled for the error message `No module named _pywrap_tensorflow` but haven't gotten any useful results.  What's really puzzling is that tensorflow loads in python but not [ipython.]
2. This error doesn't happen if I import tensorflow in a Jupyter notebook either.  Only iPython from the command line.

### Logs or other output that would be helpful
(If logs are large, please upload as attachment).

**Comment by caisq** [comment]
Does your LD_LIBRARY_PATH include "/usr/local/cuda/lib"? Is it configured a system-wide, like in /etc/profile?

**Comment by johann-petrak** [comment]
Same problem on Ubuntu 16.04 when installing TensorFlow tensorflow-0.9.0  with CUDA (17.5) support according to the instructions at the website. Installation for Ubuntu Linux 16.04 64 bit, Anaconda2 64 bit. 

In python, import tensorflow works:
```
$ python
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://anaconda.org
>>> import tensorflow as tf
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:102] Couldn't open CUDA library libcudnn.so. LD_LIBRARY_PATH: /home/johann/software/anaconda2/lib/:/home/johann/torch/install/lib:
I tensorflow/stream_executor/cuda/cuda_dnn.cc:2092] Unable to load cuDNN DSO
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcuda.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcurand.so locally
>>> 
``` 

But with ipython tensorflow is not known:
```
$ ipython
Python 2.7.12 |Anaconda custom (64-bit)| (default, Jul  2 2016, 17:42:40) 
Type "copyright", "credits" or "license" for more information.

IPython 4.2.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: 
In [1]: import tensorflow as tf
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-41389fad42b5> in <module>()
----> 1 import tensorflow as tf

ImportError: No module named tensorflow

In [2]: 
```

**Comment by johann-petrak** [comment]
The solution is simple: when the tensorflow environment is activated, i.e. after running `source activate tensorflow`, ipython needs to get installed (again? specifically for that environment?) using `conda install ipython`. After this, importing tensorflow in ipython works just fine.

**Comment by michaelisard** [comment]
Sorry if I am misunderstanding, but are you saying this is a documentation bug or an installation bug?

**Comment by johann-petrak** [comment]
From my understanding of the mechanics of anaconda it looks like a documentation bug: apparently, this is how one needs to do things in an environment that gets activated by "source activate tensorflow". For example, one also has to install other python packages into that environment before they can be used. So unless this is regarded common knowledge, it would maybe be a good idea to mention that one has to install ipything into the environment in order to use tensorflow from ipython.

**Comment by michaelisard** [comment]
Thanks. Would you submit a PR for the doc?

**Comment by johann-petrak** [comment]
https://github.com/tensorflow/tensorflow/pull/3514
