### ISSUE TITLE
"module 'tensorflow' has no attribute <anything>" if tensorflow_core imported first

### ISSUE THREAD

**Issue by fernandocamargoti** [tensorflow/tensorflow#33212]
**System information**
- OS Platform and Distribution: Linux Manjaro 18
- TensorFlow installed from: pip install tensorflow-gpu==2.0.0
- TensorFlow version: 2.0.0
- Python version: 3.6

**Describe the current behavior**
If I import something from **tensorflow_core** before importing **tensorflow**, the **tensorflow** doens't work properly.

**Describe the expected behavior**
Being able to import from tensorflow_core (eg: from tensorflow_core.python.keras.engine.training import Model) with no problem.

**Code to reproduce the issue**

```
from tensorflow_core.python.keras.engine.training import Model
import tensorflow as tf

print(tf.__version__)
```
AttributeError: module 'tensorflow' has no attribute '__version__'

The following works:

```
import tensorflow as tf
from tensorflow_core.python.keras.engine.training import Model

print(tf.__version__)
```

**Comment by gowthamkpr** [comment]
Was able to reproduce it. Heres my [gist](https://colab.sandbox.google.com/gist/gowthamkpr/1ce795e85e3c24a5e9c7ed90f07d3cde/untitled178.ipynb).

The issue is that module wrapping hides all symbols starts with _ from __all__ so __version__ is hided as well. Created a PR #30778 for the fix, but still the issue persists.

**Comment by mihaimaruseac** [comment]
Never import `tensorflow_core`. That is an internal implementation detail.

We don't support fixing issues that are caused by not using the API as is designed.
