### ISSUE TITLE
Unable to use the save model for prediction

### ISSUE THREAD

**Issue by kuetuofa** [tensorflow/tensorflow#33214]

**Comment by kuetuofa** [comment]
I am trying to use Transformer model with distributed training. The codes are available in this [repository](https://github.com/kuetuofa/Transformer).  I can train the model by running following command `python distributed_train.py` after training It's saving the model in the model dir as the pictures shows.
![Capture](https://user-images.githubusercontent.com/51720321/66590364-9e7dab80-eb5e-11e9-85a3-4b63ed64d336.JPG)

I am trying to load the model from saved model and send some data for prediction but I am ended up getting an error shown in the screenshot below 
![Capture1](https://user-images.githubusercontent.com/51720321/66591134-3f209b00-eb60-11e9-8224-94bafec43deb.JPG)

I am interested to know how should I send data for prediction?
Any help regarding this will be greatly appreciated

**Comment by oanush** [comment]
@kuetuofa ,
Can you share a simple and standalone code to reproduce the issue reported here? Thanks!

**Comment by kuetuofa** [comment]
Hi @oanush Thanks for responding. Unfortunately the code is not simple that's why I put it in the following [repository](https://github.com/kuetuofa/Transformer). Will you able to check it out from there? It's a public repo.

**Comment by jvishnuvardhan** [comment]
@kuetuofa This is not Build/Installation or Bug/Performance issue. Please post this kind of support questions at [Stackoverflow](https://stackoverflow.com/questions/tagged/tensorflow). There is a big community to support and learn from your questions. GitHub is mainly for addressing bugs in installation and performance. Thanks!
