### ISSUE TITLE
Wrong type in rnn function

### ISSUE THREAD

**Issue by raduk** [tensorflow/tensorflow#3322]
I think the type of `zero_output` in line 135 in [(rnn.py)](https://github.com/tensorflow/tensorflow/blob/r0.9/tensorflow/python/ops/rnn.py#L135) should be `dtype` and not `inputs[0].dtype` as it is right now. If the cell output is a float, this will trigger an exception in the select statement in `_rnn_step` function in line [(298)](https://github.com/tensorflow/tensorflow/blob/r0.9/tensorflow/python/ops/rnn.py#L298) of the type 

`TypeError: Input 'e' of 'Select' Op has type float32 that does not match type int32 of argument 't'.`

when the inputs of the cells are int. I don't have a short piece of code to reproduce this, but if needed I can produce one.

**Comment by fwalch** [comment]
I think this has been fixed on `master` (bbdda85344b819ce4db0bab5a9143fe9c4ff1c76).

**Comment by jmchen-g** [comment]
@raduk Could you try it out and close this if it is fixed?

**Comment by raduk** [comment]
Looks like it is, thanks !
