### ISSUE TITLE
python3-pip missing from container image

### ISSUE THREAD

**Issue by BobyMCbobs** [tensorflow/tensorflow#33226]
# Issue
Python 2.7 is being deprecated in 2020, Python 3.6+ is included but is lacking pip3.  
Some [Python examples](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/examples/python) don't work without having to manually install it.

## Fix
Install python3-pip as a dependency

**Comment by yongtang** [comment]
@BobyMCbobs I tried with `docker run -i -t tensorflow/tensorflow:2.0.0-py3` and pip3 is inside.

**Comment by BobyMCbobs** [comment]
> @BobyMCbobs I tried with `docker run -i -t tensorflow/tensorflow:2.0.0-py3` and pip3 is inside.

Shouldn't this image be the default one?

**Comment by angerson** [comment]
@BobyMCbobs, can you provide some command line examples to demonstrate this? We host many images, and I don't know which one you mean.

**Comment by BobyMCbobs** [comment]
> @BobyMCbobs, our current images do default to Python 2, and probably will continue to do so until Python 2.7 reaches EOL in January 2020. Until then, you'll need to use one of the `-py3` images if you wish to use Python 3.

OK, this is good to know. I'll close the issue.
