### ISSUE TITLE
TF 2.0: Can't authenticate with google storage in colab

### ISSUE THREAD

**Issue by georgealexandruvlad** [tensorflow/tensorflow#33222]
I'm trying to use the TPU in colab so I have to authenticate to my google storage account to feed the data (as I understood from past tutorials on using TPUs on colab). When I'm trying to authenticate I get the following error:

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-2-1f759c1655bd> in <module>()
      1 from google.colab import auth
----> 2 auth.authenticate_user()

/usr/local/lib/python3.6/dist-packages/google/colab/auth.py in authenticate_user(clear_output)
    154       with tf.compat.v1.Session('grpc://{}'.format(colab_tpu_addr)) as sess:
    155         with open(_get_adc_path()) as auth_info:
--> 156           tf.contrib.cloud.configure_gcs(
    157               sess, credentials=_json.load(auth_info))
    158   if _check_adc():

AttributeError: module 'tensorflow' has no attribute 'contrib'
```

The code I run is:

```
!pip install tensorflow-gpu
from google.colab import auth
auth.authenticate_user()
```
The following link contains the code to reproduce the error https://colab.research.google.com/drive/1LQ_SuPoetIUBTBhohVbFJnatkyKNb1G9

**Comment by gowthamkpr** [comment]
@georgealexandruvlad This is issue is related to google colab. You can post your issue in [googlecolab/colabtools](https://github.com/googlecolab/colabtools/issues). 

This is a know issue. You can look at this [comment](https://github.com/googlecolab/colabtools/issues/602#issuecomment-503189066) which should help you understand the situation but you're still likely to hit trouble with TPUs + TF2
