### ISSUE TITLE
java.lang.RuntimeException: java.lang.IllegalArgumentException: Internal error: Cannot create interpreter: Didn't find custom op for name 'TFLite_Detection_PostProcess' with version 1 

### ISSUE THREAD

**Issue by WestbrookZero** [tensorflow/tensorflow#33231]
I used tensorflow lite android object detection demo in my android project , but it crashs , I set ndk {
            abiFilters 'armeabi-v7a'
        } 
       in build.gradle, it still crashs
     Error Log ：
 java.lang.RuntimeException: java.lang.IllegalArgumentException: Internal error: Cannot create interpreter: Didn't find custom op for name 'TFLite_Detection_PostProcess' with version 1
    Registration failed. at com.tfdetection.tflite.TFLiteObjectDetectionAPIModel.create(TFLiteObjectDetectionAPIModel.java:125)
  crash code ：d.tfLite = new Interpreter(loadModelFile(assetManager, modelFilename));

**Comment by avaish1** [comment]
@WestbrookZero  , your error logs indicates that tflite model used here has operation which are not supported. Check for your model file if that is correctly converted to tflite.

**Comment by WestbrookZero** [comment]
@avaish1  my tflite can be used by an empty android project , but can't be used by my android project ,and official pre-training tflite is still this error in my android project .

**Comment by WestbrookZero** [comment]
I solve it in build.gradle :  implementation 'org.tensorflow:tensorflow-lite:2.0.0'
