### ISSUE TITLE
Embedding visualization in tf.keras / TensorFlow 2.0

### ISSUE THREAD

**Issue by KristianHolsheimer** [tensorflow/tensorflow#33230]
I'm trying to visualize some embeddings in Tensorboard. In pure keras this was possible, for example:
- https://keras.io/examples/tensorboard_embeddings_mnist/

There was already a regression in `tf.keras`, breaking this functionality, see [this bug](https://github.com/keras-team/keras/issues/12808).

I thought I'd try out tensorflow 2.0 and it seems that the functionality is removed altogether. I now get the message:

> WARNING:tensorflow:`embeddings_layer_names` is not supported in TensorFlow 2.0. Instead, all `Embedding` layers will be visualized.

I generally don't care about visualizing my `Embedding` layers. Instead, I'd like to visualize the output of my bottleneck layer, which is typically just a `Dense` layer.

As I'm writing this, I do realize that the way tensorboard/projector works is that is extracts the embedding `Variable` (weights) from a checkpoint. In the case of an `Embedding` layer this is very natural. The interesting case, I would argue, is the visualization of **activations**, i.e. a generic `Tensor`.

Is this supported by `tf.keras` or should I write a custom callback class to do this?

Thanks!

**Comment by rmothukuru** [comment]
@KristianHolsheimer,
Can you please refer to the Embedding Projector and let us know if this is what you are looking for? Thanks!

**Comment by sushreebarsa** [comment]
@KristianHolsheimer  It looks like you are using an older Version of Tensorflow 2.0. Many bugs have been fixed in the latest version. Can you please execute your code using Latest stable Version(2.5) and let us know if the issue still persists? Thanks!
