### ISSUE TITLE
Saving GRU with dropout to SavedModel fails

### ISSUE THREAD

**Issue by fhausmann** [tensorflow/tensorflow#33247]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Colab
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): Pip
- TensorFlow version (use command below): v2.0.0-rc2-26-g64c3d38 2.0.0
- Python version: python 3.6.8
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Describe the current behavior**
When Model containing GRU layer, dropout is set and activation='relu', the model is not savable.

Error:
Attempted to save a function b'__inference_GRU_layer_call_fn_8041' which references a symbolic Tensor Tensor("dropout/mul_1:0", shape=(None, 3), dtype=float32) that is not a simple constant. This is not supported.

**Describe the expected behavior**
Model gets saved.

**Code to reproduce the issue**
```
from tensorflow import keras
from tensorflow.keras import layers

inputs = keras.Input(shape=(784,3), name='digits')
x = layers.GRU(64, activation='relu', name='GRU',dropout=0.1)(inputs)
x = layers.Dense(64, activation='relu', name='dense')(x)
outputs = layers.Dense(10, activation='softmax', name='predictions')(x)

model = keras.Model(inputs=inputs, outputs=outputs, name='3_layer')
model.summary()
model.save('model',save_format='tf')
```
Based on: https://www.tensorflow.org/guide/keras/save_and_serialize

**Comment by oanush** [comment]
Issue replicating for TF-2.0, kindly find the [gist](https://colab.sandbox.google.com/gist/oanush/4a4201abcbe95c5eb2e19bc5d3f5bde1/33247.ipynb) of colab.Thanks!

**Comment by rmothukuru** [comment]
@fhausmann,
The error disappears if `dropout=0` or if `layers.Dense` instead of `layers.GRU`. The link, https://www.tensorflow.org/guide/keras/save_and_serialize, provided by you doesn't demonstrate on how to Save the Model with `layers.GRU`.

Can you please refer [Image_Captioning_Tutorial](https://www.tensorflow.org/tutorials/text/image_captioning), [Text_Generation_Tutorial](https://www.tensorflow.org/tutorials/text/text_generation) and [NMT_With_Attention_Tutorial](https://www.tensorflow.org/tutorials/text/nmt_with_attention) where, usage of `layers.GRU` is demonstrated and let us know if it helps. Thanks!

**Comment by fhausmann** [comment]
@rmothukuru Thanks for your answer.
The error also disappers if 'activation' is not set and yes the link is maybe a bit missleading, since the example there is for Dense layer only. However, I thought this was a good minimal working example also with GRU.
I had a look into your links, but unfortunately non of them demonstrate how to save a model with GRU layer in the SavedModel format.

I tried for the Text_Generation_Tutorial (added `model.save('model',save_format="tf")` after training, but it also failed here (with another error: AssertionError: Tried to export a function which references untracked object Tensor("StatefulPartitionedCall/args_2:0", shape=(), dtype=resource).TensorFlow objects (e.g. tf.Variable) captured by functions must be tracked by assigning them to an attribute of a tracked object or assigned to an attribute of the main object directly.)

Seems that GRU models does not allow saving in SavedModel format at the moment?

**Comment by fhausmann** [comment]
Maybe related to #33355 ?

**Comment by rmothukuru** [comment]
@fhausmann,
Model is Saved Successfully if you replace `model.save('model',save_format="tf")` with `model.save('model.h5')` . Here is the [Gist](https://colab.sandbox.google.com/gist/rmothukuru/72984b3a326970c85edb8f03312cb199/33247.ipynb).

**Comment by fhausmann** [comment]
Yes, this probably solves the issue for most people, but its a different format , binary HDF5 vs. SavedModel.

**Comment by rmothukuru** [comment]
@fhausmann,
In your case, you can either use `keras.models.save_model(model=model, filepath='model')` or 
`model.save('model')`. Please let me know if it works. Thanks!

**Comment by rmothukuru** [comment]
There is an issue, probably with the argument, `save_format='tf'` because, the code, `model.save('model', save_format='tf')` is resulting in the Error mentioned by you.

**Comment by fhausmann** [comment]
@rmothukuru 
I tried both on your gist and both give me the error. Only the 'model.h5' works in my hands

**Comment by wangdong1992** [comment]
I also encountered the same problem. Have you solved it?

**Comment by fhausmann** [comment]
`tf.keras.experimental.export_saved_model(model, 'modelfolder')` and `tf.keras.experimental.load_from_saved_model('modelfolder')`
seems to be a workaround even they are deprecated.

**Comment by rmothukuru** [comment]
To add more information, Model is Saved without any Error if we build the Model using Dense or using LSTM and Dense. But if we build the Model with GRU as one of the Layers, it is resulting in either the Error,
 ```Error:
Attempted to save a function b'__inference_GRU_layer_call_fn_8041' which references a symbolic Tensor Tensor("dropout/mul_1:0", shape=(None, 3), dtype=float32) that is not a simple constant. This is not supported.``` or the Error, 

`AssertionError: Tried to export a function which references untracked object Tensor("StatefulPartitionedCall/args_2:0", shape=(), dtype=resource).TensorFlow objects (e.g. tf.Variable) captured by functions must be tracked by assigning them to an attribute of a tracked object or assigned to an attribute of the main object directly.`.

Here is [Gist_of_Error1](https://colab.sandbox.google.com/gist/rmothukuru/00386fc1a493b344282b1b8aa97e20e7/33247.ipynb) and [Gist_Of_Error2](https://colab.sandbox.google.com/gist/rmothukuru/78f245f68f3729eb1c8f0da1e0df93a1/33355.ipynb).

**Comment by tanzhenyu** [comment]
See the above link. I don't think LSTM works as well

**Comment by karlsonthisisbud** [comment]
tf.keras.experimental.export_saved_model still works

**Comment by jvishnuvardhan** [comment]
@fhausmann This was resolved in `tf-nightly`. Please check the [gist here](https://colab.sandbox.google.com/gist/jvishnuvardhan/28eb34025ba304b45f2a8bb74c2cd2a4/untitled774.ipynb). 

As this was resolved, I am closing this issue. Please feel free to reopen if the issue persists later. Thanks!

**Comment by phemmer** [comment]
Does anyone have the commit ID which resolved this issue? I don't want to run a nightly release, and need to backport the fix into a stable version.

**Comment by jvishnuvardhan** [comment]
@phemmer New stable version (`TF2.2`) will be release soon. Please check the recent [announcements here](https://groups.google.com/a/tensorflow.org/forum/#!forum/build). Thanks!

**Comment by phemmer** [comment]
Can we not just have the commit ID? Yes 2.2 may be close, but it's still a few weeks off I'd imagine. And in addition, I'm using [IBM's Large Model Support patch](https://github.com/IBM/tensorflow-large-model-support), which will likely take an additional several weeks to be updated to 2.2.
