### ISSUE TITLE
build_pip_package failed

### ISSUE THREAD

**Issue by Phhere** [tensorflow/tensorflow#3325]
GitHub issues are for bugs / installation problems / feature requests.  
For general support from the community, see [StackOverflow](https://stackoverflow.com/questions/tagged/tensorflow).
To make bugs and feature requests more easy to find and organize, we close issues that are deemed
out of scope for GitHub Issues and point people to StackOverflow.

For bugs or installation issues, please provide the following information.
The more information you provide, the more easily we will be able to offer
help and advice.

### Environment info
Operating System:
Redhat 6.7
module environment
gcc 6.1.0

`printenv
MKLROOT=/software/intel/xe2015/composer_xe_2015.1.133/mkl
FLIBDIR=/software/intel/xe2015/composer_xe_2015.1.133/compiler/lib/intel64
MANPATH=/software/python/3.4.5/login/man:/software/intel/xe2015/composer_xe_2015.1.133/man/en_US:/usr/share/man:/usr/man:/usr/local/share/man:/usr/X11R6/man
MKLLIBDIR=/software/intel/xe2015/composer_xe_2015.1.133/mkl/lib/intel64
FDIR=/software/intel/xe2015/composer_xe_2015.1.133
IPPROOT=/software/intel/xe2015/composer_xe_2015.1.133/ipp
INTEL_LICENSE_FILE=/software/intel/licenses/server.lic
TERM=xterm
SHELL=/bin/bash
MLIBDIR=/software/intel/xe2015/composer_xe_2015.1.133/mkl/lib/intel64
HISTSIZE=1000
SSH_CLIENT=134.99.4.11 52640 22
LIBRARY_PATH=/software/intel/xe2015/composer_xe_2015.1.133/compiler/lib/intel64:/software/intel/xe2015/composer_xe_2015.1.133/ipp/lib/intel64:/software/intel/xe2015/composer_xe_2015.1.133/mkl/lib/intel64:/software/intel/xe2015/composer_xe_2015.1.133/tbb/lib/intel64
FPATH=
OLDPWD=/root
SSH_TTY=/dev/pts/3
USER=root
LD_LIBRARY_PATH=/software/gcc/6.1.0/login/lib:/software/gcc/6.1.0/login/lib64:/software/python/install/Python-3.4.5/Include/:/software/python/3.4.5/login/lib:/software/intel/xe2015/composer_xe_2015.1.133/compiler/lib/intel64:/software/intel/xe2015/composer_xe_2015.1.133/ipp/lib/intel64:/software/intel/xe2015/composer_xe_2015.1.133/mkl/lib/intel64:/software/intel/xe2015/composer_xe_2015.1.133/tbb/lib/intel64:/lib64:/usr/lib64:/usr/local/lib64:/usr/X11R6/lib64
CPATH=/software/intel/xe2015/composer_xe_2015.1.133/mkl/include:/software/intel/xe2015/composer_xe_2015.1.133/tbb/include
LIBPATH=/software/python/install/Python-3.4.5/Lib/:/software/python/3.4.5/login/lib
CDIR=/software/intel/xe2015/composer_xe_2015.1.133
CLIBDIR=/software/intel/xe2015/composer_xe_2015.1.133/compiler/lib/intel64
MAIL=/var/spool/mail/root
PATH=/software/gcc/6.1.0/login/bin:/software/python/3.4.5/login/bin:/software/intel/xe2015/composer_xe_2015.1.133/bin/intel64:/software/intel/xe2015/composer_xe_2015.1.133/bin/intel64_mic:/software/intel/xe2015/composer_xe_2015.1.133/debugger/gui/intel64:/usr/pbs/bin:.:/bin:/usr/bin:/usr/local/bin:/usr/X11R6/bin
TBBROOT=/software/intel/xe2015/composer_xe_2015.1.133/tbb
F90=gfortran
PWD=/software/tensorflow/install/tensorflow
_LMFILES_=/software/modules/tools/hpc_basis:/software/modules/compiler/intel/xe2015:/software/modules/tools/Python/3.4.5:/software/modules/compiler/gcc/6.1.0
F95=gfortran
LANG=en_US.UTF-8
MODULEPATH=/software/modules/compiler:/software/modules/software:/software/modules/tools
LOADEDMODULES=hpc_basis:intel/xe2015:Python/3.4.5:gcc/6.1.0
PYTHONHOME=/software/python/3.4.5/login
F77=gfortran
CXX=g++
HISTCONTROL=ignoredups
SHLVL=1
HOME=/root
FC=gfortran
DYLD_LIBRARY_PATH=/software/gcc/6.1.0/login/lib:/software/gcc/6.1.0/login/lib64:/software/intel/xe2015/composer_xe_2015.1.133/compiler/lib/intel64:/software/intel/xe2015/composer_xe_2015.1.133/ipp/lib/intel64:/software/intel/xe2015/composer_xe_2015.1.133/mkl/lib/intel64:/software/intel/xe2015/composer_xe_2015.1.133/tbb/lib/intel64
LOGNAME=root
CVS_RSH=ssh
MODULESHOME=/usr/share/Modules
LESSOPEN=||/usr/bin/lesspipe.sh %s
ARCH=login
FRTLIB=-lifcore
CC=gcc
INCLUDE=/software/intel/xe2015/composer_xe_2015.1.133/mkl/include:/software/intel/xe2015/composer_xe_2015.1.133/tbb/include:/usr/X11R6/include/X11:/usr/include:/usr/local/include
G_BROKEN_FILENAMES=1
BASH_FUNC_module()=() {  eval `/usr/bin/modulecmd bash $*`
}
_=/usr/bin/printenv
`

Installed version of CUDA and cuDNN: 
(please attach the output of `ls -l /path/to/cuda/lib/libcud*`):
ls -l /software/CUDA/7.5.18/lib/libcud*
-rw-r--r-- 1 root users 189170 Sep 10  2015 /software/CUDA/7.5.18/lib/libcudadevrt.a
lrwxrwxrwx 1 root users     16 Sep 10  2015 /software/CUDA/7.5.18/lib/libcudart.so -> libcudart.so.7.5
lrwxrwxrwx 1 root users     19 Sep 10  2015 /software/CUDA/7.5.18/lib/libcudart.so.7.5 -> libcudart.so.7.5.18
-rwxr-xr-x 1 root users 311596 Sep 10  2015 /software/CUDA/7.5.18/lib/libcudart.so.7.5.18
-rw-r--r-- 1 root users 558020 Sep 10  2015 /software/CUDA/7.5.18/lib/libcudart_static.a

If installed from sources, provide the commit hash:
d2c913aa9b7cb63e466392f76d46ac5fbc1e9825

### Steps to reproduce
1. install gcc in different path and set PATH, LD_LIBRARY_PATH, INCLDUE_PATH
2. git clone https://github.com/tensorflow/tensorflow.git
3. ./configure
4. bazel build -c opt --config=cuda //tensorflow/tools/pip_package:build_pip_package --verbose_failures

### Logs or other output that would be helpful
`[root@hpc-login1 tensorflow]# bazel build -c opt --config=cuda //tensorflow/tools/pip_package:build_pip_package --verbose_failures
WARNING: /software/tensorflow/install/tensorflow/util/python/BUILD:11:16: in includes attribute of cc_library rule //util/python:python_headers: 'python_include' resolves to 'util/python/python_include' not in 'third_party'. This will be an error in the future.
INFO: Found 1 target...
ERROR: /root/.cache/bazel/_bazel_root/60e5a3f81176660f3aa05e1fb0a50126/external/zlib_archive/BUILD:7:1: undeclared inclusion(s) in rule '@zlib_archive//:zlib':
this rule is missing dependency declarations for the following files included by 'external/zlib_archive/zlib-1.2.8/uncompr.c':
  '/software/gcc/6.1.0/login/lib/gcc/x86_64-pc-linux-gnu/6.1.0/include-fixed/limits.h'
  '/software/gcc/6.1.0/login/lib/gcc/x86_64-pc-linux-gnu/6.1.0/include-fixed/syslimits.h'
  '/software/gcc/6.1.0/login/lib/gcc/x86_64-pc-linux-gnu/6.1.0/include/stddef.h'
  '/software/gcc/6.1.0/login/lib/gcc/x86_64-pc-linux-gnu/6.1.0/include/stdarg.h'.
Target //tensorflow/tools/pip_package:build_pip_package failed to build
INFO: Elapsed time: 3.201s, Critical Path: 1.01s`

I also tried to use the intel compiler but bazel brakes the environment

**Comment by jmchen-g** [comment]
Redhat is not officially supported. But you can move this to Stackoverflow though and people might be able to help there.
