### ISSUE TITLE
How to confiture TF2.0 compilation with Intel MPI ?

### ISSUE THREAD

**Issue by VitaMusic** [tensorflow/tensorflow#33251]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): RHEL 7.2
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: none
- TensorFlow installed from (source or binary): source (configuration process pbm)
- TensorFlow version: 2.0
- Python version: 3.6.9
- Installed using virtualenv? pip? conda?: not concerned
- Bazel version (if compiling from source): 0.29.1
- GCC/Compiler version (if compiling from source): 4.8.5
- CUDA/cuDNN version: 10.0 / 7.6.4 
- GPU model and memory: Tesla K80 / 256Gb

**Describe the problem**
problem in ./configure when asking for MPI Toolkit path
I found description howto for openmpi (https://github.com/robsanpam/TensorFlow_From_Sources), but I want to use intel mpi.
what I need to indicate in path for intel mpi (intel cluster edition 2019) ?

**Provide the exact sequence of commands / steps that you executed before running into the problem**
I input : /opt/intel/compilers_and_libraries/linux/mpi/intel64

**Any other info / logs**
Invalid path to the MPI Toolkit. /opt/intel/compilers_and_libraries/linux/mpi/intel64 or True or False or False cannot be found

**Comment by oanush** [comment]
@VitaMusic ,
Can you please provide `./configure ` output? also provide more information on sequence of commands / steps that was followed before facing the issue. Thanks!

**Comment by VitaMusic** [comment]
please find here :

$ ./configure
WARNING: --batch mode is deprecated. Please instead explicitly shut down
your Bazel server using the command "bazel shutdown".
You have bazel 0.29.1 installed.
Please specify the location of python. [Default is /usr/bin/python]:


Found possible Python library paths:
  /opt/anaconda3/lib/python3.6/site-packages
Please input the desired Python library path to use.  Default is
[/opt/anaconda3/lib/python3.6/site-packages]

Do you wish to build TensorFlow with XLA JIT support? [Y/n]:
XLA JIT support will be enabled for TensorFlow.

Do you wish to build TensorFlow with OpenCL SYCL support? [y/N]:
No OpenCL SYCL support will be enabled for TensorFlow.

Do you wish to build TensorFlow with ROCm support? [y/N]:
No ROCm support will be enabled for TensorFlow.

Do you wish to build TensorFlow with CUDA support? [y/N]: y
CUDA support will be enabled for TensorFlow.

Do you wish to build TensorFlow with TensorRT support? [y/N]: y
TensorRT support will be enabled for TensorFlow.

Could not find any NvInferVersion.h matching version '' in any subdirectory:
        ''
        'include'
        'include/cuda'
        'include/*-linux-gnu'
        'extras/CUPTI/include'
        'include/cuda/CUPTI'
of:
        '/lib'
        '/lib64'
        '/usr'
        '/usr/lib64/R/lib'
        '/usr/lib64/dyninst'
        '/usr/lib64/iscsi'
        '/usr/lib64/mysql'
        '/usr/lib64/qt-3.3/lib'
        '/usr/local/cuda'
Asking for detailed CUDA configuration...

Please specify the CUDA SDK version you want to use. [Leave empty to
default to CUDA 10]: 10.0


Please specify the cuDNN version you want to use. [Leave empty to default
to cuDNN 7]: 7.6.4


Please specify the TensorRT version you want to use. [Leave empty to
 default to TensorRT 5]: 6.0.1


Please specify the locally installed NCCL version you want to use. [Leave
empty to use http://github.com/nvidia/nccl]:


Please specify the comma-separated list of base paths to look for CUDA
libraries and headers. [Leave empty to use the default]:
/usr/local/cuda,/usr/local/cuda/bin,/usr/local/cuda/lib64,/usr/local/cuda/include,/opt/TensorRT-6.0.1.5/bin,/opt/TensorRT-6.0.1.5/lib,/opt/TensorRT-6.0.1.5/include


Found CUDA 10.0 in:
    /usr/local/cuda/lib64
    /usr/local/cuda/include
Found cuDNN 7 in:
    /usr/local/cuda/lib64
    /usr/local/cuda/include
Found TensorRT 6 in:
    /opt/TensorRT-6.0.1.5/lib
    /opt/TensorRT-6.0.1.5/include


Please specify a list of comma-separated CUDA compute capabilities you want
to build with.
You can find the compute capability of your device at:
https://developer.nvidia.com/cuda-gpus.
Please note that each additional compute capability significantly increases
your build time and binary size, and that TensorFlow only supports compute
capabilities >= 3.5 [Default is: 3.7,3.7]: 3.7,6.0,7.0,7.5


Do you want to use clang as CUDA compiler? [y/N]:
nvcc will be used as CUDA compiler.

Please specify which gcc should be used by nvcc as the host compiler.
[Default is /usr/bin/gcc]:


Do you wish to build TensorFlow with MPI support? [y/N]: y
MPI support will be enabled for TensorFlow.

Please specify the MPI toolkit folder. [Default is
/opt/intel/compilers_and_libraries_2018.3.222/linux/mpi/intel64]:


Invalid path to the MPI Toolkit.
/opt/intel/compilers_and_libraries_2018.3.222/linux/mpi/intel64/include or
True or False or False cannot be found
Please specify the MPI toolkit folder. [Default is
/opt/intel/compilers_and_libraries_2018.3.222/linux/mpi/intel64]:


----------------------------------

sourcing of mpi vars does not help
source
/home/apps/intel2018u3/compilers_and_libraries/linux/mpi/intel64/bin/mpivars.sh
release

**Comment by angerson** [comment]
Intel MPI support has been moved to https://github.com/tensorflow/networking. Please follow the instructions there.
