### ISSUE TITLE
Can't save a Model with a TimeDistributed layer wrapping another Model

### ISSUE THREAD

**Issue by artemmavrin** [tensorflow/tensorflow#33261]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution: Linux Ubuntu 18.04.2
- TensorFlow installed from (source or binary): binary
- TensorFlow version: 2.0.0
- Python version: 3.7.3
- CUDA/cuDNN version: CUDA 10.1 cuDNN 7.5.1
- GPU model and memory: TITAN X

**Describe the current behavior**

I get a `ValueError` when trying to save a `tf.keras.Model` with a `tf.keras.layers.TimeDistributed` layer wrapping another `tf.keras.Model` that has convolutional layers. I am using `tf.keras.Model.save` with the default `save_format` (SavedModel). See below for examples.

There is no error when saving with `save_format='h5'`.

**Describe the expected behavior**

Successfully saving a SavedModel with the `tf.keras.layers.TimeDistributed` layer.

**Code to reproduce the issue**

1.  Wrapping a 1-layer convolutional NN with `tf.keras.layers.TimeDistributed`:

    ```python
    import tensorflow as tf

    input_shape = (100, 100, 3)

    embedding_model = tf.keras.Sequential([
        tf.keras.layers.Input(input_shape),
        tf.keras.layers.Conv2D(filters=32, kernel_size=3, strides=1),
    ])

    input_sequence = tf.keras.layers.Input((None,) + input_shape)
    sequence_embedding = tf.keras.layers.TimeDistributed(embedding_model)
    outputs = sequence_embedding(input_sequence)

    model = tf.keras.Model(inputs=input_sequence, outputs=outputs)

    model.save('model1')
    ```

    Error:

    ```
    ValueError: Input 0 of layer conv2d is incompatible with the layer: expected ndim=4, found ndim=5. Full shape received: [None, None, 100, 100, 3]
    ```

2.  Wrapping a pre-trained `tf.keras.applications` model (closer to my actual use case):

    ```python
    import tensorflow as tf

    input_shape = (224, 224, 3)

    mobilenet = tf.keras.applications.MobileNet(
        input_shape=input_shape,
        include_top=False,
        weights='imagenet',
        pooling='avg',
    )

    input_sequence = tf.keras.layers.Input((None,) + input_shape)
    sequence_embedding = tf.keras.layers.TimeDistributed(mobilenet)
    outputs = sequence_embedding(input_sequence)

    model = tf.keras.Model(inputs=input_sequence, outputs=outputs)

    model.save('model2')
    ```

    Error:

    ```
    ValueError: Input 0 of layer conv1_pad is incompatible with the layer: expected ndim=4, found ndim=5. Full shape received: [None, None, 224, 224, 3]
    ```

3.  Saving as an HDF5 file instead:

    ```python
    import tensorflow as tf

    input_shape = (224, 224, 3)

    mobilenet = tf.keras.applications.MobileNet(
        input_shape=input_shape,
        include_top=False,
        weights='imagenet',
        pooling='avg',
    )

    input_sequence = tf.keras.layers.Input((None,) + input_shape)
    sequence_embedding = tf.keras.layers.TimeDistributed(mobilenet)
    outputs = sequence_embedding(input_sequence)

    model = tf.keras.Model(inputs=input_sequence, outputs=outputs)

    model.save('model3.h5', save_format='h5')
    ```

    This works without errors.

4.  Saving to the SavedModel format works with just dense layers:

    ```python
    import tensorflow as tf

    input_shape = (100,)

    embedding_model = tf.keras.Sequential([
        tf.keras.layers.Input(input_shape),
        tf.keras.layers.Dense(units=10)
    ])

    input_sequence = tf.keras.layers.Input((None,) + input_shape)
    sequence_embedding = tf.keras.layers.TimeDistributed(embedding_model)
    outputs = sequence_embedding(input_sequence)

    model = tf.keras.Model(inputs=input_sequence, outputs=outputs)

    model.save('model4')
    ```

    This works without errors.

**Comment by ravikyram** [comment]
I have tried on colab with TF version 2.0  and was able to reproduce the issue.Please, find the gist [here](https://colab.sandbox.google.com/gist/ravikyram/00b7541a4eb2b6492c984d4201acce7f/untitled265.ipynb).Thanks!

**Comment by artemmavrin** [comment]
Is there any update? I noticed in #33094 that there was a fix for saving `TimeDistributed` layers in the nightly release. I tried with `tf-nightly==2.1.0-dev20191113`, but I'm getting the same error.

**Comment by boluoyu** [comment]
Any update?

**Comment by artemmavrin** [comment]
Same errors with `tensorflow==2.1.0-rc0`.

---

By the way, there seems to be no problem saving a `TimeDistributed` layer wrapping a convolutional layer instead of a `Model` which has a convolutional layer in it.

For example, this works:

```python
import tensorflow as tf

time_distributed_layer = tf.keras.layers.TimeDistributed(
    layer=tf.keras.layers.Conv2D(filters=16, kernel_size=3),
    input_shape=(None, 100, 100, 3),
)
model = tf.keras.Sequential([time_distributed_layer])
model.save('model')  # Works

# Check correct restoration
restored_model = tf.keras.models.load_model('model')
for weight, restored_weight in zip(model.weights, restored_model.weights):
    assert weight.name == restored_weight.name
    tf.debugging.assert_equal(weight, restored_weight)
```

Whereas this doesn't:

```python
import tensorflow as tf

input_shape = (224, 224, 3)
time_distributed_layer = tf.keras.layers.TimeDistributed(
    layer=tf.keras.applications.MobileNet(
        input_shape=(224, 224, 3),
        include_top=False,
        weights='imagenet',
        pooling='avg',),
    input_shape=(None, 224, 224, 3),
)
model = tf.keras.Sequential([time_distributed_layer])
model.save('model')  # Same error as before
```

**Comment by boluoyu** [comment]
I also encountered this bug , how can I solve it

**Comment by henrypinkard** [comment]
+1, Also running into this

**Comment by henrypinkard** [comment]
@k-w-w this is a pretty major limitation at the moment. Any idea on what needs to be changed to fix it?

**Comment by k-w-w** [comment]
There appears to be a problem with saving layer masks using SavedModel. looking into this

**Comment by boluoyu** [comment]
@k-w-w any update on this issue?

**Comment by Peter-Devine** [comment]
Bump

**Comment by artemmavrin** [comment]
Appears to be fixed by 9f2aa61811b29e700b8325bb57b1f4b0093c1d4d

**Comment by marziehoghbaie** [comment]
Hi there, 
I am using time distributed layer to apply another model on each frame and processing the final features by conv 3D. the model is trained properly. but when I want to load the model and use it for test, I face different issues:
- first, the model cant be loaded because of the nested model
- second, the model acc on the same val dataset is not reproducible

**Comment by jvishnuvardhan** [comment]
@marziehoghbaie Please create a new issue with a simple standalone code to reproduce the error. Thanks!
