### ISSUE TITLE
Difference between Tensor and EagerTensor?

### ISSUE THREAD

**Issue by OverLordGoldDragon** [tensorflow/tensorflow#33264]
[Relevant issue](https://github.com/tensorflow/tensorflow/issues/33227) w/ full code; excerpt:

```python
var_delta = m_t / (K.sqrt(v_t) + epsilon_t)
var_update = state_ops.assign_sub(var, lr_t * var_delta, use_locking=self._use_locking)
```
Above fails to update `var`, but using `math_ops.sqrt` fixes it. To differentiate, below are some `print` statements & their outputs. Code also included demonstrating introspection limitation.

It appears that `K.sqrt` yields a Keras `Tensor`, whereas `math_ops.sqrt` yields a `tf.Tensor`, with former not showing its value even though eager is on. However, calling `K.eval` on `K.sqrt` shows the same value, so it isn't 'lost' or different. 

All considered: why does `state_ops.assign_sub` work with an `EagerTensor` but fail with a `Tensor`? How are they different? -- (TF2, Keras 2.3.0)

<hr>

```python
X1 = math_ops.sqrt(v_t)
X2 = K.sqrt(v_t)
Y1 = m_t / (math_ops.sqrt(v_t) + epsilon_t)
Y2 = m_t / (K.sqrt(v_t) + epsilon_t)

print(X1);       print(X2);       print()
print(Y1);       print(Y2);       print()
print(type(X1)); print(type(X2)); print()
print(type(Y1)); print(type(Y2)); print()
print("type(ref) =", type(var))
```
```python
tf.Tensor(
[[0.0002048  0.00189643]
 [0.00204984 0.00426161]
 [0.0013686  0.0048186 ]
 [0.00296201 0.00318883]], shape=(4, 2), dtype=float32)
Tensor("Sqrt:0", shape=(4, 2), dtype=float32, device=/job:localhost/
replica:0/task:0/device:CPU:0)

tf.Tensor(
[[ 3.1607556 -3.1621318]
 [-3.162145  -3.1622243]
 [ 3.1620677  3.162233 ]
 [-3.1621926 -3.1621997]], shape=(4, 2), dtype=float32)
Tensor("truediv:0", shape=(4, 2), dtype=float32, device=/job:localhost/
replica:0/task:0/device:CPU:0)

<class 'tensorflow.python.framework.ops.EagerTensor'>
<class 'tensorflow.python.framework.ops.Tensor'>

<class 'tensorflow.python.framework.ops.EagerTensor'>
<class 'tensorflow.python.framework.ops.Tensor'>

type(ref) = <class 'tensorflow.python.ops.resource_variable_ops.ResourceVariable'>
```

<hr>

**UPDATE**: The _type_ information may be more relevant; (`tf.`) `Tensor` vs. (Keras) `EagerTensor`. However, one lacks reasonable introspection:

```python
from tensorflow.python.framework.ops import Tensor, EagerTensor
print(Tensor.__doc__) # OK
print(EagerTensor.__doc__) # returns None

from inspect import getsource
print(getsource(EagerTensor)) # OSError: could not find class definition
```
Looking into the parent module, apparently I'll need to look into the C API to find out:

```python
EagerTensor = c_api.TFE_Py_InitEagerTensor(_EagerTensorBase)
```

**Comment by oanush** [comment]
@OverLordGoldDragon ,
Can you please provide complete code used to reproduce the issue reported here ? When tried executing the issue i got  `NameError: name 'math_ops' is not defined`. Thanks!

**Comment by OverLordGoldDragon** [comment]
@oanush Full [gist](https://gist.github.com/OverLordGoldDragon/aad492db1ff6f20a7983e600611799f7) here and referenced issue [here](https://github.com/tensorflow/tensorflow/issues/33227)

**Comment by laplace674** [comment]
I met this problem today. As I see, EagerTensor will automatically change to suitable type when been used and can be easy to transfer to numpy array with . numpy(). But Tensor will change all result to Tensor type when been called, and I haven't found a way to transfer Tensor type to any other type yet, I'm using TF2.2 and I cannot .eval the Tensor type
