### ISSUE TITLE
Build of Tensorflow 2.0 from source fails on Windows “Could not find bazel-bin”

### ISSUE THREAD

**Issue by maurera** [tensorflow/tensorflow#33265]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- TensorFlow installed from (source or binary): source
- TensorFlow version: 2.0
- Python version: 3.7.4
- Bazel version (if compiling from source): 0.26.1
- GCC/Compiler version (if compiling from source): Visual Studio 2017
- CUDA/cuDNN version: None (CPU-only)
- GPU model and memory: None (CPU-only)

**Describe the problem**
_(Also posted on Stackoverflow [here](https://stackoverflow.com/questions/58344865/build-of-tensorflow-2-0-from-source-fails-on-windows-could-not-find-bazel-bin) as I'm not sure the correct place to post)_

I'm following the guide [Build from source on Windows](https://www.tensorflow.org/install/source_windows#build_the_package) in order to get AVX2 support of Tensorflow 2.0. I successfully ran the bazel build command, but haven't been able to run build_pip_package successfully.

**Provide the exact sequence of commands / steps that you executed before running into the problem**

I followed the instructions in the Build From Source guide for the most part. I cloned the r2.0 branch of tensorflow from git and put it in c:\tmp\tensorflow. I installed the python and the tensorflow package dependencies. I installed bazel, msys2, and Visual Studio 2017 (with build tools). I configured the system build (cpu-only with AVX2 support). I then successfully ran:

```
cd c:\tmp\tensorflow
set BAZEL_VS=C:\Program Files (x86)\Microsoft Visual Studio\2017\Community
set BAZEL_VC=C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC
bazel build --config=opt //tensorflow/tools/pip_package:build_pip_package --define=no_tensorflow_py_deps=true
```

The next step in the instructions "Build the package" says to run
```
bazel-bin\tensorflow\tools\pip_package\build_pip_package C:/tmp/tensorflow_pkg
```

However, the folder C:\tmp\tensorflow\bazel-bin is empty. When I look at the log (shown below), I can see that there's a file build_pip_package.exe at C:/users/john.doe/_bazel_john.doe/3ttaaxce/execroot/org_tensorflow/bazel-out/x64_windows-opt/bin/tensorflow/tools/pip_package/build_pip_package.exe. I tried running the following:
```
C:/users/john.doe/_bazel_john.doe/3ttaaxce/execroot/org_tensorflow/bazel-out/x64_windows-opt/bin/tensorflow/tools/pip_package/build_pip_package C:/tmp/tensorflow_pkg
```
But this results in the error:
>Fri Oct 11 08:30:40 PDT 2019 : === Preparing sources in dir: /tmp/tmp.B207TraE5w
>
>Could not find bazel-bin. Did you run from the root of the build tree?

Should there be a bazel-bin folder with the implied substructure somewhere (bazel-bin\tensorflow\tools\pip_package\build_pip_package)?

**Any other info / logs**

Pasting the last few lines of build output:
```
INFO: From Linking tensorflow/lite/experimental/microfrontend/python/ops/_audio_microfrontend_op.so:
   Creating library bazel-out/x64_windows-opt/bin/tensorflow/lite/experimental/microfrontend/python/ops/python/ops/_audio_microfrontend_op.so.if.lib and object bazel-out/x64_windows-opt/bin/tensorflow/lite/experimental/microfrontend/python/ops/python/ops/_audio_microfrontend_op.so.if.exp
INFO: From Linking tensorflow/compiler/tf2xla/ops/_xla_ops.so:
   Creating library bazel-out/x64_windows-opt/bin/tensorflow/compiler/tf2xla/ops/_xla_ops.so.if.lib and object bazel-out/x64_windows-opt/bin/tensorflow/compiler/tf2xla/ops/_xla_ops.so.if.exp
Target //tensorflow/tools/pip_package:build_pip_package up-to-date:
  C:/users/john.doe/_bazel_john.doe/3ttaaxce/execroot/org_tensorflow/bazel-out/x64_windows-opt/bin/tensorflow/tools/pip_package/build_pip_package
  C:/users/john.doe/_bazel_john.doe/3ttaaxce/execroot/org_tensorflow/bazel-out/x64_windows-opt/bin/tensorflow/tools/pip_package/build_pip_package.exe
INFO: Elapsed time: 32810.307s, Critical Path: 25586.71s
INFO: 8885 processes: 8885 local.
INFO: Build completed successfully, 11312 total actions
```

**Comment by mihaimaruseac** [comment]
It seems there is no symlink for `bazel-bin/` being created.

Can you try manually creating it and copying all files from `C:/users/john.doe/_bazel_john.doe/3ttaaxce/execroot/org_tensorflow/bazel-out/x64_windows-opt/bin/tensorflow/tools/pip_package/build_pip_package.exe` into `C:\tmp\tensorflow\bazel-bin`?

If that doesn't work, can you building on a different directory, not `C:\tmp`? Maybe `tmp` is somehow mismanaged?

**Comment by maurera** [comment]
> It seems there is no symlink for `bazel-bin/` being created.
> 
> Can you try manually creating it and copying all files from `C:/users/john.doe/_bazel_john.doe/3ttaaxce/execroot/org_tensorflow/bazel-out/x64_windows-opt/bin/tensorflow/tools/pip_package/build_pip_package.exe` into `C:\tmp\tensorflow\bazel-bin`?
> 
> If that doesn't work, can you building on a different directory, not `C:\tmp`? Maybe `tmp` is somehow mismanaged?

Thanks for the response. I tried a new build on C:\tmp2 and it built successfully.
