### ISSUE TITLE
Installation of tensorflow 2.0 cpu on windows 10 not working

### ISSUE THREAD

**Issue by tessy1234** [tensorflow/tensorflow#33266]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): no
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10 64 bit
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: n/a
- TensorFlow installed from (source or binary): pip install tensorflow
- TensorFlow version (use command below): 2.0.0
- Python version: 3.7.4
- Bazel version (if compiling from source): n/a
- GCC/Compiler version (if compiling from source): n/a
- CUDA/cuDNN version: n/a
- GPU model and memory: n/a

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
Installation of tensorflow 2.0 cpu on windows 10 not working. I'm unable to import tensorflow.
**Describe the expected behavior**
Run the command "python -c "import tensorflow as tf" within conda CLI without error.
**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.
1) 
#from conda CLI base create new environment
conda create --name tensorflow2_test
2)
#activate environment
conda activate tensorflow2_test
3)
#install pip
conda install pip
4)
#install environment tensorflow 2.0
pip install tensorflow
5)
#verify install: 
python -c "import tensorflow as tf"

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

error trace:
------------
```
(tensorflow2_test) C:\~\install environment\production>python -c "import tensorflow as tf"
Traceback (most recent call last):
  File "C:\Anaconda3\envs\tensorflow2_test\lib\site-packages\tensorflow_core\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Anaconda3\envs\tensorflow2_test\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Anaconda3\envs\tensorflow2_test\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Anaconda3\envs\tensorflow2_test\lib\imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Anaconda3\envs\tensorflow2_test\lib\imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: A dynamic link library (DLL) initialization routine failed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Anaconda3\envs\tensorflow2_test\lib\site-packages\tensorflow\__init__.py", line 98, in <module>
    from tensorflow_core import *
  File "C:\Anaconda3\envs\tensorflow2_test\lib\site-packages\tensorflow_core\__init__.py", line 40, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "C:\Anaconda3\envs\tensorflow2_test\lib\site-packages\tensorflow\__init__.py", line 50, in __getattr__
    module = self._load()
  File "C:\Anaconda3\envs\tensorflow2_test\lib\site-packages\tensorflow\__init__.py", line 44, in _load
    module = _importlib.import_module(self.__name__)
  File "C:\Anaconda3\envs\tensorflow2_test\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Anaconda3\envs\tensorflow2_test\lib\site-packages\tensorflow_core\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Anaconda3\envs\tensorflow2_test\lib\site-packages\tensorflow_core\python\pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "C:\Anaconda3\envs\tensorflow2_test\lib\site-packages\tensorflow_core\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Anaconda3\envs\tensorflow2_test\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Anaconda3\envs\tensorflow2_test\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Anaconda3\envs\tensorflow2_test\lib\imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Anaconda3\envs\tensorflow2_test\lib\imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: A dynamic link library (DLL) initialization routine failed.


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

(tensorflow2_test) C:\~\install environment\production>
```
package list:
-------------
(tensorflow2_test) C:\~\install environment\production>conda list
# packages in environment at C:\Anaconda3\envs\tensorflow2_test:
#
# Name                    Version                   Build  Channel
absl-py                   0.8.1                    pypi_0    pypi
astor                     0.8.0                    pypi_0    pypi
ca-certificates           2019.8.28                     0
certifi                   2019.9.11                py37_0
gast                      0.2.2                    pypi_0    pypi
google-pasta              0.1.7                    pypi_0    pypi
grpcio                    1.24.1                   pypi_0    pypi
h5py                      2.10.0                   pypi_0    pypi
keras-applications        1.0.8                    pypi_0    pypi
keras-preprocessing       1.1.0                    pypi_0    pypi
markdown                  3.1.1                    pypi_0    pypi
numpy                     1.17.2                   pypi_0    pypi
openssl                   1.1.1d               he774522_2
opt-einsum                3.1.0                    pypi_0    pypi
pip                       19.2.3                   py37_0
protobuf                  3.10.0                   pypi_0    pypi
python                    3.7.4                h5263a28_0
setuptools                41.4.0                   py37_0
six                       1.12.0                   pypi_0    pypi
sqlite                    3.30.0               he774522_0
tensorboard               2.0.0                    pypi_0    pypi
tensorflow                2.0.0                    pypi_0    pypi
tensorflow-estimator      2.0.0                    pypi_0    pypi
termcolor                 1.1.0                    pypi_0    pypi
vc                        14.1                 h0510ff6_4
vs2015_runtime            14.16.27012          hf0eaf9b_0
werkzeug                  0.16.0                   pypi_0    pypi
wheel                     0.33.6                   py37_0
wincertstore              0.2                      py37_0
wrapt                     1.11.2                   pypi_0    pypi

(tensorflow2_test) C:\~\install environment\production>

**Comment by mihaimaruseac** [comment]
Can you check your CPU to see if it supports AVX, please?

**Comment by ymodak** [comment]
*TensorFlow release binaries (CPU/GPU) version 1.6 and higher are prebuilt with AVX instruction sets.*  
See [hardware requirements][1] to know more.  

Therefore on any CPU that does not have these instruction sets, either CPU or GPU version of TF will fail to load.
Apparently, your CPU model does not support AVX instruction sets. You can still use TensorFlow with the alternatives given below:  

* Try Google Colab to use TensorFlow.    
 * The easiest way to use TF will be to switch to [google colab](https://colab.sandbox.google.com/notebooks/welcome.ipynb#recent=true). You get pre-installed latest stable TF version. Also you can use ```pip install``` to install any other preferred TF version.  
    * It has an added advantage since you can you easily switch to different hardware accelerators (cpu, gpu, tpu) as per the task. 
    * All you need is a good internet connection and you are all set.  
* Try to build TF from sources by changing CPU optimization flags.


  [1]: https://www.tensorflow.org/install/pip#hardware-requirements

**Comment by mihaimaruseac** [comment]
See also #19584 if your CPU doesn't support AVX.

**Comment by tessy1234** [comment]
I am running Intel® Core™ i7-820QM Processor (8M Cache, 1.73 GHz)
[https://www.google.at/url?sa=t&rct=j&q=&esrc=s&source=web&cd=3&cad=rja&uact=8&ved=2ahUKEwiGltvkoZzlAhU76KYKHXt0DiMQFjACegQIARAB&url=https%3A%2F%2Fark.intel.com%2Fcontent%2Fwww%2Fus%2Fen%2Fark%2Fproducts%2F43124%2Fintel-core-i7-820qm-processor-8m-cache-1-73-ghz.html&usg=AOvVaw1v8vs0mUnJQ1ZAU7OhpQJz](url)

According to this spec it supports: Instruction Set Extensions:  Intel® SSE4.2
The annotation to Instruction Set Extensions says: May support SSE (Streaming SIMD Extensions) and AVX (Advanced Vector Extensions).

I guess Intel® SSE4.2 does not support AVX by default, but I am not sure.

As a reference I installed Tensorflow 1.14 and it works.
According to GitHub tags TensorFlow  1.6.0 was released on Feb 28, 2018, but I am able to run Tensorflow 1.14 released on Jun 19, 2019.
If Tensorflow 1.14 needs AVX, then the statement on the Tensorflow install page contradicts my test result.

Can you explain what greater-equal TensorFlow 1.6 means in this context?

Summary with Instruction Set Extensions on my computer:
•	Tensorflow 1.14 working. 
•	TensorFlow 2.0.0 not working.

Open question: 
Does SSE4.2 support AVX by default?

**Comment by tessy1234** [comment]
Link: Intel® Core™ i7-820QM Processor (8M Cache, 1.73 GHz)
[https://ark.intel.com/content/www/us/en/ark/products/43124/intel-core-i7-820qm-processor-8m-cache-1-73-ghz.html](url)

**Comment by mihaimaruseac** [comment]
If 1.14 worked then this is not an AVX issue

**Comment by tessy1234** [comment]
You are saying hardware requirements for tensorflow 2.0 cpu are satisfied!
This brings me back to the original question.
When tensorflow 1.14 cpu is working, why is tensorflow 2.0 cpu not working?

**Comment by mihaimaruseac** [comment]
The best way forward would be to identify which DLL fails to load

**Comment by gadagashwini** [comment]
@tessy1234,
Open ...\Lib\site-packages\tensorflow\python\_pywrap_tensorflow_internal.pyd use Dependency Walker, it will show you the 
DLL dependency tree, you will find which DLL cause the problem. Dependency Walker link : http://www.dependencywalker.com/

**Comment by tessy1234** [comment]
![dependencies_snapshoot](https://user-images.githubusercontent.com/41914070/67006301-1743b100-f0e5-11e9-8ef8-fbad49502b0f.jpg)

Run Dependencies(Dependency walker): 
------------------------------------
resource:
https://github.com/lucasg/Dependencies/releases/download/v1.9/Dependencies_x64_Release.zip
run:
C:\run\dependencies\DependenciesGui.exe

open file:
C:\Anaconda3\envs\tensorflow2_env\Lib\site-packages\tensorflow_core\python\_pywrap_tensorflow_internal.pyd

result:
python37.dll missing 
(see screenshot above)

hint:
found
C:\Anaconda3\envs\tensorflow2_env\python37.dll

installation difference:
------------------------
working environment: tensorflow 1.14.0
conda install tensorflow

non-working environment: tensorflow 2.0 
pip install tensorflow

possible explanation:
---------------------
pip installing library into anaconda environment instead of using the conda package manager?
conda install for tensorflow 2.0 cpu not available.

how to proceed?
------------------

**Comment by tessy1234** [comment]
I am creating a brand new environment (in my case "tensorflow2_env") within anaconda and then run "pip install tensorflow" as requested.
The tensorflow runtime calls _pywrap_tensorflow_internal.pyd, which needs python37.dll, but can't find it.
The missing python37.dll is part of tensorflow runtime and can be found in tensorflow2_env.
Therefore tensorflow should know python37.dll.
Is this a valid argument?

**Comment by tessy1234** [comment]
Where can I get the SWIG interface declaration of the python extension _pywrap_tensorflow_internal.pyd?

**Comment by gadagashwini** [comment]
@tessy1234, 
Would you like to try with PIP virtual env. If yes, please follow the below steps:
```
$pip install virtualenv
$virtualenv tf_2.0.0   # tf_2.0.0 is virtual env name
$source tf_2.0.0/bin/activate
tf_2.0.0 $ pip install tensorflow==2.0.0
```
Let us know how it progresses. Thanks!

**Comment by tessy1234** [comment]
tests:
------
tensorflow 2.0 import failed:
-------------------------------
python -c "import tensorflow as tf"

detail:
-------
#CLI anaconda;  default path: C:\Users\~
#optional: explore tensorflow runtime
#test target: cd into following directory
C:\Anaconda3\envs\tensorflow2_env\Lib\site-packages\tensorflow_core\python
C:\Anaconda3\envs\tensorflow_1_14_env\Lib\site-packages\tensorflow\python

#activate environment
conda activate tensorflow2_env
conda activate tensorflow_1_14_env
deactivate

#tensorflow 1.14
#all imports successful
python -c "import tensorflow as tf"
python -c "import tensorflow.python.pywrap_tensorflow"
python -c "import tensorflow.python.pywrap_tensorflow_internal"
#import .pyd file; C++-object code
python -c "import tensorflow.python._pywrap_tensorflow_internal"

#tensorflow 2.0
#all imports fail
python -c "import tensorflow as tf"
python -c "import tensorflow.python._pywrap_tensorflow_internal"

#optional
#list packages
conda list
conda list tensorflow
conda list python

**Comment by mihaimaruseac** [comment]
Why do you activate both environments at once and then deactivate one?

**Comment by tessy1234** [comment]
test tensorflow 2.0 virtualenv:
--------------------------------
virtual environment:
----------------------
#location of environments
cd C:\environments

#create virtual environment
#python version 3.7.4
virtualenv -p C:\Users\~\AppData\Local\Programs\Python\Python37\python.exe tf_2_0_0

#remove virtual environment
rm -r tf_2_0_0

#activate environment 
tf_2_0_0\Scripts\activate
#deactivate environment 
deactivate

install packages
-------------------
pip install tensorflow==2.0.0

verify install:
---------------
python -c "import tensorflow as tf"

packages:
-----------
(tf_2_0_0) C:\environments>python -V
Python 3.7.4

(tf_2_0_0) C:\environments>pip list
Package              Version
-------------------- -------
absl-py              0.8.1
astor                0.8.0
gast                 0.2.2
google-pasta         0.1.7
grpcio               1.24.1
h5py                 2.10.0
Keras-Applications   1.0.8
Keras-Preprocessing  1.1.0
Markdown             3.1.1
numpy                1.17.3
opt-einsum           3.1.0
pip                  19.3.1
protobuf             3.10.0
setuptools           41.4.0
six                  1.12.0
tensorboard          2.0.0
tensorflow           2.0.0
tensorflow-estimator 2.0.0
termcolor            1.1.0
Werkzeug             0.16.0
wheel                0.33.6
wrapt                1.11.2

(tf_2_0_0) C:\environments>

error trace:
------------
(tf_2_0_0) C:\environments>python -c "import tensorflow as tf"
Traceback (most recent call last):
  File "C:\environments\tf_2_0_0\lib\site-packages\tensorflow_core\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\environments\tf_2_0_0\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\environments\tf_2_0_0\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\environments\tf_2_0_0\lib\imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "C:\environments\tf_2_0_0\lib\imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: A dynamic link library (DLL) initialization routine failed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\environments\tf_2_0_0\lib\site-packages\tensorflow\__init__.py", line 98, in <module>
    from tensorflow_core import *
  File "C:\environments\tf_2_0_0\lib\site-packages\tensorflow_core\__init__.py", line 40, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "C:\environments\tf_2_0_0\lib\site-packages\tensorflow\__init__.py", line 50, in __getattr__
    module = self._load()
  File "C:\environments\tf_2_0_0\lib\site-packages\tensorflow\__init__.py", line 44, in _load
    module = _importlib.import_module(self.__name__)
  File "C:\environments\tf_2_0_0\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\environments\tf_2_0_0\lib\site-packages\tensorflow_core\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\environments\tf_2_0_0\lib\site-packages\tensorflow_core\python\pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "C:\environments\tf_2_0_0\lib\site-packages\tensorflow_core\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\environments\tf_2_0_0\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\environments\tf_2_0_0\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\environments\tf_2_0_0\lib\imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "C:\environments\tf_2_0_0\lib\imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: A dynamic link library (DLL) initialization routine failed.


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

(tf_2_0_0) C:\environments>

**Comment by tessy1234** [comment]
anaconda tests:
-----------------
Activate and deactivate the various environments were done consecutively.

**Comment by mihaimaruseac** [comment]
Please post log of a full session instead of separating commands by their scope and not posting relevant output.

Also, please use proper markdown to format code blocks/console output

```
 ```
 your code goes here
 ```
```

**Comment by tessy1234** [comment]
debug tensorflow 2.0 runtime:
-------------------------
analyse last statement (line 345) in error trace before exception
(File "C:\environments\tf_2_0_0\lib\imp.py", line 345, in load_dynamic)

result:
-------
for some reasons the DLL "_pywrap_tensorflow_internal.pyd" can't be loaded into tensorflow runtime!

detail:
--------
#see top entries in error trace
#included debug information in function load_dynamic in file imp.py before line 345:
		...
        print('debug: entry')
        print(spec)
        print('debug: exit')
        return _load(spec)

error trace:
------------
```
(tf_2_0_0) C:\environments>python -c "import tensorflow as tf"
debug: entry
ModuleSpec(name='_pywrap_tensorflow_internal', loader=<_frozen_importlib_external.ExtensionFileLoader object at 0x000001F0D159B288>, origin='C:\\environments\\tf_2_0_0\\lib\\site-packages\\tensorflow_core\\python\\_pywrap_tensorflow_internal.pyd')
debug: exit
Traceback (most recent call last):
  File "C:\environments\tf_2_0_0\lib\site-packages\tensorflow_core\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\environments\tf_2_0_0\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\environments\tf_2_0_0\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\environments\tf_2_0_0\lib\imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "C:\environments\tf_2_0_0\lib\imp.py", line 345, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: A dynamic link library (DLL) initialization routine failed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\environments\tf_2_0_0\lib\site-packages\tensorflow\__init__.py", line 98, in <module>
    from tensorflow_core import *
  File "C:\environments\tf_2_0_0\lib\site-packages\tensorflow_core\__init__.py", line 40, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "C:\environments\tf_2_0_0\lib\site-packages\tensorflow\__init__.py", line 50, in __getattr__
    module = self._load()
  File "C:\environments\tf_2_0_0\lib\site-packages\tensorflow\__init__.py", line 44, in _load
    module = _importlib.import_module(self.__name__)
  File "C:\environments\tf_2_0_0\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\environments\tf_2_0_0\lib\site-packages\tensorflow_core\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\environments\tf_2_0_0\lib\site-packages\tensorflow_core\python\pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "C:\environments\tf_2_0_0\lib\site-packages\tensorflow_core\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\environments\tf_2_0_0\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\environments\tf_2_0_0\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\environments\tf_2_0_0\lib\imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "C:\environments\tf_2_0_0\lib\imp.py", line 345, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: A dynamic link library (DLL) initialization routine failed.


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

(tf_2_0_0) C:\environments>
```

**Comment by tessy1234** [comment]
can you provide a unit test for the DLL "_pywrap_tensorflow_internal.pyd"; the fact is that it can't be loaded into tensorflow runtime 2.0 cpu on windows 10; I have no idea why it is not loading properly.

**Comment by gunan** [comment]
This is an AVX issue.
The CPU you mentioned does not have AVX support.
Maybe you downloaded the previous package from anaconda (not built by us) and newer one through pip (built by us) and that may be the reason 1.14 worked.

But this is definitely caused by your CPU not having AVX instructions.
SSE4.2 and AVX are two separate instruction sets.

**Comment by tessy1234** [comment]
I created 2 conda environments: 
1) tensorflow2_0_conda environment:
conda installation using 
`conda install python=3.7 tensorflow=2.0`
2) tensorflow2_0_pip environment:
pip installation using
`conda install python=3.7 
pip install tensorflow==2.0.0
`
Both installations completed without any error.

Import test: 
`python -c "import tensorflow as tf"`
ad 1) conda env works fine
ad 2) pip env failed with error message as above
`ImportError: DLL load failed ...`

Why does conda env work fine but pip env don't?

**Comment by mihaimaruseac** [comment]
Conda built from source whereas pip used a prebuilt binary.

Building from source allows you to get working pip even if your CPU does not support AVX

If conda didn't built from source, someone else did a built for conda.
