### ISSUE TITLE
INT8 calibration error using TrtGraphConverterV2 in TensorFlow2.0

### ISSUE THREAD

**Issue by ay27** [tensorflow/tensorflow#33277]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): pip install tensorflow-gpu
- TensorFlow version (use command below): v2.0.0-rc2-26-g64c3d38
- Python version: 3.6.8
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: cuda10.0
- GPU model and memory: TITAN V, 12GB

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
Using TensorRT version in: 5.1.5
When using TrtGraphConverterV2 to convert a saved model and trying to calibrate with INT8 support, it will raise the error shown as follow.
Should be mentioned that, the FP16 and FP32 conversation is work fine but only the INT8 is failed.
```
2019-10-12 06:33:06.015951: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libnvinfer_plugin.so.5
2019-10-12 06:33:06.142792: E tensorflow/compiler/tf2tensorrt/kernels/trt_engine_op.cc:838] Calibration failed: Invalid argument: Pad only supports explicit padding on 4 dimensional tensor, at StatefulPartitionedCall/resnet50/conv1_pad/Pad
2019-10-12 06:33:06.142978: W tensorflow/core/common_runtime/base_collective_executor.cc:216] BaseCollectiveExecutor::StartAbort Internal: Failed to feed calibration data
         [[{{node TRTEngineOp_0}}]]
Traceback (most recent call last):
  File "calibration.py", line 16, in <module>
    converter.convert(calibration_input_fn=input_fn)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/compiler/tensorrt/trt_convert.py", line 984, in convert
    self._converted_func(*map(ops.convert_to_tensor, inp))
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/eager/function.py", line 1081, in __call__
    return self._call_impl(args, kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/eager/function.py", line 1121, in _call_impl
    return self._call_flat(args, self.captured_inputs, cancellation_manager)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/eager/function.py", line 1224, in _call_flat
    ctx, args, cancellation_manager=cancellation_manager)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/eager/function.py", line 511, in call
    ctx=ctx)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/eager/execute.py", line 67, in quick_execute
    six.raise_from(core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.InternalError:  Failed to feed calibration data
         [[node TRTEngineOp_0 (defined at /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/ops.py:1751) ]] [Op:__inference_pruned_79677]

Function call stack:
pruned

terminate called without an active exception
```
**Describe the expected behavior**

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.
```python
from tensorflow.python.compiler.tensorrt import trt_convert as trt
import tensorflow as tf

model = tf.keras.applications.ResNet50(weights=None)
out = model(tf.random.normal((2, 224, 224, 3)))
tf.saved_model.save(model, './saved_model/')
print(model.input_names, model.output_names)

params = trt.DEFAULT_TRT_CONVERSION_PARAMS._replace(precision_mode='INT8',
                                                    use_calibration=True)
converter = trt.TrtGraphConverterV2(input_saved_model_dir='./saved_model/', conversion_params=params)

def input_fn():
    for i in range(10):
        yield tf.random.normal((1, 224, 224, 3))
converter.convert(calibration_input_fn=input_fn)  #  raise error here
converter.save('./model.trt')
```
**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by ay27** [comment]
I also tried another simple model and found that the existing Conv2D layer will lead to error. Also when change to FP16 or FP32, all the convert works fine!! And no matter the data format is channels_first or channals_last, the results are the same.

Check this code for more details:
```python
from tensorflow.python.compiler.tensorrt import trt_convert as trt
import tensorflow as tf
from tensorflow.python.framework.func_graph import def_function
from tensorflow.python.framework import tensor_spec

class MyModel(tf.keras.Model):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.conv2 = tf.keras.layers.Conv2D(64, (7, 7), strides=(2, 2), padding='valid', data_format='channels_last')
        self.dense = tf.keras.layers.Dense(10, activation='softmax')

    @def_function.function(input_signature=[
        tensor_spec.TensorSpec(shape=[None, 32, 32, 3], dtype=tf.float32)
    ])
    def call(self, inputs, training=True, **kwargs):
        inputs = self.conv2(inputs)  # remove this line, work fine!!
        x = tf.reshape(inputs, [-1, inputs.shape[-1]])
        x = self.dense(x)
        return x

model = MyModel()
out = model(tf.random.normal((2, 32, 32, 3)))
tf.saved_model.save(model, './saved_model/', {'model_key': model.call})

params = trt.DEFAULT_TRT_CONVERSION_PARAMS._replace(precision_mode='INT8',
                                                    use_calibration=True)
converter = trt.TrtGraphConverterV2(input_saved_model_dir='./saved_model/', conversion_params=params,
                                    input_saved_model_signature_key='model_key')
def input_fn():
    for i in range(10):
        yield tf.random.normal((1, 32, 32, 3))
converter.convert(calibration_input_fn=input_fn)
converter.save('./model.trt')
```

**Comment by oanush** [comment]
@ay27 ,
When tried executing the given code, [colab](https://colab.sandbox.google.com/gist/oanush/6b73dc27aaff2332555c403e2712b804/33277.ipynb) session crashed for both the given code snippets. Can you check and provide gist of colab to reproduce the issue ?

**Comment by ay27** [comment]
@oanush ,
I try to run in colab, the crash reason is the environment does not have the TensorRT package. 
![image](https://user-images.githubusercontent.com/3942031/66733051-d3f10480-ee90-11e9-9c5e-9eb2dec12ad4.png)

**Comment by ay27** [comment]
@oanush ,
I tried to reproduce in colab, the crash reason is the environment in colab does not have the TensorRT package. You can check the running log for details.
I am not familiar with colab, and don't know how to install the package on colab. Maybe you can reproduce the problem in a local CUDA environment?

![image](https://user-images.githubusercontent.com/3942031/66733274-92ad2480-ee91-11e9-875a-a2190bcea9db.png)

**Comment by ay27** [comment]
Does this issue have any progress?

**Comment by soldierofhell** [comment]
I'm also interested. To reproduce in colab one has to install TensorRT 5.1.5
`!apt-get install -y --no-install-recommends libnvinfer5=5.1.5-1+cuda10.0 libnvinfer-dev=5.1.5-1+cuda10.0`

**Comment by paapu88** [comment]
same problem here
pip3 install tensorflow-gpu==2.0.0
tf: v2.0.0-rc2-26-g64c3d38 2.0.0
dpkg -l | grep nvinfer

> ii  libnvinfer-dev                                              6.0.1-1+cuda10.1                                amd64        TensorRT development libraries and headers
ii  libnvinfer5                                                 5.1.5-1+cuda10.1                                amd64        TensorRT runtime libraries
ii  libnvinfer6                                                 6.0.1-1+cuda10.1                                amd64        TensorRT runtime libraries

output:
>tiny_yolov3_3l.py", line 100, in __init__
    converter.convert(calibration_input_fn=self.get_calibration_batch)
  File "/home/mka/venvs/tf2/lib/python3.6/site-packages/tensorflow_core/python/compiler/tensorrt/trt_convert.py", line 984, in convert
    self._converted_func(*map(ops.convert_to_tensor, inp))
  File "/home/mka/venvs/tf2/lib/python3.6/site-packages/tensorflow_core/python/eager/function.py", line 1081, in __call__
    return self._call_impl(args, kwargs)
  File "/home/mka/venvs/tf2/lib/python3.6/site-packages/tensorflow_core/python/eager/function.py", line 1121, in _call_impl
    return self._call_flat(args, self.captured_inputs, cancellation_manager)
  File "/home/mka/venvs/tf2/lib/python3.6/site-packages/tensorflow_core/python/eager/function.py", line 1224, in _call_flat
    ctx, args, cancellation_manager=cancellation_manager)
  File "/home/mka/venvs/tf2/lib/python3.6/site-packages/tensorflow_core/python/eager/function.py", line 511, in call
    ctx=ctx)
  File "/home/mka/venvs/tf2/lib/python3.6/site-packages/tensorflow_core/python/eager/execute.py", line 67, in quick_execute
    six.raise_from(core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.InternalError:  Failed to feed calibration data
	 [[node TRTEngineOp_3 (defined at /home/mka/venvs/tf2/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py:1751) ]] [Op:__inference_pruned_22003]

>Function call stack:
pruned

>terminate called without an active exception
Aborted (core dumped)

**Comment by aaroey** [comment]
@ay27 could you try letting the input_fn return a tuple?
`        yield tf.random.normal((1, 224, 224, 3)),`

**Comment by aaroey** [comment]
After making the above change, the code snippet mentioned by @ay27 works well for me.

**Comment by amahendrakar** [comment]
> @ay27 could you try letting the input_fn return a tuple?
> ` yield tf.random.normal((1, 224, 224, 3)),`

@ay27,
Is this still an issue? Please feel free to close the issue if resolved. Thanks!

**Comment by UcefMountacer** [comment]
I had a similar problem when trying to convert SSD MobileNet2 to INT8. 

The error was : 

```
InvalidArgumentError: 2 root error(s) found.
  (0) Invalid argument:  Input shape axis 0 must equal 1, got shape [320,320,3]
	 [[node StatefulPartitionedCall/Preprocessor/unstack (defined at <ipython-input-68-f0b69da9b8ec>:1) ]]
	 [[StatefulPartitionedCall/Postprocessor/BatchMultiClassNonMaxSuppression/MultiClassNonMaxSuppression/Reshape_11/_38]]
  (1) Invalid argument:  Input shape axis 0 must equal 1, got shape [320,320,3]
	 [[node StatefulPartitionedCall/Preprocessor/unstack (defined at <ipython-input-68-f0b69da9b8ec>:1) ]]
0 successful operations.
0 derived errors ignored. [Op:__inference_pruned_835619]

Function call stack:
pruned -> pruned
```

Adding a comma at the end to specify a tuple data format solved the issue :)

**Comment by vinilreddy36** [comment]
> @ay27 could you try letting the input_fn return a tuple?
> ` yield tf.random.normal((1, 224, 224, 3)),`

adding that  line raised a new error 

File "test.py", line 21, in <module>
   converter.convert(calibration_input_fn=my_calibration_input_fn)
  File "/home/vinil/.local/lib/python3.6/site-packages/tensorflow/python/compiler/tensorrt/trt_convert.py", line 1124, in convert
    self._converted_func(*map(ops.convert_to_tensor, inp))
  File "/home/vinil/.local/lib/python3.6/site-packages/tensorflow/python/eager/function.py", line 1669, in __call__
    return self._call_impl(args, kwargs)
  File "/home/vinil/.local/lib/python3.6/site-packages/tensorflow/python/eager/wrap_function.py", line 247, in _call_impl
    args, kwargs, cancellation_manager)
  File "/home/vinil/.local/lib/python3.6/site-packages/tensorflow/python/eager/function.py", line 1687, in _call_impl
    return self._call_with_flat_signature(args, kwargs, cancellation_manager)
  File "/home/vinil/.local/lib/python3.6/site-packages/tensorflow/python/eager/function.py", line 1736, in _call_with_flat_signature
    return self._call_flat(args, self.captured_inputs, cancellation_manager)
  File "/home/vinil/.local/lib/python3.6/site-packages/tensorflow/python/eager/function.py", line 1919, in _call_flat
    ctx, args, cancellation_manager=cancellation_manager))
  File "/home/vinil/.local/lib/python3.6/site-packages/tensorflow/python/eager/function.py", line 560, in call
    ctx=ctx)
  File "/home/vinil/.local/lib/python3.6/site-packages/tensorflow/python/eager/execute.py", line 60, in quick_execute
    inputs, attrs, num_outputs)
`tensorflow.python.framework.errors_impl.InvalidArgumentError: cannot compute __inference_pruned_63044 as input #0(zero-based) was expected to be a uint8 tensor but is a float tensor [Op:__inference_pruned_63044]`

**Comment by snownus** [comment]
@vinilreddy36 , input is float, need to update to tf.cast to int8
