### ISSUE TITLE
Installation to shared (global) python env via Conda.

### ISSUE THREAD

**Issue by MGarvinNYC** [tensorflow/tensorflow#33275]
I understand that Conda can be used to install older versions of Tensorflow, but it appears difficult with TF 2.0.  Most articles refer to creating the environment via Conda, but then installing via pip after the env is activated.  Given tales of problems when mixing install methods, it seems safer to find an installation method using Conda directly.  Looking for methods or projected timeline when this will be available.

**Comment by oanush** [comment]
@MGarvinNYC ,
Hi can you please try creating a pip environment and then install TF using pip in the same. As we don't support issues with conda environment, refer the [link](https://github.com/tensorflow/tensorflow/issues/33206#issuecomment-541148907).Thanks!

**Comment by oanush** [comment]
@MGarvinNYC ,
Any update on the issue?thanks!

**Comment by oanush** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Comment by MGarvinNYC** [comment]
Issue was not resolved in this thread.  The goal was to maintain compatibility with Conda environments, and pip does not do that.

But it should be noted that as of a couple days ago, Tensorflow 2.0 has been added to the Conda repo, which should solve problems with compatibility
