### ISSUE TITLE
Issue running compile_ios_tensorflow.sh?

### ISSUE THREAD

**Issue by sahil912** [tensorflow/tensorflow#3327]
On running compile_ios_tensorflow.sh, I am facing the below issue.

**sh compile_ios_tensorflow.sh** 

    sed: tensorflow/contrib/makefile/downloads/eigen-latest/eigen/src/Core/arch/NEON/Complex.h: No such file or directory
    sed: tensorflow/contrib/makefile/downloads/eigen-latest/eigen/src/Core/arch/NEON/Complex.h: No such file or directory
    sed: tensorflow/contrib/makefile/downloads/eigen-latest/eigen/src/Core/arch/NEON/Complex.h: No such file or directory
    make: tensorflow/contrib/makefile/Makefile: No such file or directory
    make: *** No rule to make target `tensorflow/contrib/makefile/Makefile'.  Stop.
    make: tensorflow/contrib/makefile/Makefile: No such file or directory
    make: *** No rule to make target `tensorflow/contrib/makefile/Makefile'.  Stop.
armv7 compilation failed.

because of this I am unable to proceed with iOS example, cos of missing libtensorflow.a 

    ld: file not found: /Users/jsahil/projects/tensorflow/tensorflow-master/tensorflow/contrib/ios_examples/camera/../../makefile/gen/lib/libtensorflow-core.a

Please let me know, if I am missing something or this is an issue with the script. Thanks

**Comment by jmchen-g** [comment]
@petewarden Could you take a look at this please?

**Comment by petewarden** [comment]
Sorry you're hitting problems! It looks like your immediate problem is that you're running the script with the working directory set to tensorflow/contrib/makefile, e.g. you've done this:

```bash
git clone https://github.com/tensorflow/tensorflow
cd tensorflow/tensorflow/contrib/makefile
sh compile_ios_tensorflow.sh
```

What you should actually do is this:

```bash
git clone https://github.com/tensorflow/tensorflow
cd tensorflow
tensorflow/contrib/makefile/compile_all_ios.sh
```

The documentation is at https://github.com/tensorflow/tensorflow/tree/master/tensorflow/contrib/makefile#ios but I realize that is a bit unclear about which directory to run the scripts from, so we should improve that. 

Does that help?

**Comment by sahil912** [comment]
@petewarden  I have tried to follow the steps you mentioned and I am getting the following error

    Undefined symbols for architecture armv7:
  "tensorflow::DebugNodeInserter::InsertNodes(tensorflow::Graph*, tensorflow::Device*)", referenced from:
      tensorflow::DirectSession::GetOrCreateExecutors(tensorflow::thread::ThreadPool*, tensorflow::gtl::ArraySlice<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, tensorflow::gtl::ArraySlice<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, tensorflow::gtl::ArraySlice<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, tensorflow::DirectSession::ExecutorsAndKeys**, tensorflow::DirectSession::RunStateArgs*) in libtensorflow-core-armv7.a(direct_session.o)
  "void tensorflow::HandleStridedSliceGradCase<Eigen::ThreadPoolDevice, tensorflow::bfloat16, 1>(tensorflow::OpKernelContext*, tensorflow::gtl::ArraySlice<long long> const&, tensorflow::gtl::ArraySlice<long long> const&, tensorflow::gtl::ArraySlice<long long> const&, tensorflow::TensorShape const&, bool, tensorflow::Tensor*)", referenced from:
      tensorflow::StridedSliceGradOp<Eigen::ThreadPoolDevice, tensorflow::bfloat16>::Compute(tensorflow::OpKernelContext*) in libtensorflow-core-armv7.a(strided_slice_op.o)
  "void tensorflow::HandleStridedSliceCase<Eigen::ThreadPoolDevice, tensorflow::bfloat16, 5>(tensorflow::OpKernelContext*, tensorflow::gtl::ArraySlice<long long> const&, tensorflow::gtl::ArraySlice<long long> const&, tensorflow::gtl::ArraySlice<long long> const&, tensorflow::TensorShape const&, bool, tensorflow::Tensor*)", referenced from:
      tensorflow::StridedSliceOp<Eigen::ThreadPoolDevice, tensorflow::bfloat16>::Compute(tensorflow::OpKernelContext*) in libtensorflow-core-armv7.a(strided_slice_op.o)
  "void tensorflow::HandleStridedSliceCase<Eigen::ThreadPoolDevice, tensorflow::bfloat16, 6>(tensorflow::OpKernelContext*, tensorflow::gtl::ArraySlice<long long> const&, tensorflow::gtl::ArraySlice<long long> const&, tensorflow::gtl::ArraySlice<long long> const&, tensorflow::TensorShape const&, bool, tensorflow::Tensor*)", referenced from:
      tensorflow::StridedSliceOp<Eigen::ThreadPoolDevice, tensorflow::bfloat16>::Compute(tensorflow::OpKernelContext*) in libtensorflow-core-armv7.a(strided_slice_op.o)
  "void tensorflow::HandleStridedSliceGradCase<Eigen::ThreadPoolDevice, float, 1>(tensorflow::OpKernelContext*, tensorflow::gtl::ArraySlice<long long> const&, tensorflow::gtl::ArraySlice<long long> const&, tensorflow::gtl::ArraySlice<long long> const&, tensorflow::TensorShape const&, bool, tensorflow::Tensor*)", referenced from:
      tensorflow::StridedSliceGradOp<Eigen::ThreadPoolDevice, float>::Compute(tensorflow::OpKernelContext*) in libtensorflow-core-armv7.a(strided_slice_op.o)
  "void tensorflow::HandleStridedSliceGradCase<Eigen::ThreadPoolDevice, float, 2>(tensorflow::OpKernelContext*, tensorflow::gtl::ArraySlice<long long> const&, tensorflow::gtl::ArraySlice<long long> const&, tensorflow::gtl::ArraySlice<long long> const&, tensorflow::TensorShape const&, bool, tensorflow::Tensor*)", referenced from:
      tensorflow::StridedSliceGradOp<Eigen::ThreadPoolDevice, float>::Compute(tensorflow::OpKernelContext*) in libtensorflow-core-armv7.a(strided_slice_op.o)
  "void tensorflow::HandleStridedSliceGradCase<Eigen::ThreadPoolDevice, tensorflow::bfloat16, 2>(tensorflow::OpKernelContext*, tensorflow::gtl::ArraySlice<long long> const&, tensorflow::gtl::ArraySlice<long long> const&, tensorflow::gtl::ArraySlice<long long> const&, tensorflow::TensorShape const&, bool, tensorflow::Tensor*)", referenced from:
      tensorflow::StridedSliceGradOp<Eigen::ThreadPoolDevice, tensorflow::bfloat16>::Compute(tensorflow::OpKernelContext*) in libtensorflow-core-armv7.a(strided_slice_op.o)
  "void tensorflow::HandleStridedSliceCase<Eigen::ThreadPoolDevice, float, 1>(tensorflow::OpKernelContext*, tensorflow::gtl::ArraySlice<long long> const&, tensorflow::gtl::ArraySlice<long long> const&, tensorflow::gtl::ArraySlice<long long> const&, tensorflow::TensorShape const&, bool, tensorflow::Tensor*)", referenced from:
      tensorflow::StridedSliceOp<Eigen::ThreadPoolDevice, float>::Compute(tensorflow::OpKernelContext*) in libtensorflow-core-armv7.a(strided_slice_op.o)
  "void tensorflow::HandleStridedSliceGradCase<Eigen::ThreadPoolDevice, float, 6>(tensorflow::OpKernelContext*, tensorflow::gtl::ArraySlice<long long> const&, tensorflow::gtl::ArraySlice<long long> const&, tensorflow::gtl::ArraySlice<long long> const&, tensorflow::TensorShape const&, bool, tensorflow::Tensor*)", referenced from:
      tensorflow::StridedSliceGradOp<Eigen::ThreadPoolDevice, float>::Compute(tensorflow::OpKernelContext*) in libtensorflow-core-armv7.a(strided_slice_op.o)
  "void tensorflow::HandleStridedSliceGradCase<Eigen::ThreadPoolDevice, tensorflow::bfloat16, 4>(tensorflow::OpKernelContext*, tensorflow::gtl::ArraySlice<long long> const&, tensorflow::gtl::ArraySlice<long long> const&, tensorflow::gtl::ArraySlice<long long> const&, tensorflow::TensorShape const&, bool, tensorflow::Tensor*)", referenced from:
      tensorflow::StridedSliceGradOp<Eigen::ThreadPoolDevice, tensorflow::bfloat16>::Compute(tensorflow::OpKernelContext*) in libtensorflow-core-armv7.a(strided_slice_op.o)
  "void tensorflow::HandleStridedSliceCase<Eigen::ThreadPoolDevice, tensorflow::bfloat16, 2>(tensorflow::OpKernelContext*, tensorflow::gtl::ArraySlice<long long> const&, tensorflow::gtl::ArraySlice<long long> const&, tensorflow::gtl::ArraySlice<long long> const&, tensorflow::TensorShape const&, bool, tensorflow::Tensor*)", referenced from:
      tensorflow::StridedSliceOp<Eigen::ThreadPoolDevice, tensorflow::bfloat16>::Compute(tensorflow::OpKernelContext*) in libtensorflow-core-armv7.a(strided_slice_op.o)
  "void tensorflow::HandleStridedSliceCase<Eigen::ThreadPoolDevice, float, 3>(tensorflow::OpKernelContext*, tensorflow::gtl::ArraySlice<long long> const&, tensorflow::gtl::ArraySlice<long long> const&, tensorflow::gtl::ArraySlice<long long> const&, tensorflow::TensorShape const&, bool, tensorflow::Tensor*)", referenced from:
      tensorflow::StridedSliceOp<Eigen::ThreadPoolDevice, float>::Compute(tensorflow::OpKernelContext*) in libtensorflow-core-armv7.a(strided_slice_op.o)
  "void tensorflow::HandleStridedSliceGradCase<Eigen::ThreadPoolDevice, tensorflow::bfloat16, 5>(tensorflow::OpKernelContext*, tensorflow::gtl::ArraySlice<long long> const&, tensorflow::gtl::ArraySlice<long long> const&, tensorflow::gtl::ArraySlice<long long> const&, tensorflow::TensorShape const&, bool, tensorflow::Tensor*)", referenced from:
      tensorflow::StridedSliceGradOp<Eigen::ThreadPoolDevice, tensorflow::bfloat16>::Compute(tensorflow::OpKernelContext*) in libtensorflow-core-armv7.a(strided_slice_op.o)
  "void tensorflow::HandleStridedSliceCase<Eigen::ThreadPoolDevice, tensorflow::bfloat16, 3>(tensorflow::OpKernelContext*, tensorflow::gtl::ArraySlice<long long> const&, tensorflow::gtl::ArraySlice<long long> const&, tensorflow::gtl::ArraySlice<long long> const&, tensorflow::TensorShape const&, bool, tensorflow::Tensor*)", referenced from:
      tensorflow::StridedSliceOp<Eigen::ThreadPoolDevice, tensorflow::bfloat16>::Compute(tensorflow::OpKernelContext*) in libtensorflow-core-armv7.a(strided_slice_op.o)
  "void tensorflow::HandleStridedSliceCase<Eigen::ThreadPoolDevice, float, 4>(tensorflow::OpKernelContext*, tensorflow::gtl::ArraySlice<long long> const&, tensorflow::gtl::ArraySlice<long long> const&, tensorflow::gtl::ArraySlice<long long> const&, tensorflow::TensorShape const&, bool, tensorflow::Tensor*)", referenced from:
      tensorflow::StridedSliceOp<Eigen::ThreadPoolDevice, float>::Compute(tensorflow::OpKernelContext*) in libtensorflow-core-armv7.a(strided_slice_op.o)
  "void tensorflow::HandleStridedSliceGradCase<Eigen::ThreadPoolDevice, tensorflow::bfloat16, 6>(tensorflow::OpKernelContext*, tensorflow::gtl::ArraySlice<long long> const&, tensorflow::gtl::ArraySlice<long long> const&, tensorflow::gtl::ArraySlice<long long> const&, tensorflow::TensorShape const&, bool, tensorflow::Tensor*)", referenced from:
      tensorflow::StridedSliceGradOp<Eigen::ThreadPoolDevice, tensorflow::bfloat16>::Compute(tensorflow::OpKernelContext*) in libtensorflow-core-armv7.a(strided_slice_op.o)
  "void tensorflow::HandleStridedSliceCase<Eigen::ThreadPoolDevice, tensorflow::bfloat16, 4>(tensorflow::OpKernelContext*, tensorflow::gtl::ArraySlice<long long> const&, tensorflow::gtl::ArraySlice<long long> const&, tensorflow::gtl::ArraySlice<long long> const&, tensorflow::TensorShape const&, bool, tensorflow::Tensor*)", referenced from:
      tensorflow::StridedSliceOp<Eigen::ThreadPoolDevice, tensorflow::bfloat16>::Compute(tensorflow::OpKernelContext*) in libtensorflow-core-armv7.a(strided_slice_op.o)
  "void tensorflow::HandleStridedSliceCase<Eigen::ThreadPoolDevice, float, 5>(tensorflow::OpKernelContext*, tensorflow::gtl::ArraySlice<long long> const&, tensorflow::gtl::ArraySlice<long long> const&, tensorflow::gtl::ArraySlice<long long> const&, tensorflow::TensorShape const&, bool, tensorflow::Tensor*)", referenced from:
      tensorflow::StridedSliceOp<Eigen::ThreadPoolDevice, float>::Compute(tensorflow::OpKernelContext*) in libtensorflow-core-armv7.a(strided_slice_op.o)
  "void tensorflow::HandleStridedSliceGradCase<Eigen::ThreadPoolDevice, int, 1>(tensorflow::OpKernelContext*, tensorflow::gtl::ArraySlice<long long> const&, tensorflow::gtl::ArraySlice<long long> const&, tensorflow::gtl::ArraySlice<long long> const&, tensorflow::TensorShape const&, bool, tensorflow::Tensor*)", referenced from:
      tensorflow::StridedSliceGradOp<Eigen::ThreadPoolDevice, int>::Compute(tensorflow::OpKernelContext*) in libtensorflow-core-armv7.a(strided_slice_op.o)
  "void tensorflow::HandleStridedSliceCase<Eigen::ThreadPoolDevice, float, 6>(tensorflow::OpKernelContext*, tensorflow::gtl::ArraySlice<long long> const&, tensorflow::gtl::ArraySlice<long long> const&, tensorflow::gtl::ArraySlice<long long> const&, tensorflow::TensorShape const&, bool, tensorflow::Tensor*)", referenced from:
      tensorflow::StridedSliceOp<Eigen::ThreadPoolDevice, float>::Compute(tensorflow::OpKernelContext*) in libtensorflow-core-armv7.a(strided_slice_op.o)
  "void tensorflow::HandleStridedSliceGradCase<Eigen::ThreadPoolDevice, int, 2>(tensorflow::OpKernelContext*, tensorflow::gtl::ArraySlice<long long> const&, tensorflow::gtl::ArraySlice<long long> const&, tensorflow::gtl::ArraySlice<long long> const&, tensorflow::TensorShape const&, bool, tensorflow::Tensor*)", referenced from:
      tensorflow::StridedSliceGradOp<Eigen::ThreadPoolDevice, int>::Compute(tensorflow::OpKernelContext*) in libtensorflow-core-armv7.a(strided_slice_op.o)
  "void tensorflow::HandleStridedSliceGradCase<Eigen::ThreadPoolDevice, int, 3>(tensorflow::OpKernelContext*, tensorflow::gtl::ArraySlice<long long> const&, tensorflow::gtl::ArraySlice<long long> const&, tensorflow::gtl::ArraySlice<long long> const&, tensorflow::TensorShape const&, bool, tensorflow::Tensor*)", referenced from:
      tensorflow::StridedSliceGradOp<Eigen::ThreadPoolDevice, int>::Compute(tensorflow::OpKernelContext*) in libtensorflow-core-armv7.a(strided_slice_op.o)
  "void tensorflow::HandleStridedSliceGradCase<Eigen::ThreadPoolDevice, int, 4>(tensorflow::OpKernelContext*, tensorflow::gtl::ArraySlice<long long> const&, tensorflow::gtl::ArraySlice<long long> const&, tensorflow::gtl::ArraySlice<long long> const&, tensorflow::TensorShape const&, bool, tensorflow::Tensor*)", referenced from:
      tensorflow::StridedSliceGradOp<Eigen::ThreadPoolDevice, int>::Compute(tensorflow::OpKernelContext*) in libtensorflow-core-armv7.a(strided_slice_op.o)
  "void tensorflow::HandleStridedSliceGradCase<Eigen::ThreadPoolDevice, int, 5>(tensorflow::OpKernelContext*, tensorflow::gtl::ArraySlice<long long> const&, tensorflow::gtl::ArraySlice<long long> const&, tensorflow::gtl::ArraySlice<long long> const&, tensorflow::TensorShape const&, bool, tensorflow::Tensor*)", referenced from:
      tensorflow::StridedSliceGradOp<Eigen::ThreadPoolDevice, int>::Compute(tensorflow::OpKernelContext*) in libtensorflow-core-armv7.a(strided_slice_op.o)
  "void tensorflow::HandleStridedSliceGradCase<Eigen::ThreadPoolDevice, tensorflow::bfloat16, 3>(tensorflow::OpKernelContext*, tensorflow::gtl::ArraySlice<long long> const&, tensorflow::gtl::ArraySlice<long long> const&, tensorflow::gtl::ArraySlice<long long> const&, tensorflow::TensorShape const&, bool, tensorflow::Tensor*)", referenced from:
      tensorflow::StridedSliceGradOp<Eigen::ThreadPoolDevice, tensorflow::bfloat16>::Compute(tensorflow::OpKernelContext*) in libtensorflow-core-armv7.a(strided_slice_op.o)
  "void tensorflow::HandleStridedSliceCase<Eigen::ThreadPoolDevice, tensorflow::bfloat16, 1>(tensorflow::OpKernelContext*, tensorflow::gtl::ArraySlice<long long> const&, tensorflow::gtl::ArraySlice<long long> const&, tensorflow::gtl::ArraySlice<long long> const&, tensorflow::TensorShape const&, bool, tensorflow::Tensor*)", referenced from:
      tensorflow::StridedSliceOp<Eigen::ThreadPoolDevice, tensorflow::bfloat16>::Compute(tensorflow::OpKernelContext*) in libtensorflow-core-armv7.a(strided_slice_op.o)
  "void tensorflow::HandleStridedSliceCase<Eigen::ThreadPoolDevice, float, 2>(tensorflow::OpKernelContext*, tensorflow::gtl::ArraySlice<long long> const&, tensorflow::gtl::ArraySlice<long long> const&, tensorflow::gtl::ArraySlice<long long> const&, tensorflow::TensorShape const&, bool, tensorflow::Tensor*)", referenced from:
      tensorflow::StridedSliceOp<Eigen::ThreadPoolDevice, float>::Compute(tensorflow::OpKernelContext*) in libtensorflow-core-armv7.a(strided_slice_op.o)
  "void tensorflow::HandleStridedSliceCase<Eigen::ThreadPoolDevice, int, 1>(tensorflow::OpKernelContext*, tensorflow::gtl::ArraySlice<long long> const&, tensorflow::gtl::ArraySlice<long long> const&, tensorflow::gtl::ArraySlice<long long> const&, tensorflow::TensorShape const&, bool, tensorflow::Tensor*)", referenced from:
      tensorflow::StridedSliceOp<Eigen::ThreadPoolDevice, int>::Compute(tensorflow::OpKernelContext*) in libtensorflow-core-armv7.a(strided_slice_op.o)
  "void tensorflow::HandleStridedSliceGradCase<Eigen::ThreadPoolDevice, int, 6>(tensorflow::OpKernelContext*, tensorflow::gtl::ArraySlice<long long> const&, tensorflow::gtl::ArraySlice<long long> const&, tensorflow::gtl::ArraySlice<long long> const&, tensorflow::TensorShape const&, bool, tensorflow::Tensor*)", referenced from:
      tensorflow::StridedSliceGradOp<Eigen::ThreadPoolDevice, int>::Compute(tensorflow::OpKernelContext*) in libtensorflow-core-armv7.a(strided_slice_op.o)
  "void tensorflow::HandleStridedSliceGradCase<Eigen::ThreadPoolDevice, float, 4>(tensorflow::OpKernelContext*, tensorflow::gtl::ArraySlice<long long> const&, tensorflow::gtl::ArraySlice<long long> const&, tensorflow::gtl::ArraySlice<long long> const&, tensorflow::TensorShape const&, bool, tensorflow::Tensor*)", referenced from:
      tensorflow::StridedSliceGradOp<Eigen::ThreadPoolDevice, float>::Compute(tensorflow::OpKernelContext*) in libtensorflow-core-armv7.a(strided_slice_op.o)
  "void tensorflow::HandleStridedSliceCase<Eigen::ThreadPoolDevice, int, 5>(tensorflow::OpKernelContext*, tensorflow::gtl::ArraySlice<long long> const&, tensorflow::gtl::ArraySlice<long long> const&, tensorflow::gtl::ArraySlice<long long> const&, tensorflow::TensorShape const&, bool, tensorflow::Tensor*)", referenced from:
      tensorflow::StridedSliceOp<Eigen::ThreadPoolDevice, int>::Compute(tensorflow::OpKernelContext*) in libtensorflow-core-armv7.a(strided_slice_op.o)
  "void tensorflow::HandleStridedSliceCase<Eigen::ThreadPoolDevice, int, 2>(tensorflow::OpKernelContext*, tensorflow::gtl::ArraySlice<long long> const&, tensorflow::gtl::ArraySlice<long long> const&, tensorflow::gtl::ArraySlice<long long> const&, tensorflow::TensorShape const&, bool, tensorflow::Tensor*)", referenced from:
      tensorflow::StridedSliceOp<Eigen::ThreadPoolDevice, int>::Compute(tensorflow::OpKernelContext*) in libtensorflow-core-armv7.a(strided_slice_op.o)
  "void tensorflow::HandleStridedSliceGradCase<Eigen::ThreadPoolDevice, float, 3>(tensorflow::OpKernelContext*, tensorflow::gtl::ArraySlice<long long> const&, tensorflow::gtl::ArraySlice<long long> const&, tensorflow::gtl::ArraySlice<long long> const&, tensorflow::TensorShape const&, bool, tensorflow::Tensor*)", referenced from:
      tensorflow::StridedSliceGradOp<Eigen::ThreadPoolDevice, float>::Compute(tensorflow::OpKernelContext*) in libtensorflow-core-armv7.a(strided_slice_op.o)
  "void tensorflow::HandleStridedSliceCase<Eigen::ThreadPoolDevice, int, 4>(tensorflow::OpKernelContext*, tensorflow::gtl::ArraySlice<long long> const&, tensorflow::gtl::ArraySlice<long long> const&, tensorflow::gtl::ArraySlice<long long> const&, tensorflow::TensorShape const&, bool, tensorflow::Tensor*)", referenced from:
      tensorflow::StridedSliceOp<Eigen::ThreadPoolDevice, int>::Compute(tensorflow::OpKernelContext*) in libtensorflow-core-armv7.a(strided_slice_op.o)
  "tensorflow::DebugNodeInserter::DebugNodeInserter(google::protobuf::RepeatedPtrField<tensorflow::DebugTensorWatch> const&)", referenced from:
      tensorflow::DirectSession::Run(tensorflow::RunOptions const&, std::__1::vector<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, tensorflow::Tensor>, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, tensorflow::Tensor> > > const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, std::__1::vector<tensorflow::Tensor, std::__1::allocator<tensorflow::Tensor> >*, tensorflow::RunMetadata*) in libtensorflow-core-armv7.a(direct_session.o)
  "void tensorflow::HandleStridedSliceCase<Eigen::ThreadPoolDevice, int, 3>(tensorflow::OpKernelContext*, tensorflow::gtl::ArraySlice<long long> const&, tensorflow::gtl::ArraySlice<long long> const&, tensorflow::gtl::ArraySlice<long long> const&, tensorflow::TensorShape const&, bool, tensorflow::Tensor*)", referenced from:
      tensorflow::StridedSliceOp<Eigen::ThreadPoolDevice, int>::Compute(tensorflow::OpKernelContext*) in libtensorflow-core-armv7.a(strided_slice_op.o)
  "void tensorflow::HandleStridedSliceGradCase<Eigen::ThreadPoolDevice, float, 5>(tensorflow::OpKernelContext*, tensorflow::gtl::ArraySlice<long long> const&, tensorflow::gtl::ArraySlice<long long> const&, tensorflow::gtl::ArraySlice<long long> const&, tensorflow::TensorShape const&, bool, tensorflow::Tensor*)", referenced from:
      tensorflow::StridedSliceGradOp<Eigen::ThreadPoolDevice, float>::Compute(tensorflow::OpKernelContext*) in libtensorflow-core-armv7.a(strided_slice_op.o)
  "void tensorflow::HandleStridedSliceCase<Eigen::ThreadPoolDevice, int, 6>(tensorflow::OpKernelContext*, tensorflow::gtl::ArraySlice<long long> const&, tensorflow::gtl::ArraySlice<long long> const&, tensorflow::gtl::ArraySlice<long long> const&, tensorflow::TensorShape const&, bool, tensorflow::Tensor*)", referenced from:
      tensorflow::StridedSliceOp<Eigen::ThreadPoolDevice, int>::Compute(tensorflow::OpKernelContext*) in libtensorflow-core-armv7.a(strided_slice_op.o)
ld: symbol(s) not found for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [/Users/jsahil/projects/tensorflow/tensorflow-latest/tensorflow/tensorflow/contrib/makefile/gen/bin/benchmark] Error 1
+ '[' 2 -ne 0 ']'
+ echo 'armv7 compilation failed.'
armv7 compilation failed.
+ exit 1

**Comment by sahil912** [comment]
On latest build, I tried to run tensorflow/contrib/makefile/compile_ios_tensorflow.sh


    Undefined symbols for architecture armv7:
      "tensorflow::OptimizationPassRegistry::Global()", referenced from:
      tensorflow::SimpleGraphExecutionState::InitBaseGraph(tensorflow::BuildGraphOptions const&) in libtensorflow-core-armv7.a(simple_graph_execution_state.o)
      tensorflow::SimpleGraphExecutionState::BuildGraph(tensorflow::BuildGraphOptions const&,     std::__1::unique_ptr<tensorflow::SimpleClientGraph, std::__1::default_delete<tensorflow::SimpleClientGraph> >*) in libtensorflow-core-armv7.a(simple_graph_execution_state.o)
      "tensorflow::OptimizationPassRegistry::RunGrouping(tensorflow::OptimizationPassRegistry::Grouping, tensorflow::GraphOptimizationPassOptions const&)", referenced from:
      tensorflow::SimpleGraphExecutionState::InitBaseGraph(tensorflow::BuildGraphOptions const&) in libtensorflow-core-armv7.a(simple_graph_execution_state.o)
      tensorflow::SimpleGraphExecutionState::BuildGraph(tensorflow::BuildGraphOptions const&,   std::__1::unique_ptr<tensorflow::SimpleClientGraph, std::__1::default_delete<tensorflow::SimpleClientGraph> >*) in libtensorflow-core-armv7.a(simple_graph_execution_state.o)
    ld: symbol(s) not found for architecture armv7
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    make: *** [/Users/jsahil/projects/tensorflow/tensorflow-  latest/tensorflow/tensorflow/contrib/makefile/gen/bin/benchmark] Error 1
    armv7 compilation failed.


Thanks

**Comment by sahil912** [comment]
works good after #3382  commit. Thanks
