### ISSUE TITLE
Catnot catch `InvalidArgumentError` exception

### ISSUE THREAD

**Issue by lc0** [tensorflow/tensorflow#33281]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): colab
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): - 
- TensorFlow version (use command below): 1.15 and 2.0
- Python version: 3.6.8
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`
v2.0.0-rc1-51-g2646d23 2.0.0-rc2

**Describe the current behavior**
Exception fails without being able to catch with 
`except tf.errors.InvalidArgumentError as exception:`

**Describe the expected behavior**
I expect, to be able to handle the mentioned example

**Code to reproduce the issue**
https://colab.research.google.com/drive/1IEg-KbY08dnCNnZSiuGb0-jToUDtQ_Vi#scrollTo=Xll7CUHiYn1B

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by lc0** [comment]
I think I was to handle exceptions in such way, unfortunately, I can not find a working solution neither for 1.x neither for 2.0

**Comment by jsimsa** [comment]
Your `decode_jpeg_and_label` Python function is only executed once to build the function graph and `try` and `except` statements will have no effect at that.

The actual execution of the logic happens when `next` is called (as part of `for elem in dataset:`), so if you would like to catch the error you could do the following:

```
dataset = ...
iterator = iter(dataset)
```

while True:
  try:
    elem = next(iterator)
    ...
  except InvalidArgumentError:
    ...
  except OutOfRangeError:
    break
```

**Comment by lc0** [comment]
@jsimsa Thank you for explanation. The only difference, seems like we need to catch `StopIteration` on the last next call

**Comment by jsimsa** [comment]
You are right, I updated my response above to reflect that.
