### ISSUE TITLE
image rotate

### ISSUE THREAD

**Issue by Stick-To** [tensorflow/tensorflow#33287]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using):tensorflow2.0
- Are you willing to contribute it (Yes/No):

**Describe the feature and the current behavior/state.**

**Will this change the current api? How?**

**Who will benefit with this feature?**

**Any Other info.**

rotate an image with a degree as 
tf.contrib.image.rotate  in tensorflow1

**Comment by ravikyram** [comment]
@Stick-To 

Can you please go through the below link and see if it helps you.Thanks!
https://www.tensorflow.org/addons/api_docs/python/tfa/image/rotate

**Comment by Stick-To** [comment]
@ravikyram  Yes, thank you very much
