### ISSUE TITLE
tensorflow 1.14 eigen using failed

### ISSUE THREAD

**Issue by goldbalance** [tensorflow/tensorflow#33280]
tensorflow version:1.14
tensorflow lib compile ok, but i use c api to embed into my app, make build error below:

In file included from _external/usr/local/include/tensorflow/unsupported/Eigen/CXX11/Tensor:120:0,
                 from _external/usr/local/include/tensorflow/third_party/eigen3/unsupported/Eigen/CXX11/Tensor:1,
                 from _external/usr/local/include/tensorflow/tensorflow/core/framework/tensor.h:21,
                 from _external/usr/local/include/tensorflow/tensorflow/core/public/session.h:24,
                 from _external/usr/local/include/tensorflow/tensorflow/cc/saved_model/loader.h:26,
                 from ./apps/frame/util/tensorflow_util.h:7,
                 from build/release64/apps/frame/data_loader/tensorflow_loader.h:5,
                 from build/release64/apps/frame/data_loader/ServiceDataLoaderFactory.cpp:5:
_external/usr/local/include/tensorflow/unsupported/Eigen/CXX11/src/Tensor/TensorBlock.h: In static member function 'static void Eigen::internal::TensorBlockIO<Scalar, StorageIndex, NumDims, Layout, BlockRead>::Copy(const Block&, StorageIndex, const Dimensions&, const Dimensions&, const Scalar*, Scalar*)':
_external/usr/local/include/tensorflow/unsupported/Eigen/CXX11/src/Tensor/TensorBlock.h:393:63: error: the value of 'j' is not usable in a constant expression
         if (++block_iter_state[j].count < block_iter_state[j].size) {
                                                               ^
_external/usr/local/include/tensorflow/unsupported/Eigen/CXX11/src/Tensor/TensorBlock.h:392:16: note: 'int j' is not const
       for (int j = 0; j < num_squeezed_dims; ++j) {
                ^
_external/usr/local/include/tensorflow/unsupported/Eigen/CXX11/src/Tensor/TensorBlock.h:393:35: error: parse error in template argument list
         if (++block_iter_state[j].count < block_iter_state[j].size) {
                                   ^
_external/usr/local/include/tensorflow/unsupported/Eigen/CXX11/src/Tensor/TensorBlock.h: In static member function 'static void Eigen::internal::TensorBlockCwiseUnaryIO<UnaryFunctor, StorageIndex, OutputScalar, NumDims, Layout>::Run(const UnaryFunctor&, const Dimensions&, const Dimensions&, OutputScalar*, Eigen::array<StorageIndex, NumDims>&, const InputScalar*)':
_external/usr/local/include/tensorflow/unsupported/Eigen/CXX11/src/Tensor/TensorBlock.h:604:21: error: parse error in template argument list
         if (++state.count < state.size) {
                     ^
_external/usr/local/include/tensorflow/unsupported/Eigen/CXX11/src/Tensor/TensorBlock.h: In static member function 'static void Eigen::internal::TensorBlockCwiseBinaryIO<BinaryFunctor, StorageIndex, OutputScalar, NumDims, Layout>::Run(const BinaryFunctor&, const Dimensions&, const Dimensions&, OutputScalar*, Eigen::array<StorageIndex, NumDims>&, const LeftScalar*, Eigen::array<StorageIndex, NumDims>&, const RightScalar*)':
_external/usr/local/include/tensorflow/unsupported/Eigen/CXX11/src/Tensor/TensorBlock.h:758:21: error: parse error in template argument list
         if (++state.count < state.size) {

I try to replace it with 3.3.7 eigen, but tensorflow code is confict with 3.3.7 eigen.
Please help me!

**Comment by ravikyram** [comment]
Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version. Also, did you compile from source or install a binary?

Make sure you also include the exact command if possible to produce the output included in your test case. If you are unclear what to include see the issue template displayed in [the Github new issue template](https://github.com/tensorflow/tensorflow/issues/new/choose).

We ask for this in the issue submission template, because it is really difficult to help without that information. Thanks!

**Comment by goldbalance** [comment]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): RHEL
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): source
- TensorFlow version: 1.14
- Python version: 2.7
- Installed using virtualenv? pip? conda?: pip
- Bazel version (if compiling from source): 0.25.0
- GCC/Compiler version (if compiling from source): 4.8.5
- CUDA/cuDNN version:
- GPU model and memory:

**Describe the problem**

`
In file included from _external/usr/local/include/tensorflow/unsupported/Eigen/CXX11/Tensor:120:0,
from _external/usr/local/include/tensorflow/third_party/eigen3/unsupported/Eigen/CXX11/Tensor:1,
from _external/usr/local/include/tensorflow/tensorflow/core/framework/tensor.h:21,
from _external/usr/local/include/tensorflow/tensorflow/core/public/session.h:24,
from _external/usr/local/include/tensorflow/tensorflow/cc/saved_model/loader.h:26,
from ./apps/frame/util/tensorflow_util.h:7,
from build/release64/apps/frame/data_loader/tensorflow_loader.h:5,
from build/release64/apps/frame/data_loader/ServiceDataLoaderFactory.cpp:5:
_external/usr/local/include/tensorflow/unsupported/Eigen/CXX11/src/Tensor/TensorBlock.h: In static member function 'static void Eigen::internal::TensorBlockIO<Scalar, StorageIndex, NumDims, Layout, BlockRead>::Copy(const Block&, StorageIndex, const Dimensions&, const Dimensions&, const Scalar*, Scalar*)':
_external/usr/local/include/tensorflow/unsupported/Eigen/CXX11/src/Tensor/TensorBlock.h:393:63: error: the value of 'j' is not usable in a constant expression
if (++block_iter_state[j].count < block_iter_state[j].size) {
^
_external/usr/local/include/tensorflow/unsupported/Eigen/CXX11/src/Tensor/TensorBlock.h:392:16: note: 'int j' is not const
for (int j = 0; j < num_squeezed_dims; ++j) {
^
_external/usr/local/include/tensorflow/unsupported/Eigen/CXX11/src/Tensor/TensorBlock.h:393:35: error: parse error in template argument list
if (++block_iter_state[j].count < block_iter_state[j].size) {
^
_external/usr/local/include/tensorflow/unsupported/Eigen/CXX11/src/Tensor/TensorBlock.h: In static member function 'static void Eigen::internal::TensorBlockCwiseUnaryIO<UnaryFunctor, StorageIndex, OutputScalar, NumDims, Layout>::Run(const UnaryFunctor&, const Dimensions&, const Dimensions&, OutputScalar*, Eigen::array<StorageIndex, NumDims>&, const InputScalar*)':
_external/usr/local/include/tensorflow/unsupported/Eigen/CXX11/src/Tensor/TensorBlock.h:604:21: error: parse error in template argument list
if (++state.count < state.size) {
^
_external/usr/local/include/tensorflow/unsupported/Eigen/CXX11/src/Tensor/TensorBlock.h: In static member function 'static void Eigen::internal::TensorBlockCwiseBinaryIO<BinaryFunctor, StorageIndex, OutputScalar, NumDims, Layout>::Run(const BinaryFunctor&, const Dimensions&, const Dimensions&, OutputScalar*, Eigen::array<StorageIndex, NumDims>&, const LeftScalar*, Eigen::array<StorageIndex, NumDims>&, const RightScalar*)':
_external/usr/local/include/tensorflow/unsupported/Eigen/CXX11/src/Tensor/TensorBlock.h:758:21: error: parse error in template argument list
if (++state.count < state.size) {`

**Provide the exact sequence of commands / steps that you executed before running into the problem**

tensorflow lib compile ok, but i use c api to embed into my app, make build error above.
I try to replace it with 3.3.7 eigen, but tensorflow code is confict with 3.3.7 eigen.

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by goldbalance** [comment]
> Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version. Also, did you compile from source or install a binary?
> 
> Make sure you also include the exact command if possible to produce the output included in your test case. If you are unclear what to include see the issue template displayed in [the Github new issue template](https://github.com/tensorflow/tensorflow/issues/new/choose).
> 
> We ask for this in the issue submission template, because it is really difficult to help without that information. Thanks!

<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): RHEL
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): source
- TensorFlow version: 1.14
- Python version: 2.7
- Installed using virtualenv? pip? conda?: pip
- Bazel version (if compiling from source): 0.25.0
- GCC/Compiler version (if compiling from source): 4.8.5
- CUDA/cuDNN version:
- GPU model and memory:

**Describe the problem**

`
In file included from _external/usr/local/include/tensorflow/unsupported/Eigen/CXX11/Tensor:120:0,
from _external/usr/local/include/tensorflow/third_party/eigen3/unsupported/Eigen/CXX11/Tensor:1,
from _external/usr/local/include/tensorflow/tensorflow/core/framework/tensor.h:21,
from _external/usr/local/include/tensorflow/tensorflow/core/public/session.h:24,
from _external/usr/local/include/tensorflow/tensorflow/cc/saved_model/loader.h:26,
from ./apps/frame/util/tensorflow_util.h:7,
from build/release64/apps/frame/data_loader/tensorflow_loader.h:5,
from build/release64/apps/frame/data_loader/ServiceDataLoaderFactory.cpp:5:
_external/usr/local/include/tensorflow/unsupported/Eigen/CXX11/src/Tensor/TensorBlock.h: In static member function 'static void Eigen::internal::TensorBlockIO<Scalar, StorageIndex, NumDims, Layout, BlockRead>::Copy(const Block&, StorageIndex, const Dimensions&, const Dimensions&, const Scalar*, Scalar*)':
_external/usr/local/include/tensorflow/unsupported/Eigen/CXX11/src/Tensor/TensorBlock.h:393:63: error: the value of 'j' is not usable in a constant expression
if (++block_iter_state[j].count < block_iter_state[j].size) {
^
_external/usr/local/include/tensorflow/unsupported/Eigen/CXX11/src/Tensor/TensorBlock.h:392:16: note: 'int j' is not const
for (int j = 0; j < num_squeezed_dims; ++j) {
^
_external/usr/local/include/tensorflow/unsupported/Eigen/CXX11/src/Tensor/TensorBlock.h:393:35: error: parse error in template argument list
if (++block_iter_state[j].count < block_iter_state[j].size) {
^
_external/usr/local/include/tensorflow/unsupported/Eigen/CXX11/src/Tensor/TensorBlock.h: In static member function 'static void Eigen::internal::TensorBlockCwiseUnaryIO<UnaryFunctor, StorageIndex, OutputScalar, NumDims, Layout>::Run(const UnaryFunctor&, const Dimensions&, const Dimensions&, OutputScalar*, Eigen::array<StorageIndex, NumDims>&, const InputScalar*)':
_external/usr/local/include/tensorflow/unsupported/Eigen/CXX11/src/Tensor/TensorBlock.h:604:21: error: parse error in template argument list
if (++state.count < state.size) {
^
_external/usr/local/include/tensorflow/unsupported/Eigen/CXX11/src/Tensor/TensorBlock.h: In static member function 'static void Eigen::internal::TensorBlockCwiseBinaryIO<BinaryFunctor, StorageIndex, OutputScalar, NumDims, Layout>::Run(const BinaryFunctor&, const Dimensions&, const Dimensions&, OutputScalar*, Eigen::array<StorageIndex, NumDims>&, const LeftScalar*, Eigen::array<StorageIndex, NumDims>&, const RightScalar*)':
_external/usr/local/include/tensorflow/unsupported/Eigen/CXX11/src/Tensor/TensorBlock.h:758:21: error: parse error in template argument list
if (++state.count < state.size) {`

**Provide the exact sequence of commands / steps that you executed before running into the problem**

tensorflow lib compile ok, but i use tensorflow sdk to embed into my app, make build error above.
I try to replace it with 3.3.7 eigen, but tensorflow code is confict with 3.3.7 eigen.

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.
[kai.ren_tensorflow_sdk.tar.gz](https://github.com/tensorflow/tensorflow/files/3724714/kai.ren_tensorflow_sdk.tar.gz)

**Comment by ravikyram** [comment]
@goldbalance 
Thanks for the platform details.Please, provide the exact sequence of commands / steps that you executed before running into the problem.Thanks!

**Comment by goldbalance** [comment]
em, i will give you a demo with tensorflow_sdk

**Comment by jdduke** [comment]
There's nothing we can do for 1.14, are you able to repro with the latest master build? If not, what about 1.15 or the upcoming 2.1 release?

**Comment by ymodak** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Comment by surak** [comment]
> There's nothing we can do for 1.14, are you able to repro with the latest master build? If not, what about 1.15 or the upcoming 2.1 release?

This is the same with 1.15.3
