### ISSUE TITLE
Multiple builds of zlib library

### ISSUE THREAD

**Issue by butterfly-coder** [tensorflow/tensorflow#33288]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution:Linux Ubuntu 18.04.1 LTS
- TensorFlow installed from (source or binary):Source
- TensorFlow version:1.15
- Python version:3.7
- Installed using virtualenv? pip? conda?:build with bazel
- Bazel version (if compiling from source):0.26.1
- GCC/Compiler version (if compiling from source):7.4.0

**Describe the problem**
I'm trying to build tensorflow from source with bazel.
But I faced errors like follow.
**Provide the exact sequence of commands / steps that you executed before running into the problem**
Command : bazel build --define=grpc-no-ares=true --config=opt //tensorflow/tools/pip_package:build_pip_package

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

ERROR: /home/butterfly/tf/tensorflow/tensorflow/BUILD:563:1: Linking of rule '//tensorflow:libtensorflow_framework.so.1.15.0' failed (Exit 1)
/usr/bin/ld.gold: error: bazel-out/host/bin/external/zlib_archive/_objs/zlib/adler32.pic.o: multiple definition of 'adler32'
/usr/bin/ld.gold: bazel-out/host/bin/external/zlib/_objs/zlib/adler32.pic.o: previous definition here
/usr/bin/ld.gold: error: bazel-out/host/bin/external/zlib_archive/_objs/zlib/adler32.pic.o: multiple definition of 'adler32_combine'
/usr/bin/ld.gold: bazel-out/host/bin/external/zlib/_objs/zlib/adler32.pic.o: previous definition here
/usr/bin/ld.gold: error: bazel-out/host/bin/external/zlib_archive/_objs/zlib/adler32.pic.o: multiple definition of 'adler32_combine64'
/usr/bin/ld.gold: bazel-out/host/bin/external/zlib/_objs/zlib/adler32.pic.o: previous definition here
/usr/bin/ld.gold: error: bazel-out/host/bin/external/zlib_archive/_objs/zlib/adler32.pic.o: multiple definition of 'adler32_z'
/usr/bin/ld.gold: bazel-out/host/bin/external/zlib/_objs/zlib/adler32.pic.o: previous definition here
/usr/bin/ld.gold: error: bazel-out/host/bin/external/zlib_archive/_objs/zlib/compress.pic.o: multiple definition of 'compress'
/usr/bin/ld.gold: bazel-out/host/bin/external/zlib/_objs/zlib/compress.pic.o: previous definition here
/usr/bin/ld.gold: error: bazel-out/host/bin/external/zlib_archive/_objs/zlib/compress.pic.o: multiple definition of 'compress2'
/usr/bin/ld.gold: bazel-out/host/bin/external/zlib/_objs/zlib/compress.pic.o: previous definition here
/usr/bin/ld.gold: error: bazel-out/host/bin/external/zlib_archive/_objs/zlib/compress.pic.o: multiple definition of 'compressBound'
/usr/bin/ld.gold: bazel-out/host/bin/external/zlib/_objs/zlib/compress.pic.o: previous definition here
/usr/bin/ld.gold: error: bazel-out/host/bin/external/zlib_archive/_objs/zlib/crc32.pic.o: multiple definition of 'crc32'
/usr/bin/ld.gold: bazel-out/host/bin/external/zlib/_objs/zlib/crc32.pic.o: previous definition here
/usr/bin/ld.gold: error: bazel-out/host/bin/external/zlib_archive/_objs/zlib/crc32.pic.o: multiple definition of 'crc32_combine'
/usr/bin/ld.gold: bazel-out/host/bin/external/zlib/_objs/zlib/crc32.pic.o: previous definition here
/usr/bin/ld.gold: error: bazel-out/host/bin/external/zlib_archive/_objs/zlib/crc32.pic.o: multiple definition of 'crc32_combine64'
/usr/bin/ld.gold: bazel-out/host/bin/external/zlib/_objs/zlib/crc32.pic.o: previous definition here
/usr/bin/ld.gold: error: bazel-out/host/bin/external/zlib_archive/_objs/zlib/crc32.pic.o: multiple definition of 'crc32_z'
/usr/bin/ld.gold: bazel-out/host/bin/external/zlib/_objs/zlib/crc32.pic.o: previous definition here
/usr/bin/ld.gold: error: bazel-out/host/bin/external/zlib_archive/_objs/zlib/crc32.pic.o: multiple definition of 'get_crc_table'
/usr/bin/ld.gold: bazel-out/host/bin/external/zlib/_objs/zlib/crc32.pic.o: previous definition here
/usr/bin/ld.gold: error: bazel-out/host/bin/external/zlib_archive/_objs/zlib/deflate.pic.o: multiple definition of 'deflate'
/usr/bin/ld.gold: bazel-out/host/bin/external/zlib/_objs/zlib/deflate.pic.o: previous definition here
/usr/bin/ld.gold: error: bazel-out/host/bin/external/zlib_archive/_objs/zlib/deflate.pic.o: multiple definition of 'deflateBound'
/usr/bin/ld.gold: bazel-out/host/bin/external/zlib/_objs/zlib/deflate.pic.o: previous definition here
/usr/bin/ld.gold: error: bazel-out/host/bin/external/zlib_archive/_objs/zlib/deflate.pic.o: multiple definition of 'deflateCopy'
/usr/bin/ld.gold: bazel-out/host/bin/external/zlib/_objs/zlib/deflate.pic.o: previous definition here
/usr/bin/ld.gold: error: bazel-out/host/bin/external/zlib_archive/_objs/zlib/deflate.pic.o: multiple definition of 'deflateEnd'
/usr/bin/ld.gold: bazel-out/host/bin/external/zlib/_objs/zlib/deflate.pic.o: previous definition here
/usr/bin/ld.gold: error: bazel-out/host/bin/external/zlib_archive/_objs/zlib/deflate.pic.o: multiple definition of 'deflateGetDictionary'
/usr/bin/ld.gold: bazel-out/host/bin/external/zlib/_objs/zlib/deflate.pic.o: previous definition here
/usr/bin/ld.gold: error: bazel-out/host/bin/external/zlib_archive/_objs/zlib/deflate.pic.o: multiple definition of 'deflateInit2_'
/usr/bin/ld.gold: bazel-out/host/bin/external/zlib/_objs/zlib/deflate.pic.o: previous definition here
/usr/bin/ld.gold: error: bazel-out/host/bin/external/zlib_archive/_objs/zlib/deflate.pic.o: multiple definition of 'deflateInit_'
/usr/bin/ld.gold: bazel-out/host/bin/external/zlib/_objs/zlib/deflate.pic.o: previous definition here
/usr/bin/ld.gold: error: bazel-out/host/bin/external/zlib_archive/_objs/zlib/deflate.pic.o: multiple definition of 'deflateParams'
/usr/bin/ld.gold: bazel-out/host/bin/external/zlib/_objs/zlib/deflate.pic.o: previous definition here
/usr/bin/ld.gold: error: bazel-out/host/bin/external/zlib_archive/_objs/zlib/deflate.pic.o: multiple definition of 'deflatePending'
/usr/bin/ld.gold: bazel-out/host/bin/external/zlib/_objs/zlib/deflate.pic.o: previous definition here
/usr/bin/ld.gold: error: bazel-out/host/bin/external/zlib_archive/_objs/zlib/deflate.pic.o: multiple definition of 'deflatePrime'
/usr/bin/ld.gold: bazel-out/host/bin/external/zlib/_objs/zlib/deflate.pic.o: previous definition here
/usr/bin/ld.gold: error: bazel-out/host/bin/external/zlib_archive/_objs/zlib/deflate.pic.o: multiple definition of 'deflateReset'
/usr/bin/ld.gold: bazel-out/host/bin/external/zlib/_objs/zlib/deflate.pic.o: previous definition here
/usr/bin/ld.gold: error: bazel-out/host/bin/external/zlib_archive/_objs/zlib/deflate.pic.o: multiple definition of 'deflateResetKeep'
/usr/bin/ld.gold: bazel-out/host/bin/external/zlib/_objs/zlib/deflate.pic.o: previous definition here
/usr/bin/ld.gold: error: bazel-out/host/bin/external/zlib_archive/_objs/zlib/deflate.pic.o: multiple definition of 'deflateSetDictionary'
/usr/bin/ld.gold: bazel-out/host/bin/external/zlib/_objs/zlib/deflate.pic.o: previous definition here
/usr/bin/ld.gold: error: bazel-out/host/bin/external/zlib_archive/_objs/zlib/deflate.pic.o: multiple definition of 'deflateSetHeader'
/usr/bin/ld.gold: bazel-out/host/bin/external/zlib/_objs/zlib/deflate.pic.o: previous definition here
/usr/bin/ld.gold: error: bazel-out/host/bin/external/zlib_archive/_objs/zlib/deflate.pic.o: multiple definition of 'deflateTune'
/usr/bin/ld.gold: bazel-out/host/bin/external/zlib/_objs/zlib/deflate.pic.o: previous definition here
/usr/bin/ld.gold: error: bazel-out/host/bin/external/zlib_archive/_objs/zlib/deflate.pic.o: multiple definition of 'deflate_copyright'
/usr/bin/ld.gold: bazel-out/host/bin/external/zlib/_objs/zlib/deflate.pic.o: previous definition here
/usr/bin/ld.gold: error: bazel-out/host/bin/external/zlib_archive/_objs/zlib/gzclose.pic.o: multiple definition of 'gzclose'
/usr/bin/ld.gold: bazel-out/host/bin/external/zlib/_objs/zlib/gzclose.pic.o: previous definition here
/usr/bin/ld.gold: error: bazel-out/host/bin/external/zlib_archive/_objs/zlib/gzlib.pic.o: multiple definition of 'gz_error'
/usr/bin/ld.gold: bazel-out/host/bin/external/zlib/_objs/zlib/gzlib.pic.o: previous definition here
/usr/bin/ld.gold: error: bazel-out/host/bin/external/zlib_archive/_objs/zlib/gzlib.pic.o: multiple definition of 'gzbuffer'
/usr/bin/ld.gold: bazel-out/host/bin/external/zlib/_objs/zlib/gzlib.pic.o: previous definition here
/usr/bin/ld.gold: error: bazel-out/host/bin/external/zlib_archive/_objs/zlib/gzlib.pic.o: multiple definition of 'gzclearerr'
/usr/bin/ld.gold: bazel-out/host/bin/external/zlib/_objs/zlib/gzlib.pic.o: previous definition here
/usr/bin/ld.gold: error: bazel-out/host/bin/external/zlib_archive/_objs/zlib/gzlib.pic.o: multiple definition of 'gzdopen'
/usr/bin/ld.gold: bazel-out/host/bin/external/zlib/_objs/zlib/gzlib.pic.o: previous definition here
/usr/bin/ld.gold: error: bazel-out/host/bin/external/zlib_archive/_objs/zlib/gzlib.pic.o: multiple definition of 'gzeof'
/usr/bin/ld.gold: bazel-out/host/bin/external/zlib/_objs/zlib/gzlib.pic.o: previous definition here
/usr/bin/ld.gold: error: bazel-out/host/bin/external/zlib_archive/_objs/zlib/gzlib.pic.o: multiple definition of 'gzerror'
/usr/bin/ld.gold: bazel-out/host/bin/external/zlib/_objs/zlib/gzlib.pic.o: previous definition here
/usr/bin/ld.gold: error: bazel-out/host/bin/external/zlib_archive/_objs/zlib/gzlib.pic.o: multiple definition of 'gzoffset'
/usr/bin/ld.gold: bazel-out/host/bin/external/zlib/_objs/zlib/gzlib.pic.o: previous definition here
/usr/bin/ld.gold: error: bazel-out/host/bin/external/zlib_archive/_objs/zlib/gzlib.pic.o: multiple definition of 'gzoffset64'
/usr/bin/ld.gold: bazel-out/host/bin/external/zlib/_objs/zlib/gzlib.pic.o: previous definition here
/usr/bin/ld.gold: error: bazel-out/host/bin/external/zlib_archive/_objs/zlib/gzlib.pic.o: multiple definition of 'gzopen'
/usr/bin/ld.gold: bazel-out/host/bin/external/zlib/_objs/zlib/gzlib.pic.o: previous definition here
/usr/bin/ld.gold: error: bazel-out/host/bin/external/zlib_archive/_objs/zlib/gzlib.pic.o: multiple definition of 'gzopen64'
/usr/bin/ld.gold: bazel-out/host/bin/external/zlib/_objs/zlib/gzlib.pic.o: previous definition here
/usr/bin/ld.gold: error: bazel-out/host/bin/external/zlib_archive/_objs/zlib/gzlib.pic.o: multiple definition of 'gzrewind'
/usr/bin/ld.gold: bazel-out/host/bin/external/zlib/_objs/zlib/gzlib.pic.o: previous definition here
/usr/bin/ld.gold: error: bazel-out/host/bin/external/zlib_archive/_objs/zlib/gzlib.pic.o: multiple definition of 'gzseek'
/usr/bin/ld.gold: bazel-out/host/bin/external/zlib/_objs/zlib/gzlib.pic.o: previous definition here
/usr/bin/ld.gold: error: bazel-out/host/bin/external/zlib_archive/_objs/zlib/gzlib.pic.o: multiple definition of 'gzseek64'
/usr/bin/ld.gold: bazel-out/host/bin/external/zlib/_objs/zlib/gzlib.pic.o: previous definition here
/usr/bin/ld.gold: error: bazel-out/host/bin/external/zlib_archive/_objs/zlib/gzlib.pic.o: multiple definition of 'gztell'
/usr/bin/ld.gold: bazel-out/host/bin/external/zlib/_objs/zlib/gzlib.pic.o: previous definition here
/usr/bin/ld.gold: error: bazel-out/host/bin/external/zlib_archive/_objs/zlib/gzlib.pic.o: multiple definition of 'gztell64'
/usr/bin/ld.gold: bazel-out/host/bin/external/zlib/_objs/zlib/gzlib.pic.o: previous definition here
/usr/bin/ld.gold: error: bazel-out/host/bin/external/zlib_archive/_objs/zlib/gzread.pic.o: multiple definition of 'gzclose_r'
/usr/bin/ld.gold: bazel-out/host/bin/external/zlib/_objs/zlib/gzread.pic.o: previous definition here
/usr/bin/ld.gold: error: bazel-out/host/bin/external/zlib_archive/_objs/zlib/gzread.pic.o: multiple definition of 'gzdirect'
/usr/bin/ld.gold: bazel-out/host/bin/external/zlib/_objs/zlib/gzread.pic.o: previous definition here
/usr/bin/ld.gold: error: bazel-out/host/bin/external/zlib_archive/_objs/zlib/gzread.pic.o: multiple definition of 'gzfread'
/usr/bin/ld.gold: bazel-out/host/bin/external/zlib/_objs/zlib/gzread.pic.o: previous definition here
/usr/bin/ld.gold: error: bazel-out/host/bin/external/zlib_archive/_objs/zlib/gzread.pic.o: multiple definition of 'gzgetc'
/usr/bin/ld.gold: bazel-out/host/bin/external/zlib/_objs/zlib/gzread.pic.o: previous definition here
/usr/bin/ld.gold: error: bazel-out/host/bin/external/zlib_archive/_objs/zlib/gzread.pic.o: multiple definition of 'gzgetc_'
/usr/bin/ld.gold: bazel-out/host/bin/external/zlib/_objs/zlib/gzread.pic.o: previous definition here
/usr/bin/ld.gold: error: bazel-out/host/bin/external/zlib_archive/_objs/zlib/gzread.pic.o: multiple definition of 'gzgets'
/usr/bin/ld.gold: bazel-out/host/bin/external/zlib/_objs/zlib/gzread.pic.o: previous definition here
/usr/bin/ld.gold: error: bazel-out/host/bin/external/zlib_archive/_objs/zlib/gzread.pic.o: multiple definition of 'gzread'
/usr/bin/ld.gold: bazel-out/host/bin/external/zlib/_objs/zlib/gzread.pic.o: previous definition here
/usr/bin/ld.gold: error: bazel-out/host/bin/external/zlib_archive/_objs/zlib/gzread.pic.o: multiple definition of 'gzungetc'
/usr/bin/ld.gold: bazel-out/host/bin/external/zlib/_objs/zlib/gzread.pic.o: previous definition here
/usr/bin/ld.gold: error: bazel-out/host/bin/external/zlib_archive/_objs/zlib/gzwrite.pic.o: multiple definition of 'gzclose_w'
/usr/bin/ld.gold: bazel-out/host/bin/external/zlib/_objs/zlib/gzwrite.pic.o: previous definition here
/usr/bin/ld.gold: error: bazel-out/host/bin/external/zlib_archive/_objs/zlib/gzwrite.pic.o: multiple definition of 'gzflush'
/usr/bin/ld.gold: bazel-out/host/bin/external/zlib/_objs/zlib/gzwrite.pic.o: previous definition here
/usr/bin/ld.gold: error: bazel-out/host/bin/external/zlib_archive/_objs/zlib/gzwrite.pic.o: multiple definition of 'gzfwrite'
/usr/bin/ld.gold: bazel-out/host/bin/external/zlib/_objs/zlib/gzwrite.pic.o: previous definition here
/usr/bin/ld.gold: error: bazel-out/host/bin/external/zlib_archive/_objs/zlib/gzwrite.pic.o: multiple definition of 'gzprintf'
/usr/bin/ld.gold: bazel-out/host/bin/external/zlib/_objs/zlib/gzwrite.pic.o: previous definition here
/usr/bin/ld.gold: error: bazel-out/host/bin/external/zlib_archive/_objs/zlib/gzwrite.pic.o: multiple definition of 'gzputc'
/usr/bin/ld.gold: bazel-out/host/bin/external/zlib/_objs/zlib/gzwrite.pic.o: previous definition here
/usr/bin/ld.gold: error: bazel-out/host/bin/external/zlib_archive/_objs/zlib/gzwrite.pic.o: multiple definition of 'gzputs'
/usr/bin/ld.gold: bazel-out/host/bin/external/zlib/_objs/zlib/gzwrite.pic.o: previous definition here
/usr/bin/ld.gold: error: bazel-out/host/bin/external/zlib_archive/_objs/zlib/gzwrite.pic.o: multiple definition of 'gzsetparams'
/usr/bin/ld.gold: bazel-out/host/bin/external/zlib/_objs/zlib/gzwrite.pic.o: previous definition here
/usr/bin/ld.gold: error: bazel-out/host/bin/external/zlib_archive/_objs/zlib/gzwrite.pic.o: multiple definition of 'gzvprintf'
/usr/bin/ld.gold: bazel-out/host/bin/external/zlib/_objs/zlib/gzwrite.pic.o: previous definition here
/usr/bin/ld.gold: error: bazel-out/host/bin/external/zlib_archive/_objs/zlib/gzwrite.pic.o: multiple definition of 'gzwrite'
/usr/bin/ld.gold: bazel-out/host/bin/external/zlib/_objs/zlib/gzwrite.pic.o: previous definition here
/usr/bin/ld.gold: error: bazel-out/host/bin/external/zlib_archive/_objs/zlib/infback.pic.o: multiple definition of 'inflateBack'
/usr/bin/ld.gold: bazel-out/host/bin/external/zlib/_objs/zlib/infback.pic.o: previous definition here
/usr/bin/ld.gold: error: bazel-out/host/bin/external/zlib_archive/_objs/zlib/infback.pic.o: multiple definition of 'inflateBackEnd'
/usr/bin/ld.gold: bazel-out/host/bin/external/zlib/_objs/zlib/infback.pic.o: previous definition here
/usr/bin/ld.gold: error: bazel-out/host/bin/external/zlib_archive/_objs/zlib/infback.pic.o: multiple definition of 'inflateBackInit_'
/usr/bin/ld.gold: bazel-out/host/bin/external/zlib/_objs/zlib/infback.pic.o: previous definition here
/usr/bin/ld.gold: error: bazel-out/host/bin/external/zlib_archive/_objs/zlib/inffast.pic.o: multiple definition of 'inflate_fast'
/usr/bin/ld.gold: bazel-out/host/bin/external/zlib/_objs/zlib/inffast.pic.o: previous definition here
/usr/bin/ld.gold: error: bazel-out/host/bin/external/zlib_archive/_objs/zlib/inflate.pic.o: multiple definition of 'inflate'
/usr/bin/ld.gold: bazel-out/host/bin/external/zlib/_objs/zlib/inflate.pic.o: previous definition here
/usr/bin/ld.gold: error: bazel-out/host/bin/external/zlib_archive/_objs/zlib/inflate.pic.o: multiple definition of 'inflateCodesUsed'
/usr/bin/ld.gold: bazel-out/host/bin/external/zlib/_objs/zlib/inflate.pic.o: previous definition here
/usr/bin/ld.gold: error: bazel-out/host/bin/external/zlib_archive/_objs/zlib/inflate.pic.o: multiple definition of 'inflateCopy'
/usr/bin/ld.gold: bazel-out/host/bin/external/zlib/_objs/zlib/inflate.pic.o: previous definition here
/usr/bin/ld.gold: error: bazel-out/host/bin/external/zlib_archive/_objs/zlib/inflate.pic.o: multiple definition of 'inflateEnd'
/usr/bin/ld.gold: bazel-out/host/bin/external/zlib/_objs/zlib/inflate.pic.o: previous definition here
/usr/bin/ld.gold: error: bazel-out/host/bin/external/zlib_archive/_objs/zlib/inflate.pic.o: multiple definition of 'inflateGetDictionary'
/usr/bin/ld.gold: bazel-out/host/bin/external/zlib/_objs/zlib/inflate.pic.o: previous definition here
/usr/bin/ld.gold: error: bazel-out/host/bin/external/zlib_archive/_objs/zlib/inflate.pic.o: multiple definition of 'inflateGetHeader'
/usr/bin/ld.gold: bazel-out/host/bin/external/zlib/_objs/zlib/inflate.pic.o: previous definition here
/usr/bin/ld.gold: error: bazel-out/host/bin/external/zlib_archive/_objs/zlib/inflate.pic.o: multiple definition of 'inflateInit2_'
/usr/bin/ld.gold: bazel-out/host/bin/external/zlib/_objs/zlib/inflate.pic.o: previous definition here
/usr/bin/ld.gold: error: bazel-out/host/bin/external/zlib_archive/_objs/zlib/inflate.pic.o: multiple definition of 'inflateInit_'
/usr/bin/ld.gold: bazel-out/host/bin/external/zlib/_objs/zlib/inflate.pic.o: previous definition here
/usr/bin/ld.gold: error: bazel-out/host/bin/external/zlib_archive/_objs/zlib/inflate.pic.o: multiple definition of 'inflateMark'
/usr/bin/ld.gold: bazel-out/host/bin/external/zlib/_objs/zlib/inflate.pic.o: previous definition here
/usr/bin/ld.gold: error: bazel-out/host/bin/external/zlib_archive/_objs/zlib/inflate.pic.o: multiple definition of 'inflatePrime'
/usr/bin/ld.gold: bazel-out/host/bin/external/zlib/_objs/zlib/inflate.pic.o: previous definition here
/usr/bin/ld.gold: error: bazel-out/host/bin/external/zlib_archive/_objs/zlib/inflate.pic.o: multiple definition of 'inflateReset'
/usr/bin/ld.gold: bazel-out/host/bin/external/zlib/_objs/zlib/inflate.pic.o: previous definition here
/usr/bin/ld.gold: error: bazel-out/host/bin/external/zlib_archive/_objs/zlib/inflate.pic.o: multiple definition of 'inflateReset2'
/usr/bin/ld.gold: bazel-out/host/bin/external/zlib/_objs/zlib/inflate.pic.o: previous definition here
/usr/bin/ld.gold: error: bazel-out/host/bin/external/zlib_archive/_objs/zlib/inflate.pic.o: multiple definition of 'inflateResetKeep'
/usr/bin/ld.gold: bazel-out/host/bin/external/zlib/_objs/zlib/inflate.pic.o: previous definition here
/usr/bin/ld.gold: error: bazel-out/host/bin/external/zlib_archive/_objs/zlib/inflate.pic.o: multiple definition of 'inflateSetDictionary'
/usr/bin/ld.gold: bazel-out/host/bin/external/zlib/_objs/zlib/inflate.pic.o: previous definition here
/usr/bin/ld.gold: error: bazel-out/host/bin/external/zlib_archive/_objs/zlib/inflate.pic.o: multiple definition of 'inflateSync'
/usr/bin/ld.gold: bazel-out/host/bin/external/zlib/_objs/zlib/inflate.pic.o: previous definition here
/usr/bin/ld.gold: error: bazel-out/host/bin/external/zlib_archive/_objs/zlib/inflate.pic.o: multiple definition of 'inflateSyncPoint'
/usr/bin/ld.gold: bazel-out/host/bin/external/zlib/_objs/zlib/inflate.pic.o: previous definition here
/usr/bin/ld.gold: error: bazel-out/host/bin/external/zlib_archive/_objs/zlib/inflate.pic.o: multiple definition of 'inflateUndermine'
/usr/bin/ld.gold: bazel-out/host/bin/external/zlib/_objs/zlib/inflate.pic.o: previous definition here
/usr/bin/ld.gold: error: bazel-out/host/bin/external/zlib_archive/_objs/zlib/inflate.pic.o: multiple definition of 'inflateValidate'
/usr/bin/ld.gold: bazel-out/host/bin/external/zlib/_objs/zlib/inflate.pic.o: previous definition here
/usr/bin/ld.gold: error: bazel-out/host/bin/external/zlib_archive/_objs/zlib/inftrees.pic.o: multiple definition of 'inflate_copyright'
/usr/bin/ld.gold: bazel-out/host/bin/external/zlib/_objs/zlib/inftrees.pic.o: previous definition here
/usr/bin/ld.gold: error: bazel-out/host/bin/external/zlib_archive/_objs/zlib/inftrees.pic.o: multiple definition of 'inflate_table'
/usr/bin/ld.gold: bazel-out/host/bin/external/zlib/_objs/zlib/inftrees.pic.o: previous definition here
/usr/bin/ld.gold: error: bazel-out/host/bin/external/zlib_archive/_objs/zlib/trees.pic.o: multiple definition of '_dist_code'
/usr/bin/ld.gold: bazel-out/host/bin/external/zlib/_objs/zlib/trees.pic.o: previous definition here
/usr/bin/ld.gold: error: bazel-out/host/bin/external/zlib_archive/_objs/zlib/trees.pic.o: multiple definition of '_length_code'
/usr/bin/ld.gold: bazel-out/host/bin/external/zlib/_objs/zlib/trees.pic.o: previous definition here
/usr/bin/ld.gold: error: bazel-out/host/bin/external/zlib_archive/_objs/zlib/trees.pic.o: multiple definition of '_tr_align'
/usr/bin/ld.gold: bazel-out/host/bin/external/zlib/_objs/zlib/trees.pic.o: previous definition here
/usr/bin/ld.gold: error: bazel-out/host/bin/external/zlib_archive/_objs/zlib/trees.pic.o: multiple definition of '_tr_flush_bits'
/usr/bin/ld.gold: bazel-out/host/bin/external/zlib/_objs/zlib/trees.pic.o: previous definition here
/usr/bin/ld.gold: error: bazel-out/host/bin/external/zlib_archive/_objs/zlib/trees.pic.o: multiple definition of '_tr_flush_block'
/usr/bin/ld.gold: bazel-out/host/bin/external/zlib/_objs/zlib/trees.pic.o: previous definition here
/usr/bin/ld.gold: error: bazel-out/host/bin/external/zlib_archive/_objs/zlib/trees.pic.o: multiple definition of '_tr_init'
/usr/bin/ld.gold: bazel-out/host/bin/external/zlib/_objs/zlib/trees.pic.o: previous definition here
/usr/bin/ld.gold: error: bazel-out/host/bin/external/zlib_archive/_objs/zlib/trees.pic.o: multiple definition of '_tr_stored_block'
/usr/bin/ld.gold: bazel-out/host/bin/external/zlib/_objs/zlib/trees.pic.o: previous definition here
/usr/bin/ld.gold: error: bazel-out/host/bin/external/zlib_archive/_objs/zlib/trees.pic.o: multiple definition of '_tr_tally'
/usr/bin/ld.gold: bazel-out/host/bin/external/zlib/_objs/zlib/trees.pic.o: previous definition here
/usr/bin/ld.gold: error: bazel-out/host/bin/external/zlib_archive/_objs/zlib/uncompr.pic.o: multiple definition of 'uncompress'
/usr/bin/ld.gold: bazel-out/host/bin/external/zlib/_objs/zlib/uncompr.pic.o: previous definition here
/usr/bin/ld.gold: error: bazel-out/host/bin/external/zlib_archive/_objs/zlib/uncompr.pic.o: multiple definition of 'uncompress2'
/usr/bin/ld.gold: bazel-out/host/bin/external/zlib/_objs/zlib/uncompr.pic.o: previous definition here
/usr/bin/ld.gold: error: bazel-out/host/bin/external/zlib_archive/_objs/zlib/zutil.pic.o: multiple definition of 'zError'
/usr/bin/ld.gold: bazel-out/host/bin/external/zlib/_objs/zlib/zutil.pic.o: previous definition here
/usr/bin/ld.gold: error: bazel-out/host/bin/external/zlib_archive/_objs/zlib/zutil.pic.o: multiple definition of 'z_errmsg'
/usr/bin/ld.gold: bazel-out/host/bin/external/zlib/_objs/zlib/zutil.pic.o: previous definition here
/usr/bin/ld.gold: error: bazel-out/host/bin/external/zlib_archive/_objs/zlib/zutil.pic.o: multiple definition of 'zcalloc'
/usr/bin/ld.gold: bazel-out/host/bin/external/zlib/_objs/zlib/zutil.pic.o: previous definition here
/usr/bin/ld.gold: error: bazel-out/host/bin/external/zlib_archive/_objs/zlib/zutil.pic.o: multiple definition of 'zcfree'
/usr/bin/ld.gold: bazel-out/host/bin/external/zlib/_objs/zlib/zutil.pic.o: previous definition here
/usr/bin/ld.gold: error: bazel-out/host/bin/external/zlib_archive/_objs/zlib/zutil.pic.o: multiple definition of 'zlibCompileFlags'
/usr/bin/ld.gold: bazel-out/host/bin/external/zlib/_objs/zlib/zutil.pic.o: previous definition here
/usr/bin/ld.gold: error: bazel-out/host/bin/external/zlib_archive/_objs/zlib/zutil.pic.o: multiple definition of 'zlibVersion'
/usr/bin/ld.gold: bazel-out/host/bin/external/zlib/_objs/zlib/zutil.pic.o: previous definition here
clang: error: linker command failed with exit code 1 (use -v to see invocation)
Target //tensorflow/tools/pip_package:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 16.852s, Critical Path: 5.74s
INFO: 14 processes: 14 local.
FAILED: Build did NOT complete successfully

**Comment by mihaimaruseac** [comment]
Can you check if #31196 helps?

**Comment by gadagashwini** [comment]
@butterfly-coder, Did you get a chance to look at the @mihaimaruseac's comment. Thanks!

**Comment by gadagashwini** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
