### ISSUE TITLE
Cannot import tensorflow.train

### ISSUE THREAD

**Issue by ageron** [tensorflow/tensorflow#33289]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): MacOSX 10.14.6
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): v2.0.0-rc2-26-g64c3d382ca 2.0.0
- Python version: 3.7.4
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

**Describe the current behavior**

Importing tensorflow.train raises a `ModuleNotFoundError: No module named 'tensorflow.train'`.

**Describe the expected behavior**

No error.
Note: this used to work fine in tf-nightly-2.0-preview.

**Code to reproduce the issue**

```python
import tensorflow.train
```

**Other info / logs**

Traceback:

```
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-0b4f8a92bbad> in <module>
----> 1 import tensorflow.train

ModuleNotFoundError: No module named 'tensorflow.train'
```

**Workaround**

Instead of:

```python
from tensorflow.train import BytesList
```

use:

```python
import tensorflow as tf
BytesList = tf.train.BytesList
```

**Comment by oanush** [comment]
issue replicating for TF-2.0, kindly find the [gist](https://colab.sandbox.google.com/gist/oanush/f346c12da815f02b9c54ad983e73e9cf/33289.ipynb) of colab.Thanks!

**Comment by nickcorona** [comment]
Same issue here.

**Comment by ravikyram** [comment]
@ageron 

This issue was resolved in TF version 2.2.rc3(`!pip install tensorflow==2.2-rc3 `).Please, find the gist [here.](https://colab.sandbox.google.com/gist/ravikyram/db65d7af7fbb1175072cdfbc82e2320b/untitled817.ipynb)Please verify once and close the issue. Thanks!

**Comment by ravikyram** [comment]
I am closing this thread as the issue got resolved in latest TF versions.Thanks!

**Comment by said-ml** [comment]
this issue was resolved in tf.__version==2.12.0
