### ISSUE TITLE
issue running build_all_ios.sh ?

### ISSUE THREAD

**Issue by sahil912** [tensorflow/tensorflow#3329]
On running build_all_ios.sh script, getting folllowing error?

m -lz
    Undefined symbols for architecture x86_64:
      "google::protobuf::io::CodedInputStream::ReadVarintSizeAsIntFallback()", referenced from:
      google::protobuf::io::CodedInputStream::ReadVarintSizeAsInt(int*) in test_log.pb.o
      google::protobuf::io::CodedInputStream::ReadVarintSizeAsInt(int*) in saved_tensor_slice.pb.o
      google::protobuf::io::CodedInputStream::ReadVarintSizeAsInt(int*) in event.pb.o
      google::protobuf::io::CodedInputStream::ReadVarintSizeAsInt(int*) in tensorflow_server.pb.o
      google::protobuf::io::CodedInputStream::ReadVarintSizeAsInt(int*) in named_tensor.pb.o
      google::protobuf::io::CodedInputStream::ReadVarintSizeAsInt(int*) in meta_graph.pb.o
      google::protobuf::io::CodedInputStream::ReadVarintSizeAsInt(int*) in config.pb.o
      ...
      "google::protobuf::MessageLite::InternalSerializeWithCachedSizesToArray(bool, unsigned char*) const", referenced from:
      vtable for google::protobuf::internal::MapEntryBase in test_log.pb.o
      vtable for google::protobuf::internal::MapEntryBase in tensorflow_server.pb.o
      vtable for google::protobuf::internal::MapEntryBase in meta_graph.pb.o
      vtable for google::protobuf::internal::MapEntryBase in config.pb.o
      vtable for google::protobuf::internal::MapEntryBase in graph.pb.o
      vtable for google::protobuf::internal::MapEntryBase in function.pb.o
      vtable for google::protobuf::internal::MapEntryBase in attr_value.pb.o
      ...
    ld: symbol(s) not found for architecture x86_64
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    make: *** [/Users/jsahil/projects/tensorflow/tensorflow
master/tensorflow/contrib/makefile/gen/host_bin/proto_text] Error 1
    + '[' 2 -ne 0 ']'
    + echo 'armv7 compilation failed.'
    armv7 compilation failed. 
    + exit 1

Let me know if I am missing something. Thanks

**Comment by jmchen-g** [comment]
@petewarden Could you take a look at this please?

**Comment by petewarden** [comment]
I've looked at it, and wasn't able to reproduce the problem. I did encounter a few missing files from the Makefile that I've added in PR #3337, but after that the build_all_ios.sh script completed successfully.

@sahil912 can you see if there's any mention of missing libprotobuf files in the lines before those linker errors, since it appears that the creation of those failed?

**Comment by fgeorg** [comment]
I had the same problem as above and pulling in your changes seems to have fixed the issue

**Comment by sahil912** [comment]
@petewarden 

I tried to run this with the latest version, and getting following error:

    "void tensorflow::HandleStridedSliceCase<Eigen::ThreadPoolDevice, int, 3>(tensorflow::OpKernelContext*, tensorflow::gtl::ArraySlice<long long> const&, tensorflow::gtl::ArraySlice<long long> const&, tensorflow::gtl::ArraySlice<long long> const&, tensorflow::TensorShape const&, bool, tensorflow::Tensor*)", referenced from:
      tensorflow::StridedSliceOp<Eigen::ThreadPoolDevice, int>::Compute(tensorflow::OpKernelContext*) in libtensorflow-core-armv7.a(strided_slice_op.o)
  "void tensorflow::HandleStridedSliceGradCase<Eigen::ThreadPoolDevice, float, 5>(tensorflow::OpKernelContext*, tensorflow::gtl::ArraySlice<long long> const&, tensorflow::gtl::ArraySlice<long long> const&, tensorflow::gtl::ArraySlice<long long> const&, tensorflow::TensorShape const&, bool, tensorflow::Tensor*)", referenced from:
      tensorflow::StridedSliceGradOp<Eigen::ThreadPoolDevice, float>::Compute(tensorflow::OpKernelContext*) in libtensorflow-core-armv7.a(strided_slice_op.o)
  "void tensorflow::HandleStridedSliceCase<Eigen::ThreadPoolDevice, int, 6>(tensorflow::OpKernelContext*, tensorflow::gtl::ArraySlice<long long> const&, tensorflow::gtl::ArraySlice<long long> const&, tensorflow::gtl::ArraySlice<long long> const&, tensorflow::TensorShape const&, bool, tensorflow::Tensor*)", referenced from:
      tensorflow::StridedSliceOp<Eigen::ThreadPoolDevice, int>::Compute(tensorflow::OpKernelContext*) in libtensorflow-core-armv7.a(strided_slice_op.o)
ld: symbol(s) not found for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [/Users/jsahil/projects/tensorflow/tensorflow-latest/tensorflow/tensorflow/contrib/makefile/gen/bin/benchmark] Error 1
+ '[' 2 -ne 0 ']'
+ echo 'armv7 compilation failed.'
armv7 compilation failed.
+ exit 1

**Comment by sahil912** [comment]
works good after #3382 commit. Thanks
