### ISSUE TITLE
Tflite coverter error. tensorflow/lite/toco/tooling_util.cc:935

### ISSUE THREAD

**Issue by tdas714** [tensorflow/tensorflow#33302]
<em>I'm trying to convert a TensorFlow model to tflite model from a frozen graph.
I' getting an error saying I should make a bug report to tflite team.

**you can download the graph from [HERE.**](https://drive.google.com/file/d/1LqyZWJsZadOHCxY8kG8JAskMoRgOWzSH/view?usp=sharing) 

any help would be much appreciated. </em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 7
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.0.0
- Python version: 3.7

**Describe the current behavior**
tensorflow/lite/toco/tooling_util.cc:935] Check failed: GetOpWithOutput(model, output_array) Specified output array "sample_sequence/while/Exit_3" is not produced by any op in this graph. Is it a typo? This should not happen. If you trigger this error please send a bug report (with code to reporduce this error), to the TensorFlow Lite team.
Aborted (core dumped)
**Describe the expected behavior**

**Code to reproduce the issue**
**import tensorflow as tf
import sys
from tensorflow.python.platform import gfile

from tensorflow.core.protobuf import saved_model_pb2
from tensorflow.python.util import compat

graph_def_file = "frozen_355.pb"
input_arrays = ["sample_sequence/model/Shape"]
output_arrays = ["sample_sequence/while/Exit_3"]

converter = tf.compat.v1.lite.TFLiteConverter.from_frozen_graph(graph_def_file, input_arrays, output_arrays)
tflite_model = converter.convert()
open("converted_model_0.tflite", "wb").write(tflite_model)**

**Other info / logs**
ConverterError                            Traceback (most recent call last)
<ipython-input-4-e27c2f171b9b> in <module>()
      4 
      5 converter = tf.compat.v1.lite.TFLiteConverter.from_frozen_graph(graph_def_file, input_arrays, output_arrays)
----> 6 tflite_model = converter.convert()
      7 open("content/drive/My Drive/converted_model_0.tflite", "wb").write(tflite_model)

2 frames
/usr/local/lib/python3.6/dist-packages/tensorflow_core/lite/python/convert.py in toco_convert_protos(model_flags_str, toco_flags_str, input_data_str, debug_info_str, enable_mlir_converter)
    198       stdout = _try_convert_to_unicode(stdout)
    199       stderr = _try_convert_to_unicode(stderr)
--> 200       raise ConverterError("See console for info.\n%s\n%s\n" % (stdout, stderr))
    201   finally:
    202     # Must manually cleanup files.

ConverterError: See console for info.
2019-10-13 11:18:54.608948: F tensorflow/lite/toco/tooling_util.cc:935] Check failed: GetOpWithOutput(model, output_array) Specified output array "sample_sequence/while/Exit_3" is not produced by any op in this graph. Is it a typo? This should not happen. If you trigger this error please send a bug report (with code to reporduce this error), to the TensorFlow Lite team.
Aborted (core dumped)

**Comment by oanush** [comment]
I was able to replicate the issue, please find the .ipynb file.
[33302.ipynb.zip](https://github.com/tensorflow/tensorflow/files/3723813/33302.ipynb.zip)
Thanks!

**Comment by tdas714** [comment]
have you find any reason, why it's happening.

let me know .

**Comment by gargn** [comment]
An `Exit` op means that this graph has control flow. TensorFlow Lite doesn't support control flow generated by TensorFlow 1.X so this functionality is not expected to work. We are working on supporting control flow 2.0 so please regenerate your graph in 2.0 if you want to run it using TenosrFlow Lite.
