### ISSUE TITLE
layer reuse

### ISSUE THREAD

**Issue by Stick-To** [tensorflow/tensorflow#33305]
```

def head(self, input, num_anchors, name, flatten=False):

    out_channels = (self.num_classes + 4) * num_anchors
    conv = layers.Conv2D(256, 3, 1, 'same', activation='relu', name=name+'_conv1')(input)
    conv = layers.Conv2D(256, 3, 1, 'same', activation='relu', name=name+'_conv2')(conv)
    conv = layers.Conv2D(256, 3, 1, 'same', activation='relu', name=name+'_conv3')(conv)
    out = layers.Conv2D(out_channels, 3, 1, 'same', name=name+'output')(conv)
    return out

```

I want to know how to reuse these layers as tf.variable_scope(scope resue=tf.AUTO_REUSE) in tensorflow1

In tensorflow1

```
with tf.variable_scope('a', resue=tf.AUTO_REUSE) as scope:

         all layers here could be auto reuse

```

**Comment by oanush** [comment]
@Stick-To ,
Can you share complete code to reproduce the issue reported here? Also provide the TF version being used.

**Comment by Stick-To** [comment]
`
out1 = self.head(fpn_feat[0], len(anchors[0]), 'head', flatten=True)
out2 = self.head(fpn_feat[1], len(anchors[1]), 'head', flatten=True)
out3 = self.head(fpn_feat[2], len(anchors[2]), 'head', flatten=True)
out4 = self.head(fpn_feat[3], len(anchors[3]), 'head', flatten=True)
out5 = self.head(fpn_feat[4], len(anchors[4]), 'head', flatten=True)
`
@oanush  I want to resue the layers in head()

**Comment by oanush** [comment]
@Stick-To ,
Hi, I see that there are entities like `input, num_anchors, name` code for which are not given, can you provide the complete code for same ?

**Comment by mihaimaruseac** [comment]
Also, can you please use proper markdown format around the code so that it can be read?

**Comment by zheyuanWang** [comment]
>  how to reuse these layers as tf.variable_scope(scope resue=tf.AUTO_REUSE) in tensorflow1
Hi, have you figured out how to reuse?
