### ISSUE TITLE
tf_upgrade_v2 is not reporting issues related to invalid imports in TensorFlow 2

### ISSUE THREAD

**Issue by nbro** [tensorflow/tensorflow#33309]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Mac OS Catalina
- TensorFlow installed from (source or binary): binary (pip install tensorflow)
- TensorFlow version (use command below): 2.0.0
- Python version: 3.7.4
- CUDA/cuDNN version: None
- GPU model and memory: Intel Iris Pro 1536 MB

**Describe the current behavior**

I am trying to use the script `tf_upgrade_v2` as follows 

```
tf_upgrade_v2 --infile bayesian_nn.py --outfile bayesian_nn2.py
```
The new file `bayesian_nn2.py` is created and the `report.txt` file is also generated, but `report.txt` does not report any issues, while in `bayesian_nn2.py` there is still code that cannot be run in TF2. For example, `report.txt` does not report that I have the import `from tensorflow.contrib.learn.python.learn.datasets import mnist`, which is no longer valid in TF2.

More specifically, this is my `report.txt`

```
TensorFlow 2.0 Upgrade Script
-----------------------------
Converted 1 files
Detected 0 issues that require attention
--------------------------------------------------------------------------------
================================================================================
Detailed log follows:

================================================================================
--------------------------------------------------------------------------------
Processing file 'bayesian_nn.py'
 outputting to 'bayesian_nn2.py'
--------------------------------------------------------------------------------
```

I am trying to port the following module https://github.com/tensorflow/probability/blob/master/tensorflow_probability/examples/bayesian_neural_network.py to TF2.

According to the documentation, the upgrade script should report these issues: https://www.tensorflow.org/guide/upgrade, but it does not.

**Comment by oanush** [comment]
@nbro ,
Thank you for reporting the issue, can you please provide bayesian_nn.py file  or the code the used in the file ?

**Comment by nbro** [comment]
@oanush The file is called `bayesian_nn.py`, but the code is the same as in https://github.com/tensorflow/probability/blob/master/tensorflow_probability/examples/bayesian_neural_network.py.

**Comment by oanush** [comment]
I was able to replicate the issue in local. Thanks!

**Comment by martinwicke** [comment]
@tomerk -- I think to some extent this is inevitable (we are only considering "tf." when warning/modifying), but we did discuss whether it might be feasible to handle some common patterns.

**Comment by sanatmpa1** [comment]
@nbro,

We are checking to see if you still need help on this issue. We recommend that you upgrade to `2.6` which is latest stable version of TF and let us know if the issue still persists in newer versions. we will get you the right help.Thanks!
