### ISSUE TITLE
when run example: speech_commands and try to run freeze.py, Tensor name "final_fc_bias" not found in checkpoint files /tmp/speech_commands_train/conv.ckpt-2000.index

### ISSUE THREAD

**Issue by FridaCai** [tensorflow/tensorflow#33306]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
no

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
MacOS Sierra version 10.12.6

- TensorFlow installed from (source or binary):
binary

- TensorFlow version (use command below):
2.0 beta

- Python version:
2.7

- Run tf_env_collect.sh
== check python ===================================================
python version: 2.7.10
python branch: 
python build version: ('default', 'Feb  7 2017 00:08:15')
python compiler version: GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)
python implementation: CPython

== check os platform ===============================================
os: Darwin
os kernel version: Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEASE_X86_64
os release version: 16.7.0
os platform: Darwin-16.7.0-x86_64-i386-64bit
linux distribution: ('', '', '')
linux os distribution: ('', '', '')
mac version: ('10.12.6', ('', '', ''), 'x86_64')
uname: ('Darwin', 's-macbook-air', '16.7.0', 'Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEASE_X86_64', 'x86_64', 'i386')
architecture: ('64bit', '')
machine: x86_64

== are we in docker =============================================
No

== compiler =====================================================
Apple LLVM version 9.0.0 (clang-900.0.38)
Target: x86_64-apple-darwin16.7.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

== check pips ===================================================
numpy                                  1.8.0rc1

== check for virtualenv =========================================
False

== tensorflow import ============================================
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named tensorflow

== env ==========================================================
LD_LIBRARY_PATH is unset
DYLD_LIBRARY_PATH is unset

== nvidia-smi ===================================================
./tf_env_collect.sh: line 147: nvidia-smi: command not found

== cuda libs  ===================================================

== tensorflow installed from info ==================

== python version  ==============================================
(major, minor, micro, releaselevel, serial)
(2, 7, 10, 'final', 0)

== bazel version  ===============================================
Build label: 0.29.1
Build time: Tue Sep 10 13:47:42 2019 (1568123262)
Build timestamp: 1568123262
Build timestamp as int: 1568123262

== check python ===================================================
python version: 2.7.10
python branch: 
python build version: ('default', 'Feb  7 2017 00:08:15')
python compiler version: GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)
python implementation: CPython

== check os platform ===============================================
os: Darwin
os kernel version: Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEASE_X86_64
os release version: 16.7.0
os platform: Darwin-16.7.0-x86_64-i386-64bit
linux distribution: ('', '', '')
linux os distribution: ('', '', '')
mac version: ('10.12.6', ('', '', ''), 'x86_64')
uname: ('Darwin', 's-macbook-air', '16.7.0', 'Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEASE_X86_64', 'x86_64', 'i386')
architecture: ('64bit', '')
machine: x86_64

== are we in docker =============================================
No

== compiler =====================================================
Apple LLVM version 9.0.0 (clang-900.0.38)
Target: x86_64-apple-darwin16.7.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

== check pips ===================================================
numpy                                  1.16.5              
protobuf                               3.9.1               
tensorflow                             2.0.0b0             

== check for virtualenv =========================================
True

== tensorflow import ============================================
tf.version.VERSION = 2.0.0-beta0
tf.version.GIT_VERSION = v1.12.1-3259-gf59745a381
tf.version.COMPILER_VERSION = 4.2.1 Compatible Apple LLVM 10.0.0 (clang-1000.11.45.5)

== env ==========================================================
LD_LIBRARY_PATH is unset
DYLD_LIBRARY_PATH is unset

== nvidia-smi ===================================================
./tf_env_collect.sh: line 147: nvidia-smi: command not found

== cuda libs  ===================================================

== tensorflow installed from info ==================
Name: tensorflow
Version: 2.0.0b0
Summary: TensorFlow is an open source machine learning framework for everyone.
Home-page: https://www.tensorflow.org/
Author-email: packages@tensorflow.org
License: Apache 2.0
Location: /Users/liupai/tensorflow/lib/python2.7/site-packages
Required-by: 

== python version  ==============================================
(major, minor, micro, releaselevel, serial)
(2, 7, 10, 'final', 0)

== bazel version  ===============================================
Build label: 0.29.1
Build time: Tue Sep 10 13:47:42 2019 (1568123262)
Build timestamp: 1568123262
Build timestamp as int: 1568123262

**Describe the current behavior**
I am following the tutorials:
examples/speech_commands

python tensorflow/examples/speech_commands/train.py 
--how_many_training_steps=1500,500  
--data_dir="speech_commands_v0.02" 
--data_url=

python tensorflow/examples/speech_commands/freeze.py 
--start_checkpoint=/tmp/speech_commands_train/conv.ckpt-2000.index 
--output_file=/tmp/my_frozen_graph.pb

it failed with:
(tensorflow) s-macbook-air:tensorflow liupai$ python tensorflow/examples/speech_commands/freeze.py --start_checkpoint=/tmp/speech_commands_train/conv.ckpt-200.index --output_file=/tmp/my_frozen_graph.pb
2019-10-13 18:55:56.670314: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
WARNING:tensorflow:From /Users/liupai/tensorflow/lib/python2.7/site-packages/tensorflow/python/training/saver.py:1276: checkpoint_exists (from tensorflow.python.training.checkpoint_management) is deprecated and will be removed in a future version.
Instructions for updating:
Use standard file APIs to check for files with this prefix.
W1013 18:55:56.782098 140736832123840 deprecation.py:323] From /Users/liupai/tensorflow/lib/python2.7/site-packages/tensorflow/python/training/saver.py:1276: checkpoint_exists (from tensorflow.python.training.checkpoint_management) is deprecated and will be removed in a future version.
Instructions for updating:
Use standard file APIs to check for files with this prefix.
INFO:tensorflow:Restoring parameters from /tmp/speech_commands_train/conv.ckpt-200.index
I1013 18:55:56.784265 140736832123840 saver.py:1280] Restoring parameters from /tmp/speech_commands_train/conv.ckpt-200.index
Traceback (most recent call last):
  File "tensorflow/examples/speech_commands/freeze.py", line 250, in <module>
    tf.compat.v1.app.run(main=main, argv=[sys.argv[0]] + unparsed)
  File "/Users/liupai/tensorflow/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/Users/liupai/tensorflow/lib/python2.7/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/Users/liupai/tensorflow/lib/python2.7/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "tensorflow/examples/speech_commands/freeze.py", line 176, in main
    models.load_variables_from_checkpoint(sess, FLAGS.start_checkpoint)
  File "/Users/liupai/tensorflow/tensorflow/tensorflow/examples/speech_commands/models.py", line 101, in load_variables_from_checkpoint
    saver.restore(sess, start_checkpoint)
  File "/Users/liupai/tensorflow/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1302, in restore
    err, "a Variable name or other graph key that is missing")
tensorflow.python.framework.errors_impl.NotFoundError: Restoring from checkpoint failed. This is most likely due to a Variable name or other graph key that is missing from the checkpoint. Please ensure that you have not altered the graph expected based on the checkpoint. Original error:

Tensor name "final_fc_bias" not found in checkpoint files /tmp/speech_commands_train/conv.ckpt-200.index
	 [[node save/RestoreV2 (defined at /Users/liupai/tensorflow/tensorflow/tensorflow/examples/speech_commands/models.py:100) ]]

Original stack trace for u'save/RestoreV2':
  File "tensorflow/examples/speech_commands/freeze.py", line 250, in <module>
    tf.compat.v1.app.run(main=main, argv=[sys.argv[0]] + unparsed)
  File "/Users/liupai/tensorflow/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/Users/liupai/tensorflow/lib/python2.7/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/Users/liupai/tensorflow/lib/python2.7/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "tensorflow/examples/speech_commands/freeze.py", line 176, in main
    models.load_variables_from_checkpoint(sess, FLAGS.start_checkpoint)
  File "/Users/liupai/tensorflow/tensorflow/tensorflow/examples/speech_commands/models.py", line 100, in load_variables_from_checkpoint
    saver = tf.compat.v1.train.Saver(tf.compat.v1.global_variables())
  File "/Users/liupai/tensorflow/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 825, in __init__
    self.build()
  File "/Users/liupai/tensorflow/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 837, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "/Users/liupai/tensorflow/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 875, in _build
    build_restore=build_restore)
  File "/Users/liupai/tensorflow/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 508, in _build_internal
    restore_sequentially, reshape)
  File "/Users/liupai/tensorflow/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 328, in _AddRestoreOps
    restore_sequentially)
  File "/Users/liupai/tensorflow/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 575, in bulk_restore
    return io_ops.restore_v2(filename_tensor, names, slices, dtypes)
  File "/Users/liupai/tensorflow/lib/python2.7/site-packages/tensorflow/python/ops/gen_io_ops.py", line 1696, in restore_v2
    name=name)
  File "/Users/liupai/tensorflow/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "/Users/liupai/tensorflow/lib/python2.7/site-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/Users/liupai/tensorflow/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 3296, in create_op
    op_def=op_def)
  File "/Users/liupai/tensorflow/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1692, in __init__
    self._traceback = tf_stack.extract_stack()

**Describe the expected behavior**
when run freeze.py, it should success according to the tutorials.

**Comment by ravikyram** [comment]
@FridaCai 
Can you please let us know which tutorial you are referring to? Thanks!.

**Comment by FridaCai** [comment]
tutorial: https://github.com/tensorflow/docs/blob/master/site/en/r1/tutorials/sequences/audio_recognition.md

**Comment by FridaCai** [comment]
another issue when following the tutorial:

bazel run tensorflow/examples/speech_commands:generate_streaming_test_wav
Starting local Bazel server and connecting to it...
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=1 --terminal_columns=80
INFO: Reading rc options for 'run' from /Users/liupai/tensorflow/tensorflow/.bazelrc:
  Inherited 'build' options: --apple_platform_type=macos --define framework_shared_object=true --define open_source_build=true --define=use_fast_cpp_protos=true --define=allow_oversize_protos=true --spawn_strategy=standalone --strategy=Genrule=standalone -c opt --cxxopt=-std=c++14 --host_cxxopt=-std=c++14 --announce_rc --define=grpc_no_ares=true --define=PREFIX=/usr --define=LIBDIR=$(PREFIX)/lib --define=INCLUDEDIR=$(PREFIX)/include
Traceback (most recent call last):
  File "/private/var/tmp/_bazel_liupai/75ba6c3dceb6d95ea0c24bbee6657cc0/external/org_tensorflow/tensorflow/tools/git/gen_git_source.py", line 29, in <module>
    from builtins import bytes  # pylint: disable=redefined-builtin
ImportError: No module named builtins
INFO: Call stack for the definition of repository 'local_config_git' which is a git_configure (rule definition at /Users/liupai/tensorflow/tensorflow/third_party/git/git_configure.bzl:63:17):
 - /Users/liupai/tensorflow/tensorflow/tensorflow/workspace.bzl:74:5
 - /Users/liupai/tensorflow/tensorflow/WORKSPACE:19:1
ERROR: An error occurred during the fetch of repository 'local_config_git':
   Traceback (most recent call last):
	File "/Users/liupai/tensorflow/tensorflow/third_party/git/git_configure.bzl", line 61
		_fail(result.stderr)
	File "/Users/liupai/tensorflow/tensorflow/third_party/git/git_configure.bzl", line 14, in _fail
		fail(("%sGit Configuration Error:%s %...)))
Git Configuration Error: Traceback (most recent call last):
  File "/private/var/tmp/_bazel_liupai/75ba6c3dceb6d95ea0c24bbee6657cc0/external/org_tensorflow/tensorflow/tools/git/gen_git_source.py", line 29, in <module>
    from builtins import bytes  # pylint: disable=redefined-builtin
ImportError: No module named builtins

INFO: Call stack for the definition of repository 'grpc' which is a tf_http_archive (rule definition at /Users/liupai/tensorflow/tensorflow/third_party/repo.bzl:121:19):
 - /Users/liupai/tensorflow/tensorflow/tensorflow/workspace.bzl:513:5
 - /Users/liupai/tensorflow/tensorflow/WORKSPACE:19:1
INFO: Call stack for the definition of repository 'llvm' which is a tf_http_archive (rule definition at /Users/liupai/tensorflow/tensorflow/third_party/repo.bzl:121:19):
 - /Users/liupai/tensorflow/tensorflow/tensorflow/workspace.bzl:548:5
 - /Users/liupai/tensorflow/tensorflow/WORKSPACE:19:1
ERROR: /Users/liupai/tensorflow/tensorflow/tensorflow/core/BUILD:2751:1: //tensorflow/core:version_info_gen depends on @local_config_git//:gen/spec.json in repository @local_config_git which failed to fetch. no such package '@local_config_git//': Traceback (most recent call last):
	File "/Users/liupai/tensorflow/tensorflow/third_party/git/git_configure.bzl", line 61
		_fail(result.stderr)
	File "/Users/liupai/tensorflow/tensorflow/third_party/git/git_configure.bzl", line 14, in _fail
		fail(("%sGit Configuration Error:%s %...)))
Git Configuration Error: Traceback (most recent call last):
  File "/private/var/tmp/_bazel_liupai/75ba6c3dceb6d95ea0c24bbee6657cc0/external/org_tensorflow/tensorflow/tools/git/gen_git_source.py", line 29, in <module>
    from builtins import bytes  # pylint: disable=redefined-builtin
ImportError: No module named builtins

ERROR: /Users/liupai/tensorflow/tensorflow/tensorflow/core/BUILD:2751:1: //tensorflow/core:version_info_gen depends on @local_config_git//:gen/head in repository @local_config_git which failed to fetch. no such package '@local_config_git//': Traceback (most recent call last):
	File "/Users/liupai/tensorflow/tensorflow/third_party/git/git_configure.bzl", line 61
		_fail(result.stderr)
	File "/Users/liupai/tensorflow/tensorflow/third_party/git/git_configure.bzl", line 14, in _fail
		fail(("%sGit Configuration Error:%s %...)))
Git Configuration Error: Traceback (most recent call last):
  File "/private/var/tmp/_bazel_liupai/75ba6c3dceb6d95ea0c24bbee6657cc0/external/org_tensorflow/tensorflow/tools/git/gen_git_source.py", line 29, in <module>
    from builtins import bytes  # pylint: disable=redefined-builtin
ImportError: No module named builtins

ERROR: /Users/liupai/tensorflow/tensorflow/tensorflow/core/BUILD:2751:1: //tensorflow/core:version_info_gen depends on @local_config_git//:gen/branch_ref in repository @local_config_git which failed to fetch. no such package '@local_config_git//': Traceback (most recent call last):
	File "/Users/liupai/tensorflow/tensorflow/third_party/git/git_configure.bzl", line 61
		_fail(result.stderr)
	File "/Users/liupai/tensorflow/tensorflow/third_party/git/git_configure.bzl", line 14, in _fail
		fail(("%sGit Configuration Error:%s %...)))
Git Configuration Error: Traceback (most recent call last):
  File "/private/var/tmp/_bazel_liupai/75ba6c3dceb6d95ea0c24bbee6657cc0/external/org_tensorflow/tensorflow/tools/git/gen_git_source.py", line 29, in <module>
    from builtins import bytes  # pylint: disable=redefined-builtin
ImportError: No module named builtins

ERROR: Analysis of target '//tensorflow/examples/speech_commands:generate_streaming_test_wav' failed; build aborted: no such package '@local_config_git//': Traceback (most recent call last):
	File "/Users/liupai/tensorflow/tensorflow/third_party/git/git_configure.bzl", line 61
		_fail(result.stderr)
	File "/Users/liupai/tensorflow/tensorflow/third_party/git/git_configure.bzl", line 14, in _fail
		fail(("%sGit Configuration Error:%s %...)))
Git Configuration Error: Traceback (most recent call last):
  File "/private/var/tmp/_bazel_liupai/75ba6c3dceb6d95ea0c24bbee6657cc0/external/org_tensorflow/tensorflow/tools/git/gen_git_source.py", line 29, in <module>
    from builtins import bytes  # pylint: disable=redefined-builtin
ImportError: No module named builtins

INFO: Elapsed time: 18.452s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (157 packages loaded, 4227 targets\
FAILED: Build did NOT complete successfully (157 packages loaded, 4227 targets\
 configured)

**Comment by jvishnuvardhan** [comment]
@FridaCai Is this still an issue. Can you please try with recent `tf-nightly` and let us know whether the issue persists with latest TF version. Thanks!

Please close the issue if this was already resolved with the recent TF version. Thanks!

**Comment by ymodak** [comment]
@FridaCai Since the stacktrace says Restoring from checkpoint failed. This is most likely due to a Variable name or other graph key that is missing from the checkpoint.
You may want to try complete training for 18000 steps as mentioned in the tutorial before freezing.
See https://github.com/tensorflow/docs/blob/master/site/en/r1/tutorials/sequences/audio_recognition.md

**Comment by jvishnuvardhan** [comment]
I think it was resolved. I am closing the issue. Please open a new ticket if you see similar issue again. Thanks!
