### ISSUE TITLE
tf.io.gfile.GFile.read() dose not return but terminates my 

### ISSUE THREAD

**Issue by Jinof** [tensorflow/tensorflow#33301]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- OS: Windows 10 18362
- TensorFlow installed from (source or binary): sourece
- TensorFlow version (use command below):  v2.0.0-rc2-26-g64c3d382ca 2.0.0
- Python version: python 3.68

**Describe the current behavior**
The func read() does not work (it return noting) and terminates my program. 
**Describe the expected behavior**
In the doc, read() shoud return the contents of the file as string
**Code to reproduce the issue**
`import tensorflow as tf `
`image = tf.io.gfile.GFile(r"..\datasets\icdar2015\img_1.jpg", 'r')`
`image.read()`

My TF2.0 version below has the same problem with the beyond.
`image_data = tf.io.gfile.GFile(os.path.abspath(path), 'rb').read()`

My TF1.x version below run well 
`image_data = tf.gfile.FastGFile(os.path.abspath(path), 'rb').read()`

**Comment by gadagashwini** [comment]
@Jinof, I tried replicating the issue with Tf 2.0.0 but it worked as expected. `tf.io.gfile.GFile(path).read() `returns the content of the file as string. Please refer [this link](https://www.tensorflow.org/api_docs/python/tf/io/gfile/GFile#read). Thanks

**Comment by Jinof** [comment]
> @Jinof, I tried replicating the issue with Tf 2.0.0 but it worked as expected. `tf.io.gfile.GFile(path).read() `returns the content of the file as string. Please refer [this link](https://www.tensorflow.org/api_docs/python/tf/io/gfile/GFile#read). Thanks

Yeah i have made it.My program does have some problem.What puzzles me is my TF2.0 version quit without reporting any error but my TF1.X version report my errors correctly.
