### ISSUE TITLE
tensorflow based shared library can't link to other project

### ISSUE THREAD

**Issue by qazmichaelgw** [tensorflow/tensorflow#3330]
Problem:
I create a project in tensorflow/tensorflow/my_project. Then create a library by cc_library of bazel. I can compile it and create the library. For example, test.a, test.so in tensorflow/bazel-bin/my_project. But if I use the library in another project by linking it. It would raise a problem of finding the header file.
```
fatal error: tensorflow/core/framework/graph.pb.h: No such file or directory
```
test.h:
```
#include "tensorflow/core/framework/graph.pb.h"
#include "tensorflow/core/framework/tensor.h"
#include "tensorflow/core/public/session.h"
#include "tensorflow/core/platform/env.h"

blabla...
```

**Comment by jmchen-g** [comment]
@martinwicke Do you know what is the recommended way to do such thing?

**Comment by martinwicke** [comment]
This is a question best asked on the bazel channels. 

Also, you should include information on how you've set up your other's project's build. It looks like you simply haven't included the correct paths in whatever build system you use there.
