### ISSUE TITLE
No OpKernel was registered to support Op 'TPUReplicateMetadata' used by node TPUReplicateMetadata

### ISSUE THREAD

**Issue by appleyuchi** [tensorflow/tensorflow#33307]
When I run the following .ipynb:

https://colab.research.google.com/drive/1DpUCBm58fruGNRtQL_DiSVbT90spdZgm

I got:
No OpKernel was registered to support Op 'TPUReplicateMetadata' used by node TPUReplicateMetadata (defined at /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/ops.py:1748) with these attrs: [num_cores_per_replica=1, use_tpu=true, num_replicas=8, computation_shape=[], host_compute_core=[], device_assignment=[], _tpu_replicate="cluster", padding_map=[], topology="", step_marker_location="STEP_MARK_AT_ENTRY", allow_soft_placement=false]
Registered devices: [CPU, XLA_CPU]

**Comment by ravikyram** [comment]
Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version. Also, did you compile from source or install a binary?.
I tried with TF 1.14 ,1.15.0-rc3, 1.13.1 and i am able to reproduce the issue.Please, find the gist [here](https://colab.sandbox.google.com/gist/ravikyram/f66344f948481ed6af0d25cbfcb08b06/untitled261.ipynb).But in the colab link you have shared i am not seeing any error.Can you please confirm is this expected behavior?.Thanks!

**Comment by appleyuchi** [comment]
@ravikyram Thanks for your replies.
I use your gist and find new error:
/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/callbacks.py in configure_callbacks(callbacks, model, do_validation, batch_size, epochs, steps_per_epoch, samples, verbose, count_mode, mode)
    118   callback_list.model.stop_training = False
    119   # pylint: disable=protected-access
--> 120   if callback_list.model._ckpt_saved_epoch is not None:
    121     # The attribute `_ckpt_saved_epoch` is supposed to be None at the start of
    122     # training (it should be made None at the end of successful multi-worker

AttributeError: 'KerasTPUModel' object has no attribute '_ckpt_saved_epoch'

**Comment by appleyuchi** [comment]
> Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version. Also, did you compile from source or install a binary?.
> I tried with TF 1.14 ,1.15.0-rc3, 1.13.1 and i am able to reproduce the issue.Please, find the gist [here](https://colab.sandbox.google.com/gist/ravikyram/f66344f948481ed6af0d25cbfcb08b06/untitled261.ipynb).But in the colab link you have shared i am not seeing any error.Can you please confirm is this expected behavior?.Thanks!


I just use colab,all edition are same as yours.
 Could you help me? thanks

**Comment by appleyuchi** [comment]
what's your meaning?

"I tried with TF 1.14 ,1.15.0-rc3, 1.13.1 and i am able to reproduce the issue.
Please, find the gist here.
But in the colab link you have shared i am not seeing any error."

you are  able to reproduce the issue
you are not able to reroduce the issue in my link?

????

**Comment by ravikyram** [comment]
@appleyuchi 

Now,I am able to reproduce the issue in the link provided by you .Thanks!

**Comment by appleyuchi** [comment]
> @appleyuchi
> 
> Now,I am able to reproduce the issue in the link provided by you .Thanks!

waiting for your help.
I seems hard to find answer from Google.
Much Thanks

**Comment by jvishnuvardhan** [comment]
@appleyuchi I looked at your code. There are multiple updates you need to do before it runs. For instance, `tpu_model.fit_generator` is not supported with TPU distribution strategy and you also need to define, compile and fit the `model` under `with strategy.scope():`. Can you please follow the [TF Resource here](https://www.tensorflow.org/guide/distributed_training) and update your code. 

You could also find some TPU codes from github users [like this  one](https://github.com/tensorflow/tensorflow/issues/30162). Thanks!

**Comment by appleyuchi** [comment]
@jvishnuvardhan 
This code is from some technical news by a small company.
it did not tell any version requirements.
So I met such problems.
Could you help me fix it?Thanks
And it seems that it is really an internal bug of Tensorflow

**Comment by jvishnuvardhan** [comment]
@appleyuchi You could follow the links I provided and update your codes. Thanks!

**Comment by appleyuchi** [comment]
@jvishnuvardhan they seems are not the same issue.

**Comment by jvishnuvardhan** [comment]
This is not Build/Installation or Bug/Performance issue. Please post this kind of support questions at [Stackoverflow](https://stackoverflow.com/questions/tagged/tensorflow). There is a big community to support and learn from your questions. GitHub is mainly for addressing bugs in installation and performance. Thanks!

**Comment by appleyuchi** [comment]
> This is not Build/Installation or Bug/Performance issue. Please post this kind of support questions at [Stackoverflow](https://stackoverflow.com/questions/tagged/tensorflow). There is a big community to support and learn from your questions. GitHub is mainly for addressing bugs in installation and performance. Thanks!


But only the developer know the meaning of each word of this error.
It's impossible for users to understand the meaning without the help of developer.

**Comment by appleyuchi** [comment]
OK,I'll try to ask this question on stackoveflow today.
