### ISSUE TITLE
Retrofitting: idgi make me smarter :)

### ISSUE THREAD

**Issue by disyntheticlogic** [tensorflow/tensorflow#3331]
can someone point me to some info on retrofitting?  I don't get it really.  

I'm specifically trying to combine some of my writing with ConceptNet (which I can download in matrix form) in order to generate output that sounds something like me or at least talks about the things i talk about.  Guess I'm not understanding how to align and combine the matrices for the most part but any literature is greatly appreciated.

Cheers,
di-synthetic-logic
p.s. bless you

**Comment by vrv** [comment]
This is probably a better question for StackOverflow, the people monitoring these issues are only helping with bugs / TensorFlow core features.
