### ISSUE TITLE
tf.print usage throws SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by yongtang** [tensorflow/tensorflow#33311]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): n/a
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: n/a
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.0.0
- Python version: 2.7 (Ubuntu 18.04 system default + latest pip from get-pip.py)
- Bazel version (if compiling from source): n/a
- GCC/Compiler version (if compiling from source): n/a
- CUDA/cuDNN version: n/a
- GPU model and memory: n/a

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**

Wile playing with `tf.print` as described in docs, the following error happens:
```python
$ python
Python 2.7.15+ (default, Oct  7 2019, 17:39:04) 
[GCC 7.4.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
>>> import sys
>>> tensor = tf.range(10) 
>>> tf.print(tensor, output_stream=sys.stderr)
  File "<stdin>", line 1
    tf.print(tensor, output_stream=sys.stderr)
           ^
SyntaxError: invalid syntax
>>>
```
**Describe the expected behavior**

`tf.print` should print out values as was specified in https://www.tensorflow.org/api_docs/python/tf/print

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

```python
import tensorflow as tf
import sys
tensor = tf.range(10) 
tf.print(tensor, output_stream=sys.stderr)
```

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by ravikyram** [comment]
@yongtang 
You can add `from __future__ import print_function` before your code then you will not see the syntax error.Please, find the gist [here.](https://colab.sandbox.google.com/gist/ravikyram/113721be2d017fecb3d6fd80c83b74b4/untitled260.ipynb).Thanks!

**Comment by yongtang** [comment]
@ravikyram Yes I missed `from __future__ import print_function` line. 👍 Thanks for the help!
