### ISSUE TITLE
[TF 2.0 API Docs] tf.GradientTape

### ISSUE THREAD

**Issue by prabindh** [tensorflow/tensorflow#33326]
## URL(s) with the issue:

https://www.tensorflow.org/api_docs/python/tf/GradientTape

### Clear description
Class members and Return values in "gradient" function not consistent with actual values in code

### Correct links
Yes
### Parameters defined
Yes
### Returns defined
Needs to be modified
gradient () :
1. Argument - unconnected_gradients: a value which can either hold 'none' or 'zero'

  Should be NONE or ZERO

2. Return values:  

In addition to the mentioned return values, If none of the provided elements in "sources" argument are being watched, the function will return None

### Raises listed and defined
Yes

### Usage example
Yes
### Submit a pull request?
Yes

**Comment by MarkDaoust** [comment]
Hi @prabindh,
 
It looks like the maintainers are only accepting more-significant Docs PRs, to reduce the overhead of tiny changes. Thanks for taking a shot. Please try again when you have more to contribute.
