### ISSUE TITLE
use tf.layers.dense as a layer ups bug

### ISSUE THREAD

**Issue by ucasiggcas** [tensorflow/tensorflow#33328]
hi,dear all,
I just wanna use the tf's dense,
and when I set tf.layers.dense as a keras layer,it ups a bug,
how to solve it ?

codes:
```
def dense(inputs):
    return tf.layers.dense(inputs,units=513,activation='relu')

x_mixed=tf.keras.Input(shape=(5, 256),dtype=tf.float32, name='input')
fc_out=tf.keras.layers.Lambda(dense)(x_mixed)

model=tf.keras.Model(inputs=x_mixed,outputs=fc_out)
model.compile(loss="mse",metrics=['mae'],optimizer='adam')
model.summary()

X=np.random.randn(1000,5,256)
y=np.random.randn(1000,5,513)
model.fit(X,y,batch_size=16,epochs=5)
```

bug：
`ValueError: Tensor conversion requested dtype float32_ref for Tensor with dtype float32: 'Tensor("Adam/dense/kernel/m/Initializer/zeros:0", shape=(256, 513), dtype=float32)'`
Thx

**Comment by ravikyram** [comment]
@ucasiggcas 
Can you please let us know the Tensorflow version you are using?.I have tried on colab with TF version 1.15.0-rc3 and was able to reproduce the issue.Please, find the gist [here](https://colab.sandbox.google.com/gist/ravikyram/bf3ed878169513cdf1ee4e4fc4269bc5/untitled270.ipynb). Thanks!

**Comment by ucasiggcas** [comment]
@ravikyram 
the tf version is 1.14.0, and installed with
`pip install tensorflow-gpu`

**Comment by ravikyram** [comment]
I have tried on colab with TF version 1.14, 1.15.0-rc3 and was able to reproduce the issue.Please, find the gist [here](https://colab.sandbox.google.com/gist/ravikyram/2493233a0c605357b9cb39a5d9f1798a/untitled270.ipynb).Thanks!

**Comment by 2696120622** [comment]
How to fix this error?

**Comment by yhliang2018** [comment]
May you try [`tf.keras.layers.Dense`](https://www.tensorflow.org/api_docs/python/tf/keras/layers/Dense?version=nightly) in TF 2.x? As  and `tf.keras.layers.*` uses reference variables by default in TF 2.x, so the compatibility between keras model and `tf.layers.*` is not guaranteed.

**Comment by jvishnuvardhan** [comment]
@ucasiggcas Based on @yhliang2018 suggestion, I updated one line in the code and the error is gone. Please check the [gist here](https://colab.sandbox.google.com/gist/jvishnuvardhan/30231da16b6ca9455e6cecf2737b4c31/untitled837.ipynb). I have used `TF1.15`. Thanks!

The line I change from `return tf.layers.dense(inputs,units=513,activation='relu')` to `return tf.keras.layers.Dense(units=513,activation='relu')(inputs)`. Thanks

I am closing this issue as it was resolved. Please feel free to open if I am mistaken. Thanks!

**Comment by ucas010** [comment]
No,
the same codes tf1.15
```
import tensorflow as tf
import numpy as np


def dense(inputs):
    #return tf.layers.dense(inputs,units=513,activation='relu')
    tf.keras.layers.Dense(units=513,activation='relu')(inputs)

x_mixed=tf.keras.Input(shape=(5, 256),dtype=tf.float32, name='input')
fc_out=tf.keras.layers.Lambda(dense)(x_mixed)

model=tf.keras.Model(inputs=x_mixed,outputs=fc_out)
model.compile(loss="mse",metrics=['mae'],optimizer='adam')
model.summary()

X=np.random.randn(1000,5,256)
y=np.random.randn(1000,5,513)
model.fit(X,y,batch_size=16,epochs=5)
```

but the error :
```
If using Keras pass *_constraint arguments to layers.
Traceback (most recent call last):
  File "D:/python36/new/tf_dense_.py", line 10, in <module>
    fc_out=tf.keras.layers.Lambda(dense)(x_mixed)
  File "D:\python36\lib\site-packages\tensorflow_core\python\keras\engine\base_layer.py", line 874, in __call__
    '(layer: ' + self.name + ').')
ValueError: A layer's `call` method should return a Tensor or a list of Tensors, not None (layer: lambda).
```
