### ISSUE TITLE
Potential error in Codelab : Learning Tensorflow 2 : Computer Vision 

### ISSUE THREAD

**Issue by Satwato** [tensorflow/tensorflow#33333]
So I was following this codelab : https://codelabs.developers.google.com/codelabs/tensorflow-lab2-computervision/index.html?index=..%2F..index#4

On slide 5 the optimizer is set to be `tf.train.AdamOptimizer()`
and it returns an error of
 `module 'tensorflow_core._api.v2.train' has no attribute 'AdamOptimizer'`
I guess it should be 
`tf.optimizers.Adam()`
?

**Comment by Satwato** [comment]
Just found another error on the same codelab
`if(logs.get('acc')>0.95):`
in the 8th slide, last chunk of code, in the myCallBack definition. 
putting logs.get('acc') on tensorflow 2.0.0 returns an error
`TypeError: '>' not supported between instances of 'NoneType' and 'float'`
changing it to logs.get('accuracy') works.

**Comment by ravikyram** [comment]
@Satwato 

How did you  navigate to this codelab page? Is this the page you are referring,  is from tensorflow official website?.Thanks!

**Comment by Satwato** [comment]
@ravikyram I got to this codelab by searching for Tensorflow on this website : https://codelabs.developers.google.com/

**Comment by jvishnuvardhan** [comment]
@Satwato Please check [this tutorial](https://www.tensorflow.org/tutorials/keras/classification) on TF website which is most updated and very similar to the codelabs tutorial. If you notice any issues the tutorial on TF website, please file bug in TF repository. Regarding the callbacks, you can replace `acc` with `accuracy` and it should work. But for more detailed guide on custom callbacks, please check [here](https://www.tensorflow.org/guide/keras/custom_callback).

If you are looking for more tutorials and guides on `tensorflow`, [here](https://www.tensorflow.org/tutorials) is the page for tutorials and [here](https://www.tensorflow.org/guide) is the page for guides. These links have everything to become an expert in TF. Thanks!

I am closing this as it is resolved. Please feel free to open a new issue when you notice any errors in tutorials on TF website. Thanks!
