### ISSUE TITLE
//tensorflow/python/autograph/pyct/static_analysis/activity_py3_test.py fails with Python2.7

### ISSUE THREAD

**Issue by kbhute-ibm** [tensorflow/tensorflow#33338]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 19.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: No
- TensorFlow installed from (source or binary): Source
- TensorFlow version (use command below): v2.0.0
- Python version: Python 2.7.15+
- Bazel version (if compiling from source): 0.26.1
- GCC/Compiler version (if compiling from source): gcc (Ubuntu 8.3.0-6ubuntu1) 8.3.0
- CUDA/cuDNN version: NA
- GPU model and memory: NA

**Describe the current behavior**
Looks like //tensorflow/python/autograph/pyct/static_analysis:activity_py3_test is newly added in TF 2.0. Following command throws this error 
```
bazel --host_jvm_args="-Xms1024m" --host_jvm_args="-Xmx2048m" test --define=tensorflow_mkldnn_contraction_kernel=0 --host_javabase="@local_jdk//:jdk" //tensorflow/python/autograph/pyct/static_analysis:activity_py3_test
```
Error:
```
File "/root/.cache/bazel/_bazel_root/efb88f6336d9c4a18216fb94287b8d97/execroot/org_tensorflow/bazel-out/k8-py3-opt/bin/tensorflow/python/autograph/pyct/static_analysis/activity_py3_test.runfiles/org_tensorflow/tensorflow/python/autograph/pyct/static_analysis/activity_py3_test.py", line 39
    nonlocal nonlocal_a
                      ^
SyntaxError: invalid syntax
```
I found [here](https://stackoverflow.com/questions/14264313/syntax-error-on-nonlocal-statement-in-python/14264325#14264325) that this issue gets resolved by upgrading Python2 to Python3. Tried the same and test passes. 

Is Python3.x recommended for building Tensorflow 2.0? I didn't see such update in Release notes for Tensorflow 2.x. Also as per [this update on Python](https://pip.pypa.io/en/latest/development/release-process/#python-2-support) Python2.7 will be deprecated in few months, are we planning to completely shift to Python 3.x?

Please guide us on this. Thanks.

**Comment by kbhute-ibm** [comment]
Adding below tests which show same behavior:

//tensorflow/python/autograph/impl:api_py3_test
//tensorflow/python/autograph/operators:py_builtins_py3_test
//tensorflow/python/autograph/pyct/static_analysis:liveness_py3_test
//tensorflow/python/autograph/pyct/static_analysis:reaching_definitions_py3_test

**Comment by mihaimaruseac** [comment]
You are trying to run python3 tests using python2 :-/

**Comment by kbhute-ibm** [comment]
Thanks @mihaimaruseac.
