### ISSUE TITLE
tf.contrib.image.transform in TF2.0

### ISSUE THREAD

**Issue by chayka** [tensorflow/tensorflow#33335]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using): 2.0
- Are you willing to contribute it (Yes/No): No

**Describe the feature and the current behavior/state.**
In TF 1.X there were nice methods [tf.contrib.image.transform()](https://www.tensorflow.org/versions/r1.14/api_docs/python/tf/contrib/image/transform) and [tf.contrib.image.compose_transforms()](https://www.tensorflow.org/versions/r1.14/api_docs/python/tf/contrib/image/compose_transforms) that allowed to perform affine transforms with an image. 

In TF 2.0 whole tf.contrib.* is dropped.

For instance, I was using those in my custom augmentation mechanisms to add rotation and shear transforms (along with all zooms, shifts, flips, etc). And in TF 2.0 I see no way to perform those.

I tried to implement such a functionality with numpy+opencv instead of TF. However when I tried injecting such a functionality to tf.dataset.map() pipeline tensors seemed not to have .nupmy() method yet.

I also found tf.keras.preprocessing.image.apply_affine_transform() which does perform affine transform on image, but according to [docs](https://www.tensorflow.org/versions/r1.14/api_docs/python/tf/keras/preprocessing/image/apply_affine_transform) it works with numpy array only.

**Will this change the current api? How?**
I guess that would be nice to port those functions form 1.14 to 2.X to: tf.image.compose_transforms() and tf.image.transform() or something. Should not affect existing API I guess.

**Who will benefit with this feature?**
Anybody who likes to perform affine transforms on image say in data augmentation step of model training.

**Any Other info.**
If I miss something and mentioned functionality can be implemented with existing API, please let me know.

**Comment by lgeiger** [comment]
`tf.contrib.image.transform` and `tf.contrib.image.compose_transform` are now part of the [`tensorflow_addons.image`](https://github.com/tensorflow/addons/blob/master/tensorflow_addons/image/README.md) module which should implement the functionality you are looking for.

**Comment by gowthamkpr** [comment]
@chayka As mentioned in the previous comment, you can refer to tensorflow_addons to find the same functions. Closing this issue as it has been resolved.

**Comment by chayka** [comment]
Thank you guys a lot! Could be a nice idea to leave a note in tf.contrib.* branch docs that some functionality is not dropped, but could be found somewhere else. Spent quite some time looking for it and still missed it. But anyway, thanks for TF2.0, great job!
