### ISSUE TITLE
tf.data pipeline on TPU slows when upgrading from v1.12 -> v1.14

### ISSUE THREAD

**Issue by zo7** [tensorflow/tensorflow#33347]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 16.04 & 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): Binary
- TensorFlow version (use command below): 1.12.0 & 1.14.0
- Python version: 3.6.8
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: N/A (TPU)
- GPU model and memory: N/A (TPU)

**Describe the current behavior**

Training a custom estimator on TPU with a `tf.data` pipeline that reads from TFRecords performs well on v1.12. Profiling with the TPU profiler shows that very little of the step time is spent waiting for input.

After upgrading to v1.14, training is slowed down, and the TPU profiler reports that much more of the step time is spent waiting for input (~67.1%). The global steps/sec falls from ~10 steps/sec to ~6 steps/sec.

Fixing deprecation warnings (e.g. not using `.make_one_shot_iterator().get_next()`) doesn't seem to help.

Our pipeline appears to follow the [`tf.data` performance guidelines](https://www.tensorflow.org/guide/data_performance) except for not using `tf.data.experimental.AUTOTUNE` -- using this parameter doesn't recover performance either.

**Describe the expected behavior**

I would not expect upgrading the library to slow down data infeed.

**Code to reproduce the issue**

Our `tf.data` pipeline looks roughly like:
```python
dataset = tf.data.TFRecordDataset(
    tf.data.Dataset.list_files(pattern, shuffle=True),
    buffer_size=(32 * 1024 * 1024),
    num_parallel_reads=8,
)
dataset = dataset.shuffle(shuffle_buffer_size) \
                 .repeat() \
                 .map(parse_fn, num_parallel_calls=8) \
                 .batch(batch_size, drop_remainder=True) \
                 .prefetch(4)
```
Tuning parameters after upgrading doesn't recover any performance, nor does using `tf.data.experimental.AUTOTUNE`.

**Other info / logs**

Here are the overview pages from the TPU profiler on TensorBoard:

TPU profiler v1.12:
![v1-12](https://user-images.githubusercontent.com/3229244/66775978-2a9f1400-ee7a-11e9-9a7c-66af8da8829d.png)

TPU profiler v1.14:
![v1-14](https://user-images.githubusercontent.com/3229244/66775984-2ecb3180-ee7a-11e9-8f77-435ce9b0236e.png)

Let me know if there's any other information that I can provide!

**Comment by oanush** [comment]
@zo7 ,
Thank you for reporting, can you please provide complete code to replicate the above issue ?

**Comment by zo7** [comment]
Sure, I can see if I can create an example to replicate the issue sometime today. Didn't want to post company code here.

**Comment by oanush** [comment]
@zo7 ,
Hi,any update on the issue ?Thanks!

**Comment by zo7** [comment]
I've been working on a minimal example to share, but I can't seem to replicate the issue with it... I'll work on it some more, but it's not clear what might be causing the slowdown.

**Comment by oanush** [comment]
@zo7 ,
Hi, no update on the minimal example yet?Thanks!

**Comment by zo7** [comment]
No, I haven't had too much time to work on this and it's unclear what's causing it...

**Comment by oanush** [comment]
@zo7 ,
I will close the issue for now, once the new information is available kindly reopen the issue. Thanks!

**Comment by zo7** [comment]
Sorry, I will reopen if I am able to reproduce.

However I will leave one last nugget: Upgrading from v1.14 -> v1.15 makes it even *worse*. Our model goes from ~10 steps/sec (v1.12) -> ~6 steps/sec (v1.14) -> ~3 steps/sec (v1.15)

<img width="1073" alt="Screen Shot 2019-11-06 at 2 49 31 PM" src="https://user-images.githubusercontent.com/3229244/68345010-35c61800-00a5-11ea-89a7-618e7ca41f05.png">

I cannot reproduce without sharing our code + data, but our experience as users upgrading the past few versions has been *terrible*.
