### ISSUE TITLE
keras optimizer `apply_gradients` arg `grads_and_vars` has wrong type in documentation

### ISSUE THREAD

**Issue by koenhelwegen** [tensorflow/tensorflow#33345]
## URL(s) with the issue:

https://github.com/tensorflow/tensorflow/blob/516c98da7b7d8526c153827c426c675a4ece9543/tensorflow/python/keras/optimizer_v2/optimizer_v2.py#L414

## Description of issue (what needs changing):

`grads_and_vars` is documented as list but is actually passed as `zip object`.

### Clear description

This can be problematic when writing custom optimizers that iterate over the `grads_and_vars` multiple times, as in that case a `zip object` will not give the intended behaviour.

**Comment by gadagashwini** [comment]
@koenhelwegen, Since the associated PR has been merged, are you happy to close if no issue persists. Thanks!

**Comment by koenhelwegen** [comment]
Hi, thanks for taking this up. PR is in a separate repo where the change from `list` to `zip object` resulted in a bug in a custom optimizer. The TF documentation is still incorrect.

**Comment by jvishnuvardhan** [comment]
@koenhelwegen Are you willing to contribute through PR? Link this issue in the PR and it will automatically closes once the PR merges. Thanks!

**Comment by koenhelwegen** [comment]
At a closer look it seems the `grads_and_vars` zip is usually converted to a list before it's passed to `apply_gradients` (e.g. [here](https://github.com/tensorflow/tensorflow/blob/1cf0898dd4331baf93fe77205550f2c2e6c90ee5/tensorflow/python/keras/optimizer_v2/optimizer_v2.py#L501), but not [here](https://github.com/tensorflow/tensorflow/blob/1cf0898dd4331baf93fe77205550f2c2e6c90ee5/tensorflow/python/keras/engine/training_eager.py#L272)), so I'm not sure if this is a documentation error or that this is a bug in `training_eager.py`.

**Comment by Saduf2019** [comment]
@koenhelwegen,
Since the associated PR has been merged,please confirm if the issue can be closed. Thanks!
