### ISSUE TITLE
ImportError: libcublas.so.9.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by shalijiang** [tensorflow/tensorflow#33359]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Centos 7
- TensorFlow installed from (source or binary): binary
- TensorFlow version: 1.6
- Python version: 2.7
- Installed using virtualenv? pip? conda?: pip
- CUDA/cuDNN version: 9.0/7
- GPU model and memory: GeForce GTX TITAN and Tesla K40c

**Describe the problem**

**Provide the exact sequence of commands / steps that you executed before running into the problem**

when "import tensorflow", will show "ImportError: libcublas.so.9.0: cannot open shared object file: No such file or directory" 

But /usr/local/cuda-9.0 is installed, and CUDA_HOME points to this path. 

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.
```

>>> "libcublas.so.9.0" in os.listdir("/usr/local/cuda-9.0/lib64")
True
>>> os.environ["CUDA_HOME"]
'/usr/local/cuda-9.0'
>>> import tensorflow
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/project/activelearning/shalijiang/anaconda2/lib/python2.7/site-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "/project/activelearning/shalijiang/anaconda2/lib/python2.7/site-packages/tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/project/activelearning/shalijiang/anaconda2/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/project/activelearning/shalijiang/anaconda2/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/project/activelearning/shalijiang/anaconda2/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/project/activelearning/shalijiang/anaconda2/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
ImportError: libcublas.so.9.0: cannot open shared object file: No such file or directory


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/install_sources#common_installation_problems

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.
```

**Comment by ravikyram** [comment]
@shalijiang 

Can you go through the below [link1 ](https://stackoverflow.com/questions/48428415/importerror-libcublas-so-9-0-cannot-open-shared-object-file) , #20569 and see [software requirements](https://www.tensorflow.org/install/gpu) and see if it helps you.Thanks!

**Comment by ravikyram** [comment]
@shalijiang 

Any updates on the issue please. Thanks!

**Comment by ravikyram** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
