### ISSUE TITLE
No module named 'tensorflow.tools.graph_transforms' in TF2.0

### ISSUE THREAD

**Issue by 1duo** [tensorflow/tensorflow#33352]
This functionality seems still [included](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/graph_transforms/README.md#strip_unused_nodes) in TensorFlow 2.0, however, it raises an error when calling.

```
% ipython
Python 3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 16:52:21) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.8.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: from tensorflow.tools.graph_transforms import TransformGraph                                                 
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-1fd86d9792e0> in <module>
----> 1 from tensorflow.tools.graph_transforms import TransformGraph

ModuleNotFoundError: No module named 'tensorflow.tools.graph_transforms'
```

TensorFlow version:

```
% pip show tensorflow
Name: tensorflow
Version: 2.0.0
Summary: TensorFlow is an open source machine learning framework for everyone.
Home-page: https://www.tensorflow.org/
Author: Google Inc.
Author-email: packages@tensorflow.org
License: Apache 2.0
Location: /Volumes/data/venv-tf2/lib/python3.7/site-packages
Requires: gast, six, tensorboard, grpcio, termcolor, tensorflow-estimator, protobuf, keras-preprocessing, keras-applications, numpy, opt-einsum, absl-py, wrapt, wheel, astor, google-pasta
Required-by: tfcoreml
```

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): macOS 10.15
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): binary pip install
- TensorFlow version (use command below): 2.0.0
- Python version: 3.7.3
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

**Comment by gowthamkpr** [comment]
Similar to the issue #30746 

Was able to reproduce this issue. Please find the gist [here](https://colab.sandbox.google.com/gist/gowthamkpr/185f73a175e6b9fec45fd91a15d83830/untitled188.ipynb)

**Comment by bmdivakar** [comment]
Facing similar issue.

Error Message..
`Python 3.6.8 (default, Oct  7 2019, 12:59:55)
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow.tools.graph_transforms
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'tensorflow.tools.graph_transforms'
`
Tensorflow Version ..
`Name: tensorflow
Version: 2.0.0
Summary: TensorFlow is an open source machine learning framework for everyone.
Home-page: https://www.tensorflow.org/
Author: Google Inc.
Author-email: packages@tensorflow.org
License: Apache 2.0
Location: /usr/local/lib/python3.6/dist-packages
Requires: tensorflow-estimator, wheel, wrapt, grpcio, tensorboard, gast, astor, termcolor, numpy, keras-preprocessing, google-pasta, six, absl-py, protobuf, keras-applications, opt-einsum
`

**Comment by bmdivakar** [comment]
Facing similar issue..

**Comment by suharshs** [comment]
This is WIA. The code is still in the repository but this code is not exposed intentionally in TF 2.0 as graphs are not central in 2.0, look to Grappler as the place for TF rewrites now.

**Comment by x10000year** [comment]
@suharshs  how to use grappler? is it automatically enabeled? i don't find any document about it.

**Comment by nuka137** [comment]
@x10000year 

Recently, the document about the graph optimization is merged to tensorlflow/doc (https://github.com/tensorflow/docs/pull/1206).
This document describes how to control behaviours of grappler.
I hope this document meets your requirement.
