### ISSUE TITLE
INFO level logs not coming in MirroredStrategy()

### ISSUE THREAD

**Issue by sayakpaul** [tensorflow/tensorflow#33361]
Hi. I am on TensorFlow 2.0 and on my local Jupyter Notebook environment. I am following [this example](https://www.tensorflow.org/tutorials/distribute/keras). When I am running the accompanying notebook Colab, the INFO level logs are getting displayed. But when I am running local, the logs are not there (although locally I am running a slightly different code) and here it is:

```python
import tensorflow as tf

strategy = tf.distribute.MirroredStrategy()

# Call the distribution scope context manager
with strategy.scope():
    # Define a model to fit the above data
    model = tf.keras.Sequential([
        tf.keras.layers.Dropout(rate=0.2, input_shape=X.shape[1:]),
        tf.keras.layers.Dense(units=64, activation='relu'),
        tf.keras.layers.Dropout(rate=0.2),
        tf.keras.layers.Dense(units=1, activation='sigmoid')
    ])
    
    # Compile the model
    model.compile(loss='binary_crossentropy',
                optimizer='adam',
                metrics=['accuracy'])
```

Any hints as to why the logs are not coming?

**Comment by ravikyram** [comment]
@sayakpaul 

Thanks for reporting the issue. Can you please provide complete code snippet to reproduce the issue in our environment.So i can check the same in Jupyter notebook and Colab for localizing the issue faster.Thanks!

**Comment by sayakpaul** [comment]
I have already provided the complete code snippet @ravikyram

**Comment by ravikyram** [comment]
@sayakpaul 
I tried reproducing the issue in colab and Jupyter notebook.However i am getting the below error message `error.NameError: name 'X' is not defined`.Thanks!

**Comment by sayakpaul** [comment]
What code are you using? You should be using the following:

```python
import tensorflow as tf

strategy = tf.distribute.MirroredStrategy()

# Call the distribution scope context manager
with strategy.scope():
    # Define a model to fit the above data
    model = tf.keras.Sequential([
        tf.keras.layers.Dropout(rate=0.2, input_shape=X.shape[1:]),
        tf.keras.layers.Dense(units=64, activation='relu'),
        tf.keras.layers.Dropout(rate=0.2),
        tf.keras.layers.Dense(units=1, activation='sigmoid')
    ])
    
    # Compile the model
    model.compile(loss='binary_crossentropy',
                optimizer='adam',
                metrics=['accuracy'])
```

**Comment by ravikyram** [comment]
@sayakpaul 
Please, find the gist [here](https://colab.sandbox.google.com/gist/ravikyram/c85e97df70f575c135350ae3029a7db2/untitled287.ipynb). Please, help me in reproducing the issue.Thanks!

**Comment by sayakpaul** [comment]
Here you go:

```python
import tensorflow as tf

strategy = tf.distribute.MirroredStrategy()

# Call the distribution scope context manager
with strategy.scope():
    # Define a model to fit the above data
    model = tf.keras.Sequential([
        tf.keras.layers.Dropout(rate=0.2, input_shape=(7,)),
        tf.keras.layers.Dense(units=64, activation='relu'),
        tf.keras.layers.Dropout(rate=0.2),
        tf.keras.layers.Dense(units=1, activation='sigmoid')
    ])
    
    # Compile the model
    model.compile(loss='binary_crossentropy',
                optimizer='adam',
                metrics=['accuracy'])
```

**Comment by sayakpaul** [comment]
@ravikyram any updates?

**Comment by ymodak** [comment]
Apologies for the delay in response. Is this still an issue?
I tried TF 2.0 and TF-Nightly versions in python interpreter (terminal), I can see the log info printed.
Can you please confirm by trying in python interpreter? Thanks!
