### ISSUE TITLE
TensorFlow source cannot be compiled with -c dbg

### ISSUE THREAD

**Issue by bas-aarts** [tensorflow/tensorflow#33360]
When compiling the TensorFlow sources (at 776b99925c1fe0d045b363f7437c21a5a9ce2357) with:
bazel build -c dbg -j 24 --config=opt //tensorflow/tools/pip_package:build_pip_package

it produces many errors like:
```
external/arm_neon_2_x86_sse/NEON_2_SSE.h:2296:30: error: selector must be an integer constant in the range 0..7
     #define _MM_INSERT_EPI16 _mm_insert_epi16
                              ^
external/arm_neon_2_x86_sse/NEON_2_SSE.h:9369:40: note: in expansion of macro '_MM_INSERT_EPI16'
 #define vld1q_lane_s16(ptr, vec, lane) _MM_INSERT_EPI16(vec, *(ptr), lane)
                                        ^~~~~~~~~~~~~~~~
external/arm_neon_2_x86_sse/NEON_2_SSE.h:12090:12: note: in expansion of macro 'vld1q_lane_s16'
     return vld1q_lane_s16(&val, vec,  lane);
```
This started when the TF build moved to C++14 compilation. It works fine with C++11.
I distilled it down to the following piece of code:
```
typedef short __v8hi __attribute__ ((__vector_size__ (16)));
extern inline __attribute__((__gnu_inline__, __always_inline__, __artificial__))
__v8hi vsetq_lane_s16(__v8hi x,const int l)
{ return __builtin_ia32_vec_set_v8hi(x,0,(l)); }
void ff(__v8hi x) { vsetq_lane_s16(x,0);}```

When compiling this with
g++ -std=c++11 x.cc -c
it compiles just fine. When compiling with
g++ -std=c++14 x.cc -c
it produces:
x.cc: In function ‘void ff(__v8hi)’:
x.cc:6:47: error: selector must be an integer constant in the range 0..7
     return __builtin_ia32_vec_set_v8hi(x,0,(l));
```

some details:
- removing the "const" from the formal argument makes C++11 fail as well
- removing the () around "l" makes c++14 pass
- int(l) in stead of (l) make c++14 pass, but (int)(l) still fails

Tried gcc 7.4.0 with glibc 2.27 on ubuntu 18.04
and gcc 5.4.0 with glibc 2.23 on ubuntu 16.04

**Comment by oanush** [comment]
@bas-aarts ,
Please provide more information on the issue like sequence of commands / steps that you executed before running into the problem?

**Comment by bas-aarts** [comment]
I just tried to build TensorFlow in debug mode:
bazel build -j 24 --config=opt -c dbg //tensorflow/tools/pip_package:build_pip_package

**Comment by angerson** [comment]
Can you please provide a complete log of `./configure` and the bazel build command you're running, starting from a fresh environment targeting the `master` branch?

**Comment by bas-aarts** [comment]
build:
bazel build -j 24 --config=opt -c dbg //tensorflow/tools/pip_package:build_pip_package

confg:
root@1204a5c05f6b:/home/baarts/tensorflow# cat .tf_configure.bazelrc
build --action_env PYTHON_BIN_PATH="/usr/bin/python"
build --action_env PYTHON_LIB_PATH="/usr/local/lib/python3.6/dist-packages"
build --python_path="/usr/bin/python"
build:xla --define with_xla_support=true
build --config=xla
build --action_env CUDA_TOOLKIT_PATH="/usr/local/cuda"
build --action_env TF_CUDA_COMPUTE_CAPABILITIES="7.0"
build --action_env LD_LIBRARY_PATH="/usr/local/cuda/extras/CUPTI/lib64:/usr/local/cuda/compat/lib:/usr/local/nvidia/lib:/usr/local/nvidia/lib64:/usr/local/lib/tensorflow"
build --action_env GCC_HOST_COMPILER_PATH="/usr/bin/gcc"
build --config=cuda
build:opt --copt=-march=native
build:opt --copt=-Wno-sign-compare
build:opt --host_copt=-march=native
build:opt --define with_default_optimizations=true
build:v2 --define=tf_api_version=2
test --flaky_test_attempts=3
test --test_size_filters=small,medium
test --test_tag_filters=-benchmark-test,-no_oss,-oss_serial
test --build_tag_filters=-benchmark-test,-no_oss
test --test_tag_filters=-gpu
test --build_tag_filters=-gpu
build --action_env TF_CONFIGURE_IOS="0"

**Comment by nouiz** [comment]
Note, this isn't fixed and the original author responded. So the status isn't right.

**Comment by nouiz** [comment]
I just saw that this file is compile `external/arm_neon_2_x86_sse/NEON_2_SSE.h`, but why the arm code is included? It probably shouldn't be included at first.  From the full error message, it seems it comes from tflite:

```
ERROR: /tensorflow/tensorflow/lite/kernels/BUILD:425:1: C++ compilation of rule '//tensorflow/lite/kernels:builtin_op_kernels' failed (Exit 1)
In file included from /usr/lib/gcc/x86_64-linux-gnu/5/include/x86intrin.h:41:0,
                 from /usr/include/x86_64-linux-gnu/c++/5/bits/opt_random.h:33,
                 from /usr/include/c++/5/random:50,
                 from /usr/include/c++/5/bits/stl_algo.h:66,
                 from /usr/include/c++/5/algorithm:62,
                 from external/gemmlowp/public/../internal/../internal/common.h:24,
                 from external/gemmlowp/public/../internal/../internal/kernel_default.h:22,
                 from external/gemmlowp/public/../internal/dispatch_gemm_shape.h:20,
                 from external/gemmlowp/public/gemmlowp.h:19,
                 from ./tensorflow/lite/kernels/cpu_backend_context.h:21,
                 from ./tensorflow/lite/kernels/internal/optimized/integer_ops/depthwise_conv.h:19,
                 from tensorflow/lite/kernels/depthwise_conv.cc:16:
external/arm_neon_2_x86_sse/NEON_2_SSE.h: In function 'void tflite::optimized_integer_ops::depthwise_conv::DepthwiseConvInitAccBuffer(int, int, const int32*, int32*)':
external/arm_neon_2_x86_sse/NEON_2_SSE.h:2297:34: error: selector must be an integer constant in the range 0..3
         #define _MM_INSERT_EPI32 _mm_insert_epi32
                                  ^
external/arm_neon_2_x86_sse/NEON_2_SSE.h:9366:40: note: in expansion of macro '_MM_INSERT_EPI32'
 #define vld1q_lane_s32(ptr, vec, lane) _MM_INSERT_EPI32(vec, *(ptr), lane)
                                        ^
external/arm_neon_2_x86_sse/NEON_2_SSE.h:12092:12: note: in expansion of macro 'vld1q_lane_s32'
     return vld1q_lane_s32(&val, vec,  lane);
            ^
external/arm_neon_2_x86_sse/NEON_2_SSE.h:2297:34: error: selector must be an integer constant in the range 0..3
         #define _MM_INSERT_EPI32 _mm_insert_epi32
                                  ^
external/arm_neon_2_x86_sse/NEON_2_SSE.h:9366:40: note: in expansion of macro '_MM_INSERT_EPI32'
 #define vld1q_lane_s32(ptr, vec, lane) _MM_INSERT_EPI32(vec, *(ptr), lane)
                                        ^
external/arm_neon_2_x86_sse/NEON_2_SSE.h:12092:12: note: in expansion of macro 'vld1q_lane_s32'
     return vld1q_lane_s32(&val, vec,  lane);
            ^
external/arm_neon_2_x86_sse/NEON_2_SSE.h: In function 'void tflite::optimized_ops::depthwise_conv::DepthwiseConvInitAccBuffer(int, int, const int32*, int32*)':
external/arm_neon_2_x86_sse/NEON_2_SSE.h:2297:34: error: selector must be an integer constant in the range 0..3
         #define _MM_INSERT_EPI32 _mm_insert_epi32
                                  ^
external/arm_neon_2_x86_sse/NEON_2_SSE.h:9366:40: note: in expansion of macro '_MM_INSERT_EPI32'
 #define vld1q_lane_s32(ptr, vec, lane) _MM_INSERT_EPI32(vec, *(ptr), lane)
                                        ^
external/arm_neon_2_x86_sse/NEON_2_SSE.h:12092:12: note: in expansion of macro 'vld1q_lane_s32'
     return vld1q_lane_s32(&val, vec,  lane);
            ^
external/arm_neon_2_x86_sse/NEON_2_SSE.h:2297:34: error: selector must be an integer constant in the range 0..3
         #define _MM_INSERT_EPI32 _mm_insert_epi32
                                  ^
external/arm_neon_2_x86_sse/NEON_2_SSE.h:9366:40: note: in expansion of macro '_MM_INSERT_EPI32'
 #define vld1q_lane_s32(ptr, vec, lane) _MM_INSERT_EPI32(vec, *(ptr), lane)
                                        ^
external/arm_neon_2_x86_sse/NEON_2_SSE.h:12092:12: note: in expansion of macro 'vld1q_lane_s32'
     return vld1q_lane_s32(&val, vec,  lane);
            ^
Target //tensorflow/tools/pip_package:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.
```

**Comment by bas-aarts** [comment]
I've implemented a workaround for this in the dbg config. Compiling with
  --config=dbg
in stead of
   --config=opt -c dbg
circumvents this issue by disabling x86 neon

closing this issue (no response for over 6 months)

**Comment by kevint324** [comment]
I got the same error on tf2.4 
It seems the bug is still there.
