### ISSUE TITLE
How to make a custom Model with a stateful LSTM

### ISSUE THREAD

**Issue by njellinas** [tensorflow/tensorflow#33371]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): The Decoder part in the official example: https://www.tensorflow.org/tutorials/text/nmt_with_attention
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- TensorFlow installed from (source or binary): pip
- TensorFlow version (use command below): 2.0.0
- Python version: 3.6.9
- CUDA/cuDNN version: 10.0
- GPU model and memory: GTX 1080Ti, 12 GB

**Describe the current behavior**
ValueError: If a RNN is stateful, it needs to know its batch size. Specify the batch size of your input tensors: 
- If using a Sequential model, specify the batch size by passing a `batch_input_shape` argument to your first layer.
- If using the functional API, specify the batch size by passing a `batch_shape` argument to your Input layer.

**Describe the expected behavior**
I want to make a custom decoder layer with a stateful LSTM and a pre-net which is a simple Dense, but I do not want to use Sequential or functional API, because I want to control with reset_states() when the LSTM states will be reset. It always shows the error above. How should I give the input shape in this custom layer?

**Code to reproduce the issue**
```python
class Decoder(Model):
    def __init__(self, dim):
        super(DecoderCell, self).__init__()
        self.input = Sequential([
            Input(batch_shape=(32, 1, num_mels)),
            Dense(128, activation='relu')
        ])

        self.rnn = LSTM(256, stateful=True)

    def call(self, x):
        x = self.input(x)

        x = self.rnn(x)

        return x
```

**Comment by oanush** [comment]
@njellinas ,This is not Build/Installation or Bug/Performance issue. Please post this kind of support questions at Stackoverflow. There is a big community to support and learn from your questions. GitHub is mainly for addressing bugs in installation and performance. Thanks!

**Comment by mattiasu96** [comment]
@njellinas Did you ask on Stackoverflow? Did you solve your problem? I have similar problem
