### ISSUE TITLE
importing tensorflow inside a function/object causes a memory leak

### ISSUE THREAD

**Issue by rggjan** [tensorflow/tensorflow#33376]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): OSX 10.15
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: No
- TensorFlow installed from (source or binary): pip install tensorflow==1.14
- TensorFlow version (use command below): 1.14.0
- Python version: 3.6.8
- Bazel version (if compiling from source): -
- GCC/Compiler version (if compiling from source): -
- CUDA/cuDNN version: -
- GPU model and memory: -

**Describe the current behavior**
When importing tensorflow from a function or object, the `import` statement somehow keeps a reference to the function and increasing it's reference count. The full `import` stacktrace is never freed, making it impossible for the object (and anything referenced from that object or function) to be freed from memory.

**Describe the expected behavior**
It should be possible to free the function calling `import tensorflow`. This is not an issue with any other imports (like `import logger`).

**Code to reproduce the issue**
```
import gc


class TFImporter:
    def __init__(self, name):
        self._name = name
        print(f"TFImporter init {self._name}")

    def get_tf(self):
        print(f"import tensorflow {self._name}")
        import tensorflow
        print(tensorflow.version.VERSION)

    def get_other_module(self):
        print(f"import logging {self._name}")
        import logging
        logging.info("Message")

    def __del__(self):
        print(f"TFImporter delete {self._name}")


def main():
    importer1 = TFImporter(1)
    importer1.get_other_module()
    del importer1
    print("importer1 deleted")

    importer2 = TFImporter(2)
    importer2.get_tf()
    del importer2
    print("importer2 deleted")

    importer3 = TFImporter(3)
    importer3.get_tf()
    del importer3
    print("importer3 deleted")

    print(f"Garbage collection: {gc.collect()}")

    print(f"Waiting for input:")
    input()


main()
```

this outputs:

```
/Users/jan/miniconda/envs/foo/bin/python /Users/jan/code/tensorflow_error.py
TFImporter init 1
import logging 1
TFImporter delete 1
importer1 deleted
TFImporter init 2
import tensorflow 2
1.14.0
importer2 deleted
TFImporter init 3
import tensorflow 3
1.14.0
TFImporter delete 3
importer3 deleted
Garbage collection: 22
Waiting for input:
foo
TFImporter delete 2

Process finished with exit code 0
```

So `importer2` is only freed after the python application finishes. Neither `gc.collect` nor deleting the object causes it to be released in python.

This is not an issue in this toy example, but `importer2` could have a reference to a large number of other objects that take considerable space in memory in reality.

Also, this only happens for the first `import`. `importer3` can be freed without issues.

**Other info / logs**
[tf_env.txt](https://github.com/tensorflow/tensorflow/files/3729501/tf_env.txt)

**Comment by martinwicke** [comment]
@annarev is this related to lazy loaders or estimator/keras integration?

**Comment by annarev** [comment]
It appears to be due to saving error when importing portpicker here:
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/framework/test_util.py#L44

We can probably save the error text instead or import portpicker inside the function that creates a cluster.

**Comment by martinwicke** [comment]
Yeah, it seems weird that we'd survive the import, only to error out later.
Let's either import it inside the cluster creation, or print the error
directly on import (but still continue), and later error with a note to
look for the earlier error.

Honestly, I think the local import is preferable in this case.
