### ISSUE TITLE
Tensorflow build error on the Macbook docker 

### ISSUE THREAD

**Issue by goooodday** [tensorflow/tensorflow#3338]
In my MacBook(using docker) has a built in Tensorflow source.
The error occurred during the build.
### Environment info

Operating System: OSX, El Capitan
Using Docker & tensor flow docker image :  tensorflow/tensorflow:latest-devel
### Steps to reproduce
1. checking bazel & update
2. download a new tensorflow source
3. ./configure   --> No GPU...
4. build bazel to pip
   --> bazel build -c opt //tensorflow/tools/pip_package:build_pip_package
### Build error

> ERROR: /tensorflow/tensorflow/core/kernels/BUILD:1694:1: C++ compilation of rule '//tensorflow/core/kernels:training_ops' failed: gcc failed: error executing command /usr/bin/gcc -U_FORTIFY_SOURCE '-D_FORTIFY_SOURCE=1' -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 -DNDEBUG -ffunction-sections ... (remaining 107 argument(s) skipped): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 4.
> gcc: internal compiler error: Killed (program cc1plus)
> Please submit a full bug report,
> with preprocessed source if appropriate.
> <img width="990" alt="2016-07-16 12 07 46" src="https://cloud.githubusercontent.com/assets/547925/16892518/445d0698-4b50-11e6-946e-36b90c2d8ea6.png">
> 
> See file:///usr/share/doc/gcc-4.8/README.Bugs for instructions.
> Target //tensorflow/tools/pip_package:build_pip_package failed to build
#### Include option(--verbose_failures) build err:

  bazel build -c opt //tensorflow/tools/pip_package:build_pip_package --verbose_failures

> ERROR: /tensorflow/tensorflow/core/kernels/BUILD:1078:1: C++ compilation of rule '//tensorflow/core/kernels:argmax_op' failed: gcc failed: error executing command
>   (cd /root/.cache/bazel/_bazel_root/68a62076e91007a7908bc42a32e4cff9/tensorflow && \
>   exec env - \
>     PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin \
>   /usr/bin/gcc -U_FORTIFY_SOURCE '-D_FORTIFY_SOURCE=1' -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 -DNDEBUG -ffunction-sections -fdata-sections '-std=c++0x' -DHAVE_CONFIG_H -iquote . -iquote bazel-out/local_linux-opt/genfiles -iquote external/protobuf -iquote bazel-out/local_linux-opt/genfiles/external/protobuf -iquote external/bazel_tools -iquote bazel-out/local_linux-opt/genfiles/external/bazel_tools -iquote external/farmhash_archive -iquote bazel-out/local_linux-opt/genfiles/external/farmhash_archive -iquote external/jpeg_archive -iquote bazel-out/local_linux-opt/genfiles/external/jpeg_archive -iquote external/png_archive -iquote bazel-out/local_linux-opt/genfiles/external/png_archive -iquote external/gif_archive -iquote bazel-out/local_linux-opt/genfiles/external/gif_archive -iquote external/highwayhash -iquote bazel-out/local_linux-opt/genfiles/external/highwayhash -iquote external/re2 -iquote bazel-out/local_linux-opt/genfiles/external/re2 -iquote external/eigen_archive -iquote bazel-out/local_linux-opt/genfiles/external/eigen_archive -iquote external/zlib_archive -iquote bazel-out/local_linux-opt/genfiles/external/zlib_archive -isystem external/protobuf/src -isystem bazel-out/local_linux-opt/genfiles/external/protobuf/src -isystem external/bazel_tools/tools/cpp/gcc3 -isystem external/farmhash_archive/farmhash-34c13ddfab0e35422f4c3979f360635a8c050260 -isystem bazel-out/local_linux-opt/genfiles/external/farmhash_archive/farmhash-34c13ddfab0e35422f4c3979f360635a8c050260 -isystem external/jpeg_archive/jpeg-9a -isystem bazel-out/local_linux-opt/genfiles/external/jpeg_archive/jpeg-9a -isystem external/png_archive/libpng-1.2.53 -isystem bazel-out/local_linux-opt/genfiles/external/png_archive/libpng-1.2.53 -isystem external/gif_archive/giflib-5.1.4/lib -isystem bazel-out/local_linux-opt/genfiles/external/gif_archive/giflib-5.1.4/lib -isystem external/highwayhash -isystem bazel-out/local_linux-opt/genfiles/external/highwayhash -isystem external/re2 -isystem bazel-out/local_linux-opt/genfiles/external/re2 -isystem third_party/eigen3 -isystem bazel-out/local_linux-opt/genfiles/third_party/eigen3 -isystem external/eigen_archive/eigen-eigen-b4fa9622b809 -isystem bazel-out/local_linux-opt/genfiles/external/eigen_archive/eigen-eigen-b4fa9622b809 -isystem external/zlib_archive/zlib-1.2.8 -isystem bazel-out/local_linux-opt/genfiles/external/zlib_archive/zlib-1.2.8 -fno-exceptions -DEIGEN_AVOID_STL_ARRAY -pthread -no-canonical-prefixes -fno-canonical-system-headers -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' '-frandom-seed=bazel-out/local_linux-opt/bin/tensorflow/core/kernels/_objs/argmax_op/tensorflow/core/kernels/argmax_op.pic.o' -MD -MF bazel-out/local_linux-opt/bin/tensorflow/core/kernels/_objs/argmax_op/tensorflow/core/kernels/argmax_op.pic.d -fPIC -c tensorflow/core/kernels/argmax_op.cc -o bazel-out/local_linux-opt/bin/tensorflow/core/kernels/_objs/argmax_op/tensorflow/core/kernels/argmax_op.pic.o): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 4.
> gcc: internal compiler error: Killed (program cc1plus)
> Please submit a full bug report,
> with preprocessed source if appropriate.
> See file:///usr/share/doc/gcc-4.8/README.Bugs for instructions.
> Target //tensorflow/tools/pip_package:build_pip_package failed to build
> INFO: Elapsed time: 3619.233s, Critical Path: 3589.94s

<img width="1246" alt="2016-07-16 2 48 52" src="https://cloud.githubusercontent.com/assets/547925/16893041/8d3c4fb8-4b64-11e6-8d8f-0557e9128b1f.png">

**Comment by Mistobaan** [comment]
can you run it again with `--verbose_failures` ? 
`bazel build -c opt //tensorflow/tools/pip_package:build_pip_package --verbose_failures`

**Comment by goooodday** [comment]
@Mistobaan No, I don't try again ....
Now, I'm running again. Thank U!!!

**Comment by goooodday** [comment]
Updated a error log.
How do I bug report.

**Comment by jmchen-g** [comment]
@caisq Could you take a look at this please?

**Comment by trevyn** [comment]
This gcc internal compiler error appears to be an out-of-memory event; I experienced this using Ubuntu 14.04.5 in a VMware Fusion VM on Mac OS X with the default 1024MB of memory assigned. Increasing VM memory to 8192MB yielded a successful build.

**Comment by gunan** [comment]
Looks like the there is an explanation here.
Closing the issue for now. Please reopen if the above suggestion wont resolve the problem for you.

Also, the error message suggests you should report a gcc bug, so I am assuming this is a gcc bug.
