### ISSUE TITLE
[TF2.0] tf.make_ndarray() not functional

### ISSUE THREAD

**Issue by steph-en-m** [tensorflow/tensorflow#33389]
* environment: colab
* python3
* TF 2.0

Running ```tf.make_ndarray()``` throws an attribute error ```AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'tensor_shape' ```

As per the documentation [here](https://www.tensorflow.org/api_docs/python/tf/make_ndarray)
it's supposed to create a numpy array with the same shape and content as the input tensor.
I've also tried with lazy eval mode but the same attribute error is thrown. could it be a bug??

```python
a=tf.constant([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
x = tf.make_ndarray(a)
print(x)
```
Full error log:
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-4-039c2e207451> in <module>()
      1 a=tf.constant([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
----> 2 tf.make_ndarray(a)
      3 #print(x)

/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/tensor_util.py in MakeNdarray(tensor)
    576 
    577   """
--> 578   shape = [d.size for d in tensor.tensor_shape.dim]
    579   num_elements = np.prod(shape, dtype=np.int64)
    580   tensor_dtype = dtypes.as_dtype(tensor.dtype)

AttributeError: 'Tensor' object has no attribute 'tensor_shape'
```

**Comment by lc0** [comment]
@steph-en-m I am not sure what exactly you are trying to do, but 2.0 allows to just run .numpy on a tensor

```
a = tf.constant([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
a_n = a.numpy()

print(f"{a_n.shape} - {a.shape}")
```
that gives you 
```
(2, 2, 3) - (2, 2, 3)
```

**Comment by lc0** [comment]
I think I found the use-case you might have under 2.0

In case you are trying to form a request for TensorFlow serving you would need to `tf. make_tensor_proto` and from there you can convert back with mentioned your function above.

Something like this 
![image](https://user-images.githubusercontent.com/775466/66874275-f2e3b980-efaa-11e9-99fe-e74aecb3ff51.png)

**Comment by ravikyram** [comment]
@steph-en-m 

Have a look on @lc0 's suggestion and let us know if that helps to resolve the issue. Thanks!

**Comment by steph-en-m** [comment]
Thanks @lc0 your second suggestion explains/resolves my issue.

**Comment by das-ankur** [comment]
I use the same suggestion of @lc0 but in my case I am having trouble to save the model. I am getting error like this: 
raise TypeError("Expected any non-tensor type, got a tensor instead.")
TypeError: Expected any non-tensor type, got a tensor instead.
