### ISSUE TITLE
TypeError: reduce() missing 1 required positional argument: 'per_replica_value'

### ISSUE THREAD

**Issue by sourcecode369** [tensorflow/tensorflow#33388]
```
> with mirrored_strategy.scope():
>     model = tf.keras.Sequential([tf.keras.layers.Dense(1, input_shape=(1,))])
>     optimizer = tf.keras.optimizers.Adam(learning_rate=0.001)
> 
> global_batch_size = 10 * mirrored_strategy.num_replicas_in_sync
> 
> def input_fn():
>     dataset = tf.data.Dataset.from_tensors(([1.], [1.])).repeat(1000).batch(
>     global_batch_size)
>     dist_dataset = mirrored_strategy.experimental_distribute_dataset(dataset)
>     return dist_dataset
>     
> dataset = input_fn()
> 
> @tf.function
> def train_step(dist_inputs):
>     def step_fn(inputs):
>         features, labels = inputs
>         with tf.GradientTape() as tape:
>             logits = model(features)
>             cross_entropy = tf.nn.softmax_cross_entropy_with_logits(
>                 logits=logits, labels=labels
>             )
>             loss = tf.reduce_sum(cross_entropy) * (1.0 / global_batch_size)
>         grads = tape.gradient(loss, model.trainable_variables)
>         optimizer.apply_gradients(list(zip(grads, model.trainable_variables)))
>         return cross_entropy
> 
>     per_example_losses = mirrored_strategy.experimental_run_v2(
>         step_fn, args=(dist_inputs,)
>     )
>     mean_loss = mirrored_strategy.reduce(
>         tf.distribute.ReduceOp.MEAN, per_example_losses, axis=0
>     )    
>     return mean_loss
> 
> with mirrored_strategy.scope():
>     for input in dataset:
>         train_step(inputs)
```

Its one of the code snippets from the distributed strategy guide for custom training loops.
Im getting this, 

TypeError:TypeError: reduce() missing 1 required positional argument: 'per_replica_value' 

but then when I ran the same code today morning it was working perfectly.

**Comment by oanush** [comment]
@sourcecode369 ,
Thank you for reporting, Can you please provide complete code to reproduce the above issue ? Also let us know TF version being used.

**Comment by sourcecode369** [comment]
I'm using TensorFlow 2.0, there is some kind of bug. I am getting this error again by trying out a different code. 

```
import tensorflow as tf
print("TensorFlow version: ", tf.__version__)
```

```
tf.debugging.set_log_device_placement(True)
tf.config.set_soft_device_placement(True)

gpus = tf.config.experimental.list_physical_devices("GPU")
if gpus:
    try:
        tf.config.experimental.set_virtual_device_configuration(
            gpus[0],
            [tf.config.experimental.VirtualDeviceConfiguration(memory_limit=1024),
             tf.config.experimental.VirtualDeviceConfiguration(memory_limit=1024)]
        )
        logical_gpus = tf.config.experimental.list_logical_devices("GPU")
        print("Physical GPUs", len(gpus), "Logical GPUs", len(logical_gpus))
    except RuntimeError as e:
        print(e)
else:
    print("No GPUs found.")
```

```
tf.debugging.set_log_device_placement(True)
tf.config.set_soft_device_placement(True)

mirrorerd_strategy = tf.distribute.MirroredStrategy(cross_device_ops=tf.distribute.ReductionToOneDevice)
with mirrorerd_strategy.scope():
    inputs = tf.keras.layers.Input(shape=(1,))
    predictions = tf.keras.layers.Dense(1)(inputs)
    model = tf.keras.models.Model(inputs=inputs, outputs=predictions)
    model.compile(optimizer="adam", loss="binary_crossentropy",metrics=["accuracy"])
```

I am getting the same error again when I try to run the above code. Please help me out. I have confirmed twice that Im using TensorFlow 2.0 on Google Colaboratory and have installed by, 

> pip install --upgrade tensorflow

 and my gpu runtime is active.


For the above one, that is pretty much the complete code. Just that there was one more line of code above where I create an object of tf.distribute.MirroredStrategy by using the below code,

`mirrorerd_strategy = tf.distribute.MirroredStrategy(cross_device_ops=tf.distribute.ReductionToOneDevice)
`


> Below I am pasting the complete error message that I am receiving when trying to run both of the code. Hope this helps,
> 
> INFO:tensorflow:Error reported to Coordinator: reduce() missing 1 required positional argument: 'per_replica_value'
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/training/coordinator.py", line 297, in stop_on_exception
>     yield
>   File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/distribute/mirrored_strategy.py", line 190, in _call_for_each_replica
>     **merge_kwargs)
>   File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/utils/metrics_utils.py", line 118, in merge_fn_wrapper
>     result = distribution.experimental_local_results(merge_fn)[0](*args)
>   File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/metrics.py", line 368, in result
>     return math_ops.div_no_nan(self.total, self.count)
>   File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/util/dispatch.py", line 180, in wrapper
>     return target(*args, **kwargs)
>   File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/ops/math_ops.py", line 1111, in div_no_nan
>     x = ops.convert_to_tensor(x, name="x")
>   File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/ops.py", line 1184, in convert_to_tensor
>     return convert_to_tensor_v2(value, dtype, preferred_dtype, name)
>   File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/ops.py", line 1242, in convert_to_tensor_v2
>     as_ref=False)
>   File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/ops.py", line 1296, in internal_convert_to_tensor
>     ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
>   File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/distribute/values.py", line 1271, in _tensor_conversion_sync_on_read
>     return var._dense_var_to_tensor(dtype=dtype, name=name, as_ref=as_ref)  # pylint: disable=protected-access
>   File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/distribute/values.py", line 1261, in _dense_var_to_tensor
>     self.get(), dtype=dtype, name=name, as_ref=as_ref)
>   File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/distribute/values.py", line 322, in get
>     return self._get_cross_replica()
>   File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/distribute/values.py", line 1237, in _get_cross_replica
>     self, axis=None)
>   File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/distribute/distribute_lib.py", line 805, in reduce
>     return self._extended._reduce(reduce_op, value)  # pylint: disable=protected-access
>   File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/distribute/distribute_lib.py", line 1436, in _reduce
>     device_util.current() or "/device:CPU:0"))[0]
>   File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/distribute/mirrored_strategy.py", line 703, in _reduce_to
>     reduce_op, value, destinations=destinations)
> TypeError: reduce() missing 1 required positional argument: 'per_replica_value'

---------------------------------------------------------------------------
```
TypeError                                 Traceback (most recent call last)
<ipython-input-18-2e63ea6eaf5a> in <module>()
      7     predictions = tf.keras.layers.Dense(1)(inputs)
      8     model = tf.keras.models.Model(inputs=inputs, outputs=predictions)
----> 9     model.compile(optimizer="adam", loss="binary_crossentropy",metrics=["accuracy"])
```

**27 frames**
```
/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/distribute/mirrored_strategy.py in _reduce_to(self, reduce_op, value, destinations)
    701           reduce_op, self._device_map, value, destinations)
    702     return self._get_cross_device_ops().reduce(
--> 703         reduce_op, value, destinations=destinations)
    704 
    705   def _batch_reduce_to(self, reduce_op, value_destination_pairs):
```

### TypeError: reduce() missing 1 required positional argument: 'per_replica_value'


Please help me out.

**Comment by sourcecode369** [comment]
is there anybody who can help me out with this?

**Comment by sourcecode369** [comment]
I finally was able to solve this for the keras by removing the metrics argument, though I dont understand why thats the case. 
However for custom tensorflow training loop the error still persists. I guess the error is somewhere here,

> per_example_losses = mirrored_strategy.experimental_run_v2(
>         step_fn, args=(dist_inputs,)
>     )
>     mean_loss = mirrored_strategy.reduce(
>         tf.distribute.ReduceOp.MEAN, per_example_losses, axis=0
>     )

I'll try to look into it and report back.

**Comment by sourcecode369** [comment]
I finally solved it.

**Comment by anj-s** [comment]
sourcecode369@ can you tell us how you solved the issue? I was able to repro the bug with the given cross_device_ops argument.

**Comment by sourcecode369** [comment]
> sourcecode369@ can you tell us how you solved the issue? I was able to repro the bug with the given cross_device_ops argument.

Yup the problem I found was due toi `tf.distribute.MirroredStrategy(cross_device_ops=tf.distribute.ReductionToOneDevice)` and rather the proper definition would be,
`tf.distribute.MirroredStrategy(cross_device_ops=tf.distribute.ReductionToOneDevice())`. Forgot to put the parenthesis due to which a default argument was not getting passed.
