### ISSUE TITLE
hub.Module("https://tfhub.dev/google/elmo/2")` doesn't work.

### ISSUE THREAD

**Issue by fairy-of-9** [tensorflow/tensorflow#33385]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- TensorFlow-hub version: 0.6.0
- TensorFlow version: 1.14.0
- Python version: 3.7.4

**Describe the current behavior**
The module load has not been completed and is waiting indefinitely.

**Code to reproduce the issue**
`elmo = hub.Module("https://tfhub.dev/google/elmo/2")`

**Comment by gowthamkpr** [comment]
@fairy-of-9 I am closing this issue as it has already been updated [here](https://github.com/tensorflow/hub/issues/385) and it belongs to tensorflow/hub repo and you will get an expedited answer. Thanks!
