### ISSUE TITLE
Desynchronized zipped datasets when using tf.data.experimental.ignore_errors

### ISSUE THREAD

**Issue by scharron** [tensorflow/tensorflow#33383]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
Linux Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
na
- TensorFlow installed from (source or binary):
binary
- TensorFlow version (use command below):
v2.0.0-rc2-26-g64c3d38 2.0.0
- Python version:
Python 3.7.4
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
cuda 10.0
- GPU model and memory:
P100 / 16GB

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**

When an error is caught using the `tf.data.experimental.ignore_errors` on a zipped dataset, only the faulty dataset drops an element. The datasets are therefore desynchronized.

**Describe the expected behavior**

Datasets should stay synchronized by dropping an element from both datasets.

**Code to reproduce the issue**

```
good_dataset = tf.data.Dataset.from_tensor_slices([1., 2., 0., 4.])
bad_dataset = good_dataset.map(lambda x: tf.debugging.check_numerics(1. / x, "error"))

dataset = tf.data.Dataset.zip((bad_dataset, good_dataset))
dataset = dataset.apply(tf.data.experimental.ignore_errors())

for bad, good in dataset:
    print(float(good), float(bad))

1.0 1.0
2.0 0.5
0.0 0.25
```

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by gadagashwini** [comment]
I could reproduce the issue with Tf 2.0.0. Please see the gist [here](https://colab.sandbox.google.com/gist/gadagashwini/48e54114ef599b79cd9d09e4a7fb9736/untitled201.ipynb). Thanks!

**Comment by jsimsa** [comment]
This is working as intended. The good dataset dropped `0.0` while the bad dataset dropped `1 / 0.0`.

@scharron What output would you expect for your example?

**Comment by scharron** [comment]
@jsimsa Oops sorry I went too fast, I fixed the code to reproduce

(if zipping `good` then `bad` it works, but the reverse does not)

**Comment by yongtang** [comment]
I think the issue is that, in case of zip, when error or end-of-sequence encountered the remaining components are not "flushed out".  So out-of-sync happens when ignore_errors is in play.

Created a PR #33887, think this could fix the issue.

**Comment by scharron** [comment]
Thanks !

Wouldn't it be possible and useful to also issue a warning if the `tf.data.experimental.ignore_errors` is applied to any Dataset used as input to `tf.data.Dataset.zip`.

This could also result in datasets desynchronization if any of the zipped datasets drops any item, and in my opinion shouldn't be the behaviour of a `zip` function.
