### ISSUE TITLE
Bugs about dequantize operator calculation formula in SCALED mode

### ISSUE THREAD

**Issue by BluePaladin** [tensorflow/tensorflow#33382]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 16.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: -
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 1.14.0
- Python version: Python 2.7.12
- Bazel version (if compiling from source): -
- GCC/Compiler version (if compiling from source): -
- CUDA/cuDNN version: -
- GPU model and memory: -

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
Using numpy to simulate the calculation formula in SCALED mode of the dequantize operator in tensorflow, you can't get the correct result.
```
# This is the method of dequantize operator in tensorflow kernel code written by me.
if mode == "SCALED":
    num_bits = size * 8
    if dtype == "uint8":
        limit_min = 0
        limit_max = 1 << num_bits - 1
        scalar_factor = max_range / limit_max
    if dtype in ("int8", "int32"):
        limit_min = -(1 << (num_bits - 1))
        limit_max = -1 * limit_min - 1
        scalar_factor = max(min_range / limit_min, max_range / limit_max)
    res = input_tensor * scalar_factor
```
```
# This is the code of dequantize operator in tensorflow kernel code written by c++.
else if (mode_ == QUANTIZE_MODE_SCALED) {
    const float scale_factor =
        std::numeric_limits<T>::min() == 0
            ? (max_range / std::numeric_limits<T>::max())
            : std::max(min_range / std::numeric_limits<T>::min(),
                       max_range / std::numeric_limits<T>::max());
    const auto& input_tensor = input.flat<T>();
    output->flat<float>() =
    input_tensor.template cast<int>().template cast<float>() * scale_factor;
}
```
**Describe the expected behavior**
the code written by me should get the same result as the tensorflow c++ code.
However, I got much different result.

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.
```
# Then, I write the code that can get the same result as the actual result of the tensorflow
if mode == "SCALED":
    m = max_range  # float32
    if dtype == "int8" or dtype == "int16" or dtype == "int32":
        # min&max fixed is float32
        [min_fixed, max_fixed] = [-((1 << (num_bits - 1)) - 1), (1 << (num_bits - 1))-1]
        s = 2.0 * m / (max_fixed - min_fixed)
    if dtype == "uint8" or dtype == "uint16":
        [min_fixed, max_fixed] = [0, (1 << num_bits) - 1]
        s = m / (max_fixed - min_fixed)
    z = input_tensor * s
```
In my code, the _input_min_range_ param is redundant.

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by oanush** [comment]
@BluePaladin ,
Thank you for reporting, can you please provide complete code to reproduce the issue reported 
above ? Thanks!

**Comment by BluePaladin** [comment]
[dequantize_data.txt](https://github.com/tensorflow/tensorflow/files/3751297/dequantize_data.txt)

**Comment by oanush** [comment]
@BluePaladin ,
When tried running the code I got `UnboundLocalError: local variable 'z_offset' referenced before assignment`, can you please check ?Thanks

**Comment by BluePaladin** [comment]
@oanush, I am very sorry to offer a wrong code. Please try this one,  thank you!
[dequantize_data.txt](https://github.com/tensorflow/tensorflow/files/3761531/dequantize_data.txt)

**Comment by BluePaladin** [comment]
@ymodak Bro, is there any progress in this issue now?

**Comment by ymodak** [comment]
Apologies BluePaladin this issue fell through the cracks. 
Is this still an issue? If yes then can you please try testing it with latest TF (2.2) version?
Thanks!
