### ISSUE TITLE
TensorFlow documentation should be associated with the applicable specific versions of TensorFlow

### ISSUE THREAD

**Issue by nbro** [tensorflow/tensorflow#33391]
## URL(s) with the issue:

Please provide a link to the documentation entry, for example:
https://www.tensorflow.org/guide/gpu

## Description of issue (what needs changing):

I was reading this documentation page https://www.tensorflow.org/guide/gpu, but it is **unclear** which TensorFlow version the documentation applies to. Especially now that a stable version of TF 2 has been released, it is important to clarify which TF version the documentation refers to. 

On the top bar of the linked webpage, there is a menu called API, where you can select the API you are interested in. Right now, the sub-menu corresponding to the specific version of TF I am reading is not even highlighted, so I don't know if I am reading the documentation for TF 1 or 2. To confuse people even further, even though I think I am reading the documentation for TF 2, in another top bar, it is written `TF 1`. 

Given that I am confused, another person can also be confused, so the documentation needs to be clarified. So, I suggest that every documentation page is associated (**in a very clear way**) with all applicable TF versions.

**Comment by nikitamaia** [comment]
Closing this issue now since the TF guide is for TF2 and there is a separate TF1 tab in the navigation that redirects to the TF1 docs repo
![Screen Shot 2021-02-12 at 5 16 36 PM](https://user-images.githubusercontent.com/16965738/107832476-22990200-6d56-11eb-97aa-c79200458dbf.png)
