### ISSUE TITLE
python -c "import tensorflow as tf; print(tf.contrib.eager.num_gpus())" from docs doesn't work with 

### ISSUE THREAD

**Issue by rlewkowicz** [tensorflow/tensorflow#33396]
python -c "import tensorflow as tf; print(tf.contrib.eager.num_gpus())" Doesn't work from https://www.tensorflow.org/install/source
with tf2

**Comment by oanush** [comment]
@rlewkowicz ,
Hi, The reason for that is `contrib` has been removed from TF 2.0, please use command 
`print("Num GPUs Available: ", len(tf.config.experimental.list_physical_devices('GPU')))` . Refer this [link](https://www.tensorflow.org/guide/gpu) for more info on the same.Thanks!
