### ISSUE TITLE
Docker Image with a pre-built Tensorflow-gpu with a compute capability 3.0 GPUs

### ISSUE THREAD

**Issue by dmitryr117** [tensorflow/tensorflow#33390]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using): 2.0

**Describe the feature and the current behavior/state.**
Currently if someone has an older GPU - they have to build from source. However this is time-consuming and error-prone. I tried building it as per instructions with no luck.

**Will this change the current api? How?**

**Who will benefit with this feature?**
 If there was a docker image for legacy GPU CUDA support - it would help many people who still have a legacy GPU cards to make use of them to train their models without having to dash out hundreds of dollars on a new GPU card right away. Building from source is very time consuming and error prone.

**Any Other info.**

**Comment by angerson** [comment]
We're unable to provide official support for this, unfortunately.

**Comment by D1abloRUS** [comment]
@dmitryr117 You can use https://puzl.ee so as not to buy a new gpu

**Comment by tilakrayal** [comment]
@dmitryr117 
Is this still an issue?
Could you please update TensorFlow to the latest stable version v.2.6 and let us know if you are facing the same error. Thanks!
