### ISSUE TITLE
AttributeError: 'list' object has no attribute 'op' when calling SparseCategoricalCrossentropy

### ISSUE THREAD

**Issue by netw0rkf10w** [tensorflow/tensorflow#33394]
**Describe the current behavior**
When running the following code in the [documentation](https://www.tensorflow.org/api_docs/python/tf/keras/losses/SparseCategoricalCrossentropy) of `SparseCategoricalCrossentropy`:

```
cce = tf.keras.losses.SparseCategoricalCrossentropy()
loss = cce(
  [0, 1, 2],
  [[.9, .05, .05], [.5, .89, .6], [.05, .01, .94]])
print('Loss: ', loss.numpy())  # Loss: 0.3239
```

I obtained the following error:

> ---------------------------------------------------------------------------
> AttributeError                            Traceback (most recent call last)
> <ipython-input-2-e7331c659215> in <module>()
>       3 loss = cce(
>       4   [0, 1, 2],
> ----> 5   [[.9, .05, .05], [.5, .89, .6], [.05, .01, .94]])
>       6 print('Loss: ', loss.numpy())  # Loss: 0.3239
> 
> 3 frames
> /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/backend.py in sparse_categorical_crossentropy(target, output, from_logits, axis)
>    4397   if not from_logits:
>    4398     if (isinstance(output, (ops.EagerTensor, variables_module.Variable)) or
> -> 4399         output.op.type != 'Softmax'):
>    4400       epsilon_ = _constant_to_tensor(epsilon(), output.dtype.base_dtype)
>    4401       output = clip_ops.clip_by_value(output, epsilon_, 1 - epsilon_)
> 
> AttributeError: 'list' object has no attribute 'op'

**Comment by yongtang** [comment]
Added a PR #33406 for the fix.

**Comment by jvishnuvardhan** [comment]
@netw0rkf10w The above PR will fix the issue for you. In the mean time you can provide converted tensors of `y_pred` and `y_true`  as follows. Thanks!
`loss = cce(
  tf.convert_to_tensor([0, 1, 2]),
  tf.convert_to_tensor([[.9, .05, .05], [.5, .89, .6], [.05, .01, .94]]))`

**Comment by netw0rkf10w** [comment]
@jvishnuvardhan Thanks a lot!

**Comment by ilyarudyak** [comment]
Still doesn't work.

> ---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-21-8338a7552986> in <module>()
----> 1 sce(y_true, y_pred)

/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tensorflow_core/python/keras/losses.py in __call__(self, y_true, y_pred, sample_weight)
    124         y_true, y_pred, sample_weight)
    125     with K.name_scope(scope_name or self.__class__.__name__), graph_ctx:
--> 126       losses = self.call(y_true, y_pred)
    127       return losses_utils.compute_weighted_loss(
    128           losses, sample_weight, reduction=self._get_reduction())

/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tensorflow_core/python/keras/losses.py in call(self, y_true, y_pred)
    219       y_pred, y_true = tf_losses_util.squeeze_or_expand_dimensions(
    220           y_pred, y_true)
--> 221     return self.fn(y_true, y_pred, **self._fn_kwargs)
    222 
    223   def get_config(self):

/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tensorflow_core/python/keras/losses.py in sparse_categorical_crossentropy(y_true, y_pred, from_logits, axis)
    976 def sparse_categorical_crossentropy(y_true, y_pred, from_logits=False, axis=-1):
    977   return K.sparse_categorical_crossentropy(
--> 978       y_true, y_pred, from_logits=from_logits, axis=axis)
    979 
    980 

/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tensorflow_core/python/keras/backend.py in sparse_categorical_crossentropy(target, output, from_logits, axis)
   4528   if not from_logits:
   4529     if (isinstance(output, (ops.EagerTensor, variables_module.Variable)) or
-> 4530         output.op.type != 'Softmax'):
   4531       epsilon_ = _constant_to_tensor(epsilon(), output.dtype.base_dtype)
   4532       output = clip_ops.clip_by_value(output, epsilon_, 1 - epsilon_)

AttributeError: 'list' object has no attribute 'op'

**Comment by jvishnuvardhan** [comment]
@ilyarudyak Can you please create a new issue and provide a standalone code to reproduce the issue?  Please ping me in that issue. Thanks!

**Comment by Ekberjan** [comment]
I'm getting `AttributeError: 'list' object has no attribute 'op'` when I try to get the output node name of a loaded model as follows:

```
model = tf.keras.models.load_model('test_model.h5')
output_names = model.outputs.op.name
```

My Tensorflow version is: 2.5.0
