### ISSUE TITLE
Eager mode not being disabled tf 1.14.0

### ISSUE THREAD

**Issue by shashankg7** [tensorflow/tensorflow#33407]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version (use command below):
- Python version:
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**

**Describe the expected behavior**

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

Trying out example from Tensorflow Probability with the following code:

```
import tensorflow as tf
import tensorflow_probability as tfp
import numpy as np

tfd = tfp.distributions
dtype = np.float32

with tf.Session(graph=tf.Graph()) as sess:
  # Set up random seed for the optimizer
  tf.set_random_seed(42)
  true_mean = dtype([0, 0, 0])
  true_cov = dtype([[1, 0.25, 0.25], [0.25, 1, 0.25], [0.25, 0.25, 1]])
  # Loss is defined through the Cholesky decomposition
  chol = tf.linalg.cholesky(true_cov)

  var_1 = tf.Variable(name='var_1', initial_value=[1., 1.])
  var_2 = tf.Variable(name='var_2', initial_value=[1.])

  def loss_fn():
    var = tf.concat([var_1, var_2], axis=-1)
    loss_part = tf.linalg.cholesky_solve(chol, tf.expand_dims(var, -1))
    return tf.linalg.matvec(loss_part, var, transpose_a=True)

  # Set up the learning rate with a polynomial decay
  step = tf.Variable(0, dtype=tf.int64)
  starter_learning_rate = .3
  end_learning_rate = 1e-4
  decay_steps = 1e4
  learning_rate = tf.compat.v1.train.polynomial_decay(
      starter_learning_rate,
      step,
      decay_steps,
      end_learning_rate,
      power=1.)

  # Set up the optimizer
  optimizer_kernel = tfp.optimizer.StochasticGradientLangevinDynamics(
      learning_rate=learning_rate, preconditioner_decay_rate=0.99)
  optimizer_kernel.iterations = step
  optimizer = optimizer_kernel.minimize(loss_fn, var_list=[var_1, var_2])

  # Number of training steps
  training_steps = 5000
  # Record the steps as and treat them as samples
  samples = [np.zeros([training_steps, 2]), np.zeros([training_steps, 1])]
  sess.run(tf.compat.v1.global_variables_initializer())
  for step in range(training_steps):
    sess.run(optimizer)
    sample = [sess.run(var_1), sess.run(var_2)]
    samples[0][step, :] = sample[0]
    samples[1][step, :] = sample[1]

  samples_ = np.concatenate(samples, axis=-1)
  sample_mean = np.mean(samples_, 0)
  print('sample mean', sample_mean)

```
Getting following error:

```
File "/Users/shashank.gupta/miniconda2/lib/python2.7/site-packages/tensorflow/python/keras/optimizer_v2/optimizer_v2.py", line 318, in minimize
    loss, var_list=var_list, grad_loss=grad_loss)
  File "/Users/shashank.gupta/miniconda2/lib/python2.7/site-packages/tensorflow/python/keras/optimizer_v2/optimizer_v2.py", line 351, in _compute_gradients
    tape.watch(var_list)
  File "/Users/shashank.gupta/miniconda2/lib/python2.7/site-packages/tensorflow/python/eager/backprop.py", line 816, in watch
    for t in nest.flatten(tensor):
AttributeError: 'RefVariable' object has no attribute '_id'

```
Looks like eager mode is enabled. Have added a command to disable it still it's getting activated.

**Comment by oanush** [comment]
Issue replicating for TF-1.14, please find the [gist](https://colab.sandbox.google.com/gist/oanush/3bb01b691f398c4e0763ee69609b00bc/33407.ipynb) of colab.

**Comment by rmothukuru** [comment]
@shashankg7,
The problem might not be because of Eager Execution because, when I executed the command, `tf.executing_eagerly()`, it resulted in `False`. So, the problem might be something else. 

Are you just executing One of the Examples of Tensorflow Probability. If so,can you please let us know which example are you trying out from Tensorflow Probability, so that we can dig deeper, and if needed, change the Example as well, accordingly. Thanks!

**Comment by shashankg7** [comment]
@rmothukuru 

I am trying an example from here: https://www.tensorflow.org/probability/api_docs/python/tfp/optimizer/StochasticGradientLangevinDynamics

**Comment by jvishnuvardhan** [comment]
@shashankg7 Thanks for filing this issue. I was able to reproduce even with `TF1.15`. Error is coming from this line in the code.
`optimizer = optimizer_kernel.minimize(loss_fn, var_list=[var_1, var_2])`
I am not familiar with `tfp`. May be it is better to raise an issue in the `tfp` repo. Thanks!

**Comment by jvishnuvardhan** [comment]
@shashankg7 I think this is a stale issue. Please note that there are no upgrades to TF1.x unless there is any security related issue. So, please use TF2.x. I have used `TF2.3` and I was able to run the code without any issue. Also, note that I did  update your code in order to run it in TF2.3. Thanks!

Please take a look at the [gist here](https://colab.research.google.com/gist/jvishnuvardhan/3f8a43e8a76d7d3fa66ecf3478891c5a/33407.ipynb).

Please verify once and close the issue. Thanks !
