### ISSUE TITLE
TensorFlow Lite: TensorListFromTensor, TensorListReserve, TensorListStack, While

### ISSUE THREAD

**Issue by vcarpani** [tensorflow/tensorflow#33416]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Arch Linux
- TensorFlow installed from (source or binary): Binaries from pacman
- TensorFlow version (or github SHA if from source): 2.0.0

**Provide the text output from tflite_convert**

```
Some of the operators in the model are not supported by the standard TensorFlow Lite runtime and are not recognized by TensorFlow. If you have a custom implementation for them you can disable this error with --allow_custom_ops, or by setting allow_custom_ops=True when calling tf.lite.TFLiteConverter(). Here is a list of builtin operators you are using: ADD, CONCATENATION, CONV_2D, EXPAND_DIMS, FILL, LOGISTIC, MAXIMUM, MAX_POOL_2D, MINIMUM, MUL, PACK, PAD, RELU, RESHAPE, RESIZE_NEAREST_NEIGHBOR, SHAPE, STRIDED_SLICE, SUB, TILE, TRANSPOSE. Here is a list of operators for which you will need custom implementations: TensorListFromTensor, TensorListReserve, TensorListStack, While.

```

The model is very similar to https://github.com/fizyr/keras-retinanet.

I am converting with target specs `[tf.lite.OpsSet.TFLITE_BUILTINS, tf.lite.OpsSet.SELECT_TF_OPS]`, so my problem could be solved by adding TensorListFromTensor, TensorListReserve, TensorListStack, While to the whitelist [here](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/delegates/flex/whitelisted_flex_ops.cc) and use the standard tensorflow implementation.

**Comment by hzk7287** [comment]
Is it OK to just add TensorListFromTensor, TensorListReserve, TensorListStack, While to the whitelist .  Should I build it from source to get a binary version?  Just add these operators to whitelist and I don't do anything else?  These operators will use standard tensorflow implementation automatically？

**Comment by haozha111** [comment]
Hi,

Sorry for late reply. Can you try out our new TF Lite converter by setting:
converter.experimental_new_converter = True 

Please use the tf-nightly pip package so that you can get this working.

Thanks.

**Comment by hzk7287** [comment]
> Hi,
> 
> Sorry for late reply. Can you try out our new TF Lite converter by setting:
> converter.experimental_new_converter = True
> 
> Please use the tf-nightly pip package so that you can get this working.
> 
> Thanks.

Thanks for you reply.  I have solved it. please keep working on it. It is really a nice framework. By the way, tf1 is very diffcult to use, but tf2.0 is much bettter.

**Comment by hzk7287** [comment]
Thanks for you reply.  I have solved it. please keep working on it. It is really a nice framework. By the way, tf1 is very diffcult to use, but tf2.0 is much bettter.

**Comment by 2696120622** [comment]
> **System information**
> 
> * OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Arch Linux
> * TensorFlow installed from (source or binary): Binaries from pacman
> * TensorFlow version (or github SHA if from source): 2.0.0
> 
> **Provide the text output from tflite_convert**
> 
> ```
> Some of the operators in the model are not supported by the standard TensorFlow Lite runtime and are not recognized by TensorFlow. If you have a custom implementation for them you can disable this error with --allow_custom_ops, or by setting allow_custom_ops=True when calling tf.lite.TFLiteConverter(). Here is a list of builtin operators you are using: ADD, CONCATENATION, CONV_2D, EXPAND_DIMS, FILL, LOGISTIC, MAXIMUM, MAX_POOL_2D, MINIMUM, MUL, PACK, PAD, RELU, RESHAPE, RESIZE_NEAREST_NEIGHBOR, SHAPE, STRIDED_SLICE, SUB, TILE, TRANSPOSE. Here is a list of operators for which you will need custom implementations: TensorListFromTensor, TensorListReserve, TensorListStack, While.
> ```
> 
> The model is very similar to https://github.com/fizyr/keras-retinanet.
> 
> I am converting with target specs `[tf.lite.OpsSet.TFLITE_BUILTINS, tf.lite.OpsSet.SELECT_TF_OPS]`, so my problem could be solved by adding TensorListFromTensor, TensorListReserve, TensorListStack, While to the whitelist [here](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/delegates/flex/whitelisted_flex_ops.cc) and use the standard tensorflow implementation.

I am trying to convert EfficientDet in https://github.com/xuannianz/EfficientDet, which is based on fizyr/keras-retinanet in https://github.com/fizyr/keras-retinanet.
My tensorflow is 1.15.0.
I have converted the model to tflite.When call interpreter.allocate_tensors(), I still get the same error as you said.
My code as follows.
custom_objects = {
'BatchNormalization': layers_new.BatchNormalization,
'swish' : efficientnet.get_swish(backend=keras.backend,layers=keras.layers,models=keras.models,utils=keras.utils),
'FixedDropout' : efficientnet.get_dropout(backend=keras.backend,layers=keras.layers,models=keras.models,utils=keras.utils),
'wBiFPNAdd' : layers_new.wBiFPNAdd,
'PriorProbability' : initializers.PriorProbability,
'RegressBoxes' : layers_new.RegressBoxes,
'FilterDetections' : layers_new.FilterDetections,
'ClipBoxes' : layers_new.ClipBoxes,
'_smooth_l1' : losses.smooth_l1(),
'_focal' : losses.focal(),
}
input_shapes = {'input_2':[None,768,768,3],'input_5':[None,184140,4]}
tf.enable_control_flow_v2()
converter = tf.lite.TFLiteConverter.from_keras_model_file('E:/object_detection/EfficientDet-region_anchor_opt_mbconv-head-ckpts/inference_ckpts/ckpts_B0_image-size-768/mbconv-se-head_1e-5_unfreeze-backbone_freeze-bn/csv_04_0.6736_0.7484.h5',
custom_objects=custom_objects,
input_shapes=input_shapes,
)
converter.experimental_new_converter = True
converter.allow_custom_ops=True
tflite_model = converter.convert()
open("E:/object_detection/EfficientDet-region_anchor_opt_mbconv-head-ckpts/tflites/ckpts_B0_image-size-768/mbconv-se-head_1e-5_unfreeze-backbone_freeze-bn/csv_04_0.6736_0.7484.tflite", "wb").write(tflite_model)
interpreter = tf.lite.Interpreter(model_path="E:/object_detection/EfficientDet-region_anchor_opt_mbconv-head-ckpts/tflites/ckpts_B0_image-size-768/mbconv-se-head_1e-5_unfreeze-backbone_freeze-bn/csv_04_0.6736_0.7484.tflite")
interpreter.allocate_tensors()
`
And the error is about TensorListFromTensor as follows.
`
RuntimeError                              Traceback (most recent call last)
<ipython-input-13-ca8eb7ec6089> in <module>()
      1 # interpreter = tf.lite.Interpreter(model_content=tflite_model)
----> 2 interpreter.allocate_tensors()
      3 # help(tf.lite.Interpreter)

~\AppData\Roaming\Python\Python36\site-packages\tensorflow_core\lite\python\interpreter.py in allocate_tensors(self)
    242   def allocate_tensors(self):
    243     self._ensure_safe()
--> 244     return self._interpreter.AllocateTensors()
    245 
    246   def _safe_to_run(self):

~\AppData\Roaming\Python\Python36\site-packages\tensorflow_core\lite\python\interpreter_wrapper\tensorflow_wrap_interpreter_wrapper.py in AllocateTensors(self)
    104 
    105     def AllocateTensors(self):
--> 106         return _tensorflow_wrap_interpreter_wrapper.InterpreterWrapper_AllocateTensors(self)
    107 
    108     def Invoke(self):

RuntimeError: Encountered unresolved custom op: TensorListFromTensor.Node number 710 (TensorListFromTensor) failed to prepare.
`

I am new to tflite.Could you share your custom implementations: TensorListFromTensor, TensorListReserve, TensorListStack, While. Thanks a lot!

**Comment by gunjanddave** [comment]
@hzk7287 Can you please help that How you have resolved it ?

**Comment by hzk7287** [comment]
> @hzk7287 Can you please help that How you have resolved it ?

take a look at https://github.com/tensorflow/tensorflow/issues/33490 
I use tensorflow2.0

**Comment by padoremu** [comment]
As a summary, here is a minimal example for tensorflow 2.0 with an RNN that produced the same error, including one line from the solution mentioned by @hzk7287 in #33490:

adding `converter.allow_custom_ops = True` was enough to solve the problem in my case.

```python
import tensorflow as tf

model = tf.keras.Sequential()

model.add(tf.keras.layers.Input(shape=(1, 1,)))

cell = tf.keras.layers.GRUCell(10)

model.add(tf.keras.layers.RNN(cell))

converter = tf.lite.TFLiteConverter.from_keras_model(model)

converter.allow_custom_ops = True # does the trick
#converter.experimental_new_converter = True # does not help

tflite_model = converter.convert()
```

**Comment by padoremu** [comment]
According to the [RNN Lite conversion documentation](https://www.tensorflow.org/lite/convert/rnn), only `static_rnn` without `sequence_length` is supported by Tensorflow Lite. According to the [static_rnn documentation](https://www.tensorflow.org/versions/r1.15/api_docs/python/tf/nn/static_rnn), `keras.layers.RNN(cell, unroll=True)` is the equivalent in Tensorflow 2.

So I added `unroll=True` and it works. However, unfortunately, the model does not work for Tensorflow Lite Micro.

```python
import tensorflow as tf

model = tf.keras.Sequential()

model.add(tf.keras.layers.Input(shape=(1, 1,)))

cell = tf.keras.layers.GRUCell(10)

model.add(tf.keras.layers.RNN(cell, unroll=True))

converter = tf.lite.TFLiteConverter.from_keras_model(model)

tflite_model = converter.convert()

# for testing if operations are implemented by Tensorflow Lite
interpreter = tf.lite.Interpreter(model_content=tflite_model)
interpreter.allocate_tensors()
interpreter.invoke()
```

**Comment by pietermarsman** [comment]
I had a similar error as above using tensorflow 2.2:

```
error: failed to legalize operation 'tf.TensorListReserve'
```

and

```
error: requires element_dtype to be 1-bit/8-bit/16-bit/32-bit/64-bit integer or 16-bit/32-bit/64-bit float type during TF Lite transformation pass
```

I fixed it by using:

```python
converter = TFLiteConverter.from_saved_model(model_dir)
converter.experimental_new_converter = False
converter.optimizations = [tf.lite.Optimize.OPTIMIZE_FOR_SIZE]
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS, tf.lite.OpsSet.SELECT_TF_OPS]
converter.allow_custom_ops=True
tflite_model = converter.convert()
```

Compared to the fix by @hzk7287 in https://github.com/tensorflow/tensorflow/issues/33490#issuecomment-544847214, this also disables the new experimental converter.
