### ISSUE TITLE
Specifying output_shape is not working in tf.keras Lambda Layer

### ISSUE THREAD

**Issue by dennis-ec** [tensorflow/tensorflow#33422]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.0.0
- Python version: 3.7.3
- CUDA/cuDNN version: 10.0/7

**Describe the current behavior**
When creating a keras Model using a lambda function with specified output shape, the shape is not assigned to the resulting tensor: 
dense_net from the example below:
`<tf.Tensor 'lambda_6/Identity:0' shape=(None, None, None) dtype=float32>`
If used before another layer like Dense the error appears:
`ValueError: The last dimension of the inputs to `Dense` should be defined. Found `None`.`

**Describe the expected behavior**
dense_net should have shape information:
`<tf.Tensor 'lambda_6/Identity:0' shape=(None, 10, 5) dtype=float32>`

**Code to reproduce the issue**
```
from tensorflow.keras.layers import Input, Dense, Lambda
from tensorflow.keras.models import Model
from tensorflow.keras.backend import to_dense

test_input = Input((10, 5), sparse=True)
dense_net = Lambda(to_dense, output_shape=(10, 5))(test_input)
test_net = Dense(50)(dense_net)
```

**Comment by dennis-ec** [comment]
Edit: Found a workaround:

```
from tensorflow.keras.layers import Input, Dense, Lambda, Layer, Reshape
from tensorflow.keras.models import Model
from tensorflow.keras.backend import to_dense

test_input = Input((10, 5), sparse=True)
dense_net = Lambda(to_dense)(test_input)
reshape_net = Reshape((10, 5))(dense_net)
test_net = Dense(50)(reshape_net)
```

Bug still remains though.

**Comment by oanush** [comment]
Issue replicating for TF-2.0, please find the [gist](https://colab.sandbox.google.com/gist/oanush/2071cc1a42c3c1991d99da279c98b051/33422.ipynb) for the same.Thanks!

**Comment by dennis-ec** [comment]
Trying a custom Layer instead of the Lambda Layer results in the same error:
```
class ToDenseLayer(Layer):
    def __init__(self, out_shape: int):
        super(ToDenseLayer, self).__init__()
        self.out_shape = out_shape

    def call(self, inputs, **kwargs):
        return tf.sparse.to_dense(inputs)

    def compute_output_shape(self, input_shape):
        return None, None, self.out_shape
```

**Comment by gowthamkpr** [comment]
`output_shape` in the Lambda Layer  is used to help Keras do shape inference when in eager execution (or otherwise when shape information is not available), but it does not override TF shape inference on tensors, so it does not affect the tensor.shape attribute of the outputs.

To set the shape of a symbolic tensor with partial shape information, you should use the `set_shape` method.

**Comment by mantelllo** [comment]
Received this error in TF 2.4.1. Used keras Lambda with tf.squeeze and `output_shape` defined, but got the error within next layer which is Dense. I checked internals of sequential model, it did not infer output shape of the Lambda layer (`output_tensor` is
`<KerasTensor: shape=<unknown> dtype=float32 (created by layer 'lambda')>`). Now I look for "clean" solution not to speak about the workarounds.

My question - when `output_shape` is defined, and inference for output shape is unsuccessful, can the `output_shape` defined by user be used?
