### ISSUE TITLE
TPU/Colab auth to google cloud bucket failing

### ISSUE THREAD

**Issue by anhmeow** [tensorflow/tensorflow#33426]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Colab
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 1.15rc
- Python version: 3.6
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory: TPU

**Describe the current behavior**
Calling this code on a TPU notebook on colab generate this issue :
```
from google.colab import auth
auth.authenticate_user()
```

WARNING:tensorflow:
The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
  * https://github.com/tensorflow/io (for I/O related ops)
If you depend on functionality not listed there, please file an issue.

---------------------------------------------------------------------------
InternalError                             Traceback (most recent call last)
/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/client/session.py in _do_call(self, fn, *args)
   1364     try:
-> 1365       return fn(*args)
   1366     except errors.OpError as e:

9 frames
/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/client/session.py in _run_fn(feed_dict, fetch_list, target_list, options, run_metadata)
   1349       return self._call_tf_sessionrun(options, feed_dict, fetch_list,
-> 1350                                       target_list, run_metadata)
   1351 

/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/client/session.py in _call_tf_sessionrun(self, options, feed_dict, fetch_list, target_list, run_metadata)
   1442                                             fetch_list, target_list,
-> 1443                                             run_metadata)
   1444 

InternalError: From /job:tpu_worker/replica:0/task:0:
The filesystem registered under the 'gs://' scheme was not a tensorflow::RetryingGcsFileSystem*.
	 [[{{node GcsConfigureCredentials}}]]

During handling of the above exception, another exception occurred:

InternalError                             Traceback (most recent call last)
<ipython-input-3-1f759c1655bd> in <module>()
      1 from google.colab import auth
----> 2 auth.authenticate_user()

/usr/local/lib/python3.6/dist-packages/google/colab/auth.py in authenticate_user(clear_output)
    155         with open(_get_adc_path()) as auth_info:
    156           tf.contrib.cloud.configure_gcs(
--> 157               sess, credentials=_json.load(auth_info))
    158   if _check_adc():
    159     return

/usr/local/lib/python3.6/dist-packages/tensorflow_core/contrib/cloud/python/ops/gcs_config_ops.py in configure_gcs(session, credentials, block_cache, device)
    180     with ops.device(device):
    181       return configure(credentials, block_cache)
--> 182   return configure(credentials, block_cache)
    183 
    184 

/usr/local/lib/python3.6/dist-packages/tensorflow_core/contrib/cloud/python/ops/gcs_config_ops.py in configure(credentials, block_cache)
    169       placeholder = array_ops.placeholder(dtypes.string)
    170       op = gen_gcs_config_ops.gcs_configure_credentials(placeholder)
--> 171       session.run(op, feed_dict={placeholder: credentials})
    172     if block_cache:
    173       op = gen_gcs_config_ops.gcs_configure_block_cache(

/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/client/session.py in run(self, fetches, feed_dict, options, run_metadata)
    954     try:
    955       result = self._run(None, fetches, feed_dict, options_ptr,
--> 956                          run_metadata_ptr)
    957       if run_metadata:
    958         proto_data = tf_session.TF_GetBuffer(run_metadata_ptr)

/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/client/session.py in _run(self, handle, fetches, feed_dict, options, run_metadata)
   1178     if final_fetches or final_targets or (handle and feed_dict_tensor):
   1179       results = self._do_run(handle, final_targets, final_fetches,
-> 1180                              feed_dict_tensor, options, run_metadata)
   1181     else:
   1182       results = []

/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/client/session.py in _do_run(self, handle, target_list, fetch_list, feed_dict, options, run_metadata)
   1357     if handle is None:
   1358       return self._do_call(_run_fn, feeds, fetches, targets, options,
-> 1359                            run_metadata)
   1360     else:
   1361       return self._do_call(_prun_fn, handle, feeds, fetches)

/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/client/session.py in _do_call(self, fn, *args)
   1382                     '\nsession_config.graph_options.rewrite_options.'
   1383                     'disable_meta_optimizer = True')
-> 1384       raise type(e)(node_def, op, message)
   1385 
   1386   def _extend_graph(self):

InternalError: From /job:tpu_worker/replica:0/task:0:
The filesystem registered under the 'gs://' scheme was not a tensorflow::RetryingGcsFileSystem*.
	 [[node GcsConfigureCredentials (defined at /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/ops.py:1748) ]]

**Describe the expected behavior**
Auth must work

**Code to reproduce the issue**
```
from google.colab import auth
auth.authenticate_user()
```

**Comment by anhmeow** [comment]
It works on GPU/CPU mode

**Comment by FrederikWA** [comment]
It seems to be an issue with the Tensorflow version < 2.x. I had the same error with 1.13.1 but changing to Tensorflow 2.0.0 solved the issue.

**Comment by anhmeow** [comment]
With tensorflow 2.0.0, i've got the following error : 
```
AttributeError                            Traceback (most recent call last)
<ipython-input-1-131e482caf09> in <module>()
      2 
      3 from google.colab import auth
----> 4 auth.authenticate_user()

/usr/local/lib/python3.6/dist-packages/google/colab/auth.py in authenticate_user(clear_output)
    154       with tf.compat.v1.Session('grpc://{}'.format(colab_tpu_addr)) as sess:
    155         with open(_get_adc_path()) as auth_info:
--> 156           tf.contrib.cloud.configure_gcs(
    157               sess, credentials=_json.load(auth_info))
    158   if _check_adc():

AttributeError: module 'tensorflow' has no attribute 'contrib'
```

**Comment by anhmeow** [comment]
So far as a workaround, i skip the google auth, just comment the two lines : 
```
from google.colab import auth
auth.authenticate_user()
```

when ever a call (like model.fit) required access to a bucket, it generates me a message like service-XYZ@cloud-tpu.iam.gserviceaccount.com doesn't have access to gs path.

I just add this account as a 'reader' of the gs and it works.

**Comment by muxgt** [comment]
For me it doesn't show account name, just says 'Anonymous caller':
`"message": "Anonymous caller does not have storage.objects.get access to...`

**Comment by kurnianggoro** [comment]
i got similar problem yesterday but it is work now, colab team said they fixed the problem few hours ago

**Comment by anhmeow** [comment]
i confirm, it's solved !
