### ISSUE TITLE
Can I export a gpu-trained model to a cpu-only machine for serving/evaluation?

### ISSUE THREAD

**Issue by 3rduncle** [tensorflow/tensorflow#3343]
I trained a model on a GPU machine.
When l load such model on a cpu-only machine, I get the error below.
![](https://raw.githubusercontent.com/3rduncle/DeepNLP/master/error.png)

Thank you for any suggestions!

**Comment by jmchen-g** [comment]
@vrv Could you take a look at this please? Do we have such support now? Thanks.

**Comment by vrv** [comment]
Yup, you can pass tf.ConfigProto(allow_soft_placement=True) to the tf.Session if you really want to ignore device placement directives in the graph.  I'm not a huge fan of using this option (I'd rather the graph be rewritten to strip out the device fields explicitly), but that should work.

**Comment by vrv** [comment]
Also, in the future, StackOverflow is the right place to ask these questions.
