### ISSUE TITLE
GraphKeys.BIASES variables present in losses.get_regularization_losses()

### ISSUE THREAD

**Issue by pisiiki** [tensorflow/tensorflow#33446]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes.
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04.
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 1.14 GPU
- Python version: 3.6
- CUDA/cuDNN version: 10.2
- GPU model and memory: 1060 ti

**Describe the current behavior**

All variables, including biases are added to regularization losses (not only weights) within a tf.variable_scope with a regularizer.

**Describe the expected behavior**

I find this behavior very strange. As far as I know only weights should be added to the l1/l2 losses list. Even if some of the losses resolve to zero later (doesn't seem the case). I asume this is by design, however this has caused me tons of confusion in the past and forces me to manually pass the regularizer everywhere. Please point me in the right direction if I'm missing something here, because I find this quite odd.

**Code to reproduce the issue**

```
import tensorflow.compat.v1 as tf
import tensorflow.contrib.layers as tf_c_l

with tf.Session() as sess:
    t0 = tf.placeholder(dtype=tf.float32, shape=(20, 10,))

    reg = tf_c_l.l1_l2_regularizer()
    with tf.variable_scope('test', regularizer=reg):
        v2 = tf.get_variable('test', shape=(20, 10), collections=[tf.GraphKeys.BIASES])
        layer = tf_c_l.fully_connected(t0, num_outputs=10)

    print('Bias Variables:')
    for i in tf.get_collection(tf.GraphKeys.BIASES):
        print('{} {}'.format(i.shape.as_list(), i.name))

    print()

    print('Regularization losses:')
    for i in tf.losses.get_regularization_losses():
        print('{} {}'.format(i.shape.as_list(), i.name))
```

**Other info / logs**

```
Bias Variables:
[20, 10] test/test:0

Regularization losses:
[] test/test/Regularizer/l1_l2_regularizer:0
[] test/fully_connected/weights/Regularizer/l1_l2_regularizer:0
[] test/fully_connected/biases/Regularizer/l1_l2_regularizer:0
```

**Comment by ravikyram** [comment]
I have tried on colab with TF version 1.14, 1.15.0-rc3 and was able to reproduce the issue.Please, find the gist [here](https://colab.sandbox.google.com/gist/ravikyram/f1d2d75f051cfde366dcfd0bbb3e5719/untitled286.ipynb). Thanks!

**Comment by jvishnuvardhan** [comment]
@pisiiki Is this still an issue for you? Can you please try latest versions and let us know whether the error persists or not. Thanks!

Please feel free to close if this was already resolved for you. Thanks!
