### ISSUE TITLE
Unable to run train.py / model_main.py

### ISSUE THREAD

**Issue by RockOrSomething** [tensorflow/tensorflow#33442]
**System information**
- Windows 10
- TensorFlow installed via pip - I've tried 1.5, 1.8, 1.9, and 2.0 - all yield different error messages
- Python 3.7.4 installed, 3.5 in virtual environment
- Using conda too
- CUDA/cuDNN: N/A
- GPU model and memory: N/A, CPU only

Consistently getting error message when trying to execute train.py or model_main.py.  The latter always returns "no module named pycocotools."

The train.py error depends on the version of Tensorflow I try, but it's always "module tensorflow has no attribute '[something]'"  For example, 'contrib,' or 'experimental'.

I'm using this command: `python` model_main.py --logtostderr --train_dir=training/ `--pipeline_config_path=training/faster_rcnn_inception_v2_pets.config`

I also tried porting the train.py to v2, with no change.

Full traceback: 
`Traceback (most recent call last):
  File "train.py", line 49, in <module>
    from object_detection.builders import dataset_builder
  File "C:\tensorflow1\models\research\object_detection\builders\dataset_builder.py", line 27, in <module>
    from object_detection.data_decoders import tf_example_decoder
  File "C:\tensorflow1\models\research\object_detection\data_decoders\tf_example_decoder.py", line 32, in <module>
    slim_example_decoder = tf.contrib.slim.tfexample_decoder
AttributeError: module 'tensorflow' has no attribute `'contrib'``

HUGE thanks for looking at this - I'm not a professional programmer, just a hobbyist trying to get better.  I appreciate the help in solving it, and I'm very open to education to help me understand the 'why' behind these problems!

**Comment by oanush** [comment]
@RockOrSomething ,
Hello, `AttributeError: module 'tensorflow' has no attribute 'contrib'` is faced because `contrib` is removed from latest TF-2.0 version, you need find alternatives for that using [this](https://github.com/tensorflow/addons) link. Hence you need to modify code according to TF1.X and TF2.X versions.
Can you please provide the `train.py `and `model_main.py `files or gist of colab which you are trying to execute so that we can replicate the issue?Thanks!

**Comment by RockOrSomething** [comment]
Sure, here they are.  
[training scripts.zip](https://github.com/tensorflow/tensorflow/files/3741168/training.scripts.zip)

Originals can be found here:
[https://github.com/EdjeElectronics/TensorFlow-Object-Detection-API-Tutorial-Train-Multiple-Objects-Windows-10](https://github.com/EdjeElectronics/TensorFlow-Object-Detection-API-Tutorial-Train-Multiple-Objects-Windows-10)

I'll have a look at that link and try to find an alternative.

**Comment by oanush** [comment]
@RockOrSomething ,
did you get chance to check the link and modify the code? 
Also as this question is not a bug or feature request better asked on [StackOverflow](http://stackoverflow.com/questions/tagged//tensorflow) . There is also a larger community that reads questions there.

**Comment by unixist** [comment]
Running basically the same `model_main.py` command I get:

```
Traceback (most recent call last):
  File "model_main.py", line 26, in <module>
    from object_detection import model_lib
  File "C:\tensorflow1\models\research\object_detection\model_lib.py", line 27, in <module>
    from object_detection import eval_util
  File "C:\tensorflow1\models\research\object_detection\eval_util.py", line 40, in <module>
    slim = tf.contrib.slim
AttributeError: module 'tensorflow' has no attribute 'contrib'
```

**Comment by oanush** [comment]
@RockOrSomething ,
Any update on the issue ?Thanks!

**Comment by RockOrSomething** [comment]
@oanush, I'm closing this one out for the moment.  I have to take a leave of absence due for the rest of the year, and after that I'm going to try this entire process again on a fresh image, new hardware.  If the issue persists, I'll run it to ground on StackExchange and report back here!

**Comment by Keyrainn** [comment]
is there any workaround ?

**Comment by danpetlin** [comment]
Hi there, also trying to figure out how to resolve the same issue. I would highly appreciate If someone can recommend an addon which allows an updated TF2 code to be run smoothly without "contrib"

**Comment by nandinib1999** [comment]
Has anyone been able to find a workaround?

**Comment by RockOrSomething** [comment]
Project is on pause for me - catching up in other areas until the new year.

**Comment by unixist** [comment]
I'm still troubleshooting this.

**Comment by veonua** [comment]
any clues what to do with slim package on tf2 ?

**Comment by staciewow** [comment]
also facing the same issue. 
```
    slim = tf.contrib.slim
AttributeError: module 'tensorflow' has no attribute 'contrib'
```

**Comment by tanmay1994** [comment]
Hello @oanush , Could you please help me with the issue in my train.py model ? I have tried a hell lot of stuffs and still blooming around for a solution. 
Please help me if you can. I'll be obliged. (AttributeError: module 'tensorflow' has no attribute 'contrib'). 
Here is my code:
[train.zip](https://github.com/tensorflow/tensorflow/files/4076931/train.zip)

**Comment by oanush** [comment]
> Hello @oanush , Could you please help me with the issue in my train.py model ? I have tried a hell lot of stuffs and still blooming around for a solution.
> Please help me if you can. I'll be obliged. (AttributeError: module 'tensorflow' has no attribute 'contrib').
> Here is my code:
> [train.zip](https://github.com/tensorflow/tensorflow/files/4076931/train.zip)

@tanmay1994 ,
From the error log I see that you are using code which is 1.x compatible and not 2.x. You must be using 2.x tensorflow version to run the code, `contrib` is depreciated in tf-2.x version. Please refer this[ add-on link ](https://github.com/tensorflow/addons)and modify the code for 2.x.

**Comment by thekillertoaster** [comment]
Can confirm i'm getting the same problem with train.py
