### ISSUE TITLE
Tensorboard is failing to parse tfevents

### ISSUE THREAD

**Issue by bpajusco** [tensorflow/tensorflow#3344]
GitHub issues are for bugs / installation problems / feature requests.  
For general support from the community, see [StackOverflow](https://stackoverflow.com/questions/tagged/tensorflow).
To make bugs and feature requests more easy to find and organize, we close issues that are deemed
out of scope for GitHub Issues and point people to StackOverflow.

For bugs or installation issues, please provide the following information.
The more information you provide, the more easily we will be able to offer
help and advice.

### Environment info
Operating System:
Ubuntu 16.04
Installed version of CUDA and cuDNN: 
(please attach the output of `ls -l /path/to/cuda/lib/libcud*`):
No Cuda
If installed from binary pip package, provide:

1. Which pip package you installed.
2. The output from `python -c "import tensorflow; print(tensorflow.__version__)"`.

'0.9.0'
If installed from sources, provide the commit hash:

### Steps to reproduce
1.
2.
3.

### What have you tried?
1.I've followed the instructions on README and verified that tensorboard is pointing to the right directory and the log files are there

### Logs or other output that would be helpful
(If logs are large, please upload as attachment).
As requested, the log file is supplied below
[log.zip](https://github.com/tensorflow/tensorflow/files/367328/log.zip)

**Comment by jmchen-g** [comment]
@danmane Could you take a look at this please?

**Comment by danmane** [comment]
Can you run `tensorboard --inspect --logdir=XXXX` and report what it says?

**Comment by bpajusco** [comment]
Here is the output from the --inspect command


======================================================================
Processing event files... (this can take a few minutes)
======================================================================

Found event files in:
/home/bruno/Documents/Machine_Learning/Tensorflow/TensorFlow-Examples/notebooks/tmp/tensorflow_logs

These tags are in 
/home/bruno/Documents/Machine_Learning/Tensorflow/TensorFlow-Examples/notebooks/tmp/tensorflow_logs:
audio -
histograms -
images -
scalars
    xentropy_mean
======================================================================

Event statistics for 
/home/bruno/Documents/Machine_Learning/Tensorflow/TensorFlow-Examples/notebooks/tmp/tensorflow_logs:
audio -
graph
    first_step           0
    last_step            0
    max_step             0
    min_step             0
    num_steps            1
    outoforder_steps     []
histograms -
images -
scalars
    first_step           10
    last_step            650
    max_step             650
    min_step             10
    num_steps            65
    outoforder_steps     []
sessionlog:checkpoint -
sessionlog:start -
sessionlog:stop -
======================================================================

**Comment by danmane** [comment]
Hmm, TensorBoard should display events when loaded against that directory, can you try again? I just inspected the logs you uploaded, and they contain no scalar summaries, so I think perhaps the situation has changed between when you filed the issue and uploaded logs, and when you ran the inspect command.

**Comment by bpajusco** [comment]
Here it is. Looks pretty similar to me anyway


======================================================================
Processing event files... (this can take a few minutes)
======================================================================

Found event files in:
/home/bruno/Documents/Machine_Learning/Tensorflow/TensorFlow-Examples/notebooks/tmp/tensorflow_logs

These tags are in 
/home/bruno/Documents/Machine_Learning/Tensorflow/TensorFlow-Examples/notebooks/tmp/tensorflow_logs:
audio -
histograms -
images -
scalars
    xentropy_mean
======================================================================

Event statistics for 
/home/bruno/Documents/Machine_Learning/Tensorflow/TensorFlow-Examples/notebooks/tmp/tensorflow_logs:
audio -
graph
    first_step           0
    last_step            0
    max_step             0
    min_step             0
    num_steps            1
    outoforder_steps     []
histograms -
images -
scalars
    first_step           10
    last_step            650
    max_step             650
    min_step             10
    num_steps            65
    outoforder_steps     []
sessionlog:checkpoint -
sessionlog:start -
sessionlog:stop -
======================================================================

**Comment by danmane** [comment]
No, I mean can you verify that nothing is showing up in TensorBoard UI when loaded on that directory?

**Comment by danmane** [comment]
To be clear: in the --inspect output you show, TensorBoard discovers scalar summaries, which I expect it would display. In the original log files you uploaded, there are no scalar summaries (and --inspect confirms that). So something has changed since you posted this issue.

**Comment by bpajusco** [comment]
Thanks for the clarification and the instructions. As you can see, I'm a 
Tensorflow noob. You're right that everything shows up as expected now 
and I'm really puzzled why it does since I changed nothing in the 
graph/scalars or images but it seems to be working fine. I'm obviously 
mocking things up here and there but I have no idea how; in other words, 
I'm quite dangerous at this stage since I clearly don't know enough how 
to operate Tensorflow.

Thanks for you help
