### ISSUE TITLE
WARNING:tensorflow:Entity <function layers at 0x7fdeb05e6d08> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: If not matching a CFG node, must be a block statement: <gast.gast.ImportFrom object at 0x7fde56634b38>

### ISSUE THREAD

**Issue by cfwin** [tensorflow/tensorflow#33449]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): centos7
- TensorFlow installed from (source or binary):
- TensorFlow version (use command below): 1.15.0
- Python version: 3.7.4
- Bazel version (if compiling from source): 1.0.0
- GCC/Compiler version (if compiling from source):4.8.5 
- CUDA/cuDNN version: 10.0/7.60
- GPU model and memory: 2080ti/11GB

**Describe the current behavior**
tensor2tensor 1.14.1 
t2t-trainer 

PROBLEM=translate_ende_wmt32k
MODEL=transformer
HPARAMS=transformer_base_single_gpu
t2t-trainer \
  --data_dir=$DATA_DIR \
  --problem=$PROBLEM \
  --model=$MODEL \
  --hparams_set=$HPARAMS \
  --output_dir=$TRAIN_DIR

**Other info / logs / WARNING logs**

WARNING:tensorflow:Entity <function layers at 0x7fe5fa758d08> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: If not matching a CFG node, must be a block statement: <gast.gast.ImportFrom object at 0x7fe60c8ffc50>
W1017 12:48:28.307721 140626233849664 ag_logging.py:146] Entity <function layers at 0x7fe5fa758d08> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: If not matching a CFG node, must be a block statement: <gast.gast.ImportFrom object at 0x7fe60c8ffc50>
WARNING:tensorflow:From /opt/anaconda3/envs/tensorflow-gpu/lib/python3.6/site-packages/tensor2tensor/layers/common_layers.py:3077: The name tf.layers.Dense is deprecated. Please use tf.compat.v1.layers.Dense instead.

WARNING:tensorflow:From /opt/anaconda3/envs/tensorflow-gpu/lib/python3.6/site-packages/tensor2tensor/utils/bleu_hook.py:151: py_func (from tensorflow.python.ops.script_ops) is deprecated and will be removed in a future version.
Instructions for updating:
tf.py_func is deprecated in TF V2. Instead, there are two
    options available in V2.
    - tf.py_function takes a python function which manipulates tf eager
    tensors instead of numpy arrays. It's easy to convert a tf eager tensor to
    an ndarray (just call tensor.numpy()) but having access to eager tensors
    means `tf.py_function`s can use accelerators such as GPUs as well as
    being differentiable using a gradient tape.
    - tf.numpy_function maintains the semantics of the deprecated tf.py_func
    (it is not differentiable, and manipulates numpy arrays). It drops the
    stateful argument making all functions stateful.

W1017 12:52:31.947059 140626233849664 deprecation.py:323] From /opt/anaconda3/envs/tensorflow-gpu/lib/python3.6/site-packages/tensor2tensor/utils/bleu_hook.py:151: py_func (from tensorflow.python.ops.script_ops) is deprecated and will be removed in a future version.
Instructions for updating:
tf.py_func is deprecated in TF V2. Instead, there are two
    options available in V2.
    - tf.py_function takes a python function which manipulates tf eager
    tensors instead of numpy arrays. It's easy to convert a tf eager tensor to
    an ndarray (just call tensor.numpy()) but having access to eager tensors
    means `tf.py_function`s can use accelerators such as GPUs as well as
    being differentiable using a gradient tape.
    - tf.numpy_function maintains the semantics of the deprecated tf.py_func
    (it is not differentiable, and manipulates numpy arrays). It drops the
    stateful argument making all functions stateful.

**Comment by ravikyram** [comment]
@cfwin 
Can you please elaborate about the issue & the context.Will it be possible to provide simple stand alone code to reproduce the issue in our environment, then it will be easy for localizing the issue faster.Thanks!

**Comment by urvishp80** [comment]
I have got the more or less same issue while running the BERT model using TF hub. 

`WARNING: Entity <bound method BertLayer.call of <__main__.BertLayer object at 0x000001F3B880B0B8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method BertLayer.call of <__main__.BertLayer object at 0x000001F3B880B0B8>>: AttributeError: module 'gast' has no attribute 'Num'`

and then I got the error as follows 

```FailedPreconditionError                   Traceback (most recent call last)
 in 
      9     validation_data=([test_input_ids, test_input_masks, test_segment_ids], test_labels),
     10     epochs=1,
---> 11     batch_size=64
     12 )

~\envs\tf_1_14\lib\site-packages\tensorflow\python\keras\engine\training.py in fit(self, x, y, batch_size, epochs, verbose, callbacks, validation_split, validation_data, shuffle, class_weight, sample_weight, initial_epoch, steps_per_epoch, validation_steps, validation_freq, max_queue_size, workers, use_multiprocessing, **kwargs)
    778           validation_steps=validation_steps,
    779           validation_freq=validation_freq,
--> 780           steps_name='steps_per_epoch')
    781 
    782   def evaluate(self,

~\envs\tf_1_14\lib\site-packages\tensorflow\python\keras\engine\training_arrays.py in model_iteration(model, inputs, targets, sample_weights, batch_size, epochs, verbose, callbacks, val_inputs, val_targets, val_sample_weights, shuffle, initial_epoch, steps_per_epoch, validation_steps, validation_freq, mode, validation_in_fit, prepared_feed_values_from_dataset, steps_name, **kwargs)
    361 
    362         # Get outputs.
--> 363         batch_outs = f(ins_batch)
    364         if not isinstance(batch_outs, list):
    365           batch_outs = [batch_outs]

~\envs\tf_1_14\lib\site-packages\tensorflow\python\keras\backend.py in __call__(self, inputs)
   3290 
   3291     fetched = self._callable_fn(*array_vals,
-> 3292                                 run_metadata=self.run_metadata)
   3293     self._call_fetch_callbacks(fetched[-len(self._fetches):])
   3294     output_structure = nest.pack_sequence_as(

~\envs\tf_1_14\lib\site-packages\tensorflow\python\client\session.py in __call__(self, *args, **kwargs)
   1456         ret = tf_session.TF_SessionRunCallable(self._session._session,
   1457                                                self._handle, args,
-> 1458                                                run_metadata_ptr)
   1459         if run_metadata:
   1460           proto_data = tf_session.TF_GetBuffer(run_metadata_ptr)

FailedPreconditionError: 2 root error(s) found.
  (0) Failed precondition: Error while reading resource variable bert_layer_module/bert/encoder/layer_5/intermediate/dense/bias from Container: localhost. This could mean that the variable was uninitialized. Not found: Resource localhost/bert_layer_module/bert/encoder/layer_5/intermediate/dense/bias/class tensorflow::Var does not exist.
	 [[{{node bert_layer/bert_layer_module_apply_tokens/bert/encoder/layer_5/intermediate/dense/BiasAdd/ReadVariableOp}}]]
	 [[loss/mul/_491]]
  (1) Failed precondition: Error while reading resource variable bert_layer_module/bert/encoder/layer_5/intermediate/dense/bias from Container: localhost. This could mean that the variable was uninitialized. Not found: Resource localhost/bert_layer_module/bert/encoder/layer_5/intermediate/dense/bias/class tensorflow::Var does not exist.
	 [[{{node bert_layer/bert_layer_module_apply_tokens/bert/encoder/layer_5/intermediate/dense/BiasAdd/ReadVariableOp}}]]
0 successful operations.
0 derived errors ignored.```

I have,
TF = 1.14
OS = Windows 10
GPU = 2060rtx

**Comment by urvishp80** [comment]
I run my code again and I got this error now 

```ResourceExhaustedError                    Traceback (most recent call last)
 in 
      9     validation_data=([test_input_ids, test_input_masks, test_segment_ids], test_labels),
     10     epochs=1,
---> 11     batch_size=64
     12 )

~\envs\tf_1_14\lib\site-packages\tensorflow\python\keras\engine\training.py in fit(self, x, y, batch_size, epochs, verbose, callbacks, validation_split, validation_data, shuffle, class_weight, sample_weight, initial_epoch, steps_per_epoch, validation_steps, validation_freq, max_queue_size, workers, use_multiprocessing, **kwargs)
    778           validation_steps=validation_steps,
    779           validation_freq=validation_freq,
--> 780           steps_name='steps_per_epoch')
    781 
    782   def evaluate(self,

~\envs\tf_1_14\lib\site-packages\tensorflow\python\keras\engine\training_arrays.py in model_iteration(model, inputs, targets, sample_weights, batch_size, epochs, verbose, callbacks, val_inputs, val_targets, val_sample_weights, shuffle, initial_epoch, steps_per_epoch, validation_steps, validation_freq, mode, validation_in_fit, prepared_feed_values_from_dataset, steps_name, **kwargs)
    361 
    362         # Get outputs.
--> 363         batch_outs = f(ins_batch)
    364         if not isinstance(batch_outs, list):
    365           batch_outs = [batch_outs]

~\envs\tf_1_14\lib\site-packages\tensorflow\python\keras\backend.py in __call__(self, inputs)
   3290 
   3291     fetched = self._callable_fn(*array_vals,
-> 3292                                 run_metadata=self.run_metadata)
   3293     self._call_fetch_callbacks(fetched[-len(self._fetches):])
   3294     output_structure = nest.pack_sequence_as(

~\envs\tf_1_14\lib\site-packages\tensorflow\python\client\session.py in __call__(self, *args, **kwargs)
   1456         ret = tf_session.TF_SessionRunCallable(self._session._session,
   1457                                                self._handle, args,
-> 1458                                                run_metadata_ptr)
   1459         if run_metadata:
   1460           proto_data = tf_session.TF_GetBuffer(run_metadata_ptr)

ResourceExhaustedError: 2 root error(s) found.
  (0) Resource exhausted: OOM when allocating tensor with shape[64,12,256,256] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
	 [[{{node bert_layer/bert_layer_module_apply_tokens/bert/encoder/layer_11/attention/self/MatMul}}]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

	 [[loss/mul/_1199]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

  (1) Resource exhausted: OOM when allocating tensor with shape[64,12,256,256] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
	 [[{{node bert_layer/bert_layer_module_apply_tokens/bert/encoder/layer_11/attention/self/MatMul}}]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

0 successful operations.
0 derived errors ignored.
```

**Comment by ravikyram** [comment]
@cfwin 
any updates please.
@urvishp80 
What is the version of gast on your system?.
Can you please try by downgrading the gast by using pip install gast==0.2.2 and let us know if the issue still persists. Thanks!

**Comment by ravikyram** [comment]
@cfwin 
@urvishp80 
any update please.Thanks!

**Comment by keineahnung2345** [comment]
For me, the warning happens in tensorflow==1.14.0 and gast==0.3.2, but doesn't show in tensorflow==1.13.2 and gast==0.3.2.
