### ISSUE TITLE
tf.print operations inside tf.function do not print in order

### ISSUE THREAD

**Issue by humcasma** [tensorflow/tensorflow#33453]
**System information**
Tensorflow-gpu 2.0.0 installed via `pip install tensorflow-gpu` in a Colaboratory notebook.

**Describe the current and expected behavior**
In https://www.tensorflow.org/guide/function#side_effects one can read that `tf.print` operations inside `tf.function` will execute in order. This seem, indeed , to be the case. However, while operations are executed in order, the printed statements are not always shown in the expected order.

The code
```
v = tf.Variable(5)

@tf.function
def find_next_odd():
  tf.print('1:',v)
  v.assign(v + 1)
  tf.print('2:', v)
  if v % 2 == 0:
    v.assign(v + 1)
    tf.print('3:', v)

find_next_odd()
```
prints
```
1: 5
3: 7
2: 6
```

Note, however, that if a (dummy) conditional statement is inserted before the second `tf.print`, the output is the expected one.

The code
```
v = tf.Variable(5)

@tf.function
def find_next_odd():
  tf.print('1:',v)
  v.assign(v + 1)
  if v==v: #dummy condition
    tf.print('2:', v)
  if v % 2 == 0:
    v.assign(v + 1)
    tf.print('3:', v)

find_next_odd()
```
prints
```
1: 5
2: 6
3: 7
```

**Comment by oanush** [comment]
@humcasma ,
Can you please try using latest` tf-nightly-gpu-2.1.0.dev20191017`, issue seemed to be fixed. Kindly find the [gist](https://colab.sandbox.google.com/gist/oanush/e3f25288b0b53912adc5ca36131f6c72/33453.ipynb) of colab.Thanks!

**Comment by humcasma** [comment]
@oanush Unfortunately I am not able to confirm whether it has been fixed or not. When using the nightly version of tensorflow I get an exception when running `v = tf.Variable(5)`:

>  AttributeError: 'google.protobuf.pyext._message.RepeatedCompositeCo' object has no attribute 'append'

**Comment by oanush** [comment]
@humcasma ,
It worked fine for me, try with `pip install tf-nightly-gpu`. Please share the gist of colab your trying to execute.

**Comment by humcasma** [comment]
@oanush You can access the gist [here](https://colab.research.google.com/gist/humcasma/cecc9b33645c774409a576d0c4b496b2/33453.ipynb)

**Comment by oanush** [comment]
@humcasma ,
Hi, tried running the same gist no error was faced. 
For the error being faced can you check the [link](https://stackoverflow.com/questions/58343293/attributeerror-google-protobuf-pyext-message-repeatedcompositeco-object-has)?

**Comment by humcasma** [comment]
It works now as expected. Thanks!
