### ISSUE TITLE
A question on ctc implementation

### ISSUE THREAD

**Issue by chengmengli06** [tensorflow/tensorflow#33462]
I have a question on ctc implementation here:
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/util/ctc/ctc_loss_calculator.h#L500
why the gradient is set to y instead of zero when no valid path is found?

**Comment by jvishnuvardhan** [comment]
This is not Build/Installation or Bug/Performance issue. Please post this kind of support questions at [Stackoverflow](https://stackoverflow.com/questions/tagged/tensorflow). There is a big community to support and learn from your questions. We might answer these support type questions on stackoverflow. GitHub is mainly for addressing bugs in installation and performance. Thanks!
