### ISSUE TITLE
Undefined symbols for architecture arm64:   "NewGpuDelegate(GpuDelegateOptions const*)

### ISSUE THREAD

**Issue by Mana-M** [tensorflow/tensorflow#33463]
System information

    Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
    OS Platform and Distribution (e.g., Linux Ubuntu 16.04): macOS 10.14.6
    Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: iPhone X.s, 13.1.3
    TensorFlow installed from (source or binary): source
    TensorFlow version (use command below): master branch cloned on 2019-10-8
    Python version: 3.7.4
    Bazel version (if compiling from source):  0.26.1
    GCC/Compiler version (if compiling from source): NA
    CUDA/cuDNN version: NA
    GPU model and memory: NA

Describe the current behavior:
It fails to build the library in Xcode.
Undefined symbols for architecture arm64:   "NewGpuDelegate(GpuDelegateOptions const*)

Describe the expected behavior:
I want to build my C++ library with the ability to run it with GPU in an iOS app

Code to reproduce the issue

Other info / logs
I changed the extension of the file having this line of code: 
_delegate = NewGpuDelegate(&options);_
from cpp to mm, as otherwise I couldn't include header files for metal(which are written in obj-c).
I tested the tensorflow ios/camera example and it builds and runs fine. But using the same .framework lib gives me the same undefined symbol error.

Bazel Command for building the tensorflow lib:
**bazel build -c opt --cpu ios_arm64 --copt -Os --copt -DTFLITE_GPU_BINARY_RELEASE --copt -fvisibility=hidden --linkopt -s --strip always --cxxopt=-std=c++14 :tensorflow_lite_gpu_framework --apple_platform_type=ios**

Any help would be appreciated!

**Comment by RuohengLiu** [comment]
same problem

**Comment by mohantym** [comment]
Hi @Mana-M ! 1.x version are not supported any more. Please check this [thread](https://www.tensorflow.org/lite/guide/build_ios) to build and use TFLite in IOS framework with 2.8 codebase. Thanks!
