### ISSUE TITLE
tf.range is not equivalent to np.arange

### ISSUE THREAD

**Issue by stefan-falk** [tensorflow/tensorflow#33467]
`tensorflow-gpu==1.12.3`

[The docs](https://www.tensorflow.org/versions/r1.12/api_docs/python/tf/range#numpy_compatibility) state about `tf.range`:

> Equivalent to np.arange

But:

```python
import tensorflow as tf
import numpy as np
tf.enable_eager_execution()

def main():

    s = tf.constant(np.random.rand(20))
    rate = 2.5
    s1 = np.arange(0, tf.shape(s)[0], rate)
    s2 = tf.range(0, tf.shape(s)[0], rate).numpy()

    print(s1)
    print(s2)

if __name__ == '__main__':
    main()
```

Outputs:

```
[ 0.   2.5  5.   7.5 10.  12.5 15.  17.5 20.  22.5]
[ 0.   2.5  5.   7.5 10.  12.5 15.  17.5]
```

**Comment by yongtang** [comment]
@stefan-falk I tried with TF 2.0.0 and the values seem to match. Can you update the TF (1.12.3 is a little outdated) to latest 2.0.0?

**Comment by oanush** [comment]
@stefan-falk ,
Hi, you can also try 1.15rc3 version. It works fine.Thanks!

**Comment by oanush** [comment]
@stefan-falk ,
Hi, any update on the issue ?Thanks!

**Comment by oanush** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Comment by stefan-falk** [comment]
@oanush Sorry for responding so late.I am stuck with 1.12 - I am sure it works with later versions but the example above was run with 1.12. Looking forward for 1.12.4 :P
