### ISSUE TITLE
build fails when choosing clang/llvm compiler instead of nvcc compiler

### ISSUE THREAD

**Issue by Ghassan** [tensorflow/tensorflow#33473]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution Linux Ubuntu 18.04):
- TensorFlow installed from (source or binary): Source
- TensorFlow version: r2.0
- Python version: 3.6
- Installed using virtualenv? pip? conda?: conda
- Bazel version (if compiling from source): 0.26.1
- GCC/Compiler version (if compiling from source): clang version 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
- CUDA/cuDNN version: CUDA 10.0 /cuDNN 7.6.3.30
- GPU model and memory: nvidia GTX 1080 8GB RAM

**Problem Description**
when building using clang/llvm compiler over nvcc, the build fails  with the error message:

ERROR: /usr/local/tensorflow/tensorflow/tools/pip_package/BUILD:35:1: Illegal ambiguous match on configurable attribute "deps" in //tensorflow/tools/pip_package:included_headers_gather:
@local_config_cuda//cuda:using_nvcc
@local_config_cuda//cuda:using_clang
Multiple matches are not allowed unless one is unambiguously more specialized.

**Provide the exact sequence of commands / steps that you executed before running into the problem**

step1:  configuring with these options:
Do you wish to build TensorFlow with XLA JIT support? [Y/n]: y
XLA JIT support will be enabled for TensorFlow.

Do you wish to build TensorFlow with OpenCL SYCL support? [y/N]: n
No OpenCL SYCL support will be enabled for TensorFlow.

Do you wish to build TensorFlow with ROCm support? [y/N]: n
No ROCm support will be enabled for TensorFlow.

Do you wish to build TensorFlow with CUDA support? [y/N]: y
CUDA support will be enabled for TensorFlow.

Do you wish to build TensorFlow with TensorRT support? [y/N]: y
TensorRT support will be enabled for TensorFlow.

Found CUDA 10.0 in:
    /usr/local/cuda/lib64
    /usr/local/cuda/include
Found cuDNN 7 in:
    /usr/lib/x86_64-linux-gnu
    /usr/include
Found TensorRT 6 in:
    /usr/lib/x86_64-linux-gnu
    /usr/include/x86_64-linux-gnu

Please specify a list of comma-separated CUDA compute capabilities you want to build with.
You can find the compute capability of your device at: https://developer.nvidia.com/cuda-gpus.
Please note that each additional compute capability significantly increases your build time and binary size, and that TensorFlow only supports compute capabilities >= 3.5 [Default is: 6.1]: 

Do you want to use clang as CUDA compiler? [y/N]: y
Clang will be used as CUDA compiler.

Do you wish to download a fresh release of clang? (Experimental) [y/N]: n
Clang will not be downloaded.

Please specify which clang should be used as device and host compiler. [Default is /usr/bin/clang]: 

Do you wish to build TensorFlow with MPI support? [y/N]: y
MPI support will be enabled for TensorFlow.

Please specify the MPI toolkit folder. [Default is /usr/local/pgi/linux86-64/19.4/mpi/openmpi-3.1.3]: 

Please specify optimization flags to use during compilation when bazel option "--config=opt" is specified [Default is -march=native -Wno-sign-compare]: 

Would you like to interactively configure ./WORKSPACE for Android builds? [y/N]: n
Not configuring the WORKSPACE for Android builds.

Preconfigured Bazel build configs. You can use any of the below by adding "--config=<>" to your build command. See .bazelrc for more details.
	--config=mkl         	# Build with MKL support.
	--config=monolithic  	# Config for mostly static monolithic build.
	--config=gdr         	# Build with GDR support.
	--config=verbs       	# Build with libverbs support.
	--config=ngraph      	# Build with Intel nGraph support.
	--config=numa        	# Build with NUMA support.
	--config=dynamic_kernels	# (Experimental) Build kernels into separate shared objects.
	--config=v2          	# Build TensorFlow 2.x instead of 1.x.
Preconfigured Bazel build configs to DISABLE default on features:
	--config=noaws       	# Disable AWS S3 filesystem support.
	--config=nogcp       	# Disable GCP support.
	--config=nohdfs      	# Disable HDFS support.
	--config=noignite    	# Disable Apache Ignite support.
	--config=nokafka     	# Disable Apache Kafka support.
	--config=nonccl      	# Disable NVIDIA NCCL support.
Configuration finished

step 2: build with this command:

bazel build  --config=cuda --linkopt='-lrt'  --verbose_failures -c opt  //tensorflow/tools/pip_package:build_pip_packag

**Any other info / logs**
none

**Comment by gadagashwini** [comment]
@Ghassan, Just to verify, did you follow the instructions mentioned in [this link](https://www.tensorflow.org/install/source). Thanks!

**Comment by gadagashwini** [comment]
@Ghassan, Is this still an issue!

**Comment by gadagashwini** [comment]
Please follow the instructions mentioned in this [link](https://www.tensorflow.org/install/source).
Closing the issue due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
