### ISSUE TITLE
TFLite-micro: unable to build bluepill tests

### ISSUE THREAD

**Issue by PiotrZierhoffer** [tensorflow/tensorflow#33470]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Debian 9
- TensorFlow version: current master (17c4db8)
- GCC version: gcc (Debian 9.2.1-8) 9.2.1 20190909

**Describe the problem**

Trying to follow the instructions from [TFLite Micro README](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/experimental/micro/README.md#building-for-the-blue-pill-stm32f103-using-make) fails, being unable to build the code properly.

I traced down the problem to e98d181 - the commit before this one passes properly.

The fail log is below, but the first line is important, namely the `cannot find entry symbol _main`.
Further lines are because Renode is unable to run it properly.

```
...
.../tensorflow/tensorflow/lite/experimental/micro/tools/make/downloads/gcc_embedded/bin/../lib/gcc/arm-none-eabi/7.3.1/../../../../arm-none-eabi/bin/ld: warning: cannot find entry symbol _main; defaulting to 0000000008000000
tensorflow/lite/experimental/micro/testing/test_bluepill_binary.sh tensorflow/lite/experimental/micro/tools/make/gen/bluepill_cortex-m3/bin/micro_features_fft_test '~~~ALL TESTS PASSED~~~'
Sending build context to Docker daemon  37.38kB
Step 1/2 : FROM antmicro/renode:latest
 ---> d8aae99c4341
Step 2/2 : LABEL maintainer="Pete Warden <petewarden@google.com>"
 ---> Using cache
 ---> 659756518d3d
Successfully built 659756518d3d
Successfully tagged renode_bluepill:latest
LOGS:
Preparing suites
Starting suites
Running /workspace/tensorflow/lite/experimental/micro/testing/bluepill.robot
==============================================================================
bluepill                                                                      
==============================================================================
Should Run Bluepill Test :: Runs a Bluepill test and waits for a s... | FAIL |
TargetInvocationException: Exception has been thrown by the target of an invocation.
InvalidOperationException: Time for operation to finish has exceeded 00:00:30.000000. Events so far:
[14:42:22.501]   ------------------------------------------------------------------------------------
[14:42:52.633]   >>> 'WaitUntilLine': timeout occurred
[14:42:52.634]   >>> Characters waiting in buffer: 

[14:42:52.635]   ------------------------------------------------------------------------------------
------------------------------------------------------------------------------
bluepill                                                              | FAIL |
1 critical test, 0 passed, 1 failed
1 test total, 0 passed, 1 failed
==============================================================================
Output:  /home/developer/bluepill.xml
Cleaning up suites
Aggregating all robot results
Output:  /home/developer/robot_output.xml
Log:     /home/developer/log.html
Report:  /home/developer/report.html
Some tests failed :( See logs for details!
tensorflow/lite/experimental/micro/tools/make/gen/bluepill_cortex-m3/bin/micro_features_fft_test: FAIL - '~~~ALL TESTS PASSED~~~' not found in logs.
make: *** [tensorflow/lite/experimental/micro/examples/micro_speech/Makefile.inc:314: test_micro_features_fft_test] Error 1
```

The said symbol is provided by stm32_bare_lib which is downloaded correctly. The problem is that it is **not compiled** at all. I believe that `MICROLITE_CC_SRCS` in [bluepill_makefile.inc](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/experimental/micro/tools/make/targets/bluepill_makefile.inc) is evaluated before the lib is actually downloaded.

This is easy to verify: just add the following in `bluepill_makefile.inc:54`
```
$(error MICROLITE_CC_SRCS is $(MICROLITE_CC_SRCS))
```
It will stop the build process before downloading the lib (and will print out the variable **not** containing the relevant source files).

**Provide the exact sequence of commands / steps that you executed before running into the problem**

1. Clone the repo
2. Run `make -f tensorflow/lite/experimental/micro/tools/make/Makefile TARGET=bluepill test`
3. Fail with the above.

CC @petewarden 

**Note**
I assume there are two actual problems: one is that the compilation is not correct, the other is that it does not prevent the test from running, but let's it work on a "crippled" output binary.

**Comment by advaitjain** [comment]
The tests all build now, with the caveat that the binary size is more than what the bluepill hardware can support. A subset of the tests can be run in the renode emulator (e.g. kernel_add_test) while others fail.

The remaining work to be done to get everything going again for the Bluepill platform is being tracked internally so I am closing this issue for now.

Please let us know if there is something specific that you are unable to do at this time.
