### ISSUE TITLE
Allowing to provide pre-built flatbuffers when building tflite C++

### ISSUE THREAD

**Issue by DoumanAsh** [tensorflow/tensorflow#33472]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Android/Ubuntu
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): Source
- TensorFlow version: 1.15.0
- Python version: 3.6.8
- Installed using virtualenv? pip? conda?: ip
- Bazel version (if compiling from source): 0.24.1
- GCC/Compiler version (if compiling from source): NDK r17b clang
- CUDA/cuDNN version: -
- GPU model and memory: -

**Describe the problem**
Currently tensorflow build always pulls flatbuffers on its own, resulting in duplication of flatbuffers, if user already has dependency on flatbuffers.
Due to how tensorflow headers work, it leaks dependency to generated schema (and therefore flatbuffers.h) 
But as we used flatbuffers 1.10.0 in our project, we had no compilation errors due to missing header.
Since tf 1.15 schema uses some specific feature of flatbuffers 1.11.0 which results in failed build when including model.h for example

Ideally it would be great if flatbuffers schema wouldn't be leaked, but I doubt it is feasible.
So my plan is currently upgrading our own flatbuffers to 1.11.0.

But this brings me to a question, if we could somehow tell bazel to use our own flatbuffers instead of pulling its own?

P.s. I tried to find some options in configuration script, but there seem to be none. So I assume most common use case is always build own copy of flatbuffers as part of build process.

**Any other info / logs**

Having proper instructions to how build and install self-contained C++ tflite would be nice too :)

**Comment by jdduke** [comment]
Hi @DoumanAsh, out of curiosity, would it help if we had a pure C API (perhaps with lightweight C++ wrappers) which did not have any kind of flatbuffer dependency in its public API?

And for the C/C++ library, are you fine if it's built as a separate shared library? Or are you buliding it as a direct bazel dependency in your project?

**Comment by DoumanAsh** [comment]
Hey @jdduke actually if flatbuffers wouldn't be leaked, it would be perfect for us.
The main problem right now is that not only it is leaked in headers, but GPU delegate library has these symbols public, which originally caused some asan issues.
I only noticed flatbuffers in public API because it was using our own headers which wasn't comptabile with 1.15 :(

Ideally we'd like static library, but shared library works just fine for us, we do not use bazel and package our dependencies using conan

**Comment by DoumanAsh** [comment]
@jdduke On side note, as 1.15 is latest release, I assume any changes related to that would be reflected only in 2.x right?

**Comment by jdduke** [comment]
Hey @DoumanAsh , apologies for the severely delayed response.

We have migrated our [C API](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/c) out of experimental, and it does not pull in the flatbuffer headers. At the same time, I'm trying to pull out the flatbuffer header dependency from the C++ API, but that's a bit more involved.

I should also note that we started exporting the C API symbols from the native libraries, and including the C headers, in our [prebuilt Android libraries](https://bintray.com/google/tensorflow/tensorflow-lite#files/org%2Ftensorflow%2Ftensorflow-lite%2F0.0.0-nightly) in case you'd prefer to use prebuilts.

**Comment by DoumanAsh** [comment]
@jdduke Glad to hear this, do you have any idea which 2.x version would get stable C API?

As for pre-built libraries, for our purpose we only need C/C++ API so we avoid any JNI enabled binaries (as we use tensorflow lite outside of Android too)

**Comment by jdduke** [comment]
The next release (2.2) will have the stable C API embedded in the prebuilt Android libraries.

We're also exploring hosting prebuilt libraries for non-Android platforms, but it likely won't be until Q2 that we can make that happen.

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.
