### ISSUE TITLE
Need a way to get Intermediate Layer Inputs/Activations for tf.keras Models

### ISSUE THREAD

**Issue by n2cholas** [tensorflow/tensorflow#33478]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using):
2.0
- Are you willing to contribute it (Yes/No):
Yes, if there is a consensus on how it should be designed. 

**Describe the feature and the current behavior/state.**
In eager mode, there is no way to access a tf.keras model's layer inputs/outputs during training (as far as I can tell, please correct me if I'm wrong). In TF 1.x (graph mode), this was not a problem, since you could use <s>[`layer.input`](https://github.com/tensorflow/tensorflow/blob/r2.0/tensorflow/python/keras/engine/base_layer.py#L1541-L1558) or [`layer.output`](https://github.com/tensorflow/tensorflow/blob/r2.0/tensorflow/python/keras/engine/base_layer.py#L1560-L1577)</s> [`layer.inbound_nodes` or `layer.outbound_nodes`](https://github.com/tensorflow/tensorflow/blob/r2.0/tensorflow/python/keras/engine/base_layer.py#L1663-L1673) to get these tensors and use those values, but this is no longer possible in eager mode. 

PyTorch solves this issue by allowing users to register hooks on layers, which is essentially a function that is called before/after the forward/backward pass on a layer. [Here](https://pytorch.org/docs/stable/_modules/torch/nn/modules/module.html#Module.register_forward_hook) is the code for `register_forward_hook` in PyTorch.

Alternatively, the input/output properties of a layer could store a reference to the tensors used in the most recent forward pass.

**Will this change the current api? How?**
Yes, depending on how this is implemented. If a hooks approach is used, this public method would have to be added to `tf.keras.layers.Layer`. If the input/output property approach is used, these properties would have new behavior in eager mode.

**Who will benefit with this feature?**
Being able to access, record, manipulate, or otherwise use layer inputs and outputs for models during training/inference is generally very useful. 

A specific example is the [K-FAC](https://arxiv.org/abs/1503.05671) optimization algorithm, which uses each layer's inputs and pre-activation gradients to approximate the Fisher information matrix. The [current implementation](https://github.com/tensorflow/kfac) does not support eager. PyTorch implementations (e.g. [this one](https://github.com/alecwangcq/KFAC-Pytorch/blob/master/optimizers/kfac.py#L81-L82)) of this algorithm use hooks to do this.

Another use case is visualizing intermediate activations of CNNs. [This example](https://towardsdatascience.com/visualizing-intermediate-activation-in-convolutional-neural-networks-with-keras-260b36d60d0) uses layer.outputs in TF 1.x + Keras to grab the right tensors then creating an augmented model. This process would be greatly simplified by allowing access to intermediate activations without augmenting the model. 
  
**Any Other info.**
[Here](https://github.com/tensorflow/tensorflow/issues/33129) is a related issue about getting intermediate activations.

**EDIT (2019-10-20):** I learned that `layer.inbound_nodes `and `layer.outbound_nodes` used to have this behavior, not `layer.input` and `layer.output`. `layer.input` and `layer.output` track the tensors that are created when [`model.build(input_shape)`](https://github.com/tensorflow/tensorflow/blob/r2.0/tensorflow/python/keras/engine/base_layer.py#L365-L379) is called. When you use the model as a callable on your own input (i.e. `predictions = model(inputs)`), new tensors are created (reusing the model's weights/architecture). In TF 1.x, `inputs` would be added to the `inbound_nodes` list and `predictions` would be added to the `outbound_nodes` list during this call. Now, since in eager mode the model is called on a new `EagerTensor` for every training step, it is not reasonable to add that many new tensors to these lists, so the property was deprecated. Since this feature used to exist, I think it's important for a reasonable replacement to exist in TF2 (such as hooks or a layer property tracking the most recent inputs/outputs).

**Comment by jvishnuvardhan** [comment]
@n2cholas If you are looking for `tf.keras` Models, `model.get_layer(layer_name).outputs` or `model.layer[layer_index].output` will provide the details you are looking. This was already answered in the [link](https://github.com/tensorflow/tensorflow/issues/33129) you provided. 

Please let us know what you think. Thanks!

**Comment by n2cholas** [comment]
Thanks @jvishnuvardhan for your response. I don't think `model.layer[layer_index].output` gives me the outputs I need.  Here's a minimal example of trying to compute the output gradients from a Dense layer using this property (runs in colab):

```
%tensorflow_version 2.x
import tensorflow as tf

(x_train, y_train), _ = tf.keras.datasets.mnist.load_data()
train_ds = tf.data.Dataset.from_tensor_slices((x_train, y_train)).batch(32)

model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128),
  tf.keras.layers.ReLU(),
  tf.keras.layers.Dense(10)
])

loss_object = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

images, labels = next(iter(train_ds))

with tf.GradientTape() as tape:
  predictions = model(images)
  loss = loss_object(labels, predictions)
  
print(tape.gradient(loss, model.layers[1].output))
```

This prints `None` instead of the gradient. Manually tracking the outputs at each layer then computing the gradient gives me the output gradient of the Dense layer, which is what I need:

```
outputs = [images]
with tf.GradientTape() as tape:
  for layer in model.layers:
    outputs.append(layer(outputs[-1]))
  loss = loss_object(labels, outputs[-1])
  
print(tape.gradient(loss, outputs[2]))
```

In this sequential case, manually doing the forward pass (as I did with the loop) is trivial, but it can become difficult with other architectures, such as ResNets. With hooks, this would not be necessary.

Am I doing something wrong? Is there a better way for me to track the intermediate activations?

**Comment by n2cholas** [comment]
If you change the model code to not include an `input_shape`, the model is never built and the `input` and `output` properties don't exist, even after the forward pass. If you change the model code from my previous example to the following:
```
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(),
  tf.keras.layers.Dense(128),
  tf.keras.layers.ReLU(),
  tf.keras.layers.Dense(10)
])
```
The first bit of code in my previous reply will result in `AttributeError: Layer dense has no inbound nodes.`

The `input` and `output` properties simply track the tensors created when the model built, not the tensors created during the `predictions = model(images)` call. The tensors I'm interested in are the ones created during that call.

**Comment by n2cholas** [comment]
@jvishnuvardhan @tanzhenyu Any update on this? I would be happy to implement hooks and submit a PR if hooks seem like the most suitable way to move forward.

**Comment by dimitry12** [comment]
@n2cholas I will happily test your PR :D

**Comment by gourie** [comment]
Same problem here, great problem description @n2cholas!

**Comment by StanleyGan** [comment]
My current application also needs to access the intermediate activations and backward gradients. Since a solution to this has not been implemented yet, does it make sense to just save these tensors as attributes of my class which is inherited from `keras.models.Model`?

**Comment by n2cholas** [comment]
Sorry about the delay, I won't have the bandwidth to work on my implementation until the end of December. I'd be happy to test someone else's implementation if they do it sooner!

> My current application also needs to access the intermediate activations and backward gradients. Since a solution to this has not been implemented yet, does it make sense to just save these tensors as attributes of my class which is inherited from `tf.keras.models.Model`?

Yes, this is what I've been doing. I subclassed all the layer types I needed, then saved the input/output tensors as attributes during my forward pass.

**Comment by n2cholas** [comment]
Should I create an RFC for this, since it's an API addition? Or just a PR? Also, how should this interact with autograph and model saving? The base_layer.py code is pretty intimidating.  I'd love some guidance from a TensorFlower, if possible.

Here's a temporary layer wrapper I've been using to get this functionality. This is pretty similar to what I'd do in the `tf.keras.layers.Layer` code (in the `__call__` function): 

```Python
%tensorflow_version 2.x 
import tensorflow as tf
from typing import List, Callable, Optional

class LayerWithHooks(tf.keras.layers.Layer):
  def __init__(
      self, 
      layer: tf.keras.layers.Layer,
      hooks: List[Callable[[tf.Tensor, tf.Tensor], Optional[tf.Tensor]]] = None):
    super().__init__()
    self._layer = layer
    self._hooks = hooks or []
  
  def call(self, input: tf.Tensor) -> tf.Tensor:
    output = self._layer(input)
    for hook in self._hooks:
      hook_result = hook(input, output)
      if hook_result is not None:
        output = hook_result
    return output
  
  def register_hook(
      self, 
      hook: Callable[[tf.Tensor, tf.Tensor], Optional[tf.Tensor]]) -> None:
    self._hooks.append(hook)

model = tf.keras.Sequential([
  LayerWithHooks(tf.keras.layers.Dense(50, input_shape=(1,))),
  LayerWithHooks(tf.keras.layers.Dense(1)),
])
```

If you have an existing model, the code below seems to work, though I'm always hesitant to use monkey patching:

```Python
model = tf.keras.Sequential([
  tf.keras.layers.Dense(50, input_shape=(1,)),
  tf.keras.layers.Dense(1),
])

def get_call_fn(layer: tf.keras.layers.Layer) -> Callable[[tf.Tensor], tf.Tensor]:
  old_call_fn = layer.call
  def call(input: tf.Tensor) -> tf.Tensor:
    output = old_call_fn(input)
    for hook in layer._hooks:
        hook_result = hook(input, output)
        if hook_result is not None:
          output = hook_result
    return output
  return call

for layer in model.layers:
  layer._hooks = []
  layer.call = get_call_fn(layer)
  layer.register_hook = lambda hook: layer._hooks.append(hook)
```

Here's an example of saving inputs/outputs with this:

```Python
class InputOutputSaver:
  def __call__(self, input: tf.Tensor, output: tf.Tensor) -> None:
    self.input = input
    self.output = output

savers = {}
for layer in model.layers:
  saver = InputOutputSaver()
  layer.register_hook(saver)
  savers[layer] = saver

inps = tf.convert_to_tensor([[1.], [2.], [3.],])
print(model(inps))
print(savers[model.layers[0]].output)
```

This temporary solution workaround was not thoroughly tested, please let me know if you have any suggestions.

**Comment by fxtentacle** [comment]
Did you know that model.outputs is a mutable Pyhon list? You can just change it to return all outputs.
```
# assuming model is a keras Sequence and x is a valid input
output_names = [l.name for l in model.layers]
model.outputs = [l.output for l in model.layers]
model.build(input_shape=x.shape)
output_values = model(x)
layer_name_to_output_value = dict(zip(output_names, output_values))
```

**Comment by Alessiobrini** [comment]
Has some improvement been done to solve this issue? Or do we still need to save manually intermediate output as an attribute of the model? It is very impractical to have this problem when using model subclassing in eager mode

**Comment by armansamimi** [comment]
hey guys

If i want to get the output of a intermediate layer in my NN, What should i do? which function can give me the output of the specific layer? and can i define a new loss function at that layer? for example for parallel learning : parent classification and subclass classification.

**Comment by tanzhenyu** [comment]
Sorry for the delay!
I'm not sure if layer.input and layer.output cannot achieve what you're looking for.
First of all, layer.inbound_nodes and layer.outbound_nodes are deprecated in 2.0.
Second of all, layer.input and layer.output are still symbolic tensors, just as you described, they're created under the first `layer.build(input_shape)`

So to make your first use case work, i.e., the activation visualization work, it should be exactly the same code as before, i.e.,:
```python
original_model = tf.keras.Model(inputs, outputs)
activation_outputs = [layer.output for layer in original_model.layers]
activation_model = tf.keras.Model(inputs, activation_outputs)
```

To make your second use case work, i.e., getting the right gradient, remember `input` and `output` are symbolic tensors, what you really need is the gradient of an `EagerTensor` imperatively, so:
```python
seq_1 = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128),
])
seq_2 = tf.keras.models.Sequential([
  tf.keras.layers.ReLU(),
  tf.keras.layers.Dense(10)
])
loss_object = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)
images, labels = next(iter(train_ds))
with tf.GradientTape() as tape:
  out = seq_1(images)
  predictions = seq_2(out)
  loss = loss_object(labels, predictions)
  
print(tape.gradient(loss, out))
```
Or you can create a subclassed model that returns the final output as well as the intermediate output.

If this is too much of a hassle, maybe we could consider `layer.eager_input` and `layer.symbolic_input`.

**Comment by tanzhenyu** [comment]
BTW, you can still call a layer repeatedly and add inputs to the nodes.
```python
input_1 = tf.keras.Input((5,), name='input_1')
dense = tf.keras.layers.Dense(units=3)
output_1 = dense(input_1)
print(dense.inbound_nodes[0].input_tensors)
input_2 = tf.keras.Input((5,), name='input_2')
output_2 = dense(input_2)
print(dense.inbound_nodes[1].input_tensors)
```

**Comment by tanzhenyu** [comment]
Also check this as suggestion:
https://github.com/tensorflow/tensorflow/issues/33129#issuecomment-539876444

**Comment by tanzhenyu** [comment]
Closing it for now. Feel free to re-open if you still have concerns :-)

**Comment by NihalHarish** [comment]
How do we the same thing when running non-eager mode, i.e `tf.function`?

**Comment by boluoyu** [comment]
> BTW, you can still call a layer repeatedly and add inputs to the nodes.
> 
> ```python
> input_1 = tf.keras.Input((5,), name='input_1')
> dense = tf.keras.layers.Dense(units=3)
> output_1 = dense(input_1) 
> print(dense.inbound_nodes[0].input_tensors)  #<tf.Tensor 'input_1:0' shape=(None, 5) dtype=float32>
> input_2 = tf.keras.Input((5,), name='input_2')
> output_2 = dense(input_2)
> print(dense.inbound_nodes[1].input_tensors)  #<tf.Tensor 'input_2:0' shape=(None, 5) dtype=float32>
> ```
@tanzhenyu 
I want to get intermediate tensor,not layer's output.for example:
```
model = train_model()
func = tf.function(model)
tensor_specs1 = tf.TensorSpec.from_tensor(model.input)
call = func.get_concrete_function(tensor_specs1)
graph = call.graph
outputs = graph.get_tensor_by_name('model_1/word_encoder_time/word_attention/Softmax:0')
pred_model = tf.keras.models.Model(model.input,outputs)
results = pred_model(tensor_specs1)

```
but raise an exception:
```
raise ValueError("Tensor %s is not an element of this graph." % obj)
ValueError: Tensor Tensor("model_1/word_encoder_time/model/word_attention/BiasAdd:0", shape=(?, 10), dtype=float32) is not an element of this graph
```
```
outputs = [model.get_layer(name=output).get_output_at(0) for output in output_layers]
pred_model = tf.keras.models.Model(model.input,outputs)
```
It's working ,but it's not what I want.

**Comment by ucalyptus** [comment]
@tanzhenyu any updates ?

**Comment by sandeep22-v** [comment]
Any updates?

**Comment by k-lam** [comment]
Using monkey patch to break in and hook, that is not a elegant way, but it works
```python
def proxy_call(input:tf.Tensor, obj:tf.keras.layers.Layer)->tf.Tensor:
    if obj._before_call is not None:
        obj._before_call(obj,input)
    output = obj._old_call(input)
    if obj._after_call is not None:
        hook_result = obj._after_call(obj, input, output)
        if hook_result is not None:
            output = hook_result
    return output

def hook_layer_call(layers: List[tf.keras.layers.Layer], 
                    before_call: Callable[[tf.keras.layers.Layer, tf.Tensor],None]=None, 
                    after_call: Callable[[tf.keras.layers.Layer, tf.Tensor, tf.Tensor],Optional[tf.Tensor]]=None):
    for layer in layers:
        layer._before_call = before_call
        layer._after_call = after_call
        layer._old_call = layer.call
        layer.call = functools.partial(proxy_call, obj=layer)

def print_input_output(layer:tf.keras.layers.Layer, input:tf.Tensor, output:tf.Tensor):
    print(input, output)

# suppose you have a model(such as a tf.keras.Sequential instance)
hook_layer_call(model.layers, after_call=print_input_output)
```

**Comment by rachthree** [comment]
I'm a bit late, but I created a utility `tensorflow-hooks` (installable via PyPI) that provides forward pre-hooks and forward hooks to TensorFlow Keras layers: https://github.com/rachthree/tensorflow-hooks. I hope it'll be useful for others. Thank you @k-lam for the inspiration!

**Comment by Exasperatedfireball** [comment]
https://exit-ziggy.github.io/G_BaFMUAc9-FagZXLAzE_N16U4qMq6EcOkqCFtSDDjxoVU7h_2ZOqN0fok6euq2TEA/



i sought a solution for quite a while and ultimately found the answer
