### ISSUE TITLE
Error in loading a keras model saved by tf 1.15 from tf 1.14

### ISSUE THREAD

**Issue by saintthor** [tensorflow/tensorflow#33479]
I saved the keras model by tf 1.15.
when loading from  tf 1.14, occurs:

> ValueError: ('Unrecognized keyword arguments:', dict_keys(['ragged']))

how to fix it?

**Comment by gowthamkpr** [comment]
Tensorflow 1.15 contains breaking changes like ragged tensor support, so it does not support backwards compatibility(Tf 1.14). This is the issue. Please try to load it using Tensorflow 1.15 and it should work.

**Comment by saintthor** [comment]
> Tensorflow 1.15 contains breaking changes like ragged tensor support, so it does not support backwards compatibility(Tf 1.14). This is the issue. Please try to load it using Tensorflow 1.15 and it should work.

Thanks.

Can I save the model by tf 1.15 to the old format? Or any way else to convert backwards?

**Comment by galaktyk** [comment]
You can load tf1.15+ model using  tf1.15-2.1. Then save only weights to open in tf1.14
\___________________________________________________________________
\# In tensorflow 1.15-2.1
\# Load model
model = load_model("my_model.h5")

\# Save weights and architecture
model.save_weights("weights_only.h5")

\# Save model config
json_config = model.to_json()
with open('model_config.json', 'w') as json_file:
    json_file.write(json_config)
\___________________________________________________________________
\# In tensorflow 1.14   
\# Reload the model from the 2 files we saved
with open('model_config.json') as json_file:
    json_config = json_file.read()
new_model = tf.keras.models.model_from_json(json_config)

\# Load weights
new_model.load_weights('weights_only.h5')
'''

**Comment by saintthor** [comment]
> You can load tf1.15+ model using tf1.15-2.1. Then save only weights to open in tf1.14
> ___________________________________________________________________
> # In tensorflow 1.15-2.1
> # Load model
> model = load_model("my_model.h5")
> 
> # Save weights and architecture
> model.save_weights("weights_only.h5")
> 
> # Save model config
> json_config = model.to_json()
> with open('model_config.json', 'w') as json_file:
> json_file.write(json_config)
> ___________________________________________________________________
> # In tensorflow 1.14
> # Reload the model from the 2 files we saved
> with open('model_config.json') as json_file:
> json_config = json_file.read()
> new_model = tf.keras.models.model_from_json(json_config)
> 
> # Load weights
> new_model.load_weights('weights_only.h5')
> '''

Thank you. I will try later.

**Comment by OlofHarrysson** [comment]
I wrote a repo to handle this issue. It utilizes docker to load/save models in different tensorflow versions and gets around the ragged keyword. Here it is https://github.com/OlofHarrysson/tensorflow-model-converter

**Comment by saintthor** [comment]
> I wrote a repo to handle this issue. It utilizes docker to load/save models in different tensorflow versions and gets around the ragged keyword. Here it is https://github.com/OlofHarrysson/tensorflow-model-converter

It seems great._

**Comment by realleyriley** [comment]
I tried out the repo from @OlofHarrysson but it wasn't able to load a tf.keras 2.1.0 model for some reason. 

I was able to get past the "ragged" error though. In the `model_config.json`, I just ctrl+f for 'rag' and found one match which was this: `"ragged": false,`. I deleted that and then was able to load the model configuration and its weights :)
