### ISSUE TITLE
In the pix2pix tutorial, the dimension of upsample within up_stack looks wrong. Only the image size is doubled, not filters!

### ISSUE THREAD

**Issue by CindyQi7788** [tensorflow/tensorflow#33482]
This template is for miscellaneous issues not covered by the other issue categories.

For questions on how to work with TensorFlow, or support for problems that are not verified bugs in TensorFlow, please go to [StackOverflow](https://stackoverflow.com/questions/tagged/tensorflow).

If you are reporting a vulnerability, please use the [dedicated reporting process](https://github.com/tensorflow/tensorflow/blob/master/SECURITY.md).

For high-level discussions about TensorFlow, please post to discuss@tensorflow.org, for questions about the development or internal workings of TensorFlow, or if you would like to know how to contribute to TensorFlow, please post to developers@tensorflow.org.

**Comment by CindyQi7788** [comment]
Although it won't effect anything, but just wanna point it out for the comments are not right.

**Comment by oanush** [comment]
@CindyQi7788 ,
Hello, Can you please let us know where exactly in the [pix2pix tutorial](https://www.tensorflow.org/tutorials/generative/pix2pix) issue is being reported by you?

**Comment by CindyQi7788** [comment]
In the cell of Define a Generator: I think the dimension after 1st
upsample(512, 4, apply_dropout=True) ,  ### (bs, 2,2, 512), and so on...
otherwise the dimensions do not match with skip layers below.

up_stack = [
upsample(512, 4, apply_dropout=True), # (bs, 2, 2, 1024) ---> should be
(bs, 2,2, 512)
upsample(512, 4, apply_dropout=True), # (bs, 4, 4, 1024) ---> should be
(bs, 4, 4, 512)
upsample(512, 4, apply_dropout=True), # (bs, 8, 8, 1024) ---> should be
(bs, 8, 8, 512)
upsample(512, 4), # (bs, 16, 16, 1024) ---> should be (bs, 16, 16, 512)
upsample(256, 4), # (bs, 32, 32, 512) ---> should be (bs, 32, 32, 256)
upsample(128, 4), # (bs, 64, 64, 256) ---> should be (bs, 64, 64, 128)
upsample(64, 4), # (bs, 128, 128, 128) ---> should be (bs, 128, 128, 64)

**Comment by lamberta** [comment]
Thanks. That notebook lives over here in the tensorflow/docs repo: https://github.com/tensorflow/docs/blob/master/site/en/tutorials/generative/pix2pix.ipynb
Can you send a pull request, please?

**Comment by yashk2810** [comment]
I think, the up_stack comments are referring to the shapes after the concatenation with the skip connection.

**Comment by CindyQi7788** [comment]
yeah, "after the concatenation with the skip connection"  makes sense.

Thanks
Xin

**Comment by ymodak** [comment]
Closing this issue since its resolved. Thanks!
