### ISSUE TITLE
CTC tensorflow lite conversion problem

### ISSUE THREAD

**Issue by tulasiram58827** [tensorflow/tensorflow#33494]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):Ubuntu 19.04
- TensorFlow installed from (source or binary):binary
- TensorFlow version (or github SHA if from source): 2.0

**Provide the text output from tflite_convert**
```
Some of the operators in the model are not supported by the standard TensorFlow Lite runtime and are not recognized by TensorFlow. If you have a custom implementation for them you can disable this error with --allow_custom_ops, or by setting allow_custom_ops=True when calling tf.lite.TFLiteConverter(). Here is a list of builtin operators you are using: . Here is a list of operators for which you will need custom implementations: CTC_BEAM_SEARCH_DECODER.```

Also, please include a link to a GraphDef or the model if possible.
import tensorflow as tf
class BasicModel(tf.Module):
  def __init__(self):
    self.const = None
  @tf.function(input_signature=[tf.TensorSpec(shape=[None,500,28], dtype=tf.float32),tf.TensorSpec(shape=[None,], dtype=tf.int32)])
  def decoder(self, logits,seq_len):
    decoded, log_prob = tf.nn.ctc_beam_search_decoder(logits, seq_len)
    return decoded
# Create the tf.Module object.
root = BasicModel()
# Get the concrete function.
concrete_func = root.decoder.get_concrete_function()
converter = tf.lite.TFLiteConverter.from_concrete_functions([concrete_func])
converter.allow_custom_ops = False
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS,tf.lite.OpsSet.SELECT_TF_OPS]
tflite_model =converter.convert()

open("ctc_greedy_decoder.tflite",'wb').write(tflite_model)

**Any other info / logs**

But according to this link https://github.com/tensorflow/tensorflow/tree/r2.0/tensorflow/lite/experimental/kernels ctc_beam_search_decoder is registered as tflite op.

Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by haozha111** [comment]
Hi,

Could you change this line:
converter.allow_custom_ops = False

to
converter.allow_custom_ops = True


I run your script in TF 2 and can successfully do the conversion.

**Comment by tulasiram58827** [comment]
But if I do converter.allow_custom_ops=True I can convert it to tflite but I am not able to use it.
Here is the error :
Traceback (most recent call last):
  File "tflite.py", line 34, in <module>
    inference_from_tflite(pbfile_path)
  File "tflite.py", line 24, in inference_from_tflite
    interpreter.allocate_tensors()
  File "/home/mihup/anaconda3/lib/python3.7/site-packages/tensorflow_core/lite/python/interpreter.py", line 244, in allocate_tensors
    return self._interpreter.AllocateTensors()
  File "/home/mihup/anaconda3/lib/python3.7/site-packages/tensorflow_core/lite/python/interpreter_wrapper/tensorflow_wrap_interpreter_wrapper.py", line 106, in AllocateTensors
    return _tensorflow_wrap_interpreter_wrapper.InterpreterWrapper_AllocateTensors(self)
RuntimeError: Encountered unresolved custom op: CTC_BEAM_SEARCH_DECODER.Node number 0 (CTC_BEAM_SEARCH_DECODER) failed to prepare.

Code used for inference:
interpreter = tf.lite.Interpreter(model_path=tflite_model)
interpreter.allocate_tensors()
input_details = interpreter.get_input_details()
output_details = interpreter.get_output_details()
interpreter.invoke()
print(input_details,output_details)

**Comment by haozha111** [comment]
This seems like the default op resolver couldn't find the op kernel for CTC_BEAM_SEARCH_DECODER.

I guess you need to implement something like this:
tflite::ops::builtin::BuiltinOpResolver builtins;
builtins.AddCustom("Sin", Register_CTC_BEAM_SEARCH_DECODER());

The corresponding python interpreter to use with custom op is:
https://github.com/tensorflow/tensorflow/blob/0dec1a6a8a5d7a40378ab418ceab20cd6d4adb4b/tensorflow/lite/python/interpreter.py#L499

Please See link:https://www.tensorflow.org/lite/guide/ops_custom#defining_the_kernel_in_the_tensorflow_lite_runtime

**Comment by tulasiram58827** [comment]
The corresponding python interpreter   "class InterpreterWithCustomOps(Interpreter): "  to use with custom op is not present in the stable releases like  1.14,1.15,2.0 .
Python interpreter "class InterpreterWithCustomOps(Interpreter): " is only available in the master branch.
How can I use it as I cannot use master branch with pip install

**Comment by tulasiram58827** [comment]
@haozha111  please look into it

**Comment by tulasiram58827** [comment]
@haozha111 any update on this?

**Comment by haozha111** [comment]
Hi!

InterpreterWithCustomOps seems not the correct recommendation here, since it's currently not exposed as the public API. Looping in @jdduke to take a look. Hi Jared, do you know the recommended interpreter API to use when the model contains customs ops such as ctc beam search decoder? AFAIK the model can convert but it encounters a kernel registration issue during runtime.

**Comment by jdduke** [comment]
@tulasiram58827 just to be clear, do you want Python support primarily for testing? Or you plan on deploying your model in a Python environment? You can use `InterpreterWithCustomOps` if you build from source. How else did you want to plug in your custom ops into that function? Would you be linking it into the TF runtime?

**Comment by tulasiram58827** [comment]
@jdduke I planned for deploying my model in cpp enviornment. I want to converty my ctc model to tflite and use it in tflite runtime. I can easily convert my model to tflite by specifying this while conversion(converter.allow_custom_ops = True) but in runtime i am facing difficulties that this op is not registered. Please check this log.
Here is the error :
Traceback (most recent call last):
File "tflite.py", line 34, in
inference_from_tflite(pbfile_path)
File "tflite.py", line 24, in inference_from_tflite
interpreter.allocate_tensors()
File "/home/mihup/anaconda3/lib/python3.7/site-packages/tensorflow_core/lite/python/interpreter.py", line 244, in allocate_tensors
return self._interpreter.AllocateTensors()
File "/home/mihup/anaconda3/lib/python3.7/site-packages/tensorflow_core/lite/python/interpreter_wrapper/tensorflow_wrap_interpreter_wrapper.py", line 106, in AllocateTensors
return _tensorflow_wrap_interpreter_wrapper.InterpreterWrapper_AllocateTensors(self)
RuntimeError: Encountered unresolved custom op: CTC_BEAM_SEARCH_DECODER.Node number 0 (CTC_BEAM_SEARCH_DECODER) failed to prepare.

**Comment by tulasiram58827** [comment]
@jdduke Any update?

**Comment by jdduke** [comment]
I see, you would need to link in the CTC_BEAM_SEARCH_DECODER custom op manually. So you'd have to update the [builtin deps](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/kernels/BUILD#L625) to include [this dependency](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/experimental/kernels/BUILD#L39), then manually register that kernel [here](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/kernels/register.cc#L315) via:

```
AddCustom("CTC_BEEM_SEARCH_DECODER",
            tflite::ops::experimental::Register_CTC_BEAM_SEARCH_DECODER());
```

**Comment by tulasiram58827** [comment]
Thanks @jdduke for the pointers. But with this modifications we need to compile tensorflow from source. Is it possible to add this op in next tensorflow release or atleast in TF Nightly because CTC is something widely used in Speech Recognition engines and also OCR engines. Recently i am working to make on device OCR possible in this [Repository](https://github.com/tulasiram58827/ocr_tflite) But at the end we need a CTC Decoder to do post processing. It would be very great if TFLite team can add support to CTC op.

**Comment by jdduke** [comment]
@tulasiram58827 can you confirm that, by building from source with that op included as a custom op, your model runs successfully? If so, we can look into adding it as a builtin operator. Thanks. It would also help if you can attach the model that is created if you allow custom ops. Thanks.

**Comment by tulasiram58827** [comment]
@jdduke I tried building from source including custom op but it seems like `ctc_beam_search_decoder.cc` file is missing. Please find the error here.

> ERROR: missing input file 'tensorflow/lite/kernels/ctc_beam_search_decoder.cc', owner: '//tensorflow/lite/kernels:ctc_beam_search_decoder.cc'

**Comment by jdduke** [comment]
The kernel is actually defined here: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/experimental/kernels/BUILD#L39. So you would need to add

```
//tensorflow/lite/experimental/kernels:ctc_beam_search_decoder_op
```

to the builtin deps [here](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/kernels/BUILD#L653), then add a line that registers it with the builtin op registry [here](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/kernels/register.cc#L318).

That should make it available for any target you build from source.

**Comment by tulasiram58827** [comment]
Thanks @jdduke .Previous error was resolved. New error popped out.
> ERROR: /home/ram/Projects/tensorflow/tensorflow/lite/kernels/BUILD:781:1: C++ compilation of rule '//tensorflow/lite/kernels:builtin_ops' failed (Exit 1)
tensorflow/lite/kernels/register.cc: In constructor 'tflite::ops::builtin::BuiltinOpResolver::BuiltinOpResolver()':
tensorflow/lite/kernels/register.cc:322:26: error: 'tflite::ops::experimental' has not been declared
             tflite::ops::experimental::Register_CTC_BEAM_SEARCH_DECODER());

**Comment by jdduke** [comment]
You need to forward declare it first, e.g., https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/kernels/register.cc#L27,  but in the right experimental namespace.

**Comment by tulasiram58827** [comment]
Hi @jdduke With the new version of TensorFlow 2.4 my conversion of CTC Decoder is successful by enabling TFLite Ops 
```
converter.target_spec.supported_ops = [
          tf.lite.OpsSet.TFLITE_BUILTINS, # enable TensorFlow Lite ops.
          tf.lite.OpsSet.SELECT_TF_OPS # enable TensorFlow ops.
      ]
```

My issue is solved. You can check this [OCR Notebook](https://github.com/tulasiram58827/ocr_tflite/blob/main/colabs/KERAS_OCR_TFLITE.ipynb) where I successfully used and converted CTC Decoder to TFLite.

**Comment by jdduke** [comment]
Great!
