### ISSUE TITLE
//tensorflow/python/kernel_tests:decode_raw_op_test fails with Assertion error

### ISSUE THREAD

**Issue by abhay1722** [tensorflow/tensorflow#33496]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):  Linux Ubuntu 19.04 s390x
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: NA
- TensorFlow installed from (source or binary): Source
- TensorFlow version (use command below): 2.0.0
- Python version: 2.7.16
- Bazel version (if compiling from source): 0.26.1
- GCC/Compiler version (if compiling from source): gcc (Ubuntu 8.3.0-6ubuntu1) 8.3.0
- CUDA/cuDNN version: NA
- GPU model and memory: NA

**Describe the current behavior**
The above test fails with the output array mismatch in [testToComplex64](https://github.com/tensorflow/tensorflow/blob/v2.0.0/tensorflow/python/kernel_tests/decode_raw_op_test.py#L105) and [testToComplex128](https://github.com/tensorflow/tensorflow/blob/v2.0.0/tensorflow/python/kernel_tests/decode_raw_op_test.py#L118).

The cause of failure seems to be in the byte swapping code to solve endianness problem [here](https://github.com/tensorflow/tensorflow/blob/v2.0.0/tensorflow/core/kernels/decode_raw_op.cc#L88). The code doesn't seem to work as intentioned for **complex data**.

**Describe the expected behavior**
The test should pass on s390x.

**Code to reproduce the issue**
```
bazel test //tensorflow/python/kernel_tests:decode_raw_op_test
```

**Other info / logs**
```
AssertionError:
Arrays are not equal

not equal where = (array([0, 0]), array([1, 2]))
not equal lhs = [[ 2.-2.j -3.+3.j]]
not equal rhs = [-2.+2.j  3.-3.j]
Mismatch: 0%
Max absolute difference: 8.48528137
Max relative difference: 2.
 x: matrix([[ 1.+1.j,  2.-2.j, -3.+3.j, -4.-4.j]])
 y: array([[ 1.+1.j, -2.+2.j,  3.-3.j, -4.-4.j]])

======================================================================
FAIL: testToComplex64 (__main__.DecodeRawOpTest)
testToComplex64 (__main__.DecodeRawOpTest)
----------------------------------------------------------------------
AssertionError:
Arrays are not equal

not equal where = (array([0, 0]), array([1, 2]))
not equal lhs = [[ 2.-2.j -3.+3.j]]
not equal rhs = [-2.+2.j  3.-3.j]
Mismatch: 0%
Max absolute difference: 8.485281
Max relative difference: 2.
 x: matrix([[ 1.+1.j,  2.-2.j, -3.+3.j, -4.-4.j]], dtype=complex64)
 y: array([[ 1.+1.j, -2.+2.j,  3.-3.j, -4.-4.j]], dtype=complex64)

----------------------------------------------------------------------
```

**Comment by abhay1722** [comment]
Further Analysis shows that the real and imaginary components in the output are getting swapped with each other causing the array mismatch on Big Endian.
@jiefangxuanyan I could see [PR](https://github.com/tensorflow/tensorflow/pull/9876) for fixing endianness problem in the `decode_raw_op` functionality. However, the tests for complex data types have been recently added and need more changes for incorporating this particular case.
Could you please have a look?

**Comment by rmothukuru** [comment]
In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thanks!

**Comment by rmothukuru** [comment]
@abhay1722,
In the process of reproducing the error, I have cloned the Branch corresponding to TF Version 2.0 and ran the command, 

`bazel test //usr/local/google/home/mothukuru/tensorflow- 2.0/tensorflow/python/kernel_tests:decode_raw_op_test` but it resulted in the below error, 

```
ERROR: The 'test' command is only supported from within a workspace (below a directory having a WORKSPACE file).
See documentation at https://docs.bazel.build/versions/master/build-ref.html#workspace
INFO: Writing tracer profile to '/usr/local/google/home/mothukuru/.cache/bazel/_bazel_mothukuru/d41d8cd98f00b204e9800998ecf8427e/command.profile.gz'
WARNING: --batch mode is deprecated. Please instead explicitly shut down your Bazel server using the command "bazel shutdown".
```. 

Can you please help us reproduce the error. Thanks!

**Comment by abhay1722** [comment]
> @abhay1722,
> In the process of reproducing the error, I have cloned the Branch corresponding to TF Version 2.0 and ran the command,
> 
> `bazel test //usr/local/google/home/mothukuru/tensorflow- 2.0/tensorflow/python/kernel_tests:decode_raw_op_test` but it resulted in the below error,
> 
> ```
> ERROR: The 'test' command is only supported from within a workspace (below a directory having a WORKSPACE file).
> See documentation at https://docs.bazel.build/versions/master/build-ref.html#workspace
> INFO: Writing tracer profile to '/usr/local/google/home/mothukuru/.cache/bazel/_bazel_mothukuru/d41d8cd98f00b204e9800998ecf8427e/command.profile.gz'
> WARNING: --batch mode is deprecated. Please instead explicitly shut down your Bazel server using the command "bazel shutdown".
> ```
> 
> Can you please help us reproduce the error. Thanks!

@rmothukuru I suggest that you run the test from the location where you have cloned the Tensorflow repo.
For instance, If I clone the [repo](https://github.com/tensorflow/tensorflow.git) in the `\home\test` folder, then I must do the following:-
```
cd \home\test\tensorflow\
bazel test //tensorflow/python/kernel_tests:decode_raw_op_test
```
