### ISSUE TITLE
Some of the operators in the model are not supported by the standard TensorFlow Lite runtime!!!

### ISSUE THREAD

**Issue by hzk7287** [tensorflow/tensorflow#33490]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- TensorFlow installed from (source or binary):
- TensorFlow version (or github SHA if from source):

 OS Platform and Distribution: **WIn10**
 TensorFlow installed from  **binary**
  TensorFlow version  **TF2.0 '2.1.0-dev20191015'**

**Provide the text output from tflite_convert**

 and pasting the following:

Some of the operators in the model are not supported by the standard TensorFlow Lite runtime. If those are native TensorFlow operators, you might be able to use the extended runtime by passing --enable_select_tf_ops, or by setting target_ops=TFLITE_BUILTINS,SELECT_TF_OPS when calling tf.lite.TFLiteConverter(). Otherwise, if you have a custom implementation for them you can disable this error with --allow_custom_ops, or by setting allow_custom_ops=True when calling tf.lite.TFLiteConverter(). Here is a list of builtin operators you are using: ADD, CONCATENATION, CONV_2D, FILL, LEAKY_RELU, MEAN, MUL, PACK, RESHAPE, REVERSE_V2, SHAPE, STRIDED_SLICE, TRANSPOSE. Here is a list of operators for which you will need custom implementations: TensorListFromTensor, TensorListReserve, TensorListStack, While.
Traceback (most recent call last):
  File "d:\users\zhenk\anaconda3\envs\tensorflow2.0\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "d:\users\zhenk\anaconda3\envs\tensorflow2.0\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\Users\zhenk\Anaconda3\envs\tensorflow2.0\Scripts\toco_from_protos.exe\__main__.py", line 9, in <module>
  File "d:\users\zhenk\anaconda3\envs\tensorflow2.0\lib\site-packages\tensorflow_core\lite\toco\python\toco_from_protos.py", line 89, in main
    app.run(main=execute, argv=[sys.argv[0]] + unparsed)
  File "d:\users\zhenk\anaconda3\envs\tensorflow2.0\lib\site-packages\tensorflow_core\python\platform\app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "d:\users\zhenk\anaconda3\envs\tensorflow2.0\lib\site-packages\absl\app.py", line 299, in run
    _run_main(main, args)
  File "d:\users\zhenk\anaconda3\envs\tensorflow2.0\lib\site-packages\absl\app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "d:\users\zhenk\anaconda3\envs\tensorflow2.0\lib\site-packages\tensorflow_core\lite\toco\python\toco_from_protos.py", line 52, in execute
    enable_mlir_converter)
Exception: We are continually in the process of adding support to TensorFlow Lite for more ops. It would be helpful if you could inform us of how this conversion went by opening a github issue at https://github.com/tensorflow/tensorflow/issues/new?template=40-tflite-op-request.md
 and pasting the following:

Some of the operators in the model are not supported by the standard TensorFlow Lite runtime. If those are native TensorFlow operators, you might be able to use the extended runtime by passing --enable_select_tf_ops, or by setting target_ops=TFLITE_BUILTINS,SELECT_TF_OPS when calling tf.lite.TFLiteConverter(). Otherwise, if you have a custom implementation for them you can disable this error with --allow_custom_ops, or by setting allow_custom_ops=True when calling tf.lite.TFLiteConverter(). Here is a list of builtin operators you are using: ADD, CONCATENATION, CONV_2D, FILL, LEAKY_RELU, MEAN, MUL, PACK, RESHAPE, REVERSE_V2, SHAPE, STRIDED_SLICE, TRANSPOSE. Here is a list of operators for which you will need custom implementations: TensorListFromTensor, TensorListReserve, TensorListStack, While.

Also, please include a link to a GraphDef or the model if possible.

**Any other info / logs**

Can you help me ? If I want to use this model in TensorFlow Lite , what shall I do? 

Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by ymodak** [comment]
As the error message suggested you will need custom implementations for following operations;
```TensorListFromTensor, TensorListReserve, TensorListStack, While.```

- To make a custom op you may refer https://www.tensorflow.org/lite/guide/ops_custom
- You can also raise a request to add these features in TF by commenting on this issue thread.
  https://github.com/tensorflow/tensorflow/issues/21526
- You can try converting your model using ```TFLITE_BUILTINS, SELECT_TF_OPS``` flags to reduce custom implementation of ops (only a subset of ops can be implemented by this method while others may still require custom implementation )

**Comment by hzk7287** [comment]
Thank you for your reply! I have found this https://github.com/tensorflow/tensorflow/issues/33416. 

vcarpani says "so my problem could be solved by adding TensorListFromTensor, TensorListReserve, TensorListStack, While to the whitelist here and use the standard tensorflow implementation."

**Comment by hzk7287** [comment]
I finally solved this problem using th following code

---------------------------------------------------------------------------------------------------------------
converter.optimizations = [tf.lite.Optimize.OPTIMIZE_FOR_SIZE]
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS, tf.lite.OpsSet.SELECT_TF_OPS]
converter.allow_custom_ops=True
tflite_model = converter.convert()
--------------------------------------------------------------------------------------------------------------

**Comment by hzk7287** [comment]
I have solved  this problem.

**Comment by 2696120622** [comment]
> I finally solved this problem using the following code
> 
> ## converter.optimizations = [tf.lite.Optimize.OPTIMIZE_FOR_SIZE]
> converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS, tf.lite.OpsSet.SELECT_TF_OPS]
> converter.allow_custom_ops=True
> tflite_model = converter.convert()

@hzk7287 
I follow your code, but I still get the same error.
`converter.optimizations = [tf.lite.Optimize.OPTIMIZE_FOR_SIZE]
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS, tf.lite.OpsSet.SELECT_TF_OPS]
converter.allow_custom_ops=True
tflite_model = converter.convert()`

Error as follows.

`RuntimeError                              Traceback (most recent call last)
<ipython-input-13-ca8eb7ec6089> in <module>()
      1 # interpreter = tf.lite.Interpreter(model_content=tflite_model)
----> 2 interpreter.allocate_tensors()
      3 # help(tf.lite.Interpreter)

~\AppData\Roaming\Python\Python36\site-packages\tensorflow_core\lite\python\interpreter.py in allocate_tensors(self)
    242   def allocate_tensors(self):
    243     self._ensure_safe()
--> 244     return self._interpreter.AllocateTensors()
    245 
    246   def _safe_to_run(self):

~\AppData\Roaming\Python\Python36\site-packages\tensorflow_core\lite\python\interpreter_wrapper\tensorflow_wrap_interpreter_wrapper.py in AllocateTensors(self)
    104 
    105     def AllocateTensors(self):
--> 106         return _tensorflow_wrap_interpreter_wrapper.InterpreterWrapper_AllocateTensors(self)
    107 
    108     def Invoke(self):

RuntimeError: Encountered unresolved custom op: TensorListFromTensor.Node number 710 (TensorListFromTensor) failed to prepare.`

I am trying to convert EfficientDet in https://github.com/xuannianz/EfficientDet, which is based on fizyr/keras-retinanet in https://github.com/fizyr/keras-retinanet. 
My tensorflow is 1.15.0.

**Comment by 2696120622** [comment]
> As the error message suggested you will need custom implementations for following operations;
> `TensorListFromTensor, TensorListReserve, TensorListStack, While.`
> 
> * To make a custom op you may refer https://www.tensorflow.org/lite/guide/ops_custom
> * You can also raise a request to add these features in TF by commenting on this issue thread.
>   #21526
> * You can try converting your model using `TFLITE_BUILTINS, SELECT_TF_OPS` flags to reduce custom implementation of ops (only a subset of ops can be implemented by this method while others may still require custom implementation )

@ymodak Hi, Could you share your custom implementations for following operations;
TensorListFromTensor, TensorListReserve, TensorListStack, While? And how to use them?

**Comment by pietermarsman** [comment]
I had a similar error as above using tensorflow 2.2:

```
error: failed to legalize operation 'tf.TensorListReserve'
```

and

```
error: requires element_dtype to be 1-bit/8-bit/16-bit/32-bit/64-bit integer or 16-bit/32-bit/64-bit float type during TF Lite transformation pass
```

I fixed it by using:

```python
converter = TFLiteConverter.from_saved_model(model_dir)
converter.experimental_new_converter = False
converter.optimizations = [tf.lite.Optimize.OPTIMIZE_FOR_SIZE]
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS, tf.lite.OpsSet.SELECT_TF_OPS]
converter.allow_custom_ops=True
tflite_model = converter.convert()
```

Compared to the fix by @hzk7287 in https://github.com/tensorflow/tensorflow/issues/33490#issuecomment-544847214, this also disables the new experimental converter.

**Comment by celikmustafa89** [comment]
> I finally solved this problem using the following code
> 
> ## converter.optimizations = [tf.lite.Optimize.OPTIMIZE_FOR_SIZE]
> converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS, tf.lite.OpsSet.SELECT_TF_OPS]
> converter.allow_custom_ops=True
> tflite_model = converter.convert()

I love you
