### ISSUE TITLE
TFLite slower than Keras on RPi 4

### ISSUE THREAD

**Issue by JesperChristensen89** [tensorflow/tensorflow#33498]
When doing inference on a Raspberry Pi 4 with Keras and Tensorflow installed using `pip`, the inference time is slower using TFLite. 

The initial Keras model is about 20 mb - after converting it to TFLite it is about 2.4 mb. During inference the Keras model processes a sample in about 50 ms and TFLite does it in about 80 ms. 

Initially the pip-installed version of Tensorflow caused errors with TFLite, so I installed TFLite-runtime using this information: https://www.tensorflow.org/lite/guide/python

During inference in TFLite I use the following snippet:
```python
interpreter = tflite.Interpreter(model_path=CHECKPOINT)
interpreter.allocate_tensors()

input_index = interpreter.get_input_details()[0]["index"]
output_index = interpreter.get_output_details()[0]["index"]

for im in images:
	t = time.time()
	
	inp = np.expand_dims(np.expand_dims(im,-1),0)

	interpreter.set_tensor(input_index, inp)
	interpreter.invoke()
	
	predictions = interpreter.get_tensor(output_index)

	print("Time: {}".format(time.time()-t),end="\r")
```

Does anybody have any experience with TFLite on Raspberry Pi? Am I missing something in order accelerate inference further? It seems wrong that inference should be faster in Keras with 10x model size.

**Comment by terryheo** [comment]
@JesperChristensen89 do you still having the issue with recent (2.1) TFLite package?

**Comment by JesperChristensen89** [comment]
@terryheo I actually think I found out that Keras automatically use all cores where as TFlite only use 1.

**Comment by terryheo** [comment]
1. From TF2.3, you can control the number of threads.
https://www.tensorflow.org/versions/r2.3/api_docs/python/tf/lite/Interpreter

2. To get a speed up, you need to quantize your model to integer
https://www.tensorflow.org/lite/performance/model_optimization

Thanks.

**Comment by pritamghanghas** [comment]
we tried with tf2.2, it was still slower than using h5 model. Will try 2.3 soon.
