### ISSUE TITLE
module 'tensorflow' has no attribute 'ConfigProto'

### ISSUE THREAD

**Issue by Grape-A** [tensorflow/tensorflow#33504]
```python
import tensorflow as tf
import os
config = tf.ConfigProto()

AttributeError: module 'tensorflow' has no attribute 'ConfigProto'
```

**Comment by blairhan** [comment]
I guess you're using tensorflow 2.x. In that case, use tf.compat.v1.ConfigProto() instead.

**Comment by ymodak** [comment]
```tf.ConfigProto``` is deprecated in TF 2.0
Configuring device placements, device policy, gpu memory growth etc can still be done in TF 2.0 using [```tf.config.experimental```](https://www.tensorflow.org/api_docs/python/tf/config/experimental)

**Comment by Grape-A** [comment]
> `tf.ConfigProto` is deprecated in TF 2.0
> Configuring device placements, device policy, gpu memory growth etc can still be done in TF 2.0 using [`tf.config.experimental`](https://www.tensorflow.org/api_docs/python/tf/config/experimental)

thank you！

**Comment by Grape-A** [comment]
> I guess you're using tensorflow 2.x. In that case, use tf.compat.v1.ConfigProto() instead.

thank you！

**Comment by gadagashwini** [comment]
@Grape-A, Are you happy to close this if no issue persists. Thanks!

**Comment by mayankpagaria** [comment]
AttributeError: module 'tensorflow.compat' has no attribute 'v1'
