### ISSUE TITLE
No GPU implementation of determinant and no gradient of determinant?

### ISSUE THREAD

**Issue by shawnLeeZX** [tensorflow/tensorflow#3350]
We do not have GPU implementation of determinant calculation and its gradient is not available? It is really nice to have them.

Thanks!

**Comment by concretevitamin** [comment]
Thanks for reporting this.  We most likely will not work on it in the near future.  Marking as "contributions welcome".

**Comment by harpone** [comment]
[Issue on computing log det by Cholesky decomposition](https://github.com/tensorflow/tensorflow/issues/367). Applies to also regular determinant.

**Comment by shawnLeeZX** [comment]
Thanks for pointing it out!

**Comment by alexmonroe87** [comment]
Using tf.matrix_determinant() in the compute graph is not currently possible?

**Comment by harpone** [comment]
It is now (I think), but I guess usually people would like to compute e.g. log det instead of det, and computing det first and then taking log is numerically very unstable. So one would prefer to use e.g. the Cholesky decomposition for symmetric pos def matrices or e.g. LU decomp in the general case.

**Comment by alexmonroe87** [comment]
Does tensorflow have an op for log det or the ops required to do it yourself?

**Comment by harpone** [comment]
As mentioned by RuiShu in the issue 367 thread, you can compute `logdetA = 2*sum(log(diag(chol(A))))` (for a symmetric pos def matrix, such as a correlation matrix), which currently should now be doable with tf ops which also have gradients. Haven't tried that out myself though (I would need logdet for general non-symmetric matrices anyway).

**Comment by alexmonroe87** [comment]
Yes likewise, having the pos def constraint is of no use to me. LU decomposition is not differentiable? Or simply not doable with tf ops?

**Comment by harpone** [comment]
Well basically LU decomposition would be used for computing the *value* of the logdet(M), while there's an explicit expression for the logdet gradient as inv(transpose(M))... so it would be enough if there was a fast GPU op for e.g. LU decomposition (there was some talk in some of the issues about SVD op coming soon, which would also do the trick). Then it would be simple to define a tf op for the logdet and register the gradient as the inverse transpose. So the LU/cholesky etc. wouldn't need to be differentiable (I actually don't know what's the point in having a differentiable Cholesky etc., but then again I haven't read the paper cited in the other issue).

If an LU/SVD op comes up, I could probably work out the logdet...

**Comment by EverettYou** [comment]
@harpone What is the latest progress of the tf op for logdet? I found that the SVD op has been implemented but not its gradient yet. Also do you know how can I see the code for determinant in TF?

**Comment by aselle** [comment]
@EverettYou to see the code search for REGISTER_OP("Determinant") in the repo.

**Comment by yongtang** [comment]
I think the GPU version of the determinant has been added recently by commit (https://github.com/tensorflow/tensorflow/commit/7d0afb0c7ab86c169fdf12c841155409b89126b9)?

**Comment by itsmeolivia** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
