### ISSUE TITLE
Model.fit displays wrong information on progress bars for attrs classes

### ISSUE THREAD

**Issue by trendelkampschroer** [tensorflow/tensorflow#33503]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
Yes, a minimal self-contained python script demonstrating the bug

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
OSX

- TensorFlow installed from (source or binary):
Installed from anaconda

- TensorFlow version (use command below):
1.14

- Python version:
3.6.9

**Describe the current behavior**
Wrong progress bar information [1000/12] overly long progress bar

**Describe the expected behavior**
Correct progress bar information [100/100] progress bar reasonably short

**Code to reproduce the issue**
```python
import attr
import numpy as np

from tensorflow.python.keras import Input, Model
from tensorflow.python.keras.layers import Dense
from tensorflow.python.keras.optimizers import SGD
from tensorflow.python.keras.utils import Sequence


def make_model(D):
    x = Input(shape=[D])
    y = Dense(1, activation=None)(x)
    model = Model(inputs=x, outputs=y)
    model.compile(optimizer=SGD(), loss="mean_squared_error")
    return model


@attr.s
class Feed(Sequence):
    foo = attr.ib(default=np.arange(12))  # Remove this attribute to get the expected behaviour
    batch_size = attr.ib(default=10)
    feature_dimension = attr.ib(default=3)

    def __getitem__(self, idx):
        features = np.random.randn(self.batch_size, self.feature_dimension)
        targets = np.sum(features, axis=1, keepdims=True)
        return features, targets

    def __len__(self):
        return 100


if __name__ == "__main__":
    feed = Feed()
    model = make_model(feed.feature_dimension)
    model.fit(x=feed, epochs=10)
```

**Other info / logs**
The bug is caused by 
```python
def _get_num_samples_or_steps(data, steps_per_epoch):
  """Returns number of samples or steps, and whether to use steps count mode."""
  flat_inputs = nest.flatten(data)
  if hasattr(flat_inputs[0], 'shape'):
    return int(flat_inputs[0].shape[0]), False
  return steps_per_epoch, True
```
in module `tensorflow.python.keras.engine.training_generator`.

`_get_num_samples_or_steps` should always return `steps_per_epoch, True` for a `Sequence` irrespective of the `attrs.Attributes` of the class implementing the `Sequence` interface. 

The statement `if data_utils.is_generator_or_sequence(x):` in module `tensorflow.python.keras.engine.training` is already ensuring that the passed object is a `Sequence` and therefore the call to function `_get_num_samples_or_steps` seems superfluous.

**Comment by rmothukuru** [comment]
Could replicate the error with `TF Version 1.14 and 1.15` and by `importing` from `tensorflow.python.keras` and  `tensorflow.keras` as well.

Here is the [Gist](https://colab.sandbox.google.com/gist/rmothukuru/c2fde49c1f29ff4dff930baf03f9ad81/33503_progressbar.ipynb). Thanks!

**Comment by omalleyt12** [comment]
@trendelkampschroer Thanks for the issue!

This is fixed in the latest tf-nightly: `pip install tf-nightly`
