### ISSUE TITLE
Not allowed to load local resource on chrome

### ISSUE THREAD

**Issue by kingsleyljc** [tensorflow/tensorflow#33509]
I have downloaded the examples/Iris file from github, and follow REAMME.md.
But when I enter the link
`yarn watch`
The server was built, and the chrome came automatically. 
But the css file and js file wasn't called successfully.
 When I read the console, it was said that
**" Not allowed to load local resource file:///C:/Program%20Files/Git/tfjs-examples.44bb3400.css "**
I spent two days finding the answers but i failed. Hope someone could help me..

**Comment by rmothukuru** [comment]
@kingsleyljc,
It looks like this issue is related to TF JS, not Tensorflow. If so, request you to raise an issue in [TF JS Github Repository](https://github.com/tensorflow/tfjs/issues/) because it will be looked in by the respective experts. Thanks!
