### ISSUE TITLE
tf.keras.applications download path should be made configurable.

### ISSUE THREAD

**Issue by indranaut** [tensorflow/tensorflow#33501]
The download path for the models downloaded using tf.keras.applications seems to be hardcoded to `~/.keras/models`.  
This path should be made configurable. 
It will benefit people who have less storage space in their home folder, which is a feature in many large-scale computational clusters.

**Comment by gadagashwini** [comment]
@indranaut, Will it be possible to provide any use case or sample standalone code. Thanks!

**Comment by indranaut** [comment]
@gadagashwini  There is no need for any sample standalone code here.

The issue is simple. When models are downloaded, they are downloaded to `~/.keras/models`. 

But what if the disk quota policy does not allow for a lot of space in the home folder ? Hence, a much better thing would be to make the download path configurable.

**Comment by tanzhenyu** [comment]
The cached_sub_dir is configurable. Do you need anything else?

**Comment by indranaut** [comment]
The arguments `cached_sub_dir` and `cache_dir` are configurable only on directly using `tf.keras.utils.get_file`. They are not configurable when you are using something like `model = `tf.keras.applications.ResNet50(include_top=False, weights='imagenet')` .

I did some digging and found out that in order to download the models to some other folder, one needs to go inside `keras_applications` folder and directly modify the file `resnet50.py`. The modification is to explicitly add an argument called `cache_dir`  and using it in `get_file` function which is called inside `resnet50.py`. 

I think that an ideal solution of this issue would be to cohesively merge `keras_applications` and `tensorflow` repositories along with changes to reflect the configuration of path.

**Comment by tanzhenyu** [comment]
I think this can be achieved via:
1. using tf.keras.utils.get_file, and configure where you wanna download your checkpoint to, say `file_path`.
2. passing `weights=file_path` when you're creating the model.

Let us know if this works for you.

**Comment by tanzhenyu** [comment]
Closing this for now. Let us know if you have any other questions.

**Comment by davymoon** [comment]
Why not move all the model.h5 files from /.keras/models to another directory and then softlink them?
