### ISSUE TITLE
tf.lite operators missing for `tf.nn.ctc_loss`: `Empty`, `InplaceAdd` and `While`

### ISSUE THREAD

**Issue by BeWe11** [tensorflow/tensorflow#33515]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): macOS 10.14.6
- TensorFlow installed from (source or binary): binary
- TensorFlow version (or github SHA if from source): 2.0.0

**Provide the text output from tflite_convert**

```
Some of the operators in the model are not supported by the standard TensorFlow Lite runtime and are not recognized by TensorFlow. If you have a custom implementation for them you can disable this error with --allow_custom_o
ps, or by setting allow_custom_ops=True when calling tf.lite.TFLiteConverter(). Here is a list of builtin operators you are using: ADD, CAST, CONCATENATION, CONV_2D, DIV, EXP, EXPAND_DIMS, FLOOR_DIV, FULLY_CONNECTED, GATHER,
 LESS, LOG, LOG_SOFTMAX, MAXIMUM, MAX_POOL_2D, MEAN, MUL, NEG, ONE_HOT, PACK, PAD, PADV2, RANGE, RESHAPE, SHAPE, SPLIT_V, SQRT, SQUARE, SQUEEZE, STRIDED_SLICE, SUB, SUM, TILE, TRANSPOSE. Here is a list of operators for which
 you will need custom implementations: Empty, InplaceAdd, While.
Traceback (most recent call last):
  File "/Users/ben/miniconda3/envs/wakeword/bin/toco_from_protos", line 10, in <module>
    sys.exit(main())
  File "/Users/ben/miniconda3/envs/wakeword/lib/python3.6/site-packages/tensorflow_core/lite/toco/python/toco_from_protos.py", line 89, in main                                                                                
    app.run(main=execute, argv=[sys.argv[0]] + unparsed)
  File "/Users/ben/miniconda3/envs/wakeword/lib/python3.6/site-packages/tensorflow_core/python/platform/app.py", line 40, in run                                                                                               
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/Users/ben/miniconda3/envs/wakeword/lib/python3.6/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/Users/ben/miniconda3/envs/wakeword/lib/python3.6/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "/Users/ben/miniconda3/envs/wakeword/lib/python3.6/site-packages/tensorflow_core/lite/toco/python/toco_from_protos.py", line 52, in execute                                                                             
    enable_mlir_converter)
Exception: We are continually in the process of adding support to TensorFlow Lite for more ops. It would be helpful if you could inform us of how this conversion went by opening a github issue at https://github.com/tensorflo
w/tensorflow/issues/new?template=40-tflite-op-request.md
 and pasting the following:

Some of the operators in the model are not supported by the standard TensorFlow Lite runtime and are not recognized by TensorFlow. If you have a custom implementation for them you can disable this error with --allow_custom_o
ps, or by setting allow_custom_ops=True when calling tf.lite.TFLiteConverter(). Here is a list of builtin operators you are using: ADD, CAST, CONCATENATION, CONV_2D, DIV, EXP, EXPAND_DIMS, FLOOR_DIV, FULLY_CONNECTED, GATHER,
 LESS, LOG, LOG_SOFTMAX, MAXIMUM, MAX_POOL_2D, MEAN, MUL, NEG, ONE_HOT, PACK, PAD, PADV2, RANGE, RESHAPE, SHAPE, SPLIT_V, SQRT, SQUARE, SQUEEZE, STRIDED_SLICE, SUB, SUM, TILE, TRANSPOSE. Here is a list of operators for which
 you will need custom implementations: Empty, InplaceAdd, While.
```

**Any other info / logs**

I'm trying to convert a keras model using tf.lite. The last layer of the model uses the `tf.nn.ctc_loss` in its `call` method. When I leave this layer off the model, the conversion works just fine.

Apparantly, only three operators are missing from making this work: `Empty`, `InplaceAdd` and `While`.

The error message also says this:
```
2019-10-18 18:19:25.694843: W tensorflow/lite/toco/tflite/operator.cc:2692] Op Empty is a valid TensorFlow op but has not been whitelisted for the TensorFlow Lite flex op set.                                                 
2019-10-18 18:19:25.694848: W tensorflow/lite/toco/tflite/operator.cc:2692] Op InplaceAdd is a valid TensorFlow op but has not been whitelisted for the TensorFlow Lite flex op set.                                            
2019-10-18 18:19:25.694852: W tensorflow/lite/toco/tflite/operator.cc:2692] Op While is a valid TensorFlow op but has not been whitelisted for the TensorFlow Lite flex op set. 
```
Does this mean that the only thing missing from making this work is to somehow add these operators to the whitelist? Is this something that users can do? How are the chances that these operators are going to be included in tf.lite by default in the near feature?

Thanks!

**Comment by haozha111** [comment]
Hi Benjamin,

Simply add those ops into the whitelist won't work, unfortunately. Since 'while' is a control flow op, the flex runtime currently can't run control flow ops.

I'm wondering why do we need compute ctc loss in tflite? isn't it related with training only? if we don't care about computing the loss in inference, i think we can just use the logits and decode the result from it? actually tflite has supported CTC_BEAM_SEARCH_DECODER as a custom op.

**Comment by BeWe11** [comment]
Hey @haozha111, thank you for your response.

I understand where you're coming from. Models trained with CTC loss usually try to return the most likely label sequence for the given input sequence (which would be solved by CTC_BEAM_SEARCH_DECODER).

However, I'm using my model to return the probability that a *given target label sequence* is contained in the input sequence (which is probortional to the CTC loss itself).

In particular, I have a model that predicts phonemes using audio data as input and I am using the CTC loss function to calculate whether a given sequence of phonemes was spoken in an audio file.

A pseudo-code example:
```
target_sequence = ["H", "EH", "L", "L", "OH"]
logits = model.predict(audio)
probability_of_target_sequence = ctc_loss(logits, target_sequence)
```

Using full beam search for this use-case is somewhat wasteful, as the space of relevant label-paths is already known (the valid paths for the given target sequence). Also, if the top-paths returned by the beam search decoder do not include the exact form of the target sequence, the probability of the target sequence can only be calculated indirectly by using the top paths with the smallest edit distance to the target sequence.

Do you see any way to handle this using tf.lite? If this is currently impossible, how likely is it that the required control flow ops will become part of tf.lite in the near future?

Thanks!

**Comment by haozha111** [comment]
Hi,

Thanks for the explanation. I think I understand your use case better now.

I took a stab into the tf.nn.ctc_loss and a similar keras API tf.keras.backend.ctc_batch_cost. Unfortunately tflite can't support either of them at the moment:

1) As you said, the tf.nn.ctc_loss contains unsupported op like tf.Empty, tf.InplaceAdd and While.
2) tf.keras.backend.ctc_batch_cost's implementation is a bit different, but it contains unsupported ops like CTCLoss and While.

That being said, none of those two ctc loss could be supported in TF Lite at the moment..Which is a bit disappointing.

Currently I could suggestion several walk-arounds:
1) Use the CTC_BEAM_SEARCH_DECODER, but the computation cost could be higher.
2) Put the ctc loss function outside of the TF Graph. Compute the loss in your application logic instead.


Thanks!

(As we are working towards a completely new TF Lite converter, hopefully some of the issues here will be easier to tackle with.. please stay tuned).

**Comment by BeWe11** [comment]
Thank you @haozha111 for this explanation. I anticipated this would be the case. I'll try to work-around this issue and I'm looking forward to the revamped tf.lite converter.

**Comment by BeWe11** [comment]
Hey @haozha111,

In https://github.com/tensorflow/tensorflow/issues/30754#issuecomment-549471852 you have described how to use the experimental new optimizer to save RNNs in tf.lite format. Will this optimizer work for the operators missing for the ctc loss?

Thanks!

**Comment by haozha111** [comment]
Unfortunately it won't. Since CTC loss requires more ops like 'Empty' and 'InplaceAdd'.

**Comment by CatalinVoss** [comment]
@BeWe11 curious: have you found a workaround or a speedy implementation for your CTC calculation use case?

**Comment by saikumarchalla** [comment]
@BeWe11  Is it still an issue for you? If not, please go ahead and close the issue.Thanks!

**Comment by BeWe11** [comment]
Hey @saikumarchalla,

First, thank you for not auto-closing this issue. Unfortunately, I'm not working on this project anymore and don't have the time right now to write a new test-case. Feel free to close this issue.
