### ISSUE TITLE
Error while trying to use tf.broadcast_weights 

### ISSUE THREAD

**Issue by MeghnaNatraj** [tensorflow/tensorflow#33526]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux (Google Colab)
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: Google Colab
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.0
- Python version: 3.x
- Bazel version (if compiling from source): -
- GCC/Compiler version (if compiling from source): -
- CUDA/cuDNN version: -
- GPU model and memory: - 

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
Unable to import tf.broadcast_weights in TF 2.0. 

**Describe the expected behavior**
Should be able to import tf.broadcast_weights in TF 2.0

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

Method 1: Plain python + TF 2.0
```
import tensorflow as tf     # version 2.0
tf.broadcast_weights
```
_throws_ ** AttributeError: module 'tensorflow' has no attribute 'broadcast_weights'**

Method 2: Codelab
I found this error in a recent TF 2.0 + Keras tutorial - https://colab.sandbox.google.com/drive/1UCJt8EYjlzCs1H1d1X0iDGYJsHKwu-NO

- Search for "broadcast_weights" in this codelab. 
- Run all cells before this.
- Modify code "m.update_state([0, 1, 1, 1], [0, 1, 0, 0])" to "m.update_state([0, 1, 1, 1], [0, 1, 0, 0]), sample_weight=[0.1,0.2,0.3,0.4]"
- Run this cell
- throws AttributeError: module 'tensorflow' has no attribute 'broadcast_weights'

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by ravikyram** [comment]
I have tried on colab with TF version 2.0  and was able to reproduce the issue. Please, find the gist here.[Method1](https://colab.sandbox.google.com/gist/ravikyram/a2a526b2e1d95d7a70d6361efdc04da9/tensorflow-2-0-keras-crash-course.ipynb) and [Method2](https://colab.sandbox.google.com/gist/ravikyram/dc8967174fec9d63a6630c2bff684c10/untitled288.ipynb).Thanks!

**Comment by jvishnuvardhan** [comment]
@MeghnaNatraj Thanks for finding the bug in the doc. Could you point us to the source of the notebook. Where did find this link? Thanks!

**Comment by MeghnaNatraj** [comment]
@jvishnuvardhan I found this issue while playing with a recent tutorial published by François Chollet
http://link.oreilly.com/P000Q3rFWM0iPY010sCSs30
(Original Link: https://colab.sandbox.google.com/drive/1UCJt8EYjlzCs1H1d1X0iDGYJsHKwu-NO)
Search for "tf.broadcast_weights" in this tutorial.

Usage 2:
This API is also used in the TF website here: https://www.tensorflow.org/api_docs/python/tf/keras/metrics/Metric

Definition:
https://github.com/tensorflow/tensorflow/blob/9590c4c32dd4346ea5c35673336f5912c6072bf2/tensorflow/python/ops/weights_broadcast_ops.py#L136

**Comment by jvishnuvardhan** [comment]
@MeghnaNatraj Thanks for the links. First link is already updated by the author. We will work on updating link in the `Usage 2`. Thanks!

**Comment by jvishnuvardhan** [comment]
@MarkDaoust I think we need to update [this page](https://www.tensorflow.org/api_docs/python/tf/keras/metrics/Metric). The issue is in this line 

`sample_weight = tf.broadcast_weights(sample_weight, values)`

where `tf.broadcast_weights` throws `AttributeError: module 'tensorflow' has no attribute 'broadcast_weights'`. 

I don't think this tf.broadcast_weights is exposed to the public. Thank you!

**Comment by dubesar** [comment]
@MarkDaoust I confirmed all the codes of the tf.broadcast_weights in https://github.com/tensorflow/tensorflow/blob/9590c4c32dd4346ea5c35673336f5912c6072bf2/tensorflow/python/ops/weights_broadcast_ops.py#L136,
https://github.com/tensorflow/tensorflow/blob/9590c4c32dd4346ea5c35673336f5912c6072bf2/tensorflow/python/ops/metrics.py,
https://github.com/tensorflow/tensorflow/blob/9590c4c32dd4346ea5c35673336f5912c6072bf2/tensorflow/python/ops/metrics_impl.py

And these all seem fine. But still, tf.broadcast_weights throughs Attribute error.

**Comment by MeghnaNatraj** [comment]
tf.broadcast_weights does not work and is still referenced here (https://www.tensorflow.org/api_docs/python/tf/keras/metrics/Metric).

**Comment by yongtang** [comment]
The issue is that `tf.broadcast_weights` is not exposed through `tf_export`, wondering if it makes sense to expose this API given it is referenced in multiple places? 

/cc @tensorflow/api-owners

**Comment by alextp** [comment]
I think we need to remove the reference to tf.broadcast_weights from the documentation.

**Comment by yongtang** [comment]
I take a look at the usage of `tf.broadcast_weights` in docstring. The related docstring is just an example,  and `broadcast_weights` by itself is just to make sure it follow a subset of broadcast rules than `tf.multiply`. It actually makes sense to remove this line as it does not add much to be an example in docs:
    
```diff
         sample_weight = tf.cast(sample_weight, self.dtype)
-        sample_weight = tf.broadcast_weights(sample_weight, values)
         values = tf.multiply(values, sample_weight)
```

Created a PR #39161 for the fix.
