### ISSUE TITLE
how can tf.image.crop_and_resize receive a tensor as crop box? 

### ISSUE THREAD

**Issue by cgcodeboy** [tensorflow/tensorflow#33525]
### I have a proble with tf.image.crop_and_resize()
I have two tensor now, one with a dimension of (4,4,1), the other with a dimension of (1732,1732,3). I tried to get the index of maximum of the first tensor. and use the index multiply 433 as an index to crop the other tensor. But when I use tf.where to get the index, it returns a tensor, the tf.image.crop_and_resize just receive float32 as the box, I use keras to build a model, how can I transform the tensor index into value without run a session.

**Comment by jvishnuvardhan** [comment]
This is not Build/Installation or Bug/Performance issue. Please post this kind of support questions at [Stackoverflow](https://stackoverflow.com/questions/tagged/tensorflow). There is a big community to support and learn from your questions. GitHub is mainly for addressing bugs in installation and performance. Thanks!
