### ISSUE TITLE
Finish making strided_slice equivalent to numpy's strided_slice

### ISSUE THREAD

**Issue by jbuckman** [tensorflow/tensorflow#33534]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using): 1.14
- Are you willing to contribute it (Yes/No): No

**Describe the feature and the current behavior/state.**

Currently, Tensorflow uses a slicing syntax very similar to Numpy's: for example, x[...,:,0:-4] would work equivalently in both TF and Numpy. However, more advanced indexing does not work; for example, trying to use [this approach](https://matthewmcgonagle.github.io/blog/2017/10/13/SelectingSubsquaresWithNumpyIndexing) to get sub-squares from a Tensorflow tensor does not work, and in fact as far as I can tell, clever advanced indexing like this is currently impossible. As a researcher, I'm often trying to do somewhat non-standard things, and I've encountered these indexing issues several times. With TF reaching maturity, it would be good to have these advanced indexing features implemented so that slicing is fully on-par with Numpy.

**Will this change the current api? How?**

No, it will integrate seamlessly, simply providing more functionality.

**Who will benefit with this feature?**

Most advanced users of Tensorflow (especially researchers) will get a lot of benefit from this.

**Any Other info.**

Numpy has already implemented this, so it shouldn't be too difficult to port that code to TF.

**Comment by rmothukuru** [comment]
@jbuckman,
Can you please let us know if [tf.slice](https://www.tensorflow.org/api_docs/python/tf/slice), [tf.gather](https://www.tensorflow.org/api_docs/python/tf/gather) and tf.[gather_nd](https://www.tensorflow.org/api_docs/python/tf/gather_nd) are the APIs that you are looking for? Thanks!
