### ISSUE TITLE
TypeError: Expected Operation, Variable, or Tensor, got 0

### ISSUE THREAD

**Issue by jacpy** [tensorflow/tensorflow#33545]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):NONE
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:NONE
- TensorFlow installed from (source or binary):binary
- TensorFlow version (use command below):2.0
- Python version:3.6
- Bazel version (if compiling from source):NONE
- GCC/Compiler version (if compiling from source):NONE
- CUDA/cuDNN version:NONE
- GPU model and memory:NONE

**Describe the current behavior**
```
File "keras_to_tensorflow.py", line 186, in <module>
    app.run(main)
  File "/home/venv/lib/python3.6/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/home/venv/lib/python3.6/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "keras_to_tensorflow.py", line 132, in main
    model = load_model(FLAGS.input_model, FLAGS.input_model_json, FLAGS.input_model_yaml)
  File "keras_to_tensorflow.py", line 65, in load_model
    model = vgg_blstm_ctc.model(is_training=False, img_size=(256,32), num_classes=11, max_label_length=26)
  File "/home/keras_to_tensorflow/vgg_blstm_ctc.py", line 70, in model
    y = Bidirectional(LSTM(256, kernel_initializer=initializer, return_sequences=True), merge_mode='sum', name='LSTM_1')(rnn_input) # 32*512
  File "/usr/local/lib/python3.6/dist-packages/keras/layers/wrappers.py", line 437, in __call__
    return super(Bidirectional, self).__call__(inputs, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py", line 75, in symbolic_fn_wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/keras/engine/base_layer.py", line 489, in __call__
    output = self.call(inputs, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/keras/layers/wrappers.py", line 530, in call
    initial_state=forward_state, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/keras/layers/recurrent.py", line 2247, in call
    initial_state=initial_state)
  File "/usr/local/lib/python3.6/dist-packages/keras/layers/recurrent.py", line 682, in call
    input_length=timesteps)
  File "/usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py", line 3105, in rnn
    targets=[last_output])
  File "/home/venv/lib/python3.6/site-packages/tensorflow_core/python/keras/utils/tf_utils.py", line 134, in get_reachable_from_inputs
    raise TypeError('Expected Operation, Variable, or Tensor, got ' + str(x))
TypeError: Expected Operation, Variable, or Tensor, got 0
```

**Describe the expected behavior**
when I convert the keras model to the tensorflow model, but I get an error above. anybody can help me?

**Code to reproduce the issue**

the `keras_to_tensorflow.py` file is from [here](https://github.com/amir-abdi/keras_to_tensorflow),  the `vgg_blstm_ctc.py` file is from [here](https://github.com/DevilExileSu/BankCardOCR), the input model is from [here](https://github.com/DevilExileSu/BankCardOCR/tree/master/train/model).I has changed the `keras_to_tensorflow.py` file like this:

```
def load_model(input_model_path, input_json_path=None, input_yaml_path=None):
    if not Path(input_model_path).exists():
        raise FileNotFoundError(
            'Model file `{}` does not exist.'.format(input_model_path))
    try:
        #model = keras.models.load_model(input_model_path)
        model = vgg_blstm_ctc.model(is_training=False, img_size=(256,32), num_classes=11, max_label_length=26)
        return model 
    except FileNotFoundError as err:
        logging.error('Input mode file (%s) does not exist.', FLAGS.input_model)
        raise err
```

**Comment by jvishnuvardhan** [comment]
This is not Build/Installation or Bug/Performance issue. Please post this kind of support questions at [Stackoverflow](https://stackoverflow.com/questions/tagged/tensorflow). There is a big community to support and learn from your questions. GitHub is mainly for addressing bugs in installation and performance. Thanks!

Please post it in Stackoverflow with the standalone code, we will resolve it there. Thanks!

**Comment by jacpy** [comment]
> This is not Build/Installation or Bug/Performance issue. Please post this kind of support questions at [Stackoverflow](https://stackoverflow.com/questions/tagged/tensorflow). There is a big community to support and learn from your questions. GitHub is mainly for addressing bugs in installation and performance. Thanks!
> 
> Please post it in Stackoverflow with the standalone code, we will resolve it there. Thanks!

I have solved the problem, thx.

**Comment by deeplogix-ashutosh** [comment]
> > This is not Build/Installation or Bug/Performance issue. Please post this kind of support questions at [Stackoverflow](https://stackoverflow.com/questions/tagged/tensorflow). There is a big community to support and learn from your questions. GitHub is mainly for addressing bugs in installation and performance. Thanks!
> > Please post it in Stackoverflow with the standalone code, we will resolve it there. Thanks!
> 
> I have solved the problem, thx.

I am facing same problem .Please could you help me for the same

**Comment by dmthinker** [comment]
> > This is not Build/Installation or Bug/Performance issue. Please post this kind of support questions at [Stackoverflow](https://stackoverflow.com/questions/tagged/tensorflow). There is a big community to support and learn from your questions. GitHub is mainly for addressing bugs in installation and performance. Thanks!
> > Please post it in Stackoverflow with the standalone code, we will resolve it there. Thanks!
> 
> I have solved the problem, thx.

I am facing same problem .Please could you help me for this. It seems that when I use the keras.backend.set_learning_phase(0), than the exception will be throwed. What should I do when I convert the h5 to tensorflow pb.

**Comment by dmthinker** [comment]
> > > This is not Build/Installation or Bug/Performance issue. Please post this kind of support questions at [Stackoverflow](https://stackoverflow.com/questions/tagged/tensorflow). There is a big community to support and learn from your questions. GitHub is mainly for addressing bugs in installation and performance. Thanks!
> > > Please post it in Stackoverflow with the standalone code, we will resolve it there. Thanks!
> > 
> > 
> > I have solved the problem, thx.
> 
> I am facing same problem .Please could you help me for the same

If you fix this problem, can you help me for this please. It seems that when I use the keras.backend.set_learning_phase(0), than the exception will be throwed. What should I do when I convert the h5 to tensorflow pb.

**Comment by ManiBlitz** [comment]
@jacpy Can you please provide the solution you for for the problem? I am running into the same issue passing a Tensor for an Embedding layer to an LSTM. That would help me a lot in my researches. Thank you

**Comment by ManiBlitz** [comment]
> @jacpy Can you please provide the solution you for for the problem? I am running into the same issue passing a Tensor for an Embedding layer to an LSTM. That would help me a lot in my researches. Thank you

Solved my issue. Some updates concerning Keras and Tensorflow. The best option so far is replacing:

```import keras as K```

to:

```import tensorflow.python.keras as K```

after updating tensorflow and keras to their latest version.

**Comment by mtobeiyf** [comment]
Use older versions of the libraries would solve the problem
tensorflow==1.13.2
keras==2.2.4

**Comment by crisoracle** [comment]
> @jacpy Can you please provide the solution you for for the problem? I am running into the same issue passing a Tensor for an Embedding layer to an LSTM. That would help me a lot in my researches. Thank you
> 
> Solved my issue. Some updates concerning Keras and Tensorflow. The best option so far is replacing:
> import keras as K
> to:
> import tensorflow.python.keras as K
> after updating tensorflow and keras to their latest version.

thx!!! u'r ans helps me to solve the problem which disturbs me for  a long time

**Comment by adityakpranav** [comment]
> 
> 
> > @jacpy Can you please provide the solution you for for the problem? I am running into the same issue passing a Tensor for an Embedding layer to an LSTM. That would help me a lot in my researches. Thank you
> 
> Solved my issue. Some updates concerning Keras and Tensorflow. The best option so far is replacing:
> 
> `import keras as K`
> 
> to:
> 
> `import tensorflow.python.keras as K`
> 
> after updating tensorflow and keras to their latest version.

thanks bro!! was getting a similar error `TypeError: Expected Operation, Variable, or Tensor, got 1`

**Comment by sadam-99** [comment]
> > > @jacpy Can you please provide the solution you for for the problem? I am running into the same issue passing a Tensor for an Embedding layer to an LSTM. That would help me a lot in my researches. Thank you
> > 
> > 
> > Solved my issue. Some updates concerning Keras and Tensorflow. The best option so far is replacing:
> > `import keras as K`
> > to:
> > `import tensorflow.python.keras as K`
> > after updating tensorflow and keras to their latest version.
> 
> thanks bro!! was getting a similar error `TypeError: Expected Operation, Variable, or Tensor, got 1`



> > This is not Build/Installation or Bug/Performance issue. Please post this kind of support questions at [Stackoverflow](https://stackoverflow.com/questions/tagged/tensorflow). There is a big community to support and learn from your questions. GitHub is mainly for addressing bugs in installation and performance. Thanks!
> > Please post it in Stackoverflow with the standalone code, we will resolve it there. Thanks!
> 
> I have solved the problem, thx.

I tried replacing:
import keras as K
to:
import tensorflow.python.keras as K
But still its is not working, My Both Keras and Tensorflow are also updated. Any idea what other issue could be there?

**Comment by sadam-99** [comment]
> > > @jacpy Can you please provide the solution you for for the problem? I am running into the same issue passing a Tensor for an Embedding layer to an LSTM. That would help me a lot in my researches. Thank you
> > 
> > 
> > Solved my issue. Some updates concerning Keras and Tensorflow. The best option so far is replacing:
> > `import keras as K`
> > to:
> > `import tensorflow.python.keras as K`
> > after updating tensorflow and keras to their latest version.
> 
> thanks bro!! was getting a similar error `TypeError: Expected Operation, Variable, or Tensor, got 1`

I tried replacing:
import keras as K
to:
import tensorflow.python.keras as K
But still its is not working, My Both Keras and Tensorflow are also updated. Any idea what other issue could be there?
