### ISSUE TITLE
I want to train my model on gpu. So i installed everything which given in tensorflow-gpu. But now i want to go back on cpu. So, how to come back on cpu ? 

### ISSUE THREAD

**Issue by NIravMeghani** [tensorflow/tensorflow#33549]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version (use command below):
- Python version:
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**

**Describe the expected behavior**

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by ravikyram** [comment]
Can you please go through the [link](https://www.tensorflow.org/guide/gpu) , #31135 and see if it helps you.Also, please let us know which TensorFlow version you are using ?.Thanks!

**Comment by NIravMeghani** [comment]
tensorflow version 2.0.0

**Comment by NIravMeghani** [comment]
Python 3.7.2 (tags/v3.7.2:9a3ffc0492, Dec 23 2018, 23:09:28) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license()" for more information.
>>> from __future__ import absolute_import, division, print_function, unicode_literals

>>> from __future__ import absolute_import, division, print_function, unicode_literals
>>> import tensorflow as tf
>>> print("Num GPUs Available: ", len(tf.config.experimental.list_physical_devices('GPU')))
Num GPUs Available:  0
>>> tf.debugging.set_log_device_placement(True)
>>> a = tf.constant([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]])
>>> b = tf.constant([[1.0, 2.0], [3.0, 4.0], [5.0, 6.0]])
>>> c = tf.matmul(a, b)
>>> print(c)
tf.Tensor(
[[22. 28.]
 [49. 64.]], shape=(2, 2), dtype=float32)

Num GPUs Available:  0 .....here it's shown no gpu avilable. but i have NVIDIA Geforce 940MX.

**Comment by ymodak** [comment]
Since your system fails to recognize gpu it tells us that tf-gpu was not correctly configured.
Can you please confirm following things;
Did you install TF-GPU version? ```pip install tensorflow-gpu ```
See https://www.tensorflow.org/install/gpu
Downloaded cuda toolkit and updated cuda, cupti, cudnn environment variables?
See https://www.tensorflow.org/install/gpu#software_requirements
