### ISSUE TITLE
Support for Mediapipe tflite ops.

### ISSUE THREAD

**Issue by SanthoshRajendiran** [tensorflow/tensorflow#33557]
**System information**
- TensorFlow version (you are using): 2.0 
- Are you willing to contribute it (Yes/No): Yes

**Describe the feature and the current behavior/state.**
Mediapipe gives some custom implementation for few operators that can run only in Android GPU (Maxunpooling, Maxpoolingwithargmax2d, Convolution2dtransposebias). In tensorflow github repository, they have been mentioned as custom ops. But could not find out implementation for the same.Android GPU delegate does not run the model, and fails with error it is unresolved custom op.

**Will this change the current api? How?**
No. It will be one another addition to the already existing operators in TFLite GPU delegate.

**Who will benefit with this feature?**
Mediapipe, Tensorflow and Android researchers

**Any Other info.**
Attached with this is the sample hair segmentation TFLite, that they are using.

[hair_segmentation.tflite.zip](https://github.com/tensorflow/tensorflow/files/3749221/hair_segmentation.tflite.zip)

**Comment by impjdi** [comment]
Sorry for the late reply; I was out on a conference.

We have been trying to get those ops as part of builtin ops, but this never got prioritized.  Re-assigning to @jdduke

**Comment by jdduke** [comment]
Which version of TensorFlow Lite are you using? In theory, it should now be possible (in the latest nightly) to apply the GPU delegate even if there are unresolved ops.

**Comment by SanthoshRajendiran** [comment]
How to build model with Convolution2DTransposeBias? I did not find any python implementation for the layer.

**Comment by SanthoshRajendiran** [comment]
I checked the latest benchmark, still I am not able to benchmark the hair segmentation model provided by Mediapipe.

Error log is attached below 
[benchmarking_issues.txt](https://github.com/tensorflow/tensorflow/files/3857883/benchmarking_issues.txt)

**Comment by impjdi** [comment]
@SanthoshRajendiran 

Ah, those need to be defined in the op resolver.  Take a look at these for examples:

https://github.com/google/mediapipe/tree/master/mediapipe/util/tflite

**Comment by jdduke** [comment]
Just to be clear, you should still be able to benchmark this with benchmark_model by adding the `--use_gpu=true` flag. It looks like you're not enabling that in your command-line invocation.

**Comment by SanthoshRajendiran** [comment]
Actually, I tried that too.. That is also not working, attaching the error log herewith.
[benchmarking_issues_gpu.txt](https://github.com/tensorflow/tensorflow/files/3878212/benchmarking_issues_gpu.txt)

**Comment by yxchng** [comment]
@impjdi Are you guys going to accept pull requests for this issue? I can help.

**Comment by impjdi** [comment]
@yxchng what exactly are you trying put in the PR?  implementations of those ops?

**Comment by yxchng** [comment]
@impjdi Yup. To make it possible to run MediaPipe models on PC.

**Comment by impjdi** [comment]
@yxchng Thank you for the offer, but that would directly create a conflict with what we have internally.  The best is if you convince TFLite team to make those ops (Maxunpooling, Maxpoolingwithargmax2d, Convolution2dtransposebias) a standard op (note that I'm not a member of the TFLite team directly).  Then, we can open source the three hidden ops.

**Comment by SwatiModi** [comment]
I was facing this issue but got a solution,

The initial code for Opresolver was 
```
tflite::ops::builtin::BuiltinOpResolver resolver;
```
replace it by 
```
builtins.AddCustom("MaxPoolingWithArgmax2D", RegisterMaxPoolingWithArgmax2D());
builtins.AddCustom("MaxUnpooling2D", RegisterMaxUnpooling2D());
builtins.AddCustom("Convolution2DTransposeBias", RegisterConvolution2DTransposeBias());
std::unique_ptr<tflite::Interpreter> interpreter;
tflite::InterpreterBuilder(*model.get(), builtins)(&interpreter);
```

Also add the following code of the Custom Layers from the file 
<a href = "https://github.com/google/mediapipe/blob/master/mediapipe/util/tflite/op_resolver.cc">here</a>
```
TfLiteRegistration* RegisterMaxPoolingWithArgmax2D() {
  static TfLiteRegistration reg = {
      [](TfLiteContext*, const char*, size_t) -> void* {
        return new TfLitePaddingValues();
      },
      [](TfLiteContext*, void* buffer) -> void {
        delete reinterpret_cast<TfLitePaddingValues*>(buffer);
      },
      [](TfLiteContext* context, TfLiteNode* node) -> TfLiteStatus {
        return kTfLiteOk;
      },
      [](TfLiteContext* context, TfLiteNode*) -> TfLiteStatus {
        context->ReportError(
            context, "MaxPoolingWixthArgmax2D is only available on the GPU.");
        return kTfLiteError;
      },
  };
  return &reg;
}

TfLiteRegistration* RegisterMaxUnpooling2D( ) {
  static TfLiteRegistration reg = {nullptr, nullptr, nullptr, nullptr};
  return &reg;
}

TfLiteRegistration* RegisterConvolution2DTransposeBias() {
  static TfLiteRegistration reg = {nullptr, nullptr, nullptr, nullptr};
  return &reg;
}
```

And include the following headers
```
#include "mediapipe/mediapipe/util/tflite/op_resolver.h"
#include "tensorflow/lite/builtin_op_data.h"
```

**Comment by rmothukuru** [comment]
@SanthoshRajendiran,
Can you please refer [this documentation](https://www.tensorflow.org/lite/examples/segmentation/overview) and let us know if this is what you are looking for? Also, please refer to the documentation for [Pose Estimation](https://www.tensorflow.org/lite/examples/pose_estimation/overview) and [Object Detection](https://www.tensorflow.org/lite/examples/object_detection/overview). 

Hope this helps. Thanks!
