### ISSUE TITLE
I have installed tensorflow 2.0 through Anaconda prompt, however the jupyternotebook can't find the tf2.0 module.

### ISSUE THREAD

**Issue by bugzhu** [tensorflow/tensorflow#33554]
**System information**
- Window 10 operation system
- TensorFlow 2.0:
- Python 3.6:
- Installed using pip;
- Downloaded from pypi.org.

**Problem**
I have installed TensorFlow 2.0 through Anaconda prompt, however, the jupyter notebook can't find the TensorFlow module. The detailed error is 

> ModuleNotFoundError: No module named 'tensorflow'.

Through the command 'pip list', I can find the TF 2.0.0 in my env. Meanwhile, when I using PyCharm in the env with TF 2.0.0, the PyCharm can find the TF 2.0.0 module.

**Comment by gowthamkpr** [comment]
**Try installing tensorflow this way:**

Create a virtual environment (recommended)

```
(base) C:\Users\XXXX>conda create -n venv pip python=3.6
(base) C:\Users\XXXX>conda activate venv
(venv) C:\Users\XXXX>pip install --ignore-installed --upgrade https://storage.googleapis.com/tensorflow/windows/cpu/tensorflow-2.0.0-cp36-cp36m-win_amd64.whl
```

**Then test it in terminal:**

```
(venv) C:\Users\XXXX>python
Python 3.6.8 |Anaconda, Inc.| (default, Feb 21 2019, 18:30:04) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
>>> tf.__version__
```

**Comment by bugzhu** [comment]
Thank you very much. My problem was solved with your method. @gowthamkpr
