### ISSUE TITLE
Failure to build tensorflow in Ubuntu

### ISSUE THREAD

**Issue by photogazer** [tensorflow/tensorflow#33551]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): source
- TensorFlow version: master 0f752f7368f88b61916a3d1700685d01aff835cc
- Python version: Python 3.6.8
- Installed using virtualenv? pip? conda?:
- Bazel version (if compiling from source): 1.0.0
- GCC/Compiler version (if compiling from source): 7.4.0
- CUDA/cuDNN version:
- GPU model and memory:

**Describe the problem**
I am unable to rebuild the tensorflow library.

**Provide the exact sequence of commands / steps that you executed before running into the problem**
Cloned the repository as per instructions on https://www.tensorflow.org/lite/microcontrollers/library. When I tried to build using this command

make -f tensorflow/lite/experimental/micro/tools/make/Makefile test

The build fails:
```
g++ -O3 -DNDEBUG -std=c++11 -g -DTF_LITE_STATIC_MEMORY -DTF_LITE_DISABLE_X86_NEON -I. -Itensorflow/lite/experimental/micro/tools/make/downloads/ -Itensorflow/lite/experimental/micro/tools/make/downloads/gemmlowp -Itensorflow/lite/experimental/micro/tools/make/downloads/flatbuffers/include -Itensorflow/lite/experimental/micro/tools/make/downloads/kissfft -c tensorflow/lite/experimental/micro/kernels/logical.cc -o tensorflow/lite/experimental/micro/tools/make/gen/linux_x86_64/obj/tensorflow/lite/experimental/micro/kernels/logical.o
In file included from ./tensorflow/lite/kernels/internal/reference/binary_function.h:18:0,
                 from tensorflow/lite/experimental/micro/kernels/logical.cc:16:
./tensorflow/lite/kernels/internal/common.h:24:10: fatal error: fixedpoint/fixedpoint.h: No such file or directory
 #include "fixedpoint/fixedpoint.h"
          ^~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
tensorflow/lite/experimental/micro/tools/make/Makefile:244: recipe for target 'tensorflow/lite/experimental/micro/tools/make/gen/linux_x86_64/obj/tensorflow/lite/experimental/micro/kernels/logical.o' failed
make: *** [tensorflow/lite/experimental/micro/tools/make/gen/linux_x86_64/obj/tensorflow/lite/experimental/micro/kernels/logical.o] Error 1
```

**Comment by yongtang** [comment]
@photogazer I noticed you are using Bazel 1.0.0. If I remember bazel 1.0.0 is still not supported yet. Could try with bazel 0.29.1 and see if the issue persists?

**Comment by photogazer** [comment]
> @photogazer I noticed you are using Bazel 1.0.0. If I remember bazel 1.0.0 is still not supported yet. Could try with bazel 0.29.1 and see if the issue persists?

I am now on bazel 0.29.1, but I am seeing the same error.

**Comment by angerson** [comment]
@rmothukuru This is a TF Lite build issue. Can you re-triage to one of their build experts, please? I'm not sure who owns the microcontroller builds here.

**Comment by rockyrhodes** [comment]
This header file, fixedpoint.h, should have been downloaded by the make command to the tensorflow/lite/experimental/micro/tools/make/downloads/gemmlowp/fixedpoint/ directory.  Could you check if this gemmlowp directory has been successfully downloaded?  Possibly there was some issue with this download that scrolled by in your error log?

Also, the make command you executed is trying to build the tests for your host operating system, an x86 system.  If you want to compile code for a microcontroller platform, you'll need to compile for a specific target, set by adding TARGET=xxx on your commandline, as noted in that documentation you referenced.

**Comment by photogazer** [comment]
Yes, fixedpoint.h is located at the location you have indicated.

Strangely, when I try to rerun the same command to build tonight, the build went through to completion: 

```
~~~ALL TESTS PASSED~~~

tensorflow/lite/experimental/micro/tools/make/gen/linux_x86_64/bin/kernel_add_test: PASS
```

I did not rebase. So perhaps there was a temporary issue connecting to a server last week. In any case I no longer see the build issue for now. Thanks for the help!

**Comment by rockyrhodes** [comment]
Glad you got it figured out!
