### ISSUE TITLE
Incorrect Arduino Person Detection .zip package

### ISSUE THREAD

**Issue by smellslikeml** [tensorflow/tensorflow#33552]
## URL(s) with the issue:
https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/experimental/micro/examples/person_detection
https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/experimental/micro/examples/person_detection#obtain-and-import-the-library

## Description of issue (what needs changing):
Under the heading "Obtain and Import the Library", the link incorrectly refers to the micro_speech.zip package instead of a person_detection example.

**Comment by Samsomyajit** [comment]
I am taking this problem!

**Comment by Samsomyajit** [comment]
@smellslikeml  would you please elaborate on this issue...

**Comment by smellslikeml** [comment]
@Samsomyajit Certainly, both "person_detection" and the "magic_wand" Arduino demos under tensorflow/lite/experimental/micro/examples (under heading: Obtain and Import the Library) incorrectly link the micro_speech.zip and the hello_world.zip packages, respectively.

**Comment by Samsomyajit** [comment]
@smellslikeml That probaby deals with our problem here...

**Comment by smellslikeml** [comment]
@Samsomyajit thanks! Look forward to the update.

**Comment by mayorquinmachines** [comment]
@Samsomyajit I think I found the package! 
https://storage.googleapis.com/tensorflow-nightly/github/tensorflow/tensorflow/lite/experimental/micro/tools/make/gen/arduino_x86_64/prj/person_detection/tensorflow_lite.zip

It's named tensorflow_lite.zip instead of person_detection.zip

**Comment by Samsomyajit** [comment]
Hey, I was looking for the link to the library.....thank you!
😊

**Comment by Samsomyajit** [comment]
@smellslikeml I have updated the link to the library. Thnx for the link

**Comment by gowthamkpr** [comment]
@smellslikeml Can I close this issue as the update to the docs is being tracked [here](https://github.com/tensorflow/tensorflow/pull/33579). Thanks!

**Comment by smellslikeml** [comment]
@gowthamkpr Sure! Thank you :)
