### ISSUE TITLE
[TF 2.0] repeatdataset has no attribute 'make_one_shot_iterator'

### ISSUE THREAD

**Issue by yeonsookKwak** [tensorflow/tensorflow#33555]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):window10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version (use command below):2.0.0
- Python version:3
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:colab

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
when I tried to train with estimator object, i can see this error below.
AttributeError: 'RepeatDataset' object has no attribute 'make_one_shot_iterator'
def mapping_fn(X,Y):
  input, labels = {'x':X},Y
  return input,labels

def train_input_fn():
  dataset = tf.data.Dataset.from_tensor_slices((input_train, label_train))
  dataset = dataset.shuffle(buffer_size = len(input_train))
  dataset = dataset.batch(BATCH_SIZE)
  dataset = dataset.map(mapping_fn)
  dataset = dataset.repeat(count = NUM_EPOCHS)
  iterator = dataset.make_one_shot_iterator()

  return iterator.get_next()

def eval_input_fn():
  dataset = tf.data.Dataset.from_tensor_slices((input_eval, label_eval))
  dataset = dataset.shuffle(buffer_size = len(input_eval))
  dataset = dataset.batch(16)
  dataset = dataset.map(mapping_fn)
  iterator =dataset.make_one_shot_iterator()

  return iterator.get_next()

wirh model_fn = CNN, RNN model 
est = tf.estimator.Estimator(model_fn, model_dir = "/content/gdrive/checkpoint/cnn_model")
est.train(train_input_fn)

**Describe the expected behavior**

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by gowthamkpr** [comment]
As per Release 2.0.0-alpha0, tf.data.Dataset.make_one_shot_iterator() has been deprecate in V1, removed from V2, and added to tf.compat.v1.data.make_one_shot_iterator(). 

For more details you can refer to the following [issue](https://github.com/tensorflow/tensorflow/issues/29252)
