### ISSUE TITLE
tf.keras.Model.fit ignores class_weight when passed tf.data.Dataset

### ISSUE THREAD

**Issue by mmilosav** [tensorflow/tensorflow#33550]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): MacOS 10.14.6 or Colab
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.0.0, 1.15.0-rc3
- Python version: 3.7
- CUDA/cuDNN version:
- GPU model and memory: None or Colab

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**

`tf.keras.Model.fit` ignores `class_weight` when passed a `tf.data.Dataset`.  When passed an instance of `tf.data.Dataset` and a `class_weight` dictionary with nonsensical label keys, it runs without exception, whereas it correctly raises `ValueError` when passed a pair of `np.ndarray`.

**Describe the expected behavior**

`tf.keras.Model.fit` should apply `class_weight` when passed a `tf.data.Dataset`.  It should raise an exception for incorrect `class_weight` keys.

**Code to reproduce the issue**

```python
import tensorflow as tf
import numpy as np

features = np.array([[-1.], [1.]], dtype=np.float32)
labels = np.array([[0], [1]], dtype=np.int32)

dataset = tf.data.Dataset.from_tensor_slices((features, labels)).batch(1)

model = tf.keras.Sequential([tf.keras.layers.Dense(1, activation='sigmoid')])

model.compile(optimizer='sgd', loss='binary_crossentropy')

class_weight = {'bad_negative_label': 0.5, 'bad_positive_label': 0.5}

fit_ops = (('tf.data.Dataset', lambda: model.fit(dataset, class_weight=class_weight, verbose=0)),
           ('np.ndarray', lambda: model.fit(features, labels, class_weight=class_weight, verbose=0)))

for key, fit_op in fit_ops:
    try:
        print(f'fitting {key} with bad class_weight label')
        fit_op()
    except ValueError as e:
        print('failed as it should have')
        raise ValueError from e
    else:
        print('succeded but should have failed')
```

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

```
fitting tf.data.Dataset with bad class_weight label
succeded but should have failed
fitting np.ndarray with bad class_weight label
failed as it should have
Traceback (most recent call last):
  File "scratch.py", line 22, in <module>
    fit_op()
  File "scratch.py", line 17, in <lambda>
    ('np.ndarray', lambda: model.fit(features, labels, class_weight=class_weight, verbose=0)))
  File "/usr/local/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training.py", line 728, in fit
    use_multiprocessing=use_multiprocessing)
  File "/usr/local/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training_v2.py", line 224, in fit
    distribution_strategy=strategy)
  File "/usr/local/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training_v2.py", line 547, in _process_training_inputs
    use_multiprocessing=use_multiprocessing)
  File "/usr/local/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training_v2.py", line 594, in _process_inputs
    steps=steps)
  File "/usr/local/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training.py", line 2530, in _standardize_user_data
    feed_sample_weight_modes)
  File "/usr/local/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training.py", line 2529, in <listcomp>
    for (ref, sw, cw, mode) in zip(y, sample_weights, class_weights,
  File "/usr/local/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training_utils.py", line 946, in standardize_weights
    '`class_weight`.' % (existing_classes - existing_class_weight))
ValueError: `class_weight` must contain all classes in the data. The classes {0, 1} exist in the data but not in `class_weight`.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "scratch.py", line 25, in <module>
    raise ValueError from e
ValueError

Process finished with exit code 1
```

**Comment by gadagashwini** [comment]
I could reproduce the issue on colab with TF 2.0.0.
Please see the gist [here](https://colab.sandbox.google.com/gist/gadagashwini/12fbb6df6ff8c99dce74b1464b725141/untitled213.ipynb). Thanks

**Comment by mmilosav** [comment]
Could it be that the call to `model._standardize_user_data` in training_v2.py:
https://github.com/tensorflow/tensorflow/blob/8b324344adacdfd37587d1fa591aab0e6a23a6ac/tensorflow/python/keras/engine/training_v2.py#L641
should also be passed `extract_tensors_from_dataset=True`?

**Comment by mmilosav** [comment]
p.s. Or, could it be that calling `train_on_batch` by running `strategy.experimental_run_v2` on `per_replica_function` in https://github.com/tensorflow/tensorflow/blob/8b324344adacdfd37587d1fa591aab0e6a23a6ac/tensorflow/python/keras/engine/training_v2_utils.py#L72 
is failing to pass the `class_weight` to `train_on_batch`?  (Unless there is a partial binding of `class_weight` kwarg to `train_on_batch` somewhere, but I don't see it.).   
Thank you.

**Comment by jvdgoltz** [comment]
We are having a similar problem. It would be nice if we could use class_weights in model.fit() instead of relying on adding a sample weight to the tf.data.Dataset (x, y, weight).

**Comment by mmilosav** [comment]
It is very dangerous for the training behavior to completely change, in terms of applying vs. ignoring without any warning the `class_weight` kwarg, simply by going from `model.fit(x, y, class_weight=class_weight, ...)` to `model.fit(tf.data.Dataset.from_tensor_slices((x, y)).batch(...), class_weight=class_weight, ...)`.  

Consider for example the [Classification on imbalanced data](https://www.tensorflow.org/tutorials/structured_data/imbalanced_data) tutorial that specifically demos `class_weight`.  By simply replacing `train_features, test_features` with `tf.data.Dataset.from_tensor_slices((train_features, test_features)).batch(BATCH_SIZE)` (and similar for `validation_data`, and also removing the `batch_size` kwarg in `model.fit`), the tutorial example **fails** to apply `class_weight`, again, without any warning.

**Comment by Liu-Da** [comment]
Has this problem been resolved in tf2.1

**Comment by omalleyt12** [comment]
@mmilosav Thanks for the issue!

This has been fixed in the latest tf-nightly: `pip install -U tf-nightly`
