### ISSUE TITLE
Dev-board Interpretere Runtime Error

### ISSUE THREAD

**Issue by adish333** [tensorflow/tensorflow#33558]
I am working on the Coral dev board. I'm trying to deploy a segmentation model on it. When I'm running my deep lab segmentation model it is giving me the following error-

```
Traceback (most recent call last):
  File "infer.py", line 17, in <module>
    interpreter.allocate_tensors()
  File "/home/mendel/.local/lib/python3.5/site-packages/tflite_runtime/interpreter.py", line 244, in allocate_tensors
    return self._interpreter.AllocateTensors()
  File "/home/mendel/.local/lib/python3.5/site-packages/tflite_runtime/interpreter_wrapper.py", line 114, in AllocateTensors
    return _interpreter_wrapper.InterpreterWrapper_AllocateTensors(self)
RuntimeError: Internal: :71 tf_lite_type != kTfLiteUInt8 (9 != 3)Node number 79 (EdgeTpuDelegateForCustomOp) failed to prepare.
```
The model and script are working fine if I don't make it TPU compatible using edgetpu_compiler.

**Code to reproduce the issue**
```
from tqdm import tqdm
import numpy as np
from tflite_runtime.interpreter import Interpreter
from tflite_runtime.interpreter import load_delegate

test_data = np.random.rand(480,480,3)
img = np.array([test_data], dtype=np.float32)

interpreter = Interpreter(
      model_path="deep_lab_quant_edgetpu.tflite",
      experimental_delegates=[load_delegate('libedgetpu.so.1.0')])

interpreter.allocate_tensors()

input_details = interpreter.get_input_details()
output_details = interpreter.get_output_details()
interpreter.set_tensor(input_details[0]['index'], img)
interpreter.invoke()
output_data = interpreter.get_tensor(output_details[0]['index'])
```

**Comment by mattroos** [comment]
I get the same error for my custom image processing model. I don't truly know the source of the error, but have found that when reducing the size of the model (number of channels in each layer) and/or the input tensor (height and width dimensions), the error goes away.

However, the output of the edgetpu compiler suggests that even my "full-size" model easily fits on the TPU:
```
Input model: model.tflite
Input size: 925.08KiB
Output model: model_edgetpu.tflite
Output size: 1.04MiB
On-chip memory available for caching model parameters: 5.78MiB
On-chip memory used for caching model parameters: 1019.75KiB
Off-chip memory used for streaming uncached model parameters: 0.00B
Number of Edge TPU subgraphs: 1
Total number of operations: 54
Operation log: model_edgetpu.log
```

**Comment by adish333** [comment]
@mattroos thanks for your suggestion. This did not solve my error though!
Below is the output log of edgetpu compilation of .tflite model. I'm using deeplab for segmentation. let me know if you are able to capture any error here.
Also, can you suggest me any other model which can be run on coral dev board?
Thanks. 
```
Edge TPU Compiler version 2.0.267685300
Input: deep_lab_quant.tflite
Output: deep_lab_quant_edgetpu.tflite

Operator                       Count      Status

QUANTIZE                       1          More than one subgraph is not supported
QUANTIZE                       1          Operation is otherwise supported, but not mapped due to some unspecified limitation
MUL                            10         More than one subgraph is not supported
RESHAPE                        1          More than one subgraph is not supported
RESIZE_BILINEAR                2          Image-interpolation layer won't run precisely enough on Edge TPU
ADD                            3          Mapped to Edge TPU
ADD                            7          More than one subgraph is not supported
CONCATENATION                  1          More than one subgraph is not supported
CONV_2D                        15         Mapped to Edge TPU
CONV_2D                        23         More than one subgraph is not supported
DEPTHWISE_CONV_2D              7          Mapped to Edge TPU
DEPTHWISE_CONV_2D              10         Tensor has unsupported rank (up to 3 innermost dimensions mapped)
BATCH_TO_SPACE_ND              10         Operation not supported
DEQUANTIZE                     1          Operation is working on an unsupported data type
SPACE_TO_BATCH_ND              10         Tensor has unsupported rank (up to 3 innermost dimensions mapped)
MEAN                           1          More than one subgraph is not supported
```

**Comment by mattroos** [comment]
See one of my EdgeTPU testing scripts, here: https://github.com/mattroos/EdgeTpuTesting/blob/master/test_edgetpu.ipynb
It builds, converts (to quantized INT8 model), compiles, and runs a very simple model (nothing but a max pooling layer). It works for me, and I've also successfully tried conv2d, relu, add, and separable conv2d layers. [Note that the output cells in the notebook don't really match the code in the cells, because I edited some of the code and saved the notebook before re-running it. But it does work for me, with layers "Mapped to Edge TPU" and giving meaningful output.]

Obviously this model doesn't do anything useful. It's just confirms that small, simple models can be run on the EdgeTPU.

**Comment by Namburger** [comment]
@adish333 @mattroos 
Nam from Coral Team here, apologize for the issue. We currently have not supported models with tf2.0 yet. Could you guys run into the same issue if downgrading to tf1.5?

**Comment by mattroos** [comment]
I'll give it a try. @Namburger, did you really mean tf1.5? Did you possibly mean tf1.15?

**Comment by Namburger** [comment]
@mattroos sorry, tf1.15

**Comment by mattroos** [comment]
@Namburger, I gave it a try but can't be past the conversion of the model from the saved keras format to the tflite format. When I instantiate the converter I get warning, but no errors:
```
>>> converter = tf.lite.TFLiteConverter.from_keras_model_file('model_keras') # TF1.15
```
```
WARNING:tensorflow:From /home/mroos/python_envs/env_tensorflow1.15/lib/python3.6/site-packages/tensorflow_core/python/ops/init_ops.py:97: calling GlorotUniform.__init__ (from tensorflow.python.ops.init_ops) with dtype is deprecated and will be removed in a future version.
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor
WARNING:tensorflow:From /home/mroos/python_envs/env_tensorflow1.15/lib/python3.6/site-packages/tensorflow_core/python/ops/init_ops.py:97: calling Zeros.__init__ (from tensorflow.python.ops.init_ops) with dtype is deprecated and will be removed in a future version.
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor
WARNING:tensorflow:From /home/mroos/python_envs/env_tensorflow1.15/lib/python3.6/site-packages/tensorflow_core/python/ops/init_ops.py:97: calling GlorotNormal.__init__ (from tensorflow.python.ops.init_ops) with dtype is deprecated and will be removed in a future version.
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor
WARNING:tensorflow:No training configuration found in save file: the model was *not* compiled. Compile it manually.
WARNING:tensorflow:From /home/mroos/python_envs/env_tensorflow1.15/lib/python3.6/site-packages/tensorflow_core/lite/python/util.py:249: convert_variables_to_constants (from tensorflow.python.framework.graph_util_impl) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.compat.v1.graph_util.convert_variables_to_constants`
WARNING:tensorflow:From /home/mroos/python_envs/env_tensorflow1.15/lib/python3.6/site-packages/tensorflow_core/python/framework/graph_util_impl.py:277: extract_sub_graph (from tensorflow.python.framework.graph_util_impl) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.compat.v1.graph_util.extract_sub_graph`
INFO:tensorflow:Froze 60 variables.
INFO:tensorflow:Converted 60 variables to const ops.
```

Then when I call convert(), I get an error that I can't interpret:
```
>>> converter.optimizations = [tf.lite.Optimize.DEFAULT]
>>> converter.representative_dataset = tf.lite.RepresentativeDataset(representative_dataset_gen)
>>> converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8] # For EdgeTPU, no float ops allowed
>>> tflite_model = converter.convert()
```
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-8-7698de81c241> in <module>
----> 1 tflite_model = converter.convert()
      2 open('model.tflite', 'wb').write(tflite_model)

~/python_envs/env_tensorflow1.15/lib/python3.6/site-packages/tensorflow_core/lite/python/lite.py in convert(self)
    991     if self._is_calibration_quantize():
    992       result = self._calibrate_quantize_model(result, inference_input_type,
--> 993                                               inference_output_type)
    994 
    995     return result

~/python_envs/env_tensorflow1.15/lib/python3.6/site-packages/tensorflow_core/lite/python/lite.py in _calibrate_quantize_model(self, result, inference_input_type, inference_output_type)
    237     return calibrate_quantize.calibrate_and_quantize(
    238         self.representative_dataset.input_gen, inference_input_type,
--> 239         inference_output_type, allow_float)
    240 
    241   def _get_base_converter_args(self):

~/python_envs/env_tensorflow1.15/lib/python3.6/site-packages/tensorflow_core/lite/python/optimize/calibrator.py in calibrate_and_quantize(self, dataset_gen, input_type, output_type, allow_float)
     73     self._calibrator.Prepare()
     74     for calibration_sample in dataset_gen():
---> 75       self._calibrator.FeedTensor(calibration_sample)
     76     return self._calibrator.QuantizeModel(
     77         np.dtype(input_type.as_numpy_dtype()).num,

~/python_envs/env_tensorflow1.15/lib/python3.6/site-packages/tensorflow_core/lite/python/optimize/tensorflow_lite_wrap_calibration_wrapper.py in FeedTensor(self, input_value)
    110 
    111     def FeedTensor(self, input_value):
--> 112         return _tensorflow_lite_wrap_calibration_wrapper.CalibrationWrapper_FeedTensor(self, input_value)
    113 
    114     def QuantizeModel(self, input_py_type, output_py_type, allow_float):

ValueError: Failed to convert value into readable tensor.
```

**Comment by Namburger** [comment]
@mattroos Thanks for trying, any chance you are converting the saved keras model that was created with tf2.0?
If it was created with tf1.15 and you are still having issue converting, then we might need to wait for a tensorflower to help out on this one :/

**Comment by mattroos** [comment]
@Namburger, I used a single script to create, save, and (attempt to) convert the model under TF1.15.

**Comment by mattroos** [comment]
@Namburger, I thought I'd try using the tflite_runtime interpreter rather than the tensorflow interpreter, to see if that made any difference.  I installed the tflite_runtime package for python 3.6, using the wheel linked here: [https://www.tensorflow.org/lite/guide/python](https://www.tensorflow.org/lite/guide/python)

When I try to instantiate the interpreter, 
```
from tflite_runtime.interpreter import load_delegate
from tflite_runtime.interpreter import Interpreter
interpreter = Interpreter(model_path='model_edgetpu.tflite',
                          model_content=None,
                          experimental_delegates=[load_delegate('libedgetpu.so.1.0')])
```
I get this error:
```
---------------------------------------------------------------------------
NotImplementedError                       Traceback (most recent call last)
<ipython-input-7-2755d7c8d022> in <module>
      6 #     interpreter = Interpreter(model_path='model_edgetpu.tflite',
      7 #                               experimental_delegates=[load_delegate('libedgetpu.so.1.0')])
----> 8     interpreter = Interpreter(model_path='model_edgetpu.tflite', model_content=None, experimental_delegates=[load_delegate('libedgetpu.so.1.0')])
      9 
     10 #     # if using full TensorFlow package...

~/python_envs/env_tf_nightly/lib/python3.6/site-packages/tflite_runtime/interpreter.py in __init__(self, model_path, model_content, experimental_delegates)
    204       self._interpreter = (
    205           _interpreter_wrapper.InterpreterWrapper_CreateWrapperCPPFromFile(
--> 206               model_path))
    207       if not self._interpreter:
    208         raise ValueError('Failed to open {}'.format(model_path))

NotImplementedError: Wrong number or type of arguments for overloaded function 'InterpreterWrapper_CreateWrapperCPPFromFile'.
  Possible C/C++ prototypes are:
    tflite::interpreter_wrapper::InterpreterWrapper::CreateWrapperCPPFromFile(char const *,std::vector< std::string > const &,std::string *)
    tflite::interpreter_wrapper::InterpreterWrapper::tflite_interpreter_wrapper_InterpreterWrapper_CreateWrapperCPPFromFile__SWIG_1(char const *,PyObject *)
```
I've tried to initialize the interpreter with a subset of the initializing, arguments, but to no avail.

Any guesses? Maybe I should submit a new issue about this.

**Comment by adish333** [comment]
@Namburger Thanks for the suggestion. Our code worked after downgrading to tf 1.15 and retraining the Keras model.

**Comment by mattroos** [comment]
@adish333, do you mind sharing the lines of code you used for your working, TF1.15 conversion? E.g., did you set values for these attributes before calling convert()? Others?
```
converter.inference_input_type = tf.float32
converter.inference_output_type = tf.float32
```

**Comment by JiatianWu** [comment]
@mattroos I met the same issue when I tried to do post-training quantization:

`Traceback (most recent call last):
  File "convert_tf.py", line 183, in <module>
    convert_pb_lite_quant()
  File "convert_tf.py", line 80, in convert_pb_lite_quant
    tflite_quant_model = converter.convert()
  File "/home/jiatian/.local/lib/python3.6/site-packages/tensorflow_core/lite/python/lite.py", line 994, in convert
    inference_output_type)
  File "/home/jiatian/.local/lib/python3.6/site-packages/tensorflow_core/lite/python/lite.py", line 240, in _calibrate_quantize_model
    inference_output_type, allow_float)
  File "/home/jiatian/.local/lib/python3.6/site-packages/tensorflow_core/lite/python/optimize/calibrator.py", line 76, in calibrate_and_quantize
    self._calibrator.FeedTensor(calibration_sample)
  File "/home/jiatian/.local/lib/python3.6/site-packages/tensorflow_core/lite/python/optimize/tensorflow_lite_wrap_calibration_wrapper.py", line 113, in FeedTensor
    return _tensorflow_lite_wrap_calibration_wrapper.CalibrationWrapper_FeedTensor(self, input_value)
ValueError: Failed to convert value into readable tensor.
` 
Did you solve this?

**Comment by mattroos** [comment]
@JiatianWu, I think I had been using one of the nightly versions of tf1.15. After switching to tf1.15.0, that error went away.
```
pip install tensorflow==1.15.0
```
I still get an error similar that of the original poster, however,
```
RuntimeError: Internal: :71 tf_lite_type != kTfLiteUInt8 (9 != 3)Node number 79 (EdgeTpuDelegateForCustomOp) failed to prepare.
```
when I build and run a model in which the input tensor is "too large", even with small models and an input tensor that isn't particularly large (e.g., (256, 256, 3) input into a model with one conv2d layer that has three input channels and 256 output channels).

**Comment by alexanderfrey** [comment]
Same problem here with input tensors that are too large. @mattroos Did you solve your problem ?

**Comment by mattroos** [comment]
No, @alexanderfrey. I've been told by the coral support team that this a problem with the EdgeTPU runtime code, which is provided by their team of engineers (initial release was version 10, current release is version 12). They claimed it would be fixed in a future release but would not give a release date estimate. I'm not even sure it will be resolved in the next release, versus one further down the road. Hard to plan ahead on my projects with this kind of timeline-less problem.

**Comment by git-hamza** [comment]
There is a new update from the coral team. Please have a look at it, you will find your solution. [January 2020 Updates ](https://coral.ai/news/updates-01-2020/)

**Comment by mattroos** [comment]
I haven't fully tested it, but at first pass, yes, this January updates resolved this. Thanks to the Google team!
