### ISSUE TITLE
feature request - tf.stack

### ISSUE THREAD

**Issue by danielbarter** [tensorflow/tensorflow#3355]
Given a tensor `x[i,j,k]` in a graph, I often want to construct tensors like `X[i,j,k,p,q] = x[i,j,k]`. 

You can get this done using `tf.pack`, but it can get kind of messy if you are adding a bunch of dimensions.

It would be nice if there was a function `tf.stack(x,list)` which added dimensions to a tensor as above. The name is motivated by the following situation. If x is a matrix, then tf.stack(x,[n]) would create a 3-tensor by stacking the matrix up n times. I imagine that tf.stack would fit nicely under tf.tile in the documentation

It is possible that there is already a better way to do this than using tf.pack, but if so, it is not in the docs.

**Comment by vrv** [comment]
Try tf.tile ?

**Comment by danielbarter** [comment]
If I understand correctly, tf.tile can't change the dimension of a tensor. What is the best way to cast a tensor of dimension `[a,b,c]` to a tensor of dimension `[a,b,c,1,1]`?

**Comment by vrv** [comment]
You can use tf.expand_dims, then followed by tf.tile, perhaps!

**Comment by danielbarter** [comment]
@vrv that works very well. Sorry for the stupid question and thanks for the fast response!

**Comment by vrv** [comment]
Glad I could help, and no worries -- you might also ask these types of questions on StackOverflow -- the community is also quite helpful for these kind of modeling / programming questions.
