### ISSUE TITLE
tf.io.GFIle not working correctly with UTF-8 files and Python3

### ISSUE THREAD

**Issue by cyfra** [tensorflow/tensorflow#33563]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu
- TensorFlow installed from (source or binary): source internal Google
- TensorFlow version (use command below): 1.5.0, internal Google
- Python version: 3.6.7

**Describe the current behavior**
Calling 'read(X)' on the text files opened with GFile in python3 doesn't work properly (it fetches X bytes rather than X characters). This often results with the UnicodeDecodeError (as the read can happen in the middle of the unicode character).

**Describe the expected behavior**
It should behave like python3: reading the X characters.

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

```python
my_text = 'Bären'
with open('/tmp/ex1', 'w') as f:
  f.write(my_text)

// Will read the whole string correctly.
with open('/tmp/ex1', 'r') as f:
  print(f.read())

// This will print 2 chars Ba
with open('/tmp/ex1', 'r') as f:
 print(f.read(2))

// This will print 3 chars: Bar
with open('/tmp/ex1', 'r') as f:
 print(f.read(3))

// This will print the whole thing.
with tf.io.gfile.GFile('/tmp/ex1', 'r') as f:
  print(f.read())

// This will crash.. :-(
with tf.io.gfile.GFile('/tmp/ex1', 'r') as f:
  print(f.read(2))
```

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

The error will be:
```
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc3 in position 1: unexpected end of data
```

**Comment by mihaimaruseac** [comment]
Confirmed in tf-nightly and python3.7

**Comment by yongtang** [comment]
I think it is possible to check the utf8 length while reading, and compensate the remaining bytes. Created a PR #33590 for the fix.

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.
