### ISSUE TITLE
TFLite metal delegate can't share MTLDevice

### ISSUE THREAD

**Issue by stakemura** [tensorflow/tensorflow#33564]
**System information**
- TensorFlow version (you are using):master branch
- Are you willing to contribute it (Yes/No):Yes

**Describe the feature and the current behavior/state.**
As Apple [the official document](https://developer.apple.com/library/archive/documentation/3DDrawing/Conceptual/MTLBestPracticesGuide/PersistentObjects.html) mentioned, all apps should create only one MTLDevice object.

> All apps should create only one MTLDevice object per GPU and reuse it for all your Metal work on that GPU. Most apps should create only one MTLCommandQueue object per GPU, though you may want more if each command queue represents different Metal work (for example, non-real-time compute processing and real-time graphics rendering)..

However, the current TFLite implementation doesn't have the interface to share MTLDevice as [metal_delegate.mm](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/delegates/gpu/metal_delegate.mm) shows.

```mm
  explicit Delegate(const TFLGpuDelegateOptions* options) {
    if (options) {
      options_ = *options;
    } else {
      // Default options.
      options_.allow_precision_loss = false;
      options_.wait_type = TFLGpuDelegateWaitType::TFLGpuDelegateWaitTypePassive;
    }
    metal_device_ = MTLCreateSystemDefaultDevice();
```
This issue is critical for me since I should integrate TFLite into the existing metal application.
Would you like to improve this initialization function?
One of my idea is that adds default MTLDevice parameter to TFLGpuDelegateOptions.
If you need, I will send PR.

**Comment by NikolayChirkov** [comment]
Hi Shintaro, thanks for the request. Yes, we plan (November) to support passing the device into the delegate. It also allows to use multiple devices on macos.

**Comment by stakemura-bns** [comment]
@ NikolayChirkov Any news about this feature ?
I am looking forward to getting updates from you. Thanks again.

**Comment by stakemura** [comment]
@ NikolayChirkov Any news about this feature ?
I am looking forward to getting updates from you. Thanks again.

**Comment by impjdi** [comment]
@stakemura 

Sorry, @NikolayChirkov has switched teams and isn't working on TFLite GPU anymore.  Thus, we don't have a maintainer for Metal.

@miaout17 

IIRC there is some complexities with ObjC and Swift.  How do you feel we should proceed?  I think support of this functionality is now up to you guys, from the API's point of view.

**Comment by stakemura** [comment]
@miaout17
I have waited for the response for a long time.
Would you like to give me a reply?

**Comment by miaout17** [comment]
(I'm sorry for the delay -- Missed these message due to my notification settings)

Did you run into any real problems with this issue on iOS devices?
If I understand correctly, [MTLCreateSystemDefaultDevice](https://developer.apple.com/documentation/metal/1433401-mtlcreatesystemdefaultdevice) returns a reference to the preferred default Metal device object, so it's not really creating multiple devices when it's called more than once. 

If you want to pass a `MTLDevice` for some reasons, I think it's possible to make the change. 

Replying to @impjdi 's question:

> IIRC there is some complexities with ObjC and Swift. How do you feel we should proceed? I think support of this functionality is now up to you guys, from the API's point of view.

I think this is possible. The only constraint is that `TFLGpuDelegateOptions` should to be in pure C. We can either define a `void *` or a forward decelerated structure in `TFLGpuDelegateOptions` to represent `MTLDevice`.

**Comment by impjdi** [comment]
Yeah, we changed it from C-compatible to ObjC-compatible, because we didn't foresee Swift usage.  I think it's fine to use `void*`.

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.
