### ISSUE TITLE
symbol "_SaverDef_default_instance_" becomes undefined after updating tensorflow from 1.2 to 1.12

### ISSUE THREAD

**Issue by RaymondReddington** [tensorflow/tensorflow#33562]
symbol "_SaverDef_default_instance_" becomes undefined after updating tensorflow from 1.2 to 1.12

what dependency shoud i add to BUILD file?

_SaverDef_default_instance_ is in cc file generated by tensorflow/core/framework/saver.proto in 1.2

in 1.12, saver.proto is not compiled. has the target changed?

the dependency targets in BUILD are:
       "//tensorflow/cc:cc_ops",
        "//tensorflow/cc:client_session",
        "//tensorflow/core:tensorflow"

Env Info:
tensorflow:  HEAD detached at v1.12.1
                    https://github.com/tensorflow/tensorflow.git

```shell
commit c20310273f663b1dbf9ca9e68068784d44a95ae2
Merge: cc494ee f303882
Author: TensorFlower Gardener <gardener@tensorflow.org>
Date:   Thu Apr 18 06:15:58 2019 -0700

    Merge pull request #27699 from yongtang:27497-ragged-axis
    
    PiperOrigin-RevId: 244173513
```

bazel:  get from https://releases.bazel.build/0.25.0/rc3/index.html

os: centos7 
kernel: 3.10.107 
gcc version 4.8.5 20150623 (Red Hat 4.8.5-4) (GCC)
cpu:
```shell
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                8
On-line CPU(s) list:   0-7
Thread(s) per core:    1
Core(s) per socket:    8
Socket(s):             1
NUMA node(s):          1
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 94
Model name:            Intel(R) Xeon(R) Gold 61xx CPU
Stepping:              3
CPU MHz:               2494.140
BogoMIPS:              4988.28
Hypervisor vendor:     KVM
Virtualization type:   full
L1d cache:             32K
L1i cache:             32K
L2 cache:              4096K
NUMA node0 CPU(s):     0-7
```

dir structure: tensorflow-1.12(git root)/tensorflow/my_implement/BUILD
BUILD file:
```shell
cc_binary(
    name = "libMyImplement.so",
    srcs = ["my_implement.h",
            "my_implement.cc",
            ],
    linkshared = 1,
    deps = [
        "//tensorflow/cc:cc_ops",
        "//tensorflow/cc:client_session",
        "//tensorflow/core:tensorflow"
        ],
)
```

it reports symbol "_SaverDef_default_instance_" undefined while loading libMyImplement.so which compiled in v1.12.1

i think maybe something i forget to add to deps list. or should i execute some ./configure command with any special parameter before compiling?

there is no errors loading libMyImplement.so compiled in tensorflow v1.2.0

and i have tried compile libMyImplement.so in tensorflow v1.13, and there is still this error

**Comment by oanush** [comment]
@RaymondReddington ,
Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version. Also, did you compile from source or install a binary?
Make sure you also include the exact command if possible to produce the output included in your test case. If you are unclear what to include see the issue template displayed in [the Github new issue template](https://github.com/tensorflow/tensorflow/issues/new/choose).
We ask for this in the issue submission template, because it is really difficult to help without that information. Thanks!

**Comment by RaymondReddington** [comment]
> @RaymondReddington ,
> Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version. Also, did you compile from source or install a binary?
> Make sure you also include the exact command if possible to produce the output included in your test case. If you are unclear what to include see the issue template displayed in [the Github new issue template](https://github.com/tensorflow/tensorflow/issues/new/choose).
> We ask for this in the issue submission template, because it is really difficult to help without that information. Thanks!

i have update my description

**Comment by oanush** [comment]
@RaymondReddington ,
Rather than upgrading tensorflow version, can you please try building Tensorflow from the scratch for 1.12.1 using this [link](https://www.tensorflow.org/install/source)?Thanks!

**Comment by RaymondReddington** [comment]
> @RaymondReddington ,
> Rather than upgrading tensorflow version, can you please try building Tensorflow from the scratch for 1.12.1 using this [link](https://www.tensorflow.org/install/source)?Thanks!

now i'm on branch r1.12
and following the steps in the link you give.
i get some error when do this step:
```shell
bazel build --config=opt //tensorflow/tools/pip_package:build_pip_package
```

error is:
```
 //tensorflow/tools/pip_package:build_pip_package
Starting local Bazel server and connecting to it...
ERROR: /data/tensorflow/tensorflow-r1.12/WORKSPACE:3:1: name 'http_archive' is not defined
ERROR: Error evaluating WORKSPACE file
ERROR: error loading package '': Encountered error while reading extension file 'closure/defs.bzl': no such package '@io_bazel_rules_closure//closure': error loading package 'external': Could not load //external package
ERROR: error loading package '': Encountered error while reading extension file 'closure/defs.bzl': no such package '@io_bazel_rules_closure//closure': error loading package 'external': Could not load //external package
INFO: Elapsed time: 1.949s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
```

my bazel version is 0.25.0 rc3
./configure command has checked bazel version and no error found.
so how to solve this ?

**Comment by RaymondReddington** [comment]
@oanush 
in branch r1.12
i have tried removing flag linkshared=1 in my own BUILD file.
it occurs this error:
```shell
bazel-out/k8-opt/bin/tensorflow/core/_objs/protos_all_proto_text/saved_tensor_slice.pb_text.o:saved_tensor_slice.pb_text.cc:function tensorflow::internal::AppendProtoDebugString(tensorflow::strings::ProtoTextOutput*, tensorflow::SavedSliceMeta const&): error: undefined reference to 'tensorflow::_SavedSliceMeta_default_instance_'
collect2: error: ld returned 1 exit status
Target //tensorflow/lstm_kernel:libDeepNlpModelEn.so failed to build
```
just like the error symbol "_SaverDef_default_instance_" becomes when loading libDeepNlpModelEn.so which compiled with flag linkshared=1

**Comment by RaymondReddington** [comment]
@sukritiramesh @tensorflower-gardener @christisg @jhseu 
how to add saver.pb dependence for c++ implemention?

**Comment by RaymondReddington** [comment]
@oanush 
i have modified BUILD like this:
```shell
cc_binary(
    name = "myimplement",
    data = [
        "//tensorflow/core:android_proto_srcs",
        "//tensorflow/core:protos_all_proto_text",
    ],
)
cc_proto_library(
    name = "myproto",
    srcs = [ "my_implement.h", "my_implement.cc" ],
    deps  = [
        ":myproto_text",
    ],
)

proto_library (
    name = "myproto_text",
    data = [
        "//tensorflow/core:protos_all_proto_text",
    ],
)
```
it seems that it does compiling some more proto,
but not the proto i need.
it still has the error:
```shell
bazel-out/k8-opt/bin/tensorflow/core/_objs/protos_all_proto_text/saved_tensor_slice.pb_text.o:saved_tensor_slice.pb_text.cc:function tensorflow::internal::AppendProtoDebugString(tensorflow::strings::ProtoTextOutput*, tensorflow::SavedSliceMeta const&): error: undefined reference to 'tensorflow::_SavedSliceMeta_default_instance_'
collect2: error: ld returned 1 exit status
INFO: Elapsed time: 100.226s, Critical Path: 85.13s
```

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.
