### ISSUE TITLE
Failure to load and remap a 2-D Tensor from checkpoint when variance scaling initializer is used

### ISSUE THREAD

**Issue by mbartzokas** [tensorflow/tensorflow#33567]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): YES
- OS Platform and Distribution:
os: Darwin
os kernel version: Darwin Kernel Version 17.7.0: Wed Feb 27 00:43:23 PST 2019; root:xnu-4570.71.35~1/RELEASE_X86_64
os release version: 17.7.0
os platform: Darwin-17.7.0-x86_64-i386-64bit
linux distribution: ('', '', '')
linux os distribution: ('', '', '')
mac version: ('10.13.6', ('', '', ''), 'x86_64')
- TensorFlow installed from (source or binary): NO
- TensorFlow version (use command below):
tf.version.VERSION = 1.14.0
tf.version.GIT_VERSION = v1.14.0-rc1-22-gaf24dc91b5
tf.version.COMPILER_VERSION = 4.2.1 Compatible Apple LLVM 10.0.0 (clang-1000.11.45.5)
- Python version:
(major, minor, micro, releaselevel, serial)
(2, 7, 15, 'final', 0)
- Bazel version (if compiling from source): NO
- GCC/Compiler version (if compiling from source): NO
- CUDA/cuDNN version: NO
- GPU model and memory: NO

**Describe the current behavior**
I train with the estimator api and I wish to warm start a 2d variable (which I use as embedding). My old model has different embedding vocabulary than the new one so I pass a WarmStartSettings structure including tf.estimator.VocabInfo.
If I pass tf.estimator.VocabInfo without specifying a backup_initializer, the 0 initializer is used as default and the warm start and training finish successfully. However when I pass a backup_initializer, like tf.compat.v1.initializers.variance_scaling, I get a TypeError, which it looks like is caused because the initializer requires that its shape is a non Tensor, but the gen_checkpoint_ops.generate_vocab_remapping returns Tensors which are passed to the initilizer as shape.

**Describe the expected behavior**
Ability to load and remap a 2-D Tensor from a checkpoint when a custom initializer is used. So eventually be able to warm start whenever my new model embeddings have different vocabularies than the old

**Code to reproduce the issue**
```
import tensorflow as tf
from tensorflow.python.training import checkpoint_ops

if __name__ == '__main__':
    initializer = tf.compat.v1.initializers.variance_scaling(scale=0.175, mode="fan_in", distribution='uniform')

    old_row_vocab_file = './old_vocab_path'  # text file with 2 rows
    new_row_vocab_file = './new_vocab_path'  # text file with 2 rows

    checkpoint_ops._load_and_remap_matrix(ckpt_path='', old_tensor_name='old_tensor/name', new_row_vocab_offset=0,
                                          num_rows_to_load=2, new_col_vocab_size=3, initializer=initializer,
                                          old_row_vocab_size=-1, old_row_vocab_file=old_row_vocab_file,
                                          new_row_vocab_file=new_row_vocab_file)
```

**Other info / logs**
```
File "/env/lib/python2.7/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1365, in _train_with_estimator_spec
    warm_starting_util.warm_start(*self._warm_start_settings)
  File "/env/lib/python2.7/site-packages/tensorflow/python/training/warm_starting_util.py", line 460, in warm_start
    axis=vocab_info.axis)
  File "/env/lib/python2.7/site-packages/tensorflow/python/training/warm_starting_util.py", line 301, in _warm_start_var_with_vocab
    init(shape=v_shape, partition_info=partition_info))
  File "/env/lib/python2.7/site-packages/tensorflow/python/training/checkpoint_ops.py", line 414, in _initializer
    max_rows_in_memory=max_rows_in_memory)
  File "/env/lib/python2.7/site-packages/tensorflow/python/training/checkpoint_ops.py", line 179, in _load_and_remap_matrix
    num_rows_present * num_cols_present, 1
  File "/env/lib/python2.7/site-packages/tensorflow/python/ops/init_ops.py", line 515, in __call__
    fan_in, fan_out = _compute_fans(scale_shape)
  File "/env/lib/python2.7/site-packages/tensorflow/python/ops/init_ops.py", line 1447, in _compute_fans
    return int(fan_in), int(fan_out)
TypeError: int() argument must be a string or a number, not 'Tensor'
```

**Comment by gadagashwini** [comment]
@mbartzokas, Please provide the minimal standalone code to replicate the issue. Thanks!

**Comment by mbartzokas** [comment]
Hi @gadagashwini, the code under "Code to reproduce the issue" above is the minimal to reproduce it and give you the traceback below. The code never reaches the point when it reads the checkpoints or the files so it doesn't matter that I don't pass actual checkpoints or files.
```
Traceback (most recent call last):
  File "...../reproduce.py", line 122, in <module>
    new_row_vocab_file=new_row_vocab_file)
  File "...../venv/lib/python2.7/site-packages/tensorflow/python/training/checkpoint_ops.py", line 179, in _load_and_remap_matrix
    num_rows_present * num_cols_present, 1
  File "...../venv/lib/python2.7/site-packages/tensorflow/python/ops/init_ops.py", line 515, in __call__
    fan_in, fan_out = _compute_fans(scale_shape)
  File "...../venv/lib/python2.7/site-packages/tensorflow/python/ops/init_ops.py", line 1447, in _compute_fans
    return int(fan_in), int(fan_out)
TypeError: int() argument must be a string or a number, not 'Tensor'
```

**Comment by gadagashwini** [comment]
Issue is replicating with Tf 1.14.0. and Tf 1.15.0 as well. Please take a look at gist [TF1.14](https://colab.sandbox.google.com/gist/gadagashwini/3cb2e1c7ab8bfd2e5b56e564d40fe09e/untitled220.ipynb) and [TF1.15](https://colab.sandbox.google.com/gist/gadagashwini/f5b2125bf080bfc7b2d0c2c87bcd50e0/untitled221.ipynb) .Thanks!

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.
