### ISSUE TITLE
tensorflow model installation fails on windows10,using cmake3.15.4win64 , visual studio anyversion

### ISSUE THREAD

**Issue by devitnow15** [tensorflow/tensorflow#33578]
following https://tensorflow-object-detection-api-tutorial.readthedocs.io/en/latest/training.html
and https://github.com/protocolbuffers/protobuf/blob/master/cmake/README.md 
 protobuf failing while using command 

cmake -G "NMake Makefiles" -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=../../../../install ../..

error says : /out:CMakeCCompilerId.exe 
CMakeCCompilerId.obj 
LINK : fatal error LNK1104: cannot open file 'LIBCMT.lib'

lib path is given in environment variables.
running from command prompt.
attached are error and output files
[CMakeError.log](https://github.com/tensorflow/tensorflow/files/3752000/CMakeError.log)
[CMakeOutput.log](https://github.com/tensorflow/tensorflow/files/3752002/CMakeOutput.log)

**Comment by oanush** [comment]
@devitnow15 ,
We don't support cmake related issue's,  please try installation of TF using bazel refer [this](https://www.tensorflow.org/install/source_windows) link.Thanks!

**Comment by devitnow15** [comment]
I want to train few models for my requirements for which tensorFlow Models Installation is necessary.
This is what I infer from https://github.com/tensorflow/tensorflow/issues/33578 .
Tensorflow Object Detection API uses Protobufs to configure model and training parameters.Before the framework can be used, the Protobuf libraries must be downloaded and compiled.
After downloading the latest protoc-3.5.1-win32.zip , to configure and compile , cmake is necessary ?
Can I train the models without using Cmake ? Bazel doesnt look like it would server the purpose here.
let me know how else I can use tensor flow for training models if I need not use cmake ?
I am new to this whole thing , and this is taking away a lot of time

**Comment by oanush** [comment]
@devitnow15 ,
Unfortunately we don't support issues related to any other package installer other than bazel. Hence bazel is the only option to install TF. Thanks!

**Comment by devitnow15** [comment]
worked using command prompt of C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build>vcvars64.bat , cd to Google Protobuf\cmake\build\release 
and then run command :
cmake -G "NMake Makefiles" -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=../../../../install ../..
