### ISSUE TITLE
Tracing of first batch does not collect compute events

### ISSUE THREAD

**Issue by Flamefire** [tensorflow/tensorflow#33571]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Mint 19.2
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: unknown
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): v2.0.0-rc2-26-g64c3d38 2.0.0
- Python version: 3.6.9
- CUDA/cuDNN version: none
- GPU model and memory: none

**Describe the current behavior**

Using `profile_batch=1` for `tf.keras.callbacks.TensorBoard` does not collect any compute calls in the profile/trace

**Describe the expected behavior**

Similar timeline shown as for e.g. `profile_batch=2`.

**Code to reproduce the issue**
```
import tensorflow_datasets as tfds
import tensorflow as tf
import datetime
import os

tf.config.threading.set_inter_op_parallelism_threads(1)

datasets, info = tfds.load(name='mnist',
                           with_info=True,
                           as_supervised=True,
                           shuffle_files=False)

mnist_train, mnist_test = datasets['train'], datasets['test']
strategy = tf.distribute.OneDeviceStrategy("/cpu:0")

num_train_examples = info.splits['train'].num_examples

BATCH_SIZE_PER_REPLICA = 64
BATCH_SIZE = BATCH_SIZE_PER_REPLICA * strategy.num_replicas_in_sync


def scale(image, label):
    image = tf.cast(image, tf.float32)
    image /= 255
    return image, label


train_dataset = mnist_train.map(scale).cache().shuffle(
    num_train_examples).batch(BATCH_SIZE)
eval_dataset = mnist_test.map(scale).batch(BATCH_SIZE)

log_dir = "/tmp/tf_logs/fit/" + datetime.datetime.now().strftime(
    "%Y%m%d-%H%M%S")

with strategy.scope():
    model = tf.keras.Sequential([
        tf.keras.layers.Conv2D(32,
                               3,
                               activation='relu',
                               input_shape=(28, 28, 1)),
        tf.keras.layers.MaxPooling2D(),
        tf.keras.layers.Flatten(),
        tf.keras.layers.Dense(64, activation='relu'),
        tf.keras.layers.Dense(10, activation='softmax')
    ])

    model.compile(loss='sparse_categorical_crossentropy',
                  optimizer=tf.keras.optimizers.Adam(),
                  metrics=['accuracy'])

    callbacks = [
            tf.keras.callbacks.TensorBoard(log_dir=log_dir,
                                           histogram_freq=0,
                                           profile_batch=1)
    ]
    model.fit(train_dataset, epochs=3, steps_per_epoch=20, callbacks=callbacks)
```

**Other info / logs**
[epoch1.zip](https://github.com/tensorflow/tensorflow/files/3750929/epoch1.zip)
[epoch2.zip](https://github.com/tensorflow/tensorflow/files/3750930/epoch2.zip)

When opening the trace in TensorBoard there is a lot of "stuff" in epoch1, but no "tf_compute" section as with epoch2

**Comment by oanush** [comment]
@Flamefire ,
Thank you for reporting, when tried to run given i got `NameError: name 'num_train_examples' is not defined`. Can you please provide a complete standalone code to reproduce the issue ?Thanks!

**Comment by Flamefire** [comment]
Sorry, I cut the code to remove the unnecessary bits, but forgot about that. Added to the above example.

**Comment by gowthamkpr** [comment]
Was able to reproduce it. Please find the github gist [here](https://colab.sandbox.google.com/gist/gowthamkpr/77e75db8bf851b175033e94e4db30f2d/untitled246.ipynb). Thanks!

**Comment by sushreebarsa** [comment]
Was able to reproduce the issue in TF v2.5 ,please find the gist [here](https://colab.research.google.com/gist/sushreebarsa/e4d09cb2a2960e6fe319ccfb4bef1b85/untitled23.ipynb)..Thanks !

**Comment by kumariko** [comment]
Was able to reproduce the issue in TF v2.6 ,please find the gist [`here`](https://colab.research.google.com/gist/kumariko/7f93c660c0b854c9e4b56ed17618cbd5/untitled23.ipynb#scrollTo=X1Zx7UeBKCiq)..Thanks !

**Comment by tensorflowbutler** [comment]
Hi There,

 This is a stale issue. As you are using an older version of tensorflow, we are checking to see if you still need help on this issue. Please test the issue with the latest TensorFlow (TF2.7 and tf-nightly). If the issue still persists with the newer versions of TF, please feel free to open it in [keras-team/keras](https://github.com/keras-team/keras/issues) repository by providing details about the issue and a standalone code to reproduce the issue. Thanks! 

 Please note that Keras development has moved to a separate Keras-team/keras repository to focus entirely on only Keras. Thanks!
