### ISSUE TITLE
tf.compat.v1.wrap_function throws error when creating variable in tf.distribute scope

### ISSUE THREAD

**Issue by kazimuth** [tensorflow/tensorflow#33585]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Google Colab TPU
- TensorFlow installed from (source or binary): Binary
- TensorFlow version (use command below): v2.0.0-rc2-26-g64c3d38 2.0.0
- Python version: 3.6

**Code to reproduce the issue**
```python
%tensorflow_version 2.x
import tensorflow as tf

# define a function that uses tf.compat.v1.get_variable with some initializer
def f():
    v = tf.compat.v1.get_variable(
      'v',
      initializer=tf.compat.v1.variance_scaling_initializer(), shape=(1), trainable=True
    )
    return v

# this works:
wrapped = tf.compat.v1.wrap_function(f, [])

# but, connect to a TPU...
tpu_address = 'grpc://' + os.environ['COLAB_TPU_ADDR']
cluster_resolver = tf.distribute.cluster_resolver.TPUClusterResolver(tpu=tpu_address)
tf.config.experimental_connect_to_cluster(cluster_resolver)
tf.tpu.experimental.initialize_tpu_system(cluster_resolver)
with tf.distribute.experimental.TPUStrategy(cluster_resolver).scope():
    # ...and, this throws:
    # ValueError: Tensor-typed variable initializers must either be
    # wrapped in an init_scope or callable
    wrapped = tf.compat.v1.wrap_function(f, [])
```

It seems like wrapped_function variable creation is interacting poorly with distribute somehow.

Note, a simple `lambda: 0` initializer doesn't seem to cause this to happen. Not sure why. 

**Expected behavior**
This should "just work", unless these features aren't intended to be used together.

**Comment by sunzhe09** [comment]
I meet the same problem

**Comment by mohantym** [comment]
Was able to replicate the issue with TF v2.5 ,please find the [gist ](https://colab.research.google.com/gist/mohantym/4966cc2e7c58c329b940713f949452f2/33585.ipynb#scrollTo=CdEj98g42R9r)here ..Thanks!

**Comment by sushreebarsa** [comment]
@kazimuth I tried to reproduce the issue on Colab using TF v2.7.0 and didn't see the error reported .Could you please find the gist [here](https://colab.research.google.com/gist/sushreebarsa/60aa323a9986e8f947cb0e25d1850342/gist33585.ipynb) for reference ?Thanks!
