### ISSUE TITLE
graph_transforms build has error

### ISSUE THREAD

**Issue by yyf1986** [tensorflow/tensorflow#33594]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):Ubuntu 18.04.3 LTS
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): pip install
- TensorFlow version: 1.13
- Python version: 3.6
- Installed using virtualenv? pip? conda?: no
- Bazel version (if compiling from source):0.21,I download deb file
- GCC/Compiler version (if compiling from source):Ubuntu default gcc,gcc version 7.4.0
- CUDA/cuDNN version: no
- GPU model and memory:no

I want to know,which version with tensorflow and bazel can build sucess?

**Comment by yyf1986** [comment]
tf1.4  bazel 0.29
C++ compilation of rule '//tensorflow/core/kernels:tile_ops' failed

**Comment by ravikyram** [comment]
@yyf1986 

Can you please go through the below [link](https://www.tensorflow.org/install/source#tested_build_configurations) and see if it helps you.Thanks!

**Comment by ravikyram** [comment]
@yyf1986 

Any updates on this issue please. Thanks!

**Comment by ravikyram** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
