### ISSUE TITLE
about tf.gradients() API

### ISSUE THREAD

**Issue by candyzone** [tensorflow/tensorflow#33598]
The API `tf.gradients` has a parameter `gate_gradients`
```gate_gradients: If True, add a tuple around the gradients returned for an operations. This avoids some race conditions.```

In case of op has more than one in_grads, it makes a barrier, grads will not propagate until the whole grad subGraph was computed. It make sense.

But, in case of op has more than one in_grads and the upstream ops are not Variable, the barrier seems redundant. The OP parallelism can be improved.

thanks

**Comment by candyzone** [comment]
@gowthamkpr

**Comment by rmothukuru** [comment]
@candyzone,
Sorry for the delayed response. In **`Tensorflow 2.x`**, we use [tf.GradientTape](https://www.tensorflow.org/api_docs/python/tf/GradientTape) over [tf.gradients](https://www.tensorflow.org/api_docs/python/tf/gradients). Can you please let us know if the feature that you are looking for is not present in [tf.GradientTape](https://www.tensorflow.org/api_docs/python/tf/GradientTape) as well?

Thanks!
