### ISSUE TITLE
C binding for tensorflow 2.0

### ISSUE THREAD

**Issue by oak-tree** [tensorflow/tensorflow#33599]
Is there a release date for `c binding` for `tf2`?

**Comment by foxik** [comment]
We are currently building libtensorflow by ourselves, but it would be great if the official one would appear.

**Comment by av8ramit** [comment]
@sjamesr is the Java SIG taking ownership of the libtensorflow releases?

**Comment by gunan** [comment]
I am taking ownership of libtensorflow packages, as it looks like all of the previous owners left the team.
We have noticed some issues with the current packages we have. We will look into fixing them and publishing them again.

**Comment by foxik** [comment]
Yay!

**Comment by grantstephens** [comment]
@foxik Could you please share how you are building them yourself. We have tried, but it errors when making predictions. Thanks in advance.

**Comment by JustinWick** [comment]
Does anyone know what version of TensorFlow 2 will have libtensorflow in it?

**Comment by av8ramit** [comment]
2.3 will have libtensorflow. Additionally we have nightly packages on GCS. You can find the links on the main README.

**Comment by ankane** [comment]
For everyone who's subscribed, it's arrived: https://www.tensorflow.org/install/lang_c

**Comment by JustinWick** [comment]
I saw that, awesome, thanks everyone!

**Comment by rmothukuru** [comment]
@oak-tree,
Closing this issue as it has been resolved, as per [this Comment](https://github.com/tensorflow/tensorflow/issues/33599#issuecomment-666157941). Please refer this [Tensorflow Documentation](https://www.tensorflow.org/install/lang_c) for more information. Thanks!
