### ISSUE TITLE
Cannot make tensorflow to  use a local gcc installation?

### ISSUE THREAD

**Issue by casiciaco** [tensorflow/tensorflow#336]
Hi,
I am bound to an old installation on a machine. I had to install a local gcc 4.8.1 and make my way through a bazel compilation (thanks to the community for their help :) ). However, now I am unable to compile tensorflow. This is the error I get:
```
gcc: unrecognized option '-no-canonical-prefixes'
cc1plus: error: unrecognized command line option "-std=c++11"
cc1plus: warning: unrecognized command line option "-Wno-free-nonheap-object"
ERROR: $HOME/tensorflow/google/protobuf/BUILD:29:1: C++ compilation of rule '//google/protobuf:protobuf_lite' failed: crosstool_wrapper_driver_is_not_gcc failed: error executing command third_party/gpus/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc -U_FORTIFY_SOURCE '-D_FORTIFY_SOURCE=1' -fstack-protector -fPIE -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object ... : com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
```
I guess it is not getting the correct gcc, since if I run : 
``` 
/path/to/local/gcc.4.8.1/bin/gcc -std=c++11  example.cc 
```
All is ok, but if I run 
```
/usr/bin/gcc  -std=c++11 example.cc
```
I get the same error"
```
cc1plus: error: unrecognized command line option "-std=c++11"
```
If I add the ``` --verbose_failures ``` option, I get this additional information:
```
(cd $HOME/.cache/bazel/_bazel_$USER/2d4cdeea5be55811d371414ca0f7bd15/tensorflow && \
  exec env - \
    PATH=$HOME/jdk1.8.0_65/bin/:$HOME/local.gcc-4.8.1/bin:/usr/lib64/qt-3.3/bin:/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/sbin:$HOME/bin \
  third_party/gpus/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc -U_FORTIFY_SOURCE '-D_FORTIFY_SOURCE=1' -fstack-protector -fPIE -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 -DNDEBUG -ffunction-sections -fdata-sections '-std=c++11' -iquote . -iquote bazel-out/local_linux-opt/genfiles -iquote external/bazel_tools -iquote bazel-out/local_linux-opt/genfiles/external/bazel_tools -isystem google/protobuf/src -isystem bazel-out/local_linux-opt/genfiles/google/protobuf/src -isystem external/bazel_tools/tools/cpp/gcc3 -DHAVE_PTHREAD -Wall -Wwrite-strings -Woverloaded-virtual -Wno-sign-compare '-Wno-error=unused-function' -no-canonical-prefixes -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' '-frandom-seed=bazel-out/local_linux-opt/bin/google/protobuf/_objs/protobuf_lite/google/protobuf/src/google/protobuf/wire_format_lite.o' -MD -MF bazel-out/local_linux-opt/bin/google/protobuf/_objs/protobuf_lite/google/protobuf/src/google/protobuf/wire_format_lite.d -c google/protobuf/src/google/protobuf/wire_format_lite.cc -o bazel-out/local_linux-opt/bin/google/protobuf/_objs/protobuf_lite/google/protobuf/src/google/protobuf/wire_format_lite.o)
```
 How can I make it use the correct gcc ?

Thanks,

**Comment by vrv** [comment]
This seems more like a bazel-related question -- can please you file an issue at their github repo?

**Comment by casiciaco** [comment]
Hi, 
I think it is not a bazel related problem.   I get the error when I execute the following: 
```
bazel build -c opt --config=cuda //tensorflow/cc:tutorials_example_trainer
```
Then I get the above error at this stage:
 ```
(cd $HOME/.cache/bazel/_bazel_$USER/2d4cdeea5be55811d371414ca0f7bd15/tensorflow && \
  exec env - \
    PATH=$HOME/jdk1.8.0_65/bin/:$HOME/local.gcc-4.8.1/bin:/usr/lib64/qt-3.3/bin:/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/sbin:$HOME/bin \
  third_party/gpus/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc -U_FORTIFY_SOURCE '-D_FORTIFY_SOURCE=1' ... -- see above for full command --)
```
I execute:
```
(cd $HOME/.cache/bazel/_bazel_$USER/2d4cdeea5be55811d371414ca0f7bd15/tensorflow && \
  exec env - \
    PATH=$HOME/jdk1.8.0_65/bin/:$HOME/local.gcc-4.8.1/bin:/usr/lib64/qt-3.3/bin:/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/sbin:$HOME/bin \
  gcc  -U_FORTIFY_SOURCE '-D_FORTIFY_SOURCE=1'  ... )
```
Then this compilation step works. I think : 
```
third_party/gpus/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc
```
Is not getting the correct gcc. 
Moreover if  I remove the cuda flag (``` --config=cuda ```) and execute this:
```
bazel build -c opt  //tensorflow/cc:tutorials_example_trainer
```
Then the wrapper is different (``` external/bazel_tools/tools/cpp/gcc_wrapper.sh ``` instead of ``` third_party/gpus/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc
```  ) and it passes this step. So it seems to be a specific problem of tensorFlow + Cuda + the crosstool_wrapper_driver_is_not_gcc .

**Comment by casiciaco** [comment]
Hi, 
following in the https://github.com/bazelbuild/bazel/issues/649  , it seems a tensorflow configuration problem. It is not 100% solved, can anyone help ?

**Comment by wchan** [comment]
FYI, this is still not solve -- using a local GCC does not work as OP mentioned. Somehow TF or bazel is picking up my /usr/bin/g++ instead of /usr/local/bin/g++ ... debugging...

**Comment by raindeer** [comment]
Any solution to this yet?

**Comment by casiciaco** [comment]
Yes, 
from here  https://github.com/bazelbuild/bazel/issues/649, apply the comment fix by sethbruder , and then edit compile.sh to export your flags.

**Comment by peterbraden** [comment]
Is there any way to do this without editing build files?

**Comment by martinwicke** [comment]
This question is probably better asked over at bazel, they're more likely
to be able to help with this.

**Comment by ScottHCL** [comment]
I had counted such problem when compiling tensorflow from source in mac system:
gcc: error: unrecognized command line option '-fcolor-diagnostics'
gcc: error: unrecognized command line option '-Wthread-safety'
gcc: error: unrecognized command line option '-Wself-assign'
ERROR: /Users/clhuang/Downloads/tensorflow/google/protobuf/BUILD:29:1: C++ compilation of rule '//google/protobuf:protobuf_lite' failed: osx_gcc_wrapper.sh failed: error executing command external/bazel_tools/tools/cpp/osx_gcc_wrapper.sh '-D_FORTIFY_SOURCE=1' -fstack-protector -fcolor-diagnostics -Wall -Wthread-safety -Wself-assign -fno-omit-frame-pointer -g0 -O2 -DNDEBUG ... (remaining 37 argument(s) skipped): com.google.devtools.build.lib.shell.BadExitStatusException


And my gcc version is 4.9,when I just run the command /my/path/gcc-4.9 -Wthread-safety  example.cc,
it also shows gcc: error: unrecognized command line option '-fcolor-diagnostics'.could anyone give me some advise

**Comment by leetenthu** [comment]
I have the same issue as ScottHCL. Anyone please any solution?

**Comment by jhave** [comment]
same issue. did editing build files work for anyone else?

**Comment by Tweakmind** [comment]
Add the following to your path:
/usr/lib/gcc/x86_64-linux-gnu/4.8

I added the following to .bashrc
export PATH=/usr/lib/gcc/x86_64-linux-gnu/4.8${PATH:+:${PATH}}

All cc1 and cc1plus errors are now gone during basel compile.

FYI, I also compiled basel 0.14.1 using gcc-4.8 as well, not sure if this is necessary. This alone did not cure this problem but may have cured others.

Ubuntu 18.04 LTS
Anaconda3-5.2.0-Linux-x86_64.sh
cuda_9.2.88_396.26_linux.run
cudnn-9.2-linux-x64-v7.1.tgz
openjdk-11-jre-headless
gcc-4.8, g++-4.8

Target //tensorflow/tools/pip_package:build_pip_package up-to-date:
  bazel-bin/tensorflow/tools/pip_package/build_pip_package
INFO: Elapsed time: 1806.409s, Critical Path: 138.18s
INFO: 6930 processes, local.
INFO: Build completed successfully, 7875 total actions

Hope it helps
