### ISSUE TITLE
5:1: C++ compilation of rule '//tensorflow/stream_executor:stream_executor' failed:

### ISSUE THREAD

**Issue by Dan1900** [tensorflow/tensorflow#3360]
I am using the latest branch of tensorflow 
Error:/home/xxxxx/bazel/output/bazel build -c opt --config=cuda //tensorflow/cc:tutorials_example_trainer --verbose_failures
/home/xxxxx/bazel/output/bazel build -c opt --config=cuda //tensorflow/cc:tutorials_example_trainer --verbose_failures
/home/newSpace/projects2/tensorflow/tensorflow/stream_executor/BUILD:5:1: C++ compilation of rule '//tensorflow/stream_executor:stream_executor' failed: crosstool_wrapper_driver_is_not_gcc failed: error executing command third_party/gpus/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc -U_FORTIFY_SOURCE '-D_FORTIFY_SOURCE=1' -fstack-protector -fPIE -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object ... (remaining 117 argument(s) skipped): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
tensorflow/stream_executor/cuda/cuda_dnn.cc: In function 'cudnnConvolutionFwdAlgo_t perftools::gputools::cuda::{anonymous}::ToConvForwardAlgo(perftools::gputools::dnn::AlgorithmType)':
tensorflow/stream_executor/cuda/cuda_dnn.cc:266:10: error: 'CUDNN_CONVOLUTION_FWD_ALGO_FFT_TILING' was not declared in this scope
     case CUDNN_CONVOLUTION_FWD_ALGO_FFT_TILING:
          ^
tensorflow/stream_executor/cuda/cuda_dnn.cc: In function 'cudnnConvolutionBwdDataAlgo_t perftools::gputools::cuda::{anonymous}::ToConvBackwardDataAlgo(perftools::gputools::dnn::AlgorithmType)':
tensorflow/stream_executor/cuda/cuda_dnn.cc:284:10: error: 'CUDNN_CONVOLUTION_BWD_DATA_ALGO_FFT_TILING' was not declared in this scope
     case CUDNN_CONVOLUTION_BWD_DATA_ALGO_FFT_TILING:
          ^
tensorflow/stream_executor/cuda/cuda_dnn.cc: In member function 'virtual bool perftools::gputools::cuda::CudnnSupport::GetConvolveAlgorithms(std::vector<long long int>*)':
tensorflow/stream_executor/cuda/cuda_dnn.cc:942:7: error: 'CUDNN_CONVOLUTION_FWD_ALGO_FFT_TILING' was not declared in this scope
       CUDNN_CONVOLUTION_FWD_ALGO_FFT_TILING,
       ^
tensorflow/stream_executor/cuda/cuda_dnn.cc:947:4: error: no matching function for call to 'std::vector<long long int>::assign(<brace-enclosed initializer list>)'
   });
    ^

**Comment by ibab** [comment]
Which version of cuDNN are you using?
cuDNN v4 seems to be working at the moment.

**Comment by concretevitamin** [comment]
Please report your complete environment info (see other issues).  Thanks!

**Comment by Dan1900** [comment]
ubuntu 14.04.4 LTS  
cuda7.0 
cudnn v4  
gcc 4.9.4

**Comment by Dan1900** [comment]
Thank you for your comments.I check my install steps again and find that I choose the cudnn 7.0,maybe it is the problem! when I change it to 4,it works.Thank you again.
