### ISSUE TITLE
tf.pow() overflow??

### ISSUE THREAD

**Issue by steph-en-m** [tensorflow/tensorflow#33603]
Env:
* Colab (with gpu on)
* TF 2.0
* Python3

Running tf.pow() with integer powers greater than 5 returns wrong results and to me it looks like an overflow.
```python
a = tf.constant(50)
b = tf.constant(6)
tf.pow(a,b)
```
The above returns:
```
tf.Tensor(-1554869184, shape=(), dtype=int32)
```
Which is mathematically wrong. Here is the result (the correct one) when using python's math library.
```python
import math
math.pow(50,6)
```
The above returns ```15625000000.0```

Using python's math library gives correct results for higher powers which I'd expect tf.pow() to do for integer inputs. 
Any explanation for this discrepancy!!

**Comment by oanush** [comment]
Issue replicating in TF-2.0, kindly find the [gist](https://colab.sandbox.google.com/gist/oanush/bb4b5fe54b25afa435b0055243f63d14/33603.ipynb) of colab.Thanks!

**Comment by blairhan** [comment]
Range for int32 is from -2,147,483,648 to 2,147,483,647 while the result you want exceeds the limit.
Therefore, the solution is
```
a = tf.constant(50, tf.int64)
b = tf.constant(6, tf.int64)
tf.pow(a,b)
```

which returns
`<tf.Tensor: id=2, shape=(), dtype=int64, numpy=15625000000>
`

**Comment by steph-en-m** [comment]
Thanks @oanush and @blairhan. I thought the types were applied implicitly but I get it now.

**Comment by gowthamkpr** [comment]
@steph-en-m Can you close this issue as it has been resolved. Thanks!

**Comment by steph-en-m** [comment]
> Thanks @oanush and @blairhan. I thought the types were applied implicitly but I get it now.

Actually am more interested in knowing why the tensorflow team chose to implement it this way (where one explicitly sets ```dtypes```) rather than the python ```math.pow()``` style implementation

**Comment by mihaimaruseac** [comment]
Because these types need to be propagated to the C++ core layer. Dynamic typing is not a panacea
