### ISSUE TITLE
[TF-Nighly] Keras object serialization breaks for certain object names

### ISSUE THREAD

**Issue by seanpmorgan** [tensorflow/tensorflow#33614]
## System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: Yes, but seq2seq maintained by Google
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: All
- **TensorFlow installed from (source or binary)**: Binary
- **TensorFlow version (use command below)**: tf-nightly > 20191018

### Describe the problem
Since b22fd65247633edfbc000c3bd9b9008502aedc33 serialization breaks if the name attribute of an object matches the name of a keras registered object. The check added compares `key,items` in a config and checks if the `item` matches the name of a registered object. This is brittle because `{'name': 'ObjectNameAttribute'}` appears in that config. Below I've attached a way to break the test case. 

This breaks all Attention mechanism serializations from seq2seq. E.g:
https://github.com/tensorflow/addons/blob/master/tensorflow_addons/seq2seq/attention_wrapper.py#L687
https://github.com/tensorflow/addons/blob/master/tensorflow_addons/seq2seq/attention_wrapper_test.py#L155

But also our activation layers who's default name matches the registered activation name:
https://github.com/tensorflow/addons/blob/master/tensorflow_addons/layers/sparsemax.py#L27
https://github.com/tensorflow/addons/blob/master/tensorflow_addons/activations/sparsemax.py#L27

I believe adding a check that `key` != `name` would fix this, but haven't thought through all of the implications.

### Source code / logs
Modified test case that breaks. Notice the `name` of Dense Layer matches a `custom_object` and thus breaks. 

```
import tensorflow as tf
import tensorflow.keras as keras


class SerDeTest(tf.test.TestCase):
    def test_nested_serializable_fn(self):
        def serializable_fn(x):
            """A serializable function to pass out of a test layer's config."""
            return x

        class SerializableNestedInt(int):
            """A serializable object containing a serializable function."""

            def __new__(cls, value, fn):
                obj = int.__new__(cls, value)
                obj.fn = fn
                return obj

            def get_config(self):
                return {'value': int(self), 'fn': self.fn}

            @classmethod
            def from_config(cls, config):
                return cls(**config)

        layer = keras.layers.Dense(
            SerializableNestedInt(3, serializable_fn),
            name='SerializableNestedInt',
            activation='relu',
            kernel_initializer='ones',
            bias_regularizer='l2')
        config = keras.layers.serialize(layer)
        new_layer = keras.layers.deserialize(
            config,
            custom_objects={
                'serializable_fn': serializable_fn,
                'SerializableNestedInt': SerializableNestedInt
            })
        self.assertEqual(new_layer.activation, keras.activations.relu)
        self.assertIsInstance(new_layer.bias_regularizer, keras.regularizers.L1L2)
        self.assertIsInstance(new_layer.units, SerializableNestedInt)
        self.assertEqual(new_layer.units, 3)
        self.assertIs(new_layer.units.fn, serializable_fn)


if __name__ == "__main__":
    tf.test.main()
```

`TypeError: __new__() missing 2 required positional arguments: 'value' and 'fn'`

cc @qlzh727 as owner for the seq2seq code that is breaking.

**Comment by qlzh727** [comment]
The fix will reach nightly tomorrow.

**Comment by seanpmorgan** [comment]
Thanks for the quick fix!

**Comment by seanpmorgan** [comment]
Since https://github.com/tensorflow/addons/pull/621 is still failing for one edge case, thought I'd re-open this for tracking.

**Comment by qlzh727** [comment]
Sorry for the late reply, it seems that the issue on addon side has been addressed in https://github.com/tensorflow/addons/pull/669. Closing this issue for now.
