### ISSUE TITLE
massive c++14 warning during build

### ISSUE THREAD

**Issue by alanpurple** [tensorflow/tensorflow#33618]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): windows 10 1903 x64
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): source
- TensorFlow version: 2.0.0
- Python version: 3.7.4 x64
- Installed using virtualenv? pip? conda?: N/A
- Bazel version (if compiling from source): 0.29.1
- GCC/Compiler version (if compiling from source):   VS 2017 build tools
- CUDA/cuDNN version: 10.1 / 7.6.4
- GPU model and memory: RTX 2080Ti GDDR6 11GB

**Describe the problem**
massive unknown option warning from compiler

the option '-std=c++14' should not be used

**Provide the exact sequence of commands / steps that you executed before running into the problem**
bazel build //tensorflow/tools/pip_package:build_pip_package

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.
```
cl : Command line warning D9002 : ignoring unknown option '-std=c++14'
```

**Comment by ravikyram** [comment]
@alanpurple 

Can you please let us know the output of ./configure.py. Thanks!

**Comment by alanpurple** [comment]
@ravikyram 
```
PS D:\repo\tensorflow> .\configure
WARNING: --batch mode is deprecated. Please instead explicitly shut down your Bazel server using the command "bazel shutdown".
You have bazel 0.29.1 installed.
Please specify the location of python. [Default is C:\Anaconda3\python.exe]:


Found possible Python library paths:
  C:\Anaconda3\lib\site-packages
Please input the desired Python library path to use.  Default is [C:\Anaconda3\lib\site-packages]

Do you wish to build TensorFlow with XLA JIT support? [y/N]:
No XLA JIT support will be enabled for TensorFlow.

Do you wish to build TensorFlow with ROCm support? [y/N]:
No ROCm support will be enabled for TensorFlow.

Do you wish to build TensorFlow with CUDA support? [y/N]: y
CUDA support will be enabled for TensorFlow.

Found CUDA 10.1 in:
    C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.1/lib/x64
    C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.1/include
Found cuDNN 7 in:
    C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.1/lib/x64
    C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.1/include


Please specify a list of comma-separated CUDA compute capabilities you want to build with.
You can find the compute capability of your device at: https://developer.nvidia.com/cuda-gpus.
Please note that each additional compute capability significantly increases your build time and binary size, and that TensorFlow only supports compute capabilities >= 3.5 [Default is: 3.5,7.0]: 6.1,7.5


Please specify optimization flags to use during compilation when bazel option "--config=opt" is specified [Default is /arch:AVX]:


Would you like to override eigen strong inline for some C++ compilation to reduce the compilation time? [Y/n]:
Eigen strong inline overridden.

Preconfigured Bazel build configs. You can use any of the below by adding "--config=<>" to your build command. See .bazelrc for more details.
        --config=mkl            # Build with MKL support.
        --config=monolithic     # Config for mostly static monolithic build.
        --config=ngraph         # Build with Intel nGraph support.
        --config=numa           # Build with NUMA support.
        --config=dynamic_kernels        # (Experimental) Build kernels into separate shared objects.
        --config=v2             # Build TensorFlow 2.x instead of 1.x.
Preconfigured Bazel build configs to DISABLE default on features:
        --config=noaws          # Disable AWS S3 filesystem support.
        --config=nogcp          # Disable GCP support.
        --config=nohdfs         # Disable HDFS support.
        --config=nonccl         # Disable NVIDIA NCCL support.
Configuration finished
```

**Comment by mihaimaruseac** [comment]
Does your compiler support c++14?

**Comment by alanpurple** [comment]
@mihaimaruseac 
as below blog says, yes

https://mariusbancila.ro/blog/2017/03/08/whats-new-in-visual-studio-2017-for-cpp-development/

**Comment by jevad** [comment]
I get this also.  I tried both bazel 0.29.1 and 1.2.0.  The problem is that '-std=c++14' is not a valid flag for cl.  The cl flag that should be used to specify the C++ 14 standard  is '/std:c++14'.

**Comment by mchenx** [comment]
yeah ~ above comment seems to be the reason to the issue

**Comment by juanlp** [comment]
> I get this also. I tried both bazel 0.29.1 and 1.2.0. The problem is that '-std=c++14' is not a valid flag for cl. The cl flag that should be used to specify the C++ 14 standard is '/std:c++14'.

Where do you update this? Thanks

**Comment by nikroc896** [comment]
@jevad Can you tell me the build command or the file where '/std:c++14' should be specified?

> I get this also. I tried both bazel 0.29.1 and 1.2.0. The problem is that '-std=c++14' is not a valid flag for cl. The cl flag that should be used to specify the C++ 14 standard is '/std:c++14'.

**Comment by tilakrayal** [comment]
@alanpurple ,
Is this still an issue?

Could you please update TensorFlow to the latest stable version v.2.6 and let us know if you are facing the same error. Thanks!
