### ISSUE TITLE
[TFLite, Bug] Unexpected weights changes after conversion

### ISSUE THREAD

**Issue by Vooblin** [tensorflow/tensorflow#33613]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): no
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: no
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below): VERSION=2.0.0, GIT_VERSION=v1.12.1-15611-g025365a736
- Python version: 3.6.8
- Bazel version (if compiling from source): 0.26.1
- GCC/Compiler version (if compiling from source): GCC 8.3.0
- CUDA/cuDNN version: CUDA Version: 10.1
- GPU model and memory: GeForce GTX 1080 Titan 11GB

**Describe the current behavior**
In this issue code from tensorflow/models is used (tensorflow/models/official/nlp/bert_modeling.py). After conversion weights of model seriously changes. After some minimal fixes in source code of tensorflow/models it is solved but program mustn't changes. Below I show some cases. Code of keras layer EmbeddingPostprocessor:
```
def call(self, inputs):
    """Implements call() for the layer."""
    unpacked_inputs = tf_utils.unpack_inputs(inputs)
    word_embeddings = unpacked_inputs[0]
    token_type_ids = unpacked_inputs[1]
    input_shape = tf_utils.get_shape_list(word_embeddings, expected_rank=3)
    batch_size = input_shape[0]
    seq_length = input_shape[1]
    width = input_shape[2]

    output = word_embeddings
    if self.use_type_embeddings:
      flat_token_type_ids = tf.reshape(token_type_ids, [-1])
      one_hot_ids = tf.one_hot(
          flat_token_type_ids,
          depth=self.token_type_vocab_size,
          dtype=self.dtype)
      token_type_embeddings = tf.matmul(one_hot_ids, self.type_embeddings)
      token_type_embeddings = tf.reshape(token_type_embeddings,
                                         [batch_size, seq_length, width])
      output += token_type_embeddings

    if self.use_position_embeddings:
      position_embeddings = tf.expand_dims(
          tf.slice(self.position_embeddings, [0, 0], [seq_length, width]),
          axis=0)

      output += position_embeddings

    output = self.output_layer_norm(output)
    output = self.output_dropout(output)

    return output
```

1) Without changes in source code. Weights are incorrect.
2) Fixes are shown under this point. In this case weights are correct.
```
if self.use_type_embeddings:
      flat_token_type_ids = tf.reshape(token_type_ids, [-1])
      token_type_embeddings = tf.gather(self.type_embeddings, flat_token_type_embeddings)
      token_type_embeddings = tf.reshape(token_type_embeddings,
                                         [batch_size, seq_length, width])
      output += token_type_embeddings
```
3) Use EmbeddingPostprocessor without position_embeddings. In this case weights are correct. Example with full code is in the part "Code to reproduce the issue"
```
outputs = EmbeddingPostprocessor(
    use_type_embeddings=True,
    token_type_vocab_size=2,
    use_position_embeddings=False,
    dtype=tf.float32)(input1, input2)
```

**Code to reproduce the issue**
```
import tensorflow as tf
import numpy as np

from official.nlp.bert_modeling import EmbeddingPostprocessor

size = 100

input1 = tf.keras.layers.Input(shape=(size, size), dtype=tf.float32, name='1')
input2 = tf.keras.layers.Input(shape=(size,), dtype=tf.int32, name='2')
outputs = EmbeddingPostprocessor(
    use_type_embeddings=True,
    token_type_vocab_size=2,
    dtype=tf.float32)(input1, input2)
model = tf.keras.Model(inputs=[input1, input2], outputs=outputs)

example1 = tf.constant(np.random.random_sample(size=(1, size, size)), dtype=tf.float32)
example2 = tf.constant(np.random.randint(2, size=(1, size), dtype=np.int32))
example = {'1': example1, '2': example2}

output1 = model.predict(example)

converter = tf.lite.TFLiteConverter.from_keras_model(model)
tflite_model = converter.convert()

interpreter = tf.lite.Interpreter(model_content=tflite_model)
interpreter.allocate_tensors()

input_details = interpreter.get_input_details()
output_details = interpreter.get_output_details()

interpreter.reset_all_variables()
interpreter.set_tensor(input_details[0]['index'], example[input_details[0]['name']])
interpreter.set_tensor(input_details[1]['index'], example[input_details[1]['name']])
interpreter.invoke()

output2 = interpreter.get_tensor(output_details[0]['index'])

print(np.sum(np.abs(output1 - output2)))
```

**Other info / logs**
* With error:
```
*** INFO MESSAGES ***
691.0672
```
* Without error:
```
*** INFO MESSAGES ***
0.0021286607
```

**Comment by gadagashwini** [comment]
@Vooblin, Since the associated PR has been merged. Can we close this issue.

**Comment by gadagashwini** [comment]
@Vooblin, Can you please let us know if you are happy to close if no issue persists. Thanks!

**Comment by Vooblin** [comment]
@gadagashwini Sorry, I missed your last comment and forgot about this issue. Associated PR fixed only code in tensorflow/models. I think that this issue related to problem with tflite converter and PR didn't fix it. So I think that problem wasn't solved but if you think that it's not so important and it doesn't need to be fixed then I won't mind closing this issue.

**Comment by amahendrakar** [comment]
@Vooblin,
Is this still an issue? Could you please update TensorFlow to v2.3 and check if you are facing the same issue. Thanks!
