### ISSUE TITLE
Is it possible to provide a demo of the uvccamera object detection in android by tensorflow lite ? 

### ISSUE THREAD

**Issue by WestbrookZero** [tensorflow/tensorflow#33629]
this demo "https://github.com/tensorflow/examples/tree/master/lite/examples/object_detection/android"
is android camera , i  need to use in uvccamera in android to detection object , i copy code to my uvccamera in android project , it is not detection right , so Is it possible to provide a demo of the uvccamera object detection in android by tensorflow lite ?

**Comment by jdduke** [comment]
This is really more of a StackOverflow question, can you please post there? As long as you can convert your camera image into a Bitmap, the code should largely remain the same. You'll just want to make sure you're doing the right cropping/scaling, and that you convert to RGB format.

**Comment by WestbrookZero** [comment]
I am really do the same with the tensorflow lite object detection android demo,  it is always detection wrong beyong camera size. I am already asked question on  StackOverflow , width is 640 , height is 480 ,  I use the main code : 
@Override
        public void onFrame(final ByteBuffer frame) {
                if (mFrame == null) {
                    mFrame = Bitmap.createBitmap(width, height, Bitmap.Config.ARGB_8888);
                }
				mUVCCameraView.getBitmap(mFrame);
				mTfDetector.rgbFrameBitmap = mFrame;
				mTfDetector.processImage();
		}

protected void processImage() {
    trackingOverlay.postInvalidate();
    //rgbFrameBitmap.setPixels(getRgbBytes(), 0, previewWidth, 0, 0, previewWidth, previewHeight);
    final Canvas canvas = new Canvas(croppedBitmap);
    canvas.drawBitmap(rgbFrameBitmap, frameToCropTransform, null);
    final SurfaceHolder holder = MainActivity.Instance().getResultView().getHolder();
    final long startTime = SystemClock.uptimeMillis();
    final List<Classifier.Recognition> results = detector.recognizeImage(croppedBitmap);
    lastProcessingTimeMs = SystemClock.uptimeMillis() - startTime;
    cropCopyBitmap = Bitmap.createBitmap(croppedBitmap);
    final Canvas canvas01 = new Canvas(cropCopyBitmap);
    final Paint paint = new Paint();
    paint.setColor(Color.RED);
    paint.setStyle(Style.STROKE);
    paint.setStrokeWidth(2.0f);
    float minimumConfidence = MINIMUM_CONFIDENCE_TF_OD_API;
    switch (MODE) {
      case TF_OD_API:
        minimumConfidence = MINIMUM_CONFIDENCE_TF_OD_API;
        break;
    }
    final List<Classifier.Recognition> mappedRecognitions =
            new LinkedList<Classifier.Recognition>();
    for (final Classifier.Recognition result : results) {
      final RectF location = result.getLocation();
      if (location != null && result.getConfidence() >= minimumConfidence) {
        canvas01.drawRect(location, paint);
        cropToFrameTransform.mapRect(location);
        result.setLocation(location);
        mappedRecognitions.add(result);
      }
    }
    tracker.trackResults(mappedRecognitions, currTimestamp);
    trackingOverlay.postInvalidate();
  }

**Comment by WestbrookZero** [comment]
@jdduke  I can directly get rgb bitmap from uvccamera , if should i use rgbFrameBitmap.setPixels(getRgbBytes(), 0, previewWidth, 0, 0, previewWidth, previewHeight); or i directly set mTfDetector.rgbFrameBitmap = mFrame; ?

**Comment by WestbrookZero** [comment]
thanks you .
