### ISSUE TITLE
tf.strings.split bug

### ISSUE THREAD

**Issue by fsx950223** [tensorflow/tensorflow#33623]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):binary
- TensorFlow version (use command below):1.15.0
- Python version:3.6.8
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'to_sparse'
**Describe the expected behavior**
The op should return SparseTensor or RaggedTensor
**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.
```python
import tensorflow as tf
tf.strings.split('a b')
```
**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

[colab](https://colab.research.google.com/drive/1PrFuL7hC25yRGmFfbwwRK1if9N8d1M9A)

**Comment by blairhan** [comment]
you need brackets for the input. Try this:
```
c = tf.strings.split(['a b'])
c.values
```

**Comment by fsx950223** [comment]
> You need brackets for the input. Try this:
> 
> ```
> c = tf.strings.split(['a b'])
> c.values
> ```

tf.strings.split('a b',result_type='RaggedTensor') works and returns a Tensor.In fact, it should return a RaggedTensor
