### ISSUE TITLE
tf.io.write_file truncates the file everytime

### ISSUE THREAD

**Issue by simpsam** [tensorflow/tensorflow#33639]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using): 2.0
- Are you willing to contribute it (Yes/No): Yes

**Describe the feature and the current behavior/state.**
tf.io.write_file is not able to append to the file. I have a scenario where I want to write the output of the network (text generation) to a file. However I use sharded execution of tf.function which writes to different files (suffixed by the shard range) so that I can handle the total billion range. This is not possible through current available API

**Will this change the current api? How?** A parameter to tf.io.write_file to append to the file.

**Who will benefit with this feature?** All users

**Any Other info.**

**Comment by mihaimaruseac** [comment]
Please post a code sample showcasing the bug

**Comment by mihaimaruseac** [comment]
Tested on `tf-nightly`, there is no bug:

```console
Python 3.7.3 (default, Apr  3 2019, 05:39:12) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
>>> tf.__version__
'2.1.0-dev20191024'
>>> tf.io.gfile.GFile('x', 'w').write('xyz')
>>> tf.io.gfile.GFile('x', 'w').write('asdf')
>>> tf.io.gfile.GFile('x', 'r').read()
'asdf'
>>> tf.io.gfile.GFile('x', 'a').write('xyz')
>>> tf.io.gfile.GFile('x', 'a').write('asdf')
>>> tf.io.gfile.GFile('x', 'r').read()
'asdfxyzasdf'
>>> 
```

**Comment by thkfly** [comment]
> Tested on `tf-nightly`, there is no bug:
> 
> ```
> Python 3.7.3 (default, Apr  3 2019, 05:39:12) 
> [GCC 8.3.0] on linux
> Type "help", "copyright", "credits" or "license" for more information.
> >>> import tensorflow as tf
> >>> tf.__version__
> '2.1.0-dev20191024'
> >>> tf.io.gfile.GFile('x', 'w').write('xyz')
> >>> tf.io.gfile.GFile('x', 'w').write('asdf')
> >>> tf.io.gfile.GFile('x', 'r').read()
> 'asdf'
> >>> tf.io.gfile.GFile('x', 'a').write('xyz')
> >>> tf.io.gfile.GFile('x', 'a').write('asdf')
> >>> tf.io.gfile.GFile('x', 'r').read()
> 'asdfxyzasdf'
> >>> 
> ```

however, 
tf.io.gfile.GFile could not open file when filename stored in tf.tensor while tf.function could
this is especially important inside tf.function
