### ISSUE TITLE
TFLite C++ example for Raspberry Pi

### ISSUE THREAD

**Issue by JesperChristensen89** [tensorflow/tensorflow#33637]
Having followed this guide: https://www.tensorflow.org/lite/guide/build_rpi I end up with a static library called `libtensorflow-lite.a`. 

There doesn't seem to be any instruction, documentation or examples available on how to actually use this for C++ on ARM. Some says to have a look at the `minimal.cc` example, but this does not include the static library nor does it include any compile instruction for ARM.

Can someone provide a working example?

**Comment by terryheo** [comment]
If you're looking for Makefile of minimal.cc, you can find it on https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/tools/make/Makefile#L280
