### ISSUE TITLE
embeddings tutorial has dead link to googlecode svn

### ISSUE THREAD

**Issue by eliben** [tensorflow/tensorflow#3363]
The page:

https://www.tensorflow.org/versions/r0.9/tutorials/word2vec/index.html#evaluating-embeddings-analogical-reasoning

Has a dead (404) link to https://word2vec.googlecode.com/svn/trunk/questions-words.txt

I'd submit a PR if I knew where it *should* point, but I don't :)

**Comment by ibab** [comment]
The project has been archived on Google code and it seems that there's no simple way to link to the file. It also looks like there's no official Github mirror.
Here's a link to an unofficial mirror, but I'm not sure whether it's a good idea to use this one:
https://raw.githubusercontent.com/dav/word2vec/master/data/questions-words.txt

I think the best solution would be to include the file in the TensorFlow repo itself right next to the word2vec example code.
The example code also needs to be adjusted, as it contains the old link:
https://github.com/tensorflow/tensorflow/blob/r0.9/tensorflow/models/embedding/word2vec.py#L57
Let's see what the tensorflow maintainers think.

**Comment by concretevitamin** [comment]
@martinwicke Can you take a look? Thanks.

**Comment by xmbrst** [comment]
Fixed in r0.10. Data is now available at http://download.tensorflow.org/data/questions-words.txt .
