### ISSUE TITLE
MKL is not enabled after building from source

### ISSUE THREAD

**Issue by Selotkin** [tensorflow/tensorflow#33630]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: NA
- TensorFlow installed from (source or binary): source
- TensorFlow version: 1.15
- Python version: 3.6.8
- Installed using virtualenv? pip? conda?:
- Bazel version (if compiling from source): 0.26.1
- GCC/Compiler version (if compiling from source): 7.4.0

**Describe the problem**
MKL is not enabled after building from source with -config=mkl. I have checked with the function tensorflow.pywrap_tensorflow.IsMklEnabled(). It returns "False".
**Provide the exact sequence of commands / steps that you executed before running into the problem**
I followed the installation guide on https://www.tensorflow.org/install/source. I build with:
`bazel build -c opt --copt=-march=native --copt=-mfpmath=both --config=mkl //tensorflow/tools/pip_package:build_pip_package`

How can I build correct with mkl enabled. Thank you in advance

**Comment by leslie-fang-intel** [comment]
TensorFlow version: 1.15
```
yes  "" | python configure.py
bazel build -c opt --copt=-march=native --copt=-mfpmath=both --config=mkl //tensorflow/tools/pip_package:build_pip_package
```
Test Code
```
import tensorflow
print(tensorflow.pywrap_tensorflow.IsMklEnabled())
```
which returns true.

**Comment by Selotkin** [comment]
@leslie-fang-intel Thanks, after several tries I finally built with MKL.
