### ISSUE TITLE
Build Tensorflow with Bazel not working

### ISSUE THREAD

**Issue by furkank75** [tensorflow/tensorflow#33633]
I would like build tensorflow with Bazel to use the compiled libary in c++. I run the following commands in cmd.
```
C:\Users\Furkan\Desktop\tensorflow-1.14.0>bazel build --config=opt
WARNING: Usage: bazel build <options> <targets>.
Invoke `bazel help build` for full description of usage and options.
Your request is correct, but requested an empty set of targets. Nothing will be built.
INFO: Build option --define has changed, discarding analysis cache.
INFO: Analyzed 0 targets (0 packages loaded, 0 targets configured).
INFO: Found 0 targets...
INFO: Elapsed time: 0.124s, Critical Path: 0.01s
INFO: 0 processes.
INFO: Build completed successfully, 1 total action
```
After that they create the folders in tensorflow, but the folders are empty.. What I do wrong??

bazel: 0.25.2
tensorflow: 1.14.0

**Comment by mihaimaruseac** [comment]
You are not passing a target to build. Please consult Bazel documentation and the [TF Install from source page](https://www.tensorflow.org/install/source_windows)

Closing as this is not a TF issue
