### ISSUE TITLE
Allow device groups / CPU in MirroredStrategy

### ISSUE THREAD

**Issue by olesalscheider** [tensorflow/tensorflow#33645]
**System information**
- TensorFlow version (you are using): 2.0
- Are you willing to contribute it (Yes/No): Yes

**Describe the feature and the current behavior/state.**

My neural network is too large to be trained on a single GPU. In this specific case I have one layer that needs a lot of memory but does not perform expensive computations.
I can train the network if I place this layer on the CPU (so that it uses main memory) or on another GPU.

But I still would like to use MirroredStrategy to distribute the training across multiple GPUs.
Currently this combination is not possible.

Therefore I would like to request a feature to place parts of the computations inside a cross-replica context on the CPU. In a more generic case MirroredStrategy could distribute computations across device groups (instead of devices) and allow the user to place operations on different devices inside the group.

This could look like follows:
```
strategy = tf.distribute.MirroredStrategy()
with strategy.scope():
        x = f1()
    with tf.device('/cpu:0'):
        y = f2(x)
```

Or like this in the general case:
```
strategy = tf.distribute.MirroredStrategy(devices=[['/gpu:0', '/gpu:1'], ['/gpu:3', '/gpu:4']])
with strategy.scope():
    with tf.device('/vgpu:0'):
        x = f1()
    with tf.device('/vgpu:1'):
        y = f2(x)
```

**Will this change the current api? How?**
The general case (device groups) needs a way to specify which devices are inside which group. See above for an example.

**Who will benefit with this feature?**
Everyone who wants to train larger models that do not fit into the VRAM of a single GPU but who still wants to use MirroredStrategy.

**Comment by yuefengz** [comment]
The model parallelism project is on our radar. We've actively been working on it: https://github.com/tensorflow/tensorflow/issues/27724

**Comment by rmothukuru** [comment]
@olesalscheider,
Can you please confirm if we can close this issue as it has been tracked in #27724. Thanks!

**Comment by olesalscheider** [comment]
Yes, I think both issues request the same feature. You can close this issue if you want.

**Comment by rmothukuru** [comment]
@olesalscheider,
Closing this issue as discussed above. Thanks!
