### ISSUE TITLE
Output names lost when loading Keras model in SavedModel format

### ISSUE THREAD

**Issue by cstruct** [tensorflow/tensorflow#33641]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux-5.0.0-25-generic-x86_64-with-Ubuntu-18.04-bionic
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.0.0
- Python version: 3.7.4

**Describe the current behavior**
When loading a Keras model saved in the `SavedModel` format the output names are lost. Losing the output names causes loading to fail if using dictionaries for configuring loss or metrics.

**Describe the expected behavior**
Output names to be restored when loading the model and dictionaries for losses to be working when loading the model.

**Code to reproduce the issue**
`output_names` is not restored and outputs are given new auto-generated names:
```py
import tensorflow as tf

i = tf.keras.layers.Input((1,))
x = tf.keras.layers.Dense(1, name='my-output')(i)
m = tf.keras.Model(i, x)
m.compile(loss='mse')

m.save('my-saved-model')
m2 = tf.keras.models.load_model('my-saved-model')
assert m2.output_names[0] == 'my-output'  # AssertionError
```

Model fails to load when using dictionaries for losses:
```py
import tensorflow as tf

i = tf.keras.layers.Input((1,))
x = tf.keras.layers.Dense(1, name='my-output')(i)
m = tf.keras.Model(i, x)
m.compile(loss={'my-output': 'mse'})
assert m.output_names[0] == 'my-output'

m.save('my-saved-model')
m2 = tf.keras.models.load_model('my-saved-model') # ValueError: Unknown entries in loss dictionary: ['my-output']. Only expected following keys: ['output_1']
```

**Comment by gadagashwini** [comment]
Issue is replicating with TF 2.0.0. Please take a look at the [gist](https://colab.sandbox.google.com/gist/gadagashwini/529b06c9cac349064ad90177da793da9/untitled223.ipynb). Thanks!

**Comment by ymodak** [comment]
```model.save``` method fails with precondition error in TF 2.0 nightly version '2.1.0-dev20191024'
```python
WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/ops/resource_variable_ops.py:1785: calling BaseResourceVariable.__init__ (from tensorflow.python.ops.resource_variable_ops) with constraint is deprecated and will be removed in a future version.
Instructions for updating:
If using Keras pass *_constraint arguments to layers.
---------------------------------------------------------------------------
FailedPreconditionError                   Traceback (most recent call last)
<ipython-input-1-edade35c87e6> in <module>()
      6 m.compile(loss='mse')
      7 
----> 8 m.save('my-saved-model')
      9 m2 = tf.keras.models.load_model('my-saved-model')
     10 assert m2.output_names[0] == 'my-output'  # AssertionError

6 frames
/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/lib/io/file_io.py in recursive_create_dir_v2(path)
    453     errors.OpError: If the operation fails.
    454   """
--> 455   pywrap_tensorflow.RecursivelyCreateDir(compat.as_bytes(path))
    456 
    457 

FailedPreconditionError: my-saved-model/variables; Not a directory
```

**Comment by ymodak** [comment]
This is fixed with latest tf version 2.1.0.-rc0. Thanks!

**Comment by k-w-w** [comment]
Confirming, thanks!

**Comment by LucaCappelletti94** [comment]
The issue seems to have resurfaced in version `2.17.0`. The gist that was linked is a dead link. Is there any solution suggested?
