### ISSUE TITLE
update tutorial for tensorflow object detection api , generate_tf_record is giving a tough time

### ISSUE THREAD

**Issue by devitnow15** [tensorflow/tensorflow#33644]
https://tensorflow-object-detection-api-tutorial.readthedocs.io/en/latest/training.html

update generate_tf_record file according to running version in tensor flow.

**Comment by imskr** [comment]
I would like to work on this. Please assign!

**Comment by ymodak** [comment]
The GitHub repository you are referring to is not maintained by offfical TensorFlow team.
Perhaps your issue is more suitable on https://github.com/sglvladi/TensorFlowObjectDetectionTutorial/issues.
Please try posting it there. Thanks!
