### ISSUE TITLE
Allow Keras ModelCheckpoint to save the best N checkpoints

### ISSUE THREAD

**Issue by iteal** [tensorflow/tensorflow#33658]
The callback tf.keras.callbacks.ModelCheckpoint allows to save the best checkpoint using save_best_only=True. In the Estimator API we can use tf.estimator.BestExporter that saves the top N checkpoints (parameter exports_to_keep). 

It seems using the Estimator API is becoming discouraged, for example I need to use compat v1 symbols to use the BestExporter.

Is it possible to update the Keras ModelCheckpoint class to allow to save the top N models instead of just the best?

**System information**
- TensorFlow version (you are using): 2.0
- Are you willing to contribute it (Yes/No): No

**Describe the feature and the current behavior/state.**

**Will this change the current api? How?**
Yes, the constructor of tf.keras.callbacks.ModelCheckpoint needs a new parameter which is the equivalent of tf.estimator.BestExporter exports_to_keep. We can keep save_best_only but the two parameters can't be used as the same time.

**Who will benefit with this feature?**
Everybody that wants to save several models. For example for model averaging.

**Any Other info.**

**Comment by schustmi** [comment]
I wrote a [ModelCheckpoint subclass](https://github.com/schustmi/tf_utils/blob/915fe5e231ca302b28cd02dc8ac2e4c772a62e0b/tf_utils/callbacks.py#L34) that implements this if you're still looking for this functionality.

**Comment by jvishnuvardhan** [comment]
@schustmi Thanks for the implementation.

@iteal Sorry for the late response. Do you think @schustmi 's custom callback will work for you?

Are you still interested in contributing? If yes, please feel free to open a PR in  [keras-team/keras repo.](https://github.com/keras-team/keras/issues) repository.

Please note that Keras development moved to keras-team/keras repository to focus on only keras. Thanks!
