### ISSUE TITLE
Iterator initialization fails on GPU, sometimes segfaults on creating next batch

### ISSUE THREAD

**Issue by neonrights** [tensorflow/tensorflow#33661]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: n/a
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below): 1.14
- Python version: 3.6.9
- Bazel version (if compiling from source): n/a
- GCC/Compiler version (if compiling from source): n/a
- CUDA/cuDNN version: 10.1/7.6
- GPU model and memory: 2 Tesla K80s

**Describe the current behavior**
session fails to initialize iterable dataset on GPU with message `tensorflow.python.framework.errors_impl.NotFoundError: No registered 'Const' OpKernel for GPU devices compatible with node {{node compression_type}}`.  No such issue occurs on CPU.  In some cases, the dataset initializes, but fetching the next set of data causes a segfault.  I have been unable to create simple code which reproduces the second effect.

**Describe the expected behavior**
dataset initializes and no segfault when creating next batch

**Code to reproduce the issue**
```python
import tensorflow as tf

from tensorflow.python.client import device_lib

def parse_line(line):
    items = tf.string_split([line])
    token_ids = tf.string_to_number(items.values, out_type=tf.int32)
    return token_ids

def get_gpu_name():
    devices = device_lib.list_local_devices()
    for device in devices:
        if device.device_type == "GPU":
            return device.name

def main():
    data_file = "data_file.txt"
    with open(data_file, 'w', encoding='utf-8') as f:
        f.write("0 1 2 3 4 5 6 7 8")
    dataset = tf.data.TextLineDataset(data_file).map(parse_line)
    data_iter = dataset.make_initializable_iterator()
    gpu_device = get_gpu_name()
    
    with tf.device(gpu_device):
        features = data_iter.get_next()

    with tf.Session() as session:
        session.run(data_iter.initializer) # <- tensorflow fails on this line
        session.run(features) # <- tensorflow sometimes segfaults on this line
```

**Other info / logs**
[gpu.log](https://github.com/tensorflow/tensorflow/files/3765376/gpu.log)

**Comment by neonrights** [comment]
I tried switching cuda versions from 10.1 to 9.0.  The error still occurs.  Can anyone give some clarity on possible causes for this bug?

**Comment by ravikyram** [comment]
@neonrights 
Can you try switching to cuda 10.0 (The TF-GPU 1.14 prebuilt binary supports cuda 10.0) and check. Also, looks like code is incomplete and share sample data file `data_file.txt` to reproduce the issue in our environment. It will help us in localizing the issue faster, Thanks!

**Comment by neonrights** [comment]
@ravikyram  `data_file.txt` is created by the script in `main()`

It's just a file containing vectors encoded as integers separated by spaces on each line e.g.
```
0 1 2 3 4 5 6 7 8 9
10 4 17 33
4 4 4 4 4 4 4
```

Switching to 10.0 fixes the issue in both the code sample above and my actual model training code.

**Comment by ravikyram** [comment]
@neonrights 

Please, let me know if we can close this issue since it looks to be fixed. Thanks!

**Comment by neonrights** [comment]
yes you can close the issue
