### ISSUE TITLE
[Simple Bug] 'name' should be a variable

### ISSUE THREAD

**Issue by walty19950301** [tensorflow/tensorflow#33668]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- TensorFlow version 1.13
- Python version: 3.6.8

**Describe the current behavior**
I want build two convLSTMCell and use them. like follow [Code to reproduce the issue]
tensorflow talk to me: `ValueError: Variable kernel already exists, disallowed. Did you mean to set reuse=True or reuse=tf.AUTO_REUSE in VarScope? Originally defined at xxxx.`

**Describe the expected behavior**
the code can run without error.

**Code to reproduce the issue**
```
import tensorflow as tf
import tensorflow.contrib.rnn as rnn
import numpy as np

npa = np.array([[[[1,2,3],[4,5,6],[4,5,6]],[[7,8,9],[10,11,12],[10,11,12]],[[13,14,15],[16,17,18],[16,17,18]]]])
print(npa.shape)
x = tf.constant(npa, dtype=tf.float32)
print(x)
# first cell
cell_encoder = rnn.Conv2DLSTMCell(input_shape=[x.shape[1], x.shape[2], x.shape[3]], output_channels=4,kernel_shape=[3, 3], name='encoder')
initial1 = cell_encoder.zero_state(batch_size=x.shape[0],dtype=tf.float32)
x1, fs1 = cell_encoder.call(inputs=x, state=initial1)
# second cell
cell_decoder = rnn.Conv2DLSTMCell(input_shape=[x.shape[1], x.shape[2], x.shape[3]], output_channels=4, kernel_shape=[3, 3], name='decoder')
initial2 = cell_decoder.zero_state(batch_size=x.shape[0], dtype=tf.float32)
x2, fs2 = cell_decoder.call(inputs=x, state=initial2)

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    x = sess.run(x2)
    print(x)
```
[minimal standalone code ]

**Other info / logs**
When system execution `[cell_decoder.call]`,  tensorflow talk to me: `ValueError: Variable kernel already exists, disallowed. Did you mean to set reuse=True or reuse=tf.AUTO_REUSE in VarScope? Originally defined at xxxx`.
then ,i tack the code find `tensorflow/contrib/rnn/python/ops/rnn_cell.py line: 2215 & 2228, vs.get_variable function `name of the function should be a variable, not a constant.
the issue is simple. If the name  is a constant, the second cell, cell_decoder, will use the same one variable.

Thanks to tensorflow for providing AI open source framework.  O(∩_∩)O

**Comment by ravikyram** [comment]
Looks like code is incomplete. In order to expedite the trouble-shooting process, please provide a minimal standalone code to reproduce the issue reported here. Thanks!

**Comment by mihaimaruseac** [comment]
Please use triple backticks before and after the code to make it easier to read. Every textbox on GitHub has a small M and a down arrow just above the Comment/Submit/etc. green button. Clicking on it will give you a tutorial on how to properly use Markdown. Please use it properly so issues can be analyzed faster

**Comment by walty19950301** [comment]
> Looks like code is incomplete. In order to expedite the trouble-shooting process, please provide a minimal standalone code to reproduce the issue reported here. Thanks!

i’m change the [Code to reproduce the issue]~

**Comment by ravikyram** [comment]
@walty19950301 

Any update please. Thanks!

**Comment by ravikyram** [comment]
I have tried on colab with TF version 1.13, 1.15 and was able to reproduce the issue.Please, find the gist [here.](https://colab.sandbox.google.com/gist/ravikyram/d49c453983908cdf90bd771bb4d4724a/untitled338.ipynb) Thanks!

**Comment by walty19950301** [comment]
> I have tried on colab with TF version 1.13, 1.15 and was able to reproduce the issue.Please, find the gist [here.](https://colab.sandbox.google.com/gist/ravikyram/d49c453983908cdf90bd771bb4d4724a/untitled338.ipynb) Thanks!


There is the key of the issue.  Every `rnn.Conv2DLSTMCell` will call same one `vs.get_variable`. (`Conv2DLSTMCell `call `call`, `call `call `_conv`, `_conv `call `vs.get_variable`)
```
/usr/local/lib/python3.6/dist-packages/tensorflow_core/contrib/rnn/python/ops/rnn_cell.py in _conv(args, filter_size, num_features, bias, bias_start)
   2228   # Now the computation.
   2229   kernel = vs.get_variable(
-> 2230       "kernel", filter_size + [total_arg_size_depth, num_features], dtype=dtype)
   2231   if len(args) == 1:
   2232     res = conv_op(args[0], kernel, strides, padding="SAME")
```
I use twice `rnn.Conv2DLSTMCell`. The first cell is right without error, but the second is error. The reason is that name of `vs.get_variable` is a constent. The first cell gets the 'kernel' variable, and the second cell should  get a new variable which not same with the 'kernel' varibale.

I think the `_conv` function should be modified as follow: (the wrong code is commented out by `#` )
```
def _conv(args, filter_size, num_features, bias, bias_start=0.0, name='_conv'):
  """Convolution.

  Args:
    args: a Tensor or a list of Tensors of dimension 3D, 4D or 5D,
    batch x n, Tensors.
    filter_size: int tuple of filter height and width.
    num_features: int, number of features.
    bias: Whether to use biases in the convolution layer.
    bias_start: starting value to initialize the bias; 0 by default.

  Returns:
    A 3D, 4D, or 5D Tensor with shape [batch ... num_features]

  Raises:
    ValueError: if some of the arguments has unspecified or wrong shape.
  """

  # Calculate the total size of arguments on dimension 1.
  total_arg_size_depth = 0
  shapes = [a.get_shape().as_list() for a in args]
  shape_length = len(shapes[0])
  for shape in shapes:
    if len(shape) not in [3, 4, 5]:
      raise ValueError("Conv Linear expects 3D, 4D "
                       "or 5D arguments: %s" % str(shapes))
    if len(shape) != len(shapes[0]):
      raise ValueError("Conv Linear expects all args "
                       "to be of same Dimension: %s" % str(shapes))
    else:
      total_arg_size_depth += shape[-1]
  dtype = [a.dtype for a in args][0]

  # determine correct conv operation
  if shape_length == 3:
    conv_op = nn_ops.conv1d
    strides = 1
  elif shape_length == 4:
    conv_op = nn_ops.conv2d
    strides = shape_length * [1]
  elif shape_length == 5:
    conv_op = nn_ops.conv3d
    strides = shape_length * [1]

  # Now the computation.
  # kernel = vs.get_variable(
  #     "kernel", filter_size + [total_arg_size_depth, num_features], dtype=dtype)
  kernel = vs.get_variable(
    name + "_kernel", filter_size + [total_arg_size_depth, num_features], dtype=dtype)
  if len(args) == 1:
    res = conv_op(args[0], kernel, strides, padding="SAME")
  else:
    res = conv_op(
        array_ops.concat(axis=shape_length - 1, values=args),
        kernel,
        strides,
        padding="SAME")
  if not bias:
    return res
  # bias_term = vs.get_variable(
  #     "biases", [num_features],
  #     dtype=dtype,
  #     initializer=init_ops.constant_initializer(bias_start, dtype=dtype))
  bias_term = vs.get_variable(
    name + "_biases", [num_features],
   dtype=dtype,
  initializer=init_ops.constant_initializer(bias_start, dtype=dtype))
  return res + bias_term
```

**Comment by gowthamkpr** [comment]
Contrib is being depricated @walty19950301 Can you please repeat this with TF 2.0 and see if the issue still persists?

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.
