### ISSUE TITLE
bus error (core dumped), when build with GPU support

### ISSUE THREAD

**Issue by luxiaolei** [tensorflow/tensorflow#3366]
I followed the installing from source tutorial, however in step
```
bazel-bin/tensorflow/cc/tutorials_example_trainer --use_gpu
```
I encountered the following message:
```
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcublas.so locally
[1]    5462 bus error (core dumped)  bazel-bin/tensorflow/cc/tutorials_example_trainer --use_gpu
```

Any helps would be great

### Environment info
Operating System:  Ubuntu 16.04

Installed version of CUDA and cuDNN: CUDA 8.0, cuDNN 5

(please attach the output of `ls -l /path/to/cuda/lib/libcud*`):
```
/usr/local/cuda/lib64/libcudadevrt.a
/usr/local/cuda/lib64/libcudart.so
/usr/local/cuda/lib64/libcudart.so.8.0
/usr/local/cuda/lib64/libcudart.so.8.0.27
/usr/local/cuda/lib64/libcudart_static.a
/usr/local/cuda/lib64/libcudnn.so
/usr/local/cuda/lib64/libcudnn.so.5
/usr/local/cuda/lib64/libcudnn.so.5.0.5
```

If installed from sources, provide the commit hash:
e95f4e760c6b6713b6b686ebeff9a1586a5831dd

### Steps to reproduce
1. flowed the tutorial of installing Tensorflow from source 

### What have you tried?
1. goolged around, but with no help

**Comment by concretevitamin** [comment]
I don't think CUDA 8.0 is fully, if at all, supported yet.  CUDA 7.0 to 7.5 should work.
