### ISSUE TITLE
Potential redundancy in using np.array

### ISSUE THREAD

**Issue by sayakpaul** [tensorflow/tensorflow#33667]
Thank you for submitting a TensorFlow documentation issue. Per our GitHub
policy, we only address code/doc bugs, performance issues, feature requests, and
build/installation issues on GitHub.

The TensorFlow docs are open source! To get involved, read the documentation
contributor guide: https://www.tensorflow.org/community/contribute/docs

## URL(s) with the issue:

Please provide a link to the documentation entry:
https://www.tensorflow.org/tutorials/generative/deepdream

## Description of the issue (what needs changing):
In this example, we are already performing this: `original_img = np.array(original_img)` in the beginning. Then, what is the point of repeating it here: `img = tf.constant(np.array(original_img))` and here: `shift_down, shift_right, img_rolled = random_roll(np.array(original_img), 512)`?

**Comment by gowthamkpr** [comment]
@sayakpaul Taking it up an octave and Scaling up with tiles are two different techniques.

In the 1st technique, you converted an image to tensor and then cast it to float32 to multiply it by an octave(i.e., floating point number) but in the second technique you are just passing in the original image that is a numpy array directly to the function.

I don't think this is redundant information.

**Comment by sayakpaul** [comment]
@gowthamkpr 

> @sayakpaul Taking it up an octave and Scaling up with tiles are two different techniques.

I guess I never mentioned scaling up octaves and tiling are the two same techniques. 

Regarding the redundancy, the order of the lines code (that I mentioned initially) in the tutorial goes like the following:

```
original_img = np.array(original_img)
img = tf.constant(np.array(original_img))
shift_down, shift_right, img_rolled = random_roll(np.array(original_img), 512)
```

All I am trying to say is if we are creating an `np.array` of the `original_img` in the very beginning then what's the point of doing it again for the downstream tasks as `original_img` is already an `np.array` (made in the first step)?

**Comment by gowthamkpr** [comment]
@sayakpaul Yes, I agree with you. We will take a look into it. Thanks!

**Comment by sayakpaul** [comment]
I opened a PR for the same as well. @gowthamkpr
