### ISSUE TITLE
How to write a dataset of serialized examples directly to a tfrecords file?

### ISSUE THREAD

**Issue by KristianHolsheimer** [tensorflow/tensorflow#33662]
I tried asking the broader community for this, but nothing came back, so I'm asking it here.

I have a `tf.data.Dataset` that contains serialized tfrecord/protobuf examples:

```python
>>> example = ds.make_one_shot_iterator().get_next()
>>> example
<tf.Tensor: id=42, shape=(), dtype=string, numpy=b'\n\xdd:\n\r\n\x01y\x12\x08\x12\x06\n\x...'>
```
So each example in the dataset `ds` is just a flat byte string.

What I'd like to do is to write these byte strings to disk (tfrecords file). The way I know to do this is to go through python land. For instance, using a tf1 session, this would look like:
```python
example = ds.make_one_shot_iterator().get_next()

with tf.io.TFRecordWriter("/path/to/output/data.tfrecords") as w:
    with tf.Session() as sess:
        w.write(sess.run(example))
```
This doesn't feel very efficient to me. So my question is:

- Is there a way that I can write this to a file without having to go through the python layer?

**Comment by jsimsa** [comment]
Does the [following guide](https://www.tensorflow.org/tutorials/load_data/tfrecord#tfrecord_files_using_tfdata) address your question?

cc @MarkDaoust

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.
