### ISSUE TITLE
[Docker] The 'tensorflow/tensorflow:1.15.0-py3' is missing on DockerHub

### ISSUE THREAD

**Issue by Ark-kun** [tensorflow/tensorflow#33665]
All other combinations of `tensorflow:1.15.0[-gpu][-py3][-jypyter]` are available.

**Comment by angerson** [comment]
Thank you for your report. It looks like our CI failed while uploading that specific image. I've re-deployed the missing image, and I'm investigating the CI system to ensure it catches future errors.
