### ISSUE TITLE
TensorFlow Lite Support for LSTM Models

### ISSUE THREAD

**Issue by deansk90** [tensorflow/tensorflow#33679]
**System information**
- TensorFlow version (you are using): 2.0.0
- Are you willing to contribute it (Yes/No): No

**Describe the feature and the current behavior/state.**
As mentioned in the TensorFlow Lite 2019 roadmap, a full support for LSTM and RNN models is expected. When this support is expected to be released? will it also support LSTM layers from Keras? 

**Will this change the current api? How?**
Not sure 

**Who will benefit with this feature?**
Everyone which would like to convert TensorFlow LSTM models to the TensorFlow lite format 

**Any Other info.**

**Comment by rmothukuru** [comment]
@deansk90,
Sorry for the delayed response. Can you please refer [TF Lite Guide for RNN/LSTM](https://www.tensorflow.org/lite/convert/rnn) and let us know if this is what you are looking for? Thanks!
