### ISSUE TITLE
TF lite GPU delegates should use the same linker script as main library

### ISSUE THREAD

**Issue by DoumanAsh** [tensorflow/tensorflow#33676]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Android/Ubuntu
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): Source
- TensorFlow version: 1.15.0
- Python version: 3.6.8
- Installed using virtualenv? pip? conda?: ip
- Bazel version (if compiling from source): 0.24.1
- GCC/Compiler version (if compiling from source): NDK r17b clang
- CUDA/cuDNN version: -
- GPU model and memory: -

**Describe the problem**
Currently libtensorflowlite.so is build with `"-Wl,--version-script,$(location //tensorflow/lite:tflite_version_script.lds)"`

The same is not done for gpu delegates.
Is there any particular reason for that?
I believe it should be applied to gpu delegate libraries too, as currently you'll need 
I don't believe any symbol other than tflite related symbols are necessary.
If `visibility=hidden` by default is ok (since I think we only need C API from GPU Delegate), then shouldn't it be default flag for the library?

Inconsistent symbol hiding makes it confusing when building both main library and gpu delegates
Would it be acceptable to hide symbols by default or use linker script as in main tflite library?

**Provide the exact sequence of commands / steps that you executed before running into the problem**

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by impjdi** [comment]
@DoumanAsh 

Sorry for the late reply; I've been out on a conference.

Hm, I'm not sure what that flag does, and re: your question of:

> Is there any particular reason for that?

The people owning TFLite and who delivers the TFLite GPU are different set of people with the latter (I belong here) being more agnostic of what the proper way is :p 

Please feel free to send a PR to me and @jdduke

**Comment by jdduke** [comment]
Hi @DoumanAsh, thanks for flagging, we should absolutely be consistent. If you want to propose a PR, feel free to, otherwise I can take a look.

**Comment by DoumanAsh** [comment]
Looking over at the delegate API, I see only C API (which is marked visible in code).
So I think the simplest approach would be is to by default build with `hidden` visibility.
Which doesn't require any extra linking script (which is what we do internally when we build delegate)

So I'd suggest it as PR for now as all vital APIs are marked with `TFL_CAPI_EXPORT` which resolves to corresponding attribute.
@jdduke does it sound good to you?

**Comment by DoumanAsh** [comment]
As a side question.
I noticed that 1.15 brought a new GPU Delegate.
Are there any plans for which is going to be a final one?

**Comment by impjdi** [comment]
The new GPU delegate you are referring to probably has the logic of "try to use OpenCL if available,  fallback to OpenGL otherwise".  I'm not 100% certain whether we will kill off the "old" OpenGL delegate, but chances are high.

**Comment by jdduke** [comment]
Hi @DoumanAsh, the V2 delegate is going to be the default going forward. The pre-compiled GPU delegate (on JCenter/Maven) has already been updated to use this variant, as has our benchmark tooling. We're preparing a blog post, and will likely deprecate the "V1" API at some point.

**Comment by DoumanAsh** [comment]
Good to know, I will be shifting our code base to use it then
