### ISSUE TITLE
tflite:experimental:micro:riscv: the default build target is wrong.

### ISSUE THREAD

**Issue by zhoupeng** [tensorflow/tensorflow#33677]
The intended target ( `make -f tensorflow/lite/experimental/micro/tools/make/Makefile TARGET=riscv32_mcu`) should be `all` , as in the README.md
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/experimental/micro/README.md.
But in fact it's not `all' by default.

**Comment by zhoupeng** [comment]
Fixed by pull request https://github.com/tensorflow/tensorflow/pull/33680, waiting for review.

**Comment by rockyrhodes** [comment]
Looks like @nkreeger has commented on your pull request.

**Comment by saikumarchalla** [comment]
@zhoupeng  PR is already  merged.  Please go  ahead and close the issue if you don't have any further queries.
