### ISSUE TITLE
download tensorboard vis export to image files

### ISSUE THREAD

**Issue by gideonite** [tensorflow/tensorflow#3368]
Has there been discussion of exporting tensorboard visualizations as images (e.g. `.png`)? This would be helpful for rough drafts and work-in-progress type presentations.

**Comment by danmane** [comment]
We haven't discussed this much, it's not on the radar at the moment.

**Comment by Anthony-Tatowicz** [comment]
The work around to this is just to download the data as csv and use something like excel to create visuals.

**Comment by gideonite** [comment]
Ah right. Awesome.

From the currently running tutorial csv download appears to be broken. Should I open an issue?

https://www.tensorflow.org/tensorboard/index.html#events

I'm also a bit confused why the csv and json download buttons are hidden behind a few clicks. What's the idea behind that?

**Comment by Anthony-Tatowicz** [comment]
Yeah seems like csv file didn't get generated. I would try it on local data to double check and if it still fails open an issue, as for the UI I have no idea. If you look here there is some helper scripts, but they sound sort of hacky atm and they make it sound like csv isn't supported yet.

https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tensorboard/README.md#how-can-i-export-data-from-tensorboard

**Comment by CJxD** [comment]
The easiest way I've found is to save the SVG element to a .svg file, and then in-line all the CSS. There's a handy bookmarklet that does it for you, found here: http://nytimes.github.io/svg-crowbar/

**Comment by wchargin** [comment]
CSV should be working fine in the current release, as should JSON.

@CJxD, thanks for sharing that workaround! Like @dandelionmane said, this isn't really high-priority for us at this time, so I'm closing it for now. If you like, feel free to open an issue in our new repository at https://github.com/tensorflow/tensorboard/issues. Thanks!
