### ISSUE TITLE
How can i predict on image classifier?

### ISSUE THREAD

**Issue by ktfth** [tensorflow/tensorflow#33692]
https://www.tensorflow.org/tutorials/images/classification

**Comment by bhadreshpsavani** [comment]
Can I work on it?

**Comment by ktfth** [comment]
Yes you have the link for an example

**Comment by ktfth** [comment]
I have made a test with other images and the prediction reach zeros and for me this is not good. Thank you a lot for the work on top of it.

**Comment by jvishnuvardhan** [comment]
@ktfth Are you testing your own images of cats and/or dogs? I think this network is made as a simple model to demonstrate the classification and related operations. If the prediction is not good for your images, then you can update the model by adding some more hidden layers.

Having said that this is not a build/installation or Bug and Performance issue.

This is not Build/Installation or Bug/Performance issue. Please post this kind of support questions at [Stackoverflow](https://stackoverflow.com/questions/tagged/tensorflow). There is a big community to support and learn from your questions. GitHub is mainly for addressing bugs in installation and performance. Thanks!
