### ISSUE TITLE
Tests for examples/learn

### ISSUE THREAD

**Issue by gideonite** [tensorflow/tensorflow#3370]
A little while ago I caught a bug with the [resnet example](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/examples/skflow/resnet.py) that could have been caught by an automated test.

What do people think about bringing in some kind of automated tests to examples/skflow? What sort of tests should these be? I think the first step would be to simply run the code regularly. That would have caught the bug with the resnet example.

**Comment by concretevitamin** [comment]
@ilblackdragon: can you comment on this, thanks.

**Comment by ilblackdragon** [comment]
@gideonite That would be great. I think @zhangyaobit was planning to work on tests for some of the examples, but contributions definitely will be welcome.

**Comment by zhangyaobit** [comment]
Yes, I actually added the "first step" to run code regularly :) 
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/examples/skflow/examples_test.sh

This list only covers about half of the examples in examples/skflow though. I have moved to and are currently occupied by other projects, so contributions are welcome to add other examples!

**Comment by terrytangyuan** [comment]
@zhangyaobit Awesome!

**Comment by michaelisard** [comment]
@ilblackdragon if nobody in the TensorFlow org is going to work on this should I mark it 'contributions welcome'?

**Comment by gideonite** [comment]
I'm going to get started on it tonight. Been trying to get to it all week.
Sorry for the lack of communication.

**Comment by gideonite** [comment]
Stupid question: how do you run this test script? I can't find any documentation. I've done some grepping around the code base and determined that the most reasonable thing should be something like:

```
bazel test //tensorflow/examples/skflow
```

But running this gives:

```
WARNING: Sandboxed execution is not supported on your system and thus hermeticity of actions cannot be guaranteed. See http://bazel.io/docs/bazel-user-manual.html#sandboxing for more information. You can turn off this warning via --ignore_unsupported_sandboxing.
ERROR: no such target '//tensorflow/examples/skflow:skflow': target 'skflow' not declared in package 'tensorflow/examples/skflow' defined by /path/to/my/install/gideonite-tensorflow/tensorflow/examples/skflow/BUILD.
INFO: Elapsed time: 0.727s
ERROR: Couldn't start the build. Unable to run tests.
```

**Comment by ilblackdragon** [comment]
@gideonite  You need to have py_test targets in the `tensorflow/examples/skflow/BUILD` file.
For example target `mnist_test`, then you can run it with `blaze test //tensorflow/examples/skflow:mnist_test`.

**Comment by ilblackdragon** [comment]
Current status: we have script to run tests, but they are manual and long - which at the end is going to still lead to rotting of the code. Still pending a more robust solution.

**Comment by drpngx** [comment]
Closing since it's a bit open-ended. Feel free to open a new issue if we need to reconsider.
