### ISSUE TITLE
build tensorflow on mac failed

### ISSUE THREAD

**Issue by dongxiao92** [tensorflow/tensorflow#33702]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: macOS high sierra
- **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device**: No
- **TensorFlow installed from (source or binary)**: source
- **TensorFlow version (use command below)**: source on branch r1.13
- **Python version**: 3.6.5(Anaconda)
- **Bazel version (if compiling from source)**: 0.21.0
- **GCC/Compiler version (if compiling from source)**: Apple LLVM version 9.1.0 (clang-902.0.39.2)
- **CUDA/cuDNN version**: No
- **GPU model and memory**: No
- **Exact command to reproduce**:
```
git checkout r1.13
./configure
only XLA support is enabled
bazel build --config=opt //tensorflow/tools/pip_package:build_pip_package --verbose_failures
```

### Describe the problem
build tensoeflow from source failed.

> ImportError: dlopen(/private/var/tmp/_bazel_dongxiao/c0c832007eb15ba2db0e9df6a49eabb9/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/create_tensorflow.python_api_1_tf_python_api_gen_v1.runfiles/org_tensorflow/tensorflow/python/_pywrap_tensorflow_internal.so, 6): Symbol not found: __ZN10tensorflow19XlaCompilationCache28kDefaultCompilationThresholdE

### Source code / logs
INFO: From Linking tensorflow/core/libgpu_runtime_impl.lo:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: bazel-out/darwin-opt/bin/tensorflow/core/libgpu_runtime_impl.lo(gpu_device.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: bazel-out/darwin-opt/bin/tensorflow/core/libgpu_runtime_impl.lo(gpu_device_factory.o) has no symbols
ERROR: /Users/dongxiao/working/tensorflow/tensorflow/BUILD:579:1: Executing genrule //tensorflow:tf_python_api_gen_v1 failed (Exit 1): bash failed: error executing command
  (cd /private/var/tmp/_bazel_dongxiao/c0c832007eb15ba2db0e9df6a49eabb9/execroot/org_tensorflow && \
  exec env - \
    PATH=/bin:/usr/bin \
    PYTHON_BIN_PATH=/Users/dongxiao/anaconda3/bin/python \
    PYTHON_LIB_PATH=/Users/dongxiao/anaconda3/lib/python3.6/site-packages \
    TF_DOWNLOAD_CLANG=0 \
    TF_NEED_CUDA=0 \
    TF_NEED_OPENCL_SYCL=0 \
    TF_NEED_ROCM=0 \
  /bin/bash -c 'source external/bazel_tools/tools/genrule/genrule-setup.sh; bazel-out/host/bin/tensorflow/create_tensorflow.python_api_1_tf_python_api_gen_v1 --root_init_template=tensorflow/api_template_v1.__init__.py --apidir=bazel-out/darwin-opt/genfiles/tensorflow_api/v1/ --apiname=tensorflow --apiversion=1 --compat_apiversion=1  --compat_init_template=tensorflow/compat_template_v1.__init__.py --package=tensorflow.python,tensorflow.lite.python.lite --output_package=tensorflow._api.v1 bazel-out/darwin-opt/genfiles/tensorflow/_api/v1/v1.py bazel-out/darwin-opt/genfiles/tensorflow/_api/v1/app/__init__.py bazel-out/darwin-opt/genfiles/tensorflow/_api/v1/autograph/__init__.py bazel-out/darwin-opt/genfiles/tensorflow/_api/v1/autograph/experimental/__init__.py bazel-out/darwin-opt/genfiles/tensorflow/_api/v1/bitwise/__init__.py bazel-out/darwin-opt/genfiles/tensorflow/_api/v1/compat/__init__.py bazel-out/darwin-opt/genfiles/tensorflow/_api/v1/data/__init__.py bazel-out/darwin-opt/genfiles/tensorflow/_api/v1/data/experimental/__init__.py bazel-out/darwin-opt/genfiles/tensorflow/_api/v1/debugging/__init__.py bazel-out/darwin-opt/genfiles/tensorflow/_api/v1/distribute/__init__.py bazel-out/darwin-opt/genfiles/tensorflow/_api/v1/distributions/__init__.py bazel-out/darwin-opt/genfiles/tensorflow/_api/v1/dtypes/__init__.py bazel-out/darwin-opt/genfiles/tensorflow/_api/v1/errors/__init__.py bazel-out/darwin-opt/genfiles/tensorflow/_api/v1/experimental/__init__.py bazel-out/darwin-opt/genfiles/tensorflow/_api/v1/feature_column/__init__.py bazel-out/darwin-opt/genfiles/tensorflow/_api/v1/gfile/__init__.py bazel-out/darwin-opt/genfiles/tensorflow/_api/v1/io/gfile/__init__.py bazel-out/darwin-opt/genfiles/tensorflow/_api/v1/graph_util/__init__.py bazel-out/darwin-opt/genfiles/tensorflow/_api/v1/image/__init__.py bazel-out/darwin-opt/genfiles/tensorflow/_api/v1/io/__init__.py bazel-out/darwin-opt/genfiles/tensorflow/_api/v1/queue/__init__.py bazel-out/darwin-opt/genfiles/tensorflow/_api/v1/initializers/__init__.py bazel-out/darwin-opt/genfiles/tensorflow/_api/v1/keras/__init__.py bazel-out/darwin-opt/genfiles/tensorflow/_api/v1/keras/activations/__init__.py bazel-out/darwin-opt/genfiles/tensorflow/_api/v1/keras/applications/__init__.py bazel-out/darwin-opt/genfiles/tensorflow/_api/v1/keras/applications/densenet/__init__.py bazel-out/darwin-opt/genfiles/tensorflow/_api/v1/keras/applications/inception_resnet_v2/__init__.py bazel-out/darwin-opt/genfiles/tensorflow/_api/v1/keras/applications/inception_v3/__init__.py bazel-out/darwin-opt/genfiles/tensorflow/_api/v1/keras/applications/mobilenet/__init__.py bazel-out/darwin-opt/genfiles/tensorflow/_api/v1/keras/applications/mobilenet_v2/__init__.py bazel-out/darwin-opt/genfiles/tensorflow/_api/v1/keras/applications/nasnet/__init__.py bazel-out/darwin-opt/genfiles/tensorflow/_api/v1/keras/applications/resnet50/__init__.py bazel-out/darwin-opt/genfiles/tensorflow/_api/v1/keras/applications/vgg16/__init__.py bazel-out/darwin-opt/genfiles/tensorflow/_api/v1/keras/applications/vgg19/__init__.py bazel-out/darwin-opt/genfiles/tensorflow/_api/v1/keras/applications/xception/__init__.py bazel-out/darwin-opt/genfiles/tensorflow/_api/v1/keras/backend/__init__.py bazel-out/darwin-opt/genfiles/tensorflow/_api/v1/keras/callbacks/__init__.py bazel-out/darwin-opt/genfiles/tensorflow/_api/v1/keras/constraints/__init__.py bazel-out/darwin-opt/genfiles/tensorflow/_api/v1/keras/datasets/__init__.py bazel-out/darwin-opt/genfiles/tensorflow/_api/v1/keras/datasets/boston_housing/__init__.py bazel-out/darwin-opt/genfiles/tensorflow/_api/v1/keras/datasets/cifar10/__init__.py bazel-out/darwin-opt/genfiles/tensorflow/_api/v1/keras/datasets/cifar100/__init__.py bazel-out/darwin-opt/genfiles/tensorflow/_api/v1/keras/datasets/fashion_mnist/__init__.py bazel-out/darwin-opt/genfiles/tensorflow/_api/v1/keras/datasets/imdb/__init__.py bazel-out/darwin-opt/genfiles/tensorflow/_api/v1/keras/datasets/mnist/__init__.py bazel-out/darwin-opt/genfiles/tensorflow/_api/v1/keras/datasets/reuters/__init__.py bazel-out/darwin-opt/genfiles/tensorflow/_api/v1/keras/estimator/__init__.py bazel-out/darwin-opt/genfiles/tensorflow/_api/v1/keras/experimental/__init__.py bazel-out/darwin-opt/genfiles/tensorflow/_api/v1/keras/initializers/__init__.py bazel-out/darwin-opt/genfiles/tensorflow/_api/v1/keras/layers/__init__.py bazel-out/darwin-opt/genfiles/tensorflow/_api/v1/keras/losses/__init__.py bazel-out/darwin-opt/genfiles/tensorflow/_api/v1/keras/metrics/__init__.py bazel-out/darwin-opt/genfiles/tensorflow/_api/v1/keras/models/__init__.py bazel-out/darwin-opt/genfiles/tensorflow/_api/v1/keras/optimizers/__init__.py bazel-out/darwin-opt/genfiles/tensorflow/_api/v1/keras/preprocessing/__init__.py bazel-out/darwin-opt/genfiles/tensorflow/_api/v1/keras/preprocessing/image/__init__.py bazel-out/darwin-opt/genfiles/tensorflow/_api/v1/keras/preprocessing/sequence/__init__.py bazel-out/darwin-opt/genfiles/tensorflow/_api/v1/keras/preprocessing/text/__init__.py bazel-out/darwin-opt/genfiles/tensorflow/_api/v1/keras/regularizers/__init__.py bazel-out/darwin-opt/genfiles/tensorflow/_api/v1/keras/utils/__init__.py bazel-out/darwin-opt/genfiles/tensorflow/_api/v1/keras/wrappers/__init__.py bazel-out/darwin-opt/genfiles/tensorflow/_api/v1/keras/wrappers/scikit_learn/__init__.py bazel-out/darwin-opt/genfiles/tensorflow/_api/v1/layers/__init__.py bazel-out/darwin-opt/genfiles/tensorflow/_api/v1/layers/experimental/__init__.py bazel-out/darwin-opt/genfiles/tensorflow/_api/v1/linalg/__init__.py bazel-out/darwin-opt/genfiles/tensorflow/_api/v1/lite/__init__.py bazel-out/darwin-opt/genfiles/tensorflow/_api/v1/lite/constants/__init__.py bazel-out/darwin-opt/genfiles/tensorflow/_api/v1/logging/__init__.py bazel-out/darwin-opt/genfiles/tensorflow/_api/v1/losses/__init__.py bazel-out/darwin-opt/genfiles/tensorflow/_api/v1/manip/__init__.py bazel-out/darwin-opt/genfiles/tensorflow/_api/v1/math/__init__.py bazel-out/darwin-opt/genfiles/tensorflow/_api/v1/metrics/__init__.py bazel-out/darwin-opt/genfiles/tensorflow/_api/v1/nn/__init__.py bazel-out/darwin-opt/genfiles/tensorflow/_api/v1/nn/rnn_cell/__init__.py bazel-out/darwin-opt/genfiles/tensorflow/_api/v1/profiler/__init__.py bazel-out/darwin-opt/genfiles/tensorflow/_api/v1/python_io/__init__.py bazel-out/darwin-opt/genfiles/tensorflow/_api/v1/quantization/__init__.py bazel-out/darwin-opt/genfiles/tensorflow/_api/v1/ragged/__init__.py bazel-out/darwin-opt/genfiles/tensorflow/_api/v1/random/__init__.py bazel-out/darwin-opt/genfiles/tensorflow/_api/v1/resource_loader/__init__.py bazel-out/darwin-opt/genfiles/tensorflow/_api/v1/strings/__init__.py bazel-out/darwin-opt/genfiles/tensorflow/_api/v1/saved_model/__init__.py bazel-out/darwin-opt/genfiles/tensorflow/_api/v1/saved_model/builder/__init__.py bazel-out/darwin-opt/genfiles/tensorflow/_api/v1/saved_model/constants/__init__.py bazel-out/darwin-opt/genfiles/tensorflow/_api/v1/saved_model/experimental/__init__.py bazel-out/darwin-opt/genfiles/tensorflow/_api/v1/saved_model/loader/__init__.py bazel-out/darwin-opt/genfiles/tensorflow/_api/v1/saved_model/main_op/__init__.py bazel-out/darwin-opt/genfiles/tensorflow/_api/v1/saved_model/signature_constants/__init__.py bazel-out/darwin-opt/genfiles/tensorflow/_api/v1/saved_model/signature_def_utils/__init__.py bazel-out/darwin-opt/genfiles/tensorflow/_api/v1/saved_model/tag_constants/__init__.py bazel-out/darwin-opt/genfiles/tensorflow/_api/v1/saved_model/utils/__init__.py bazel-out/darwin-opt/genfiles/tensorflow/_api/v1/sets/__init__.py bazel-out/darwin-opt/genfiles/tensorflow/_api/v1/signal/__init__.py bazel-out/darwin-opt/genfiles/tensorflow/_api/v1/sparse/__init__.py bazel-out/darwin-opt/genfiles/tensorflow/_api/v1/spectral/__init__.py bazel-out/darwin-opt/genfiles/tensorflow/_api/v1/summary/__init__.py bazel-out/darwin-opt/genfiles/tensorflow/_api/v1/sysconfig/__init__.py bazel-out/darwin-opt/genfiles/tensorflow/_api/v1/test/__init__.py bazel-out/darwin-opt/genfiles/tensorflow/_api/v1/train/__init__.py bazel-out/darwin-opt/genfiles/tensorflow/_api/v1/train/queue_runner/__init__.py bazel-out/darwin-opt/genfiles/tensorflow/_api/v1/user_ops/__init__.py bazel-out/darwin-opt/genfiles/tensorflow/_api/v1/version/__init__.py bazel-out/darwin-opt/genfiles/tensorflow/_api/v1/compat/v1/__init__.py bazel-out/darwin-opt/genfiles/tensorflow/_api/v1/compat/v1/app/__init__.py bazel-out/darwin-opt/genfiles/tensorflow/_api/v1/compat/v1/autograph/__init__.py bazel-out/darwin-opt/genfiles/tensorflow/_api/v1/compat/v1/autograph/experimental/__init__.py bazel-out/darwin-opt/genfiles/tensorflow/_api/v1/compat/v1/bitwise/__init__.py bazel-out/darwin-opt/genfiles/tensorflow/_api/v1/compat/v1/compat/__init__.py bazel-out/darwin-opt/genfiles/tensorflow/_api/v1/compat/v1/data/__init__.py bazel-out/darwin-opt/genfiles/tensorflow/_api/v1/compat/v1/data/experimental/__init__.py bazel-out/darwin-opt/genfiles/tensorflow/_api/v1/compat/v1/debugging/__init__.py bazel-out/darwin-opt/genfiles/tensorflow/_api/v1/compat/v1/distribute/__init__.py bazel-out/darwin-opt/genfiles/tensorflow/_api/v1/compat/v1/distributions/__init__.py bazel-out/darwin-opt/genfiles/tensorflow/_api/v1/compat/v1/dtypes/__init__.py bazel-out/darwin-opt/genfiles/tensorflow/_api/v1/compat/v1/errors/__init__.py bazel-out/darwin-opt/genfiles/tensorflow/_api/v1/compat/v1/experimental/__init__.py bazel-out/darwin-opt/genfiles/tensorflow/_api/v1/compat/v1/feature_column/__init__.py bazel-out/darwin-opt/genfiles/tensorflow/_api/v1/compat/v1/gfile/__init__.py bazel-out/darwin-opt/genfiles/tensorflow/_api/v1/compat/v1/io/gfile/__init__.py bazel-out/darwin-opt/genfiles/tensorflow/_api/v1/compat/v1/graph_util/__init__.py bazel-out/darwin-opt/genfiles/tensorflow/_api/v1/compat/v1/image/__init__.py bazel-out/darwin-opt/genfiles/tensorflow/_api/v1/compat/v1/io/__init__.py bazel-out/darwin-opt/genfiles/tensorflow/_api/v1/compat/v1/queue/__init__.py bazel-out/darwin-opt/genfiles/tensorflow/_api/v1/compat/v1/initializers/__init__.py bazel-out/darwin-opt/genfiles/tensorflow/_api/v1/compat/v1/keras/__init__.py bazel-out/darwin-opt/genfiles/tensorflow/_api/v1/compat/v1/keras/activations/__init__.py bazel-out/darwin-opt/genfiles/tensorflow/_api/v1/compat/v1/keras/applications/__init__.py bazel-out/darwin-opt/genfiles/tensorflow/_api/v1/compat/v1/keras/applications/densenet/__init__.py bazel-out/darwin-opt/genfiles/tensorflow/_api/v1/compat/v1/keras/applications/inception_resnet_v2/__init__.py bazel-out/darwin-opt/genfiles/tensorflow/_api/v1/compat/v1/keras/applications/inception_v3/__init__.py bazel-out/darwin-opt/genfiles/tensorflow/_api/v1/compat/v1/keras/applications/mobilenet/__init__.py bazel-out/darwin-opt/genfiles/tensorflow/_api/v1/compat/v1/keras/applications/mobilenet_v2/__init__.py bazel-out/darwin-opt/genfiles/tensorflow/_api/v1/compat/v1/keras/applications/nasnet/__init__.py bazel-out/darwin-opt/genfiles/tensorflow/_api/v1/compat/v1/keras/applications/resnet50/__init__.py bazel-out/darwin-opt/genfiles/tensorflow/_api/v1/compat/v1/keras/applications/vgg16/__init__.py bazel-out/darwin-opt/genfiles/tensorflow/_api/v1/compat/v1/keras/applications/vgg19/__init__.py bazel-out/darwin-opt/genfiles/tensorflow/_api/v1/compat/v1/keras/applications/xception/__init__.py bazel-out/darwin-opt/genfiles/tensorflow/_api/v1/compat/v1/keras/backend/__init__.py bazel-out/darwin-opt/genfiles/tensorflow/_api/v1/compat/v1/keras/callbacks/__init__.py bazel-out/darwin-opt/genfiles/tensorflow/_api/v1/compat/v1/keras/constraints/__init__.py bazel-out/darwin-opt/genfiles/tensorflow/_api/v1/compat/v1/keras/datasets/__init__.py bazel-out/darwin-opt/genfiles/tensorflow/_api/v1/compat/v1/keras/datasets/boston_housing/__init__.py bazel-out/darwin-opt/genfiles/tensorflow/_api/v1/compat/v1/keras/datasets/cifar10/__init__.py bazel-out/darwin-opt/genfiles/tensorflow/_api/v1/compat/v1/keras/datasets/cifar100/__init__.py bazel-out/darwin-opt/genfiles/tensorflow/_api/v1/compat/v1/keras/datasets/fashion_mnist/__init__.py bazel-out/darwin-opt/genfiles/tensorflow/_api/v1/compat/v1/keras/datasets/imdb/__init__.py bazel-out/darwin-opt/genfiles/tensorflow/_api/v1/compat/v1/keras/datasets/mnist/__init__.py bazel-out/darwin-opt/genfiles/tensorflow/_api/v1/compat/v1/keras/datasets/reuters/__init__.py bazel-out/darwin-opt/genfiles/tensorflow/_api/v1/compat/v1/keras/estimator/__init__.py bazel-out/darwin-opt/genfiles/tensorflow/_api/v1/compat/v1/keras/experimental/__init__.py bazel-out/darwin-opt/genfiles/tensorflow/_api/v1/compat/v1/keras/initializers/__init__.py bazel-out/darwin-opt/genfiles/tensorflow/_api/v1/compat/v1/keras/layers/__init__.py bazel-out/darwin-opt/genfiles/tensorflow/_api/v1/compat/v1/keras/losses/__init__.py bazel-out/darwin-opt/genfiles/tensorflow/_api/v1/compat/v1/keras/metrics/__init__.py bazel-out/darwin-opt/genfiles/tensorflow/_api/v1/compat/v1/keras/models/__init__.py bazel-out/darwin-opt/genfiles/tensorflow/_api/v1/compat/v1/keras/optimizers/__init__.py bazel-out/darwin-opt/genfiles/tensorflow/_api/v1/compat/v1/keras/preprocessing/__init__.py bazel-out/darwin-opt/genfiles/tensorflow/_api/v1/compat/v1/keras/preprocessing/image/__init__.py bazel-out/darwin-opt/genfiles/tensorflow/_api/v1/compat/v1/keras/preprocessing/sequence/__init__.py bazel-out/darwin-opt/genfiles/tensorflow/_api/v1/compat/v1/keras/preprocessing/text/__init__.py bazel-out/darwin-opt/genfiles/tensorflow/_api/v1/compat/v1/keras/regularizers/__init__.py bazel-out/darwin-opt/genfiles/tensorflow/_api/v1/compat/v1/keras/utils/__init__.py bazel-out/darwin-opt/genfiles/tensorflow/_api/v1/compat/v1/keras/wrappers/__init__.py bazel-out/darwin-opt/genfiles/tensorflow/_api/v1/compat/v1/keras/wrappers/scikit_learn/__init__.py bazel-out/darwin-opt/genfiles/tensorflow/_api/v1/compat/v1/layers/__init__.py bazel-out/darwin-opt/genfiles/tensorflow/_api/v1/compat/v1/layers/experimental/__init__.py bazel-out/darwin-opt/genfiles/tensorflow/_api/v1/compat/v1/linalg/__init__.py bazel-out/darwin-opt/genfiles/tensorflow/_api/v1/compat/v1/lite/__init__.py bazel-out/darwin-opt/genfiles/tensorflow/_api/v1/compat/v1/lite/constants/__init__.py bazel-out/darwin-opt/genfiles/tensorflow/_api/v1/compat/v1/logging/__init__.py bazel-out/darwin-opt/genfiles/tensorflow/_api/v1/compat/v1/losses/__init__.py bazel-out/darwin-opt/genfiles/tensorflow/_api/v1/compat/v1/manip/__init__.py bazel-out/darwin-opt/genfiles/tensorflow/_api/v1/compat/v1/math/__init__.py bazel-out/darwin-opt/genfiles/tensorflow/_api/v1/compat/v1/metrics/__init__.py bazel-out/darwin-opt/genfiles/tensorflow/_api/v1/compat/v1/nn/__init__.py bazel-out/darwin-opt/genfiles/tensorflow/_api/v1/compat/v1/nn/rnn_cell/__init__.py bazel-out/darwin-opt/genfiles/tensorflow/_api/v1/compat/v1/profiler/__init__.py bazel-out/darwin-opt/genfiles/tensorflow/_api/v1/compat/v1/python_io/__init__.py bazel-out/darwin-opt/genfiles/tensorflow/_api/v1/compat/v1/quantization/__init__.py bazel-out/darwin-opt/genfiles/tensorflow/_api/v1/compat/v1/ragged/__init__.py bazel-out/darwin-opt/genfiles/tensorflow/_api/v1/compat/v1/random/__init__.py bazel-out/darwin-opt/genfiles/tensorflow/_api/v1/compat/v1/resource_loader/__init__.py bazel-out/darwin-opt/genfiles/tensorflow/_api/v1/compat/v1/strings/__init__.py bazel-out/darwin-opt/genfiles/tensorflow/_api/v1/compat/v1/saved_model/__init__.py bazel-out/darwin-opt/genfiles/tensorflow/_api/v1/compat/v1/saved_model/builder/__init__.py bazel-out/darwin-opt/genfiles/tensorflow/_api/v1/compat/v1/saved_model/constants/__init__.py bazel-out/darwin-opt/genfiles/tensorflow/_api/v1/compat/v1/saved_model/experimental/__init__.py bazel-out/darwin-opt/genfiles/tensorflow/_api/v1/compat/v1/saved_model/loader/__init__.py bazel-out/darwin-opt/genfiles/tensorflow/_api/v1/compat/v1/saved_model/main_op/__init__.py bazel-out/darwin-opt/genfiles/tensorflow/_api/v1/compat/v1/saved_model/signature_constants/__init__.py bazel-out/darwin-opt/genfiles/tensorflow/_api/v1/compat/v1/saved_model/signature_def_utils/__init__.py bazel-out/darwin-opt/genfiles/tensorflow/_api/v1/compat/v1/saved_model/tag_constants/__init__.py bazel-out/darwin-opt/genfiles/tensorflow/_api/v1/compat/v1/saved_model/utils/__init__.py bazel-out/darwin-opt/genfiles/tensorflow/_api/v1/compat/v1/sets/__init__.py bazel-out/darwin-opt/genfiles/tensorflow/_api/v1/compat/v1/signal/__init__.py bazel-out/darwin-opt/genfiles/tensorflow/_api/v1/compat/v1/sparse/__init__.py bazel-out/darwin-opt/genfiles/tensorflow/_api/v1/compat/v1/spectral/__init__.py bazel-out/darwin-opt/genfiles/tensorflow/_api/v1/compat/v1/summary/__init__.py bazel-out/darwin-opt/genfiles/tensorflow/_api/v1/compat/v1/sysconfig/__init__.py bazel-out/darwin-opt/genfiles/tensorflow/_api/v1/compat/v1/test/__init__.py bazel-out/darwin-opt/genfiles/tensorflow/_api/v1/compat/v1/train/__init__.py bazel-out/darwin-opt/genfiles/tensorflow/_api/v1/compat/v1/train/queue_runner/__init__.py bazel-out/darwin-opt/genfiles/tensorflow/_api/v1/compat/v1/user_ops/__init__.py bazel-out/darwin-opt/genfiles/tensorflow/_api/v1/compat/v1/version/__init__.py')
Execution platform: @bazel_tools//platforms:host_platform
Traceback (most recent call last):
  File "/private/var/tmp/_bazel_dongxiao/c0c832007eb15ba2db0e9df6a49eabb9/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/create_tensorflow.python_api_1_tf_python_api_gen_v1.runfiles/org_tensorflow/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/private/var/tmp/_bazel_dongxiao/c0c832007eb15ba2db0e9df6a49eabb9/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/create_tensorflow.python_api_1_tf_python_api_gen_v1.runfiles/org_tensorflow/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/private/var/tmp/_bazel_dongxiao/c0c832007eb15ba2db0e9df6a49eabb9/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/create_tensorflow.python_api_1_tf_python_api_gen_v1.runfiles/org_tensorflow/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/Users/dongxiao/anaconda3/lib/python3.6/imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "/Users/dongxiao/anaconda3/lib/python3.6/imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: dlopen(/private/var/tmp/_bazel_dongxiao/c0c832007eb15ba2db0e9df6a49eabb9/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/create_tensorflow.python_api_1_tf_python_api_gen_v1.runfiles/org_tensorflow/tensorflow/python/_pywrap_tensorflow_internal.so, 6): Symbol not found: __ZN10tensorflow19XlaCompilationCache28kDefaultCompilationThresholdE
  Referenced from: /private/var/tmp/_bazel_dongxiao/c0c832007eb15ba2db0e9df6a49eabb9/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/create_tensorflow.python_api_1_tf_python_api_gen_v1.runfiles/org_tensorflow/tensorflow/python/_pywrap_tensorflow_internal.so
  Expected in: flat namespace
 in /private/var/tmp/_bazel_dongxiao/c0c832007eb15ba2db0e9df6a49eabb9/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/create_tensorflow.python_api_1_tf_python_api_gen_v1.runfiles/org_tensorflow/tensorflow/python/_pywrap_tensorflow_internal.so

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/private/var/tmp/_bazel_dongxiao/c0c832007eb15ba2db0e9df6a49eabb9/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/create_tensorflow.python_api_1_tf_python_api_gen_v1.runfiles/org_tensorflow/tensorflow/python/tools/api/generator/create_python_api.py", line 27, in <module>
    from tensorflow.python.tools.api.generator import doc_srcs
  File "/private/var/tmp/_bazel_dongxiao/c0c832007eb15ba2db0e9df6a49eabb9/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/create_tensorflow.python_api_1_tf_python_api_gen_v1.runfiles/org_tensorflow/tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/private/var/tmp/_bazel_dongxiao/c0c832007eb15ba2db0e9df6a49eabb9/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/create_tensorflow.python_api_1_tf_python_api_gen_v1.runfiles/org_tensorflow/tensorflow/python/pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/private/var/tmp/_bazel_dongxiao/c0c832007eb15ba2db0e9df6a49eabb9/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/create_tensorflow.python_api_1_tf_python_api_gen_v1.runfiles/org_tensorflow/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/private/var/tmp/_bazel_dongxiao/c0c832007eb15ba2db0e9df6a49eabb9/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/create_tensorflow.python_api_1_tf_python_api_gen_v1.runfiles/org_tensorflow/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/private/var/tmp/_bazel_dongxiao/c0c832007eb15ba2db0e9df6a49eabb9/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/create_tensorflow.python_api_1_tf_python_api_gen_v1.runfiles/org_tensorflow/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/Users/dongxiao/anaconda3/lib/python3.6/imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "/Users/dongxiao/anaconda3/lib/python3.6/imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: dlopen(/private/var/tmp/_bazel_dongxiao/c0c832007eb15ba2db0e9df6a49eabb9/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/create_tensorflow.python_api_1_tf_python_api_gen_v1.runfiles/org_tensorflow/tensorflow/python/_pywrap_tensorflow_internal.so, 6): Symbol not found: __ZN10tensorflow19XlaCompilationCache28kDefaultCompilationThresholdE
  Referenced from: /private/var/tmp/_bazel_dongxiao/c0c832007eb15ba2db0e9df6a49eabb9/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/create_tensorflow.python_api_1_tf_python_api_gen_v1.runfiles/org_tensorflow/tensorflow/python/_pywrap_tensorflow_internal.so
  Expected in: flat namespace
 in /private/var/tmp/_bazel_dongxiao/c0c832007eb15ba2db0e9df6a49eabb9/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/create_tensorflow.python_api_1_tf_python_api_gen_v1.runfiles/org_tensorflow/tensorflow/python/_pywrap_tensorflow_internal.so

Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.
Target //tensorflow/tools/pip_package:build_pip_package failed to build

**Comment by ymodak** [comment]
Does your cpu support AVX instruction sets?

**Comment by dongxiao92** [comment]
@ymodak Yes, the result of `sysctl -a | grep machdep.cpu.features` is shown below.

> ➜  xla sysctl -a | grep machdep.cpu.features
> machdep.cpu.features: FPU VME DE PSE TSC MSR PAE MCE CX8 APIC SEP MTRR PGE MCA CMOV PAT PSE36 CLFSH DS ACPI MMX FXSR SSE SSE2 SS HTT TM PBE SSE3 PCLMULQDQ DTES64 MON DSCPL VMX EST TM2 SSSE3 FMA CX16 TPR PDCM SSE4.1 SSE4.2 x2APIC MOVBE POPCNT AES PCID XSAVE OSXSAVE SEGLIM64 TSCTMR AVX1.0 RDRAND F16C

**Comment by ymodak** [comment]
Can you try compiling TF with avx flag?

**Comment by dongxiao92** [comment]
@ymodak Thanks for your advice. I have switched to branch r1.14 and built tensorflow with xla successfully.
