### ISSUE TITLE
Is is possible to run Tensorflow Lite with threading disables / without Pthreads / only 1 thread

### ISSUE THREAD

**Issue by davlhd** [tensorflow/tensorflow#33710]
I am trying to compile TensorflowLite for emscripten (I am aware of TensorflowJS) and pthreads are currently disabled. Is there a way to use it without pthreads?

**Comment by jvishnuvardhan** [comment]
This is not Build/Installation or Bug/Performance issue. Please post this kind of support questions at [Stackoverflow](https://stackoverflow.com/questions/tagged/tensorflow). There is a big community to support and learn from your questions. GitHub is mainly for addressing bugs in installation and performance. Thanks!

**Comment by dhirajnitk** [comment]
@davlhd 
Did you manage to build tflite with emscripten?
Could you share the bazel/workspace file's for the configuration?
