### ISSUE TITLE
TFLITE MODEL INPUT DYNAMIC INPUT SIZE

### ISSUE THREAD

**Issue by tulasiram58827** [tensorflow/tensorflow#33711]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
- **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device**:
- **TensorFlow installed from (source or binary)**:binary
- **TensorFlow version (use command below)**: 1.14
- **Python version**:
- **Bazel version (if compiling from source)**:
- **GCC/Compiler version (if compiling from source)**:
- **CUDA/cuDNN version**:
- **GPU model and memory**:
- **Exact command to reproduce**:

You can collect some of this information using our environment capture script:

https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh

You can obtain the TensorFlow version with:

```bash
python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"
```

### Describe the problem
When I am resizing input tensor in tflite model and allocating the tensors I am getting error )Node number 0 (RESHAPE) failed to prepare.

### Source code / logs
 File "tflite_inference.py", line 176, in <module>
    inference_from_tflite(path_to_tflite,path_to_input)	
  File "tflite_inference.py", line 118, in inference_from_tflite
    interpreter.allocate_tensors()
  File "/home/asus/miniconda/espnet/tools/venv/lib/python3.7/site-packages/tensorflow/lite/python/interpreter.py", line 95, in allocate_tensors
    return self._interpreter.AllocateTensors()
  File "/home/asus/miniconda/espnet/tools/venv/lib/python3.7/site-packages/tensorflow/lite/python/interpreter_wrapper/tensorflow_wrap_interpreter_wrapper.py", line 106, in AllocateTensors
    return _tensorflow_wrap_interpreter_wrapper.InterpreterWrapper_AllocateTensors(self)
RuntimeError: tensorflow/lite/kernels/reshape.cc:58 num_input_elements != num_output_elements (44000 != 4000)Node number 0 (RESHAPE) failed to prepare.

Source Code:
        interpreter = tf.lite.Interpreter(model_path=tflite_model)
        #Getting the input data
        input_data = np.load(input_mel)
        print(input_data.shape)
        input_details = interpreter.get_input_details()
        output_details = interpreter.get_output_details()
        input_data_resized = np.reshape(input_data,(1,input_data.shape[0],80))
        interpreter.resize_tensor_input(input_details[0]['index'], (1, input_data.shape[0], 80))
        interpreter.allocate_tensors()
        interpreter.set_tensor(input_details[0]['index'],input_data_resized)
        interpreter.invoke()

**Comment by jvishnuvardhan** [comment]
@tulasiram58827 Can you please provide a simple standalone code to reproduce the issue? Thanks!

**Comment by tulasiram58827** [comment]
Use shape (1,550,80)

**Comment by tulasiram58827** [comment]
I had already provided the source code in the first comment itself. Now I am posting again the code to reproduce the issue:
interpreter = tf.lite.Interpreter(model_path=tflite_model)
#Getting the input data
input_data = np.load(input_mel)
print(input_data.shape)
input_details = interpreter.get_input_details()
output_details = interpreter.get_output_details()
input_data_resized = np.reshape(input_data,(1,input_data.shape[0],80))
interpreter.resize_tensor_input(input_details[0]['index'], (1, input_data.shape[0], 80))
interpreter.allocate_tensors()



I am also attaching the code which is used to convert into tensorflow lite model.

converter = tf.lite.TFLiteConverter.from_frozen_graph(
          graph_def_file, input_arrays, output_arrays,input_shapes = {"input_mel":[None,50,80]})
converter.allow_custom_ops=False
tflite_model = converter.convert()
open("output.tflite", "wb").write(tflite_model)

**Comment by jvishnuvardhan** [comment]
@tulasiram58827 Can you please create a colab and share with us. Currently, I cannot run your code as `graph_def_file` is missing. Thanks!

**Comment by tulasiram58827** [comment]
This is the colab notebook link:
https://colab.research.google.com/drive/10lvhLU9CQ53Ie9IiLNJmOTTyYlX13P-o

Graph def file:
[dc_11lakh.pb.tar.gz](https://github.com/tensorflow/tensorflow/files/3797812/dc_11lakh.pb.tar.gz)

**Comment by jvishnuvardhan** [comment]
@tulasiram58827 Unfortunately this is still not a standalone code. `input_data_resized` is missing. I replaced it with `input_data` and I get different error. Please check the gist [here](https://colab.sandbox.google.com/gist/jvishnuvardhan/82768ad01f5d57284992d5d8228a7a2b/dynamic_input.ipynb).

Please run the code in the colab before sending it. You could also check with `TF1.15` which is newer version. Thanks!

**Comment by tulasiram58827** [comment]
Sorry some details are missing. I updated the notebook and I am able to reproduce the same error with the updated notebook. Please check this [link](https://colab.research.google.com/gist/tulasiram58827/000ec1ebebae1bd90cc5c99bd3fdf1bd/dynamic_input.ipynb)

**Comment by tulasiram58827** [comment]
@jvishnuvardhan please look into this

**Comment by haozha111** [comment]
assigning this to nupurgarg@ who is working on dynamic shape support.

**Comment by tulasiram58827** [comment]
@gargn Any update on this

**Comment by gargn** [comment]
Support for unknown dimensions in TensorFlow Lite was added last week (5591208).

Can you try converting your model again with the `tf-nightly` (`pip install tf-nightly`). Convert the model with `experimental_new_converter = True`.

When you load the model it should have an additional field `shape_signature` that contains the shape with any unknown dimensions marked with `-1`. `shape` will have those dimensions marked with `1`.

You can then call `ResizeInputTensor` with the desired shape when running the interpreter. The generated model will only work on the latest TensorFlow version (i.e. the interpreter on the `tf-nightly` version you are running).

Currently, models using quantization are not supported.

**Comment by dathudeptrai** [comment]
@gargn Hi, i'm wondering why don't we set the fixed length large enough then use tf.slice or tf.boolean_mask to obtain the desired shape. Example the inputs_shape is [1, 1000] then we can pass the 2nd input tensor is the scalar real_length so we can easily obtain the desired inputs by using tf.slice(inputs, [0, 0], [-1, real_length]). By this way we also use with quantization.

**Comment by Zeeshan113-hub** [comment]
hello, everyone 
I have a model which I convert from mat file to file input size is 1x3x224x244.
I wanted to change the input size of Tensorflow in the android example so I use this model with the above size
