### ISSUE TITLE
same code run on different versions of tf cost large different gpu memory consumption.

### ISSUE THREAD

**Issue by Jar7** [tensorflow/tensorflow#33719]
HI,
In my two system(P40, CUDA9, CUDNN7), tf1.8 and tf1.12 are installed respectively, and the same piece of code runs in tf1.12 almost double the allocated gpu memory as in tf1.8.

I wrote the following code to simplify the comparison. At this time in tf1.8, 1241MiB gpu memory is allocated and in tf1.12, 737MiB gpu memory is allocated. How could I optimize the gpu memory allocation in tf? Any suggestion would be appreciated.
```
import tensorflow as tf                                                                                                              
config = tf.ConfigProto()
config.gpu_options.allow_growth = True
config.allow_soft_placement = True
a=tf.get_variable('a',(100,100))
b=tf.get_variable('b',(10000,10000))
sess=tf.Session(config=config)
sess.run(tf.global_variables_initializer())
```

**Comment by jvishnuvardhan** [comment]
@Jar7 Please try to use most recent TF versions (TF.1.15 or TF2.0) as there were several improvements in the performance. Please check the guides and tutorials provided in the TF website as for [gpu](https://www.tensorflow.org/guide/gpu), [distributed_training](https://www.tensorflow.org/guide/distributed_training) and [`tf.data`](https://www.tensorflow.org/guide/data_performance) for best performance using machine learning pipeline. Thanks!

**Comment by jvishnuvardhan** [comment]
This is not Build/Installation or Bug/Performance issue. Please post this kind of support questions at [Stackoverflow](https://stackoverflow.com/questions/tagged/tensorflow). There is a big community to support and learn from your questions. GitHub is mainly for addressing bugs in installation and performance. Thanks!

**Comment by Jar7** [comment]
> @Jar7 Please try to use most recent TF versions (TF.1.15 or TF2.0) as there were several improvements in the performance. Please check the guides and tutorials provided in the TF website as for [gpu](https://www.tensorflow.org/guide/gpu), [distributed_training](https://www.tensorflow.org/guide/distributed_training) and [`tf.data`](https://www.tensorflow.org/guide/data_performance) for best performance using machine learning pipeline. Thanks!

Hi, could you please specify the reason for different gpu memory allocation for the provided code on different version of tensorflow? I have read the tutorials about gpu, and cannot find the answer. It is straightforward that some gpu memory is unnecessary allocated. Is it a bug?

**Comment by jvishnuvardhan** [comment]
@Jar7 May be there was an over allocation in `TF1.8`, which is a very old version. The allocation with TF1.12 seems to be correct as I checked with `TF1.15` which is also taking similar allocation. I would suggest to use `TF1.15` as there were lots of performance improvements. Thanks!
