### ISSUE TITLE
GridRNNCell -> RNN TypeError: unsupported operand type(s) for +: 'int'

### ISSUE THREAD

**Issue by KendallWeihe** [tensorflow/tensorflow#3371]
I am unsure whether this is an issue in my code, or a bug in the contrib -> GridRNNCell.

Please see this SO post: http://stackoverflow.com/questions/38442025/tensorflow-grid-lstm-rnn-typeerror

**Comment by concretevitamin** [comment]
Marking as community support.

**Comment by KendallWeihe** [comment]
@concretevitamin can you find the pull request for `GridRNNCell`?
