### ISSUE TITLE
TypeError: An op outside of the function building code is being passed a Graph tensor

### ISSUE THREAD

**Issue by nbro** [tensorflow/tensorflow#33729]
**System information**
- Have I written custom code: Yes.
- OS Platform and Distribution: Mac OS Catalina: 10.15 (19A602)
- TensorFlow installed from: binary
- TensorFlow version: 2.0.0
- Python version: 3.7.4
- GPU model and memory: Intel Iris Pro 1536 MB

**Describe the current behavior**

I am getting the error

> tensorflow.python.eager.core._SymbolicException: Inputs to eager execution function cannot be Keras symbolic tensors, but found [<tf.Tensor 'conv2d_flipout/divergence_kernel:0' shape=() dtype=float32>]

After having gotten the exception

> TypeError: An op outside of the function building code is being passed a Graph tensor

See the detailed traceback below.

**Describe the expected behavior**

No error.

**Code to reproduce the issue**

```
from __future__ import print_function

import tensorflow as tf
import tensorflow_probability as tfp

# tf.compat.v1.disable_eager_execution()

def get_bayesian_model(input_shape=None, num_classes=10):
    model = tf.keras.Sequential()
    model.add(tf.keras.layers.Input(shape=input_shape))
    model.add(tfp.layers.Convolution2DFlipout(6, kernel_size=5, padding="SAME", activation=tf.nn.relu))
    model.add(tf.keras.layers.Flatten())
    model.add(tfp.layers.DenseFlipout(84, activation=tf.nn.relu))
    model.add(tfp.layers.DenseFlipout(num_classes))
    return model

def get_mnist_data(normalize=True):
    img_rows, img_cols = 28, 28
    (x_train, y_train), (x_test, y_test) = tf.keras.datasets.mnist.load_data()

    if tf.keras.backend.image_data_format() == 'channels_first':
        x_train = x_train.reshape(x_train.shape[0], 1, img_rows, img_cols)
        x_test = x_test.reshape(x_test.shape[0], 1, img_rows, img_cols)
        input_shape = (1, img_rows, img_cols)
    else:
        x_train = x_train.reshape(x_train.shape[0], img_rows, img_cols, 1)
        x_test = x_test.reshape(x_test.shape[0], img_rows, img_cols, 1)
        input_shape = (img_rows, img_cols, 1)

    x_train = x_train.astype('float32')
    x_test = x_test.astype('float32')

    if normalize:
        x_train /= 255
        x_test /= 255

    return x_train, y_train, x_test, y_test, input_shape


def train():
    # Hyper-parameters.
    batch_size = 128
    num_classes = 10
    epochs = 1

    # Get the training data.
    x_train, y_train, x_test, y_test, input_shape = get_mnist_data()

    # Get the model.
    model = get_bayesian_model(input_shape=input_shape, num_classes=num_classes)

    # Prepare the model for training.
    model.compile(optimizer=tf.keras.optimizers.Adam(), loss="sparse_categorical_crossentropy",
                  metrics=['accuracy'])

    # Train the model.
    model.fit(x_train, y_train, batch_size=batch_size, epochs=epochs, verbose=1)
    model.evaluate(x_test, y_test, verbose=0)


if __name__ == "__main__":
    train()
```

**Other info / logs**

```
WARNING:tensorflow:From /Users/nbro/Desktop/my_project/venv/lib/python3.7/site-packages/tensorflow_probability/python/layers/util.py:104: Layer.add_variable (from tensorflow.python.keras.engine.base_layer) is deprecated and will be removed in a future version.
Instructions for updating:
Please use `layer.add_weight` method instead.
2019-10-25 20:38:32.504579: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2019-10-25 20:38:32.517426: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x7fe25e59f290 executing computations on platform Host. Devices:
2019-10-25 20:38:32.517438: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): Host, Default Version
Train on 60000 samples
Traceback (most recent call last):
  128/60000 [..............................] - ETA: 7:32  File "/Users/nbro/Desktop/my_project/venv/lib/python3.7/site-packages/tensorflow_core/python/eager/execute.py", line 61, in quick_execute
    num_outputs)
TypeError: An op outside of the function building code is being passed
a "Graph" tensor. It is possible to have Graph tensors
leak out of the function building context by including a
tf.init_scope in your function building code.
For example, the following function will fail:
  @tf.function
  def has_init_scope():
    my_constant = tf.constant(1.)
    with tf.init_scope():
      added = my_constant * 2
The graph tensor has name: conv2d_flipout/divergence_kernel:0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/nbro/Desktop/my_project/my_module.py", line 63, in <module>
    train()
  File "/Users/nbro/Desktop/my_project/my_module.py", line 58, in train
    model.fit(x_train, y_train, batch_size=batch_size, epochs=epochs, verbose=1)
  File "/Users/nbro/Desktop/my_project/venv/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training.py", line 728, in fit
    use_multiprocessing=use_multiprocessing)
  File "/Users/nbro/Desktop/my_project/venv/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training_v2.py", line 324, in fit
    total_epochs=epochs)
  File "/Users/nbro/Desktop/my_project/venv/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training_v2.py", line 123, in run_one_epoch
    batch_outs = execution_function(iterator)
  File "/Users/nbro/Desktop/my_project/venv/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training_v2_utils.py", line 86, in execution_function
    distributed_function(input_fn))
  File "/Users/nbro/Desktop/my_project/venv/lib/python3.7/site-packages/tensorflow_core/python/eager/def_function.py", line 457, in __call__
    result = self._call(*args, **kwds)
  File "/Users/nbro/Desktop/my_project/venv/lib/python3.7/site-packages/tensorflow_core/python/eager/def_function.py", line 520, in _call
    return self._stateless_fn(*args, **kwds)
  File "/Users/nbro/Desktop/my_project/venv/lib/python3.7/site-packages/tensorflow_core/python/eager/function.py", line 1823, in __call__
    return graph_function._filtered_call(args, kwargs)  # pylint: disable=protected-access
  File "/Users/nbro/Desktop/my_project/venv/lib/python3.7/site-packages/tensorflow_core/python/eager/function.py", line 1141, in _filtered_call
    self.captured_inputs)
  File "/Users/nbro/Desktop/my_project/venv/lib/python3.7/site-packages/tensorflow_core/python/eager/function.py", line 1224, in _call_flat
    ctx, args, cancellation_manager=cancellation_manager)
  File "/Users/nbro/Desktop/my_project/venv/lib/python3.7/site-packages/tensorflow_core/python/eager/function.py", line 511, in call
    ctx=ctx)
  File "/Users/nbro/Desktop/my_project/venv/lib/python3.7/site-packages/tensorflow_core/python/eager/execute.py", line 75, in quick_execute
    "tensors, but found {}".format(keras_symbolic_tensors))
tensorflow.python.eager.core._SymbolicException: Inputs to eager execution function cannot be Keras symbolic tensors, but found [<tf.Tensor 'conv2d_flipout/divergence_kernel:0' shape=() dtype=float32>]
```

The problem is apparently related to the layer `tfp.layers.Convolution2DFlipout`. I know that if I use `tf.compat.v1.disable_eager_execution()` after having imported TensorFlow, I do not get the mentioned error anymore, but I would like to use TensorFlow's eager execution, avoid sessions or placeholders.

I opened the same issue here: https://github.com/tensorflow/probability/issues/620.

**Comment by ravikyram** [comment]
@nbro 
I tried reproducing the issue. However i am seeing different error`ValueError: No gradients provided for any variable: ['conv2d_flipout/kernel_posterior_loc:0', 'conv2d_flipout/kernel_posterior_untransformed_scale:0', 'conv2d_flipout/bias_posterior_loc:0', 'dense_flipout/kernel_posterior_loc:0', 'dense_flipout/kernel_posterior_untransformed_scale:0', 'dense_flipout/bias_posterior_loc:0', 'dense_flipout_1/kernel_posterior_loc:0', 'dense_flipout_1/kernel_posterior_untransformed_scale:0', 'dense_flipout_1/bias_posterior_loc:0'].`Please, find the gist [here](https://colab.sandbox.google.com/gist/ravikyram/1665e31f72a3207226543fb8d3589723/untitled313.ipynb).Thanks!

**Comment by nbro** [comment]
@ravikyram Please, use the following dependencies

```
Package                Version
---------------------- -------
absl-py                0.8.1  
astor                  0.8.0  
cloudpickle            1.1.1  
decorator              4.4.1  
gast                   0.2.2  
google-pasta           0.1.7  
grpcio                 1.24.3 
h5py                   2.10.0 
Keras-Applications     1.0.8  
Keras-Preprocessing    1.1.0  
Markdown               3.1.1  
numpy                  1.17.3 
opt-einsum             3.1.0  
pip                    10.0.1 
protobuf               3.10.0 
setuptools             39.1.0 
six                    1.12.0 
tensorboard            2.0.0  
tensorflow             2.0.0  
tensorflow-estimator   2.0.1  
tensorflow-probability 0.8.0  
termcolor              1.1.0  
Werkzeug               0.16.0 
wheel                  0.33.6 
wrapt                  1.11.2 
```

I only had to install TensorFlow 2 (without GPU support) and TensorFlow Probability with the following `requirements.txt` file inside an empty virtual environment (which contained only the usual setuptools and wheel packages)

```
tensorflow==2.0.0
tensorflow-probability
```

The other dependencies you see above have been installed recursively. You should also try to use Python 3.7 (given that I am using it and I don't have Python 3.6 installed), but I don't think this is the problem. Furthermore, you should try to use Mac OS X (with the specific version above), but I also don't think this is the problem.

**Comment by nbro** [comment]
@ravikyram , @ymodak Apparently, if I set the parameter `experimental_run_tf_function` to `False` when calling `model.compile`, that is, `model.compile(..., experimental_run_tf_function=False)`, I do not get this error anymore.  There's a related issue https://github.com/tensorflow/addons/issues/428.

**What is `experimental_run_tf_function` exactly supposed to do?**

However, while training the model, even though the loss decreases throughout the epochs (from ~911194 to ~8), the accuracy does not increase but slightly oscillates even though it is always very small (it starts at 0.0688 and ends at like 0.1). I've tried this with both TensorFlow 2.0.0. and 2.1.0rc0. I've also tried with both the `sparse_categorical_crossentropy` and `categorical_crossentropy` loss functions (of course, in the latter case, I've converted the labels to binary with `tf.keras.utils.to_categorical`).

On the other hand, if I use the following custom loss function

```
def neg_log_likelihood_with_logits(y_true, y_pred):
    y_pred_dist = tfp.distributions.Categorical(logits=y_pred)
    return -tf.reduce_mean(y_pred_dist.log_prob(tf.argmax(y_true, axis=-1)))
```

The accuracy with the validation dataset (which is 0.1 of the training dataset) is more than 0.9 after the first epoch, but, rather than progressively increasing in the next epochs, it oscillates (even though it never goes under 0.9). Maybe this oscillation is due to the fact that I set the parameter `validation_split=0.1` of the [`fit`](https://keras.io/models/model/#fit) method to specify the fraction of the training dataset to be used for validation, but, according to [the documentation of the `fit` method](https://keras.io/models/model/#fit), the fraction of the training dataset used for validation seems to be selected before training, so, given that apparently that fraction is always the same, this should not be the cause of the oscillation of the accuracy, even considering that the forward pass of the model is stochastic, so, given the same input, the output might not always be the same. According to https://datascience.stackexchange.com/a/38956/10640, the fraction of the training dataset used for validation is selected before training, so it is fixed across epochs, so this should confirm the idea that this is not the cause of the oscillation of the accuracy.

Anyway, I thought that the `sparse_categorical_crossentropy` and `categorical_crossentropy` losses should compute something similar to the custom loss `neg_log_likelihood_with_logits`, but without using `tfp.distributions.Categorical`, but they probably use softmax. I suppose that these Keras' loss functions just call the corresponding TensorFlow ones.

**What is the difference between `sparse_categorical_crossentropy` (or `categorical_crossentropy`) and  `neg_log_likelihood_with_logits`, in terms of functionality or, more precisely, what are the possible causes of these different results (or accuracies)?**

For example, in the documentation of the `DenseFlipout` layer, you provide the following example

```
import tensorflow_probability as tfp

model = tf.keras.Sequential([
    tfp.layers.DenseFlipout(512, activation=tf.nn.relu),
    tfp.layers.DenseFlipout(10),
])

logits = model(features)
neg_log_likelihood = tf.nn.softmax_cross_entropy_with_logits(labels=labels, logits=logits)
kl = sum(model.losses)
loss = neg_log_likelihood + kl
train_op = tf.train.AdamOptimizer().minimize(loss)
```

which uses `softmax_cross_entropy_with_logits` to compute the negative log-likelihood part of the loss. However, the example of the Bayesian neural network https://github.com/tensorflow/probability/blob/master/tensorflow_probability/examples/bayesian_neural_network.py does something similar to the custom loss `neg_log_likelihood_with_logits`, that is, it uses TensorFlow Probability's `tfd.Categorical`.

**Comment by nbro** [comment]
I think that this issue is related to the parameter `kernel_divergence_fn` of `tfp.layers.Convolution2DFlipout`. In fact, if you set it to `None`or you create a custom function that returns the KL divergence, then this issue doesn't occur anymore even without the need for `experimental_run_tf_function=False`. 

As far as I understand, `experimental_run_tf_function=False` would go back to the previous way of TensorFlow of handling computation (i.e. using multiple paths). Honestly, I still don't get how and why this affects this particular issue with `tfp.layers.Convolution2DFlipout` (but e.g. not the other Bayesian layers).

**Comment by nbro** [comment]
This issue doesn't seem to occur anymore with the following versions

tf-nightly             2.2.0.dev20200422  
tfp-nightly            0.11.0.dev20200422

**Comment by ymodak** [comment]
Can this be closed since the error is not seen in tf-nightly version? Thanks!

**Comment by nbro** [comment]
@ymodak I wouldn't close this until the new stable version is released.

**Comment by ymodak** [comment]
TF 2.2 final version has released and this works successfully. Please give it a try. Thanks!
