### ISSUE TITLE
Tensorflow 2.0 error when used via pyinstaller build - ImportError: cannot import name 'pywrap_tensorflow' from 'tensorflow_core.python'

### ISSUE THREAD

**Issue by anilkdas** [tensorflow/tensorflow#33722]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): binary
- TensorFlow version: 2.0
- Python version: 3.7
- Installed using virtualenv? pip? conda?: pip
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Describe the problem**
This has happened after upgrade to Tensorflow 2.0 . 

On executing the EXE file generated by Pyinstaller for Tensorflow 2.0, we get the following error:

'ImportError: cannot import name 'pywrap_tensorflow' from 'tensorflow_core.python'

The scripts work okay in PyCharm or Jupyter. The same version of scripts when run under Tensorflow 1.x execute correctly

**Provide the exact sequence of commands / steps that you executed before running into the problem**
1.  upgraded tensorflow to 2.0
2. Adjusted python code to accommodate module dependence from Keras to tf.keras
3. Build exe --onefile via pyinstaller
4. on execution of exe get the following error 
"ImportError: cannot import name 'pywrap_tensorflow' from 'tensorflow_core.python' "

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by oanush** [comment]
@anilkdas ,
Can you please refer this [link](https://stackoverflow.com/questions/35953210/error-running-basic-tensorflow-example) of similar issue ?Thanks!

**Comment by oanush** [comment]
@anilkdas ,
Any update on the issue ?Thanks!

**Comment by evancasey** [comment]
There are a couple of solutions proposed [here](https://github.com/pyinstaller/pyinstaller/issues/4400#issuecomment-550905592)

**Comment by oanush** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Comment by prabs190** [comment]
i am getting below error. Can anyone please help me on this

import tensorflow as tf
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\a658371\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow\__init__.py", line 101, in <module>
    from tensorflow_core import *
  File "C:\Users\a658371\AppData\Roaming\Python\Python37\site-packages\tensorflow_core\__init__.py", line 28, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "C:\Users\a658371\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow\__init__.py", line 50, in __getattr__
    module = self._load()
  File "C:\Users\a658371\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow\__init__.py", line 44, in _load
    module = _importlib.import_module(self.__name__)
  File "C:\Users\a658371\AppData\Local\Continuum\anaconda3\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Users\a658371\AppData\Roaming\Python\Python37\site-packages\tensorflow_core\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
ImportError: cannot import name 'pywrap_tensorflow' from 'tensorflow_core.python' (C:\Users\a658371\AppData\Roaming\Python\Python37\site-packages\tensorflow_core\python\__init__.py)
