### ISSUE TITLE
`fit_generator` (tf.keras.utils.Sequence) is not supported for models compiled with tf.distribute.Strategy

### ISSUE THREAD

**Issue by olk** [tensorflow/tensorflow#33725]
**System information**
- OS Platform and Distribution: Arch Linux (Linux-5.3.7-arch1-1-ARCH-x86_64-with-arch)
- TensorFlow installed from (source or binary): binary
- TensorFlow version:  2.0.0
- Keras version: 2.2.4-tf
- Python version: 3.7.4
- GCC/Compiler version: 9.2.0
- CUDA/cuDNN version: cuda 10.1.243-1 / cudnn 7.6.4.38-1
- GPU model and memory: 2x GeForce GTX 1080 Ti 11GB

**Describe the current behavior**
- Model.fit_generator() invoked with generator dervied from tf.keras.utils.Sequence
- execution fails with NotImplementedError

```
strategy = tf.distribute.MirroredStrategy()
with strategy.scope():
         model = OCRNet.build(train_gen.output_size, img_w, img_h, max_text_len)
         adam = Adam(lr=lr, beta_1=0.9, beta_2=0.999, epsilon=1e-08)
         model.compile(loss={'ctc': lambda y_true, y_pred: y_pred}, optimizer=adam, metrics=['accuracy'])
history = model.fit_generator(
         generator=train_gen,
         epochs=epochs,
         validation_data=val_gen,
         use_multiprocessing=True,
         workers=6,
         callbacks=callbacks)
```

**Other info / logs**

> Traceback (most recent call last):
>   File "src/models/train.py", line 119, in <module>
>     main()
>   File "src/models/train.py", line 112, in main
>     fit(model, train_gen, val_gen, epochs, callbacks)
>   File "src/models/train.py", line 39, in fit
>     callbacks=callbacks)
>   File "/usr/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training.py", line 1277, in fit_generator
>     raise NotImplementedError('`fit_generator` is not supported for '
> NotImplementedError: `fit_generator` is not supported for models compiled with tf.distribute.Strategy.

**Comment by olk** [comment]
I replaced model.fit_generator() by model.fit() (fit_generator will be deprecated in next releases).
But I get a different error:

> Traceback (most recent call last):
>   File "src/models/train.py", line 116, in <module>
>     main()
>   File "src/models/train.py", line 109, in main
>     callbacks=callbacks)
>   File "/usr/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training.py", line 728, in fit
>     use_multiprocessing=use_multiprocessing)
>   File "/usr/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training_v2.py", line 224, in fit
>     distribution_strategy=strategy)
>   File "/usr/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training_v2.py", line 547, in _process_training_inputs
>     use_multiprocessing=use_multiprocessing)
>   File "/usr/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training_v2.py", line 606, in _process_inputs
>     use_multiprocessing=use_multiprocessing)
>   File "/usr/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/data_adapter.py", line 606, in __init__
>     nested_dtypes = nest.map_structure(lambda t: t.dtype, peek)
>   File "/usr/lib/python3.7/site-packages/tensorflow_core/python/util/nest.py", line 535, in map_structure
>     structure[0], [func(*x) for x in entries],
>   File "/usr/lib/python3.7/site-packages/tensorflow_core/python/util/nest.py", line 535, in <listcomp>
>     structure[0], [func(*x) for x in entries],
>   File "/usr/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/data_adapter.py", line 606, in <lambda>
>     nested_dtypes = nest.map_structure(lambda t: t.dtype, peek)
> AttributeError: 'str' object has no attribute 'dtype

**Comment by olk** [comment]
removed string type from generator output - code works now

**Comment by 1044197988** [comment]
fit_generator将在以后的版本中弃用,不会吧，这个API我认为很好用的
这个错误要怎么解决呢？如果数据很大，不能一次性存到内存中
使用tf.data来实现吗?

**Comment by Santosh-Gupta** [comment]
> I replaced model.fit_generator() by model.fit() (fit_generator will be deprecated in next releases).

Where did you hear this?

**Comment by 1044197988** [comment]
我也认为fit_generator will be deprecated in the future
现在fit也支持生成器，多GPU的话，直接用fit就可以
