### ISSUE TITLE
Multi-GPU for LSTM

### ISSUE THREAD

**Issue by yajiemiao** [tensorflow/tensorflow#3372]
I am experimenting with multi-gpu feedforwarding for LSTM models, by feeding two batches of sequences through a LSTM model. Here are two cases I am testing:

**Single-GPU**: simply pass the two batches sequentially on 1 GPU
**Two-GPU**: 2 parallel GPUs where each GPU takes care of one batch. **My code is in the attached file** (.txt --> .py).

However, instead of being 2X faster, the two-GPU case runs even slightly slower than the single-GPU case. It seems that even if I am initiating 2 GPU threads, the 2 batches are processed still sequentially, rather than in a parallel manner. 

Does anyone see anything wrong with my code, or give any insight on how to do debugging? Your help would be highly appreciated.

[lstm_multi_gpu.txt](https://github.com/tensorflow/tensorflow/files/370021/lstm_multi_gpu.txt)

**Comment by concretevitamin** [comment]
Several issues I see:

1. `log_device_placement=False,allow_soft_placement=True` are passed to your Session ctor.  You should flip both, so as to verify that indeed two GPUs are used, but not just one.

2. For benchmark purposes, you should not just report one iter.  Best practices are to warm up for a few iters, then start timing (the trial runs), and report avg with std.

**Comment by aselle** [comment]
Automatically closing due to lack of recent activity. Please reopen when further information becomes available.
