### ISSUE TITLE
Training loop freezes and then stops when try to run Cycle-GAN on multi-GPU system on Google GCP using 'tf.distribute.MirroredStrategy()' .

### ISSUE THREAD

**Issue by gaurav-singh1998** [tensorflow/tensorflow#33723]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:NaN
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below): 2.0.0
- Python version:3.6
- Bazel version (if compiling from source): NaN
- GCC/Compiler version (if compiling from source): NaN
- CUDA/cuDNN version: 10
- GPU model and memory: 4 Nvidia Tesla K80's of 11GB each

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
Training loop stops after few steps in the first epoch itself.
**Describe the expected behavior**
Training loop should run smoothly.

**Other info / logs**
The link below contains a zip file in which the python scripts which I used to train this model on Multi GPU using 'tf.distribute.MirroredStrategy()' is stored.
[The python scripts can be found here](https://drive.google.com/file/d/17TBNfs1h0Lnolq5ZaomqE9pTzdoGjEWb/view?usp=sharing)

> Running 'download.py' will download the dataset that I used.

> 'model.py' contains code for the architecture of the generator and the discriminator that  I used for training this Cycle-GAN

> 'utils.py' contains code that I used for preprocessing the images 

> 'main.py' contains the code in which I used 'tf.distribute.MirroredStrategy()' for multi-GPU training but it stops after few steps in the first epoch.

**Comment by robieta** [comment]
Please provide a minimal and hermetic repro of the issue, rather than the full model code.

Nothe that you can also use the virtual device configuration described in https://www.tensorflow.org/api_docs/python/tf/config/experimental/set_virtual_device_configuration to reproduce multi-device mirrored strategy (in this case 2 CPU) in colab.

**Comment by crccw** [comment]
Hello gaurav-singh1998, have you verified that it works without tf.distribute.MirroredStrategy()?

**Comment by crccw** [comment]
closing due to inactiveness, please re-open if it's still an issue : )
