### ISSUE TITLE
RuntimeError:Data adapters should be mutually exclusive

### ISSUE THREAD

**Issue by 408881465** [tensorflow/tensorflow#33734]
Today I run [transfer_learning_with_hub.ipynb](https://colab.research.google.com/github/tensorflow/docs/blob/master/site/en/tutorials/images/transfer_learning_with_hub.ipynb) **on Google Colab**, It show errors info below.
**But yesterday I run this jupyter nootbook successfully.**

It seems that  using the latest TensorFlow version **2.1.0-dev20191025** cause the problem

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):**Linux 5c32dbcf8bfd 4.14.137+ #1 SMP Thu Aug 8 02:47:02 PDT 2019 x86_64 x86_64 x86_64 GNU/Linux**
- TensorFlow version (use command below):**'2.1.0-dev20191025'**
- Python version:**Python 3.6.8**
- GCC/Compiler version (if compiling from source): **[GCC 8.3.0] on linux**
- CUDA/cuDNN version:
- GPU model and memory:12.72GB

**Describe the current behavior**
errors is below

**Describe the expected behavior**
Yesterday, I run this jupyter nootbook successfully.

**Code to reproduce the issue**
when runnig codes below it show errors
```
steps_per_epoch = np.ceil(image_data.samples/image_data.batch_size)
batch_stats_callback = CollectBatchStats()
history = model.fit_generator(image_data, epochs=2,
                              steps_per_epoch=steps_per_epoch,
                              callbacks = [batch_stats_callback])
```

**Other info / logs**
```
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-52-dd38f4e8ca03> in <module>()
      5 history = model.fit_generator(image_data, epochs=2,
      6                               steps_per_epoch=steps_per_epoch,
----> 7                               callbacks = [batch_stats_callback])

5 frames
/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/engine/data_adapter.py in select_data_adapter(x, y)
    979         "handling inputs. Found multiple adapters {} to handle "
    980         "input: {}, {}".format(
--> 981             adapter_cls, _type_name(x), _type_name(y)))
    982   return adapter_cls[0]
    983 

RuntimeError: Data adapters should be mutually exclusive for handling inputs. Found multiple adapters [<class 'tensorflow.python.keras.engine.data_adapter.GeneratorDataAdapter'>, <class 'tensorflow.python.keras.engine.data_adapter.KerasSequenceAdapter'>] to handle input: <class 'keras_preprocessing.image.directory_iterator.DirectoryIterator'>, <class 'NoneType'>
```

**Comment by 408881465** [comment]
After downgrade tensorflow  tf-hub-nightly and  tf-nightly It works.

**Comment by ymodak** [comment]
Closing this issue since its resolved. Thanks!
