### ISSUE TITLE
Large bias values for Inception V4 TFLite model

### ISSUE THREAD

**Issue by smohan10** [tensorflow/tensorflow#33735]
This template is for miscellaneous issues not covered by the other issue categories.

For questions on how to work with TensorFlow, or support for problems that are not verified bugs in TensorFlow, please go to [StackOverflow](https://stackoverflow.com/questions/tagged/tensorflow).

If you are reporting a vulnerability, please use the [dedicated reporting process](https://github.com/tensorflow/tensorflow/blob/master/SECURITY.md).

For high-level discussions about TensorFlow, please post to discuss@tensorflow.org, for questions about the development or internal workings of TensorFlow, or if you would like to know how to contribute to TensorFlow, please post to developers@tensorflow.org.

Model: Inception V4
Dataset: Dog 120. 
Calibration images: 10 images of resolution 299x299

Steps to convert to TFLite model:
- converter = tf.lite.TFLiteConverter.from_frozen_graph(model_file,  [input_node], [output_node])
- converter.optimizations = [tf.lite.Optimize.DEFAULT]
- converter.representative_dataset = representative_dataset_gen
- with open(tflite_model_file, "wb") as w:
	w.write(converter.convert())

I see the bias values of most of the convolution having values such as "-2147483647". Below is an example. 

![image](https://user-images.githubusercontent.com/5778892/67609304-e137aa00-f740-11e9-86a6-ddb9ff382f39.png)

The corresponding frozen protobuf value is:

![image](https://user-images.githubusercontent.com/5778892/67609341-147a3900-f741-11e9-89b0-2a817c476dde.png)

Can someone help me understand why the quantization is happening in such a way for the INT32 biases ?

**Comment by smohan10** [comment]
Hi, 

Any update on this thread?

**Comment by jdduke** [comment]
Apologies for the delayed response, reassigning to some folks who can help.

**Comment by liyunlu0618** [comment]
Thanks for flagging this issue! We also found this ourselves and implemented a scale adjustment to avoid overflow when quantizing biases. Can you try again with the nightly build and let us know how it goes? Thanks!

**Comment by smohan10** [comment]
Thank you so much for your reply. I will try the nightly build version soon and let you know.

**Comment by raziel** [comment]
Hi @smohan10 Can you please update the bug with your results?
Thanks

**Comment by liyunlu0618** [comment]
We've verified inception v4 works fine with post-training quantization. 
Top 1 accuracy, float 80.24%, and quantized 80.21%.
Feel free to reopen if you run into other issues.
