### ISSUE TITLE
Hyperlink in codelab redirects to a 404 page

### ISSUE THREAD

**Issue by AbhishekS-2099** [tensorflow/tensorflow#33743]
#32417  URL(s) with the issue:

https://codelabs.developers.google.com/codelabs/tensorflow-for-poets/?utm_campaign=chrome_series_machinelearning_063016&utm_source=gdev&utm_medium=yt-desc#1

## Description of issue (what needs changing):
Update the link to redirect to the latest version of Tensorflow

### Clear description

Always better to redirect to a page that helps out a user, rather than keep links to 404 pages.

### Correct links

Is the link to the source code correct?

### Raises listed and defined

Server raises a 404 Page, which is an error.

### Usage example

It isn't exactly a use case. Just a QoL change.

### Request visuals, if applicable

Are there currently visuals? If not, will it clarify the content?
<img width="1440" alt="Screenshot 2019-10-26 at 4 36 23 PM" src="https://user-images.githubusercontent.com/41414202/67618592-17435f80-f80f-11e9-9cb1-2b4d9a44ab34.png">
<img width="1440" alt="Screenshot 2019-10-26 at 4 36 31 PM" src="https://user-images.githubusercontent.com/41414202/67618594-1a3e5000-f80f-11e9-92f4-6716b871496f.png">

### Submit a pull request?
 Yes. I love contributing in small ways, since I'm still a rather newbie developer. Errors even small should be dealt with I presume?

**Comment by AbhishekS-2099** [comment]
Could I receive some help regarding the repo? Please ping me at abhishek.sankar.in@ieee.org

Thanks!

**Comment by EvilTrtl** [comment]
As of the Tensorflow 2.0 release, that Codelab was deprecated. A 2.0 version of that colab can be found at [https://colab.research.google.com/github/tensorflow/examples/blob/master/community/en/flowers_tf_lite.ipynb](url)
