### ISSUE TITLE
Tensor zero_padding2d_1_input:0, specified in either feed_devices or fetch_devices was not found in the Graph

### ISSUE THREAD

**Issue by loretoparisi** [tensorflow/tensorflow#33744]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
_custom_
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
```
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
```
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
none
- TensorFlow installed from (source or binary):
_binary_
- TensorFlow version (use command below):
`v1.14.0-rc1-22-gaf24dc9 1.14.0`
- Python version:
Python 3.7.4
- Bazel version (if compiling from source):
_none_
- GCC/Compiler version (if compiling from source):
_none_
- CUDA/cuDNN version:
_none_
- GPU model and memory:
CPU model

**Describe the current behavior**
This issue happens when running the Tensorflow model inference in a Tornado server started as a Thread.
```python
class WebServer(threading.Thread):
    def run(self):
        application.listen(8888)
        #asyncio.set_event_loop(asyncio.new_event_loop())
        asyncio.set_event_loop(AnyThreadEventLoopPolicy())
        tornado.ioloop.IOLoop.instance().start()
WebServer.start()
```

**Describe the expected behavior**

**Code to reproduce the issue**
Inference running without any issue. The issue does not occur when it starts running on the main thread instead:

```python
application.listen(8888)
application.listen(8888)
tornado.ioloop.IOLoop.instance().start()
```

**Other info / logs**
This error happens on both Tensorflow models I run, so I assume it's a threading problem when running the Graph in a thread that it is not the main thread.

The only error logging I get is
` Tensor zero_padding2d_1_input:0, specified in either feed_devices or fetch_devices was not found in the Graph`

**Comment by loretoparisi** [comment]
**[NOTE]**
According to [here](https://stackoverflow.com/questions/54652536/keras-tensorflow-backend-error-tensor-input-10-specified-in-either-feed-de), I have tried to run `model.predict` in my session so I did

```python
    with session.as_default():
        with session.graph.as_default():
            labels = np.round(model.predict(X)[0])
        
            prediction = []

            for i in range(0, len(labels)):
                if labels[i] == 1:
                    prediction.append(labels_group[i])

            return prediction
```

but now getting a 

```
Error while reading resource variable block4_conv2/kernel from Container: localhost. This could mean that the variable was uninitialized. Not found: Container localhost does not exist. (Could not find resource: localhost/block4_conv2/kernel)
	 [[{{node sequential_1_3/block4_conv2/convolution/ReadVariableOp}}]]
```

**Comment by loretoparisi** [comment]
**[NOTE]**
I was able to solve this issue creating a new `global session` and then setting it to keras before loading the model as stated in https://github.com/tensorflow/tensorflow/issues/28287#issuecomment-495005162:

```python
   def load_tensorflow_shared_session(self):
        """ Load a Tensorflow/Keras shared session """
        # LP: create a config by gpu cpu backend
        if os.getenv('HAS_GPU', '0') == '1':
            config = tf.ConfigProto(
                device_count={'GPU': 1},
                intra_op_parallelism_threads=1,
                allow_soft_placement=True
            )
            config.gpu_options.allow_growth = True
            config.gpu_options.per_process_gpu_memory_fraction = 0.6
        else:
            config = tf.ConfigProto(
                intra_op_parallelism_threads=1,
                allow_soft_placement=True
            )
        # LP: create session by config
        self.tf_session = tf.Session(config=config)

        return self.tf_session
```

and then passing this shared session to all TF /Keras models:

```python
def load__model(MODEL_PATH, session):
    '''
        Load the model
    '''

    # IMPORTANT: models have to be loaded AFTER SETTING THE SESSION for keras! 
    # Otherwise, their weights will be unavailable in the threads after the session there has been set
    set_session(session)
    model = keras.models.load_model(MODEL_PATH)
    model._make_predict_function()
```

Instead of using `global session` object I'm using a singleton object that retains `this.tf_session`, by the way it works in both ways.

**Comment by jvishnuvardhan** [comment]
@loretoparisi Is this still an issue or was it resolved? Please close the issue if it was resolved already. Thanks!

**Comment by loretoparisi** [comment]
@jvishnuvardhan please let me check, thank you.

**Comment by jvishnuvardhan** [comment]
@loretoparisi When you check, can you also check with latest versions in TF1.x and TF2.x? Thanks!

**Comment by loretoparisi** [comment]
So for sure we were talking about of version TF 1.x.

**Comment by jvishnuvardhan** [comment]
@loretoparisi Can you please check with the latest versions in TF1.15.3 and let us know whether the issue persists? Thanks!

Please feel free to close the issue if the issue was resolved for you. Thanks!

**Comment by loretoparisi** [comment]
@jvishnuvardhan ok I will confirm.

**Comment by jvishnuvardhan** [comment]
@loretoparisi Are you confirming that this is an issue with `TF1.15.3` or your are confirming that this is already resolved for you? Thanks!

**Comment by loretoparisi** [comment]
@jvishnuvardhan I confirm that this has been resolved. I have investigated the solution. The problem was related to a wrong handling of the TF session through different models loaded on the same server (multi-processing application server so with the same shared session). The solution was a common shared session, passed through all loaded models.
