### ISSUE TITLE
Android app compilation fails: fatal error: gif_lib_private.h: No such file or directory

### ISSUE THREAD

**Issue by Arn-O** [tensorflow/tensorflow#3374]
Hi.

I'm unable to compile the Android app. Here is the error message:

```
ERROR: /home/arnaud/.cache/bazel/_bazel_arnaud/5d461d587a2aa81b3eca305842d75a99/external/gif_archive/BUILD:14:1: C++ compilation of rule '@gif_archive//:gif' failed: namespace-sandbox failed: error executing command /home/arnaud/.cache/bazel/_bazel_arnaud/5d461d587a2aa81b3eca305842d75a99/execroot/tensorflow/_bin/namespace-sandbox ... (remaining 46 argument(s) skipped).
external/gif_archive/giflib-5.1.4/lib/quantize.c:17:29: fatal error: gif_lib_private.h: No such file or directory
compilation terminated.
Target //tensorflow/examples/android:tensorflow_demo failed to build
Use --verbose_failures to see the command lines of failed build steps.
```

### Environment info
Operating System: Ubuntu 16.04

Installed version of CUDA and cuDNN: N/A
(please attach the output of `ls -l /path/to/cuda/lib/libcud*`):

If installed from binary pip package, provide:

1. Which pip package you installed.
2. The output from `python -c "import tensorflow; print(tensorflow.__version__)"`.

If installed from sources, provide the commit hash: https://github.com/tensorflow/tensorflow/commit/a3f61c1d5c76339e6c9655dac426bb3822659772

### Steps to reproduce
1. bazel build //tensorflow/examples/android:tensorflow_demo
2.
3.

### What have you tried?
1. install the giflib from Ubuntu, but I understand that bazel downloads during the build process

### Logs or other output that would be helpful

With max verbosity:

```
ERROR: /home/arnaud/.cache/bazel/_bazel_arnaud/5d461d587a2aa81b3eca305842d75a99/external/gif_archive/BUILD:14:1: C++ compilation of rule '@gif_archive//:gif' failed: namespace-sandbox failed: error executing command 
  (cd /home/arnaud/.cache/bazel/_bazel_arnaud/5d461d587a2aa81b3eca305842d75a99/execroot/tensorflow && \
  exec env - \
    PATH=/home/arnaud/Documents/Python/anaconda2/bin:/home/arnaud/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/arnaud/.rvm/bin:/home/arnaud/.rvm/bin:/home/arnaud/Documents/Android/android-studio/bin \
  /home/arnaud/.cache/bazel/_bazel_arnaud/5d461d587a2aa81b3eca305842d75a99/execroot/tensorflow/_bin/namespace-sandbox @/home/arnaud/.cache/bazel/_bazel_arnaud/5d461d587a2aa81b3eca305842d75a99/execroot/tensorflow/bazel-sandbox/aeac231e-239e-4110-a556-7f20a424a56a-197.params -- /usr/bin/gcc -U_FORTIFY_SOURCE '-D_FORTIFY_SOURCE=1' -fstack-protector -Wall -Wl,-z,-relro,-z,now -B/usr/bin -B/usr/bin -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 -DNDEBUG -ffunction-sections -fdata-sections -g0 -DHAVE_CONFIG_H -iquote external/gif_archive -iquote bazel-out/host/genfiles/external/gif_archive -iquote external/bazel_tools -iquote bazel-out/host/genfiles/external/bazel_tools -isystem external/gif_archive/giflib-5.1.4/lib -isystem bazel-out/host/genfiles/external/gif_archive/giflib-5.1.4/lib -isystem external/bazel_tools/tools/cpp/gcc3 -fno-canonical-system-headers -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -MD -MF bazel-out/host/bin/external/gif_archive/_objs/gif/external/gif_archive/giflib-5.1.4/lib/gif_err.d -c external/gif_archive/giflib-5.1.4/lib/gif_err.c -o bazel-out/host/bin/external/gif_archive/_objs/gif/external/gif_archive/giflib-5.1.4/lib/gif_err.o).
external/gif_archive/giflib-5.1.4/lib/gif_err.c:10:29: fatal error: gif_lib_private.h: No such file or directory
compilation terminated.
Target //tensorflow/examples/android:tensorflow_demo failed to build
```

**Comment by andrewharp** [comment]
I'm not certain why this is happening yet, but running ./configure seems to make it go away for me.

**Comment by andrewharp** [comment]
There is a dependency chain between //tensorflow/core:android_tensorflow_lib_lite and @gif_archive//:gif:

> $ bazel query "somepath(tensorflow/core:android_tensorflow_lib_lite, @gif_archive//:gif)"
> //tensorflow/core:android_tensorflow_lib_lite
> //tensorflow/core:android_srcs
> //tensorflow/core:proto_text_srcs_all
> //tensorflow/tools/proto_text:gen_proto_text_functions
> //tensorflow/core:lib
> //tensorflow/core:lib_internal
> //tensorflow/core/platform/default/build_config:platformlib
> @gif_archive//:gif

@martinwicke @raingo I think this may be from https://github.com/tensorflow/tensorflow/pull/3264

As gif support is unnecessary for the Android build, is there any easy way we can make the build proceed despite gif_archive not having been configured?

**Comment by martinwicke** [comment]
platformlib also depends on png and jpeg -- are those also unnecessary in android? If so, we could split all image support out into a separate target, but it would be a fair amount of work to separate core:lib_internal into two (or more) targets.

**Comment by andrewharp** [comment]
All that the Android build needs from platformlib is the proto_text_srcs_all output which depends on platformlib. It doesn't use the actual platformlib binary for compilation -- all srcs are compiled from scratch using the resulting android_srcs filegroup.

So if somehow we could reduce the complexity of generating proto_text_srcs_all, that would reduce Android issues going forward.

**Comment by martinwicke** [comment]
@keveman can the protos be built without any of the other lib stuff? It seems this quickly turning into a requirement for mobile.

**Comment by keveman** [comment]
`//tensorflow/core:proto_text_srcs_all` is not part the proto library, but something that @cwhipkey wrote. I doubt it can be built independent of `core:lib`, but maybe @cwhipkey can answer it better.

**Comment by andrewharp** [comment]
It's generated by the cc_binary tool gen_proto_text_functions, which only uses the following basic TF includes:
#include "third_party/tensorflow/core/lib/strings/str_util.h"
#include "third_party/tensorflow/core/lib/strings/strcat.h"
#include "third_party/tensorflow/core/platform/macros.h"
#include "third_party/tensorflow/core/platform/types.h"
#include "third_party/tensorflow/core/platform/init_main.h"
#include "third_party/tensorflow/core/platform/logging.h"
#include "third_party/tensorflow/core/platform/protobuf.h"

The entirety of platformlib apart from protos_cc should not be required for this binary, so maybe there is some way to refactor the targets involved.

**Comment by cwhipkey** [comment]
I think it's possible to get it down to just the dependency on protobuf.h
(I have a change somewhere where I did that, but it was ultimately not
needed).  Would that help?  The protobuf.h code would still need to be made
available somehow.

**Comment by andrewharp** [comment]
@cwhipkey Yes, that was exactly what was needed. Starting from that CL I was able to get something building that fixes this issue by creating a minimal dependency tree for gen_proto_text_functions.

**Comment by Arn-O** [comment]
I can confirm that the ``./configure`` works for me. So we can close this issue, or keep it open for reference, if someone wants to remove the unnecessary dependencies.

**Comment by andrewharp** [comment]
I've submitted a fix internally; it should show up externally in the next push -- I'll close the issue when it does.

**Comment by andrewharp** [comment]
Separate compilation path added for proto tool in https://github.com/tensorflow/tensorflow/commit/4e9a42b7d3764928bdb6625c26f2dbd8f0415834, so Android build should be simpler/faster now.
