### ISSUE TITLE
Copy one graph to another

### ISSUE THREAD

**Issue by anshkumar** [tensorflow/tensorflow#33741]
I want to copy a loaded graph to another one. Here, is what I'm trying to do

```
import tensorflow as tf
import numpy as np
import cv2

input_names = ['image_tensor']
pb_fname1 = "/Users/vedanshu/frozen_graph/ssd_tomato_l1_frozen_graph.pb"

def get_frozen_graph(graph_file):
    """Read Frozen Graph file from disk."""
    with tf.gfile.FastGFile(graph_file, "rb") as f:
        graph_def = tf.GraphDef()
        graph_def.ParseFromString(f.read())
    return graph_def

trt_graph1 = get_frozen_graph(pb_fname1)

detection_graph1 = tf.Graph()
with detection_graph1.as_default():
    tf.import_graph_def(trt_graph1, name='')
    tf_sess1 = tf.Session(graph=detection_graph1)

tf_input1 = tf_sess1.graph.get_tensor_by_name(input_names[0] + ':0')
tf_scores1 = tf_sess1.graph.get_tensor_by_name('detection_scores:0')
tf_boxes1 = tf_sess1.graph.get_tensor_by_name('detection_boxes:0')
tf_classes1 = tf_sess1.graph.get_tensor_by_name('detection_classes:0')
tf_num_detections1 = tf_sess1.graph.get_tensor_by_name('num_detections:0')
```

Now I want to copy `tf_input1`, `tf_scores1`, `tf_boxes1`, `tf_num_detections1` to another graph. Currently I'm trying to use `copy_op_to_graph` (depricated) as follows:

```
import sys

detection_graph2 = tf.Graph()

namespace = "Ved"
copied_variables = []
sys.setrecursionlimit(10000000)

tf_num_detections1_copy = tf.contrib.copy_graph.copy_op_to_graph(tf_num_detections1, detection_graph2,copied_variables, namespace)
```

But the python kernel is getting killed without any error. 

System informations:
OS: Mac OS 10.13.6
Tf veriosn: 1.13.1
RAM: 8GB

**Comment by oanush** [comment]
@anshkumar ,
Can you please share `ssd_tomato_l1_frozen_graph.pb` so that we can try replicating the issue ?Thanks!

**Comment by anshkumar** [comment]
@oanush Here is the [link](https://drive.google.com/open?id=1JC66YZEsdjtuGTF6ONJEfNibhJvSMvj5) to the model.

**Comment by oanush** [comment]
Issue replicating for the given code for TF version-1.13 also for 1.15. Kindly find the [gist](https://colab.sandbox.google.com/gist/oanush/dd9fead0efb88c6947e2540896d6380c/untitled25.ipynb) of the colab.Thanks!

**Comment by jvishnuvardhan** [comment]
This is not Build/Installation or Bug/Performance issue. Please post this kind of support questions at [Stackoverflow](https://stackoverflow.com/questions/tagged/tensorflow). There is a big community to support and learn from your questions. GitHub is mainly for addressing bugs in installation and performance. Thanks
