### ISSUE TITLE
Using tf.contrib.framework.nest functions in TF2.0

### ISSUE THREAD

**Issue by aravic** [tensorflow/tensorflow#33748]
The tf.contrib.framework.nest module seems to have been moved to tf.nest after contrib has been deprecated in TF2.0.

However, not all the functions have been exported.
tf.contrib.framework.nest (https://www.tensorflow.org/versions/r1.15/api_docs/python/tf/contrib/framework/nest) has the following functions:
assert_same_structure(...)
assert_shallow_structure(..)
flatten(...)
flatten_dict_items(...)
flatten_up_to(...)
flatten_with_joined_string_paths(...)
flatten_with_tuple_paths(...)
flatten_with_tuple_paths_up_to(...)
get_traverse_shallow_structure(...)
is_nested(...)
is_sequence(...)
is_sequence_or_composite(...)
map_structure(...)
map_structure_up_to(...)
map_structure_with_paths(...)
map_structure_with_tuple_paths(...)
map_structure_with_tuple_paths_up_to(...)
pack_sequence_as(...)
yield_flat_paths(...)

where tf.nest (https://www.tensorflow.org/api_docs/python/tf/nest/map_structure) only has the following:
assert_same_structure(...)
flatten(...)
is_nested(...)
map_structure(...)
pack_sequence_as(...)

This is limiting to our application since we depend on specifying a flat structure to limit the nesting of the functions.
More specifically, we would like to use the *_up_to variants and the *_with_paths variants which seems to have been removed in tf.nest

Is there a way to use the previous API (the contrib one) for these functions in TF2.0

**Comment by rajathkmp** [comment]
+1

**Comment by superbobry** [comment]
Hi @aravic, we have recently released a subset of tf.contrib.framework.nest functions as a separate [library](http://pypi.org/project/dm-tree). It does not have exactly the same API as nest but it is fairly close, and most of the functions [are there](http://tree.readthedocs.io).

**Comment by aravic** [comment]
This is great. Thank you!

**Comment by superbobry** [comment]
Feel free to close the issue and open any new ones on the tree [issue tracker](https://github.com/deepmind/tree/issues).
