### ISSUE TITLE
Docs do not link to source

### ISSUE THREAD

**Issue by janosh** [tensorflow/tensorflow#33756]
One really useful feature in the sklearn docs is that each and every item has a link back to its source on GitHub. For example, see [RandomForestRegressor](https://scikit-learn.org/stable/modules/generated/sklearn.ensemble.RandomForestRegressor.html):

> class sklearn.ensemble.RandomForestRegressor(n_estimators=’warn’, criterion=’mse’, max_depth=None, min_samples_split=2, min_samples_leaf=1, min_weight_fraction_leaf=0.0, max_features=’auto’, max_leaf_nodes=None, min_impurity_decrease=0.0, min_impurity_split=None, bootstrap=True, oob_score=False, n_jobs=None, random_state=None, verbose=0, warm_start=False)&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;--> **[[source]](https://github.com/scikit-learn/scikit-learn/blob/1495f6924/sklearn/ensemble/forest.py#L1046)** <--

Would be nice if the TF docs could do the same.

**Comment by yashk2810** [comment]
Every TF API is now doing that. There is a big Github button at the top :)

https://www.tensorflow.org/api_docs/python/tf/concat

**Comment by janosh** [comment]
I noticed. Thanks a lot! 👍
