### ISSUE TITLE
Inclusion of a model re-training example

### ISSUE THREAD

**Issue by sayakpaul** [tensorflow/tensorflow#33757]
## URL(s) with the issue: [https://www.tensorflow.org/tutorials/keras/save_and_load](https://www.tensorflow.org/tutorials/keras/save_and_load)

Please provide a link to the documentation entry, for example:
https://www.tensorflow.org/tutorials/keras/save_and_load

## Description of issue (what needs changing):

Since model re-training is quite vital in both applied and research-based environments, I think it would be great to include an example on the same in this tutorial. 

### Clear description

The tutorial shows how to save and load models using various options. It does mention that using the model checkpoints it is possible to train the model from the point it was left off. However, currently, there is no section in the tutorial that shows how to do that in the correct way. 

For example, why should someone use this method? How is it useful?

There are several instances where a model may have to be retrained:
- There is new data and the model needs to re-trained on that
- If we are on local machines and if there is a power failure or bottlenecks that cause the training process to stop, we can always load up the latest checkpoints and re-train the models from there.

**Comment by nikitamaia** [comment]
Hi @sayakpaul, late response here, but does the[ Save checkpoints during training](https://www.tensorflow.org/tutorials/keras/save_and_load#save_checkpoints_during_training) section of the guide provide adequate information?
