### ISSUE TITLE
Better (simpler!) model checkpointing

### ISSUE THREAD

**Issue by netw0rkf10w** [tensorflow/tensorflow#33763]
**System information**
- TensorFlow version (you are using): 2.0.0
- Are you willing to contribute it (Yes/No): Yes

**Describe the feature and the current behavior/state.**
The current `tf.train.Checkpoint` is really a bit too complicated and not easy to use. Suppose that I want to save **the best model** (that has the best validation accuracy) during my **custom training loop**, and that I want to save **only the best model because I don't want to waste disk space**. My common sense tells me that this is so simple, just like in all other libraries:

```
if best_acc < epoch_acc:
    best_acc = epoch_acc
    checkpoint.save(os.path.join(checkpoint_dir, 'best'))
```

Results after 3 epochs:
```
best-1.index
best-1.data-00001-of-00002
best-1.data-00000-of-00002
best-2.index
best-2.data-00001-of-00002
best-2.data-00000-of-00002
best-3.index
best-3.data-00001-of-00002
best-3.data-00000-of-00002
```
Oops... My disk does not like this! And there's no option to turn off the counter and choose the exact file names that I want!

Same problem for **saving only the last checkpoint**. You would tell me that one can use `tf.train.CheckpointManager` for this task (by setting `max_to_keep = 1`), but, **a checkpoint object and then a checkpoint manager object to manage checkpoints, seriously?** Yet another additional layer of complexity! (Not to say that `CheckpointManager` cannot deal with the best model saving described above).

I think one of the major limitations of TensorFlow was complexity, really. In TensorFlow 2 this has been significantly reduced, but I believe we can do more.

It would be best to give the users the simplest option to `save(filepath)` and `restore(filepath)` in a **single file** (instead of *.index plus a bunch of data files), with whatever `filepath` they want. Just like in any other libraries such as PyTorch or Keras! (Keras's usage cannot be applied here because the model may not be compiled in a custom training loop). 

Finally: my apologies if such a solution already exists and I am not aware of that because of my lack of knowledge! (I have wrestled with `tf.train.Checkpoint` over the last days, and have checked the official [guide](https://www.tensorflow.org/guide) and [tutorials](https://www.tensorflow.org/tutorials) but could not find anything like that.)

I am just a TF beginner but will try to contribute, if you are open to changes. Thanks.

**Will this change the current api? How?**
I guess. I don't know how exactly, though.

**Who will benefit with this feature?**
Every user who wants to manually save checkpoints.

**Comment by netw0rkf10w** [comment]
FYI this is a hack that I did to achieve what I want, which may be useful to others:

```
class CheckpointWrapper(object):
    def __init__(self, **kargs):
        self.checkpoint = tf.train.Checkpoint(**kargs)

    def save(self, prefix, counter=None):
        """
        NOTE: this wrapper assumes that no two checkpoints have the same prefix,
        therefore, this function will delete existing checkpoints with the
        same prefix before saving (here prefix acts like a file path).
        counter: save with this counter instead of the value in save_counter
        """
        save_dir = os.path.dirname(prefix)
        if not os.path.isdir(save_dir):
            os.makedirs(save_dir)

        # save to temporary files first, to avoid overwriting existing files too early
        random_string = '_' + str(random.randint(1e6, 1e7)) + '_'
        temp_prefix = prefix + random_string
        if counter is not None:
            stored_counter = self.checkpoint.save_counter
            self.checkpoint.save_counter.assign(counter - 1)
        self.checkpoint.save(temp_prefix)
        # restore the original counter (incremented by 1 as we have saved one)
        if counter is not None:
            self.checkpoint.save_counter.assign(stored_counter + 1)

        # success. "Overwrite" (well: delete) previous checkpoint with same prefix
        prfx = os.path.basename(prefix)
        # search and delete all files prefix-<integer>.index, prefix-<integer>.data-<integer>-of-<integer>
        pattern = re.compile(r"{}-\d+\.index|{}-\d+\.data-\d+-of-\d+".format(prfx, prfx))
        for fname in os.listdir(save_dir):
            if pattern.match(fname):
                os.remove(os.path.join(save_dir, fname))
        # rename the saved checkpoint
        for fname in os.listdir(save_dir):
            os.rename(os.path.join(save_dir, fname),
                      os.path.join(save_dir, fname.replace(random_string, '')))

    def restore(self, prefix):
        """
        restore from the last checkpoint with given prefix
        """
        save_dir = os.path.dirname(prefix)
        prfx = os.path.basename(prefix)
        pattern = re.compile(r"{}-\d+\.index".format(prfx))
        restore_prefix = None
        for fname in os.listdir(save_dir):
            if pattern.match(fname):
                restore_prefix = os.path.join(save_dir, os.path.splitext(fname)[0])
                break
        self.checkpoint.restore(restore_prefix)
        return restore_prefix
```

**Comment by jvishnuvardhan** [comment]
@netw0rkf10w I think your issue is similar to [this resource](https://github.com/tensorflow/tensorflow/issues/30695#issuecomment-511932452).
Please follow the resolution provided in that resource and let us know if you are looking for anything different. Thanks!

**Comment by netw0rkf10w** [comment]
Hi @jvishnuvardhan. Thanks for your reply. Unfortunately that resource doest not help because it is for Keras `.fit()` only (I believe). My issue is specifically for custom training loop with GradientTape.

I also mentioned this in the post:

> It would be best to give the users the simplest option to save(filepath) and restore(filepath) in a single file (instead of *.index plus a bunch of data files), with whatever filepath they want. Just like in any other libraries such as PyTorch or **Keras**! (**Keras's usage cannot be applied here because the model may not be compiled in a custom training loop**).

**Comment by allenlavoie** [comment]
You can use `tf.train.Checkpoint.write` if you want a no-frills API that just saves to a given prefix.

**Comment by netw0rkf10w** [comment]
@allenlavoie I obtained the following error when restoring a checkpoint in a distributed training:

```
File "/home/username/.env/python3/lib/python3.5/site-packages/tensorflow_core/python/eager/def_function.py", line 457, in __call__
    result = self._call(*args, **kwds)
  File "/home/username/.env/python3/lib/python3.5/site-packages/tensorflow_core/python/eager/def_function.py", line 520, in _call
    return self._stateless_fn(*args, **kwds)
  File "/home/username/.env/python3/lib/python3.5/site-packages/tensorflow_core/python/eager/function.py", line 1823, in __call__
    return graph_function._filtered_call(args, kwargs)  # pylint: disable=protected-access
  File "/home/username/.env/python3/lib/python3.5/site-packages/tensorflow_core/python/eager/function.py", line 1141, in _filtered_call
    self.captured_inputs)
  File "/home/username/.env/python3/lib/python3.5/site-packages/tensorflow_core/python/eager/function.py", line 1224, in _call_flat
    ctx, args, cancellation_manager=cancellation_manager)
  File "/home/username/.env/python3/lib/python3.5/site-packages/tensorflow_core/python/eager/function.py", line 511, in call
    ctx=ctx)
  File "/home/username/.env/python3/lib/python3.5/site-packages/tensorflow_core/python/eager/execute.py", line 67, in quick_execute
    six.raise_from(core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.InvalidArgumentError: Cannot place the graph because a reference or resource edge connects colocation groups with incompatible assigned devices: /job:localhost/replica:0/task:0/device:GPU:0 vs /job:localhost/replica:0/task:0/device:GPU:1. The edge src node is Func/while/body/_1/input/_2741 , and the dst node is while/body/_1/Adam/Adam/update/update_1/ResourceApplyAdam [Op:__inference_distributed_train_epoch_31342]
```

Should I create a new issue? Thanks.

**Comment by allenlavoie** [comment]
Probably the optimizer's slot variable creation has moved to where the primary variable is created rather than happening during apply_gradients. That shouldn't generally affect placement, but looks like it's breaking something in your code.

Anyway, it's definitely not this issue. Feel free to open another one.
