### ISSUE TITLE
Example of "audio recognition" trained in tf-1.15.0 isn't able to recognize sound "Yes" on SparkFun Edge development board.

### ISSUE THREAD

**Issue by huaxiaozhong1** [tensorflow/tensorflow#33778]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): no.
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04.
- TensorFlow installed from (source or binary):
Created a docker container from docker image: tensorflow/tensorflow:1.15.0-gpu-py3-jupyter.
Inside the container, got tensorflow source tree through the following steps:
```
mkdir tensorflow
cd tensorflow
git init
git remote add origin https://github.com/tensorflow/tensorflow.git
git ls-remote --tags origin | grep 1.15.0
38ea9bbfea423eb968fcc70bc454471277c9537c	refs/tags/v1.15.0
git pull origin refs/tags/v1.15.0
```
- TensorFlow version (use command below): v1.15.0.
- Python version: 3.6.8.
- Bazel version (if compiling from source): neither installed nor used. 
- GCC/Compiler version (if compiling from source): gcc version 7.4.0 (Ubuntu 7.4.0-1ubuntu1~18.04.1). 
- CUDA/cuDNN version:  compute capability: 5.2. 
- GPU model and memory: GeForce GTX 960. 

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

v1.15.0-rc3-22-g590d6ee 1.15.0

**Describe the current behavior**
Going through the following steps (for all the steps in details, please see **Code to reproduce the issue** ), SparkFun Edge board was be flashed successfully. But it wasn't able to recognize the sound “Yes” :-(

**Describe the expected behavior**
If flashing the board with [the binary tf model](tensorflow/tensorflow/lite/experimental/micro/examples/micro_speech/simple_features/tiny_conv_simple_features_model_data.cc) that tf source tree brings, the sound “Yes” was recognized perfectly.
Could you let us know the exact environment and procedure that your tiny_conv_simple_features_model_data.cc was generated in? 

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.
#### 1.2, 
```
python tensorflow/tensorflow/examples/speech_commands/train.py \
--model_architecture=tiny_conv --window_stride=20 --preprocess=micro \
--wanted_words="yes,no" --silence_percentage=25 --unknown_percentage=25 \
--quantize=1 --verbosity=INFO --how_many_training_steps="15000,3000" \
--learning_rate="0.001,0.0001" --summaries_dir=/tmp/retrain_logs \
--data_dir=/tmp/speech_dataset –train_dir=/tmp/speech_commands_train
```
The training reached ~90%  accuracy, see [191028.log](https://github.com/tensorflow/tensorflow/files/3778241/191028.log.tar.gz) as attached.

#### 1.3, 
```
python tensorflow/tensorflow/examples/speech_commands/freeze.py \
--model_architecture=tiny_conv --window_stride=20 --preprocess=micro \
--wanted_words="yes,no" --quantize=1 --output_file=/tmp/tiny_conv.pb \
--start_checkpoint=/tmp/speech_commands_train/tiny_conv.ckpt-18000
```
#### 1.4, 
```
toco \
--graph_def_file=/tmp/tiny_conv.pb --output_file=/tmp/tiny_conv.tflite \
--input_shapes=1,49,40,1 --input_arrays=Reshape_2 --output_arrays='labels_softmax' \
--inference_type=QUANTIZED_UINT8 --mean_values=0 --std_dev_values=9.8077
```
#### 1.5,   
```
xxd -i /tmp/tiny_conv.tflite > /tmp/tiny_conv_micro_features_model_data.cc
```
#### 1.6,
Modified the binary model file to [tiny_conv_micro_features_model_data.new.cc](https://github.com/tensorflow/tensorflow/files/3778266/tiny_conv_micro_features_model_data.new.cc.gz) as attached, put it into tensorflow/lite/experimental/micro/examples/micro_speech/micro_features
#### 2.1, 
```
make -f tensorflow/lite/experimental/micro/tools/make/Makefile TARGET=sparkfun_edge TAGS="CMSIS" micro_speech_bin
```
#### 2.2, 
```
cp tensorflow/lite/experimental/micro/tools/make/downloads/AmbiqSuite-Rel2.0.0/tools/apollo3_scripts/keys_info0.py \
tensorflow/lite/experimental/micro/tools/make/downloads/AmbiqSuite-Rel2.0.0/tools/apollo3_scripts/keys_info.py
```
#### 2.3,
```
python3 tensorflow/lite/experimental/micro/tools/make/downloads/AmbiqSuite-Rel2.0.0/tools/apollo3_scripts/create_cust_image_blob.py \
--bin tensorflow/lite/experimental/micro/tools/make/gen/sparkfun_edge_cortex-m4/bin/micro_speech.bin \
--load-address 0xC000 \
--magic-num 0xCB \
-o main_nonsecure_ota \
--version 0x0
```
#### 2.4, 
```
python3 tensorflow/lite/experimental/micro/tools/make/downloads/AmbiqSuite-Rel2.0.0/tools/apollo3_scripts/create_cust_wireupdate_blob.py \
--load-address 0x20000 \
--bin main_nonsecure_ota.bin \
-i 6 \
-o main_nonsecure_wire \
--options 0x1
```
#### 2.5,
Walked through [AI on a microcontroller with TensorFlow Lite and SparkFun Edge](https://codelabs.developers.google.com/codelabs/sparkfun-tensorflow/#0), flashed our program and bootloader into the board. 
Test it then. 

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by huaxiaozhong1** [comment]
### 3. More results that I have dug out until Oct 31, 2019. 
#### 3.1, 
As reported at 1.2, we got a model whose accuracy reached ~ 90%. But, after freezing, its “predictions” on many “Yes” sample wavs are always 33% (see
[191031v2.log](https://github.com/tensorflow/tensorflow/files/3797952/191031v2.log)).
#### 3.2, 
If I just ran [your example for Training](https://github.com/tensorflow/docs/blob/master/site/en/r1/tutorials/sequences/audio_recognition.md#training) by "copy/paste", the accuracy is < 10%! (see 
[191031v3.log](https://github.com/tensorflow/tensorflow/files/3797992/191031v3.log). (Could you let me know why?)
#### 3.3, 
Also on your guidance [Use your local machine](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/experimental/micro/examples/micro_speech#use-your-local-machine), you wrote: 
#### "You must currently use the TensorFlow Nightly pip package. This version is confirmed to work:"
```
tf-nightly-gpu==1.15.0.dev20190729
```
However, train.py still was failed when I ran the commands as below.  
```
pip3 list | grep tensorflow
tensorflow-estimator 1.15.1             
tensorflow-gpu       1.15.0
```
```
pip3 install tf-nightly-gpu==1.15.0.dev20190729
Collecting tf-nightly-gpu==1.15.0.dev20190729
  Using cached https://files.pythonhosted.org/packages/c6/ed/6cc1a8a764c046cd102ec58904c32eebaa1360efe858796c97645f63401e/tf_nightly_gpu-1.15.0.dev20190729-cp36-cp36m-manylinux1_x86_64.whl
......
Successfully installed tf-nightly-gpu-1.15.0.dev20190729
```
```
python tensorflow/tensorflow/examples/speech_commands/train.py \
> --model_architecture=tiny_conv --window_stride=20 --preprocess=micro \
> --wanted_words="yes,no" --silence_percentage=25 --unknown_percentage=25 \
> --quantize=1 --verbosity=INFO --how_many_training_steps="15000,3000" \
> --learning_rate="0.001,0.0001" --summaries_dir=/tmp/retrain_logs \
> --data_dir=/tmp/speech_dataset –train_dir=/tmp/speech_commands_train
Traceback (most recent call last):
  File "tensorflow/tensorflow/examples/speech_commands/train.py", line 81, in <module>
    import input_data
......
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/canned/dnn.py", line 23, in <module>
    from tensorflow.python.feature_column import dense_features
ImportError: cannot import name 'dense_features'
```
Could you let us know the environments that you confirmed the train.py could work with? And we would continue to work for you on this issue if you need.

**Comment by huaxiaozhong1** [comment]
The key problem of this issue is here -- 
The [doc of Simple Audio Recognition](https://github.com/tensorflow/docs/blob/master/site/en/r1/tutorials/sequences/audio_recognition.md#simple-audio-recognition) guides: 
"
To begin the training process, go to the TensorFlow source tree and run:
...
python tensorflow/examples/speech_commands/train.py
...
After a few hours of training (depending on your machine's speed) ... you should see an **accuracy** of **between 85% and 90%**.
"
But the **accuracy** that I got with my reproduction is **33% or < 10%**  (see my commits 3.1 and 3.2 as above). 
I believe that **the command got success some times ago**.
It will be very appreciated if you could let us know **the environment (or configuration) that you had made the command succeed in with**? You just need to let us know which commit needs to be **restored** from repository, then we could reproduce your success of the training.  
Many thanks again.

**Comment by rockyrhodes** [comment]
Sorry you're having trouble reproducing our results.  @dansitu can help with the details of the exact configuration we used in our tutorial.  I've also downloaded the model file you supplied and will see if I get any better results.  Maybe @dansitu can also comment on the accuracy that should be expected when running this code on a sparkfun board with our demo code.  The accuracy number quoted is the accuracy expected from the training code.

**Comment by huaxiaozhong1** [comment]
### 4, A model was created. 
***Thanks*** for [@rockyrhodes](https://github.com/rockyrhodes) taking care of the issue and [@dansitu](https://github.com/dansitu) handling it.

With surfing internet and my trials, the example model of "speech recognition", 
trained by tensorflow/examples/speech_commands/***train.py***, can reach ***accuracy ~ 90%***. 
But, if running the model on ***on SparkFun Edge board*** (e.g., a word "Yes"), the confidence score is ***far lower*** than the score that the existing binary model, provided by the commit,  provides. 
What is ***key problem*** for us to ***train your own*** "speech recognition" ***model***? According to my experiences, the key problem is to find correct git repository commit. 
At the end of this comment, you will learn how to ***create***/***train***/***flash*** a model based on 2 commits of Tensorflow repository. If "detection_threshold" is set as 150 (the commit provides a binary format model whose "detection_threshold" is 200), the model could recognize almost all "Yes" heard on SparkFun Edge board. 

#### 4.1, Setup environment.
[How to Train New TensorFlow Lite Micro Speech Models](https://www.digikey.com/en/maker/projects/how-to-train-new-tensorflow-lite-micro-speech-models/e9480d4a38264604a2bf0336ce11aa9e) is a good reference. 
```
sudo docker run --runtime=nvidia –name speech-verify -it tensorflow/tensorflow:1.15.0-gpu-py3-jupyter bash
sudo docker container start speech-verify
sudo docker container exec -it speech-verify /bin/bash 
```
Within the container,
```
apt-get install -y curl zip git xxd

pip3 list | grep tensorflow
tensorflow-estimator 1.15.1             
tensorflow-gpu       1.15.0

pip3 install tf-nightly-gpu==1.15.0.dev20190729
pip3 install -I tensorflow_estimator==1.13.0

curl -O -L https://github.com/bazelbuild/bazel/releases/download/0.23.1/bazel-0.23.1-installer-linux-x86_64.sh
chmod +x bazel-0.23.1-installer-linux-x86_64.sh
./bazel-0.23.1-installer-linux-x86_64.sh 
```
Checkout 2 commits from Git repository of Tensorflow:
```
git clone https://github.com/tensorflow/tensorflow.git

cp -rp  tensorflow  tensorflow-aa47072ff4e2b7735b0e0ef9ef52f68ffbf7ef54
cd  tensorflow-aa47072ff4e2b7735b0e0ef9ef52f68ffbf7ef54
git checkout aa47072ff4e2b7735b0e0ef9ef52f68ffbf7ef54

cd ..
mv tensorflow tensorflow-4a464440b2e8f382f442b6e952d64a56701ab045
cd tensorflow-4a464440b2e8f382f442b6e952d64a56701ab045
git checkout 4a464440b2e8f382f442b6e952d64a56701ab045

yes "" | ./configure

```
#### 4.2, Training.
Still in the container:
```
bazel run -c opt --copt=-mavx2 --copt=-mfma tensorflow/examples/speech_commands:train -- --model_architecture=tiny_conv --window_stride=20 --preprocess=micro --wanted_words="yes,no" --silence_percentage=25 --unknown_percentage=25 –quantize=1

bazel run tensorflow/examples/speech_commands:freeze -- --model_architecture=tiny_conv --window_stride=20 --preprocess=micro --wanted_words="yes,no" --quantize=1 --output_file=/tmp/tiny_conv.pb –start_checkpoint=/tmp/speech_commands_train/tiny_conv.ckpt-18000

bazel run tensorflow/lite/toco:toco -- --input_file=/tmp/tiny_conv.pb --output_file=/tmp/tiny_conv.tflite --input_shapes=1,49,40,1 --input_arrays=Reshapexxd -i /tmp/tiny_conv.tflite > /tmp/tiny_conv_micro_features_model_data.cc_1 --output_arrays='labels_softmax' --inference_type=QUANTIZED_UINT8 --mean_values=0 --std_values=9.8077

xxd -i /tmp/tiny_conv.tflite > /tmp/tiny_conv_micro_features_model_data.cc
```
#### 4.3, Flash.
Continue inside container:
```
cd ../tensorflow-4a464440b2e8f382f442b6e952d64a56701ab045
```
Actually the commit provides an existing model that was trained, which is located at: ***tensorflow/tensorflow/lite/experimental/micro/examples/micro_speech/tiny_conv_micro_features_model_data.cc***. Change its name and keep it in case we want to test it as comparison. 
Change value of "detection_threshold" to 150 (source file: tensorflow/tensorflow/lite/experimental/micro/examples/micro_speech/micro_features/recognize_commands.h).
```
mv tensorflow/tensorflow/lite/experimental/micro/examples/micro_speech/micro_features/tiny_conv_micro_features_model_data.cc 
tensorflow/tensorflow/lite/experimental/micro/examples/micro_speech/micro_features/tiny_conv_micro_features_model_data.ori.cc
cp -p  /tmp/tiny_conv_micro_features_model_data.cc tensorflow/tensorflow/lite/experimental/micro/examples/micro_speech/micro_features

make -f tensorflow/lite/experimental/micro/tools/make/Makefile clean

make -f tensorflow/lite/experimental/micro/tools/make/Makefile TARGET=sparkfun_edge TAGS="CMSIS" micro_speech_bin

cp tensorflow/lite/experimental/micro/tools/make/downloads/AmbiqSuite-Rel2.0.0/tools/apollo3_scripts/keys_info0.py \
tensorflow/lite/experimental/micro/tools/make/downloads/AmbiqSuite-Rel2.0.0/tools/apollo3_scripts/keys_info.py

python3 tensorflow/lite/experimental/micro/tools/make/downloads/AmbiqSuite-Rel2.0.0/tools/apollo3_scripts/create_cust_image_blob.py \
--bin tensorflow/lite/experimental/micro/tools/make/gen/sparkfun_edge_cortex-m4/bin/micro_speech.bin \
--load-address 0xC000 \
--magic-num 0xCB \
-o main_nonsecure_ota \
--version 0x0

python3 tensorflow/lite/experimental/micro/tools/make/downloads/AmbiqSuite-Rel2.0.0/tools/apollo3_scripts/create_cust_wireupdate_blob.py \
--load-address 0x20000 \
--bin main_nonsecure_ota.bin \
-i 6 \detection_threshold
-o main_nonsecure_wire \
--options 0x1
```
Following the [STEPs](https://codelabs.developers.google.com/codelabs/sparkfun-tensorflow/#5), flash the board physically. 
#### 4.4, Comparison for 2 test results.
If [Reading debug output](https://codelabs.developers.google.com/codelabs/sparkfun-tensorflow/#8),we could get 2 test results. 
![binary-model-provided-by-the-commit](https://user-images.githubusercontent.com/20430028/68668334-e723ec80-0582-11ea-80e8-649de08202ef.png) is the test result originating from running the existing binary model (see 4.3). The test recognizes all sound "Yes" with "detection_threshold=200".
![model-trained-by-the-commit](https://user-images.githubusercontent.com/20430028/68669339-43880b80-0585-11ea-85c8-5c1918f934ea.png) shows the test based on the model we have just trained. The model recognizes almost all "Yes" but detection_threshold is tuned to a lower value: 150. 
#### 4.5, Remaining question.
We have just created a model that could manage to recognize words (e.g., "Yes") as expected. But It is sure that someone had created a working model that can get higher confidence accuracy. How could we reach the "higher confidence accuracy"?

**Comment by huaxiaozhong1** [comment]
As for my ***"Remaining question"*** (see 4.5 above): ***"How could we reach the 'higher confidence accuracy'?"***, could you give us some guidance? Thanks!

**Comment by huaxiaozhong1** [comment]
#### 4.3, Flash (the section needs to be fixed as below)
Prepare the board image to flash, which the trained model is in.
Still in the container, change directory --
```
cd ../tensorflow-4a464440b2e8f382f442b6e952d64a56701ab045
```
Actually the commit provides an existing trained model, which is: tensorflow-4a464440b2e8f382f442b6e952d64a56701ab045/tensorflow/lite/experimental/micro/examples/micro_speech/tiny_conv_micro_features_model_data.cc. Change its name as tiny_conv_micro_features_model_data.ori.cc and keep it in case you may need to test it as comparison.

Regarding to the current "confidence score" that can be reached with the 2 commits, I would suggest to change value of "[detection_threshold](tensorflow-4a464440b2e8f382f442b6e952d64a56701ab045/tensorflow/lite/experimental/micro/examples/micro_speech/micro_features/recognize_commands.h)" to 150.
```
mv tensorflow/lite/experimental/micro/examples/micro_speech/micro_features/tiny_conv_micro_features_model_data.cc 
tensorflow/lite/experimental/micro/examples/micro_speech/micro_features/tiny_conv_micro_features_model_data.ori.cc
cp -p  /tmp/tiny_conv_micro_features_model_data.cc tensorflow/lite/experimental/micro/examples/micro_speech/micro_features
```
Following "[Convert to a C array](https://www.tensorflow.org/lite/microcontrollers/build_convert#convert_to_a_c_array)", copy the head and tail of tensorflow-4a464440b2e8f382f442b6e952d64a56701ab045/tensorflow/lite/experimental/micro/examples/micro_speech/micro_features/tiny_conv_micro_features_model_data.ori.cc, paste them to tiny_conv_micro_featurestensorflow-4a464440b2e8f382f442b6e952d64a56701ab045/tensorflow/lite/experimental/micro/examples/micro_speech/micro_features/tiny_conv_micro_features_model_data.cc.

Build borad image including the model and all depedencies --
```
make -f tensorflow/lite/experimental/micro/tools/make/Makefile clean

make -f tensorflow/lite/experimental/micro/tools/make/Makefile TARGET=sparkfun_edge TAGS="CMSIS" micro_speech_bin

cp tensorflow/lite/experimental/micro/tools/make/downloads/AmbiqSuite-Rel2.0.0/tools/apollo3_scripts/keys_info0.py \
tensorflow/lite/experimental/micro/tools/make/downloads/AmbiqSuite-Rel2.0.0/tools/apollo3_scripts/keys_info.py

python3 tensorflow/lite/experimental/micro/tools/make/downloads/AmbiqSuite-Rel2.0.0/tools/apollo3_scripts/create_cust_image_blob.py \
--bin tensorflow/lite/experimental/micro/tools/make/gen/sparkfun_edge_cortex-m4/bin/micro_speech.bin \
--load-address 0xC000 \
--magic-num 0xCB \
-o main_nonsecure_ota \
--version 0x0

python3 tensorflow/lite/experimental/micro/tools/make/downloads/AmbiqSuite-Rel2.0.0/tools/apollo3_scripts/create_cust_wireupdate_blob.py \
--load-address 0x20000 \
--bin main_nonsecure_ota.bin \
-i 6 \detection_threshold
-o main_nonsecure_wire \
--options 0x1
```
