### ISSUE TITLE
tf 1.15.0  retrained ssdlite_mobilenet_v2_coco+focal loss to quantization

### ISSUE THREAD

**Issue by zychen2016** [tensorflow/tensorflow#33779]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):  Ubuntu18.04
- TensorFlow installed from (source or binary):  source
- TensorFlow version (or github SHA if from source): 1.15.0

Step1:retrain ssdlite_mobilenet_v2_coco model using focal loss,get model.ckpt
Step2:using export_inference_graph.py to get frozen_inference_graph.pb and saved_model
Step3:using tflite 

```
import tensorflow as tf
converter = tf.lite.TFLiteConverter.from_saved_model(path/to/saved_model_dir)
converter.optimizations = [tf.lite.Optimize.OPTIMIZE_FOR_SIZE]
tflite_quant_model = converter.convert()
```

```
//error
array.data_type==array.final_data_type Array "image_tensor" has mis-matching .....(data_type=uint8,final_data_type=float)
```

Then, using `saved_model_cli show --dir=./saved_model --all` 

ouput is

```
signature_def['serving_default']:
  The given SavedModel SignatureDef contains the following input(s):
    inputs['inputs'] tensor_info:
        dtype: DT_UINT8
        shape: (-1, -1, -1, 3)
        name: image_tensor:0
  The given SavedModel SignatureDef contains the following output(s):
    outputs['detection_boxes'] tensor_info:
        dtype: DT_FLOAT
        shape: (-1, 100, 4)
        name: detection_boxes:0
    outputs['detection_classes'] tensor_info:
        dtype: DT_FLOAT
        shape: (-1, 100)
        name: detection_classes:0
    outputs['detection_scores'] tensor_info:
        dtype: DT_FLOAT
        shape: (-1, 100)
        name: detection_scores:0
    outputs['num_detections'] tensor_info:
        dtype: DT_FLOAT
        shape: (-1)
        name: num_detections:0
  Method name is: tensorflow/serving/predict
```

1.Just means , my saved_model input is unit8 and output is float32, could not using tf-lite to quantization?
2. Could get ssd_mobilenet_v2 quantized model without config parameter,it means train again!!
`graph_rewriter {quantization {....}}`

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.
