### ISSUE TITLE
Is it possible to support gif images in ImageDataGenerator?

### ISSUE THREAD

**Issue by ZxMYS** [tensorflow/tensorflow#33770]
**System information**
- TensorFlow version (you are using):
 2.0.0
- Are you willing to contribute it (Yes/No):
Not sure how to :(

**Describe the feature and the current behavior/state.**
ImageDataGenerator currently ignores gif images in its methods (like `flow_from_directory`), why doesn't it take gif? As gif is also widely used over the Internet it should be supported too.
**Will this change the current api? How?**
No
**Who will benefit with this feature?**
Whoever that has a bunch of gif in their dataset

**Comment by omalleyt12** [comment]
@ZxMYS Future work in data handling is happening in `tf.data` and `tf.io`

You can decode a gif using this method: https://www.tensorflow.org/api_docs/python/tf/io/decode_gif
