### ISSUE TITLE
For tf2.0, why both tf.keras and tf.nn exist in the new version of Tensorflow? 

### ISSUE THREAD

**Issue by Zhengtq** [tensorflow/tensorflow#33775]
I found that tf.keras and tf.nn could do the same thing, so why keep both tf.keras and tf.nn existed in the new version of tf2.0?

**Comment by ymodak** [comment]
A subset of ```tf.keras``` functions are available in ```tf.nn``` module. However the parameters of these functions are different.
For instance we may compare the parameters of [tf.nn.conv2d](https://www.tensorflow.org/api_docs/python/tf/nn/conv2d) and  [tf.keras.layers.Conv2D](https://www.tensorflow.org/api_docs/python/tf/keras/layers/Conv2D)
Therefore it offers more flexibility to the users for same implementation.

**Comment by Zhengtq** [comment]
As tf.keras api could provide more flexibility in contrast to tf.nn api, so I think there is no need to keep tf.nn api in the new version of tf2.0 any more. If keep both, it could cause more confusion to tensorflow users.

**Comment by MaggieLieu** [comment]
tf.nn.conv2d and tf.keras.layers.Conv2D for example are not the same. The former does not yet include bias or activation. Personally I find tf.nn more flexible in particular for custom models whereas tf.keras is easier to use.

**Comment by gowthamkpr** [comment]
@Zhengtq Yes. As mentioned in the above comment, tf.nn is used for flexibility for custom models and tf.keras is based on usability.

For more information you can follow the folllowing [thread](https://stackoverflow.com/questions/42785026/tf-nn-conv2d-vs-tf-layers-conv2d). Thanks!
