### ISSUE TITLE
tflite_convert always required '--saved_model_dir --keras_model_file' arguments, even I specified '--graph_def_file'

### ISSUE THREAD

**Issue by xenogew** [tensorflow/tensorflow#33774]
## Computer spec:
-  Windows 10 update 1903 (build 18362.449)
-  Python 3.7 (run with venv)
-  Powershell Core console under VS Code
- Tensorflow 2.0.0 (install with `pip`)

## URL(s) with the issue:

Please provide a link to the documentation entry, for example:
https://www.tensorflow.org/lite/convert/cmdline_examples

## Description of issue (what needs changing):

Example defined what I can't follow, and the result always error with no specific arguments `--saved_model_dir` or `--keras_model_file`. 
Moreover, if I specified `--keras_model_file` with file name, it won't count as a file, it turn out the code logic count as it a folder path. 

### Clear description

In my case: Basic example -> [Convert a Tensorflow Graphdef](https://www.tensorflow.org/lite/convert/cmdline_examples#convert_a_tensorflow_graphdef_). I did download file as specify in `curl` command then extracted it to `./tmp`. Copy all you code in example code frame and run it. `tflite_convert --output_file=./tmp/foo.tflite --graph_def_file=./tmp/mobilenet_v1_0.50_128/frozen_graph.pb --input_arrays=input --output_arrays=MobilenetV1/Predictions/Reshape_1` then it throw with error. 
```
usage: tflite_convert [-h] --output_file OUTPUT_FILE
                      (--saved_model_dir SAVED_MODEL_DIR | --keras_model_file KERAS_MODEL_FILE)
tflite_convert: error: one of the arguments --saved_model_dir --keras_model_file is required
```

### Correct links

**Basic** example should no some kind like this error. And I'm the beginner here who need to learn from basic example code you prepared.

### Parameters defined

As you can see above, that was the command defined in you document page and I just copy + paste into command console.

### Returns defined

No, but it shouldn't error like this.

### Raises listed and defined

Above, I wrote it.

### Usage example

Above, I wrote it.

### Request visuals, if applicable

Run yourself, you will see what I got.

### Submit a pull request?

No.

**Comment by Mycaster** [comment]
cannot  reproduce it

**Comment by xenogew** [comment]
Update:
Change environment to a newly created Virtual Machine on Azure
-  CentOS 7.7.1908
-  Python3.6
-  pip version 19.3.1
-  Tensorflow version 2.0.0 (install via `pip install`)

Result:
```
tflite_convert \
>   --output_file=/tmp/foo.tflite \
>   --graph_def_file=/tmp/mobilenet_v1_0.50_128/frozen_graph.pb \
>   --input_arrays=input \
>   --output_arrays=MobilenetV1/Predictions/Reshape_1
usage: tflite_convert [-h] --output_file OUTPUT_FILE
                      (--saved_model_dir SAVED_MODEL_DIR | --keras_model_file KERAS_MODEL_FILE)
tflite_convert: error: one of the arguments --saved_model_dir --keras_model_file is required
```

**Comment by ymodak** [comment]
The [example](https://www.tensorflow.org/lite/convert/cmdline_examples#convert_a_tensorflow_graphdef_) you are referring to contains documentation on using the ```tflite_convert``` command line tool in TensorFlow 1.X. Therefore the above example works in TF 1.X and fails in TF 2.X
For using ```tflite_convert``` command line tool in TF 2.X you may see https://www.tensorflow.org/lite/convert/index

**Comment by xenogew** [comment]
Then,
Can I use model `.pb` file from the [example](https://www.tensorflow.org/lite/convert/cmdline_examples#convert_a_tensorflow_graphdef_) (the stuff defined in example `curl https://storage.googleapis.com/download.tensorflow.org/models/mobilenet_v1_0.50_128_frozen.tgz   | tar xzv -C /tmp` to be a convert source model?

The truth is I tried once and it look like it's the **multiple functions** that the convert tool doesn't be implemented yet.
```
ValueError: This converter can only convert a single ConcreteFunction. Converting multiple functions is under development.
```

And it has same result as I tried with downloaded model from **Azure Custom Vision**.

To clarify more specifically for what I want. I want to run ["Android example project of Object Detection"](https://github.com/tensorflow/examples/blob/master/lite/examples/object_detection/android/README.md) with the `.tflite` trained model which downloaded from **Azure Custom Vision**.

First, I tried with `.tflite` version: result -> app crashed immediately with "byte buffer specific number is not correct" error message.
Then, I want to tried from convert `.pb` version to `.tflite` as what I understand now the `.pb` file I got it should be a "saved model". But result is same **Converting multiple functions is under development**

As a new to Machine Learning like me, I just need an example that can follow and see output without error, so, I can use it as reference what is different from what I got. The thing I found right now make my head confuse and dizzy because I spend time for this issue for 7 days.

**Comment by freedomtan** [comment]
@xenogew You are trying to use a classification model in an object detection example. As stated explained in the [Android example project of Object Detection](https://github.com/tensorflow/examples/blob/master/lite/examples/object_detection/android/README.md) page you referred to, you should start from a quantized [MobileNet SSD](https://github.com/tensorflow/models/tree/master/research/object_detection) model instead.

**classification models != object detection models**

**Comment by xenogew** [comment]
@freedomtan OK, in the case you mentioned, I tried once with create new project on Azure Custom Vision in Object Detection type - trained - download `.tflite` file and replace in the Android example code. But it still crashed with exception.
```
...
...
E/AndroidRuntime: FATAL EXCEPTION: inference
    Process: org.tensorflow.lite.examples.detection, PID: 21344
    java.lang.IllegalArgumentException: Cannot convert between a TensorFlowLite buffer with 2076672 bytes and a ByteBuffer with 270000 bytes.
...
...
```
Do you have suggestion about this issue?

And what you mentioned about "Quantized MobileNet SSD", how can I recognize it, cause it's not appear about it in anywhere? Do Tensorflow have command line to detect type of the model?

**Comment by freedomtan** [comment]
That looks like tensor size mismatch. I am not familiar with Azure related stuff, are you sure that models generated by the service is compatible with the app? My suggestion is to start from something like the [TFLite object detection doc](https://www.tensorflow.org/lite/models/object_detection/overview) and read [quantization](https://www.tensorflow.org/lite/performance/model_optimization) related stuff.

**Comment by xenogew** [comment]
@freedomtan Yes, sure, I downloaded from the 'Export' option which provide a lot of type of model compatible and Tensorflow is the one of them, it also provide choices of Tensorflow, Tensorflow Lite, Tensorflow.js.

So, the version compatible will be related to this issue? For example: "Android example use the 'Model' created by Tensorflow 2.0" but "Azure thing is created from Tensorflow 1.7" (I don't know, is it really  be?, but just raise example to ask you about backward compatibility of Model)

### The tensor size you mentioned, what is it?
-  Is it related to anything about technical term/word of Tensorflow?
-  Or it's just a file size that mismatch to the defined variable in the code?
-  I thought the code will be defined with variable, so the size of it shouldn't related to the model file that much. I thought it should read the size number from the file that be defined the file reference (path/file name) and the code read it and recognize the file size itself. Am I wrong?
-  If you please, could you help me point to the place in the code, which I should learn and make change to it to make the application can run without crash?

And thanks to the guide links you mentioned, I'll take a look at them.

**Comment by ymodak** [comment]
> Update:
> Change environment to a newly created Virtual Machine on Azure
> 
> * CentOS 7.7.1908
> * Python3.6
> * pip version 19.3.1
> * Tensorflow version 2.0.0 (install via `pip install`)
> 
> Result:
> 
> ```
> tflite_convert \
> >   --output_file=/tmp/foo.tflite \
> >   --graph_def_file=/tmp/mobilenet_v1_0.50_128/frozen_graph.pb \
> >   --input_arrays=input \
> >   --output_arrays=MobilenetV1/Predictions/Reshape_1
> usage: tflite_convert [-h] --output_file OUTPUT_FILE
>                       (--saved_model_dir SAVED_MODEL_DIR | --keras_model_file KERAS_MODEL_FILE)
> tflite_convert: error: one of the arguments --saved_model_dir --keras_model_file is required
> ```

Apologies for the delay in response. You may add the `--enable_v1_converter` flag to get support for converting graphdefs from the command line in TF 2.
```
tflite_convert \
  --output_file=/tmp/foo.tflite \
  --graph_def_file=/tmp/mobilenet_v1_0.50_128/frozen_graph.pb \
  --enable_v1_converter\
  --input_arrays=input \
   --output_arrays=MobilenetV1/Predictions/Reshape_1
```
