### ISSUE TITLE
 Model created by tf.keras.models.Model does not have attribute 'metrics_tensors'

### ISSUE THREAD

**Issue by kiflowb777** [tensorflow/tensorflow#33789]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): pip
- TensorFlow version (use command below): 1.14 and 2.0 (GPU)
- Python version: 3.6.1
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 10/6.7.4
- GPU model and memory: RTX 2060

After switching to tf.keras from Keras I cannot append to metrics_tensors.
Code from https://github.com/matterport/Mask_RCNN
```
# Add metrics for losses
        for name in loss_names:
            if name in self.keras_model.metrics_names:
                continue
            layer = self.keras_model.get_layer(name)
            self.keras_model.metrics_names.append(name)
            loss = (
                tf.reduce_mean(layer.output, keepdims=True)
                * self.config.LOSS_WEIGHTS.get(name, 1.))
            self.keras_model.metrics_tensors.append(loss)
```
result:
```
  File "C:\Project\mrcnn\model.py", line 35, in build_mrcnn_network
    maskRcnn = MaskRCNN(mode, config, common_services, depth, service_version)
  File "C:\Project\mrcnn\model.py", line 52, in __init__
    self.compile()
  File "C:\Project\mrcnn\model.py", line 270, in compile
    self.keras_model.metrics_tensors.append(loss)
AttributeError: 'Model' object has no attribute 'metrics_tensors'
```

**Comment by kiflowb777** [comment]
Documents relating to this matter:
https://github.com/keras-team/keras/issues/13497
https://github.com/matterport/Mask_RCNN/issues/1820

**Comment by ravikyram** [comment]
@kiflowb777 
Can you please share simple standalone code to reproduce the issue in our environment. It helps in localizing the issue faster. Thanks!

**Comment by kiflowb777** [comment]
```
use_tf_keras = False

import numpy as np
import mnist
import tensorflow as tf

if use_tf_keras:
    from tensorflow.keras.models import Sequential
    from tensorflow.keras.layers import Dense
    from tensorflow.keras.utils import to_categorical
else:
    from keras.models import Sequential
    from keras.layers import Dense
    from keras.utils import to_categorical

train_images = mnist.train_images()
train_labels = mnist.train_labels()
test_images = mnist.test_images()
test_labels = mnist.test_labels()

# Normalize the images.
train_images = (train_images / 255) - 0.5
test_images = (test_images / 255) - 0.5

# Flatten the images.
train_images = train_images.reshape((-1, 784))
test_images = test_images.reshape((-1, 784))

# Build the model.
model = Sequential([
  Dense(64, activation='relu', input_shape=(784,)),
  Dense(64, activation='relu'),
  Dense(10, activation='softmax'),
])

loss_name = 'categorical_crossentropy'

# Compile the model.
model.compile(
  optimizer='adam',
  loss=loss_name,
  metrics=['accuracy'],
)

# This causes an error after switching to the tf.keras
for layer in model.layers:
    loss = tf.reduce_mean(layer.output, keepdims=True)
    model.metrics_tensors.append(loss)  # if tf.keras: AttributeError: 'Sequential' object has no attribute 'metrics_tensors'

# Train the model.
model.fit(
  train_images,
  to_categorical(train_labels),
  epochs=5,
  batch_size=32,
)
```

use_tf_keras= False (use Keras), 
use_tf_keras = True (then use tf.keras)

**Comment by kiflowb777** [comment]
if I use the Keras everything is ok, but when I use the tf.keras I get an error:
```
AttributeError                            Traceback (most recent call last)
<ipython-input-9-c6ee62f59e7b> in <module>
     46 for layer in model.layers:
     47     loss = tf.reduce_mean(layer.output, keepdims=True)
---> 48     model.metrics_tensors.append(loss)
     49 
     50 # Train the model.

AttributeError: 'Sequential' object has no attribute 'metrics_tensors'
```

**Comment by jvishnuvardhan** [comment]
@kiflowb777 The error is correctly displaying the attribute error as there is no attribute named "metric_tensors". When i changed one line from 
`model.metrics_tensors.append(loss)`
to
`model.metrics.append(loss)`
there was no error. I changed your code to work with `tf.keras` and the updated code is [here](https://colab.sandbox.google.com/gist/jvishnuvardhan/6305f3b797a7ca9059b9d766e71a53f1/untitled605.ipynb). Thanks!

I will close this issue as it was resolved. Please feel free to reopen if the issue persists again. Thanks!

**Comment by kiflowb777** [comment]
Related topics: https://github.com/tensorflow/tensorflow/issues/34443

**Comment by kiflowb777** [comment]
Should you use
```model.metrics.append(loss)```
 or 
```model.add_metric(loss)```
?
