### ISSUE TITLE
Using tf.keras.backend.zeros in while loops.

### ISSUE THREAD

**Issue by hgaiser** [tensorflow/tensorflow#33787]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): **Yes**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): **Arch Linux**
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): **Binary**
- TensorFlow version (use command below): **2.0.0**
- Python version: **3.7**
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: **N/A**
- GPU model and memory: **N/A**

**Describe the current behavior**
The effect of `tf.zeros` and `tf.keras.backend.zeros` is not the same and results in some inconsistent behaviour. This also holds for other functions such as `tf.keras.backend.ones` and others like it.

Specifically, using `tf.keras.backend.zeros` in a `tf.map_fn` function (or something similar) breaks because `tf.keras.backend.zeros` has a `tf.init_scope` which causes it to be created out of the context of the while loop.

**Describe the expected behavior**
Expected behaviour would be that `tf.zeros` and `tf.keras.backend.zeros` are identical and that they follow the usage of `tf.zeros`; meaning not changing the scope in which they are created.

**Code to reproduce the issue**
```python
import tensorflow as tf

tf.compat.v1.disable_v2_behavior()

# Works because we don't change the scope.
def works(inputs):
	return tf.zeros((tf.keras.backend.shape(inputs[0])[0],))

# Works because both tf.zeros and its inputs are in the same scope.
## This function helps explain the root of the issue.
def works2(inputs):
	with tf.init_scope():
		return tf.zeros((tf.keras.backend.shape(inputs[0])[0],))

# Breaks because tf.keras.backend.zeros is being created in a different scope from tf.keras.backend.shape.
def breaks(inputs):
	return tf.keras.backend.zeros((tf.keras.backend.shape(inputs[0])[0],))

# Breaks because the shape is created outside of the context of the tf.zeros.
## This function helps explain the root of the issue.
## This is an extract of how tf.keras.backend.zeros is implemented.
def breaks2(inputs):
	shape = (tf.keras.backend.shape(inputs[0])[0],)
	with tf.init_scope():
		return tf.zeros(shape)

inputs = [tf.keras.layers.Input(shape=(5, 5))]

# This works when using tf.zeros because it doesn't change the scope.
tf.map_fn(works, elems=inputs, dtype=tf.keras.backend.floatx())

# This works when tf.zeros and its inputs are in the same scope (using tf.init_scope).
tf.map_fn(works2, elems=inputs, dtype=tf.keras.backend.floatx())

# This breaks when using tf.keras.backend.zeros because it creates the zeros in a new scope.
try:
	tf.map_fn(breaks, elems=inputs, dtype=tf.keras.backend.floatx())
except ValueError as e:
	print("Caught error: {}".format(e))

# This breaks when using tf.zeros when its inputs are defined in a different scope.
try:
	tf.map_fn(breaks2, elems=inputs, dtype=tf.keras.backend.floatx())
except ValueError as e:
	print("Caught error: {}".format(e))
```

**Other info / logs**
This change was introduced in https://github.com/tensorflow/tensorflow/commit/1d91f3532ee4df36749dda1a39b8a2a78232dd74 by @rjpower . It would be great if I could get some feedback on why this `init_scope` got added there and if it should be changed.

**Comment by rjpower** [comment]
Indeed, this was my change, but I've long forgotten the reasoning. I looked up a bit more context. Summarizing the conversation at the time:

Variables initialized inside of a loop (as from a training loop) need to be in the init_scope to avoid an error.  For layers, this is handled by the make_variable helper, but optimizers can end up creating temporary variables and triggering this issue.

I'm not sure what the contract is for tf.keras.backend (is it intended as public or not). But I support fixing this. We should remmove the scoping from backend.{zeros, ones} and explicitly add the init_scope when initializing optimizer variables. I'll defer to the keras-team for how to properly stage the fix.

**Comment by hgaiser** [comment]
Thank you for the feedback @rjpower . I'm fairly certain `tf.keras.backend` is intended to be public, as it provides an easy migration from `keras` to `tf.keras`.

> I'll defer to the keras-team for how to properly stage the fix.

Is there a way I can follow this progress? Or will this issue be updated when the keras-team handles it?

**Comment by rjpower** [comment]
Sorry for the delay -- yes -- I'll ask someone on the Keras/DS team to look into this and update the status on this issue.

**Comment by hgaiser** [comment]
Hey @rjpower , it has been a while, is there an update on this issue?

**Comment by hgaiser** [comment]
@rjpower any update on this?

**Comment by rjpower** [comment]
@hgaiser apologies for the delay.

So: tf.keras.backend should be considered private to Keras. Unfortunately it looks like fixing the behavior will be somewhat challenging as it affects variable initialization. There's some long term work planned to try to make this more consistent, but I'm afraid it won't land soon.

**Comment by qlzh727** [comment]
Note that tf.zeros and tf.keras.backend.zeros are different.

tf.zeros is expected to return a constant tensor, whereas tf.keras.backend.zeros is expected to return a **variable** that filled with zeros. The keras one is more like a shortcut to create variable with a zero initializer.

Closing this bug since the expectation of those two API are different.

**Comment by hgaiser** [comment]
@qlzh727 I understand that `tensorflow.zeros` creates a constant tensor and `tf.keras.backend.zeros` creates a variable, but shouldn't they both be useable in a while loop?

Currently, `tf.keras.backend.zeros` **can't** be used in while loops, while if you created a `tf.variable` containing zeros you **can** use it in while loops. Surely that's a bug right?

**Comment by qlzh727** [comment]
Thanks for bring this up. I agree that forcing init_scope under the hood is not ideal, and its not clearly documented in the API docstring.

I think the issue that @rjpower trying to walkaround is for the optimizer, which use backend.zeros to create varibles. I think we should remove the init_scope in backend.zeros, and add init_scope explicitly to the optimizer.

**Comment by qlzh727** [comment]
Checked with @fchollet offline for this issue. He think it is fine to create variables with zeros/ones under init scope, and we will keep this behavior. If you need non-variable zeros under while loop, you can use tf.zeros, otherwise, you can use tf.Variable(), but the initiali value of it need to be under init_scope as well.

**Comment by hgaiser** [comment]
I respectfully disagree with you @qlzh727 . What is the motivation for @fchollet to say it is fine? I can't think of any reason for a function as basic as a `zeros` or `ones` to not work in a different scope (like a loop). Specially since it used to work before https://github.com/tensorflow/tensorflow/commit/1d91f3532ee4df36749dda1a39b8a2a78232dd74 . 

I don't know what the motivation is for `zeros` and `ones` to be in `init_scope` for the optimizer, but it makes more sense to perform the scope change there instead of forcing it everywhere when it isn't necessary. This simply breaks expected (and previously working) functionality. What is the benefit, outside of the optimizer, to use `tf.init_scope`? 

You suggest to use `tf.zeros` instead, which is a possible (yet in my opinion illogical) solution, but this same issue exists in Keras. In the case of Keras it makes no sense at all to use `tf.zeros` since the whole idea is to be backend independent. I was expecting this to be fixed in `tf.keras` so that it can possibly be fixed in Keras as well.
