### ISSUE TITLE
TFLiteConverter from_keras_model TypeError: call() got an unexpected keyword argument 'training'

### ISSUE THREAD

**Issue by ONLYstcm** [tensorflow/tensorflow#33788]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Custom code
- Arch Linux Kernel 5.3.7
- TensorFlow installed via pip
- TensorFlow version v2.0.0-rc2-26-g64c3d38 2.0.0
- Python version: 3.7.4

**Describe the current behavior**
When trying to convert a Keras CNN to TFlite file I get an error at the following line: `converter = tf.lite.TFLiteConverter.from_keras_model(model)`

**Describe the expected behavior**
A TFlite file is expected to be created and written to the local directory.

**Code to reproduce the issue**
```
# Importing the Keras libraries and packages
from keras.models import Sequential, save_model
from keras.layers.core import Dense, Dropout, Flatten
from keras.layers.convolutional import Conv2D, MaxPooling2D
from keras.preprocessing import image
from sklearn.metrics import classification_report, confusion_matrix
import tensorflow as tf
import numpy as np

imageResX, imageResY = 256, 256

def CNNmodel():
	classifier = Sequential()
	classifier.add(Conv2D(filters=128, kernel_size=(3,3), activation='relu', input_shape=(imageResX, imageResY, 3)))
	classifier.add(MaxPooling2D(pool_size=(3,3)))
	classifier.add(Flatten())
	classifier.add(Dense(units=128, activation='relu'))
	classifier.add(Dropout(rate=0.5))
	classifier.add(Dense(units=4, activation='softmax'))
	classifier.compile(optimizer='sgd', loss='categorical_crossentropy', metrics=['accuracy'])
	return classifier

# create a data generators
train_datagen = image.ImageDataGenerator(rescale=1./255)
test_datagen = image.ImageDataGenerator(rescale=1./255) 

training_set = train_datagen.flow_from_directory('MY DATA/Training', target_size = (imageResX, imageResY), batch_size = 64, class_mode = 'categorical')
evaluate_set = train_datagen.flow_from_directory('MY DATA/Evaluation', target_size = (imageResX, imageResY), batch_size = 64, class_mode = 'categorical')
test_set = test_datagen.flow_from_directory('MY DATA/Testing', target_size = (imageResX, imageResY), batch_size = 64, class_mode = 'categorical', shuffle=False)

step_size_train=training_set.n//training_set.batch_size
step_size_evaluate=evaluate_set.n//evaluate_set.batch_size
step_size_test=test_set.n//test_set.batch_size

model = CNNmodel()
history = model.fit_generator(generator=training_set, steps_per_epoch=step_size_train, epochs=1, validation_data=evaluate_set, validation_steps=step_size_evaluate)

labels = (training_set.class_indices)
labels = dict((v,k) for k,v in labels.items())

# Save KERAS model
modelName = "ST-AI-Model"
save_model(model, str(modelName+".h5"))

# Convert KERAS model
converter = tf.lite.TFLiteConverter.from_keras_model(model)
tflite_model = converter.convert()
open(str(modelName+".tflite"), "wb").write(tflite_model)

prediction = model.predict_generator(generator=test_set, verbose=1)
classes = test_set.classes[test_set.index_array]
predicted_class_indices = np.argmax(prediction, axis=1)
target_names = [labels[k] for k in range(len(training_set.class_indices))]


print('Confusion Matrix')
print(confusion_matrix(test_set.classes[test_set.index_array], predicted_class_indices))
print('Classification Report')
print(sum(predicted_class_indices==classes)/len(test_set.classes))
print(classification_report(test_set.classes[test_set.index_array], predicted_class_indices, target_names=target_names))
```

**Other info / logs**

> Traceback (most recent call last):
  File "/home/user/code/classifier.py", line 98, in <module>
    converter = tf.lite.TFLiteConverter.from_keras_model(model)
  File "/usr/lib/python3.7/site-packages/tensorflow_core/lite/python/lite.py", line 383, in from_keras_model
    concrete_func = func.get_concrete_function()
  File "/usr/lib/python3.7/site-packages/tensorflow_core/python/eager/def_function.py", line 776, in get_concrete_function
    self._initialize(args, kwargs, add_initializers_to=initializer_map)
  File "/usr/lib/python3.7/site-packages/tensorflow_core/python/eager/def_function.py", line 408, in _initialize
    *args, **kwds))
  File "/usr/lib/python3.7/site-packages/tensorflow_core/python/eager/function.py", line 1848, in _get_concrete_function_internal_garbage_collected
    graph_function, _, _ = self._maybe_define_function(args, kwargs)
  File "/usr/lib/python3.7/site-packages/tensorflow_core/python/eager/function.py", line 2150, in _maybe_define_function
    graph_function = self._create_graph_function(args, kwargs)
  File "/usr/lib/python3.7/site-packages/tensorflow_core/python/eager/function.py", line 2041, in _create_graph_function
    capture_by_value=self._capture_by_value),
  File "/usr/lib/python3.7/site-packages/tensorflow_core/python/framework/func_graph.py", line 915, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "/usr/lib/python3.7/site-packages/tensorflow_core/python/eager/def_function.py", line 358, in wrapped_fn
    return weak_wrapped_fn().__wrapped__(*args, **kwds)
  File "/usr/lib/python3.7/site-packages/tensorflow_core/python/keras/saving/saving_utils.py", line 143, in _wrapped_model
    outputs_list = nest.flatten(model(inputs=inputs, training=False))
  File "/usr/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py", line 75, in symbolic_fn_wrapper
    return func(*args, **kwargs)
  File "/usr/lib/python3.7/site-packages/keras/engine/base_layer.py", line 489, in __call__
    output = self.call(inputs, **kwargs)
TypeError: call() got an unexpected keyword argument 'training'
[Finished in 666.7s with exit code 1]

**Comment by haozha111** [comment]
Could you try something like this:

Before you actually create the tflite converter:
converter = tf.lite.TFLiteConverter.from_keras_model(model)
tflite_model = converter.convert()
open(str(modelName+".tflite"), "wb").write(tflite_model)

Try load a new instance of the keras model you just saved, rather than using the one created before training. I just create the same keras model 'CNNmodel' as yours, and convert it directly to tflite (without the fit step) and it works without any issue.

**Comment by ONLYstcm** [comment]
I tried that. Still gives the same error. I've even simplified the code to a much more simple case that produces the same error.

```
# Importing the Keras libraries and packages
from keras.models import Sequential, save_model
from keras.layers.core import Dense, Dropout, Flatten
from keras.layers.convolutional import Conv2D, MaxPooling2D
import tensorflow as tf

imageResX, imageResY = 256, 256

def CNNmodel():
	classifier = Sequential()
	classifier.add(Conv2D(filters=128, kernel_size=(3,3), activation='relu', input_shape=(imageResX, imageResY, 3)))
	classifier.add(MaxPooling2D(pool_size=(3,3)))
	classifier.add(Flatten())
	classifier.add(Dense(units=128, activation='relu'))
	classifier.add(Dropout(rate=0.5))
	classifier.add(Dense(units=4, activation='softmax'))
	classifier.compile(optimizer='sgd', loss='categorical_crossentropy', metrics=['accuracy'])
	return classifier

model = CNNmodel()

# Convert KERAS model
converter = tf.lite.TFLiteConverter.from_keras_model(model)
tflite_model = converter.convert()
open("test.tflite", "wb").write(tflite_model)
```

**Comment by Machine-Hum** [comment]
I'm getting the same error trying to do the same thing, was the resolved?

**Comment by Machine-Hum** [comment]
I've fixed this issue (and am on to the next bug). I was also using the keras lib, however if you switch over to tf.keras the problem goes away.

**Comment by haozha111** [comment]
Forgot to mention that I was also using the `tf.keras` API rather than the pure `keras` version. Could you try switching to `tf.keras` API and convert?

**Comment by ONLYstcm** [comment]
I just switched over, now it's working!

**Comment by ONLYstcm** [comment]
I just switched over, now it's working!

**Comment by krishnak** [comment]
> Forgot to mention that I was also using the `tf.keras` API rather than the pure `keras` version. Could you try switching to `tf.keras` API and convert?

I am getting this error, I am using pure keras, what needs to be done to switch to tf.keras

converter = tf.lite.TFLiteConverter.from_keras_model(model)

should this line be changed to something else, please advise with a code snippet

**Comment by haozha111** [comment]
> > Forgot to mention that I was also using the `tf.keras` API rather than the pure `keras` version. Could you try switching to `tf.keras` API and convert?
> 
> I am getting this error, I am using pure keras, what needs to be done to switch to tf.keras
> 
> converter = tf.lite.TFLiteConverter.from_keras_model(model)
> 
> should this line be changed to something else, please advise with a code snippet

I mean when you build your keras model, use the `tf.keras.xxx` layer API instead of the one without the `tf` prefix. I believe there are some minor differences between the two set of APIs. Cheers.

**Comment by Mohit-Ak** [comment]
> > Forgot to mention that I was also using the `tf.keras` API rather than the pure `keras` version. Could you try switching to `tf.keras` API and convert?
> 
> I am getting this error, I am using pure keras, what needs to be done to switch to tf.keras
> 
> converter = tf.lite.TFLiteConverter.from_keras_model(model)
> 
> should this line be changed to something else, please advise with a code snippet

Here is how the import statements should look. Notice that it is not straight forwards "Find&Replace" as a number of paths have changed.

import tensorflow as tf
from tensorflow.keras.models import Sequential, save_model
from tensorflow.keras.layers import Dense, Dropout, Flatten
from tensorflow.keras.layers import Conv2D, MaxPooling2D

**Comment by Lebhoryi** [comment]
@mritunjai-chandra to your problem， try to update your tensorflow at least 2.3

**Comment by qiyangzhang0329** [comment]
`import tensorflow as tf
assert float(tf.__version__[:3]) >= 2.3
config = tf.compat.v1.ConfigProto()
config.gpu_options.allow_growth = True
session = tf.compat.v1.InteractiveSession(config=config)
import tensorflow.keras as keras
import pathlib
import numpy as np
import tensorflow_model_optimization as tfmot
from tensorflow.keras.preprocessing.image import ImageDataGenerator


origin_model = tf.keras.applications.MobileNetV3Small(
    input_shape=(224, 224, 3), alpha=1.0, include_top=True, weights='imagenet',
    input_tensor=None, pooling=None, classes=1000,
    classifier_activation='softmax'
)


quant_aware_model = tfmot.quantization.keras.quantize_model(origin_model)



quant_aware_model.compile(optimizer=tf.keras.optimizers.RMSprop(lr=0.00001),  # 0.045, momentum=0.9, decay=0.98),
                              loss='sparse_categorical_crossentropy',
                              metrics=['accuracy'])`
When I do this it's very strange to report an error.
![image](https://user-images.githubusercontent.com/32632952/120809866-13e09000-c57d-11eb-8469-6d0cff43b86b.png)
@krishnak @haozha111 @Mohit-Ak @mritunjai-chandra @Machine-Hum,Can you help me find out the reason? It's been bothering me for a long time

**Comment by Etty-Cohen** [comment]
> > > Forgot to mention that I was also using the `tf.keras` API rather than the pure `keras` version. Could you try switching to `tf.keras` API and convert?
> > 
> > 
> > I am getting this error, I am using pure keras, what needs to be done to switch to tf.keras
> > converter = tf.lite.TFLiteConverter.from_keras_model(model)
> > should this line be changed to something else, please advise with a code snippet
> 
> Here is how the import statements should look. Notice that it is not straight forwards "Find&Replace" as a number of paths have changed.
> 
> ```
> import tensorflow as tf
> from tensorflow.keras.models import Sequential, save_model
> from tensorflow.keras.layers import Dense, Dropout, Flatten
> from tensorflow.keras.layers import Conv2D, MaxPooling2D
> ```

@Mohit-Ak , @haozha111 , @o7-machinehum   I also have that problem, and I tried to do the imports like yow write.
But I got an error:
Import "tensorflow.keras.models" could not be resolved
Should I install that tensorflow.keras?
Thanks:)
