### ISSUE TITLE
Why not feed placeholders by name?

### ISSUE THREAD

**Issue by danijar** [tensorflow/tensorflow#3378]
I couldn't find anything [in the documentation](https://www.tensorflow.org/versions/r0.9/how_tos/reading_data/index.html#feeding) on this. Is it possible to feed placeholders by name? If not, why? I think this would be useful to feed graphs after loading them from disk.

```python
import tensorflow as tf
x = tf.placeholder(tf.float32, (None,), 'x')
y = tf.reduce_sum(x)
sess = tf.Session()

sess.run(y, {x: [1, 2, 3]}
# > 6.0

sess.run(y, {'x': [1, 2, 3]}
# > Cannot interpret feed_dict key as Tensor: The name 'x' refers to an operation,
# > not a Tensor. Tensor names must be of the form "<op_name>:<output_index>".

sess.run(y, {tf.get_default_graph().get_operation_by_name('x').outputs[0]: [1, 2, 3]})
# > 6.0
```

**Comment by yaroslavvb** [comment]
You need to add ":0"
print sess.run(y, {'x:0': [1, 2, 3]})

Here's some background on why the ":0" is needed:
http://stackoverflow.com/a/37870634/419116

**Comment by danijar** [comment]
Thanks.

**Comment by dataf3l** [comment]
didn't work for me, but maybe try {x:1} instead of {"x":1} since it takes a dict of tensor as keys and values as values.

**Comment by XiaoZYang** [comment]
@dataf3l  Try to figure out that your placeholder has the same name 'x'. First I try the method @yaroslavvb mentioned it didn't work, and I find out that the placeholder's default name is not 'x'.
