### ISSUE TITLE
tfp.sts.AutoregressiveStateSpaceModel noise mean should be settable

### ISSUE THREAD

**Issue by jrm346** [tensorflow/tensorflow#33784]
**System information**
- TensorFlow version (you are using): 2.0
- Are you willing to contribute it (Yes/No): No

**Describe the feature and the current behavior/state.**

in tfp.sts.AutoregressiveStateSpaceModel you cant currently set the mean of the normally distributed noise. this would be nice to add as some auto-regressive models may add a constant term at each time step. the math would then be :

```python
level[t+1] = (sum(coefficients * levels[t:t-order:-1]) +
              Normal(level_mean, level_scale))
```

**Will this change the current api? How?**
this would require an additional parameter

**Who will benefit with this feature?**
people who want to do auto-regressive models with a constant term

**Any Other info.**

**Comment by rmothukuru** [comment]
@jrm346,
Sorry for the delayed response. Can you please let us know if [this is the functionality](https://www.tensorflow.org/probability/api_docs/python/tfp/sts/AutoregressiveStateSpaceModel#mean) that you are looking for? 

Thanks!
