### ISSUE TITLE
Tensorflow 0.9 HDF5

### ISSUE THREAD

**Issue by tetmin** [tensorflow/tensorflow#3379]
The Tensorflow 0.9 changelog mentions HDF5 support but I can't find any further details. What is actually implemented, is it possible to stream HDF5 files using the Tensorflow pipelines?

**Comment by concretevitamin** [comment]
I did a search in the repo, perhaps the only thing is an usage example?  See `tensorflow/examples/skflow/hdf5_classification.py`.

**Comment by terrytangyuan** [comment]
That example is probably broken as we are switching to learn.dataframe soon instead of data feeder. For now, you can probably load it into numpy. Stay tuned!

**Comment by concretevitamin** [comment]
Ok, closing for now.

**Comment by tetmin** [comment]
Loading into numpy doesn't work since I need out-of-core support, it seems the only way to achieve this now without IO/CPU blocking training is to convert to a TFRecord, is that correct?

**Comment by tomrunia** [comment]
@tetmin: you can use QueueRunners, see: http://stackoverflow.com/questions/34594198/how-to-prefetch-data-using-a-custom-python-function-in-tensorflow

**Comment by KnightOfTheMoonlight** [comment]
@tomrunia  You suggestion just works for small datasets, which out-of-core support is not needed. For big dataset, it is not possible to load the entire dataset once, right? If there's is any mistake from my opinion, please let me know.

@tetmin Hi, I have the same issue. And from my search, change hdf5 file to tfrecord or binary file will be the only feasible way. Did you find another way?
