### ISSUE TITLE
tf.data.Dataset.from_generator triggers a SIGBUS signal when operating with numpy arrays

### ISSUE THREAD

**Issue by santiago-akle** [tensorflow/tensorflow#33796]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): 
OSX Mojave 10.14.6 

- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:

- TensorFlow installed from (source or binary):
Binray
- TensorFlow version (use command below):
GIT v2.0.0-rc2-26-g64c3d382ca 
Tensorflow 2.0.0

- Python version: 
Python 3.6.8

- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
On cpu
- GPU model and memory:

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**

Clean virtualenv with tensorflow==2.0.0 installed 
tf.data.Dataset.from_generator raises a SIGBUS when operating on large enough Numpy arrays 

Using 
tf_dataset = tf.data.Dataset.from_generator(gen_callable,
                                                output_types=(tf.float32),
                                                output_shapes=(None, 3))
with a function that generates and operates on medium sized numpy arrays triggers a SIGBUS signal.

**Describe the expected behavior**

No SIGUS should be raised

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

### NOT A CONTRIBUTION
```
import os

import numpy as np
import tensorflow as tf


def foo(x, R):
    return np.matmul(x, R)


def baz(x, R):
    return foo(x, R)


def bar(x, R):
    registered_x = baz(
        x, R
    )
    return registered_x


def gen_callable():
    for i in range(1):
        R = np.eye(3).astype(np.float32)
        x = np.random.randn(40000, 3).astype(np.float32)
        prod = bar(
            x, R
        )
        yield prod


def make_tf_generator():
    tf_dataset = tf.data.Dataset.from_generator(gen_callable,
                                                output_types=(tf.float32),
                                                output_shapes=(None, 3))

    for d in tf_dataset:
        print(d)

if __name__ == '__main__':
    make_tf_generator()
```
**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

output of pip freeze 

absl-py==0.8.1
astor==0.8.0
gast==0.2.2
google-pasta==0.1.7
grpcio==1.24.1
h5py==2.10.0
Keras-Applications==1.0.8
Keras-Preprocessing==1.1.0
Markdown==3.1.1
numpy==1.17.2
opt-einsum==3.1.0
protobuf==3.10.0
six==1.12.0
tensorboard==2.0.0
tensorflow==2.0.0
tensorflow-estimator==2.0.0
termcolor==1.1.0
Werkzeug==0.16.0
wrapt==1.11.2

**Comment by ymodak** [comment]
Apologies for the delay in response. I was able to execute your script successfully using TF 2.1.0-rc1.
```python
tf.Tensor(
[[-0.31721887  1.0121828   0.18239886]
 [-0.23083398 -1.3029127  -1.4065455 ]
 [-0.05021447  0.17920735  0.6323469 ]
 ...
 [ 0.8527863  -0.31213287  0.14148703]
 [ 1.2265248  -1.2042834  -0.91572493]
 [-2.5031376  -1.3834713   1.367332  ]], shape=(40000, 3), dtype=float32)
```
