### ISSUE TITLE
[TF 2.0 API Docs] tf.keras.layers.simpleRNN

### ISSUE THREAD

**Issue by brorro** [tensorflow/tensorflow#33794]
## URL(s) with the issue:
https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/keras/layers/SimpleRNN

### Clear description

The document mentions nothing about call argument `inputs` when it takes 
`[[batch, timesteps, feature], [batch, state]]`. In case of `inputs` is a list, the elements of `inputs[1:]` work as initial_state in each batch.

Example)
```
import tensorflow as tf
from tensorflow.keras.layers import *


class foo(tf.keras.Model):
    def __init__(self, rnn_units, dense_units, **kwargs):
        super().__init__(**kwargs)
        self.r1 = SimpleRNN(rnn_units)
        self.r2 = SimpleRNN(rnn_units)
        self.flat = tf.keras.layers.Flatten()
        self.d1 = Dense(rnn_units)
        self.d2 = Dense(dense_units)

    def call(self, inputs, **kwargs):

        x = self.r1(inputs)
        state = self.d1(self.flat(x))
        x = self.r2([inputs, state])
        x = self.d2(x)

        return x


train_input = tf.random.normal(shape=(6, 5, 10))
train_target = tf.random.normal(shape=(6, 8))

a = foo(10, 8)
a.compile(tf.keras.optimizers.SGD(0.01), loss=tf.keras.losses.MeanSquaredError())
a.fit(train_input, train_target)


b = SimpleRNN(10)(train_input)
state = Dense(10)(tf.reshape(b, (tf.shape(b)[0], -1)))
b = SimpleRNN(10)([train_input, state])
```

It also should be noted that `initial_state` argument should be `None` when `inputs` has states.
Other recurrent layers have same issue.

### Submit a pull request?
If this issue was not intended or a bug,
I'm planning to submit a pull request to fix the doc issue in a week. May i?

**Comment by jvishnuvardhan** [comment]
@brorro Are you interested in submitting a PR to update the docs? Please feel free to send PR and add a note here so that we can track. Thanks!

**Comment by brorro** [comment]
@jvishnuvardhan I will. Thank you

**Comment by SumanSudhir** [comment]
I am willing to take up this issue

**Comment by brorro** [comment]
@SumanSudhir Happy to hear that. I tried this but cannot find any documents to create my edited api docs.. it only creates unmodified one.

**Comment by Saduf2019** [comment]
@brorro 
Is this still an issue.

**Comment by jvishnuvardhan** [comment]
This is updated in recent TF version. Please check the page https://www.tensorflow.org/api_docs/python/tf/keras/layers/SimpleRNN

I am closing this issue as this was resolved. Please feel free to reopen if this is still an issue. Thanks!
