### ISSUE TITLE
Pull Requests: Ubuntu CC test is flakey

### ISSUE THREAD

**Issue by petewarden** [tensorflow/tensorflow#33798]
When testing pull requests the "Ubuntu CC" test seems to never(?) complete. See two examples here:

https://github.com/tensorflow/tensorflow/pull/33492
https://github.com/tensorflow/tensorflow/pull/32168

This makes it hard to for contributors to tell if their changes have broken the project, or if it's an unrelated flake (as it seems to be in these cases). This is the most obvious example of the problem, but we see many unrelated failures on the CI tests for PRs.

**Comment by lsgrep** [comment]
BTW, I think CI should run automatically after each commit.

**Comment by gunan** [comment]
Unfortunately, running CI automatically for each commit is not something we can do at the moment, due to the restrictions put on us by the service we are using.

**Comment by freddan80** [comment]
Main issue right now is that the test seems to hang. It never finishes. Many PR's have been in this limbo for weeks. There's no link or status indication for us to see what actually is going on, all we see is this:

![image](https://user-images.githubusercontent.com/15377492/68010677-81338d00-fc85-11e9-8570-bf3d9656bd05.png)

The same goes for most PR's here:
https://github.com/tensorflow/tensorflow/labels/comp%3Amicro

What exactly does this test do?

**Comment by lsgrep** [comment]
This one is also failing.  How can we fix this?  #33553

**Comment by av8ramit** [comment]
@gunan removed "Ubuntu CC" from the GitHub setting.
