### ISSUE TITLE
Does Tensorflowlite model support GPU boost on PC?

### ISSUE THREAD

**Issue by huangshaoguang** [tensorflow/tensorflow#33804]
Does Tensorflowlite model support GPU boost on PC? I can't find an example for supporting  GPU boost on PC, there're all examples for the mobile GPU boost or mobile CPU.

**Comment by ravikyram** [comment]
@huangshaoguang 
Can you go through the [link ](https://www.tensorflow.org/lite/performance/gpu)and see if it helps you.Thanks!

**Comment by ravikyram** [comment]
@huangshaoguang 

Can you please let us know any update on this issue. Thanks!

**Comment by ravikyram** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
