### ISSUE TITLE
Pull Requests: Map needed for request workflow

### ISSUE THREAD

**Issue by petewarden** [tensorflow/tensorflow#33802]
At the moment external contributors don't have any way of knowing what the lifecycle of a pull request is. We have [documentation on contributing code](https://www.tensorflow.org/community/contribute/code), but it's silent on the details of what happens to a request once it's been submitted. Chandni presented a fantastic flowchart at the contributor's summit today that would be a great foundation for documentation explaining the stages that a PR goes through.

This would help external contributors understand what they need to do to successfully submit code to the project, and combined with https://github.com/tensorflow/tensorflow/issues/33801 will give them the visibility they need to be effective TensorFlow developers.

/cc @freddan80 @jenselofsson

**Comment by freddan80** [comment]
Thanks for raising this issue! It would be great to see such a flowchart.

**Comment by mihaimaruseac** [comment]
![7XNWZfbTauSmBXn](https://user-images.githubusercontent.com/323199/188019356-b2b36a33-99a9-4c55-9c9b-a0c6f6a13eed.png)

**Comment by bhack** [comment]
I've additional review points at:
https://github.com/tensorflow/tensorflow/pull/57564

**Comment by SuryanarayanaY** [comment]
Hi @petewarden ,
As per your request for documenting a way of knowing the lifecycle of a pull request our team taken the action and PR already done and merged.I hope [this](https://github.com/tensorflow/tensorflow/blob/master/CONTRIBUTING.md) is the document you are looking for. Shall we close this issue ?
