### ISSUE TITLE
Pull Requests: Trusted committers should be able to approve

### ISSUE THREAD

**Issue by petewarden** [tensorflow/tensorflow#33800]
@jenselofsson is a trusted external committer from Arm, but at least some of the PRs that he has approved have required an additional Google review on GitHub. I would expect that he would be able to review and approve pull requests. For an example, see PR https://github.com/tensorflow/tensorflow/pull/33420

**Comment by Saduf2019** [comment]
@petewarden 
Is this still an issue, could you please verify if all review access is provided as requested for so we may move this to closed status.
