### ISSUE TITLE
TensorFlow pre-built package not available for download

### ISSUE THREAD

**Issue by rajeev-mirelz** [tensorflow/tensorflow#33807]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 16.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: NA
- TensorFlow installed from (source or binary): NA
- TensorFlow version: 2.0
- Python version: 3.6
- Installed using virtualenv? pip? conda?: pip using wheel
- Bazel version (if compiling from source): NA
- GCC/Compiler version (if compiling from source): NA
- CUDA/cuDNN version: 
- GPU model and memory:

**Describe the problem**
We are not able to download the wheels given on page -> https://www.tensorflow.org/install/pip. We are getting the following error when we try to get the *.whl in a browser:

<Error>
<Code>NoSuchKey</Code>
<Message>The specified key does not exist.</Message>
<Details>
No such object: tensorflow/linux/gpu/tensorflow_gpu-2.0.0-cp36-cp36m-linux_x86_64.whl
</Details>
</Error>

The issue occurs with all the links. We tried wget command on linux and get 404 error.
 
**Provide the exact sequence of commands / steps that you executed before running into the problem**

wget https://storage.googleapis.com/tensorflow/linux/gpu/tensorflow_gpu-2.0.0-cp36-cp36m-linux_x86_64.whl

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by jiyongjung0** [comment]
Oops, I've accidentally closed this issue. (Don't know why exactly yet...) Sorry for the inconvenience.

**Comment by MarkDaoust** [comment]
Strange! I meant to auto close it with  tensorflow/docs@89c6bbf56262. I'm not sure why github only noticed the copy in your fork... I do think this is fixed now.
