### ISSUE TITLE
InTopKV2 cannot use k as a tensor

### ISSUE THREAD

**Issue by 593618638** [tensorflow/tensorflow#33805]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
   Linux Ubuntu 16.04
- TensorFlow installed from (source or binary):
    binary
- TensorFlow version (use command below):
   TF 1.0

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
   I try to use k as a tensor in InTopKV2 however, it tells me the k must be a scalar.
   This is my code
`input = tf.constant([[0.1, 0.2, 0.3, 0.4], [0.5, 0.6, 0.7, 0.8]])
 k = tf.constant([2, 3])
 output = gen_nn_ops.in_top_kv2(input,[2,2],k)
`
![image](https://user-images.githubusercontent.com/22829190/67732568-c31ac400-fa36-11e9-91af-b7084f915877.png)
   
**Describe the expected behavior**
   K can be used as 1-D tensor
**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.
![image](https://user-images.githubusercontent.com/22829190/67732046-24419800-fa35-11e9-8b40-e72d436ea757.png)

**Comment by ravikyram** [comment]
@593618638 
Looks like code is incomplete.Please, provide simple standalone code, then it is easy for localizing the issue faster. Thanks !

**Comment by ravikyram** [comment]
@593618638 
Please, let us know any update on this issue. Thanks!

**Comment by ravikyram** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
