### ISSUE TITLE
KMeans module not found in TensorFlow 2

### ISSUE THREAD

**Issue by SaschaHeyer** [tensorflow/tensorflow#33818]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): no
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Mac 10.13.3
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: /
- TensorFlow installed from (source or binary): pip package manager
- TensorFlow version (use command below): 2.0.0
- Python version: 3.7.4
- Bazel version (if compiling from source): /
- GCC/Compiler version (if compiling from source): /
- CUDA/cuDNN version: /
- GPU model and memory: /

**Describe the current behavior**
I am following this TensorFlow documentation https://www.tensorflow.org/api_docs/python/tf/compat/v1/estimator/experimental/KMeans

When running the example I am getting the following error message:
```
AttributeError: module 'tensorflow_estimator.python.estimator.api._v2.estimator.experimental' has no attribute 'KMeans'
```

**Describe the expected behavior**
I expect a example which is possible to execute

**Code to reproduce the issue**
```
import numpy as np
import tensorflow as tf

num_points = 100
dimensions = 2
points = np.random.uniform(0, 1000, [num_points, dimensions])

def input_fn():
  return tf.train.limit_epochs(
      tf.convert_to_tensor(points, dtype=tf.float32), num_epochs=1)

num_clusters = 5
kmeans = tf.estimator.experimental.KMeans(
    num_clusters=num_clusters, use_mini_batch=False)

# train
num_iterations = 10
previous_centers = None
for _ in xrange(num_iterations):
  kmeans.train(input_fn)
  cluster_centers = kmeans.cluster_centers()
  if previous_centers is not None:
    print 'delta:', cluster_centers - previous_centers
  previous_centers = cluster_centers
  print 'score:', kmeans.score(input_fn)
print 'cluster centers:', cluster_centers

# map the input points to their clusters
cluster_indices = list(kmeans.predict_cluster_index(input_fn))
for i, point in enumerate(points):
  cluster_index = cluster_indices[i]
  center = cluster_centers[cluster_index]
  print 'point:', point, 'is in cluster', cluster_index, 'centered at', center
```

**Other info / logs**
I also tried to run it with the nightly version of TensorFlow 2, but I get the same results

**Comment by gowthamkpr** [comment]
@SaschaHeyer As mentioned by the error message and as you can see [here](https://www.tensorflow.org/api_docs/python/tf/estimator/experimental) the `tf.estimator.experimental` module doesn't have `KMeans`. 
Instead you can use `tf.compat.v1.estimator.experimental.KMeans` to accomplish the same task. You can find my github gist [here](https://colab.sandbox.google.com/gist/gowthamkpr/674ddf0ad388d3e29750e7c3200c67d9/untitled213.ipynb), where I used the same to accomplish the task.

**Comment by gowthamkpr** [comment]
@SaschaHeyer As mentioned by the error message and as you can see [here](https://www.tensorflow.org/api_docs/python/tf/estimator/experimental) the `tf.estimator.experimental` module doesn't have `KMeans`. 
Instead you can use `tf.compat.v1.estimator.experimental.KMeans` to accomplish the same task. You can find my github gist [here](https://colab.sandbox.google.com/gist/gowthamkpr/674ddf0ad388d3e29750e7c3200c67d9/untitled213.ipynb), where I used the same to accomplish the task.

**Comment by SaschaHeyer** [comment]
@gowthamkpr confirmed 👍
Thanks for the fast feedback appreciate it
