### ISSUE TITLE
Failure to install via 'pipenv install' with just "tensorflow==2.0.0" in requirements.txt

### ISSUE THREAD

**Issue by neilwarrack** [tensorflow/tensorflow#33817]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 16.04
- TensorFlow installed from (source or binary): binary
- TensorFlow version: 2.0.0
- Python version: 3.6.6
- Installed using virtualenv? pip? conda?: 'pipenv install' in a pyenv
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory: not sure 

**Describe the problem**

I'm sorry if this is the wrong place to post this but I'm having trouble installing Tensorflow 2.0.0. I posted this problem on Super User [here](https://superuser.com/questions/1496530/difficulty-installing-tensorflow-using-requirements-txt-and-pipenv-install?noredirect=1#) but I'm not sure if that was the best place.

I have managed to install Tensorflow on my computer but I'm working on a [shared project](https://gitlab.com/neilwarrack/spinformation) and we want it to be installed using the 'pipenv install' command along with a `requirements.txt` file. If I have a one line requirements.txt file that looks like this: `tensorflow==2.0.0`, then I see a lot of python traceback output which I have attached here (and can be found in the [Super User question I posted](https://superuser.com/questions/1496530/difficulty-installing-tensorflow-using-requirements-txt-and-pipenv-install?noredirect=1#))
[tensor_pipenv.log](https://github.com/tensorflow/tensorflow/files/3782673/tensor_pipenv.log)

I have the following possibly helpful versions/locations of things:
> $ which pip
> /home/nw/.pyenv/shims/pip
> $ which pipenv
> home/nw/.local/bin/pipenv
> $ which python
> /home/nw/.pyenv/shims/python
> $ python --version
> 3.6.6
> $ pip --version
> pip 19.3.1 from /usr/local/lib/python3.5/dist-packages/pip (python 3.5)

I see the same output if I try this with [our full requirements.txt](https://gitlab.com/neilwarrack/spinformation/blob/master/requirements.txt) file: 
[requirements_orig.txt](https://github.com/tensorflow/tensorflow/files/3782698/requirements_orig.txt)

**Comment by neilwarrack** [comment]
Someone suggested I upgrade setuptools. But I upgraded to 41.5.1 (latest) and it makes no difference.

**Comment by gowthamkpr** [comment]
@neilwarrack This is not a tensorflow issue. This issue related to `pipenv` and its been tracked [here](https://github.com/pypa/pipenv/issues/2791). Follow this [comment](https://github.com/pypa/pipenv/issues/2791#issuecomment-446037453) and it should work.

**Comment by Zerthick** [comment]
This is happening in one of my projects, for now you can just skip the pipenv install and use pip directly to install tensorflow, however this isn't an ideal solution.

**Comment by neilwarrack** [comment]
> @neilwarrack This is not a tensorflow issue. This issue related to `pipenv` and its been tracked [here](https://github.com/pypa/pipenv/issues/2791). Follow this [comment](https://github.com/pypa/pipenv/issues/2791#issuecomment-446037453) and it should work.

Hi! Thanks for your feedback!
:D
