### ISSUE TITLE
Please add the "reuse" parameter to tf.keras.layers.Conv2D()

### ISSUE THREAD

**Issue by Leonscrt** [tensorflow/tensorflow#33810]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using):
- Are you willing to contribute it (Yes/No):

No

**Describe the feature and the current behavior/state.**
Unable to implement complex weight sharing
**Will this change the current api? How?**
will do！Add the "reuse" parameter to tf.keras.layers.Conv2D()
**Who will benefit with this feature?**
Every user
**Any Other info.**
Why remove the ‘reuse’ parameter from tf.keras.layers.Conv2D(), or do you provide other ways to share weights? The algorithm implemented in 1.x is now not implemented in 2.0. If there is no better way to share weights, please let the ‘reuse’ parameter come back.

**Comment by tanzhenyu** [comment]
`reuse` is a tf legacy python layer thing, it's never part of keras layers, and especially not part of Tensorflow 2.0 because we removed variable scope and the reusing of variables.
To achieve weight sharing, either reuse the layer directly, or build customized layer that re-uses the weight
