### ISSUE TITLE
code and tutorial description mismatch on CNN

### ISSUE THREAD

**Issue by jramirezpr** [tensorflow/tensorflow#33824]
## URL(s) with the issue:
https://www.tensorflow.org/tutorials/images/cnn
## Description of issue (what needs changing):
Two mismatchs between output shape on model summary and tutorial:
1"To complete our model, you will feed the last output tensor from the convolutional base (of shape (3, 3, 64))"
should be changed to
To complete our model, you will feed the last output tensor from the convolutional base (of shape (4, 4, 64))
  
2."As you can see, our (3, 3, 64) outputs were flattened into vectors of shape (576) before going through two Dense layers."
This should be changed to 
"As you can see, our (4, 4, 64) outputs were flattened into vectors of shape (1024) before going through two Dense layers.

**Comment by jvishnuvardhan** [comment]
@jramirezpr Thanks for finding the typo's. We will update them. Thanks!

**Comment by lamberta** [comment]
Thanks for the report, can you please send a pull request?
That file is here in the tensorflow/docs repo: https://github.com/tensorflow/docs/blob/master/site/en/tutorials/images/cnn.ipynb
If you're unfamiliar with editing notebooks, see this section of the TensorFlow docs contributor guide: https://www.tensorflow.org/community/contribute/docs#interactive_notebooks

**Comment by copperwiring** [comment]
@lamberta I have sent a pull request for this issue which can be found [here](https://github.com/tensorflow/docs/pull/1238). Please let me know if you have any questions.

**Comment by copperwiring** [comment]
I am working on it right now. I have created a related issue [here](https://github.com/tensorflow/tensorflow/issues/34639).

@lamberta Let me know if I am missing something in the PR. If not, I'm working on both issues right now.

**Comment by ymodak** [comment]
This is fixed now. Thanks!
