### ISSUE TITLE
Calling train in SavedModelEstimator gives ValueError: At least two variables have the same name

### ISSUE THREAD

**Issue by EduardoDixo** [tensorflow/tensorflow#33826]
**System information**
- TensorFlow version (use command below): 1.12.0-rc2-3-ga6d8ffae09 1.12.0
- Python version: Python 3.6.9

**Describe the current behavior**

- Defining a model using tensorflow.keras
- Converting the compiled model to estimator
- Training estimator using train_and_evaluate
- Export all saved models for  "TRAIN", "EVAL" and "PREDICT"

When I create a SavedModelEstimator from the previous exported data, I am able to call evaluate and predict successfully. However, if I call the method train I get an error "ValueError: At least two variables have the same name: dense_1/bias/Adam)".

**I can warm-start sucessfully if I change the line in _get_grouped_variables to:** https://github.com/tensorflow/tensorflow/blob/9c52e7ce02532c22a79ae7139f37c663add4c90f/tensorflow/python/training/warm_starting_util.py#L349

`ops.GraphKeys.TRAINABLE_VARIABLES, scope=v)`

**Code to reproduce the issue**

```python
import tensorflow as tf
from tensorflow.keras.layers import Input, Dense, Dropout
from tensorflow.keras.models import Model
from tensorflow.keras.estimator import model_to_estimator
import keras.backend as K
import numpy as np
import os


def model_fn():
    # 10 features
    input_layer = Input(shape=(10,), name="inputs", dtype=tf.float32)
    dense_1 = Dense(units=10, activation="relu", name="dense_1")(input_layer)
    dense_2 = Dense(units=1, activation="linear", name="outputs",
                    dtype=tf.float32)(dense_1)
    model = Model(inputs=input_layer, outputs=dense_2)
    model.compile(optimizer=tf.train.AdamOptimizer(),
                  loss="mse")
    return model


def synthetic_input_fn(num_examples, num_features):
    # dummy data
    return tf.data.Dataset.from_tensor_slices(({"inputs": np.random.random((num_examples, num_features))}, np.random.randint(10, size=num_examples))) \
        .shuffle(512) \
        .batch(32) \
        .repeat(10)


if __name__ == "__main__":

    MODEL_DIR = "./model"
    SAVED_MODEL_DIR = os.path.join(MODEL_DIR, "saved")

    def cust_train_input_fn():
        return synthetic_input_fn(1000, 10)

    def cust_eval_input_fn():
        return synthetic_input_fn(100, 10)

    tf.logging.set_verbosity(tf.logging.INFO)

    # define model and convert to estimator
    model = model_fn()
    estimator = model_to_estimator(
        keras_model=model,
        model_dir=MODEL_DIR
    )

    train_spec = tf.estimator.TrainSpec(input_fn=cust_train_input_fn)
    eval_spec = tf.estimator.EvalSpec(input_fn=cust_eval_input_fn)

    # train and evaluate dummy model
    tf.estimator.train_and_evaluate(
        estimator=estimator,
        train_spec=train_spec,
        eval_spec=eval_spec
    )

    # export all modes
    feature_spec = {"inputs": tf.placeholder(tf.float64, (None, 10))}

    label_spec = tf.placeholder(dtype=tf.int64)

    serving_fn = tf.estimator.export.build_raw_serving_input_receiver_fn(feature_spec)
    training_fn = tf.contrib.estimator.build_raw_supervised_input_receiver_fn(feature_spec, label_spec)

    rcrv_fn_map = {
        tf.estimator.ModeKeys.TRAIN: training_fn,
        tf.estimator.ModeKeys.EVAL: training_fn,
        tf.estimator.ModeKeys.PREDICT: serving_fn
    }

    tf.contrib.estimator.export_all_saved_models(
        estimator,
        export_dir_base=SAVED_MODEL_DIR,
        input_receiver_fn_map=rcrv_fn_map
    )

    tf.keras.backend.clear_session()

    saved_estimator = tf.contrib.estimator.SavedModelEstimator(os.path.join(SAVED_MODEL_DIR, os.listdir(SAVED_MODEL_DIR)[0]))
    saved_estimator.train(cust_train_input_fn)
```

**Other info / logs**
Using TensorFlow backend.
INFO:tensorflow:Using default config.
INFO:tensorflow:Using the Keras model provided.
2019-10-29 14:26:59.280066: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
INFO:tensorflow:Using config: {'_model_dir': './model', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': allow_soft_placement: true
graph_options {
  rewrite_options {
    meta_optimizer_iterations: ONE
  }
}
, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 100, '_train_distribute': None, '_device_fn': None, '_protocol': None, '_eval_distribute': None, '_experimental_distribute': None, '_service': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x62b766be0>, '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}
INFO:tensorflow:Not using Distribute Coordinator.
INFO:tensorflow:Running training and evaluation locally (non-distributed).
INFO:tensorflow:Start train and evaluate loop. The evaluate will happen after every checkpoint. Checkpoint frequency is determined based on RunConfig arguments: save_checkpoints_steps None or save_checkpoints_secs 600.
INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Warm-starting with WarmStartSettings: WarmStartSettings(ckpt_to_initialize_from='./model/keras/keras_model.ckpt', vars_to_warm_start='.*', var_name_to_vocab_info={}, var_name_to_prev_var_name={})
INFO:tensorflow:Warm-starting from: ('./model/keras/keras_model.ckpt',)
INFO:tensorflow:Warm-starting variable: dense_1/kernel; prev_var_name: Unchanged
INFO:tensorflow:Warm-starting variable: dense_1/bias; prev_var_name: Unchanged
INFO:tensorflow:Warm-starting variable: outputs/kernel; prev_var_name: Unchanged
INFO:tensorflow:Warm-starting variable: outputs/bias; prev_var_name: Unchanged
INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Saving checkpoints for 0 into ./model/model.ckpt.
INFO:tensorflow:loss = 32.57418, step = 1
INFO:tensorflow:global_step/sec: 1201.8
INFO:tensorflow:loss = 24.11268, step = 101 (0.083 sec)
INFO:tensorflow:global_step/sec: 1799.1
INFO:tensorflow:loss = 12.514932, step = 201 (0.056 sec)
INFO:tensorflow:global_step/sec: 1810.48
INFO:tensorflow:loss = 9.915621, step = 301 (0.055 sec)
INFO:tensorflow:Saving checkpoints for 320 into ./model/model.ckpt.
INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Starting evaluation at 2019-10-29-14:27:00
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from ./model/model.ckpt-320
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Evaluation [10/100]
INFO:tensorflow:Evaluation [20/100]
INFO:tensorflow:Evaluation [30/100]
INFO:tensorflow:Evaluation [40/100]
INFO:tensorflow:Finished evaluation at 2019-10-29-14:27:00
INFO:tensorflow:Saving dict for global step 320: global_step = 320, loss = 8.093195
INFO:tensorflow:Saving 'checkpoint_path' summary for global step 320: ./model/model.ckpt-320
INFO:tensorflow:Loss for final step: 10.114872.
INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Signatures INCLUDED in export for Classify: None
INFO:tensorflow:Signatures INCLUDED in export for Regress: None
INFO:tensorflow:Signatures INCLUDED in export for Predict: None
INFO:tensorflow:Signatures INCLUDED in export for Train: ['train']
INFO:tensorflow:Signatures INCLUDED in export for Eval: None
WARNING:tensorflow:Export includes no default signature!
INFO:tensorflow:Restoring parameters from ./model/model.ckpt-320
WARNING:tensorflow:From /anaconda3/envs/tf-abalone/lib/python3.6/site-packages/tensorflow/python/estimator/estimator.py:1044: calling SavedModelBuilder.add_meta_graph_and_variables (from tensorflow.python.saved_model.builder_impl) with legacy_init_op is deprecated and will be removed in a future version.
Instructions for updating:
Pass your op to the equivalent parameter main_op instead.
INFO:tensorflow:Assets added to graph.
INFO:tensorflow:No assets to write.
INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Signatures INCLUDED in export for Classify: None
INFO:tensorflow:Signatures INCLUDED in export for Regress: None
INFO:tensorflow:Signatures INCLUDED in export for Predict: None
INFO:tensorflow:Signatures INCLUDED in export for Train: None
INFO:tensorflow:Signatures INCLUDED in export for Eval: ['eval']
WARNING:tensorflow:Export includes no default signature!
INFO:tensorflow:Restoring parameters from ./model/model.ckpt-320
WARNING:tensorflow:From /anaconda3/envs/tf-abalone/lib/python3.6/site-packages/tensorflow/python/estimator/estimator.py:1046: calling SavedModelBuilder.add_meta_graph (from tensorflow.python.saved_model.builder_impl) with legacy_init_op is deprecated and will be removed in a future version.
Instructions for updating:
Pass your op to the equivalent parameter main_op instead.
INFO:tensorflow:Assets added to graph.
INFO:tensorflow:No assets to write.
INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Signatures INCLUDED in export for Classify: None
INFO:tensorflow:Signatures INCLUDED in export for Regress: None
INFO:tensorflow:Signatures INCLUDED in export for Predict: ['serving_default']
INFO:tensorflow:Signatures INCLUDED in export for Train: None
INFO:tensorflow:Signatures INCLUDED in export for Eval: None
INFO:tensorflow:Restoring parameters from ./model/model.ckpt-320
INFO:tensorflow:Assets added to graph.
INFO:tensorflow:No assets to write.
INFO:tensorflow:SavedModel written to: ./model/saved/temp-b'1572359223'/saved_model.pb
INFO:tensorflow:Using default config.
WARNING:tensorflow:Using temporary folder as model directory: /var/folders/8s/tjdwdq296s5fdljp3p6jd9z40000gn/T/tmp7c0vhh49
INFO:tensorflow:Using config: {'_model_dir': '/var/folders/8s/tjdwdq296s5fdljp3p6jd9z40000gn/T/tmp7c0vhh49', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': allow_soft_placement: true
graph_options {
  rewrite_options {
    meta_optimizer_iterations: ONE
  }
}
, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 100, '_train_distribute': None, '_device_fn': None, '_protocol': None, '_eval_distribute': None, '_experimental_distribute': None, '_service': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x1c316e6208>, '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}
INFO:tensorflow:Checking available modes for SavedModelEstimator.
INFO:tensorflow:Available modes for Estimator: ['train', 'eval', 'infer']
INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Warm-starting with WarmStartSettings: WarmStartSettings(ckpt_to_initialize_from='./model/saved/1572359223/variables/variables', vars_to_warm_start=['dense_1/bias', 'dense_1/bias/Adam', 'dense_1/bias/Adam_1', 'dense_1/kernel', 'dense_1/kernel/Adam', 'dense_1/kernel/Adam_1', 'global_step', 'outputs/bias', 'outputs/bias/Adam', 'outputs/bias/Adam_1', 'outputs/kernel', 'outputs/kernel/Adam', 'outputs/kernel/Adam_1', 'training/TFOptimizer/beta1_power', 'training/TFOptimizer/beta2_power'], var_name_to_vocab_info={}, var_name_to_prev_var_name={})
INFO:tensorflow:Warm-starting from: ('./model/saved/1572359223/variables/variables',)
INFO:tensorflow:Warm-starting variable: dense_1/bias; prev_var_name: Unchanged
INFO:tensorflow:Warm-starting variable: dense_1/bias/Adam; prev_var_name: Unchanged
Traceback (most recent call last):
  File "main.py", line 83, in <module>
    saved_estimator.train(cust_train_input_fn)
  File "/anaconda3/envs/tf-abalone/lib/python3.6/site-packages/tensorflow/python/estimator/estimator.py", line 354, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "/anaconda3/envs/tf-abalone/lib/python3.6/site-packages/tensorflow/python/estimator/estimator.py", line 1207, in _train_model
    return self._train_model_default(input_fn, hooks, saving_listeners)
  File "/anaconda3/envs/tf-abalone/lib/python3.6/site-packages/tensorflow/python/estimator/estimator.py", line 1241, in _train_model_default
    saving_listeners)
  File "/anaconda3/envs/tf-abalone/lib/python3.6/site-packages/tensorflow/python/estimator/estimator.py", line 1360, in _train_with_estimator_spec
    warm_starting_util.warm_start(*self._warm_start_settings)
  File "/anaconda3/envs/tf-abalone/lib/python3.6/site-packages/tensorflow/python/training/warm_starting_util.py", line 463, in warm_start
    _warm_start_var(variable, ckpt_to_initialize_from, prev_var_name)
  File "/anaconda3/envs/tf-abalone/lib/python3.6/site-packages/tensorflow/python/training/warm_starting_util.py", line 170, in _warm_start_var
    current_var_name = _infer_var_name(var)
  File "/anaconda3/envs/tf-abalone/lib/python3.6/site-packages/tensorflow/python/training/warm_starting_util.py", line 142, in _infer_var_name
    name_to_var_dict = saver.BaseSaverBuilder.OpListToDict(var)
  File "/anaconda3/envs/tf-abalone/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 572, in OpListToDict
    name)
ValueError: At least two variables have the same name: dense_1/bias/Adam

**Comment by oanush** [comment]
Issue replicating for TF 1.12,kindly find the [gist](https://colab.sandbox.google.com/gist/oanush/7f3781dbd355dcf9915f96c2c1405944/33826.ipynb) of colab.Thanks!

**Comment by EduardoDixo** [comment]
Forgot to mention that there is an issue when running the same code in TensorFlow 1.13, 1.14 and 1.15, in the SavedModelEstimator call to train, raising:

`ValueError: Dimension 0 in both shapes must be equal, but are 0 and 1. Shapes are [0] and [1]. for 'loss/outputs_loss/weighted_loss/broadcast_weights/assert_broadcastable/is_valid_shape/has_valid_nonscalar_shape/has_invalid_dims/DenseToDenseSetOperation' (op: 'DenseToDenseSetOperation') with input shapes: [0,1], [1,2].`

Should this be a new issue?

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.
