### ISSUE TITLE
tf.contrib.rnn.OutputProjectionWrapper

### ISSUE THREAD

**Issue by ucasiggcas** [tensorflow/tensorflow#33822]
hi,
In tf 1.14.0,there is no new API for the function,
could you help me ?I want translate the Op in tflite .
thx

**Comment by gowthamkpr** [comment]
Can you please be specific of what your issue is @ucasiggcas ?

**Comment by gowthamkpr** [comment]
Closing this issue as it has been awaiting response for more than 3 weeks. Please add additional comments and we can open this issue again. Thanks!
