### ISSUE TITLE
Missing TF 2.0 low-level API guide

### ISSUE THREAD

**Issue by chrism0dwk** [tensorflow/tensorflow#33823]
## URL(s) with the issue:

https://www.tensorflow.org/guide

## Description of issue (what needs changing):

In the TF1.* docs, a very helpful low-level API guide was provided which helped those of us interested in using TensorFlow for applications other than NN style models.  This appears to be entirely missing from the TF 2.0 documentation.  Is this omission on purpose, and if so how do we teach people how to use the low-level API?

Thanks,

Chris

**Comment by dexception** [comment]
Stop wasting your time with Tensorflow. 
I have too wasted my time. Nobody listens.
Move to PyTorch.

**Comment by yashk2810** [comment]
We have this guide now: https://www.tensorflow.org/tutorials/customization/performance

But we are working on more.

**Comment by zealotpb** [comment]
Same question.
Why are the low-level guides removed? I'm not a Keras idiot...

**Comment by miguelalba96** [comment]
if you want to use the low level API of tensorflow for model construction try to see the documentation of tf.Module and @ tf. function, here is an example of how to create one conv layer

```def weights(name, shape, mean=0.0, stddev=0.02):
    var = tf.Variable(tf.random_normal_initializer(mean=mean, stddev=stddev)(shape), name=name)
    return var```
then: 

```class conv_layer(tf.Module):
    def __init__(self, filters, norm, act_type='ReLu', name=None):
        super(conv_layer, self).__init__(name=name)
        self.filters = filters
        self.norm = norm
        self.act_type = act_type
        with self.name_scope:
            self.normalization = type_norm(norm) # another class using tf.Module

    @tf.Module.with_name_scope
    def __call__(self, input):
        if not hasattr(self, 'weights'):
            self.weights = weights('weights', (7, 7, input.get_shape()[-1], self.filters))
        padded = tf.pad(input, [[0, 0], [3, 3], [3, 3], [0, 0]], 'REFLECT')
        conv = tf.nn.conv2d(padded, self.weights, strides=[1, 1, 1, 1], padding='VALID')

        normalized = self.normalization(conv)

        if self.act_type == 'ReLu':
            output = tf.nn.relu(normalized)
        elif self.act_type == 'tanh':
            output = tf.nn.tanh(normalized)
        return output``` 

write the architecture in the same way

**Comment by Saduf2019** [comment]
@chrism0dwk 
Is this still an issue.

**Comment by chrism0dwk** [comment]
@Saduf2019 Yes, I believe it is now covered in the new Tensorflow Basics section of the TF [Guide](https://tensorflow.org/guide).  Very many thanks for the new resource!

**Comment by Saduf2019** [comment]
@chrism0dwk 
Thanks for your update.
