### ISSUE TITLE
Train in Keras with Stateless CuDNN GRU and infer using tensorflow with stateful CuDNN GRU

### ISSUE THREAD

**Issue by dsp-ml** [tensorflow/tensorflow#33829]
Hi

I am facing a problem with using Stateful and Steteless CuDNN GRU

I trained my model in Keras with CuDNN GRU's using let's say 1000 time steps and stateful=False. 

During inference, to keep the model real-time, I changed the time_steps to 1, and stateful=true to load the model and it's weights. I converted this model to tensorflow protobuf using convert_variables_to_constants() function to freeze the graph and write_graph() to write it to a protobuf file.

The problem I am facing currently is that I am getting same results whether or not stateful = True or False during inference. which means I am missing something while converting keras model to tensorflow model. Is there any special consideration needed with the conversion process?

While running tensorflow session, along with the output, do I need to get states of all the CuDNN GRU layers and pass in these states with the next input? If yes, how can I get these states from the graph. It's not clear from the nodes of cudnn layer, which of it might contain state information. 

Or is there something very fundamental I am missing here? Any help is very much appreciated. 

Tensorflow version : 1.14.0
Keras version : 2.2.4

Thanks

**Comment by ymodak** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.
Thanks!
