### ISSUE TITLE
Typo in TensorFlow Core Tutorials - Image classification

### ISSUE THREAD

**Issue by taeklee** [tensorflow/tensorflow#33830]
## URL(s) with the issue:
https://github.com/tensorflow/docs/blob/master/site/en/tutorials/images/classification.ipynb

## Description of issue (what needs changing):
Typo

### Clear description
```
Create the model
The model consists of three convolution blocks with a max pool layer in each of them. There's a fully connected layer with 512 units on top of it thatr is activated by a relu activation function. 
```
In Create the model section,
```thatr``` should be ```that```

```
Create the model
The model consists of three convolution blocks with a max pool layer in each of them. There's a fully connected layer with 512 units on top of it that is activated by a relu activation function. 
```

**Comment by lamberta** [comment]
Thanks for the report.
Can you please make a pull request? This doc lives here: https://github.com/tensorflow/docs/blob/master/site/en/tutorials/images/classification.ipynb
If not familiar, check out this section in the [TensorFlow doc contributor guide](https://www.tensorflow.org/community/contribute/docs#interactive_notebooks).

**Comment by taeklee** [comment]
Thank you for review the issue.
Can you please check out the pull request I made? https://github.com/tensorflow/docs/pull/1148

**Comment by lamberta** [comment]
This was merged. Thanks
