### ISSUE TITLE
tensorflow.linalg.norm document missing

### ISSUE THREAD

**Issue by fsx950223** [tensorflow/tensorflow#33839]
Thank you for submitting a TensorFlow documentation issue. Per our GitHub
policy, we only address code/doc bugs, performance issues, feature requests, and
build/installation issues on GitHub.

The TensorFlow docs are open source! To get involved, read the documentation
contributor guide: https://www.tensorflow.org/community/contribute/docs

## URL(s) with the issue:
https://github.com/tensorflow/tensorflow/blob/1cf0898dd4331baf93fe77205550f2c2e6c90ee5/tensorflow/python/ops/linalg_ops.py#L426

## Description of issue (what needs changing):
I can't find ```tensorflow.linalg.norm``` on official v2.0 API document

**Comment by nikochiko** [comment]
Because ```tf.linalg.norm``` is same  as ```tf.norm```, the documentation is shared with ```tf.norm``` https://www.tensorflow.org/api_docs/python/tf/norm

**Comment by fsx950223** [comment]
> Because `tf.linalg.norm` is same as `tf.norm`, the documentation is shared with `tf.norm` https://www.tensorflow.org/api_docs/python/tf/norm

Thanks
