### ISSUE TITLE
How can I convert outputs or tflite tensors to swift multi-dimensional arrays to be able to perform mathematical computations on them?

### ISSUE THREAD

**Issue by joker2017** [tensorflow/tensorflow#33832]
I am running posenet on swift with tflite.
The model has multiple output arrays with the following dimensions:
1x14x14x17, 1x14x14x34, 1x14x14x32, 1x14x14x32

How can I convert outputs or tflite tensors to swift ios multi-dimensional arrays to be able to perform mathematical computations on them?

[There was a similar question for java](https://github.com/tensorflow/tensorflow/issues/25841)

**Comment by joker2017** [comment]
**help me please**

**Comment by joker2017** [comment]
is it possible now?

**Comment by norangLemon** [comment]
Hi, @joker2017 
Sorry for late answer.

In Swift, `Tensor` is implemented like [this][Swift Tensor].
To perform mathematical computations on the data of a `Tensor`, you can access to the [`Data`] of a tensor.

However, dealing with [`Data`][Data] type is a bit tricky.
Instead, you can convert the [`Data`] type to the other data type, such as [`Array`].

You can convert [`Data`] to the single dimensional [`Array`], as well as multi dimensional [`Array`].
If you choose to convert this as a single dimensional [`Array`], you can take a look at [PoseNet] example.
In [the example][PoseNet], it implemented [FlatArray] structure to convert a [`Tensor`][Swift Tensor].
You can access to the each element like `tensorData[1, 13, 12, 15]`.
The use case is in the [`ModelDataHandler.swift`][PoseNet FlatArray].


[Swift Tensor]: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/experimental/swift/Sources/Tensor.swift
[`Data`]: https://developer.apple.com/documentation/foundation/data
[`Array`]: https://developer.apple.com/documentation/swift/array
[PoseNet]: https://github.com/tensorflow/examples/tree/master/lite/examples/posenet/ios
[PoseNet FlatArray]: https://github.com/tensorflow/examples/blob/master/lite/examples/posenet/ios/PoseNet/ModelDataHandler/ModelDataHandler.swift#L187
[FlatArray]: https://github.com/tensorflow/examples/blob/master/lite/examples/posenet/ios/PoseNet/Extensions/TFLiteExtension.swift#L43
