### ISSUE TITLE
Support SelectV2 in grappler layout transposer

### ISSUE THREAD

**Issue by lgeiger** [tensorflow/tensorflow#33847]
This issue is extracted from the conversation in https://github.com/tensorflow/tensorflow/pull/33694#issuecomment-546124837

 `SelectV2` currently isn't added to `grappler/op_types.cc`
https://github.com/tensorflow/tensorflow/blob/543f61dcab11cc3461c97dcdce660536e3e498d7/tensorflow/core/grappler/op_types.cc#L460
which is used in the layout optimizer?
https://github.com/tensorflow/tensorflow/blob/543f61dcab11cc3461c97dcdce660536e3e498d7/tensorflow/core/grappler/optimizers/generic_layout_optimizer_transposer_factory.cc#L95-L97

Ideally the layout optimizer would support `SelectV2` as well so it should be added to `grappler/op_types.cc`.

@reedwm Mentioned that in `SelectV2`, the inputs do not need to be the same shape but only need to be broadcastable to each other, which might be problematic for the layout optimizer. @andyly, do you know?

**Comment by andyly** [comment]
Currently the layout optimizer checks for if the first input (the cond) to Select is rank 0, 1, or 4. There is also an assumption that the other inputs (t and e in the op def) are rank 4. There will need to be some changes required for the other inputs in terms of checking if transposes should be added, and which inputs to add transposes to.

**Comment by lgeiger** [comment]
Thanks for the answer, that's good to know. I won't have time anytime soon to send a PR for this, so feel free to take over or close this issue.

**Comment by lgeiger** [comment]
Closing, since it looks like support for this was added in 7ea9c329266e365f667cfb75965543c08bac7476
