### ISSUE TITLE
Outdated doc for tf.keras.Model.save

### ISSUE THREAD

**Issue by durandg12** [tensorflow/tensorflow#33856]
## URL(s) with the issue:

[https://www.tensorflow.org/api_docs/python/tf/keras/Model#save](https://www.tensorflow.org/api_docs/python/tf/keras/Model#save)

## Description of issue (what needs changing):

The following sentence is outdated and recommends to use a deprecated method:

> The 'tf' option is currently disabled (use [tf.keras.experimental.export_saved_model](https://www.tensorflow.org/api_docs/python/tf/keras/experimental/export_saved_model) instead).

**Comment by nikochiko** [comment]
Has this issue already been taken up? I can make the fix otherwise.

**Comment by imskr** [comment]
I want to work on this issue!

**Comment by jvishnuvardhan** [comment]
@imskr If @nikochiko is not working on it, then you can work on it. If you have already worked on, then submit a PR to update the docs. Thanks!

**Comment by nikochiko** [comment]
@jvishnuvardhan @imskr I have done the editing. A few additions and formatting corrections were also required there. Also I found maybe a bug in the code for which I will reference an issue here in a edited comment soon.

**Comment by nikochiko** [comment]
The PR has been merged. This issue can be closed. @jvishnuvardhan @durandg12

**Comment by nikochiko** [comment]
The docs have been updated. Changes are already visible in rc 2.1 API docs: https://www.tensorflow.org/versions/r2.1/api_docs/python/tf/keras/Model#save
This issue can be closed. @jvishnuvardhan @durandg12
