### ISSUE TITLE
Ubuntu 16.04

### ISSUE THREAD

**Issue by sammoes** [tensorflow/tensorflow#3386]
On Ubuntu 16.04 (gcc default is 5.3), 
apt-get install cuda-toolkit installs the library files in usr/lib/x86_64-linux-gnu
tensorflow prefers them in usr/local/cuda
.configure allows you to change the directory

cuDNN installs in /usr/local/cuda (more or less by default)
telling configure that cuDNN is in usr/local/cuda makes tf look for cuda in usr/local/cuda

Before you know it, you have cuda versions, nvidia versions, cuda folders etc. all over the place but tf not knowing any GPU!!

**Comment by yaroslavvb** [comment]
I have not had success getting TensorFlow GPU to work through apt-get install cuda-toolkit, hence I always install cuda through tarbar from NVidia website

**Comment by sammoes** [comment]
Yeah, I understand, but in 16.04, it is possible to set the default gcc to 4.9 to be able to build the .run file,  however, I ran into complaints about the 5.3 compiler again when building tf from source after that.  With the cuda .deb, tf doesn't know the gpu:0 the .deb possibly overwrites the nvidia 367 driver (partially) (or it lets you select whether to do so, it comes with 361 long term supported version I think).

At least, please update the TF website, the ubuntu install instruction is outdated, especially wrt 16.04 but also wrt cuDNN, because cuDNN 5 is no longer a  release candidate. It just gets spectacularly confusing, just following those instructions to the letter, they seem outdated for 16.04. You'll see SO full with questions again soon, just because versions are progressing and not thoroughly tested or explained.

**Comment by sammoes** [comment]
I get the gpu:0 now through the nvidia-docker solution
Please leave it open until the website is updated.

**Comment by concretevitamin** [comment]
@vrv: who is the point of contact of `os_setup.md`?

**Comment by vrv** [comment]
there is no point of contact per-se, anyone can send a PR to add information there if it is suitably generic for an important class of systems that we support

**Comment by yaroslavvb** [comment]
Related issue #2897

**Comment by wagonhelm** [comment]
I just installed Cuda using apt-get and copy and pasted all the CudNN files into the usr folder and using the pip GPU installation everything worked dandy.

I walked through the whole process here.
https://www.youtube.com/watch?v=HM57GyqwGxA

**Comment by gunan** [comment]
Looks like this issue was resolved.
Also there has been many updates to our scripts and documentation, so I think this issue got resolved, but it was not closed.
Please reopen if you still run into this problem.
