### ISSUE TITLE
tf 1.14 compile error with gcc 4.9.2

### ISSUE THREAD

**Issue by goldbalance** [tensorflow/tensorflow#33861]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): RHEL
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): source
- TensorFlow version: 1.14.0
- Python version: 2.7
- Installed using virtualenv? pip? conda?: 
- Bazel version (if compiling from source): 0.25.0
- GCC/Compiler version (if compiling from source): 4.9.2
- CUDA/cuDNN version: 
- GPU model and memory:

**Describe the problem**
`[944 / 2,400] Compiling external/protobuf_archive/src/google/protobuf/compiler/java/java_message_field_lite.cc [for host]; 0s local ... (47 actions running)
ERROR: /home/admin/tensorflow-1.14.0/tensorflow/lite/kernels/BUILD:403:1: C++ compilation of rule '//tensorflow/lite/kernels:lstm_eval' failed (Exit 1)
In file included from external/eigen_archive/Eigen/Core:161:0,
                 from ./third_party/eigen3/Eigen/Core:1,
                 from tensorflow/lite/kernels/lstm_eval.cc:23:
external/eigen_archive/Eigen/src/Core/arch/AVX512/PacketMath.h:124:1: error: 'Packet Eigen::internal::pset1(const typename Eigen::internal::unpacket_traits<Packet>::type&) [with Packet = __vector(16) float; typename Eigen::internal::unpacket_traits<Packet>::type = float]' conflicts with a previous declaration
 }
 ^
In file included from external/eigen_archive/Eigen/Core:158:0,
                 from ./third_party/eigen3/Eigen/Core:1,
                 from tensorflow/lite/kernels/lstm_eval.cc:23:
external/eigen_archive/Eigen/src/Core/arch/AVX/PacketMath.h:130:41: note: previous declaration 'Packet Eigen::internal::pset1(const typename Eigen::internal::unpacket_traits<Packet>::type&) [with Packet = __vector(8) float; typename Eigen::internal::unpacket_traits<Packet>::type = float]'
 template<> EIGEN_STRONG_INLINE Packet8f pset1<Packet8f>(const float&  from) { return _mm256_set1_ps(from); }
                                         ^
In file included from external/eigen_archive/Eigen/Core:161:0,
                 from ./third_party/eigen3/Eigen/Core:1,
                 from tensorflow/lite/kernels/lstm_eval.cc:23:
external/eigen_archive/Eigen/src/Core/arch/AVX512/PacketMath.h:122:31: note: -fabi-version=6 (or =0) avoids this error with a change in mangling
 EIGEN_STRONG_INLINE Packet16f pset1<Packet16f>(const float& from) {
                               ^
external/eigen_archive/Eigen/src/Core/arch/AVX512/PacketMath.h:128:1: error: 'Packet Eigen::internal::pset1(const typename Eigen::internal::unpacket_traits<Packet>::type&) [with Packet = __vector(8) double; typename Eigen::internal::unpacket_traits<Packet>::type = double]' conflicts with a previous declaration
 }
 ^
In file included from external/eigen_archive/Eigen/Core:158:0,
                 from ./third_party/eigen3/Eigen/Core:1,
                 from tensorflow/lite/kernels/lstm_eval.cc:23:
external/eigen_archive/Eigen/src/Core/arch/AVX/PacketMath.h:131:41: note: previous declaration 'Packet Eigen::internal::pset1(const typename Eigen::internal::unpacket_traits<Packet>::type&) [with Packet = __vector(4) double; typename Eigen::internal::unpacket_traits<Packet>::type = double]'
 template<> EIGEN_STRONG_INLINE Packet4d pset1<Packet4d>(const double& from) { return _mm256_set1_pd(from); }
                                         ^
In file included from external/eigen_archive/Eigen/Core:161:0,
                 from ./third_party/eigen3/Eigen/Core:1,
                 from tensorflow/lite/kernels/lstm_eval.cc:23:
external/eigen_archive/Eigen/src/Core/arch/AVX512/PacketMath.h:126:30: note: -fabi-version=6 (or =0) avoids this error with a change in mangling
 EIGEN_STRONG_INLINE Packet8d pset1<Packet8d>(const double& from) {
                                                           ^
external/eigen_archive/Eigen/src/Core/arch/AVX512/PacketMath.h:132:1: error: 'Packet Eigen::internal::pset1(const typename Eigen::internal::unpacket_traits<Packet>::type&) [with Packet = __vector(8) long long int; typename Eigen::internal::unpacket_traits<Packet>::type = int]' conflicts with a previous declaration
 }
 ^`
**Provide the exact sequence of commands / steps that you executed before running into the problem**

bazel build --config=opt --config=mkl --cxxopt=-mavx --cxxopt=-mavx2 --cxxopt=-msse3 --cxxopt=-msse4.1 --cxxopt=-msse4.2 --cxxopt=-mfma --copt=-mavx --copt=-mavx2 --copt=-msse3 --copt=-msse4.1 --copt=-msse4.2 --copt=-mfma --cxxopt=-fabi-version=6 --copt=-fabi-version=6 //tensorflow/tools/pip_package:build_pip_package

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by goldbalance** [comment]
I built successfully with gcc 4.8.5, i make sure that it is relate to gcc version

**Comment by gadagashwini** [comment]
@goldbalance, Please take a look at the Tensorflow [tested build configuration](https://www.tensorflow.org/install/source#tested_build_configurations).Tensorflow 1.14.0 supports GCC 4.8. Thanks!

**Comment by goldbalance** [comment]
> @goldbalance, Please take a look at the Tensorflow [tested build configuration](https://www.tensorflow.org/install/source#tested_build_configurations).Tensorflow 1.14.0 supports GCC 4.8. Thanks!

I see it. Thanks!. But param simd is only supportted with gcc 4.9 or above. Hope your supporting.

**Comment by angerson** [comment]
Thanks for the report. As mentioned, TF 1.14.0 only officially supports GCC 4.8. If you'd like to use those newer options, please build at master, which supports GCC 7.3.1. Thanks!
