### ISSUE TITLE
How does the graphdef file provided in simple audio recognition tutorial can be converted to tflite file?

### ISSUE THREAD

**Issue by vihari1729** [tensorflow/tensorflow#33867]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):Linux Ubuntu 16.04
- TensorFlow installed from (source or binary):source
- TensorFlow version (or github SHA if from [source):tensorflow 1.14

**Provide the text output from tflite_convert**

```
# Copy and paste here
```ValueError: std_dev and mean must be defined when inference_input_type is QUANTIZED_UINT8.

where i dont know mean and std_dev values 

Also, please include a link to a GraphDef or the model if possible.
https://github.com/tensorflow/docs/blob/master/site/en/r1/tutorials/sequences/audio_recognition.md
**Any other info / logs**

Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.
tflite_convert \
--output_file=model.tflite \
--graph_def_file=/home/unizen/Downloads/my_frozen_graph.pb \
--inference_type=QUANTIZED_UINT8 \
--input_shapes=16000,1:  \
--input_arrays=decoded_sample_data,decoded_sample_data:1 \
--output_arrays=labels_softmax \

**Comment by ravikyram** [comment]
Can you please go through [link1](https://stackoverflow.com/questions/57272861/i-have-problem-converting-pb-file-to-tflite-file) and see if it helps you.Thanks!

**Comment by vihari1729** [comment]
what are the mean and std dev values of the training network. Could you also verify the input and output arrays @ravikyram

**Comment by vihari1729** [comment]
Any update regarding the comment?

**Comment by haozha111** [comment]
From the user guide: https://www.tensorflow.org/lite/convert/quantization

The std_dev and mean need to be provided otherwise the model doesn't know how to map from uint8 to float ranges. Adding Alan for further suggestions.

**Comment by vihari1729** [comment]
> From the user guide: https://www.tensorflow.org/lite/convert/quantization
> 
> The std_dev and mean need to be provided otherwise the model doesn't know how to map from uint8 to float ranges. Adding Alan for further suggestions.

Thanks for the reply man. But i didn't do training with my code.I followed the tutorial in the below link for the creation of graphdef file
https://github.com/tensorflow/docs/blob/master/site/en/r1/tutorials/sequences/audio_recognition.md

**Comment by vihari1729** [comment]
Any update?
