### ISSUE TITLE
Windows fatal exception: access violation with tensorboard

### ISSUE THREAD

**Issue by sutongkui** [tensorflow/tensorflow#33864]
I met a [strange problem]( https://stackoverflow.com/questions/58636880/windows-fatal-exception-access-violation-with-tensorboard), It works well before, then I move all anaconda files from one disk to another SSD, the error occurs. I have tried to remove all the anaconda file and reinstall the whole thing, but still nothing.

**Comment by ymodak** [comment]
duplicate https://github.com/tensorflow/tensorboard/issues/2399

**Comment by sutongkui** [comment]
I solved this, uninstall tf1.4 and install 1.13, then it works well
