### ISSUE TITLE
TensorFlow GPU version uses Eigen for convolution.

### ISSUE THREAD

**Issue by yunxiangz** [tensorflow/tensorflow#33865]
I am debugging the Tensorflow conv_ops_test in the core/kernel folder via VS code. 
I found that TensorFlow uses Eigen for GPU version convolution. Not sure why coz I heard that it should call cuBLAS library for GPU things. Hope someone could help me.

The settings and commands that I used are as follows:

Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 16.04
Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: No
TensorFlow installed from (source or binary): Source
TensorFlow version (use command below): 1.4
Python version: 3.5
Bazel version (if compiling from source): 0.54
GCC/Compiler version (if compiling from source): 5.5
CUDA/cuDNN version: 8/6
GPU model and memory: GTX 1080Ti
Exact command to reproduce: bazel build --spawn_strategy=standalone --verbose_failures --config=cuda --copt="-fPIC" --copt="-DNDEBUG" --local_resources 11048,2.0,2.0 -c dbg --copt -g //tensorflow/tools/pip_package:build_pip_package
and then: bazel build --config=cuda -c dbg --copt -g //tensorflow/core/kernels:conv_ops_test

**Comment by sanjoy** [comment]
> I found that TensorFlow uses Eigen for GPU version convolution.

Can you be more specific?  Why do you think TF is using Eigen for convolutions?  [LaunchConv2DOp<GPUDevice, T>::operator()](https://github.com/tensorflow/tensorflow/blob/d95e97aef9bc589d9b2a08bfc806e3c5f48fcc90/tensorflow/core/kernels/conv_ops.cc#L647) is the main entry point into cuBLAS / cuDNN.

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.
