### ISSUE TITLE
Build breaks: The value 'REPOSITORY_NAME' has been removed in favor of 'repository_name()', please use the latter (https://docs.bazel.build/versions/master/skylark/lib/native.html#repository_name).

### ISSUE THREAD

**Issue by yurivict** [tensorflow/tensorflow#33863]
TF 2.0.0 fails to be built by bazel-1.1.0:

```
INFO: Found applicable config definition build:opt in file /usr/ports/science/py-tensorflow/work-py36/tensorflow-2.0.0/.tf_configure.bazelrc: --copt=-march=native --copt=-I/usr/local/include --host_copt=-march=native --define with_default_optimizations=true
ERROR: /usr/ports/science/py-tensorflow/work-py36/bazel_out/05d0f16da4b074c80492981824445ee0/external/com_google_protobuf/protobuf.bzl:274:40: The value 'REPOSITORY_NAME' has been removed in favor of 'repository_name()', please use the latter (https://docs.bazel.build/versions/master/skylark/lib/native.html#repository_name).
ERROR: /usr/ports/science/py-tensorflow/work-py36/bazel_out/05d0f16da4b074c80492981824445ee0/external/com_google_protobuf/protobuf.bzl:275:33: The value 'PACKAGE_NAME' has been removed in favor of 'package_name()', please use the latter (https://docs.bazel.build/versions/master/skylark/lib/native.html#package_name). 
ERROR: /usr/ports/science/py-tensorflow/work-py36/bazel_out/05d0f16da4b074c80492981824445ee0/external/com_google_protobuf/protobuf.bzl:275:11: The value 'PACKAGE_NAME' has been removed in favor of 'package_name()', please use the latter (https://docs.bazel.build/versions/master/skylark/lib/native.html#package_name). 
INFO: Call stack for the definition of repository 'local_config_syslibs' which is a syslibs_configure (rule definition at /usr/ports/science/py-tensorflow/work-py36/tensorflow-2.0.0/third_party/systemlibs/syslibs_configure.bzl:154:21):
 - /usr/ports/science/py-tensorflow/work-py36/tensorflow-2.0.0/tensorflow/workspace.bzl:73:5
 - /usr/ports/science/py-tensorflow/work-py36/tensorflow-2.0.0/WORKSPACE:19:1
ERROR: Skipping '//tensorflow:libtensorflow_cc.so': error loading package 'tensorflow': in /usr/ports/science/py-tensorflow/work-py36/tensorflow-2.0.0/tensorflow/core/platform/default/build_config.bzl: Extension 'protobuf.bzl' has errors
ERROR: error loading package 'tensorflow': in /usr/ports/science/py-tensorflow/work-py36/tensorflow-2.0.0/tensorflow/core/platform/default/build_config.bzl: Extension 'protobuf.bzl' has errors
```

Both bazel and TF are of the latest versions. What's going on?

**Comment by nikochiko** [comment]
As per [the table](https://www.tensorflow.org/install/source_windows#tested_build_configurations) at the end of this documentation page, Only `Bazel 0.26.1` has been tested with `TensorFlow-2.0.0`
The instructions recommend installing Bazel 0.24.1. (With a misleading instruction for which I have made a PR.)
The updated docs will be merged soon. :)

**Comment by nikochiko** [comment]
@oanush I can help resolve this issue. Can you assign me here?

**Comment by mihaimaruseac** [comment]
@yurivict are you compiling from `master` or from `r2.0`?

@nikochiko I'll assign you, thanks for offering to help

**Comment by nikochiko** [comment]
@mihaimaruseac 👍 Thank you!

**Comment by yurivict** [comment]
I'm compiling from 1.14.0

**Comment by mihaimaruseac** [comment]
Oh, the `r1.14` branch (and all other `r.*` branches) has not been ported to work with the newest Bazel. Usually we cut each release branch with a range of Bazel versions that we know we can compile with and use only one of these to do the actual release. The range is visible in `configure.py` (running `./configure` with Bazel outside the range will tell you to upgrade/downgrade) and the version we've used is listed in the table at the documentation page about installing from source (linked above)

**Comment by yurivict** [comment]
I actually would rather much prefer cmake to bazel, because all these issues simply don't exist with any cmake-based projects.

Maybe you could rather put your efforts to create the cmake build files instead? I think everybody outside of google struggles with bazel, and would rather see cmake do the build, because it's much simpler.

**Comment by nikochiko** [comment]
@yurivict There was actually a very similar discussion here: https://github.com/tensorflow/tensorflow/issues/6923.

**Comment by mihaimaruseac** [comment]
Also, SIG Build can help with build issues  https://groups.google.com/a/tensorflow.org/forum/#!forum/build

**Comment by yurivict** [comment]
The discussion was in 2017, and yet there's still no cmake build and it is extremely hard to build TensorFlow.

**Comment by gadagashwini** [comment]
Hi @yurivict, Tensorflow v1.14 requires `Bazel 0.24.1`. 
I would recommend you to try latest stable build with following configuration.



tensorflow-2.9.0 | 3.7-3.10 | GCC 9.3.1 | Bazel 5.0.0
-- | -- | -- | --

Follow the steps mentioned on [tensorflow.org](https://www.tensorflow.org/install/source) to build tensorflow from source. Thank you!
