### ISSUE TITLE
how to run test case in ring_reducer_test.cc

### ISSUE THREAD

**Issue by Keepmoving-ZXY** [tensorflow/tensorflow#33871]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):CentOS Linux release 7.6.1810 (Core)
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:N/A
- TensorFlow installed from (source or binary):source
- TensorFlow version:1.14.0
- Python version:3.6.8
- Installed using virtualenv? pip? conda?:pip
- Bazel version (if compiling from source): 0.25.0
- GCC/Compiler version (if compiling from source):7.3.1
- CUDA/cuDNN version:cuda:10.0, cudnn:7.5.0.56
- GPU model and memory:Telas v100, 32GB

I want to run test case in tensorflow/core/common_runtime/ring_reducer_test.cc, so I try this:
```
bazel test -c opt --config=cuda //tensorflow/core:ring_reducer_test
```
but bazel give me a error messages:
```
debian ~/collective/tensorflow $ bazel test -c opt --config=cuda //tensorflow/core:ring_reducer_test
WARNING: The following configs were expanded more than once: [cuda]. For repeatable flags, repeats are counted twice and may lead to unexpected behavior.
ERROR: Skipping '//tensorflow/core:ring_reducer_test': no such target '//tensorflow/core:ring_reducer_test': target 'ring_reducer_test' not declared in package 'tensorflow/core' defined by /home/zxy/collective/tensorflow/tensorflow/core/BUILD
ERROR: no such target '//tensorflow/core:ring_reducer_test': target 'ring_reducer_test' not declared in package 'tensorflow/core' defined by /home/zxy/collective/tensorflow/tensorflow/core/BUILD
INFO: Elapsed time: 0.212s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
FAILED: Build did NOT complete successfully (0 packages loaded)
```
bazel thinks that `ring_reducer_test` is not exist in `/home/zxy/collective/tensorflow/tensorflow/core/BUILD`, but I do find it. So can you help me to run test case in `ring_reducer_test.cc`?

**Comment by gowthamkpr** [comment]
I think you did not run `./configure`? Please look at issue #4279

**Comment by Keepmoving-ZXY** [comment]
the same error even after run `./configure`, below is content of `.tf_configure.bazelrc`:
```
build --action_env PYTHON_BIN_PATH="/home/zxy/collective/bin/python"
build --action_env PYTHON_LIB_PATH="/opt/rh/llvm-toolset-7.0/root/usr/lib/python2.7/site-packages"
build --python_path="/home/zxy/collective/bin/python"
build --action_env PYTHONPATH="/opt/rh/llvm-toolset-7.0/root/usr/lib/python2.7/site-packages:/opt/rh/devtoolset-7/root/usr/lib64/python2.7/site-packages:/opt/rh/devtoolset-7/root/usr/lib/python2.7/site-packages"
build:xla --define with_xla_support=true
build --action_env TF_NEED_OPENCL_SYCL="0"
build --action_env TF_NEED_ROCM="0"
build --action_env TF_NEED_CUDA="1"
build --action_env TF_NEED_TENSORRT="0"
build --action_env CUDA_TOOLKIT_PATH="/usr/local/cuda"
build --action_env TF_CUDA_COMPUTE_CAPABILITIES="7.0,7.0,7.0,7.0"
build --action_env LD_LIBRARY_PATH="/opt/rh/llvm-toolset-7.0/root/usr/lib64:/opt/rh/devtoolset-7/root/usr/lib64:/opt/rh/devtoolset-7/root/usr/lib:/opt/rh/devtoolset-7/root/usr/lib64/dyninst:/opt/rh/devtoolset-7/root/usr/lib/dyninst:/opt/rh/devtoolset-7/root/usr/lib64:/opt/rh/devtoolset-7/root/usr/lib"
build --action_env TF_CUDA_CLANG="0"
build --action_env GCC_HOST_COMPILER_PATH="/opt/rh/devtoolset-7/root/usr/bin/gcc"
build --config=cuda
build:opt --copt=-march=native
build:opt --copt=-Wno-sign-compare
build:opt --host_copt=-march=native
build:opt --define with_default_optimizations=true
build:v2 --define=tf_api_version=2
test --flaky_test_attempts=3
test --test_size_filters=small,medium
test --test_tag_filters=-benchmark-test,-no_oss,-oss_serial
test --build_tag_filters=-benchmark-test,-no_oss
test --test_tag_filters=-gpu
test --build_tag_filters=-gpu
build --action_env TF_CONFIGURE_IOS="0"

```
Is there some wrong in `.tf_configure.bazelrc`?

**Comment by gowthamkpr** [comment]
Tensorflow is built with bazel version 0.24.1. Can you please try it with bazel 0.24.1 and let me know if you are able to build successfully. For more info, go through this [link](https://www.tensorflow.org/install/source).

**Comment by Keepmoving-ZXY** [comment]
The same error even with bazel 0.24.1:
```
(collective) gpu7 ~/collective/tensorflow $ bazel test -c opt --config=cuda //tensorflow/core:ring_reducer_test
Starting local Bazel server and connecting to it...
WARNING: The following configs were expanded more than once: [cuda]. For repeatable flags, repeats are counted twice and may lead to unexpected behavior.
DEBUG: /home/zxy/.cache/bazel/_bazel_zxy/398544b8d2045ac5982abb4c34aae05c/external/bazel_tools/tools/cpp/lib_cc_configure.bzl:115:5: 
Auto-Configuration Warning: 'TMP' environment variable is not set, using 'C:\Windows\Temp' as default
ERROR: Skipping '//tensorflow/core:ring_reducer_test': no such target '//tensorflow/core:ring_reducer_test': target 'ring_reducer_test' not declared in package 'tensorflow/core' defined by /home/zxy/collective/tensorflow/tensorflow/core/BUILD
ERROR: no such target '//tensorflow/core:ring_reducer_test': target 'ring_reducer_test' not declared in package 'tensorflow/core' defined by /home/zxy/collective/tensorflow/tensorflow/core/BUILD
INFO: Elapsed time: 8.180s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (1 packages loaded)
FAILED: Build did NOT complete successfully (1 packages loaded)
```
version of bazel is:
```
(collective) gpu7 ~/collective/tensorflow $ bazel version
Build label: 0.24.1
Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Tue Apr 2 16:29:26 2019 (1554222566)
Build timestamp: 1554222566
Build timestamp as int: 1554222566
```

**Comment by gowthamkpr** [comment]
@Keepmoving-ZXY This is the configuration of Tensorflow-gpu 1.14


Version - tensorflow_gpu-1.14.0 
Python version - 2.7, 3.3-3.7
Compiler - GCC 4.8 
Build tools - Bazel 0.24.1
cuDNN - 7.4 
CUDA - 10.0

If you see above some of the configurations i.e., compiler and cuDNN versions are not matching.
For more information, you can refer to the following [guide](https://www.tensorflow.org/install/source#gpu)

Thanks!

**Comment by gowthamkpr** [comment]
@Keepmoving-ZXY Were you able to solve this issue?

**Comment by Keepmoving-ZXY** [comment]
No, I think there is no related to configuration of TensorFlow, I think the target `ring_reducer_test` is defined as private, not public, so I can't build the `ring_reducer_test` independently. I can see `test_main.cc` in `tensorflow/core/platform` but there is no instructions about how and when to run it. Could you tell me how to run tensorflow's c++ testcase?

**Comment by dubey** [comment]
Can you try `bazel test -c opt --config=cuda //tensorflow/core:common_runtime_ring_reducer_test`?

**Comment by Keepmoving-ZXY** [comment]
Yes, this can build `ring_reducer_test.cc` and it's dependency, and export binary file in `bazel-bin/tensorflow/core/common_runtime_ring_reducer_test`, thank you very much. And could you tell me why I must add `common_runtime` to `ring_reducer_test`?

**Comment by dubey** [comment]
`ring_reducer_test` is defined in `core/BUILD` using [`tf_cc_tests_gpu`](https://github.com/tensorflow/tensorflow/blob/1e65730120aafc413e8c3dcddcf19cd8d184fe1b/tensorflow/core/BUILD#L3718).  If you follow the definition of `tf_cc_tests_gpu` in `tensorflow.bzl`, you will eventually arrive at [`src_to_test_name`](https://github.com/tensorflow/tensorflow/blob/1e65730120aafc413e8c3dcddcf19cd8d184fe1b/tensorflow/tensorflow.bzl#L82), which contains the logic for which you're looking.

**Comment by Keepmoving-ZXY** [comment]
ok, thank you.

**Comment by rayoluo** [comment]
thanks! figure it out finally...
