### ISSUE TITLE
How to add an optimizer to tesorflow simple speech recognition

### ISSUE THREAD

**Issue by chathuravithakshana** [tensorflow/tensorflow#33876]
I wanna know how to add an optimizer such as Adam, or Nadam optimizer to the simple speech recognition example in this repository? Because I don't know where to or how to add it in the code such as to "model.py" file or where and how?

**Comment by gowthamkpr** [comment]
@chathuravithakshana Please post this question in [stackoverflow](https://stackoverflow.com/questions/tagged/tensorflow) as github is only meant for bug/performance, build/install, feature requests or doc changes. Thanks!
