### ISSUE TITLE
Strange behaviour of tf.sigmoid

### ISSUE THREAD

**Issue by georgesterpu** [tensorflow/tensorflow#33878]
**System information**
- OS Platform and Distribution: Manjaro Linux testing
- TensorFlow installed from: binary (pip tf-nightly)
- TensorFlow version: v1.12.1-17077-ge9a3aa1 2.1.0-dev20191030
- Python version: 3.7.4
- CPU Model: Intel m3-6Y30

**Describe the current behavior**
It seems that `tf.sigmoid` returns different values for identical inputs.

**Describe the expected behavior**
Return identical outputs for identical inputs, regardless of the error scale.

**Code to reproduce the issue**
```
import tensorflow as tf

a = tf.convert_to_tensor(
    [[0.2, 0.2],
     [0.2, 0.2],
     [0.2, 0.2],
     [0.2, 0.2],
     [0.2, 0.2],],
    dtype=tf.float32)

sigm = tf.sigmoid(a)

if tf.__version__.startswith('1'):
  tf.InteractiveSession()
  sigm = sigm.eval()
elif tf.__version__.startswith('2'):
  sigm = sigm.numpy()
else:
  raise ValueError()

assert((sigm[0] == sigm[1]).all()); print("*"*1)
assert((sigm[0] == sigm[2]).all()); print("*"*2)
assert((sigm[0] == sigm[3]).all()); print("*"*3)
assert((sigm[0] == sigm[4]).all()); print("*"*4)
```

**Other info / logs**
I can reproduce this in TensorFlow 1.x, 2.0, on GPU and CPU, on my laptop or in Google Colab.
`1 / (1 + tf.exp(-a))` seems to return the expected output.

TensorFlow appears to use the sigmoid implementation from the Eigen library, so I am trying to notify the contributors listed in the source files @benoitsteiner @ebrevdo @ggael 
I know that the differences are very small, yet the sigmoid function is at the core of some stateful operations such as LSTM, posing the risk of error accumulation. Besides that, I am simply curious to find out what causes this difference.

**Comment by ggael** [comment]
See: https://eigen.tuxfamily.org/bz/show_bug.cgi?id=1777

**Comment by ebrevdo** [comment]
+Alexandre Passos <apassos@google.com> +Rasmus Larsen
<rmlarsen@google.com> this
is a performance optimization I think.  Perhaps we should add a precision
attr or graph config like xla does?

**Comment by ebrevdo** [comment]
This particular optimization is problematic, since it gives values that are
very far off for gradients of values below -14. I have a TODO to remove it
and just rely on the vectorized version of division, addition and exp.

**Comment by ebrevdo** [comment]
Googlers: This is internal bug b/143090143.

**Comment by georgesterpu** [comment]
Apologies for the noob question, not familiar with Eigen: are the results different for some inputs because they are processed by different implementations of sigmoid, a fast one for the biggest chunk that is a multiple of the acceptable sizes, and a slower one for the remainder ?

**Comment by jvishnuvardhan** [comment]
@georgesterpu Is this still an issue. I ran your code with `tf-nightly` and found results were asserted for the first three conditions and only failed for the last condition. However, this could be related to numerical error as the numerical mismatch is in 5th decimal.
```
print(sigm[0]) #[0.549834 0.549834]
print(sigm[2]) #[0.549834 0.549834]
print(sigm[4]) #[0.54983395 0.54983395]
```

Please check the [gist here](https://colab.research.google.com/gist/jvishnuvardhan/2f27b3eb5cb8921d82d0494327e5b97a/untitled53.ipynb). Thanks!

**Comment by georgesterpu** [comment]
@jvishnuvardhan thank you very much for the follow up.
As far as I understand, this may be a side effect of an optimisation.
One of the eigen developers wrote that `Having (even slightly) different results for the same input is not good.`

Looking at the commit history in ` Eigen/src/Core//functors/UnaryFunctors.h`, I think that @rmlarsen is the most qualified to clarify this.

**Comment by jvishnuvardhan** [comment]
@rmlarsen Can you please take a look at this issue. Thanks!

**Comment by jvishnuvardhan** [comment]
@georgesterpu I think this was resolved in recent `tf-nightly`. I couldn't reproduce the issue with `tf-nightly` and [here](https://colab.research.google.com/gist/jvishnuvardhan/d6c4e9fa4849020ae89101d1f45cce8b/untitled53.ipynb) is the gist for your reference. Thanks!

Please verify once and close the issue if this was resolved for you. Thanks!

**Comment by georgesterpu** [comment]
Thank you @jvishnuvardhan.
