### ISSUE TITLE
ERROR: An error occurred during the fetch of repository 'local_config_cuda': Traceback (most recent call last): File "/home/shaurya/Downloads/tensorflow/third_party/gpus/cuda_configure.bzl", line 1266 _create_local_cuda_repository(repository_ctx) File "/home/shaurya/Downloads/tensorflow/third_party/gpus/cuda_configure.bzl", line 1199, in _create_local_cuda_repository _tpl(repository_ctx, "crosstool:BUILD", c...) File "/home/shaurya/Downloads/tensorflow/third_party/gpus/cuda_configure.bzl", line 745, in _tpl repository_ctx.template(out, Label(("//third_party/gpus/%s...)), ...) class com.google.devtools.build.lib.syntax.SkylarkList$MutableList cannot be cast to class java.lang.String (com.google.devtools.build.lib.syntax.SkylarkList$MutableList is in unnamed module of loader 'app'; java.lang.String is in module java.base of loader 'bootstrap')

### ISSUE THREAD

**Issue by shauryad15** [tensorflow/tensorflow#33879]
bazel version -- [bazel release 0.26.1]
cuda 10.0
cudnn 7
ubuntu 18.04
tensorflow r1.14

while building tensorflow, getting this error:
INFO: Call stack for the definition of repository 'local_config_cuda' which is a cuda_configure (rule definition at /home/shaurya/Downloads/tensorflow/third_party/gpus/cuda_configure.bzl:1268:18):
 - /home/shaurya/Downloads/tensorflow/tensorflow/workspace.bzl:63:5
 - /home/shaurya/Downloads/tensorflow/WORKSPACE:94:1
ERROR: An error occurred during the fetch of repository 'local_config_cuda':
   Traceback (most recent call last):
	File "/home/shaurya/Downloads/tensorflow/third_party/gpus/cuda_configure.bzl", line 1266
		_create_local_cuda_repository(repository_ctx)
	File "/home/shaurya/Downloads/tensorflow/third_party/gpus/cuda_configure.bzl", line 1199, in _create_local_cuda_repository
		_tpl(repository_ctx, "crosstool:BUILD", c...)
	File "/home/shaurya/Downloads/tensorflow/third_party/gpus/cuda_configure.bzl", line 745, in _tpl
		repository_ctx.template(out, Label(("//third_party/gpus/%s...)), ...)
class com.google.devtools.build.lib.syntax.SkylarkList$MutableList cannot be cast to class java.lang.String (com.google.devtools.build.lib.syntax.SkylarkList$MutableList is in unnamed module of loader 'app'; java.lang.String is in module java.base of loader 'bootstrap')
ERROR: Skipping '//tensorflow/tools/pip_package:build_pip_package': error loading package 'tensorflow/tools/pip_package': Encountered error while reading extension file 'cuda/build_defs.bzl': no such package '@local_config_cuda//cuda': Traceback (most recent call last):
	File "/home/shaurya/Downloads/tensorflow/third_party/gpus/cuda_configure.bzl", line 1266
		_create_local_cuda_repository(repository_ctx)
	File "/home/shaurya/Downloads/tensorflow/third_party/gpus/cuda_configure.bzl", line 1199, in _create_local_cuda_repository
		_tpl(repository_ctx, "crosstool:BUILD", c...)
	File "/home/shaurya/Downloads/tensorflow/third_party/gpus/cuda_configure.bzl", line 745, in _tpl
		repository_ctx.template(out, Label(("//third_party/gpus/%s...)), ...)
class com.google.devtools.build.lib.syntax.SkylarkList$MutableList cannot be cast to class java.lang.String (com.google.devtools.build.lib.syntax.SkylarkList$MutableList is in unnamed module of loader 'app'; java.lang.String is in module java.base of loader 'bootstrap')
WARNING: Target pattern parsing failed.
ERROR: error loading package 'tensorflow/tools/pip_package': Encountered error while reading extension file 'cuda/build_defs.bzl': no such package '@local_config_cuda//cuda': Traceback (most recent call last):
	File "/home/shaurya/Downloads/tensorflow/third_party/gpus/cuda_configure.bzl", line 1266
		_create_local_cuda_repository(repository_ctx)
	File "/home/shaurya/Downloads/tensorflow/third_party/gpus/cuda_configure.bzl", line 1199, in _create_local_cuda_repository
		_tpl(repository_ctx, "crosstool:BUILD", c...)
	File "/home/shaurya/Downloads/tensorflow/third_party/gpus/cuda_configure.bzl", line 745, in _tpl
		repository_ctx.template(out, Label(("//third_party/gpus/%s...)), ...)
class com.google.devtools.build.lib.syntax.SkylarkList$MutableList cannot be cast to class java.lang.String (com.google.devtools.build.lib.syntax.SkylarkList$MutableList is in unnamed module of loader 'app'; java.lang.String is in module java.base of loader 'bootstrap')
INFO: Elapsed time: 0.485s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
    currently loading: tensorflow/tools/pip_package

**Comment by gunan** [comment]
Did you run `./configure` before running the build, as instructed in https://www.tensorflow.org/install/source#configure_the_build

**Comment by shauryad15** [comment]
Yes, i followed the exact same step.
