### ISSUE TITLE
mobile tensorflow

### ISSUE THREAD

**Issue by baylor0118** [tensorflow/tensorflow#3387]
About mobile tensorflow ( https://www.tensorflow.org/mobile.html ), I want to download the inception
(http://download.tensorflow.org/models/image/imagenet/inception-2015-12-05.tgz), but it has been 
damaged.

Thank you!

**Comment by fwalch** [comment]
The download/extraction works for me; are you sure it's not a problem with your network connection or something like that?

**Comment by concretevitamin** [comment]
Same: works for me.  Closing for now.

**Comment by baylor0118** [comment]
Thank you very much.
