### ISSUE TITLE
Setting Log Level via Java API?

### ISSUE THREAD

**Issue by lucaro** [tensorflow/tensorflow#33881]
**System information**
- TensorFlow version: 1.14 (via Java API)

**Describe the current behavior**

When using the current Java bindings for TensorFlow, the log gets filled with output from every operation when a model is evaluated. I was unable to find a way to set the log level via the Java API. Is this at all possible?

**Comment by Craigacp** [comment]
Active development on the TF Java API is happening on github.com/tensorflow/java, might be worth opening the issue there.

**Comment by lucaro** [comment]
Hey, thanks, but the code in that repository is not yet available as a maven artifact. The relevant code in my case is hosted in https://github.com/tensorflow/tensorflow/tree/master/tensorflow/java

**Comment by Craigacp** [comment]
Yes, but there isn't any development happening on the API in the main tensorflow tree. I don't think it's possible to set the log level from Java at the moment. Open the issue on the Java API and we'll get to it.

**Comment by lucaro** [comment]
Ok, thanks!

**Comment by ravikyram** [comment]
Can we close issue here and follow up in [tensorflow/java#3](https://github.com/tensorflow/java/issues/3).Please, confirm.Thanks!

**Comment by lucaro** [comment]
Whatever is easiest for you.

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.

**Comment by lucaro** [comment]
I don't think this has been resolved in tensorflow 2.X, or am I missing something?

**Comment by lucaro** [comment]
Well, that's one way to deal with it...
