### ISSUE TITLE
 Support sparse inputs for Embedding layer

### ISSUE THREAD

**Issue by workingloong** [tensorflow/tensorflow#33880]
**System information**
- TensorFlow version (you are using): 2.0.0
- Are you willing to contribute it (Yes/No): Yes. And the code change is ready.

**Describe the feature and the current behavior/state.**
The tf.keras.layers.Embedding only can be used with dense inputs. The user must customize a layer for sparse tensor inputs by using tf.nn.embedding_lookup_sparse.  Or, the user needs to use tf.feature_columns.embedding_columns to transform sparse inputs to tf.layer.DenseFeature.

**Will this change the current api? How?**
The Embedding layer should add the `combiner` argument for sparse inputs. The value of `combiner` can be "sum", "mean" and so on.

**Who will benefit with this feature?**
Embedding with sparse inputs is commonly used in advertising and recommendation system in which the input ids of a sample are very sparse. 

**Any Other info.**

**Comment by mvbattan** [comment]
Any workarounds on this ? This is my approach so far, but I feel it's messy and leads to a much bigger model than should be.
```
input_layer = Input(input_shape)
x = Dense(input_shape, kernel_initializer='ones', bias_initializer='zeros', name='unpack')(input_layer)
x = Embedding(X.shape[1], 128)(x)
...
model.get_layer(name='unpack').trainable = False
```

**Comment by pavithrasv** [comment]
Adding @tanzhenyu who is working on sparse inputs

**Comment by 0x1997** [comment]
Any updates?

**Comment by cjmcgraw** [comment]
@tanzhenyu  any updates on this, or potentially a workaround for it for those of us who have sparse inputs and would like to use an embedding?

**Comment by cjmcgraw** [comment]
Follow up on my previous message. I've been able to overcome this with the following code from `tensorflow==2.5.0`

If you're seeing this message in the future and its not resolved, here was the implementation I came up with to overcome this problem.

```python
import tensorflow as tf

from tensorflow.keras import backend
from tensorflow.python.ops import embedding_ops
from tensorflow.python.ops import math_ops


class SparseEmbedding(tf.keras.layers.Embedding):
    def __init__(self, *args, combiner=None, mask_zero=None, **kwargs):
        assert mask_zero is None, "Cannot use sparse embedding with mask zero!"
        self._combiner = combiner
        super().__init__(*args, **kwargs)

    def compute_mask(self, inputs, mask=None):
        return None

    def call(self, inputs):
        dtype = backend.dtype(inputs)
        if dtype != 'int32' and dtype != 'int64':
            raise TypeError(f"""
            Failed to process inputs! Expected dtype to be integers!
            
            expected: int32 or int64
            received: {dtype}
            name: {inputs.name}
            """)
        out = embedding_ops.safe_embedding_lookup_sparse_v2(
            embedding_weights=self.embeddings,
            sparse_ids=inputs,
            combiner=self._combiner
        )
        if self._dtype_policy.compute_dtype != self._dtype_policy.variable_dtype:
            # Instead of casting the variable as in most layers, cast the output, as
            # this is mathematically equivalent but is faster.
            out = math_ops.cast(out, self._dtype_policy.compute_dtype)
        return out

    def get_config(self):
        base_config = super().get_config()
        config = {
            "combiner": self._combiner
        }
        return dict(list(base_config.items()) + list(config.items()))
```

**Comment by akrlowicz** [comment]
@cjmcgraw what is mask_zero in this code, how should it look like?

**Comment by tilakrayal** [comment]
@workingloong,
Could you please take a look at the latest official link for the **tf.keras.layers.Embedding**, where it was documented that this layer accepts [tf.Tensor](https://www.tensorflow.org/api_docs/python/tf/Tensor), [tf.RaggedTensor](https://www.tensorflow.org/api_docs/python/tf/RaggedTensor) and [tf.SparseTensor](https://www.tensorflow.org/api_docs/python/tf/sparse/SparseTensor) input.

https://www.tensorflow.org/api_docs/python/tf/keras/layers/Embedding



sparse | If True, calling this layer returns a tf.SparseTensor. If False, the layer returns a dense tf.Tensor. For an entry with no features in a sparse tensor (entry with value 0), the embedding vector of index 0 is returned by default.
-- | --
