### ISSUE TITLE
I am trying to edit tensorflow lite docs but not able to find source code

### ISSUE THREAD

**Issue by mr-yamraj** [tensorflow/tensorflow#33883]
link which I want to edit: [https://www.tensorflow.org/community/contribute/docs](https://www.tensorflow.org/community/contribute/docs)
The description of Digit classifier is incorrect

**Comment by nikochiko** [comment]
@mr-yamraj This is the file you are looking for: https://github.com/tensorflow/docs/blob/master/site/en/community/contribute/docs.md

The TensorFlow website code in stored in the /site/ directory within the `docs` repository.

**Comment by nikochiko** [comment]
I would be glad to have this issue assigned if any more help is required. 
Otherwise, this issue can be closed.

**Comment by jvishnuvardhan** [comment]
Thanks @nikochiko . @mr-yamraj Please close the issue if it was resolved by @nikochiko .
