### ISSUE TITLE
tf.image.per_image_standardization return wrong values

### ISSUE THREAD

**Issue by skyap** [tensorflow/tensorflow#33892]
Tensorflow version = 1.15
tf.image.per_image_standardization does not standardize value to [-1,1] 
i test in tensorflow 1.12 it work correctly
 
```python
import tensorflow as tf 
import numpy as np 
print(tf.__version__)
a = tf.constant([[[1,2,3],[4,5,6]]])
b = tf.image.per_image_standardization(a)
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    print(sess.run(b))
x = np.asarray([[[1,2,3],[4,5,6]]], dtype=np.float64)

def normalize_meanstd(a, axis=None): 
    # axis param denotes axes along which mean & std reductions are to be performed
    mean = np.mean(a, axis=axis, keepdims=True)
    std = np.sqrt(((a - mean)**2).mean(axis=axis, keepdims=True))
    return (a - mean) / std

print(normalize_meanstd(x))
```
```
1.15.0
[[[-6 -3 -1]
  [ 1  3  6]]]
[[[-1.46385011 -0.87831007 -0.29277002]
  [ 0.29277002  0.87831007  1.46385011]]]
```

**Comment by maridia** [comment]
It's because a is interpreted as an int tensor instead of a float tensor.  If you define 
a = tf.constant([[[1.0,2.0,3.0],[4.0,5.0,6.0]]])
you get the correct behavior.

**Comment by skyap** [comment]
thanks! it should handle int tensor because image normally in uint8 and since when we are using "tf.image.per_image_standardization"  we will not change the data type as we expect  the function handle it.

**Comment by jvishnuvardhan** [comment]
@skyap Looks like there is some issue with converting dtype from `int` to `float` with this `convert_image_dtype` function in the source code of `tf.image.per_image_standardization`. We will take a look deeper at the source. Thanks!

**Comment by starp0wer** [comment]
The same issue still exists in TensorFlow version 2.3.0. 
`x = [[[0.8, 1., 1.],
      [1., 1., 1.]],
    [[0., 0., 0.],
      [0.8, 0.8, 1.]]]`
`y = tf.image.convert_image_dtype(x, dtype=tf.uint8, saturate=False)`
`normal_y = tf.image.per_image_standardization(y)`
`print(normal_y)` -> `tf.Tensor(
[[[ 61 185 185]
  [185 185 185]]
 [[  0   0   0]
  [ 61  61 185]]], shape=(2, 2, 3), dtype=uint8)`
This is slightly inconvenient, as @skyap mentioned that a lot of times images are stored in uint8 format, including the returned image from `tf.io.decode_jpeg`. This also conflicts with the documentation of `tf.image.convert_image_dtype` https://www.tensorflow.org/api_docs/python/tf/image/per_image_standardization, where the description says "Linearly scales each image in image to have mean 0 and variance 1." 

And as @ jvishnuvardhan mentioned, the problem exists in the use of` convert_image_dtype`. According to https://www.tensorflow.org/api_docs/python/tf/image/convert_image_dtype, images in floating point values are expected to have values in the range [0,1) and images in integer values are expected to have values in the range [0,MAX]. When converting the dtype from float into uint, `convert_image_dtype` rescales the standardized image back into the expected range of [0, MAX]. But it doesn't rescale the standardized floating point values into its expected range of [0,1), so the `tf.image.per_image_standardization` can still work as expected if the original image is in floating point values. 

I wonder if the documentation of `image.per_image_standardization` could be revised to add a reminder of dtype , or if the convert_image_dtype function can be revised to handle these cases appropriately. Based on the current documentation, as a user I'd be expecting the `image.per_image_standardization` to return to me me pixel values with mean 0 and variance 1 directly without having to converting the image dtype.

**Comment by mixxen** [comment]
We have been dealing with inconsistencies with training for a while now, and have found the root cause to be related to this issue.

Here is the offending commit:

https://github.com/tensorflow/tensorflow/commit/906e0e3bc0dfe12db19afa261e4d793b73cb64ec

In version 1.14, per_image_standardization internally converted integer images to float and returned the standardized image as a float.

In version 1.15+, per_image_standardization internally converts the integer images to a float then divides by the max dtype value, and converts it back to an integer image.

This is especially bad for users of 1.14 and earlier who upgraded to 1.15 or 2.0+ as their integer image data would be quantized and/or truncated (e.g. unsigned int) by per_image_standardization.

Suggest updating the documentation and/or throwing an exception if the input type is unsigned int. See example below:

``` python
import tensorflow as tf 
import numpy as np 
print(tf.__version__)
# unsigned int example (works in 1.14, but really, really, bad in 1.15+)
a = tf.constant([[[1,2,3],[4,5,6]]], tf.uint16)
b = tf.image.per_image_standardization(a)
x = np.asarray([[[1,2,3],[4,5,6]]], dtype=np.float64)

def normalize_meanstd(a, axis=None): 
    # axis param denotes axes along which mean & std reductions are to be performed
    mean = np.mean(a, axis=axis, keepdims=True)
    std = np.sqrt(((a - mean)**2).mean(axis=axis, keepdims=True))
    return (a - mean) / std

print(b)
print(normalize_meanstd(x))
```
```
2.2.0
tf.Tensor(
[[[0 0 0]
  [1 3 6]]], shape=(1, 2, 3), dtype=uint16)
[[[-1.46385011 -0.87831007 -0.29277002]
  [ 0.29277002  0.87831007  1.46385011]]]
```

**Comment by hyeygit** [comment]
Related github issue: #44983 

The changes in https://github.com/tensorflow/tensorflow/commit/906e0e3bc0dfe12db19afa261e4d793b73cb64ec unintentionally modified the behavior of `tf.image.per_image_standardization` and is reverted in https://github.com/tensorflow/tensorflow/commit/b6be9714e878a7dd0d1405bd7a83e021ba4b561a. 

With `tf-nightly`, the function should return expected values for `uint` data types as before. Here is a [colab](https://colab.research.google.com/drive/1nqzU22tZ0RVAaDm6drWPkfGV8cc7A_3x?usp=sharing) verifying the fix.
