### ISSUE TITLE
tensorflow 2.0, tf.keras can't place model with tf.device('/device:GPU:0')?

### ISSUE THREAD

**Issue by luvwinnie** [tensorflow/tensorflow#33903]
I have 2 different models and I want to train multitasks by loading those models to different GPUs respectively. I think this is so-called model parallelism. For example, one model is about 8GB, another is 12GB, I use the following code to load model to the respective device, however, it just doesn't work, the TensorFlow trying to load the whole model into same GPU(PC with 2 RTX Titan 24GB). Is this the problem with namescope?

System information

Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04
TensorFlow version (use command below): 2.0.0-stable version
Python version: 3.7.4
CUDA/cuDNN version: 10.0
GPU model and memory: RTX Titan x2 

```
with tf.device('/device:GPU:0'):
     model_1 = K.models.load_model(model_path1)
with tf.device('/device:GPU:1'):
     model_2 = K.models.load_model(model_path2)
```

Can I have some support with this?

I have been asked this problem in [stackoverflow](https://stackoverflow.com/questions/58448034/tensorflow-2-0-how-to-train-mutliple-model-with-mutliple-gpu) but no body answer my question.

**Comment by ravikyram** [comment]
Can you please go through the [link](https://www.tensorflow.org/guide/gpu#using_multiple_gpus) and see if it helps you. Thanks!

**Comment by ravikyram** [comment]
@luvwinnie 
Any update on this issue please. Thanks!

**Comment by ravikyram** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
