### ISSUE TITLE
Update sample session for build from source instruction docs

### ISSUE THREAD

**Issue by nikochiko** [tensorflow/tensorflow#33906]
## URL(s) with the issue:
https://www.tensorflow.org/install/source_windows
https://www.tensorflow.org/install/source

## Description of issue (what needs changing):
The sample sessions given in the docs are old (Bazel 0.15.1, TensorFlow 1.11, python 2.7)
A new session-copy with the more recent TensorFlow 2.x with Bazel 0.26.1 would be more helpful.
Also, python 2.7 is reaching end-of-life in Jan 2020.

### Submit a pull request?

Are you planning to also submit a pull request to fix the issue? Yes.

**Comment by jvishnuvardhan** [comment]
@nikochiko Are you saying the instructions to install TF from source uses Bazel 0.15.1? I see [here](https://www.tensorflow.org/install/source_windows#setup_for_windows) Bazel 0.24.1. Am I missing something here. Can you please describe with little more details? Thanks!

**Comment by nikochiko** [comment]
@jvishnuvardhan I don't mean in the text instructions. There is a sample configuration session on the instructions page. It drops down with a '+' button. 
![Capture](https://user-images.githubusercontent.com/37668193/68988565-8d137780-085f-11ea-9ca9-ce65db0abd28.PNG)

It is very outdated. Having a newer version can help with installation since many users are facing build failures.

**Comment by jvishnuvardhan** [comment]
@nikochiko I agree that the sample configuration is with an older version but it an example to any user how to configure. It is difficult to update this configuration every time when a dependency (python/CUDA/Bazel etc) is changed. Thanks!

@MarkDaoust Can you Please take a look at it. Are we updating this in the near future? Thanks!

**Comment by jvishnuvardhan** [comment]
I am closing this issue as I think this issue was resolved. There is another `sample configuration` with newer versions in the build-from-source for linux/MacOS [page](https://www.tensorflow.org/install/source). Thanks!
