### ISSUE TITLE
'Copy link to this section' feature not working for certain sections.

### ISSUE THREAD

**Issue by nikochiko** [tensorflow/tensorflow#33905]
## URL(s) with the issue:
- https://www.tensorflow.org/install/source_windows
- https://www.tensorflow.org/install/source

## Browser used:
Tried on Microsoft Edge and Mozilla Firefox up-to-date versions.

## Description of issue (what needs changing):
The 'Copy link to this section' feature is not working for the `View sample configuration session` sections for the Linux and Windows build-from-source instruction docs.
### Clear description:
The issue-causing sections are located under these sections: 
- https://www.tensorflow.org/install/source#sample_session (Linux)
- https://www.tensorflow.org/install/source_windows#configure_the_build (Windows)

### Submit a pull request?

Are you planning to also submit a pull request to fix the issue?:  Yes, I can fix the markdown to correct the issue.

**Comment by nikochiko** [comment]
@lamberta From where should this issue be fixed? It doesn't look like a MarkDown issue. 
Thank you in advance.

**Comment by lamberta** [comment]
Possibly related to internal bug: b/115916696
Will wait and see

**Comment by amahendrakar** [comment]
> The 'Copy link to this section' feature is not working for the `View sample configuration session` sections for the Linux and Windows build-from-source instruction docs.

@nikochiko,
Looks like this issue is fixed. Links for `View sample configuration session` section works for both Windows and Linux.

- Windows : https://www.tensorflow.org/install/source_windows#expandable-1
- Linux : https://www.tensorflow.org/install/source#expandable-1

Please feel free to close the issue if resolved. Thanks!
