### ISSUE TITLE
Could not find any cupti.h in any subdirectory when running Configure in Tensorflow

### ISSUE THREAD

**Issue by za13** [tensorflow/tensorflow#33918]
I'm using Ubuntu and have CUDA 7.5 installed according to `nvcc --version`

I git cloned Tensorflow and attempted `./configure` and got the below:

    Please specify the location of python. [Default is /home/me/anaconda3/bin/python]: 
    
    
    Found possible Python library paths:
      /home/me/anaconda3/lib/python3.6/site-packages
    Please input the desired Python library path to use.  Default is [/home/me/anaconda3/lib/python3.6/site-packages]
    
    Do you wish to build TensorFlow with XLA JIT support? [Y/n]: 
    XLA JIT support will be enabled for TensorFlow.
    
    Do you wish to build TensorFlow with OpenCL SYCL support? [y/N]: n
    No OpenCL SYCL support will be enabled for TensorFlow.
    
    Do you wish to build TensorFlow with ROCm support? [y/N]: 
    No ROCm support will be enabled for TensorFlow.
    
    Do you wish to build TensorFlow with CUDA support? [y/N]: y
    CUDA support will be enabled for TensorFlow.
    
    Do you wish to build TensorFlow with TensorRT support? [y/N]: 
    No TensorRT support will be enabled for TensorFlow.

It then shows the error:

    Could not find any cupti.h in any subdirectory:

It then asks for the CUDA Version:

    Please specify the CUDA SDK version you want to use. [Leave empty to default to CUDA 10]: 7.5
    
    
    Please specify the cuDNN version you want to use. [Leave empty to default to cuDNN 7]: 
    
    
    Please specify the locally installed NCCL version you want to use. [Leave empty to use http://github.com/nvidia/nccl]: 
    
    
    Please specify the comma-separated list of base paths to look for CUDA libraries and headers. [Leave empty to use the default]:

 
But it shows the same error: `Could not find any cupti.h in any subdirectory:`

**Comment by gadagashwini** [comment]
@za13, Did you set the proper CUDA path in `./configure`. Thanks!

**Comment by za13** [comment]
how do I do that?

**Comment by gadagashwini** [comment]
@za13, While running `./configure`, specify the CUDA installed path. Thanks!

**Comment by gadagashwini** [comment]
@za13, Please follow the instructions mentioned [here](https://www.tensorflow.org/install/source). Thanks!

**Comment by za13** [comment]
I don't see how I can specify the CUDA installed path when running `./configure`

As soon as I enter `./configure`, it shows

Please specify the location of python. [Default is /home/me/anaconda3/bin/python]: 


Found possible Python library paths:
  /home/me/anaconda3/lib/python3.6/site-packages
Please input the desired Python library path to use.  Default is [/home/me/anaconda3/lib/python3.6/site-packages]

Do you wish to build TensorFlow with XLA JIT support? [Y/n]: 
XLA JIT support will be enabled for TensorFlow.

Do you wish to build TensorFlow with OpenCL SYCL support? [y/N]: n
No OpenCL SYCL support will be enabled for TensorFlow.

Do you wish to build TensorFlow with ROCm support? [y/N]: 
No ROCm support will be enabled for TensorFlow.

Do you wish to build TensorFlow with CUDA support? [y/N]: y
CUDA support will be enabled for TensorFlow.

Do you wish to build TensorFlow with TensorRT support? [y/N]: 
No TensorRT support will be enabled for TensorFlow.

when it then gets to

`Please specify the CUDA SDK version you want to use. [Leave empty to default to CUDA 10]: 7.5
`

and I enter `9.1` since `sudo find / -name nvcc` showed `/usr/local/cuda-9.1/bin/nvcc

It shows `could not find any cuda.h matching version 9.1 in any subdirectory

**Comment by gadagashwini** [comment]
@za13,
Use CUDA 9.0 and cuDNN 7.
Please specify the path CUDA path in ./configure
```
Do you wish to build TensorFlow with CUDA support? [y/N]: Y
CUDA support will be enabled for TensorFlow.

Please specify the CUDA SDK version you want to use. [Leave empty to default to CUDA 9.0]: 9.0

Please specify the location where CUDA 9.0 toolkit is installed. Refer to README.md for more details. [Default is /usr/local/cuda]:

Please specify the cuDNN version you want to use. [Leave empty to default to cuDNN 7.0]: 7.0

Please specify the location where cuDNN 7 library is installed. Refer to README.md for more details. [Default is /usr/local/cuda]:
```
Let us know how it progresses. Thanks!

**Comment by za13** [comment]
when I tried CUDA 9.0 and cuDNN 7.0 as you suggested, it says `could not find any cuda.h matching version 9.0 in any subdirectory`

**Comment by za13** [comment]
can anyone help?

**Comment by ymodak** [comment]
Apologies for the delay in response. You need to add ```CUPTI``` to the ```$LD_LIBRARY_PATH```environment variable path.
See https://www.tensorflow.org/install/gpu#linux_setup

**Comment by za13** [comment]
add `CUPTI` to the `$LD_LIBRARY_PATH` gave the same error of `could not find any cuda.h matching version 9.0 in any subdirectory`
