### ISSUE TITLE
tf.keras (tf 2) much slower than tf 1.14

### ISSUE THREAD

**Issue by renatobellotti** [tensorflow/tensorflow#33911]
I try to train a simple dense feedforward network consisting of:

- input layer of size 8
- 3 hidden layers, each with 40 neurons and ReLU activations
- output layer of size 9

for a regression.

The performance of keras using tensorflow 1.14 is about 3 times faster than using a freshly installed tensorflow 2.0.0... Is this to be expected, or might this be a bug?
I am training on a CPU.

**Comment by jvishnuvardhan** [comment]
@renatobellotti Can you please provide a standalone code to reproduce the issue? Thanks!

**Comment by renatobellotti** [comment]
I cannot reproduce it anymore... Probably something with my setup was wrong. Thanks for your interest anyway!
