### ISSUE TITLE
cudnn5  so slow

### ISSUE THREAD

**Issue by nationalflag** [tensorflow/tensorflow#3391]
I updated cudnn from 4 to 5, and reinstall tensorflow from source.
But I found that my code run almost 6 time slower than before.

**Comment by concretevitamin** [comment]
Please provide more environment details and a minimum repro (if you can isolate the performance degradation to a few ops, or a minimum model).

**Comment by concretevitamin** [comment]
(For example, please copy the issue report template from #3366.)
