### ISSUE TITLE
build tensorflow from source failed on Linux

### ISSUE THREAD

**Issue by dongxiao92** [tensorflow/tensorflow#33910]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 16.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: NA
- TensorFlow installed from (source or binary): source
- TensorFlow version: r1.14
- Python version: Python 3.7.3 (default, Mar 27 2019, 22:11:17) [GCC 7.3.0] :: Anaconda, Inc. on linux
- Installed using virtualenv? pip? conda?: NA
- Bazel version (if compiling from source): 0.25.0
- GCC/Compiler version (if compiling from source): gcc (Ubuntu 5.4.0-6ubuntu1~16.04.10) 5.4.0 20160609; nvcc release 9.1, V9.1.85
- CUDA/cuDNN version: 9.1/7.3.0
- GPU model and memory: Nvidia Titan XP with 12 GB memory

**Describe the problem**
build tensorflow from source on branch r1.14 on ubuntu 16.04 with GPU and XLA support failed. Errors related to undefiend symbols in cublas occured. I can ensure the cublas library has been installed in the $CUDA_HOME/lib64 (/usr/local/cuda/lib64) which has been added to $LD_LIBRARY_PATH. I also print the symbols in the installed cublas.so and the two undefined symbols can be found:

> dongxiao@178-ubuntu ~/working/tensorflow                                                                                                                                  
> (base) > $ nm -D /usr/local/cuda/lib64/libcublas.so | grep "cublasGemmStridedBatchedEx"                                                                                   
> 0000000000398e70 T cublasGemmStridedBatchedEx
> dongxiao@178-ubuntu ~/working/tensorflow                                                                                                                                  
> (base) > $ nm -D /usr/local/cuda/lib64/libcublas.so | grep "cublasGemmBatchedEx"                                                                                          
> 0000000000399e20 T cublasGemmBatchedEx

**Provide the exact sequence of commands / steps that you executed before running into the problem**
```
git clone https://github.com/tensorflow/tensorflow.git
git checkout r1.14
./configure  #only enable GPU and XLA support
bazel build --verbose_failures --config=noaws --config=nogcp --config=nohdfs --config=noignite --config=nokafka --config=nonccl --action_env=LD_LIBRARY_PATH=/usr/local/cuda/lib64/ --config=cuda --config=opt //tensorflow/tools/pip_package:build_pip_package
```

**Any other info / logs**

> ERROR: /home/dongxiao/working/tensorflow/tensorflow/contrib/ffmpeg/BUILD:100:1: Linking of rule '//tensorflow/contrib/ffmpeg:gen_decode_video_op_py_py_wrappers_cc' failed (Exit 1): crosstool_wrapper_driver_is_not_gcc failed: error executing command
>   (cd /home/dongxiao/.cache/bazel/_bazel_dongxiao/09108a4ee4f3be79160332645b3550ec/execroot/org_tensorflow && \
>   exec env - \
>     LD_LIBRARY_PATH=/usr/local/cuda/lib64: \
>     PATH=/home/dongxiao/anaconda3/bin:/home/dongxiao/anaconda3/condabin:/usr/local/cuda/bin:/home/dongxiao/tools/login/node-v8.2.1-linux-x64/bin:/home/dongxiao/tools/llvm-4.0.0.src/build/bin:/home/dongxiao/tools/cfe-4.0.1.src/build/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games \
>     PWD=/proc/self/cwd \
>   external/local_config_cuda/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc -o bazel-out/host/bin/tensorflow/contrib/ffmpeg/gen_decode_video_op_py_py_wrappers_cc '-Wl,-rpath,$ORIGIN/../../../_solib_local/_U_S_Stensorflow_Scontrib_Sffmpeg_Cgen_Udecode_Uvideo_Uop_Upy_Upy_Uwrappers_Ucc___Utensorflow' -Lbazel-out/host/bin/_solib_local/_U_S_Stensorflow_Scontrib_Sffmpeg_Cgen_Udecode_Uvideo_Uop_Upy_Upy_Uwrappers_Ucc___Utensorflow -Wl,-ldl '-Wl,-rpath,$ORIGIN/,-rpath,$ORIGIN/..,-rpath,$ORIGIN/../..' -pthread -pthread -pthread -pthread -Wl,-S -Wl,-no-as-needed -pie -Wl,-z,relro,-z,now '-Wl,--build-id=md5' '-Wl,--hash-style=gnu' -no-canonical-prefixes -fno-canonical-system-headers -B/usr/bin -Wl,--gc-sections -Wl,@bazel-out/host/bin/tensorflow/contrib/ffmpeg/gen_decode_video_op_py_py_wrappers_cc-2.params)
> Execution platform: @bazel_tools//platforms:host_platform
> bazel-out/host/bin/_solib_local/_U_S_Stensorflow_Scontrib_Sffmpeg_Cgen_Udecode_Uvideo_Uop_Upy_Upy_Uwrappers_Ucc___Utensorflow/libtensorflow_framework.so.1: undefined reference to `cublasGemmBatchedEx'
> bazel-out/host/bin/_solib_local/_U_S_Stensorflow_Scontrib_Sffmpeg_Cgen_Udecode_Uvideo_Uop_Upy_Upy_Uwrappers_Ucc___Utensorflow/libtensorflow_framework.so.1: undefined reference to `cublasGemmStridedBatchedEx'
> collect2: error: ld returned 1 exit status
> Target //tensorflow/tools/pip_package:build_pip_package failed to build
> INFO: Elapsed time: 348.727s, Critical Path: 79.30s
> INFO: 1621 processes: 1621 local.
> FAILED: Build did NOT complete successfully

It seems the cublas linking options are not added in the command properly, which should be '-lcublas -L/usr/local/cuda/lib64'. But I'm not sure about that. I have not found propoer place to add these options to try.

**Comment by dongxiao92** [comment]
any comments?

**Comment by ravikyram** [comment]
@dongxiao92 

Can you please let us know the output of ./configure.py. Thanks!

**Comment by dongxiao92** [comment]
@ravikyram 
hello, the output of ./configure is listed below.

> 
> Preconfigured Bazel build configs. You can use any of the below by adding "--config=<>" to your build command. See .bazelrc for more details.
> 	--config=mkl         	# Build with MKL support.
> 	--config=monolithic  	# Config for mostly static monolithic build.
> 	--config=gdr         	# Build with GDR support.
> 	--config=verbs       	# Build with libverbs support.
> 	--config=ngraph      	# Build with Intel nGraph support.
> 	--config=numa        	# Build with NUMA support.
> 	--config=dynamic_kernels	# (Experimental) Build kernels into separate shared objects.
> Preconfigured Bazel build configs to DISABLE default on features:
> 	--config=noaws       	# Disable AWS S3 filesystem support.
> 	--config=nogcp       	# Disable GCP support.
> 	--config=nohdfs      	# Disable HDFS support.
> 	--config=noignite    	# Disable Apache Ignite support.
> 	--config=nokafka     	# Disable Apache Kafka support.
> 	--config=nonccl      	# Disable NVIDIA NCCL support.
> Configuration finished
>

**Comment by dongxiao92** [comment]
guys, any updates?

**Comment by odinsbane** [comment]
I suspect that TF1.14 and cuda 9.1 are not compatible. I have the same issue currently, and I am trying to switch to 10.1 to see if it builds. I think this issue is actually why I have been using TF 1.13.

**Comment by gadagashwini** [comment]
@dongxiao92, Tensorflow 1.14 supports CUDA 10.0 and cuDNN 7.4.
Please take a look at [tested build configuration](https://www.tensorflow.org/install/source#gpu).

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.
