### ISSUE TITLE
Setting inputs tf.keras.Model

### ISSUE THREAD

**Issue by RomanSteinberg** [tensorflow/tensorflow#33913]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes  
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Google Colab (see link below)
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: -  
- TensorFlow installed from (source or binary): binary  
- TensorFlow version (use command below): 2.0.0
- Python version: 3.6
- Bazel version (if compiling from source): - 
- GCC/Compiler version (if compiling from source): - 
- CUDA/cuDNN version: -
- GPU model and memory: -

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
Input shapes are not determined automatically which leads to impossibility to save a custom keras model.

**Describe the expected behavior**
Input shapes should be derived automatically. And it should be possible to save custom keras model. 

**Code to reproduce the issue**
[Gist](https://gist.github.com/RomanSteinberg/c4a47470ab1c06b0c45fa92d07afe2e3) which is the part of  [Colab example](https://colab.research.google.com/github/tensorflow/docs/blob/master/site/en/guide/keras/custom_layers_and_models.ipynb).

**Other info / logs**
There is an [Colab example](https://colab.research.google.com/github/tensorflow/docs/blob/master/site/en/guide/keras/custom_layers_and_models.ipynb) which demonstrates the problem. The part "Putting it all together" demonstrates the training of VAE. If you try to save model `vae.save('vae')` you obtain an error
```
ValueError: Model <__main__.VariationalAutoEncoder object at 0x7fde216170f0> cannot be saved because the input shapes have not been set. Usually, input shapes are automatically determined from calling .fit() or .predict(). To manually set the shapes, call model._set_inputs(inputs).
```
But it is impossible to add such line to `__init__` or `call` method. The only workaround I found is to add
```
if step == 0 and epoch == 0:
     vae._set_inputs(x_batch_train)
```
in the training loop. It is not straight forward. Anyway, input shapes should be determined while training without this code.

**Comment by jvishnuvardhan** [comment]
@RomanSteinberg I tried running the example and then saved model (`vae.save("./my_model")`) without any issue. Please check [the gist here](https://colab.sandbox.google.com/gist/jvishnuvardhan/bd3e400db9d5dbfaa328a6f41ffc9b89/custom_layers_and_models.ipynb). Please elaborate on what is missing and what feature you are requesting. Thanks

**Comment by jvishnuvardhan** [comment]
@RomanSteinberg did you had a chance to look at my gist. Please close the issue if it was resolved already. Thanks!

**Comment by RomanSteinberg** [comment]
@jvishnuvardhan sorry, for being out of github. I checked your gist and it uses nightly build and version tf 2.1.0. I specified tf 2.0.0 in my starting post. Tomorrow I'll check more carefully and if this problem is resolved in tf 2.1.0 I will close the issue.

**Comment by RomanSteinberg** [comment]
@jvishnuvardhan your gist hasn't solved this issue. 
I ran first cell of your gist. It install tf 2.1.0-dev20191201 and asked me to restart runtime. I did it and ran all cells before section 'Putting it all together' and trained vae for 1 epoch. I've got [the same issue](http://i.imgur.com/6FhueIr.png). 

Second experiment. I restarted runtime and ran all cells including section 'Putting it all together' cells. There are two training processes. First uses loops which causes the error I mentioned earlier and second uses `vae.fit` method. It overwrites variable `vae` and I tried to save this new variable. It [succeeds with warning](http://i.imgur.com/8JgLtqJ.png). So, it means that the problem is in the training process which uses loops instead of `fit` method.

**Comment by RomanSteinberg** [comment]
@jvishnuvardhan it seems that a month has passed without any activity. I think that possibility to save model is a core requirement to train a model. May be it is time to raise the priority. What do you think?

**Comment by RomanSteinberg** [comment]
@omalleyt12 the status of this issue is _awaiting tensorflower_. Is it about you? May be you need to change status or something?

**Comment by omalleyt12** [comment]
@RomanSteinberg Thanks for the issue!

This is fixed in the latest nightly: `pip install -U tf-nightly`
