### ISSUE TITLE
tf.compat purpose may be misstated

### ISSUE THREAD

**Issue by raffaem** [tensorflow/tensorflow#33922]
## URL(s) with the issue
https://www.tensorflow.org/api_docs/python/tf/compat

## Description of issue (what needs changing):
Docs say

> Functions for Python 2 vs. 3 compatibility.

But on [StackOverflow they told me that](https://stackoverflow.com/questions/58631390/what-is-the-purpose-of-tf-compat)

> The documentation for the module about Python should actually be changed. Originally, tf.compat only held functions for that purpose (and it was like that until 1.13, see all module documentation). However, it was later repurposed for TensorFlow version compatibility.

**Comment by lamberta** [comment]
Good catch, thanks.
Should probably also point to the migration guide: https://www.tensorflow.org/guide/migrate
