### ISSUE TITLE
Laconic error when validation_steps ommitted for model.fit in TF 2.0.0

### ISSUE THREAD

**Issue by MikeOfZen** [tensorflow/tensorflow#33939]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): **Colab**
- TensorFlow version (use command below): v2.0.0-rc2-26-g64c3d38 2.0.0
- Python version: 3.6.8
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory: **TPU selected Colab**

**Describe the current behavior**
When running the script below on TF 1.15, it runs well throughout.
Running in TF 2.0, it crashes on the validation stage of the first epoch.
if `validation_steps` in `model.fit` is included it does run throughout.
however, if it's omitted (which is natural to assume, as the dataset itself is not repeated)
a strange error message `TypeError: 'function' object is not subscriptable` is given.

**Describe the expected behavior**
Either, TF 2 should behave similarly to TF 1, ie use up the entire validation set.
Or report a more informative error regarding 'validation_steps' requirement (similar to the error if steps_per_epoch are omitted for the training data).

**Code to reproduce the issue**
```
%tensorflow_version 2.x  #(commented out for TF 1.x case)
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt
import tensorflow_datasets as tfds
import os

resolver = tf.distribute.cluster_resolver.TPUClusterResolver(tpu='grpc://' + os.environ['COLAB_TPU_ADDR'])
tf.config.experimental_connect_to_cluster(resolver)
tf.tpu.experimental.initialize_tpu_system(resolver)
strategy = tf.distribute.experimental.TPUStrategy(resolver)

IMG_HEIGHT=IMG_WIDTH=200
BATCH_SIZE=128

def create_model():
  model = tf.keras.models.Sequential()
  model.add(tf.keras.layers.BatchNormalization(input_shape=(IMG_HEIGHT,IMG_WIDTH,1)))
  model.add(tf.keras.layers.Conv2D(64, (3, 3), activation='elu'))
  model.add(tf.keras.layers.MaxPooling2D(2))
  model.add(tf.keras.layers.Dropout(0.25))

  model.add(tf.keras.layers.BatchNormalization(input_shape=(IMG_HEIGHT,IMG_WIDTH,3)))
  model.add(tf.keras.layers.Conv2D(64, (3, 3), activation='elu'))
  model.add(tf.keras.layers.MaxPooling2D(2))
  model.add(tf.keras.layers.Dropout(0.25))

  model.add(tf.keras.layers.BatchNormalization(input_shape=(IMG_HEIGHT,IMG_WIDTH,3)))
  model.add(tf.keras.layers.Conv2D(64, (5, 5), activation='elu'))
  model.add(tf.keras.layers.MaxPooling2D(2))
  model.add(tf.keras.layers.Dropout(0.25))

  model.add(tf.keras.layers.BatchNormalization())
  model.add(tf.keras.layers.Conv2D(128, (3, 3),  activation='elu'))
  model.add(tf.keras.layers.MaxPooling2D(2))
  model.add(tf.keras.layers.Dropout(0.25))

  model.add(tf.keras.layers.BatchNormalization())
  model.add(tf.keras.layers.Conv2D(256, (3, 3),  activation='elu'))
  #model.add(tf.keras.layers.MaxPooling2D(2))
  model.add(tf.keras.layers.Dropout(0.25))

  model.add(tf.keras.layers.BatchNormalization())
  model.add(tf.keras.layers.Conv2D(512, (3, 3),  activation='elu'))
  model.add(tf.keras.layers.MaxPooling2D(2))
  model.add(tf.keras.layers.Dropout(0.25))

  model.add(tf.keras.layers.Flatten())
  model.add(tf.keras.layers.Dense(256))
  model.add(tf.keras.layers.Activation('elu'))
  model.add(tf.keras.layers.Dropout(0.5))
  model.add(tf.keras.layers.Dense(10))
  model.add(tf.keras.layers.Activation('softmax'))
  return model


with strategy.scope():
  train_ds = (tfds.load("mnist:3.*.*", split="train", as_supervised=True, try_gcs=True)
    .map(lambda image,label:(tf.image.convert_image_dtype(image, tf.float32),label))
    .map(lambda image,label:(tf.image.resize(image,(IMG_HEIGHT,IMG_WIDTH)),label))
    #.map(lambda image,label:(tf.cast(image, tf.float32)/255.0,tf.cast(label, tf.float32)))
    .batch(BATCH_SIZE))

  #distributed_train_ds=strategy.experimental_distribute_dataset(train_ds)

  validation_ds = (tfds.load("mnist:3.*.*", split="test", as_supervised=True, try_gcs=True)
    .map(lambda image,label:(tf.image.convert_image_dtype(image, tf.float32),label))
    .map(lambda image,label:(tf.image.resize(image,(IMG_HEIGHT,IMG_WIDTH)),label))
    #.map(lambda image,label:(tf.cast(image, tf.float32)/255.0,tf.cast(label, tf.float32)))
    .batch(BATCH_SIZE))

  #distributed_validation_ds=strategy.experimental_distribute_dataset(validation_ds)

  model=create_model()
  model.compile(
        optimizer=tf.keras.optimizers.Adam(),
        loss="sparse_categorical_crossentropy",
        metrics=['sparse_categorical_accuracy'])

model.fit(train_ds,epochs=3,steps_per_epoch=100,validation_data=validation_ds)
```
this produces this output, after going through the training fine, it crashes on the validation set
```
Train on 100 steps
Epoch 1/3
 99/100 [============================>.] - ETA: 0s - loss: 1.4453 - sparse_categorical_accuracy: 0.7015
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-10-fd27085b00aa> in <module>()
----> 1 model.fit(train_ds,epochs=3,steps_per_epoch=100,validation_data=validation_ds)

5 frames
/tensorflow-2.0.0/python3.6/tensorflow_core/python/keras/engine/training_utils.py in check_num_samples(ins, batch_size, steps, steps_name)
    425     return None
    426 
--> 427   if hasattr(ins[0], 'shape'):
    428     return int(ins[0].shape[0])
    429   return None  # Edge case where ins == [static_learning_phase]

TypeError: 'function' object is not subscriptable

```
**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by karmel** [comment]
We should minimally be able to improve the error message here. @yhliang2018 will take a look, but if you are interested in contributing a fix, please let us know.

**Comment by yhliang2018** [comment]
@MikeOfZen This issue should have been fixed. Can you verify it with tf-nightly? If the error is gone, feel free to close the issue.

**Comment by jvishnuvardhan** [comment]
@MikeOfZen As mentioned by @yhliang2018 , this was resolved `TF2.2.0-rc2`. Please check the [gist here](https://colab.research.google.com/gist/jvishnuvardhan/bbdb01789e1f322d5ddf16f329109309/untitled49.ipynb). Thanks!

Can you please verify and close the issue? Thanks!

**Comment by goldiegadde** [comment]
Closing this issue as this is fixed in the latest upcoming release as well as fix is available in tf-nightly. @MikeOfZen Please reopen if you are still running into issues. 
Thanks!
