### ISSUE TITLE
Remove h5py hard dependency to support python 3.8 on Ubuntu 18.04

### ISSUE THREAD

**Issue by yongtang** [tensorflow/tensorflow#33935]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using): master
- Are you willing to contribute it (Yes/No): yes

**Describe the feature and the current behavior/state.**

At the moment, I have been able to build tensorflow master on Ubuntu 18.04 with Python 3.8. However, the generated wheel package still could not be installed because `h5py` could not be installed on Ubuntu 18.04 with python 3.8 support.

Note I am using python 3.8 deadsnake/ppa.

I checked the dependency maps of pip. It looks like h5py is not a hard dependency as in tensorflow h5py is dynamically loaded.

If h5py could be removed from the pip requirement, then I think tensorflow could fully support python 3.8.

**Will this change the current api? How?**

n/a

**Who will benefit with this feature?**

python 3.8 support for tensorflow

**Any Other info.**

**Comment by yongtang** [comment]
The h5py dependency seems to come from keras_applications. Have opened an issue in:

https://github.com/keras-team/keras-applications/issues/147

to see if it is possible to remove h5py from keras_applications.

**Comment by yongtang** [comment]
Added a PR:

https://github.com/keras-team/keras-applications/pull/148

to remove hard dependency of h5py from Keras-applications.

**Comment by gunan** [comment]
not just h5py, grpcio is also another dependency that still does not have python 3.8.
Moreover, h5py now has python 3.8 support on windows. not sure about linux.
