### ISSUE TITLE
logdir not recognized as a keyword argument when fitting a DNNRegressor

### ISSUE THREAD

**Issue by dbikard** [tensorflow/tensorflow#3394]
Hi,
I got the following error when trying to fit a DNNRegressor with this code:
```
reg=learn.DNNRegressor(hidden_units=[200,20],activation_fn=tf.tanh)
reg.fit(X_train,Y_train,steps=1000,logdir='/tmp/')
```
TypeError: fit() got an unexpected keyword argument 'logdir'

Was the option to monitor a regressor not implemented yet?
Thanks,
David

**Comment by terrytangyuan** [comment]
Please use model_dir in the constructor

**Comment by dbikard** [comment]
Using model_dir in the constructor still gives me the same error
```
reg=learn.DNNRegressor(hidden_units=[100,100],activation_fn=tf.tanh,model_dir='/DNN/')
reg.fit(X_train,Y_train,steps=100,monitors=[val_monitor],logdir='/DNN/')

> TypeError: fit() got an unexpected keyword argument 'logdir'
```
any help is welcome.
Thanks!

**Comment by terrytangyuan** [comment]
Pass it to DNNRegressor (constructor), not fit.

**Comment by concretevitamin** [comment]
Sounds like a usage issue.  Nonetheless, StackOverflow is a better venue.

**Comment by dbikard** [comment]
Thanks, removing logdir from fit() worked, and I was able to launch tensorboard. I was mislead by the usage reported here: http://terrytangyuan.github.io/2016/03/14/scikit-flow-intro/
