### ISSUE TITLE
Visualize accuracy on tensorboard

### ISSUE THREAD

**Issue by abdou31** [tensorflow/tensorflow#33941]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):binary
- TensorFlow version (use command below):1.13.1
- Python version:3.6.4
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:9/7.4
- GPU model and memory: Nvidia Geforce 840m 4 Go

**Describe the current behavior**
Hello,
I'm trained a model and I have all .ckpts files with `graph.pbtxt` and `checkpoint` file.
I would like to visualize all parameters, for e.g ( accuracy , precision , valid loss and train loss ) using Tensorboard.
The problem is that I can only visualize the loss and the learning_rate graph

How can I see all the metrics and graphs on Tensorboard?

**Comment by rmothukuru** [comment]
@abdou31,
As per my understanding, you might be using the code similar to that shown below, as shown in [this link](https://www.tensorflow.org/tensorboard/scalars_and_keras#training_the_model_and_logging_loss) 

`model.compile(loss='mse', # keras.losses.mean_squared_error    optimizer=keras.optimizers.SGD(lr=0.2))`

By adding the line, `metrics=['accuracy']`, you should be able to visualize the Accuracy in Tensorboard. Code should be as shown below:

```
model.compile(loss='mse', # keras.losses.mean_squared_error
    metrics=['accuracy'],
    optimizer=keras.optimizers.SGD(lr=0.2),)
```

Please let us know if it works. Thanks!

**Comment by abdou31** [comment]
Sorry, for some false information.
I can see only the variable of `global_steps` and `loss`, not `learning_rate` and `loss` variables as mentioned in the image below:

![image](https://user-images.githubusercontent.com/19480228/68116957-5bfc8400-fefc-11e9-9cc2-49d0cf2d32ec.png)

For the code , I do not have used keras implementation , I have used estimator and that was some of my code:
```python
if mode == tf.estimator.ModeKeys.PREDICT:
        return tf.estimator.EstimatorSpec(mode=mode, predictions=predictions_dict)

    # Calculate loss using mean squared error.
    label_tensor = tf.convert_to_tensor(labels, dtype=tf.float32)
    loss = tf.losses.mean_squared_error(
        labels=label_tensor, predictions=logits)

    # Configure the train OP for TRAIN mode.

    if mode == tf.estimator.ModeKeys.TRAIN:
        optimizer = tf.train.AdamOptimizer(learning_rate=0.0001) # Reducing the learning rate value from 0.001 to 0.0001
        train_op = optimizer.minimize(
            loss=loss,
            global_step=tf.train.get_global_step()
            )
        return tf.estimator.EstimatorSpec(
            mode=mode,
            loss=loss,
            train_op=train_op,
            export_outputs={'marks': tf.estimator.export.RegressionOutput(logits)})

    # Add evaluation metrics (for EVAL mode)
    eval_metric_ops = {
        "accuracy": tf.metrics.accuracy(
            labels=label_tensor,
            predictions=logits)}
    return tf.estimator.EstimatorSpec(
        mode=mode, loss=loss, eval_metric_ops=eval_metric_ops)

```

What should I change?

**Comment by rmothukuru** [comment]
@abdou31,
Can you please check [this link](https://towardsdatascience.com/first-contact-with-tensorflow-estimator-69a5e072998d) where the Model is built using Estimators and Accuracy is Visualized in Tensorboard. 
Thanks!

**Comment by abdou31** [comment]
I have tried what is mentionned in the link but , I go this error:
>ValueError: Passed (<tf.Tensor 'accuracy/value:0' shape=() dtype=float32>, <tf.Tensor 'accuracy/update_op:0' shape=() dtype=float32>) should have graph attribute that is equal to current graph <tensorflow.python.framework.ops.Graph object at 0x0000018B36721DA0>.


That was what I have added :

```python 
 accuracy=tf.metrics.accuracy(labels=label_tensor,predictions=logits)
    # Create train hook list to visualize loss , accuracy and global_steps

    train_hook_list=[]
    train_tensors_log={"accuracy":accuracy,"loss":loss,"global_steps":tf.train.get_global_step()}
    train_hook_list.append(tf.train.LoggingTensorHook(tensors=train_tensors_log,every_n_iter=100))
    # Configure the train OP for TRAIN mode.

    if mode == tf.estimator.ModeKeys.TRAIN:
        optimizer = tf.train.AdamOptimizer(learning_rate=0.0001) # Reducing the learning rate value from 0.001 to 0.0001
        train_op = optimizer.minimize(
            loss=loss,
            global_step=tf.train.get_global_step()
            )
        return tf.estimator.EstimatorSpec(
            mode=mode,
            loss=loss,
            train_op=train_op,
            training_hooks=train_hook_list,
            export_outputs={'marks': tf.estimator.export.RegressionOutput(logits)})

```

**Comment by gowthamkpr** [comment]
To solve the error please go through the following [question](https://stackoverflow.com/questions/42799041/valueerror-passed-tensor-should-have-graph-attribute-that-is-equal-to-curr) @abdou31

**Comment by gowthamkpr** [comment]
@abdou31 Were you able to solve the probe using the recommendation above? Thanks!

**Comment by abdou31** [comment]
No . 
Because my problem is related to regression not classification

**Comment by nfelt** [comment]
Can you try just adding `tf.summary.scalar("accuracy", accuracy)` to your estimator model function, below where you define the accuracy metric?

**Comment by abdou31** [comment]
@nfelt sorry but the main problem here is a regression problem. There is no accuracy in regression

**Comment by nfelt** [comment]
I asked about accuracy because that's what was shown in the sample of your model function.  If that's not the model function and metric you're interested in getting working, can you post the details of what those are and what the specific problem is?

**Comment by abdou31** [comment]
@nfelt , The problem is I would like to show accuracy in Tensorboard after training my model.
I'm working on a model that predict eye landmarks in real-time, I would like to tell you that this is related to a regression problem, not a classification problem.
Do you have any idea how can I see the correct accuracy ( summary graph ) on Tensorboard ?
Note: the original project that I work on it is CNN facial Facial landmark of Yin Guibang ,

**Comment by Banjerd-pkt** [comment]
> 
> 
> I have tried what is mentionned in the link but , I go this error:
> 
> > ValueError: Passed (<tf.Tensor 'accuracy/value:0' shape=() dtype=float32>, <tf.Tensor 'accuracy/update_op:0' shape=() dtype=float32>) should have graph attribute that is equal to current graph <tensorflow.python.framework.ops.Graph object at 0x0000018B36721DA0>.
> 
> That was what I have added :
> 
> ```python
>  accuracy=tf.metrics.accuracy(labels=label_tensor,predictions=logits)
>     # Create train hook list to visualize loss , accuracy and global_steps
> 
>     train_hook_list=[]
>     train_tensors_log={"accuracy":accuracy,"loss":loss,"global_steps":tf.train.get_global_step()}
>     train_hook_list.append(tf.train.LoggingTensorHook(tensors=train_tensors_log,every_n_iter=100))
>     # Configure the train OP for TRAIN mode.
> 
>     if mode == tf.estimator.ModeKeys.TRAIN:
>         optimizer = tf.train.AdamOptimizer(learning_rate=0.0001) # Reducing the learning rate value from 0.001 to 0.0001
>         train_op = optimizer.minimize(
>             loss=loss,
>             global_step=tf.train.get_global_step()
>             )
>         return tf.estimator.EstimatorSpec(
>             mode=mode,
>             loss=loss,
>             train_op=train_op,
>             training_hooks=train_hook_list,
>             export_outputs={'marks': tf.estimator.export.RegressionOutput(logits)})
> ```
> 
> **Update**:
> 
> I solved this problem, in training it appears the accuracy:
> 
> ![zzssacuu](https://user-images.githubusercontent.com/19480228/68469772-1c46dc80-021b-11ea-9c0e-1eaef8d0c6ad.PNG)
> 
> But when I try to visualize the accuracy on Tensorboard, I didn't get it :
> 
> ![accurrc](https://user-images.githubusercontent.com/19480228/68469814-3680ba80-021b-11ea-8430-0ba733e0a7a3.PNG)
> 
> What is the problem here??

where I can add your code for show accuracy when training my model

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.
