### ISSUE TITLE
ValueError: Shapes (8334, 256) and (8335, 256) are incompatible

### ISSUE THREAD

**Issue by TheBlackPlague** [tensorflow/tensorflow#33948]
# **System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): 
Two OS used:
  - Windows 10
  - Google Compute Engine (GPU) OS (whatever that might be?)
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.0.0 (on both OS)
- Python version: 
  - Windows 10 (running Python 3.6.6)
  - Google Compute Engine OS (running Python 3.6)

# **Describe the current behavior**
A model is compiled and trained using `script A` on the Google Compute Engine. The weights are saved separately rather than altogether due to #33947 , using the `model.save_weights()`.

The weights are then saved as a zip, and transferred to a Windows-based machine.

On the Windows-based machine, the same code is run to compile the model but instead of training the model again - the weights are loaded using `model.load_weights()`.

This results in a 
```
ValueError: Shapes (8334, 256) and (8335, 256) are incompatible
```

# **Describe the expected behavior**
A model is compiled and trained using `script A` on the Google Compute Engine. The weights are saved separately rather than altogether due to #33947 , using the `model.save_weights()`.

The weights are then saved as a zip, and transferred to a Windows-based machine.

On the Windows-based machine, the same code is run to compile the model but instead of training the model again - the weights are loaded using `model.load_weights()`.

The weights are loaded successfully.

# **Possible Cause**
**Model Summary on the two machines are different... which is likely causing the issue.**
- Google Compute Engine (GPU):
```
Model: "transformer"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
==================================================================================================
inputs (InputLayer)             [(None, None)]       0                                            
__________________________________________________________________________________________________
dec_inputs (InputLayer)         [(None, None)]       0                                            
__________________________________________________________________________________________________
enc_padding_mask (Lambda)       (None, 1, 1, None)   0           inputs[0][0]                     
__________________________________________________________________________________________________
encoder (Model)                 (None, None, 256)    3187968     inputs[0][0]                     
                                                                 enc_padding_mask[0][0]           
__________________________________________________________________________________________________
look_ahead_mask (Lambda)        (None, 1, None, None 0           dec_inputs[0][0]                 
__________________________________________________________________________________________________
dec_padding_mask (Lambda)       (None, 1, 1, None)   0           inputs[0][0]                     
__________________________________________________________________________________________________
decoder (Model)                 (None, None, 256)    3715328     dec_inputs[0][0]                 
                                                                 encoder[1][0]                    
                                                                 look_ahead_mask[0][0]            
                                                                 dec_padding_mask[0][0]           
__________________________________________________________________________________________________
outputs (Dense)                 (None, None, 8335)   2142095     decoder[1][0]                    
==================================================================================================
Total params: 9,045,391
Trainable params: 9,045,391
Non-trainable params: 0
__________________________________________________________________________________________________
```
- Windows-based Machine:
```
Model: "transformer"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to
==================================================================================================
inputs (InputLayer)             [(None, None)]       0
__________________________________________________________________________________________________
dec_inputs (InputLayer)         [(None, None)]       0
__________________________________________________________________________________________________
enc_padding_mask (Lambda)       (None, 1, 1, None)   0           inputs[0][0]
__________________________________________________________________________________________________
encoder (Model)                 (None, None, 256)    3187712     inputs[0][0]
                                                                 enc_padding_mask[0][0]
__________________________________________________________________________________________________
look_ahead_mask (Lambda)        (None, 1, None, None 0           dec_inputs[0][0]
__________________________________________________________________________________________________
dec_padding_mask (Lambda)       (None, 1, 1, None)   0           inputs[0][0]
__________________________________________________________________________________________________
decoder (Model)                 (None, None, 256)    3715072     dec_inputs[0][0]
                                                                 encoder[1][0]
                                                                 look_ahead_mask[0][0]
                                                                 dec_padding_mask[0][0]
__________________________________________________________________________________________________
outputs (Dense)                 (None, None, 8334)   2141838     decoder[1][0]
==================================================================================================
Total params: 9,044,622
Trainable params: 9,044,622
Non-trainable params: 0
__________________________________________________________________________________________________
```

# **Other info / logs**
[log.txt](https://github.com/tensorflow/tensorflow/files/3801603/log.txt)

**Comment by ravikyram** [comment]
In order to expedite the trouble-shooting process, please provide a minimal standalone code to reproduce the issue reported here. Thanks!

**Comment by TheBlackPlague** [comment]
The minimal standalone code is literally my whole project. I'm sure TensorFlow developers can replicate this issue using Google Colab & a personal device using Attention() layers and saving model weights. @ravikyram

**Comment by jvishnuvardhan** [comment]
@TheBlackPlague I think it is difficult to find the source without a standalone code. Other than the size mismatch, number of weights of different layers is different between GCP model and the local model. Can you please take any simple model (if your model is private) from TF website and create a standalone code? Can you please mention what steps(defined model architecture, compiled, trained the model, saved_weights,.......)  you followed with little more details. Thanks!

**Comment by TheBlackPlague** [comment]
Of course. This is very similar to what I was doing and I think this may be a good replication. 

https://github.com/tensorflow/examples/blob/master/community/en/transformer_chatbot.ipynb

Hope this helps and you can reproduce.
@jvishnuvardhan

**Comment by TheBlackPlague** [comment]
Any update on this? @jvishnuvardhan

**Comment by jvishnuvardhan** [comment]
@TheBlackPlague Sorry for the very late response. Can you please provide a simple standalone code to reproduce the issue?  Recently there were couple of important updates in model saving and loading related codes. Can you please try `model.save` approach that saves everything. Thanks!

**Comment by TheBlackPlague** [comment]
Yeah this issue was fixed with the latest updates.

**Comment by jvishnuvardhan** [comment]
@TheBlackPlague Thanks for the confirmation. I will close the issue. Thanks!

**Comment by jianmosier** [comment]
@jvishnuvardhan  I have such a similar problem, and it happened on the latest version. I hope you can give me some suggestions.
my code as below:

```
%tensorflow_version 2.x
import tensorflow as tf
import numpy as np
import h5py
import t3f
import matplotlib.pyplot as plt
filename = "./video.h5"
np.random.seed(0)
with h5py.File(filename, "r") as f:
    print("Keys: %s" % f.keys())
    a_group_key = list(f.keys())[0]
    data = list(f[a_group_key])
    data_np = np.array(data)
data_tensor = tf.convert_to_tensor(data_np)
shape = [107]+[60]+[80]+[3]
# A is large tt-ranks tensor
A = t3f.to_tt_tensor(data_tensor)
# Create an X variable.
init_X = t3f.random_tensor(shape, tt_rank=3)
X = t3f.get_variable('X', initializer=init_X)
def step():
    gradF = X - A
    riemannian_grad = t3f.riemannian.project(gradF, X)
    alpha = 1.0
    t3f.assign(X, t3f.round(X - alpha * riemannian_grad, max_tt_rank=2))
    return 0.5 * t3f.frobenius_norm_squared(X - A)
log = []
for i in range(1000):
    F = step()
    if i % 10 == 0:
        print(F)
    log.append(F.numpy())
```
Exit:
> ---------------------------------------------------------------------------
> ValueError                                Traceback (most recent call last)
> <ipython-input-34-e5f2500494ee> in <module>()
>       1 log = []
>       2 for i in range(1000):
> ----> 3     F = step()
>       4     if i % 10 == 0:
>       5         print(F)
> 
> 4 frames
> /usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/tensor_shape.py in assert_is_compatible_with(self, other)
>    1115     """
>    1116     if not self.is_compatible_with(other):
> -> 1117       raise ValueError("Shapes %s and %s are incompatible" % (self, other))
>    1118 
>    1119   def most_specific_compatible_shape(self, other):
> 
> ValueError: Shapes (1, 107, 3) and (1, 107, 2) are incompatible
> 

But the data_tensor's shape is [107]+[60]+[80]+[3], it's same with A or X, I'm confused.

**Comment by jvishnuvardhan** [comment]
@jianmosier Please create a new issue with the content you mentioned above. It will be easy for the community to follow. Please ping me there. Thanks!

**Comment by Malithi-gif** [comment]
raise ValueError("Shapes %s and %s are incompatible" % (self, other))
ValueError: Shapes (2, 56, 56, 1024) and () are incompatible

Can anyone help me?
