### ISSUE TITLE
NotImplementedError: Layers with arguments in `__init__` must override `get_config`

### ISSUE THREAD

**Issue by TheBlackPlague** [tensorflow/tensorflow#33947]
Related to #32662

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): 
`Google Compute Engine (GPU)` running `Intel(R) Xeon(R) CPU @ 2.30GHz` 
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.0.0
- Python version: 3.6
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Describe the current behavior**
Model is unable to be saved using `model.save()`

**Describe the expected behavior**
Model is saved successfully.

**Code to reproduce the issue**
Code to reproduce this issue can be found on the related Stackoverflow page: https://stackoverflow.com/q/58678836/12315223

Another good reproduction of this since I'm using `Attention()` layers is found here:
https://github.com/tensorflow/tensorflow/issues/33380#issuecomment-542931948

**Other info / logs**
[log.txt](https://github.com/tensorflow/tensorflow/files/3801439/log.txt)

**Comment by TheBlackPlague** [comment]
This issue has been resolved thanks to a "hacky solution".

Solution:
https://stackoverflow.com/a/58680354/12315223

I'll leave this issue open in-case a better solution is provided on Stackoverflow or here. Feel free to close it here if no solution better than mine is available.

**Comment by ymodak** [comment]
Closing this issue since its resolved. Feel free to reopen if necessary. Thanks!
