### ISSUE TITLE
Tensorflow Android Library doesn't define targetSdkVersion

### ISSUE THREAD

**Issue by ori-6over6** [tensorflow/tensorflow#33949]
Hey,
I'm using your android tensorflow library for an android library I'm working on.

When adding your sdk I automatically see 2 additional permissions - Phone and Storage.
I checked and turns our the permissions are added because your SDK doesn't define a targetSdkVersion, so by default the targetSdkVersion of your sdk is considered 1, and according to [android docs](https://developer.android.com/studio/build/manifest-merge.html#implicit_system_permissions) the permissions are added automatically in such case.

Please let me know if you can solve my issue (maybe by adding targetSdkVersion to your project?)

**System information**
The android dependency I'm using is: implementation 'org.tensorflow:tensorflow-android:1.13.1'

Thanks!

**Comment by gadagashwini** [comment]
@ori-6over6,
Please follow the instructions mentioned in this [link](https://www.tensorflow.org/lite/guide/android) for Tensorflow android. Thanks!

**Comment by ori-6over6** [comment]
@gadagashwini I'll check it out. Thanks!

**Comment by gadagashwini** [comment]
@ori-6over6, Were you able to resolve this issue. Thanks!

**Comment by ori-6over6** [comment]
@gadagashwini yeah the permissions issue is solved when using the library you recommended, thanks!
We are currently working on integrating this library to work with our model

**Comment by ori-6over6** [comment]
@gadagashwini Hey, we are trying to convert our pb model to a tflite model.
Our model is frozen. Is it possible to convert it?

**Comment by gadagashwini** [comment]
@ori-6over6, Here is the [link](https://www.tensorflow.org/lite/convert/python_api) for Tensorflow lite converter.
Thanks!

**Comment by ori-6over6** [comment]
@gadagashwini Thanks for the quick response!
We looked over the documentation (actually preferred the command line tool over the python api but who cares (; ). At first we couldn't convert the model because apparently [Tensorflow 2 converter doesn't support frozen models graphs](https://www.tensorflow.org/lite/convert/python_api#formats_supported_by_tfliteconverter), so we had to use Tensorflow 1 for the conversion.
Right now we have a tflite version of our model and we are in the process of making it work.
Will let you know once we are successful. Thanks again!

**Comment by gadagashwini** [comment]
@ori-6over6, Is this still an issue.

**Comment by ori-6over6** [comment]
Hey @gadagashwini, we were using [MTCNN4Android](https://github.com/vcvycy/MTCNN4Android) for detecting eyes using Tensorflow so we are now trying to use an [equivalent version for TFLite](https://github.com/syaringan357/Android-MobileFaceNet-MTCNN-FaceDeSpoofing), but their model detection is less accurate.
Anyway the TFLite integration seems to be working and the extra permissions are no longer needed, so I guess this issue can be considered solved. Thanks for the help!

**Comment by gadagashwini** [comment]
@ori-6over6, Closing the issue since its resolved. Thanks!
