### ISSUE TITLE
Is it possible to reduce the number of kernels/filters in a trained model in Tensorflow?

### ISSUE THREAD

**Issue by Safiullahmarwat** [tensorflow/tensorflow#33958]
If I have a trained model, where I want to retrain the same model, with few filters/kernel removed from the existing model. e.g. 
(The sam ecan be found [here](https://stackoverflow.com/questions/58313035/how-to-reduce-the-number-of-kernels-filters-in-a-trained-model-in-tensorflow?noredirect=1&lq=1), i searched, but came to know that TF dose not support variable resizing, only reshape is supported)
`conv1 = tf.get_variable('conv1_1', shape=(11, 11, 3, 64), initializer=tf.contrib.layers.xavier_initializer()),`
and I want to resize this tensor such that it has the shape of (11, 11, 3, 20) but the same name and position, mean exactly the same variable. Advance thanks for the help.

I have tried tf.reshape but it gives me error of not matching the number of elements in a and b I have also tried tf.assign(a,b, validate_shape=false)

```
self.weights = {
    'conv1_': tf.get_variable('conv1_l1', shape=(11, 11, 3, 64), initializer=tf.contrib.layers.xavier_initializer()),
    'conv2_': tf.get_variable('conv2_l1', shape=(7, 7, 64, 128), initializer=tf.contrib.layers.xavier_initializer())
}
```

**Comment by ravikyram** [comment]
Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version. Also, did you compile from source or install a binary?

Make sure you also include the exact command if possible to produce the output included in your test case. If you are unclear what to include see the issue template displayed in [the Github new issue template](https://github.com/tensorflow/tensorflow/issues/new/choose).

We ask for this in the issue submission template, because it is really difficult to help without that information. Thanks!

**Comment by Safiullahmarwat** [comment]
@ravikyram brother I updated the post, but i think its not allowing any update. I am giving you the details here. Please let me know should you need more details. Thank you. 
My Python version 3.7 and TF version 1.4 (installed via 'pip install') on Windows. 
further, for example I have the following code
```
self.weights = {
    'conv1_': tf.get_variable('conv1_l1', shape=(11, 11, 3, 64), initializer=tf.contrib.layers.xavier_initializer()),
    'conv2_': tf.get_variable('conv2_l1', shape=(7, 7, 64, 128), initializer=tf.contrib.layers.xavier_initializer())
}
```
and I want to resize any of these variable, such that its shape become like 'shape=(11, 11, 3, 20)' during the training. 
May be, TF have such support, but I tried my best to find any such command, but failed. 
thank you

**Comment by ravikyram** [comment]
@Safiullahmarwat 

Can you please confirm TF version you are using it is 1.4 or 1.14?

**Comment by Safiullahmarwat** [comment]
@ravikyram Sir,I am soo sory, my TF version is 1.14.0

**Comment by Safiullahmarwat** [comment]
Hi there! should i wait for any response? I dont know why the @tensorflowbutler removed the awaiting response :)

**Comment by ymodak** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.
Thanks!

**Comment by Safiullahmarwat** [comment]
I think there is no such question on StackOveflow. I asked the question on the [forum ](https://stackoverflow.com/questions/58313035/how-to-reduce-the-number-of-kernels-filters-in-a-trained-model-in-tensorflow/58315394) but nobody answered me, thats why i requested for the feature. If you know any link toward such question, please let me know. Thank you 🥇
