### ISSUE TITLE
tf.volume.resize 

### ISSUE THREAD

**Issue by wanderine** [tensorflow/tensorflow#33951]
**System information**
- TensorFlow version (you are using): 1.14
- Are you willing to contribute it (Yes/No): Yes

**Describe the feature and the current behavior/state.**

tf.image.resize works for 2D images, would be nice with tf.volume.resize for 3D volumes, instead of using tf.keras.layers.UpSampling3D that only performs nearest neighbor interpolation.

**Will this change the current api? How?**

I don't think so

**Who will benefit with this feature?**

Many working with 3D data

**Any Other info.**

**Comment by prerakmody** [comment]
Is there any update on this?
Just as [(TF2.2.0) tf.image.resize](https://www.tensorflow.org/api_docs/python/tf/image/resize) offers an option for bilinear interpolation, it would be great to have a tf.volume.resize that offers trilinear interpolation.

The closest thing right now is [(TF2.2.0) tf.keras.backend.resize_volumes](https://www.tensorflow.org/api_docs/python/tf/keras/backend/resize_volumes) but that repeats elements when you look into its [source code](https://github.com/tensorflow/tensorflow/blob/v2.2.0/tensorflow/python/keras/backend.py#L2835-L2864).

**Comment by sylqiu** [comment]
+1 Please add this functionality similar to torch.nn.functional.interpolate

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.

**Comment by petoor** [comment]
Any update on this feature request? I would love to see it implemented as well.

**Comment by XXZhou25** [comment]
Same question. Will you update this feature?

**Comment by vbvg2008** [comment]
any updates?

**Comment by bhack** [comment]
It is submitted again in https://github.com/keras-team/keras/issues/16260

You could subscribe and comment there.
