### ISSUE TITLE
2 issues: tf.train.Checkpoint does not seem to save optimizer state, impossible to load_weights using skip_mismatch=True

### ISSUE THREAD

**Issue by netw0rkf10w** [tensorflow/tensorflow#33969]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes, with minor modifications from the official documentation
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Colab
- TensorFlow installed from (source or binary): `!pip install tf-nightly-gpu`
- TensorFlow version (use command below): 
- Python version: `v1.12.1-17291-ga2a3b22 2.1.0-dev20191103`

**Describe the current behavior**

1. When restoring from a tf.train.Checkpoint, training does not seem to resume from exactly where it was left off.

2. It is not possible to load pretrained weights to the same model with different output dimension, even with `skip_mismatch=True`.

**Code to reproduce the issue**
The two issues can be reproduced using [this Colab Notebook](https://colab.research.google.com/drive/1M0PDxTsXfL0lvFcsEhNTvNG-titdARYo).

**Comment by oanush** [comment]
Issue replicating for the given code. Thanks!

**Comment by mathemakitten** [comment]
Hi, are there any updates on this? Seeing this issue on `tf-nightly==2.2.0.dev20200119` also using model checkpoints saved via `checkpoint.save`. Checking `optimizer.iterations` after reinstantiation, it is always reset to be 0.

**Comment by jvishnuvardhan** [comment]
@netw0rkf10w @mathemakitten Is this still an issue? Can you please check with latest version `TF2.2` and `TF-nightly` and let us know how it perform. I tested your code with `tf-nightly`. Regarding you two issues

Issue 1 : This was resolved as the loss after restoring checkpoint is smaller.
Issue 2 (with tf format): loading of weights is based on topology when the model is a subclass model. This was the error "NotImplementedError: Weights may only be loaded based on topology into Models when loading TensorFlow-formatted weights (got by_name=True to load_weights)."

Issue 2 (with h5 format): Approach should be to call model on some data to initiate the weights and then assign the weights. Currently it throws an error "ValueError: Unable to load weights saved in HDF5 format into a subclassed Model which has not created its variables yet. Call the Model first, then load the weights."

Please check [this](https://www.tensorflow.org/guide/checkpoint) resource for checkpointing and [this](https://www.tensorflow.org/guide/keras/save_and_serialize) is for save_load subclass models.

Check the example from the above link
```
# Create a simple functional model
inputs = keras.Input(shape=(784,), name='digits')
x = keras.layers.Dense(64, activation='relu', name='dense_1')(inputs)
x = keras.layers.Dense(64, activation='relu', name='dense_2')(x)
outputs = keras.layers.Dense(10, name='predictions')(x)
functional_model = keras.Model(inputs=inputs, outputs=outputs, name='3_layer_mlp')

# Define a subclassed model with the same architecture
class SubclassedModel(keras.Model):
  def __init__(self, output_dim, name=None):
    super(SubclassedModel, self).__init__(name=name)
    self.output_dim = output_dim
    self.dense_1 = keras.layers.Dense(64, activation='relu', name='dense_1')
    self.dense_2 = keras.layers.Dense(64, activation='relu', name='dense_2')
    self.dense_3 = keras.layers.Dense(output_dim, name='predictions')
  def call(self, inputs):
    x = self.dense_1(inputs)
    x = self.dense_2(x)
    x = self.dense_3(x)
    return x
  def get_config(self):
    return {'output_dim': self.output_dim, 'name': self.name}

subclassed_model = SubclassedModel(10)
# Call the subclassed model once to create the weights.
subclassed_model(tf.ones((1, 784)))

# Copy weights from functional_model to subclassed_model.
subclassed_model.set_weights(functional_model.get_weights())
```

Please verify once and close the issue if this was resolved for you. Thanks!

**Comment by mathemakitten** [comment]
Mine has been resolved, running on TF2.2. Thanks!
