### ISSUE TITLE
Cannot use dictionary embeddings metadata for keras callbacks

### ISSUE THREAD

**Issue by ouakif** [tensorflow/tensorflow#33967]
Using dictionary as embeddings_metadata does not seem to be handled correctly in the Keras callbacks v2.
Indeed, while trying to do so I get the following error message:
```ValueError: Unrecognized `Embedding` layer names passed to `keras.callbacks.TensorBoard` `embeddings_metadata` argument: dict_keys(['embedding_1', 'embedding_2'])```
After looking at the source code (see [here](https://github.com/tensorflow/tensorflow/blob/32d76ec3e633e0ef5c980b5a91a510bb71d668ed/tensorflow/python/keras/callbacks.py#L1575)), I figured that, when the metadata is not a string, it checked if the layer names was in `embedding.metadata_path`. However, this variable is never set in this case and it is an empty string by default.

Looking at how it is handled in the [v1](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/keras/callbacks_v1.py), I think the check should be done on `self.embeddings_metadata` (assuming if it is not a string it is a dictionary). So
```if layer.name in embedding.metadata_path:```
should be something like
```if layer.name in self.embeddings_metadata:```
Maybe it should be a copy of this dictionary or there should be a test to check that this is indeed a dictionary.

**Comment by gadagashwini** [comment]
@ouakif, Will it be possible to share the sample standalone code reproduce the reported issue. Thanks!

**Comment by ouakif** [comment]
I tried to run this [example](https://keras.io/examples/tensorboard_embeddings_mnist/) from the Keras website.
You can run it on a [Colab](https://colab.research.google.com/) adding ` %tensorflow_version 2.x` on the first line.
``` python
from os import makedirs
from os.path import exists, join

from tensorflow.keras.callbacks import TensorBoard
from tensorflow.keras.datasets import mnist
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, Flatten, Conv2D, MaxPooling2D
from tensorflow.keras import backend as K
import tensorflow as tf
import numpy as np

batch_size = 128
num_classes = 10
epochs = 12
log_dir = './logs'

if not exists(log_dir):
    makedirs(log_dir)

# input image dimensions
img_rows, img_cols = 28, 28

# the data, split between train and test sets
(x_train, y_train), (x_test, y_test) = mnist.load_data()

if K.image_data_format() == 'channels_first':
    x_train = x_train.reshape(x_train.shape[0], 1, img_rows, img_cols)
    x_test = x_test.reshape(x_test.shape[0], 1, img_rows, img_cols)
    input_shape = (1, img_rows, img_cols)
else:
    x_train = x_train.reshape(x_train.shape[0], img_rows, img_cols, 1)
    x_test = x_test.reshape(x_test.shape[0], img_rows, img_cols, 1)
    input_shape = (img_rows, img_cols, 1)

x_train = x_train.astype('float32')
x_test = x_test.astype('float32')
x_train /= 255
x_test /= 255

# save class labels to disk to color data points in TensorBoard accordingly
with open(join(log_dir, 'metadata.tsv'), 'w') as f:
    np.savetxt(f, y_test)

# convert class vectors to binary class matrices
y_train = tf.keras.utils.to_categorical(y_train, num_classes)
y_test = tf.keras.utils.to_categorical(y_test, num_classes)

tensorboard = TensorBoard(batch_size=batch_size,
                          embeddings_freq=1,
                          # This does not work
                          embeddings_metadata={'features': 'metadata.tsv'}
                          # I also tested this and does not work either
                          # embeddings_metadata='metadata.tsv'
                          )

model = Sequential()
model.add(Conv2D(32, kernel_size=(3, 3),
                 activation='relu',
                 input_shape=input_shape))
model.add(Conv2D(64, (3, 3), activation='relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Dropout(0.25))
model.add(Flatten())
model.add(Dense(128, activation='relu', name='features'))
model.add(Dropout(0.5))
model.add(Dense(num_classes, activation='softmax'))

model.compile(loss=tf.keras.losses.categorical_crossentropy,
              optimizer=tf.keras.optimizers.Adadelta(),
              metrics=['accuracy'])

model.fit(x_train, y_train,
          batch_size=batch_size,
          callbacks=[tensorboard],
          epochs=epochs,
          verbose=1,
          validation_data=(x_test, y_test))
score = model.evaluate(x_test, y_test, verbose=0)
print('Test loss:', score[0])
print('Test accuracy:', score[1])```

**Comment by gadagashwini** [comment]
I could reproduce the issue on colab with Tf 2.0. 
Please find the gist [here](https://colab.sandbox.google.com/gist/gadagashwini/ee2bfba3b871578892def0b1742308ac/untitled240.ipynb). Thanks!

**Comment by gowthamkpr** [comment]
@ouakif 
`embeddings_layer_names` is not supported in TensorFlow 2.0. Instead, all Embedding layers will be visualized.

For more info you can take a look at the source code [here](https://github.com/tensorflow/tensorflow/blob/1cf0898dd4331baf93fe77205550f2c2e6c90ee5/tensorflow/python/keras/callbacks.py#L1475)

Thanks!

**Comment by ouakif** [comment]
Thank you for your answer.
However, here I am trying to set `embeddings_metadata` which should be supported (see [here](https://github.com/tensorflow/tensorflow/blob/1cf0898dd4331baf93fe77205550f2c2e6c90ee5/tensorflow/python/keras/callbacks.py#L1406))
In fact, one of the issues is that `_configure_embeddings` trying to check if the layer.name is in `embedding.metadata_path` while this variable is never filled (see [here](https://github.com/tensorflow/tensorflow/blob/1cf0898dd4331baf93fe77205550f2c2e6c90ee5/tensorflow/python/keras/callbacks.py#L1531)).

**Comment by ouakif** [comment]
Here are the changes that I would suggest. Not yet tested with the nightly version https://github.com/tensorflow/tensorflow/compare/master...ouakif:correct_embeddings_metadata?expand=1

**Comment by kobayakawa-t-ko** [comment]
I have the same problem.
As someone pointed out elsewhere, the following modifications seems to work for me.
```
--- callbacks.py.org	2019-12-13 14:17:53.000000000 +0900
+++ callbacks.py	2019-12-24 10:18:56.000000000 +0900
@@ -1528,13 +1528,13 @@
           if isinstance(self.embeddings_metadata, str):
             embedding.metadata_path = self.embeddings_metadata
           else:
-            if layer.name in embedding.metadata_path:
+            if layer.name in self.embeddings_metadata:
               embedding.metadata_path = self.embeddings_metadata.pop(layer.name)
 
-    if self.embeddings_metadata:
-      raise ValueError('Unrecognized `Embedding` layer names passed to '
-                       '`keras.callbacks.TensorBoard` `embeddings_metadata` '
-                       'argument: ' + str(self.embeddings_metadata.keys()))
+#    if self.embeddings_metadata:
+#      raise ValueError('Unrecognized `Embedding` layer names passed to '
+#                       '`keras.callbacks.TensorBoard` `embeddings_metadata` '
+#                       'argument: ' + str(self.embeddings_metadata.keys()))
 
     class DummyWriter(object):
       """Dummy writer to conform to `Projector` API."""
```

**Comment by tomtang110** [comment]
> Using dictionary as embeddings_metadata does not seem to be handled correctly in the Keras callbacks v2.
> Indeed, while trying to do so I get the following error message:
> `` ValueError: Unrecognized `Embedding` layer names passed to `keras.callbacks.TensorBoard` `embeddings_metadata` argument: dict_keys(['embedding_1', 'embedding_2']) ``
> After looking at the source code (see [here](https://github.com/tensorflow/tensorflow/blob/32d76ec3e633e0ef5c980b5a91a510bb71d668ed/tensorflow/python/keras/callbacks.py#L1575)), I figured that, when the metadata is not a string, it checked if the layer names was in `embedding.metadata_path`. However, this variable is never set in this case and it is an empty string by default.
> 
> Looking at how it is handled in the [v1](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/keras/callbacks_v1.py), I think the check should be done on `self.embeddings_metadata` (assuming if it is not a string it is a dictionary). So
> `if layer.name in embedding.metadata_path:`
> should be something like
> `if layer.name in self.embeddings_metadata:`
> Maybe it should be a copy of this dictionary or there should be a test to check that this is indeed a dictionary.

Hi
could you tell me the metadata format?  Particularly for word of bag, is it the word files?
like this 
```
with open('./logs/text_classify/word.tsv','w') as f:
    for i in range(len(word2id)):
        f.write('{}'.format(id2word[i]) + '\n')
```

**Comment by richardwth** [comment]
Has this issue been solved?

I tried running the Keras example mentioned by @ouakif on Colab using TensorFlow version 2.2.0-rc3. It did not work. The following error is given:

    ValueError: Unrecognized `Embedding` layer names passed to `keras.callbacks.TensorBoard` `embeddings_metadata` argument: dict_keys(['features'])

**Comment by ghego** [comment]
+1 on this issue

**Comment by insuquot** [comment]
I ran into this error while trying to visualize the word embeddings in Tensorboard Projector (as opposed to the default word IDs). Code to reproduce below. Using method 1 in my example, I can load the metadata.tsv file manually in Projector to see the words, but I'd like to load these automatically using the `embeddings_metadata` argument.

The [documentation](https://www.tensorflow.org/api_docs/python/tf/keras/callbacks/TensorBoard) says you can provide a string with the file location/name that would apply to the Embedding layer, but from method 2 in my example, I get `AttributeError: 'str' object has no attribute 'keys'`. When I pass a dictionary as seen in method 3, I get `ValueError: Unrecognized Embedding layer names passed to keras.callbacks.TensorBoard embeddings_metadata argument: dict_keys(['embedding'])`

```
import csv
import os
from tensorflow import keras
import tensorflow as tf
import tensorflow_datasets as tfds
import time

datasets, info = tfds.load("imdb_reviews", as_supervised=True, with_info=True)

words = ['zero', 'one', 'two', 'three', 'four']
word_ids = list(range(5))
vocab_init = tf.lookup.KeyValueTensorInitializer(words, np.array(word_ids, dtype=np.int64))
table = tf.lookup.StaticVocabularyTable(vocab_init, 1)

def preprocess(X_batch, y_batch):
    X_batch = tf.strings.substr(X_batch, 0, 300)
    X_batch = tf.strings.regex_replace(X_batch, b"<br\\s*/?>", b" ")
    X_batch = tf.strings.regex_replace(X_batch, b"[^a-zA-Z']", b" ")
    X_batch = tf.strings.split(X_batch)
    return X_batch.to_tensor(default_value=b"<pad>"), y_batch

def encode_words(X_batch, y_batch):
    return table.lookup(X_batch), y_batch

train_set = datasets['train'].batch(32).map(preprocess)
train_set = train_set.map(encode_words).prefetch(1)

# save words as metadata to include in tensorboard callback
with open('metadata.tsv', 'w') as f:
    writer = csv.writer(f, delimiter='\t')
    writer.writerows(zip(['id'], ['word']))
    writer.writerows(zip(word_ids, words))
    writer.writerows(zip([5], ['oov']))

root_logdir = os.path.join(os.curdir, 'my_logs')

def get_run_logdir():
    run_id = time.strftime('run_%Y_%m_%d-%H_%M_%S')
    return os.path.join(root_logdir, run_id)

run_logdir = get_run_logdir()

embed_size = 6
model = keras.models.Sequential([
    keras.layers.Embedding(6, embed_size, input_shape=[None], name='embedding'),
    keras.layers.GRU(6, return_sequences=True),
    keras.layers.GRU(6),
    keras.layers.Dense(1, activation='sigmoid')
])
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

# three methods tried:
# 1. shows word_ids only in tensorboard projector
#tensorboard_cb = keras.callbacks.TensorBoard(run_logdir, embeddings_freq=1)
# 2. str obj has not attribute keys
#tensorboard_cb = keras.callbacks.TensorBoard(run_logdir, embeddings_freq=1, embeddings_metadata='metadata.tsv')
# 3. unrecognized embedding layer name
tensorboard_cb = keras.callbacks.TensorBoard(run_logdir, embeddings_freq=1, embeddings_metadata={'embedding': 'metadata.tsv'})

history = model.fit(train_set, epochs=1, callbacks=[tensorboard_cb])
```

**Comment by insuquot** [comment]
@rchao would love to get your feedback on this issue

**Comment by sushreebarsa** [comment]
Was able to reproduce the issue in TF v2.5 ,please check the gist [here](https://colab.research.google.com/gist/sushreebarsa/2f6cb875530a158f65ecd8f9549b6a4a/untitled25.ipynb)..Thanks !

**Comment by sushreebarsa** [comment]
Was able to replicate the issue with TF 2.6.0-dev20210606,please find the gist [here](https://colab.research.google.com/gist/sushreebarsa/28bad14c285ba2748060f095e42d3f3d/untitled242.ipynb) ..Thanks

**Comment by Saduf2019** [comment]
@ouakif 
Please post this issue on keras-team/keras repo.
To know more refer to:
https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999

**Comment by tensorflowbutler** [comment]
Hi There,

 This is a stale issue. As you are using an older version of tensorflow, we are checking to see if you still need help on this issue. Please test the issue with the latest TensorFlow (TF2.7 and tf-nightly). If the issue still persists with the newer versions of TF, please feel free to open it in [keras-team/keras](https://github.com/keras-team/keras/issues) repository by providing details about the issue and a standalone code to reproduce the issue. Thanks! 

 Please note that Keras development has moved to a separate Keras-team/keras repository to focus entirely on only Keras. Thanks!

**Comment by tilakrayal** [comment]
@ouakif ,
As commented above please feel free to close this issue here and post in Keras repo.Thanks
