### ISSUE TITLE
Can not compile the tensorflow lite example

### ISSUE THREAD

**Issue by kop57890** [tensorflow/tensorflow#33968]
When I use the command "make -f tensorflow/lite/experimental/micro/tools/make/Makefile micro_speech", it shows the error message below:
**./tensorflow/lite/experimental/micro/kernels/activation_utils.h:43:23: error: ‘signbit’ was not declared in this scope 
    return signbit(a);**
I am sure I had build this example successfully few days ago(I built it on Ubuntu 16.04 x64). Is there anything changed for this example this week? Thanks.

**Comment by gadagashwini** [comment]
@kop57890, Just to verify, did you follow this [link](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/experimental/micro/examples/micro_speech#micro-speech-example). Thanks!

**Comment by kop57890** [comment]
Yes,I did. Or can't this example able to run on the Ubuntu 16.04? Thanks!

**Comment by Jhouteddy** [comment]
Hi,
I also use the command "make -f tensorflow/lite/experimental/micro/tools/make/Makefile micro_speech"
When I run micro_speech on Ubuntu 16.04 , It does not work(As shown below)
![1](https://user-images.githubusercontent.com/41892320/68205749-fa284100-0005-11ea-8267-7c7defefc4c9.jpg)
So I use gdb to debug(As shown below)
![2](https://user-images.githubusercontent.com/41892320/68205809-26dc5880-0006-11ea-9ff8-6c33fe0f19ac.jpg)
Does micro_speech need to run on a specific version? Thanks

**Comment by redmapleleaf** [comment]
I got the same error building tensorflow lite micro:
./tensorflow/lite/experimental/micro/kernels/activation_utils.h: In function ‘float tflite::ops::micro::ActivationValFloat(TfLiteFusedActivation, float)’:
./tensorflow/lite/experimental/micro/kernels/activation_utils.h:43:23: error: ‘signbit’ was not declared in this scope
       return signbit(a);
                       ^
./tensorflow/lite/experimental/micro/kernels/activation_utils.h:43:23: note: suggested alternative:
In file included from /usr/include/c++/5/random:38:0,
                 from /usr/include/c++/5/bits/stl_algo.h:66,
                 from /usr/include/c++/5/algorithm:62,
                 from ./tensorflow/lite/experimental/micro/kernels/activation_utils.h:19,
                 from tensorflow/lite/experimental/micro/kernels/svdf.cc:20:
/usr/include/c++/5/cmath:682:5: note:   ‘std::signbit’
     signbit(_Tp __x)
     ^
tensorflow/lite/experimental/micro/tools/make/Makefile:250: recipe for target 'tensorflow/lite/experimental/micro/tools/make/gen/linux_x86_64/obj/tensorflow/lite/experimental/micro/kernels/svdf.o' failed
make: *** [tensorflow/lite/experimental/micro/tools/make/gen/linux_x86_64/obj/tensorflow/lite/experimental/micro/kernels/svdf.o] Error 1

**Comment by redmapleleaf** [comment]
For the benefit of someone else running into this error, I fixed the problem by adding a line "using namespace std;" in the file tensorflow/lite/experimental/micro/kernels/svdf.cc.

#include <math.h>
**using namespace std;**

#include "tensorflow/lite/c/builtin_op_data.h"
#include "tensorflow/lite/c/c_api_internal.h"
#include "tensorflow/lite/experimental/micro/kernels/activation_utils.h"
#include "tensorflow/lite/experimental/micro/micro_utils.h"

**Comment by njeffrie** [comment]
It looks like this has been fixed by changing signbit to std::signbit.  I verified building with the same command locally. Closing for now - please re-open if this remains an issue for you.
