### ISSUE TITLE
dynamic shape for deconv ops

### ISSUE THREAD

**Issue by suke27** [tensorflow/tensorflow#33961]
i just check https://github.com/tensorflow/tensorflow/issues/833
it provide code for tf.nn.conv2d_transpose to support dyncmic shape. i want to ask how to apply it for slim.conv2d_transpose. Plz help to check. thank you!

**Comment by ymodak** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.
 Thanks!
