### ISSUE TITLE
init_from_checkpoint support loading different variables from multiple checkpoints

### ISSUE THREAD

**Issue by congchan** [tensorflow/tensorflow#33963]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**For example**
say I created a model with encoder + decoder, could `init_from_checkpoint` support loading encoder from A-checkpoint, and loading decoder from B-checkpoint?
```python
init_from_checkpoint(init_checkpoint_0, assignment_map_0)
init_from_checkpoint(init_checkpoint_1, assignment_map_0)
```

**System information**
- TensorFlow version (you are using): version 1.12

**Describe the feature and the current behavior/state.**

**Will this change the current api? How?** probably not

**Who will benefit with this feature?** developers who need more flexible graph loading， who need more flexible transfer leaning tricks

**Any Other info.**
pip install 
on both windows and linux

**Comment by ravikyram** [comment]
Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version. Also, did you compile from source or install a binary?

Make sure you also include the exact command if possible to produce the output included in your test case. If you are unclear what to include see the issue template displayed in [the Github new issue template](https://github.com/tensorflow/tensorflow/issues/new/choose).

We ask for this in the issue submission template, because it is really difficult to help without that information. Thanks!

**Comment by ravikyram** [comment]
@congchan 
Any updates on this issue please. Thanks!

**Comment by congchan** [comment]
> @congchan
> Any updates on this issue please. Thanks!

<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**For example**
say I created a model with encoder + decoder, could `init_from_checkpoint` support loading encoder from A-checkpoint, and loading decoder from B-checkpoint?
```python
init_from_checkpoint(init_checkpoint_0, assignment_map_0)
init_from_checkpoint(init_checkpoint_1, assignment_map_0)
```

**System information**
- TensorFlow version (you are using): version >1.12


**Describe the feature and the current behavior/state.**

**Will this change the current api? How?** probably not

**Who will benefit with this feature?** developers who need more flexible graph loading， who need more flexible transfer leaning tricks

**Any Other info.**
pip install 
on both windows and linux

**Comment by ravikyram** [comment]
@congchan 

Do you have any use case that requires the feature you are interested in? Please feel free to submit a PR if you have use cases that supports that feature.Thanks!

**Comment by congchan** [comment]
@ravikyram  what it means for PR of use cases?

**Comment by ravikyram** [comment]
@congchan 
Is it possible to elaborate the reported feature request with a sample code ? or provide more information about feature request.Thanks!

**Comment by congchan** [comment]
OK, take the code snippet from https://github.com/google-research/bert/blob/cc7051dc592802f501e8a6f71f8fb3cf9de95dc9/run_classifier.py#L661
for examples:
is it possible to load a bert from the pre-trained bert ckp, and load a bi-lstm layer from another pre-trained ckp?

**Comment by k-w-w** [comment]
You should already be able to use multiple `init_from_checkpoint` calls to different checkpoints.

In the [API documentation](https://www.tensorflow.org/api_docs/python/tf/compat/v1/train/init_from_checkpoint), there are several examples of how to use init_from_checkpoint. You can either initialize all variables, or specific variables.
