### ISSUE TITLE
Any way to generate offline documents for TF2.0 in HTML/pdf/markdown?

### ISSUE THREAD

**Issue by 3fen** [tensorflow/tensorflow#33966]
Since we have network issues visiting official tensorflow document website within our area, are there any clues for generating offline api-docs with the document repository?

**Comment by lamberta** [comment]
Hello.

Usually we generate the API reference Markdown in the tensorflow/docs repo. It should all be readable by browsing GitHub, just select the branch: https://github.com/tensorflow/docs/tree/r1.14/site/en/api_docs
But we're a bit behind for this last release. @MarkDaoust, can you generate the latest-greatest, please? (b/142128205)

The rest of the site docs are in the tensorflow/docs [site/en directory](https://github.com/tensorflow/docs/tree/master/site/en). Many are Jupyter notebooks and the HTML is only available through tensorflow.org.

**Comment by 3fen** [comment]
Sure, it helps. Thanks.

**Comment by MarkDaoust** [comment]
> But we're a bit behind for this last release. @MarkDaoust, can you generate the latest-greatest, please? (b/142128205)

Yes.

> Many are Jupyter notebooks and the HTML is only available through tensorflow.org.

You can convert them with `jupyter nbconvert` but if you have jupyter installed you can just use the notebook interface.
