### ISSUE TITLE
AttributeError: 'Tensor' object has no attribute '_keras_shape'

### ISSUE THREAD

**Issue by JackGuoFranklin** [tensorflow/tensorflow#33977]
this si my code 
base_model = tf.keras.applications.MobileNetV2(input_shape=IMG_SHAPE,
                                               include_top=False,
                                               weights='imagenet')

this is my error
Traceback (most recent call last):
  File "/Users/***/Sites/python/nlp/images/Transfer learning with a pretrained ConvNet.py", line 154, in <module>
    weights='imagenet')
  File "/anaconda3/lib/python3.6/site-packages/tensorflow/python/keras/applications/__init__.py", line 70, in wrapper
    return base_fun(*args, **kwargs)
  File "/anaconda3/lib/python3.6/site-packages/tensorflow/python/keras/applications/mobilenet_v2.py", line 32, in MobileNetV2
    return mobilenet_v2.MobileNetV2(*args, **kwargs)
  File "/anaconda3/lib/python3.6/site-packages/keras_applications/mobilenet_v2.py", line 355, in MobileNetV2
    expansion=1, block_id=0)
  File "/anaconda3/lib/python3.6/site-packages/keras_applications/mobilenet_v2.py", line 461, in _inverted_res_block
    in_channels = inputs._keras_shape[-1]
AttributeError: 'Tensor' object has no attribute '_keras_shape'

I learn tensorflow2.0  Tutorials Transfer learning with a pretrained ConvNet
please help me .

**Comment by dubesar** [comment]
what you can do is:
instead of this code: `from keras.models import Model` change to `from tensorflow.keras.models import Model`  or `from tensorflow.python.keras.layers import Input` to `from keras.layers import Input`

Depending on the version of tensorflow/keras the attribute names can differ.

I hope it helps.
Ping me if this doesn't solve the problem.

**Comment by ymodak** [comment]
The tutorial https://www.tensorflow.org/tutorials/images/transfer_learning works as expected in google colab.
If have custom code, try replacing imports from ```keras``` to ```tf.keras```
What version of TF and Kerass are you using?

**Comment by JackGuoFranklin** [comment]
my code is the tutorial code ,i use the pychrom  

tf.version
2.0.0-beta0
tf.keras.version
2.2.4-tf

@dubesar,
your solvtion  ,it not work.
@ymodak 
my code and  the tutorial code is " keras= tf.keras"   
 it not work.please help me . i try many times ,it not work

**Comment by JackGuoFranklin** [comment]
google colab. is  ok，why pychrom is not work。@ymodak

**Comment by JackGuoFranklin** [comment]
it is work ,just update TF and keras @ymodak @dubesar

**Comment by wangyexiang** [comment]
tf.__version__ 
2.1.0 
tf.keras.__version__
2.2.4-tf
I meet the same issue. I want to change [https://github.com/guilherme-pombo/keras_resnext_fpn/blob/master/resnext_fpn.py](url) into tf.keras, like 
)

![图片](https://user-images.githubusercontent.com/23202109/74914320-3341c100-53fd-11ea-95d0-0d6b52887412.png)
