### ISSUE TITLE
Can't place tf.nn.moments() on GPU when first dimension is None

### ISSUE THREAD

**Issue by osdf** [tensorflow/tensorflow#3397]
At first this sounds like #2508, but this was closed and apparently fixed and the error message is also different. So it might be more related to #139, and possibly to the comment of @mrry on `tf.mean` on GPUs. The example below works with cpu device context (or no explicit device placement at all). Is this a missing feature or should one not expect that this is fixable?
### Environment info

Operating System:
Ubuntu 15.10

Installed version of CUDA and cuDNN: 
CUDA7.5/cuDNN4.0.4

(please attach the output of `ls -l /path/to/cuda/lib/libcud*`):

```
-rw-r--r-- 1 root root 189170 Jan  1 23:25 /usr/local/cuda/lib/libcudadevrt.a
lrwxrwxrwx 1 root root     16 Jan  1 23:25 /usr/local/cuda/lib/libcudart.so -> libcudart.so.7.5
lrwxrwxrwx 1 root root     19 Jan  1 23:25 /usr/local/cuda/lib/libcudart.so.7.5 -> libcudart.so.7.5.18
-rwxr-xr-x 1 root root 311596 Jan  1 23:25 /usr/local/cuda/lib/libcudart.so.7.5.18
-rw-r--r-- 1 root root 558020 Jan  1 23:25 /usr/local/cuda/lib/libcudart_static.a
```

If installed from sources, provide the commit hash: [fc91629](https://github.com/tensorflow/tensorflow/commit/fc9162975e52978d3af38549b570cc3cc5f0ab66)
### Steps to reproduce

```
import tensorflow as tf
import numpy as np

with tf.device("/gpu:0"):
    x = tf.placeholder(tf.float32, shape=[None, 5])
    mean, var = tf.nn.moments(x, axes=[0])
sess = tf.Session()
sess.run([mean, var], feed_dict={x:np.random.randn(10, 5)})
```

results in

```
E tensorflow/core/client/tensor_c_api.cc:485] Cannot assign a device to node 'moments/sufficient_statistics/SparseToDense': Could not satisfy explicit device specification '/device:GPU:0' because no supported kernel for GPU devices is available.
     [[Node: moments/sufficient_statistics/SparseToDense = SparseToDense[T=DT_BOOL, Tindices=DT_INT32, validate_indices=true, _device="/device:GPU:0"](moments/sufficient_statistics/SparseToDense/sparse_indices, moments/sufficient_statistics/Shape_1, moments/sufficient_statistics/SparseToDense/sparse_values, moments/sufficient_statistics/SparseToDense/default_value)]]
```
### What have you tried?
1. Setting `shape=[10, 5]` fixes the above problem (to be expected).
2. Setting device context to `with tf.device("/cpu:0"):` works with `None` shape info, too.

**Comment by concretevitamin** [comment]
The call stack is as such: `tf.nn.moments()` calls `sufficient_statistics()`, which contains [this part](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/ops/nn.py#L695):

```python
    if x_shape.is_fully_defined():
        <some code>
    else:  # shape needs to be inferred at runtime.
      x_shape = array_ops.shape(x)
      select_axes = sparse_ops.sparse_to_dense(axes, array_ops.shape(x_shape),
                                               True, False)
```

Since the shape contains `None` the else branch is taken.  Lastly, the `SparseToDense` op only has a CPU kernel, not a GPU one.  Hence the failure.

Possible fixes:
- Somehow change the `tf.nn.moments()` code path, so that `sparse_to_dense()` is avoided.
- Or, implement a SparseToDense GPU kernel.

Marking as contribution welcome, since we're not likely to work on this in the near future.

**Comment by vincentvanhoucke** [comment]
Yes, it's a known wrinkle, that would only be properly solved with a dedicated op or a GPU implementation of `sparse_to_dense`. In practice, there should be no good reason to want to enforce a hard placement of all the ops on GPU though. With soft placement, you may let the graph mostly run on GPU and back off to CPU only for this one op without a GPU equivalent.

**Comment by osdf** [comment]
Thank you for the replies. Out of curiosity, would the performance hit of going down to cpu and up again be negligible? The ```tf.nn.moments``` is used in a BatchNorm layer in this case, so with ResNets, many of this transfers would happen. Or is using ```None``` in the batchsize itself having already such a negative effect (e.g. because some optimizations can't be realized offline) that this copying does not add that much overhead?

**Comment by vincentvanhoucke** [comment]
This op operates on four floats. There should be no impact at all.

**Comment by concretevitamin** [comment]
@osdf: for now, I think a workaround is to use
```
    sess = tf.Session(config=tf.ConfigProto(allow_soft_placement=True))
```
which should attempt to place non-GPU-available ops on CPU instead.

**Comment by osdf** [comment]
Thank you @concretevitamin and @vincentvanhoucke. Do you think this issue should be closed? If it turns out that somebody needs this to be placed on GPU it could be reopened. (I briefly thought of taking a stab at it but a bit time-limited right now). Apart from that it serves as a reference if anybody else encounters it.

**Comment by vincentvanhoucke** [comment]
Please leave it open. It's likely others will hit the same problem.

**Comment by vincentvanhoucke** [comment]
Pending https://github.com/tensorflow/tensorflow/pull/6031 should fully address this.

**Comment by Namnamseo** [comment]
I think the issue is unresolved. I thought it would be better to post here, continuing the discussion.
Take this toy example:

```python
with tf.device('/gpu:2'):
    x = tf.placeholder(tf.float32, shape=[None, 100])
    weight_dense_1 = tf.Variable(tf.zeros([100, 10]))
    dense_1_out = tf.matmul(x, weight_dense_1)
    mean, var = tf.nn.moments(dense_1_out, [0], shift=None, name=None, keep_dims=False)
    coeff = tf.rsqrt(var + 1e-8)
    y = dense_1_out * coeff - mean * coeff
    grad = tf.gradients(y, [weight_dense_1], colocate_gradients_with_ops=True)
```

This immediately shows up some warnings:
```
WARNING:tensorflow:Tried to colocate gradients/moments/sufficient_statistics/count_grad/Rank with an op moments/sufficient_statistics/count that had a different device: /device:CPU:0 vs /device:GPU:2. Ignoring colocation property.
WARNING:tensorflow:Tried to colocate gradients/moments/sufficient_statistics/count_grad/range_1/start with an op moments/sufficient_statistics/count that had a different device: /device:CPU:0 vs /device:GPU:2. Ignoring colocation property.
WARNING:tensorflow:Tried to colocate gradients/moments/sufficient_statistics/count_grad/range_1/delta with an op moments/sufficient_statistics/count that had a different device: /device:CPU:0 vs /device:GPU:2. Ignoring colocation property.
WARNING:tensorflow:Tried to colocate gradients/moments/sufficient_statistics/count_grad/range_1 with an op moments/sufficient_statistics/count that had a different device: /device:CPU:0 vs /device:GPU:2. Ignoring colocation property.
WARNING:tensorflow:Tried to colocate gradients/moments/sufficient_statistics/count_grad/ListDiff with an op moments/sufficient_statistics/count that had a different device: /device:CPU:0 vs /device:GPU:2. Ignoring colocation property.
WARNING:tensorflow:Tried to colocate gradients/moments/sufficient_statistics/count_grad/concat/axis with an op moments/sufficient_statistics/count that had a different device: /device:CPU:0 vs /device:GPU:2. Ignoring colocation property.
WARNING:tensorflow:Tried to colocate gradients/moments/sufficient_statistics/count_grad/concat with an op moments/sufficient_statistics/count that had a different device: /device:CPU:0 vs /device:GPU:2. Ignoring colocation property.
WARNING:tensorflow:Tried to colocate gradients/moments/sufficient_statistics/count_grad/Gather with an op moments/sufficient_statistics/count that had a different device: /device:CPU:0 vs /device:GPU:2. Ignoring colocation property.
WARNING:tensorflow:Tried to colocate gradients/moments/sufficient_statistics/count_grad/Const with an op moments/sufficient_statistics/count that had a different device: /device:CPU:0 vs /device:GPU:2. Ignoring colocation property.
WARNING:tensorflow:Tried to colocate gradients/moments/sufficient_statistics/count_grad/Prod with an op moments/sufficient_statistics/count that had a different device: /device:CPU:0 vs /device:GPU:2. Ignoring colocation property.
WARNING:tensorflow:Tried to colocate gradients/moments/sufficient_statistics/count_grad/Gather_1 with an op moments/sufficient_statistics/count that had a different device: /device:CPU:0 vs /device:GPU:2. Ignoring colocation property.
WARNING:tensorflow:Tried to colocate gradients/moments/sufficient_statistics/count_grad/Const_1 with an op moments/sufficient_statistics/count that had a different device: /device:CPU:0 vs /device:GPU:2. Ignoring colocation property.
WARNING:tensorflow:Tried to colocate gradients/moments/sufficient_statistics/count_grad/Prod_1 with an op moments/sufficient_statistics/count that had a different device: /device:CPU:0 vs /device:GPU:2. Ignoring colocation property.
```

And if I force it to run(by setting `allow_soft_placement=False`), an error is occured:
```
InvalidArgumentError: Cannot colocate nodes 'gradients/moments/sufficient_statistics/count_grad/Const_1' and 'gradients/moments/sufficient_statistics/count_grad/Cumprod_1/axis: Cannot merge devices with incompatible types: '/GPU:2' and '/CPU:0'
	 [[Node: gradients/moments/sufficient_statistics/count_grad/Const_1 = Const[_class=["loc:@moments/sufficient_statistics/count"], dtype=DT_INT32, value=Tensor<type: int32 shape: [1] values: 0>, _device="/device:CPU:0"]()]]
```

When setting the placeholder's batch size explicitly, the warning is gone.

I'm using pip3-installed `tensorflow-gpu==1.0.1`, with Python 3.5.2.
CUDA 8.0.61, cuDNN 5.1.10 is installed on Ubuntu 16.04.

**Comment by Namnamseo** [comment]
As the problem seems to be about a whole different things, I'm opening a new issue.
