### ISSUE TITLE
assert_shapes broken code in documentation

### ISSUE THREAD

**Issue by bodin-e** [tensorflow/tensorflow#33974]
## URL(s) with the issue:
https://www.tensorflow.org/api_docs/python/tf/debugging/assert_shapes

## Description of issue (what needs changing):
The source code in the example is incorrect.

Is:
tf.assert_shapes([
  (x: ('N', 'Q')),
  (y: ('N', 'D')),
  (param: ('Q',)),
  (scalar: ()),
])

Should be:
tf.assert_shapes([
  (x, ('N', 'Q')),
  (y, ('N', 'D')),
  (param, ('Q',)),
  (scalar, ()),
]).

Note that ":" is not allowed in Python to form 2-tuples.

**Comment by lamberta** [comment]
Thanks for the report! Can you make a PR? That file is here: https://github.com/tensorflow/tensorflow/blob/r2.0/tensorflow/python/ops/check_ops.py#L1697-L1747 (link at top of page on tf.org)

**Comment by dubesar** [comment]
@lamberta  I have opened a pull request making the relevant changes to the documentation folder.

**Comment by bodin-e** [comment]
Thanks @dubesar, then its sorted.

**Comment by dubesar** [comment]
@MarkDaoust  this issue can be closed now as it's solved
