### ISSUE TITLE
Errors when instantiating multiple tf.keras models on different threads concurrently

### ISSUE THREAD

**Issue by josephcappadona** [tensorflow/tensorflow#33986]
**System information**
I am running custom code on a MacBook Pro running Mac OS Mojave 10.14.6:
```
 Model Name:	MacBook Pro
  Model Identifier:	MacBookPro15,1
  Processor Name:	Intel Core i9
  Processor Speed:	2.3 GHz
  Number of Processors:	1
  Total Number of Cores:	8
  L2 Cache (per Core):	256 KB
  L3 Cache:	16 MB
  Hyper-Threading Technology:	Enabled
  Memory:	16 GB
```

I am running Python 3.7.3 installed via homebrew and Tensorflow 2.0.0 (v2.0.0-rc2-26-g64c3d382ca 2.0.0) installed via pip.

**Describe the current behavior**

When instantiating multiple `tf.keras.Sequential` models concurrently on different threads, I sometimes get errors in certain calls within `site-packages/tensorflow_core/python/framework/ops.py`. Tracebacks are included below.

**Describe the expected behavior**

Expected behavior is that multiple tf.keras models can be instantiated on multiple threads without conflict.

**Code to reproduce the issue + Other info / logs**

The error that I am getting in my development code is this:

```
Traceback (most recent call last):
...
  File "/Users/josephcappadona/Documents/demo/demo/models/models.py", line 24, in __init__
    super().__init__([logit_layer, activation_layer], name)
  File "/Users/josephcappadona/.local/share/virtualenvs/demo-qfKwvgY4/lib/python3.7/site-packages/tensorflow_core/python/training/tracking/base.py", line 457, in _method_wrapper
    result = method(self, *args, **kwargs)
  File "/Users/josephcappadona/.local/share/virtualenvs/demo-qfKwvgY4/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/sequential.py", line 114, in __init__
    self.add(layer)
  File "/Users/josephcappadona/.local/share/virtualenvs/demo-qfKwvgY4/lib/python3.7/site-packages/tensorflow_core/python/training/tracking/base.py", line 457, in _method_wrapper
    result = method(self, *args, **kwargs)
  File "/Users/josephcappadona/.local/share/virtualenvs/demo-qfKwvgY4/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/sequential.py", line 174, in add
    batch_shape=batch_shape, dtype=dtype, name=layer.name + '_input')
  File "/Users/josephcappadona/.local/share/virtualenvs/demo-qfKwvgY4/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/input_layer.py", line 263, in Input
    input_tensor=tensor)
  File "/Users/josephcappadona/.local/share/virtualenvs/demo-qfKwvgY4/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/input_layer.py", line 125, in __init__
    ragged=ragged)
  File "/Users/josephcappadona/.local/share/virtualenvs/demo-qfKwvgY4/lib/python3.7/site-packages/tensorflow_core/python/keras/backend.py", line 1057, in placeholder
    x = array_ops.placeholder(dtype, shape=shape, name=name)
  File "/Users/josephcappadona/.local/share/virtualenvs/demo-qfKwvgY4/lib/python3.7/site-packages/tensorflow_core/python/ops/array_ops.py", line 2630, in placeholder
    return gen_array_ops.placeholder(dtype=dtype, shape=shape, name=name)
  File "/Users/josephcappadona/.local/share/virtualenvs/demo-qfKwvgY4/lib/python3.7/site-packages/tensorflow_core/python/ops/gen_array_ops.py", line 6671, in placeholder
    "Placeholder", dtype=dtype, shape=shape, name=name)
  File "/Users/josephcappadona/.local/share/virtualenvs/demo-qfKwvgY4/lib/python3.7/site-packages/tensorflow_core/python/framework/op_def_library.py", line 793, in _apply_op_helper
    op_def=op_def)
  File "/Users/josephcappadona/.local/share/virtualenvs/demo-qfKwvgY4/lib/python3.7/site-packages/tensorflow_core/python/framework/func_graph.py", line 548, in create_op
    compute_device)
  File "/Users/josephcappadona/.local/share/virtualenvs/demo-qfKwvgY4/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py", line 3430, in _create_op_internal
    self._create_op_helper(ret, compute_device=compute_device)
  File "/Users/josephcappadona/.local/share/virtualenvs/demo-qfKwvgY4/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py", line 3469, in _create_op_helper
    for key, value in self._attr_scope_map.items():
RuntimeError: dictionary changed size during iteration
```
however I cannot reproduce this error reliably. It seems to happen a very small percentage of the time, making debugging it very difficult. Essentially, this happens when running a Flask app in which multiple models are instantiated concurrently across different threads at the same time.

In trying to write some code that reproduces something similar so that I could include something in this issue, I was able to use this code
```python
import tensorflow as tf
from threading import Thread

def build_model():
    layer_1 = tf.keras.layers.Dense(1, input_shape=(20,))
    layer_2 = tf.keras.layers.Activation(tf.sigmoid)
    tf.keras.Sequential([layer_1, layer_2])

for i in range(100):
    t = Thread(target=build_model)
    t.start()
```

in a jupyter notebook to generate this error

```
Exception in thread Thread-369:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "<ipython-input-8-c7ffb35bc6af>", line 4, in build_model
    tf.keras.Sequential([layer_1, layer_2])
  File "/Users/josephcappadona/.local/share/virtualenvs/demo-qfKwvgY4/lib/python3.7/site-packages/tensorflow_core/python/training/tracking/base.py", line 457, in _method_wrapper
    result = method(self, *args, **kwargs)
  File "/Users/josephcappadona/.local/share/virtualenvs/demo-qfKwvgY4/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/sequential.py", line 114, in __init__
    self.add(layer)
  File "/Users/josephcappadona/.local/share/virtualenvs/demo-qfKwvgY4/lib/python3.7/site-packages/tensorflow_core/python/training/tracking/base.py", line 457, in _method_wrapper
    result = method(self, *args, **kwargs)
  File "/Users/josephcappadona/.local/share/virtualenvs/demo-qfKwvgY4/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/sequential.py", line 196, in add
    output_tensor = layer(self.outputs[0])
  File "/Users/josephcappadona/.local/share/virtualenvs/demo-qfKwvgY4/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/base_layer.py", line 845, in __call__
    outputs = base_layer_utils.mark_as_return(outputs, acd)
  File "/Users/josephcappadona/.local/share/virtualenvs/demo-qfKwvgY4/lib/python3.7/site-packages/tensorflow_core/python/framework/auto_control_deps.py", line 300, in __exit__
    if op.type == "Switch" and op.inputs[0].dtype == dtypes_module.resource:
  File "/Users/josephcappadona/.local/share/virtualenvs/demo-qfKwvgY4/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py", line 2259, in type
    return c_api.TF_OperationOpType(self._c_op)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf2 in position 0: invalid continuation byte
```
which, while obviously is a different error, also happens in `tensorflow_core/python/framework/ops.py` and also involves the use of an instance variable (in this case `self._c_op`).

Please let me know if there's any other information I need to provide to help debug. I assume this has something to do with shared global state across a tensorflow session, but I'm not sure if there is something that I am supposed to do to prevent these types of errors.

**Comment by AIRLegend** [comment]
Same error here. Launching child processes seems to work, though.

**Comment by josephcappadona** [comment]
> Launching child processes seems to work, though.

Thanks. I've written the following decorator to run a function as a child process. It doesn't work on functions that return `tf.keras` models, since they are not pickleable which is a requirement for the `multiprocessing.Queue` object, but it works as a temporary fix that I can use to decorate the function that instantiates and uses the model. It fixes the example code that I provided above, however I'm not positive that it fixed the original error that I got since I can't reproduce it reliably.

```python
import multiprocessing as mp

def run_as_child_process(f):
    """Decorator which makes the input function run as a child process to the
    thread on which it was called. Requires that the function's return value is
    pickleable (this is a requirement in order to put an object in a
    `multiprocessing.Queue` object) or else it will fail silently.

    Args:
        f: A function whose return value is pickleable.

    Returns:
        A function.
    """

    def subprocess_f(q, *args, **kwargs):
        """Takes in a multiprocessing.Queue object and the positional and
        keyword arguments for `f`. Runs `f` and places the return value in the
        queue for retrieval by the parent process.

        Args:
            q: A multiprocessing.Queue object.
        """
        ret = f(*args, **kwargs)
        q.put(ret)

    def new_f(*args, **kwargs):
        """Spawns a new process in which to run `f`. `q.get()` blocks until it
        receives data from the child process and then returns that data."""
        q = mp.Queue()
        new_args = tuple([q] + list(args))
        p = mp.Process(target=subprocess_f, args=new_args, kwargs=kwargs)
        p.start()
        ret = q.get()
        p.join()
        return ret

    return new_f
```

**Comment by josephcappadona** [comment]
If someone could chime in with a more official fix, that would be appreciated.

**Comment by ravikyram** [comment]
Can you please try using [distribution strategy](https://www.tensorflow.org/api_docs/python/tf/distribute?hl=en
) and see how it progresses. Also it will be great help if you share minimal stand alone code , it helps us in localizing the issue faster.Thanks!

**Comment by AIRLegend** [comment]
The only solution I got to work was using the TF 1.0 api for creating each model in a separate graph. However, I think this is a little bit dirty, but I don't get it to work with the TF 2.0 API. @josephcappadona, in your first example, would be something like:

```python3
def build_model():
            with tf.compat.v1.Session() as sess:
                gra = tf.Graph()
                with gra.as_default():
                        layer_1 = tf.keras.layers.Dense(1, input_shape=(20,))
                        layer_2 = tf.keras.layers.Activation(tf.sigmoid)
                        tf.keras.Sequential([layer_1, layer_2])
```

How would it be the best approximation for instantiating several models, like agents for a game (only using them for inference)?.

**Comment by josephcappadona** [comment]
> Can you please try using [distribution strategy](https://www.tensorflow.org/api_docs/python/tf/distribute?hl=en) and see how it progresses. Also it will be great help if you share minimal stand alone code , it helps us in localizing the issue faster.Thanks!

I was not able to get it working with the `tf.distribute.Strategy` API. It is not the training that is the issue, it is simply the instantiation of the models that throws the errors.

The example that I included above is the best example I can get, it throws an error fairly consistently. The bug is stochastic in nature, so I'm having trouble reproducing it consistently. The best I was able to do is the following:

```python
import tensorflow as tf
from threading import Thread
import multiprocessing as mp
from uuid import uuid4
import time
import numpy as np

def get_sleep_time():
    return abs(np.random.normal(loc=0.1, scale=0.5))

def build_model(i, z):
    time.sleep(get_sleep_time())
    layer_1 = tf.keras.layers.Dense(1, input_shape=(20,))
    layer_2 = tf.keras.layers.Activation(tf.sigmoid)
    model = tf.keras.Sequential([layer_1, layer_2], str(i) + str(uuid4()))
    z.put(model.name)
    return model.name

z = mp.Queue()
for i in range(100):
    t = Thread(target=build_model, args=(i, z))
    t.start()
```

The goal of the sleeping is to make it more likely that two model instantiations will conflict. This code throws a `UnicodeDecodeError` for me about half of the time.

**Comment by AIRLegend** [comment]
Hope someone can shed some light on this... I solved my issue with the approximation I posted, but I would like to know if there is a cleaner way.

**Comment by josephcappadona** [comment]
> Hope someone can shed some light on this... I solved my issue with the approximation I posted, but I would like to know if there is a cleaner way.

After more testing, it seems this has solved my issue, but yes, a canonical way to solve this with TF 2.0 would be ideal.

**Comment by samuel500** [comment]
> > Launching child processes seems to work, though.
> 
> Thanks. I've written the following decorator to run a function as a child process. It doesn't work on functions that return `tf.keras` models, since they are not pickleable which is a requirement for the `multiprocessing.Queue` object, but it works as a temporary fix that I can use to decorate the function that instantiates and uses the model. It fixes the example code that I provided above, however I'm not positive that it fixed the original error that I got since I can't reproduce it reliably.
> 
> ```python
> import multiprocessing as mp
> 
> def run_as_child_process(f):
>     """Decorator which makes the input function run as a child process to the
>     thread on which it was called. Requires that the function's return value is
>     pickleable (this is a requirement in order to put an object in a
>     `multiprocessing.Queue` object) or else it will fail silently.
> 
>     Args:
>         f: A function whose return value is pickleable.
> 
>     Returns:
>         A function.
>     """
> 
>     def subprocess_f(q, *args, **kwargs):
>         """Takes in a multiprocessing.Queue object and the positional and
>         keyword arguments for `f`. Runs `f` and places the return value in the
>         queue for retrieval by the parent process.
> 
>         Args:
>             q: A multiprocessing.Queue object.
>         """
>         ret = f(*args, **kwargs)
>         q.put(ret)
> 
>     def new_f(*args, **kwargs):
>         """Spawns a new process in which to run `f`. `q.get()` blocks until it
>         receives data from the child process and then returns that data."""
>         q = mp.Queue()
>         new_args = tuple([q] + list(args))
>         p = mp.Process(target=subprocess_f, args=new_args, kwargs=kwargs)
>         p.start()
>         ret = q.get()
>         p.join()
>         return ret
> 
>     return new_f
> ```
> 
> Edit: Sometimes the example code throws this error
> 
> ```
> Traceback (most recent call last):
>   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 917, in _bootstrap_inner
>     self.run()
>   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 865, in run
>     self._target(*self._args, **self._kwargs)
>   File "<ipython-input-3-6d3398ac7046>", line 5, in build_model
>     model = tf.keras.Sequential([layer_1, layer_2], str(i) + '__' + str(uuid4()))
> ...
>   File "/Users/josephcappadona/.local/share/virtualenvs/demo-qfKwvgY4/lib/python3.7/site-packages/tensorflow_core/python/framework/func_graph.py", line 548, in create_op
>     compute_device)
>   File "/Users/josephcappadona/.local/share/virtualenvs/demo-qfKwvgY4/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py", line 3430, in _create_op_internal
>     self._create_op_helper(ret, compute_device=compute_device)
>   File "/Users/josephcappadona/.local/share/virtualenvs/demo-qfKwvgY4/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py", line 3469, in _create_op_helper
>     for key, value in self._attr_scope_map.items():
> RuntimeError: dictionary changed size during iteration
> ```
> 
> which is the precise error I get in my development code, however using the decorator makes this error disappear, so I am more confident now that the decorator has fixed the issue. It would still be nice to have an official fix though.

Not sure if this applies, but you could maybe do `w = model.get_weights()`, send the list of numpy arrays to the Queue, and then `model.set_weights(w)` on the other side. It's a bit ugly, but should allow you to effectively send a model in a Queue.

**Comment by AIRLegend** [comment]
The problem for us is in the model/graph declaration part. It seems that all the 100 threads create 100 models on the same graph, so some node names conflict. My idea was that each thread had it's separate session so this don't occur. However, I still have the question for someone on the TF community: What is the best way (with TF 2.0) to make a model on each thread (not having the name collisions) using only them for inference?

**Comment by rmothukuru** [comment]
@josephcappadona,
Can you please let us know if [this comment](https://github.com/tensorflow/tensorflow/issues/33986#issuecomment-550186975) has resolved your issue? 

Also, your code could be run without any error with **`Tensorflow Version 2.5`** (executed more tha 10 times, even in **`Jupyter Notebook`**). Please find [the Gist](https://colab.research.google.com/gist/rmothukuru/7184cde9009d10668ed5e0d3e932c11e/gh_33986.ipynb) of the Working Code.

Thanks!

**Comment by Saduf2019** [comment]
@josephcappadona 
Please post this issue on [keras-team/keras repo.](https://github.com/keras-team/keras/issues)
To know more see;
https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999
