### ISSUE TITLE
Update `nogpu` tag references to be `no_gpu` instead?

### ISSUE THREAD

**Issue by deven-amd** [tensorflow/tensorflow#33987]
Currently the scripts used to run TF unit tests on the ROCm platform filter out tests that are tagged with the `no_gpu` tag

* https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/ci_build/linux/rocm/run_cc_core.sh
* https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/ci_build/linux/rocm/run_csb_tests.sh
* https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/ci_build/linux/rocm/run_py3_core.sh
* https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/ci_build/xla/linux/rocm/run_py3.sh

The same applies for scripts for the CUDA platform as well.

There seem to be some tests that are tagged with the `nogpu` tag instead of the `no_gpu` tag.
One example is 

https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/tpu/tpu.bzl#L44

Such tests do not get filtered out by the test scripts above, and as a consequence they get reported as regression failures when those test scripts are run.

So the question here is 
* should we update all references to the `nogpu` tag to instead be `no_gpu`
OR
* should we update all the scripts instead to also filter out the `nogpu` tagged tests?

-----------------------

@chsigg

**Comment by deven-amd** [comment]
a related question for the `master` branch (which is now TF2.0).

Should the test scripts also filter out `v1only` tagged tests?

**Comment by deven-amd** [comment]
gentle ping....any update here?

**Comment by chsigg** [comment]
Sorry for the delay. I think we should change `nogpu` tags to `no_gpu`. I can take care of this.

**Comment by deven-amd** [comment]
@chsigg thanks.

how about the `v1only` tagged tests....should they also be filtered out by default on the `master` branch?

**Comment by av8ramit** [comment]
Ping @chsigg has this been done? Removing myself from assignees. Thanks!

**Comment by sanatmpa1** [comment]
@deven-amd,

As per this [commit](https://github.com/tensorflow/tensorflow/commit/3a91a0251bdbda59e8079958ff9261fcb752f52f), `nogpu` tag references have been modified to `no-gpu` by @chsigg and so I am closing this issue. Feel free to open a new issue if you face any further problems. Thanks!
