### ISSUE TITLE
Build error in Macbook (tensorflow lite)

### ISSUE THREAD

**Issue by ek9852** [tensorflow/tensorflow#33983]
- OS Platform and Distribution Macbook
- TensorFlow installed from (source or binary): github latest bf282dece59bdf88f7a58bcf1064723cb3eea51e 
- TensorFlow version:trunk
- Bazel version (if compiling from source):  1.0.0-homebrew
- GCC/Compiler version (if compiling from source): Apple clang version 11.0.0 (clang-1100.0.33.8)

Run ./tensorflow/lite/tools/make/build_lib.sh or ./tensorflow/lite/tools/make/build_ios_universal_lib.sh
Same build problem:

g++ -O3 -DNDEBUG -fPIC  --std=c++11 -I. -I/Users/kmok/workspaces/tensorflow/tensorflow/lite/tools/make/../../../../../ -I/Users/kmok/workspaces/tensorflow/tensorflow/lite/tools/make/../../../../../../ -I/Users/kmok/workspaces/tensorflow/tensorflow/lite/tools/make/downloads/ -I/Users/kmok/workspaces/tensorflow/tensorflow/lite/tools/make/downloads/eigen -I/Users/kmok/workspaces/tensorflow/tensorflow/lite/tools/make/downloads/absl -I/Users/kmok/workspaces/tensorflow/tensorflow/lite/tools/make/downloads/gemmlowp -I/Users/kmok/workspaces/tensorflow/tensorflow/lite/tools/make/downloads/neon_2_sse -I/Users/kmok/workspaces/tensorflow/tensorflow/lite/tools/make/downloads/farmhash/src -I/Users/kmok/workspaces/tensorflow/tensorflow/lite/tools/make/downloads/flatbuffers/include -I -I/usr/local/include -c tensorflow/lite/experimental/ruy/block_map.cc -o /Users/kmok/workspaces/tensorflow/tensorflow/lite/tools/make/gen/osx_x86_64/obj/tensorflow/lite/experimental/ruy/block_map.o
In file included from tensorflow/lite/core/api/op_resolver.cc:16:
In file included from ./tensorflow/lite/core/api/op_resolver.h:20:
**./tensorflow/lite/schema/schema_generated.h:2660:8: error: ISO C++ forbids forward references to 'enum' types**
In file included from tensorflow/lite/core/api/flatbuffer_conversions.cc:  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
16:
       ^In file included from 
./tensorflow/lite/core/api/flatbuffer_conversions.h:24:
In file included from ./tensorflow/lite/core/api/op_resolver.h:20:
**./tensorflow/lite/schema/schema_generated.h:2660:8: error: ISO C++ forbids forward references to 'enum' types**
**./tensorflow/lite/schema/schema_generated.h:2660:32: error: field has incomplete type 'enum FlatBuffersVTableOffset'**
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
       ^
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {

**Comment by YoungANDJ** [comment]
I have the same question at 'flatbuffer' and 'enum'. Please make sure that U **use the latest FLATTERBUFFER** so that _flatbuffers/flatbuffers.h has type 'FlatBuffersVTableOffset'._ I solve the problem with it. U can try it. Good Luck.

**Comment by ek9852** [comment]
It had nothing   related to flatbuffer from the log , also the flatbuffer is downloaded by download_dependencies.sh, not  using system one.
