### ISSUE TITLE
Autograph error in LSTMCell when using dropout

### ISSUE THREAD

**Issue by georgesterpu** [tensorflow/tensorflow#33991]
**System information**
- Have I written custom code: no
- OS Platform and Distribution: Manjaro linux testing
- TensorFlow installed from: pip binary
- TensorFlow version: v2.0.0-rc2-26-g64c3d38 2.0.0
- Python version: 3.7.4
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

**Describe the current behavior**
TensorFlow returns an error when decorating functions calling `LSTMCell.call` with `@tf.function` if dropout is non-zero (most common scenario).
```
TypeError: An op outside of the function building code is being passed
a "Graph" tensor. It is possible to have Graph tensors
leak out of the function building context by including a
tf.init_scope in your function building code.
For example, the following function will fail:
  @tf.function
  def has_init_scope():
    my_constant = tf.constant(1.)
    with tf.init_scope():
      added = my_constant * 2
The graph tensor has name: lstm_cell_1/ones_like:0
```

**Describe the expected behavior**
Compile the LSTMCell code correctly

**Code to reproduce the issue**
```
import tensorflow as tf


good_cell = tf.keras.layers.LSTMCell(units=2, dropout=0.0, implementation=1)
bad_cell = tf.keras.layers.LSTMCell(units=2, dropout=0.1, implementation=1)
inputs = tf.ones((1, 2))

state = good_cell.get_initial_state(inputs)

@tf.function
def no_dropout():
    output = good_cell(inputs, state)
    return output

@tf.function
def dropout():
    output = bad_cell(inputs, state)
    return output

print('='*50)
print(no_dropout())
print('='*50)
print(dropout())
```

**Other info / logs**
I did a quick investigation and found out that setting `self._dropout_mask = None` [at the top of the call method](https://github.com/tensorflow/tensorflow/blob/r2.0/tensorflow/python/keras/layers/recurrent.py#L2210) makes the code work again. This forces the reset of the cached dropout mask used at the previous/first call of LSTMCell.

**Comment by oanush** [comment]
Issue replicating for both  TF 2.0 and nightly version.Kindly find the [gist](https://colab.sandbox.google.com/gist/oanush/7c9b4739689b5a093a27dbe3bc12c834/33991.ipynb) of colab.Thanks!

**Comment by qlzh727** [comment]
So the story is bit complicated.

If you debug the bad cell call with debugger, you will see the the bad_cell.call() is invoked twice. This means the second time when its invoked, its using the cached dropout mask created in the second trace.

To walkaround this issue, you can update your code as below. This is mimic what a normal cell will behave to process the inputs 10 times. The LSTM/RNN layer is resetting mask for every batch. User will have to do the same if they want to direct play with the cell.

```
@tf.function
def dropout(inputs):
  time_step = 10
  bad_cell.reset_dropout_mask()
  bad_cell.reset_recurrent_dropout_mask()
  state = bad_cell.get_initial_state(inputs)
  for i in range(time_step):
    inputs, state = bad_cell(inputs, state)
  return inputs, state
```

**Comment by georgesterpu** [comment]
Hi @qlzh727 
Just wanted to thank you for your great response. This is an interesting behaviour of tf.function that I was not aware of, so I learnt something new :)

> This means the second time when its invoked, its using the cached dropout mask created in the second trace.

Would you be able to help me with a high-level technical explanation ? I don't fully understand this yet, although it seems related to the specific implementation of tf.function.

**Comment by qlzh727** [comment]
Ah sorry, I made a typo in the original message:

> This means the second time when its invoked, its using the cached dropout mask created in the **FIRST** trace.

So, in high level, tf.function will convert a python function into a tf graph, which will be used to execution. The conversion process is called "trace". During tracing, tf.function will check if there is any variable gets created. If that is the case, tf.function will trace the second time and make sure no other variable is created, as a verification. When the verification failed, it will raise an error.

In your case, the function body will create following items in the first trace:
1. cached masks
2. variables for bad_cell when it is called with inputs. The build() function is first invoked when cell is not build.

Since tf.function detect the variable creation, it will try to trace the second time. During the second trace, the code will try to use the cached mask in a different graph (created in the first trace). Since it can't access those tensors across the graph, it raises an error to you.

As a verification, you can try build your cell first outside the tf.function for your existing code, and it should make it work too.

**Comment by qlzh727** [comment]
```python
import tensorflow as tf


good_cell = tf.keras.layers.LSTMCell(units=2, dropout=0.0, implementation=1)
bad_cell = tf.keras.layers.LSTMCell(units=2, dropout=0.1, implementation=1)
inputs = tf.ones((1, 2))
good_cell.build(inputs.shape)
bad_cell.build(inputs.shape)

state = good_cell.get_initial_state(inputs)

@tf.function
def no_dropout():
  output = good_cell(inputs, state)
  return output

@tf.function
def dropout():
  output = bad_cell(inputs, state)
  return output

print('='*50)
print(no_dropout())
print('='*50)
print(dropout())
```

**Comment by wpc009** [comment]
So, is there any roadmap for this?
Or, all we got is a workaround.
