### ISSUE TITLE
different gpu to each session in a thread

### ISSUE THREAD

**Issue by liupengkd** [tensorflow/tensorflow#33996]
tensorflow c API：I want to create multiple sessions for different models in a thread, how to assign a different gpu to each session.

**Comment by ravikyram** [comment]
@liupengkd 
Can you go through the [link](https://www.tensorflow.org/guide/gpu#using_multiple_gpus) and see if it helps you?.Thanks!

**Comment by liupengkd** [comment]
@ravikyram Thank you for your answer。I know how to set it in python，however， I want to set it in C
