### ISSUE TITLE
Error when run docker image on Mac OS X 10.11.1

### ISSUE THREAD

**Issue by jnd02** [tensorflow/tensorflow#34]
I'm getting the following error when trying to execute 
- docker run -it b.gcr.io/tensorflow/tensorflow 

9390232ac080: Error pulling image (latest) from b.gcr.io/tensorflow/tensorflow, endpoint: https://b.gcr.io/v1/, Server error: Status9390232ac080: Error pulling image (latest) from b.gcr.io/tensorflow/tensorflow, Server error: Status 403 while fetching image layer (a5a467fddcb8848a80942d0191134c925fa16ffa9655c540acd34284f4f6375d) 
ac65c371c3a5: Download complete 
a5a467fddcb8: Error pulling dependent layers 

Error pulling image (latest) from b.gcr.io/tensorflow/tensorflow, Server error: Status 403 while fetching image layer (a5a467fddcb8848a80942d0191134c925fa16ffa9655c540acd34284f4f6375d)

**Comment by lukovkin** [comment]
The same thing on Ubuntu 14.04. Maybe too much requests.

**Comment by mmolaro** [comment]
Can also confirm that pulling the docker image doesn't seem to work in Ubuntu 14.04. 
Is b.gcr.io actually set up to have public docker containers?

I thought the point of the Google cloud registry was to have private / authentication required containers.

https://cloud.google.com/container-registry/
"Google Container Registry provides secure, private Docker image storage on Google Cloud Platform."

**Comment by craigcitro** [comment]
hey all -- it looks like we picked up a permissions problem. looking now.

**Comment by craigcitro** [comment]
Should be fixed now.

**Comment by craigcitro** [comment]
I'm closing, but feel free to ping/re-open if you spot this again.

**Comment by craigcitro** [comment]
@mmolaro Actually, GCR is built to support public images (like this one), as well as serve more core infrastructure needs ("I want to serve images to other parts of my cluster"). But I'm looking into getting us on dockerhub, too.

**Comment by maadcodr** [comment]
When I run docker pull b.gcr.io/tensorflow/tensorflow, I get:

Error pulling image (latest) from b.gcr.io/tensorflow/tensorflow, Server error 401 while fetching image layer

Please advise,
Maad

**Comment by craigcitro** [comment]
@maadcodr I can't seem to repro this -- let's move to a new issue, and include some details about your setup (at least OS, docker version)?

**Comment by maadcodr** [comment]
@craigcitro  nvm it was a proxy/firewall issue...

**Comment by swayam01** [comment]
Swayam-MacBook-Pro:~ Swayam$ docker run -it gcr.io/tensorflow/tensorflow:latest-devel
docker: Error response from daemon: oci runtime error: container_linux.go:265: starting container process caused "exec: \"/bin/bash\": stat /bin/bash: no such file or directory".

Stuck with this error since morning! no answers available in forum

**Comment by craigcitro** [comment]
@swayam01 I can't seem to repro what you're seeing; my advice is to `docker pull gcr.io/tensorflow/tensorflow:latest-devel` and then try again.

If that doesn't work, go ahead and file a new issue.
