### ISSUE TITLE
Documentation unclear tf.batch_to_space

### ISSUE THREAD

**Issue by nikochiko** [tensorflow/tensorflow#34005]
## URL(s) with the issue:
https://www.tensorflow.org/api_docs/python/tf/batch_to_space

## Description of issue (what needs changing):
1. Example needs to be added.
2. `crops` part in `Args:` section is very difficult to understand. Needs to be better formatted (put into code). 

### Clear description:
Documentation is unclear, no example is shown. Also, there is one extremely long paragraph with code in between in the `crops` section under args.

### Parameters defined

Are all parameters defined and formatted correctly? 
=> Not well formatted.

### Returns defined

Are return values defined?
=> Yes

### Raises listed and defined

Are the errors defined? 
=> No

### Usage example

Is there a usage example?
=> No

### Submit a pull request?
=> No

**Comment by copperwiring** [comment]
@nikochiko Do you want to work on improving this section? I could not understand from the opened issue if you have only reported an issue or also proposed to work with it? In later case, I can join you in re-formatting the doc for this topic.

**Comment by nikochiko** [comment]
@copperwiring Sure, I would like to work on it. But I will have to look into its technical details before that. If you have any resources, it would be great if you share them. I'll try to learn something about it from code in the meanwhile.

**Comment by nikochiko** [comment]
@oanush Please assign this to me and @copperwiring . Will open a PR soon.

**Comment by ymodak** [comment]
@nikochiko Feel free to raise a PR and reference this issue. Thanks!

**Comment by dubesar** [comment]
@ymodak this issue be used for Google Code-in as a Documentation and research challenge?

**Comment by nikochiko** [comment]
@dubesar I had started working on the formatting part of the issue and was planning to make a PR till tomorrow. The job is mostly to 
- Sync the docs formatting with its [r1 version](https://www.tensorflow.org/versions/r1.15/api_docs/python/tf/batch_to_space_nd).
- Make the documentation easier to understand, editing it and adding "Examples:" and "Raises:" sections.
I can make some minor edits with the language to make it more suitable as a Google Code-In challenge. 
@ymodak , @dubesar ?

**Comment by dubesar** [comment]
@nikochiko Yeah that would be great if some part of this issue is available for Google Code-in

**Comment by nikochiko** [comment]
@dubesar See the referenced PR and a comment on it. I have made some additional changes and made the task more clear.

**Comment by nikochiko** [comment]
PR merged. Closing issue.
