### ISSUE TITLE
 About failed to load model from pb 

### ISSUE THREAD

**Issue by kscorpio** [tensorflow/tensorflow#34001]
I train the model in Ubuntu(VM) ,with tensorflow 1.14.0 , export pb file

but in android app whit tensorflow-android:1.13.1 ，can not load pb file

“ failed to load model from pb  ”

**Comment by ymodak** [comment]
Can you please try setting same version of TF in the android app as well?.
Update the android build dependencies to tensorflow-android:1.14.0

**Comment by kscorpio** [comment]
the latest version of tensorflow-android is 1.13.1 
> https://mvnrepository.com/artifact/org.tensorflow/tensorflow-android

**Comment by ymodak** [comment]
I beg your pardon, you are right. TensorFlow Mobile is deprecated.
See https://github.com/tensorflow/examples/blob/master/community/en/docs/tfmobile/android_build.md#building-tensorflow-on-android
 You may try using TF Lite for your case.
