### ISSUE TITLE
Can I say the version compatibility of tensorflow is just not great. 

### ISSUE THREAD

**Issue by yang-yk** [tensorflow/tensorflow#34002]
Can I say the version compatibility of tensorflow is just like shit. The code under older versions can not work at all under the new versions and you never know which version you should use. The defintions of  functions in different versions changes greatly and you never know which function is really what you need. When you want to run a new code, you have to try all the versions to make it work if you don't know its original tf version. Or you must change the code to statisfy the demand of the old versions. And sometimes you waste so much time and then you find you still can't make it work.
Anybody has the same problem? I think it's one of the most important reasons why more and more people are turning to pytorch.

**Comment by uday60** [comment]
Don't forget how painful it is to train on multiple gpus. f u Google !

**Comment by copperwiring** [comment]
Thank you for your feedback for tensor-flow version compatibility. TF is a growing community and efforts are being made to address this issue. If you have a specific concern w.r.t. t a certain problem, please don't forget to put the code snippets with the version issues for other to look at it.

TF accepts constructive criticism.

**Comment by ravikyram** [comment]
@yang-yk,
Thank you for reporting the issue.
In order to expedite the trouble-shooting process, please provide a code snippets along with versions you are facing the issue. Thanks!

**Comment by yang-yk** [comment]
> @yang-yk,
> Thank you for reporting the issue.
> In order to expedite the trouble-shooting process, please provide a code snippets along with versions you are facing the issue. Thanks!

Thanks for your reply and sorry for my rudeness. It’s about the tf estimator using multi-gpus. When I try to use the mirroredstrategy as what the official code teaches, there are always errors. Although I have tried tf version from 1.4 to 1.15, I still can't make it work. The errors are always different under different versions. I am so tired to solve the problem becasue it has taken me all day.  And I have experienced the version problems many  times. Once I was a supporter of tensorflow, but now I start try to use pytorch.  As mentioned above, the tf versions are too confusing. Learning the new version tf costs too much, and the previous codes also need to be corrected.  In most cases, when you just get used to the current tf, the completely different tf is released. And it is not compatible with the previous version. Having said so much, I just hope that tf will not be abandoned by researchers in the future.

**Comment by martinwicke** [comment]
@yang-yk the issue tracker is for feature requests or bug reports. Your complaint is not constructive in form or content. 

TensorFlow conforms to semver for backwards compatibility. If we violated [our promises](tensorflow.org/guide/versions), that would be a bug we can fix.

**Comment by yang-yk** [comment]
So disappointed! Both the framework and the reply.
