### ISSUE TITLE
Something wrong with "model.fit(x_train, y_train, epochs=5)"

### ISSUE THREAD

**Issue by githubzjm** [tensorflow/tensorflow#34003]
Even I copy the code like below from the official website and run it in jupyter notebook, I get an error:
**ValueError: Attempt to convert a value (5) with an unsupported type (<class 'numpy.uint8'>) to a Tensor.**
My tensorflow version is 2.0, plz help
```
import tensorflow as tf
mnist = tf.keras.datasets.mnist

(x_train, y_train),(x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10, activation='softmax')
])

model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

model.fit(x_train, y_train, epochs=5)
model.evaluate(x_test, y_test)

```

**Comment by nikochiko** [comment]
The code is correct. It should run well on both tf-1.x and tf -2.x. 
See these links:
https://github.com/nikochiko/code/blob/master/tf1_tf-issue_34003.ipynb
https://github.com/nikochiko/code/blob/master/tf2_tf-issue_34003.ipynb

**Comment by githubzjm** [comment]
Sure, here is the total error log, thanks a lot
> ---------------------------------------------------------------------------
> ValueError                                Traceback (most recent call last)
> <ipython-input-1-357d0cd1907d> in <module>
>      16               metrics=['accuracy'])
>      17 
> ---> 18 model.fit(x_train, y_train, epochs=5)
>      19 model.evaluate(x_test, y_test)
> 
> E:\Anaconda\lib\site-packages\tensorflow_core\python\keras\engine\training.py in fit(self, x, y, batch_size, epochs, verbose, callbacks, validation_split, validation_data, shuffle, class_weight, sample_weight, initial_epoch, steps_per_epoch, validation_steps, validation_freq, max_queue_size, workers, use_multiprocessing, **kwargs)
>     726         max_queue_size=max_queue_size,
>     727         workers=workers,
> --> 728         use_multiprocessing=use_multiprocessing)
>     729 
>     730   def evaluate(self,
> 
> E:\Anaconda\lib\site-packages\tensorflow_core\python\keras\engine\training_v2.py in fit(self, model, x, y, batch_size, epochs, verbose, callbacks, validation_split, validation_data, shuffle, class_weight, sample_weight, initial_epoch, steps_per_epoch, validation_steps, validation_freq, **kwargs)
>     222           validation_data=validation_data,
>     223           validation_steps=validation_steps,
> --> 224           distribution_strategy=strategy)
>     225 
>     226       total_samples = _get_total_number_of_samples(training_data_adapter)
> 
> E:\Anaconda\lib\site-packages\tensorflow_core\python\keras\engine\training_v2.py in _process_training_inputs(model, x, y, batch_size, epochs, sample_weights, class_weights, steps_per_epoch, validation_split, validation_data, validation_steps, shuffle, distribution_strategy, max_queue_size, workers, use_multiprocessing)
>     545         max_queue_size=max_queue_size,
>     546         workers=workers,
> --> 547         use_multiprocessing=use_multiprocessing)
>     548     val_adapter = None
>     549     if validation_data:
> 
> E:\Anaconda\lib\site-packages\tensorflow_core\python\keras\engine\training_v2.py in _process_inputs(model, x, y, batch_size, epochs, sample_weights, class_weights, shuffle, steps, distribution_strategy, max_queue_size, workers, use_multiprocessing)
>     604       max_queue_size=max_queue_size,
>     605       workers=workers,
> --> 606       use_multiprocessing=use_multiprocessing)
>     607   # As a fallback for the data type that does not work with
>     608   # _standardize_user_data, use the _prepare_model_with_inputs.
> 
> E:\Anaconda\lib\site-packages\tensorflow_core\python\keras\engine\data_adapter.py in __init__(self, x, y, sample_weights, batch_size, epochs, steps, shuffle, **kwargs)
>     319     dataset = dataset_ops.DatasetV2.zip((
>     320         indices_dataset,
> --> 321         dataset_ops.DatasetV2.from_tensors(inputs).repeat()
>     322     ))
>     323 
> 
> E:\Anaconda\lib\site-packages\tensorflow_core\python\data\ops\dataset_ops.py in from_tensors(tensors)
>     412       Dataset: A `Dataset`.
>     413     """
> --> 414     return TensorDataset(tensors)
>     415 
>     416   @staticmethod
> 
> E:\Anaconda\lib\site-packages\tensorflow_core\python\data\ops\dataset_ops.py in __init__(self, element)
>    2333   def __init__(self, element):
>    2334     """See `Dataset.from_tensors()` for details."""
> -> 2335     element = structure.normalize_element(element)
>    2336     self._structure = structure.type_spec_from_value(element)
>    2337     self._tensors = structure.to_tensor_list(self._structure, element)
> 
> E:\Anaconda\lib\site-packages\tensorflow_core\python\data\util\structure.py in normalize_element(element)
>     109         else:
>     110           normalized_components.append(
> --> 111               ops.convert_to_tensor(t, name="component_%d" % i))
>     112   return nest.pack_sequence_as(element, normalized_components)
>     113 
> 
> E:\Anaconda\lib\site-packages\tensorflow_core\python\framework\ops.py in convert_to_tensor(value, dtype, name, preferred_dtype, dtype_hint)
>    1182   preferred_dtype = deprecation.deprecated_argument_lookup(
>    1183       "dtype_hint", dtype_hint, "preferred_dtype", preferred_dtype)
> -> 1184   return convert_to_tensor_v2(value, dtype, preferred_dtype, name)
>    1185 
>    1186 
> 
> E:\Anaconda\lib\site-packages\tensorflow_core\python\framework\ops.py in convert_to_tensor_v2(value, dtype, dtype_hint, name)
>    1240       name=name,
>    1241       preferred_dtype=dtype_hint,
> -> 1242       as_ref=False)
>    1243 
>    1244 
> 
> E:\Anaconda\lib\site-packages\tensorflow_core\python\framework\ops.py in internal_convert_to_tensor(value, dtype, name, as_ref, preferred_dtype, ctx, accept_composite_tensors)
>    1294 
>    1295     if ret is None:
> -> 1296       ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
>    1297 
>    1298     if ret is NotImplemented:
> 
> E:\Anaconda\lib\site-packages\tensorflow_core\python\framework\tensor_conversion_registry.py in _default_conversion_function(***failed resolving arguments***)
>      50 def _default_conversion_function(value, dtype, name, as_ref):
>      51   del as_ref  # Unused.
> ---> 52   return constant_op.constant(value, dtype, name=name)
>      53 
>      54 
> 
> E:\Anaconda\lib\site-packages\tensorflow_core\python\framework\constant_op.py in constant(value, dtype, shape, name)
>     225   """
>     226   return _constant_impl(value, dtype, shape, name, verify_shape=False,
> --> 227                         allow_broadcast=True)
>     228 
>     229 
> 
> E:\Anaconda\lib\site-packages\tensorflow_core\python\framework\constant_op.py in _constant_impl(value, dtype, shape, name, verify_shape, allow_broadcast)
>     233   ctx = context.context()
>     234   if ctx.executing_eagerly():
> --> 235     t = convert_to_eager_tensor(value, ctx, dtype)
>     236     if shape is None:
>     237       return t
> 
> E:\Anaconda\lib\site-packages\tensorflow_core\python\framework\constant_op.py in convert_to_eager_tensor(value, ctx, dtype)
>      94       dtype = dtypes.as_dtype(dtype).as_datatype_enum
>      95   ctx.ensure_initialized()
> ---> 96   return ops.EagerTensor(value, ctx.device_name, dtype)
>      97 
>      98 
> 
> ValueError: Attempt to convert a value (5) with an unsupported type (<class 'numpy.uint8'>) to a Tensor.
>

**Comment by ravikyram** [comment]
@githubzjm 
I have tried on colab with TF version 2.0  and i am not seeing any error message. Please, find the gist [here](https://colab.sandbox.google.com/gist/ravikyram/5c1e097d5bb95ca5bc887e279e789e5e/untitled333.ipynb). Thanks!

**Comment by nikochiko** [comment]
@githubzjm , Do similar errors occur for other values of `epochs` ?

**Comment by githubzjm** [comment]
Yes, I change the value of epochs to 6 and the error is the same：
**ValueError: Attempt to convert a value (5) with an unsupported type (<class 'numpy.uint8'>) to a Tensor.**

**Comment by ravikyram** [comment]
@githubzjm 

Do you have multiple versions of numpy installed in your system?
Please check using `pip show numpy`
Can you uninstall all numpy versions and later install numpy==1.16.4?
`pip uninstall numpy` (till you uninstall all versions) then you install `pip install numpy==1.16.4` and check whether the issue still persists?. Thanks!

**Comment by githubzjm** [comment]
Thanks, I have solved it! But it seems not the various versions of numpy caused the problem, but the old version 1.15.4 somehow doesn't work well for Tensorflow2.0. Do not need to uninstall all numpy versions, just use `conda update numpy` to update.

Besides, `pip show numpy` only shows me one version of numpy at first(now it can't find any file after I run `conda remove numpy`), but `conda search numpy`  shows many installed verisons.

**Comment by ravikyram** [comment]
@githubzjm 

I am closing the issue, since the query is been resolved. Thanks!
