### ISSUE TITLE
tf.keras.layers.SimpleRNN doesn't use GPU?

### ISSUE THREAD

**Issue by airplane2230** [tensorflow/tensorflow#34004]
First, This is a example in TensorFlow 2.0 with Keras.

```
from tensorflow.keras.datasets import imdb

num_words = 10000
(X_train, y_train), (X_test, y_test) = imdb.load_data(num_words=num_words)

from tensorflow.keras.preprocessing.sequence import pad_sequences

max_len = 500

pad_X_train = pad_sequences(X_train, maxlen=max_len)
pad_X_test = pad_sequences(X_test, maxlen=max_len)

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import SimpleRNN, Dense, Embedding  

model = Sequential()
model.add(Embedding(input_dim = num_words, output_dim = 32))
model.add(SimpleRNN(32, return_sequences = True, dropout = 0.15, recurrent_dropout = 0.15))
model.add(SimpleRNN(32))
model.add(Dense(1, activation = 'sigmoid'))

model.compile(optimizer='adam',
             loss = 'binary_crossentropy',
             metrics = ['acc'])

# model.summary()

history = model.fit(pad_X_train, y_train, 
                    batch_size = 32, epochs = 15, 
                    validation_split = 0.2)
```

+ Use Window 10 and TF 2.0
+ NVidia Driver : 418.81
+ CUDA : 10.1
+ GPU : GeForce GTX 1050

And, When I use the layer SimpleRNN in keras, GPU-Utils is very low. what happen??
![image](https://user-images.githubusercontent.com/33315343/68199250-04940c00-0001-11ea-9b53-b315e6ff8505.png)

For checking if my GPU worked correctly, I use it using Conv2D.
![image](https://user-images.githubusercontent.com/33315343/68199475-753b2880-0001-11ea-90be-bae41dc5d637.png)

The above picture was run on the MNIST dataset, which does not seem to require much GPU-Utils.

I haven't seen 100% use, but my GPU seems to work fine.

Stacking multiple SimpleRNN layers or using just one will not increase GPU-Utils at 10%. 
What's wrong?

Is it because of the feature of the layer?

**Comment by gowthamkpr** [comment]
@airplane2230 Can you share a github gist reproducing the issue on colab. Thanks!

**Comment by gowthamkpr** [comment]
In TensorFlow 2.0, if you want to use GPU, you need to pip install tensorflow-gpu==2.0

Some history:
For a long time the tensorflow pip package was CPU only and the tensorflow-gpu pip package was GPU only. This was still true when TensorFlow 2.0 was released.

TensorFlow 1.15.0 was released after TensorFlow 2.0, and that was the first package where the tensorflow pip package could work with either GPU or CPU.

TensorFlow 2.1.0, when released, should work the same as TensorFlow 1.15.0 does, but for now to use GPU with TensorFlow 2.0, you need to install tensorflow-gpu

**Comment by airplane2230** [comment]
Thank you for your answer.

In my writing, The sentence 'Use Window 10 and TF 2.0' is wrong.

Correctly, 'Use Window 10 and TF 2.0-gpu'. 

This mean, I already install tensorflow-gpu==2.0.0 and The above code run in this environment!

thanks.

**Comment by sanjoy** [comment]
Can you please attach the logs that TensorFlow generated?

**Comment by airplane2230** [comment]
Thank you for your answer. 

what is the logs?

In the Running Time, there is no logs. Just run only.

The SimpleRNN example code attached to this shows that 
the training is very slow even when compared to the layered LSTM or CNN code.

Thank you!

**Comment by sanjoy** [comment]
By "logs" I meant the entire output of the TF program.

However, re-reading the bug report, I don't think the logs will be super useful.  In your case the TF program _is using_ the GPU, just not as much you'd expect, right?

This sort of thing is very hard to debug over email, I'd suggest using the [trace viewer](https://www.tensorflow.org/tensorboard/tensorboard_profiling_keras#trace_viewer) to see if you can spot any red flags.
