### ISSUE TITLE
crop_and_resize_v2() got an unexpected keyword argument 'box_ind'，how to understand the 'box_ind' when the num_boxes equal to 1, batch_size equal to 32?

### ISSUE THREAD

**Issue by lxz1104** [tensorflow/tensorflow#34011]
I am using the ROI_pooling layer for feature extraction. The dimension of the feature map is 32 * 12 * 12 * 64, and the output clipping dimension is 7 * 7. Only one clipping is needed. How do I use the function tf.image.crop_and_ resize?

**Comment by omega-accelr** [comment]
Hi @lxz1104 ,
Would you please tell me how did you solved this issue?
