### ISSUE TITLE
Run a TensorFlow demo model : IOError: CRC check failed

### ISSUE THREAD

**Issue by wfs** [tensorflow/tensorflow#3401]
### Environment info
Operating System:
(tensorflow) paddlescoot@paddlescoot-Satellite-P870:~$ cat /proc/version
Linux version 4.4.0-31-generic (buildd@lgw01-16) (gcc version 5.3.1 20160413 (Ubuntu 5.3.1-14ubuntu2.1) ) #50-Ubuntu SMP Wed Jul 13 00:07:12 UTC 2016

If installed from binary pip package, provide:

1. Which pip package you installed.
Follow python 2.7 virtualenv installtion notes - https://www.tensorflow.org/versions/r0.9/get_started/os_setup.html#virtualenv-installation
2. The output from `python -c "import tensorflow; print(tensorflow.__version__)"`.
0.9.0

### Steps to reproduce
1. Follow Test notes here - https://www.tensorflow.org/versions/r0.9/get_started/os_setup.html#test-the-tensorflow-installation
2. When you get to the last step, the following error appears : 
(tensorflow) paddlescoot@paddlescoot-Satellite-P870:~$ python /home/paddlescoot/tensorflow/local/lib/python2.7/site-packages/tensorflow/models/image/mnist/convolutional.py
Extracting data/train-images-idx3-ubyte.gz
Traceback (most recent call last):
  File "/home/paddlescoot/tensorflow/local/lib/python2.7/site-packages/tensorflow/models/image/mnist/convolutional.py", line 316, in <module>
    tf.app.run()
  File "/home/paddlescoot/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 30, in run
    sys.exit(main(sys.argv))
  File "/home/paddlescoot/tensorflow/local/lib/python2.7/site-packages/tensorflow/models/image/mnist/convolutional.py", line 128, in main
    train_data = extract_data(train_data_filename, 60000)
  File "/home/paddlescoot/tensorflow/local/lib/python2.7/site-packages/tensorflow/models/image/mnist/convolutional.py", line 75, in extract_data
    buf = bytestream.read(IMAGE_SIZE * IMAGE_SIZE * num_images)
  File "/usr/lib/python2.7/gzip.py", line 268, in read
    self._read(readsize)
  File "/usr/lib/python2.7/gzip.py", line 315, in _read
    self._read_eof()
  File "/usr/lib/python2.7/gzip.py", line 354, in _read_eof
    hex(self.crc)))
IOError: CRC check failed 0xb3e5d2f6 != 0x255cc2beL

### What have you tried?
1. Searching similar issues.

**Comment by concretevitamin** [comment]
I cannot reproduce, as this sounds like the download of the MNIST data zip files failed.

Could you try to manually download the MNIST zip files, and replace the corrupted versions with the fresh ones?

**Comment by wfs** [comment]
Thanks @concretevitamin . Yes something happened to the file on original download.

Was ...
9609216 train-images-idx3-ubyte.gz

Should be ...
9912422 train-images-idx3-ubyte.gz

Manually downloaded, re-ran convolutional.py and it worked.

**Comment by layumi** [comment]
I meet the same problem when I run /models/tutorials/image/imagenet/classify_image.py. 
I delete /tmp/imagenet/inception-2015-12-05.tgz  and re-download the model. The problem was solved.

**Comment by tigerpup** [comment]
I met the same problem deleting the data dir in the same folder as the script worked for me

**Comment by datomnurdin** [comment]
any solution for this?
