### ISSUE TITLE
Keras' load_weights() bug: ValueError: You are trying to load a weight file containing 1 layers into a model with 0 layers.

### ISSUE THREAD

**Issue by netw0rkf10w** [tensorflow/tensorflow#34016]
**System information**
- Have I written custom code: Yes
- OS Platform and Distribution: Colab
- TensorFlow version: 2.0.0

**Describe the current behavior**

Using `model.save_weights()` and then `model.load_weights()` caused this error:
`ValueError: You are trying to load a weight file containing 1 layers into a model with 0 layers.`

**Code to reproduce the issue**
See [this Colab notebook](https://colab.research.google.com/drive/1-8kVsk-2PMTX_V_6VRHMWczz4T_4MPev).

**Comment by karmel** [comment]
In 2.0, the default saving format is the TensorFlow checkpoint format. Can you try using the TF checkpoint format and see if the colab works? (Just remove the .h5 extension in the save filename, and it will save out to TF checkpoint format.)

**Comment by netw0rkf10w** [comment]
Hi @karmel,
Saving to TF format should work. However, one cannot later load the weights with `by_name=True, skip_mismatch=True`, which I need for doing transfer learning. I tried this on TF 2.1.0.dev20191103 but obtained `Error: shapes incompatible` (the pretrained weights were trained from a different dataset having a different number of classes).

**Comment by jvishnuvardhan** [comment]
@netw0rkf10w As mentioned by @karmel I changed your code to save weights in *.tf format and everything works as expected. [Here](https://colab.sandbox.google.com/gist/jvishnuvardhan/1404f0bfd5a429b585f1de847600ae5a/tf_checkpoint.ipynb) is the gist for your reference. 

I am closing this issue as it was resolved. Please feel free to open if the issue persists with any other models. Thanks!

**Comment by netw0rkf10w** [comment]
@jvishnuvardhan You are basically saying that the `.h5` format is not officially supported? In that case please remove it from your documentation then.

**Comment by jvishnuvardhan** [comment]
@netw0rkf10w Sorry. I didn't mean that we are not officially supporting `.h5` format. Thanks!
If you want us to look in detail at your issue, please provide a simple standalone code to reproduce the error. Thanks!

**Comment by jvishnuvardhan** [comment]
@netw0rkf10w I think with subclass model, the input/output shape is unknown until it is first tested with proper data. I updated your code as follows which worked without any issue with .h5 format.
 
```
net2 = Net(classes=5)
temp_predictions = net2(sample[0])
net2.load_weights('./net.h5')
new_predictions = net2(sample)
```

Please check the [gist here](https://colab.sandbox.google.com/gist/jvishnuvardhan/fbc2cdea31a5b588a6525b2d62f009c0/tf_checkpoint.ipynb).

Please close the issue if it is resolved. Thanks!

**Comment by jvishnuvardhan** [comment]
I am closing the issue as it was resolved. Please feel free to open it if the issue persists again. Thanks!
