### ISSUE TITLE
Rename this repo to Big Migraine !!

### ISSUE THREAD

**Issue by uday60** [tensorflow/tensorflow#34017]
I don;t know which version to use for which purpose ... huge compatibility disaster !
Training on multiple gpu even bill gates cannot do...
AVX instructions are missing for pip install...
Tensorflow lite, Tensorflow TFX, Tensorflow serving.... crap after crap.
whether to use keras or tensorflow
There are no performance matrix comparing and converting your models...
Even the book publishers and article writers are confused which version should they be using....

**Comment by martinwicke** [comment]
The issue tracker is for bug reports, or feature requests.

**Comment by jamessmith90** [comment]
+1 for not releasing cuda 10.1 even after 8 months.
