### ISSUE TITLE
Error message in Hello_world example - ML for micro 

### ISSUE THREAD

**Issue by Gus-Ghedim** [tensorflow/tensorflow#34013]
I am having the following error message when I am trying to run the hello_world example for microcontrollers:

`C:\Users\arge10\tensorflow>make -f tensorflow/lite/experimental/micro/tools/make/Makefile TARGET=mbed TAGS="CMSIS disco_f746ng" generate_hello_world_mbed_project
process_begin: CreateProcess(NULL, uname -m, ...) failed.
-m was unexpected at this time.
tensorflow/lite/experimental/micro/tools/make/download_and_extract.sh "https://github.com/google/gemmlowp/archive/719139ce755a0f31cbf1c37f7f98adcc7fc9f425.zip" "7e8191b24853d75de2af87622ad293ba" tensorflow/lite/experimental/micro/tools/make/downloads/gemmlowp
'tensorflow' is not recognized as an internal or external command,
operable program or batch file.
tensorflow/lite/experimental/micro/tools/make/Makefile:240: recipe for target 'tensorflow/lite/experimental/micro/tools/make/downloads/gemmlowp' failed
make: *** [tensorflow/lite/experimental/micro/tools/make/downloads/gemmlowp] Error 1`

I searched for some solution on the internet about this issue, but I was unable to find any solution
Did someone else face this problem before?

**Comment by gadagashwini** [comment]
@Gus-Ghedim, Please provide details about what platform you are using (operating system, architecture). 
Make sure you also include the exact command if possible to produce the output included in your test case. 
Thanks!

**Comment by gadagashwini** [comment]
@Gus-Ghedim, Provide more information about the issue. Thanks!

**Comment by gadagashwini** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
