### ISSUE TITLE
Support key mapping in TFRecord

### ISSUE THREAD

**Issue by Officium** [tensorflow/tensorflow#34037]
**System information**
- TensorFlow version (you are using): 2.0
- Are you willing to contribute it (Yes/No): Yes

**Describe the feature and the current behavior/state.**
For multiple features situation like recommendation, names of features will take a lot of spaces in tfrecord files. A simple solution is replacing name by feature's index. Do this compression automatically needs change tfrecord file. Support a user-specific option maybe better.

**Will this change the current api? How?**
Add a key mapping parameter to `tf.data.TFRecordDataset`, `tf.io.TFRecordWriter` and `tf.data.FixedLengthRecordDataset`.

**Who will benefit with this feature?**
Save disk space for industry situations.

**Any Other info.**

**Comment by ravikyram** [comment]
@Officium 
Do you have any use case that requires the feature you are interested in? Please feel free to submit a PR if you have use cases that supports that feature. Thanks!

**Comment by Officium** [comment]
@ravikyram In CTR prediction task, one may use statistics of history over several dimensions to construct features. For example, a user's features contains the average click count on advertises with same category of users with same gender in past 7 days. A middle size advertise system may use thousands of such features. For system implementation, the feature consistence between online and offline is important. So the features used online will be recored in logs which can be converted to TFRecords by Spark for offline training. Here is a simple comparison case. In this case, mapping name to index will save 13% store spaces.
```python
import itertools
import random

import tensorflow as tf
from tqdm import trange


def construct_feature_names():
    id_features = ['age', 'gender', 'category', 'city', 'system']
    dense_features = ['impression', 'click', 'ctr', 'pagetime']
    time_features = [1, 7, 14, 28]

    total_features = []
    for cross_num in range(len(id_features)):
        for id_cross in itertools.combinations(id_features, cross_num):
            for dense, time in itertools.product(dense_features, time_features):
                total_features.append('_'.join(id_cross + (dense, str(time))))
    return total_features


def write_tfrecord(write_path, num_sample=10000, use_index_key=False):
    """
    Write random samples to tfrecord
    Args:
        write_path (str): file path to write
        num_sample (int): total number of random samples
        use_index_key (bool): whether use feature's index to replace its name
    """
    with tf.io.TFRecordWriter(write_path, 'GZIP') as writer:
        for _ in trange(num_sample):
            features = {}
            for name in construct_feature_names():
                key = name if not use_index_key else str(len(features))
                features[key] = tf.train.Feature(int64_list=tf.train.Int64List(value=[int(10000000 * random.random())]))
            tfrecord_example = tf.train.Example(features=tf.train.Features(feature=features))
            writer.write(tfrecord_example.SerializeToString())


write_tfrecord('index.tfrecord', use_index_key=True)
write_tfrecord('raw.tfrecord', use_index_key=False)
```

**Comment by Officium** [comment]
@ravikyram This feature will support a time-space tradeoff. In real system, TBs of data will be used for distributional training.  It saves disk space and network transmission time but increases loading time. Basically, it provides improvement.

**Comment by tilakrayal** [comment]
@Officium,
Have you got the chance to take a look at this official document where the required features were added in the upcoming tensorflow versions.
https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/data/TFRecordDataset
https://www.tensorflow.org/api_docs/python/tf/data/FixedLengthRecordDataset




key_func | A function mapping a nested structure of tensors (having shapes and types defined by self.output_shapes and self.output_types) to a scalar tf.int64 tensor.
-- | --
reduce_func | A function mapping a key and a dataset of up to window_size consecutive elements matching that key to another dataset.
window_size | A tf.int64 scalar tf.Tensor, representing the number of consecutive elements matching the same key to combine in a single batch, which will be passed to reduce_func. Mutually exclusive with window_size_func.
window_size_func | A function mapping a key to a tf.int64 scalar tf.Tensor, representing the number of consecutive elements matching the same key to combine in a single batch, which will be passed to reduce_func. Mutually exclusive with window_size.
