### ISSUE TITLE
How to add android_sdk_repository rule into workspace.bzl?

### ISSUE THREAD

**Issue by shauryad15** [tensorflow/tensorflow#34031]
I build tensorflow without android. Now i want to add android_sdk_repository and android_ndk rule into workspace.bzl so that i can build the apk.

I've tried adding :
android_sdk_repository(
name = "androidsdk",
// Set the path to the directory the Android SDK was unzipped into.
path = "/home/shaurya/Android/Sdk",
// Set the API level of the installed SDK Platform.
api_level = 28,
// Set the version of the build tools (a directory inside build-tools)
build_tools_version="28.0.2"
)
into workspace.bzl inside tensorflow but i'm getting this error :name 'android_sdk_repository' is not defined need help.

**Comment by freedomtan** [comment]
Please write configurations into **WORKSPACE** or **.bazelrc**, check the [Android quickstart
](https://www.tensorflow.org/lite/guide/android#build_tensorflow_lite_locally) for more details.

**Comment by shauryad15** [comment]
ok, but as you see, while i'm trying to write these configurations, i'm getting the above mentioned error. Can you please let me know the exact format so that I can add it into workspace.bzl?

**Comment by jdduke** [comment]
Rather than modifying it manually, have you tried instead running the `configure` script in the root checkout directory, and explicitly pointing the script to your Android SDK/NDK when prompted?

**Comment by freedomtan** [comment]
@shauryad15 As suggested by @jdduke, there are some options
1. try `configure`
2. read the article I mentioned and write configurations to `.tf_configure.bazelrc` manually
3. write your configurations into `WORKSPACE`, see this [bazel doc](https://docs.bazel.build/versions/master/be/android.html) for what/how to write.

**Comment by shauryad15** [comment]
@jdduke Ok, so you're suggesting me to rebuild tensorflow?
@freedomtan can you please provide me the link?

**Comment by freedomtan** [comment]
@shauheen links were in previous comments already.
