### ISSUE TITLE
how to use tensorflow lite gpu delegate in android object detection ? 

### ISSUE THREAD

**Issue by WestbrookZero** [tensorflow/tensorflow#34033]
private Interpreter tfLite;
public static Classifier create(
      final AssetManager assetManager,
      final String modelFilename,
      final String labelFilename,
      final int inputSize,
      final boolean isQuantized)
      throws IOException 
{
        -------------------------
      try {
          GpuDelegate delegate = new GpuDelegate();
          Interpreter.Options options = (new Interpreter.Options()).addDelegate(delegate);
          /*d.tfLite = new Interpreter(loadModelFile(assetManager, modelFilename));*/
         d.tfLite = new Interpreter(loadModelFile(assetManager, modelFilename), options);
        while (true) {
           writeToInput(input);
           d.tfLite.run(input, output);
           readFromOutput(output);
      }
       delegate.close();
       -------------------------
}
   what does it means for input and output ? how to transmit parameter  input and out ?

**Comment by ravikyram** [comment]
@WestbrookZero 
Can you please go through the [link ](https://www.tensorflow.org/lite/performance/gpu)and see if it helps you. Thanks!

**Comment by ravikyram** [comment]
@WestbrookZero 

Any updates please. Thanks!

**Comment by WestbrookZero** [comment]
I read the tensorflow lite website gpu delegate tutorial , I used android aar , implementation 'org.tensorflow:tensorflow-lite-gpu:0.0.0-nightly' ，but there is still cpu increasing too much . if i used   implementation 'org.tensorflow:tensorflow-lite-gpu:2.0.0' ,  there is no cpu increasing , but can't recognize image .

**Comment by jdduke** [comment]
The detection sample ships a quantized model, which isn't accelerated on the GPU. We'll likely be addressing this in a future update which has both float/quantized models in the sample. 

Note that you should really try to avoid re-creating the Interpreter/Delegate for just a single inference call.  Please have a look at our detection example @ https://github.com/tensorflow/examples/blob/master/lite/examples/object_detection/android/README.md.

**Comment by WestbrookZero** [comment]
@jdduke  I used float SSDMobileNetV2 model ，android aar gpu version “org.tensorflow:tensorflow-lite-gpu:0.0.0-nightly” , but cpu is still increasing . i  refer to  "https://github.com/tensorflow/examples/blob/master/lite/examples/object_detection/android/README.md" this demo ,  It is to change the code below 
`d.tfLite = new Interpreter(loadModelFile(assetManager, modelFilename));`
With the following code
`import org.tensorflow.lite.gpu.GpuDelegate;
private GpuDelegate gpuDelegate;
GpuDelegate delegate = new GpuDelegate();
Interpreter.Options options = (new Interpreter.Options()).addDelegate(delegate);
d.tfLite = new Interpreter(loadModelFile(assetManager, modelFilename), options);`
I don't know what does it mean " try to avoid re-creating the Interpreter/Delegate for just a single inference call "

**Comment by jdduke** [comment]
My comment about avoiding recreation was based on your snippet in the original issue report. If that's not how you're actually using it in the app, that's fine.

What device(s) are you testing against? And can you provide a link to the exact .tflite model you're using? Thanks.

**Comment by WestbrookZero** [comment]
I used android device , link : https://storage.googleapis.com/download.tensorflow.org/models/tflite/gpu/mobile_ssd_v2_float_coco.tflite

**Comment by jdduke** [comment]
> I used android device 

Yes, but which android device exactly? Can you output the result of `adb shell getprop ro.product.device`? Performance can vary widely depending on the CPU/GPU that is used. For instance, on a Pixel 4, CPU w/ 4 threads is 30ms, and the GPU is 10ms. On a Pixel 3a, CPU w/ 4 threads is 100ms, and the GPU is 30ms.
