### ISSUE TITLE
TFLite Micro allocator, need to set quantized_dimension

### ISSUE THREAD

**Issue by driedler** [tensorflow/tensorflow#34056]
In the latest master, 

tensorflow/lite/experimental/micro/micro_allocator.cc

In `InitializeRuntimeTensor()` near line 365, need to add:

```
quantization->quantized_dimension = src_quantization->quantized_dimension();
```

**Comment by MeghnaNatraj** [comment]
As the issues seems to be resolved in [Line 490] (https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/experimental/micro/micro_allocator.cc#L490), we're closing it. Reopen if it hasn't been resolved with the following information:

Provide the updated the line number where the `quantized_dimension` needs to be set from the latest git commit. The function `InitializeRuntimeTensor()` seems to start from a new [Line 376] (https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/experimental/micro/micro_allocator.cc#L376) now .
