### ISSUE TITLE
InternalError:  Blas GEMM launch failed

### ISSUE THREAD

**Issue by germanjke** [tensorflow/tensorflow#34069]
**System information**
- Uusing a stock example script provided in TensorFlow (first guide with mnist dataset), so code is 100% right. And this problem haunts me in every model :(
- OS Platform: Windows 10
- TensorFlow installed from (source or binary): pip3 install tensorflow-gpu . And i have a quustion here: shouild i install keras? I think its already in tf 2.0
- TensorFlow version (use command below): 2.0.0
- Python version: 3.7.5
- CUDA/cuDNN version: 10.1 / 7.6.5
- GPU model and memory: GTX 1060 3GB

**Describe the problem**
I train the model described in the guides on the official tf website, so there can be no problems with the code. When I start learning the model, I have a bug from below. This happens not only on this code, but also on others. I have the latest versions of cuda and cudnn, visual studio 2017.

**Interesting**
On one of the sites I saw a solution to the problem as follows: conda update --all. Indeed, after this command and reboot I can train the model, but only ONCE, the next model will be with the same error.

**Code to reproduce the issue**
model = keras.Sequential([
    keras.layers.Flatten(input_shape=(28, 28)),
    keras.layers.Dense(128, activation='relu'),
    keras.layers.Dense(10, activation='softmax')
])
model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])
model.fit(train_images, train_labels, epochs=10)

**Error Log**
---------------------------------------------------------------------------
InternalError                             Traceback (most recent call last)
<ipython-input-10-41cd0b44e416> in <module>
      2 
      3 model.fit(partial_train_data, partial_train_targets,
----> 4         epochs=num_epochs, batch_size=1, verbose=0)

~\Anaconda3\lib\site-packages\tensorflow_core\python\keras\engine\training.py in fit(self, x, y, batch_size, epochs, verbose, callbacks, validation_split, validation_data, shuffle, class_weight, sample_weight, initial_epoch, steps_per_epoch, validation_steps, validation_freq, max_queue_size, workers, use_multiprocessing, **kwargs)
    726         max_queue_size=max_queue_size,
    727         workers=workers,
--> 728         use_multiprocessing=use_multiprocessing)
    729 
    730   def evaluate(self,

~\Anaconda3\lib\site-packages\tensorflow_core\python\keras\engine\training_v2.py in fit(self, model, x, y, batch_size, epochs, verbose, callbacks, validation_split, validation_data, shuffle, class_weight, sample_weight, initial_epoch, steps_per_epoch, validation_steps, validation_freq, **kwargs)
    322                 mode=ModeKeys.TRAIN,
    323                 training_context=training_context,
--> 324                 total_epochs=epochs)
    325             cbks.make_logs(model, epoch_logs, training_result, ModeKeys.TRAIN)
    326 

~\Anaconda3\lib\site-packages\tensorflow_core\python\keras\engine\training_v2.py in run_one_epoch(model, iterator, execution_function, dataset_size, batch_size, strategy, steps_per_epoch, num_samples, mode, training_context, total_epochs)
    121         step=step, mode=mode, size=current_batch_size) as batch_logs:
    122       try:
--> 123         batch_outs = execution_function(iterator)
    124       except (StopIteration, errors.OutOfRangeError):
    125         # TODO(kaftan): File bug about tf function and errors.OutOfRangeError?

~\Anaconda3\lib\site-packages\tensorflow_core\python\keras\engine\training_v2_utils.py in execution_function(input_fn)
     84     # `numpy` translates Tensors to values in Eager mode.
     85     return nest.map_structure(_non_none_constant_value,
---> 86                               distributed_function(input_fn))
     87 
     88   return execution_function

~\Anaconda3\lib\site-packages\tensorflow_core\python\eager\def_function.py in __call__(self, *args, **kwds)
    455 
    456     tracing_count = self._get_tracing_count()
--> 457     result = self._call(*args, **kwds)
    458     if tracing_count == self._get_tracing_count():
    459       self._call_counter.called_without_tracing()

~\Anaconda3\lib\site-packages\tensorflow_core\python\eager\def_function.py in _call(self, *args, **kwds)
    518         # Lifting succeeded, so variables are initialized and we can run the
    519         # stateless function.
--> 520         return self._stateless_fn(*args, **kwds)
    521     else:
    522       canon_args, canon_kwds = \

~\Anaconda3\lib\site-packages\tensorflow_core\python\eager\function.py in __call__(self, *args, **kwargs)
   1821     """Calls a graph function specialized to the inputs."""
   1822     graph_function, args, kwargs = self._maybe_define_function(args, kwargs)
-> 1823     return graph_function._filtered_call(args, kwargs)  # pylint: disable=protected-access
   1824 
   1825   @property

~\Anaconda3\lib\site-packages\tensorflow_core\python\eager\function.py in _filtered_call(self, args, kwargs)
   1139          if isinstance(t, (ops.Tensor,
   1140                            resource_variable_ops.BaseResourceVariable))),
-> 1141         self.captured_inputs)
   1142 
   1143   def _call_flat(self, args, captured_inputs, cancellation_manager=None):

~\Anaconda3\lib\site-packages\tensorflow_core\python\eager\function.py in _call_flat(self, args, captured_inputs, cancellation_manager)
   1222     if executing_eagerly:
   1223       flat_outputs = forward_function.call(
-> 1224           ctx, args, cancellation_manager=cancellation_manager)
   1225     else:
   1226       gradient_name = self._delayed_rewrite_functions.register()

~\Anaconda3\lib\site-packages\tensorflow_core\python\eager\function.py in call(self, ctx, args, cancellation_manager)
    509               inputs=args,
    510               attrs=("executor_type", executor_type, "config_proto", config),
--> 511               ctx=ctx)
    512         else:
    513           outputs = execute.execute_with_cancellation(

~\Anaconda3\lib\site-packages\tensorflow_core\python\eager\execute.py in quick_execute(op_name, num_outputs, inputs, attrs, ctx, name)
     65     else:
     66       message = e.message
---> 67     six.raise_from(core._status_to_exception(e.code, message), None)
     68   except TypeError as e:
     69     keras_symbolic_tensors = [

~\Anaconda3\lib\site-packages\six.py in raise_from(value, from_value)

InternalError:  Blas GEMM launch failed : a.shape=(1, 13), b.shape=(13, 64), m=1, n=64, k=13
	 [[node sequential/dense/MatMul (defined at C:\Users\Gera\Anaconda3\lib\site-packages\tensorflow_core\python\framework\ops.py:1751) ]] [Op:__inference_distributed_function_785]

Function call stack:
distributed_function

**Comment by oanush** [comment]
@germanjke ,
Can you please refer links of these similar issue's and solutions present in them and see if it solves the issue, [1 ](https://github.com/tensorflow/tensorflow/issues/11812)[2](https://stackoverflow.com/questions/37337728/tensorflow-internalerror-blas-sgemm-launch-failed) and [3](https://stackoverflow.com/questions/43990046/tensorflow-blas-gemm-launch-failed?rq=1).

**Comment by germanjke** [comment]
> @germanjke ,
> Can you please refer links of these similar issue's and solutions present in them and see if it solves the issue, [1 ](https://github.com/tensorflow/tensorflow/issues/11812)[2](https://stackoverflow.com/questions/37337728/tensorflow-internalerror-blas-sgemm-launch-failed) and [3](https://stackoverflow.com/questions/43990046/tensorflow-blas-gemm-launch-failed?rq=1).Thanks!

@oanush 
I got the decision on the first link. The problem was that I had discovered too many JupyterNotebooks. When I closed them, launched one and rebooted kernel everything works. Thank you very much!

**Comment by oanush** [comment]
Thank you,closing since issue is resolved.

**Comment by vijendra21vijendra** [comment]
i have done everything listed here but none is working
