### ISSUE TITLE
Work group size selection in OpenGL

### ISSUE THREAD

**Issue by Lumosis** [tensorflow/tensorflow#34064]
**System information**
- TensorFlow version (you are using): v2.0.0
- Are you willing to contribute it (Yes/No): Yes

**Describe the feature and the current behavior/state.**
Hi, I am running tensorflow lite v2.0.0 on my Mali-G72 and Adreno 630 GPUs. I have read some of the tf lite source codes in order to see how you make use of OpenGL. 

In /tensorflow/tensorflow/lite/delegates/gpu/gl/workgroups/calculator_from_metadata.cc, I noticed you are trying to choose a proper work group size. However, it seems it did not really use calculator_from_metadata but to use default_calculator_ when running on my GPUs. Intuitively, I believe that the choice of work group size influences the performance and a choice from calculator_from_metadata should be better. But calculator_from_metadata is not working because there is not any data saved in the vector workgroups_. 
Have you finished this part, yet? I would appreciate it if you can share any information about this.

**Comment by impjdi** [comment]
@Lumosis 

Hi there, thanks for digging deeper into the code and noticing this detail :)

You are very welcome to experiment with the workgroup sizes.  What we have observed in the past is that Adreno is more susceptible to workgroup changes, and can get up to 30% faster if you choose a good workgroup size or also 30% slower if you choose a bad one.  Now, with Mali devices, we strangely only saw a drop of performance no matter what we did, so we decided to leave Mali as is.  We might want some advice from Mali experts who is not present nearby our team =/

**Comment by Lumosis** [comment]
@impjdi 

Hi impjdi, I wonder which model you were using to test performance for different group sizes. I tested using different group sizes (on Adreno) on single op model, like add_1024x1024, but did not find large fluctuations. The inference time basically fluctuated with 2% range. Could you share some information?

**Comment by impjdi** [comment]
Yeah, I don't think we tweaked any ops like ADD.  IIRC we only investigated
in CONV & DWCONV.  Our paper that describes our investigation in workgroup
sizes is here: https://arxiv.org/abs/1907.01989

Of course, it may have changed since the paper; the paper was written in
April, we had someone else look at it since then, and there was some recent
submission around the workgroup size calculation.

**Comment by brucechou1983** [comment]
@impjdi do you have any update about Mali GPU wg selection?

**Comment by impjdi** [comment]
Unfortunately, no.  We have played around with Mali workgroup sizes, but haven't seen much performance difference which is not intuitive.

**Comment by brucechou1983** [comment]
@impjdi Thanks for sharing the information. I basically did the same thing, and I don't have any idea about what MALI wg sizes actually affect. It's also weird that for some TFLite models, I found that devices with older MALI GPU models (say G72 and T880) run even 1.5-2x faster than ones with newer models (G76).

**Comment by kumariko** [comment]
Could you please let us know if this issue still persists ? If it is resolved then please feel free to move this issue to close status ? please refer [link](https://stackoverflow.com/questions/19477348/opencl-opengl-interop-dimensions-of-a-renderbuffer-in-relation-to-workgroup-size), [link](https://stackoverflow.com/questions/11466162/work-group-sizes) . Thanks!
