### ISSUE TITLE
Building TensorFlow 2 with bazel fails

### ISSUE THREAD

**Issue by ShaharATterrain** [tensorflow/tensorflow#34075]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (Windows 10):
- TensorFlow installed from (source):
- TensorFlow version: 2.0 (master branch on 07 Nov 2019, to be exact)
- Python version: 3.7
- Installed using virtualenv? pip? conda?: No
- Bazel version (if compiling from source): 0.29.1
- GCC/Compiler version (if compiling from source):  8.1.0
- CUDA/cuDNN version: 10.0/7
- GPU model and memory: GeForce GTX 1050 15.88 GB RAM

Trying to compile TF 2.0 with Bazel, ends up in a failure.
I am struggling this isssue for quite a while, looked it up online, but havn't found any solution. Several running configuration (with or w/o Cuda, with or w/o creating zip file, etc) eventually leading to the same failure.

My actions:
1. git checkout master (in the TF git repo)
2. bazel clean
3. configure (all defaults except for python path and Cuda)
4. bazel build --config=cuda --define=no_tensorflow_py_deps=true tensorflow:tensorflow_cc.dll

Failure message:
ERROR: C:/users/shahar/git/tensorflow/tensorflow/core/BUILD:2537:1: Executing genrule //tensorflow/core:version_info_gen failed (Exit 5)
LAUNCHER ERROR: Cannot launch process: "C:/Program Files/WindowsApps/PythonSoftwareFoundation.Python.3.7_3.7.1520.0_x64__qbz5n2kfra8p0/python.exe" C:\users\shahar\_bazel_shahar\duchsbgv\execroot\org_tensorflow\bazel-out\x64_windows-opt\bin\tensorflow\tools\git\gen_git_source.zip --generate external/local_config_git/gen/spec.json external/local_config_git/gen/head external/local_config_git/gen/branch_ref bazel-out/x64_windows-opt/bin/tensorflow/core/util/version_info.cc --git_tag_override=
Reason: (error: 5): Access is denied.

What am i doing wrong?

**Comment by nikochiko** [comment]
According to the documentation, building `TensorFlow 2.0` wheel has only been tested with `Bazel 0.26.1`. Refer to this [table](https://www.tensorflow.org/install/source_windows#gpu).

**Comment by gadagashwini** [comment]
@ShaharATterrain, 
Please include the full error log. 
Tensorflow 2.0 supports bazel 0.26.1. Downgrade the bazel version and run configure.py, follow the steps mentioned [here](https://www.tensorflow.org/install/source_windows#build_the_pip_package). Thanks!

**Comment by ShaharATterrain** [comment]
@nikochiko 
@gadagashwini ,
- I have downgraded to bazel 0.26.1, yet the problem remains.
- The link provided explains how to build the **python** API, and i need the **C++** API. Besides that, I was following these instructions to begin with.
- This is the log, from the first ERROR message: 
```
INFO: From Compiling external/grpc/src/cpp/util/time_cc.cc:
cl : Command line warning D9002 : ignoring unknown option '-std=c++14'
ERROR: C:/users/shahar/git/tensorflow/tensorflow/core/BUILD:2537:1: Executing genrule //tensorflow/core:version_info_gen failed (Exit 5): bash.exe failed: error executing command
  cd C:/users/shahar/_bazel_shahar/duchsbgv/execroot/org_tensorflow
  SET CUDA_TOOLKIT_PATH=C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.0
    SET PATH=C:\msys64\usr\bin;C:\msys64\bin;C:\WINDOWS;C:\WINDOWS\System32;C:\WINDOWS\System32\WindowsPowerShell\v1.0;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0\bin;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0\libnvvp;C:\Program Files\AdoptOpenJDK\jdk-13.0.0.33-hotspot\bin;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\iCLS\;C:\Program Files\Intel\Intel(R) Management Engine Components\iCLS\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\mingw-w64\x86_64-8.1.0-posix-seh-rt_v6-rev0\mingw64\bin;C:\Program Files\Boost\bin;C:\Program Files\bazel;C:\Program Files\Git\cmd;C:\Program Files\dotnet\;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\msys64\usr\bin;C:\Users\Shahar\AppData\Local\Microsoft\WindowsApps
    SET PYTHON_BIN_PATH=C:/python/python.exe
    SET PYTHON_LIB_PATH=C:/python/lib/site-packages
    SET RUNFILES_MANIFEST_ONLY=1
    SET TF2_BEHAVIOR=1
    SET TF_CONFIGURE_IOS=0
    SET TF_CUDA_COMPUTE_CAPABILITIES=6.1
    SET TF_NEED_CUDA=1
  C:/msys64/usr/bin/bash.exe -c source external/bazel_tools/tools/genrule/genrule-setup.sh; bazel-out/x64_windows-opt/bin/tensorflow/tools/git/gen_git_source.exe --generate external/local_config_git/gen/spec.json external/local_config_git/gen/head external/local_config_git/gen/branch_ref "bazel-out/x64_windows-opt/bin/tensorflow/core/util/version_info.cc" --git_tag_override=${GIT_TAG_OVERRIDE:-}
Execution platform: @bazel_tools//platforms:host_platform
LAUNCHER ERROR: Cannot launch process: "C:/python/python.exe" C:\users\shahar\_bazel_shahar\duchsbgv\execroot\org_tensorflow\bazel-out\x64_windows-opt\bin\tensorflow\tools\git\gen_git_source.zip --generate external/local_config_git/gen/spec.json external/local_config_git/gen/head external/local_config_git/gen/branch_ref bazel-out/x64_windows-opt/bin/tensorflow/core/util/version_info.cc --git_tag_override=
Reason: (error: 5): Access is denied.

Target //tensorflow:tensorflow_cc.dll failed to build
INFO: Elapsed time: 522.968s, Critical Path: 77.69s
INFO: 633 processes: 633 local.
FAILED: Build did NOT complete successfully
```

If it's better that i extract the error log in any other format, please tell me which.
Thanks.
![Capture1](https://user-images.githubusercontent.com/52371777/68541621-6f9b6500-03aa-11ea-82f2-d8f8cd662aae.PNG)

**Comment by soorajvinod123** [comment]
has anyone fixed this?im having the same problem on bazel 0.26.1...tensorflow 1.15...please help

**Comment by Saduf2019** [comment]
@soorajvinod123 
Please check [this link](https://stackoverflow.com/questions/58753233/building-tensorflow-2-with-bazel-0-29-1-on-windows-10-fails) with same error. Can you please upgrade to later versions of tf and let us know if you still face any issues.
@ShaharATterrain 
Is this still an issue?
