### ISSUE TITLE
Example custom training loop failed when using tf.train.MomentumOptimizer

### ISSUE THREAD

**Issue by yuqcraft** [tensorflow/tensorflow#34078]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): None
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): On google codelab
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: No
- TensorFlow installed from (source or binary): On google codelab
- TensorFlow version (use command below): 1.15.0
- Python version: 3.6.8
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source): 
- CUDA/cuDNN version: Run on cpu.
- GPU model and memory: Run on cpu.

docs/site/en/r1/tutorials/distribute/training_loops.ipynb

I run tensorflow/docs/blob/master/site/en/r1/tutorials/distribute/training_loops.ipynb using google colab and changing the optimizer to tf.train.MomentumOptimizer() and it gives me the following error:

```
InternalError: Invalid variable reference. [[node Momentum/update_0_7/update_dense_1/bias/ResourceApplyMomentum (defined at /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/ops.py:1748) ]]
```

**Describe the expected behavior**
I was expecting the custom training loop can be run using different optimizers.

**Code to reproduce the issue**
Please goto training_loops.ipynb and open google colab from there.

**Comment by gadagashwini** [comment]
@yuqcraft, Please provide the google colab link to expedite the trouble-shooting process. Thanks!

**Comment by yuqcraft** [comment]
Hey @gadagashwini, thanks for the reply. Here's the link:

https://colab.research.google.com/github/tensorflow/docs/blob/master/site/en/r1/tutorials/distribute/training_loops.ipynb

**Comment by gadagashwini** [comment]
@yuqcraft, I changed the line `optimizer = tf.train.MomentumOptimizer('Momentum',0.001)`. It worked as expected. Can you check once and let me know if its still an error. Thanks!

**Comment by yuqcraft** [comment]
@gadagashwini 

When I changed to what you have: tf.train.MomentumOptimizer('Momentum',0.001) and I got this error:

UnimplementedError: Cast string to float is not supported
	 [[node Momentum_2/update_0/update_conv2d_12/kernel/Cast (defined at /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/ops.py:1748) ]]

The codelab default tf version is 1.15.0. According to manual, I changed it to tf.train.MomentumOptimizer(momentum=0.001, learning_rate=1e-3), then I still got the following error:

InternalError: Invalid variable reference.
	 [[node Momentum_3/update_0_7/update_dense_15/bias/ResourceApplyMomentum (defined at /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/ops.py:1748) ]]

**Comment by gadagashwini** [comment]
Issue is replicating on colab with Tf 1.15.0. Thanks!

**Comment by gowthamkpr** [comment]
Please find the github gist [here](https://colab.sandbox.google.com/gist/gowthamkpr/4b65b08bc4676a2d04927a1ec594f6df/copy-of-training_loops.ipynb). Thanks!

**Comment by karmel** [comment]
Thanks, @yuqcraft for the report. This seems to be an issue with the code rather than an issue with the optimizer. Please post to [StackOverflow](http://stackoverflow.com), where there is a larger community to answer such questions.

**Comment by yuqcraft** [comment]
> Please find the github gist [here](https://colab.sandbox.google.com/gist/gowthamkpr/4b65b08bc4676a2d04927a1ec594f6df/copy-of-training_loops.ipynb). Thanks!

Hey @gadagashwini,

When I run the github gist, I still got the same error..

---------------------------------------------------------------------------
InternalError                             Traceback (most recent call last)
/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/client/session.py in _do_call(self, fn, *args)
   1364     try:
-> 1365       return fn(*args)
   1366     except errors.OpError as e:

6 frames
InternalError: Invalid variable reference.
	 [[{{node Momentum/update_0_7/update_dense_1/bias/ResourceApplyMomentum}}]]

During handling of the above exception, another exception occurred:

InternalError                             Traceback (most recent call last)
/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/client/session.py in _do_call(self, fn, *args)
   1382                     '\nsession_config.graph_options.rewrite_options.'
   1383                     'disable_meta_optimizer = True')
-> 1384       raise type(e)(node_def, op, message)
   1385 
   1386   def _extend_graph(self):

InternalError: Invalid variable reference.
	 [[node Momentum/update_0_7/update_dense_1/bias/ResourceApplyMomentum (defined at /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/ops.py:1748) ]]

Original stack trace for 'Momentum/update_0_7/update_dense_1/bias/ResourceApplyMomentum':
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
