### ISSUE TITLE
AttributeError: 'Module' object has no attribute 'app'

### ISSUE THREAD

**Issue by yourntjamdotexe** [tensorflow/tensorflow#34072]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): no
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): MacOS Mojave 10.14.5
- TensorFlow version (use command below): Tensorflow for poets 2
- Python version: 2.7.17

**Describe the current behavior**
I tried to run the training for "tensorflow for poets 2" and it shows me this:
```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Users/fabian/tensorflow-for-poets-2/scripts/retrain.py", line 1326, in <module>
    tf.app.run(main=main, argv=[sys.argv[0]] + unparsed)
AttributeError: 'module' object has no attribute 'app'
```

I'm not so familiar with coding, but is there a way to resolve this problem?
Thanks

**Comment by aselle** [comment]
tf.app is a v1 feature. Use tf.compat.v1.app instead.
