### ISSUE TITLE
Keras named inputs lost with SavedModel format

### ISSUE THREAD

**Issue by louisjc** [tensorflow/tensorflow#34070]
**System information**
- Have I written custom code: yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): **Google Colab, TF 2.0**

**Describe the current behavior**
If I define a Keras model with named inputs (`Input(name="x_embedding")`), I can use a Dict as input with the original model or after saving to h5, but not with the new SavedModel format: The name of my input layer is changed from `x_embedding` to `input_1`.

**Describe the expected behavior**
The model loaded from SavedModel should keep the named inputs.

**Code to reproduce the issue**
https://colab.research.google.com/drive/19ICXHeL4tzAN9z1LCi-3Su8l5X2_NhxM

```python
try:
  %tensorflow_version 2.x
except Exception:
  pass
  
import tensorflow as tf
import numpy as np
from tensorflow.keras.layers import Input, Dense
from tensorflow.keras.models import Model
from tensorflow.keras.models import load_model

input_seq = Input(shape=(1,), name="x_embedding")
model = Model(inputs=input_seq, outputs=input_seq)
model.compile(optimizer="adam", loss="sparse_categorical_crossentropy")

x = {"x_embedding": np.array([0.1] * 100)}
y = np.array([0] * 100)

model.fit(x,y)

# Works with original model
res = model.evaluate(x,y)
print("model.evaluate =", res)

# Works with h5 model
model.save("my_h5Model.h5", save_format="h5")
model2 = load_model("my_h5Model.h5")
res = model2.evaluate(x,y)
print("model2.evaluate =", res)

# Doesn't work with SavedModel format
model.save("my_SavedModel", save_format="tf")
model3 = load_model("my_SavedModel")
res = model3.evaluate(x,y)
print("model3.evaluate =", res)

# Work with SavedModel format if I rename x_embedding -> input_1
x2 = {"input_1": np.array([0.1] * 100)}
res = model3.evaluate(x2,y)
print("model3.evaluate =", res)
```
**Other info / logs**
`ValueError: No data provided for "input_1". Need data for each key in: ['input_1']`

**Comment by louisjc** [comment]
Still an issue with `tf-nightly==2.1.0.dev20191126`

**Comment by goldiegadde** [comment]
This is fixed with the latest tf-nightly: here is an updated [gist](https://colab.research.google.com/drive/19ICXHeL4tzAN9z1LCi-3Su8l5X2_NhxM?usp=sharing)

**Comment by louisjc** [comment]
Great, thanks @goldiegadde !
