### ISSUE TITLE
[TF 2.0] Add batched gradient function to GradientTape

### ISSUE THREAD

**Issue by n-gao** [tensorflow/tensorflow#34087]
**System information**
- TensorFlow version (you are using): 2.0.0

**Describe the feature and the current behavior/state.**
There should be a feature for batched gradient computation in GradientTape similar to batched_jacobian.

**Will this change the current api? How?**
`GradientTape.batched_gradient` would exist.

**Who will benefit with this feature?**
If someone wants to compute the second derivative of an output w.r.t. the input. Here is an example:
Let's assume `x=(x_1, x_2, x_3)` and we have some function (network) which gives us a scalar output for every x `f(x)=y`. Computing the second derivative of the `f(x)` w.r.t. `x_i` `(d^2f(x)/dx_i^2)` involves either a gradient computation + jacobian computation or a gradient computation + loop:
1. solution with jacobian:
```
with tf.GradientTape(True) as g:
  g.watch(x)
  with tf.GradientTape() as gg:
    gg.watch(x)
    y = f(x)
  dy_dx = gg.gradient(y, x)
d2y_dx2 = g.jacobian(y, x) # here some filtering is requires to get only the diagonal elements
```
2. solution with loop of gradients:
```
with tf.GradientTape(True) as g:
  x_i = [x[i] for i in range(len(x))]
  [g.watch(_x) for _x in x_i]
  x = tf.stack(x_i, 0)
  with tf.GradientTape() as gg:
    gg.watch(x)
    y = f(x)
  dy_dx = gg.gradient(y, x)
  dy_dx_i = [dy_dx[i] for i in range(len(dy_dx))]
d2y_dx2 = tf.stack([g.gradient(grad, _x) for grad, _x in zip(dy_dx_i, x_i)])
```

The first solution is expensive due to the jacobian computation and for the second one, one has to split up the tensor before and after and loop over gradient computation.

**Comment by rmothukuru** [comment]
@n-gao,
Sorry for the delayed response. Can you please let us know if this is [the functionality](https://www.tensorflow.org/guide/advanced_autodiff#higher-order_gradients) that you are looking for? Thanks!
