### ISSUE TITLE
How To Image Retraining : ImportError: No module named mock

### ISSUE THREAD

**Issue by wfs** [tensorflow/tensorflow#3408]
### Environment info
Operating System:
cat /proc/version
Linux version 4.4.0-31-generic (buildd@lgw01-16) (gcc version 5.3.1 20160413 (Ubuntu 5.3.1-14ubuntu2.1) ) #50-Ubuntu SMP Wed Jul 13 00:07:12 UTC 2016

1. Which pip package you installed.
2. The output from `python -c "import tensorflow; print(tensorflow.__version__)"`.
0.9.0

### Steps to reproduce
1. Following this tutorial : https://www.tensorflow.org/versions/r0.9/how_tos/image_retraining/index.html
2. Executing this command after having completed the flower images download : (tensorflow) paddlescoot@paddlescoot-Satellite-P870:~/tensorflow_source/tensorflow$ bazel build tensorflow/examples/image_retraining:retrain
3. See terminal output text [file here for details of error.](https://drive.google.com/open?id=0B0Oci8Q1NdEuUDJ4R2FHTkYtXzQ)

### What have you tried?
1. Searched for similar issues.

**Comment by concretevitamin** [comment]
Does `pip install mock` help?  We started requiring this package on this [commit](https://github.com/tensorflow/tensorflow/commit/f72242bfce6f3976d433d051f6316a135d05b811).

**Comment by dmansfield** [comment]
Just encountered this when building TF Serving with TF submodule updated to latest master. `pip install mock` got past it.

**Comment by GeorgianaPetria** [comment]
I had this issue when using an aws instance that had tensorflow installed.
I tried installing mock, but it didn't make any change.
Finally, it turned out the installed tensorflow version was quite old and the issue was related to this https://github.com/tensorflow/serving/issues/139

I just had to upgrade tensorflow and it worked: https://www.tensorflow.org/get_started/os_setup

**Comment by shanxiongfei** [comment]
I have the same problem, who can help me?wangjingsideMacBook-Pro:tensorflow ginthva$ bazel-bin/tensorflow/examples/image_retraining/retrain 
Traceback (most recent call last):
  File "/Users/ginthva/tensorflow/bazel-bin/tensorflow/examples/image_retraining/retrain.runfiles/org_tensorflow/tensorflow/examples/image_retraining/retrain.py", line 79, in <module>
    import tensorflow as tf
  File "/Users/ginthva/tensorflow/bazel-bin/tensorflow/examples/image_retraining/retrain.runfiles/org_tensorflow/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "/Users/ginthva/tensorflow/bazel-bin/tensorflow/examples/image_retraining/retrain.runfiles/org_tensorflow/tensorflow/python/__init__.py", line 124, in <module>
    from tensorflow.python.platform import test
  File "/Users/ginthva/tensorflow/bazel-bin/tensorflow/examples/image_retraining/retrain.runfiles/org_tensorflow/tensorflow/python/platform/test.py", line 50, in <module>
    import mock                # pylint: disable=g-import-not-at-top,unused-import
ImportError: No module named mock

**Comment by xtr33me** [comment]
@shanxiongfei Were you ever able to find a solution? I am seeing the same thing in a docker container on macbook pro Sierra and not having any luck getting past it yet.

**Comment by lijiansong** [comment]
you can remove mock by the following command:
```
$ sudo rm -rf /usr/local/lib/python2.7/dist-packages/mock
$ sodo rm -rf /usr/local/lib/python2.7/dist-packages/mock-2.0.0.dist-info
```
then type the following command to install mock
```
$ sudo pip install --upgrade mock
```

**Comment by junlulocky** [comment]
hey, my solution:
for windows: 
sudo /bin/env pip uninstall mock  ## important
sudo /bin/env python  pip install mock

for MAC
sudo /usr/bin/env pip uninstall mock  ## important
sudo /usr/bin/env python  pip install mock

checkout this link for why use '/usr/bin/env' beforehand: http://www.junlulocky.com/blog/pythontricks

**Comment by lechatthecat** [comment]
maybe try both:
$ pip3 install mock
$ pip2 install mock
