### ISSUE TITLE
Can't find tensorflow.examples.tutorial

### ISSUE THREAD

**Issue by wady101** [tensorflow/tensorflow#34083]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): None
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04.3 LTS
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: None
- TensorFlow installed from (source or binary): Source
- TensorFlow version (use command below): v1.12.1-17556-g63c45aacf3 2.0.0
- Python version: Python 3.7.4
- Bazel version (if compiling from source):0.27.1
- GCC/Compiler version (if compiling from source):7.4.0
- CUDA/cuDNN version: V10.1.243
- GPU model and memory: GP107GL [Quadro P1000]  -- 4031MiB 

**Describe the current behavior**
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError:  No module named 'tensorflow.examples'
```
As the error sugests, can't find the module. Am I missing something while generating the wheel package from bazel? 

**Describe the expected behavior**
Is there in the source code repo, hence should work. No monkey-fixes please. I have tried local copying the directory, but then some other tensorflow module is missing (tensorflow.contrib and goes on).  

**Code to reproduce the issue**
`python -c 'from tensorflow.examples.tutorials import input_data'`

**Other info / logs**
`bazel build --verbose_failures  --config=monolithic //tensorflow/tools/pip_package:build_pip_package`
Command I used to create the wheel package from tensorflow source.

**Comment by nikochiko** [comment]
Yes. You should refer to this [table](https://www.tensorflow.org/install/source_windows#gpu) and create wheel package with tested configuration.

**Comment by wady101** [comment]
@nikochiko, I tried bezel 0.26.1 before this. It was stuck stuck at the same issue.

**Comment by oanush** [comment]
Issue replicating for TF2.0 version.Kindly find the [gist](https://colab.sandbox.google.com/gist/oanush/4a0e6b790a2eeddfbb0578f00ddb44a3/34083.ipynb) of colab.Thanks!

**Comment by ymodak** [comment]
I believe there's a typo in your import. 
Can you try with;
```import tensorflow.examples.tutorials```

**Comment by wady101** [comment]
Thanks @ymodak . Didn't see that :<

**Comment by wady101** [comment]
@ymodak I apologize. It still doesn't work. Strangely, it was working in the colab link yesterday, but not today.  Can you give this a try? I tried it on the local build (mentioned in the issue) I was using today, and it still gives me the same error.
I have updated the issue.

**Comment by Leslie-Fang** [comment]
@wady101 you need to set the PYTHONPATH
`
export PYTHONPATH=$tensorflow_examples_root
`

**Comment by wady101** [comment]
@Leslie-Fang sorry, what is $tensorflow_examples_root? Couldn't find any mention of env variable online.

 Also should I set this before building from source or after?

**Comment by Leslie-Fang** [comment]
@wady101 I suspect it's because of all tensorflow version. 
Did you write your benchmark or models by yourself?

**Comment by wady101** [comment]
No @Leslie-Fang , I am trying to get a piece of code to run https://github.com/layog/Accurate-Binary-Convolution-Network

Still, what do I keep PYTHONPATH? Can you echo it on your pc and show it here? Thanks

**Comment by Leslie-Fang** [comment]
@wady101 Sorry, I mis-read your error message.
I thought it was tensorflow_examples couldn't be find.

I suspect your error message relates with the tf version as you can see  https://github.com/layog/Accurate-Binary-Convolution-Network is using TF1.4(tensorflow-gpu==1.4.1)

**Comment by wady101** [comment]
@Leslie-Fang No worries. Read the issue description, I have given all the necessary details.

**Comment by ymodak** [comment]
TF 1.4.1 is obsolete. Please install latest version of TF and import again.
Current colab host TF 1.15.0 version an can successfully import.
```from tensorflow.examples.tutorials.mnist import input_data```

**Comment by wady101** [comment]
@ymodak I have tried all three versions - 1.4.1, 1.12.1 and 2.0.0 - all three give me the same error (Using both "building from source" and "pip"). 
The two things I ask for is ; 
> Is there a flag being missed in the bezel command I have used to build tensorflow (see ISSUE)? Do I have to export some path to PYTHONPATH as mentioned by @Leslie-Fang ? 
> If not, is there a workaround which will solve my problem? 
Repository I am trying to run - https://github.com/layog/Accurate-Binary-Convolution-Network/blob/master/ABC-layer-inference-support.ipynb [5th cell in Jupyter book gives me error] 
Thanks

**Comment by oscar7692** [comment]
I'm using tensorflow-cpu==2.1.0 and I had the same issue 

`ModuleNotFoundError:  No module named 'tensorflow.examples'`

I solve this downloading manually the directory called "tutorials" from tensorflow repo
[https://github.com/tensorflow/tensorflow/tree/master/tensorflow/examples/tutorials](url)

and placed it in my virtual env directory 
`myenv\Lib\site-packages\tensorflow_core\examples\`

after that it works fine

**Comment by PiyushChawla** [comment]
Thanks @oscar7692 worked for me as well that way. life saver.
