### ISSUE TITLE
[Codelab] Update digit classifier Android app to target API level 29

### ISSUE THREAD

**Issue by Kbhredsox** [tensorflow/tensorflow#34084]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- Android Studio version: 3.5

**Describe the problem**
The Android app package available from https://codelabs.developers.google.com/codelabs/digit-classifier-tflite/index.html?index=..%2F..index#2 has a targetSdkVersion of "28". This should be updated to "29".

**Provide the exact sequence of commands / steps that you executed before running into the problem**
1. Download codelab ZIP file
2. Open the Android Studio project: lite/codelabs/digit_classifier/android/start/
3. View the project's app/build.gradle file.

**Comment by jdduke** [comment]
We're not taking advantage of any API 29 features, and 28 is the standard targetSdkVersion for the Play Store.
