### ISSUE TITLE
Cannot load saved model fitted via csv dataset

### ISSUE THREAD

**Issue by EdwarDDay** [tensorflow/tensorflow#34096]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): MacOS 10.14.6
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.0.0
- Python version: 3.7
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Describe the current behavior**
I load data from a csv file to create the dataset for fitting my model. After saving the model, I can't load it again. I get the following error message:
`ValueError: ('We expected a dictionary here. Instead we got: ', <tf.Tensor 'Placeholder:0' shape=(None,) dtype=float32>)`

**Describe the expected behavior**
The program should load the model.

**Code to reproduce the issue**
```python
import tensorflow as tf
from tensorflow import keras

dataset: tf.data.Dataset = tf.data.experimental.make_csv_dataset('xor.csv', 4, label_name='result')
columns = [tf.feature_column.numeric_column('a'), tf.feature_column.numeric_column('b')]
input_column = keras.layers.DenseFeatures(columns)
layers = [input_column,
          keras.layers.Dense(4, activation='relu'),
          keras.layers.Dense(2)]
model = keras.Sequential(layers)
model.compile(loss='mean_squared_error', optimizer='adam', metrics=['binary_accuracy'])
model.fit(dataset, steps_per_epoch=4, epochs=2000)
keras.models.save_model(model, 'test_model.h5')
# model.save('test_model.h5')
model = keras.models.load_model('test_model.h5')
```
xor.csv:
```
a,b,result
0,0,0
0,1,1
1,0,1
1,1,0
```

**Other info / logs**
```
Traceback (most recent call last):
...
  File "main.py", line 76, in main
    model = keras.models.load_model('test_model.h5')
  File "/.../lib/python3.7/site-packages/tensorflow_core/python/keras/saving/save.py", line 146, in load_model
    return hdf5_format.load_model_from_hdf5(filepath, custom_objects, compile)
  File "/.../lib/python3.7/site-packages/tensorflow_core/python/keras/saving/hdf5_format.py", line 168, in load_model_from_hdf5
    custom_objects=custom_objects)
  File "/.../lib/python3.7/site-packages/tensorflow_core/python/keras/saving/model_config.py", line 55, in model_from_config
    return deserialize(config, custom_objects=custom_objects)
  File "/.../lib/python3.7/site-packages/tensorflow_core/python/keras/layers/serialization.py", line 106, in deserialize
    printable_module_name='layer')
  File "/.../lib/python3.7/site-packages/tensorflow_core/python/keras/utils/generic_utils.py", line 303, in deserialize_keras_object
    list(custom_objects.items())))
  File "/.../lib/python3.7/site-packages/tensorflow_core/python/keras/engine/sequential.py", line 380, in from_config
    model.build(build_input_shape)
  File "/.../lib/python3.7/site-packages/tensorflow_core/python/keras/engine/sequential.py", line 260, in build
    super(Sequential, self).build(input_shape)
  File "/.../lib/python3.7/site-packages/tensorflow_core/python/keras/engine/network.py", line 682, in build
    self.call(x, **kwargs)
  File "/.../lib/python3.7/site-packages/tensorflow_core/python/keras/engine/sequential.py", line 281, in call
    outputs = layer(inputs, **kwargs)
  File "/.../lib/python3.7/site-packages/tensorflow_core/python/keras/engine/base_layer.py", line 778, in __call__
    outputs = call_fn(cast_inputs, *args, **kwargs)
  File "/.../lib/python3.7/site-packages/tensorflow_core/python/autograph/impl/api.py", line 237, in wrapper
    raise e.ag_error_metadata.to_exception(e)
ValueError: in converted code:
    /.../lib/python3.7/site-packages/tensorflow_core/python/feature_column/dense_features.py:129 call
        features)
    ValueError: ('We expected a dictionary here. Instead we got: ', <tf.Tensor 'Placeholder:0' shape=(None,) dtype=float32>)
```

**Comment by ymodak** [comment]
in TF 2.X save format is TensorFlow Model format (tf) by default.
Can you please try using setting ```save_format='h5' ``` argument in ```tf.keras.models.save_model``` and try again?

**Comment by EdwarDDay** [comment]
> In TF 2.X save format is TensorFlow Model format (tf) by default.
> Can you please try using setting `save_format='h5' ` argument in [`tf.keras.models.save_model`](https://www.tensorflow.org/api_docs/python/tf/keras/models/save_model?hl=vi#arguments) and try again?

I tried it and the same error was thrown again.

**Comment by EdwarDDay** [comment]
Is there a workaround for this bug?

**Comment by bm777** [comment]
> Is there a workaround for this bug?


Hello **@EdwarDDay**,  if you are using **TF2.x**, it will work.

**save with:** 
tf.keras.models.save_model(model, "path/model") # without extension .h5, only string of your model

**and load with:**
new_model = tf.keras.models.load_model("path/model") # as you have saved in first time, without extension again.

**Comment by adamblalockaaa** [comment]
> > Is there a workaround for this bug?
> 
> Hello **@EdwarDDay**, if you are using **TF2.x**, it will work.
> 
> **save with:**
> tf.keras.models.save_model(model, "path/model") # without extension .h5, only string of your model
> 
> **and load with:**
> new_model = tf.keras.models.load_model("path/model") # as you have saved in first time, without extension again.
> 
> like this ...
> ![model-keras](https://user-images.githubusercontent.com/29865600/70857116-49a53b00-1ee9-11ea-9021-bc5b264bf062.png)
> ![directory](https://user-images.githubusercontent.com/29865600/70857131-9721a800-1ee9-11ea-8a15-b714d4ba1f66.png)

This solution does not work for my situation because for my project I need to save a single h5 file and not a whole directory, is there another way to fix this issue?

**Comment by ymodak** [comment]
Tried https://www.tensorflow.org/tutorials/load_data/pandas_dataframe example with saving/loading model in tf/h5 format and works correctly. Please test with latest version of TF and try again. Others who are experiencing similar issue please raise a new issue thread. Thanks!
