### ISSUE TITLE
Failed to run the unit test of bonus_tests

### ISSUE THREAD

**Issue by Leslie-Fang** [tensorflow/tensorflow#34091]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Centos7.6
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below): 2.0 master branch, commit-id:af019188adc704569b7cce51e50eba489af1a725 
- Python version: 3.6
- Bazel version (if compiling from source): 0.27.1
- GCC/Compiler version (if compiling from source): 6.3
- CUDA/cuDNN version:
- GPU model and memory:

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
After build from source code:
```
bazel --output_user_root=$build_dir build --config=v2 //tensorflow/tools/pip_package:build_pip_package 
```

I run the unit test:
```
bazel --output_user_root=$build_dir test //tensorflow/core/kernels:bonus_tests
```
It failed with the error message:

_ERROR: no such target '//tensorflow/core/kernels:bonus_tests': target 'bonus_tests' not declared in package 'tensorflow/core/kernels' (did you mean 'loss_test'?) defined by /home/lesliefang/debug_failrunbonus_tests/tensorflow/tensorflow/core/kernels/BUILD
INFO: Elapsed time: 0.382s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
FAILED: Build did NOT complete successfully (0 packages loaded)_

**Describe the expected behavior**
The unit test should run successfully.

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.
As the description above.

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by Leslie-Fang** [comment]
If I change this line:https://github.com/tensorflow/tensorflow/blob/bfce5bae88e01c080c8cc9224b439c4dd26c506b/tensorflow/core/kernels/BUILD#L3163-L3193
tf_cc_tests to tf_cc_test
It can find the unit test case and show pass result.

**Comment by gowthamkpr** [comment]
As you can see [here](https://github.com/tensorflow/tensorflow/blob/7a07f274d65bed12b91b6c6dbe4987a6e1649429/tensorflow/tensorflow.bzl#L1169) tf_cc_tests perform tf_cc_test form multiple ops(components)

**Source**
```
# Create a cc_test for each of the tensorflow tests listed in "tests"
def tf_cc_tests(
        srcs,
        deps,
        name = "",
        linkstatic = 0,
        tags = [],
        size = "medium",
        args = None,
        linkopts = [],
        kernels = []):
    for src in srcs:
        tf_cc_test(
            name = src_to_test_name(src),
            size = size,
            srcs = [src],
            args = args,
            kernels = kernels,
            linkopts = linkopts,
            linkstatic = linkstatic,
            tags = tags,
            deps = deps,
        )
```

**Example**
```
tf_cc_tests(
    name = "bonus_tests",
    srcs = [
        "adjust_contrast_op_test.cc",
        "colorspace_op_test.cc",
        "crop_and_resize_op_test.cc",
        "non_max_suppression_op_test.cc",
        "resize_area_op_test.cc",
        "resize_bicubic_op_test.cc",
        "resize_nearest_neighbor_op_test.cc",
        "scale_and_translate_op_test.cc",
    ],
    linkopts = select({
        "//tensorflow:macos": ["-headerpad_max_install_names"],
        "//conditions:default": [],
    }),
    deps = [
        ":image",
        ":ops_testutil",
        ":ops_util",
        ":sampling_kernels",
        "//tensorflow/core:core_cpu",
        "//tensorflow/core:framework",
        "//tensorflow/core:lib",
        "//tensorflow/core:lib_internal",
        "//tensorflow/core:protos_all_cc",
        "//tensorflow/core:test",
        "//tensorflow/core:test_main",
        "//tensorflow/core:testlib",
    ],
)
```

Let me know if the above explanation helps. Thanks!

**Comment by Leslie-Fang** [comment]
@gowthamkpr Thanks for the explanation. I understand the definition of tf_cc_tests. 
The question is why I run：
`
bazel --output_user_root=$build_dir test //tensorflow/core/kernels:bonus_tests
`
which throws the error:
_ERROR: no such target '//tensorflow/core/kernels:bonus_tests': target 'bonus_tests' not declared in package 'tensorflow/core/kernels' (did you mean 'loss_test'?) defined by /home/lesliefang/debug_failrunbonus_tests/tensorflow/tensorflow/core/kernels/BUILD
INFO: Elapsed time: 0.382s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
FAILED: Build did NOT complete successfully (0 packages loaded)_

**Comment by gowthamkpr** [comment]
`ERROR: no such target '//tensorflow/core/kernels:bonus_tests': target 'bonus_tests' not declared in package 'tensorflow/core/kernels' (did you mean 'loss_test'?) defined by /home/lesliefang/debug_failrunbonus_tests/tensorflow/tensorflow/core/kernels/BUILD`

Can you take a look at the source of in this path in your system and let me know if 'bonus_tests' is declared or no?

**Comment by Leslie-Fang** [comment]
@gowthamkpr Yes, 'bonus_tests' is defined in the file $tensorflow_root/tensorflow/core/kernels/BUILD
I am using master branch, commit-id: af019188adc704569b7cce51e50eba489af1a725
You can help to reproduce this issue if possible.

**Comment by akuegel** [comment]
The name of the tf_cc_tests rule is never used to create an executable. If you check the definition, it creates executable tests for each of the entries in srcs (their name derived from name of their source file). So you can for example run:
bazel --output_user_root=$build_dir test //tensorflow/core/kernels:adjust_contrast_op_test
(this is the first of the created tests from the bonus_tests target).

**Comment by Leslie-Fang** [comment]
@akuegel Thanks a lot and It explains clearly.
