### ISSUE TITLE
Forking TensorFlow after You Already Pip Installed

### ISSUE THREAD

**Issue by LeavesBreathe** [tensorflow/tensorflow#341]
Hey TF, love your code.

I recently forked and cloned TF because I wanted to add some new features to it. 

However, previously I pip installed it, so my question is:

How do I change it so that when I call in `import TensorFlow`, it comes from my specified directory (cloned dir) and not the one in `dist-packages`? 

Do I need to re-install TensorFlow? Or can I just simply use the scripts found in my TensorFlow clone?

Thanks!

**Comment by vrv** [comment]
I would probably pip uninstall tensorflow's binary package if you're building from source, just to avoid any problems.  the binary install is for those who just want to use the library as is without modification.

**Comment by MarkDaoust** [comment]
>How do I change it so that when I call import TensorFlow, it comes from my specified directory (cloned dir) and not the one in dist-packages? 

I think that's the more important part of the question.

Often you can just `pip install -e ...` but I don't see any way to install tensorflow in an "editable" mode so you can easily try out changes, without rebuilding/reinstalling the wheel.

Am I missing something? Is there a simple way?

**Comment by ebrevdo** [comment]
You can use this pip install option if you want to modify the python code
live. Any changes to the c++ build or dependencies requires a recompile.

**Comment by MarkDaoust** [comment]
Thanks @ebrevdo , but I don't see it.

There's no `setup.py` in the root directory

If I take the `setup.py` from `tensorflow/tools/pip_package` and run a `pip install -e` I still can't get past the `ImportError: Error importing tensorflow: you should not try to import
  tensorflow from its source directory...`

Does it work for you? Could you be more specific on how to do it?

**Comment by LeavesBreathe** [comment]
Thank you for suggesting to pip uninstall it. I can do that, but I thought it wouldn't be favorable to do so. I'll give a try and see if it works! Thanks!
