### ISSUE TITLE
many proto files lack go_package

### ISSUE THREAD

**Issue by aronatkins** [tensorflow/tensorflow#34100]
**System information**
- OS Platform and Distribution: Linux Ubuntu 16.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): source
- TensorFlow version: 1.15.0
- Python version: N/A
- Installed using virtualenv? pip? conda?: release .tar.gz
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

**Describe the problem**

As noted in https://github.com/golang/protobuf/issues/984, a number of `*.proto` files lack `go_version` statements. 

The commands:

```bash
protoc \
       -I./github.com/tensorflow/tensorflow \
       --go_out=plugins=grpc:./ \
       ./github.com/tensorflow/tensorflow/tensorflow/core/framework/*.proto
protoc \
       -I./github.com/tensorflow/tensorflow \
       --go_out=plugins=grpc:./ \
       ./github.com/tensorflow/tensorflow/tensorflow/core/protobuf/{saver,saved_model,struct,trackable_object_graph,saved_object_graph,meta_graph}.proto
```

give the error:

```bash
2019/11/07 14:43:01 protoc-gen-go: error:inconsistent package import paths: "github.com/tensorflow/tensorflow/tensorflow/go/core/protobuf", "tensorflow/core/protobuf"
```

I have worked around this locally by adding `go_package` statements to the following files so everything is emitted into `github.com/tensorflow/tensorflow/tensorflow/go/core`:

* tensorflow/core/protobuf/saved_object_graph.proto
* tensorflow/core/protobuf/struct.proto
* tensorflow/core/protobuf/trackable_object_graph.proto

```
option go_package = "github.com/tensorflow/tensorflow/tensorflow/go/core/protobuf";
```

A number of other `*.proto` files also appear to lack `go_package`; not sure if they all need update:

```
$ grep -L go_package $(find tensorflow/core -name "*.proto")
tensorflow/core/kernels/boosted_trees/boosted_trees.proto
tensorflow/core/util/test_log.proto
tensorflow/core/util/memmapped_file_system.proto
tensorflow/core/util/saved_tensor_slice.proto
tensorflow/core/util/example_proto_fast_parsing_test.proto
tensorflow/core/util/event.proto
tensorflow/core/grappler/costs/op_performance_data.proto
tensorflow/core/profiler/tfprof_options.proto
tensorflow/core/profiler/tfprof_output.proto
tensorflow/core/profiler/profiler_analysis.proto
tensorflow/core/profiler/tfprof_log.proto
tensorflow/core/profiler/op_profile.proto
tensorflow/core/profiler/profiler_service.proto
tensorflow/core/profiler/profile.proto
tensorflow/core/protobuf/trace_events.proto
tensorflow/core/protobuf/conv_autotuning.proto
tensorflow/core/protobuf/autotuning.proto
tensorflow/core/protobuf/graph_debug_info.proto
tensorflow/core/protobuf/eager_service.proto
tensorflow/core/protobuf/replay_log.proto
tensorflow/core/protobuf/transport_options.proto
tensorflow/core/protobuf/tpu/compilation_result.proto
tensorflow/core/protobuf/tpu/optimization_parameters.proto
tensorflow/core/protobuf/tpu/tpu_embedding_output_layout.proto
tensorflow/core/protobuf/tpu/topology.proto
tensorflow/core/protobuf/tpu/tpu_embedding_configuration.proto
tensorflow/core/protobuf/tpu/dynamic_padding.proto
tensorflow/core/protobuf/data/experimental/snapshot.proto
tensorflow/core/debug/debug_service.proto
tensorflow/core/debug/debugger_event_metadata.proto
```

Closely related to https://github.com/tensorflow/tensorflow/issues/16282, https://github.com/tensorflow/tensorflow/issues/30093 and a few other issues/PRs that attempt to incrementally add `go_package` statements.

**Comment by ravikyram** [comment]
@aronatkins 

Can you please elaborate about the issue & the context. It helps us in localizing the issue faster. Thanks!

**Comment by aronatkins** [comment]
@ravikyram - What specific additional information do you need?

We were trying to compile the protocol buffer definitions into Go source/packages using `protoc`. Unfortunately, not every `*.proto` file contains a `go_package` declaration. As a result, `protoc` code-generates Go files in two different directory hierarchies.

I've enumerated the three `*.proto` files that I needed to hand-patch and also found all the `*.proto` files without `go_package` in case that helps.

We use the protocol buffer definitions to load saved models from disk and perform prediction requests. 

See golang/protobuf#984, where the protobuf folks indicate that the missing `go_package` declarations are probably an oversight of the TF project.

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.
