### ISSUE TITLE
Download link for PoseNet tflite doesn't work

### ISSUE THREAD

**Issue by likwifi** [tensorflow/tensorflow#34102]
Pose Net download link from https://www.tensorflow.org/lite/models/pose_estimation/overview
doesn't work.

https://storage.googleapis.com/download.tensorflow.org/models/tflite/posenet_mobilenet_v1_100_257x257_multi_kpt_stripped.tflite

**Comment by likwifi** [comment]
I was able to download it Firefox but same link doesn't work on chrome.

**Comment by gowthamkpr** [comment]
Was able to download it on chrome. Try uninstalling and reinstalling your browser 
![image](https://user-images.githubusercontent.com/47574994/68514763-83708b00-0233-11ea-981f-5eaf521602a4.png). Thanks!
