### ISSUE TITLE
Histogramme

### ISSUE THREAD

**Issue by lethienhoa** [tensorflow/tensorflow#3410]
Hi, 
This is not a problem but rather a question about the quantile "histogram". I see that Tensorflow can plot almost everything (W, dW, b, db,...).

But what is in it actually ? Knowing that b is a vector, W is a matrix. I assumed that Tensorflow has calculated the norm (L2 et Frobenius) of these tensors to view their evolution through time, right ?

Of course, a probability density function is more than welcome than just a quantile region to treat multimodal, but then, how we can view large multidimensional variables in just a unique graphic ?

Many thanks,
Hoa

**Comment by concretevitamin** [comment]
Sorry, I don't understand the issue.

Seeing this does not sound like a bug nor a feature request, please redirect the discussion to the [mailing list](https://groups.google.com/a/tensorflow.org/d/forum/discuss) or to StackOverflow.
