### ISSUE TITLE
Run Time series forecasting Tutorials , the warning raised. W tensorflow/core/grappler/optimizers/implementation_selector.cc:310] Skipping optimization due to error while loading function libraries

### ISSUE THREAD

**Issue by chris881** [tensorflow/tensorflow#34115]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
I try to run Time series forecasting Tutorials . the code was exactly same as the github shows.
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
Win10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
NONE
- TensorFlow installed from (source or binary):
source 
- TensorFlow version (use command below):
Tensorflow 2.0 stable version
- Python version:
py 3.7
- Bazel version (if compiling from source):
NONE
- GCC/Compiler version (if compiling from source):
NONE
- CUDA/cuDNN version:
NONE
- GPU model and memory:
NONE
You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
when I try to run the Time series forecasting Tutorials , the warning raised .
I don
2019-11-09 11:05:44.540408: W tensorflow/core/grappler/optimizers/implementation_selector.cc:310] Skipping optimization due to error while loading function libraries: Invalid argument: Functions '__inference___backward_standard_lstm_2511_2996' and '__inference___backward_standard_lstm_2511_2996_specialized_for_StatefulPartitionedCall_at___inference_distributed_function_3085' both implement 'lstm_b5a954a4-22ab-43b7-aa70-42d55d0dde61' but their signatures do not match.
**Describe the expected behavior**
how to solve this warning ?
**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.
the same as Tutorial. https://tensorflow.google.cn/tutorials/structured_data/time_series
**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by gadagashwini** [comment]
@chris881, I tried the tutorial on colab. It executed as expected.
Please take a look at the colab [gist](https://colab.sandbox.google.com/gist/gadagashwini/441c50ce70cd7bc2afe5eb05b0e3bc1c/untitled250.ipynb).Thanks!

**Comment by chris881** [comment]
thanks a lot . i will double check the code.
