### ISSUE TITLE
Building error: ptxas fatal   : Internal error: writing file ERROR: /disk1/caina2/tensorflow/tensorflow/core/kernels/BUILD:1509:1: output 'tensorflow/core/kernels/_objs/depth_space_ops_gpu/tensorflow/core/kernels/depthtospace_op_gpu.cu.pic.o' was not created.

### ISSUE THREAD

**Issue by annisamansa** [tensorflow/tensorflow#3411]
when build_pip_package, ending with 

ptxas fatal   : Internal error: writing file
ERROR: /disk1/caina2/tensorflow/tensorflow/core/kernels/BUILD:1509:1: output 'tensorflow/core/kernels/_objs/depth_space_ops_gpu/tensorflow/core/kernels/depthtospace_op_gpu.cu.pic.o' was not created.

Does anyone have the same problem?

### Environment info
Operating System:
centos 6.2
glibc 2.23
Installed version of CUDA and cuDNN: 
cuda 7.5
libcudnn.so.5.0.4
bazel-0.3.0
install from source

### What have you tried?
/disk1/caina2/bazel-0.3.0/output/bazel build -c opt --config=cuda --verbose_failures //tensorflow/tools/pip_package:build_pip_package

### Logs or other output that would be helpful

INFO: From Compiling tensorflow/core/kernels/depthtospace_op_gpu.cu.cc:
nvcc warning : option '--relaxed-constexpr' has been deprecated and replaced by option '--expt-relaxed-constexpr'.
In file included from third_party/gpus/cuda/include/host_config.h:161:0,
                 from third_party/gpus/cuda/include/cuda_runtime.h:76,
                 from <command-line>:0:
/usr/include/features.h:331:4: warning: #warning _FORTIFY_SOURCE requires compiling with optimization (-O) [-Wcpp]
 #  warning _FORTIFY_SOURCE requires compiling with optimization (-O)
    ^
In file included from third_party/gpus/cuda/include/host_config.h:161:0,
                 from third_party/gpus/cuda/include/cuda_runtime.h:76,
                 from <command-line>:0:
/usr/include/features.h:331:4: warning: #warning _FORTIFY_SOURCE requires compiling with optimization (-O) [-Wcpp]
 #  warning _FORTIFY_SOURCE requires compiling with optimization (-O)
    ^
In file included from third_party/gpus/cuda/include/host_config.h:161:0,
                 from third_party/gpus/cuda/include/cuda_runtime.h:76,
                 from <command-line>:0:
/usr/include/features.h:331:4: warning: #warning _FORTIFY_SOURCE requires compiling with optimization (-O) [-Wcpp]
 #  warning _FORTIFY_SOURCE requires compiling with optimization (-O)
    ^
nvcc warning : option '--relaxed-constexpr' has been deprecated and replaced by option '--expt-relaxed-constexpr'.
ptxas fatal   : Internal error: writing file
ERROR: /disk1/caina2/tensorflow/tensorflow/core/kernels/BUILD:1509:1: output 'tensorflow/core/kernels/_objs/depth_space_ops_gpu/tensorflow/core/kernels/depthtospace_op_gpu.cu.pic.o' was not created.
ERROR: /disk1/caina2/tensorflow/tensorflow/core/kernels/BUILD:1509:1: not all outputs were created.
ERROR: /disk1/caina2/tensorflow/tensorflow/core/kernels/BUILD:1509:1: output 'tensorflow/core/kernels/_objs/depth_space_ops_gpu/tensorflow/core/kernels/spacetodepth_op_gpu.cu.pic.o' was not created.
Target //tensorflow/tools/pip_package:build_pip_package failed to build
INFO: Elapsed time: 242.863s, Critical Path: 236.90s

**Comment by concretevitamin** [comment]
Two notes:

1. You said "install from source".  What version/commit?
2. CentOS 7 and above are supported.  Please try to use one of those versions.

**Comment by annisamansa** [comment]
sorry for forgetting it...
commit fc9162975e52978d3af38549b570cc3cc5f0ab66

is that still because of centos version?

**Comment by concretevitamin** [comment]
I don't know, unfortunately.  Please try to test against a newer version (>= 7).

**Comment by annisamansa** [comment]
~~~-_______-~~~thank u all the same...

**Comment by annisamansa** [comment]
hooray! centos 7.x finally successful! thanks god~~~~~~~~~
