### ISSUE TITLE
Looking for a simple gray scale and threshold function in tflite with flutter

### ISSUE THREAD

**Issue by officer47p** [tensorflow/tensorflow#34129]
Hey everybody,
I know it's a wrong place to ask this question but I couldn't anywhere else active like GitHub, so here it goes.
I'm creating a flutter app that needs to get the stream of the frames from the camera and do some image processing on it, actually, just turning it into grayscale and do a threshold operation.
I couldn't find any library that can do that in Flutter.
I used to do these operations with Opencv and numpy in python, but with flutter, it's a whole other story.
I thought that maybe flutter "tflite" has this feature in it.

Thanks a lot and I'm sorry to post this question here.

**Comment by ymodak** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.

 Thanks!
