### ISSUE TITLE
Build failed on matrix_square_root_op using GCC 7.4.0 and Ubuntu 18.04

### ISSUE THREAD

**Issue by nlbutts** [tensorflow/tensorflow#34122]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
`
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.3 LTS"
NAME="Ubuntu"
VERSION="18.04.3 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.3 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
`

- TensorFlow installed from (source or binary):
Tensorflow github hash: ce0b9aa347979cfbe4291440a3aeeb7af3dda41d
- TensorFlow version:
2.0

- Python version:
Python 3.6.8

- Installed using virtualenv? pip? conda?:
Building

- Bazel version (if compiling from source):
bazel 0.29.1

- GCC/Compiler version (if compiling from source):
`
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/7/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 7.4.0-1ubuntu1~18.04.1' --with-bugurl=file:///usr/share/doc/gcc-7/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++ --prefix=/usr --with-gcc-major-version-only --program-suffix=-7 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --enable-default-pie --with-system-zlib --with-target-system-zlib --enable-objc-gc=auto --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 7.4.0 (Ubuntu 7.4.0-1ubuntu1~18.04.1) 
`

- CUDA/cuDNN version:
NA

- GPU model and memory:
NA

**Describe the problem**

I'm attempting to build Tensorflow from source to enable AVX2 and FMA instructions. I get the following error, which appears to be a compiler bug???

/projects/tensorflow/tensorflow/core/kernels/BUILD:3559:1: C++ compilation of rule '//tensorflow/core/kernels:matrix_square_root_op' failed (Exit 4)
gcc: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-7/README.Bugs> for instructions.
Target //tensorflow/tools/pip_package:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.

**Comment by nikochiko** [comment]
Please refer to this [table](https://www.tensorflow.org/install/source.md#linux) for tested build configurations. Bazel 0.29.1 is not supported, use Bazel 0.26.1 instead.

**Comment by dbonner** [comment]
When you run ./configure with bazel 0.26.1 you are told that you must install a higher version of bazel.

**Comment by nikochiko** [comment]
Can you send a more detailed error log? Also your GCC version.

**Comment by gadagashwini** [comment]
@nlbutts, Please Provide the exact sequence of commands / steps that you executed before running into the problem and also include the full error log. Thanks!

**Comment by wdirons** [comment]
`gcc: internal compiler error: Killed (program cc1plus)` is a common error seen at random spots when you don't have enough memory on the system your compiling TensorFlow on. Try using the `--local_resources` flag to limit resource usage during the build.

Something like:

```
bazel build -c opt --local_resources 4096,4.0,1.0 //tensorflow/tools/pip_package:build_pip_package
```

**Comment by nlbutts** [comment]
OK, I got it working on one of my computers. I uninstalled Bazel 0.29.1 and installed Bazel 0.26.1. Then I limited the amount of memory allowed to be used with this command:
`
bazel build --cxxopt="-D_GLIBCXX_USE_CXX11_ABI=0" --local_ram_resources=8192 -c opt --copt=-mavx --copt=-mavx2 --copt=-mfma --copt=-mfpmath=both -k //tensorflow/tools/pip_package:build_pip_package
`
