### ISSUE TITLE
The latest version(2.0.0) of TensorFlow import protobuf error

### ISSUE THREAD

**Issue by chenquan** [tensorflow/tensorflow#34120]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Win10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):binary
- TensorFlow version (use command below):2.0.0
- Python version:3.6.0
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

v2.0.0-rc2-26-g64c3d382ca 2.0.0

**Describe the current behavior**

Importing tensorflow gives me following error.
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "E:\ProgramData\Anaconda3\envs\ai\lib\site-packages\tensorflow\__init__.py", line 98, in <module>
    from tensorflow_core import *
  File "E:\ProgramData\Anaconda3\envs\ai\lib\site-packages\tensorflow_core\__init__.py", line 40, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "E:\ProgramData\Anaconda3\envs\ai\lib\site-packages\tensorflow\__init__.py", line 50, in __getattr__
    module = self._load()
  File "E:\ProgramData\Anaconda3\envs\ai\lib\site-packages\tensorflow\__init__.py", line 44, in _load
    module = _importlib.import_module(self.__name__)
  File "E:\ProgramData\Anaconda3\envs\ai\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "E:\ProgramData\Anaconda3\envs\ai\lib\site-packages\tensorflow_core\python\__init__.py", line 52, in <module>
    from tensorflow.core.framework.graph_pb2 import *
  File "E:\ProgramData\Anaconda3\envs\ai\lib\site-packages\tensorflow_core\core\framework\graph_pb2.py", line 7, in <module>
    from google.protobuf import descriptor as _descriptor
  File "E:\ProgramData\Anaconda3\envs\ai\lib\site-packages\google\protobuf\descriptor.py", line 47, in <module>
    from google.protobuf.pyext import _message
ImportError: DLL load failed: 找不到指定的程序。
```
**Solution**
I already found a solution to this problem. It is related to the pip package protobuf 3.6.0. I solved this problem by issuing following commands:
```
pip uninstall protobuf
pip install protobuf==3.6.0
```
**Describe the expected behavior**

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

```python
import tensorflow
```

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by ravikyram** [comment]
@chenquan 

Looks like you found solution for this issue. Can you please confirm, whether we can close this issue as it was resolved. Thanks!

**Comment by chenquan** [comment]
Yes! According to the installation log, it is caused by `protobuf > = 3.6.1`.The installation of version 3.6.0 can work normally.

**Comment by chenquan** [comment]
> @chenquan
> 
> Looks like you found solution for this issue. Can you please confirm, whether we can close this issue as it was resolved. Thanks!

Yes! According to the installation log, it is caused by `protobuf > = 3.6.1`.The installation of version 3.6.0 can work normally.

**Comment by ravikyram** [comment]
I am closing this issue, since it was resolved. Thanks!
