### ISSUE TITLE
Failed to load delegate from libedgetpu.so.1.0

### ISSUE THREAD

**Issue by bsddemon** [tensorflow/tensorflow#34135]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
Raspbian
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
Raspberry Pi
- TensorFlow installed from (source or binary):
Binary
- TensorFlow version:
- Python version:
3.5
- Installed using virtualenv? pip? conda?:
pip
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Describe the problem**
 libedgetpu.so.1.0 fails to load for certain user.

**Provide the exact sequence of commands / steps that you executed before running into the problem**
  interpreter = Interpreter(args.model, experimental_delegates=[load_delegate('libedgetpu.so.1.0')])

It works perfectly for the user I can sudo. But I want to use the library with a different user (that cannot do sudo). I found in another issue that I need to add this user to the plugdev group. Which I did with the following command:
sudo usermod -aG plugdev [your username] 
This did not solve the problem.

**Any other info / logs**
    interpreter = Interpreter(args.model, experimental_delegates=[load_delegate('libedgetpu.so.1.0')])
  File "/home/certain-user/.local/lib/python3.5/site-packages/tflite_runtime/interpreter.py", line 168, in load_delegate
    library, str(e)))
ValueError: Failed to load delegate from libedgetpu.so.1.0

**Comment by Namburger** [comment]
@bsddemon is it only for certain user? Try this:
```
$ sudo usermod -aG plugdev [your username]
```

**Comment by freedomtan** [comment]
It seems it's not documented. At least, I don't remember seeing it mentioned. Using delegate is kinda API/ABI dependent, if there is data structure or function parameters changes, loading a delegate could fail. A safe way to make sure you can use the Edge TPU delegate is to check the source code by Edge TPU team. E.g., the [latest source code](https://github.com/google-coral/edgetpu) you can find now is for diploria2. And the TensorFlow version used by it is TensorFlow https://github.com/tensorflow/tensorflow/commit/5d0b55dd4a00c74809e5b32217070a26ac6ef823. You can find corresponding version in Edge TPU repo's WORKSPACE file, check [here](https://github.com/google-coral/edgetpu/blob/master/WORKSPACE#L5-L8)

**Comment by DebojitBiswas** [comment]
Hi Team,
I am also getting the same error while I am trying to access the python script from a php block through a browser. The program is running fine while run from a terminal. For an example "python runProg.py" works fine from the terminal. Also, I can run the php block separately which is calling the python block. Like "php start.php" works fine. But While I am running it from the browser like 192.168.XX.XX/start.php, the browser is throwing the error. I did not find the solution through the internet. If anyone got any suggestion that would be helpful.

**Comment by Olli69** [comment]
With MacOS restarting the computer solved the problem.

**Comment by DebojitBiswas** [comment]
Hi Olli,
I am using a Raspberry Pi. The problem persists for last one month. I did at least 100 restarts in the meantime.

**Comment by bsddemon** [comment]
I am also using a Raspberry Pi and I still have not solved this issues.

**Comment by Namburger** [comment]
@DebojitBiswas @bsddemon make sure you guys upgrade the `tflite_runtime` package from [here](https://www.tensorflow.org/lite/guide/python)
My py runs consistently without issues

**Comment by Syirrus** [comment]
> With MacOS restarting the computer solved the problem.

I'm having the same problem and restarting my machine does nothing. :(

**Comment by Syirrus** [comment]
For me I tried this also on a RPI4 - 4GB and I still get this error when I connect the TPU to a USB3.0 port. If I use a USB2.0 port it works.

**Comment by Namburger** [comment]
@Syirrus I believe this USB3.0 issues is actually a bug in rpi4's HW. Check [here](https://www.raspberrypi.org/documentation/hardware/raspberrypi/usb/README.md)

**Comment by youngelf** [comment]
I encounter this problem on the Coral Edge TPU boards as well.
Setup:
1. Board is updated (not that it matters since no new software has been released for some time.)
2. I am trying to run the classification example from [this repository](https://github.com/google-coral/tflite/tree/master/python/examples/classification)
3. I have installed the wheel for tflite_runtime-2.1.0.post1-cp35-cp35m. Newer wheels refuse to install with errors:
```
$ pip3 install https://dl.google.com/coral/python/tflite_runtime-2.1.0.post1-cp38-cp38-linux_aarch64.whl
tflite_runtime-2.1.0.post1-cp38-cp38-linux_aarch64.whl is not a supported wheel on this platform.
```
4. I haven't made any changes, I'm just trying to run the hello-world of this device and confirm stuff is working. 


Full error is below:
```
tflite/python/examples/classification$ python3 classify_image.py \
>   --model models/mobilenet_v2_1.0_224_inat_bird_quant.tflite \
>   --labels models/inat_bird_labels.txt \
>   --input images/parrot.jpg
Traceback (most recent call last):
  File "classify_image.py", line 122, in <module>
    main()
  File "classify_image.py", line 99, in main
    interpreter = make_interpreter(args.model)
  File "classify_image.py", line 73, in make_interpreter
    {'device': device[0]} if device else {})
  File "/usr/local/lib/python3.5/dist-packages/tflite_runtime/interpreter.py", line 161, in load_delegate
    delegate = Delegate(library, options)
  File "/usr/local/lib/python3.5/dist-packages/tflite_runtime/interpreter.py", line 90, in __init__
    self._library = ctypes.pydll.LoadLibrary(library)
  File "/usr/lib/python3.5/ctypes/__init__.py", line 425, in LoadLibrary
    return self._dlltype(name)
  File "/usr/lib/python3.5/ctypes/__init__.py", line 347, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libedgetpu.so.1: cannot open shared object file: No such file or directory
Exception ignored in: <bound method Delegate.__del__ of <tflite_runtime.interpreter.Delegate object at 0xffff77fb1e80>>
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/tflite_runtime/interpreter.py", line 125, in __del__
    if self._library is not None:
AttributeError: 'Delegate' object has no attribute '_library'
```

**Comment by Namburger** [comment]
@youngelf 
```
OSError: libedgetpu.so.1: cannot open shared object file: No such file or directory
```
Means that you son't have libedgetpu installed. 
Also, can you share your outputs of:
```
cat /etc/os-release
dpkg -l | grep edgetpu
```
It looks like you are running a very old version of mendel OS to even have python3.5 as default. I know there are a lot of tutorials out there that had older versions but I definitely suggest installing new OS. Currently, we're at mendel 5.0, try this: https://coral.ai/docs/dev-board/reflash/#flash-a-new-system-image

**Comment by youngelf** [comment]
Thanks, namburger. I flashed it last weekend, here we go:

$ cat /etc/os-release
PRETTY_NAME="Mendel GNU/Linux 5 (Eagle)"
NAME="Mendel GNU/Linux"
ID=mendel
ID_LIKE=debian
HOME_URL="https://coral.ai/"
SUPPORT_URL="https://coral.ai/"
BUG_REPORT_URL="https://coral.ai/"
VERSION_CODENAME="eagle"

$ dpkg -l |grep edgetpu
ii  edgetpu-examples                     14.1                                all          Example code for Edge TPU Python API
ii  edgetpudemo                          3-1                                 all          Edge TPU demo script
ii  libedgetpu-dev                       14.1                                arm64        Development files for libedgetpu
ii  libedgetpu1-std:arm64                14.1                                arm64        Support library for Edge TPU
ii  python3-edgetpu                      14.1                                arm64        Edge TPU Python API
ii  python3-edgetpuvision                6-1                                 arm64        EdgeTPU camera API


# wget https://dl.google.com/coral/python/tflite_runtime-2.1.0.post1-cp37-cp37m-linux_aarch64.whl--2020-11-05 17:56:48--  https://dl.google.com/coral/python/tflite_runtime-2.1.0.post1-cp37-cp37m-linux_aarch64.whl
Resolving dl.google.com (dl.google.com)... 172.217.5.110, 2607:f8b0:4007:803::200e
Connecting to dl.google.com (dl.google.com)|172.217.5.110|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1940683 (1.9M) [application/octet-stream]
Saving to: ‘tflite_runtime-2.1.0.post1-cp37-cp37m-linux_aarch64.whl’

tflite_runtime-2.1.0.post1 100%[=======================================>]   1.85M  2.89MB/s    in 0.6s

2020-11-05 17:56:49 (2.89 MB/s) - ‘tflite_runtime-2.1.0.post1-cp37-cp37m-linux_aarch64.whl’ saved [1940683/1940683]

# pip3 install tflite_runtime-2.1.0.post1-cp37-cp37m-linux_aarch64.whl
Processing ./tflite_runtime-2.1.0.post1-cp37-cp37m-linux_aarch64.whl
Requirement already satisfied: numpy>=1.12.1 in /usr/lib/python3/dist-packages (from tflite-runtime==2.1.0.post1) (1.16.2)
Installing collected packages: tflite-runtime
Successfully installed tflite-runtime-2.1.0.post1


$ ipython3
Python 3.7.3 (default, Dec 20 2019, 18:57:59)
Type "copyright", "credits" or "license" for more information.

IPython 5.8.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: import tflite_runtime as tf

In [2]: tf.__version__
Out[2]: '2.1.0.post1'


~/coral/tflite/python/examples/classification$ python3 classify_image.py \
> --model models/mobilenet_v2_1.0_224_inat_bird_quant_edgetpu.tflite \
> --labels models/inat_bird_labels.txt \
> --input images/parrot.jpg

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/tflite_runtime/interpreter.py", line 161, in load_delegate
    delegate = Delegate(library, options)
  File "/usr/local/lib/python3.7/dist-packages/tflite_runtime/interpreter.py", line 120, in __init__
    raise ValueError(capture.message)
ValueError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "classify_image.py", line 122, in <module>
    main()
  File "classify_image.py", line 99, in main
    interpreter = make_interpreter(args.model)
  File "classify_image.py", line 73, in make_interpreter
    {'device': device[0]} if device else {})
  File "/usr/local/lib/python3.7/dist-packages/tflite_runtime/interpreter.py", line 164, in load_delegate
    library, str(e)))
ValueError: Failed to load delegate from libedgetpu.so.1


(I suspect hardware damage, as on this board the Wifi is detected with 'lshw' but nmcli doesn't think it exists.)

# nmcli d
DEVICE  TYPE      STATE      CONNECTION         
eth0    ethernet  connected  Wired connection 1 
usb0    ethernet  connected  gadget0            
usb1    ethernet  connected  gadget1            
lo      loopback  unmanaged  --             

Full output of 'lshw' attached here:
[lshw.txt](https://github.com/tensorflow/tensorflow/files/5498462/lshw.txt)

**Comment by Namburger** [comment]
@youngelf does 
ls /dev/apex_0 
shows anything?

**Comment by youngelf** [comment]
Nope, nothing. 

```
# ls /dev/
autofs           input             mxc_hantro          random     tty22  tty46    ttymxc2   vcs2
block            ion               net                 rtc        tty23  tty47    ttyp0     vcs3
... 
initctl          mqueue            ptypf               tty21      tty45  ttymxc1  vcs1

```

Nothing called apex.

**Comment by Namburger** [comment]
@youngelf apex is literally how the software interact with the edgetpu lol
Could you ping us an email to coral-support@google.com? 
Looks like some how the edgetpu completely disappear from the board, we can issue a replacement

**Comment by youngelf** [comment]
Super, thanks. Will do.

**Comment by youngelf** [comment]
Got the updated boards, and I was able to run the inference in the classify_image.py example from [here](https://coral.ai/docs/dev-board/get-started#6-run-a-model-using-the-pycoral-api).

Thanks so much!

**Comment by sushreebarsa** [comment]
@bsddemon Could you please try to  upgrade the **`tflite_runtime`** package from [link](https://www.tensorflow.org/lite/guide/python) and try to execute your code using latest stable version of TF **`2.6.0`** .Please let us know if helps?Thanks!

**Comment by pri2si17-1997** [comment]
I have also faced this issue and I think one more possible reason is that the user may not be the part of `apex` group. So, adding user to the `apex` group can fix this issue. This can be done using:

`sudo usermod -a -G apex <user_name>`

This may fix #32743.

**Comment by Redsandro** [comment]
So what was actually causing the problem? What was the solution? I connected the Coral Edge USB version to a desktop PC, I'm running into the issues described above. Looks like the Coral device `1a6e:089a` is connected, but `apex_0` is not available.

```
$ python3 examples/classify_image.py --model test_data/mobilenet_v2_1.0_224_inat_bird_quant_edgetpu.tflite --labels test_data/inat_bird_labels.txt --input test_data/parrot.jpg

ValueError: Failed to load delegate from libedgetpu.so.1

$ dpkg -l | grep edgetpu
||/ Name                   Version  Architecture  Description
ii  libedgetpu1-std:amd64  16.0     amd64         Support library for Edge TPU

$ lsusb | grep "1a6e:089a"
Bus 004 Device 007: ID 1a6e:089a Global Unichip Corp. 

$ ls /dev/apex_0
ls: cannot access '/dev/apex_0': No such file or directory
```

**Comment by Redsandro** [comment]
Disregard the above. I have not restarted this server in years because everything just works without ever rebooting.
But I thought I'd give it a shot and reboot. Now it works.

__PS - I stil do not have `/dev/apex_0`.__ But the inferencing examples now work. Turns out this is only for the **PCIe Coral.** So to avoid confusion for future googlers, the USB Coral is hidden away in `/dev/bus/usb`.
