### ISSUE TITLE
Unable to convert .pb to .tflite 

### ISSUE THREAD

**Issue by Keyrainn** [tensorflow/tensorflow#34143]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Window 10
- TensorFlow installed from (source or binary): python -m pip install tensorflow==1.15
- TensorFlow version (or github SHA if from source): 1.15

I am currently trying to convert .pb file from export_tflite_ssd_graph.py into a .tflite file and encountered these error:

>2019-11-11 06:45:44.042588: F tensorflow/lite/toco/tooling_util.cc:935] Check failed: GetOpWithOutput(model, output_array) Specified output array "'TFLite_Detection_PostProcess'" is not produced by any op in this graph. Is it a typo? This should not happen. If you trigger this error please send a bug report (with code to reporduce this error), to the TensorFlow Lite team.
Fatal Python error: Aborted

This is what i try to run
```
tflite_convert --output_file=C:/tensorflow1/models/research/object_detection/inference_graph/detect.tflite --graph_def_file=C:/tensorflow1/models/research/object_detection/inference_graph/tflite_graph.pb --inference_type=FLOAT --inference_input_type=QUANTIZED_UINT8 --input_arrays=normalized_input_image_tensor --input_shapes=1,300,300,3 --output_arrays='TFLite_Detection_PostProcess','TFLite_Detection_PostProcess:1','TFLite_Detection_PostProcess:2','TFLite_Detection_PostProcess:3' --mean_values=128 --std_dev_values=128 --change_concat_input_ranges=false --allow_custom_ops
```

Link is the full traceback:
https://pastebin.com/xJ1vZGmd

I've also check from https://stackoverflow.com/questions/52918051/how-to-convert-pb-to-tflite-format  and confirm that the output array is TFLite_Detection_PostProcess
```
output name =
TFLite_Detection_PostProcess

Input name =
normalized_input_image_tensor
```

**Comment by Keyrainn** [comment]
>Update

tested my frozen_inference.pb on object_detection_tutorial.ipynb and the inference is working fine. 

![WhatsApp Image 2019-11-11 at 21 45 27](https://user-images.githubusercontent.com/18519104/68642815-4c0f2080-054a-11ea-9636-fac0b8c4cf21.jpeg)

**Comment by srjoglekar246** [comment]
Hey @Keyrainn , did you add `--add_postprocessing_op=true` to the command when you ran `export_tflite_ssd_graph.py`? If yes, could you paste that entire command? Looks like the .pb file you have exported doesn't have the exact structure the converter expects, so something might be off.

**Comment by Keyrainn** [comment]
currently stuck with issue #7640

**Comment by Keyrainn** [comment]
Currently stuck with [Invoking ptxas not supported on Windows #7640](https://github.com/tensorflow/models/issues/7640)

**Comment by Keyrainn** [comment]
Hi @srjoglekar246 , i have added ```--add_postprocessing_op=true``` when running ```export_tflite_ssd_graph.py``` and it's still producing the same error.

below is the command that i use to ran ```export_tflite_ssd_graph.py``` :
python export_tflite_ssd_graph.py --pipeline_config_path=training/ssd_mobilenet_v2_coco.config --trained_checkpoint_prefix training/model.ckpt-10647 --output_directory inference_tflite --add_postprocessing_op=true --max_detections 10

**Comment by srjoglekar246** [comment]
I see the following in your converter command: `--inference_type=FLOAT --inference_input_type=QUANTIZED_UINT8` Is your model quantized? 

If yes, please provide the following instead:
``` 
--input_format=TENSORFLOW_GRAPHDEF --output_format=TFLITE --inference_type=QUANTIZED_UINT8 --mean_values=129 --std_values=128
```

If not:
```
--input_format=TENSORFLOW_GRAPHDEF --output_format=TFLITE --inference_type=FLOAT
```

**Comment by Keyrainn** [comment]
I've retrained an unquantized model and have tried as per you suggestion and it still come out with the same error

```
tflite_convert --graph_def_file=C:/tensorflow1/models/research/object_detection/inference_tflite/tflite_graph.pb --output_file=C:/tensorflow1/models/research/object_detection/inference_tflite/detect.tflite --input_format=TENSORFLOW_GRAPHDEF --output_format=TFLITE --inference_input_type=FLOAT --input_shapes="1,300, 300,3" --input_arrays=normalized_input_image_tensor --output_arrays='TFLite_Detection_PostProcess','TFLite_Detection_PostProcess:1','TFLite_Detection_PostProcess:2','TFLite_Detection_PostProcess:3' --inference_type=FLOAT --allow_custom_ops

```

**Comment by Keyrainn** [comment]
I've trained an unquantized model and added as per your suggestion. but its still producing the same error

```
tflite_convert --graph_def_file=C:/tensorflow1/models/research/object_detection/inference_tflite/tflite_graph.pb --output_file=C:/tensorflow1/models/research/object_detection/inference_tflite/detect.tflite --input_format=TENSORFLOW_GRAPHDEF --output_format=TFLITE --inference_type=FLOAT --input_shapes="1,300, 300,3" --input_arrays=normalized_input_image_tensor --output_arrays='TFLite_Detection_PostProcess','TFLite_Detection_PostProcess:1','TFLite_Detection_PostProcess:2','TFLite_Detection_PostProcess:3' --allow_custom_ops



```

**Comment by Keyrainn** [comment]
@srjoglekar246 i'm not sure what kind of bug i'm facing but to others that having this issue current workaround is to run it in google colab.

**Comment by srjoglekar246** [comment]
That is strange. So running in colab with the same commands solved it for you as well?

**Comment by Keyrainn** [comment]
yes it solve for me. Currently i am able to do up to training part only. all file conversion to .pb or .tflite is being done on colab

**Comment by srjoglekar246** [comment]
I guess the TF version (or the environment) you are using might have some bugs. You could try using our [Python API](https://www.tensorflow.org/lite/convert/python_api) for conversion to fit better into your training+conversion pipeline, but your error seems to indicate an issue with the `export_tflite_ssd_graph` tool. Do you run that script in colab as well?

**Comment by Keyrainn** [comment]
yes. only training done on local machine

**Comment by josantoniojl** [comment]
Hi, do you know any tutorial to use google colab to transform my models? I've done the training, but I have problems transforming it into lite format. 

> yes. only training done on local machine.

**Comment by erolgerceker** [comment]
i did what u said. i got this error.

UnicodeDecodeError: 'utf-8' codec can't decode byte 0x9d in position 3: invalid start byte

**Comment by erolgerceker** [comment]
> I see the following in your converter command: `--inference_type=FLOAT --inference_input_type=QUANTIZED_UINT8` Is your model quantized?
> 
> If yes, please provide the following instead:
> 
> ```
> --input_format=TENSORFLOW_GRAPHDEF --output_format=TFLITE --inference_type=QUANTIZED_UINT8 --mean_values=129 --std_values=128
> ```
> 
> If not:
> 
> ```
> --input_format=TENSORFLOW_GRAPHDEF --output_format=TFLITE --inference_type=FLOAT
> ```

i did what u said. i got this error.

UnicodeDecodeError: 'utf-8' codec can't decode byte 0x9d in position 3: invalid start byte

**Comment by srjoglekar246** [comment]
@erolgerceker Which model are you trying to convert? The error indicates something is wrong with the source (TensorFlow) model, which is strange.

**Comment by spranjal25** [comment]
> **System information**
> 
> * OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Window 10
> * TensorFlow installed from (source or binary): python -m pip install tensorflow==1.15
> * TensorFlow version (or github SHA if from source): 1.15
> 
> I am currently trying to convert .pb file from export_tflite_ssd_graph.py into a .tflite file and encountered these error:
> 
> > 2019-11-11 06:45:44.042588: F tensorflow/lite/toco/tooling_util.cc:935] Check failed: GetOpWithOutput(model, output_array) Specified output array "'TFLite_Detection_PostProcess'" is not produced by any op in this graph. Is it a typo? This should not happen. If you trigger this error please send a bug report (with code to reporduce this error), to the TensorFlow Lite team.
> > Fatal Python error: Aborted
> 
> This is what i try to run
> 
> ```
> tflite_convert --output_file=C:/tensorflow1/models/research/object_detection/inference_graph/detect.tflite --graph_def_file=C:/tensorflow1/models/research/object_detection/inference_graph/tflite_graph.pb --inference_type=FLOAT --inference_input_type=QUANTIZED_UINT8 --input_arrays=normalized_input_image_tensor --input_shapes=1,300,300,3 --output_arrays='TFLite_Detection_PostProcess','TFLite_Detection_PostProcess:1','TFLite_Detection_PostProcess:2','TFLite_Detection_PostProcess:3' --mean_values=128 --std_dev_values=128 --change_concat_input_ranges=false --allow_custom_ops
> ```
> 
> Link is the full traceback:
> https://pastebin.com/xJ1vZGmd
> 
> I've also check from https://stackoverflow.com/questions/52918051/how-to-convert-pb-to-tflite-format and confirm that the output array is TFLite_Detection_PostProcess
> 
> ```
> output name =
> TFLite_Detection_PostProcess
> 
> Input name =
> normalized_input_image_tensor
> ```

I was getting the same error, looks like a small change can solve this.
Don't use the quotes in output_arrays i.e (' TFlite_Detection_PostProcess')

instead of using
 --output_arrays='TFLite_Detection_PostProcess','TFLite_Detection_PostProcess:1','TFLite_Detection_PostProcess:2','TFLite_Detection_PostProcess:3' Use: 
--output_arrays=TFLite_Detection_PostProcess,TFLite_Detection_PostProcess:1,TFLite_Detection_PostProcess:2,TFLite_Detection_PostProcess:3

let me know if the same works for you!

**Comment by Saduf2019** [comment]
@Keyrainn 
Please let us know if this is still an issue.

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.
