### ISSUE TITLE
How to get training time per epoch using TPUEstimator?

### ISSUE THREAD

**Issue by elvinjgalarza** [tensorflow/tensorflow#34147]
I know with Keras you can set verbose levels (0,1,2) to see training time per each epoch; however, I can't seem to figure out how to get a "verbose" feature working when trying to use the TPUEstimator. I'm using v1.14

**Comment by ymodak** [comment]
```model.fit``` and ```model.evaluate```methods offer verbose functionality. You may use them with a variety of accelerators cpu, gpu and tpu.
You may set the log level in the program by;
```python
import tensorflow as tf
tf.logging.set_verbosity(tf.logging.INFO)
```

**Comment by elvinjgalarza** [comment]
Hi Yasir, thanks for answering! 

Doesn't model.fit and model.evaluate require a model that takes numpy arrays as a dataset only?

**Comment by ymodak** [comment]
That's correct. It will come in handy if using keras sequential api. For estimators you may try setting log level info for training status.
