### ISSUE TITLE
Combining packages from different channels

### ISSUE THREAD

**Issue by Anjaaaa** [tensorflow/tensorflow#34142]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
Ubuntu 18.04
- TensorFlow installed from (source or binary):
conda (using conda-forge)
- TensorFlow version:
1.13.2
- Python version:
2.7.15
- Installed using virtualenv? pip? conda?:
conda
- GCC/Compiler version (if compiling from source):
4.8.3

**Describe the problem**
I am trying to get a running tensorflow 1.13.2 combined with ROOT (in particular root, root_numpy, and rootpy) in a conda environment. The issue is that there is no one conda channel that contains all of those packages at once but I need to combine two channels. I tried different orders of installing the packages but whenever I start using the second channel, I get this error: (in this case, I first installed all the root stuff, which worked and then added tensorflow)
```
>>> import tensorflow
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/anja/anaconda3/envs/new_try/lib/python2.7/site-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "/home/anja/anaconda3/envs/new_try/lib/python2.7/site-packages/tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/home/anja/anaconda3/envs/new_try/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/home/anja/anaconda3/envs/new_try/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/home/anja/anaconda3/envs/new_try/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/home/anja/anaconda3/envs/new_try/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
ImportError: /home/anja/anaconda3/envs/new_try/lib/python2.7/site-packages/tensorflow/python/../../../../libstdc++.so.6: version `CXXABI_1.3.8' not found (required by /home/anja/anaconda3/envs/new_try/lib/python2.7/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so)
```

**Comment by gadagashwini** [comment]
@Anjaaaa, Is there a specific reason to use two different channels. 
Please follow the steps mentioned below to install Tenosrflow using conda single channel.
Set Up Anaconda Environments
conda create --name tf_2.0.0
Activate the new Environment
source activate tf_2.0.0
Install Tf 2.0
conda install tensorflow=2.0 python=2.7
Let us know if it resolves your issue. Thanks!

**Comment by Anjaaaa** [comment]
As I said, I want to install it in combination with `root`,`rootpy`, and `root-numpy` and there is no channel that combines all of them. I also tried installing everything from `conda-forge` and add what's missing using `pip` but no success.

**Comment by gadagashwini** [comment]
@Anjaaaa,
Sorry, but we don't provide support for issues with the conda environment.
Please follow the instructions mentioned in this [link](https://www.tensorflow.org/install/pip). Thanks!

**Comment by gadagashwini** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
