### ISSUE TITLE
[tf2.0] Can not load keras saved model with customized loss function

### ISSUE THREAD

**Issue by saintthor** [tensorflow/tensorflow#34140]
I run tensorflow.keras on colab.research.google.com. 

In tf2.0, I trained a model with a customized loss function named Loss, then saved it by keras.Model.save().
When I try loading it by 
`keras.models.load_model( 'filename', custom_objects = { 'Loss': Loss } )`
It raises:
> /tensorflow-2.0.0/python3.6/tensorflow_core/python/keras/engine/training_utils.py in get_loss_function(loss)
>    1092   return losses.LossFunctionWrapper(
>    1093       loss_fn,
> -> 1094       name=loss_fn.__name__,
>    1095       reduction=losses_utils.ReductionV2.SUM_OVER_BATCH_SIZE)
>    1096 
> 
> AttributeError: 'Loss' object has no attribute '__name__'

Even to set Loss.__name__ = 'xxx' before calling load_model does not help.

If set the 'compile' param to True for load_model, it may load successfully. But the loaded model can not work on evaluating or predicting.

To load the files saved by keras of tf1.5 is all OK. The model is trained by the same customized loss function. The model is saved to a file by tf1.5, while to a path by tf2.0.

How can I solve it?

**Comment by oanush** [comment]
@saintthor ,
Can you share a simple and standalone code to reproduce the issue? Thanks!

**Comment by saintthor** [comment]
> @saintthor ,
> Can you share a simple and standalone code to reproduce the issue? Thanks!

please test this code:

```
def Loss( y0, y ):
    return K.mean( K.maximum( K.abs( y0 / ( K.abs( y ) + 0.1 )), K.abs( y / ( K.abs( y0 ) + 0.1 ))))

InputLayer = tf.keras.layers.Input( dtype = 'float32', shape = ( 4, ))
Output = tf.keras.layers.Dense( 1, use_bias = True )( InputLayer )
model = tf.keras.models.Model( inputs = [InputLayer], outputs=[Output] )
model.compile( loss = Loss, optimizer = tf.keras.optimizers.Adam())
XData = np.random.random(( 100, 4 ))
YData = np.random.random(( 100, ))
model.fit( [XData], [YData], epochs = 5, batch_size = 5, verbose=2 )
model.save( 'mo.test' )
tf.keras.models.load_model( 'mo.test' )
```

the last line raises:
```

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-23-23b454583e49> in <module>()
     10 model.fit( [XData], [YData], epochs = 5, batch_size = 5, verbose=2 )
     11 model.save( 'mo.test' )
---> 12 tf.keras.models.load_model( 'mo.test' )

6 frames
/tensorflow-2.0.0/python3.6/tensorflow_core/python/keras/saving/save.py in load_model(filepath, custom_objects, compile)
    148   if isinstance(filepath, six.string_types):
    149     loader_impl.parse_saved_model(filepath)
--> 150     return saved_model_load.load(filepath, compile)
    151 
    152   raise IOError(

/tensorflow-2.0.0/python3.6/tensorflow_core/python/keras/saving/saved_model/load.py in load(path, compile)
     91     if model._training_config is not None:  # pylint: disable=protected-access
     92       model.compile(**saving_utils.compile_args_from_training_config(
---> 93           model._training_config))  # pylint: disable=protected-access
     94 
     95   return model

/tensorflow-2.0.0/python3.6/tensorflow_core/python/training/tracking/base.py in _method_wrapper(self, *args, **kwargs)
    455     self._self_setattr_tracking = False  # pylint: disable=protected-access
    456     try:
--> 457       result = method(self, *args, **kwargs)
    458     finally:
    459       self._self_setattr_tracking = previous_value  # pylint: disable=protected-access

/tensorflow-2.0.0/python3.6/tensorflow_core/python/keras/engine/training.py in compile(self, optimizer, loss, metrics, loss_weights, sample_weight_mode, weighted_metrics, target_tensors, distribute, **kwargs)
    334     # Prepare list of loss functions, same size of model outputs.
    335     self.loss_functions = training_utils.prepare_loss_functions(
--> 336         self.loss, self.output_names)
    337 
    338     target_tensors = self._process_target_tensor_for_compile(target_tensors)

/tensorflow-2.0.0/python3.6/tensorflow_core/python/keras/engine/training_utils.py in prepare_loss_functions(loss, output_names)
   1349       loss_functions.append(get_loss_function(loss.get(name, None)))
   1350   elif isinstance(loss, six.string_types):
-> 1351     loss_functions = [get_loss_function(loss) for _ in output_names]
   1352   elif isinstance(loss, collections_abc.Sequence):
   1353     if len(loss) != len(output_names):

/tensorflow-2.0.0/python3.6/tensorflow_core/python/keras/engine/training_utils.py in <listcomp>(.0)
   1349       loss_functions.append(get_loss_function(loss.get(name, None)))
   1350   elif isinstance(loss, six.string_types):
-> 1351     loss_functions = [get_loss_function(loss) for _ in output_names]
   1352   elif isinstance(loss, collections_abc.Sequence):
   1353     if len(loss) != len(output_names):

/tensorflow-2.0.0/python3.6/tensorflow_core/python/keras/engine/training_utils.py in get_loss_function(loss)
   1092   return losses.LossFunctionWrapper(
   1093       loss_fn,
-> 1094       name=loss_fn.__name__,
   1095       reduction=losses_utils.ReductionV2.SUM_OVER_BATCH_SIZE)
   1096 

AttributeError: 'Loss' object has no attribute '__name__'
```

thanks.

**Comment by saintthor** [comment]
changing the last line to
`tf.keras.models.load_model( 'mo.test', custom_objects = { 'Loss': Loss } )
`raises the same error.

**Comment by oanush** [comment]
@saintthor ,
Can you please provide complete code so that we can reproduce the issue from our end?Thanks!

**Comment by saintthor** [comment]
> @saintthor ,
> Can you please provide complete code so that we can reproduce the issue from our end?Thanks!

The above code is almost complete. See the follow code. I run it in google colab.
```

%tensorflow_version 2.x
import numpy as np
import tensorflow as tf
K = tf.keras.backend

def Loss( y0, y ):
    return K.mean( K.maximum( K.abs( y0 / ( K.abs( y ) + 0.1 )), K.abs( y / ( K.abs( y0 ) + 0.1 ))))

InputLayer = tf.keras.layers.Input( dtype = 'float32', shape = ( 4, ))
Output = tf.keras.layers.Dense( 1, use_bias = True )( InputLayer )
model = tf.keras.models.Model( inputs = [InputLayer], outputs=[Output] )
model.compile( loss = Loss, optimizer = tf.keras.optimizers.Adam())
XData = np.random.random(( 100, 4 ))
YData = np.random.random(( 100, ))
model.fit( [XData], [YData], epochs = 5, batch_size = 5, verbose=2 )
model.save( 'mo.test' )
#each of the follow lines raises error
#tf.keras.models.load_model( 'mo.test', custom_objects = { 'Loss': Loss } )
tf.keras.models.load_model( 'mo.test' )
```

**Comment by oanush** [comment]
Issue replicating for TF-2.0 and tf-nightly. kindly find the [gist](https://colab.sandbox.google.com/gist/oanush/d2a2ccbc84474b6fc693ebcad55f049c/34140.ipynb) of colab.Thanks!

**Comment by jvishnuvardhan** [comment]
@saintthor Approach to load a model when a custom object was used is little different. First, you need to load the saved model with `custom_objects` and `compile = False`. Then compile the model with the `custom_objects` as shown below.

```
model.save( 'mo.test' )
#each of the follow lines raises error
new_model =  tf.keras.models.load_model( 'mo.test', custom_objects = { 'Loss': Loss },compile=False)
new_model.compile( loss = Loss, optimizer = tf.keras.optimizers.Adam())
#tf.keras.models.load_model( 'mo.test' )
```

Hope this helps. Please close the issue if the issue was resolved. Thanks!

**Comment by saintthor** [comment]
> @saintthor Approach to load a model when a custom object was used is little different. First, you need to load the saved model with `custom_objects` and `compile = False`. Then compile the model with the `custom_objects` as shown below.
> 
> ```
> model.save( 'mo.test' )
> #each of the follow lines raises error
> new_model =  tf.keras.models.load_model( 'mo.test', custom_objects = { 'Loss': Loss },compile=False)
> new_model.compile( loss = Loss, optimizer = tf.keras.optimizers.Adam())
> #tf.keras.models.load_model( 'mo.test' )
> ```
> 
> Hope this helps. Please close the issue if the issue was resolved. Thanks!
> [Here](https://colab.sandbox.google.com/gist/jvishnuvardhan/ef405b1200a5a7e087408b693273f65b/34140.ipynb) is the gist for your reference. Thanks!

thank you. this solution works well.
