### ISSUE TITLE
tf.data.experimental.choose_from_datasets freezes if one of the datasets is empty

### ISSUE THREAD

**Issue by thijskooi** [tensorflow/tensorflow#34153]
**System information**
- TensorFlow version (you are using): 1.14.0
- Are you willing to contribute it (Yes/No): No

**Describe the feature and the current behavior/state.**

`tf.data.experimental.choose_from_datasets` freezes if one of the datasets is empty. This can happen for instance, when splitting the dataset into classes, recombining them using this function and one of the classes is not present in the input data. 

**Will this change the current api? How?**
No

**Who will benefit with this feature?**

Anyone using complicated input pipelines. 

**Any Other info.**

**Comment by ravikyram** [comment]
@thijskooi 
Do you have any use case that requires the feature you are interested in? Please feel free to submit a PR if you have use cases that supports that feature.Thanks!

**Comment by jsimsa** [comment]
@thijskooi thank you for reporting the issue. Could you please provide working example that can be used to readily reproduce the issue to aide with debugging? Thank you.

**Comment by rachellim** [comment]
Hi @thijskooi, I'm not able to reproduce your error with TF 1.14.0 (and at HEAD). Can you provide a repro?

**Comment by thijskooi** [comment]
Sorry for the delay in reply. Unfortunately, we can not create a minimal sample where this happens without sharing too much code, the issue may be further down our pipeline. I will close the issue for now, if this comes up in the future again with a clearer example I will re-open.
