### ISSUE TITLE
TensorFlow Lite Op Request

### ISSUE THREAD

**Issue by sachaarbonel** [tensorflow/tensorflow#34150]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): OSX 10.14.6
- TensorFlow installed from (source or binary): 2.0
- TensorFlow version (or github SHA if from source):

**Provide the text output from tflite_convert**

```bash
TensorFlow Lite currently doesn't support control flow ops: Enter, Exit, Merge, Switch. We are working on supporting control flow ops, please see github issue at https://github.com/tensorflow/tensorflow/issues/28485. Some of the operators in the model are not supported by the standard TensorFlow Lite runtime. If those are native TensorFlow operators, you might be able to use the extended runtime by passing --enable_select_tf_ops, or by setting target_ops=TFLITE_BUILTINS,SELECT_TF_OPS when calling tf.lite.TFLiteConverter(). Otherwise, if you have a custom implementation for them you can disable this error with --allow_custom_ops, or by setting allow_custom_ops=True when calling tf.lite.TFLiteConverter(). Here is a list of builtin operators you are using: ADD, CONCATENATION, CONV_2D, EQUAL, FLOOR, FULLY_CONNECTED, LESS, LOGICAL_AND, LOGISTIC, MAX_POOL_2D, MUL, RESHAPE, REVERSE_V2, SPLIT, TANH, TRANSPOSE. Here is a list of operators for which you will need custom implementations: CTC_BEAM_SEARCH_DECODER, LoopCond, RandomUniform, TensorArrayGatherV3, TensorArrayReadV3, TensorArrayScatterV3, TensorArrayV3, TensorArrayWriteV3.
```

Also, please include a link to a GraphDef or the model if possible.
The model comes from this repository : https://github.com/MaybeShewill-CV/CRNN_Tensorflow

**Any other info / logs**

Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by haozha111** [comment]
The model contains v1 control flow ops and tensorlist, which is not supported by our old converter.

Could you try to export the model in TF 2.0, and then try with our new converter (install the latest tf-nightly) and then add this:
converter.experimental_new_converter = True.

**Comment by Sach97** [comment]
Thank's @haozha111 I'll try that !

**Comment by haozha111** [comment]
is the issue fixed?

**Comment by Saduf2019** [comment]
@sachaarbonel 
Please update as per above comment.
