### ISSUE TITLE
BERT-joint TF1 baseline fails on TPU training

### ISSUE THREAD

**Issue by mosicr** [tensorflow/tensorflow#34155]
BERT-joint baseline script [https://github.com/google-research/language/tree/master/language/question_answering/bert_joint#training-our-model](url)
 fails on TPU training with:

E1111 11:25:56.709489 140509220771584 error_handling.py:81] Closing session due to error From /job:worker/replica:0/task:0:
End of sequence
	 [[node input_pipeline_task0/while/IteratorGetNext (defined at usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/ops.py:1748) ]]
2019-11-11 11:26:03.693223: W tensorflow/core/distributed_runtime/rpc/grpc_remote_master.cc:157] RPC failed with status = "Unavailable: Socket closed" and grpc_error_string = "{"created":"@1573471563.693073061","description":"Error received from peer","file":"external/grpc/src/core/lib/surface/call.cc","file_line":1039,"grpc_message":"Socket closed","grpc_status":14}", maybe retrying the RPC
2019-11-11 11:26:03.693329: W tensorflow/core/distributed_runtime/rpc/grpc_remote_master.cc:157] RPC failed with status = "Unavailable: Socket closed" and grpc_error_string = "{"created":"@1573471563.693032484","description":"Error received from peer","file":"external/grpc/src/core/lib/surface/call.cc","file_line":1039,"grpc_message":"Socket closed","grpc_status":14}", maybe retrying the RPC
ERROR:tensorflow:Error recorded from outfeed: Step was cancelled by an explicit call to `Session::Close()`.
E1111 11:26:17.120502 140509233358592 error_handling.py:75] Error recorded from outfeed: Step was cancelled by an explicit call to `Session::Close()`.
INFO:tensorflow:An error was raised. This may be due to a preemption in a connected worker or parameter server. The current session will be closed and a new session will be created. This error may also occur due to a gRPC failure caused by high memory or network bandwidth usage in the parameter servers. If this error occurs repeatedly, try increasing the number of parameter servers assigned to the job. Error: Session c3d5a74e41ee70e5 is not found.
I1111 11:26:17.120874 140510448183168 monitored_session.py:1269] An error was raised. This may be due to a preemption in a connected worker or parameter server. The current session will be closed and a new session will be created. This error may also occur due to a gRPC failure caused by high memory or network bandwidth usage in the parameter servers. If this error occurs repeatedly, try increasing the number of parameter servers assigned to the job. Error: Session c3d5a74e41ee70e5 is not found.
ERROR:tensorflow:

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
No custom code - this is google provided example
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
Google Colab default
- TensorFlow version (use command below):
print(tf.GIT_VERSION, tf.VERSION)
v1.15.0-0-g590d6eef7e 1.15.0
- Python version: 3.6.8 (default, Oct  7 2019, 12:59:55) 
[GCC 8.3.0]
Using TPU

**Code to reproduce the issue**
https://github.com/google-research/language/blob/master/language/question_answering/bert_joint/run_nq.py

**Comment by jvishnuvardhan** [comment]
@mosicr Sorry for missing this issue. Is this still an issue? Can you please run with `TF1.15.3` and see whether the issue persists with a newer version. I ran the code and notice some file missing error as shown below. Please take a look at the [gist here](https://colab.research.google.com/gist/jvishnuvardhan/5036b9b468071cf62f41e4d9f76d4960/untitled944.ipynb). Thanks

```
WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/bert/optimization.py:87: The name tf.train.Optimizer is deprecated. Please use tf.compat.v1.train.Optimizer instead.


---------------------------------------------------------------------------
ValidationError                           Traceback (most recent call last)
/usr/local/lib/python3.6/dist-packages/absl/flags/_flagvalues.py in _assert_validators(self, validators)
    527       try:
--> 528         validator.verify(self)
    529       except _exceptions.ValidationError as e:

10 frames
ValidationError: Flag --vocab_file must have a value other than None.

During handling of the above exception, another exception occurred:

IllegalFlagValueError                     Traceback (most recent call last)
/usr/local/lib/python3.6/dist-packages/absl/flags/_flagvalues.py in _assert_validators(self, validators)
    529       except _exceptions.ValidationError as e:
    530         message = validator.print_flags_with_values(self)
--> 531         raise _exceptions.IllegalFlagValueError('%s: %s' % (message, str(e)))
    532 
    533   def __delattr__(self, flag_name):

IllegalFlagValueError: flag --vocab_file=None: Flag --vocab_file must have a value other than None.
```

Please verify and close the issue if this was resolved for you. Thanks!
