### ISSUE TITLE
Can't train a model using Java in Windows

### ISSUE THREAD

**Issue by jedakiah13** [tensorflow/tensorflow#34152]
I know training a model is currently not supported for Java.

I was just wondering when this is likely to be available?

**Comment by ymodak** [comment]
Examples found in the [tensorflow/models](https://github.com/tensorflow/models/tree/master/samples/languages/java#tensorflow-for-java-examples) GitHub repository can be good starting point.
See https://github.com/tensorflow/models/tree/master/samples/languages/java/training

**Comment by jedakiah13** [comment]
Thank you but this is a very simple example.
For example if I follow
https://github.com/tensorflow/hub/blob/580847f6613fdf0b0d7911d8811c136df3e9404a/examples/image_retraining/retrain.py#L721

as an example for retraining an image recognition model, I should take the bottleneck and create a new training layer on top, I can't seem to do this in Java, perhaps I'm wrong but from what I've read elsewhere there just isn't java support for this.

If there is a way I can retrain Inception V3 in Java and I'm missing it then I would be happily guided.

**Comment by gowthamkpr** [comment]
@jedakiah13 You can try referring to this [deeplab example](https://stackoverflow.com/questions/61104096/tensorflow-inference-using-java-api-extremely-slow) and try converting the code to java on your own. Thanks!.

I'm closing this issue as this can be better asked in stackoverflow as this is a support question if you have any more questions. Thanks!
