### ISSUE TITLE
Performance regression with obj. det model from 1.14 to 1.15

### ISSUE THREAD

**Issue by dave-andersen** [tensorflow/tensorflow#34174]
2.7x slowdown on a nearly-off-the-shelf tensorflow object detection API model (differences and pipeline config below) when going from 1.14 to 1.15.  The regression is _not_ present in 2.0.

This is a fine-tuned SSD mobilenets FPN coco config, with the only changes being:

Fixed size input of 1024x1024
Single class detection
 model draws from layers 2-5 instead of 3-6 and so is a fair bit larger than one might otherwise expect.

I've attached my pipeline.config to reproduce the bug.

I'm just running natively in TF with my own inference pipeline, doing the obvious feed_dict to get data in:

```
            out = sess.run(
                [
                    sess.graph.get_tensor_by_name(node) for node in [
                        'num_detections:0', 'detection_scores:0',
                        'detection_boxes:0', 'detection_classes:0'
                    ]
                ],
                feed_dict={'image_tensor:0': img_batch})
```
[pipeline.config.txt](https://github.com/tensorflow/tensorflow/files/3833314/pipeline.config.txt)

**System information**
Running on Ubuntu 18.04, Xeon, Titan V GPU, 12GB

Comparing between TF 1.14-GPU and 1.15 with conda/pip.
```
python 3.6.9 |Anaconda, Inc.| (default, Jul 30 2019, 19:07:31)
[GCC 7.3.0] on linux
```

CUDA 10.0
CuDNN 7.6

**Describe the current behavior**

2.7x slower in 1.15. :-)

**Describe the expected behavior**

**Code to reproduce the issue**

See attached pipeline.config (would need to specify some training/testing tfrecord)

**Other info / logs**
This issue is related to an issue on tensorflow/serving:  https://github.com/tensorflow/serving/issues/1469

**Comment by ilaripih** [comment]
I can confirm this. All I did was re-export the SavedModel from the official pretrained checkpoint with a fixed `[None, 640, 640, 3]` input size and performance with batch size 4 went from 5.67 FPS to 0.22 FPS on a GTX 1060. So 25x slower for me. My setup:

* Tensorflow 1.14.0 (CPU version) for exporting the SavedModel
* Pipeline config: https://github.com/tensorflow/models/blob/master/research/object_detection/samples/configs/ssd_resnet50_v1_fpn_shared_box_predictor_640x640_coco14_sync.config
* `checkpoint` and `model.ckpt.*` used in the exporting operation: http://download.tensorflow.org/models/object_detection/ssd_resnet50_v1_fpn_shared_box_predictor_640x640_coco14_sync_2018_07_03.tar.gz

For inference I used the official libtensorflow-gpu from here: https://storage.googleapis.com/tensorflow/libtensorflow/libtensorflow-gpu-linux-x86_64-1.15.0.tar.gz

Interestingly, the performance is fine when running the SavedModel from the official `ssd_resnet50_v1_fpn_shared_box_predictor_640x640_coco14_sync_2018_07_03.tar.gz` tarball directly.

**Comment by gadagashwini** [comment]
@dave-andersen, can you try @ilaripih's workaround and let us know if that helps. Thanks!

**Comment by ilaripih** [comment]
@gadagashwini I don't think I presented any workaround. Yes, the performance is fine when using the official saved_model.pb from download.tensorflow.org. But as soon as I export the model (which I have to do for any custom model) the performance with TF 1.15.0-gpu drops.

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.
