### ISSUE TITLE
Bug with tf.function and complex variables

### ISSUE THREAD

**Issue by kmkolasinski** [tensorflow/tensorflow#34178]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): installed from conda using `conda install tensorflow==2.0`
- TensorFlow version (use command below): 2.0.0
- Python version: Python 3.6.0 :: Continuum Analytics, Inc.
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: using CPU only
- GPU model and memory: using CPU only

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
When running following code:
```
import tensorflow as tf
import numpy as np

@tf.function
def fn():
    some_variable = tf.cast(1.0, tf.complex64)
    T = 1j * np.eye(8, dtype=np.complex64)
    return tf.convert_to_tensor(T)

fn().numpy()
```
I got incorrect output:
```
array([[0.+1.j, 0.+1.j, 0.+1.j, 0.+1.j, 0.+1.j, 0.+1.j, 0.+1.j, 0.+1.j],
       [0.+1.j, 0.+1.j, 0.+1.j, 0.+1.j, 0.+1.j, 0.+1.j, 0.+1.j, 0.+1.j],
       [0.+1.j, 0.+1.j, 0.+1.j, 0.+1.j, 0.+1.j, 0.+1.j, 0.+1.j, 0.+1.j],
       [0.+1.j, 0.+1.j, 0.+1.j, 0.+1.j, 0.+1.j, 0.+1.j, 0.+1.j, 0.+1.j],
       [0.+1.j, 0.+1.j, 0.+1.j, 0.+1.j, 0.+1.j, 0.+1.j, 0.+1.j, 0.+1.j],
       [0.+1.j, 0.+1.j, 0.+1.j, 0.+1.j, 0.+1.j, 0.+1.j, 0.+1.j, 0.+1.j],
       [0.+1.j, 0.+1.j, 0.+1.j, 0.+1.j, 0.+1.j, 0.+1.j, 0.+1.j, 0.+1.j],
       [0.+1.j, 0.+1.j, 0.+1.j, 0.+1.j, 0.+1.j, 0.+1.j, 0.+1.j, 0.+1.j]],
      dtype=complex64)
```

I have installed fresh conda enviroment with python 3.6 and tensorflow 2.0.0. GPU 
is disabled with ` export CUDA_VISIBLE_DEVICES="-1"`

**Describe the expected behavior**

The output should be following:
```
array([[0.+1.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+1.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+1.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+1.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+1.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+1.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+1.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+1.j]],
      dtype=complex64)
```

I got correct output for following versions of the function:
```
@tf.function
def fn():
    T = 1j * np.eye(8, dtype=np.complex64)
    return tf.convert_to_tensor(T)
```
and (when tf.function is removed)
```
def fn():
    some_variable = tf.cast(1.0, tf.complex64)
    T = 1j * np.eye(8, dtype=np.complex64)
    return tf.convert_to_tensor(T)
```
and when I use small value for np.eye
```
@tf.function
def fn():
    some_variable = tf.cast(1.0, tf.complex64)
    T = 1j * np.eye(7, dtype=np.complex64)
    return tf.convert_to_tensor(T)
```

Can you reproduce my error ? 

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

As above. 

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

The fragment of the output of `conda list` command:
```
tensorflow                2.0.0           gpu_py36h6b29c10_0  
tensorflow-addons         0.5.0                     <pip>
tensorflow-base           2.0.0           gpu_py36h0ec5d1f_0  
tensorflow-estimator      2.0.0              pyh2649769_0  
tensorflow-probability    0.8.0                     <pip>
```

**Comment by oanush** [comment]
@kmkolasinski ,
please try using the latest ` tf-nightly 2.1.0.dev20191110 version-` `pip install tf-nightly` , issue seem to be fixed. Kindly find the [gist](https://colab.sandbox.google.com/gist/oanush/54566ac084555f5edb9aaf6adaf5301a/34178.ipynb) of colab.Thanks!

**Comment by kmkolasinski** [comment]
Thank you @oanush it works correctly with the latest version. This issue can be closed.

**Comment by oanush** [comment]
Closing since issue is resolved,Thanks!
