### ISSUE TITLE
cannot install tensorflow from source

### ISSUE THREAD

**Issue by lecterquadpartisan** [tensorflow/tensorflow#3418]
Hi, trying to build tensorflow from source. Getting the error message below -

"/home/lec/Downloads/tensorflow/tensorflow/tools/proto_text/BUILD:31:1: Linking of rule '//tensorflow/tools/proto_text:gen_proto_text_functions' failed: crosstool_wrapper_driver_is_not_gcc failed: error executing command third_party/gpus/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc -o bazel-out/host/bin/tensorflow/tools/proto_text/gen_proto_text_functions ... (remaining 31 argument(s) skipped): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1"

**Comment by concretevitamin** [comment]
Please complete environment information, steps you took, etc.  See #3366 as an example, thanks.

**Comment by lecterquadpartisan** [comment]
Environment info

Bazel 0.3.0

Operating System: Ubuntu 16.04
Installed version of CUDA and cuDNN: CUDA 8.0, cuDNN 5

Ran this step :
bazel build -c opt --config=cuda //tensorflow/tools/pip_package:build_pip_package

**Comment by lecterquadpartisan** [comment]
Repository used :
git clone https://github.com/tensorflow/tensorflow

**Comment by yaroslavvb** [comment]
may need to run with `--verbose_failures` to see what the actual error message was

**Comment by concretevitamin** [comment]
Yep.  Also, CUDA 8.0 may not be fully supported yet.  Try 7.5?
