### ISSUE TITLE
How to apply feature extraction in tensorflow (not use tf.keras)

### ISSUE THREAD

**Issue by tuanhanhdmprof** [tensorflow/tensorflow#34184]
I want to apply feature extraction with pre-trained model (VGG16) by removing the last layer and replacing other FC layer (less classes).
I don't want to use tf.keras. How to deal it?
Help me!
Thanks a lot!

**Comment by ymodak** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.
Thanks!
