### ISSUE TITLE
TF-TRT optimized graph get wrong results when using batch size <=7

### ISSUE THREAD

**Issue by ArtificialNotImbecile** [tensorflow/tensorflow#34185]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 1.14.0
- Python version: 3.6.8
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:10.2
- GPU model and memory:Tesla T4 with 15001MiB memory

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
When using TF-TRT optimized graph to do inference, it only works as expected when batch size >=7(I tested batch size from 1-16). And the result is completely wrong when batch size <7
**Describe the expected behavior**
Small batch size should also give me the correct result since my original un-optimized graph can handle small batch size.
**Code to reproduce the issue**
Setup according to  https://github.com/tensorflow/tensorrt/tree/master/tftrt/examples/object_detection:
```
# in path/to/tftrt/examples/object_detection/
import tensorflow as tf
from tensorflow.python.compiler.tensorrt import trt_convert as trt
import cv2
from collections import namedtuple
from PIL import Image
import numpy as np
import time
import json
import subprocess
import os
import glob
from tftrt.examples.object_detection.graph_utils import force_nms_cpu as f_force_nms_cpu
from tftrt.examples.object_detection.graph_utils import replace_relu6 as f_replace_relu6
from tftrt.examples.object_detection.graph_utils import remove_assert as f_remove_assert

def optimize_model(frozen_graph,
                   use_trt=True,
                   force_nms_cpu=True,
                   replace_relu6=True,
                   remove_assert=True,
                   precision_mode='FP32',
                   minimum_segment_size=2,
                   max_workspace_size_bytes=1 << 32,
                   maximum_cached_engines=100,
                   calib_images_dir=None,
                   num_calib_images=None,
                   calib_batch_size=1,
                   calib_image_shape=None,
                   output_path=None):
    #same function copied from  path/to/tftrt/examples/object_detection/object_detection.py#L328
    pass
# optimized a customed frozen graph
frozen_graph_path = 'path/to/frozen_graph.pb'
frozen_graph = tf.GraphDef()
with open(frozen_graph_path, 'rb') as f:
    frozen_graph.ParseFromString(f.read())
frozen_graph = optimize_model(
    frozen_graph,
    force_nms_cpu=False,
    replace_relu6=True,
    remove_assert=True,
    use_trt=True,
    precision_mode="FP16",
    max_workspace_size_bytes=17179869184,
    output_path='./trt_frozen_graph.pb'
)

# run inference
frozen_graph_path = './trt_frozen_graph.pb'
frozen_graph = tf.GraphDef()
with open(frozen_graph_path, 'rb') as f:
    frozen_graph.ParseFromString(f.read())

# images = [bs, h, w, 3]
INPUT_NAME = 'input'
BOXES_NAME = 'output/boxes'
CLASSES_NAME = 'output/labels'
SCORES_NAME = 'output/scores'
NUM_DETECTIONS_NAME = 'output/num_detections'
with tf.Graph().as_default() as tf_graph:
    with tf.Session(config=tf_config) as tf_sess:
        tf.import_graph_def(frozen_graph, name='')
        tf_input = tf_graph.get_tensor_by_name(INPUT_NAME + ':0')
        tf_boxes = tf_graph.get_tensor_by_name(BOXES_NAME + ':0')
        tf_classes = tf_graph.get_tensor_by_name(CLASSES_NAME + ':0')
        tf_scores = tf_graph.get_tensor_by_name(SCORES_NAME + ':0')
        tf_num_detections = tf_graph.get_tensor_by_name(
            NUM_DETECTIONS_NAME + ':0')
        boxes, classes, scores, num_detections = tf_sess.run(
                    [tf_boxes, tf_classes, tf_scores, tf_num_detections],
                    feed_dict={tf_input: batch_images})
```
**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.
My frozen graph can be download at https://drive.google.com/open?id=1s_laMhRw8GC6I9brQjn6apKTfhWe734J
```
WARNING:tensorflow:From /notebooks/tensorrt/tftrt/examples/object_detection/graph_utils.py:31: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.
WARNING:tensorflow:From /notebooks/tensorrt/tftrt/examples/object_detection/graph_utils.py:31: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

INFO:tensorflow:Linked TensorRT version: (6, 0, 1)
INFO:tensorflow:Loaded TensorRT version: (6, 0, 1)
INFO:tensorflow:Running against TensorRT version 6.0.1
graph_size(MB)(native_tf): 54.5
graph_size(MB)(trt): 106.0
num_nodes(native_tf): 10992
num_nodes(tftrt_total): 10156
num_nodes(trt_only): 290
time(s) (trt_conversion): 15.8726
```

**Comment by ArtificialNotImbecile** [comment]
It seems that `tf.image.combined_non_max_suppression()` is problematic after optimization, since if i change to batch size 1 and use `tf.image.non_max_suppression()` , the result is what I expected.

**Comment by jvishnuvardhan** [comment]
@ArtificialNotImbecile Can you please try `TF1.15` and let us know whether it resolved or not. Thanks!

**Comment by ArtificialNotImbecile** [comment]
> @ArtificialNotImbecile Can you please try `TF1.15` and let us know whether it resolved or not. Thanks!

I can not optimize the graph in `tensorflow=1.15.0`, it breaks my jupyter notebook every time I call the `trt.TrtGraphConverter()` function. I'll report the result If I can get the optimization work in `TF1.15`.

**Comment by aaroey** [comment]
@pooyadavoodi any ideas?

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.
