### ISSUE TITLE
ValueError: Unknown layer: DenseFeatures for tensorflow2.0

### ISSUE THREAD

**Issue by muzixizhu** [tensorflow/tensorflow#34189]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):Y
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):Mac
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):N
- TensorFlow version (use command below):2.0.0(stable)
- Python version:3.7.3
- Bazel version (if compiling from source):Y/N
- GCC/Compiler version (if compiling from source):Y/N
- CUDA/cuDNN version:N
- GPU model and memory:N

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
loading a saved .h5 model which includes a DenseFeatures Layer fails:
ValueError: Unknown layer: DenseFeatures

**Describe the expected behavior**
model is loading, and i can use the pre_trained model for online service

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.
import pandas as pd

# pip install -q tensorflow==2.0.0-alpha0
import tensorflow as tf
from tensorflow import feature_column
from tensorflow.keras import layers
from sklearn.model_selection import train_test_split

URL = 'https://storage.googleapis.com/applied-dl/heart.csv'
dataframe = pd.read_csv(URL)
train, test = train_test_split(dataframe, test_size=0.2)
train, val = train_test_split(train, test_size=0.2)

# A utility method to create a tf.data dataset from a Pandas Dataframe
def df_to_dataset(dataframe, shuffle=True, batch_size=32):
  dataframe = dataframe.copy()
  labels = dataframe.pop('target')
  ds = tf.data.Dataset.from_tensor_slices((dict(dataframe), labels))
  if shuffle:
    ds = ds.shuffle(buffer_size=len(dataframe))
  ds = ds.batch(batch_size)
  return ds

feature_columns = []

# numeric cols
for header in ['age', 'trestbps', 'chol', 'thalach', 'oldpeak', 'slope', 'ca']:
  feature_columns.append(feature_column.numeric_column(header))

feature_layer = tf.keras.layers.DenseFeatures(feature_columns)

batch_size = 32
train_ds = df_to_dataset(train, batch_size=batch_size)
val_ds = df_to_dataset(val, shuffle=False, batch_size=batch_size)
test_ds = df_to_dataset(test, shuffle=False, batch_size=batch_size)

model = tf.keras.Sequential([
  feature_layer,
  layers.Dense(128, activation='relu'),
  layers.Dense(128, activation='relu'),
  layers.Dense(1, activation='sigmoid')
])

model.compile(optimizer='adam',
              loss='binary_crossentropy')

model.fit(train_ds, 
          validation_data=val_ds, 
          epochs=5)

model.save('my_model.h5')
from tensorflow import keras
new_model = keras.models.load_model('my_model.h5')

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

    ValueError: ('We expected a dictionary here. Instead we got: ', <tf.Tensor 'Placeholder:0' shape=(None,) dtype=float32>)

**Comment by muzixizhu** [comment]
I also met the Error   Unknown layer: DenseFeatures for tensorflow2.0 in issue https://github.com/tensorflow/tensorflow/issues/27008, but i have not seen any solutions to this issue ,

**Comment by gadagashwini** [comment]
@muzixizhu, I tried replicating the issue on colab with Tf 2.0 but got a different error. Please take a look at colab gist [here](https://colab.sandbox.google.com/gist/gadagashwini/31c284ef598a07e9d96b734d7e3a81c3/untitled256.ipynb).
Thanks!

**Comment by muzixizhu** [comment]
change your code for my_input_fn()


  if shuffle:
    ds = ds.shuffle(buffer_size=len(dataframe))
    ds = ds.batch(batch_size)


it should be:
if shuffle:
ds = ds.shuffle(buffer_size=len(dataframe))
ds = ds.batch(batch_size)






At 2019-11-13 16:17:54, "gadagashwini" <notifications@github.com> wrote:


@muzixizhu, I tried replicating the issue on colab with Tf 2.0 but got a different error. Please take a look at colab gist here.
Thanks!

**Comment by muzixizhu** [comment]
sorry for my paste, the original code for df_to_dataset() is 
if shuffle:
    ds = ds.shuffle(buffer_size=len(dataframe))
ds = ds.batch(batch_size)
return ds

**Comment by muzixizhu** [comment]
sorry for my paste, the original code for df_to_dataset() is
if shuffle:
    ds = ds.shuffle(buffer_size=len(dataframe))
ds = ds.batch(batch_size)
return ds

**Comment by gadagashwini** [comment]
Issue is replicating on colab with Tensorflow 2.0.
Please see the gist [here](https://colab.sandbox.google.com/gist/gadagashwini/409e82576732d06e907d0042b070dae9/untitled256.ipynb). Thanks!

**Comment by ymodak** [comment]
The script executes successfully if you save/load the model in ```tf``` format.

**Comment by ravikyram** [comment]
I have tried in colab with TF version 2.2, nightly version(2.3.0-dev20200612) .I am seeing the below error message(`ValueError: You are trying to load a weight file containing 3 layers into a model with 0 layers.`).Please, find the gist [here](https://colab.research.google.com/gist/ravikyram/666a1221a9d12cc80f58ba38be70cd83/untitled15.ipynb).Thanks!

**Comment by sushreebarsa** [comment]
Was able to replicate the issue in TF 2.6.0-dev20210529,please find the gist [here ](https://colab.research.google.com/gist/sushreebarsa/82adca7cac43fd8b8250962ab7fcd3f1/untitled78.ipynb#scrollTo=tkDyLiyv-gep)..Thanks !

**Comment by sanatmpa1** [comment]
@muzixizhu,

I modified your code to remove .h5 extension while saving the model and it worked without any errors. Please take a look at the [gist here](https://colab.research.google.com/gist/sanatmpa1/5156de008111bff37c238b87a4fb7e00/34189.ipynb). Thanks
