### ISSUE TITLE
tf.size() has no documentation

### ISSUE THREAD

**Issue by danijar** [tensorflow/tensorflow#34194]
https://www.tensorflow.org/api_docs/python/tf/size

Example: "Returns the number of elements in the tensor. It equals the length of the flattened tensor."

**Comment by kshitijaggrwl** [comment]
@danijar, I want to contribute to this issue. Can you help me in doing so?
I am completely new to this world of open source.

**Comment by danijar** [comment]
Sorry, I can't assist you with the workflow. [CONTRIBUTING.md](https://github.com/tensorflow/tensorflow/blob/master/CONTRIBUTING.md) would be a good place to get started.

**Comment by copperwiring** [comment]
@lamberta @goldiegadde Is this issue being worked on? If not, can I submit a PR?

**Comment by copperwiring** [comment]
Submitted a PR @danijar @lamberta

**Comment by lamberta** [comment]
Thank you @copperwiring 🚀
