### ISSUE TITLE
TF2.1 build from source failure

### ISSUE THREAD

**Issue by sbushmanov** [tensorflow/tensorflow#34191]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: `No`
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: `Linux Ubuntu 18.0.4`
- **Python version tried**: `3.6/3.7`
- **gcc/g++**: `7.4.0 (Ubuntu 7.4.0-1ubuntu1~18.04.1)`
- **TensorFlow installed from (source or binary)**: `source`
- **TensorFlow version (use command below)**: `2.1`
git clone https://github.com/tensorflow/tensorflow tensorflow  -b r2.1
- **Bazel version (if compiling from source)**: `0.29.1`
Build label: 0.29.1
Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Tue Sep 10 13:44:39 2019 (1568123079)
- **CUDA/cuDNN version**: `V10.1.243/7.6.1`
- **GPU model and memory**: `GeForce GTX 1080 TX 12Gb`
- **Exact command to reproduce**:

> bazel build --linkopt='-lrt' --copt=-mavx --copt=-mavx2 --copt=-mfma --copt=-mfpmath=both --copt=-mavx --copt=-msse4.1 --copt=-msse4.2 --config=noaws --config=nohdfs --config=nonccl --cxxopt="-D_GLIBCXX_USE_CXX11_ABI=0" --config=cuda -k //tensorflow/tools/pip_package:build_pip_package --verbose_failures 2>&1 | tee bazel.log

### Describe the problem
Failed to build from source TF2.1 with CUDA (though able to builf TF2.0 without a problem)

### Source code / logs

Config (all default options except enabling CUDA):

(base) sergey@sergey-Bionic:~/tensorflow$ ./configure
WARNING: --batch mode is deprecated. Please instead explicitly shut down your Bazel server using the command "bazel shutdown".
You have bazel 0.29.1 installed.
Please specify the location of python. [Default is /home/sergey/anaconda3/bin/python]: 

Found possible Python library paths:
  /home/sergey/anaconda3/lib/python3.6/site-packages
Please input the desired Python library path to use.  Default is [/home/sergey/anaconda3/lib/python3.6/site-packages]

Do you wish to build TensorFlow with XLA JIT support? [Y/n]: 
XLA JIT support will be enabled for TensorFlow.

Do you wish to build TensorFlow with OpenCL SYCL support? [y/N]: 
No OpenCL SYCL support will be enabled for TensorFlow.

Do you wish to build TensorFlow with ROCm support? [y/N]: 
No ROCm support will be enabled for TensorFlow.

Do you wish to build TensorFlow with CUDA support? [y/N]: y
CUDA support will be enabled for TensorFlow.

Do you wish to build TensorFlow with TensorRT support? [y/N]: 
No TensorRT support will be enabled for TensorFlow.

Found CUDA 10.1 in:
    /usr/local/cuda/lib64
    /usr/local/cuda/include
Found cuDNN 7 in:
    /usr/lib64
    /usr/include

Please specify a list of comma-separated CUDA compute capabilities you want to build with.
You can find the compute capability of your device at: https://developer.nvidia.com/cuda-gpus.
Please note that each additional compute capability significantly increases your build time and binary size, and that TensorFlow only supports compute capabilities >= 3.5 [Default is: 6.1]: 

Do you want to use clang as CUDA compiler? [y/N]: 
nvcc will be used as CUDA compiler.

Please specify which gcc should be used by nvcc as the host compiler. [Default is /usr/bin/gcc]: 

Please specify optimization flags to use during compilation when bazel option "--config=opt" is specified [Default is -march=native -Wno-sign-compare]: 

Would you like to interactively configure ./WORKSPACE for Android builds? [y/N]: 
Not configuring the WORKSPACE for Android builds.

### Example of Bazel error messages:

> ERROR: /home/sergey/tensorflow/tensorflow/python/BUILD:2640:1: Couldn't build file tensorflow/python/gen_tpu_ops_py_wrappers_cc: Linking of rule '//tensorflow/python:gen_tpu_ops_py_wrappers_cc' failed (Exit 1)
--
bazel-out/host/bin/tensorflow/core/protobuf/tpu/libtpu_embedding_output_layout_proto_cc.lo(tpu_embedding_output_layout.pb.o):(.data.rel.ro._ZTVN10tensorflow3tpu24TPUEmbeddingOutputLayoutE[_ZTVN10tensorflow3tpu24TPUEmbeddingOutputLayoutE]+0x60): undefined reference to `google::protobuf::Message::CheckTypeAndMergeFrom(google::protobuf::MessageLite const&)'
bazel-out/host/bin/tensorflow/core/protobuf/tpu/libtpu_embedding_output_layout_proto_cc.lo(tpu_embedding_output_layout.pb.o):(.data.rel.ro._ZTVN10tensorflow3tpu24TPUEmbeddingOutputLayoutE[_ZTVN10tensorflow3tpu24TPUEmbeddingOutputLayoutE]+0x80): undefined reference to `google::protobuf::MessageLite::SerializeWithCachedSizesToArray(unsigned char*) const'
bazel-out/host/bin/tensorflow/core/protobuf/tpu/libtpu_embedding_output_layout_proto_cc.lo(tpu_embedding_output_layout.pb.o):(.data.rel.ro._ZTVN10tensorflow3tpu24TPUEmbeddingOutputLayoutE[_ZTVN10tensorflow3tpu24TPUEmbeddingOutputLayoutE]+0xb0): undefined reference to `google::protobuf::Message::DiscardUnknownFields()'
bazel-out/host/bin/tensorflow/core/protobuf/tpu/libtpu_embedding_output_layout_proto_cc.lo(tpu_embedding_output_layout.pb.o):(.data.rel.ro._ZTVN10tensorflow3tpu24TPUEmbeddingOutputLayoutE[_ZTVN10tensorflow3tpu24TPUEmbeddingOutputLayoutE]+0xb8): undefined reference to `google::protobuf::Message::SpaceUsedLong() const'
collect2: error: ld returned 1 exit status
ERROR: /home/sergey/tensorflow/tensorflow/python/BUILD:2359:1: Couldn't build file tensorflow/python/gen_checkpoint_ops_py_wrappers_cc: Linking of rule '//tensorflow/python:gen_checkpoint_ops_py_wrappers_cc' failed (Exit 1)
--
bazel-out/host/bin/tensorflow/core/libcheckpoint_ops_op_lib.lo(checkpoint_ops.o): In function `__static_initialization_and_destruction_0(int, int) [clone .constprop.45]':
checkpoint_ops.cc:(.text.startup._Z41__static_initialization_and_destruction_0ii.constprop.45+0x19b): undefined reference to `tensorflow::register_op::OpDefBuilderReceiver::OpDefBuilderReceiver(tensorflow::register_op::OpDefBuilderWrapper<true> const&)'
checkpoint_ops.cc:(.text.startup._Z41__static_initialization_and_destruction_0ii.constprop.45+0x3ff): undefined reference to `tensorflow::OpDefBuilder::SetIsStateful()'
checkpoint_ops.cc:(.text.startup._Z41__static_initialization_and_destruction_0ii.constprop.45+0x424): undefined reference to `tensorflow::register_op::OpDefBuilderReceiver::OpDefBuilderReceiver(tensorflow::register_op::OpDefBuilderWrapper<true> const&)'
collect2: error: ld returned 1 exit status
ERROR: /home/sergey/tensorflow/tensorflow/python/BUILD:2339:1: Couldn't build file tensorflow/python/gen_audio_ops_py_wrappers_cc: Linking of rule '//tensorflow/python:gen_audio_ops_py_wrappers_cc' failed (Exit 1)
--
audio_ops.cc:(.text.startup._Z41__static_initialization_and_destruction_0ii.constprop.63+0x140): undefined reference to `tensorflow::register_op::OpDefBuilderReceiver::OpDefBuilderReceiver(tensorflow::register_op::OpDefBuilderWrapper<true> const&)'
audio_ops.cc:(.text.startup._Z41__static_initialization_and_destruction_0ii.constprop.63+0x250): undefined reference to `tensorflow::register_op::OpDefBuilderReceiver::OpDefBuilderReceiver(tensorflow::register_op::OpDefBuilderWrapper<true> const&)'
audio_ops.cc:(.text.startup._Z41__static_initialization_and_destruction_0ii.constprop.63+0x386): undefined reference to `tensorflow::register_op::OpDefBuilderReceiver::OpDefBuilderReceiver(tensorflow::register_op::OpDefBuilderWrapper<true> const&)'
audio_ops.cc:(.text.startup._Z41__static_initialization_and_destruction_0ii.constprop.63+0x562): undefined reference to `tensorflow::register_op::OpDefBuilderReceiver::OpDefBuilderReceiver(tensorflow::register_op::OpDefBuilderWrapper<true> const&)'
collect2: error: ld returned 1 exit status

### Full bazel error log see attached.
[bazel_error.l og](https://github.com/tensorflow/models/files/3834933/bazel_error.log)

**Comment by alanpurple** [comment]
same here

I've never succeeded build since master got 2.0.0 ( before I successfully build 2.0.0 in r2.0 branch )

**Comment by chris0914** [comment]
Same error here but under python 3.7
Tried with bazel 0.27.1 and 0.29.1. Used the r2.1 branch, while the r2.0 branch worked fine for me last time. Did some of you manage to compile or is it a bug?

**Comment by sbushmanov** [comment]
It would be nice if someone who succeeded with building TF2.1 shared their config (CUDA and Bazel versions at least) and cast some light if building with CUDA 10.2 is possible.

**Comment by itemko** [comment]
@sbushmanov 
It seems we might observe something similar 1-2 weeks ago after default Bazel version upgrade (possibly related issues: https://github.com/tensorflow/tensorflow/issues/34117 https://github.com/tensorflow/tensorflow/issues/34222). About a week ago the issue has disappeared but we changed build environment to CUDA 10.1 and Bazel 1.1.0 (installed automatically via [Bazelisk](https://github.com/bazelbuild/bazelisk) as recommended in the [TensorFlow building instructions](https://www.tensorflow.org/install/source#install_bazel)). We use TensorFlow master branch.
For TensorFlow building with CUDA 10.2 I can refer to [NGC TensorFlow docker image](https://ngc.nvidia.com/catalog/containers/nvidia:tensorflow) - there're scripts to build TensorFlow inside (see /opt/tensorflow/, with CUDA 10.2).
PS: You can trigger [Mellanox TensorFlow CI](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/tools/ci_build#mellanox-tensorflow-ci) to get build log file with settings we use.

**Comment by chris0914** [comment]
Am I correct, that the master branch is still TensorFlow 1.15 and not the nightly TensorFlow 2.1 @itemko?

**Comment by powderluv** [comment]
add --noincompatible_do_not_split_linking_cmdline to bazel flags

**Comment by sbushmanov** [comment]
Finally successfully built tf 2.1.0 rc0 with CUDA 10.2, Bazel 0.29.1 and
https://github.com/tensorflow/tensorflow/issues/34429#issuecomment-557408498

```
INFO: Elapsed time: 10509.148s, Critical Path: 317.59s
INFO: 25874 processes: 25874 local.
INFO: Build completed successfully, 40666 total actions
INFO: Build completed successfully, 40666 total actions
```

**Comment by amahendrakar** [comment]
> Finally successfully built tf 2.1.0 rc0 with CUDA 10.2, Bazel 0.29.1

@sbushmanov,
Closing this issue as it is resolved. Please feel free to re-open if mistaken. Thanks!
