### ISSUE TITLE
TypeError: Parameter to MergeFrom() must be instance of same class: expected tensorboard.SummaryMetadata got tensorflow.SummaryMetadata.

### ISSUE THREAD

**Issue by sbj028** [tensorflow/tensorflow#34190]
Hey, I'm trying to use Hyperparameter tuning with the HParams Dashboard. Trying to follow the guidelines on https://www.tensorflow.org/tensorboard/hyperparameter_tuning_with_hparams 
although I'm using Pytorch instead of a Keras model. 

To start with I'm only focusing on one hyperparameter (lambda_L1), following the tutorial this is what I've got:   

```
HP_LAMBDA_L1 = hp.HParam('lambda_L1', hp.IntInterval(0, 200))

""""Preparations for HP tuning"""
train_writer = tf.summary.create_file_writer(opt.log_dir) 
with train_writer.as_default():
    hp.hparams_config(
        hparams=[HP_LAMBDA_L1],
        metrics=[hp.Metric('accuracy', display_name='Accuracy')],  # TODO
    )

"""For each run, log an hparams summary with the hyperparameters and final accuracy:"""
def run(run_dir, hparams):
    with tf.summary.create_file_writer(run_dir).as_default():
        hp.hparams(hparams)  # record the values used in this trial
        mse_accuracy = train_model(hparams)
        tf.summary.scalar('accuracy', mse_accuracy, step=1)

run_num = 0
for lambda_L1 in np.linspace(HP_LAMBDA_L1.domain.min_value,
                                 HP_LAMBDA_L1.domain.max_value, 5,):
    hparams = {
        HP_LAMBDA_L1: lambda_L1
    }
    run_name = "run-%d" % run_num
    print('--- Starting trial: %s' % run_name)
    print({h.name: hparams[h] for h in hparams})
    run('logs/test_lambdaL1/' + run_name, hparams)
    run_num += 1
```
The `train_model()  ` is in Pytorch. I'm using `!pip install -q tensorflow==2.0.0-alpha0 ` in Google colab wich hasn't given me any trubles before. 

The error I've got: 

`Traceback (most recent call last):
  File "/content/drive/My Drive/Colab Notebooks/pix2pix_HPtuning/train_tb_HPtuning.py", line 69, in <module>
    metrics=[hp.Metric('accuracy', display_name='Accuracy')],  # TODO
  File "/usr/local/lib/python3.6/dist-packages/tensorboard/plugins/hparams/summary_v2.py", line 135, in hparams_config
    time_created_secs=time_created_secs,
  File "/usr/local/lib/python3.6/dist-packages/tensorboard/plugins/hparams/summary_v2.py", line 177, in hparams_config_pb
    plugin_data_pb2.HParamsPluginData(experiment=experiment),
  File "/usr/local/lib/python3.6/dist-packages/tensorboard/plugins/hparams/summary_v2.py", line 250, in _summary_pb
    summary.value.add(tag=tag, metadata=summary_metadata)
TypeError: Parameter to MergeFrom() must be instance of same class: expected tensorboard.SummaryMetadata got tensorflow.SummaryMetadata.`

Does anyone know how to solve the issue?

**Comment by sbj028** [comment]
As an additional note: 
I've also tried the following for tensorflow: 
```
try:
  # %tensorflow_version only exists in Colab.
  %tensorflow_version 2.x
except Exception:
  pass
```
Which also gives me errors, but these complain that there's something wrong in `train_model(hparams)` which I know can't be the case since `train_model` works perfectly fine without the HyperParameter tuning.

**Comment by oanush** [comment]
@sbj028 ,
Thank you for reporting the issue, can you please share the complete code to reproduce the error reported here? 
I also see that there is no issue faced in colab running on 2.0alpha version. Please try using latest  `tf-2.0` or` tf -nightly `version and check if the issue is being faced. Thanks!

**Comment by sbj028** [comment]
Thank you for the answer. 

I've now tried the following:
`!pip install tensorflow-gpu==2.0`
or
`try:
  %tensorflow_version 2.x
except Exception:
  pass`
or
`!pip install tf-nightly`
or
`!pip install tf-nightly-2.0-preview`
or
`!pip install tensorflow-gpu`
which all work fine using Google Colab. 

The following version: `!pip install -q tensorflow==2.0.0-alpha0 ` still gives me

> TypeError: Parameter to MergeFrom() must be instance of same class: expected tensorboard.SummaryMetadata got tensorflow.SummaryMetadata.

mentioned above. But since I'm able to continue trying out the hyperparameter tuning using all other versions for tensorflow I will close this issue.
 
The `train_model(hparams)` calls the Pix2pix script `train.py` that can be found at [https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix](url) and passing the hparams that I'm interested in. 

Thanks!
