### ISSUE TITLE
keras.backend.function with learning phase gives AttributeError

### ISSUE THREAD

**Issue by StefReck** [tensorflow/tensorflow#34201]
I'm using the following script from the keras docu page to get the output of an intermediate layer in training phase:
``` python
from tensorflow.keras import backend as K

K.function([model.layers[0].input, K.learning_phase()],
           [model.layers[1].output])
```

Which throws this error:
``` python
AttributeError                            Traceback (most recent call last)
<ipython-input-2-d35d4dbf76cf> in <module>
      2
      3 K.function([model.layers[0].input, K.learning_phase()],
----> 4            [model.layers[1].output])

/home/woody/capn/mppi013h/conda_envs/orca_cpu_env/lib/python3.6/site-packages/tensorflow_core/python/keras/backend.py in function(inputs, outputs, updates, name, **kwargs)
   3771       raise ValueError('Session keyword arguments are not support during '
   3772                        'eager execution. You passed: %s' % (kwargs,))
-> 3773     return EagerExecutionFunction(inputs, outputs, updates=updates, name=name)
   3774
   3775   if kwargs:

/home/woody/capn/mppi013h/conda_envs/orca_cpu_env/lib/python3.6/site-packages/tensorflow_core/python/keras/backend.py in __init__(self, inputs, outputs, updates, name)
   3668             add_sources=True,
   3669             handle_captures=True,
-> 3670             base_graph=source_graph)
   3671
   3672         inputs = [lifted_map[i] for i in inputs]

/home/woody/capn/mppi013h/conda_envs/orca_cpu_env/lib/python3.6/site-packages/tensorflow_core/python/eager/lift_to_graph.py in lift_to_graph(tensors, graph, sources, disallowed_placeholders, add_sources, handle_captures, base_graph, op_map)
    247   # Check that the initializer does not depend on any placeholders.
    248   sources = object_identity.ObjectIdentitySet(sources or [])
--> 249   visited_ops = set([x.op for x in sources])
    250   op_outputs = collections.defaultdict(set)
    251

/home/woody/capn/mppi013h/conda_envs/orca_cpu_env/lib/python3.6/site-packages/tensorflow_core/python/eager/lift_to_graph.py in <listcomp>(.0)
    247   # Check that the initializer does not depend on any placeholders.
    248   sources = object_identity.ObjectIdentitySet(sources or [])
--> 249   visited_ops = set([x.op for x in sources])
    250   op_outputs = collections.defaultdict(set)
    251

AttributeError: 'int' object has no attribute 'op'
``` 
Using this simple model:
``` python
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Activation

model = Sequential()
model.add(Dense(32, input_dim=784))
model.add(Activation('relu'))
``` 
If I use keras instead of tensorflow.keras, it works fine. 

- TensorFlow version: 2.0.0
- Python version: 3.6.8
`

**Comment by gadagashwini** [comment]
Issue  is replicating with Tensorflow 2.0.
Please see the gist [here](https://colab.sandbox.google.com/gist/gadagashwini/ca116dc97ea159632f759757e5c235a9/untitled257.ipynb). Thanks!

**Comment by kaibrach** [comment]
Is there any solution for that issue?

**Comment by superJen99** [comment]
DIY it... write all of the functions and objects without using Tensorflow

**Comment by kaibrach** [comment]
The only solution I found is to disable eager execution on startup.
`tf.compat.v1.disable_eager_execution()`

Afterwards 
```python
  f = K.function([self.model.layers[0].input, K.learning_phase()],
                       [self.model.layers[-1].output])
```

can be used as usual

**Comment by kaibrach** [comment]
I found a way (workaround) how the `K.function()` can be executed with eager_execution enabled.
I tried this with **TF 2.1 Version**.

We need to import private functions from `tensorflow.python.keras` instead of `tf.keras.backend` to get access to `symbolic_learning_phase()`. 

```python
        f = K.function([self.model.layers[0].input, 
                        #K.learning_phase()],
                        K.symbolic_learning_phase()], # Workaround (maybe slowdown)
                        [self.model.output])
    
        ''' Run the function for the number of mc_samples with learning_phase flag True=training'''
        Yt_hat = np.array([f((X_test, True))[0] for _ in range(mc_samples)])
```

This workaround is ok for development but take care to enter private functions!
`tf.keras` (Public)
`tf.pyhton.keras` (Private)

**Comment by Jordy-VL** [comment]
I successfully used the below until TF 2.2, thanks! 

However, in TF 2.3 this functionality is broken. 
Error raised: 
```
*** ValueError: Input tensors to a Functional must come from `tf.keras.Input`. Received: Tensor("keras_learning_phase:0", shape=(), dtype=bool) (missing previous layer metadata).

```

> I found a way (workaround) how the `K.function()` can be executed with eager_execution enabled.
> I tried this with **TF 2.1 Version**.
> 
> We need to import private functions from `tensorflow.python.keras` instead of `tf.keras` to get access to `symbolic_learning_phase()`.
> 
> ```python
>         f = K.function([self.model.layers[0].input, 
>                         #K.learning_phase()],
>                         K.symbolic_learning_phase()], # Workaround (maybe slowdown)
>                         [self.model.output])
>     
>         # Run the function for the number of mc_samples with learning_phase enabled
>         Yt_hat = np.array([f((X_test, True))[0] for _ in range(mc_samples)])
> ```
> 
> This workaround is ok for development but **DO NOT USE** private functions when writing custom functions/classes!
> 
> `tf.keras` (Public)
> `tf.pyhton.keras` (Private)

**Comment by superJen99** [comment]
This will be useful, thanks!

**Comment by Jordy-VL** [comment]
Any update? It is blocking factor for upgrading to TF2.3

**Comment by kaibrach** [comment]
For Tensorflow 2.**3** you have to do the following for using the Keras Backend function in eager execution mode:

```python
        from tensorflow.python.keras.backend import eager_learning_phase_scope
        f = K.function([self.model.layers[0].input],      
                              [self.model.output])
    
        # Run the function for the number of mc_samples with learning_phase enabled
        with eager_learning_phase_scope(value=1): # 0=test, 1=train
            Yt_hat = np.array([f((X))[0] for _ in range(mc_samples)])
```

**Comment by Jordy-VL** [comment]
@kaibrach Life-Saver! 

Thank you very much :)

**Comment by jvishnuvardhan** [comment]
@StefReck This is an old issue. I think this was resolved in recent `tf-nightly`. I have updated the code little bit to comply the  modifications in TF and Keras. Please check the [gist here](https://colab.research.google.com/gist/jvishnuvardhan/95aec95cf616daacd7f5470b8b21a7a1/untitled990.ipynb).  You can find complete code [here](https://github.com/jvishnuvardhan/Stackoverflow_Questions/blob/master/mnist_getting_output_of_each_layer.ipynb) on accessing intermediate layers of a model.

Please verify and let us know if the issue persists. Thanks!
