### ISSUE TITLE
Running Bidirectional RNN cells on parallel

### ISSUE THREAD

**Issue by ASDen** [tensorflow/tensorflow#3420]
is there any method to run Bidirectional RNNs on parallel as they should (they have no dependency on each other)
I noticed that stacking 2 LSTM layer has the exact same performance as bidirection LSTM (BLSTM)
even 4 stacked LSTM has same performance as 2 parallel BLSTMs (which simply means  that TF runtime doesn't parallelize BLSTMs at all, I also notice the same behavior on both the CPU and the GPU)

Note: I am using small cells that are trivial to fit simultaneously

Thanks,

**Comment by concretevitamin** [comment]
Could you provide your reproducible code snippet?

**Comment by ASDen** [comment]
This is somewhat lengthy, as I take the chance to also demonstrate a speed problem with dynamic_rnn when specifying sequence_length
```python
import tensorflow as tf
from tensorflow.python.ops  import rnn, rnn_cell,array_ops
import numpy as np
import time

batch_size = 128
n_input = 20
n_steps = 50
n_hidden = 40

np.random.seed(1234)
tf.set_random_seed(1234)

data = tf.constant(np.random.uniform(-1.0, 1.0, [batch_size,n_steps,n_input]), dtype=tf.float32)
sql  = tf.constant([n_steps] * batch_size, tf.int64)
lstm_cell = rnn_cell.LSTMCell(num_units=n_hidden, state_is_tuple=True)

def stacked_lstm():
    mlstm_cell = rnn_cell.MultiRNNCell([lstm_cell] * 2, state_is_tuple=True)
    return rnn.dynamic_rnn(mlstm_cell, data, dtype=tf.float32,sequence_length=sql)[0]

def stacked_lstm_no_sql():
    mlstm_cell = rnn_cell.MultiRNNCell([lstm_cell] * 2, state_is_tuple=True)
    return rnn.dynamic_rnn(mlstm_cell, data, dtype=tf.float32)[0]

def bi_lstm():
    return rnn.bidirectional_dynamic_rnn(lstm_cell, lstm_cell, data, sequence_length=sql, dtype=tf.float32)[0]

def bi_lstm_no_sql():
    y1 = rnn.dynamic_rnn(lstm_cell, data,  dtype=tf.float32,scope='r1')[0]
    rdata = array_ops.reverse_sequence(input=data, seq_lengths=sql, seq_dim=1, batch_dim=0)
    y2 = rnn.dynamic_rnn(lstm_cell, rdata, dtype=tf.float32,scope='r2')[0]
    y2 = array_ops.reverse_sequence(input=y2, seq_lengths=sql, seq_dim=1, batch_dim=0)
    return [y1,y2]

y = stacked_lstm()
#y=stacked_lstm_no_sql()
#y = bi_lstm()
#y = bi_lstm_no_sql()

init = tf.initialize_all_variables()

config = tf.ConfigProto(
    #device_count={'GPU': 0}, #turn GPU on and off
)

with tf.Session(config=config) as sess:
    sess.run(init)
    start = time.time()
    for i in range(1000):
        sess.run(y)
        if(i%100 == 0): print "Iter : ",i*batch_size
    end = time.time()
    print "Finished!  ", (end - start)
```

when running on GTX 960, you get (i record Utilization from nvidia-setting)
stacked_lstm              : 14.11s     GPU Util:69%
stacked_lstm_no_sql : 10.49s     GPU Util:79%
bi_lstm              : 16.15s     GPU Util:65%
bi_lstm_no_sql  : 11.54s     GPU Util:75%

we note:
1) stacked_lstm is generally faster than bi_lstm (though, bi_lstm is trivial to parallelize and should be generally up to 2X faster)
2) removing sequence_length has huge impact on speed. However, I noted that the two methods (with and without sequence_length) return different results, and in my practical use cases removing sequence_length generally returns slightly worse results

what is really needed is method to allow parallel execution of independent parts of the graph like BLSTMs

**Comment by concretevitamin** [comment]
@ebrevdo: can you take a look?

@ASDen: a more accurate way to measure the running time is to wrap the results in `tf.group()`, so that the device-to-host transfer of final results is not included.

**Comment by ASDen** [comment]
@ebrevdo any thoughts here...

**Comment by ebrevdo** [comment]
When using a dynamic_rnn, there is an "execution barrier" between calls to dynamic_rnn; because of the way that data is processed at input & output to the RNN while_loop.  The bidirectional_dynamic_rnn just calls dynamic_rnn twice, much the way you do in `bi_lstm_no_sql`.  In fact, it also uses `reverse_sequence`, which *also* forms a barrier between any two RNN calls.  There's no way around `reverse_sequence`: all its inputs must be available to properly verse time according to the counts in `sequence_length`.  If you can suggest a way to improve performance or, e.g., make a simpler dynamic sequence reversal system (which does not rely on a monolithic op) then I would like to hear it.

**Comment by ASDen** [comment]
another implicit performance penalty I noticed is that when using deep LSTM networks, using MultiRNNCell instead of manual construction can be 2-3X faster (I think because it uses a single while loop)
the problem with deep BLSTMs is that you can't do them with a single cell or a single while loop (layer output dependency) which means it incurs such a huge penalty solely due to many while loops involved
any thoughts on a more "light weight" while loop ?

Note: with big output size/batch size the performance gap decreases, however the big sizes are less useful, and I do think on cards bigger than GTX 960, even the big sizes would suffer same penalty

**Comment by avostryakov** [comment]
@ebrevdo Maybe I don't understand something but is it possible to execute forward pass of dynamic_rnn on one GPU and backward pass on an another GPU. Should it be two times faster in this case?

@ASDen It looks like you made opposite conclusions. Can you clarify what is faster MultiRNNCell or manually constructed cells?

**Comment by ASDen** [comment]
@avostryakov for deep networks (e.g. 8 layers and more) MultiRNNCell can be 2-3x faster than manual construction

**Comment by avostryakov** [comment]
@ASDen Thank you! I'm just trying to make my code faster. A simple architecture with embedding layer, 2 LSTM layers with dynamic_rnn (sequence_length is None) + classification on top of last hidden state works 30% slower than the same architecture on theano+lasagne. I thought that tensorflow 0.9 was optimized enough.

**Comment by ebrevdo** [comment]
@ASDen apologies; in fact, there is no execution barrier because the following can be run in parallel:

chunk 1:
reverse x
y_rev = lstm(x_rev)
y_bak = reverse y_rev

chunk 2:
y_fw = lstm(x)

then you need to wait for both of these chunks to finish before you can concat them.

dynamic bidirectional rnn doesn't even bother with the concat - you get both pieces and can concat them if you wish.

right now, running the fw & reverse on multiple GPUs would require creating a special device setter and calling bidirectional rnn within that context.  see, e.g., the [replica_device_setter](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/training/device_setter.py) function, the result of which you would pass to tf.device.

**Comment by ebrevdo** [comment]
@avostryakov can you provide some details about the sizes of your inputs, number of frames, depth of your RNN, and cell size?

**Comment by avostryakov** [comment]
@ebrevdo Size of input: 100, Number of time steps: 400, Depth: 2-3 layers if I understood correctly, cell size (hidden state size): 400.

**Comment by ASDen** [comment]
@ebrevdo much thanks, this should solve the problem for multiple devices
but what about a single device (e.g. a single GPU) ?
as a side note, when I tried to run two different versions of my code on parallel, I notice only ~ 50% decrease in performance (e.g. when a single instance takes n seconds, running two parallel instances takes only 1.5n not 2n seconds) so this should be doable and the device has the capacity for it, but I was wondering if TF provides any mechanism for controlling this

**Comment by ebrevdo** [comment]
@avostryakov are you using MultiRNNCell?  is this unidirectional or bidirectional rnn?  you could also try using the new LSTMBlockCell in `tf.contrib.rnn` instead of the base `BasicLSTMCell`, which *may* improve your performance.  Let me know how that works for you.

**Comment by ebrevdo** [comment]
@ASDen you mean for running two replicas on the same worker in parallel?  Probably your best bet is to just run multiple python training threads and use the same session in each of them.  They can even read minibatches off the same queue.  If you're using a `Supervisor`, then you can use its `managed_session` object.

**Comment by ebrevdo** [comment]
You can also use Supervisor's loop fn to start a bunch of training threads, and synchronize their exits.  See [Supervisor](https://www.tensorflow.org/versions/r0.10/api_docs/python/train.html#Supervisor) and search for "Supervisor.loop"

**Comment by avostryakov** [comment]
@ebrevdo By the way, LSTMBlockCell didn't work together with optimizers during training as I mentioned here: https://github.com/tensorflow/tensorflow/pull/2002#issuecomment-239411957 Was it fixed already? 

My original question was simple: Should it be two times faster if I execute forward pass on one GPU and backward pass on another comparing to do it on one GPU. No MultiRNNCell. Input for both layers is the same. Add hidden states of both passes together in the end.

**Comment by ebrevdo** [comment]
@avostryakov almost.  the hidden states, if you concatenate them, will have to run on one of the GPUs, and this will require a copy.  however, this is trivial compared to the hard work the LSTM cells are doing in the forwards & backwards passes.  So the larger your cell batch size, depth, and number of iterations, the closer the performance should get to 2x.

**Comment by ebrevdo** [comment]
Does that resolve your issue?

**Comment by avostryakov** [comment]
@ebrevdo If you ask me then yes, you answered my question. Thank you!

**Comment by ebrevdo** [comment]
Great! For any orthogonal questions we can open a different, more focused, issue.
