### ISSUE TITLE
C installation still suggests 1.14.0 download

### ISSUE THREAD

**Issue by aronatkins** [tensorflow/tensorflow#34205]
## URL(s) with the issue:

https://www.tensorflow.org/install/lang_c

## Description of issue (what needs changing):

The download instructions link to 1.14.0 libraries rather than 1.15.0; the 1.15.0 libraries appear to exist and 1.15.0 is a release according to https://github.com/tensorflow/tensorflow/releases

**Comment by EvilTrtl** [comment]
I've changed them to the 1.15.0 ones #1216

**Comment by EvilTrtl** [comment]
tensorflow/docs#1216

**Comment by EvilTrtl** [comment]
tensorflow/docs#1216

**Comment by lamberta** [comment]
Fix merged. tensorflow.org will updated on next site push.
Thanks!
