### ISSUE TITLE
Incorrect predictions occur when using a custom quantized model

### ISSUE THREAD

**Issue by on-device-ai** [tensorflow/tensorflow#34217]
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 16.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: STM32F746 Discovery kit
- TensorFlow installed from (source or binary):binary
- TensorFlow version (use command below):2.0.0
- Python version:3.7.4
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:10.0
- GPU model and memory:Quadro P4000 8GB

This is a issue with TensorFlow Lite for Microcontrollers. Incorrect predictions occur when my ClassifyHeartbeats ( https://github.com/on-device-ai/ClassifyHeartbeats/tree/quantized_model/ ) project uses the quantized model; however, if I use a no quantized model, it is normal predictions.

**Comment by MeghnaNatraj** [comment]
On running the jupyter notebook [here](https://github.com/on-device-ai/ClassifyHeartbeats/blob/quantized_model/tensorflow/classify_heartbeats_cnn.ipynb), the predictions are the same for the the tflite models (tflite and quantized_tflite). 

Is the issue only occurring when you run it on the STM32F746 Discovery kit?

Thank you providing a well documented repository. Is it also possible to provide instructions you've used for running your C model file on the microcontroller?

**Comment by on-device-ai** [comment]
Yes, the issue happens the TensorFlow Lite for Microcontrollers is run on the STM32F746 discovery kit. About the C model running, used the Hello World example to generate the ARM Mbed  (please see NOTE.txt) and "manually" modify it to the ClassifyHeartbeats project. The modified files are at https://github.com/on-device-ai/ClassifyHeartbeats/tree/quantized_model/mbed .Please see RESULT.txt get the running result (including no quantized and quantized. No quantized version "//#define USE_QUANTIZED" result is correct).

**Comment by MeghnaNatraj** [comment]
Hello, could you confirm if you are still facing this issue? I am yet to reproduce the issue on the micro-controller but it seems to be working on the jupyter notebook.

**Comment by on-device-ai** [comment]
I used the float point model with the last TensorFlow source code doing the demo because the quantized model has the same issue for prediction. I just joined the tinyML Summit 2020, and I will take the time to confirm it again.  
![74486009-e98f2e80-4e70-11ea-99cb-8386ac6c106c](https://user-images.githubusercontent.com/44540872/74723004-cf8c8c00-5274-11ea-8f19-2aae43c75ef1.png)

**Comment by on-device-ai** [comment]
I have used the latest TensorFlow source code to verify this issue. The same is used the Hello World example to generate the ARM Mbed project and "manually" modify it to the ClassifyHeartbeats [Mbed](https://github.com/on-device-ai/ClassifyHeartbeats/tree/quantized_model/mbed) project. Using the quantized model inference results are also incorrect, please see [RESULT.txt](https://github.com/on-device-ai/ClassifyHeartbeats/blob/quantized_model/RESULT.txt). But TFLite Micro currently has on the Mbed are many problems, so I may use other verification methods to confirm this issue.

**Comment by on-device-ai** [comment]
I got Daniel Situnayake's suggestion at tensorflow/sig-micro-Gitter, and set a parameter (need to provide a representative dataset) when converting to the tflite model, which solved the problem. The source code at https://github.com/on-device-ai/ClassifyHeartbeats/tree/quantized_model . This Issue can be closed, thank you.

**Comment by MeghnaNatraj** [comment]
We're updating the examples to reflect this change. Glad that you were able to fix this issue!
