### ISSUE TITLE
TFLite_Detection_PostProcess

### ISSUE THREAD

**Issue by jianhuaxiao** [tensorflow/tensorflow#34228]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- TensorFlow installed from (source or binary):
- TensorFlow version (or github SHA if from source):

**Provide the text output from tflite_convert**

```
# Copy and paste here
```

Also, please include a link to a GraphDef or the model if possible.

**Any other info / logs**

Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by ravikyram** [comment]
@jianhuaxiao 

Can you please elaborate about the issue & the context.Will it be possible to provide related code.Thanks!

**Comment by ravikyram** [comment]
@jianhuaxiao 

Any update on this issue please. Thanks!

**Comment by ravikyram** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
