### ISSUE TITLE
Rejection resampling with multi-label output

### ISSUE THREAD

**Issue by qbeer** [tensorflow/tensorflow#34224]
### Description

I was reading the about the experimental rejection sampling method and I was wondering. What if I have multi-label binary classes? E.g. [1, 0, ,0, 1, 0, 0, 0, 0, 0, 0]. If I want to even the distribution of each label with `target_dist=[0.1] * 10 ` what is the expected behaviour?

#### URL(s) with the issue: [Rejection resampling Docs](https://www.tensorflow.org/api_docs/python/tf/data/experimental/rejection_resample)

Thanks in advance!

**Comment by gowthamkpr** [comment]
Can you please be more clearer on what you are trying to accomplish here with an application. Thanks @qbeer

**Comment by gowthamkpr** [comment]
@qbeer Can I close this issue. Let me know if you have any doubts?

**Comment by qbeer** [comment]
Yes you can close this, thank you for the answer. I understand know that I had to implement the `class_fn` which used an `argmax` operation therefore the resampler only works for exclusive labels. It is not straigthforward to implement it in a fashion I would have liked to but the doubt is answered now.
