### ISSUE TITLE
ubuntu  cuda10.1 build error. Linking of rule '//tensorflow/python:gen_logging_ops_py_wrappers_cc' failed (Exit 1)

### ISSUE THREAD

**Issue by ydxt** [tensorflow/tensorflow#34222]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- Ubuntu 18.04
- TensorFlow installed from (source or binary):
- TensorFlow version:  v2.0.0-rc2
- Python version: 3.7
- Installed using conda
- Bazel version (if compiling from source):0.29.1
- GCC/Compiler version (if compiling from source): 7.4
- CUDA/cuDNN version: cuda 10.1  cuDNN 7.6.5
- GPU model and memory:  nvida RTX2060， memory 6GB

compile config：
build --action_env PYTHON_BIN_PATH="/home/ubuntu/.conda/envs/tensorflow-gpu/bin/python"
build --action_env PYTHON_LIB_PATH="/home/ubuntu/.conda/envs/tensorflow-gpu/lib/python3.7/site-packages"
build --python_path="/home/ubuntu/.conda/envs/tensorflow-gpu/bin/python"
build:xla --define with_xla_support=true
build --action_env CUDA_TOOLKIT_PATH="/usr/local/cuda"
build --action_env TF_CUDA_COMPUTE_CAPABILITIES="7.5"
build --action_env LD_LIBRARY_PATH="/home/ubuntu/ThirdpartyLibrary/ode/ode-build/lib:/usr/local/lib:/usr/local/lib/boost:/usr/local/cuda/lib64:/usr/local/cuda/extras/CUPTI/lib64"
build --action_env GCC_HOST_COMPILER_PATH="/usr/bin/x86_64-linux-gnu-gcc-7"
build --config=cuda
build:opt --copt=-march=native
build:opt --copt=-Wno-sign-compare
build:opt --host_copt=-march=native
build:opt --define with_default_optimizations=true
test --flaky_test_attempts=3
test --test_size_filters=small,medium
test --test_tag_filters=-benchmark-test,-no_oss,-oss_serial
test --build_tag_filters=-benchmark-test,-no_oss
test --test_tag_filters=-gpu
test --build_tag_filters=-gpu
build --action_env TF_CONFIGURE_IOS="0"

use build opt：
bazel build --config=opt --config=v2 --config=cuda --cxxopt="-D_GLIBCXX_USE_CXX11_ABI=0" --verbose_failures //tensorflow/tools/pip_package:build_pip_package

error info：
external/com_google_absl/absl/types/optional.h(425): warning: expression has no effect
          detected during instantiation of "const T &absl::optional<T>::operator*() const & [with T=stream_executor::dnn::AlgorithmDesc]" 
./tensorflow/stream_executor/dnn.h(804): here

external/com_google_absl/absl/types/optional.h(425): warning: expression has no effect
          detected during instantiation of "const T &absl::optional<T>::operator*() const & [with T=size_t]" 
./tensorflow/stream_executor/dnn.h(858): here

INFO: From Compiling tensorflow/core/kernels/slice_op_gpu.cu.cc:
external/com_google_absl/absl/strings/string_view.h(495): warning: expression has no effect

external/com_google_absl/absl/strings/string_view.h(495): warning: expression has no effect

ERROR: /home/ubuntu/ThirdpartyLibrary/tensorflow/tensorflow/tensorflow/python/BUILD:2444:1: Linking of rule '//tensorflow/python:gen_logging_ops_py_wrappers_cc' failed (Exit 1)
bazel-out/host/bin/tensorflow/core/libop_gen_lib.a(op_gen_lib.o): In function `google::protobuf::internal::ArenaStringPtr::CreateInstance(google::protobuf::Arena*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const*)':
op_gen_lib.cc:(.text._ZN6google8protobuf8internal14ArenaStringPtr14CreateInstanceEPNS0_5ArenaEPKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE[_ZN6google8protobuf8internal14ArenaStringPtr14CreateInstanceEPNS0_5ArenaEPKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE]+0x36): undefined reference to `google::protobuf::internal::ArenaImpl::AllocateAlignedAndAddCleanup(unsigned long, void (*)(void*))'
op_gen_lib.cc:(.text._ZN6google8protobuf8internal14ArenaStringPtr14CreateInstanceEPNS0_5ArenaEPKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE[_ZN6google8protobuf8internal14ArenaStringPtr14CreateInstanceEPNS0_5ArenaEPKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE]+0xc0): undefined reference to `google::protobuf::Arena::OnArenaAllocation(std::type_info const*, unsigned long) const'
bazel-out/host/bin/tensorflow/core/libop_gen_lib.a(op_gen_lib.o): In function `tensorflow::(anonymous namespace)::MergeArg(tensorflow::ApiDef_Arg*, tensorflow::ApiDef_Arg const&)':
op_gen_lib.cc:(.text._ZN10tensorflow12_GLOBAL__N_18MergeArgEPNS_10ApiDef_ArgERKS1_+0x4c): undefined reference to `google::protobuf::internal::fixed_address_empty_string[abi:cxx11]'
op_gen_lib.cc:(.text._ZN10tensorflow12_GLOBAL__N_18MergeArgEPNS_10ApiDef_ArgERKS1_+0x77): undefined reference to `google::protobuf::internal::fixed_address_empty_string[abi:cxx11]'
bazel-out/host/bin/tensorflow/core/libop_gen_lib.a(op_gen_lib.o): In function `tensorflow::WordWrap[abi:cxx11](absl::string_view, absl::string_view, int)':
op_gen_lib.cc:(.text._ZN10tensorflow8WordWrapB5cxx11EN4absl11string_viewES1_i+0x10a): undefined reference to `tensorflow::strings::StrAppend(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, tensorflow::strings::AlphaNum const&)'
op_gen_lib.cc:(.text._ZN10tensorflow8WordWrapB5cxx11EN4absl11string_viewES1_i+0x20f): undefined reference to `tensorflow::strings::StrAppend(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, tensorflow::strings::AlphaNum const&)'
op_gen_lib.cc:(.text._ZN10tensorflow8WordWrapB5cxx11EN4absl11string_viewES1_i+0x299): undefined reference to `tensorflow::strings::StrAppend(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, tensorflow::strings::AlphaNum const&)'
op_gen_lib.cc:(.text._ZN10tensorflow8WordWrapB5cxx11EN4absl11string_viewES1_i+0x2c6): undefined reference to `tensorflow::strings::StrAppend(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, tensorflow::strings::AlphaNum const&)'
bazel-out/host/bin/tensorflow/core/libop_gen_lib.a(op_gen_lib.o): In function `tensorflow::PBTxtFromMultiline[abi:cxx11](absl::string_view)':
op_gen_lib.cc:(.text._ZN10tensorflow18PBTxtFromMultilineB5cxx11EN4absl11string_viewE+0x199): undefined reference to `tensorflow::strings::StrAppend(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, tensorflow::strings::AlphaNum const&, tensorflow::strings::AlphaNum const&)'
op_gen_lib.cc:(.text._ZN10tensorflow18PBTxtFromMultilineB5cxx11EN4absl11string_viewE+0x229): undefined reference to `tensorflow::strings::StrAppend(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, tensorflow::strings::AlphaNum const&)'
op_gen_lib.cc:(.text._ZN10tensorflow18PBTxtFromMultilineB5cxx11EN4absl11string_viewE+0x350): undefined reference to `tensorflow::strings::StrAppend(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, tensorflow::strings::AlphaNum const&)'
op_gen_lib.cc:(.text._ZN10tensorflow18PBTxtFromMultilineB5cxx11EN4absl11string_viewE+0x4a4): undefined reference to `tensorflow::strings::internal::AppendPieces(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, std::initializer_list<absl::string_view>)'
op_gen_lib.cc:(.text._ZN10tensorflow18PBTxtFromMultilineB5cxx11EN4absl11string_viewE+0x540): undefined reference to `tensorflow::strings::StrAppend(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, tensorflow::strings::AlphaNum const&)'
bazel-out/host/bin/tensorflow/core/libop_gen_lib.a(op_gen_lib.o): In function `tensorflow::Status tensorflow::errors::FailedPrecondition<char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >(char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)':
op_gen_lib.cc:
....
...
....
`tensorflow::register_op::OpDefBuilderReceiver::OpDefBuilderReceiver(tensorflow::register_op::OpDefBuilderWrapper<true> const&)'
logging_ops.cc:(.text.startup._Z41__static_initialization_and_destruction_0ii.constprop.69+0x1217): undefined reference to `tensorflow::OpDefBuilder::SetIsStateful()'
logging_ops.cc:(.text.startup._Z41__static_initialization_and_destruction_0ii.constprop.69+0x1235): undefined reference to `tensorflow::register_op::OpDefBuilderReceiver::OpDefBuilderReceiver(tensorflow::register_op::OpDefBuilderWrapper<true> const&)'
collect2: error: ld returned 1 exit status
Target //tensorflow/tools/pip_package:build_pip_package failed to build
INFO: Elapsed time: 7445.735s, Critical Path: 194.55s
INFO: 10220 processes: 10220 local.
FAILED: Build did NOT complete successfully

**Comment by itemko** [comment]
@ydxt 
How have you resolved this?

**Comment by ydxt** [comment]
> @ydxt
> How have you resolved this?

the problem still exists. I don't have an answer right now.

**Comment by marcojerome** [comment]
Same problem in ubuntu 19.10, same configuration as ydxt

**Comment by itemko** [comment]
Seems we're observing something similar after recent Bazel version upgrade.

**Comment by itemko** [comment]
Possibly related issue https://github.com/tensorflow/tensorflow/issues/34117

**Comment by marcojerome** [comment]
I confirm that with bazel 0.24.1 does work and the linking error disappears.

**Comment by ravikyram** [comment]
@ydxt 

Can you please confirm if @marcojerome's workaround is working for you.Thanks!

**Comment by ydxt** [comment]
> I confirm that with bazel 0.24.1 does work and the linking error disappears.

@marcojerome  @ravikyram Thanks, I will try it with bazel 0.24.1

**Comment by itemko** [comment]
JFYI
For our similar case the problem is not reproducible with TensorFlow master since yesterday (looks like there were some fixes). Bazel version: 0.29.1.
For example, this TensorFlow commit (95051b912c0b00f9cde62aada17687151944eb0d) is built successfully.

**Comment by ydxt** [comment]
tensorflow r2.0 with  bazel 0.24.1 successed builded, thank you for your reply.
