### ISSUE TITLE
Android - Posenet is slow/laggy

### ISSUE THREAD

**Issue by HBiSoft** [tensorflow/tensorflow#34230]
**System information**
- I'm using the posenet example
- Samsung J7 Pro running Android 9

**Describe the current behavior**
The preview is slow/laggy. The interpreter takes on avarage 300ms when using GPU and 400ms when using CPU

**Describe the expected behavior**
The preview should display the frames smoothly

**Code to reproduce the issue**
I'm running the posenet example application

**Other info / logs**
This issue is not present in the Tensorflow Detect example. 
I tried reducing the preview size, but the issue remains

    org.tensorflow.lite.examples.posenet I/posenet: Interpreter took 305,41 ms
    org.tensorflow.lite.examples.posenet I/posenet: Scaling to [-1,1] took 104,03 ms

Please let me know if you need more info.

**Comment by yyoon** [comment]
Currently, this is done intentionally to sync the frame with the estimated pose displayed on screen. We could add an option to toggle this behavior.

**Comment by HBiSoft** [comment]
@yyoon That would be great.

**Comment by eQueue** [comment]
@HBiSoft 
hi, i'm running posenet example of tensorflow lite.
i got same issue. how can you solve that problem? did you sync the frame with estimated pose displayed on screen? can you share your modified code?
i appreciate for your help

**Comment by HBiSoft** [comment]
@eQueue 
I have not yet found a way around this.

@yyoon 
>Currently, this is done intentionally to sync the frame with the estimated pose displayed on screen.

Does this mean that we will not be able to detect a pose in real time? Any updates on this issue will be appreciated.

**Comment by Nishikoh** [comment]
I thought about two ways to improve.
1. Edit lines 446, 447 and 449 of PosenetActivity.kt

      // Process an image for analysis in every 3 frames.
      frameCounter = (frameCounter + 1) % 3          // delete or comment this line
      if (frameCounter == 0) {                                    // delete or comment this line
        processImage(rotatedBitmap)
      }                                                                        // delete or comment this line

2.  Eddit PREVIEW_WIDTH and  PREVIEW_HEIGHT of  PosenetActivity.kt
The lower these two values, the faster. However, it is not recommended due to the loss of accuracy.

**Comment by HBiSoft** [comment]
@Nishikoh 
I tried both of your suggestions and neither of them made a difference.

**Comment by lintian06** [comment]
We fixed this app to run with 4-threads CPU now, and it runs at about 10fps on Pixel 3. Should be close to the realtime.

**Comment by HBiSoft** [comment]
@lintian06 
I tested the change and the preview is still "choppy". With CPU, I now get about 200ms.

**Comment by panmin** [comment]
the same problem，the preview delay， why readme gif is affluent

**Comment by lintian06** [comment]
It may depend on phone models. The test on Pixel 3 is like:

CPU: 4 threads
Scaling to [-1,1] took 46.63 ms
Interpreter took 43.72 ms

GPU
Scaling to [-1,1] took 46.67 ms
Interpreter took 15.28 ms

It depends on hardware. You may adjust according to your phone.

**Comment by HBiSoft** [comment]
@lintian06 
>It depends on hardware.

This is a big issue since there are 4000+ android devices, all with different chipsets.

>You may adjust according to your phone.

What do you suggest we adjust?

I have tried:
- Increasing the threads
- Reducing the preview dimensions
- Feeding frames continuously (instead of every third frame)
- Increase/decrease the frame rate
- Running tensorflow/posenet on its own (without drawing anything on the canvas except the preview frame)

CPU comparison between the Pixel 3 and my device:
---

Google Pixel 3:
`Octa-core (4x2.5 GHz Kryo 385 Gold & 4x1.6 GHz Kryo 385 Silver)`

Samsung J7 Pro:
`Octa-core 1.6 GHz Cortex-A53`

**Comment by yyoon** [comment]
cc/ @terryheo

**Comment by terryheo** [comment]
https://github.com/tensorflow/tensorflow/issues/34230#issuecomment-597255383 the change looks good to me. I'll handle it.

@HBiSoft I think there are two area to improve.
1. Quantization
https://www.tensorflow.org/lite/performance/model_optimization
If you quantized model, you'll get better performance.
2. Optimize scaling
In your log, scaling takes 100ms. I can see some inefficiency on converting YUV to ARGB and resizing. I think we could get resized ARGB image directly from the camera.
Also there is a logic creating input tensor in Java layer. We might be able to handle this natively.

**Comment by terryheo** [comment]
https://github.com/tensorflow/examples/commit/f61466134db544776a1819cbe7af8673c7626216 is merged.

https://github.com/tensorflow/examples/commit/a50d45351c16c990a62beb65cf99fa066eb5cbd9 resolves the scaling issue.
There is still a room to improve with the quantization but we don't have a concrete plan yet. Let's close this.

**Comment by HBiSoft** [comment]
@terryheo 
I tested the changes and I could barely see any improvement in performance. It is still "laggy".

    Interpreter took 201,77 ms
    Scaling to [-1,1] took 108,88 ms

I'm not sure how much quantization will increase performance.

**Comment by terryheo** [comment]
@HBiSoft Please check if you build & install correctly.
I have a low end device which took 350ms in scaling. Now it only takes 50ms.

**Comment by HBiSoft** [comment]
@terryheo 
>Please check if you build & install correctly.

I downloaded [tensorflow examples](https://github.com/tensorflow/examples) then opened the [posenet for android example app](https://github.com/tensorflow/examples/tree/master/lite/examples/posenet/android). After that, I made the changes you mentioned above - tensorflow/examples@f614661 and tensorflow/examples@a50d453 - Then ran the app on my device.

Am I missing something?

**Comment by terryheo** [comment]
> I downloaded tensorflow examples then opened the posenet for android example app. After that, I made the changes you mentioned above - tensorflow/examples@f614661 and tensorflow/examples@a50d453 - Then ran the app on my device.

You don't need to apply changes manually. Plz just use master branch that contains everything you need.

```
a50d453 (HEAD, origin/master, origin/HEAD) Posenet: Use getPixels() to read pixels efficiently
f614661 Posenet: Handle every coming frame
89fa240 Upgrade permission requests.
f026043 ModelMaker Hparams should extend Hub's make_image_classifier_lib Hparams
cfddb05 Migrate to use dataset.cardinality.
36c0ad2 Refactor model_maker utils and TensorFlow 1 tests.
6c3c9b6 Posenet: Use TFLite 2.2.0
```
If you have these already, how about changing log "Scaling to [-1,1] took xxx ms" to a different string to verify if you're running correct version?

**Comment by HBiSoft** [comment]
@terryheo 
Thank you for your reply. I ran the master branch and I get the following:

    Interpreter took 204,42 ms
    Scaling to [-1,1] took 26,47 ms

The scaling is faster, but the preview is still not as it should be. I guess quantization is the only option to improve this, It looks kinda complicated though. I will have a look into it.
