### ISSUE TITLE
Checkpoint managers overwrite not owned checkpoints

### ISSUE THREAD

**Issue by georgesterpu** [tensorflow/tensorflow#34234]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): no
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Manjaro linux testing
- TensorFlow installed from: pypi binary
- TensorFlow version (use command below): v1.12.1-16854-g6778662 2.1.0-dev20191028
- Python version: 3.7.4

**Describe the current behavior**
A `tf.train.CheckpointManager` erases checkpoints in its directory path that were not written by it.
This is a different behaviour from `tf.train.Saver` in TF1.

**Describe the expected behavior**
Do not remove checkpoints that are not owned by a CheckpointManager instance.
In the code below, I expected to have checkpoints 1, 2, 4, 5 at the end. Instead, only 4 and 5 survived.

**Code to reproduce the issue**
```
import tensorflow as tf

var = tf.Variable(initial_value=12)

checkpoint = tf.train.Checkpoint(var=var)
manager = tf.train.CheckpointManager(
    checkpoint=checkpoint,
    directory='./delete_me/',
    max_to_keep=2)

manager.save(0)
manager.save(1)
manager.save(2)

manager2 = tf.train.CheckpointManager(
    checkpoint=checkpoint,
    directory='./delete_me/',
    max_to_keep=2)

manager2.save(3)
manager2.save(4)
manager2.save(5)
#  Why were 1 and 2 deleted by manager2 ?
```

**Other info / logs**

**Comment by gadagashwini** [comment]
@georgesterpu, In the `tf.train.CheckpointManager()`, change the value of `max_to_keep=5`.
max_to_keep shows the number of checkpoints to keep. Please refer this [link](https://www.tensorflow.org/api_docs/python/tf/train/CheckpointManager) for more information. Thanks!

**Comment by georgesterpu** [comment]
Hi @gadagashwini 
Thanks for the reply.
My issue is slightly different. I think that `manager2` should not erase checkpoints written by `manager`, or in general by any other checkpoint manager.

The aim is to keep up to N checkpoints from a set of M managers writing K checkpoints each, where K >> N. You cannot control this with the `max_to_keep` parameter alone, unless it is set to a very large value of the order of M*K.

I expected each checkpoint manager to keep a list of all the checkpoints it has written so far, and to do the sweep operation only on this list. Instead, it appears that a checkpoint manager inspects its working directory (which can be shared by other managers) and is able to sweep any checkpoint inside, leaving up to N checkpoints there. With `tf.train.Saver` in TensorFlow 1, that directory would contain N * M checkpoints.

Please let me know if this explanation is more clear.

**Comment by gadagashwini** [comment]
Issue is replicating on colab with TF 2.1.0.dev20191028.
Please see gist [here](https://colab.sandbox.google.com/gist/gadagashwini/458b64b41d927e2e18318900b306d959/untitled258.ipynb). Thanks!

**Comment by rmothukuru** [comment]
@georgesterpu,
As per @gadagashwini's comment, by using `max_to_keep=10`, all the Checkpoints are retained. Please find the [Gist](https://colab.sandbox.google.com/gist/rmothukuru/729f03581c84f22332f4eb2ff29b47f5/untitled258.ipynb#scrollTo=m9Ca1XPakRK9). Please let me know if you need more information. Thanks!

**Comment by georgesterpu** [comment]
Thanks, @rmothukuru,
Sorry, I think that I haven't explained this clear enough, please have a look at another snippet below.

```
import tensorflow as tf

var = tf.Variable(initial_value=12)

checkpoint = tf.train.Checkpoint(var=var)
manager = tf.train.CheckpointManager(
    checkpoint=checkpoint,
    directory='./delete_me/',
    max_to_keep=2)

for i in range(1000):
    manager.save(i)

manager2 = tf.train.CheckpointManager(
    checkpoint=checkpoint,
    directory='./delete_me/',
    max_to_keep=2)

for i in range(1000, 2000):
    manager2.save(i)
```

What I would like to find in the checkpoint directory is the following list of checkpoints:
`ckpt-998, ckpt-999, ckpt-1998, ckpt-1999`, or the last two checkpoints saved by each manager.
Instead, there are only `ckpt-1998, ckpt-1999`. You are suggesting that the solution to this is to change max to keep to 1000, which will save an unnecessarily amount of checkpoints.

**Comment by rmothukuru** [comment]
Could reproduce the issue with TF Version 2.0. Here is the [Gist](https://colab.sandbox.google.com/gist/rmothukuru/c350687aa6389346a38ac2e7595c2c7b/untitled262.ipynb). Thanks!

**Comment by karmel** [comment]
The checkpoint directory should be viewed as a single unit of work, and in general, we would not advise using the same checkpoint dir for multiple checkpoint managers, for this reason and others. In this case, please use separate directories for each Manager, or adjust params to match the expectations of the checkpoint dir rather than each manager alone.

**Comment by georgesterpu** [comment]
Thanks, @karmel, I will update my code in that case.
I have an use case where a new Manager resumes training from the latest checkpoint of a previous Manager, but also need to store the last checkpoint of each manager. Some checkpoint copying script will do it.
