### ISSUE TITLE
@tf.function slower the GPU performance?

### ISSUE THREAD

**Issue by lucify123** [tensorflow/tensorflow#34231]
import time
    import tensorflow as tf
    @tf.function #Commenting out this line makes a huge difference in GPU performance
    def measure(x, steps):
      tf.matmul(x, x)
      start = time.time()
      for i in range(steps):
        x = tf.matmul(x, x)
      end = time.time()
      return end - start
    
    shape = (1000, 1000)
    steps = 2000
    #print("Time to multiply a {} matrix by itself {} times:".format(shape, steps))
    
    # Run on CPU:
    with tf.device("/cpu:0"):
      print("CPU: {} secs".format(measure(tf.random.normal(shape), steps)))
    
    # Run on GPU, if available:
    if tf.test.is_gpu_available():
      with tf.device("/gpu:0"):
        print("GPU: {} secs".format(measure(tf.random.normal(shape), steps)))

GPU:1080ti
CPU:2990wx

when use @tf.function，results below：
CPU: 1.223414659500122 secs
GPU: 1.223414659500122 secs

when don't use @tf.function
CPU: 6.363093614578247 secs
GPU: 0.25109028816223145 secs

why 4x slower ?
when should we use  "@tf.function" instead of  "with tf.device("/gpu:0"):"

**Comment by ravikyram** [comment]
I have tried on colab with TF version 2.0  and was able to reproduce the issue.Please, find the gist [here](https://colab.sandbox.google.com/gist/ravikyram/9513fe1081ff6b3149d6ed6ba9c0e25c/untitled366.ipynb). Thanks!

**Comment by ymodak** [comment]
```@tf.function``` does graph representation of your python code to deploy your model across various devices. The speed up can be observed on executing computationally intensive tasks and may not happen in simple cases such as matrix multiplication.
