### ISSUE TITLE
tf.keras.backend.gradients error in eager mode

### ISSUE THREAD

**Issue by ksasi** [tensorflow/tensorflow#34235]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below): n/a
- Python version: 3.6.8
- Bazel version (if compiling from source): n/a
- GCC/Compiler version (if compiling from source): n/a
- CUDA/cuDNN version: Cuda compilation tools, release 10.0, V10.0.130
- GPU model and memory: Tesla P100

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
Usage of tf.keras.backend.gradients in tensorflow 2.0 gives the following error :

RuntimeError: tf.gradients is not supported when eager execution is enabled. Use tf.GradientTape instead.

The entire error is as below : 

---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-55-a2847ee8d0c4> in <module>()
     69         ax[x, y].set_title('filter %d' % (x * plot_y + y - 1))
     70 
---> 71 vis_img_in_filter()

3 frames
<ipython-input-55-a2847ee8d0c4> in vis_img_in_filter(img, layer_name)
     30 
     31         # compute the gradient of the input picture wrt this loss
---> 32         grads = K.gradients(loss, model.input)[0]
     33 
     34         # normalization trick: we normalize the gradient

/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/backend.py in gradients(loss, variables)
   3795   """
   3796   return gradients_module.gradients(
-> 3797       loss, variables, colocate_gradients_with_ops=True)
   3798 
   3799 

/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/ops/gradients_impl.py in gradients(ys, xs, grad_ys, name, colocate_gradients_with_ops, gate_gradients, aggregation_method, stop_gradients, unconnected_gradients)
    156         ys, xs, grad_ys, name, colocate_gradients_with_ops,
    157         gate_gradients, aggregation_method, stop_gradients,
--> 158         unconnected_gradients)
    159   # pylint: enable=protected-access
    160 

/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/ops/gradients_util.py in _GradientsHelper(ys, xs, grad_ys, name, colocate_gradients_with_ops, gate_gradients, aggregation_method, stop_gradients, unconnected_gradients, src_graph)
    503   """Implementation of gradients()."""
    504   if context.executing_eagerly():
--> 505     raise RuntimeError("tf.gradients is not supported when eager execution "
    506                        "is enabled. Use tf.GradientTape instead.")
    507   if src_graph is None:

RuntimeError: tf.gradients is not supported when eager execution is enabled. Use tf.GradientTape instead.

**Describe the expected behavior**

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by oanush** [comment]
@ksasi ,
Thank you for reporting the issue,
can you please provide the code to reproduce the issue reported here from our side?
Also,Tensorflow 2.0 by default uses Eager-Execution.please deactivate the eager execution :
`tf.compat.v1.disable_eager_execution()`
Find this SO [link](https://stackoverflow.com/questions/56478454/in-tensorflow-2-0-with-eager-execution-how-to-compute-the-gradients-of-a-networ) of similar issue and let us know if its was helpful.

**Comment by ksasi** [comment]
Hi,

tf.compat.v1.disable_eager_execution() seems to be helping with the error. This can be a workaround. However , shouldn't "tf.keras.backend.gradients" automatically detect the eager vs graph mode and then obtain gradients?

Below is the code to reproduce the issue. The "vis_img_in_filter()" fails with the error, as eager is enabled by default in tf.keras 2.0

import numpy as np
import tensorflow as tf

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, Activation, Flatten, Add
from tensorflow.keras.layers import Conv2D, MaxPool2D
from tensorflow.keras import utils

from tensorflow.keras.datasets import mnist

print(tf.version.VERSION)
print(tf.keras.__version__)


(X_train, y_train), (X_test, y_test) = mnist.load_data()

X_train = X_train.astype('float32')
X_test = X_test.astype('float32')
X_train /= 255
X_test /= 255


Y_train = utils.to_categorical(y_train, 10)
Y_test = utils.to_categorical(y_test, 10)


from keras.layers import Activation
model = Sequential()

model.add(Conv2D(filters = 32, kernel_size = (3, 3), activation='relu', input_shape=(28,28,1), use_bias = False))
model.add(Conv2D(filters = 10, kernel_size = (1, 1) , activation='relu', use_bias = False))
model.add(Conv2D(filters = 10, kernel_size = (26, 26), use_bias = False))
model.add(Flatten())
model.add(Activation('softmax'))

model.compile(loss='categorical_crossentropy',
             optimizer='adam',
             metrics=['accuracy'])

model.fit(X_train, Y_train, batch_size=128, epochs=10, validation_data = (X_test, Y_test), verbose=1)


layer_dict = dict([(layer.name, layer) for layer in model.layers])


import numpy as np
from matplotlib import pyplot as plt
from tensorflow.keras import backend as K
%matplotlib inline
# util function to convert a tensor into a valid image
def deprocess_image(x):
    # normalize tensor: center on 0., ensure std is 0.1
    x -= x.mean()
    x /= (x.std() + 1e-5)
    x *= 0.1

    # clip to [0, 1]
    x += 0.5
    x = np.clip(x, 0, 1)

    # convert to RGB array
    x *= 255
    #x = x.transpose((1, 2, 0))
    x = np.clip(x, 0, 255).astype('uint8')
    return x

def vis_img_in_filter(img = np.array(X_train[2]).reshape((1, 28, 28, 1)).astype(np.float64), 
                      layer_name = 'conv2d_1'):
    layer_output = layer_dict[layer_name].output
    img_ascs = list()
    for filter_index in range(layer_output.shape[3]):
        # build a loss function that maximizes the activation
        # of the nth filter of the layer considered
        loss = K.mean(layer_output[:, :, :, filter_index])

        # compute the gradient of the input picture wrt this loss
        grads = K.gradients(loss, model.input)[0]

        # normalization trick: we normalize the gradient
        grads /= (K.sqrt(K.mean(K.square(grads))) + 1e-5)

        # this function returns the loss and grads given the input picture
        iterate = K.function([model.input], [loss, grads])

        # step size for gradient ascent
        step = 5.

        img_asc = np.array(img)
        # run gradient ascent for 20 steps
        for i in range(20):
            loss_value, grads_value = iterate([img_asc])
            img_asc += grads_value * step

        img_asc = img_asc[0]
        img_ascs.append(deprocess_image(img_asc).reshape((28, 28)))
        
    if layer_output.shape[3] >= 35:
        plot_x, plot_y = 6, 6
    elif layer_output.shape[3] >= 23:
        plot_x, plot_y = 4, 6
    elif layer_output.shape[3] >= 11:
        plot_x, plot_y = 2, 6
    else:
        plot_x, plot_y = 1, 2
    fig, ax = plt.subplots(plot_x, plot_y, figsize = (12, 12))
    ax[0, 0].imshow(img.reshape((28, 28)), cmap = 'gray')
    ax[0, 0].set_title('Input image')
    fig.suptitle('Input image and %s filters' % (layer_name,))
    fig.tight_layout(pad = 0.3, rect = [0, 0, 0.9, 0.9])
    for (x, y) in [(i, j) for i in range(plot_x) for j in range(plot_y)]:
        if x == 0 and y == 0:
            continue
        ax[x, y].imshow(img_ascs[x * plot_y + y - 1], cmap = 'gray')
        ax[x, y].set_title('filter %d' % (x * plot_y + y - 1))

vis_img_in_filter()

**Comment by mikegashler** [comment]
I am also blocked by this issue. If it helps, here is another repro:
```import numpy as np
import tensorflow as tf
import keras

# First, let's do something that requires eager mode
tf.enable_eager_execution()
a = tf.constant(3.0)
print(a.numpy()) # in graph mode, this line fails with "'Tensor' object has no attribute 'numpy'"

# Next, let's try to train a Keras model
X = np.array([[0, 0], [1, 1]])
k_input = keras.Input(shape = (2,))
k_layer = keras.layers.Dense(2)(k_input)
k_optimizer: keras.optimizers.Adam = keras.optimizers.Adam(lr = 1e-3)
k_model = keras.Model(k_input, k_layer)
k_model.compile(optimizer = k_optimizer, loss = 'mse')
k_model.train_on_batch(X, X) # This line fails with "tf.gradients is not supported when eager execution is enabled."
print("This line is never reached!")

**Comment by ymodak** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.

Thanks!

**Comment by ksasi** [comment]
@ymodak , I am not sure if this is a usable question. But rather the intended behaviour. Can you confirm if this behaviour is as per the intended design and this is not a bug?
