### ISSUE TITLE
When the result of tf.saved_model.load goes out of scope, it invalidates models that are still in-scope

### ISSUE THREAD

**Issue by chkothe** [tensorflow/tensorflow#34253]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes, a trivial change to a stock example
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10 x64
- TensorFlow installed from (source or binary): binary via pip
- TensorFlow version (use command below): tensorflow-gpu 2.0.0
- Python version: 3.6.6
- CUDA/cuDNN version: 10.0 / 10.0-windows10-x64-v7.6.0.64
- GPU model and memory: GeForce GTX 1050 Ti (laptop)

**Describe the current behavior**

Loading a TF2 model built with the Keras API, and then predicting with random data follows this minimal recipe:
```
import tensorflow as tf
loaded = tf.saved_model.load('some/model')
infer = loaded.signatures['serving_default']
data = tf.constant(np.asarray(np.random.randn(my_shape), dtype=np.float32))
preds = infer(data)
```

However, if we don't keep a reference to `loaded` around or lose it some time later...
```
import tensorflow as tf
infer = tf.saved_model.load('some/model').signatures['serving_default']
data = tf.constant(np.asarray(np.random.randn(my_shape), dtype=np.float32))
preds = infer(data)
```

... it fails with this utterly confusing error about variables being potentially uninitialized (for which google searches lead down various unrelated tf 1.x related rabbit holes):
```
2019-11-13 15:37:09.423218: W tensorflow/core/common_runtime/base_collective_executor.cc:216] BaseCollectiveExecutor::StartAbort Failed precondition: Error while reading resource variable batch_normalization_150/moving_mean_12513 from Container: localhost. This could mean that the variable was uninitialized. Not found: Resource localhost/batch_normalization_150/moving_mean_12513/class tensorflow::Var does not exist.
	 [[{{node StatefulPartitionedCall/model_65/model_60/batch_normalization_150/FusedBatchNormV3/ReadVariableOp}}]]
Traceback (most recent call last):
  File "D:/DEVEL/experiments/test_load.py", line 17, in <module>
    preds = infer(data)
  File "C:\Users\chris\Miniconda3\envs\np2019-11-06e2\lib\site-packages\tensorflow_core\python\eager\function.py", line 1081, in __call__
    return self._call_impl(args, kwargs)
  File "C:\Users\chris\Miniconda3\envs\np2019-11-06e2\lib\site-packages\tensorflow_core\python\eager\function.py", line 1121, in _call_impl
    return self._call_flat(args, self.captured_inputs, cancellation_manager)
  File "C:\Users\chris\Miniconda3\envs\np2019-11-06e2\lib\site-packages\tensorflow_core\python\saved_model\load.py", line 99, in _call_flat
    cancellation_manager)
  File "C:\Users\chris\Miniconda3\envs\np2019-11-06e2\lib\site-packages\tensorflow_core\python\eager\function.py", line 1224, in _call_flat
    ctx, args, cancellation_manager=cancellation_manager)
  File "C:\Users\chris\Miniconda3\envs\np2019-11-06e2\lib\site-packages\tensorflow_core\python\eager\function.py", line 511, in call
    ctx=ctx)
  File "C:\Users\chris\Miniconda3\envs\np2019-11-06e2\lib\site-packages\tensorflow_core\python\eager\execute.py", line 67, in quick_execute
    six.raise_from(core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.FailedPreconditionError:  Error while reading resource variable batch_normalization_150/moving_mean_12513 from Container: localhost. This could mean that the variable was uninitialized. Not found: Resource localhost/batch_normalization_150/moving_mean_12513/class tensorflow::Var does not exist.
	 [[{{node StatefulPartitionedCall/model_65/model_60/batch_normalization_150/FusedBatchNormV3/ReadVariableOp}}]] [Op:__inference_signature_wrapper_5266]

Function call stack:
signature_wrapper
```

**Describe the expected behavior**

The `infer` object holds a reference to the data that it depends on so that it doesn't get garbage-collected.

**Code to reproduce the issue**
If you run the TF2.0 Saved Model tutorial colab notebook (https://colab.research.google.com/github/tensorflow/docs/blob/master/site/en/guide/saved_model.ipynb) up to and including the cell

```
!saved_model_cli show --dir /tmp/mobilenet/1 --tag_set serve --signature_def serving_default
```

but then you execute the following cell instead of the one that would create the variable `loaded`:

```
infer = tf.saved_model.load("/tmp/mobilenet/1/").signatures["serving_default"]
print(infer.structured_outputs)
labeling = infer(tf.constant(x))[pretrained_model.output_names[0]]
decoded = imagenet_labels[np.argsort(labeling)[0,::-1][:5]+1]
print("Result after saving and loading:\n", decoded)
```

... then it fails with:
```
---------------------------------------------------------------------------
FailedPreconditionError                   Traceback (most recent call last)
<ipython-input-8-f42985f0118d> in <module>()
----> 1 labeling = infer(tf.constant(x))[pretrained_model.output_names[0]]
      2 
      3 decoded = imagenet_labels[np.argsort(labeling)[0,::-1][:5]+1]
      4 
      5 print("Result after saving and loading:\n", decoded)

6 frames
/usr/local/lib/python3.6/dist-packages/six.py in raise_from(value, from_value)

FailedPreconditionError:  Error while reading resource variable conv_pw_7_bn/moving_variance_33153 from Container: localhost. This could mean that the variable was uninitialized. Not found: Resource localhost/conv_pw_7_bn/moving_variance_33153/N10tensorflow3VarE does not exist.
	 [[{{node StatefulPartitionedCall/mobilenet_1.00_224/conv_pw_7_bn/FusedBatchNormV3/ReadVariableOp_1}}]] [Op:__inference_signature_wrapper_30328]

Function call stack:
signature_wrapper
```

**Comment by gowthamkpr** [comment]
Was able to reproduce this issue. Please find the gist [here](https://colab.sandbox.google.com/gist/gowthamkpr/c38e0f0526c3cae25572f9ddb158ce90/copy-of-copy-of-saved_model.ipynb).

**Comment by ethanyanjiali** [comment]
I'm seeing a same issue when I load and use my custom saved_model.

**Comment by jrbuhl93** [comment]
Does anyone have a work around for this?

**Comment by k-w-w** [comment]
Functions only keep weak references to variables, so if the loaded object is garbage collected, the variables will be deleted as well. Make sure the loaded object remains in memory (using @jrbuhl93's approach as one such workaround)

**Comment by regzon** [comment]
Can this behavior be documented? This is not obvious for many people.

**Comment by joao-carvalheira** [comment]
I made it a global variable and it worked. Something like this:

```
loaded_model = None

def load_model():
    global loaded_model
    # load_model
```

**Comment by dain5832** [comment]
> I made it a global variable and it worked. Something like this:
> 
> ```
> loaded_model = None
> 
> def load_model():
>     global loaded_model
>     # load_model
> ```
I'm also having a same issue.
You mean you assigned your loaded model(tf.saved_model.load('some/model')) to loaded_model variable?

**Comment by dexter2406** [comment]
> > I made it a global variable and it worked. Something like this:
> > ```
> > loaded_model = None
> > 
> > def load_model():
> >     global loaded_model
> >     # load_model
> > ```
> 
> I'm also having a same issue.
> You mean you assigned your loaded model(tf.saved_model.load('some/model')) to variable "loaded_model"?

Just write it as Class and make it an attribute. It works for me.
