### ISSUE TITLE
A custom RNN cell does not support a high-order state_size

### ISSUE THREAD

**Issue by xlnwel** [tensorflow/tensorflow#34269]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):No
TensorFlow version (use command below):2.0.0
- Python version:3.7.4

**Describe the current behavior**
Cannot have a custom RNN cell to have a high order state_size.

**Describe the expected behavior**

**Code to reproduce the issue**
```
import numpy as np
import tensorflow as tf
from tensorflow.keras import layers

class NewCell(layers.Layer):
    def __init__(self, name=None):
        
        self.state_size = (
            tf.TensorShape([1, 2]),
            (tf.TensorShape([1, 2]), tf.TensorShape([2, 3])) # error cause by this tuple
        )
        self.output_size = (tf.TensorShape([1, 2]), )
        super().__init__(name=name)
        
    def call(self, inputs, state):
        print('everything is safe and sound!')
        return inputs, state
        
rnn = layers.RNN(NewCell())
inputs = tf.convert_to_tensor(np.random.rand(2, 1, 2))
rnn(inputs)
```

**Other info / logs**

The error message is:
> int() argument must be a string, a bytes-like object or a number, not 'TensorShape'

**Comment by gadagashwini** [comment]
Issue is replicating with Tensorflow version 2.0.
Please see the gist [here](https://colab.sandbox.google.com/gist/gadagashwini/0f2c5c2f88db0dacf2e0b3dff238941c/34269.ipynb). Thanks!

**Comment by gcuder** [comment]
Any update on this?

**Comment by sushreebarsa** [comment]
Issue is replicating with Tensorflow version 2.6.0-dev20210529,please find the gist [here](https://colab.research.google.com/gist/sushreebarsa/f75251be59852ecf722e998de43bf8b0/untitled82.ipynb#scrollTo=dXrmjt4NR4tF). Thanks!

**Comment by mohantym** [comment]
The error got resolved by removing the extra parentheses from this code block  
``` python 
 self.state_size = (
            tf.TensorShape([1, 2]),
            (tf.TensorShape([1, 2]), tf.TensorShape([2, 3])) 

```
with Tensorflow  version 2.5 ,please find the [gist ](https://colab.research.google.com/gist/mohantym/4251b02c22cde6e26a6dafc6291d2318/34269.ipynb#scrollTo=HekGzwptSAWR) of working code  ..Thanks!
