### ISSUE TITLE
How to get the last timestep of the output of an RNN?

### ISSUE THREAD

**Issue by ushnish** [tensorflow/tensorflow#3426]
Just a general question which might also help others, namely what is the correct way to extract the last timestep of the output of an RNN. Is it as simple as 

`outputs, state = tf.nn.dynamic_rnn(cell=dropout_cell, inputs=outputs1, initial_state=initial_state, sequence_length=s)`
`last = tf.gather(outputs, int(outputs.get_shape()[0]) - 1)`

Or should i transpose the output before performing gather, as per this example

`outputs, state = tf.nn.dynamic_rnn(cell=dropout_cell, inputs=outputs1, initial_state=initial_state, sequence_length=s)`
`outputs = tf.transpose(outputs, [1, 0, 2])`
`last = tf.gather(outputs, int(outputs.get_shape()[0]) - 1)`

Thank you

**Comment by concretevitamin** [comment]
This is best suited for StackOverflow, as it is not a bug nor feature request.
