### ISSUE TITLE
ValueError: Error when checking input: expected flatten_1_input to have 3 dimensions, but got array with shape (60000, 1)

### ISSUE THREAD

**Issue by hy59** [tensorflow/tensorflow#34274]
I ran the quickstart for beginner demo on my PC, but when i run the last cell, there is a **ValueError:Error when checking input: expected flatten_1_input to have 3 dimensions, but got array with shape (60000, 1)**, but when I ran the demo in Colab， there was no problem,
could you please tell what happend about this?
![image](https://user-images.githubusercontent.com/15179180/68869687-8c31f700-0734-11ea-8fa7-92705abc7310.png)
![image](https://user-images.githubusercontent.com/15179180/68869715-9522c880-0734-11ea-80aa-31106cc90506.png)

**Comment by oanush** [comment]
@hy59 ,
Can you please provide gist of colab or code being used so that we can try replicating the issue from our end?Thanks!

**Comment by oanush** [comment]
@hy59 ,
any update on the issue ?Thanks!

**Comment by oanush** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
