### ISSUE TITLE
Failing dependency downloads in latest

### ISSUE THREAD

**Issue by apcode** [tensorflow/tensorflow#3427]
### Environment info
Operating System: OSX El Capitan
Latest pull on 20th July 2016: c5983f87f0402f2cb8c627807917ebdf8e4d4bb6

Run: tensorflow/contrib/makefile/download_dependencies.sh

Failing output:
+ DOWNLOADS_DIR=tensorflow/contrib/makefile/downloads
+ mkdir tensorflow/contrib/makefile/downloads
++ cat eigen.BUILD
++ grep archive_dir
++ head -1
++ cut -f3 -d-
++ cut -f1 '-d"'
+ EIGEN_HASH=
+ curl https://bitbucket.org/eigen/eigen/get/.tar.gz -o /tmp/eigen-.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 26011  100 26011    0     0  34718      0 --:--:-- --:--:-- --:--:-- 34727
+ tar xzf /tmp/eigen-.tar.gz -C tensorflow/contrib/makefile/downloads
tar: Unrecognized archive format
tar: Error exit delayed from previous errors.

**Comment by apcode** [comment]
As shown in the output:

The download_dependencies.sh tries to grep the eigen hash from the eigen.BUILD file by finding the archive_dir. But there is no archive_dir in eigen.BUILD so it finds nothing.

**Comment by ruppeshnalwaya1993** [comment]
In the latest Tensorflow, this problem pops up again. 
When I execute tensorflow/contrib/makefile/download_dependencies.sh
I get following error:
downloading http://mirror.bazel.build/bitbucket.org/eigen/eigen/get/f3a22f35b044.tar.gz
tar: Unrecognized archive format
tar: Error exit delayed from previous errors.

This error was not there in the Tensorflow on May 10
https://github.com/tensorflow/tensorflow/tree/a17664aa2c0049f2a3027c8b59787c6eb9241267

When I replace the tensorflow/workspace.bzl from May 10 repo to current repo, the download_dependencies.sh works fine.

Any suggestions.
