### ISSUE TITLE
Custom model implementation to tensor flow lite micro speech example

### ISSUE THREAD

**Issue by hardware-dept** [tensorflow/tensorflow#34273]
Hi everyone.

Currently I am working with tensorflow lite micro speech example for stm32f7disco board and want to try it with my own trained model. Unfortunately, the result I have for now is that replacement of generated <tiny_conv>.cc file is not enough for that since my model doesn't pass some internal chekcups. Can somebody give an instruction on how to implement custom model to this project? And to be sure about the model can you give some explanations of parameters which are used in training and generating .tflite file?

**Comment by gadagashwini** [comment]
@hardware-dept, Please refer this [link](https://www.tensorflow.org/lite/microcontrollers/build_convert). Thanks!

**Comment by gadagashwini** [comment]
@hardware-dept, Is this still an issue? Thanks

**Comment by gadagashwini** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
