### ISSUE TITLE
Add ExtractImagePatches op to tensorflow lite (flex) whitelist

### ISSUE THREAD

**Issue by nstyler** [tensorflow/tensorflow#34280]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 16.04
- TensorFlow installed from (source or binary): source
- TensorFlow version (or github SHA if from source): 1.14 top of the tree 14 Nov2019 (last checkin 00fad90125b18b80fe054de1055770cfb8fe4ba3)

**Provide the text output from tflite_convert**

2019-11-14 17:57:00.806373: W tensorflow/lite/toco/tflite/operator.cc:2661] Op ExtractImagePatches is a valid TensorFlow op but has not been whitelisted for the TensorFlow Lite flex op set.
2019-11-14 17:57:00.806488: W tensorflow/lite/toco/tflite/operator.cc:2661] Op ExtractImagePatches is a valid TensorFlow op but has not been whitelisted for the TensorFlow Lite flex op set.
2019-11-14 17:57:00.806577: E tensorflow/lite/toco/toco_tooling.cc:462] We are continually in the process of adding support to TensorFlow Lite for more ops. It would be helpful if you could inform us of how this conversion went by opening a github issue at https://github.com/tensorflow/tensorflow/issues/new?template=40-tflite-op-request.md

**Comment by gadagashwini** [comment]
@nstyler, Please provide the exact sequence of commands / steps that you executed before running into the problem

**Comment by nstyler** [comment]
Hi! Thanks for a quick reply!

I used the next steps:

```
import tensorflow as tf
converter = tf.lite.TFLiteConverter.from_frozen_graph("aIN256.pb", ["Placeholder_1"], ["Squeeze"])
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS, tf.lite.OpsSet.SELECT_TF_OPS]
tflite_model = converter.convert()
```

# at this stage I get the error about ExtractImagePatches not been whitelisted for the TensorFlow Lite flex op set

**Comment by hvico** [comment]
Having the same problem here, have a model which uses ExtractImagePatches and I am unable to convert it to TFLITE using select_tf_ops since the op its not whitelisted.

**Comment by glemercier** [comment]
+1

**Comment by butterfly-coder** [comment]
Hello, all.
ExtractImagePatches op was added to tensorflow lite(flex) whitelist.
https://github.com/tensorflow/tensorflow/commit/7b180f700755b0a3fc0eb9de349f7caacc422d2d

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.

**Comment by namanbiyani** [comment]
Hey! Will it be possible for anyone to explain how do we use  tensorflow lite(flex)  to convert model having ExtractImagePatches op to tflite?
