### ISSUE TITLE
failed installing using virtualenv

### ISSUE THREAD

**Issue by itayguy** [tensorflow/tensorflow#343]
(tensorflow)itay@ubuntu:~/tensorflow$ pip install --upgrade https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.5.0-cp27-none-linux_x86_64.whl
Downloading/unpacking https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.5.0-cp27-none-linux_x86_64.whl
  Downloading tensorflow-0.5.0-cp27-none-linux_x86_64.whl (10.9Mb): 10.9Mb downloaded
  Running setup.py egg_info for package from https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.5.0-cp27-none-linux_x86_64.whl
    Traceback (most recent call last):
      File "<string>", line 14, in <module>
    IOError: [Errno 2] No such file or directory: '/tmp/pip-2LuRsH-build/setup.py'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 14, in <module>

IOError: [Errno 2] No such file or directory: '/tmp/pip-2LuRsH-build/setup.py'

----------------------------------------
Command python setup.py egg_info failed with error code 1 in /tmp/pip-2LuRsH-build

any help?

**Comment by vrv** [comment]
http://www.tensorflow.org/get_started/os_setup.html#pip-installation-issues ?  Let us know if those instructions don't help

**Comment by itayguy** [comment]
they don't help , that's why I opened an issue.
I was able to run it using docker.
