### ISSUE TITLE
error " 'tflite::FlatbufferModel' has not been declared "when use Tensorflow lite C++ API

### ISSUE THREAD

**Issue by Yooong-W** [tensorflow/tensorflow#34307]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04
- TensorFlow installed from (source or binary):source
- TensorFlow version (or github SHA if from source):r1.14

i run `bazel build //tensorflow/lite:libtensorflowlite` and `bazel build //tensorflow/lite:framework`,so i get libtensorflowlite.so and libframework.so. 
Then i use the library in my own code,but i got an error:

```
main.cpp: In function ‘int main()’:
main.cpp:9:59: error: ‘tflite::FlatbufferModel’ has not been declared
  std::unique_ptr<tflite::FlatBufferModel> model = tflite::FlatbufferModel::BuildFromFile("test1.tflite");
                                                           ^
main.cpp:17:10: error: ‘tflite::ops’ has not been declared
  tflite::ops::builtin::BuiltinOpResolver resolver;
          ^
main.cpp:17:42: error: expected ‘;’ before ‘resolver’
  tflite::ops::builtin::BuiltinOpResolver resolver;
                                          ^
main.cpp:19:43: error: ‘resolver’ was not declared in this scope
  tflite::InterpreterBuilder(*model.get(), resolver)(&interpreter);
                                           ^
```

the command i used:
`g++  -std=c++11 -I/home/wang/work/ARM-BAZEL/tensorflow-r1.14 -I/home/wang/work/ARM-BAZEL/tensorflow-r1.14/tensorflow/lite/tools/make/downloads/flatbuffers/include main.cpp -o test -L/home/wang/work/ARM-BAZEL/tensorflow-r1.14/bazel-bin/tensorflow/lite -ltensorflowlite -lframework`

i want know where is the problem chould be ? I'm relly not familiar with how to use tensorflow lite.

**Comment by ashishmagar600** [comment]
what happened.. how did you solved?
