### ISSUE TITLE
Tensorflow 1.15 doesn't exists within pip install

### ISSUE THREAD

**Issue by ugurkanates** [tensorflow/tensorflow#34302]
Thank you for submitting a TensorFlow documentation issue. Per our GitHub
policy, we only address code/doc bugs, performance issues, feature requests, and
build/installation issues on GitHub.

The TensorFlow docs are open source! To get involved, read the documentation
contributor guide: https://www.tensorflow.org/community/contribute/docs

## URL(s) with the issue:

Please provide a link to the documentation entry, for example:
https://www.tensorflow.org/install/pip

## Description of issue (what needs changing):
It says tensorflow 1.15 is final version for 1xx versions yet pip install 1.15 returns this

"$ pip3 install tensorflow==1.15
Collecting tensorflow==1.15
  Could not find a version that satisfies the requirement tensorflow==1.15 (from versions: 0.12.1, 1.0.0, 1.0.1, 1.1.0rc0, 1.1.0rc1, 1.1.0rc2, 1.1.0, 1.2.0rc0, 1.2.0rc1, 1.2.0rc2, 1.2.0, 1.2.1, 1.3.0rc0, 1.3.0rc1, 1.3.0rc2, 1.3.0, 1.4.0rc0, 1.4.0rc1, 1.4.0, 1.4.1, 1.5.0rc0, 1.5.0rc1, 1.5.0, 1.5.1, 1.6.0rc0, 1.6.0rc1, 1.6.0, 1.7.0rc0, 1.7.0rc1, 1.7.0, 1.7.1, 1.8.0rc0, 1.8.0rc1, 1.8.0, 1.9.0rc0, 1.9.0rc1, 1.9.0rc2, 1.9.0, 1.10.0rc0, 1.10.0rc1, 1.10.0, 1.10.1, 1.11.0rc0, 1.11.0rc1, 1.11.0rc2, 1.11.0, 1.12.0rc0, 1.12.0rc1, 1.12.0rc2, 1.12.0, 1.12.2, 1.12.3, 1.13.0rc0, 1.13.0rc1, 1.13.0rc2, 1.13.1, 1.13.2, 1.14.0rc0, 1.14.0rc1, 1.14.0, 2.0.0a0, 2.0.0b0, 2.0.0b1)
No matching distribution found for tensorflow==1.15
"

It should be corrected I think.

**Comment by yangw1234** [comment]
Hi, I just came across the problem myself, and I fixed it by upgrading pip to 19.0.

**Comment by gadagashwini** [comment]
@ugurkanates, PIP install TF 1.15 is available.
Please see the gist [here](https://colab.sandbox.google.com/gist/gadagashwini/21d328ab6113dce454199f711badb4cf/untitled263.ipynb). Thanks!

**Comment by mihaimaruseac** [comment]
Please upgrade pip.

**Comment by ColonelThirtyTwo** [comment]
Getting this issue even with updated pip and setuptools, both on Windows and Arch Linux:

```
C:\windows\system32>python -m pip install tensorflow==1.15
ERROR: Could not find a version that satisfies the requirement tensorflow==1.15 (from versions: none)
ERROR: No matching distribution found for tensorflow==1.15

C:\windows\system32>python -m pip --version
pip 19.3.1 from C:\Program Files (x86)\Python37-32\lib\site-packages\pip (python 3.7)

C:\windows\system32>python --version
Python 3.7.4
```

```
col@col-siris ~/AIDungeon> python -m pip install tensorflow==1.15.0
ERROR: Could not find a version that satisfies the requirement tensorflow==1.15.0 (from versions: none)
ERROR: No matching distribution found for tensorflow==1.15.0
col@col-siris ~/AIDungeon> python -m pip --version
pip 19.3.1 from /usr/lib/python3.8/site-packages/pip (python 3.8)
col@col-siris ~/AIDungeon> python --version
Python 3.8.1
```

**Comment by mihaimaruseac** [comment]
https://pypi.org/project/tensorflow/#files

Also, please see https://github.com/tensorflow/tensorflow/issues/33374#issuecomment-571074915

**Comment by MasterGroosha** [comment]
Even with the latest pip there is no 1.15 package available

**Comment by mihaimaruseac** [comment]
@MasterGroosha : 32 bits python? Python 2? Python 3.8?

**Comment by MasterGroosha** [comment]
@mihaimaruseac Yeah, my bad, I didn't understand your messages. With Python 3.8, I cannot install TF-1.15, but I did install it with 3.7.6

**Comment by raphtlw** [comment]
Also encountered this issue but pip showed a different message for me

```zsh
ERROR: Could not find a version that satisfies the requirement tensorflow==1.15 (from versions: 2.2.0rc1, 2.2.0rc2, 2.2.0rc3, 2.2.0rc4, 2.2.0)
ERROR: No matching distribution found for tensorflow==1.15
```

**Comment by mihaimaruseac** [comment]
@raphtlw that is because you are using python3.8 which is not supported in TF before 2.2

**Comment by adelriosantiago** [comment]
@mihaimaruseac So what are the correct versions for the issue that @raphtlw is having? Should I downgrade from python3.8 to something else?

**Comment by mihaimaruseac** [comment]
Yes, [any version of Python above 3.5 and below 3.8](https://www.tensorflow.org/install/pip#system-requirements)

**Comment by lamak** [comment]
Check your python version, tensorflow officially supports up to 3.7
