### ISSUE TITLE
Feature Request: Pass 'elapsed_secs' into LoggingHook string formatter.

### ISSUE THREAD

**Issue by kiunthmo** [tensorflow/tensorflow#34308]
Can the tf.train.LoggingTensorHook be changed to pass the time elapsed into the string formatter?

It would be quite easy to add it to the dictionary of values already being passed to the formatter function. Currently you have to choose between your own custom string formatter, and seeing the time elapsed - I think it would be quite easy to have both with a small change to the code.

Thanks.

**Comment by ravikyram** [comment]
@kiunthmo 
Do you have any use case that requires the feature you are interested in? Please feel free to submit a PR if you have use cases that supports that feature.Thanks!

**Comment by ravikyram** [comment]
@kiunthmo 

Any update on this issue please?. Thanks!

**Comment by kiunthmo** [comment]
My use case is during evaluation to monitor the performance. For short, scalar tensors you don't really need to do much formatting, but if i'm comparing two larger tensors it can be useful to align them using formatting. The problem is that by using the formatter you sacrifice the elapsed time.

In LoggingHook source you can see that when there is a formatter only the tensor values are passed to said formatter:

```
  def _log_tensors(self, tensor_values):
    original = np.get_printoptions()
    np.set_printoptions(suppress=True)
    elapsed_secs, _ = self._timer.update_last_triggered_step(self._iter_count)
    if self._formatter:
      logging.info(self._formatter(tensor_values))
    else:
      stats = []
      for tag in self._tag_order:
        stats.append("%s = %s" % (tag, tensor_values[tag]))
      if elapsed_secs is not None:
        logging.info("%s (%.3f sec)", ", ".join(stats), elapsed_secs)
      else:
        logging.info("%s", ", ".join(stats))
    np.set_printoptions(**original)
```

This could be easily changed to append to elapsed seconds to the values, or pass it to the formatter as a second argument.

**Comment by karmel** [comment]
Thanks @kiunthmo for the request. I am wary of complicating the code for the hook, and we are unlikely to have cycles for this, but we could consider a PR if you send one.

**Comment by marindred** [comment]
I would like to work on this, hopefully I'll have a PR that solves it soon.

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.
