### ISSUE TITLE
Feature_columns  causes model training to be slow

### ISSUE THREAD

**Issue by ztz818** [tensorflow/tensorflow#34300]
I use tf2.0 functional API to build the model, and use feature columns to process the data. I find that each step of my training takes a long time, and the CPU utilization is very low. My device is a 16 core CPU. When I don't use feature columns, I can run the model with multiple cores. I'm confused. Can someone answer this question?
![image](https://user-images.githubusercontent.com/26998046/68914950-39d7f100-079b-11ea-9f54-7d1053a5f623.png)
In a certain training, each step takes more than 100 ms, which is very slow
![image](https://user-images.githubusercontent.com/26998046/68915018-6b50bc80-079b-11ea-811c-37cb22bf237c.png)
The utilization rate of cou in the training process is very low, and it does not play the multi-core performance at all.

The result is a test when using the official feature _columns tutorial.https://www.tensorflow.org/tutorials/structured_data/feature_columns?hl=zh-CN
When I use the MNIST tutorial to run in the same environment, CPU utilization is completely multi-core performance.
Has anyone encountered this problem? Thank you very much.

**Comment by ztz818** [comment]
I want to know why feature_columns cause model training not to use multi-core CPU

**Comment by oanush** [comment]
@ztz818 ,
When tried running the tutorial for TF-2.0, I was able to run it without any issues. Please find the [gist](https://colab.sandbox.google.com/gist/oanush/014444e1e04149353045f14d15297af6/34300.ipynb) of colab. Kindly let us know if your are using any different code? provide us with the same.

**Comment by oanush** [comment]
@ztz818 ,
Any update on the issue ?Thanks!

**Comment by oanush** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Comment by GoingMyWay** [comment]
The feature_columns in TF 2.x is really slow in eager mode when initialization, and very very slow when forwarding. I am annoyed by TF 2.x. Some docs in feature_columns of TF 2.x are only copied from TF 1.x. For example, `input_layer` is not available in TF 2.x, but still on docs of TF 2.x.

**Comment by osljw** [comment]
2021， tf2.4, same problem,
