### ISSUE TITLE
Ignoring gpu device with Cuda multiprocessor count: 7.

### ISSUE THREAD

**Issue by gaphex** [tensorflow/tensorflow#3430]
I am unable to run TF on a GPU, despite the fact that I have 2 CUDA-enabled K4200 NVIDIA QUATTRO (Compute Capability 3.0)

### Environment info
Operating System: linux 14.04 x64

Installed version of CUDA and cuDNN: 
1. CUDA 7.5
2. cuDNN 4

If installed from binary pip package, provide:

1. Ubuntu/Linux 64-bit, GPU enabled, Python 2.7
2. TF v0.9.0

### Steps to reproduce
1. Run IPython Notebook
2. Run a tensorflow session (I was doing Udacity DL course)
3. In IPython log, observe:

I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:924] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
I tensorflow/core/common_runtime/gpu/gpu_init.cc:102] Found device 0 with properties:
name: Quadro K4200
major: 3 minor: 0 memoryClockRate (GHz) 0.784
pciBusID 0000:03:00.0
Total memory: 4.00GiB
Free memory: 3.96GiB
W tensorflow/stream_executor/cuda/cuda_driver.cc:572] creating context when one is currently active; existing: 0x3b717e0
I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:924] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
I tensorflow/core/common_runtime/gpu/gpu_init.cc:102] Found device 1 with properties:
name: Quadro K4200
major: 3 minor: 0 memoryClockRate (GHz) 0.784
pciBusID 0000:04:00.0
Total memory: 4.00GiB
Free memory: 3.86GiB
I tensorflow/core/common_runtime/gpu/gpu_init.cc:126] DMA: 0 1
I tensorflow/core/common_runtime/gpu/gpu_init.cc:136] 0:   Y Y
I tensorflow/core/common_runtime/gpu/gpu_init.cc:136] 1:   Y Y
I tensorflow/core/common_runtime/gpu/gpu_device.cc:793] Ignoring gpu device (device: 0, name: Quadro K4200, pci bus id: 0000:03:00.0) with Cuda multiprocessor count: 7. The minimum required count is 8. You can adjust this requirement with the env var TF_MIN_GPU_MULTIPROCESSOR_COUNT.
I tensorflow/core/common_runtime/gpu/gpu_device.cc:793] Ignoring gpu device (device: 1, name: Quadro K4200, pci bus id: 0000:04:00.0) with Cuda multiprocessor count: 7. The minimum required count is 8. You can adjust this requirement with the env var TF_MIN_GPU_MULTIPROCESSOR_COUNT.

### What have you tried?
1. Setting TF_MIN_GPU_MULTIPROCESSOR_COUNT to 4, both locally and system-wide

### Logs or other output that would be helpful
echo $TF_MIN_GPU_MULTIPROCESSOR_COUNT
4

Am I missing something? Setting the environment variable seems to have no effect.

**Comment by concretevitamin** [comment]
Can you try 
```
bazel --copt=-DTF_MIN_GPU_MULTIPROCESSOR_COUNT=4 build <...>
```
or 
```
TF_MIN_GPU_MULTIPROCESSOR_COUNT=4 bazel build <...>
```

Additionally, perhaps add `--copt=-DTF_EXTRA_CUDA_CAPABILITIES=3.0`.

**Comment by gaphex** [comment]
According to 

I tensorflow/core/common_runtime/gpu/gpu_device.cc:839] Creating TensorFlow device (/gpu:0) -> (device: 0, name: Quadro K4200, pci bus id: 0000:03:00.0)
I tensorflow/core/common_runtime/gpu/gpu_device.cc:839] Creating TensorFlow device (/gpu:1) -> (device: 1, name: Quadro K4200, pci bus id: 0000:04:00.0)

it now seems to work correctly. Thanks!
