### ISSUE TITLE
Error when importing tensorflow

### ISSUE THREAD

**Issue by chisom812** [tensorflow/tensorflow#34314]
hello github
i have been having issues importing tensorflow
first i installed the tensorflow==1.31 and i got an error attached below while trying to import tensorflow.
someone suggested i use conda install tensorflow which i did and when trying to import tensorflow my python stops working and my kernel dies.
i was also instructed to upgrade numpy using pip install numpy --upgrade. which i also did. but on trying to import tensorflow again my computer sends a notification of python stops working and kernel dies and restarts again.
my computer is 4g Ram
please your suggestion will be needed. i am stuck

**Comment by joekiller** [comment]
Seems like a pipy distribution problem. I cannot get 2.0.0 either.

**Comment by joekiller** [comment]
Also seemed to only affect me running python 3.8. I reverted to 3.7 and it found it fine.

**Comment by chisom812** [comment]
How do I revert my python to 2.7 and I don't understand your first comment please can you explain more

**Comment by gowthamkpr** [comment]
@chisom812 Please following the template [here](https://github.com/tensorflow/tensorflow/issues/new/choose)  as the current information is too vague for us to help you. Thanks!

**Comment by gowthamkpr** [comment]
@chisom812 Can you please respond to the question above. Thanks!

**Comment by gowthamkpr** [comment]
Closing this issue as it has been inactive for more than 3 weeks. Please add additional  comments and we can open this issue again. Thanks!
