### ISSUE TITLE
tf-lite version info

### ISSUE THREAD

**Issue by peter197321** [tensorflow/tensorflow#34310]
I have preinstalled TensorFlow - lite on my system, is it possible to get version information of it programmatically? If so - how?
Thanks.

**Comment by ymodak** [comment]
TF Lite comes with TensorFlow prebuilt binary. So it will be the same version as your installed TF.
From python interpreter you may try;
```python
import tensorflow as tf
tf.__version__
```

**Comment by peter197321** [comment]
Thanks. How about in C++ case?

Dne pá 15. 11. 2019 19:25 uživatel Yasir Modak <notifications@github.com>
napsal:

**Comment by ymodak** [comment]
The version will be same and you may use the above snippet to get tf version. Thanks!
Closing this issue now, feel free to reopen if have any questions. Thanks!
