### ISSUE TITLE
missing 'train' module

### ISSUE THREAD

**Issue by bgenchel** [tensorflow/tensorflow#3432]
trying to follow this document: https://www.tensorflow.org/versions/r0.9/how_tos/distributed/index.html

can't import tf.train because train doesn't exist.

i looked through the repo; it appears that's a correct appraisal. TF does not have a train package.

??

**Comment by concretevitamin** [comment]
Please *do* fill in the issue template to include more info.

`tf.train` should work and many people run the classes in it regularly.

**Comment by aselle** [comment]
Automatically closing due to lack of recent activity. Please reopen if further information becomes available.
