### ISSUE TITLE
prepare_attention API of tensorflow 1.0.0 equivalent in tensorflow 1.13.1

### ISSUE THREAD

**Issue by lpcoutinho** [tensorflow/tensorflow#34328]
What is the equivalent API in tensorflow 1.13.1 for prepare_attention(tf.contrib.seq2seq.prepare_attention) of tensorflow 1.0.0?

Thanks!!!

**Comment by oanush** [comment]
@lpcoutinho ,
Hi,Please note that `tf.contrib.seq2seq.DynamicAttentionWrapper `will work. Also for 2.0 contrib has been removed and the equivalent is[ Addon-Seq2Seq](https://github.com/tensorflow/addons/blob/master/tensorflow_addons/seq2seq/README.md).Thanks!

**Comment by oanush** [comment]
@lpcoutinho ,
Any update on the issue ?Thanks!

**Comment by oanush** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
