### ISSUE TITLE
Collective AllGather Fails to Collect Tensors in Multi-(TF)Task Between-Graph Distributed Execution

### ISSUE THREAD

**Issue by pengwu22** [tensorflow/tensorflow#34322]
**System information**
- OS Platform and Distribution: Ubuntu 18.04
- TensorFlow installed from (source or binary): binary whl
- TensorFlow version (use command below): `tensorflow-gpu==2.0.0`
- Python version: 3.6.8
- CUDA/cuDNN version: 10.0 / 7.6.4, recommended with the support of `nccl`
- GPU model and memory: GeForce GTX 1080 Ti

**Describe the current behavior**
First, we need the two files below.
`cluster.py`:
```python
import time
from multiprocessing import Process

from tensorflow.core.protobuf import config_pb2
from tensorflow.python.training.server_lib import Server

CLUSTER_SPEC = {
    "worker": [
        "localhost:14286",
        "localhost:14287"
    ]
}

GROUP_SIZE = 4


def _configure(group_size):
    gpu_options = config_pb2.GPUOptions(
        visible_device_list='0,1',
        per_process_gpu_memory_fraction=0.7 / group_size
    )
    experimental = config_pb2.ConfigProto.Experimental(collective_nccl=True)
    experimental.collective_group_leader = '/job:worker/replica:0/task:0'
    return config_pb2.ConfigProto(gpu_options=gpu_options, experimental=experimental)


class TFCluster:
    def __init__(self, cluster_spec):
        self._cluster_spec = cluster_spec
        self._num_worker = len(self._cluster_spec.get("worker", []))
        self._tf_servers = []

    def start(self):
        def server(job_name: str, task_index: int):
            s = Server(self._cluster_spec,
                       job_name=job_name,
                       task_index=task_index,
                       config=_configure(GROUP_SIZE))
            s.join()

        assert self._num_worker >= 1
        for i in range(self._num_worker):
            self._tf_servers.append(Process(target=server,
                                            args=("worker", i), daemon=True))
            # break
        for proc in self._tf_servers:
            proc.start()

    def stop(self):
        for proc in self._tf_servers:
            proc.terminate()


if __name__ == '__main__':
    cluster = TFCluster(CLUSTER_SPEC)
    cluster.start()
    time.sleep(5)
    input('Press Enter to Stop.')
    cluster.stop()
```
`task.py`:
```python
import argparse

import numpy as np
import tensorflow as tf
from tensorflow.core.protobuf import config_pb2
from tensorflow.python import ops
from tensorflow.python.client.session import Session
from tensorflow.python.ops import collective_ops

from cluster import CLUSTER_SPEC, GROUP_SIZE

VAR = np.array([0.1, 1.1, 2.1, 3.1, 4.1, 5.1, 6.1, 7.1])
VAR_TASK_INDEX = 0


def test_collective(job_name, task_index, num_gpus):
    worker_device = "/job:%s/task:%d" % (job_name, task_index)
    master_target = "grpc://" + CLUSTER_SPEC[job_name][task_index]
    print('> Session Target:', master_target)

    with ops.Graph().as_default(), Session(target=master_target) as sess:
        def run(x):
            run_options = config_pb2.RunOptions()
            run_options.experimental.collective_graph_key = task_index + 1
            # Different positive graph key for different task to avoid racing conditions.
            return sess.run(x, options=run_options)

        with ops.device('/job:worker/task:%d/device:CPU:0' % VAR_TASK_INDEX):  # make sure all use the same variable
            var = tf.Variable(VAR, name='W')

        targets = []
        collectives = []
        for i in range(num_gpus):
            with ops.device(worker_device + '/device:GPU:' + str(i)):
                t = var + 0.2 * task_index + 0.1 * i
                targets.append(t)
                collectives.append(
                    collective_ops.all_gather(
                        t,
                        group_size=GROUP_SIZE,
                        group_key=1, instance_key=1
                    )
                    # collective_ops.all_reduce(
                    #     t,
                    #     group_size=GROUP_SIZE,
                    #     group_key=1, instance_key=1, merge_op='Add', final_op='Div'
                    # )
                )

        run(tf.compat.v1.global_variables_initializer())

        var_value = run(var)
        print('> Variable Value:', var_value)

        targets_value = run(targets)
        print('> Targets Value:', targets_value)

        collectives_value = run(collectives)
        print('> Collectives Value:', collectives_value)


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.register("type", "bool", lambda v: v.lower() == "true")

    parser.add_argument(
        "--job_name",
        type=str,
        default="",
    )
    parser.add_argument(
        "--task_index",
        type=int,
        default=0,
    )
    FLAGS, unparsed = parser.parse_known_args()
    num_gpus_per_node = 2
    test_collective(job_name=FLAGS.job_name, task_index=FLAGS.task_index, num_gpus=num_gpus_per_node)
```

Then one could use the following commands to run the experiment:
```bash
python cluster.py
python task.py --job_name=worker --task_index=0
python task.py --job_name=worker --task_index=1
```

* EXPERIMENT 1 (FAILURE):
  * Run the above code without change. Note that the `GROUP_SIZE=4`. It is programmed to all gather the 4 tensors across `task:0/GPU:0/` `task:0/GPU:1` `task:1/GPU:0` `task:1/GPU:1`, but gets stuck. If one turns on the env `TF_CPP_MIN_VLOG_LEVEL=1` , one will notice it successfully gathers the values but gets stuck right after it, specifically after `tensorflow/core/common_runtime/collective_rma_local.cc:105] PostToPeer ...`

* EXPERIMENT 2 (SUCCESS):
 * Run the above code with `GROUP_SIZE=2`. On each task, It is programmed to gather 2 tensors on the 2 GPUs of that task. For example, on `task 0`, it gathers `task:0/GPU:0` and `task:0/GPU:1` and it succeeds.

* EXPERIMENT 3 (SUCCESS):
* Run the above code with the original `GROUP_SIZE=4` but with the `all_reduce` op (as provided in the commented code) instead of `all_gather`. It succeeds.

**Describe the expected behavior**

It is expected that all the experiments above should succeed. However, EXPERIMENT 1 fails, but 2 and 3 succeed. 3 means the collective executor works in a multi-task way of executing the graph on `all_reduce`. 2 means `all_gather` works if only collects tensor within one graph. 1 means the bug where `all_gather` fails to collect tensors across the tasks. 

**Code to reproduce the issue**
See above

**Comment by pw2393** [comment]
@rmothukuru Thanks for the label. But it may be a `comp:op` bug for `collective_gather` instead of a GPU bug.

**Comment by pw2393** [comment]
Hi @dubey, wondering if you might have any idea on whether the above code misuses anything or something else causes that. 😄

**Comment by zhisbug** [comment]
wonder if there is any update on this issue?

**Comment by zhisbug** [comment]
wonder if there is any update on this issue?

**Comment by sushreebarsa** [comment]
Was able to replicate the issue in TF 2.6.0-dev20210529,please find the gist [here](https://colab.research.google.com/gist/sushreebarsa/5ae77e936421ae6648a77903787705e7/untitled80.ipynb#scrollTo=hXKlZ2teJKXP)..Thanks !

**Comment by kumariko** [comment]
I was able to reproduce the issue in TF 2.6, please find the gist [**`here`**](https://colab.research.google.com/gist/kumariko/84045750f10af051765b7902c3a9f5ec/untitled80.ipynb#scrollTo=_J8m072tMdiO).

**Comment by Venkat6871** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
