### ISSUE TITLE
TF World '19 Talk: Facemesh with TF.js in the browser

### ISSUE THREAD

**Issue by kavikode** [tensorflow/tensorflow#34330]
Just saw the wonderful Unlocking the power of ML for your JavaScript applications with TensorFlow.js talk, link: https://youtu.be/kKp7HLnPDxc.

I'd also like to try the code of using Facemesh in the browser. Following the example code in the video at 25:48, I went to https://cdn.jsdelivr.net/npm/@tensorflow-models/facemesh. 

However, I get the message "Failed to resolve the requested file." 

Will you please help me find the Facemesh model?

**Comment by ravikyram** [comment]
This issue is more suitable for TensorFlow TFjs repo. Please post it on TFjs repo from [here.](https://github.com/tensorflow/tfjs/issues/new). Thanks!

**Comment by ravikyram** [comment]
@kavikode 
Please, let us know if you have posted the issue in TensorFlow TFjs repo ?. Thanks!

**Comment by ravikyram** [comment]
I am closing the issue as this issue is related to TFjs repo. Thanks!
