### ISSUE TITLE
default installed version of tensorflow lite arduino library is pre-compiled, causing confusing error reports

### ISSUE THREAD

**Issue by ladyada** [tensorflow/tensorflow#34334]
hiya @petewarden ive been re-porting my demos (hooray) for Arduino boards
https://learn.adafruit.com/tensorflow-lite-for-edgebadge-kit-quickstart

right now when folks install the TensorFlow library it defaults to the pre-compiled version, which causes very obscure errors about register arguments if they are not using the exact same processor.

https://learn.adafruit.com/tensorflow-lite-for-edgebadge-kit-quickstart/troubleshooting#uses-vfp-register-arguments-and-libtensorflowlite-dot-a-does-not-error-10-2

please make the default non-pre-compiled...Arduino IDE has a huge collection of supported boards, and as is, will confuse a lot of people :)

**Comment by petewarden** [comment]
Sorry, I missed this one originally! I will dig into this, since we are keen to have widespread support.

**Comment by ladyada** [comment]
thank u 👍

**Comment by petewarden** [comment]
I've contacted the Arduino IDE team for help on this, I hope to have more progress to report soon.

**Comment by ladyada** [comment]
hihi checkin' in on this issue - i saw also SFE bumped into the same issue

https://learn.sparkfun.com/tutorials/programming-the-sparkfun-edge-with-arduino

`NOTE: It is imperative that you install the non-precompiled version of the library. Installing the pre-compiled library will only lead to failure and sadness.`

**Comment by petewarden** [comment]
The Arduino team now have a pending PR which they believe should fix this problem:
https://github.com/arduino/arduino-cli/pull/512

Could you take a look and provide feedback? Thanks for your patience!

**Comment by ladyada** [comment]
super rad! i will! :) i published a guide this weekend - https://learn.adafruit.com/tensorflow-lite-for-circuit-playground-bluefruit-quickstart

**Comment by petewarden** [comment]
I think this is now fixed and checked in, so closing! Let me know if I'm wrong and I'll reopen, thanks for your work on this.
