### ISSUE TITLE
TFLite allocate tensors fails: (CONCATENATION) failed to prepare after input shape resize

### ISSUE THREAD

**Issue by Angtrim** [tensorflow/tensorflow#34345]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):  **Yes**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): **OSX**
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: **No**
- TensorFlow installed from (source or binary): **binary** 
- TensorFlow version (use command below):  **2.1.0-dev20191113**
- Python version: **3.7.4**

**Describe the current behavior**

I create a fully convolutional simple model using tf.keras API.
I convert the model to TFlite.
I resize the shape of the input tensor, but when I ask the interpreter to allocate the tensors, I get this error:

`RuntimeError: tensorflow/lite/kernels/concatenation.cc:74 t->dims->data[d] != t0->dims->data[d] (24 != 52)Node number 12 (CONCATENATION) failed to prepare.
`

**Describe the expected behavior**

I expect the interpreter to be able to resize all the tensors.
Below you can find the simple model I've built to reproduce this issue.
What I've notice is that without the `Concatenate` op the allocation works correctly.

**Code to reproduce the issue**

```
from tensorflow.keras.layers import Conv2D, UpSampling2D, LeakyReLU, Concatenate
from tensorflow.keras import Model, layers
from tensorflow import keras
import tensorflow as tf

# Encoder
encoder_input = keras.Input(shape=(28, 28, 1), name='img')
conv1 = layers.Conv2D(16, 3, activation='relu')(encoder_input)
conv2 = layers.Conv2D(32, 3, activation='relu')(conv1)
max1 = layers.MaxPooling2D(3)(conv2)
conv3 = layers.Conv2D(32, 3, activation='relu')(max1)
conv4 = layers.Conv2D(16, 3, activation='relu')(conv3)
encoder_output = layers.GlobalMaxPooling2D()(conv4)
encoder = keras.Model(encoder_input, encoder_output, name='encoder')

# Decoder
resh = layers.Reshape((4, 4, 1))(encoder_output)
upconv1 = layers.Conv2DTranspose(16, 3, activation='relu')(resh)
upconv2 = layers.Conv2DTranspose(32, 3, activation='relu')(upconv1)
upsample = layers.UpSampling2D(3)(upconv2)
conc = layers.Concatenate()([conv2,upsample])
conv5 = layers.Conv2DTranspose(16, 3, activation='relu')(conc)
decoder_output = layers.Conv2DTranspose(1, 3, activation='relu')(conv5)

# autoencoder
autoencoder = keras.Model(encoder_input, decoder_output, name='autoencoder')

# conversion
converter = tf.lite.TFLiteConverter.from_keras_model(autoencoder)
tflite_model = converter.convert()
open("model.tflite", "wb").write(tflite_model)

# inference
interpreter = tf.lite.Interpreter(model_path="model.tflite")
input_details = interpreter.get_input_details()
interpreter.resize_tensor_input(input_details[0]["index"],[1,56,56,1])
interpreter.allocate_tensors()
```

**Comment by liyunlu0618** [comment]
WIthout resizing the input does your model convert fine?

**Comment by Angtrim** [comment]
@liyunlu0618 Yes. Without resizing it works fine.
I think I've managed to find the issue.
The problems is not the concatenation, but the UpSampling2D layer.

When the graph is converted, the shape of the input tensor that is used by the UpSampling2D layer to resize the image is converted to a constant and hardcoded in the UpSampling2D layer.
So, when the Input of the graph is resized, the transformation it is not propagated to the UpSampling2D layer since the OPs used to calculate the new size have been folded.
So, since the UpSampling2D layer is not resized, the Concatenation produces an error

The solution would be to prevent the converter to convert to constant the part of the graph that is used by the UpSampling2D layer to calculate the new size.

As a workaround, I've coded a custom UpSampling2D layer that takes as a resize shape the value of another Input tensor instead of calculating it using the input image.

**Comment by harsh306** [comment]
@Angtrim , can you explain a bit about the workaround
Did you use,  upsample = tflite_interpreter.get_tensor_details() and then maually change the shapes according to the inputs, using resize_tensor_input ?

**Comment by Angtrim** [comment]
@harsh306 To apply my workaround, these are the steps you have to follow:
1) Edit your model input: you should add a second input tensor (a proper one, like if it was another input image), made just of 2 floats, so that during training and inference you can pass the size of your image. 
2) Edit the resize nodes: now that you have a second input, you should connect it to the resize node passing it as the "size" parameter (if you look [here](https://www.tensorflow.org/api_docs/python/tf/image/resize), the "size" param is a tensor).
Since you probably have more than one upsampling layers, every resize node should take a multiplied version of the "size" tensor.
3) During training you add to your data the size of the image (probably constant in all the dataset) and pass it to the network.
4) After training, you can convert it to tflite. Thanks to this workaround, the converter can't hardcode the size of the resize nodes, since it's not anymore calculated on the size of the previous node but it is expected to arrive as data.
5) During tflite inference, you use `resize_tensor_input` on the image input tensor, and in the size tensore you have added you pass the image size.

**Comment by rachit2608** [comment]
@Angtrim, Hi, I am trying to follow the same approach and able to infer the pb file as well. Because to infer pb file we specify size in feeddict.. But, while converting to tflite it doesnt know the value of size. Hence, it cant make resizebilinear layer. And I am not able to convert to tflite successfully. How did you tackle this issue? Can u share code snippet if possible for tflite conversion?
Thanks.

**Comment by mohantym** [comment]
Hi @Angtrim , was able to replicate in 2.1 and resolve in 2.6 without any error . Providing [Gist ](https://colab.research.google.com/gist/mohantym/220523097c97de4508281fa9931adbc9/github_34345.ipynb)for reference.
