### ISSUE TITLE
save method shows buggy/confusing behaviour

### ISSUE THREAD

**Issue by nikochiko** [tensorflow/tensorflow#34348]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Google Colab 
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: NN
- TensorFlow installed from (source or binary): NN
- TensorFlow version (use command below): 2.0.0
- Python version: 3.6
- Bazel version (if compiling from source): NN
- GCC/Compiler version (if compiling from source): NN
- CUDA/cuDNN version: NN
- GPU model and memory: NN

**Describe the current behavior**
tf.keras.Model.save shows confusing behavior with the save_format argument.
See [gist](https://colab.research.google.com/gist/nikochiko/7a624ae90563b831d5229eb0ee5b0d41/tf_model_save_buggy.ipynb).
Even when save_format is set as  'tf', the model is saved as 'h5' if the filepath ends in suffix '.h5'
Also, it defaults random string arguments to tf format. 

**Describe the expected behavior**
The value of the save_format argument should be the format of the saved file irrespective of the filepath. 
Or else, there should be a boolean argument like 'save_as_h5' instead.

**Code to reproduce the issue**
https://colab.research.google.com/gist/nikochiko/7a624ae90563b831d5229eb0ee5b0d41/tf_model_save_buggy.ipynb#scrollTo=1H73RxH5sTgl

**Other info / logs**
[Source code](https://github.com/tensorflow/tensorflow/blob/r2.0/tensorflow/python/keras/engine/network.py#L923-L975)
[Outdated documentation](https://www.tensorflow.org/api_docs/python/tf/keras/Model#save)
Updated docs for current behavior in [PR](https://github.com/tensorflow/tensorflow/pull/34347/files)

**More details**
model.save_weights handles it better: see [gist](https://colab.research.google.com/gist/nikochiko/ff693562546dbda5d5868ec7e7d75bad/tf_save_weights.ipynb)

**Comment by rmothukuru** [comment]
Could reproduce the issue with TF Version 2.0. Here is the [Gist](https://colab.sandbox.google.com/gist/rmothukuru/565a2bee7543a888a9677813b9e0447a/tf_model_save_buggy.ipynb).

**Comment by nikochiko** [comment]
@rmothukuru @k-w-w I can make a fix for this in accordance with the `save_weights` method. Shall I start working?

**Comment by k-w-w** [comment]
That would be great! Reviewing the PR now
