### ISSUE TITLE
Serialization support for RaggedTensor

### ISSUE THREAD

**Issue by MikeOfZen** [tensorflow/tensorflow#34349]
**System information**
- TensorFlow version (you are using):2.0.0
- Are you willing to contribute it (Yes/No):No

**Describe the feature and the current behavior/state.**
Currently, there is no support for serializing RaggedTensors similiraly to tf.io.serialize_tensor

**Will this change the current api? How?**
This shouldn't affect any other functionality

**Who will benefit with this feature?**
Users of ragged tensors wishing to use TFrecords

**Comment by edloper** [comment]
Here's some simple code to serialize and deserialize ragged tensors (or any other composite tensors, like SparseTensor), by breaking them into component tensors and serializing those.

```
def serialize_composite(rt):
  components = tf.nest.flatten(rt, expand_composites=True)
  return tf.stack([tf.io.serialize_tensor(t) for t in components])

def deserialize_composite(serialized, type_spec):
  component_specs = tf.nest.flatten(type_spec, expand_composites=True)
  components = [tf.io.parse_tensor(serialized[i], spec.dtype) 
                   for i, spec in enumerate(component_specs)]
  return tf.nest.pack_sequence_as(type_spec, components, expand_composites=True)
```

Example use:

```
>>> rt = tf.ragged.constant([[1, 2], [3], [4, 5, 6]])
>>> serialized = serialize_composite(rt)
>>> print(serialized)
tf.Tensor(
[b'\x08\x03\x12\x04\x12\x02\x08\x06"...etc])
>>> rt_spec = tf.RaggedTensorSpec(dtype=tf.int32, ragged_rank=1)
>>> deserialized = deserialize_composite(serialized, rt_spec)
>>> print(deserialized)
<tf.RaggedTensor [[1, 2], [3], [4, 5, 6]]>
```

A couple notes:

* The tensor returned by `serialize_composite` will be a vector with shape `[num_components]`.  For a RaggedTensor with `ragged_rank=1`, `num_components=2`.
* You need to specify the TypeSpec when deserializing.  For RaggedTensorSpec, you'll need to at least provide the dtype of values and the ragged_rank (i.e., the number of ragged dimensions).
* If you want to use RaggedTensors with TFRecords, you may also consider using [tf.io.RaggedFeature](https://www.tensorflow.org/api_docs/python/tf/io/RaggedFeature) with `tf.io.parse_example`.

**Comment by edloper** [comment]
Closing this issue; but please re-open if you feel it's not addressed.

**Comment by Nilabhra** [comment]
@edloper 
Hi! I am currently writing ragged tensors to and from TFRecords using slight modifications to your functions:

```python
def serialize_composite(rt):
    components = tf.nest.flatten(rt, expand_composites=True)
    return tf.io.serialize_tensor(
        tf.stack([tf.io.serialize_tensor(t) for t in components])
    ).numpy()

def deserialize_composite(serialized, type_spec):
    serialized = tf.io.parse_tensor(serialized, tf.string)
    component_specs = tf.nest.flatten(type_spec, expand_composites=True)
    components = [
        tf.io.parse_tensor(serialized[i], spec.dtype)
        for i, spec in enumerate(component_specs)
    ]
    return tf.nest.pack_sequence_as(type_spec, components, expand_composites=True)
```

But with this method, I am having to write the ragged tensors as bytes and read them as `FixedLenFeature` of type `tf.string`. Is there anyway I can directly read them from the TFRecords as `RaggedTensor`?
