### ISSUE TITLE
Image preprocessing for transfer learning confusing

### ISSUE THREAD

**Issue by jsgonsette** [tensorflow/tensorflow#34340]
I'm really confused about what preprocessing to apply on image data when working with pre-trained models for transfer learning. Of course, this is very specific for each model, but I thought Keras brought some disambiguation by bringing the _**preprocess_input**_ function. By using it, users should normally not worry about how to transform an image before pushing it into the pre-trained model.

I recently tried to use one of such model provided in Tensorflow 2.Keras. Even if this function exists, the related documentation is, let's say, minimal:
https://www.tensorflow.org/api_docs/python/tf/keras/applications/mobilenet_v2/preprocess_input

But what is very disturbing is that this function is not used at all in the provided tutorials. For example, this one (https://www.tensorflow.org/tutorials/images/transfer_learning_with_hub) pre-processes images by dividing raw pixels by 255.

> image_generator = tf.keras.preprocessing.image.ImageDataGenerator(rescale=1/255)

In this other tutorial (https://www.tensorflow.org/tutorials/images/transfer_learning), pre-processing is done like this: 

> image = (image/127.5) - 1

However, both tutorial are supposed to use a **mobilenet_v2** model pre-trained on _ImageNet_

This makes **3 different ways to process an image**, without any helping documentation to shed some light on what appears to me like "black magic". Any help would be welcome, along with an appropriate documentation of course.

**Comment by developer22-university** [comment]
HI, interested in solving your issue.

**Comment by developer22-university** [comment]
check if its fine

**Comment by rmothukuru** [comment]
@jsgonsette,
Thank you for the detailed explanation. This issue seems to be related to reusing Pre-Trained Models. So, it is better raised in [TF Hub Repository](https://github.com/tensorflow/hub/issues), as the issues in that Repo will be looked into by the experts in Pre-Trained Models. Thanks!

**Comment by jsgonsette** [comment]
Ok, I'm doing that.

**Comment by rmothukuru** [comment]
@jsgonsette,
Closing the issue as it has been raised in TF Hub Repo. Thanks!
