### ISSUE TITLE
object_detection  dataset could not be checkpointed

### ISSUE THREAD

**Issue by zhanghaocol** [tensorflow/tensorflow#34357]
Hi, guys:
for TF1.14/1.15 used with tensorflow_model object_detction,

if I tried to save the state of the dataset for next restoring, I would encounter an issue.

> tensorflow.python.framework.errors_impl.InvalidArgumentError: 2 root error(s) found.
  (0) Invalid argument: Op[name: RandomHorizontalFlip/random_uniform/RandomUniform, type: RandomUniform] in function Dataset_map_process_fn_70 is stateful. Saving stateful functions is not supported yet.
         [[node SerializeIterator (defined at /local/mnt/workspace/zhanghao/download/tensorflow_model/research/object_detection/inputs.py:588) ]]
  (1) Invalid argument: Op[name: RandomHorizontalFlip/random_uniform/RandomUniform, type: RandomUniform] in function Dataset_map_process_fn_70 is stateful. Saving stateful functions is not supported yet.
         [[node SerializeIterator (defined at /local/mnt/workspace/zhanghao/download/tensorflow_model/research/object_detection/inputs.py:588) ]]
         [[FeatureExtractor/MobilenetV2/layer_19_1_Conv2d_2_1x1_256/BatchNorm/gamma/RMSProp_1/_7416]]

And the try is just adding the code to "<dir>/tensorflow_model/research/object_detection/inputs.py::train_input"

`  dataset = INPUT_BUILDER_UTIL_MAP['dataset_build'](
      train_input_config,
      transform_input_data_fn=transform_and_pad_input_data_fn,
      batch_size=params['batch_size'] if params else train_config.batch_size)

  iterator = dataset.make_initializable_iterator()
  tf.add_to_collection(tf.GraphKeys.TABLE_INITIALIZERS, iterator.initializer)

  saveable_obj = tf.data.experimental.make_saveable_from_iterator(iterator)

  tf.add_to_collection(tf.GraphKeys.SAVEABLE_OBJECTS, saveable_obj)

  return dataset`

And if I adopt "tf.data.experimental.CheckpointInputPipelineHook", got the same issue.

**Comment by jvishnuvardhan** [comment]
This is not Build/Installation or Bug/Performance issue. Please post this kind of support questions at [Stackoverflow](https://stackoverflow.com/questions/tagged/tensorflow). There is a big community to support and learn from your questions. GitHub is mainly for addressing bugs in installation and performance. Thanks!

**Comment by zhanghaocol** [comment]
yep, thank you.
