### ISSUE TITLE
Merging two RT graphs throughs an error

### ISSUE THREAD

**Issue by anshkumar** [tensorflow/tensorflow#34353]
I want to merge two RT graphs into a single graph. But while merging I'm getting error.
My code is as follows:

```
import tensorflow as tf
from tensorflow.python.compiler.tensorrt import trt_convert as trt

saved_model1 = "/home/xavier2/saved_model/ssd_tomato_l1"
saved_model2 = "/home/xavier2/saved_model/faster_rcnn_tomato_l2_grid_750x750"

def create_trt_inference_graph(graph_path):
    converter = trt.TrtGraphConverter(input_saved_model_dir=graph_path , 
        precision_mode=trt.TrtPrecisionMode.FP16)
    converted_graph_def = converter.convert()
    return converted_graph_def

def get_serialized_graph(graph_path):
    converted_graph_def = create_trt_inference_graph(graph_path)
    serial_def = converted_graph_def.SerializeToString()
    return serial_def

def get_frozen_graph(graph_path):
    graph_def = tf.GraphDef()
    graph_def.ParseFromString(get_serialized_graph(graph_path))
    return graph_def

def rename_frame_name(graphdef, suffix):
    # Bug reported at https://github.com/tensorflow/tensorflow/issues/22162#issuecomment-428091121
    for n in graphdef.node:
        if "while" in n.name:
            if "frame_name" in n.attr:
                n.attr["frame_name"].s = str(n.attr["frame_name"]).replace("while_context","while_context" + suffix).encode('utf-8')

l1_graph = tf.Graph()
with l1_graph.as_default():
    trt_graph1 = get_frozen_graph(saved_model1)
    [tf_input1, tf_scores1, tf_boxes1, tf_classes1, tf_num_detections1] = tf.import_graph_def(trt_graph1, 
            return_elements=['import/image_tensor:0', 'import/detection_scores:0', 'import/detection_boxes:0', 'import/detection_classes:0','import/num_detections:0'])

connected_graph = tf.Graph()
with connected_graph.as_default():
    l1_graph_def = l1_graph.as_graph_def()
    g1name = 'ved'
    rename_frame_name(l1_graph_def, g1name)
    tf.import_graph_def(l1_graph_def, name=g1name)
    trt_graph2 = get_frozen_graph(saved_model2)
    g2name = 'level2'
    rename_frame_name(trt_graph2, g2name)
    [tf_scores, tf_boxes, tf_classes, tf_num_detections] = tf.import_graph_def(trt_graph2,
            return_elements=['import/detection_scores:0', 'import/detection_boxes:0', 'import/detection_classes:0','import/num_detections:0'])
```

It throws following error:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/importer.py", line 427, in import_graph_def
    graph._c_graph, serialized, options)  # pylint: disable=protected-access
tensorflow.python.framework.errors_impl.InvalidArgumentError: Cannot add function 'TRTEngineOp_1_native_segment' because a different function with the same name already exists.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 10, in <module>
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/importer.py", line 431, in import_graph_def
    raise ValueError(str(e))
ValueError: Cannot add function 'TRTEngineOp_1_native_segment' because a different function with the same name already exists.
```

My specs are:

Tensorflow: 1.14.0
Python: 3.6.8
Platform: Ubuntu 18.04.2 LTS (GNU/Linux 4.9.140-tegra aarch64)

**Comment by rmothukuru** [comment]
@anshkumar,
 Can you please share `saved_model1` and `saved_model2` so that we can reproduce the issue at our end. Thanks!

**Comment by anshkumar** [comment]
Here is the [link](https://drive.google.com/open?id=1lgZB27bdv7qFMfMwTETv11PCq-BZszcg).

**Comment by rmothukuru** [comment]
@anshkumar,
When trying to reproduce your error, below error encountered. Can you please help us reproduce the your error. Thanks!

`ValueError: Requested return tensor 'import/detection_scores:0' not found in graph def`

**Comment by anshkumar** [comment]
You need to have [tensorRT](https://docs.nvidia.com/deeplearning/sdk/tensorrt-install-guide/index.html) installed. It's showing in the info that it's not able to find tensorRT version:

```
INFO:tensorflow:Linked TensorRT version: (0, 0, 0)
INFO:tensorflow:Loaded TensorRT version: (0, 0, 0)
INFO:tensorflow:Running against TensorRT version 0.0.0
...
```

**Comment by jvishnuvardhan** [comment]
As mentioned by @aaroey in another related issue, can you try with `TF1.15` and let us know whether the issue persists with the newer version or not. Thanks!

> In 1.14 TF-TRT was disable by default accidentally due to some release problem, and we're fixing the it in 1.15. In fact 1.15rc1 and 2.0rc1 were out and TF-TRT was enabled in both, please try with that and let me know.

**Comment by anshkumar** [comment]
My platform is NVIDIA Jetson AGX Xavier; tensorflow is provided by nvidia. The list of version provided by them is [here](https://developer.download.nvidia.com/compute/redist/jp/v42/tensorflow-gpu/). (TF-TRT is enabled with the version of tensorflow in the link.) On google colabs, I don't know how to enable TF-TRT.

**Comment by aaroey** [comment]
Hi @anshkumar, it currently doesn't support merging two TF-TRT converted graphs into one, the main reason is, both graph will have TRTEngineOps with the same name. Please let me know why this is useful and provide more info about your use case. Thanks.

Also @sanjoy

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.
