### ISSUE TITLE
MemcpyHtoD blocks gpu computing when using StagingArea

### ISSUE THREAD

**Issue by zhm9484** [tensorflow/tensorflow#34368]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 16.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version (use command below): 1.13.1
- Python version: 3.5.2
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 10.0/7.4
- GPU model and memory: v100 32GB

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
I used StagingArea to make data transferring and coputing as a pipeline. But it turned out that MemcpyHtoD was not overlapped with computing. 
![image](https://user-images.githubusercontent.com/12964346/69027289-62652280-0a09-11ea-9f4d-721ba29f8442.png)

**Describe the expected behavior**
Data transferring overlaps with computing in order to speed up training.
**Code to reproduce the issue**
```
with tf.device("/gpu:0"):
    cpu_to_gpu_stage = data_flow_ops.StagingArea(dtypes=_dtypes(data), shapes=_shapes(data))
    cpu_to_gpu_op = cpu_to_gpu_stage.put(data)

    data2 = cpu_to_gpu_stage.get()
    train_op = model.build_graph(data2)

sess.run([cpu_to_gpu_op])
while 1:
    res = sess.run([train_op, cpu_to_gpu_op])[0]

```
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by smthxwolf** [comment]
i've got the same problem on tf1.14, rtx2080ti

**Comment by ymodak** [comment]
Code you provided is incomplete. Please provide minimal reproducible test case. Thanks!

**Comment by zhm9484** [comment]
> Code you provided is incomplete. Please provide minimal reproducible test case. Thanks!
Thanks for answering!

I use tf_cnn_benchmarks to see if the problem remains.
[https://github.com/tensorflow/benchmarks](url)

The command is 
`mpirun --allow-run-as-root -np 1 python scripts/tf_cnn_benchmarks/tf_cnn_benchmarks.py --model alexnet --batch_size 1024 --variable_update horovod --trace_file=/learner/benchmarks/timeline.json --data_name cifar10 --data_dir /learner/benchmarks/cifar-10-batches-py`.

The problem remains. MemcpyHtoD is not overlapped with computing.
![image](https://user-images.githubusercontent.com/12964346/69699495-072ae280-1123-11ea-9cdf-5c46675117e1.png)

**Comment by zhm9484** [comment]
Hi, everyone!
I wrote an easy case to reproduce the problem. Here is the code:
```
import numpy as np
import tensorflow as tf
from tensorflow.python.ops import data_flow_ops
from tensorflow.python.client import timeline

gpu = "/gpu:0"
size = 10000000
data = np.random.rand(size).astype(np.float32)
def generate_data():
    return data

def compute(inp):
    out = tf.zeros_like(inp, dtype=np.float32)
    for i in range(1000):
        out = tf.math.add(inp, out)
    return out

def build_graph(inp):
    with tf.device(gpu):
        cpu_to_gpu_stage = data_flow_ops.StagingArea(dtypes=[np.float32], shapes=[size])
        copy_op = cpu_to_gpu_stage.put(inp)
        
        inp = cpu_to_gpu_stage.get()
        compute_op = compute(inp)

        return copy_op, compute_op

inp = tf.py_func(generate_data, [], [np.float32])
copy_op, compute_op = build_graph(inp)

sess = tf.Session()

def run_with_tl(sess, ops, output_path):
    run_options = tf.RunOptions(trace_level=tf.RunOptions.FULL_TRACE)
    run_metadata = tf.RunMetadata()
    sess.run(ops, options=run_options, run_metadata=run_metadata)
    tl = timeline.Timeline(run_metadata.step_stats)
    ctf = tl.generate_chrome_trace_format()
    with open(output_path, "w") as fp:
        fp.write(ctf)

run_with_tl(sess, [copy_op], "timeline.json")
for i in range(20):
    print(i)
    run_with_tl(sess, [copy_op, compute_op], "timeline_{}.json".format(i))
```
Here is the timeline:
![image](https://user-images.githubusercontent.com/12964346/69911433-66a42d80-1456-11ea-8877-67557aabb1a9.png)

It still took extra time to do the MemcpyHToD.

**Comment by zhm9484** [comment]
@ymodak 
Hi! Could you tell what was wrong in the case above?

**Comment by zhm9484** [comment]
I figured it out. It's about the pinned memory.

**Comment by xiaolou** [comment]
> I figured it out. It's about the pinned memory.

@zhm9484 how to fix it ?

**Comment by zhm9484** [comment]
> > I figured it out. It's about the pinned memory.
> 
> @zhm9484 how to fix it ?

Modify the case above.
```
import numpy as np
import tensorflow as tf
from tensorflow.python.ops import data_flow_ops
from tensorflow.python.client import timeline
import pycuda.driver as cuda
import pycuda.autoinit

gpu = "/gpu:0"
size = 10000000
data = np.random.rand(size).astype(np.float32)
pinned_data = cuda.pagelocked_empty_like(data, mem_flags=cuda.host_alloc_flags.DEVICEMAP)
pinned_data[:] = data
def generate_data():
    return pinned_data

def compute(inp):
    out = tf.zeros_like(inp, dtype=np.float32)
    for i in range(100):
        out = tf.math.add(inp, out)
    return out

def build_graph(inp):
    with tf.device(gpu):
        cpu_to_gpu_stage = data_flow_ops.StagingArea(dtypes=[np.float32], shapes=[size])
        copy_op = cpu_to_gpu_stage.put(inp)
        
        inp = cpu_to_gpu_stage.get()
        compute_op = compute(inp)

        return copy_op, compute_op

inp = tf.py_func(generate_data, [], [np.float32])
copy_op, compute_op = build_graph(inp)

sess = tf.Session()

def run_with_tl(sess, ops, output_path):
    run_options = tf.RunOptions(trace_level=tf.RunOptions.FULL_TRACE)
    run_metadata = tf.RunMetadata()
    sess.run(ops, options=run_options, run_metadata=run_metadata)
    tl = timeline.Timeline(run_metadata.step_stats)
    ctf = tl.generate_chrome_trace_format()
    with open(output_path, "w") as fp:
        fp.write(ctf)

run_with_tl(sess, [copy_op], "timeline.json")
for i in range(20):
    print(i)
    run_with_tl(sess, [copy_op, compute_op], "timeline_{}.json".format(i))

```
