### ISSUE TITLE
Why tf.concat not support multiply types

### ISSUE THREAD

**Issue by Leslie-Fang** [tensorflow/tensorflow#34365]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using): TF2.0
- Are you willing to contribute it (Yes/No): Yes

**Describe the feature and the current behavior/state.**
I have 2 tensor with shape(1,4)
but one tensor(a) is string type.
Another tensor(b) is int32 type.
When I try to concat them
tf.concat([a,b], 0)
I get the error message:
_tensorflow.python.framework.errors_impl.InvalidArgumentError: cannot compute ConcatV2 as input #1(zero-based) was expected to be a string tensor but is a int32 tensor [Op:ConcatV2] name: concat_

**Will this change the current api? How?**

**Who will benefit with this feature?**
tf.concat users

**Any Other info.**

**Comment by sgpritam** [comment]
Concatenates the list of tensors values along dimension axis. If values[i].shape = [D0, D1, ... Daxis(i), ...Dn], the concatenated result has shape
[D0, D1, ... Raxis, ...Dn]
where
Raxis = sum(Daxis(i))

That is, the data from the input tensors is joined along the axis dimension.

The number of dimensions of the input tensors must match, and all dimensions except axis must be equal.

For example:
t1 = [[1, 2, 3], [4, 5, 6]]
t2 = [[7, 8, 9], [10, 11, 12]]
tf.concat([t1, t2], 0) # [[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]]
tf.concat([t1, t2], 1) # [[1, 2, 3, 7, 8, 9], [4, 5, 6, 10, 11, 12]]

tensor t3 with shape [2, 3]
tensor t4 with shape [2, 3]
tf.shape(tf.concat([t3, t4], 0)) # [4, 3]
tf.shape(tf.concat([t3, t4], 1)) # [2, 6]

As in Python, the axis could also be negative numbers. Negative axis are interpreted as counting from the end of the rank, i.e., axis + rank(values)-th dimension

**Comment by Leslie-Fang** [comment]
@sgpritam My input tensors definitely has the same dimension but one is tf.string and another one is tf.int32.

**Comment by gowthamkpr** [comment]
@Leslie-Fang As you can see from the definition of values in the function, the two tensors should be of same type and this function doesn't cast the two types into the same type. This is the cause of the error.

```
def concat_v2(values, axis, name=None):
  r"""Concatenates tensors along one dimension.

  Args:
    values: A list of at least 2 `Tensor` objects with the same type.
      List of `N` Tensors to concatenate. Their ranks and types must match,
      and their sizes must match in all dimensions except `concat_dim`.
    axis: A `Tensor`. Must be one of the following types: `int32`, `int64`.
      0-D.  The dimension along which to concatenate.  Must be in the
      range [-rank(values), rank(values)).
    name: A name for the operation (optional).

```

**Comment by Leslie-Fang** [comment]
@gowthamkpr Thanks for the sharing. Is there any special consideration to design the input tensors must be the same type? My question is that whether this API could support the input tensors with different types.

**Comment by gowthamkpr** [comment]
@Leslie-Fang Can't promise anything but I will keep you updated on this feature request.

**Comment by rmothukuru** [comment]
@Leslie-Fang,
Sorry for the delayed response. **`Concatenation`** of a **`String Tensor`** and an **`Integer Tensor`** no more results in an **`Error`**. Please find [the Gist](https://colab.research.google.com/gist/rmothukuru/97e681b1c190d1599f75f203c277ac21/gh_34365.ipynb) of the working code. Thanks!
