### ISSUE TITLE
google/protobuf/any.proto: File not found

### ISSUE THREAD

**Issue by gclouding** [tensorflow/tensorflow#3437]
### Environment info
Operating System: ubuntu14.04

I have install java8 and the latest version of bazel ([bazel release 0.3.0-2016-07-21 (@2e1dbd7)]) pulled from github. After then, I pulled the tensorflow.igt using the command: git clone --recurse-submodules https://github.com/tensorflow/tensorflow.

Then, I intended to install tensorflow following the steps:
1) Install java8.
2) Install bazel ([bazel release 0.3.0-2016-07-21 (@2e1dbd7)])  pulled from github.
3) git clone --recurse-submodules https://github.com/tensorflow/tensorflow.
4) ./configure (in the root dir of tensorflow, without using google cloud, without configuration of gpu)
5) bazel build -c opt //tensorflow/tools/pip_package:build_pip_package

Unfortunately, error prompted in Step 5:
      ".. tensorflow/tensorflow/tools/pip_package/BUILD:23:1: error loading package 'tensorflow/core': Encountered error while reading extension file 'protobuf.bzl': no such package '@protobuf//': Error cloning repository: https://github.com/google/protobuf: cannot open git-upload-pack caused by https://github.com/google/protobuf: cannot open git-upload-pack caused by sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target caused by PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target caused by unable to find valid certification path to requested target and referenced by '//tensorflow/tools/pip_package:build_pip_package'.
ERROR: Analysis of target '//tensorflow/tools/pip_package:build_pip_package' failed; build aborted.
INFO: 
Elapsed time: 0.102s"

I have confirmed that git clone can be used normally to pull the code from https://github.com/google/protobuf.

Anyone knows how this problem can be fixed ?

**Comment by gclouding** [comment]
After I downloaded the dependencies manually, the previous errors were passed. However, I got the following errors:

WARNING: ../tensorflow/util/python/BUILD:11:16: in includes attribute of cc_library rule //util/python:python_headers: 'python_include' resolves to 'util/python/python_include' not in 'third_party'. This will be an error in the future.
ERROR: /home/dl/.cache/bazel/_bazel_dl/647b15c3637d5190d4f70d81e8357baf/external/protobuf/BUILD:331:1: in cc_binary rule @protobuf//:protoc: cycle in dependency graph:
    //tensorflow/tools/pip_package:build_pip_package
    //tensorflow/tensorboard:tensorboard
    //tensorflow/tensorboard/backend:server
    //tensorflow/python:summary
    //tensorflow/python:util
    @protobuf//:protobuf_python
    @protobuf//:python/google/protobuf/wrappers_pb2.py
    @protobuf//:protobuf_python_genproto
  * @protobuf//:protoc (host)
    @protobuf//:protoc_lib (host)
    @protobuf//:protobuf (host)
    @protobuf//:protobuf_lite (host)
    @protobuf//:src/google/protobuf/util/message_differencer_unittest.pb.h (host)
    @protobuf//:cc_test_protos_genproto (host)
    @protobuf//:cc_wkt_protos_genproto (host)
  * @protobuf//:protoc (host)
This cycle occurred because of a configuration option.
ERROR: Analysis of target '//tensorflow/tools/pip_package:build_pip_package' failed; build aborted.
INFO: Elapsed time: 0.146s

**Comment by concretevitamin** [comment]
@martinwicke can you take a look at the Bazel issue?  Thanks.

**Comment by martinwicke** [comment]
Are you sure you have the correct version of protobuf? It's sadly very specific: 3.0.0b2.

**Comment by gclouding** [comment]
I downloaded this version of protobuf ------ https://github.com/google/protobuf/archive/v3.0.0-beta-2.tar.gz
And execute "bazel clean --expunge", and then use bazel to build tensorflow agian. However, different errors occured:

`ERROR: /home/dl/.cache/bazel/_bazel_dl/647b15c3637d5190d4f70d81e8357baf/external/protobuf/BUILD:32:5: no such variable: internal_gen_well_known_protos_java.
ERROR: /home/dl/.cache/bazel/_bazel_dl/647b15c3637d5190d4f70d81e8357baf/external/protobuf/BUILD:525:1: name 'internal_gen_well_known_protos_java' is not defined.
ERROR: /home/dl/.cache/bazel/_bazel_dl/647b15c3637d5190d4f70d81e8357baf/external/protobuf/BUILD:633:1: missing mandatory positional argument 'include' while calling internal_copied_filegroup(name, srcs, include, **kargs).
ERROR: /home/dl/.cache/bazel/_bazel_dl/647b15c3637d5190d4f70d81e8357baf/external/protobuf/BUILD:670:1: missing mandatory positional argument 'include' while calling internal_copied_filegroup(name, srcs, include, **kargs).
ERROR: /home/dl/.cache/bazel/_bazel_dl/647b15c3637d5190d4f70d81e8357baf/external/protobuf/BUILD:723:1: name 'internal_protobuf_py_tests' is not defined.
ERROR: /home/dl/.cache/bazel/_bazel_dl/647b15c3637d5190d4f70d81e8357baf/external/protobuf/BUILD:644:1: Target '@protobuf//:use_fast_cpp_protos' contains an error and its package is in error and referenced by '@protobuf//:protobuf_python'.
ERROR: /home/dl/bxl/tensorflow/tensorflow/python/BUILD:917:1: Target '@protobuf//:protobuf_python' contains an error and its package is in error and referenced by '//tensorflow/python:util'.
ERROR: Analysis of target '//tensorflow/tools/pip_package:build_pip_package' failed; build aborted.
`

**Comment by gclouding** [comment]
@martinwicke

**Comment by martinwicke** [comment]
Which version of bazel are you using?

**Comment by gclouding** [comment]
the above problem concerned with bazel is solved.  However, the following problem occured:

../tensorflow/tensorflow/core/BUILD:91:1: null failed: protoc failed: error executing command bazel-out/host/bin/external/protobuf/protoc '--cpp_out=bazel-out/local-opt/genfiles/' -I. -Isrc tensorflow/core/example/example.proto tensorflow/core/example/example_parser_configuration.proto ... (remaining 30 argument(s) skipped): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
src: warning: directory does not exist.
google/protobuf/any.proto: File not found.
tensorflow/core/protobuf/meta_graph.proto: Import "google/protobuf/any.proto" was not found or had errors.
tensorflow/core/protobuf/meta_graph.proto:41:5: "google.protobuf.Any" is not defined.
tensorflow/core/protobuf/meta_graph.proto:162:14: "google.protobuf.Any" is not defined.
Target //tensorflow/tools/pip_package:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 0.263s, Critical Path: 0.02s

**Comment by martinwicke** [comment]
Can you try this with bazel 0.2.3? It is possible tensorflow doesn't work with bazel at head right now.

**Comment by girving** [comment]
@martinwicke Should this be closed due to lack of response, or is there more checking to do?

**Comment by martinwicke** [comment]
I do not know the status of this -- but it seems like an isolated thing. Closing, feel free to reopen with new information if it persists.

**Comment by philipjhc** [comment]
Is this problem finally solved?
