### ISSUE TITLE
Why is autoencoder with tensorflow 2.0 is performing very bad compared to the same code in keras?

### ISSUE THREAD

**Issue by ahmedelmahy** [tensorflow/tensorflow#34380]
I am training an autoencoder on the mnist data With keras the validation loss is great (starting from 0.2687 to .1) While with tensorflow(version 2.0).keras validation loss is stuck at (.6) Even though I am using the same code.

Below is the code with keras ([you can test it in colab](https://colab.research.google.com/drive/1AD5Z_pXsaM6Ubn6Yfg0uD230J9o8AfRS)) and followed by the code with tf.keras ([you can test it in colab](https://colab.research.google.com/drive/1Hj3-_Bjfkp3-dmd38-1CmIR4VLOV98hB))

```
from keras.layers import Input, Dense
from keras.models import Model, Sequential
from keras.datasets import mnist
import numpy as np

#Import the MNIST data, only take the images since we don't need the targets
(x_train, y_train), (x_test, y_test) = mnist.load_data()
#Normalize and reshape images to vectors
x_train = x_train.astype('float32') / 255.
x_test = x_test.astype('float32') / 255.
x_train = x_train.reshape((len(x_train), np.prod(x_train.shape[1:])))
x_test = x_test.reshape((len(x_test), np.prod(x_test.shape[1:])))
print (x_train.shape)
print (x_test.shape)


input = Input(shape=(784,))
y = Dense(64, activation='relu')(input)
z = Dense(784, activation='sigmoid')(y)
ae = Model(input, z)
encoder = Model(input, y)
input_decoder = Input(shape = (64,))
decoder_layer = ae.layers[-1]
decoder = Model(input_decoder, decoder_layer(input_decoder))
ae.compile(optimizer='adadelta', loss = 'binary_crossentropy')
ae.fit(x_train, x_train, epochs = 50, batch_size=256, shuffle=False, validation_data=(x_test, x_test))
```

60000/60000 [==============================] - 5s 88us/step - loss: 0.3494 - val_loss: 0.2688 Epoch 2/50 60000/60000 [==============================] - 4s 74us/step - loss: 0.2578 - val_loss: 0.2445 Epoch 3/50

```
from tensorflow.keras.layers import Input, Dense
from tensorflow.keras.models import Model, Sequential
from tensorflow.keras.datasets import mnist
import numpy as np

#Import the MNIST data, only take the images since we don't need the targets
(x_train, y_train), (x_test, y_test) = mnist.load_data()
#Normalize and reshape images to vectors
x_train = x_train.astype('float32') / 255.
x_test = x_test.astype('float32') / 255.
x_train = x_train.reshape((len(x_train), np.prod(x_train.shape[1:])))
x_test = x_test.reshape((len(x_test), np.prod(x_test.shape[1:])))
print (x_train.shape)
print (x_test.shape)


input = Input(shape=(784,))
y = Dense(64, activation='relu')(input)
z = Dense(784, activation='sigmoid')(y)
ae = Model(input, z)
encoder = Model(input, y)
input_decoder = Input(shape = (64,))
decoder_layer = ae.layers[-1]
decoder = Model(input_decoder, decoder_layer(input_decoder))
ae.compile(optimizer='adadelta', loss = 'binary_crossentropy')
ae.fit(x_train, x_train, epochs = 50, batch_size=256, shuffle=False, validation_data=(x_test, x_test))

```
Train on 60000 samples, validate on 10000 samples Epoch 1/50 60000/60000 [==============================] - 4s 59us/sample - loss: 0.6941 - val_loss: 0.6939 Epoch 2/50 60000/60000 [==============================] - 3s 47us/sample - loss: 0.6937 - val_loss: 0.6936

**Comment by ahmedelmahy** [comment]
It turns out it's a behaviour from the optimizer. Could it be a bug? or just different initialization parameters 

with tf.keras it works very well and reaches val_loss less than 1 with adam optimizer
```

#from keras import backend as K
from tensorflow.keras.layers import Input, Dense, Dropout
from tensorflow.keras.utils import plot_model, to_categorical
from tensorflow.keras.callbacks import EarlyStopping
from tensorflow.keras.models import Model, Sequential
from tensorflow.keras.datasets import mnist
from tensorflow.keras import regularizers
import tensorflow.keras as keras
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import tensorflow as tf

#Import the MNIST data, only take the images since we don't need the targets
(x_train, y_train), (x_test, y_test) = mnist.load_data()
#Normalize and reshape images to vectors
x_train = x_train.astype('float32') / 255.
x_test = x_test.astype('float32') / 255.
x_train = x_train.reshape((len(x_train), np.prod(x_train.shape[1:])))
x_test = x_test.reshape((len(x_test), np.prod(x_test.shape[1:])))
print (x_train.shape)
print (x_test.shape)


input = Input(shape=(784,))
y = Dense(64, activation='relu')(input)
z = Dense(784, activation='sigmoid')(y)
ae = Model(input, z)
encoder = Model(input, y)
input_decoder = Input(shape = (encoding_size,))
decoder_layer = ae.layers[-1]
decoder = Model(input_decoder, decoder_layer(input_decoder))
ae.compile(optimizer='adam', loss = 'binary_crossentropy')
ae.fit(x_train, x_train, epochs = 50, batch_size=256, shuffle=False, validation_data=(x_test, x_test))

```

Train on 60000 samples, validate on 10000 samples
Epoch 1/50
60000/60000 [==============================] - 2s 28us/sample - loss: 0.2540 - val_loss: 0.1771
Epoch 2/50
60000/60000 [==============================] - 1s 20us/sample - loss: 0.1578 - val_loss: 0.1418

**Comment by ravikyram** [comment]
@ahmedelmahy 
I tried the code with keras using TF 1.15 and validation loss is converging  (starting from 0.2687 to .1). However in TF 2.0 using keras gives the below error.
`RuntimeError: It looks like you are trying to use a version of multi-backend Keras that does not support TensorFlow 2.0. We recommend using `tf.keras`, or alternatively, downgrading to TensorFlow 1.14`.
I tried the given code using tf.keras using TF 2.0 against adadelta and adam and yes 'adadelta' has much worse performance compared to adam (as you can see [here](https://colab.sandbox.google.com/gist/ravikyram/abf3f37d69beb90346d2aa7a05f88f70/ae-in-tf-keras.ipynb) and this can be explained [here](https://www.reddit.com/r/MachineLearning/comments/3y84hr/how_does_adam_compare_to_adadelta/).Please correct me if you think otherwise.Thanks!

**Comment by ravikyram** [comment]
@ahmedelmahy 

Any update on this issue please?. Thanks!

**Comment by ahmedelmahy** [comment]
@ravikyram  thanks for the mention. That seems correct that adam could be faster than adadelta
[reddit](https://www.reddit.com/r/MachineLearning/comments/3y84hr/how_does_adam_compare_to_adadelta/)


But I still kind of don't understand why "adadelta" is behaving in a different way in tf.keras as compared to the separate keras  package.
For now I am using Adam and things are working fine.

**Comment by tanzhenyu** [comment]
@ahmedelmahy I think this is probably due to we changed the default learning rate (unfortunately) from 1.0 to 0.001. Can you try it and let us know if it fixes for you?

**Comment by ahmedelmahy** [comment]
That works like a charm @tanzhenyu  . [Setting the learning rate ](https://colab.research.google.com/drive/1Hj3-_Bjfkp3-dmd38-1CmIR4VLOV98hB) to 1.0 produces the same results as with keras.
