### ISSUE TITLE
Discussion: A possible Profiling method for TensorFlow

### ISSUE THREAD

**Issue by AlvinChen13** [tensorflow/tensorflow#3438]
Goals:
1. Get the timing run on CPU & GPU.
2. Get the timing for each OP (run on GPU or CPU) or a serial of OPs.

Identify the performance bottlenecks to do the optimization.

I just review some code for TF, and I find it should be possible to add some profiling code in tensorflow/core or tensorflow/stream_executor.

How about the idea? Any comments?

**Comment by concretevitamin** [comment]
Take a look at #1824?  The StepStats and timeline functionalities that we open-sourced a while ago should address these two goals.

Feel free to re-open if there's something missing.
