### ISSUE TITLE
GPU device not found in Colab

### ISSUE THREAD

**Issue by bigmw** [tensorflow/tensorflow#34385]
My code worked well with GPU in Colab yesterday. But this morning it became very slow. So I suspect that CPU is used despite hardware accelerator is set to GPU in “change runtime type” explicitly. So I check the availability of GPU following the tutorial:
https://colab.research.google.com/notebooks/gpu.ipynb

code chunk:
```
%tensorflow_version 2.x
import tensorflow as tf
device_name = tf.test.gpu_device_name()
if device_name != '/device:GPU:0':
  raise SystemError('GPU device not found')
print('Found GPU at: {}'.format(device_name))
```

Indeed, I got SystemError: GPU device not found. I tried this with different sessions or google user accounts, the same results. You should be able to replicate this in a new Colab session.
Maybe some tensorflow updates are involved? It could be that Colab session provide GPU, but tensorflow can’t see it, e.g. tf.test.gpu_device_name() or tf.test.is_gpu_available(). 
Please help, thank you!

**Comment by ymodak** [comment]
The best available hardware is prioritized for users who use Colaboratory interactively rather than for long-running computations. Users who use Colaboratory for long-running computations may be temporarily restricted in the type of hardware made available to them, and/or the duration that the hardware can be used for.
See [Why are hardware resources such as T4 GPUs not available to me?](https://research.google.com/colaboratory/faq.html)
You may try shut down current notebook and start a new one.

**Comment by bigmw** [comment]
Thanks for the response. I only use Colaboratory interactively, and never for long-running computations. It is not likely that I am temporarily restricted because I tried the GPU test in different sessions and different user accounts (mentioned above). That’s way I think it is more likely related to tensorflow update.
Can you try the code chunk above in Colab (of course with hardware accelerator is set to GPU in “change runtime type” first) to see whether you can replicate the problem? thanks.

**Comment by ymodak** [comment]
Thanks. I was able to reproduce the behavior.
As a workaround you may try installing tf-nightly-gpu version;
```pip install tf-nightly-gpu```
You can also comment out ```%tensorflow_version 2.x``` lines from the colab.
Can you please point me to the webpage where you found the tutorial? Thanks!

**Comment by qo4on** [comment]
I have the same issue. Yesterday everything worked fine. I also didn't use it for long-running computations.

**Comment by bigmw** [comment]
@ymodak 
installing tf-nightly-gpu does not help. Commenting out %tensorflow_version 2.x lines works. It's even more likely that this is due to some recent update in tensorflow 2. You can find the tutorial in my original question above. Thanks.
@qo4on 
glad that someone replicates my problem more precisely! Hope the tensorflow team can quicly noticed this and reverse the problematic update.

**Comment by arthurflor23** [comment]
I'm also having the same problem and in this morning worked fine.

**Comment by AlessioGalluccio** [comment]
Same here. Thank you, I was hopeless. I will wait tomorrow

**Comment by QuangHa97** [comment]
Hello @bigmw, I got the same issue.  tf 2.0 GPU worked yesterday and today it is not working.
Tf 1.15 still can find GPU but same like tf 2.0 can't find GPU (include K80, T4 and P100 in google colab).

**Comment by zxam** [comment]
Downgrading cuda from 10.1 to 10.0 may solve the problem. [stackoverflow](https://stackoverflow.com/questions/58926378/unable-to-run-even-basic-example-with-tf-2-0-and-gpu-support-in-colab)

**Comment by QuangHa97** [comment]
Thank @ymodak, tensorflow 2.1.0-dev20191119 worked for me.

```
!pip install tf-nightly-gpu
try:
  import tensorflow.compat.v2 as tf
except Exception:
  pass
tf.enable_v2_behavior()
print(tf.__version__)
```
`2.1.0-dev20191119`

Comment: %tensorflow_version 2.x still get tf 2.0 so that wont work.

**Comment by qo4on** [comment]
Run this code, get some red lines, restart runtime and run again:
```
!pip install tf-nightly-gpu
import tensorflow as tf
print("Version: ", tf.__version__)
print(tf.config.list_physical_devices('GPU'))

# Version:  2.1.0-dev20191119
# [PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]
```

**Comment by bigmw** [comment]
Thanks @QuangHa97 
installing tf-nightly-gpu following your code above does solve the GPU error. However, GPU under tf-nightly-gpu (TF 2.1.0-dev20191119) seems to be much slower than the original TF 2.0 (before this bug occurred). My code used to take 5.6 seconds per epoch, now it’s 8.6 seconds, about ~54% slower than before. There should still be some issue there with tf-nightly-gpu. Hope the TF team would notice and work on this.

**Comment by bigmw** [comment]
UPDATE:
GPU is working with TF 2.0 now in Colab. Thanks for all your comments/suggestions.

**Comment by ymodak** [comment]
Awesome. Closing this issue. Thanks!

**Comment by vantainguyen** [comment]
> UPDATE:
> GPU is working with TF 2.0 now in Colab. Thanks for all your comments/suggestions.

I still got the same error; why is that?

**Comment by alex-sokolov2011** [comment]
I still got the same error after
```
pip install tf-nightly-gpu

%tensorflow_version 2.x  
import tensorflow as tf  
device_name = tf.test.gpu_device_name()  
if device_name != '/device:GPU:0':
   raise SystemError('GPU device not found')
print('Found GPU at: {}'.format(device_name))
```
SystemError                               Traceback (most recent call last)

<ipython-input-10-7c0b5e3718da> in <module>()
      3 device_name = tf.test.gpu_device_name()
      4 if device_name != '/device:GPU:0':
----> 5    raise SystemError('GPU device not found')
      6 print('Found GPU at: {}'.format(device_name))

SystemError: GPU device not found

but 
`!nvidia-smi`
get
NVIDIA-SMI 460.56       Driver Version: 460.32.03    CUDA Version: 11.2

**Comment by chiragnsolanki** [comment]
Open google Colab -> Right top corner find RAM/Disk -> Dropdown ->View resources - >change runtime -> hardware accelerator -> select GPU -> save .This solves the issue

**Comment by Pfed-prog** [comment]
> 
> 
> Open google Colab -> Right top corner find RAM/Disk -> Dropdown ->View resources - >change runtime -> hardware accelerator -> select GPU -> save .This solves the issue

that actually solved my errors in colab, cheers

**Comment by Vishnu2331** [comment]
after giving command in colab:

!pip install tf-nightly-gpu
%tensorflow_version 2.x  
import tensorflow as tf  
device_name = tf.test.gpu_device_name()  
if device_name != '/device:GPU:0':
   raise SystemError('GPU device not found')
print('Found GPU at: {}'.format(device_name))



i am getting error as:



RuntimeError                              Traceback (most recent call last)
RuntimeError: module compiled against API version 0xe but this version of numpy is 0xd
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
ImportError: numpy.core.multiarray failed to import

The above exception was the direct cause of the following exception:

SystemError                               Traceback (most recent call last)
SystemError: <built-in method __contains__ of dict object at 0x7f367d7bee60> returned a result with an error set

The above exception was the direct cause of the following exception:

ImportError                               Traceback (most recent call last)
[<ipython-input-9-f287495fe26c>](https://localhost:8080/#) in <module>()
      2 
      3 get_ipython().magic('tensorflow_version 2.x')
----> 4 import tensorflow as tf
      5 device_name = tf.test.gpu_device_name()
      6 if device_name != '/device:GPU:0':

3 frames
[/usr/local/lib/python3.7/dist-packages/tensorflow/python/client/pywrap_tf_session.py](https://localhost:8080/#) in <module>()
     17 # pylint: disable=invalid-import-order,g-bad-import-order, wildcard-import, unused-import
     18 from tensorflow.python import pywrap_tensorflow
---> 19 from tensorflow.python.client._pywrap_tf_session import *
     20 from tensorflow.python.client._pywrap_tf_session import _TF_SetTarget
     21 from tensorflow.python.client._pywrap_tf_session import _TF_SetConfig

ImportError: initialization failed
