### ISSUE TITLE
TFLite GL Delegate build is leaking Foundation libraries

### ISSUE THREAD

**Issue by infil00p** [tensorflow/tensorflow#34395]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Mac OS X 10.14.6 Mojave
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): source
- TensorFlow version: v1.15.0
- Python version: 3.7.4
- Installed using virtualenv? pip? conda?:
- Bazel version (if compiling from source): 0.26.0
- GCC/Compiler version (if compiling from source): NDK 18
- CUDA/cuDNN version:
- GPU model and memory:

**Describe the problem**

The Foundation Library is leaking into the GL delegate on v1.15.0.  This is related to [this bug](https://github.com/abseil/abseil-cpp/issues/326), but it didn't happen on v1.14.0

**Any other info / logs**
```
Joes-MacBook-Pro-3:gpu jbowser$ bazel build -c opt --config android_arm64 --copt -Os --copt -DTFLITE_GPU_BINARY_RELEASE --copt -fvisibility=hidden --linkopt -s --strip always :libtensorflowlite_gpu_gl.so
Starting local Bazel server and connecting to it...
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=1 --terminal_columns=238
INFO: Reading rc options for 'build' from /Users/jbowser/tensorflow_source/tensorflow/.bazelrc:
  'build' options: --apple_platform_type=macos --define framework_shared_object=true --define open_source_build=true --define=use_fast_cpp_protos=true --define=allow_oversize_protos=true --spawn_strategy=standalone --strategy=Genrule=standalone -c opt --announce_rc --define=grpc_no_ares=true --define=PREFIX=/usr --define=LIBDIR=$(PREFIX)/lib --define=INCLUDEDIR=$(PREFIX)/include
INFO: Reading rc options for 'build' from /Users/jbowser/tensorflow_source/tensorflow/.tf_configure.bazelrc:
  'build' options: --action_env PYTHON_BIN_PATH=/usr/local/opt/python3/bin/python3.7 --action_env PYTHON_LIB_PATH=/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages --python_path=/usr/local/opt/python3/bin/python3.7 --config=xla --action_env ANDROID_NDK_HOME=/Users/jbowser/ndk_builds/android-ndk-r18 --action_env ANDROID_NDK_API_LEVEL=18 --action_env ANDROID_BUILD_TOOLS_VERSION=29.0.2 --action_env ANDROID_SDK_API_LEVEL=29 --action_env ANDROID_SDK_HOME=/Users/jbowser/library/Android/Sdk --action_env TF_CONFIGURE_IOS=0
INFO: Found applicable config definition build:xla in file /Users/jbowser/tensorflow_source/tensorflow/.tf_configure.bazelrc: --define with_xla_support=true
INFO: Found applicable config definition build:android_arm64 in file /Users/jbowser/tensorflow_source/tensorflow/.bazelrc: --config=android --cpu=arm64-v8a --fat_apk_cpu=arm64-v8a
INFO: Found applicable config definition build:android in file /Users/jbowser/tensorflow_source/tensorflow/.bazelrc: --crosstool_top=//external:android/crosstool --host_crosstool_top=@bazel_tools//tools/cpp:toolchain
INFO: Analyzed target //tensorflow/lite/delegates/gpu:libtensorflowlite_gpu_gl.so (45 packages loaded, 3483 targets configured).
INFO: Found 1 target...
INFO: Deleting stale sandbox base /private/var/tmp/_bazel_jbowser/e70d978bebad2fab57f73474f3b8c22a/sandbox
ERROR: /Users/jbowser/tensorflow_source/tensorflow/tensorflow/lite/delegates/gpu/BUILD:110:1: Linking of rule '//tensorflow/lite/delegates/gpu:libtensorflowlite_gpu_gl.so' failed (Exit 1)
external/androidndk/ndk/toolchains/aarch64-linux-android-4.9/prebuilt/darwin-x86_64/lib/gcc/aarch64-linux-android/4.9.x/../../../../aarch64-linux-android/bin/ld: cannot find Foundation: No such file or directory
clang: error: linker command failed with exit code 1 (use -v to see invocation)
Target //tensorflow/lite/delegates/gpu:libtensorflowlite_gpu_gl.so failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 68.598s, Critical Path: 26.36s
INFO: 227 processes: 227 local.
FAILED: Build did NOT complete successfully```

**Comment by yyoon** [comment]
Looks like the fix for this issue (04e169ac74a81b00507f1bb571513a5c2f61547f) has not been included in v1.15.0 tag. If you want to build it from v1.15.0, you could cherry-pick that patch to your local repository and build successfully.

```sh
$ git checkout v1.15.0
$ git cherry-pick 04e169ac74a81b00507f1bb571513a5c2f61547f
$ bazel build ...
```

Could you try this and see if this works?

**Comment by infil00p** [comment]
@yyoon It does work.  So...a couple of questions:

1. Does this just build on Linux? 
2. Will there be a patch release with this fix? Or should I just create a custom tag of v1.15.0+select_ops_fix?

**Comment by yyoon** [comment]
1. Yes, it does work on Linux without patching that commit.
2. I guess it depends on your use case. The patch commit is already released in master branch, so if you could build from master, that should be an option for you. If not, I think locally creating a new tag for yourself should also work fine.

**Comment by infil00p** [comment]
I can create a custom tag for this.  The reason I want to build off of v1.15.0 and a custom tag is because I want to avoid issues with v2.0.0: https://github.com/tensorflow/tensorflow/issues/34393

**Comment by yyoon** [comment]
Yes, please use a custom tag if it suits your needs. Let me close this issue.
