### ISSUE TITLE
TFLite SIGILL on Invoke()

### ISSUE THREAD

**Issue by infil00p** [tensorflow/tensorflow#34393]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): I am using the C++ API on Android
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Android 10, Android 9
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: Pixel 3, Samsung Galaxy S8
- TensorFlow installed from (source or binary): Built from tag (build included in repro repo)
- TensorFlow version (use command below): v2.0.0
- Python version:
- Bazel version (if compiling from source): 0.28.0
- GCC/Compiler version (if compiling from source): NDK 18
- CUDA/cuDNN version:
- GPU model and memory:

**Describe the current behaviour**
While debugging C++ on Android, SIGILL is triggered on the interpreter->Invoke() call.  If you step past inference, TFLite still successfully infers and produces the correct result, but SIGILL shouldn't happen.

**Describe the expected behavior**
SIGILL shouldn't happen

**Code to reproduce the issue**
This repro reproduces this issue:
git@github.com:infil00p/TFLiteSigILL.git

**Other info / logs**
Debug frame for SIGILL
<img width="1286" alt="Screen Shot 2019-11-18 at 12 56 57 PM" src="https://user-images.githubusercontent.com/2313/69093285-026b7d80-0a03-11ea-809b-1e73d1537bf4.png">

**Comment by jdduke** [comment]
@srjoglekar246 could you take a look?

**Comment by srjoglekar246** [comment]
Hey @infil00p,
Does the SIGILL also occur when you do inference without any debug tooling? There are some known issues with JNI code & gdb tooling, so I was wondering if its related.

**Comment by infil00p** [comment]
@srjoglekar246 It doesn't.  Even when using debug tooling, the inference continues and I get an output from it.  I'm trying to investigate some other issues and this is appearing on v2.0.0 where v1.14.0 was working fine.

**Comment by amahendrakar** [comment]
@infil00p,
Could you please update TensorFlow to the latest stable version v2.4.1 and check if you are facing the same issue? Thanks!
