### ISSUE TITLE
Possible bug (wrong sign) in BTRS algorithm for binomial sampling?

### ISSUE THREAD

**Issue by jamestwebber** [tensorflow/tensorflow#34398]
This is a very esoteric issue: I was reading the [BTRS paper](https://www.tandfonline.com/doi/abs/10.1080/00949659308811496) and trying to understand the algorithm by reading the [TF implementation](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/kernels/random_binomial_op.cc), and I think I found a bug on line 99, in the Stirling approximation for `log(k!)`:

```
return (1.0 / 12 - (1.0 / 360 + 1.0 / 1260 / kp1sq) / kp1sq) / (k + 1);
```

If I'm reading the paper correctly, the sign on the third term is wrong, because it should be positive in the final sum (see page 106-106 of Hörmann et al):

```
return (1.0 / 12 - (1.0 / 360 - 1.0 / 1260 / kp1sq) / kp1sq) / (k + 1);
```

Or maybe there's an error in the paper? Anyway just thought I'd mention it.

**Comment by copperwiring** [comment]
@jamestwebber  It appears you are correct. I verified the equation from the original paper which can found here: https://epub.wu.ac.at/1242/1/document.pdf (Page 7)

I am sending a PR request now.

**Comment by lamberta** [comment]
This is merged and will be updated on the site the next docs push/release.
Thank you, all
