### ISSUE TITLE
 Distributed training resnet50 using 4 nodes 32  TeslaV100 cards

### ISSUE THREAD

**Issue by gentelyang** [tensorflow/tensorflow#34404]
I checked a lot of literature, but I didn't find the results. The questions are as follows:
How many hours can it converge？（Distributed training resnet50 using 4 nodes 32 TeslaV100 cards）

Do you have internal test results that can be displayed to better understand the performance of your distributed training.

**Comment by jvishnuvardhan** [comment]
There are lot of resource like [this](https://www.leadergpu.com/articles/429-tensorflow-resnet-50-benchmark) on benchmark performance of tensorflow. 

This is not Build/Installation or Bug/Performance issue. Please post this kind of support questions at [Stackoverflow](https://stackoverflow.com/questions/tagged/tensorflow). There is a big community to support and learn from your questions. GitHub is mainly for addressing bugs in installation and performance. Thanks!
