### ISSUE TITLE
How to access the context menu in pywinauto

### ISSUE THREAD

**Issue by Sathis89** [tensorflow/tensorflow#34407]
Hello All,

I could not able to access the menus(tool bars in the left side of an application). Can you please help how to acsess thos menus using pywinauto ?
I could not able to attach the screenshot because of some issue in the attachment process.

Thanks in Advance!!

**Comment by oanush** [comment]
@Sathis89 ,
Can you please open an issue in the [pywinauto](https://github.com/pywinauto/pywinauto/issues/new) repo as this is not related to TensorFlow.
Thanks!
