### ISSUE TITLE
tf.keras.utils.get_file error in Extracting .zip format

### ISSUE THREAD

**Issue by vinayapathak** [tensorflow/tensorflow#34405]
Hi, 
**Issue**: tf.keras.utils.get_filecannot extract .zip file and returns a list
Basicallly I have to convert the entire data set into tar.gz format since for some reason the above module is unable to extract the .zip folder. Another bug is that the .tar folder name and the fname have to be compulsorily same as per present module. I hope these two issues get fixed by the Tensorflow community :)
Any help will be appreciate...
Thanks in Advance...

**Comment by Leslie-Fang** [comment]
I think this API is able to extract the .zip file. Is there something special in your modules?

**Comment by copperwiring** [comment]
@vinayapathak : From https://www.tensorflow.org/api_docs/python/tf/keras/utils/get_file 

> files in tar, tar.gz, tar.bz, and zip formats can also be extracted. Passing a hash will verify the file after download. The command line programs shasum and sha256sum can compute the hash.

Could you post your code snippet for us to analyze the issue better?

**Comment by gadagashwini** [comment]
@vinayapathak, Specify the `archive_format` as .zip or .tar. 
`cache_subdir: Subdirectory under the Keras cache dir where the file is saved. If an absolute path /path/to/folder is specified the file will be saved at that location.`
For more info see https://www.tensorflow.org/api_docs/python/tf/keras/utils/get_file

**Comment by vinayapathak** [comment]
Thanks all!

**Comment by navi63** [comment]
@vinayapathak Hi
can you help me to solve this
i want to replace my files in this block of lines
image_path = tf.keras.utils.get_file(
      'flower_photos',
      'https://storage.googleapis.com/download.tensorflow.org/example_images/flower_photos.tgz',
      untar=True)

**Comment by vinayak-pathak** [comment]
Extremely sorry for late reply. Use !wget for best performance
