### ISSUE TITLE
Documentation for 'Adding a new op'

### ISSUE THREAD

**Issue by tvogels** [tensorflow/tensorflow#3441]
This is a feature request. Currently, I find the documentation for 'Adding an Op' quite minimal. There are a few important questions that remain unanswered:
- How should one use multithreaded CPU code in an operation? Can we use OpenMP? How many threads should an op use? It is hard to find this in the implementations of existing ops, because they are all based on _Eigen_.
- How should a GPU version of the op be written? Should it be a cuda kernel, or the code spawning cuda kernels? Maybe there could be a simple example for both CPU and GPU code not using Eigen.

**Comment by tvogels** [comment]
Can I use C++ threads in the CPU implementation of an op? And how should I choose the number of threads to use?

**Comment by sdrelton** [comment]
I'm also interested in using CPU threads in an op. Did you ever figure it out @tvogels?

**Comment by tvogels** [comment]
No, sorry, I left it single threaded

**Comment by sdrelton** [comment]
@tvogels No problem, thanks anyway

**Comment by cwhipkey** [comment]
In random_op.cc, there is an example of a multi-threaded op in the CPUDevice FillPhiloxRandom: 
  https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/kernels/random_op.cc#L164
It uses the Shard function declared in work_sharder.h to split work across multiple threads.

**Comment by sdrelton** [comment]
Brilliant thank you very much! That's my weekend sorted :)
________________________________________

**Comment by cwhipkey** [comment]
Some documentation has been added, and should be available when documentation is next rebuilt.
