### ISSUE TITLE
How to limit tensorflow CPU and memory usage in c_api?

### ISSUE THREAD

**Issue by msnh2012** [tensorflow/tensorflow#34410]
**In python:**
`sess = tf.Session(config=
    tf.ConfigProto(inter_op_parallelism_threads=1,
                   intra_op_parallelism_threads=1))`
**c_api:**
How?

**Comment by alextp** [comment]
Use TF_SessionOptions https://github.com/tensorflow/tensorflow/blob/f7c570c53cee6bf140c7900ae01f857871f74d26/tensorflow/c/c_api.h#L147 to set the config proto, which has those fields.
