### ISSUE TITLE
Multiple public header files are not usable. Dependencies are missing.

### ISSUE THREAD

**Issue by DEKHTIARJonathan** [tensorflow/tensorflow#34428]
Hi,

The following files import header files from path which are not existing:

```bash
$ cd /usr/local/lib/python3.6/dist-packages/tensorflow/include/
$ grep -rnw '.' -e 'third_party/gpus/cuda'

./tensorflow/stream_executor/gpu/gpu_types.h:31:#include "third_party/gpus/cuda/include/cuComplex.h"
./tensorflow/stream_executor/gpu/gpu_types.h:32:#include "third_party/gpus/cuda/include/cuda.h"
./tensorflow/core/util/gpu_kernel_helper.h:22:#include "third_party/gpus/cuda/include/cuda_fp16.h"
./tensorflow/core/util/gpu_device_functions.h:34:#include "third_party/gpus/cuda/include/cuComplex.h"
./tensorflow/core/util/gpu_device_functions.h:35:#include "third_party/gpus/cuda/include/cuda.h"
```

This is problematic because the headers can't be imported as the path requested does not exist:
```bash
$ ls /usr/local/lib/python3.6/dist-packages/tensorflow/include/third_party/gpus/cuda/include/
ls: cannot access '/usr/local/lib/python3.6/dist-packages/tensorflow/include/third_party/gpus/cuda/include/': No such file or directory
```

Problem was caused by this commit: https://github.com/tensorflow/tensorflow/commit/922386b9fcc23596877da3500787a045a861cb52#diff-3146a2ef48234a027b42c52f71bcb177

This issue lead to multiple issues as soon as CUDA GPUs are used with the C++ API.

**Workaround:**
As a temporary solution, one may create a symbolic link from the CUDA path, nonetheless modifying system should not be a permanent solution.
```bash
mkdir -p /usr/local/lib/python3.6/dist-packages/tensorflow/include/third_party/gpus/cuda/
ln -s /usr/local/cuda/include /usr/local/lib/python3.6/dist-packages/tensorflow/include/third_party/gpus/cuda/
ls /usr/local/lib/python3.6/dist-packages/tensorflow/include/third_party/gpus/cuda/include
```

**Solution:**
Instead of:
```cpp
#include "third_party/gpus/cuda/include/cuComplex.h"
#include "third_party/gpus/cuda/include/cuda.h"
```

Please do:
```cpp
#include "cuda/include/cuComplex.h"
#include "cuda/include/cuda.h"
```

**Comment by sanjoy** [comment]
@DEKHTIARJonathan can you share how you're building and/or using TensorFlow?  Are you building a TF pip package and using that?

**Comment by Artem-B** [comment]
Do I understand it correctly that you are attempting to use TF headers that are included along with a *python* package? I'm not sure if that's supposed to work in principle. Tensorflow in general requires  rather particular build setup in order to work. I would not expect any C++ bits to work/compile outside of that build environment. I could be wrong, though. 
@sanjoy -- does TF provide precompiled C++ libraries to end-users? Or do we only expose python API packages? I see that there's a separate C library: https://www.tensorflow.org/install/lang_c but it does not expose any C++ headers.

**Comment by byronyi** [comment]
There is a custom-op template repo which implements the CUDA kernel using TF Python package; take look at [this](https://github.com/tensorflow/custom-op/blob/master/tensorflow_time_two/cc/kernels/time_two_kernels.cu.cc#L21).

If you are using Bazel, my guess is that the headers are linked via [this line](https://github.com/tensorflow/custom-op/blob/master/tensorflow_time_two/BUILD#L34). Alternatively, if you are using Makefile, take a look at [this](https://github.com/tensorflow/custom-op/blob/master/Makefile#L34).

Also ping @yifeif; she is the author of the custom-op template repo.

**Comment by Artem-B** [comment]
The custom op most likely requires building it in the same environment where TF itself was built -- the headers rely on all sorts of macros that may be set differently depending on TF build configuration. 
Custom op build instructions here https://github.com/tensorflow/custom-op  use docker containers provided by TF for that purpose. 

From the FAQ on that page:

> Q: Do I need both the toolchain and the docker image? 
> A: Yes, you will need both to get the same setup we use to build TensorFlow's official pip package.
>

**Comment by byronyi** [comment]
> The custom op most likely requires building it in the same environment where TF itself was built -- the headers rely on all sorts of macros that may be set differently depending on TF build configuration.
> Custom op build instructions here https://github.com/tensorflow/custom-op use docker containers provided by TF for that purpose.
> 
> From the FAQ on that page:
> 
> > Q: Do I need both the toolchain and the docker image?
> > A: Yes, you will need both to get the same setup we use to build TensorFlow's official pip package.

I guess that is so, until Op registration is implemented in C API.

**Comment by sanjoy** [comment]
Closing since IIUC there is nothing for us to do here as per comments above..  Please reopen if you disagree.
