### ISSUE TITLE
Issue in building TFLITE static library for linux environment 

### ISSUE THREAD

**Issue by SidGATOR** [tensorflow/tensorflow#34423]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution 
Linux Ubuntu 16.04
- TensorFlow installed from (source or binary): v1.15.0-rc-2
- Python version: 3.6
- Installed using virtualenv? pip? conda?: From source
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source): gcc5.5
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

**Describe the problem**
Cannot compile static library for TFLITE inference engine using the provided Makefile. When run, generated_scheme.h will not be link with flatbuffers/flatbuffers.h and will flag variable not declared in this scope for everything 
**Provide the exact sequence of commands / steps that you executed before running into the problem**
git clone https://github.com/tensorflow/tensorflow.git
git checkout tags/v1.15.0-rc-2
cd tensorflow
./tensorflow/lite/tools/make/download_dependencies.sh 
 ./tensorflow/lite/tools/make/build_lib.sh

**Any other info / logs**

**Comment by SidGATOR** [comment]
issue can be resolved by removing line 33 and 34 from the Makefile in ./tensorflow/lite/tools/make/Makefile
`INCLUDES := \
-I. \
-I$(MAKEFILE_DIR)/../../../../../ \
-I$(MAKEFILE_DIR)/../../../../../../ \
-I$(MAKEFILE_DIR)/downloads/ \
-I$(MAKEFILE_DIR)/downloads/eigen \
-I$(MAKEFILE_DIR)/downloads/absl \
-I$(MAKEFILE_DIR)/downloads/gemmlowp \
-I$(MAKEFILE_DIR)/downloads/neon_2_sse \
-I$(MAKEFILE_DIR)/downloads/farmhash/src \
-I$(MAKEFILE_DIR)/downloads/flatbuffers/include \
-I$(OBJDIR)`

To 
`-I. \
-I$(MAKEFILE_DIR)/downloads/ \
-I$(MAKEFILE_DIR)/downloads/eigen \
-I$(MAKEFILE_DIR)/downloads/absl \
-I$(MAKEFILE_DIR)/downloads/gemmlowp \
-I$(MAKEFILE_DIR)/downloads/neon_2_sse \
-I$(MAKEFILE_DIR)/downloads/farmhash/src \
-I$(MAKEFILE_DIR)/downloads/flatbuffers/include \
-I$(OBJDIR)`

**Comment by gowthamkpr** [comment]
So, the issue is resolved here right @SidGATOR

**Comment by SidGATOR** [comment]
> So, the issue is resolved here right @SidGATOR

Yes it is. You can add the changes to the branch
