### ISSUE TITLE
Extremely slow pre-processing of images using InceptionV3

### ISSUE THREAD

**Issue by anthonyatp** [tensorflow/tensorflow#34424]
**System information**
- OS Platform and Distribution: Google AI Platform
- TensorFlow version: v2.0
- Python version: v3.*
- Machine type: 4 vCPUs, 15 GB RAM
- GPU: 1x NVIDIA Tesla K80

I am training a model to caption images and have mostly used this tutorial: https://www.tensorflow.org/tutorials/text/image_captioning#download_and_prepare_the_ms-coco_dataset

The issue is, I am trying to pre-process each image with InceptionV3 and cache the output to disk, however, each iteration (code snippet below) takes about 22s without GPUs and 18s with NVIDIA Tesla K80. This is way too slow for 30,000+ images for example. 

My image file size ranges between 60-150kb each.

```
# Get unique images
encode_train = sorted(set(img_name_vector))

image_dataset = tf.data.Dataset.from_tensor_slices(encode_train)
image_dataset = image_dataset.map(
  load_image, num_parallel_calls=tf.data.experimental.AUTOTUNE).batch(16)

for img, path in image_dataset:
  batch_features = image_features_extract_model(img)
  batch_features = tf.reshape(batch_features,
                              (batch_features.shape[0], -1, batch_features.shape[3]))

  for bf, p in zip(batch_features, path):
    np.save(tf.io.gfile.GFile(IMG_PATH, 'w'), bf.numpy())
```

The tensorflow tutorial claims that caching will take about 10 minutes to run in Colab with a GPU (for 30,000 images).

I wonder if I am doing something wrong, or if there is a more efficient way to achieve this?

Any help is appreciated!

**Comment by rmothukuru** [comment]
@anthonyatp,
Can you try reducing the Batch Size and check if it helps. Thanks!

**Comment by anthonyatp** [comment]
@rmothukuru 
I reduced the batch size from 16 to 8 and it takes around 11s per iteration but it has double the amount of iterations so would actually take longer than if batch size was 16?

As mentioned, the tutorial claims this takes 10mins to run in colab with GPU (for 30k images and batch size 16) - currently that would take me over 9 hours. Obviously I'm using a different dataset but the image sizes are comparable to the tutorial.

The other notable difference is that I am using a dataset stored in GCS and not local - could this be the issue?

Otherwise, it's pretty unrealistic for me to train this model using a relatively small dataset

**Comment by gowthamkpr** [comment]
I think data read here is a bottle neck as I tried running the code thats given [here](https://www.tensorflow.org/tutorials/text/image_captioning#download_and_prepare_the_ms-coco_dataset) and didn't face any issues.

More over you can try converting your data into TFRecords asTFRecords and corresponding TF infrastructure for them (queues/runners/readers) are really optimized for fast reading.By using tf.data API and especially Dataset.prefetch(), you can gain a substantial speedup.

You can also go though the 2nd answer given [here](https://stackoverflow.com/questions/55260190/how-to-speed-up-my-keras-cnn-with-pre-trained-inceptionv3). If you have any more questions, I would recommend posting them on stackoverflow. Thanks!
