### ISSUE TITLE
bazel build issue for tensorflow 2.0

### ISSUE THREAD

**Issue by xiang123** [tensorflow/tensorflow#34425]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution: Linux Ubuntu 18.04 
- TensorFlow installed from source
- TensorFlow version 2.0.0
- Python version: 2.7.15+ and python 3.6.8
- Installed using pip
- Bazel version 1.1.0
- GCC/Compiler version : gcc 7.4.0
- CUDA/cuDNN version: CUDA Version 10.1.243,  cuDNN version 7.6.5
- CPU model and memory: Intel® Core™ i7-7700HQ CPU @ 2.80GHz × 8, 15.4GB
- GPU model and memory: GeForce GTX 1050 Ti/PCIe/SSE2, 4GB

**Describe the problem**
I try to do bazel build for tensorflow
when running this command $bazel build //tensorflow/tools/pip_package:build_pip_package
it give me these error:

```
ERROR: /home/linxiang/tensorflow/tensorflow/stream_executor/cuda/BUILD:198:1: C++ compilation of rule '//tensorflow/stream_executor/cuda:cublas_stub' failed (Exit 1)
In file included from tensorflow/stream_executor/cuda/cublas_stub.cc:66:0:
./tensorflow/stream_executor/cuda/cublas_10_1.inc:122:25: error: 'cublasLogCallback' was not declared in this scope
 cublasSetLoggerCallback(cublasLogCallback userCallback) {
                         ^~~~~~~~~~~~~~~~~
./tensorflow/stream_executor/cuda/cublas_10_1.inc:122:25: note: suggested alternative: 'cublasSetLoggerCallback'
 cublasSetLoggerCallback(cublasLogCallback userCallback) {
                         ^~~~~~~~~~~~~~~~~
                         cublasSetLoggerCallback
./tensorflow/stream_executor/cuda/cublas_10_1.inc:130:25: error: 'cublasLogCallback' was not declared in this scope
 cublasGetLoggerCallback(cublasLogCallback *userCallback) {
                         ^~~~~~~~~~~~~~~~~
./tensorflow/stream_executor/cuda/cublas_10_1.inc:130:25: note: suggested alternative: 'cublasGetLoggerCallback'
 cublasGetLoggerCallback(cublasLogCallback *userCallback) {
                         ^~~~~~~~~~~~~~~~~
                         cublasGetLoggerCallback
./tensorflow/stream_executor/cuda/cublas_10_1.inc:130:44: error: 'userCallback' was not declared in this scope
 cublasGetLoggerCallback(cublasLogCallback *userCallback) {
                                            ^~~~~~~~~~~~
./tensorflow/stream_executor/cuda/cublas_10_1.inc:130:44: note: suggested alternative: 'CUstreamCallback'
 cublasGetLoggerCallback(cublasLogCallback *userCallback) {
                                            ^~~~~~~~~~~~
                                            CUstreamCallback

```

**Comment by xiang123** [comment]
in configure.py, I only put yes for Do you wish to build TensorFlow with CUDA support? [y/N]: Y.

**Comment by gadagashwini** [comment]
@xiang123, In the configure.py, did you set the path for CUDA. Thanks!

**Comment by xiang123** [comment]
> @xiang123, In the configure.py, did you set the path for CUDA. Thanks!
it fond the path by itself
the configure shows:
Found CUDA 10.1 in:
    /usr/local/cuda/lib64
    /usr/local/cuda/include
Found cuDNN 7 in:
    /usr/local/cuda/lib64
    /usr/local/cuda/include

**Comment by xiang123** [comment]
@gadagashwini 
it fond the path by itself
the configure shows:

Found CUDA 10.1 in:
/usr/local/cuda/lib64
/usr/local/cuda/include
Found cuDNN 7 in:
/usr/local/cuda/lib64
/usr/local/cuda/include

**Comment by xiang123** [comment]
after I switch CUDA back to 10.0 problem solved

**Comment by LeicongLi** [comment]
What if I want to build tensorflow using cuda 10.2.
Is there a solution other than downgrading cuda to 10.0?
