### ISSUE TITLE
r2.0/2.1 Python 3.8 AutoGraph could not transform <bound method LinearRegressionTF.fit of <tensorflow.python.eager.function.TfMethodTarget object at 0x7f7a5ccc1fa0>> and will run it as-is

### ISSUE THREAD

**Issue by dbonner** [tensorflow/tensorflow#34433]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes (attached file code_warning_py38.py.txt -> rename it as .py and execute it)
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below): This problem occurs with both r2.0 (built from head) and r2.1rc0
- Python version: 3.8 virtual environment (The problem does not occur with Python 3.7.3)
- Bazel version (if compiling from source): 0.26.1
- GCC/Compiler version (if compiling from source): 7.4.0
- CUDA/cuDNN version: CUDA 10 / cuDNN 7.6.5
- GPU model and memory: Nvidia Geforce RTX 2080 Ti

**Describe the current behavior**
export AUTOGRAPH_VERBOSITY=10
Run the attached python script (renamed as .py)
python code_warning_py38.py &> output.txt
Read the output in the attached output.txt

**Describe the expected behavior**
There is no warning message when the script is run with Python 3.7.3

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.
See both files attached.
[code_warning_py38.py.txt](https://github.com/tensorflow/tensorflow/files/3867410/code_warning_py38.py.txt)
[output.txt](https://github.com/tensorflow/tensorflow/files/3867412/output.txt)

**Comment by gadagashwini** [comment]
@dbonner, Thanks for reporting the issue. Please provide the input data file to reproduce the reported issue. Thanks!

**Comment by dbonner** [comment]
@gadagashwini 
[cal_house.json.gz](https://github.com/tensorflow/tensorflow/files/3873037/cal_house.json.gz)
Sorry, I forgot to do this.  Here it is.
Regards,
Dan

**Comment by gadagashwini** [comment]
Works without warning or error with Tf 2.0 and Python 3.6.
Please see the gist [here](https://colab.sandbox.google.com/gist/gadagashwini/850e1f79b50a8847c2fff9e42aa2b4bf/untitled274.ipynb). Thanks!

**Comment by dbonner** [comment]
@gadagashwini and @jvishnuvardhan 
I expected Python 3.6 with TF2.0 to work without warning or error.
I believe this problem only occurs with Python 3.8 with TF2.0 built from source using Python 3.8.
All the best,
Daniel

**Comment by mdanatg** [comment]
I'm looking into this, but am a bit swamped today. If you have the chance, could you check the version of `gast` you have installed?

**Comment by dbonner** [comment]
Hi Dan,
gast==0.2.2
Cheers

**Comment by mdanatg** [comment]
Thanks, that saved me a few roundtrips.

I ran a build with 3.8, and it looks like the AST transformations need to be updated to work with Python 3.8, I suspect that's because of the grammar changes. I'll make the necessary fixes, hopefully it won't take more than a week or two to finish them.

**Comment by mdanatg** [comment]
Update - after https://github.com/tensorflow/tensorflow/commit/a396eb4a3a7dc08b859df42919fcc7bdf8236a01, 3.8 syntax should be fully supported. I'm re-checking the script to see if anything else remains.

**Comment by mdanatg** [comment]
Looks like astor is not compatible with 3.8, either, so we'll need to replace that dependency. Fortunately it's fairly straightforward to swap in something else like astunparse.

**Comment by mdanatg** [comment]
Progress update - upgrade to astunparse is done, awaiting new release of gast which fixes a bug with FunctionDef nodes in 3.8 (see https://github.com/serge-sans-paille/gast/pull/43).

**Comment by mdanatg** [comment]
This should now be fixed at head. With the pip package from source, running code_warning_py38.py should no longer print a warning.

**Comment by dbonner** [comment]
I can't test the resolution until I build tensorflow for python 3.8.0.  Unfortunately my build is failing (see issue #36170 )

**Comment by dbonner** [comment]
I got the build to work.  Yes, this is fixed.
