### ISSUE TITLE
Build failure: undefined reference to protobuf symbols #34117 closed issue still occurring on r2.1

### ISSUE THREAD

**Issue by dbonner** [tensorflow/tensorflow#34439]
Re: [https://github.com/tensorflow/tensorflow/issues/34117](url)
This issue is still occurring when I build r2.1 branch with bazel 1.1.0.
It has been fixed on head.  Would it be possible to implement the fix on build r2.1
Also the maximum bazel version needs to be increased to 1.1.0 in configure.py once the fix is implemented (in both head and r2.1).

**Comment by goldiegadde** [comment]
We do not intend to change the Bazel version on r2.1 branch. 
@mihaimaruseac as well to confirm.

**Comment by mihaimaruseac** [comment]
We should only cherry-pick the fix from head but we are too late in the release process to do another bazel version switch.

**Comment by amahendrakar** [comment]
@dbonner,
Hope the above comments answered your query. Can we close this issue if you have no further queries? Thanks!
