### ISSUE TITLE
tensorflow is not using GPU

### ISSUE THREAD

**Issue by sehargul-123** [tensorflow/tensorflow#34434]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 18.04):
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:None
- TensorFlow installed from (source or binary):binary
- TensorFlow version:tensorflow-gpu==1.14
- Python version:3.6.8
- Installed using virtualenv? pip? conda?:pip
- Bazel version (if compiling from source):none
- GCC/Compiler version (if compiling from source):none
- CUDA/cuDNN version:10.1/7.6.4
- GPU model and memory:GeForce GTX 1060 6GB and 6144 MB

**Describe the problem** my problem is that my gpu is not being used during training 

**Provide the exact sequence of commands / steps that you executed before running into the problem**
I have run the following command for training my model
python -u "DeepSpeech.py"\
    --train_files "/home/sehar/urdu/cv-valid-train.csv"\
    --dev_files "/home/sehar/urdu/cv-valid-dev.csv" \
    --test_files "/home/sehar/urdu/cv-valid-test.csv" \
    --alphabet_config_path "/home/sehar/urdu-models/alphabet.txt" \
    --lm_binary_path "/home/sehar/urdu-models/lm.binary" \
    --lm_trie_path "/home/sehar/urdu-models/trie" \
    --learning_rate 0.000025 \
    --dropout_rate 0\
    --log_level 1 \
    --noearly_stop \
    --epochs 100 \
    --max_to_keep 1 \
    --checkpoint_dir "/home/sehar/DeepSpeech/check" \
    --export_dir "/home/sehar/urdu-models"

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by ymodak** [comment]
Please switch to cuda 10.0 or gpu support
See [software requirements](https://www.tensorflow.org/install/gpu#software_requirements)

**Comment by ravikyram** [comment]
@sehargul-123 

Any update on this issue please. Thanks!

**Comment by ravikyram** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
