### ISSUE TITLE
Model mismatch between create_low_latency_conv_model and cnn-one-fstride4

### ISSUE THREAD

**Issue by csukuangfj** [tensorflow/tensorflow#34432]
https://github.com/tensorflow/tensorflow/blob/ba63d9082a2265da91ec4daefecfa4cd47fcf07f/tensorflow/examples/speech_commands/models.py#L337-L339

But the stride is actually **one** instead of **four**:

https://github.com/tensorflow/tensorflow/blob/ba63d9082a2265da91ec4daefecfa4cd47fcf07f/tensorflow/examples/speech_commands/models.py#L388-L389

which results in a **huge** increase of the number of parameters of the subsequent FC layer.

**Comment by ravikyram** [comment]
@csukuangfj 

Can you please let us know which TensorFlow version you are using.Will it be possible to share related code, it helps us in localizing the issue faster. Thanks!

**Comment by csukuangfj** [comment]
@ravikyram 
the links in the above issue comment come from the latest master branch.

**Comment by Saduf2019** [comment]
@csukuangfj
Is this still an issue.

**Comment by csukuangfj** [comment]
@Saduf2019 

Sorry, I am no longer working on it and I am not able to set up an environment to verify it.

**Comment by Saduf2019** [comment]
@csukuangfj
In that case can you please move this to close status.
