### ISSUE TITLE
AttributeError: module 'tensorflow' has no attribute 'app'

### ISSUE THREAD

**Issue by Casco-csv** [tensorflow/tensorflow#34431]
Hi, I'm new in the field of machine learning, and I started watching a video about how to classify images
Video: https://www.youtube.com/watch?v=EKe05rMG-Ww

but in a part when I run: python csv_a_tf.py --csv_input=CSV/test.csv --output_path=TFRecords/test.record --images=images

this gives me back:
----------------------------------------
Traceback (most recent call last):
  File "csv_a_tf.py", line 24, in <module>
    flags = tf.app.flags
AttributeError: module 'tensorflow' has no attribute 'app'
----------------------------------------
any ideas?

**Comment by shun-lin** [comment]
Are you using tensorflow version 1.x or tensorflow version 2.x, in this tensorflow 2 guide, https://www.tensorflow.org/guide/effective_tf2, it says `tf.app` is removed. Therefore I think the code in `csv_a_tf.py` is using `tf 1.x` version and the tensorflow in your environment in 2.x. I hope this helps!

To resolve, either uninstall tensorflow 2.x and then install 1.x, or modify the code so that it uses 2.x API :)

**Comment by Casco-csv** [comment]
Thanks it has helped me a lot :D

**Comment by Shivaganesh367** [comment]
Can you tell me how solved this AttributeError:module 'tensorflow' has no attribute 'app'.

**Comment by motaha** [comment]
Like what @shun-lin said, 'app' is removed from tensorflow 2.x. So, check your tensorflow version if it is 2.x then you either have to install a tensorflow 1.x version or modify your code to support the 2.x version.

**Comment by Cibi075** [comment]
> Are you using tensorflow version 1.x or tensorflow version 2.x, in this tensorflow 2 guide, https://www.tensorflow.org/guide/effective_tf2, it says `tf.app` is removed. Therefore I think the code in `csv_a_tf.py` is using `tf 1.x` version and the tensorflow in your environment in 2.x. I hope this helps!
> 
> To resolve, either uninstall tensorflow 2.x and then install 1.x, or modify the code so that it uses 2.x API :)

apt solution

**Comment by abdelazizmirasoft** [comment]
Try to use: `import tensorflow.compat.v1 as tf
`

**Comment by krishbala07** [comment]
To resolve this issue I uninstall tensorflow : pip uninstall tensorflow
                                       and
Install tensorflow :  pip install tensorflow==1.15

**Comment by zenglian** [comment]
Use abseil instead: See https://abseil.io/docs/python/quickstart

**Comment by azeemabbas** [comment]
Replace tf.app with tf.compat.v1.app

**Comment by yashmukaty** [comment]
If I do this - Replace tf.app with tf.compat.v1.app it says AttributeError: module 'tensorflow_core._api.v2.compat.v1.app' has no attribute 'DEFINE_string'

**Comment by azeemabbas** [comment]
> Replace tf.app with tf.compat.v1.app

I worked for me but later on I got tf.contrib error. Even I tried on Google Colab, tf.contrib error is same.

So finally on my local machine, I downgraded the tensorflow to 1.15.x using
pip uninstall tensorflow
pip install pip install tensorflow==1.15.2


For Google Colab, I used 

%tensorflow_version 1.x
import tensorflow as tf

**Comment by shantanumane** [comment]
If I don't want to uninstall tensorflow==2.1 then how should I progress further.
There is any other option.

**Comment by enragedginger** [comment]
For anyone reading this who doesn't want to ditch Tensorflow 2, the Effective Tensorflow 2 API changes are listed [here](https://www.tensorflow.org/guide/effective_tf2).

That page has this sentence:

> Some of the major changes include removing tf.app, tf.flags, and tf.logging in favor of the now open-source absl-py

and links you to [this project](https://github.com/abseil/abseil-py)

which says you can install with this `pip install absl-py`.

The README for absl-py also links to [an example application](https://github.com/abseil/abseil-py/blob/master/smoke_tests/sample_app.py) which shows what needs to change in your code.

Alternatively, you can just run `tf_upgrade_v2` against your code as detailed [here](https://www.tensorflow.org/guide/upgrade).

**Comment by Xxiexie** [comment]
亲测，1.14版本的不行

**Comment by ianguidini** [comment]
If you're using TensorFlow 2 there's a very easy solution.

First make sure you have abseil installed https://github.com/abseil/abseil-py

In your code, `import absl`

Then in your code, replace `tf.app.flags` for `absl.flags`

So for example:

`flags = absl.flags`

There you go! Everything else can stay the same!

**Comment by TheManjia** [comment]
So the solution is to "use a thirdy part library because we removed ours?"
This is nowhere close to a solution, what if anyone has to use an existing generate_tfRecord.py?

**Comment by ianguidini** [comment]
If anyone has to use an existing generate_tfrecord.py that is incompatible
with the TensorFlow version they are using, but are also impeded from
downgrading their Tensorflow version as other comments have suggested here,
but also refuse to use a third party open-source library to patch that case
of incompatibility, then my final suggestion would be to look in other
threads for a different existing generate_tfrecord script, that is
compatible with their TensorFlow version.

**Comment by Bmoradi93** [comment]
> Try to use: `import tensorflow.compat.v1 as tf `

Thank you!
That was the solution!

**Comment by lxf745194316** [comment]
> Replace tf.app with tf.compat.v1.app

it does not work

**Comment by tauruswcc** [comment]
> For anyone reading this who doesn't want to ditch Tensorflow 2, the Effective Tensorflow 2 API changes are listed [here](https://www.tensorflow.org/guide/effective_tf2).
> 
> That page has this sentence:
> 
> > Some of the major changes include removing tf.app, tf.flags, and tf.logging in favor of the now open-source absl-py
> 
> and links you to [this project](https://github.com/abseil/abseil-py)
> 
> which says you can install with this `pip install absl-py`.
> 
> The README for absl-py also links to [an example application](https://github.com/abseil/abseil-py/blob/master/smoke_tests/sample_app.py) which shows what needs to change in your code.
> 
> Alternatively, you can just run `tf_upgrade_v2` against your code as detailed [here](https://www.tensorflow.org/guide/upgrade).
Thank you so much for your comments! I finally solve the problem by using the abseil package. Specifically, I use the following:

```
from absl import app
from absl import flags

FLAGS = flags.FLAGS
```

**Comment by TramBao2000** [comment]
> > Replace tf.app with tf.compat.v1.app
> 
> It worked for me but later on I got tf.contrib error. Even I tried on Google Colab, tf.contrib error is same.
> 
> So finally on my local machine, I downgraded the tensorflow to 1.15.x using pip uninstall tensorflow pip install tensorflow==1.15.2
> 
> For Google Colab, I used
> 
> %tensorflow_version 1.x import tensorflow as tf

thanks somuch

**Comment by VinceJnz** [comment]
This introduced "bug" impacts a number of object_detection tools.
Is it going to be fixed?
