### ISSUE TITLE
Add GPU delegate support to the TFLite experimental c api

### ISSUE THREAD

**Issue by stephen-systemfriend** [tensorflow/tensorflow#34436]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using): 2.0
- Are you willing to contribute it (Yes/No): Yes

**Describe the feature and the current behavior/state.**
the lite experimental c api (used by the unity plugin) currently only supports running the network on the CPU.
It would be very useful to be able to use the GPU delegate for apps made directly in unity.

**Will this change the current api? How?**
It extends the lite c api to be more in line with the c++ api. 

**Who will benefit with this feature?**
Anyone who wants to use Tensorflow in unity on modern phones.

**Comment by impjdi** [comment]
@stephen-systemfriend 

We made sure that `//tensorflow/lite/delegates/gpu/delegate.h` stays compatible with C.  I need a little bit of elaboration.  Are you requesting an API beyond the TFLite delegate?

**Comment by stephen-systemfriend** [comment]
I want to access the gpu delegate from some C# code. I'm currently using the Unity plugin, and was hoping to extend it to use the gpu delegate as well, but it didn't seem to be supported. I'll attempt to use the delegate as is and get back to you if it doesn't work.

**Comment by impjdi** [comment]
Ah, I always forget Unity is in C#.

@jdduke 

Do we have an official strategy on C# usage?

**Comment by jdduke** [comment]
We do support C# and Unity for CPU inference. We'd have to do some more investigation about GPU delegate work, though. Unity's render thread and context are likely unavailable on the sim thread, so we'd need to do some testing first to see how well this would work.

**Comment by stephen-systemfriend** [comment]
with the changes in https://github.com/stephen-systemfriend/tensorflow/commit/5c8659b0b61b2d6789119e18c231c8d6cb5c5d47 it seems to run fine on android (though the SSD net I wanted to use has some custom ops that currently get in the way). Can I make a pull request/what kind of tests should I run first?

**Comment by jdduke** [comment]
I would apply the delegate, try running the example model in the sample Unity app (I believe the operator should be supported by the GPU), check the adb logs and make sure you see something about GPU delegate initialization.

**Comment by rmothukuru** [comment]
@stephen-systemfriend,
Sorry for the delayed response. It looks like [TensorFlow Lite GPU delegate](https://www.tensorflow.org/lite/performance/gpu) has been implemented. Can you please check and confirm the same? Thanks!
