### ISSUE TITLE
Tensorflow C/C++ only?

### ISSUE THREAD

**Issue by sergeay** [tensorflow/tensorflow#34447]
- OS Platform and Distribution Linux Ubuntu 18.04
- Virtual guest on windows hyperV

Trying your installation steps and fails again and again:

pip install -U pip six numpy wheel setuptools mock 'future>=0

It's trying to connect without success, although the machine does not have any network issue.

Is there a way to use TensorFlow w/o python , only C/C++?

**Comment by abhiverma1924** [comment]
@sergeay Can you please explain clearly, what you are trying to do?

**Comment by bhack** [comment]
If you want c++ only check https://jacobgil.github.io/deeplearning/tensorflow-cpp

**Comment by gadagashwini** [comment]
@sergeay, Install Tensorflow C using the instructions mentioned [here](https://www.tensorflow.org/install/lang_c).  Please find the tensorflow C++ operation in this [link](https://www.tensorflow.org/api_docs/cc). Thanks!

**Comment by sergeay** [comment]
bhack and gadagashwini , thanks I'll try those links.

abhiverma1924, I am trying to make tensorflow work on my ubuntu 18.04 machine, I am not interested in any python and it seems the main page of tensorflow requires all kind of bazel, pyton this and python that, each installation step is failing one after the other and requires tons of time to look at the conflicting packages and environment and resolve the issues.

**Comment by gadagashwini** [comment]
@sergeay, Any update!

**Comment by sergeay** [comment]
I finally used the python interface and it works after some massages...
Thanks you for your help.

**Comment by mihaimaruseac** [comment]
Closing as it seems fixed.
