### ISSUE TITLE
Updating the guide for building TensorFlow Lite with select ops for iOS

### ISSUE THREAD

**Issue by tpeet** [tensorflow/tensorflow#34441]
Hi!

We followed the [guide](https://www.tensorflow.org/lite/guide/ops_select#ios), which seems bit outdated as `tensorflow/contrib` has been removed. We couldn't get TFLite model with select ops working on iOS, while the same model is working well on Android. It seems that bazel could also be used for building the library together with using private CocoaPods. We tested this approach but were also unsuccessful. Could the documentation be improved with this regard for having clearer guidelines?

Ideas and explanations of how to get it working are also welcome under this issue. Do you have an estimation when could we expect the CocoaPods (with-select-ops version) for iOS/Swift?

## URL(s) with the issue:
https://www.tensorflow.org/lite/guide/ops_select#ios

## Description of issue (what needs changing):
The current guide could be improved, especially because `tensorflow/contrib` is removed in the latest version of TensorFlow. Therefore, `tensorflow/contrib/makefile/build_all_ios_with_tflite.sh` is no longer available for building TensorFlow Lite with select ops support.

### Clear description
Couldn't get a TFLite model with select ops working in iOS by following the [guide](https://www.tensorflow.org/lite/guide/ops_select#ios). The same model was successfully working on Android with nightly builds. Would be nice to have a guide for how to build it with bazel.

### Correct links
N/A

### Parameters defined
N/A

### Returns defined
N/A

### Raises listed and defined
N/A

### Usage example
Would be good if it would be explained in more detail what has to be done. Do we only have to compile and link libraries as explained in the documentation or do we need to modify the code also, e.g. add Flex delegate as an option for Interpreter?

### Request visuals, if applicable
No need for visuals

### Submit a pull request?
N/A

**Comment by yyoon** [comment]
Will update the official document soon to reflect the changes in building TFLite with select ops for iOS.

In the meantime, you can try building the following bazel target:
```sh
bazel build --config=ios --ios_multi_cpus=armv7,arm64,x86_64 -c opt \
  //tensorflow/lite/experimental/ios:TensorFlowLiteCWithSelectTfOps_framework
```

The resulting framework can then be used in place of the `TensorFlowLiteC` framework described in this guide: https://www.tensorflow.org/lite/guide/build_ios

There's one more step to follow when building an app with this framework. In your Xcode project, go to `Build Settings` tab of your app target configuration, and add `-force_load <path/to/TensorFlowLiteCWithSelectTfOps.framework/TensorFlowLiteCWithSelectTfOps>` to the `Other Linker Flags` setting.

Let me know if you have any further questions. Will keep this bug open until the official doc is updated.

**Comment by tpeet** [comment]
Thank you very much! We got it working :)

**Comment by gitathrun** [comment]
@yyoon Hi, Yoon, thanks for your indication, great explaination! And you might want to change the cmdline a little for there is a typo, which causes the build process encounter bazel's "no such target" errors, remove the __C__ between TensorFlowLite and SelectTfOps_framework.

```
bazel build -c opt --config=ios --ios_multi_cpus=armv7,arm64,x86_64 //tensorflow/lite/experimental/ios:TensorFlowLiteSelectTfOps_framework
```

**Comment by gitathrun** [comment]
@tpeet Hi, tpeet, is there any documentation on how to use the big binary library with swift or obj-c? I import it to the project, but do not know where and how to start use it? Many thanks.

**Comment by gitathrun** [comment]
@yyoon Hi, Yoon, could you be more specific about the step at the stage of "in place of the TensorFlowLiteC framework"? Do I need to modify the .podsepc file only? or do I need to rewrite the TensorflowLiteSwift's source code, such as change the __import__ of __TensorflowLiteC__ to __TensorflowLiteSelectTfOps__ ?

**Comment by mtngld** [comment]
Just a note that the [documentation](https://www.tensorflow.org/lite/guide/ops_select) is still not  updated, maybe this issue should be reopened to track this?

**Comment by yyoon** [comment]
The select TF ops documentation for iOS has been updated (4654b512e70aa11958c0830f5c1fd07dc996745a). Feel free to file a new bug if you encounter any issues.
