### ISSUE TITLE
Modifications to BUILD to Use Target libtensorflowlite and make tar.gz

### ISSUE THREAD

**Issue by dtsmith2001** [tensorflow/tensorflow#34459]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04.3 LTS
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): source
- TensorFlow version: tag v2.0.0
- Python version: Python 3.6.8
- Installed using virtualenv? pip? conda?: from GitHub repository
- Bazel version (if compiling from source): Build label: 0.26.0
- GCC/Compiler version (if compiling from source): gcc version 7.4.0 (Ubuntu 7.4.0-1ubuntu1~18.04.1)
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

**Describe the problem**

I modified `tensorflow/tensorflow/tools/lib_package/BUILD` (enclosed). I am trying to build Tensorflow Lite in the same way the Tensorflow C library is built.

```bash
bazel build --jobs=1 --local_ram_resources=1024 --config=opt --config=v2 --config=noaws //tensorflow/tools/lib_package:libtensorflow
```

Final output:

```
Target //tensorflow/tools/lib_package:libtensorflow up-to-date:
  bazel-bin/tensorflow/tools/lib_package/libtensorflow.tar.gz
```
I'd like to do the same for Tensorflow Lite.

**Provide the exact sequence of commands / steps that you executed before running into the problem**

1. Compiled Tensorflow C package using `bazel build --jobs=1 --local_ram_resources=1024 --config=opt --config=v2 --config=noaws //tensorflow/tools/lib_package:libtensorflow`
2. Modified `tensorflow/tensorflow/tools/lib_package/BUILD`.
3. Compiled Tensorflow Lite using `bazel build --jobs=1 --local_ram_resources=1024 --config=opt --config=v2 --config=noaws //tensorflow/lite:libtensorflowlite.so`.
4. The archive `libtensorflowlite.tar.gz` is not produced.
5. Tried `bazel build --jobs=1 --local_ram_resources=1024 --config=opt --config=v2 --config=noaws //tensorflow/lite:libtensorflowlite.so` but got the error

```
ERROR: Skipping '//tensorflow/lite:libtensorflowlite': no such target '//tensorflow/lite:libtensorflowlite': target 'libtensorflowlite' not declared in package 'tensorflow/lite' (did you mean 'libtensorflowlite.so'?) defined by /mnt/drive/stuff/src/tensorflow/tensorflow/lite/BUILD
WARNING: Target pattern parsing failed.
ERROR: no such target '//tensorflow/lite:libtensorflowlite': target 'libtensorflowlite' not declared in package 'tensorflow/lite' (did you mean 'libtensorflowlite.so'?) defined by /mnt/drive/stuff/src/tensorflow/tensorflow/lite/BUILD
INFO: Elapsed time: 0.279s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 pac\
kages loaded)
```

I am happy to turn this into a PR.

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.
N/A

[BUILD.zip](https://github.com/tensorflow/tensorflow/files/3870140/BUILD.zip)

**Comment by dtsmith2001** [comment]
Apologies! My change worked. I found `libtensorflowlite.tar.gz` in `bazel-bin/tensorflow/tools/lib_package/`. I'll fork, push, and make a PR.

**Comment by amahendrakar** [comment]
> Apologies! My change worked. I found `libtensorflowlite.tar.gz` in `bazel-bin/tensorflow/tools/lib_package/`.

@dtsmith2001,
Any updates regarding this? Please feel free to close the issue if resolved. Thanks!

**Comment by dtsmith2001** [comment]
@amahendrakar Sorry, I got diverted. Let me look into this today.

**Comment by dtsmith2001** [comment]
No time to work on this. Closing.
