### ISSUE TITLE
Using skip and ignore_errors cause training hang

### ISSUE THREAD

**Issue by grzjab** [tensorflow/tensorflow#34458]
Using skip on a dataset that contains corrupted data and then applying ignore_errors() causes fit method to hang before the validation step. The fit method uses dataset for training and validation.

This behavior was reported using
Ubuntu 18.04, Tensorflow 2.0.0 installed using pip, python 3.7.3

```
import tensorflow as tf
dataset = tf.data.Dataset.from_tensor_slices([1., 0., 2., 1.,])
dataset = dataset.map(lambda x: tf.debugging.check_numerics(1. / x, "error"))

train = tf.data.Dataset.zip((dataset, dataset)).batch(1).repeat().apply(tf.data.experimental.ignore_errors())
val = tf.data.Dataset.zip((dataset, dataset)).skip(2).batch(1).repeat().apply(tf.data.experimental.ignore_errors())

model = tf.keras.Sequential([
    tf.keras.layers.Dense(32, activation='relu', input_shape=(1,)),
])
model.compile(optimizer='adam', loss='mse')
model.fit(train, epochs=10, steps_per_epoch=4, validation_data=val, validation_steps=2 )
```

**Comment by gadagashwini** [comment]
Issue is replicating with Tf 2.0.
Please take a look at colab [gist](https://colab.sandbox.google.com/gist/gadagashwini/db3cd6c2d13e3b16b6cc3fedfac2b1ae/untitled265.ipynb). Thanks!

**Comment by gowthamkpr** [comment]
@grzjab This bug has been fixed in TF-nightly. Please find my github gist [here](https://colab.sandbox.google.com/gist/gowthamkpr/3beef897724021a730c2e8b0086068c7/copy-of-untitled265.ipynb).

**Comment by grzjab** [comment]
Thank you!
