### ISSUE TITLE
python3.7.3 Anaconda tensorflow   No module named 'joblib'

### ISSUE THREAD

**Issue by Passenger12138** [tensorflow/tensorflow#34452]
I have successfully installed the sklearn library, but it shows the code running result display.
No module named 'joblib'
I am very confused, I hope to get your answer, thanks ‘
Here is my code

---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-25-638e12154cef> in <module>
----> 1 from sklearn.datasets import load_wine
      2 win_dataset=load_wine()
      3 print('\n\n\n')
      4 print("the result is")
      5 print("红酒中的数据：\n{}".format(wine_dataset.keys()))

~\AppData\Roaming\Python\Python37\site-packages\sklearn\__init__.py in <module>
     74 else:
     75     from . import __check_build
---> 76     from .base import clone
     77     from .utils._show_versions import show_versions
     78 

~\AppData\Roaming\Python\Python37\site-packages\sklearn\base.py in <module>
     14 
     15 from . import __version__
---> 16 from .utils import _IS_32BIT
     17 
     18 _DEFAULT_TAGS = {

~\AppData\Roaming\Python\Python37\site-packages\sklearn\utils\__init__.py in <module>
     15 from .murmurhash import murmurhash3_32
     16 from .class_weight import compute_class_weight, compute_sample_weight
---> 17 from . import _joblib
     18 from ..exceptions import DataConversionWarning
     19 from .deprecation import deprecated

~\AppData\Roaming\Python\Python37\site-packages\sklearn\utils\_joblib.py in <module>
      6     # joblib imports may raise DeprecationWarning on certain Python
      7     # versions
----> 8     import joblib
      9     from joblib import logger
     10     from joblib import dump, load

ModuleNotFoundError: No module named 'joblib'

**Comment by gowthamkpr** [comment]
Install joblib package using this command
`conda install -c anaconda joblib`
and this should solve your issue.

If you are still running into the sane issue, you can go through the following questions [#1](https://stackoverflow.com/questions/35103338/python-no-module-named-how-to-use-pip) and [#2](https://forum.knime.com/t/modulenotfounderror-no-module-named-joblib/15275).

**Comment by Passenger12138** [comment]
I have successfully solved the problem, thank you very much for your answer.
