### ISSUE TITLE
Unify the APIs on a tf.keras.Model when trained vs when it is saved and loaded.

### ISSUE THREAD

**Issue by MeghnaNatraj** [tensorflow/tensorflow#34463]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using): 2.0.0
- Are you willing to contribute it (Yes/No): No

**Describe the feature and the current behavior/state.**
Explaining the issue using inference as an example API:
Running inference on a loaded model is different than running inference on model you just trained and this causes confusion. For a trained model we use: `model.predict(input)` but for a loaded saved model we need to directly invoke the model by running `model(input)` as explained below:

a) Train a Model
```
model = tf.keras.Model(...)
model.compile(...)
model.fit(...)
```

**Method 1:**
b) Run Predictions
`model.predict(input)`

**Method 2:**
b) Save a Model
`tf.saved_model.save(model, '/tmp/model')`
c) Load a Model
`tf.saved_model.load(model, '/tmp/model')`
d) Run predictions on loaded model
`model(input)`

Note: There are many other model APIs that also differ this way. It would be better to have a consistent format.

**Will this change the current api? How?**
Yes, it would change the current API. You'd have to add additional functions to the current loaded model format or ensure it is loaded in the same way as a model trained in a jupyter notebook.

**Who will benefit with this feature?**
Everyone using tensorflow 2.0

**Any Other info.**
-

**Comment by k-w-w** [comment]
You should use `tf.keras.models.load_model` to use the Keras APIs (`predict`, `fit`, etc.) on the loaded model.

**Comment by MeghnaNatraj** [comment]
Thank you!
