### ISSUE TITLE
TF 1.15 to TF 2.0 breaking changes even with tf.compat.v1 for saving models for use with tf serving

### ISSUE THREAD

**Issue by SumNeuron** [tensorflow/tensorflow#34466]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): debian dockerized
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: n/a
- TensorFlow installed from (source or binary): docker
- TensorFlow version (use command below): 1.15 and 2.0.0
- Python version: 3.7
- Bazel version (if compiling from source): n/a
- GCC/Compiler version (if compiling from source): n/a
- CUDA/cuDNN version: n/a
- GPU model and memory: n/a

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
Currently trying to export a `tf.keras` model in v `2.0.0` using `tf.compat.v1` functions (which will be removed in the future) does not work. Using the same code in `1.15.0` works.  Currently there is not a `tf.compat.v2` function which is concerning for those using this functionality for compatibility with tf serving.

**Describe the expected behavior**
That code with `tf.compat.v1` works in `2.0` as it does in `1.15`

**Code to reproduce the issue**
This repo: https://gitlab.com/SumNeuron/docker-nf
Is my dockerized TF MWE. It contains the code necessary to reproduce the issue as well as subsequent steps (e.g. spin up a dockerized web app with the served model).

In order to reproduce the bug there are two files of relevance:

1. `Dockerfile.ai`
2. `notebooks/Make Toy Model.ipynb`

The first two lines of `Dockerfile.ai`:
```
FROM tensorflow/tensorflow:1.15.0rc2-gpu-py3-jupyter
# FROM tensorflow/tensorflow:2.0.0-gpu-py3-jupyter
```
are for convenience of toggling between TF versions.

To spin up the service:

```
docker-compose -f docker-compose.ai.development.yml build
docker-compose -f docker-compose.ai.development.yml up
```

Then navigate to the mounted notebook.
After running the toy model there is a code cell with markdown content:

>Simple Save for Serving

under which has the following code (which is more or less copy-paste from a tf official documentation example).

```
MODEL_DIR = '../models/serving/toy'
version = 1
export_path = os.path.join(MODEL_DIR, str(version))
if not os.path.isdir(export_path):
    os.makedirs(export_path)
    
tf.compat.v1.saved_model.simple_save(
    tf.compat.v1.keras.backend.get_session(),
    export_path,
    inputs={'input_tensor': model.input},
    outputs={'output_tensor': model.outputs[0]})
```
This will work when using tf version `1.15`. It will fail with tf version `2.0`

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by nikochiko** [comment]
@SumNeuron , the notebook you have shared saves the model successfully. Please share a notebook in which you face the issue.

**Comment by SumNeuron** [comment]
@nikochiko did you change the `FROM` statement in `Dockerfile.ai` from 

```dockerfile
FROM tensorflow/tensorflow:1.15.0rc2-gpu-py3-jupyter
# FROM tensorflow/tensorflow:2.0.0-gpu-py3-jupyter
```

to 

```
# FROM tensorflow/tensorflow:1.15.0rc2-gpu-py3-jupyter
FROM tensorflow/tensorflow:2.0.0-gpu-py3-jupyter
```

**Comment by nikochiko** [comment]
@SumNeuron What error are you getting? You have provided too little information to help. 
And to make TF1.X code compatible with TF2.X, you need to disable eager execution with `tf.compat.v1.disable_eager_execution()`.
Works fine for me. See gist: https://colab.research.google.com/gist/nikochiko/cc43b4e4e57918669c217c9fe91270b1/34466.ipynb

**Comment by nikochiko** [comment]
@oanush @gowthamkpr , I think this issue is wrongly marked as a bug. Please see.

**Comment by SumNeuron** [comment]
@nikochiko ah so it was 
```
tf.compat.v1.disable_eager_execution()
``` 
that was the missing line?

**Comment by nikochiko** [comment]
@SumNeuron Yes. See the gist.

**Comment by SumNeuron** [comment]
@nikochiko Then for now I recommend perhaps updating the error message.
Set `enable_eager = True` and run with 2.0 and get the error:


```
RuntimeError: build_tensor_info is not supported in Eager mode.
```

to include a statement pointing to `tf.compat.v1.disable_eager_execution()`

**Comment by nikochiko** [comment]
@SumNeuron Why did you change it to True?

**Comment by SumNeuron** [comment]
@nikochiko to see the error message. When eager was rolled out there was emphasis on enabling it (auto-on for 2.0), but i have yet to encounter that it could or may need to be disabled for v1 compatibility, so adding a note to the error message may be useful to other users as well

**Comment by nikochiko** [comment]
No, look, you can avoid errors altogether with this syntax instead: 
```python
if tf.executing_eagerly():
  tf.compat.v1.disable_eager_execution()
```

**Comment by SumNeuron** [comment]
@nikochiko the point I was trying to make is that the need for
```
tf.compat.v1.disable_eager_execution()
```
is not made explicitly clear, especially as many `tf.compat.v1` functions also work in eagerly. 


Semirelated, do you know the v2 version of the code (e.g. how to achieve the same `.pb` file without `v1` functions?

**Comment by nikochiko** [comment]
@SumNeuron , if I understand correctly, you are trying to make your code compatible with both `TensorFlow 1.X` and `TensorFlow 2.X`. You should first decide whether you want to have eager execution enabled or not, and you can continue with that. As you mentioned that some v1 compat functions are compatible with eager execution, but it will be weird to have your code execute differently in 1.X and 2.X considering that your goal was to make it usable in both. 

For the TensorFlow 2.X version of the code, you can use the [`tf_upgrade_v2`](https://www.tensorflow.org/guide/upgrade) utility. It will convert all v1 symbols to their v2 equivalents.

**Comment by SumNeuron** [comment]
@nikochiko Not quite. I am happy to transfer to v2 and live in the new TF paradigm. 

You might have noticed in your colab (copy from the repo I provided), the header for the code which breaks without disabling eager, is "Simple Save for Serving". 

The only thing I want to be compatible in V2 is saving a trained keras model for later use with `tf-serving`

**Comment by nikochiko** [comment]
@SumNeuron , if you are ready to move to TF2, you only need to apply `tf_upgrade_v2`.
@gowthamkpr , please take this on from here.

**Comment by gowthamkpr** [comment]
@SumNeuron I am gonna close this issue for now as its not related to bug/performance, build/install, feature or docs related issues. Please post any more questions that you have on stackoverflow as there is a wider community to respond. Thanks @SumNeuron for answering.
