### ISSUE TITLE
404 link in documentation

### ISSUE THREAD

**Issue by gregsadetsky** [tensorflow/tensorflow#34460]
## URL(s) with the issue:

https://github.com/tensorflow/docs/blob/master/site/en/r1/tutorials/sequences/audio_recognition.md

## Description of issue (what needs changing):

Non functioning link in the documentation:

```
### Custom Training Data
By default the script will download the [Speech Commands
dataset](https://download.tensorflow.org/data/speech_commands_v0.01.tgz)
```

https://download.tensorflow.org/data/speech_commands_v0.01.tgz leads to a non working page.

**Comment by ayushmankumar7** [comment]
It's showing that the particular page is "unsafe". Going to the advanced tab, we can download the dataset.

**Comment by ymodak** [comment]
Closing this issue since the associated PR has merged and dataset download link is fixed. Thanks!
