### ISSUE TITLE
Get a confused error when using tf.keras.layers.Conv2D to create Gan model

### ISSUE THREAD

**Issue by Panshangka** [tensorflow/tensorflow#34474]
Hello, I tried to convert my tensorflow 1.x code to tensorflow 2.0, but met with some problems here:

the original 1.x code is:
def generator(inputs_real, is_train=True, alpha=0.01, name="generator"):
    # 256*256*3
    with tf.variable_scope(name, reuse=(not is_train)):
        # 128*128*64
        conv1 = tf.layers.conv2d(inputs_real, 64, (3,3), padding='same')
        conv1 = tf.nn.relu(conv1)
        conv1 = tf.layers.max_pooling2d(conv1, (2,2), (2,2), padding='same')
        # 64*64*128
        conv2 = tf.layers.conv2d(conv1, 128, (3,3), padding='same')
        conv2 = tf.layers.conv2d(conv1, 128, (3,3), padding='same')
        conv2 = tf.nn.relu(conv2)
        conv2 = tf.layers.max_pooling2d(conv2, (2,2), (2,2), padding='same')
        # 32*32*256
        conv3 = tf.layers.conv2d(conv2, 256, (3,3), padding='same')
        conv3 = tf.layers.conv2d(conv2, 256, (3,3), padding='same')
        conv3 = tf.nn.relu(conv3)
        conv3 = tf.layers.max_pooling2d(conv3, (2,2), (2,2), padding='same')
        # 16*16*512
        conv4 = tf.layers.conv2d(conv3, 512, (3,3), padding='same')
        conv4 = tf.layers.conv2d(conv3, 512, (3,3), padding='same')
        conv4 = tf.nn.relu(conv4)
        conv4 = tf.layers.max_pooling2d(conv4, (2,2), (2,2), padding='same')
        # 8*8*512
        conv5 = tf.layers.conv2d(conv4, 512, (3,3), padding='same')
        conv5 = tf.layers.conv2d(conv4, 512, (3,3), padding='same')
        conv5 = tf.nn.relu(conv5)
        conv5 = tf.layers.max_pooling2d(conv5, (2,2), (2,2), padding='same')
        # 4*4*512
        conv6 = tf.layers.conv2d(conv5, 512, (3,3), padding='same')
        conv6 = tf.layers.conv2d(conv5, 512, (3,3), padding='same')
        conv6 = tf.nn.relu(conv6)
        conv6 = tf.layers.max_pooling2d(conv6, (2,2), (2,2), padding='same')

everything worked fine, but when I try to convert to:

class Generator(tf.keras.Model):
  def __init__(self, is_train):
    super(Generator, self).__init__()
    self.is_train = is_train
    self.conv64 = tf.keras.layers.Conv2D(64, (3, 3), input_shape=(256, 256, 3), data_format='channels_last', padding='same')
    self.conv128 = tf.keras.layers.Conv2D(128, (3, 3), data_format='channels_last', padding='same')
    self.conv256 = tf.keras.layers.Conv2D(256, (3, 3), data_format='channels_last', padding='same')
    self.conv512 = tf.keras.layers.Conv2D(512, (3, 3), data_format='channels_last', padding='same')
    self.conv_transpose1 = tf.keras.layers.Conv2DTranspose(1, (3, 3), strides=(2, 2), data_format='channels_last', padding='same')
    self.conv_transpose64 = tf.keras.layers.Conv2DTranspose(64, (3, 3), strides=(2, 2), data_format='channels_last', padding='same')
    self.conv_transpose128 = tf.keras.layers.Conv2DTranspose(128, (3, 3), strides=(2, 2), data_format='channels_last', padding='same')
    self.conv_transpose256 = tf.keras.layers.Conv2DTranspose(256, (3, 3), strides=(2, 2), data_format='channels_last', padding='same')
    self.conv_transpose512 = tf.keras.layers.Conv2DTranspose(512, (3, 3), strides=(2, 2), data_format='channels_last', padding='same')
    self.MaxPool2D = tf.keras.layers.MaxPool2D((2,2), (2,2), padding='same')
    self.BatchNormalization = tf.keras.layers.BatchNormalization(trainable=is_train)

  def call(self, inputs_real):
    conv1 = self.conv64(inputs_real)
    conv1 = layers.ReLU()(conv1)
    conv1 = self.MaxPool2D(conv1)

    # 64*64*128
    conv2 = self.conv128(conv1)
    conv2 = layers.ReLU()(conv2)
    conv2 = self.MaxPool2D(conv2)

    # 32*32*256
    conv3 = self.conv256(conv2)
    conv3 = layers.ReLU()(conv3)
    conv3 = self.MaxPool2D(conv3)
    print(conv3.shape)

    # 16*16*512
    conv4 = self.conv512(conv3)
    conv4 = layers.ReLU()(conv4)
    conv4 = self.MaxPool2D(conv4)
    print(conv4.shape)

    # 8*8*512
    conv5 = self.conv512(conv4)
    conv5 = layers.ReLU()(conv5)
    conv5 = self.MaxPool2D(conv5)
        
    # 4*4*512
    conv6 = self.conv512(conv5)
    conv6 = layers.ReLU()(conv6)
    conv6 = self.MaxPool2D(conv6)

The error is:
Traceback (most recent call last):
  File "gan_2.0.py", line 269, in <module>
    train()
  File "gan_2.0.py", line 266, in train
    loss_dict = train_step(image_batch, cartoon_batch)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow_core\python\eager\def_function.py", line 457, in __call__
    result = self._call(*args, **kwds)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow_core\python\eager\def_function.py", line 503, in _call
    self._initialize(args, kwds, add_initializers_to=initializer_map)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow_core\python\eager\def_function.py", line 408, in _initialize
    *args, **kwds))
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow_core\python\eager\function.py", line 1848, in _get_concrete_function_internal_garbage_collected
    graph_function, _, _ = self._maybe_define_function(args, kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow_core\python\eager\function.py", line 2150, in _maybe_define_function
    graph_function = self._create_graph_function(args, kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow_core\python\eager\function.py", line 2041, in _create_graph_function
    capture_by_value=self._capture_by_value),
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow_core\python\framework\func_graph.py", line 915, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow_core\python\eager\def_function.py", line 358, in wrapped_fn
    return weak_wrapped_fn().__wrapped__(*args, **kwds)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow_core\python\framework\func_graph.py", line 905, in wrapper
    raise e.ag_error_metadata.to_exception(e)
ValueError: in converted code:

    gan_2.0.py:228 train_step  *
        fake_cartoons = generatorc(image_batch)
    C:\ProgramData\Anaconda3\lib\site-packages\tensorflow_core\python\keras\engine\base_layer.py:847 __call__
        outputs = call_fn(cast_inputs, *args, **kwargs)
    gan_2.0.py:59 call  *
        conv6 = self.conv512(conv5)
    C:\ProgramData\Anaconda3\lib\site-packages\tensorflow_core\python\keras\engine\base_layer.py:812 __call__
        self.name)
    C:\ProgramData\Anaconda3\lib\site-packages\tensorflow_core\python\keras\engine\input_spec.py:213 assert_input_compatibility
        ' but received input with shape ' + str(shape))

    ValueError: Input 0 of layer conv2d_3 is incompatible with the layer: expected axis -1 of input shape to have value 256 but received input with shape [1, 8, 8, 512]

It seems that conv5 = self.conv512(conv4) only takes the input of shape[, , , 256], but after conv4 = self.conv512(conv3), the last shape is 512 after the con2d's kernel size is 512.  Which means the kernel size should be different between stacked layers?
I'm really confused here...

**Comment by ravikyram** [comment]
@Panshangka 

Can you please share the code with proper indentation or colab link, so it will be easy to reproduce the issue in our environment. It helps us in localizing the issue faster. Thanks!

**Comment by Panshangka** [comment]
> @Panshangka
> 
> Can you please share the code with proper indentation or colab link, so it will be easy to reproduce the issue in our environment. It helps us in localizing the issue faster. Thanks!

Thanks for your reply, This is my colab link:https://colab.research.google.com/drive/1i3gB11KmRjLWESslUaUMWSD6ldJ5SamU

**Comment by WindQAQ** [comment]
> It seems that conv5 = self.conv512(conv4) only takes the input of shape[, , , 256], but after conv4 = self.conv512(conv3), the last shape is 512 after the con2d's kernel size is 512. Which means the kernel size should be different between stacked layers?
I'm really confused here...

TF - Keras defaults to channel last representation. So the problem here is:

`self.conv512` is first build with input channels 256 when calling `conv4 = self.conv512(conv3)`. However, when calling `conv5 = self.conv512(conv4)`, the input channels become 512.

```python
conv3 = self.conv256(conv2)
conv3 = layers.ReLU()(conv3)
conv3 = self.MaxPool2D(conv3)
print(conv3.shape) # here the output channels is 256

conv4 = self.conv512(conv3) # so the input channels here is 256
conv4 = layers.ReLU()(conv4)
conv4 = self.MaxPool2D(conv4)
print(conv4.shape) # here the output channels is 512

# 8*8*512
# errors occurred because the `self.conv512` is built with input channels 256 but received 512 instead.
conv5 = self.conv512(conv4) 
conv5 = layers.ReLU()(conv5)
conv5 = self.MaxPool2D(conv5)
```

**Comment by Panshangka** [comment]
> ```python
> conv512
> ```

Thanks! But how do I exactly make this the same as tf.layers? I searched the documentation but got no clue. Maybe I should use another API in tf 2.0 cause I can't change the model structure that I am going to build

**Comment by WindQAQ** [comment]
> > ```python
> > conv512
> > ```
> 
> Thanks! But how do I exactly make this the same as tf.layers? I searched the documentation but got no clue. Maybe I should use another API in tf 2.0 cause I can't change the model structure that I am going to build

Could you say more about the implementation of `tf.layers` so that I could help you? Maybe give a link of reference codes in `tf.layers`. Thanks!

**Comment by Panshangka** [comment]
> > > ```python
> > > conv512
> > > ```
> > 
> > 
> > Thanks! But how do I exactly make this the same as tf.layers? I searched the documentation but got no clue. Maybe I should use another API in tf 2.0 cause I can't change the model structure that I am going to build
> 
> Could you say more about the implementation of `tf.layers` so that I could help you? Maybe give a link of reference codes in `tf.layers`. Thanks!

The same notebook, I have pasted the implementation of tf.layers in the second cell. It seems that tf.layers.conv2d does not defaults to channel last representation as tf.keras.layers.con2d do
https://colab.research.google.com/drive/1i3gB11KmRjLWESslUaUMWSD6ldJ5SamU

**Comment by WindQAQ** [comment]
> The same notebook, I have pasted the implementation of tf.layers in the second cell. It seems that tf.layers.conv2d does not defaults to channel last representation as tf.keras.layers.con2d do
> https://colab.research.google.com/drive/1i3gB11KmRjLWESslUaUMWSD6ldJ5SamU

It does actually. Each time you call `tf.layers.conv2d`, it will generate a convolution kernel/weight. For example, in your generator, it generates 14 kernels/weights (each of them might have different shape depending on input and parameters). However, your `tf.keras.layers.*` implementation only builds 4 convolution layers. You could check this by printing number of parameters in each implementation. There will be a large difference between them. To fix this, you have to instantiate 14 convolution layers in `__init__`, and call it carefully in `call` .

**Comment by WindQAQ** [comment]
FYI, https://github.com/tensorflow/tensorflow/blob/r2.0/tensorflow/python/layers/convolutional.py#L317-L424

You could see a new layer will be created (if `reuse` is False) and applied on inputs.

**Comment by Panshangka** [comment]
> FYI, https://github.com/tensorflow/tensorflow/blob/r2.0/tensorflow/python/layers/convolutional.py#L317-L424
> 
> You could see a new layer will be created (if `reuse` is False) and applied on inputs.

谢谢，I should read more about the source code

**Comment by WindQAQ** [comment]
No worries! It's a hard transition from 1.x to 2.0. Please let me know if you have further questions. Thank you :-)

**Comment by Panshangka** [comment]
> No worries! It's a hard transition from 1.x to 2.0. Please let me know if you have further questions. Thank you :-)

Hello again! I successfully print out the loss during training, but when I save the model to find out the size of model only 20KB. Something went wrong, and I visualized the structure looks weird.
here is my colab link:https://colab.research.google.com/drive/1i3gB11KmRjLWESslUaUMWSD6ldJ5SamU
Thanks!

**Comment by WindQAQ** [comment]
It's because you *instantiate the layer in `call` and do not set it as attribute* (like `self.conv = xxxx`), the weights won't be trackable for either `Generator` or `Discriminator`.

IMO, the following pattern would be better for you:
https://colab.research.google.com/drive/1U2Sy5A3ciwPqVeSV9zFDcxoiA3kDnMCl

Also, note that some layers such as batch normalization or dropout have different behavior in training and testing phase, so you *must* pass `training` when calling the layer to differentiate different phase.
https://www.tensorflow.org/api_docs/python/tf/keras/layers/BatchNormalization
https://www.tensorflow.org/api_docs/python/tf/keras/layers/Dropout

**Comment by Panshangka** [comment]
> It's because you _instantiate the layer in `call` and do not set it as attribute_ (like `self.conv = xxxx`), the weights won't be trackable for either `Generator` or `Discriminator`.
> 
> IMO, the following pattern would be better for you:
> https://colab.research.google.com/drive/1U2Sy5A3ciwPqVeSV9zFDcxoiA3kDnMCl
> 
> Also, note that some layers such as batch normalization or dropout have different behavior in training and testing phase, so you _must_ pass `training` when calling the layer to differentiate different phase.
> https://www.tensorflow.org/api_docs/python/tf/keras/layers/BatchNormalization
> https://www.tensorflow.org/api_docs/python/tf/keras/layers/Dropout

Thank you so much! my problem has been solved!  Now the model file is 386MB
