### ISSUE TITLE
Error with Placeholder_1

### ISSUE THREAD

**Issue by Pauladds** [tensorflow/tensorflow#34482]
I tried to run el script https://github.com/tensorflow/magenta-demos/blob/master/jupyter-notebooks/Sketch_RNN.ipynb but with diferente dataset (pig.npz) and with the checkpoints of that and i have the next problem : 
![download](https://user-images.githubusercontent.com/38189240/69332857-d8f75f80-0c57-11ea-813c-22fe4db6b636.png)
Thnak you :)

**Comment by oanush** [comment]
@Pauladds ,
Hi, I see that TF version-1.8.0 is being used, please try using the latest version 1.15 and let us know the results. Also please provide a minimal standard code to reproduce the issue reported here if it exists in latest version. Thanks!

**Comment by Pauladds** [comment]
Hi, I have TF 1.15 and my program still doesn't work. Here is the code, i am running "blob_sketch_RNN-bread" but i don't know my problem... 
my version of TF is:
(magenta) paula@oceanus:~$ pip show tensorflow-gpu
Name: tensorflow-gpu
Version: 1.15.0
Summary: TensorFlow is an open source machine learning framework for everyone.
Home-page: https://www.tensorflow.org/
Author: Google Inc.
Author-email: packages@tensorflow.org
License: Apache 2.0
Location: /home/paula/miniconda3/envs/magenta/lib/python3.7/site-packages
Requires: tensorflow-estimator, tensorboard, keras-preprocessing, google-pasta, numpy, termcolor, wrapt, gast, keras-applications, absl-py, protobuf, grpcio, astor, opt-einsum, wheel, six

Thank you in advance :)

**Comment by oanush** [comment]
@Pauladds ,
Hi, link provided https://github.com/Pauladds/Rnn_sketch doesnt seem to work, can you provide the working link?Thanks!

**Comment by oanush** [comment]
@Pauladds ,
any update on the issue ?Thanks!

**Comment by Pauladds** [comment]
Sorry! I found the problem and I solve it!
Thank you :)
