### ISSUE TITLE
how to build tensorflow lite static library for android use ndk?

### ISSUE THREAD

**Issue by mlinxiang** [tensorflow/tensorflow#34489]
i check all issue about build static library with ndk for android c++ code, but no one give a complete guide.  and different version from r1.12 r.113 r1.15 has very different tensorflow/lite/tools/make   build_**.sh and target/**.inc, any guide for me to use cmake or bazel to build a libtensorflow-lite.a with armv-8a and armv7a on mac or linux machine.

**Comment by jianlijianli** [comment]
Hi mlinxiang, thanks for using tensorflow lite.

For your use case, could you please try to follow https://www.tensorflow.org/lite/guide/android (and https://github.com/tensorflow/examples/blob/master/lite/examples/image_classification/android/README.md)? That should create a standard image classification model.

Thanks.

**Comment by mlinxiang** [comment]
@jianlijianli i want to build a libtensorflow-lite.a to compile my c++ code which will be used by android through jni.  i find one way to do this, but need a lot change about Makefile and target/***.inc, and a lot env settings.  i think maybe this could be more official guide for new people. later i can share my steps to do so

**Comment by jdduke** [comment]
Is there a reason you need a static library, rather than a shared library? We're close to enabling C API usage from the nightly AAR builds, which you can integrate into your JNI gradle project.

**Comment by mlinxiang** [comment]
@jdduke my project pipeline is  android app --> jni --> c++ sdk,  the c++ sdk code and  jni compile together as a so<build by cmake+ndk not in android studio>, which can be used by any android project, and the c++ sdk code also can compile to a ".a" static library used by ios.  so all the thirdparty librarys are use static library link. 

i build the static library by modify makefile and target inc use ndk toolchain and generate static library.  but i still have some problem with how to enable gpu support.

**Comment by linyongye** [comment]
@mlinxiang Hi, I also want to build tensorflow lite static library, but fail, can you share your steps how to build tendorflow lite ".a" static library ?

**Comment by yavol** [comment]
The problem with .so library is that is has lots of symbols which are not needed. Specifically tensorflow lite if compiled as .so library is ~50MB in size vs //tensorflow/lite/java:libtensorflowlite_jni.so which is ~1MB. I would guess *_jni.so library is so much smaller due to stripping of unused sections and symbol info. Distributing an app with 50MB lib is impractical.

**Comment by jdduke** [comment]
Hi @yavol , which platform are you targeting? We do strip symbols for Linux/Mac when you build `//tensorflow/lite:libtensorflowlite.so` and `//tensorflow/lite/c:libtensoflowlite_c.so` via bazel. The shared libraries for those should be ~1-2MB when you build with `-c opt`.

**Comment by mlinxiang** [comment]
@linyongye sorry for late response, please use this link to download the scripts : https://pan.baidu.com/s/12Y1ftf2BjIWw1d-WyjaZOQ  access code: km9h 
contain build_armv7a_lib.sh build_armv8a_lib.sh, and Makefile.andriod,  please set env parameter ANDROID_NDK , the min version is ndk18,  and some tensorflow root WORKSPACE add follow config:
android_sdk_repository(
148    name = "androidsdk",
149    api_level = 26,
150    build_tools_version = "26.0.2",
151    path = "/Users/***/Library/Android/sdk",
152 )
153
154 android_ndk_repository(
155    name="androidndk",
157    path="/Users/****/Library/Android/sdk/ndk/20.0.5594570",
159    api_level=24
160 )

 tensorflow 1.15   tensorflow/lite/delegates/gpu/gl/kernels/test_util.h  need to delete
-#include <gmock/gmock.h>
-#include <gtest/gtest.h>

compile need some runtime generate head file, please first use bazel to compile so, then copy to source file dir:  bazel build --cxxopt=--std=c++11 -c opt --config android_arm64 tensorflow/lite/delegates/gpu:gl_delegate
the include file need to scan the tensorflow/lite source dir get all *.h file, and the download flatbuffer has it's prebuilded include, copy this to flatbuff root dir

**Comment by knightfork** [comment]
@mlinxiang , the link you shared is not working. Is there any other way you can share it please?

When I try to build static lib with bazel, it fails building flatbuffers.

Thanks!

**Comment by mlinxiang** [comment]
@knightfork google drive link: https://drive.google.com/open?id=1lBhZ4HbcQ0XAwVC2lyiTMdKo1UT2S9fw

**Comment by orangesomethingorange** [comment]
> Is there a reason you need a static library, rather than a shared library? We're close to enabling C API usage from the nightly AAR builds, which you can integrate into your JNI gradle project.

I'd like to use C++ API from the nightly AAR builds, and integrate that into my JNI project.
I've been trying to do that for the past week unsuccessfully... Can you please elaborate on what I need to do to use it?

**Comment by knightfork** [comment]
@mlinxiang , thanks a lot!

**Comment by sunfrank1987** [comment]
@mlinxiang hi build tensorflow lite static lib for android base ndk  standalone toolchain base on tensorflow2.3

https://github.com/sunfrank1987/build_tensorflow_lite

**Comment by jdduke** [comment]
Note that we've committed an experimental version of CMake support @ https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/tools/cmake. This should make it easier to generate the static library, when necessary, or to integrate directly into your CMake-based project/toolchain.

**Comment by LxzBUG** [comment]
@jdduke https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/tools/cmake, I have generated static files,but when I integrate them into cmakelist,all  undefined reference to `TfLiteModelCreate'   undefined reference to  undefined reference to

**Comment by steven-johnson** [comment]
> Note that we've committed an experimental version of CMake support @ https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/tools/cmake. This should make it easier to generate the static library, when necessary, or to integrate directly into your CMake-based project/toolchain.

Well, yes and no: this works fine as long as you are using it directly from another CMake build; if you just want to build a one-off static library to use in a different build system (Make, in my case), you still have to track down and build all the transitive dependencies, which are missing. 

Amusingly, the Make-produced static library for e.g. Linux doesn't have this issue and works fine, but the stuff in tools/make seems to support every sort of mobile arm platform *except* for Android.

(Does Bazel even support the ability to produce standalone static libraries? Last time I checked, it didn't, so I haven't checked for TFLite...)

**Comment by jdduke** [comment]
> Does Bazel even support the ability to produce standalone static libraries? Last time I checked, it didn't, so I haven't checked for TFLite...

Sadly, no, at least not that I'm aware of. There are some ways to traverse the transitive cc_library deps w/ Bazel, and manually generate a static library. We've considered adding a helper rule for doing so, but it's somewhat brittle.

**Comment by steven-johnson** [comment]
FWIW, the [instructions](https://www.tensorflow.org/lite/guide/android) for using Bazel to build a **dynamic** library for Android don't work either...

```
$ bazel build -c opt --config=android_arm64 //tensorflow/lite:libtensorflowlite.so
...stuff...
ERROR: /private/var/tmp/_bazel_srj/5404487c5e532e1d3fa71c94c3e65bf0/external/local_config_cc/BUILD:41:1: in cc_toolchain_suite rule @local_config_cc//:toolchain: cc_toolchain_suite '@local_config_cc//:toolchain' does not contain a toolchain for cpu 'arm64-v8a'
ERROR: Analysis of target '//tensorflow/lite:libtensorflowlite.so' failed; build aborted: Analysis of target '@local_config_cc//:toolchain' failed
```

**Comment by milinddeore** [comment]
@steven-johnson to cross compile tensorflow lite for a specific `ARCH` and platform type, you need to set `WORKSPACE`. 

This can be done using `./configure` under tensorflow repo, as mentioned [here](https://www.tensorflow.org/lite/guide/build_android#configure_workspace_and_bazelrc) 

Now run following build command: 
```
bazel build -c opt --config=android_arm64 //tensorflow/lite:libtensorflowlite.so
```

For me its creates the shared object but when i run it on Android phone, i get following error: 

```
2020-12-26 11:36:14.960 7288-7288/com.example.ndkcamlibs E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.ndkcamlibs, PID: 7288
    java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "_ZN6tflite4impl18InterpreterBuilderclEPNSt6__ndk110unique_ptrINS0_11InterpreterENS2_14default_deleteIS4_EEEE" referenced by "/data/app/com.example.ndkcamlibs-XB6q0orTTyV629Xo1BR27w==/base.apk!/lib/arm64-v8a/libndksamplecam.so"...
        at java.lang.Runtime.loadLibrary0(Runtime.java:1016)
        at java.lang.System.loadLibrary(System.java:1657)
        at com.example.ndkcamlibs.MainActivity.<clinit>(MainActivity.java:293)
        at java.lang.Class.newInstance(Native Method)
        at android.app.Instrumentation.newActivity(Instrumentation.java:1190)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2837)
```

I have copied `libndksamplecam.so` and `libtensorflowlite.so` to `jniLibs` folder in Android studio.

**Comment by steven-johnson** [comment]
@milinddeore I gave up on building that target at all, and settled on using the C-API-only variant (`//tensorflow/lite/c:tensorflowlite_c`), which builds reliably under Bazel.

**Comment by milinddeore** [comment]
@steven-johnson But just in case you would like to its super easy, i made mistake when i copied header file, i mistakenly copied `.cc` file too. I have done a edit to my previous comment. (_Just in case you would like to try._)

**Comment by ar-visions** [comment]
I've been trying to build static.  There are numerous problems so far mostly with its inability to deselect alot of Ruy library code which becomes a dependency even when you compile without it:

The following is from https://github.com/tensorflow/tensorflow/issues/52373

cmake ../tensorflow/lite -DTFLITE_ENABLE_RUY=OFF -DTFLITE_ENABLE_NNAPI=OFF -DTFLITE_ENABLE_GPU=OFF -DTFLITE_ENABLE_XNNPACK=OFF -DTFLITE_ENABLE_MMAP=OFF
make

It proceeds to compile RUY code anyway, and it produces a .a file but it has these dependencies which shouldn't be there.
