### ISSUE TITLE
Tensorflow 2.0 does not use GPU, while Tensorflow 1.15 does

### ISSUE THREAD

**Issue by dmus** [tensorflow/tensorflow#34485]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
No

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
Linux Ubuntu 18.04

- TensorFlow installed from (source or binary):
binary (pip install tensorflow==2.0 vs pip install tensorflow==1.15

- TensorFlow version (use command below):
2.0 and 1.15

- Python version:
Python 3.6.5

- CUDA/cuDNN version:
== cuda libs  ===================================================
/usr/local/cuda-10.1/targets/x86_64-linux/lib/libcudart.so.10.1.243
/usr/local/cuda-10.1/targets/x86_64-linux/lib/libcudart_static.a
/usr/local/cuda-10.0/doc/man/man7/libcudart.so.7
/usr/local/cuda-10.0/doc/man/man7/libcudart.7
/usr/local/cuda-10.0/targets/x86_64-linux/lib/libcudart_static.a
/usr/local/cuda-10.0/targets/x86_64-linux/lib/libcudart.so.10.0.130

- GPU model and memory:
Nvidia Quadro T2000

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
import tensorflow as tf
tf.test.is_gpu_available()
this gives False for Tensorflow 2.0 and True for Tensorflow 1.15

**Describe the expected behavior**
It should be True for both

**Code to reproduce the issue**
import tensorflow as tf
tf.test.is_gpu_available()

**Other info / logs**

== env ==========================================================
LD_LIBRARY_PATH is unset
DYLD_LIBRARY_PATH is unset

== nvidia-smi ===================================================
Thu Nov 21 14:40:53 2019       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 430.26       Driver Version: 430.26       CUDA Version: 10.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Quadro T2000        Off  | 00000000:01:00.0 Off |                  N/A |
| N/A   55C    P8     1W /  N/A |    654MiB /  3914MiB |      5%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0      2059      G   /usr/lib/xorg/Xorg                           331MiB |
|    0      2237      G   /usr/bin/gnome-shell                         146MiB |
|    0      2606      G   ...quest-channel-token=3079153680037509795   172MiB |
|    0      4718      G   /snap/pycharm-community/167/jbr/bin/java       2MiB |
+-----------------------------------------------------------------------------+

== cuda libs  ===================================================
/usr/local/cuda-10.1/targets/x86_64-linux/lib/libcudart.so.10.1.243
/usr/local/cuda-10.1/targets/x86_64-linux/lib/libcudart_static.a
/usr/local/cuda-10.0/doc/man/man7/libcudart.so.7
/usr/local/cuda-10.0/doc/man/man7/libcudart.7
/usr/local/cuda-10.0/targets/x86_64-linux/lib/libcudart_static.a
/usr/local/cuda-10.0/targets/x86_64-linux/lib/libcudart.so.10.0.130

== tensorflow installed from info ==================
Name: tensorflow
Version: 2.0.0
Summary: TensorFlow is an open source machine learning framework for everyone.
Home-page: https://www.tensorflow.org/
Author-email: packages@tensorflow.org
License: Apache 2.0
Location: /home/derk/playground/venv/lib/python3.6/site-packages
Required-by: 

== python version  ==============================================
(major, minor, micro, releaselevel, serial)
(3, 6, 5, 'final', 0)

== bazel version  ===============================================

**Comment by wdirons** [comment]
In TensorFlow 2.0, if you want to use GPU, you need to `pip install tensorflow-gpu==2.0`

Some history:
For a long time the `tensorflow` pip package was CPU only and the `tensorflow-gpu` pip package was GPU only. This was still true when TensorFlow 2.0 was released.

TensorFlow 1.15.0 was released after TensorFlow 2.0, and that was the first package where the `tensorflow` pip package could work with either GPU or CPU.

TensorFlow 2.1.0, when released, should work the same as TensorFlow 1.15.0 does, but for now to use GPU with TensorFlow 2.0, you need to install `tensorflow-gpu`

**Comment by gadagashwini** [comment]
@dmus, 
In Tensorflow 1.15.0, pip package will by default include GPU support (same as tensorflow-gpu now) for the platforms we currently have GPU support (Linux and Windows).
In Tenosrflow 2.0, for GPU support use `pip install tensorflow-gpu==2.0.0.`
For information Please refer the [release notes](https://github.com/tensorflow/tensorflow/releases). Thanks!

**Comment by gadagashwini** [comment]
@dmus, Is this still an issue. Thanks!

**Comment by gadagashwini** [comment]
Closing since its resolved. Please feel free to open if issue still persists. Thanks!

**Comment by mrrqzhang** [comment]
tensorflow 1.12 ok for gpu.
>>> print( tf.__version__)
1.12.0
>>> tf.test.is_gpu_available()
True

**Comment by ThinhNgVhust** [comment]
> In TensorFlow 2.0, if you want to use GPU, you need to `pip install tensorflow-gpu==2.0`
> 
> Some history:
> For a long time the `tensorflow` pip package was CPU only and the `tensorflow-gpu` pip package was GPU only. This was still true when TensorFlow 2.0 was released.
> 
> TensorFlow 1.15.0 was released after TensorFlow 2.0, and that was the first package where the `tensorflow` pip package could work with either GPU or CPU.
> 
> TensorFlow 2.1.0, when released, should work the same as TensorFlow 1.15.0 does, but for now to use GPU with TensorFlow 2.0, you need to install `tensorflow-gpu`

build from source show wrong compatible type=> https://www.tensorflow.org/install/source#gpu . change **pip install tensorflow==2.0** to pip **install tensorflow-gpu==2.0.0.**
