### ISSUE TITLE
Summaries producing warnings

### ISSUE THREAD

**Issue by plooney** [tensorflow/tensorflow#34481]
The example code states 

```
writer = tf.summary.create_file_writer("/tmp/mylogs/tf_function")

@tf.function
def my_func(step):
  with writer.as_default():
    # other model code would go here
    tf.summary.scalar("my_metric", 0.5, step=step)

for step in range(100):
  my_func(step)
  writer.flush()
```

But on multiple systems and operating systems I am seeing warnings using code like this of the form 

> 
WARNING:tensorflow:5 out of the last 5 calls to <function my_func at 0x7fc4f0197ae8> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings is likely due to passing python objects instead of tensors. Also, tf.function has experimental_relax_shapes=True option that relaxes argument shapes that can avoid unnecessary retracing. Please refer to https://www.tensorflow.org/beta/tutorials/eager/tf_function#python_or_tensor_args and https://www.tensorflow.org/api_docs/python/tf/function for more details.

**Comment by plooney** [comment]
The example should be 

`for step in range(100):
    step = tf.convert_to_tensor(step, dtype=tf.int64)
    my_func(step)
    writer.flush()` 

or 

`for step in tf.range(100):
    step = tf.cast(step, tf.int64)
    my_func(step)
    writer.flush()`

**Comment by gadagashwini** [comment]
Could reproduce the issue with TF 2.0.
Please see the gist [here](https://colab.sandbox.google.com/gist/gadagashwini/74b3582f02348373e348f075afbf4edd/untitled266.ipynb). Thanks!

**Comment by nfelt** [comment]
Thanks for pointing this out, we'll fix it.  @plooney Just to confirm, is the example code you're referring to the code shown in https://www.tensorflow.org/tensorboard/migrate?

**Comment by plooney** [comment]
That is correct

**Comment by amahendrakar** [comment]
Was able to reproduce the issue with TF v2.2 and TF-nightly (i.e. v2.3.0-dev20200623). Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/7f288214bf0c5a7575ad5313805e0124/34481.ipynb#scrollTo=ZG-bSPiwcmEa). Thanks!

**Comment by jvishnuvardhan** [comment]
@plooney Thanks for raising this issue. This was updated in the TF website as shown below and it works without any error.

```
for step in tf.range(100, dtype=tf.int64):
  my_func(step)
  writer.flush()
```

I am closing this issue as this was already resolved in the current [migration guide](https://www.tensorflow.org/tensorboard/migrate). Please feel free to reopen if I am mistaken. Thanks!
