### ISSUE TITLE
ListWrapper does not support insert method for nested lists of layers

### ISSUE THREAD

**Issue by fjean** [tensorflow/tensorflow#34488]
**System information**
- Have I written custom code: **yes**
- OS Platform and Distribution: **Linux Ubuntu 18.04**
- Mobile device: **N/A**
- TensorFlow installed from: **binary**
- TensorFlow version: **2.0.0**
- Python version: **3.7.5**
- Bazel version: **N/A**
- GCC/Compiler version: **N/A**
- CUDA/cuDNN version: **10.1 / 7.6.4**
- GPU model and memory: **GeForce GTX 1070, 8 GB**

**Describe the current behavior**
List of layers added to another `list` with the `insert` method are ignored by the model; it works fine with the `append` method.

This seems to be a problem with ListWrapper.

**Describe the expected behavior**
All `list` methods should be supported for defining nested list of layers.

**Code to reproduce the issue**

Minimal example:

```python
class MyModel(tf.keras.Model): 
    def __init__(self, **kwargs): 
        super().__init__(**kwargs) 
        self.conv1 = [] 
        self.conv1.append([tf.keras.layers.Conv2D(8, 3, name="conv1")]) 
        self.conv2 = [] 
        self.conv2.insert(0, [tf.keras.layers.Conv2D(16, 3, name="conv2")]) 

    def call(self, inputs): 
        x = inputs 
        x = self.conv1[0][0](x) 
        x = self.conv2[0][0](x) 
        return x


m = MyModel()
m.build((None, None, None, 3))
m.summary()

for w in m.trainable_weights: 
    print(w.name)
```
output is:
```
Model: "my_model"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
=================================================================
conv1 (Conv2D)               multiple                  224       
=================================================================
Total params: 224
Trainable params: 224
Non-trainable params: 0
_________________________________________________________________

conv1/kernel:0
conv1/bias:0
```
Note that `conv2` has been ignored.

**Other info / logs**

N/A

**Comment by ravikyram** [comment]
I have tried on colab with TF version 2.0 ,2.1.0-dev20191124 and was able to reproduce the issue.Please, find the gist [here](https://colab.sandbox.google.com/gist/ravikyram/6a4e1d47c491f31d5f0ff5c817ab8263/untitled407.ipynb). Thanks!

**Comment by qlzh727** [comment]
Assigning to Allen who is the owner of ListWrapper.

**Comment by allenlavoie** [comment]
Checkpointing doesn't support insert, so it'll throw an exception on save. The Layer is added to the list, though. Keras probably still wants to collect layers through lists in this case. Hopefully someone who works on Keras can iron out that policy. Scott, can you find an owner?

**Comment by sushreebarsa** [comment]
Was able to replicate the issue in TF 2.6.0-dev20210529,please find the gist [here](https://colab.research.google.com/gist/sushreebarsa/fd7e0cd798fc9e635285b0f8d45395c0/untitled85.ipynb)..Thanks !

**Comment by tensorflowbutler** [comment]
Hi There,

 This is a stale issue. As you are using an older version of tensorflow, we are checking to see if you still need help on this issue. Please test the issue with the latest TensorFlow (TF2.7 and tf-nightly). If the issue still persists with the newer versions of TF, please feel free to open it in [keras-team/keras](https://github.com/keras-team/keras/issues) repository by providing details about the issue and a standalone code to reproduce the issue. Thanks! 

 Please note that Keras development has moved to a separate Keras-team/keras repository to focus entirely on only Keras. Thanks!
