### ISSUE TITLE
Tensorflow 1.6 without SSE4.1

### ISSUE THREAD

**Issue by josephernest** [tensorflow/tensorflow#34490]
Hello,
It seems that Tensorflow 1.6 and later versions are configured to require SSE4.1 instructions by default. Some processors (like AMD Phenom II x4 965) do not have these instructions.

**How to configure / rebuild Tensorflow for Python 3 to run on CPUs without SSE4.1?**

**Comment by wdirons** [comment]
You'll need to build TensorFlow from source following the instructions here:

https://www.tensorflow.org/install/source

Note the table here: https://www.tensorflow.org/install/source#cpu, on what version of bazel, python and gcc to use for TensorFlow 1.6

**Comment by gowthamkpr** [comment]
@josephernest As mentioned by William above, you can try building it from source. Also I would recommend you using the latest version of Tensorflow as for the versions less than 1.11, the support is minimal. Thanks!

**Comment by josephernest** [comment]
@gowthamkpr @wdirons Thank you for your answers. Even if there is a HOWTO, this seems to be quite like a long task (installing the right `bazel` (?), the right gcc which is probably not the one I have currently installed, configure the build settings, probably a full day or two when you're new to it, etc.).

Would you have a TF 1.14 build with SSE4.1 off? I think it could be useful for many people using such processors. 

Or maybe are there some unofficial builds available somewhere for this?
(A bit similar to what Gohlke does: https://www.lfd.uci.edu/~gohlke/pythonlibs/, but for Linux 64 in my case.)

Thank you very very much if you have this!

**Comment by wdirons** [comment]
There are plans for an on-demand build service document here: https://github.com/tensorflow/community/blob/master/rfcs/20190225-tf-on-demand.md, but details like who is providing the pool of machines to build on is not worked out. 

I'm not aware of anyone providing unofficial builds without SSE4.1.

**Comment by wdirons** [comment]
I should also point out that if you use a devel docker container then all the prereqs should already be installed

```
docker pull tensorflow/tensorflow:1.11.0-devel-py3
or
docker pull tensorflow/tensorflow:1.6.0-devel-py3
```

**Comment by josephernest** [comment]
> There are plans for an on-demand build service document here: 
 
Oh this would be really great... Is there a waiting list for this service, or could my use case (TF 1.14 without SSE4.1) serve as a demo case for this service? :-)

If you had a little spare time on a machine to run such a build in background, I would be really interested @wdirons if we can send it via file transfer ;) (my email is on my profile)

> I should also point out that if you use a devel docker container then all the prereqs should already be installed

Would you have a list of commands in this example:

    docker pull tensorflow/tensorflow:1.14.0-devel-gpu(?)-py3
    docker run ...
    configure SSE4.1
    build
  
in order to get a .whl at the end that I can export outside of the container and use in my normal project?

Thanks in advance :)
