### ISSUE TITLE
IPython Notebook kernel dies when importing tensorflow

### ISSUE THREAD

**Issue by shekkizh** [tensorflow/tensorflow#3449]
### Environment info
Operating System: nvidia-docker (Docker version 1.11.2, build b9f10c9)
Tensorflow version 0.8.0

### Steps to reproduce
1. Run ipyhton notebook from nvidia-docker
2. import tensorflow
3. Kernel dies with Kernel Restarting dialog and message "The kernel appears to have died. It will restart automatically"
4. importing numpy package before importing tensorflow solves the issue.

**Comment by yaroslavvb** [comment]
There was a similar crash fixed in 0.9
https://github.com/tensorflow/tensorflow/pull/2173#event-646602065

**Comment by concretevitamin** [comment]
@shekkizh can you test against 0.8.0, as @yaroslavvb mentioned (thanks!)?

**Comment by shekkizh** [comment]
Closing issue since the problem is reported to be fixed in 0.9. Thanks @yaroslavvb @concretevitamin

**Comment by nabinbhusal80** [comment]
i am having same problem in my desktop even when i import numpy before importing tensorflow

**Comment by tpaixao** [comment]
same problem here, both in python2.7 and python3.5. crash happens even if imported in a normal python shell (no jupyter)
