### ISSUE TITLE
How to get sample_weights and learning_phase? (TF2 Eager)

### ISSUE THREAD

**Issue by OverLordGoldDragon** [tensorflow/tensorflow#34508]
`model.sample_weights` works w/ `from keras` imports but not `from tensorflow.keras`; I need the sample weights _tensor_  to feed to `K.function` to get layer gradients, outputs, etc.

Using `model._feed_sample_weights` instead does eliminate the error, but returns `[]`, and feeding `np.ones(32)` vs. `4*np.ones(32)` for sample weights yields the same outputs (it shouldn't).

<hr>

**Note**: see [this thread](https://github.com/tensorflow/tensorflow/issues/34507) regarding learning_phase

<hr>

**Applied example**:

```python
import tensorflow.keras.backend as K
from tensorflow.keras.layers import Input, Dense
from tensorflow.keras.models import Model
import numpy as np

ipt = Input((16,))
out = Dense(16)(ipt)
model = Model(ipt, out)
model.compile('adam', 'mse')

x = np.random.randn(32, 16)
model.train_on_batch(x, x)

grads = model.optimizer.get_gradients(model.total_loss, model.layers[-1].output)
grads_fn = K.function(inputs=[model.inputs[0], model._feed_targets[0], model.sample_weights[0]], 
                      outputs=grads)
```

**Full error trace**:

```python
File "<ipython-input-3-ef022490b960>", line 16, in <module>
  outputs=grads)
File "D:\Anaconda\envs\tf2_env\lib\site-packages\tensorflow_core\python\keras\backend.py", line 3773, in function
  return EagerExecutionFunction(inputs, outputs, updates=updates, name=name)
File "D:\Anaconda\envs\tf2_env\lib\site-packages\tensorflow_core\python\keras\backend.py", line 3670, in __init__
  base_graph=source_graph)
File "D:\Anaconda\envs\tf2_env\lib\site-packages\tensorflow_core\python\eager\lift_to_graph.py", line 249, in lift_to_graph
  visited_ops = set([x.op for x in sources])
File "D:\Anaconda\envs\tf2_env\lib\site-packages\tensorflow_core\python\eager\lift_to_graph.py", line 249, in <listcomp>
  visited_ops = set([x.op for x in sources])

AttributeError: 'NoneType' object has no attribute 'op'
```

**Comment by dubesar** [comment]
Hi @OverLordGoldDragon The above code works fine for TensorFlow 1.15
But it seems to fail for TF 2.0

The reason it is failing is the ``` python3 model.sample_weights[0] ``` is outputting None
I don't know the reason for the output None for the model.sample_weights 

Please ping me if your issue gets resolved or you find any more issue.

**Comment by ravikyram** [comment]
I have tried on colab with TF version 2.0 ,2.1.0-dev20191124 and was able to reproduce the issue.Please, find the gist [here](https://colab.sandbox.google.com/gist/ravikyram/eb1a3406aab356a8128b7ecd391fbfa5/untitled405.ipynb).However i am not seeing any issue with TF version 1.15. Thanks!

**Comment by OverLordGoldDragon** [comment]
@ravikyram Indeed, TF 1.14/1.15 works fine. 

Off-topic but interestingly, your Colab notebook doesn't show any "Owners" in "Notebook info" - how did you do it? Any share option I use includes my Colab g-mail

**Comment by OverLordGoldDragon** [comment]
fchollet assigned - hope there's a response before TF3 release

**Comment by OverLordGoldDragon** [comment]
A partly working, but unstable workaround was found in the linked SO:

```python
import tensorflow.python.keras.backend as K
learning_phase = K.symbolic_learning_phase()
```
This'll work in a simple example, but is [problematic](https://stackoverflow.com/questions/58279628/what-is-the-difference-between-tf-keras-and-tf-python-keras?noredirect=1&lq=1) in practice

**Comment by OverLordGoldDragon** [comment]
Any progress on this in TF2.2?

**Comment by goldiegadde** [comment]
@OverLordGoldDragon is this still an issue, this maybe coming very late, and you might have figured this out already  [get_gradients is only supported in v1 style graph mode](https://www.tensorflow.org/api_docs/python/tf/keras/optimizers/Optimizer?version=nightly#get_gradients). for computing gradients in Eager mode, please check this [link](https://www.tensorflow.org/guide/eager#eager_training)

**Comment by OverLordGoldDragon** [comment]
@goldiegadde [Resolved](https://stackoverflow.com/a/61952452/10133797).

**Comment by daniil-lyakhov** [comment]
@OverLordGoldDragon could you please add more details on symbolic_learning_phase issue? I want to use learning phase as a part of the model in graph mode to control layer behavior depend on lf  and can't do this due to it just an int, not a tensor
