### ISSUE TITLE
BufferedInputStream should avoid doing Reset() in Seek when new position is still in buffer. 

### ISSUE THREAD

**Issue by burgerkingeater** [tensorflow/tensorflow#34510]
Check the [code here](https://github.com/tensorflow/tensorflow/blob/597a30bc61134ee1deec0b439b3649f346f1f119/tensorflow/core/lib/io/buffered_inputstream.cc#L161) 
``` 
 // Position of the buffer within file.
  const int64 bufpos = Tell();
  if (position < bufpos) {
    // Reset input stream and skip 'position' bytes.
    TF_RETURN_IF_ERROR(Reset());
    return SkipNBytes(position);
  }
```

 I see two issues, correct me if i'm wrong:
1. Tell() doesn't return the position of the buffer within file as suggested in comment, in fact it returns the position of the `pos_` within the file.
2. when `position` is still inside buffer, it will do a `Reset` anyway, which could impact the performance for read later since it would fill buffer of the previously buffered data. 

Fixing PR: #34515

**Comment by ymodak** [comment]
Closing this issue since the associated PR is closed. Feel free to reopen if necessary. Thanks!
