### ISSUE TITLE
keras.Model does not work with keras.Input that was created with `tensor=` kwarg.

### ISSUE THREAD

**Issue by 7Z0nE** [tensorflow/tensorflow#34521]
### System information
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): **yes**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): **Linux Ubuntu 18.04 LTS**
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): **binary**
- TensorFlow version (use command below): **1.15.0-rc2**
- Python version: **3.7.4**
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

### current behavior
`keras.Input` and `keras.InputLayer` give the option to pass in a `tf.placeholder` through the argument `tensor=None`. When using the output of `keras.Input(tensor=some_placeholder)` as inputs to the functional keras.Model and subsequently calling `model.predict(batch)` on the newly created model an error occurs:

```
ValueError: ('Error when checking model input: expected no data, but got:', array([[0., 1.],
       [2., 3.],
       [4., 5.],
       [6., 7.],
       [8., 9.]]))
```

### expected behavior
No error occurs and keras.Model correctly feeds the inputs through the graph.

### Code to reproduce the issue
The following code breaks:
**snippet 1**
```
import tensorflow as tf
import tensorflow.keras as keras
import numpy as np

print("TF VERSION: ", tf.__version__)

ph = tf.placeholder(shape=[None,2], dtype=tf.float32)

# create input layer from a predefined tensorflow placeholder
inputs = keras.Input(tensor=ph)
# perform some operation
A = tf.constant([[0.5, 0],[0, 0.5]], dtype=tf.float32)
x = tf.linalg.matmul(inputs, A)
outputs = tf.reduce_sum(x, axis=1)

# make a model
model = keras.Model(inputs=inputs, outputs=outputs)

# try to feed a batch through the model
batch = np.linspace(0, 9, 10).reshape(5, 2)
out = model.predict(batch)

print(out)
```
### Explanation
I already debugged through the keras code and I think I spotted the issue:
_tesorflow/python/keras/engine/network.py, lines 342-352_
**snippet 2**
```
for i, layer in enumerate(self._input_layers):
      self.input_names.append(layer.name)
      if layer.is_placeholder:
        self._feed_input_names.append(layer.name)
        # Use batch_input_shape here because non-eager composite tensors may not
        # have a shape attribute that's meaningful (sparse, for instance, has
        # a tensor that's non-constant and needs to be fed). This means that
        # input layers that create placeholders will need to have the
        # batch_input_shape attr to allow for input shape validation.
        self._feed_input_shapes.append(layer._batch_input_shape)
        self._feed_inputs.append(layer.input)
```
snippet 2 is taken from the Network constructor. As can be seen, only tensors coming from layers with `is_placeholder` set to true are added to the `_feed_inputs` array.
In out case, this array is empty, because our `InputLayer` that was created from a `tf.placeholder` has `is_placeholder` set to false.
Looking at the constructor code of `InputLayer` we can see why this is the case:
_tensorflow/python/keras/engine/input_layer.py, lines 115 - 138_
**snippet 3**
```
    if input_tensor is None:
      if input_shape is not None:
        batch_input_shape = (batch_size,) + tuple(input_shape)
      else:
        batch_input_shape = None
      graph = backend.get_graph()
      with graph.as_default():
        input_tensor = backend.placeholder(
            shape=batch_input_shape,
            dtype=dtype,
            name=self.name,
            sparse=sparse,
            ragged=ragged)

      self.is_placeholder = True
      self._batch_input_shape = batch_input_shape
    else:
      if not tf_utils.is_symbolic_tensor(input_tensor):
        raise ValueError('You should not pass an EagerTensor to `Input`. '
                         'For example, instead of creating an '
                         'InputLayer, you should instantiate your model and '
                         'directly call it on your input.')
      self.is_placeholder = False
      self._batch_input_shape = tuple(input_tensor.shape.as_list())
```
input_tensor has the value from the `tensor=` argument. In our case, this holds the placeholder we passed to `Input(tensor=ph)`. Since it is not None `self.is_placeholder = False` is run in the else-case.
This subsequently results in the layer not being added to the _feed_inputs of the model which then does not expect any inputs to the predict method.

The issue can be worked around by manually setting the `is_placeholder` field of our input layer.
**snippet 4**
```
inputs._keras_history[0].is_placeholder = True
```
Adding this line of code just below line 10 of **snippet 1** resolves the error.
Fixed code:
**snippet 5**
```
import tensorflow as tf
import tensorflow.keras as keras
import numpy as np

print("TF VERSION: ", tf.__version__)

ph = tf.placeholder(shape=[None,2], dtype=tf.float32)

# create input layer from a predefined tensorflow placeholder
inputs = keras.Input(tensor=ph)
inputs._keras_history[0].is_placeholder=True
# perform some operation
A = tf.constant([[0.5, 0],[0, 0.5]], dtype=tf.float32)
x = tf.linalg.matmul(inputs, A)
outputs = tf.reduce_sum(x, axis=1)

# make a model
model = keras.Model(inputs=inputs, outputs=outputs)

# try to feed a batch through the model
batch = np.linspace(0, 9, 10).reshape(5, 2)
out = model.predict(batch)

print(out)
```
Output:
```
TF VERSION:  1.15.0-rc2
[0.5 2.5 4.5 6.5 8.5]
```

Since I can not think of any reason, why an InputLayer created from a placeholder should have `is_placeholder=False` I think this issue can be resolved by removing the respective line of code.

**Comment by ravikyram** [comment]
I have tried on colab with TF version 1.15 and was able to reproduce the issue.Please, find the gist [here](https://colab.sandbox.google.com/gist/ravikyram/bba32c27b2cba874adbb8d2addcb9285/untitled403.ipynb).Thanks!

**Comment by omalleyt12** [comment]
@7Z0nE Thanks for the issue!

Placeholders are removed in TF2, instead you can write the code like this:

```python
import tensorflow as tf
import tensorflow.keras as keras
import numpy as np

print("TF VERSION: ", tf.__version__)


# create input layer from a predefined tensorflow placeholder
inputs = keras.Input(shape=[2,], dtype=tf.float32)
# perform some operation
A = tf.constant([[0.5, 0],[0, 0.5]], dtype=tf.float32)
x = tf.linalg.matmul(inputs, A)
outputs = tf.reduce_sum(x, axis=1)

# make a model
model = keras.Model(inputs=inputs, outputs=outputs)

# try to feed a batch through the model
batch = np.linspace(0, 9, 10).reshape(5, 2)
out = model.predict(batch)

print(out)
```

Unfortunately we are not able to backport fixes like this to earlier version.

Please try with the latest tf-nightly `pip install -U tf-nightly`
