### ISSUE TITLE
does not contain a toolchain for cpu 'arm64-v8a' when building tensorflow lite

### ISSUE THREAD

**Issue by Yooong-W** [tensorflow/tensorflow#34520]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):Linux 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):source
- TensorFlow version:r1.15
- Bazel version (if compiling from source):0.24.1

Hi,
I'm trying to build the tensorflow lite for 'arm64-v8a' with linux on an amd64 with linux. the command i us`bazel build -c opt //tensorflow/lite:libtensorflowlite.so --cpu=arm64-v8a`, I got the following error:

`/home/wang/.cache/bazel/_bazel_wang/c72f4772665ac4cb0690414b07635968/external/local_config_cc/BUILD:45:1: in cc_toolchain_suite rule @local_config_cc//:toolchain: cc_toolchain_suite '@local_config_cc//:toolchain' does not contain a toolchain for cpu 'arm64-v8a'`
I'm new to bazel and cannot find a detailed walkthrough.what should i do?

**Comment by Yooong-W** [comment]
i changed the command `bazel build -c opt //tensorflow/lite:libtensorflowlite.so --fat_apk_cpu=arm64-v8a`,and it works well. i want know What is the difference between the --fat_apk_cpu=arm64-v8a and --cpu=arm64-v8a? and is the generated library suitable for arm64-v8a with linux?

**Comment by jdduke** [comment]
`fat_apk_cpu` is for Android builds, and is likely unsuited for building for Linux. Does `--cpu=aarch64` or `--cpu=arm64` work for you?

**Comment by Yooong-W** [comment]
hi, @jdduke
thanks for your suggest ,I've tried you mentioned，but i got the same error:

`/home/wang/.cache/bazel/_bazel_wang/c72f4772665ac4cb0690414b07635968/external/local_config_cc/BUILD:45:1: in cc_toolchain_suite rule @local_config_cc//:toolchain: cc_toolchain_suite '@local_config_cc//:toolchain' does not contain a toolchain for cpu 'aarch64'`

Does this mean I need to rewrite a `BUILD` for aarch64?

**Comment by jdduke** [comment]
What version of bazel are you using? [This thread](https://github.com/tensorflow/tensorflow/pull/16175) and [this thread](https://github.com/tensorflow/tensorflow/issues/22629) might be useful reference points.

**Comment by Yooong-W** [comment]
> What version of bazel are you using? [This thread](https://github.com/tensorflow/tensorflow/pull/16175) and [this thread](https://github.com/tensorflow/tensorflow/issues/22629) might be useful reference points.

Sorry, maybe I didn’t express it clearly, I mean cross compiling the tflite for aarch64 on the x86_64.
and my bazel version is 0.24.1

**Comment by jdduke** [comment]
Here are some [instructions that might help](https://github.com/xifengcun/tensorflow-aarch64-crossbuild). As noted in other threads, we don't (yet) officially support cross-compilation to arm64 builds on x86 linux, so efforts to do so will likely require some amount of hacking around on your part. This holds similarly for TensorFlow.

**Comment by jdduke** [comment]
All that said, if you can get this working without too much trouble, we can consider making upstream changes to make this easier. Pull requests welcome :).

**Comment by Yooong-W** [comment]
> 综上所述，如果您可以轻松完成这项工作，那么我们可以考虑进行上游更改以简化此过程。拉请求欢迎：）。

thanks very, the instructuins is helpful!

**Comment by get2abhi** [comment]
Just reconfigure Tensorflow because this step adds ANDROID NDK TOOLCHAIN in path which is used by bazel

on the top most tensorflow root just run

`./configure`

**Comment by chauvinSimon** [comment]
I could get around this issue by [configuring WORKSPACE and .bazelrc](https://www.tensorflow.org/lite/guide/build_android#configure_workspace_and_bazelrc), answering "Yes" when the script asks to interactively configure the `./WORKSPACE` for Android builds.
