### ISSUE TITLE
Saver (sharded) ignores number of checkpoints to keep

### ISSUE THREAD

**Issue by mmuneebs** [tensorflow/tensorflow#3453]
`tf.train.Saver()` has a default limit of 5 most recent checkpoints to keep (`max_to_keep=5`). When I use a Saver with `sharded=True` option, only one machine performs this check and keeps ALL the checkpoints without removing any of them.

### Environment info
Operating System: Ubuntu 14.04 LTS
Built from source; commit hash: aa2cacd6627ffb296bedc910c957a0fd4a2f957f

### Steps to reproduce
- Init a sharded saver and pass it to the Supervisor for distributed training and auto-model saving after every `save_model_secs`.
```
saver = tf.train.Saver(sharded=True)
sv = tf.train.Supervisor(is_chief=is_chief,
                                 logdir=FLAGS.train_dir,
                                 init_op=init_op,
                                 summary_op=None,
                                 global_step=global_step,
                                 saver=saver,
                                 save_model_secs=FLAGS.save_interval_secs)
```
- Start two workers and one ps on machine 0. Start two more workers and one ps on machine 1.
- The saver keeps the 5 most recent sharded checkpoints on machine 0 (where the chief worker also runs). But machine 1 keeps all sharded checkpoints from beginning.

**Comment by concretevitamin** [comment]
I can't immediately tell why, looking at the code.  Call stack: `Saver.save()` calls `_MaybeDeleteOldCheckpoints()`, which will inspect `max_to_keep`.  

Could you add some debug logging to both these methods, and relaunch on the two machines?

**Comment by mmuneebs** [comment]
Can you please guide on how to add the debug logging?

**Comment by concretevitamin** [comment]
`print("in save()")` and `print("in _MaybeDeleteOldCheckpoints()")`?  Your goal is to figure out if these two functions are actually called?

**Comment by aselle** [comment]
Automatically closing due to lack of recent activity. Please reopen if further information becomes available.
