### ISSUE TITLE
Build from head fails with Bazel 1.1.0 but succeeds with Bazel 0.26.1

### ISSUE THREAD

**Issue by dbonner** [tensorflow/tensorflow#34538]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- TensorFlow installed from (source or binary): source (building source issue)
- TensorFlow version: build from head (2.0.0)
- Python version: 3.7.3
- Installed using virtualenv? pip? conda?: Conda
- Bazel version (if compiling from source): 1.1.0 fails while 0.26.1 succeeds
- GCC/Compiler version (if compiling from source): 7.4.0
- CUDA/cuDNN version: CUDA 10.1, cuDNN 7.6.5
- GPU model and memory: Nvidia RTX 2080 Ti

**Describe the problem**

Building with Bazel 1.1.0 fails with the following message:
ImportError: /home/daniel/.cache/bazel/_bazel_daniel/79db702fc9f94af7d11e11c5d64854d0/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/python/keras/api/create_tensorflow.python_api_1_keras_python_api_gen.runfiles/org_tensorflow/tensorflow/compiler/tf2tensorrt/_wrap_py_utils.so: undefined symbol: _ZN10tensorflowlsERSoRKNS_6StatusE

Note: The failure of target //tensorflow/python/keras/api:create_tensorflow.python_api_1_keras_python_api_gen (with exit code 1) may have been caused by the fact that it is a Python 2 program that was built in the host configuration, which uses Python 3. You can change the host configuration (for the entire build) to instead use Python 2 by setting --host_force_python=PY2.
If this error started occurring in Bazel 0.27 and later, it may be because the Python toolchain now enforces that targets analyzed as PY2 and PY3 run under a Python 2 and Python 3 interpreter, respectively. See https://github.com/bazelbuild/bazel/issues/7899 for more information.

**Provide the exact sequence of commands / steps that you executed before running into the problem**
git clone https://github.com/tensorflow/tensorflow.git
cd tensorflow
git checkout -b mybranch
./configure
[tf_configure.bazelrc.txt](https://github.com/tensorflow/tensorflow/files/3882194/tf_configure.bazelrc.txt)
bazel build --explain=verbose_explanations.txt --verbose_explanations --verbose_failures --subcommands=pretty_print --config=opt --config=cuda --config=v2 --cxxopt="-D_GLIBCXX_USE_CXX11_ABI=0" //tensorflow/tools/pip_package:build_pip_package &> log.txt

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

See ful log.txt (which shows failure with Bazel 1.1.0)
and log2.txt (which shows success with Bazel 0.26.1)
from the following link: [Dropbox folder](https://www.dropbox.com/sh/mz1qvrd2yw0fb0a/AAB5ZAIWH0fj7C5okI1By-rna?dl=0)

**Comment by amahendrakar** [comment]
@dbonner,
Is this still an issue? Please feel free to close the issue if resolved. Thanks!
