### ISSUE TITLE
Is TF Lite optimized for nvidia gpu's and Intel CPUs?

### ISSUE THREAD

**Issue by fcakir** [tensorflow/tensorflow#34536]
Is TF Lite optimized for nvidia gpu's (as similar to TensorRT) and Intel CPUs. If not is there a list of supported hardware/accelerators out there?

**Comment by Cospel** [comment]
I think there is a plan in 2019 to add "First-class x86 support". At least that is written in the roadmap https://www.tensorflow.org/lite/guide/roadmap

So hopefully we will be able to optimize models on intel cpus.

**Comment by impjdi** [comment]
re: Nvidia GPU: No.  We targeted major mobile GPUs and they include Adreno, Mali, and PowerVR.

re: Intel CPU: You got the answer from @Cospel up there :)

**Comment by dlarue** [comment]
@impjdi   regarding the question if TF Lite is optimized for x86 CPU:  A post dated August 2019 about a 2019 Roadmap does not answer the question if it has been optimized for x86 CPUs.

**Comment by impjdi** [comment]
@dlarue 

Unfortunately, I'm not a direct member of TFLite and don't know their plans in detail.  AFAIK there are plans to support XNNPACK and from what I've seen, it woks great on Intel CPU-based desktops quite well.

**Comment by pigubaoza** [comment]
are there any updates to the x86 support?

**Comment by impjdi** [comment]
Maybe with TF 2.3 release.

**Comment by arturdryomov** [comment]
@impjdi, hey, it’s been a year — is it possible to use CUDA for Lite models? I see the `tensorflow-gpu` package and [a good amount of instructions](https://www.tensorflow.org/install/gpu). However, there are no mentions of `tensorflow.lite.Interpreter`.

**Comment by impjdi** [comment]
For that, you may want to create a CUDA delegate.  The link you provided is for TF, *not* TFLite.

**Comment by nathant-tommys** [comment]
I am trying to use the XNN Pack in python running on an Ubuntu machine with tflite_runtime 2.11.0. Is there any way of doing this? It has x86 CPU and Intel GPU that could be used. Any thoughts? Thanks!
