### ISSUE TITLE
RNN document is not clear

### ISSUE THREAD

**Issue by zwenju** [tensorflow/tensorflow#34539]
Thank you for submitting a TensorFlow documentation issue. Per our GitHub
policy, we only address code/doc bugs, performance issues, feature requests, and
build/installation issues on GitHub.

The TensorFlow docs are open source! To get involved, read the documentation
contributor guide: https://www.tensorflow.org/community/contribute/docs

## URL(s) with the issue:
https://www.tensorflow.org/api_docs/python/tf/keras/layers/RNN

Please provide a link to the documentation entry, for example:
https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/MyMethod

### Clear description

Problem 1:
Could you provides the math model of the rnn?

Problem 2:   this is not return information about  the method of 
get_initial_state(inputs=None, batch_size=None, dtype=None).
and 
how to define own get_initial_state ?
what is the connect between   state_size  and get_initial_state
Problem 3, 
could  you write more clear about  arguments  of the methods:  call, build, get_initial_state,
such as the   dimension of them.  each dimension is what .

Problem 4:
is the  cell  defined layer by user ?

thanks!

**Comment by dubesar** [comment]
@ymodak  Can this issue be included for Google Code-in as a task ?

**Comment by Dexter2389** [comment]
If no one is working on it, I can take this task-up.

**Comment by niranjan8129** [comment]
I getting this issue since long back .. I posted but it seems no one is taking care this issue . TF1.X 
version was pretty clear and return state as well. TF2.0 RNN document is not clear and the return type specially get_initial_state(inputs=None, batch_size=None, dtype=None).

**Comment by ymodak** [comment]
The documentation for `tf.keras.layers.RNN` has been significantly improved now.
It answers most of the ask in the original issue such as arguments of the methods: call, build, get_initial_state and more.
See https://www.tensorflow.org/api_docs/python/tf/keras/layers/RNN
