### ISSUE TITLE
Hey i need help with this problem in kali linux

### ISSUE THREAD

**Issue by Feelingloved** [tensorflow/tensorflow#34543]
Umm so i was using Kali linux today and I wanted to download HiddenEye but i get this problem here is a screneshot - http://prntscr.com/q0xuqi

Any way on how i can fix that and i am new to kali linux stuff

**Comment by oanush** [comment]
@Feelingloved ,
This is not Build/Installation or Bug/Performance issue. This repo is to report issue related to Tensorflow/core.Please raise the issue in right repo.Thanks!
