### ISSUE TITLE
Cannot install tensorflow on raspberry pi-0, raspbian buster

### ISSUE THREAD

**Issue by sidwa** [tensorflow/tensorflow#34550]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):Raspbian Buster
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: Raspberry Pi-0
- TensorFlow installed from (source or binary): binary
- TensorFlow version:1.14.0, 1.13.0
- Python version: 3.7.3
- Installed using virtualenv? pip? conda?: virtualenv and pip3
- Bazel version (if compiling from source): NA
- GCC/Compiler version (if compiling from source): NA
- CUDA/cuDNN version: NA
- GPU model and memory: NA

**Describe the problem**

**Provide the exact sequence of commands / steps that you executed before running into the problem**
I tried to perform steps given here: https://www.tensorflow.org/install/pip?lang=python3
for full tf install using binary

last command to install tensorflow being 
pip3 install https://storage.googleapis.com/tensorflow/raspberrypi/tensorflow-1.14.0-cp34-none-linux_armv6l.whl

**Any other info / logs**
I get the following error
ERROR: tensorflow-1.14.0-cp34-none-linux_armv6l.whl is not a supported wheel on this platform.

If I just do pip3 install --no-cache-dir tensorflow (rpi-0 memory is too small) I get,

ERROR: THESE PACKAGES DO NOT MATCH THE HASHES FROM THE REQUIREMENTS FILE. If you                                                                                                                                                              have updated the package versions, please update the hashes. Otherwise, examine                                                                                                                                                              the package contents carefully; someone may have tampered with them.
    tensorflow from https://www.piwheels.org/simple/tensorflow/tensorflow-1.13.1                                                                                                                                                             -cp37-none-linux_armv6l.whl#sha256=25f4ff027beec1e568baf8e90a07bad59d354560533d6                                                                                                                                                             b37318b9efeb70beeb1:
        Expected sha256 25f4ff027beec1e568baf8e90a07bad59d354560533d6b37318b9efe                                                                                                                                                             b70beeb1
             Got        3aad2c162168a62adae30e226bcddfef74e5db1ca98bec1383958fb5                                                                                                                                                             80e67123

**Comment by oanush** [comment]
@sidwa ,
Can you please refer the [link](https://github.com/MycroftAI/mycroft-precise/issues/79#issuecomment-532723758) of similar issue and let us know if it helped ?Thanks!

**Comment by sidwa** [comment]
pipenv doesn't seem to work adding sudo to those commands don't help either

**Comment by sidwa** [comment]
Currently I can install tensorflow using, "pip3 --no-cache-dir install tensorflow" there is no hash mismatch anymore.

**Comment by dzilaan** [comment]
still has the error when i used "pip3 --no-cache-dir install tensorflow"
