### ISSUE TITLE
ppc64le hang nsync::nsync_mu_semaphore_p_with_deadline

### ISSUE THREAD

**Issue by sh1ng** [tensorflow/tensorflow#34555]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
custom
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
```
uname -a    
Linux 00da561b85b1 4.14.0-115.13.1.el7a.ppc64le #1 SMP Thu Sep 19 14:12:21 UTC 2019 ppc64le ppc64le ppc64le GNU/Linux
```
```
cpu		: POWER9, altivec supported
clock		: 3783.000000MHz
revision	: 2.2 (pvr 004e 1202)

timebase	: 512000000
platform	: PowerNV
model		: 8335-GTH
machine		: PowerNV 8335-GTH
firmware	: OPAL
MMU		: Radix
```
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
source compiled with
```
ENV PYTHON_BIN_PATH=/usr/bin/python \
    PYTHON_LIB_PATH=/usr/lib/python2.7/site-packages \
    TF_NEED_JEMALLOC=1 \
    TF_NEED_GCP=0 \
    TF_NEED_HDFS=0 \
    TF_NEED_AWS=0 \
    TF_NEED_KAFKA=0 \
    TF_ENABLE_XLA=0 \
    TF_NEED_GDR=0 \
    TF_NEED_VERBS=0 \
    TF_NEED_NGRAPH=0 \
    TF_NEED_OPENCL_SYCL=0 \
    TF_NEED_CUDA=0 \
    TF_CUDA_CLANG=0 \
    TF_DOWNLOAD_CLANG=0 \
    TF_NEED_MPI=0 \
    GCC_HOST_COMPILER_PATH=gcc \
    CC_OPT_FLAGS=FROM_OPT \
    TF_SET_ANDROID_WORKSPACE=0
```
- TensorFlow version (use command below):
https://github.com/tensorflow/tensorflow/archive/v1.13.1.tar.gz
- Python version:
2.7
- Bazel version (if compiling from source):
https://github.com/bazelbuild/bazel/releases/download/0.19.2/bazel-0.19.2-dist.zip
- GCC/Compiler version (if compiling from source):
```
gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-36)
```
- CUDA/cuDNN version:
None
- GPU model and memory:
Tesla V100-SXM2-32GB, but tf is compiled without gpu support

Process hangs sometimes. bt is in attachments
[bt.log](https://github.com/tensorflow/tensorflow/files/3883495/bt.log)

**Comment by gadagashwini** [comment]
@sh1ng,
Provide the exact sequence of commands / steps that you executed before running into the problem. Thanks!

**Comment by sh1ng** [comment]
It's not so easy as it includes a lot of our internal code(python) and we see the issue periodically in the smoke test.

**Comment by gadagashwini** [comment]
@sh1ng, Its hard to analyze the issue without code snippet. Could you write minimum code snippet which generates reported issue. Thanks!
