### ISSUE TITLE
Feature Request: support sparse tensor in conv2d operator

### ISSUE THREAD

**Issue by iurilgit** [tensorflow/tensorflow#3455]
It looks like TF doesn't support conv2d as another thread mentioned (https://github.com/tensorflow/tensorflow/issues/1604). This is critical for us since we are implementing CDSSM (from microsoft https://www.microsoft.com/en-us/research/wp-content/uploads/2016/02/www2014_cdssm_p07.pdf). Miscrosoft's library supports it and the training speed is dramatically faster than using TF. So we strongly feel this feature is important.

**Comment by vrv** [comment]
Is this different from #1604 ?

**Comment by iurilgit** [comment]
It is essentially the same. But that was  not reported as a feature request. I am shouting out officially to request it. :)

**Comment by vrv** [comment]
I will retitle that one.

**Comment by iurilgit** [comment]
That works too. Thanks!
