### ISSUE TITLE
numpy.dot and tensorflow.tensordot can't be used together in MacBook

### ISSUE THREAD

**Issue by huangyh09** [tensorflow/tensorflow#34553]
Hi, 

I was using tensorflow (2.0.0) and numpy (1.7.3) on my MacBook (with Python 3.7.5), but it failed to use both `numpy.dot` (or `numpy.tensordot`) and `tensorflow.tensordot` in one jupyter notebook (no error reported but never finish), though any of them alone works properly.

I have tried the same codes on Linux with the same conda environment, and there is no such issue.

Codes I tested:
```
import numpy as np
import tensorflow as tf

Nd, Nk, Ns = 3, 2, 5
w_np = np.ones([Nd, Nk], dtype=np.float32)
z_np = np.ones([Nk, Ns], dtype=np.float32)
```

Only one the the following two works on MacBook:
```
tf.tensordot(w_np, z_np, axes=1)
```

Or

```
np.tensordot(w_np, z_np, axes=1) # or np.dot(w_np, z_np)
```

**Comment by ravikyram** [comment]
I have tried on colab with TF version 2.0 in Linux and i am not seeing any issue. Please, find the gist [here](https://colab.sandbox.google.com/gist/ravikyram/9fafbfb43166245d6ebc0e5b28b2106c/untitled399.ipynb).Thanks!

**Comment by huangyh09** [comment]
Thanks for testing this. Yes, it works in Linux for myself too, but not in MacBook.

Yuanhua

**Comment by huangyh09** [comment]
When I tested again in teminal instead of ipython notebook, the session has been closed with following log:

```
OMP: Error #15: Initializing libiomp5.dylib, but found libiomp5.dylib already initialized.
OMP: Hint This means that multiple copies of the OpenMP runtime have been linked into the program. That is dangerous, since it can degrade performance or cause incorrect results. The best thing to do is to ensure that only a single OpenMP runtime is linked into the process, e.g. by avoiding static linking of the OpenMP runtime in any library. As an unsafe, unsupported, undocumented workaround you can set the environment variable KMP_DUPLICATE_LIB_OK=TRUE to allow the program to continue to execute, but that may cause crashes or silently produce incorrect results. For more information, please see http://www.intel.com/software/products/support/.
```

As suggested in the log, adding the following lines before running the code can avoid the issue.
```
import os
os.environ['KMP_DUPLICATE_LIB_OK']='True'
```
Also see here: https://github.com/dmlc/xgboost/issues/1715#issuecomment-420305786

Yuanhua
