### ISSUE TITLE
tf.keras fit is incompatible with tf.function

### ISSUE THREAD

**Issue by Danmou** [tensorflow/tensorflow#34556]
**System information**
- TensorFlow version (use command below): 2.0.0
- Python version: 3.7

**Describe the current behavior**
I'm not sure if this is a bug or a documentation issue. The [migration guide](https://www.tensorflow.org/guide/migrate#mixed_variables_v1layers) recommends adding the `@tf.function` decorator to the `call` method of subclassed Keras models or layers. However, this causes problems when using the `Layer.add_loss` method with input-dependent losses as described in the [Keras guide](https://www.tensorflow.org/guide/keras/custom_layers_and_models#layers_recursively_collect_losses_created_during_the_forward_pass). In retrospect it makes sense that this doesn't work since `tf.function` requires all outputs to be returned from the function, but this is not made very clear in the docs and the resulting error message is not very helpful.

**Code to reproduce the issue**
```python
import numpy as np
import tensorflow as tf
from tensorflow.keras import layers

class MyModel(tf.keras.Model):
    def __init__(self, num_classes):
        super().__init__()
        self.num_classes = num_classes
        self.dense = layers.Dense(num_classes, activation='sigmoid')

    @tf.function
    def call(self, inputs):
        self.add_loss(tf.reduce_sum(inputs), inputs=True)
        return self.dense(inputs)

data = np.random.random((1000, 32))
labels = np.random.random((1000, 10))
model = MyModel(num_classes=10)
model.compile(optimizer=tf.keras.optimizers.RMSprop(0.001),
              loss='categorical_crossentropy')
model.fit(data, labels, epochs=50)
```
And the resulting error:
```
TypeError: An op outside of the function building code is being passed
a "Graph" tensor. It is possible to have Graph tensors
leak out of the function building context by including a
tf.init_scope in your function building code.
For example, the following function will fail:
  @tf.function
  def has_init_scope():
    my_constant = tf.constant(1.)
    with tf.init_scope():
      added = my_constant * 2
The graph tensor has name: Sum:0
```

**Expected behavior**
Ideally `add_loss` and `tf.function` would somehow be compatible. This would give me the flexibility to use the model directly by calling it or use the keras `fit` and `predict` functions as I please without hurting performance. Alternatively, at least the `tf.keras` guide should make the incompatibility clear, and perhaps an explicit check should be added to make sure `add_loss` is not called inside a `tf.function`.

**Comment by ymodak** [comment]
The issue reproduces with tf-nightly version 2.1.0-dev20191125.

**Comment by sushreebarsa** [comment]
Was able to reproduce the issue in TF 2.6.0-dev20210529,please find the gist [here](https://colab.research.google.com/gist/sushreebarsa/7a8c1ce66ad5eb7a990c64829dfcb0d7/untitled87.ipynb)..Thanks !
