### ISSUE TITLE
multi previous states RNN 

### ISSUE THREAD

**Issue by zwenju** [tensorflow/tensorflow#34562]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using):
- Are you willing to contribute it (Yes/No):

**Describe the feature and the current behavior/state.**

I try to use the RNN model to do the time series as 
h_t  = F(  h_{t-1},   h_{t-2}   X_t  )
I found that  RNN in TF2.0  not works.

It only works for the following model.
h_t  = F(  h_{t-1},  X_t  )

Could you give me some help  which RNN model in TF2.0 could do the 
h_t  = F(  h_{t-1},   h_{t-2}   X_t  ),

where t is a sequence of time [t_0, t_1,  t_2,  ...,   t_N ].

Thanks

**Will this change the current api? How?**

**Who will benefit with this feature?**

**Any Other info.**

**Comment by qlzh727** [comment]
So far, all the classic RNN cell only access the state from t-1, rather than from any previous state further. This is why we design the API interface like at as well, where cell takes inputs and state from t-1. 

You will have to write your own code achieve the behavior you described. Eg:

```
class DoubleStateCell(layer):

  def __init__(self, units):
     # having 2 states like LSTM, but tracking t-1 and t-2
     self.state_size = [units, units] 

  def call(self, inputs, states):
     state_t-1 = states[0]
     state_t-2 = states[1]
     .....
     new_state = ...
     output = ....
     return output, [new_state, state_t-1]
```
