### ISSUE TITLE
RuntimeError: Collective ops must be configured at program startup

### ISSUE THREAD

**Issue by MoizArif** [tensorflow/tensorflow#34568]
Running distributed TensorFlow gives:

> RuntimeError: Collective ops must be configured at program startup

**System information**
- Tutorial: https://www.tensorflow.org/tutorials/distribute/multi_worker_with_keras
- Ubuntu 18.04 (4.15.0-70-generic)
- TensorFlow installed from pip using pip install tensorflow==2.0.0
- Python 2.7.15

> numpy                    1.16.5
> protobuf                 3.10.0
> tensorflow-datasets      1.3.0
> tensorflow-estimator     2.0.1
> tensorflow-metadata      0.15.1

In the sequence of code, first TF_CONFIG is set using:
`os.environ["TF_CONFIG"] = json.dumps({"cluster": {"worker": ["abc:12345", "bcd:23456", "cde:34567"]},"task": {"type": "worker", "index": 0}})`

and then:
`strategy = tf.distribute.experimental.MultiWorkerMirroredStrategy()`

The expected behavior should be that this strategy should work but I get: 
`RuntimeError: Collective ops must be configured at program startup`

As per the documentation, the TF_CONFIG is defined before the strategy command. I read some of the issues and people suggested to upgrade to the latest tf-nightly but even after I did that I still get the same issue.

**Comment by gadagashwini** [comment]
@MoizArif, I tried the tutorial colab link, its working without any error. Looks like Python version incompatibility. Try upgrading `Python `to `3.x` and check once.  Let us know how it progresses. Thanks!

**Comment by MoizArif** [comment]
Hi, thank you for your response. 

Upgrading my environment to Python 3.6.8 still gives the same error as described earlier. In the tutorial:
`strategy = tf.distribute.experimental.MultiWorkerMirroredStrategy()`
gives a warning:
`WARNING:tensorflow:Collective ops is not configured at program startup. Some performance features may not be enabled.`
 but in my environment, it gives this as an error instead of a warning. 
`RuntimeError: Collective ops must be configured at program startup`

I am confused since other issues suggest this has already been fixed but even with the latest tensorflow/tf-nightly code I still get this as an error. Even when I do define the collective ops at startup.

**Comment by gadagashwini** [comment]
@MoizArif, 
In the tutorial it is mentioned that `Currently there is a limitation in MultiWorkerMirroredStrategy where TensorFlow ops need to be created after the instance of strategy is created. If you see RuntimeError: Collective ops must be configured at program startup, try creating the instance of MultiWorkerMirroredStrategy at the beginning of the program and put the code that may create ops after the strategy is instantiated.`.
Please see [here](https://www.tensorflow.org/tutorials/distribute/multi_worker_with_keras#train_the_model_with_multiworkermirroredstrategy) for more information. Thanks!

**Comment by MoizArif** [comment]
I have created the strategy instance before the collection ops definition and it seems to have by-passed my original error.

**Comment by ranvirdesai** [comment]
@MoizArif 
I am also facing the same issue, is it resolved?

**Comment by hariouat** [comment]
still have the same issue, did you find a solution,?
