### ISSUE TITLE
No way to use tensorflow with cuda on windows.  cudaGetDevice() failed.

### ISSUE THREAD

**Issue by acarrill** [tensorflow/tensorflow#34567]
Hi,

I'm trying to use cuda with tensorflow. I installed cuda 10.0 and tensorflow 2.0, my version of VS is 2017. I set my env variables and the problem persists.

This is the error message: **cudaGetDevice() failed. Status: cudaGetErrorString symbol not found.**

Thanks to u all!

**Comment by ravikyram** [comment]
@acarrill 

Please, see [software requirements](https://www.tensorflow.org/install/gpu#software_requirements) are met.Also go through [link1](https://stackoverflow.com/questions/58868272/what-may-be-the-problem-with-this-cudagetdevice-failed-status-cudageterrorst) and [link2](https://stackoverflow.com/questions/58235018/cuda-issue-how-to-clean-install-cuda-in-win-10-to-resolve-cudagetdevice-fail) and see if it helps you.Also see which TF binary suits your case https://www.tensorflow.org/install/pip?lang=python3#older-versions-of-tensorflow. Thanks!

**Comment by ravikyram** [comment]
@acarrill 

Any update on the issue please. Thanks!

**Comment by acarrill** [comment]
@ravikyram Yep, sorry!
I'm now able to use tensorflow with gpu. I only had to uninstall tensorflow and tensorflow-gpu, next I reinstalled tensorflow-gpu, also I included this line in my code:

`os.environ["CUDA_VISIBLE_DEVICES"]="0"`

Now I have other issue. I can't confirm what physical device I'm using. It's looks like gpu, even if 
I change CUDA_VISIBLE_DEVICES if I execute the following command I always  receive a "True" answer

`tf.test.is_gpu_available( cuda_only=False, min_cuda_compute_capability=None )`

If I use this code i have not answer:

`with tf.device('/CPU:0'):
    tf.test.is_gpu_available( cuda_only=False, min_cuda_compute_capability=None )
`

If I use this other one, 

`tf.config.experimental.list_physical_devices(device_type=None)`

this is the answer: 

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'),
 PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

I have other doubts about "tf.compat.v1.Session()" but I'm not pretty sure i should open other topic.

Cheers, and sry for the late response!

**Comment by ravikyram** [comment]
@acarrill 

Looks like original issue got resolved.Please, feel free to open new issue if you are facing other issues.Please provide all the information as per the new issue template and raise new issue. Thanks!

**Comment by ravikyram** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Comment by aayushkeshari** [comment]
I am reopening this issue
