### ISSUE TITLE
[tflite] Need custom implementantion for operators

### ISSUE THREAD

**Issue by gogokinghaha** [tensorflow/tensorflow#34576]
Some of the operators in the model are not supported by the standard TensorFlow Lite runtime. If those are native TensorFlow operators, you might be able to use the extended runtime by passing --enable_select_tf_ops, or by setting target_ops=TFLITE_BUILTINS,SELECT_TF_OPS when calling tf.lite.TFLiteConverter(). Otherwise, if you have a custom implementation for them you can disable this error with --allow_custom_ops, or by setting allow_custom_ops=True when calling tf.lite.TFLiteConverter(). Here is a list of builtin operators you are using: FULLY_CONNECTED, RESHAPE, STRIDED_SLICE. Here is a list of operators for which you will need custom implementations: TensorListFromTensor, TensorListReserve, TensorListStack, While.

**Comment by ymodak** [comment]
You can try [converting your model](https://www.tensorflow.org/lite/guide/ops_select#converting_the_model) using ```TFLITE_BUILTINS, SELECT_TF_OPS``` flags to reduce custom implementation of ops (only a subset of ops can be implemented by this method while others may still require custom implementation )

What version of TF are you using?

**Comment by ymodak** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
