### ISSUE TITLE
Problem in distributed tensorflow demo?

### ISSUE THREAD

**Issue by perhapszzy** [tensorflow/tensorflow#3457]
### Environment info

Operating System:
Kubernetes (using the 0.8.0 server image)

Installed version of CUDA and cuDNN: 
No

When I start the [mnist_replica demo](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/dist_test/python/mnist_replica.py), it stuck after `prepare_or_wait_for_session`

But if I run `start_queue_runners` for both chief worker and all other workers, it runs successfully. (By removing `and is_chief` part [here](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/dist_test/python/mnist_replica.py#L224) and [here](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/dist_test/python/mnist_replica.py#L193))

Is this a bug in the demo?

**Comment by perhapszzy** [comment]
made a pr https://github.com/tensorflow/tensorflow/pull/3458 to fix this

**Comment by perhapszzy** [comment]
Update： If I start workers this way:
```
  if FLAGS.job_name == 'ps':
    server.join()
  else:
   # Do training
```

Instead of connecting to worker each time:
```
sess = sv.prepare_or_wait_for_session(FLAGS.worker_grpc_url)
```

I can successfully run the code. Any explanation about this?

**Comment by perhapszzy** [comment]
Way to repeat the problem:
On my own laptop run the following three cmd:
```
python mnist_replica.py --worker_grpc_url="grpc://43.254.53.118:30001" --worker_index=0 --sync_replicas
python mnist_replica.py --worker_grpc_url="grpc://43.254.53.118:30002" --worker_index=1 --sync_replicas
python mnist_replica.py --worker_grpc_url="grpc://43.254.53.118:30003" --worker_index=2 --sync_replicas
```
The log for worker1 is:
```
Worker GRPC URL: grpc://43.254.53.118:30001
Worker index = 0
Number of workers = 3
Worker 0: Initializing session...
Worker 0: Session initialization complete.
Starting chief queue runner and running init_tokens_op
Training begins @ 1469418277.317969
1469418277.659315: Worker 0: training step 1 done (global step: 0)
1469418277.961008: Worker 0: training step 2 done (global step: 0)
1469418278.261021: Worker 0: training step 3 done (global step: 0)
1469418292.345302: Worker 0: training step 4 done (global step: 0)
```

The log for worker2 is:
```
Worker GRPC URL: grpc://43.254.53.118:30002
Worker index = 1
Number of workers = 3
Worker 1: Waiting for session to be initialized...
Worker 1: Session initialization complete.
Training begins @ 1469418290.118592
1469418292.332708: Worker 1: training step 1 done (global step: 0)
1469418292.865696: Worker 1: training step 2 done (global step: 1)
```
And log for worker 3 is:
```
Worker GRPC URL: grpc://43.254.53.118:30003
Worker index = 2
Number of workers = 3
Worker 2: Waiting for session to be initialized...
Worker 2: Session initialization complete.
Training begins @ 1469418298.766421
```

They stuck there forever. I'm keeping the server alive so that anybody should be able to repeat this problem. The mnist_replica.py is [here](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/dist_test/python/mnist_replica.py) and I also updated the file:
[mnist_replica.py.txt](https://github.com/tensorflow/tensorflow/files/380746/mnist_replica.py.txt)

**Comment by DjangoPeng** [comment]
@perhapszzy 
Have you solved the problem? I'm trying the distributed mnist demo, and I'm facing the same problem!
The tutorial of distributed tensorflow is really awful and hard-to-use

**Comment by perhapszzy** [comment]
I can start the demo by applying this pr:
https://github.com/tensorflow/tensorflow/pull/3458

but I haven't figured out why.

**Comment by caisq** [comment]
The --sync-replicas mode is not fully supported yet (see the obscurely located line at: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/dist_test/scripts/dist_mnist_test.sh#L69). If you remove that flag, it should work under the asynchronous mode.

**Comment by perhapszzy** [comment]
Is synchronous model not supported in general or just this demo doesn't support it? I did found it work when start individual works this way:

```
  if FLAGS.job_name == 'ps':
    server.join()
  else:
   # Do training
```
 
And it also runs by applying that pr. (not sure if it works expectedly).

**Comment by drpngx** [comment]
Closing this as per @jmchen-g comment on the PR. Let us know if it's still not fixed.
