### ISSUE TITLE
Many problems when to convert pb to tflite

### ISSUE THREAD

**Issue by kscorpio** [tensorflow/tensorflow#34578]
- OS Platform and Distribution ( Linux Ubuntu 18.04 **install on VMware Fusion **):
- TensorFlow installed from (source or binary): binary 
- TensorFlow version (or github SHA if from source): 1.14.0

> train model
I download pet data source and train

```
 python3 object_detection/model_main.py --pipeline_config_path=ssd_mobilenet_v1_pets.config  --model_dir=output
```
 

> use to get tflite_graph.pb and tflite_graph.pbtxt 

```
 python3 object_detection/export_tflite_ssd_graph.py  --pipeline_config_path=ssd_mobilenet_v1_pets.config  --trained_checkpoint_prefix=output/model.ckpt-0  --output_directory=output --add_postprocessing_op=true
```

> get tflite 

```
bazel run -c opt tensorflow/lite/toco:toco --  --input_file=$TRAINHOME/tflite/tflite_graph.pb --output_file=$TRAINHOME/tflite/detect.tflite --input_shapes=1,300,300,3 --input_arrays=normalized_input_image_tensor --output_arrays='TFLite_Detection_PostProcess','TFLite_Detection_PostProcess:1','TFLite_Detection_PostProcess:2','TFLite_Detection_PostProcess:3'  --inference_type=QUANTIZED_UINT8 --mean_values=128 --std_values=128 --change_concat_input_ranges=false --allow_custom_ops
```

`tensorflow/lite/toco:` is a directory which i download tensorflow source code from github
 
error message :

```bash
 INFO: Writing tracer profile to '/home/kscorpio/.cache/bazel/_bazel_kscorpio/875b32c2c1b2a0876b2c7691115da3ca/command.profile.gz'
ERROR: Skipping 'tensorflow/lite/toco:toco': error loading package 'tensorflow/lite/toco': in /home/kscorpio/tensorflow/tensorflow.bzl: in /home/kscorpio/tensorflow/core/platform/default/build_config_root.bzl: Unable to find package for @local_config_remote_execution//:remote_execution.bzl: The repository '@local_config_remote_execution' could not be resolved.
WARNING: Target pattern parsing failed.
ERROR: error loading package 'tensorflow/lite/toco': in /home/kscorpio/tensorflow/tensorflow.bzl: in /home/kscorpio/tensorflow/core/platform/default/build_config_root.bzl: Unable to find package for @local_config_remote_execution//:remote_execution.bzl: The repository '@local_config_remote_execution' could not be resolved.
INFO: Elapsed time: 0.183s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (1 packages loaded)
FAILED: Build did NOT complete successfully (1 packages loaded)

```

in addition , `bazel run xxxxx:toco` and `tflite_convert ` which is the right way ?

**Comment by ymodak** [comment]
Looks like you are trying to serve a object detection model in tf lite. In that case following example may come in handy.
See https://www.tensorflow.org/lite/models/object_detection/overview
https://github.com/tensorflow/examples/blob/master/lite/examples/object_detection/android/README.md
For [building a custom model](https://www.tensorflow.org/lite/models/object_detection/overview#customize_model) you may use transfer learning to train new data.

**Comment by kscorpio** [comment]
I don't want to use a tflite object detection model in Android devices or iOS devices . It's to train a model with Tensorflow model - object detection ,and covert "xxx.pb" to "xx.tflite"

> https://github.com/tensorflow/models/tree/master/research/object_detection

> https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/running_on_mobile_tensorflowlite.md
