### ISSUE TITLE
training with dataset cifar100fails: KeyError: 'conv2d_input

### ISSUE THREAD

**Issue by olk** [tensorflow/tensorflow#34588]
**System information**System information
- OS Platform and Distribution: Arch Linux, 5.3.7-arch1-1-ARCH
- TensorFlow installed from: binary
- TensorFlow version: 2.0.0
- Keras version: 2.2.4-tf
- Python version: 3.7.4
- CUDA/cuDNN version: CUDA 10.1.243 / cuDNN 7.6.2.24
- GPU model and memory: 2x GTX 1080 Ti 11GB"`

**Describe the current behavior**
exception thrown: "KeyError: 'conv2d_input'"

**backtrace**

> Epoch 1/10
>       1/Unknown - 0s 70ms/stepTraceback (most recent call last):
>   File "cifar100.py", line 35, in <module>
>     verbose=1)
>   File "/usr/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training.py", line 728, in fit
>     use_multiprocessing=use_multiprocessing)
>   File "/usr/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training_v2.py", line 324, in fit
>     total_epochs=epochs)
>   File "/usr/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training_v2.py", line 123, in run_one_epoch
>     batch_outs = execution_function(iterator)
>   File "/usr/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training_v2_utils.py", line 86, in execution_function
>     distributed_function(input_fn))
>   File "/usr/lib/python3.7/site-packages/tensorflow_core/python/eager/def_function.py", line 457, in __call__
>     result = self._call(*args, **kwds)
>   File "/usr/lib/python3.7/site-packages/tensorflow_core/python/eager/def_function.py", line 503, in _call
>     self._initialize(args, kwds, add_initializers_to=initializer_map)
>   File "/usr/lib/python3.7/site-packages/tensorflow_core/python/eager/def_function.py", line 408, in _initialize
>     *args, **kwds))
>   File "/usr/lib/python3.7/site-packages/tensorflow_core/python/eager/function.py", line 1848, in _get_concrete_function_internal_garbage_collected
>     graph_function, _, _ = self._maybe_define_function(args, kwargs)
>   File "/usr/lib/python3.7/site-packages/tensorflow_core/python/eager/function.py", line 2150, in _maybe_define_function
>     graph_function = self._create_graph_function(args, kwargs)
>   File "/usr/lib/python3.7/site-packages/tensorflow_core/python/eager/function.py", line 2041, in _create_graph_function
>     capture_by_value=self._capture_by_value),
>   File "/usr/lib/python3.7/site-packages/tensorflow_core/python/framework/func_graph.py", line 915, in func_graph_from_py_func
>     func_outputs = python_func(*func_args, **func_kwargs)
>   File "/usr/lib/python3.7/site-packages/tensorflow_core/python/eager/def_function.py", line 358, in wrapped_fn
>     return weak_wrapped_fn().__wrapped__(*args, **kwds)
>   File "/usr/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training_v2_utils.py", line 66, in distributed_function
>     model, input_iterator, mode)
>   File "/usr/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training_v2_utils.py", line 118, in _prepare_feed_values
>     inputs = [inputs[key] for key in model._feed_input_names]
>   File "/usr/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training_v2_utils.py", line 118, in <listcomp>
>     inputs = [inputs[key] for key in model._feed_input_names]
> KeyError: 'conv2d_input'

**Describe the expected behavior**
training the network doesn't fail

**Code to reproduce the issue**

```
import tensorflow as tf
import tensorflow_datasets as tfds

from tensorflow.keras.layers import BatchNormalization, Conv2D, Dense, Dropout, Flatten, MaxPooling2D

ds_train = tfds.load(name="cifar100", split=tfds.Split.TRAIN)
ds_test = tfds.load(name="cifar100", split=tfds.Split.TEST)

input_shape = (32,32, 3)
num_classes = 10
epochs = 10

model = tf.keras.Sequential([
    Conv2D(32, 5, padding='same', activation='relu', input_shape=input_shape),
    MaxPooling2D((2, 2), (2, 2), padding='same'),
    BatchNormalization(),
    Conv2D(64, 5, padding='same', activation='relu'),
    MaxPooling2D((2, 2), (2, 2), padding='same'),
    Flatten(),
    Dense(1024, activation='relu'),
    Dropout(0.4),
    Dense(num_classes, activation='softmax')
])

model.summary()

model.compile(
    loss=tf.keras.losses.categorical_crossentropy,
    optimizer='adam',
    metrics=['accuracy'])

model.fit(ds_train,
          epochs=epochs,
          validation_data=ds_test,
          verbose=1)
```

**Comment by oanush** [comment]
Issue replicating for the given code, kindly find the [gist](https://colab.sandbox.google.com/gist/oanush/28b102fd0e6013a885cba6e51d5c944e/34588.ipynb) of colab.Thanks!

**Comment by rmothukuru** [comment]
@olk, 
The error might be because the `Input Shape` which the Convolutional Layer expects and the Input Shape of tf.data.dataset doesn't match.  Please refer [this link](https://towardsdatascience.com/cifar-10-image-classification-in-tensorflow-5b501f7dc77c), which has the complete code for Image Classification for Cifar Dataset. Thanks!

**Comment by olk** [comment]
`as_supervised=True` fixed the issue
