### ISSUE TITLE
tf.cond blocks forever when one branch calls tf.random_crop trough tf.map_fn

### ISSUE THREAD

**Issue by untom** [tensorflow/tensorflow#3459]
I'm running tensorflow 0.9.0 on Python 3.5.2 using CUDA 7.5 on CentOS 7, and I keep running into very weird behaviour: tf.cond seems to stall forever when the non-active branch calls tf.random_crop. I've reduced my code to the following minimal example:

    import numpy as np
    import tensorflow as tf

    IMG_WIDTH = 32
    IMG_HEIGHT = 32
    IMG_CHANNELS = 3

    def distort_image(image):
        # this should crop the whole image, i.e. do nothing!
        return tf.random_crop(image, [IMG_HEIGHT, IMG_WIDTH, IMG_CHANNELS])

    xx = np.random.normal(size=(4, IMG_HEIGHT, IMG_WIDTH, 3)).astype(np.float32)

    tf.reset_default_graph()
    x = tf.placeholder(tf.float32, shape=(None, IMG_HEIGHT, IMG_WIDTH, IMG_CHANNELS))
    is_training = tf.placeholder(tf.bool)
    xp = tf.cond(is_training,  
            lambda: tf.map_fn(distort_image, x, back_prop=False),  
            lambda: tf.identity(x))  

    init = tf.initialize_all_variables()
    with tf.Session() as sess:
        sess.run(init)
        p = sess.run(xp, feed_dict={x: xx, is_training: False})

The weird thing is that if `is_training` is set to True, the function runs through without problems. I.e., when you actually call the `tf.map_fn` branch, everything works out fine.

**Comment by untom** [comment]
So, I played around with this a bit more: the behaviour is a bit different on CPU and on GPU.  On the CPU, the above code runs though just fine. For what it's worth, I'm using a TitanX using Cuda 7.5.

**Comment by ebrevdo** [comment]
It would be helpful if you could run the code in gdb and provide a gist with the full backtrace ("thread apply all bt").

you may need to run "gdb --args python ./path/to/your/python/script"

**Comment by untom** [comment]
For what it's worth, if I explicitly place `xp` on the CPU using a `device_scope`, I don't run into any issues. As far as I'm concerned, my issue is solved and this can be closed.

**Comment by ebrevdo** [comment]
@yuanbyu you have a change that probably fixes this, yes?

**Comment by yuanbyu** [comment]
Yes. It is CL/129785041 that you reviewed.  -Yuan

**Comment by ebrevdo** [comment]
Thomas, can you confirm this bug is fixed?

**Comment by untom** [comment]
Hi! Unfortunately I don't have the time to compile my own TF version right now, so I'll have to wait for the next RC-release to test this.

**Comment by ebrevdo** [comment]
You can download a nightly wheel.  See the readme.md on
github/tensorflow/tensorflow.

**Comment by ebrevdo** [comment]
Please close the issue once you see that it's been solved in the nightlies.

**Comment by yuanbyu** [comment]
This should have fixed at HEAD.  Please verify.

**Comment by untom** [comment]
I can confirm that the behavior seems fixed with the current nightlies
