### ISSUE TITLE
build from source fails

### ISSUE THREAD

**Issue by hartsantler** [tensorflow/tensorflow#346]
i just built the latest bazel from source, and pulled the latest tensorflow from source, and ran this to compile tensor:
```bash
bazel build -c opt //tensorflow/tools/pip_package:build_pip_package
```

After running for awhile, it failed with this error:

```
ERROR: /home/brett/tensorflow/tensorflow/tensorboard/bower/BUILD:3:1: no such package '@plottable//': Unexpected end of file from server and referenced by '//tensorflow/tensorboard/bower:bower'.
ERROR: Loading failed; build aborted.
INFO: Elapsed time: 173.131s
```

I am running Fedora22, 64bits.

**Comment by hartsantler** [comment]
i tried running the command again, and now i get these errors:
```
INFO: Found 1 target...
INFO: From Compiling google/protobuf/src/google/protobuf/stubs/structurally_valid.cc [for host]:
google/protobuf/src/google/protobuf/stubs/structurally_valid.cc:4:42: fatal error: google/protobuf/stubs/common.h: No such file or directory
compilation terminated.
ERROR: /home/brett/tensorflow/google/protobuf/BUILD:29:1: C++ compilation of rule '//google/protobuf:protobuf_lite' failed: gcc failed: error executing command /usr/bin/gcc -U_FORTIFY_SOURCE '-D_FORTIFY_SOURCE=1' -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 -DNDEBUG -ffunction-sections ... (remaining 36 argument(s) skipped).
Target //tensorflow/tools/pip_package:build_pip_package failed to build
```

**Comment by hartsantler** [comment]
i ran with --verbose_failures, looks like `hash.h` is missing.

```
[brett@localhost tensorflow]$ bazel build -c opt //tensorflow/tools/pip_package:build_pip_package --verbose_failures
INFO: Found 1 target...
INFO: From Compiling google/protobuf/src/google/protobuf/compiler/parser.cc [for host]:
google/protobuf/src/google/protobuf/compiler/parser.cc:38:40: fatal error: google/protobuf/stubs/hash.h: No such file or directory
compilation terminated.
ERROR: /home/brett/tensorflow/google/protobuf/BUILD:63:1: C++ compilation of rule '//google/protobuf:protobuf' failed: gcc failed: error executing command 
  (cd /home/brett/.cache/bazel/_bazel_brett/cad5cb2acfc6cd577d8180fb5b9f9a6b/tensorflow && \
  exec env - \
    PATH=/usr/lib64/qt-3.3/bin:/usr/lib64/ccache:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/bin:/sbin:/home/brett/.local/bin:/home/brett/bin \
  /usr/bin/gcc -U_FORTIFY_SOURCE '-D_FORTIFY_SOURCE=1' -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 -DNDEBUG -ffunction-sections -fdata-sections -g0 '-std=c++0x' -iquote . -iquote bazel-out/host/genfiles -iquote external/bazel_tools -iquote bazel-out/host/genfiles/external/bazel_tools -isystem google/protobuf/src -isystem bazel-out/host/genfiles/google/protobuf/src -isystem external/bazel_tools/tools/cpp/gcc3 -DHAVE_PTHREAD -Wall -Wwrite-strings -Woverloaded-virtual -Wno-sign-compare '-Wno-error=unused-function' -no-canonical-prefixes -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' '-frandom-seed=bazel-out/host/bin/google/protobuf/_objs/protobuf/google/protobuf/src/google/protobuf/compiler/parser.o' -MD -MF bazel-out/host/bin/google/protobuf/_objs/protobuf/google/protobuf/src/google/protobuf/compiler/parser.d -c google/protobuf/src/google/protobuf/compiler/parser.cc -o bazel-out/host/bin/google/protobuf/_objs/protobuf/google/protobuf/src/google/protobuf/compiler/parser.o): gcc failed: error executing command 
  (cd /home/brett/.cache/bazel/_bazel_brett/cad5cb2acfc6cd577d8180fb5b9f9a6b/tensorflow && \
  exec env - \
    PATH=/usr/lib64/qt-3.3/bin:/usr/lib64/ccache:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/bin:/sbin:/home/brett/.local/bin:/home/brett/bin \
  /usr/bin/gcc -U_FORTIFY_SOURCE '-D_FORTIFY_SOURCE=1' -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 -DNDEBUG -ffunction-sections -fdata-sections -g0 '-std=c++0x' -iquote . -iquote bazel-out/host/genfiles -iquote external/bazel_tools -iquote bazel-out/host/genfiles/external/bazel_tools -isystem google/protobuf/src -isystem bazel-out/host/genfiles/google/protobuf/src -isystem external/bazel_tools/tools/cpp/gcc3 -DHAVE_PTHREAD -Wall -Wwrite-strings -Woverloaded-virtual -Wno-sign-compare '-Wno-error=unused-function' -no-canonical-prefixes -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' '-frandom-seed=bazel-out/host/bin/google/protobuf/_objs/protobuf/google/protobuf/src/google/protobuf/compiler/parser.o' -MD -MF bazel-out/host/bin/google/protobuf/_objs/protobuf/google/protobuf/src/google/protobuf/compiler/parser.d -c google/protobuf/src/google/protobuf/compiler/parser.cc -o bazel-out/host/bin/google/protobuf/_objs/protobuf/google/protobuf/src/google/protobuf/compiler/parser.o).
Target //tensorflow/tools/pip_package:build_pip_package failed to build
INFO: Elapsed time: 0.925s, Critical Path: 0.50s
```

**Comment by hartsantler** [comment]
just pulled the latest source and now getting this error:
```bash
INFO: From Compiling google/protobuf/src/google/protobuf/io/zero_copy_stream.cc [for host]:
google/protobuf/src/google/protobuf/io/zero_copy_stream.cc:35:49: fatal error: google/protobuf/io/zero_copy_stream.h: No such file or directory
compilation terminated.
ERROR: /home/brett/tensorflow/google/protobuf/BUILD:29:1: C++ compilation of rule '//google/protobuf:protobuf_lite' failed: gcc failed: error executing command /usr/bin/gcc -U_FORTIFY_SOURCE '-D_FORTIFY_SOURCE=1' -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 -DNDEBUG -ffunction-sections ... (remaining 36 argument(s) skipped).
Target //tensorflow/tools/pip_package:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 87.105s, Critical Path: 6.22s
```

**Comment by futurely** [comment]
Bazel is really the top blocker to most users who use CMake or make.

**Comment by futurely** [comment]
"We’ve found 84 issues" out of 443 issues.
https://github.com/tensorflow/tensorflow/search?q=bazel&type=Issues&utf8=%E2%9C%93

**Comment by hartsantler** [comment]
not sure why we even have to deal with bazel in the first place, when cmake is already a great platform independent build tool.  is this just Google trying to get us to beta test its new toy Bazel?

**Comment by blue-programmer** [comment]
Sounds like Google trying us all for something however bazel it is good platform as you say would be shame to change it 
 
 
  On Wed, 9 Dec, 2015 at 1:24 AM, Angry Lion<notifications@github.com> wrote:   
not sure why we even have to deal with bazel in the first place, when cmake is already a great platform independent build tool. is this just Google trying to get us to beta test its new toy Bazel?

**Comment by vrv** [comment]
If someone out there wants to work on CMake support for TensorFlow, I think we would welcome it as a contribution to our repo (so bazel and CMake would be options.).

If anyone has the time to help us out, maybe send an email out to the discuss mailing list and all interested parties can collaborate.

**Comment by blue-programmer** [comment]
I can do it please do give me more details and I can program it for you guys 
 
 
  On Wed, 9 Dec, 2015 at 1:49 AM, Vijay Vasudevan<notifications@github.com> wrote:   
If someone out there wants to work on CMake support for TensorFlow, I think we would welcome it as a contribution to our repo (so bazel and CMake would be options.).

If anyone has the time to help us out, maybe send an email out to the discuss mailing list and all interested parties can collaborate.

**Comment by martinwicke** [comment]
There are a number of files generated using protobuf (from .proto files),
but I'm pretty sure that's supported out of the box by cmake. There are
also build rules for Cuda files (using nvcc), which may be a fairly rare
use case, but also shouldn't be a huge problem. Finally, we are using swig
to wrap C++ code in python. The rest is just building c++ and copying
things to the right places.

In all, it's not a simple project to convert, but all that's necessary is
contained in the BUILD files (and the bazel docs).

Since cmake would help with a lot of platform issues (Windows support,
embedded support, etc.), we are more than happy to help, and we'd be very
excited about contributions in this area.

**Comment by futurely** [comment]
Most of the similar requirements to use CMake have already been solved in [Caffe](https://github.com/BVLC/caffe).

**Comment by vrv** [comment]
Closing for now -- it sounds like most of the issues are unrelated to TensorFlow and all related to bazel, and we should redirect discussion / effort around an alternative build system there.

**Comment by yazabaza** [comment]
Example Tensorflow convolutional code (e.g. https://github.com/tensorflow/tensorflow/blob/master/tensorflow/models/image/mnist/convolutional.py) does not run with the binary installed version and instead apparently requires buildng from source. See https://github.com/tensorflow/tensorflow/issues/1235. How do we build from source given this issue?

**Comment by martinwicke** [comment]
Can someone verify that the supported build process does not work for them with a recent version of tensorflow and bazel? It is true that master does sometimes break, and there's usually no need to build from master. Checking out r0.7 and building that should not cause any trouble.

Also, we do have a nascent (and currently broken) cmake build (in contrib/cmake), if anyone is interested in contributing to it, we'd welcome that.

**Comment by evolu8** [comment]
I just tried following the build from source instructions here:
https://www.tensorflow.org/versions/r0.7/get_started/os_setup.html#create-the-pip-package-and-install

And got the bower error. Please advise.

**Comment by martinwicke** [comment]
@danmane can you take a look?

**Comment by danmane** [comment]
@evolu8: I believe the bower error is an issue with the connection between GitHub and bazel being flakey, and bazel not retrying on network failure. Can you try installing again and see if it still fails?
