### ISSUE TITLE
Memory leak when append predictions to list

### ISSUE THREAD

**Issue by kindernerd** [tensorflow/tensorflow#34606]
When append prediction tensors to list, gpu memory will gradually increase, the occupied memory (model memory) will not be released (even when move the model prediction in @tf.function)
```
for data in dataset:
    pred = model(...)
    preds.append(pred)
```
this works as expected
```
for data in dataset:
  pred = model(...)
  preds.append(np.array(pred))
```

**Comment by gadagashwini** [comment]
@kindernerd, Please provide the complete standalone code to analyze the reported issue and also mention Tensorflow version. Thanks!

**Comment by gadagashwini** [comment]
@kindernerd, Could you elaborate your issue by providing complete code.Thanks

**Comment by gadagashwini** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
