### ISSUE TITLE
How to quickly add extract_image_patch op support in tflite?

### ISSUE THREAD

**Issue by siju-samuel** [tensorflow/tensorflow#34604]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):Ubuntu 18.04
- TensorFlow installed from (source or binary):Source
- TensorFlow version (or github SHA if from source):1.14

**Command used to run the converter or code if you’re using the Python API**

```
import tensorflow as tf
saved_model_dir="./"
converter = tf.lite.TFLiteConverter.from_saved_model(saved_model_dir)
converter.target_ops = [tf.lite.OpsSet.TFLITE_BUILTINS,
                                       tf.lite.OpsSet.SELECT_TF_OPS]
#converter.allow_custom_ops=True
tflite_model = converter.convert()
open("./converted_model.tflite", "wb").write(tflite_model)
```

**The output from the converter invocation**

```
Some of the operators in the model are not supported by the standard TensorFlow Lite runtime and are not recognized by TensorFlow. If you have a custom implementation for them you can disable this error with --allow_custom_ops, or by setting allow_custom_ops=True when calling tf.lite.TFLiteConverter(). Here is a list of builtin operators you are using: ADD, CAST, CONCATENATION, CONV_2D, DIV, ELU, LOGISTIC, MAXIMUM, MINIMUM, MUL, RELU, RESHAPE, RESIZE_NEAREST_NEIGHBOR, REVERSE_V2, SOFTMAX, SPLIT, SQRT, SQUARE, STRIDED_SLICE, SUM, TANH, TRANSPOSE, TRANSPOSE_CONV. Here is a list of operators for which you will need custom implementations: ExtractImagePatches.
Traceback (most recent call last):
  File "/home/siju/.local/bin/toco_from_protos", line 8, in <module>
    sys.exit(main())
  File "/home/siju/.local/lib/python3.6/site-packages/tensorflow/lite/toco/python/toco_from_protos.py", line 59, in main
    app.run(main=execute, argv=[sys.argv[0]] + unparsed)
  File "/home/siju/.local/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/home/siju/.local/lib/python3.6/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/home/siju/.local/lib/python3.6/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "/home/siju/.local/lib/python3.6/site-packages/tensorflow/lite/toco/python/toco_from_protos.py", line 33, in execute
    output_str = tensorflow_wrap_toco.TocoConvert(model_str, toco_str, input_str)
Exception: We are continually in the process of adding support to TensorFlow Lite for more ops. It would be helpful if you could inform us of how this conversion went by opening a github issue at https://github.com/tensorflow/tensorflow/issues/new?template=40-tflite-op-request.md
 and pasting the following:

Some of the operators in the model are not supported by the standard TensorFlow Lite runtime and are not recognized by TensorFlow. If you have a custom implementation for them you can disable this error with --allow_custom_ops, or by setting allow_custom_ops=True when calling tf.lite.TFLiteConverter(). Here is a list of builtin operators you are using: ADD, CAST, CONCATENATION, CONV_2D, DIV, ELU, LOGISTIC, MAXIMUM, MINIMUM, MUL, RELU, RESHAPE, RESIZE_NEAREST_NEIGHBOR, REVERSE_V2, SOFTMAX, SPLIT, SQRT, SQUARE, STRIDED_SLICE, SUM, TANH, TRANSPOSE, TRANSPOSE_CONV. Here is a list of operators for which you will need custom implementations: ExtractImagePatches.
```

**Also, please include a link to the saved model or GraphDef**

[saved_model.zip](https://github.com/tensorflow/tensorflow/files/3890254/saved_model.zip)

**Failure details**
I want to implement a block of contextual attenuation which contains op
[extract image patches](https://www.tensorflow.org/api_docs/python/tf/image/extract_patches)
This op is not the first/last one. its in the middle so that i cannot do the processing outside the model.

**Any other info / logs**
NO

**Comment by siju-samuel** [comment]
@gbaned Could you please help to assign one person to help me add this as a custom op?

**Comment by gbaned** [comment]
> @gbaned Could you please help to assign one person to help me add this as a custom op?

Sure @siju-samuel  Thanks!

**Comment by siju-samuel** [comment]
@haozha111 any help is appreciated!
i implemented as custom operator and now im facing another issue.

output shape of extract_image_patch is 1, 64, 85, 1536
Next layer after extract_image_patch is reshape new_shape=[1,-1,4,4,96], where this error is coming.

```
ERROR: tensorflow/lite/kernels/reshape.cc:66 num_input_elements != num_output_elements (1 != 0)
ERROR: Node number 150 (RESHAPE) failed to prepare.
```
Its quite a long time. please help!!

**Comment by butterfly-coder** [comment]
Hi, @siju-samuel 
I've faced the same problem. Could you share the way to solve the problem?

**Comment by siju-samuel** [comment]
You can try adding as a builtin-op instead of custom op.

**Comment by butterfly-coder** [comment]
Hi, @siju-samuel 
Thanks for your fast reply.
I tried with it before, but there wasn't ExtractImagePatches ops in builtin-op list.
Could you please explain how to add it as a builin-op?

**Comment by dragen1860** [comment]
@siju-samuel Hi, I facing the same problem when export DeepFill models. Haved you solved this problem, looking forward to chat with you!

**Comment by siju-samuel** [comment]
It was quite some time back.
First i tried to implement ExtractImagePatches from the eigen. eigen already have api to support ExtractImagePatches.  You can add as a op in lite. For reference you can use [this](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/kernels/extract_image_patches_op.h) .

Eigen impl [link](https://github.com/libigl/eigen/blob/1f05f51517ec4fd91eed711e0f89e97a7c028c0e/unsupported/Eigen/CXX11/src/Tensor/TensorImagePatch.h#L151)

But for me there were some other issues as well. So i abandoned this method and i splitted the tflite graph into two and i did ExtractImagePatches outside tflite network.

I strongly feel tflite must add support for this op. If its in middle of network, its difficult to process.

**Comment by dragen1860** [comment]
@siju-samuel Thanks for your update!
yes, ExtraImagePatches op is really important! I hold the same opinion with you!

**Comment by tianye2856** [comment]
Hi
Does tflite support ExtraImagePatches op now?

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.
