### ISSUE TITLE
Build a static tensorflow on Alpine linux 

### ISSUE THREAD

**Issue by stereomatchingkiss** [tensorflow/tensorflow#34612]
Any instructions, documents or blogs show us how to build static library of tensorflow on Alpine linux? I want to port the object detection model(and other) to aws lambda, build tensorflow as a static library could save a lot of troubles

**Comment by Saduf2019** [comment]
@stereomatchingkiss 
Could you please try on latest stable version of tf and let us know if this is still an issue.Thanks!
