### ISSUE TITLE
ValueError: model_fn (<tensorflow.python.eager.def_function.Function object at 0x7f0391abc4a8>) must include features argument.

### ISSUE THREAD

**Issue by muhammadfahid51** [tensorflow/tensorflow#34617]
I have been trying to solve this for 5 hours but to no avails. Kindly help if any of you have solved this. I have renamed all the variable accordingly but it still says, value error. I can share my code with you if you want. 
I am using **Tensorflow 2.0**

**Comment by nikochiko** [comment]
@muhammadfahid51 , please share your code. Preferable as a Google Colab gist and please follow the issue template given.

**Comment by muhammadfahid51** [comment]
> @muhammadfahid51 , please share your code, preferably as a Google Colab gist.

nikochiko here is my code,


import tensorflow as tf
import numpy as np

from tensorflow.keras.datasets import mnist


@tf.function
def model_fn(features, labels, mode, params):
    img = tf.keras.layers.Input(features, shape=(28, 28, 1))
    img = tf.keras.layers.Conv2D(32, (3, 3), activation="relu")(img)
    img = tf.keras.layers.MaxPool2D((2, 2), 2)(img)
    img = tf.keras.layers.Conv2D(64, (3, 3), activation="relu")(img)
    img = tf.keras.layers.MaxPool2D((2, 2), 2)(img)
    img = tf.keras.layers.Conv2D(64, (3, 3), activation="relu")(img)
    img = tf.keras.layers.Flatten()(img)
    img = tf.keras.layers.Dense(units=256, activation="relu")(img)
    img = tf.keras.layers.Dense(units=128, activation="relu")(img)
    logits = tf.keras.layers.Dense(units=10, activation=None)(img)

    probs = tf.nn.softmax(logits)
    predicted_classes = tf.argmax(probs, 1)

    loss = tf.losses.sparse_categorical_crossentropy(labels, logits)

    acc = tf.metrics.Accuracy(labels, predicted_classes)
    metrics = {"accuracy": acc}
    tf.summary.scaler('accuracy', acc[1])

    if mode == tf.estimator.ModeKeys.EVAL:
        return tf.estimator.EstimatorSpec(mode,
                                          loss=loss, eval_metric_ops=metrics)

    assert mode == tf.estimator.ModeKeys.TRAIN

    optimizer = tf.keras.optimizers.Adam(learning_rate=0.001)
    train_op = optimizer.minimize(loss)
    return tf.estimator.EstimatorSpec(mode,
                                      loss=loss, train_op=train_op)


def load_mnist():
    train, test = mnist.load_data()
    return train, test


def train_input_fn(features, labels, batch_size):
    dataset = tf.data.Dataset.from_tensor_slices((features, labels))
    dataset = dataset.shuffle(500)
    dataset = dataset.repeat().batch(batch_size)
    return dataset


def eval_input_fn(imgs, labels, batch_size):
    dataset = tf.data.Dataset.from_tensor_slices((imgs, labels))
    dataset = dataset.batch(batch_size)
    return dataset


def main(m_dir=None):
    (x_train, y_train), (x_test, y_test) = load_mnist()
    classifier = tf.estimator.Estimator(model_fn=model_fn,
                                        params=['features', 'labels', 'mode', 'params', 'self', 'config'])


main()

**Comment by nikochiko** [comment]
@muhammadfahid51 , TensorFlow is unable to recognize the arguments included in `model_fn` due to the  `@tf.function` wrapper.  You need to remove the it. See [gist](https://colab.research.google.com/gist/nikochiko/c3e8173b553510106753e5f9fe4f8b3a/untitled34.ipynb)

**Comment by muhammadfahid51** [comment]
Thanks a lot bro. Thanks a LOT

**Comment by muhammadfahid51** [comment]
> Thanks a lot bro. Thanks a LOT

`

**Comment by muhammadfahid51** [comment]
> Thanks a lot bro. Thanks a LOT



> @muhammadfahid51 , TensorFlow is unable to recognize the arguments included in `model_fn` due to the `@tf.function` wrapper. You need to remove the it. See [gist](https://colab.research.google.com/gist/nikochiko/c3e8173b553510106753e5f9fe4f8b3a/untitled34.ipynb)

TypeError: minimize() missing 1 required positional argument: 'var_list'


Here is my code, Can you solve this bro. I don't know what to put there,

import tensorflow as tf

from tensorflow.keras.datasets import mnist


def model_fn(features, labels, mode, params):
    features = tf.cast(features, dtype=tf.float32)
    print(features.dtype)
    img = tf.keras.layers.Conv2D(32, (3, 3), activation="relu")(features)
    img = tf.keras.layers.MaxPool2D((2, 2), 2)(img)
    img = tf.keras.layers.Conv2D(64, (3, 3), activation="relu")(img)
    img = tf.keras.layers.MaxPool2D((2, 2), 2)(img)
    img = tf.keras.layers.Conv2D(64, (3, 3), activation="relu")(img)
    img = tf.keras.layers.Flatten()(img)
    img = tf.keras.layers.Dense(units=256, activation="relu")(img)
    img = tf.keras.layers.Dense(units=128, activation="relu")(img)
    logits = tf.keras.layers.Dense(units=10, activation=None)(img)

    probs = tf.keras.activations.softmax(logits)
    predicted_classes = tf.argmax(probs, 1)

    loss = tf.keras.losses.sparse_categorical_crossentropy(labels, probs)

    acc = tf.compat.v1.metrics.accuracy(labels, predicted_classes)
    metrics = {"accuracy": acc}
    tf.summary.scalar("accuracy", acc[1])

    if mode == tf.estimator.ModeKeys.EVAL:
        return tf.estimator.EstimatorSpec(mode,
                                          loss=loss, eval_metric_ops=metrics)

    assert mode == tf.estimator.ModeKeys.TRAIN

    optimizer = tf.keras.optimizers.Adagrad(learning_rate=0.001)
    train_op = optimizer.minimize(loss)
    return tf.estimator.EstimatorSpec(mode,
                                      loss=loss, train_op=train_op)


def load_mnist():
    train, test = mnist.load_data()
    return train, test


def train_input_fn(features, labels, batch_size):
    # features = tf.convert_to_tensor(features, dtype=tf.float32)
    # labels = tf.convert_to_tensor(labels, dtype=tf.int32)
    dataset = tf.data.Dataset.from_tensor_slices((features, labels))
    dataset = dataset.shuffle(500)
    dataset = dataset.repeat().batch(batch_size)
    return dataset


def eval_input_fn(imgs, labels, batch_size):
    dataset = tf.data.Dataset.from_tensor_slices((imgs, labels))
    dataset = dataset.batch(batch_size)
    return dataset


def main(m_dir=None):
    (x_train, y_train), (x_test, y_test) = load_mnist()
    x_train = x_train.reshape(60000, 28, 28, 1)
    x_test = x_test.reshape(10000, 28, 28, 1)
    classifier = tf.estimator.Estimator(model_fn=model_fn, model_dir=m_dir)

    classifier.train(input_fn=lambda: train_input_fn(x_train, y_train, 500), steps=100)


if __name__ == "__main__":
    main()

**Comment by nikochiko** [comment]
@muhammadfahid51 , please open another issue and feel free to tag me there. Please keep the issue comments related. Also, enclose all of your code in one ``` codeblock.
