### ISSUE TITLE
Support exporting the transform graph from tf.Transform together with the model graph defined using Keras to SavedModel in TensorFlow 2.0

### ISSUE THREAD

**Issue by brightcoder01** [tensorflow/tensorflow#34618]
**System information**
- TensorFlow version (you are using): TensorFlow 2.0
- Are you willing to contribute it (Yes/No): Yes

**Describe the feature and the current behavior/state.**
The feature is:  improve `tf.saved.saved_model` Api in Keras and support exporting the transform graph from tf.Transform and the graph from the Keras model together into a single SavedModel.

**Current behavior/state** about how to export transform graph and model graph together to a SavedModel?  
Estimator (Work well):  
From [tf.transform official tutorial](https://github.com/tensorflow/transform/blob/cf517f1a8765e6552d09cee65efea80e26c05f5e/examples/census_example.py#L380-L382), at the stage of exporting model, it will call [estimator.export_saved_model(exported_model_dir, serving_input_fn)](https://github.com/tensorflow/estimator/blob/b22a912de2693322622d6f50e3a19e98fecac441/tensorflow_estimator/python/estimator/estimator.py#L661) to complete the model exporting work. Inside its implementation, it calls serving_input_fn to load the transform graph from SavedModel at first, and then calls estimator's model_fn to generate the model graph, combines these two graph into one graph and finally exports it into one SavedModel. Please check the [code snippet](https://github.com/tensorflow/estimator/blob/43921b4552d1c30acc31d3b5989112cb397383e0/tensorflow_estimator/python/estimator/estimator.py#L926-L937).  

Keras (Can not):  
For TF2.0, we define a model using keras and exports it by calling [tf.saved.saved_model](https://www.tensorflow.org/api_docs/python/tf/saved_model/save). This SavedModel only contains the model definition including feature columns and network structure. `tf.saved.saved_model` api doesn't have the parameter `serving_input_fn` just like estimator and **it lacks the flexibility to combine transform graph and model graph together for inference**.

**Will this change the current api? How?**
Will change the Api `tf.saved.save_model`, add a new parameter `serving_input_fn`.

**Who will benefit with this feature?**
The users of tf.Transform and TensorFlow 2.0

**Any Other info.**

**Comment by rmothukuru** [comment]
The same question has been asked in [Tensorflow Transform](https://github.com/tensorflow/transform/issues/150) Repository as well.

**Comment by brightcoder01** [comment]
Hi, @rmothukuru and @k-w-w , can you please share more information about this issue?

**Comment by rmothukuru** [comment]
@brightcoder01,
Can you please let us know if [this comment](https://github.com/tensorflow/transform/issues/150#issuecomment-694769276) has resolved your issue? Thanks!
