### ISSUE TITLE
遇到ValueError: Invalid tensors 'input/input_data:0' were found.

### ISSUE THREAD

**Issue by 774219268** [tensorflow/tensorflow#34614]
遇到ValueError: Invalid tensors 'input/input_data:0' were found.
同样问题，请问有谁解决了吗？帮我， 'input/input_data:0' 是我测试pb模型是的输入变量名，但是转tflite时，报上述错误。谢谢。。。

**Comment by gadagashwini** [comment]
I apologize, but I am having a hard time understanding what the problem is, where the problem is, and what version it affects. Please resubmit and pay attention to the issue template (https://github.com/tensorflow/tensorflow/issues/new/choose). Please provide all the information it asks. Thank you.
