### ISSUE TITLE
Fold ADD with TRANSPOSECONV in tflite converter.

### ISSUE THREAD

**Issue by psunn** [tensorflow/tensorflow#34622]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

- This is a feature request and also relative to performance issue.

**System information**
- TensorFlow version (you are using):
tf-nightly '2.1.0-dev20191126'
- Are you willing to contribute it (Yes/No):
Yes

**Describe the feature and the current behavior/state.**
For generating _.tflite_ file with [_TFLiteConverter_](https://www.tensorflow.org/api_docs/python/tf/lite/TFLiteConverter), when model contains [_Conv2DTranspose_](https://www.tensorflow.org/api_docs/python/tf/keras/layers/Conv2DTranspose) layers, bias cannot fold into Operator TRANSPOSECONV. It will result with extra Op ADD following Op TRANSPOSECONV.
But with other CONV-like layers (Conv2D, DepthwiseConv2D), bias will be fold into CONV layer.

- [ ] **bias should fold into Op TRANSPOSECONV in tflite.**

Reproduce current behaviors with example code and model graph:
```
def get_keras_model():
    input_0 = tf.keras.layers.Input(shape=[100,100,3])
    # Conv2D with bias
    conv_0 = tf.keras.layers.Conv2D(filters=3, kernel_size=[3, 3],
                                    use_bias=True, padding="same",
                                    kernel_initializer=tf.random_uniform_initializer,
                                    bias_initializer=tf.random_uniform_initializer)(input_0)
    # Conv2D without bias
    conv_1 = tf.keras.layers.Conv2D(filters=3, kernel_size=[3, 3],
                                    use_bias=False, padding="same",
                                    kernel_initializer=tf.random_uniform_initializer)(conv_0)
    # DepthwiseConv2D with bias
    depthwise_conv_0 = tf.keras.layers.DepthwiseConv2D(kernel_size=[3, 3],
                                                       use_bias=True, padding="same",
                                                       kernel_initializer=tf.random_uniform_initializer,
                                                       bias_initializer=tf.random_uniform_initializer)(conv_1)
    # DepthiseConv2D without bias
    depthwise_conv_1 = tf.keras.layers.DepthwiseConv2D(kernel_size=[3, 3],
                                                       use_bias=False, padding="same",
                                                       kernel_initializer=tf.random_uniform_initializer)(depthwise_conv_0)
    # TrasposeConv with bias
    transpose_conv_0 = tf.keras.layers.Conv2DTranspose(filters=3, kernel_size=[3,3],
                                                       use_bias=True, padding="same",
                                                       kernel_initializer=tf.random_uniform_initializer,
                                                       bias_initializer=tf.random_uniform_initializer)(depthwise_conv_1)
    # TrasposeConv without bias
    transpose_conv_1 = tf.keras.layers.Conv2DTranspose(filters=3, kernel_size=[3, 3],
                                                       use_bias=False, padding="same",
                                                       kernel_initializer=tf.random_uniform_initializer)(transpose_conv_0)

    keras_model = tf.keras.models.Model(inputs=[input_0], outputs=[transpose_conv_1])

    return keras_model


def gen_tflite():

    keras_model = get_keras_model()
    keras_model.compile(loss=tf.keras.losses.categorical_crossentropy,
                        optimizer='adam',
                        metrics=['accuracy'])
    converter = tf.lite.TFLiteConverter.from_keras_model(keras_model)
    tflite_quant_model = converter.convert()
    open('conv.tflite', 'wb').write(tflite_quant_model)

gen_tflite()
```
As the graph below shows, _TFLiteConverter_ will fold bias with Conv2D and Depthwise2D, but not fold bias with TransposeConv:
![image](https://user-images.githubusercontent.com/55463253/69658482-2f0f3d00-1074-11ea-944f-f46fe3723453.png)

**Will this change the current api? How?**

It will not affect any TF python api.
It will affect [tflite](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/kernels/transpose_conv.cc#L341) as bias added.

**Who will benefit with this feature?**

Users of TensorFlow, as 

- consistent implementation/behavior between conv-like layers

- Performance boost when tflite running on device, as TRANSPOSECONV + ADD folded into TRANSPOSECONV

**Any Other info.**
N/A

**Comment by psunn** [comment]
@liyunlu0618 Sorry to bother you, I saw your update with INT8 TRANSPOSE_CONV reference kernel.

Do you mind to have a look of this issue? I'm wondering why transpose_conv doesn't come with bias in tflite Op kernel. Meantime, conv and depthwise_conv does.

I'm trying to contribute regarding this issue, so that transpose_conv will has bias inside. And tflite graph transformer will behave the same for {conv, depthwise_conv, transpose_conv}, which fuse bias add with "conv" Op.

It will be very helpful if you can give some suggestions. Thanks.

**Comment by psunn** [comment]
@gadagashwini @haozha111 Hi guys, sorry to bother you. Can you give some suggestions?

**Comment by psunn** [comment]
Pull request [https://github.com/tensorflow/tensorflow/pull/34903](url) trying to resolve this issue.

**Comment by psunn** [comment]
thanks!

**Comment by anilsathyan7** [comment]
Is this issue resolved??
It does not seem to work in tf versions: 2.4.0-dev20200916, 2.3.0 !!!
An extra shape node seems to be created ...
