### ISSUE TITLE
Tutorial on basic classification needs some documentation improvement 

### ISSUE THREAD

**Issue by copperwiring** [tensorflow/tensorflow#34631]
Thank you for submitting a TensorFlow documentation issue. Per our GitHub
policy, we only address code/doc bugs, performance issues, feature requests, and
build/installation issues on GitHub.

The TensorFlow docs are open source! To get involved, read the documentation
contributor guide: https://www.tensorflow.org/community/contribute/docs

## URL(s) with the issue: 

Please provide a link to the documentation entry, for example:
https://www.tensorflow.org/tutorials/keras/classification/ 

## Description of issue (what needs changing):
One of the first step-by-step tutorial which explains a neural network is on Basic Classification [here](https://www.tensorflow.org/tutorials/keras/classification/). However, it can benefit from additional explanations on few terms like overfitting, optimizer etc.  

### Clear description
We add one line description for *overfitting*  to help user get a first hand idea of what *overfitting* does. Later, we add an extra line with a link to TensorFlow definition of overfit where user can find more information. The suggested changes  are expected to make it easier for users to get an intuitive understanding of the term.

### Correct links

Is the link to the source code correct? Yes

### Submit a pull request? 

Yes.

Are you planning to also submit a pull request to fix the issue? See the docs
contributor guide: https://www.tensorflow.org/community/contribute/docs,
docs API guide: https://www.tensorflow.org/community/contribute/docs_ref and the
docs style guide: https://www.tensorflow.org/community/contribute/docs_style

**Comment by lamberta** [comment]
Thanks @copperwiring , do you have a pull request in the works for this? Please link when ready for review

**Comment by copperwiring** [comment]
Oh! Yes. I missed this. I'll send a PR in a few days. Thanks Billy!

**Comment by ManishAradwad** [comment]
Can i take this one plz??

**Comment by copperwiring** [comment]
Hi @ManishAradwad Please go ahead and work on it. It'll take me some time to pick up this issue. If needed, I can help you later in the documentation improvement process. Thanks!

CC: @8bitmp3

**Comment by ManishAradwad** [comment]
Thanks, Srishti!!

**Comment by jvishnuvardhan** [comment]
This was already resolved by the https://github.com/tensorflow/docs/pull/1347 Thanks to @ManishAradwad 

As this is already reflecting in the TF website, I am closing this issue. Thanks!
