### ISSUE TITLE
Contribution guideline for Interative Notebook needs to be modified.

### ISSUE THREAD

**Issue by copperwiring** [tensorflow/tensorflow#34639]
Thank you for submitting a TensorFlow documentation issue. Per our GitHub
policy, we only address code/doc bugs, performance issues, feature requests, and
build/installation issues on GitHub.

The TensorFlow docs are open source! To get involved, read the documentation
contributor guide: https://www.tensorflow.org/community/contribute/docs

## URL(s) with the issue:

Please provide a link to the documentation entry, for example:
https://www.tensorflow.org/community/contribute/docs 

## Description of issue (what needs changing):
Documentation under "Interactive notebooks" needs to be modified to accommodate issues created after direct editing of Jupyter Notebook in Colab.
  

### Clear description. 

Direct editing (on colab or using VSCode) Jupyter Notebook and committing as mentioned [here](https://www.tensorflow.org/community/contribute/docs) adds additional unintended changes like prettifying and escapes unicode symbols. 

For example, see here: https://github.com/tensorflow/docs/pull/1238 

Related code commit : https://github.com/copperwiring/docs/commit/98f35604617d1ecc93b3dc75ac6ec4ab108536eb 

### Correct links

Yes

### Parameters defined

N/A

### Returns defined

N/A

### Raises listed and defined

None.

### Usage example

It is useful and needed for any PR request for Jupyter Notebook

### Request visuals, if applicable

N/A

### Submit a pull request?

I am planning to submit a PR to improve the documentation.

**Comment by lamberta** [comment]
Thanks, @copperwiring 

Unfortunately this is WAI since there are serialization differences between Colab versions. This is being tracked in an internal ticket (b/123414970)

cc: @csemike @corrieann
