### ISSUE TITLE
when set CollectiveCommunication NCCL, the train is stucking

### ISSUE THREAD

**Issue by zwqjoy** [tensorflow/tensorflow#34638]
System information

    Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
    OS Platform and Distribution: Ubuntu 18.04
    TensorFlow installed from (source or binary): pip install tensorflow-gpu
    TensorFlow version (use command below): 2.0
    Python version: 3.6.9
    CUDA/cuDNN version: 10/7.6.4.38
    GPU model and memory: Tesla P4  8G

Describe the current behavior
I  run the code described below:

**TEST 1:   (two machine)**

os.environ['TF_CONFIG'] = json.dumps({
    'cluster': {
        'worker': ["server1:12345", "server2:12345"]
    },
    'task': {'type': 'worker', 'index': 0}
})

In the other machine

os.environ['TF_CONFIG'] = json.dumps({
    'cluster': {
        'worker': ["server1:12345", "server2:12345"]
    },
    'task': {'type': 'worker', 'index': 1}
})

When the script start processing the first epoch it crashes,

**Describe the expected behavior**

15s/epoch  is so slow

<img width="1162" alt="图片" src="https://user-images.githubusercontent.com/12653212/69707374-942a6780-1134-11ea-8dd1-994fd7e41451.png">

**TEST 2:   (one machine)**

os.environ['TF_CONFIG'] = json.dumps({
    'cluster': {
        'worker': ["server1:12345"]
    },
    'task': {'type': 'worker', 'index': 0}
})

**Describe the expected behavior**

5s/epoch      same as use  strategy = tf.distribute.MirroredStrategy()  one GPU card

<img width="1072" alt="图片" src="https://user-images.githubusercontent.com/12653212/69707387-9b517580-1134-11ea-976a-73c9d36fdc2b.png">

**CODE**

```
import ssl

ssl._create_default_https_context = ssl._create_unverified_context
import os
import json

import tensorflow as tf
import tensorflow_datasets as tfds

import argparse


def configure_cluster(worker_hosts=None, task_index=-1):
    """Set multi-worker cluster spec in TF_CONFIG environment variable.
    Args:
      worker_hosts: comma-separated list of worker ip:port pairs.
    Returns:
      Number of workers in the cluster.
    """
    tf_config = json.loads(os.environ.get('TF_CONFIG', '{}'))
    if tf_config:
        num_workers = len(tf_config['cluster'].get('worker', []))
    elif worker_hosts:
        workers = worker_hosts.split(',')
        num_workers = len(workers)
        if num_workers > 1 and task_index < 0:
            raise ValueError('Must specify task_index when number of workers > 1')
        task_index = 0 if num_workers == 1 else task_index
        os.environ['TF_CONFIG'] = json.dumps({
            'cluster': {
                'worker': workers
            },
            'task': {'type': 'worker', 'index': task_index}
        })
    else:
        num_workers = 1
    return num_workers


parser = argparse.ArgumentParser(description='TensorFlow Benchmark',
                                 formatter_class=argparse.ArgumentDefaultsHelpFormatter)
parser.add_argument('--num-epochs', type=int, default=5, help='input batch size')
parser.add_argument('--batch-size-per-replica', type=int, default=64, help='input batch size')
parser.add_argument('--worker-hosts', type=str, default=None)
parser.add_argument('--worker-index', type=int, default=0)

args = parser.parse_args()

worker_num = configure_cluster(args.worker_hosts, args.worker_index)
batch_size = args.batch_size_per_replica * worker_num
print('Batch Size: %d' % batch_size)

gpus = tf.config.experimental.list_physical_devices('GPU')
print("Physical GPU Devices Num:", len(gpus))
for gpu in gpus:
    tf.config.experimental.set_memory_growth(gpu, True)

strategy = tf.distribute.experimental.MultiWorkerMirroredStrategy(
    communication=tf.distribute.experimental.CollectiveCommunication.RING)

def resize(image, label):
    image = tf.image.resize(image, [128, 128]) / 255.0
    return image, label


# if as_supervised is True，return image abd label
dataset, info = tfds.load("tf_flowers", split=tfds.Split.TRAIN, with_info=True, as_supervised=True)
dataset = dataset.map(resize).repeat().shuffle(1024).batch(batch_size)
total_num_examples = 3670

with strategy.scope():
    model = tf.keras.Sequential([
        tf.keras.layers.Conv2D(32, [3, 3], activation='relu'),
        tf.keras.layers.Conv2D(64, [3, 3], activation='relu'),
        tf.keras.layers.MaxPooling2D(pool_size=(2, 2)),
        tf.keras.layers.Dropout(0.25),
        tf.keras.layers.Flatten(),
        tf.keras.layers.Dense(128, activation='relu'),
        tf.keras.layers.Dropout(0.5),
        tf.keras.layers.Dense(info.features['label'].num_classes, activation='softmax')
    ])
    model.compile(
        optimizer=tf.optimizers.Adam(learning_rate=0.001),
        loss=tf.keras.losses.sparse_categorical_crossentropy,
        metrics=[tf.keras.metrics.sparse_categorical_accuracy]
    )

model.fit(dataset, steps_per_epoch=total_num_examples // batch_size, epochs=args.num_epochs)


```

In TEST 2:    only 1 worker,   5s/epoch ~ 6s/epoch  （batch_szie = 128）

In TEST 1:  2 workers,     15s/epoch  ~ 19s/epoch  （per_batch_szie = 64, batch_size = 64 *2 = 128）

**Question1:** 
So, I cannot understand,  with dist MultiWorkerMirroredStrategy  worker nums > 1,  
why Training is so slow

**Question2:**
when I  set   strategy = tf.distribute.experimental.MultiWorkerMirroredStrategy(
    communication=tf.distribute.experimental.CollectiveCommunication.NCCL) 

In TEST 1:  2 workers,  the training will stuck  in epoch 2,   epoch 1 done.

<img width="1185" alt="图片" src="https://user-images.githubusercontent.com/12653212/69708066-e750ea00-1135-11ea-9bb4-362340737b76.png">

**Comment by byronyi** [comment]
@zwqjoy Try setting your environment with `NCCL_DEBUG=INFO` and please send us the output log.

**Comment by zwqjoy** [comment]
> @zwqjoy Try setting your environment with `NCCL_DEBUG=INFO` and please send us the output log.

![图片](https://user-images.githubusercontent.com/12653212/69783404-6ace1200-11ee-11ea-9592-9a6e4ee26b1b.png)


![图片](https://user-images.githubusercontent.com/12653212/69783386-61dd4080-11ee-11ea-9c3f-ba43c4b2069e.png)

**Comment by zwqjoy** [comment]
> @zwqjoy Try setting your environment with `NCCL_DEBUG=INFO` and please send us the output log.

And I see the NCCL Version is:   NCCL version 2.4.7+cudaCUDA_MAJOR.CUDA_MINOR

![图片](https://user-images.githubusercontent.com/12653212/69790962-74f80c80-11fe-11ea-909f-dd3844e4dd50.png)

but I use : https://github.com/nvIDIA/nccl
<img width="691" alt="图片" src="https://user-images.githubusercontent.com/12653212/69790998-850fec00-11fe-11ea-8509-9c94091298ef.png">

![图片](https://user-images.githubusercontent.com/12653212/69791050-a40e7e00-11fe-11ea-9972-12c7766dbf51.png)

**Comment by zwqjoy** [comment]
set NCCL_LL_THRESHOLD=0  it works.   


```

NCCL_LL_THRESHOLD

(since 2.1, removed in 2.5)

The NCCL_LL_THRESHOLD variable sets the size limit under which NCCL uses low-latency algorithms.
Values accepted

The default is 16384 (up to 2.2) or is dependent on the number of ranks (2.3 and later).

Values are integers, in bytes.

```

**Comment by zwqjoy** [comment]
set NCCL_LL_THRESHOLD=0, It works

**Comment by jiangxiaobin96** [comment]
Must I use build-in NCCL version? How to set latest NCCL?
