### ISSUE TITLE
Profiling with Tensorboard is unable to catch GPU operations

### ISSUE THREAD

**Issue by littlebeandog** [tensorflow/tensorflow#34633]
**System information**

- OS Platform and Distribution: Linux Ubuntu 16.04
- TensorFlow version (use command below):v2.0.0-rc2-26-g64c3d38 2.0.0
- Python version:3.7.3
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:10.2
- GPU : P40

**Describe the current behavior**
Following the description in doc, I use the code snippet below to profile model.
```python3
log_dir="logs/" + datetime.now().strftime("%Y%m%d-%H%M%S")
tensorboard_callback = tf.keras.callbacks.TensorBoard(log_dir=log_dir, histogram_freq=1, profile_batch = 3)

merge_model.fit(
    dataset, epochs=2, steps_per_epoch=100,
    validation_data=eval_dataset,
    validation_steps=66,
    validation_freq=1,
    callbacks=[tensorboard_callback]
)
```
But tensorboard callback only captured  cpu ops.
![image](https://user-images.githubusercontent.com/14145834/69692741-f459e300-110d-11ea-9391-e7900280ef96.png)

It's for sure that i'm using a gpu version tf and the device is used during training.

**Comment by ymodak** [comment]
I suspect your TF does not recognize gpu.  TF 2.0 pre built binary supports cuda 10.0. 
You may try printing;
```python
import tensorflow as tf
tf.test.is_gpu_available()
```
If prints ```False```, then switch to cuda 10.0 and update cuda,cupti, cudnn environment variables.

**Comment by tlkh** [comment]
Please do check the console output (in the Terminal window if you are using Jupyter) and see if TensorFlow reports that CUPTI is not found.

**Comment by littlebeandog** [comment]
> I suspect your TF does not recognize gpu. TF 2.0 pre built binary supports cuda 10.0.
> You may try printing;
> 
> ```python
> import tensorflow as tf
> tf.test.is_gpu_available()
> ```
> 
> If prints `False`, then switch to cuda 10.0 and update cuda,cupti, cudnn environment variables.
Hi, I think tf recognized gpu correctly, and gpu is utilized for training.
![image](https://user-images.githubusercontent.com/14145834/69933774-daa00d80-150a-11ea-8d42-c9bb2c578b64.png)
![image](https://user-images.githubusercontent.com/14145834/69933851-1c30b880-150b-11ea-8796-0d76327ddd32.png)

**Comment by littlebeandog** [comment]
> CUPTI

Thanks for reply, I do find log as you said. What should I do to fix?
```
2019-12-02 13:59:56.583464: E tensorflow/core/platform/default/device_tracer.cc:70] CUPTI error: CUPTI could not be loaded or symbol could not be found.
```

**Comment by littlebeandog** [comment]
> Please do check the console output (in the Terminal window if you are using Jupyter) and see if TensorFlow reports that CUPTI is not found.

Thanks for reply, I do find log as you said. What should I do to fix?

```
2019-12-02 13:59:56.583464: E tensorflow/core/platform/default/device_tracer.cc:70] CUPTI error: CUPTI could not be loaded or symbol could not be found.
```

**Comment by ravikyram** [comment]
@littlebeandog 
Please, let me know if we can close this issue since it looks to be fixed. Thanks!

**Comment by littlebeandog** [comment]
> @littlebeandog
> Please, let me know if we can close this issue since it looks to be fixed. Thanks!

Yes, problem solved, thanks.

**Comment by ravikyram** [comment]
I am closing the issue since the query is been resolved. Thanks!
