### ISSUE TITLE
Extract the element from the output list of tf.py_func when length 1

### ISSUE THREAD

**Issue by omoindrot** [tensorflow/tensorflow#3464]
`tf.py_func` could extract the element from the list when the length is 1.

In this example:

    def func(x):
        return 2*x

    x = tf.constant(1.)
    res = tf.py_func(func, [x], [tf.float32])

`res` is a list containing 1 Tensor. This can be confusing, because users expect to get only one tensor as output.

`tf.cond` handles this case well:
> **Returns:**
> Tensors returned by the call to either fn1 or fn2. If the callables return a singleton list, the element is extracted from the list.

**Comment by yaroslavvb** [comment]
Maybe it could be 
```
tf.py_func(func, [x], [tf.float32]) -> returns list of tf.float32
tf.py_func(func, [x], tf.float32) -> returns single tf.float32
```
This is similar to `session.run` which returns either list of numpy arrays or single numpy array depending on whether input is a list

**Comment by omoindrot** [comment]
That would work for me.

**Comment by concretevitamin** [comment]
We are unlikely to work on this soon, so marking as contributions welcome.  IMO @yaroslavvb's suggested behavior is saner than checking for the length of the result list.

**Comment by suiyuan2009** [comment]
dbs

**Comment by suiyuan2009** [comment]
op's attr can't be {type, list(type)}, so I suggest add a boolean to distinguish

**Comment by suiyuan2009** [comment]
@concretevitamin since attr can't be set as {type, list(type)}, if it's set as list(type), then this op will always return [...] instead of ... , I want to make C++ api and python api same as each other, I need help.

**Comment by TimZaman** [comment]
I think #3744 closes this one.
