### ISSUE TITLE
Use TPU on Colab shows:Session edefaa660de08d53 is not found.

### ISSUE THREAD

**Issue by x7night** [tensorflow/tensorflow#34648]
I want to use the tpu on colab to do some exercise. i follow the colab tutorial to use the tpu. i can run the example on tpu. but when i run a new  custom model, the console shows "Session edefaa660de08d53 is not found."
i don't know what mistake there is

**System information**
- env:   colab
- TensorFlow installed from (source or binary):  
- TensorFlow version (use command below): 1.15
- Python version: python3

**Describe the current behavior**
i download a data from internet on loacl storage. Then i read the data and convert it to the tfrecord,
And i bulid a custom model. i  use the tup like the tutorial shows.
But when i run model.fit(), the console shows this mistake.
how do i fix it?

**Code to reproduce the issue**
```python
filename = os.listdir(r'./tfrecord')
files = [os.path.join(r'./tfrecord', x) for x in filename]
dataset = tf.data.TFRecordDataset(files)
dataset = dataset.map(_parse_func)
dataset = dataset.shuffle(256)
dataset = dataset.batch(128,drop_remainder=True)

# define some custom layer, those layer made by Conv2D, Concat, softmax
# define the custom model

resolver = tf.contrib.cluster_resolver.TPUClusterResolver('grpc://' + os.environ['COLAB_TPU_ADDR'])
tf.contrib.distribute.initialize_tpu_system(resolver)
strategy = tf.contrib.distribute.TPUStrategy(resolver)

with strategy.scope():
    opt = tf.keras.optimizers.Adam()
    def rmse(y_true, y_pred):
        return tf.reduce_mean(tf.math.sqrt(tf.math.squared_difference(y_pred, y_true)))
    generator = generator_() # my custom model
    generator.compile(optimizer=opt, loss=tf.keras.metrics.MSE, metrics=[rmse])
model.fit()
```
the github gist to reproduce the problem is:
https://gist.github.com/x7night/45ba9eb08f568909bde0cc5f65050653
**Other info / logs**
Session edefaa660de08d53 is not found.

**Comment by gowthamkpr** [comment]
@x7night Can you please share a google colab gist reproducing this issue. Thanks!

**Comment by x7night** [comment]
> @x7night Can you please share a google colab gist reproducing this issue. Thanks!
does the gist like blow ? i just find the buttom to save the .ipynb as the github gist. the link is:
https://gist.github.com/x7night/45ba9eb08f568909bde0cc5f65050653

**Comment by x7night** [comment]
> @x7night Can you please share a google colab gist reproducing this issue. Thanks!
@gowthamkpr
does the gist like blow ? i just find the buttom to save the .ipynb as the github gist. the link is:
https://gist.github.com/x7night/45ba9eb08f568909bde0cc5f65050653

**Comment by gowthamkpr** [comment]
@x7night This is similar to the issue #32712. Please confirm, if thats the case we can track this in a single issue.

**Comment by x7night** [comment]
@gowthamkpr 
it seems like that. i get data from the TFRecordDataset, and i also get the mistake ' session not found' when i run model.fit()

**Comment by gowthamkpr** [comment]
I am gonna close this issue as it has already been tracked here #32712 @x7night. Please follow that issue and it should be resolved soon. Thanks!
