### ISSUE TITLE
TypeError: minimize() missing 1 required positional argument: 'var_list'

### ISSUE THREAD

**Issue by muhammadfahid51** [tensorflow/tensorflow#34645]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version (use command below): 2.0
- Python version:
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**

**Describe the expected behavior**

import tensorflow as tf

from tensorflow.keras.datasets import mnist

def model_fn(features, labels, mode, params):
    features = tf.cast(features, dtype=tf.float32)
    print(features.dtype)
    img = tf.keras.layers.Conv2D(32, (3, 3), activation="relu")(features)
    img = tf.keras.layers.MaxPool2D((2, 2), 2)(img)
    img = tf.keras.layers.Conv2D(64, (3, 3), activation="relu")(img)
    img = tf.keras.layers.MaxPool2D((2, 2), 2)(img)
    img = tf.keras.layers.Conv2D(64, (3, 3), activation="relu")(img)
    img = tf.keras.layers.Flatten()(img)
    img = tf.keras.layers.Dense(units=256, activation="relu")(img)
    img = tf.keras.layers.Dense(units=128, activation="relu")(img)
    logits = tf.keras.layers.Dense(units=10, activation=None)(img)

    probs = tf.keras.activations.softmax(logits)
    predicted_classes = tf.argmax(probs, 1)

    loss = tf.keras.losses.sparse_categorical_crossentropy(labels, probs)

    acc = tf.compat.v1.metrics.accuracy(labels, predicted_classes)
    metrics = {"accuracy": acc}
    tf.summary.scalar("accuracy", acc[1])

    if mode == tf.estimator.ModeKeys.EVAL:
        return tf.estimator.EstimatorSpec(mode,
                                          loss=loss, eval_metric_ops=metrics)

    assert mode == tf.estimator.ModeKeys.TRAIN

    optimizer = tf.keras.optimizers.Adagrad(learning_rate=0.001)
    train_op = optimizer.minimize(loss)
    return tf.estimator.EstimatorSpec(mode,
                                      loss=loss, train_op=train_op)

def load_mnist():
    train, test = mnist.load_data()
    return train, test

def train_input_fn(features, labels, batch_size):
    # features = tf.convert_to_tensor(features, dtype=tf.float32)
    # labels = tf.convert_to_tensor(labels, dtype=tf.int32)
    dataset = tf.data.Dataset.from_tensor_slices((features, labels))
    dataset = dataset.shuffle(500)
    dataset = dataset.repeat().batch(batch_size)
    return dataset

def eval_input_fn(imgs, labels, batch_size):
    dataset = tf.data.Dataset.from_tensor_slices((imgs, labels))
    dataset = dataset.batch(batch_size)
    return dataset

def main(m_dir=None):
    (x_train, y_train), (x_test, y_test) = load_mnist()
    x_train = x_train.reshape(60000, 28, 28, 1)
    x_test = x_test.reshape(10000, 28, 28, 1)
    classifier = tf.estimator.Estimator(model_fn=model_fn, model_dir=m_dir)

    classifier.train(input_fn=lambda: train_input_fn(x_train, y_train, 500), steps=100)

if __name__ == "__main__":
    main()
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by gadagashwini** [comment]
@muhammadfahid51, `optimizer.minimize()` function requires two argument loss and var_list. 
In your code replace `optimizer.minimize(loss)` with `optimizer.minimize(loss, var_list=None)`. For more see this [link](https://www.tensorflow.org/api_docs/python/tf/compat/v1/train/AdagradOptimizer#compute_gradients). Thanks!

**Comment by cshjin** [comment]
In TF2.0, You are using the Keras optimizer, where it requires two arguments including the var_list. 
See the doc here: https://www.tensorflow.org/api_docs/python/tf/keras/optimizers/Optimizer#minimize
Example like: https://www.tensorflow.org/api_docs/python/tf/keras/optimizers/Optimizer#example
would explicitly get **var_list** from **trainable_weights**.

In TF1.X, instead, you could use the tf.train.AdagradOptimizer, where the **var_list** is not required.
See the doc here: https://www.tensorflow.org/api_docs/python/tf/compat/v1/train/AdagradOptimizer#minimize

**Comment by cshjin** [comment]
In your case, either build a model object and take the **model.trainable_weights**, or define layers one by one and retrieve variables by **layer.weights**.

Check the doc here: https://www.tensorflow.org/guide/migrate#2_use_python_objects_to_track_variables_and_losses

**Comment by gadagashwini** [comment]
Closing since issue is resolved. Please feel free to reopen if issue still persists. Thanks!

**Comment by 1165628028** [comment]
> @muhammadfahid51, `optimizer.minimize()` function requires two argument loss and var_list.
> In your code replace `optimizer.minimize(loss)` with `optimizer.minimize(loss, var_list=None)`. For more see this [link](https://www.tensorflow.org/api_docs/python/tf/compat/v1/train/AdagradOptimizer#compute_gradients). Thanks!

when i  replace optimizer.minimize(loss) with optimizer.minimize(loss, var_list=None), it report new error:
`ValueError: `tape` is required when a `Tensor` loss is passed.`
