### ISSUE TITLE
How to build static libtensorflowlite.a for Android ?

### ISSUE THREAD

**Issue by huanyingjun** [tensorflow/tensorflow#34647]
bazel build -c opt --config=andrdoi_arm --cxxopt='--std=c++11' --cpu=arm64-v8a \
tensorflow/lite:libtensorflowlite.so

I can build libtensorflowlite.so using above command .
Is there any way to build static libtensorflowlite.a for Android ?

**Comment by nutsiepully** [comment]
bazel does not natively support generating static `.a` libraries.

Is there a specific reason you need a `.a` for Android? Since Android code gets bundled as an Apk, you typically want to bundle the `libtensorflowlite.so` in the Apk which can then get linked to the binary when the app starts.
