### ISSUE TITLE
TypeError while importing tensorflow caused by site.USER_SITE is set to None

### ISSUE THREAD

**Issue by tkilias** [tensorflow/tensorflow#34643]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: --
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.0.0
- Python version: 3.6
- Bazel version (if compiling from source): --
- GCC/Compiler version (if compiling from source): --
- CUDA/cuDNN version: --
- GPU model and memory: --

**Describe the current behavior**

When importing the tensorflow module with

`import tensorflow`

the following Exception gets thrown

> Traceback (most recent call last):
>   File "IMPORT_TENSORFLOW", line 8, in run
>   File "/usr/local/lib/python3.6/dist-packages/tensorflow/__init__.py", line 98, in <module>
>     from tensorflow_core import *
>   File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/__init__.py", line 403, in <module>
>     if _running_from_pip_package():
>   File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/__init__.py", line 401, in _running_from_pip_package
>     _current_file_location.startswith(dir_) for dir_ in _site_packages_dirs)
>   File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/__init__.py", line 401, in <genexpr>
    _current_file_location.startswith(dir_) for dir_ in _site_packages_dirs)
> TypeError: startswith first arg must be str or a tuple of str, not NoneType

from

https://github.com/tensorflow/tensorflow/blob/64c3d382cadf7bbe8e7e99884bede8284ff67f56/tensorflow/api_template.__init__.py#L119

The cause for this is

https://github.com/tensorflow/tensorflow/blob/64c3d382cadf7bbe8e7e99884bede8284ff67f56/tensorflow/api_template.__init__.py#L104

because `site.USER_SITE` can be `None` accordingly to the python documentation https://docs.python.org/3.6/library/site.html#site.USER_SITE and in this environment it happens to be the case.

A workaround for this is to call  site.getusersitepackages() before importing tensorflow. However, in my opinion the `USER_SITE` needs to be checked here before it is used, or the list _site_packages_dirs needs to be filtered for `None` values.

**Describe the expected behavior**

`import tensorflow` succeeds without the exception

**Code to reproduce the issue**

Start container:

`docker run --rm -it tensorflow/tensorflow:2.0.0-py3 bash`

Start python3 in the container without site initialization:

`python3 -S`

Add package locations to the sys.path and import tensorflow:

```
import sys
sys.path=['', '/usr/lib/python36.zip', '/usr/lib/python3.6', '/usr/lib/python3.6/lib-dynload', '/usr/local/lib/python3.6/dist-packages', '/usr/lib/python3/dist-packages']
import tensorflow
```

**Comment by yongtang** [comment]
I can verify the error with TF 2.2.0rc3. Created a PR  #38663 for the fix.
