### ISSUE TITLE
problems when I build tensorflow from source, someone helps please

### ISSUE THREAD

**Issue by 652994331** [tensorflow/tensorflow#34657]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 16.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: no
- TensorFlow installed from (source or binary): source(not sure, i am using ./configure and  then bazel build)
- TensorFlow version: 1.14(for my conda environment)
- Python version: 3.6.8
- Installed using virtualenv? pip? conda?: conda create -n xxx python=3.6.8 the enter the env and pip install tensorflow==1.14
- Bazel version (if compiling from source):1.1.0
- GCC/Compiler version (if compiling from source): 6.4.0
- CUDA/cuDNN version: cuda 10/cudnn  CUDNN_MAJOR 7
- GPU model and memory: TESLA P40

**Describe the problem**

**Provide the exact sequence of commands / steps that you executed before running into the problem**

HI, GUYS, I was trying to build tensorflow transform_graph tools  from source(same way as build tensorflow), I already installed bazel and clone tensorflow from github. When i use command
bazel build tensorflow/tools/graph_transforms:transform_graph, i got this problem
![image](https://user-images.githubusercontent.com/51428350/69752002-2286f500-1105-11ea-9f50-547851b71f59.png)

after searching for a while, i think it might because of the CUDA , so i ./configure again, this time, when it needs me to choose do you wish to build tf with cuda support, i chose no
and build again, but this time still not work
![image](https://user-images.githubusercontent.com/51428350/69752146-78f43380-1105-11ea-8407-c0de92760ec9.png)

could you please help me out? thanks so much

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.
