### ISSUE TITLE
GPU unit-test infrastructure breakage (`Dockerfile.gpu`, `gpu/run_py3_core.sh`) 

### ISSUE THREAD

**Issue by deven-amd** [tensorflow/tensorflow#34652]
Evertyime we sync (the `develop-upstream` branch) in our TF fork (with the `master` branch of this repo), we run a bunch of test-suites to qualify the changes before taking them.

One of those testsuites involves running the `GPU` tests (on the `cuda` platform) using the following command 

```
tensorflow/tools/ci_build/ci_build.sh GPU ./tensorflow/tools/ci_build/linux/gpu/run_py3_core.sh
```

The above testsuite failed for us during our latest sync attempt. 

We re-ran the CI job directly on the code in the `master` branch (as opposed to the merged code in our repo), and we see the same errors, leading us to believe that the breakage originates due to changes in the upstream repo.

Link to the CI run log mentioned above : http://ml-ci.amd.com:21096/job/tensorflow-cuda/1/console

Our last successful merge was about 3 weeks ago, so the breakage seems to have been introduced sometime within the last 3 weeks. 

Errors similar to the ones we see, have been reported in other github issues.
https://github.com/tensorflow/tensorflow/issues/34429
https://github.com/tensorflow/tensorflow/issues/34117

When we look at the invocation log for the `Linux GPU` (in the **Continuous build status** section of README.md), the run is passing, but it seems to use a different script and different env-vars/options/etc as compared to those used by the `Dockerfile.gpu` and `./tensorflow/tools/ci_build/linux/gpu/*.sh` scripts that are used by our CI job.

The request here is to please identify what is causing the breakage we see on our end, and fix it. Also please update the GPU test scripts (`Dockerfile.gpu` + `./tensorflow/tools/ci_build/linux/gpu/*.sh` ) to match what is done by the GPU CI runs kicked off internally.

thanks

/cc @chsigg @parallelo @sunway513 @whchung

**Comment by deven-amd** [comment]
For one of the errors we see in our CI run

```
ImportError: /home/ubuntu/workspace/tensorflow-cuda/bazel-ci_build-cache/.cache/bazel/_bazel_ubuntu/eab0d61a99b6696edb3d2aff87b585e8/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/create_tensorflow.python_api_2_tf_python_api_gen_v2.runfiles/org_tensorflow/tensorflow/compiler/tf2tensorrt/_wrap_py_utils.so: undefined symbol: _ZN10tensorflowlsERSoRKNS_6StatusE
----------------
Note: The failure of target //tensorflow:create_tensorflow.python_api_2_tf_python_api_gen_v2 (with exit code 1) may have been caused by the fact that it is a Python 2 program that was built in the host configuration, which uses Python 3. You can change the host configuration (for the entire build) to instead use Python 2 by setting --host_force_python=PY2.
```

we tried using the recommended workaround, (i.e. the `--host_force_python` option) but it seemed to have no effect

**Comment by deven-amd** [comment]
@gunan gentle ping

**Comment by gunan** [comment]
@angerson Could you take a look?
is this due to our dockerfiles being broken?

**Comment by deven-amd** [comment]
The XLA tests (i.e. the tests run by the script https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/ci_build/xla/linux/gpu/run_py3.sh )  seem to be similarly broken on the CUDA platform 

http://ml-ci.amd.com:21096/job/tensorflow-cuda-xla/1/console

**Comment by angerson** [comment]
I don't think this would be related to the Dockerfiles, at least not the ones in tools/dockerfiles; those aren't used by these old CI build scripts. I've been trying to get the Dockerfiles to build again (the old maintainer departed) but I'm running into trouble compiling with TensorRT.

As for the tests, ci_build/release contains tests we run internally; you should be able to find some helpful build options there. I don't think we use ci_build.sh internally.

**Comment by deven-amd** [comment]
@gunan @angerson thanks for the answers

It would be really helpful if you could make the dockerfiles+scripts in the public repo functional again. It would give us the ability to both 
* experimentally verify what is currently working / broken in the upstream repo
* ensure that the changes in the PRs we submit are not regressing existing functionality.

In the meantime, is there any way we can get a current pass/fail status for all the tests that would be run by these 3 scripts.
* https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/ci_build/linux/gpu/run_cc_core.sh
* https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/ci_build/linux/gpu/run_py3_core.sh
* https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/ci_build/xla/linux/gpu/run_py3.sh

The `rocm` versions of those scritps are what we use to run our CI. When we get a regression in those tests, we need to figure out whether the cause is a change in the upstream repo, or something we changed in our fork. We have not had the ability to run these tests on the upstream repo for more than a month now, and hence do not know which tests are currently broken, and hence the request to you.

thanks

deven

**Comment by deven-amd** [comment]
@gunan @angerson any update here?

**Comment by jerryyin** [comment]
Gentle pint here. The fact that those scripts are broken makes it hard for us `ROCm` people to do sanity checks between that of `Cuda`. We are trying to behave like good first class citizen here and not break `Cuda` build in `ROCm` features. Could you either share the way to do the `internal` build or take a look at those scripts? For the minimal, sharing the `Linux GPU` build for PR sanity check can be useful for us.

**Comment by gunan** [comment]
We did update our dockerfiles, but our CI does not run using ci_build.sh anymore
one thing to try can be to use devel dockerfile TF is publishing on dockerhub, and run the script you run_py3_core.sh script you ran directly on it.

About the python version isue you ran into may be due to ci_build.sh trying to override `PYTHON_BIN_PATH` environment variable.

**Comment by Venkat6871** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
