### ISSUE TITLE
AttributeError: module 'tensorflow' has no attribute 'Session'

### ISSUE THREAD

**Issue by shreyasharma98** [tensorflow/tensorflow#34658]
> import tensorflow as tf
> sess = tf.Session()

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-9-f75057d1d95f> in <module>
----> 1 sess = tf.Session()

AttributeError: module 'tensorflow' has no attribute 'Session'
Environment details : 
Anaconda Python : 3.6
tensorflow version : 2.0.0
Machine (OS) : LINUX , Ubuntu 16.04

New to tensorflow, I am facing this error help me with this!

**Comment by nikochiko** [comment]
@imshreyaa , you are using old TensorFlow 1.X syntax. `tf.Session()`was deprecated in TensorFlow 2.0.0
Please go through the latest documentation on https://www.tensorflow.org to know more.
If you still want to use `tf.Session()`, use the syntax `tf.compat.v1.Session()` instead. 
*Also because you are new to TensorFlow, I would recommend you practice on Google Colab [notebooks](https://colab.research.google.com/) instead. You have much more flexibility, you won't need to download anything, most example datasets are already there. You get to try out TensorFlow 1 and TensorFlow 2 side by side and also import other example colab notebooks as it is. Hope this helps. :)

**Comment by alexlaurence** [comment]
I'm having the same issue too... Was working before the weekend. Not anymore.

**Comment by oanush** [comment]
@shreyasharma98 ,
can you please check @nikochiko reponse and let us know if it helped.Thanks!

**Comment by oanush** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Comment by LeeJongAnn** [comment]
Thank you So much I have the same problem , and now I can study tensorflow Thx!!!!

**Comment by geekyarthurs** [comment]
Thank you so much <3

**Comment by ElyasRashno** [comment]
The "sess = tf.Session()" operation is deprecated in tensorflow version 2.0.0
Please set your tensorflow version less than 2.0.0 .
Good Luck.

**Comment by ShreeniketJoshi** [comment]
> The "sess = tf.Session()" operation is deprecated in tensorflow version 2.0.0
> Please set your tensorflow version less than 2.0.0 .
> Good Luck.

Hi, can you please advise on how to downgrade tensorboard to 2.0? Along with tensorflow?

**Comment by Kiranw24** [comment]
i'm using it on google colab but still getting same error

**Comment by Isha307** [comment]
In google colab also, we have to use tf.compat.v1.Session()

**Comment by 4yafes6** [comment]
> @imShreyaa , eski TensorFlow 1.X sözdizimini kullanıyorsunuz. `tf.Session()`TensorFlow 2.0.0'da kullanımdan kaldırıldı Daha fazla bilgi için lütfen [https://www.tensorflow.org adresindeki](https://www.tensorflow.org) en son belgeleri inceleyin . Hâlâ kullanmak istiyorsanız `tf.Session()`, bunun yerine sözdizimini `tf.compat.v1.Session()`kullanın. *Ayrıca TensorFlow'da yeni olduğunuz için bunun yerine Google Colab [not defterlerinde](https://colab.research.google.com/) pratik yapmanızı tavsiye ederim . Çok daha fazla esneklik var, hiçbir şey indirmenize gerek yok, çoğu örnek veri seti/kütüphane zaten orada. TensorFlow 1 ve TensorFlow 2'yi yan yana deneyebilir ve diğer örnek ortak çalışma not defterlerini olduğu gibi içe aktarabilirsiniz. Bu yardımcı olur umarım. :)

TypeError: 'Session' object is not callable

**Comment by codemaker2015** [comment]
```
import tensorflow as tf
sess = tf.compat.v1.Session()
```
