### ISSUE TITLE
tensorflow-serving apt-get not working

### ISSUE THREAD

**Issue by ajayaraman** [tensorflow/tensorflow#34656]
**System information**
- OS : Linux
- TensorFlow installed from (source or binary): binary
- TensorFlow version: 2.0.0
- Python version: 3.7
- Installed using virtualenv? pip

**Describe the problem**
Upon following instructions in https://www.tensorflow.org/tfx/serving/setup for apt-get method to install tensorflow-model-serving-universal 

get the following error

Err:3 http://storage.googleapis.com/tensorflow-serving-apt stable InRelease   503  Service Unavailable [IP: 172.217.6.80 80]

**Provide the exact sequence of commands / steps that you executed before running into the problem**

echo "deb [arch=amd64] http://storage.googleapis.com/tensorflow-serving-apt stable tensorflow-model-server tensorflow-model-server-universal" | sudo tee /etc/apt/sources.list.d/tensorflow-serving.list && \
curl https://storage.googleapis.com/tensorflow-serving-apt/tensorflow-serving.release.pub.gpg | sudo apt-key add -
apt-get update && apt-get install tensorflow-model-server

**Comment by gowthamkpr** [comment]
@ajayaraman I am going to close this issue here. Please post this issue in [tensorflow/serving](https://github.com/tensorflow/serving/issues) repository as this issue is more apt to that repository.
