### ISSUE TITLE
TensorFlow Lite for Microcontrollers fails to build 

### ISSUE THREAD

**Issue by kenthinson** [tensorflow/tensorflow#34664]
Attempting to build the test arduino library using:
./tensorflow/lite/experimental/micro/tools/ci_build/test_arduino.sh
Throws a error about not being able to execute Arduino-cli.
I installed Arduino-cli through brew but still get the error.

**System information**
- Mac OSX 10.15.1
- TensorFlow version: Master
- Python version: 2.7

If I had to guess the build script is pulling down the linux binary and failing to run it. But I have not verified this.

**Comment by wangtz** [comment]
Could you share the detailed error to help debugging? Thx!

**Comment by amahendrakar** [comment]
@kenthinson,
Is this still an issue? Could you please update TensorFlow to v2.3 and check if you are still facing the same error. Thanks!
