### ISSUE TITLE
Weight Normalization

### ISSUE THREAD

**Issue by MachineJeff** [tensorflow/tensorflow#34666]
**System information**
- TensorFlow version : 1.11
- Are you willing to contribute it : Yes

**Describe the feature and the current behavior/state.**

Weight Normalization is described in [Weight Normalization: A Simple Reparameterization
to Accelerate Training of Deep Neural Networks](https://arxiv.org/pdf/1602.07868.pdf).

Current, only in tf2.0 and use tensorflow-addons can achieve this normalization, it's [tfa-2.0](https://www.tensorflow.org/addons/tutorials/layers_weightnormalization)

In [Github](https://github.com/zoli333/Weight-Normalization) , someone write it in Conv2D

**Will this change the current api? How?**
It should build a serious of new apis.

**Who will benefit with this feature?**
Especially who want to train a GAN.

**Comment by oanush** [comment]
@MachineJeff ,
Hi,Release 1.15.0-rc0 is the last 1.x release for TensorFlow. We do not expect to update the 1.x branch with features, although we will issue patch releases to fix vulnerabilities for at least one year.
Please refer the [link](https://github.com/tensorflow/tensorflow/releases/tag/v1.15.0-rc0).Thanks!

**Comment by oanush** [comment]
@MachineJeff ,
any update on the issue?Thanks!
