### ISSUE TITLE
armeabi-v7a libtensorflowlite_jni.so：signal 7 (SIGBUS), code 1 (BUS_ADRALN), fault addr 0xeef5445f

### ISSUE THREAD

**Issue by yanceyblog** [tensorflow/tensorflow#34669]
11-26 06:29:37.207 25216 25216 F DEBUG   : Revision: '1234'
11-26 06:29:37.207 25216 25216 F DEBUG   : ABI: 'arm'
11-26 06:29:37.207 25216 25216 F DEBUG   : pid: 24454, tid: 24528, name: RxCachedThreadS  
11-26 06:29:37.207 25216 25216 F DEBUG   : signal 7 (SIGBUS), code 1 (BUS_ADRALN), fault addr 0xeef5445f
11-26 06:29:37.207 25216 25216 F DEBUG   :     r0  eef5445f  r1  cd222804  r2  cd222800  r3  00000000
11-26 06:29:37.207 25216 25216 F DEBUG   :     r4  0000005a  r5  00000000  r6  cd2234c0  r7  d1ec0f28
11-26 06:29:37.207 25216 25216 F DEBUG   :     r8  00000000  r9  eef5445f  r10 00000168  r11 cd2234c0
11-26 06:29:37.207 25216 25216 F DEBUG   :     ip  00000009  sp  d1ec0e68  lr  00000004  pc  cd725ede

**Comment by yanceyblog** [comment]
11-26 06:29:37.207 25216 25216 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
11-26 06:29:37.207 25216 25216 F DEBUG   : Build fingerprint: 'changhong/changhong_MT9652_cn/changhong_MT9652_cn:9/PPR2.180905.006.A1/TVOS-04.16.031.01.12:userdebug/dev-keys'
11-26 06:29:37.207 25216 25216 F DEBUG   : Revision: '1234'
11-26 06:29:37.207 25216 25216 F DEBUG   : ABI: 'arm'
11-26 06:29:37.207 25216 25216 F DEBUG   : pid: 24454, tid: 24528, name: RxCachedThreadS  >>> com.tensorflow.jni <<<
11-26 06:29:37.207 25216 25216 F DEBUG   : signal 7 (SIGBUS), code 1 (BUS_ADRALN), fault addr 0xeef5445f
11-26 06:29:37.207 25216 25216 F DEBUG   :     r0  eef5445f  r1  cd222804  r2  cd222800  r3  00000000
11-26 06:29:37.207 25216 25216 F DEBUG   :     r4  0000005a  r5  00000000  r6  cd2234c0  r7  d1ec0f28
11-26 06:29:37.207 25216 25216 F DEBUG   :     r8  00000000  r9  eef5445f  r10 00000168  r11 cd2234c0
11-26 06:29:37.207 25216 25216 F DEBUG   :     ip  00000009  sp  d1ec0e68  lr  00000004  pc  cd725ede
11-26 06:29:37.292 25216 25216 F DEBUG   : 
11-26 06:29:37.292 25216 25216 F DEBUG   : backtrace:
11-26 06:29:37.292 25216 25216 F DEBUG   :     #00 pc 00093ede  /data/app/com.tensorflow.jni-kNNGQ77u2Lr-Bq2GxxZZEg==/lib/arm/libtensorflowlite_jni.so
11-26 06:29:37.293 25216 25216 F DEBUG   :     #01 pc 0009536b  /data/app/com.tensorflow.jni-kNNGQ77u2Lr-Bq2GxxZZEg==/lib/arm/libtensorflowlite_jni.so
11-26 06:29:37.293 25216 25216 F DEBUG   :     #02 pc 00092bc3  /data/app/com.tensorflow.jni-kNNGQ77u2Lr-Bq2GxxZZEg==/lib/arm/libtensorflowlite_jni.so
11-26 06:29:37.293 25216 25216 F DEBUG   :     #03 pc 000ce64d  /data/app/com.tensorflow.jni-kNNGQ77u2Lr-Bq2GxxZZEg==/lib/arm/libtensorflowlite_jni.so
11-26 06:29:37.293 25216 25216 F DEBUG   :     #04 pc 000080af  /data/app/com.tensorflow.jni-kNNGQ77u2Lr-Bq2GxxZZEg==/lib/arm/libtensorflowlite_jni.so (Java_org_tensorflow_lite_NativeInterpreterWrapper_run+26)
11-26 06:29:37.293 25216 25216 F DEBUG   :     #05 pc 00037691  /data/app/com.tensorflow.jni-kNNGQ77u2Lr-Bq2GxxZZEg==/oat/arm/base.odex (offset 0x2f000) (org.tensorflow.lite.NativeInterpreterWrapper.run+120)
11-26 06:29:37.293 25216 25216 F DEBUG   :     #06 pc 00416b75  /system/lib/libart.so (art_quick_invoke_stub_internal+68)
11-26 06:29:37.293 25216 25216 F DEBUG   :     #07 pc 003f0397  /system/lib/libart.so (art_quick_invoke_static_stub+222)
11-26 06:29:37.293 25216 25216 F DEBUG   :     #08 pc 000a103b  /system/lib/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+154)
11-26 06:29:37.293 25216 25216 F DEBUG   :     #09 pc 001e83bd  /system/lib/libart.so (art::interpreter::ArtInterpreterToCompiledCodeBridge(art::Thread*, art::ArtMethod*, art::ShadowFrame*, unsigned short, art::JValue*)+232)
11-26 06:29:37.293 25216 25216 F DEBUG   :     #10 pc 001e309d  /system/lib/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+776)
11-26 06:29:37.293 25216 25216 F DEBUG   :     #11 pc 003ebe93  /system/lib/libart.so (MterpInvokeStatic+130)
11-26 06:29:37.293 25216 25216 F DEBUG   :     #12 pc 00409b14  /system/lib/libart.so (ExecuteMterpImpl+14612)
11-26 06:29:37.293 25216 25216 F DEBUG   :     #13 pc 00b15e72  /data/app/com.tensorflow.jni-kNNGQ77u2Lr-Bq2GxxZZEg==/oat/arm/base.vdex (org.tensorflow.lite.NativeInterpreterWrapper.run+166)
11-26 06:29:37.293 25216 25216 F DEBUG   :     #14 pc 001c7a15  /system/lib/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadERKNS_20CodeItemDataAccessorERNS_11ShadowFrameENS_6JValueEb.llvm.3885687342+352)
11-26 06:29:37.293 25216 25216 F DEBUG   :     #15 pc 001cc2e3  /system/lib/libart.so (art::interpreter::ArtInterpreterToInterpreterBridge(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame*, art::JValue*)+146)
11-26 06:29:37.294 25216 25216 F DEBUG   :     #16 pc 001e3087  /system/lib/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+754)
11-26 06:29:37.294 25216 25216 F DEBUG   :     #17 pc 003eaeb7  /system/lib/libart.so (MterpInvokeVirtual+442)
11-26 06:29:37.294 25216 25216 F DEBUG   :     #18 pc 00409994  /system/lib/libart.so (ExecuteMterpImpl+14228)
11-26 06:29:37.294 25216 25216 F DEBUG   :     #19 pc 00b15858  /data/app/com.tensorflow.jni-kNNGQ77u2Lr-Bq2GxxZZEg==/oat/arm/base.vdex (org.tensorflow.lite.Interpreter.runForMultipleInputsOutputs+10)
11-26 06:29:37.294 25216 25216 F DEBUG   :     #20 pc 001c7a15  /system/lib/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadERKNS_20CodeItemDataAccessorERNS_11ShadowFrameENS_6JValueEb.llvm.3885687342+352)
11-26 06:29:37.294 25216 25216 F DEBUG   :     #21 pc 001cc2e3  /system/lib/libart.so (art::interpreter::ArtInterpreterToInterpreterBridge(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame*, art::JValue*)+146)
11-26 06:29:37.294 25216 25216 F DEBUG   :     #22 pc 001e3087  /system/lib/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+754)
11-26 06:29:37.294 25216 25216 F DEBUG   :     #23 pc 003eaeb7  /system/lib/libart.so (MterpInvokeVirtual+442)
11-26 06:29:37.294 25216 25216 F DEBUG   :     #24 pc 00409994  /system/lib/libart.so (ExecuteMterpImpl+14228)
11-26 06:29:37.294 25216 25216 F DEBUG   :     #25 pc 00b15842  /data/app/com.tensorflow.jni-kNNGQ77u2Lr-Bq2GxxZZEg==/oat/arm/base.vdex (org.tensorflow.lite.Interpreter.run+36)
11-26 06:29:37.294 25216 25216 F DEBUG   :     #26 pc 001c7a15  /system/lib/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadERKNS_20CodeItemDataAccessorERNS_11ShadowFrameENS_6JValueEb.llvm.3885687342+352)
11-26 06:29:37.294 25216 25216 F DEBUG   :     #27 pc 001cc2e3  /system/lib/libart.so (art::interpreter::ArtInterpreterToInterpreterBridge(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame*, art::JValue*)+146)
11-26 06:29:37.295 25216 25216 F DEBUG   :     #28 pc 001e3087  /system/lib/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+754)
11-26 06:29:37.295 25216 25216 F DEBUG   :     #29 pc 003eaeb7  /system/lib/libart.so (MterpInvokeVirtual+442)
11-26 06:29:37.295 25216 25216 F DEBUG   :     #30 pc 00409994  /system/lib/libart.so (ExecuteMterpImpl+14228)
11-26 06:29:37.295 25216 25216 F DEBUG   :     #31 pc 004a1b36  /data/app/com.tensorflow.jni-kNNGQ77u2Lr-Bq2GxxZZEg==/oat/arm/base.vdex (com.tensorflow.jni.core.nlp.offline.LocalNLP.process+234)
11-26 06:29:37.295 25216 25216 F DEBUG   :     #32 pc 001c7a15  /system/lib/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadERKNS_20CodeItemDataAccessorERNS_11ShadowFrameENS_6JValueEb.llvm.3885687342+352)
11-26 06:29:37.295 25216 25216 F DEBUG   :     #33 pc 001cc2e3  /system/lib/libart.so (art::interpreter::ArtInterpreterToInterpreterBridge(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame*, art::JValue*)+146)
11-26 06:29:37.295 25216 25216 F DEBUG   :     #34 pc 001e3087  /system/lib/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+754)
11-26 06:29:37.296 25216 25216 F DEBUG   :     #35 pc 003eaeb7  /system/lib/libart.so (MterpInvokeVirtual+442)
11-26 06:29:37.296 25216 25216 F DEBUG   :     #36 pc 00409994  /system/lib/libart.so (ExecuteMterpImpl+14228)
11-26 06:29:37.296 25216 25216 F DEBUG   :     #37 pc 0047f032  /data/app/com.tensorflow.jni-kNNGQ77u2Lr-Bq2GxxZZEg==/oat/arm/base.vdex (com.tensorflow.jni.core.nlp.NlpScheduler.lambda$requestLocal$0$NlpScheduler+42)
11-26 06:29:37.296 25216 25216 F DEBUG   :     #38 pc 001c7a15  /system/lib/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadERKNS_20CodeItemDataAccessorERNS_11ShadowFrameENS_6JValueEb.llvm.3885687342+352)
11-26 06:29:37.296 25216 25216 F DEBUG   :     #39 pc 001cc2e3  /system/lib/libart.so (art::interpreter::ArtInterpreterToInterpreterBridge(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame*, art::JValue*)+146)
11-26 06:29:37.296 25216 25216 F DEBUG   :     #40 pc 001e3087  /system/lib/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+754)
11-26 06:29:37.296 25216 25216 F DEBUG   :     #41 pc 003eaeb7  /system/lib/libart.so (MterpInvokeVirtual+442)
11-26 06:29:37.296 25216 25216 F DEBUG   :     #42 pc 00409994  /system/lib/libart.so (ExecuteMterpImpl+14228)
11-26 06:29:37.296 25216 25216 F DEBUG   :     #43 pc 0047e83a  /data/app/com.tensorflow.jni-kNNGQ77u2Lr-Bq2GxxZZEg==/oat/arm/base.vdex (com.tensorflow.jni.core.nlp.NlpScheduler$$Lambda$0.subscribe+8)
11-26 06:29:37.296 25216 25216 F DEBUG   :     #44 pc 001c7a15  /system/lib/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadERKNS_20CodeItemDataAccessorERNS_11ShadowFrameENS_6JValueEb.llvm.3885687342+352)
11-26 06:29:37.296 25216 25216 F DEBUG   :     #45 pc 001cc2e3  /system/lib/libart.so (art::interpreter::ArtInterpreterToInterpreterBridge(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame*, art::JValue*)+146)
11-26 06:29:37.296 25216 25216 F DEBUG   :     #46 pc 001e3087  /system/lib/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+754)
11-26 06:29:37.296 25216 25216 F DEBUG   :     #47 pc 003eba85  /system/lib/libart.so (MterpInvokeInterface+1020)
11-26 06:29:37.296 25216 25216 F DEBUG   :     #48 pc 00409b94  /system/lib/libart.so (ExecuteMterpImpl+14740)
11-26 06:29:37.296 25216 25216 F DEBUG   :     #49 pc 00a1e2e0  /data/app/com.tensorflow.jni-kNNGQ77u2Lr-Bq2GxxZZEg==/oat/arm/base.vdex (io.reactivex.internal.operators.observable.ObservableCreate.subscribeActual+20)
11-26 06:29:37.297 25216 25216 F DEBUG   :     #50 pc 001c7a15  /system/lib/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadERKNS_20CodeItemDataAccessorERNS_11ShadowFrameENS_6JValueEb.llvm.3885687342+352)
11-26 06:29:37.297 25216 25216 F DEBUG   :     #51 pc 001cc2e3  /system/lib/libart.so (art::interpreter::ArtInterpreterToInterpreterBridge(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame*, art::JValue*)+146)
11-26 06:29:37.297 25216 25216 F DEBUG   :     #52 pc 001e3087  /system/lib/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+754)
11-26 06:29:37.297 25216 25216 F DEBUG   :     #53 pc 003eaeb7  /system/lib/libart.so (MterpInvokeVirtual+442)
11-26 06:29:37.297 25216 25216 F DEBUG   :     #54 pc 00409994  /system/lib/libart.so (ExecuteMterpImpl+14228)
11-26 06:29:37.297 25216 25216 F DEBUG   :     #55 pc 00246994  /data/app/com.tensorflow.jni-kNNGQ77u2Lr-Bq2GxxZZEg==/oat/arm/base.vdex (io.reactivex.Observable.subscribe+30)
11-26 06:29:37.297 25216 25216 F DEBUG   :     #56 pc 001c7a15  /system/lib/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadERKNS_20CodeItemDataAccessorERNS_11ShadowFrameENS_6JValueEb.llvm.3885687342+352)
11-26 06:29:37.297 25216 25216 F DEBUG   :     #57 pc 001cc2e3  /system/lib/libart.so (art::interpreter::ArtInterpreterToInterpreterBridge(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame*, art::JValue*)+146)
11-26 06:29:37.297 25216 25216 F DEBUG   :     #58 pc 001e3087  /system/lib/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+754)
11-26 06:29:37.297 25216 25216 F DEBUG   :     #59 pc 003eba85  /system/lib/libart.so (MterpInvokeInterface+1020)
11-26 06:29:37.297 25216 25216 F DEBUG   :     #60 pc 00409b94  /system/lib/libart.so (ExecuteMterpImpl+14740)
11-26 06:29:37.297 25216 25216 F DEBUG   :     #61 pc 00a28e00  /data/app/com.tensorflow.jni-kNNGQ77u2Lr-Bq2GxxZZEg==/oat/arm/base.vdex (io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run+12)
11-26 06:29:37.297 25216 25216 F DEBUG   :     #62 pc 001c7a15  /system/lib/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadERKNS_20CodeItemDataAccessorERNS_11ShadowFrameENS_6JValueEb.llvm.3885687342+352)
11-26 06:29:37.298 25216 25216 F DEBUG   :     #63 pc 001cc2e3  /system/lib/libart.so (art::interpreter::ArtInterpreterToInterpreterBridge(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame*, art::JValue*)+146)
11-26 06:29:37.298 25216 25216 F DEBUG   :     #64 pc 001e3087  /system/lib/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+754)
11-26 06:29:37.298 25216 25216 F DEBUG   :     #65 pc 003eba85  /system/lib/libart.so (MterpInvokeInterface+1020)
11-26 06:29:37.298 25216 25216 F DEBUG   :     #66 pc 00409b94  /system/lib/libart.so (ExecuteMterpImpl+14740)
11-26 06:29:37.298 25216 25216 F DEBUG   :     #67 pc 005e9120  /data/app/com.tensorflow.jni-kNNGQ77u2Lr-Bq2GxxZZEg==/oat/arm/base.vdex (io.reactivex.Scheduler$DisposeTask.run+18)
11-26 06:29:37.298 25216 25216 F DEBUG   :     #68 pc 001c7a15  /system/lib/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadERKNS_20CodeItemDataAccessorERNS_11ShadowFrameENS_6JValueEb.llvm.3885687342+352)
11-26 06:29:37.298 25216 25216 F DEBUG   :     #69 pc 001cc2e3  /system/lib/libart.so (art::interpreter::ArtInterpreterToInterpreterBridge(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame*, art::JValue*)+146)
11-26 06:29:37.298 25216 25216 F DEBUG   :     #70 pc 001e3087  /system/lib/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+754)
11-26 06:29:37.298 25216 25216 F DEBUG   :     #71 pc 003eba85  /system/lib/libart.so (MterpInvokeInterface+1020)
11-26 06:29:37.298 25216 25216 F DEBUG   :     #72 pc 00409b94  /system/lib/libart.so (ExecuteMterpImpl+14740)
11-26 06:29:37.298 25216 25216 F DEBUG   :     #73 pc 00a36e5e  /data/app/com.tensorflow.jni-kNNGQ77u2Lr-Bq2GxxZZEg==/oat/arm/base.vdex (io.reactivex.internal.schedulers.ScheduledRunnable.run+26)
11-26 06:29:37.298 25216 25216 F DEBUG   :     #74 pc 001c7a15  /system/lib/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadERKNS_20CodeItemDataAccessorERNS_11ShadowFrameENS_6JValueEb.llvm.3885687342+352)
11-26 06:29:37.299 25216 25216 F DEBUG   :     #75 pc 001cc2e3  /system/lib/libart.so (art::interpreter::ArtInterpreterToInterpreterBridge(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame*, art::JValue*)+146)
11-26 06:29:37.299 25216 25216 F DEBUG   :     #76 pc 001e3087  /system/lib/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+754)
11-26 06:29:37.299 25216 25216 F DEBUG   :     #77 pc 003eaeb7  /system/lib/libart.so (MterpInvokeVirtual+442)
11-26 06:29:37.299 25216 25216 F DEBUG   :     #78 pc 00409994  /system/lib/libart.so (ExecuteMterpImpl+14228)
11-26 06:29:37.299 25216 25216 F DEBUG   :     #79 pc 00a36d2a  /data/app/com.tensorflow.jni-kNNGQ77u2Lr-Bq2GxxZZEg==/oat/arm/base.vdex (io.reactivex.internal.schedulers.ScheduledRunnable.call)
11-26 06:29:37.299 25216 25216 F DEBUG   :     #80 pc 001c7a15  /system/lib/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadERKNS_20CodeItemDataAccessorERNS_11ShadowFrameENS_6JValueEb.llvm.3885687342+352)
11-26 06:29:37.299 25216 25216 F DEBUG   :     #81 pc 001cc2e3  /system/lib/libart.so (art::interpreter::ArtInterpreterToInterpreterBridge(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame*, art::JValue*)+146)
11-26 06:29:37.299 25216 25216 F DEBUG   :     #82 pc 001e3087  /system/lib/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+754)
11-26 06:29:37.299 25216 25216 F DEBUG   :     #83 pc 003eba85  /system/lib/libart.so (MterpInvokeInterface+1020)
11-26 06:29:37.299 25216 25216 F DEBUG   :     #84 pc 00409b94  /system/lib/libart.so (ExecuteMterpImpl+14740)
11-26 06:29:37.299 25216 25216 F DEBUG   :     #85 pc 001130fa  /system/framework/boot-core-oj.vdex (java.util.concurrent.FutureTask.run+62)
11-26 06:29:37.299 25216 25216 F DEBUG   :     #86 pc 001c7a15  /system/lib/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadERKNS_20CodeItemDataAccessorERNS_11ShadowFrameENS_6JValueEb.llvm.3885687342+352)
11-26 06:29:37.299 25216 25216 F DEBUG   :     #87 pc 001cc2e3  /system/lib/libart.so (art::interpreter::ArtInterpreterToInterpreterBridge(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame*, art::JValue*)+146)
11-26 06:29:37.299 25216 25216 F DEBUG   :     #88 pc 001e3087  /system/lib/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+754)
11-26 06:29:37.299 25216 25216 F DEBUG   :     #89 pc 003eb3cd  /system/lib/libart.so (MterpInvokeSuper+1096)
11-26 06:29:37.300 25216 25216 F DEBUG   :     #90 pc 00409a14  /system/lib/libart.so (ExecuteMterpImpl+14356)
11-26 06:29:37.300 25216 25216 F DEBUG   :     #91 pc 00115776  /system/framework/boot-core-oj.vdex (java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run+38)
11-26 06:29:37.300 25216 25216 F DEBUG   :     #92 pc 001c7a15  /system/lib/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadERKNS_20CodeItemDataAccessorERNS_11ShadowFrameENS_6JValueEb.llvm.3885687342+352)
11-26 06:29:37.300 25216 25216 F DEBUG   :     #93 pc 001cc2e3  /system/lib/libart.so (art::interpreter::ArtInterpreterToInterpreterBridge(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame*, art::JValue*)+146)
11-26 06:29:37.300 25216 25216 F DEBUG   :     #94 pc 001e3087  /system/lib/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+754)
11-26 06:29:37.300 25216 25216 F DEBUG   :     #95 pc 003eba85  /system/lib/libart.so (MterpInvokeInterface+1020)
11-26 06:29:37.300 25216 25216 F DEBUG   :     #96 pc 00409b94  /system/lib/libart.so (ExecuteMterpImpl+14740)
11-26 06:29:37.300 25216 25216 F DEBUG   :     #97 pc 001170e0  /system/framework/boot-core-oj.vdex (java.util.concurrent.ThreadPoolExecutor.runWorker+162)
11-26 06:29:37.300 25216 25216 F DEBUG   :     #98 pc 001c7a15  /system/lib/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadERKNS_20CodeItemDataAccessorERNS_11ShadowFrameENS_6JValueEb.llvm.3885687342+352)
11-26 06:29:37.300 25216 25216 F DEBUG   :     #99 pc 001cc2e3  /system/lib/libart.so (art::interpreter::ArtInterpreterToInterpreterBridge(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame*, art::JValue*)+146)
11-26 06:29:37.300 25216 25216 F DEBUG   :     #100 pc 001e3087  /system/lib/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+754)
11-26 06:29:37.300 25216 25216 F DEBUG   :     #101 pc 003eaeb7  /system/lib/libart.so (MterpInvokeVirtual+442)
11-26 06:29:37.300 25216 25216 F DEBUG   :     #102 pc 00409994  /system/lib/libart.so (ExecuteMterpImpl+14228)
11-26 06:29:37.300 25216 25216 F DEBUG   :     #103 pc 0011640e  /system/framework/boot-core-oj.vdex (java.util.concurrent.ThreadPoolExecutor$Worker.run+4)
11-26 06:29:37.300 25216 25216 F DEBUG   :     #104 pc 001c7a15  /system/lib/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadERKNS_20CodeItemDataAccessorERNS_11ShadowFrameENS_6JValueEb.llvm.3885687342+352)
11-26 06:29:37.301 25216 25216 F DEBUG   :     #105 pc 001cc2e3  /system/lib/libart.so (art::interpreter::ArtInterpreterToInterpreterBridge(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame*, art::JValue*)+146)
11-26 06:29:37.301 25216 25216 F DEBUG   :     #106 pc 001e3087  /system/lib/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+754)
11-26 06:29:37.301 25216 25216 F DEBUG   :     #107 pc 003eba85  /system/lib/libart.so (MterpInvokeInterface+1020)
11-26 06:29:37.301 25216 25216 F DEBUG   :     #108 pc 00409b94  /system/lib/libart.so (ExecuteMterpImpl+14740)
11-26 06:29:37.301 25216 25216 F DEBUG   :     #109 pc 000ca806  /system/framework/boot-core-oj.vdex (java.lang.Thread.run+12)
11-26 06:29:37.301 25216 25216 F DEBUG   :     #110 pc 001c7a15  /system/lib/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadERKNS_20CodeItemDataAccessorERNS_11ShadowFrameENS_6JValueEb.llvm.3885687342+352)
11-26 06:29:37.301 25216 25216 F DEBUG   :     #111 pc 001cc22f  /system/lib/libart.so (art::interpreter::EnterInterpreterFromEntryPoint(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame*)+82)
11-26 06:29:37.301 25216 25216 F DEBUG   :     #112 pc 003de6fb  /system/lib/libart.so (artQuickToInterpreterBridge+890)
11-26 06:29:37.301 25216 25216 F DEBUG   :     #113 pc 0041b0ff  /system/lib/libart.so (art_quick_to_interpreter_bridge+30)
11-26 06:29:37.301 25216 25216 F DEBUG   :     #114 pc 00416b75  /system/lib/libart.so (art_quick_invoke_stub_internal+68)
11-26 06:29:37.301 25216 25216 F DEBUG   :     #115 pc 003f0293  /system/lib/libart.so (art_quick_invoke_stub+226)
11-26 06:29:37.301 25216 25216 F DEBUG   :     #116 pc 000a1029  /system/lib/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+136)
11-26 06:29:37.301 25216 25216 F DEBUG   :     #117 pc 0034f9dd  /system/lib/libart.so (art::(anonymous namespace)::InvokeWithArgArray(art::ScopedObjectAccessAlreadyRunnable const&, art::ArtMethod*, art::(anonymous namespace)::ArgArray*, art::JValue*, char const*)+52)
11-26 06:29:37.301 25216 25216 F DEBUG   :     #118 pc 00350769  /system/lib/libart.so (art::InvokeVirtualOrInterfaceWithJValues(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, _jmethodID*, jvalue*)+316)
11-26 06:29:37.301 25216 25216 F DEBUG   :     #119 pc 0037230d  /system/lib/libart.so (art::Thread::CreateCallback(void*)+900)
11-26 06:29:37.302 25216 25216 F DEBUG   :     #120 pc 000639f5  /system/lib/libc.so (__pthread_start(void*)+22)
11-26 06:29:37.302 25216 25216 F DEBUG   :     #121 pc 0001df65  /system/lib/libc.so (__start_thread+22)

**Comment by gadagashwini** [comment]
@yanceyblog,
Please Provide the exact sequence of commands / steps that you executed before running into the problem. Thanks!

**Comment by gadagashwini** [comment]
@yanceyblog, Provide more information about the issue. Thanks!

**Comment by gadagashwini** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
