### ISSUE TITLE
Missing Operations for TfLite GPU Delegate

### ISSUE THREAD

**Issue by Noltibus** [tensorflow/tensorflow#34679]
**System information**
- TensorFlow version (you are using): 
on Android: 'org.tensorflow:tensorflow-lite:0.0.0-nightly' and 'org.tensorflow:tensorflow-lite-gpu:0.0.0-nightly'
- Are you willing to contribute it (Yes/No): Yes to the best of my possibilities

**Describe the feature and the current behavior/state.**
I'm trying to use the GPU delegate for my custom tflite model. Creating the interpreter with the GPU delegate using this code:
```
 val options = Options()
options.setUseNNAPI(false)
options.setAllowFp16PrecisionForFp32(true)
options.setNumThreads(NUM_THREADS)
val gpuDelegate = GpuDelegate()
options.addDelegate(gpuDelegate)

d.tfLite = Interpreter( loadModelFile(assetManager)!!, options)
```
 results in my model being run normally, hence delivering the correct outputs but not being accelerated by the GPU in my opinion, since the execution time is exactly the same as without using the delegate. Adding the line  `d.tfLite!!.modifyGraphWithDelegate(gpuDelegate)` (I don't know if this is necessary, it would also be nice to know?) results in the following error:
```
java.lang.IllegalArgumentException: Internal error: Failed to apply delegate: Next operations are not supported by GPU delegate:
    CONV_2D: Max version supported: 1. Requested version 2.
    LOCAL_RESPONSE_NORMALIZATION: Operation is not supported.
    SPLIT: Operation is not supported.
    First 0 operations will run on the GPU, and the remaining 12 on the CPU.ModifyGraphWithDelegate is disallowed when graph is immutable.
    java.lang.RuntimeException: java.lang.IllegalArgumentException: Internal error: Failed to apply delegate: Next operations are not supported by GPU delegate:
    CONV_2D: Max version supported: 1. Requested version 2.
    LOCAL_RESPONSE_NORMALIZATION: Operation is not supported.
    SPLIT: Operation is not supported.
    First 0 operations will run on the GPU, and the remaining 12 on the CPU.ModifyGraphWithDelegate is disallowed when graph is immutable.
```

So first of all: It would be nice to have those unsupported operations, i.e. 

- CONV_2D v2
- LOCAL_RESPONSE_NORMALIZATION
- SPLIT

Second of all: what does `ModifyGraphWithDelegate is disallowed when graph is immutable` mean? Do I have to make any changes to my tflite model?

**Comment by jdduke** [comment]
@impjdi are there any plans to support dilation with GPU conv?

**Comment by impjdi** [comment]
@jdduke IIRC we have dilation for all our conv operators.  What is different in `CONV_2D` v2 vs. v1?

@Noltibus 

1. We have limited resource, and probably can't accommodate individual requests of op shader implementations.  We'll keep your request in mind.

2. The error message is coming from `//tensorflow/lite/core/subgraph.cc`... you can grep for that.  I have the impression you're calling `ModifyGraphWithDelegate` twice or maybe after `AllocateTensors` or something?  I'm not entirely sure when a graph is considered immutable without studying the code path.

**Comment by jdduke** [comment]
> IIRC we have dilation for all our conv operators. What is different in CONV_2D v2 vs. v1?

v2 will have dilation values that aren't 1. If that's supported, we can update the GPU delegate to handle that version.

**Comment by Noltibus** [comment]
Is there any way I can help with those operations. For example, the SPLIT operator? It might be somewhat similar to the SLICE operator?

**Comment by Noltibus** [comment]
> > IIRC we have dilation for all our conv operators. What is different in CONV_2D v2 vs. v1?
> 
> v2 will have dilation values that aren't 1. If that's supported, we can update the GPU delegate to handle that version.

Does that mean CONV v2 is "almost" supported?

**Comment by impjdi** [comment]
@Noltibus 

Yeah, I have a change that will open it up which is being reviewed.  In the meantime, you can just comment out the `CONV_2D` operator's version check in `//tensorflow/lite/delegates/gpu/common/model_builder.cc`and things should just work.

**Comment by Noltibus** [comment]
Ok, thank you!! So you will keep my request for LRN in mind? Is there any way I can help with SPLIT. I never wrote an Operation before but I learn pretty quickly ;-)

**Comment by impjdi** [comment]
@Noltibus 

Sure thing.  This is an open source project, and contributions are welcome :)

Before you dig into the shader code, I would advise to understand the DHWC4 format (or PHWC4... we renamed the format at one point) first.  It's essentially slicing a HWC tensor into 4-channel slices; that's used throughout the OpenGL delegate.  I'm not so sure about the OpenCL delegate; it has more complicated formats.

Then, when it comes to the shader code, OpenGL delegate uses shader code generation to avoid code duplication, but unfortunately, it makes reading & understanding hard.  OpenCL doesn't use the code generation logic and might be easier to author one.  After that, you want to also write some unit tests to make sure things work as intended.

Of course, the easiest is to find the closest op implementation and modifying that :)

**Comment by eQueue** [comment]
@Noltibus
hi i'm running posenet example of Tensorflow lite.
i got a same issue in GPU Delegate.
 i found where this app select CPU,GPU, NNAPI.
that file is at android/posenet/src/main/java/org.tensorflow.lite.examples.posenet.lib/Posenet.kt
Unfortunately, posenet example is written of kotlin. so i can't insert your same java code.
i modified,
`class Posenet(
  val context: Context,
  val filename: String = "posenet_model.tflite",
  val device: Device = Device.GPU
) : AutoCloseable {
  var lastInferenceTimeNanos: Long = -1
    private set

  /** An Interpreter for the TFLite model.   */
  private var interpreter: Interpreter? = null
  private var gpuDelegate: GpuDelegate? = null

  private fun getInterpreter(): Interpreter {
    if (interpreter != null) {
      return interpreter!!
    }
    val options = Interpreter.Options()
    when (device) {
      Device.CPU -> { }
      Device.GPU -> {
        gpuDelegate = GpuDelegate()
        options.addDelegate(gpuDelegate)
        options.setNumThreads(4)
        options.setAllowFp16PrecisionForFp32(true)
      }`

but it doesn't change fps. i guess that i just change name of device, not device's actual running.
how can i use correctly device's GPU? how can i modify?
And.. why you insert 
`options.setAllowFp16PrecisionForFp32(true)
options.setNumThreads(NUM_THREADS)`
this line?
if this is absent, it doesn'y use GPU?

**Comment by jdduke** [comment]
@terryheo can help further diagnose.

**Comment by terryheo** [comment]
@eQueue you don't need set threads for GPU.
Just changing
```
val device: Device = Device.CPU
```
to
```
val device: Device = Device.GPU
```
is enough for Posenet example.
BTW, I've found that the current Posenet example depends on TFLite 2.0.0. I'll update it to use TFLite 2.2.0 which gives slightly better performance.

In my testing GPU gives about 35ms inference time with Posenet model.

**Comment by sushreebarsa** [comment]
@Noltibus Is this still an issue ?
Please refer to the [comment](https://github.com/tensorflow/tensorflow/issues/34679#issuecomment-638840216) above and let us know ?Thanks!

**Comment by Noltibus** [comment]
According to the documentation here: https://www.tensorflow.org/lite/performance/gpu_advanced none of the operations I listed above are supported, yet, so this is an ongoing issue for me.

**Comment by impjdi** [comment]
Our documentation is not always up to date.  You want to check the source code ;)

`LOCAL_RESPONSE_NORMALIZATION` <- I've never seen this op and it's unlikely that we'll add this.

`SPLIT` <- depending on the axis, this might be supported or not.

Also, it might be good to upgrade from 0.0.0 to whatever is at the top of the master branch.

**Comment by tilakrayal** [comment]
@Noltibus,
As requested the changes were made with the commit [98203f8](https://github.com/tensorflow/tensorflow/commit/98203f896c2b0a25b4e5d3d62475465df7138f79). Kindly take a look at the model_builder.cc file where split_node was added.

https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/delegates/gpu/common/model_builder.cc

```
    Node* split_node = graph->NewNode();
    RETURN_IF_ERROR(reader->AddInput(split_node, 0));
    {
      SplitAttributes split_attr;
      split_attr.axis = Axis::CHANNELS;
      split_node->operation.type = ToString(OperationType::SPLIT);
      split_node->operation.attributes = split_attr;
    }
```

**Comment by tilakrayal** [comment]
Closing this as stale. Please reopen if this is still a valid request.
