### ISSUE TITLE
how can i visualize activation of a layer?

### ISSUE THREAD

**Issue by molo32** [tensorflow/tensorflow#34671]
python 3
google colab
gpu

**Comment by oanush** [comment]
@molo32 
Please refer the [link](https://towardsdatascience.com/visualizing-intermediate-activation-in-convolutional-neural-networks-with-keras-260b36d60d0) for visualization activation in CNN using keras. Let us know if it helped.
Meanwhile Can you please provide more information issue? Thanks!

**Comment by oanush** [comment]
@molo32 ,
any update on the issue ?Thanks!

**Comment by oanush** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
