### ISSUE TITLE
`py_function` in eager mode with Tensors fails

### ISSUE THREAD

**Issue by jackd** [tensorflow/tensorflow#34674]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 16.04
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): v1.12.1-8709-gddde447 2.0.0-dev20190813
- Python version: 3.6.9

## Current Behaviour

`tf.py_function` fails when run in eager mode with `tf.Tensor`s from `tf.keras.Input`s

## Expected Behariour

Same as in graph mode.

## Code to reproduce the issue
```python
import tensorflow as tf
tf.compat.v1.enable_eager_execution()

x = tf.keras.layers.Input(shape=(), dtype=tf.float32)
y = tf.keras.layers.Input(shape=(), dtype=tf.float32)

def f(x, y):
    return x + y

z = tf.py_function(f, (x, y), tf.float32)
```

## Stack trace
```
Traceback (most recent call last):
  File "../site-packages/tensorflow_core/python/ops/gen_script_ops.py", line 53, in eager_py_func
    token, "is_async", is_async, "Tout", Tout)
tensorflow.python.eager.core._FallbackException: This function does not handle the case of the path where all inputs are not already EagerTensors.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "pfk.py", line 11, in <module>
    z = tf.py_function(f, (x, y), tf.float32)
  File "../site-packages/tensorflow_core/python/ops/script_ops.py", line 404, in eager_py_func
    return _internal_py_func(func=func, inp=inp, Tout=Tout, eager=True, name=name)
  File "../site-packages/tensorflow_core/python/ops/script_ops.py", line 293, in _internal_py_func
    name=name)
  File "../site-packages/tensorflow_core/python/ops/gen_script_ops.py", line 59, in eager_py_func
    ctx=_ctx)
  File "../site-packages/tensorflow_core/python/ops/gen_script_ops.py", line 113, in eager_py_func_eager_fallback
    _attr_Tin, input = _execute.convert_to_mixed_eager_tensors(input, _ctx)
  File "../site-packages/tensorflow_core/python/eager/execute.py", line 277, in convert_to_mixed_eager_tensors
    types = [t._datatype_enum() for t in v]  # pylint: disable=protected-access
  File "../site-packages/tensorflow_core/python/eager/execute.py", line 277, in <listcomp>
    types = [t._datatype_enum() for t in v]  # pylint: disable=protected-access
AttributeError: 'Tensor' object has no attribute '_datatype_enum'
```

**Comment by jackd** [comment]
Workaround: wrap it in a `Lambda`, though this is highly unexpected/unintuitive.

```python
def run(args):
    return tf.py_function(f, args, tf.float32)

z = tf.keras.layers.Lambda(run)([x, y])
```

**Comment by gadagashwini** [comment]
I could reproduce the issue with Tensorflow 2.0.
Please see the colab gist [here](https://colab.sandbox.google.com/gist/gadagashwini/3a4d6e2b631dbf57791b55c689142a0c/untitled279.ipynb). Thanks!

**Comment by robieta** [comment]
Wrapping any graph computation in a Lambda layer or a custom Layer (putting code in the `call` body) is the correct way to do it. There is a mechanism called the TensorFlowOpLayer which tries to wrap "bare" computations in layers, but it is best-effort only. So your workaround isn't really a workaround.

**Comment by jackd** [comment]
Ack, was about to say "I'd prefer a more helpful error message" then I realized the top traceback says almost exactly that - just not where I normally look for the underlying cause...
