### ISSUE TITLE
You must feed a value for placeholder tensor 'Placeholder' with dtype int32

### ISSUE THREAD

**Issue by molo32** [tensorflow/tensorflow#34672]
```
    import tensorflow as tf  

    d1 = tf.placeholder(tf.int32)
    d2 = tf.add(6, 2, name="Add_these_numbers2")
    d3 = tf.add(d1, d2, name="res5")
    d4 = tf.add(d1, d3, name="res5")
    
    with tf.Session() as sess:
       # writer = tf.summary.FileWriter("output", sessi.graph)
        print(sess.run(d3))
        print(sess.run(d4,feed_dict={d1:0}))
```

why do you give me this error?

use python 3 with google colab gpu
F

**Comment by oanush** [comment]
@molo32 ,
Tensor will produce an error unless it value is fed with the` [feed_dict](https://www.tensorflow.org/api_docs/python/tf/compat/v1/placeholder#for_example) `optional argument, line   `print(sess.run(d3))` throws an error as the value is not fed.
Try running the code
```
 import tensorflow as tf  
 d1 = tf.placeholder(tf.int32)
 d2 = tf.add(6, 2, name="Add_these_numbers2")
 d3 = tf.add(d1, d2, name="res5")
 d4 = tf.add(d1, d3, name="res5")
    
 with tf.Session() as sess:
       # writer = tf.summary.FileWriter("output", sessi.graph)
       #print(sess.run(d3)) (remove this line or comment it)
      print(sess.run(d4,feed_dict={d1:0}))
```
kindly find the [gist](https://colab.sandbox.google.com/gist/oanush/b3889cf62e4f582311f34fe67d38c292/34672.ipynb) of colab.Thanks!

**Comment by oanush** [comment]
@molo32 ,
Any update on the issue ?Thanks!

**Comment by oanush** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
