### ISSUE TITLE
How to stop the process while sess.run in TensorFlowInferenceInterface?

### ISSUE THREAD

**Issue by heiwais25** [tensorflow/tensorflow#34670]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using): 2.0
- Are you willing to contribute it (Yes/No): Yes

**Describe the feature and the current behavior/state.**
I'm now developing the application with TensorFlowInferenceInterface in android. What I tried to find was stop function that stop the running calculation by setting some flag that can make calculation quit. However, the only thing I found was `TensorFlowInferenceInterface.close()` that couldn't stop running calculation. 

Is there any feature to set flag to stop the process? If there is already related information, I'm sorry and please let me know :)

**Will this change the current api? How?**
Little bit?

**Who will benefit with this feature?**
Android developers who are running the Tensorflow can make their application more responsive to the user.

**Any Other info.**
I run TensorFlowInferenceInterface with `rxJava` to serve it in background.

Thank you so much!

**Comment by jdduke** [comment]
There's no way to do this. Note that TFLite actually has a cancellation API for doing this, though it's not yet exposed in Java. Is there a reason you have to use TFMobile (used by TensorFlowInferenceInterface) rather than TFLite?

**Comment by heiwais25** [comment]
@jdduke I see. We used TFMobile because TFLite doesn't provide much operations related to the Transformer as I searched correctly. Actually, we will use TFLite if the related operations are implemented. Thank you for your reply :)
