### ISSUE TITLE
Wrong inputs shape for 1D-inputs in keras with run_eagerly=True

### ISSUE THREAD

**Issue by shkarupa-alex** [tensorflow/tensorflow#34687]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Colab
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): default v2 for Colab
- TensorFlow version (use command below): v2.0.0-0-g64c3d382ca 2.0.0
- Python version: default for Colab
- Bazel version (if compiling from source): No
- GCC/Compiler version (if compiling from source): No
- CUDA/cuDNN version: Colab
- GPU model and memory: Colab

**Describe the current behavior**
When compiling keras model with run_eagerly=True and passing 1D-inputs, model reshapes it into 2D.
When compiling with run_eagerly=False everything works as expected: layer obtains 1D-input.

**Describe the expected behavior**
Model should not corrupt inputs shape.

**Code to reproduce the issue**
https://colab.research.google.com/drive/1LHtQRE1CnjkZCOqGe-O7VbBKHWSTCtJS

**Comment by shkarupa-alex** [comment]
Still got this issue in v2.1.0-rc1-0-g064e1535a7 || 2.1.0-rc1

**Comment by jvishnuvardhan** [comment]
@shkarupa-alex I think this was resolved in recent `tf-nightly`. Please change the first line of your code to `!pip install tf-nightly` and run the colab. Here is the output when `run_eagerly=True` was selected.

```
This should be (None,) because of 1D-input:  (2,)
1/1 [==============================] - 0s 1ms/step - loss: 4.0000
<tensorflow.python.keras.callbacks.History at 0x7ff3319e4518>
```

For the same option (`run_eagerly=True`), earlier output is as follows which was not correct.

```
Train on 2 samples
WARNING:tensorflow:Model was constructed with shape Tensor("input_2:0", shape=(None,), dtype=float32) for input (None,), but it was re-called on a Tensor with incompatible shape (2, 1).
This should be (None,) because of 1D-input:  (2, 1)
WARNING:tensorflow:The list of trainable weights is empty. Make sure that you are not setting model.trainable to False before compiling the model.
2/2 [==============================] - 0s 5ms/sample - loss: 4.0000
<tensorflow.python.keras.callbacks.History at 0x7fcb970bc4e0>
```

I am closing this issue as it was resolved. Please feel free to reopen if I am mistaken. Thanks!
