### ISSUE TITLE
TensorArray objects improperly handled as tf.function arguments or return values

### ISSUE THREAD

**Issue by diNatale** [tensorflow/tensorflow#34683]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux, Ubuntu 16.04
- TensorFlow installed from (source or binary): tensorflow-gpu from binary
- TensorFlow version (use command below): 2.0.0
- Python version: 3.6.7
- CUDA/cuDNN version: CUDA 10.0, cuDNN 7.6.0.64
- GPU model and memory: GeForce GTX  1080

**Describe the current behavior**
When you return a created TensorArray from a function decorated with tf.function, the returned object is an empty Tensor with an illegal state:
  object type is **tf.Tensor(<unprintable>, shape=(), dtype=variant)**

This object cannot be used and will throw an exception when attempting to use it.
See also attached image for more details.

Example of the exception, when calling concat method:
AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'concat'

**Describe the expected behavior**
The returned object should be a legal TensorArray instance, as is the case when you use only Eager mode functions.
In this case the object type is **<tensorflow.python.ops.tensor_array_ops.TensorArray object at 0x7f73b0386208>**

The code works fine if all functions are in Eager mode (see code example).
The code works fine if you concat the TensorArray before returning it (see code example).

**Code to reproduce the issue**
```
@tf.function
def accumulate_no_error_graph(d):
    arr = tf.TensorArray(tf.float32, num_rows)

    for i in range(num_rows):
        arr = arr.write(i, d[i])

    return arr.concat()

def accumulate_no_error_eager(d):
    arr = tf.TensorArray(tf.float32, num_rows)

    for i in range(num_rows):
        arr = arr.write(i, d[i])

    return arr

@tf.function
def accumulate_error_graph(d):
    arr = tf.TensorArray(tf.float32, num_rows)

    for i in range(num_rows):
        arr = arr.write(i, d[i])

    return arr

num_rows = 10
a = tf.random.uniform([num_rows, 2])

# Works well
data = accumulate_no_error_eager(a)
print(f'From eager: {data}')

data = accumulate_no_error_graph(a)
print(f'From Graph with concat: {data}')

# Doesn't work!
data = accumulate_error_graph(a)
print(f'From Graph no concat: {data}')
```

**Other info / logs**
Output of the code:
```
From eager: <tensorflow.python.ops.tensor_array_ops.TensorArray object at 0x7ff67c5ac470>
From Graph with concat: [0.6765479  0.28778458 0.85561883 0.41792393 0.667024   0.35702074
 0.33666503 0.6575141  0.05998921 0.06930244 0.05852807 0.65689635
 0.4156996  0.39695132 0.78036475 0.79794145 0.96339357 0.49462914
 0.885311   0.04960382]

Traceback (most recent call last):
ValueError: Tensorflow type 21 not convertible to numpy dtype.
```

![image](https://user-images.githubusercontent.com/569000/69805111-a7970a80-11e8-11ea-8233-54b2385728c0.png)

**Comment by diNatale** [comment]
[https://github.com/tensorflow/tensorflow/issues/30409](url)

**Comment by mdanatg** [comment]
A similar issue is around passing TensorArrays as arguments: https://github.com/tensorflow/tensorflow/issues/30409#issuecomment-508983979

Updating the bug title a bit to catch both cases.

**Comment by ravikyram** [comment]
I have tried on colab with TF version 2.0 ,2.1.0-dev20191128  and was able to reproduce the issue.Please, find the gist [here](https://colab.sandbox.google.com/gist/ravikyram/cc1b34dba4b052e81ff306fc3976507f/untitled415.ipynb). Thanks!

**Comment by saxenasaurabh** [comment]
TensorArrays have completely different representations in graph and eager modes. Inside graphs (tf.function) a TensorArray is a `DT_VARIANT` type tensor wrapping a `vector<Tensor*>` whereas in eager mode it is just a python list of EagerTensors so they are not really interoperable. This was done to avoid keeping a copy of the entire TensorArray when performing an operation in eager mode.

A workaround for now maybe to return `arr.stack()` from the tf.function and unstack the returned value using `tf.TensorArray(tf.float32, num_rows).unstack(accumulate_error_graph(a))`. If we support returning TensorArrays from tf.function this is what we might end up doing under the hood. Even if we don't support this, we should definitely raise a better error message at function tracing time maybe.

**Comment by amahendrakar** [comment]
@diNatale,
Could you please check @saxenasaurabh's workaround and let us know if you are still facing the issue. Thanks!

**Comment by amahendrakar** [comment]
> Could you please check @saxenasaurabh's workaround and let us know if you are still facing the issue. Thanks!

@diNatale,
Any updates regarding this? Please feel free to close the issue if resolved. Thanks!

**Comment by daganesh** [comment]
Hi @amahendrakar ,
Unfortunately I have "neglected" my tf2/eager implementation due to these and a couple more issues, and had to focus hard on pushing on the older version (tf1-compatible).
I will try to give it higher priority soon.
Cheers

**Comment by amahendrakar** [comment]
> Unfortunately I have "neglected" my tf2/eager implementation due to these and a couple more issues, and had to focus hard on pushing on the older version (tf1-compatible).
> I will try to give it higher priority soon.
> Cheers

@daganesh,
Please submit a new issue from [this link](https://github.com/tensorflow/tensorflow/issues/new/choose) and fill in the template, so that we can track the issue there. Thanks!

**Comment by amahendrakar** [comment]
> Any updates regarding this? Please feel free to close the issue if resolved. Thanks!

@diNatale,
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Comment by hadifar** [comment]
Another way to reproduce the exception:

```
import tensorflow.compat.v1 as tf

tf.disable_v2_behavior()

ss = tf.constant([[1, 2, 3, 4, 5], [0, 0, 0, 2, 1]], dtype=tf.float32)
indecies = tf.where(tf.not_equal(ss, 0))

b = tf.compat.v1.raw_ops.DenseToCSRSparseMatrix(dense_input=ss, indices=indecies)

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    print(sess.run(b))
```

Would you please give me some hints to solve the issue?

**Comment by mdanatg** [comment]
Re-opening as we plan to address the issue internally.

@hadifar although it raises the same error, your code describes a different problem - could you file a separate issue?

**Comment by mdanatg** [comment]
This is still on the roadmap, but is not being actively worked on at the moment.

**Comment by mdanatg** [comment]
Not sure why this issue keeps getting auto-closed. It's definitely something we intend to fix.

**Comment by tilakrayal** [comment]
@diNatale,
I tried to execute the code on tf-nightly **v2.13.0-dev20230420** and it was executed without any issue/error. Could you please take a look at the gist of it [here](https://colab.research.google.com/gist/tilakrayal/07a23ee2cae1f11ed923bd7c9434982b/untitled1077.ipynb). Thank you!
