### ISSUE TITLE
Failed to load nodes from frozen graph file(.pb)

### ISSUE THREAD

**Issue by alekdev2019** [tensorflow/tensorflow#34688]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): macOS High Sierra 10.13.6
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: No
- TensorFlow installed from (source or binary): Python binary(pip install tensorflow==1.7.0)
- TensorFlow version (use command below): 1.7.0
- Python version: 3.6.8
- Bazel version (if compiling from source): 0.10.0(never used bazel)
- GCC/Compiler version (if compiling from source): Apple LLVM version 10.0.0 (clang-1000.11.45.5)
- CUDA/cuDNN version: Not used CUDA/cuDNN
- GPU model and memory: Not used GPU

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
When I tried to load frozen graph(.pb) as graph_def, I couldn't get success to run [import_graph_def](https://github.com/tensorflow/tensorflow/blob/9156fcc7a8a901ca9e553297da8237a313255bd8/tensorflow/python/framework/importer.py#L402).
I received a ValueError: **ValueError: graph_def is invalid at node 'inpaint_net/conv1/kernel/Assign': Input tensor 'inpaint_net/conv1/kernel:0' Cannot convert a tensor of type float32 to an input of type float32_ref.**
I found similar issues from #3628 and #24062, but I can not resolve with @barbolo's suggested [code](https://github.com/tensorflow/tensorflow/issues/3628#issuecomment-272147744).

**Describe the expected behavior**
It should load gragh_def object by using [tf.import_graph_def](https://github.com/tensorflow/tensorflow/blob/9156fcc7a8a901ca9e553297da8237a313255bd8/tensorflow/python/framework/importer.py#L402) function.

**Code to reproduce the issue**
```
import tensorflow as tf
from tensorflow.python.platform import gfile
input = 'model/snapmodel-160000.pb'
with tf.Session() as sess:
    print("load graph")
    with gfile.FastGFile(input,'rb') as f:
       graph_def = tf.GraphDef()
    graph_def.ParseFromString(f.read())
    f = open(node_file, 'a')
    # fix nodes
    for node in graph_def.node:
        if node.op == 'RefSwitch':
            node.op = 'Switch'
            for index in range(len(node.input)):
                node.input[index] = node.input[index] + '/read'
        elif node.op == 'AssignSub':
            node.op = 'Sub'
            if 'use_locking' in node.attr: del node.attr['use_locking']
        elif node.op == 'AssignAdd':
            node.op = 'Add'
            if 'use_locking' in node.attr: del node.attr['use_locking']
        elif node.op == 'Assign':
            if 'use_locking' in node.attr: del node.attr['use_locking']

    with sess.graph.as_default() as tf_graph:
        tf.import_graph_def(graph_def, name='')
```

**Other info / logs**
There is full log:
```
/Users/mac/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/Users/mac/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/Users/mac/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:519: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/Users/mac/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:520: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/Users/mac/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:521: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/Users/mac/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:526: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
2019-11-28 05:03:22.022135: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
load graph
Traceback (most recent call last):
  File "/Users/mac/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/importer.py", line 667, in import_graph_def
    op._add_input(source_tensor, dtype=input_type)
  File "/Users/mac/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1898, in _add_input
    (tensor.dtype.name, dtype.name))
TypeError: Cannot convert a tensor of type float32 to an input of type float32_ref

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Applications/PyCharm.app/Contents/helpers/pydev/pydevd.py", line 1664, in <module>
    main()
  File "/Applications/PyCharm.app/Contents/helpers/pydev/pydevd.py", line 1658, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/Applications/PyCharm.app/Contents/helpers/pydev/pydevd.py", line 1068, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/Applications/PyCharm.app/Contents/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/Volumes/Work/2019_Work/Inpainting/tensorflow-onnx/convert.py", line 68, in <module>
    tf.import_graph_def(graph_def, name='')
  File "/Users/mac/anaconda3/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 432, in new_func
    return func(*args, **kwargs)
  File "/Users/mac/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/importer.py", line 671, in import_graph_def
    node, 'Input tensor %r %s' % (input_name, te)))
ValueError: graph_def is invalid at node 'inpaint_net/conv1/kernel/Assign': Input tensor 'inpaint_net/conv1/kernel:0' Cannot convert a tensor of type float32 to an input of type float32_ref.
```

Please give me a help for resolving this issue asap.
Thank you

**Comment by gadagashwini** [comment]
@alekdev2019, Thanks for reporting issue.
Could you please try against latest TF version 1.15.0. 
Let us know how it progresses. Thanks!

**Comment by alekdev2019** [comment]
Helo @gadagashwini 
Thank you for your reply.
But I should use TF 1.7.0 because [model](https://github.com/JiahuiYu/generative_inpainting) was trained by TF 1.7.0.
I've tested [this project](https://github.com/JiahuiYu/generative_inpainting) with another TF version, but it only work with TF 1.7.0.
Please let me know how I can resolve above issue.
Thank you

**Comment by gadagashwini** [comment]
@alekdev2019, Could you post the .pb file to reproduce the reported issue. Thanks!

**Comment by alekdev2019** [comment]
@gadagashwini , there is my frozen_graph file path:
https://drive.google.com/open?id=1tnMg5GVn7R8gU-X5yiORQN8wKsr2X8lW

Thank you.

**Comment by gadagashwini** [comment]
@alekdev2019, tried to replicate the reported issue but received different error message. 
Please see the [gist](https://colab.sandbox.google.com/gist/gadagashwini/098f8779983524ad7a18fa24cd31c843/untitled291.ipynb) and provide more information. Thanks!

**Comment by alekdev2019** [comment]
@gadagashwini , I have checked your logs and not sure if you copied pb file at the path correctly.
If you copied the file correctly, then it seems like dependency's version issue.
There are my dependencies:
```
pip list
Package             Version   
------------------- ----------
absl-py             0.8.1     
asn1crypto          1.2.0     
astor               0.8.0     
attrs               19.3.0    
bleach              1.5.0     
certifi             2019.11.28
cffi                1.13.2    
chardet             3.0.4     
coverage            4.5.4     
cryptography        2.8       
future              0.18.2    
gast                0.3.2     
grpcio              1.25.0    
html5lib            0.9999999 
idna                2.8       
importlib-metadata  1.1.0     
Keras-Applications  1.0.8     
Keras-Preprocessing 1.1.0     
Markdown            3.1.1     
mock                3.0.5     
more-itertools      7.2.0     
numpy               1.17.4    
packaging           19.2      
parameterized       0.7.0     
pip                 19.3.1    
pluggy              0.13.1    
protobuf            3.11.1    
py                  1.8.0     
pycparser           2.19      
pyOpenSSL           19.1.0    
pyparsing           2.4.5     
PySocks             1.7.1     
pytest              5.3.1     
pytest-cov          2.8.1     
pytest-runner       5.2       
PyYAML              5.1.2     
requests            2.22.0    
setuptools          42.0.1    
six                 1.13.0    
tensorboard         1.7.0     
tensorflow          1.7.0     
termcolor           1.1.0     
typing-extensions   3.7.4.1   
urllib3             1.25.7    
wcwidth             0.1.7     
Werkzeug            0.16.0    
wheel               0.33.6    
zipp                0.6.0 
```

Please let me know if my env resolve your problems.
Thank you

**Comment by gowthamkpr** [comment]
@alekdev2019 May be this [comment](https://github.com/tensorflow/tensorflow/issues/3628#issuecomment-272149052) might help you to solve your problem.
Unfortunately I don't have a great solution for this yet, partly because I haven't been able to create a simple reproducible test case.

Also would recommend you to post this question in stackoverflow where the community may help. Thanks!
