### ISSUE TITLE
API Documentation - Incorrect formatting for tanh activation function

### ISSUE THREAD

**Issue by benchislett** [tensorflow/tensorflow#34694]
## URL(s) with the issue:

https://www.tensorflow.org/api_docs/python/tf/keras/activations/tanh

## Description of issue (what needs changing):

The arguments section of the tanh activation documentation is not formatted correctly.

I am uncertain as to why, but suspect it may be due to a lack of a newline after the example block ([code here](https://github.com/tensorflow/tensorflow/blob/r2.0/tensorflow/python/keras/activations.py#L201-L221))

**Comment by nikochiko** [comment]
@benchislett , thanks for reporting, but the issue has actually already been fixed in the `master` branch [here](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/keras/activations.py#L225-L243).

**Comment by benchislett** [comment]
Great! Thanks for letting me know.
