### ISSUE TITLE
Attention of the value_embeddings inputs

### ISSUE THREAD

**Issue by vsuarezpaniagua** [tensorflow/tensorflow#34696]
This [line](https://github.com/tensorflow/tensorflow/blob/1cf0898dd4331baf93fe77205550f2c2e6c90ee5/tensorflow/python/keras/layers/dense_attention.py#L241) and this [one](https://github.com/tensorflow/tensorflow/blob/1cf0898dd4331baf93fe77205550f2c2e6c90ee5/tensorflow/python/keras/layers/dense_attention.py#L368) should be:
```
value_embeddings = token_embedding(value_input)
```

**Comment by gadagashwini** [comment]
Similar issue [#34283](https://github.com/tensorflow/tensorflow/issues/34283). Thanks!

**Comment by ymodak** [comment]
This is fixed now. Thanks!
