### ISSUE TITLE
Using clip_by_value anywhere in the model graph (including in a metric) produces a model which cannot be saved as h5.

### ISSUE THREAD

**Issue by feature-engineer** [tensorflow/tensorflow#34690]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 7 and Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.0
- Python version: 3.7.4 and 3.6.8

**Describe the current behavior**

Using a custom metric function which employs tf.clip_by_value, then adding it to the model by model.add_loss, and attempting to save it using model.save results in a ValueError exception saying "Unable to create group (name already exists) - full trace provided at the end.

Playing around with this model, the custom metric is irrelevant, it also happens with this:

```python
from tensorflow.keras import Model, layers
import tensorflow as tf

x = layers.Input((10, 10, 1))
t = tf.clip_by_value(x, 0, 1)
pred = layers.Dense(8, activation='relu')(t)
model = Model(inputs=x, outputs=pred)
model.compile(loss='binary_crossentropy', optimizer='adam')
model.save('bla.h5')
```

**Describe the expected behavior**
I would expect the model to get saved without an issue.

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

```python
from tensorflow.keras import Model, layers
import tensorflow as tf

x = layers.Input((10, 10, 1))
pred = layers.Dense(8, activation='relu')(x)
model = Model(inputs=x, outputs=pred)

def custom_metric(y_pred):
    y_pred = tf.clip_by_value(y_pred, 0, 1)
    return tf.reduce_mean(y_pred)

model.add_metric(custom_metric(pred), name='val_custom', aggregation='mean')

model.compile(loss='binary_crossentropy', optimizer='adam')
model.save('bla.h5')
```

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

```python
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-6-11f183ffac31> in <module>
----> 1 model.save('bla.h5')

~/projects/tensorflow/env/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/network.py in save(self, filepath, overwrite, include_optimizer, save_format, signatures, options)
    973     """
    974     saving.save_model(self, filepath, overwrite, include_optimizer, save_format,
--> 975                       signatures, options)
    976 
    977   def save_weights(self, filepath, overwrite=True, save_format=None):

~/projects/tensorflow/env/lib/python3.6/site-packages/tensorflow_core/python/keras/saving/save.py in save_model(model, filepath, overwrite, include_optimizer, save_format, signatures, options)
    110           'or using `save_weights`.')
    111     hdf5_format.save_model_to_hdf5(
--> 112         model, filepath, overwrite, include_optimizer)
    113   else:
    114     saved_model_save.save(model, filepath, overwrite, include_optimizer,

~/projects/tensorflow/env/lib/python3.6/site-packages/tensorflow_core/python/keras/saving/hdf5_format.py in save_model_to_hdf5(model, filepath, overwrite, include_optimizer)
    107     model_weights_group = f.create_group('model_weights')
    108     model_layers = model.layers
--> 109     save_weights_to_hdf5_group(model_weights_group, model_layers)
    110 
    111     # TODO(b/128683857): Add integration tests between tf.keras and external

~/projects/tensorflow/env/lib/python3.6/site-packages/tensorflow_core/python/keras/saving/hdf5_format.py in save_weights_to_hdf5_group(f, layers)
    623 
    624   for layer in layers:
--> 625     g = f.create_group(layer.name)
    626     weights = _legacy_weights(layer)
    627     weight_values = K.batch_get_value(weights)

~/projects/tensorflow/env/lib/python3.6/site-packages/h5py/_hl/group.py in create_group(self, name, track_order)
     66             name, lcpl = self._e(name, lcpl=True)
     67             gcpl = Group._gcpl_crt_order if track_order else None
---> 68             gid = h5g.create(self.id, name, lcpl=lcpl, gcpl=gcpl)
     69             return Group(gid)
     70 

h5py/_objects.pyx in h5py._objects.with_phil.wrapper()

h5py/_objects.pyx in h5py._objects.with_phil.wrapper()

h5py/h5g.pyx in h5py.h5g.create()

ValueError: Unable to create group (name already exists)
```

**Comment by gadagashwini** [comment]
Issue is replicating with Tensorflow 2.0.
Please see the [gist](https://colab.sandbox.google.com/gist/gadagashwini/4c0112dd8bb56b7ae29c0b39b02931e3/untitled283.ipynb). Thanks!

**Comment by rmothukuru** [comment]
@feature-engineer,
 The Model will be Saved successfully if you use `model.save('bla')` for saving the Model. Here is the [Gist](https://colab.sandbox.google.com/gist/rmothukuru/d95c4d04bb6c37ad8326e4401d63f110/untitled283.ipynb). Thanks!

**Comment by rmothukuru** [comment]
@feature-engineer,
Can you please let us know if your issue is resolved. Thanks!

**Comment by feature-engineer** [comment]
@rmothukuru That's certainly a workaround. However I would like to use the h5 format, and I think it should still be a bug to resolve if tensorflow isn't planning on deprecating this format.

**Comment by jvishnuvardhan** [comment]
@feature-engineer I think this was resolved in `tf-nightly`. I cannot reproduce the issue with `tf-nightly`. Please take a look at the [gist here](https://colab.sandbox.google.com/gist/jvishnuvardhan/ac8ce65ee413880f26d189b31a9b0f63/untitled283.ipynb). Thanks!

**Comment by feature-engineer** [comment]
Yes, it indeed seem to have been resolved.

**Comment by fzyzcjy** [comment]
It still does not work in tf 2.1...

**Comment by jvishnuvardhan** [comment]
@fzyzcjy Please check with `tf-nightly`. There were lots of modifications after `TF2.1`, so the updated code is `tf-nightly`. Currently `TF2.2.0-rc2` released and i think the stable `TF2.2` will be released in near future. Thanks!

**Comment by fzyzcjy** [comment]
@jvishnuvardhan Sorry is it stable enough? I am afraid nightly will contain strange bugs...?

**Comment by jvishnuvardhan** [comment]
@fzyzcjy I guess there will be a stable `TF2.2` in near future. It is currently `TF2.2.0-rc2`. Thanks!
