### ISSUE TITLE
Raspberry Pi Bazel Build "Define appropriate PLATFORM macro" error

### ISSUE THREAD

**Issue by samjabrahams** [tensorflow/tensorflow#3469]
When building TensorFlow on Raspberry Pi with Bazel, the pre-compiler end up throwing this error:

```
Define the appropriate PLATFORM_<foo> macro for this platform
```

From what I've been able to gather, here's the cause of the issue:
1. Because Raspberry Pi uses an ARM CPU, the `IS_MOBILE_PLATFORM` macro is defined [in `tensorflow/core/platform/platform.h](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/platform/platform.h#L45)
2. Later, when trying to compile [png.h](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/platform/png.h#L23-L26), [gif.h](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/platform/gif.h), or [jpeg.h](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/platform/jpeg.h), the if/else statements fall through, leaving with the default option to throw an error.
### Environment info

Operating System: Raspbian GNU/Linux, version 8.0

Installed version of CUDA and cuDNN: N/A

Installed from source.
1. The commit hash : e95f4e760c6b6713b6b686ebeff9a1586a5831dd
2. The output of `bazel version` : 

```
Build label: 0.2.1-2016-06-13 (@447f7f3)
Build target: bazel-out/local_linux-fastbuild/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Mon Jun 13 19:05:24 2016 (1465844724)
Build timestamp: 1465844724
Build timestamp as int: 1465844724
```
### Steps to reproduce
1. Build TensorFlow from source on Raspberry Pi [as described in this guide](https://github.com/samjabrahams/tensorflow-on-raspberry-pi/blob/master/GUIDE.md) _without_ deleting [this line from `tensorflow/core/platform/platform.h`](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/platform/platform.h#L45), which defines `IS_MOBILE_PLATFORM` when compiling on ARM devices.
### What have you tried?
1. Deleted the line mentioned above, which fixes the problem for local builds
### Logs or other output that would be helpful

[define_macro_error.txt](https://github.com/tensorflow/tensorflow/files/378789/define_macro_error.txt)

**Comment by samjabrahams** [comment]
According to [this post on StackExchange](http://raspberrypi.stackexchange.com/questions/754/how-can-i-detect-that-im-compiling-for-raspberry-pi), it looks like there's no reliable, automatic way to detect if building for Raspberry Pi. 

Would it be possible to add in a `#if  !defined(PLATFORM_RASPBERRY_PI)` line in [`platform.h`](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/platform/platform.h#L45) and define the macro manually in Bazel with `--copt="-D PLATFORM_RASPBERRY_PI"`?

**Comment by danbri** [comment]
@petewarden any thoughts?

**Comment by petewarden** [comment]
No update on this one I'm afraid. I've been focused on the makefile approach to building for the Pi, and I'm not familiar enough with Bazel to suggest the right way to handle this.

**Comment by drpngx** [comment]
Closing this -- we only support Makefile builds right now.

**Comment by samjabrahams** [comment]
Ok, no worries- I'll keep maintaining my repo for those who want a Python interface on their Raspberry Pi.

**Comment by EddieOne** [comment]
Long build process of the Raspberry Pi.
