### ISSUE TITLE
How to view CI build history of master branch

### ISSUE THREAD

**Issue by youhanmo** [tensorflow/tensorflow#34703]
Hi team,
How can I view the CI build history in ci systems internal to Google or in Jenkins ?
I did not find the url of the build history of tensorflow master branch.
Any ideas ? Thank you.

**Comment by ymodak** [comment]
From the raised pull request after approval from reviewer you may see build tests populating. If you click on the details link on any of the completed tests you should be able to see all results of CI builds.
See https://github.com/tensorflow/tensorflow/tree/master/tensorflow/tools/ci_build#view-ci-results
