### ISSUE TITLE
allow_growth not working when using estimator and MirroredStrategy distribution

### ISSUE THREAD

**Issue by tz301** [tensorflow/tensorflow#34709]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04.3 LTS
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 1.14.0
- Python version: 3.6.8
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 10.0.130/7.6.4
- GPU model and memory: 8 * Tesla P40, 22919MiB

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**

When I use estimator and distribute.MirroredStrategy, it will allocate all GPU memory, even if I just use one GPU.

```
import tensorflow as tf
session_config = tf.ConfigProto()
session_config.gpu_options.allow_growth = True
session_config.allow_soft_placement = True
strategy = tf.contrib.distribute.MirroredStrategy(num_gpus=num_gpus)
config = tf.estimator.RunConfig(session_config=session_config, train_distribute=strategy)
estimator = tf.estimator.Estimator(model_fn, model_dir, config, params)
estimator.train()
```

If I set `os.environ["TF_FORCE_GPU_ALLOW_GROWTH"] = "true"`, GPU memory will be correctly allocated. 

I don't know if it's related to `session_config.allow_soft_placement = True`, but if I don't set this value, it will raise error "cannot assign a device for operation argmax".

**Describe the expected behavior**

Make "allow_growth" working when using estimator and MirroredStrategy distribution.

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

```
import os
import tensorflow as tf
import tensorflow.keras.layers as layers
import numpy as np


def model_fn(features, labels, mode):
  """A simple 2-classify model.
  
  """
  model = tf.keras.Sequential([layers.Dense(80, activation="relu"), layers.Dense(2)])
  logits = model(features)
  loss = tf.losses.softmax_cross_entropy(labels, logits)

  if mode == tf.estimator.ModeKeys.TRAIN:
    optimizer = tf.train.AdamOptimizer(learning_rate=0.001)
    train_op = optimizer.minimize(loss, tf.train.get_global_step())
    return tf.estimator.EstimatorSpec(mode, loss=loss, train_op=train_op)


def input_fn():
  """dataset that return feature and label.

  """
  features_mat = np.random.randn(10, 10) 
  labels_mat = np.random.randint(0, 2, size=(10, 2)) 
  dataset = tf.data.Dataset.from_tensor_slices((features_mat, labels_mat))
  return dataset.batch(1)

os.environ["CUDA_VISIBLE_DEVICES"] = "0"  # Set available GPU id. 
session_config = tf.ConfigProto()
session_config.gpu_options.allow_growth = True

session_config.allow_soft_placement = True
strategy = tf.contrib.distribute.MirroredStrategy(num_gpus=1)
config = tf.estimator.RunConfig(session_config=session_config, train_distribute=strategy)
# If disable above 3 lines and using following line, GPU memory allocation will be correct.
#config = tf.estimator.RunConfig(session_config=session_config)

estimator = tf.estimator.Estimator(model_fn, config=config)

while True:
  estimator.train(input_fn)
```

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.
