### ISSUE TITLE
Complete support for LSTM/GRU for TFLite

### ISSUE THREAD

**Issue by justlike-prog** [tensorflow/tensorflow#34706]
**System information**
- TensorFlow version (you are using): 2.0
- Are you willing to contribute it (Yes/No): Yes

**Describe the feature and the current behavior/state.**

Reading the [roadmap](https://www.tensorflow.org/lite/guide/roadmap) of Tensorflow Lite for 2019 there should be full LSTM/GRU support by the end of this year, but I don't seen anything done, also no recent update of the state of the roadmap. At the moment there are two [workarounds](https://www.tensorflow.org/lite/convert/rnn) that work suboptimally. I have never been able to reproduce nearly the results I had with plain TF.

**Who will benefit with this feature?**

I think having LSTM/GRU is crucial since a lot of architectures are using them and mobile/embedded DL development is a big topic right now.

**Comment by ymodak** [comment]
You may try using ```experimental_new_converter``` in latest tf-nightly builds to convert your lstm models in TF Lite.
See https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/examples/experimental_new_converter/keras_lstm.ipynb

**Comment by justlike-prog** [comment]
Hmm yeah that's another workaround I guess. If there is a way to help with the implementation I would be willing to do it if I get some guidance from a person that worked on it a bit and has a rough idea what has to be done.

**Comment by justlike-prog** [comment]
hey what is the status on this? I proposed (with another account) to work on this issue as a part of a GSoC project but didnt get any answers as for mentorship yet. Anyone has a clue who I could contact directly in this matter?

**Comment by ashwinmurthy** [comment]
@justlike-prog  We recently announce TF 2.0 Keras to TFLite fused LSTM conversion support.

Please see below:
https://groups.google.com/a/tensorflow.org/g/tflite/c/Ub4apUvblN8

Would you be interested in trying this out? this is an e2e solution, once you get the fused LSTM in Tflite, that can also be quantized.

**Comment by ymodak** [comment]
TensorFlow RNN conversion to TensorFlow Lite is supported from TF 2.3 release.
See https://www.tensorflow.org/lite/convert/rnn#tensorflow_rnns_apis_supported
Thanks!
