### ISSUE TITLE
Docker build for TensorFlow GPU taking too long(Up 45 hours!) 

### ISSUE THREAD

**Issue by RafayAK** [tensorflow/tensorflow#34719]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04.3 LTS
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): Docker image (tensorflow/tensorflow:devel-gpu-py3)
- TensorFlow version: 2.0
- Python version: 3
- Installed using virtualenv? pip? conda?: Docker 
- Bazel version (if compiling from source): default for docker image
- GCC/Compiler version (if compiling from source): default for docker image
- CUDA/cuDNN version: 10.0
- GPU model and memory: GT 750m
- CPU: Intel® Core™ i7-4500U CPU @ 1.80GHz × 4 

**Describe the problem**
I'm trying to build TensorFlow for my GPU with CUDA compute capability 3.0. The build seems to take forever to complete.
I'm following these guides:
[Build from source using Docker](https://www.tensorflow.org/install/source#gpu_support_3)
[Setup Docker for TensorFlow ](https://www.tensorflow.org/install/docker)

I can't figure out if I did something wrong.

**Provide the exact sequence of commands/steps that you executed before running into the problem**

Following Docker commands were used to run the container:
```
docker pull tensorflow/tensorflow:devel-gpu-py3
docker run --gpus all -it -w /tensorflow -v $PWD:/mnt -e HOST_PERMS="$(id -u):$(id -g)" tensorflow/tensorflow:devel-gpu-py3 bash
```

Then navigating to `tensorflow_src`,  `./configure` the command was run setting all values to defaults and "No" to all features(CUDA and CUdnn were automatically detected)

Finally, the following command was run to start the build process:
```
bazel build --config=v2 --config=opt --config=cuda //tensorflow/tools/pip_package:build_pip_package
```

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

Currently, the container has been up for 45 hours!. It doesn't seem like it is coming to end anytime soon. At the time of writing Bazel build is on action 29,910/29,333.
```
CONTAINER ID        IMAGE                                 COMMAND             CREATED             STATUS              PORTS               NAMES
9bcd8e96c6ce        tensorflow/tensorflow:devel-gpu-py3   "bash"              45 hours ago        Up 45 hours                             cool_spence
```

**Comment by TeammakS** [comment]
use the update and the upgrade and then run the code in the docker cloud.

**Comment by RafayAK** [comment]
@TeammakS Thanks for the response I'll try it out.
A few more questions: 
1. During the configuration procedure, I am not prompted to specify a list of CUDA compute capabilities or if I want TensorRT or not like many tutorials point out. All these seem to be automatically set.
opening up `.tf_configure.bazelrc ` I see `TF_CUDA_COMPUTE_CAPABILITIES="3.5,5.2,6.0,6.1,7.0` and `--config=tensorrt` already set.

2. Any idea how I can install the resulting wheel file into a conda environment? Can't seem to get gpu up and running.(Installed `conda install -c anaconda cudnn` and 
`conda install -c anaconda cudatoolkit=10.0`)

**Comment by RafayAK** [comment]
Following is the log when I try to execute `tf.test.is_gpu_available()`:
```
WARNING:tensorflow:From <stdin>:1: is_gpu_available (from tensorflow.python.framework.test_util) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.config.experimental.list_physical_devices('GPU')` instead.
2019-12-01 21:56:33.548107: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1
2019-12-01 21:56:33.682574: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-12-01 21:56:33.684118: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1546] Found device 0 with properties: 
name: GeForce GT 750M major: 3 minor: 0 memoryClockRate(GHz): 0.967
pciBusID: 0000:04:00.0
2019-12-01 21:56:33.684692: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcudart.so.10.0'; dlerror: libcudart.so.10.0: cannot open shared object file: No such file or directory
2019-12-01 21:56:33.684925: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcublas.so.10.0'; dlerror: libcublas.so.10.0: cannot open shared object file: No such file or directory
2019-12-01 21:56:33.685130: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcufft.so.10.0'; dlerror: libcufft.so.10.0: cannot open shared object file: No such file or directory
2019-12-01 21:56:33.685326: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcurand.so.10.0'; dlerror: libcurand.so.10.0: cannot open shared object file: No such file or directory
2019-12-01 21:56:33.685525: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcusolver.so.10.0'; dlerror: libcusolver.so.10.0: cannot open shared object file: No such file or directory
2019-12-01 21:56:33.685724: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcusparse.so.10.0'; dlerror: libcusparse.so.10.0: cannot open shared object file: No such file or directory
2019-12-01 21:56:33.685966: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcudnn.so.7'; dlerror: libcudnn.so.7: cannot open shared object file: No such file or directory
2019-12-01 21:56:33.686020: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1569] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...
2019-12-01 21:56:33.779228: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1087] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-12-01 21:56:33.779302: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1093]      0 
2019-12-01 21:56:33.779333: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1106] 0:   N 
False
```

**Comment by gadagashwini** [comment]
@RafayAK, Follow the instructions mentioned [here](https://www.tensorflow.org/install/gpu#ubuntu_1804_cuda_10) to install CUDA and cuDNN.
GPU support Tensorflow uses nvidia-docker. Please install nvidia-docker and try again. Thanks!

**Comment by RafayAK** [comment]
@gadagashwini did follow that. Unfortunately, some of the instructions do not apply to legacy hardware. Nvidia Docker is installed. Secondly, can you help answer the following questions?

> @TeammakS Thanks for the response I'll try it out.
> A few more questions:
> 
> 1. During the configuration procedure, I am not prompted to specify a list of CUDA compute capabilities or if I want TensorRT or not like many tutorials point out. All these seem to be automatically set.
>    opening up `.tf_configure.bazelrc ` I see `TF_CUDA_COMPUTE_CAPABILITIES="3.5,5.2,6.0,6.1,7.0` and `--config=tensorrt` already set.
> 2. Any idea how I can install the resulting wheel file into a conda environment? Can't seem to get gpu up and running.(Installed `conda install -c anaconda cudnn` and
>    `conda install -c anaconda cudatoolkit=10.0`)

**Comment by gadagashwini** [comment]
@RafayAK, Could you include ./configure output here.

**Comment by RafayAK** [comment]
This is how I set up my config file:
```
root@ba5c2e5a2d2b:/tensorflow_src# ./configure 
Extracting Bazel installation...
WARNING: --batch mode is deprecated. Please instead explicitly shut down your Bazel server using the command "bazel shutdown".
You have bazel 0.26.1 installed.
Please specify the location of python. [Default is /usr/local/bin/python]: 


Found possible Python library paths:
  /usr/local/lib/python3.6/dist-packages
  /usr/lib/python3/dist-packages
Please input the desired Python library path to use.  Default is [/usr/local/lib/python3.6/dist-packages]

Do you wish to build TensorFlow with XLA JIT support? [Y/n]: n
No XLA JIT support will be enabled for TensorFlow.

Do you wish to build TensorFlow with OpenCL SYCL support? [y/N]: N
No OpenCL SYCL support will be enabled for TensorFlow.

Do you wish to build TensorFlow with ROCm support? [y/N]: N
No ROCm support will be enabled for TensorFlow.

Found CUDA 10.0 in:
    /usr/local/cuda-10.0/lib64
    /usr/local/cuda-10.0/include
Found cuDNN 7 in:
    /usr/lib/x86_64-linux-gnu
    /usr/include
Found TensorRT 5 in:
    /usr/lib/x86_64-linux-gnu
    /usr/include/x86_64-linux-gnu


Do you want to use clang as CUDA compiler? [y/N]: N
nvcc will be used as CUDA compiler.

Please specify which gcc should be used by nvcc as the host compiler. [Default is /usr/bin/gcc]: 


Please specify optimization flags to use during compilation when bazel option "--config=opt" is specified [Default is -march=native -Wno-sign-compare]: 


Would you like to interactively configure ./WORKSPACE for Android builds? [y/N]: N
Not configuring the WORKSPACE for Android builds.

Preconfigured Bazel build configs. You can use any of the below by adding "--config=<>" to your build command. See .bazelrc for more details.
	--config=mkl         	# Build with MKL support.
	--config=monolithic  	# Config for mostly static monolithic build.
	--config=ngraph      	# Build with Intel nGraph support.
	--config=numa        	# Build with NUMA support.
	--config=dynamic_kernels	# (Experimental) Build kernels into separate shared objects.
	--config=v2          	# Build TensorFlow 2.x instead of 1.x.
Preconfigured Bazel build configs to DISABLE default on features:
	--config=noaws       	# Disable AWS S3 filesystem support.
	--config=nogcp       	# Disable GCP support.
	--config=nohdfs      	# Disable HDFS support.
	--config=nonccl      	# Disable NVIDIA NCCL support.
Configuration finished

```

**Comment by RafayAK** [comment]
Also here is the build configuration, as set in the `.tf_configure.bazelrc` (notice how `build:xla` is set to true, even after its 'No' in the `.configure` file)

```
build --action_env PYTHON_BIN_PATH="/usr/local/bin/python"
build --action_env PYTHON_LIB_PATH="/usr/local/lib/python3.6/dist-packages"
build --python_path="/usr/local/bin/python"
build:xla --define with_xla_support=true
build --config=tensorrt
build --action_env TF_CUDA_VERSION="10.0"
build --action_env TF_CUDNN_VERSION="7"
build --action_env CUDA_TOOLKIT_PATH="/usr/local/cuda-10.0"
build --action_env TF_CUDA_COMPUTE_CAPABILITIES="3.5,5.2,6.0,6.1,7.0"
build --action_env LD_LIBRARY_PATH="/usr/local/cuda/extras/CUPTI/lib64:/usr/local/cuda/lib64:/usr/local/nvidia/lib:/usr/local/nvidia/lib64"
build --action_env GCC_HOST_COMPILER_PATH="/usr/bin/gcc"
build --config=cuda
build:opt --copt=-march=native
build:opt --copt=-Wno-sign-compare
build:opt --host_copt=-march=native
build:opt --define with_default_optimizations=true
test --flaky_test_attempts=3
test --test_size_filters=small,medium
test --test_tag_filters=-benchmark-test,-no_oss,-oss_serial
test --build_tag_filters=-benchmark-test,-no_oss
test --test_tag_filters=-no_gpu
test --build_tag_filters=-no_gpu
test --test_env=LD_LIBRARY_PATH
build --action_env TF_CONFIGURE_IOS="0"
```

**Comment by RafayAK** [comment]
Added the .configue output, 8 days ago

**Comment by suphoff** [comment]
Looks like the tensorflow/tensorflow:devel-gpu-py3 image is stale and is no longer being updated.
( last update > 2 month ago )

**Comment by RafayAK** [comment]
@suphoff any idea what I should do then?

**Comment by suphoff** [comment]
@RafayAK : I would just use "tensorflow/tensorflow:devel-gpu" and add python3 + (required python packages) as this is a lot easier then gathering the cuda requirements. Additionally I would open a new issue about the missing updates of  the "tensorflow/tensorflow:devel-gpu-py3" image.

**Comment by suphoff** [comment]
@RafayAK : FYI: Docker files for creating your own images are now in tensorflow/tools/dockerfiles/dockerfiles

**Comment by RafayAK** [comment]
@suphoff Thanks! I'll check it out

**Comment by bhack** [comment]
I think that we could track this in https://github.com/tensorflow/build/issues/5

**Comment by sanatmpa1** [comment]
@RafayAK,

We are checking to see if you still need help on this issue. We recommend that you upgrade to `2.6` which is latest stable version of TF and let us know if the issue still persists in newer versions. 

You can use this [guide](https://www.tensorflow.org/install/docker) for your reference.Thanks!
