### ISSUE TITLE
TensorFlow 1.15.0 fails to build .so files in contrib 

### ISSUE THREAD

**Issue by maziyarpanahi** [tensorflow/tensorflow#34714]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): macOS Catalina, Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): source
- TensorFlow version: 1.15
- Python version: 3
- Installed using virtualenv? pip? conda?: conda
- Bazel version (if compiling from source): 0.26.1
- GCC/Compiler version (if compiling from source): 
macOS: Apple clang version 11.0.0 (clang-1100.0.33.12)
Ubuntu 18.04: 7.x
Ubuntu 16.04: 5.x
- CUDA/cuDNN version:
- GPU model and memory:
Only the machine with Ubuntu 16.04 has Tesla and CUDA

**Describe the problem**
I am trying to generate two `.so` files from contrib in TensorFlow `1.15.0`. I understand this version comes without contrib, so when it's installed via `pip` or `conda` I cannot find my two `.so` files like previous versions (1.12.0, 1.13.1): `_lstm_ops.so` and `_sparse_feature_cross_op.so`. However, if I build from the source of TF 1.15.0 in Ubuntu 16.04 I can see these two files for Linux. Since I need these two for macOS as well I tried to build from the source on my macOS. 

The build goes until the end without any problem, however, I cannot find these two `.so` files on my macOS. I have tried to replicate the same thing on Ubuntu 18.04, but I cannot find the `.so` files there neither. It seems the only place I can build from the source and get my `.so` files is in Ubuntu 16.04. 

How is it possible that Ubuntu 16.04 can build TF 1.15 from source and produce those two `.so` files, but it fails in macOS Catalina and Ubuntu 18.04? Is it because these two are newer systems? Is there a requirement for contrib to be a lower version?

**Provide the exact sequence of commands / steps that you executed before running into the problem**

- git clone TensorFlow
- git checkout r1.15
- ./configure (no gpu or anything extra - no to all questions)
- bazel build for java

The mentioned steps will produce the `.so` files I required in Ubuntu 16.04 but fail to do so in macOS (Catalina) nor in Ubuntu 18.04. 

The command to build from source for Java:
```bash
bazel build //tensorflow/java:tensorflow //tensorflow/java:libtensorflow_jni
```

**Any other info / logs**
No, there is no error in any of the builds (Java, Python) in any of the three OS.

**Comment by maziyarpanahi** [comment]
I appreciate your help @angerson! Please let me know if you need more info or any test you need me to do.

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.
