### ISSUE TITLE
How to boost speed for cpu in TF2?

### ISSUE THREAD

**Issue by songs18** [tensorflow/tensorflow#34717]
I am running a program based on tensorflow2.0 and do not use GPU, i use the 'top' command, i found the CPU's usage is strange:
%Cpu0  : 21.0 us,  1.0 sy,  0.0 ni, 78.0 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
%Cpu1  : 15.7 us,  0.0 sy,  0.0 ni, 84.3 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
%Cpu2  : 13.8 us,  1.3 sy,  0.0 ni, 84.8 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
%Cpu3  : 15.2 us,  1.3 sy,  0.0 ni, 83.4 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
%Cpu4  : 18.1 us,  1.3 sy,  0.0 ni, 80.6 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
%Cpu5  : 14.9 us,  1.4 sy,  0.0 ni, 83.8 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
%Cpu6  :  3.7 us,  1.3 sy,  0.0 ni, 95.0 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
%Cpu7  :  5.0 us,  0.7 sy,  0.0 ni, 94.4 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
%Cpu8  :  5.0 us,  0.7 sy,  0.0 ni, 94.3 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
%Cpu9  :  5.0 us,  1.3 sy,  0.0 ni, 93.7 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
%Cpu10 :  5.0 us,  1.3 sy,  0.0 ni, 93.7 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
%Cpu11 :  4.4 us,  1.0 sy,  0.0 ni, 94.6 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st

In 12 cores, why just 6 cores are running at high load and 6cores is low high load? How can i boost speed with 12 core at high speed just like blas etc. parallel? Note i run this program in the environment where no other programs affect as i reboot my server.
Thanks!

**Comment by songs18** [comment]
The result of tf.config.threading.get_intra_op_parallelism_threads() is 0, i know this means that tf will pick  an appropriate number, Is there any mechanism to pick the number in TF? If not, is there any guidence for select the number according to the graph and the server condition? I can only trial and error?

**Comment by ravikyram** [comment]
Here is the clear explanation on how the parameters controls the multithreading in Tensorflow. 
https://stackoverflow.com/questions/41233635/meaning-of-inter-op-parallelism-threads-and-intra-op-parallelism-threads . 
Please, see if it helps you. Thanks!
