### ISSUE TITLE
Please fix the example section of tf.constant_initialize

### ISSUE THREAD

**Issue by vinayapathak** [tensorflow/tensorflow#34712]
Thank you for submitting a TensorFlow documentation issue. Per our GitHub
policy, we only address code/doc bugs, performance issues, feature requests, and
build/installation issues on GitHub.

The TensorFlow docs are open source! To get involved, read the documentation
contributor guide: https://www.tensorflow.org/community/contribute/docs

## URL(s) with the issue:
https://www.tensorflow.org/api_docs/python/tf/constant_initializer#used_in_the_tutorials

Please provide a link to the documentation entry, for example:
https://www.tensorflow.org/api_docs/python/tf/constant_initializer#used_in_the_tutorials

## Description of issue (what needs changing):
Please fix the example section of tf.constant_initialize
### Clear description
Examples section of the page is not properly compiled making it unreadable
For example, why should someone use this method? How is it useful?

### Correct links

Is the link to the source code correct?

### Parameters defined

Are all parameters defined and formatted correctly?

### Returns defined

Are return values defined?

### Raises listed and defined

Are the errors defined? For example,
https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/feature_column/categorical_column_with_vocabulary_file#raises

### Usage example

Is there a usage example?

See the API guide: https://www.tensorflow.org/community/contribute/docs_ref
on how to write testable usage examples.

### Request visuals, if applicable

Are there currently visuals? If not, will it clarify the content?

### Submit a pull request?

Are you planning to also submit a pull request to fix the issue? See the docs
contributor guide: https://www.tensorflow.org/community/contribute/docs,
docs API guide: https://www.tensorflow.org/community/contribute/docs_ref and the
docs style guide: https://www.tensorflow.org/community/contribute/docs_style

**Comment by rohanreddych** [comment]
I made a pull request can you once check if it is correct or not. In the docs_ref it is given to remove the ``` and put >>> and to keep ... for indentation.
@dynamicwebpaige  can you once check this.

**Comment by rohanreddych** [comment]
@jvishnuvardhan Code is  fine in the master branch but, the url at the top of the page which on documentation page which shows the code location on github is pointing to the r2.0 branch which has some error in it.

**Comment by rohanreddych** [comment]
what does awaiting tensorflower mean

**Comment by jvishnuvardhan** [comment]
@vinayapathak I think this was resolved. I can see couple of examples, arguments, error raises, `Used in the notebooks` etc.

The document page url also referring to correct location.

I am closing this issue as this was already resolved. Please feel free to reopen I am mistaken. thanks!
