### ISSUE TITLE
Can't use assert statement inside tf.function

### ISSUE THREAD

**Issue by danmou** [tensorflow/tensorflow#34715]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Manjaro Linux
- TensorFlow version (use command below): 2.0.0
- Python version: 3.7

**Describe the current behavior**
`assert` with a tensor inside a `tf.function` results in the following error:
```
OperatorNotAllowedInGraphError: using a `tf.Tensor` as a Python `bool` is not allowed: AutoGraph did not convert this function. Try decorating it directly with @tf.function.
```

**Describe the expected behavior**
The assert statement should be converted to `tf.Assert` by AutoGraph.

**Code to reproduce the issue**
```python
import tensorflow as tf

@tf.function
def f(x):
    assert tf.constant(True), 'assert failed'
    return x

x = tf.ones(())
print(f(x))
```

**Comment by bozcani** [comment]
@Danmou  tf.Assert includes optional parameters "summarize" and "name" which might be useful for debugging. With the expected behavior that you mentioned above, this information cannot be fed using Python's standard assert statement. What would happen in that case?

**Comment by Danmou** [comment]
In my opinion those can just be left at their default values. The name can be decided by AutoGraph just like for all the other ops it creates. If someone wants full control they can still use tf.Assert.

The current behavior is unintuitive - you can use a tensor as the condition in an if statement but not in an assert.

**Comment by ravikyram** [comment]
I have tried on colab with TF version 2.0 ,2.1.0-dev20191201 and was able to reproduce the issue. Please, find the gist [here](https://colab.sandbox.google.com/gist/ravikyram/e8c0136d50bb52032150dfbf0a84119a/untitled428.ipynb). Thanks!

**Comment by mdanatg** [comment]
This feature is actually available, just not enabled by default. Here's how to enable it:

```
@tf.function(experimental_autograph_options=tf.autograph.experimental.Feature.ASSERT_STATEMENTS)
def f(x):
    assert tf.constant(False), 'assert failed'
    return x
```

I'll leave this issue open to enable asserts by default, it's something we've been wanting to do for a while.

**Comment by sushreebarsa** [comment]
Was able to replicate the issue in TF v2.5,please find the gist [here](https://colab.research.google.com/gist/sushreebarsa/ff28bb6d4c663080452d357157ebc4fd/untitled95.ipynb)..Thanks !

**Comment by danmou** [comment]
Hi @tilakrayal, I opened this issue 4 years ago. It is no longer relevant for me.

**Comment by tilakrayal** [comment]
@danmou,
Apologies for the delay. If you still no longer look at this issue, Could you please move this issue to the closed status. Thank you!
