### ISSUE TITLE
Can't accept a 2d array

### ISSUE THREAD

**Issue by mariusjohan** [tensorflow/tensorflow#34724]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10 (latest version)
- TensorFlow installed from (source or binary): PIP
- TensorFlow version (use command below): 1.14
- Python version: 3.7.4

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**When feeding the fully connected layer my last 2d rnn matrix even though the documentation says that it should be able to accept a 2d matrix**

**It should take a 2d matrix**

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.
```python
import tensorflow as tf

inputs = tf.placeholder(tf.int32, shape=(None, 750), name="inputs")
questions = tf.placeholder(tf.int32, shape=(None, 750), name="inputs")

gru_cell = tf.nn,rnn_cell.GRUCell(64) # Units= 64
output, (state_c, state_h) = gru_cell(inputs, questions)
# Both output & both states dimension is 2
logits = tf.contrib.layers.fully_connected(output, num_outputs=100, activation_fn=None) # vocab_size = 100
# We don't have to run the session since Tensorflow will check the tensors for the right shape
```

**Comment by gadagashwini** [comment]
@mariusjohan, Please provide the complete standalone code to replicate the reported issue here. Thanks!

**Comment by mariusjohan** [comment]
@gadagashwini Is that enough?

**Comment by gadagashwini** [comment]
@mariusjohan, Please find the gist [here](https://colab.sandbox.google.com/gist/gadagashwini/d4440b9d05dca338f3e86df94a92bd3b/untitled290.ipynb) and let us know the expected output. Thanks!

**Comment by mariusjohan** [comment]
Sorry for taking so long, I've been really busy in school so I could not find any time. But here I am!

For some reason i could not run the gist, but i copy-pasted the code into my terminal and for some reason it worked there even with at 2d tensor.

Sorry for wasting your time :) But it doesnt work in own project for some reason. But i think i can solve it myself.
