### ISSUE TITLE
AttributeError: module 'tensorflow_datasets' has no attribute 'load'

### ISSUE THREAD

**Issue by catqaq** [tensorflow/tensorflow#34727]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- TensorFlow installed from (pip):
- TensorFlow version (2.0):
- Python version: 3.6

**Code to reproduce the issue**
import tensorflow_datasets as tfds
data = tfds.load('glue/mrpc')

**Comment by rao208** [comment]
@catqaq what was the problem? How did you find the solution? I have the same error

**Comment by shubham-malaviya** [comment]
Try upgrading tensorflow-dataset may help. 

pip install --upgrade tensorflow-dataset

**Comment by hesiqi1998** [comment]
I have the same error, tensorflow version is 2.3.0, python 3.7, is it because of the version problem?

**Comment by catqaq** [comment]
You can try to  upgrade tensorflow-dataset or downgrade python. Good luck!

**Comment by hesiqi1998** [comment]
I tried to make a change and I didn't solve the problem.I downgraded the python version to 3.6 and try to upgrade tensorflow-dataset. And even I changed tensorflow version to 2.1.0
AttributeError: module 'tensorflow_datasets' has no attribute 'load'

**Comment by MH0386** [comment]
I have the same error

TensorFlow 2.10
Python 3.11.12

**Comment by shott92** [comment]
> Try upgrading tensorflow-dataset may help.
> 
> pip install --upgrade tensorflow-dataset

**pip install --upgrade tensorflow-datasets

**Comment by steveepreston** [comment]
Problem still exists:
tensorflow= 4.53.0
tensorflow-datasets= 4.9.9

Code:
```python
import tensorflow_datasets as tfds
tfds.load()
```
Error:
`AttributeError: module 'tensorflow_datasets' has no attribute 'load'`
