### ISSUE TITLE
Zero value warning message in quantized convolution op is wrong?

### ISSUE THREAD

**Issue by ngaloppo** [tensorflow/tensorflow#3472]
This warning message [in this quantized ops code snippet](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/quantization/kernels/quantized_conv_ops.cc#L201-L206) is output when `input_offset < 0`:

> Zero is not representable in the quantized range used by the input. This means QuantizedConv2d has to fall back to a slow implementation, since the border of zero values can't be represented easily. You should try to construct graphs that avoid this situation.

Is that really what's going on there? What does that have to do with `input_offset < 0`? Secondly, there is a code comment about gemmlowp needing support for a specific code path (perhaps it's the `input_offset < 0` path?). What's going on here? 

Adding @petewarden as he's probably the most familiar with this code.

**Comment by drpngx** [comment]
The snippet is no longer a valid link. Please ask on stackoverflow if you need more info.
