### ISSUE TITLE
tensorflow-gpu 2.0 cannot be imported

### ISSUE THREAD

**Issue by songheej** [tensorflow/tensorflow#34735]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution: Ubuntu 18.04)
- TensorFlow installed from (source or binary)
- TensorFlow version: tensorflow-gpu 2.0.0
- Python version: 3.6
- Installed using virtualenv? pip? conda?: installed using pip
- Bazel version (if compiling from source): 
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 10.0 / 7.6.4
- GPU model and memory: GeForce GTX, driveri 410.104

i have tensorflow-estimator 2.0 & tensorflow-gpu 2.0 installed, and it shows under 'pip list' and 'conda list'.

but import tensorflow is not working as attached picture;

![capture](https://user-images.githubusercontent.com/46334448/69915721-9888b480-1495-11ea-8593-f93413cc9ccd.JPG)

please help..!! thank you all for your help in advance!

**Comment by gadagashwini** [comment]
@songheej,
Below are the instructions to install Tensorflow 2.0 using PIP
**Note:** Make sure CUDA and cuDNN path are set before installing Tenosrflow-gpu.
#Install tensorflow using pip virtual env 
$pip install virtualenv
$virtualenv tf_2.0.0   # tf_2.0.0 is virtual env name
$source tf_2.0.0/bin/activate
tf_2.0.0 $ pip install tensorflow-gpu==2.0.0
tf_2.0.0 $ python
>>import tensorflow as tf
>>tf.__version__
2.0.0

Let us know how it progresses. Thanks!

**Comment by gadagashwini** [comment]
@songheej, Is this still an issue!

**Comment by gadagashwini** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
