### ISSUE TITLE
Delete init_op option

### ISSUE THREAD

**Issue by MARMOTatZJU** [tensorflow/tensorflow#34738]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using): 1.15.0
- Are you willing to contribute it (Yes/No): Yes

**Describe the feature and the current behavior/state.**
I am using HiAI-DDK in order to deploy my model on mobile phone. The model transform failed with debug information that the _init_op_ is not supported. I think this should be due to the redundant part in the initialization procedure for trained model. So I wonder if there exists the feature that allows me to delete a node in a graph (especially tf_rep). 
I am using onnx-tf to do the transformation. 

**Will this change the current api? How?**
Add node deleting interface, (not sure)

**Who will benefit with this feature?**
Engineers working with model deployment.

**Any Other info.**

**Comment by gadagashwini** [comment]
@MARMOTatZJU, Could you post your sample code snippet for us to analyze the issue better?

**Comment by gadagashwini** [comment]
@MARMOTatZJU, Could you elaborate feature request with code snippet and if any use case. Thanks!

**Comment by gadagashwini** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
