### ISSUE TITLE
Cannot import name 'pywrap_tensorflow'

### ISSUE THREAD

**Issue by mynameisdongyoung** [tensorflow/tensorflow#3474]
Hi, I have tried almost every methods in Stackoverflow and here, but am still struggling with the problem. Please help me to solve it.

### Environment info
Operating System: **Ubuntu 16.04 64bit (GTX 1070)** 

Installed version of CUDA and cuDNN: **CUDA 8.0 RC & cuDNN 5.0**
(please attach the output of `ls -l /path/to/cuda/lib/libcud*`):
dongyoung@dkpc:~$ ls /usr/local/cuda/lib64/libcud*
/usr/local/cuda/lib64/libcudadevrt.a    /usr/local/cuda/lib64/libcudart.so.8.0.27  /usr/local/cuda/lib64/libcudnn.so.5
/usr/local/cuda/lib64/libcudart.so      /usr/local/cuda/lib64/libcudart_static.a   /usr/local/cuda/lib64/libcudnn.so.5.0.5
/usr/local/cuda/lib64/libcudart.so.8.0  /usr/local/cuda/lib64/libcudnn.so          /usr/local/cuda/lib64/libcudnn_static.a

If installed from binary pip package, provide

1. Which pip package you installed.
2. The output from `python -c "import tensorflow; print(tensorflow.__version__)"`.

If installed from source, provide 

1. The commit hash (`git rev-parse HEAD`) 
Sorry, but I don't know how to do this. I just downloaded the tensorflow-master.zip file from Github

2. The output of `bazel version`
**[bazel release 0.3.0]**

### Steps to reproduce
1. In my home directory, type 'ipython3', then change directory to tensorflow that I installed which is ~/tensorflow
2. then type 'import tensorflow as tf'
3. It shows ImportError: cannot import name 'pywrap_tensorflow'

### Logs or other output that would be helpful
![screenshot from 2016-07-23 12-18-14](https://cloud.githubusercontent.com/assets/673965/17075477/8e5fbdf6-50cf-11e6-8e7e-0ede795a251b.png)

(If logs are large, please upload as attachment).

One more question is that how can I make a path 'tensorflow' to use globally?

Thank you :)

**Comment by hholst80** [comment]
Is the ~/tensorflow also the src directory? That ususlly works bad for me.

**Comment by mynameisdongyoung** [comment]
Thank you so much hholst80! It helped :+1:
