### ISSUE TITLE
Autograph failure with tf.ragged.boolean_mask

### ISSUE THREAD

**Issue by leandro-gracia-gil** [tensorflow/tensorflow#34740]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes, providing source
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Mac OS 10.15.1, most likely irrelevant.
- TensorFlow installed from (source or binary): binary from pip
- TensorFlow version (use command below): v2.0.0-rc2-26-g64c3d382ca 2.0.0
- Python version: 3.7.2
- CUDA/cuDNN version: using CPU only.

**Describe the current behavior**
I have a function computing a loss for a Keras model that produces multiple outputs of different sizes, and chooses one of them based on an index received as input from a tf.data.Dataset. Since the desired outputs have different sizes, they are stored in the dataset as ragged tensors and tf.ragged.boolean_mask is used to perform appropriate selections based on the index.

**Describe the expected behavior**
The function works fine in eager mode, but raises the following exception when trying to apply @tf.function on it:

> 2019-12-01 22:06:26.103694: W tensorflow/core/common_runtime/base_collective_executor.cc:216] BaseCollectiveExecutor::StartAbort Invalid argument: Input to reshape is a tensor with 388 values, but the requested shape has 408
> Traceback (most recent call last):
>   File "ragged_bug.py", line 50, in <module>
>     loss, grads = get_loss(model, inputs, outputs, index)
>   File ".../lib/python3.7/site-packages/tensorflow_core/python/eager/def_function.py", line 457, in __call__
>     result = self._call(*args, **kwds)
>   File ".../lib/python3.7/site-packages/tensorflow_core/python/eager/def_function.py", line 494, in _call
>     results = self._stateful_fn(*args, **kwds)
>   File ".../lib/python3.7/site-packages/tensorflow_core/python/eager/function.py", line 1823, in __call__
>     return graph_function._filtered_call(args, kwargs)  # pylint: disable=protected-access
>   File ".../lib/python3.7/site-packages/tensorflow_core/python/eager/function.py", line 1141, in _filtered_call
>     self.captured_inputs)
>   File ".../lib/python3.7/site-packages/tensorflow_core/python/eager/function.py", line 1224, in _call_flat
>     ctx, args, cancellation_manager=cancellation_manager)
>   File ".../lib/python3.7/site-packages/tensorflow_core/python/eager/function.py", line 511, in call
>     ctx=ctx)
>   File ".../lib/python3.7/site-packages/tensorflow_core/python/eager/execute.py", line 67, in quick_execute
>     six.raise_from(core._status_to_exception(e.code, message), None)
>   File "<string>", line 3, in raise_from
> tensorflow.python.framework.errors_impl.InvalidArgumentError:  Input to reshape is a tensor with 388 values, but the requested shape has 408
> 	 [[node RaggedMask_1/RaggedMask/boolean_mask/Reshape (defined at .../lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py:1751) ]] [Op:__inference_get_loss_1681]

I can confirm that making all model output sizes the same removes the problem, suggesting an issue with the use of ragged tensors in this situation. Also, the actual exception values change on every run since they depend on the random data being generated.

**Code to reproduce the issue**
[ragged_bug.py.txt](https://github.com/tensorflow/tensorflow/files/3908709/ragged_bug.py.txt)

**Comment by ravikyram** [comment]
@leandro-gracia-gil 

Can you please try with recent nightly version(`!pip install tf-nightly==2.1.0dev20191201`). I am not seeing any issue with recent nightly version. Please, find the gist [here.](https://colab.sandbox.google.com/gist/ravikyram/6d90edaa50eeaefff46c676b020ca2a0/untitled434.ipynb)Thanks!

**Comment by leandro-gracia-gil** [comment]
@ravikyram 

The recent nightly version does seem to fix the problem. Thanks!
