### ISSUE TITLE
how to convert tensorflow1.13 trained model ckpt to tflite use tensorflow2.0?

### ISSUE THREAD

**Issue by mlinxiang** [tensorflow/tensorflow#34749]
i have a model trained use tensorflow1.13 and i can export model to pb from checkpoints and then convert to tflite file by tf.lite.TFLiteConverter.from_frozen_graph. but in tensorflow 2.0 there is no this method. my code trained use slim, so is very hard to change to tf2.0 retrain the model, are there any method to read from the original ckpt files to convert tf2.0 tflite file?

**Comment by ymodak** [comment]
You may use (tf.compat.v1.lite.TFLiteConverter)[https://www.tensorflow.org/api_docs/python/tf/compat/v1/lite/TFLiteConverter#from_frozen_graph] in this case.

**Comment by mlinxiang** [comment]
my approach is first to load ckpt and then use saved_model builder to save a format of saved_model, then update tensorflow to 2.1, then use tfliteconverter v2 method from_saved_model to generate tflite
