### ISSUE TITLE
estimator API may not save the latest variable value

### ISSUE THREAD

**Issue by SeekerYb** [tensorflow/tensorflow#34750]
**System information**
- TensorFlow version :tf1.10.0

**Describe the current behavior**

hello,I build a model with estimator API, According to this tutorial: https://www.tensorflow.org/tutorials/distribute/multi_worker_with_estimator ,I use parameter server distribute strategy to train my model. I devide the training data into several parts on average, the chief get one part, each worker get one part also. I didn't set the max train step,so the training will end when the data used up. in practical, I found that some worker is slower than chief(because of mechine performace),so the chief finish early than some workers. when the chief finish, it will dump the last checkpoint, and the training result(by other unfinished worker) after this time node will be lost.I think it may not expected.
**Describe the expected behavior**
I expect the model satisfy “all the training data used exactly once”，no mater which mechine run faster. Is there any way to make the chief wait until all worker finished，then dump the last checkpoint？

**Comment by oanush** [comment]
@SeekerYb ,
Can you please provide the standalone code used ?Thanks!

**Comment by oanush** [comment]
@SeekerYb ,
Any update on the issue ?Thanks!

**Comment by oanush** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
