### ISSUE TITLE
Multiple inputs for iOS benchmark app

### ISSUE THREAD

**Issue by Ori226** [tensorflow/tensorflow#34757]
Hi.
I'm trying to find a way in the "benchmark_params.json":
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/tools/benchmark/ios/README.md

To define multiple inputs to the network. Is it even possible?

**Comment by Ori226** [comment]
I found a solution. It is possible. I found the explanation in the source code error message:
    LOG(ERROR) << "There must be the same number of items in --input_layer,"
               << " --input_layer_shape, and --input_layer_type, for example"
               << " --input_layer=input1,input2 --input_layer_type=float,float "
               << " --input_layer_shape=1,224,224,4:1,20";

in the file:
https://github.com/tensorflow/tensorflow/blob/d1002d97efdbb173e3798cba7e11dd0eb89bdbe7/tensorflow/tools/benchmark/benchmark_model.cc


I believe this explanation should be added to the documentation

**Comment by yyoon** [comment]
@Ori226 Thanks for flagging this! Will keep this issue open until the doc is updated.

**Comment by Saduf2019** [comment]
@Ori226 
Is this still an issue.

**Comment by yyoon** [comment]
The multiple input explanation has been added to the [README file](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/tools/benchmark/README.md) since. Closing.
