### ISSUE TITLE
Error with tensorflow lite interpreter

### ISSUE THREAD

**Issue by dsp-ml** [tensorflow/tensorflow#34766]
Hi, I am trying to create a wrapper library that takes tensorflow lite model, returns interpreter, which is used later to invoke on specific inputs

I am using the mimimal.cc example code and modified it to my needs as follows:
```
#include <cstdio>
#include "tensorflow/lite/interpreter.h"
#include "tensorflow/lite/kernels/register.h"
#include "tensorflow/lite/model.h"
#include "tensorflow/lite/optional_debug_tools.h"


using namespace tflite;


#define TFLITE_MINIMAL_CHECK(x)                              \
  if (!(x)) {                                                \
    fprintf(stderr, "Error at %s:%d\n", __FILE__, __LINE__); \
    exit(1);                                                 \
  }

#include "CHModel.h"

void* LoadModel(struct CHModel *chmodel)
{

  std::unique_ptr<tflite::FlatBufferModel> model =
      tflite::FlatBufferModel::BuildFromFile(chmodel->model_file);
  TFLITE_MINIMAL_CHECK(model != nullptr);

  // Build the interpreter
  tflite::ops::builtin::BuiltinOpResolver resolver;
  InterpreterBuilder builder(*model, resolver);
  std::unique_ptr<Interpreter>* interpreter = new std::unique_ptr<Interpreter>;
  builder(interpreter);
  TFLITE_MINIMAL_CHECK((*interpreter) != nullptr);

  // Allocate tensor buffers.
  TFLITE_MINIMAL_CHECK((*interpreter)->AllocateTensors() == kTfLiteOk);
  printf("=== Pre-invoke Interpreter State ===\n");
  //tflite::PrintInterpreterState(interpreter.get());

  return interpreter;
}


void RunModel(struct CHModel *model, void* network, double** input, double** output)
{
 if(network == NULL) printf(" the network pointer is NULL \n");

  std::unique_ptr<Interpreter>* interpreter = new std::unique_ptr<Interpreter>;
  interpreter = (std::unique_ptr<Interpreter>*) (network);
  TFLITE_MINIMAL_CHECK(interpreter != nullptr);
  printf("entered run function\n");
  printf("tensors size: %d \n",(*interpreter)->tensors_size());
  printf("nodes size: %d \n", (*interpreter)->nodes_size());
  printf("inputs: %d \n", (*interpreter)->inputs().size());
  printf("input(0) name: %s \n", (*interpreter)->GetInputName(0));
  // Fill input buffers
  // TODO(user): Insert code to fill input tensors
  
  
  // Run inference
  TFLITE_MINIMAL_CHECK(interpreter != nullptr);
  //(*interpreter)->Invoke();
  //printf("\n\n=== Post-invoke Interpreter State ===\n");
  //tflite::PrintInterpreterState((*interpreter).get());

  // Read output buffers
  // TODO(user): Insert getting data out code.


}
```

I build this using 
gcc -shared -Wall -o libmodel.so -fPIC CHModel.cpp -I/home/developer/Development/tensorflow/tensorflow/lite/tools/make/downloads/flatbuffers/include -I/home/developer/Development/tensorflow/ -pthread -Wall -Wextra -pedantic -L. -l:libtensorflow-lite.a

I wrote a simple application to use this library
```
network = LoadModel(&model);

for ( i=0; i<3; i++){
        printf("Running model for the %ith time \n", i);
	RunModel(&model, network, input, output);
    }
```

this is the output I am getting
```
finished allocating memory
=== Pre-invoke Interpreter State ===
Running model for the 0th time 
entered run function
tensors size: 208 
nodes size: 111 
inputs: 3 
Segmentation fault (core dumped)
```

I don't understand why (*interpreter)->tensors_size() works but (*interpreter)->GetInputName(0) is giving problems

Is there anything I am doing wrong? In my application, I am going to run the models multiple times with multiple inputs, so I want to remove the overhead of loading it every time, so I am getting interpreter from LoadModel() and giving it to RunModel().

**System information**
- Linux Ubuntu 18.04
- TensorFlow version r2.1

**Comment by daverim** [comment]
Hi,

This is probably better to ask on [StackOverflow](https://stackoverflow.com)

But it looks like your `unique_ptr<Interpreter>` created in `LoadModel` has no references after exiting the function so is deleted (possibly right after printing inputs).

**Comment by NPetsky** [comment]
@dsp-ml I had the same error (always segfaults when trying to do smthg with the interpreter), then I considered that the tflite::FlatbufferModel has to have the same lifetime as the interpreter and now it works (see https://www.tensorflow.org/lite/api_docs/cc/class/tflite/interpreter-builder)
