### ISSUE TITLE
TFLite object detection output values

### ISSUE THREAD

**Issue by arushgupta2007** [tensorflow/tensorflow#34761]
This template is for miscellaneous issues not covered by the other issue categories.

For questions on how to work with TensorFlow, or support for problems that are not verified bugs in TensorFlow, please go to [StackOverflow](https://stackoverflow.com/questions/tagged/tensorflow).

If you are reporting a vulnerability, please use the [dedicated reporting process](https://github.com/tensorflow/tensorflow/blob/master/SECURITY.md).

For high-level discussions about TensorFlow, please post to discuss@tensorflow.org, for questions about the development or internal workings of TensorFlow, or if you would like to know how to contribute to TensorFlow, please post to developers@tensorflow.org.

Hi, 

I am using TFLite in my project, which includes object detection in python. I am working on a raspberry pi so TFLite was suitable for this. I could successsfully invoke the interpreter and get some numbers as the output:

```
[[[ 1.66415479e-02  5.48024022e-04  8.67791831e-01  3.35325867e-01]
  [ 7.41335377e-02  3.22245747e-01  9.64617252e-01  9.71388936e-01]
  [-2.11861148e-03  5.41743517e-01  2.60241032e-01  7.02846169e-01]
  [-5.67546487e-03  3.26282382e-01  8.59034657e-01  6.30770981e-01]
  [ 7.27111334e-03  7.90268779e-01  2.86753297e-01  9.56545353e-01]
  [ 2.07318692e-03  7.96441555e-01  5.48386931e-01  9.96111989e-01]
  [-1.04907183e-02  2.38761827e-01  6.75976276e-01  7.01156497e-01]
  [ 3.12007014e-02  1.34294275e-02  5.82291842e-01  3.10949832e-01]
  [-1.95578858e-03  7.05318868e-01  9.18281525e-02  7.96184599e-01]
  [-5.43205580e-03  3.23292404e-01  6.34427786e-01  5.68508685e-01]]]
```

How do I convert these numbers to classes and then to thier location in the image?

Here is my code if I did something wrong:

```python
import tensorflow as tf 
import numpy as np
import cv2

interpreter = tf.lite.Interpreter(model_path="/content/drive/My Drive/detect.tflite")
interpreter.allocate_tensors()

input_details = interpreter.get_input_details()
output_details = interpreter.get_output_details()
print(input_details)
print(output_details)

input_shape = input_details[0]['shape']
im = cv2.imread("/content/drive/My Drive/doggy.jpg")
im_rgb = cv2.cvtColor(im, cv2.COLOR_BGR2RGB)
im_rgb = cv2.resize(im_rgb, (input_shape[1], input_shape[2]))
input_data = np.expand_dims(im_rgb, axis=0)
print(input_data.shape)

interpreter.set_tensor(input_details[0]['index'], input_data)

interpreter.invoke()

output_data = interpreter.get_tensor(output_details[0]['index'])
print(output_data.shape)
print()
print(output_data)
```
Output:
```
[{'name': 'normalized_input_image_tensor', 'index': 175, 'shape': array([  1, 300, 300,   3], dtype=int32), 'dtype': <class 'numpy.uint8'>, 'quantization': (0.0078125, 128)}]
[{'name': 'TFLite_Detection_PostProcess', 'index': 167, 'shape': array([ 1, 10,  4], dtype=int32), 'dtype': <class 'numpy.float32'>, 'quantization': (0.0, 0)}, {'name': 'TFLite_Detection_PostProcess:1', 'index': 168, 'shape': array([ 1, 10], dtype=int32), 'dtype': <class 'numpy.float32'>, 'quantization': (0.0, 0)}, {'name': 'TFLite_Detection_PostProcess:2', 'index': 169, 'shape': array([ 1, 10], dtype=int32), 'dtype': <class 'numpy.float32'>, 'quantization': (0.0, 0)}, {'name': 'TFLite_Detection_PostProcess:3', 'index': 170, 'shape': array([1], dtype=int32), 'dtype': <class 'numpy.float32'>, 'quantization': (0.0, 0)}]

(1, 300, 300, 3)

(1, 10, 4)

[[[ 1.66415479e-02  5.48024022e-04  8.67791831e-01  3.35325867e-01]
  [ 7.41335377e-02  3.22245747e-01  9.64617252e-01  9.71388936e-01]
  [-2.11861148e-03  5.41743517e-01  2.60241032e-01  7.02846169e-01]
  [-5.67546487e-03  3.26282382e-01  8.59034657e-01  6.30770981e-01]
  [ 7.27111334e-03  7.90268779e-01  2.86753297e-01  9.56545353e-01]
  [ 2.07318692e-03  7.96441555e-01  5.48386931e-01  9.96111989e-01]
  [-1.04907183e-02  2.38761827e-01  6.75976276e-01  7.01156497e-01]
  [ 3.12007014e-02  1.34294275e-02  5.82291842e-01  3.10949832e-01]
  [-1.95578858e-03  7.05318868e-01  9.18281525e-02  7.96184599e-01]
  [-5.43205580e-03  3.23292404e-01  6.34427786e-01  5.68508685e-01]]]
```

Thanks

**Comment by daverim** [comment]
Hi,

You should post this question on [StackOverFlow](https://stackoverflow.com/questions/tagged/tensorflow).

Just as an FYI:

The TFLite_Detection_PostProcess custom op node has four outputs
detection_boxes: a tensor of shape [1, num_boxes, 4] with normalized coordinates
detection_classes: a tensor of shape [1, num_boxes] containing class prediction for each box
detection_scores: a tensor of shape [1, num_boxes]
num_boxes: a tensor of size 1 containing the number of detected boxes

```
detection_boxes = interpreter.get_tensor(output_details[0]['index'])
detection_classes = interpreter.get_tensor(output_details[1]['index'])
detection_scores = interpreter.get_tensor(output_details[2]['index'])
num_boxes = interpreter.get_tensor(output_details[3]['index'])
for i in range(num_boxes):
  if detection_scores[0, i] > .5:
       x = detection_boxes[0, i, [1, 3]] * img_width
       y = detection_boxes[0, i, [0, 2]] * img_height
       rectangle = [x[0], y[0], x[1], y[1]]
       class_id = detection_classes[0, i]
       ...
```

**Comment by arushgupta2007** [comment]
Thanks for the reply with the answer I needed. Sorry I mad an issue here :) 
For those who are getting an error in the for loop, change the for loop to :
```python
for i in range(int(num_boxes[0])):
```
Thanks Again

**Comment by hutgun11** [comment]
why my output_detail have just 1-dimention 
output [{'name': 'output_boxes', 'index': 104, 'shape': array([   1, 5415,   16]), 'dtype': <class 'numpy.float32'>, 'quantization': (0.0, 0)}]

**Comment by ricardoantonello** [comment]
> why my output_detail have just 1-dimention
> output [{'name': 'output_boxes', 'index': 104, 'shape': array([ 1, 5415, 16]), 'dtype': <class 'numpy.float32'>, 'quantization': (0.0, 0)}]

I got the same error...
