### ISSUE TITLE
How to initialize LSTMStateTuple ?

### ISSUE THREAD

**Issue by zsdonghao** [tensorflow/tensorflow#3476]
In ptb_word_lm.py tutorial. When I set tf.nn.rnn_cell.BasicLSTMCell to  `state_is_tuple=True`, it fail initialise the state at the begining of each epoch. What is the way to initialise a `LSTMStateTuple` ?

I did use cell.zero_state to get the varible for the initial state, which works fine. However, when I want to get initial values of the initial state using `initial_state.eval()`, I got an error saying that AttributeError: `LSTMStateTuple` object has no attribute 'eval'.

Please see a simplified version of my code below (this code works well when `state_is_tuple=False`)

        state = lstm.initial_state.eval()
        for step, (x, y) in enumerate(reader.ptb_iterator(train_data,
                                                        batch_size, num_steps)):
            feed_dict = {
                input_data: x, targets: y,
                lstm.initial_state: state
            }
            _cost, state, _ = sess.run(
                [cost, lstm.final_state, train_op],
                feed_dict=feed_dict
            )
The main reason for feeding this initial_state into feed_dict is to propagate the cell's state to the next iteration.

Many Thank

**Comment by ebrevdo** [comment]
A) use the zero_state function on the cell object

B) for an rnn, all time steps share weights.  We use one matrix to keep all gate weights.  Split by column into 4 parts to get the 4 gate weight matrices.

C) StackOverflow is a better place to ask.

**Comment by zsdonghao** [comment]
@ebrevdo Thank you. But I still can't initialize state from ```LSTMStateTuple```.

When ```state_is_tuple = False```, I can get new state values by ```new_state_val = state.eval()```, and then feed ```new_state_val``` into ```feed_dict```.

However, when ```state_is_tuple=True```, I can't initialize the state values as ```LSTMStateTuple``` does not have ```eval()```. So I instead do the following:
```
new_state = state
new_state[0].assign(state[0].eval())
new_state[1].assign(state[1].eval())
```
I got an error saying --> AttributeError: 'Tensor' object has no attribute 'assign'

Could you please advise how to get the initial state from the LSTM cell when ```state_tuple=True```?

Many thanks : D

**Comment by ebrevdo** [comment]
Usually states are fed to tf.nn.rnn via initial_state parameter.  you can use cell.zero_state method to get an all zeros initial state.  Alternatively, you do not have to pass one and cell.zero_state will be called for you.  You do not need to store an initial state to a Variable in most cases.

**Comment by zsdonghao** [comment]
@ebrevdo Perharps, I didn't describe my problem clearly. I did use ```cell.zero_state``` to get the varible for the initial state, which works fine. However, when I want to get initial values of the initial state using ```initial_state.eval()```, I got an error saying that ```AttributeError: 'LSTMStateTuple' object has no attribute 'eval'```.

Please see a simplified version of my code below (this code works well when ```state_is_tuple=False```)

```
        state = lstm.initial_state.eval()
        for step, (x, y) in enumerate(reader.ptb_iterator(train_data,
                                                        batch_size, num_steps)):
            feed_dict = {
                input_data: x, targets: y,
                lstm.initial_state: state
            }
            _cost, state, _ = sess.run(
                [cost, lstm.final_state, train_op],
                feed_dict=feed_dict
            )
```

The main reason for feeding this initial_state into ```feed_dict``` is to propagate the cell's state to the next iteration.

Many Thank

**Comment by ebrevdo** [comment]
LSTMStateTuple is just a tuple.  You can create it with two placeholders and when you run session, pass values for those placeholders with the feed_dict param.  To evaluate an LSTMStateTuple, simply call session.run(lstm_state_tuple).

**Comment by zsdonghao** [comment]
@ebrevdo can you give a code example ?

**Comment by evanthebouncy** [comment]
It seems I'm late to the party but can someone explain why the state is a tuple and not just a single value? thanks.

**Comment by a3626a** [comment]
LSTMTuple consists of previous cell state, and output.

**Comment by yurijvolkov** [comment]
It seems that this issue was resolved a long time ago. But I stuck on this problem not so long ago and didn't figure out good solution from upward thread. 

So I decided to share solution I found. Possibly it would be useful for somebody.

After creating cell (e.g. with MultiRNNCell) we can receive zero_state of it cell. Hence we can initialise Tensor with such shape and feed value into it. After that we only need to pass it into RNN directly.
Code example:

`
Code example:  

    init_state = cell.zero_state(batch_size[0], tf.float32)

    init_state = tf.identity(init_state, 'init_state') #Actually it works without this line. But it can be useful 

    _lstm_state_ = tf.contrib.rnn.LSTMStateTuple(init_state[0, 0, :, :], init_state[0,1,:,:])

    preds, final_state = tf.nn.dynamic_rnn(cell, x, initial_state=(_lstm_state_,), parallel_iterations=1)
`

Imo, this solution much scalable (e.g. for adding more layers) than creating placeholder for each LSTM layer parameter.

**Comment by issa-s-ayoub** [comment]
Another solution:

initial_state_c = tf.placeholder(dtype=m_dtype, shape=[None, cell_size], name="initial_state_c")
initial_state_h = tf.placeholder(dtype=m_dtype, shape=[None, cell_size], name="initial_state_h")

initial_state = tf.nn.rnn_cell.LSTMStateTuple(initial_state_c, initial_state_h)

cell = tf.nn.rnn_cell.LSTMCell(cell_size, use_peepholes=use_peepholes, initializer=kernel_initializer)
LSTM_cell = cell
output, new_state = tf.nn.dynamic_rnn(cell, inputs, dtype=m_dtype, sequence_length=length,
                                              initial_state=initial_state)

new_state_temp = LSTM_cell.zero_state(batch_size=34, dtype=m_dtype)
new_state_ = sess.run(new_state_temp)

feed_dict = {inputs_ph: train_x[:, i*time_steps: (i + 1) * time_steps, :],
                             labels_ph: train_y[:, i*time_steps: (i + 1) * time_steps, :],
                             phase_train: True, initial_state_c: new_state_.c, initial_state_h: new_state_.h}
_, summary_t, new_state_ = sess.run([train_step, summary_train, new_state], feed_dict=feed_dict)
