### ISSUE TITLE
ValueError: Dimensions must be equal, but are 32 and 64 for 'conv2/Conv2D' (op: 'Conv2D') with input shapes: [?,?,?,32], [3,3,64,128].

### ISSUE THREAD

**Issue by sarthakforwet** [tensorflow/tensorflow#34760]
Hello There,
I am Working on a project of converting given image to its latex form . 
I have cloned this github repo->
**https://github.com/yixuanzhou/image2latex.git**

I am using Python-2 and tensorflow_version = 0.12.1 with a GPU backend on **Google-Colab**.
I have resotred  the Weights  correctly and tried to run the file **predict.py** Without calling the function **predict** inside that file I am getting no error . But when I am calling that function with an input image ,it showed me an error that Data Format must be NHWC and the file **ops.py** under the tflib folder in that repo used data format of NCHW . So i simply changed the data format from NCHW to NHWC.
After that when I run the program **predict.py** I am getting this error :

Traceback (most recent call last):
  File "predict.py", line 32, in <module>
    ctx = tflib.network.im2latex_cnn(X,NUM_FEATS_START,False)
  File "/content/image2latex/tflib/network.py", line 79, in im2latex_cnn
    X = tf.nn.relu(tflib.ops.conv2d('conv2', X, 3, 1, num_feats, num_feats*2, pad = 'SAME', bias=False))
  File "/content/image2latex/tflib/ops.py", line 202, in conv2d
    out = tf.nn.conv2d(input, filters, strides=[1, 1, stride, stride], padding=pad, data_format='NHWC')
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_nn_ops.py", line 396, in conv2d
    data_format=data_format, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.py", line 759, in apply_op
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 2242, in create_op
    set_shapes_for_outputs(ret)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1617, in set_shapes_for_outputs
    shapes = shape_func(op)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1568, in call_with_requiring
    return call_cpp_shape_fn(op, require_shape_fn=True)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/common_shapes.py", line 610, in call_cpp_shape_fn
    debug_python_shape_fn, require_shape_fn)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/common_shapes.py", line 675, in _call_cpp_shape_fn_impl
    raise ValueError(err.message)
ValueError: Dimensions must be equal, but are 32 and 64 for 'conv2/Conv2D' (op: 'Conv2D') with input shapes: [?,?,?,32], [3,3,64,128].

I have also tried a solution proposed on StackOverflow :
-> **https://stackoverflow.com/questions/37689423/convert-between-nhwc-and-nchw-in-tensorflow**

Kindly help me regarding this issue .
-->Thanks<--

**Comment by gadagashwini** [comment]
@sarthakforwet, Could you post your Google-colab gist to analyze the reported issue. Thanks!

**Comment by sarthakforwet** [comment]
https://colab.research.google.com/gist/sarthakforwet/cd7ff133d0e68cf21571de3790010543/untitled0.ipynb

Here is my Colab gist. Kindly have a look at it .
Thanks

**Comment by gadagashwini** [comment]
@sarthakforwet, Is there specific reason to use two frameworks such as Theano and Tenosrflow.  Tensorflow version is very old, Can you try with latest Tensorflow version 1.15. Let us know if it solves your problem. Thanks!

**Comment by sarthakforwet** [comment]
Theano and Tensorflow both are used  in this particular repo and some functions I found in theano for whom any equivalent was unable to be found out in tensorflow.

Secondly , even if I use **Tensorflow-1.15** , same issue persists and if I change the code from original one to mentioned below i am getting new error i.e 

**ValueError: Input size (depth of inputs) must be accessible via shape inference, but saw value None.**

_Before  :-_ 

tflib/ops.py in conv2d
**out = tf.nn.conv2d(input, filters, strides=[1, 1, stride, stride], padding=pad, data_format='NHWC')**

tflib/ops.py in max_pool

**return  tf.nn.max_pool(l_input, ksize=[1, 1, k1, k2], strides=[1, 1, s1, s2],
                          padding='SAME', name=name, data_format='NCHW')**

_After :-_ 

tflib/ops.py in conv2d
**out = tf.nn.conv2d(input, filters, strides=[1, stride, stride, 1], padding=pad, data_format='NHWC')**

tflib/ops.py in max_pool

**return  tf.nn.max_pool(l_input, ksize=[1, k1, k2, 1], strides=[1, s1, s2, 1],
                          padding='SAME', name=name, data_format='NCHW')**

**Comment by gadagashwini** [comment]
@sarthakforwet, Could you provide the code snippet with only Tensorflow, indeed it will hep us to analyze the issue faster.Thanks!

**Comment by gadagashwini** [comment]
@sarthakforwet, Any update on issue!

**Comment by gadagashwini** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
