### ISSUE TITLE
Build issue "None of the libraries match their SONAME" (libcudnn)

### ISSUE THREAD

**Issue by edrozenberg** [tensorflow/tensorflow#34777]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
Slackware Linux 64 -current (14.2+) 2019-12-02
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
Source
- TensorFlow version:
HEAD 882a1c8ed7
- Python version:
Python 3.7.5
- Installed using virtualenv? pip? conda?:
Directly from OS
- Bazel version (if compiling from source):
Binary download bazel 1.1.0
- GCC/Compiler version (if compiling from source):
gcc (GCC) 8.3.1 20191031
- CUDA/cuDNN version:
cuda_10.2.89_440.33.01_linux.run
cudnn-10.2-linux-x64-v7.6.5.32.tgz
nccl_2.5.6-2+cuda10.2_x86_64.txz
- GPU model and memory:
MSI Graphic Cards GT 1030 2G LP OC

**Describe the problem**
Trying to build TF shows error `Cuda Configuration Error: None of the libraries match their SONAME: /opt/nvidia/cuda/lib64/libcudnn.so.7`

**Provide the exact sequence of commands / steps that you executed before running into the problem**
- Installed nvidia kernel modules and driver 440.31
- Installed cuda, cudnn, nccl, tensorrt to `/opt/nvidia/cuda  /opt/nvidia/nccl  /opt/nvidia/tensorrt`
- Installed bazel binary as `/usr/bin/bazel`
- Downloaded latest TF source from GitHub
- Used TF's `./configure` command to config the build
- Ran build `bazel build //tensorflow/tools/pip_package:build_pip_package`

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.
[.tf_configure.bazelrc](https://github.com/tensorflow/tensorflow/files/3913908/tf_configure.bazelrc.txt)
[tf-build-err.txt](https://github.com/tensorflow/tensorflow/files/3913909/tf-build-err.txt)

**Comment by amahendrakar** [comment]
@edrozenberg,
Is this still an issue?

Could you please update TensorFlow to the latest stable version v2.4.1 and check if you are facing the same error. Thanks!

**Comment by edrozenberg** [comment]
@amahendrakar thanks, closing. No such problems building `2.4.1` recently.
