### ISSUE TITLE
tf.keras uses Eager execution or Graph execution in tf 2.0 ?

### ISSUE THREAD

**Issue by LuchoTangorra** [tensorflow/tensorflow#34771]
Hello, i'm doing a research work and i'd be glad to know if in tf 2.0, tensorflow.keras uses eager execution vs graph execution instead.

**Comment by oanush** [comment]
@LuchoTangorra ,
Hi, by default it is Eager execution in Tensorflow 2.0,irrespective of usage of tf.keras or not. 
Kindly refer this [link](https://www.tensorflow.org/guide/effective_tf2#eager_execution).Thanks!

**Comment by LuchoTangorra** [comment]
Thank you!
Why is this ? I think that if you are using a Keras model, you don't really need to debug, but to speed up your project, and Eager executions do the opposite. Am i wrong? 

I don't understand the the reason of Eager execution using Keras.

Thank you in advance!

**Comment by jvishnuvardhan** [comment]
@LuchoTangorra Eager execution is by default in TF2.0. This is more intuitive and useful to starters as well as experts to see what a variable holds at any time (more like pythonic). Once you checks everything running without a bug, then you can add @tf.function to run time intensive functions in graph mode. Some of the functions like model.fit runs in graph mode. There are several ways to speed up your TF2.0 and you don't lose the performance. 

Please checks the [guides and tutorials](https://www.tensorflow.org/guide) on TF website and also take  a look at the tensorflow [channel on Youtube](https://www.youtube.com/watch?v=5ECD8J3dvDQ).

Having said that, This is not Build/Installation or Bug/Performance issue. Please post this kind of support questions at [Stackoverflow](https://stackoverflow.com/questions/tagged/tensorflow). There is a big community to support and learn from your questions. GitHub is mainly for addressing bugs in installation and performance. Thanks!

**Comment by markemus** [comment]
I believe this thread is incorrect, and tf.keras actually uses graph execution inside of layers. See the issue [here ](https://github.com/tensorflow/tensorflow/issues/36715) where we discuss this.

 Can anyone confirm?
