### ISSUE TITLE
Boosted trees using Estimators codes crash

### ISSUE THREAD

**Issue by fancyerii** [tensorflow/tensorflow#34784]
When I test the codes in https://www.tensorflow.org/tutorials/estimator/boosted_trees, it crashed. and I see the error of "malloc(): memory corruption (fast): 0x00007f4f84066f50 ***". The detailed error messages can be found here(https://gist.github.com/fancyerii/c805604e94b76988771e4ff045aeb303)

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 16.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below): 2.0.0
- Python version: 3.6.8
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 10.1/7.0
- GPU model and memory: Quadro P3000

**Code to reproduce the issue**
https://gist.github.com/fancyerii/538d4033bc94115c561a146b78beeac9

**Other info / logs**
https://gist.github.com/fancyerii/c805604e94b76988771e4ff045aeb303

**Comment by oanush** [comment]
@fancyerii ,
When tried running the given code in TF-2.0, I did not face any error. Kindly find the [gist](https://colab.sandbox.google.com/gist/oanush/6b66743fe92a533bd9f0a35e47976b87/34784.ipynb) of colab for your reference.Thanks!

**Comment by oanush** [comment]
@fancyerii ,
Any update on the issue ?Thanks!

**Comment by oanush** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
