### ISSUE TITLE
obfuscate_names encrypts inputs

### ISSUE THREAD

**Issue by sonfiree** [tensorflow/tensorflow#34781]
I'm try work on with Graph Transform Tool. 
And found with the flag `obfuscate_names`, he inputs the encrypting. Outputs not encrypting.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): windows 10
- TensorFlow installed from (source or binary): source 
- TensorFlow version (use command below): 1.14.0
- Python version: 3.7.2
- CUDA/cuDNN version: 10.1
- GPU model and memory: 1060

**Comment by gowthamkpr** [comment]
@sonfiree Can you please provide a simple reproducible case for us to reproduce the issue. Thanks!

**Comment by gowthamkpr** [comment]
@sonfiree Can you please respond to the above question. Thanks!

**Comment by gowthamkpr** [comment]
Closing this issue as it has been inactive for more than 3 weeks. Please add additional comments and we can open the issue again. Thanks!
