### ISSUE TITLE
Inconsistent cpu/gpu results of gather_nd

### ISSUE THREAD

**Issue by Queequeg92** [tensorflow/tensorflow#34788]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): NO
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.0.0
- Python version: 3.6.8
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 10.2
- GPU model and memory: 11G

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
When I set device to gpu, the code runs correctly. When I set device to cpu, the code raises error: tensorflow.python.framework.errors_impl.InvalidArgumentError: indices[4] = [4, -1] does not index into param shape [5,1] [Op:GatherNd].
**Describe the expected behavior**
Consistent results on cpu and gpu.
**Code to reproduce the issue**
```
import os

import tensorflow as tf
import numpy as np

np.random.seed(2222222)

with tf.device('cpu:0'):
  a = np.random.rand(5, 1)
  print(a)

  b = tf.gather_nd(
      a,
      [[0, -1], [1, -1], [2, -1], [3, -1], [4, -1]])

  print(b.numpy())
```
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by ravikyram** [comment]
I have tried on colab with TF version 2.0, 2.1.0-dev20191203 and was able to reproduce the issue.Please, find the gist [here](https://colab.sandbox.google.com/gist/ravikyram/cccb91f1714c050ea544e6ada5861cb3/untitled441.ipynb). Thanks!

**Comment by Queequeg92** [comment]
@ravikyram Looking forward to your fix. Thx!

**Comment by alextp** [comment]
This is a known issue in TF we cannot change without breaking backward compatibility; gather with invalid indices fails on the CPU but does not on the GPU :-/
