### ISSUE TITLE
tf custom model serialization issue

### ISSUE THREAD

**Issue by ajayaraman** [tensorflow/tensorflow#34799]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): 
Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
Linux Debian
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: NA
- TensorFlow installed from (source or binary): binary using pip install tensorflow
- TensorFlow version (use command below):  v2.0.0-rc2-26-g64c3d38 2.0.0
- Python version: 3.7
- Bazel version (if compiling from source): NA
- GCC/Compiler version (if compiling from source): NA
- CUDA/cuDNN version: NA
- GPU model and memory:  NA

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**

Reconstructing custom model from json produces the following error

  File "/opt/conda/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/network.py", line 1841, in reconstruct_from_config
    for layer_data in config['layers']:
KeyError: 'layers'

**Describe the expected behavior**

model should load without issues as this is a pretty trivial case

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

```python
from tensorflow import keras
import numpy as np 

class TM(keras.Model):
    def __init__(self, **kwargs):
        super().__init__(**kwargs)

    def build(self, input_shape):
        self.lm = self.add_weight(shape=[2,5], initializer="uniform", name="wts")
        super().build(input_shape)

    def call(self, x):
        return x @ self.lm

    def get_config(self):
        return {}        

# serialize arch to json and weights to h5
x = np.random.rand(5,2)
m = TM()
y = m(x) #build
json_config = m.to_json()

# error on loading back
m2 = keras.models.model_from_json(json_config, custom_objects= {"TM": TM})
```

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

  File "training/test_model_class.py", line 25, in <module>
    m2 = keras.models.model_from_json(json_config, custom_objects= {"TM": TM})
  File "/opt/conda/lib/python3.7/site-packages/tensorflow_core/python/keras/saving/model_config.py", line 96, in model_from_json
    return deserialize(config, custom_objects=custom_objects)
  File "/opt/conda/lib/python3.7/site-packages/tensorflow_core/python/keras/layers/serialization.py", line 102, in deserialize
    printable_module_name='layer')
  File "/opt/conda/lib/python3.7/site-packages/tensorflow_core/python/keras/utils/generic_utils.py", line 191, in deserialize_keras_object
    list(custom_objects.items())))
  File "/opt/conda/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/network.py", line 906, in from_config
    config, custom_objects)
  File "/opt/conda/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/network.py", line 1841, in reconstruct_from_config
    for layer_data in config['layers']:
KeyError: 'layers'

**Comment by Athul8raj** [comment]
Note that "build" method is applied to a "keras.layers.Layer" subclass and not to a "keras.Model" subclass.
You have essentially written a custom layer code and not a custom model code.
Please refer : https://www.tensorflow.org/guide/keras/custom_layers_and_models

**Comment by ajayaraman** [comment]
Thanks, as I explored the documentation further, I realized that I can accomplish what I want with custom layers and still use the functional api to compose the custom layers into models. So I'd like to maybe request that the error message be improved when to_json() is invoked on a subclassed model suggesting that it is not supported. At least that way it will be easier to adapt and make use of custom layers instead

> Note that "build" method is applied to a "keras.layers.Layer" subclass and not to a "keras.Model" subclass.
> You have essentially written a custom layer code and not a custom model code.
> Please refer : https://www.tensorflow.org/guide/keras/custom_layers_and_models
