### ISSUE TITLE
bazel build tensorflow lite with with_select_tf_ops Error

### ISSUE THREAD

**Issue by Yooong-W** [tensorflow/tensorflow#34796]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):Linux Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version:r1.14
- Bazel version (if compiling from source):0.24.1

**Describe the problem**

i set a crosstool for bazel to build tensorflow lite, it work well when build `libtensorflowlite.so`.
but when i add the tensorflow ops delegate library dependency (`tensorflow/lite/delegates/flex:delegate`) to the build dependencies, i got an error:

```
ERROR:/home/wang/.cache/bazel/_bazel_wang/4b298145d4306eeb9a64ca7837a4593b/external/nasm/BUILD.bazel:8:1: C++ compilation of rule '@nasm//:nasm' failed (Exit 1): gcc failed: error executing command 
  (cd /home/wang/.cache/bazel/_bazel_wang/4b298145d4306eeb9a64ca7837a4593b/execroot/org_tensorflow && \
  exec env - \
    PATH=/home/wang/.local/bin:/home/wang/bin:/home/wang/android-ndk-r17c:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/wang/.local/bin:/home/wang/bin:/usr/ARM/toolchain/gcc-linaro-7.4.1-2019.02-x86_64_aarch64-linux-gnu/bin \
    PWD=/proc/self/cwd \
  /usr/bin/gcc -U_FORTIFY_SOURCE '-D_FORTIFY_SOURCE=2' -fstack-protector -Wall -Wl,-z,-relro,-z,now -B/usr/bin -B/usr/bin -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -isystem /usr/include -g0 -O3 -DNDEBUG -ffunction-sections -fdata-sections -MD -MF bazel-out/host/bin/external/nasm/_objs/nasm/assemble.d '-frandom-seed=bazel-out/host/bin/external/nasm/_objs/nasm/assemble.o' -DHAVE_SNPRINTF -DHAVE_SYS_TYPES_H -iquote external/nasm -iquote bazel-out/host/genfiles/external/nasm -iquote bazel-out/host/bin/external/nasm -iquote external/bazel_tools -iquote bazel-out/host/genfiles/external/bazel_tools -iquote bazel-out/host/bin/external/bazel_tools -isystem external/nasm/asm -isystem bazel-out/host/genfiles/external/nasm/asm -isystem bazel-out/host/bin/external/nasm/asm -isystem external/nasm/include -isystem bazel-out/host/genfiles/external/nasm/include -isystem bazel-out/host/bin/external/nasm/include -isystem external/nasm/output -isystem bazel-out/host/genfiles/external/nasm/output -isystem bazel-out/host/bin/external/nasm/output -isystem external/nasm/x86 -isystem bazel-out/host/genfiles/external/nasm/x86 -isystem bazel-out/host/bin/external/nasm/x86 -g0 '-march=native' -w '-std=c99' -fno-canonical-system-headers -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -c external/nasm/asm/assemble.c -o bazel-out/host/bin/external/nasm/_objs/nasm/assemble.o)
Execution platform: @bazel_tools//platforms:host_platform
external/nasm/asm/assemble.c: In function 'assert_no_prefix':
external/nasm/asm/assemble.c:265:20: error: 'ERR_NONFATAL' undeclared (first use in this function)
         nasm_error(ERR_NONFATAL, "invalid %s prefix",
                    ^
external/nasm/asm/assemble.c:265:20: note: each undeclared identifier is reported only once for each function it appears in
external/nasm/asm/assemble.c: In function 'warn_overflow':
external/nasm/asm/assemble.c:295:16: error: 'ERR_WARNING' undeclared (first use in this function)
     nasm_error(ERR_WARNING | ERR_PASS2 | ERR_WARN_NOV,
                ^
external/nasm/asm/assemble.c:295:30: error: 'ERR_PASS2' undeclared (first use in this function)
     nasm_error(ERR_WARNING | ERR_PASS2 | ERR_WARN_NOV,
                              ^
external/nasm/asm/assemble.c:295:42: error: 'ERR_WARN_NOV' undeclared (first use in this function)
     nasm_error(ERR_WARNING | ERR_PASS2 | ERR_WARN_NOV,
                                          ^
external/nasm/asm/assemble.c: In function 'out':
external/nasm/asm/assemble.c:402:24: error: 'ERR_NONFATAL' undeclared (first use in this function)
             nasm_error(ERR_NONFATAL,
                        ^
external/nasm/asm/assemble.c:406:24: error: 'ERR_WARNING' undeclared (first use in this function)
             nasm_error(ERR_WARNING | ERR_WARN_ZEXTRELOC,
                        ^
external/nasm/asm/assemble.c:406:38: error: 'ERR_WARN_ZEXTRELOC' undeclared (first use in this function)
             nasm_error(ERR_WARNING | ERR_WARN_ZEXTRELOC,
                                      ^
external/nasm/asm/assemble.c: In function 'out_reladdr':
external/nasm/asm/assemble.c:473:20: error: 'ERR_NONFATAL' undeclared (first use in this function)
         nasm_error(ERR_NONFATAL, "invalid use of self-relative expression");
                    ^
external/nasm/asm/assemble.c: In function 'jmp_match':
external/nasm/asm/assemble.c:527:20: error: 'ERR_WARNING' undeclared (first use in this function)
         nasm_error(ERR_WARNING | ERR_WARN_BND | ERR_PASS2 ,
                    ^
external/nasm/asm/assemble.c:527:34: error: 'ERR_WARN_BND' undeclared (first use in this function)
         nasm_error(ERR_WARNING | ERR_WARN_BND | ERR_PASS2 ,
```
what should i do?
**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by daverim** [comment]
Hi,

Not sure how your build is configured, could you post your crosstool config?

**Comment by Yooong-W** [comment]
the directory structure like this:
```
└──tensorflow
       ├── aarch64_compiler
       │   ├── BUILD
       │   └──CROSSTOOL
       │   └──  cross_toolchain_target_aarch64.BUILD
       └── build_tflite_aarch64.sh
       └── WORKSPACE
```
The BUILD,CROSSTOOL,WORKSPACE , cross_toolchain_target_aarch64.BUILD,  build_tflite_aarch64.sh, files i am using are:
[BUILD.txt](https://github.com/tensorflow/tensorflow/files/3925380/BUILD.txt)
[build_tflite_aarch64.sh.txt](https://github.com/tensorflow/tensorflow/files/3925381/build_tflite_aarch64.sh.txt)
[cross_toolchain_target_aarch64.BUILD.txt](https://github.com/tensorflow/tensorflow/files/3925382/cross_toolchain_target_aarch64.BUILD.txt)
[CROSSTOOL.txt](https://github.com/tensorflow/tensorflow/files/3925383/CROSSTOOL.txt)
[WORKSPACE.txt](https://github.com/tensorflow/tensorflow/files/3925384/WORKSPACE.txt)

i use this crosstool successfully compiled the libtensorflowlite.so, but it doesn't work for framework and the library `with_select_tf_ops`. when compile the framework, i got this error:
```
ERROR: /home/wang/work/arm64/tensorflow-r1.14/tensorflow/lite/BUILD:149:1: Linking of rule '//tensorflow/lite:framework' failed (Exit 1): aarch64-linux-gnu-gcc failed: error executing command 
  (cd /home/wang/.cache/bazel/_bazel_wang/4b298145d4306eeb9a64ca7837a4593b/execroot/org_tensorflow && \
  exec env - \
    PATH=/home/wang/.local/bin:/home/wang/bin:/home/wang/android-ndk-r17c:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/wang/.local/bin:/home/wang/bin:/usr/ARM/toolchain/gcc-linaro-7.4.1-2019.02-x86_64_aarch64-linux-gnu/bin \
    PWD=/proc/self/cwd \
    PYTHON_BIN_PATH=/usr/bin/python \
    PYTHON_LIB_PATH=/usr/local/lib/python2.7/dist-packages \
    TF_CONFIGURE_IOS=0 \
    TF_DOWNLOAD_CLANG=0 \
    TF_NEED_CUDA=0 \
    TF_NEED_OPENCL_SYCL=0 \
    TF_NEED_ROCM=0 \
  /usr/ARM/toolchain/gcc-linaro-7.4.1-2019.02-x86_64_aarch64-linux-gnu/bin/aarch64-linux-gnu-gcc -shared -o bazel-out/aarch64-opt/bin/tensorflow/lite/libframework.so -L/usr/ARM/toolchain/gcc-linaro-7.4.1-2019.02-x86_64_aarch64-linux-gnu/lib -L/usr/ARM/toolchain/gcc-linaro-7.4.1-2019.02-x86_64_aarch64-linux-gnu/aarch64-linux-gnu/lib -L/usr/ARM/toolchain/gcc-linaro-7.4.1-2019.02-x86_64_aarch64-linux-gnu/aarch64-linux-gnu/lib64 -L/usr/ARM/toolchain/gcc-linaro-7.4.1-2019.02-x86_64_aarch64-linux-gnu/aarch64-linux-gnu/libc/lib -L/usr/ARM/toolchain/gcc-linaro-7.4.1-2019.02-x86_64_aarch64-linux-gnu/aarch64-linux-gnu/libc/usr/lib '-Wl,--dynamic-linker=/usr/ARM/toolchain/gcc-linaro-7.4.1-2019.02-x86_64_aarch64-linux-gnu/aarch64-linux-gnu/libc/lib/ld-linux-aarch64.so.1' -no-canonical-prefixes -pie -Wl,-z,relro,-z,now '-Wl,--build-id=md5' '-Wl,--hash-style=gnu' -Wl,--gc-sections -Wl,@bazel-out/aarch64-opt/bin/tensorflow/lite/libframework.so-2.params)
Execution platform: @bazel_tools//platforms:host_platform
/usr/ARM/toolchain/gcc-linaro-7.4.1-2019.02-x86_64_aarch64-linux-gnu/bin/../aarch64-linux-gnu/libc/usr/lib/Scrt1.o: In function `_start':
/home/tcwg-buildslave/workspace/tcwg-make-release_1/snapshots/glibc.git~release~2.25~master/csu/../sysdeps/aarch64/start.S:64: undefined reference to `main'
/home/tcwg-buildslave/workspace/tcwg-make-release_1/snapshots/glibc.git~release~2.25~master/csu/../sysdeps/aarch64/start.S:65: undefined reference to `main'
collect2: error: ld returned 1 exit status

```
im really hope you can help me in your free time,Thanks!

**Comment by daverim** [comment]
I see you are trying to build for linux aarch64, @terryheo, could you take a look?

**Comment by Yooong-W** [comment]
> I see you are trying to build for linux aarch64, @terryheo, could you take a look?

yes, i set this toolchain build for linux aarch64 at linux x86_64

**Comment by terryheo** [comment]
Hi @Yooong-W 
I'm see the following error with your configuration.

ERROR: /usr/local/google/home/terryheo/work/tensorflow/aarch64_compiler/BUILD:25:1: //aarch64_compiler:cc-compiler-local: missing value for mandatory attribute 'toolchain_config' in 'cc_toolchain' rule
ERROR: /usr/local/google/home/terryheo/work/tensorflow/aarch64_compiler/BUILD:38:1: //aarch64_compiler:cc-compiler-aarch64: missing value for mandatory attribute 'toolchain_config' in 'cc_toolchain' rule

I'm using Bazel version 1.2.1. Could you provide a proper toolchain_config ?

**Comment by Yooong-W** [comment]
sorry, im new to bazel. i dont know what's you mean of toolchain_config, i add these four files only,`BUILD`、`cross_toolchain_target_aarch64.BUILD` 、`CROSSTOOL `、`WORKSPACE`.  maybe you can give me some suggestions?

**Comment by Yooong-W** [comment]
maybe i know what's you mean about the `toolchain_config`, i use the [guide ](https://docs.bazel.build/versions/0.23.0/tutorial/crosstool.html) is for bazel 0.23.0 or the before. the bazel version later 0.23.0 should use this [guide](https://docs.bazel.build/versions/1.2.0/tutorial/cc-toolchain-config.html). 
and in my `BUILD` file , it does not contain the attribute `toolchain_config` in `cc_toolchain` rule.

**Comment by Yooong-W** [comment]
> 嗨，@terryheo
> 对不起，我是bazel的新手。我不知道什么是你的意思的`toolchain_config`，我只添加这四个文件`BUILD`，`cross_toolchain_target_aarch64.BUILD`，`CROSSTOOL `， ，`WORKSPACE`。也许您可以给我一些建议？

maybe i know what's you mean about the `toolchain_config`, i use the [guide ](https://docs.bazel.build/versions/0.23.0/tutorial/crosstool.html) is for bazel 0.23.0 or the before. the bazel version later 0.23.0 should use this [guide](https://docs.bazel.build/versions/1.2.0/tutorial/cc-toolchain-config.html). 
and in my `BUILD` file , it does not contain the attribute `toolchain_config` in `cc_toolchain` rule.

**Comment by terryheo** [comment]
For now, the official way of building TFLite library for aarch64 is https://www.tensorflow.org/lite/guide/build_arm64 which doesn't support flex delegate.

**Comment by terryheo** [comment]
Now we have a toolchain for aarch64. You can use it as the following.

```
bazel build -c opt --config=elinux_aarch64 //tensorflow/lite/delegates/flex:delegate
```
