### ISSUE TITLE
variable scope is changed by force when reopened (with regard to use Adam) (with new example)

### ISSUE THREAD

**Issue by yanghoonkim** [tensorflow/tensorflow#34791]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 16.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): 
- TensorFlow version (use command below): 1.12
- Python version: 2.7
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory: 1080ti

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
The same issue with #30813

**Describe the expected behavior**

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.
Please compare the results of following codes

code 1:
```
import tensorflow as tf
class generator:
    def __init__(self):
        with tf.variable_scope('myscope'):
            self.a = tf.get_variable('a', [4,3,2], tf.float32)
            self.b = tf.get_variable('b', [4,3,2], tf.float32)
            self.c = tf.reduce_sum(self.a + self.b)
            self.d = tf.train.AdamOptimizer(name = 'adamopt')
            self.e = self.d.compute_gradients(self.c, tf.trainable_variables())
            self.f = self.d.apply_gradients(self.e)
        for item in tf.global_variables():
            if 'beta' in item.name:
                print item
    
    def compute(self):
        with tf.variable_scope('myscope'):
            self.e1 = self.d.compute_gradients(self.c, tf.trainable_variables())
            self.f1 = self.d.apply_gradients(self.e1)
        print '------------------------'
        for item in tf.global_variables():
            if 'beta' in item.name:
                print item
    
    def compute1(self):
        with tf.variable_scope('myscope'):
            self.e2 = self.d.compute_gradients(self.c, tf.trainable_variables())
            self.f2 = self.d.apply_gradients(self.e2)
        print '---------------------------'
        for item in tf.global_variables():
            if 'beta' in item.name:
                print item

g = generator()
g.compute()
g.compute1()
```

The printed result will be:
```
<tf.Variable 'myscope/beta1_power:0' shape=() dtype=float32_ref>
<tf.Variable 'myscope/beta2_power:0' shape=() dtype=float32_ref>
------------------------
<tf.Variable 'myscope/beta1_power:0' shape=() dtype=float32_ref>
<tf.Variable 'myscope/beta2_power:0' shape=() dtype=float32_ref>
---------------------------
<tf.Variable 'myscope/beta1_power:0' shape=() dtype=float32_ref>
<tf.Variable 'myscope/beta2_power:0' shape=() dtype=float32_ref>
```

However

code 2:
```
import tensorflow as tf
class generator:
    def __init__(self):
        with tf.variable_scope('myscope'):
            self.a = tf.get_variable('a', [4,3,2], tf.float32)
            self.b = tf.get_variable('b', [4,3,2], tf.float32)
            self.c = tf.reduce_sum(self.a + self.b)
            self.d = tf.train.AdamOptimizer(name = 'adamopt')
    
    def compute(self):
        with tf.variable_scope('myscope'):
            self.e1 = self.d.compute_gradients(self.c, tf.trainable_variables())
            self.f1 = self.d.apply_gradients(self.e1)
        print '------------------------'
        for item in tf.global_variables():
            if 'beta' in item.name:
                print item
    
    def compute1(self):
        with tf.variable_scope('myscope'):
            self.e2 = self.d.compute_gradients(self.c, tf.trainable_variables())
            self.f2 = self.d.apply_gradients(self.e2)
        print '---------------------------'
        for item in tf.global_variables():
            if 'beta' in item.name:
                print item

g = generator()
g.compute()
g.compute1()
```

results in:
```
------------------------
<tf.Variable 'myscope_1/beta1_power:0' shape=() dtype=float32_ref>
<tf.Variable 'myscope_1/beta2_power:0' shape=() dtype=float32_ref>
---------------------------
<tf.Variable 'myscope_1/beta1_power:0' shape=() dtype=float32_ref>
<tf.Variable 'myscope_1/beta2_power:0' shape=() dtype=float32_ref>
```

The only difference between two code is that the first code block doesn't operate 'apply_gradients' operation within the first opening of the variable scope. And I found that this results from the fact that the `beta` is made with `variable_scope.variable` operation. Is this a bug? or an intended results?

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by ravikyram** [comment]
I have tried on colab with TF version 1.12,1.15 and was able to reproduce the issue.Please, find the gists of [code1](https://colab.sandbox.google.com/gist/ravikyram/8da27df4cb68029c2dae23a95fb01d34/untitled439.ipynb) and [code2.](https://colab.sandbox.google.com/gist/ravikyram/2c0fffd2fae199f489869cf3bf8ae6f6/untitled440.ipynb) Thanks!

**Comment by jvishnuvardhan** [comment]
@yanghoonkim Is this still an issue for you? Can you please try latest versions and let us know how it progresses. Thanks!

Please close the issue if this was already resolved for you. Thanks!
