### ISSUE TITLE
@local_config_cc//:toolchain' does not contain a toolchain for cpu 'ios_x86_64'

### ISSUE THREAD

**Issue by suraj-0387** [tensorflow/tensorflow#34794]
I am trying to import mediapipe project using Bazel. But when try to sync the project by clicking on bazel->sync->sync bazel  I get following issues. I am using ubuntu LTS 18 version and bazel version is 0.29.1. I am new to mediapipe so please provide detail answer for the issue.
   
     Error:Error:line: 47in cc_toolchain_suite rule @local_config_cc//:toolchain: cc_toolchain_suite 
     '@local_config_cc//:toolchain' does not contain a toolchain for cpu 'ios_x86_64'

    Error:Error:While resolving toolchains for target @bazel_tools//tools/objc:dummy_lib: no 
    matching toolchains found for types @bazel_tools//tools/cpp:toolchain_type

**Comment by ravikyram** [comment]
Looks like the issue is not related to Tensorflow. Can you please elaborate about the issue & the context.Will it be possible to provide related code.Thanks!

**Comment by suraj-0387** [comment]
Hi Ravikyram, 

I am working on mediapipe Handtracking application and I am trying to import the project using bazel but I try to sync it 
it gives me that issue.I think I will have to add some configuration in some file but I really do not know what and where I have to add. 
As you know that mediapipe uses tensorflow and other developers are also facing the similar issue and they mention that it is a tensorflow issue 
and becuse of it I added it to tensorflow. 

Thanks and Regards, 
Suraj

**Comment by ravikyram** [comment]
Please, let us know which version of Tensorflow you are using. Is it possible to provide related code. Thanks!

**Comment by suraj-0387** [comment]
Tensorflow version 1.13.2 and the example can be accessed from mediapipe/examples/android/handtrackinggpu

**Comment by jvishnuvardhan** [comment]
@suraj-0387 Can you please post the issue in the `mediapipe` repo [here](https://github.com/google/mediapipe/issues). The resolution should be faster there. Thanks!

**Comment by suraj-0387** [comment]
close it
