### ISSUE TITLE
build tensorflow/python.tools:optimize_for_inference failed

### ISSUE THREAD

**Issue by 652994331** [tensorflow/tensorflow#34806]
\
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): source
- TensorFlow version: 1.14
- Python version: 3.7
- Installed using virtualenv? pip? conda?: conda
- Bazel version (if compiling from source): 0.26.0
- GCC/Compiler version (if compiling from source):6.4.0
- CUDA/cuDNN version:  cuda 10 cudnn 7 
- GPU model and memory: p40

i was trying to optimize tensorflow on cpu, that's why i followed a website to use tool: optimize_for_inference to decrease the size of my pb model.  I cloned tensorflow, get into the tensorflow directory,  used  
bazel build tensorflow/python.tools:optimize_for_inference to build optimize_for_inference script
.but i got some error like :
![image](https://user-images.githubusercontent.com/51428350/70078703-0927f200-15b8-11ea-9917-18f9b2ddf6b6.png)

![image](https://user-images.githubusercontent.com/51428350/70078751-20ff7600-15b8-11ea-94e6-a4a0dc874b32.png)

i am not sure what these problems are, could anyone help me out? thanks so much

**Comment by gowthamkpr** [comment]
What OS Platform and Distribution are you using @652994331

**Comment by 652994331** [comment]
Hi，it’s centos 7 linux&nbsp;



发自我的iPhone


------------------ Original ------------------

**Comment by gowthamkpr** [comment]
@652994331 As mentioned [here](https://github.com/tensorflow/tensorflow/issues/29053#issuecomment-551907472), this is a purely bazel issue, where bazel has a problem autodetecting the toolchain on the system.

I am closing this issue.You can reach out to bazel team, or try getting help through stackoverflow. Thanks!
