### ISSUE TITLE
Object detection evaluation done on only a subset of test images

### ISSUE THREAD

**Issue by enorkus** [tensorflow/tensorflow#34804]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): **No**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): **Google Colab**
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: **N/A**
- TensorFlow installed from (source or binary): **Default installation on Google Colab**
- TensorFlow version (use command below): **v1.15.0-0-g590d6eef7e 1.15.0**
- Python version: **Python 3.6.8**
- Bazel version (if compiling from source): **N/A**
- GCC/Compiler version (if compiling from source): **N/A**
- CUDA/cuDNN version: **N/A**
- GPU model and memory: **Google Colab**

**Describe the current behavior**
Evaluation is done on precisely 496 images
On every evaluation i get this:
    
    I1129 04:00:20.238537 139729717991168 coco_evaluation.py:205] Performing evaluation on 496 images.

**Describe the expected behavior**
Evaluation is done on 1000 images

**Code to reproduce the issue**
Training ssd_mobilenet_v2, using object_detection/model_main.py running the following:

    !python3 object_detection/model_main.py --pipeline_config_path=pipeline.config --model_dir=ssd_mobilenet/ --num_train_steps=200000 --sample_1_of_n_eval_examples=1 --alsologtostderr

Inside pipeline.config:
    
    num_examples: 1000

Also inside test images directory there is precisely 1000 annotated images.
I did not specify the number 496 anywhere and it seem to be changing according to how many images there actually is inside test directory.

**Comment by oanush** [comment]
@enorkus ,
Can you share a standalone code/gist of code used to reproduce the error reported here?Thanks!

**Comment by enorkus** [comment]
Not really possible. You have to have 1000 labeled images inside test directory, any number of images inside train directory, set `num_examples` inside `pipeline.config` to 1000 and run the training via:
`!python3 object_detection/model_main.py --pipeline_config_path=pipeline.config --model_dir=ssd_mobilenet/ --num_train_steps=200000 --sample_1_of_n_eval_examples=1 --alsologtostderr`

**Comment by enorkus** [comment]
Tried reproducing again after some time and cannot do it. Might have been a configuration problem after all.
