### ISSUE TITLE
Please add Tested build configurations for Tensorflow 1.15 and Tensorflow 1.15-gpu

### ISSUE THREAD

**Issue by gowthamkpr** [tensorflow/tensorflow#34805]
Thank you for submitting a TensorFlow documentation issue. Per our GitHub
policy, we only address code/doc bugs, performance issues, feature requests, and
build/installation issues on GitHub.

The TensorFlow docs are open source! To get involved, read the documentation
contributor guide: https://www.tensorflow.org/community/contribute/docs

## URL(s) with the issue: N/A

Please provide a link to the documentation entry, for example:
https://www.tensorflow.org/install/source

### Clear description

For example, why should someone use this method? How is it useful?
I cannot find the test build configurations for Tensorflow 1.15. It is useful for someone who is trying to build Tensorflow 1.15.

**Comment by ANaablevy** [comment]
Any update on this? Or what version of cudnn and CUDA are used in the pypi tensorflow 1.15 build?

**Comment by jvishnuvardhan** [comment]
@gowthamkpr I am closing this as this was resolved already. Please check the update tested build configs [here](https://www.tensorflow.org/install/source#tested_build_configurations). Thanks!
