### ISSUE TITLE
YOLOBOX ops, YoloNMS ops

### ISSUE THREAD

**Issue by mengjiexu** [tensorflow/tensorflow#34817]
Use tf2.0 project: yolov3-tf2
I train the model, and want to covert it to .tflite file. Then I get error:
Some of the operators in the model are not supported by the standard TensorFlow Lite runtime. If those are native TensorFlow operators, you might be able to use the extended runtime by passing --enable_select_tf_ops, or by setting target_ops=TFLITE_BUILTINS,SELECT_TF_OPS when calling tf.lite.TFLiteConverter(). Otherwise, if you have a custom implementation for them you can disable this error with --allow_custom_ops, or by setting allow_custom_ops=True when calling tf.lite.TFLiteConverter(). Here is a list of builtin operators you are using: ADD, CAST, CONCATENATION, CONV_2D, DEPTHWISE_CONV_2D, DIV, EXP, EXPAND_DIMS, FILL, LEAKY_RELU, LOGISTIC, MUL, PACK, PAD, RESHAPE, RESIZE_NEAREST_NEIGHBOR, SHAPE, SPLIT_V, STRIDED_SLICE, SUB. Here is a list of operators for which you will need custom implementations: CombinedNonMaxSuppression, Size.

The YoloBoxes and YoloNms ops is not supported.

**Comment by daverim** [comment]
Hi,

If you are trying to convert a model with custom ops, you will need to add the flag allow_custom_ops=True to the command line converter or by adding 
`converter.allow_custom_ops = True` before calling converter.convert() if you are using the Python API.

If you don't have the custom op implementation for the runtime, see this guide to adding custom ops to your runtime <https://www.tensorflow.org/lite/guide/ops_custom>

**Comment by amahendrakar** [comment]
@mengjiexu,
Is this still an issue? Could you please check @daverim's comment and let us know if the issue is resolved. Thanks!
