### ISSUE TITLE
gru convert tflite err(KeyError: 'kernel')

### ISSUE THREAD

**Issue by mkz0930** [tensorflow/tensorflow#34813]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):windows 10, notebook(anconda)
- TensorFlow installed from (source or binary): binary
- TensorFlow version (or github SHA if from source):
tensorflow2.0.0 (use pip install)

**Command used to run the converter or code if you’re using the Python API**
converter = tf.lite.TFLiteConverter.from_keras_model(model)
tflite_model = converter.convert() # where is wrong

 Copy and paste here the exact command
```python
input_tensor = tf.keras.Input(shape=(28, 28))
x = tf.keras.layers.GRU(154)(input_tensor)
x = tf.keras.layers.Flatten()(x)
out_tensor = tf.keras.layers.Dense(10, activation="relu")(x)
model = tf.keras.Model(input_tensor, out_tensor)
model.summary()

converter = tf.lite.TFLiteConverter.from_keras_model(model)
tflite_model = converter.convert() # where is wrong
open("converted_keras_model.tflite", "wb").write(tflite_model)
```
**The output from the converter invocation**
KeyError: 'kernel'
```
Copy and paste the output here.
KeyError                                  Traceback (most recent call last)
<ipython-input-7-b14fd83e63c7> in <module>()
     13 
     14 converter = tf.lite.TFLiteConverter.from_keras_model(model)
---> 15 tflite_model = converter.convert()
     16 open("converted_keras_model.tflite", "wb").write(tflite_model)

~\AppData\Roaming\Python\Python36\site-packages\tensorflow_core\lite\python\lite.py in convert(self)
    403 
    404     frozen_func = _convert_to_constants.convert_variables_to_constants_v2(
--> 405         self._funcs[0], lower_control_flow=False)
    406     input_tensors = [
    407         tensor for tensor in frozen_func.inputs

~\AppData\Roaming\Python\Python36\site-packages\tensorflow_core\python\framework\convert_to_constants.py in convert_variables_to_constants_v2(func, lower_control_flow)
    412 
    413   # Get mapping from function name to argument types.
--> 414   function_data = _get_control_flow_function_data(node_defs, tensor_data)
    415 
    416   # Get variable data for all nodes in `node_defs`.

~\AppData\Roaming\Python\Python36\site-packages\tensorflow_core\python\framework\convert_to_constants.py in _get_control_flow_function_data(node_defs, tensor_data)
    260         if arg_types[idx] == dtypes.resource:
    261           input_name = node.input[idx]
--> 262           arg_types[idx] = get_resource_type(input_name)
    263           output_shapes[idx] = get_resource_shape(input_name)
    264 

~\AppData\Roaming\Python\Python36\site-packages\tensorflow_core\python\framework\convert_to_constants.py in get_resource_type(node_name)
    226 
    227   def get_resource_type(node_name):
--> 228     numpy_type = tensor_data[node_name]["data"].dtype
    229     return dtypes.as_dtype(numpy_type).as_datatype_enum
    230 

KeyError: 'kernel'



**Failure details**
conversion is  wrong.



**Any other info / logs**

**Comment by wangtz** [comment]
Hi Renjie, 

Any thoughts / guidance on the RNN stuff?

**Comment by renjie-liu** [comment]
Hi Nupur, can you help take a look? thanks

**Comment by jvishnuvardhan** [comment]
@mkz0930 When I added experimental flag, everything worked as expected. Please add one line to your code after `converter`.

`converter.experimental_new_converter = True`

Please check the gist [here](https://colab.sandbox.google.com/gist/jvishnuvardhan/bbea3254d686cb5b2d32ffe9d43511a0/untitled685.ipynb). Thanks!

Please close the issue if it was resolved for you. Thanks!

**Comment by mkz0930** [comment]
> @mkz0930 When I added experimental flag, everything worked as expected. Please add one line to your code after `converter`.
> 
> ```python
> converter = tf.lite.TFLiteConverter.from_keras_model(model)
> converter.experimental_new_converter = True
> tflite_model = converter.convert()
> ```
> 
> Please check the gist [here](https://colab.sandbox.google.com/gist/jvishnuvardhan/bbea3254d686cb5b2d32ffe9d43511a0/untitled685.ipynb). Thanks!
> 
> Please close the issue if it was resolved for you. Thanks!

@jvishnuvardhan 
I'm sorry, it didn't work by adding the flag. The error is the same.

My version is 2.0.0, is your version 2.1rc?

**Comment by gargn** [comment]
@mkz0930 The flag `experimental_new_converter` is not available in 2.0. Please use the `tf-nightly` (`pip install tf-nightly`).

**Comment by mkz0930** [comment]
thanks very much ,it works@gargn

**Comment by stefan-falk** [comment]
This sounds familiar to me (see https://stackoverflow.com/questions/63303926/tfliteconverter-throws-keyerror-cond-1-input-1-0).

I sometimes get `KeyError: 'cond_1_input_1_0'` or `KeyError: 'kernel'`. Not quite sure yet what exactly causes what but does anybody else know maybe?
