### ISSUE TITLE
tflite load model failed use static library, how to get the error info, now only ok or error code?

### ISSUE THREAD

**Issue by mlinxiang** [tensorflow/tensorflow#34814]
i have a tflite model with two type float and float16, run with gpu(use c++ interface). float run ok and both model run ok use python, but float16 failed when use c++ code at code: auto iRetCode = m_pDeeplabInterp->ModifyGraphWithDelegate(m_pGPUDelegate); but this only return one error code 1, but no any other information, i can't find any way to do more thing to check whether is model has ops not support by tflite or my convert pipeline has error.

**Comment by impjdi** [comment]
can you share the model and the way you initialize & invoke the interpreter?

**Comment by mlinxiang** [comment]
when use c++ to run tflite model<both c++ and python are tensorflow 2.1>, system has't any information or error message output, tflite::StderrReporter is not used for tflite system to output error information. so are there any way to output system error information like model load failed info, invoke error info, and any thing else.

i used tensorflow/lite/tools/make scripts to compiled static library and call model by ndk in android app, float32 or quant model all run ok. but float16 can't run, failed at m_pDeeplabInterp->AllocateTensors(). so is there any micro define or flags to enable float16 feature of tflite?

**Comment by impjdi** [comment]
The error message may not be propagated in function definitions, but we print out details using `context->ReportError()` and this should be visible via `adb logcat`.  Well, at least that's how I get the details =/

**Comment by mlinxiang** [comment]
sad to get nothing from adb logcat

**Comment by impjdi** [comment]
@jdduke 

Do you have guidance on how one can retrieve the TFLite `context->ReportError()`?

**Comment by jdduke** [comment]
By default it should be routed to adb. Can you capture and send a bug report after you repro the issue? https://developer.android.com/studio/debug/bug-report
