### ISSUE TITLE
The checkpoint generated by tensorflow2.0 training does not have a meta file. How should it be converted to a pb file?

### ISSUE THREAD

**Issue by shenx3x** [tensorflow/tensorflow#34812]
When T1, the meta file is converted to a pb file, and then the pb file is converted to a tflite file. Now T2 does not generate a meta file, what should I do? Can anyone help me?

**Comment by ymodak** [comment]
You can try ```TFLiteConverter.from_saved_model()``` in TF 2.
See https://www.tensorflow.org/lite/convert/python_api#converting_a_savedmodel_
