### ISSUE TITLE
Compiling tensorflow 2.0.0 on Jetson AGX Xavier

### ISSUE THREAD

**Issue by vladsqp** [tensorflow/tensorflow#34825]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution: Linux Ubuntu 18.04
- TensorFlow installed from (source or binary): https://github.com/tensorflow/tensorflow/archive/v2.0.0.tar.gz
- TensorFlow version: 2.0.0
- Python version: 3.6.9
- Installed using virtualenv? pip? conda?: pip
- Bazel version (if compiling from source): 0.26.1
- GCC/Compiler version (if compiling from source): 7.4.0
- CUDA/cuDNN version: 10.0.326 / 7.5
- GPU model and memory: Jetson AGX Xavier (512-core Volta GPU with Tensor Cores) 16GB

**Describe the problem**
I'm compiling tensorflow 2.0.0 on Jetson AGX Xavier.
I'm following the tutorial on: https://jkjung-avt.github.io/build-tensorflow-2.0.0/
but compiling blaze fails with:
```
ERROR: /mnt/nvme/tensorflow_install/jetson_nano/src/tensorflow-2.0.0/tensorflow/python/keras/api/BUILD:46:1: Executing genrule //tensorflow/python/keras/api:keras_python_api_gen_compat_v2 failed (Exit 1)
Traceback (most recent call last):
  File "/mnt/nvme/.cache/bazel/_bazel_nvidia/98cdf810b71446efc44591ffddb09367/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/python/keras/api/create_tensorflow.python_api_2_keras_python_api_gen_compat_v2.runfiles/org_tensorflow/tensorflow/python/tools/api/generator/create_python_api.py", line 27, in <module>
    from tensorflow.python.tools.api.generator import doc_srcs
  File "/mnt/nvme/.cache/bazel/_bazel_nvidia/98cdf810b71446efc44591ffddb09367/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/python/keras/api/create_tensorflow.python_api_2_keras_python_api_gen_compat_v2.runfiles/org_tensorflow/tensorflow/python/__init__.py", line 52, in <module>
    from tensorflow.core.framework.graph_pb2 import *
  File "/mnt/nvme/.cache/bazel/_bazel_nvidia/98cdf810b71446efc44591ffddb09367/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/python/keras/api/create_tensorflow.python_api_2_keras_python_api_gen_compat_v2.runfiles/org_tensorflow/tensorflow/core/framework/graph_pb2.py", line 7, in <module>
    from google.protobuf import descriptor as _descriptor
ModuleNotFoundError: No module named 'google.protobuf'
Target //tensorflow/tools/pip_package:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 13210.120s, Critical Path: 451.46s
INFO: 11876 processes: 11876 local.
FAILED: Build did NOT complete successfully
```
but on the other hand if I'm running that line alone it works no problem:
```
/mnt/nvme/tensorflow_install/jetson_nano$ python3
Python 3.6.9 (default, Nov  7 2019, 10:44:02) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from google.protobuf import descriptor as _descriptor
>>> exit()
```

I'm assuming something wrong with my enviroment, but how can I check it?

**Comment by gadagashwini** [comment]
@vladsqp, Please Provide the exact sequence of commands / steps that you executed before running into the problem. Thanks!

**Comment by vladsqp** [comment]
I've followed the exact sequence of commands from here: https://jkjung-avt.github.io/build-tensorflow-2.0.0/
But it seems the issue was solved:
I've followed the solution 2 here: https://stackoverflow.com/a/57068827

And also installed protobuf for all my python versions just in case bazel is using the wrong one at that stage.
Now it works builds!
