### ISSUE TITLE
Update Docker Image

### ISSUE THREAD

**Issue by drcrook1** [tensorflow/tensorflow#3482]
Hey All,

There are a variety of issues I'm running into with the docker image, just basic stuff.
1.  sudo apt-get update
2.  Python3 support
3.  Nano is not installed (vim is the worst)
   3a.  I want this so I can easily edit the notebook config for setting passwords.
4.  The jupyter notebook needs to be updated to the latest
5.  Pip updates
6.  Maybe ship with Anaconda as well.

Its just a variety of things that aren't working quite well.  I'm trying to put together a Jupyter Notebook our machine learning meetup group can use and share, and its just a pain in the neck. 

I tried to do just a fresh setup from a fresh linux vm, but I was having issues getting Jupyter to actually recognize the TensorFlow install; so now I'm trying the docker image again.  The biggest issue with the docker image in its current state is that after a while the auto-save starts breaking, json formats for posting to save break and then it messes up the encoding of the notebook, which then becomes more or less un-recoverable (without extensive effort).

I beleive (not sure) that updating everything in the supported image would fix at least some of these issues.

**Comment by kootenpv** [comment]
I think vim is more popular than nano...
I'm mostly bothered by the fact that tensorflow is an old version and not "the latest". It runs 0.7.0. How could that be?

**Comment by Anthony-Tatowicz** [comment]
On Docker Hub you can pick which version they have different tags in the tach section, there is 0.9 and even nightlys. The other stuff your best bet is to create our own image based off they one they have. The current image installs the latest pip and jupyter when you run it, if you want to update you can either create bash into the container and update or rerun the container.
