### ISSUE TITLE
Slicing error: Using a `tf.Tensor` as a Python `bool` is not allowed

### ISSUE THREAD

**Issue by DSLituiev** [tensorflow/tensorflow#3483]
### Environment info
Operating System:
MacOSX, Python3, tensorflow version '0.9.0'

### Steps to reproduce
1. I am trying to slice a tensor (I want to remove boundaries for purpose of error evaluation)
```
# vector_loss  = tf.Variable(...)
pad = 8
width = tf.shape(vector_loss,)[2]
vector_loss = vector_loss[:,:,pad:width-pad, :]
```

### Logs or other output that would be helpful
(If logs are large, please upload as attachment).
```
Traceback (most recent call last):
  File "./footprint_poisson.py", line 445, in <module>
    epochs=50)
  File "./footprint_poisson.py", line 263, in fit
    tot_loss = self._create_loss()
  File "./footprint_poisson.py", line 220, in _create_loss
    poisson_loss_ = poisson_loss(self.vars.y, self.vars.y_predicted, pad = 8)
  File "./footprint_poisson.py", line 28, in poisson_loss
    vector_loss = vector_loss[:,:,pad:width-pad, :]
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/tensorflow/python/ops/array_ops.py", line 176, in _SliceHelper
    if s.stop is not None and s.stop < 0:
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 515, in __bool__
    raise TypeError("Using a `tf.Tensor` as a Python `bool` is not allowed. "
TypeError: Using a `tf.Tensor` as a Python `bool` is not allowed. Use `if t is not None:` instead of `if t:` to test if a tensor is defined, and use the logical TensorFlow ops to test the value of a tensor.
```

**Comment by concretevitamin** [comment]
Quick things to check:

1) Do you mean `tf.shape(vector_loss,)` or, without the comma?
2) Make sure the shape of `vector_loss` is fully defined.  I think you need `width` to be a constant.

**Comment by aselle** [comment]
ranges cannot be specified with tensors, they have to be values.... so you must do
```
pad = 8
width = tf.shape(vector_loss,)[2]
start, end = pad, (width - pad ).eval()
vector_loss = vector_loss[:,:,start:end, :]
```

Soon, we will release negative index support which will not ease the restriction that the end range cannot be a tensor, but it will allow

`vector_loss[:,:,pad:-pad,:]
`

**Comment by DSLituiev** [comment]
Looks like shape of `vector_loss` was not fully defined. Can ranges be specified with `tensorflow.python.framework.tensor_shape.Dimension`?

**Comment by aselle** [comment]
The change that I was describing will be sync'd soon (it's internal). For now try,
```python
shape = tf.shape(vector_loss)
start = tf.pack([0,0,pad,0])
size = tf.pack([shape[0],shape[1],shape[2]-pad,shape[3]])
vector_loss = vector_loss.slice(start,size)
```

**Comment by aselle** [comment]
This is now done and including as of 57197386a469e00693540481de08a9b1770c7bb4
