### ISSUE TITLE
TF2.0 - Cannot convert EagerTensor to datatype and casting

### ISSUE THREAD

**Issue by 00krishna** [tensorflow/tensorflow#34848]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution Linux Ubuntu 18.04
- TensorFlow installed from (source or binary): Installed from Anaconda
- TensorFlow version (use command below):
`python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`
unknown 2.0.0
I am using TF 2.0.0.
- Python version: python 3.7.4
- Bazel version (if compiling from source): NA
- GCC/Compiler version (if compiling from source): NA
- CUDA/cuDNN version: Cuda release 10.1, V10.1.168; cudnn 7.6.0

- GPU model and memory: Nvidia GTX 1080 11GB.

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
The code provided generates an error:
```
TypeError: Cannot convert 1.0 to EagerTensor of dtype int64
```
The cause of the error is not clear but the setup of the code basically follows the Tensorflow tutorial.

**Describe the expected behavior**
The `model.fit()` function should run and complete training. Instead this error gets generated and the training terminates early. I only get like step or such. 

**Code to reproduce the issue**
Note that the error gets generated towards the bottom of the `main()` function, where I invoke the `fit()` function. 

```
#!/usr/bin/python

from __future__ import absolute_import, division, print_function, unicode_literals

# import comet_ml in the top of your file
from comet_ml import Experiment
from comet_ml import Optimizer
import numpy as np
import pandas as pd
import tensorflow as tf
import datetime
from tensorflow import feature_column
from tensorflow.keras import layers
from sklearn.model_selection import train_test_split

# Add the following code anywhere in your machine learning file

def main():

    # Import and setup data

    URL = 'https://storage.googleapis.com/applied-dl/heart.csv'
    dataframe = pd.read_csv(URL)

    # Setup training test split

    train, test = train_test_split(dataframe, test_size=0.2)
    train, val = train_test_split(train, test_size=0.2)
    print(f'The training set is of length: {len(train)}')
    batch_size = 32

    train_ds = df_to_dataset(train, batch_size=batch_size)
    val_ds = df_to_dataset(val, shuffle=False, batch_size=batch_size)
    test_ds = df_to_dataset(test, shuffle=False, batch_size=batch_size)

    size_train_ds = get_dataset_length(df_to_dataset(train, batch_size=1, repeat=1))
    size_test_ds = get_dataset_length(df_to_dataset(test, batch_size=1, repeat=1))
    size_validation_ds = get_dataset_length(df_to_dataset(val, batch_size=1, repeat=1))

    print(f' training data length is: {size_train_ds}')
    print(f' test data length is: {size_test_ds}')
    print(f' validation data length is: {size_validation_ds}')
    # Configure experiment and hyperparameters to test with.

    hparams = {"nodes":128, "thal_embedding_cols": 3}

    loss = fit_model(train_ds,  # <-- ERROR GETS GENERATED AROUND HERE.
                     test_ds,
                     val_ds,
                     epochs=100,
                     batch_size=batch_size,
                     number_training_examples=size_train_ds,
                     number_testing_examples=size_test_ds,
                     number_validation_examples=size_validation_ds,
                     hyper_parameters=hparams)


    return 0

def df_to_dataset(dataframe, shuffle=True, repeat=None, batch_size=32):
    dataframe = dataframe.copy()
    labels = dataframe.pop('target')
    ds = tf.data.Dataset.from_tensor_slices((dict(dataframe), labels))
    if shuffle:
        ds = ds.shuffle(buffer_size=len(dataframe))
    ds = ds.batch(batch_size).repeat(repeat)
    return ds

def get_dataset_length(ds):
    """
    This function will get the number of examples in a tf.data.Dataset. Make
    sure that the batch size for the dataset is set to 1, otherwise this
    function will count the number of batches in the data. 
    """
    return ds.reduce(np.int64(0), lambda x, _: x + 1)

def define_features(hyper_parameters):

    feature_columns = []
    # numeric cols
    for header in ['age', 'trestbps', 'chol', 'thalach', 'oldpeak', 'slope', 'ca']:
        feature_columns.append(feature_column.numeric_column(header))
        

    # bucketized cols
    age = feature_column.numeric_column("age")
    age_buckets = feature_column.bucketized_column(age,
                                                   boundaries=[18, 25, 30, 35,
                                                               40, 45, 50, 55,
                                                               60, 65])
    #feature_columns.append(age_buckets)

    # indicator cols
    thal = feature_column.categorical_column_with_vocabulary_list(
        'thal', ['fixed', 'normal', 'reversible'])
    thal_one_hot = feature_column.indicator_column(thal)
    #feature_columns.append(thal_one_hot)

    # embedding cols
    thal_embedding = feature_column.embedding_column(thal,
                                                     dimension= \
                                                     hyper_parameters['thal_embedding_cols'])
    #feature_columns.append(thal_embedding)

    # crossed cols
    crossed_feature = feature_column.crossed_column([age_buckets, thal], hash_bucket_size=1000)
    crossed_feature = feature_column.indicator_column(crossed_feature)
    #feature_columns.append(crossed_feature)
    return feature_columns

def build_model(features, hyper_parameters):
    '''
    documentation string
    '''
    feature_layer = tf.keras.layers.DenseFeatures(features)

    model = tf.keras.Sequential([
        feature_layer,
        layers.Dense(hyper_parameters['nodes'], activation='relu'),
        layers.Dense(hyper_parameters['nodes'], activation='relu'),
        layers.Dense(hyper_parameters['nodes'], activation='relu'),
        layers.Dense(hyper_parameters['nodes'], activation='relu'),
        layers.Dense(1, activation='sigmoid')
    ])

    model.compile(optimizer='adam',
                  loss='binary_crossentropy',
                  metrics=['accuracy'])

    return model


def fit_model(
              train_dataset,
              test_dataset,
              validation_dataset,
              epochs=None,
              batch_size=None,
              number_training_examples=None,
              number_testing_examples=None,
              number_validation_examples=None,
              hyper_parameters=None):


    model = build_model(define_features(hyper_parameters), hyper_parameters)

    log_dir = "logs/fit/" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
    tensorboard_callback = tf.keras.callbacks.TensorBoard(log_dir=log_dir, histogram_freq=1)

    model.fit(train_dataset,
              validation_data = test_dataset,
              epochs = epochs,
              steps_per_epoch = number_training_examples//batch_size,
              validation_steps= number_testing_examples//batch_size,
              callbacks = [tensorboard_callback])

    # score = model.evaluate(x_test, y_test, verbose=0)[1]
    loss, accuracy = model.evaluate(validation_dataset,
                                    steps=number_validation_examples//batch_size,
                                    verbose=0)
    print(loss)
    return loss

if __name__ == "__main__":
    main()

```

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

NA

**Comment by oanush** [comment]
Issue replicating for TF 2.0 and tf-nightly, please find the [gist](https://colab.sandbox.google.com/gist/oanush/d9e6b644abc2f9610e677bf2ac4cd6e6/34854.ipynb) of colab.Thanks!

**Comment by 00krishna** [comment]
Okay, I figured out the cause of this error. The `get_dataset_length()` function returns a tensor instead of a scalar. And when I pass that tensor to the `fit()` function as below
```
model.fit(train_dataset,
              validation_data = test_dataset,
              epochs = epochs,
              steps_per_epoch = number_training_examples//batch_size, <--PROBLEM
              validation_steps= number_testing_examples//batch_size, <-- PROBLEM
              callbacks = [tensorboard_callback])
```
Then when I pass the tensor to the `fit()` function, this generates the error message. But the error message has nothing to do with the actual error. So that is a big problem since it took me a while to figure out that this is the problem. This could be a simple error trapping issue. Or, if you think that these functions should treat tensors as first-class citizens, then all of the function arguments should be able to accept tensors too, right?

Anyhow, that is what I figured out.

**Comment by 00krishna** [comment]
Hey folks. So again, the issue seems to be associated with the `get_dataset_length()` function returning a tensor of 1 integer value. So it seems like the `model.fit()` function cannot accept tensors for the `steps_per_epoch` or such arguments. Now I guess that is a design question. Should those argument be limited to scalar values in principal, or should they be able to take a tensor and parse it for a single scalar value?

**Comment by ravikyram** [comment]
Issue replicating for TF 2.2 and tf-nightly, please find the [gist](https://colab.research.google.com/gist/ravikyram/aede98eece4cafc03f123fda870d768d/untitled28.ipynb) of colab.Thanks!

**Comment by talhaanwarch** [comment]
Is this issue resolved?

**Comment by sushreebarsa** [comment]
Was able to replicate the issue in TF v2.5 ,please find the gist [here](https://colab.research.google.com/gist/sushreebarsa/54763fa5449817ab8b3368a8fff992ce/untitled28.ipynb#scrollTo=94DG3yfQGZfB)..Thanks !

**Comment by renziver** [comment]
Encountered the same issue when I used a `tensor` for the provided data size length. This is using `tensorflow-2.6.0`

`train_size = train_split.reduce(0, lambda x, _: x + 1)`
  `val_size = val_split.reduce(0, lambda x, _: x + 1)`
`batch_size =8`
`model.fit(..., steps_per_epoch=train_size//batch_size` <-- ERROR  `TypeError: Cannot convert 1.0 to EagerTensor of dtype int64`

The solution was to convert the tensor to a scalar value i.e. train_size.numpy()

But I agree that it was hard to debug as the given error is a big unclear.

**Comment by mohantym** [comment]
@00krishna ! This issue was getting resolved after putting any random number in **steps_per_epoch and validation_steps** of last model.fit() operation. Attaching [Gist ](https://colab.sandbox.google.com/gist/mohantym/b2679fd377f26782e5308adad5d3c334/untitled28.ipynb#scrollTo=FTNA_s_K10tI)for reference. Thanks!

**Comment by 00krishna** [comment]
@mohantym thanks so much for your help with this. I appreciate the assistance.
