### ISSUE TITLE
How to add "TFLite_Detection_Postprocess" op in Keras model when using tf2.x

### ISSUE THREAD

**Issue by JoelTsui** [tensorflow/tensorflow#34857]
In tf1.x, I used `export_tflite_ssd_graph.py` function in the `object_detection` module to convert model adding`TFLite_Detection_Postprocess` op, but now, I write model use Keras in tf2.x, and there are no documents to tell how to do the conversion.

**Comment by jvishnuvardhan** [comment]
@JoelTsui Do you have any model that you want to convert? There is a [`new expeimental_new_converter`](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/examples/experimental_new_converter) that you could try.

Please let us know more details and a standalone code to reproduce the issue. Thanks!

**Comment by JoelTsui** [comment]
The problem is not about "convert", but about adding `TFLite_Detection_Postprocess` op when converting

**Comment by jvishnuvardhan** [comment]
@JoelTsui Can you please share a standalone code to reproduce the issue? Thanks!

**Comment by jvishnuvardhan** [comment]
@JoelTsui Can you please share a standalone code to reproduce the issue? Thanks!

**Comment by jvishnuvardhan** [comment]
Closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
