### ISSUE TITLE
SparseCategoricalCrossEntropy example contains a mistake in terms of input

### ISSUE THREAD

**Issue by Antymon** [tensorflow/tensorflow#34858]
## URL(s) with the issue:

https://github.com/tensorflow/tensorflow/blob/1cf0898dd4331baf93fe77205550f2c2e6c90ee5/tensorflow/python/keras/losses.py#L493

### Clear description

Entries [1,0] and [1,2] of a tensor linked to should be 10 times smaller in order for the second entry to sum up to 1.

### Submit a pull request?

Are you planning to also submit a pull request to fix the issue? 

No, the change seems too small for an expensive TF CI to run.

**Comment by Yash-Varshney** [comment]
Hello Developers ! I am new to open source community and want to contribute to tensorflow.
I got the issue but I dont know how to solve this issue. Any help would highly be appreciated .
Thanks..

**Comment by jvishnuvardhan** [comment]
@Antymon Can you please check the `master` [here](https://github.com/tensorflow/tensorflow/blob/1d846a29c7879772634e0fd286764259531b63c0/tensorflow/python/keras/losses.py#L520). It was corrected there. Thanks!

**Comment by Antymon** [comment]
Cool.
