### ISSUE TITLE
 tf.feature_column.shared_embeddings supports eager mode 

### ISSUE THREAD

**Issue by workingloong** [tensorflow/tensorflow#34862]
**System information**
- TensorFlow version (you are using): TF 2.0.0
- Are you willing to contribute it (Yes/No): No

**Describe the feature and the current behavior/state.**
Using tensorflow-2.0.0 with eager mode,  tf.feature_column.shared_embeddings  can not support eager mode. 

**Will this change the current api? How?**
No.

**Who will benefit with this feature?**
tf.feature_column.shared_embeddings is a common feature column API，we can use it for multiple category_column with embedding parameters.

**Any Other info.**

**Comment by ravikyram** [comment]
@workingloong 
Do you have any use case that requires the feature you are interested in? Please feel free to submit a PR if you have use cases that supports that feature.Thanks!

**Comment by tanzhenyu** [comment]
We don't have plans for supporting additional features with feature columns at this point. The right solution will come with this [RFC](https://github.com/tensorflow/community/pull/188)

**Comment by panpan123456** [comment]
Has this problem been solved?I had met the same problem
