### ISSUE TITLE
saved_model.go

### ISSUE THREAD

**Issue by jacobxy** [tensorflow/tensorflow#34867]
where is the package "github.com/tensorflow/tensorflow/tensorflow/go/genop/internal/proto/github.com/tensorflow/tensorflow/tensorflow/go/core"?
   I can't build the program.

**Comment by oanush** [comment]
@jacobxy ,
Can you please provide more information about the issue? also provide a standalone code to reproduce the issue,mention the TF version being used.Thanks!

**Comment by oanush** [comment]
@jacobxy ,
Any update on the issue?Thanks!
