### ISSUE TITLE
[TF2.0]how to save model to get .pb in this example?

### ISSUE THREAD

**Issue by SmileTM** [tensorflow/tensorflow#34865]
https://www.tensorflow.org/tutorials/text/nmt_with_attention
In this [example](https://www.tensorflow.org/tutorials/text/nmt_with_attention) ,how to save model to get .pb ? 

I tried this way, but have some bugs.
what should I do? 
```
tf.saved_model.save(decoder, "./decoder_out/1")
tf.saved_model.save(encoder, "./encoder_out/1")


encoder = tf.saved_model.load('./encoder_out/1')
decoder = tf.saved_model.load('./decoder_out/1')

sentence = u'¿todavia estan en casa?'
attention_plot = np.zeros((max_length_targ, max_length_inp))
sentence = preprocess_sentence(sentence)
    
inputs = [inp_lang.word_index[i] for i in sentence.split(' ')]
inputs = tf.keras.preprocessing.sequence.pad_sequences([inputs],maxlen=max_length_inp,padding='post')
    
    
inputs = tf.convert_to_tensor(inputs)
result = ''
hidden = [tf.zeros((1,units))]
enc_out, enc_hidden = encoder(inputs, hidden)


---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-59-ba6b7bf7814b> in <module>
     10 result = ''
     11 hidden = [tf.zeros((1,units))]
---> 12 enc_out, enc_hidden = encoder(inputs, hidden)

TypeError: '_UserObject' object is not callable

```

**Comment by SmileTM** [comment]
the encoder.call  have two parameters. In this way, how to save model (.pd) ?
```
class Encoder(tf.keras.Model):
  def __init__(self, vocab_size, embedding_dim, enc_units, batch_sz):
    super(Encoder, self).__init__()
    self.batch_sz = batch_sz
    self.enc_units = enc_units
    self.embedding = tf.keras.layers.Embedding(vocab_size, embedding_dim)
    self.gru = tf.keras.layers.GRU(self.enc_units,
                                   return_sequences=True,
                                   return_state=True,
                                   recurrent_initializer='glorot_uniform')

  def call(self, x, hidden):
    x = self.embedding(x)
    output, state = self.gru(x, initial_state = hidden)
    return output, state

  def initialize_hidden_state(self):
    return tf.zeros((self.batch_sz, self.enc_units))
```

**Comment by xiaoyangnihao** [comment]
@SmileTM Hi, How did you solve this problem ? I am stuck in this problem for several days, hoping you reply, thanks.

**Comment by SmileTM** [comment]
> @SmileTM @oanush Hi, How did you solve this problem ? I am stuck in this problem for several days, hoping your reply, thanks.

In tensorflow2.0,  if you have  two parameters or more  parameters， we need follow this code：

```
class MyLayer(tf.keras.layers.Layer):
    def __init__(self,**kwargs):
        super(MyLayer, self).__init__(**kwargs)
    def call(self, inputs):
        a,b,c,d = inputs
        e = a+b+c+d
        return e

layer = MyLayer()
result = layer((a,b,c,d))    
 ```
 two parameters or more  parameters need to be packed by list or tuple in `def call`. 
If your parameters not be packed by list or tuple, it will have some errors when you deploy `.pd` in your server .

the `.pd`, just use `model.save('path')` can be getten.

**Comment by xiaoyangnihao** [comment]
> > @SmileTM @oanush Hi, How did you solve this problem ? I am stuck in this problem for several days, hoping your reply, thanks.
> 
> In tensorflow2.0, if you have two parameters or more parameters， we need follow this code：
> 
> ```
> class MyLayer(tf.keras.layers.Layer):
>     def __init__(self,**kwargs):
>         super(MyLayer, self).__init__(**kwargs)
>     def call(self, inputs):
>         a,b,c,d = inputs
>         e = a+b+c+d
>         return e
> 
> layer = MyLayer()
> result = layer((a,b,c,d))    
> ```
> 
> two parameters or more parameters need to be packed by list or tuple in `def call`.
> If your parameters not be packed by list or tuple, it will have some errors when you deploy `.pd` in your server .
> 
> the `.pd`, just use `model.save('path')` can be getten.

Thanks for your quick reply, I will try.

**Comment by xiaoyangnihao** [comment]
@SmileTM Hi, I opened a issue: https://github.com/tensorflow/tensorflow/issues/37439, which also is similar,  TypeError: '_UserObject' object is not callable, can you have a quick look, or any suggestions ? Thanks.

**Comment by hahadashi** [comment]
> the encoder.call have two parameters. In this way, how to save model (.pd) ?
> 
> ```
> class Encoder(tf.keras.Model):
>   def __init__(self, vocab_size, embedding_dim, enc_units, batch_sz):
>     super(Encoder, self).__init__()
>     self.batch_sz = batch_sz
>     self.enc_units = enc_units
>     self.embedding = tf.keras.layers.Embedding(vocab_size, embedding_dim)
>     self.gru = tf.keras.layers.GRU(self.enc_units,
>                                    return_sequences=True,
>                                    return_state=True,
>                                    recurrent_initializer='glorot_uniform')
> 
>   def call(self, x, hidden):
>     x = self.embedding(x)
>     output, state = self.gru(x, initial_state = hidden)
>     return output, state
> 
>   def initialize_hidden_state(self):
>     return tf.zeros((self.batch_sz, self.enc_units))
> ```
@SmileTM @xiaoyangnihao @oanush 
hi ,  have you solve your problem？i also want to frozen the attention model，and split them to two  pb model（Encoder and deocder）。i use  tf.compat.v1.train.write_graph （some people advice）. use this way i can convert ckpt model to pb model. but i run their model and their result is different . i dont know whats wrong with me,  hope you give some advice.

**Comment by hahadashi** [comment]
> > the encoder.call have two parameters. In this way, how to save model (.pd) ?
> > ```
> > class Encoder(tf.keras.Model):
> >   def __init__(self, vocab_size, embedding_dim, enc_units, batch_sz):
> >     super(Encoder, self).__init__()
> >     self.batch_sz = batch_sz
> >     self.enc_units = enc_units
> >     self.embedding = tf.keras.layers.Embedding(vocab_size, embedding_dim)
> >     self.gru = tf.keras.layers.GRU(self.enc_units,
> >                                    return_sequences=True,
> >                                    return_state=True,
> >                                    recurrent_initializer='glorot_uniform')
> > 
> >   def call(self, x, hidden):
> >     x = self.embedding(x)
> >     output, state = self.gru(x, initial_state = hidden)
> >     return output, state
> > 
> >   def initialize_hidden_state(self):
> >     return tf.zeros((self.batch_sz, self.enc_units))
> > ```
> 
> @SmileTM @xiaoyangnihao @oanush
> hi , have you solve your problem？i also want to frozen the attention model，and split them to two pb model（Encoder and deocder）。i use tf.compat.v1.train.write_graph （some people advice）. use this way i can convert ckpt model to pb model. but i run their model and their result is different . i dont know whats wrong with me, hope you give some advice.

i find restore ckpt model or h5 model is failure. 。 some pb model op params value is initial value
