### ISSUE TITLE
use 'grpc + verbs' appears (core dumped)

### ISSUE THREAD

**Issue by Richie-yan** [tensorflow/tensorflow#34863]
When I change the protocol to 'grpc + verbs' for RDMA training, the program will have a core dump:

INFO tensorflow 140500786698048 Create CheckpointSaverHook.
INFO tensorflow 140500786698048 Start Tensorflow server.
tensorflow/core/distributed_runtime/rpc/grpc_channel.cc:215] Initialize GrpcChannelCache for job chief
...
tensorflow / contrib / verbs / rdma.cc: 159] Check failed: num_devs_with_active_port> 0 There is no active port in the system
(core dumped)

My underlying environment is ROCE，25worker+16ps
Is it my environmental problem? The program works when I use protocol to 'grpc'.
I want to know what is causing this error and how to fix it？

**Comment by ravikyram** [comment]
Can you please elaborate about the issue & the context.Will it be possible to provide related code.It helps us in localizing the issue faster.Also, let us know which Tensorflow version you are using?Thanks!

**Comment by byronyi** [comment]
@Richie-yan You could run a basic test of your RoCE environment by `ibv_devinfo`. It appears to me that all of your IB/RDMA ports are down.

**Comment by Richie-yan** [comment]
@byronyi  
I use ibstat for testing. The mlx5_0 Port 1 status of several machines is Active, and I can run rdma traffic using ib_write_bw

**Comment by byronyi** [comment]
@Richie-yan Then you could try setting ENV VARS `RDMA_DEVICE` and `RDMA_DEVICE_PORT` manually. See https://github.com/tensorflow/tensorflow/blob/r1.15/tensorflow/contrib/verbs/rdma.cc#L129-L162 for the underlying logic.

**Comment by ravikyram** [comment]
@Richie-yan 

was this resolved by following @byronyi  suggestion? . Thanks!

**Comment by ravikyram** [comment]
@Richie-yan 

Any update on this issue please. Thanks!

**Comment by ravikyram** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
