### ISSUE TITLE
Skipping optimization warning when using tanh activation in LSTM layers

### ISSUE THREAD

**Issue by giamic** [tensorflow/tensorflow#34874]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 19.10
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): v2.0.0-rc2-26-g64c3d38 2.0.0
- Python version: 3.7
- GPU model and memory: no GPU

**Describe the current behavior**
When training a model containing an LSTM layer with activation function 'tanh', I receive the following warnings:

> W tensorflow/core/grappler/optimizers/implementation_selector.cc:310] Skipping optimization due to error while loading function libraries: Invalid argument: Functions '__inference___backward_cudnn_lstm_with_fallback_2431_2613' and '__inference___backward_standard_lstm_2770_3255_specialized_for_StatefulPartitionedCall_at___inference_distributed_function_3336' both implement 'lstm_c366749f-d70a-4931-b887-2ea0c126b791' but their signatures do not match.
> W tensorflow/core/grappler/optimizers/implementation_selector.cc:310] Skipping optimization due to error while loading function libraries: Invalid argument: Functions '__inference_cudnn_lstm_with_fallback_3844' and '__inference_standard_lstm_3733_specialized_for_model_lstm_StatefulPartitionedCall_at___inference_distributed_function_4076' both implement 'lstm_3433d132-ad4b-4073-bc24-8ed871518bdc' but their signatures do not match.

However, it feels like the model is still training, despite the warning. The warnings disappear when changing the activation function.

**Describe the expected behavior**
The warning shouldn't appear.

**Code to reproduce the issue**
```
import numpy as np
import tensorflow as tf
from tensorflow.keras.layers import Input, LSTM
from tensorflow.keras.models import Model

n_trn, n_vld = 10_000, 100
x_trn = np.random.randint(2, size=(n_trn, 10, 2))
y_trn = x_trn
x_vld = np.random.randint(2, size=(n_vld, 10, 2))
y_vld = x_vld

train_data = tf.data.Dataset.from_tensor_slices((x_trn, y_trn)).repeat().batch(100)
valid_data = tf.data.Dataset.from_tensor_slices((x_vld, y_vld)).repeat().batch(100)

x = Input(shape=(10, 2))
y = tf.math.abs(LSTM(2, return_sequences=True, dropout=0.3, activation='tanh')(x))

model = Model(inputs=[x], outputs=y)
model.compile(optimizer='adam', loss='binary_crossentropy')
model.fit(train_data, steps_per_epoch=100, epochs=100, validation_data=valid_data, validation_steps=1)
```

**Comment by ravikyram** [comment]
I have tried on colab with TF version 2.0 and i am not seeing any issue. Please, find the gist [here](https://colab.sandbox.google.com/gist/ravikyram/3d0d3b8b6d88e4b3ac4b09b060201265/untitled453.ipynb). Thanks!

**Comment by ravikyram** [comment]
@giamic 

Any update on this issue please. Thanks!

**Comment by ravikyram** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
