### ISSUE TITLE
tf.string tensors are not converted to numpy string arrays

### ISSUE THREAD

**Issue by hermannsblum** [tensorflow/tensorflow#34871]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Bug appears on Linux Ubuntu 18.04, but also in Colab Notebooks
- TensorFlow version (use command below): 2.0.0
- Python version: 3.6

**Describe the current behavior**

[Colab Notebook to reproduce](https://colab.research.google.com/drive/13zEPEBbfOR0U5TVc4dABxtT6NUB6TftL)

When casting a tensor of type `tf.string` to a numpy array in eager mode, the ndarray does not have a correct string dtype, but is converted to an array of arbitrary objects.

```
tf_str = tf.constant(['Hello World', 'B'])
>> <tf.Tensor: id=1, shape=(2,), dtype=string, numpy=array([b'Hello World', b'B'], dtype=object)>
tf_str.numpy()
>> array([b'Hello World', b'B'], dtype=object)
tf_str.numpy().astype(str)  # expicit casting to string
>> array(['Hello World', 'B'], dtype='<U11')
```

**Describe the expected behavior**
It would be expected that a `tf.string` datatype is converted to a [numpy string datatype](https://docs.scipy.org/doc/numpy/reference/arrays.dtypes.html#string-dtype-note).

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

[Colab Notebook to reproduce](https://colab.research.google.com/drive/13zEPEBbfOR0U5TVc4dABxtT6NUB6TftL)

**Comment by gowthamkpr** [comment]
@hermannsblum Thats an expected behavior of numpy. Please refer to the following [question](https://stackoverflow.com/questions/16037824/how-to-convert-numpy-object-array-into-str-unicode-array) for more details.
