### ISSUE TITLE
Cannot execute the substraction op with the broadcast mechanism

### ISSUE THREAD

**Issue by TomorrowIsAnOtherDay** [tensorflow/tensorflow#34891]
```python
import tensorflow as tf
import numpy as np
x = tf.constant(np.random.random((500, 6)))
y = x - x[:,0]
```
This code raises the issue of not supporting [500,6] - [500] in the `sub` OP.
I suppose that it should compute correctly, using the broadcast automatically?
Is it a bug? 
version: tf2.0

**Comment by amahendrakar** [comment]
Could reproduce the issue with TF version 2.0. Please find the [Gist](https://colab.sandbox.google.com/gist/amahendrakar/4c280e1f0c990947b4397089a389ce91/34891.ipynb) here.
Thanks!

**Comment by TomorrowIsAnOtherDay** [comment]
Same problem in div op.
Please have a check on it, too.

**Comment by TomorrowIsAnOtherDay** [comment]
@jvishnuvardhan any progress here?

**Comment by ravikyram** [comment]
could reproduce the issue with TF version 2.2.0-dev20200319. Please, find the gist [here](https://colab.sandbox.google.com/gist/ravikyram/bebc538e6b1827e4fd2031f2768ec363/untitled739.ipynb#scrollTo=8w0YFR4JHdg6). Thanks!

**Comment by jvishnuvardhan** [comment]
@TomorrowIsAnOtherDay I updated part of your code. You could use the following to access just a column and subtract it from the whole tensor. 

```
import numpy as np
x = tf.constant(np.random.random((500, 6)))
indices = [0]
y = x - tf.gather(x, indices, axis=1)
```
 
Please close the issue if this was resolved for you. Thanks!

**Comment by TomorrowIsAnOtherDay** [comment]
This is an ugly solution. I just want to write the code in a pythonic way, but the solution rolls me back into tf1.0.

**Comment by saxenasaurabh** [comment]
This is consistent with the broadcast semantics of numpy:

```
>>> x=np.random.random((500, 6))
>>> x-x[:,0]
ValueError: operands could not be broadcast together with shapes (500,6) (500,) 
```
