### ISSUE TITLE
SavedModel format for tf.estimator class in Tensorflow 2.0

### ISSUE THREAD

**Issue by jnsgrnborg** [tensorflow/tensorflow#34895]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): NO
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): mac os mojave 10.14.6
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below):  2.0.0
- Python version: 2.7.10 
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**

I'm moving to TF 2.0 with its very nice dataset functionalities, but I got stuck when I want to save the model in the SavedModel format.

I'm using the estimator class to do a linear regression, and after training this is how I'd set up the export in TF 1:
```
columns = [('hour', tf.int64),
           ('domain', tf.string),
           ('device_type', tf.string)]
feature_placeholders = {
 name: tf.placeholder(dtype, [1], name=name + "_placeholder")
 for name, dtype in columns
}
```
I have three features with different datatypes, and I use the placeholder method to concatenate them into a dict that is then served using the tf.estimator.export.build_raw_serving_input_receiver_fn() method, and finally exported using the estimator.export_saved_model to my model directory:

```
export_input_fn = tf.estimator.export.build_raw_serving_input_receiver_fn(
    feature_placeholders)
estimator.export_saved_model(model_dir, export_input_fn)
```
All tutorials online uses this series of steps, but tf.placeholder() doesn't exist in TF 2.0, so how can I do this?

**Comment by karmel** [comment]
In 2.0, you can use tf.compat.v1.placeholder. We have [moved to Keras as the primary high level API](https://medium.com/tensorflow/standardizing-on-keras-guidance-on-high-level-apis-in-tensorflow-2-0-bad2b04c819a), and would encourage you to write your models using Keras if possible. Estimator is fundamentally tied to v1/Sessions, so if you must stay in the Estimator ecosystem, you will likely have to use some amount of compat.v1 functionality.

**Comment by jnsgrnborg** [comment]
Hey Karmel

Thanks for answering!

Currently I'm training in TF 2.0 and then serializing in TF 1.x. Seems to be working..

**Comment by 17patelumang** [comment]
@jnsgrnborg  have you tried reverse ? training in TF 1.x and serializing in TF 2.0 ?
