### ISSUE TITLE
Fit of Undefined in train TensorFlowJS - Transfer learning audio recognizer

### ISSUE THREAD

**Issue by burakberber** [tensorflow/tensorflow#34899]
In the example of 'Transfer learning audio recognizer' there is an error on lines.
**Uncaught (in promise) TypeError: Cannot read property 'fit' of undefined**

there is an error highlighted like shown :

![Ekran Resmi 2019-12-06 17 09 11](https://user-images.githubusercontent.com/25597808/70328972-566fc200-184b-11ea-9add-c31964511b35.png)

**Comment by oanush** [comment]
@burakberber ,
Please raise the issue related to TF.js in this [repo](https://github.com/tensorflow/tfjs/issues/new).Thanks!
