### ISSUE TITLE
tf.execute_volume_patches misses one dimension when used with placeholders and None

### ISSUE THREAD

**Issue by fontm2** [tensorflow/tensorflow#34898]
Tested in with tf 1.12.0 and tf 2.0. Below code for use with tf 2.0.

p = tf.keras.backend.placeholder((1,None,None,None,1))
kernel = [1,3,3,3,1]
strides = [1,1,1,1,1]
tf.extract_volume_patches(p, kernes, strides, 'SAME')
>>><tf.Tensor 'ExtractVolumePatches:0' shape=(1, None, None, 27) dtype=float32>

p = tf.keras.backend.placeholder((1,120,130,140,1))
kernel = [1,3,3,3,1]
strides = [1,1,1,1,1]
tf.extract_volume_patches(p, kernes, strides, 'SAME')
>>><tf.Tensor 'ExtractVolumePatches:0' shape=(1, 120, 130, 140, 27) dtype=float32>

Is there a reason behind this behaviour?

**Comment by ravikyram** [comment]
I have tried on colab with TF version 1.12,1.15, 2.0, 2.1.0-rc0 and was able to reproduce the issue.Please, find the gist [here](https://colab.sandbox.google.com/gist/ravikyram/b83ee96afa6000082d3e4ee4c3c7bf3d/untitled452.ipynb). Thanks!

**Comment by ravikyram** [comment]
could reproduce the issue with TF version 2.2.0-dev20200319. Please, find the gist [here.](https://colab.sandbox.google.com/gist/ravikyram/b83ee96afa6000082d3e4ee4c3c7bf3d/untitled452.ipynb#scrollTo=EqLHygzDEuZU).Thanks!

**Comment by ymodak** [comment]
@hsgkim Can you please take a look at this issue? Looks like this is possibly related to your changes in the past. 
Thank you.

**Comment by sushreebarsa** [comment]
I have tried this in TF version 2.5 ,please find the gist [here](https://colab.research.google.com/gist/sushreebarsa/9261c352b130574b4f5833582e8debb5/untitled106.ipynb?authuser=1)  ..Thanks !

**Comment by sushreebarsa** [comment]
Closing this issue as it is fixed in latest version of TensorFlow. Please feel free to reopen the issue if you still have a concern. Thanks!

**Comment by sushreebarsa** [comment]
Was able to reproduce the issue on Colab using tf-nightly , please find the [gist](https://colab.research.google.com/gist/sushreebarsa/88092eb250d677541cfeabcec7e5a8b7/untitled738.ipynb) for reference.Thanks!

**Comment by tilakrayal** [comment]
@fontm2,
As mentioned in the official doc, while we are trying the `tf.extract_volume_patches`, the **ksizes** and **strides** should be the list of ints that has length >= 5

![Screenshot 2023-04-27 12 44 46 PM](https://user-images.githubusercontent.com/81610181/234787527-cd9ade5b-f964-4503-962d-dc19a96acf32.png)



**Args:**
ksizes | A list of ints that has length >= 5. The size of the sliding window for each dimension of input.
-- | --
strides | A list of ints that has length >= 5. 1-D of length 5. How far the centers of two consecutive patches are in input. Must be: [1, stride_planes, stride_rows, stride_cols, 1].

**Comment by MKimiSH** [comment]
> I was able to reproduce the issue on Colab using tf-nightly(2.13.0-dev20230215). I also tried with TF2.x API `tf.keras.Input()` and observed similar results. please find the gist of [nightly-2.13.0-dev20230215](https://colab.sandbox.google.com/gist/tilakrayal/7aa962c597086ad64fad1a36498c591c/34898_2_13ipynb.ipynb) for reference.Thank you!

I ran the colab notebook just now with the latest tf-nightly versions and the problem is still there. How come it's still not resolved?
