### ISSUE TITLE
tf.keras.models.Sequential does not support run_eagarly

### ISSUE THREAD

**Issue by Squadrick** [tensorflow/tensorflow#34890]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- TensorFlow installed from (source or binary): Binary
- TensorFlow version (use command below): v1.12.1-16986-g6c32a22 2.1.0-dev20191029
- Python version: 3.6.8

**Describe the current behavior**
`tf.keras.models.Sequential` doesn't support `run_eagarly` as mentioned in the [docs](https://www.tensorflow.org/api_docs/python/tf/keras/Sequential#run_eagerly).

**Describe the expected behaviour**
Either Sequential model accepts `run_eagarly` as a param and changes its behaviour, or we modify the docs. 

**Code to reproduce the issue**

```python
import tensorflow as tf

model = tf.keras.models.Sequential(
    layers=[tf.keras.layers.Dense(input_shape=(3, ), units=1)], 
    run_eagerly=True)
```

**Other info / logs**

```
Traceback (most recent call last):
  File "tst.py", line 5, in <module>
    run_eagerly=True)
  File "/home/squadrick/.local/lib/python3.6/site-packages/tensorflow_core/python/training/tracking/base.py", line 457, in _method_wrapper
    result = method(self, *args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'run_eagerly'
```

**Comment by oanush** [comment]
@Squadrick,
Hello, Please try giving `run_eagerly=True` as a parameter to compile it should work fine, kindly refer the [link](https://www.tensorflow.org/guide/keras/overview#train_and_evaluate).
Also find the [gist](https://colab.sandbox.google.com/gist/oanush/e1262a3a58d8bf0e6bb4419b361e78d7/34890.ipynb) of colab. Let us know if it helped.Thanks!

**Comment by Squadrick** [comment]
@oanush My issue is more to do with the incorrect documentation. I eventually figured out how to run the model, but the documentation is completely wrong.

**Comment by Squadrick** [comment]
@karmel Any update on this?

**Comment by lamberta** [comment]
Hi @Squadrick, what part of the doc is incorrect? It doesn't say it's an argument to init. But could clarify in the doc string that it should be called in compile. It would be useful to add the param to the .compile method.
Can you send a PR for https://www.tensorflow.org/api_docs/python/tf/keras/Sequential?version=nightly ?
The pages have a link "View source" to edit the docstring.

**Comment by Squadrick** [comment]
My bad. I figured `Properties` meant things that could be passed to `__init__`. The docs are correct. I'll close this issue, thanks for the help.

**Comment by Squadrick** [comment]
I'll create the PR soon.
