### ISSUE TITLE
tensorflow gpu inference  only one thread is busy

### ISSUE THREAD

**Issue by gao8954** [tensorflow/tensorflow#34906]
PID USER      PR  NI    VIRT    RES    SHR S %CPU %MEM     TIME+ COMMAND
  **5708 root      20   0 21.518g 1.820g 794224 S 82.0  0.7   6:38.31 server**
  5722 root      20   0 21.518g 1.820g 794224 S  8.0  0.7   0:36.46 server
  5747 root      20   0 21.518g 1.820g 794224 S  8.0  0.7   0:36.61 server
  5712 root      20   0 21.518g 1.820g 794224 S  7.7  0.7   0:36.35 server
  5714 root      20   0 21.518g 1.820g 794224 S  7.7  0.7   0:36.49 server
  5716 root      20   0 21.518g 1.820g 794224 S  7.7  0.7   0:36.57 server
  5718 root      20   0 21.518g 1.820g 794224 S  7.7  0.7   0:36.36 server
  5721 root      20   0 21.518g 1.820g 794224 S  7.7  0.7   0:36.52 server
  5723 root      20   0 21.518g 1.820g 794224 S  7.7  0.7   0:36.42 server
  5724 root      20   0 21.518g 1.820g 794224 S  7.7  0.7   0:36.47 server
  5725 root      20   0 21.518g 1.820g 794224 S  7.7  0.7   0:36.60 server
  5726 root      20   0 21.518g 1.820g 794224 R  7.7  0.7   0:36.48 server
  5728 root      20   0 21.518g 1.820g 794224 R  7.7  0.7   0:36.35 server
  5730 root      20   0 21.518g 1.820g 794224 S  7.7  0.7   0:36.46 server
  5731 root      20   0 21.518g 1.820g 794224 S  7.7  0.7   0:36.37 server
  5734 root      20   0 21.518g 1.820g 794224 S  7.7  0.7   0:36.42 server
  5736 root      20   0 21.518g 1.820g 794224 S  7.7  0.7   0:36.43 server
  5737 root      20   0 21.518g 1.820g 794224 S  7.7  0.7   0:36.35 server
  5741 root      20   0 21.518g 1.820g 794224 R  7.7  0.7   0:36.58 server

tensorflow gpu inference  only one thread is busy, and the inference is so slow ,and the gpu useage is low, something bug?

tensorflow gpu version is 1.13.1

**Comment by amahendrakar** [comment]
Please provide details about what platform you are using (operating system, architecture). Also, did you compile from source or install a binary?

Make sure you also include the exact command if possible to produce the output included in your test case. If you are unclear what to include see the issue template displayed in [the Github new issue template](https://github.com/tensorflow/tensorflow/issues/new/choose/new).

We ask for this in the issue submission template, because it is really difficult to help without that information. Thanks!

**Comment by gao8954** [comment]
![image](https://user-images.githubusercontent.com/7404433/70619013-18a9d980-1c4f-11ea-9ffe-3f5c9a048b4a.png)
![image](https://user-images.githubusercontent.com/7404433/70619031-22cbd800-1c4f-11ea-9fe3-b360db148978.png)
install a binary  from here, (alse try the version 1.15.0, same performance)
![image](https://user-images.githubusercontent.com/7404433/70619174-658db000-1c4f-11ea-99e7-9c8d6412be60.png)
https://www.tensorflow.org/install/lang_c

**Comment by jvishnuvardhan** [comment]
@gao8954 Can you please follow the `gpu` usage guide [here](https://www.tensorflow.org/guide/gpu) and let us know whether it resolved your issue. Thanks!

**Comment by jvishnuvardhan** [comment]
Closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
