### ISSUE TITLE
Unified file system support implementation for C++/Python

### ISSUE THREAD

**Issue by llhe** [tensorflow/tensorflow#3491]
Currently the C++ code has file system interface and provides POSIX and GCS implementation. However, part of the Python code also using another file system abstraction (tensorflow/python/summary/impl/gcs.py). This is annoying and tedious to supporting new type of file systems. So what is the consideration here and whether this is plan to make the Python code depending on C++ IO abstraction only.

**Comment by michaelisard** [comment]
@rohan100jain can you comment on this?

**Comment by rohan100jain** [comment]
I'm actively working on this right now. The idea is what you suggested - exposing a python file interface that wraps the internal C++ file system interface so that all new file systems can just be directly implemented on top of C++ and is available automatically.

**Comment by llhe** [comment]
@rohan100jain when will this feature be released? may be the interace can be released first?
we want to add our dfs support based on this and don't wish to do in the current GCS way which hacks the python layer.

**Comment by vrv** [comment]
I think you can probably get started right now implementing the file_system.h API -- there is a private internal library in python that currently already binds to the C++ implementation, but we have not yet exposed it until we can completely replace all of the existing uses.  By the time you probably get all of the C++ components done, I'm optimistic that the python support will be there too.

Which DFS are you working on, and where were you planning on hosting the code, btw?  Alternative implementations of the file_system implementations should be a matter of building and linking a shared library, but we haven't yet tried this ourselves (currently we host and support all of the file system implementations, but we probably won't do this for all filesystems).

**Comment by llhe** [comment]
@vrv It's a DFS we developed and mainly used internally: https://github.com/XiaoMi/galaxy-fds-sdk-cpp. And we host it in our internal branch since the audience is quite limited right now, so it's not a problem now. We already implemented the file_system based on 0.9 and the basic train/export/serving flow can work, however many python code are broken.

As you mentioned, hosting can be an issue when the DFS can't be accepted and integrated to the trunk code tree. What about supporting dynamic loading of the file system plugin, just like adding customized op? I can work on it if contribution welcome.

I just found the recently release internal python interface file_io.py as you mentioned, a great progress, expecting it goes public.

**Comment by llhe** [comment]
@vrv By the way, I noticed two facts:
1. file_io.py only support read_file_to_string for reading, will it be problematic for large files?
2. the GCS implemented recently added read ahead buffer. In fact we also support this improvement for our DFS implementation. I wondering will the sequential access pattern guaranteed by the upper level? Or else the performance can be very bad when the caching/buffering failed. If not, may be exposing a config parameter for NewRandomAccessFile to allow flexible caching a better solution?

**Comment by llhe** [comment]
Just checked code, the plugin mechanism is already implemented but not documented: ./tensorflow/python/framework/test_file_system.cc

**Comment by rohan100jain** [comment]
file_io.py is now live and gfile redirects to it now. This should unify the python and C++ implementations. Let me know if there are further feature requests.

@llhe 
1. vrv@ just added support for read(n). This mirrors what we used to have and should help out with large files
2. We have a BufferedInputStream that does buffering on top of the RandomAccessFile. The python read(n), tell(), seek() functions are using it now as well. Its not perfect read ahead (in which we should perhaps read the next chunk of the buffer via a second thread etc.) but it should help out a bit with performance. Please feel free to open more feature requests if needed.

The plugin mechanism for file systems isn't documented but there is a separate issue tracking that (https://github.com/tensorflow/tensorflow/issues/4120)

Closing this bug now.
