### ISSUE TITLE
AssertionError: Could not compute output Tensor

### ISSUE THREAD

**Issue by Supachan** [tensorflow/tensorflow#34912]
I am trying to use functional API to build an encoder-decoder model for grammatical error correction. Given incorrect sentences (x) and correct sentences (y):

```
x = tf.random.uniform(shape=(1000,8), minval=2, maxval=voc_len, dtype=tf.dtypes.int32)
y = tf.random.uniform(shape=(1000,6), minval=2, maxval=voc_len, dtype=tf.dtypes.int32)

x = np.array(tf.concat([tf.ones([1000,1], tf.int32), x, tf.zeros([1000,1], tf.int32)], 1))
y = np.array(tf.concat([tf.ones([1000,1], tf.int32), y, tf.zeros([1000,1], tf.int32)], 1))

input_x = Input(shape=(None,), name='inc_sent')
input_y = Input(shape=(None,), name='cor_sent')

emb_enc = Embedding(input_dim=voc_len+1, output_dim=emb_size, name='inc_emb')(input_x)
emb_dec = Embedding(input_dim=voc_len+1, output_dim=emb_size, name='cor_emb')(input_y)

gru_enc_l1 = GRU(units, return_sequences = True, return_state = True, recurrent_initializer='glorot_uniform', name='inc_gru_l1')
gru_dec_l1 = GRU(units, return_sequences = True, return_state = True, recurrent_initializer='glorot_uniform', name='cor_gru_l1')

o_enc1, h_enc1 = gru_enc_l1(emb_enc, initial_state = tf.zeros([1000,100]))
o_dec1, h_dec1 = gru_dec_l1(emb_dec, initial_state = h_enc1)

# I would like to inspect o_dec1:
model = Model(inputs = [input_x, input_y], outputs = o_dec1)

model(x,y)
```
The error shows `AssertionError: Could not compute output Tensor("cor_gru_l1_28/Identity:0", shape=(1000, None, 100), dtype=float32)`

How can I fix it? Please let me know. Thank you in advance

**Comment by amahendrakar** [comment]
@Supachan,
Tried reproducing your code but got the error `NotImplementedError: Cannot convert a symbolic Tensor (concat:0) to a numpy array. `. Please find the attached [Gist](https://colab.sandbox.google.com/gist/amahendrakar/f28189f8b7f88dd779743fda5c4968f3/34912.ipynb#scrollTo=lVyyh8qXVu09) here.
Can you please help us to reproduce the issue. Also please provide Tensorflow version, platform details etc. Thanks!

**Comment by amahendrakar** [comment]
Any update on this issue? Thanks!

**Comment by Supachan** [comment]
To amahendrakar,

I am sorry to reply you late. The code was figured out by typing the last line: `model = ([x,y])`. Just inserted `[ ]` into `x,y`.

```
from __future__ import absolute_import, division, print_function, unicode_literals

import matplotlib.pylab as plt

try:
  # %tensorflow_version only exists in Colab.
  %tensorflow_version 2.x
except Exception:
  pass

import tensorflow as tf
from tensorflow.keras.layers import Flatten, Layer, Dense, LayerNormalization, Embedding, Dropout, Concatenate, Input, GRU, LSTM
from tensorflow.keras.models import Sequential, Model

voc_len = 30
emb_size = 10
units = 100

x = tf.random.uniform(shape=(1000,8), minval=2, maxval=10, dtype=tf.dtypes.int32)
y = tf.random.uniform(shape=(1000,6), minval=2, maxval=10, dtype=tf.dtypes.int32)

x = np.array(tf.concat([tf.ones([1000,1], tf.int32), x, tf.zeros([1000,1], tf.int32)], 1))
y = np.array(tf.concat([tf.ones([1000,1], tf.int32), y, tf.zeros([1000,1], tf.int32)], 1))

input_x = Input(shape=(None,), name='inc_sent')
input_y = Input(shape=(None,), name='cor_sent')

emb_enc = Embedding(input_dim=voc_len+1, output_dim=emb_size, name='inc_emb')(input_x)
emb_dec = Embedding(input_dim=voc_len+1, output_dim=emb_size, name='cor_emb')(input_y)

gru_enc_l1 = GRU(units, return_sequences = True, return_state = True, recurrent_initializer='glorot_uniform', name='inc_gru_l1')
gru_dec_l1 = GRU(units, return_sequences = True, return_state = True, recurrent_initializer='glorot_uniform', name='cor_gru_l1')

o_enc1, h_enc1 = gru_enc_l1(emb_enc, initial_state = tf.zeros([1000,100]))
o_dec1, h_dec1 = gru_dec_l1(emb_dec, initial_state = h_enc1)

# I would like to inspect o_dec1:
model = Model(inputs = [input_x, input_y], outputs = o_dec1)

model([x,y])

```

Hope this help you. Let me close this issue.

**Comment by Supachan** [comment]
To amahendrakar,

I forget one thing to answer your question. The code was run on Colab and TF2.0.
Thanks.

Supachan

**Comment by TamMinhVo** [comment]
Hello all!! I have met the same problem. Could you please share your solution for this. Thank you so much.

**Comment by amahendrakar** [comment]
@TamMinhVo,
> I am sorry to reply you late. The code was figured out by typing the last line: `model = ([x,y])`. Just inserted `[ ]` into `x,y`.

The above change seems to help. Please check if it works. if not submit a new issue from [this link](https://github.com/tensorflow/tensorflow/issues/new/choose), so that we can track the issue there. Thanks!

**Comment by drcege** [comment]
This feature is super misleading!  It wasted me half a day to figure out the problem.

It should be emphasized in the documentation.

**Comment by samcaetano** [comment]
I had the same issue here using tf.data.Datasets and, for me, the problem was related with the inputs and outputs.

I solved by naming each input layer and latter by creating a TF Dataset with the inputs as a dict and the output as a single value. Something like the following:

` # Example code

x1 = tf.keras.layer.Input(..., name='input_1')
x2 = tf.keras.layer.Input(..., name='input_2')
......
concat_layer = tf.keras.layers.Concatenate([x1, x2])
y = tf.keras.layer.Dense(1)(x1)

model = Model([x1, x2], y)

dataset = tf.data.Dataset(....) # suppose each sample in dataset is a triple (2-features and 1 label)

def input_solver(sample):
    return {'input_1': sample[0], 'input_2': sample[1]}, sample[2]

dataset.map(input_solver) # this will map the first and the second feature in this triple-sample to the inputs.
model.fit(dataset, epochs=5)
`

This solved for me with multiple inputs datasets

**Comment by CheWang09** [comment]
Hello, I also have the same problem. When I use keras bert , it throws out an issue about inputs and outputs. Can anyone help me solve this problem.
![image](https://user-images.githubusercontent.com/32276346/92403591-58f9a200-f164-11ea-9637-d5f866aeeb00.png)
Above is my code.
And following is my code problem 
![image](https://user-images.githubusercontent.com/32276346/92403672-81819c00-f164-11ea-8220-1c504ab0f699.png)

**Comment by amahendrakar** [comment]
> Hello, I also have the same problem. When I use keras bert , it throws out an issue about inputs and outputs. Can anyone help me solve this problem.

@Supachan,
Could you please submit a new issue from [this link](https://github.com/tensorflow/tensorflow/issues/new/choose) and fill in the template, so that we can track the issue there. Thanks!

**Comment by mhorlacher** [comment]
> return {'input_1': sample[0], 'input_2': sample[1]}, sample[2]


This is what fixed it for me.
