### ISSUE TITLE
Tensorflow Lite does not include GPU 

### ISSUE THREAD

**Issue by j-o-d-o** [tensorflow/tensorflow#34922]
**System information**
- OS Platform and Distribution: Linux Mint 19
- TensorFlow installed from (source or binary): source
- TensorFlow version: current master (094da7eaa9d802ee676170f2df58ded528da52d9)
- Installed using: make (as shown here: https://www.tensorflow.org/lite/guide/build_arm64)
- GCC/Compiler version (if compiling from source): gcc 7.4.0
- CUDA/cuDNN version: V9.1.85
- GPU model and memory: GeForce GTX 1660 6GB

**Describe the problem**
The Makefile (tensorflow/tensorflow/lite/tools/make/Makefile) for TF Lite does not include any possibility to include gpu delegates for x86.

```bash
>> ./download_dependencies.sh
>> ./build.lib.sh
```

Then e.g. this will result in an undefined reference error: 
```cpp
TfLiteGpuDelegateV2Create()
```

**What I have tried**
I adapted some files and tried to get it working, but with little success:
```bash
# for cl support
>> sudo apt-get install nvidia-cuda-toolkit
# egl
>> sudo apt-get install libegl1-mesa-dev
# gles
>> sudo apt-get install libgles2-mesa-dev

# add fp16 to download_dependencies.sh
FP16_URL="https://github.com/Maratyszcza/FP16/archive/master.zip"
...
download_and_extract "${FP16_URL}" "${DOWNLOADS_DIR}/fp16"

# add to Makefile
INCLUDES := \
...
-I$(MAKEFILE_DIR)/downloads/fp16/include \
...

CORE_CC_ALL_SRCS := \
...
$(wildcard tensorflow/lite/delegates/*.cc) \
$(wildcard tensorflow/lite/delegates/gpu/**/*.cc) \
...
```

Results in error:
```
In file included from /usr/include/EGL/eglplatform.h:124:0,
                 from /usr/include/EGL/egl.h:39,
                 from ./tensorflow/lite/delegates/gpu/cl/egl_sync.h:19,
                 from tensorflow/lite/delegates/gpu/cl/egl_sync.cc:16:
./tensorflow/lite/delegates/gpu/common/status.h:47:7: error: expected identifier before ‘int’
 class Status {
```

**Comment by daverim** [comment]
Hi @impjdi, could you help answer this question? Thanks!

**Comment by impjdi** [comment]
EGL by default pulls in X11 headers.  X11 includes a

> typedef int Status;

somewhere.  You need to find the flag that disables that.  It's different for each platform, so I can't pinpoint which flag you need to set.  One of the name's I've seen in the past is something like `MESA_EGL_NO_X11_HEADER`, but really, you have to dig deeper and find the flag that does the job.

**Comment by j-o-d-o** [comment]
Thanks for the feedback!
I am still a bit lost. Is this expected? Is the code within `tensorflow/lite/delegates/gpu` ever used then e.g. when using bazel? Could not find any docu about that.

**Comment by impjdi** [comment]
That part is usually built with proper EGL for mobile devices, not Mesa.

TFLite GPU is not friendly with non-mobile setting (yet?).

**Comment by j-o-d-o** [comment]
Ah ok, that might explain why I have trouble getting it work. Then I guess I am just using the wrong tool for my usecase.
Nevertheless, would be a cool feature.
