### ISSUE TITLE
Support EIGEN_USE_MKL_ALL macro for building tensorflow

### ISSUE THREAD

**Issue by refraction-ray** [tensorflow/tensorflow#34924]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using): tf1.14, tf2.0
- Are you willing to contribute it (Yes/No): No, I am not familiar with bazel

**Describe the feature and the current behavior/state.**
If my understanding is correct, the compiling flag `--config=mkl` for bazel only enables mkl-dnn supports which could replace several basic ops like matrix multiplication with mkl implementation using jit. However, it seems to me that this flag doesn't enable mkl linkage with Eigen. Therefore, all linear ops beyond several covered in mkl-dnn are still executed in plain eigen single-threaded implementation which is too slow to use (there can be O(10) or even O(100) speed difference for large matrix and eigh, svd, qr ops, as previously noted in https://github.com/tensorflow/tensorflow/issues/7128, https://github.com/tensorflow/tensorflow/issues/13222, etc.). 

Currently, in tensorflow.bzl, `DEIGEN_USE_VML` flag is set when compiled with --config=mkl. As explained in https://github.com/tensorflow/tensorflow/issues/30592, this indicates eigen is not enabled with mkl at all. But a simple replacement of this flag with `DEIGEN_USE_MKL_ALL` leads to failure of the compiling with the error complaining <mkl.h> not found. Also as noted https://github.com/tensorflow/tensorflow/pull/12219, MKL optimized Tensorflow does not support EIGEN_USE_MKL_ALL. I know little about bazel setup, so I don't know whether turn on such support is involved or as simple as some small tweaks.

In sum, tuning tf building system to "really" enable mkl behind tf is of great importance and it is vital for the speed of a large range of matrix ops. And this should be the expected behavior for `--config=mkl` flag after all. Currently, so called "intel optimized" or "mkl enabled" tensorflow is somehow confusing.

**Will this change the current api? How?**
Not for the user level API.

**Who will benefit with this feature?**
Anyone using tf in his/her workflow including matrix operations like EIG, SVD, QR etc on CPU. (One can argue that there is no problem for GPU implementation, but cusolver implementations for SVD and QR can still be much slower than mkl cpu implementations. So fast CPU implementations are critical for these matrix decomposition types op).

**Any Other info.**

**Comment by Leslie-Fang** [comment]
@refraction-ray Could give the full build commands which you use?

**Comment by refraction-ray** [comment]
@Leslie-Fang , I believe the building workflow is similar to [official doc](https://www.tensorflow.org/install/source#cpu-only_2) using devel docker. The only tweak I have done is changing the flag in tensorflow.bzl directly into `DEIGEN_USE_MKL_ALL`.
This fails building for sure, since no path (header or library) is specified for mkl library which eigen is required now. Since I have no time to learn about bazel building system, I didn't try adding some cxxopts or hacking more bazel files. And https://github.com/tensorflow/tensorflow/pull/12219 gives me the impression `DEIGEN_USE_MKL_ALL` support is not trivial in tf building.
And this is the reason for this issue, either some experts tell me how to build tf with `EIGEN_USE_MKL_ALL` flag by some small tweaks or building related codebase is better to be improved accordingly for mkl support.

**Comment by Leslie-Fang** [comment]
@refraction-ray if that's the case in https://github.com/tensorflow/tensorflow/pull/12219 , although I don't know why but MKLDNN support and eigen with mkl support seems cann't be enabled simultaneously.
Which Eigen ops is the bottleneck of your application?
I have done some Eigen op optimization previously.

**Comment by refraction-ray** [comment]
@Leslie-Fang , as I have mentioned, QR, SVD decompositions are slow with eigen implementation compared to MKL multithreaded version.

**Comment by Leslie-Fang** [comment]
@refraction-ray Do you know how to measure the performance of QR, SVD ops with MKL multithreaded version?

**Comment by Leslie-Fang** [comment]
I see some comments in the https://github.com/tensorflow/tensorflow/issues/7128 about how to measure the performance. 
I will try to enable the native Eigen multithread version.

**Comment by refraction-ray** [comment]
@Leslie-Fang , great! Be sure to use mkl linked numpy for the benchmark

**Comment by Leslie-Fang** [comment]
@refraction-ray Have checked the implementation of QR and SVD in tensorflow.
https://github.com/tensorflow/tensorflow/blob/a74e202f4a93c19863061d18979436b0470d862d/tensorflow/core/kernels/qr_op_impl.h#L101-L120
Both of them are invoking eigen in-place decomposition.
https://eigen.tuxfamily.org/dox/classEigen_1_1HouseholderQR.html
I suspect there is no parallel optimization we can do in the tensorflow op.

**Comment by refraction-ray** [comment]
@Leslie-Fang , this is why I believe the better solution here is to enable mkl linkage with eigen when building tensorflow. If this works, all ops can enjoy multithreaded mkl implementation and no need to hack these ops one by one.

**Comment by Exferro** [comment]
Hi everyone, could you please tell if there has been any progress on the subject? I am not an expert, but enabling MKL support for Eigen operations sounds like a reasonable solution, and would be highly appreciated. Otherwise, it's a bit frustrating to see how TensorFlow humbly uses only one core, while NumPy enjoys running SVD with >1000% CPU load :-)

**Comment by NeoZhangJianyu** [comment]
@refraction-ray 
Though Eigen supports mkl (https://eigen.tuxfamily.org/dox/TopicUsingIntelMKL.html), it not available through Tensorflow.

**Comment by Venkat6871** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
