### ISSUE TITLE
Tutorial for Data Augmentation using tf.image

### ISSUE THREAD

**Issue by akalakheti** [tensorflow/tensorflow#34935]
Hi, my name is Rachin Kalakheti and i am a participant of Google Code-in 2019. I felt overwhelmed to know Tensorflow is also one of the organization for this year. So, there was a task to create a notebook tutorial on Data Augmentation using tf.image. I see that currently there is no tutorial regarding the same topic. So, I would like to contribute to the community by adding my tutorial to the  Tensorflow repo. Therefore I am seeking guidance as to discuss this further.
Link to my notebook tutorial: https://colab.research.google.com/drive/1skGIQhwifJY6HWO6ZnbFe4un-VuJ3VW5

Thank you!

**Comment by dubesar** [comment]
@akalakheti  Does this task is included in GCI 2019. Note that you get points for tasks included in the portal. Confirm this before doing this.

**Comment by akalakheti** [comment]
Yes, this task is included in GCI 2019 and I have completed this task.

**Comment by akalakheti** [comment]
any update in this issue?

**Comment by akalakheti** [comment]
Why is there no response on this issue?

**Comment by rohanreddych** [comment]
I dont see any "issue" here if this is your issue `I am seeking guidance as to discuss this further` then you should ask this in a mailing list or any forum.

**Comment by swghosh** [comment]
Is this issue still open?

**Comment by MarkDaoust** [comment]
@swghosh: Yes. let me go check the status of that PR.

**Comment by jvishnuvardhan** [comment]
I am closing this issue as the related PR already merged. Please feel free to reopen if I am mistaken. Thanks!
