### ISSUE TITLE
TensorFlow broadcasting results in error of Incompatible shapes

### ISSUE THREAD

**Issue by hoangcuong2011** [tensorflow/tensorflow#34931]
Greetings,

Another day, another potentially "deep" bug with TF I found! :-) 

I have three tensors: A, B, C. Here A is of shape (None, 64, 64), B is of shape: (None, 64) and C is of shape (None, 64). What I wanted to do is to have an element-wise multiplication followed by an element-wise addition.

Thanks to TF broadcasting, the code I needed to write is simply:

A * B + C

With this, the output should have shape  (None, 64, 64). All these things are a part of my model, and everything works well. Specifically, by working well I mean I can compile the model and print model summary() successfully.

Unfortunately, when I fit the the model to my training data, I got a problem of Incompatible shapes as bellows.

```

  File "/home/cuong.hoang/anaconda2/envs/py36_env_tensor_gpu_pip_local/lib/python3.6/site-packages/tensorflow/python/keras/engine/training.py", line 780, in fit
    steps_name='steps_per_epoch')
  File "/home/cuong.hoang/anaconda2/envs/py36_env_tensor_gpu_pip_local/lib/python3.6/site-packages/tensorflow/python/keras/engine/training_arrays.py", line 363, in model_iteration
    batch_outs = f(ins_batch)
  File "/home/cuong.hoang/anaconda2/envs/py36_env_tensor_gpu_pip_local/lib/python3.6/site-packages/tensorflow/python/keras/backend.py", line 3292, in __call__
    run_metadata=self.run_metadata)
  File "/home/cuong.hoang/anaconda2/envs/py36_env_tensor_gpu_pip_local/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1458, in __call__
    run_metadata_ptr)
tensorflow.python.framework.errors_impl.InvalidArgumentError: 2 root error(s) found.
  (0) Invalid argument: Incompatible shapes: [32,64] vs. [32,64,64]
	 [[{{node encoder_layer/mul_5}}]]
	 [[loss/mul/_5175]]
  (1) Invalid argument: Incompatible shapes: [32,64] vs. [32,64,64]
	 [[{{node encoder_layer/mul_5}}]]
0 successful operations.
0 derived errors ignored.
```

I am pretty sure my code correct, and the problem, I think is because of broadcasting. Moving forward, I decided to write by myself the code to make B and C has size (None, 64, 64) by repeating. The code is pretty simple, for B, as example:
```
B = K.expand_dims(B, axis=-1)
B = K.repeat_elements(B, 64, axis=2)
```

With this, the model compiles OK, and more importantly, when I fit the model to data, it runs OK as well.

So, I believe this is a bug of TensorFlow broadcasting. I am curious why it happens and did anyone get any similar error before?

This is with Tensorflow 1.14. If you want the code to reproduce the error just let me know.

**Comment by ravikyram** [comment]
@hoangcuong2011 

Can you please help us with the code to reproduce the issue in our environment. It helps us in localizing the issue faster.Thanks!

**Comment by hoangcuong2011** [comment]
@ravikyram: Thx. Below is the simplest code to reproduce the error. I removed C and kept only A and B with shape as follows:
```

A Tensor("MatMul:0", shape=(?, 64, 64), dtype=float32)
B Tensor("Cast:0", shape=(?, 64), dtype=float32)
```
Then:
`A * B Tensor("mul:0", shape=(?, 64, 64), dtype=float32)`

But when I fit the model, I got this:
```
Traceback (most recent call last):
  File "/Users/hoangcuong2011/Desktop/translation/error.py", line 33, in <module>
    main()
  File "/Users/hoangcuong2011/Desktop/translation/error.py", line 29, in main
    model.fit(dataset, dataset, epochs=200)
  File "/Users/hoangcuong2011/anaconda3/envs/py36_good_env/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training.py", line 727, in fit
    use_multiprocessing=use_multiprocessing)
  File "/Users/hoangcuong2011/anaconda3/envs/py36_good_env/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training_arrays.py", line 675, in fit
    steps_name='steps_per_epoch')
  File "/Users/hoangcuong2011/anaconda3/envs/py36_good_env/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training_arrays.py", line 394, in model_iteration
    batch_outs = f(ins_batch)
  File "/Users/hoangcuong2011/anaconda3/envs/py36_good_env/lib/python3.6/site-packages/tensorflow_core/python/keras/backend.py", line 3476, in __call__
    run_metadata=self.run_metadata)
  File "/Users/hoangcuong2011/anaconda3/envs/py36_good_env/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1472, in __call__
    run_metadata_ptr)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Incompatible shapes: [32,64,64] vs. [32,64]
	 [[{{node training/Adam/gradients/gradients/mul_grad/BroadcastGradientArgs}}]]
```



Full code to reproduce the error:

```
import tensorflow as tf
import numpy as np

def main(max_seq_length=64):
    def create_model():
        sequence = tf.keras.layers.Input(dtype='int32', shape=(max_seq_length,))
        embedding_layer \
            = tf.keras.layers.Embedding(100, 512, input_length=max_seq_length)
        embedding = embedding_layer(sequence)
        embedding_reverse = tf.keras.backend.permute_dimensions(embedding, pattern=(0, 2, 1))
        A = tf.keras.backend.batch_dot(embedding, embedding_reverse)
        print("A", A)
        B = tf.dtypes.cast(tf.keras.backend.not_equal(0, sequence), dtype='float32')
        print("B", B)
        A = A * B
        print("new A", A)
        output = tf.keras.activations.softmax(A, axis=-1)
        model = tf.keras.models.Model(inputs=[sequence], outputs=output)
        model.compile(
            tf.keras.optimizers.Adam(),
            loss=tf.keras.losses.sparse_categorical_crossentropy)
        return model

    model = create_model()
    print(model.summary())

    dataset = np.random.randint(10, size=(100, max_seq_length))
    
    model.fit(dataset, dataset, epochs=200)


if __name__ == '__main__':
    main()
```

**Comment by ravikyram** [comment]
I have tried on colab with TF version 1.14, 1.15 and was able to reproduce the issue.

I tried with TF version 2.0, 2.1.0-rc0 and i am seeing below error message.
```
InvalidArgumentError:  Incompatible shapes: [32,64,64] vs. [32,64]
	 [[node BroadcastGradientArgs_4 (defined at <ipython-input-3-ad43ee668564>:28) ]] [Op:__inference_distributed_function_743]
```
Please, find the gist [here](https://colab.sandbox.google.com/gist/ravikyram/02d8fdddb062c6118d3c2409834d320e/untitled465.ipynb). Thanks!

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.

**Comment by tomoleary** [comment]
Did anyone find workarounds for this issue?
