### ISSUE TITLE
Train time per sample grows with dataset tensor size, even though it is always cropped to the same size

### ISSUE THREAD

**Issue by feature-engineer** [tensorflow/tensorflow#34936]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.0
- Python version: 3.7.5
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 
- GPU model and memory:

**Describe the current behavior**
When using `dataset.from_tensor_slices` on a tensor with shape (1, 10000, 1000) then `.map(tf.image.random_crop((20, 20)))`, training is 100 times faster par one iteration than when using  `dataset.from_tensor_slices` on a tensor with shape (1, 100000, 10000)

**Describe the expected behavior**
I expect that as long as the tensor can be kept in RAM, its size would not affect performance (putting aside tensors small enough to be kept in CPU cache)

**Code to reproduce the issue**

This is the simplest form of data and model that reproduces this.. not very interesting, but I really can't see any reason why this would be so much slower when the ones and zeros are bigger.

```python
ones = tf.ones((1, 10000, 1000))
zeros = tf.zeros((1, 10000, 1000))
data = tf.data.Dataset.from_tensor_slices(
    (
        ones,
        tf.ones((1, 1))
    )
).concatenate(
    tf.data.Dataset.from_tensor_slices(
        (
            zeros,
            tf.zeros((1, 1))
        )
    )
).map(lambda x, y: (tf.image.random_crop(x, (20, 20)), y)).repeat().batch(10)

x = tf.keras.layers.Input((20, 20))
y = tf.keras.layers.Dense(1, tf.keras.activations.sigmoid)(x)
model = tf.keras.models.Model(inputs=[x], outputs=[y])
model.compile(loss='mean_squared_error', optimizer='ADAM')
model.fit(x=data, epochs=100, steps_per_epoch=100, validation_data=validation, validation_steps=3)
```

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by oanush** [comment]
Tried running the code in colab, did not see any performance issue. kindly find the [gist](https://colab.sandbox.google.com/gist/oanush/93f113270cda46e525b36721366afa79/34936.ipynb) of colab.Thanks!

**Comment by feature-engineer** [comment]
@oanush Did you try changing the size of ones and zeros? It drastically affects the training time..

I have added another cell to your gist, the only difference being, zeros and one in the first cell have 100 times more values. Since we randomly crop them before processing them in our network, the original size should not affect performance. But try comparing the training performance of these two cells, and you'll find that one take 100 times more time to train.

**Comment by feature-engineer** [comment]
The problem seems to stem from dataset's map method, not from the random_crop... I've added a timeit on the random_crop, and changing the input size of that function has no repercussions, as expected.

So it would seem that the the map method is the inefficient link here.

**Comment by feature-engineer** [comment]
I have opened a new issue, since this one's title, as well as example code distracts from the root cause:  see [issue #35135](https://github.com/tensorflow/tensorflow/issues/35135)

**Comment by feature-engineer** [comment]
The issue was due to the use of `from_tensor_slices`, which apparently means the tensors passed as arguments to `from_tensor_slices` are being copied on each iteration over the dataset. 

Replacing `from_tensor_slices` with `from_tensors` fixed the performance issue.
