### ISSUE TITLE
SymbolicException: Inputs to eager execution function cannot be Keras symbolic tensors, but found [<tf.Tensor 'keras_learning_phase:0' shape=() dtype=bool>]

### ISSUE THREAD

**Issue by UdiBhaskar** [tensorflow/tensorflow#34944]
Hi,
 I am writing Encoder-Decoder architecture with Bahdanau Attention using tf.keras with TensorFlow 2.0. Below is my code This is working with TensorFlow 1.15 but getting the error in 2.0. you can check the code in colab notebook [here](https://colab.research.google.com/drive/12Vq1t9xOtrPmXV2Sj_GSoE9bxH7FgaKs). 
```
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from tensorflow.keras.layers import Input, Dense, Conv2D, BatchNormalization, Activation, Dropout, GRU, Embedding
from tensorflow.keras.models import Model
from tensorflow.keras import activations
from tensorflow.keras.layers import Layer
from tensorflow.keras import layers
import tensorflow as tf
from tensorflow.keras.layers import GRU, concatenate, Lambda

ENCODER_SEQ_LEN = 30
DECODER_SEQ_LEN = 20
VOCAB_SIZE = 500
units = 16

tf.keras.backend.clear_session()
class Encoder(Model):
    def __init__(self, vocab_size, embedding_dim, input_length, units):
        super(Encoder, self).__init__()
        self.vocab_size = vocab_size
        self.embedding_dim = embedding_dim
        self.input_length = input_length
        self.units = units
        self.embedding = Embedding(input_dim=VOCAB_SIZE, output_dim=50, input_length=self.input_length,
                           mask_zero=False, name="embedding_layer_encoder")
        self.gru = GRU(self.units, return_state=True, return_sequences=True, name="Encoder_GRU")
    @tf.function
    def call(self, inputs, training=True):
        x_embedd = self.embedding(inputs)
        gru_output, gru_state = self.gru(x_embedd)
        return gru_output, gru_state
    
class BahdanauAttention(tf.keras.layers.Layer):
    def __init__(self, units):
        super(BahdanauAttention, self).__init__()
        self.W1 = tf.keras.layers.Dense(units)
        self.W2 = tf.keras.layers.Dense(units)
        self.V = tf.keras.layers.Dense(1)

    def call(self, query, values):
        # hidden shape == (batch_size, hidden size)
        # # hidden_with_time_axis shape == (batch_size, 1, hidden size)
        # # we are doing this to perform addition to calculate the score
        hidden_with_time_axis = tf.expand_dims(query, 1)
        # score shape == (batch_size, max_length, 1)
        # # we get 1 at the last axis because we are applying score to self.V
        # # the shape of the tensor before applying self.V is (batch_size, max_length, units)
        score = self.V(tf.nn.tanh(self.W1(values) + self.W2(hidden_with_time_axis)))
        # attention_weights shape == (batch_size, max_length, 1)
        attention_weights = tf.nn.softmax(score, axis=1)
        # context_vector shape after sum == (batch_size, hidden_size)
        context_vector = attention_weights * values
        context_vector = tf.reduce_sum(context_vector, axis=1)
        return context_vector

class onestepDecoder(Model):
    def __init__(self, vocab_size, embedding_dim, dec_units, att_units):
        super(onestepDecoder, self).__init__()
        self.vocab_size = vocab_size
        self.embedding_dim = embedding_dim
        self.dec_units = dec_units
        self.att_units = att_units
        self.embedd = Embedding(input_dim=self.vocab_size, output_dim=self.embedding_dim,
                      input_length=1, mask_zero=False, name="Decoder_Embedding_layer")
        self.att_layer = BahdanauAttention(units=self.att_units) #name='Attention')
        self.dense = Dense(self.vocab_size, activation="softmax", name="DenseOut")
        self.gru = GRU(units=self.dec_units, return_state=True, name="DecGRU")
    @tf.function
    def call(self, input_decoder, input_state, encoder_outputs, training=True):
        x_embedd = self.embedd(input_decoder)
        context_vector = self.att_layer(input_state, encoder_outputs )
        concat = tf.concat([tf.expand_dims(context_vector, 1), x_embedd], axis=-1)
        decoder_output, Decoder_state = self.gru(concat, initial_state=input_state)
        output = self.dense(decoder_output)
        return (output, Decoder_state)
class Decoder(Model):
    def __init__(self, vocab_size, embedding_dim, dec_units, att_units):
        super(Decoder, self).__init__()
        self.vocab_size = vocab_size
        self.embedding_dim = embedding_dim
        self.dec_units = dec_units
        self.att_units = att_units
        self.stepdec = onestepDecoder(self.vocab_size, self.embedding_dim, self.dec_units, self.att_units)
    @tf.function
    def call(self, input_decoder, input_state, encoder_outputs):
        all_outputs= tf.TensorArray(tf.float32, size=input_decoder.shape[1], name="output_arrays")
        for timestep in range(input_decoder.shape[1]):
            output, input_state = self.stepdec(input_decoder[:,timestep:timestep+1], input_state, encoder_outputs)
            all_outputs = all_outputs.write(timestep, output)
        all_outputs = tf.transpose(all_outputs.stack(), [1, 0, 2])
        return all_outputs

encoder_input = Input(shape=(ENCODER_SEQ_LEN,), name='encoder_input_final')
decoder_input = Input(shape=(DECODER_SEQ_LEN,), name="Decoder_inout_final")
encoder = Encoder(vocab_size=VOCAB_SIZE, embedding_dim=50, input_length=ENCODER_SEQ_LEN, units=16)
x_gru_out, x_gru_state = encoder(encoder_input)
decoder = Decoder(vocab_size=VOCAB_SIZE, embedding_dim=50, dec_units=16, att_units=20)
all_outputs = decoder(decoder_input, x_gru_state, x_gru_out)
encoder_decoder = Model([encoder_input, decoder_input], outputs=all_outputs)
encoder_decoder.compile(optimizer='adam',loss='sparse_categorical_crossentropy')

x = np.random.randint(0, 499, size=(2000, ENCODER_SEQ_LEN))
y = np.random.randint(0, 499, size=(2000, DECODER_SEQ_LEN))

encoder_decoder.fit(x=[x,y], y=y, epochs=1,verbose=1,batch_size=32)
```
**Error**:
TypeError                                 Traceback (most recent call last)
/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/eager/execute.py in quick_execute(op_name, num_outputs, inputs, attrs, ctx, name)
     60                                                op_name, inputs, attrs,
---> 61                                                num_outputs)
     62   except core._NotOkStatusException as e:

TypeError: An op outside of the function building code is being passed
a "Graph" tensor. It is possible to have Graph tensors
leak out of the function building context by including a
tf.init_scope in your function building code.
For example, the following function will fail:
  @tf.function
  def has_init_scope():
    my_constant = tf.constant(1.)
    with tf.init_scope():
      added = my_constant * 2
The graph tensor has name: keras_learning_phase:0

During handling of the above exception, another exception occurred:

_SymbolicException                        Traceback (most recent call last)
11 frames
/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/eager/execute.py in quick_execute(op_name, num_outputs, inputs, attrs, ctx, name)
     73       raise core._SymbolicException(
     74           "Inputs to eager execution function cannot be Keras symbolic "
---> 75           "tensors, but found {}".format(keras_symbolic_tensors))
     76     raise e
     77   # pylint: enable=protected-access

_SymbolicException: Inputs to eager execution function cannot be Keras symbolic tensors, but found [<tf.Tensor 'keras_learning_phase:0' shape=() dtype=bool>]

**Comment by Athul8raj** [comment]
Error is self-explainatory. If running under eager mode ,tensorflow op will check if the inputs are of type "_tensorflow.python.framework.ops.EagerTensor_" and keras ops are implemented as DAGs. So the inputs to the eagermode will be of "_tensorflow.python.framework.ops.Tensor_" and this throws the error

You can change the input type to EagerTensor by explicity telling tensorflow to run in eager mode for keras. 
"_tf.config.experimental_run_functions_eagerly(True)_" 

Adding this statement should solve your issue. Although note that there will be significant performance hits since you are running now in eager mode and recommended only for debugging,profiling etc.

**Comment by UdiBhaskar** [comment]
can we change any code to work without "tf.config.experimental_run_functions_eagerly(True)" ? @Athul8raj

**Comment by Athul8raj** [comment]
For the first part of your question, yes it is possible to run in Eagermode without that statement, but instead of the fit function from keras you have to calculate gradients with the help of a gradient tape which will take care of loss gradient and track all the trainable variables

For the second part, I am not sure why you are getting the error, because I am not facing that .
Can you specify the TF version you are running and also the OS Specs.
Actually you should include these details in the subject of this issue. That should be the way tensorflow issues should be raised

The template shown below: 

"_System information_

_Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No_
_OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10 Home_
_Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:_
_TensorFlow installed from (source or binary): binary_
_TensorFlow version (use command below): v1.12.0-9492-g2c319fb415 2.0.0-alpha0_
_Python version: 3.6.8 |Anaconda, Inc.| (default, Feb 21 2019, 18:30:04) [MSC v.1916 64 bit (AMD64)]_
_Bazel version (if compiling from source): NA_
_GCC/Compiler version (if compiling from source): NA_
_CUDA/cuDNN version: NA_
_GPU model and memory: NA_
_You can collect some of this information using our environment capture_
_script_
_You can also obtain the TensorFlow version with: 1. TF 1.0: python -c "import tensorflow as tf_ _print(tf.GIT_VERSION, tf.VERSION)" 2. TF 2.0: python -c "import tensorflow as tf_ _print(tf.version.GIT_VERSION, tf.version.VERSION)"_

_Describe the current behavior_
_The code snippets works fine on Colab but gives the following error on Windows:_"

**Comment by UdiBhaskar** [comment]
Below is my system information. 
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10 Home
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: NA
- TensorFlow installed from (source or binary): Binary
- TensorFlow version (use command below): v2.0.0-rc2-26-g64c3d382ca 2.0.0
- Python version: Python 3.7.3
- Bazel version (if compiling from source): NA
- GCC/Compiler version (if compiling from source): NA
- CUDA/cuDNN version: CUDA toolkit 10.0.130
- GPU model and memory: GTX 1050 Ti

Describe the current behavior
The above code snippet with/without @tf.function is not working in colab as well. I am getting the same error.

**Comment by Athul8raj** [comment]
Can you provide a collab gist?.

**Comment by UdiBhaskar** [comment]
below are the two links, please check
[error code without tf.function](https://gist.github.com/UdiBhaskar/d7492b7be034db1480db717ceb6e767e). 
[Error code with tf.function](https://gist.github.com/UdiBhaskar/613e671d8785538b1380a7f3909899ed)

**Comment by Athul8raj** [comment]
If you are not providing "_tf.config.experimental_run_functions_eagerly(True)_". then you have to give the model to gradient tape as shown in here

https://www.tensorflow.org/tutorials/text/nmt_with_attention

**Comment by UdiBhaskar** [comment]
I saw documentation for tf.config.experimental_run_functions_eagerly(True) and it was saying useful while debugging and read the functional API specs and in that it was saying that, if a model built by a functional API is compiled without any error, you can use that model to train and this won't give any error. 
i understand if i am writing the code with tf.functions, i have to give eager tensor as input not keras but if am removing the tf.function, it has to work right? it is working fine with 1.15 version and in above comment you told, it is working on your system with 2.0 alpha. is there any bug in auto graph with keras .fit?

**Comment by Athul8raj** [comment]
As per TF 2.0 docs,there are two ways to create models, one is through object oriented way and one is using the keras functional api. While there are examples where they have called layer subclass in a keras functional model, there are no instances of models subclasses being called in a keras functional api. This may be the reason you are encountering the issue.

One way to go, if you want to stick with the functional api would be to change the model subclasses to layer subclasses and write a single model function. 
For more info please refer : https://www.tensorflow.org/guide/keras/custom_layers_and_models#the_model_class

PS: please forgive my assertion in the previous reply. I didnt mean you have to, its just another way of doing it

**Comment by UdiBhaskar** [comment]
@Athul8raj I checked with the above cases as well and getting the same error. I am not getting any error if i am using a 1.15 version or below. 

case-1 : Total model subclassing API  - Got same error. you can check [here](https://gist.github.com/UdiBhaskar/8f96a48dbe3afe9b969b4d46e835a93b)
case-2 : Custom layers(not model subclassing) and functional API - Got same error. You can check [here](https://gist.github.com/UdiBhaskar/e795757f6b07f70275ab37739d07e411)
case-3 : Custom layers and model subclassing API - Got same error. You can check [here](https://gist.github.com/UdiBhaskar/000af58031c6b95c046a8365df466ed9)

**Comment by Athul8raj** [comment]
You are not getting error in TF 1.15 and below because in tf 2.0 eager execution is enabled by default.

So I thought of disabling the eager execution and your code worked perfectly.
this is the statement to disable eager execution "_tf.compat.v1.disable_eager_execution()_"
Here are the docs : https://www.tensorflow.org/api_docs/python/tf/compat/v1/disable_eager_execution

Here is the example code with gradient tape and eager execution : https://www.tensorflow.org/tutorials/text/nmt_with_attention

**Comment by UdiBhaskar** [comment]
I got that if I disable my eager execution, I can run my model without error or if I use gradient tape then also I can run the model without error.  but I will get the error if I use .fit method with my Keras model but it has to work even in TensorFlow 2.0 right. do you think of any bug in .fit method with the autograph in 2.0 with eager execution?

**Comment by Athul8raj** [comment]
I don't believe it is a bug rather TF gives us freedom in choosing each method. While we can mix match the layer with keras functional api, I guess we can't make the model subclass work with the Model api of keras. This is where, in my opinion the distinction between eager execution and keras graph mode comes into conflict giving rise to this "_SymbolicException_". 
Making TF aware beforehand what mode it should execute solves it.

**Comment by Douboo** [comment]
> I got that if I disable my eager execution, I can run my model without error or if I use gradient tape then also I can run the model without error. but I will get the error if I use .fit method with my Keras model but it has to work even in TensorFlow 2.0 right. do you think of any bug in .fit method with the autograph in 2.0 with eager execution?

hey~ I encountered the same problem. Inspired by [your code](https://gist.github.com/UdiBhaskar/e795757f6b07f70275ab37739d07e411) I run the `.fit` method with the autograph in tf2.0 with eager execution successfully. You can check the [code](https://github.com/Douboo/tf_env_debug/blob/master/custom_layers_and_model_subclassing_API.ipynb)

**Comment by ymodak** [comment]
Closing this issue since its resolved. Thanks!

**Comment by tanjhysj0** [comment]
how?

**Comment by chansonzhang** [comment]
> Error is self-explainatory. If running under eager mode ,tensorflow op will check if the inputs are of type "_tensorflow.python.framework.ops.EagerTensor_" and keras ops are implemented as DAGs. So the inputs to the eagermode will be of "_tensorflow.python.framework.ops.Tensor_" and this throws the error
> 
> You can change the input type to EagerTensor by explicity telling tensorflow to run in eager mode for keras.
> "_tf.config.experimental_run_functions_eagerly(True)_"
> 
> Adding this statement should solve your issue. Although note that there will be significant performance hits since you are running now in eager mode and recommended only for debugging,profiling etc.

solved my problem, thanks

**Comment by sowmyamanojna** [comment]
In order to evade the performance degradation when setting eager execution to True, you could run the code on colab with 
```python
%tensorflow_version 1.x
```
