### ISSUE TITLE
Does TensorFlow 2.x still need the bazel build option of --cxxopt="-D_GLIBCXX_USE_CXX11_ABI=0" ?

### ISSUE THREAD

**Issue by shizukanaskytree** [tensorflow/tensorflow#34946]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 16.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: No.
- TensorFlow installed from (source or binary): source
- TensorFlow version:  v2.1.0-rc0 
- Python version: 3.6
- Installed using virtualenv? pip? conda?: conda
- Bazel version (if compiling from source): bazel 1.2.1
- GCC/Compiler version (if compiling from source): gcc (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609
- CUDA/cuDNN version: CUDA 10.0 / cuDNN 7
- GPU model and memory: 1080Ti, ~11GB

**Describe the problem**

According to the official doc in section **TensorFlow 2.x** from https://www.tensorflow.org/install/source#tensorflow_2x, to build the TF 2.X via bazel 

```
bazel build //tensorflow/tools/pip_package:build_pip_package
```
Do we need the bazel option of --cxxopt="-D_GLIBCXX_USE_CXX11_ABI=0" ?

The [subsection: Bazel build options](https://www.tensorflow.org/install/source#bazel_build_options) under section **TensorFlow 1.x** states that 

> The official TensorFlow packages are built with GCC 4 and use the older ABI. For GCC 5 and later, make your build compatible with the older ABI using: --cxxopt="-D_GLIBCXX_USE_CXX11_ABI=0". ABI compatibility ensures that custom ops built against the official TensorFlow package continue to work with the GCC 5 built package.

However,  `The official TensorFlow packages ` link includes TF 2.X. 
So, does TensorFlow 2.x still need the bazel option of --cxxopt="-D_GLIBCXX_USE_CXX11_ABI=0" ?

**Provide the exact sequence of commands / steps that you executed before running into the problem**

> The official TensorFlow packages are built with GCC 4 and use the older ABI. For GCC 5 and later, make your build compatible with the older ABI using: --cxxopt="-D_GLIBCXX_USE_CXX11_ABI=0". ABI compatibility ensures that custom ops built against the official TensorFlow package continue to work with the GCC 5 built package.

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by simonmaurer** [comment]
any updates on this?

**Comment by bplevin36** [comment]
I have this question as well.  As it is now, attempting to use the C libs (libtensorflow.so) alongside anything that uses custom ops (like tensorflow-text) is extremely unpleasant due to ABI issues.  Further documentation on this would be very helpful.

**Comment by kevint324** [comment]
updates?

**Comment by Saduf2019** [comment]
@shizukanaskytree 
Could you please try on latest stable version of tf and let us know if this is still an issue.Thanks!

**Comment by kevint324** [comment]
Could you please post the related commit? What's changed? The default ABI or documentation?

**Comment by sspintel** [comment]
@Saduf2019 I don't think the recent official TensorFlow packages, including 2.7 or 2.8 have moved away from GCC 4 and the older ABI. They still seem to be using --cxxopt="-D_GLIBCXX_USE_CXX11_ABI=0" for the PyPi packages as well.

The issue questions if the older ABI (i.e --cxxopt="-D_GLIBCXX_USE_CXX11_ABI=0") is still needed for the latest versions of TensorFlow. Is it being maintained so for any particular reason?

For example, this dockerfile still uses manylinux2010 which has the older toolchain with GLIC 2.12, and libstdc++ 4.4

**Comment by bhack** [comment]
> For example, this dockerfile still uses manylinux2010 which has the older toolchain with GLIC 2.12, and libstdc++ 4.4
Dockerfile for nightly wheels is now:
https://discuss.tensorflow.org/t/adopting-open-source-dockerfiles-for-official-tf-nightly-ci/6050/24

**Comment by sspintel** [comment]
@bhack Thanks for sharing this resource. Do you know if there are plans to switch to a newer manylinux tag and toolset for the official PyPi builds? Something that preferably uses the newer ABI (i.e, one that uses --cxxopt="-D_GLIBCXX_USE_CXX11_ABI=1")?

**Comment by bhack** [comment]
There is a WIP PR for manylinux2014:

https://github.com/tensorflow/build/pull/57

**Comment by guizili0** [comment]
@bhack did the PR you share would change the ABI value(from 0 to 1) in the compile stage? thanks.

**Comment by bhack** [comment]
You can try to ask there directly in the PR

**Comment by nitins17** [comment]
Hello everyone,
With the release of 2.9, TensorFlow has switched over to the new libstdcxx ABI as part of the manylinux2014 upgrade. Please see the [release notes](https://github.com/tensorflow/tensorflow/releases/tag/v2.9.0) and the [community forum thread](https://discuss.tensorflow.org/t/tensorflow-linux-wheels-are-being-upgraded-to-manylinux2014/8339) for more information. Thanks!

**Comment by sspintel** [comment]
Thank you so much for the resolution of this issue. One of the biggest upgrades in TF that solves a lot of build and packaging issues. 😍
