### ISSUE TITLE
tensorflow1.14.0 correspond protobuf version？

### ISSUE THREAD

**Issue by zxgm** [tensorflow/tensorflow#34952]
ImportError: /usr/local/lib/python3.6/dist-packages/tensorflow/python/_pywrap_tensorflow_internal.so: undefined symbol: _ZN6google8protobuf8internal26fixed_address_empty_stringE

I think the problem is caused by incompatible versions？So i need protobuf version that conrrespond tensorflow1.14.0

**Comment by ravikyram** [comment]
@zxgm 

Which protobuf version you are using?.Request you to check using `$ pip show protobuf` . Request you to uninstall by using `pip uninstall protobuf` and try installing  `pip install protobuf==3.8 ` and see how it progresses. Thanks!

**Comment by zxgm** [comment]
Thanks a lot! I sovled the problem.

**Comment by ravikyram** [comment]
@zxgm 

Closing the issue since its resolved. Thanks!
