### ISSUE TITLE
Keras MobilenetV3 weights 

### ISSUE THREAD

**Issue by SanthoshRajendiran** [tensorflow/tensorflow#34954]
**System information**
- TensorFlow version (you are using): 2.0
- Are you willing to contribute it (Yes/No): Yes

**Describe the feature and the current behavior/state.**
Tensorflow MobilenetV3 code and checkpoints(.ckpt, .pb, .tflite) have been provided. What changes need to be incorporated to use the model, in Keras. As of now, Keras supports applications till MobilenetV2, and not MobilenetV3. If provided, it will be easier for model loading and usage as it is. 

**Will this change the current api? How?**
No. It will be an update to the current scenario.

**Who will benefit with this feature?**
Users of Tensorflow and Keras

**Any Other info.**
NIL

**Comment by SanthoshRajendiran** [comment]
Any updates on this request!! @fchollet ??

**Comment by edurenye** [comment]
MobileNetV3 was added to keras-applications: https://github.com/keras-team/keras-applications/pull/176

**Comment by ymodak** [comment]
Closing this issue since it's resolved. Thanks!

> MobileNetV3 was added to keras-applications: [keras-team/keras-applications#176](https://github.com/keras-team/keras-applications/pull/176)

**Comment by edurenye** [comment]
Was added to keras-applications, but not to keras-applications inside TensorFlow, so do not close it, please.

**Comment by ymodak** [comment]
This feature is now available with TF 2.4.1
See https://www.tensorflow.org/api_docs/python/tf/keras/applications/MobileNetV3Small?hl=zh-cn and
https://www.tensorflow.org/api_docs/python/tf/keras/applications/MobileNetV3Large?hl=zh-cn

**Comment by edurenye** [comment]
Then this can be closed now

**Comment by bhack** [comment]
Can we close this?
