### ISSUE TITLE
RunMetaData

### ISSUE THREAD

**Issue by luzm3** [tensorflow/tensorflow#34956]
Hello!
I want to know how to use tf.RunMetaData() in tf.contrib.tpu.TPUEstimator(), because I want to analyze the time in ops.
Thank you!

**Comment by jvishnuvardhan** [comment]
This is not Build/Installation or Bug/Performance issue. Please post this kind of support questions at [Stackoverflow](https://stackoverflow.com/questions/tagged/tensorflow). There is a big community to support and learn from your questions. GitHub is mainly for addressing bugs in installation and performance. Thanks!
