### ISSUE TITLE
A question about PSNR implementation in tensorflow 2.0

### ISSUE THREAD

**Issue by wukong4430** [tensorflow/tensorflow#34953]
This template is for miscellaneous issues not covered by the other issue categories.

For questions on how to work with TensorFlow, or support for problems that are not verified bugs in TensorFlow, please go to [StackOverflow](https://stackoverflow.com/questions/tagged/tensorflow).

If you are reporting a vulnerability, please use the [dedicated reporting process](https://github.com/tensorflow/tensorflow/blob/master/SECURITY.md).

For high-level discussions about TensorFlow, please post to discuss@tensorflow.org, for questions about the development or internal workings of TensorFlow, or if you would like to know how to contribute to TensorFlow, please post to developers@tensorflow.org.
  
I am working on some image processes using PSNR ( [tf.image.psnr](https://www.tensorflow.org/api_docs/python/tf/image/psnr)), but always I
got results larger than what I expected. Then I check the source code and I
find

```
psnr_val = math_ops.subtract(

20 * math_ops.log(max_val) / math_ops.log(10.0),

np.float32(10 / np.log(10)) * math_ops.log(mse),

name='psnr')
```

Compare to the standard PSNR algorithm, its formula as follows:

![image](https://user-images.githubusercontent.com/14346086/70408961-03814f00-1a85-11ea-8df2-8c0f470e86f0.png)

I wonder why there is np.log(10) in the tensorflow implementation rather
than np.log10(10)? Or is there anything I get wrong?

Thanks for any help.

**Comment by rafariva** [comment]
its the same...

![image](https://user-images.githubusercontent.com/26292862/72998480-e6ea6d80-3dcb-11ea-9ce9-184290c71b76.png)

**Comment by ccrusius** [comment]
I'll close this, as the comment above shows the equation is equivalent.
