### ISSUE TITLE
How to use SparseTensor in capi?

### ISSUE THREAD

**Issue by haolujun** [tensorflow/tensorflow#34957]
HI :
    How to use SparseTensor in capi?

**Comment by oanush** [comment]
@haolujun ,
Can you please refer this [link](https://www.tensorflow.org/api_docs/cc#sparse_ops) and let us know if it helped? Thanks!

**Comment by oanush** [comment]
@haolujun ,
Any update on the issue?Thanks!

**Comment by oanush** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
