### ISSUE TITLE
DepthwiseConv in lite/kernels/internal/reference/depthwiseconv_float.h can be optimized better

### ISSUE THREAD

**Issue by yurivict** [tensorflow/tensorflow#34955]
These two lines https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/kernels/internal/reference/depthwiseconv_float.h#L62 can be moved up, because they only depend on out_x/out_y, there's no need to compute them per input depth/depth_multiplier.

**Comment by daverim** [comment]
Hi @yurivict, thank you for your question. You are correct. The reference operations are designed for clarity rather than optimized for performance so that others can implement optimized implementations.

**Comment by yurivict** [comment]
> reference operations are designed for clarity

It's less clarity this way because lines are misplaced, producing the impression that they need to be recomputed per input_channel/multiplier when in reality they are not.

**Comment by daverim** [comment]
Sorry for the very very long wait. Short answer is that we want to keep the code in the innermost loop to make the code as simple to read as possible  -- compiler can handle simple optimizations like this in any case.
