### ISSUE TITLE
EfficientDet: Are you going to implement this in the object detection API?

### ISSUE THREAD

**Issue by TimoK93** [tensorflow/tensorflow#34961]
**System information**
- TensorFlow version (you are using): 2.0

**Describe the feature and the current behavior/state.**
I read about this new Network topology: [https://arxiv.org/pdf/1911.09070.pdf](https://arxiv.org/pdf/1911.09070.pdf ) 

It seems to work precisely and fast. Are you going to implement this new topology to your framework?

**Will this change the current api? How?**
Possible

**Who will benefit with this feature?**
Everyone who works with object detectors!

**Any Other info.**
If the answer is yes: will there be a quantized version for TPU inference?

Thanks in advance,
Timo

**Comment by dynamicwebpaige** [comment]
Linking a [community-built implementation of EfficientDet in TF 2.x](https://github.com/Guillem96/efficientdet-tf) in the interim. Thanks, @Guillem96!

**Comment by Guillem96** [comment]
@dynamicwebpaige I am still working with it. My intention is to override `train_step` method of my EfficientDet class, [just as tf 2.2.0 style](https://twitter.com/fchollet/status/1250622989541838848?s=19) , and get the `.fit` method extra features (TPUDistribute strategy, logging, callbacks,...) for free.

Thanks for linking my implementation here 😃

**Comment by jens25** [comment]
@TimoK93 
It's now available in the TensorFlow 2 Detection Model Zoo
https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/tf2_detection_zoo.md

**Comment by rmothukuru** [comment]
@TimoK93,
Sorry for the delayed response. **`EfficientDet`** is present in the [Model Zoo](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/tf2_detection_zoo.md) as well as in [Tensorflow.org](https://www.tensorflow.org/lite/tutorials/model_maker_object_detection#customize_the_efficientdet_model_hyperparameters).

Thanks!
