### ISSUE TITLE
Missing symbols from C++ API

### ISSUE THREAD

**Issue by kgizdov** [tensorflow/tensorflow#34980]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): stock example
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): ArchLinux x86_64
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: n/a
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below): 2.1.0-rc0
- Python version: 3.8
- Bazel version (if compiling from source): 1.2.0
- GCC/Compiler version (if compiling from source): 9.2
- CUDA/cuDNN version: 10.2.89/7.6.5.32
- GPU model and memory: NVidia GTX 980

**Describe the current behavior**
Trying to compile an example results in broken linking:
```c++
// basic.cpp
// tensorflow/cc/example/example.cc

#include "tensorflow/cc/client/client_session.h"
#include "tensorflow/cc/ops/standard_ops.h"
#include "tensorflow/core/framework/tensor.h"

int main() {
  namespace tf = tensorflow;
  namespace tfo = tensorflow::ops;
  tf::Scope root = tf::Scope::NewRootScope();
  // Matrix A = [3 2; -1 0]
  auto A = tfo::Const(root, { {3.f, 2.f}, {-1.f, 0.f} });
  // Vector b = [3 5]
  auto b = tfo::Const(root, { {3.f, 5.f} });
  // v = Ab^T
  auto v = tfo::MatMul(root.WithOpName("v"), A, b, tfo::MatMul::TransposeB(true));
  std::vector<tf::Tensor> outputs;
  tf::ClientSession session(root);
  // Run and fetch v
  TF_CHECK_OK(session.Run({v}, &outputs));
  // Expect outputs[0] == [19; -3]
  LOG(INFO) << outputs[0].matrix<float>();
  return 0;
}
```
trying to compile with `g++ basic.cpp -I/usr/include/tensorflow  -ltensorflow_cc -ltensorflow_framework  -o basic` fails:
```bash
make -C tensorflow/basic run
make[1]: Entering directory '/home/gizdov/Git/arch-package-tests/tensorflow/basic'
g++ basic.cpp -I/usr/include/tensorflow  -ltensorflow_cc -ltensorflow_framework  -o basic
/usr/bin/ld: /tmp/ccidGpWX.o: in function `main':
basic.cpp:(.text+0x363): undefined reference to `tensorflow::ClientSession::ClientSession(tensorflow::Scope const&)'
/usr/bin/ld: basic.cpp:(.text+0x3ea): undefined reference to `tensorflow::ClientSession::Run(std::vector<tensorflow::Output, std::allocator<tensorflow::Output> > const&, std::vector<tensorflow::Tensor, std::allocator<tensorflow::Tensor> >*) const'
/usr/bin/ld: basic.cpp:(.text+0x52b): undefined reference to `tensorflow::ClientSession::~ClientSession()'
/usr/bin/ld: basic.cpp:(.text+0x70d): undefined reference to `tensorflow::ClientSession::~ClientSession()'
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile:6: basic] Error 1
make[1]: Leaving directory '/home/gizdov/Git/arch-package-tests/tensorflow/basic'
make: *** [Makefile:11: tensorflow/basic] Error 2
```

**Describe the expected behavior**
Correct symbols should be exposed in `libtensorflow_cc.so` so that linking can work properly.

**Code to reproduce the issue**
source included above, `Makefile` provided below
```Makefile
CXX=g++
BINS=basic
INCL_DIR=$(shell pkg-config tensorflow_cc --cflags)
LIBS=$(shell pkg-config tensorflow_cc --libs)
$(BINS): $(BINS).cpp
	$(CXX) $< $(INCL_DIR) $(LIBS) -o $@
.PHONY: clean run
run: $(BINS)
	./$<
clean:
	rm -rf $(BINS)
```

**Other info / logs**
Provided are `nm` dumps with all available symbols that are exposed in `libtensorflow.so`, `libtensorflow_cc` and `libtensorflow_framework`:
[libtensorflow.so.2.1.0rc0-nm-symbol-dump.log](https://github.com/tensorflow/tensorflow/files/3942585/libtensorflow.so.2.1.0rc0-nm-symbol-dump.log)
[libtensorflow_cc.so.2.1.0rc0-nm-symbol-dump.log](https://github.com/tensorflow/tensorflow/files/3942586/libtensorflow_cc.so.2.1.0rc0-nm-symbol-dump.log)
[libtensorflow_framework.so.2.1.0rc0-nm-symbol-dump.log](https://github.com/tensorflow/tensorflow/files/3942587/libtensorflow_framework.so.2.1.0rc0-nm-symbol-dump.log)

**Comment by goldiegadde** [comment]
@kgizdov Can you please try with 2.1.0-rc1, we believe this [commit](https://github.com/tensorflow/tensorflow/commit/971a1881934f6878edaa5af753f29a0b300f04bb) to have fixed this issue.

**Comment by kgizdov** [comment]
indeed, that seems to have fixed it.
