### ISSUE TITLE
Can I train with keras float16 and convert it to tensorflow-lite float16 model

### ISSUE THREAD

**Issue by akkaze** [tensorflow/tensorflow#34982]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using):
- Are you willing to contribute it (Yes/No):

**Describe the feature and the current behavior/state.**

**Will this change the current api? How?**

**Who will benefit with this feature?**

**Any Other info.**

**Comment by terryheo** [comment]
TFLite converter supports FP16 quantization. https://www.tensorflow.org/lite/performance/post_training_quantization#float16_quantization_of_weights
In this case, you don't actually need to use float16 at training stage. You can train your model with float32 and covert it to tflite with fp16 quantization.

**Comment by akkaze** [comment]
there is lots of quantization in the model if I use tflite float16 quantization，these quantization may consume times，is there any way to remove them

**Comment by terryheo** [comment]
@akkaze some quantization techniques requires quant and dequant operations which are essential. But in our benchmark, those ops impact minimal to overall computation time.
