### ISSUE TITLE
Compilation issue on Example program of TF Lite

### ISSUE THREAD

**Issue by techguyzz** [tensorflow/tensorflow#34996]
**System information**
- OS Platform and Distribution : Linux Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:Desktop
- TensorFlow installed from (source or binary): Source https://github.com/tensorflow/tensorflow.git
- TensorFlow version: Release 1.15.0
- Python version:
- GCC/Compiler version (if compiling from source): gcc (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
- CUDA/cuDNN version:
- GPU model and memory:

**Describe the problem**
Default compilation of example folder (Hello World) leads to missing header file reference and shows error.

**Provide the exact sequence of commands / steps that you executed before running into the problem**

1. Install Ubuntu 18.04 OS
2. Download git using command "git clone https://github.com/tensorflow/tensorflow.git"
3. Install build essentials using command "sudo apt install build-essential"
4. Install curl library using command "sudo apt install curl"
5. Issue command "make -f tensorflow/lite/micro/tools/make/Makefile test_hello_world_test"

**Any other info / logs**
make -f tensorflow/lite/micro/tools/make/Makefile test_hello_world_test
g++ -O3 -DNDEBUG -std=c++11 -g -DTF_LITE_STATIC_MEMORY -fno-rtti -DTF_LITE_DISABLE_X86_NEON -I. -Itensorflow/lite/micro/tools/make/downloads/ -Itensorflow/lite/micro/tools/make/downloads/gemmlowp -Itensorflow/lite/micro/tools/make/downloads/flatbuffers/include -Itensorflow/lite/micro/tools/make/downloads/kissfft -c tensorflow/lite/micro/kernels/logical.cc -o tensorflow/lite/micro/tools/make/gen/linux_x86_64/obj/tensorflow/lite/micro/kernels/logical.o
In file included from ./tensorflow/lite/kernels/internal/reference/binary_function.h:18:0,
                 from tensorflow/lite/micro/kernels/logical.cc:16:
./tensorflow/lite/kernels/internal/common.h:24:10: fatal error: fixedpoint/fixedpoint.h: No such file or directory
 #include "fixedpoint/fixedpoint.h"
          ^~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
tensorflow/lite/micro/tools/make/Makefile:257: recipe for target 'tensorflow/lite/micro/tools/make/gen/linux_x86_64/obj/tensorflow/lite/micro/kernels/logical.o' failed
make: *** [tensorflow/lite/micro/tools/make/gen/linux_x86_64/obj/tensorflow/lite/micro/kernels/logical.o] Error 1

**Comment by njeffrie** [comment]
I've tried locally and am not seeing the same issue you see.  I'm wondering if one of the downloads may have failed for you.
Please try running
make -f tensorflow/lite/micro/tools/make/Makefile clean_downloads
make -f tensorflow/lite/micro/tools/make/Makefile clean
make -f tensorflow/lite/micro/tools/make/Makefile test_hello_world_test

**Comment by techguyzz** [comment]
Hi Nat,

Its working fine after Executing mentioned steps. I believe it should be download failure of Header file "tensorflow/lite/micro/tools/make/downloads/gemmlowp/fixedpoint/fixedpoint.h"
