### ISSUE TITLE
Placeholder names are inconsistent when re-entering a scope

### ISSUE THREAD

**Issue by holdenlee** [tensorflow/tensorflow#3499]
```
    with tf.Graph().as_default() as g:
        for name in ["a","b"]:
            with tf.variable_scope("fc"):
                x = tf.placeholder(tf.float32, shape=[1], name=name)
                print(x)
```
gives
```
Tensor("fc/a:0", shape=(1,), dtype=float32)
Tensor("fc_1/b:0", shape=(1,), dtype=float32)
```
The variable "b" unexpectedly has the name "fc_1/b:0" rather than "fc/b:0". This makes it difficult to refer to placeholders by name in my program.

**Comment by shekkizh** [comment]
with tf.Graph().as_default() as g:
        with tf.variable_scope("fc"):
			for name in ["a","b"]:
                x = tf.placeholder(tf.float32, shape=[1], name=name)
                print(x)
The variable scope should be defined outside the for loop, otherwise you are defining two variable scopes and since they are not marked to be reused tensorflow automatically appends the second one with "_1"

**Comment by holdenlee** [comment]
This only happens with placeholders, not with variables. For variables, entering the same scope twice results in variables being created in the same variable scope.

**Comment by Anthony-Tatowicz** [comment]
Well it would seem variable scope is just that variable scope not placeholder scope?

**Comment by michaelisard** [comment]
Does [name_scope](https://www.tensorflow.org/versions/r0.9/api_docs/python/framework.html#Graph.name_scope) do what you need?

([StackOverflow](https://stackoverflow.com/questions/tagged/tensorflow) is a better venue for this kind of question.)

**Comment by aselle** [comment]
Automatically closing due to lack of recent activity. Please reopen when you have additional information.

**Comment by holdenlee** [comment]
Exactly the same thing happens with `name_scope` instead of `variable_scope`.

**Comment by aselle** [comment]
Your comment about variables created is not true:
```python
import tensorflow as tf 

with tf.Session() as sess:
        for name in ["a","b"]:
            with tf.variable_scope("fc"):
                xx = tf.Variable([1,2], name=name+"v")
		print(xx.name)
                x = tf.placeholder(tf.float32, shape=[1], name=name)
                print(x)
```
yields
```
fc/av:0
Tensor("fc/a:0", shape=(1,), dtype=float32)
fc_1/bv:0
Tensor("fc_1/b:0", shape=(1,), dtype=float32)
```
name_scope on the outside is what you want. If you want to switch scopes and return to that scope you can (see documentation of name_scope). e.g. this does what you want...
```python
import tensorflow as tf

with tf.name_scope("fc") as scope:
   with tf.Session() as sess:
        for name in ["a","b"]:
            with tf.name_scope(scope):
                xx = tf.Variable([1,2], name=name+"v")
                print(xx.name)
                x = tf.placeholder(tf.float32, shape=[1], name=name)
                print(x)
```
(notice how we capture the scope on the outside)

**Comment by daeyun** [comment]
in case anyone else is wondering the same thing; `tf.name_scope(name + '/')` will force `name` to be re-used. `scope` is just `name + '/'`

**Comment by aselle** [comment]
Automatically closing due to lack of recent activity. Please reopen when further information becomes available.

**Comment by shun1024** [comment]
there is inconsistent between placeholder and variables. 

When add '/' to placeholder, it works. 

But the variables repeated '/' to '//' ....
