### ISSUE TITLE
Tensorboard: Can'r reach localhost:6006 after "fuser 6006/tcp -k"

### ISSUE THREAD

**Issue by Krutang** [tensorflow/tensorflow#34990]
Hi!

I just installed Tensorboard and everything worked fine. I noticed that the old loss-curves where kept in the plots and after reading online I took the suggestion to kill the process by:

fuser 6006/tcp -k

When I nor run Tensorboard and get:
Reusing TensorBoard on port 6006 (pid 48869), started 1:40:42 ago. (Use '!kill 48869' to kill it.)
Please visit http://localhost:6006 in a web browser.

The webpage cannot be reached (Unable to connect). I have probably screwed something up that a reboot did not solve... Can someone help me to un-screw myself?

Thanks!
btw, first post so sorry if the format is off!

**Comment by Krutang** [comment]
Please delete this, I didn't follow the new issue template and it does seem to work if don't run it via ipython.

If the problem persists I'll resubmit according to the template. 

Sorry!

**Comment by oanush** [comment]
@Krutang ,
Closing the issue as per your comment, please reopen the issue if it still persists.Thank you!
