### ISSUE TITLE
Classification of Forum for Microcontrollers Vs Android/other OS Apps

### ISSUE THREAD

**Issue by techguyzz** [tensorflow/tensorflow#34998]
Hi Experts,

I found the issues reported are mixed of platforms used like Desktop, Android, micontroller and other OS. Is there feature to classify it only based on micro-controller based APPS.

It will help better understand the types of problems and issues.

**Comment by ymodak** [comment]
@techguyzz You may use any of the templates to post a issue, make sure you provide all relevant information as much as you can. Once you post the issue we can label appropriately after interpreting the content. We can use label ```micro``` on GitHub for your case.
