### ISSUE TITLE
CPU Version install successfull,but import tensorflow error

### ISSUE THREAD

**Issue by caohaox** [tensorflow/tensorflow#350]
Python 2.7.3 (default, Jul 29 2015, 13:52:45) 
[GCC 3.4.5 20051201 (Red Hat 3.4.5-2)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/users/caohao/.jumbo/lib/python2.7/site-packages/tensorflow/__init__.py", line 4, in <module>
    from tensorflow.python import *
  File "/home/users/caohao/.jumbo/lib/python2.7/site-packages/tensorflow/python/__init__.py", line 22, in <module>
    from tensorflow.python.client.client_lib import *
  File "/home/users/caohao/.jumbo/lib/python2.7/site-packages/tensorflow/python/client/client_lib.py", line 35, in <module>
    from tensorflow.python.client.session import InteractiveSession
  File "/home/users/caohao/.jumbo/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 11, in <module>
    from tensorflow.python import pywrap_tensorflow as tf_session
  File "/home/users/caohao/.jumbo/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 28, in <module>
    _pywrap_tensorflow = swig_import_helper()
  File "/home/users/caohao/.jumbo/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow', fp, pathname, description)
ImportError: /home/users/caohao/.jumbo/lib/python2.7/site-packages/tensorflow/python/_pywrap_tensorflow.so: ELF file OS ABI invalid

**Comment by caohaox** [comment]
install pip from source；the error always exiting

**Comment by vrv** [comment]
What do you get from the output of `uname -a` ?

(We only support 64-bit platforms at the moment).

**Comment by caohaox** [comment]
uname -a output：
2.6.32_1-17-0-0 #1 SMP Mon Aug 24 11:14:27 CST 2015 x86_64 GNU/Linux

**Comment by vrv** [comment]
Do you know what version of glibc you have installed on your machine?  (I think `ldd --version` might tell you).

I think we require something later than 2.14 or 2.17...

**Comment by caohaox** [comment]
ldd --version
ldd () 2.18
Copyright (C) 2013 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Roland McGrath and Ulrich Drepper

**Comment by vrv** [comment]
Hmm :(.  All the info online suggests some kind of glibc version skew.  You might want to try the instructions to install from source in the meantime.

**Comment by victormas65** [comment]
Estimados,

Hay algun site o documentación donde pueda ver la funcionalidad de
TensorFlow, estoy iniciando mi conocimiento en esta herramienta. Me
gustaría conocer:
1.- su funcionalidad, para identificar su aplicación en mis proyectos.
2.- su instalación e implementación

Gracias,
V+


Un abrazo,
V+

2015-11-25 23:49 GMT-05:00 Vijay Vasudevan <notifications@github.com>:

**Comment by martinwicke** [comment]
Is this still an issue with the new release?

**Comment by hainm** [comment]
I just tried with version 0.7.0 for Red Hat 4.4.7-1.

`pip install --upgrade https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.7.0-py3-none-linux_x86_64.whl --no-deps`

Got similiar `ELF file OS ABI invalid` error. :(

**Comment by lvaleriu** [comment]
Python 3.3.2 (default, Aug 14 2014, 14:25:52)  _(tried with python 2.7, 3, etc)_
[GCC 4.8.2 20140120 (Red Hat 4.8.2-16)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named 'tensorflow'
>>>

**Comment by vrv** [comment]
Closing due to likely GLIBC issues.
