### ISSUE TITLE
Inconsistent loading of saved model

### ISSUE THREAD

**Issue by fonnesbeck** [tensorflow/tensorflow#35002]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Debian Linux
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.0.0
- Python version: 3.7.3

**Describe the current behavior**

I have several models saved using `model.save` as hdf5 objects. However, when I try to load them from a script via:

```python
tf.keras.models.load_model(DATA_DIR + "models/{}.h5".format(filename))
```

I get an I/O error:

```
"Unable to open object (file read failed: time = Tue Dec 10 16:36:14 2019\n, filename = '/home/fonnesbeck/models/Slider-rhb-rhp-attack.h5', file descriptor = 14, errno = 5, error message = 'Input/output error', buf = 0x7f642c733da0, total read size = 272, bytes this sub-read = 272, bytes actually read = 18446744073709551615, offset = 8443360)"
```

Yet, when I manually go in and import the file manually from the terminal, it works fine:

```
>>> import tensorflow as tf
>>> tf.keras.models.load_model('Slider-rhb-rhp-attack.h5')
2019-12-10 16:34:45.948071: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions tha
t this TensorFlow binary was not compiled to use: AVX2 FMA
2019-12-10 16:34:46.355657: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2300000000 Hz
2019-12-10 16:34:46.356406: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x557d96a7f470 executing 
computations on platform Host. Devices:
2019-12-10 16:34:46.356451: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): Host, De
fault Version
<tensorflow.python.keras.engine.sequential.Sequential object at 0x7fa474307400>
```

Even stranger, after having done the manual import, running the script works fine. this seems to happen with every new file.

**Comment by fonnesbeck** [comment]
I notice that if I use the SavedModel format rather than HDF5, this issue does not come up, however the model takes a lot longer to load and run, so I'd prefer to get HDF5 working.

**Comment by ymodak** [comment]
@fonnesbeck  You may try using TF 2.1.0.rc0 version for H5 model saving and loading.

**Comment by fonnesbeck** [comment]
I've tried this with 2.1.0.rc1, but now get the following:

```
OSError: SavedModel file does not exist at: ./models/my_model.h5/{saved_model.pbtxt|saved_model.pb}
```

Why is it now looking for a SavedModel when I've passed it a `h5` extension in the string? The documentation says it should recognize this.

**Comment by fonnesbeck** [comment]
OK, I noticed in the release notes that under 2.1 the model needs to be saved with a `save_format="h5"` argument.

I've gone ahead and done this; unfortunately, the same error comes up: a file read failure.

**Comment by fonnesbeck** [comment]
More info: this only seems to occur when the models are stored on a GCS bucket (which has been mounted using `gcsfuse`). If I move the models to a local directory, they open fine.

**Comment by k-w-w** [comment]
There are issues with using HDF5 with GCS. I'm not sure when we'll be able to get to this, but please use the workaround where the model is copied locally before loading.

**Comment by sushreebarsa** [comment]
@fonnesbeck We see that you are using older version of tensorflow .Many bug have been fixed in latest version. We recommend that you upgrade to latest stable version of tensorflow 2.6.0 and let us know if the issue still persists in newer versions .Thanks!
