### ISSUE TITLE
Attention/AdditiveAttention Issue

### ISSUE THREAD

**Issue by nectario** [tensorflow/tensorflow#35007]
I have the following functions to return two models:

```
def get_question_model(self, embedding):
        question_input = Input(shape=(None,), name='question_input')
        question_embedding = embedding(question_input)

        cnn_1d = Conv1D(128, 4, padding='same', activation='relu', strides=1)(question_embedding)
        cnn_1d = AveragePooling1D(pool_size=3)(cnn_1d)

        model = Model(question_input, cnn_1d)
        return model

def get_sentence_model(self, embedding, question_model):
        sentence_input = Input(shape=(None,),  name='sentence_input')
        sentence_embedding = embedding(sentence_input)
        cnn_1d = Conv1D(128, 4, padding="same", activation='relu', strides=1)(sentence_embedding)
        cnn_1d = AveragePooling1D(pool_size=3)(cnn_1d)

        sentence_attention = AdditiveAttention()([cnn_1d, question_model])
        model = Model(sentence_input, sentence_attention)
        model.shape = model.output_shape
        return model
```

And the functions are called:
```
   self.question_model = self.get_question_model(embedding)
   self.sentence_model = self.get_sentence_model(embedding, self.question_model)
```
#####

I get the following issue:

```
2019-12-10 18:17:01.848676: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1304] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 9371 MB memory) -> physical GPU (device: 0, name: TITAN V, pci bus id: 0000:83:00.0, compute capability: 7.0)
Traceback (most recent call last):
  File "D:/Development/competitions/Kaggle/Tensorflow 2.0 - Q_a_A/tensorflow_2.0/QuestionAnswerContextAttention.py", line 376, in <module>
    qa_model.fit(input=input, output=y)
  File "D:/Development/competitions/Kaggle/Tensorflow 2.0 - Q_a_A/tensorflow_2.0/QuestionAnswerContextAttention.py", line 152, in fit
    self.model = self.get_model()
  File "D:/Development/competitions/Kaggle/Tensorflow 2.0 - Q_a_A/tensorflow_2.0/QuestionAnswerContextAttention.py", line 123, in get_model
    self.sentence_model = self.get_sentence_model(embedding, self.question_model)
  File "D:/Development/competitions/Kaggle/Tensorflow 2.0 - Q_a_A/tensorflow_2.0/QuestionAnswerContextAttention.py", line 84, in get_sentence_model
    sentence_attention = AdditiveAttention()([cnn_1d, question_model])
  File "C:\Development\Python\Python37\lib\site-packages\tensorflow_core\python\keras\engine\base_layer.py", line 887, in __call__
    self._maybe_build(inputs)
  File "C:\Development\Python\Python37\lib\site-packages\tensorflow_core\python\keras\engine\base_layer.py", line 2141, in _maybe_build
    self.build(input_shapes)
  File "C:\Development\Python\Python37\lib\site-packages\tensorflow_core\python\keras\layers\dense_attention.py", line 406, in build
    v_shape = tensor_shape.TensorShape(input_shape[1])
**TypeError: 'NoneType' object is not subscriptable**
```

**Comment by ravikyram** [comment]
@nectario 

Looks like code is incomplete. Request you to provide complete code to reproduce the issue in our environment. It helps us in localizing the issue faster.Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version. Thanks!

**Comment by nectario** [comment]
Hi,

I have attached a zip file that contains the complete code with the data. Just unzip and run it as:

python QAModel.py

Also, for the information you requested:

**Version:** TensorFlow 2.0  (GPU Version)
**Operating System:** Windows 10
**Graphics Card:** Nvidia Titan V

[AttentionProblem.zip](https://github.com/tensorflow/tensorflow/files/3958469/AttentionProblem.zip)

Let me know if you need anything else.

Thanks,

Nektarios

**Comment by ravikyram** [comment]
I have tried on colab with TF version 2.0 and was able to reproduce the issue.Please, find the gist [here.](https://colab.sandbox.google.com/gist/ravikyram/2e0fe01fd916adcc8f011abf3ea2c2d2/untitled476.ipynb) Thanks!

**Comment by jvishnuvardhan** [comment]
@nectario I see the shapes of ```X.dat```and ```Y.dat``` are of ```(5, None, None, None)```, and ```(5, None)```. Is that what you intended?  The error clearly throws ```TypeError: 'NoneType' object is not subscriptable```. Please let me know what you think. Thanks!

**Comment by nectario** [comment]
Both X and y consist of variable length lists and hence, are ragged tensors. RaggedTensors is an exciting new feature of Tesnorflow 2.0 and this is exactly what I want!

**Comment by nectario** [comment]
I do not want to pad!

**Comment by jvishnuvardhan** [comment]
I tried `tf-nightly` instead of `TF2.0` that was used in the gist. I still get the same error as you are getting. Thanks!

**Comment by nectario** [comment]
This error happens because Model class does not have a shape field. In the code if no shape is present, it initializes it to None. Here is a snippet in base_layer:

```
 input_shapes = None
      if all(hasattr(x, 'shape') for x in input_list):
        input_shapes = nest.map_structure(lambda x: x.shape, inputs)
      # Only call `build` if the user has manually overridden the build method.
      if not hasattr(self.build, '_is_default'):
        # Any setup work performed only once should happen in an `init_scope`
        # to avoid creating symbolic Tensors that will later pollute any eager
        # operations.
        with tf_utils.maybe_init_scope(self):
          self.build(input_shapes)
```

**Comment by ravikyram** [comment]
I have tried in colab with TF GPU version 2.2, nightly version and was able to reproduce the issue.Please, find the gist [here](https://colab.research.google.com/gist/ravikyram/c69ad703c9307d2fff4fa05eda9b316b/untitled30.ipynb).Thanks!

**Comment by sachinprasadhs** [comment]
Was able to reproduce your issue in Tensorflow GPU 2.5, please find the gist [here](https://colab.research.google.com/gist/sachinprasadhs/9647b4ee94fa0a18f68708eff3b17772/35007.ipynb). Thanks!

**Comment by tensorflowbutler** [comment]
Hi There,

 This is a stale issue. As you are using an older version of tensorflow, we are checking to see if you still need help on this issue. Please test the issue with the latest TensorFlow (TF2.7 and tf-nightly). If the issue still persists with the newer versions of TF, please feel free to open it in [keras-team/keras](https://github.com/keras-team/keras/issues) repository by providing details about the issue and a standalone code to reproduce the issue. Thanks! 

 Please note that Keras development has moved to a separate Keras-team/keras repository to focus entirely on only Keras. Thanks!

**Comment by nectario** [comment]
Issue can be closed. Don't experience this now.
