### ISSUE TITLE
Gradient of matmul in while_loop works when run eagerly but not as tf.function

### ISSUE THREAD

**Issue by mjwatkins2** [tensorflow/tensorflow#35012]
**System information**
- Have I written custom code: Example provided below
- OS Platform and Distribution: Both Windows 10 and Google Colab
- TensorFlow installed from binary
- TensorFlow version: Both 2.0.0 and 2.1.0-rc0
- Python version: 3.6 and 3.7.4

**Describe the current behavior**
If I multiply tensors together in a while_loop I can compute higher order gradients when running eagerly, but not when running inside a function with the @tf.function decorator. If I manually unroll the loop, it works either way, so the problem must be related to the interaction between tf.function and tf.while_loop.

> TypeError: in converted code:
> 
>     <ipython-input-17-50c1c9a72b0f>:17 func  *
>         d3y_dx3 = t.gradient(d2y_dx2, x)
>     /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/eager/backprop.py:999 gradient
>         if not backprop_util.IsTrainable(t):
>     /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/eager/backprop_util.py:30 IsTrainable
>         dtype = dtypes.as_dtype(dtype)
>     /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/dtypes.py:725 as_dtype
>         (type_value,))
> 
>     TypeError: Cannot convert value None to a TensorFlow DType.

**Describe the expected behavior**
The output of this function should be the same regardless of the @tf.function decorator:
> [[0 0 4]]
> [[[-2 1 10]]]
> [[[8 2 20]]]
> [[[-18 6 30]]]
> [[[24 24 24]]]

**Code to reproduce the issue**
Run without and then with @tf.function:
```
import tensorflow as tf

x = tf.Variable([[[-1.0]], [[0.0]], [[1.0]]])

# @tf.function
def func():
    with tf.GradientTape(persistent=True) as t:
        t.watch(x)
        pv = x
        
        n = 4
        c = lambda i, _: i < n
        b = lambda i, pv: (i+1, tf.concat([x, tf.matmul(pv, x)], axis=1))
        _, pv = tf.while_loop(c, b, (tf.constant(1), pv), shape_invariants=(tf.constant(1).shape, tf.TensorShape([3, None, 1])))

        # manual loop unrolling works fine both ways:
        # pv = tf.concat([x, tf.matmul(pv, x)], axis=1)
        # pv = tf.concat([x, tf.matmul(pv, x)], axis=1)
        # pv = tf.concat([x, tf.matmul(pv, x)], axis=1)
        
        y = tf.reduce_sum(pv, axis=1)
        dy_dx = t.gradient(y, x)
        d2y_dx2 = t.gradient(dy_dx, x)
        d3y_dx3 = t.gradient(d2y_dx2, x)
        d4y_dx4 = t.gradient(d3y_dx3, x)
    del t

    tf.print(tf.transpose(y)) # transpose to print on one line
    tf.print(tf.transpose(dy_dx))
    tf.print(tf.transpose(d2y_dx2))
    tf.print(tf.transpose(d3y_dx3))
    tf.print(tf.transpose(d4y_dx4))

func()
```

**Comment by oanush** [comment]
Issue replicating for TF 2.1, kindly find the [gist](https://colab.sandbox.google.com/gist/oanush/90b02ed9bb7cc3c9e4e404dcc93ab9bb/35012.ipynb) of colab.Thanks!

**Comment by alextp** [comment]
@allenlavoie does this ring any bells?

**Comment by allenlavoie** [comment]
We have not yet fixed higher-order gradients for cond/while under a tape AFAIK. I believe they need a similar fix to the one we applied to tf.function for recording/accepting gradients of side-outputs. CC @saxenasaurabh. `tf.gradients` likely works.

That said, I'm not sure why this specific error is the one we see first. If we're not going to fix/test these soon we should probably start throwing an exception (we've had an internal bug open for a while).

**Comment by Athul8raj** [comment]
Since gradient tape with the tf.while_loop was not running with the tf.function decorator ,I move the the while loop(python while) into another function and then decorated it with the tf.function. It seems to be working.

Please find the gist here : 
https://colab.research.google.com/drive/1Y_0EfYzkA6dWjCCL02mz3vOgJRdwpqd1

**Comment by saxenasaurabh** [comment]
Wrapping in `tf.function` sounds reasonable till we have a proper fix. Runtime performance would be similar since we would inline the inner `tf.function` anyway.

**Comment by mjwatkins2** [comment]
Fair enough, thank you all.

**Comment by ravikyram** [comment]
Issue is replicating with TF 2.2-rc3 .Please, find the gist [here](https://colab.sandbox.google.com/gist/ravikyram/3ef77bf017c72028e54600191a994754/untitled820.ipynb).Thanks!

**Comment by Saduf2019** [comment]
Issue is replicating with TF 2.4.0-dev20200817 .Please, find the [gist here](https://colab.research.google.com/gist/Saduf2019/5f514ad7ab269ca09368f4ea343bab8a/untitled367.ipynb).Thanks!

**Comment by sushreebarsa** [comment]
Was able to replicate the issue in TF v2.5,please find the gist [here](https://colab.research.google.com/gist/sushreebarsa/96b5bb532a7689c334b72c5cbd11fd80/untitled119.ipynb)..Thanks !

**Comment by sushreebarsa** [comment]
Was able to replicate the issue with TF 2.6.0-dev20210606,please find the gist [here](https://colab.research.google.com/gist/sushreebarsa/92e81bf1813b8395fd3f11c148fdab4d/untitled253.ipynb) ..Thanks!

**Comment by kumariko** [comment]
I could reproduce the issue with TF 2.6 . Please find the [**`gist`**](https://colab.research.google.com/gist/kumariko/4c5030039b88f4c2bbf1205f46b515ae/untitled253.ipynb#scrollTo=8bSJFFrhl86E) here.Thanks!

**Comment by chunduriv** [comment]
I was able to replicate the issue in tf-nightly 2.10.0-dev20220726. Please find the [gist](https://colab.sandbox.google.com/gist/chunduriv/4804410121549b20a883ddde3bf528a5/untitled44.ipynb) for reference. Thank you.

**Comment by tilakrayal** [comment]
Closing this as stale. Please reopen if this is still a valid request. Thank you!
