### ISSUE TITLE
Streaming_mean along specific dimension

### ISSUE THREAD

**Issue by jrabary** [tensorflow/tensorflow#3502]
Currently the streaming_mean function computes the mean for all tensor values. It would be interesting to have the possibility to specify the axis along with we want to compute the mean.

**Comment by michaelisard** [comment]
Marking as contributions welcome since it is in contrib not core TensorFlow.

**Comment by itsmeolivia** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
