### ISSUE TITLE
How to use a lstm layer with projection in tf2.0

### ISSUE THREAD

**Issue by manish-kumar-garg** [tensorflow/tensorflow#35026]
Is there any way to use projection in tf.keras.layers.lstm mention in [paper](https://static.googleusercontent.com/media/research.google.com/en//pubs/archive/43905.pdf)

**Comment by manish-kumar-garg** [comment]
Hi @gowthamkpr, can you tell me how to achieve this?

**Comment by gowthamkpr** [comment]
@manish-kumar-garg I am going to close this issue as this is not related to bug/performance, build/install, feature request or docs related issues. Please post this question in stackoverflow .Thanks!

**Comment by beanmoon** [comment]
is it possible now in 2021?
