### ISSUE TITLE
[MLIR] tf-opt can not run with -debug option

### ISSUE THREAD

**Issue by qqsun8819** [tensorflow/tensorflow#35023]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):Linux Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:No
- TensorFlow installed from (source or binary):source
- TensorFlow version (use command below): 2.0.0
- Python version:3.7
- Bazel version (if compiling from source):1.0.1
- GCC/Compiler version (if compiling from source):6.4.0
- CUDA/cuDNN version: 10
- GPU model and memory: V100 

**Describe the current behavior**
in current tensorflow dialect (implemented in tensorflow/compiler/mlir)， we use LLVM_DEBUG in various place to print some debug information during compilation , and if we run tf-opt , it's expected to print these informations with -debug option added, this is also the behavior with mlir-opt, but in current master branch , if I pass a -debug option to tf-opt ,an error occured
 ```
#bazel-bin/tensorflow/compiler/mlir/tf-opt -debug
tf-opt: Unknown command line argument '-debug'.  Try: 'bazel-bin/tensorflow/compiler/mlir/tf-opt --help'
tf-opt: Did you mean '--help'?
```
but if I run mlir-opt with -debug:
```
#bin/mlir-opt -debug
Args: bin/mlir-opt -debug
```
I've also compared the main function between tf-opt(https://github.com/tensorflow/tensorflow/blob/master/tensorflow/compiler/mlir/tf_mlir_opt_main.cc ) and mlir-opt  (https://github.com/tensorflow/mlir/blob/master/tools/mlir-opt/mlir-opt.cpp ) and see no apparent difference between the two files

**Describe the expected behavior**

tf-opt can run with -debug so I can use the debug info to debug the compilation process

**Comment by jpienaar** [comment]
In InitMlir we parse the flags with the two different command libraries in use: if no ` -- ` is on the line, then all are passed to LLVM's cl, if ` -- ` then the part before ` -- ` is passed to LLVM and those after to TF's flags. Try 

tf-opt -debug --

Please reopen if this doesn't resolve it.
