### ISSUE TITLE
Installing tensorflow on windows through Docker

### ISSUE THREAD

**Issue by josefinb** [tensorflow/tensorflow#3503]
Hi,

I've successfully installed docker toolbox and created a container but when I enter 

docker run -it b.gcr.io/tensorflow/tensorflow

I get "Unable to find image 'docker run -it b.gcr.io/tensorflow/tensorflow' loally"

I have read on other threads that this might be due to space allocation so this container already has 20gb.

What do I do? I've got a Windows 10 Pro.

Thanks a lot!

**Comment by martinwicke** [comment]
Because of a severe lack of Windows machine to test this on we can't directly support Windows (yet). Maybe someone here has an idea. You can also try StackOverflow.

**Comment by martinwicke** [comment]
I don't believe this is a TensorFlow issue. Please comment to reopen if it is, and if so, let me know what we can change to improve this.
