### ISSUE TITLE
ValueError: This converter can only convert a single ConcreteFunction. Converting multiple functions is under development.

### ISSUE THREAD

**Issue by anandsaini024** [tensorflow/tensorflow#35031]
**System information**
- Windows 10 866 bit OS,x64 based processor 
- python 3.5.4 (working on virtual env)
- pip installed version of Tensorflow
- TensorFlow version: tensorflow==2.0.0
- other packages:
scikit-learn==0.22
scipy==1.4.0rc2
six==1.12.0
tb-nightly==2.1.0a20191115

**Command used to run the converter or code if you’re using the Python API**
Used the following code to quantize the frozen graph [http://download.tensorflow.org/models/speech_commands_v0.02.zip]()
```
# the above frozen graph was saved in a directory as "saved_model"
```
code:
import tensorflow as tf
def representative_dataset_gen():
  for _ in range(num_calibration_steps):
    # Get sample input data as a numpy array in a method of your choosing.
    yield [input]

converter = tf.lite.TFLiteConverter.from_saved_model('C:/test/saved_model')
converter.optimizations = [tf.lite.Optimize.OPTIMIZE_FOR_SIZE]
converter.representative_dataset = representative_dataset_gen
tflite_quant_model = converter.convert()

**The output from the converter invocation**

```
File "trained_model_quantize.py", line 11, in <module>
    tflite_quant_model = converter.convert()
  File "C:\Users\Desktop\Projects\Environments\google_speech\lib\site-packages\tensorflow_core\lite\python\lite.py", line 421, in convert
    raise ValueError("This converter can only convert a single "
ValueError: This converter can only convert a single ConcreteFunction. Converting multiple functions is under development.
```

**Also, please include a link to the saved model or GraphDef**
Tutorial: [https://github.com/tensorflow/docs/blob/master/site/en/r1/tutorials/sequences/audio_recognition.md]()
 
Graph: [http://download.tensorflow.org/models/speech_commands_v0.02.zip]()
**Objective**
I'm trying to convert this model (frozen graph) which is in normal Float 32 to fixed point 8 bit.

**Comment by trayanmomkov** [comment]
@daverim could you please explain what exactly "This converter can only convert a single ConcreteFunction." means?
Why it happens and how to avoid it?
Sorry if questions are silly but I'm new to Tensorflow.

**Comment by ckcampbell248** [comment]
Are there any updates on this? I'm having the same issue.

**Comment by trayanmomkov** [comment]
See this: https://github.com/tensorflow/tensorflow/issues/34350

**Comment by sushreebarsa** [comment]
@anandsaini024  Could you please try on latest stable version of tf 2.5 or 2.4.1 and let us know if this is still an issue.Thanks!
