### ISSUE TITLE
How to know if savedmodel supports batch input and dynamic length input?

### ISSUE THREAD

**Issue by zxgm** [tensorflow/tensorflow#35042]
I use the follwing code:

```
with tf.Session() as sess:
    meta_graph_def = tf.saved_model.loader.load(sess, ["serve"], model_path)
    signature = meta_graph_def.signature_def
    print(signature["serving_default"])
    if str(-1) in str(signature["serving_default"]):
        print("support batch input")
    else:
        print("Not support batch input")
```
the result:
```
inputs {
  key: "hist_i"
  value {
    name: "my_input/hist_item_id:0"
    dtype: DT_INT32
    tensor_shape {
      dim {
        size: -1
      }
      dim {
        size: -1
      }
    }
  }
}
inputs {
  key: "hist_t"
  value {
    name: "my_input/hist_time:0"
    dtype: DT_INT32
    tensor_shape {
      dim {
        size: -1
      }
      dim {
        size: -1
      }
    }
  }
}
inputs {
  key: "item_id"
  value {
    name: "my_input/item_id:0"
    dtype: DT_INT32
    tensor_shape {
      dim {
        size: -1
      }
    }
  }
}
inputs {
  key: "sl"
  value {
    name: "my_input/Placeholder:0"
    dtype: DT_INT32
    tensor_shape {
      dim {
        size: -1
      }
    }
  }
}
inputs {
  key: "user_id"
  value {
    name: "my_input/user_id:0"
    dtype: DT_INT64
    tensor_shape {
      dim {
        size: -1
      }
    }
  }
}
```
But the code can't to distinguish with batch input and dynamic  length input.Anyone can help me?Thank you very much.

**Comment by ravikyram** [comment]
@zxgm 

Can you please help us with the Tensorflow version you are using?.And also request you to provide simple standalone code to reproduce the issue in our environment.It helps us in localizing the issue faster. Thanks!

**Comment by zxgm** [comment]
I use tensorflow1.12 or tensorflow1.14.Assume have a savedmodel format model,how to know if the savedmodel supports batch input and dynamci length input? Are there related APIs to determine whether batch processing is supported?

**Comment by ymodak** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.
 Thanks!
