### ISSUE TITLE
Use bazel to build tensorflow has some error

### ISSUE THREAD

**Issue by kscorpio** [tensorflow/tensorflow#35051]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution :Linux Ubuntu 18.04 
- TensorFlow installed from (source or binary):source
- Python version: 3.6
- Installed using virtualenv? pip? conda?: pip
- Bazel version (if compiling from source):bazel-1.0.0 and soft lint to bazel
- GCC/Compiler version (if compiling from source): 7.4.0 
- CUDA/cuDNN version: no 

**Describe the problem**
use bazel to build tensorflow (newest clone from github)

```
bazel build --local_ram_resources=2048 --config=opt //tensorflow/tools/pip_package:build_pip_package 
``` 
Error message : 
```
gcc: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-7/README.Bugs> for instructions.
Target //tensorflow/tools/pip_package:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.
ERROR: /home/test/tensorflow/tensorflow/python/tools/BUILD:280:1 C++ compilation of rule '//tensorflow/core/kernels:conv_ops' failed (Exit 4)
INFO: Elapsed time: 13914.473s, Critical Path: 2099.24s
INFO: 3244 processes: 3244 local.
FAILED: Build did NOT complete successfully
```

**Comment by mapavia** [comment]
I am also experiencing the same error. Were you able to fix it?

**Comment by mihaimaruseac** [comment]
Can you try to reduce amount of resources used by the compiler?

**Comment by mapavia** [comment]
Solve mine by using `--local_cpu_resources 1` instead of `--local_ram_resources=2048`

**Comment by mihaimaruseac** [comment]
In this case, can we close as fixed?

**Comment by amahendrakar** [comment]
@kscorpio,
Is this still an issue?

> Solved mine by using `--local_cpu_resources 1` instead of `--local_ram_resources=2048`

Please take a look at @mapavia's comment and check if it helps. Thanks!
