### ISSUE TITLE
Enable fully_connected to uniquify the scope name

### ISSUE THREAD

**Issue by cgarciae** [tensorflow/tensorflow#3505]
The implementation of `tf.contrib.layers.fully_connected` uses `variable_op_scope` to handle the name scope of the variables, the problem is that the name scope is only _uniquified_ if `scope` is `None`, that is, if you dont pass a custom name, by default it will be `"fully_connected"`. 

However, in the library I am building I create tons of shorcut methods like `relu_layer`, `sigmoid_layer`, etc, which are implemented using `fully_connected` plus their corresponding activation function. I'd like these names to be uniquified automatically so I don't get these kind of errors:

> ValueError: Variable relu_layer/weights already exists, disallowed. Did you mean to set reuse=True in VarScope?

In the mean time, could you give me a hint of how to uniquify a variable name scope myself? Is there a function that does this already?

Thanks!

**Comment by michaelisard** [comment]
[StackOverflow](https://stackoverflow.com/questions/tagged/tensorflow) is a better venue for this kind of usage question. Does adding your own variable_op_scope outside the call to fully_connected help?

**Comment by cgarciae** [comment]
@michaelisard It works but I don't think its a proper solution, the names and TensorBoard graph become highly redundant, for example `relu_layer_2/fully_connected/Relu` and `relu_layer_2/fully_connected/weights`, with a small fix you could remove the `fully_connected` part.

Just change

    with variable_scope.variable_op_scope([inputs],
                                        scope,
                                        'fully_connected',
                                        reuse=reuse) as sc:

to

    scope = scope if scope else `fully_connected`
    with variable_scope.variable_op_scope([inputs],
                                        None,
                                        scope,
                                        reuse=reuse) as sc:

on
https://github.com/tensorflow/tensorflow/blob/73ced9d797056c7e67a06ed2098dd809d85ec44a/tensorflow/contrib/layers/python/layers/layers.py#L786

I could create a pull request if you like.

**Comment by cgarciae** [comment]
You could also just define the input parameters scope as `scope='fully_connected'` on the function definition an eliminate the line `scope = scope if scope else `fully_connected` of my solution

**Comment by michaelisard** [comment]
@sguada maybe you can comment?

**Comment by sguada** [comment]
Using automatic naming for variable_scopes is a bad idea, if you add a new layer in between all the variables change their name, and create problems restoring and reusing models.  For instance you cannot reuse a layer unless it has given scope.

There is already some partial functions that assign different activation functions to fully_connected 
https://github.com/tensorflow/tensorflow/blob/73ced9d797056c7e67a06ed2098dd809d85ec44a/tensorflow/contrib/layers/python/layers/layers.py#L1337

I could consider adding a default_parameter='fully_connected' to the layers, but I would encourage you to use explicit names for all your layers.

**Comment by cgarciae** [comment]
@sguada Thing is, in the same way `fully_connected` lets your users get away with not naming every single layer but getting a sensible default, I too would like the users of my library to have that flexibility. That automatic behavior is very helpful when your just learning and want to get things done quickly.

The `default_parameter='fully_connected'` idea is excellent, would allow both automatic naming + unique identification when reuse is required.

**Comment by tfboyd** [comment]
Automatically closing due to lack of recent activity. We hope that you were able to resolve it on your own. However, since this is a support issue rather than a bug or feature request, you will probably get more information by posting it on StackOverflow.
