### ISSUE TITLE
 AndroidRuntime: Node number 1 (SPLIT) failed to prepare.

### ISSUE THREAD

**Issue by glevenc** [tensorflow/tensorflow#35053]
Hi, when i use my own trained rnn model to inference on my andorid app
the tflite convert is successully with python api 

import tensorflow as tf
converter = tf.lite.TFLiteConverter.from_saved_model(saved_model_dir)
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS,
                                       tf.lite.OpsSet.SELECT_TF_OPS]
tflite_model = converter.convert()
open("converted_model.tflite", "wb").write(tflite_model)

but when i run this model in andorid app ,
tflite.run(input, output);
 it run into the issuses as the log shows:
could anyone take a look at this?

**Any other info / logs**
[16-14-29.810] 01-01 08:49:45.232 12405 12427 E AndroidRuntime: FATAL EXCEPTION: inference
﻿﻿[16-14-29.810] 01-01 08:49:45.232 12405 12427 E AndroidRuntime: Process: com.hse.wifimotiondetection, PID: 12405
﻿﻿[16-14-29.810] 01-01 08:49:45.232 12405 12427 E AndroidRuntime: java.lang.IllegalStateException: Internal error: Unexpected failure when preparing tensor allocations: tensorflow/lite/kernels/split.cc Not an even split
﻿﻿[16-14-29.810] 01-01 08:49:45.232 12405 12427 E AndroidRuntime: Node number 1 (SPLIT) failed to prepare.
﻿﻿[16-14-29.854] 01-01 08:49:45.232 12405 12427 E AndroidRuntime: 
﻿﻿[16-14-29.854] 01-01 08:49:45.232 12405 12427 E AndroidRuntime:        at org.tensorflow.lite.NativeInterpreterWrapper.allocateTensors(Native Method)
﻿﻿[16-14-29.854] 01-01 08:49:45.232 12405 12427 E AndroidRuntime:        at org.tensorflow.lite.NativeInterpreterWrapper.run(NativeInterpreterWrapper.java:143)
﻿﻿[16-14-29.854] 01-01 08:49:45.232 12405 12427 E AndroidRuntime:        at org.tensorflow.lite.Interpreter.runForMultipleInputsOutputs(Interpreter.java:296)
﻿﻿[16-14-29.898] 01-01 08:49:45.232 12405 12427 E AndroidRuntime:        at org.tensorflow.lite.Interpreter.run(Interpreter.java:259)
﻿﻿[16-14-29.898] 01-01 08:49:45.232 12405 12427 E AndroidRuntime:        at com.hse.wifimotiondetection.tflite.Classifier.recognizeWiFiData(Classifier.java:282)
﻿﻿[16-14-29.898] 01-01 08:49:45.232 12405 12427 E AndroidRuntime:        at com.hse.wifimotiondetection.MainActivity$1.run(MainActivity.java:101)
﻿﻿[16-14-29.899] 01-01 08:49:45.232 12405 12427 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:789)
﻿﻿[16-14-29.942] 01-01 08:49:45.232 12405 12427 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:98)
﻿﻿[16-14-29.942] 01-01 08:49:45.232 12405 12427 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:164)
﻿﻿[16-14-29.943] 01-01 08:49:45.232 12405 12427 E AndroidRuntime:        at android.os.HandlerThread.run(HandlerThread.java:65)
﻿﻿[16-14-29.943] 01-01 08:54:34.738 13372 13372 I AndroidRuntime: VM exiting with result code 0.

**Comment by jvishnuvardhan** [comment]
@glevenc Can you please try 
1. the example I provided in this [example](https://colab.sandbox.google.com/gist/jvishnuvardhan/66d5a457486c4a3189950d91a0b8c159/untitled632.ipynb) and see whether the tensorflow model and the tf_lite model are working similar? 
2. Can you please share a standalone code to reproduce the issue. Thanks!

**Comment by glevenc** [comment]
> 
> 
> @glevenc Can you please try
> 
>     1. the example I provided in this [example](https://colab.sandbox.google.com/gist/jvishnuvardhan/66d5a457486c4a3189950d91a0b8c159/untitled632.ipynb) and see whether the tensorflow model and the tf_lite model are working similar?
> 
>     2. Can you please share a standalone code to reproduce the issue. Thanks!

@jvishnuvardhan 
Hi, sorry , i cannot try the example during the 
tf.compat.v1.disable_eager_execution() this mode  in my code  when i convert the model to tflite format
as the log error shows


>>> tflite_model = converter.convert()
WARNING:tensorflow:Issue encountered when serializing variables.
Type is unsupported, or the types of the items don't match field type in CollectionDef. Note this is a warning and probably safe to ignore.
Tensor.name is meaningless when eager execution is enabled.
2019-12-14 10:58:26.734639: I tensorflow/core/grappler/devices.cc:60] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0 (Note: TensorFlow was not compiled with CUDA support)
2019-12-14 10:58:26.741202: I tensorflow/core/grappler/clusters/single_machine.cc:356] Starting new session
2019-12-14 10:58:26.755469: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:716] Optimization results for grappler item: graph_to_optimize
2019-12-14 10:58:26.760993: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:718]   function_optimizer: function_optimizer did nothing. time = 0.001ms.
2019-12-14 10:58:26.764765: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:718]   function_optimizer: function_optimizer did nothing. time = 0.001ms.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\d\.conda\envs\ai\lib\site-packages\tensorflow_core\lite\python\lite.py", line 405, in convert
    self._funcs[0], lower_control_flow=False)
  File "C:\Users\d\.conda\envs\ai\lib\site-packages\tensorflow_core\python\framework\convert_to_constants.py", line 411, in convert_variables_to_constants_v2
    tensor_data = _get_tensor_data(func)
  File "C:\Users\d\.conda\envs\ai\lib\site-packages\tensorflow_core\python\framework\convert_to_constants.py", line 193, in _get_tensor_data
    data = map_index_to_variable[idx].numpy()
  File "C:\Users\d\.conda\envs\ai\lib\site-packages\tensorflow_core\python\ops\resource_variable_ops.py", line 579, in numpy
    "numpy() is only available when eager execution is enabled.")
NotImplementedError: numpy() is only available when eager execution is enabled.

**Comment by haozha111** [comment]
hi, does this issue still exist?
