### ISSUE TITLE
4D transpose convolutional layers

### ISSUE THREAD

**Issue by OrodRazeghi** [tensorflow/tensorflow#35058]
I've been looking for an implementation of a 4D conv layer in tensorflow and found a solution here:
https://github.com/funkey/conv4d
I was wondering if anyone could help me with the transpose version of this 4D conv layer. How would that look like in the implementation? It seems that in this case, frame_results is the output and is the result of summing the convolution of the current input frame with its previous kernel frame. The reverse would be the result of summing the 3D transpose layers? or there is more to it? any comments will be very appreciated, thanks.

**Comment by jvishnuvardhan** [comment]
This is not Build/Installation or Bug/Performance issue. Please post this kind of support questions at [Stackoverflow](https://stackoverflow.com/questions/tagged/tensorflow). There is a big community to support and learn from your questions. GitHub is mainly for addressing bugs in installation and performance. Thanks!
