### ISSUE TITLE
functional ops are not exposed in documentation

### ISSUE THREAD

**Issue by alquraishi** [tensorflow/tensorflow#3506]
It appears that functional ops are now fully documented, given /tensorflow/g3doc/api_docs/python/functional_ops.md, but they are not exposed in the main documentation (index.md does not link to functional_ops.md)

**Comment by alquraishi** [comment]
I take it back. I see that they are linked, but for some reason in the API browser they don't show up in the left side navigator.

**Comment by alquraishi** [comment]
I also can't find TensorArray in the docs.

**Comment by drpngx** [comment]
We now have spiffy new docs. Feel free to open a new issue if you have issues with the new docs on our devsite.
