### ISSUE TITLE
 [1.15] Build from source fails on Raspberry Pi

### ISSUE THREAD

**Issue by tallero** [tensorflow/tensorflow#35062]
**System information**
- OS Platform and Distribution: Archlinux
- Mobile device: Raspberry Pi
- TensorFlow installed from (source or binary): source
- TensorFlow version: 1.15
- Python version: 3.8
- Installed using virtualenv? pip? conda?: the docker image you provide.
- Bazel version (if compiling from source): the one you put in that image.
- GCC/Compiler version (if compiling from source): the one you put in the image
- CUDA/cuDNN version: No cuda
- GPU model and memory: The computer on which Docker runs has 16gb of ram.

Builds fails while compiling. Build log has been attached. Instructions actually mention that one should checkout a known working version but it does not specify where I could discover which version actually builds on raspberry.

The one listed at this [documentation page](https://www.tensorflow.org/install/source_rpi):

    CI_DOCKER_EXTRA_PARAMS="-e CI_BUILD_PYTHON=python3 -e CROSSTOOL_PYTHON_INCLUDE_PATH=/usr/include/python3.4" \
    tensorflow/tools/ci_build/ci_build.sh PI-PYTHON3 \
    tensorflow/tools/ci_build/pi/build_raspberry_pi.sh

**Any other info / logs**
[tensorflow-1.15-docker-raspberry-armhf-build.log](https://github.com/tensorflow/tensorflow/files/3957401/tensorflow-1.15-docker-raspberry-armhf-build.log).

Actually it just failed on another point, too.
Last part of the latter log:

    peStorage; UniquerT = mlir::detail::TypeUniquer]'
    external/local_config_mlir/lib/IR/Types.cpp:66:66:   required from here
    external/local_config_mlir/include/mlir/Support/StorageUniquer.h:232:34: error: 'getKey' is not a member of 'mlir::detail::OpaqueTypeStorage'
         return ImplTy::getKey(args...);
                                      ^
    external/local_config_mlir/include/mlir/Support/StorageUniquer.h: In instantiation of 'static typename std::enable_if<typename mlir::detail::detector<void, mlir::detail::has_impltype_hash_t, ImplTy, DerivedKey>::value_t:: value, llvm::hash_code>::type mlir::StorageUniquer::getHash(unsigned int, const DerivedKey&) [with ImplTy = mlir::detail::OpaqueTypeStorage; DerivedKey = std::pair<mlir::Identifier, llvm::StringRef>; typename std::enable_if<typename mlir::detail::detector<void, mlir::detail::has_impltype_hash_t, ImplTy, DerivedKey>::value_t:: value, llvm::hash_code>::type = llvm::hash_code]':
    external/local_config_mlir/include/mlir/Support/StorageUniquer.h:141:59:   required from 'Storage* mlir::StorageUniquer::get(std::function<void(Storage*)>, unsigned int, Arg&&, Args&& ...) [with Storage = mlir::detail::OpaqueTypeStorage; Arg = mlir::Identifier&; Args = {llvm::StringRef&}]'
    external/local_config_mlir/include/mlir/IR/TypeSupport.h:104:42:   required from 'static T mlir::detail::TypeUniquer::get(mlir::MLIRContext*, unsigned int, Args&& ...) [with T = mlir::OpaqueType; Args = {mlir::Identifier&, llvm::StringRef&}]'
    external/local_config_mlir/include/mlir/IR/StorageUniquerSupport.h:67:64:   required from 'static ConcreteT mlir::detail::StorageUserBase<ConcreteT, BaseT, StorageT, UniquerT>::get(mlir::MLIRContext*, unsigned int, Args ...) [with Args = {mlir::Identifier, llvm::StringRef}; ConcreteT = mlir::OpaqueType; BaseT = mlir::Type; StorageT = mlir::detail::OpaqueTypeStorage; UniquerT = mlir::detail::TypeUniquer]'
    external/local_config_mlir/lib/IR/Types.cpp:66:66:   required from here
    external/local_config_mlir/include/mlir/Support/StorageUniquer.h:255:63: error: 'hashKey' is not a member of 'mlir::detail::OpaqueTypeStorage'
         return llvm::hash_combine(kind, ImplTy::hashKey(derivedKey));

**EDIT 19/12/17:** As a temporary workaround I installed [PINTO0309](https://github.com/PINTO0309/Tensorflow-bin)'s binaries.

**Comment by mhurliman** [comment]
Just hit this same issue building PI-PYTHON3, PI_ONE on a Ubuntu 18.04 host build machine.

**Comment by dougyfresh42** [comment]
I believe this issue has to do with the older cross compiler in the 1.15 Pi build (v4.9) which doesn't support all C++14 extensions.  I've worked around the issue by cherry-picking [commit 20dfc83d](https://github.com/tensorflow/tensorflow/commit/20dfc83d59d591339ba4be06230a7350543cfe40#diff-00a21b168974d2d842d84a57987129f4) and then building:
```bash
git clone https://github.com/tensorflow/tensorflow.git
cd tensorflow/
git checkout v1.15.0
git cherry-pick 20dfc83d
```

**Comment by terryheo** [comment]
Thanks, @dougyfresh42 
I've created PR for the cherry-pick.
https://github.com/tensorflow/tensorflow/pull/39441
