### ISSUE TITLE
Bug in documentation of tf.while_loop.  parallel_iterations doesn't seem to affect performance.

### ISSUE THREAD

**Issue by charles19920528** [tensorflow/tensorflow#35065]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes and no.
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04.3 LTS
- TensorFlow installed from (source or binary): I used `pip install tensorflow-gpu==2.0.0`
- TensorFlow version (use command below): 2.0.0
- Python version: 3.7.5
- CUDA/cuDNN version: 10.1
- GPU model and memory: 1080 TI and 11170 MiB

**Describe the current behavior**
First as discussed in this [issue](https://github.com/tensorflow/tensorflow/issues/18257). There is a bug in the first example of the documentation of `tf.while_loop`. 

Then, the parallel_iterations argument doesn't seem to parallelize the loop. There is no difference between the run time with `parallel_iterations = 1` or `parallel_iterations = 10`. 
I have a question opened on [Stackoverflow](https://stackoverflow.com/questions/59299060/tf-2-0-while-loop-and-parallel-iterations) .

**Describe the expected behavior**
If the function in iteration n doesn't depend on previous iterations, then I expect that by setting `parallel_iterations = 10,` the loop should finish about 10 times faster than setting `parallel_iterations = 1`
**Code to reproduce the issue**
The code is posted on the [Stackoverflow](https://stackoverflow.com/questions/59299060/tf-2-0-while-loop-and-parallel-iterations).

**Comment by ravikyram** [comment]
@charles19920528 

I have tried in colab with TF 2.0. Please, find the gist [here](https://colab.sandbox.google.com/gist/ravikyram/d7958779064096e958bbcf734e8df670/untitled486.ipynb). Is this the expected behavior?

**Comment by charles19920528** [comment]
@ravikyram Not really. I was hoping that by just setting `parallel_iterations=10`, the `print_fun` will run in parallel. I don't think this [code](https://colab.sandbox.google.com/gist/ravikyram/d7958779064096e958bbcf734e8df670/untitled486.ipynb) is running in parallel. 

I sort of got my answer on the [StackOverflow](https://stackoverflow.com/questions/59299060/tf-2-0-while-loop-and-parallel-iterations). As Srihari Humbarwadi pointed out, the `parallel_iterations` argument in `tf.while_loop` doesn't mean anything in the eager mode. So in order to run the loop in parallel, I need to use the graph mode with `@tf.function`. The documentation of `tf.while_loop` , as far as I can tell, doesn't explicitly mentioned this important point . So perhaps someone can improve the documentation.

**Comment by Saduf2019** [comment]
@charles19920528 
Is this still an issue

**Comment by mdanatg** [comment]
Side note: a bug in tf.while_loop itself caused tf.while_loop to run sequentially, even in graph mode. Eager tf.while_loop is still identical to running a Python while.
