### ISSUE TITLE
Calculate arena size for TensorFlow Lite Micro models

### ISSUE THREAD

**Issue by petewarden** [tensorflow/tensorflow#35070]
TensorFlow Lite for Microcontrollers doesn't depend on dynamic memory allocation, so it requires users to supply a memory arena when an interpreter is created, as described in this documentation:
https://www.tensorflow.org/lite/microcontrollers/get_started
We need a better way to decide 'tensor_arena_size'. Currently, the above page says 'The size required will depend on the model you are using, and may need to be determined by experimentation.'

The simplest solution might be an offline script that returns the size needed to hold a model's activation buffers, but this won't include miscellaneous or platform-dependent allocations in its total. Another approach might be to return the size needed as an integer along with the error report string from the interpreter creation.

**Comment by petewarden** [comment]
Tagging @tensorflow/micro

**Comment by hdpklm** [comment]
> Tagging @tensorflow/micro

this link is not available

**Comment by janjongboom** [comment]
For anyone else looking for a solution: hacked up https://github.com/edgeimpulse/tflite-find-arena-size which can be called from Node.js (or native) and calculates the arena size. The WebAssembly version seems to approximate the required memory on Cortex-M quite well.

**Comment by AdamMiltonBarker** [comment]
This is a real pain, I have an Acute Lymphoblastic Leukemia model loaded on a Nano 33 BLE and get the following, "Arena size is too small for all buffers. Needed 2497920 but only 209248 was available." unfortunately incrementing the arena size any further leads to the board becoming unresponsive, it uses 97% of dynamic memory and if I push arena size any further have to double tap reset to bring the board back to life. I saw a notebook that showed additional steps to help shrink model size (my model is 702632, more than double of person detector) but all Tensorflow notebooks and documentation links are dead within the space of the day.

**Comment by AdamMiltonBarker** [comment]
They have moved here by the way: https://github.com/tensorflow/tflite-micro but none of the old notebooks are available any more. All links from Tensorflow website are broken, not good for people who may be considering using this tech lol.

**Comment by wangtz** [comment]
FYI TFLite micro has an API to show the exact arena size after initialization, just in case it's helpful for you.

https://github.com/tensorflow/tflite-micro/blob/2791785562d660f328c54055bb4ab2df56a37f4a/tensorflow/lite/micro/micro_interpreter.h#L127

**Comment by avionicharshit-byte** [comment]
For anyone landing here from search: this still is not part of TFLM, so I built an open source tool that does it.

```
pip install mcufit
mcufit check model.tflite -b esp32-s3
```

gives an instant arena estimate from static tensor-lifetime analysis, and

```
mcufit setup-exact
mcufit check model.tflite -b esp32-s3 --exact
```

measures the exact arena size by running the model through the real TFLM interpreter compiled for your host machine (no hardware needed). There is also a browser version that does the measurement with TFLM compiled to WebAssembly: https://avionicharshit-byte.github.io/mcufit/

Repo: https://github.com/avionicharshit-byte/mcufit
Hope it saves someone the flash-and-guess loop.
