### ISSUE TITLE
ValueError: Unable to save the object ListWrapper([ListWrapper([None])]) tensorflow 2.0

### ISSUE THREAD

**Issue by zheLim** [tensorflow/tensorflow#35075]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):  Linux Ubuntu 16.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.0.0
- Python version: 3.6.9
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: cuda 10/ cudnn 7.6.5
- GPU model and memory: V100

**Describe the current behavior**
When saving a model, in my case, HRNet, i met the following error: ValueError: Unable to save the object ListWrapper([ListWrapper([None])])
The error message suggest that "If you don't need this list checkpointed, wrap it in a tf.contrib.checkpoint.NoDependency object; it will be automatically un-wrapped and subsequently ignored." However, tf 2.0 has no module named contri.

**Describe the expected behavior**
Save the model correctly.
**Code to reproduce the issue**
You can run the following code to reproduce this issue
https://github.com/zheLim/auto-face-parsing/blob/master/lib/model/seg_hrnet.py

**Comment by gadagashwini** [comment]
@zheLim, Could provide the minimal standalone code to replicate the reported issue. Thanks!

**Comment by zheLim** [comment]
Hi, I have try to provide minimal code, but the problem only happens on the code i proviode. I think it is better to give it up.

**Comment by gadagashwini** [comment]
@zheLim, It would be easy if we share the minimal reproducible code to analyze the reported issue and move faster. Thanks!

**Comment by gadagashwini** [comment]
@zheLim, Any update on minimal code snippet.

**Comment by zheLim** [comment]
> @zheLim, Any update on minimal code snippet.

Thanks for your attention. I did not spend more time on this issue.

**Comment by gadagashwini** [comment]
@zheLim, Will close the issue. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
