### ISSUE TITLE
TensorFlow Lite Micro MaxPool kernel needs int8 support

### ISSUE THREAD

**Issue by petewarden** [tensorflow/tensorflow#35071]
TensorFlow Lite for Microcontrollers has a MAXPOOL operation, but it only supports float and uint8 execution, not int8.

**Comment by petewarden** [comment]
Tagging @tensorflow/micro

**Comment by giorgio-arenarm** [comment]
Hi @petewarden I will start working on it, is that ok for you guys?

**Comment by giorgio-arenarm** [comment]
Issue resolved. It should be safe to close this :)

**Comment by mohantym** [comment]
Hi @petewarden ! MaxPool Kernel from TFLite Micro does support int8 now.
