### ISSUE TITLE
Explain how int8 input and output quantization conversion works in TensorFlow Lite

### ISSUE THREAD

**Issue by petewarden** [tensorflow/tensorflow#35072]
We've had feedback from multiple developers that it's hard to figure out how to calculate the right  int8 values for quantized inputs, and understand what int8 values mean as outputs.

For example, when feeding an image to uint8 quantized inputs, the values can be left as in their source 0 to 255 range. For int8 inputs, the developer will typically need to subtract 128 from each value, but this knowledge (and how the offset value is calculated) is not documented. In the same way, users will need to map the -128 to 127 output values to the actual real number range of their outputs, but this process is unclear.

Tagging the @tensorflow/micro team.

**Comment by PrashantDandriyal** [comment]
Made clarification. Created Pull Request #36271

**Comment by Saduf2019** [comment]
@petewarden 
Please let us know if we can move this to closed status as the pull request is in merged status.

**Comment by Saduf2019** [comment]
Moving this to close status as the pr is merged.
