### ISSUE TITLE
Add usage examples for tf.audio APIs

### ISSUE THREAD

**Issue by boronhub** [tensorflow/tensorflow#35079]
Thank you for submitting a TensorFlow documentation issue. Per our GitHub
policy, we only address code/doc bugs, performance issues, feature requests, and
build/installation issues on GitHub.

The TensorFlow docs are open source! To get involved, read the documentation
contributor guide: https://www.tensorflow.org/community/contribute/docs

## URL(s) with the issue:

Please provide a link to the documentation entry, for example:
https://www.tensorflow.org/api_docs/python/tf/audio

## Description of issue (what needs changing):
Currently, there are no usage examples for tf.audio APIs , which makes it difficult for new users to implement the same.

### Clear description

For example, why should someone use this method? How is it useful?
**Audio is an area not really explored in machine learning to extent image and text has. While TensorFlow does provide a good amount of documentation for the general Args and Returns of the various functions under tf.audio, since most new users will have very little experience with audio as compared to tf.image**

### Correct links

Is the link to the source code correct?
**Yes**

### Parameters defined

Are all parameters defined and formatted correctly?
**Yes**

### Returns defined

Are return values defined?
**Yes**

### Raises listed and defined

Are the errors defined? For example,
https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/feature_column/categorical_column_with_vocabulary_file#raises
**No**

### Usage example

Is there a usage example?
**No**

See the API guide: https://www.tensorflow.org/community/contribute/docs_ref
on how to write testable usage examples.

### Request visuals, if applicable

Are there currently visuals? If not, will it clarify the content?
**Formatted code blocks are present, which are satisfactory.**

### Submit a pull request?

Are you planning to also submit a pull request to fix the issue? See the docs
contributor guide: https://www.tensorflow.org/community/contribute/docs,
docs API guide: https://www.tensorflow.org/community/contribute/docs_ref and the
docs style guide: https://www.tensorflow.org/community/contribute/docs_style
**Yes, I think I can provide a detailed usage example.**

**Comment by ravikyram** [comment]
similar issue#28236

**Comment by boronhub** [comment]
@ravikyram can you please direct me to where i can add usage examples for this ? The docs page does not have a link to where the audio function is located, and I am having some trouble finding it on my own.

**Comment by MarkDaoust** [comment]
Yeah, some ops are auto-generated, and don't have python-source to link to.

Usually if there's no link it's available in the `tensorflow/core/api_dev` directory: 

https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/api_def/base_api/api_def_DecodeWav.pbtxt
