### ISSUE TITLE
optimize_for_inference not working for my graph?

### ISSUE THREAD

**Issue by Razor1O9** [tensorflow/tensorflow#35087]
It does not seem to make a difference if I use optimize_for_inference when I generate the pb and pbtxt graphs for my network. The size of the unoptimized graph is 177.775kb and the size for the optimized graph is 177.739kb.

I'm not sure wheter the optimize_for_inference Tool is correctly working for my graph. I currently cannot deploy my model in openCV, which throws an exception [EX] because the graph does not seem to be optimized. 

**I want to access my tensorflow protobuf files with the following openCV function:**
Net ub6net = readNetFromTensorflow (model, config) // PB and PBTXT

**This throws the following Exception:**
Version 1 - optimize_for_inference disabled: **[EX]** Assertion failed in function 'addConstNodes'
Version 2 - optimize_for_inference enabled: **[EX]** Assertion failed in function 'addConstNodes'

___________________________________

This exception gets thrown when the input files are not optimized for inference and it is thrown regardless of the fact that the graph has been optimized or not, indicating that no optimization was applied.

**I would be glad if someone can help me to solve this issue, as it seems to be related to the optimize_for_inference Tool.**

**My Code to generate the pb and pbtxt file:**

```
# -*- coding: utf-8 -*-
# File: export.py

import tensorflow as tf
from tensorflow.python.framework import graph_util
from tensorflow.python.platform import gfile
from tensorflow.python.tools import optimize_for_inference_lib

from ..compat import is_tfv2, tfv1
from ..input_source import PlaceholderInput
from ..tfutils.common import get_tensors_by_names, get_tf_version_tuple
from ..tfutils.tower import PredictTowerContext
from ..utils import logger

__all__ = ['ModelExporter']


class ModelExporter(object):
    """Export models for inference."""

    def __init__(self, config):
        """Initialise the export process.
        Args:
            config (PredictConfig): the config to use.
                The graph will be built with the tower function defined by this `PredictConfig`.
                Then the input / output names will be used to export models for inference.
        """
        super(ModelExporter, self).__init__()
        self.config = config

    def export_compact(self, filename, optimize=True, toco_compatible=False):
        """Create a self-contained inference-only graph and write final graph (in pb format) to disk.
        Args:
            filename (str): path to the output graph
            optimize (bool): whether to use TensorFlow's `optimize_for_inference`
                to prune and optimize the graph. This does not work on all types of graphs.
            toco_compatible (bool): See TensorFlow's
                `optimize_for_inference
                <https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/tools/optimize_for_inference.py>`_
                for details. Only available after TF 1.8.
        """
        if toco_compatible:
            assert optimize, "toco_compatible is only effective when optimize=True!"
        self.graph = self.config._maybe_create_graph()
        with self.graph.as_default():
            input = PlaceholderInput()
            input.setup(self.config.input_signature)
            with PredictTowerContext(''):
                self.config.tower_func(*input.get_input_tensors())

            input_tensors = get_tensors_by_names(self.config.input_names)
            output_tensors = get_tensors_by_names(self.config.output_names)

            self.config.session_init._setup_graph()
            # we cannot use "self.config.session_creator.create_session()" here since it finalizes the graph
            sess = tfv1.Session(config=tfv1.ConfigProto(allow_soft_placement=True))
            self.config.session_init._run_init(sess)

            dtypes = [n.dtype for n in input_tensors]

            # freeze variables to constants
            frozen_graph_def = graph_util.convert_variables_to_constants(
                sess,
                self.graph.as_graph_def(),
                [n.name[:-2] for n in output_tensors],
                variable_names_whitelist=None,
                variable_names_blacklist=None)

            # prune unused nodes from graph
            if optimize:
                toco_args = () if get_tf_version_tuple() < (1, 8) else (toco_compatible, )
                frozen_graph_def = optimize_for_inference_lib.optimize_for_inference(
                    frozen_graph_def,
                    [n.name[:-2] for n in input_tensors],
                    [n.name[:-2] for n in output_tensors],
                    [dtype.as_datatype_enum for dtype in dtypes],
                    *toco_args)

            tf.train.write_graph(frozen_graph_def, filename, 'ub6_model.pb', as_text=False)
            logger.info("Output graph written to {}.".format(filename))
            tf.train.write_graph(frozen_graph_def, filename, 'ub6_config.pbtxt', as_text=True)
            logger.info("Output graph written to {}.".format(filename))
```

**Comment by Razor1O9** [comment]
I've now used the script tools provided by tensorflow to freeze and optimize my graph. The script tools where: **freeze_graph.py** and o**ptimize_for_inference.py**.

The file size of the script based approach was identical with the file size of my functional approach. The file which was generated with the script tools throws the same exception as above.

**Comment by Razor1O9** [comment]
My non-frozen graph is about 2mb in size while my frozen graph is 173mb.
Is this normal? My optimized frozen graph is still 173mb and only loses 100kb compared to the non-optimized frozen graph.

I'm confused...

**Comment by Razor1O9** [comment]
I've uploaded my non-frozen, frozen and frozen_optimized Graphs for direct comparison:
https://mega.nz/#F!UtNS0ABR!uMTD88Yp0zsF-d1UwYPAhA

My **unfrozen and unoptimized** graph (ub6_unfrozen.pb) only has a file-size of 1Mb and as soon as I freeze it (frozen.pb), it jumps to 173mb and only loses a few kb after optimization (frozenOpt.pb).

**Comment by gadagashwini** [comment]
@Razor1O9, Please provide the Tensorflow version that your using. Thanks!

**Comment by Razor1O9** [comment]
**Thanks for the response.**

Tensorflow 1.9
OpenCV 4.1.1

**Comment by Razor1O9** [comment]
I've updated to Tensorflow 1.14 with the same result when I try to read the Model in OpenCV 4.1.1.
I either get the **nodesMapIt != nodesMap.end() in function sortByExecutionOrder** exception (when I only use the pb file) or Assertion failed in **function 'addConstNodes'** exception (when I use the pb and pbtext file).

**Step 1; Generate unfrozen graph (1mb in size)**

**Step 2; Freeze ist with freeze_graph.py (173mb in size)**
It froze 239 variables and converted them to const ops. 
The file size increased significantly 

**Step 3; Optimize graph with optimize_for_inference.py (173mb in size)**
The tool printed the following instructions for updating:
graph_util.extract_sub_graph
graph_util.remove_training_nodes

Suprisingly, the file size is only a few hundret kilobyte smaller between step 2 and step 3.

**Comment by Razor1O9** [comment]
I've added the tensorflow modelfiles (checkpoint, index etc.) to the mega link:
https://mega.nz/fm/ZwMQ3aAK

**Comment by Razor1O9** [comment]
**Closing this issue, as it has been solved:**
https://github.com/opencv/opencv/issues/16155
