### ISSUE TITLE
no attribute 'op' in keras.losses.SparseCategoricalCrossentropy

### ISSUE THREAD

**Issue by temminks** [tensorflow/tensorflow#35089]
**System information**
- OS Platform and Distribution: Jupyter on Windows 10
- TensorFlow installed from: anaconda in venv
- TensorFlow version: 2.0.0
- Python version: 3.7

**Describe the current behavior**
I'm running the example from the [tensorflow documentation for keras.losses.SparseCategoricalCrossentropy](https://www.tensorflow.org/api_docs/python/tf/keras/losses/SparseCategoricalCrossentropy) and get the error:
`'list' object has no attribute 'op'`
If we set `from_logits` to `True` it is working.

**Code to reproduce the issue**
```
cce = tf.keras.losses.SparseCategoricalCrossentropy()
loss = cce( [0, 1, 2], [[.9, .05, .05], [.5, .89, .6], [.05, .01, .94]])
```

**Comment by gowthamkpr** [comment]
@temminks This has been fixed in the latest nightly version. Please find my gist [here](https://colab.sandbox.google.com/gist/gowthamkpr/df198dee880d87c1813129452345ce5a/untitled260.ipynb). Thanks!
