### ISSUE TITLE
[DOCS] Using `>>>` in documentation is incorrectly formatted on website

### ISSUE THREAD

**Issue by Squadrick** [tensorflow/tensorflow#35085]
## URL(s) with the issue:
https://www.tensorflow.org/api_docs/python/tf/constant_initializer

## Description of issue (what needs changing):
The [example code](https://github.com/tensorflow/tensorflow/blob/1cf0898dd4331baf93fe77205550f2c2e6c90ee5/tensorflow/python/ops/init_ops_v2.py#L152) uses `>>>`, but on the website, this is incorrectly converted to `&gt;&gt;&gt;`

TF docs link: https://www.tensorflow.org/api_docs/python/tf/constant_initializer

### Submit a pull request?

This is more of a problem with how documentation is generated from comments in the python file. I don't mind taking a look if someone can point out where to get started.

**Comment by lamberta** [comment]
This looks fixed in nightly: https://www.tensorflow.org/api_docs/python/tf/constant_initializer?version=nightly
