### ISSUE TITLE
Tensorflow lite C++ standalone projects from 'generate_projects' missing sparkfun headers?

### ISSUE THREAD

**Issue by BerndHuber** [tensorflow/tensorflow#35096]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): OSX 10.14.6
- TensorFlow installed from (source or binary): source
- TensorFlow version: 1.15.0 (same observation for version 2.0), from https://github.com/tensorflow/tensorflow/releases/tag/v1.15.0
- Python version: python3
- GCC/Compiler version (if compiling from source): arm-none-eabi-g++

**Describe the problem**
The standalone projects generated with Tensorflow Lite seem to be missing some headers.

Following this tutorial: 
[https://www.tensorflow.org/lite/microcontrollers/library#generate_projects_for_other_platforms
](https://www.tensorflow.org/lite/microcontrollers/library#generate_projects_for_other_platforms
)

I run the following command (the link seems to be off here in the tutorial, as 'micro' is in another subfolder' experimental'):
`gmake -f tensorflow/lite/experimental/micro/tools/make/Makefile TARGET=sparkfun_edge generate_projects`

After this command is finished, the files are generated as expected in:
`tensorflow/lite/experimental/micro/tools/make/gen/sparkfun_edge_cortex-m4/prj`

But when trying to build the micro_speech binary like this:
```
cd tensorflow/lite/experimental/micro/tools/make/gen/sparkfun_edge_cortex-m4/prj/micro_speech/make
gmake
```

I am getting the following error:
```
arm-none-eabi-g++ -O3 -DNDEBUG -std=c++11 -g -DTF_LITE_STATIC_MEMORY -DPART_apollo3 -DAM_PACKAGE_BGA -DAM_PART_APOLLO3 -DGEMMLOWP_ALLOW_SLOW_SCALAR_FALLBACK -DTF_LITE_STATIC_MEMORY -DNDEBUG -DTF_LITE_MCU_DEBUG_LOG -D __FPU_PRESENT=1 -DARM_MATH_CM4 -fno-rtti -fmessage-length=0 -fno-exceptions -fno-unwind-tables -fno-builtin -ffunction-sections -fdata-sections -funsigned-char -MMD -mcpu=cortex-m4 -mthumb -mfpu=fpv4-sp-d16 -mfloat-abi=hard -std=gnu++11 -Wvla -Wall -Wextra -Wno-unused-parameter -Wno-missing-field-initializers -Wno-write-strings -Wno-sign-compare -fno-delete-null-pointer-checks -fomit-frame-pointer -fpermissive -nostdlib -ggdb -O3 -I. -I./third_party/gemmlowp -I./third_party/flatbuffers/include -I./third_party/kissfft  -c tensorflow/lite/experimental/micro/sparkfun_edge/debug_log.cc -o tensorflow/lite/experimental/micro/sparkfun_edge/debug_log.o
tensorflow/lite/experimental/micro/sparkfun_edge/debug_log.cc:22:10: fatal error: am_bsp.h: No such file or directory
 #include "am_bsp.h"   // NOLINT
          ^~~~~~~~~~
compilation terminated.
make: *** [tensorflow/lite/experimental/micro/sparkfun_edge/debug_log.o] Error 1
```

This is the header file of the sparkfun edge board that I want to build this for.

**Comment by amahendrakar** [comment]
@BerndHuber,
Is this still an issue? I was able to build the binaries as per the [guide](https://www.tensorflow.org/lite/microcontrollers/library#build_binaries). Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/d2a598608ca2dfd9206403095ebed6eb/35096.ipynb). Thanks!
