### ISSUE TITLE
Inconsistency with the shapes for `reduce_sum` and `reduce_logsumexp` for vectorized_map in graph mode

### ISSUE THREAD

**Issue by rrkarim** [tensorflow/tensorflow#35099]
I don't understand the cause of different handling of shapes for two methods, here is the snippet:

```python
import tensorflow as tf
import tensorflow_probability as tfp

def _log_prob(x):
    x = tf.convert_to_tensor(x, name='x')
    distribution_log_probs = [x for i in range(5)]
    cat_log_probs = [x for i in range(5)]
    final_log_probs = [
        cat_lp + d_lp
        for (cat_lp, d_lp) in zip(cat_log_probs, distribution_log_probs)
    ]
    concat_log_probs = tf.stack(final_log_probs, 0)
    log_sum = tf.reduce_logsumexp(concat_log_probs, axis=[0])
    # log_sum = tf.reduce_sum(concat_log_probs, axis=[0])
    return log_sum

@tf.function(autograph=False)
def f():
    log_prob = tf.vectorized_map(_log_prob, tf.ones((1,5)))
    print(log_prob.shape) # prints (None, 5) for `tf.reduce_logsumexp` and (1, 5) for `tf.reduce_sum`
```

So basically `tf.reduce_logsumexp` gives dynamic shape for the output tensor while `tf.reduce_sum` assigns static shape. Can anybody please give some clear picture on such behaviour and is it expected?

```
tf: 2.0.0
tfp: 0.8.0
```

**Comment by rrkarim** [comment]
#35073

**Comment by rrkarim** [comment]
I guess the problem is that v2 methods like `select_v2` are not correctly (or even not exposed) exposed in gen_math_ops. Little fix will solve the problem with `reduce_logsumexp`. Not sure if I can open PR with more detailed review of the issues with imports.

**Comment by ravikyram** [comment]
@rrkarim 

I have tried in colab with TF 2.0, 2.1.0-rc1 and was able to reproduce the issue.Please, find the gist [here](https://colab.sandbox.google.com/gist/ravikyram/61ab1f7a87eae6ac1049881313c5b7bd/untitled482.ipynb). Thanks!

**Comment by rrkarim** [comment]
@ravikyram does the PR solve the issue?

**Comment by rrkarim** [comment]
@ravikyram the previous code was merged again: [commit](https://github.com/tensorflow/tensorflow/commit/21882b67cbe63aaf1ee9c3d4e6f90d16cb08967d). Can you please give some info on it?

**Comment by junpenglao** [comment]
@dynamicwebpaige could you give us some help here? We got a few things blocked by this.

**Comment by kyleabeauchamp** [comment]
I also just encountered this issue, I was hoping to port my code from pymc3 to tensorflow but hit this.

**Comment by junpenglao** [comment]
pinging a few more folks: @derifatives @brianwa84

**Comment by brianwa84** [comment]
@agarwal-ashish 
It's a difference related to `vectorized_map`. You can see by putting `assert log_prob.shape.is_fully_defined()` that both variants have a fully defined shape w/in `_log_prob`, but that they lose it when traced by vectorized_map.

**Comment by brianwa84** [comment]
Here's my full repro against nightlies:
```python
%tensorflow_version 2.x
!pip install --upgrade pip
!python -m pip uninstall --yes tensorflow tensorflow-probability
!python -m pip install -q tf-nightly-cpu tfp-nightly
import tensorflow as tf, tensorflow_probability as tfp
print(tf.__version__, tfp.__version__)

def _log_prob(x):
    x = tf.convert_to_tensor(x, name='x')
    distribution_log_probs = [x for i in range(5)]
    cat_log_probs = [x for i in range(5)]
    final_log_probs = [
        cat_lp + d_lp
        for (cat_lp, d_lp) in zip(cat_log_probs, distribution_log_probs)
    ]
    concat_log_probs = tf.stack(final_log_probs, 0)
    log_sum = tf.reduce_logsumexp(concat_log_probs, axis=[0])
    # log_sum = tf.reduce_sum(concat_log_probs, axis=[0])
    assert log_sum.shape.is_fully_defined()
    return log_sum

@tf.function(autograph=False)
def f():
    log_prob = tf.vectorized_map(_log_prob, tf.ones((1,5)))
    print('log_prob.shape = ', log_prob.shape ) # prints (None, 5) for `tf.reduce_logsumexp` and (1, 5) for `tf.reduce_sum`

f()
```

**Comment by rrkarim** [comment]
@brianwa84 the issue was fixed before and merged: #35162 (it was built in one of the nightly builds), but then the commit was reverted due to the forward compatibility issues. I'm still not aware how the commit was breaking the forward compatibility, so that what I was asking above.

**Comment by Saduf2019** [comment]
@rrkarim 
I ran the code on tf-nightly() ,please find the [gist here](https://colab.research.google.com/gist/Saduf2019/893f242891da72b30927815e155518b4/untitled359.ipynb) and [here](https://colab.research.google.com/gist/Saduf2019/4e4daa12e3b9b53c47c246bec5a4f33e/untitled359.ipynb).

**Comment by rrkarim** [comment]
@Saduf2019 yeap, recently our PR also passed the tests so yeah (related to the inconsistency with shapes), so yeah I'm closing the issue. Thank you.
