### ISSUE TITLE
Tensorboard Embedding Projector Custom Search Bug

### ISSUE THREAD

**Issue by pujaarajan** [tensorflow/tensorflow#35105]
Context: I am using the online version of the [Tensorboard Embedding Projector](https://projector.tensorflow.org/). I uploaded my own checkpoint and metadata TSVs with 681909 rows each. I clicked on the "CUSTOM" tab, and then found a bug when I tried to search. 

Current Behavior/Bug: I am unable to click on the search bar that says "Search by". When I do click anywhere in the search bar, a drop down appears with the option "label". If I click label and try to search again, there is no difference. There is no error message.

Expected Behavior: I would be able to search, or be given an error message indicating why I'm unable to.

**Comment by oanush** [comment]
@pujaarajan ,
This looks like tensorboard related issue, could you please report issue in [Tensorboard](https://github.com/tensorflow/tensorboard/issues/new/choose) repo. Also close this issue once its reported there. Thanks!
