### ISSUE TITLE
STM32F7-Disco Hello World example fails to build

### ISSUE THREAD

**Issue by pramodjayram** [tensorflow/tensorflow#35114]
@tensorflow/micro

**System information**
- Host OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
NAME="Ubuntu"
VERSION="18.04.3 LTS"
ID=ubuntu
PRETTY_NAME="Ubuntu 18.04.3 LTS"
VERSION_ID="18.04"
Python versionL 2.7.15+
- Target platform (e.g. Arm Mbed OS, Arduino Nano 33 etc.): STM32F7-Disco and also tried on K64F based on ARM-M4

**Describe the problem**
I am attempting to build the Hello World example for the STM32F7-Disco from the following link but it is failing to build
https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/micro/examples/hello_world.

**Please provide the exact sequence of commands/steps when you ran into the problem**
make -f tensorflow/lite/micro/tools/make/Makefile TARGET=mbed TAGS="CMSIS disco_f746ng" generate_hello_world_mbed_project

cd tensorflow/lite/micro/tools/make/gen/mbed_cortex-m4/prj/hello_world/mbed

mbed config root .

mbed deploy
python -c 'import fileinput, glob;
for filename in glob.glob("mbed-os/tools/profiles/*.json"):
  for line in fileinput.input(filename, inplace=True):
    print line.replace("\"-std=gnu++98\"","\"-std=c++11\", \"-fpermissive\"")'

mbed compile -m DISCO_F746NG -t GCC_ARM

This is the error I seen before making a change to :

`Compile [ 98.7%]: arm_mult_q15.c
[Error] arm_mult_q15.c@101,6: conflicting types for 'arm_mult_q15'
[ERROR] ./tensorflow/lite/micro/tools/make/downloads/cmsis/CMSIS/DSP/Source/BasicMathFunctions/arm_mult_q15.c:101:6: error: conflicting types for 'arm_mult_q15'
 void arm_mult_q15(
      ^~~~~~~~~~~~
In file included from ./tensorflow/lite/micro/tools/make/downloads/cmsis/CMSIS/DSP/Source/BasicMathFunctions/arm_mult_q15.c:29:0:
./mbed-os/cmsis/TARGET_CORTEX_M/arm_math.h:1924:8: note: previous declaration of 'arm_mult_q15' was here
   void arm_mult_q15(
        ^~~~~~~~~~~~

[mbed] ERROR: "/usr/bin/python" returned error.
       Code: 1
       Path: "/home/pramod/tensorflow-master/tensorflow/lite/micro/tools/make/gen/mbed_cortex-m4/prj/hello_world/mbed"
       Command: "/usr/bin/python -u /home/pramod/tensorflow-master/tensorflow/lite/micro/tools/make/gen/mbed_cortex-m4/prj/hello_world/mbed/mbed-os/tools/make.py -D TF_LITE_STATIC_MEMORY -t GCC_ARM -m DISCO_F746NG --source . --build ./BUILD/DISCO_F746NG/GCC_ARM"
       Tip: You could retry the last command with "-v" flag for verbose output
`
Any help regarding this is deeply appreciated.

Thank you

**Comment by ross114** [comment]
i got the error, could anyone help to fix it

**Comment by sachinprasadhs** [comment]
Hi,
The above link which you have provided does not exists anymore, could you please try the same example mentioned in the latest version [here](https://www.tensorflow.org/lite/microcontrollers/get_started_low_level).
Feel free to open new issue if you still face an error.
