### ISSUE TITLE
Poor performance of model.fit and/or model.predict in TF 2.1.0-rc1

### ISSUE THREAD

**Issue by gdudziuk** [tensorflow/tensorflow#35124]
**System information**
- Have I written custom code: Yes
- OS Platform and Distribution: Linux Kubuntu 18.04, kernel 5.0
- Mobile device: Not verified on mobile devices
- TensorFlow installed from: binary via `pip install tensorflow-gpu`
- TensorFlow version: `2.1.0-rc1`, however affected are also `2.1.0-rc0`, `2.0.0`, `2.0.0-rc2`, `2.0.0-rc1` and `2.0.0-rc0`.
- Python version: 3.6.9
- CUDA version: 10.1 for TF 2.1.0-rc0; 10.0 for the earlier versions of TF
- cuDNN version: 7
- GPU model and memory: Nvidia GeForce GTX 1050 Ti (4GB)
- CPU model: AMD Ryzen 7 1700

**Describe the current behavior**

The code attached below works about 10x slower with TF `2.1.0-rc1` and `2.1.0-rc0` than with `1.14.0`. This code was posted earlier by @ipsec in the issue #33030 in connection with memory leaks in TF `2.0.0`. Now, in `2.1.0-rc*` the memory leaks seem fixed, but the execution of the code in question exhibits poor speed performance. Said that, the performance was even worse in `2.0.0` and pre-releases `2.0.0-rc*`, but the about 10x slowdown in `2.1.0-rc*` compared to `1.14.0` is significant.

Here I provide some more results obtained on my device:

* With TF `1.14.0`, one "episode", i.e. one iteration of the `for` loop in the below code, takes ca. 8.5-9.5 seconds in the graph execution mode and ca. 7-7.5 seconds with the eager execution enabled. The memory consumption of the Python process associated with this code is ca. 600 MB.

* With TF from `2.0.0-a0` to `2.0.0-b1` I obtain very similar results.

* With TF from `2.0.0-rc0` to `2.0.0` one episode takes ca. 120 seconds. There is also a memory leak. The memory usage after the 1st episode is ca 2 GB and is growing ca 1.5 GB per episode.

* For TF `2.1.0-rc0` and `2.1.0-rc1` the memory usage is ca. 800 MB and doesn't grow significantly from episode to episode, so the memory leak is fixed. Note that this memory usage is higher than in `1.14.0` but the difference is plausible. Nevertheless, for `2.1.0-rc0` and `2.1.0-rc1` I have measured the execution time to be ca. 75 seconds per episode, so the code execution is still very slow compared to `1.14.0`.

**Describe the expected behavior**

The code attached below should be executed in `2.1.0` comparably fast to `1.14.0`. The difference in the execution time shouldn't be 10-fold.

**Code to reproduce the issue**

This code has already been posted by @ipsec in the issue #33030. Here I only add time measuremets, change verbosity details and reduce the default number of episodes.

```python
import gym
import numpy as np
import matplotlib.pylab as plt

import tensorflow as tf
from tensorflow.keras import layers

import time

env = gym.make('NChain-v0')


def q_learning_keras(env, num_episodes=10):
    # create the keras model
    model = tf.keras.Sequential()
    model.add(layers.InputLayer(batch_input_shape=(1, 5)))
    model.add(layers.Dense(10, activation='sigmoid'))
    model.add(layers.Dense(2, activation='linear'))
    model.compile(loss='mse', optimizer='adam', metrics=['mae'])
    # now execute the q learning
    y = 0.95
    eps = 0.5
    decay_factor = 0.999
    r_avg_list = []
    for i in range(num_episodes):
        s = env.reset()
        eps *= decay_factor
        #if i % 100 == 0:
        print("Episode {} of {}".format(i + 1, num_episodes))
        t_start = time.time()
        done = False
        r_sum = 0
        while not done:
            if np.random.random() < eps:
                a = np.random.randint(0, 2)
            else:
                a = np.argmax(model.predict(np.identity(5)[s:s + 1]))
            new_s, r, done, _ = env.step(a)
            target = r + y * np.max(model.predict(np.identity(5)[new_s:new_s + 1]))
            target_vec = model.predict(np.identity(5)[s:s + 1])[0]
            target_vec[a] = target
            model.fit(np.identity(5)[s:s + 1], target_vec.reshape(-1, 2), epochs=1, verbose=0)
            s = new_s
            r_sum += r
        print("Elapsed time: {}".format(time.time()-t_start))
        r_avg_list.append(r_sum / 1000)
    plt.plot(r_avg_list)
    plt.ylabel('Average reward per game')
    plt.xlabel('Number of games')
    plt.show()
    for i in range(5):
        print("State {} - action {}".format(i, model.predict(np.identity(5)[i:i + 1])))


if __name__ == "__main__":
    q_learning_keras(env) 
```

**Comment by darsh8200** [comment]
It has to be your system problem as i ran the code on tf2.0 and it ran 1 epoch under 15 seconds which denies your 120 seconds time lapse.
![Screenshot (1)](https://user-images.githubusercontent.com/46572301/70856376-8ed56700-1f01-11ea-8e3a-4d4a6d7a979c.png)

**Comment by gdudziuk** [comment]
@darsh8200, if it happens with official Tensorflow binaries running on an officially supported system, then it is a Tensorflow problem. But thanks for checking this. Would it be a problem for you to check also if you obtain similar results with TF 1.14?

**Comment by oanush** [comment]
I Was able to reproduce the error for TF-2.0-rc1 and TF-nightly.Kindly find the [gist](https://colab.sandbox.google.com/gist/oanush/24d7f3a6b5900b87d0037cb500db0d5d/35124.ipynb) of colab.Thanks!

**Comment by Arsakes** [comment]
I've also notices disastrous performance drop between TF2.1/2.0 and 1.14/1.15.

It's hard to compare pieces of code directly since,  2x advises very differnt style of coding.
Anyways I've ported 3 vision models from legacy graph mode and with using the same input pipeline based on `tf.data.Dataset` the performance drop is goes from
1.5 - 2.9step/s 
to 0.3-0.5 step/s
I've tired eager execution, partial graph mode (one step of training with @tf.function) and full in graph mode (whole training loop in @tf.function).
At best the performance is 4 times worse.

**Comment by robieta** [comment]
If we take the above example and replace the following lines, the episode time drops from ~70 seconds to 5.5-6 seconds:

Reported:
```
...
a = np.argmax(model.predict(np.identity(5)[s:s + 1]))
...
target = r + y * np.max(model.predict(np.identity(5)[new_s:new_s + 1]))
target_vec = model.predict(np.identity(5)[s:s + 1])[0]
...
model.fit(np.identity(5)[s:s + 1], target_vec.reshape(-1, 2), epochs=1, verbose=0)
...
```

New:
```
...
a = np.argmax(model.predict_on_batch(np.identity(5)[s:s + 1]))
...
target = r + y * np.max(model.predict_on_batch(np.identity(5)[new_s:new_s + 1]))

# We call `.numpy()` because the next line performs a slice assignment on target_vec
target_vec = model.predict_on_batch(np.identity(5)[s:s + 1])[0].numpy()
...
model.train_on_batch(np.identity(5)[s:s + 1], target_vec.reshape(-1, 2))
...
```

Full [gist](https://colab.sandbox.google.com/gist/robieta/580d214431312972d47542b122f44870/copy-of-35124.ipynb) indicates that the new result matches the old result.

So what's going on here, and why is there a slowdown from 1.14? There is a detailed discussion in https://github.com/tensorflow/tensorflow/issues/33340 (including my explanation starting at https://github.com/tensorflow/tensorflow/issues/33340#issuecomment-569458253), but the high level overview is that machinery was added to the "epoch based" endpoints (`fit/evaluate/predict`) which makes them scale better, but adds some fixed overhead. And when those endpoints are called on a single batch, those instantiation overheads aren't well amortized and performance suffers. There are single batch equivalents which are more suited for the workload that you're running, but they are unfortunately less well known. There is an open action item to add a warning when fit, evaluate, or predict is used on a single batch of data. @goldiegadde for tracking.

**Comment by pavithrasv** [comment]
Thank you for taking a look Taylor!

**Comment by gdudziuk** [comment]
I can confirm that. With the changes you suggest, @robieta, I get ~13 sec/episode with TF 2.0.0 and ~4.7-4.8 sec/episode for TF 2.1.0. So I think we may close the issue.

Thank you for your explanations and the link to the other issue. It's worth reading. I knew earlier that there were methods like `predict_on_batch` and `train_on_batch`in the Keras API but I didn't know what is their intended use.

Maybe the main points of the discussion in #33340 or the high level overview that you present here could be included into the official guide? Correct me if I'm wrong but I cannot find `predict_on_batch` or `train_on_batch` even mentioned in the [tutorials](https://www.tensorflow.org/tutorials) or the [guide](https://www.tensorflow.org/guide). I'm having the impression that if one wants to really understand Tensorflow then it is necessary to study Github issues.
