### ISSUE TITLE
how to use different convolutional filter for each data in a minibatch

### ISSUE THREAD

**Issue by J-zin** [tensorflow/tensorflow#35134]
Hi,
I want to use a different convolutional filter for each data in a minibatch, that's said:
if the input images have shape: [batch_size, height, width, channel], and I want to use different filters for each image in the minibatch, so the filter shape is: [batch_size, f_width, f_height, in_channel, out_channel].  So each image in the minibatch corresponds to different filters. 

I try to solve it use tf.nn.depthwise_conv2d, but I cannot guarantee it is used in correct way. So I want to know there is some API designed for this situation?

If my statement is unclear, here is a link to the question: https://stackoverflow.com/questions/42068999/tensorflow-convolutions-with-different-filter-for-each-sample-in-the-mini-batch

**Comment by ymodak** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.
 Thanks!
