### ISSUE TITLE
clone_model changing UpSampling2D interpolation from bilinear to nearest neighbor

### ISSUE THREAD

**Issue by manicman1999** [tensorflow/tensorflow#35137]
**System information**
Windows 10 (Also happens on Ubuntu 18.04)
Installed from binary
Tensorflow-GPU 2.0.0b1
CUDA 10.0 / CuDNN 7.6
Python 3.6.8
GTX 1060 6GB (also GTX 1080 8GB)

When cloning a model using the clone_model function (AND model_from_json), upsampling interpolation switches from bilinear to nearest neighbor.

Here's some simple code which replicates the issue:

```
from tensorflow.keras.models import *
from tensorflow.keras.layers import *
import matplotlib.pyplot as plt
import numpy as np

#Make bilinear upsampling model
x = Sequential([UpSampling2D(8, interpolation = 'bilinear', input_shape = [5, 5, 3])])

#Clone model
y = clone_model(x)

#Get noise image
z = np.random.uniform(0.0, 1.0, [1, 5, 5, 3])

#X's upsampling
plt.figure(1)
plt.imshow(x.predict(z)[0])

#Y's upsampling
plt.figure(2)
plt.imshow(y.predict(z)[0])

plt.show()
```

Which outputs these two figures:
![Figure_1](https://user-images.githubusercontent.com/8140937/70866792-a3325780-1f33-11ea-99e1-53eff1a8f015.png)
![Figure_2](https://user-images.githubusercontent.com/8140937/70866791-a3325780-1f33-11ea-893c-fe95fafe8f0f.png)

**Comment by gadagashwini** [comment]
@manicman1999, I tried with Tensorflow-gpu 2.0 it outputs as expected. Please find the gist [here](https://colab.sandbox.google.com/gist/gadagashwini/15cb7ad955be9cd66dfc115c03f5eb3a/untitled309.ipynb). Thanks!
