### ISSUE TITLE
mnist data download failure

### ISSUE THREAD

**Issue by rogeryuchao** [tensorflow/tensorflow#35130]
When I use 
from tensorflow.examples.tutorials.mnist import input_data
mnist = input_data.read_data_sets("/tmp/mnist/", one_hot = True)

It seems that I cannot download the gz files from the googleapis? Error as below
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749)>

Then I manually visit the source site, also error xml replied as below:
<Error>
<Code>AccessDenied</Code>
<Message>Access denied.</Message>
<Details>
Anonymous caller does not have storage.objects.get access to cvdf-datasets/mnist.
</Details>
</Error>

So how can I fix the problem? Thanks a lot.

**Comment by ravikyram** [comment]
Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version. Also, did you compile from source or install a binary?

Also, can you go through the [link1](https://github.com/tensorflow/tensorflow/issues/10779) , [link2 ](https://github.com/ageron/handson-ml/issues/59) and[ link3](https://github.com/tensorflow/models/issues/5871) and see if it helps you. Thanks!

**Comment by rogeryuchao** [comment]
Sir     I think it's the problem for China only.  I tried to manually download it by whether and everything went well already.  So you may close the ticket and thank you for your support. Best RegardRoger Yu发自我的华为手机-------- 原始邮件 --------发件人： ravikyram <notifications@github.com>日期： 2019年12月16日周一 下午2:17收件人： tensorflow/tensorflow <tensorflow@noreply.github.com>抄送： rogeryuchao <18501790682@163.com>, Author <author@noreply.github.com>主    题： Re: [tensorflow/tensorflow] mnist data download failure (#35130)Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version. Also, did you compile from source or install a binary?
Also, can you go through the link1 , link2  and link3 and see if it helps you. Thanks!

**Comment by ravikyram** [comment]
@rogeryuchao 

I am closing the issue   since the query is been resolved. Thanks!
