### ISSUE TITLE
Size not changed when convert pb file to tflite file

### ISSUE THREAD

**Issue by lccssr** [tensorflow/tensorflow#35147]
I tried to convert my quantized pb file to tflite file. 
My code is:
import tensorflow as tf

from tensorflow import lite
FLAGS = tf.app.flags.FLAGS
inputs=["input_images"]
outputs=["output_1"]
converter = lite.TFLiteConverter.from_frozen_graph(
    graph_def_file='./q/te.pb',
    input_arrays=inputs,
    output_arrays=outputs
)
#converter.post_training_quantize = False
converter.inference_input_type = lite.constants.QUANTIZED_UINT8
input_arrays = converter.get_input_arrays()
converter.quantized_input_stats = {input_arrays[0]:(0, 255)}
converter.default_ranges_stats = (0, 255)
tflite_quantized_model = converter.convert()
with open('te.tflite', 'wb') as f:
    f.write(tflite_quantized_model)

The pb was frozen by a model that had already been quantized by "create_training_graph" and "create_eval_graph". The size of my pb file is 83.45MB and the size of my tflite file is 83.15MB. How can I sovle this problem? I just want to quantize my pb file and get a smaller size file.

**Comment by ymodak** [comment]
You may try full integer quantization of weights and activations to reduce your file size.
```python
converter.optimizations = [tf.lite.Optimize.DEFAULT]
```
See https://www.tensorflow.org/lite/convert/quantization
