### ISSUE TITLE
Reading checkpoint file fail will ignore all checkpoints

### ISSUE THREAD

**Issue by zakar** [tensorflow/tensorflow#35148]
When restoring a checkpoint, if it read checkpoint file fail then all checkpoints will be ignored and train from scratch. I think it should throw exception rather than ignore, otherwise it will train from scratch silently. Especially read fail could happen when using distributed storage.

![image](https://user-images.githubusercontent.com/1125780/70891780-ea4b4600-2022-11ea-9ae0-fcf4572b1997.png)

Link to the code:
https://github.com/tensorflow/tensorflow/blob/r2.1/tensorflow/python/training/checkpoint_management.py#L287

**Comment by allenlavoie** [comment]
I'd just check whether <dir>/checkpoint exists. If it does and that function returns None, you can throw an exception. Otherwise you can use the parsed proto.

Throwing new exceptions here isn't backward compatible.
