### ISSUE TITLE
 How to package My MFCC modules 

### ISSUE THREAD

**Issue by fmbao** [tensorflow/tensorflow#35145]
@tensorflow/micro
I want to package the MFCC into my model tflite. like this(tensorflow/lite/android/conv_actions_frozen.tflite)
But I build my own keras layer. And conert to tflite.The Model is a mess where the MFCC func.Why ?

**Comment by MeghnaNatraj** [comment]
Hello, please answer the following questions and if possible, code to re-produce the results.

-  Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): 
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version (use command below):
- Python version:
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:
- Code, if any, to reproduce the results (eg: links to github repo, colab or jupyter notebook, etc)

**Comment by MeghnaNatraj** [comment]
Closing the issue as we have not received a response. Re-open and provide more information to help us debug the issue.
