### ISSUE TITLE
Building from source: ERROR: kernels:training_ops

### ISSUE THREAD

**Issue by lbarosi** [tensorflow/tensorflow#35142]
**System information**
- **Linux Ubuntu 18.04**
- TensorFlow installed from (source or binary): **source**
- TensorFlow version: v2 (master)
- Python version: python 3.7.5
- Installed using virtualenv? conda:  conda 4.7.12
- Bazel version (if compiling from source): **bazel 1.1.0**
- GCC/Compiler version (if compiling from source): **gcc 8.3.0**
- CUDA/cuDNN version: **CUDA 10.2/cuDNN7.6.5**
- GPU model and memory: GeForce GTX670 4035Mb
- CPU Intel i7860@2.80GHz
- Kernel  Linux-headers-4.15.0-73
- NVCC -  v2.5.6, for CUDA 10.2, Nov 19,2019

**Describe the problem**

It seems Bazel Build is disregarding my choice of **NOT INSTALLING XLA**.

I installed CUDA and cuDNN, NCCL, created a python 3.7.5 environment and decided to build tensorflow from MASTER branch since my  GPU has capabilities 3.0 and the other installs I tried, from docker or conda, where complaining about a minimum capability of 3.5.

There were plenty of documentation for the need of a build from source for 3.0 capability and I decided to do it. 

From git I realized it was necessary to disable XLA. `./configure` asked for **XLA** capabitity and I answered **N** (Y was the default), it correctly detected python, cuda and gcc, I wrote **3.0** for desired capability, (A message showed me the need to disable XLA, what I already did). 

When I did the bazel build it took a huge lot of time and seemed to freeze with something like the piece below.
````bash
./tensorflow/compiler/xla/service/hlo_computation.h:562:3: note: in expansion of macro ‘TF_RET_CHECK’
   TF_RET_CHECK(order.size() == instruction_count());
   ^~~~~~~~~~~~
./tensorflow/compiler/xla/service/hlo_computation.h: In instantiation of ‘tensorflow::Status xla::HloComputation::AcceptOrdered(xla::DfsHloVisitorBase<HloInstructionPtr>*, absl::Span<xla::HloInstruction* const>) const [with HloInstructionPtr = const xla::HloInstruction*]’:
./tensorflow/compiler/xla/service/hlo_computation.h:588:61:   required from here
./tensorflow/compiler/xla/service/hlo_computation.h:562:29: warning: comparison of integer expressions of different signedness: ‘absl::Span<xla::HloInstruction* const>::size_type’ {aka ‘long unsigned int’} and ‘tensorflow::int64’ {aka ‘long long int’} [-Wsign-compare]
   TF_RET_CHECK(order.size() == instruction_count());
./tensorflow/core/platform/macros.h:87:47: note: in definition of macro ‘TF_PREDICT_FALSE’
 #define TF_PREDICT_FALSE(x) (__builtin_expect(x, 0))
                                               ^
./tensorflow/compiler/xla/service/hlo_computation.h:562:3: note: in expansion of macro ‘TF_RET_CHECK’
   TF_RET_CHECK(order.size() == instruction_count());
   ^~~~~~~~~~~~
./tensorflow/compiler/xla/array.h: In instantiation of ‘tensorflow::int64 xla::Array<T>::dim(tensorflow::int64) const [with T = int; tensorflow::int64 = long long int]’:

````

**Provide the exact sequence of commands / steps that you executed before running into the problem**
````bash 
bazel build --config=opt -- config=--local_ram_resources=6000  --cxxopt="-D_GLIBCXX_USE_CXX11_ABI=0" --config=cuda //tensorflow/tools/pip_package:build_pip_package
````

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.
The pieces showing the actual error ocurrered as follows:
````
ERROR: /home/lbarosi/Pythonia/tensorflow/tensorflow/core/kernels/BUILD:5735:1: C++ compilation of rule '//tensorflow/core/kernels:training_ops' failed (Exit 1)
x86_64-linux-gnu-gcc-8: fatal error: Killed signal terminated program cc1plus
compilation terminated.
Target //tensorflow/tools/pip_package:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.
ERROR: /home/lbarosi/Pythonia/tensorflow/tensorflow/python/tools/BUILD:141:1 C++ compilation of rule '//tensorflow/core/kernels:training_ops' failed (Exit 1)
INFO: Elapsed time: 4520.437s, Critical Path: 1586.97s
INFO: 5492 processes: 5492 local.
FAILED: Build did NOT complete successfully

````

Any help is appreciated. I would like to try as much as possible to stick with this configurations without downgradings of CUDA or cuDNN.

**Comment by myaldiz** [comment]
I am having same issue when I try to build Tensorflow 2.3.0 in Jetson Nano using Docker.
```Dockerfile
RUN cd ~ \
  && git clone --recursive --branch "v2.3.0-rc0" https://github.com/tensorflow/tensorflow.git

RUN cd ~/tensorflow \
  && PYTHON_BIN_PATH=$(which python3) \
  PYTHON_LIB_PATH=$(python3 -c 'import site; print(site.getsitepackages()[0])') \
  TF_NEED_OPENCL_SYCL=0 \
  TF_NEED_OPENCL=0 \
  TF_NEED_ROCM=0 \
  TF_NEED_CUDA=1 \
  TF_NEED_TENSORRT=1 \
  TF_CUDA_VERSION=10.2 \
  TF_TENSORRT_VERSION=7 \
  CUDA_TOOLKIT_PATH=/usr/local/cuda \
  CUDNN_INSTALL_PATH=/usr/lib/aarch64-linux-gnu \
  TENSORRT_INSTALL_PATH=/usr/lib/aarch64-linux-gnu \
  TF_CUDA_COMPUTE_CAPABILITIES=5.3 \
  TF_CUDA_CLANG=0 \
  TF_NEED_IGNITE=0 \
  TF_ENABLE_XLA=0 \
  TF_NEED_MPI=0 \
  GCC_HOST_COMPILER_PATH=$(which gcc) \
  CC_OPT_FLAGS="-march=native" \
  TF_SET_ANDROID_WORKSPACE=0 \
  ./configure \
  && bazel build --config=opt --config=cuda --config=noaws \
   --config=nogcp --local_ram_resources=3000 //tensorflow/tools/pip_package:build_pip_package
```

```
ERROR: /root/tensorflow/tensorflow/core/kernels/BUILD:6109:1: C++ compilation of rule '//tensorflow/core/kernels:training_ops' failed (Exit 1)
aarch64-linux-gnu-gcc-8: fatal error: Killed signal terminated program cc1plus
compilation terminated.
Target //tensorflow/tools/pip_package:build_pip_package failed to build
```
Any insights on what the problem is about?

**Comment by lbarosi** [comment]
Your problem is slightly differente @myaldiz. With CUDA capabilities 5.3 you may not need to compile at all, there is still hope for you. Though it seems clear that bazel is actually having problems with options. (Have you tryed enabling XLA to see if it works?)

**Comment by bachi76** [comment]
@lbarosi did you find a way to make it work with a capability 3.0 GPU? I'm right now in the same position. Noticed that the TF 2.3 configure script doesn't even ask if XLA support is desired.

**Comment by lbarosi** [comment]
Quite a long time to answer, but I gave up. Moving to newer GPU.

**Comment by lbarosi** [comment]
I am closing this issue for lack of support and interest.
