### ISSUE TITLE
micro_speech example inference issue

### ISSUE THREAD

**Issue by rayeh5** [tensorflow/tensorflow#35143]
@tensorflow/micro

**System information**
- Host OS Platform and Distribution
      Answer: Linux Ubuntu 16.04
- TensorFlow installed from (source or binary):
     Answer: source
- Tensorflow version (commit SHA if source):
- Target platform (e.g. Arm Mbed OS, Arduino Nano 33 etc.):
    Answer: x86
**Describe the problem**
   I build the x86 version of micro_speech example, run it with the g_yes_1000ms_sample_data file, but the result is "Heard silence (0)", it should be "yes"
**Please provide the exact sequence of commands/steps when you ran into the problem**
   1. mkdir x86 under micro/examples/micro_speech directory
   2. in the x86 folder, add "command_responder.cc":
void RespondToCommand(tflite::ErrorReporter* error_reporter,
                      int32_t current_time, const char* found_command,
                      uint8_t score, bool is_new_command) {
  //if (is_new_command) {
    error_reporter->Report("Heard %s (%d) @%dms", found_command, score,
                           current_time);
    sleep(2);
  //}
}
   3. in the x86 folder, add audio_provider.cc:
TfLiteStatus GetAudioSamples(tflite::ErrorReporter* error_reporter,
                             int start_ms, int duration_ms,
                             int* audio_samples_size, int16_t** audio_samples) {

  const int yes_start = (0 * kAudioSampleFrequency) / 1000;
  const int yes_end = (1000 * kAudioSampleFrequency) / 1000;
  const int wraparound = (1000 * kAudioSampleFrequency) / 1000;
  const int start_sample = (start_ms * kAudioSampleFrequency) / 1000;
  for (int i = 0; i < kMaxAudioSampleSize; ++i) {
    const int sample_index = (start_sample + i) % wraparound;
    int16_t sample;
    sample = g_yes_1000ms_sample_data[sample_index - yes_start];
    g_dummy_audio_data[i] = sample;
  }
  *audio_samples_size = kMaxAudioSampleSize;
  *audio_samples = g_dummy_audio_data;

  return kTfLiteOk;
}

int32_t LatestAudioTimestamp()
{
     // This is how we let the outside world know that new audio data has arrived.
     g_latest_audio_timestamp += 1000;
    return g_latest_audio_timestamp;
}

4. build the example:
make -f tensorflow/lite/experimental/micro/tools/make/Makefile TARGET=x86 micro_speech
5. run the example:
   [~/tf-20191211/tensorflow-master/tensorflow/lite/experimental/micro/tools/make/gen/x86_x86_64/bin]./micro_speech
   start_ms=40 duration_ms=30
   start_ms=60 duration_ms=30
   start_ms=80 duration_ms=30
 ...
   Heard silence (0) @1000ms

actually, the result is the same when I port this example to my EVB.
By the way, why the start_ms begin with 40 instead of 0?

Thanks for your support.

ruey-an

**Comment by rayeh5** [comment]
I may find the reason.
It should be caused by setting of RecognizeCommands(), after change the setting as below:
  explicit RecognizeCommands(tflite::ErrorReporter* error_reporter,
                             int32_t average_window_duration_ms = 0,
                             uint8_t detection_threshold = 0,
                             int32_t suppression_ms = 0,
                             int32_t minimum_count = 0);
the result is correct now.

**Comment by sbu75** [comment]
@rayeh5,
Did your code run several times correct for the word 'no' for me not, only for 'yes' it is working. 
Could you point me where my error is. Tried several Things but believe Audio Input and tensowork isn't in sync.
Did you find the cause?
Thanks for any Feedback.
