### ISSUE TITLE
Are there related APIs to determine savedmodel  whether batch is supported?

### ISSUE THREAD

**Issue by zxgm** [tensorflow/tensorflow#35153]
There have a savedmodel format model,have some method or API to judge that is support batch?

**Comment by gadagashwini** [comment]
@zxgm, Please refer this [link](https://www.tensorflow.org/guide/saved_model). Thanks!

**Comment by gadagashwini** [comment]
@zxgm, Was the link resolved your issue.Thanks!

**Comment by zxgm** [comment]
The ide not resolve my problem, but I have found other method.Thanks a lot!!!
