### ISSUE TITLE
SavedModelBundle.getSignatures() does not return outputs in correct order.

### ISSUE THREAD

**Issue by vcarpani** [tensorflow/tensorflow#35150]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Arch Linux
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.1.0.rc0
- Python version: 3.8
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: Not relevant
- GPU model and memory: Not relevant

**Describe the current behavior**
Loading a SavedModel in C++, the outputs (and probably also inputs, but I do not have models with multiple inputs) from the signature are returned in a random order, which then causes the network to fail when used for inference.

**Describe the expected behavior**
The outputs (and probably inputs) should be returned in the correct order.

**Code to reproduce the issue**
```
std::string model_dir = "/path/to/my_model";
std::vector<string> input_names;
std::vector<string> output_names;
tensorflow::SavedModelBundleLite bundle; // Same with SavedModelBundle

// Create default options.
tensorflow::SessionOptions session_options;
tensorflow::RunOptions run_options;

// Load model.
auto status = tensorflow::LoadSavedModel(
	session_options,
	run_options,
	model_dir,
	{tensorflow::kSavedModelTagServe},
	&bundle
);

// Check if model has been loaded correctly.
if (!status.ok()) {
	std::cerr << status.ToString() << std::endl;
	return;
}

// Get model signature.
auto signatures = bundle.GetSignatures();
if (!signatures.contains("serving_default")) {
	std::cerr << "Could not find serving_default in model signatures." << std::endl;
	return;
}

// Get the inputs names.
for (auto const & input : signatures.at("serving_default").inputs()) {
	input_names.push_back(input.second.name());
}

// Get the outputs names.
for (auto const & output : signatures.at("serving_default").outputs()) {
	output_names.push_back(output.second.name());
}
std::vector<tensorflow::Tensor>  inputs = getMyInputs();  // Some compatible input vector.
std::vector<tensorflow::Tensor>  outputs;

// Create a vector of pairs for associating inputs to their names.
std::vector<std::pair<std::string, tensorflow::Tensor>> input_pairs;
for (std::size_t i = 0; i < inputs.size(); ++i) {
	input_pairs.push_back({input_names.at(i), inputs.at(i)});
}

// Run the network.
bundle.GetSession()->Run(
	input_pairs,
	output_names,
	{},
	&outputs
);
```

When running this the output order changes, giving a mismatch error (eg. `Check failed: dtype() == expected_dtype (3 vs. 1) float expected, got int32`) after calling `Run`.

**Comment by vcarpani** [comment]
Bump?

**Comment by vcarpani** [comment]
Any news on this?

**Comment by vcarpani** [comment]
Bump?

**Comment by sushreebarsa** [comment]
@vcarpani We see that you are using older version of tensorflow .Many bug have been fixed in latest version. We recommend that you upgrade to latest stable version of tensorflow 2.6.0 and let us know if the issue still persists in newer versions .Thanks!

**Comment by vcarpani** [comment]
Hello @sushreebarsa, I have changed my implementation, so I am not using this function anymore, closing the issue.
