### ISSUE TITLE
Item assigment

### ISSUE THREAD

**Issue by sweetxiaoqizi** [tensorflow/tensorflow#35156]
I really want to know why tf can't support item assigment like numpy

**Comment by dubesar** [comment]
In general, a TensorFlow tensor object is not assignable*, so you cannot use it on the left-hand side of an assignment.
Another way you can do it like this.
```python3
aa=tf.Variable(tf.zeros(3, tf.int32))
aa=aa[2].assign(1)
```
then the output is:
```
array([0, 0, 1], dtype=int32)
```

**Comment by gadagashwini** [comment]
@sweetxiaoqizi, Did @dubesar's suggestion solved your issue. Thanks!

**Comment by gadagashwini** [comment]
@sweetxiaoqizi, Is this still an issue!

**Comment by gadagashwini** [comment]
Looks like issue is resolved. Feel free to reopen if issue still persists. Thanks!
