### ISSUE TITLE
Cannot train keras model with 2 outputs

### ISSUE THREAD

**Issue by ongoing0217** [tensorflow/tensorflow#35154]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10 Family
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.0.0
- Python version: 3.6.6
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 10 / 7.6.4
- GPU model and memory: GeForce 940M

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**

`import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.layers import Dense, Input
from tensorflow.keras import Model`

A tf.keras model is created with 2 output heads:

`inputs=Input(shape=(20))
x=Dense(32, activation='relu')(inputs)
output1=Dense(3, activation='softmax')(x)
output2=Dense(6, activation='softmax')(x)

model=Model(inputs=inputs, outputs=[output1, output2])
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])`

Then an arbitary sized training sample is created:

`labels=tf.constant([[0 for i in range(50)],[1 for i in range(50)]], shape=[50,2])

sample=[]
for i in range(20):
    if i%2==0:
        sample.append(0)
    else: sample.append(1)

data=tf.constant([sample for i in range(50)], shape=[50,20])`

When the data is called for training,

`model.fit(data, labels, epochs=1, batch_size=5)`

 an error occurs saying that the module expected 2 arrays, but when I swap out the validation dataset with a pair of 2 arrays:

`model.fit(data, (labels1, labels2), epochs=1, batch_size=5)`

another error pops up saying that the x and y dimensions must be the same. To put simply, keras thinks that the pair of validation outputs is an array.

**Describe the expected behavior**
The model.fit method runs and the model is trained for 1 epoch with 50 samples.

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.
copy the above code in order, with the last model.fit method not usable.

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.
`Traceback (most recent call last):
  File "C:\Users\admin\Desktop\working as intended\CONSTANTINOPLE\test\test duo output.py", line 25, in <module>
    model.fit(data, labels, epochs=1, batch_size=8)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow_core\python\keras\engine\training.py", line 728, in fit
    use_multiprocessing=use_multiprocessing)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow_core\python\keras\engine\training_v2.py", line 224, in fit
    distribution_strategy=strategy)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow_core\python\keras\engine\training_v2.py", line 547, in _process_training_inputs
    use_multiprocessing=use_multiprocessing)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow_core\python\keras\engine\training_v2.py", line 594, in _process_inputs
    steps=steps)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow_core\python\keras\engine\training.py", line 2519, in _standardize_user_data
    exception_prefix='target')
  File "C:\Users\admin\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow_core\python\keras\engine\training_utils.py", line 531, in standardize_input_data
    str(len(data)) + ' arrays: ' + str(data)[:200] + '...')
ValueError: Error when checking model target: the list of Numpy arrays that you are passing to your model is not the size the model expected. Expected to see 2 array(s), but instead got the following list of 1 arrays: [<tf.Tensor: id=286, shape=(50, 2), dtype=int32, numpy=
array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0...`

**Comment by darsh8200** [comment]
in model.fit() you don't need to include the batch_size as per my opinion use the callbacks if defined, let me show you an example by attaching a .
![Screenshot (2)](https://user-images.githubusercontent.com/46572301/70909745-1f13c900-2034-11ea-8f1e-47497457b184.png)
ipynb file of code

**Comment by ongoing0217** [comment]
@darsh8200 I don't think you are getting what I was asking. I wanted to ask about how to train a network with 2 output heads. And also the batch size variable is arbitary and can be removed in this case.

**Comment by pandrey-fr** [comment]
Hi,

To make the model training work, you need to pass labels as a list of two tensors (each associated with one of the outputs), _i.e._ `model.fit(x, [y1, y2])` with `x` of shape `(n, 20)`, `y1` of shape `(n,)` and `y2` of shape `(n,)` (note that you could also add a dimension for batch-size, but that is another topic).

If I go back to your initial definition of `data` and `labels` as two Tensors of respective shapes `(50, 20)` and `(50, 2)`, you can run : `model.fit(data, [labels[:, 0], labels[:, 1]], epochs=1, batch_size=5)`.

I hope this helps :)

**Comment by ongoing0217** [comment]
@pandrey-fr I used your code and with some tweaking, the code ran flawlessly. I didn't know you can write grammar like `labels[:, 0]` before, seems like I have more stuff to learn :D Thanks for the help, apperciate it

**Comment by pandrey-fr** [comment]
@ongoing0217 You are welcome ! The use of slice notation is only valid in Eager execution, so you should use it with parsimony, but it can be useful in debugging contexts :)
