### ISSUE TITLE
Caching to file instead of memory of tf.data.dataset using 2 map functions with cache(filename) in between and (x, y) tuple not working

### ISSUE THREAD

**Issue by josdewitte** [tensorflow/tensorflow#35157]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
Windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
None
- TensorFlow installed from (source or binary):
binary
- TensorFlow version (use command below):
2.0
- Python version:
3.6.8
- Bazel version (if compiling from source):
none
- GCC/Compiler version (if compiling from source):
none
- CUDA/cuDNN version:
none
- GPU model and memory:
none

map(), then caching a dataset of (image shape (224,224,3), and one_hot_encoded class index shape (n)) and subsequent map() works when simply using cache(); however when using file-based caching (which I need because of large dataset) using cache('cache.tmp') fails with the following error:
(I tried making the one-hot same type as image shape (float64) instead of int32 but does not help)
Also not using a tuple but array gives same error.

First I create dataset using tuple: (array of file names (str), array of class indices (str)) 
Then in map( lambda x, y : return (load_image(x) (float64 (224,224,3)), tf.one_hot(int(y), self.class_count, dtype=tf.float64))

afterwards when cache('cache.tmp'); and using a second .map(lambda x, y : return (preprocess(x), y))
the error is produced

Call stack:

14:09:27.225818: W tensorflow/core/framework/op_kernel.cc:1622] OP_REQUIRES failed at iterator_ops.cc:929 : Invalid argument: {{function_node __inference_Dataset_map_preprocess_10622}} Expects arg[1] to be double but string is provided
Traceback (most recent call last):
    x, y = next(dataset_iterator)
  File "C:\Python36\lib\site-packages\tensorflow_core\python\data\ops\iterator_ops.py", line 622, in __next__
    return self.next()
  File "C:\Python36\lib\site-packages\tensorflow_core\python\data\ops\iterator_ops.py", line 666, in next
    return self._next_internal()
  File "C:\Python36\lib\site-packages\tensorflow_core\python\data\ops\iterator_ops.py", line 651, in _next_internal
    output_shapes=self._flat_output_shapes)
  File "C:\Python36\lib\site-packages\tensorflow_core\python\ops\gen_dataset_ops.py", line 2672, in iterator_get_next_sync
    _six.raise_from(_core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.InvalidArgumentError: {{function_node __inference_Dataset_map_preprocess_10622}} Expects arg[1] to be double but string is provided [Op:IteratorGetNextSync]

**Describe the expected behavior**
Successful caching of dataset

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by gadagashwini** [comment]
@josdewitte, Could you provide the standalone code snippet to replicate the issue. Thanks!

**Comment by josdewitte** [comment]
@gadagashwini, deleted the cache files manually this morning; now I cannot reproduce the issue. Maybe you can verify that these files are cleaned up on every dataset.cache(filename) locations. Should we close this ?

**Comment by gadagashwini** [comment]
@josdewitte, If issue is no longer exist we can close this. Thanks!
