### ISSUE TITLE
Language Modeling: Test Sentence Probability

### ISSUE THREAD

**Issue by pranjaldaga** [tensorflow/tensorflow#3515]
I have trained and saved an RNN model using the tutorial given [here in the Tensorflow docs](https://www.tensorflow.org/versions/r0.9/tutorials/recurrent/index.html). I want to evaluate this model by finding **log probability of each test sentence**. I would really appreciate if someone can help me out with this.
Thanks!

**Comment by vrv** [comment]
Hi, this is a question more appropriate to StackOverflow.
