### ISSUE TITLE
TypeError: Tensor is unhashable if Tensor equality is enabled. Instead, use tensor.experimental_ref() as the key.

### ISSUE THREAD

**Issue by ShibaPrasad** [tensorflow/tensorflow#35164]
**Describe the problem**
I am having the the below problem
TypeError: Tensor is unhashable if Tensor equality is enabled. Instead, use tensor.experimental_ref() as the key.

**Provide the exact sequence of commands / steps that you executed before running into the problem**

gen_optimizer = tf.keras.optimizers.Adam(1e-3, beta_1=0.5)
disc_optimizer = tf.keras.optimizers.RMSprop(1e-3)
    
# model
model = VAEGAN(
    enc = encoder,
    dec = decoder,
    vae_disc_function = vaegan_discrim,
    lr_base_gen = 1e-3, # 
    lr_base_disc = 1e-4, # the discriminator's job is easier than the generators so make the learning rate lower
    latent_loss_div=1, # this variable will depend on your dataset - choose a number that will bring your latent loss to ~1-10
    sig_mult = 10, # how binary the discriminator's learning rate is shifted (we squash it with a sigmoid)
    recon_loss_div = .001, # this variable will depend on your dataset - choose a number that will bring your latent loss to ~1-10
)

model.train(example_data)

**Any other info / logs**
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-11-2112af51db2e> in <module>
----> 1 model.train(example_data)

<ipython-input-6-94ca8f8e5589> in train(self, x)
     93 
     94     def train(self, x):
---> 95         enc_gradients, dec_gradients, disc_gradients = self.compute_gradients(x)
     96         self.apply_gradients(enc_gradients, dec_gradients, disc_gradients)
     97 

<ipython-input-6-94ca8f8e5589> in compute_gradients(self, x)
     74     def compute_gradients(self, x):
     75         with tf.GradientTape() as enc_tape, tf.GradientTape() as dec_tape, tf.GradientTape() as disc_tape:
---> 76             (_, latent_loss, discrim_layer_recon_loss, gen_fake_loss, disc_fake_loss, disc_real_loss,) = self.compute_loss(x)
     77 
     78             enc_loss = latent_loss + discrim_layer_recon_loss

<ipython-input-6-94ca8f8e5589> in compute_loss(self, x)
     48         # pass through network
     49         q_z = self.dist_encode(x)
---> 50         z = q_z.sample()
     51         p_z = ds.MultivariateNormalDiag(loc=[0.0] * z.shape[-1], scale_diag=[1.0] * z.shape[-1])
     52         xg = self.decode(z)

~/anaconda3/lib/python3.7/site-packages/tensorflow_probability/python/distributions/distribution.py in sample(self, sample_shape, seed, name, **kwargs)
    838       samples: a `Tensor` with prepended dimensions `sample_shape`.
    839     """
--> 840     return self._call_sample_n(sample_shape, seed, name, **kwargs)
    841 
    842   def _call_log_prob(self, value, name, **kwargs):

~/anaconda3/lib/python3.7/site-packages/tensorflow_probability/python/distributions/transformed_distribution.py in _call_sample_n(self, sample_shape, seed, name, **kwargs)
    389       # work, it is imperative that this is the last modification to the
    390       # returned result.
--> 391       y = self.bijector.forward(x, **bijector_kwargs)
    392       y = self._set_sample_static_shape(y, sample_shape)
    393 

~/anaconda3/lib/python3.7/site-packages/tensorflow_probability/python/bijectors/bijector.py in forward(self, x, name, **kwargs)
    931       NotImplementedError: if `_forward` is not implemented.
    932     """
--> 933     return self._call_forward(x, name, **kwargs)
    934 
    935   def _inverse(self, y):

~/anaconda3/lib/python3.7/site-packages/tensorflow_probability/python/bijectors/bijector.py in _call_forward(self, x, name, **kwargs)
    902       if not self._is_injective:  # No caching for non-injective
    903         return self._forward(x, **kwargs)
--> 904       mapping = self._lookup(x=x, kwargs=kwargs)
    905       if mapping.y is not None:
    906         return mapping.y

~/anaconda3/lib/python3.7/site-packages/tensorflow_probability/python/bijectors/bijector.py in _lookup(self, x, y, kwargs)
   1341     if x is not None:
   1342       # We removed x at caching time. Add it back if we lookup successfully.
-> 1343       mapping = self._from_x[x].get(subkey, mapping).merge(x=x)
   1344     if y is not None:
   1345       # We removed y at caching time. Add it back if we lookup successfully.

~/anaconda3/lib/python3.7/site-packages/tensorflow_probability/python/bijectors/bijector.py in __getitem__(self, key)
    149   def __getitem__(self, key):
    150     weak_key = HashableWeakRef(key, lambda w: self.pop(w, None))
--> 151     return super(WeakKeyDefaultDict, self).__getitem__(weak_key)
    152 
    153   # This is the "DefaultDict" part.

~/anaconda3/lib/python3.7/site-packages/tensorflow_probability/python/bijectors/bijector.py in __hash__(self)
    179     x = self()
    180     if not isinstance(x, np.ndarray):
--> 181       return hash(x)
    182     # Note: The following logic can never be reached by the public API because
    183     # the bijector base class always calls `convert_to_tensor` before accessing

~/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py in __hash__(self)
    711     if (Tensor._USE_EQUALITY and executing_eagerly_outside_functions() and
    712         (g is None or g._building_function)):  # pylint: disable=protected-access
--> 713       raise TypeError("Tensor is unhashable if Tensor equality is enabled. "
    714                       "Instead, use tensor.experimental_ref() as the key.")
    715     else:

TypeError: Tensor is unhashable if Tensor equality is enabled. Instead, use tensor.experimental_ref() as the key.

**Comment by gadagashwini** [comment]
@ShibaPrasad, Please provide the complete code and Tenosrflow version to replicate the reported issue here. Thanks!

**Comment by gadagashwini** [comment]
@ShibaPrasad, Any update on this issue!

**Comment by shaunster0** [comment]
I'm getting this too, using a gpu on Colab

**Comment by gadagashwini** [comment]
@shaunster0, Can you share the colab gist here to analyze the issue. Thanks!

**Comment by gadagashwini** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Comment by stephenwithav** [comment]
Hi @gadagashwini!  I'm having this problem, too.

I'm following along with the code linked in this article:

https://blog.tensorflow.org/2019/03/variational-autoencoders-with.html

...but using TF 2.x.

https://colab.research.google.com/drive/1HonWNUBQaecB4GHAAGiVP6YBUDc33qOF

The error occurs when defining the encoder:

```python
encoder = tfk.Sequential([
    tfkl.InputLayer(input_shape=input_shape),
    tfkl.Lambda(lambda x: tf.cast(x, tf.float32) - 0.5),
    tfkl.Conv2D(base_depth, 5, strides=1,
                padding='same', activation=tf.nn.leaky_relu),
    tfkl.Conv2D(base_depth, 5, strides=2,
                padding='same', activation=tf.nn.leaky_relu),
    tfkl.Conv2D(2 * base_depth, 5, strides=1,
                padding='same', activation=tf.nn.leaky_relu),
    tfkl.Conv2D(2 * base_depth, 5, strides=2,
                padding='same', activation=tf.nn.leaky_relu),
    tfkl.Conv2D(4 * encoded_size, 7, strides=1,
                padding='valid', activation=tf.nn.leaky_relu),
    tfkl.Flatten(),
    tfkl.Dense(tfpl.MultivariateNormalTriL.params_size(encoded_size),
               activation=None),
    tfpl.MultivariateNormalTriL(
        encoded_size,
        activity_regularizer=tfpl.KLDivergenceRegularizer(prior)),
])
```

```
TypeError                                 Traceback (most recent call last)
<ipython-input-10-f26eb36ef5f5> in <module>()
     17     tfpl.MultivariateNormalTriL(
     18         encoded_size,
---> 19         activity_regularizer=tfpl.KLDivergenceRegularizer(prior)),
     20 ])
     21 
```

```
TypeError: in converted code:

    /usr/local/lib/python3.6/dist-packages/tensorflow_probability/python/layers/distribution_layer.py:212 call
        inputs, *args, **kwargs)
    /tensorflow-2.1.0/python3.6/tensorflow_core/python/keras/layers/core.py:846 call
        result = self.function(inputs, **kwargs)
    /usr/local/lib/python3.6/dist-packages/tensorflow_probability/python/layers/distribution_layer.py:160 _fn
        d = make_distribution_fn(*fargs, **fkwargs)
    /usr/local/lib/python3.6/dist-packages/tensorflow_probability/python/layers/distribution_layer.py:343 <lambda>
        lambda t: MultivariateNormalTriL.new(t, event_size, validate_args),
    /usr/local/lib/python3.6/dist-packages/tensorflow_probability/python/layers/distribution_layer.py:358 new
        scale_tril=scale_tril(params[..., event_size:]),
    /usr/local/lib/python3.6/dist-packages/tensorflow_probability/python/bijectors/bijector.py:803 __call__
        return self._call_forward(value, name=name or "forward", **kwargs)
    /usr/local/lib/python3.6/dist-packages/tensorflow_probability/python/bijectors/bijector.py:904 _call_forward
        mapping = self._lookup(x=x, kwargs=kwargs)
    /usr/local/lib/python3.6/dist-packages/tensorflow_probability/python/bijectors/bijector.py:1343 _lookup
        mapping = self._from_x[x].get(subkey, mapping).merge(x=x)
    /usr/local/lib/python3.6/dist-packages/tensorflow_probability/python/bijectors/bijector.py:151 __getitem__
        return super(WeakKeyDefaultDict, self).__getitem__(weak_key)
    /usr/local/lib/python3.6/dist-packages/tensorflow_probability/python/bijectors/bijector.py:181 __hash__
        return hash(x)
    /tensorflow-2.1.0/python3.6/tensorflow_core/python/framework/ops.py:705 __hash__
        raise TypeError("Tensor is unhashable if Tensor equality is enabled. "

    TypeError: Tensor is unhashable if Tensor equality is enabled. Instead, use tensor.experimental_ref() as the key.
```

Does this help or should I create a new issue?

**Comment by gadagashwini** [comment]
@stephenwithav, Can you open new issue with filling issue [Template](https://github.com/tensorflow/tensorflow/issues/new/choose) and include the colab gist also. Thanks!
