### ISSUE TITLE
TensorFlow Lite C++ image classification demo result error

### ISSUE THREAD

**Issue by jianlongf** [tensorflow/tensorflow#35169]
I follow the guidelines of TensorFlow Lite C++ image classification demo. Firstly I clone TensorFlow and use to build label_image for Android armv8 by bazel 1.2.1.

> bazel build -c opt --cxxopt=-std=c++11 --config=android_arm64 \
>   //tensorflow/lite/examples/label_image:label_image

When I run the sample in the guide. I got the error result like below:

> Loaded model ./mobilenet_v1_1.0_224.tflite
> resolved reporter
> INFO: Initialized TensorFlow Lite runtime.
> invoked
> average time: 52.036 ms
> -nan: 1000 1000:toilet tissue, toilet paper, bathroom tissue
> -nan: 999 999:ear, spike, capitulum
> -nan: 998 998:bolete
> -nan: 997 997:hen-of-the-woods, hen of the woods, Polyporus frondosus, Grifola frondosa
> -nan: 996 996:earthstar

According to the guide, the right result is below:

> Loaded model /tmp/mobilenet_v1_1.0_224.tflite
> resolved reporter
> invoked
> average time: 68.12 ms
> 0.860174: 653 653:military uniform
> 0.0481017: 907 907:Windsor tie
> 0.00786704: 466 466:bulletproof vest
> 0.00644932: 514 514:cornet, horn, trumpet, trump
> 0.00608029: 543 543:drumstick

BTW, The TensorFlow version is the latest commit of the master.
`
commit 27e6c7b49f4558dfc4bd59a9c492bf4f390a77da
Author: A. Unique TensorFlower <gardener@tensorflow.org>
Date:   Mon Dec 16 01:03:06 2019 -0800

    compat: Update forward compatibility horizon to 2019-12-16

    PiperOrigin-RevId: 285720630
    Change-Id: Ib744d5f7de70a6c6d73dd1a386712e404d0c2b99
`

**Comment by jianlongf** [comment]
I got the right result by checkout the tag v2.0.0

> Loaded model ./mobilenet_v1_1.0_224.tflite
> resolved reporter
> INFO: Initialized TensorFlow Lite runtime.
> invoked
> average time: 76.076 ms
> 0.860174: 653 653:military uniform
> 0.048102: 907 907:Windsor tie
> 0.00786704: 466 466:bulletproof vest
> 0.00644931: 514 514:cornet, horn, trumpet, trump
> 0.0060803: 543 543:drumstick
>

**Comment by ymodak** [comment]
Closing this issue since its resolved. Thanks!
