### ISSUE TITLE
missing symbols from c++ API

### ISSUE THREAD

**Issue by robosina** [tensorflow/tensorflow#35178]
**System information**
- OS Platform: Windows10
- TensorFlow installed from:source
- TensorFlow version:1.13.0
- Python version: NO
- Bazel version (if compiling from source):0.19
- GCC/Compiler version: msvc14

**Describe the problem**
I want to build tensorflow from the source using the below command 
`bazel build -c opt  --config=mkl --config=monolithic --linkopt="/FORCE:MULTIPLE" --define=no_tensorflow_py_deps=true //tensorflow:libtensorflow_cc.so //tensorflow:install_headers   //tensorflow/tools/lib_package:libtensorflow --verbose_failures`

However after the dll file generated, some symbol is not inside of the dll, I will paste some of this error in here(As far as I know this problem is accured because number of symbol is limited in windows, So all functions in tensorflow source can't be exported( I _check the exported function using dumpbin.exe /EXPORT and it's weird because only 3000 symbols is exported )_
`tfwrapper.obj : error LNK2001: unresolved external symbol "class tensorflow::Output __cdecl tensorflow::ops::Const(class tensorflow::Scope const &,struct tensorflow::Input::Initializer const &)" (?Const@ops@tensorflow@@YA?AVOutput@2@AEBVScope@2@AEBUInitializer@Input@2@@Z)`

`tfwrapper.obj : error LNK2001: unresolved external symbol "public: __cdecl tensorflow::ops::DecodePng::DecodePng(class tensorflow::Scope const &,class tensorflow::Input,struct tensorflow::ops::DecodePng::Attrs const &)" (??0DecodePng@ops@tensorflow@@QEAA@AEBVScope@2@VInput@2@AEBUAttrs@012@@Z)`

`tfwrapper.obj : error LNK2001: unresolved external symbol "public: __cdecl tensorflow::ops::Placeholder::Placeholder(class tensorflow::Scope const &,enum tensorflow::DataType)" (??0Placeholder@ops@tensorflow@@QEAA@AEBVScope@2@W4DataType@2@@Z)`

and for solving this issue I work on two idea
 **first one** is using `def_file_filter.py.tpl`, as may you know in this file I have to add missed symbol to it like below(I just paste some of them in here) and reconfigure & recompile the source(I guess). But this solution can't export any of this missing symbol for me

     # Header for the def file.
     def_fp.write("LIBRARY " + args.target + "\n")
    def_fp.write("EXPORTS\n")
    def_fp.write("\t ??1OpDef@tensorflow@@UEAA@XZ\n")
	def_fp.write("\t ??0DecodePng@ops@tensorflow@@QEAA@AEBVScope@2@VInput@2@AEBUAttrs@012@@Z\n")
	def_fp.write("\t ??6tensorflow@@YAAEAV?$basic_ostream@DU?$char_traits@D@std@@@std@@AEAV12@AEBVStatus@0@@Z\n")`

So, I can't solve my problem using this method. So I use another Idea that I got this Idea from `ashley tharp` (you can see her great work in this[ link](https://github.com/robosina/stuff/tree/master/ai/tensorflow/build_tensorflow_1.14_source_for_Windows)) and this workaround solve 8 of this problems. Main idea of her is to add `TF_EXPORT` macro to the function names to force symbol to include in the dll file. but my problem is raised in the DecodePng file, there is a function in tensorflow source ->`tensorflow/core/kernels/decode_image_op.cc` the function signature is 
     
     void DecodePng(OpKernelContext* context, StringPiece input)
 I can't find any other. But in examples of the tensorflow we will see this way to read png files

    image_reader = DecodePng(root.WithOpName("png_reader"), file_reader,
                             DecodePng::Channels(wanted_channels));
this two function is not same and I couldn't find this function in the tensorflow source code so I can't add `TF_EXPORT` macro to it, but how it is possible to use a function that is not present in source code?? So I look in the bazel genereated files and this function is in there.(it is in `bazel-source/bazel-out/x64_windows-opt/genfiles/tensorflow/cc/ops/image_ops.h`)

     DecodePng(const ::tensorflow::Scope& scope, ::tensorflow::Input contents);
     DecodePng(const ::tensorflow::Scope& scope, ::tensorflow::Input contents, const
          DecodePng::Attrs& attrs);

 I don't know exactly how bazel created it and how to add `TF_EXPORT` macro to it(because this files is machine generated files and you can't add TF_EXPORT to it, because it will be overwritten in compile time)

**Comment by NeoZhangJianyu** [comment]
@robosina 
Sorry, it's long time no answer this issue.

Is the issue still present?

**Comment by robosina** [comment]
@NeoZhangJianyu , unfortunately no, I tried so many ways but I can't resolve these errors.

**Comment by NeoZhangJianyu** [comment]
@robosina 
Is your case changed now? like TF & bazel version?

What's the current version of the building target? And could you share your build cmd and error log?

**Comment by robosina** [comment]
@NeoZhangJianyu Since I can't use tensorflow and it didn't give me proper performance on cpu, I have changed my framework to Pytorch as it has simpler API in c++!

**Comment by NeoZhangJianyu** [comment]
@robosina 
OK! I understand.

Do you think this issue could be continued or closed?

**Comment by NeoZhangJianyu** [comment]
@robosina 
Thank you very much!
