### ISSUE TITLE
Upgrading Boringssl Version in TensorFlow

### ISSUE THREAD

**Issue by abhay1722** [tensorflow/tensorflow#35179]
I am trying to build Tensorflow using latest Boringssl. However, facing compilation issues.
Is there any plan to upgrade the Boringssl commit currently being used in TensorFlow to a recent commit?

**Comment by yongtang** [comment]
Created PR #35196 with the upgrade of boringssl

**Comment by abhay1722** [comment]
Issue being tracked in the PR https://github.com/tensorflow/tensorflow/pull/35196.
