### ISSUE TITLE
TypeError when using boolean_mask to evaluate hessian matrix

### ISSUE THREAD

**Issue by husisy** [tensorflow/tensorflow#35172]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes (see code snippet below)
- OS Platform and Distribution: both on win10 and Linux Ubuntu 18.04
- TensorFlow installed from: binary (via `pip install tensorflow`)
- TensorFlow version (use command below): `2.0.0`
- Python version: `3.7.3`
- CUDA/cuDNN version: not applicable
- GPU model and memory: not applicable

**minimum code to reproduce the issue**

```Python
import numpy as np
import tensorflow as tf
hfe = lambda x,y: np.max(np.abs(x-y)/(np.abs(x)+np.abs(y)+1e-3))
N0 = 3
np0 = np.random.randn(N0)
np2 = np.sum(np0**3)
hessian_np0 = np.diag(6*np0) #the correct hessian via numpy
tf0 = tf.constant(np0)
with tf.GradientTape() as tape0:
    tape0.watch(tf0)
    with tf.GradientTape() as tape1:
        tape1.watch(tf0)
        # tf1 = tf0 # @label-0 pass 
        # tf1 = tf.gather(tf0*1, tf.range(N0)) # @label-1 pass
        tf1 = tf.boolean_mask(tf0, tf.ones(N0, dtype=tf.bool)) # @label-2 fail TypeError
        tf2 = tf.math.reduce_sum(tf1**3)
    grad_tf0 = tape1.gradient(tf2, tf0)
hessian_tf0 = tape0.jacobian(grad_tf0, tf0) #the hessian via tensorflow
print('relative error:: np vs tf', hfe(hessian_np0, hessian_tf0.numpy()))
```

**current behavior**: both `@label-0 @label-1 @label-2` (see comments in the code snippet) could give the correct `tf1` (just identical with `tf0`), but only `@label-0 @label-1` could give the correct hessian matrix as `hessian_np0` (second order derivative), `@label-2` will raise `TypeError` (see attached [traceback.log](https://github.com/tensorflow/tensorflow/files/3971266/traceback.log))

**expected behavior**: `@label-0 @label-1 @label-2` should give the same hessian matrix

**Comment by oanush** [comment]
@husisy ,
When tried running the code in TF-nightly issue seemed to be fixed, kindly refer the [gist](https://colab.sandbox.google.com/gist/oanush/4bf90fdcc8ae193ff478b2fac353474f/35172.ipynb) of colab.Thanks!

**Comment by husisy** [comment]
> @husisy ,
> When tried running the code in `TF-nightly `issue seemed to be fixed, kindly refer the [gist](https://colab.sandbox.google.com/gist/oanush/4bf90fdcc8ae193ff478b2fac353474f/35172.ipynb) of colab.Thanks!

many thanks.
