### ISSUE TITLE
Error when running distributed MNIST example

### ISSUE THREAD

**Issue by lliu25** [tensorflow/tensorflow#3517]
Hi I am new to tensorflow and distributed tensorflow. I was trying to run an example from #2726 

Right now I am using tensorflow 0.9 on a cluster of Raspberry Pi3, using slurm to manage the nodes in the cluster, the script is below:
#!/bin/bash

#SBATCH -N 4
#SBATCH --nodelist=piw[25-28]

node1=piw25
node2=piw26
node3=piw27
node4=piw28

#On node1:
srun -N 1 -n 1 python mnist_yetanother.py \
     --ps_hosts=$node1:2223 \
     --worker_hosts=$node2:2223,$node3:2223,$node4:2223 \
     --job_name=ps --task_index=0 &
#On node2:
srun -N 1 -n 1 python mnist_yetanother.py \
     --ps_hosts=$node1:2223 \
     --worker_hosts=$node2:2223,$node3:2223,$node4:2223 \
     --job_name=worker --task_index=0 &
#On node3:
srun -N 1 -n 1 python mnist_yetanother.py \
     --ps_hosts=$node1:2223 \
     --worker_hosts=$node2:2223,$node3:2223,$node4:2223 \
     --job_name=worker --task_index=1 &
#On node4:
srun -N 1 -n 1 python mnist_yetanother.py \
     --ps_hosts=$node1:2223 \
     --worker_hosts=$node2:2223,$node3:2223,$node4:2223 \
     --job_name=worker --task_index=2
wait

And this is the error message:

I tensorflow/core/distributed_runtime/rpc/grpc_channel.cc:206] Initialize HostPortsGrpcChannelCache for job ps -> {piw25:2223}
I tensorflow/core/distributed_runtime/rpc/grpc_channel.cc:206] Initialize HostPortsGrpcChannelCache for job worker -> {piw26:2223, piw27:2223, localhost:2223}
I tensorflow/core/distributed_runtime/rpc/grpc_channel.cc:206] Initialize HostPortsGrpcChannelCache for job ps -> {localhost:2223}
I tensorflow/core/distributed_runtime/rpc/grpc_channel.cc:206] Initialize HostPortsGrpcChannelCache for job worker -> {piw26:2223, piw27:2223, piw28:2223}
I tensorflow/core/distributed_runtime/rpc/grpc_server_lib.cc:202] Started server with target: grpc://localhost:2223
I tensorflow/core/distributed_runtime/rpc/grpc_server_lib.cc:202] Started server with target: grpc://localhost:2223
I tensorflow/core/distributed_runtime/rpc/grpc_channel.cc:206] Initialize HostPortsGrpcChannelCache for job ps -> {piw25:2223}
I tensorflow/core/distributed_runtime/rpc/grpc_channel.cc:206] Initialize HostPortsGrpcChannelCache for job ps -> {piw25:2223}
I tensorflow/core/distributed_runtime/rpc/grpc_channel.cc:206] Initialize HostPortsGrpcChannelCache for job worker -> {localhost:2223, piw27:2223, piw28:2223}
I tensorflow/core/distributed_runtime/rpc/grpc_server_lib.cc:202] Started server with target: grpc://localhost:2223
I tensorflow/core/distributed_runtime/rpc/grpc_channel.cc:206] Initialize HostPortsGrpcChannelCache for job worker -> {piw26:2223, localhost:2223, piw28:2223}
I tensorflow/core/distributed_runtime/rpc/grpc_server_lib.cc:202] Started server with target: grpc://localhost:2223
Extracting data/train-images-idx3-ubyte.gz
Extracting data/train-labels-idx1-ubyte.gz
Extracting data/t10k-images-idx3-ubyte.gz
Extracting data/t10k-labels-idx1-ubyte.gz
Initialized!
Traceback (most recent call last):
  File "mnist_yetanother.py", line 351, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 30, in run
    sys.exit(main(sys.argv))
  File "mnist_yetanother.py", line 310, in main
    with sv.prepare_or_wait_for_session(server.target, config=None) as sess:
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/supervisor.py", line 684, in prepare_or_wait_for_session
    init_feed_dict=self._init_feed_dict, init_fn=self._init_fn)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/session_manager.py", line 176, in prepare_session
    sess.run(init_op, feed_dict=init_feed_dict)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 372, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 636, in _run
    feed_dict_string, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 708, in _do_run
    target_list, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 728, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors.InvalidArgumentError: /job:worker/replica:0/task:0/cpu:0 unknown device.
	 [[Node: truncated_normal_2_S5 = _Recv[client_terminated=false, recv_device="/job:ps/replica:0/task:0/cpu:0", send_device="/job:worker/replica:0/task:0/cpu:0", send_device_incarnation=-8305312558883263444, tensor_name="edge_62_truncated_normal_2", tensor_type=DT_FLOAT, _device="/job:ps/replica:0/task:0/cpu:0"]()]]
srun: error: piw28: task 0: Exited with exit code 1
E0726 15:08:58.966743325   10814 tcp_client_posix.c:173]     failed to connect to 'ipv4:192.168.50.38:2223': socket error: connection refused
E tensorflow/core/distributed_runtime/master.cc:202] Master init: Unavailable: 
E0726 15:09:04.384147901   10819 tcp_client_posix.c:191]     failed to connect to 'ipv4:192.168.50.38:2223': timeout occurred
E0726 15:09:09.463843371   10814 tcp_client_posix.c:191]     failed to connect to 'ipv4:192.168.50.38:2223': timeout occurred
E0726 15:09:18.410973793   10820 tcp_client_posix.c:191]     failed to connect to 'ipv4:192.168.50.38:2223': timeout occurred
E0726 15:09:29.903416857   10814 tcp_client_posix.c:173]     failed to connect to 'ipv4:192.168.50.38:2223': socket error: connection refused
E tensorflow/core/distributed_runtime/master.cc:202] Master init: Unavailable: 
E0726 15:10:00.977546704   10814 tcp_client_posix.c:173]     failed to connect to 'ipv4:192.168.50.38:2223': socket error: connection refused
E0726 15:10:47.956032631   10814 tcp_client_posix.c:191]     failed to connect to 'ipv4:192.168.50.38:2223': timeout occurred
E0726 15:11:48.090654174   10814 tcp_client_posix.c:191]     failed to connect to 'ipv4:192.168.50.38:2223': timeout occurred
E0726 15:13:21.260355773   10814 tcp_client_posix.c:191]     failed to connect to 'ipv4:192.168.50.38:2223': timeout occurred
E0726 15:15:21.261626939   10814 tcp_client_posix.c:191]     failed to connect to 'ipv4:192.168.50.38:2223': timeout occurred
E0726 15:17:21.263101653   10819 tcp_client_posix.c:191]     failed to connect to 'ipv4:192.168.50.38:2223': timeout occurred
E0726 15:19:21.264292261   10814 tcp_client_posix.c:191]     failed to connect to 'ipv4:192.168.50.38:2223': timeout occurred
E0726 15:21:21.265185108   10820 tcp_client_posix.c:191]     failed to connect to 'ipv4:192.168.50.38:2223': timeout occurred
E0726 15:23:21.265939820   10801 tcp_client_posix.c:191]     failed to connect to 'ipv4:192.168.50.38:2223': timeout occurred

I killed the program after a while. I'm not sure why I would get "[Node: truncated_normal_2_S5 = _Recv[client_terminated=false, recv_device="/job:ps/replica:0/task:0/cpu:0", send_device="/job:worker/replica:0/task:0/cpu:0", send_device_incarnation=-8305312558883263444, tensor_name="edge_62_truncated_normal_2", tensor_type=DT_FLOAT, _device="/job:ps/replica:0/task:0/cpu:0"]()]" such error message. Searching online does not help too much...

Any help or advice will be greatly appreciated!

**Comment by michaelisard** [comment]
I think the relevant part of the message is 'Error: /job:worker/replica:0/task:0/cpu:0 unknown device.' Could you include mnist_yetanother.py as well to make sure you are setting up the [cluster spec](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/g3doc/how_tos/distributed/index.md) correctly?

**Comment by lliu25** [comment]
Hi @michaelisard thank you for your reply, I used exactly the same code as in #2726, so the setup of cluster spec remains the same. Although I did try to hard code the assignment of the node into the code, still the same error.

**Comment by mrry** [comment]
Looking at your log output (and slightly unjumbling it), it appears that the ClusterSpec is appropriately configured:

```
# Presumably worker 2:
I tensorflow/core/distributed_runtime/rpc/grpc_channel.cc:206] Initialize HostPortsGrpcChannelCache for job ps -> {piw25:2223}
I tensorflow/core/distributed_runtime/rpc/grpc_channel.cc:206] Initialize HostPortsGrpcChannelCache for job worker -> {piw26:2223, piw27:2223, localhost:2223}
# Presumably the PS:
I tensorflow/core/distributed_runtime/rpc/grpc_channel.cc:206] Initialize HostPortsGrpcChannelCache for job ps -> {localhost:2223}
I tensorflow/core/distributed_runtime/rpc/grpc_channel.cc:206] Initialize HostPortsGrpcChannelCache for job worker -> {piw26:2223, piw27:2223, piw28:2223}
# [...]
# Presumably worker 0:
I tensorflow/core/distributed_runtime/rpc/grpc_channel.cc:206] Initialize HostPortsGrpcChannelCache for job ps -> {piw25:2223}
I tensorflow/core/distributed_runtime/rpc/grpc_channel.cc:206] Initialize HostPortsGrpcChannelCache for job worker -> {localhost:2223, piw27:2223, piw28:2223}
# Presumably worker 1:
I tensorflow/core/distributed_runtime/rpc/grpc_channel.cc:206] Initialize HostPortsGrpcChannelCache for job ps -> {piw25:2223}
I tensorflow/core/distributed_runtime/rpc/grpc_channel.cc:206] Initialize HostPortsGrpcChannelCache for job worker -> {piw26:2223, localhost:2223, piw28:2223}
```

However, the error you are seeing appears to be a result of misconfiguration: one worker is making a request to the process that it *believes* is worker 0, but the receiving process does not have the appropriate device (and so presumbly is actually a *different* worker).

How is your DNS configured for the cluster? Is it possible that one of the hosts has a different mapping for `piw26` than the others (or than the cluster manager)?

**Comment by lliu25** [comment]
Hi @mrry the cluster is set up to use /etc/hosts for hostname resolution within the cluster. We switched to use the IP addresses of the nodes and we ran into the same error. I'm skeptical if the error message is caused by 

> tensorflow.python.framework.errors.InvalidArgumentError: /job:worker/replica:0/task:0/cpu:0 unknown device.
[[Node: truncated_normal_2_S5 = _Recvclient_terminated=false, recv_device="/job:ps/replica:0/task:0/cpu:0", send_device="/job:worker/replica:0/task:0/cpu:0", send_device_incarnation=-8305312558883263444, tensor_name="edge_62_truncated_normal_2", tensor_type=DT_FLOAT, _device="/job:ps/replica:0/task:0/cpu:0"]]

Something related to truncated_normal as the input argument?

Thank you for your reply!

**Comment by mrry** [comment]
Do you have the ability to recompile from source? I can think of a small patch that would make it easier to diagnose the problem.

(I don't think it's related to the particular use of `truncated_normal`, and it still seems like an address misconfiguration to me, although using IP addresses rules out DNS misconfiguration.)

**Comment by lliu25** [comment]
@mrry inspired us to check if the tasks are running on the designated nodes. We now changed the way of assigning the nodes, and now it's working! thanks a lot!!!

The script is shown below:
#!/bin/bash

#SBATCH -N 4
#SBATCH --nodelist=piw[25-28]

node1=piw25
node2=piw26
node3=piw27
node4=piw28

# On node1:
srun --nodelist=piw25 -N 1 -n 1 python mnist_yetanother.py \
     --ps_hosts=$node1:2223 \
     --worker_hosts=$node2:2223,$node3:2223,$node4:2223 \
     --job_name=ps --task_index=0 &
# On node2:
srun --nodelist=piw26 -N 1 -n 1 python mnist_yetanother.py \
     --ps_hosts=$node1:2223 \
     --worker_hosts=$node2:2223,$node3:2223,$node4:2223 \
     --job_name=worker --task_index=0 &
# On node3:
srun --nodelist=piw27 -N 1 -n 1 python mnist_yetanother.py \
     --ps_hosts=$node1:2223 \
     --worker_hosts=$node2:2223,$node3:2223,$node4:2223 \
     --job_name=worker --task_index=1 &
# On node4:
srun --nodelist=piw28 -N 1 -n 1 python mnist_yetanother.py \
     --ps_hosts=$node1:2223 \
     --worker_hosts=$node2:2223,$node3:2223,$node4:2223 \
     --job_name=worker --task_index=2
wait

**Comment by mrry** [comment]
Glad to hear it! So - just for my understanding - was the problem that Slurm was assigning some tasks to the same nodes? (or assigning them in a non-deterministic order?)

**Comment by lliu25** [comment]
I don't think this is caused by slurm assigning tasks to the same nodes. As long as the tasks are specified to each node specifically they can run correctly. I have run into the situation where some tasks assigned to the same node, I will try to post that error message later, different from what I post here.

**Comment by lliu25** [comment]
When I accidentally tried to assign several tasks to the same node, I got the following error message:
I tensorflow/core/distributed_runtime/rpc/grpc_channel.cc:206] Initialize HostPortsGrpcChannelCache for job ps -> {192.168.50.35:2223}
I tensorflow/core/distributed_runtime/rpc/grpc_channel.cc:206] Initialize HostPortsGrpcChannelCache for job worker -> {192.168.50.36:2223, 192.168.50.37:2223, localhost:2223}
I tensorflow/core/distributed_runtime/rpc/grpc_server_lib.cc:202] Started server with target: grpc://localhost:2223
E0727 11:38:35.762428930   22857 tcp_server_posix.c:284]     bind addr=[::]:2223: Address already in use
srun: error: piw25: task 0: Segmentation fault
E0727 11:38:35.762761220   22857 server_chttp2.c:119]        No address added out of total 1 resolved
E0727 11:38:37.724595086   21952 tcp_server_posix.c:284]     bind addr=[::]:2223: Address already in use
srun: error: piw27: task 0: Segmentation fault
E0727 11:38:37.725087528   21952 server_chttp2.c:119]        No address added out of total 1 resolved
E0727 11:38:37.822318646   23426 tcp_server_posix.c:284]     bind addr=[::]:2223: Address already in use
E0727 11:38:37.822415468   23426 server_chttp2.c:119]        No address added out of total 1 resolved
srun: error: piw26: task 0: Segmentation fault
slurmstepd: error: *** STEP 626.1 CANCELLED AT 2016-07-27T11:40:22 *** on piw28
srun: got SIGCONT
slurmstepd: error: *** JOB 626 CANCELLED AT 2016-07-27T11:40:22 *** on piw25
srun: Job step aborted: Waiting up to 2 seconds for job step to finish.

So it told me the address that I tried to access is already in use.

**Comment by qingzew** [comment]
so I have the same problem, but with different port, anyone has solve it?
