### ISSUE TITLE
TypeError: Tensor is unhashable if Tensor equality is enabled. Instead, use tensor.experimental_ref() as the key.

### ISSUE THREAD

**Issue by joshnarani9** [tensorflow/tensorflow#35184]
from tensorflow.keras.applications.inception_v3 import InceptionV3
model = InceptionV3(weights='imagenet')
model_new = Model(model.input, model.layers[-2].output)

**after running the above line i got the below error:**

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-50-8b5bbb7c43a4> in <module>
      1 # Create a new model, by removing the last layer (output layer) from the inception v3
----> 2 model_new = Model(model.input, model.layers[-2].output)

~\Anaconda3\lib\site-packages\keras\legacy\interfaces.py in wrapper(*args, **kwargs)
     89                 warnings.warn('Update your `' + object_name + '` call to the ' +
     90                               'Keras 2 API: ' + signature, stacklevel=2)
---> 91             return func(*args, **kwargs)
     92         wrapper._original_function = func
     93         return wrapper

~\Anaconda3\lib\site-packages\keras\engine\network.py in __init__(self, *args, **kwargs)
     91                 'inputs' in kwargs and 'outputs' in kwargs):
     92             # Graph network
---> 93             self._init_graph_network(*args, **kwargs)
     94         else:
     95             # Subclassed network

~\Anaconda3\lib\site-packages\keras\engine\network.py in _init_graph_network(self, inputs, outputs, name)
    145         # User-provided argument validation.
    146         # Check for redundancy in inputs.
--> 147         if len(set(self.inputs)) != len(self.inputs):
    148             raise ValueError('The list of inputs passed to the model '
    149                              'is redundant. '

~\Anaconda3\lib\site-packages\tensorflow_core\python\framework\ops.py in __hash__(self)
    711     if (Tensor._USE_EQUALITY and executing_eagerly_outside_functions() and
    712         (g is None or g._building_function)):  # pylint: disable=protected-access
--> 713       raise TypeError("Tensor is unhashable if Tensor equality is enabled. "
    714                       "Instead, use tensor.experimental_ref() as the key.")
    715     else:

TypeError: Tensor is unhashable if Tensor equality is enabled. Instead, use tensor.experimental_ref() as the key.

**Comment by ravikyram** [comment]
@joshnarani9 

Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version. Also, did you compile from source or install a binary?

Request you to provide minimal standalone code to reproduce the issue in our environment. It helps us in localizing the issue faster.If you are unclear what to include see the issue template displayed in [the Github new issue template](https://github.com/tensorflow/tensorflow/issues/new/choose).

We ask for this in the issue submission template, because it is really difficult to help without that information. Thanks!

**Comment by ymodak** [comment]
I was able to run your script successfully in TF 1.15 and TF 2.1.0-rc1. Can you please confirm your TF version? Additionally if using TF Probability, may state its version too?
```python
from tensorflow.keras.applications.inception_v3 import InceptionV3
from tensorflow.keras import Model
model = InceptionV3(weights='imagenet')
model_new = Model(model.input, model.layers[-2].output)
```

**Comment by joshnarani9** [comment]
Keras=2.0.5
Tensorflow=1.14.0

**Comment by ymodak** [comment]
Please switch to latest keras version (Keras 2.2.5) and try again. Try creating a virtual environment with updated Keras and TF versions.
