### ISSUE TITLE
Windows build failed - Internal compiler error Visual Studio 2017 - FAILED: Build did NOT complete successfully

### ISSUE THREAD

**Issue by giaxxi** [tensorflow/tensorflow#35180]
**System information**
- OS Platform and Distribution: Windows 7 Professional SP1 64 bit
- TensorFlow installed from (source or binary): source
- TensorFlow version: tensorflow-master (downloaded 18/12/2019)
- Python version: 3.7
- Installed using virtualenv? pip? conda?: YES, conda
- Bazel version (if compiling from source): 1.1.0
- GCC/Compiler version (if compiling from source): MSVC 14.16.27023 (Visual Studio 2017)
- CUDA/cuDNN version: build for CPU
- GPU model and memory: (Quadro K200M)

**Describe the problem**
Followed this guide: https://www.tensorflow.org/install/source_windows and just build failed.
I tested different combinations (https://www.tensorflow.org/install/source_windows#cpu) and I was just able to compile just the **r1.14 successfully**, by the way.
**r2.0** failed with the same message as master.
But back to master release.

**Provide the exact sequence of commands / steps that you executed before running into the problem**

- Donwloaded the `tensorflow-master.zip` from github
- Installed Bazel version 1.1.0
- cmd to folder `\tensorflow-master`
- `activate python37 environment` (conda)
- Set env var for bazel: `set BAZEL_VC=C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC`
- Check Bazel version
```
(python37) C:\Users\username\bin\tensorflow-master>bazel --version
bazel 1.1.0
```
- Configure
```
(python37) C:\Users\ username\bin\tensorflow-master>python ./configure.py
You have bazel 1.1.0 installed.
Please specify the location of python. [Default is C:\Users\ username\Anaconda3\envs\python37\python.exe]:

Found possible Python library paths:
  C:\Users\ username\Anaconda3\envs\python37\lib\site-packages
Please input the desired Python library path to use.  Default is [C:\Users\ username\Anaconda3\envs\python37\lib\site-packages]

Do you wish to build TensorFlow with XLA JIT support? [y/N]: n
No XLA JIT support will be enabled for TensorFlow.

Do you wish to build TensorFlow with ROCm support? [y/N]: n
No ROCm support will be enabled for TensorFlow.

Do you wish to build TensorFlow with CUDA support? [y/N]: n
No CUDA support will be enabled for TensorFlow.

Please specify optimization flags to use during compilation when bazel option "--config=opt" is specified [Default is /arch:AVX]:

Would you like to override eigen strong inline for some C++ compilation to reduce the compilation time? [Y/n]: y
Eigen strong inline overridden.
```
- Launch the compilation: `bazel build //tensorflow:tensorflow_cc.lib`
- After time elapsed the process ended with: `FAILED: Build did NOT complete successfully`

**Any other info / logs**
Just attaching the last rows of the terminal messages

Message has Italian chunks of which I'm trying to provide a translation here:
```
note: vedere il riferimento all'istanza '<Sconosciuto>' della funzione <Sconosciuto> di cui è in corso la compilazione
note: check the reference to instance '<Unknown>' of the function <Unknown> which is compiling
```

```
Errore interno del compilatore in C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\bin\HostX64\x64\cl.exe. Verrà richiesto di inviare una segnalazione errori a Microsoft in un momento successivo.
Internal error of the compiler in C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\bin\HostX64\x64\cl.exe. It will be required to send an error report to Microsoft next.
```

```
ERRORE INTERNO DEL COMPILATORE in 'C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\bin\HostX64\x64\cl.exe' Per altre informazioni, scegliere Supporto tecnico dal menu ? di Visual C++ o aprire il file della Guida relativo al supporto tecnico
INTERNAL ERROR OF THE COMPILER in 'C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\bin\HostX64\x64\cl.exe' For more information, choose Technical support from ? menu of Visual C++ or open the file from the guide related with technical support
```

[tensorflow-master-build-fail-log.txt](https://github.com/tensorflow/tensorflow/files/3971998/tensorflow-master-build-fail-log.txt)

**Comment by gunan** [comment]
Looks like a compiler bug to me?
@angerson could you loop in sig-build to see if they can help?

**Comment by sanatmpa1** [comment]
@giaxxi,

Can you try building the latest stable version of tensorflow i.e `2.6.0` and lets us know if the issue still persists? You can follow this [guide](https://www.tensorflow.org/install/source_windows) to build from source. Thanks!
