### ISSUE TITLE
ModuleNotFoundError: No module named 'tensorflow.contrib'

### ISSUE THREAD

**Issue by MrRex42** [tensorflow/tensorflow#35197]
Hello, I'm trying to use TF but I have an issue...
When I run my code I have :

    import tflearn
  File "//anaconda3/lib/python3.7/site-packages/tflearn/__init__.py", line 4, in <module>
    from . import config
  File "//anaconda3/lib/python3.7/site-packages/tflearn/config.py", line 5, in <module>
    from .variables import variable
  File "//anaconda3/lib/python3.7/site-packages/tflearn/variables.py", line 7, in <module>
    from tensorflow.contrib.framework.python.ops import add_arg_scope as contrib_add_arg_scope
ModuleNotFoundError: No module named 'tensorflow.contrib'

I believe I'm using tensorflow 2.0. 

The modules in my code : 
import nltk
from nltk.stem.lancaster import LancasterStemmer
import numpy
import tflearn
import tensorflow 
import json 
import random

Can you help me ? 
Thank you.

**Comment by boronhub** [comment]
It is most probably a version issue, as tensorflow.contrib has been removed in version 2.0, and version <= 1.14 is needed to use tflearn.

Similar to issue #30794

**Comment by gowthamkpr** [comment]
@MrRex42 As mentioned in the above comment try using Tensorflow version <=1.14 and this should solve your issue. I am gonna close this issue as it has been resolved. Thanks!
