### ISSUE TITLE
ImportError: DLL load failed TF 1.15

### ISSUE THREAD

**Issue by Snickbrack** [tensorflow/tensorflow#35193]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 7
- TensorFlow version: 1.15
- Python version: 3.7.5
- Installed using virtualenv? pip? conda?: pip inside conda
- CUDA/cuDNN version: 10.1
- GPU model and memory: Nvidia GTX 750 with 1 GB Memory

I get the error that "Failed to load the native TensorFlow runtime." when trying to use Tensorflow with ImageAI.

This is my complete stack-trace:

> Using TensorFlow backend.
> Traceback (most recent call last):
>   File "C:\Anaconda3\envs\imageai\lib\site-packages\tensorflow\pyth
> on\pywrap_tensorflow.py", line 58, in <module>
>     from tensorflow.python.pywrap_tensorflow_internal import *
>   File "C:\Anaconda3\envs\imageai\lib\site-packages\tensorflow\pyth
> on\pywrap_tensorflow_internal.py", line 28, in <module>
>     _pywrap_tensorflow_internal = swig_import_helper()
>   File "C:\Anaconda3\envs\imageai\lib\site-packages\tensorflow\pyth
> on\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
>     _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, descript
> ion)
>   File "C:\Anaconda3\envs\imageai\lib\imp.py", line 242, in load_mo
> dule
>     return load_dynamic(name, filename, file)
>   File "C:\Anaconda3\envs\imageai\lib\imp.py", line 342, in load_dy
> namic
>     return _load(spec)
> ImportError: DLL load failed: Das angegebene Modul wurde nicht gefunden.
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "C:\Documents\ImageAI\CustomDetectionTraining.py", line 1, i
> n <module>
>     from imageai.Detection.Custom import DetectionModelTrainer
>   File "C:\Anaconda3\envs\imageai\lib\site-packages\imageai\Detecti
> on\__init__.py", line 2, in <module>
>     from imageai.Detection.keras_retinanet.models.resnet import resnet50_retinan
> et
>   File "C:\Anaconda3\envs\imageai\lib\site-packages\imageai\Detecti
> on\keras_retinanet\models\resnet.py", line 19, in <module>
>     import keras
>   File "C:\Anaconda3\envs\imageai\lib\site-packages\keras\__init__.
> py", line 3, in <module>
>     from . import utils
>   File "C:\Anaconda3\envs\imageai\lib\site-packages\keras\utils\__i
> nit__.py", line 6, in <module>
>     from . import conv_utils
>   File "C:\Anaconda3\envs\imageai\lib\site-packages\keras\utils\con
> v_utils.py", line 9, in <module>
>     from .. import backend as K
>   File "C:\Anaconda3\envs\imageai\lib\site-packages\keras\backend\_
> _init__.py", line 1, in <module>
>     from .load_backend import epsilon
>   File "C:\Anaconda3\envs\imageai\lib\site-packages\keras\backend\l
> oad_backend.py", line 90, in <module>
>     from .tensorflow_backend import *
>   File "C:\Anaconda3\envs\imageai\lib\site-packages\keras\backend\t
> ensorflow_backend.py", line 5, in <module>
>     import tensorflow as tf
>   File "C:\Anaconda3\envs\imageai\lib\site-packages\tensorflow\__in
> it__.py", line 24, in <module>
>     from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-im
> port
>   File "C:\Anaconda3\envs\imageai\lib\site-packages\tensorflow\pyth
> on\__init__.py", line 49, in <module>
>     from tensorflow.python import pywrap_tensorflow
>   File "C:\Anaconda3\envs\imageai\lib\site-packages\tensorflow\pyth
> on\pywrap_tensorflow.py", line 74, in <module>
>     raise ImportError(msg)
> ImportError: Traceback (most recent call last):
>   File "C:\Anaconda3\envs\imageai\lib\site-packages\tensorflow\pyth
> on\pywrap_tensorflow.py", line 58, in <module>
>     from tensorflow.python.pywrap_tensorflow_internal import *
>   File "C:\Anaconda3\envs\imageai\lib\site-packages\tensorflow\pyth
> on\pywrap_tensorflow_internal.py", line 28, in <module>
>     _pywrap_tensorflow_internal = swig_import_helper()
>   File "C:\Anaconda3\envs\imageai\lib\site-packages\tensorflow\pyth
> on\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
>     _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, descript
> ion)
>   File "C:\Anaconda3\envs\imageai\lib\imp.py", line 242, in load_mo
> dule
>     return load_dynamic(name, filename, file)
>   File "C:\Anaconda3\envs\imageai\lib\imp.py", line 342, in load_dy
> namic
>     return _load(spec)
> ImportError: DLL load failed: Das angegebene Modul wurde nicht gefunden.
> 
> 
> Failed to load the native TensorFlow runtime.
> 
> See https://www.tensorflow.org/install/errors
> 
> for some common reasons and solutions.  Include the entire stack trace
> above this error message when asking for help.
>

**Comment by dubesar** [comment]
https://github.com/tensorflow/tensorflow/issues/13715

A very similar issue as yours. If not resolved with the help of the above, please ping then.

**Comment by Snickbrack** [comment]
Hey, what do you mean by wheel file?

**Comment by dubesar** [comment]
> Hey, what do you mean by wheel file?

A WHL file is a package saved in the Wheel format, which is the standard built-package format used for Python distributions. It contains all the files for a Python install and metadata, which includes the version of the wheel implementation and specification used to package it. WHL files are compressed using Zip compression.

**Comment by oanush** [comment]
@Snickbrack ,
Hi, Please make sure system supports AVX, also there are similar issues [28848](https://github.com/tensorflow/tensorflow/issues/28848) and [22794](https://github.com/tensorflow/tensorflow/issues/22794) Kindly refer them. Hope you have followed instructions from [TensorFlow website](https://www.tensorflow.org/install/gpu#windows_setup).Thanks!

**Comment by oanush** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
