### ISSUE TITLE
Tensorflow not detecting/recognizing GPU

### ISSUE THREAD

**Issue by Meraj99** [tensorflow/tensorflow#35195]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: PC
- TensorFlow installed from (source or binary): Binary
- TensorFlow version: 2.0.0
- Python version: 3.6
- Installed using virtualenv? pip? conda?: pip/conda (both, neither work)
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: CUDA 10.0, cuDNN 7
- GPU model and memory: NVIDIA GeForce 940M

I'm using an NVIDIA GeForce 940M, and have followed the instructions to install Tensorflow GPU exactly as given [here](https://www.tensorflow.org/install/gpu):

    # Add NVIDIA package repositories
    wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/cuda-repo-ubuntu1804_10.0.130-1_amd64.deb
    sudo dpkg -i cuda-repo-ubuntu1804_10.0.130-1_amd64.deb
    sudo apt-key adv --fetch-keys https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/7fa2af80.pub
    sudo apt-get update
    wget http://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1804/x86_64/nvidia-machine-learning-repo-ubuntu1804_1.0.0-1_amd64.deb
    sudo apt install ./nvidia-machine-learning-repo-ubuntu1804_1.0.0-1_amd64.deb
    sudo apt-get update
    
    # Install NVIDIA driver
    sudo apt-get install --no-install-recommends nvidia-driver-418
    # Reboot. Check that GPUs are visible using the command: nvidia-smi
    
    # Install development and runtime libraries (~4GB)
    sudo apt-get install --no-install-recommends \
        cuda-10-0 \
        libcudnn7=7.6.2.24-1+cuda10.0  \
        libcudnn7-dev=7.6.2.24-1+cuda10.0
    # Install TensorRT. Requires that libcudnn7 is installed above.
    sudo apt-get install -y --no-install-recommends libnvinfer5=5.1.5-1+cuda10.0 \
        libnvinfer-dev=5.1.5-1+cuda10.0

This is the output of `nvidia-smi`:

    +-----------------------------------------------------------------------------+
    | NVIDIA-SMI 440.33.01    Driver Version: 440.33.01    CUDA Version: 10.2     |
    |-------------------------------+----------------------+----------------------+
    | GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
    | Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
    |===============================+======================+======================|
    |   0  GeForce 940M        On   | 00000000:01:00.0 Off |                  N/A |
    | N/A   52C    P0    N/A /  N/A |    238MiB /  4046MiB |      6%      Default |
    +-------------------------------+----------------------+----------------------+
                                                                                   
    +-----------------------------------------------------------------------------+
    | Processes:                                                       GPU Memory |
    |  GPU       PID   Type   Process name                             Usage      |
    |=============================================================================|
    |    0      1027      G   /usr/lib/xorg/Xorg                            24MiB |
    |    0      1184      G   /usr/bin/gnome-shell                          46MiB |
    |    0      1388      G   /usr/lib/xorg/Xorg                           110MiB |
    |    0      1555      G   /usr/bin/gnome-shell                          52MiB |
    +-----------------------------------------------------------------------------+

and `nvcc -v`:

    nvcc: NVIDIA (R) Cuda compiler driver
    Copyright (c) 2005-2018 NVIDIA Corporation
    Built on Sat_Aug_25_21:08:01_CDT_2018
    Cuda compilation tools, release 10.0, V10.0.130

and I've installed `tensorflow-gpu` using both conda and pip (neither work).

The output of

    from tensorflow.python.client import device_lib
    print(device_lib.list_local_devices())

is:

    [name: "/device:CPU:0"
    device_type: "CPU"
    memory_limit: 268435456
    locality {
    }
    incarnation: 9340164754758349370
    , name: "/device:XLA_CPU:0"
    device_type: "XLA_CPU"
    memory_limit: 17179869184
    locality {
    }
    incarnation: 3967057350071782501
    physical_device_desc: "device: XLA_CPU device"
    ]

As seen, tensorflow does not recognize the GPU. What do I do?

**Comment by ravikyram** [comment]
@Meraj99 
TensorFlow automatically places operations on a GPU, if possible. As you only have one GPU in your system, it is used by default.
Find more information here: https://www.tensorflow.org/guide/using_gpu
Make sure you have TensorFlow GPU installed:
https://www.tensorflow.org/install/gpu

Please, go through the [link1](https://github.com/tensorflow/tensorflow/issues/21411),[link2](https://github.com/tensorflow/tensorflow/issues/31267) and see if it helps you. Thanks!

**Comment by Meraj99** [comment]
I've fixed it by `pip uninstall tensorflow`. The tensorflow-gpu still works.
