### ISSUE TITLE
Suggestions for simplifying directory structure

### ISSUE THREAD

**Issue by JohnAllen** [tensorflow/tensorflow#3519]
(version/machine agnostic)

I just want to say that after using TF for a while, I still have to fire too many brain cells to remember which directory certain files are in.  

The shortest way I can say this is that I suggest placing **all** instructional/non-source files in the same directory, _probably at the top_ of tensorflow so  visitors can easily find them.

Right now there are:
- `tensorflow[org]/models` (separate repo containing pre-trained models)
- `tensorflow[org]/tensorflow/tensorflow/examples/`
  -`tensorflow[org]/tensorflow/tensorflow/models`
- `tensorflow[org]/tensorflow/tensorflow/tutorials` (these are Tensorflow website tutorials)
- `tensorflow[org]/tensorflow/tensorflow/examples/how_tos`

Hopefully I am not the only one that sometimes finds this confusing, probably because of the same words being used repeatedly to describe different things.

Suggestion 1 is to place the tensorflow/[examples & models] directories into the root of `tensorflow[org]/tensorflow` and renaming that directory to examples_tutorials, to make where to look obvious for those not digging through the source (which is probably a majority of visitors).  I think that single, simple change would simplify this directory structure quite a bit.

I have a couple of additional suggestions for renaming the tensorflow/tensorflow/models directory (note not the pre-trained repo).
1. Rename the separate tensorflow/models **repo** (that contains code pertaining to pre-trained models) to `pre-trained-models` or `pre-trained-weights` and rename the `tensorflow/examples/models` **directory** to something that conveys the fact that it contains research paper models and not pre-trained ones.
2. Rename `models/embedding` to `word2vec` or something else more descriptive

Happy to submit a PR or two if the team wants to make these changes.

**Comment by michaelisard** [comment]
@martinwicke would you like to comment or reassign?

**Comment by martinwicke** [comment]
This is a good thing to do, but it isn't particularly high on our list of priorities. Note that there are not only pre-trained models in the models repo, so I don't think it should be renamed. 

I agree with your suggestion to have a single top-level examples directory. Honestly, I would just have a tensorflow/examples directory, for instance like this:

tensorflow/examples/mnist
tensorflow/examples/word2vec (although embedding is actually more descriptive)
...

I don't see a lot of value distinguishing between tutorials and howtos and we'll likely remove that distinction on the website soon.

This is a perfectly valid feature request, and mostly what would have to happen is to move the code around and fix the links in the documentation and the build files. A PR would be greatly appreciated.

**Comment by karmel** [comment]
Thanks for the feedback @JohnAllen -- we are reorganizing sample models, and converging on the [Official Models](https://github.com/tensorflow/models/tree/master/official) as the place to house reference implementations. Closing this, as that effort is underway.
