### ISSUE TITLE
Does TF2.0 absolutely support TPU now？

### ISSUE THREAD

**Issue by xixiaoyao** [tensorflow/tensorflow#35209]
Our TF code is written with TF2.0 (eager mode). However we heard that TF2.0 cannot run on TPU
 device. So is there any supporting plan ? Or when to release TPU-friendly TF2.X?

**Comment by oanush** [comment]
@xixiaoyao ,
Hello, 2.0 indeed supports TPU, please refer the link [TPUstrategy](https://www.tensorflow.org/guide/distributed_training#tpustrategy) for more information.Thanks!

**Comment by oanush** [comment]
@xixiaoyao ,
Any update on the issue?Thanks!

**Comment by oanush** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
