### ISSUE TITLE
TypeError: expected bytes, Descriptor found

### ISSUE THREAD

**Issue by saqibshakeel035** [tensorflow/tensorflow#35208]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (Windows 10)
- TensorFlow installed from (source):
- TensorFlow version: Tensorflow GPU Version 1.14.0
- Python version: 3.6.9
- Installed using conda:
- CUDA/cuDNN version: cuda_10.0.130_411.31_win10 / cudnn-10.0-windows10-x64-v7.4.1.5
- GPU model and memory: nvidia mx 250 with 2GB0

**Describe the problem**
I am folliowing the [Edge Electronics](https://github.com/EdjeElectronics/TensorFlow-Object-Detection-API-Tutorial-Train-Multiple-Objects-Windows-10#1-install-anaconda-cuda-and-cudnn) github repository. At [step 2d. Set up new Anaconda virtual environment](https://github.com/EdjeElectronics/TensorFlow-Object-Detection-API-Tutorial-Train-Multiple-Objects-Windows-10#2d-set-up-new-anaconda-virtual-environment)  I created a virtual environment using `conda create -n tensorflow1 pip python=3.6` 
The other commands I executed are:
`activate tensorflow1`
`python -m pip install --upgrade pip`
`pip install --ignore-installed --upgrade tensorflow-gpu==1.14.0`
After last command, when I try to import tensorflow, it get imported successfully but after running follwoing command,
`conda install -c anaconda protobuf` when I again try to import tensorflow, I get the following error. 
(tensorflow1) C:\>python
Python 3.6.9 |Anaconda, Inc.| (default, Jul 30 2019, 14:00:49) [MSC v.1915 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\saqib\Anaconda3\envs\tensorflow2\lib\site-packages\tensorflow\__init__.py", line 28, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "C:\Users\saqib\Anaconda3\envs\tensorflow2\lib\site-packages\tensorflow\python\__init__.py", line 52, in <module>
    from tensorflow.core.framework.graph_pb2 import *
  File "C:\Users\saqib\Anaconda3\envs\tensorflow2\lib\site-packages\tensorflow\core\framework\graph_pb2.py", line 16, in <module>
    from tensorflow.core.framework import node_def_pb2 as tensorflow_dot_core_dot_framework_dot_node__def__pb2
  File "C:\Users\saqib\Anaconda3\envs\tensorflow2\lib\site-packages\tensorflow\core\framework\node_def_pb2.py", line 16, in <module>
    from tensorflow.core.framework import attr_value_pb2 as tensorflow_dot_core_dot_framework_dot_attr__value__pb2
  File "C:\Users\saqib\Anaconda3\envs\tensorflow2\lib\site-packages\tensorflow\core\framework\attr_value_pb2.py", line 16, in <module>
    from tensorflow.core.framework import tensor_pb2 as tensorflow_dot_core_dot_framework_dot_tensor__pb2
  File "C:\Users\saqib\Anaconda3\envs\tensorflow2\lib\site-packages\tensorflow\core\framework\tensor_pb2.py", line 16, in <module>
    from tensorflow.core.framework import resource_handle_pb2 as tensorflow_dot_core_dot_framework_dot_resource__handle__pb2
  File "C:\Users\saqib\Anaconda3\envs\tensorflow2\lib\site-packages\tensorflow\core\framework\resource_handle_pb2.py", line 92, in <module>
    __module__ = 'tensorflow.core.framework.resource_handle_pb2'
TypeError: expected bytes, Descriptor found

I have tried everthing like removing the virtual environment and creating the new but still the same error. 
What mistake dou you think I am doing?
Any possible solution will be apppreciated.
Thanks in advance :) 
Looking forward for quick reply

**Comment by oanush** [comment]
@saqibshakeel035 ,
Hello, I indeed tried following all the steps as given in the [link](https://github.com/EdjeElectronics/TensorFlow-Object-Detection-API-Tutorial-Train-Multiple-Objects-Windows-10#2d-set-up-new-anaconda-virtual-environment), make sure you install all the necessary packages mentioned in the link, and try using latest version` tf-1.15 `
`pip install --ignore-installed --upgrade tensorflow-gpu==1.15.0`, I was able to import tensorflow successfully.Thanks!

**Comment by oanush** [comment]
@saqibshakeel035 ,
Any update on the issue ?Thanks!

**Comment by saqibshakeel035** [comment]
> @saqibshakeel035 ,
> Any update on the issue ?Thanks!

Thanks for your update on the issue,  I didn't read your previous comment and was waiting. Now I am gonna try again and than will update you in few hours.

**Comment by oanush** [comment]
@saqibshakeel035 ,
Any latest update ?Thanks!

**Comment by saqibshakeel035** [comment]
> @saqibshakeel035 ,
> Any latest update ?Thanks!

Sorry for a late reply, Actually I am able to import TensorFlow  after installation using pip install --ignore-installed --upgrade tensorflow-gpu==1.15.0 but it gives me error after installation of protobuf using conda install -c anaconda protobuf, I get the same error mentioned above.

**Comment by saqibshakeel035** [comment]
Any update as I am still stuck at this point????

**Comment by ymodak** [comment]
You don't need to install protobuf separately. Can you try and create a new virtual environment and install TF again without installing protobuf? Thanks!
See https://www.tensorflow.org/install/pip?lang=python3#2.-create-a-virtual-environment-recommended

**Comment by saqibshakeel035** [comment]
> You don't need to install protobuf separately. Can you try and create a new virtual environment and install TF again without installing protobuf? Thanks!
> See https://www.tensorflow.org/install/pip?lang=python3#2.-create-a-virtual-environment-recommended

It worked fine. Just to mention one thing that if someone is using [Edge Electronics github repository](https://github.com/EdjeElectronics/TensorFlow-Object-Detection-API-Tutorial-Train-Multiple-Objects-Windows-10#1-install-anaconda-cuda-and-cudnn) and facing the same issue as mine, I recommend you to install all other packages in step  [2d](https://github.com/EdjeElectronics/TensorFlow-Object-Detection-API-Tutorial-Train-Multiple-Objects-Windows-10#2d-set-up-new-anaconda-virtual-environment) and then install tensorflow using  `pip install --ignore-installed --upgrade tensorflow-gpu==1.15.0` . It worked for me. 
Good Luck!!

**Comment by satyamedh** [comment]
try resarting the cmd

**Comment by PreVizsla** [comment]
still got the same issue after following that guide xD

**Comment by navroopsingh1** [comment]
Same here, I tried making a new virtual environment and used pip install --ignore-installed --upgrade tensorflow-gpu==1.15.0 this time but I ended up with the same error.

**Comment by Khan-123-tar** [comment]
I am facing this error when importing tensorflow (TypeError: expected bytes, Descriptor found ) and secondly when from keras.models import Sequential it render this error (Using TensorFlow backend.)
