### ISSUE TITLE
Object detection producing incorrect results on mobile (ios)

### ISSUE THREAD

**Issue by Lhogeshwaran** [tensorflow/tensorflow#35205]
Object detection SSD trained and tested to produce expected results in PC. 
http://download.tensorflow.org/models/object_detection/ssd_inception_v2_coco_2018_01_28.tar.gz
https://github.com/tensorflow/models/blob/master/research/object_detection/samples/configs/ssd_inception_v2_pets.config

Model works well and produces accurate results on PC. 
After converting to tflite and loading in mobile, the camera view shows incorrect detection (several detection of same class and in fixed place even when moving the camera).

**Comment by Lhogeshwaran** [comment]
Found a similar reported issue - https://github.com/tensorflow/tensorflow/issues/25746

**Comment by gadagashwini** [comment]
@Lhogeshwaran, There is a objection detection model in Tflite for iOS.
https://github.com/tensorflow/examples/tree/master/lite/examples/object_detection/ios

**Comment by yyoon** [comment]
@Lhogeshwaran Could you also describe how exactly you loaded the model on mobile, and how you preprocessed the inputs?

**Comment by Lhogeshwaran** [comment]
Thank you both! 

@yyoon I converted the model to the .tflite format, placed it inside ObjectDetection/Model and changed the ModelDataHandler modelInfo and labelInfo to point to the custom model.

**Comment by Lhogeshwaran** [comment]
I used the saved_model.pb to check the output by capturing photos/videos using the mobile and using them to test in the system

**Comment by sushreebarsa** [comment]
@Lhogeshwaran We see that you are using older version of tensorflow .Many bug have been fixed in latest version. We recommend that you upgrade to latest stable version of tensorflow 2.6.0 and let us know if the issue still persists in newer versions .Thanks!
