### ISSUE TITLE
TensorImage grayscale (single channel) image support 

### ISSUE THREAD

**Issue by hvico** [tensorflow/tensorflow#35211]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 18.04
- **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device**: Huawei
- **TensorFlow installed from (source or binary)**: Source
- **TensorFlow version (use command below)**: 2.0
- **Python version**: 3.6
- **Bazel version (if compiling from source)**: 
- **GCC/Compiler version (if compiling from source)**: 
- **CUDA/cuDNN version**: 10.2
- **GPU model and memory**: GTX2080TI
- **Exact command to reproduce**:

### Describe the problem
This is a feature request. I am struggling to make a TFLITE model that works perfectly in Python to  also work in and Android apk. It seems I have problems related with the conversion from Bitmap to a bytebuffer, std, mean and that stuff (I've been using old Android examples that made the conversion Bitmap -> Bytebuffer manually). 

Now I've seen this new TensorImage feature in tensorflow-lite-support and tried it, but it seems it only supports loading RGB images. My model is MNIST-based, so the input shape of the images are (28, 28, 1). I don't see how I can use TensorImage to feed my model in this scenario.

Can you please support grayscale (1 channel) images also please? 

Thanks,

**Comment by yyoon** [comment]
@lu-wang-g Could you take a look?

**Comment by lu-wang-g** [comment]
Thanks for letting us know about your requests! The grayscale image is on our todo list, but is not prioritized at this moment. We'll definitely consider your feedback into our roadmap planning for Q1 2020. I'll give you updates once it is confirmed.

**Comment by hvico** [comment]
OK, thanks for the feedback, I will gladly test the feature as soon as you release it. By now I was able to solve my problem manipulating the ByteBuffer manually.

**Comment by soham24** [comment]
@hvico hello sir,
can you tell us how exactly you did this?

**Comment by hvico** [comment]
Hello. It's been a while, unfortunatelly I couldn't find this code now. For what I recall I think I just dropped the usage of TensorImage and managed to load the ByteBuffer manually for this particular model. Thanks!

**Comment by rmothukuru** [comment]
@hvico,
Sorry for the delayed response. Can you please refer the documentation of [TF Lite Basic image manipulation and conversion ](https://www.tensorflow.org/lite/inference_with_metadata/lite_support#basic_image_manipulation_and_conversion) and let us know if this issue is resolved? Thanks!

**Comment by lu-wang-g** [comment]
TFLite Support library can help convert RGB image to grayscale. You can create  the ImageProcessor as follows:

```
ImageProcessor processor =
        new ImageProcessor.Builder().add(new TransformToGrayscaleOp()).build();
```

See more instructions about ImageProcessor as @rmothukuru pointed out above.

**Comment by AndryCU** [comment]
Why when i traid to use TransformToGrayscaleOp i see a: **Unresolved reference: TransformToGrayscaleOp** error?

**Comment by lu-wang-g** [comment]
@AndryCU have you pulled in the lastest tflite support library, "org.tensorflow:tensorflow-lite-support:0.3.0"?

**Comment by AndryCU** [comment]
@lu-wang-g SOLVED. I don't know why android studio don't said me that was avaible a newer version, anyway...thanks...

**Comment by lu-wang-g** [comment]
You're welcome!
