### ISSUE TITLE
I need a function which like np.argwhere

### ISSUE THREAD

**Issue by xinyidaren** [tensorflow/tensorflow#35210]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using):2.0
- Are you willing to contribute it (Yes/No):No

**Describe the feature and the current behavior/state.**
The current API only includes argmax and argmin for return the index of tensor，i need a function 
which like np.argwhere for inference centernet
**Will this change the current api? How?**
it will not change.only append an api in tf.math
**Who will benefit with this feature?**
everyone
**Any Other info.**

**Comment by SumanSudhir** [comment]
np.argwhere is related to Numpy issue. Do you mean tf.math.argwhere

**Comment by SumanSudhir** [comment]
I am willing to work on this issue. Can you please assign this to me?

**Comment by Athul8raj** [comment]
I believe you can get the indexes when the condition is met as tensors just by using _tf.where(condition)_
Sample code 

`
import tensorflow as tf
import numpy as np

numpy_array = np.arange(6).reshape(2,3)
indices = np.argwhere(numpy_array>1)
print(indices)

>>>[[0 2]
 [1 0]
 [1 1]
 [1 2]]

tensor_array = tf.convert_to_tensor(numpy_array)
cond_indices = tf.where(tensor_array>1)
print(cond_indices)

>>>tf.Tensor(
[[0 2]
 [1 0]
 [1 1]
 [1 2]], shape=(4, 2), dtype=int64)
`

**Comment by ravikyram** [comment]
@xinyidaren 
Can you please check @Athul8raj suggestion.Thanks!

**Comment by xinyidaren** [comment]
thanks a lot!!
