### ISSUE TITLE
tf.load_op_library bug

### ISSUE THREAD

**Issue by northeastsquare** [tensorflow/tensorflow#35212]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): https://github.com/cogaplex-bts/bts
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): ubuntu 1604
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): pip
- TensorFlow version (use command below):1.13.2
- Python version: 3.7
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source): pip 
- CUDA/cuDNN version: 10.0 
- GPU model and memory: 1060, 6G

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
in a process, use full path , twice load:
tf.load_op_library(os.path.join(dname, 'build/libcompute_depth.so'))
the second time, OP_LIST is empty, 
but with relative path, twice  tf.load_op_library not empty
**Describe the expected behavior**
use full path, twice  tf.load_op_library, OP_LIST should not empty
**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.
I compile https://github.com/cogaplex-bts/bts, met this problem. But I think this is a general problem, reproduce: just in a python file, load the library twice, with full path and relative path   
**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

```
compute_depth_grad_module dict: {'__name__': 'a11935c229913616b7b14d8da52f01ac', '__doc__': 'Python wrappers around TensorFlow ops.\n\nThis file is MACHINE GENERATED! Do not edit.\n', ...  , 'LIB_HANDLE': <Swig Object of type 'TF_Library *' at 0x7ff4ad011f60>, 'OP_LIST': op {
  name: "ComputeDepth"
  input_arg {
    name: "input"
    type: DT_FLOAT
  }
  input_arg {
    name: "focal"
    type: DT_FLOAT
  }
  output_arg {
    name: "depth"
    type: DT_FLOAT
  }
  attr {
    name: "upratio"
    type: "int"
  }
}
op {
  name: "ComputeDepthGrad"
  input_arg {
    name: "depth_grad"
    type: DT_FLOAT
  }
  input_arg {
    name: "input"
    type: DT_FLOAT
  }
  input_arg {
    name: "focal"
    type: DT_FLOAT
  }
  output_arg {
    name: "grad_input"
    type: DT_FLOAT
  }
  output_arg {
    name: "grad_focal"
    type: DT_FLOAT
  }
}
}
{'__name__': 'a11935c229913616b7b14d8da52f01ac', '__doc__': 'Python wrappers around TensorFlow ops.\n\nThis file is MACHINE GENERATED! Do not edit.\n', '__package__': None,  ... , 'LIB_HANDLE': <Swig Object of type 'TF_Library *' at 0x7ff4ad011f60>, 'OP_LIST': op {
  name: "ComputeDepth"
  input_arg {
    name: "input"
    type: DT_FLOAT
  }
  input_arg {
    name: "focal"
    type: DT_FLOAT
  }
  output_arg {
    name: "depth"
    type: DT_FLOAT
  }
  attr {
    name: "upratio"
    type: "int"
  }
}
op {
  name: "ComputeDepthGrad"
  input_arg {
    name: "depth_grad"
    type: DT_FLOAT
  }
  input_arg {
    name: "input"
    type: DT_FLOAT
  }
  input_arg {
    name: "focal"
    type: DT_FLOAT
  }
  output_arg {
    name: "grad_input"
    type: DT_FLOAT
  }
  output_arg {
    name: "grad_focal"
    type: DT_FLOAT
  }
}
}
```

but with full name, second will print:
```
compute_depth_grad_module dict: {'__name__': '670cc8cfec5b6d3b8635f39bd583d769', '__doc__': 'Python wrappers around TensorFlow ops.\n\nThis file is MACHINE GENERATED! Do not edit.\n', '__package__': None, ... , 'LIB_HANDLE': <Swig Object of type 'TF_Library *' at 0x7f6b2a8f3e70>, 'OP_LIST': }
```

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.
