### ISSUE TITLE
Tensorflow build unsuccessful using bazel build

### ISSUE THREAD

**Issue by spurani** [tensorflow/tensorflow#35227]
So I have been following to this guide https://www.tensorflow.org/install/source and https://www.tensorflow.org/install/gpu. My system configuration is

+-----------------------------------------------------------------------------+
| NVIDIA-SMI 440.33.01    Driver Version: 440.33.01    CUDA Version: 10.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 1050    Off  | 00000000:01:00.0  On |                  N/A |
| 45%   27C    P8    N/A /  75W |    258MiB /  1997MiB |     10%      Default |
+-------------------------------+----------------------+----------------------+
                                                                              
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0      1022      G   /usr/lib/xorg/Xorg                           151MiB |
|    0      2686      G   compiz                                       102MiB |
|    0      5660      G   /usr/lib/firefox/firefox                       1MiB |
+-----------------------------------------------------------------------------+

./deviceQuery Starting...

 CUDA Device Query (Runtime API) version (CUDART static linking)

Detected 1 CUDA Capable device(s)

Device 0: "GeForce GTX 1050"
  CUDA Driver Version / Runtime Version          10.2 / 9.0
  CUDA Capability Major/Minor version number:    6.1
  Total amount of global memory:                 1998 MBytes (2094989312 bytes)
  ( 5) Multiprocessors, (128) CUDA Cores/MP:     640 CUDA Cores
  GPU Max Clock rate:                            1455 MHz (1.46 GHz)
  Memory Clock rate:                             3504 Mhz
  Memory Bus Width:                              128-bit
  L2 Cache Size:                                 1048576 bytes
  Maximum Texture Dimension Size (x,y,z)         1D=(131072), 2D=(131072, 65536), 3D=(16384, 16384, 16384)
  Maximum Layered 1D Texture Size, (num) layers  1D=(32768), 2048 layers
  Maximum Layered 2D Texture Size, (num) layers  2D=(32768, 32768), 2048 layers
  Total amount of constant memory:               65536 bytes
  Total amount of shared memory per block:       49152 bytes
  Total number of registers available per block: 65536
  Warp size:                                     32
  Maximum number of threads per multiprocessor:  2048
  Maximum number of threads per block:           1024
  Max dimension size of a thread block (x,y,z): (1024, 1024, 64)
  Max dimension size of a grid size    (x,y,z): (2147483647, 65535, 65535)
  Maximum memory pitch:                          2147483647 bytes
  Texture alignment:                             512 bytes
  Concurrent copy and kernel execution:          Yes with 2 copy engine(s)
  Run time limit on kernels:                     Yes
  Integrated GPU sharing Host Memory:            No
  Support host page-locked memory mapping:       Yes
  Alignment requirement for Surfaces:            Yes
  Device has ECC support:                        Disabled
  Device supports Unified Addressing (UVA):      Yes
  Supports Cooperative Kernel Launch:            Yes
  Supports MultiDevice Co-op Kernel Launch:      Yes
  Device PCI Domain ID / Bus ID / location ID:   0 / 1 / 0
  Compute Mode:
     < Default (multiple host threads can use ::cudaSetDevice() with device simultaneously) >

deviceQuery, CUDA Driver = CUDART, CUDA Driver Version = 10.2, CUDA Runtime Version = 9.0, NumDevs = 1

nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2017 NVIDIA Corporation
Built on Fri_Sep__1_21:08:03_CDT_2017
Cuda compilation tools, release 9.0, V9.0.176

libcudnn => 7.6.0
#define CUDNN_MAJOR 7
#define CUDNN_MINOR 6
#define CUDNN_PATCHLEVEL 0
--
#define CUDNN_VERSION (CUDNN_MAJOR * 1000 + CUDNN_MINOR * 100 + CUDNN_PATCHLEVEL)

#include "driver_types.h"

NCCL version => 2.4.7
gcc => 5.4.0
pyhton => 2.7.0

dpkg -l | grep TensorRT
ii  graphsurgeon-tf                                            5.1.5-1+cuda9.0                                 amd64        GraphSurgeon for TensorRT package
ii  libnvinfer-dev                                             5.1.5-1+cuda9.0                                 amd64        TensorRT development libraries and headers
ii  libnvinfer-samples                                         5.1.5-1+cuda9.0                                 all          TensorRT samples and documentation
ii  libnvinfer5                                                5.1.5-1+cuda9.0                                 amd64        TensorRT runtime libraries
ii  python-libnvinfer                                          5.1.5-1+cuda9.0                                 amd64        Python bindings for TensorRT
ii  python-libnvinfer-dev                                      5.1.5-1+cuda9.0                                 amd64        Python development package for TensorRT
ii  tensorrt                                                   5.1.5.0-1+cuda9.0                               amd64        Meta package of TensorRT
ii  uff-converter-tf                                           5.1.5-1+cuda9.0                                 amd64        UFF converter for TensorRT package

after running this command
**bazel build --config=opt --config=cuda --cxxopt="-D_GLIBCXX_USE_CXX11_ABI=0" //tensorflow/tools/pip_package:build_pip_package
and
bazel build --config=opt  --cxxopt="-D_GLIBCXX_USE_CXX11_ABI=0" //tensorflow/tools/pip_package:build_pip_package**

I got the same error both time mentioned at bottom

**ERROR: /home/user/tensorflow/tensorflow/core/kernels/BUILD:2951:1: output 'tensorflow/core/kernels/_objs/cwise_op_gpu/tensorflow/core/kernels/cwise_op_gpu_mul.cu.pic.o' was not created
ERROR: /home/user/tensorflow/tensorflow/core/kernels/BUILD:2951:1: not all outputs were created or valid
Target //tensorflow/tools/pip_package:build_pip_package failed to build
FAILED: Build did NOT complete successfully**

Any help would be appreciated I am still learning and trying to understand tensorflow and its conepts. It would be great and exciting if anyone could give any suggestions or advice where I am going wrong. Though I am referring to couple of references will keep you guys posted if I come across anything relevant. Let me know if more info is required. Thanks

**Comment by spurani** [comment]
A quick update in this sections. ERROR: /home/user/tensorflow/tensorflow/BUILD:533:1: Executing genrule //tensorflow:tf_python_api_gen_v1 failed (Exit 1)
Traceback (most recent call last):
  File "/home/user/.cache/bazel/_bazel_user/f11a7014505dc3312336ee3d012a10b6/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/create_tensorflow.python_api_1.runfiles/org_tensorflow/tensorflow/python/tools/api/generator/create_python_api.py", line 27, in <module>
    from tensorflow.python.tools.api.generator import doc_srcs
  File "/home/user/.cache/bazel/_bazel_user/f11a7014505dc3312336ee3d012a10b6/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/create_tensorflow.python_api_1.runfiles/org_tensorflow/tensorflow/python/__init__.py", line 59, in <module>
    from tensorflow.core.framework.graph_pb2 import *
  File "/home/user/.cache/bazel/_bazel_user/f11a7014505dc3312336ee3d012a10b6/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/create_tensorflow.python_api_1.runfiles/org_tensorflow/tensorflow/core/framework/graph_pb2.py", line 15, in <module>
    from tensorflow.core.framework import node_def_pb2 as tensorflow_dot_core_dot_framework_dot_node__def__pb2
  File "/home/user/.cache/bazel/_bazel_user/f11a7014505dc3312336ee3d012a10b6/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/create_tensorflow.python_api_1.runfiles/org_tensorflow/tensorflow/core/framework/node_def_pb2.py", line 15, in <module>
    from tensorflow.core.framework import attr_value_pb2 as tensorflow_dot_core_dot_framework_dot_attr__value__pb2
  File "/home/user/.cache/bazel/_bazel_user/f11a7014505dc3312336ee3d012a10b6/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/create_tensorflow.python_api_1.runfiles/org_tensorflow/tensorflow/core/framework/attr_value_pb2.py", line 15, in <module>
    from tensorflow.core.framework import tensor_pb2 as tensorflow_dot_core_dot_framework_dot_tensor__pb2
  File "/home/user/.cache/bazel/_bazel_user/f11a7014505dc3312336ee3d012a10b6/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/create_tensorflow.python_api_1.runfiles/org_tensorflow/tensorflow/core/framework/tensor_pb2.py", line 15, in <module>
    from tensorflow.core.framework import resource_handle_pb2 as tensorflow_dot_core_dot_framework_dot_resource__handle__pb2
  File "/home/user/.cache/bazel/_bazel_user/f11a7014505dc3312336ee3d012a10b6/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/create_tensorflow.python_api_1.runfiles/org_tensorflow/tensorflow/core/framework/resource_handle_pb2.py", line 22, in <module>
    serialized_pb=_b('\n/tensorflow/core/framework/resource_handle.proto\x12\ntensorflow\"r\n\x13ResourceHandleProto\x12\x0e\n\x06\x64\x65vice\x18\x01 \x01(\t\x12\x11\n\tcontainer\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x11\n\thash_code\x18\x04 \x01(\x04\x12\x17\n\x0fmaybe_type_name\x18\x05 \x01(\tBn\n\x18org.tensorflow.frameworkB\x0eResourceHandleP\x01Z=github.com/tensorflow/tensorflow/tensorflow/go/core/framework\xf8\x01\x01\x62\x06proto3')
**TypeError: __new__() got an unexpected keyword argument 'serialized_options'**

Target //tensorflow/tools/pip_package:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 2315.104s, Critical Path: 235.46s
INFO: 3311 processes: 3311 local.

**FAILED: Build did NOT complete successfully**

So I am now trying to figure out how to solve this error. If anyone is familiar with this error feel free to drop any suggestions or advice it would be really helpful thanks

**Comment by gadagashwini** [comment]
@spurani, Could you post the `./configure` output log. Thanks!

**Comment by spurani** [comment]
@gadagashwini Here is my ./configure output. I ran this command **cat .tf_configure.bazelrc**. I hope this helps. Please feel free to reach out if you require more information.

build --action_env PYTHON_BIN_PATH="/usr/bin/python"
build --action_env PYTHON_LIB_PATH="/usr/local/lib/python2.7/dist-packages"
build --python_path="/usr/bin/python"
build:ignite --define with_ignite_support=true
build:xla --define with_xla_support=true
build --action_env TF_NEED_OPENCL_SYCL="0"
build --action_env TF_NEED_ROCM="0"
build --action_env TF_NEED_CUDA="1"
build --action_env CUDA_TOOLKIT_PATH="/usr/local/cuda"
build --action_env TF_CUDA_VERSION="9.0"
build --action_env CUDNN_INSTALL_PATH="/usr/lib/x86_64-linux-gnu"
build --action_env TF_CUDNN_VERSION="7"
build --action_env TENSORRT_INSTALL_PATH="/usr/lib/x86_64-linux-gnu"
build --action_env TF_TENSORRT_VERSION="5.1.5"
build --action_env NCCL_INSTALL_PATH="/usr/lib/x86_64-linux-gnu"
build --action_env NCCL_HDR_PATH="/usr/include"
build --action_env TF_NCCL_VERSION="2"
build --action_env TF_CUDA_COMPUTE_CAPABILITIES="6.1"
build --action_env TF_CUDA_CLANG="0"
build --action_env GCC_HOST_COMPILER_PATH="/usr/bin/gcc"
build --config=cuda
test --config=cuda
build:opt --copt=-march=native
build:opt --host_copt=-march=native
build:opt --define with_default_optimizations=true
build:v2 --define=tf_api_version=2

**Comment by gadagashwini** [comment]
@spurani, Looks like in the `./configure` output, CUDA version is 9.0 but at the `nvidia-smi` CUDA 10.2.
Please check the CUDA and cuDNN version. Provide the Tenosrflow version/branch that you are building. Thanks!

**Comment by spurani** [comment]
@gadagashwini thanks for your prompt reply really appreciate it. I am building tensorflow version 1.12.0
https://github.com/tensorflow/tensorflow/releases/tag/v1.12.0. I haven't installed cudnn separately it came along with cuda 9.0. Also I have been following these instructions for setting up tensorflow before installationhttps://www.tensorflow.org/install/gpu and here is test build compatibility configurations for gpu https://www.tensorflow.org/install/source#linux  and for installation https://www.tensorflow.org/install/source#linux. 

as you said in your previous comment that in the ./configure output, CUDA version is 9.0 but at the nvidia-smi CUDA 10.2. In explanation can you please refer to this blog I hope it will clear any doubts if you have https://stackoverflow.com/questions/53422407/different-cuda-versions-shown-by-nvcc-and-nvidia-smi. Please feel free to reach out should you have any questions or If you require any further information. Thanks

**Comment by gadagashwini** [comment]
@spurani, If you have multiple CUDA versions, 
Add cuda, cudnn, cupti variables to your environment path.https://www.tensorflow.org/install/gpu#linux_setup.
Please take a look at tested build configuration.
https://www.tensorflow.org/install/source#gpu
Tensorflow 1.12 supports CUDA 9.0.
Thanks!

**Comment by spurani** [comment]
@gadagashwini I have already added cuda, cudnn, cupti variables to your environment path based on this https://www.tensorflow.org/install/gpu#linux_setup. The same issue(as mentioned above) still exists.  **TypeError: new() got an unexpected keyword argument 'serialized_options'**. Is there anything else you could suggest? Though I am trying my best to figure out the issue. But till now I didn't find anything relevant on internet which could help me solve the issue. Thanks

**Comment by spurani** [comment]
@gadagashwini . So basically I removed tensorflow completely and started from scratch with the help of the mentioned guide. I was successfully able to build and run to install tensorflow after following this guide https://medium.com/repro-repo/speed-up-learning-by-building-tensorflow-gpu-from-source-on-ubuntu-d03bb4e06b23 .

Target //tensorflow/tools/pip_package:build_pip_package up-to-date:
  bazel-bin/tensorflow/tools/pip_package/build_pip_package

INFO: Elapsed time: 3517.322s, Critical Path: 250.75s
INFO: 9346 processes: 9346 local.
INFO: Build completed successfully, 9500 total actions

I ran these 2 commands to verify the installation
**python -c "import tensorflow as tf; print(tf.__version__)"**
/home/path/.local/lib/python3.5/site-packages/tensorflow/python/framework/dtypes.py:523: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/path/.local/lib/python3.5/site-packages/tensorflow/python/framework/dtypes.py:524: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/path/.local/lib/python3.5/site-packages/tensorflow/python/framework/dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/home/path/.local/lib/python3.5/site-packages/tensorflow/python/framework/dtypes.py:526: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/home/path/.local/lib/python3.5/site-packages/tensorflow/python/framework/dtypes.py:527: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/home/path/.local/lib/python3.5/site-packages/tensorflow/python/framework/dtypes.py:532: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
1.12.0

**python -c "import tensorflow as tf; print(tf.contrib.eager.num_gpus())"**
/home/path/.local/lib/python3.5/site-packages/tensorflow/python/framework/dtypes.py:523: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/path/.local/lib/python3.5/site-packages/tensorflow/python/framework/dtypes.py:524: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/path/.local/lib/python3.5/site-packages/tensorflow/python/framework/dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/home/path/.local/lib/python3.5/site-packages/tensorflow/python/framework/dtypes.py:526: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/home/path/.local/lib/python3.5/site-packages/tensorflow/python/framework/dtypes.py:527: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/home/path/.local/lib/python3.5/site-packages/tensorflow/python/framework/dtypes.py:532: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
2019-12-25 18:15:33.357674: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2019-12-25 18:15:33.416894: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:964] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-12-25 18:15:33.417115: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1432] Found device 0 with properties: 
name: GeForce GTX 1050 major: 6 minor: 1 memoryClockRate(GHz): 1.455
pciBusID: 0000:01:00.0
totalMemory: 1.95GiB freeMemory: 1.65GiB
2019-12-25 18:15:33.417129: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1511] Adding visible gpu devices: 0
2019-12-25 18:15:33.634565: I tensorflow/core/common_runtime/gpu/gpu_device.cc:982] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-12-25 18:15:33.634593: I tensorflow/core/common_runtime/gpu/gpu_device.cc:988]      0 
2019-12-25 18:15:33.634599: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1001] 0:   N 
2019-12-25 18:15:33.634702: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 1397 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1050, pci bus id: 0000:01:00.0, compute capability: 6.1)
1

But still my digits says Tensorflow support disabled. Can you please guide me through this?
Thanks

**Comment by gadagashwini** [comment]
> But still my digits says Tensorflow support disabled. Can you please guide me through this?
> Thanks
Looks like the Tensorflow installed correctly.
Could you elaborate the issue with context. Thanks!

**Comment by spurani** [comment]
> > But still my digits says Tensorflow support disabled. Can you please guide me through this?
> > Thanks
> 
> Looks like the Tensorflow installed correctly.
> Could you elaborate the issue with context. Thanks!

I am trying to integrate Tensorflow framework in Nvidia Digits. I already have nvidia Digits working with Caffe framework. https://github.com/NVIDIA/DIGITS/blob/master/docs/BuildTensorflow.md and https://github.com/NVIDIA/DIGITS/blob/master/docs/GettingStartedTensorflow.md might answer your question. Please let me know if you require more info. Thanks

**Comment by spurani** [comment]
@gadagashwini Is it possible to build Tensorflow using python 2.7? Because I removed my previous tensorflow installation which was built on python 3.5. I have tried building tensorflow several times using python 2.7 but it fails everytime is there a command from where I can trace logs and show you what's the exact issue. It would a learning lesson for me is you could me solve this issue. My system configuration is exactly the same mentioned in my previous posts. Thanks and cheers.

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.
