### ISSUE TITLE
Configuring issues with tag 2.1.0

### ISSUE THREAD

**Issue by aPonza** [tensorflow/tensorflow#35228]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Debian 9
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: no
- TensorFlow installed from (source or binary): source
- TensorFlow version: 2.1.0rc1 (and rc0)
- Python version: 3.6.8
- Installed using virtualenv? pip? conda?: virtualenv
- Bazel version (if compiling from source): bazelisk
- GCC/Compiler version (if compiling from source): 6.3.0
- CUDA/cuDNN version: 10.1 and 7.6.5
- GPU model and memory: 2x NVidia Titan XP 11GB

1. Configuring from both tags (rc0 and rc1) picks the wrong bazel (0.26 instead of 1.1.0) due to misconfigured .bazelversion, which should be cherry-picked from a later commit to make it work. I don't see the reason for this to be necessary and not having a buildable tag. The commit a5f9bcd64453ff3d1f64cb4da4786db3d2da7f82 should be the one but, while I understand this making rc0 not work, I don't understand rc1 also not working since it's a later tag.

2. Configuring out of source, i.e. with a tree made to be able to call `../configure` (hybrid out-of-source) or `../tensorflow/configure` (full out-of-source) results in `/usr/local/bin/python3.6: can't open file 'third_party/gpus/find_cuda_config.py': [Errno 2] No such file or directory`, likely due to 'third_party/gpus/find_cuda_config.py' being an absoulte path instead of a relative one.

**Comment by hf-sky-hf** [comment]
Ok

**Comment by perfinion** [comment]
@mihaimaruseac: the `.bazelversion` in the r2.1 branch does not match the allowed range in `configure.py` (range is 0.27-0.29, `.bazelversion is 0.26)

**Comment by mihaimaruseac** [comment]
I'll make a cherry-pick

**Comment by mihaimaruseac** [comment]
Actually, there is #35470 already for this.

**Comment by aPonza** [comment]
I still don't see the reason to not have a buildable tag. Regardless, that would fix point 1. What about the second? Could that be a valid way to fix the issue or am I the only one having it?

**Comment by mihaimaruseac** [comment]
`r2.1` branch was cut before changes were made to support bazel 1.1.0. Thus, tags on this branch should be buildable with Bazel from `0.27` to `0.29`. It is lucky if it also builds with 1.1.0.

Regarding second point, I don't think you're supposed to run configure out of tree. I don't know of any other open source project which allows you to `${path_to}/configure` from outside the tree

**Comment by aPonza** [comment]
`tags on this branch should be buildable with Bazel from 0.27 to 0.29` isn't true though, due to said bazelversion being incorrectly set to 0.26. The point of my last comment was to point out my desire to have r2.1 build out of the box after dependencies are satisfied (i.e. include the commit from 5 days ago which you linked in the final r2.1 tag), I suppose that's the reason it's still a release candidate.

Now that you say it, I can only think of CMake Open Source projects which allow it, but it is a "best practice" so to speak, as far as I know. Many projects not only allow it but enforce it as well (e.g. OpenCV, ROS, ...), but still mostly CMake ones. Actually [google tells me Qt allows it](https://www.qtcentre.org/threads/23086-Building-qt-out-of-source?s=0f1acc001d79521205a72a0b7790fe9e&p=112396#post112396), but I see your point, and that is a very old link.

**Comment by mihaimaruseac** [comment]
#35470 has been merged
