### ISSUE TITLE
Return some sort of verifying data structure for load_weights for tf.keras models

### ISSUE THREAD

**Issue by ashutoshbsathe** [tensorflow/tensorflow#35239]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using): 2.0.0
- Are you willing to contribute it (Yes/No): Yes

**Describe the feature and the current behavior/state.**
Currently, whenever user loads keras models using HDF5, user gets no confirmation that models were loaded successfully ([\[1\]](https://www.tensorflow.org/api_docs/python/tf/keras/Sequential#load_weights), [\[2\]](https://www.tensorflow.org/api_docs/python/tf/keras/Model?version=stable#load_weights) return nothing). This confirmation could be useful for verifying that weights are properly loaded. In case of transfer learning, users typically only want to load specific weights from the HDF5file. This can be currently achieved by using `load_weights(by_name=True)`, however, users don't get any confirmation about which layers were actually loaded.

Also, in case there are no matching layers in between the original model and source model, the `model.load_weights(by_name=True)` fails without raising any exception so there is no way to actually debug what went wrong with the model loading. (Note here that I'm talking about name mismatch not weight mismatch) This significantly affects the ability to write unit tests for models since the tester code cannot actually verify what layers were loaded from HDF5 file.

**Will this change the current api? How?**
Yes, this changes the current API for [\[1\]](https://www.tensorflow.org/api_docs/python/tf/keras/Model?version=stable#load_weights) and [\[2\]](https://www.tensorflow.org/api_docs/python/tf/keras/Sequential#load_weights) by adding a return type to them. Specifically, we will be returning a particular data structure when loading HDF5 files [here](https://github.com/tensorflow/tensorflow/blob/c49396cf71dacc32195033507b3bbd985b12c255/tensorflow/python/keras/engine/network.py#L1131). My current idea is to return the list of layers that were loaded from HDF5 although I'm open to discussion about the return type.

**Who will benefit with this feature?**
Users who are loading their weights from h5py files and want to verify/check what layers were loaded from HDF5. 

**Any Other info.**
N/A

Let me know if any more clarification/information is needed. I'm willing to contribute by working on this issue.

**Comment by ashutoshbsathe** [comment]
Currently, the only way to see if model loads the weights correctly is by manually setting weights for every layer from hdf5 which is very inefficient. (Discussion on keras repo [here](https://github.com/keras-team/keras/issues/5397))
(To build a unit test for verifying if model is correctly getting loaded, one needs to collect initial weights of the model somewhere, manually set the weights using hdf5 and lastly compare the newly set weights with the initial weights. This is a very inefficient workflow and can be improvised by the feature I have requested above)

**Comment by ashutoshbsathe** [comment]
@fchollet (correct me if I'm wrong) the final function that sets the values of weights in keras is [this](https://github.com/tensorflow/tensorflow/blob/ea8b6de39fc208619281f34163952ccaa134c04c/tensorflow/python/keras/saving/hdf5_format.py#L639). I can see that it contains `layer_names` which holds the list of layers for which the API will try to load weights for. 

IMO we can simply return this list to every caller function and that would suffice ? If you agree, please let me know. I have just setup a tensorflow development environment and I can send a PR for this.

**Comment by RomanGirin** [comment]
I agree, this feature would be very useful!

**Comment by rmothukuru** [comment]
@ashutoshbsathe,
Sorry for the delayed response. Documentation of [Model.Load_Weights](https://www.tensorflow.org/api_docs/python/tf/keras/Model#load_weights) states that it returns:

> When loading a weight file in TensorFlow format, returns the same status object as tf.train.Checkpoint.restore. When graph building, restore ops are run automatically as soon as the network is built (on first call for user-defined classes inheriting from Model, immediately if it is already built).

We can verify if the object is of type, **`tf.train.Checkpoint.restore`**. Thanks!

**Comment by ashutoshbsathe** [comment]
> @ashutoshbsathe,
> Sorry for the delayed response. Documentation of [Model.Load_Weights](https://www.tensorflow.org/api_docs/python/tf/keras/Model#load_weights) states that it returns:
> 
> > When loading a weight file in TensorFlow format, returns the same status object as tf.train.Checkpoint.restore. When graph building, restore ops are run automatically as soon as the network is built (on first call for user-defined classes inheriting from Model, immediately if it is already built).
> 
> We can verify if the object is of type, **`tf.train.Checkpoint.restore`**. Thanks!

Hi, the return value exists only when restoring TF checkpoints. The issue is about return value when loading HDF5 weights. The documentation also mentions that when loading HDF5 files, the return value is `None`

**Comment by Venkat6871** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
