### ISSUE TITLE
Do you really guys calculate the gates values in LSTM?

### ISSUE THREAD

**Issue by dialgop** [tensorflow/tensorflow#3523]
Hello guys, I was checking at the code in the classes BasicLSTMCell  as well as LSTMCell and I don't see you use formulas to get the values of the gates (output, input and forget) is this procedure you guys use really valid (since gates have their own calculation)?

in the _linear method (which you use) I just see matmul, concat and some functions from variable_scope.py However if you did it in another way, I would like to know it.

**Comment by michaelisard** [comment]
I think this question is better suited to [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) unless you determine that there's a specific bug that needs to be addressed.
