### ISSUE TITLE
Undefined symbols for architecture x86_64: _deflate (zlib)

### ISSUE THREAD

**Issue by morgangiraud** [tensorflow/tensorflow#3524]
Hi!

I was trying to reproduce one of my previous work on tensorflow on IOS when I stumble upon this error:

```
Undefined symbols for architecture x86_64:
  "_deflate", referenced from:
      tensorflow::io::ZlibOutputBuffer::Deflate(int) in libtensorflow-core.a(zlib_outputbuffer.o)
  "_deflateEnd", referenced from:
      tensorflow::io::ZlibOutputBuffer::Close() in libtensorflow-core.a(zlib_outputbuffer.o)
  "_deflateInit2_", referenced from:
      tensorflow::io::ZlibOutputBuffer::ZlibOutputBuffer(tensorflow::WritableFile*, int, int, tensorflow::io::ZlibCompressionOptions const&) in libtensorflow-core.a(zlib_outputbuffer.o)
  "_inflate", referenced from:
      tensorflow::io::ZlibInputBuffer::Inflate() in libtensorflow-core.a(zlib_inputbuffer.o)
  "_inflateEnd", referenced from:
      tensorflow::io::ZlibInputBuffer::~ZlibInputBuffer() in libtensorflow-core.a(zlib_inputbuffer.o)
      tensorflow::io::ZlibInputBuffer::~ZlibInputBuffer() in libtensorflow-core.a(zlib_inputbuffer.o)
  "_inflateInit2_", referenced from:
      tensorflow::io::ZlibInputBuffer::ZlibInputBuffer(tensorflow::RandomAccessFile*, unsigned long, unsigned long, tensorflow::io::ZlibCompressionOptions const&) in libtensorflow-core.a(zlib_inputbuffer.o)
```
Step i did:
- I cloned tensorflow at 10am 27/07/2016, paris timezone
- I ran gen_files_list.sh
- I compile tensorflow on IOS using the compile_all_ios.sh script on my project: ❌
- I git reset --hard HEAD
- I compile tensorflow on IOS using the compile_all_ios.sh script on my project: ❌

It works on the simple IOS examples.
Do you have any hint on this one ?

Other info:
- Mac OSX v 10.11.5
- Tensorflow on master branch

**Comment by martinwicke** [comment]
I suspect the makefile doesn't properly add -lz. @petewarden would know.

**Comment by morgangiraud** [comment]
Some more information:
In the `proto_text_cc_files.txt`, i've compilled tensorflow **with** and **without** those lines:
```
tensorflow/core/lib/io/zlib_outputbuffer.cc
tensorflow/core/lib/io/zlib_inputbuffer.cc
```
Nothing changed.

**Comment by petewarden** [comment]
I believe I've fixed this now, with the addition of zlib to the linking stage of the OS X part of the iOS build. Closing for now, but please reopen if you're still hitting issues.

**Comment by liliang027** [comment]
I have the save issue with the latest code:

Undefined symbols for architecture x86_64:
  "_deflate", referenced from:
      tensorflow::io::ZlibOutputBuffer::Deflate(int) in zlib_outputbuffer.o
  "_deflateEnd", referenced from:
      tensorflow::io::ZlibOutputBuffer::Close() in zlib_outputbuffer.o
  "_deflateInit2_", referenced from:
      tensorflow::io::ZlibOutputBuffer::Init() in zlib_outputbuffer.o
  "_inflate", referenced from:
      tensorflow::io::ZlibInputStream::Inflate() in zlib_inputstream.o
  "_inflateEnd", referenced from:
      tensorflow::io::ZlibInputStream::~ZlibInputStream() in zlib_inputstream.o
  "_inflateInit2_", referenced from:
      tensorflow::io::ZlibInputStream::InitZlibBuffer() in zlib_inputstream.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [/Users/bruce/workspace/tensorflow-master/tensorflow/contrib/makefile/gen/host_bin/proto_text] Error 1
+ '[' 2 -ne 0 ']'
+ echo 'arm7vs compilation failed.'
arm7vs compilation failed.
+ exit 1
