### ISSUE TITLE
tensorflow 2.0 tf.linalg.normalize yields nan

### ISSUE THREAD

**Issue by hyperji** [tensorflow/tensorflow#35257]
### tf.linalg.normalize(np.zeros([10, 4]), ord=1, axis=-1) yields nan as below

(<tf.Tensor: id=58, shape=(10, 4), dtype=float64, numpy=
 array([[nan, nan, nan, nan],
        [nan, nan, nan, nan],
        [nan, nan, nan, nan],
        [nan, nan, nan, nan],
        [nan, nan, nan, nan],
        [nan, nan, nan, nan],
        [nan, nan, nan, nan],
        [nan, nan, nan, nan],
        [nan, nan, nan, nan],
        [nan, nan, nan, nan]])>,
 <tf.Tensor: id=57, shape=(10, 1), dtype=float64, numpy=
 array([[0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.]])>)

* I know this is caused by divide by 0, so in the future tensorflow should make this operation more numerically stable.

**Comment by ravikyram** [comment]
I have tried on colab with TF version 2.0 ,2.1.0-rc1 and was able to reproduce the issue.Please, find the gist [here](https://colab.sandbox.google.com/gist/ravikyram/050a8b84e6e584ca6567697b674e8230/untitled490.ipynb). Thanks!

**Comment by rmlarsen** [comment]
This seems to be working as intended. How would you normalize 0? The NaN tell you that you tried something that is not well defined, exactly as intended.

**Comment by wandering007** [comment]
@hyperji You can use tf.math.l2_normalize instead. ( https://www.tensorflow.org/api_docs/python/tf/math/l2_normalize )
