### ISSUE TITLE
tensorflow build fails

### ISSUE THREAD

**Issue by FranzBl** [tensorflow/tensorflow#35253]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform Windows 10 Pro
- desktop computer:
- TensorFlow installed from source
- TensorFlow version: 2.0
- Python version: 3.7
- Installed using virtualenv? pip? conda?: installed via command line / git clone etc.
- Bazel version (if compiling from source): 1.1.0
- GCC/Compiler version (if compiling from source): Visual Studio 2017 Redistributables
- CUDA/cuDNN version: --- (ROCm selected)
- GPU model and memory:  AMD FX-8800P R7

Build fails, see listing below.

C:\Users\Bludorf\tensorflow>python ./configure.py
WARNING: Running Bazel server needs to be killed, because the startup options are different.
WARNING: Waiting for server process to terminate (waited 5 seconds, waiting at most 60)
WARNING: Waiting for server process to terminate (waited 10 seconds, waiting at most 60)
WARNING: --batch mode is deprecated. Please instead explicitly shut down your Bazel server using the command "bazel shutdown".
You have bazel 1.1.0 installed.
Please specify the location of python. [Default is C:\Users\Bludorf\AppData\Local\Programs\Python\Python37\python.exe]: 

Found possible Python library paths:
  C:\Users\Bludorf\AppData\Local\Programs\Python\Python37\lib\site-packages
Please input the desired Python library path to use.  Default is [C:\Users\Bludorf\AppData\Local\Programs\Python\Python37\lib\site-packages]

Do you wish to build TensorFlow with XLA JIT support? [y/N]: y
XLA JIT support will be enabled for TensorFlow.

Do you wish to build TensorFlow with ROCm support? [y/N]: y
ROCm support will be enabled for TensorFlow.

Do you wish to build TensorFlow with CUDA support? [y/N]: N
No CUDA support will be enabled for TensorFlow.

Please specify optimization flags to use during compilation when bazel option "--config=opt" is specified [Default is /arch:AVX]:

Would you like to override eigen strong inline for some C++ compilation to reduce the compilation time? [Y/n]: Y
Eigen strong inline overridden.

Preconfigured Bazel build configs. You can use any of the below by adding "--config=<>" to your build command. See .bazelrc for more details.
        --config=mkl            # Build with MKL support.
        --config=monolithic     # Config for mostly static monolithic build.
        --config=ngraph         # Build with Intel nGraph support.
        --config=numa           # Build with NUMA support.
        --config=dynamic_kernels        # (Experimental) Build kernels into separate shared objects.
        --config=v2             # Build TensorFlow 2.x instead of 1.x.
Preconfigured Bazel build configs to DISABLE default on features:
        --config=noaws          # Disable AWS S3 filesystem support.
        --config=nogcp          # Disable GCP support.
        --config=nohdfs         # Disable HDFS support.
        --config=nonccl         # Disable NVIDIA NCCL support.

C:\Users\Bludorf\tensorflow>bazel build --config=v2 //tensorflow/tools/pip_package:build_pip_package
Starting local Bazel server and connecting to it...
WARNING: The following configs were expanded more than once: [v2]. For repeatable flags, repeats are counted twice and may lead to unexpected behavior.
INFO: Writing tracer profile to 'C:/users/bludorf/_bazel_bludorf/jkbqqwso/command.profile.gz'
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=1 --terminal_columns=120
INFO: Options provided by the client:
  'build' options: --python_path=C:/Users/Bludorf/AppData/Local/Programs/Python/Python37/python.exe
INFO: Reading rc options for 'build' from c:\users\bludorf\tensorflow\.bazelrc:
  'build' options: --apple_platform_type=macos --define framework_shared_object=true --define open_source_build=true --java_toolchain=//third_party/toolchains/java:tf_java_toolchain --host_java_toolchain=//third_party/toolchains/java:tf_java_toolchain --define=use_fast_cpp_protos=true --define=allow_oversize_protos=true --spawn_strategy=standalone -c opt --announce_rc --define=grpc_no_ares=true --noincompatible_remove_legacy_whole_archive --enable_platform_specific_config --config=v2
INFO: Reading rc options for 'build' from c:\users\bludorf\tensorflow\.tf_configure.bazelrc:
  'build' options: --action_env PYTHON_BIN_PATH=C:/Users/Bludorf/AppData/Local/Programs/Python/Python37/python.exe --action_env PYTHON_LIB_PATH=C:/Users/Bludorf/AppData/Local/Programs/Python/Python37/lib/site-packages --python_path=C:/Users/Bludorf/AppData/Local/Programs/Python/Python37/python.exe --config=xla --config=rocm --define=override_eigen_strong_inline=true --action_env TF_CONFIGURE_IOS=0
INFO: Found applicable config definition build:v2 in file c:\users\bludorf\tensorflow\.bazelrc: --define=tf_api_version=2 --action_env=TF2_BEHAVIOR=1
INFO: Found applicable config definition build:xla in file c:\users\bludorf\tensorflow\.bazelrc: --action_env=TF_ENABLE_XLA=1 --define=with_xla_support=true
INFO: Found applicable config definition build:xla in file c:\users\bludorf\tensorflow\.tf_configure.bazelrc: --define with_xla_support=true
INFO: Found applicable config definition build:rocm in file c:\users\bludorf\tensorflow\.bazelrc: --crosstool_top=@local_config_rocm//crosstool:toolchain --define=using_rocm=true --define=using_rocm_hipcc=true --action_env TF_NEED_ROCM=1
INFO: Found applicable config definition build:v2 in file c:\users\bludorf\tensorflow\.bazelrc: --define=tf_api_version=2 --action_env=TF2_BEHAVIOR=1
INFO: Found applicable config definition build:windows in file c:\users\bludorf\tensorflow\.bazelrc: --copt=/w --cxxopt=/std:c++14 --host_cxxopt=/std:c++14 --config=monolithic --copt=-DWIN32_LEAN_AND_MEAN --host_copt=-DWIN32_LEAN_AND_MEAN --copt=-DNOGDI --host_copt=-DNOGDI --linkopt=/DEBUG --host_linkopt=/DEBUG --linkopt=/OPT:REF --host_linkopt=/OPT:REF --linkopt=/OPT:ICF --host_linkopt=/OPT:ICF --experimental_strict_action_env=true --incompatible_windows_native_test_wrapper --verbose_failures --distinct_host_configuration=false
INFO: Found applicable config definition build:monolithic in file c:\users\bludorf\tensorflow\.bazelrc: --define framework_shared_object=false
INFO: Call stack for the definition of repository 'io_bazel_rules_docker' which is a git_repository (rule definition at C:/users/bludorf/_bazel_bludorf/jkbqqwso/external/bazel_tools/tools/build_defs/repo/git.bzl:195:18):
 - C:/users/bludorf/_bazel_bludorf/jkbqqwso/external/bazel_toolchains/repositories/repositories.bzl:37:9
 - C:/users/bludorf/tensorflow/WORKSPACE:37:1
ERROR: An error occurred during the fetch of repository 'io_bazel_rules_docker':
   Traceback (most recent call last):
        File "C:/users/bludorf/_bazel_bludorf/jkbqqwso/external/bazel_tools/tools/build_defs/repo/git.bzl", line 177
                _clone_or_update(ctx)
        File "C:/users/bludorf/_bazel_bludorf/jkbqqwso/external/bazel_tools/tools/build_defs/repo/git.bzl", line 36, in _clone_or_update
                git_repo(ctx, directory)
        File "C:/users/bludorf/_bazel_bludorf/jkbqqwso/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 91, in git_repo
                _update(ctx, git_repo)
        File "C:/users/bludorf/_bazel_bludorf/jkbqqwso/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 101, in _update
                init(ctx, git_repo)
        File "C:/users/bludorf/_bazel_bludorf/jkbqqwso/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 115, in init
                _error(ctx.name, cl, st.stderr)
        File "C:/users/bludorf/_bazel_bludorf/jkbqqwso/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 181, in _error
                fail(<1 more arguments>)
error running 'git init C:/users/bludorf/_bazel_bludorf/jkbqqwso/external/io_bazel_rules_docker' while working with @io_bazel_rules_docker:
java.io.IOException: ERROR: src/main/native/windows/process.cc(199): CreateProcessW("git" init C:/users/bludorf/_bazel_bludorf/jkbqqwso/external/io_bazel_rules_docker): Das System kann die angegebene Datei nicht finden.
 (error: 2)
ERROR: no such package '@io_bazel_rules_docker//repositories': Traceback (most recent call last):
        File "C:/users/bludorf/_bazel_bludorf/jkbqqwso/external/bazel_tools/tools/build_defs/repo/git.bzl", line 177
                _clone_or_update(ctx)
        File "C:/users/bludorf/_bazel_bludorf/jkbqqwso/external/bazel_tools/tools/build_defs/repo/git.bzl", line 36, in _clone_or_update
                git_repo(ctx, directory)
        File "C:/users/bludorf/_bazel_bludorf/jkbqqwso/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 91, in git_repo
                _update(ctx, git_repo)
        File "C:/users/bludorf/_bazel_bludorf/jkbqqwso/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 101, in _update
                init(ctx, git_repo)
        File "C:/users/bludorf/_bazel_bludorf/jkbqqwso/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 115, in init
                _error(ctx.name, cl, st.stderr)
        File "C:/users/bludorf/_bazel_bludorf/jkbqqwso/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 181, in _error
                fail(<1 more arguments>)
error running 'git init C:/users/bludorf/_bazel_bludorf/jkbqqwso/external/io_bazel_rules_docker' while working with @io_bazel_rules_docker:
java.io.IOException: ERROR: src/main/native/windows/process.cc(199): CreateProcessW("git" init C:/users/bludorf/_bazel_bludorf/jkbqqwso/external/io_bazel_rules_docker): Das System kann die angegebene Datei nicht finden.
 (error: 2)
ERROR: no such package '@io_bazel_rules_docker//repositories': Traceback (most recent call last):
        File "C:/users/bludorf/_bazel_bludorf/jkbqqwso/external/bazel_tools/tools/build_defs/repo/git.bzl", line 177
                _clone_or_update(ctx)
        File "C:/users/bludorf/_bazel_bludorf/jkbqqwso/external/bazel_tools/tools/build_defs/repo/git.bzl", line 36, in _clone_or_update
                git_repo(ctx, directory)
        File "C:/users/bludorf/_bazel_bludorf/jkbqqwso/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 91, in git_repo
                _update(ctx, git_repo)
        File "C:/users/bludorf/_bazel_bludorf/jkbqqwso/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 101, in _update
                init(ctx, git_repo)
        File "C:/users/bludorf/_bazel_bludorf/jkbqqwso/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 115, in init
                _error(ctx.name, cl, st.stderr)
        File "C:/users/bludorf/_bazel_bludorf/jkbqqwso/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 181, in _error
                fail(<1 more arguments>)
error running 'git init C:/users/bludorf/_bazel_bludorf/jkbqqwso/external/io_bazel_rules_docker' while working with @io_bazel_rules_docker:
java.io.IOException: ERROR: src/main/native/windows/process.cc(199): CreateProcessW("git" init C:/users/bludorf/_bazel_bludorf/jkbqqwso/external/io_bazel_rules_docker): Das System kann die angegebene Datei nicht finden.
 (error: 2)
INFO: Elapsed time: 7.563s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)

**Comment by FranzBl** [comment]
I could verify that this problem happens in version bazel 1.0.0 and higher. Lower versions are not allowed to build tensorflow:

-------> bazel 0.29.1

C:\Users\Bludorf\tensorflow>bazel version
Extracting Bazel installation...
Starting local Bazel server and connecting to it...
Build label: 0.29.1
Build target: bazel-out/x64_windows-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Tue Sep 10 13:45:30 2019 (1568123130)
Build timestamp: 1568123130
Build timestamp as int: 1568123130

C:\Users\Bludorf\tensorflow>python ./configure.py
WARNING: Running Bazel server needs to be killed, because the startup options are different.
WARNING: Waiting for server process to terminate (waited 5 seconds, waiting at most 60)
WARNING: Waiting for server process to terminate (waited 10 seconds, waiting at most 60)
WARNING: --batch mode is deprecated. Please instead explicitly shut down your Bazel server using the command "bazel shutdown".
You have bazel 0.29.1 installed.
Please upgrade your bazel installation to version 1.0.0 or higher to build TensorFlow!

C:\Users\Bludorf\tensorflow>

-------> bazel 1.0.0

C:\Users\Bludorf\tensorflow>bazel version
Starting local Bazel server and connecting to it...
Server crashed during startup. Now printing c:\users\bludorf\_bazel_bludorf\jkbqqwso\server\jvm.out
I/O Error: C:/users/bludorf/_bazel_bludorf/jkbqqwso/server/server_info.rawproto.tmp -> C:/users/bludorf/_bazel_bludorf/jkbqqwso/server/server_info.rawproto (Permission denied)

C:\Users\Bludorf\tensorflow>

**Comment by FranzBl** [comment]
By now, this situation is without solution, since newer bazel versions than 1.1.0 are not accepted to build tensorflow.
Did anyone ever build tensorflow on Windows successfully? It doesn't seem so.
By the way, on Ubuntu tensorflow doesn't build from source either, from other (but similar) reasons. So it looks like all amd gpu's that need opengl are unable to be used with tensorflow.

**Comment by ashutoshbsathe** [comment]
I was able to build TensorFlow 2.0 with CUDA support successfully on Windows 10.
I needed following to be added at the top of my workspace file in order to build successfully:
```
http_archive(
name = "io_bazel_rules_docker",
sha256 = "aed1c249d4ec8f703edddf35cbe9dfaca0b5f5ea6e4cd9e83e99f3b0d1136c3d",
strip_prefix = "rules_docker-0.7.0",
urls = ["https://github.com/bazelbuild/rules_docker/archive/v0.7.0.tar.gz"],
)
```
The fix was suggested by discussion in another issue [here](https://github.com/tensorflow/tensorflow/issues/27576#issuecomment-504703397). I'm using Windows 10, Python 3.7 in Anaconda virtual environment, Visual Studio 2017, Bazel 0.28.0

**Comment by mpmischitelli** [comment]
I can confirm that the solution given by @ashutoshbsathe does indeed work under Windows. Of course it is preferable to update rules_docker to the latest version possible (I'm currently building using 0.12.0). For your convenience, this is the updated rule:

```
http_archive(
    name = "io_bazel_rules_docker",
    sha256 = "413bb1ec0895a8d3249a01edf24b82fd06af3c8633c9fb833a0cb1d4b234d46d",
    strip_prefix = "rules_docker-0.12.0",
    urls = ["https://github.com/bazelbuild/rules_docker/archive/v0.12.0.tar.gz"],
)
```

**Comment by amahendrakar** [comment]
@FranzBl,
Is this still an issue?

Could you please follow the official [build form source guide](https://www.tensorflow.org/install/source_windows) and check if you are facing the same issue with TF v2.4 as well? Thanks!
