### ISSUE TITLE
LSTMCell initialization issue ( get_initial_state )

### ISSUE THREAD

**Issue by niranjan8129** [tensorflow/tensorflow#35251]
Hi,
When I am using get_initial_state to initialize, I am getting error below . 
Could you please suggest me how to initialize LSTMCell cell? 

lstm_cell = tf.keras.layers.LSTM(units=128)
lstm_cell = tf.nn.RNNCellDropoutWrapper(   lstm_cell,    output_keep_prob=self.dropout_keep_prob)
self._initial_state = **lstm_cell.get_initial_state(128, tf.float32)**

**ValueError**: slice index 0 of dimension 0 out of bounds. for strided_slice (op: StridedSlice) with input shapes: [0], [1], [1], [1] and with computed input tensors: input[1] = <0>, input[2] = <1>, input[3] = <1>.

**Comment by oanush** [comment]
@niranjan8129 ,
Can you please provide the code to reproduce the error reported?Kindly mention TF version being used.
Meanwhile also refer to this [link](https://stackoverflow.com/questions/50385447/how-to-deal-with-keras-erroslice-index-0-of-dimension-0-out-of-bounds) and let us know if it helps solving your issue,Thanks!

**Comment by niranjan8129** [comment]
@oanush 

I am working on Tensorflow 2.0. Here is the colab reproduce the error . there is no zero_state in lSTM cell on the TF2.0 version. They added new syntax **get_initial_state**.

**self._initial_state = lstm_cell.get_initial_state(128, tf.float32)** 

https://colab.sandbox.google.com/gist/ravikyram/304d34ec814dbbf13ed63b5a23416ab1/untitled458.ipynb

OR

you can go through the below steps.

!git clone https://github.com/niranjan8129/classification_tensorflow

!pip install tensorflow-gpu==2.0.0-beta1
from google.colab import drive
dirpath=drive.mount('/classification_tensorflow')

!chmod 777 classification_tensorflow
!python ./classification_tensorflow/train.py ./classification_tensorflow/data/train.csv.zip ./classification_tensorflow/training_config.json

**Comment by ymodak** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.
 Thanks!
