### ISSUE TITLE
module 'tensorflow._api.v1.keras.layers' has no attribute 'DenseFeatures'

### ISSUE THREAD

**Issue by WakerKQ** [tensorflow/tensorflow#35254]
I want to use feature column as input to my customed model. I do as the answer 
 of the question suggested,   
https://stackoverflow.com/questions/54375298/how-to-use-tensorflow-feature-columns-as-input-to-a-keras-model

feature_layer = tf.keras.layers.DenseFeatures(feature_columns=feature_columns)

but i got the error as below:

AttributeError                            Traceback (most recent call last)
<ipython-input-23-db9a4807151e> in <module>
----> 1 feature_layer = tf.keras.layers.DenseFeatures(feature_columns=feature_columns)
      2 # feature_layer_outputs = feature_layer(feature_layer_inputs)

AttributeError: module 'tensorflow._api.v1.keras.layers' has no attribute 'DenseFeatures'

I use tensorflow 1.14 and keras version 2.2.4
Does anyone could tell me how to fix it, thanks very much!

**Comment by amahendrakar** [comment]
In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thanks!

**Comment by boronhub** [comment]
One thing you can try is using tf.compat.v1.keras.layers.DenseFeatures if your project requires TF 1.14. If not, consider upgrading to TensorFlow 2.0

**Comment by WakerKQ** [comment]
> In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thanks!

my code snippet is basically like this:

from __future__ import absolute_import, division, print_function

import numpy as np
import pandas as pd
from tensorflow import feature_column
from tensorflow import keras
from tensorflow.keras import layers
from sklearn.model_selection import train_test_split

URL = 'https://storage.googleapis.com/applied-dl/heart.csv'
dataframe = pd.read_csv(URL)
dataframe.head()

train, test = train_test_split(dataframe, test_size=0.2)
train, val = train_test_split(train, test_size=0.2)
print(len(train), 'train examples')
print(len(val), 'validation examples')
print(len(test), 'test examples')

def df_to_dataset(dataframe, shuffle=True, batch_size=32):
  dataframe = dataframe.copy()
  labels = dataframe.pop('target')
  ds = tf.data.Dataset.from_tensor_slices((dict(dataframe), labels))
  if shuffle:
    ds = ds.shuffle(buffer_size=len(dataframe))
  ds = ds.batch(batch_size)
  return ds

batch_size = 5 # A small batch sized is used for demonstration purposes
train_ds = df_to_dataset(train, batch_size=batch_size)
val_ds = df_to_dataset(val, shuffle=False, batch_size=batch_size)
test_ds = df_to_dataset(test, shuffle=False, batch_size=batch_size)

age = feature_column.numeric_column("age")
feature_columns = []
feature_layer_inputs = {}


for header in ['age', 'trestbps', 'chol', 'thalach', 'oldpeak', 'slope', 'ca']:
  feature_columns.append(feature_column.numeric_column(header))
  feature_layer_inputs[header] = tf.keras.Input(shape=(1,), name=header)

age_buckets = feature_column.bucketized_column(age, boundaries=[18, 25, 30, 35, 40, 45, 50, 55, 60, 65])
feature_columns.append(age_buckets)


thal = feature_column.categorical_column_with_vocabulary_list(
      'thal', ['fixed', 'normal', 'reversible'])
thal_one_hot = feature_column.indicator_column(thal)
feature_columns.append(thal_one_hot)
feature_layer_inputs['thal'] = tf.keras.Input(shape=(1,), name='thal', dtype=tf.string)

batch_size = 32
train_ds = df_to_dataset(train, batch_size=batch_size)
val_ds = df_to_dataset(val, shuffle=False, batch_size=batch_size)
test_ds = df_to_dataset(test, shuffle=False, batch_size=batch_size)

feature_layer = tf.keras.layers.DenseFeatures(feature_columns)

**Comment by WakerKQ** [comment]
> One thing you can try is using tf.compat.v1.keras.layers.DenseFeatures if your project requires TF 1.14. If not, consider upgrading to TensorFlow 2.0

Yes, my project requeres TF1.14, I tried tf.compat.v1.keras.layers.DenseFeatures but it did not work.  I will try TensorFlow 2.0.

**Comment by amahendrakar** [comment]
@WakerKQ,
I was able to run the code with TF version 1.14, without any errors. Please check for the attached [Gist here](https://colab.sandbox.google.com/gist/amahendrakar/94f228a23ba7881553acd24dfd52e2f8/35254.ipynb). Thanks!

**Comment by WakerKQ** [comment]
> @WakerKQ,
> I was able to run the code with TF version 1.14, without any errors. Please check for the attached [Gist here](https://colab.sandbox.google.com/gist/amahendrakar/94f228a23ba7881553acd24dfd52e2f8/35254.ipynb). Thanks!

Thanks for your helpful answers, both should work.   I upgraded to TF2.0 and solved the problem.

**Comment by amahendrakar** [comment]
Closing issue as it is resolved.
