### ISSUE TITLE
While using tf.import_graph_def: ValueError: Input 1 of node StatefulPartitionedCall

### ISSUE THREAD

**Issue by caibadal5** [tensorflow/tensorflow#35272]
I am trying to freeze and obfuscate my model but when running:
tf.import_graph_def(graph_def, name='')

I am getting the error:
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "a.py", line 129, in <module>
    optimize_model('/home/xxxx/Desktop/Pervasive/Projects/Ofuscar/1576096897/','/home/xxxx/Desktop/Pervasive/Projects/Ofuscar/out/')
  File "a.py", line 123, in optimize_model
    convert_graph_def_to_saved_model(output_model_dir, input_nodes, output_nodes, graph_filepath)
  File "a.py", line 99, in convert_graph_def_to_saved_model
    tf.import_graph_def(graph_def, name='')
  File "/usr/local/lib/python3.5/dist-packages/tensorflow_core/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow_core/python/framework/importer.py", line 405, in import_graph_def
    producer_op_list=producer_op_list)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow_core/python/framework/importer.py", line 505, in _import_graph_def_internal
    raise ValueError(str(e))
ValueError: Input 1 of node StatefulPartitionedCall was passed float from NASNet/conv0/weights:0 incompatible with expected resource.

The graph_def was loaded with the function:
def get_graph_def_from_file(graph_filepath):
    with tf.Graph().as_default():
        with tf.gfile.GFile(graph_filepath, 'rb') as f:
            graph_def = tf.GraphDef()
            graph_def.ParseFromString(f.read())
            return graph_def

**Comment by gadagashwini** [comment]
@caibadal5, Please provide the complete standalone code and Tensorflow version that your using. Thanks!

**Comment by gadagashwini** [comment]
@caibadal5, Any update on code!

**Comment by caibadal5** [comment]
The main part of the code is the one I showed. I have used tf 1.15.0 both for the saved model and for this code. Thank you for your patience!

**Comment by gadagashwini** [comment]
@caibadal5, Looks like code is incomplete please provide the complete code and necessary files to replicate the issue. Thanks!

**Comment by caibadal5** [comment]
It's a model that we are selling to a company, I don't feel comfortable publishing it on git :) Thanks for your interest anyway

**Comment by gadagashwini** [comment]
@caibadal5, Can you provide minimal code snippet which replicates the reported issue to analyze.

**Comment by gadagashwini** [comment]
Closing the issue. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Comment by christegho** [comment]
Were you able to resolve this issue? I am having something similar when importing a graph with tf1.15

**Comment by Zhiwei35** [comment]
Were you able to resolve this issue? I am having something similar when importing a graph with tf 2.4
