### ISSUE TITLE
rnn.bidirectional_dynamic_rnn doesn't really take sequence_length of int32s

### ISSUE THREAD

**Issue by jonrein** [tensorflow/tensorflow#3528]
The docstring for rnn.bidirectional_dynamic_rnn indicates that the sequence_length argument can be an int32/int64 vector, but array_ops.reverse_sequence only accepts an int64 vector as its seq_lengths argument.  I'll leave it to you whether the solution is to modify reverse_sequence or just amend the docstring.

**Comment by michaelisard** [comment]
@ebrevdo would you make the call?

**Comment by ebrevdo** [comment]
We can also cast up to int64.

**Comment by michaelisard** [comment]
Any preference?

**Comment by jonrein** [comment]
Personally, I'm using the same sequence_length tensor in a ctc_ops call down the line which requires int32, so it'd be nice to have those consistent.

**Comment by ebrevdo** [comment]
They will be consistent; ctc_ops can continue working with the int32
version.

Unless you have sequence lengths greater than 2**31-1, the values are the
same.

**Comment by avostryakov** [comment]
@ebrevdo  Can I suggest another fix? If sequence_length = None, array_ops.reverse_sequence will not work. I think the patch is trivial: 
if sequence_length:
  inputs_reverse = array_ops.reverse_sequence(
        input=inputs, seq_lengths=sequence_length,
        seq_dim=time_dim, batch_dim=batch_dim)
else:
  dims = [False]*tf.rank(inputs)
  dims[time_dim] = True
  inputs_reverse = array_ops.reverse(input=inputs, dims=dims)

**Comment by avostryakov** [comment]
And I agree with @jonrein, it will be easier to have possibility to use int32 too.

**Comment by ebrevdo** [comment]
This is pretty easy to do by adding a few lines to the reverse sequence op declaration under core/ops/ and instantiating some additional tempaltes in core/kernels/.  Contributions welcome.

**Comment by suiyuan2009** [comment]
in dynamic_rnn, seq_length will first be cast to int32, [dynamic_rnn](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/ops/rnn.py#L787)

**Comment by guotong1988** [comment]
@ebrevdo If this bug haven't been fixed , I want to working on it.

**Comment by ebrevdo** [comment]
Contributions welcome

**Comment by guotong1988** [comment]
It seems suiyuan2009 fixed it.

**Comment by yongtang** [comment]
I think this issue could be closed as PR #3774 adds the int32 support?

**Comment by ebrevdo** [comment]
Thanks!
