### ISSUE TITLE
OneDeviceStrategy allocates memory on two GPUs

### ISSUE THREAD

**Issue by olk** [tensorflow/tensorflow#35298]
**System information**
- OS Platform and Distribution: Arch Linux, 5.4.2-arch1-1-ARCH
- TensorFlow installed from: binary
- TensorFlow version: 2.1.0rc1
- Keras version: 2.2.4-tf
- Python version: 3.8
- GPU model and memory: 2x GTX 1080 Ti 11GB"`

**Describe the current behavior**
OneDeviceStrategy is set to use GPU0 but allocates full memory at GPU0 and GPU1 too.
On both GPUs 11GB are allocated.
Using not Strategy (simple plain TF code) - the memory is allocated only at GPU0.

**Describe the expected behavior**
OneDeviceStrategy is set to use GPU0 allocates memory only at GPU0 as the code does if OneDeviceStrategy is not used.

**Comment by gadagashwini** [comment]
@olk, Could you post the standalone code to analyze the issue. Thanks!

**Comment by olk** [comment]
```
import tensorflow as tf
  import tensorflow_datasets as tfds
  import time
  
  from tensorflow.keras.optimizers import Adam
  
  def build_model():
      filters = 48
      units = 24
      kernel_size = 7
      learning_rate = 1e-4
      model = tf.keras.Sequential([
        tf.keras.layers.Conv2D(filters=filters, kernel_size=(kernel_size, kernel_size), activation='relu', input_shape=(28, 28, 1)),
        tf.keras.layers.MaxPooling2D(),
        tf.keras.layers.Flatten(),
        tf.keras.layers.Dense(units, activation='relu'),
        tf.keras.layers.Dense(10, activation='softmax')
      ])
      model.compile(loss='sparse_categorical_crossentropy', optimizer=Adam(learning_rate), metrics=['accuracy'])
      return model
  
  datasets, info = tfds.load(name='mnist', with_info=True, as_supervised=True)
  mnist_train, mnist_test = datasets['train'], datasets['test']
  
  num_train_examples = info.splits['train'].num_examples
  num_test_examples = info.splits['test'].num_examples
  
  strategy = tf.distribute.OneDeviceStrategy(device='/gpu:0')
  #strategy = tf.distribute.MirroredStrategy()
  print('Number of devices: {}'.format(strategy.num_replicas_in_sync))
  
  BUFFER_SIZE = 10000
  BATCH_SIZE = 32
  
  def scale(image, label):
    image = tf.cast(image, tf.float32)
    image /= 255
    return image, label
  
  train_dataset = mnist_train.map(scale).shuffle(BUFFER_SIZE).repeat().batch(BATCH_SIZE).prefetch(buffer_size=tf.data.experimental.AUTOTUNE)
  eval_dataset = mnist_test.map(scale).repeat().batch(BATCH_SIZE).prefetch(buffer_size=tf.data.experimental.AUTOTUNE)
  
  with strategy.scope():
    model = build_model()
  
  epochs=5
  start = time.perf_counter()
  model.fit(
          train_dataset,
          validation_data=eval_dataset,
          steps_per_epoch=num_train_examples/epochs,
          validation_steps=num_test_examples/epochs,
          epochs=epochs)
  elapsed = time.perf_counter() - start
  print('elapsed: {:0.3f}'.format(elapsed))
```

**Comment by anj-s** [comment]
olk@ TensorFlow by default maps all the GPU memory on all available GPUs for a given process. To limit the number of GPUs you want to use you can use the `tf.config.experimental.set_visible_devices` option. There is also an option for memory growth. More details can be found [here](https://www.tensorflow.org/guide/gpu#limiting_gpu_memory_growth).

**Comment by olk** [comment]
@ anj-s c TF allocates 100% memory on **both GPUs** if I use **OneDeviceStrategy()** !

**Comment by anj-s** [comment]
olk@ what is the behavior when you don't use OneDeviceStrategy? Also how do you determine memory allocation?

**Comment by olk** [comment]
@anj-s Using OneDeviceStrategy(device='/gpu:1') allocates memory 11GB on gpu:0 and gpu:1. The same happens if I don't use the code from above without strategy. The resource utilization is shown via nvtop and/or nvidia_smi.

**Comment by anj-s** [comment]
Just to clarify the behavior is the same with and without strategy. Did using tf.config.experimental.set_visible_devices help?

**Comment by olk** [comment]
The same with and without strategy - I would expect that TF allocates memory only at the gpu:0 as it is specified by **OneDeviceStrategy(device='/gpu:0'))**. Otherwise I would get problems if I run a second TF app that uses the other second GPU via **OneDeviceStrategy(device='/gpu:1'))** (and both apps try to allocate memory on both GPUs).

**Comment by anj-s** [comment]
@olk As mentioned in the above [comment](https://github.com/tensorflow/tensorflow/issues/35298#issuecomment-569151712) this is expected. Please reopen the issue if you are unable to use `tf.config.experimental.set_visible_devices` successfully. Thanks!

**Comment by olk** [comment]
@anj-s I would consider it as  a bug that OneDeviceStrategy allocates (100%!) memory on other GPUs than specified in OneDeviceStrategy. I'd like to ask what's the benefit of OneDeviceStrategy compered to no using a strategy. At least the naming 'OneDeviceStrategy' is misleading.

**Comment by PrimarchOfTheSpaceWolves** [comment]
I have used tf.config.experimental.set_visible_devices() to limit things to gpu:1.  However, passing "/gpu:1" to OneDeviceStrategy fails saying it cannot find that GPU, and setting it to "/gpu:0" just allocates space on GPU 0 (physical).
Granted, one can forgo using OneDeviceStrategy altogether, but that renders OneDeviceStrategy completely moot.  The problem is that I'm writing code to switch between that and MirroredStrategy depending on how many GPUs are requested for a given code run, so it's a real shame.

**Comment by pukkinming** [comment]
FYI - I solved the issue by using the following
`import os`
`os.environ["CUDA_VISIBLE_DEVICES"] = '0'`
