### ISSUE TITLE
About bias quantization of hexagon delegate

### ISSUE THREAD

**Issue by lee-bin** [tensorflow/tensorflow#35299]
As far as I know, Tensorflow Lite uses input_scale * weight_scale as bias scale to quantize bias tensor to int32. However, hexagon use int32_min/in32_max as min/max to quantize bias tensor.
So how do you handle this difference to hexagon delegation? Below is the conv_2d builder of the hexagon delegation. I don't see where the transformation is.
https://github.com/tensorflow/tensorflow/blob/539b7642a928c7fbfb4d896f650f7e6d79c2a5e0/tensorflow/lite/experimental/delegates/hexagon/builders/conv_2d_builder.cc#L234

**Comment by karimnosseir** [comment]
Hi @lee-bin 

The delegate doesn't use int32_min/max as min max for quantization, it computes them from the scale/zero point data in the tensor
https://github.com/tensorflow/tensorflow/blob/539b7642a928c7fbfb4d896f650f7e6d79c2a5e0/tensorflow/lite/experimental/delegates/hexagon/builders/op_builder.h#L133

The quantization params in the tensor should guarantee the input_scale*weight_scale you mentioned.

Thanks

**Comment by lee-bin** [comment]
Thanks. The bias scale, this way, is the same as in lite and hexagon which guarantees the restored bias. It really helped.
