### ISSUE TITLE
cifar10 speed numbers

### ISSUE THREAD

**Issue by suhangpro** [tensorflow/tensorflow#353]
In the comments of [cifar10_train.py](https://tensorflow.googlesource.com/tensorflow/+/master/tensorflow/models/image/cifar10/cifar10_train.py), it says: 
```
Accuracy:
cifar10_train.py achieves ~86% accuracy after 100K steps (256 epochs of
data) as judged by cifar10_eval.py.

Speed: With batch_size 128.

System        | Step Time (sec/batch)  |     Accuracy
------------------------------------------------------------------
1 Tesla K20m  | 0.35-0.60              | ~86% at 60K steps  (5 hours)
1 Tesla K40m  | 0.25-0.35              | ~86% at 100K steps (4 hours)
```
The math doesn't look right to me: 
5 x 60 x 60 / 60K=**0.3** sec/batch
4 x 60 x 60 / 100K=**0.144** sec/batch

Also, on my machine (K40c, 28 CPU cores, SSD) I can only reach about half the speed (~0.6 sec/batch). Any idea what might be the factor that slows it down? Thanks!

**Comment by vrv** [comment]
I bet these numbers (both ours and yours) are probably out dated -- re-open if there's still a problem with newer releases.
