### ISSUE TITLE
A possible bug in ConvRNN2D __call__

### ISSUE THREAD

**Issue by gmrhub** [tensorflow/tensorflow#35306]
Referring to
[ConvRNN2D.__call__](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/keras/layers/convolutional_recurrent.py#L294-L341)

L308 ` kwargs['initial_state'] = initial_state` and L317 `kwargs['constants'] = constants` should be added in the else block at L340. The current situation contradicts with the use of `full_input` at L337.

I am not sure if we can simply replicate the code from its parent [RNN.__call__](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/keras/layers/recurrent.py#L640-L700).

I went ahead and tried it, but after loading the saved model weights in a complete new python session the results on validation data doesn't match at all.

I would appreciate a quick fix for local edit at least.

Thanks

**Comment by ravikyram** [comment]
Can you please  help us with simple standalone code to reproduce the issue in our environment. It helps us in localizing the issue faster. Which TensorFlow version you are using?.Thanks!

**Comment by gmrhub** [comment]
Please refer the linked issue. That support is never resolved, people tried their own ways.
So while I was skimming through the code I noticed the bug and suggested the line numbers.

It seems that feature is never tested. After fixing the code it works but has another problem of non reproducible results when re loading the weights (in a new run). I think somehow it behaves like **stateful** model, which is not.

I'm using tf 2.0, but the code in master branch is same.

Since you asked, an example model:
`
from tensorflow.keras import layers
 import tensorflow.keras as keras
encoder_inputs = layers.Input((None,3))
 encoder = layers.ConvLSTM2D(filters=32, kernel_size=(3, 3), padding="same", return_sequences=False, return_state=True)
 encoder_outputs, state_h, state_c = encoder(encoder_inputs)
 encoder_states = [state_h, state_c]

 decoder_inputs = layers.Input((None,4))
 decoder_lstm = layers.ConvLSTM2D(filters=32, kernel_size=(3, 3), padding="same", return_sequences=False, return_state=True)
 decoder_outputs, _, _ = decoder_lstm([decoder_inputs,state_h, state_c])
 output = layers.Conv2D(1, (3,3), padding="same", activation="relu")(decoder_outputs)
 model = keras.Model([encoder_inputs, decoder_inputs], output)
`

**Comment by ravikyram** [comment]
@gmrhub 
I have tried on colab with TF version 2.0,2.1.0-rc1 and i am seeing `AssertionError: `.Please, find the gist [here](https://colab.sandbox.google.com/gist/ravikyram/47bd873e15b693985657da79121bc541/untitled498.ipynb).Is this the expected behavior?

**Comment by gmrhub** [comment]
Yes, that error is due to the lines I mentioned above.

**Comment by JBLanier** [comment]
Related stackoverflow with a workaround that allowed me to train successfully (tf 1.14): [https://stackoverflow.com/questions/50253138/convlstm2d-initial-state-assertion-error](https://stackoverflow.com/questions/50253138/convlstm2d-initial-state-assertion-error)

In` ConvRNN2D.__call__()` : change
`    if K.is_keras_tensor(additional_inputs[0]):
`
to 
`  if False and K.is_keras_tensor(additional_inputs[0]):`

**Comment by qlzh727** [comment]
Sorry for the very late reply. I will take a look and fix the issue.

**Comment by gyla1993** [comment]
tf.__version__=1.15.0
tf.keras.__version__ = 2.2.4-tf

I encounter a similar problem when using tf.keras.layers.convLSTM2D with initial_state being input. The code raises the problem is
```
de_convlstm = ConvLSTM2D(filters=64, kernel_size=(5, 5), name='de_convlstm',
                             return_state=True, padding='same', return_sequences=True)
decoder_convlstm, h, c = de_convlstm(inputs=[decoder_conv2d_2, h, c])
```
Following a possible solution in https://github.com/keras-team/keras/issues/9761#issuecomment-499222895, I remove 
```
inputs, initial_state, constants = self._standardize_args(
            inputs, initial_state, constants)
```
from tensorflow_core/python/keras/layers/convolutional_recurrent.py. However, the following ValueError is reported
_ValueError: Variable <tf.Variable 'en3_trans/kernel:0' shape=(1, 1, 5, 8) dtype=float32> has `None` for gradient. Please make sure that all of your ops have a gradient defined (i.e. are differentiable). Common ops without gradient: K.argmax, K.round, K.eval_

BTW, I am really sure that my code runs well without initial_state being assigned, such as  
```
de_convlstm = ConvLSTM2D(filters=64, kernel_size=(5, 5), name='de_convlstm',
                             return_state=True, padding='same', return_sequences=True)
decoder_convlstm, h, c = de_convlstm(inputs=decoder_conv2d_2)
```
