### ISSUE TITLE
tf.math.sigmoid precision issues on GPU

### ISSUE THREAD

**Issue by guillaumekln** [tensorflow/tensorflow#35309]
**System information**
- Have I written custom code: Yes
- OS Platform and Distribution: Ubuntu 16.04
- TensorFlow installed from: binary
- TensorFlow version: `2.1.0.dev20191219`
- Python version: 3.6.8
- CUDA/cuDNN version: CUDA 10.1 / cuDNN 7.6.3
- GPU model and memory: GTX 1060 6GB

**Describe the current behavior**

We compared TensorFlow versions `2.1.0.dev20191203` and `2.1.0.dev20191219` and found some precision differences when using `tf.math.sigmoid`. Is that expected and what is the related commit?

Some results are improved (see last section) but we also find some inconsistent values on GPU when the tensor size is changing.

**Describe the expected behavior**

Sigmoid results should not depend on the tensor size.

**Code to reproduce the issue**

On GPU, going from 3 to 4 elements changes the result:

```python
>>> tf.sigmoid([34.0, 0.0, 0.0])
<tf.Tensor: shape=(3,), dtype=float32, numpy=array([1. , 0.5, 0.5], dtype=float32)>
>>> tf.sigmoid([34.0, 0.0, 0.0, 0.0])
<tf.Tensor: shape=(4,), dtype=float32, numpy=array([0.99999994, 0.5       , 0.5       , 0.5       ], dtype=float32)
```

This is especially problematic when taking the log of the sigmoid output. For reference, this is not an issue on CPU:

```python
>>> tf.sigmoid([34.0, 0.0, 0.0])
<tf.Tensor: shape=(3,), dtype=float32, numpy=array([1. , 0.5, 0.5], dtype=float32)>
>>> tf.sigmoid([34.0, 0.0, 0.0, 0.0])
<tf.Tensor: shape=(4,), dtype=float32, numpy=array([1. , 0.5, 0.5, 0.5], dtype=float32)>
```

**Other info / logs**

Here is an example of improved precision:

In `2.1.0.dev20191203`:

```python
>>> tf.sigmoid(-20.0)
<tf.Tensor: shape=(), dtype=float32, numpy=0.>
```

In `2.1.0.dev20191219`:

```python
>>> tf.sigmoid(-20.0)
<tf.Tensor: shape=(), dtype=float32, numpy=2.0611537e-09>
```

**Comment by georgesterpu** [comment]
A related issue might be https://github.com/tensorflow/tensorflow/issues/33878, thus related to eigen
There are several commits from Rasmus Larsen in the eigen repository in December, so I guess this is likely to explain the difference between `1203` and `1219` in tensorflow.

**Comment by guillaumekln** [comment]
I could no longer reproduce the issue with 2.1 and 2.2.0.dev20200212.
