### ISSUE TITLE
runnin magic_wand on efr/efm32 microcontroller

### ISSUE THREAD

**Issue by KarimelQ** [tensorflow/tensorflow#35305]
@tensorflow/micro

**System information**
- Host OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04 ( Windows SL)
- TensorFlow installed from (source or binary): source
- Tensorflow version (commit SHA if source):
- Target platform (e.g. Arm Mbed OS, Arduino Nano 33 etc.): target : efr32/efm32 (tried to compile with mbed) 

**Describe the problem**
I'm trying to run one of the provided projects on efr/efm32 microcontroller, (i choose magic_wanda example because i have an accelero & it seem's good example to start with). 
I wanted just to generate a binary file first, then make changes to adapt code with external accelerometer, itried this command:  _make -f tensorflow/lite/micro/tools/make/Makefile TARGET=mbed TAGS="CMSIS efm32pg_stk3401" magic_wand_bin_ but errors appear.
Should i do some big modifications on project to run it on efr32/efm32 micro ?
Thank's for your answers

**Please provide the exact sequence of commands/steps when you ran into the problem**

 _make -f tensorflow/lite/micro/tools/make/Makefile TARGET=mbed TAGS="CMSIS efm32pg_stk3401" magic_wand_bin

**Comment by amahendrakar** [comment]
@KarimelQ,
Could you please provide the error log and also the TensorFlow version you are using. Thanks!

**Comment by KarimelQ** [comment]
@amahendrakar This is the error log: 
fatal error: mbed.h: No such file or directory
 #include <mbed.h>
          ^~~~~~~~
compilation terminated.
tensorflow/lite/micro/tools/make/Makefile:258: recipe for target 'tensorflow/lite/micro/tools/make/gen/mbed_cortex-m4/obj/tensorflow/lite/micro/mbed/debug_log.o' failed
make: *** [tensorflow/lite/micro/tools/make/gen/mbed_cortex-m4/obj/tensorflow/lite/micro/mbed/debug_log.o] Error 1
there is no error related to mbed with other projects.
i used different versions of tf, i'm using the last version actually.

Thanks

**Comment by mohantym** [comment]
Hi @KarimelQ !
We are checking to see whether you still need help in this issue . Have you checked [documentation](https://www.tensorflow.org/lite/microcontrollers) from latest versions yet? Please post this query in [TF forum](https://discuss.tensorflow.org/)/Stackoverflow for further assistance as there will be larger community to address this issue.. Thanks!
