### ISSUE TITLE
Graphics Card Recommendation

### ISSUE THREAD

**Issue by SouradipBh** [tensorflow/tensorflow#35300]
I am running video-detection application using Yolo and FRCNN model( using Tensorflow backend).
I have to run around 50 parallel video detection simultaneously. Please advice which Graphics card or Combination of Graphics should be able to handle the load of Graphics.

My options are : -
i) 2 x RTX-TITAN
ii) 4 x RTX 2080ti
iii) 8 x GTX 1080ti

**Comment by CleanPegasus** [comment]
Will you be training a model or running a model? If you are training a model, then go with 2 x Titan RTX. If you are running the model then any of these combinations will suffice.
PS: I've never seen any computer with 8 GTX 1080ti except for mining rigs. Be careful before you buy it.

**Comment by jvishnuvardhan** [comment]
This is not Build/Installation or Bug/Performance issue. Please post this kind of support questions at [Stackoverflow](https://stackoverflow.com/questions/tagged/tensorflow). There is a big community to support and learn from your questions. GitHub is mainly for addressing bugs in installation and performance. Thanks!
