### ISSUE TITLE
TensorFlow Lite Micro fully connected int8 test passes illegal filter offset

### ISSUE THREAD

**Issue by petewarden** [tensorflow/tensorflow#35318]
An external developer pointed out that the test for the quantized fully connected operation passes in a non-zero weight offset to the kernel for int8 tests:
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/micro/kernels/fully_connected_test.cc#L118-L119

The quantization specification promises that int8 kernels will always receive zero weight offsets:
https://www.tensorflow.org/lite/performance/quantization_spec

This failing test is preventing an optimized kernel for a hardware platform from being accepted.

**Comment by pstadelmann** [comment]
ARM with CMSIS-NN optimization seems to be also affected by this issue. At least the int8 tests fail and once the same workaround as above is added [here](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/micro/kernels/cmsis-nn/fully_connected.cc), all tests pass.

**Comment by JaccovG** [comment]
This issue has been fixed by PR #38040

**Comment by saikumarchalla** [comment]
@petewarden  Can I close this issue?
