### ISSUE TITLE
Tensorflow build from source - choose patch version

### ISSUE THREAD

**Issue by FrancescoTerrosi** [tensorflow/tensorflow#35311]
**System information**
- OS Platform and Distribution: Linux Ubuntu 18.04
- TensorFlow installed from (source or binary): source
- TensorFlow version: 1.14
- Python version: 3.5
- Installed using virtualenv? pip? conda?: using conda
- Bazel version (if compiling from source): 0.24.1
- GCC/Compiler version (if compiling from source): 7.4
- CUDA/cuDNN version: CUDA 10.0, CUDNN 7
- GPU model and memory: GeForce RTX 2080 8 GB

**Describe the problem**

**Provide the exact sequence of commands / steps that you executed before running into the problem**

I'm building tensorflow 1.14 from source because I'm working with an old cpu.

Due to compatibility issues I *MUST* use version 1.14.0, however I always end up with the pip package for version 1.14.1. I read in the documentation that it was related to the bazel version installed so I downgraded to 0.24.1 (as pointed in the docs) but still, i get version 1.14.1

**Comment by gadagashwini** [comment]
@FrancescoTerrosi, Please provide the error log and exact sequence of commands/steps that you executed before running into the problem. Thanks!

**Comment by mihaimaruseac** [comment]
You need to do `git checkout v1.14.0` if you want to build the code at version 1.14.0. Checking out `r1.14` gets you the latest code on the branch, which was supposed to be for the release of 1.14.1.

As this is not really a TF issue but more a git usage one, I'm going to go ahead and close the issue.
