### ISSUE TITLE
Where is the pip package for TF 1.15?

### ISSUE THREAD

**Issue by 0x0539** [tensorflow/tensorflow#35316]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu (or similar)
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): N/A
- TensorFlow version: 1.15
- Python version: python3
- Installed using virtualenv? pip? conda?: virtualenv and pip
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

**Describe the problem**
Version 1.15 of TF does not seem to exist on pip, but the documentation [states that it does](https://www.tensorflow.org/install/pip?lang=python3#3.-install-the-tensorflow-pip-package)

**Provide the exact sequence of commands / steps that you executed before running into the problem**
```
pip3 install tensorflow==1.15
Collecting tensorflow==1.15
  Could not find a version that satisfies the requirement tensorflow==1.15 (from versions: 1.13.0rc1, 1.13.0rc2, 1.13.1, 1.13.2, 1.14.0rc0, 1.14.0rc1, 1.14.0, 2.0.0a0, 2.0.0b0, 2.0.0b1)
No matching distribution found for tensorflow==1.15
```

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.
Version 1.15 is required for einsum gradients.

**Comment by 0x0539** [comment]
Here is a [gist](https://gist.github.com/0x0539/abfd4071a7740dfaa53bdc1beaeb1c54) showing the full log output, with verbose mode.
There are tensorflow 1.15 pip modules available, but not for python3.
Next, I'll test whether I can get this working in a python2 env.

**Comment by 0x0539** [comment]
I verified that this works with a python2 environment.
Are there plans to release a python3 pip module for TF 1.15? This would be really useful for library maintainers, as they can support both versions of python for TF1.X projects.

**Comment by 0x0539** [comment]
Also, it would make the docs consistent with reality, which is always a plus :) https://www.tensorflow.org/install/pip?lang=python3#3.-install-the-tensorflow-pip-package

**Comment by mihaimaruseac** [comment]
Please upgrade `pip` version. The pip exists already, see for example https://pypi.org/project/tensorflow/1.15.0/#files

**Comment by mihaimaruseac** [comment]
In particular, you missed the `pip install --upgrade pip` part of the documentation, just slightly above the link you provided

**Comment by 0x0539** [comment]
Oh, that fixed it! Thanks!
