### ISSUE TITLE
Error: Cannot convert 'auto' to EagerTensor of dtype float

### ISSUE THREAD

**Issue by yourtheron** [tensorflow/tensorflow#35329]
Thank you for submitting a TensorFlow documentation issue. Per our GitHub
policy, we only address code/doc bugs, performance issues, feature requests, and
build/installation issues on GitHub.

The TensorFlow docs are open source! To get involved, read the documentation
contributor guide: https://www.tensorflow.org/community/contribute/docs

## URL(s) with the issue:

Please provide a link to the documentation entry, for example:
https://www.tensorflow.org/api_docs/python/tf/keras/losses/Reduction?version=stable

## Description of issue (what needs changing):

I intend to build up a custom loss function as follows:

`	from __future__ import absolute_import, division, print_function, unicode_literals
	import functools

	import numpy as np
	import tensorflow as tf

	class GeneralDiceLoss(tf.keras.losses.Loss):
		def __init__(self, reduction=tf.keras.losses.Reduction.AUTO, name='GeneralDiceLoss'):
			super().__init__(reduction=reduction, name=name)
			self.epsilon = 1e-16 
		
		
		def get_config(self):
			config = super(GeneralDiceLoss, self).get_config()
			return config
		
		def call(self, yPred, yTrue):
			#yTrue =tf.dtypes.cast(yTrue, dtype=yPred.dtype)
			# Dot product yPred and yTrue and sum them up for each datum and class
			crossProd=tf.multiply(yPred, yTrue)
			crossProdSum=tf.math.reduce_sum(crossProd, axis=np.arange(2, yTrue.ndim))
			# Calculate weight for each datum and class 
			weight = tf.math.reduce_sum(yTrue, axis=np.arange(2, yTrue.ndim))
			weight = tf.math.divide(1, tf.math.square(weight)+self.epsilon)
			# Weighted sum over classes
			numerator = 2*tf.math.reduce_sum(tf.multiply(crossProdSum, weight), axis=1)
			# Saquared summation 
			yySum = tf.math.reduce_sum(tf.math.square(yPred) + tf.math.square(yTrue), axis=np.arange(2, yTrue.ndim))
			# Weighted sum over classes
			denominator = tf.math.reduce_sum(tf.multiply(weight, yySum), axis=1)
			loss = 1 - tf.math.divide(numerator, denominator+self.epsilon)
			#loss = tf.math.reduce_mean(1 - tf.math.divide(numerator, denominator+self.epsilon))
			
			return loss
`

Then I create variables to have it test
`

	GeneralDiceLoss()
	yPred = tf.random.uniform(shape=(16, 3, 4, 4, 4))
	yTrue = tf.round(tf.random.uniform(shape=(16, 3, 4, 4, 4)))

	loss=GeneralDiceLoss(yPred, yTrue)
`
But I got an error
`

	  File "...\keras-gpu\lib\site-packages\tensorflow_core\python\framework\constant_op.py", line 96, in convert_to_eager_tensor
		return ops.EagerTensor(value, ctx.device_name, dtype)

	TypeError: Cannot convert 'auto' to EagerTensor of dtype float
`

In the doc above, 
1) there is NO clear indication or warning about conversion issue, not to mention there is NO dtype conversion in my code at all. 
2) there is NO clear example indicating which option, AUTO or SUM_OVER_BATCH_SIZE, should be adopted in one's minbatch size is greater than 1. In my case, assume my batch is 16 as exhibted in yPred and yTrue above, shall I use

`
			loss = 1 - tf.math.divide(numerator, denominator+self.epsilon)
`
or 
`
			loss = tf.math.reduce_mean(1 - tf.math.divide(numerator, denominator+self.epsilon))
`
And for which option?

Building up a custom layer/loss function is already a tough task for many practitioners, so could the doc provide more detailed explanations and examples so as to make users' life a little bit easier? Many thanks.

**Comment by amahendrakar** [comment]
Was able to reproduce the issue. Please find the [Gist](https://colab.sandbox.google.com/gist/amahendrakar/ed9cea3d43ac8815969a2988edec2d61/35329.ipynb) here. Thanks!

**Comment by yourtheron** [comment]
I see. So may I ask what the solution is or where I made mistakes in
my code? I cannot see any incompatible shape of tensors. I am quite
new to tf.
Thanks.

**Comment by yourtheron** [comment]
@amahendrakar So how to change the code and make it work? From the link you gave, I am afraid that I did not see any change. Now, even even a dummy class below raises the same error. 
```
import numpy as np
import tensorflow as tf


class GeneralDiceLoss(tf.keras.losses.Loss):
	def __init__(self, reduction=tf.keras.losses.Reduction.AUTO, name='GeneralDiceLoss'):
		super().__init__(reduction=reduction, name=name)
	
	
	def get_config(self):
		config = super(GeneralDiceLoss, self).get_config()
		return config

	def call(self, yPred, yTrue):
            loss = 0
		
	    return loss
    
GeneralDiceLoss()
yPred = tf.random.uniform(shape=(16, 3, 4, 4, 4))
yTrue = tf.round(tf.random.uniform(shape=(16, 3, 4, 4, 4)))

loss=GeneralDiceLoss(yPred, yTrue)
```

**Comment by tavco09** [comment]
Good job!

**Comment by yourtheron** [comment]
@tavco09 Sorry, but I have not seen any solution, yet. Did I miss anything?

**Comment by amukh18** [comment]
Hello. I would like to work on this issue. Could you please give me some guidance as to how I should proceed?

**Comment by yourtheron** [comment]
@amukh18 Hi, thanks for the message. Please see my code above
```
import numpy as np
import tensorflow as tf


class GeneralDiceLoss(tf.keras.losses.Loss):
	def __init__(self, reduction=tf.keras.losses.Reduction.AUTO, name='GeneralDiceLoss'):
		super().__init__(reduction=reduction, name=name)
	
	
	def get_config(self):
		config = super(GeneralDiceLoss, self).get_config()
		return config

	def call(self, yPred, yTrue):
            loss = 0
		
	    return loss
    
GeneralDiceLoss()
yPred = tf.random.uniform(shape=(16, 3, 4, 4, 4))
yTrue = tf.round(tf.random.uniform(shape=(16, 3, 4, 4, 4)))

loss=GeneralDiceLoss(yPred, yTrue)
```
Even a dummy class can reproduce the issue.

**Comment by amukh18** [comment]
Could you please tell me what 'auto' is in the given error (I'm a bit new to Tensorflow)?

**Comment by yourtheron** [comment]
I am sorry I do not have a clue, which is partly why I asked the question.

**Comment by yourtheron** [comment]
@pavithrasv When I tried the code on Colab, the following error popped out
```
AttributeError                            Traceback (most recent call last)
<ipython-input-3-465b8423adac> in <module>()
      1 import tensorflow as tf
      2 from tensorflow.keras import layers
----> 3 class GeneralDiceLoss(tf.keras.losses.Loss):
      4     def __init__(self, wPow, reduction=tf.keras.losses.Reduction.AUTO, name='GeneralDiceLoss'):
      5         super().__init__(reduction=reduction, name=name)

1 frames
/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/util/module_wrapper.py in __getattr__(self, name)
    191   def __getattr__(self, name):
    192     try:
--> 193       attr = getattr(self._tfmw_wrapped_module, name)
    194     except AttributeError:
    195       if not self._tfmw_public_apis:

AttributeError: module 'tensorflow.python.keras.api._v1.keras.losses' has no attribute 'Reduction'
```

**Comment by dli7319** [comment]
You need to create an instance of your loss class before you call it.

```
loss_func = GeneralDiceLoss()
loss_val = loss_func(yPred, yTrue)
```

**Comment by tavco09** [comment]
Thanks buddy! 

Отправлено из мобильной Почты Mail.Ru

четверг, 9 апреля 2020 г., 00:30 +0300 от notifications@github.com  <notifications@github.com>:

**Comment by anish9** [comment]
> Could you please tell me what 'auto' is in the given error (I'm a bit new to Tensorflow)? I have tried searching this keyword but haven't got any answers.

AUTO reduction is default when losses are computed in multiple GPU's, basically you can get an output there but if you have 3 GPU's and you allocate a batch size of 30(GLOBAL BATCH SIZE) then the replicas of computation is 3 with each getting 10 batches, so at the end when mean or sum is computed in batches it shouldn't be at 10 but 30 which is your GLOBAL BATCH SIZE, so setting AUTO will produce wrong values, so when strategy is called we should be careful in declaring the aggregating and compute method which will be computed in GLOBAL BATCH SIZE.

**Comment by rmothukuru** [comment]
@yourtheron,
Code works fine if we create an instance of the Class as per [dli7319's Comment](https://github.com/tensorflow/tensorflow/issues/35329#issuecomment-611205264). Please find [the Gist](https://colab.research.google.com/gist/rmothukuru/7814fe7ceb1fa32164595328609771a2/35329.ipynb) of the working code. Thanks!
