### ISSUE TITLE
dataset_ops.py   'NoneType' object has no attribute 'device'

### ISSUE THREAD

**Issue by kuzen** [tensorflow/tensorflow#35326]
**System information**
- Ubuntu 16.04
- TensorFlow and Tensorflow_Datasets installed from conda
- TensorFlow version 2.0
- Python version: 3.7
- GPU : None

**Describe the current behavior**
when I run the code form [segmentation](https://www.tensorflow.org/tutorials/images/segmentation?hl=en)
after plt.show()
it run well in jupyter but this error occurred in *.py
```
Traceback (most recent call last):
  File "/home/cirno/anaconda3/envs/pytf/lib/python3.7/site-packages/tensorflow_core/python/data/ops/dataset_ops.py", line 3009, in __del__
AttributeError: 'NoneType' object has no attribute 'device'
Exception ignored in: <function _MemoryCacheDeleter.__del__ at 0x7f839a9344d0>
Traceback (most recent call last):
  File "/home/cirno/anaconda3/envs/pytf/lib/python3.7/site-packages/tensorflow_core/python/data/ops/dataset_ops.py", line 2944, in __del__
AttributeError: 'NoneType' object has no attribute 'device'
Exception ignored in: <function _RandomSeedGeneratorDeleter.__del__ at 0x7f839a9347a0>
Traceback (most recent call last):
  File "/home/cirno/anaconda3/envs/pytf/lib/python3.7/site-packages/tensorflow_core/python/data/ops/dataset_ops.py", line 3009, in __del__
AttributeError: 'NoneType' object has no attribute 'device'
```

**Code to reproduce the issue**
[segmentation](https://www.tensorflow.org/tutorials/images/segmentation?hl=en)

**Other info **
in dataset_ops.py
add `import tensorflow as tf`
and
line: 2944 and 3009   `with ops.device(self._device):` modify to  `with tf.device(self._device):`
It looks like it's solved

**Comment by ravikyram** [comment]
@kuzen 

I have tried in TF 2.0 and i am not seeing any issue.Please, find the log file. 
[log.tar.gz](https://github.com/tensorflow/tensorflow/files/3994521/log.tar.gz). Please, correct me if i miss something.Thanks!

**Comment by kuzen** [comment]
Sorry, i can't reproduce this.

**Comment by mvrska** [comment]
Hello,
I am getting this same issue while following
[this time series tutorial](https://www.tensorflow.org/tutorials/structured_data/time_series?hl=en)
on windows in VS Code, when trying to use the `simple_lstm_model` `predict` or `fit` methods.
```
Exception ignored in: <function _MemoryCacheDeleter.__del__ at 0x000001BA6BB2B288>
Traceback (most recent call last):
  File "C:\Users\MichalVrska\.conda\envs\tensor\lib\site-packages\tensorflow_core\python\data\ops\dataset_ops.py", line 2945, in __del__
AttributeError: 'NoneType' object has no attribute 'device'
Exception ignored in: <function _RandomSeedGeneratorDeleter.__del__ at 0x000001BA6BB2B558>
Traceback (most recent call last):
  File "C:\Users\MichalVrska\.conda\envs\tensor\lib\site-packages\tensorflow_core\python\data\ops\dataset_ops.py", line 3010, in __del__
AttributeError: 'NoneType' object has no attribute 'device'
```

**Comment by mvrska** [comment]
@ravikyram I encountered this issue today again after a lenghty model compilation, so I checked my RAM and found that I was completely exhausting it (16GB) and I suspect that this might be the root of the issue. Can you confirm if you have enough RAM or also running out?

**Comment by bersbersbers** [comment]
Here is some test code that I could repro the same error with:
```
import os
import random

import numpy as np
import tensorflow as tf
from tensorflow import keras

seed = 0
os.environ["PYTHONHASHSEED"] = str(seed)
random.seed(seed)
np.random.seed(seed)
tf.random.set_seed(seed)
layer = keras.layers.Input(shape=(32, 32, 3))
model = keras.models.Model(inputs=layer, outputs=layer)
model.compile(optimizer="adam", loss="mse")
data = np.empty((5, 32, 32, 3))
data = tf.data.Dataset.from_tensor_slices((data, data))
data = data.shuffle(buffer_size=5).batch(2)
model.fit(x=data, verbose=1, epochs=10)
print("Done.")
```

The output ends in
```
Epoch 9/10
3/3 [==============================] - 0s 6ms/step - loss: 0.0000e+00
Epoch 10/10
3/3 [==============================] - 0s 6ms/step - loss: 0.0000e+00
Done.
Exception ignored in: <function _RandomSeedGeneratorDeleter.__del__ at 0x00000185EAEC2EE8>
Traceback (most recent call last):
  File "C:\Users\bersbersbers\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\python\data\ops\dataset_ops.py", line 3462, in __del__
AttributeError: 'NoneType' object has no attribute 'device'****
```

This error appears when remote-debugging in VS Code through VS Code Remote SSH, but not when running the same file locally (neither on the client nor the server). The server has 256 GB RAM, of which 8 are in use, so I doubt RAM is an issue, @mvrska.

This is TF 2.1.0rc2 on Python 3.7.6 on a Windows 10 server.

**Comment by pmalecka** [comment]
Can replicate this: Windows 10, Nvidia RTX 2080S. 16GB ram, 8 used.

**Comment by MarkDaoust** [comment]
Hi.

I don't think this is:

 1) something to worry about, or 
2) an error that can be simply fixed. 

These are all labeled "Exception ignored" is likely because the object is being deleted during python exit. See this answer:

https://stackoverflow.com/a/16620987/997378

This isn't interrupting a running program, right?

> add import `tensorflow as tf` and line: 2944 and 3009 with ops.device(self._device): modify to with tf.device(self._device): It looks like it's solved

Thanks for the suggestion @kuzen. This might look like a fix but it isn't, really. This has something to do with object deletion order, I think during python exit.

Tensorflow files never `import tensorflow  as tf` directly, they import the file that the object they want is implemented in.  `tf.device` is implemented in `/tensorflow/python/framework/ops.py`.

**Comment by pmalecka** [comment]
Hi,
you are absolutely correct, thanks for the detailed answer.

It's not a running program that is being interrupted, this just gets written to the output at the end of the execution.

Thanks again,
Peter
