### ISSUE TITLE
Need the help for "ERROR: Failed to load libhexagon_interface.so"

### ISSUE THREAD

**Issue by edgeaidl20** [tensorflow/tensorflow#35320]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution :16.04 :
- Mobile device: Samsung Galaxy S9:
- TensorFlow installed from source:
- TensorFlow version: TF mainline
- Python version: 3.6
- Installed using virtualenv? N/A
- Bazel version (if compiling from source): 1.2.1
- GCC/Compiler version (if compiling from source): 5.4.0
- CUDA/cuDNN version: 10.1
- GPU model and memory: 1080TI

**Describe the problem**
Where is to get the libhexagon_interface.so? Got this error "ERROR: Failed to load libhexagon_interface.so" when using the hexagon delegate.

**Provide the exact sequence of commands / steps that you executed before running into the problem**
run the hexagon delegate example.

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by edgedlai** [comment]
Saw the other issue has no problem to run hexagon delegate, but not sure how to get the "libhexagon_interface.so"?
https://github.com/tensorflow/tensorflow/issues/35221

**Comment by edgedlai** [comment]
@karimnosseir, Can you help to comment on this?

**Comment by karimnosseir** [comment]
Hi @edgedlai 
It is part of the third_party/hexagon package which bazel automatically downloads

You can fetch it like this
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/experimental/delegates/hexagon/java/BUILD#L29

I am assuming you're trying to use the C API and not using the Java AAR, correct ?

**Comment by edgeaidl20** [comment]
@karimnosseir , got it, thanks, it's working now.

**Comment by karimnosseir** [comment]
You're welcome.

Thanks

**Comment by harshgrovr** [comment]
> Hi @edgedlai
> It is part of the third_party/hexagon package which bazel automatically downloads
> 
> You can fetch it like this
> https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/experimental/delegates/hexagon/java/BUILD#L29
> 
> I am assuming you're trying to use the C API and not using the Java AAR, correct ?

Hey, I am not able to reach that link, can you please share?

**Comment by karimnosseir** [comment]
@harshgrovr The link now should be [1] as hexagon delegate moved outside experimental directory

[1] https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/delegates/hexagon/java/BUILD#L29
