### ISSUE TITLE
ValueError: name for name_scope must be a string when Building up a Custom Model

### ISSUE THREAD

**Issue by yourtheron** [tensorflow/tensorflow#35337]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 7
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): 
- TensorFlow version (use command below): 2.0.0
- Python version: 3.7
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 10.1
- GPU model and memory: 

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

Hi,

I tried to follow tf's doc to build up a model as follows:
https://www.tensorflow.org/guide/keras/custom_layers_and_models

`
					
	class CBR(layers.Layer):
		'''
		Convolution + Batch normalisation + Relu
		'''
		def __int__(self, filterNum, kSize, strSize, padMode, name='cbr', **kwargs):
			super(CBR, self).__init__(name=name, **kwargs)
			self.conv3D = layers.Conv3D(filters=filterNum, kernel_size=kSize, strides=strSize, padding=padMode, data_format='channels_first')
			self.BN = layers.BatchNormalization(axis=1)
		def call(self, inputs):
			x = self.conv3D(inputs)
			x=self.BN(x)
			return layers.Relu(x)
			
	class SimpleUNet(tf.keras.Model, layers.Layer):
		'''
		Serialise basic units so as to build up a double-layered encoder-decoder U-Net
		Input:
			inDim: [mbSize, modaility/channel, tensor dimensions]
			classNum: background included
			name: name for the net
			inputs: 5D tf tensor of [mbSize, modaility/channel, tensor dimensions]. Inputs must be organised into channel first
		Returns:
			outputs: 5D tf tensor of [mbSize, classNum, tensor dimensions]
		'''
		def __init__(self, inDim, classNum, name='SimpleUNet', **kwargs):
			super(SimpleUNet, self).__init__(name=name, **kwargs)
			self.inDim = inDim
			self.classNum = classNum
			dimEnSt1End = np.array(inDim[1:])-2-2
			dimEnSt2Ed = dimEnSt1End/2-2-2
			dimBridgeEnd = (dimEnSt2Ed/2-2-2)*2
			dimDEStd1End = (dimBridgeEnd-2-2)*2
			outDim = dimDEStd1End-2-2-2
			temp = ((dimEnSt2Ed - dimBridgeEnd)/2).astype('int32')
			crop3d1 = tuple(np.tile(temp, (2, 1)).T)
			temp = ((dimEnSt1End - dimDEStd1End)/2).astype('int32')
			crop3d2 = tuple(np.tile(temp, (2, 1)).T)
			# list of basic units used in the model
			self.en_st1_cbr1 = CBR(32, 3, 1, 'valid')
			self.en_st1_cbr2 = CBR(64, 3, 1, 'valid')
			self.en_st2_mp = layers.MaxPooling3D(pool_size=(2, 2, 2), strides=(2, 2, 2), padding='valid', data_format='channels_first')
			self.en_st2_cbr1 = CBR(64, 3, 1, 'valid')
			self.en_st2_cbr2 = CBR(128, 3, 1, 'valid')
			self.bridge_mp = layers.MaxPooling3D(pool_size=(2, 2, 2), strides=(2, 2, 2), padding='valid', data_format='channels_first')
			self.bridge_cbr1 = CBR(128, 3, 1, 'valid')
			self.bridge_cbr2 = CBR(256, 3, 1, 'valid')    
			self.bridge_tconv1 = layers.Conv3DTranspose(256, 2, strides=2, padding='valid', data_format='channels_first')
			self.de_3dcrop1 = layers.Cropping3D(crop3d1, data_format='channels_first')
			self.de_st1_cbr1 = CBR(256, 3, 1, 'valid')
			self.de_st1_cbr2 = CBR(128, 3, 1, 'valid')    
			self.de_st1_tconv1 = layers.Conv3DTranspose(128, 2, strides=2, padding='valid', data_format='channels_first')
			self.de_3dcrop2 = layers.Cropping3D(crop3d2, data_format='channels_first')
			self.de_st2_cbr1 = CBR(64, 3, 1, 'valid')
			self.de_st2_cbr2 = CBR(64, 3, 1, 'valid') 
			self.final_conv3D = layers.Conv3D(filters=self.classNum, kernel_size=3, strides=1, padding='valid', data_format='channels_first')
					
		def call(self, inputs):
			x = self.en_st1_cbr1(inputs)
			xEnSt1End = self.en_st1_cbr2(x)
			x= self.en_st2_mp(xEnSt1End)
			x= self.en_st2_cbr1(x)
			xEnSt2Ed = self.en_st2_cbr2(x)
			x = self.bridge_mp(xEnSt2Ed)
			x = self.bridge_cbr1(x)
			x = self.bridge_cbr2(x)
			xBridgeEnd = self.bridge_tconv1(x)
			xCrop1 = self.de_3dcrop1(xEnSt2Ed)
			x = layers.Concatenate([xBridgeEnd, xCrop1], axis=1)
			x = self.de_st1_cbr1(x)
			x = self.de_st1_cbr2(x)
			xDeSt1End = self.de_st1_tconv1(x)
			xCrop2 = self.de_3dcrop2(xEnSt1End)
			x = layers.Concatenate([xDeSt1End, xCrop2], axis=1)
			x = self.de_st2_cbr1(x)
			x = self.de_st2_cbr2(x)
			x = self.final_conv3D(x)
			outputs = activations.softmax(x, axis=1)
			
			return outputs

`

Then I initialised it, and tried to build it by calling SUNet.build
`
	classNum = 3 
	mbSize = 16 
	inDim = [4, 64, 64, 64] 
	SUNet = SimpleUNet(inDim, classNum) 
	SUNet.build(input_shape=inDim)
`
I strictly followed the example given in tf's doc, but an error was raised when building up it
ValueError: name for name_scope must be a string.
It occurred here when CBR is called for the first time:

`
def __int__(self, filterNum, kSize, strSize, padMode, name='cbr', **kwargs): 
	super(CBR, self).__init__(name=name, **kwargs)
`

I cannot figure out any syntactic mistake. Could anyone give me a hand? Thanks a lot.
Or, is the model cannot be built at this moment until it is actually used when being called in the training?

**Comment by jvishnuvardhan** [comment]
@yourtheron Can you please provide simple standalone code to reproduce the issue? Thanks!

**Comment by yourtheron** [comment]
@jvishnuvardhan Sure. The following is a fairly simple class of TestNet invovling class CBR

`
		from __future__ import absolute_import, division, print_function, unicode_literals
		import functools

		import numpy as np
		import tensorflow as tf
		from tensorflow.keras import layers, activations

		class CBR(layers.Layer):
			"""Convolution + Batch normalisation + Relu"""
		#    def __int__(self, filterNum, kSize, strSize, padMode):
			def __int__(self, filterNum, kSize, strSize, padMode, name='cbr', **kwargs):
				super(CBR, self).__init__(name=name, **kwargs)
				self.conv3D = layers.Conv3D(filters=filterNum, kernel_size=kSize, strides=strSize, padding=padMode, data_format='channels_first')
				self.BN = layers.BatchNormalization(axis=1)
			def call(self, inputs):
				x = self.conv3D(inputs)
				x=self.BN(x)
				return activations.relu(x)

		class TestNet(tf.keras.Model):
			def __init__(self, inDim, classNum, name='testNet', **kwargs):        
				super(TestNet, self).__init__(name=name, **kwargs)
				self.inDim = inDim
				self.classNum = classNum
				self.en_st1_cbr1 = CBR(32, 3, 1, 'valid')
			def call(self, inputs):
				x = layers.Input(shape=self.inDim)
				x = self.en_st1_cbr1(x)
				outputs = activations.softmax(x, axis=1)        
				return outputs
			

		classNum = 2
		inDim = [4, 64, 64, 64]
		TNet = TestNet(inDim, classNum)
		# Whethere calling build() or call(), the bug occurs
		TNet.build(input_shape=inDim)
		TestSignal = tf.random.uniform((10, 4, 64, 64, 64))
		TNet.call(TestSignal)
`

**Comment by yourtheron** [comment]
@jvishnuvardhan I think I found a work-around. If I do not define CBR as a custom layer class as paraphrased in the tf's doc, but a custom model instead, it works. But it might still be better to figure out why defining it as a layer class does not, thanks.
```
		class C3BR(tf.keras.Model):

			def __init__(self, filterNum, kSize, strSize, padMode):
				super(C3BR, self).__init__()
				self.conv = layers.Conv3D(filters=filterNum, kernel_size=kSize, strides=strSize, padding=padMode, data_format='channels_first')
				self.BN = layers.BatchNormalization(axis=1)
			
			def call(self, inputs):
				x = self.conv(inputs)
				x= self.BN(x)
				return activations.relu(x)
```

**Comment by cgarciae** [comment]
Getting the same error.

**Comment by cboulay** [comment]
In case this helps someone, I was getting the same error because I removed a no-longer-required positional argument (integer) from my custom model's `__init__` signature without updating the code that instantiated the model. In practice, the integer was getting passed to the only remaining argument: the `name=` kwarg.

I think it's not the same problem OP is experiencing but probably related. I notice that in the working tf.keras.Model subclass version there is no longer a 'name' kwarg. I would also check the contents of **kwargs, and check what is being passed to the super(CBR, self).__init__(name=name).

**Comment by amahendrakar** [comment]
@yourtheron,
Could you please update TensorFlow to v2.3 and check if you are still facing the same issue. 

Also, please take a look at @cboulay's workaround and let us know if it helps. Thanks!

**Comment by yourtheron** [comment]
@amahendrakar
If I run the simple code I posted on 24/12/2019 on tf 2.3, Windows 7, Python 3.8.3, the error occurred on the following line
`
super(TestNet, self).__init__(name=name, **kwargs)
`
Then the error info reads

  File "D:\TProgramFiles\Anaconda3\envs\keras-gpu\lib\site-packages\tensorflow\python\training\tracking\base.py", line 457, in _method_wrapper
    result = method(self, *args, **kwargs)

  File "D:\TProgramFiles\Anaconda3\envs\keras-gpu\lib\site-packages\tensorflow\python\keras\engine\training.py", line 308, in __init__
    self._init_batch_counters()

  File "D:\TProgramFiles\Anaconda3\envs\keras-gpu\lib\site-packages\tensorflow\python\training\tracking\base.py", line 457, in _method_wrapper
    result = method(self, *args, **kwargs)

  File "D:\TProgramFiles\Anaconda3\envs\keras-gpu\lib\site-packages\tensorflow\python\keras\engine\training.py", line 317, in _init_batch_counters
    self._train_counter = variables.Variable(0, dtype='int64', aggregation=agg)

  File "D:\TProgramFiles\Anaconda3\envs\keras-gpu\lib\site-packages\tensorflow\python\ops\variables.py", line 262, in __call__
    return cls._variable_v2_call(*args, **kwargs)

  File "D:\TProgramFiles\Anaconda3\envs\keras-gpu\lib\site-packages\tensorflow\python\ops\variables.py", line 244, in _variable_v2_call
    return previous_getter(

  File "D:\TProgramFiles\Anaconda3\envs\keras-gpu\lib\site-packages\tensorflow\python\ops\variables.py", line 237, in <lambda>
    previous_getter = lambda **kws: default_variable_creator_v2(None, **kws)

  File "D:\TProgramFiles\Anaconda3\envs\keras-gpu\lib\site-packages\tensorflow\python\ops\variable_scope.py", line 2633, in default_variable_creator_v2
    return resource_variable_ops.ResourceVariable(

  File "D:\TProgramFiles\Anaconda3\envs\keras-gpu\lib\site-packages\tensorflow\python\ops\variables.py", line 264, in __call__
    return super(VariableMetaclass, cls).__call__(*args, **kwargs)

  File "D:\TProgramFiles\Anaconda3\envs\keras-gpu\lib\site-packages\tensorflow\python\ops\resource_variable_ops.py", line 1507, in __init__
    self._init_from_args(

  File "D:\TProgramFiles\Anaconda3\envs\keras-gpu\lib\site-packages\tensorflow\python\ops\resource_variable_ops.py", line 1661, in _init_from_args
    handle = eager_safe_variable_handle(

  File "D:\TProgramFiles\Anaconda3\envs\keras-gpu\lib\site-packages\tensorflow\python\ops\resource_variable_ops.py", line 242, in eager_safe_variable_handle
    return _variable_handle_from_shape_and_dtype(

  File "D:\TProgramFiles\Anaconda3\envs\keras-gpu\lib\site-packages\tensorflow\python\ops\resource_variable_ops.py", line 174, in _variable_handle_from_shape_and_dtype
    gen_logging_ops._assert(  # pylint: disable=protected-access

  File "D:\TProgramFiles\Anaconda3\envs\keras-gpu\lib\site-packages\tensorflow\python\ops\gen_logging_ops.py", line 49, in _assert
    _ops.raise_from_not_ok_status(e, name)

  File "D:\TProgramFiles\Anaconda3\envs\keras-gpu\lib\site-packages\tensorflow\python\framework\ops.py", line 6843, in raise_from_not_ok_status
    six.raise_from(core._status_to_exception(e.code, message), None)

  File "<string>", line 3, in raise_from

InvalidArgumentError: assertion failed: [0] [Op:Assert] name: EagerVariableNameReuse

Whether I use
`
super(TestNet, self).__init__()
`
or
`
super(TestNet, self).__init__(name=name)
`
The error remains the same.
In tf2.0, that line of code worked at least.

**Comment by yourtheron** [comment]
@amahendrakar 
`
super(TestNet, self).__init__()
`
works in tf 2.1, Python 3.7.7 though, together with the workaround in CBR above,

**Comment by amahendrakar** [comment]
@yourtheron,
In order to expedite the trouble-shooting process, could you please provide the latest minimal reproducible code which you are running.

>works in tf 2.1, Python 3.7.7 though, together with the workaround in CBR above,

Also, could you please check if the same works with TF v2.3 and TF-nightly. Thanks!

**Comment by yourtheron** [comment]
@amahendrakar 
It is just the code I posted in this thread on 24/12/2019

**Comment by amahendrakar** [comment]
Running the code with [TF v2.3](https://colab.sandbox.google.com/gist/amahendrakar/4066bf4a3a843684e96e2397c92af2d5/35337-2-3.ipynb) throws an error stating 
`ValueError: You cannot build your model by calling build if your layers do not support float type inputs. Instead, in order to instantiate and build your model, call your model on real tensor data (of the correct dtype).`

Whereas, on running the code with [TF-nightly](https://colab.sandbox.google.com/gist/amahendrakar/18b82e148ec042801c9fa2aea2525379/35337-tf-nightly.ipynb#scrollTo=gYM2rfzl4v1S), the error is
`NotImplementedError: Please run in eager mode or implement the compute_output_shape method on your layer (CBR).`

Please find the attached gist. Thanks!

**Comment by yourtheron** [comment]
@amahendrakar When I ran it with tf2.3, those errors I printed above have occurred after the following line was executed.
`
TNet = TestNet(inDim, classNum)
`
before reaching the build stage.

Another strange thing.
I added a work-around, and had the following code run with tf2.1

`
	import numpy as np
	import tensorflow as tf
	from tensorflow.keras import layers, activations

	class CBR(tf.keras.Model):
		def __int__(self, filterNum, kSize, strSize, padMode):
			super(CBR, self).__init__() 
			self.conv = layers.Conv3D(filters=filterNum, kernel_size=kSize, strides=strSize, padding=padMode, data_format='channels_first') 
			self.BN = layers.BatchNormalization(axis=1)
		def call(self, inputs):
			x = self.conv(inputs)
			x=self.BN(x)
			return activations.relu(x)
		
		def build_model(self, input_shape):
			self.build(input_shape)
			inputs = tf.keras.Input(shape=input_shape[1:])
			_ = self.call(inputs, True) 
			
			
	class TestNet(tf.keras.Model):
		def __init__(self, inDim, classNum):        
			super(TestNet, self).__init__()
			self.inDim = inDim
			self.classNum = classNum
			self.en_st1_cbr1 = CBR(32, 3, 1, 'valid')
		def call(self, inputs):
			x = layers.Input(shape=self.inDim)
			x = self.en_st1_cbr1(x)
			outputs = activations.softmax(x, axis=1)        
			return outputs
		
		def build_model(self, input_shape):
			self.build(input_shape)
			inputs = tf.keras.Input(shape=input_shape[1:])
			_ = self.call(inputs, True) 	

	classNum = 2
	inDim = [4, 64, 64, 64]
	TNet = TestNet(inDim, classNum)
	# Whethere calling build() or call(), the bug occurs
	TNet.build_model(input_shape=((1,) + tuple(inDim)))
`

An error occurs saying
`
	AttributeError: in converted code:

		<ipython-input-1-04ea61c5d34b>:11 call  *
			x = self.conv(inputs)

		AttributeError: 'CBR' object has no attribute 'conv
`

I really cannot find out why. Could you take a look? Cheers.

**Comment by sushreebarsa** [comment]
Was able to replicate the issue with TF 2.6.0-dev20210606,please find the gist [here](https://colab.research.google.com/gist/sushreebarsa/19da9e3d073fb24d94e6f981e85992a0/untitled220.ipynb#scrollTo=mvnkn7P5BHVG)..Thanks !

**Comment by mohantym** [comment]
Hi @yourtheron .I think  I found a typo  here  in this line                                                                                                                     
  ` def __int__(self, filterNum, kSize, strSize, padMode, name='cbr', **kwargs):  `                                                                                Was able to replicate the issue with TF v2.5 and v2.3 `after replacing __int__ with __init__ `,please find the gist [here ](https://colab.research.google.com/gist/mohantym/6d92241371703e7957b3141fa6c71bdb/35337.ipynb).Thanks!

**Comment by yourtheron** [comment]
@mohantym Got it, thanks a lot!
