### ISSUE TITLE
Question about tf.keras.backend switch in lambda layer for short circuit computation

### ISSUE THREAD

**Issue by zack466** [tensorflow/tensorflow#35334]
I am using tf.keras.backend.switch inside of a lambda layer in order to swap between multiple different "expert" layers based on the output of a "gating" layer. When the entire model is used to predict an output, does it evaluate the gating layer first and then "short circuit" to only evaluate the single selected expert layer (to save computation time)? If not, how could I implement this?

I am using tensorflow 2.0 gpu and the keras functional api

Update: I created a custom layer with multiple input/output tensors rather than using a Lambda layer, but the question above still stands.

**Comment by ymodak** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.
 Thanks!
