### ISSUE TITLE
Tensorflow-lite gpu output is corrupted when using opencl backend

### ISSUE THREAD

**Issue by anilsathyan7** [tensorflow/tensorflow#35339]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Android version:9, Ubuntu 16.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: OnePlus3, GPU:Adreno 530
- TensorFlow installed from (source or binary): tensorflow-lite-gpu 1.15, tensorflow-lite-gpu:0.0.0-nightly from 'https://mvnrepository.com'
- TensorFlow version (use command below): 1.14, 1.15

**Describe the current behavior**
I'm using tflite-gpu in my android application for semantic segmentation. Using my tflite model(all gpu supported ops) i'am able to get proper output with CPU version and tensorflow-lite-gpu 1.14 ;but when i use nightly or 1.15 it loads up opencl backend and gives corrupted output. This backend seems to take longer time to start up(5-10s); however it seems to be faster than corresponding opengl version. When i run the model to get a image output (float:0-1) there seems to be random rectangular blanks within the output. The input is 256x256x3(float) and output os 256x256x1(float). However.  i 'am not facing this issue using a different model with input size 128; even though i use the same back-end.
**Describe the expected behavior**
The tflite model should produce correct output with opencl backend like the  opengl version, regardless of input size.

**Other info / logs**
I'am getting correct output for model with 128 input size regardless of backends and devices; but for the model with 256 output size i'am not getting proper output with opencl backend (gpu-nightly and gpu-1.15)
[Models.zip](https://github.com/tensorflow/tensorflow/files/3992313/Models.zip)

Only the '**opencl gpu delegate with this 256 input sized-model**' produces this corrupted output; other versions (CPU, Opengl-GPU, 128 input-model with Opencl etc.) seems to produce correct result without the rectangular blanks.
![tmap54](https://user-images.githubusercontent.com/1130185/71320296-57515680-24cf-11ea-8c26-66f62c948e94.PNG)

**Comment by impjdi** [comment]
I forwarded this to our OpenCL engineer.  He's looking.

**Comment by impjdi** [comment]
Btw, I spy 3 black rectangles (1 in the background).  Is it always the same location, or is it random?

**Comment by impjdi** [comment]
Hm, we cannot reproduce this bug with Adreno 530 (Samsung S7 Edge; sorry, we don't have OnePlus3).  Do you see this on every frame or only occasionally?

**Comment by anilsathyan7** [comment]
It appears randomly on most of the frames. I'am able to run it at around 12 fps using opencl backend.The phone uses OxygenOS 9.0.6 and is based on android Pie.These rectangles appears  in both  foreground and background regions of the segmentation map(model is about portrait segmentation). Also, is it normal for the model to take this much time for initialization?

**Comment by impjdi** [comment]
@anilsathyan7 

Engineer suspects some problems in GPU/CPU synchronization when fetching output.  Unfortunately, he wasn't able to reproduce the problem on his device and is now on vacation until mid Jan.  Do you have the luxury of checking things on another device?

By the way, I heard your network has transpose convs in them.  There's been a commit 020e0de6b0c6741acae0735c41f9dff463230aa8 which should speed things up a bit.

**Comment by anilsathyan7** [comment]
Sure, i will check it on other devices. Currently i'am using java float array of shape [1][257*257] to get the flattened output from model. I also saw the recent android support library that tf has released, for handling I/O. Is it still in development phase or can we use it for  production?

Thanks

**Comment by impjdi** [comment]
@anilsathyan7 

While I don't have experience with the android support library you linked, things under experimental  are... well... experimental.

The APIs and/or implementation details may change, and in worst case, they may not survive experimental and may be killed.  In that sense, I wouldn't say it's safe to use it for production.  But if you're willing to eat up that development cost, go ahead :P  Sorry for not being able to give you a definitive answer there; I'm not directly part of the TFLite org and don't know their plans at the sub project level.

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.
