### ISSUE TITLE
Problems with quantization. Op type not registered 'Dequantize' and other problems

### ISSUE THREAD

**Issue by GrachevArtem** [tensorflow/tensorflow#3533]
Hi Everyone,

I did quantization with tensorflow following this manual: https://www.tensorflow.org/versions/master/how_tos/quantization/index.html

Here detailed description of my current problem: 
http://stackoverflow.com/questions/38615558/bug-in-tensorflow-tuttorial-about-quantization

And here parent problem: 
http://stackoverflow.com/questions/38595600/notfounderror-op-type-not-registered-dequantize

I use pip install tensorflow. Python2.7, tensorflow=0.9.0
Also I have git-master repository and use bazel-build for other tools like freezing and so on. 
bazel version=0.3.0
OS: Ubuntu 16.04 LTS
gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.1) 

@petewarden 

I am ready to give you any additional information 

Thanks, 
 Artem

**Comment by huyong1109** [comment]
Same problems. Can't load the quantization library anyway!

**Comment by upupnoel** [comment]
i found a solution, rebuilt the `label_image` by adding two lines below 
```
"//tensorflow/contrib/quantization:cc_ops",
"//tensorflow/contrib/quantization/kernels:quantized_ops"
```
into `tensorflow/examples/label_image/BUILD` . It works for me (ubuntu 1404LTS, tf0.9-gpu ).

**Comment by perone** [comment]
I'm facing the same issue, however in my case adding the dependencies doesn't work because they don't compile for Android.

**Comment by chenbiaolong** [comment]
@perone same problem as you, did your android project work now? @petewarden can you give a tutorial about how android project use the quantize neural networks ?

**Comment by perone** [comment]
@chenbiaolong not yet, I tried to add the required dependencies (the quantized operations) but they do not compile for Android, it seems that quantization isn't ready yet for Android compilation.

**Comment by sulc** [comment]
I am facing the same issues when trying to use a quantized network on Android (tried both with TF r0.8 and r0.10). Any news, solutions or advices? :)

**Comment by drpngx** [comment]
Please upgrade to a newer version, `0.12.1` or master. Feel free to open a new issue if the problem persists.
