### ISSUE TITLE
Support other types of Tensors in tf.data.Dataset.from_generator

### ISSUE THREAD

**Issue by konopik** [tensorflow/tensorflow#35342]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: YES
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: macOS 10.15.2 (19C57)
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**:v2.0.0-rc2-26-g64c3d382ca 2.0.0
- **Python version**:3.7.5 (default, Oct 25 2019, 18:18:54) \n[Clang 11.0.0 (clang-1100.0.33.8)]

### Describe the problem

`tf.data.Dataset` supports RaggedTensor and SparseTensor but `tf.data.Dataset.from_generator` is limited to Tensors only. Please support other types of Tensors. 

### Source code / logs

```
    def data_get():
        for i in range(5):
            yield tf.ragged.constant([[i, i], [i]])

    ds = tf.data.Dataset.from_generator(data_get, tf.int32)

    for sample in ds:
        print(sample)
```

produces:

Traceback (most recent call last):

```
  File "/Users/peak/IdeaProjects/TFmodels/venv-tf2/lib/python3.7/site-packages/tensorflow_core/python/ops/script_ops.py", line 221, in __call__
    ret = func(*args)

  File "/Users/peak/IdeaProjects/TFmodels/venv-tf2/lib/python3.7/site-packages/tensorflow_core/python/data/ops/dataset_ops.py", line 606, in generator_py_func
    "element was %s." % (dtype.name, ret))

TypeError: `generator` yielded an element that could not be converted to the expected type. The expected type was int32, but the yielded element was <tf.RaggedTensor [[0, 0], [0]]>.
```

**Comment by jsimsa** [comment]
This would indeed be useful. My preference for the API would be to add an optional `output_spec` argument which -- when set -- would be used in place of `output_types` and `output_shapes` to identify the output signature of the generator.

This is also a good candidate for external contribution as it is narrowly scoped, so I am marking it as "contributions welcome".

**Comment by punndcoder28** [comment]
Hey! I would love to work on this. Any guidance would be appreciated.

**Comment by SSaishruthi** [comment]
Is anyone working on this? If not, I would like to work on this

**Comment by lithuak** [comment]
@SSaishruthi I'm trying to work on it at the moment.

**Comment by JulesGM** [comment]
This is supported in tf 2.5 (maybe 2.4?) with the output_signature argument of from_generator

**Comment by lithuak** [comment]
@JulesGM yes

**Comment by lithuak** [comment]
@gowthamkpr @jsimsa We implemented and merged this, so this issues can be closed )
