### ISSUE TITLE
SGD only? What about other algorithms like L-BFGS?

### ISSUE THREAD

**Issue by juicyslew** [tensorflow/tensorflow#3535]
This is simply a question, not an issue, as this seemed like the best place to ask:

I was looking at the video an model on the site, and it appeared to only have SGD as an algorithm for machine learning.  I was wondering if other algorithms are also included in tensorflow.

An interested student,
William

**Comment by michaelisard** [comment]
It's better to ask this kind of question on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow), thanks!
