### ISSUE TITLE
tf-lite C++ API giving same inference output for every input

### ISSUE THREAD

**Issue by rishabhrishu** [tensorflow/tensorflow#35357]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): macOS Mojave(v.10.14.5)
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: n.a.
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below): git tag: v1.14.0
- Python version: n.a.
- Bazel version (if compiling from source): 0.24.1
- GCC/Compiler version (if compiling from source): Apple clang version 11.0.0 (clang-1100.0.33.12)
- CUDA/cuDNN version: n.a.
- GPU model and memory: n.a.

**Describe the current behavior**
Model giving same output for every input.

**Describe the expected behavior**
Model should give different output for different inputs, and outputs of python API and C++ API should match.

**Code to reproduce the issue**
I want to evaluate tf model in a C++ project.

I built tf-lite dynamic library using following command
`bazel build -c opt //tensorflow/contrib/lite:libtensorflowLite.so --cxxopt="-std=c++11" --verbose_failures`.

In my project's cmake file, I set target_link_library property to `tensorflow/bazel-bin/tensorflow/lite/libtensorflowlite.so`, and I set appropriate header search paths so that my code compiles properly.

I converted my model to .tflite format via this snippet
```import tensorflow as tf
converter = tf.lite.TFLiteConverter.from_keras_model_file('model.h5') 
tfmodel = converter.convert() 
open("model.tflite", "wb").write(tfmodel)
```

I wrote this code for my model evaluation
```// Load the model
std::unique_ptr<tflite::FlatBufferModel> model = tflite::FlatBufferModel::BuildFromFile("model.tflite");

// Build the interpreter
tflite::ops::builtin::BuiltinOpResolver resolver;
std::unique_ptr<tflite::Interpreter> interpreter;

tflite::InterpreterBuilder builder(*model, resolver);
builder(&interpreter);
interpreter->AllocateTensors();

// Check interpreter state
tflite::PrintInterpreterState(interpreter.get());

std::vector<std::vector<double>> tensor;     // I filled this vector, (dims are 2050, 6)

int input = interpreter->inputs()[0];      // input dims are (1, 2050, 6)
float* input_data_ptr = interpreter->typed_input_tensor<float>(input);
for (int i = 0; i < 2050; ++i) {
    for (int j = 0; j < 6; j++) {
        *(input_data_ptr) = (float)tensor[i][j];
        input_data_ptr++;
    }
}

interpreter->Invoke();
int output_idx = interpreter->outputs()[0];
float* output = interpreter->typed_output_tensor<float>(output_idx);
std::cout << "OUTPUT: " << *output << std::endl;
```

```INFO: Initialized TensorFlow Lite runtime.
Interpreter has 96 tensors and 42 nodes
Inputs: 10
Outputs: 8

         < ........................ other layers>
Tensor   8 dense_2/Sigmoid      kTfLiteFloat32  kTfLiteArenaRw          4 bytes ( 0.0 MB)  1 1
         < ........................ other layers>
Tensor  10 input_1              kTfLiteFloat32  kTfLiteArenaRw      49200 bytes ( 0.0 MB)  1 2050 6
         < ........................ other layers>

OUTPUT: -3.74034
```
Issue is that I get this same output for all the inputs, and its also wrong as sigmoid should be between 0-1

Trying evaluation from python yields expected results. I used this snippet to run in python
```import numpy as np
import tensorflow as tf

# Load TFLite model and allocate tensors.
interpreter = tf.lite.Interpreter(model_path="model.tflite")
interpreter.allocate_tensors()

# Get input and output tensors.
input_details = interpreter.get_input_details()
output_details = interpreter.get_output_details()
print("INPUT DETAILS: ", input_details)
print("OUTPUT DETAILS: ", output_details)

# Evaluate
dataset = h5py.File('dataset.h5', 'r')
input_data1 = np.array(dataset["test"][:])    #shape is (1, 2050, 6)
interpreter.set_tensor(input_details[0]['index'], input_data1)
interpreter.invoke()

output_data = interpreter.get_tensor(output_details[0]['index'])
print("OUTPUT_DATA: ", output_data)
```
This gives correct output 
```
INPUT DETAULS:  [{'name': 'input_1', 'index': 10, 'shape': array([   1, 2050,    6], dtype=int32), 'dtype': <class 'numpy.float32'>, 'quantization': (0.0, 0)}]
OUTPUT DETAILS:  [{'name': 'dense_2/Sigmoid', 'index': 8, 'shape': array([1, 1], dtype=int32), 'dtype': <class 'numpy.float32'>, 'quantization': (0.0, 0)}]

OUTPUT_DATA [[0.02964767]]
```

**Comment by rishabhrishu** [comment]
This is not a bug, but wrong API usage.

Changing `typed_input_tensor` to `typed_tensor` and `typed_output_tensor` to `typed_tensor` resolved the issue for me.

For anyone else having the same issue, 
```
int input_tensor_idx = 0;
int input = interpreter->inputs()[input_tensor_idx];
float* input_data_ptr = interpreter->typed_input_tensor<float>(input_tensor_idx);
```
and
```
int input_tensor_idx = 0;
int input = interpreter->inputs()[input_tensor_idx];
float* input_data_ptr = interpreter->typed_tensor<float>(input);
```
are identical. 

This can be verified by looking at implementation of [typed_input_tensor](https://github.com/tensorflow/tensorflow/blob/49f453f1f9d8c878f7d381b7631051995336a264/tensorflow/lite/interpreter.h#L269).
```
  template <class T>
  T* typed_input_tensor(int index) {
    return typed_tensor<T>(inputs()[index]);
  }
```

**Comment by flamxi** [comment]
I am facing the same problem right now, I get the output all equal for all the classes no matter what input data I type in, I am using tensorflow 2.3 C++ API, @rishabhrishu I even changed the API as you suggested but still the same! 
Anyone any help here!
