### ISSUE TITLE
Bazel target to create C++ library headers

### ISSUE THREAD

**Issue by hillegass** [tensorflow/tensorflow#3536]
Thanks to the `//tensorflow:libtensorflow.so` target, I can now build a shared library that I can use in my C++ programs.  I want to install that library in `/usr/local/lib` and put the headers for it in `/usr/local/include`, but there is no target to build and install those headers.  In particular, building the library doesn't build the headers from the proto files, so I have `error_codes.proto`, but not `error_codes.pb.h`, so I can't even use the source directory for the headers.

**Comment by michaelisard** [comment]
@martinwicke is this addressed in any planned build system changes?

**Comment by martinwicke** [comment]
No

**Comment by keveman** [comment]
Is the target `//tensorflow/core:framework_headers_lib` not sufficient?

**Comment by hillegass** [comment]
The .proto files are not compiled to .pb.h files when I build the `//tensorflow/core:framework_headers_lib` target

```
$ **bazel build //tensorflow/core:framework_headers_lib**
..
WARNING: /private/var/tmp/_bazel_aaron/cd1b...c/external/protobuf/WORKSPACE:1: Workspace name in /private/var/tmp/_bazel_aaron/cd1b...c/external/protobuf/WORKSPACE (@__main__) does not match the name given in the repository's definition (@protobuf); this will cause a build error in future versions.
WARNING: /private/var/tmp/_bazel_aaron/cd1b...c/external/re2/WORKSPACE:1: Workspace name in /private/var/tmp/_bazel_aaron/cd1b...c/external/re2/WORKSPACE (@__main__) does not match the name given in the repository's definition (@re2); this will cause a build error in future versions.
WARNING: /private/var/tmp/_bazel_aaron/cd1b...c/external/highwayhash/WORKSPACE:1: Workspace name in /private/var/tmp/_bazel_aaron/cd1b...c/external/highwayhash/WORKSPACE (@__main__) does not match the name given in the repository's definition (@highwayhash); this will cause a build error in future versions.
INFO: Found 1 target...
Target //tensorflow/core:framework_headers_lib up-to-date (nothing to build)
INFO: Elapsed time: 5.460s, Critical Path: 0.01s
```

**Comment by keveman** [comment]
@hillegass Sorry, I misunderstood your requirement. `//tensorflow/core:framework_headers_lib` is meant for use within a `BUILD` file, when building with `bazel`. If you want to use `libtensorflow.so` in a different build system, and just want the header files, we package them up in the pip packages. For example, [here](https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.9.0-cp27-none-linux_x86_64.whl) is the python2 pip package. The header files go in `<install path>/tensorflow/include`m where `<install path>` is platform dependent. It usually is something like `/usr/local/lib/python2.7/site-packages`. Feel free to close the issue once you verify that it works for you.

**Comment by hillegass** [comment]
My fault.  The headers were, indeed, in the python directory.  (For other lost people, on a Mac the include directory is `/Library/Python/2.7/site-packages/tensorflow/include/` . Thank you!

**Comment by hillegass** [comment]
Quick follow up note for others: A couple of the important headers (especially those related to sessions) are not in that include directory, so you will need to copy them from the source tree: 
`$ cd tensorflow/tensorflow/core/public
$ sudo cp session.h session_options.h tensor_c_api.h /Library/Python/2.7/site-packages/tensorflow/include/tensorflow/core/public/`

**Comment by JueLin** [comment]
I have built the "//tensorflow:libtensorflow.so" target by bazel. Then I have copied all header files in "/usr/local/lib/python3.5/dist-packages/tensorflow" to "/usr/local/include". And I double checked that "session.h" is definitely in "/usr/local/include/tensorflow/core/public".
So I tried to build a very simple project by running command "g++ -o a.out main.cc -I/usr/local/include". And the error message is "main.cc:1:45: fatal error: /tensorflow/core/public/session.h: No such file or directory".  Apparently the "#include "/tensorflow/core/public/session.h" cannot find the header file in "/usr/local/include" even though the "session.h" is definitely there. Can anyone help? I got stuck in this for several days..

**Comment by ftokarev** [comment]
Heads-up: there is a dedicated `//tensorflow:install_headers` target now
