### ISSUE TITLE
Cannot save Keras model to pb using model.save()

### ISSUE THREAD

**Issue by justnoxx** [tensorflow/tensorflow#35365]
Hello!
As been said in https://www.tensorflow.org/guide/keras/save_and_serialize#export_to_savedmodel , to save the Keras model to the format that could be used by TensorFlow, I need to use model.save() and provide save_format='tf', but what it throws me an exception.

**System information**
tf_env_collect.sh has been used to get:

== check python ===================================================
python version: 3.6.10
python branch: 
python build version: ('default', 'Dec 23 2019 13:58:32')
python compiler version: GCC 7.4.0
python implementation: CPython

== check os platform ===============================================
os: Linux
os kernel version: #81-Ubuntu SMP Tue Nov 26 12:20:02 UTC 2019
os release version: 4.15.0-72-generic
os platform: Linux-4.15.0-72-generic-x86_64-with-debian-buster-sid
linux distribution: ('debian', 'buster/sid', '')
linux os distribution: ('debian', 'buster/sid', '')
mac version: ('', ('', '', ''), '')
uname: uname_result(system='Linux', node='hellfire', release='4.15.0-72-generic', version='#81-Ubuntu SMP Tue Nov 26 12:20:02 UTC 2019', machine='x86_64', processor='x86_64')
architecture: ('64bit', '')
machine: x86_64

== are we in docker =============================================
No

== compiler =====================================================
c++ (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

== check pips ===================================================
numpy                1.18.0 
protobuf             3.11.2 
tensorflow           1.14.0 
tensorflow-estimator 1.14.0 

== check for virtualenv =========================================
False

== tensorflow import ============================================
tf.version.VERSION = 1.14.0
tf.version.GIT_VERSION = v1.14.0-rc1-22-gaf24dc91b5
tf.version.COMPILER_VERSION = 4.8.5
== env ==========================================================
LD_LIBRARY_PATH is unset
DYLD_LIBRARY_PATH is unset

== nvidia-smi ===================================================
/tmp/tf_env_collect.sh: line 147: nvidia-smi: command not found

== cuda libs  ===================================================

== tensorflow installed from info ==================
Name: tensorflow
Version: 1.14.0
Summary: TensorFlow is an open source machine learning framework for everyone.
Home-page: https://www.tensorflow.org/
Author-email: packages@tensorflow.org
License: Apache 2.0
Location: /home/noxx/.pyenv/versions/3.6.10/envs/dmitriystf2/lib/python3.6/site-packages
Required-by: 

== python version  ==============================================
(major, minor, micro, releaselevel, serial)
(3, 6, 10, 'final', 0)

== bazel version  ===============================================

**Describe the current behavior**

Exception:
```
Traceback (most recent call last):
  File "load_file2.py", line 14, in <module>
    classifier.save('/tmp/keras-model.pb', save_format='tf')
```

**Describe the expected behavior**

Model is saved as described in https://www.tensorflow.org/guide/keras/save_and_serialize#export_to_savedmodel

**Code to reproduce the issue**

```
import pandas as pd
import tensorflow as tf;
import keras;
from keras import Sequential
from keras.layers import Dense
import json;
import numpy as np;

classifier = Sequential()
classifier.add(Dense(4, activation='relu', kernel_initializer='random_normal', input_dim=4))
classifier.add(Dense(1, activation='sigmoid', kernel_initializer='random_normal'))
classifier.compile(optimizer ='adam',loss='binary_crossentropy', metrics = ['accuracy'])

classifier.save('/tmp/keras-model.pb', save_format='tf')
```

**Other info / logs**
I have the same behavior on tensorflow2

Thanks.

**Comment by oanush** [comment]
@justnoxx ,
Hello, please try saving model in .h5 format using command `classifier.save('my_model.h5')`, model should be saved successfully.
Kindly find the gist of [colab](https://colab.sandbox.google.com/gist/oanush/175dc66b70dd893a710f0b09c8538a97/35365.ipynb) for reference.Thanks!

**Comment by justnoxx** [comment]
@oanush thanks for your answer! .h5 model works fine, there are no issues with that.
Looks like that my issue is resolved for now by replacing 

```
import keras;
from keras import Sequential
from keras.layers import Dense
```

with

```
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense
```

It looks like that it is my fault, so, I will close my issue, but I am just wondering, how it could be that it does not work from direct Keras import? Do they have a different versions?

Thanks for your time.

**Comment by oanush** [comment]
@justnoxx , the first part `import keras` uses [tensorflow as backend](https://keras.io/backend/), and the second one is [tf.keras ](https://www.tensorflow.org/guide/keras)both are not the same.Thanks!

**Comment by justnoxx** [comment]
Thanks a lot. It is clear now.
