### ISSUE TITLE
7.4.1 but source was compiled with: 7.6.0

### ISSUE THREAD

**Issue by SreenijaK** [tensorflow/tensorflow#35376]
Successfully opened dynamic library libcudnn.so.7
2019-12-24 05:34:15.862520: E tensorflow/stream_executor/cuda/cuda_dnn.cc:319] Loaded runtime CuDNN library: 7.4.1 but source was compiled with: 7.6.0.  CuDNN library major and minor version needs to match or have higher minor version in case of CuDNN 7.0 or later version. If using a binary install, upgrade your CuDNN library.  If building from sources, make sure the library loaded at runtime is compatible with the version specified during compile configuration.

**System information**
- Ubuntu 16.04
- TensorFlow version: tensorflow-gpu==1.15.0
- Python version:3.5
- Installed using virtualenv? pip? conda?:-virtualenv
- CUDA 10
cuDNN version:
cat /usr/local/cuda/include/cudnn.h | grep CUDNN_MAJOR -A 2
#define CUDNN_MAJOR 7
#define CUDNN_MINOR 4
#define CUDNN_PATCHLEVEL 1
--
#define CUDNN_VERSION (CUDNN_MAJOR * 1000 + CUDNN_MINOR * 100 + CUDNN_PATCHLEVEL)
- GPU model and memory:

**Comment by gadagashwini** [comment]
@SreenijaK, Please elaborate the issue and also provide the exact sequence of commands / steps that you executed before running into the problem. Thanks!

**Comment by gadagashwini** [comment]
@SreenijaK, Elaborate the issue with context. Thanks!

**Comment by Xiaohui-Z** [comment]
you should download the  cuDNN v7.6.5 in the nivida website then release it. you will find a youfilefolder/cuda/lib64, then add the lib64 to your LD_LIBRARY_PATH. It works for me, my code was this:
1. download cudnn-10.0-linux-x64-v7.6.5.32.tgz
2.tar -zxvf cudnn-10.0-linux-x64-v7.6.5.32.tgz
3. vim ~/.bashrc, add this line"export $LD_LIBRARY_PATH=yourfolder/cuda/lib64:$LD_LIBRARY_PATH" and save
4. source ~/.bashrc

**Comment by gadagashwini** [comment]
@SreenijaK, Download the cuDNN 7.6.5 from nvidia website https://developer.nvidia.com/rdp/cudnn-archive. And install the following packages
```
sudo dpkg -i bcudnn7_7.6.5.32-1+cuda10.0_amd64.deb
sudo dpkg -i libcudnn7-dev_7.6.5.32-1+cuda10.0_amd64.deb
sudo dpkg -i libcudnn7-doc_7.6.5.32-1+cuda10.0_amd64.deb
```
Add the path $LD_LIBRARY_PATH as mentioned by @Xiaohui-Z.
Let us know how it progress. Thanks!

**Comment by gadagashwini** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Comment by PalashSharma15** [comment]
@gadagashwini do we need to uninstall previous version first?

**Comment by gadagashwini** [comment]
@PalashSharma15, In case of multiple versions, Add the desired version path $LD_LIBRARY_PATH

**Comment by PalashSharma15** [comment]
> @PalashSharma15, In case of multiple versions, Add the desired version path $LD_LIBRARY_PATH

Okay Thanks

**Comment by jl0x61** [comment]
> @SreenijaK, Download the cuDNN 7.6.5 from nvidia website https://developer.nvidia.com/rdp/cudnn-archive. And install the following packages
> 
> ```
> sudo dpkg -i bcudnn7_7.6.5.32-1+cuda10.0_amd64.deb
> sudo dpkg -i libcudnn7-dev_7.6.5.32-1+cuda10.0_amd64.deb
> sudo dpkg -i libcudnn7-doc_7.6.5.32-1+cuda10.0_amd64.deb
> ```
> 
> Add the path $LD_LIBRARY_PATH as mentioned by @Xiaohui-Z.
> Let us know how it progress. Thanks!

Hello, I have met the similary problem, the error message is :
```
Loaded runtime CuDNN library: 7.3.1 but source was compiled with: 7.6.0.  CuDNN library major and minor version needs to match or have higher minor version in case of CuDNN 7.0 or later version. If using a binary install, upgrade your CuDNN library.  If building from sources, make sure the library loaded at runtime is compatible with the version specified during compile configuration.
2020-02-28 21:58:20.637693: W tensorflow/core/framework/op_kernel.cc:1651] OP_REQUIRES failed at cudnn_rnn_ops.cc:1510 : Unknown: Fail to find the dnn implementation.
2 root error(s) found.
  (0) Unknown: Fail to find the dnn implementation.
	 [[{{node cu_dnngru_1/CudnnRNN}}]]	 [[Mean/_155]]
  (1) Unknown: Fail to find the dnn implementation.
	 [[{{node cu_dnngru_1/CudnnRNN}}]]
0 successful operations.
0 derived errors ignored.
```
And I download and install cudnn with version 7.6.4:
```
sudo dpkg -i bcudnn7_7.6.4.38-1+cuda10.0_amd64.deb
sudo dpkg -i libcudnn7-dev_7.6.4.38-1+cuda10.0_amd64.deb
sudo dpkg -i libcudnn7-doc_7.6.4.38-1+cuda10.0_amd64.deb
```
And I replaced `/usr/local/cuda/lib64/cudnn.h` with the installed `/usr/include/x86_64-linux-gnu/cudnn_v7.h` and set $LD_LIBRARY_PATH to `/usr/local/cuda/lib64/` but the error message didn't change.
Did I do something wrong?
