### ISSUE TITLE
TensorflowLite gives wrong results when use GPU delegate

### ISSUE THREAD

**Issue by wangyiwei0306** [tensorflow/tensorflow#35378]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):Yes
- OS Platform and Distribution (Android7.1 Snapdragon 625):
- Mobile device (HUAWEI Nova CAZ-AL 10) if the issue happens on mobile device:
- TensorFlow installed from (source):
- TensorFlow version (org.tensorflow:tensorflow-lite-gpu:0.0.0-nightly):

**Describe the current behavior**
I use **yolov3** model on android platform to do object detection. When I did object detection on CPU the results are right but when I add GPU module the results are totally different.

**Code to reproduce the issue**

/**
 * Wrapper for frozen detection models trained using the Tensorflow Object Detection API:
 * github.com/tensorflow/models/tree/master/research/object_detection
 */
public class TFLitePanoObjectDetectionAPIModel implements Classifier {
  private static final Logger LOGGER = new Logger();

  private static final int NUM_of_classes = 19;
  private static final int NUM_THREADS = 4;
  private boolean isModelQuantized;
  private int inputSize;
  private Vector<String> labels = new Vector<String>();
  private int[] intValues;
  private float[][][][] output_1;
  private float[][][][] output_2;
  private float[][][][] output_3;
  private ByteBuffer imgData;
  private Interpreter tflite;
  private MappedByteBuffer tfliteModel;
  private final Interpreter.Options tfliteOptions = new Interpreter.Options();
  private GpuDelegate gpuDelegate = null;
  private NnApiDelegate nnapiDelegate = null;
  private int gridNum;

  private int BoxNum_each_gird=3;
  private float[][][][] floatValues;

  private TFLitePanoObjectDetectionAPIModel() {}
  private float scoreThreshold = 0.3f;
  private int blockSize=32;

  public static Classifier create(
      final AssetManager assetManager,
      final String modelFilename,
      final String labelFilename,
      final int inputSize,
      final boolean isQuantized)
      throws IOException {
    final TFLitePanoObjectDetectionAPIModel d = new TFLitePanoObjectDetectionAPIModel();
    try {

      d.tfliteModel=loadModelFile(assetManager, modelFilename);
      if (d.gpuDelegate == null)
      {
        d.gpuDelegate = new GpuDelegate();
        d.tfliteOptions.addDelegate(d.gpuDelegate);
      }
      d.tflite = new Interpreter(d.tfliteModel,d.tfliteOptions);
    } catch (Exception e) {
      throw new RuntimeException(e);
    }

    d.isModelQuantized = isQuantized;
    // Pre-allocate buffers.
    int numBytesPerChannel;
    if (isQuantized) {
      numBytesPerChannel = 1; // Quantized
    } else {
      numBytesPerChannel = 4; // Floating point
    }
    d.imgData = ByteBuffer.allocateDirect(1 * d.inputSize * 2*d.inputSize * 3 * numBytesPerChannel);//
    d.imgData.order(ByteOrder.nativeOrder());
    d.intValues = new int[d.inputSize * 2*d.inputSize];

    d.gridNum=d.inputSize/32;
    d.floatValues=new float[1][d.inputSize][2 * d.inputSize ][3];
    d.output_1 = new float[1][][][];
    d.output_2 = new float[1][][][];
    d.output_3 = new float[1][][][];

    return d;
  }
  }

  @Override
  public List<Recognition> recognizeImage(final Bitmap bitmap) {

    bitmap.getPixels(intValues, 0, bitmap.getWidth(), 0, 0, bitmap.getWidth(), bitmap.getHeight());
    imgData.rewind();

    for (int i = 0; i < inputSize; ++i)
    {
      for (int j = 0; j < 2*inputSize; ++j)
      {
        int pixelValue = intValues[i * 2*inputSize + j];
          // Float model
          floatValues[0][i][j][0]=((pixelValue >> 16) & 0xFF)/255.0f ;
          floatValues[0][i][j][1]=((pixelValue >> 8) & 0xFF)/255.0f ;
          floatValues[0][i][j][2]=(pixelValue& 0xFF) /255.0f;
      }
    }

     int channelNum=BoxNum_each_gird*(NUM_of_classes+5);

    output_1 = new float[1][gridNum][2*gridNum][channelNum];
    output_2 = new float[1][2*gridNum][4*gridNum][channelNum];
    output_3 = new float[1][4*gridNum][8*gridNum][channelNum];

    Object[] inputArray = {floatValues};
    Map<Integer, Object> outputMap = new HashMap<>();
    outputMap.put(0, output_1);
    outputMap.put(1, output_2);
    outputMap.put(2, output_3);
    Trace.endSection();

    // Run the inference call.
    Trace.beginSection("run");
    long startTime = SystemClock.uptimeMillis();
    tflite.runForMultipleInputsOutputs(inputArray, outputMap);
    long lastingTime=SystemClock.uptimeMillis()-startTime;

    LOGGER.i("runForMultipleInputsOutputs time of each image: " + lastingTime + "ms");
    Trace.endSection(); 
    }

}`
**Describe the expected behavior**

Provide a reproducible test case that is the bare minimum necessary to generate the problem.

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by wangyiwei0306** [comment]
PS: I can run the demos in tensorflowlite correctly on my phone.
 
And I used **modifyGraphWithDelegate()** function and got the following logs:

I/tflite: Initialized TensorFlow Lite runtime.
I/tflite: Created TensorFlow Lite delegate for GPU.
E/libEGL: validate_display:99 error 3008 (EGL_BAD_DISPLAY)
I/tflite: Initialized OpenCL-based API.
I/art: Background sticky concurrent mark sweep GC freed 580(74KB) AllocSpace objects, 1(20KB) LOS objects, 0% free, 74MB/74MB, paused 287us total 174.102ms
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.tensorflow.lite.examples.detection, PID: 8779
    java.lang.RuntimeException: Unable to start activity ComponentInfo{org.tensorflow.lite.examples.detection/org.tensorflow.lite.examples.detection.PanoDetectorActivity}: java.lang.IllegalArgumentException: Internal error: Failed to apply delegate: Next operations are not supported by GPU delegate:
    MAXIMUM: Operation is not supported.
    RESIZE_NEAREST_NEIGHBOR: Operation is not supported.
    First 2 operations will run on the GPU, and the remaining 249 on the CPU.
    ModifyGraphWithDelegate is disallowed when graph is immutable.
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2793)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2864)
        at android.app.ActivityThread.-wrap12(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1567)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:156)
        at android.app.ActivityThread.main(ActivityThread.java:6523)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)
     Caused by: java.lang.IllegalArgumentException: Internal error: Failed to apply delegate: Next operations are not supported by GPU delegate:
    MAXIMUM: Operation is not supported.
    RESIZE_NEAREST_NEIGHBOR: Operation is not supported.
    First 2 operations will run on the GPU, and the remaining 249 on the CPU.
    ModifyGraphWithDelegate is disallowed when graph is immutable.
        at org.tensorflow.lite.NativeInterpreterWrapper.applyDelegate(Native Method)
        at org.tensorflow.lite.NativeInterpreterWrapper.modifyGraphWithDelegate(NativeInterpreterWrapper.java:195)
        at org.tensorflow.lite.Interpreter.modifyGraphWithDelegate(Interpreter.java:409)
        at org.tensorflow.lite.examples.detection.tflite.TFLitePanoObjectDetectionAPIModel.recognizeImage(TFLitePanoObjectDetectionAPIModel.java:281)
        at org.tensorflow.lite.examples.detection.PanoDetectorActivity.onCreate(PanoDetectorActivity.java:134)
        at android.app.Activity.performCreate(Activity.java:6915)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1123)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2746)
        	... 9 more
I/Process: Sending signal. PID: 8779 SIG: 9
Disconnected from the target VM, address: 'localhost:8608', transport: 'socket'

So, I have questions:
1. Did I start GPU correctly?
2. I only add GPU option to my code why the results are totally different compared with results on CPU whose results are right?

**Comment by impjdi** [comment]
That's quite a wall of code that you just dumped on the wall =/

> Did I start GPU correctly?

Apparently not; the real failure is:

> ModifyGraphWithDelegate is disallowed when graph is immutable.

You would have to find out what triggers that condition.  I, unfortunately, haven't experienced that condition and can't tell what you're doing wrong.

> I only add GPU option to my code why the results are totally different compared with results on CPU whose results are right?

Based on:

> First 2 operations will run on the GPU, and the remaining 249 on the CPU.

There is some relay; first 2 ops on the GPU, and then the 249 ops on the CPU.  Maybe something is broken there?

**Comment by wangyiwei0306** [comment]
@impjdi Thank you very much for your help. Sorry with such wall of codes.
On tensorflow official document https://www.tensorflow.org/lite/performance/gpu it said 

>  if some of the ops are not supported by the GPU delegate, the framework will only run a part of the graph on the GPU and the remaining part on the CPU. And in this case, the user will get a warning like:
> WARNING: op code #42 cannot be handled by this delegate.

But when I add gpu delegate like:

`    
try {
      d.tfliteModel=loadModelFile(assetManager, modelFilename);
      if (d.gpuDelegate == null)
      {
        d.gpuDelegate = new GpuDelegate();
        d.tfliteOptions.addDelegate(d.gpuDelegate);
      }
      d.tflite = new Interpreter(d.tfliteModel,d.tfliteOptions);
    } catch (Exception e) {
      throw new RuntimeException(e);
    }
`
And use  it like:
 `tflite.runForMultipleInputsOutputs(inputArray, outputMap);`

I only got logs like :

> I/tflite: Created TensorFlow Lite delegate for GPU.
> I/tflite: Initialized TensorFlow Lite runtime.
> E/libEGL: validate_display:99 error 3008 (EGL_BAD_DISPLAY)
> I/tflite: Initialized OpenCL-based API.
> I/art: Background sticky concurrent mark sweep GC freed 431(60KB) AllocSpace objects, 1(20KB) LOS objects, 0% free, 74MB/74MB, paused 1.324ms total 147.756ms
> I/tensorflow: TFLitePanoObjectDetectionAPIModel: runForMultipleInputsOutputs time of each image: 20778ms
> I/tensorflow: PanoDetectorActivity: Inference time of each image: 20980ms
> I/HwPointEventFilter: do not support AFT because of no config
> I/Adreno: QUALCOMM build                   : 26f5f0d, I4f723aa5a2
>     Build Date                       : 04/26/17
>     OpenGL ES Shader Compiler Version: XE031.09.00.03
>     Local Branch                     : 
>     Remote Branch                    : refs/tags/AU_LINUX_ANDROID_LA.UM.5.5.R1.07.00.00.269.013
>     Remote Branch                    : NONE
>     Reconstruct Branch               : NOTHING
> I/OpenGLRenderer: Initialized EGL, version 1.4
> W/OpenGLRenderer: load: so=libhwuibp.so
>     dlopen failed: library "libhwuibp.so" not found
>     Initialize Binary Program Cache: Load Failed
> I/Adreno: QUALCOMM build                   : 26f5f0d, I4f723aa5a2
>     Build Date                       : 04/26/17
>     OpenGL ES Shader Compiler Version: XE031.09.00.03
>     Local Branch                     : 
>     Remote Branch                    : refs/tags/AU_LINUX_ANDROID_LA.UM.5.5.R1.07.00.00.269.013
>     Remote Branch                    : NONE
>     Reconstruct Branch               : NOTHING
> I/OpenGLRenderer: Initialized EGL, version 1.4

There are not detecting results like:
navigation_display (4) 0.311861 RectF(784.7063, 239.35332, 825.18225, 258.89636)

The followings are my assumptions:
1. In yolov3 network there are some residual block , did TFLite gpu support ?
2. In yolov3 network there are Leaky_ReLU, is this affect my precision?
3. My network transformation from .pb to .tflite is not right?

**Comment by impjdi** [comment]
1. For the same model, normalization should be the same.  GPU doesn't do anything on top of it; it just processes the input as is.

2. It can't be totally the same, because of floating point precision loss.  Even with CPU, two implementations will give you different numbers.  Remember, with floating point, a + b + c is not the same as c + b + a.  It should be close though.

3. It depends on the intermediate tensors too, not just the input tensor.  However, as a data point, I had to reduce 513x513 in DeepLab segmentation to 257x257 so that it runs on the GPU, because 513x513 was too huge.  But in those cases, you will most likely get other types of error (out of memory or something like that), rather than a wrong answer.

4. You would have to read the log; it will tell you how many ops were run on the GPU and how many on the CPU.  In normal case, you should get a similar answer because if GPU fails to replace parts of the graph, it will fall back to CPU.

**Comment by wangyiwei0306** [comment]
@impjdi  I totally agree with your comments. Now I only add GPU delegate like:

> d.tfliteModel=loadModelFile(assetManager, modelFilename);
> d.gpuDelegate = new GpuDelegate();
> d.tfliteOptions.addDelegate(d.gpuDelegate);
> d.tflite = new Interpreter(d.tfliteModel,d.tfliteOptions);

And in my log I only can see:

> I/tflite: Created TensorFlow Lite delegate for GPU.
> I/tflite: Initialized TensorFlow Lite runtime.
> E/libEGL: validate_display:99 error 3008 (EGL_BAD_DISPLAY)
> I/tflite: Initialized OpenCL-based API.
> I/art: Background sticky concurrent mark sweep GC freed 410(47KB) AllocSpace objects, 1(20KB) LOS objects, 0% free, 74MB/74MB, paused 367us total 147.780ms
> I/tensorflow: TFLitePanoObjectDetectionAPIModel: runForMultipleInputsOutputs time of each image: 19333ms
> I/tensorflow: PanoDetectorActivity: Inference time of each image: 19588ms
> I/HwPointEventFilter: do not support AFT because of no config
> I/Adreno: QUALCOMM build                   : 26f5f0d, I4f723aa5a2
>     Build Date                       : 04/26/17
>     OpenGL ES Shader Compiler Version: XE031.09.00.03
>     Local Branch                     : 
>     Remote Branch                    : refs/tags/AU_LINUX_ANDROID_LA.UM.5.5.R1.07.00.00.269.013
>     Remote Branch                    : NONE
>     Reconstruct Branch               : NOTHING
> I/OpenGLRenderer: Initialized EGL, version 1.4
> W/OpenGLRenderer: load: so=libhwuibp.so
>     dlopen failed: library "libhwuibp.so" not found
>     Initialize Binary Program Cache: Load Failed

No information about how many ops  run on the GPU and how many on the CPU.  
1. If I want to check how many ops  run on the GPU and how many on the CPU, which function should I use? 
2. Do you ever encounter such problems,  can you provide me some possible solutions or ways to debug this problem?

**Comment by sushreebarsa** [comment]
@wangyiwei0306 We see that you are using older version of tensorflow .Many bug have been fixed in latest version. We recommend that you upgrade to latest stable version of tensorflow 2.6.0 and let us know if the issue still persists in newer versions .Thanks!
