### ISSUE TITLE
Cannot export keras model to SavedModel if mixed-precision policy is enabled

### ISSUE THREAD

**Issue by bearsroom** [tensorflow/tensorflow#35379]
**System information**

- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Debian 9
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): starting from 2.0, nightly version tested
- Python version: 3.5

**Describe the current behavior**

When keras mixed-precision policy "mixed_float16" is in use, we can't save the keras model in SavedModel format with method `keras.models.Model.save` without a specific `signatures`. It seems like a mismatch between input signature inferred by the model itself and the auto-casted inputs:

```
ValueError: Python inputs incompatible with input_signature: inputs ((<tf.Tensor 'conv1_pad/Cast:0' shape=(None, 224, 224, 3) dtype=float16>,)), input_signature ((TensorSpec(shape=(None, None, None, None), dtype=tf.float32, name=None),))
```

Although we can use `graph_rewrite` as mixed-precision training method to bypass this autocasting issue, but `graph_rewrite` is not working in some cases (e.g. train a subclassed model with `tf.GradientTape`) thus it is not recommended by tensorflow official guide. For flexibility we do hope to use mixed-precision policy in mixed-precision training, and directly exporting mixed-precision trained model to SavedModel for deployment is straightforward in production pipeline.

**Code to reproduce the issue**

We can reproduce this bug by using the official image classification training example from https://github.com/tensorflow/models/tree/master/official/vision/image_classification

```
"""
Test mixed-precision policy model saving
"""
import logging
import os

from absl import app as absl_app
import tensorflow as tf

from official.vision.image_classification.resnet_model import resnet50


def main(argv):
  tf.compat.v1.enable_eager_execution()
  
  # setup mixed-precision policy
  # the policy enables the autocasting behavior in keras layers
  policy = tf.keras.mixed_precision.experimental.Policy(
        'mixed_float16', loss_scale=128)
  tf.keras.mixed_precision.experimental.set_policy(policy)

  model = resnet50(1000)
  model_dir = 'temp/saved_model_test'

  if not os.path.isdir(model_dir):
    os.makedirs(model_dir)
  model.save(model_dir,
             save_format='tf')
  logging.info('Exported trained model to directory {}'.format(
      model_dir))


if __name__ == '__main__':
  absl_app.run(main)
```

**Comment by byronyi** [comment]
Gently ping @reedwm; does this look familiar to you?

**Comment by oanush** [comment]
When tried replicating the issue, I got the error as per the colab [gist](https://colab.sandbox.google.com/gist/oanush/1cc1d54c6411da3cdc2d5009b59775b1/35379.ipynb).Thanks!

**Comment by reedwm** [comment]
Thank you for filing this and the short example to reproduce. I will have a fix soon. In the future, I plan on testing the official models with SavedModel to ensure issues like this do not occur in the future.

**Comment by byronyi** [comment]
@reedwm @goldiegadde shall we apply the fix above to r2.1? Mixed precision along with XLA improves training performance dramatically and we’d really like to use it with our e2e training/inference pipeline

**Comment by jtavrisov** [comment]
Is this working for anyone. I updated to 2.1 and I no longer get this same error but now I get

TypeError: Input 'filter' of 'Conv2D' Op has type float16 that does not match type float32 of argument 'input'.

I tried this first on my models and then ran the given snippet and got the same deal.

**Comment by reedwm** [comment]
Unfortunately the fix did not make it into 2.1 :(. It will be in 2.2 however, and the fix is already in `tf-nightly`

I'm not sure why the error message is different. Note that `Model.save_weights` still works, just not `Model.save`. 

As a workaround, you can call `Model.save_weights`, rebuild the model in fp32, call `Model.load_weights` on the fp32 model then call `Model.save`. But understandably, this is very irritating, and it doesn't save a mixed precision model. Using the old [`tf.train.experimental.enable_mixed_precision_graph_rewrite`](https://www.tensorflow.org/api_docs/python/tf/train/experimental/enable_mixed_precision_graph_rewrite) API also works but note we plan on deprecating then removing it (it will remain in `tf.compat.v1` for a long time though).

**Comment by chebcia** [comment]
Still affected in tf= 2.11.0

**Comment by innat** [comment]
Until now, tensorflow/keras doens't support saving model (`model.save`) other than float32 dtype, thus saving model with mixed precision (`float16` / ` bfloat16`) is not supported. Even if you manually cast to `float32` on some operations while mixed precision is enabled and eventually save the model successfully, it saves as `float32` format. Very disappointing. I wonder if `keras-v3` format any different. 

https://github.com/keras-team/keras/issues/17275
