### ISSUE TITLE
Use tf-lite C++ API for both Android and iOS

### ISSUE THREAD

**Issue by rishabhrishu** [tensorflow/tensorflow#35386]
**System information**
- OS Platform and Distribution: macOS 10.14.5
- TensorFlow installed from (source or binary): source
- TensorFlow version: v.2.0
- Python version: 3.7
- Installed using virtualenv? pip? conda?: source
- Bazel version (if compiling from source): 0.24.1
- GCC/Compiler version (if compiling from source): clang version 7.0.1

I am a mobile developer, using C++ to build portable parts of my apps that work on both Android and iOS.
Here is my workflow:
- For portable parts, I code a cross-platform library on macOS, build/unit-test it on macOS
- then, build/unit-test it on Linux
- create android and ios builds of the library using the respective toolchains, and integrate it into the mobile apps

While exploring tflite, I can see multiple APIs: C, C++, Obj-C, Swift, Java.
To write portable code, Obj-C/Swift/Java APIs are out of picture.
Is there any common API (C or C++) which can be used to evaluate tf-lite models on macOS, Linux, Android and iOS? If yes, what are the bazel targets to build?

**Comment by dimitrijer** [comment]
I have been using C API (`tensorflow/lite/c`) to successfully run inference on TFLite models on macOS, Windows and Android ARM/ARM64 from Unity. Right now I am trying to see whether I can use the same API for iOS.

Bazel commands for building static libraries are, in order for macOS/Windows, ARM64 Android and ARM Android:
```
bazel build -c opt --cxxopt=--std=c++11 //tensorflow/lite/c:tensorflowlite_c
bazel build -c opt --cxxopt=--std=c++11 --config=android_arm64 //tensorflow/lite/c:tensorflowlite_c
bazel build -c opt --cxxopt=--std=c++11 --config=android_arm //tensorflow/lite/c:tensorflowlite_c
```
You need to run `./configure` prior to this to set up Bazel to use Android toolchain.

**Comment by freedomtan** [comment]
@dimitrijer short answer for building C API library for iOS arm64:
```
 bazel build -c opt --config ios_arm64 //tensorflow/lite/experimental/ios:TensorFlowLiteC_framework  
```

And you may want to check `tensorflow/lite/experimental/ios/BUILD`

**Comment by dimitrijer** [comment]
@freedomtan thanks, will check that out!

I also found out a set of scripts that build C++ TFLite static library for multiple Android/iOS architectures at `tensorflow/lite/tools/make` - and the library also includes the C API! I get universal `libtensorflowlite.a` library after running `build_ios_universal_lib.sh -a "armv7 armv7s arm64"`. If I copy over C API headers, I should be able to link against this static library during Unity XCode build.

**Comment by rishabhrishu** [comment]
I was able to build C++ static library for iOS, following instructions provided by @dimitrijer. Is there a similar way to build it for Android for following architectures: `'x86', 'x86_64', 'armeabi-v7a', 'arm64-v8a'`?

**Comment by freedomtan** [comment]
There are `android, android_arm (armeabi-v7a), android_arm64 (arm64-v8a), android_x86, and android_x86_64`. Check your `$ROOT_OF_TENSORFLOW_SORUCE/.bazelrc` or https://github.com/tensorflow/tensorflow/blob/master/.bazelrc for how they are defined.

**Comment by ymodak** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Comment by corporate-fun** [comment]
@ymodak @freedomtan I wonder if I can hijack this issue to ask a question... 

Are there any benefits that I would get from using the iOS Swift library and the Android Java library that I wouldn't get from using the cross-platform c++ library? 

For example, in the documentation for tflite there is a section about "GPU Acceleration and Delegates" (https://www.tensorflow.org/lite/guide/get_started#gpu_acceleration_and_delegates). Would I no longer have easy access to these delegates that leverage platform specific capabilities if I choose to go with a cross-platform c++ implementation? I want to ensure that I am leveraging things like Android NN API and iOS Metal and any other future platform specific performance enhancements that become available.

Best
