### ISSUE TITLE
ERROR: Next operations are not supported by GPU delegate.

### ISSUE THREAD

**Issue by shauryad15** [tensorflow/tensorflow#35389]
INFO: Initialized TensorFlow Lite runtime.
INFO: Created TensorFlow Lite delegate for GPU.
ERROR: Next operations are not supported by GPU delegate:
CONCATENATION: 
CONV_2D: 
CUSTOM TFLite_Detection_PostProcess: Operation is not supported.
DEPTHWISE_CONV_2D: 
LOGISTIC: 
RESHAPE: 
First 0 operations will run on the GPU, and the remaining 64 on the CPU.

I've converted model to tflite and i'm getting this error. Can anybody help me why i'm getting this and/or what could be the possible reason?

Here's the code:

bool ObjectDetector::init(const std::string &model_file, bool is_quantized,
                          const std::string &labels_file)
{
    // Load model.
    model_ = tflite::FlatBufferModel::BuildFromFile(model_file.c_str());
    if (!model_)
    {
        LOG(ERROR) << "Failed to load model: " << model_file;
        return false;
    }

    // Create interpreter.
    tflite::ops::builtin::BuiltinOpResolver resolver;
    tflite::InterpreterBuilder(*model_, resolver)(&interpreter_);
    if (!interpreter_)
    {
        LOG(ERROR) << "Failed to create interpreter!";
        return false;
    }
    /*if (interpreter_->AllocateTensors() != kTfLiteOk)
    {
        LOG(ERROR) << "Failed to allocate tensors!";
        return false;
    }
    const TfLiteGpuDelegateOptions options = {
    .metadata = NULL,
    .compile_options = {
        .precision_loss_allowed = 1,  // FP16
        .preferred_gl_object_type = TFLITE_GL_OBJECT_TYPE_FASTEST,
        .dynamic_batch_enabled = 0,   // Not fully functional yet
    },
    };*/
    auto* delegate = TfLiteGpuDelegateCreate(/*default options=*/nullptr);
    if (interpreter_->ModifyGraphWithDelegate(delegate) != kTfLiteOk) return false;
    //LOG(ERROR) << "DetectEmptyParkingSlots:: TfLiteGpuDelegateCreate Passed!!! Hurray!....." << std::endl;
    
    //interpreter_->SetNumThreads(1);
    interpreter_->UseNNAPI(1);

    // Find input tensors.
    if (interpreter_->inputs().size() != 1)
    {
        LOG(ERROR) << "Graph needs to have 1 and only 1 input!";
        return false;
    }
    input_tensor_ = interpreter_->tensor(interpreter_->inputs()[0]);
    if (is_quantized)
    {
        if (input_tensor_->type != kTfLiteUInt8)
        {
            LOG(ERROR) << "Quantized graph's input should be kTfLiteUInt8!";
            return false;
        }
    }
    else
    {
        if (input_tensor_->type != kTfLiteFloat32)
            LOG(ERROR) << "Quantized graph's input should be kTfLiteFloat32!";
        {
            return false;
        }
    }

    // Find output tensors.
    if (interpreter_->outputs().size() != 4)
    {
        LOG(ERROR) << "Graph needs to have 4 and only 4 outputs!";
        return false;
    }
    output_locations_ = interpreter_->tensor(interpreter_->outputs()[0]);
    output_classes_ = interpreter_->tensor(interpreter_->outputs()[1]);
    output_scores_ = interpreter_->tensor(interpreter_->outputs()[2]);
    num_detections_ = interpreter_->tensor(interpreter_->outputs()[3]);

    std::vector<std::string> labels;
    ReadLines(labels_file, &labels);
    labels_ = labels;
    return true;
}

**Comment by impjdi** [comment]
I have the impression you messed up with the TF source code based on:

> ERROR: Next operations are not supported by GPU delegate:
> CONCATENATION:
> CONV_2D:
> DEPTHWISE_CONV_2D:
> LOGISTIC:
> RESHAPE:

As these are properly supported on the GPU delegate.  It is natural for 

> CUSTOM TFLite_Detection_PostProcess: Operation is not supported.

as the GPU delegate doesn't implement that.

**Comment by shauryad15** [comment]
Any pointers on how to solve it?

**Comment by shauryad15** [comment]
any update on the same? can i have a proper doc or reference on how to use gpu delecate?

**Comment by impjdi** [comment]
Your code snippet is correct in terms of how to initialize things.  What I'm not clear is why you're getting 

> ERROR: Next operations are not supported by GPU delegate:
> CONCATENATION:
> CONV_2D:
> DEPTHWISE_CONV_2D:
> LOGISTIC:
> RESHAPE:

as we support those.  Can you attach the model?

**Comment by shauryad15** [comment]
[detect.zip](https://github.com/tensorflow/tensorflow/files/4095732/detect.zip)
this is the model. also i would like to know that is there any specific way to convert the model to run in gpu? i've followed this link for conversion https://medium.com/tensorflow/training-and-serving-a-realtime-mobile-object-detector-in-30-minutes-with-cloud-tpus-b78971cf1193 .

**Comment by impjdi** [comment]
I see you're using a quantized network.  For GPU, you want float models :)

**Comment by shauryad15** [comment]
sorry, I posted a different model. 
[detect.zip](https://github.com/tensorflow/tensorflow/files/4096225/detect.zip)

this is the correct model.

**Comment by shauryad15** [comment]
ok, i'll explain what I did, may be from there you can guide me better. I took ssd_mobilenet_v1 model, did transfer learning on my data and saved the model using https://medium.com/tensorflow/training-and-serving-a-realtime-mobile-object-detector-in-30-minutes-with-cloud-tpus-b78971cf1193 this link. After training, I exported the model using python object_detection/export_tflite_ssd_graph.py \
--pipeline_config_path=$CONFIG_FILE \
--trained_checkpoint_prefix=$CHECKPOINT_PATH \
--output_directory=$OUTPUT_DIR \
--add_postprocessing_op=true . Now, from here, can you please guide on what to do next to run it on gpu. I'm using snapdragon 8155 soc. It'll be very helpful. @impjdi

**Comment by shauryad15** [comment]
@impjdi any update?

**Comment by impjdi** [comment]
I'm not familiar with the object detector, but the post clearly states that it's related to quantization.  If you inspect your network, you can see it has FakeQuant ops everywhere.  Those are not compatible with GPUs as mentioned before.  Try to get a hold of the original float model.

**Comment by shauryad15** [comment]
@impjdi can you please add someone who can help me in converting ssd_mobilenet_v1 model into tflite float model for running in snapdragon board using gpu delegate. I can't find a proper **documentation** anywhere. When i'm using this script :

tflite_convert --output_file ./model.tflite --saved_model_dir /home/shaurya/Downloads/ssd_mobilenet_v1_coco_2018_01_28/saved_model --output_format TFLITE --inference_type FLOAT --input_arrays image_tensor --input_shapes 1,300,300,3 --output_arrays detection_boxes,detection_classes,detection_scores,num_detections

I'm getting this error: ValueError: None is only supported in the 1st dimension. Tensor 'image_tensor' has invalid shape '[None, None, None, 3]'.

It's been more than 2 month and i'm struck.

@achowdhery

**Comment by shauryad15** [comment]
any help sir?

**Comment by impjdi** [comment]
The command line that you use looks correct to me, but note that I'm not super familiar with TOCO myself; I usually only work with the final Flatbuffer model, and use flatc to convert back and forth.

I would try to grep for the error message in the code base and find out what condition is failing.

**Comment by shauryad15** [comment]
@impjdi do you have any follow steps on how to convert an object detection model into it's compatible tflite format so that we can use gpu delegate to run it?

I tried converting it the model into it's tflite format but i'm getting model initialisation error. no documentation is available in internet. Do you any?

**Comment by shauryad15** [comment]
[detect.zip](https://github.com/tensorflow/tensorflow/files/4132456/detect.zip)
@impjdi can you check this model? Is this fine?

**Comment by impjdi** [comment]
Yeah, I think this looks like a float model.  Of course, GPU delegate won't be able to run the last op (TFLite_Detection_PostProcess) but the rest should be runnable on the GPU.

**Comment by shauryad15** [comment]
is there any reason why it's not supported??

Anyways, I'm able to use GPU now.

**Comment by impjdi** [comment]
We have limited resource and cannot even implement every builtin op.  A very specialized post processing op is surely very far away from being prioritized.

Glad that GPU works for you now.
