### ISSUE TITLE
Save model to pb and pbtxt

### ISSUE THREAD

**Issue by GaranceRichard** [tensorflow/tensorflow#35382]
I would like to use a model trained on python on C++

tried by tflite but cmake needed don't work
by the past, I had to use pb file and pbtxt file that works.

In TF 2.0 how could I save a Model to pb and pbtxt file to use it on C++
Or is there a better way that doesn't involve Cmake ?

Thanks a lot,

**Comment by gadagashwini** [comment]
@GaranceRichard, Please follow [this](https://www.tensorflow.org/guide/saved_model#load_a_savedmodel_in_c) guide to load a savedmodel in C++. Let us know if it helps. Thanks!

**Comment by GaranceRichard** [comment]
with my model (as model) I did :
tf.saved_model.save(model,"") which gives me a saved_model.pb
sent to C++ dev, I'll tell you if it's ok...

**Comment by gadagashwini** [comment]
@GaranceRichard, Any update!

**Comment by gadagashwini** [comment]
Closing this issue now, Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
