### ISSUE TITLE
TF1.14.0 C++  CPU single thread 

### ISSUE THREAD

**Issue by crystalwan** [tensorflow/tensorflow#35387]
I compiling tensorflow library (libtensorflow_cc.so libtensorflow_framework.so) by bazel，and used it in CPU mode. I want to run the program linked by the built tf library in one thread. The configuration bellow is set.
      
     

- SessionOptions opts;

- opts.config.set_inter_op_parallelism_threads(1)

- opts.config.set_intra_op_parallelism_threads(1)

But the number of the threads  is 4. except the main thread, there are 3 threads, which be created by the bellow function:

- tensorflow::thread::EigenEnvironment::CreateThread()

- Eigen::ThreadPoolTempl<tensorflow::thread::EigenEnvironment>::WorkerLoop(int)

how to close these three threads?

**Comment by gowthamkpr** [comment]
@crystalwan Please post this question in stackoverflow as this is not related to bug/performance, feature request, build/install related issue. Thanks!

**Comment by fisakhan** [comment]
@crystalwan did you solve the problem? I'm facing the same problem. I couldn't find answer to this question on the following github and stackoverflow issues:
https://github.com/tensorflow/tensorflow/issues/42510
https://github.com/tensorflow/tensorflow/issues/33627
https://github.com/usnistgov/frvt/issues/12
https://github.com/tensorflow/models/issues/3176
https://github.com/tensorflow/tensorflow/issues/13853
https://stackoverflow.com/questions/47548145/understanding-tensorflow-inter-intra-parallelism-threads
https://stackoverflow.com/questions/60206113/how-to-stop-tensorflow-from-multi-threading
https://stackoverflow.com/questions/34389945/changing-the-number-of-threads-in-tensorflow-on-cifar10
https://stackoverflow.com/questions/39035639/importing-tensorflow-spawns-threads
