### ISSUE TITLE
no such target '//tensorflow:windows': target 'windows' not declared in package

### ISSUE THREAD

**Issue by jude2014** [tensorflow/tensorflow#35397]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from source:
- TensorFlow version 1.13.1:
- Python version: 3.6.7
- Installed using virtualenv? pip? conda?:anaconda3
- Bazel version (if compiling from source): 0.21.0
- GCC/Compiler version (if compiling from source):4.8
- CUDA/cuDNN version: CUDA10, cuDNN7.4
- GPU model and memory: GPU memory 22G, model bert-base-chinese

**Describe the problem**

**Provide the exact sequence of commands / steps that you executed before running into the problem**
bazel build :loader --config=monolithic

**Any other info / logs**
![image](https://user-images.githubusercontent.com/11387828/71431384-6bf93e80-26c9-11ea-9b98-f915b0e8d17b.png)
i don‘t know what happen, i build a tensor add operator demo and it success, but when i load pb model it fails and i rowback to the demo it never success again and report such error, how should i do?

**Comment by jude2014** [comment]
os is linux

**Comment by gadagashwini** [comment]
@jude2014, Please provide the complete code snippet to replicate the reported issue. Thanks!

**Comment by gadagashwini** [comment]
@jude2014, Any update on the issue. 
Provide the exact sequence of commands / steps that you executed before running into the problem.

**Comment by gadagashwini** [comment]
@jude2014, Is this still an issue. Thanks!

**Comment by gadagashwini** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
