### ISSUE TITLE
Tutorials are difficult to read

### ISSUE THREAD

**Issue by veita** [tensorflow/tensorflow#354]
Greyish text on white background causes eye fatigue. Especially with longer text, and sanserif fonts.

**Comment by vrv** [comment]
@danmane, @martinwicke: I assume this is just a css style change?

**Comment by martinwicke** [comment]
Not quite but almost. Dan is on it.

**Comment by danmane** [comment]
Done.

**Comment by veita** [comment]
The contrast is much better now. So the readability.

Thank you very much.
