### ISSUE TITLE
Variable.assign throws expection randomly

### ISSUE THREAD

**Issue by mbz** [tensorflow/tensorflow#3540]
I'm trying to copy weights between two graphs which are running in two different processes simply by fetching the values from one, sending them to the second process and assigning the values there.

The code I have is pretty simple and straight forward:

    def get_all_variable_values(self):
        vars = list(self.sess.graph.get_collection(tf.GraphKeys.TRAINABLE_VARIABLES))
        names = [v.name for v in vars]
        values = self.sess.run(vars)
        return dict(zip(names, values))

    def set_all_variable_values(self, update_dict):
        for var in self.sess.graph.get_collection(tf.GraphKeys.TRAINABLE_VARIABLES):
            self.sess.run(var.assign(update_dict[var.name]))

But time to time (seems to be completely random), the following exception happens.
I also tried replacing `Variable.assign` with `tf.assign` and the same problem happens.

Any idea why?

```
Traceback (most recent call last):
  File "/home/mbz/anaconda3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 715, in _do_call
    return fn(*args)
  File "/home/mbz/anaconda3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 697, in _run_fn
    status, run_metadata)
  File "/home/mbz/anaconda3/lib/python3.5/contextlib.py", line 66, in __exit__
    next(self.gen)
  File "/home/mbz/anaconda3/lib/python3.5/site-packages/tensorflow/python/framework/errors.py", line 450, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors.NotFoundError: FetchOutputs node Assign_404:0: not found

During handling of the above exception, another exception occurred.

Traceback (most recent call last):
  File "/home/mbz/anaconda3/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/home/mbz/anaconda3/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/home/mbz/projects/pacman_multi_gpu/ProcessServer.py", line 50, in update_model
    self.model.set_all_variable_values(update_dict)
  File "/home/mbz/projects/pacman_multi_gpu/NetworkVP.py", line 258, in set_all_variable_values
    self.sess.run(var.assign(update_dict[var.name]))
  File "/home/mbz/anaconda3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 372, in run
    run_metadata_ptr)
  File "/home/mbz/anaconda3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 636, in _run
    feed_dict_string, options, run_metadata)
  File "/home/mbz/anaconda3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 708, in _do_run
    target_list, options, run_metadata)
  File "/home/mbz/anaconda3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 728, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors.NotFoundError: FetchOutputs node Assign_404:0: not found

```

**Comment by michaelisard** [comment]
This is probably better discussed on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow). Have you tried creating the graph before the call to run? It looks as if you are modifying the graph inside the loop in set_all_variable_values.

**Comment by mbz** [comment]
The graph has been created beforehand, but I'm not modifying it (at least not deliberately!).
I'm not sure which line in `set_all_variable_values` you are talking about:

    for var in self.sess.graph.get_collection(tf.GraphKeys.TRAINABLE_VARIABLES):

This one is to just go through all the variables, and this 

    self.sess.run(var.assign(update_dict[var.name]))

just replaces their value.

**Comment by michaelisard** [comment]
TensorFlow works by first building a graph of Ops, and then running that graph once it is assembled. tf.assign adds a new assign node to the graph, which is typically run later as a side-effect of calling tf.run on some node. In your case you are adding the new node and then calling run on the newly-added node. As I said, this kind of discussion is better suited to the StackOverflow forum which is a good place for discussing TensorFlow usage.

**Comment by mbz** [comment]
Thanks, that makes sense. However that still doesn't explain the random behaviour of TensorFlow, does it? With your explanation, the rational is that `Graph` object is not thread safe and if changes while being processed the code may break?

**Comment by michaelisard** [comment]
Well, I'm not sure because you didn't provide a larger code snippet but you did say that there are multiple processes and it's unclear how you are calling it. It certainly isn't the common use case to have multiple threads mutating the graph concurrently. @mrry could you comment on what if any guarantees there are for thread safety?

**Comment by mrry** [comment]
Which version of TensorFlow are you running? The thread safety of the `tf.Graph` has been improved somewhat recently, so it'd be great if you could confirm this is still a problem with the latest version.

In general though, if you're modifying the graph in response to an unbounded number of server requests, there's a memory leak that will bite you in the future. I'd suggest creating one assign op per variable ahead of time, which would take a placeholder that you could feed each time you get a new value. That would address the leak (and sidestep the potential thread safety issue).

**Comment by mbz** [comment]
Thanks for the reply. I'm switching to your design. Just out of curiosity, can I pull the same thing off using a `Saver`? It seems what `Saver` essentially does is the same as what you described.

I'm using Version: 0.9.0rc0. Can update to a newer version if it is available.

**Comment by mrry** [comment]
Yes, you could do this using a `Saver`, but it should be slightly faster (fewer copies etc.) to go through the feed mechanism. Either way, creating the saver or the placeholders once would be the way to go.

It looks like the thread-safety fix missed 0.9, but it should be in the nightlies and 0.10rc0.

**Comment by mbz** [comment]
cool, I ended up writing the following functions:

```
    def _create_restore_point(self):
        self.restore_dict = {}
        self.restore_ops = []
        for var in self.sess.graph.get_collection(tf.GraphKeys.TRAINABLE_VARIABLES):
            place_holder = tf.placeholder(tf.float32, var.get_shape(), 'ph%s' % var.name.split(':')[0])
            self.restore_dict[var.name] = place_holder
            self.restore_ops.append(tf.assign(var, place_holder))

    def set_all_variable_values(self, update_dict):
        feed_dict = {}
        for name, value in update_dict.items():
            feed_dict[self.restore_dict[name]] = value
        self.sess.run(self.restore_ops, feed_dict=feed_dict)
```

It seems that it is working, but may not be optimal.

**Comment by mrry** [comment]
That looks good to me. I'll close this issue for now, since it doesn't seem like there's any (unfixed) bug, but feel free to reopen if that doesn't work.
