### ISSUE TITLE
Cannot build gl_delegate of android

### ISSUE THREAD

**Issue by stereomatchingkiss** [tensorflow/tensorflow#35408]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu18.04.3 LTS, 64bits
- TensorFlow installed from: https://github.com/tensorflow/tensorflow, 
- TensorFlow version: 8e8fabfee3
- Python version: Python 3.6.9 :: Anaconda, Inc.
- Installed using virtualenv? pip? conda?: conda
- Bazel version (if compiling from source): 1.1.0
- GCC/Compiler version (if compiling from source): Not compiled from source
- CUDA/cuDNN version: None
- GPU model and memory: None

**Describe the problem**

I can build the libtensorflow-lite.a. by 

`./tensorflow/lite/tools/make/build_aarch64_lib.sh`

But cannot build the gl_delegate by

`bazel build -c opt --config android_arm64 tensorflow/lite/delegates/gpu:gl_delegate`

**Provide the exact sequence of commands / steps that you executed before running into the problem**

1. Install tensorflow and build the libtensorflow-lite.a by the instructions from [here](https://www.tensorflow.org/lite/guide/build_arm64)
2. Install bazel by the instructions from [here](https://docs.bazel.build/versions/master/install-ubuntu.html) 
3. Install anaconda, create environment
`conta create --name tensorflow python=3.6`
4. Install tensorflow and others tools by conda
5. Build gl_delegate by `bazel build -c opt --config android_arm64 tensorflow/lite/delegates/gpu:gl_delegate`

**Any other info / logs**

> NFO: Writing tracer profile to '/home/yyyy/.cache/bazel/_bazel_yyyy/9f4180a9f81bdaca56a8020b37cc35bc/command.profile.gz'
> INFO: Options provided by the client:
>   Inherited 'common' options: --isatty=1 --terminal_columns=111
> INFO: Reading rc options for 'build' from /home/yyyy/Qt/3rdLibs/tensorflow/.bazelrc:
>   'build' options: --apple_platform_type=macos --define framework_shared_object=true --define open_source_build=true --java_toolchain=//third_party/toolchains/java:tf_java_toolchain --host_java_toolchain=//third_party/toolchains/java:tf_java_toolchain --define=use_fast_cpp_protos=true --define=allow_oversize_protos=true --spawn_strategy=standalone -c opt --announce_rc --define=grpc_no_ares=true --noincompatible_remove_legacy_whole_archive --enable_platform_specific_config --config=v2
> INFO: Found applicable config definition build:v2 in file /home/yyyy/Qt/3rdLibs/tensorflow/.bazelrc: --define=tf_api_version=2 --action_env=TF2_BEHAVIOR=1
> INFO: Found applicable config definition build:android_arm64 in file /home/yyyy/Qt/3rdLibs/tensorflow/.bazelrc: --config=android --cpu=arm64-v8a --fat_apk_cpu=arm64-v8a
> INFO: Found applicable config definition build:android in file /home/yyyy/Qt/3rdLibs/tensorflow/.bazelrc: --crosstool_top=//external:android/crosstool --host_crosstool_top=@bazel_tools//tools/cpp:toolchain
> INFO: Found applicable config definition build:linux in file /home/yyyy/Qt/3rdLibs/tensorflow/.bazelrc: --copt=-w --define=PREFIX=/usr --define=LIBDIR=$(PREFIX)/lib --define=INCLUDEDIR=$(PREFIX)/include --cxxopt=-std=c++14 --host_cxxopt=-std=c++14 --config=dynamic_kernels
> INFO: Found applicable config definition build:dynamic_kernels in file /home/yyyy/Qt/3rdLibs/tensorflow/.bazelrc: --define=dynamic_loaded_kernels=true --copt=-DAUTOLOAD_DYNAMIC_KERNELS
> DEBUG: Rule 'io_bazel_rules_docker' indicated that a canonical reproducible form can be obtained by modifying arguments shallow_since = "1556410077 -0400"
> DEBUG: Call stack for the definition of repository 'io_bazel_rules_docker' which is a git_repository (rule definition at /home/yyyy/.cache/bazel/_bazel_yyyy/9f4180a9f81bdaca56a8020b37cc35bc/external/bazel_tools/tools/build_defs/repo/git.bzl:195:18):
>  - /home/yyyy/.cache/bazel/_bazel_yyyy/9f4180a9f81bdaca56a8020b37cc35bc/external/bazel_toolchains/repositories/repositories.bzl:37:9
>  - /home/yyyy/Qt/3rdLibs/tensorflow/WORKSPACE:37:1
> ERROR: /home/yyyy/.cache/bazel/_bazel_yyyy/9f4180a9f81bdaca56a8020b37cc35bc/external/local_config_cc/BUILD:47:1: in cc_toolchain_suite rule @local_config_cc//:toolchain: cc_toolchain_suite '@local_config_cc//:toolchain' does not contain a toolchain for cpu 'arm64-v8a'
> ERROR: Analysis of target '//tensorflow/lite/delegates/gpu:libtensorflowlite_gpu_gl.so' failed; build aborted: Analysis of target '@local_config_cc//:toolchain' failed; build aborted
> INFO: Elapsed time: 0.450s
> INFO: 0 processes.
> FAILED: Build did NOT complete successfully (1 packages loaded, 1 target configured)

**Comment by freedomtan** [comment]
@stereomatchingkiss do you have Android NDK configured properly? if you are not sure, start from `./configure` again.

**Comment by jdduke** [comment]
Also, if you're building for Android, using `./tensorflow/lite/tools/make/build_aarch64_lib.sh` is probably not what you want. You should run `/.configure`' per the suggestion from @freedomtan, and then use the shared libraries for either `lite:libtensorflowlite.so` or `lite/c:libtensorflowlite_c.so`.

**Comment by stereomatchingkiss** [comment]
Thanks to both of you, I build the gl_delegate successfully.

>./tensorflow/lite/tools/make/build_aarch64_lib.sh

What should I do if this is not the right way?Or you mean I should run ./configure before I run "./tensorflow/lite/tools/make/build_aarch64_lib.sh"?

**Comment by jdduke** [comment]
> What should I do if this is not the right way?

The main question is, do you *really* need a static library (generated by the Makefile script), or can you use a shared library (built via bazel)? `./configure` is necessary for bazel builds targeting Android, but shouldn't be required when using the Makefile-based build scripot.

**Comment by stereomatchingkiss** [comment]
>The main question is, do you really need a static library (generated by the Makefile script)

No. I use the Makefile script because
the [doc](https://www.tensorflow.org/lite/guide/build_arm64) at here tell us to build the lib like that, not  a recommend way?

**Comment by jdduke** [comment]
Ah, right, that guide is generally for *non-Android* ARM64 builds, where it's more difficult to cross-compile with bazel. We're working on a revamped C++ guide, for Android, which should make it easier to get started if you prefer or need to use the C/C++ APIs on Android, rather than the existing prebuilt Java AAR libs.

**Comment by stereomatchingkiss** [comment]
> We're working on a revamped C++ guide, for Android
Thanks, how long do you think this would come out?

> if you prefer or need to use the C/C++ APIs on Android
I develop cross-platform app by Qt5, so c/c++ api are much easier to use than java api for me

**Comment by stereomatchingkiss** [comment]
> 
> 
> Ah, right, that guide is generally for _non-Android_ ARM64 builds, where it's more difficult to cross-compile with bazel. We're working on a revamped C++ guide, for Android, which should make it easier to get started if you prefer or need to use the C/C++ APIs on Android, rather than the existing prebuilt Java AAR libs.

Tried to figure out how to build by myself but it don't work so far. Almost every deep learning libraries are written by c++ but almost every deep learning treat c++ as 3rd class citizens, sigh.

**Comment by jdduke** [comment]
Expect a much more detailed and useful guide by the end of January. Thanks for your patience on this.

**Comment by sushreebarsa** [comment]
@stereomatchingkiss We see that you are using older version of tensorflow .Many bug have been fixed in latest version. We recommend that you upgrade to latest stable version of tensorflow 2.6.0 and let us know if the issue still persists in newer versions .Thanks!
