### ISSUE TITLE
vgg19.preprocess_input doesn't work in TF2.1 autograph mode

### ISSUE THREAD

**Issue by olegmyrk** [tensorflow/tensorflow#35413]
**System information**

* Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
* OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04.3 LTS
* TensorFlow installed from (source or binary): binary
* TensorFlow version (use command below): v2.1.0-rc1-58-g9837ece 2.1.0-rc2 (python3 -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)")
* Python version: Python 3.6.8
* CUDA/cuDNN version: Driver Version: 440.33.01, CUDA Version: 10.2, cuDNN 7.6.2
* GPU model and memory: Tesla V100-SXM2-16GB

**Describe the current behavior**
Running 
```
tensorflow.keras.applications.vgg19.preprocess_input
```
inside @tf.function results in exception:
```
TypeError: An op outside of the function building code is being passed
a "Graph" tensor. It is possible to have Graph tensors
leak out of the function building context by including a
tf.init_scope in your function building code.
For example, the following function will fail:
  @tf.function
  def has_init_scope():
    my_constant = tf.constant(1.)
    with tf.init_scope():
      added = my_constant * 2
The graph tensor has name: VGGLoss/Const:0
```

**Describe the expected behavior**
Should work the same as in tf1.x
https://github.com/olegmyrk/SPADE-Tensorflow/blob/develop/vgg19_keras.py#L15

**Code to reproduce the issue**
```self.vgg_loss = VGGLoss() ```
https://github.com/olegmyrk/SPADE-Tensorflow/blob/85b5fd7943296561dc3d54557fec5346c2adea58/SPADE.py#L631

```g_nondet_vgg_loss = self.vgg_loss(fake_nondet_x_output, real_x)```
https://github.com/olegmyrk/SPADE-Tensorflow/blob/85b5fd7943296561dc3d54557fec5346c2adea58/SPADE.py#L776

```g_det_vgg_loss = self.vgg_loss(real_x, fake_det_x_stats[0][0])```
https://github.com/olegmyrk/SPADE-Tensorflow/blob/85b5fd7943296561dc3d54557fec5346c2adea58/SPADE.py#L784

This is the line that fails:
```
x_vgg, y_vgg = self.vgg(preprocess_input(x)), self.vgg(preprocess_input(y))
```
https://github.com/olegmyrk/SPADE-Tensorflow/blob/85b5fd7943296561dc3d54557fec5346c2adea58/vgg19_keras.py#L15

I also tried to patch the code for preprocess_input myself
https://github.com/olegmyrk/SPADE-Tensorflow/blob/85b5fd7943296561dc3d54557fec5346c2adea58/vgg19_keras.py#L62
It somewhat works but judging by the scale of the VGG loss some input normalization is off.

**Other info / logs**
```
Traceback (most recent call last):
  File "main.py", line 134, in <module>
    main()
  File "main.py", line 121, in main
    gan.train()
  File "/app/home/ubuntu/SPADE-Tensorflow.tf2/SPADE.py", line 1180, in train
    build()
  File "/home/ubuntu/.local/lib/python3.6/site-packages/tensorflow_core/python/eager/def_function.py", line 568, in __call__
    result = self._call(*args, **kwds)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/tensorflow_core/python/eager/def_function.py", line 632, in _call
    return self._stateless_fn(*args, **kwds)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/tensorflow_core/python/eager/function.py", line 2363, in __call__
    return graph_function._filtered_call(args, kwargs)  # pylint: disable=protected-access
  File "/home/ubuntu/.local/lib/python3.6/site-packages/tensorflow_core/python/eager/function.py", line 1611, in _filtered_call
    self.captured_inputs)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/tensorflow_core/python/eager/function.py", line 1692, in _call_flat
    ctx, args, cancellation_manager=cancellation_manager))
  File "/home/ubuntu/.local/lib/python3.6/site-packages/tensorflow_core/python/eager/function.py", line 545, in call
    ctx=ctx)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/tensorflow_core/python/eager/execute.py", line 76, in quick_execute
    raise e
  File "/home/ubuntu/.local/lib/python3.6/site-packages/tensorflow_core/python/eager/execute.py", line 61, in quick_execute
    num_outputs)
TypeError: An op outside of the function building code is being passed
a "Graph" tensor. It is possible to have Graph tensors
leak out of the function building context by including a
tf.init_scope in your function building code.
For example, the following function will fail:
  @tf.function
  def has_init_scope():
    my_constant = tf.constant(1.)
    with tf.init_scope():
      added = my_constant * 2
The graph tensor has name: VGGLoss/Const:0
```

**Comment by gowthamkpr** [comment]
@olegmyrk I am using tf-nightly and I am not running into any error. Please take a look at the [gist](https://colab.sandbox.google.com/gist/gowthamkpr/7464f8e197fb9f2917f07639ce819aa8/style_transfer.ipynb). Thanks!

**Comment by olegmyrk** [comment]
Here is the smallest code that can reproduce the bug in v2.1.0-rc1-58-g9837ece 2.1.0-rc2:
```
import numpy as np 
import tensorflow as tf 
 
dataset1 = tf.data.Dataset.from_tensor_slices(([np.zeros((1,224,224,3),np.float32)]))
 
@tf.function 
def run1(x): 
  with tf.name_scope("preprocess_input"):
    return tf.keras.applications.vgg19.preprocess_input(x)
 
for x in dataset1: 
  result = run1(x) 
  print(result)

dataset2 = tf.data.Dataset.from_tensor_slices(([np.zeros((1,224,224,3),np.float32)])) 
 
@tf.function 
def run2(x): 
  return tf.keras.applications.vgg19.preprocess_input(x)
 
for x in dataset2: 
  result = run2(x) 
  print(result)
```

It is different from what my codes does but results in the same error:
```
TypeError: An op outside of the function building code is being passed
a "Graph" tensor. It is possible to have Graph tensors
leak out of the function building context by including a
tf.init_scope in your function building code.
For example, the following function will fail:
  @tf.function
  def has_init_scope():
    my_constant = tf.constant(1.)
    with tf.init_scope():
      added = my_constant * 2
The graph tensor has name: preprocess_input/Const:0
```

**Comment by gowthamkpr** [comment]
I am not running into any error using tf-nightly. Please find my gist [here](https://colab.sandbox.google.com/gist/gowthamkpr/315b4908917a55858f0f0ef03f219bbf/untitled270.ipynb).

**Comment by olegmyrk** [comment]
Fails in TF 2.1.0:
https://colab.research.google.com/gist/olegmyrk/7b3254a35f0a104fe83f1f60bf693ac0/untitled0.ipynb

**Comment by gowthamkpr** [comment]
@olegmyrk I agree its failing in TF 2.1.0 but it has been fixed in the nightly version. Please find my gist [here](https://colab.sandbox.google.com/gist/gowthamkpr/d3ec266927b357929cc2d2dc88e322a8/copy-of-untitled0.ipynb). It bug fix will be shown in the next stable version. Thanks!
