### ISSUE TITLE
x/Unknown while training the first epoch.

### ISSUE THREAD

**Issue by msteknoadam** [tensorflow/tensorflow#35422]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No.
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Code is ran on Google Colab (However, my machine is Windows 10 Version 1903 if that matters)
- TensorFlow installed from (source or binary): No knowledge, using the already installed version on Google Colab
- TensorFlow version (use command below): v2.1.0-rc1-0-g064e1535a7 2.1.0-rc1
- Python version: 3.6.9
- GCC/Compiler version (if compiling from source): 8.3.0
- GPU model and memory: No knowledge, using the given Google Colab hardware.

**Describe the current behavior**
When fitting the model, on the first epoch, it counts steps like "337/Unknown", the Unknown stays there until the first epoch fitting is over(at step 582) but that issue gets fixed after the first epoch is over. The text turns to "582/582" and it shows like "x/582" on the next epochs.

**Describe the expected behavior**
It should say like "x/582" at the first epoch too.

**Code to reproduce the issue**
https://colab.research.google.com/github/tensorflow/docs/blob/master/site/en/tutorials/images/transfer_learning.ipynb
Try doing the "Train the model" part. You should encounter this problem when you start fitting the model.

**Comment by oanush** [comment]
@msteknoadam ,
Issue seems to be fixed in the latest `tf-nightly 2.1.0.dev20191226`,can you try using that version?Thanks!

**Comment by msteknoadam** [comment]
Uhm, sorry but no, it's still the same. I made sure that I was on version 2.1.0-dev20191226 and it still shows like "x/Unknown"

**Comment by jvishnuvardhan** [comment]
@msteknoadam Actually, an iterator generates data dynamically. So the length of a dataset iterator is unknown untill you iterate through it. [This resource](https://stackoverflow.com/questions/52264469/determine-number-of-records-in-tf-data-dataset-tensorflow) has more detailed explanation for your question.

You could pass `steps_per_epoch` argument to the `model.fit` as shown below. Then, it prints as you are expecting. 
```
 history = model.fit(train_batches,
                    epochs=initial_epochs,steps_per_epoch=steps_per_epoch,
                    validation_data=validation_batches)
```

I am closing this issue as it was resolved. Please feel free to open new issue if you encounter any related issues. Thanks!

**Comment by aldnoahh** [comment]
I had the same problem. My guess is this is due to the fact the code was previous version (before 2.x).
Solution: In the fit function, specify batch_size and steps_per_epoch, and it shall work beautifully. At least, worked for me.
