### ISSUE TITLE
Add wheel for python3.8 on pypi

### ISSUE THREAD

**Issue by stevenleeS0ht** [tensorflow/tensorflow#35438]
Currently, there is no wheel on pypi for python 3.8

I strongly hope that there will be support for latest python version.

**Comment by oanush** [comment]
@stevenleeS0ht ,
Hello, We can expect python 3.8 support with TF 2.2.
Please check  [#33374 ](https://github.com/tensorflow/tensorflow/issues/33374#issuecomment-562663993)Thanks!

**Comment by mihaimaruseac** [comment]
Closing as duplicate of #33374
