### ISSUE TITLE
boolean_mask failed in iOS: Running model failed:Invalid argument: No OpKernel was registered to support Op 'Gather' with these attrs

### ISSUE THREAD

**Issue by yjmade** [tensorflow/tensorflow#3543]
### Environment info

Operating System:
Building on Mac OS X
Running on iOS 9.2.1
1. The commit hash (`git rev-parse HEAD`)
   71f6bb336e5e11d6da2cedac6ba1c992ad9992bd
2. The output of `bazel version`

```
Build target: bazel-out/local-fastbuild/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Tue Jul 12 11:11:47 2016 (1468321907)
Build timestamp: 1468321907
Build timestamp as int: 1468321907
```
### Steps to reproduce
1. I compile tf for iOS with the makefile
2. I frozen a model with last step as  a boolean_mask (that prozen pb file runs perfectly with TF 0.9.0 python api )
3. I run it in iOS, log report 

```
Running model failed:Invalid argument: No OpKernel was registered to support Op 'Gather' with these attrs
     [[Node: classes_num_filtered/Gather = Gather[Tindices=DT_INT64, Tparams=DT_INT64, validate_indices=true](classes_num_filtered/Reshape, classes_num_filtered/Squeeze)]]
```

so it happens with the gather op inside the boolean_mask, when I removed this operation, it runs without problem in iOS.
Is that means gather op is not currently support in iOS? 
Do I have a work around for now? I need to filter the data with porbs > threhold.

``` python
        mask = self.classes_prob > self.threshold
        self.classes_prob_filtered = tf.boolean_mask(self.classes_prob, mask, name="probs_filtered") 
        self.classes_arg_filtered = tf.boolean_mask(self.classes_arg, mask, name="classes_num_filtered") 
        self.boxes_filtered = tf.boolean_mask(self.boxes, mask, name="boxes_filtered") 
```

I checked the  tf_cc_files.txt, tensorflow/core/kernels/gather_op.cc do exist.

**Comment by yjmade** [comment]
I update to last reversion 98d63de3bb2bab7c9a81f83c8ca864741399300c and recompiled everything, problem still exist

**Comment by michaelisard** [comment]
@petewarden could you take a look?

**Comment by petewarden** [comment]
Sorry for the long delay on this one. We only support a limited number of ops by default on iOS, to keep the binary size small, but you can add your own to the list by including them locally in this file:
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/makefile/tf_op_files.txt

In this case you'll want to add `tensorflow/core/kernels/gather_op.cc`. Can you let me know if that helps?

**Comment by drpngx** [comment]
@petewarden 's solution should work. Feel free to open a new issue if the problem persists.
