### ISSUE TITLE
could not find 'TrtGraphConverter

### ISSUE THREAD

**Issue by MrCrazyCrab** [tensorflow/tensorflow#35440]
i want to create a TensorRT inference graph directly from my SavedModel. However i met a problem
"from tensorflow.python.compiler.tensorrt import trt_convert as trt
ModuleNotFoundError: No module named 'tensorflow.python.compiler"
when i change it into "from tensorflow.contrib.tensorrt.python import trt_convert as trt" i met another problem that "AttributeError: module 'tensorflow.contrib.tensorrt.python.trt_convert' has no attribute 'TrtGraphConverter'"
my tensorflow is 1.13.1

**Comment by ravikyram** [comment]
@MrCrazyCrab 

I tried in colab with TF 1.13.1 with `from tensorflow.contrib.tensorrt.python import trt_convert as trt`and i am not seeing any issue. Please, find the gist [here](https://colab.sandbox.google.com/gist/ravikyram/729d680a9bdc44c92fb2edf62a72605f/untitled509.ipynb). Thanks!

**Comment by jnd77** [comment]
@MrCrazyCrab If am not mistaken , TrtGraphConverter did not exist yet in TF 1.13. You would need to update TF to 1.15 or 2.0 I think.
With TF 1.13, you can use the "old" way (which is no longer documented on Nvidia website):
   ```
from tensorflow.contrib import tensorrt as trt
trt_graph = trt.create_inference_graph(...)
```

create_inference_graph has options very similar to TrtGraphConverter

**Comment by MrCrazyCrab** [comment]
@jnd77 thank you, i would try later.

**Comment by ymodak** [comment]
You need to install tensorflow-gpu version. Can you confirm this?
Also startting TF 1.14, TF-TRT was moved to core from contrib module.
So in your case you should try;
`from tensorflow.contrib.tensorrt.python import trt_convert as trt`

**Comment by ravikyram** [comment]
@MrCrazyCrab 

Any update on this issue please. Thanks!

**Comment by ravikyram** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Comment by saikrishnadas** [comment]
I still get the same  **TrtGraphConverter** issue
Tensorflow version 2.0 GPU supported 
and changed `from tensorflow.contrib.tensorrt.python import trt_convert as trt` to `from tensorflow.python.compiler.tensorrt import trt_convert as trt

Can anyone help me with this ?
 `

**Comment by MrCrazyCrab** [comment]
@saikrishnadas try it on ubuntu not windows!

**Comment by saikrishnadas** [comment]
@MrCrazyCrab I use Ubuntu 18.04

**Comment by MrCrazyCrab** [comment]
@saikrishnadas uh... maybe you should see if there is a file "trt_convert.py" in the /compile/tensorrt/. If not, you should consider whethere  to reinstall the tensorflow.

**Comment by saikrishnadas** [comment]
@MrCrazyCrab Yep ! I just re-installed tensorflow and that worked. But is it still .pb format after it convert it to tensorRT with savedmodel ? I recently converted my yolo.weight model to onnx and to tensorrt which gave a extension of .trt .

**Comment by MrCrazyCrab** [comment]
@saikrishnadas  yeah, and there is more files after converting.

**Comment by saikrishnadas** [comment]
@MrCrazyCrab Thanks Man
