### ISSUE TITLE
Chain multiple estimators to create a single SavedModel 

### ISSUE THREAD

**Issue by tejaslodaya** [tensorflow/tensorflow#35447]
Chain multiple estimators to create a single SavedModel with a single serving file/output.

Suppose I have 3 estimators with me, first is BoostedTrees, who's output I want to use as input into DNNClassifier, and the output of which I want to use in my custom Estimator.

Is there a way to chain output/input of each other to create a **mega** estimator of sorts.

Please help me out here.

**Comment by tejaslodaya** [comment]
@gadagashwini @ymodak @omalleyt12 👆

**Comment by tejaslodaya** [comment]
Hi @ravikyram @ymodak ,

Any update on the above would be appreciated.

**Comment by tejaslodaya** [comment]
Hi @ymodak @ravikyram @gadagashwini 

Any update on the above?

**Comment by ymodak** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.
Thanks!
