### ISSUE TITLE
HashTableV2, LookupTableFindV2 are not supported

### ISSUE THREAD

**Issue by wenyun** [tensorflow/tensorflow#35454]
**System information**
- Linux CentOs 7
- TensorFlow installed from pip:
- TensorFlow version 1.15.0:

**Provide the text output from tflite_convert**

```
Some of the operators in the model are not supported by the standard TensorFlow Lite runtime and are not recognized by TensorFlow. If you have a custom implementation for them you can disable this error with --allow_custom_ops, or by setting allow_custom_ops=True when calling tf.lite.TFLiteConverter(). Here is a list of builtin operators you are using: CONCATENATION, FULLY_CONNECTED, LOGISTIC, MUL, ONE_HOT, PACK, RESHAPE, SHAPE, SPARSE_TO_DENSE, STRIDED_SLICE, SUB, SUM. Here is a list of operators for which you will need custom implementations: HashTableV2, LookupTableFindV2.```


**Any other info / logs**

looks like the above two operators are not supported. We are using Estimator APIs and I think the above ops are used in categorical_column where we need to lookup the feature from a vocabulary list.

**Comment by oanush** [comment]
@wenyun ,
Hello, as per the [official documentation](https://www.tensorflow.org/lite/guide/ops_compatibility#unsupported_operations) TensorFlow Lite operations HashTableV2, LookupTableFindV2  are present but not ready for custom models yet.

**Comment by oanush** [comment]
@wenyun,
Any update on the issue ?Thanks!

**Comment by oanush** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
