### ISSUE TITLE
EMNIST Link Broken 

### ISSUE THREAD

**Issue by AND2797** [tensorflow/tensorflow#35459]
The link to the [EMNIST page](https://www.tensorflow.org/datasets/catalog/emnist) on Tensorflow's docs is broken.

The existing link is -
https://www.nist.gov/node/1298471/emnist-dataset

It should be replaced by -
http://www.itl.nist.gov/iaui/vip/cs_links/EMNIST/gzip.zip

**Comment by monsij** [comment]
Interested to fix this @AND2797 . Do all the mentions of the link are required to be changed to [http://www.itl.nist.gov/iaui/vip/cs_links/EMNIST/gzip.zip](http://www.itl.nist.gov/iaui/vip/cs_links/EMNIST/gzip.zip) as some refer to the homepage rather than the dataset itself. Can [https://www.nist.gov/itl/products-and-services/emnist-dataset](https://www.nist.gov/itl/products-and-services/emnist-dataset) be used except for the first occurrence?

**Comment by AND2797** [comment]
Actually, good point. I assumed that the link led to the download of the actual dataset. Now since the link is broken I am not sure if it led to the download of the actual data set or the home page of the dataset. 

Perhaps one could add both, or either one.

**Comment by monsij** [comment]
Additionally, I don't think this page of documentation is based on any file in this repository. Any opinions on this @AND2797 ?

**Comment by AND2797** [comment]
> Additionally, I don't think this page of documentation is based on any file in this repository. Any opinions on this @AND2797 ?

do you mean based on any module source code?

**Comment by monsij** [comment]
Yes. The source code behind that page of documentation at [EMNIST PAGE](https://www.tensorflow.org/datasets/catalog/emnist).

**Comment by AND2797** [comment]
I am not sure if the page is there in the documentation or not... will have to check.

**Comment by gadagashwini** [comment]
@AND2797, Can you add PR link here. Thanks!

**Comment by AND2797** [comment]
> @AND2797, Can you add PR link here. Thanks!

Do you mean this -> https://github.com/AND2797/datasets/pull/1

**Comment by gadagashwini** [comment]
@AND2797, Can you submit this PR against Tensorflow?

**Comment by AND2797** [comment]
Could you provide instructions as to how I can do this?

**Comment by AND2797** [comment]
> @AND2797, Can you submit this PR against Tensorflow?

Yes, I've done it  now. 
https://github.com/tensorflow/datasets/pull/1322
This is the link.

**Comment by AND2797** [comment]
I've submitted the PR against tensorflow, can anyone take a look?

**Comment by ymodak** [comment]
@rsepassi  Can PTAL? Thanks!

**Comment by rsepassi** [comment]
Fix will go out shortly. Thank you!
