### ISSUE TITLE
which is the correct type for debugging.assert_shape?

### ISSUE THREAD

**Issue by MokkeMeguru** [tensorflow/tensorflow#35452]
## URL(s) with the issue:

https://www.tensorflow.org/api_docs/python/tf/debugging/assert_shapes?version=stable

## Description of issue (what needs changing):

Update Documentation or implementation of `tf.debugging.assert_shapes`.     
`Shapes` in its argument requires LIST OF TUPLE, not DICTIONARIES.

### Clear description

Your Documentation (Python 4's syntax?)
```python
x = tf.random.normal([128, 32, 32, 1])
tf.debugging.assert_shapes(
    [(x: (128, 32, 32, 1))]
)
# => 
#     [(x: (128, 32, 32, 1))]
#       ^
# SyntaxError: invalid syntax
```

With dictionary (Python 3's syntax)
```python
tf.debugging.assert_shapes(
    {x: (128, 32, 32, 1)}
)
# =>
# ... ... Traceback (most recent call last):
#   File "<stdin>", line 2, in <module>
#  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/ops.py", line 713, in __hash__
#     raise TypeError("Tensor is unhashable if Tensor equality is enabled. "
# TypeError: Tensor is unhashable if Tensor equality is enabled. Instead, use tensor.experimental_ref() as the key.
```
With list of tuple (python 3's syntax)(NOT DICTIONARIES)
```python
tf.debugging.assert_shapes([
    (x, (128, 32, 32, 1))
]
)
# => nothing (correct)
```

**Comment by ravikyram** [comment]
I have tried on colab with TF version 1.15 and i am not seeing any issue with dictionary  and with list of tuple (python 3's syntax) . I have tried in colab with TF 2.0 and i am able to reproduce the issue.Please, find the gist [here.](https://colab.sandbox.google.com/gist/ravikyram/d75c8e3a0d3121bace78789f88b03b6a/untitled512.ipynb) Thanks!

**Comment by MokkeMeguru** [comment]
OK, I found we can use LIST OF TUPLE and also can use DICTIONARY at tf_1.15 (but its document is for tf_2.0 ...).
It's the problem of the document's syntax error.
Thanks!
