### ISSUE TITLE
tf.print can't print chinese characters

### ISSUE THREAD

**Issue by DachuanZhao** [tensorflow/tensorflow#35456]
**System information**

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): 
win10 1909
- TensorFlow installed from (source or binary):
pip install tensorflow
- TensorFlow version (use command below):
2.0.0
- Python version:
3.7.4

**Describe the current behavior**
```
import tensorflow as tf 
tf.print("中文测试")
tf.print("Chinese test")
print("中文测试")
print("Chinese test")
```
current output is
涓枃娴嬭瘯
Chinese test
中文测试
Chinese test

expected output is
中文测试
Chinese test
中文测试
Chinese test

**Comment by ravikyram** [comment]
I have tried on colab with TF version 2.0 , TF Nightly version 2.1.0-dev20191229 and i am not seeing any issue. Please, find the gist [here.](https://colab.sandbox.google.com/gist/ravikyram/87a35d7a47720f1293a16a80c421917e/untitled511.ipynb) Thanks!

**Comment by DachuanZhao** [comment]
> I have tried on colab with TF version 2.0 , TF Nightly version 2.1.0-dev20191229 and i am not seeing any issue. Please, find the gist [here.](https://colab.sandbox.google.com/gist/ravikyram/87a35d7a47720f1293a16a80c421917e/untitled511.ipynb) Thanks!

Hi , @ravikyram . When I run the code on linux by using ```python test.py``` or in jupyter (no matter on linux or windows) , It works well. But when I run it in powershell or cmd , it's strange that only ```tf.print``` can't output correctly . When I change windows global character encoding from ``GBK``` to ```utf8``` , both of them works well ......

**Comment by ravikyram** [comment]
@DachuanZhao 

Can we close this issue since the query is been resolved? Thanks!
