### ISSUE TITLE
integrate.odeint in tensorflow 2.0

### ISSUE THREAD

**Issue by Tonytony123474** [tensorflow/tensorflow#35460]
Can't find odeint or integrate...
can't import contrib from tf.compat.v1 
where is odeint

**Comment by gadagashwini** [comment]
@Tonytony123474,
`integrate.odeint` is moved to Tensorflow/scientific in Tf 2.0. 
Try, `pip install tensorflow-scientific`
`tfs.integrate.odeint`
Thanks!

**Comment by gadagashwini** [comment]
@Tonytony123474, Closing since its resolved. Please feel free to comment or reopen if its still an issue. Thanks!
