### ISSUE TITLE
Sample VAE code throws error: "ValueError: The last dimension of the inputs to Dense should be defined. Found None"

### ISSUE THREAD

**Issue by ZoltanRado** [tensorflow/tensorflow#35464]
I am very new to TF2 and tried to customize the example code on the tensorflow guide documentation:

https://www.tensorflow.org/guide/keras/custom_layers_and_models#putting_it_all_together_an_end-to-end_example

The code given in the guide does not run if the latent dimension is set 1, it runs fine for every latent dimension >1!

For training I tried to use the code given in the example but set the latent dim to 1:
```
vae = VariationalAutoEncoder(784, 64, 1)

optimizer = tf.keras.optimizers.Adam(learning_rate=1e-3)

vae.compile(optimizer, loss=tf.keras.losses.MeanSquaredError())
vae.fit(x_train, x_train, epochs=3, batch_size=64)
```

The error when trying to train is:

**ValueError: The last dimension of the inputs to Dense should be defined. Found None** and is thrown upon return from the Sample function where I think:
```
epsilon = tf.keras.backend.random_normal(shape=(batch, dim))
```
can not handle shape=(?,1).

Can someone help I am trying to use the code as a template but I need latent dimension to be 1!

Thanks

**Comment by vishwas1234567** [comment]
tf.keras and just keras has the different performance instances thus making that the tf being compatible for all the version is a different deal and thus we have to have a version that satisfies just read the documentation and study you will get it done.

**Comment by oanush** [comment]
@ZoltanRado ,
For the tutorial mentioned I was able to run the code `latent_dim=1 `without any error, can you please provide link gist of colab used ?Thanks!

**Comment by ZoltanRado** [comment]
Here is a gist produced by [ravikyram](https://github.com/ravikyram) on colab with TF version 2.0 and was able to reproduce the issue.Please, find the [gist](https://colab.sandbox.google.com/gist/ravikyram/421ce6dadb234bbe06a11cbec1f6f94a/untitled518.ipynb) here.

I am working on TF2.0.0 with Anaconda on my machine.

Thanks

**Comment by ZoltanRado** [comment]
Here is a gist produced by [ravikyram](https://github.com/ravikyram) on colab with TF version 2.0 and was able to reproduce the issue. Please, find the [gist](https://colab.sandbox.google.com/gist/ravikyram/421ce6dadb234bbe06a11cbec1f6f94a/untitled518.ipynb) here.

I am working on TF2.0.0 with Anaconda on my machine.

Thanks

**Comment by ZoltanRado** [comment]
Here is the code:
```
class Sampling(layers.Layer):
  """Uses (z_mean, z_log_var) to sample z, the vector encoding a digit."""

  def call(self, inputs):
    z_mean, z_log_var = inputs
    batch = tf.shape(z_mean)[0]
    dim = tf.shape(z_mean)[1]
    epsilon = tf.keras.backend.random_normal(shape=(batch, dim))
    return z_mean + tf.exp(0.5 * z_log_var) * epsilon


class Encoder(layers.Layer):
  """Maps MNIST digits to a triplet (z_mean, z_log_var, z)."""

  def __init__(self,
               latent_dim=32,
               intermediate_dim=64,
               name='encoder',
               **kwargs):
    super(Encoder, self).__init__(name=name, **kwargs)
    self.dense_proj = layers.Dense(intermediate_dim, activation='relu')
    self.dense_mean = layers.Dense(latent_dim)
    self.dense_log_var = layers.Dense(latent_dim)
    self.sampling = Sampling()

  def call(self, inputs):
    x = self.dense_proj(inputs)
    z_mean = self.dense_mean(x)
    z_log_var = self.dense_log_var(x)
    z = self.sampling((z_mean, z_log_var))
    return z_mean, z_log_var, z


class Decoder(layers.Layer):
  """Converts z, the encoded digit vector, back into a readable digit."""

  def __init__(self,
               original_dim,
               intermediate_dim=64,
               name='decoder',
               **kwargs):
    super(Decoder, self).__init__(name=name, **kwargs)
    self.dense_proj = layers.Dense(intermediate_dim, activation='relu')
    self.dense_output = layers.Dense(original_dim, activation='sigmoid')

  def call(self, inputs):
    x = self.dense_proj(inputs)
    return self.dense_output(x)


class VariationalAutoEncoder(tf.keras.Model):
  """Combines the encoder and decoder into an end-to-end model for training."""

  def __init__(self,
               original_dim,
               intermediate_dim=64,
               latent_dim=32,
               name='autoencoder',
               **kwargs):
    super(VariationalAutoEncoder, self).__init__(name=name, **kwargs)
    self.original_dim = original_dim
    self.encoder = Encoder(latent_dim=latent_dim,
                           intermediate_dim=intermediate_dim)
    self.decoder = Decoder(original_dim, intermediate_dim=intermediate_dim)

  def call(self, inputs):
    z_mean, z_log_var, z = self.encoder(inputs)
    reconstructed = self.decoder(z)
    # Add KL divergence regularization loss.
    kl_loss = - 0.5 * tf.reduce_mean(
        z_log_var - tf.square(z_mean) - tf.exp(z_log_var) + 1)
    self.add_loss(kl_loss)
    return reconstructed



vae = VariationalAutoEncoder(784, 64, 1)

optimizer = tf.keras.optimizers.Adam(learning_rate=1e-3)

vae.compile(optimizer, loss=tf.keras.losses.MeanSquaredError())
vae.fit(x_train, x_train, epochs=3, batch_size=64)
```

**Comment by ZoltanRado** [comment]
I have produced it too (my first gist :-) ) [here](https://colab.research.google.com/gist/ZoltanRado/a599188734f3cebacbdc0bfc53e62c50/untitled0.ipynb)

**Comment by 8bitmp3** [comment]
Hey @ZoltanRado I am not an auto-encoder specialist, but I've also managed to reproduce a similar error in Colab with GPU acceleration enabled just now. Looping in @lamberta @MarkDaoust @yashk2810, just in case. 

To save time, the Colab notebook is [here](https://colab.research.google.com/github/tensorflow/docs/blob/master/site/en/guide/keras/custom_layers_and_models.ipynb#scrollTo=oDVSVl4Iu8kC) and the official guide is [here](https://www.tensorflow.org/guide/keras/custom_layers_and_models#putting_it_all_together_an_end-to-end_example).

_1) Successful run over 3 epochs, as designed:_

First, import the libraries and run the cell straight after ["Putting it all together: an end-to-end example"]((https://www.tensorflow.org/guide/keras/custom_layers_and_models#putting_it_all_together_an_end-to-end_example) ) in the "Customer Layers and Models" Keras Guide:
```
class Sampling(layers.Layer):
...
class Encoder(layers.Layer):
...
class Decoder(layers.Layer):
...
class VariationalAutoEncoder(tf.keras.Model):
...
```
and change the latent dimension argument to 1 from the default value of 32 in the next cell, such that:

```python
original_dim = 784
vae = VariationalAutoEncoder(original_dim, 64, 1) # replaced 32 with 1 here
...
...
# Iterate over epochs.
for epoch in range(epochs):
...
```
If you run it, you hopefully shouldn't see any errors during training:
```
Downloading data from ...
...
Start of epoch 0
step 0: mean loss = tf.Tensor(0.34020466, shape=(), dtype=float32)
...
Start of epoch 2
...
step 900: mean loss = tf.Tensor(0.072112255, shape=(), dtype=float32)
```

For the reference:
```python
class VariationalAutoEncoder(tf.keras.Model):
...
  def __init__(self,
               original_dim,
               intermediate_dim=64,
               latent_dim=32,
               name='autoencoder',
               **kwargs):
```

_2) Where the error message appears_

Following (1) above, as soon as you run the next cell after:
```markdown
Note that since the VAE is subclassing `Model`, it features built-in training loops. So you could also have trained it like this:
```
which is:
```python
vae = VariationalAutoEncoder(784, 64, 1)

optimizer = tf.keras.optimizers.Adam(learning_rate=1e-3)

vae.compile(optimizer, loss=tf.keras.losses.MeanSquaredError())
vae.fit(x_train, x_train, epochs=3, batch_size=64)
```
you get:
```
ValueError: The last dimension of the inputs to `Dense` should be defined. Found `None`
```

It works if you change the `latent_dim` arg value from 1 to, say, 32 (the default value).

**Comment by ZoltanRado** [comment]
Yes @8bitmp3 you are correct, I am very new to TF2 but I think there is a bug in "tf.keras.backend.random_normal(shape=(batch, dim))"  where it can  not handle correctly shape=(None,1).

**Comment by vishwas1234567** [comment]
I think the way you have defined is best understood when you explain the
data that you have.

**Comment by ZoltanRado** [comment]
Hi @vishwas1234567 i don't fully understand you, the data used is the keras example is the MNIST digits data and is downloaded by the sample code.  That is the data that is used to produce the error.  I have coded different simple encoders with KL divergence and tried to use the same Gaussian-normal error sampling given in the sample
```
class Sampling(layers.Layer):
```
and got the same error without exception when setting latent dimension to 1!
for some reason the code in the class:
```
return z_mean + tf.exp(0.5 * z_log_var) * epsilon
```
returns a shape=(None,None) when latent dimension is set to 1 while if latent_dim=X (where X>1) it returns shape=(None,X) as one would expect.  I tried to trouble shoot it but I am new so was not very successful but it seem to me that **epsilon** ergo **tf.keras.backend.random_normal(shape=(batch, dim))** is the culprit.

**Comment by MarkDaoust** [comment]
Hi.

The easiest way to debug this is to just add a bunch of print statements, and inspect the shapes.

The problem here is the interaction of broadcasting wth the `z_mean + tf.exp(0.5 * z_log_var) * epsilon` line.

Normally  the last dimension of  z_mean, and z_log_var are known but the last dimension of epsilon is not.

Since you mul and add epsilon it assumes the two have the same shape.

When they have a last dimension of 1, It thinks you might be boradcasting z_mean and z_log_var with epsilon, it can't tell.

So the fix is to tell it that you know the shape of epsilon, and are not broadcastng. Add the following before that line: `epsilon.set_shape(z_mean.shape)`.

If you think this edge-case is important, send a PR to update https://github.com/tensorflow/docs/blob/master/site/en/guide/keras/custom_layers_and_models.ipynb.

**Comment by MarkDaoust** [comment]
Also not for the future that this would be better as a stack-overflow question instead of a github bug.

Have a nice day.

**Comment by ZoltanRado** [comment]
Thank you so much @MarkDaoust I appreciate your help.
I read up on broadcasting and it seem it works in TF the same way as in numpy.
Although I think this is important ( I am using my custom models for parameter estimation with exclusively one dimensional latent layers) as I am very new I am not going to send a PR.

I did post it at stack-overflow first for a couple of weeks but got no help!

Thanks again for the help.
