### ISSUE TITLE
tensorflow installation in raspberry pi : HadoopFileSystem load error

### ISSUE THREAD

**Issue by prudhvirajboddu** [tensorflow/tensorflow#35462]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Raspberry pi 4
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: No
- TensorFlow installed from (source or binary): binary in pip
- TensorFlow version: 1.14
- Python version: 3.7
- Installed using  pip
- Bazel version (if compiling from source): No
- GCC/Compiler version (if compiling from source): No
- CUDA/cuDNN version: No
- GPU model and memory: No

**Describe the problem**
****
pi@raspberrypi:~/examples/lite/examples/object_detection/raspberry_pi $ python3 detect_picamera.py   --model /tmp/detect.tflite   --labels /tmp/coco_labels.txt
2019-12-28 17:43:12.464130: E tensorflow/core/platform/hadoop/hadoop_file_system.cc:132] HadoopFileSystem load error: libhdfs.so: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "detect_picamera.py", line 34, in <module>
    from tf.lite.interpreter import Interpreter
ModuleNotFoundError: No module named 'tf'
***

**Provide the exact sequence of commands / steps that you executed before running into the problem**
***
 Tensorflow model running issue replaced the code with in original source code

> from_ tflite_runtime.interpreter import Interpreter

***
**WIth**
***
> from tf.lite import Interpreter
***

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by rafalfirlejczyk** [comment]
I got today the same issue when trying to run the fresh installed tensorflow on my raspberry pi 3+

**Comment by prudhvirajboddu** [comment]
> I got today the same issue when trying to run the fresh installed tensorflow on my raspberry pi 3+

You got any solution for that ?

**Comment by ArcherWoo** [comment]
I got same issue with my raspi 4B, but I don't think it's a fatal issue since I still can run tf.constant. However, it is still weird.....

**Comment by rafalfirlejczyk** [comment]
> > I got today the same issue when trying to run the fresh installed tensorflow on my raspberry pi 3+
> 
> You got any solution for that ?

No

**Comment by prudhvirajboddu** [comment]
> I got today the same issue when trying to run the fresh installed tensorflow on my raspberry pi 3+

What are you trying to run ? If it's any tensorflow package  then use from 
`tensorflow.*`

> The core tensorflow package With version 1.14x 
**I got answer when I run this in object detection**

**Comment by connor-makowski** [comment]
Experiencing this problem currently. Based on comments, it looks like this issue should not be closed anyway.

**Comment by LuisCampos1234** [comment]
yeah issue still present, same version of software as original filing  

2020-02-12 14:41:15.443282: E tensorflow/core/platform/hadoop/hadoop_file_system.cc:132] HadoopFileSystem load error: libhdfs.so: cannot open shared object file: No such file or directory

**Comment by prudhvirajboddu** [comment]
> yeah issue still present, same version of software as original filing
> 
> 2020-02-12 14:41:15.443282: E tensorflow/core/platform/hadoop/hadoop_file_system.cc:132] HadoopFileSystem load error: libhdfs.so: cannot open shared object file: No such file or directory

It is but the running of lite models in PI doesn't effect by this So. I closed the issue

**Comment by Rewove** [comment]
You can still use TF as usual while you got this prompt out.

**Comment by yoyojacky** [comment]
sudo apt-get install -y libhdf5-dev libc-ares-dev libeigen3-dev
python3 -m pip install keras_applications==1.0.8 --no-deps
python3 -m pip install keras_preprocessing==1.1.0 --no-deps
python3 -m pip install h5py==2.9.0
sudo apt-get install -y openmpi-bin libopenmpi-dev
sudo apt-get install -y libatlas-base-dev
python3 -m pip install -U six wheel mock

**Comment by MysteryCoder456** [comment]
> sudo apt-get install -y libhdf5-dev libc-ares-dev libeigen3-dev
> python3 -m pip install keras_applications==1.0.8 --no-deps
> python3 -m pip install keras_preprocessing==1.1.0 --no-deps
> python3 -m pip install h5py==2.9.0
> sudo apt-get install -y openmpi-bin libopenmpi-dev
> sudo apt-get install -y libatlas-base-dev
> python3 -m pip install -U six wheel mock

Does this fix the issue?

**Comment by Lizard00** [comment]
I still get this error: 

```
Traceback (most recent call last):
  File "Object_detection_picamera.py", line 27, in <module>
    import tensorflow as tf
ModuleNotFoundError: No module named 'tensorflow'
```

**Comment by chenxingqiang** [comment]
IF You still use TensorFlow 1.15.0  with HDFS data, you could do as below:
1. Download the version of hadoop your system has been used, unzip it into "/usr/local/hadoop/",then leave it;
2. export those env variables:
    on my cluster:
like this:
export JAVA_HOME=/usr/java/jdk1.8.0_181-cloudera
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/cuda-10.2/extras/CUPTI/lib64
export HADOOP_HDFS_HOME=/usr/local/hadoop/hadoop-2.7.7
source ${HADOOP_HDFS_HOME}/libexec/hadoop-config.sh
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:${JAVA_HOME}/jre/lib/amd64/server
export CLASSPATH=$(${HADOOP_HDFS_HOME}/bin/hadoop classpath --glob)
