### ISSUE TITLE
SequenceEnqueuer doesn't work

### ISSUE THREAD

**Issue by AakashKumarNain** [tensorflow/tensorflow#35477]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): 16.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.0
- Python version: 3.7
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Describe the current behavior**
`SequenceEnqueuer` object takes a `Sequence` object which then can be used with multi-processing for fast data pipeline. But as soon as you start an `enqueuer`, it throws `NotImplemented` error.

**Describe the expected behavior**
It should produce batches of data using multiprocessing.

**Code to reproduce the issue**
```python
!pip install tensorflow

import numpy as np
import tensorflow as tf
from tensorflow.keras.utils import Sequence, to_categorical, SequenceEnqueuer

class DataGenerator(Sequence):
    def __init__(self, batch_size=32):
        self.batch_size = batch_size
        self.indices = np.arange(1024)

    def __len__(self):
        return 1024
    
    def __getitem__(self, idx):
        x = np.random.rand(self.batch_size, 32, 32, 3).astype(np.float32)
        y = np.random.randint(10, size=(self.batch_size))
        return x, y

ds = DataGenerator(batch_size=32)
enqueuer = SequenceEnqueuer(ds, use_multiprocessing=True)
enqueuer.start(workers=2)
```

**Other info / logs**
```
---------------------------------------------------------------------------

NotImplementedError                       Traceback (most recent call last)

<ipython-input-13-fd99ac8a9d30> in <module>()
      1 enqueuer = SequenceEnqueuer(ds, use_multiprocessing=True)
----> 2 enqueuer.start(workers=2)

1 frames

/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/utils/data_utils.py in start(self, workers, max_queue_size)
    727     """
    728     if self.use_multiprocessing:
--> 729       self.executor_fn = self._get_executor_init(workers)
    730     else:
    731       # We do not need the init since it's threads.

/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/utils/data_utils.py in _get_executor_init(self, workers)
    778         Function, a Function to initialize the pool
    779     """
--> 780     raise NotImplementedError
    781 
    782   @abstractmethod

NotImplementedError: 
```

**Comment by AakashKumarNain** [comment]
cc: @fchollet

**Comment by ravikyram** [comment]
I have tried on colab with TF version 2.0, 2.1.0-dev20191229 and was able to reproduce the issue.Please, find the gist [here](https://colab.sandbox.google.com/gist/ravikyram/8ab18eb35dc9b0ff7d16572f966267dd/untitled513.ipynb). Thanks!

**Comment by karmel** [comment]
Sequence is an abstract class that is intended to be subclassed, as seen here: https://www.tensorflow.org/api_docs/python/tf/keras/utils/Sequence?version=stable#examples_2

**Comment by AakashKumarNain** [comment]
@karmel I think you are mixing `Sequence` with `SequenceEnqueuer`. The later should take an instance of `Sequence` and should generate batches of data.

**Comment by vkumar1997** [comment]
@AakashKumarNain Did you find a solution for this?

**Comment by ssarkar2** [comment]
@AakashKumarNain @vkumar1997  SequenceEnqueuer seems to be an abstract class with non implemented functions. you can try [OrderedEnqueuer ](https://www.tensorflow.org/api_docs/python/tf/keras/utils/OrderedEnqueuer)
