### ISSUE TITLE
non_max_suppression is full of bugs!

### ISSUE THREAD

**Issue by MoussaMM** [tensorflow/tensorflow#35482]
**System information**
The bugs are not related to my system informations. They are caused by a bad coding style in the https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/kernels/non_max_suppression_op.cu.cc and https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/kernels/non_max_suppression_op.cc. Just to be sure those bugs could be easily reproduced on google colab. 

**Describe the current behavior**
I ll mention two major bugs.
The first one is a garbage output when the boxes coordinates are not logical. In fact given a box(y1,x1,y2,x2)  coordinates with y1 = y2 or x1 = x2 (the coordinates of a line) or even worst the coordinates of a point ( x1 = x2 = y1 = y2) the algorithme will only output the line when reaching it. 
**Code to reproduce the issue**
Here is the code to reproduce the behaviour on google colab: 

```
import numpy as np
%tensorflow_version 2.x
import tensorflow as tf
tf.__version__
boxes = np.array([[0.1,0.1,0.2,0.2], [0.3,0.3,0.3,0.4], [0.5,0.5,0.6,0.6], [0.7,0.7,0.8,0.8]], dtype= np.float32)
scores = np.array([0.9,0.8,0.7,0.6], dtype = np.float32)
(tf.image.non_max_suppression(boxes, scores, 8))
```

output:
```
'2.1.0-rc1'
<tf.Tensor: shape=(8,), dtype=int32, numpy=array([0, 1, 1, 1, 1, 1, 1, 1], dtype=int32)>
```

Now I ll explain brievely how the algorithm is coded in tensorflow. Given a list of candidate boxes containing in the beginning all the user boxes and a list of chosen boxes empty, if the box is chosen it will not immediately delete it from the candidate box. In fact, this box will be again processed as a candidate box in the next iteration. But because it is already in the chosen boxes it wont be chosen again . The reason for that is that the IOU of a box with himself is 1 which is always above the threshold. Unfortunately, the IOU of a line or a point with any box is 0. This is applied even when the IOU is calculated of the line with iteself. This will result in adding the line to the chosen boxes again and again. This behaviour is mentioned in this issue but wasn't clearly explained. https://github.com/tensorflow/tensorflow/issues/29628

**Describe the expected behavior**
The expected behaviour must be decided by the tensorflow programer. He can chose between putting it only once in the result : 
-<tf.Tensor: shape=(8,), dtype=int32, numpy=array([0, 1, 2, 3], dtype=int32)> 
or deleting the line box
 -<tf.Tensor: shape=(8,), dtype=int32, numpy=array([0, 2, 3], dtype=int32)>

- The second bug is really inexplainable. Why there is only the gpu specialisation of non_max_suppression_v2 ? Did the developer forgot about it? This was mentioned in several issues under the name : non max suppression work only on cpu. This is completely understandable because the default version of non_max_suppression is v3 which dosent have a gpu specialisation. 

**Code to reproduce the issue**
on colab u can just copy this code:

```
import numpy as np
%tensorflow_version 2.x
import tensorflow as tf
tf.debugging.set_log_device_placement(True)
boxes = np.array([[0.1,0.1,0.2,0.2], [0.3,0.3,0.3,0.4], [0.5,0.5,0.6,0.6], [0.7,0.7,0.8,0.8]], dtype= np.float32)
scores = np.array([0.9,0.8,0.7,0.6], dtype = np.float32)
with tf.device('/GPU:0'):
  print(tf.image.non_max_suppression(boxes, scores, 8))
```

output:

> Executing op NonMaxSuppressionV3 in device /job:localhost/replica:0/task:0/device:CPU:0
> tf.Tensor([0 1 1 1 1 1 1 1], shape=(8,), dtype=int32)

**Describe the expected behavior**

> Executing op NonMaxSuppressionV3 in device /job:localhost/replica:0/task:0/device:GPU:0

Correcting this issue is quite simple and straightforward. Gpu specialisation must be made for non_max_suppression_v3 at least.

**Comment by gadagashwini** [comment]
Issue is replicating on colab with Tf 2.1.
Please find the gist [here](https://colab.sandbox.google.com/gist/gadagashwini/2cf976ada8376c28056285c958785c97/untitled331.ipynb). Thanks!

**Comment by samikama** [comment]
@MoussaMM NMS is defined on boxes and not lines or points. I don't think there is any issue with the code there. I believe your inputs are not valid inputs. Please point me to the reference where NMS is defined on point or lines. Otherwise this can be closed.

**Comment by MoussaMM** [comment]
@samikama thank you a lot for your reply. Yeah you have a valid point, the operation is not designed for anything but boxes. But even if it s not defined to points or lines returning a completely unexpected results for a wrong input is an issue. That is why I made a pull request to raise an error when entering wrong coordinates : https://github.com/tensorflow/tensorflow/pull/35544 . Probably it is not an important problem in most cases but imagine that this operation will take its input from a not controlled neural network. This will make the user completely lost.
In addition, the gpu specialization are commented in the source code and were not attended since. I guess the user won't understand that this operation doesn't have a gpu specialization. Until then I wish that this issue remains opened.

**Comment by amahendrakar** [comment]
@MoussaMM,
Is this still an issue?

On running the code with the latest stable version of TensorFlow v2.4.1, I got the 'expected behavior'. Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/c3a25e8b35823a178d85f378a6de9ac3/35482.ipynb). Thanks!

**Comment by MoussaMM** [comment]
Yes I think the issue is solved. Thank you!
