### ISSUE TITLE
Why doesn't ```tf.keras.losses.binary_crossentropy``` raise error

### ISSUE THREAD

**Issue by DachuanZhao** [tensorflow/tensorflow#35490]
```
x = np.arange(10,dtype=np.float64).reshape(10,1)
#x.shape = (10,1)

y = np.arange(10,dtype=np.float64)
#y.shape = (10,)

tf.keras.losses.binary_crossentropy(y_true=y, y_pred=x)
#this line does't raise error

tf.keras.metrics.BinaryAccuracy()(y_true=y, y_pred=x)
#this line neither

tf.keras.metrics.Precision()(y_true=y, y_pred=x)
#this line raise an error
```
I think ```binary_crossentropy``` and ```BinaryAccuracy```  should raise an ValueError like ```tf.keras.metrics.Precision```: 
```
ValueError: Shapes (128, 1) and (128,) are incompatible
```

**Comment by oanush** [comment]
@DachuanZhao ,
I was able to replicate the issue with TF-1.5 and TF-2.0, kindly find the [gist](https://colab.sandbox.google.com/gist/oanush/febed084ad734e809b857a89164015ae/35490.ipynb) of colab.Thanks!

**Comment by pavithrasv** [comment]
Precision metric should actually not be raising an error. Have a change out to fix this.

**Comment by pavithrasv** [comment]
This is fixed now in : https://github.com/tensorflow/tensorflow/commit/ba8a0c934147fcf2a879f349677fc11676c73835#diff-1d3c0e76cc08b7d6e2e3a6ab89965a5c
