### ISSUE TITLE
code for libhexagon_interface.so

### ISSUE THREAD

**Issue by dlaiup** [tensorflow/tensorflow#35506]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 16.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): source
- TensorFlow version: 1.15
- Python version: 3.4
- Installed using virtualenv? pip? conda?: pip
- Bazel version (if compiling from source): 1.2.1
- GCC/Compiler version (if compiling from source): 5.4
- CUDA/cuDNN version: 10.1
- GPU model and memory: 1080TI, 12G

**Describe the problem**
@karimnosseir, saw your answers to the https://github.com/tensorflow/tensorflow/issues/35221, 
Just interested in where is the source code to build libhexagon_interface.so for the hexagon delegate? 
Found that libhexagon_nn_skel.so had the source code in https://source.codeaurora.org/quic/hexagon_nn/nnlib/, but no code for libhexagon_interface.so? Do you know if libhexagon_interface.so will be open source as well?

**Comment by karimnosseir** [comment]
Hi,

We can't host the code because of licensing as it depends on some libraries we don't have control on.

**Comment by olramde** [comment]
s

**Comment by dlaiup** [comment]
Got it, thanks.

**Comment by liuming-td** [comment]
how can we get libhexagon_interface.so? I can't find this shared library from the directory of tensorflow lite. Hope someone can help me !

**Comment by karimnosseir** [comment]
@liuming-td You can get from [here](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/delegates/hexagon/hexagon_nn/BUILD#L34)

example:
bazel build --config=android_arm64  -c opt //tensorflow/lite/delegates/hexagon/hexagon_nn:libhexagon_interface.so

If you need it for arm linux
You can reach directly to me through email (same as my username here) and i will share it.

P.S.:
The code itself will be added to github soon, we worked with QC on resolving most of the licensing issues and will be pushed soon.

**Comment by duynguyen0209** [comment]
G

**Comment by liuming-td** [comment]
> @liuming-td You can get from [here](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/delegates/hexagon/hexagon_nn/BUILD#L34)
> 
> example:
> bazel build --config=android_arm64 -c opt //tensorflow/lite/delegates/hexagon/hexagon_nn:libhexagon_interface.so
> 
> If you need it for arm linux
> You can reach directly to me through email (same as my username here) and i will share it.
> 
> P.S.:
> The code itself will be added to github soon, we worked with QC on resolving most of the licensing issues and will be pushed soon.

Thank you very much for your reply!
I want to ask that what's the difference between the "hexagon_nn_global_teardown" function in tf lite delegate and "hexagon_nn_teardown" function in Hexagonnn SDK. And the same question for "hexagon_nn_global_init".
And also, could you tell me something about how the "hexagon_nn_is_device_supported" function implemented？

**Comment by karimnosseir** [comment]
hexagon_nn_global_teardown/hexagon_nn_global_init are methods we introduced to make sure we do any initialization/destructions required before/after doing any dsp calls.

hexagon_nn_teardown are responsible for destructing 1 single dsp graph (takes the graph id).

hexagon_nn_is_device_supported is a method we introduced and calls during delegate creation to make sure the device is from the set of devices that we know is supported and delegate tried on it.

We maintain static list of soc ID that are supported.
It is something like
 - Get SoC ID
 - Check if SoC ID is in the static list of supported devices
 - If yes return true, otherwise false.

**Comment by liuming-td** [comment]
> hexagon_nn_global_teardown/hexagon_nn_global_init are methods we introduced to make sure we do any initialization/destructions required before/after doing any dsp calls.
> 
> hexagon_nn_teardown are responsible for destructing 1 single dsp graph (takes the graph id).
> 
> hexagon_nn_is_device_supported is a method we introduced and calls during delegate creation to make sure the device is from the set of devices that we know is supported and delegate tried on it.
> 
> We maintain static list of soc ID that are supported.
> It is something like
> 
> * Get SoC ID
> * Check if SoC ID is in the static list of supported devices
> * If yes return true, otherwise false.

Really appreciate!

**Comment by usuku-hideki** [comment]
@karimnosseir 
When I call close() on HexagonDelegate, the DDR frequency does not come down.
I want to lower the DDR frequency by calling close() of HexagonDelegate.
The version of libhexagon_interface.so that I am using is Hexagon SDK (ver. 3.4.3).
I would like to get libhexagon_interface.so which uses the new Hexagon SDK (ver.3.5.4).
Could you please share the libhexagon_interface.so?

Please let me know if you have any other good solutions other than the above.

**Comment by karimnosseir** [comment]
@usuku-hideki 

The code of libhexagon_interface.so is now on github [here](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/delegates/hexagon/hexagon_nn)

Feel free to adjust it as you want per your use case.

You might want to also check the code under third_party in [this](https://github.com/tensorflow/tensorflow/blob/master/third_party/hexagon/workspace.bzl) package, as it might be different from what you find in the SDK version you're using.

**Comment by usuku-hideki** [comment]
@karimnosseir 
Thank you for your reply.
I was able to build and libhexagon_interface.so which uses HexagonSDK version 3.4.3.
Do you know how to make libhexagon_interface.so which uses HexagonSDK version 3.5.4?
Please let me know if you know.

**Comment by karimnosseir** [comment]
@usuku-hideki 
How did you build it ? Did you update the dependent files that are required from the SDK and used blaze or something else ?

The code should compile on SDK 3.5.4 and even 4.3.0

**Comment by usuku-hideki** [comment]
@karimnosseir 
I built the Heagon SDK version 3.5.4 and created libhexagon_nn_skel.so.
I built the tensorflow library with bazel and created libhexagon_interface.so.

None of the files have been changed.
I guess I should change some settings in the dependency files, but I don't know where to change to get the libhexagon_interface.so that uses Hexagon SDK 3.5.4.
If you know, please let me know.

**Comment by karimnosseir** [comment]
@usuku-hideki Sorry for the late reply.

You will need to update the build file and replace all dependencies with "@hexagon_nn//" to use your own versions.

**Comment by xbwee1024** [comment]
@karimnosseir 
I have a 865_rb5 device and after flash the system (ubuntu_aarch64) has `/usr/lib/libhexagon_interface.so` and `/usr/lib/rfsa/adsp/libhexagon_nn_skel.so` existed already, and I can run tflite benchmark_model with hexagon delegate successfully, why?  as you known hexagon_nn in tflite is different with which in Hexagon_SDK. 
I think the only way is that `/usr/lib/libhexagon_interface.so` on RB5 is built from tflite source code, is that right ?

**Comment by xbwee1024** [comment]
Maybe i found the answer:
https://developer.qualcomm.com/forum/qdn-forums/hardware/qualcomm-robotics-rb5-development-kit/68515
> If you are opting for second, you application will need two different libraries as mentioned below:
    1. libhexagon_interface.so: 
This library is loaded on ARM side and acts as a stub that runs on arm to send RPC calls to DSP to execute a network. 
This library has to be build from tensorflow repository (using bazel if running on android, RB5 ships this library. You can find it in /usr/lib/).

**Comment by karimnosseir** [comment]
@xbwee1024 Yes libhexagon_interface.so is built from TF repo.
You can build this rule to compile it.
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/delegates/hexagon/hexagon_nn/BUILD#L75

If you're facing issue with different versions. You can adjust to the version you have by updating this and building the libhexagon_interface
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/delegates/hexagon/hexagon_nn/hexagon_nn_init.cc#L29

**Comment by xbwee1024** [comment]
@karimnosseir very clear, thanks for your reply 👍

**Comment by xbwee1024** [comment]
@karimnosseir still have another question, appreciate if you know the anser:
How can tflite::delegate::hexagon run on QC devices without 'device signing'(signature with TestSig, unsigned-PD)?
Or it does but i dont known, and where?
Thanks~
