### ISSUE TITLE
Tensorflow gets stuck in sess.run() while making a prediction

### ISSUE THREAD

**Issue by ubaid08** [tensorflow/tensorflow#35508]
I'm using an **ssd** model to make prediction on images using **tensorflow**. I'm currently on **tensorflow** **1.14.0**.

I'm running the code in two different environments. I'm making a request to Cherrypy in one environment and it is working perfectly fine.

In the other environment, the request is made to **Cherrypy** through **Kafka** and the `tf.session.run()` gets stuck infinitely and doesn't return any output nor does it raise an exception.

`results = self._do_run(handle, final_targets, final_fetches,
                             feed_dict_tensor, options, run_metadata)`

This line is found in `session.py` package in `TensorFlow`. This is the specific point in code where the code gets stuck

I have not been able to figure out a reason for this anomaly and I didn't find anything useful on the internet regarding this problem. Does sending a request through **Kafka** is causing such an abnormal behavior?

Any help in this regard would be very appreciated. Thank You.

The details of my environment:

> CLUTTER_IM_MODULE=xim LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:.tar=01;31:.tgz=01;31:.arc=01;31:.arj=01;31:.taz=01;31:.lha=01;31:.lz4=01;31:.lzh=01;31:.lzma=01;31:.tlz=01;31:.txz=01;31:.tzo=01;31:.t7z=01;31:.zip=01;31:.z=01;31:.Z=01;31:.dz=01;31:.gz=01;31:.lrz=01;31:.lz=01;31:.lzo=01;31:.xz=01;31:.zst=01;31:.tzst=01;31:.bz2=01;31:.bz=01;31:.tbz=01;31:.tbz2=01;31:.tz=01;31:.deb=01;31:.rpm=01;31:.jar=01;31:.war=01;31:.ear=01;31:.sar=01;31:.rar=01;31:.alz=01;31:.ace=01;31:.zoo=01;31:.cpio=01;31:.7z=01;31:.rz=01;31:.cab=01;31:.wim=01;31:.swm=01;31:.dwm=01;31:.esd=01;31:.jpg=01;35:.jpeg=01;35:.mjpg=01;35:.mjpeg=01;35:.gif=01;35:.bmp=01;35:.pbm=01;35:.pgm=01;35:.ppm=01;35:.tga=01;35:.xbm=01;35:.xpm=01;35:.tif=01;35:.tiff=01;35:.png=01;35:.svg=01;35:.svgz=01;35:.mng=01;35:.pcx=01;35:.mov=01;35:.mpg=01;35:.mpeg=01;35:.m2v=01;35:.mkv=01;35:.webm=01;35:.ogm=01;35:.mp4=01;35:.m4v=01;35:.mp4v=01;35:.vob=01;35:.qt=01;35:.nuv=01;35:.wmv=01;35:.asf=01;35:.rm=01;35:.rmvb=01;35:.flc=01;35:.avi=01;35:.fli=01;35:.flv=01;35:.gl=01;35:.dl=01;35:.xcf=01;35:.xwd=01;35:.yuv=01;35:.cgm=01;35:.emf=01;35:.ogv=01;35:.ogx=01;35:.aac=00;36:.au=00;36:.flac=00;36:.m4a=00;36:.mid=00;36:.midi=00;36:.mka=00;36:.mp3=00;36:.mpc=00;36:.ogg=00;36:.ra=00;36:.wav=00;36:.oga=00;36:.opus=00;36:.spx=00;36:.xspf=00;36: LESSCLOSE=/usr/bin/lesspipe %s %s XDG_MENU_PREFIX=gnome- LANG=en_US.UTF-8 MANAGERPID=3651 DISPLAY=:0 INVOCATION_ID=56bfbab67ced4d1496b1e75a14fb4af7 GNOME_SHELL_SESSION_MODE=ubuntu COLORTERM=truecolor ZEITGEIST_DATA_PATH=/home/pandas/.local/share/zeitgeist USERNAME=pandas XDG_VTNR=2 SSH_AUTH_SOCK=/run/user/1000/keyring/ssh XDG_SESSION_ID=2 USER=pandas DESKTOP_SESSION=ubuntu QT4_IM_MODULE=xim TEXTDOMAINDIR=/usr/share/locale/ GNOME_TERMINAL_SCREEN=/org/gnome/Terminal/screen/a438ce7f_2ce0_4925_a81f_ef228f7d5a94 JOURNAL_STREAM=9:71038 TEXTDOMAIN=im-config SSH_AGENT_PID=3796 QT_ACCESSIBILITY=1 XDG_SESSION_TYPE=x11 XDG_DATA_DIRS=/usr/share/ubuntu:/usr/local/share/:/usr/share/:/var/lib/snapd/desktop XDG_SESSION_DESKTOP=ubuntu DBUS_STARTER_ADDRESS=unix:path=/run/user/1000/bus,guid=d47913508d685ac43652dcc65e059d87 GTK_MODULES=gail:atk-bridge WINDOWPATH=2 TERM=xterm-256color SHELL=/bin/bash VTE_VERSION=5202 QT_IM_MODULE=xim XMODIFIERS=@im=ibus IM_CONFIG_PHASE=2 DBUS_STARTER_BUS_TYPE=session XDG_CURRENT_DESKTOP=ubuntu:GNOME GPG_AGENT_INFO=/run/user/1000/gnupg/S.gpg-agent:0:1 GNOME_TERMINAL_SERVICE=:1.98 XDG_SEAT=seat0 SHLVL=1 GDMSESSION=ubuntu GNOME_DESKTOP_SESSION_ID=this-is-deprecated LOGNAME=pandas DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus,guid=d47913508d685ac43652dcc65e059d87 XDG_RUNTIME_DIR=/run/user/1000 XAUTHORITY=/run/user/1000/gdm/Xauthority XDG_CONFIG_DIRS=/etc/xdg/xdg-ubuntu:/etc/xdg PATH=/home/pandas/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin SESSION_MANAGER=local/ubuntu:@/tmp/.ICE-unix/3691,unix/ubuntu:/tmp/.ICE-unix/3691 LESSOPEN=| /usr/bin/lesspipe %s GTK_IM_MODULE=ibus

>

**Comment by gadagashwini** [comment]
@ubaid08, Just to verify, did you check whether the ssd model is running as expected before deploying it on Cherrypy. Thanks!

**Comment by ubaid08** [comment]
@gadagashwini yes it working perfectly fine when a direct call is made to cherrypy but it causes the mentioned problem when a request is made to cherrypy through kafka.

**Comment by gadagashwini** [comment]
@ubaid08, Looks like issue is not related to Tensorflow. Can you check and confirm. Thanks!

**Comment by gadagashwini** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
