### ISSUE TITLE
GPU Support for Poisson Random Noise Generator in TensorFlow

### ISSUE THREAD

**Issue by kjmiller944** [tensorflow/tensorflow#35502]
I am interested in using Generative Adversarial Network (GAN) to generate synthetic images for algorithm training. Poisson-distributed noise is an important source of noise in images. However, it does not appear that the TensorFlow Poisson noise generator has GPU support. The following code fails to execute:

```
import tensorflow as tf

with tf.Session() as sess:
    with tf.device("/gpu:0"):
        test = sess.run(tf.random.poisson(1.0, [], dtype=tf.float32))
print(test)
```
with the error message
```
tensorflow.python.framework.errors_impl.InvalidArgumentError: Cannot assign a device for operation random_poisson/RandomPoissonV2: node random_poisson/RandomPoissonV2 (defined at /home/kjmiller/anaconda3/envs/tf_clone/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py:1748)  was explicitly assigned to /device:GPU:0 but available devices are [ /job:localhost/replica:0/task:0/device:CPU:0, /job:localhost/replica:0/task:0/device:XLA_CPU:0, /job:localhost/replica:0/task:0/device:XLA_GPU:0 ]. Make sure the device specification refers to a valid device.
	 [[random_poisson/RandomPoissonV2]]
```
When training my model (the code is too much to place here), I get
```
LookupError: No gradient defined for operation 'Generator/RandomPoissonV2' (op type: RandomPoissonV2)
```
I have tried overriding the gradient in the hopes that is the issue, but that did not work. I am pretty should that the second error also has to do with GPU support, as the `lam` argument input to tf.random.poisson is a tensor that lives in GPU memory.

It would be a tremendous help if TensorFlow had GPU support for Poisson-distributed noise, as this is a fundamental noise source for any image taken with a camera.

**Comment by gadagashwini** [comment]
@kjmiller944, Which Tensorflow version are you using.
I tried with Tf 2.0, i didn't receive error message.Please take a look at gist [here](https://colab.sandbox.google.com/gist/gadagashwini/f3e81f4c0436f97b01625569f6a2e74e/untitled330.ipynb). Thanks!

**Comment by kjmiller944** [comment]
@gadagashwini thank you. I just realize now that I did not correctly install my TensorFlow 2.0 GPU version. I am still getting the second error message regarding the `ValueError` but I want to try something and get back to you. Thank you for your quick reply.

**Comment by gadagashwini** [comment]
@kjmiller944, Any update!

**Comment by gadagashwini** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
