### ISSUE TITLE
A puzzling & fatal error occurred in the tf.matmal()

### ISSUE THREAD

**Issue by cantbeblank96** [tensorflow/tensorflow#35500]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

System information

- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
no
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
Linux Ubuntu 18.04 and win 10
- TensorFlow installed from (source or binary):
Install in the conda integration environment
conda create -n tf2-gpu tensorflow-gpu=2.0
- TensorFlow version (use command below):
tf-gpu 2.0 stable  &  tf-gpu 2.0 beta
- Python version:
3.6
- CUDA/cuDNN version:
CUDA: 10.0.0130-0
cuDNN: 7.6.5
- GPU model and memory:
GeForce GTX 850M
GeForce RTX 2070S

You can collect some of this information using our environment capture
script
You can also obtain the TensorFlow version with: 1. TF 1.0: python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)" 2. TF 2.0: python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"

Describe the current behavior & expected behavior

The following error occurs when using  tf.matmal() to compute the product of multidimensional tensors on the gpu.

    import tensorflow as tf
    import numpy as np
    
    j = np.random.rand(10, 6, 1130, 16, 8)
    k = np.random.rand(10, 6, 1130, 8, 1)
    # with tf.device("CPU:0"):
    j = tf.cast(j, dtype=tf.float32)
    k = tf.cast(k, dtype=tf.float32)
    
    a = tf.matmul(j, k)[9, 3]
    b = tf.matmul(j[9], k[9])[3]
    c = tf.matmul(j[9, 3], k[9, 3])
    
    print(tf.reduce_all(tf.equal(a, b)))
    print(tf.reduce_all(tf.equal(b, c)))
    
    '''
    tf.Tensor(False, shape=(), dtype=bool)  # The correct output would be True
    tf.Tensor(True, shape=(), dtype=bool)
    '''

This error does not occur while using the CPU.

    ...
    
    with tf.device("CPU:0"):
        j = tf.cast(j, dtype=tf.float32)
        k = tf.cast(k, dtype=tf.float32)
    
        a = tf.matmul(j, k)[9, 3]
        b = tf.matmul(j[9], k[9])[3]
        c = tf.matmul(j[9, 3], k[9, 3])
    
        print(tf.reduce_all(tf.equal(a, b)))
        print(tf.reduce_all(tf.equal(b, c)))
    
    '''
    tf.Tensor(True, shape=(), dtype=bool)
    tf.Tensor(True, shape=(), dtype=bool)
    '''

This error will not occur even if you reduce the size of some dimension a bit.

We make the following changes:

    # j = np.random.rand(10, 6, 1130, 16, 8)
    # k = np.random.rand(10, 6, 1130, 8, 1)
    j = np.random.rand(10, 6, 1129, 16, 8)  # 1130 --> 1129
    k = np.random.rand(10, 6, 1129, 8, 1)

also use the gpu:

    j = tf.cast(j, dtype=tf.float32)
    k = tf.cast(k, dtype=tf.float32)
    
    a = tf.matmul(j, k)[9, 3]
    b = tf.matmul(j[9], k[9])[3]
    c = tf.matmul(j[9, 3], k[9, 3])
    
    print(tf.reduce_all(tf.equal(a, b)))
    print(tf.reduce_all(tf.equal(b, c)))
    
    '''
    tf.Tensor(True, shape=(), dtype=bool)
    tf.Tensor(True, shape=(), dtype=bool)
    '''

I tested it on different GPU and OS , but got the same error.

When errors occur, I have compared the specific differences between the two methods ( a and b), and found that it is not the slight differences that cause the error.

    print(tf.reduce_sum(a-b))
    '''
    tf.Tensor(-1.3804454e+38, shape=(), dtype=float32)
    '''

**Comment by cantbeblank96** [comment]
Further, I found that the error should be related to the dimensional size of the matrix

    offset = 0
    while True:
        j = np.random.rand(*(65530+offset*1 , 16, 8))
        k = np.random.rand(*(65530+offset*1 , 8, 1))
        # with tf.device("CPU:0"):
        j = tf.cast(j, dtype=tf.float32)
        k = tf.cast(k, dtype=tf.float32)
    
        a = tf.matmul(j, k)[-1]
    
        b = tf.matmul(j[-1], k[-1])
        print(offset)
    
        if not tf.reduce_all(tf.equal(a, b)).numpy():
            break
    
        offset += 1
    
    print(65530+offset*1)
    '''
    65536  (is 2^16)
    '''

**Comment by gadagashwini** [comment]
Issue is replicating with Tf 2.0.
Please find the gist [here](https://colab.sandbox.google.com/gist/gadagashwini/a221e9be6aab3be79921b03150442ab8/untitled333.ipynb). Thanks!

**Comment by cantbeblank96** [comment]
thanks for your replication, this error still exists in colab.

Is there any update on resolving this error.
This is important because this error is out of control unless the gpu is not used.

**Comment by cantbeblank96** [comment]
@alextp Can you take a look at this?

**Comment by alextp** [comment]
I just ran against tf-nightly and it's fixed there.

**Comment by cantbeblank96** [comment]
Well, this bug was also fixed in version 2.1
