### ISSUE TITLE
TFLite GPU Delegate on iOS: failed assertion `Cannot create a buffer of zero length.

### ISSUE THREAD

**Issue by rajeev-mirelz** [tensorflow/tensorflow#35509]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): iPAD OS 13.2.2
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: iPAD Pro 2018
- TensorFlow installed from (source or binary): Binary (TfLiteGPUExperimental)
- TensorFlow version (use command below):
- Python version: NA
- Bazel version (if compiling from source): NA
- GCC/Compiler version (if compiling from source): NA
- CUDA/cuDNN version: NA
- GPU model and memory: iPAD GPU

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
When running the model on iPAD using CPU, we are able to get the output. But when doing GPU delegate, we get the error the following error:
_failed assertion `Cannot create a buffer of zero length._
**Describe the expected behavior**
No error
**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.
delegate = NewGpuDelegate(nullptr);
      interpreter->ModifyGraphWithDelegate(delegate);

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by rajeev-mirelz** [comment]
Hi Folks, any update on this one. Thanks.

**Comment by yyoon** [comment]
Were you trying to run your own app? Which model were you using?

**Comment by rajeev-mirelz** [comment]
@yyoon I was using 'palm_detection.tflite' model on the following web link --> https://github.com/google/mediapipe/tree/master/mediapipe/models

Please let me know if you need any additional information.

**Comment by yyoon** [comment]
And which exact app were you using for running that model?
Was it your own written app, or did you try to modify one of the existing example apps?

**Comment by rajeev-mirelz** [comment]
@yyoon We were trying to use tflite model on iOS using the following code.

```
tflite::InterpreterBuilder(*model, resolver)(&interpreter);
GpuDelegateOptions options;
options.allow_precision_loss = true;
options.wait_type = GpuDelegateOptions :: WaitType::kActive;
delegate = NewGpuDelegate(nullptr);
interpreter->ModifyGraphWithDelegate(delegate);
....

```
The code fails on the last  line 'interpreter->ModifyGraphWithDelegate(delegate);' above. Please let me know if you need any more information. Thanks.

**Comment by rajeev-mirelz** [comment]
@yyoon Any update on this one. Thanks a lot for your help.

**Comment by rajeev-mirelz** [comment]
@yyoon Any luck with this one. Thanks.

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this issue, as you are using an older version of tensorflow(1.x) which is officially considered as end of life. We recommend that you upgrade to 2.4 or later version and let us know if the issue still persists in newer versions. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, Please open a new issue for any help you need against 2.x, and we will get you the right help.

**Comment by rajeev-tbrew** [comment]
We can close this issue.

**Comment by rajeev-mirelz** [comment]
We can close this issue.
