### ISSUE TITLE
where can I find “hexagon_nn_skel.run” ?

### ISSUE THREAD

**Issue by huanyingjun** [tensorflow/tensorflow#35511]
from "tensorflow/lite/g3doc/performance/hexagon_delegate.md" :
Run “hexagon_nn_skel.run” - Note: you will need to accept the license agreement. It should provide 3 different shared libraries “libhexagon_nn_skel.so”, “libhexagon_nn_skel_v65.so”, “libhexagon_nn_skel_v66.so”

but I can not find hexagon_nn_skel.run, where can I download  “libhexagon_nn_skel.so”, “libhexagon_nn_skel_v65.so”, “libhexagon_nn_skel_v66.so”  ??

**Comment by ZeusLMT** [comment]
If you read the instructions [here](https://blog.tensorflow.org/2019/12/accelerating-tensorflow-lite-on-qualcomm.html), you can see they have included a link to download that

I extracted that link here for you, in case you don't want to search through the instructions: [hexagon_nn_skel.run](https://storage.cloud.google.com/download.tensorflow.org/tflite/hexagon_nn_skel_1_10_3_1.run)

**Comment by huanyingjun** [comment]
thanks

**Comment by anidh** [comment]
> thanks



> If you read the instructions [here](https://blog.tensorflow.org/2019/12/accelerating-tensorflow-lite-on-qualcomm.html), you can see they have included a link to download that
> 
> I extracted that link here for you, in case you don't want to search through the instructions: [hexagon_nn_skel.run](https://storage.cloud.google.com/download.tensorflow.org/tflite/hexagon_nn_skel_1_10_3_1.run)

HI There,

When I'm trying to run the file it's stuck on 
Verifying archive integrity...  100%   All good.
Uncompressing Hexagon NN Shared Libs  100%  
:
That's it.. I have been waiting for almost 15-20 min and no progress. 
Can you please help me in finding what I'm doing wrong.

Thanks

**Comment by anidh** [comment]
> > thanks
> 
> > If you read the instructions [here](https://blog.tensorflow.org/2019/12/accelerating-tensorflow-lite-on-qualcomm.html), you can see they have included a link to download that
> > I extracted that link here for you, in case you don't want to search through the instructions: [hexagon_nn_skel.run](https://storage.cloud.google.com/download.tensorflow.org/tflite/hexagon_nn_skel_1_10_3_1.run)
> 
> HI There,
> 
> When I'm trying to run the file it's stuck on
> Verifying archive integrity... 100% All good.
> Uncompressing Hexagon NN Shared Libs 100%
> :
> That's it.. I have been waiting for almost 15-20 min and no progress.
> Can you please help me in finding what I'm doing wrong.
> 
> Thanks

I finally managed to make it work. For people wondering you need to type "I ACCEPT" without quotes after ":" to make it extract files. Maybe "Y/n" option would've made more sense.
