### ISSUE TITLE
pip installation .whl for aarch64?

### ISSUE THREAD

**Issue by jiapei100** [tensorflow/tensorflow#35514]
Is there a release version for **aarch64**?
It seems there are only version of **x86_64**, **raspberry pi(armv7)**, etc. ?

**Comment by Rajratnpranesh** [comment]
Hey @jiapei100 

Try this- pip install tensorflow-aarch64

**Comment by oanush** [comment]
@jiapei100 ,
Please try using this [command](https://pypi.org/project/tensorflow-aarch64/).Thanks!

**Comment by oanush** [comment]
@jiapei100 ,
Any update on the issue ?Thanks!

**Comment by oanush** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
