### ISSUE TITLE
C++ Tensorflow is very slower than Python Tensorflow

### ISSUE THREAD

**Issue by fmmohammadi** [tensorflow/tensorflow#35512]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below): 1.14 and 1.13
- Python version: 3.6.8
- Bazel version (if compiling from source): 0.21.0
- GCC/Compiler version (if compiling from source): VC 14 (VS 2015)
- CUDA/cuDNN version: 10.0/7.4
- GPU model and memory: RTX 2080

**Describe the current behavior**
I exported a .pb graph file. I use it in python and it took 55 milliseconds to process. I also use it in C++ (both pre-build versions and self-build from source) it took 750 milliseconds. Everything is same!

**Describe the expected behavior**
both python and C++ take 55 ms to process.

 
**Other info / logs**
I build C++ API with below command:
`bazel --output_user_root="C:/bazel/our" build -c opt --copt="-mavx" --config=opt --config=cuda //tensorflow:libtensorflow_cc.so` then rename .so to .dll and .so.ifso to .lib

in #3471 (https://github.com/tensorflow/tensorflow/issues/3471#issuecomment-234671300) mentioned to add `-c opt` flag with `--copt=-mavx`. but it didn't make any difference. Also I found tons of warning as: 
`cl : Command line warning D9002 : ignoring unknown option '-mavx'
`

**Comment by fmmohammadi** [comment]
@concretevitamin would you please help?!

**Comment by oanush** [comment]
@fmmohammadi ,
Thanks for reporting the issue ,Can you share a standalone code to reproduce the error reported here?Thanks!

**Comment by fmmohammadi** [comment]
> @fmmohammadi ,
> Thanks for reporting the issue ,Can you share a standalone code to reproduce the error reported here?Thanks!

Thanks for your consideration. Actually this is not a error that may crashing the program. It is a performance bug. BTW, here is a sample code:

First include tensorflow:

```
#include "tensorflow/cc/ops/const_op.h"
#include "tensorflow/cc/ops/image_ops.h"
#include "tensorflow/cc/ops/array_ops.h"
#include "tensorflow/cc/ops/standard_ops.h"
#include "tensorflow/core/framework/graph.pb.h"
#include "tensorflow/core/framework/tensor.h"
#include "tensorflow/core/graph/default_device.h"
#include "tensorflow/core/graph/graph_def_builder.h"
#include "tensorflow/core/lib/core/errors.h"
#include "tensorflow/core/lib/core/stringpiece.h"
#include "tensorflow/core/lib/core/threadpool.h"
#include "tensorflow/core/lib/io/path.h"
#include "tensorflow/core/lib/strings/stringprintf.h"
#include "tensorflow/core/platform/env.h"
#include "tensorflow/core/platform/init_main.h"
#include "tensorflow/core/platform/logging.h"
#include "tensorflow/core/platform/types.h"
#include "tensorflow/core/public/session.h"
#include "tensorflow/core/util/command_line_flags.h"
#include "tensorflow/cc/ops/io_ops.h"
#include <tensorflow/core/protobuf/meta_graph.pb.h>
```

Next,  Load the freez graph (.pb file) and create a session:

```
GraphPath = "../model.pb";
tensorflow::SessionOptions options;
tensorflow::ConfigProto & config = options.config;
config.mutable_gpu_options()->set_allow_growth(true);
tensorflow::Status status;
status = tensorflow::NewSession(options, &session);
if (!status.ok()) {std::cout << "error: " << status.ToString() << "\n";}
tensorflow::GraphDef graph_def;
status = ReadBinaryProto(tensorflow::Env::Default(), GraphPath, &graph_def);
if (!status.ok()) {std::cout << "error: " << status.ToString() << "\n";}
status = session->Create(graph_def);
if (!status.ok()) {std::cout << "error: " << status.ToString() << "\n";}
```

Then, load video frames with OpenCV and copy cvMat to a Tensor:

```
char VIDEO_FILE[] = "../data/Video.asf";
VideoCapture capture;
capture.open(VIDEO_FILE);
if (!capture.isOpened()) {throw "Error when reading VIDEO_FILE";}
Mat frame;
capture >> frame;
if (frame.empty()) {throw "Error when reading FRAME";}
Tensor Img_ten(tensorflow::DT_FLOAT, tensorflow::TensorShape({ 1, 3, height_des, width_des }));
CopyCvImage2Tensor(frame, Img_ten); //this function copy image to above tensor successfully!
```

Finally, run the session:

```
//input and output name. all is correct!
string input_layer = "input:0";
std::vector<string> output_layer = { "output:0", "output:1", "output:2",  "output:3", "output:4", "output:5", "output:6", "output:7", "output:8" };
std::vector<Tensor> net_out;
Status run_status = session->Run({ { input_layer, Img_ten } }, output_layer, {}, &net_out);
if (!run_status .ok()) {std::cout << "error: " << run_status .ToString() << "\n";}
```

 Here, the final section (running session), with python tensorflow take about 50 to 60 milliseconds but with C++ tensorflow (which build with parameters as mentioned above) take about 700 to 720 milliseconds. about 12x slower!!!

Also, here is the python code:

```
import tensorflow as tf
tf_graph = self.load_pb('../model.pb')
sess = tf.Session(graph=tf_graph)
output_tensor = ["output:0", "output:1", "output:2",  "output:3", "output:4", "output:5", "output:6", "output:7", "output:8"]
input_tensor = tf_graph.get_tensor_by_name('input:0')
ret, frame = cap.read()
IMAGE_tensor = copy2Tensor(frame)
output_tf = self.sess.run(output_tensor, feed_dict={input_tensor: IMAGE_tensor})
```

Both are same version of tensorflow and run on RTX 2080. both allocate about 7GB memory of GPU but the main difference is than python API utilize about 40% of Cuda whereas C++ API utilize about 5% of Cuda in Performance tab of Task Manager (or even with nvidia-smi.exe). I think this is the cause of this performance bug. But I don't know what is the solution?!

**Comment by fmmohammadi** [comment]
@ymodak no idea?

**Comment by ymodak** [comment]
Can you attach your `.pb` file as well?

**Comment by wangwenchao-job** [comment]
Was this resolved later? I encountered the same problem.
@ymodak
@fmmohammadi

**Comment by fmmohammadi** [comment]
> Was this resolved later? I encountered the same problem.
> @ymodak
> @fmmohammadi

Try rebuild tensorflow with mkl support
also make sure that the debugger of VS is not activate during running (even in release mode)
