### ISSUE TITLE
model.fit_generator() always uses eager execution instead of a compiled graph

### ISSUE THREAD

**Issue by jlherren** [tensorflow/tensorflow#35513]
**System information**
OS: Debian 10, x64
GPU: GeForce GTX 1060 6GB
Python: 3.7.3
TensorFlow: 2.0.0 installed from source (git tag v2.0.0)
Bazel: 0.26.1
GCC: 6.5.0
CUDA: 10.1
cuDNN: 7.6.4

**Code to reproduce the issue**
```python
import numpy
import tensorflow as tf
from tensorflow.keras import Model
from tensorflow.keras.layers import Input, Layer

BATCH_SIZE = 32
N_BATCHES = 8
FEATURE_SIZE = 32

class SimpleDense(Layer):
    def __init__(self, units, **kwargs):
        super().__init__(**kwargs)
        self.units = units

    def build(self, input_shape):
        self.kernel = self.add_weight('kernel', shape=[input_shape[-1], self.units])

    def call(self, inputs, **kwargs):
        print('call() has been called with', inputs.__class__.__name__)
        return tf.matmul(inputs, self.kernel)

i = Input(shape=(FEATURE_SIZE,))
o = SimpleDense(units=FEATURE_SIZE)(i)
m = Model(i, o)
m.compile('sgd', 'mse')

print('*** Using fit()')
xy = numpy.zeros((N_BATCHES * BATCH_SIZE, FEATURE_SIZE))
m.fit(xy, xy, batch_size=BATCH_SIZE, verbose=0)

print('*** Using fit_generator()')

def gen():
    zeros = numpy.zeros((BATCH_SIZE, FEATURE_SIZE))
    for _ in range(N_BATCHES):
        yield zeros, zeros

m.fit_generator(gen(), steps_per_epoch=N_BATCHES, epochs=1, verbose=0)
```

**Describe the current behavior**
Output of the above code is:
```
call() has been called with Tensor
*** Using fit()
call() has been called with Tensor
call() has been called with Tensor
*** Using fit_generator()
call() has been called with EagerTensor
call() has been called with EagerTensor
call() has been called with EagerTensor
call() has been called with EagerTensor
call() has been called with EagerTensor
call() has been called with EagerTensor
call() has been called with EagerTensor
call() has been called with EagerTensor
```
When using `fit()` the model runs as a graph, as it should. When using `fit_generator()` the model is run with eager execution, causing `call()` to be invoked on every single batch.

**Describe the expected behavior**
`fit_generator()` should also run the model as a graph, for increased performance.

**Other observations**
* Using `tf.compat.v1.disable_eager_execution()` is an obvious workaround
* It's also possible to use `m.compile(..., experimental_run_tf_function=False)`, however that is very inconvenient because this flag does not persist across saving/reloading (and it's not possible to pass it again, since `compile()` is called by the loading code)
* Setting `m._experimental_run_tf_function = False` is an ugly hack, but works also when reloading the model.
* Setting `m.run_eagerly = False` does not help since it's already `False`.
* Decorating `SimpleDense.call()` with `@tf.function` also works, but that's inconvenient to do for all layers and it's not optimal since only a part of the entire model will run as graph. Also I'm not sure how to manually wrap the entire model with `@tf.function`.

**Comment by ravikyram** [comment]
@jlherren 

Model.fit_generator is deprecated starting from tensorflow 2.1.0 which is currently is in rc2. You can find the documentation for tf-2.1.0-rc1 [here](https://www.tensorflow.org/versions/r2.1/api_docs/python/tf/keras/Model#fit): . Please, find the gist [here](https://colab.sandbox.google.com/gist/ravikyram/0864e10599ddf385c85f3c60f0b2060f/untitled523.ipynb). Thanks!

**Comment by jlherren** [comment]
I will go for TF 2.1, thanks.
