### ISSUE TITLE
Suspected memory leak - when loading multiple models with tf.keras.models.load_model()

### ISSUE THREAD

**Issue by farotem** [tensorflow/tensorflow#35524]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
Linux Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
NA
- TensorFlow installed from (source or binary): binary wheel via PyPI
- TensorFlow version (use command below):
2.1.0-dev20191231 (v1.12.1-21412-g3a094e6 2.1.0-dev20191231)
- Python version:
- Bazel version (if compiling from source):
NA
- GCC/Compiler version (if compiling from source):
NA
- CUDA/cuDNN version:
CUDA 10.0 
- GPU model and memory:
V100 32 GB
You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**

I'm suspecting a CPU memory leak when loading multiple models.
When im running infinite loop that keeps loading the same model while using the same variable the memory (private bytes and working set) of the process keep increasing. At some points the working set seems to free some memory, but the trend is that the memory keeps on rising.
I used a simple model (attached).

This trend happens even though I call gc.collect() on every iteration and tf.keras.backend.clear_session().

the issue also happens in TF 2.0 (v2.0.0-rc2-26-g64c3d38 2.0.0).
for a specific model:
    running in TF 2.0 each iteration adds 16 MiB
    running in TF 2.1 each iteration adds 2 MiB

**Describe the expected behavior**

The memory shouldnt increase on each interation

**Code to reproduce the issue**
`
```
import os
import tensorflow as tf
import gc # garbage collector
import objgraph
from memory_profiler import profile

def mem_stat():
  objs = gc.get_objects()
  print("total objects count", len(objs))

@profile
def profile_own_model():
    model = tf.keras.models.Sequential([
        tf.keras.layers.Flatten(input_shape=(28, 28)),
        tf.keras.layers.Dense(128, activation='relu'),
        tf.keras.layers.Dropout(0.2),
        tf.keras.layers.Dense(10, activation='softmax')
    ])
    # model.save('my_model')
    tf.keras.backend.clear_session()
    del model
    gc.collect()

@profile
def profile_load_model(path):
    model = tf.keras.models.load_model(model_path, compile=False)
    tf.keras.backend.clear_session()
    del model
    gc.collect()



model_path = f'/my_model.hd5'
print("load model in loops:")

c = 1
while True:
    print("----------- iter", c)
    profile_load_model(model_path)

    print("mem stat after model creation:")
    mem_stat()
    objgraph.show_growth(limit=30)
    c += 1
```
`

**Other info / logs**
![memory tf 2 1](https://user-images.githubusercontent.com/27951762/71644038-d9f5c500-2cca-11ea-96e3-b8aedd2e4efb.png)

Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by gadagashwini** [comment]
@farotem, I tried reproducing the issue with Tf 2.1.but got different error message. Please find the [gist](https://colab.sandbox.google.com/gist/gadagashwini/71946c07f0ba1906fc249029847f4259/untitled335.ipynb) and confirm. Thanks!

**Comment by farotem** [comment]
@gadagashwini hi I looked at the gist, 
it looks like the profiler can't work under Ipython environment still you can look at the memory with your own tools.. 
to run the code just comment the memory_profiler part:

```
import os
import tensorflow as tf
import gc # garbage collector
import objgraph
#from memory_profiler import profile

```
```
def mem_stat():
    objs = gc.get_objects()
    print("total objects count", len(objs))

#@profile
def profile_own_model():
    model = tf.keras.models.Sequential([
        tf.keras.layers.Flatten(input_shape=(28, 28)),
        tf.keras.layers.Dense(128, activation='relu'),
        tf.keras.layers.Dropout(0.2),
        tf.keras.layers.Dense(10, activation='softmax')
    ])
    # model.save('my_model')
    tf.keras.backend.clear_session()
    del model
    gc.collect()

#@profile
def profile_load_model(path):
    model = tf.keras.models.load_model(model_path, compile=False)
    tf.keras.backend.clear_session()
    del model
    gc.collect()

model_path = f'/my_model.hd5'
print("load model in loops:")

c = 1
while True:
    print("----------- iter", c)
    profile_load_model(model_path)

    print("mem stat after model creation:")
    mem_stat()
    objgraph.show_growth(limit=30)
    c += 1

````
`

**Comment by retviews** [comment]
Installing tf-nightly-gpu with "pip install tf-nightly-gpu" fixed the issue for me

**Comment by gadagashwini** [comment]
@farotem, I tried replicating the issue with commenting profile, looks like issue is related my_model file. Please find the [gist](https://colab.sandbox.google.com/gist/gadagashwini/4fcd1d5ae63b0f72dcc65076e10aad15/untitled338.ipynb?authuser=1). Can you try @retviews's suggestion and let us know how it progresses. Thanks!

**Comment by farotem** [comment]
Hi I tried installing tf-nightly-gpu, version: 2.1.0.dev20200107
**still** receives memory leaks in the CPU.
note 1:
the number of python objects doesn't seem to be the cause for the leak, after few iterations the number of python objects do not increase but the memory usage of the CPU is still increasing.
note 2: 
I tried loading the same model from json and **there are no memory leaks**.
I think it means the memory leaks is somewhere in deserializing the model from folder.

I looked at the gist, below is the fixed code: (changed the path of file)


```
import os
import tensorflow as tf
import gc # garbage collector

def build_and_save_own_model():
    model = tf.keras.models.Sequential([
        tf.keras.layers.Flatten(input_shape=(28, 28)),
        tf.keras.layers.Dense(128, activation='relu'),
        tf.keras.layers.Dropout(0.2),
        tf.keras.layers.Dense(10, activation='softmax')
    ])
    model.save('my_model')
    tf.keras.backend.clear_session()
    del model
    gc.collect()

def profile_load_model(path):
    model = tf.keras.models.load_model(model_path, compile=False)
    tf.keras.backend.clear_session()
    del model
    gc.collect()

model_path = 'my_model'
build_and_save_own_model()
print("load model in loops:")
c = 1
while True:
    print("----------- iter", c)
    profile_load_model(model_path)
    c += 1
```

**Comment by gadagashwini** [comment]
Issue is replicating on colab.
Please take a look at [gist](https://colab.research.google.com/drive/1TLk3pOxde4KERIBOEHE96hlfgNZOZA67?usp=sharing). Thanks!

**Comment by ymodak** [comment]
Is this still an issue with latest version of tensorflow (2.2)?

**Comment by JoshEZiegler** [comment]
I seem to be having this same issue on TF 2.3.

**Comment by farotem** [comment]
tested on TF 2.3 same issue..

**Comment by JoshEZiegler** [comment]
This seems to be reduced with the latest tf-nightly, tested with [this colab notebook](https://colab.research.google.com/gist/idfah/dff83de8d2a6406c9b92221e6282a8d6/tf2_load_mem_leak.ipynb#scrollTo=5IhHO-wynZKC). 

See also #40171 for more discussion.

**Comment by farotem** [comment]
It is reduced but not fixed sadly its still an issue for our team
I opened a new bug for nightly version (tf2. 4)
https://github.com/tensorflow/tensorflow/issues/45453#issuecomment-740755898
