### ISSUE TITLE
TFLite model output different probabilities and thus different classes in Android compared to the original h5 model..

### ISSUE THREAD

**Issue by rishabhsahrawat** [tensorflow/tensorflow#35538]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Google Colab / Android Studio
- TensorFlow installed from (source or binary): Source
- TensorFlow version (or github SHA if from source):  1.14

**Provide the text output from tflite_convert**
TFLite Model output probabilities on same input text:
```
[0.07323484, 0.021794094, 0.013985702, 0.013658127, 0.010268052]
```

H5 Model file output on same input text: 
```
[0.03437233, 0.02771266, 0.01885756, 0.01123235, 0.01093488]
```
However, in both cases the first probabilities belong to the same classes. The predicted classes in both cases are not meaningless but also they are not same, which should be the case.

**Comment by ravikyram** [comment]
@rishabhsahrawat 

Can you please help us by providing the related code. It helps us in localizing the issue faster. Thanks!

**Comment by rishabhsahrawat** [comment]
Hi @ravikyram , thanks for your response. Which code exactly do you need?. Because it will consist code for the whole android app and also the python code for executing H5 model file. Thanks.

**Comment by am15h** [comment]
@rishabhsahrawat Are you sure that you are feeding the same input (which in your case might be word vectors) to TFLite Model as your H5 Model. I suspect that you are using different methods/dictionaries/word_embeddings to convert raw text to the form of input data in the two cases thats why your results are different although the input text is same. Providing related code will be very helpful.

**Comment by rishabhsahrawat** [comment]
@am15h yes, I am feeding the same input before pre-processing and after it I am receiving the exact output that I am receiving in Python. This pre-processed text is then fed to a dictionary consisting the words to Embedding layers vectors (since Embedding layer is not supported in TFLite). This mapping was in data type double but as TFlite model does not support Double so it was converted Float type, however I read that it does not affect the TFLite model's output. The vectors are then fed to the TFLite model which was saved without the embedding layer (first layer), this outputs probabilities for each class, ultimately giving classes.

Below are the codes:- 
1. 
`````
        // for removing stopwords
        val english_stopwords: List<String> = BufferedReader(InputStreamReader(context!!.assets.open("english.txt"))).readLines() //consisting stopwords
        tokens = ArrayList(tokens)
        tokens.removeAll(ArrayList(english_stopwords))
        // Getting POS Tags for Lemmatizer
        val pos_tags = posTaggerModel!!.tag(tokens.toTypedArray())
        // Lemmatization
        val lemmas = lemmatizerModel!!.lemmatize(tokens.toTypedArray(), pos_tags)
       // Stemming
        var stemmings = ArrayList<String>()
        for (inputString in lemmas.map { it.trim() }) {
            stemmings.add(stemmerModel!!.stem(inputString).toString())
        }

// For inferencing from TFLite model
    @Throws(IOException::class)
    private fun loadModelFile(): MappedByteBuffer {
        val MODEL_ASSETS_PATH = "CNNmodel4.tflite"
        val assetFileDescriptor = assets.openFd(MODEL_ASSETS_PATH)
        val fileInputStream = FileInputStream(assetFileDescriptor.fileDescriptor)
        val fileChannel = fileInputStream.channel
        val startoffset = assetFileDescriptor.startOffset
        val declaredLength = assetFileDescriptor.declaredLength
        return fileChannel.map(FileChannel.MapMode.READ_ONLY, startoffset, declaredLength)
    }
val interpreter = Interpreter(loadModelFile())
#INPUTS ARE PADDED TO MATCH THE EXACT SHAPE BEFORE FEEDING TO THE MODEL
interpreter.run(inputs, outputs) // Giving probabilities as outputs
`````

2. In Python
`````
def preprocess_fn(document_in):
  document_in = document_in.translate(str.maketrans(string.punctuation,' '*len(string.punctuation)))# removing punctuations with space
  document_in = document_in.split() #tokenization
  document_in = [doc_word.lower() for doc_word in document_in if doc_word not in stopwords.words('english')]
  document_in = [lemmer.lemmatize(token) for token in document_in]# moving 3rd -> 1st P and past, future -> present
  print ("Lemm: ",document_in)
  document_in = [snowstemmer.stem(wert) for wert in document_in]# stemming words to root
  print ("Stem: ",document_in)
  document_in = ' '.join(document_in)
  return document_in

encoder.encode(preprocess_fn(input_text_description)) // ENCODED INPUT TEXT
#INPUTS ARE PADDED TO MATCH THE EXACT SHAPE BEFORE FEEDING TO THE MODEL
model.predict(tf.expand_dims(input, 0), steps = 1)# Model prediction probs
`````

Please let me know if you require any other information @ravikyram  @ymodak . Thank you very much!

**Comment by rishabhsahrawat** [comment]
Any updates on this issue?

**Comment by jaeyoo** [comment]
Hi @rishabhsahrawat , I want to know more about your models. could you share "CNNmodel4.tflite"'s structure and the file "english.txt"?

**Comment by imaneBYD2020** [comment]
i get the same issues any help plz

**Comment by jaeyoo** [comment]
For now, I am not sure what the exact cause is because there was no response, but I want to say that upgrading to the latest TensorFlows (e.g. tf-nightly>=2.5 or tensorflow>=2.4) and check it again.

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.
