### ISSUE TITLE
CUDA libraries in a self created docker container

### ISSUE THREAD

**Issue by xentity** [tensorflow/tensorflow#35539]
** Base System information**
- Linux Ubuntu 18.04
- nvidia-docker: Docker version 19.03.5, build 633a0ea838
- nvidia driver via: `sudo apt-get install nvidia-driver-418`
- CUDA/cuDNN version: 10.1
- GPU model and memory:
```
$ nvidia-smi 
Thu Jan  2 12:08:27 2020       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 430.64       Driver Version: 430.64       CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GT 710      Off  | 00000000:AF:00.0 N/A |                  N/A |
| 40%   46C    P0    N/A /  N/A |      0MiB /  2002MiB |     N/A      Default |
+-------------------------------+----------------------+----------------------+
|   1  GeForce RTX 207...  Off  | 00000000:D8:00.0 Off |                  N/A |
| 34%   39C    P0     1W / 215W |      0MiB /  7982MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0                    Not Supported                                       |
+-----------------------------------------------------------------------------+
```

** Docker container information**
- Linux Ubuntu 18.04
- TensorFlow installed from: pip3
- TensorFlow version: 1.14.0
- Python version: 3.6.9
- CUDA/cuDNN version:
- GPU model and memory: nvidia-smi output (see above)
- my Dockerfile:
```
#https://www.tensorflow.org/install/gpu
FROM nvidia/cuda:10.0-base-ubuntu18.04

ENV PATH=/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/opt/conda/bin:$PATH
RUN apt-get update && apt-get upgrade -y && apt-get install -y \
        nodejs \
        npm \
        python3-pip \
        wget \
        libmysqlclient-dev \
        python-dev
#RUN wget -nv https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh && bash Miniconda3-latest-Linux-x86_64.sh -b -p /opt/conda && rm Miniconda3-latest-Lin$
RUN mkdir /etc/skel/notebooks
RUN npm install -g configurable-http-proxy && pip3 install \
        jupyterhub \
        jupyterhub-ldapauthenticator \
        jupyterlab \
        notebook \
        tensorflow-gpu
RUN pip3 install \
        folium \
        keras \
        matplotlib \
        mysql \
        mysql-connector \
        pandas \
        pymysql \
        seaborn \
        sklearn
VOLUME ["/home"]
RUN useradd -ms /bin/bash user -p "$(openssl passwd -1 test)"
COPY ./jupyterhub_config.py /etc/jupyterhub/jupyterhub_config.py
COPY ./jupyterhub_cookie_secret /etc/jupyterhub/jupyterhub_cookie_secret
COPY ./jupyterhub.sqlite /etc/jupyterhub/jupyterhub.sqlite
#CMD ["/usr/local/bin/jupyterhub", "upgrade-db", "--db=sqlite:////etc/jupyterhub/jupyterhub.sqlite"]
EXPOSE 8000
CMD ["/usr/local/bin/jupyterhub", "-f", "/etc/jupyterhub/jupyterhub_config.py", "--debug"]
```

**Describe the problem**

I created a Docker container based on the Dockerfile (see above) for a multiuser jupyterhub (with notebook and lab). The basics works fine, I can log in and use the desired python packages and running my projects. However, the container lacks the GPU capabiltites.

- container will be started by: `$ nvidia-docker run -d -p 8000:8000 --runtime=nvidia --restart unless-stopped --gpus all -v ~/myDocker/home:/home jupyterhub`
- `nvidia-smi` works within the container
- `device_lib.list_local_devices()` prints:
```[name: "/device:CPU:0"
device_type: "CPU"
memory_limit: 268435456
locality {
}
incarnation: 9710542890831123693
, name: "/device:XLA_GPU:0"
device_type: "XLA_GPU"
memory_limit: 17179869184
locality {
}
incarnation: 12724683280898329209
physical_device_desc: "device: XLA_GPU device"
, name: "/device:XLA_GPU:1"
device_type: "XLA_GPU"
memory_limit: 17179869184
locality {
}
incarnation: 12608392157467121046
physical_device_desc: "device: XLA_GPU device"
, name: "/device:XLA_CPU:0"
device_type: "XLA_CPU"
memory_limit: 17179869184
locality {
}
incarnation: 16188673672643731433
physical_device_desc: "device: XLA_CPU device"
]
```

- `from keras import backend as K
K.tensorflow_backend._get_available_gpus()` prints an empty field
- `tf.test.is_gpu_available()` says `False`

I can see that tensorflow is looking for the following ones and cannot find them:
- libcublas.so.10.0
- libcufft.so.10.0
- libcurand.so.10.0
- libcusolver.so.10.0
- libcusparse.so.10.0
- libcudnn.so.7

It is strange, I never installed nvidia-smi within the container, I seems to be deployed by docker, but necessary parts are missing for tensorflow. However, if I install CUDA or/and nvidia-toolkits and other software parts in the container, tensorflow is reporting about incorpatible versions:

```
2020-01-01 20:50:11.429852: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 AVX512F FMA
2020-01-01 20:50:11.466847: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcuda.so.1
2020-01-01 20:50:11.468037: E tensorflow/stream_executor/cuda/cuda_driver.cc:318] failed call to cuInit: CUDA_ERROR_SYSTEM_DRIVER_MISMATCH: system has unsupported display driver / cuda driver combination
2020-01-01 20:50:11.468085: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:169] retrieving CUDA diagnostic information for host: 9f9f93453aee
2020-01-01 20:50:11.468093: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:176] hostname: 9f9f93453aee
2020-01-01 20:50:11.468236: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:200] libcuda reported version is: 440.33.1
2020-01-01 20:50:11.468265: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:204] kernel reported version is: 430.64.0
2020-01-01 20:50:11.468285: E tensorflow/stream_executor/cuda/cuda_diagnostics.cc:313] kernel version 430.64.0 does not match DSO version 440.33.1 -- cannot find working devices in this configuration
2020-01-01 20:50:11.489100: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2100000000 Hz
2020-01-01 20:50:11.493082: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x4c12f30 executing computations on platform Host. Devices:
2020-01-01 20:50:11.493143: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): <undefined>, <undefined>
```
I do not think that it is an tensorflow issue. It is moreover the question, how to create an own docker container with tensorflow-gpu with CUDA support. Is the docker base image the right one?

**Comment by jnd77** [comment]
I use this Docker (from Nvidia as well), which takes care of pretty much everything:
https://docs.nvidia.com/deeplearning/frameworks/tensorflow-release-notes/running.html

Only thing required is to install the Nvidia drivers before launching the Docker ...

**Comment by gadagashwini** [comment]
@xentity, Please refer [Tensorflow doc](https://www.tensorflow.org/install/docker#gpu_support) for GPU support Tensorflow. Thanks!

**Comment by xentity** [comment]
@jnd77 thx for the hint, I'll have a look to this image as well.

@gadagashwini of course, I did read this page several times.

I made some progress:
- I had to extend the env: `ENV LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/cuda/lib64`
- since tensorflow is looking for different filenames, I had to link them: `ln -s /usr/local/cuda/lib64/libcufft.so.10 /usr/local/cuda/lib64/libcufft.so.10.0` as an example for all other libs mentioned in the error message above.

After that I realized that plain python can run it, but not on JupyterHub. After a lot of trying I realized JupyterHub knows no LD_LIBRARY_PATH (var is empty or not set), but this is necessary for TensorFlow, isn't it?. Some research showed me that it does not apply all envs from the system for security reasons. To solve it, I had to change my JupyterHub config:

```
#  This whitelist is used to ensure that sensitive information in the JupyterHub
#  process's environment (such as `CONFIGPROXY_AUTH_TOKEN`) is not passed to the
#  single-user server's process.
c.Spawner.env_keep = ['PATH', 'PYTHONPATH', 'CONDA_ROOT', 'CONDA_DEFAULT_ENV', 'VIRTUAL_ENV', 'LANG', 'LC_ALL', 'LD_LIBRARY_PATH']
```
This yielded into `['/job:localhost/replica:0/task:0/device:GPU:0']` when requesting keras for all GPUs. Yikes!

I tried to run some model fitting, but ran into this issue as well: https://github.com/tensorflow/tensorflow/issues/24828
The workaround is to place this snippet on top of the notebook:
```
config = ConfigProto()
config.gpu_options.allow_growth = True
session = InteractiveSession(config=config)
```
The fitting runs, approximately seven times fast with GPU. I'm just wondering that such fundamental points like the lib names (for TensorFlow) and the env var (for JupyterHub) are not generally solved.

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.
