### ISSUE TITLE
How to remove future warnings in tensorflow 2.0?

### ISSUE THREAD

**Issue by rajcivils** [tensorflow/tensorflow#35531]
Hello I am using tensorflow 2.0 and whenever I import tensorflow it gives me a future warning which is very long and annoying and does hides a big part of the output. I have tried many solutions from other issues but none of them work and I think almost all of them are for tf1.0. I have tried - 

```py
import logging
tf.get_logger().setLevel(logging.ERROR)
```
```py
import sys
original_stdout = sys.stdout
sys.stdout = None
```
```py
import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3' 
import tensorflow as tf
```
Also I have tried solutions from these issues - 
https://github.com/tensorflow/tensorflow/issues/8340
https://github.com/tensorflow/tensorflow/issues/7652
None of them work.

**Comment by oanush** [comment]
@rajcivils ,
Please try the solutions provided in these links [1](https://github.com/tensorflow/tensorflow/issues/8340#issuecomment-332212742) & [2](https://stackoverflow.com/questions/35911252/disable-tensorflow-debugging-information).Thanks!

**Comment by rajcivils** [comment]
@oanush None of them work

**Comment by oanush** [comment]
@rajcivils ,
Can you share a standalone code to reproduce the error faced by you?Thanks!

**Comment by rajcivils** [comment]
@oanush There is no error it is a warning

**Comment by rajcivils** [comment]
Hello I got the solution we need to only do this - 
```py
import warnings
warnings.filterwarnings("ignore")
import tensorflow as tf
```
