### ISSUE TITLE
Include file when building tensorflow 2.0 from source missing.

### ISSUE THREAD

**Issue by halsot** [tensorflow/tensorflow#35534]
When compiled, tensorflow2.0 outputs the libtensorflow_cc.so and libtensorflow_framework.so
Used: bazel build --config=opt  //tensorflow:libtensorflow_cc.so 
However there are no more genfiles where I was getting the include files to link to . In the tensorflow/cc/ops directory e.g. I am missing array_ops. There are many others missing. Before I could those from genfiles directory, now this folder is gone. Where can I get all the include files to compile my file with?
The alternative I think would be to use bazel build <my file>, however this takes too long to compile my file. I just want to use g++ to link with the above lib and the include files.
------------------------
OS: Linux Ubuntu 14.04 
Tensorflow 2.0 (master) installed from source
No Cuda
C++ API

**Comment by perfinion** [comment]
You can use `bazel build //tensorflow:install_headers` and it will collect all the headers needed for libtensorflow.so and libtensorflow_cc.so etc and put them in a dir, then you can `cp -R bazel-genfiles/tensorflow/include/* /usr/include/tensorflow/`

**Comment by halsot** [comment]
Thank you, is there some place you looked into the directory to know the command install_headers was needed with bazel build? If so, could you tell me, so that I can also compile third party tools like protobuf, google, etc. if need be without having to ask. Thanks again

**Comment by perfinion** [comment]
oh, i added the install_headers target to tensorflow a long time ago cuz I needed exactly this, so i knew its there ;). Its not a standardized bazel thing so I made a custom rule in tensorflow. There is this: https://github.com/bazelbuild/bazel/issues/5849 But nothing standardized for all packages to use yet.

**Comment by halsot** [comment]
Thank you, is there some place you looked into the directory to know the command install_headers was needed with bazel build? If so, could you tell me, so that I can also compile third party tools like protobuf, google, etc. if need be without having to ask. Thanks again
