### ISSUE TITLE
Fail to invoke tflite_runtime.interpreter

### ISSUE THREAD

**Issue by fmbao** [tensorflow/tensorflow#35532]
I'm trying to run the tflite_runtime.interpreter

However when I go to run the interpreter I get the following error:
`RuntimeError: tensorflow/lite/kernels/mfcc.cc:131 params->dct_coefficient_count != mfcc_output.size() (40 != 0)Node number 1 (Mfcc) failed to invoke.`

**Comment by fmbao** [comment]
定定定

**Comment by fmbao** [comment]
求帮忙

**Comment by fmbao** [comment]
不要沉啊啊啊啊啊

**Comment by ymodak** [comment]
duplicate #33857

**Comment by fmbao** [comment]
I solve the problem,thks

**Comment by ymodak** [comment]
Thanks. If you can please post your solution on this thread that will be great for the community.
