### ISSUE TITLE
lite/micro: Incorrectly copy quantization information from serialized data

### ISSUE THREAD

**Issue by apple11361** [tensorflow/tensorflow#35535]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 16.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below):
- Python version:
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source): gcc/c++ 5.4.0
- CUDA/cuDNN version:
- GPU model and memory:

**Describe the current behavior**
When micro allocator copies quantization information from serialized data in InitializeRuntimeTensor(), it copies 8 bytes for 'zero_point'. However, the size of 'zero_point' is 4 bytes, so the next member data('allocation_type') will be modified accidentally.

**Describe the expected behavior**
I think it should just copy 4 bytes for 'zero_point'.

**Code to reproduce the issue**
Any test case in tensorflow/lite/micro/examples/ can reproduce the issue.

**Other info / logs**
This is the fragment of bug code
```
  // This magic handles issues with little-endianness.
  for (unsigned int b = 0; b < sizeof(int64_t); ++b)
    *(reinterpret_cast<char*>(&result->params.zero_point) + b) =
        *(reinterpret_cast<const char*>(
          src_quantization->zero_point()->Data()) +
            b);
    result->params.zero_point =
      flatbuffers::EndianScalar(result->params.zero_point);
```
Screenshot below is a tensor before the code
![image](https://user-images.githubusercontent.com/11289375/71656049-b5562780-2d74-11ea-84ee-48cbe5b424b0.png)

Screenshot below is a tensor after the code
![image](https://user-images.githubusercontent.com/11289375/71656203-652b9500-2d75-11ea-8e35-8ff7810da4d1.png)

The quantization information should not modify the allocation_type. I think `sizeof(int64_t)` should be changed into `sizeof(result->params.zero_point)`

**Comment by njeffrie** [comment]
Thanks for reporting this issue.  I have created a patch to fix this internally, and it should merge in shortly.

**Comment by apple11361** [comment]
Hello, @njeffrie :
Thank you for your patch. However, I don't think the patch can resolve the issue. I want to know why the patch is that change `sizeof(int64_t)` into `sizeof(sizeof(result->params.zero_point))`. I think it doesn't make sense because the return type of `sizeof()` is `size_t` and the type of `params.zeor_point` is `int32_t`. In some machines, `sizeof(size_t)` is 8, that will overwrite memory allocation type. Why are there two `sizeof()`.

**Comment by njeffrie** [comment]
Oops, good catch!  Unintentionally added an additional sizeof there. Submitting patch to fix this.

**Comment by apple11361** [comment]
Thank you very much.
