### ISSUE TITLE
Different outputs using tensorflow.contrib.learn.Estimator.predict()

### ISSUE THREAD

**Issue by dzenteno2** [tensorflow/tensorflow#3554]
I trained a tensorflow model using skflow, but when I tried to predict some new value of my data, things didn't work. This is what is happening.

I have X, the matrix containing the observations.

When I run

`y_predicted = classifier.predict(X, batch_size=128)`

I'm interested in the output of indexes 855, 15035, 49536, 856, 857

so

`y_predicted['class'][(855, 15035, 49536, 856, 857), ]`

the results are exactly what I have expected

`array([0, 0, 0, 3, 3])`

Everything is fine up to here, but if I pass to predict function just the indexes of interest, the results are different. Here is an example:

`y_predicted = classifier.predict(X[(855, 15035, 49536, 856, 857), :], batch_size=128)`

Then, the output is wrong

`y_predicted['class']``

gives

`array([0, 0, 0, 2, 0])`

I tried several ways to do this, and I always get the wrong results.

Thank you.

**Comment by michaelisard** [comment]
This type of usage question is better suited to [StackOverflow](https://stackoverflow.com/questions/tagged/tensorflow). Please reopen if it turns out this is a TensorFlow bug.
