### ISSUE TITLE
“Cloud TPU” console spam on every TensorFlow import

### ISSUE THREAD

**Issue by wchargin** [tensorflow/tensorflow#35547]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): gLinux (like Debian)
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): `v1.12.1-21487-g2e8d5e5 2.1.0-dev20200102`
- Python version: Python 3.7.5rc1
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

**Describe the current behavior**

Importing TensorFlow prints an unnecessary and unhelpful warning:

> WARNING:tensorflow:Falling back to tensorflow client, its recommended to install the cloud tpu client directly with pip install cloud-tpu-client .

**Describe the expected behavior**

Importing TensorFlow should not print any messages about Cloud TPUs.
This is a normal desktop installation that doesn’t have anything to do
with TPUs, and doesn’t need them.

**Code to reproduce the issue**

```shell
python -c 'import tensorflow' 2>&1 | diff -u /dev/null -
```

**Other info / logs**

Likely introduced by 5364121e858b.

**Comment by frankchn** [comment]
Thanks for your report! It should be fixed starting with the nightly build tomorrow morning (`2.1.0-dev20200104`).

**Comment by wchargin** [comment]
Awesome; thanks! Thanks for fixing the grammar, too. :-)

**Comment by brando90** [comment]
> Thanks for your report! It should be fixed starting with the nightly build tomorrow morning (`2.1.0-dev20200104`).

what version of TensorFlow fixes this issue?

**Comment by Alexgolshtein** [comment]
Got the same info message on Tensorflow 2.4.1.
