### ISSUE TITLE
set_floatx('float16') slow to build/compile

### ISSUE THREAD

**Issue by arthurflor23** [tensorflow/tensorflow#35553]
**System information**
Google Colab system (GPU mode) with TensorFlow 2.1-rc2 and Python 3.

**Describe the current behavior**
Take a long time to build/compile a seq2seq model when use ``set_floatx('float16')`` instead float32 (default)

**Describe the expected behavior**
I don't know if is normal, but default value ``float32`` takes 1-2 second

**Code to reproduce the issue**
I coded an example [here](https://drive.google.com/open?id=170KpjIGFmNNt-SS-6oXgVbRnZR4-7ah_)

**Comment by ravikyram** [comment]
I have tried on colab with TF version 2.1-rc2 and was able to reproduce the issue.Thanks!

**Comment by jvishnuvardhan** [comment]
@arthurflor23 I agree with you. Setting `float16` as default dtype is taking long time. However, it is not recommend to use `float16` as it could result in numerical instability. There is a note on TF website about that. Please check [here](https://www.tensorflow.org/api_docs/python/tf/keras/backend/set_floatx).

> Note: It is not recommended to set this to float16 for training, as this will likely cause numeric stability issues. Instead, mixed precision, which is using a mix of float16 and float32, can be used by calling tf.keras.mixed_precision.experimental.set_policy('mixed_float16'). See the mixed precision guide for details. 

You could try with `float64` which takes ~2 sec as shown in this [gist](https://colab.research.google.com/gist/jvishnuvardhan/6cb4ebed8b8f2d97424ebe1cffe9e62b/set_floatx-float16.ipynb
). Lot of ops have `floatt32` as default dtype. Thanks!

**Comment by arthurflor23** [comment]
Wow, thanks a lot, I didn't know about the numerical instability!
