### ISSUE TITLE
Line break missing in tf.keras.Model.fit() documentation

### ISSUE THREAD

**Issue by bersbersbers** [tensorflow/tensorflow#35557]
## URL(s) with the issue:
https://www.tensorflow.org/api_docs/python/tf/keras/Model?version=stable

## Description of issue (what needs changing):
In the `validation_data` part of `Model.fit()`, the third alternative reads
> dataset For the first two cases, `batch_size` must be provided. For the last case, `validation_steps` must be provided.

I feel a link break should be inserted after "dataset".

**Comment by bersbersbers** [comment]
In addition, I am not even sure that 
> For the first two cases, `batch_size` must be provided
is correct, because
> If unspecified, `batch_size` will default to 32.

**Comment by ManishAradwad** [comment]
I'll be glad to do this one!!

**Comment by ManishAradwad** [comment]
Can I take this issue?

**Comment by ymodak** [comment]
Thanks. This is fixed in tf nightly version and we can expect it in next stable release.
See https://www.tensorflow.org/api_docs/python/tf/keras/Model?version=nightly#arguments_3

**Comment by bersbersbers** [comment]
Sorry for the late response. Again, this statement
> If unspecified, `batch_size` will default to 32.

implies that this statement

> For the first two cases, `batch_size` must be provided.

is maybe incorrect.

Also, why is the whole text
> For the first two cases, `batch_size` must be provided.
> For the last case, `validation_steps` could be provided.

in a code block?
