### ISSUE TITLE
Typo Errors in `l05c03_exercise_flowers_with_data_augmentation.ipynb`

### ISSUE THREAD

**Issue by ManishAradwad** [tensorflow/tensorflow#35565]
## URL(s) with the issue:

https://github.com/tensorflow/examples/blob/master/courses/udacity_intro_to_tensorflow_for_deep_learning/l05c03_exercise_flowers_with_data_augmentation.ipynb

## Description of issue (what needs changing):

In the directory structure, it should be "daisy" instead of "diasy"

![Screenshot from 2020-01-03 18-39-11](https://user-images.githubusercontent.com/29497701/71725075-a8aaff80-2e58-11ea-9ac8-076078500026.png)

### Submit a pull request?

Yes

**Comment by ymodak** [comment]
Closing since the associated PR has been merged. Thanks!
