### ISSUE TITLE
PEM routines:OPENSSL_internal:NO_START_LINE

### ISSUE THREAD

**Issue by LyraWang** [tensorflow/tensorflow#35562]
Actually  this is not a tensorflow problem. I had a project my own, it run well. But it comes to an runtime error when I link it to the the tensorflow_framework.so, even I didn't change any codes of my project(it doesn't include any of tensoflow headers).  It seems related to openssl certification, but it's hard to trace where the collapse occurred. Is there anybody can help me? Thanks very much!

**System information**
...
terminate called after throwing an instance of 'std::runtime_error'
  what():  Unable to parse cert 1: error:0900006e:PEM routines:OPENSSL_internal:NO_START_LINE
*** Aborted at 1578043256 (unix time) try "date -d @1578043256" if you are using GNU date ***
PC: @     0x7ffb9e4b8e97 gsignal
*** SIGABRT (@0x3e800006475) received by PID 25717 (TID 0x7ffbaa404500) from PID 25717; stack trace: ***
    @     0x7ffba03c7890 (unknown)
    @     0x7ffb9e4b8e97 gsignal
    @     0x7ffb9e4ba801 abort
    @     0x7ffb9eead957 (unknown)
    @     0x7ffb9eeb3ab6 (unknown)
    @     0x7ffb9eeb3af1 std::terminate()
    @     0x7ffb9eeb3d24 __cxa_throw
    @     0x555e5286eea7 (unknown)
    @     0x555e5272d044 (unknown)
    @     0x555e5272d342 (unknown)
    @     0x555e5245ec1c (unknown)
    @     0x555e52479c7e (unknown)
    @     0x555e52479e98 (unknown)
    @     0x555e5244452e (unknown)
    @     0x7ffb9e49bb97 __libc_start_main
    @     0x555e52449dea (unknown)

version: tensorflow 1.14.0

**Comment by mihaimaruseac** [comment]
Can you try with TF1.15, TF2.0, latest nightly, and/or build from `master`?

1.14 is old and there are some issues with the way it was released.

**Comment by amahendrakar** [comment]
> Can you try with TF1.15, TF2.0, latest nightly, and/or build from `master`?

@LyraWang,
Any updates regarding this? Could you please check the above comment and let us know if this is still an issue? Thanks!
