### ISSUE TITLE
tflite_runtime interpreter.py NOT ImplementedError

### ISSUE THREAD

**Issue by Celt1967** [tensorflow/tensorflow#35564]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Raspbian Buster
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) Raspberry Pi 4B
- TensorFlow installed from (source or binary): Source
- TensorFlow version: 1.14
- Python version:3.7
- Installed using virtualenv? pip? conda?: Pip within virtual environment
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

Installed Tesnorflow Lite Runtime from the instructions in Python Quickstart using tflite_runtime-1.14.0-cp37-cp37m-linux_armv7l.whl.

On executing the following command:

python label_image.py   --model_file /home/pi/mobilenet_v1_1.0_224.tflite   --label_file /home/pi/labels.txt   --image /tmp/grace_hopper.bmp

I get:

2020-01-03 11:20:05.640880: E tensorflow/core/platform/hadoop/hadoop_file_system.cc:132] HadoopFileSystem load error: libhdfs.so: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "label_image.py", line 63, in <module>
    interpreter = tflite.Interpreter(model_path=args.model_file)
  File "/home/pi/.virtualenvs/HOLLY/lib/python3.7/site-packages/tflite_runtime/interpreter.py", line 206, in __init__
    model_path))
NotImplementedError: Wrong number or type of arguments for overloaded function 'InterpreterWrapper_CreateWrapperCPPFromFile'.
  Possible C/C++ prototypes are:
    tflite::interpreter_wrapper::InterpreterWrapper::CreateWrapperCPPFromFile(char const *,std::vector< std::string > const &,std::string *)
    tflite::interpreter_wrapper::InterpreterWrapper::tflite_interpreter_wrapper_InterpreterWrapper_CreateWrapperCPPFromFile__SWIG_1(char const *,PyObject *)

Very new to GitHub and Tensorflow so appologies if im miss posting or not providing enough info but i'm a bit stuck on how to resolve this.

Many thanks

Eifion

**Comment by Celt1967** [comment]
I have now been able to run the label_image.py.  The issue seems to be that i had installed tflite_runtime following the instructions given and also Tensorflow 1.14 which.  TFLite has a version of interpreter.py which works and Tensorflow _core also has a differeent version of interpreter.py in a folder.  The system seems to default to using the Tensorflow version which does not seem to work in my system as described above.

My solution for now was to rename the interpreter.py in the Tensorflow 1.14 Lite folder.  Not sure if this will cause further issues ?

**Comment by jvishnuvardhan** [comment]
@Celt1967 There were some known bugs in `TF1.14`. Can you please try `TF1.15` or `TF2.0` and let us know whether the issue persists in the newer versions? Thanks!

**Comment by jvishnuvardhan** [comment]
@Celt1967 Did you had time to test with latest versions of TF as mentioned in my last response? Thanks!

**Comment by jvishnuvardhan** [comment]
Closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Comment by Celt1967** [comment]
Sorry for not getting back.  Yes installing Tensorflow 2.0.0 solved the issue.  Thanks.  Although installing Tensorflow 2 on a Raspberry Pi was another challenge.

**Comment by chenpengf0223** [comment]
TF2.1.0 also has the issue... I try it on a linux.
