### ISSUE TITLE
tensorflow 2.0.0 crashes with protobuf 3.10.1 on macOS

### ISSUE THREAD

**Issue by essandess** [tensorflow/tensorflow#35573]
Using MacPorts with the latest up-to-date versions (tensorflow 2.0.0, protobuf 3.10.1),

> `python3 -c 'import tensorflow'`
```
[libprotobuf ERROR google/protobuf/descriptor_database.cc:394] Invalid file descriptor data passed to EncodedDescriptorDatabase::Add().
[libprotobuf FATAL google/protobuf/descriptor.cc:1359] CHECK failed: GeneratedDatabase()->Add(encoded_file_descriptor, size): 
libc++abi.dylib: terminating with uncaught exception of type google::protobuf::FatalException: CHECK failed: GeneratedDatabase()->Add(encoded_file_descriptor, size): 
Abort trap: 6
```

This is reported and closed in https://github.com/tensorflow/tensorboard/issues/2985, but the issue persists.

A workaround is `pip-3.7 install protobuf==3.8`, but this doesn't work with system-level, up-to-date library installs like with MacPorts. Also see: https://trac.macports.org/ticket/59826

Is this an issue with TF, or with protobuf?

**Comment by gunan** [comment]
Are you installing TF through macports or pip.
Unless macports just fetches the package from what we are building, it may be built with different flags, causing all kinds of ABI issues.
Similar for protobuf. If these are packages not built by us, I do not think we can do much to help.

**Comment by essandess** [comment]
Good point. The issue isn't reproducible with a pip install, so it's some MacPorts flag or related issue.

I'll try to produce a clean, working build on macOS and reflect the working steps in a Portfile.

**Comment by SARCASMOOO** [comment]
Another thing you can try is to install an older version of libprotobuf and *protobuf. I had the same issue but I was using anaconda. I went from version 3.10.1 to version 3.8.0. After doing this it started working. Not sure if this is because I unistalled and reinstalled thoughs pakcages or if it was a version issue.

**Comment by anton-matosov** [comment]
I experience the same issue if I install tensorflow from conda, which gets libprotobuf 3.11.1
Workaround of `protobuf==3.8` suggested here worked for me on conda as well.

**Comment by Theoda** [comment]
I got the same error after `pip3 install tensorflow`, but solved simply through:
```shell
pip3 uninstall protobuf
pip3 install protobuf
```
The latest protobuf 3.11.3 works fine.

**Comment by beannguyen** [comment]
> I experience the same issue if I install tensorflow from conda, which gets libprotobuf 3.11.1
> Workaround of `protobuf==3.8` suggested here worked for me on conda as well.

It works with protobuf 3.8. Thank you.

**Comment by KaisJM** [comment]
had a similar issue when loading Tensorboard in a jupyter notebook. uninstalling protobuf 3.11.2 and installing protobuf==3.8 worked. protobuff==3.11.3 did NOT work.

**Comment by museum-future** [comment]
I got the same error using tensorboard with conda and tf 1.15, have to downgrade protobuf to 3.8

**Comment by tobegit3hub** [comment]
We get this warning when running TensorFlow 2.1 when downgrading protobuf to 3.8. This will work for protobuf 3.8 but not 3.11.

```
ERROR: tensorflow 2.1.0 has requirement protobuf>=3.9.2, but you'll have protobuf 3.8.0 which is incompatible.
```

**Comment by youwithouto** [comment]
I got the same issue after install `2.2.0-rc3` from source with `protobuf@3.11.1` on a Mac.

@theoda 's solution resolve my issue which updated protobuf to `3.11.3`

**Comment by mihaimaruseac** [comment]
Unfortunately we are too tied in with the protobuf version, so you have to use the exact same version as the one TF was built with.

**Comment by jianfeifeng** [comment]
it doesn't work for tf-2.0.0 and protobuf-3.8.0, and i have tried many versions for tf and protobuf , but this error still exists. Which one can tell me the exactly reason and the solution for this problem?

**Comment by tjan90** [comment]
python 3.6, Tf 2.2.0, protobuf 3.12.1. Stil doesnt work, tried many other other of both tf and protobuf but no success. 
Using Pycharm and working in venv

**Comment by baaj2109** [comment]
downgrade onnx to 1.6.0 work for me.

**Comment by elsieyin** [comment]
> It doesn't work for tf-2.0.0 and protobuf-3.8.0, and i have tried many versions for tf and protobuf , but this error still exists. Which one can tell me the exactly reason and the solution for this problem?

I got the same error, and use tf2.0.0 and protobuf 3.6, seems solved

**Comment by jvishnuvardhan** [comment]
@essandess Looks like this was resolved. Can you please confirm whether this is still an issue with recent TF version? Thanks!

**Comment by essandess** [comment]
Yes, thank you, resolved with TF 2.5.0 and protobuf 3.17.0.

**Comment by jvishnuvardhan** [comment]
Closing this issue as this was resolved. Thanks!

**Comment by sumit-jr** [comment]
<img width="827" alt="Screenshot 2023-06-22 at 10 07 17" src="https://github.com/tensorflow/tensorflow/assets/81641001/387eb2ab-70e9-4315-9649-6f736e458e0a">


I Still got the same error.
Help me to fix this

**Comment by mihaimaruseac** [comment]
Please open a new issue, this issues has been closed 3 years ago.
