### ISSUE TITLE
TensorRT 6.0.1 performs worse than TensorRT 5.1.6 on Jetson AGX Xavier

### ISSUE THREAD

**Issue by doruksonmez** [tensorflow/tensorflow#35583]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Jetpack 4.3 (L4T 32.3.1 Ubuntu 18.04)
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): Nvidia Official Wheel
- TensorFlow version (use command below): 1.13.1 & 1.15.0
- Python version: 3.6
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 10.0.326 / 7.5.0 & 7.6.3
- GPU model and memory: Tegra Xavier 16 GB

**Describe the current behavior**
I am currently trying some examples within from docker containers on new release of Jetpack (4.3). I wanted to do some benchmarkings and compare TensorRT 6.0.1 and cuDNN 7.6.3 versions with the old ones (5.1.6 and 7.5.0 respectively). I have some issues regarding to this as follows;

1. **24 FPS** with --> protobuf=3.6.1, tensorflow-gpu=1.13.1+nv19.3, tensorrt=5.1.6, cudnn=7.5.0 opencv=3.3.1
2. **9.6 FPS** with --> protobuf=3.8.0, tensorflow-gpu=1.15.0+nv19.11, tensorrt=6.0.1, cudnn=7.6.3, opencv=4.1.1
3. **8.5 FPS** with --> protobuf=3.6.1, tensorflow-gpu=1.15.0+nv19.11, tensorrt=6.0.1, cudnn=7.6.3, opencv=4.1.1
4. **6.5 FPS** with --> protobuf=3.6.1, tensorflow-gpu=1.15.0+nv19.11, tensorrt=5.1.6, cudnn=7.5.0, opencv=3.4.6

**Describe the expected behavior**
Improved inference performance (above 24 FPS) with the new versions of Tensorflow, cuDNN and TensorRT

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.
https://github.com/jkjung-avt/tf_trt_models --> `python3 camera_tf_trt.py --usb --model ssd_mobilenet_v1_coco --build`

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

I've created a [topic](https://devtalk.nvidia.com/default/topic/1069238/jetson-agx-xavier/tensorrt-6-0-1-performs-worse-than-tensorrt-5-1-6-on-jetson-agx-xavier/) on Nvidia DevTalk forum and here is the answer I got from Nvidia people: [DevTalk forum comment](https://devtalk.nvidia.com/default/topic/1069238/jetson-agx-xavier/tensorrt-6-0-1-performs-worse-than-tensorrt-5-1-6-on-jetson-agx-xavier/post/5416335/#5416335)

**Comment by doruksonmez** [comment]
Another benchmark;

5. 21 FPS with --> protobuf=3.6.1, tensorflow-gpu=1.13.1+nv19.03, tensorrt=5.1.6, cudnn=7.6.3, opencv=4.1.1

**Comment by sanjoy** [comment]
CC @DEKHTIARJonathan

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.
