### ISSUE TITLE
Looking to install 1.15 C++ 

### ISSUE THREAD

**Issue by DaveBGld** [tensorflow/tensorflow#35587]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: NO
- TensorFlow installed from (source or binary): source
- TensorFlow version: 1.15.0
- Python version: 3.6.9
- Installed using virtualenv? pip? conda?: virtualenv
- Bazel version (if compiling from source): 0.26.1
- GCC/Compiler version (if compiling from source): 7.4.0
- CUDA/cuDNN version: 10.0.326
- GPU model and memory: 1080ti 11MB

**Describe the problem**

Build command:

`bazel build -c opt --jobs 32 --copt=-mavx --copt=-mavx2 --copt=-mfma --copt=-mfpmath=both --copt=-msse4.1 --copt=-msse4.2 -k //tensorflow/tools/pip_package:build_pip_package --cxxopt="-D_GLIBCXX_USE_CXX11_ABI=0" --define=grpc_no_ares=true
`

Completed the build with bazel, and want to produce the libraries and includes to install in my system, but I'm unable to find anywhere ()many years experience with CMAKE, 0 with bazel).

I found [https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/lib_package/README.md](url) for C (NOT what I'm looking for but wanted to get started with something..), and ran the command instructed there

`bazel test --config opt //tensorflow/tools/lib_package:libtensorflow_test`

But returns 

`ERROR: Config value opt is not defined in any .rc file`

But the real question is how do I install tensorflow 1.15 C++ 

Many thanks!!

**Comment by DaveBGld** [comment]
Although I didn't find any documetation for building a standalone c++ install, I found a solution here:

[https://stackoverflow.com/questions/33620794/how-to-build-and-use-google-tensorflow-c-api](url)

`bazel build //tensorflow:libtensorflow_cc.so --config=monolithic`

But that results in error:
 
`Config value monolithic is not defined in any .rc file`

I'm using OpenCV hence the need for `config=monolithic`.

I opened a separate issue for this other problem, but since I don't have an official source on how to produce the c++ standalone, I am leaving this one here also, since they seem to be different issues.

Many thanks for any helo!

Dave

**Comment by ymodak** [comment]
Did you configure the build with `./configure` option before building?
https://www.tensorflow.org/install/source#configure_the_build

**Comment by DaveBGld** [comment]
Hi Yasir thanks for your reply!

This is four projects ago....   Looking at my project log, what I did then after being stuck with this TF problem was to create the model  on Pytrorch docker exported to ONNX  and converted that to TensorRT on the edge computer. Inference is running on TensorRT quite well...

Have used Pytorch since.

Thanks
