### ISSUE TITLE
[sparkfun-tensorflow-codelab] - Update Code

### ISSUE THREAD

**Issue by GantMan** [tensorflow/tensorflow#35594]
The codelab still links to the experimental folder for the makefile, which is incorrect.

Visual:
![image](https://user-images.githubusercontent.com/997157/71787651-3bc27180-2fe0-11ea-8318-424dc887efc5.png)

Update the codelab at this link https://codelabs.developers.google.com/codelabs/sparkfun-tensorflow/#3

Code should read:
```
make -f tensorflow/lite/micro/tools/make/Makefile \                                    
TARGET=sparkfun_edge micro_speech_bin
```

## URL(s) with the issue:
https://codelabs.developers.google.com/codelabs/sparkfun-tensorflow/#3

**Comment by perfinion** [comment]
@petewarden is this the right place for bugs for codelabs like that?

**Comment by GantMan** [comment]
If there's any way I can do a PR to fix this, let me know.

**Comment by rohanreddych** [comment]
@GantMan  This is not the correct place for codelabs. At the bottom left side of the page there is a link to `Report a mistake`,  you can close this issue and do it there itself.

**Comment by ymodak** [comment]
The codelab is now updated with the changes mentioned upstream. Thanks!
https://codelabs.developers.google.com/codelabs/sparkfun-tensorflow/#3
