### ISSUE TITLE
Can I add a py_func to a queue?

### ISSUE THREAD

**Issue by alexgkendall** [tensorflow/tensorflow#3559]
Is it possible to add a custom py_func to load non-image data in a FIFOQueue? It appears that the Queue does not support py_func objects. Specifically can you enqueue a py_func object? When trying this Tensor Flow gives the following error:

`tensorflow/core/framework/op_kernel.cc:909] Unimplemented: Unsupported object type Tensor`

I've tried calling `set_shape` on the `py_func` output

**Comment by michaelisard** [comment]
Sorry I am not understanding immediately. Are you asking whether or not you can use higher-order functions, i.e. send functions down a queue, and then dequeue and apply them? Or are you asking if you can process images from a queue with a custom processor?

**Comment by alexgkendall** [comment]
Yes I'd like to process other data (such as 16-bit png images and .npy files) from a queue with a custom processor. 

Ideally I'd like to avoid using TFRecord as an intermediate format.

**Comment by michaelisard** [comment]
You could encode arbitrary data into a string tensor and send the string tensor into the queue, then process the strings at the other end with a custom function. I'm still not sure I'm understanding though: is the queue relevant, or are you just asking how to store and process binary data in tensors?

If this is a usage question it's probably better suited to [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow): this forum is intended for TensorFlow bugs and installation issues.
