### ISSUE TITLE
translate: unrecognized option --data_dir

### ISSUE THREAD

**Issue by markusdr** [tensorflow/tensorflow#356]
I tried the 'translate' command described in the tutorial (http://www.tensorflow.org/tutorials/seq2seq/index.html#run_it). But it threw an error:

    $ bazel run -c opt tensorflow/models/rnn/translate:translate --data_dir /tmp/data --train_dir /tmp/train  
    Unrecognized option: --data_dir 

For the records, this worked instead:

    $ bazel build -c opt --config=cuda tensorflow/models/rnn/translate:translate            
    $ bazel-bin/tensorflow/models/rnn/translate/translate --data_dir /tmp/data --train_dir /tmp/train

**Comment by vrv** [comment]
I think there's a missing '--' after "tensorflow/models/rnn/translate:translate".  We'll fix it soon!

**Comment by vrv** [comment]
I believe this was fixed a few weeks ago.
