### ISSUE TITLE
Beginner models

### ISSUE THREAD

**Issue by generationzcode** [tensorflow/tensorflow#35608]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using):2.0
- Are you willing to contribute it (Yes/No):Yes

**Describe the feature and the current behavior/state.**
perfectly normal
**Will this change the current api? How?**
Yes. The beginner models can be a different api in tensorflow itself. Like `tf.BeginnerModel`.
**Who will benefit with this feature?**
Beginners in machine learning who want to write less code and acheive a lot
**Any Other info.**
This will make it easier to use tensorflow as a beginner

**Comment by ymodak** [comment]
For beginners: The best place to start is with the user-friendly Sequential API. You can create models by plugging together building blocks.
See https://www.tensorflow.org/overview and https://colab.sandbox.google.com/github/tensorflow/docs/blob/master/site/en/tutorials/quickstart/beginner.ipynb

**Comment by generationXcode** [comment]
Thats one way to look at it, but another way is that absolute beginners to this topic will want to see some quick results as well. Maybe they don't know coding that well, or they want to try it out before getting their hands dirrty with relatively tougher methods of making models (`tf.Sequential`)

**Comment by WilliamHYZhang** [comment]
What part of using `tf.Sequential` is relatively tough?

**Comment by generationXcode** [comment]
@WilliamHYZhang  Good question... I think beginners would like to start off by getting results quickly to see how cool and powerful this technologie is. But in tf.Sequential you have to explicitly state all the layers in the model, the optimizer, the activation and many other things. These would be very confusing to a beginner who might not know much about this field. It would also give them the satisfaction of knowing that they didn't copy and paste everything from the tutorial.😊🖖

**Comment by ymodak** [comment]
We have added a variety of new tutorials for beginners.
You may try ML basics with Keras that covers a variety of concepts.
See https://www.tensorflow.org/tutorials
Thanks!
