### ISSUE TITLE
Census tutorial documentation refers to Python 2, but code uses Python 3

### ISSUE THREAD

**Issue by fdb** [tensorflow/tensorflow#35602]
## URL(s) with the issue:

https://www.tensorflow.org/tfx/tutorials/transform/census#python_check_imports_and_globals

## Description of issue (what needs changing):

The text says "First we'll make sure that we're using Python 2, and then go ahead and install and import the stuff we need." but the code below indicates we need to use Python 3.

### Clear description

The text states:

> First we'll make sure that we're using Python 2, and then go ahead and install and import the stuff we need.

The code example says:

```python
import sys

# Confirm that we're using Python 3
assert sys.version_info.major is 3, 'Oops, not running Python 3. Use Runtime > Change runtime type'
```

**Comment by ravikyram** [comment]
@fdb 

This issue is more suitable for TensorFlow Extended (TFX) repo.Please post it on TFX repo from [here](https://github.com/tensorflow/tfx/issues).Thanks!

**Comment by abhiverma1924** [comment]
@fdb In the given URL of the issue only python 3 is mentioned. If I am wrong do mention the line number you are talking about, Thanks.

**Comment by ravikyram** [comment]
@fdb 
Can we close this issue here and track the issue in TFX repo. Please, confirm. Thanks!

**Comment by ravikyram** [comment]
@fdb 

Automatically closing due to lack of recent activity. I believe you have raised issue in TFX repo and tracking the issue in TFX repo. Thanks!
