### ISSUE TITLE
Request Adding Ops in Tensorflow Lite ：RandomUniform

### ISSUE THREAD

**Issue by aijiart** [tensorflow/tensorflow#35605]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- TensorFlow installed from (source or binary):
- TensorFlow version (or github SHA if from source):

**Provide the text output from tflite_convert**

```
# Copy and paste here
Some of the operators in the model are not supported by the standard TensorFlow Lite runtime and are not recognized by TensorFlow. If you have a custom implementation for them you can disable this error with --allow_custom_ops, or by setting allow_custom_ops=True when calling tf.lite.TFLiteConverter(). Here is a list of builtin operators you are using: ADD, CONCATENATION, CONV_2D, DIV, FLOOR, MAX_POOL_2D, MUL, RESHAPE, SPLIT, SUB, TRANSPOSE_CONV. Here is a list of operators for which you will need custom implementations: RandomUniform.
```

Also, please include a link to a GraphDef or the model if possible.

**Any other info / logs**

Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by ymodak** [comment]
You may try converting your model using `Select TensorFlow Ops`. This should help you to avoid custom implementation for `RandomUniform`. 
See https://www.tensorflow.org/lite/guide/ops_select#converting_the_model

**Comment by jvishnuvardhan** [comment]
@aijiart Can you please share a standalone code to reproduce the issue. Did you try adding `converter.allow_custom_ops = True` to enable custom ops in the `tf.lite`? Thanks!

**Comment by aijiart** [comment]
> @aijiart Can you please share a standalone code to reproduce the issue. Did you try adding `converter.allow_custom_ops = True` to enable custom ops in the `tf.lite`? Thanks!

Thank. I have tried the step you point out, but I shouldn't test the tflite model directly in python. Because the tflite Interpreter can't process the tensorflow ops just now.

**Comment by aijiart** [comment]
> You may try converting your model using `Select TensorFlow Ops`. This should help you to avoid custom implementation for `RandomUniform`.
> See https://www.tensorflow.org/lite/guide/ops_select#converting_the_model

Thanks a lot.  Problem sovled~
