### ISSUE TITLE
log1pexp

### ISSUE THREAD

**Issue by cossio** [tensorflow/tensorflow#35606]
**System information**
- TensorFlow version (you are using): 2.0
- Are you willing to contribute it (Yes/No): -

**Describe the feature and the current behavior/state.**

Please add `log1pexp(x)` function to math. This computes `log(1 + exp(x)` in a numerically stable way. Here is a Python implementation that I am currently using:

```
@tf.function
def log1pexp(x):
    return tf.where(tf.less(x, 9),
                    tf.math.log1p(tf.exp(x)),
                    tf.where(tf.less(x, 16),
                             x + tf.math.exp(-x),
                             x))
```

But a native C version will probably be faster.

**Who will benefit with this feature?**

This function is useful when programming RBM models, for instance. But it has many other uses.

**Comment by pshiko** [comment]
@cossio
you can use `tf.math.softplus` function! 🎉 
https://www.tensorflow.org/api_docs/python/tf/math/softplus?version=stable

**Comment by cossio** [comment]
@pshiko Thanks! I guess I was used to looking for this under the name `log1pexp`.
