### ISSUE TITLE
erfcx special function

### ISSUE THREAD

**Issue by cossio** [tensorflow/tensorflow#35617]
**System information**
- TensorFlow version (you are using): 2.0
- Are you willing to contribute it (Yes/No): -

**Describe the feature and the current behavior/state.**

I would like to see the `erfcx(x) = exp(x**2) * erfc(x)` function (e.g., `scipy.special.erfcx`) implemented in Tensorflow. The naive implementation `exp(x**2) * erfc(x)` fails for large `x`.

This is useful when one needs to work with truncated normal distributions. 

`erfcx` is available in many numerical packages, such as [Matlab](https://www.mathworks.com/help/matlab/ref/erfcx.html), [Julia](https://juliamath.github.io/SpecialFunctions.jl/latest/functions_list/#SpecialFunctions.erfcx), [SciPy](https://docs.scipy.org/doc/scipy/reference/generated/scipy.special.erfcx.html) [R](https://www.rdocumentation.org/packages/pracma/versions/1.9.9/topics/erf), and others.

An alternative is to implement `log_erfc(x) = log(erfc(x))`, from which one can obtain `erfcx(x)` accurately. The function `log_erfc(x)` is implemented in [GSL](https://github.com/ampl/gsl/blob/644e768630841bd085cb7121085a688c4ff424d0/specfunc/erfc.c#L441).

**Who will benefit with this feature?**

Anyone working with truncated normal distributions.

**Comment by cossio** [comment]
In the meantime is there a workaround to use this function? Hopefully without degrading performance too much. Note that I intend to run this model on the cpu only, so maybe that helps.

**Comment by cossio** [comment]
One thing I tried is this:

```python
@tf.function
def erfcx1(x):
    return tf.convert_to_tensor(scipy.special.erfcx(A))

def erfcx2(x):
    return tf.convert_to_tensor(scipy.special.erfcx(A))
```

Interestingly, the `@tf.function` annotation here seems to degrade performance:

```python
A = tf.random.uniform((50,60))
%timeit erfcx1(A) # 95 µs ± 12.8 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)
%timeit erfcx2(A) # 63.9 µs ± 6.07 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)
```

Why?

**Comment by gowthamkpr** [comment]
@cossio  I checked it in tf-nightly and the performance is low if we decorate the function with tf-nightly

**Comment by cossio** [comment]
@gowthamkpr Thanks. Is there a PR to look at?

**Comment by mayou36** [comment]
@cossio the decorated function won't work as expected: this just remembers each Python input and rebuilds the graph. I recommend to read up on this e.g. [here](https://www.tensorflow.org/guide/function). Actually, try to put in a tensor, not a Python number and the decorated should fail.

erfcx was though added now in the nightlies

**Comment by rmothukuru** [comment]
@cossio,
[tfp.math.erfcx ](https://www.tensorflow.org/probability/api_docs/python/tfp/math/erfcx) is available now. The [documentation](https://www.tensorflow.org/probability/api_docs/python/tfp/math/erfcx) states:

> Note: This API is new and only available via pip install tfp-nightly.

Thank you @mayou36 for pointing it out.

**Comment by mayou36** [comment]
Just to add, there is the difference that this does not (yet) work for complex arguments (but this is WIP: https://github.com/tensorflow/probability/issues/1265)

**Comment by cossio** [comment]
Bump

**Comment by rmothukuru** [comment]
@cossio,
As per [this comment](https://github.com/tensorflow/tensorflow/issues/35617#issuecomment-829345082), this issue is related to **`Tensorflow Probability`**, not actual **`Tensorflow`**. Can we close this issue as it is being tracked in [TF Probability Repo](https://github.com/tensorflow/probability/issues/1265)? Thanks!

**Comment by cossio** [comment]
Closed in favor of https://github.com/tensorflow/probability/issues/1265
