### ISSUE TITLE
Segmentation fault when inferencing in C++

### ISSUE THREAD

**Issue by dawgster** [tensorflow/tensorflow#35614]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
 Linux Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
/
- TensorFlow installed from (source or binary):
source
- TensorFlow version (use command below):
2.1
- Python version:
3.6.9
- Bazel version (if compiling from source):
bazel 0.27.2
- GCC/Compiler version (if compiling from source):
gcc 8.3.0
- CUDA/cuDNN version:
10.1
- GPU model and memory:
gtx 950m

**Describe the current behavior**
I have trained a model (sub-classed keras.Model) and saved it via the SavedModel-API in Python.
I want to include this model in a c++ program. To this end, I have compiled the tensorflow_cc library and linked it to my project by using:

`bazel build --config=opt --config=cuda //tensorflow:libtensorflow_cc.so`

In c++, I can load the model, but upon running the session for inference, the program suffers a segmentation fault. I have done this in a similar manner before, but not since moving to eager execution. My model's call method is decorated with @tf.function. Unfortunately, I am unable to provide further details since I can't build tensorflow with debug symbols to get a proper backtrace of the issue.
 
**Describe the expected behavior**
The model should run a forward pass in C++. 
**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

```c++
#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Winvalid-partial-specialization"
#include <tensorflow/core/public/session.h>
#include <tensorflow/core/protobuf/meta_graph.pb.h>
#include <tensorflow/core/public/session_options.h>
#include <tensorflow/cc/saved_model/loader.h>
#include <tensorflow/cc/saved_model/tag_constants.h>
#pragma GCC diagnostic pop
#else
#include <tensorflow/core/public/session.h>
#include <tensorflow/core/protobuf/meta_graph.pb.h>
#include <tensorflow/core/public/session_options.h>
#include <tensorflow/cc/saved_model/loader.h>
#include <tensorflow/cc/saved_model/tag_constants.h>
#endif

#include <string>
#include <Eigen/Dense>

using namespace tensorflow;

int main(){

    const std::string pathToGraph = "/path/to/saved/model/";

    Status status;
    SavedModelBundle bundle;
    status = LoadSavedModel(SessionOptions(), RunOptions(), pathToGraph, {tensorflow::kSavedModelTagServe}, &bundle);
    Session* session = bundle.GetSession();

    if (!status.ok())
    {
        throw std::runtime_error("Could not create Tensorflow session: " + status.ToString());
    }

    if (!status.ok())
    {
        throw std::runtime_error("Error reading graph definition from " + pathToGraph + ": " + status.ToString());
    }

    GraphDef def = bundle.meta_graph_def.graph_def();
    std::string outputlayer = "StatefulPartitionedCall:0";

    tensorflow::Tensor input_tensor_state(tensorflow::DT_FLOAT, tensorflow::TensorShape({1, 6}));
    tensorflow::Tensor input_tensor_action(tensorflow::DT_FLOAT, tensorflow::TensorShape({1, 3}));

    auto input_tensor_state_mapped = input_tensor_state.flat<float>().data();
    auto input_tensor_action_mapped = input_tensor_action.flat<float>().data();

    Eigen::Matrix<float, 6, 1> X = Eigen::Matrix<float, 6, 1>::Zero();
    Eigen::Matrix<float, 3, 1> U = Eigen::Matrix<float, 3, 1>::Zero();

    memcpy(input_tensor_state_mapped, X.data(), X.size()*sizeof(float));
    memcpy(input_tensor_action_mapped, U.data(), U.size()*sizeof(float));

    std::vector<tensorflow::Tensor> outputs;
    
    Status run_status = session->Run({{"serving_default_input_1:0", input_tensor_state},
                                      {"serving_default_input_2:0", input_tensor_action}}, {outputlayer}, {},
                                     &outputs); // The program segfaults here


}

```

**Other info / logs**
I am also including the saved model in question.
[NeuralModel.zip](https://github.com/tensorflow/tensorflow/files/4027127/NeuralModel.zip)

**Comment by mihaimaruseac** [comment]
Can you minimize the code and the model and provide both?

**Comment by mihaimaruseac** [comment]
Sorry, I just saw you provided the model too.

**Comment by dawgster** [comment]
@mihaimaruseac Hello! What exactly do you want me to minimize? Do you mean the code used for model training?

**Comment by mihaimaruseac** [comment]
Hi. Please ignore the request to minimize code, didn't look properly

**Comment by dawgster** [comment]
@mihaimaruseac Any idea in what direction I could go to solve the issue?

**Comment by mihaimaruseac** [comment]
Can you try running under Valgrind? Or identifying the line of the crash?

I didn't get a chance to look into this, the earliest I can get to it would be mid February

**Comment by LemonRay** [comment]
Have you solved the problem yet? If you did it, could you tell me? Thanks!

**Comment by dawgster** [comment]
@LemonRay Yeah I did solve it for my case. The pointer to the session stored in the SavedModelBundle is a unique_ptr and you can't use it the way I did. I ended up accessing it through the SavedModelBundle like this:

```cpp
Status status;
SavedModelBundle bundle
status = LoadSavedModel(SessionOptions(), RunOptions(), pathToGraph, {tensorflow::kSavedModelTagServe}, &bundle);
... //define inputs and outputs
Status run_status = bundle.session->Run({{"serving_default_input_1:0", input_tensor_state}, {"serving_default_input_2:0", input_tensor_action}}, {outputlayer}, {}, &outputs);
```
Hope this is applicable to your problem.

**Comment by mihaimaruseac** [comment]
Can we close this if it is fixed?

**Comment by LemonRay** [comment]
I'll have a try! Thanks for your reply.
