### ISSUE TITLE
Typo Error in `l07c01_saving_and_loading_models.ipynb`

### ISSUE THREAD

**Issue by ManishAradwad** [tensorflow/tensorflow#35616]
## URL(s) with the issue:

https://github.com/ManishAradwad/examples/blob/9f7d80aff8214b358e4aea0b83f2648748990c4b/courses/udacity_intro_to_tensorflow_for_deep_learning/l07c01_saving_and_loading_models.ipynb#L579

`The differnece in output should be zero:`

## Description of issue (what needs changing):

differnece should be difference

### Submit a pull request?

Yes

**Comment by abhiverma1924** [comment]
@jvishnuvardhan Is this issue is solved?

**Comment by jvishnuvardhan** [comment]
@abhiverma1924 There is a PR https://github.com/tensorflow/examples/pull/138 opened to resolve this issue. Thanks.

**Comment by lamberta** [comment]
Thanks. In the process of merging that PR so will close the issue in this repo.
