### ISSUE TITLE
Tensorflow thirdparty libraries are clashing with other same libraries in the project

### ISSUE THREAD

**Issue by kattakarthik** [tensorflow/tensorflow#35627]
**System information**
Linux
tensorflow-2.0.0 
Bazel 0.26.1
Built using virtual environment, python 3

**Describe the problem**
Built **libtensorflow_cc.so & libtensorflow_framework.so** using bazel 0.26.1.
And when linked our existing c++ binary to these libraries, libcurl or opencv calls are clashing with the symbols in tensorflow libraries.

How exactly I can built & include these tenforflow libraries in a larger project without exporting third party symbols. 

Is --config=monolithic the right way ?

**Comment by ymodak** [comment]
This thread may help #1924 #14267

**Comment by kattakarthik** [comment]
Thanks for the reply @ymodak. I tried --monolithic option and it resolved the symbols conflicts issue.

But it seems to be breaking  TensorRT integration ?? I get these error while running my code ::

Or could the error be because of something else I missed. I'm linking against -ltensorflow_cc and -lprotobuf only.

**Comment by ymodak** [comment]
What version of cuda/cudnn and tensorrt are you using?

**Comment by kattakarthik** [comment]
--monolithic option helped resolving symbols clash issue. I have resolved the other issues by removing gpu calls from our binary.
