### ISSUE TITLE
Locate operations on parameter server

### ISSUE THREAD

**Issue by liaha** [tensorflow/tensorflow#3562]
Hi,

I'm working on a distributed tensorflow, and I want to do some preprocess on the variables before the workers retrieve the variable. The preprocessing will trim the model and consequently reduce the amount of network traffic that transfer the variable from parameter server to workers. 

Is that possible to put operations on parameter servers? Thank you

**Comment by michaelisard** [comment]
Yes, there's no distinction between parameter servers and other workers in TensorFlow, and Ops can be placed in the most appropriate location. [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) is the right place for this kind of usage question: if you search for 'device placement' or 'device scope' you will see discussions about placing ops.
