### ISSUE TITLE
How many items does tf.gradients return?

### ISSUE THREAD

**Issue by sharvil** [tensorflow/tensorflow#35628]
Thank you for submitting a TensorFlow documentation issue. Per our GitHub
policy, we only address code/doc bugs, performance issues, feature requests, and
build/installation issues on GitHub.

The TensorFlow docs are open source! To get involved, read the documentation
contributor guide: https://www.tensorflow.org/community/contribute/docs

## URL(s) with the issue:

Please provide a link to the documentation entry, for example:
https://www.tensorflow.org/api_docs/python/tf/gradients?version=stable

## Description of issue (what needs changing):
It's unclear how many list items are returned from `tf.gradients`.

The second paragraph states that "It returns a list of Tensor of length `len(xs)` where each tensor is the `sum(dy/dx)` for y in `ys`." The "Returns" section says, "A list of `sum(dy/dx)` for each x in `xs`."

So... which one is it? `sum(dy/dx)` for x in `xs` or `sum(dy/dx)` for y in `ys`? Besides the inconsistency, the summation notation in this documentation is ambiguous. When it says "`sum(dy/dx)` for x in `xs`" does that mean `dy/dx` is summed over the `ys` axis and there is one element produced for each `xs` or the other way around?

A clarifying example would help and a statement along the lines of "returns a list of <whatever> with as many elements as `xs`" (or `ys` -- I don't know).

### Clear description

For example, why should someone use this method? How is it useful?

### Correct links

Is the link to the source code correct?

### Parameters defined

Are all parameters defined and formatted correctly?

### Returns defined

Are return values defined?

### Raises listed and defined

Are the errors defined? For example,
https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/feature_column/categorical_column_with_vocabulary_file#raises

### Usage example

Is there a usage example?

See the API guide: https://www.tensorflow.org/community/contribute/docs_ref
on how to write testable usage examples.

### Request visuals, if applicable

Are there currently visuals? If not, will it clarify the content?

### Submit a pull request?

Are you planning to also submit a pull request to fix the issue? See the docs
contributor guide: https://www.tensorflow.org/community/contribute/docs,
docs API guide: https://www.tensorflow.org/community/contribute/docs_ref and the
docs style guide: https://www.tensorflow.org/community/contribute/docs_style

**Comment by jvishnuvardhan** [comment]
@sharvil Are you planning to submit PR to update the docs? Thanks!

**Comment by sharvil** [comment]
@jvishnuvardhan, no I'm not planning to submit a PR.

**Comment by ashutosh1919** [comment]
@sharvil , @jvishnuvardhan and @MarkDaoust. Please review the above PR of mine. I have solved the problem with the doc.

**Comment by ashutosh1919** [comment]
Issue resolved by PR #36206 and @sharvil and @alextp has approved it. Please close this issue if everything is resolved, @MarkDaoust , @jvishnuvardhan and @sharvil.

**Comment by amahendrakar** [comment]
@sharvil,
Closing this issue based on [your comment](https://github.com/tensorflow/tensorflow/pull/36206#issuecomment-579969531) in PR #36206.

Please feel free to re-open if mistaken. Thanks!
