### ISSUE TITLE
tensorflow for arm64 issue

### ISSUE THREAD

**Issue by openedev** [tensorflow/tensorflow#35637]
Hi,

I have successfully built the tensorflow for arm64 and indeed it created libtensorflow-lite.a However I'm trying to import the tesorflow in one of my python script like

$ cat test.py
import numpy
import tensorflow

It is showing No named modules something like.

$ python3 test.py 
Traceback (most recent call last):
  File "test_imports/test_ai.py", line 2, in <module>
    import tensorflow
ModuleNotFoundError: No module named 'tensorflow'

Do we need to do any setup to python to picking the tensorflow here? or did I miss any step.

Any help?

**Comment by aselle** [comment]
how did you build it?
you can't import a .a you must import a python library which usually is a dylib or so or dll

**Comment by ymodak** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
