### ISSUE TITLE
Incorrect name_scope with tf.function decoration

### ISSUE THREAD

**Issue by emailweixu** [tensorflow/tensorflow#35649]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): v2.0.0-rc2-26-g64c3d38 2.0.0
- Python version: 3.6
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Describe the current behavior**
If a function is decorated with tf.function, the name_scope is lost

**Describe the expected behavior**
The name_scope should be same with or without tf.function decoration

**Code to reproduce the issue**
```python
import tensorflow as tf

@tf.function
def f():
    with tf.name_scope("f") as scope:
        tf.print(scope)

def g():
    with tf.name_scope("g") as scope:
        tf.print(scope)

def main():
    with tf.name_scope("main"):
        f()   # expect to print "main/f/", actually get "f/"
        g()

if __name__ == "__main__":
    main()
```
The output is
```
f/
main/g/
```

**Comment by oanush** [comment]
Issue is replicating for 2.0 and also TF-nightly, please find the [gist](https://colab.sandbox.google.com/gist/oanush/40d1bf5f1cd626c48a9a55ff5b25527f/35649.ipynb) of colab.Thanks!

**Comment by alextp** [comment]
This is working as intended. The name_scope in the function is rooted at the function graph, and not at the call site (otherwise we'd have to retrace the function every time it's called to make sure it's using the proper name_scope). At runtime you can tell the correct scoping by the nesting of the name of the call op and the ops inside the function graph.

**Comment by emailweixu** [comment]
I think that @tf.function should not change the behavior of the decorated function whenever possible. If a function behave differently after the decoration, it makes the code hard to write.
I am sure there are ways to avoid retracing, similar to experimental_relax_shapes.

The reason I notice this is that I have function doing some tf.summary.scalar(), because of the name scope, the summary tag is different after @tf.function decoration.
