### ISSUE TITLE
tf.strings.lower and tf.strings.upper have "TODO" docstrings

### ISSUE THREAD

**Issue by pbaranay** [tensorflow/tensorflow#35647]
## URL(s) with the issue:

* lower: https://www.tensorflow.org/api_docs/python/tf/strings/lower?version=stable
* upper: https://www.tensorflow.org/api_docs/python/tf/strings/upper?version=stable

### Clear description

The first line of the docstrings for these functions is the auto-generated "TODO: add doc." instead of an actual summary.

### Submit a pull request?

Yes, I'll be submitting one shortly.

**Comment by rohanreddych** [comment]
@pbaranay  can you provide link to the code

**Comment by ymodak** [comment]
Closing this issue since the associated PR has been merged. Thanks!
