### ISSUE TITLE
Error trying to build for AVX2 on CPU

### ISSUE THREAD

**Issue by ajidevelop** [tensorflow/tensorflow#35645]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): source
- TensorFlow version: 2.0.0
- Python version: 3.6.4
- Installed using virtualenv? pip? conda?: pip
- Bazel version (if compiling from source): 0.26.1
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 10/7
- GPU model and memory: NVIDIA GeForce MX150

**Describe the problem**
I am trying to build tensorflow with AVX2 instructions for my CPU to increase speeds, but bazel keeps failing when loading tensorflow

**Provide the exact sequence of commands / steps that you executed before running into the problem**
1. Cloned the tensorflow source from github and checked out the r2.0 branch.
2. Ran python ./configure.py
3. Proceded through steps, selecting no for all other builds and set the bazel config option to /arch:AVC2
4. Ran bazel build --config=opt //tensorflow/tools/pip_package:build_pip_package

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.
The error text is attached here:
[error.txt](https://github.com/tensorflow/tensorflow/files/4032375/error.txt)

**Comment by oanush** [comment]
@ajidevelop ,
Hello i see error `Stderr: /usr/bin/bash: patch: command not found` in log ,[can you install `patch` in your `PATH`](https://github.com/bazelbuild/rules_go/issues/1811)?Thanks!

**Comment by ajidevelop** [comment]
This seemed to fix the issue, but the only thing I'm confused about is why the build_pip_package command seem to target 16000+ packages

**Comment by ymodak** [comment]
Closing this issue since it's resolved. 
Feel free to reopen if still have problems. Thanks!
