### ISSUE TITLE
ERROR: Could not find a version that satisfies the requirement tensorflow

### ISSUE THREAD

**Issue by MarkJThomas** [tensorflow/tensorflow#35646]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Mac Air, Moave (10.14.5 )

- TensorFlow installed from (source or binary): installed using: pip3 install tensorflow
- TensorFlow version: 2.0
- Python version: 3.6.5 64Bit
- Installed using: pip

**Describe the problem**
Using in RStudio, I installed R packages: 

devtools::install_github('rstudio/tensorflow')

devtools::install_github('rstudio/keras')

tried:

install_tensorflow()
tensorflow::install_tensorflow()

but both gave me an error message:

ERROR: Could not find a version that satisfies the requirement tensorflow==2.0.0 (from versions: none)
ERROR: No matching distribution found for tensorflow==2.0.0
Error: Error installing package(s): 'tensorflow==2.0.0'

I checked page after page and found that I needed 3.6.x version of python, so I reverted and it did nothing. I re-installed tensorflow and nothing changed. 

When I checked on python tensorflow worled but for some reason I can't get it to work on RStudio.

Any help please?

Thanks
Mark

**Comment by oanush** [comment]
@MarkJThomas ,
Can you check the [link](https://tensorflow.rstudio.com/installation/) and let us know if it was helpful?Thanks!

**Comment by oanush** [comment]
@MarkJThomas ,
Any update on the issue ?Thanks!

**Comment by oanush** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Comment by venkatesh2374** [comment]
I retrief after 5-10 mins, it worked
