### ISSUE TITLE
mysql-client can not be installed FROM official tensorflow/tensorflow image

### ISSUE THREAD

**Issue by SumNeuron** [tensorflow/tensorflow#35642]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): official tensorflow image from docker hub
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: n/a
- TensorFlow installed from (source or binary): n/a
- TensorFlow version: 1.15.0
- Python version: 3
- Installed using virtualenv? pip? conda?: Docker
- Bazel version (if compiling from source): n/a
- GCC/Compiler version (if compiling from source): n/a
- CUDA/cuDNN version: 10
- GPU model and memory: n/a

**Describe the problem**
Simple image built `FROM tensorflow/tensorflow:tag` fails to build when including `mysql-client`

```dockerfile
FROM tensorflow/tensorflow:1.15.0-gpu-py3-jupyter

# Avoid ERROR: invoke-rc.d: policy-rc.d denied execution of start.
# RUN sed -i "s/^exit 101$/exit 0/" /usr/sbin/policy-rc.d

# --- Install any needed packages specified in requirements.apt
COPY requirements.apt .
RUN apt-get update && xargs apt-get install -y < requirements.apt

# --- Install any needed packages specified in requirements.pip
COPY requirements.pip .
RUN pip install -U --trusted-host pypi.python.org -r requirements.pip

# activate jupyter extensions
RUN jupyter contrib nbextension install \
  && jupyter nbextension enable codefolding/main \
  && jupyter nbextension enable collapsible_headings/main
```

**Provide the exact sequence of commands / steps that you executed before running into the problem**

A MWE [repo](https://gitlab.com/SumNeuron/mytf) contains the following files:

- `Dockerfile.ai`: custom image built on top of official tensorflow/tensorflow
- `docker-compose.ai.development.yml`: specifies `Dockerfile.ai` as build file and mounts `notebooks` directory
- `requirements.pip`: pip requirements that may be used in images other than `Dockerfile.ai`
- `requirements.apt`: packages needed to be installed via `apt-get`

For convenience a python script `docker.py` is provided, e.g. 
```
python docker.py -c {build | up | down}
```
instead of 
```
docker-compose -f docker-compose.ai.development.yml {build | up | down}
```

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.
