### ISSUE TITLE
Custom bidirectional LSTM cell throws unexpected keyword argument 'name'

### ISSUE THREAD

**Issue by datjandra** [tensorflow/tensorflow#35656]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
N/A - tested on colab only
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
N/A
- TensorFlow installed from (source or binary):
binary
- TensorFlow version (use command below):
2.1.0-rc1
- Python version:
3.6.9
- Bazel version (if compiling from source):
N/A
- GCC/Compiler version (if compiling from source):
GCC 8.3.0
- CUDA/cuDNN version:
N/A
- GPU model and memory:
N/A

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
throws unexpected keyword argument 'name' error

**Describe the expected behavior**
should not throw error

**Code to reproduce the issue**
https://colab.research.google.com/drive/17B_MLss_dWjJCBvyMRCWFga31Im2eesc

**Other info / logs**
```
from __future__ import absolute_import, division, print_function, unicode_literals

%tensorflow_version 2.x

import tensorflow as tf
import sys

print(tf.version.GIT_VERSION, tf.version.VERSION)
print(sys.version)

class TestLSTMCell(tf.keras.layers.LSTMCell):
    def __init__(self, units):
        # what's missing here to prevent "TypeError: __init__() got an unexpected keyword argument 'name'"
        super(TestLSTMCell, self).__init__(units)

inputs = tf.keras.Input((128, 256))
cell = TestLSTMCell(512)
forward_layer = tf.keras.layers.RNN(cell, return_state=True)

outputs = forward_layer(inputs)
print("works !!!")

bidirectional_rnn = tf.keras.layers.Bidirectional(forward_layer, merge_mode="concat")
print("nope")
```

See colab link for stack trace.

**Comment by oanush** [comment]
Issue replicating for TF versions 2.1 and tf-nightly. Thanks!

**Comment by pandrey-fr** [comment]
When you define a subclass of `tf.keras.layers.Layer`, you should have its `__init__` method respect the API defined at parent level, which means you need to accept some kwargs (and pass them to the parent constructor through the `super` call).

This is because a number of arguments ('trainable', 'name', 'dtype' and 'dynamic') are part of the basic API but take default values, so that they are not explicitly listed in the `__init__` signature (they are documented, though : run `help(tf.keras.layers.Layer)`).

In effect:
```python
class TestLSTMCell(tf.keras.layers.LSTMCell):
    def __init__(self, units, **kwargs):
        super(TestLSTMCell, self).__init__(units, **kwargs)
```

**Comment by datjandra** [comment]
> ```python
> **kwargs
> ```

Thanks. Passing **kwargs resolved the error.
