### ISSUE TITLE
'AttentionWrapper' object has no attribute 'zero_state' 

### ISSUE THREAD

**Issue by Neel125** [tensorflow/tensorflow#35657]
This template is for miscellaneous issues not covered by the other issue categories.

For questions on how to work with TensorFlow, or support for problems that are not verified bugs in TensorFlow, please go to [StackOverflow](https://stackoverflow.com/questions/tagged/tensorflow).

If you are reporting a vulnerability, please use the [dedicated reporting process](https://github.com/tensorflow/tensorflow/blob/master/SECURITY.md).

For high-level discussions about TensorFlow, please post to discuss@tensorflow.org, for questions about the development or internal workings of TensorFlow, or if you would like to know how to contribute to TensorFlow, please post to developers@tensorflow.org.

**Comment by oanush** [comment]
@Neel125 ,
Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version.
In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thanks!

**Comment by Neel125** [comment]
@oanush 
I am using tensorflow 2.0 and os ubuntu 16.04

**Comment by oanush** [comment]
> @oanush
> I am using tensorflow 2.0 and os ubuntu 16.04

@Neel125 ,
Please provide complete information like what exactly the issue is,code used before facing error log, stack trace of error. Thanks!

**Comment by oanush** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
