### ISSUE TITLE
assign() got an unexpected keyword argument 'validate_shape'

### ISSUE THREAD

**Issue by bersbersbers** [tensorflow/tensorflow#35667]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
```
import tensorflow as tf

a = tf.Variable(2)
a.assign(5)
assert a.numpy() == 5

# ValueError: Shapes () and (2,) are incompatible
a.assign([1,2])  

# TypeError: assign() got an unexpected keyword argument 'validate_shape'
a.assign([1,2], validate_shape=False)

# ValueError: Shapes () and (2,) are incompatible
tf.compat.v1.assign(a, [1,2], validate_shape=False)  

```
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10, Linux
- TensorFlow installed from (source or binary): pip
- TensorFlow version (use command below): 2.0.0, 2.1.0
- Python version: 3.7

**Describe the current behavior**

`tf.assign` had a `validate_shape` parameter that `Variable.assign` seems to be missing.

In addition, the docs say:
> If you want to change the shape of a variable later you have to use an `assign` Op with `validate_shape=False`.

https://www.tensorflow.org/api_docs/python/tf/Variable

How should one change the shape of a variable?

**Code to reproduce the issue**
See above.

**Comment by bersbersbers** [comment]
According to #30840, one now has to use `a = tf.Variable(2, Shape=tf.TensorShape(None))` (compare #26104 and https://github.com/tensorflow/tensorflow/commit/f9f2547b085969c67dc140aaa230551b6471a956).

Still, this looks like a documentation issue: 
> you have to use an `assign` Op with `validate_shape=False`.

is incorrect and should be replaced by

> this is only possible if the variable has been initiliazed with `shape=TensorShape(None)` .

**Comment by rushabh-v** [comment]
@jvishnuvardhan Can I open a PR as my first contribution?

**Comment by amahendrakar** [comment]
@bersbersbers,
The documentation for [tf.Variable](https://www.tensorflow.org/api_docs/python/tf/Variable#assign) has been updated and the above mentioned incorrect statement no longer exists.

Closing this issue as it is resolved. Please feel free to re-open if mistaken. Thanks!
