### ISSUE TITLE
the network is not learning anything - problem with Adam optimizer?

### ISSUE THREAD

**Issue by dusa2** [tensorflow/tensorflow#35668]
I customized this repository of Recurrent Models of Visual Attention (minimal) implementation on MNIST dataset to work with my custom RGB dataset, here is the forked repository: https://github.com/dusa2/RAM

Basically I made minimal changes to make it work with RGB data, and I read in the data using the datagenerator, I have checked data input and shapes and it all seems okay.

However, the network is not learning anything at all! I have a %50 %50 2 label dataset, and the network reward only moves around 0.5, the evaluation is around %50 and at first very little improvement is made (as it reads on the first epoch), but after that the network accuracy does not get better at all. I tried to lower the learning rate and nothing has changed. I suspect that the Adam optimizer does not update the learning rate either.

It all seems straightforward but I can not figure out why. I also tried another dataset (again custom) and it has the same behavior. How can I make sure that the optimizer is working as intended? What else might be the problem?

**Comment by ravikyram** [comment]
@dusa2 
Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version. Also, did you compile from source or install a binary.

Request you to provide simple standalone code to reproduce the issue in our environment. It helps us in localizing the issue faster.
 If you are unclear what to include see the issue template displayed in [the Github new issue template](https://github.com/tensorflow/tensorflow/issues/new/choose).

We ask for this in the issue submission template, because it is really difficult to help without that information. Thanks!

**Comment by dusa2** [comment]
@ravikyram I am using Ubuntu 16.04 python 3 tensorflow version 1.9.0 (binary install)

will try to add a standalone, for now these could be useful as the source code is pretty minimal.  

train.txt format:
filename label
video02_000000 0
video03_000025 1
video04_000050 0

The data is any a set of RGB images (jpeg format), the dataset is read in datagenerator lines 89-101 (path and folder structure needs to be customized)

Mine looks like:

├── data
   ├── images
   └────video01
   └──────video01_000000.jpg
   └──────video01_000025.jpg
   └──────video01_000050.jpg
   └──────....
   └────video02
   └────video99
....

```
    def _read_txt_file(self):
        """Read the content of the text file and store it into lists."""
        self.img_paths = []
        self.labels = []
        with open(self.txt_file, 'r') as f:
            lines = f.readlines()
            for line in lines:
                items = line.split(' ')
                print(items)
                video = items[0].split('_')[0]
                impath =  '/home/data/images/'+video+'/'+items[0] +'.jpg'
                self.img_paths.append(impath)
                self.labels.append(int(items[1]))

```

**Comment by ravikyram** [comment]
@dusa2 
Is it possible for you to try latest TF version 1.15 and let us know whether the issue persists? There were lots of performance improvements in the latest versions. Thanks!

**Comment by dusa2** [comment]
@ravikyram I installed TF version 1.15 in a virtenv now I get this error:

```
import tensorlayer as tl
ImportError: No module named 'tensorlayer'
```

so, I can't even import TF, I tried to look up for solutions but all suggests changing version?

This is how I installed TF btw:` pip install --pre "tensorflow==1.15.*"`
 am I not getting the latest 1.15? what may be wrong?

**Comment by dusa2** [comment]
This is so curious, even for many epochs, it doesn't learn anything at all. Nothing. the loss / reward never changes

**Comment by ymodak** [comment]
Apologies for the delay in response.
Install pip version 19.0 or later. See https://www.tensorflow.org/install/pip#system-requirements
Also this article may help https://stats.stackexchange.com/questions/352036/what-should-i-do-when-my-neural-network-doesnt-learn.
