### ISSUE TITLE
Register a custom tensorflow operation that could be used in tensorflow C++, which itself uses some existing tensorflow operation

### ISSUE THREAD

**Issue by mohitsaini-vgroup** [tensorflow/tensorflow#35664]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10 Professional
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: -
- TensorFlow installed from (source or binary): source
- TensorFlow version: 1.14.0
- Python version: 3.6.6
- Installed using virtualenv? pip? conda?: -
- Bazel version (if compiling from source): 0.24.1
- GCC/Compiler version (if compiling from source): -
- CUDA/cuDNN version: -
- GPU model and memory: - 

**Describe the problem**
I’m trying to register a custom tensorflow operation that I could later use in C++.
The operation is required to use an already existing tensorflow operation as-

`Output output1 = tensorflow::ops::DeepCopy(scope, tensor);`

I’ve created custom_symbolic_gradients.cc file that contains following as shown in official documentation of tensorflow to create a custom op (https://www.tensorflow.org/guide/create_op )-
1. Defining the op interface 
2. Implementing the kernel for the op
3. Registering it with tensorflow kernel

I’ve placed `custom_symbolic_gradients.cc` in following directory:
`//tensorflow/core/user_ops/custom_symbolic_gradients.cc`

When I try to build this tensorflow package with bazel, the following problem arises-
`custom_symbolic_gradients.cc` includes a header file `tensorflow/cc/ops/standard_ops.h` (I had to include it because `DeepCopy `is declared in this header file), which further contains more headers (`tensorlfow/cc/ops/array_ops.h`, `tensorflow/cc/ops/candidate_sampling_ops.h`, and so on...) but these headers are not pre existing in tensorflow package and are generated while building tensorflow with bazel.

So, while building tensorflow with bazel with the following command-
`bazel build -c opt //tensorflow:libtensorflow_cc.so` 

I’m getting the following error-
`.\tensorflow/cc/ops/standard_ops.h(19): fatal error C1083: Cannot open include file: 'tensorflow/cc/ops/array_ops.h': No such file or directory
`
I’ve also tried it with different targets but still get the same error.

Later, I tried it building as incremental build, I first built tensorflow using bazel successfully without adding any custom tensorflow operation, and then tried to build it again after adding custom_symbolic_gradients.cc file in the `tensorflow/core/user_ops/` directory, then I get the following error - 
```
undeclared inclusion(s) in rule '//tensorflow/core:user_ops_op_lib':
this rule is missing dependency declarations for the following files included by 'tensorflow/core/user_ops/custom_symbolic_gradients.cc':
  'bazel-out/x64_windows-opt/genfiles/tensorflow/cc/ops/array_ops.h'
Target //tensorflow:libtensorflow_cc.so failed to build

```
Any idea that I can use to resolve this issue?

**Provide the exact sequence of commands / steps that you executed before running into the problem**
bazel build -c opt //tensorflow:libtensorflow_cc.so 

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

[command.log](https://github.com/tensorflow/tensorflow/files/4034281/command.log)

**Comment by gowthamkpr** [comment]
@mohitsaini-vgroup please post this question in stackoverflow as github is only meant for bug/performance, build/install, feature request or doc related issues. Thanks!
