### ISSUE TITLE
ModuleNotFoundError: No module named 'tflite_runtime'

### ISSUE THREAD

**Issue by batulrangwala** [tensorflow/tensorflow#35663]
Hi,

I am working a x86 Laptop and have installed tensorflow using https://www.tensorflow.org/lite/guide/python
Following is the list of tflite  installed
```

ankit@HP:~$ pip3 list | grep tflite
tflite                        1.15.0                       
tflite-runtime                1.14.0 
```    

my aim is to get a Google coral example running from this link https://coral.ai/docs/accelerator/get-started/#3-run-a-model-using-the-tensorflow-lite-api

When I execute the command for inference I get the folllowing error

```
Traceback (most recent call last):
  File "classify_image.py", line 36, in <module>
    import tflite_runtime.interpreter as tflite
ModuleNotFoundError: No module named 'tflite_runtime'

```

Is there anything else that I need to install. I already have installed the libedgetpu1-std.

**Comment by DantrazTrev** [comment]
Maybe you can use `import tflite-runtime.interpreter as tflite` instead of ` import tflite_runtime.interpreter as tflite` .

**Comment by aselle** [comment]
What exactly are you using to run the inference command?
Are you sure that is the same version of python? i.e. if you are using pip3 but then using python you will probably be using python2 which doesn't have it installed.

**Comment by batulrangwala** [comment]
> Maybe you can use `import tflite-runtime.interpreter as tflite` instead of ` import tflite_runtime.interpreter as tflite` .

This results in syntax error

**Comment by batulrangwala** [comment]
> What exactly are you using to run the inference command?
> Are you sure that is the same version of python? i.e. if you are using pip3 but then using python you will probably be using python2 which doesn't have it installed.

I am using python3 command as follows (same is mentioned on the example in website link given before)
python3 classify_image.py --model models/mobilenet_v2_1.0_224_inat_bird_quant_edgetpu.tflite --labels models/inat_bird_labels.txt --input images/parrot.jpg

I am not working with python2 and I am sure of that.
Actually the example was working initially (For this I had never installed anything related to python or tensorflow. It was a handover of laptop with all of this done).
However I was perfoming a task to convert frozen model (.pb) to tflite model (.tflite) and ended up uninstalling and reinstalling different versions of tensorflow and messed up the system
As I am newbie to python and tensorflow I was not aware about conda environments and did everything on the base.
However I have now set up a conda environment with python3.6 and tensorflow as mentioned. but the example faills at tflite_runtime.

**Comment by aselle** [comment]
Try making a new conda environment and installing tf_runtime again. Show the whole log of commands you wrote and what happened. You can look inside the conda directories site-packages to see if tf_runtime files are there. You can run python3.6 interactively and look at sys.path to see what paths are searched for imports.

**Comment by batulrangwala** [comment]
Hi
I have created a new conda environment with python=3.5
I have also loaded the tflite as follows

```
(py35) ankit@HP:~/Desktop/coral/tflite/python/examples/classification$ sudo pip3 install /home/ankit/tflite_runtime-1.14.0-cp35-cp35m-linux_x86_64.whl 
WARNING: The directory '/home/ankit/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
WARNING: The directory '/home/ankit/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Processing /home/ankit/tflite_runtime-1.14.0-cp35-cp35m-linux_x86_64.whl
Installing collected packages: tflite-runtime
Successfully installed tflite-runtime-1.14.0
```


however I am still getting the same error.
```
(py35) ankit@HP:~/Desktop/coral/tflite/python/examples/classification$ python3 classify_image.py --model models/mobilenet_v2_1.0_224_inat_bird_quant_edgetpu.tflite --labels models/inat_bird_labels.txt --input images/parrot.jpg
Traceback (most recent call last):
  File "classify_image.py", line 36, in <module>
    import tflite_runtime.interpreter as tflite
ImportError: No module named 'tflite_runtime'
```

After careful investigation I observed that the tflite_runtime module was not getting loaded in the env lib path but the base /usr/local/lib.

Resolved it by copying the tflite_runtime folders in my conda env.


I now have a query that why pip3 install command is not installing the module in the conda environment that I am working, instead its installed in the base environment.

**Comment by aselle** [comment]
Ah, it makes sense from your commands what happened
when you run with sudo pip install you install in /usr/local/lbi


conda create --name myenv
conda activate myenv
pip install tensorflow (or whatever)

The point is that you need to activate the conda environment. Then you don't need "sudo pip"

**Comment by batulrangwala** [comment]
I was working in the environment only. 

However if I do not use sudo it was giving me Permission denied error. Hence I had to use sudo with the pip install command

**Comment by endamaco** [comment]
So is tflite working only with conda and not venv?

**Comment by kevin5k** [comment]
I confirm tflite 2.1.0 is working on venv. Tested on an RPI4.

**Comment by rajurimu** [comment]
I am facing this issue on TFLite on Pi Zero.

System information

OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Raspbian GNU/Linux 10 (buster)
Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: Raspberry Pi Zero
TensorFlow installed from (source or binary): Compile natively on Raspberry Pi using https://www.tensorflow.org/lite/guide/build_rpi
TensorFlow version: Trying to install and Tensorflow lite as a standalone
Python version: 3.7.3
Installed using virtualenv? pip? conda?:
Bazel version (if compiling from source): None
GCC/Compiler version (if compiling from source):
CUDA/cuDNN version:
GPU model and memory:
Describe the problem
Trying to install Tensorflow Lite on RPI Zero as a standalone. However once installation is complete as per the following steps,
sudo apt-get install build-essential
git clone https://github.com/tensorflow/tensorflow.git tensorflow_src
cd tensorflow_src && ./tensorflow/lite/tools/make/download_dependencies.sh
./tensorflow/lite/tools/make/build_rpi_lib.sh

I can not import,
import tflite_runtime.interpreter as tflite

Error I am getting is
ModuleNotFoundError: No module named 'tflite_runtime'

In addition as per the instructions, I should see a static library. I do not see this either.
tensorflow/lite/tools/make/gen/lib/rpi_armv6/libtensorflow-lite.a

**Comment by znerl** [comment]
> 
> 
> I am facing this issue on TFLite on Pi Zero.
> 
> System information
> 
> OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Raspbian GNU/Linux 10 (buster)
> Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: Raspberry Pi Zero
> TensorFlow installed from (source or binary): Compile natively on Raspberry Pi using https://www.tensorflow.org/lite/guide/build_rpi
> TensorFlow version: Trying to install and Tensorflow lite as a standalone
> Python version: 3.7.3
> Installed using virtualenv? pip? conda?:
> Bazel version (if compiling from source): None
> GCC/Compiler version (if compiling from source):
> CUDA/cuDNN version:
> GPU model and memory:
> Describe the problem
> Trying to install Tensorflow Lite on RPI Zero as a standalone. However once installation is complete as per the following steps,
> sudo apt-get install build-essential
> git clone https://github.com/tensorflow/tensorflow.git tensorflow_src
> cd tensorflow_src && ./tensorflow/lite/tools/make/download_dependencies.sh
> ./tensorflow/lite/tools/make/build_rpi_lib.sh
> 
> I can not import,
> import tflite_runtime.interpreter as tflite
> 
> Error I am getting is
> ModuleNotFoundError: No module named 'tflite_runtime'
> 
> In addition as per the instructions, I should see a static library. I do not see this either.
> tensorflow/lite/tools/make/gen/lib/rpi_armv6/libtensorflow-lite.a

Same Problem here, could someone help us?
