### ISSUE TITLE
SymbolicException: Inputs to eager execution function cannot be Keras symbolic tensors, but found [<tf.Tensor 'input_1:0' shape=(None, 30, 78) dtype=float32>]

### ISSUE THREAD

**Issue by Krishnarohith10** [tensorflow/tensorflow#35674]
------------------------

### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Windows 10 Version 1909
- **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device**:
- **TensorFlow version (use command below)**: 2.0.0
- **Python version**: 3.6.9
- **CUDA/cuDNN version**:10.0.130
- **GPU model and memory**:GTX 1660 Ti 6GB

[Jazz improvisation with LSTM.zip](https://github.com/tensorflow/tensorflow/files/4035452/Jazz.improvisation.with.LSTM.zip)

I uploaded a zip file in which the .ipynb file when runs gets that error. Please you can run and check what's the problem. How to fix this issuse?

**Comment by oanush** [comment]
@Krishnarohith10 ,
One workaround for the issue can be trying to disable eager execution and run the .ipynb file
```
import tensorflow as tf
tf.compat.v1.disable_eager_execution()
```
You can also refer solution of this similar issue.
Kindly post the question in Stack-overflow if above solution is not helpful.Thanks!

**Comment by Krishnarohith10** [comment]
Thank you for your Solution. Sadly it gone worse. I don't know what is it even. Here have a look:
![1](https://user-images.githubusercontent.com/44919399/72087388-61c47a80-332e-11ea-8a5e-41920f2dc5f9.jpg)

**Comment by Krishnarohith10** [comment]
This is error message I get:
![1](https://user-images.githubusercontent.com/44919399/72214532-137bcb00-352a-11ea-9fd1-d36d93260676.jpg)

**Comment by jvishnuvardhan** [comment]
@Krishnarohith10 Sorry for the late response. Is this still an issue for you? Thanks!

**Comment by Krishnarohith10** [comment]
Not anymore. So I'm closing this issue. Sorry that I didn't notice this issue is still open. Thank You
