### ISSUE TITLE
Where is self.activity_regularizer used in SimpleRNN, GRU and LSTM? Is it a dangling orphan attribute?

### ISSUE THREAD

**Issue by ulf1** [tensorflow/tensorflow#35671]
In the `__init__()` of keras' `SimpleRNN`, `GRU` and `LSTM` the input parameter `activity_regularizer` is stored

```
...
self.activity_regularizer = regularizers.get(activity_regularizer)
...
```

However, it seems that `self.activity_regularizer` never used anywhere in `SimpleRNN`, `GRU` and `LSTM` afterwards.

**Comment by qlzh727** [comment]
It is used in the base layer. See https://github.com/tensorflow/tensorflow/blob/52a9ff02c5d630494b8d5ce5a42004b5a7247478/tensorflow/python/keras/engine/base_layer.py#L942, and search for all the usage of self._ activity_regularizer.
