### ISSUE TITLE
tf.keras.estimator.model_to_estimator InvalidArgumentError: while setting up XLA_GPU_JIT device number 2

### ISSUE THREAD

**Issue by coert** [tensorflow/tensorflow#35672]
I get an error similar to the issue described in https://github.com/tensorflow/tensorflow/issues/31451
When using tf.keras.estimator.model_to_estimator in TF 1.14 and 1.15 I get the InvalidArgumentError described below. The problem doesn't occur in TF 1.13.2. 

I use Linux Mint with Python 3.6 with 2 GPUs (Nvidia GTX1080Ti). To be complete, there are 3 NVidia video cards in the machine (that seems relevant if I understand the error correctly).

```
---------------------------------------------------------------------------
InvalidArgumentError                      Traceback (most recent call last)
<ipython-input-6-3ce5a1d7f637> in <module>
      2     keras_model=model_f,
      3     custom_objects={'Merge': Merge},
----> 4     model_dir='./data/estimator')

~/.../python3.6/site-packages/tensorflow_core/python/keras/estimator/__init__.py in model_to_estimator(keras_model, keras_model_path, custom_objects, model_dir, config, checkpoint_format)
    105       config=config,
    106       checkpoint_format=checkpoint_format,
--> 107       use_v2_estimator=False)
    108 
    109 

~/.../python3.6/site-packages/tensorflow_estimator/python/estimator/keras.py in model_to_estimator(keras_model, keras_model_path, custom_objects, model_dir, config, checkpoint_format, use_v2_estimator)
    574   if keras_model._is_graph_network:
    575     warm_start_path = _save_first_checkpoint(keras_model, custom_objects,
--> 576                                              config, save_object_ckpt)
    577   elif keras_model.built:
    578     logging.warning('You are creating an Estimator from a Keras model manually '

~/.../python3.6/site-packages/tensorflow_estimator/python/estimator/keras.py in _save_first_checkpoint(keras_model, custom_objects, config, save_object_ckpt)
    390 
    391       # save to checkpoint
--> 392       with session.Session(config=config.session_config) as sess:
    393         if keras_weights:
    394           model.set_weights(keras_weights)

~/.../python3.6/site-packages/tensorflow_core/python/client/session.py in __init__(self, target, graph, config)
   1583           protocol buffer with configuration options for the session.
   1584     """
-> 1585     super(Session, self).__init__(target, graph, config=config)
   1586     # NOTE(mrry): Create these on first `__enter__` to avoid a reference cycle.
   1587     self._default_graph_context_manager = None

~/.../python3.6/site-packages/tensorflow_core/python/client/session.py in __init__(self, target, graph, config)
    697     try:
    698       # pylint: disable=protected-access
--> 699       self._session = tf_session.TF_NewSessionRef(self._graph._c_graph, opts)
    700       # pylint: enable=protected-access
    701     finally:

InvalidArgumentError: Invalid device ordinal value (2). Valid range is [0, 1].
	while setting up XLA_GPU_JIT device number 2
```

**Comment by gadagashwini** [comment]
@coert, Thanks for reporting the issue. Can you provide the reproducible code snippet to analyze the issue. Thanks!

**Comment by coert** [comment]
@gadagashwini sorry for the late reply!

This is the minimal code example:
```
import os
import sys
import logging
import tensorflow as tf

from tensorflow.keras.models import load_model

module_path = os.path.abspath(os.path.join('./src'))
if module_path not in sys.path:
    sys.path.append(module_path)

from src.config import CACHE_PATH
from src.networks import KerasGenerator

TRAIN_RESULTS_DIR = os.path.join(CACHE_PATH, 'models')
model_file = os.path.join(TRAIN_RESULTS_DIR, 'model.h5')
model = load_model(model_file)

ESTIMATOR_DIR = os.path.join(CACHE_PATH, 'estimator')
estimator = tf.keras.estimator.model_to_estimator(
    keras_model=model,
    model_dir=ESTIMATOR_DIR)
```

TF log output:
> [I 15:08:58.427 NotebookApp] Replaying 5 buffered messages
> 2020-01-21 15:09:05.038867: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1
> 2020-01-21 15:09:05.098955: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties: 
> name: GeForce GTX 1080 Ti major: 6 minor: 1 memoryClockRate(GHz): 1.62
> pciBusID: 0000:17:00.0
> 2020-01-21 15:09:05.099452: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 1 with properties: 
> name: GeForce GTX 1080 Ti major: 6 minor: 1 memoryClockRate(GHz): 1.62
> pciBusID: 0000:65:00.0
> 2020-01-21 15:09:05.100057: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 2 with properties: 
> name: GeForce GT 710 major: 3 minor: 5 memoryClockRate(GHz): 0.954
> pciBusID: 0000:b3:00.0
> 2020-01-21 15:09:05.100289: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.0
> 2020-01-21 15:09:05.101249: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10.0
> 2020-01-21 15:09:05.102169: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10.0
> 2020-01-21 15:09:05.102434: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10.0
> 2020-01-21 15:09:05.103553: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10.0
> 2020-01-21 15:09:05.104468: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10.0
> 2020-01-21 15:09:05.106899: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
> 2020-01-21 15:09:05.109872: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1731] Ignoring visible gpu device (device: 2, name: GeForce GT 710, pci bus id: 0000:b3:00.0, compute capability: 3.5) with core count: 1. The minimum required count is 8. You can adjust this requirement with the env var TF_MIN_GPU_MULTIPROCESSOR_COUNT.
> 2020-01-21 15:09:05.109883: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0, 1
> 2020-01-21 15:09:05.110185: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 AVX512F FMA
> 2020-01-21 15:09:05.135240: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 3600000000 Hz
> 2020-01-21 15:09:05.136730: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x702be70 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
> 2020-01-21 15:09:05.136766: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
> 2020-01-21 15:09:05.335023: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x70ceaf0 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
> 2020-01-21 15:09:05.335076: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): GeForce GTX 1080 Ti, Compute Capability 6.1
> 2020-01-21 15:09:05.335098: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (1): GeForce GTX 1080 Ti, Compute Capability 6.1
> 2020-01-21 15:09:05.339283: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties: 
> name: GeForce GTX 1080 Ti major: 6 minor: 1 memoryClockRate(GHz): 1.62
> pciBusID: 0000:17:00.0
> 2020-01-21 15:09:05.340643: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 1 with properties: 
> name: GeForce GTX 1080 Ti major: 6 minor: 1 memoryClockRate(GHz): 1.62
> pciBusID: 0000:65:00.0
> 2020-01-21 15:09:05.340741: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.0
> 2020-01-21 15:09:05.340784: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10.0
> 2020-01-21 15:09:05.340821: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10.0
> 2020-01-21 15:09:05.340860: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10.0
> 2020-01-21 15:09:05.340904: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10.0
> 2020-01-21 15:09:05.340942: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10.0
> 2020-01-21 15:09:05.340982: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
> 2020-01-21 15:09:05.344734: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0, 1
> 2020-01-21 15:09:05.344786: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.0
> 2020-01-21 15:09:05.347038: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1159] Device interconnect StreamExecutor with strength 1 edge matrix:
> 2020-01-21 15:09:05.347056: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1165]      0 1 
> 2020-01-21 15:09:05.347067: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 0:   N Y 
> 2020-01-21 15:09:05.347075: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 1:   Y N 
> 2020-01-21 15:09:05.351812: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1304] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 10479 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1080 Ti, pci bus id: 0000:17:00.0, compute capability: 6.1)
> 2020-01-21 15:09:05.352967: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1304] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:1 with 10003 MB memory) -> physical GPU (device: 1, name: GeForce GTX 1080 Ti, pci bus id: 0000:65:00.0, compute capability: 6.1)

Error message:
```
21-01-2020:15:16:28,886 INFO  [estimator.py:1800] Using default config.
21-01-2020:15:16:28,888 INFO  [keras.py:536] Using the Keras model provided.
---------------------------------------------------------------------------
InvalidArgumentError                      Traceback (most recent call last)
<ipython-input-4-4e5a90fa8adc> in <module>
      2 estimator = tf.keras.estimator.model_to_estimator(
      3     keras_model=model,
----> 4     model_dir=ESTIMATOR_DIR)

~/.local/share/virtualenvs/ExpozeGAN2018TF-bd3ZjwC4/lib/python3.7/site-packages/tensorflow_core/python/keras/estimator/__init__.py in model_to_estimator(keras_model, keras_model_path, custom_objects, model_dir, config, checkpoint_format)
    105       config=config,
    106       checkpoint_format=checkpoint_format,
--> 107       use_v2_estimator=False)
    108 
    109 

~/.local/share/virtualenvs/ExpozeGAN2018TF-bd3ZjwC4/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/keras.py in model_to_estimator(keras_model, keras_model_path, custom_objects, model_dir, config, checkpoint_format, use_v2_estimator)
    574   if keras_model._is_graph_network:
    575     warm_start_path = _save_first_checkpoint(keras_model, custom_objects,
--> 576                                              config, save_object_ckpt)
    577   elif keras_model.built:
    578     logging.warning('You are creating an Estimator from a Keras model manually '

~/.local/share/virtualenvs/ExpozeGAN2018TF-bd3ZjwC4/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/keras.py in _save_first_checkpoint(keras_model, custom_objects, config, save_object_ckpt)
    390 
    391       # save to checkpoint
--> 392       with session.Session(config=config.session_config) as sess:
    393         if keras_weights:
    394           model.set_weights(keras_weights)

~/.local/share/virtualenvs/ExpozeGAN2018TF-bd3ZjwC4/lib/python3.7/site-packages/tensorflow_core/python/client/session.py in __init__(self, target, graph, config)
   1583           protocol buffer with configuration options for the session.
   1584     """
-> 1585     super(Session, self).__init__(target, graph, config=config)
   1586     # NOTE(mrry): Create these on first `__enter__` to avoid a reference cycle.
   1587     self._default_graph_context_manager = None

~/.local/share/virtualenvs/ExpozeGAN2018TF-bd3ZjwC4/lib/python3.7/site-packages/tensorflow_core/python/client/session.py in __init__(self, target, graph, config)
    697     try:
    698       # pylint: disable=protected-access
--> 699       self._session = tf_session.TF_NewSessionRef(self._graph._c_graph, opts)
    700       # pylint: enable=protected-access
    701     finally:

InvalidArgumentError: Invalid device ordinal value (2). Valid range is [0, 1].
	while setting up XLA_GPU_JIT device number 2
```

**Comment by gadagashwini** [comment]
@coert, Looks like code is incomplete to replicate the reported issue.
Please provide more information on `from src.config import CACHE_PATH`  to reproduce the issue. Thanks!

**Comment by coert** [comment]
I did some more digging. I believe the error only occurs when you use load_model in combination with model_to_estimator. So it seems something is not loaded properly. Here's the example:

```
import os
import sys
import tensorflow as tf
from shutil import rmtree
from pathlib import Path

tf.get_logger().setLevel(tf.logging.ERROR)

from tensorflow.keras.models import load_model
from tensorflow.keras import backend as K

layers = tf.keras.layers
inputs = layers.Input(shape=(8,8,3), name="input")
outputs = tf.keras.layers.Conv2D(filters=1, kernel_size=(1,1),
                                 name="output")(inputs)
model = tf.keras.models.Model(inputs=inputs, outputs=outputs, name="model")
model.compile(optimizer=tf.keras.optimizers.Adagrad(lr=3e-4), 
              loss='binary_crossentropy', metrics=['accuracy'])
model.summary()

## Uncommenting the next 4 lines will cause model_to_estimator to fail! ##
# model_filename = './model.h5'
# model.save(model_filename)
# K.clear_session()
# model = load_model(model_filename)

# careful! we're removing the whole estimator path
# (if it exists, it will not be recreated)
estimator_path = Path('./data/estimator')
if estimator_path.exists():
    rmtree(str(estimator_path))
    
estimator = tf.keras.estimator.model_to_estimator(
    keras_model=model,
    model_dir=str(estimator_path))
```

**Comment by gadagashwini** [comment]
@coert, I tried reproducing it with Tf-gpu 1.15 but no error. Please take a look at [gist](https://colab.research.google.com/gist/gadagashwini/5eb5578f670744f3efb51bfef6290efd/untitled369.ipynb) and confirm the issue still exists or not. Thanks

**Comment by coert** [comment]
@gadagashwini how can I check that the gist is using multiple GPU devices? I think the problem is in the combination of reloading a model while have multiple usable GPUs in your system. From the original log above:
```
2020-01-21 15:09:05.347056: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1165]    0 1 
2020-01-21 15:09:05.347067: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 0: N Y 
2020-01-21 15:09:05.347075: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 1: Y N
```

Long story short, the gist works fine, but it isn't representative of the problem.

**Comment by sanjoy** [comment]
Can you please check if this still happens on TF-nightly?  We have made some improvements in this area.

**Comment by coert** [comment]
Looks good on tf-nightly 2.2.0.dev20200403. Thanks!

**Comment by coert** [comment]
Unable to check tf-nightly 1.15.x, I think that's due to: 
https://github.com/tensorflow/tensorflow/issues/37317
https://github.com/pypa/pypi-support/issues/224
