### ISSUE TITLE
KeyError Tensorflow

### ISSUE THREAD

**Issue by rahulroxx** [tensorflow/tensorflow#3567]
Traceback (most recent call last):
  File "ptb_word_lm.py", line 326, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 30, in run
    sys.exit(main(sys.argv))
  File "ptb_word_lm.py", line 291, in main
    raw_data = reader.ptb_raw_data(FLAGS.data_path)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/models/rnn/ptb/reader.py", line 76, in ptb_raw_data
    valid_data = _file_to_word_ids(valid_path, word_to_id)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/models/rnn/ptb/reader.py", line 48, in _file_to_word_ids
    return [word_to_id[word] for word in data]
KeyError: 'FLOOR\\n<eos>\\n//'

**Comment by michaelisard** [comment]
Could you give more details as indicated in the issue template that appears when you click 'New Issue', e.g. OS, repro steps, etc.? Thanks!

**Comment by pranjaldaga** [comment]
Hi @michaelisard I encountered a similar error when I changed the contents of 'ptb.train.txt' or 'ptb.valid.txt' or 'ptb.test.txt' files while running the [LSTM tutorial](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/models/rnn/ptb/ptb_word_lm.py) script. It might be something really silly, so I'm trying to workaround it, but any hint would be greatly appreciated. Thanks!

**Comment by rahulroxx** [comment]
the problem is that I'm trying to train rnn model to sentence tokenize with ptb example on tensorflow official webiste. 

I have a string defined as follows: 

**"""AVL LIST OF APTS High End 4bhk @ STEESHA Mount Mary Bandra Higher Floor Avl Approx 2500 sqft carpet 2 parkings Full Sea Facing Quote : Rs 30 Cr Spacious 3bhk @ PALACIO 16th Rd Bandra West Brand New Bldng Higher floor Approx 1700 sqft carpet 2 parkings Quote : Rs 9.25 Cr"""**

I need to train rnn tokenizer to tokenize sentences as 
message1 = "AVL LIST OF APTS 1) High End 4bhk @ STEESHA Mount Mary Bandra Higher Floor Avl Approx 2500 sqft carpet 2 parkings Full Sea Facing Quote : Rs 30 Cr"

message2 = " Spacious 3bhk @ PALACIO 16th Rd Bandra West Brand New Bldng Higher floor Approx 1700 sqft carpet 2 parkings Quote : Rs 9.25 Cr "

Would you please help me in solving problem I'm really stucked. 
Thanks,

**Comment by michaelisard** [comment]
It's easier to help find a problem if you are willing to say what OS and versions of tensorflow etc. you are using and a repro case, e.g. the command line you are using. If you click on 'New Issue' you will see a template which shows you the right details to fill in. Thanks!

**Comment by girving** [comment]
Closing for now due to lack of response.  We are happy to reopen if more details emerge!
