### ISSUE TITLE
Explanation regarding `seed` parameter

### ISSUE THREAD

**Issue by ManishAradwad** [tensorflow/tensorflow#35677]
## URL(s) with the issue:

https://github.com/tensorflow/examples/blob/d631c0545dac90c6390da76ed8df7c4f6a2a25bc/courses/udacity_intro_to_tensorflow_for_deep_learning/l08c01_common_patterns.ipynb#L307

`def white_noise(time, noise_level=1, seed=None):`

## Description of issue (what needs changing):

I think, we should add explanation of `seed` parameter here since it's quite an important one.

### Clear description

Some explanation about how `seed` affects generation of random numbers every time along with links for reference can be added.

### Submit a pull request?

Yes

**Comment by mohantym** [comment]
Hi @ManishAradwad @MarkDaoust 
Created a new PR [#408](https://github.com/tensorflow/examples/pull/408) to a faster merge.
Thank you!

**Comment by mohantym** [comment]
Hi @MarkDaoust !
Can you have a look at the new PR for adding an explanation of Seed parameter.
Thank you!

**Comment by MarkDaoust** [comment]
There'd be no harm in merging the PR. But there are a bunch of merge conflicts. Since Random seeds are such a common topic in software I'm not sure we need to be explaining it here. So I'm just closing, unless someone wants to fix the conflicts. Sorry!
