### ISSUE TITLE
ValueError: too many values to unpack (expected 2)

### ISSUE THREAD

**Issue by nagapoornima22** [tensorflow/tensorflow#35673]
while performing language translation it is rising an issue value error.
i followed the code from the tensorflow guide

from __future__ import absolute_import, division, print_function, unicode_literals

import tensorflow as tf

import matplotlib.pyplot as plt
import matplotlib.ticker as ticker
#from sklearn.model_selection import train_test_split

import unicodedata
import re
import numpy as np
import os
import io
import time
# Download the file

path_to_file = "spanish.txt"
# Converts the unicode file to ascii
def unicode_to_ascii(s):
    return ''.join(c for c in unicodedata.normalize('NFD', s)
                   if unicodedata.category(c) != 'Mn')

def preprocess_sentence(w):
    w = unicode_to_ascii(w.lower().strip())
    # creating a space between a word and the punctuation following it
    # eg: "he is a boy." => "he is a boy ."
    # Reference:- https://stackoverflow.com/questions/3645931/python-padding-punctuation-with-white-spaces-keeping-punctuation
    w = re.sub(r"([?.!,¿])", r" \1 ", w)
    w = re.sub(r'[" "]+', " ", w)

    # replacing everything with space except (a-z, A-Z, ".", "?", "!", ",")
    w = re.sub(r"[^a-zA-Z?.!,¿]+", " ", w)
    w = w.rstrip().strip()
    # adding a start and an end token to the sentence
    # so that the model know when to start and stop predicting.
    w = '<start> ' + w + ' <end>'
    return w
en_sentence = u"Wow!"
sp_sentence = u"¡Órale!"
print(preprocess_sentence(en_sentence))
print(preprocess_sentence(sp_sentence).encode('utf-8'))

# 1. Remove the accents
# 2. Clean the sentences
# 3. Return word pairs in the format: [ENGLISH, SPANISH]
def create_dataset(path, num_examples):
    lines = io.open(path, encoding='UTF-8').read().strip().split("\t")
    word_pairs = [[preprocess_sentence(w) for w in l.split("\t")] for l in lines[:num_examples]]
    return word_pairs
en, sp = create_dataset(path_to_file, None)
print(en[-1])
print(sp[-1])

Raising an error in line : en, sp = create_dataset(path_to_file, None)

**Comment by vidursatija** [comment]
Hi, try printing out word pairs before it is returned and see the size of the array

**Comment by nagapoornima22** [comment]
> Hi, try printing out word pairs before it is returned and see the size of the array

It is printing the output with start and end tags separated by ','

but it is again raising the same error

**Comment by vidursatija** [comment]
What is the size of the array?

**Comment by Lasers67** [comment]
The word_pairs is a single array, and cannot be split up into 2 values, try zipping the array by
zip(*word_pairs) as mentioned in the documentation.
[https://www.tensorflow.org/tutorials/text/nmt_with_attention](url)

**Comment by nagapoornima22** [comment]
> The word_pairs is a single array, and cannot be split up into 2 values, try zipping the array by
> zip(*word_pairs) as mentioned in the documentation.
> [https://www.tensorflow.org/tutorials/text/nmt_with_attention](url)

Thq it works for me

**Comment by nagapoornima22** [comment]
Hi, 
Instead of translating a single sentence always how can we take inputs from the user and translate it.
can we integrate this translation model in android.please help me to do that.

**Comment by gadagashwini** [comment]
@nagapoornima22, Take input from user using 
`input_sentence = raw_input("write a sentence") `or 
`input_sentence = input("Write a sentence")`
and please find the [guide](https://www.tensorflow.org/lite/guide/android) for deploying the translation model in android using Tensorflow. Thanks

**Comment by nagapoornima22** [comment]
> @nagapoornima22, Take input from user using
> `input_sentence = raw_input("write a sentence") `or
> `input_sentence = input("Write a sentence")`
> and please find the [guide](https://www.tensorflow.org/lite/guide/android) for deploying the translation model in android using Tensorflow. Thanks

Thankyou

**Comment by nadiaha7** [comment]
hi, i tried with the zip but the same error

**Comment by abhijeet-detha** [comment]
Tried with Zip same error.

**Comment by abhijeet-detha** [comment]
> Tried with Zip same error.

def create_dataset(path, num_examples):
  lines = io.open(path, encoding='UTF-8').read().strip().split('\n')
  word_pairs = [[preprocess_sentence(w) for w in l.split('\t')[:2]]  for l in lines[:num_examples]]
  return zip(*word_pairs)


This works!!

**Comment by abhijeet-detha** [comment]
> hi, i tried with the zip but the same error

def create_dataset(path, num_examples):
    lines = io.open(path, encoding='UTF-8').read().strip().split('\n')
    word_pairs = [[preprocess_sentence(w) for w in l.split('\t')[:2]]  for l in lines[:num_examples]]
    return zip(*word_pairs)


This works!

**Comment by Jheezy30** [comment]
please i want to save my architecture and save the model to my google drive, i am using google colab ,to be able to design the application.
