### ISSUE TITLE
multi_gpu_model is slower than single gpu model.

### ISSUE THREAD

**Issue by CleanPegasus** [tensorflow/tensorflow#35687]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): pip install
- TensorFlow version (use command below): 1.14
- Python version: Python 3.7
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 10.0
- GPU model and memory: 2*Titan XP - 12GB memory per card

**Describe the current behavior**

The performance of a multi_gpu_model is slower than using a single GPU. When the model is running on a single GPU, the compute performance of the GPU tops at 91% to 95%, but when model is running on a multiple GPUs, the performance varies from 9% to 21%.

**Describe the expected behavior**

Expect the model to train faster on multiple GPUs compared to single GPU.

**Code to reproduce the issue**

All the Convolution networks I've tried.

**Comment by gadagashwini** [comment]
@CleanPegasus, Can you provide the standalone code to replicate the reported issue. Thanks!

**Comment by gadagashwini** [comment]
@CleanPegasus, Any update!

**Comment by gadagashwini** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
