### ISSUE TITLE
TFLite C/C++ library header file installation

### ISSUE THREAD

**Issue by thkim-cochl** [tensorflow/tensorflow#35689]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04
- TensorFlow installed from (source or binary): source
- TensorFlow version: 2.0
- Bazel version (if compiling from source): 0.26.1
- GCC/Compiler version (if compiling from source): 7.4.0

**Describe the problem**
I need just a TFLite header file without the whole TensorFlow source code. Is there any method to install the TFLite header?

I found a similar issue at #3536. But, `//tensorflow:install_headers` Bazel target does not install a TFLite header file.

**Comment by tigert1998** [comment]
I have the same issue here. Could tf maintainers team nicely provides a way to export tflite headers?

**Comment by terryheo** [comment]
@jdduke any idea on this?

**Comment by jdduke** [comment]
Thanks for flagging this issue. We've been working on something like this, but still need to remove the flatbuffer inclusion from our public C++ APIs. We'll try to prioritize this for early Q2.

**Comment by raryanpur** [comment]
@jdduke any update on this?

**Comment by jdduke** [comment]
Sadly, no immediate update. At the moment, we're steering developers toward our C API if they want both a prebuilt library and a compact set of headers. The C API and headers are actually included in the latest release artifacts that we publish to Bintray: https://bintray.com/google/tensorflow/tensorflow-lite. We've added some guidance on this approach @ https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/g3doc/guide/android.md#build-android-app-using-c.

In Q3, we'll be investing in full CMake support so that we can better integrate into developer toolchains. This will also include some cleanup for the C++ API to minimize external dependencies. Thanks for your patience on this.

**Comment by raryanpur** [comment]
Thanks for the update, @jdduke!

**Comment by llschloesser** [comment]
@jdduke the C API appears insufficient for running inference on the edge tpu, will that also be a priority?

**Comment by jdduke** [comment]
> @jdduke the C API appears insufficient for running inference on the edge tpu, will that also be a priority?

Thanks for flagging the issue. You should be able to inject custom ops (`edgetpu::kCustomOp`) in the C API from the `c_api_experimental.h` header, `TfLiteInterpreterOptionsAddCustomOp`.

**Comment by llschloesser** [comment]
@Namburger, can you offer some help with the suggestion above? It looks like I need to use the C++ edgetpu API? Can you offer an example?

**Comment by llschloesser** [comment]
I got it working, thanks for the pointers. My problem was I had to switch to 2.1 and change the order of the arguments. I still have no idea what min and max version are.

Working code with TF 2.1:
```
  //                                                                            
  // Create model and interpreter options:                                      
  //                                                                            
  model_ = TfLiteModelCreateFromFile(params_.model.c_str());                    
  options_ = TfLiteInterpreterOptionsCreate();                                  
                                                                                
  //                                                                            
  // Register Edge TPU custom ops:                                              
  //                                                                            
  TfLiteInterpreterOptionsAddCustomOp(options_,                                 
                                      edgetpu::kCustomOp,                       
                                      edgetpu::RegisterCustomOp(), 10, 13);     
  //                                                                            
  // Create the delegate:                                                       
  //                                                                            
  delegate_ = edgetpu_create_delegate(device.type, device.path, nullptr, 0);    
  TfLiteInterpreterOptionsAddDelegate(options_, delegate_);                     
                                                                                
  //                                                                            
  // Create the interpreter:                                                    
  //                                                                            
  interpreter_ = TfLiteInterpreterCreate(model_, options_);
```

**Comment by jdduke** [comment]
>  I still have no idea what min and max version are.

Thanks for flagging, will add some improved comments to the header. They correspond to the C++ MutableOpResolver API, but for custom ops you can generally safely just set the min/max to "1".

>  delegate_ = edgetpu_create_delegate(device.type, device.path, nullptr, 0);    

Do you need both the delegate and the CustomOp? Does it work to add just the delegate?

**Comment by llschloesser** [comment]
@jdduke turns out you are right, only the delegate is needed. I must have had the call order wrong before and missed that. Thanks for the help and the clarification on min and max.

**Comment by CoreyCole** [comment]
@llschloesser @jdduke do you have any advice on how I can register the RandomStandardNormal custom operator prototype in the C api? It was implemented in 2.4.0-rc0 

https://github.com/tensorflow/tensorflow/commit/11823c6179a5e2ca6ac4f8480aa00c42c772885e#

I'm not sure how to use it because the registration is defined in a C++ namespace and I don't know how to use `tflite::ops::custom::Register_RANDOM_STANDARD_NORMAL` in C.

Apologies for hijacking the issue

**Comment by jdduke** [comment]
We're hoping to make the RANDOM_STANDARD_NORML op a builtin op for the next 2.5 release.

**Comment by CoreyCole** [comment]
@jdduke would you mind checking this thread on the TFLite mailing list? https://groups.google.com/a/tensorflow.org/g/tflite/c/1zfZtRtVfpY

I feel super close to getting the Register_RANDOM_STANDARD_NORMAL working from the C API, but I'm having trouble exporting the symbol to call it.

**Comment by lilinxiong** [comment]
@jdduke Hi~ Can I export the header file of libTensorFlowLite.so now?
The version I am using is v2.5.0.

**Comment by terryheo** [comment]
@lilinxiong we don't have the feature of exporting C++ headers yet.

**Comment by mohantym** [comment]
Hi @thkim-cochl !
We are checking to see whether you still need help in this issue . Have you checked [CMake minimal example ](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/examples/minimal)documentations which includes lite C header files.

Ref [1](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/examples/minimal/BUILD), [2](https://groups.google.com/a/tensorflow.org/g/tflite/c/MXVrernDHhE).

Thank you!
