### ISSUE TITLE
RuntimeError: Encountered unresolved custom op: Enter.Node number 8 (Enter) failed to prepare.

### ISSUE THREAD

**Issue by 2696120622** [tensorflow/tensorflow#35688]
I have converted tf.keras model to tf.lite successfully. However, when I use it for inference, I get an error. Is there anyone who can resolve it? Thanks!

code:
`interpreter = tf.lite.Interpreter(model_path="E:/object_detection/EfficientDet-region_anchor_opt_mbconv-head-ckpts/tflites/ckpts_B0_image-size-768/mbconv-se-head_1e-5_unfreeze-backbone_freeze-bn/csv_04_0.6736_0.7484_opts.tflite")

interpreter.allocate_tensors()`

error:
`RuntimeError                              Traceback (most recent call last)
<ipython-input-12-ca8eb7ec6089> in <module>()
      1 # interpreter = tf.lite.Interpreter(model_content=tflite_model)
----> 2 interpreter.allocate_tensors()
      3 # help(tf.lite.Interpreter)

~\AppData\Roaming\Python\Python36\site-packages\tensorflow_core\lite\python\interpreter.py in allocate_tensors(self)
    242   def allocate_tensors(self):
    243     self._ensure_safe()
--> 244     return self._interpreter.AllocateTensors()
    245 
    246   def _safe_to_run(self):

~\AppData\Roaming\Python\Python36\site-packages\tensorflow_core\lite\python\interpreter_wrapper\tensorflow_wrap_interpreter_wrapper.py in AllocateTensors(self)
    104 
    105     def AllocateTensors(self):
--> 106         return _tensorflow_wrap_interpreter_wrapper.InterpreterWrapper_AllocateTensors(self)
    107 
    108     def Invoke(self):

RuntimeError: Encountered unresolved custom op: Enter.Node number 8 (Enter) failed to prepare.`

**Comment by gadagashwini** [comment]
@2696120622, Can you provide the standalone code to reproduce the issue and also provide tensorflow version. Thanks

**Comment by 2696120622** [comment]
> @2696120622, Can you provide the standalone code to reproduce the issue and also provide tensorflow version. Thanks

OK, Thanks!
My tensorflow version is 1.15.0-rc0.
My code as follows.
`
from tensorflow import keras
import tensorflow as tf
import layers as layers_new
import initializers
import losses
import efficientnet

custom_objects = {
    'BatchNormalization': layers_new.BatchNormalization,
    'swish'            : efficientnet.get_swish(backend=keras.backend,layers=keras.layers,models=keras.models,utils=keras.utils),
    'FixedDropout'     : efficientnet.get_dropout(backend=keras.backend,layers=keras.layers,models=keras.models,utils=keras.utils),
#     'wBiFPNAdd'        : layers_new.wBiFPNAdd,
    'PriorProbability' : initializers.PriorProbability,
    'RegressBoxes'     : layers_new.RegressBoxes,
    'FilterDetections' : layers_new.FilterDetections,
    'ClipBoxes'        : layers_new.ClipBoxes,
    '_smooth_l1'       : losses.smooth_l1(),
    '_focal'           : losses.focal(),
}
input_shapes = {'input_1':[None,512,512,3],'input_4':[None,49104,4]}
converter = tf.lite.TFLiteConverter.from_keras_model_file('E:/object_detection/Efficient-region-checkpoints/inference_checkpoints/inference_checkpoints_B0/freeze-backbone-false_1e-5/csv_05_0.3995_0.5901.h5',
                                                          custom_objects=custom_objects,
                                                          input_shapes=input_shapes,
                                                          )
converter.allow_custom_ops=True
tflite_model = converter.convert()
open("E:/object_detection/Efficient-region-checkpoints/tflites/inference_checkpoints_B0/freeze-backbone-false_1e-5/csv_05_0.3995_0.5901.tflite", "wb").write(tflite_model)
interpreter = tf.lite.Interpreter(model_path="E:/object_detection/Efficient-region-checkpoints/tflites/inference_checkpoints_B0/freeze-backbone-false_1e-5/csv_05_0.3995_0.5901.tflite")
interpreter.allocate_tensors()
`

Then I get the following error.

`RuntimeError                              Traceback (most recent call last)
<ipython-input-13-e8f284b41149> in <module>()
----> 1 interpreter.allocate_tensors()

~\AppData\Roaming\Python\Python36\site-packages\tensorflow_core\lite\python\interpreter.py in allocate_tensors(self)
    242   def allocate_tensors(self):
    243     self._ensure_safe()
--> 244     return self._interpreter.AllocateTensors()
    245 
    246   def _safe_to_run(self):

~\AppData\Roaming\Python\Python36\site-packages\tensorflow_core\lite\python\interpreter_wrapper\tensorflow_wrap_interpreter_wrapper.py in AllocateTensors(self)
    104 
    105     def AllocateTensors(self):
--> 106         return _tensorflow_wrap_interpreter_wrapper.InterpreterWrapper_AllocateTensors(self)
    107 
    108     def Invoke(self):

RuntimeError: Encountered unresolved custom op: Enter.Node number 8 (Enter) failed to prepare.`

Could you help me?

**Comment by 2696120622** [comment]
> > @2696120622, Can you provide the standalone code to reproduce the issue and also provide tensorflow version. Thanks
> 
> OK, Thanks!
> My tensorflow version is 1.15.0-rc0.
> My code as follows.
> `
> from tensorflow import keras
> import tensorflow as tf
> import layers as layers_new
> import initializers
> import losses
> import efficientnet
> 
> custom_objects = {
> 'BatchNormalization': layers_new.BatchNormalization,
> 'swish' : efficientnet.get_swish(backend=keras.backend,layers=keras.layers,models=keras.models,utils=keras.utils),
> 'FixedDropout' : efficientnet.get_dropout(backend=keras.backend,layers=keras.layers,models=keras.models,utils=keras.utils),
> 'wBiFPNAdd' : layers_new.wBiFPNAdd,
> 'PriorProbability' : initializers.PriorProbability,
> 'RegressBoxes' : layers_new.RegressBoxes,
> 'FilterDetections' : layers_new.FilterDetections,
> 'ClipBoxes' : layers_new.ClipBoxes,
> '_smooth_l1' : losses.smooth_l1(),
> '_focal' : losses.focal(),
> }
> input_shapes = {'input_1':[None,512,512,3],'input_4':[None,49104,4]}
> converter = tf.lite.TFLiteConverter.from_keras_model_file('E:/object_detection/Efficient-region-checkpoints/inference_checkpoints/inference_checkpoints_B0/freeze-backbone-false_1e-5/csv_05_0.3995_0.5901.h5',
> custom_objects=custom_objects,
> input_shapes=input_shapes,
> )
> converter.allow_custom_ops=True
> tflite_model = converter.convert()
> open("E:/object_detection/Efficient-region-checkpoints/tflites/inference_checkpoints_B0/freeze-backbone-false_1e-5/csv_05_0.3995_0.5901.tflite", "wb").write(tflite_model)
> interpreter = tf.lite.Interpreter(model_path="E:/object_detection/Efficient-region-checkpoints/tflites/inference_checkpoints_B0/freeze-backbone-false_1e-5/csv_05_0.3995_0.5901.tflite")
> interpreter.allocate_tensors()
> `
> 
> Then I get the following error.
> 
> `RuntimeError Traceback (most recent call last)
> in ()
> ----> 1 interpreter.allocate_tensors()
> 
> ~\AppData\Roaming\Python\Python36\site-packages\tensorflow_core\lite\python\interpreter.py in allocate_tensors(self)
> 242 def allocate_tensors(self):
> 243 self._ensure_safe()
> --> 244 return self._interpreter.AllocateTensors()
> 245
> 246 def _safe_to_run(self):
> 
> ~\AppData\Roaming\Python\Python36\site-packages\tensorflow_core\lite\python\interpreter_wrapper\tensorflow_wrap_interpreter_wrapper.py in AllocateTensors(self)
> 104
> 105 def AllocateTensors(self):
> --> 106 return _tensorflow_wrap_interpreter_wrapper.InterpreterWrapper_AllocateTensors(self)
> 107
> 108 def Invoke(self):
> 
> RuntimeError: Encountered unresolved custom op: Enter.Node number 8 (Enter) failed to prepare.`
> 
> Could you help me?
