### ISSUE TITLE
About symbols' visibility in shared library

### ISSUE THREAD

**Issue by yejw5** [tensorflow/tensorflow#35696]
**System information**
- TensorFlow version (you are using):  v2.0.0
- Are you willing to contribute it (Yes/No): Yes

**Describe the feature and the current behavior/state.**
As we can see from [tf_version_script.lds in v2.0.0](https://github.com/tensorflow/tensorflow/blob/v2.0.0/tensorflow/tf_version_script.lds), none of `Eager*` symbols have been set to `global visibility`. But in newest master codes, this has been [updated](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tf_version_script.lds#L7).

In our usage scenario, we need transfer `EagerTensor_Handle` in our python apis to read or update the tensors. It's important that no copy happens in Tensor transfering. However, `EagerTensor*` like symbols depend on `_pywrap_tensorflow_internal.so` are `Local` visibility in current stable release.

**Will this change the current api? How?**
No. Only version script file: tf_version_script.lds 

**Who will benefit with this feature?**
The one who need read or write Tensors outside tensorflow.

**And more**
Maybe it's not good to update symbols' stripping rule in `v2.0.0` release (or other tags). But this have changed in master branch. When will you release this feature in next edition? Or is this a good way to interchange data between outerside and tf (**with zero copy**)?

**Comment by mihaimaruseac** [comment]
It is an API change as new symbols get exposed.

For 2.0 and 2.1 it is unlikely that these new symbols will be exposed. However, you can get them from `tf-nightly` and from the TF2.2 release in a few months.

**Comment by yejw5** [comment]
@mihaimaruseac Thanks for response. Looking forward to the new feature and TF2.2 release.
