### ISSUE TITLE
MultiWorkerMirroredStrategy stuck

### ISSUE THREAD

**Issue by fsx950223** [tensorflow/tensorflow#35694]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): tensorflow 1.15-2.1
- Python version:3.6.8
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
MultiWorkerMirroredStrategy stucks at start server when I run cluster on different computers.
**Describe the expected behavior**
Works same as on a computer
**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.
```python
import tensorflow as tf
import json
import os
import tensorflow_datasets as tfds

BUFFER_SIZE = 10000
BATCH_SIZE = 4

def make_datasets_unbatched():
  # Scaling MNIST data from (0, 255] to (0., 1.]
  def scale(image, label):
    image = tf.cast(image, tf.float32)
    image /= 255
    return image, label

  datasets, info = tfds.load(name='mnist',
                            with_info=True,
                            as_supervised=True)

  return datasets['train'].map(scale).cache().shuffle(BUFFER_SIZE)


def build_and_compile_cnn_model():
  model = tf.keras.Sequential([
      tf.keras.layers.Conv2D(32, 3, activation='relu', input_shape=(28, 28, 1)),
      tf.keras.layers.MaxPooling2D(),
      tf.keras.layers.Flatten(),
      tf.keras.layers.Dense(64, activation='relu'),
      tf.keras.layers.Dense(10, activation='softmax')
  ])
  model.compile(
      loss=tf.keras.losses.sparse_categorical_crossentropy,
      optimizer=tf.keras.optimizers.SGD(learning_rate=0.001),
      metrics=['accuracy'])
  return model

def train_task(index):
    os.environ['TF_CONFIG'] = json.dumps({
        'cluster': {
            'worker': ["ip1:9901","ip2:9902"],
        },
        'task': {'type': 'worker', 'index': index},
    })
    strategy = tf.distribute.experimental.MultiWorkerMirroredStrategy()
    # Here the batch size scales up by number of workers since
    # `tf.data.Dataset.batch` expects the global batch size. Previously we used 64,
    # and now this becomes 128.
    GLOBAL_BATCH_SIZE = 12
    train_datasets = make_datasets_unbatched().batch(GLOBAL_BATCH_SIZE)
    with strategy.scope():
        multi_worker_model = build_and_compile_cnn_model()
    multi_worker_model.fit(x=train_datasets, epochs=3)

# runs on ip1
train_task(0)
# runs on ip2
# train_task(1)
```
**Other info / logs**
Above code works on a single computer.
Ports are accessible between computers.
I have searched on the internet and read serveal books, but I still can't find solution.

**Comment by anj-s** [comment]
@fsx950223 Can you move 
`train_datasets = make_datasets_unbatched().batch(GLOBAL_BATCH_SIZE)` within the strategy scope? So you code above would look like:

```
with strategy.scope():
        train_datasets = make_datasets_unbatched().batch(GLOBAL_BATCH_SIZE)
        multi_worker_model = build_and_compile_cnn_model()
```

**Comment by fsx950223** [comment]
> @fsx950223 Can you move
> `train_datasets = make_datasets_unbatched().batch(GLOBAL_BATCH_SIZE)` within the strategy scope? So you code above would look like:
> 
> ```
> with strategy.scope():
>         train_datasets = make_datasets_unbatched().batch(GLOBAL_BATCH_SIZE)
>         multi_worker_model = build_and_compile_cnn_model()
> ```

The problem is solved. Thanks

**Comment by 372046933** [comment]
Can `strategy.experimental_distribute_dataset(dataset)` also be used to fix the stuck?
