### ISSUE TITLE
Correction in calculation of error while Naive Forecasting

### ISSUE THREAD

**Issue by ManishAradwad** [tensorflow/tensorflow#35693]
## URL(s) with the issue:

https://github.com/tensorflow/examples/blob/master/courses/udacity_intro_to_tensorflow_for_deep_learning/l08c03_moving_average.ipynb

## Description of issue (what needs changing):

It should be 'mean absolute error' instead of squared error while Naive Forecasting

![Screenshot from 2020-01-09 12-10-09](https://user-images.githubusercontent.com/29497701/72044240-4bd89a80-32d9-11ea-937f-a189784b83b0.png)

### Submit a pull request?

Yes, I'll be submitting one shortly

**Comment by Saduf2019** [comment]
@ManishAradwad 
can we please move this issue to closed as there is a pr [#140] to monitor this
