### ISSUE TITLE
Dangling pointer  through IntArrayFromInitializer causing Segfault in Tests

### ISSUE THREAD

**Issue by lamarrr** [tensorflow/tensorflow#35699]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 19.10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: None
- TensorFlow installed from (source or binary): source

- TensorFlow version (use command below): 2.1
- Python version: 3.6
- Bazel version (if compiling from source): 1.2.1
- GCC/Compiler version (if compiling from source): 9.2.1
- CUDA/cuDNN version: None
- GPU model and memory: None

**Describe the current behavior**
The IntArrayFromInitializer routine maintains a reference to the initializer_list's data.
The initializer_list is destroyed at the end of the function's scope as it is not a reference, and there is no guarantee that the initializer_list will exist beyond the function's scope.
This causes Segfaults and Corruption of the memory being referenced as revealed from testing "tensorflow/lite/micro/kernels:elementwise_test". This is illustrated in the screenshot attached below.

**Describe the expected behavior**
There should be an established certainty that the data being pointed to will be valid beyond the function scope. This can be achieved by using C++ constructs; concrete types instead of the error-prone C-style pointer constructs.

**Code to reproduce the issue**
test cases available under:
tensorflow/lite/micro/kernels/elementwise_test.cc

**Other info / logs**
See screenshots attached below:

The culprit (tensorflow/lite/micro/testing/test_utils.h):
![Screenshot from 2020-01-09 11-06-37](https://user-images.githubusercontent.com/26050398/72058282-24310480-32d0-11ea-940e-a1faf1fbc17e.png)

The test log (tensorflow/lite/micro/kernels/elementwise_test.cc):
![Screenshot from 2020-01-09 11-02-22](https://user-images.githubusercontent.com/26050398/72058451-66f2dc80-32d0-11ea-9059-d85ae50b6fa5.png)

**Comment by MeghnaNatraj** [comment]
Hello, 

This is currently being fixed internally. However, as there are many references of the code (tensorflow/lite/micro/testing/test_utils.h) throughout the tests, we cannot provide an ETA on the fix. 

Let us know if this is a blocker for you, otherwise feel free to close the issue.

**Comment by lamarrr** [comment]
Alright, Will do!
