### ISSUE TITLE
Init operations did not make model ready. When import form .pbtxt

### ISSUE THREAD

**Issue by HongmingHUANG** [tensorflow/tensorflow#35706]
**System information**
- Ubuntu 16.04:
- TensorFlow installed from (source or binary): pip binary
- TensorFlow version (use command below): 1.13.1
- Python version: 3.5.2
- CUDA/cuDNN version: 10.0 / 7.5
- GPU model and memory: NVIDIA RTX 2080TI

I am trying the tf.io.write_graph() and tf.import_graph_def API to implement model saving and re-building. And I encountered "Init operations did not make model ready" when importing the graph_def into MonitoredSession()

**Here is the importing related source code:**

```
# Some code to load graph_def from .pbtxt file
tf.reset_default_graph()
tf.import_graph_def(graph_def, name='')
with tf.train.MonitoredTrainingSession() as sess:
```

**The bug information is:**
RuntimeError: Init operations did not make model ready.  Init op: group_deps, init fn: None, local_init_op: name: "group_deps_1"
op: "NoOp"
input: "^init_2"
input: "^init_all_tables"
input: "^init_3"
, error: Variables not initialized: global_step, ......

**Comment by amahendrakar** [comment]
@HongmingHUANG,
In order to expedite the trouble-shooting process, could you please provide the complete code to reproduce the issue reported here. Thanks!

**Comment by HongmingHUANG** [comment]
@amahendrakar 
Thanks for your response, Here is the complete code to reproduce the issue:
The input file is a .pbtxt file exported using 
tf.io.write_graph(sess.graph_def, '.', ‘validation.pbtxt')

Here is the code to reproduce the bug (I just reproduced it now)
```
import tensorflow as tf
from google.protobuf import text_format
with open('validation.pbtxt', 'r') as fdin:
    file_content = fdin.read()
    try:
        graph_def = text_format.Parse(file_content, tf.GraphDef())
    except text_format.ParseError as e:
        raise IOError("Cannot parse file %s: %s."
                        % (filename, str(e)))
tf.reset_default_graph()
tf.import_graph_def(graph_def, name='')
with tf.train.MonitoredTrainingSession() as sess:
        sess.graph.as_default()
# Report error
```

**Comment by amahendrakar** [comment]
Was able to reproduce the issue. Please find the Gist [here](https://colab.sandbox.google.com/gist/amahendrakar/8514be1f6f1d7d5322617c413ec417fa/35706.ipynb). Thanks!

**Comment by ymodak** [comment]
You may refer #https://github.com/tensorflow/tensorflow/issues/14391

**Comment by HongmingHUANG** [comment]
> You may refer #14391

Hi ymodak, I tried the solution in #14391 that add a new checkpoint folder in the session parameter like this:
`
with tf.train.MonitoredTrainingSession(checkpoint_dir = '/tmp/new_checkpoint') as sess:
    sess.run(target_node)
`
However, I still meet the same bug.
It seems that just change the checkpoint is not enough. Do we also need to write the init function by ourselves?

**Comment by ymodak** [comment]
Apologies for the delay in response. Is this still an issue? Thanks!
