### ISSUE TITLE
[TF2.0] Build from sources to support CUDA9

### ISSUE THREAD

**Issue by SmileTM** [tensorflow/tensorflow#35701]
As we all know ，the tf2-cuda9.0 haven't the pkg by official.
But in some server， we can't update the GPU driver to support CUDA10. 
So we need to bazel the pkg by ourself.
I bazeled the  tensorflow2.0 pkgs that support cuda9.0 for py3.5 3.6 3.7 . 
I hope it could help more people.

But ，sometimes ，it will have this error.

```shell
W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcusolver.so.9.0';.....undefined symbol: GOMP_critical_end;

```

and I find if you add the two lines of code, it will work.

```python
import ctypes
ctypes.CDLL("libgomp.so.1", mode=ctypes.RTLD_GLOBAL)
```

I'm not sure if these two lines of code have some side effects.
So I need the official to explain how to avoid this error，and the  side effects will  bring by the two lines of code.

And the pkg and installation method in this link.
https://github.com/SmileTM/Tensorflow2.X-GPU-CUDA9.0

**Comment by ravikyram** [comment]
@SmileTM 

TF 2.0-GPU supports cuda 10.0. I see that you are using cuda 9.0 can you please switch to cuda 10.0 and let us know how it progresses.Please, follow the instructions from [TensorFlow website](https://www.tensorflow.org/install/source) .Thanks!

**Comment by SmileTM** [comment]
> @SmileTM
> 
> TF 2.0-GPU supports cuda 10.0. I see that you are using cuda 9.0 can you please switch to cuda 10.0 and let us know how it progresses.Please, follow the instructions from [TensorFlow website](https://www.tensorflow.org/install/source) .Thanks!


I can't update my gpu-drive to cuda10.

 So I Bazeled these pkgs from source code to help some people like me.

I just want you to verify the viability of my pkgs and my method. 

Thank you！
