### ISSUE TITLE
TensorFlow 2.1.0 requires scipy

### ISSUE THREAD

**Issue by drasmuss** [tensorflow/tensorflow#35709]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): binary
- TensorFlow version: 2.1.0
- Python version: 3.6.10
- Installed using virtualenv? pip? conda?: pip
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

**Describe the problem**

TensorFlow 2.1.0 added `scipy` as a required dependency.  However, as far as I can tell TensorFlow doesn't actually need scipy. Judging from this PR https://github.com/tensorflow/tensorflow/pull/35278 (which introduced the requirement), the intention was just to avoid a bug with scipy==1.4.0. But it seems that simply not having scipy installed would be another way to avoid that bug, and adding scipy as a requirement to every tensorflow installation seems like kind of a drastic solution. It also wasn't mentioned in the release notes at all, so I'm wondering whether this was an intentional change or not.

**Provide the exact sequence of commands / steps that you executed before running into the problem**

`pip install tensorflow`

**Comment by mihaimaruseac** [comment]
It was an intentional change but we might revisit by the time we release TF 2.2

**Comment by ahtik** [comment]
By the way, `scipy` dep already existed for `TEST_PACKAGES` included by tests_require at https://github.com/tensorflow/tensorflow/blob/ca2b3d0f9b7e0e5a5701f9175e63a320a3148d4d/tensorflow/tools/pip_package/setup.py#L129

Might be worth moving that version to scipy >= 1.4.1 as well or just getting rid of it, as it's now duplicated with `INSTALL_PACKAGES`?

Less relevant if `scipy` dep is reverted for TF 2.2.

In general, these gcc version differences that segfault pybind11 between different wheels are possibly not a battle for tensorflow scope as long as manylinux-related PEP xxx gcc etc build-related versions are followed?

**Comment by mhurliman** [comment]
Trying to get a build of Tensorflow 2.1.0 onto Raspberry Pi Zero and having a _terrible_ time building scipy 1.4.1 locally. First, it doesn't automatically enforce pybind11 is installed - a hard dependency. Secondly, it causes an internal compiler error when building some *fft.cxx file.

**Comment by frankier** [comment]
It's unfortunate that pip does not support any kind of "conflicts with" declaration. I think given this, the only better solution available now is to detect whether an incompatible version of scipy is installed early on and issue a warning, rather than adding a spurious dependency.

**Comment by mihaimaruseac** [comment]
Should be solved by  @tensorflow-copybara  in 78026d6
