### ISSUE TITLE
Problem on building tensorflow optimized for AVX2  CPU

### ISSUE THREAD

**Issue by WisarutBholsithi** [tensorflow/tensorflow#35703]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution : **Debian GNU/Linux 10 (buster)**
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): **source**
- TensorFlow version: **2.1**
- Python version: **3.6.9**
- Installed using virtualenv? pip? conda?: **N/A**
- Bazel version (if compiling from source): **1.2.1**
- GCC/Compiler version (if compiling from source): **8.3.0**
- CUDA/cuDNN version: **N/A**
- GPU model and memory: **N/A**

**Describe the problem**

Hi everybody,

I tried to build Tensorflow from the source as the way to deal with problem **Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX AVX2** since the existing installation of tensorflow by pip install does not allow the optimization for using in my laptop that use CPU that use AVX2.

However, the bazel compiler keeps giving me a headache of Fatal Failed to sync ... Permission denied. as shown in the command and  jpeg file I attached

**Provide the exact sequence of commands / steps that you executed before running into the problem**

> FATAL: failed to sync '/root/.cache/bazel/_bazel_root/install/84defa6eb1e9416bf92d6f89ab2d4f31.tmp.10122/A-server.jar': (error: 13): Permission denied

How can I deal with this kind of troubles on building and installing tensorflow optimized for my CPU? Please help me out. 

BTW, I run tensorflow through docker container since my Laptop OS is Windows 10 though. 
![ProblemonCompilingTensorFlowfromSource](https://user-images.githubusercontent.com/58510558/72069742-6d0dab00-331a-11ea-8a5f-6e0b02b09572.jpg)

**Comment by gadagashwini** [comment]
@WisarutBholsithi,
Provide the exact sequence of commands / steps that you executed before running into the problem.

**Comment by gadagashwini** [comment]
@WisarutBholsithi, Did you check the read and execute permission on the file. Thanks

**Comment by gadagashwini** [comment]
@WisarutBholsithi, Looks like the read and execute permission on the file is disabled. Navigate to the folder and change the file permission,
`chmod 777 *`. Thanks
