### ISSUE TITLE
tf2.0 & 2.1 in colab tpu get 'Compilation failure: Asked to propagate a dynamic dimension from..' error

### ISSUE THREAD

**Issue by ofpppppppdbfjs** [tensorflow/tensorflow#35708]
def simple_residual_block(input, weight_decay=1e-4):

    input_channels = input.get_shape().as_list()[-1]

    x = BatchNormalization()(input)
    x = Activation('relu')(x)
    x = Convolution2D(input_channels// 4, 1, 1, kernel_regularizer=l2(weight_decay))(x)

    x = BatchNormalization()(x)
    x = Activation('relu')(x)
    x = Convolution2D(input_channels // 4, 3, 1, padding='same', kernel_regularizer=l2(weight_decay))(x)

    x = BatchNormalization()(x)
    x = Activation('relu')(x)
    x = Convolution2D(input_channels, 1, 1, kernel_regularizer=l2(weight_decay))(x)

    x = add([x, input])
    return x

def attention_block(input, encoder_depth, weight_decay=1e-4):

    assert input.get_shape().as_list()[-2]>=math.pow(2,encoder_depth)*8, 'input width should >= pow(2,encoder_depth)*8'

    input_channels = input.get_shape().as_list()[-1]
    input = simple_residual_block(input, weight_decay)
    output_trunk = simple_residual_block(input, weight_decay)
    output_trunk = simple_residual_block(output_trunk, weight_decay)
    output_soft_mask = MaxPooling2D(padding='same')(input)
    output_soft_mask = simple_residual_block(output_soft_mask, weight_decay)

    skip_connections = []

    for i in range(encoder_depth):
        output_skip_connection = simple_residual_block(output_soft_mask, weight_decay)
        skip_connections.append(output_skip_connection)
        output_soft_mask = MaxPooling2D(padding='same')(output_soft_mask)
        output_soft_mask = simple_residual_block(output_soft_mask, weight_decay)

    skip_connections = list(reversed(skip_connections))

    for i in range(encoder_depth):
        output_soft_mask = simple_residual_block(output_soft_mask, weight_decay)
        output_soft_mask = UpSampling2D()(output_soft_mask)
        output_soft_mask = add([output_soft_mask, skip_connections[i]])

    output_soft_mask = simple_residual_block(output_soft_mask, weight_decay)
    output_soft_mask = UpSampling2D()(output_soft_mask)

    output_soft_mask = Convolution2D(input_channels, 1, 1)(output_soft_mask)
    output_soft_mask = Convolution2D(input_channels, 1, 1)(output_soft_mask)
    output_soft_mask = Activation('sigmoid')(output_soft_mask)

    output = Lambda(lambda x: x + 1)(output_soft_mask)
    output = Multiply()([output, output_trunk])
    output = simple_residual_block(output, weight_decay)

    return output

 call attention_block with encoder_depth >1 get this err, 

and setting 'strategy.experimental_enable_dynamic_batch_size = False' do not work

Epoch 1/200
496/497 [============================>.] - ETA: 0s - loss: 4.5875 - accuracy: 0.2602
---------------------------------------------------------------------------
UnimplementedError                        Traceback (most recent call last)
<ipython-input-1-db2f1c8a2097> in <module>()
    188                                 validation_data=(x_validation, y_validation),
    189                                 validation_steps=x_validation.shape[0] // batch_size,
--> 190                                 shuffle=True)
    191             show_train_history(history, 'accuracy', 'val_accuracy')
    192             show_train_history(history, 'loss', 'val_los')

11 frames
/usr/local/lib/python3.6/dist-packages/six.py in raise_from(value, from_value)

UnimplementedError:  Compilation failure: Asked to propagate a dynamic dimension from hlo %add.5706 = f32[128,8,8,64]{3,2,1,0} add(f32[128,8,8,64]{3,2,1,0} %add.5705, f32[128,8,8,64]{3,2,1,0} %add.5678), metadata={op_type="AddV2" op_name="model/add_8/add"}@{}@0 to hlo %custom-call.5725 = f32[128,16,16,64]{3,2,1,0} custom-call(f32[128,8,8,64]{3,2,1,0} %add.5706), custom_call_target="ResizeNearest", metadata={op_type="ResizeNearestNeighbor" op_name="model/up_sampling2d/resize/ResizeNearestNeighbor"}, backend_config="\"01\"", which is not implemented.
	TPU compilation failed
	 [[{{node tpu_compile_succeeded_assert/_8555495338583930365/_5}}]]
Additional GRPC error information:
{"created":"@1578578190.016458329","description":"Error received from peer","file":"external/grpc/src/core/lib/surface/call.cc","file_line":1039,"grpc_message":" Compilation failure: Asked to propagate a dynamic dimension from hlo %add.5706 = f32[128,8,8,64]{3,2,1,0} add(f32[128,8,8,64]{3,2,1,0} %add.5705, f32[128,8,8,64]{3,2,1,0} %add.5678), metadata={op_type="AddV2" op_name="model/add_8/add"}@{}@0 to hlo %custom-call.5725 = f32[128,16,16,64]{3,2,1,0} custom-call(f32[128,8,8,64]{3,2,1,0} %add.5706), custom_call_target="ResizeNearest", metadata={op_type="ResizeNearestNeighbor" op_name="model/up_sampling2d/resize/ResizeNearestNeighbor"}, backend_config="\"01\"", which is not implemented.\n\tTPU compilation failed\n\t [[{{node tpu_compile_succeeded_assert/_8555495338583930365/_5}}]]","grpc_status":12} [Op:__inference_distributed_function_203353]

Function call stack:
distributed_function -> distributed_function

**Comment by ofpppppppdbfjs** [comment]
UpSampling2D  cause this problem, but do not know why and how to fix it , i tested tf v2.1  have same error to

**Comment by dharakotecha** [comment]
Hi,
How did you solve this? I am facing the same error.

**Comment by deepwilson** [comment]
Why is the issue closed?

I too face this issue.

**Comment by RayXie29** [comment]
I did get the same problem when I was trying to train unet with TPU. Just like @ofpppppppdbfjs said, the problem is caused by upsampling2D layer. Once I replaced the upsampling2D layer with conv2d_transpose layer, the problem sloved. 
But I still don't know why Upsampling2D will cause this problem, and maybe there are some others layers might cause this problem either. I suggest that you can replace some of your layers in model with similar function layers to find out what cause this issue, until the real issue is solved by Tensorflow team.

**Comment by mayowaosibodu** [comment]
> I did get the same problem when I was trying to train unet with TPU. Just like @ofpppppppdbfjs said, the problem is caused by upsampling2D layer. Once I replaced the upsampling2D layer with conv2d_transpose layer, the problem sloved.
> But I still don't know why Upsampling2D will cause this problem, and maybe there are some other layers might cause this problem either. I suggest that you can replace some of your layers in model with similar function layers to find out what cause this issue, until the real issue is solved by Tensorflow team.

In cases where your UpSampling2D layers could be substituted with UpSampling1D, doing that also seems to make the problem go away.
