### ISSUE TITLE
AttributeError: _ckpt_saved_epoch when using MultiWorkerMirroredStrategy TF2.0

### ISSUE THREAD

**Issue by FloP93** [tensorflow/tensorflow#35705]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
Windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
pip
- TensorFlow version (use command below):
v2.0.0-rc2-26-g64c3d382ca 2.0.0
- Python version: 
3.6.9
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
10.0, 7.6.2
- GPU model and memory:
GeForce GTX 1070 and GeForce GTX 1080

**Describe the current behavior**
Crash when writing Checkpoint (or stuck when writing log for tensorboard)

**Describe the expected behavior**
Write a checkpoint and a Tensorboardlog

**Code to reproduce the issue**
```
os.environ['TF_CONFIG'] = json.dumps({
    'cluster': {
        "worker": ["10.10.1.168:1234"],
        'chief': ["10.10.1.60:2345"]
    },
    'task': {'type': 'chief', 'index': 0}
})
strategy = tf.distribute.experimental.MultiWorkerMirroredStrategy()

def get_label(file_path, class_names):
  parts = tf.strings.split(file_path, os.path.sep)
  return parts[-2] == class_names

def parse_image(filename):
    parts = tf.strings.split(filename, "\\")
    label = get_label(filename, CLASS_NAMES)
    image = tf.io.read_file(filename)
    image = tf.image.decode_png(image, channels=3)
    image = tf.image.convert_image_dtype(image, tf.float32)
    image = tf.image.resize(image, [299,299])
    return image, label

def make_dataset_unbatched():
    images_ds = list_ds.map(parse_image, num_parallel_calls=AUTOTUNE)
    images_ds = images_ds.shuffle(BATCH_SIZE)
    images_ds = images_ds.repeat(epochs)
    images_ds = images_ds.prefetch(BUFFER_SIZE)
    return images_ds

datasetFilePath = "D:\TrainData\BalancedData"
IMAGESIZE = 299
AUTOTUNE = tf.data.experimental.AUTOTUNE
datasetPath = pathlib.Path(datasetFilePath)
list_ds = tf.data.Dataset.list_files(str(datasetPath/"*/*"))
num_elements = tf.data.experimental.cardinality(list_ds).numpy()

CLASS_NAMES = np.array([item.name for item in datasetPath.glob('*')])

epochs = 2
def build_and_compile_model():
    base_model =tf.keras.applications.InceptionV3(include_top=False, weights = "imagenet", input_shape=(299,299,3))

    base_model.trainable = True
    x = base_model.output
    x = tf.keras.layers.GlobalAveragePooling2D(name="avg_pool")(x)
    x = tf.keras.layers.Dense(256, activation="relu")(x)
    predictions = tf.keras.layers.Dense(2, activation="softmax")(x)
    model = tf.keras.models.Model(inputs=base_model.input, outputs=predictions)

    base_learning_rate = 0.00001
    model.compile(optimizer=tf.keras.optimizers.Adam(lr=base_learning_rate),
                 loss="categorical_crossentropy",
                 metrics=["accuracy"])
    return model
logdir = os.path.join("Z:\Tensorflow\TensorboardLogs", datetime.datetime.now().strftime("%Y%m%d-%H%M%S"))
callbacks = [tf.keras.callbacks.ModelCheckpoint(filepath="Z:\Tensorflow\Checkpoints"), 
             tf.keras.callbacks.TensorBoard(logdir, histogram_freq=1)]

with strategy.scope():
    dataset = make_dataset_unbatched().batch(BATCH_SIZE, drop_remainder=True)
    multi_worker_model = build_and_compile_model()

history = multi_worker_model.fit(dataset, epochs=epochs, steps_per_epoch=50, callbacks=callbacks)
``` 

**Other info / logs**
[ckpt_error.txt](https://github.com/tensorflow/tensorflow/files/4040557/ckpt_error.txt)

This log happens with the checkpoint in the code, and with only the tensorboard-log as checkpoint the chief stops right at the end of the first epoch and nothing else happens.

I hope someone can help me with this.

**Comment by huhuigou** [comment]
have you solve this problem?  i also met it

**Comment by FloP93** [comment]
> have you solve this problem? i also met it

Unfortunatly not, 
because its just a side project i put it on ice for now

**Comment by huhuigou** [comment]
> > have you solve this problem? i also met it
> 
> Unfortunatly not,
> because its just a side project i put it on ice for now

i solve it by chaging tf save format to hdf5. 

filepath = 'weights.{epoch:02d}-{val_loss:.2f}.hdf5'
callbacks = [tf.keras.callbacks.ModelCheckpoint(filepath=filepath, verbose=1)]

**Comment by FloP93** [comment]
> i solved it by chaging tf save format to hdf5.
> 
> filepath = 'weights.{epoch:02d}-{val_loss:.2f}.hdf5'
> callbacks = [tf.keras.callbacks.ModelCheckpoint(filepath=filepath, verbose=1)]

Thanks for the hint, i will try that as soon as i have time to work on that project again!

**Comment by guptapriya** [comment]
Hi - we believe this should be fixed in the TF nightly (or you can also try with https://pypi.org/project/tensorflow/2.2.0rc3/) . Please re-open if not fixed.
