### ISSUE TITLE
TensorFlow<1.15 documentation redirects to GitHub

### ISSUE THREAD

**Issue by artemmavrin** [tensorflow/tensorflow#35717]
## URL(s) with the issue:

For example,
https://www.tensorflow.org/versions/r1.14/api_docs/python/tf/train
https://www.tensorflow.org/versions/r1.14/api_docs/python/tf/estimator/Estimator
https://www.tensorflow.org/versions/r1.14/api_docs/python/tf/keras/Model

## Description of issue (what needs changing):

The links above currently redirect to GitHub. The 1.15 links work:

https://www.tensorflow.org/versions/r1.15/api_docs/python/tf/train
https://www.tensorflow.org/versions/r1.15/api_docs/python/tf/estimator/Estimator
https://www.tensorflow.org/versions/r1.15/api_docs/python/tf/keras/Model

I have projects using TensorFlow 1.14, so I would like to use the 1.14 docs for reference.

Will the 1.14 docs be back up?

**Comment by jvishnuvardhan** [comment]
@artemmavrin Where did you find those links on Tensorflow website? Thanks!

**Comment by artemmavrin** [comment]
@jvishnuvardhan The links are similar to links I've been using as recently as earlier this week to access TensorFlow 1.14 documentation.

The last such working link in by browser history is https://www.tensorflow.org/versions/r1.14/api_docs/python/ from January 9, which currently redirects to https://github.com/tensorflow/docs/tree/r1.14/site/en/api_docs/python.

I've been using the 1.15 documentation and 1.14 source code for reference in the meantime, but it would be very convenient for my projects that use 1.14 if I had the 1.14 documentation at my disposal.

Thanks!

**Comment by lamberta** [comment]
HI @artemmavrin, this is works-as-intended.

tensorflow.org is focused on TF2 now, but we'll continue to host the latest 1.x version on the site (1.15). We're archiving older versions in the tensorflow/docs GitHub repo under the version branch: https://github.com/tensorflow/docs/tree/r1.14/site/en
These docs can be navigated and previewed using the GitHub previewer.
