### ISSUE TITLE
Building tensorflow from source

### ISSUE THREAD

**Issue by fjrodriguezdiaz** [tensorflow/tensorflow#3571]
Operating System: CentOS-7
CUDA: 8.0
cuDNN: 5.0
bazel: 0.3.0-2016-07-29
gcc: 4.8.5

When I try to build tensorflow from source following the instructions in https://www.tensorflow.org/versions/r0.9/get_started/os_setup.html, in particular, when executing:
bazel build -c opt --config=cuda //tensorflow/cc:tutorials_example_trainer

I get the following error:

ERROR: /home/fjrodriguez/tensorflow/tensorflow/core/kernels/BUILD:854:1: undeclared inclusion(s) in rule '//tensorflow/core/kernels:crop_and_resize_op_gpu':
this rule is missing dependency declarations for the following files included by 'tensorflow/core/kernels/crop_and_resize_op_gpu.cu.cc':
 
I have tried many times, the error is always similar, undeclared inclusion(s) in rule xxxx, but the xxxx is changing depending on the execution.

I've tried the solution proposed at https://github.com/tensorflow/tensorflow/issues/2413 without any luck
 
Thanks in advance!

**Comment by michaelisard** [comment]
CUDA 8 is not yet fully supported. Does it work with 7.5?

**Comment by fjrodriguezdiaz** [comment]
I haven't tried since GTX1080 is not supported (I think) by CUDA 7.5

**Comment by michaelisard** [comment]
Yes sorry I didn't realize you had GTV1080 I have seen several people who can't get that to work with 7.5. @martinwicke is there a required bazel version mismatch here?

**Comment by dfisla** [comment]
Want to second this, cuda 7.5 has issues with GTX 1080 (random generation, etc.) and cuda 8.0RC is not supported to tensorflow. I only manged to get torch ml framework working.

**Comment by tomvars** [comment]
I've also had this issue with 
Operating System: Ubuntu 16.04
CUDA: 8.0
cuDNN: 5.0
bazel: 0.3.0-2016-07-29
gcc: 4.9

**Comment by yaroslavvb** [comment]
CUDA 8.0 also has a 50% improvement on matmul for GTX 980 over CUDA 7.5, I hit similar issue and solution is to modify CROSSTOOL file -- https://github.com/tensorflow/tensorflow/issues/3431

**Comment by fjrodriguezdiaz** [comment]
I just tried the solution in https://github.com/tensorflow/tensorflow/issues/3431 and it works. Thanks!

**Comment by martinwicke** [comment]
In summary, setting the version explicitly should work.
