### ISSUE TITLE
tf.distribute.experimental.TPUStrategy doesn't render Stable correctly

### ISSUE THREAD

**Issue by uchua** [tensorflow/tensorflow#35712]
## URL(s) with the issue:

https://www.tensorflow.org/api_docs/python/tf/distribute/experimental/TPUStrategy?version=stable

## Description of issue (what needs changing):

On the documentation page for tf.distribute.experimental.TPUStrategy, the Stable documentation is shown as the raw text of the documentation (looks like it's a combination of HTML and Markdown?).

Example below:

<img width="1664" alt="Screen Shot 2020-01-09 at 1 22 11 PM" src="https://user-images.githubusercontent.com/11432284/72094036-87786200-32e3-11ea-89ca-253b45a5ad7b.png">

Clicking "See Nightly" it renders correctly, but clicking "See Stable" again it still shows the raw text again.

**Comment by ravikyram** [comment]
@uchua 

Looks like browser issue.Can you please check again. I am not seeing any issue with the documentation.Thanks!

**Comment by uchua** [comment]
Yup looks like it loads correctly now. I tried it on Chrome on a couple computers yesterday and they all were doing the same thing, so I'm not sure what would've changed.
