### ISSUE TITLE
parallel_for: No converter defined for MatrixSolve

### ISSUE THREAD

**Issue by carterkd** [tensorflow/tensorflow#35719]
I need to calculate the Jacobian of a function, where `tf.linalg.solve` is part of the function. I can usually use `parallel_for` but `pfor` does not support the `MatrixSolve` op, requiring a fallback to a slow while loop. It would be great to add a converter for `MatrixSolve` to `parallel_for.` Note that below, my example can be easily mathematically simplified, but in my actually use case it cannot be.

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 1.14.0
- Python version: 3.7.3

**Code to reproduce the issue**

```python
import tensorflow as tf
from tensorflow.python.ops.parallel_for.gradients import jacobian
import numpy as np

sess = tf.InteractiveSession()
print(tf.__version__)

x = tf.compat.v1.placeholder(tf.float64, shape = [3])
y = tf.compat.v1.placeholder(tf.float64, shape = [3])
z = tf.reshape(tf.linalg.solve(tf.linalg.diag(x), tf.reshape(y, [-1, 1])), [-1])

jac = jacobian(z, x)

print(sess.run(jac, feed_dict = {x: np.array([1., 1., 1.]), y: np.array([1., 2., 3.])}))
```

**Describe the current behavior**

```python
ValueError: No converter defined for MatrixSolve
name: "loop_body/gradients/MatrixSolve_grad/MatrixSolve"
op: "MatrixSolve"
input: "MatrixDiag"
input: "loop_body/gradients/Reshape_1_grad/Reshape"
attr {
  key: "T"
  value {
    type: DT_DOUBLE
  }
}
attr {
  key: "adjoint"
  value {
    b: true
  }
}

inputs: [WrappedTensor(t=<tf.Tensor 'MatrixDiag:0' shape=(3, 3) dtype=float64>, is_stacked=False, is_sparse_stacked=False), WrappedTensor(t=<tf.Tensor 'loop_body/gradients/Reshape_1_grad/Reshape/pfor/Reshape:0' shape=(3, 3, 1) dtype=float64>, is_stacked=True, is_sparse_stacked=False)]. 
Either add a converter or set --op_conversion_fallback_to_while_loop=True, which may run slower
```

**Describe the expected behavior**

I should get
```
array([[-1.,  0.,  0.],
       [ 0., -2.,  0.],
       [ 0.,  0., -3.]])
```

**Comment by carterkd** [comment]
I notice from the `pfor` [code](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/ops/parallel_for/pfor.py) that both `tf.linalg.cholesky` and `tf.linalg.triangular_solve` are supported. I'll use this as a work around until this is fixed (since I'm solving with a symmetric positive definite matrix):
```python
import tensorflow as tf
from tensorflow.python.ops.parallel_for.gradients import jacobian
import numpy as np

### work around because there is no converter for MatrixSolve in pfor
### I can change this just to tf.linalg.solve() when tensorflow fixes this
def chol_triangular_solve(a, b):
    chol_a = tf.linalg.cholesky(a)
    return tf.linalg.triangular_solve(tf.transpose(chol_a), tf.linalg.triangular_solve(chol_a, b, lower = True), lower = False)

sess = tf.InteractiveSession()
print(tf.__version__)

x = tf.compat.v1.placeholder(tf.float64, shape = [3])
y = tf.compat.v1.placeholder(tf.float64, shape = [3])
z = tf.reshape(chol_triangular_solve(tf.linalg.diag(x), tf.reshape(y, [-1, 1])), [-1])

jac = jacobian(z, x)

print(sess.run(jac, feed_dict = {x: np.array([1., 1., 1.]), y: np.array([1., 2., 3.])}))
```

This is not very elegant, but I get the desired output:
```python
[[-1.  0.  0.]
 [ 0. -2.  0.]
 [ 0.  0. -3.]]
```

**Comment by ravikyram** [comment]
I have tried on colab with TF version 1.14, 1.15 and was able to reproduce the issue.Please,find the gist [here](https://colab.sandbox.google.com/gist/ravikyram/6e311c0490f217bb66e00bfb1aa047ee/untitled546.ipynb). Thanks!

**Comment by agarwal-ashish** [comment]
MatrixSolve is supported at head but not in 1.15. Can you use a more recent version of TF, using compat.v1 if needed.?

**Comment by carterkd** [comment]
Yes, I noticed a bit ago this has been updated since my original post, but I forgot to close this. Sorry about that, and thank you!
