### ISSUE TITLE
Decorating a function with tf.function leads to slower execution

### ISSUE THREAD

**Issue by ifed-ucsd** [tensorflow/tensorflow#35720]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): None
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04.3
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: NA
- TensorFlow installed from (source or binary): Binary
- TensorFlow version (use command below): v1.12.1-21967-gd80fda0 2.1.0-dev20200109
- Python version: 3.6.9
- Bazel version (if compiling from source): NA
- GCC/Compiler version (if compiling from source): NA
- CUDA/cuDNN version: CUDA Version 10.1.243 / cuDNN 7.6.4.38-1
- GPU model and memory: TITAN V, 12GB

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
When decorating a function with tf.function leads to slower execution, even though the function accepts only tf Tensors.

**Describe the expected behavior**
I expect the function to execute as fast or faster with tf.function decoration.

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.
`
import tensorflow as tf
import numpy as np
import time

assert tf.executing_eagerly()

gpus_p = tf.config.experimental.list_physical_devices('GPU')
if gpus_p:
    try:
        # Currently, memory growth needs to be the same across GPUs
        for gpu in gpus_p:
            tf.config.experimental.set_memory_growth(gpu, True)
    except RuntimeError as e:
        # Memory growth must be set before GPUs have been initialized
        print(e)

@tf.function
def sony_forward_tf_function(x,d,xmax):
    return d * tf.round(tf.clip_by_value(x , -xmax , xmax ) / d)

def sony_forward(x,d,xmax):
    return d * tf.round(tf.clip_by_value(x , -xmax , xmax ) / d)

x = tf.random.uniform(shape=[10000,1000])
times = {'tf':[],'tf_function':[],'sony':[],'sony_function':[]}
xmax = tf.Variable(0.5)
step_size = xmax / (tf.pow(2.0, tf.cast(8,dtype=tf.float32) - 1.0) - 1.0)

sony_forward(x,-xmax,xmax)
sony_forward_tf_function(x,-xmax,xmax)

for n in range(1000):
    start = time.time()
    x = sony_forward(x,step_size,xmax)
    stop = time.time()
    times['sony'].append(stop-start)

for n in range(1000):
    start = time.time()
    x = sony_forward_tf_function(x,step_size,xmax)
    stop = time.time()
    times['sony_function'].append(stop-start)
    
print('Sony forward ' + str(1000 * np.mean(times['sony'])) + ' ms')
print('Sony forward w/ tf.function ' + str(1000 * np.mean(times['sony_function'])) + ' ms')
`

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by amahendrakar** [comment]
@ifed-ucsd,
I tried to reproduce the issue with TF- 2.1.0-dev20200109 and did not observe much difference in the execution time. Please find the attached Gist [here](https://colab.sandbox.google.com/gist/amahendrakar/7f86b6ea4efcaa5184803e1ddbed96c8/35720.ipynb).

**Comment by ifed-ucsd** [comment]
@amahendrakar But there is still a difference in runtime, with tf.function decoration leading to slower code. It seems to me that this is not the intended behavior. At the least tf.function decoration should produce functions that run as fast as ones not decorated with tf.function (if not faster)

**Comment by mdanatg** [comment]
Unfortunately, `tf.function` is not always faster for small computations. The reason is quite simple: calling an empty `tf.function` is more expensive than calling an empty Python function. This is especially true when the computations involve scalars, when the speed gained inside the function is too small to recover the cost of calling it.

This can sometimes be avoided by one of the following:
 * vectorizing the computation (e.g. instead of operating on one example at a time, operate on an entire batch); [here](https://www.tensorflow.org/guide/function#batching) is such an example
 * adding `experimental_compile=True`, which can greatly speed up complex scalar computations when XLA support is available
 * you may also speed things up by moving more computation inside the `tf.function` iself

This is something that we're addressing, as there are a few inefficiencies in the current implementation.

**Comment by ifed-ucsd** [comment]
That makes sense. When I add `experimental_compile=True`, I do see the decorated function running faster than the un-decorated one.
