### ISSUE TITLE
Wrong Window Size while training the model

### ISSUE THREAD

**Issue by ManishAradwad** [tensorflow/tensorflow#35728]
## URL(s) with the issue:

https://github.com/tensorflow/examples/blob/master/courses/udacity_intro_to_tensorflow_for_deep_learning/l08c05_forecasting_with_machine_learning.ipynb

## Description of issue (what needs changing):

Window size should be 30 instead of 20 in the description under "Forecasting With Machine Learning".

### Clear description

![Screenshot from 2020-01-10 12-05-13](https://user-images.githubusercontent.com/29497701/72131252-b1905980-33a1-11ea-8cf5-11d089d5316e.png)

--------------------
As we can see under "Linear Model", `window_size=30` while in description it is mentioned as model forecasts, given previous 20 steps.

### Submit a pull request?

Yes...

**Comment by jvishnuvardhan** [comment]
This is already resolved. In the updated docs, the window size is mentioned correctly

> First, we will train a model to forecast the next step given the previous 30 steps, therefore, we need to create a dataset of 30-step windows for training.

I am closing this issue as this was already resolved. Thanks!
