### ISSUE TITLE
How to print tensor within GradientTape scope in TF2?

### ISSUE THREAD

**Issue by yxchng** [tensorflow/tensorflow#35725]
How to print tensor within GradientTape scope in TF2? i.e.

```
with tf.GradientTape() as tape: 
    ...
    print(x)

```

Currently it gives me output like this:

> Tensor("Identity_1:0", shape=(), dtype=float32)

This is very needed for debugging. Shouldn't the concept of computational graph already be discarded in TF2, such that it should work very much like PyTorch? Why is it still behaving like TF1 in GradientTape?

**Comment by NLP-ZY** [comment]
@yxchng try tf.print() insted of print

**Comment by yxchng** [comment]
@NLP-ZY Great. Thanks!
