### ISSUE TITLE
Docker images with tags '2.1.0-gpu-py3' and '2.1.0-gpu-py3-jupyter' are missing on DockerHub

### ISSUE THREAD

**Issue by stengoes** [tensorflow/tensorflow#35733]
Probably the CI has failed to upload those images, because all other combinations of tensorflow:2.1.0[-gpu][-py3][-jupyter] are available.

**Comment by RafayAK** [comment]
Yeah seems like a recurring problem. Even many `devel` docker images are stale. According to this issue, I created [here](https://github.com/tensorflow/tensorflow/issues/35492), this problem should have been fixed by the 31st of December but, unfortunately, hasn't.

**Comment by mihaimaruseac** [comment]
@angerson is OOO for a week more but then I think this would get fixed.

Apologies for the delay, as mentioned on the other issue, our docker person has left and we have to catch up.

**Comment by angerson** [comment]
These images were uploaded some time ago, so this issue can be closed. Thanks for your understanding! Our old Docker maintainer left and we're still hard-pressed to keep up-to-date.
