### ISSUE TITLE
A strange numerical computation bug for the simple dense layer

### ISSUE THREAD

**Issue by David-Mao** [tensorflow/tensorflow#35732]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Mac OS 10.14.5
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.1.0
- Python version: 3.6.8
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: N/A
- GPU model and memory:  N/A

**Describe the current behavior**

See the code:

```
import numpy as np
import tensorflow as tf

m = 3
n = 3
x = tf.cast(np.random.randn(1, m, 32), tf.float32)
z = tf.tile(x, [n, 1, 1])

layer = tf.keras.layers.Dense(32)
w = layer(z)

tf.print(tf.norm(z[0, :, :] - z[1, :, :]), tf.norm(z[1, :, :] - z[n-1, :, :]))
tf.print(tf.norm(w[0, :, :] - w[1, :, :]), tf.norm(w[1, :, :] - w[n-1, :, :]))
```
In the code we replicate the input `x` 3 times and apply a dense layer upon it. We expect to get the same results for the 3 replicates. In fact the 1st and 2nd results are indeed same, while the 3rd result is different. Here is the results of the script above:

```
0 0
0 1.0617149e-06 # this error is not fixed for each run
```
where we expect all results to be 0.

Strangely enough, this bug only appears for some `(m,n)` pairs (in the example above `m=n=3`). I ran the code for all `m` and `n` from 1 to 100 and found that there are ~40% combinations that will cause a bug, but I didn't find any obvious pattern...

**Comment by amahendrakar** [comment]
Was able to reproduce the issue. Please find the Gist [here](https://colab.sandbox.google.com/gist/amahendrakar/88a98b7c3174e2385686af597ae1c8ca/35732.ipynb). Thanks!

**Comment by ravikyram** [comment]
@David-Mao 
Can you please try with `!pip install tf-nightly` version. I am not seeing any issue in nightly version.Please, find the gist [here](https://colab.research.google.com/gist/ravikyram/7d8c3704f0b378a3f95509587f4064ea/untitled608.ipynb).Thanks!

**Comment by David-Mao** [comment]
@ravikyram I tried with '2.2.0-dev20200208' version, and the bug shows again. Now the result is 
<img width="749" alt="image" src="https://user-images.githubusercontent.com/12476624/74125470-7d16e580-4b79-11ea-9cc0-ecfa01fe07ac.png">

**Comment by David-Mao** [comment]
Ping. This bug has still not been fixed in the most recent nightly build.

**Comment by David-Mao** [comment]
Gentle bump.

I noticed that for the latest nightly version, this bug has disappeared in Linux version. However, for the Mac version (I'm using Mac OS 10.14.5 with Python 3.7, the file is `tf_nightly-2.3.0.dev20200617-cp37-cp37m-macosx_10_9_x86_64.whl`), the bug still persists.

**Comment by ravikyram** [comment]
I have tried in TF nightly version (`2.5.0-dev20201029`) and was able to reproduce the issue. Please, find the gist [here](https://colab.research.google.com/gist/ravikyram/5e03737641cca4a4ff20e39abf25b4a7/untitled97.ipynb?authuser=1).Thanks!

**Comment by David-Mao** [comment]
Ping. This is a computation bug and it has been a year. Is there any progress? Thanks

**Comment by sachinprasadhs** [comment]
Was able to reproduce your issue, please find the gist [here](https://colab.research.google.com/gist/sachinprasadhs/a52280b0b292bb071ea4be33de0e9625/35650.ipynb). Thank you.

**Comment by tensorflowbutler** [comment]
Hi There,

 This is a stale issue. As you are using an older version of tensorflow, we are checking to see if you still need help on this issue. Please test the issue with the latest TensorFlow (TF2.7 and tf-nightly). If the issue still persists with the newer versions of TF, please feel free to open it in [keras-team/keras](https://github.com/keras-team/keras/issues) repository by providing details about the issue and a standalone code to reproduce the issue. Thanks! 

 Please note that Keras development has moved to a separate Keras-team/keras repository to focus entirely on only Keras. Thanks!
