### ISSUE TITLE
Hexagon Delegate requirements needs to be clarified?

### ISSUE THREAD

**Issue by DoumanAsh** [tensorflow/tensorflow#35734]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Android
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: SD 820 device
- TensorFlow installed from (source or binary): source, 4b7d5117de4a193bd895ff357dc5286de847c632
- TensorFlow version (use command below): -
- Python version: -
- Bazel version (if compiling from source): 1.2.1
- GCC/Compiler version (if compiling from source): Android NDK clang
- CUDA/cuDNN version: -
- GPU model and memory: -

**Describe the current behavior**

When using Hexagon delegate on 32bit ARM device:

```
CANNOT LINK EXECUTABLE: cannot locate symbol "remote_handle64_open" referenced by "/data/package/lib/libhexagon_interface.so"...
```

As far as I know 820 supports Hexagon acceleration, but it seems libhexagon_interface.so requires extra symbol that is not present on my device system libraries (As far as I know it is part of qualcomm code)

On our 64bit device I see that this function is properly used, there are even some logs from `vendor/qcom/proprietary/commonsys-intf/adsprpc/src/fastrpc_apps_user.c`

So it is more of a question: what is required to run hexagon delegate?

I know that this is pre-built library from vendor, but I wasn't able to find it in Hexagon SDK itself.
So I'm not sure where exactly it is coming from.
If possible I'd appreciate some guidance here

**Describe the expected behavior**

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by jdduke** [comment]
Thanks for the report. Can you provide more details on the specific make/model of your phone, e.g., `adb shell getprop ro.product.device`? We've tested execution on 820, so this could be device-specific.

**Comment by karimnosseir** [comment]
Thanks for the report. We saw similar issue, we have a fix for the issue and will be pushed soon.

Sorry for the trouble.

**Comment by DoumanAsh** [comment]
Thanks for fix!
