### ISSUE TITLE
build aborted analysis of target build_tbb failed

### ISSUE THREAD

**Issue by mrinalsardar** [tensorflow/tensorflow#35738]
I am trying to build `tensorflow` from source for my `Mac` as it supports `SSE4.1`, `SSE4.2`, `AVX` and `FMA` with the following the official documentation (https://www.tensorflow.org/install/source). 
I am using the `master` branch and the following command:

    bazel build -c opt --copt=-mavx --copt=-mfma --copt=-msse4.2 --copt=-msse4.1 --copt=-mfpmath=sse --cxxopt="-D_GLIBCXX_USE_CXX11_ABI=0" --config=mkl --config=ngraph --config=numa --config=noaws --config=nogcp --config=nohdfs --config=nonccl -k //tensorflow/tools/pip_package:build_pip_package

Here goes my `bazel` configuration:

    (base) IKA-XK0X8JG5J:tensorflow_build sardarmrinal$ ./configure 
    WARNING: Running Bazel server needs to be killed, because the startup options are different.
    WARNING: --batch mode is deprecated. Please instead explicitly shut down your Bazel server using the command "bazel shutdown".
    You have bazel 1.2.1 installed.
    Please specify the location of python. [Default is /opt/anaconda3/bin/python]: 

    Found possible Python library paths:
      /opt/anaconda3/lib/python3.7/site-packages
    Please input the desired Python library path to use.  Default is [/opt/anaconda3/lib/python3.7/site-packages]

    Do you wish to build TensorFlow with XLA JIT support? [Y/n]: Y
    XLA JIT support will be enabled for TensorFlow.

    Do you wish to build TensorFlow with OpenCL SYCL support? [y/N]: N
    No OpenCL SYCL support will be enabled for TensorFlow.

    Do you wish to build TensorFlow with ROCm support? [y/N]: N
    No ROCm support will be enabled for TensorFlow.

    Do you wish to build TensorFlow with CUDA support? [y/N]: N
    No CUDA support will be enabled for TensorFlow.

    Do you wish to download a fresh release of clang? (Experimental) [y/N]: N
    Clang will not be downloaded.

    Please specify optimization flags to use during compilation when bazel option "--config=opt" is specified [Default is -march=native -Wno-sign-compare]: 

    Would you like to interactively configure ./WORKSPACE for Android builds? [y/N]: N
    Not configuring the WORKSPACE for Android builds.

    Do you wish to build TensorFlow with iOS support? [y/N]: N
    No iOS support will be enabled for TensorFlow.

    Preconfigured Bazel build configs. You can use any of the below by adding "--config=<>" to your build command. See .bazelrc for more details.
    	--config=mkl         	# Build with MKL support.
    	--config=monolithic  	# Config for mostly static monolithic build.
    	--config=ngraph      	# Build with Intel nGraph support.
    	--config=numa        	# Build with NUMA support.
    	--config=dynamic_kernels	# (Experimental) Build kernels into separate shared objects.
    	--config=v2          	# Build TensorFlow 2.x instead of 1.x.
    Preconfigured Bazel build configs to DISABLE default on features:
    	--config=noaws       	# Disable AWS S3 filesystem support.
    	--config=nogcp       	# Disable GCP support.
    	--config=nohdfs      	# Disable HDFS support.
    	--config=nonccl      	# Disable NVIDIA NCCL support.
    Configuration finished

And I am getting the following error:

    ERROR: /private/var/tmp/_bazel_sardarmrinal/841c8c9a203505f6ff7b50ea63697e9e/external/tbb/BUILD.bazel:12:1: in cmd attribute of genrule rule @tbb//:build_tbb: $(AR) not defined
    ERROR: Analysis of target '//tensorflow/tools/pip_package:build_pip_package' failed; build aborted: Analysis of target '@tbb//:build_tbb' failed; build aborted

Any idea how I can get past this?

FYI: I built one successfully yesterday wihtout `--cxxopt="-D_GLIBCXX_USE_CXX11_ABI=0"` and I wanted to use this option this time. All I did was pulling the latest `master` branch.

Output from `tf_env_collect.sh`:

    == check python ===================================================
        python version: 3.7.4
        python branch: 
        python build version: ('default', 'Aug 13 2019 15:17:50')
        python compiler version: Clang 4.0.1 (tags/RELEASE_401/final)
        python implementation: CPython

    == check os platform ===============================================
    os: Darwin
    os kernel version: Darwin Kernel Version 18.7.0: Sun Dec  1 18:59:03 PST 2019; root:xnu-4903.278.19~1/RELEASE_X86_64
    os release version: 18.7.0
    os platform: Darwin-18.7.0-x86_64-i386-64bit
    linux distribution: ('', '', '')
    linux os distribution: ('', '', '')
    mac version: ('10.14.6', ('', '', ''), 'x86_64')
    uname: uname_result(system='Darwin', node='IKA-XK0X8JG5J', release='18.7.0', version='Darwin Kernel Version 18.7.0: Sun Dec  1 18:59:03 PST 2019; root:xnu-4903.278.19~1/RELEASE_X86_64', machine='x86_64', processor='i386')
    architecture: ('64bit', '')
    machine: x86_64

    == are we in docker =============================================
    No

    == compiler =====================================================
    Apple LLVM version 10.0.1 (clang-1001.0.46.4)
    Target: x86_64-apple-darwin18.7.0
    Thread model: posix
    InstalledDir: /Library/Developer/CommandLineTools/usr/bin

    == check pips ===================================================
    numpy                              1.17.2   
    numpydoc                           0.9.1    
    protobuf                           3.11.2   
    tensorflow                         2.0.0    
    tensorflow-estimator               2.0.1    

    == check for virtualenv =========================================
    False

    == tensorflow import ============================================
    tf.version.VERSION = 2.0.0
    tf.version.GIT_VERSION = unknown
    tf.version.COMPILER_VERSION = 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)

    == env ==========================================================
    LD_LIBRARY_PATH is unset
    DYLD_LIBRARY_PATH is unset

    == nvidia-smi ===================================================
    tf_env_cololect.sh: line 147: nvidia-smi: command not found

    == cuda libs  ===================================================

    == tensorflow installed from info ==================
    Name: tensorflow
    Version: 2.0.0
    Summary: TensorFlow is an open source machine learning framework for everyone.
    Home-page: https://www.tensorflow.org/
    Author-email: packages@tensorflow.org
    License: Apache 2.0
    Location: /opt/anaconda3/lib/python3.7/site-packages
    Required-by: 

    == python version  ==============================================
    (major, minor, micro, releaselevel, serial)
    (3, 7, 4, 'final', 0)

    == bazel version  ===============================================
    Build label: 1.2.1
    Build time: Tue Nov 26 15:27:31 2019 (1574782051)
    Build timestamp: 1574782051
    Build timestamp as int: 1574782051

**Comment by 004307ec** [comment]
I have met the same error with Tensorflow 1.15.0 with XLA and CUDA support enabled (using bazel 0.26.1 which is indicated by the `configure`).

**Comment by gadagashwini** [comment]
@mrinalsardar, did you get a chance to take a look at @004307ec's comment. Thanks!

**Comment by mrinalsardar** [comment]
@gadagashwini Yes I removed all extra options ans used the default setting and that worked for me as well. But I used all combinations of options from the ones I have mentioned and it seems only the default build without any option works and nothing else. Anyways, I think we can close this issue for now. Thanks!
