### ISSUE TITLE
How to add a new op to a pb model

### ISSUE THREAD

**Issue by stoneyang** [tensorflow/tensorflow#35742]
This problem is rather embarassing: I have a pb model at hand but not ready for deployment, because of a missing op. So, I doubt if I could add the required op to the pb and export a new pb for deployment?

Could anyone shed some light please?

**Comment by oanush** [comment]
@stoneyang,
Hi, Please provide more information on the issue,share a standalone code to reproduce the error reported here,also mention the TF version being used. Thanks!

**Comment by oanush** [comment]
@stoneyang ,
Any update on the issue ?Thanks!
