### ISSUE TITLE
Cannot train the person detection test on Tensorflow 2.0

### ISSUE THREAD

**Issue by hshankar61** [tensorflow/tensorflow#35746]
@tensorflow/micro

**System information**
- Host OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- TensorFlow installed from (source or binary):
- Tensorflow version (commit SHA if source):
- Target platform (e.g. Arm Mbed OS, Arduino Nano 33 etc.):

**Describe the problem**

**Please provide the exact sequence of commands/steps when you ran into the problem**

**Comment by MeghnaNatraj** [comment]
This is currently a work in progress. We'll update this issue once we have something we can share.

**Comment by MeghnaNatraj** [comment]
Update:  Due to the lack of of support for full int-8 quantization in TF2.0, we are currently only supporting model training in TF1.x.
