### ISSUE TITLE
fake_quant_with_min_max_vars innefficiencies

### ISSUE THREAD

**Issue by ramonmatas** [tensorflow/tensorflow#35741]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04.3
Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: NA
TensorFlow installed from (source or binary): Binary
TensorFlow version (use command below): v1.12.1-21401-gd908b50 2.1.0-dev20191230
Python version: 3.6.9
Bazel version (if compiling from source): NA
GCC/Compiler version (if compiling from source): NA
CUDA/cuDNN version: CUDA Version 10.1.243 / cuDNN 7.6.4.38-1
GPU model and memory: TITAN V, 12GB

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
A call to fake_quant_with_min_max_vars consistently results in a couple of D2H transfers before the quantization kernel is executed. I believe these transfers are part of ValidateInputTypeAndPlacement and largely dominate the operation cost. This is slowing down to unbearable levels the training of large NNs with fake quantization nodes.

An image of a profile resulting from back to back dependent quantization calls:

![image](https://user-images.githubusercontent.com/24900898/72160140-d7aaff00-338b-11ea-9215-d44440bb65fa.png)

**Describe the expected behavior**

I would expect little to zero overhead before the actual quantization kernel.

**Code to reproduce the issue**

`import tensorflow as tf
import numpy as np
import time
from tensorflow.python import eager
import os

x = tf.random.uniform(shape=[10000,1000])
xmax = tf.Variable(0.5)

eager.profiler.start()

xmax_val = xmax.value()

for n in range(10):
    x = tf.quantization.fake_quant_with_min_max_vars(inputs=x,
                                                    min=xmax_val,
                                                    max=xmax_val,
                                                    num_bits=8)

profiler_result = eager.profiler.stop()
eager.profiler.save(os.path.join('quant','log'), profiler_result)

`

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by suharshs** [comment]
Hi, I dug into this and the issue is that the FakeQuant operation seems to do some computation using the min and max values that must happen on the CPU host. The issue can be resolved  by forcing the min/max variable to be placed on the CPU. I see ValidateInputTypeAndPlacement disappear from my profiler when I do this.

with tf.device('/cpu:0'):
  xmax = ...
  xmax_val = 

...

Hope that helps!
