### ISSUE TITLE
Add a warning that tfds.load can not be used for own Datasets

### ISSUE THREAD

**Issue by PanCakeConnaisseur** [tensorflow/tensorflow#35745]
## URL(s) with the issue:
https://www.tensorflow.org/datasets/api_docs/python/tfds/load

## Description of issue (what needs changing):
Add a warning that `tfds.load()` can not be used for the users own Datasets, i.e. that he creates himself. To a new user trying to to load a Dataset from a set of files it is not obvious that this method is only for pre-made, immutable Datasets.

Although it does say
> Loads the named dataset into a tf.data.Dataset.

i initially interpreted it such that my own Dataset can be assigned a name. 

I was looking for a way to split a Dataset into train and validation subsets and stumbled upon this documentation. I was redirected from https://www.tensorflow.org/datasets/splits which comes up as one of the most prominent search results when searching for "tensorflow Dataset splits" .

## Result
A user who visits https://www.tensorflow.org/datasets/api_docs/python/tfds/load will not spend 1 h of trying to understand all the documentation but will immediately realize that this is only for immutable pre-made Datasets.

**Comment by abhinavsp0730** [comment]
Hey, @PanCakeConnaisseur Tensorflow Datasets (tfds) is used to load the datasets which are present on the library. For knowing which datasets are included in this library you can
Use ```tfds.list_builder()``` . For loading your custom dataset you can use ```tf.data```.

**Comment by baqarhussain11-ux** [comment]
I have made a customized dataset by using different images available online. Can i add that dataset in the tfds directory ?

Looking forward to your replies

**Comment by ymodak** [comment]
Thanks for the issue we can load datasets mentioned in the catalog [here](https://www.tensorflow.org/datasets/catalog/overview).
Perhaps we can add this to the function documentation. Thanks!

**Comment by Conchylicultor** [comment]
@ymodak Sorry for the late answer.

This is not true. `tfds.load` can be use to load any datasets as long as they have been imported. Otherwise TFDS has no way to know where the datasets is declared.

```
import tensorflow_datasets as tfds

import my_custom_dataset  # Register `MyCustomDataset`

tfds.load('my_custom_dataset')
```

**Comment by Conchylicultor** [comment]
I only see this issue now. In the future, please post the `tfds` issues in https://github.com/tensorflow/datasets as TFDS library is developed independently from TensorFlow.
