### ISSUE TITLE
diag_part documentation outdated

### ISSUE THREAD

**Issue by n-gao** [tensorflow/tensorflow#35760]
## URL(s) with the issue: 
https://www.tensorflow.org/api_docs/python/tf/linalg/diag_part?version=nightly

## Description of issue (what needs changing):
The `diag_part` documentation contains old examples of non-existing APIs, it uses `tf.matrix_diag_part` in the examples which does not exist.

**Comment by jvishnuvardhan** [comment]
@n-gao Thanks for reporting the issue. Agree. It is defined correctly in the [`tf-nightly`](https://www.tensorflow.org/api_docs/python/tf/linalg/diag_part?version=nightly) but in the examples `tf.matrix_diag_part` should have been replaced by `tf.linalg.diag_part`. Thanks!

Are you interested in creating PR to update the docs. Thanks!

**Comment by gaebor** [comment]
It's still the old documentation: https://www.tensorflow.org/api_docs/python/tf/linalg/diag_part
