### ISSUE TITLE
[TF2.1] k parameter is ignored in tf.linalg.diag_part

### ISSUE THREAD

**Issue by n-gao** [tensorflow/tensorflow#35761]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): no
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10 64bit (also happens in WSL)
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: 
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.1
- Python version: 3.7
- CUDA/cuDNN version: 10.1 (also happens in tensorflow-cpu)
- GPU model and memory: GTX 1050 2GB

**Describe the current behavior**
Using the `k` parameter of `tf.linalg.diag_part` does not affect anything. The result is still the same.

**Describe the expected behavior**
It should select the super or subdiagonal dependent on `k`.

**Code to reproduce the issue**
```
import tensorflow as tf
import numpy as np
input = np.array([[[1, 2, 3, 4],  # Input shape: (2, 3, 4)
                   [5, 6, 7, 8],
                   [9, 8, 7, 6]],
                  [[5, 4, 3, 2],
                   [1, 2, 3, 4],
                   [5, 6, 7, 8]]])
# this works as expected
tf.linalg.diag_part(input) ==> [[1, 6, 7],  # Output shape: (2, 3)
                                [5, 2, 7]]
# this does not
tf.linalg.diag_part(input, k = 1) ==> [[1, 6, 7], [5, 2, 7]] # still returns the same output
  # [[2, 7, 6], [4, 3, 8]]  Is the expected output
```
This example is taken from the [documentation](https://www.tensorflow.org/api_docs/python/tf/linalg/diag_part?version=nightly), which is also incorrect see #35760.

**Comment by gadagashwini** [comment]
I could replicate the issue with Tf 2.1.
Please find the attached [gist](https://colab.sandbox.google.com/gist/gadagashwini/86984446b8f07eeb590c3bd724a1d556/untitled343.ipynb?authuser=1). Thanks!

**Comment by jvishnuvardhan** [comment]
@n-gao I can reproduce the issue with `TF2.1`. However, the document you are referring is related `tf-nightly`. When I used `tf-nightly`, the output is as you expected. Please check the [gist here](https://colab.sandbox.google.com/gist/jvishnuvardhan/025c3ba3c089f6b4a580072f599239fa/untitled749.ipynb).

Output from the gist
```
<tf.Tensor: shape=(2, 3), dtype=int64, numpy=
array([[2, 7, 6],
       [4, 3, 8]])>
```

Please close the issue if you agree that it was resolved by using `tf-nightly`. Thanks!

**Comment by n-gao** [comment]
I can confirm that this is fixed in `tf-nightly`. Thanks!
