### ISSUE TITLE
Autograph failure with `\`

### ISSUE THREAD

**Issue by emailweixu** [tensorflow/tensorflow#35765]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): v2.1.0-rc2-17-ge5bf8de 2.1.0
- Python version: 3.6
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory: Nvidia RTX 2080

**Describe the current behavior**
Tensorflow shows warning about  failure of autograph
```
WARNING:tensorflow:AutoGraph could not transform <bound method C.f of <__main__.C object at 0x7f4a83904668>> and will run it as-is.
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: expected exactly one node node, found [<gast.gast.FunctionDef object at 0x7f4a47e0d5c0>, <gast.gast.Return object at 0x7f4a47e0df28>]
```
The warning seems to be caused by the backslash `"\"`. 

**Describe the expected behavior**
There should be no such warning

**Code to reproduce the issue**
```python
import tensorflow as tf

class C(object):
    def f(self):
        # error disappear if \ in the following line is removed
        a = \
            1
        return a

obj = C()

@tf.function
def func():
    mem =  obj.f()
    return mem

def main():
    print(func())

if __name__ == "__main__":
    main()
```

**Comment by r-wheeler** [comment]
Just ran into this as well, removing the slash fixed it.

**Comment by jvishnuvardhan** [comment]
I am closing this as the related PR fix merged. Thanks!

**Comment by emailweixu** [comment]
@jvishnuvardhan which PR fixed this bug?

**Comment by jvishnuvardhan** [comment]
@emailweixu Sorry. I thought it was merged into `master` branch in `tensorflow`. It was my mistake. I am reopening it. Thanks!

**Comment by mdanatg** [comment]
Looks like a bug in the parser. `dedent_block` seems to be confused by the backslash continuation:

```
s = r'''
    def f():
        a = \
            1
        return a
'''

print(dedent_block(s))
```

```
def f():
    a = \
    1
return a
```

**Comment by mdanatg** [comment]
For a workaround until this is fixed, note that you can use parentheses to break expressions on multiple lines:

```
a = (
    1)
```
