### ISSUE TITLE
Installation from Docker instructions have wrong argument in workspace flag

### ISSUE THREAD

**Issue by MarcoGorelli** [tensorflow/tensorflow#35774]
I'm trying to [build tensorflow from source](https://www.tensorflow.org/install/source) following the Docker instructions:
>docker pull tensorflow/tensorflow:devel

>docker run -it -w /tensorflow -v $PWD:/mnt -e HOST_PERMS="$(id -u):$(id -g)" \
    tensorflow/tensorflow:devel bash
>
>git pull  # within the container, download the latest source code

Here are the commands I run in the terminal (on Ubuntu), along with their output:
```
$ docker --version
Docker version 19.03.2, build 6a30dfc

$ docker pull tensorflow/tensorflow:devel
devel: Pulling from tensorflow/tensorflow
Digest: sha256:0ee065743f0001f922561bcba914013929a88263ec2a5af21ba35899c3ac85a7
Status: Image is up to date for tensorflow/tensorflow:devel
docker.io/tensorflow/tensorflow:devel

$ docker run -it -w /tensorflow -v $PWD:/mnt -e HOST_PERMS="$(id -u):$(id -g)" \
>     tensorflow/tensorflow:devel bash

________                               _______________                
___  __/__________________________________  ____/__  /________      __
__  /  _  _ \_  __ \_  ___/  __ \_  ___/_  /_   __  /_  __ \_ | /| / /
_  /   /  __/  / / /(__  )/ /_/ /  /   _  __/   _  / / /_/ /_ |/ |/ / 
/_/    \___//_/ /_//____/ \____//_/    /_/      /_/  \____/____/|__/


WARNING: You are running this container as root, which can cause new files in
mounted volumes to be created as the root user on your host machine.

To avoid this, run the container by specifying your user's userid:

$ docker run -u $(id -u):$(id -g) args...

root@4746a002f18e:/tensorflow# 

```

But now, if I run `git pull` as instructed, I get
```
fatal: not a git repository (or any of the parent directories): .git
```

**Comment by MarcoGorelli** [comment]
I asked about this on [StackOverflow](https://stackoverflow.com/q/59693655/9988333), and user Zeitounator suggesting instead passing the flag
```
-w /tensorflow_src
```
which seems to be working

**Comment by gadagashwini** [comment]
@MarcoGorelli, Since issue is resolved can we close this issue. Thanks!

**Comment by MarcoGorelli** [comment]
It's resolved, but will the [instructions](https://www.tensorflow.org/install/source) be updated?

**Comment by tqa236** [comment]
I notice that the instruction is already updated, so this issue is finally resolved?

**Comment by MarcoGorelli** [comment]
looks like it, thanks!
