### ISSUE TITLE
tf.Variable.assign fails silently

### ISSUE THREAD

**Issue by bersbersbers** [tensorflow/tensorflow#35781]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): see below
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10, Linux
- TensorFlow installed from (source or binary): pip
- TensorFlow version (use command below): 2.1.0
- Python version: 3.7.6

**Describe the current behavior**
A special assign operation does nothing (not even raising an error).

**Describe the expected behavior**
At least an error should be raised.

**Code to reproduce the issue**
```
import tensorflow as tf
from tensorflow import keras

# tf.config.experimental_run_functions_eagerly(True)
var = tf.Variable([[3.0]])
model = keras.Sequential([keras.layers.Dense(1, input_shape=(1,))])
model.compile(loss="mse", optimizer="adam")

tf.print(var)  # should print 3, OK
var.assign(model.inputs[0])
tf.print(var)  # should print anything else but 3, or raise an error - but prints 3
```

**Other info / logs**
```
>>> tf.print(var)  # should print 3, OK
[[3]]
>>> var.assign(model.inputs[0])
<tf.Variable 'UnreadVariable' shape=(1, 1) dtype=float32, numpy=array([[3.]], dtype=float32)>
>>> tf.print(var)  # should print anything else but 3, or raise an error - fail.
[[3]]
```

**Comment by oanush** [comment]
Issue replicating for [tf-nightly](https://colab.sandbox.google.com/gist/oanush/6c3deeb470d47befe145856a6c714ae8/35781.ipynb#scrollTo=sNXTUz6w-Pb5) , Thanks!

**Comment by ravikyram** [comment]
@bersbersbers 

I tried in colab with TF nightly version (`2.4.0-dev20200907`) and i can see after assigning operation it is raising an `TypeError:`.Please, find the gist [here](https://colab.research.google.com/gist/ravikyram/85ef6cf191ebdd087c76313532cedb99/untitled318.ipynb).Please, verify once .Thanks!

**Comment by bersbersbers** [comment]
@ravikyram thanks, I double-check that it's throwing an error as expected. I guess TF2.4.0 will have this fix then.

**Comment by ravikyram** [comment]
@bersbersbers 

Thank you for the confirmation. I am closing this issue as it was fixed in TF nightly. Thanks!
