### ISSUE TITLE
The tflite only utilize single core of CPU

### ISSUE THREAD

**Issue by woolpeeker** [tensorflow/tensorflow#35784]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
Ubuntu18.04 and Raspbian 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
Raspberry Pi 4
- TensorFlow installed from (source or binary):
Binary
- TensorFlow version (use command below):
for Ubuntu            v1.14.0-rc1-22-gaf24dc9 1.14.0
for Raspberry Pi     v1.12.1-14948-g43dcb71 1.14.0
- Python version:
3.7

**Describe the current behavior**
The tflite only utilize single core of CPU. I test it on PC and raspberry Pi 4.

**Code to reproduce the issue**
`interpreter = tf.lite.Interpreter(model_content=tflite_model) 

input_details = interpreter.get_input_details() 

output_details = interpreter.get_output_details() 

interpreter.allocate_tensors() 

interpreter.set_tensor(input_details[0]['index'], inp) 

interpreter.invoke() 

result = interpreter.get_tensor(output_details[0]['index'])`

The model I use is here:
[1578756226.tar.gz](https://github.com/tensorflow/tensorflow/files/4050550/1578756226.tar.gz)

**Comment by woolpeeker** [comment]
Is there any way to solve it now?
Thanks for any help.

**Comment by freedomtan** [comment]
I have a patch to enable multi-threading in Python, see https://github.com/tensorflow/tensorflow/pull/25748

**Comment by woolpeeker** [comment]
@freedomtan, thanks for your help. I have tried to build the .whl file from your commit. But the network always crashes when downloading Bazel and other files. Could you provide me the compiled .whl, please? Thanks again.

**Comment by freedomtan** [comment]
@woolpeeker check @PINTO0309's repos https://github.com/PINTO0309/Tensorflow-bin and https://github.com/PINTO0309/TensorflowLite-bin

**Comment by woolpeeker** [comment]
@freedomtan, you're very kind. I have tested it and set_thread_num to 4, the result is very interesting. Because I tries to test the model speed and run `interperter.invoke()` multiple times. In the first several round, it appear several python process which sum up cpu utilization 400%, but then, it disapears and leave only one python process with utilization 200%. The speed is still slower than when I use the complete tensorflow which can reach 400% utilization. But it doesn't matter, the performance is good enough. Thanks again.

**Comment by haozha111** [comment]
I'm a bit interested why it can't reach 400% cpu utilization. Are you calling interpreter.invoke repeatedly for a long duration?

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.
