### ISSUE TITLE
[GPU Backend] Tensorflow Task Graph

### ISSUE THREAD

**Issue by jon-chuang** [tensorflow/tensorflow#35787]
I am wondering about the tensorflow task/op graph. Is scheduling done ahead of time? If I am using an accelerator like a GPU using CUDA, how does the tensorflow runtime synchronise data dependencies? Does it use CUDA streams or something more sophisticated?

**Comment by gadagashwini** [comment]
@jon-chuang, Can you eloborate the issue with code snippet. 
Please provide the information asked in the [template](https://github.com/tensorflow/tensorflow/issues/new/choose). Thanks!

**Comment by gadagashwini** [comment]
@jon-chuang, Please take a look at the [Tensorflow doc](https://www.tensorflow.org/guide/gpu#with_tfdistributestrategy). Thanks!
