### ISSUE TITLE
TPU InternalError with TF 2.1.0 on Google Colab (Assigned device does not have registered OpKernel support for _Arg node iteratorgetnext_iterator)

### ISSUE THREAD

**Issue by MichaelKarpe** [tensorflow/tensorflow#35785]
**System information**
- Custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Google Colab
- TensorFlow installed from (source or binary): use of `%tensorflow_version 2.x`
- TensorFlow version (use command below): 2.1.0-rc1
- Python version: 3.6.9

**Describe the current behavior**

I tried to run @huan's Google Colab Notebook mentioned [here](https://stackoverflow.com/questions/55541881/how-to-convert-tf-keras-model-to-tpu-using-tensorflow-2-0-in-google-colab/55686370#55686370) and available [here](https://colab.research.google.com/github/huan/tensorflow-handbook-tpu/blob/master/tensorflow-handbook-tpu-example.ipynb). It raises the following error:

```
---------------------------------------------------------------------------
InternalError                             Traceback (most recent call last)
<ipython-input-7-79d308ea228d> in <module>()
      4   steps_per_epoch=60,
      5   validation_data=(x_test.astype(np.float32), y_test.astype(np.float32)),
----> 6   validation_freq=5
      7 )
      8 

11 frames
/usr/local/lib/python3.6/dist-packages/six.py in raise_from(value, from_value)

InternalError: Assigned device '/job:worker/replica:0/task:0/device:TPU:0' does not have registered OpKernel support for _Arg
	 [[{{node iteratorgetnext_iterator}}]] [Op:__inference_distributed_function_2822]
```

I tried `tf.compat.v1.disable_eager_execution()` as discussed [here](https://github.com/huan/tensorflow-handbook-tpu/issues/1) but it doesn't work:

```
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-15-5118e7c1b79a> in <module>()
      6   steps_per_epoch=60,
      7   validation_data=(x_test.astype(np.float32), y_test.astype(np.float32)),
----> 8   validation_freq=5
      9 )
     10 

25 frames
/tensorflow-2.1.0/python3.6/tensorflow_core/python/framework/ops.py in convert_to_tensor(value, dtype, name, as_ref, preferred_dtype, dtype_hint, ctx, accepted_result_types)
   1278       graph = get_default_graph()
   1279       if not graph.building_function:
-> 1280         raise RuntimeError("Attempting to capture an EagerTensor without "
   1281                            "building a function.")
   1282       return graph.capture(value, name=name)

RuntimeError: Attempting to capture an EagerTensor without building a function.
```

**Describe the expected behavior**

Not sure if @huan's example should be working given what he explained on [stackoverflow](https://stackoverflow.com/questions/55541881/how-to-convert-tf-keras-model-to-tpu-using-tensorflow-2-0-in-google-colab/55686370#55686370), but I think it should with TF 2.1.0 version.

**Code to reproduce the issue**
Again, @huan's work available [here](https://colab.research.google.com/github/huan/tensorflow-handbook-tpu/blob/master/tensorflow-handbook-tpu-example.ipynb).

**Other info / logs**
I had the same issue with personal code and thought first it was due to `ImageDataGenerator` (see my last comment [here](https://github.com/tensorflow/tensorflow/issues/34346)), however it seems not to be as @huan's example doesn't use it.
I have the same issue on @huan's code with TF 2.1.0 installed with `!pip install tensorflow==2.1.0` in his notebook.

**Comment by ravikyram** [comment]
@MichaelKarpe 

I have tried on colab with TF version 2.1.0-rc1 and was able to reproduce the issue.However i tried with `tf.compat.v1.disable_eager_execution()` and i am not seeing any error message. Please, find the gist [here](https://colab.sandbox.google.com/gist/ravikyram/e148b074900cf92a5ab2fc8730fe4f68/tensorflow-2-0-handbook-tpu-example.ipynb). Is this the expected behavior? Thanks!

**Comment by MichaelKarpe** [comment]
@ravikyram 

Indeed I did put `tf.compat.v1.disable_eager_execution()` after the `with strategy.scope():` section and before the `model.fit()`, which was not correct. It works when I put it before `with strategy.scope():`, thus your gist has the expected behavior.

**Comment by MichaelKarpe** [comment]
Please note however that when I use `tf.compat.v1.disable_eager_execution()` in my notebook using `ImageDataGenerator` (not Huan's code), I get the `AssertionError` from `assert isinstance(x, dataset_ops.DatasetV2)` described by the creator of this [issue](https://github.com/tensorflow/tensorflow/issues/34346). Sorry, I am not able to share code to reproduce the issue for now.

**Comment by MichaelKarpe** [comment]
Please find another issue raising the `DatasetV2` `AssertionError` when using `tf.compat.v1.disable_eager_execution()`: https://github.com/tensorflow/tensorflow/issues/32104#issuecomment-540326691

I tried to switch to a `DatasetV2` from my `ImageDataGenerator` but then I get this [error](https://github.com/tensorflow/tensorflow/issues/34346#issuecomment-569772139).

It seems that there are two issues: one with eager execution and then one with the `DatasetV2` assertion when using `ImageDataGenerator` (which occurs when disabling eager execution).

**Comment by rxsang** [comment]
Can you change "tf.config.experimental_connect_to_host(resolver.master())" to "tf.config.experimental_connect_to_cluster(resolver)"?

Please refer to https://www.tensorflow.org/guide/tpu for the official TPU guide.

**Comment by MichaelKarpe** [comment]
Hi @rxsang @ymodak,

I tried your suggestion but it didn't change anything. I also tried to make a simple reproducible example but I have now the same error as in the other [issue](https://github.com/tensorflow/tensorflow/issues/34346) about `ImageDataGenerator`. Thus I made a reproducible example using `ImageDataGenerator` with the example from the official TPU guide. Please find the gist [here](https://colab.research.google.com/drive/1-03688teNuDZ3Zqjb5VvlPxwt7wdNom6).

**Comment by bestpredicts** [comment]
same probleam , do u slove it ? @MichaelKarpe

**Comment by MichaelKarpe** [comment]
@bestpredicts I didn't look for a workaround, probably you should build your own `ImageDataGenerator` if you want it to work now. `ImageDataGenerator` should work in `TF 2.2.0` given what's been said [here](https://github.com/tensorflow/tensorflow/issues/34346#issuecomment-577996000).

**Comment by huan** [comment]
I believe I have found a way to fix this issue. See https://github.com/huan/tensorflow-handbook-tpu/issues/1#issuecomment-606189444

**Comment by sushreebarsa** [comment]
@MichaelKarpe Could you please let us know if this issue is resolved as per the above [ comment ](https://github.com/tensorflow/tensorflow/issues/35785#issuecomment-606190516) And if it is resolved please feel free to close this issue ?Thank you!
