### ISSUE TITLE
Shape resizing of input in tf.batch_self_adjoint_eig

### ISSUE THREAD

**Issue by arjunsesh** [tensorflow/tensorflow#3579]
GitHub issues are for bugs / installation problems / feature requests.  
For general support from the community, see [StackOverflow](https://stackoverflow.com/questions/tagged/tensorflow).
To make bugs and feature requests more easy to find and organize, we close issues that are deemed
out of scope for GitHub Issues and point people to StackOverflow.

For bugs or installation issues, please provide the following information.
The more information you provide, the more easily we will be able to offer
help and advice.

### Environment info
Operating System: Linux

### Steps to reproduce
1. Create any tensor (tf.Variable or tf.constant) containing batches of self adjoint matrices (call this B) and note its shape
2. run something like alpha_U = tf.batch_self_adjoint_eig(B)
3. look at B's shape again - the second to last dimension increments by 1

### What have you tried?
1. selecting all but the last element of the second to last dimension solves the problem, but is hacky

### Logs or other output that would be helpful
(If logs are large, please upload as attachment).
 B
\<tf.Tensor 'Const_15:0' shape=(1, 3, 3) dtype=float32\>
sess.run(B)
array([[[ 8.,  5.,  3.],
        [ 5.,  2.,  4.],
        [ 3.,  4.,  4.]]], dtype=float32)
alpha_U = tf.batch_self_adjoint_eig(B)
 B
\<tf.Tensor 'Const_15:0' shape=(1, 4, 3) dtype=float32\>
 sess.run(B)
array([[[ 8.,  5.,  3.],
        [ 5.,  2.,  4.],
        [ 3.,  4.,  4.]]], dtype=float32)

**Comment by michaelisard** [comment]
@rmlarsen would you take a look? I don't see how the LinearAlgebra op would do this.

**Comment by rmlarsen** [comment]
This was intentional. The self_adjoint_eig and batch_self_adjoint_eig ops pack the eigenvalues and eigenvectors together in a single output, such that the first row contains the eigenvalues while remaining rows contain the eigenvectors. 

I recently updated these ops, such that they return the eigenvalues and vectors as separate outputs.

https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/ops/linalg_ops.py#L408

 I also added a wrappers (*self_adjoint_eigvals) that only returns the eigenvalues, which can be significantly faster. 

https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/ops/linalg_ops.py#L449

**Comment by arjunsesh** [comment]
@rmlarsen It seems like you misunderstood what I was pointing out - I understand that the dimensions of the _output_ are (N+1) x N for both batch_self_adjoint_eig and self_adjoint_eig since it is packing both the eigenvectors and values together. I was pointing out that the batch_self_adjoint_eig function currently modifying the shape of the _input_ tensor to become (N+1) x N for no reason at all. Take a look at the example above that I posted for more clarity, and thanks for your help.

**Comment by arjunsesh** [comment]
It seems that the issue lies in _BatchSelfAdjointEigShape(op) in linalg_ops.py. In line 95 (from https://github.com/tensorflow/tensorflow/blob/r0.10/tensorflow/python/ops/linalg_ops.py), dlist[-2] += 1
also increments input_shape.dims (see line 94), causing the input dimensions to change. A deepcopy fixes the problem, but is again a hack solution.
