### ISSUE TITLE
hlo_algorithm_blacklist.cc fails compilation

### ISSUE THREAD

**Issue by oracle3001** [tensorflow/tensorflow#35796]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution : Windows 10
- TensorFlow installed from (source or binary): Source
- TensorFlow version: 2.1
- Python version: 3.7
- Bazel version (if compiling from source): 0.29.1
- GCC/Compiler version (if compiling from source): VS2019
- CUDA/cuDNN version: 10.1 / 7.6
- GPU model and memory: 2070 Max Q

I setup it using configure with the following options selected : 
- XLA JIT
- Cuda
- /arch:AVX
- Eigen strong inline overridden

When attempting to build from source using the following command. 

bazel build --config=opt --config=cuda --define=no_tensorflow_py_deps=true //tensorflow:libtensorflow.so

I get the following error.

ERROR: C:/sdks/tensorflow/tensorflow/compiler/xla/service/gpu/BUILD:1616:1: C++ compilation of rule '//tensorflow/compiler/xla/service/gpu:hlo_algorithm_blacklist' failed (Exit 2)
cl : Command line warning D9002 : ignoring unknown option '-std=c++14'
tensorflow/compiler/xla/service/gpu/hlo_algorithm_blacklist.cc(28): error C2131: expression did not evaluate to a constant
external/com_google_absl\absl/strings/string_view.h(186): note: a non-constant (sub-)expression was encountered

**Comment by amahendrakar** [comment]
@oracle3001,
Is this still an issue? 

Please take a look at [this comment](https://github.com/tensorflow/tensorflow/issues/38951#issuecomment-620551293) from similar issue #38951 and check if it helps. Thanks!
