### ISSUE TITLE
Incompatible shapes when using tf.keras.backend.ctc_decode

### ISSUE THREAD

**Issue by faustomorales** [tensorflow/tensorflow#35799]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Debian Buster
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): v2.1.0-rc2-17-ge5bf8de 2.1.0
- Python version: 3.7
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

**Describe the current behavior**
When using a `tf.keras.backend.ctc_decode` with a batch size <  the size of the model input, a ValueError is raised related to failure to broadcast input shapes.

**Describe the expected behavior**
I expect shapes to be consistent and therefore no `ValueError` to be raised.

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

```python
import tensorflow as tf
import numpy as np

def CTCDecoder():
    def decoder(y_pred):
        input_shape = tf.keras.backend.shape(y_pred)
        input_length = tf.ones(shape=input_shape[0]) * tf.keras.backend.cast(input_shape[1], 'float32')
        return tf.keras.backend.ctc_decode(y_pred, input_length)[0][0]
    return tf.keras.layers.Lambda(decoder, name='decode')

input_layer = tf.keras.layers.Input((48, 37))
x = CTCDecoder()(input_layer)
model = tf.keras.models.Model(inputs=input_layer, outputs=x)

# This never raises a ValueError. The batch size is equal to the length
# of the input.
y = model.predict(np.random.uniform(size=(100, 48, 37)), batch_size=100)

# This usually raises a ValueError.
y = model.predict(np.random.uniform(size=(100, 48, 37)), batch_size=32)

# This always raises a ValueError.
y = model.predict(np.random.uniform(size=(100, 48, 37)), batch_size=1)
```

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

Here is the full traceback for an example exception.

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-145-9e000cf7055c> in <module>
----> 1 y = model.predict(np.random.uniform(size=(100, 48, 37)), batch_size=1)

/usr/src/.venv/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training.py in predict(self, x, batch_size, verbose, steps, callbacks, max_queue_size, workers, use_multiprocessing)
   1011         max_queue_size=max_queue_size,
   1012         workers=workers,
-> 1013         use_multiprocessing=use_multiprocessing)
   1014 
   1015   def reset_metrics(self):

/usr/src/.venv/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training_v2.py in predict(self, model, x, batch_size, verbose, steps, callbacks, max_queue_size, workers, use_multiprocessing, **kwargs)
    496         model, ModeKeys.PREDICT, x=x, batch_size=batch_size, verbose=verbose,
    497         steps=steps, callbacks=callbacks, max_queue_size=max_queue_size,
--> 498         workers=workers, use_multiprocessing=use_multiprocessing, **kwargs)
    499 
    500 

/usr/src/.venv/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training_v2.py in _model_iteration(self, model, mode, x, y, batch_size, verbose, sample_weight, steps, callbacks, max_queue_size, workers, use_multiprocessing, **kwargs)
    473               mode=mode,
    474               training_context=training_context,
--> 475               total_epochs=1)
    476           cbks.make_logs(model, epoch_logs, result, mode)
    477 

/usr/src/.venv/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training_v2.py in run_one_epoch(model, iterator, execution_function, dataset_size, batch_size, strategy, steps_per_epoch, num_samples, mode, training_context, total_epochs)
    177             batch_outs,
    178             batch_start=step * batch_size,
--> 179             batch_end=step * batch_size + current_batch_size)
    180       cbks.make_logs(model, batch_logs, batch_outs, mode)
    181       step += 1

/usr/src/.venv/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training_utils.py in aggregate(self, batch_outs, batch_start, batch_end)
    345     batch_outs = nest.flatten_up_to(self._structure, batch_outs)
    346     for batch_element, result in zip(batch_outs, self.results):
--> 347       result.aggregate(batch_element, batch_start, batch_end)
    348 
    349   def finalize(self):

/usr/src/.venv/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training_utils.py in aggregate(self, batch_element, batch_start, batch_end)
    278     num_elements = np.prod(batch_element.shape)
    279     if num_elements < self._BINARY_SIZE_THRESHOLD:
--> 280       self.results[batch_start:batch_end] = batch_element
    281     else:
    282       is_finished = threading.Event()

ValueError: could not broadcast input array from shape (1,46) into shape (1,48)
```

**Comment by faustomorales** [comment]
For anyone coming across this issue, I've found that I can work around it by padding the output before returning results.

```python
def CTCDecoder():
    def decoder(y_pred):
        input_shape = tf.keras.backend.shape(y_pred)
        input_length = tf.ones(shape=input_shape[0]) * tf.keras.backend.cast(input_shape[1], 'float32')
        unpadded = tf.keras.backend.ctc_decode(y_pred, input_length)[0][0]
        # I don't think I should have to do this ... but it seems as though I do?
        unpadded_shape = tf.keras.backend.shape(unpadded)
        padded = tf.pad(unpadded, paddings=[[0, 0], [0, input_shape[1] - unpadded_shape[1]]])
        return padded
    return tf.keras.layers.Lambda(decoder, name='decode')
```

**Comment by faustomorales** [comment]
Replacing the following line in `keras.backend` would resolve this:

**Comment by faustomorales** [comment]
It seems that editing the following line in `keras.backend` could resolve this.

https://github.com/tensorflow/tensorflow/blob/30b98cc73a8b046c8ce0915f6c0c7398a4947192/tensorflow/python/keras/backend.py#L5817-L5832

I would have thought that `st.dense_shape` should be something like `(input_shape[0], input_shape[1]` where `input_shape = tf.keras.backend.shape(y_pred)` (assuming you add this line before the transpose). But this causes the associated test to fail because it assumes that the output has not been padded with -1 values, which seems incorrect to me but I'm really not sure.

https://github.com/tensorflow/tensorflow/blob/03c045e146d441a0db4bd5cc1ecef1517e5c6708/tensorflow/python/keras/backend_test.py#L1782

I'm not sure exactly what the normal behavior is here. If the current behavior is correct, then I propose that this issue be closed without action as the workaround above suits my purposes just fine. Otherwise, I'm glad to file a PR with adjustments to the function and associated test.

**Comment by rchao** [comment]
@faustomorales, would you be open to send out a PR with your modification that fixes the problem? Thanks in advance.

**Comment by faustomorales** [comment]
Yes, certainly I can do that. Will try to get it out soon.
