### ISSUE TITLE
SWIG signature mismatch at RecordWriter

### ISSUE THREAD

**Issue by raingo** [tensorflow/tensorflow#358]
I tried to run the example "tensorflow/g3doc/how_tos/reading_data/convert_to_records.py", but there is an error saying function signature mismatch on the `bool WriteRecord(::tensorflow::StringPiece record);` call.

My swig version is `SWIG Version 1.3.40`

A simple fix is to change `bool WriteRecord(::tensorflow::StringPiece record);` to `bool WriteRecord(const string &record);` for these two files,
 ```
tensorflow/tensorflow/python/lib/io/py_record_writer.h
tensorflow/tensorflow/python/lib/io/py_record_writer.cc
```

**Comment by girving** [comment]
`StringPiece` is faster than `string` in some cases, so we don't want to change the signature in that way.  Can you add the full error message?  Also, what happens if you change `::tensorflow::StringPiece` to just `tensorflow::StringPiece` (i.e., remove the `::`)?

**Comment by raingo** [comment]
Removing the "::" solves the problem. Thanks!

As a reference, following is the TypeError with "::".

```
  File "tensorflow/python/pywrap_tensorflow.py", line 132, in WriteRecord
    def WriteRecord(self, *args): return _pywrap_tensorflow.PyRecordWriter_WriteRecord(self, *args)
TypeError: in method 'PyRecordWriter_WriteRecord', argument 2 of type '::tensorflow::StringPiece'
```

**Comment by girving** [comment]
Thanks, I'll fix this in the code.
