### ISSUE TITLE
Typo Error in `tflite_c02_transfer_learning.ipynb`

### ISSUE THREAD

**Issue by ManishAradwad** [tensorflow/tensorflow#35809]
## URL(s) with the issue:

https://github.com/tensorflow/examples/blob/master/courses/udacity_intro_to_tensorflow_lite/tflite_c02_transfer_learning.ipynb

## Description of issue (what needs changing):

![Screenshot from 2020-01-13 12-53-58](https://user-images.githubusercontent.com/29497701/72238480-d7b53400-3603-11ea-847d-0eb7c0eb0716.png)

In description, it should be 'cats_vs_dogs'

### Submit a pull request?

Yes

**Comment by saurabh-biradar** [comment]
Can I fix this issue

**Comment by MarkDaoust** [comment]
Yes. I'm not sure what's broken with that other PR, a clean resubmit would be easy to merge.

**Comment by ymodak** [comment]
Closing this issue since commit [9961988](https://github.com/tensorflow/examples/commit/996198828a5d758502f0cec9c5de58f04d200a0d) fixes the issue. Thanks!
