### ISSUE TITLE
Building the PoseNet example on iOS is failed

### ISSUE THREAD

**Issue by AnyCPU** [tensorflow/tensorflow#35803]
**System information**
- OS Platform and Distribution: macOS 10.15 and iPadOS 13.3
- Mobile device: iPad 2018
- TensorFlow installed from (source or binary): pod

**Describe the problem**

I did all the steps from the readme of https://github.com/tensorflow/examples/tree/master/lite/examples/posenet/ios 

but got next error:

> [!] CocoaPods could not find compatible versions for pod "TensorFlowLiteSwift":
>  In snapshot (Podfile.lock):
>    TensorFlowLiteSwift (= 0.0.1-nightly)

> In Podfile:
>    TensorFlowLiteSwift (= 0.0.1-nightly)

> None of your spec sources contain a spec satisfying the dependencies: `TensorFlowLiteSwift (= 0.0.1-nightly), TensorFlowLiteSwift (= 0.0.1-nightly)`.

>You have either:
> * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
> * mistyped the name or version.
> * not added the source repo that hosts the Podspec to your Podfile.

**The solution**

To make it work I just removed the Podfile.lock file and run again the command
`pod install`

Maybe the source repo should also be updated.

Thanks!

**Comment by oanush** [comment]
@AnyCPU ,
Hi, This is a TF.js issue . Kindly raise a new issue in TF.js repo using this [link](https://github.com/tensorflow/tfjs/issues/new).Thanks!
