### ISSUE TITLE
Update Pull Request Template

### ISSUE THREAD

**Issue by Kazaf123** [tensorflow/tensorflow#35808]
When I read the pull request, it is hard to read, so I think updating a Pull Request Template  that similar to the Issue Template will make pull requests more readable. Such as:
######Description

######Check List

######My PR Type is:

Thank you!!

**Comment by mihaimaruseac** [comment]
There is no template at the moment, but you can create a PR to add one under `https://github.com/tensorflow/tensorflow/tree/master/.github/ISSUE_TEMPLATE`

**Comment by mihaimaruseac** [comment]
I mean, provided that this is not a spam

![VCA6DzWKgeZ](https://user-images.githubusercontent.com/323199/72463514-43280e80-3788-11ea-99eb-a623ee2be107.png)

Closing issue, but please create PR if you did this in good spirits.
