### ISSUE TITLE
concat axis!=-1 and reshape change data layout don't support quant on dsp or NPU

### ISSUE THREAD

**Issue by sunzhe09** [tensorflow/tensorflow#35807]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):ubuntu18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):pip
- TensorFlow version (use command below):1.14.0
- Python version:
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
nnapi log said:concat axis!=-1 and reshape change data layout don't support accelator
**Describe the expected behavior**
it should run successful on dsp or hta
**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.
./benmakrk --graph=myquantized.tflite --use_nnapi=true
**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.
New Comment: "01-08 20:47:35.790 14384 14384 I TypeManager: Failed to read /vendor/etc/nnapi_extensions_app_allowlist ; No app allowlisted for vendor extensions use.
01-08 20:47:35.799 919 1023 E OperationsUtils: NN_CHECK failed: inputShapes[0].scale == inputShapes[i].scale'
01-08 20:47:35.799 919 1023 E OperationsUtils:
01-08 20:47:35.799 919 1023 E OperationsUtils: NN_CHECK failed: inputShapes[0].offset == inputShapes[i].offset'
01-08 20:47:35.799 919 1023 E OperationsUtils:
01-08 20:47:35.801 919 1023 E hta-unnhal: RESHAPE doesn't support changing data layout
01-08 20:47:35.801 919 1023 E hta-unnhal: {RESHAPE, TENSOR_QUANT8} is not supported.
01-08 20:47:35.801 919 1023 E hta-unnhal: RESHAPE doesn't support changing data layout
01-08 20:47:35.801 919 1023 E hta-unnhal: {RESHAPE, TENSOR_QUANT8} is not supported.
01-08 20:47:35.801 919 1023 E hta-unnhal: RESHAPE doesn't support changing data layout
01-08 20:47:35.801 919 1023 E hta-unnhal: {RESHAPE, TENSOR_QUANT8} is not supported.
01-08 20:47:35.801 919 1023 E hta-unnhal: Only supports channel dimension for CONCATENATION
01-08 20:47:35.801 919 1023 E hta-unnhal: {CONCATENATION, TENSOR_QUANT8} is not supported.
01-08 20:47:35.801 919 1023 E hta-unnhal: RESHAPE doesn't support changing data layout
01-08 20:47:35.801 919 1023 E hta-unnhal: {RESHAPE, TENSOR_QUANT8} is not supported.
01-08 20:47:35.801 919 1023 E hta-unnhal: Only supports channel dimension for CONCATENATION
01-08 20:47:35.801 919 1023 E hta-unnhal: {CONCATENATION, TENSOR_QUANT8} is not supported.
01-08 20:47:35.805 919 1023 E OperationsUtils: NN_CHECK failed: inputShapes[0].scale == inputShapes[i].scale'
01-08 20:47:35.805 919 1023 E OperationsUtils:
01-08 20:47:35.806 919 1023 E OperationsUtils: NN_CHECK failed: inputShapes[0].offset == inputShapes[i].offset'
01-08 20:47:35.806 919 1023 E OperationsUtils:
01-08 20:47:35.810 919 1023 W android.hardware.neuralnetworks@1.2-service: pickAcceleratorByName cannot find the accelerator:adreno
01-08 20:47:35.810 919 1023 W android.hardware.neuralnetworks@1.2-service:
01-08 20:47:35.810 919 1023 W android.hardware.neuralnetworks@1.2-service: getSupportedOperations() cannot pick an accelerator
01-08 20:47:35.810 919 1023 W android.hardware.neuralnetworks@1.2-service:
01-08 20:47:35.814 919 919 E hta-unnhal: RESHAPE doesn't support changing data layout
01-08 20:47:35.814 919 919 E hta-unnhal: {RESHAPE, TENSOR_QUANT8} is not supported.
01-08 20:47:35.814 919 919 E hta-unnhal: RESHAPE doesn't support changing data layout
01-08 20:47:35.814 919 919 E hta-unnhal: {RESHAPE, TENSOR_QUANT8} is not supported.
01-08 20:47:35.814 919 919 E hta-unnhal: RESHAPE doesn't support changing data layout
01-08 20:47:35.814 919 919 E hta-unnhal: {RESHAPE, TENSOR_QUANT8} is not supported.
01-08 20:47:35.814 919 919 E hta-unnhal: Only supports channel dimension for CONCATENATION
01-08 20:47:35.814 919 919 E hta-unnhal: {CONCATENATION, TENSOR_QUANT8} is not supported.
01-08 20:47:35.814 919 919 E hta-unnhal: RESHAPE doesn't support changing data layout
01-08 20:47:35.814 919 919 E hta-unnhal: {RESHAPE, TENSOR_QUANT8} is not supported.
01-08 20:47:35.814 919 919 E hta-unnhal: Only supports channel dimension for CONCATENATION
01-08 20:47:35.814 919 919 E hta-unnhal: {CONCATENATION, TENSOR_QUANT8} is not supported."

**Comment by jdduke** [comment]
@miaowang14 what is the expected behavior here?

**Comment by sunzhe09** [comment]
@jdduke my model is from object detection api,

**Comment by miaowang14** [comment]
This is the limitation of current driver. The driver may not be able to support all the operations in the model. And from the logcat, the HTA driver requires the quantization parameters of the input tensors to be the same, and the concatenation axis being the channel dimension.

If this is an important usecase, please let us know and we can communicate back to our partners.

**Comment by sunzhe09** [comment]
> This is the limitation of current driver. The driver may not be able to support all the operations in the model. And from the logcat, the HTA driver requires the quantization parameters of the input tensors to be the same, and the concatenation axis being the channel dimension.
> 
> If this is an important usecase, please let us know and we can communicate back to our partners.

yes,our team wants a low power detection model,the last rehsape and concat ops can't run on hta or dsp,and fall back to cpu.we want a better performance

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.
