### ISSUE TITLE
Win10: ImportError: DLL load failed: The specified module could not be found

### ISSUE THREAD

**Issue by eduardoavila1m** [tensorflow/tensorflow#35805]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10 home
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: PC
- TensorFlow installed from (source or binary): 1.13.0
- TensorFlow version:
- Python version: 3.6
- Installed using virtualenv? pip? conda?: conda
- Bazel version (if compiling from source): 0.21.0
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 10.0 7.4.2.24
- GPU model and memory: RTX 2080 Ti
- CPU model and make: AMD Ryzen 7 3800X 8-Core Processor 3.89GHz
- Anaconda Python Command Prompt

**Describe the problem**

Trying to build TF 1.13 from source. Issue at the creation of wheel file with bazel. Attached exact sequence of commands issued. Trying to conver a *.pb file into a TFLite file that was trained in tensorflow 1.13

**Exact sequence of commands / steps executed before running into the problem**

conda update -n base -c defaults conda
conda update --all
conda create -n tensorflow-build pip python=3.6
conda activate tensorflow-build
python -m pip install --upgrade pip
conda install -c anaconda git
set PATH=%PATH%;C:\msys64\usr\bin
pip install six numpy wheel
pip install keras_applications==1.0.6 --no-deps
pip install keras_preprocessing==1.0.5 --no-deps
conda install -c conda-forge bazel=0.21.0
mkdir C:\tensorflow-build
cd C:\tensorflow-build
git clone https://github.com/tensorflow/tensorflow.git 
cd tensorflow
git checkout r1.13
python ./configure.py

You have bazel 0.21.0- (@non-git) installed. 

Please specify the location of python. [Default is C:\ProgramData\Anaconda3\envs\tensorflow-build\python.exe]: 
  
Found possible Python library paths: 

  C:\ProgramData\Anaconda3\envs\tensorflow-build\lib\site-packages 

Please input the desired Python library path to use.  Default is [C:\ProgramData\Anaconda3\envs\tensorflow-build\lib\site-packages] 

Do you wish to build TensorFlow with XLA JIT support? [y/N]: n 
No XLA JIT support will be enabled for TensorFlow. 

Do you wish to build TensorFlow with ROCm support? [y/N]: n 
No ROCm support will be enabled for TensorFlow. 
  
Do you wish to build TensorFlow with CUDA support? [y/N]: y 

Please specify the CUDA SDK version you want to use. [Leave empty to default to CUDA 10.0]: 10.0

Please specify the location where CUDA 10.0 toolkit is installed. Refer to README.md for more details. [Default is C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.0]:

Please specify the cuDNN version you want to use. [Leave empty to default to cuDNN 7]: 7.4

Please specify the location where cuDNN 7 library is installed. Refer to README.md for more details. [Default is C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.0]:

Please specify a list of comma-separated Cuda compute capabilities you want to build with.
You can find the compute capability of your device at: https://developer.nvidia.com/cuda-gpus.
Please note that each additional compute capability significantly increases your build time and binary size. [Default is: 3.5,7.0]: 7.5

Please specify optimization flags to use during compilation when bazel option "--config=opt" is specified [Default is /arch:AVX]:

Would you like to override eigen strong inline for some C++ compilation to reduce the compilation time? [Y/n]: y
Eigen strong inline overridden.

bazel build --config=opt --config=cuda --define=no_tensorflow_py_deps=true //tensorflow/tools/pip_package:build_pip_package

**info / logs**

////////////////////////////////////////////////////////LOG/////////////////////////////////////////////////////

ERROR: C:/tensorflow-build/tensorflow/tensorflow/BUILD:579:1: Executing genrule //tensorflow:tf_python_api_gen_v1 failed (Exit 1): bash.exe failed: error executing command
  cd C:/users/eduar/_bazel_eduar/j7bi4x5j/execroot/org_tensorflow
  SET CUDA_TOOLKIT_PATH=C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.0
    SET CUDNN_INSTALL_PATH=C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.0
    SET PATH=C:\msys64\usr\bin;C:\msys64\bin
    SET PYTHON_BIN_PATH=C:/Users/eduar/.conda/envs/tensorflow-build/python.exe
    SET PYTHON_LIB_PATH=C:/Users/eduar/.conda/envs/tensorflow-build/lib/site-packages
    SET TF_CUDA_CLANG=0
    SET TF_CUDA_COMPUTE_CAPABILITIES=7.5
    SET TF_CUDA_VERSION=10.0
    SET TF_CUDNN_VERSION=7
    SET TF_NEED_CUDA=1
    SET TF_NEED_OPENCL_SYCL=0
    SET TF_NEED_ROCM=0
  C:/msys64/usr/bin/bash.exe bazel-out/x64_windows-opt/genfiles/tensorflow/tf_python_api_gen_v1.genrule_script.sh
Execution platform: @bazel_tools//platforms:host_platform
Traceback (most recent call last):
  File "\\?\C:\Users\eduar\AppData\Local\Temp\Bazel.runfiles_fxnhn1zo\runfiles\org_tensorflow\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "\\?\C:\Users\eduar\AppData\Local\Temp\Bazel.runfiles_fxnhn1zo\runfiles\org_tensorflow\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "\\?\C:\Users\eduar\AppData\Local\Temp\Bazel.runfiles_fxnhn1zo\runfiles\org_tensorflow\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Users\eduar\.conda\envs\tensorflow-build\lib\imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\eduar\.conda\envs\tensorflow-build\lib\imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "\\?\C:\Users\eduar\AppData\Local\Temp\Bazel.runfiles_fxnhn1zo\runfiles\org_tensorflow\tensorflow\python\tools\api\generator\create_python_api.py", line 27, in <module>
    from tensorflow.python.tools.api.generator import doc_srcs
  File "\\?\C:\Users\eduar\AppData\Local\Temp\Bazel.runfiles_fxnhn1zo\runfiles\org_tensorflow\tensorflow\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "\\?\C:\Users\eduar\AppData\Local\Temp\Bazel.runfiles_fxnhn1zo\runfiles\org_tensorflow\tensorflow\python\pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "\\?\C:\Users\eduar\AppData\Local\Temp\Bazel.runfiles_fxnhn1zo\runfiles\org_tensorflow\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "\\?\C:\Users\eduar\AppData\Local\Temp\Bazel.runfiles_fxnhn1zo\runfiles\org_tensorflow\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "\\?\C:\Users\eduar\AppData\Local\Temp\Bazel.runfiles_fxnhn1zo\runfiles\org_tensorflow\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Users\eduar\.conda\envs\tensorflow-build\lib\imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\eduar\.conda\envs\tensorflow-build\lib\imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: The specified module could not be found.

Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.
Target //tensorflow/tools/pip_package:build_pip_package failed to build
INFO: Elapsed time: 1319.085s, Critical Path: 291.62s
INFO: 4651 processes: 4651 local.
FAILED: Build did NOT complete successfully

///////////////////////////////////////////////////////////////////////////////////////////////////////////////////
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by fonnesbeck** [comment]
I also get this failure on Windows 10 in a clean Conda env, installing TF 2.1 via pip.

**Comment by ravikyram** [comment]
@eduardoavila1m 
What is make/model of your cpu?
I suspect your cpu model does not support AVX instructions sets.See [hardware requirements](https://www.tensorflow.org/install/pip?lang=python3#hardware-requirements). Also go through #28848 and see if it helps you.Thanks!

**Comment by eduardoavila1m** [comment]
Hello My CPU model is a AMD Ryzen 7 3800X 8-Core Processor 3.89GHz

**Comment by eduardoavila1m** [comment]
I've reinstalled Anaconda and repeated the process. The error is persistant.

**Comment by ymodak** [comment]
Did you install Microsoft Visual Studio 2015?
See https://www.tensorflow.org/install/pip#1.-install-the-python-development-environment-on-your-system select `Windows`

**Comment by eduardoavila1m** [comment]
Yes, I've installed Visual Studio and it does not work.

**Comment by cracy3m** [comment]
I try to build r1.13 in win10 , and get the same issue.

ERROR: C:/tensorflow-build/tensorflow/tensorflow/BUILD:579:1: Executing genrule //tensorflow:tf_python_api_gen_v1 failed (Exit 1): bash.exe failed: error executing command
cd C:/users/eduar/_bazel_eduar/j7bi4x5j/execroot/org_tensorflow
SET CUDA_TOOLKIT_PATH=C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.0
SET CUDNN_INSTALL_PATH=C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.0
SET PATH=C:\msys64\usr\bin;C:\msys64\bin <<= I think the problem is here
..................
I create a softlink in C:\msys64, like this:
    cd /d C:\msys64
    mklink /D bin "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0\bin"

than the compile success

**Comment by eduardoavila1m** [comment]
The Issue was solving by re-installing the CUDA versions and assuring that the tensorflow version was compatible with the CUDA and CuDNN versions found in the table https://www.tensorflow.org/install/source. Assure the system paths have been set correctly and install the tensorflow vesrion on a clean anaconda environment utilizing pip instal tensorflow-gpu==1.13.1. After some iterations this worked. I had to uninstall and re install CUDA multiple times.
