### ISSUE TITLE
save_model_builder saved, then estimator load fail!

### ISSUE THREAD

**Issue by yongzhuo** [tensorflow/tensorflow#35806]
This template is for miscellaneous issues not covered by the other issue categories.

For questions on how to work with TensorFlow, or support for problems that are not verified bugs in TensorFlow, please go to [StackOverflow](https://stackoverflow.com/questions/tagged/tensorflow).

If you are reporting a vulnerability, please use the [dedicated reporting process](https://github.com/tensorflow/tensorflow/blob/master/SECURITY.md).

For high-level discussions about TensorFlow, please post to discuss@tensorflow.org, for questions about the development or internal workings of TensorFlow, or if you would like to know how to contribute to TensorFlow, please post to developers@tensorflow.org.

tensorflow: 1.12.0
environment: win10
code:
```python3
import tensorflow as tf
saved_model_dir = "./model_tst"

def builder_and_save_model(saved_model_dir):
    with tf.Session(graph=tf.Graph()) as sess:
        x = tf.placeholder(tf.int32, name='input_x')
        y = tf.placeholder(tf.int32, name='input_y')
        b = tf.Variable(1, name='b')
        xy = tf.multiply(x, y)
        # 这里的输出需要加上name属性
        op = tf.add(xy, b, name='output')

        sess.run(tf.global_variables_initializer())

        builder = tf.saved_model.builder.SavedModelBuilder(saved_model_dir)
        # x 为输入tensor, keep_prob为dropout的prob tensor
        inputs = {'input_x': tf.saved_model.utils.build_tensor_info(x),
                  'input_y': tf.saved_model.utils.build_tensor_info(y)}

        # y 为最终需要的输出结果tensor
        outputs = {'output': tf.saved_model.utils.build_tensor_info(op)}

        signature = tf.saved_model.signature_def_utils.build_signature_def(inputs=inputs,
                                                                           outputs=outputs,
                                                                           method_name='variables')
        builder.add_meta_graph_and_variables(sess=sess,
                                             tags=[tf.saved_model.tag_constants.SERVING],
                                             signature_def_map={'variables': signature},
                                             assets_collection=None,)
        builder.save()

builder_and_save_model(saved_model_dir)
predict_fn = tf.contrib.predictor.from_saved_model(saved_model_dir)
prediction = predict_fn( {"input_x": 5, "input_y": 6})
print(prediction["output"])
```

error:
```python3
ValueError: Got unexpected keys in input_dict: {'input_y', 'input_x'}
expected: set()
```

**Comment by rmothukuru** [comment]
@yongzhuo,
Is there any specific reason that you are using `Tensorflow Version 1.12`.  You can upgrade your Tensorflow Version and can use 

`tf.saved_model.loader.load(sess, ["tag"], saved_model_dir)` instead of 

`predict_fn = tf.contrib.predictor.from_saved_model(saved_model_dir)` (it should work even for `1.12`)

Fore more information, please refer [this Documentation](https://github.com/tensorflow/docs/blob/master/site/en/r1/guide/saved_model.md#loading-a-savedmodel-in-python) for Loading a Saved Model.

**Comment by yongzhuo** [comment]
ok, thanks!

**Comment by wenbotse** [comment]
> ok, thanks!

how did you solve this problem ? still use predictor ?
