### ISSUE TITLE
Tensorboard 2.1 broken on Windows 10 (won't display anything on webpage)

### ISSUE THREAD

**Issue by johnpjust** [tensorflow/tensorflow#35804]
I've ran the same code both before and after upgrading from 2.0 to 2.1 on two different machines.  What worked in 2.0 now in 2.1 serves up a blank web page instead of the usual graphs and stuff (page is completely blanked out).  Again, it seems to "run" as it would usually (no errors or anything, gives the typical localhost link, etc in the terminal -- just totally blank page served up).  

I've upgraded many times and this is the first TB issue I've every run across.  Any ideas?

In case you want example code to test out....

```
import tensorflow as tf

mnist = tf.keras.datasets.mnist

(x_train, y_train),(x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

def create_model():
  return tf.keras.models.Sequential([
    tf.keras.layers.Flatten(input_shape=(28, 28)),
    tf.keras.layers.Dense(512, activation='relu'),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(10, activation='softmax')
  ])

model = create_model()
model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

log_dir=r"C:\Users\justjo\PycharmProjects\tensorboardTest\logs\fit"
tensorboard_callback = tf.keras.callbacks.TensorBoard(log_dir=log_dir, histogram_freq=1, profile_batch = 100000000)

model.fit(x=x_train,
          y=y_train,
          epochs=5,
          validation_data=(x_test, y_test),
          callbacks=[tensorboard_callback])
```

Then use 
tensorboard --logdir=C:\Users\justjo\PycharmProjects\tensorboardTest\logs\fit

**Comment by ravikyram** [comment]
@johnpjust 
As the issue is more related to tensorboard can we track the issue in #3117 and close here.Thanks!
