### ISSUE TITLE
[Feature Request] MultiHeadAttention ops and Layer

### ISSUE THREAD

**Issue by cgarciae** [tensorflow/tensorflow#35801]
Multi Head Self Attention is reaching SOTA results in a wide variety of fields:
* NLP (Attention is all you need, GPT, Bert, etc)
* [Graphs](https://arxiv.org/abs/1710.10903)
* Computer Vision: [1](https://arxiv.org/abs/1906.05909) and [2](https://arxiv.org/abs/1911.03584)
* [Time Series](https://arxiv.org/pdf/1909.07369.pdf)
* [Audio/Speech Recognition](https://arxiv.org/pdf/1910.12977.pdf)

Nvidia already added this operation to [cudnn](https://docs.nvidia.com/deeplearning/sdk/cudnn-release-notes/rel_750.html) and pytorch already has an official [MultiHeadAttention](https://pytorch.org/docs/master/nn.html#multiheadattention) module. Its about time Tensorflow gets this operation too as it would enable researches and developers to get started quicker.

Currently there is an `Attention` layer in tf.keras but it only covers the main single head equation, has no learnable parameters, and can't be used as a basis for an efficient `MultiHeadAttention` implementation.

**Comment by monk1337** [comment]
@Cibifang, I would like to contribute.

**Comment by 2sin18** [comment]
@monk1337 @fchollet Any updates?

**Comment by cgarciae** [comment]
This layer is already implemented: 

https://www.tensorflow.org/addons/api_docs/python/tfa/layers/MultiHeadAttention

**Comment by 2sin18** [comment]
> This layer is already implemented:
> 
> https://www.tensorflow.org/addons/api_docs/python/tfa/layers/MultiHeadAttention

This layer do not use `cudnnMultiHeadAttnForward`.

https://github.com/tensorflow/addons/commit/3b0d97804c15e65fdf9e8e3bbc2e93de0091e5bc

**Comment by saberkun** [comment]
cudnnMultiHeadAttnForward has not been defined as TF ops/kernel yet? @reedwm @zongweiz 
We have tracked this.

**Comment by rmothukuru** [comment]
@cgarciae,
Can you please let us know if [MultiHeadAttention Layer](https://www.tensorflow.org/api_docs/python/tf/keras/layers/MultiHeadAttention) is the functionality that you are looking for? Thanks!
