### ISSUE TITLE
Threading + tf.keras.layers.Input produces TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by dswah** [tensorflow/tensorflow#35813]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- No custom code
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04.3 LTS
- TensorFlow installed from (source or binary): from pip
- TensorFlow version (use command below): v2.1.0-rc2-17-ge5bf8de 2.1.0
- Python version: Python 3.7.6 | packaged by conda-forge | (default, Jan  7 2020, 22:33:48) 
[GCC 7.3.0] on linux

- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

**Describe the current behavior**
When I build a `tf.keras` model with the functional API in a `threading.Thread`, I often (not always) see an error in a thread:
```python
TypeError: 'NoneType' object is not iterable
```
After the exception has appeared once, it does not appear again, until the python kernel is restarted.

In fact, it is not even necessary to build a whole model. Just instantiating a `tf.keras.layers.Input` layer is sufficient to get the error. I tested a few other layers (Dense, Conv1D) and they do not lead to the error, so am suspecting that there is something happening with Input)

**Describe the expected behavior**
I expect that no such error should appear in any thread when building a `tf.keras` model.

**Code to reproduce the issue**
```python
from threading import Thread
import tensorflow as tf

def make_model():
    tf.keras.layers.Input(10)
    
[Thread(target=make_model).start() for _ in range(10)]
```

**Other info / logs**
The error does not appear if i instantiate a `tf.keras.models.Model` subclass.
for example:

```python
from threading import Thread
import tensorflow as tf

class Model(tf.keras.models.Model):
    def __init__(self):
        super().__init__()
        self.dense = tf.keras.layers.Dense(10)
    
    def call(self, inputs):
        return self.dense(inputs)
    
def make_model():
    Model()
    
[Thread(target=make_model).start() for _ in range(10)]
```

Full traceback:
```python
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/home/dani/miniconda3/envs/testtf/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/home/dani/miniconda3/envs/testtf/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "<ipython-input-1-3fe088eac4c0>", line 5, in make_model
    tf.keras.layers.Input(10)
  File "/home/dani/miniconda3/envs/testtf/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/input_layer.py", line 274, in Input
    input_layer = InputLayer(**input_layer_config)
  File "/home/dani/miniconda3/envs/testtf/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/input_layer.py", line 127, in __init__
    ragged=ragged)
  File "/home/dani/miniconda3/envs/testtf/lib/python3.7/site-packages/tensorflow_core/python/keras/backend.py", line 1054, in placeholder
    x = array_ops.placeholder(dtype, shape=shape, name=name)
  File "/home/dani/miniconda3/envs/testtf/lib/python3.7/site-packages/tensorflow_core/python/ops/array_ops.py", line 2990, in placeholder
    return gen_array_ops.placeholder(dtype=dtype, shape=shape, name=name)
  File "/home/dani/miniconda3/envs/testtf/lib/python3.7/site-packages/tensorflow_core/python/ops/gen_array_ops.py", line 6676, in placeholder
    "Placeholder", dtype=dtype, shape=shape, name=name)
  File "/home/dani/miniconda3/envs/testtf/lib/python3.7/site-packages/tensorflow_core/python/framework/op_def_library.py", line 759, in _apply_op_helper
    return output_structure, op_def.is_stateful, op, outputs
  File "/home/dani/miniconda3/envs/testtf/lib/python3.7/contextlib.py", line 119, in __exit__
    next(self.gen)
  File "/home/dani/miniconda3/envs/testtf/lib/python3.7/site-packages/tensorflow_core/python/framework/func_graph.py", line 418, in inner_cm
    for fn in self._scope_exit_callbacks:
TypeError: 'NoneType' object is not iterable
```
Notes: the error does not appear in tf 2.0.

**Comment by oanush** [comment]
Issue replicating for tf-2.1 and [tf-nightly](https://colab.sandbox.google.com/gist/oanush/04f732545f614090df84351da1e693a5/35813.ipynb).Thanks!

**Comment by dswah** [comment]
@jvishnuvardhan any news on this issue? any idea where we can start to look?
i'd be happy to help if i can.

**Comment by jvishnuvardhan** [comment]
@dswah When I add a return statement (`return tf.keras.layers.Input(10)`) to the `make_model` function, output from both the codes is same. Please check the [gist here](https://colab.sandbox.google.com/gist/jvishnuvardhan/82ca4e02d6378ab4b1b40597329a81dd/untitled771.ipynb). Thanks!

**Comment by dswah** [comment]
@jvishnuvardhan No, that does not work.
![image](https://user-images.githubusercontent.com/11619412/72851446-f2df0e00-3cab-11ea-9d35-8274b6a7fe8b.png)
Sometimes the error does not show up, so you may hay gotten lucky. 
I just **restarted** the notebook and got the error using your sample.

**Comment by dswah** [comment]
@omalleyt12 hey there. Have you had a chance to take a look?
Any idea where I could help out?

thanks!

**Comment by rkbairi** [comment]
I too faced this error while running on multiple threads. As a work around, I tried locking the model creation part (the _build_ function in my code below), and the error did seem to disappear. I don't know if it will manifest in some other form somewhere else.

I wrote this code to check if multithreading works in TF 2.0 before migrating my production TF 1.0 code (which is multithreaded) to TF 2.0. Hence this code is kinda "hello world" program. Brief note on the code:

- I am trying to solve the regression y = a*x + b. Input is a set of (x,y) pairs satisfying this equation for some _a_ and _b_. The model has to estimate _a_ and _b_.
- Each thread solves different regression - i.e, _a_, _b_ are different for each thread.
- At the end to training I write the model weights (which correspond to _a_ and _b_) to a file so that I could inspect if multiple threads crossed each other and screwed up training. Luckily, this did not happen, and each thread estimated _a_ and _b_ close enough. (_a_ was correct to the 4th decimal, but _b_ was off by +/- 2 in some cases, which I have to investigate further). 
- So, it seems to me that training simultaneously on multiple threads is working, but not the simultaneous model building (hence I had to lock model building part)


```
import tensorflow as tf
from tensorflow import keras as tfkeras
import numpy as np
import threading
import multiprocessing
import itertools
import concurrent.futures
import sys
import traceback

lock = threading.Lock()

class MyNN:
    def __init__(self, a, b):
        self.a = a
        self.b = b

    def build(self):
        lock.acquire()
        inp = tfkeras.layers.Input(shape=(1,))
        oup = tfkeras.layers.Dense(1, activation=None)(inp)
        self.model = tfkeras.Model(inputs=inp, outputs=oup)
        opt = tfkeras.optimizers.Adam(learning_rate=0.1)
        self.model.compile(loss='mean_squared_error',
                      optimizer=opt,
                      metrics=['mse', 'mae', 'mape'])
        lock.release()

    def train(self):
        a = self.a
        b = self.b
        X_train = np.array([[x] for x in range(100000)])
        y_train = np.array([[a*x[0]+b] for x in X_train])
        X_test = np.array([[x+100000] for x in range(100)])
        y_test = np.array([[a*x[0]+b] for x in X_test])     

        history = self.model.fit(x=X_train, y=y_train, batch_size=10000, validation_data=(X_test, y_test), epochs=300, verbose=0)

        with open(f"c:/temp/res_{self.a}_{self.b}.txt", "w") as f:
            f.write(f"a={self.a},b={self.b}")
            f.write("\n")
            print(self.model.summary(), file=f)
            f.write("\n")
            print(self.model.get_weights(), file=f)
            f.write("\n")
            print(self.model.predict(X_test[0:10,:]), file=f)

def create_nn(config):
    try:
        print(f"Running confing: {config}")
        nn = MyNN(config[0], config[1])
        nn.build()
        nn.train()
    except:
        e = sys.exc_info()[0]
        print(e)
        traceback.print_tb(sys.exc_info()[2])
    print("Job Complete.")

with concurrent.futures.ThreadPoolExecutor(max_workers=8) as executor:
    configs = [[5,6],[3,4],[6,9],[2,3],[4,5],[7,8],[8,6],[9,4],[1,2]]
    for config in configs:
        executor.submit(create_nn, config)
        print(f"Submitted config {config}")

input("Press Enter to exit after all jobs are complete.")

```

I am not saying it will solve your problem, nor am I clear if I will stumble upon any other problems when I migrate my production TF 1.0 code to TF 2.0. I thought of sharing my observations so far.

As you mentioned, definitely there seems to be some issue with multithreading in TF 2.0. Hope it will get fixed soon.

Thanks!

**Comment by nihir27** [comment]
This also affects TF 2.2

@omalleyt12 @jvishnuvardhan Any update on this?

**Comment by fhennecker** [comment]
Also had the issue on tf 2.2 when building several models in multiple threads from a topology using `tf.keras.model.model_from_json()`.

I can confirm that @rkbairi 's solution of putting it in a locked section alleviates the issue:

```python
import threading
lock = threading.Lock()

lock.acquire()
model = tf.keras.model.model_from_json(...)
lock.release()
```

**Comment by goldiegadde** [comment]
Its possible this is now working with the latest nightly, but we dont make any guarantees using multi-threading with Keras at this time, but if you let us know why you use multi-threading we can re-evaluate.

**Comment by rmothukuru** [comment]
@dswah,
Can you please respond to the above comment? Thanks!
