### ISSUE TITLE
[Feature Request] Deformable Convolution v1 for tf-1.1.0 slim

### ISSUE THREAD

**Issue by curry8** [tensorflow/tensorflow#35811]
**System information**
- TensorFlow version (you are using): 1.1.0
TensorFlow installed from conda command
- Are you willing to contribute it (Yes/No): yes,if I have the ability

**Describe the feature and the current behavior/state.**
Deformable Convolutional [https://arxiv.org/pdf/1703.06211.pdf,https://arxiv.org/pdf/1703.06211.pdf](url), I used an old project with TF1.1.0 slim. Now I want to add Deformable Convolutional layer to train my network.
But, I can't find a way to achieve it.

**Will this change the current api? How?**
yes,add a slim layer
**Who will benefit with this feature?**
anyone who want to use deformable conv by tf slim

**Comment by ymodak** [comment]
Apologies for the delay in response. duplicate #24387
This is a work in progress in tf addons repository. 
See https://github.com/tensorflow/addons/issues/179
Closing this thread since we are already tracking it in above threads. Thanks!
