### ISSUE TITLE
Failed to load the native TensorFlow runtime. even though I have specified all paths and everything

### ISSUE THREAD

**Issue by rajcivils** [tensorflow/tensorflow#35814]
**System information**
- OS: Windows 10
- TensorFlow version: 2.1
- Python version: 3.7.0
- Installed using pip
- CUDA version: 10.1
- cuDNN version: v7.6.5.32
- GPU model and memory: GTX 1080 Ti

**Describe the problem**
Hello I tried installing tensorflow using the following command - 
```
pip --no-cache-dir install tensorflow
```
I am using no cache dir as I tried installing tensorflow many times and all of them failed. So i reinstalled python 4 times and then finally I used this command. It installed tensorflow.
But now  when I do - 
```
>>> import tensorflow
```
It gives me the following error - 

https://pastebin.com/T9niAwFt

So now I have installed everything and even added python to path and also the cuda and cudnn. But please note last time I installed python I didn't add it to path so I added it so it made 2 paths when I reinstalled python and they got duplicated and then I deleted the duplicated ones. And now here are my path variables - 
![image](https://user-images.githubusercontent.com/30827615/72258042-12829080-3633-11ea-8f3f-057141dbbceb.png)
And by the way I am using vs code 2017 and I have everything installed and also by the way I am not using any venv as I want to acess tensorflow without having to activate any environment and writing lines to activate every time I wanna acess tensorflow.

**Comment by adityaa30** [comment]
I guess your problem is because of CUDA 10.2 which is not yet supported for v2.1.0
Refer the [GPU Guide](https://www.tensorflow.org/install/gpu), it is mentioned that "TensorFlow supports CUDA 10.1 (TensorFlow >= 2.1.0)".

**Comment by rajcivils** [comment]
@adityaa30 New update I did 10.1 now and it still doesent work

**Comment by ravikyram** [comment]
@rajcivils 

Just to verify did you follow the instructions for installing GPU for [windows ](https://www.tensorflow.org/install/gpu#windows_setup).
What is make/model of your cpu?. Does your cpu supports AVX instructions sets.Thanks!

**Comment by ravikyram** [comment]
@rajcivils 

Any update on this issue please. Thanks!

**Comment by ravikyram** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
