### ISSUE TITLE
Same op sequence is computed multiple times

### ISSUE THREAD

**Issue by veqtor** [tensorflow/tensorflow#35820]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Colab
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): Not applicable
- TensorFlow version (use command below): 2.1.0
- Python version: Not applicable
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: Not applicable
- GPU model and memory: Not applicable

**Describe the current behavior**
When applying a layer multiple times to the same input, it seems TF is computing it for every call, even if it's unnecessary, see colab:
https://colab.research.google.com/drive/1PTvolVt1xQJvgp4MP0ZvgbemKBrqWy0U

**Describe the expected behavior**
The duplicate parts of the graph should be squashed

**Code to reproduce the issue**
https://colab.research.google.com/drive/1PTvolVt1xQJvgp4MP0ZvgbemKBrqWy0U

**Comment by veqtor** [comment]
Jit vs no-jit seems to make very little difference:
https://colab.research.google.com/drive/1RtCXNSCgCLap1e4mlAbd-3hyD4zvufBZ

**Comment by sachinprasadhs** [comment]
I was able to reproduce your issue in Tf-Nightly , please find the gist [here](https://colab.research.google.com/gist/sachinprasadhs/ce4def258ad61c0ff30ebbc31930e82e/35650.ipynb).

**Comment by kumariko** [comment]
I was able to reproduce your issue in Tf 2.6 , please find the gist [**`here`**](https://colab.research.google.com/gist/kumariko/e31dd1d5169bcf5ddd38a81e69e03876/35650.ipynb#scrollTo=c3LN0qQa_b4E).

**Comment by tensorflowbutler** [comment]
Hi There,

 This is a stale issue. As you are using an older version of tensorflow, we are checking to see if you still need help on this issue. Please test the issue with the latest TensorFlow (TF2.7 and tf-nightly). If the issue still persists with the newer versions of TF, please feel free to open it in [keras-team/keras](https://github.com/keras-team/keras/issues) repository by providing details about the issue and a standalone code to reproduce the issue. Thanks! 

 Please note that Keras development has moved to a separate Keras-team/keras repository to focus entirely on only Keras. Thanks!
