### ISSUE TITLE
Building the PoseNet example on iOS is failed

### ISSUE THREAD

**Issue by AnyCPU** [tensorflow/tensorflow#35831]
**System information**
- OS Platform and Distribution: macOS 10.15 and iPadOS 13.3
- Mobile device: iPad 2018
- TensorFlow installed from (source or binary): pod

**Describe the problem**

I did all the steps from the readme of https://github.com/tensorflow/examples/tree/master/lite/examples/posenet/ios 

but got next error:

> [!] CocoaPods could not find compatible versions for pod "TensorFlowLiteSwift":
>  In snapshot (Podfile.lock):
>    TensorFlowLiteSwift (= 0.0.1-nightly)

> In Podfile:
>    TensorFlowLiteSwift (= 0.0.1-nightly)

> None of your spec sources contain a spec satisfying the dependencies: `TensorFlowLiteSwift (= 0.0.1-nightly), TensorFlowLiteSwift (= 0.0.1-nightly)`.

>You have either:
> * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
> * mistyped the name or version.
> * not added the source repo that hosts the Podspec to your Podfile.

**The solution**

To make it work I just removed the Podfile.lock file and run again the command
`pod install`

Maybe the source repo should also be updated.

Thanks!

P.S.: Initially it was posted there https://github.com/tensorflow/tensorflow/issues/35803

**Comment by rthadur** [comment]
@AnyCPU please post tflite issues [tensorflow](https://github.com/tensorflow/tensorflow/issues/) repo

**Comment by norangLemon** [comment]
Hi @AnyCPU, if we can avoid this error by removing `Podfile.lock`, [it should not be removed](https://guides.cocoapods.org/using/using-cocoapods.html#benefits-of-ignoring-the-pods-directory):
```
Whether or not you check in the Pods directory,
the Podfile and Podfile.lock should always be kept under version control.
```

Did you run `pod repo update`?

What version of cocoapod did you use? You can find it with `pod --version`.
I used cocoapod version `1.7.5`, and failed to reproduce the error.

**Comment by AnyCPU** [comment]
@norangLemon 

cocoa pods version is 1.8.4

The `pod repo update` helped.

It is pretty strange I had trouble running it, anyway it works well now.

Thanks!
