### ISSUE TITLE
TF2.0 Error checkpointing custom map

### ISSUE THREAD

**Issue by Jbiloki** [tensorflow/tensorflow#35837]
I am subclassing a keras model with custom layers. Each layer wraps a dictionary of parameters that is used when generating they layers. It seems these param dictionaries are not set before the training checkpoint is made in Tensorflow, they are set after, which causes an error. I am not sure how to fix this, as the `ValueError` being raised also gives outdated information (`tf.contrib` no longer exists). 

> ValueError: Unable to save the object {'units': 32, 'activation':
> 'tanh', 'recurrent_initializer': 'glorot_uniform', 'dropout': 0,
> 'return_sequences': True} (a dictionary wrapper constructed
> automatically on attribute assignment). The wrapped dictionary was
> modified outside the wrapper (its final value was {'units': 32,
> 'activation': 'tanh', 'recurrent_initializer': 'glorot_uniform',
> 'dropout': 0, 'return_sequences': True}, its value when a checkpoint
> dependency was added was None), which breaks restoration on object
> creation.
> 
> If you don't need this dictionary checkpointed, wrap it in a
> tf.contrib.checkpoint.NoDependency object; it will be automatically
> un-wrapped and subsequently ignored.

Here's an example of the Layer that is throwing this issue:

    class RecurrentConfig(BaseLayer):
        '''Basic configurable recurrent layer'''
        def __init__(self, params: Dict[Any, Any], mode: ModeKeys, layer_name: str = '', **kwargs):
            self.layer_name = layer_name
            self.cell_name = params.pop('cell', 'GRU')
            self.num_layers = params.pop('num_layers', 1)
            kwargs['name'] = layer_name
            super().__init__(params, mode, **kwargs)
            if layer_name == '':
                self.layer_name = self.cell_name
            self.layers: List[layers.Layer] = stack_layers(self.params,
                                                           self.num_layers,
                                                           self.cell_name)
    
        def call(self, inputs: np.ndarray) -> layers.Layer:
            '''This function is a sequential/functional call to this layers logic
            Args:
                inputs: Array to be processed within this layer
            Returns:
                inputs processed through this layer'''
            processed = inputs
            for layer in self.layers:
                processed = layer(processed)
            return processed
    
        @staticmethod
        def default_params() -> Dict[Any, Any]:
            return{
                'units': 32,
                'recurrent_initializer': 'glorot_uniform',
                'dropout': 0,
                'recurrent_dropout': 0,
                'activation': 'tanh',
                'return_sequences': True
            }

BaseLayer.py

    '''Basic ABC for a keras style layer'''
    
    from typing import Dict, Any
    
    from tensorflow.keras import layers
    from mosaix_py.mosaix_learn.configurable import Configurable
    
    class BaseLayer(Configurable, layers.Layer):
        '''Base configurable Keras layer'''
        def get_config(self) -> Dict[str, Any]:
            '''Return configuration dictionary as part of keras serialization'''
            config = super().get_config()
            config.update(self.params)
            return config
    
        @staticmethod
        def default_params() -> Dict[Any, Any]:
            raise NotImplementedError('Layer does not implement default params')

**Comment by ravikyram** [comment]
@Jbiloki 

Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version. Also, did you compile from source or install a binary?

Request you to provide simple standalone code to reproduce the issue in our environment. It helps us in localizing the issue faster. If you are unclear what to include see the issue template displayed in [the Github new issue template](https://github.com/tensorflow/tensorflow/issues/new/choose).

We ask for this in the issue submission template, because it is really difficult to help without that information. Thanks!

**Comment by ravikyram** [comment]
@Jbiloki 

Any update on this issue please. Thanks!

**Comment by Jbiloki** [comment]
@ravikyram Yes, I solved the problem here https://stackoverflow.com/questions/59725989/tensorflow-checkpoint-custom-map
