### ISSUE TITLE
tensorflow/python/eager/BUILD:14:1: in cc_library rule //tensorflow/python/eager:pywrap_tfe_lib: cycle in dependency graph

### ISSUE THREAD

**Issue by vistart** [tensorflow/tensorflow#35842]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS: Windows 10 Pro x64 18362
- TensorFlow installed from (source or binary): source (master, 8782b7679c12780fd914827abf4e79ceb51d6b41)
- TensorFlow version: 2.1.0
- Python version: 3.5.3/3.6.8/3.7.6/3.8.1
- Installed using virtualenv? pip? conda?: virtualenv
- Bazel version (if compiling from source): 1.2.1
- GCC/Compiler version (if compiling from source): VS2017 14.16.27023
- CUDA/cuDNN/tensorrt version: 10.2.89, 7.6.5.32, 7.0.0.11
- GPU model and memory: RTX 2080Ti, 11GB

**Describe the problem**

```
build --action_env PYTHON_BIN_PATH="C:/tensorflow/venv36/Scripts/python.exe"
build --action_env PYTHON_LIB_PATH="C:/tensorflow/venv36/lib/site-packages"
build --python_path="C:/tensorflow/venv36/Scripts/python.exe"
build:xla --define with_xla_support=true
build --action_env CUDA_TOOLKIT_PATH="C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.2"
build --action_env TF_CUDA_COMPUTE_CAPABILITIES="6.1,7.5"
build --config=cuda
# build --config=tensorrt
build:opt --copt=/arch:AVX
build:opt --define with_default_optimizations=true
build --define=override_eigen_strong_inline=true
test --flaky_test_attempts=3
test --test_size_filters=small,medium
test:v1 --test_tag_filters=-benchmark-test,-no_oss,-no_windows,-gpu,-oss_serial
test:v1 --build_tag_filters=-benchmark-test,-no_oss,-no_windows,-gpu
test:v2 --test_tag_filters=-benchmark-test,-no_oss,-no_windows,-gpu,-oss_serial,-v1only
test:v2 --build_tag_filters=-benchmark-test,-no_oss,-no_windows,-gpu,-v1only
build --action_env TF_CONFIGURE_IOS="0"

```

If I enable tensorrt and compile using the method described in [this article](https://tensorflow.google.cn/install/source_windows#gpu_support), I get the following error:

```
ERROR: C:/tensorflow/tensorflow/python/eager/BUILD:14:1: in cc_library rule //tensorflow/python/eager:pywrap_tfe_lib: cycle in dependency graph:
    //tensorflow/tools/pip_package:build_pip_package
    //tensorflow/python/keras/distribute:distribute_strategy_test_lib
    //tensorflow/python/distribute:tpu_strategy
    //tensorflow/python/distribute:values
    //tensorflow/python:framework_ops
    //tensorflow/python:tensor_conversion_registry
    //tensorflow/python/eager:context
    //tensorflow/python/eager:executor
    //tensorflow/python:pywrap_tfe
    //tensorflow/python:pywrap_tensorflow
    //tensorflow/python:pywrap_tensorflow_internal
    //tensorflow/python:pywrap_tensorflow_internal.py
    //tensorflow/python:pywrap_tensorflow_internal_py_wrap
.-> //tensorflow/python/eager:pywrap_tfe_lib
|   //tensorflow/python:ndarray_tensor_bridge
|   //tensorflow/python:bfloat16_lib
|   //tensorflow/python:safe_ptr
|   //tensorflow/c/eager:c_api
|   //tensorflow/core/distributed_runtime/rpc:grpc_server_lib
|   //tensorflow/core/distributed_runtime/rpc:grpc_master_service
|   //tensorflow/core/distributed_runtime:master
|   //tensorflow/core/distributed_runtime:master_session
|   //tensorflow/core/distributed_runtime:scheduler
|   //tensorflow/core:tensorflow_opensource
|   //tensorflow/core:all_kernels
|   //tensorflow/core:all_kernels_impl
|   //tensorflow/compiler/tf2tensorrt:trt_op_kernels
|   //tensorflow/python:pywrap_tensorflow_import_lib
|   //tensorflow/python:pywrap_tensorflow_import_lib_file
|   //tensorflow/python:get_pywrap_tensorflow_import_lib_file
|   //tensorflow/python:_pywrap_tensorflow_internal.so
`-- //tensorflow/python/eager:pywrap_tfe_lib
This cycle occurred because of a configuration option
ERROR: Analysis of target '//tensorflow/tools/pip_package:build_pip_package' failed; build aborted
```

**Comment by ymodak** [comment]
Apologies for the delay in response. Is this still an issue? Also the bazel version requirements have been updated. See https://github.com/tensorflow/tensorflow/blob/5d615f2f05d6ecfc37951ef574e359829cb9e3e0/configure.py#L52
Thanks!

**Comment by vistart** [comment]
> Apologies for the delay in response. Is this still an issue? Also the bazel version requirements have been updated. See
> 
> https://github.com/tensorflow/tensorflow/blob/5d615f2f05d6ecfc37951ef574e359829cb9e3e0/configure.py#L52
> 
> 
> Thanks!

thank you for your reply! Due to the influence of COVID-19 recently, I have no access to the computer used for compilation. I may not be able to resume work until mid-May, and I must reply in time if I could have access to computer!

**Comment by vistart** [comment]
> Apologies for the delay in response. Is this still an issue? Also the bazel version requirements have been updated. See
> 
> https://github.com/tensorflow/tensorflow/blob/5d615f2f05d6ecfc37951ef574e359829cb9e3e0/configure.py#L52
> 
> 
> Thanks!

In the r2.2 branch (2b96f36) and master (1b49bd1), the problem still exists.

### System information

OS: Windows 10 Pro x64 18362
TensorFlow installed from (source or binary): source (r2.2, 2b96f36), (master 1b49bd1)
TensorFlow version: 2.2.0, master
Python version: 3.5.3/3.6.8/3.7.7/3.8.2
Installed using virtualenv? pip? conda?: virtualenv
Bazel version (if compiling from source): 2.0.0(r2.2), 3.0.0(master)
GCC/Compiler version (if compiling from source): VS2017 14.16.27023
CUDA/cuDNN/tensorrt version: 10.2.89, 7.6.5.32, 7.0.0.11
GPU model and memory: RTX 2080Ti, 11GB

**Comment by spazmodius** [comment]
I get a similar cycle on 1.15, if I enable `--config=tensorrt` on Windows

**Comment by Saduf2019** [comment]
@vistart 
Could you please try on the latest stable tf version 2.4.1 and let us know if this is still an issue.

**Comment by vistart** [comment]
> @vistart
> Could you please try on the latest stable tf version 2.4.1 and let us know if this is still an issue.

One year has passed since the last submission, and the software environment has changed. Currently I am waiting for NVIDIA to release TensorRT 8.0 for Windows. After the release of this version, I will test the compilation for the first time and report the results here.

**Comment by vistart** [comment]
The problem remains, but the details are different:
```
ERROR: D:/projects/tensorflow/tensorflow/python/BUILD:3345:8: in genrule rule //tensorflow/python:pywrap_tensorflow_import_lib_file: cycle in dependency graph:
    //tensorflow/tools/pip_package:build_pip_package
    //tensorflow/python/keras/distribute:dataset_creator_model_fit_test_base
    //tensorflow/python/platform:client_testlib
    //tensorflow/python:framework_test_lib
    //tensorflow/python/framework:test_lib
    //tensorflow/python:platform
    //tensorflow/python/platform:platform
    //tensorflow/python/lib/io:lib
    //tensorflow/python/lib/io:_pywrap_record_io
    //tensorflow/python/lib/io:_pywrap_record_io.pyd
    //tensorflow/python/lib/io:_pywrap_record_io_pyd_copy
    //tensorflow/python/lib/io:_pywrap_record_io.so
    //tensorflow/python:_pywrap_tensorflow_internal_windows
.-> //tensorflow/python:pywrap_tensorflow_import_lib_file
|   //tensorflow/python:get_pywrap_tensorflow_import_lib_file
|   //tensorflow/python:_pywrap_tensorflow_internal.so
|   //tensorflow/python:safe_ptr
|   //tensorflow/python/lib/core:safe_ptr
|   //tensorflow/c:c_api_no_xla
|   //tensorflow/compiler/mlir/tfr:node_expansion_pass
|   //tensorflow/core/common_runtime/eager:core_no_xla
|   //tensorflow/core/common_runtime/eager:execute
|   //tensorflow/core/common_runtime/eager:mkl_eager_op_rewrite
|   //tensorflow/core:all_kernels
|   //tensorflow/core:all_kernels_impl
|   //tensorflow/compiler/tf2tensorrt:trt_op_kernels
|   //tensorflow/compiler/tf2tensorrt:trt_conversion
|   //tensorflow/python:pywrap_tensorflow_import_lib
`-- //tensorflow/python:pywrap_tensorflow_import_lib_file
This cycle occurred because of a configuration option
ERROR: Analysis of target '//tensorflow/tools/pip_package:build_pip_package' failed; build aborted
```
