### ISSUE TITLE
Keras does not allow using custom iterator from a Python generator

### ISSUE THREAD

**Issue by PrieureDeSion** [tensorflow/tensorflow#35843]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 16.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version (use command below): 2.0
- Python version: 3.7
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Describe the current behavior**
I am trying to run model.fit() on a tf.keras model using a custom data generator on my database. While this generator derives from tf.data.Dataset, it is not a subclass because there some preprocessing involved. However, it supports an iterator that can generate batches of input-output pairs and is compatible with the Keras guidelines. However, tf.keras does not let me use this iterator and throws the following ValueError:
![image](https://user-images.githubusercontent.com/14254187/72313857-9774a680-3641-11ea-9ab2-af8deefd7307.png)

`ValueError: For performance reasons Keras `fit`, `evaluate` and`predict` accept tf.data `Datasets` as input but not iterators that have been manually generated from Datasets by users. Please directly pass in the original `Dataset` object instead of passing in iter(dataset).`

Is there a flag to overrule this behavior, which seems like a performance enhancement issue and not a fundamental inability of the package?

**Comment by amahendrakar** [comment]
@PrieureDeSion,
In order to expedite the trouble-shooting process, could you please provide the complete code to reproduce the issue reported here. Thanks!

**Comment by PrieureDeSion** [comment]
I created a keras Sequence wrapper that calls my custom iterator and that works fine. Slightly inconvenient and certainly inefficient, but gets the job done.
