### ISSUE TITLE
Aggregate lists of trainable variables from different Keras models in Tensorflow v2

### ISSUE THREAD

**Issue by nairouz** [tensorflow/tensorflow#35844]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Colab
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version (use command below): 2.1.0-rc1
- Python version: 3.6
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

I have two neural networks (e.g., f and g) implemented using `tensorflow.keras.Model`. I simply want to compute the gradient of f(g(x)). However, I was not able to aggregate the lists of trainable variables of both models. 

According to Tensorflow V2 documentations: `If you need to aggregate lists of variables (like tf.Graph.get_collection(tf.GraphKeys.VARIABLES)), use the .variables and .trainable_variables attributes of the Layer and Model objects.`

I tried to do so but I am getting this weird error:

    /content/drive/My Drive/Colab/IIC/IIC.py in train_step(self, x, gx, head)
        197 
        198                 gradients = tape.gradient(loss, trainable_variables)
    --> 199                 self.optimizer.apply_gradients(zip(gradients, trainable_variables))
        200                 self.train_loss(loss)
        201 
    
    /tensorflow-2.1.0/python3.6/tensorflow_core/python/keras/optimizer_v2/optimizer_v2.py in apply_gradients(self, grads_and_vars, name)
        432         _ = self.iterations
        433         self._create_hypers()
    --> 434         self._create_slots(var_list)
        435 
        436       if not grads_and_vars:
    
    /tensorflow-2.1.0/python3.6/tensorflow_core/python/keras/optimizer_v2/adam.py in _create_slots(self, var_list)
        147     # Separate for-loops to respect the ordering of slot variables from v1.
        148     for var in var_list:
    --> 149       self.add_slot(var, 'm')
        150     for var in var_list:
        151       self.add_slot(var, 'v')
    
    /tensorflow-2.1.0/python3.6/tensorflow_core/python/keras/optimizer_v2/optimizer_v2.py in add_slot(self, var, slot_name, initializer)
        572     if slot_name not in self._slot_names:
        573       self._slot_names.append(slot_name)
    --> 574     var_key = _var_key(var)
        575     slot_dict = self._slots.setdefault(var_key, {})
        576     weight = slot_dict.get(slot_name, None)
    
    /tensorflow-2.1.0/python3.6/tensorflow_core/python/keras/optimizer_v2/optimizer_v2.py in _var_key(var)
       1063   if hasattr(var, "_distributed_container"):
       1064     var = var._distributed_container()
    -> 1065   if var._in_graph_mode:
       1066     return var._shared_name
       1067   return var._unique_id
    
    AttributeError: 'list' object has no attribute '_in_graph_mode'

The `trainable_variables` is just a list of trainable variables from both models f and g.

    trainable_variables = [f.trainable_variables, g.trainable_variables]

**Comment by ravikyram** [comment]
@nairouz 

Request you to provide colab link or simple standalone code to reproduce the issue in our environment. It helps us in localizing the issue faster. Thanks!

**Comment by nairouz** [comment]
@ravikyram 

Here is a toy example:

```
from __future__ import absolute_import, division, print_function, unicode_literals

import tensorflow as tf

from tensorflow.keras.layers import Dense, Flatten, Conv2D
from tensorflow.keras import Model


mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

# Add a channels dimension
x_train = x_train[..., tf.newaxis]
x_test = x_test[..., tf.newaxis]


train_ds = tf.data.Dataset.from_tensor_slices(
    (x_train, y_train)).shuffle(10000).batch(32)

test_ds = tf.data.Dataset.from_tensor_slices((x_test, y_test)).batch(32)


class StupidModel1(Model):
  def __init__(self):
    super(StupidModel1, self).__init__()
    self.conv1 = Conv2D(32, 3, activation='relu')
    self.flatten = Flatten()

  def call(self, x):
    x = self.conv1(x)
    x = self.flatten(x)
    return x

class StupidModel2(Model):
  def __init__(self):
    super(StupidModel2, self).__init__()
    self.d1 = Dense(128, activation='relu')
    self.d2 = Dense(10, activation='softmax')

  def call(self, x):
    x = self.d1(x)
    return self.d2(x)

# Create an instance of the model
stupid_model_1 = StupidModel1()
stupid_model_2 = StupidModel2()

loss_object = tf.keras.losses.SparseCategoricalCrossentropy()

optimizer = tf.keras.optimizers.Adam()

train_loss = tf.keras.metrics.Mean(name='train_loss')
train_accuracy = tf.keras.metrics.SparseCategoricalAccuracy(name='train_accuracy')

test_loss = tf.keras.metrics.Mean(name='test_loss')
test_accuracy = tf.keras.metrics.SparseCategoricalAccuracy(name='test_accuracy')

@tf.function
def train_step(images, labels):
  with tf.GradientTape() as tape:
    predictions = stupid_model_2(stupid_model_1(images))
    loss = loss_object(labels, predictions)
  trainable_variables_list = [stupid_model_1.trainable_variables, stupid_model_1.trainable_variables]
  gradients = tape.gradient(loss, [stupid_model_1.trainable_variables, stupid_model_1.trainable_variables])
  optimizer.apply_gradients(zip(gradients, trainable_variables_list))

  train_loss(loss)
  train_accuracy(labels, predictions)

@tf.function
def test_step(images, labels):
  predictions = model(images)
  t_loss = loss_object(labels, predictions)

  test_loss(t_loss)
  test_accuracy(labels, predictions)

EPOCHS = 5

for epoch in range(EPOCHS):
  # Reset the metrics at the start of the next epoch
  train_loss.reset_states()
  train_accuracy.reset_states()
  test_loss.reset_states()
  test_accuracy.reset_states()

  for images, labels in train_ds:
    train_step(images, labels)

  for test_images, test_labels in test_ds:
    test_step(test_images, test_labels)

  template = 'Epoch {}, Loss: {}, Accuracy: {}, Test Loss: {}, Test Accuracy: {}'
  print(template.format(epoch+1,
                        train_loss.result(),
                        train_accuracy.result()*100,
                        test_loss.result(),
                        test_accuracy.result()*100))
```

**Comment by nairouz** [comment]
It is not a bug!!
I am sorry.

**Comment by nairouz** [comment]
It is not a bug!!
I am sorry.

**Comment by ErikEngerd** [comment]
If it is not a bug, then what is the preferred way to solve this? I have  a similar case.
Calling apply_gradients() twice, once for every model with its own trainable variables, does not give an error but might be wrong since the optimizer keeps internal state. Another solution would be to create two optimizers, one for every model, and then call apply_gradients separately for every model. 

Again, what is the preferred solution here if it is not a bug?

**Comment by frozenburst** [comment]
> If it is not a bug, then what is the preferred way to solve this? I have a similar case.
> Calling apply_gradients() twice, once for every model with its own trainable variables, does not give an error but might be wrong since the optimizer keeps internal state. Another solution would be to create two optimizers, one for every model, and then call apply_gradients separately for every model.
> 
> Again, what is the preferred solution here if it is not a bug?

The list of trainable_weights might be [list of variable], instead of [[list of variable], [list of variable]].
