### ISSUE TITLE
Bidirectional encoder for seq2seq in Tensorflow

### ISSUE THREAD

**Issue by krayush07** [tensorflow/tensorflow#3585]
All methods in `seq2seq.py` library supports encoder-decoder system with the input in forward sequence. How can we construct a bi-directional encoder-decoder using the libraries or else, much like the concept in bi-directional LSTM?

**Comment by michaelisard** [comment]
This kind of usage question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow). Github issues are for TensorFlow bugs and installation problems. Thanks!

**Comment by krayush07** [comment]
@michaelisard: I did not receive any answer on Stackoverflow,  hence I decided to put a query over here.

**Comment by jzhang533** [comment]
you'll need to implement your own encoder,
for decoder part, you could use tf provided ones : rnn_decoder or attention_decoder
in tf0.9, they are implemented in 
lib/python2.7/site-packages/tensorflow/python/ops/seq2seq.py
encoders already implemented in this file are good start points for implementing your own encoder.
