### ISSUE TITLE
TensorFlow Lite with Python

### ISSUE THREAD

**Issue by peter197321** [tensorflow/tensorflow#35851]
Hi,

is there a way (documented procedure) for preparing "Python wheel" to just install the interpreter to run inferences with TensorFlow Lite.  On the platform I use (arm64) I have option to run an inference with CPU or GPU. How this will be evaluated via Interpreter, is there an option to have more possible IP blocks to run inference on?
I'm using the 1.13.2 version.

**Comment by ymodak** [comment]
We have prebuilt tf lite interpreter python wheel for TF 1.14 arm64 platform.
See https://www.tensorflow.org/lite/guide/python#install_just_the_tensorflow_lite_interpreter

**Comment by peter197321** [comment]
is that possible to have more available accelerators? so what if GPU and
CPU are available and both capability to run tf-lite inference?

**Comment by ymodak** [comment]
Unfortunately not. For using gpu inference you have to implement gpu delegate. Thanks!
