### ISSUE TITLE
TensorBoard callback without profile_batch setting cause Errors: CUPTI_ERROR_INSUFFICIENT_PRIVILEGES and CUPTI_ERROR_INVALID_PARAMETER

### ISSUE THREAD

**Issue by gawain-git-code** [tensorflow/tensorflow#35860]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Stateless LSTM from Keras tutorial using tf backend
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.1.0
- Python version: 3.7.4
- CUDA/cuDNN version: 10.1
- GPU model and memory: MX150 10GB

**Describe the current behavior**
When using tf.keras.callbacks.TensorBoard() without the profile_batch setting, it gives out errors of CUPTI_ERROR_INSUFFICIENT_PRIVILEGES and CUPTI_ERROR_INVALID_PARAMETER from tensorflow/core/profiler/internal/gpu/cupti_tracer.cc.

**Describe the expected behavior**
With profile_batch = 0, these two errors are gone. 
But comes back when profile_batch = 1, or other non-zero values.

**Code to reproduce the issue**
```

from __future__ import print_function
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, LSTM


input_len = 1000
tsteps = 2
lahead = 1
batch_size = 1
epochs = 5

print("*" * 33)
if lahead >= tsteps:
    print("STATELESS LSTM WILL ALSO CONVERGE")
else:
    print("STATELESS LSTM WILL NOT CONVERGE")
print("*" * 33)

np.random.seed(1986)

print('Generating Data...')


def gen_uniform_amp(amp=1, xn=10000):

    data_input = np.random.uniform(-1 * amp, +1 * amp, xn)
    data_input = pd.DataFrame(data_input)
    return data_input


to_drop = max(tsteps - 1, lahead - 1)
data_input = gen_uniform_amp(amp=0.1, xn=input_len + to_drop)

expected_output = data_input.rolling(window=tsteps, center=False).mean()

if lahead > 1:
    data_input = np.repeat(data_input.values, repeats=lahead, axis=1)
    data_input = pd.DataFrame(data_input)
    for i, c in enumerate(data_input.columns):
        data_input[c] = data_input[c].shift(i)

expected_output = expected_output[to_drop:]
data_input = data_input[to_drop:]


def create_model(stateful):
    model = Sequential()
    model.add(LSTM(20,
              input_shape=(lahead, 1),
              batch_size=batch_size,
              stateful=stateful))
    model.add(Dense(1))
    model.compile(loss='mse', optimizer='adam')
    return model

print('Creating Stateful Model...')
model_stateful = create_model(stateful=True)


def split_data(x, y, ratio=0.8):
    to_train = int(input_len * ratio)
    to_train -= to_train % batch_size
    x_train = x[:to_train]
    y_train = y[:to_train]
    x_test = x[to_train:]
    y_test = y[to_train:]

    # tweak to match with batch_size
    to_drop = x.shape[0] % batch_size
    if to_drop > 0:
        x_test = x_test[:-1 * to_drop]
        y_test = y_test[:-1 * to_drop]

    # some reshaping
    reshape_3 = lambda x: x.values.reshape((x.shape[0], x.shape[1], 1))
    x_train = reshape_3(x_train)
    x_test = reshape_3(x_test)

    reshape_2 = lambda x: x.values.reshape((x.shape[0], 1))
    y_train = reshape_2(y_train)
    y_test = reshape_2(y_test)

    return (x_train, y_train), (x_test, y_test)


(x_train, y_train), (x_test, y_test) = split_data(data_input, expected_output)
print('x_train.shape: ', x_train.shape)
print('y_train.shape: ', y_train.shape)
print('x_test.shape: ', x_test.shape)
print('y_test.shape: ', y_test.shape)

print('Creating Stateless Model...')
model_stateless = create_model(stateful=False)

import os
import datetime
ROOT_DIR = os.getcwd()
log_dir = os.path.join('callback_tests')
if not os.path.exists(log_dir):
    os.makedirs(log_dir)
print(log_dir)
tensorboard_callback = tf.keras.callbacks.TensorBoard(log_dir=log_dir)
                                       
print('Training')
history = model_stateless.fit(x_train,
                    y_train,
                    batch_size=batch_size,
                    epochs=epochs,
                    verbose=1,
                    validation_data=(x_test, y_test),
                    shuffle=False,
                    callbacks=[tensorboard_callback]
                    )


```

**Other info / logs**
Train on 800 samples, validate on 200 samples
2020-01-14 21:30:27.591905: I tensorflow/core/profiler/lib/profiler_session.cc:225] Profiler session started.
2020-01-14 21:30:27.594743: I tensorflow/core/profiler/internal/gpu/cupti_tracer.cc:1259] Profiler found 1 GPUs
2020-01-14 21:30:27.599172: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cupti64_101.dll
2020-01-14 21:30:27.704083: E tensorflow/core/profiler/internal/gpu/cupti_tracer.cc:1307] function cupti_interface_->Subscribe( &subscriber_, (CUpti_CallbackFunc)ApiCallback, this)failed with error CUPTI_ERROR_INSUFFICIENT_PRIVILEGES
2020-01-14 21:30:27.716790: E tensorflow/core/profiler/internal/gpu/cupti_tracer.cc:1346] function cupti_interface_->ActivityRegisterCallbacks( AllocCuptiActivityBuffer, FreeCuptiActivityBuffer)failed with error CUPTI_ERROR_INSUFFICIENT_PRIVILEGES
Epoch 1/5
2020-01-14 21:30:28.370429: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cublas64_10.dll
2020-01-14 21:30:28.651767: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudnn64_7.dll
2020-01-14 21:30:29.662864: E tensorflow/core/profiler/internal/gpu/cupti_tracer.cc:1329] function cupti_interface_->EnableCallback( 0 , subscriber_, CUPTI_CB_DOMAIN_DRIVER_API, cbid)failed with error CUPTI_ERROR_INVALID_PARAMETER
2020-01-14 21:30:29.670282: I tensorflow/core/profiler/internal/gpu/device_tracer.cc:88]  GpuTracer has collected 0 callback api events and 0 activity events.
800/800 [==============================] - 5s 6ms/sample - loss: 0.0011 - val_loss: 0.0011
Epoch 2/5
800/800 [==============================] - 3s 4ms/sample - loss: 8.5921e-04 - val_loss: 0.0010
Epoch 3/5
800/800 [==============================] - 3s 3ms/sample - loss: 8.5613e-04 - val_loss: 0.0010
Epoch 4/5
800/800 [==============================] - 3s 4ms/sample - loss: 8.5458e-04 - val_loss: 9.9713e-04
Epoch 5/5
800/800 [==============================] - 3s 4ms/sample - loss: 8.5345e-04 - val_loss: 9.8825e-04

**Comment by airMeng** [comment]
Facing the same problem.

**Comment by kevin-hartman** [comment]
Same issue. Different code sample.

OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
TensorFlow installed from (source or binary): binary
TensorFlow version (use command below): 2.1.0
Python version: 3.7.6
CUDA/cuDNN version: 10.1
GPU model and memory: RX 2080 Ti

**Comment by eduardofv** [comment]
Same (INSUFFICIENT PRIVILEGES):
OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
TensorFlow installed from (source or binary): binary

CUDA/cuDNN version: 10.1

Host: ttmagpie_d99d3f105d0a
Python: 3.6.9 (default, Nov  7 2019, 10:44:02) 
[GCC 8.3.0]
Tensorflow: 2.1.0
GPU: available
GPU 0: GeForce GTX 960M (UUID: GPU-c604cc5b-50da-5483-bde7-f562fb1c3420)
GPU Memory:4GB
Keras: 2.2.4-tf
Hub: 0.7.0
```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 435.21       Driver Version: 435.21       CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 960M    Off  | 00000000:02:00.0 Off |                  N/A |
| N/A   46C    P5    N/A /  N/A |   3869MiB /  4046MiB |     26%      Default |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
+-----------------------------------------------------------------------------+
```

**Comment by gawain-git-code** [comment]
@airMeng @kevin-hartman @eduardofv Are you guys satisfy with the answer from @oanush ?

I personally would not because that was just telling me I can only use profile_batch settings safely in google colab instead of on my own machine setup. 

This was not answering the root cause of the problem of why cupti_tracer is signalling the errors. But thank you @oanush for spending the time to help out.

**Comment by eduardofv** [comment]
I am still receiving the error but have moved to another environment. It may have to do with driver updates on Ubuntu. Will try to check again and get back to you.

**Comment by gowthamkpr** [comment]
The error states that

> User doesn't have sufficient privileges which are required to start the profiling session. One possible reason for this may be that the NVIDIA driver or your system administrator may have restricted access to the NVIDIA GPU performance counters. 

May be its an error with the configuration itself.

**Comment by shaywinter** [comment]
Facing same issue when capturing profile data by tensorboard through gRPC: Tried following [solution](https://developer.nvidia.com/nvidia-development-tools-solutions-err-nvgpuctrperm-cupti) by nvidia (enable non privileged access to profile counters) - to no avail. my training runs as root inside a container (which was other solution suggested by nvidia).
TF2.1.0, NVIDIA Driver Version: 418.56 CUDA Version: 10.1

**Comment by dartlune** [comment]
I have the same issue when I use the official TensorFlow docker image(tensorflow/tensorflow:2.1.0-gpu-py3).
I used 'tf.keras.callbacks.TensorBoard' with model.fit() method, but during the first epoch following errors came out.

E tensorflow/core/profiler/internal/gpu/cupti_tracer.cc:1307] function cupti_interface_->Subscribe( &subscriber_, (CUpti_CallbackFunc)ApiCallback, this)failed with error CUPTI_ERROR_INSUFFICIENT_PRIVILEGES

E tensorflow/core/profiler/internal/gpu/cupti_tracer.cc:1329] function cupti_interface_->EnableCallback( 0 , subscriber_, CUPTI_CB_DOMAIN_DRIVER_API, cbid)failed with error CUPTI_ERROR_INVALID_PARAMETER

**Comment by tamaramiteva** [comment]
@dartlune Did going back to the 'tensorflow/tensorflow:2.0.0-gpu-py3' image helped?

I cannot save the model in both versions of the docker image!

Any suggestions?

**Comment by dartlune** [comment]
@tamaramiteva Actually I had some error with tensorflow/tensorflow:2.0.0-gpu-py3'.
It was a little different error with the above things.
So I did a little search and found a solution that adds some paths.

LD_LIBRARY_PATH=:/usr/local/cuda/lib64:/usr/local/cuda/extras/CUPTI/lib64
LD_INCLUDE_PATH=:/usr/local/cuda/include:/usr/local/cuda/extras/CUPTI/include

**Comment by Liu-Da** [comment]
Any update about this problem?

**Comment by vlasenkoalexey** [comment]
This is due to NVIDIA CUPTI libary API change:  https://developer.nvidia.com/nvidia-development-tools-solutions-err-nvgpuctrperm-cupti
In order for GPU profiling to work you need to run your job as sudo.
On Kubernetes you'll need a allowPrivilegeEscalation: true, you can see example here:
https://github.com/vlasenkoalexey/criteo/blob/05e2aa4c5a15b9e437a364295b7f1e5e2653a22b/scripts/template.yaml.jinja#L136
It is not convenient and won't work for all use-cases, I hope there is a better solution.

Also note that tensorboard profiler plugin got broken by Chrome 80 update, see https://github.com/tensorflow/tensorboard/issues/3209

Suggested workaround works - run Chrome with --enable-blink-features=ShadowDOMV0,CustomElementsV0,HTMLImports flags 

like:
/usr/bin/google-chrome-stable --enable-blink-features=ShadowDOMV0,CustomElementsV0,HTMLImports

**Comment by trisolaran** [comment]
Adding `options nvidia "NVreg_RestrictProfilingToAdminUsers=0"` to /etc/modprobe.d/nvidia-kernel-common.conf
and reboot should resolve the permision issue.

**Comment by dartlune** [comment]
@tamaramiteva 
I resolved the problem with docker run option '--privileged=true'.
There is no more errors such as 'CUPTI_ERROR_INSUFFICIENT_PRIVILEGES'.

**Comment by JiayuanSternLi** [comment]
> @tamaramiteva
> I resolved the problem with docker run option '--privileged=true'.
> There is no more errors such as 'CUPTI_ERROR_INSUFFICIENT_PRIVILEGES'.

GOOD!!! it worksl. Thank you

**Comment by mathpluscode** [comment]
> Adding `options nvidia "NVreg_RestrictProfilingToAdminUsers=0"` to /etc/modprobe.d/nvidia-kernel-common.conf
> and reboot should resolve the permision issue.

I had the same issue and this works perfectly for me. No more errors about libcupti.

**Comment by VladislavKlass** [comment]
Anyone with the same issue on Windows 10? The two offered solutions only work for Linux.

**Comment by VladislavKlass** [comment]
> Anyone with the same issue on Windows 10? The two offered solutions only work for Linux.

This solved the issue for me:
Right-click on your desktop desktop for quick access to the NVIDIA Control Panel
Windows Step 1: Open the NVIDIA Control Panel, select 'Desktop', and ensure 'Enable Developer Settings' is checked.
Windows Step 2: Under 'Developer' > 'Manage GPU Performance Counters', select 'Allow access to the GPU performance counter to all users' to enable unrestricted profiling[1]

**Comment by zaccharieramzi** [comment]
The current proposed solution didn't work for me.
My error still reads:
```
2020-03-31 17:35:59.512872: E tensorflow/core/profiler/internal/gpu/cupti_tracer.cc:1307] function cupti_interface_->Subscribe( &subscriber_, (CUpti_CallbackFunc)ApiCallback, this)failed with error CUPTI_ERROR_INSUFFICIENT_PRIVILEGES
2020-03-31 17:35:59.514268: E tensorflow/core/profiler/internal/gpu/cupti_tracer.cc:1346] function cupti_interface_->ActivityRegisterCallbacks( AllocCuptiActivityBuffer, FreeCuptiActivityBuffer)failed with error CUPTI_ERROR_INSUFFICIENT_PRIVILEGES
2020-03-31 17:36:00.187507: E tensorflow/core/profiler/internal/gpu/cupti_tracer.cc:1329] function cupti_interface_->EnableCallback( 0 , subscriber_, CUPTI_CB_DOMAIN_DRIVER_API, cbid)failed with error CUPTI_ERROR_INVALID_PARAMETER
2020-03-31 17:36:00.187591: I tensorflow/core/profiler/internal/gpu/device_tracer.cc:88]  GpuTracer has collected 0 callback api events and 0 activity events.
```

I also tried simply running `modprobe nvidia NVreg_RestrictProfilingToAdminUsers=0`, but it didn't work either.
Starting the application in `sudo` mode did solve the problem, but of course it's not ideal...

**Comment by ybagdasa** [comment]
> @tamaramiteva
> I resolved the problem with docker run option '--privileged=true'.
> There is no more errors such as 'CUPTI_ERROR_INSUFFICIENT_PRIVILEGES'.

This worked for me and now the profile page of tensorboard is finally showing some output! Thanks @dartlune

**Comment by hackf5** [comment]
> > Anyone with the same issue on Windows 10? The two offered solutions only work for Linux.
> 
> This solved the issue for me:
> Right-click on your desktop desktop for quick access to the NVIDIA Control Panel
> Windows Step 1: Open the NVIDIA Control Panel, select 'Desktop', and ensure 'Enable Developer Settings' is checked.
> Windows Step 2: Under 'Developer' > 'Manage GPU Performance Counters', select 'Allow access to the GPU performance counter to all users' to enable unrestricted profiling[1]

This seems to be a global setting, so it works with monkey-patched Anaconda environments.

**Comment by Student-HXJ** [comment]
> The current proposed solution didn't work for me.
> My error still reads:
> 
> ```
> 2020-03-31 17:35:59.512872: E tensorflow/core/profiler/internal/gpu/cupti_tracer.cc:1307] function cupti_interface_->Subscribe( &subscriber_, (CUpti_CallbackFunc)ApiCallback, this)failed with error CUPTI_ERROR_INSUFFICIENT_PRIVILEGES
> 2020-03-31 17:35:59.514268: E tensorflow/core/profiler/internal/gpu/cupti_tracer.cc:1346] function cupti_interface_->ActivityRegisterCallbacks( AllocCuptiActivityBuffer, FreeCuptiActivityBuffer)failed with error CUPTI_ERROR_INSUFFICIENT_PRIVILEGES
> 2020-03-31 17:36:00.187507: E tensorflow/core/profiler/internal/gpu/cupti_tracer.cc:1329] function cupti_interface_->EnableCallback( 0 , subscriber_, CUPTI_CB_DOMAIN_DRIVER_API, cbid)failed with error CUPTI_ERROR_INVALID_PARAMETER
> 2020-03-31 17:36:00.187591: I tensorflow/core/profiler/internal/gpu/device_tracer.cc:88]  GpuTracer has collected 0 callback api events and 0 activity events.
> ```
> 
> I also tried simply running `modprobe nvidia NVreg_RestrictProfilingToAdminUsers=0`, but it didn't work either.
> Starting the application in `sudo` mode did solve the problem, but of course it's not ideal...

I got the same problem as yours, have you found an ideal way?

**Comment by zaccharieramzi** [comment]
@Student-HXJ unfortunately no, I was just running my script or jupyter notebook with sudo.

**Comment by alvinwatner** [comment]
> > Anyone with the same issue on Windows 10? The two offered solutions only work for Linux.
> 
> This solved the issue for me:
> Right-click on your desktop desktop for quick access to the NVIDIA Control Panel
> Windows Step 1: Open the NVIDIA Control Panel, select 'Desktop', and ensure 'Enable Developer Settings' is checked.
> Windows Step 2: Under 'Developer' > 'Manage GPU Performance Counters', select 'Allow access to the GPU performance counter to all users' to enable unrestricted profiling[1]

Also just for a reminder, dont forget to press 'Apply' button on the right bottom corner.

**Comment by bhomaidan1990** [comment]
> 
> 
> > Anyone with the same issue on Windows 10? The two offered solutions only work for Linux.
> 
> This solved the issue for me:
> Right-click on your desktop desktop for quick access to the NVIDIA Control Panel
> Windows Step 1: Open the NVIDIA Control Panel, select 'Desktop', and ensure 'Enable Developer Settings' is checked.
> Windows Step 2: Under 'Developer' > 'Manage GPU Performance Counters', select 'Allow access to the GPU performance counter to all users' to enable unrestricted profiling[1]

I did that with Alienware 15m GPU 1070 MaxQ, after that the laptop stopped responding, so I restarted it, after that Nvidia control panel disappeared from the right mouse click! nad I wasn't able to use my GPU! maybe the NVIDIA driver  isn't working, so I have to install it again!

**Comment by robin-shaun** [comment]
> Adding `options nvidia "NVreg_RestrictProfilingToAdminUsers=0"` to /etc/modprobe.d/nvidia-kernel-common.conf
> and reboot should resolve the permision issue.

In my case, this solution doesn't work for anaconda, but work for normal python. Thanks a lot!

**Comment by adampl** [comment]
For people using Docker on Linux:
Instead of running the container with `--privileged=true` just pass `--cap-add=CAP_SYS_ADMIN`.

**Comment by kunihik0** [comment]
I'm facing same error.
I use ubuntu18.04 , CUDA10.1 and tensorflow2.2.
Please tell me if you can solve it in the same environment.

**Comment by uchar** [comment]
If you have this problem on windows, Open cmd in "Administrator Mode"

**Comment by kunihik0** [comment]
@uchar thanks for your reply.
I had error like [this](https://github.com/tensorflow/tensorflow/issues/35860#issue-549483874)
But refer to this, I added `"NVreg_RestrictProfilingToAdminUsers=0"` to `/etc/modprobe.d/nvidia-kernel-common.conf` and `export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/cuda-10.1/extras/CUPTI/lib64` to `~/.bashrc`. Then I could  solve it!　
> Adding `options nvidia "NVreg_RestrictProfilingToAdminUsers=0"` to /etc/modprobe.d/nvidia-kernel-common.conf
> and reboot should resolve the permision issue.

**Comment by d-miketa** [comment]
Can confirm that the following fixed the problem for me. It's possible that only a subset is strictly necessary.

(note: Docker config, using official 2.2.0 image)
* updating host machine to Ubuntu 20.04
* adding `options nvidia "NVreg_RestrictProfilingToAdminUsers=0"` to `/etc/modprobe.d/nvidia-kernel-common.conf` and running `update-initramfs -u`
* adding `export CUDA_VERSION="10.1"`, `export LD_LIBRARY_PATH="/usr/local/cuda-${CUDA_VERSION}/lib64:/usr/local/cuda-${CUDA_VERSION}/extras/CUPTI/lib64` and `export LD_INCLUDE_PATH="/usr/local/cuda-${CUDA_VERSION}/include:/usr/local/cuda-${CUDA_VERSION}/extras/CUPTI/include"` to the host machine's `.zshrc`
* adding `ENV LD_INCLUDE_PATH="/usr/local/cuda/include:/usr/local/cuda/extras/CUPTI/include:$LD_INCLUDE_PATH` to the Dockerfile
* running the Docker container with `--privileged`

**Comment by gizmoy** [comment]
> For people using Docker on Linux:
> Instead of running the container with `--privileged=true` just pass `--cap-add=CAP_SYS_ADMIN`.

This is the solution for multiple-GPU training. Thanks!

**Comment by vivekgr92** [comment]
> LD_LIBRARY_PATH=:/usr/local/cuda/lib64:/usr/local/cuda/extras/CUPTI/lib64
> LD_INCLUDE_PATH=:/usr/local/cuda/include:/usr/local/cuda/extras/CUPTI/include

Thanks , It worked for me.

**Comment by mikechen66** [comment]
I have had the test on the above-mentioned solutions. It seems that there is no quick way to go out of the dilemma of the error "CUPTI_ERROR_INSUFFICIENT_PRIVILEGES" 

1. The ad-hoc solution 

Even though Nvidia gives the temporal solution "CAP_SYS_ADMIN", it is a ad hoc solution. It sometimes works and does not work in the rest of the time. 

$ python abc.py --cap-add=CAP_SYS_ADMIN

2. LD_LIBRARY_PATH is not reliable

The following solutions sometimes work ans does not work in the rest of the time. 

LD_LIBRARY_PATH=:/usr/local/cuda/lib64:/usr/local/cuda/extras/CUPTI/lib64
LD_INCLUDE_PATH=:/usr/local/cuda/include:/usr/local/cuda/extras/CUPTI/include

or 

LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/cuda-10.1/extras/CUPTI/lib64

3. No  path of "/etc/modprobe.d/nvidia-kernel-common.conf"

The modprobe.d does not include the path iof "/etc/modprobe.d/nvidia-kernel-common.conf". So I could not add "NVreg_RestrictProfilingToAdminUsers=0" to /etc/modprobe.d/nvidia-kernel-common.conf 

Nvidia gives quite value explanation on the error. So it is quite strange.

**Comment by Liu-Da** [comment]
> Adding `options nvidia "NVreg_RestrictProfilingToAdminUsers=0"` to /etc/modprobe.d/nvidia-kernel-common.conf
> and reboot should resolve the permision issue.

Thanks , It worked for me.

**Comment by bonryu** [comment]
None of the solutions offered here nor  anywhere else has worked for me. Perhaps it may work if one upgrades from Ubuntu 16.04 to Ubuntu 18.04 as I see in this thread. But since I'm on a shared server, it may take some time to do the upgrade. I have not tried docker yet.

OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 16.04
TensorFlow installed from (source or binary): binary
TensorFlow version (use command below): 2.3.0 (installed with pip install -U tensorflow)
Python version: 3.8.5
CUDA/cuDNN version: 10.1
GPU model and memory: GTX 1080 Ti

**Comment by SarfarazHabib** [comment]
I am having the same error in anaconda environment. None of the solutions posted above work for me. Does anyone have any ideas what can be done?
Also what does this error actually mean, if someone is kind enough to explain it to a noob ?

**Comment by trisolaran** [comment]
Tensorflow use NVIDIA provided libcupti for GPU tracing support. However since CUDA 10, that functionality requires CAP_SYS_ADMIN privilege, or you should change the /etc/modprobe.d/nvidia-kernel-common.conf (which also require sudo, but only once).
More information can be found at (which include how to do it on windows)
https://developer.nvidia.com/nvidia-development-tools-solutions-err-nvgpuctrperm-cupti

I believe that NVIDIA enforce this restriction because of some research papers said you can steal user secrets by probing performance counters.

**Comment by SarfarazHabib** [comment]
Hey @trisolaran thanks for brief intro. The thing is i do not have /etc/modprobe.d/nvidia-kernel-common.conf such file. I am using a conda environment.

**Comment by kunihik0** [comment]
@SarfarazHabib Hi I am using a conda enviroment too and I solved this problem by adding  
`options nvidia "NVreg_RestrictProfilingToAdminUsers=0"` to `/etc/modprobe.d/nvidia-kernel-common.conf`. I had not had the file too , so you should make the file.

**Comment by SarfarazHabib** [comment]
@kunihik0 Thanks alot for the help. The error is now gone but my training stucks after random epochs. I am using tensorflow 2.3 for now on ubuntu 18.04. Can anyone guide me in any direction with respect to this new problem ??

**Comment by solarflarefx** [comment]
> > Anyone with the same issue on Windows 10? The two offered solutions only work for Linux.
> 
> This solved the issue for me:
> Right-click on your desktop desktop for quick access to the NVIDIA Control Panel
> Windows Step 1: Open the NVIDIA Control Panel, select 'Desktop', and ensure 'Enable Developer Settings' is checked.
> Windows Step 2: Under 'Developer' > 'Manage GPU Performance Counters', select 'Allow access to the GPU performance counter to all users' to enable unrestricted profiling[1]

This solution works great for Windows 10 systems.  But what about Windows Server 2019?  It seems that now Microsoft requires you to get NVIDIA Control Panel from the Microsoft Store, but that is not available on Windows Server 2019.  Is there an alternative way to allow these permissions on Windows Server 2019?

**Comment by Ruomei** [comment]
> Adding `options nvidia "NVreg_RestrictProfilingToAdminUsers=0"` to /etc/modprobe.d/nvidia-kernel-common.conf
> and reboot should resolve the permision issue.

This works for me after switching from conda to virtualenv and I also need to use `sudo` inside my virtualenv with the python under `/venv/bin/python`. Other dependencies are:

OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 16.04
TensorFlow installed from (source or binary): binary
TensorFlow version (use command below): 2.3.1
Python version: 3.7.6
CUDA/cuDNN version: 11.0
GPU model: GeForce GTX TITAN X

Now I can profile with --profile_steps=1000, 1005, for example, 5 steps, but if I increase it to 10, there is this non-deterministic segfault appearing. Not sure whether this happened to anyone else?

**Comment by d-miketa** [comment]
> Now I can profile with --profile_steps=1000, 1005, for example, 5 steps, but if I increase it to 10, there is this non-deterministic segfault appearing. Not sure whether this happened to anyone else?

Yes, I get that segfault too – I think it's because the overhead of profiling, on top of regular GPU computations, causes GPU memory overflow.

**Comment by dhiren-hamal** [comment]
In order to run docker:
`nvidia-docker run '--privileged=true' -d -it --name retina_net -v /home/readib/Experiments/:/home -p 8000:8888 -v /tmp/.X11-unix/:/tmp/.X11-unix -e DISPLAY=$DISPLAY retina_net:latest /bin/bash`

**Comment by lyw615** [comment]
@vlasenkoalexey Do  you mean the  version  of   NVIDIA CUPTI libary that  changes  API result in the error?  Will the old version that API  doesn't change  run normally?

**Comment by vlasenkoalexey** [comment]
CUPTI library is part of CUDA, before CUDA 10.x profiling didn't require admin privileges. See nvidia doc for details: https://developer.nvidia.com/nvidia-development-tools-solutions-err-nvgpuctrperm-cupti

**Comment by lyw615** [comment]
@vlasenkoalexey But  CUDA 10.x  is also troubled with the privileges problem in my local , so do many people under this issue.

**Comment by sushreebarsa** [comment]
Was able to reproduce the issue in TF v2.5 ,please find the gist [here](https://colab.research.google.com/gist/sushreebarsa/10817d7a9423b0ac02cc77ef7ac9097d/untitled123.ipynb)..Thanks !

**Comment by castielhzh** [comment]
I also met this problem.My OS is centos7, adding the conf file under /etc/modprobe.d/ and then rebuilding the inital RAM disk by `sudo dracut  --force` and reboot solve the problem.

**Comment by mohantym** [comment]
Hi @gawain-git-code  , Could you look at this[ thread ](https://forums.developer.nvidia.com/t/cupti-has-no-sufficient-privilege/144565/2)for answer ?

**Comment by berlinsaint** [comment]
how about cpu train?

**Comment by corneliusschroeder** [comment]
I'm running a tensorflow application in a Docker Container on a Windows Machine with WSL2. I get the following errors:

` tensorflow/core/profiler/lib/profiler_session.cc:159] Profiler session started.
I tensorflow/core/profiler/internal/gpu/cupti_tracer.cc:1363] Profiler found 1 GPUs
I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcupti.so.10.1
E tensorflow/core/profiler/internal/gpu/cupti_tracer.cc:1408] function cupti_interface_->Subscribe( &subscriber_, (CUpti_CallbackFunc)ApiCallback, this)failed with error CUPTI_ERROR_NOT_INITIALIZED
E tensorflow/core/profiler/internal/gpu/cupti_tracer.cc:1447] function cupti_interface_->ActivityRegisterCallbacks( AllocCuptiActivityBuffer, FreeCuptiActivityBuffer)failed with error CUPTI_ERROR_NOT_INITIALIZED
E tensorflow/core/profiler/internal/gpu/cupti_tracer.cc:1430] function cupti_interface_->EnableCallback( 0 , subscriber_, CUPTI_CB_DOMAIN_DRIVER_API, cbid)failed with error CUPTI_ERROR_INVALID_PARAMETER`

I changed the  /etc/modprobe.d/nvidia-kernel-common.conf file as suggested and run the docker container as root-user. 
Does anyone have an idea what to try next?
