### ISSUE TITLE
Errors with tf.data.Dataset shape 

### ISSUE THREAD

**Issue by anirbankonar123** [tensorflow/tensorflow#35861]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.1
- Python version: 3.6
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory: no GPU

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior** "Error when checking input: expected input1 to have 4 dimensions, but got array with shape (96, 96, 1)" 

**Describe the expected behavior** tf.data.dataset size its [[90, 96, 96, 1], [90, 6]], Input shape of CNN Model is (None,96,96,1) - so this should not give error

**Code to reproduce the issue**
https://www.kaggle.com/anirbank/bengali-graphemes-starter-eda-basic-cnn-model

**Other info / logs**
Logs given in code: Input shape:
(None, 96, 96, 1)
tf.data.Dataset shape : [[90, 96, 96, 1], [90, 6]]

**Comment by ymodak** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.
 Thanks!

**Comment by anirbankonar123** [comment]
That is not correct, this has been raised as a bug earlier. It is not
something that I dnt know how to use. I have printed the tensor shapes,
everything is fine, but still I get the error msg.
