### ISSUE TITLE
ImportError: DLL load failed: The specified procedure could not be found. appears after an hour of usage

### ISSUE THREAD

**Issue by Hofmann-Max** [tensorflow/tensorflow#35865]
- OS Platform: Windows 10 Enterprise (10.0.17134)
- TensorFlow installed with: pip install tensorflow-cpu==2.1.0
- CPU: Intel(R) Core(TM) i5-6500
- GPU: Intel(R) HD Graphics 530 (i do not want to use GPU, this is just for completeness)
- Python version: 3.6
- Code used in PyCharm CommunityEdition 2019.3.1
- Anaconda, version 4.7.12

I had the Problem, that after upgrading to tensorflow 2.1.0 the `import tensorflow` statement would not work
After enough search i found, that i needed the Visual C++ Redistributable for 2015, 2017 and 2019, which i now have installed. After that, i was able to run `import tensorflow`, but after about an hour later, the statement failed again. 
The only change to my anaconda-environment was, that i installed opencv via `conda install opencv`, which should not change tensorflow

The Traceback:
  File "<stdin>", line 1, in <module>
  File "C:\Users\*\.conda\envs\sirenai\lib\site-packages\tensorflow\__init__.py", line 101, in <module>
            from tensorflow_core import *
  File "C:\Users\*\.conda\envs\sirenai\lib\site-packages\tensorflow_core\__init__.py", line 40, in 
            <module>
            from tensorflow.python.tools import module_util as _module_util
  File "C:\Users\*\.conda\envs\sirenai\lib\site-packages\tensorflow\__init__.py", line 50, in __getattr__
            module = self._load()
  File "C:\Users\*\.conda\envs\sirenai\lib\site-packages\tensorflow\__init__.py", line 44, in _load
            module = _importlib.import_module(self.__name__)
  File "C:\Users\*\.conda\envs\sirenai\lib\importlib\__init__.py", line 126, in import_module
            return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Users\*\.conda\envs\sirenai\lib\site-packages\tensorflow_core\python\__init__.py", line 64, 
            in <module>
            from tensorflow.core.framework.graph_pb2 import *
  File "C:\Users\*\.conda\envs\sirenai\lib\site-packages\tensorflow_core\core\framework
            \graph_pb2.py", line 7, in <module>
            from google.protobuf import descriptor as _descriptor
  File "C:\Users\*\.conda\envs\sirenai\lib\site-packages\google\protobuf\descriptor.py", line 47, in 
            <module>
            from google.protobuf.pyext import _message
ImportError: DLL load failed: The specified procedure could not be found.

**Comment by gadagashwini** [comment]
@Hofmann-Max,
Open ...\Lib\site-packages\tensorflow\python\_pywrap_tensorflow_internal.pyd use Dependency Walker, it will show you the 
DLL dependency tree, you will find which DLL cause the problem. You can then install the needed package version add some path to system variable.
Reference Issue : https://github.com/tensorflow/tensorflow/issues/28848
Dependency Walker link : http://www.dependencywalker.com/

**Comment by Hofmann-Max** [comment]
@gadagashwini 
Thank you for your response
This file does not exist in this folder. It only contains the Folder __pycache__ and the File __init__.py
__pycache__ itself only contains __init__.cpython-36.pyc

**Comment by gadagashwini** [comment]
@Hofmann-Max,
Try to uninstall the existing Tensorflow and Python and install freshly by creating virtual environment.
Below are the instructions to install Tensorflow 2.1 using PIP
#Install tensorflow using pip virtual env 
$pip install virtualenv
$virtualenv tf_2.1.0   # tf_2.1.0 is virtual env name
$source tf_2.1.0/bin/activate
tf_2.1.0 $ pip install tensorflow==2.1.0
tf_2.1.0 $ python
>>import tensorflow as tf
>>tf.__version__
2.1.0
Let us know if it helps. Thanks!

**Comment by Hofmann-Max** [comment]
I managed to work around the problem by upgrading Python from 3.6 to 3.7
I am not sure at all why this error occurs or why upgrading fixes the problem

Now with Python 3.7 it works fine
