### ISSUE TITLE
Failed to invoke the interpreter with error: Provided data count 602112 must match the required count 270000.

### ISSUE THREAD

**Issue by gerchicov-bp** [tensorflow/tensorflow#35864]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): iOS 12.0.1
- TensorFlow installed from (source or binary): CocoaPods
- TensorFlow version (or github SHA if from source): 
  - TensorFlowLiteC (2.1.0)
  - TensorFlowLiteSwift (2.1.0):
    - TensorFlowLiteC (= 2.1.0)

**Command used to run the converter or code if you’re using the Python API**

```
import os, cv2, re, random
import numpy as np
import pandas as pd
import tensorflow as tf
from keras.preprocessing.image import ImageDataGenerator
from keras.preprocessing.image import img_to_array, load_img
from keras import layers, models, optimizers
from keras import backend as K
from sklearn.model_selection import train_test_split
from tensorflow.python.keras import models, layers

img_width = 150
img_height = 150
TRAIN_DIR = './input/train/'
TEST_DIR = './input/test/'
train_images_dogs_cats = [TRAIN_DIR+i for i in os.listdir(TRAIN_DIR)] # use this for full dataset
test_images_dogs_cats = [TEST_DIR+i for i in os.listdir(TEST_DIR)]

def atoi(text):
	return int(text) if text.isdigit() else text

def natural_keys(text):
	return [ atoi(c) for c in re.split('(\d+)', text) ]
	
train_images_dogs_cats.sort(key=natural_keys)
train_images_dogs_cats = train_images_dogs_cats[0:1300] + train_images_dogs_cats[12500:12500 + 1300]

test_images_dogs_cats.sort(key=natural_keys)

def prepare_data(list_of_images):
	"""
	Returns two arrays: 
		x is an array of resized images
		y is an array of labels
	"""
	x = [] # images as arrays
	y = [] # labels
	
	for image in list_of_images:
		x.append(cv2.resize(cv2.imread(image), (img_width,img_height), interpolation=cv2.INTER_CUBIC))
	
	for i in list_of_images:
		if 'dog' in i:
			y.append(1)
		elif 'cat' in i:
			y.append(0)
		#else:
			#print('neither cat nor dog name present in images')
			
	return x, y
	
X, Y = prepare_data(train_images_dogs_cats)
print(K.image_data_format())

# First split the data in two sets, 80% for training, 20% for Val/Test)
X_train, X_val, Y_train, Y_val = train_test_split(X,Y, test_size=0.2, random_state=1)

nb_train_samples = len(X_train)
nb_validation_samples = len(X_val)
batch_size = 16

model = models.Sequential()

model.add(layers.Conv2D(32, (3, 3), input_shape=(img_width, img_height, 3)))
model.add(layers.Activation('relu'))
model.add(layers.MaxPooling2D(pool_size=(2, 2)))

model.add(layers.Conv2D(32, (3, 3)))
model.add(layers.Activation('relu'))
model.add(layers.MaxPooling2D(pool_size=(2, 2)))

model.add(layers.Conv2D(64, (3, 3)))
model.add(layers.Activation('relu'))
model.add(layers.MaxPooling2D(pool_size=(2, 2)))

model.add(layers.Flatten())
model.add(layers.Dense(64))
model.add(layers.Activation('relu'))
model.add(layers.Dropout(0.5))
model.add(layers.Dense(1))
model.add(layers.Activation('sigmoid'))

model.compile(loss='binary_crossentropy',
							optimizer='rmsprop',
							metrics=['accuracy'])



model.summary()

train_datagen = ImageDataGenerator(
	rescale=1. / 255,
	shear_range=0.2,
	zoom_range=0.2,
	horizontal_flip=True)

val_datagen = ImageDataGenerator(
	rescale=1. / 255,
	shear_range=0.2,
	zoom_range=0.2,
	horizontal_flip=True)
	
train_generator = train_datagen.flow(np.array(X_train), Y_train, batch_size=batch_size)
validation_generator = val_datagen.flow(np.array(X_val), Y_val, batch_size=batch_size)

history = model.fit_generator(
	train_generator, 
	steps_per_epoch=nb_train_samples // batch_size,
	epochs=30,
	validation_data=validation_generator,
	validation_steps=nb_validation_samples // batch_size
)

model.save_weights('model_wieghts.h5')
model.save('model_keras.h5')

X_test, Y_test = prepare_data(test_images_dogs_cats) #Y_test in this case will be []

test_datagen = ImageDataGenerator(rescale=1. / 255)

test_generator = val_datagen.flow(np.array(X_test), batch_size=batch_size)
prediction_probabilities = model.predict_generator(test_generator, verbose=1)

counter = range(1, len(test_images_dogs_cats) + 1)
solution = pd.DataFrame({"id": counter, "label":list(prediction_probabilities)})
cols = ['label']

for col in cols:
	solution[col] = solution[col].map(lambda x: str(x).lstrip('[').rstrip(']')).astype(float)

solution.to_csv("dogsVScats.csv", index = False)

# Convert the model.
converter = tf.lite.TFLiteConverter.from_keras_model(model)
tflite_model = converter.convert()
open("./model_from_keras.tflite", "wb").write(tflite_model)
```

**The output from the converter invocation**
Log from console:
```
Failed to invoke the interpreter with error: Provided data count 602112 must match the required count 270000.
```

**Also, please include a link to the saved model or GraphDef**

```
https://gofile.io/?c=nOBHAC
```

**Failure details**
I took an example for iOS.
Then I generated a model using this instruction (the modified script is above):
https://www.kaggle.com/sarvajna/dogs-vs-cats-keras-solution
Then I replaced the old .tflite file with the new one.
Result - the error with data size. Where and how to fix it

P.S. It seems I have the same/similar issue but for iOS:
https://github.com/tensorflow/tensorflow/issues/21602

**Comment by blyscuit** [comment]
I'm using this same tutorial and save the model with
```
converter = tf.lite.TFLiteConverter.from_keras_model(model_new)
tflite_model = converter.convert()
open("category_model.tflite", "wb").write(tflite_model)
```
and getting the same error
```
Failed to invoke the interpreter with error: Provided data count 602112 must match the required count 270000.
```

**Comment by blyscuit** [comment]
It seems the problem is with input buffer size. In `ModelDataHandler` I changed my 
```
// MARK: - Model Parameters

  let batchSize = 1
  let inputChannels = 3
  let inputWidth = 224
  let inputHeight = 224
```
to
```
// MARK: - Model Parameters

  let batchSize = 1
  let inputChannels = 3
  let inputWidth = 150 // this should match your training data
  let inputHeight = 150 // this should match your training data
```
and now working perfectly.

[https://github.com/tensorflow/tensorflow/issues/21602#issuecomment-414412800](url)

**Comment by srjoglekar246** [comment]
Looks like you found and fixed the issue :-).
Please re-open if still applies.

Thanks!

**Comment by AzinPoshtyar** [comment]
I'm trying to run [SSD ResNet50 V1 FPN 640x640][http://download.tensorflow.org/models/object_detection/tf2/20200711/ssd_resnet50_v1_fpn_640x640_coco17_tpu-8.tar.gz] on iOS. I've successfully converted the model to tflite; it's 208.2 MB.
I did edit ModelDataHandler.swift based on the model parameters:
`// MARK: Model parameters
  let batchSize = 1
  let inputChannels = 3
  let inputWidth = 640
  let inputHeight = 640

  // image mean and std for floating model, should be consistent with parameters used in model training (I didn't change any here)
  let imageMean: Float = 127.5
  let imageStd:  Float = 127.5
`

Once I try to run the model on iOS by following [https://github.com/tensorflow/examples/tree/master/lite/examples/object_detection/ios] this error is frequently printing:
**Failed to invoke the interpreter with error: Provided data count 1228800 must match the required count 3.**

Would you please help?

**Comment by srjoglekar246** [comment]
@AzinPoshtyar There seems to be a mis-match between the data you provide, and what the model expects. Its weird that the model expects only 3 bytes in the input; something seems to be off. As a sanity check, could you look at the `Test .tflite model` section [here](https://github.com/tensorflow/models/blob/master/research/object_detection/colab_tutorials/eager_few_shot_od_training_tflite.ipynb), and try to use it with your model in a Python script (on desktop)? You can also use some tool like Netron to check if the model is correct.

**Comment by manosh7n** [comment]
My issue is a bit like this. Can anyone tell me what I'm doing wrong? 
https://github.com/tensorflow/tensorflow/issues/46199

**Comment by DLP-ios** [comment]
Hi folks, me too also getting same like above my error is 

**Failed to invoke the interpreter with error: Provided data count 602112 must match the required count 1080000.**

in my xcode project can anyone help me
