### ISSUE TITLE
Linking error when building Tensorflow 2.1

### ISSUE THREAD

**Issue by DnPlas** [tensorflow/tensorflow#35867]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
Centos 7 (Docker image)
- TensorFlow installed from (source or binary):
Source
- TensorFlow version:
r2.1
- Python version:
3.6.8
- Bazel version (if compiling from source):
0.29.1 (installed using bazelisk)
- GCC/Compiler version (if compiling from source):
7.3.1 (installed via devtoolset-7)

**Describe the problem**
When building Tensorflow 2.1, the following linking error appears:

```
ERROR: /tmp/bazel/external/swig/BUILD.bazel:5:1: Linking of rule 
'@swig//:swig' failed (Exit 1)
bazel-out/host/bin/external/swig/_objs/swig/allocate.o:allocate.cxx:
function Allocate::~Allocate(): 
error: undefined reference to 'operator delete(void*, unsigned long)'
```

Seems like an incompatibility issue when building some third party components caused when looking for that symbol.

**Provide the exact sequence of commands / steps that you executed before running into the problem**

`$ docker run centos:7`

Then inside the container:
```
# yum-config-manager --enable rhel-server-rhscl-7-rpms -y && yum install devtoolset-7 -y
# export PATH=/opt/rh/devtoolset-7/root/usr/bin${PATH:+:${PATH}}
# export PCP_DIR=/opt/rh/devtoolset-7/root
# export PERL5LIB=/opt/rh/devtoolset-7/root//usr/lib64/perl5/vendor_perl:/opt/rh/devtoolset-7/root/usr/lib/perl5:/opt/rh/devtoolset-7/root//usr/share/perl5/vendor_perl${PERL5LIB:+:${PERL5LIB}}
# rpmlibdir=$(rpm --eval "%{_libdir}")
# if [ "$rpmlibdir" != "${rpmlibdir/lib64/}" ]; then
#       rpmlibdir32=":/opt/rh/devtoolset-7/root${rpmlibdir/lib64/lib}"
# fi
# export LD_LIBRARY_PATH=/opt/rh/devtoolset-7/root$rpmlibdir$rpmlibdir32${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}
# export LD_LIBRARY_PATH=/opt/rh/devtoolset-7/root$rpmlibdir$rpmlibdir32:/opt/rh/devtoolset-7/root$rpmlibdir/dyninst$rpmlibdir32/dyninst${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}
# pythonvers=2.7
# export PYTHONPATH=/opt/rh/devtoolset-7/root/usr/lib64/python$pythonvers/site-packages:/opt/rh/devtoolset-7/root/usr/lib/python$pythonvers/site-packages${PYTHONPATH:+:${PYTHONPATH}}
# export JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.222.b10-1.el7_7.x86_64
# git clone https://github.com/tensorflow/ && cd tensorflow && git checkout r2.1
# export OPTM=3
# export PYTHON_BIN_PATH=/usr/bin/python
# export USE_DEFAULT_PYTHON_LIB_PATH=1
# export CC_OPT_FLAGS="-march=${ARCH} -mtune=$TUNE"
# export TF_NEED_JEMALLOC=1
# export TF_NEED_KAFKA=0
# export TF_NEED_OPENCL_SYCL=0
# export TF_NEED_GCP=0
# export TF_NEED_HDFS=0
# export TF_NEED_S3=0
# export TF_ENABLE_XLA=1
# export TF_NEED_GDR=0
# export TF_NEED_VERBS=0
# export TF_NEED_OPENCL=0
# export TF_NEED_MPI=0
# export TF_NEED_TENSORRT=0
# export TF_SET_ANDROID_WORKSPACE=0
# export TF_DOWNLOAD_CLANG=0
# export TF_NEED_CUDA=0
# ./configure && bazel build --cxxopt=-D_GLIBCXX_USE_CXX11_ABI=0 //tensorflow/tools/pip_package:build_pip_package
```

**Any other info / logs**
Note this error message appears when building different components. Here are some examples:

```
ERROR: /tensorflow/tensorflow/compiler/mlir/tensorflow/BUILD:713:1: Linking of rule '//tensorflow/compiler/mlir/tensorflow:derived_attr_populator_gen' failed (Exit 1)
bazel-out/host/bin/external/llvm/_objs/tablegen/Main.o:Main.cpp:function llvm::cl::list<std::string, bool, llvm::cl::parser<std::string> >::~list(): error: undefined reference to 'operator delete(void*, unsigned long)'
```

```
ERROR: /tmp/bazel/external/com_google_protobuf/BUILD:406:1: Linking of rule '@com_google_protobuf//:protoc' failed (Exit 1)
bazel-out/host/bin/external/com_google_protobuf/_objs/protoc_lib/code_generator.o:code_generator.cc:function google::protobuf::compiler::ParseGeneratorParameter(std::string const&, std::vector<std::pair<std::string, std::string>, std::allocator<std::pair<std::string, std::string> > >*): error: undefined reference to 'std::__throw_out_of_range_fmt(char const*, ...)'
bazel-out/host/bin/external/com_google_protobuf/_objs/protoc_lib/command_line_interface.o:command_line_interface.cc:function google::protobuf::io::StringOutputStream::~StringOutputStream(): error: undefined reference to 'operator delete(void*, unsigned long)'
```

**Comment by DnPlas** [comment]
Update: 
I was able to build TF 2.1 using Bazel 0.26.1 with no issues. I'm not sure what differences v0.27.1 introduces, but at least for my configuration, 0.26.1 works. I haven't found the root cause, though.

**Comment by unrahul** [comment]
I was able to replicate this on my local as well.. are others seeing this as well?

**Comment by feihugis** [comment]
I met a similar problem on CentOS 7 with Bazel 1.2.1 and GCC 8.3.1. Here is the error message:
```
ERROR: /home/xxx/.cache/bazel/_bazel_xxx/26d8964cd405c0a736925fad9b93a973/external/swig/BUILD.bazel:5:1: Linking of rule '@swig//:swig' failed (Exit 1)
bazel-out/host/bin/external/swig/_objs/swig/allocate.o:allocate.cxx:function Allocate::~Allocate(): error: undefined reference to 'operator delete(void*, unsigned long)'
bazel-out/host/bin/external/swig/_objs/swig/contract.o:contract.cxx:function Contracts::~Contracts(): error: undefined reference to 'operator delete(void*, unsigned long)'
bazel-out/host/bin/external/swig/_objs/swig/lang.o:lang.cxx:function Language::~Language(): error: undefined reference to 'operator delete(void*, unsigned long)'
bazel-out/host/bin/external/swig/_objs/swig/module.o:module.cxx:function Swig_register_module(char const*, Language* (*)()) [clone .cold.0]: error: undefined reference to 'operator delete(void*, unsigned long)'
```

**Comment by claynerobison** [comment]
I also had this problem when building r2.1 and v2.1.0 in the https://github.com/tensorflow/tensorflow/blob/r2.1/tensorflow/tools/ci_build/Dockerfile.rbe.ubuntu16.04-manylinux2010 environment using both /dt8 and /dt7:

`ERROR: /root/.cache/bazel/_bazel_root/68a62076e91007a7908bc42a32e4cff9/external/flatbuffers/BUILD.bazel:99:1: Linking of rule '@flatbuffers//:flatc' failed (Exit 1)
bazel-out/host/bin/external/flatbuffers/_objs/flatc/cpp_generator.o:cpp_generator.cc:function std::basic_stringbuf<char, std::char_traits<char>, std::allocator<char> >::~basic_stringbuf(): error: undefined reference to 'operator delete(void*, unsigned long)'
...`

**Comment by feihugis** [comment]
The solution from @wdirons works for me : `BAZEL_LINKLIBS=-l%:libstdc++.a bazel build -c opt //tensorflow/tools/pip_package:build_pip_package `

**Comment by DnPlas** [comment]
Hi @feihugis, thanks for the workaround. Any clue why it doesn't get solved by adding "--linkopt=-lstdc++"? I tried that, but seems like failing. I will try your suggestion.

**Comment by feihugis** [comment]
> Hi @feihugis, thanks for the workaround. Any clue why it doesn't get solved by adding "--linkopt=-lstdc++"? I tried that, but seems like failing. I will try your suggestion.

I am not very clear about this. @wdirons Do you have any ideas?

**Comment by wdirons** [comment]
Before compiling TensorFlow, I had to compile Bazel and it was failing with the same error:

I found these related to the issue:
https://github.com/bazelbuild/bazel/issues/8652
https://github.com/bazelbuild/bazel/pull/8660
https://github.com/bazelbuild/bazel/issues/10327

They say to use `BAZEL_LINKOPTS=-static-libstdc++ BAZEL_LINKLIBS=-l%:libstdc++.a`, but I found just using BAZEL_LINKLIBS is enough.

**Comment by amahendrakar** [comment]
> I tried that, but seems like failing. I will try your suggestion.

@DnPlas,
Is this still an issue?

Could you please update TensorFlow to the latest stable version v2.4.1 and check if you are facing the same error. Thanks!

**Comment by DnPlas** [comment]
I have not tried with 2.4, but seems like the problem is more related to bazel than it is to Tensorflow. Using @wdirons workaround worked for me, and some other folks that referenced this issue.

**Comment by amahendrakar** [comment]
@DnPlas,
Thank you for the update. Can we please close this issue as it is resolved?

**Comment by georgepaw** [comment]
I'm posting here in case someone else encounters similar issue with centos 7 and Bazel 3.7.2 followed by when loading datasets:
```
"/home/external/tf_python_python3/lib64/python3.6/site-packages/numpy/lib/npyio.py", line 255, in __getitem__
    bytes = self.zip.open(key)
  File "/usr/lib64/python3.6/zipfile.py", line 1448, in open
    return ZipExtFile(zef_file, mode, zinfo, zd, True)
  File "/usr/lib64/python3.6/zipfile.py", line 781, in __init__
    self._decompressor = _get_decompressor(self._compress_type)
  File "/usr/lib64/python3.6/zipfile.py", line 701, in _get_decompressor
    return zlib.decompressobj(-15)
ValueError: Invalid initialization option
```

setting following fixed both of them:
```
TF_SYSTEM_LIBS=zlib,png
BAZEL_LINKLIBS=-lstdc+
```
