### ISSUE TITLE
Running fit on an tf.keras.Sequential with a Keras Sequence generator causes deadlock with use_multiprocessing

### ISSUE THREAD

**Issue by andrewstanfordjason** [tensorflow/tensorflow#35879]
> 
> == check python ===================================================
> python version: 3.7.4
> python branch: 
> python build version: ('default', 'Sep  7 2019 18:27:02')
> python compiler version: Clang 10.0.1 (clang-1001.0.46.4)
> python implementation: CPython
> 
> 
> == check os platform ===============================================
> os: Darwin
> os kernel version: Darwin Kernel Version 19.0.0: Wed Sep 25 20:18:50 PDT 2019; root:xnu-6153.11.26~2/RELEASE_X86_64
> os release version: 19.0.0
> os platform: Darwin-19.0.0-x86_64-i386-64bit
> linux distribution: ('', '', '')
> linux os distribution: ('', '', '')
> mac version: ('10.15', ('', '', ''), 'x86_64')
> uname: uname_result(system='Darwin', node='Andrews-MacBook.local', release='19.0.0', version='Darwin Kernel Version 19.0.0: Wed Sep 25 20:18:50 PDT 2019; root:xnu-6153.11.26~2/RELEASE_X86_64', machine='x86_64', processor='i386')
> architecture: ('64bit', '')
> machine: x86_64
> 
> 
> == are we in docker =============================================
> No
> 
> == compiler =====================================================
> xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
> 
> == check pips ===================================================
> numpy                1.17.4   
> protobuf             3.10.0   
> tensorflow           2.1.0    
> tensorflow-estimator 2.0.1    
> 
> == check for virtualenv =========================================
> True
> 
> == tensorflow import ============================================
> tf.version.VERSION = 2.1.0
> tf.version.GIT_VERSION = v2.0.0-rc2-26-g64c3d382ca
> tf.version.COMPILER_VERSION = 4.2.1 Compatible Apple LLVM 10.0.0 (clang-1000.11.45.5)
> 
> == env ==========================================================
> LD_LIBRARY_PATH is unset
> DYLD_LIBRARY_PATH is unset
> 
> == nvidia-smi ===================================================
> ./tf_env_collect.sh: line 147: nvidia-smi: command not found
> 
> == cuda libs  ===================================================
> 
> == tensorflow installed from info ==================
> Name: tensorflow
> Version: 2.1.0
> Summary: TensorFlow is an open source machine learning framework for everyone.
> Home-page: https://www.tensorflow.org/
> Author-email: packages@tensorflow.org
> License: Apache 2.0
> Location: /Users/andrew/.local/share/virtualenvs/lib_andrew_scratch--yvJ8pLH/lib/python3.7/site-packages
> Required-by: 
> 
> == python version  ==============================================
> (major, minor, micro, releaselevel, serial)
> (3, 7, 4, 'final', 0)
> 
> == bazel version  ===============================================
> 

**Describe the current behavior**
It seems all threads are waiting in a deadlock behaviour

**Describe the expected behavior**
To train the model

**Code to reproduce the issue**

```
from tensorflow.keras.utils import Sequence
import tensorflow as tf
import numpy as  np

class DataGenerator(Sequence):
    def __init__(self):
        self.batch_size = 32
        self.output_shape = (6, 12)

    def __len__(self):
        return 128

    def __getitem__(self, index):
        X = np.random.uniform(-1, 1, (self.batch_size, *self.output_shape))
        y = np.random.uniform(-1, 1, (self.batch_size, 1))
        return (X, y)

def build_model():
    model = tf.keras.Sequential(name='hello')
    model.add(tf.keras.layers.Flatten(input_shape=(6, 12)))
    model.add(tf.keras.layers.Dense(1, activation='sigmoid'))
    model.compile(optimizer=tf.keras.optimizers.Adam(),
                  loss=tf.keras.losses.MeanSquaredError())
    return model

if __name__== "__main__":

    gen = DataGenerator()
    val_gen = DataGenerator()

    model = build_model()
    model.fit(x = gen, 
        validation_data = val_gen,
        epochs = 8,
        workers = 4,
        use_multiprocessing = True,
        shuffle=True)

```

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by andrewstanfordjason** [comment]
[example.py.zip](https://github.com/tensorflow/tensorflow/files/4061814/example.py.zip)

**Comment by andrewstanfordjason** [comment]
I have found removing the line `validation_data = val_gen,` stops the deadlock

**Comment by gadagashwini** [comment]
@andrewstanfordjason, 
You can pass a Dataset instance as the validation_data argument in fit.
For more read [here](https://www.tensorflow.org/guide/keras/train_and_evaluate#using_a_validation_dataset). Thanks!

**Comment by andrewstanfordjason** [comment]
This is indeed my error for not fully reading the docs. It would be nice if the validation data took a generator as the x input does. I guess I can work around it by using evaluate between epochs. Thank you

**Comment by jvishnuvardhan** [comment]
I am closing this issue as it was resolved. Please feel free to reopen if the issue persists again. Thanks!

**Comment by dekromp** [comment]
Are there any plans to support `tf.keras.Sequence` instances as arguments for the `validation_data` argument in the future? It is kind of counterintuitive that it works for the `x` and `y` arguments but not for validation_data.

**Comment by andrewstanfordjason** [comment]
I have worked around this by using evaluate(). It's not ideal but as my data is generated it works.

**Comment by dekromp** [comment]
Yes, thanks. I saw your workaround and I am doing actually the same now.

**Comment by jostheim** [comment]
What is going on here? I wrote a lot of code using Sequence and it is not even deprecated with time given to port, it just stops working with no warning.  My code won't run at all now, and there is no guide to porting a Sequence to a DataSet (a Sequence is not a generator so it is not that easy).  This should not be closed... I am dropping back to 2.0.1.

**Comment by jessicasena** [comment]
This should not be closed. It is counterintuitive to use your X data as Sequence and your validation data as a tuple or Dataset. And, as jostheim said, there is no guide to porting Sequence to a Dataset, and it does not seem to be easy enough to justify the lack of a guide about how to do. If Sequence is not deprecated, why validation_data argument in fit() cannot support it?

**Comment by shijianjian** [comment]
Is anyone working on this or the ```keras.Sequence``` is not going to be working anymore?

**Comment by fshofmann** [comment]
For others who have issues porting Sequence to Dataset as others in this thread, `keras.Sequence` implements the `__iter__` method.  This can be easily passed to [`tf.data.Dataset.from_generator`](https://www.tensorflow.org/api_docs/python/tf/data/Dataset#from_generator) to create a new Dataset that contains all the elements of that Sequence. Dirty solution, that is imho not a good one, but it gets the job done.
