### ISSUE TITLE
cudart64_101.dll and nvcuda.dll not found

### ISSUE THREAD

**Issue by OThmanESGI** [tensorflow/tensorflow#35872]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): windows
- TensorFlow installed from (source or binary):source
- TensorFlow version:2
- Python version:3.7
- Installed using :pip
- CUDA/cuDNN version: none
- GPU model and memory:1696

**Describe the problem**

I m not able to install Tensorflow due to a problem with my Graphic Card
here's the error message : 
![CG](https://user-images.githubusercontent.com/48018890/72365775-2a244c80-36f9-11ea-9fe4-5c5d8e97c031.jpg)
![pb CG](https://user-images.githubusercontent.com/48018890/72365807-3c9e8600-36f9-11ea-8df3-bf0c4d5b6055.jpg)
tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'cudart64_101.dll'; dlerror: cudart64_101.dll not found
 I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.

**Comment by ymodak** [comment]
It's a warning message stating gpu setup is incorrect. TF is successfully installed on your machine however you won't be able to use GPU for computations and operations will be placed on CPU.

**Comment by OThmanESGI** [comment]
so I can use Tensorflow anyway ? if it's so, how please ? thank you

**Comment by ymodak** [comment]
As it says in the log `Ignore above cudart dlerror if you dont have gpu setup`.
You can safely ignore the logs and can use tf functionality.

**Comment by frogtd129** [comment]
if you have a gpu, and it is giving that error, what should you do

**Comment by ymodak** [comment]
If you have a GPU and still you are seeing this error it can occur due to many reasons. Most common reason is incompatible TF and Cuda version. Note TF version 2.0 supports cuda 10.0
Further also make sure you update appropriate cuda environment paths.
See  https://www.tensorflow.org/install/gpu#software_requirements
