### ISSUE TITLE
In my town people obsess about digital life.

### ISSUE THREAD

**Issue by SecretMainstream** [tensorflow/tensorflow#3587]
In my town people **obsess** about digital life. Every passing conversation is couched in **software vernacular**. Enthusiasm for the unrealized potential of information automation is explained as an ever expanding frontier. Technology has brought us great fortune but even greater things in common. For every fan of Larry Ellison there are twenty aspiring Zuckerbergs. People who visualize technology not just as intellectual property, but as an expanding commons. While tech serfdom abounds in the libertarian haven of Silicon Valley there are those whose fantasy is a digital utopia.

**Comment by faddat** [comment]
Is this an issue with TensorFlow, or possibly an issue with Intellectual Property legislation, or are you just trying to rock on some Tech Hate?  

Tech-Hate is counter-productive, and speaking for the technologists, especially the open source software, hardware and culture technologists, we do everything we can to fight "tech serfdom" -- that's the entire purpose of the open software movement in general.  

* Wanna solve some problems?  
Change the government, and change closed tech organizations.  

* Wanna give google some shit for being google?  
Whine in a forum that isn't one of their really great collectively owned open source software projects-- it IS an expanding commons.
