### ISSUE TITLE
Benchmark test failed on windows

### ISSUE THREAD

**Issue by fsx950223** [tensorflow/tensorflow#35884]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):Windows
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):binary
- TensorFlow version (use command below):tf-nightly
- Python version:3.7.5
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
File "\\?\C:\Users\RUNNER~1\AppData\Local\Temp\Bazel.runfiles_e847arzc\runfiles\__main__\tensorflow_addons\activations\rrelu_test.py", line 88, in benchmarkRreluOp
    self.run_op_benchmark(sess, result.op, min_iters=25)
  File "C:\hostedtoolcache\windows\Python\3.7.5\x64\lib\site-packages\tensorflow_core\python\platform\benchmark.py", line 389, in run_op_benchmark
    "throughput": mbs / median_delta
ZeroDivisionError: float division by zero

**Describe the expected behavior**
Same behavior as ubuntu
**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.
```python 
self.run_op_benchmark(sess, result.op, min_iters=25)
```

**Other info / logs**

https://github.com/tensorflow/addons/issues/839
It seems [```time.time()```](https://github.com/tensorflow/tensorflow/blob/590d6eef7e91a6a7392c8ffffb7b58f2e0c8bc6b/tensorflow/python/platform/benchmark.py#L294) cause the problem and ```timeit.default_timer()``` could fix the problem

**Comment by gunan** [comment]
Thanks for the analysis.
As long as we do not add a new external dependency, I am ok with the proposed solution.
