### ISSUE TITLE
Documentation on Tensorflow 2.1 with TPU

### ISSUE THREAD

**Issue by qo4on** [tensorflow/tensorflow#35894]
Are you going to update your TPU documentation https://cloud.google.com/tpu/docs/colabs with 2.1 release?

**Comment by lamberta** [comment]
Sorry, different product. There's a 'Send feedback' button on that page.

There's an updated TPU guide on tensorflow.org here: https://www.tensorflow.org/guide/tpu
And we're working to update a few of our long-running notebooks.
