### ISSUE TITLE
Deprecation notice for collection.Sequence in recurrent.py

### ISSUE THREAD

**Issue by ulf1** [tensorflow/tensorflow#35892]
@qlzh727

**Describe the current behavior**

When running unit tests the following deprecation note appears

```
lib/python3.7/site-packages/tensorflow_core/python/keras/layers/recurrent.py:808: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3,and in 3.9 it will stop working
  if (isinstance(inputs, collections.Sequence)
```

**Describe the expected behavior**

No deprecation notice

Line 808 needs a minor modification
```
...
  if (isinstance(inputs, collections.abc.Sequence)
...
```

See [python 3 docs](https://docs.python.org/3/library/collections.abc.html#collections.abc.Sequence)

**Comment by qlzh727** [comment]
Since we still have to support py2 within Google for now, we can't migrate to py3 only code yet.

**Comment by bjourne** [comment]
Looks like this has been fixed the proper way now:
```python
try:
  from collections import abc as collections_abc  # pylint: disable=g-import-not-at-top
except ImportError:  # For Python 2
  import collections as collections_abc  # pylint: disable=g-import-not-at-top
```
