### ISSUE TITLE
ADAM optimizer creates trainable variable

### ISSUE THREAD

**Issue by bdaskalov** [tensorflow/tensorflow#359]
ADAM optimizer crates two variables that are marked as trainable for no good reason (at least not apparent to me). 

I sent the following path but no one seems to have looked at it:
https://tensorflow-review.googlesource.com/#/c/1141/

**Comment by vrv** [comment]
Sorry, we'll look at it soon -- we are still working on our tooling to accept external contributions, so give us a little bit more time.

**Comment by vincentvanhoucke** [comment]
First successfully merged contribution I believe. Congrats! :)

**Comment by bdaskalov** [comment]
Thanks.
