### ISSUE TITLE
Dataset padded_batch does not work as documented

### ISSUE THREAD

**Issue by dhpollack** [tensorflow/tensorflow#35900]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): A little
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Google Colab (ubuntu-based)
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.1.0-rc1
- Python version:  3.7

**Describe the current behavior**

calling `Dataset.padded_batch([batch_size], [output_shape], padding_values=1)`  fails with the following error:

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-38-6fccac1ccecf> in <module>()
     20 ds_train = ds_train.padded_batch(BATCH_SIZE, padded_shapes)
     21 
---> 22 ds_test = ds_test.padded_batch(BATCH_SIZE, padded_shapes, padding_values=padded_values)

3 frames
/tensorflow-2.1.0/python3.6/tensorflow_core/python/data/util/nest.py in assert_shallow_structure(shallow_tree, input_tree, check_types)
    297       raise TypeError(
    298           "If shallow structure is a sequence, input must also be a sequence. "
--> 299           "Input has type: %s." % type(input_tree))
    300 
    301     if check_types and not isinstance(input_tree, type(shallow_tree)):

TypeError: If shallow structure is a sequence, input must also be a sequence. Input has type: <class 'int'>.
```

Note that this does not fail if one uses the default value of `None`

**Describe the expected behavior**

Should pad the data with the value in `padding_values`.  

Also, the error message could be friendly by telling me what type it expects. 

**Code to reproduce the issue**

```
import tensorflow as tf
import tensorflow_datasets as tfds

BATCH_SIZE = 64

ds, ds_info = tfds.load("imdb_reviews/subwords8k", with_info=True, as_supervised=True)
ds_train, ds_test = ds["train"], ds["test"]

output_shapes_train = tf.compat.v1.data.get_output_shapes(ds_train)
padded_shapes = output_shapes_train  # (TensorShape([None]), TensorShape([]))
padded_values = -1

ds_train = ds_train.padded_batch(BATCH_SIZE, padded_shapes)  # does not fail here
ds_test = ds_test.padded_batch(BATCH_SIZE, padded_shapes, padding_values=padded_values)  # but does fail here
```

**Other info / logs**
https://www.tensorflow.org/api_docs/python/tf/data/Dataset?version=stable#padded_batch

Documentation seems pretty clear that the second part should work.

**Comment by oanush** [comment]
@dhpollack ,
Can you please provide complete code? When tried executing given code I got error log `NameError: name 'output_shapes_train' is not defined`,find [gist of colab](https://colab.sandbox.google.com/gist/oanush/a35082df991ff743ad242ff1a6393ead/35900.ipynb) for reference.Thanks!

**Comment by dhpollack** [comment]
@oanush sorry about that.  I forgot about the line `output_shapes_train = tf.compat.v1.data.get_output_shapes(ds_train)`, but edited the above code with it.  

I was playing with the code on colab and you can see the notebook [here](https://colab.research.google.com/drive/12cUqrvcoBDCCB7EYg5M8AiiA4VmrplVy)

**Comment by dhpollack** [comment]
I ran the code on your gist with the additional line and got the error that I've described above.  On my notebook I was using tf 2.1.0-rc1 rather than 2.2 in your gist and get the same result.

**Comment by oanush** [comment]
Issue replicating,thanks!

**Comment by jsimsa** [comment]
The structure of `padding_values` needs to match the structure of your dataset elements (so that you can specify different padding values for different structure components).

The [documentation](https://www.tensorflow.org/api_docs/python/tf/data/Dataset?version=stable#padded_batch) calls this out, including an example of a dataset whose elements are tuples.

**Comment by dhpollack** [comment]
@jsimsa the documentation is at best unclear. If I want to pad my tensor in all dimensions with -1 then why can't I use a simple integer? This seems like the most practical case and it isn't clear to me how to do this. I'm willing to admit this might not be a bug but in that case it's a feature request to allow for simple types to be propagated logically.

**Comment by jsimsa** [comment]
You can do the following:

```
ds = tf.data.Dataset.from_tensors((0.0, 1))
padding_values = tf.nest.map_structure(lambda _: -1, ds.element_spec)
print(padding_values) # prints (-1, -1)
```

**Comment by jsimsa** [comment]
The feature you are requesting seems reasonable and would make a good candidate for an external contribution. If you create a feature request, please cc me on it so that I can tag it as contributions welcome.

**Comment by dhpollack** [comment]
Ok, still seems unintuitive but that's a very helpful answer. I'll give it a shot. Thanks for clearing that up for me. 👍🏼

**Comment by dsantiago** [comment]
Dude this function `padded_batch` is horrible... Must be rethinked in my point of view
