### ISSUE TITLE
 How to use python code about  the mnist  to  build the android apk 

### ISSUE THREAD

**Issue by zwb88008** [tensorflow/tensorflow#3591]
just as the title said .
I just want to come true the mnist  on the android like the tensorflow android_demo
now I just know how to build the model with python
and what I should do the next.

**Comment by tobegit3hub** [comment]
@zwb88008 Are you trying to find this https://github.com/miyosuda/TensorFlowAndroidMNIST ?

TensorFlowAndroidMNIST is the app to run directly on you Android, just like `android_demo`. Python seems not to be recommended to integrated with Android/Java application and I hope this could help.

**Comment by zwb88008** [comment]
@tobegit3hub thank you very much . it is all I want to find.

**Comment by tobegit3hub** [comment]
You're so welcome. Feel free to close the issue and we're looking forward to any good product about TensorFlow 😃

**Comment by drpngx** [comment]
Thanks @tobegit3hub :)
