### ISSUE TITLE
Compilation of TF2.1 with CUDA and TensorRT fails on Linux 

### ISSUE THREAD

**Issue by feranick** [tensorflow/tensorflow#35917]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: No
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below): 2.1.0
- Python version: 3.6.8
- Bazel version (if compiling from source): 0.29.1
- GCC/Compiler version (if compiling from source): GCC 7.4.0
- CUDA/cuDNN version: 10.1,10.2 CuDNN 7
- GPU model and memory: NVidia GTX 1080 Ti
- TensorRT: version 6 or 7.

**Describe the current behavior**
Compiling from source, as indicated in the official tensorflow manual, compilation fails, with the error listed in the log below.
**Describe the expected behavior**
Compilation should successfully complete

**Code to reproduce the issue**
No code needed. After a checkout of the current v.2.1.0, configuration is carried out with no changes from default (other than enabling CUDA). 

**Other info / logs**
Log: see attached log.txt
[log.txt](https://github.com/tensorflow/tensorflow/files/4068010/log.txt)

**Comment by gadagashwini** [comment]
@feranick,
Provide the exact sequence of commands / steps that you executed before running into the problem. Thanks!

**Comment by feranick** [comment]
Step to reproduce:
`git clone https://github.com/tensorflow/tensorflow.git`
`cd tensorflow`
`git checkout v2.1.0`
`./configure`
(followed all the steps. Everything in default, besides activating CUDA support with TensorRT)
`bazel build --config=opt --config=cuda --config=v2 --verbose_failures --verbose_explanations //tensorflow/tools/pip_package:build_pip_package`

**Comment by feranick** [comment]
Update: Compilation is successful is TensorRT support is disabled (during the `./configure' step). 

However, tensorflow lite seems to have issues. When I run my code:

   `converter = tf.lite.TFLiteConverter.from_keras_model(model)  
    converter.optimizations = [tf.lite.Optimize.OPTIMIZE_FOR_LATENCY]
    converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
    converter.inference_input_type = tf.float32
    converter.inference_output_type = tf.uint8
    converter.representative_dataset = representative_dataset_gen
    tflite_quant_model = converter.convert()`

I get this error: 
` tflite_quant_model = converter.convert()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/lite/python/lite.py", line 469, in convert
    self.experimental_new_quantizer)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/lite/python/lite.py", line 240, in _calibrate_quantize_model
    calibrate_quantize = _calibrator.Calibrator(result)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/lite/python/optimize/calibrator.py", line 53, in __init__
    raise ValueError("Failed to parse the model: %s." % e)
ValueError: Failed to parse the model: /usr/local/lib/python3.6/dist-packages/tensorflow_core/lite/python/optimize/_tensorflow_lite_wrap_calibration_wrapper.so: undefined symbol: _ZTIN10tensorflow6DeviceE. `

**Comment by feranick** [comment]
The issue, as hinted from the log, may be related to the fact that TF2.1.0 requires bazel > 0.27 (compared to TF2.0.0 which required version <=0.26.1). Starting from bazel 0.27 and later, the Python toolchain now enforces that targets analyzed as PY2 and PY3 run under a Python 2 and Python 3 interpreter, respectively. Since the issue at play here seems to be related with a TF2 wrapper for TensorRT which is a python2 program, while the rest of the compilation proceeds in Python 3 which seems no longer allowed with bazel 0.27 and later. Therefore, TF2.0.0 can be compiled, but not TF2.1.0.

The wrapper in question is tensorflow/python/keras/api:keras_python_api_gen_compat_v2

**Comment by feranick** [comment]
I updated the bug report to highlight that the issues is present for any recent version of CUDA (10.1, 10.2).

**Comment by vistart** [comment]
> I updated the bug report to highlight that the issues is present for any recent version of CUDA (10.1, 10.2).

Error(s) occur in the following environments:
- Ubuntu 18.04.3 LTS x64
- Python 3.6
- CUDA 10.0/10.1/10.2, cudnn 7.6.5.32, nccl 2.5.6, TensorRT 6.0.1(cuda10.1)/7.0.0(cuda10.0/10.2)

(The following three archives contain compilation logs. Please untar them to read)
[tf2.1_py36_cuda10.0.tar.gz](https://github.com/tensorflow/tensorflow/files/4095816/tf2.1_py36_cuda10.0.tar.gz)
[tf2.1_py36_cuda10.1.tar.gz](https://github.com/tensorflow/tensorflow/files/4095815/tf2.1_py36_cuda10.1.tar.gz)
[tf2.1_py36_cuda10.2.tar.gz](https://github.com/tensorflow/tensorflow/files/4095817/tf2.1_py36_cuda10.2.tar.gz)

If compiled for Python 2.7, there will be no problems.

**Comment by feranick** [comment]
I no longer have issues with TF 2.2. This bug should be closed.

**Comment by feranick** [comment]
This is no longer an issue, so it should be closed.
