### ISSUE TITLE
Issue with the Interpreter on Android 

### ISSUE THREAD

**Issue by loreProgetto** [tensorflow/tensorflow#35910]
I've to files of the same model that contains the same bytes. I'm trying to initialize the interpreter with both of them, but only with one works. I attach below the two files, only the indentation  seems different but the row bytes at the inside are the same. The first file was created in python saving the converted model, the second was created passing the raw bytes throw the network an storing them in a new file in kotlin
[Archive.zip](https://github.com/tensorflow/tensorflow/files/4067466/Archive.zip)

**Comment by gadagashwini** [comment]
@loreProgetto,
Please fill the issue [template](https://github.com/tensorflow/tensorflow/issues/new/choose) to analyse the issue . Thanks!

**Comment by gadagashwini** [comment]
@loreProgetto, Please fill the issue Template. Thanks

**Comment by gadagashwini** [comment]
@loreProgetto, Please take a look at [Android quickstart](https://www.tensorflow.org/lite/guide/android) Tensorflow doc. Thanks!

**Comment by srjoglekar246** [comment]
@loreProgetto What are you trying to do? You can just initialize two interpreters with the same model file, instead of having two different files?
The models indeed seem similar, so I am not sure whats going wrong.
Could you paste your code snippet?

**Comment by gadagashwini** [comment]
@loreProgetto, Any update!

**Comment by gadagashwini** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
