### ISSUE TITLE
Install Tensorflow 1.15 on CUDA 10.2 and cudnn 7.6

### ISSUE THREAD

**Issue by craterkamath** [tensorflow/tensorflow#35926]
**System information**
- OS Platform and Distribution: **Linux Ubuntu 16.04**
- TensorFlow installed from (source or binary): **Binary**
- TensorFlow version: **1.15**
- Python version: **3.6**
- Installed using virtualenv? pip? conda?: **Conda**
- CUDA/cuDNN version: CUDA 10.2 and cuDNN 7.6
- GPU model and memory: Tesla K80 

**Describe the problem**

I have an exisiting code base that uses Tensorflow 1.15. I want to train my model on Azure Instance that uses Tesla K80. I've also installed CUDA and cuDNN versions mentioned above, globally as well as through anaconda. I want to install  the specific version of the tensorflow, is this possible? Can I get prebuilt-binaries for the same?

Initially I tried installing through **conda install tensorflow-gpu**, I get the following error while running my script.

`Loaded runtime CuDNN library: 7605 (compatibility version 7600) but source was compiled with 7102`

**Any other info / logs**
`System info:
--------------------------------------------------------------------------------
__Time Stamp__
2020-01-16 06:18:49.664813

__Hardware Information__
Machine                                       : x86_64
CPU Name                                      : haswell
CPU count                                     : 24
CFS restrictions                              : None
CPU Features                                  :
64bit aes avx avx2 bmi bmi2 cmov cx16 f16c fma fsgsbase invpcid lzcnt mmx movbe
pclmul popcnt rdrnd sahf sse sse2 sse3 sse4.1 sse4.2 ssse3 xsave xsaveopt

__OS Information__
Platform                                      : Linux-4.15.0-1066-azure-x86_64-with-debian-stretch-sid
Release                                       : 4.15.0-1066-azure
System Name                                   : Linux
Version                                       : #71-Ubuntu SMP Thu Dec 12 20:35:32 UTC 2019
OS specific info                              : debianstretch/sid
glibc info                                    : glibc 2.9

__Python Information__
Python Compiler                               : GCC 7.3.0
Python Implementation                         : CPython
Python Version                                : 3.6.10
Python Locale                                 : en_US UTF-8

__LLVM information__
LLVM version                                  : 8.0.0

__CUDA Information__
Found 4 CUDA devices
id 0            b'Tesla K80'                              [SUPPORTED]
                      compute capability: 3.7
                           pci device id: 0
                              pci bus id: 0
id 1            b'Tesla K80'                              [SUPPORTED]
                      compute capability: 3.7
                           pci device id: 0
                              pci bus id: 0
id 2            b'Tesla K80'                              [SUPPORTED]
                      compute capability: 3.7
                           pci device id: 0
                              pci bus id: 0
id 3            b'Tesla K80'                              [SUPPORTED]
                      compute capability: 3.7
                           pci device id: 0
                              pci bus id: 0
Summary:
        4/4 devices are supported
CUDA driver version                           : 10020
CUDA libraries:
Finding cublas from Conda environment
        named  libcublas.so.10.2.2.89
        trying to open library...       ok
Finding cusparse from Conda environment
        named  libcusparse.so.10.3.1.89
        trying to open library...       ok
Finding cufft from Conda environment
        named  libcufft.so.10.1.2.89
        trying to open library...       ok
Finding curand from Conda environment
        named  libcurand.so.10.1.2.89
        trying to open library...       ok
Finding nvvm from Conda environment
        named  libnvvm.so.3.3.0
        trying to open library...       ok
Finding libdevice from Conda environment
        searching for compute_20...     ok
        searching for compute_30...     ok
        searching for compute_35...     ok
        searching for compute_50...     ok

__ROC Information__
ROC available                                 : False
Error initialising ROC due to                 : No ROC toolchains found.
No HSA Agents found, encountered exception when searching:
Error at driver init:
NUMBA_HSA_DRIVER /opt/rocm/lib/libhsa-runtime64.so is not a valid file path.  Note it must be a filepath of the .so/.dll/.dylib or the driver:

__SVML Information__
SVML state, config.USING_SVML                 : False
SVML library found and loaded                 : False
llvmlite using SVML patched LLVM              : True
SVML operational                              : False

__Threading Layer Information__
TBB Threading layer available                 : True
OpenMP Threading layer available              : False
+--> Disabled due to                          : Unknown import problem.
Workqueue Threading layer available           : True

__Numba Environment Variable Information__
None set.

__Conda Information__
conda_build_version                           : 3.18.9
conda_env_version                             : 4.8.1
platform                                      : linux-64
python_version                                : 3.7.4.final.0
root_writable                                 : True

__Current Conda Env__
_libgcc_mutex             0.1                        main
absl-py                   0.9.0                    pypi_0    pypi
astor                     0.8.1                    pypi_0    pypi
ca-certificates           2019.11.27                    0    anaconda
certifi                   2019.11.28               py36_0    anaconda
cudatoolkit               10.2.89              hfd86e86_0    anaconda
cudnn                     7.6.5                cuda10.2_0    anaconda
gast                      0.2.2                    pypi_0    pypi
google-pasta              0.1.8                    pypi_0    pypi
grpcio                    1.26.0                   pypi_0    pypi
h5py                      2.10.0                   pypi_0    pypi
keras-applications        1.0.8                    pypi_0    pypi
keras-preprocessing       1.1.0                    pypi_0    pypi
ld_impl_linux-64          2.33.1               h53a641e_7
libedit                   3.1.20181209         hc058e9b_0
libffi                    3.2.1                hd88cf55_4
libgcc-ng                 9.1.0                hdf63c60_0
libstdcxx-ng              9.1.0                hdf63c60_0
llvmlite                  0.31.0                   pypi_0    pypi
markdown                  3.1.1                    pypi_0    pypi
ncurses                   6.1                  he6710b0_1
numba                     0.47.0                   pypi_0    pypi
numpy                     1.18.1                   pypi_0    pypi
openssl                   1.1.1                h7b6447c_0    anaconda
opt-einsum                3.1.0                    pypi_0    pypi
pip                       19.3.1                   py36_0
protobuf                  3.11.2                   pypi_0    pypi
python                    3.6.10               h0371630_0
readline                  7.0                  h7b6447c_5
setuptools                44.0.0                   py36_0
six                       1.14.0                   pypi_0    pypi
sqlite                    3.30.1               h7b6447c_0
tensorboard               1.15.0                   pypi_0    pypi
tensorflow-estimator      1.15.1                   pypi_0    pypi
termcolor                 1.1.0                    pypi_0    pypi
tk                        8.6.8                hbc83047_0
werkzeug                  0.16.0                   pypi_0    pypi
wheel                     0.33.6                   py36_0
wrapt                     1.11.2                   pypi_0    pypi
xz                        5.2.4                h14c3975_4
zlib                      1.2.11               h7b6447c_3
--------------------------------------------------------------------------------`

**Comment by gadagashwini** [comment]
@craterkamath, Looks like multiple cuDNN versions installed on instance.
Please follow the instructions mentioned [here](https://www.tensorflow.org/install/gpu).
Download the cuDNN 7.6.5 from nvidia website https://developer.nvidia.com/rdp/cudnn-archive 
and add it to your LD_LIBRARY_PATH.
Thanks!

**Comment by mihaimaruseac** [comment]
TF 1.15 was compiled against CUDA 10.0

For other versions of CUDA you have to compile from source.

**Comment by gadagashwini** [comment]
@craterkamath, Is this still an issue!

**Comment by craterkamath** [comment]
@gadagashwini  The issue is resolved. I installed CUDA 9.x for which the GPU had support. I think I will close this now.

**Comment by IsaacPatole** [comment]
Tesla K80 doesnt have support for cuda 10.2 is that what you mean?
