### ISSUE TITLE
Here is a list of operators for which you will need custom implementations: BatchMatMul, Erf

### ISSUE THREAD

**Issue by ChiuHsin** [tensorflow/tensorflow#35923]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): windows10
- TensorFlow installed from (source or binary): binary
- TensorFlow version (or github SHA if from source): tf-nightly 1.15

**Command used to run the converter or code if you’re using the Python API**

    input_arrays = ["inputs/input_ids", "inputs/segment_ids", "inputs/input_mask"]
    output_arrays = ["loss/prob"]
    converter = tf.lite.TFLiteConverter.from_frozen_graph(graph_def_file, input_arrays, output_arrays)
    # Weight quantization
    converter.optimizations = [tf.lite.Optimize.OPTIMIZE_FOR_SIZE]
    tflite_quant_model = converter.convert()
    tflite_model = converter.convert()

**The output from the converter invocation**

```
Some of the operators in the model are not supported by the standard TensorFlow Lite runtime. If those are native TensorFlow operators, you might be able to use the extended runtime by passing --enable_select_tf_ops, or by setting target_ops=TFLITE_BUILTINS,SELECT_TF_OPS when calling tf.lite.TFLiteConverter(). Otherwise, if you have a custom implementation for them you can disable this error with --allow_custom_ops, or by setting allow_custom_ops=True when calling tf.lite.TFLiteConverter(). Here is a list of builtin operators you are using: ADD, CAST, FULLY_CONNECTED, GATHER, MEAN, MUL, ONE_HOT, PACK, RESHAPE, RSQRT, SLICE, SOFTMAX, SQUARED_DIFFERENCE, SQUEEZE, STRIDED_SLICE, SUB, TANH, TRANSPOSE. Here is a list of operators for which you will need custom implementations: BatchMatMul, Erf.
```

I got the error, then I add  "converter.allow_custom_ops = True".  It's success.
But when i use the .lite model to interpreter, I got the new error:

```
RuntimeError: Encountered unresolved custom op: Erf.Node number 191 (Erf) failed to prepare.
```

Please help me! Thanks

**Comment by gargn** [comment]
You will need to implement `Erf` as a custom operator because it is not supported in TensorFlow Lite. There is some instruction [here](https://www.tensorflow.org/lite/guide/ops_custom).

**Comment by ymodak** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Comment by TianHongZXY** [comment]
Does BatMatMul is supported in TensorFlow Lite? I encountered this problem too using TF1.15

**Comment by YC-wind** [comment]
Does **erf** is supported in TensorFlow Lite? I encountered this problem too using TF1.14

**Comment by asimsultan** [comment]
Has any done any custom implementation of this: 
RuntimeError: Encountered unresolved custom op: Erf.Node number 97 (Erf) failed to prepare.

**Comment by will-rice** [comment]
Is there a specific reason the erf operator isn't supported or is it just because no one has contributed it?
