### ISSUE TITLE
tf.cast on native python float to dtype=tf.float64 leads to loss of precision

### ISSUE THREAD

**Issue by st--** [tensorflow/tensorflow#35938]
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): no
- OS Platform and Distribution: Linux Ubuntu 18.04
- TensorFlow installed from (source or binary): binary (pip install)
- TensorFlow version (use command below): v2.1.0-rc2-17-ge5bf8de 2.1.0, v2.0.0-rc2-26-g64c3d38 2.0.0
- Python version: 3.7

**Describe the current behavior**

`tf.cast()` on a python float (e.g, a literal float constant, not a numpy float/array type) does an implicit conversion to the TensorFlow default dtype tf.float32, which can result in loss of precision when intending to cast to tf.float64:
```python
>>> tf.cast(0.2, tf.float64)
<tf.Tensor: id=37, shape=(), dtype=float64, numpy=0.20000000298023224>
```

**Describe the expected behavior**

```python
>>> tf.cast(0.2, tf.float64)
<tf.Tensor: id=37, shape=(), dtype=float64, numpy=0.2>
```

**Code to reproduce the issue**
See above.

**Other info / logs**
This was discovered as a bug in GPflow, which we built a work-around for in https://github.com/GPflow/GPflow/pull/1211 - but this is a pervading issue, and it would be good to fix this upstream instead of having to write and use a `gpflow.cast()` everywhere just to work around having potentially passed in a python float.

**Comment by st--** [comment]
The simple workaround would be to add
```python
    if not tf.is_tensor(value):
        return tf.convert_to_tensor(value, dtype)
```
to the beginning of the definition of `tf.cast()`.

This is related to tensorflow#26033 - not having to support our own "default dtype" implementation would remove the need for a lot of the calls to tf.cast.

**Comment by yongtang** [comment]
Added PR #35961 for the fix.
