### ISSUE TITLE
No implementation found for long org.tensorflow.lite.NativeInterpreterWrapper.createErrorReporter(int)

### ISSUE THREAD

**Issue by daihuidai** [tensorflow/tensorflow#35931]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): ,macos
- TensorFlow installed from (source or binary): source

I have successfully compiled AAR through bazel and tensorflow source code:
**1.14-tensorflow-lite-with-select-tf-ops.aar** and **1.15-tensorflow-lite-with-select-tf-ops.aar**

**What i want to do:**
Since my tflite model lacks the **RandomUniform** operator, I compiled and generated the AAR.Then I followed the official tips from tensorflow to introduce AAR dependencies in Android Studio.
![image](https://user-images.githubusercontent.com/43409147/72513097-ae0c3f00-3887-11ea-80cd-d0cf4b4d6818.png)
No error was reported during synchronization, but an error occurred when running the .kt file.
**As follows, I get an error when I generate the interpreter：**
![image](https://user-images.githubusercontent.com/43409147/72515495-f5e09580-388a-11ea-8854-aac284518626.png)

**My error message is as follows**

> 01/16 17:41:17: Launching 'MainActivity' on Pixel 2 API 29.
$ adb shell am start -n "com.example.test_aar2/com.example.test_aar2.MainActivity" -a android.intent.action.MAIN -c android.intent.category.LAUNCHER
Waiting for process to come online...
Connected to process 4911 on device 'emulator-5554'.
Capturing and displaying logcat messages from application. This behavior can be disabled in the "Logcat output" section of the "Debugger" settings page.
W/RenderThread: type=1400 audit(0.0:123): avc: denied { write } for name="property_service" dev="tmpfs" ino=6939 scontext=u:r:untrusted_app:s0:c118,c256,c512,c768 tcontext=u:object_r:property_socket:s0 tclass=sock_file permissive=0 app=com.example.test_aar2
D/libEGL: Emulator has host GPU support, qemu.gles is set to 1.
W/libc: Unable to set property "qemu.gles" to "1": connection failed; errno=13 (Permission denied)
D/libEGL: loaded /vendor/lib64/egl/libEGL_emulation.so
D/libEGL: loaded /vendor/lib64/egl/libGLESv1_CM_emulation.so
D/libEGL: loaded /vendor/lib64/egl/libGLESv2_emulation.so
W/ample.test_aar: Accessing hidden method Landroid/view/View;->computeFitSystemWindows(Landroid/graphics/Rect;Landroid/graphics/Rect;)Z (greylist, reflection, allowed)
W/ample.test_aar: Accessing hidden method Landroid/view/ViewGroup;->makeOptionalFitsSystemWindows()V (greylist, reflection, allowed)
D/: HostConnection::get() New Host Connection established 0x705aa57140c0, tid 4942
D/: HostComposition ext ANDROID_EMU_CHECKSUM_HELPER_v1 ANDROID_EMU_native_sync_v2 ANDROID_EMU_native_sync_v3 ANDROID_EMU_native_sync_v4 ANDROID_EMU_dma_v1 ANDROID_EMU_direct_mem ANDROID_EMU_host_composition_v1 ANDROID_EMU_host_composition_v2 ANDROID_EMU_vulkan ANDROID_EMU_deferred_vulkan_commands ANDROID_EMU_vulkan_create_resources_with_requirements ANDROID_EMU_async_unmap_buffer GL_OES_EGL_image_external_essl3 GL_OES_vertex_array_object GL_KHR_texture_compression_astc_ldr ANDROID_EMU_gles_max_version_3_1 
W/OpenGLRenderer: Failed to choose config with EGL_SWAP_BEHAVIOR_PRESERVED, retrying without...
D/eglCodecCommon: setVertexArrayObject: set vao to 0 (0) 0 0
D/EGL_emulation: eglCreateContext: 0x705aa5714340: maj 3 min 1 rcv 4
D/EGL_emulation: eglMakeCurrent: 0x705aa5714340: ver 3 1 (tinfo 0x705aa5814400)
E/eglCodecCommon: glUtilsParamSize: unknow param 0x000082da
    glUtilsParamSize: unknow param 0x000082da
W/Gralloc3: mapper 3.x is not supported
D/: createUnique: call
    HostConnection::get() New Host Connection established 0x705aa57145c0, tid 4942
D/: HostComposition ext ANDROID_EMU_CHECKSUM_HELPER_v1 ANDROID_EMU_native_sync_v2 ANDROID_EMU_native_sync_v3 ANDROID_EMU_native_sync_v4 ANDROID_EMU_dma_v1 ANDROID_EMU_direct_mem ANDROID_EMU_host_composition_v1 ANDROID_EMU_host_composition_v2 ANDROID_EMU_vulkan ANDROID_EMU_deferred_vulkan_commands ANDROID_EMU_vulkan_create_resources_with_requirements ANDROID_EMU_async_unmap_buffer GL_OES_EGL_image_external_essl3 GL_OES_vertex_array_object GL_KHR_texture_compression_astc_ldr ANDROID_EMU_gles_max_version_3_1 
D/eglCodecCommon: allocate: Ask for block of size 0x1000
    allocate: ioctl allocate returned offset 0x3ff708000 size 0x2000
D/EGL_emulation: eglMakeCurrent: 0x705aa5714340: ver 3 1 (tinfo 0x705aa5814400)
D/eglCodecCommon: setVertexArrayObject: set vao to 0 (0) 1 0
W/System.err: TensorFlowLite: failed to load native library: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.example.test_aar2-GJboUyCuRGe7EMGh-GZalA==/base.apk"],nativeLibraryDirectories=[/data/app/com.example.test_aar2-GJboUyCuRGe7EMGh-GZalA==/lib/x86_64, /system/lib64, /system/product/lib64]]] couldn't find "libtensorflowlite_jni.so"
W/System.err: TensorFlowLite: failed to load native library: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.example.test_aar2-GJboUyCuRGe7EMGh-GZalA==/base.apk"],nativeLibraryDirectories=[/data/app/com.example.test_aar2-GJboUyCuRGe7EMGh-GZalA==/lib/x86_64, /system/lib64, /system/product/lib64]]] couldn't find "libtensorflowlite_jni.so"
E/ample.test_aar: No implementation found for long org.tensorflow.lite.NativeInterpreterWrapper.createErrorReporter(int) (tried Java_org_tensorflow_lite_NativeInterpreterWrapper_createErrorReporter and Java_org_tensorflow_lite_NativeInterpreterWrapper_createErrorReporter__I)
D/AndroidRuntime: Shutting down VM
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.test_aar2, PID: 4911
    java.lang.UnsatisfiedLinkError: No implementation found for long org.tensorflow.lite.NativeInterpreterWrapper.createErrorReporter(int) (tried Java_org_tensorflow_lite_NativeInterpreterWrapper_createErrorReporter and Java_org_tensorflow_lite_NativeInterpreterWrapper_createErrorReporter__I)
        at org.tensorflow.lite.NativeInterpreterWrapper.createErrorReporter(Native Method)
        at org.tensorflow.lite.NativeInterpreterWrapper.<init>(NativeInterpreterWrapper.java:58)
        at org.tensorflow.lite.Interpreter.<init>(Interpreter.java:224)
        at com.example.test_aar2.MainActivity.action(MainActivity.kt:47)
        at com.example.test_aar2.MainActivity.access$action(MainActivity.kt:23)
        at com.example.test_aar2.MainActivity$onCreate$1.onClick(MainActivity.kt:30)
        at android.view.View.performClick(View.java:7140)
        at android.view.View.performClickInternal(View.java:7117)
        at android.view.View.access$3500(View.java:801)
        at android.view.View$PerformClick.run(View.java:27351)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
Process 4911 terminated.

**Then I introduced two dependencies at the same time according to the official tips of tensorflow：**
![image](https://user-images.githubusercontent.com/43409147/72513782-7b167b00-3888-11ea-97e2-876c3e1734e8.png)
**As follows：**
![image](https://user-images.githubusercontent.com/43409147/72513984-d8aac780-3888-11ea-88fa-0164d51508a5.png)

**But I encountered the error again：**

> Duplicate class org.tensorflow.lite.DataType found in modules 1.14-tensorflow-lite-with-select-tf-ops-runtime.jar (1.14-tensorflow-lite-with-select-tf-ops.aar) and tensorflow-lite-2.1.0-runtime.jar (org.tensorflow:tensorflow-lite:2.1.0)
Duplicate class org.tensorflow.lite.DataType$1 found in modules 1.14-tensorflow-lite-with-select-tf-ops-runtime.jar (1.14-tensorflow-lite-with-select-tf-ops.aar) and tensorflow-lite-2.1.0-runtime.jar (org.tensorflow:tensorflow-lite:2.1.0)
Duplicate class org.tensorflow.lite.Delegate found in modules 1.14-tensorflow-lite-with-select-tf-ops-runtime.jar (1.14-tensorflow-lite-with-select-tf-ops.aar) and tensorflow-lite-2.1.0-runtime.jar (org.tensorflow:tensorflow-lite:2.1.0)
Duplicate class org.tensorflow.lite.Interpreter found in modules 1.14-tensorflow-lite-with-select-tf-ops-runtime.jar (1.14-tensorflow-lite-with-select-tf-ops.aar) and tensorflow-lite-2.1.0-runtime.jar (org.tensorflow:tensorflow-lite:2.1.0)
Duplicate class org.tensorflow.lite.Interpreter$Options found in modules 1.14-tensorflow-lite-with-select-tf-ops-runtime.jar (1.14-tensorflow-lite-with-select-tf-ops.aar) and tensorflow-lite-2.1.0-runtime.jar (org.tensorflow:tensorflow-lite:2.1.0)
Duplicate class org.tensorflow.lite.NativeInterpreterWrapper found in modules 1.14-tensorflow-lite-with-select-tf-ops-runtime.jar (1.14-tensorflow-lite-with-select-tf-ops.aar) and tensorflow-lite-2.1.0-runtime.jar (org.tensorflow:tensorflow-lite:2.1.0)
Duplicate class org.tensorflow.lite.Tensor found in modules 1.14-tensorflow-lite-with-select-tf-ops-runtime.jar (1.14-tensorflow-lite-with-select-tf-ops.aar) and tensorflow-lite-2.1.0-runtime.jar (org.tensorflow:tensorflow-lite:2.1.0)
Duplicate class org.tensorflow.lite.TensorFlowLite found in modules 1.14-tensorflow-lite-with-select-tf-ops-runtime.jar (1.14-tensorflow-lite-with-select-tf-ops.aar) and tensorflow-lite-2.1.0-runtime.jar (org.tensorflow:tensorflow-lite:2.1.0)
Duplicate class org.tensorflow.lite.nnapi.NnApiDelegate found in modules 1.14-tensorflow-lite-with-select-tf-ops-runtime.jar (1.14-tensorflow-lite-with-select-tf-ops.aar) and tensorflow-lite-2.1.0-runtime.jar (org.tensorflow:tensorflow-lite:2.1.0)

I have tried other versions of tensorflow-lite, such as 1.10.0. This error also appears.
I checked a lot of information and made a lot of changes, but still can't use this AAR and tflite that requires RandomUniform operator

So I urgently need your help ~~~

**Comment by jdduke** [comment]
Your latest gradle file doesn't conform to the guidance:
```
dependencies {
    implementation 'org.tensorflow:tensorflow-lite:0.0.0-nightly'
    implementation 'org.tensorflow:tensorflow-lite-select-tf-ops:0.0.0-nightly'
}
```

Have you given that a try?

The `tensorflow-lite-with-select-tf-ops` variant is deprecated, and was intended to replace the base `tensorflow-lite` dependency. However, the new `tensorflow-lite-select-tf-ops` dependency is intended to be used *in addition* to the `tensorflow-lite` dependency. I also noticed that there was a bad rebase in the docs for this feature, which i'll be reverting. However, I would give the approach mentioned above a try. Note that you might need to [clear your gradle cache](https://stackoverflow.com/questions/23025433/how-to-clear-gradle-cache).

**Comment by daihuidai** [comment]
Thank you very much, I tried some methods and finally solved the problem.
