### ISSUE TITLE
conda install tensorflow or any command to install the Tensroflow is not working.

### ISSUE THREAD

**Issue by vishwas1234567** [tensorflow/tensorflow#35935]
(base) C:\Users\vishwasnarayan>conda install -c anaconda tensorflow
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: C:\Users\vishwasnarayan\AppData\Local\Continuum\anaconda3

  added / updated specs:
    - tensorflow

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    _tflow_select-2.3.0        |              mkl           3 KB  anaconda
    absl-py-0.8.1              |           py37_0         162 KB  anaconda
    astor-0.8.0                |           py37_0          45 KB  anaconda
    gast-0.2.2                 |           py37_0         138 KB  anaconda
    google-pasta-0.1.8         |             py_0          43 KB  anaconda
    keras-applications-1.0.8   |             py_0          33 KB  anaconda
    keras-preprocessing-1.1.0  |             py_1          36 KB  anaconda
    libmklml-2019.0.5          |                0        21.4 MB  anaconda
    libprotobuf-3.11.2         |       h7bd577a_0         2.3 MB  anaconda
    markdown-3.1.1             |           py37_0         132 KB  anaconda
    opt_einsum-3.1.0           |             py_0          54 KB  anaconda
    protobuf-3.11.2            |   py37h33f27b4_0         597 KB  anaconda
    tensorboard-2.0.0          |     pyhb38c66f_1         3.3 MB  anaconda
    tensorflow-2.0.0           |mkl_py37he1bbcac_0           4 KB  anaconda
    tensorflow-base-2.0.0      |mkl_py37hd1d5974_0        41.9 MB  anaconda
    tensorflow-estimator-2.0.0 |     pyh2649769_0         272 KB  anaconda
    termcolor-1.1.0            |           py37_1           7 KB  anaconda
    ------------------------------------------------------------
                                           Total:        70.4 MB

The following NEW packages will be INSTALLED:

  _tflow_select      anaconda/win-64::_tflow_select-2.3.0-mkl
  absl-py            anaconda/win-64::absl-py-0.8.1-py37_0
  astor              anaconda/win-64::astor-0.8.0-py37_0
  gast               anaconda/win-64::gast-0.2.2-py37_0
  google-pasta       anaconda/noarch::google-pasta-0.1.8-py_0
  grpcio             pkgs/main/win-64::grpcio-1.16.1-py37h351948d_1
  keras-applications anaconda/noarch::keras-applications-1.0.8-py_0
  keras-preprocessi~ anaconda/noarch::keras-preprocessing-1.1.0-py_1
  libmklml           anaconda/win-64::libmklml-2019.0.5-0
  libprotobuf        anaconda/win-64::libprotobuf-3.11.2-h7bd577a_0
  markdown           anaconda/win-64::markdown-3.1.1-py37_0
  opt_einsum         anaconda/noarch::opt_einsum-3.1.0-py_0
  protobuf           anaconda/win-64::protobuf-3.11.2-py37h33f27b4_0
  tensorboard        anaconda/noarch::tensorboard-2.0.0-pyhb38c66f_1
  tensorflow         anaconda/win-64::tensorflow-2.0.0-mkl_py37he1bbcac_0
  tensorflow-base    anaconda/win-64::tensorflow-base-2.0.0-mkl_py37hd1d5974_0
  tensorflow-estima~ anaconda/noarch::tensorflow-estimator-2.0.0-pyh2649769_0
  termcolor          anaconda/win-64::termcolor-1.1.0-py37_1

Proceed ([y]/n)? y

Downloading and Extracting Packages
gast-0.2.2           | 138 KB    | ############################################################################ | 100%
tensorflow-estimator | 272 KB    | ############################################################################ | 100%
tensorflow-base-2.0. | 41.9 MB   | ############################################################################ | 100%
tensorflow-2.0.0     | 4 KB      | ############################################################################ | 100%
astor-0.8.0          | 45 KB     | ############################################################################ | 100%
absl-py-0.8.1        | 162 KB    | ############################################################################ | 100%
_tflow_select-2.3.0  | 3 KB      | ############################################################################ | 100%
libmklml-2019.0.5    | 21.4 MB   | ############################################################################ | 100%
tensorboard-2.0.0    | 3.3 MB    | ############################################################################ | 100%
libprotobuf-3.11.2   | 2.3 MB    | ############################################################################ | 100%
opt_einsum-3.1.0     | 54 KB     | ############################################################################ | 100%
markdown-3.1.1       | 132 KB    | ############################################################################ | 100%
google-pasta-0.1.8   | 43 KB     | ############################################################################ | 100%
keras-applications-1 | 33 KB     | ############################################################################ | 100%
termcolor-1.1.0      | 7 KB      | ############################################################################ | 100%
keras-preprocessing- | 36 KB     | ############################################################################ | 100%
protobuf-3.11.2      | 597 KB    | ############################################################################ | 100%
Preparing transaction: done
Verifying transaction: failed

CondaVerificationError: The package for tensorflow-base located at C:\Users\vishwasnarayan\AppData\Local\Continuum\anaconda3\pkgs\tensorflow-base-2.0.0-mkl_py37hd1d5974_0
appears to be corrupted. The path 'Lib/site-packages/tensorflow-2.0.0.data/purelib/tensorflow_core/include/tensorflow_core/core/grappler/optimizers/generic_layout_optimizer_transposer_factory.h'
specified in the package manifest cannot be found.

**Comment by ravikyram** [comment]
Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version. Also, did you compile from source or install a binary?

Make sure you also include the exact command if possible to produce the output included in your test case. If you are unclear what to include see the issue template displayed in [the Github new issue template](https://github.com/tensorflow/tensorflow/issues/new/choose).

We ask for this in the issue submission template, because it is really difficult to help without that information. Thanks!

**Comment by smsrikanthreddy** [comment]
I am getting the same error. 
OS -  Windows 10- 64 bit

command ran is
"conda install tensorflow" (python 3.7 version )
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: C:\Users\xxxxxx\AppData\Local\Continuum\anaconda3

  added / updated specs:
    - tensorflow


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    _tflow_select-2.3.0        |              mkl           3 KB
    absl-py-0.8.1              |           py37_0         165 KB
    astor-0.8.0                |           py37_0          47 KB
    conda-4.8.1                |           py37_0         2.8 MB
    gast-0.2.2                 |           py37_0         155 KB
    google-pasta-0.1.8         |             py_0          43 KB
    grpcio-1.16.1              |   py37h351948d_1         850 KB
    keras-applications-1.0.8   |             py_0          33 KB
    keras-preprocessing-1.1.0  |             py_1          36 KB
    libmklml-2019.0.5          |                0        17.4 MB
    libprotobuf-3.11.2         |       h7bd577a_0         1.8 MB
    markdown-3.1.1             |           py37_0         132 KB
    opt_einsum-3.1.0           |             py_0          54 KB
    protobuf-3.11.2            |   py37h33f27b4_0         544 KB
    tensorboard-2.0.0          |     pyhb38c66f_1         3.3 MB
    tensorflow-2.0.0           |mkl_py37he1bbcac_0           4 KB
    tensorflow-base-2.0.0      |mkl_py37hd1d5974_0        30.9 MB
    tensorflow-estimator-2.0.0 |     pyh2649769_0         250 KB
    termcolor-1.1.0            |           py37_1           8 KB
    ------------------------------------------------------------
                                           Total:        58.6 MB

The following NEW packages will be INSTALLED:

  _tflow_select      pkgs/main/win-64::_tflow_select-2.3.0-mkl
  absl-py            pkgs/main/win-64::absl-py-0.8.1-py37_0
  astor              pkgs/main/win-64::astor-0.8.0-py37_0
  gast               pkgs/main/win-64::gast-0.2.2-py37_0
  google-pasta       pkgs/main/noarch::google-pasta-0.1.8-py_0
  grpcio             pkgs/main/win-64::grpcio-1.16.1-py37h351948d_1
  keras-applications pkgs/main/noarch::keras-applications-1.0.8-py_0
  keras-preprocessi~ pkgs/main/noarch::keras-preprocessing-1.1.0-py_1
  libmklml           pkgs/main/win-64::libmklml-2019.0.5-0
  libprotobuf        pkgs/main/win-64::libprotobuf-3.11.2-h7bd577a_0
  markdown           pkgs/main/win-64::markdown-3.1.1-py37_0
  opt_einsum         pkgs/main/noarch::opt_einsum-3.1.0-py_0
  protobuf           pkgs/main/win-64::protobuf-3.11.2-py37h33f27b4_0
  tensorboard        pkgs/main/noarch::tensorboard-2.0.0-pyhb38c66f_1
  tensorflow         pkgs/main/win-64::tensorflow-2.0.0-mkl_py37he1bbcac_0
  tensorflow-base    pkgs/main/win-64::tensorflow-base-2.0.0-mkl_py37hd1d5974_0
  tensorflow-estima~ pkgs/main/noarch::tensorflow-estimator-2.0.0-pyh2649769_0
  termcolor          pkgs/main/win-64::termcolor-1.1.0-py37_1

The following packages will be UPDATED:

  conda                                       4.7.12-py37_0 --> 4.8.1-py37_0


Proceed ([y]/n)? y


Downloading and Extracting Packages
keras-applications-1 | 33 KB     | ############################################################################ | 100%
tensorflow-estimator | 250 KB    | ############################################################################ | 100%
tensorflow-2.0.0     | 4 KB      | ############################################################################ | 100%
absl-py-0.8.1        | 165 KB    | ############################################################################ | 100%
conda-4.8.1          | 2.8 MB    | ############################################################################ | 100%
astor-0.8.0          | 47 KB     | ############################################################################ | 100%
protobuf-3.11.2      | 544 KB    | ############################################################################ | 100%
libprotobuf-3.11.2   | 1.8 MB    | ############################################################################ | 100%
grpcio-1.16.1        | 850 KB    | ############################################################################ | 100%
tensorboard-2.0.0    | 3.3 MB    | ############################################################################ | 100%
termcolor-1.1.0      | 8 KB      | ############################################################################ | 100%
opt_einsum-3.1.0     | 54 KB     | ############################################################################ | 100%
markdown-3.1.1       | 132 KB    | ############################################################################ | 100%
gast-0.2.2           | 155 KB    | ############################################################################ | 100%
tensorflow-base-2.0. | 30.9 MB   | ############################################################################ | 100%
_tflow_select-2.3.0  | 3 KB      | ############################################################################ | 100%
google-pasta-0.1.8   | 43 KB     | ############################################################################ | 100%
libmklml-2019.0.5    | 17.4 MB   | ############################################################################ | 100%
keras-preprocessing- | 36 KB     | ############################################################################ | 100%
Preparing transaction: done
Verifying transaction: failed

CondaVerificationError: The package for tensorflow-base located at C:\Users\srmetlakunta\AppData\Local\Continuum\anaconda3\pkgs\tensorflow-base-2.0.0-mkl_py37hd1d5974_0
appears to be corrupted. The path 'Lib/site-packages/tensorflow-2.0.0.data/purelib/tensorflow_core/include/tensorflow_core/core/grappler/optimizers/generic_layout_optimizer_transposer_factory.h'
specified in the package manifest cannot be found.

**Comment by ravikyram** [comment]
@vishwas1234567 

Can you try installing with pip instead of conda and see how it progresses.Please, follow the instructions from [here](https://www.tensorflow.org/install/pip).Thanks!

**Comment by vishwas1234567** [comment]
I am looking for the performance form the conda and the time it commands
also have stopped working after doing it with the pip.

**Comment by migliorinie** [comment]
I traced this issue to Windows not allowing, by default, file paths loner than 256 characters. To solve, you should set the LongPathsEnabled key in your registry to 1, as explained [here](https://knowledge.autodesk.com/search-result/caas/sfdcarticles/sfdcarticles/The-Windows-10-default-path-length-limitation-MAX-PATH-is-256-characters.html).
I'm currently checking out what happens when I rename that file to be shorter, in case you, like me, don't have admin access to your computer.

**Comment by higautam** [comment]
What is a workaround here other than registry key change? 
@migliorinie you mentioned, you are checking with smaller filename. Does that change come in the next version release of tensorflow?
Can I install some older tensorflow version as a workaround?

**Comment by hallibay** [comment]
Hi @vishwas1234567 , Please i am encountering the same error while installing tensorflow on anaconda, how were you able to solve it? thanks.

**Comment by ynackash** [comment]
> I traced this issue to Windows not allowing, by default, file paths longer than 256 characters. To solve, you should set the LongPathsEnabled key in your registry to 1, as explained [here](https://knowledge.autodesk.com/search-result/caas/sfdcarticles/sfdcarticles/The-Windows-10-default-path-length-limitation-MAX-PATH-is-256-characters.html).
> I'm currently checking out what happens when I rename that file to be shorter, in case you, like me, don't have admin access to your computer.

This solution worked for me, I recommend others to try this. Thank you!

**Comment by WisamAmmori** [comment]
> I traced this issue to Windows not allowing, by default, file paths longer than 256 characters. To solve, you should set the LongPathsEnabled key in your registry to 1, as explained [here](https://knowledge.autodesk.com/search-result/caas/sfdcarticles/sfdcarticles/The-Windows-10-default-path-length-limitation-MAX-PATH-is-256-characters.html).
> I'm currently checking out what happens when I rename that file to be shorter, in case you, like me, don't have admin access to your computer.

Worked for me too. Thank you.

**Comment by mihaimaruseac** [comment]
This seems solved, closing.

Please don't reply with "works for me" as that hides the solution and then causes more duplicated issues.

**Comment by cleebp** [comment]
Our enterprise machines that can't edit registry keys continuously run into this max path issue, in our win-64 conda `tensorflow=2.7` builds we have to build from `c:\c` as even `c:\conda` will exceed the max path length while building tf. 

Additionally we have to remove the entire `_virtual_includes` directory or anyone who installs the package on a windows machine that can't edit registry keys will get a `conda verification error` where conda will say certain far-nested paths inside `_virtual_includes` can't be found (even though they exist), this is due to the max path issue.

Hopefully this helps someone else!
