### ISSUE TITLE
How to run custom encoder-decoder in Tensorflow using available APIs?

### ISSUE THREAD

**Issue by krayush07** [tensorflow/tensorflow#3593]
I need to run a encoder-decoder model in Tensorflow. I see that using the available APIs `basic_rnn_seq2seq(encoder_input_data, decoder_input_data, lstm_cell)`	etc., an encoder-decoder system can be created. However, few pertaining issues are:

 1. How can we enter the embeddings such as word2vec in such model? I am
    aware that we can do embedding lookup but as per the API
    `encoder_input_data` is a list of 2D Tensor of size batch_size x
    input_size. How can each word be represented using its respective word embedding in this setup? Even `embedding_rnn_seq2seq` internally extracts the embeddings. How to give pre-calculated word embeddings as input? 
 2. How can we get the cost and perplexity through the API?
 3. In case of test instances, we may not know the corresponding decoder inputs. How to handle such case?

**Comment by michaelisard** [comment]
This kind of usage question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow). GitHub issues are for TensorFlow bugs and installation issues. Thanks!
