### ISSUE TITLE
GPU Support Instructions for CUDA 10 (Ubuntu 16.04) refer to non-existent package

### ISSUE THREAD

**Issue by JMMarchant** [tensorflow/tensorflow#35936]
The current GPU Support instructions for CUDA 10 on Ubuntu 16.04 refers to a package version that does not exist in the [NVIDIA ML repo](https://developer.download.nvidia.cn/compute/machine-learning/repos/ubuntu1604/x86_64/): `libnvinfer5=6.0.1-1+cuda10.1`

#### Ubuntu 16.04 (CUDA 10)

<pre class="prettyprint lang-bsh">
...
# Install TensorRT. Requires that libcudnn7 is installed above.
<code class="devsite-terminal">sudo apt-get install -y --no-install-recommends libnvinfer5=6.0.1-1+cuda10.1 \
    libnvinfer-dev=6.0.1-1+cuda10.1
</code>
</pre>

This results in an error when trying to install:
```
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Version ‘6.0.1-1+cuda10.1’ for ‘libnvinfer5’ was not found
```

Changing this to `libnvinfer6=6.0.1-1+cuda10.1` seems to work and run happily.

**Comment by ashutosh1919** [comment]
@JMMarchant , Close this issue if the doc is already merged with the alternative PR merge.

**Comment by gadagashwini** [comment]
@JMMarchant, Associated PR has been merged, can we close this issue. Thanks!

**Comment by JMMarchant** [comment]
Looks good! Thanks all!
