### ISSUE TITLE
tf.data.Dataset.from_generator converts input argument types implicitly instead of just forwarding

### ISSUE THREAD

**Issue by mxmlnkn** [tensorflow/tensorflow#35944]
**System information**
- custom code
- Ubuntu 18.04.1 LTS
- Thinkpad X240
- TensorFlow installed via pip3
- TensorFlow v2.0.0-rc2-26-g64c3d38 2.0.0
- Python 3.6.8
- no CUDA/cuDNN

**Describe the current behavior**

The code below generates the output `(1, 0)` for the first print when using the generator directly and the exception below when wrapping the generator using `tf.data.Dataset.from_generator`.

```
---------------------------------------------------------------------------
InvalidArgumentError                      Traceback (most recent call last)
<ipython-input-35-36b15431cf1a> in <module>()
     17 
     18 print( next( movingWindow( data, window_size ) ) )
---> 19 print( next( iter( dataset ) ) )

/home/maximiliank/.local/lib/python3.6/site-packages/tensorflow_core/python/data/ops/iterator_ops.py in __next__(self)
    620 
    621   def __next__(self):  # For Python 3 compatibility
--> 622     return self.next()
    623 
    624   def _next_internal(self):

/home/maximiliank/.local/lib/python3.6/site-packages/tensorflow_core/python/data/ops/iterator_ops.py in next(self)
    664     """Returns a nested structure of `Tensor`s containing the next element."""
    665     try:
--> 666       return self._next_internal()
    667     except errors.OutOfRangeError:
    668       raise StopIteration

/home/maximiliank/.local/lib/python3.6/site-packages/tensorflow_core/python/data/ops/iterator_ops.py in _next_internal(self)
    649             self._iterator_resource,
    650             output_types=self._flat_output_types,
--> 651             output_shapes=self._flat_output_shapes)
    652 
    653       try:

/home/maximiliank/.local/lib/python3.6/site-packages/tensorflow_core/python/ops/gen_dataset_ops.py in iterator_get_next_sync(iterator, output_types, output_shapes, name)
   2671       else:
   2672         message = e.message
-> 2673       _six.raise_from(_core._status_to_exception(e.code, message), None)
   2674   # Add nodes to the TensorFlow graph.
   2675   if not isinstance(output_types, (list, tuple)):

/usr/lib/python3/dist-packages/six.py in raise_from(value, from_value)

InvalidArgumentError: TypeError: an integer is required
Traceback (most recent call last):

  File "/home/maximiliank/.local/lib/python3.6/site-packages/tensorflow_core/python/ops/script_ops.py", line 221, in __call__
    ret = func(*args)

  File "/home/maximiliank/.local/lib/python3.6/site-packages/tensorflow_core/python/data/ops/dataset_ops.py", line 585, in generator_py_func
    values = next(generator_state.get_iterator(iterator_id))

  File "<ipython-input-35-36b15431cf1a>", line 3, in movingWindow
    buffer = collections.deque( data[:window_size-1], maxlen = window_size )

TypeError: an integer is required


	 [[{{node PyFunc}}]] [Op:IteratorGetNextSync]
```

As it turns out this is because the `window_size` given in the `args` argument is unexpectedly converted from `int` to `np.int32`, which can't be used interchangeably for slicing or the deque maxlen parameter.

**Describe the expected behavior**

The example should work without exception. Which means, from_generator should not change the types of any arguments given via the `args` parameter.

**Code to reproduce the issue**

```Python3
import tensorflow as tf
import numpy as np
import collections

def movingWindow( data, window_size ):
    #window_size = int( window_size )
    buffer = collections.deque( data[:window_size-1], maxlen = window_size )
    for i, datum in enumerate( data[window_size-1:] ):
        buffer.append( datum )
        for b in buffer:
            yield datum, b

window_size = 2
data = np.arange( 10 )

dataset = tf.data.Dataset.from_generator( 
    movingWindow,
    args = ( data, window_size ),
    output_types = ( np.int32, np.int32 )
)

print( next( movingWindow( data, window_size ) ) )
print( next( iter( dataset ) ) )
```

**Comment by oanush** [comment]
Issue replicating for given code in 2.0 and [tf-nightly](https://colab.sandbox.google.com/gist/oanush/1e681b438b022288058eca121014b041/35944.ipynb).TThanks!

**Comment by jsimsa** [comment]
@mxmlnkn would you be able to check whether the same issue can be reproduced using `py_function` without tf.data. `tf.data.Dataset.from_generator` relies on `py_function` internally and I believe that this issue is inherent to `py_function.

**Comment by mxmlnkn** [comment]
> @mxmlnkn would you be able to check whether the same issue can be reproduced using `py_function` without tf.data. `tf.data.Dataset.from_generator` relies on `py_function` internally and I believe that this issue is inherent to `py_function`.

I'm not able to check that as I don't know how it should work. `py_function` expects the function to return tf datatypes, I think. However, if I want to test the conversion of arguments to the generator function, then the return type would be a generator object: `tf.py_function( movingWindow, ( data, window_size ), ( np.int32, np.int32 ) )` is what I tried naively and gives a long backtrace.

Also, from what I see `from_generator` uses [`numpy_function`](https://github.com/tensorflow/tensorflow/blob/41a09aa33dece4d8c051983f0af6428e9d1d593c/tensorflow/python/data/ops/dataset_ops.py#L754) not `py_function`.

Looking at the source code description and again at the documentation, the behavior actually seems to be at least known and maybe even wanted although I don't understand why:
> args: (Optional.) A tuple of tf.Tensor objects that will be evaluated and passed to generator as NumPy-array arguments.

**Comment by amahendrakar** [comment]
Issue persists in [TF v2.2](https://colab.research.google.com/gist/amahendrakar/5774003c375fe71b6a690cb00bd18b47/35944.ipynb) and [TF-nightly](https://colab.research.google.com/gist/amahendrakar/0f979ce994bea24bcc30c1718bebe7b3/35944-tf-nightly.ipynb#scrollTo=4O4xzQAJQ9WD) i.e. 2.3.0-dev20200527. Please find the attached gist. Thanks!

**Comment by sachinprasadhs** [comment]
Was able to reproduce your issue in Tf Nightly 2.6.0-dev20210524, please find the gist [here](https://colab.research.google.com/gist/sachinprasadhs/8e7162698d0b194c6a4dc85934c134c8/35650.ipynb).

**Comment by gadagashwini** [comment]
Hi @mxmlnkn, `tf.data.Dataset.from_generator` produces `FlatMapDataset`. Data iterator next function takes range of Tensor. Workaround would be

```
import tensorflow as tf
import numpy as np
import collections

def movingWindow( data, window_size ):
    #window_size = int( window_size )
    buffer = collections.deque( data[:window_size-1], maxlen = window_size )
    for i, datum in enumerate( data[window_size-1:] ):
        buffer.append( datum )
        for b in buffer:
            yield datum, b

window_size = 2
data = np.arange( 10 )

dataset = tf.data.Dataset.from_generator( 
    movingWindow,
    args = ( data, window_size ),
    output_types = ( np.int32, np.int32 )
)

print( next( movingWindow( data, window_size ) ) )
#print( next( iter( dataset ) ) )

dataset1 = tf.data.Dataset.from_tensors(dataset)
iterator = iter(dataset1)
optional = iterator.get_next_as_optional()
print(optional.has_value())
``` 

**Output**
```
(1, 0)
tf.Tensor(True, shape=(), dtype=bool)
```
Could you confirm, if this workaround helps. Thank you!
