### ISSUE TITLE
Incorrect mention of dataset....

### ISSUE THREAD

**Issue by ManishAradwad** [tensorflow/tensorflow#35940]
## URL(s) with the issue:

https://github.com/tensorflow/examples/blob/master/courses/udacity_intro_to_tensorflow_lite/tflite_c05_exercise_rock_paper_scissors.ipynb
---------------------------------------------------------------
![Screenshot from 2020-01-16 18-37-30](https://user-images.githubusercontent.com/29497701/72527695-5d004900-388f-11ea-84f8-57ed0c12c915.png)
----------------------------------------------------------------

## Description of issue (what needs changing):

I think this exercise doesn't make use of cats_vs_dogs dataset, right??

### Clear description

In place of `cats_vs_dogs` dataset, `rock_paper_scissors` dataset should be mentioned.

### Submit a pull request?

Yes, shortly

**Comment by Rinkal2** [comment]
the dataset is not loading when opening the code in google colab. both dog vs cats and rock_paper_scissors.

**Comment by MarkDaoust** [comment]
Number 5 is an exercise with parts the reader needs to complete. Number 6 is the solution, it works fine in colab.

@Rinkal2  can you be more specific? what is the problem you're seeing?

**Comment by ymodak** [comment]
Closing this issue since the associated PR has merged. 
Feel free to reopen if necessary. Thanks!
