### ISSUE TITLE
Support for saved_model (tf2.*) in tf_compile

### ISSUE THREAD

**Issue by Arjuna197** [tensorflow/tensorflow#35948]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using): 2.*
- Are you willing to contribute it (Yes/No): No

**Describe the feature and the current behavior/state.**
TF_Compile doesn't accept saved_model
**Will this change the current api? How?**
it would add a saved_model entry under tf_library macro
**Who will benefit with this feature?**
Anyone using tf2.* and tf-compile. Frozen graphs are deprecated in 2.0
**Any Other info.**
<3

**Comment by rmothukuru** [comment]
@Arjuna197,
Sorry for the delayed response. Is this **`feature`** still relevant? If so, can you please let us know the **`use case`** where this **`Feature`** is applicable? Thanks!
