### ISSUE TITLE
Unable to replicate RNN results on a different dataset

### ISSUE THREAD

**Issue by pranjaldaga** [tensorflow/tensorflow#3595]
### What is the problem?
[This RNN tutorial script ](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/models/rnn/ptb/ptb_word_lm.py) works perfectly fine until the contents of the files are unchanged, but once changed a **KeyError** is encountered. (see the error log below)

### Environment info
Operating System:

Installed version of CUDA and cuDNN: 

lrwxrwxrwx 1 root root       12 May 24 00:01 libcuda.so -> libcuda.so.1
lrwxrwxrwx 1 root root       17 May 24 00:01 libcuda.so.1 -> libcuda.so.352.41
-rwxr-xr-x 1 root root 14280360 May 24 00:01 libcuda.so.352.41
lrwxrwxrwx 1 root root       29 May 24 00:02 libcudnn.so -> /etc/alternatives/libcudnn_so
lrwxrwxrwx 1 root root       17 Feb  9 07:47 libcudnn.so.4 -> libcudnn.so.4.0.7
-rw-r--r-- 1 root root 61453024 Feb  9 07:47 libcudnn.so.4.0.7
lrwxrwxrwx 1 root root       32 May 24 00:02 libcudnn_static.a -> /etc/alternatives/libcudnn_stlib
-rw-r--r-- 1 root root 62025862 Feb  9 07:47 libcudnn_static_v4.a

If installed from binary pip package, provide:

1. Which pip package you installed: 
***Ubuntu/Linux 64-bit, GPU enabled, Python 2.7***
2. The output from `python -c "import tensorflow; print(tensorflow.__version__)"`.

I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcuda.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcurand.so locally
0.9.0

### Steps to reproduce
1. Download data from here: http://www.fit.vutbr.cz/~imikolov/rnnlm/simple-examples.tgz 
2. Cloned the tensorflow git repository, and be in the root of the git tree.
3. cd tensorflow/models/rnn/ptb
4. python ptb_word_lm.py --data_path=/tmp/simple-examples/data/ --model small

### What have you tried?
1. Change the contents of the file ptb.train.txt OR ptb.valid.txt OR ptb.test.txt

### Logs or other output that would be helpful
Traceback (most recent call last):
  File "ptb_word_lm.py", line 350, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 30, in run
    sys.exit(main(sys.argv))
  File "ptb_word_lm.py", line 289, in main
    raw_data = reader.ptb_raw_data(FLAGS.data_path)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/models/rnn/ptb/reader.py", line 76, in ptb_raw_data
    valid_data = _file_to_word_ids(valid_path, word_to_id)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/models/rnn/ptb/reader.py", line 48, in _file_to_word_ids
    return [word_to_id[word] for word in data]
KeyError: '[The'

***NOTE***: For this specific example, the contents of ptb.valid.txt were changed and the first line of this file is "[The Parent's Assistant, by Maria Edgeworth]"

**Comment by pranjaldaga** [comment]
Hi, 
I tried a bunch of things and tried to run it. Couldn't get it working. I don't think this script would be tailored specifically to the PTB data, so I am pretty sure I am missing something here. Any help/hint would be highly appreciated. Thanks!

**Comment by pranjaldaga** [comment]
@michaelisard Probably you have seen something like this before #3567 .

**Comment by poxvoculi** [comment]
This is not clearly a correctness/performance issue with TensorFlow, rather it's a question about usage of a particular program, so it would be more appropriate to ask this question on StackOverflow.  Please ask it there, and tag it with the 'tensorflow' tag.

I did take a quck look at 'ptb_valid.txt' in the *.tgz bundle referenced above.  It looks like the fragments are newline separated.  I didn't see any use of '[' or ']' to delimit text.   From your question, it sounds like you're using those chars, which may be incorrect.
