### ISSUE TITLE
Allow tf.image.extract_image_patches to work with complex numbers

### ISSUE THREAD

**Issue by lminer** [tensorflow/tensorflow#35955]
It would be nice if `tf.image.extract_image_patches` were extended to work with complex numbers as well.

I work extensively with audio data and after applying an STFT, I get a tensor of complex numbers. As I perform my training on patches from this tensor, it would be great if these patches could be extracted using `tf.image.extract_image_patches`.

I think this is something that would be valuable to many people working in the audio space.

**Comment by yongtang** [comment]
`tf.image.extract_image_patches` is quite useful and I used it before to create a sliding window effect. It makes sense to add full support for all common types.

Added a PR #35962 for complex number support.

**Comment by lminer** [comment]
Wow. That was fast!
