### ISSUE TITLE
Details about Tensorflow's I/O

### ISSUE THREAD

**Issue by claudiacorreia60** [tensorflow/tensorflow#35958]
I'm currently trying to develop an I/O optimization for DL frameworks and for this purpose I would like to understand exactly how Tensorflow behaves when the dataset doesn't fit in memory. More precisely, I want to know how much data is fetched at a time from storage and how frequently it is fetched. I also need to get in more detail about how the prefetching and shuffling features work. I have already been looking for information on these matters and have also read the documentation, but I still haven't got the details I need. Therefore, can anyone tell me where can I find an extensive explanation of Tensorflow's I/O and prefetching and shuffling methods? Or what's the code responsible for handling this?

Thanks

**Comment by ravikyram** [comment]
@claudiacorreia60 

Can you please go through this [link](https://www.tensorflow.org/guide/data_performance) and see if it helps you.Thanks!

**Comment by claudiacorreia60** [comment]
@ravikyram 

That link has useful information about the prefetching process, and [this one](https://www.tensorflow.org/guide/data#randomly_shuffling_input_data) helped me understand the shuffling process. However, I need to know details such as:
- The elements that are prefetched are stored in memory or in storage?
- The buffer used for shuffling fetches elements from memory or from storage? Are they fetched in a specific order?

Maybe if I realize what happens when the dataset doesn't fit in memory, I'll find out the answer to these questions.

Thanks for your help!

**Comment by ymodak** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.
 Thanks!
