### ISSUE TITLE
gather_nd doesnt work for batched slicing,(even for documented examples)

### ISSUE THREAD

**Issue by arvindsg** [tensorflow/tensorflow#3598]
gather_nd doesn't work for batched slicing
Steps to Reproduce

Run the following code
```python
import tensorflow as tf
cons_indices=tf.constant([[[1]], [[0]]])
batch=tf.constant([['a', 'b'], ['c', 'd']])
gathered=tf.gather_nd(batch,cons_indices)
sess = tf.Session()
result = sess.run(gathered)
print(result)
sess.close()
```

Always gives an error regarding incompatible dimensions.

Either the documentation needs to be updated to indicate proper argument format or function implementation is buggy

**Comment by poxvoculi** [comment]
When I run your program I get:

[[['c' 'd']] [['a' 'b']]]

which I believe is correct.  Could you provide more information on your version and installation, and the exact error message?

**Comment by girving** [comment]
Closing due to lack of response.  We are happy to reopen if more details emerge!

**Comment by Arsakes** [comment]
In TFv1.0 it tf.gather_nd seems to wrok randomly. Checkout [here](http://stackoverflow.com/questions/43007410/tensorflow-unexpected-tf-gather-nd-behaviour-bug)
