### ISSUE TITLE
Expand registered kernels for variable ops on GPU

### ISSUE THREAD

**Issue by dirktheeng** [tensorflow/tensorflow#35994]
**System information**
- TensorFlow version (you are using):1.14/1.15
- Are you willing to contribute it (Yes/No): yes

**Describe the feature and the current behavior/state.**

The current variable op on GPU is restricted to float, double, and int64.  Through the TF_CALL_GPU_NUMBER_TYPES and
TF_CALL_int64 macros.

The notes say to restrict the dtype to those supported by the assignment op.  The assignment op has a broader range of dtypes registered through the
TF_CALL_GPU_ALL_TYPES and 
TF_CALL_int64 macros.

This disallows users to store boolian data with small memory footprints and forces unnecessary casts.  For that matter int32's and half precision could probably also be added.

Its a very easy change to make.  However, I am not sure if there is further rational for the restricted types.

**Will this change the current api? How?**
Nothing other than allowing more dtypes to be passed into variable constuctors

**Who will benefit with this feature?**
Anyone who wants to lower variable memory footprint 

**Any Other info.**

**Comment by dirktheeng** [comment]
anybody care to comment as to why the variables are limited? our testing so far is showing no compatibility issues.

**Comment by alextp** [comment]
Replacing the registration to include TF_CALL_GPU_ALL_TYPES SGTM. @sanjoy for FYI.

**Comment by sanjoy** [comment]
Can you be more specific on which ops you want to modify?  For instance, I'm not sure if we should be calling `TF_CALL_GPU_ALL_TYPES` on `AssignAddVariableOp` since we can't add `bool`s.

**Comment by dirktheeng** [comment]
@sanjoy I would prefer to see TF_CALL_GPU_ALL_TYPE on the variableop and assignop (as well as int32) to allow users to create and store it and then limit the assignAdd and/or assignSub to datatypes which are sensible.  That way users have freedom to create and store variables with limited memory use and can then use assignAdd/Sub etc as needed.  So assignAdd/Sub would be left alone (unless you wanted to add int32s to it).  Is it necessary for the creation/assigment to match assignAdd/Sub for some reason?  If not, it would make the code much more memory efficient in certain circumstances.

**Comment by dirktheeng** [comment]
@sanjoy Also, if you look at the existing code, the assignop already has TF_CALL_GPU_ALL_TYPE registration and the variableOp TF_CALL_GPU_NUMBER_TYPE.  IMHO, they should both be TF_CALL_GPU_ALL_TYPE and also include TF_CALL_INT32

**Comment by sanjoy** [comment]
> @sanjoy I would prefer to see TF_CALL_GPU_ALL_TYPE on the variableop

Just to be clear, you're talking about the `Variable` and `VariableV2` op, *not* `VarHandleOp`?

**Comment by dirktheeng** [comment]
@sanjoy yes

**Comment by sanjoy** [comment]
> @sanjoy yes

Ok, that SGTM.  Are you going to send a PR?

**Comment by dirktheeng** [comment]
I can.  This is my first PR.  Will tests be run on servers or do I have to run tests locally?

**Comment by sanjoy** [comment]
> I can. This is my first PR. Will tests be run on servers or do I have to run tests locally?

The PR won't be merged unless all tests pass (this is automatically enforced).  However it is usually better  to run tests locally so that your PR does not get blocked.

**Comment by yongtang** [comment]
Added a PR  #38848 to use  TF_CALL_GPU_ALL_TYPES.
