### ISSUE TITLE
Text Classification RNN tutorial doesn't run under TF2.1

### ISSUE THREAD

**Issue by hohl** [tensorflow/tensorflow#35990]
## URL(s) with the issue:

https://www.tensorflow.org/tutorials/text/text_classification_rnn

## Description of issue (what needs changing):

The sample for LSTM-based text classification doesn't run under Tensorflow 2.1 anymore.

The line:

```
train_dataset = train_dataset.padded_batch(BATCH_SIZE, train_dataset.output_shapes)
```

Does fail with the error:

```
AttributeError: 'ShuffleDataset' object has no attribute 'output_shapes'
```

**Comment by oanush** [comment]
@hohl ,
You can try using 
`train_dataset = train_dataset.padded_batch(BATCH_SIZE, tf.compat.v1.data.get_output_shapes(train_dataset))`
in place of `train_dataset = train_dataset.padded_batch(BATCH_SIZE, train_dataset.output_shapes)
`
`test_dataset = test_dataset.padded_batch(BATCH_SIZE, tf.compat.v1.data.get_output_shapes(test_dataset))`
and in place of `test_dataset = test_dataset.padded_batch(BATCH_SIZE, test_dataset.output_shapes)` 
With above changes tutorials should work fine.
For more info you can refer this [SO link](https://stackoverflow.com/questions/55862178/attributeerror-shuffledataset-object-has-no-attribute-output-shapes-when).Thanks!

**Comment by lampts** [comment]
It happens to the transformer tutorial as well. https://www.tensorflow.org/tutorials/text/transformer

train_dataset = train_dataset.shuffle(BUFFER_SIZE).padded_batch(BATCH_SIZE)
--> need to add tf.compat.v1.data.get_output_shapes(test_dataset)) for padded_shape.

**Comment by oanush** [comment]
@hohl ,
Any update on the issue ?Thanks!

**Comment by hohl** [comment]
@oanush Well, yes, for me it works by using the v1 compat. 

But, considering that this is part of the official Tensorflow documentation: wouldn't it be reasonable to update the documentation? So, that others don't have to search the issues on Github to run the official tutorials?

**Comment by ymodak** [comment]
@hohl  For TF2.1  without  v1 compat you may use:
```python 
#correct version
train_dataset = train_dataset.padded_batch(BATCH_SIZE, train_dataset.output_shapes)
test_dataset = test_dataset.padded_batch(BATCH_SIZE, test_dataset.output_shapes)
```
![image](https://user-images.githubusercontent.com/42785357/74068706-2c549080-49b1-11ea-8494-3451937a5b8b.png)

The above code is given on TF website as well however colab shows different code which breaks. 
```python 
 #incorrect version
train_dataset = train_dataset.padded_batch(BATCH_SIZE)
test_dataset = test_dataset.padded_batch(BATCH_SIZE)
```
cc @lamberta

**Comment by lamberta** [comment]
Thanks.
The tutorial runs using `tf-nightly` which is what's used in the source notebook: https://colab.research.google.com/github/tensorflow/docs/blob/master/site/en/tutorials/text/text_classification_rnn.ipynb

We currently strip come Colab magic when displaying on the webpage---but we should keep this line if we see "tf-nightly"

**Comment by yashk2810** [comment]
Fixed: https://www.tensorflow.org/tutorials/text/text_classification_rnn#setup

**Comment by lamberta** [comment]
Thanks!
