### ISSUE TITLE
Keras TextVectorization AttributeError during save_weights

### ISSUE THREAD

**Issue by tripzero** [tensorflow/tensorflow#35992]
**System information**
- Colab code: https://colab.research.google.com/drive/1Lf1s9O6Z5ss33GEtb4UXEgjq4wiHw7iy
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 19.04/19.10, Google Colab
- TensorFlow installed from (source or binary): pypi binary
- TensorFlow version (use command below): 2.1.0
- Python version: 3.7

**Describe the current behavior**

AttributeError when calling save_weights on a trained model.

```
/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/backend.py in <listcomp>(.0)
   3274   """
   3275   if context.executing_eagerly():
-> 3276     return [x.numpy() for x in tensors]
   3277   elif ops.inside_function():  # pylint: disable=protected-access
   3278     raise RuntimeError('Cannot get value inside Tensorflow graph function.')

AttributeError: 'TrackableWeightHandler' object has no attribute 'numpy'
```

**Describe the expected behavior**

Model weights can be saved

**Code to reproduce the issue**

I simply modified François Chollet's (@fchollet) collab and added save_weights at the end:

https://colab.research.google.com/drive/1Lf1s9O6Z5ss33GEtb4UXEgjq4wiHw7iy#scrollTo=ZXQKEh53v948

Original colab here:

https://colab.research.google.com/drive/1RvCnR7h0_l4Ekn5vINWToI9TNJdpUZB3

**Comment by jvishnuvardhan** [comment]
@tripzero As the error mentioned, please use 'tf' format to save the model. 

> NotImplementedError: Save or restore weights that is not an instance of `tf.Variable` is not supported in h5, use `save_format='tf'` instead. Got a model or layer TextVectorization with weights [<tensorflow.python.keras.engine.base_layer_utils.TrackableWeightHandler object at 0x7f79294bd780>]

When I replaced model saving part as shown below, everything worked as expected.
`model.save_weights("foobar_tf",save_format='tf')`

Please take a look at the [gist here](https://colab.research.google.com/gist/jvishnuvardhan/b1d3020b6e7adfd22082306b5388a94e/textvectorization-example.ipynb).

Please verify once and close the issue if this was resolved for you. Thanks!

**Comment by karmel** [comment]
The TF format should be the default going forward. We will try to clarify the error message so that it's more obvious what the solution is.

**Comment by sacha-buengueroff** [comment]
How can I implement tihs inside a ModelCheckpoint? Im having difficulties with it

**Comment by jvishnuvardhan** [comment]
@sacha-buengueroff As this is an old issue, can you please open a new issue with simple standalone code to reproduce the issue? Thanks!
