### ISSUE TITLE
XLA drops performance across the nodes

### ISSUE THREAD

**Issue by vilmara** [tensorflow/tensorflow#36008]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): TF benchmarks
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):  Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: n/a
- TensorFlow installed from (source or binary): Running with Horovod 0.18.2 via docker
- TensorFlow version (use command below): v1.14.0-rc1-22-gaf24dc91b5
- Python version: 2.7
- Bazel version (if compiling from source): n/a
- GCC/Compiler version (if compiling from source): 4.8
- CUDA/cuDNN version: 10.0 / 7.6.5
- GPU model and memory: 8xV100-16GB (2 nodes, each with 4xV100GPU's)
- MPI version: 4.0.0
- Mellanox OFED version: 4.7-3.2.9.0
- GPUDirect RDMA - nvidia-peer-memory version: 1.0-8

**Describe the current behavior**
I am running TF benchmarks with Horovod in distributed mode, I see the scaling efficiency drops to from 76% (within the node) to 98% (when crossing the nodes), see below the throughput:

-1xGPU within the node total images/sec:     ~1200
-4xGPU's within the node total images/sec:   ~4712  | Scaling Efficiency (1200x4) / 4712 = 98%
-8xGPU's across the nodes total images/sec: ~7302 |  Scaling Efficiency (1200x8) / 7302 = 76%

**Describe the expected behavior**
We are expecting scaling efficiency across the nodes over 95%, it is around ~9120 img/sec. Please notice that the scaling efficiency drops only when crossing the nodes

**Code to reproduce the issue**
`mpirun -np 8 -H <ib>:4,<ib>:4 --allow-run-as-root -x NCCL_NET_GDR_LEVEL=3 -x NCCL_DEBUG_SUBSYS=NET -x NCCL_IB_DISABLE=0 -mca btl_tcp_if_include ib0 -x NCCL_SOCKET_IFNAME=ib0 -x NCCL_DEBUG=INFO -x HOROVOD_MPI_THREADS_DISABLE=1 --bind-to none --map-by slot --mca plm_rsh_args "-p 12345" python tf_cnn_benchmarks.py --data_format=NCHW --distortions=false --use_fp16=True --variable_update=horovod --model=resnet50 --batch_size=128 --xla=true`

**Other info / logs**

**Tracelog 1xGPU:**
```
Step    Img/sec total_loss
1       images/sec: 1187.6 +/- 0.0 (jitter = 0.0)       7.817
10      images/sec: 1201.3 +/- 3.4 (jitter = 9.5)       7.869
20      images/sec: 1200.5 +/- 2.5 (jitter = 6.3)       7.915
30      images/sec: 1202.0 +/- 3.3 (jitter = 8.5)       7.884
40      images/sec: 1202.0 +/- 2.7 (jitter = 7.0)       7.836
50      images/sec: 1200.3 +/- 2.2 (jitter = 6.4)       7.806
60      images/sec: 1201.2 +/- 2.0 (jitter = 6.4)       7.852
70      images/sec: 1202.1 +/- 2.0 (jitter = 7.5)       7.856
80      images/sec: 1201.1 +/- 1.9 (jitter = 7.2)       7.754
90      images/sec: 1200.5 +/- 1.7 (jitter = 6.8)       7.806
100     images/sec: 1200.7 +/- 1.6 (jitter = 6.7)       7.764
----------------------------------------------------------------
total images/sec: 1199.87
----------------------------------------------------------------
```

**Tracelog 8xGPU's:**
```
Step    Img/sec total_loss
1       images/sec: 922.9 +/- 0.0 (jitter = 0.0)        7.787
1       images/sec: 926.8 +/- 0.0 (jitter = 0.0)        7.707
1       images/sec: 927.0 +/- 0.0 (jitter = 0.0)        7.720
1       images/sec: 925.4 +/- 0.0 (jitter = 0.0)        7.881
1       images/sec: 922.4 +/- 0.0 (jitter = 0.0)        7.846
1       images/sec: 926.3 +/- 0.0 (jitter = 0.0)        7.694
1       images/sec: 924.9 +/- 0.0 (jitter = 0.0)        7.683
1       images/sec: 902.0 +/- 0.0 (jitter = 0.0)        7.762
10      images/sec: 926.2 +/- 7.6 (jitter = 25.6)       7.725
10      images/sec: 926.6 +/- 8.5 (jitter = 18.2)       7.647
10      images/sec: 926.6 +/- 7.6 (jitter = 26.9)       7.659
10      images/sec: 926.7 +/- 7.4 (jitter = 26.2)       7.703
10      images/sec: 927.9 +/- 8.2 (jitter = 8.3)        7.613
10      images/sec: 927.2 +/- 7.9 (jitter = 23.9)       7.708
10      images/sec: 927.6 +/- 7.0 (jitter = 11.8)       7.710
10      images/sec: 927.2 +/- 7.4 (jitter = 24.8)       7.669
20      images/sec: 925.7 +/- 4.5 (jitter = 20.9)       7.620
20      images/sec: 926.0 +/- 4.5 (jitter = 21.1)       7.585
20      images/sec: 926.0 +/- 5.1 (jitter = 18.1)       7.530
20      images/sec: 926.0 +/- 4.7 (jitter = 21.0)       7.600
20      images/sec: 926.8 +/- 4.5 (jitter = 17.3)       7.524
20      images/sec: 926.9 +/- 4.9 (jitter = 14.5)       7.638
20      images/sec: 926.6 +/- 4.4 (jitter = 21.8)       7.588
20      images/sec: 926.5 +/- 5.1 (jitter = 19.2)       7.682
30      images/sec: 919.9 +/- 4.1 (jitter = 25.1)       7.567
30      images/sec: 920.1 +/- 4.4 (jitter = 24.5)       7.529
30      images/sec: 920.1 +/- 4.1 (jitter = 24.0)       7.546
30      images/sec: 920.0 +/- 4.1 (jitter = 24.5)       7.578
30      images/sec: 920.5 +/- 4.4 (jitter = 23.7)       7.469
30      images/sec: 920.5 +/- 4.2 (jitter = 24.9)       7.483
30      images/sec: 920.7 +/- 4.2 (jitter = 18.8)       7.489
30      images/sec: 920.6 +/- 4.3 (jitter = 25.2)       7.526
40      images/sec: 916.3 +/- 3.9 (jitter = 25.3)       7.541
40      images/sec: 916.2 +/- 3.9 (jitter = 23.2)       7.444
40      images/sec: 916.2 +/- 4.1 (jitter = 25.1)       7.515
40      images/sec: 915.9 +/- 4.0 (jitter = 26.4)       7.476
40      images/sec: 917.0 +/- 4.1 (jitter = 26.4)       7.534
40      images/sec: 916.8 +/- 4.1 (jitter = 27.9)       7.502
40      images/sec: 916.7 +/- 4.0 (jitter = 26.5)       7.500
40      images/sec: 916.5 +/- 4.3 (jitter = 23.3)       7.529
50      images/sec: 911.2 +/- 3.7 (jitter = 24.8)       7.523
50      images/sec: 911.2 +/- 3.8 (jitter = 31.4)       7.461
50      images/sec: 911.1 +/- 3.7 (jitter = 27.8)       7.461
50      images/sec: 911.6 +/- 3.9 (jitter = 29.1)       7.524
50      images/sec: 911.7 +/- 3.8 (jitter = 24.2)       7.512
50      images/sec: 911.7 +/- 3.9 (jitter = 24.0)       7.419
50      images/sec: 910.9 +/- 3.7 (jitter = 27.9)       7.446
50      images/sec: 911.8 +/- 3.8 (jitter = 27.6)       7.467
60      images/sec: 910.2 +/- 3.5 (jitter = 29.9)       7.513
60      images/sec: 910.1 +/- 3.4 (jitter = 29.8)       7.435
60      images/sec: 910.2 +/- 3.5 (jitter = 23.2)       7.478
60      images/sec: 910.2 +/- 3.4 (jitter = 31.2)       7.463
60      images/sec: 910.7 +/- 3.5 (jitter = 26.3)       7.487
60      images/sec: 910.5 +/- 3.6 (jitter = 28.8)       7.436
60      images/sec: 910.6 +/- 3.6 (jitter = 26.5)       7.408
60      images/sec: 910.6 +/- 3.5 (jitter = 27.9)       7.446
70      images/sec: 913.4 +/- 3.2 (jitter = 26.4)       7.409
70      images/sec: 913.3 +/- 3.2 (jitter = 28.5)       7.441
70      images/sec: 913.4 +/- 3.2 (jitter = 27.8)       7.459
70      images/sec: 913.4 +/- 3.3 (jitter = 24.5)       7.440
70      images/sec: 913.8 +/- 3.4 (jitter = 27.0)       7.459
70      images/sec: 913.8 +/- 3.3 (jitter = 26.4)       7.483
70      images/sec: 913.9 +/- 3.2 (jitter = 28.7)       7.385
70      images/sec: 913.6 +/- 3.3 (jitter = 26.3)       7.445
80      images/sec: 915.7 +/- 3.0 (jitter = 30.2)       7.407
80      images/sec: 915.8 +/- 3.0 (jitter = 26.0)       7.407
80      images/sec: 915.8 +/- 3.0 (jitter = 25.1)       7.468
80      images/sec: 915.8 +/- 3.0 (jitter = 25.3)       7.472
80      images/sec: 916.2 +/- 3.0 (jitter = 27.4)       7.467
80      images/sec: 916.3 +/- 3.1 (jitter = 27.9)       7.443
80      images/sec: 916.1 +/- 3.1 (jitter = 27.7)       7.491
80      images/sec: 915.4 +/- 3.2 (jitter = 24.0)       7.553
90      images/sec: 914.7 +/- 2.8 (jitter = 26.5)       7.404
90      images/sec: 914.6 +/- 2.8 (jitter = 28.5)       7.408
90      images/sec: 914.7 +/- 2.8 (jitter = 25.3)       7.457
90      images/sec: 914.7 +/- 2.9 (jitter = 25.1)       7.405
90      images/sec: 915.0 +/- 2.9 (jitter = 24.0)       7.437
90      images/sec: 915.0 +/- 2.8 (jitter = 27.7)       7.504
90      images/sec: 915.0 +/- 3.0 (jitter = 28.1)       7.431
90      images/sec: 915.1 +/- 2.9 (jitter = 26.5)       7.430
100     images/sec: 913.2 +/- 2.6 (jitter = 26.9)       7.890
----------------------------------------------------------------
total images/sec: 7301.54
----------------------------------------------------------------
```

**Comment by byronyi** [comment]
Ping @dubey; though the issue is about horovod, does NCCL in TF core suffer from the same issue?

**Comment by dubey** [comment]
Can you describe the cluster interconnect?  I can imagine things slowing down if you have NVLink within hosts, but something much slower like TCP over ethernet across hosts.

**Comment by vilmara** [comment]
hi @dubey, I am using Mellanox InfiniBand ConnectX-5 network adapters with 100Gbit/s over IPoIB

**Comment by byronyi** [comment]
@dubey the log @vilmara pasted is from single node 8xGPU, so networking is not an issue here, but it’s horovod so there are some IPCs around.

We have similar observation that global XLA scope slows down the inter-process (both single node and multi-node) all reduces. Wrapping different parts of the model into different JIT scope seems to increase the overlap between communication and computation. This only happened when XLA is enabled.

**Comment by dubey** [comment]
Hang on, from @vilmara's comments it seems like 4x GPUs is one node, and 8x GPUs is "across nodes".  But @byronyi is claiming that 8x GPU is on a single node.

Can we please clarify the exact topology with 4 and 8 GPU runs?

**Comment by byronyi** [comment]
I’m sorry, looking it again it is indeed 4x GPU per node.

**Comment by vilmara** [comment]
> Hang on, from @vilmara's comments it seems like 4x GPUs is one node, and 8x GPUs is "across nodes". But @byronyi is claiming that 8x GPU is on a single node.
> 
> Can we please clarify the exact topology with 4 and 8 GPU runs?

hi @dubey / @byronyi, the system is configured with 2 nodes (each with 4xV100GPU's) for a total of 8xV100-16GB GPU's. I see scaling degradation happens only "across nodes"

**Comment by dubey** [comment]
Thanks for the clarification @vilmara.

In general the scaling across nodes may be lower because of lower bandwidth interconnect.  In this case since the model size is not too large it may be possible to tune some parameters to get better performance.

For NCCL, the number of rings and the number of threads per socket may be useful.  I'm not familiar with Horovod tuning.  @byronyi may have more ideas, I think he's used NCCL over IB.

If you're still stuck, I suggest reaching out to Horovod and/or NCCL owners.

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.

**Comment by vilmara** [comment]
Thanks for the update!, closing it now
