### ISSUE TITLE
[tf1] tf.keras.layers.CudnnGRU cannot be converted and loaded when in subclass of tf.keras.Model

### ISSUE THREAD

**Issue by Yablon** [tensorflow/tensorflow#36014]
**System information**
- TensorFlow version (you are using): 1.14
- Are you willing to contribute it (Yes/No): No

**Describe the feature and the current behavior/state.**

Following codes run well in training. But when I inference on CPU, I cannot load model because of [tensorflow/hdf5_format.py at r1.14 · tensorflow/tensorflow · GitHub](https://github.com/tensorflow/tensorflow/blob/r1.14/tensorflow/python/keras/saving/hdf5_format.py#L373). The code here only works when class is "Model" or "Sequential" instead of its subclasses. 

I can fix this by change the class Foo's name, but it's not a good idea to hack this. 

```
from tensorflow import keras
class Foo(keras.Model):
  def __init__(self, rnn_dims, use_gpu, **kwargs):
    super().__init__(**kwargs)
    # fixed with self.__class__.__name__ = 'Model'
    if use_gpu:
      self.gru1 = keras.layers.CuDnnGRU(rnn_dims,
                                        return_sequences=True,
                                        return_state=True)
    else:
      self.gru1 = keras.layers.GRU(rnn_dims,
                                        return_sequences=True,
                                        return_state=True,
                                        recurrent_activation='sigmoid',
                                        reset_after=True)    
  def call(self, inputs):
    return self.gru1(inputs)

def create_model(rnn_dims, use_gpu):
  foo = Foo(rnn_dims, use_gpu)
  input_layer = keras.Input(shape=(None, rnn_dims))
  output = foo(input_layer)
  # actually there are some other calculations, so I don't want to write everything in Foo here.
  return keras.Model([input_layer], [output])

# Cannot load model
model = create_model(rnn_dims, False)
model.load_weights('path_to_model')
```

**Will this change the current api? How?**
No
**Who will benefit with this feature?**

People use tensorflow 1.1x versions along with tf.keras.layers.CudnnGRU in subclass of tf.keras.Model. 

**Any Other info.**
I know tf2 has a tf.keras.layers.GRU compatibale with GRU and CudnnGRU，but it's a long way to upgrade for now for me.

**Comment by qlzh727** [comment]
Hi @Yablon, since this is an issue for TF1 and we are not going to make any new release for it, I would suggest u to upgrade to TF2 and use tf.compat.v1 if you still need to access any v1 feature. 

I am closing this issue for now, and feel free to reopen if you still hit same error with TF latest releases.
