### ISSUE TITLE
Loading a tf.Module with tf.saved_model.load missing attributes

### ISSUE THREAD

**Issue by hartikainen** [tensorflow/tensorflow#36021]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): macos Catalina
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: n/a
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): `v2.1.0-rc2-17-ge5bf8de410 2.1.0`
- Python version: `3.7.5`
- Bazel version (if compiling from source): n/a
- GCC/Compiler version (if compiling from source): n/a
- CUDA/cuDNN version: n/a
- GPU model and memory: n/a

**Describe the current behavior**
When saving and then loading a `tf.Module` instance using `tf.saved_model`, some of the attributes, such as `trainable_variables` are missing from the loaded object.

**Describe the expected behavior**
I would expect attributes like `trainable_variables` to persist through the serialization/deserialization.

**Code and logs to reproduce the issue**
For example:

```python
import tensorflow as tf


class TestModule(tf.Module):
    def __init__(self, value):
        self.variable = tf.Variable(value)


module_1 = TestModule(value=9000)
tf.saved_model.save(module_1, "./foo")
module_2 = tf.saved_model.load("./foo")

assert module_1.variable.numpy() == module_2.variable.numpy()
assert module_1.trainable_variables == (module_1.variable, )
assert module_2.trainable_variables == (module_2.variable, )
assert module_1.trainable_variables == module_2.trainable_variables
```

raises 

```
$ python -m tests.test_tf_saved_model_trainable_variables_missing
Traceback (most recent call last):
  File "/Users/hartikainen/conda/envs/softlearning-3/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Users/hartikainen/conda/envs/softlearning-3/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/hartikainen/github/rail-berkeley/softlearning-3/tests/test_tf_saved_model_trainable_variables_missing.py", line 15, in <module>
    assert module_2.trainable_variables == (module_2.variable, )
AttributeError: '_UserObject' object has no attribute 'trainable_variables'
```

**Comment by oanush** [comment]
Issue replicating for TF-2.1 and [tf-nightly](https://colab.sandbox.google.com/gist/oanush/c264d49024c257acbbbc2595ade8b468/36021.ipynb) .Thank you

**Comment by allenlavoie** [comment]
We have discussed reviving Modules as Modules instead of a minimal type. For Keras Models @k-w-w has implemented it.

I don't have plans to do this for Module, and I think the Module maintainer @tomhennigan was mildly opposed. But if someone felt strongly it's probably something they could get done. The implementation itself would be quite simple, basically [adding one of these for Module](https://github.com/tensorflow/tensorflow/blob/de45c4b29563b420b3ac9e626d0ba41cb8f2bd46/tensorflow/python/training/tracking/data_structures.py#L1020).

**Comment by hartikainen** [comment]
@allenlavoie thanks for the response, I think this makes sense. Assuming that Modules won't get fully revived, what's the suggested way of serializing objects like above? Is the best practice to manually implement the `__{set,get}state__` functions and use pickle, or is there some better way to do it? Or maybe I should use the `saved_model` like above and manually set the fields back to the deserialized object?

**Comment by allenlavoie** [comment]
One option is to add attributes before save. So if you know you'll want a list of variables, you can collect that and assign it to a different attribute. We do save lists, tuples, dicts with string keys, and namedtuples, just not `@property`s or methods.

Another option is to use GradientTape to collect trainable variables implicitly (tape.trainable_variables() I think).

**Comment by Saduf2019** [comment]
@hartikainen please confirm if above comment helps resolve the issue.

**Comment by hartikainen** [comment]
It's still a little unsatisfactory that the deserialization does not fully recover the item that was serialized. The above solutions would require some custom code for deserialization even for attributes that exist by default for `tf.Module`, which makes me feel like this way of saving/loading should raise `NotImplementedError` if the user doesn't manually implement the deserialization behavior? Or preferable the `tf.Module` would get fully deserialized.

**Comment by mohantym** [comment]
Hi @hartikainen ! I was able to resolve this issue in TF 2.6 . In the  above code , model_2 missed instantiation like model_1 , attaching [gist ](https://colab.research.google.com/gist/mohantym/1e577b3e7040530c7157588c4d3419ac/github_36021.ipynb ) for reference.

**Comment by hartikainen** [comment]
Hey @mohantym. Thanks for taking a look at this. I don't think the suggested solution in the notebook is quite what we want. It doesn't seem to be loading the model, but rather just instantiating two models with the same value.

**Comment by kkimdev** [comment]
@k-w-w Do you know why we didn't revive `trainable_variables` ?

**Comment by Saduf2019** [comment]
@hartikainen 
Please refer to above comment and confirm if this is still an issue or can we move this to closed status.
