### ISSUE TITLE
inference result is unstable

### ISSUE THREAD

**Issue by 18970901926** [tensorflow/tensorflow#36029]
when i do inference use the same input at several times,  the inference result will be error at some times, this is terrible.  I don't know why, and anyone can help me? Thank you.

**Comment by gadagashwini** [comment]
@18970901926 
Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version. Also, did you compile from source or install a binary?
Make sure you also include the exact command if possible to produce the output included in your test case. If you are unclear what to include see the issue template displayed in the Github new issue [template](https://github.com/tensorflow/tensorflow/issues/new/choose).
We ask for this in the issue submission template, because it is really difficult to help without that information. Thanks!

**Comment by 18970901926** [comment]
hi,
&nbsp;&nbsp; I have sovlved the problem by updating tf version for a higher. I stil have a question, the tf c version doesn't work when it contains LSTM block, until replacing LSTM with others. It reply that op doesn't register. It really unconvinent. And i don't know how to register. The tf.contrib module don't work. Can you help me. The LSTM cell is better than others.
&nbsp; &nbsp; &nbsp; Thank you for your reading and replying.






------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"gadagashwini"<notifications@github.com&gt;;
发送时间:&nbsp;2020年1月20日(星期一) 晚上6:21
收件人:&nbsp;"tensorflow/tensorflow"<tensorflow@noreply.github.com&gt;;
抄送:&nbsp;"功夫熊猫"<2551482565@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [tensorflow/tensorflow] inference result is unstable (#36029)




@18970901926
 Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version. Also, did you compile from source or install a binary?
 Make sure you also include the exact command if possible to produce the output included in your test case. If you are unclear what to include see the issue template displayed in the Github new issue template.
 We ask for this in the issue submission template, because it is really difficult to help without that information. Thanks!

**Comment by gadagashwini** [comment]
@18970901926,
Please provide the complete standalone code replicate the reported issue and also provide tensorflow version. Thanks!

**Comment by 18970901926** [comment]
hi,&nbsp;
&nbsp; &nbsp; The tensorflow c version is&nbsp; r1.13,&nbsp; here is the error information.
&nbsp; &nbsp; &nbsp;

&nbsp; &nbsp;Please see the attachment for the complete standalone code which replicate the reported issue.
&nbsp; &nbsp; Thanks.


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"gadagashwini"<notifications@github.com&gt;;
发送时间:&nbsp;2020年1月21日(星期二) 晚上7:21
收件人:&nbsp;"tensorflow/tensorflow"<tensorflow@noreply.github.com&gt;;
抄送:&nbsp;"功夫熊猫"<2551482565@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [tensorflow/tensorflow] inference result is unstable (#36029)




@18970901926,
 Please provide the complete standalone code replicate the reported issue and also provide tensorflow version. Thanks!
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.


从QQ邮箱发来的超大附件

demo.zip (78.90M, 2020年02月21日 10:12 到期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?k=5b31666266b925c8a3b972fa1731061c00505401090205574b095257541c000754014b5a01500d1e00005201080704515000565031393457035c094c4b5844335b&t=exs_ftn_download&code=f1fb1143

**Comment by gadagashwini** [comment]
@18970901926, Could you fill the issue [template](https://github.com/tensorflow/tensorflow/issues/new/choose) and provide all the information to analyze the issue. Thanks!

**Comment by gadagashwini** [comment]
@18970901926, Any update!

**Comment by gadagashwini** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
