### ISSUE TITLE
can't import tensorflow 

### ISSUE THREAD

**Issue by Ali-Junaid** [tensorflow/tensorflow#36020]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 8.1
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): don't understand question
- TensorFlow version: tensorflow-gpu 1.8.0
- Python version: 3.6
- Installed using virtualenv? pip? conda?: pip
- Bazel version (if compiling from source): n/a
- GCC/Compiler version (if compiling from source): n/a
- CUDA/cuDNN version: 9.1.85
- GPU model and memory: Quadro k2100M cuda cores 3.0 2GB memory

I installed CUDA 9.1.85 and  CUDnn files and then i ran a wheel supporting my pc requirements but getting this error

Microsoft Windows [Version 6.3.9600]
(c) 2013 Microsoft Corporation. All rights reserved.

C:\Users\AliJunaid>python
Python 3.6.0 (v3.6.0:41df79263a11, Dec 23 2016, 08:06:12) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\AliJunaid\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "C:\Users\AliJunaid\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\__init__.py", line 52, in <module>
    from tensorflow.core.framework.graph_pb2 import *
  File "C:\Users\AliJunaid\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\core\framework\graph_pb2.py", line 6, in <module>
    from google.protobuf import descriptor as _descriptor
  File "C:\Users\AliJunaid\AppData\Local\Programs\Python\Python36\lib\site-packages\google\protobuf\descriptor.py", line 47, in <module>
    from google.protobuf.pyext import _message
ImportError: DLL load failed: The specified procedure could not be found.
>>> exit()

C:\Users\AliJunaid>

**Comment by ymodak** [comment]
TF 1.8 GPU prebuit binary supports cuda 9.0
See https://www.tensorflow.org/install/source#gpu
You also need to update cuda, cudnn, cupti paths.
See https://www.tensorflow.org/install/gpu#windows_setup

**Comment by ravikyram** [comment]
@Ali-Junaid 
Please, see tested build configuration for TF 1.8 GPU for [windows](https://www.tensorflow.org/install/source_windows#gpu). Thanks!

**Comment by ravikyram** [comment]
@Ali-Junaid 

Any update on this issue please. Thanks!

**Comment by ravikyram** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
