### ISSUE TITLE
ADD NEW DOCUMENTATION ON HOW TO INTERACT WITH ASTRONOMY WITH ANIMATION ?

### ISSUE THREAD

**Issue by CREVIOS** [tensorflow/tensorflow#36039]
Thank you for submitting a TensorFlow documentation issue. Per our GitHub
policy, we only address code/doc bugs, performance issues, feature requests, and
build/installation issues on GitHub.

The TensorFlow docs are open source! To get involved, read the documentation
contributor guide: https://www.tensorflow.org/community/contribute/docs

## Description of issue (what needs changing):
We need a new documentation to interact with astronomy.
### Clear description

Like we think astronomical animation is good for research. We need a new documentaion how to interact with Phoebe or with other by Tensorflow .

**Comment by MarkDaoust** [comment]
https://github.com/phoebe-project ? 

This request is a little too specific. We can't have a doc showing how to make TensorFlow work with every piece of software out there, we have docs for how to use standard data types like CSV files, NumPy arrays or Pandas Dataframes. Those probably have everything you need.
