### ISSUE TITLE
tensorflow1.12 hangs at MapAndBatchDatasetOp::Dataset::Iterator::RunnerThread

### ISSUE THREAD

**Issue by yanqingshang** [tensorflow/tensorflow#36033]
- OS Platform and Distribution: aarch64 
- TensorFlow installed from (source or binary):source
- TensorFlow version: 1.12
- Python version: 3.6.1
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):

preprocessing script is MapAndBatchDataset+PrefetchDataset, When we run training for a long time, we find that the training will be hung. We found that when hanging, the value of batch_results_.front()->num_calls in the following logic of map_and_batch_dataset_op.cc is always 1

    Status GetNextInternal(IteratorContext* ctx,
                             std::vector<Tensor>* out_tensors,
                             bool* end_of_sequence) override {
        std::shared_ptr<BatchResult> result;
        {
          mutex_lock l(*mu_);
          EnsureRunnerThreadStarted(ctx);
          while (batch_results_.empty() ||
                 batch_results_.front()->num_calls > 0) {
            RecordStop(ctx);
            cond_var_->wait(l);
            RecordStart(ctx);
          }
          std::swap(result, batch_results_.front());
          batch_results_.pop_front();
          cond_var_->notify_all();
        }
        return ProcessResult(ctx, result, out_tensors, end_of_sequence);
      }

We found another function, which will reduce result-> num_calls by one. We will modify the property of result-> num_calls to atomic and there will be no problem. Does this mean that this code does not have a memory barrier.
     void CallCompleted(const std::shared_ptr<BatchResult>& result)
          LOCKS_EXCLUDED(*mu_) {
        mutex_lock l(*mu_);
        num_calls_--;
        result->num_calls--;
        cond_var_->notify_all();
      }

One more thing to say is that we only found the problem on ARM OS(aarch64), but not on Linux Ubuntu OS(X86).

We want to know if there is a bug in this snippet of TensorFlow on aarch64 and how to fix it.

Here is the call stack when hung:
Thread 374 (LWP 20847):
#0  0x0000ffffb997d22c in pthread_cond_wait@@GLIBC_2.17 () from target:/lib/aarch64-linux-gnu/libpthread.so.0
#1  0x0000ffffb11adb30 in std::condition_variable::wait(std::unique_lock<std::mutex>&) () from target:/usr/lib/aarch64-linux-gnu/libstdc++.so.6
#2  0x0000ffffb5501c5c in nsync::nsync_mu_semaphore_p_with_deadline(nsync::nsync_semaphore_s_*, timespec) ()
   from target:/usr/local/lib/python3.6/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so
#3  0x0000ffffb55012d4 in nsync::nsync_sem_wait_with_cancel_(nsync::waiter*, timespec, nsync::nsync_note_s_*) ()
   from target:/usr/local/lib/python3.6/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so
#4  0x0000ffffb54fe7f0 in nsync::nsync_cv_wait_with_deadline_generic(nsync::nsync_cv_s_*, void*, void (*)(void*), void (*)(void*), timespec, nsync::nsync_note_s_*) ()
   from target:/usr/local/lib/python3.6/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so
#5  0x0000ffffb3c962d4 in tensorflow::data::(anonymous namespace)::MapAndBatchDatasetOp::Dataset::Iterator::RunnerThread(std::shared_ptr<tensorflow::data::IteratorContext> const&) ()
   from target:/usr/local/lib/python3.6/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so
#6  0x0000ffffb11b3e14 in ?? () from target:/usr/lib/aarch64-linux-gnu/libstdc++.so.6
#7  0x0000ffffb9977088 in start_thread () from target:/lib/aarch64-linux-gnu/libpthread.so.0
#8  0x0000ffffb98054ec in ?? () from target:/lib/aarch64-linux-gnu/libc.so.6

Thread 372 (LWP 20844):
#0  0x0000ffffb997d22c in pthread_cond_wait@@GLIBC_2.17 () from target:/lib/aarch64-linux-gnu/libpthread.so.0
#1  0x0000ffffb11adb30 in std::condition_variable::wait(std::unique_lock<std::mutex>&) () from target:/usr/lib/aarch64-linux-gnu/libstdc++.so.6
#2  0x0000ffffb5501c5c in nsync::nsync_mu_semaphore_p_with_deadline(nsync::nsync_semaphore_s_*, timespec) ()
   from target:/usr/local/lib/python3.6/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so
#3  0x0000ffffb55012d4 in nsync::nsync_sem_wait_with_cancel_(nsync::waiter*, timespec, nsync::nsync_note_s_*) ()
   from target:/usr/local/lib/python3.6/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so
#4  0x0000ffffb54fe7f0 in nsync::nsync_cv_wait_with_deadline_generic(nsync::nsync_cv_s_*, void*, void (*)(void*), void (*)(void*), timespec, nsync::nsync_note_s_*) ()
   from target:/usr/local/lib/python3.6/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so
#5  0x0000ffffb3c938e4 in tensorflow::data::(anonymous namespace)::MapAndBatchDatasetOp::Dataset::Iterator::GetNextInternal(tensorflow::data::IteratorContext*, std::vector<tensorflow::Tensor, std::allocator<tensorflow::Tensor> >*, bool*) () from target:/usr/local/lib/python3.6/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so
#6  0x0000ffffb3c41918 in tensorflow::data::DatasetBaseIterator::GetNext(tensorflow::data::IteratorContext*, std::vector<tensorflow::Tensor, std::allocator<tensorflow::Tensor> >*, bool*) ()
   from target:/usr/local/lib/python3.6/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so
#7  0x0000ffffb3d25644 in std::_Function_handler<void (), tensorflow::data::PrefetchDatasetOp::Dataset::Iterator::EnsurePrefetchThreadStarted(tensorflow::data::IteratorContext*)::{lambda()#1}>::_M_invoke(std::_Any_data const&) () from target:/usr/local/lib/python3.6/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so
#8  0x0000ffffb11b3e14 in ?? () from target:/usr/lib/aarch64-linux-gnu/libstdc++.so.6
#9  0x0000ffffb9977088 in start_thread () from target:/lib/aarch64-linux-gnu/libpthread.so.0
#10 0x0000ffffb98054ec in ?? () from target:/lib/aarch64-linux-gnu/libc.so.6

**Comment by yanqingshang** [comment]
@jsimsa @ravikyram 
This problem has troubled me for a long time. Can you help analyze this problem?

**Comment by jsimsa** [comment]
@yanqingshang I am sorry to hear that this has been an issue for you. Unfortunately, the team does not have resources to investigate issues in dated version of TensorFlow. My suggestion would be to updated to more recent version of TensorFlow. The latest version is TF 2.1 and if you require TF 1 compatibility, it would be TF 1.15.

**Comment by jacquesqiao** [comment]
I meet a problem just like yours. The dataset hangs at the end of reading data. @yanqingshang

**Comment by yanqingshang** [comment]
@jacquesqiao 
You can try my workaround to see if it solves your problem. for tf1.12 version, the official does not have resources to investigate issues in dated version of TensorFlow.

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.
