### ISSUE TITLE
Showing index instead of labels in word embedding projector

### ISSUE THREAD

**Issue by zynabsmaan** [tensorflow/tensorflow#36038]
For large embedding words, I can't show the word itself but the index instead appear. And so, I can't estimate the performance of the word embedding. So, I think words should appear instead of index so, how I can benefit from it?

**System information**
- http://projector.tensorflow.org/

You can add an option so, I can choose either index or words.

Sorry for my bad English.

**Comment by jvishnuvardhan** [comment]
@zynabsmaan Where are you seeing index? Can you please share a screenshot or please give more details. I also think this is not a bug in TF. Can you please post it in Stackoverflow where there is a large community to help. We will also answer there that are not support type questions.

<img width="797" alt="Screen Shot 2020-06-03 at 12 19 30 PM" src="https://user-images.githubusercontent.com/46058173/83679863-f7d69700-a594-11ea-907f-56d838957645.png">
