### ISSUE TITLE
Cannot convert between a TensorFlowLite buffer with 1392640 bytes and a Java Buffer with 4177920 bytes.

### ISSUE THREAD

**Issue by nauyan** [tensorflow/tensorflow#36059]
I am using Tensorflow.Lite.Support function for Inference of a model that takes two input and gives output in the form of Image. The first input is an RGB image whereas the second image is a single-channel image.When I run the application for inference I get the error that is:

**Cannot convert between a TensorFlowLite buffer with 1392640 bytes and a Java Buffer with 4177920 bytes.**

I have attached my code snippet below:
```
protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        Toolbar toolbar = findViewById(R.id.toolbar);
        setSupportActionBar(toolbar);

        FloatingActionButton fab = findViewById(R.id.fab);
        fab.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                Snackbar.make(view, "Replace with your own action", Snackbar.LENGTH_LONG)
                        .setAction("Action", null).show();
            }
        });

        try {
            tflite = new Interpreter(loadModelFile(MainActivity.this, "converted_model.tflite"));


            Bitmap Image = getBitmapFromAsset(this,"001.png");
            Bitmap Mask = getBitmapFromAsset(this,"tmp_mask.png");

            int imageTensorIndex = 0;
            int[] imageShape = tflite.getInputTensor(imageTensorIndex).shape(); // {1, height, width, 3}
            int imageSizeY = imageShape[1];
            int imageSizeX = imageShape[2];
            DataType imageDataType = tflite.getInputTensor(imageTensorIndex).dataType();

            TensorImage inputImageBuffer = new TensorImage(imageDataType);
            inputImageBuffer.load(Image);

            int imageTensorIndex1 = 1;
            int[] imageShape1 = tflite.getInputTensor(imageTensorIndex1).shape(); // {1, height, width, 3}
            int imageSizeY1 = imageShape1[1];
            int imageSizeX1 = imageShape1[2];
            DataType imageDataType1 = tflite.getInputTensor(imageTensorIndex1).dataType();

            TensorImage inputImageBuffer1 = new TensorImage(imageDataType1);
            inputImageBuffer1.load(Mask);


            int OutputTensorIndex = 0;
            int[] OutputShape =
                    tflite.getOutputTensor(OutputTensorIndex).shape(); // {1, NUM_CLASSES}
            DataType OutputDataType = tflite.getOutputTensor(OutputTensorIndex).dataType();

            TensorBuffer outputBuffer = TensorBuffer.createFixedSize(OutputShape, OutputDataType);

            Object[] Inputs = {inputImageBuffer.getBuffer(),inputImageBuffer1.getBuffer()};

            Map<Integer, Object> outputs = new HashMap<>();
            outputs.put(0,outputBuffer);
            tflite.runForMultipleInputsOutputs(Inputs, outputs);

            Toast.makeText(this,"Working",Toast.LENGTH_LONG).show();
  
        } catch (IOException e) {
            Toast.makeText(this,"Failed",Toast.LENGTH_LONG).show();
            e.printStackTrace();
        }
    }

```

**Comment by nauyan** [comment]
The detailed error log is:

```
2020-01-21 11:59:21.375 12800-12800/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.inpainting, PID: 12800
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.inpainting/com.example.inpainting.MainActivity}: java.lang.IllegalArgumentException: Cannot convert between a TensorFlowLite buffer with 1392640 bytes and a Java Buffer with 4177920 bytes.
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2817)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2892)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1593)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6541)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
     Caused by: java.lang.IllegalArgumentException: Cannot convert between a TensorFlowLite buffer with 1392640 bytes and a Java Buffer with 4177920 bytes.
        at org.tensorflow.lite.Tensor.throwIfShapeIsIncompatible(Tensor.java:332)
        at org.tensorflow.lite.Tensor.throwIfDataIsIncompatible(Tensor.java:305)
        at org.tensorflow.lite.Tensor.setTo(Tensor.java:123)
        at org.tensorflow.lite.NativeInterpreterWrapper.run(NativeInterpreterWrapper.java:148)
        at org.tensorflow.lite.Interpreter.runForMultipleInputsOutputs(Interpreter.java:296)
        at com.example.inpainting.MainActivity.onCreate(MainActivity.java:119)
        at android.app.Activity.performCreate(Activity.java:6975)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1213)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2770)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2892) 
        at android.app.ActivityThread.-wrap11(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1593) 
        at android.os.Handler.dispatchMessage(Handler.java:105) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6541) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767) 
```

**Comment by nauyan** [comment]
@ravikyram @ymodak any update?

**Comment by Ehtasha** [comment]
@nauyan  I'm also facing same issue. Did you resolve this issue ?

**Comment by nauyan** [comment]
@Ehtasha No not yet.

**Comment by Dark-Monk** [comment]
@nauyan Any update for this issue?

**Comment by nauyan** [comment]
@Dark-Monk Nope

**Comment by Ehtasha** [comment]
@Dark-Monk  @nauyan 

I you are using ` runSegmentationOnBinary ` method then replace bellow lines

Replace bellow line 
`var convertedBytes = Uint8List(1 * inputSize * inputSize * 3);` 

with 
`var convertedBytes = Uint8List(4 * 1 * inputSize * inputSize * 3);`

**Comment by nauyan** [comment]
@Ehtasha I am using Java instead of kotlin seconldy I am using **runForMultipleInputsOutputs**

**Comment by Ehtasha** [comment]
Okey I'm integrating this using Flutter and binary function is available there.

But is java also multiple with 4 where you specify the image size.
Above inputSize represent the image dimention.

`(4 * 1 * 128* 128 * 3)`

**Comment by nauyan** [comment]
@Ehtasha Can you please point out where should I make changes in the above code?

**Comment by Dark-Monk** [comment]
@Ehtasha ... Appreciate the help but I am already doing this and even tried this (1 * inputSize * inputSize * 3) for Quantized model but didn't worked. I am actually using  the sample app.

Code:
int numBytesPerChannel;
if (isQuantized) {
  numBytesPerChannel = 1; // Quantized
} else {
  numBytesPerChannel = 4; // Floating point
}
d.imgData = ByteBuffer.allocateDirect(1 * d.inputSize * d.inputSize * 3 * numBytesPerChannel);

**Comment by nauyan** [comment]
@Dark-Monk I am have tried the same but doesn't work

**Comment by Ehtasha** [comment]
@nauyan  
I'm integrating my model in flutter app using tflite plugin not in android native.

In flutter binary method is available.

I will try to implement this in android also and then update if this work there.

**Comment by nauyan** [comment]
@Ehtasha sure that would be nice.

**Comment by lingjiekong** [comment]
any update? Would like to know what change need to be made in order to run inference on grayscale image.

**Comment by ymodak** [comment]
@nauyan Apologies for the delay in response. Is this still an issue?

**Comment by shivangsgangadia** [comment]
I had the same problem and found a solution.
Inspect your model using Netron. View model properties using `View -> Model Properties`.
If, for inputs, you have individual elements, see their type. It will look something like this:
`type:float32[1,1]`
This implies that each input is 1 array of 1 element which can be represented with a ByteBuffer in JAVA.
So, say you have a list of 10 inputs, each showing `type:float32[1,1]`, then your `input` object would look like this: 
<pre>
Object[] input = new Object[10];
for (int i = 0; i < 10; i++) {
            ByteBuffer temp = ByteBuffer.allocateDirect(4); // Allocate with size of float
            temp.putFloat(inputData[i]); // May be an array containing actual values
            input[i] = temp;
 }
</pre>
My output, according to Netron looked like this:
`type:float32[1,1]`
So, in JAVA, it would be:
<pre>
ByteBuffer identity = ByteBuffer.allocateDirect(4);
Map<Integer, Object> output = new TreeMap<>();
output.put(0, identity);
</pre>

Since these qualify as multiple inputs, you will have to use:
<code>interpreter.runForMultipleInputsOutputs(input, output);</code>

Hope this helps
