### ISSUE TITLE
TFLite Android Model Benchmark Tool -- results not showing up in adb logcat

### ISSUE THREAD

**Issue by forresti** [tensorflow/tensorflow#36055]
**System information**
- OS Platform and Distribution: Ubuntu 18.04
- Mobile device: Pixel 3
- TensorFlow installed from: source
- TensorFlow version: From master branch, commit hash 69ac54d92de18ca18f9a110d6dd464aeb1116342. Compiled tensorflow with `./configure` and then `bazel build --config=v1 //tensorflow/tools/pip_package:build_pip_package`.
- Python version: 3.6
- Installed using: conda
- Bazel version (if compiling from source): 1.2.1
- GCC/Compiler version (if compiling from source): 7.4, and compiling with c++14 flag
- CUDA/cuDNN version: not using gpu for this experiment
- GPU model and memory: not using gpu for this experiment
- TFLite model that I am trying to benchmark: `mobilenet_v1_0.25_192_quant.tflite` from [this page](https://www.tensorflow.org/lite/guide/hosted_models). Note that I do have some more exotic models that I'd like to benchmark, but I am starting with an off-the-shelf model from an official tensorflow page.

**Describe the problem**

I am trying to benchmark the speed of a tflite model on a pixel 3. 

On an ubuntu computer, with a Pixel 3 in developer mode connected via USB, I followed steps 1 to 5 in **[this readme](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/tools/benchmark/android/README.md)**. I did not get a single error message. When I get to step 4, I get the following output:

```
Stopping: org.tensorflow.lite.benchmark
Starting: Intent { cmp=org.tensorflow.lite.benchmark/.BenchmarkModelActivity (has extras) }
```

While running step 4, I have an other terminal window open with `adb logcat` running. Unfortunately, the phrase `Average inference` doesn't show up in the `logcat` output, and the only relevant thing in `logcat` is `01-19 23:30:20.449  1357  3307 I ActivityTaskManager: START u0 {flg=0x10000000 cmp=org.tensorflow.lite.benchmark/.BenchmarkModelActivity (has extras)} from uid 2000`, but there are no latency numbers showing up in `logcat`. 

Any idea what I am doing wrong, and what's preventing the latency numbers from showing up in `logcat`?

**Comment by jdduke** [comment]
@multiverse-tf can you take a look?

**Comment by forresti** [comment]
I spent some more time on this. Originally, I was using the newest versions of all the android stuff (NDK, SDK, build tools). I changed my NDK to version 14b and SDK to version 

>

**Comment by exist2disappear** [comment]
I have some problem ,change android config, fix it

**Comment by djbacad** [comment]
Does someone have any updates here? I'm getting the same error

**Comment by multiverse-tf** [comment]
> Does someone have any updates here? I'm getting the same error

Which TFLite version did you use? Could you try out a more recent version? The RUY path mentioned in the original comment implies it's a pretty old TFLite version. RUY was moved out of TFLite to its own independent repo in April, 2020.

**Comment by JinMoYang** [comment]
Any updataes on this issue?

**Comment by tbikash62** [comment]
Such weird problem.. Is there any way one can debug?
