### ISSUE TITLE
saved_model_cli breaks nightly packages

### ISSUE THREAD

**Issue by byronyi** [tensorflow/tensorflow#36067]
Our in-house nightly builds were broken since 2020-01-16 when auditwheel tries to repair my nightly packages. The reason under the hood seems to be an incorrect link from the recent change of adding XLA support to `saved_model_cli` in 9959c04433623e0b7ebf6248e0f75bc7a24bd7cb.

Install the latest nightly, and navigate to the directory of `tensorflow_core/compiler/aot`:

```
$ ldd _pywrap_tfcompile.so
	linux-vdso.so.1 (0x00007ffc5e064000)
	libtensorflow_framework.so.2 => /usr/local/lib/python3.7/dist-packages/tensorflow_core/compiler/aot/./../../libtensorflow_framework.so.2 (0x00007fa798bba000)
	_pywrap_tensorflow_internal.so => not found
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fa798b77000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fa798b56000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fa7989d1000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007fa79884d000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fa798833000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fa798672000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fa79afbc000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007fa798668000)
```

Obviously it links to `_pywrap_tensorflow_internal.so` but it is not found with the relative path.

PS: we are using auditwheel==3.0.0 to produce manylinux2014 builds, but the official tf-nightly uses an older version which fails to catch this.

PPS: directly using `saved_model_cli` does not give this error as `_pywrap_tensorflow_internal.so` seems to be preloaded. But I am pretty sure this is a bug that we need to fix.

Ping @ebrevdo @mihaimaruseac.

**Comment by byronyi** [comment]
The reason seems to be that `tf_python_pybind_extension` should only be used for packages in `//tensorflow/python/...`. See https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tensorflow.bzl#L2573-L2577.

**Comment by ebrevdo** [comment]
I have a solution; gonna get it through internal reviews and then will ping you when it's available.

**Comment by ebrevdo** [comment]
@byronyi let me know if this doesn't work for you.
