### ISSUE TITLE
Request for tflite using Android NDK documentaion

### ISSUE THREAD

**Issue by sanrahul** [tensorflow/tensorflow#36063]
Thank you for submitting a TensorFlow documentation issue. Per our GitHub
policy, we only address code/doc bugs, performance issues, feature requests, and
build/installation issues on GitHub.

The TensorFlow docs are open source! To get involved, read the documentation
contributor guide: https://www.tensorflow.org/community/contribute/docs

### Clear description
I have a .tflite model which involves lots of post processing. 
After following https://www.tensorflow.org/lite/guide/inference#load_and_run_a_model_in_c  I have written the code in cpp and tested on linux and adb shell.

Now I want to use this code in the sample Android apk .(https://github.com/tensorflow/examples/tree/master/lite/examples/object_detection/android)

Is there any documentation/sample usage of tflite cpp in Android? 
I have only found this(https://github.com/zimenglyu/TFLiteExample) but not able to follow this :(

Any help would be desperately appreciated.

**Comment by sanrahul** [comment]
Found this tf_world's tflite with cpp demo::
https://github.com/infil00p/tf_world
Will follow it and update.

**Comment by jvishnuvardhan** [comment]
@sanrahul Are you raising a PR to update the docs? When you raise a PR, just mention it here so that we will close after it gets merged. Thanks!
