### ISSUE TITLE
Request example for object detection  on Tensorflow >= 2.0 in CPP

### ISSUE THREAD

**Issue by xav12358** [tensorflow/tensorflow#36062]
Hello,
I want to use Tensorflow frozen models in c++. I did find examples on CPP in Tensorflow < 2.0:
https://github.com/CasiaFan/tensorflow_cpp_object_detection_web_server

Where could I get an simple SSD object detection on CPP in Tensorflow >= 2.0 ?
  

**System information** : Ubuntu 18.04
- TensorFlow version (you are using): 2.0 
- Are you willing to contribute it (Yes/No): Yes

**Comment by ymodak** [comment]
It can be a good idea to raise this issue on [tensorflow/models](https://github.com/tensorflow/models/issues) repo.
Since we have https://github.com/tensorflow/models/tree/master/research/object_detection hosted there. Thanks!
