### ISSUE TITLE
setting allow_nudging_weights_to_use_fast_gemm_kernel in the python API does not work

### ISSUE THREAD

**Issue by ianfhunter** [tensorflow/tensorflow#36069]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux, 18.04 Ubuntu
- TensorFlow installed from (source or binary): pip3
- TensorFlow version (or github SHA if from source): 1.x

**Command used to run the converter or code if you’re using the Python API**

```
...
from tensorflow.lite.toco import toco_flags_pb2 as toco_flags
toco = toco_flags.TocoFlags()
toco.allow_nudging_weights_to_use_fast_gemm_kernel = True
converter.convert()
...
```

**The output from the converter invocation**

```
Bad value for conv/weights at index 187, previous bad value at index 175, distance=12, kMinDistanceBetweenBadValues=16. Consider passing --allow_nudging_weights_to_use_fast_gemm_kernel if you don't care about accuracy.
```
In particular
```Consider passing --allow_nudging_weights_to_use_fast_gemm_kernel if you don't care about accuracy.```

**Also, please include a link to the saved model or GraphDef**

```
N/A - see below
```

**Failure details**
- expected behaviour - the erroring code continues past this step and either fails elsewhere, or continues to pass. It should not suggest the same fix.

**Any other info / logs**

I am restricted in the details I can post of my application.
It looks like the source does not have a check in there, so probably still in 2.x

**Comment by jvishnuvardhan** [comment]
@ianfhunter Can you please provide simple standalone code for faster resolution? You could use any public data. Thanks!

**Comment by jvishnuvardhan** [comment]
@ianfhunter Can you please provide simple standalone code for faster resolution? You could use any public data. Thanks!

**Comment by ianfhunter** [comment]
I'll try to do so in the coming week

**Comment by jvishnuvardhan** [comment]
@ianfhunter Are you still working on providing simple standalone code? Thanks!

**Comment by jvishnuvardhan** [comment]
Closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
