### ISSUE TITLE
Question about GLES delegate 3.1 spec support

### ISSUE THREAD

**Issue by boxerab** [tensorflow/tensorflow#36075]
Hello,
Not sure if this is right issue category, but I am interested in learning details about the GLES delegate.
In particular, I would like to know what part of the 3.1 spec is needed for the delegate, as I am looking into creating a new delegate for a system with incomplete support for 3.1. It does support SSBO and compute shaders.
Thanks!

**Comment by gadagashwini** [comment]
@boxerab, Please take look at the [document](https://www.tensorflow.org/lite/performance/gpu#android_with_android_studio) for openGl support. Thanks!

**Comment by boxerab** [comment]
@gadagashwini thanks. I am looking for specifics on what part of the 3.1 spec is needed. The document you linked to doesn't cover this, unfortunately.

**Comment by impjdi** [comment]
Yeah, the major reason for OpenGL ES 3.1 was for compute shaders & SSBO.   I would just comment out the version check and see whether things work :P

**Comment by boxerab** [comment]
Thanks, @impjdi
