### ISSUE TITLE
Can't set None on TextVectorization layer's split parameter.

### ISSUE THREAD

**Issue by stefanondisponibile** [tensorflow/tensorflow#36071]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): `no`
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): `Ubuntu 18.04`
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: `no`
- TensorFlow installed from (source or binary): `no`
- TensorFlow version (use command below): `2.0.0`
- Python version: `3.7.3`
- Bazel version (if compiling from source): `-`
- GCC/Compiler version (if compiling from source): `-`
- CUDA/cuDNN version: `-`
- GPU model and memory: `-`

**Describe the current behavior**
The TextVectorization layer `split` parameter expects `None` as a possible value but can't handle it.

**Describe the expected behavior**
The layer should work properly when `None` is passed as a `split` parameter, or documentation should be updated.

**Code to reproduce the issue**
```python
import numpy as np
import tensorflow as tf
from tensorflow.keras.layers.experimental.preprocessing import TextVectorization
from pprint import pprint
assert tf.__version__ == '2.1.0-rc1'

dummy_data = ["Foo", "bar", "foo foo", "foo bar", "foobar."]
predict_data = ["foo", "bar", "foobar", "foo foo", "OOV"]
inputs = tf.keras.layers.Input(shape=(1, ), dtype=tf.string, name="text")
vectorize_layer = TextVectorization(output_mode="binary", max_tokens=5, split=None)
vectorize_layer.adapt(np.asarray(dummy_data))
print(f"Vocabulary:\t\t{vectorize_layer.get_vocabulary()}")
outputs = vectorize_layer(inputs)
model = tf.keras.Model(inputs, outputs)
print(f"Prediction data:\t{predict_data}")
predictions = model.predict(predict_data)
print(f"Predictions:")
pprint(predictions)

AttributeError                            Traceback (most recent call last)
<ipython-input-3-f1a03cb1e414> in <module>()
      9 inputs = tf.keras.layers.Input(shape=(1, ), dtype=tf.string, name="text")
     10 vectorize_layer = TextVectorization(output_mode="binary", max_tokens=5, split=None)
---> 11 vectorize_layer.adapt(np.asarray(dummy_data))
     12 print(f"Vocabulary:\t\t{vectorize_layer.get_vocabulary()}")
     13 outputs = vectorize_layer(inputs)

/tensorflow-2.1.0/python3.6/tensorflow_core/python/keras/layers/preprocessing/text_vectorization.py in _to_numpy(self, preprocessed_data)
    334     if isinstance(preprocessed_data, np.ndarray):
    335       return preprocessed_data
    336     return np.array(preprocessed_data.to_list())
AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'to_list'
```

**Comment by ravikyram** [comment]
I have tried on colab with TF version 2.1.0-rc2, 2.2.0-dev20200121  and was able to reproduce the issue.Please, find the gist [here](https://colab.sandbox.google.com/gist/ravikyram/c006c43d35583da0a38f75fce1062854/untitled577.ipynb). Thanks!

**Comment by markomernick** [comment]
HI @stefanondisponibile and @ravikyram: we have fixed this at HEAD internally (we changed how the layer performs adapt() by deferring to internal sublayers) and I have verified your code snippet functions as expected. I believe these changes should be in the nightly, if not now then very shortly.

**Comment by jvishnuvardhan** [comment]
@stefanondisponibile This was resolved in recent `tf-nightly`. PTAL at the [gist here](https://colab.research.google.com/gist/jvishnuvardhan/444f44c8ce3d736ae470d994626ce1e5/untitled577.ipynb).

Please verify once and close the issue if this was resolved for you. Thanks!

**Comment by stefanondisponibile** [comment]
Looks good to me!
