### ISSUE TITLE
Subclassed tf.keras.Model always in training mode

### ISSUE THREAD

**Issue by marius-sm** [tensorflow/tensorflow#36073]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: no
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): v1.14.0-rc1-22-gaf24dc91b5 1.14.0
- Python version: 3.6.8
- Bazel version (if compiling from source): -
- GCC/Compiler version (if compiling from source): -
- CUDA/cuDNN version: 10.2
- GPU model and memory: P100 16GB

**Describe the current behavior**

As per the [docs](https://github.com/tensorflow/docs/blob/r1.14/site/en/api_docs/python/tf/keras/models/Model.md)

> If you subclass `Model`, you can optionally have a `training` argument (boolean) in `call`, which you can use to specify a different behavior in training and inference

So I expect the dropout in MyModel to affect the result when training.

But this script outputs 
```
Predicting :
[[1.]]
Training :
1.0
```

**Describe the expected behavior**

It should output
```
Predicting :
[[1.]]
Training :
0.5
```

**Code to reproduce the issue**

```python
import tensorflow as tf
import numpy as np

class MyModel(tf.keras.Model):

  def __init__(self):

    super(MyModel, self).__init__()

    self.dense = tf.keras.layers.Dense(100, kernel_initializer="ones", trainable=False)
    self.dropout = tf.keras.layers.Dropout(0.5)


  def call(self, inputs, training=False):

    x = self.dense(inputs)

    if training:
      x = self.dropout(x, training=training)

    x = tf.reshape(tf.reduce_sum(x)/100., [1, 1]) # If we dont reshape, we get RuntimeError: Attempted to aggregate unsupported object 1.0.
    
    return x

model = MyModel()

def loss(y_true, y_pred):
    return y_pred

model.compile(optimizer="sgd", loss=loss)

x = np.ones((1, 1), dtype=np.float32)

print("Predicting :")
print(model.predict(x)) # No dropout, output is 1 as expected

print("Training :")
print(model.train_on_batch(x)) # dropout should put half of the activations of model.dense to 0, so I expect this value to be 0.5
```

**Comment by ravikyram** [comment]
I have tried on colab with TF version 1.14, 1.15 and was able to reproduce the issue.Please, find the gist [here](https://colab.sandbox.google.com/gist/ravikyram/26a02592151fb81a7fdf9b8625377a97/untitled578.ipynb). Thanks!

**Comment by qlzh727** [comment]
The code actually runs correctly, and I think you have a misunderstanding of dropout.

If you change your model body to do:
```
  def call(self, inputs, training=False):
    if training:
      return x + 1
    else:
      return x + 2

x = np.ones((1, 1), dtype=np.float32)
model.predict(x)
model.train_on_batch(x, x)
```
The model will correctly output 3 for predict, and 2 for train.

Your original expectation for dropout is not correct since dropout will scale up the unmasked value to maintain the numerical mean value. See https://stats.stackexchange.com/questions/205932/dropout-scaling-the-activation-versus-inverting-the-dropout for more details about the math.

**Comment by marius-sm** [comment]
I did not know that, thank you ! I think it would be nice to mention that in the docs though.
