### ISSUE TITLE
Migration issue make_one_shot_iterator

### ISSUE THREAD

**Issue by shuklakirti** [tensorflow/tensorflow#36077]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version (use command below):
- Python version:
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
**ValueError: For performance reasons Keras `fit`, `evaluate` and`predict` accept tf.data `Datasets` as input but not iterators that have been manually generated from Datasets by users. Please directly pass in the original `Dataset` object instead of passing in `iter(dataset)`.**

**Describe the expected behavior**

**Code to reproduce the issue**

Trying to migrate the code from tensorflow 1.10 to tensorflow 2.0. using  
**import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()**

if train_obj.if_validate:
            tr_history = model.fit(tf.data.make_one_shot_iterator(tr_dataset), epochs=self.epochs, callbacks=callbacks, steps_per_epoch=self.steps_per_epoch, validation_data=tf.data.make_one_shot_iterator(val_dataset), validation_steps=self.validation_steps)
        else:
            tr_history = model.fit(tr_dataset.make_one_shot_iterator(), epochs=self.epochs, callbacks=callbacks, steps_per_epoch=self.steps_per_epoch)
        
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

Since I'm importing tensorflow.compat.v1 as tf and disabling v2 behaviour. Why am I still not able to use make_one_shot_iterator?

**Comment by gadagashwini** [comment]
@shuklakirti, Please follow the instructions mentioned in this [document](https://www.tensorflow.org/guide/migrate) to migrate from Tf1 to Tf2. Thanks

**Comment by shuklakirti** [comment]
@gadagashwini Thank you for replying.
The document says 
"**It is still possible to run 1.X code, unmodified (except for contrib), in TensorFlow 2.0 import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

If your code works in TensorFlow 2.0 using tf.compat.v1.disable_v2_behavior(), there are still global behavioral changes you may need to address. The major changes are:

Eager execution, v1.enable_eager_execution()t.
Resource variables, v1.enable_resource_variables():
Tensor shapes, v1.enable_v2_tensorshape()
Control flow, v1.enable_control_flow_v2()**  "

I'm not able to use make_one_shot_iterator since Keras accept tf.data Datasets as input but not iterators. How can I make it work?
Passing in the original Dataset object is also not working.

**Comment by shuklakirti** [comment]
Hi
**Update on the issue: AttributeError: 'DatasetV1Adapter' object has no attribute shape**
When I changed the code to
        if train_obj.if_validate:
            tr_history = model.fit(tr_dataset, epochs=self.epochs, callbacks=callbacks, steps_per_epoch=self.steps_per_epoch, validation_data=val_dataset, validation_steps=self.validation_steps)

Traceback (most recent call last):

  File , line 711, in <module>
    run_fn(model_name, model_path, data_path + '/model/params.json', data_path + '/experiment/params.json')

  File, line 613, in run_fn
    acc = run_obj.train_and_test(model_name,multi_gpu=True)

  File , line 236, in train_and_test
    train_obj.multi_gpu_train(train_data_obj, parallel_model, compile_train_model)

  File, line 313, in multi_gpu_train
    tr_history = model.fit(tr_dataset, epochs=self.epochs, callbacks=callbacks, steps_per_epoch=self.steps_per_epoch, validation_data=val_dataset, validation_steps=self.validation_steps)

  File, line 728, in fit
    use_multiprocessing=use_multiprocessing)

  File, line 792, in fit
    steps_name='steps_per_epoch')

  File, line 144, in model_iteration
    shuffle=shuffle)

  File , line 477, in convert_to_generator_like
    num_samples = int(nest.flatten(data)[0].shape[0])

AttributeError: 'DatasetV1Adapter' object has no attribute 'shape'

**Comment by gadagashwini** [comment]
@shuklakirti, Could you provide the minimal code snippet to replicate the reported issue. Thanks!

**Comment by gadagashwini** [comment]
@shuklakirti. Provide the minimal code snippet to analyze the issue. Thanks

**Comment by shuklakirti** [comment]
Hey. Thanks, closing the issue.
