### ISSUE TITLE
sklearn requires KerasRegressor/KerasClassifier to have _estimator_type set

### ISSUE THREAD

**Issue by oxqfsyef** [tensorflow/tensorflow#36074]
Various sklearn functions validate _estimator_type. This in the respective constructors fixes that:

KerasRegressor:
`self._estimator_type = 'regressor'`

KerasClassifier:
`self._estimator_type = 'classifier'`

**Comment by gadagashwini** [comment]
@oxqfsyef, 
can you elaborate the issue with the code snippet and error log.  
Also provide the tensorflow version. Thanks!

**Comment by oxqfsyef** [comment]
Tensorflow version is 1.14.0
`
from tensorflow.keras.wrappers.scikit_learn import KerasRegressor
from sklearn.ensemble import VotingRegressor
a = VotingRegressor([('x', KerasRegressor(lambda: None))])
a.fit([[1,2]], [3])
`
> Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "~/.conda/envs/tensorflow-gpu_1.14.0/lib/python3.7/site-packages/sklearn/ensemble/_voting.py", line 406, in fit
    return super().fit(X, y, sample_weight)
  File "~/.conda/envs/tensorflow-gpu_1.14.0/lib/python3.7/site-packages/sklearn/ensemble/_voting.py", line 57, in fit
    names, clfs = self._validate_estimators()
  File "~/.conda/envs/tensorflow-gpu_1.14.0/lib/python3.7/site-packages/sklearn/ensemble/_base.py", line 251, in _validate_estimators
    est.__class__.__name__, is_estimator_type.__name__[3:]
ValueError: The estimator KerasRegressor should be a regressor.

**Comment by gadagashwini** [comment]
Was able to reproduce the issue with Tf 1.14. and Tf 2.1 on colab.
Please find the gist [here](https://colab.research.google.com/drive/1FL9NrRyn4iiVXUSHZqRqXeXqJAlMUq4E?usp=sharing). Tha

**Comment by ymodak** [comment]
The `build_fn` in `tf.keras.wrappers.scikit_learn.KerasRegressor` should return a `keras model` which can be used on `fit/predict` method downstream.
See https://github.com/tensorflow/tensorflow/blob/cf7fcf164c9846502b21cebb7d3d5ccf6cb626e8/tensorflow/python/keras/wrappers/scikit_learn.py#L43

**Comment by adriangb** [comment]
@oxqfsyef Please check out this wrapper package, I think it should fix your issue: https://pypi.org/project/scikeras/
https://github.com/adriangb/scikeras
