### ISSUE TITLE
[Speech Commands] export function playRawAudio() no bit depth is set.

### ISSUE THREAD

**Issue by mcwebdev** [tensorflow/tensorflow#36078]
**System information**
-  stock example script provided in TensorFlow `tfjs/SpeechCommands`
- Windows 10
- Mobile device N/A
- TensorFlow installed from (source):
- TensorFlow version (use command below): Latest
- Python version: N/A
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: N/A
- GPU model and memory: sli gtx

**Describe the current behavior**
Current playback of captured speech command produces audible degradation. Setting breakpoints on `export function playRawAudio()` indicates a sample rate of `44100` which is good but I am not seeing the bit depth set anywhere. The playback seems to be using a very low bit depth 8bit? 

**Describe the expected behavior**
The expected behavior should play back recorded audio sample with clarity, changing the bit depth to 16, 24 or 32 bit float would be ideal.

**Code to reproduce the issue**
**browser_fft_utils.ts**

```
export function playRawAudio(
    rawAudio: RawAudioData, onEnded: () => void|Promise<void>): void {
  const audioContextConstructor =
      // tslint:disable-next-line:no-any
      (window as any).AudioContext || (window as any).webkitAudioContext;
  const audioContext: AudioContext = new audioContextConstructor();
  const arrayBuffer =
      audioContext.createBuffer(1, rawAudio.data.length, rawAudio.sampleRateHz);
  const nowBuffering = arrayBuffer.getChannelData(0);
  nowBuffering.set(rawAudio.data);
  const source = audioContext.createBufferSource();
  source.buffer = arrayBuffer;
  source.connect(audioContext.destination);
  source.start();
  source.onended = () => {
    if (onEnded != null) {
      onEnded();
    }
  };

```

**Other info / logs**
https://en.wikipedia.org/wiki/Audio_bit_depth

**Comment by ravikyram** [comment]
@mcwebdev 

Hi, This is a TF.js issue . Kindly raise a new issue in TF.js repo using this [link](https://github.com/tensorflow/tfjs/issues/new).Thanks!

**Comment by ravikyram** [comment]
@mcwebdev 

Hope you have raised the issue in TF.js repo. Can we track the issue in TF.js repo and close here. Please, confirm. Thanks!

**Comment by mcwebdev** [comment]
This issue can be closed, further analysis revealed the bit depth being set correctly. It seems the duration multiplier was the culprit. I think I will change that label to reflect `playback speed` in my app.

**Comment by ravikyram** [comment]
@mcwebdev 

Glad to know that you have found workaround for this issue. I am closing the issue .Thanks for the confirmation.
