### ISSUE TITLE
Update the documentation link to the TFLITE conversion commands 

### ISSUE THREAD

**Issue by Marwen-Bhj** [tensorflow/tensorflow#36099]
https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/toco

Tflite converter is missing the usage documentation exmaple links :
[link 1](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/g3doc/convert/cmdline_reference.md)
[link 2](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/g3doc/convert/cmdline_examples.md)

the flags are needed to run such command : 

```
bazel run --config=opt tensorflow/lite/toco:toco -- \
--input_file=$OUTPUT_DIR/tflite_graph.pb \
--output_file=$OUTPUT_DIR/detect.tflite \
--input_shapes=1,300,300,3 \
--input_arrays=normalized_input_image_tensor \
--output_arrays='TFLite_Detection_PostProcess','TFLite_Detection_PostProcess:1','TFLite_Detection_PostProcess:2','TFLite_Detection_PostProcess:3'  \
--inference_type=FLOAT \
--allow_custom_ops
```

Please update the links or some one points me at the file that contains these flags to investigate more other possibilities and methods.

**Comment by ymodak** [comment]
Thanks for the report. Meanwhile you may refer those links from the website.
See https://www.tensorflow.org/lite/convert

**Comment by maxence-drouhin** [comment]
Hi. Would like to contribute. How can i get write access right? Thanks

**Comment by lamberta** [comment]
Thanks. Please submit a pull request to the repo and someone will review. See the TF contributor guide for instructions: https://www.tensorflow.org/community/contribute
