### ISSUE TITLE
SlurmClusterResolver should use env variables ob job step and return correct num_accelerators

### ISSUE THREAD

**Issue by Flamefire** [tensorflow/tensorflow#36094]
The [SlurmClusterResolver](https://github.com/tensorflow/tensorflow/blob/96d0f42d1b236d21157d32805d4aa87e136083b3/tensorflow/python/distribute/cluster_resolver/slurm_cluster_resolver.py) has a few issues:

- `num_accelerators` returns the GPUs per **node**  although they should be per ** task** according to usage
- It uses scontrol which may not return the correct values (see next point)
- Slurm job steps might use different configurations than its job. E.g. after allocating 1 task with 10 cpus and gpus one might run a job step with 10 tasks and 1 cpu and gpu each. This is currently ignored leading to wrong behavior

Example: From inside an allocation with 1 task and 1 node the following will print a single hostname each, and not 2 times the same hostname each: `srun --ntasks 2 --cpus-per-task=5 scontrol show hostname`

Proposed fix:
- Use environment variables `SLURM_*` instead of `scontrol`
- When exists, use `SLURM_STEP_*` variables instead of its corresponding job variable. It might even be reasonable to NOT use the job variables at all as it doesn't make sense to run TF in the context of a job and not a job step (difference: after `salloc` or `sbatch` you'll run in the context of a job in a single instance, `srun` from inside such an allocation then starts a step and distributes execution. `srun` can also be used to implicitly call `salloc`)

I have developed a version based on the current cluster resolver which implements the above and uses https://pypi.org/project/python-hostlist to parse the tasks per node (it is possible that slurm allocates 3 tasks on the first node and 2 tasks on the second when allocating 5 tasks) and expanding the hostlist (the format used is something like `[n1-n3, n5]`.   

In the current version it makes heavy use of default values so it is possible to simply create an instance of `SlurmClusterResolver` with **no** arguments and it will fill out everything from the environment of the current job step or job. The goal was to relieve users from any fiddling with information available already and just use e.g. `MultiWorkerMirroredStrategy`

Is there interest in reviewing and accepting a PR with my improved version?

**Comment by frankchn** [comment]
@Flamefire, thanks for the bug report. I am happy to review your PR, so just create one and assign it to me. Thanks!

**Comment by Flamefire** [comment]
Ok I opened a PR with the class itself. I'll change the tests once the general approach is accepted. I don't see why it won't but I don't want to waste time if something significant needs changing.

**Comment by AngelBerihuete** [comment]
Dear @Flamefire and @frankchn 

I can login to a Slurm cluster with several nodes and 4GPUs per node. I want to do inference using distribute training (MirroredStrategy), but I do not how to see two or more modes resources. Can you share some example on using tf.distribute.cluster_resolver.SlurmClusterResolver? 

Best regards

**Comment by Flamefire** [comment]
Issue resolved by https://github.com/tensorflow/tensorflow/pull/36159

@AngelBerihuete 

You need a Strategy that accepts a `cluster_resolver` argument and when you want MultiNode you want `MultiWorkerMirroredStrategy`. For Slurm you can copy the SlurmClusterResolver from #36159 when you are using TF < 2.2 (or wait for its release)

For TF < 2.2 there is also bug #36550 which requires you to use:

```
def set_tf_config(resolver, environment=None):
    """Set the TF_CONFIG env variable from the given cluster resolver"""
    cfg = {
        'cluster': resolver.cluster_spec().as_dict(),
        'task': {
            'type': resolver.get_task_info()[0],
            'index': resolver.get_task_info()[1],
        },
        'rpc_layer': resolver.rpc_layer,
    }
    if environment:
        cfg['environment'] = environment
    os.environ['TF_CONFIG'] = json.dumps(cfg)
```

So full example of that part:

```
    resolver = SlurmClusterResolver()
    set_tf_config(resolver)
    strategy = tf.distribute.experimental.MultiWorkerMirroredStrategy(cluster_resolver=resolver)
    with strategy.scope():
        # Load and compile model and data
```

See https://www.tensorflow.org/tutorials/distribute/multi_worker_with_keras for more. Most importantly you need the `steps_per_epoch` parameter if you want to use `model.fit`

**Comment by AngelBerihuete** [comment]
Hi @Flamefire! Many thanks.

The example you share yesterday did not have errors, but the behavior was not as I expected:

```bash
== Starting run at Tue Apr  7 12:35:29 CEST 2020
== Job ID: 3965827
== Job NPROCS: 2
== Job NNODES: 2
== Node list: p9r2n[01,09]

TF version:  2.1.0
TFP version:  0.9.0
Number of devices to do Multi Worker Mirrored Strategy: 8
TF version:  2.1.0
TFP version:  0.9.0
Number of devices to do Multi Worker Mirrored Strategy: 8

```
And I expect only one execution, not two. 

```bash
TF version:  2.1.0
TFP version:  0.9.0
Number of devices to do Multi Worker Mirrored Strategy: 8

```
This is the slurm file 

```bash 
#!/bin/bash

#------- job description -------

#SBATCH --job-name='MultiWorker_test'
#SBATCH --qos=debug

#------- setup -------
# In order to use GPUs devices on BSC it
# is mandatory to allocate 40 CPUs per GPU
# requested.
# You specify the gres configuration PER-NODE
# for a job with the --gres flag and a number
# of GPUs. For instance, --gres=gpu:4, we will
# request four GPUs per node (maximun GPUs per
# node in this machine (CTE-POWER at BSC).
# Then, if also you set --node=2, you'll request
# 2*4 GPUs, and --ntasks=2*4*40=320


#SBATCH --nodes=2
#SBATCH --ntasks=2
#SBATCH --cpus-per-task=160
#SBATCH --gres=gpu:4
#SBATCH --time=00:05:00

#------- I/O -------

#SBATCH -D .
#SBATCH --output=TF2_%j.out
#SBATCH --error=TF2_%j.err

#------- load modules  -------

module purge

module load gcc/8.3.0 cuda/10.1 cudnn/7.6.4 nccl/2.4.8 tensorrt/6.0.1
openmpi/4.0.1 atlas/3.10.3 scalapack/2.0.2 fftw/3.3.8 szip/2.1.1
ffmpeg/4.2.1 opencv/4.1.1 python/3.7.4_ML

echo "== Starting run at $(date)"
echo "== Job ID: ${SLURM_JOBID}"
echo "== Job NPROCS: ${SLURM_NPROCS}"
echo "== Job NNODES: ${SLURM_NNODES}"
echo "== Node list: ${SLURM_NODELIST}"
echo "== Submit dir. : ${SLURM_SUBMIT_DIR}"

#------- Comando ------
srun python test_setup_slurm_multiple_node.py

```
and this is test_setup_slurm_multiple_node.py

```python
from __future__ import absolute_import, division, print_function,
unicode_literals

from slurm_cluster_resolver import SlurmClusterResolver
import os
import json
import sys


import tensorflow as tf
import tensorflow_probability as tfp
print("TF version: ", tf.__version__)
print("TFP version: ", tfp.__version__)

def set_tf_config(resolver, environment=None):
    """Set the TF_CONFIG env variable from the given cluster resolver"""
    cfg = {
        'cluster': resolver.cluster_spec().as_dict(),
        'task': {
            'type': resolver.get_task_info()[0],
            'index': resolver.get_task_info()[1],
        },
        'rpc_layer': resolver.rpc_layer,
    }
    if environment:
        cfg['environment'] = environment
    os.environ['TF_CONFIG'] = json.dumps(cfg)


resolver = SlurmClusterResolver()
set_tf_config(resolver)

strategy =
tf.distribute.experimental.MultiWorkerMirroredStrategy(cluster_resolver=resolver)


print ('Number of devices to do Multi Worker Mirrored Strategy:
{}'.format(strategy.num_replicas_in_sync))
```
One of the solutions given by the cluster support team is to do a ```salloc``` and then ```python  test_setup_slurm_multiple_node.py```. Are you agree?

**Comment by Flamefire** [comment]
No. Obviously you run 2 applications as is usual with slurm/MPI in general. That is the whole idea of "MultiWorker". The strategy will make those communicate with each other.

**Comment by AngelBerihuete** [comment]
Got it! Many thanks @Flamefire !
