### ISSUE TITLE
Performance problems with tf.nn.embedding_lookup in eager mode

### ISSUE THREAD

**Issue by jjedele** [tensorflow/tensorflow#36096]
**System information**
- Have I written custom code: Yes - I condensed it to a self-contained example and attach it to the issue.
- OS Platform and Distribution: Ubuntu 18.04.3 LTS
- TensorFlow installed from: binary (pip)
- TensorFlow version: 2.0.0
- Python version: 3.6.8
- CUDA/cuDNN version: CPU only
- GPU model and memory: CPU only

**Describe the current behavior**
tf.nn.embedding_lookup with eager mode enabled is so slow for me that it is practically unusable. Falling back to Numpy is faster by an order of magnitude.

**Describe the expected behavior**
The embedding lookup should perform well enough to be used. Or the information on how to use it properly should be improved.

**Code to reproduce the issue**
Below is my benchmarking code. It simulates a static word2vec (3M, 300d) lookup with artificial data under different configurations. I use a static document length of 500 tokens which I found to be the average of my dataset (OpenWebText sample).
[tf-embedding-benchmark.zip](https://github.com/tensorflow/tensorflow/files/4090909/tf-embedding-benchmark.zip)

**Other info / logs**
Below is a plot of my benchmarks. I did the benchmarks with little data and therefore there's a bit of variance in the charts. I'm currently running them with some more data, but it takes time because it is so slow. As far I can tell already, the results do not look significantly different though. `embedding_type` refers to the embedding lookup: `numpy` means Numpy indexing using `tf.py_func`. The TensorFlow variants refer to the underlying embedding data structure: `tf.constant` and `tf.Variable` with and without the `trainable` flag set.

![embedding_lookup_bm](https://user-images.githubusercontent.com/779877/72803346-2be89580-3c4e-11ea-9fd7-c0a4a5525eeb.png)

**Comment by jjedele** [comment]
Update: Benchmarks with more data:

![embedding_lookup_bm](https://user-images.githubusercontent.com/779877/72892866-ea242180-3d17-11ea-8394-f4873f2f7a14.png)

**Comment by jjedele** [comment]
I would also be interested where the strong peak around a batch size of 50 comes from.

**Comment by amahendrakar** [comment]
@jjedele,
Could you please update TensorFlow to the latest stable version v2.4 and check if you are facing the same issue. Thanks!

**Comment by jjedele** [comment]
@amahendrakar , sorry, in the meantime I do not have access to the system anymore. We worked around the problem back then. We can close the issue since apparently it's not something other people ran into.

**Comment by amahendrakar** [comment]
@jjedele,
Thank you for the update. Closing this issue, please feel free to re-open if necessary.
