### ISSUE TITLE
wget ...mnist/input_data.py from tensorflow.googlesource.com results in jargon

### ISSUE THREAD

**Issue by gakera** [tensorflow/tensorflow#361]
`wget https://tensorflow.googlesource.com/tensorflow/+/master/tensorflow/g3doc/tutorials/mnist/input_data.py` 
result is html formatted, unusable. 

`wget https://tensorflow.googlesource.com/tensorflow/+/master/tensorflow/g3doc/tutorials/mnist/input_data.py?format=TEXT` 
results in jargon, unusable. 

`wget https://github.com/tensorflow/tensorflow/raw/master/tensorflow/g3doc/tutorials/mnist/input_data.py`
works

**Comment by vrv** [comment]
Sadly, nothing we can do.  https://code.google.com/p/gitiles/issues/detail?id=7 seems relevant.
