### ISSUE TITLE
TFTRT not converting dilated convolutions

### ISSUE THREAD

**Issue by fferroni** [tensorflow/tensorflow#36109]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): pip
- TensorFlow version (use command below): 1.15
- Python version: 3.6
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 10, 7
- TensorRT: 5
- GPU model and memory:

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`
1.15.0

**Describe the current behavior**
TFTRT skips dilated convolutions and gives leaves this in the output. Other convolutions work fine.

This is what it looks like in Tensorboard: 
![dilated_convolution](https://user-images.githubusercontent.com/16327442/72840584-da172e00-3c94-11ea-9068-4c6c93b80c18.png)

It appears that there are some BatchToSpaceND and SpaceToBatchND operations. Perhaps these are not supported?

**Describe the expected behavior**

Based on the PR that was merged into Tensorflow in January last year (TFTRT: Support Dilated Convolutions #24674) I would expect that converting a convolution with dilations would be supported. Instead it's not... I tried dilation rates of 2, 8, 16...

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

```
from tensorflow.python.compiler.tensorrt import trt_convert as trt

import tensorflow as tf

inp = tf.keras.layers.Input(input=(400, 400, 3))
x = tf.keras.layers.Conv2D(8, kernel_size=(3,3), strides=(1,1), dilation_rate=(16,16))(inp)
model = tf.keras.models.Model(inp, x) 

sess = tf.keras.backend.get_session()

output_nodes = [n.name[:-2] for n in model.outputs]

graph_def = tf.graph_util.convert_variables_to_constants(sess, sess.graph.as_graph_def(), output_nodes)

converter = trt.TrtGraphConverter(input_graph_def=graph_def,
                                              nodes_blacklist=model.outputs,
                                              precision_mode="FP32",
                                              max_batch_size=1,
                                              minimum_segment_size=1,
                                              max_workspace_size_bytes=(2048>>20),
                                              use_calibration=True)
calib_graph = converter.convert()

with tf.gfile.GFile("model.trt.pbtxt", "w") as f:
        f.write(str(calib_graph))
```

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by fferroni** [comment]
Any updates?

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.
