### ISSUE TITLE
Tensorflow install breaks curl on Ubuntu

### ISSUE THREAD

**Issue by John-Nagle** [tensorflow/tensorflow#36107]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04 LTS
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version: 1.15
- Python version: 3.6.7
- Installed using virtualenv? pip? conda?: Virtualenv/pip
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory: NVidia 640

**Describe the problem**

Rasa install of Tensorflow 1.15 causes a Ubuntu dependency error which prevents "curl" from installing, which silently breaks the iDrive backup system.

The underlying problem seems to be that Tensorflow tries to build a modified "curl" with support for some Google remote file system. See this Tensorflow mod to Curl:

https://github.com/tensorflow/tensorflow/commit/bb890ea5fa4c8a2100a295e93c5bf37b3c88b55a

That would be fine if the modified "curl" was private to the Tensorflow environment, but somehow the nonstandard version of "curl" or "libcurl" got installed in the Ubuntu system. This broke the Ubuntu package dependency system, and now a standard "curl" cannot be installed. This, in turn, broke things which depend on "curl" being present, such as iDrive backups. 

Details here: https://ubuntuforums.org/showthread.php?t=2435412

Also see: https://github.com/RasaHQ/rasa/issues/5104

**Comment by gunan** [comment]
What do you mean by "rasa install"?
Standard tensorflow pip package installations should have no interactions with curl/libcurl.

**Comment by gunan** [comment]
Closing because this is an unsupported installation method/environment for TF.
This is likely due to the installer/environment.
