### ISSUE TITLE
Make TensorFlow build with system packages

### ISSUE THREAD

**Issue by Flamefire** [tensorflow/tensorflow#36127]
We want to control what versions of libraries are getting used on our cluster. TF using included and downloaded stuff is a misbehavor.

Is it possible to get a list of dependencies and whether the system version is used/found?

Can we interactively pass some arguments and have it use the system versions with TF showing if it does before running the build?

Examples that I've seen are zlib and protobuf with the protoc.

We are using a Github release and running `./configure && bazel <...>` with lots of TF_NEED_* and *_PATH variables already set.

**Comment by gadagashwini** [comment]
@Flamefire,
Get all the Tensorflow dependencies list from [setup.py](https://github.com/tensorflow/tensorflow/blob/5d5db2835967694ce4af95ce9c32cf0298ecef6e/tensorflow/tools/pip_package/setup.py) file. You can control the dependencies from this py file. Thanks!
