### ISSUE TITLE
ERROR: intel-tensorflow has an invalid wheel

### ISSUE THREAD

**Issue by djstrong** [tensorflow/tensorflow#36123]
Are you maintaining intel-tensorflow?

With pip 20.0.1:
```
$ pip install intel-tensorflow
Collecting intel-tensorflow
  Downloading intel_tensorflow-2.0.0-cp36-cp36m-manylinux2010_x86_64.whl (133.7 MB)
     |████████████████████████████████| 133.7 MB 53.8 MB/s 
ERROR: intel-tensorflow has an invalid wheel, multiple .dist-info directories found: intel_tensorflow-2.0.0.dist-info, tensorflow-2.0.0.dist-info
```
I guess the error is related to new pip.

**Comment by mihaimaruseac** [comment]
We are not maintaining that wheel, I think this should be redirected to Intel.

**Comment by oanush** [comment]
@djstrong ,
Can you please check @mihaimaruseac  update on this and redirect to Intel?thanks!

**Comment by djstrong** [comment]
Unfortunately, I can't find contact information to Intel.

**Comment by preethivenkatesh** [comment]
yeah, this is a known issue with pip 20* versions and we will fix it in the next release. the install will work on versions 19 and before.

**Comment by chuanqi129** [comment]
Hi @djstrong, we have released intel-tensorflow 2.0.1 to fix the multiple .dist-info dirs in wheels, please have a try on it. Thanks.

**Comment by Jianhui-Li** [comment]
@penpornk

**Comment by penpornk** [comment]
@Jianhui-Li Thank you!
@chuanqi129 intel-tensorflow 2.0.1 seems to only be available on `pip3`. Do you plan on adding it to `pip`, or have you discontinued Python 2 support? Just for my information. Thank you!

@djstrong I have verified that `pip3 install intel-tensorflow==2.0.1` works. Please let us know if this works for you. Thank you!

**Comment by chuanqi129** [comment]
Thanks @penpornk for your verification. Yes, we have discontinued Python 2 support.

**Comment by NeoZhangJianyu** [comment]
@djstrong Have your issue disappeared? If yes, could you close it?

**Comment by djstrong** [comment]
Yes, thank you!

**Comment by luchangli03** [comment]
pip install pip==19 solves this problem
