### ISSUE TITLE
Code will not compile Image classification

### ISSUE THREAD

**Issue by blyscuit** [tensorflow/tensorflow#36122]
https://www.tensorflow.org/tutorials/images/classification

### Clear description

There's a bug in code

`history = model.fit_generator(
    train_data_gen,
    steps_per_epoch=total_train // batch_size,
    epochs=epochs,
    validation_data=val_data_gen,
    validation_steps=total_val // batch_size
)`

where
`    steps_per_epoch=total_train // batch_size,
`
will not compile because the , is behind the comment. The correct code should be
`history = model.fit_generator(
    train_data_gen,
    steps_per_epoch=total_train, // batch_size
    epochs=epochs,
    validation_data=val_data_gen,
    validation_steps=total_val // batch_size
)`

**Comment by rushabh-v** [comment]
@blyscuit `total_train // batch_size` is integer devision of `total_train` and `batch_size`.
In python 3, `a / b` is floating point devision and `a // b` is integer devision :)
