### ISSUE TITLE
Build Tensorflow 2.0 error (CUDA 10.1, Windows 10, conda)

### ISSUE THREAD

**Issue by juskuz** [tensorflow/tensorflow#36132]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): source
- TensorFlow version: 2.0.0
- Python version: 3.7.6 (conda)
- Installed using virtualenv? pip? conda?: conda
- Bazel version (if compiling from source): 0.26.1
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: 10.1/ 7.6
- GPU model and memory: GeForce GTX 1660 Ti (6GB)
- Procesor: Intel Core i7 9th Generation (AVX2 support)

**Describe the problem**
I need tensorflow==2.0.0 to use with https://github.com/matterport/Mask_RCNN/pull/1896. (Or fix that pull request to run on my computer).
I couldn't use the official binaries due to CUDA version (I have 10.1 but tf 2.0 needs CUDA 10.0). I can't downgrade it (GPU driver is 10.1 or 10.2). I found https://github.com/tensorflow/tensorflow/issues/33026 issue and there was advice about building tf from source (https://github.com/tensorflow/tensorflow/issues/33026#issuecomment-539915647)

**Provide the exact sequence of commands / steps that you executed before running into the problem**

I was running comands from https://medium.com/@amsokol.com/how-to-build-and-install-tensorflow-2-0-1aab4eaa4c1a which is based on official documentation.

Diffs:
* Git for Windows and MSYS2 are installed on C:/ drive directly (so I set system variables properly).
* Python is installed from conda (3.7.6) (path is set correctly)
* instead of venv I'm using conda. Due to recent pip update I don't run pip update (I have 19.3.1 version)
* I set compute capability as 3.5 (there is no official info on nvidia website https://developer.nvidia.com/cuda-gpus though it's Turing series and should be 7.x)

After executing ```bazel build --config=opt --define=no_tensorflow_py_deps=true //tensorflow/tools/pip_package:build_pip_package``` it throws the errors:

```ERROR: An error occurred during the fetch of repository ‘io_bazel_rules_docker’: Traceback (most recent call last): File “C:/users/konta/_bazel_konta/cs3mthex/external/bazel_tools/tools/build_defs/repo/git.bzl”, line 234 _clone_or_update(ctx) File “C:/users/konta/_bazel_konta/cs3mthex/external/bazel_tools/tools/build_defs/repo/git.bzl”, line 74, in _clone_or_update fail((“error cloning %s:\n%s” % (ctx….))) error cloning io_bazel_rules_docker: java.io.IOException: ERROR: src/main/native/windows/process.cc(179): CreateProcessW(“C:\msys64\usr\bin” -c “ cd C:/users/konta/_bazel_konta/cs3mthex/external set -ex ( cd C:/users/konta/_bazel_konta/cs3mthex/external && if ! ( cd ‘C:/users/konta/_bazel_konta/cs3mthex/externa(…)): Odmowa dost?pu. ERROR: error loading package ‘’: Encountered error while reading extension file ‘repositories/repositories.bzl’: no such package ‘@io_bazel_rules_docker//repositories’: Traceback (most recent call last): File “C:/users/konta/_bazel_konta/cs3mthex/external/bazel_tools/tools/build_defs/repo/git.bzl”, line 234 _clone_or_update(ctx) File “C:/users/konta/_bazel_konta/cs3mthex/external/bazel_tools/tools/build_defs/repo/git.bzl”, line 74, in _clone_or_update fail((“error cloning %s:\n%s” % (ctx….))) error cloning io_bazel_rules_docker: java.io.IOException: ERROR: src/main/native/windows/process.cc(179): CreateProcessW(“C:\msys64\usr\bin” -c “ cd C:/users/konta/_bazel_konta/cs3mthex/external set -ex ( cd C:/users/konta/_bazel_konta/cs3mthex/external && if ! ( cd ‘C:/users/konta/_bazel_konta/cs3mthex/externa(…)): Odmowa dost?pu. ERROR: error loading package ‘’: Encountered error while reading extension file ‘repositories/repositories.bzl’: no such package ‘@io_bazel_rules_docker//repositories’: Traceback (most recent call last): File “C:/users/konta/_bazel_konta/cs3mthex/external/bazel_tools/tools/build_defs/repo/git.bzl”, line 234 _clone_or_update(ctx) File “C:/users/konta/_bazel_konta/cs3mthex/external/bazel_tools/tools/build_defs/repo/git.bzl”, line 74, in _clone_or_update fail((“error cloning %s:\n%s” % (ctx….))) error cloning io_bazel_rules_docker: java.io.IOException: ERROR: src/main/native/windows/process.cc(179): CreateProcessW(“C:\msys64\usr\bin” -c “ cd C:/users/konta/_bazel_konta/cs3mthex/external set -ex ( cd C:/users/konta/_bazel_konta/cs3mthex/external && if ! ( cd ‘C:/users/konta/_bazel_konta/cs3mthex/externa(…)): Odmowa dost?pu. INFO: Elapsed time: 0.103s INFO: 0 processes. FAILED: Build did NOT complete successfully (0 packages loaded)```

I found the solution of this here: https://github.com/tensorflow/tensorflow/issues/28824#issuecomment-536669038 - I added these lines to WORKSPACE file in tensorflow directory (tensorflow repo).

It gave me the next errors, so I needed to add also 

```
http_archive(
    name = "com_google_protobuf",
#    build_file = "//:third_party/protobuf.BUILD",
    sha256 = "b9e92f9af8819bbbc514e2902aec860415b70209f31dfc8c4fa72515a5df9d59",
    # This protobuf release is based on protobuf 3.8.0.
    strip_prefix = "protobuf-310ba5ee72661c081129eb878c1bbcec936b20f0",
    urls = [
        "https://storage.googleapis.com/mirror.tensorflow.org/github.com/protocolbuffers/protobuf/archive/310ba5ee72661c081129eb878c1bbcec936b20f0.tar.gz",
        "https://github.com/protocolbuffers/protobuf/archive/310ba5ee72661c081129eb878c1bbcec936b20f0.tar.gz",
    ],
)
```
 to my WORKSPACE file. This fix was working. Now it can't fetch of repository 'png_archive' (see log at the bottom). I tried to comment it in BUILD files but it was causing the next lacks (missing flatbuffers). I have no idea how it can be fixed.

**Any other info / logs**

```Odmowa dost?pu.``` means 'Permission/access denied'. I thought it's caused by Windows Defender or antivirus but it's turned off. I'm using terminal with admin privileges and user access control is set as 'never notify'. Probably there is problem with repos (when I added newer config of com_google_protobuf and  io_bazel_rules_docker there wasn't previous errors).

Full log after running build:
```(tf2.0) C:\Users\konta\Documents\Repos\tf-2.0\tensorflow>bazel build --config=opt --define=no_tensorflow_py_deps=true //tensorflow/tools/pip_package:build_pip_package                                                                          Starting local Bazel server and connecting to it...                                                                     INFO: Options provided by the client:                                                                                     Inherited 'common' options: --isatty=1 --terminal_columns=120                                                         INFO: Options provided by the client:                                                                                     'build' options: --python_path=C:/Users/konta/Miniconda3/envs/tf2.0/python.exe                                        INFO: Reading rc options for 'build' from c:\users\konta\documents\repos\tf-2.0\tensorflow\.bazelrc:                      'build' options: --apple_platform_type=macos --define framework_shared_object=true --define open_source_build=true --define=use_fast_cpp_protos=true --define=allow_oversize_protos=true --spawn_strategy=standalone --strategy=Genrule=standalone -c opt --announce_rc --define=grpc_no_ares=true --define=PREFIX=/usr --define=LIBDIR=$(PREFIX)/lib --define=INCLUDEDIR=$(PREFIX)/include --config=v2                                                                                       INFO: Reading rc options for 'build' from c:\users\konta\documents\repos\tf-2.0\tensorflow\.tf_configure.bazelrc:         'build' options: --action_env PYTHON_BIN_PATH=C:/Users/konta/Miniconda3/envs/tf2.0/python.exe --action_env PYTHON_LIB_PATH=C:/Users/konta/Miniconda3/envs/tf2.0/lib/site-packages --python_path=C:/Users/konta/Miniconda3/envs/tf2.0/python.exe --action_env CUDA_TOOLKIT_PATH=C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.1 --action_env TF_CUDA_COMPUTE_CAPABILITIES=3.5 --config=cuda --config monolithic --copt=-w --host_copt=-w --copt=-DWIN32_LEAN_AND_MEAN --host_copt=-DWIN32_LEAN_AND_MEAN --copt=-DNOGDI --host_copt=-DNOGDI --verbose_failures --distinct_host_configuration=false --define=override_eigen_strong_inline=true --action_env TF_CONFIGURE_IOS=0                                                          INFO: Found applicable config definition build:v2 in file c:\users\konta\documents\repos\tf-2.0\tensorflow\.bazelrc: --define=tf_api_version=2                                                                                                  INFO: Found applicable config definition build:cuda in file c:\users\konta\documents\repos\tf-2.0\tensorflow\.bazelrc: --config=using_cuda --define=using_cuda_nvcc=true                                                                        INFO: Found applicable config definition build:using_cuda in file c:\users\konta\documents\repos\tf-2.0\tensorflow\.bazelrc: --define=using_cuda=true --action_env TF_NEED_CUDA=1 --crosstool_top=@local_config_cuda//crosstool:toolchain       INFO: Found applicable config definition build:monolithic in file c:\users\konta\documents\repos\tf-2.0\tensorflow\.bazelrc: --define framework_shared_object=false                                                                             INFO: Found applicable config definition build:opt in file c:\users\konta\documents\repos\tf-2.0\tensorflow\.tf_configure.bazelrc: --copt=/arch:AVX2 --define with_default_optimizations=true                                                   INFO: Call stack for the definition of repository 'png_archive' which is a tf_http_archive (rule definition at C:/users/konta/documents/repos/tf-2.0/tensorflow/third_party/repo.bzl:124:19):                                                    - C:/users/konta/documents/repos/tf-2.0/tensorflow/tensorflow/workspace.bzl:260:5                                       - C:/users/konta/documents/repos/tf-2.0/tensorflow/WORKSPACE:38:1                                                      INFO: Repository 'png_archive' used the following cache hits instead of downloading the corresponding file.              * Hash 'ca74a0dace179a8422187671aee97dd3892b53e168627145271cad5b5ac81307' for https://storage.googleapis.com/mirror.tensorflow.org/github.com/glennrp/libpng/archive/v1.6.37.tar.gz                                                            If the definition of 'png_archive' was updated, verify that the hashes were also updated.                               ERROR: An error occurred during the fetch of repository 'png_archive':                                                     Traceback (most recent call last):                                                                                           File "C:/users/konta/documents/repos/tf-2.0/tensorflow/third_party/repo.bzl", line 104                                          _apply_patch(ctx, ctx.attr.patch_file)                                                                          File "C:/users/konta/documents/repos/tf-2.0/tensorflow/third_party/repo.bzl", line 71, in _apply_patch                          _execute_and_check_ret_code(ctx, cmd)                                                                           File "C:/users/konta/documents/repos/tf-2.0/tensorflow/third_party/repo.bzl", line 52, in _execute_and_check_ret_code                                                                                                                                   fail("Non-zero return code({1}) when ...))                                                              Non-zero return code(256) when executing 'C:\msys64\usr\bin -l -c "patch" "-p1" "-d" "C:/users/konta/_bazel_konta/cs3mthex/external/png_archive" "-i" "C:/users/konta/documents/repos/tf-2.0/tensorflow/third_party/png_fix_rpi.patch"':        Stdout:                                                                                                                 Stderr: java.io.IOException: ERROR: src/main/native/windows/process.cc(179): CreateProcessW("C:\msys64\usr\bin" -l -c "\"patch\" \"-p1\" \"-d\" \"C:/users/konta/_bazel_konta/cs3mthex/external/png_archive\" \"-i\" \"C:/users/konta/documents/repos/tf-2.0/tensorflow/third_party/png_fix_rpi(...)): Odmowa dost?pu.                                                  INFO: Call stack for the definition of repository 'flatbuffers' which is a third_party_http_archive (rule definition at C:/users/konta/documents/repos/tf-2.0/tensorflow/third_party/repo.bzl:204:28):                                           - C:/users/konta/documents/repos/tf-2.0/tensorflow/third_party/flatbuffers/workspace.bzl:6:5                            - C:/users/konta/documents/repos/tf-2.0/tensorflow/tensorflow/workspace.bzl:39:5                                        - C:/users/konta/documents/repos/tf-2.0/tensorflow/tensorflow/workspace.bzl:82:5                                        - C:/users/konta/documents/repos/tf-2.0/tensorflow/WORKSPACE:38:1                                                      INFO: Repository 'flatbuffers' used the following cache hits instead of downloading the corresponding file.              * Hash '3f4a286642094f45b1b77228656fbd7ea123964f19502f9ecfd29933fd23a50b' for https://storage.googleapis.com/mirror.tensorflow.org/github.com/google/flatbuffers/archive/v1.11.0.tar.gz                                                        If the definition of 'flatbuffers' was updated, verify that the hashes were also updated.                               INFO: Call stack for the definition of repository 'cython' which is a tf_http_archive (rule definition at C:/users/konta/documents/repos/tf-2.0/tensorflow/third_party/repo.bzl:124:19):                                                         - C:/users/konta/documents/repos/tf-2.0/tensorflow/tensorflow/workspace.bzl:754:5                                       - C:/users/konta/documents/repos/tf-2.0/tensorflow/WORKSPACE:38:1                                                      INFO: Repository 'cython' used the following cache hits instead of downloading the corresponding file.                   * Hash 'bccc9aa050ea02595b2440188813b936eaf345e85fb9692790cecfe095cf91aa' for https://storage.googleapis.com/mirror.tensorflow.org/github.com/cython/cython/archive/0.28.4.tar.gz                                                              If the definition of 'cython' was updated, verify that the hashes were also updated.                                    INFO: Call stack for the definition of repository 'eigen_archive' which is a tf_http_archive (rule definition at C:/users/konta/documents/repos/tf-2.0/tensorflow/third_party/repo.bzl:124:19):                                                  - C:/users/konta/documents/repos/tf-2.0/tensorflow/tensorflow/workspace.bzl:168:5                                       - C:/users/konta/documents/repos/tf-2.0/tensorflow/WORKSPACE:38:1                                                      INFO: Repository 'eigen_archive' used the following cache hits instead of downloading the corresponding file.            * Hash 'f3d69ac773ecaf3602cb940040390d4e71a501bb145ca9e01ce5464cf6d4eb68' for https://storage.googleapis.com/mirror.tensorflow.org/bitbucket.org/eigen/eigen/get/049af2f56331.tar.gz                                                           If the definition of 'eigen_archive' was updated, verify that the hashes were also updated.                             INFO: Call stack for the definition of repository 'icu' which is a third_party_http_archive (rule definition at C:/users/konta/documents/repos/tf-2.0/tensorflow/third_party/repo.bzl:204:28):                                                   - C:/users/konta/documents/repos/tf-2.0/tensorflow/third_party/icu/workspace.bzl:11:5                                   - C:/users/konta/documents/repos/tf-2.0/tensorflow/tensorflow/workspace.bzl:42:5                                        - C:/users/konta/documents/repos/tf-2.0/tensorflow/tensorflow/workspace.bzl:82:5                                        - C:/users/konta/documents/repos/tf-2.0/tensorflow/WORKSPACE:38:1                                                      INFO: Repository 'icu' used the following cache hits instead of downloading the corresponding file.                      * Hash 'e15ffd84606323cbad5515bf9ecdf8061cc3bf80fb883b9e6aa162e485aa9761' for https://storage.googleapis.com/mirror.tensorflow.org/github.com/unicode-org/icu/archive/release-62-1.tar.gz                                                      If the definition of 'icu' was updated, verify that the hashes were also updated.                                       ERROR: C:/users/konta/documents/repos/tf-2.0/tensorflow/tensorflow/tools/pip_package/BUILD:157:1: no such package '@png_archive//': Traceback (most recent call last):                                                                                  File "C:/users/konta/documents/repos/tf-2.0/tensorflow/third_party/repo.bzl", line 104                                          _apply_patch(ctx, ctx.attr.patch_file)                                                                          File "C:/users/konta/documents/repos/tf-2.0/tensorflow/third_party/repo.bzl", line 71, in _apply_patch                          _execute_and_check_ret_code(ctx, cmd)                                                                           File "C:/users/konta/documents/repos/tf-2.0/tensorflow/third_party/repo.bzl", line 52, in _execute_and_check_ret_code                                                                                                                                   fail("Non-zero return code({1}) when ...))                                                              Non-zero return code(256) when executing 'C:\msys64\usr\bin -l -c "patch" "-p1" "-d" "C:/users/konta/_bazel_konta/cs3mthex/external/png_archive" "-i" "C:/users/konta/documents/repos/tf-2.0/tensorflow/third_party/png_fix_rpi.patch"':        Stdout:                                                                                                                 Stderr: java.io.IOException: ERROR: src/main/native/windows/process.cc(179): CreateProcessW("C:\msys64\usr\bin" -l -c "\"patch\" \"-p1\" \"-d\" \"C:/users/konta/_bazel_konta/cs3mthex/external/png_archive\" \"-i\" \"C:/users/konta/documents/repos/tf-2.0/tensorflow/third_party/png_fix_rpi(...)): Odmowa dost?pu.                                                   and referenced by '//tensorflow/tools/pip_package:licenses'                                                            ERROR: Analysis of target '//tensorflow/tools/pip_package:build_pip_package' failed; build aborted: no such package '@png_archive//': Traceback (most recent call last):                                                                                File "C:/users/konta/documents/repos/tf-2.0/tensorflow/third_party/repo.bzl", line 104                                          _apply_patch(ctx, ctx.attr.patch_file)                                                                          File "C:/users/konta/documents/repos/tf-2.0/tensorflow/third_party/repo.bzl", line 71, in _apply_patch                          _execute_and_check_ret_code(ctx, cmd)                                                                           File "C:/users/konta/documents/repos/tf-2.0/tensorflow/third_party/repo.bzl", line 52, in _execute_and_check_ret_code                                                                                                                                   fail("Non-zero return code({1}) when ...))                                                              Non-zero return code(256) when executing 'C:\msys64\usr\bin -l -c "patch" "-p1" "-d" "C:/users/konta/_bazel_konta/cs3mthex/external/png_archive" "-i" "C:/users/konta/documents/repos/tf-2.0/tensorflow/third_party/png_fix_rpi.patch"':        Stdout:                                                                                                                 Stderr: java.io.IOException: ERROR: src/main/native/windows/process.cc(179): CreateProcessW("C:\msys64\usr\bin" -l -c "\"patch\" \"-p1\" \"-d\" \"C:/users/konta/_bazel_konta/cs3mthex/external/png_archive\" \"-i\" \"C:/users/konta/documents/repos/tf-2.0/tensorflow/third_party/png_fix_rpi(...)): Odmowa dost?pu.                                                  INFO: Elapsed time: 92.788s                                                                                             INFO: 0 processes.                                                                                                      FAILED: Build did NOT complete successfully (174 packages loaded, 4346 targets configured)```

**Comment by juskuz** [comment]
I installed tf 2.1.0rc0 and run in python console:

```
>>> import tensorflow as tf 
>>> tf.test.is_built_with_cuda()
True
>>> tf.test.is_gpu_available(cuda_only=False, min_cuda_compute_capability=None)
2020-01-22 15:51:56.474875: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
2020-01-22 15:51:56.497346: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library nvcuda.dll
2020-01-22 15:51:57.671307: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1555] Found device 0 with properties:
pciBusID: 0000:01:00.0 name: GeForce GTX 1660 Ti computeCapability: 7.5
coreClock: 1.455GHz coreCount: 24 deviceMemorySize: 6.00GiB deviceMemoryBandwidth: 268.26GiB/s
2020-01-22 15:51:58.574146: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1241] Created TensorFlow device (/device:GPU:0 with 4625 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1660 Ti, pci bus id: 0000:01:00.0, compute capability: 7.5)
True
```
so __GeForce GTX 1660 Ti computeCapability: 7.5__

**Comment by ahtik** [comment]
Reported compute capability of 7.5 for 1660 Ti is correct.

GeForce GTX 1660 Ti is built on Turing TU116-400-A1 and CUDA reports it's compute capability to be 7.5, although it's one of the very few GPU-s that have 7.5 capability but *do not* have Tensor Cores, go figure... :-)

You can also safely switch now to tf 2.1.0 final, it's built with CUDA 10.1.

If you still want to have fun building from source in Win10, make sure the proper VC version is installed and detected (incl make sure to set TF_VC_VERSION!). At the moment builds should work both with CUDA 10.1 and CUDA 10.0. Couple of hints can be found at https://github.com/tensorflow/tensorflow/issues/33544#issuecomment-577678541

**Comment by juskuz** [comment]
Thanks for answer and hints.
I just tried tf 2.1.0rc0 and it works with MaskRCNN (in contrast to 2.1.0) so building from source is not necessary for me now.

**Comment by gadagashwini** [comment]
@juskuz, Can we close if the issue resolved. Thanks!

**Comment by juskuz** [comment]
I think so. I closed the issue. You can change the stat label
