### ISSUE TITLE
initializer() method has no attribute run()

### ISSUE THREAD

**Issue by adekability** [tensorflow/tensorflow#36133]
**System information**
- Windows 10(x64)
- TensorFlow 2.1.0
- Python 3.7
- CUDA 10.0:
- GPU - NVIDIA GeForce GTX 1660 Ti:
__________________________________________________________________________________________________________

I wanted to repeat some code from book named "Machine Learning with TensorFlow" of Nishant Shukla (@BinRoot)

![Снимок](https://user-images.githubusercontent.com/43477533/72905924-83285c00-3d5b-11ea-81f7-dd8b37468814.PNG)

However there's an error:
`File "C:/Users/PC2/PycharmProjects/Adil/newTensor/Main.py", line 6, in <module>`
`spikes.initializer.run()`
`AttributeError: 'NoneType' object has no attribute 'run'`
__________________________________________________________________________________________________________
**And I would like to know if somebody has faced that before. I tried to reinstall tensorforce but it didn't help. I think it's because of the version update. However I don't know to fix that. I would really appreciate if somebody could help me! Thanks in advance!**

**Comment by gadagashwini** [comment]
@adekability, Issue looks like Tensorflow version incompatibility. 
Please provide the standalone code to replicate the reported issue. Thanks!

**Comment by gadagashwini** [comment]
@adekability, Provide the minimal code snippet to replicate the issue. Thanks!

**Comment by gadagashwini** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
