### ISSUE TITLE
Cannot build TensorFlow from source on Mac OS Catalina

### ISSUE THREAD

**Issue by HarrisonWilde** [tensorflow/tensorflow#36134]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Mac OS Catalina
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): source
- TensorFlow version: 2.0
- Python version: 3.7.6
- Installed using virtualenv? pip? conda?: miniconda
- Bazel version (if compiling from source): Using Bazelisk, so I presume 0.12.1
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

**Describe the problem**
Trying to install TensorFlow from source for CPU only, I encounter this issue after following the install instructions precisely and then using the following code after installing bazelisk with Go.

**Provide the exact sequence of commands / steps that you executed before running into the problem**
```
bazelisk clean --expunge
sudo xcode-select -s /Applications/Xcode.app/Contents/Developer
sudo xcodebuild -license
bazelisk clean --expunge
bazelisk build --config=opt //tensorflow/tools/pip_package:build_pip_package
```

**Any other info / logs**
```
ERROR: /Users/harrisonwilde/python/tensorflow/tensorflow/lite/tools/optimize/calibration/BUILD:106:1: undeclared inclusion(s) in rule '//tensorflow/lite/tools/optimize/calibration:calibration_reader':
this rule is missing dependency declarations for the following files included by 'tensorflow/lite/tools/optimize/calibration/calibration_reader.cc':
  'external/com_google_absl/absl/strings/string_view.h'
  'external/com_google_absl/absl/base/internal/throw_delegate.h'
Target //tensorflow/tools/pip_package:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.
ERROR: /Users/harrisonwilde/python/tensorflow/tensorflow/python/tools/BUILD:80:1 undeclared inclusion(s) in rule '//tensorflow/lite/tools/optimize/calibration:calibration_reader':
this rule is missing dependency declarations for the following files included by 'tensorflow/lite/tools/optimize/calibration/calibration_reader.cc':
  'external/com_google_absl/absl/strings/string_view.h'
  'external/com_google_absl/absl/base/internal/throw_delegate.h'
INFO: Elapsed time: 325.470s, Critical Path: 117.47s
INFO: 1821 processes: 1821 local.
FAILED: Build did NOT complete successfully
```

**Comment by mihaimaruseac** [comment]
Since you are installing from source, can you post the commit hash/branch you are building from?

**Comment by HarrisonWilde** [comment]
Apologies, I actually got this working after trying with the latest release branch, I was initially trying to build master but your comment made me realise I didn't want to do that.

**Comment by zhaozheng09** [comment]
how to solve this problem ?

**Comment by mihaimaruseac** [comment]
@zhaozheng09 please open a new issue and fill in issue template. This issue has been resolved already.
