### ISSUE TITLE
What factors influence training time through distributed strategy?

### ISSUE THREAD

**Issue by ProNoobLi** [tensorflow/tensorflow#36147]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
Ubuntu 16.04
- TensorFlow installed from (source or binary):
Source
- TensorFlow version (use command below):
TF2.1.0
- Python version:
Python3.5
- CUDA/cuDNN version:
cuda10.1
- GPU model and memory:
v100 

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
I tried to get the training time / epoch under [1, 2, 4, 8] GPUs with tf.distribute.MirroredStrategy. However, I got a very interesting result: the time cost is not only linear to the size fo dataset or GPU num, but also influenced by the training loop style, custom training loop or Keras API.
Here is the result table I make. It's not a  serious experiment but hopefully, we could get some inspiration.
![image](https://user-images.githubusercontent.com/33815430/72955745-25862500-3dd8-11ea-9e0f-ea8b00ab28db.png)

Some key points should know beforehand
1. I accumulate and average last 4 epochs out of total 5 epochs, since the first epoch always takes longer than the rest of epochs. 
2. loading styles are two: tfds.load() and the TFrecords loading recommended by tensorflow.
3. For TFrecords loading style, I first converted original images into TFrecords files, and then using TFRecords loading.
4. I promise shards number of TFrecords, global_total_batch_size, loading style don't affect training time greatly.
5. I downloaded the original datasets of tf_flowers to my disk. The meaning of _n_ in tf_flowers * n are the times I copied and pasted.  The only purpose is to enlarge the size of the dataset.
6. Please look at the rows of tf_fowers*n. With the size of the tf_flowers doubles, training time doubles with all GPU numbers. It makes sense and is same with our expectation.
7. However, changing the dataset from tf_flowers to 10k dogs(my datasets including 10k dogs of 10 classes), but keep an equivalent size. The time doesn't change as expects. 
tf_flowers*8 and 10k dogs are in similar size but tf_flowers*8 takes 3 times longer than 10k dogs
tf_flowers*20 and 10k dogs*2 are in similar size but tf_flowers*20 takes 3 times longer than 10k dogs*2
8. Keras API performs strangely as well. GPU number doesn't affect the training time linearly

**Describe the expected behavior**

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.
Keras API
```python
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function
from __future__ import unicode_literals

import tensorflow as tf
import tensorflow_datasets as tfds
import time
import datetime

import argparse
import sys
import shutil
import time
import os
import numpy as np

from functools import partial
from tensorflow.keras.layers import Input, Dense, Flatten, Conv2D, GlobalAveragePooling2D
from tensorflow.keras import Model
from tensorflow.keras.datasets.fashion_mnist import load_data
import tensorflow_datasets as tfds
import read_params
from train_config import configure_model, configure_optimizer, configure_lossfunc
from datasets.readtf_utils.dataset import get_dataset 
from datasets.readtf_utils.dataset import _parse_fn

os.environ["CUDA_VISIBLE_DEVICES"] = "0,1,2,3,4,5,6,7"
gpus = tf.config.experimental.list_physical_devices('GPU')
if gpus:
  try:
    # Currently, memory growth needs to be the same across GPUs
    for gpu in gpus:
      tf.config.experimental.set_memory_growth(gpu, True)
    logical_gpus = tf.config.experimental.list_logical_devices('GPU')
  except RuntimeError as e:
    # Memory growth must be set before GPUs have been initialized
    print(e)


num_epochs = 5
batch_size_per_replica = 128
learning_rate = 0.001
setting_GPUs_num = 8
devices = ["/gpu:"+str(i) for i in range(setting_GPUs_num)]

strategy = tf.distribute.MirroredStrategy(devices)
GPUs_num = strategy.num_replicas_in_sync
print('Number of devices: %d' % GPUs_num)  # 输出设备数量

batch_size = batch_size_per_replica

# 载入数据集并预处理
def resize(image, label):
    image = tf.image.resize(image, [224, 224]) / 255.0
    return image, label



class MyCustomCallback(tf.keras.callbacks.Callback):
    def on_train_begin(self, logs={}):
        self.train_begin = time.time()
        self.times = []
        # print('trian begins at {}'.format(self.train_begin))
        # d

    def on_epoch_begin(self, epoch, logs=None):
        self.epoch_begin = time.time()
        # print('epoch: {} begins at {}'.format(epoch, self.epoch_begin))

    def on_epoch_end(self, epoch, logs=None):
        self.epoch_end = time.time()
        self.epoch = epoch
        # print('epoch: {} ends at {}'.format(epoch, self.epoch_end))
        self.times.append(self.epoch_end-self.epoch_begin)
        print(" epoch: {} takes: {}".format(epoch, self.epoch_end-self.epoch_begin))

    def on_train_end(self, epoch, logs=None):
        self.train_end = time.time()
        # print('training takes {} secs/epoch: '.format((self.train_end - self.train_begin)/self.epoch))
        print('training takes average {:.2f} secs/epoch'.format(sum(self.times[1::]) / (self.epoch)))



tfrecords_dir = "/data121/lijiayuan/test/classify_flowers/datasets/"
dataset, _ = get_dataset(tfrecords_dir, subset="train", batch_size=batch_size)


if GPUs_num == 1:
    model = tf.keras.applications.MobileNetV2()
    model.compile(
        optimizer=tf.keras.optimizers.SGD(learning_rate=learning_rate),
        loss=tf.keras.losses.sparse_categorical_crossentropy,
        metrics=[tf.keras.metrics.sparse_categorical_accuracy]
    )
else:
    with strategy.scope():
        model = tf.keras.applications.MobileNetV2()
        model.compile(
            optimizer=tf.keras.optimizers.SGD(learning_rate=learning_rate),
            loss=tf.keras.losses.sparse_categorical_crossentropy,
            metrics=[tf.keras.metrics.sparse_categorical_accuracy]
            # run_eagerly=False
        )


start = time.time()
model.fit(dataset, epochs=num_epochs, callbacks=[MyCustomCallback()])
end = time.time()

print("{} GPUs takes {:.2f} secs/epoch = {:.2f} mins/epoch".format(strategy.num_replicas_in_sync, 
                                                                    (end-start)/num_epochs, 
                                                                    (end-start)/60/num_epochs))

```

Custom training loop
```python
from __future__ import absolute_import, division, print_function, unicode_literals

# Import TensorFlow
import tensorflow as tf

# Helper libraries
import numpy as np
import os
import time
import tensorflow_datasets as tfds
from datasets.readtf_utils.dataset import get_dataset 
from tensorflow.keras.layers import Input, Dense, Flatten, Conv2D, GlobalAveragePooling2D



os.environ["CUDA_VISIBLE_DEVICES"] = "0,1,2,3,4,5,6,7"
gpus = tf.config.experimental.list_physical_devices('GPU')
if gpus:
  try:
    # Currently, memory growth needs to be the same across GPUs
    for gpu in gpus:
      tf.config.experimental.set_memory_growth(gpu, True)
    logical_gpus = tf.config.experimental.list_logical_devices('GPU')
  except RuntimeError as e:
    # Memory growth must be set before GPUs have been initialized
    print(e)



def resize(image, label):
    image = tf.image.resize(image, [224, 224]) / 255.0
    return image, label

def assemble_model(num_classes, model_name='MobileNetV2'):
    import tensorflow as tf 
    base_model = tf.keras.applications.ResNet50(input_shape=(224,224,3),
                                                    weights='imagenet',
                                                    include_top=False)
    model = tf.keras.Sequential([
                                base_model,
                                GlobalAveragePooling2D(),
                                Dense(num_classes, activation='softmax')
                                ])
    model.trainable = True
    return model


print(tf.__version__)

setting_GPUs_num = 8
devices = ["/gpu:"+str(i) for i in range(setting_GPUs_num)]

strategy = tf.distribute.MirroredStrategy(devices)
print ('Number of devices: {}'.format(strategy.num_replicas_in_sync))
BATCH_SIZE_PER_REPLICA = 256
GLOBAL_BATCH_SIZE = BATCH_SIZE_PER_REPLICA * strategy.num_replicas_in_sync

EPOCHS = 5


##-----dataset------##
tfrecords_dir = "/data121/lijiayuan/test/classify_flowers/datasets"
train_ds, classes_num = get_dataset(tfrecords_dir, subset="train", batch_size=GLOBAL_BATCH_SIZE)


train_ds = strategy.experimental_distribute_dataset(train_ds)






with strategy.scope():
  # Set reduction to `none` so we can do the reduction afterwards and divide by
  # global batch size.
  loss_object = tf.keras.losses.SparseCategoricalCrossentropy(
      reduction=tf.keras.losses.Reduction.NONE)
  # or loss_fn = tf.keras.losses.sparse_categorical_crossentropy
  def compute_loss(labels, predictions):
    per_example_loss = loss_object(labels, predictions)
    return tf.nn.compute_average_loss(per_example_loss, global_batch_size=GLOBAL_BATCH_SIZE)


with strategy.scope():

  train_accuracy = tf.keras.metrics.SparseCategoricalAccuracy(
      name='train_accuracy')

# model and optimizer must be created under `strategy.scope`.
with strategy.scope():
  model = assemble_model(num_classes=classes_num)
  optimizer = tf.keras.optimizers.Adam()
  checkpoint = tf.train.Checkpoint(optimizer=optimizer, model=model)

with strategy.scope():
  def train_step(inputs):
    images, labels = inputs

    with tf.GradientTape() as tape:
      predictions = model(images, training=True)
      loss = compute_loss(labels, predictions)

    gradients = tape.gradient(loss, model.trainable_variables)
    optimizer.apply_gradients(zip(gradients, model.trainable_variables))

    train_accuracy.update_state(labels, predictions)
    return loss 




with strategy.scope():

  @tf.function
  def distributed_train_step(dataset_inputs):
    per_replica_losses = strategy.experimental_run_v2(train_step,
                                                      args=(dataset_inputs,))
    return strategy.reduce(tf.distribute.ReduceOp.SUM, per_replica_losses,
                           axis=None)
 
 
  times = []
  for epoch in range(EPOCHS):
    # TRAIN LOOP

    total_loss = 0.0
    num_batches = 0
    epoch_start = time.time()
    for x in train_ds:
      total_loss += distributed_train_step(x)
      num_batches += 1
    train_loss = total_loss / num_batches
    epoch_end = time.time()
    
    if epoch != 0:
      times.append(epoch_end-epoch_start)
    



    template = ("Epoch {}, Loss: {:.2f}, Accuracy: {:.2f}, "
                " Takes: {:.2f}")
    print (template.format(epoch+1, train_loss,
                           train_accuracy.result()*100, 
                           epoch_end-epoch_start))

    train_accuracy.reset_states()
  print("{} GPUs takes average {:.2f} secs".format(setting_GPUs_num, 
                                                    sum(times)/(EPOCHS-1)))


```

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by guptapriya** [comment]
hi, thank you for the analysis you've done. a couple of quick observations/questions:

1. batch size. in the keras example, the batch size seems "per replica" batch size, but in the custom training loop example, the batch size is "global", i.e. "per replica batch size * num replicas". Is that accurate? If so, the scaling you expect in those cases will be different. You should use "per replica batch size * num replicas" in both cases. I think this might address your point #8? 

2. Re point #7: Regarding your comparison of flowers vs dogs dataset, setting aside distribution, a number of factors can affect the performance observed in those 2 cases (for e.g. the input processing can take different amounts of time based on the exact input). When you say their sizes are "same", do you mean they have same number of images, or do they have the same total bytes? Why are you trying to compare the time taken for different datasets?

**Comment by JiayuanSternLi** [comment]
Hi, sorry for my late reply.
1. I indeed did the experiments on batch_size on total or per replica, but it doesn't show a great difference so I didn't mention it
2. The same is the same input size. The most weird thing is that Keras performs best on 2 GPUs while equvalent to 8 GPUs with the custom training loop:
![image](https://user-images.githubusercontent.com/33815430/73808710-d8f50d80-480b-11ea-92eb-bbd37198ffc7.png)
please take a look at the results marked by green

**Comment by JiayuanSternLi** [comment]
> hi, thank you for the analysis you've done. a couple of quick observations/questions:
> 
> 1. batch size. in the keras example, the batch size seems "per replica" batch size, but in the custom training loop example, the batch size is "global", i.e. "per replica batch size * num replicas". Is that accurate? If so, the scaling you expect in those cases will be different. You should use "per replica batch size * num replicas" in both cases. I think this might address your point #8?
> 2. Re point #7: Regarding your comparison of flowers vs dogs dataset, setting aside distribution, a number of factors can affect the performance observed in those 2 cases (for e.g. the input processing can take different amounts of time based on the exact input). When you say their sizes are "same", do you mean they have same number of images, or do they have the same total bytes? Why are you trying to compare the time taken for different datasets?
Please take a look at the above reply

**Comment by nikitamaia** [comment]
Hi @ProNoobLi, we recently published a TensorFlow [performance guide](https://www.tensorflow.org/guide/gpu_performance_analysis) that details different factors that can influence training time for single and multi gpu use cases. You might want to follow the steps in the guide and use the TF Profiler to get a better insight into your progam.
