### ISSUE TITLE
tf.function and tf.nest break for valid Mapping instances

### ISSUE THREAD

**Issue by ethereon** [tensorflow/tensorflow#36146]
`tf.function` makes invalid assumptions about arguments that are `Mapping` instances. In general, there are no requirements for `Mapping` instances to have constructors that accept `[(key, value)] ` initializers, [as assumed here](https://github.com/tensorflow/tensorflow/blob/v2.1.0/tensorflow/python/util/nest.py#L145).

This leads to cryptic exceptions when used with perfectly valid `Mapping` subclasses such as this one:
```python
class CustomMapping(Mapping):

  def __init__(self, **kwargs):
    self.mapping = kwargs
  
  def __getitem__(self, key):
    return self.mapping[key]
  
  def __iter__(self):
    return iter(self.mapping)

  def __len__(self):
    return len(self.mapping)
```

See this [Colab notebook for an example](https://colab.research.google.com/drive/1sIbvyPVtQexCWqVO7QD3KlY7PoLdPeKq).

**Comment by Saduf2019** [comment]
Issue replicating in [tf-nightly.](https://colab.research.google.com/gist/Saduf2019/52d668ef566842781e293594fabf27ef/36146.ipynb) Thanks.

**Comment by mdanatg** [comment]
It looks like `tf.nest` is overly permissive with `Mapping` subclasses, because the contract of `Mapping` does not seem to specify an interface for constructors. Users may accept key-value pairs, **kwargs or just about anything else and they'd still have a valid Mapping. Moreover, detecting how to properly use that constructor is extremely difficult in Python.

The correct solution is either to only support `dict` and `OrderedDict` (treating everything else as opaque objects), or to explicitly require a certain initialization contract.

At any rate, this limitation should be documented and a best-effort to detect errors could be made by catching anything exception that the constructor raises and adding a hint about this.

**Comment by punndcoder28** [comment]
Hey! I would like to work on this. Could you guide me?

**Comment by mdanatg** [comment]
Sure, here are a few directions for improvement -

First, the documentation of all `@tf_export` methods inside [tf.nest](https://github.com/tensorflow/tensorflow/blob/r2.1/tensorflow/python/util/nest.py) needs to be brought to date and clarify what is a "structure". Some entries mention that you can have dicts, others do not. I think the module documentation should clarify that. The docstrings in there are used to generate the [public docs](https://www.tensorflow.org/api_docs/python/tf/nest).

Second, [IsMappingHelper](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/util/util.cc#L216) that verifies for supported types should check for `MutableMapping` rather than just `Mapping`. It should probably be renamed to `IsNestCompatibleMapping` on this occasion. The reason for that is because we need to know how to construct new mappings of the same type and the Mapping interface doesn't standardize that. See [the Python reference](https://docs.python.org/3/library/collections.abc.html) for more details.

Third, [the code of _sequence_like](https://github.com/tensorflow/tensorflow/blob/v2.1.0/tensorflow/python/util/nest.py#L145) that attempts to reconstruct `dict` objects should catch exceptions and raise a more informative one (something like "could not reconstruct object of type X"). Also, [the code of _get_defun_inputs](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/framework/func_graph.py#L897) must again catch exceptions and add more information (something like "could not handlearguments of <function name>: <message of caught error>").

I hope this helps! As a general guidance, I recommend sending multiple small PRs instead of one big change, to make them easier to review.

**Comment by punndcoder28** [comment]
Hey! Thanks for the input. 
`First, the documentation of all @tf_export methods inside tf.nest needs to be brought to date and clarify what is a "structure". Some entries mention that you can have dicts, others do not. I think the module documentation should clarify that. The docstrings in there are used to generate the public docs.`
Regarding this if am not wrong a couple of the function's documentation need to updated for which I should create a separate PR is what you are suggesting and to do the same for the remaining two broken down problems?

**Comment by mdanatg** [comment]
I'd start with everything in one PR (docstring changes and small code changes), and if you end up changing lots of code, break it down into more pieces.

**Comment by punndcoder28** [comment]
@mdanatg I've create a PR #36186 addressing this. Could you please review?

**Comment by namedtoaster** [comment]
I would like to test tensorflow locally from the github repo, how do I set that up for python?

**Comment by mdanatg** [comment]
@namedtoaster see the guide: https://www.tensorflow.org/install/source; you may want to skip to the [Docker section](https://www.tensorflow.org/install/source#docker_linux_builds) for a ready-made setup.

**Comment by namedtoaster** [comment]
@mdanatg I downloaded tensorflow from the most current repo and built using the instructions you linked to. When I try to run the code from the notebook (or really any simple tensorflow command), I get the following error.

`Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.2 AVX AVX2 FMA`

Is there a way to suppress those features from my CPU so I can run tf? Or do I have to rebuild a new binary that disables those features?

**Comment by mdanatg** [comment]
@namedtoaster You can safely ignore that warning, but otherwise you want a binary that is built with those features enabled. Try to see if you can rebuild it with these bazel options: `--copt=-mavx2 --copt=-msse4 --copt=-mfma`

**Comment by namedtoaster** [comment]
@mdanatg thanks for the info. I stand corrected on my last post, I am able to do a simple tensorflow command with the original binary installed. When I tried to re-install with the optimizations I got some compiler errors that I'll try to fix at a later time. I did what you said but I get this output:

`clang: error: unsupported option '--config=opt'`

My bigger confusion right now is that when I try to run the code from the notebook I get an error about using the wrong number of arguments:

`2020-02-12 15:50:38.623392: I tensorflow/core/platform/cpu_feature_guard.cc:143] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.2 AVX AVX2 FMA
Traceback (most recent call last):
  File "/Users/----/PycharmProjects/tensorflow_dev/test.py", line 27, in <module>
    test_tf_function(CustomMapping(theta=3.1415))
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tensorflow_core/python/eager/def_function.py", line 576, in __call__
    result = self._call(*args, **kwds)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tensorflow_core/python/eager/def_function.py", line 623, in _call
    self._initialize(args, kwds, add_initializers_to=initializers)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tensorflow_core/python/eager/def_function.py", line 505, in _initialize
    *args, **kwds))
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tensorflow_core/python/eager/function.py", line 2440, in _get_concrete_function_internal_garbage_collected
    graph_function, _, _ = self._maybe_define_function(args, kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tensorflow_core/python/eager/function.py", line 2771, in _maybe_define_function
    graph_function = self._create_graph_function(args, kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tensorflow_core/python/eager/function.py", line 2661, in _create_graph_function
    capture_by_value=self._capture_by_value),
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tensorflow_core/python/framework/func_graph.py", line 898, in func_graph_from_py_func
    args, arg_names, flat_shapes=arg_shapes)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tensorflow_core/python/framework/func_graph.py", line 1132, in _get_defun_inputs_from_args
    args, names, structure=args, flat_shapes=flat_shapes)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tensorflow_core/python/framework/func_graph.py", line 1188, in _get_defun_inputs
    arg_value = nest.map_structure(_get_composite_tensor_spec, arg_value)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tensorflow_core/python/util/nest.py", line 600, in map_structure
    expand_composites=expand_composites)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tensorflow_core/python/util/nest.py", line 535, in pack_sequence_as
    return _pack_sequence_as(structure, flat_sequence, expand_composites)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tensorflow_core/python/util/nest.py", line 499, in _pack_sequence_as
    return sequence_fn(structure, packed)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tensorflow_core/python/util/nest.py", line 145, in _sequence_like
    return instance_type((key, result[key]) for key in instance)
TypeError: __init__() takes exactly 1 argument (2 given)`

I'm looking into the error right now. I may have an incorrect understanding of kwargs

**Comment by mdanatg** [comment]
I think the error you see is expected - it's the bug described in the OP.

**Comment by mdanatg** [comment]
For the instruction set warning, try specifying `-c opt` as well. I came across this page where the author seemed to successfully use these options: https://gist.github.com/Brainiarc7/6d6c3f23ea057775b72c52817759b25c

**Comment by namedtoaster** [comment]
@mdanatg that makes sense. I should've noticed that -- I will check out that link and give it a try. Thanks

**Comment by Joey155** [comment]
Hello I thought this issue was solved but it's been open for quite some time.
I would like to contribute if contributions are still being accepted.

**Comment by punndcoder28** [comment]
Hey @Joey155 ! PR #36186 has been opened regarding the same.

**Comment by kshitij12345** [comment]
@ethereon I guess the issue can be closed since the PR #36186 has been merged.

**Comment by ethereon** [comment]
I believe the described issue still exists. With PR #36186 , it produces a warning (with a typo) before failing with the same exception as before

```
WARNING:tensorflow:Mapping types may not work well with tf.nest. Preferusing MutableMapping for <class '__main__.CustomMapping'>
...
TypeError: __init__() takes 1 positional argument but 2 were given
```

Indeed, even as a workaround, it's not immediately clear that the recommendation should be to adopt `MutableMapping`, which seems like a stronger requirement than just accepting `(key, value)` pairs in the constructor...

**Comment by kshitij12345** [comment]
Oops. My bad didn't notice that.

**Comment by tonytonev** [comment]
@punndcoder28 will you update your fix as per @ethereon's feedback or shall I?

**Comment by tonytonev** [comment]
@ethereon I'm not clear on what the desired behavior would be that you would consider a "fix"? Is it a more clear error message on the exception that says something like "Map must have a (key, value) constructor" instead of "TypeError: __init__() takes 1 positional argument but 2 were given"?

**Comment by punndcoder28** [comment]
I will get on it today and try to fix. If I am unable to do so, you could take over.

**Comment by mdanatg** [comment]
The `**kwargs` mechanics only work with maps that have string keys. Since `tf.nest` cannot make any assumption about the type of the keys, I think it requires a constructor with on positional argument. So, improving the error message seems like the right path forward.

**Comment by punndcoder28** [comment]
@mdanatg How can I improve the error message? Any suggestions would be helpful.

**Comment by tonytonev** [comment]
@punndcoder28 How about "Mapping must have a (key, value) constructor". This should be an actual exception rather than just a warning, since it is a fatal error that will throw "TypeError: init() takes 1 positional argument but 2 were given" anyway. @mdanatg do you agree?

**Comment by mdanatg** [comment]
The warning message is separate. I do want to discourage using `Mapping` subclasses in favor of `MutableMapping`, for the reason that follows.

To actually raise an error, more checks need to be added: first you need to find the constructor of the type, then you need to check its argspec and count the positional arguments. Even so, we can only check that the constructor takes a positional arg and will have no idea whether that constructor expects it to be a key-value list (it might expect it to be a dict instead). So the error will not be 100% robust.

Alternatively, you could catch exceptions raised while calling the constructor and re-raise them with a helper message, something like: "Error rebuilding custom mapping. Note that it must accept a single positional argument representing an iterable of key-value pairs, in addition to self. Cause: <original error>".

**Comment by tonytonev** [comment]
@punndcoder28 Do you mind if I submit this as my first pull request? You already had your changes accepted 😄 .

**Comment by punndcoder28** [comment]
Sure. Go ahead @tonytonev.

**Comment by tonytonev** [comment]
Thanks, I'm working on getting it to build locally so I can run tests, and I'll submit a PR soon.

**Comment by tonytonev** [comment]
The fix has been merged. I think this can be closed.
