### ISSUE TITLE
TF2.0 to 2.1 breaking for tf.image.random_jpeg_quality

### ISSUE THREAD

**Issue by klanderson** [tensorflow/tensorflow#36142]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- TensorFlow version (use command below): 2.1.0
- Python version: 3.5

**Describe the current behavior**
I upgraded to tensorflow 2.1 and everything in my project is working fine except for one thing. Calling `tf.image.random_jpeg_quality` throws a ValueError: `as_list() is not defined on an unknown TensorShape`. The full error is pasted at the bottom of this issue.

The code works after removing the call to random_jpeg_quality. That works for me at this point. Just raising this issue in case it hasn't been noted yet.

**Other info / logs**
```
ValueError: in converted code:

    /data.py:261 _parse_example_augment  *
        image = tf.image.random_jpeg_quality(image=image, min_jpeg_quality=60, max_jpeg_quality=100)
    /root/miniconda3/lib/python3.5/site-packages/tensorflow_core/python/ops/image_ops_impl.py:2031 random_jpeg_quality
        return adjust_jpeg_quality(image, jpeg_quality)
    /root/miniconda3/lib/python3.5/site-packages/tensorflow_core/python/ops/image_ops_impl.py:2064 adjust_jpeg_quality
        channels = image.shape.as_list()[-1]
    /root/miniconda3/lib/python3.5/site-packages/tensorflow_core/python/framework/tensor_shape.py:1166 as_list
        raise ValueError("as_list() is not defined on an unknown TensorShape.")

    ValueError: as_list() is not defined on an unknown TensorShape.
```

**Comment by Leslie-Fang** [comment]
@klanderson  Could you provide a piece of code which to reproduce this issue?

**Comment by Leslie-Fang** [comment]
This commit id
https://github.com/tensorflow/tensorflow/commit/ef3508020e0af36bbe9f5088222778ef3678bc6f
makes the changes.
@klanderson I suspect you need to pass the None in the last shape parameter

**Comment by klanderson** [comment]
Thanks, I just wanted to bring up the issue as it was something that changed between 2.0 and 2.1.

**Comment by oanush** [comment]
@klanderson ,
Please feel free to close the issue if its resolved.Thanks!

**Comment by bardenthenry** [comment]
I use the docker image tensorflow/tensorflow:latest-gpu-py3, but the problem have not resolved. Why this issue closed?
