### ISSUE TITLE
ValueError: Tried to convert 'y' to a tensor and failed. Error: None values not supported.

### ISSUE THREAD

**Issue by Chosen-ones** [tensorflow/tensorflow#36140]
### System information
2.0.0 Tensorflow version
IDE Spyder(Python 3.7)

### Source code / logs
import sys
import os
from tensorflow.python.keras.preprocessing.image import ImageDataGenerator
from tensorflow.python.keras import optimizers
from tensorflow.python.keras import Sequential
from tensorflow.python.keras.layers import Flatten, Dense, Activation
from tensorflow.python.keras.layers import Convolution2D, MaxPooling2D
from tensorflow.python.keras.layers import Dropout
from tensorflow.python.keras.optimizers import Adam
from tensorflow.python.keras import backend as K

K.clear_session()
data_entrenamiento='./data/entrenamiento'
data_validacion= './data/validacion'

epocas=10
altura, longitud= 100, 100
batch_size=10 
pasos= 50 
pasos_validacion= 20 

filtrosConv1=32
filtrosConv2=64

tamaño_filtro1=(3,3)#Conv1
tamaño_filtro2=(2,2)#Conv2

tamaño_pool=(2,2)#Maxpooling
clases=2
lr=0.005

entrenamiento_datagen= ImageDataGenerator(rescale=1./255, #255 a 1
                                          shear_range=0.3,#Inclina la imageb
                                          zoom_range=0.3, #Realiza un zoom en la imagen
                                          horizontal_flip=True #Inversión de la imagen
                                          )

validacion_datagen=ImageDataGenerator(
                                        rescale=1./255
                                      )
imagen_entrenamiento=entrenamiento_datagen.flow_from_directory(
        data_entrenamiento,
        target_size=(altura,longitud),
        batch_size=batch_size,
        class_mode='categorical'
        )

imagen_validacion=validacion_datagen.flow_from_directory(
        data_validacion,
        target_size=(altura,longitud),
        batch_size=batch_size,
        class_mode='categorical'
        )

cnn=Sequential()

cnn.add(Convolution2D(filtrosConv1, tamaño_filtro1, padding='same', input_shape=(altura, longitud, 3), activation='relu'))
cnn.add(MaxPooling2D(pool_size=tamaño_pool))

cnn.add(Convolution2D(filtrosConv2, tamaño_filtro2, padding='same', activation='relu'))
cnn.add(MaxPooling2D(pool_size=tamaño_pool))

cnn.add(Flatten())
cnn.add(Dense(256, activation= 'relu'))
cnn.add(Dropout(0.5))
cnn.add(Dense(clases, activation='softmax'))

cnn.compile(loss='categorical_crossentropy', optimizer = optimizers.Adam(lr=lr), metrics=['accuracy'])

cnn.fit(imagen_entrenamiento, steps_per_epoch= pasos, epochs=epocas, validation_data =imagen_validacion, validation_steps=pasos_validacion)

### Problem complete
Found 4001 images belonging to 2 classes.
Found 2000 images belonging to 2 classes.
Epoch 1/10
Traceback (most recent call last):

  File "<ipython-input-11-083720e5df85>", line 1, in <module>
    runfile('C:/Users/Acer/Documents/Resp_roja/PROGRAMAS TESIS/python/practica4_TF.py', wdir='C:/Users/Acer/Documents/Resp_roja/PROGRAMAS TESIS/python')

  File "C:\Users\Acer\Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 827, in runfile
    execfile(filename, namespace)

  File "C:\Users\Acer\Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 110, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/Users/Acer/Documents/Resp_roja/PROGRAMAS TESIS/python/practica4_TF.py", line 84, in <module>
    cnn.fit(imagen_entrenamiento, steps_per_epoch= pasos, epochs=epocas, validation_data =imagen_validacion, validation_steps=pasos_validacion)

  File "C:\Users\Acer\Anaconda3\lib\site-packages\tensorflow_core\python\keras\engine\training.py", line 728, in fit
    use_multiprocessing=use_multiprocessing)

  File "C:\Users\Acer\Anaconda3\lib\site-packages\tensorflow_core\python\keras\engine\training_generator.py", line 603, in fit
    steps_name='steps_per_epoch')

  File "C:\Users\Acer\Anaconda3\lib\site-packages\tensorflow_core\python\keras\engine\training_generator.py", line 265, in model_iteration
    batch_outs = batch_function(*batch_data)

  File "C:\Users\Acer\Anaconda3\lib\site-packages\tensorflow_core\python\keras\engine\training.py", line 1017, in train_on_batch
    self._make_train_function()

  File "C:\Users\Acer\Anaconda3\lib\site-packages\tensorflow_core\python\keras\engine\training.py", line 2116, in _make_train_function
    params=self._collected_trainable_weights, loss=self.total_loss)

  File "C:\Users\Acer\Anaconda3\lib\site-packages\tensorflow_core\python\keras\optimizers.py", line 476, in get_updates
    grads = self.get_gradients(loss, params)

  File "C:\Users\Acer\Anaconda3\lib\site-packages\tensorflow_core\python\keras\optimizers.py", line 92, in get_gradients
    if None in grads:

  File "C:\Users\Acer\Anaconda3\lib\site-packages\tensorflow_core\python\ops\math_ops.py", line 1336, in tensor_equals
    return gen_math_ops.equal(self, other)

  File "C:\Users\Acer\Anaconda3\lib\site-packages\tensorflow_core\python\ops\gen_math_ops.py", line 3626, in equal
    name=name)

  File "C:\Users\Acer\Anaconda3\lib\site-packages\tensorflow_core\python\framework\op_def_library.py", line 545, in _apply_op_helper
    (input_name, err))

ValueError: Tried to convert 'y' to a tensor and failed. Error: None values not supported.

### Please help me

**Comment by oanush** [comment]
@Chosen-ones ,
Can you refer solutions in the links and let us know if it helped [link1](https://stackoverflow.com/questions/58261348/valueerror-tried-to-convert-y-to-a-tensor-and-failed-error-none-values-not) and [link2](https://stackoverflow.com/questions/58279628/what-is-the-difference-between-tf-keras-and-tf-python-keras). Thanks!

**Comment by Chosen-ones** [comment]
> @Chosen-ones ,
> Can you refer solutions in the links and let us know if it helped [link1](https://stackoverflow.com/questions/58261348/valueerror-tried-to-convert-y-to-a-tensor-and-failed-error-none-values-not) and [link2](https://stackoverflow.com/questions/58279628/what-is-the-difference-between-tf-keras-and-tf-python-keras). Thanks!

Thank you, but I removed ".python." to the imports and now It work. However, the accuracy don't rise from 0.5 in the validation phase. Do you know what it happen?

**Comment by rosanag24** [comment]
Hello, I have the same error you had. What do you mean with "remove .python"? Please I don't get it and I really want to fix this issue.

**Comment by Saduf2019** [comment]
@rosanag24 
I hope this [comment](https://github.com/tensorflow/models/issues/3705#issuecomment-375563179) helps

@Chosen-ones please confirm if we may proceed to move this issue to resolved status.

**Comment by Saduf2019** [comment]
@Chosen-ones ,
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
