### ISSUE TITLE
makefile fails to execute a.out file

### ISSUE THREAD

**Issue by applied-math-K** [tensorflow/tensorflow#36144]
I am new to TensorFlow. At the moment, I am learning TensorFlow for C code on my Macbook. I follow the instructions by Google and manage to run the 'hello world' in C.

I set the paths on my bash_profile as follows:

export LIBRARY_PATH=$LIBRARY_PATH:/usr/local/tensorflow/lib

export DYLD_LIBRARY_PATH=$DYLD_LIBRARY_PATH:/usr/local/tensorflow/lib.

My makefile is as follow.

tensorlib = -L/usr/local/tensorflow-1.15.0/lib/

tensorlnk = -I/usr/local/tensorflow-1.15.0/include/

task:

mpicc -c hello.c $(tensorlnk)

mpicc    hello.o $(tensorlib)
run:

mpirun -np 4 ./a.out
I can compile the program and generate the executable, a.out. In my terminal, I can run the program using 'mpirun -np 4 ./a.out' to execute. But the command 'make run' fails. Here is the error message

dyld: Library not loaded: @rpath/libtensorflow.1.dylib Referenced from: /Users/usr/Documents/code/dev/TensorFlow/c/./a.out Reason: image not found

Could anyone tell me what the problem is?

Many thanks in advance.

**Comment by ravikyram** [comment]
@applied-math-K 
Just to verify did you followed the instructions from [Tensorflow site](https://www.tensorflow.org/install/lang_c). Thanks!

**Comment by applied-math-K** [comment]
Yes! I followed the instructions from Tensorflow site.

**Comment by ymodak** [comment]
What is your macOS version?
See https://www.tensorflow.org/install/lang_c#supported_platforms

**Comment by applied-math-K** [comment]
I am running Catalina 10.15.3. Tensorflow runs on my Mac. But I am unable to run it using 'make run'.

**Comment by ymodak** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.
Thanks!
