### ISSUE TITLE
Output from TFLite model converted using experimental converter does not match old converter

### ISSUE THREAD

**Issue by bilalsoomro** [tensorflow/tensorflow#36156]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux
- TensorFlow installed from (source or binary): pip install tf-nightly
- TensorFlow version (or github SHA if from source): 2.2.0-dev20200123

EDIT: I am experimenting with converting the SSD MobileNet V2 models. Using the old converter, the model seems to work without any issues. However, the model converted with the new experimental converter does not match the results. I also tried a Float16 quantized version of the model and it also doesn't match the output of any the two float32 models.

**Command used to run the converter or code if you’re using the Python API**

```
converter = tf.compat.v1.lite.TFLiteConverter.from_frozen_graph(frozen_model, input_arrays, output_arrays, input_shapes)
converter.allow_custom_ops = True
converter.experimental_new_converter = True
tflite_model = converter.convert()
open('ssd_mobilenet_v2_float32_experimental.tflite', "wb").write(tflite_model)
```

**The output from the converter invocation**
Comparison of model output with old and new experimental converter.
```
AssertionError: 
Arrays are not almost equal to 5 decimals

Mismatched elements: 40 / 40 (100%)
Max absolute difference: 11.113381
Max relative difference: 3501.543
 x: array([[ -8.2944 , -10.18906,  -9.16781,  -8.85916],
       [ -8.63264,  -9.66667,  -8.13753, -11.32026],
       [ -7.67533,  -9.24478,  -9.12119, -11.07866],...
 y: array([[ 2.46333e-01, -4.78567e-01, -7.21600e-01,  4.30845e-02],
       [ 3.55053e-01,  1.12653e+00, -3.39829e+00, -5.85306e+00],
       [ 7.73718e-01,  4.47561e-01,  1.09934e+00, -1.17987e-02],...
```

**Also, please include a link to the saved model or GraphDef**
[Colab notebook with model](https://colab.research.google.com/drive/1J4As3g3BY1zkdRdHHXySz_SgvfuThqHF)

**Failure details**
The output produced by models using various options all output different results as demonstrated in notebook. I also created a Float16 Quantized version of the SSD MobileNet V2 model however that doesn't produce a similar precision output to the two F32 models.

**Comment by karimnosseir** [comment]
Ashwin can you please check

Thanks

**Comment by miaout17** [comment]
We investigated the model and found it's actually working as intended. 

Here's the detail: The model outputs up to 10 results, but the actual number of results is stored in an output tensor (output 3). 
The other outputs always allocate enough memory to handle 10 results, but only the first `num_results` rows are meaningful. The rest of output buffer is uninitialized. 

Below is the code snippet to fix the testing code:
```
# Get the number of results from the 2 models, and check if it matches. 
tflite_num_results_1 = interpreter_1.get_tensor(output_details_1[3]['index'])[0]
tflite_num_results_2 = interpreter_2.get_tensor(output_details_2[3]['index'])[0]
np.testing.assert_equal(tflite_num_results_1, tflite_num_results_2)
num_results = int(tflite_num_results_1)

# Get the actual results (bonding boxes), while slicing the first num_results rows.
tflite_results_1 = interpreter_1.get_tensor(output_details_1[0]['index'])[0, :num_results, :]
tflite_results_2 = interpreter_2.get_tensor(output_details_2[0]['index'])[0, :num_results, :]

# Compare the result.
for result_1, result_2 in zip(tflite_results_1, tflite_results_2):
  np.testing.assert_almost_equal(result_1, result_2, decimal=5)
```

Thanks for trying out the experimental converter. Let us know if you have further questions!
