### ISSUE TITLE
undeclared inclusion(s) in rule when build from source

### ISSUE THREAD

**Issue by VitaMusic** [tensorflow/tensorflow#36163]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): RHEL 7.7
- TensorFlow installed from (source or binary): source
- TensorFlow version: v2.1.0-rc2
- Python version: intel 3.6.9
- Installed using virtualenv? pip? conda?: conda
- Bazel version (if compiling from source): 0.29.1
- GCC/Compiler version (if compiling from source): 7.3
- CUDA/cuDNN version: 10.0 or 10.1 (tested the boths)
- GPU model and memory: Tesla K80

**Describe the problem**
FAILED: Build did NOT complete successfully

**Provide the exact sequence of commands / steps that you executed before running into the problem**
#compiling from source
cd /xxxx/install/tf2
git clone https://github.com/tensorflow/tensorflow
cd tensorflow
git checkout tags/v2.1.0-rc2
git checkout -b v2.1
conda activate tf2
source scl_source enable devtoolset-7 llvm-toolset-6.0
./configure
#input: /usr/bin/python3
#input: /opt/anaconda3/lib/python3.6/site-packages
#sequence: ok=enter, ok, ok, ok, y, y, 10.0; 7.6.4; 6.0.1; ok
#input: /usr/local/cuda-10.0,/usr/local/cuda-10.0/bin,/usr/local/cuda-10.0/lib64,/usr/local/cuda-10.0/include,/opt/TensorRT-6.0.1.5,/opt/TensorRT-6.0.1.5/bin,/opt/TensorRT-6.0.1.5/lib,/opt/TensorRT-6.0.1.5/include,/opt/rh/devtoolset-7/root/usr/bin,/opt/rh/devtoolset-7/root/usr/lib64,/opt/rh/devtoolset-7/root/usr/include,/opt/rh/devtoolset-7/root/usr/libexec/gcc/x86_64-redhat-linux/7,/opt/rh/devtoolset-7/root/usr/lib/gcc/x86_64-redhat-linux/7/include
#input: 3.5,3.7,6.0,7.0,7.5
#sequence: ok, ok, ok, ok
bazel build --verbose_failures --config=v2 --config=opt --config=mkl --config=cuda //tensorflow/tools/pip_package:build_pip_package
#ERROR IS HERE ...

#cleaning for next try
bazel clean --expunge --async
rm -rf $HOME/.cache/bazel
git checkout tags/v2.1.0-rc2
git branch -d v2.1
git checkout -b v2.1

**Any other info / logs**
ERROR: /home/xxx/.cache/bazel/_bazel_xxx/26195a8102390a78bf7f86e6341cc9bb/external/boringssl/BUILD:130:1: undeclared inclusion(s) in rule '@boringssl//:crypto':
this rule is missing dependency declarations for the following files included by 'external/boringssl/src/crypto/asn1/tasn_fre.c':
  '/opt/rh/devtoolset-7/root/usr/lib/gcc/x86_64-redhat-linux/7/include/stddef.h'
  '/opt/rh/devtoolset-7/root/usr/lib/gcc/x86_64-redhat-linux/7/include/stdint.h'
  '/opt/rh/devtoolset-7/root/usr/lib/gcc/x86_64-redhat-linux/7/include/stdarg.h'
Target //tensorflow/tools/pip_package:build_pip_package failed to build
ERROR: /home/xxx/install/tf2/tensorflow/tensorflow/lite/toco/python/BUILD:77:1 undeclared inclusion(s) in rule '@boringssl//:crypto':
this rule is missing dependency declarations for the following files included by 'external/boringssl/src/crypto/asn1/tasn_fre.c':
  '/opt/rh/devtoolset-7/root/usr/lib/gcc/x86_64-redhat-linux/7/include/stddef.h'
  '/opt/rh/devtoolset-7/root/usr/lib/gcc/x86_64-redhat-linux/7/include/stdint.h'
  '/opt/rh/devtoolset-7/root/usr/lib/gcc/x86_64-redhat-linux/7/include/stdarg.h'
INFO: Elapsed time: 61.246s, Critical Path: 3.70s
INFO: 198 processes: 198 local.
FAILED: Build did NOT complete successfully

**Comment by gadagashwini** [comment]
@VitaMusic, Please follow the instructions mentioned in the [Tensorflow doc](https://www.tensorflow.org/install/source). Thanks!

**Comment by VitaMusic** [comment]
What is wrong in my install script ?

пт, 24 Янв 2020 г., 10:56 gadagashwini <notifications@github.com>:

**Comment by gadagashwini** [comment]
@VitaMusic, Can you try with removing the conda actvate tf2 step and remove the bazel cache files in /root/.cache/bazel/. let us know how it progresses. Thanks

**Comment by gadagashwini** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
