### ISSUE TITLE
Logic Error in memory planner

### ISSUE THREAD

**Issue by namitajadhav** [tensorflow/tensorflow#36161]
Host OS Platform and Distribution 
NAME="Ubuntu"
VERSION="18.04 LTS"
ID=ubuntu
PRETTY_NAME="Ubuntu 18.04 LTS"
VERSION_ID="18.04"
Python versionL 2.7.15+
Target platform : K64F

Describe the problem
I am trying to deploy a GRU model on the ARM Cortex M board(K64F). During memory allocation of the tensor, I get the following error message. I don't understand the error.
It would be quite helpful if somebody knows the solution or an explanation for this following error report.

```
Logic error in memory planner, tensor 17 has an invalid lifetime
AllocateTensors() failed
```

Thank You

**Comment by suphoff** [comment]
Invalid lifetime indicates that the tensor is either never used as an input to an operation or as an output of an operation (or used as model input/output tensors).
Can you retry with the top of tree version of TF - at the very least you will get better error reporting on invalid lifetime.
As a workaround you may be able to force a valid lifetime by adding the tensor as an input or output to the model. If the same tensor is used for multiple multiple operations you may run into #35121

**Comment by namitajadhav** [comment]
Thank you for your response. Is there a way to find out the name of tensor which is never used as an input? I tried to remove all unused tensors in the model but resulted in the same error. 
Since my model can be used only with Tensorflow 1.14 I could not test with Tensorflow 2.0.0.

**Comment by suphoff** [comment]
@namitajadhav : I assume the limitation on Tensorflow 1.14 is for training and converting the model to tflite - if that is the case you can still deploy the tflite/flatbuffer on current (top of tree) tensorflow master,

@PeteBlackerThe3rd 's   tflite analyzer may help you to analyze your tflite file: https://github.com/PeteBlackerThe3rd/tflite_analyser

**Comment by ymodak** [comment]
@namitajadhav Is this still an issue? Feel free to share your resolution if you have solved it.  Thanks!

**Comment by namitajadhav** [comment]
I tried to convert the trained model (trained using tensorflow 1.14). Tried converting using tensorflow 2.1.0 while enabling version 1 and the error still persists.
I even tried to use tensorflow 2.1 to run example code as below.
([https://github.com/tensorflow/tensorflow/issues/36219])
 But it resulted in the same error as described.
 Any support with this will be of great help.

Thank You

**Comment by srjoglekar246** [comment]
@namitajadhav Could you provide your TFLite file? Its difficult to debug the tensor without seeing how its used in the model :-)

**Comment by namitajadhav** [comment]
I have attached two tflite files. The first one is created with tensorflow 1.14 which gives me a error of invalid lifetime. The second tflite is created with an example code of Keras and TF 2.1.0.
[](https://drive.google.com/file/d/1Pmen28uciZiZrDqJWDMOaZkPrZ71HWAg/view?usp=sharing)

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.
