### ISSUE TITLE
Can't run TensorFlow Model Benchmark Tool

### ISSUE THREAD

**Issue by ffriande** [tensorflow/tensorflow#36169]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): 
Linux Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
Couldn't run on mobile
- TensorFlow installed from (source or binary): 
source
- TensorFlow version:
Version: 1.14.0
- Python version:
2.7
- Installed using virtualenv? pip? conda?:
- Bazel version (if compiling from source): 
1.2.1
- GCC/Compiler version (if compiling from source):
7.4.0
- CUDA/cuDNN version:
- GPU model and memory:

**Describe the problem**

**Provide the exact sequence of commands / steps that you executed before running into the problem**

I followed the tutorial in https://github.com/tensorflow/tensorflow/tree/master/tensorflow/tools/benchmark#tensorflow-model-benchmark-tool , but couldn't get past the (0) step.
Ran ./configure and set ndk to 14 and then tried to run
`bazel build --cxxopt='--std=c++11' -c opt //tensorflow/examples/android:tensorflow_demo`
Also tried with 
`bazel build -c opt \
  --crosstool_top=//external:android/crosstool \
  --cpu=armeabi-v7a \
  --host_crosstool_top=@bazel_tools//tools/cpp:toolchain \
  --config monolithic \
  tensorflow/tools/benchmark:benchmark_model`

Also tried with ndk 20 and no luck. log files for 1st and 2nd run are attached

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.
2 files attached

[log_1st_run.txt](https://github.com/tensorflow/tensorflow/files/4106252/log_1st_run.txt)
[log_2nd_run.txt](https://github.com/tensorflow/tensorflow/files/4106253/log_2nd_run.txt)

**Comment by Saduf2019** [comment]
@ffriande Could you please let us know what Tensorflow version are you facing the issue on.

**Comment by ffriande** [comment]
> @ffriande Could you please let us know what Tensorflow version are you facing the issue on.

I've added it to the issue. It's Version: 1.14.0

**Comment by av8ramit** [comment]
@Saduf2019 are you able to see this on 1.15? Unfortunately I don't think we are taking any patches to 1.14 at the moment.

**Comment by Saduf2019** [comment]
@ffriande Could you please confirm if the abvoe comment helps resolve the issue.

**Comment by ymodak** [comment]
Closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
