### ISSUE TITLE
Memory leaks when doing a random tf.op on a previously converted to NumPy Tensor in TF2.1 

### ISSUE THREAD

**Issue by lerobitaille** [tensorflow/tensorflow#36164]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 16.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: Nope
- TensorFlow installed from (source or binary): binary (docker image)
- TensorFlow version (use command below): 2.1.0
- Python version: 3.6
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: 10.1
- GPU model and memory: GeForce GTX TITAN X (12Go)

**Describe the current behavior**

When converting a Tensor to NumPy before doing a random operation, there is a quite intense memory leak. Intriguingly, if we do not set a general seed or if we don't convert to numpy before doing the random operation, the leak is not happening. I really don't see why this is happening. I'm maybe doing something wrong, but I'm sceptical about it, the example code below being very very simple.

**Describe the expected behavior**

There should not be a leak.

**Code to reproduce the issue**

Here is a script that uses [memory-profiler](https://pypi.org/project/memory-profiler/) to profile memory in each functions. 

To generate the profiling data: 

`mprof run --python <script-name>`

To generate the figure below:

`mprof plot -o <figure-name>` 

```python
"""This script aims to show the memory leak that exists when tf has a
general seed and a conversion to numpy is done.
"""

import os
import random

import numpy as np
import tensorflow as tf
import tqdm


def transform_with_numpy():
    def transform(x):
        x = x.numpy() # Get a numpy version of x
        # Some NumPy operations here
        x = tf.cast(x, tf.float32) # Repass to tf version of x
        # A random TF function
        x = tf.image.random_contrast(x, 0.1, 0.8)
        return x
    return transform


def transform_with_tf():
    def transform(x):
        # Some TF operations here
        x = tf.cast(x, tf.float32) # Recast, just to isolate cause
        x = tf.image.random_contrast(x, 0.1, 0.8)
        return x
    return transform


def get_example(T):
    example = tf.cast(np.random.rand(224, 224), tf.float32)[tf.newaxis]
    return T(example)


#-----------------------------------------------------------------------


@profile
def function_with_conversion():
    T = transform_with_numpy()
    print(f'function_with_conversion')
    for i in tqdm.tqdm(range(1000)):
        examples = [get_example(T) for i in range(32)]


@profile
def function_with_seed():
    np.random.seed(100)
    random.seed(100)
    tf.random.set_seed(100)
    T = transform_with_tf()
    print(f'function_with_seed')
    for i in tqdm.tqdm(range(1000)):
        examples = [get_example(T) for i in range(32)]


@profile
def function_with_seed_and_conversion():
    np.random.seed(100)
    random.seed(100)
    tf.random.set_seed(100)
    T = transform_with_numpy()
    print(f'function_with_seed_and_conversion')
    for i in tqdm.tqdm(range(1000)):
        examples = [get_example(T) for i in range(32)]


if __name__ == '__main__':
    # Disable INFO and WARNING tf messages
    os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'

    # Sets the memory growth, experimental...
    physical_devices = tf.config.experimental.list_physical_devices('GPU')
    if physical_devices:
        tf.config.experimental.set_memory_growth(physical_devices[0], True)

    function_with_conversion()
    function_with_seed()
    function_with_seed_and_conversion()
```

**Other info / logs**

![test_mem_leak_2](https://user-images.githubusercontent.com/59838807/73010435-6aae5500-3de0-11ea-8615-1887894d7594.png)

**Maybe related to**
- https://github.com/tensorflow/tensorflow/issues/36034
- https://github.com/tensorflow/tensorflow/issues/30873

**EDIT:** 

After running the script a few more times, the output of the memory profiling data is more random than I thought. The second time I run the script, the leak disappears from the third function, but there seem to be a problem with the second function:

![test_mem_leak_all_seed2](https://user-images.githubusercontent.com/59838807/73025706-0ac6a700-3dfe-11ea-9031-592d829af162.png)

Then, I change the size of the examples to be (112, 112) and the leak reappears in the third function:

![test_mem_leak_7](https://user-images.githubusercontent.com/59838807/73025808-41042680-3dfe-11ea-8730-f70024673baa.png)

Then I rerun the code with (224, 224) sized examples and the leak reappears here as well:

![test_mem_leak_all_seed1](https://user-images.githubusercontent.com/59838807/73025871-5bd69b00-3dfe-11ea-974a-5de5f24fc897.png)

**EDIT 2:**

The memory leak is actually also there where the seed is set but no conversion is made. The conversion only makes it worst. For more details see [this repo](https://github.com/lerobitaille/tf-issue-36164-workaround).

**Comment by lerobitaille** [comment]
Do you have any workaround meanwhile?

**Comment by lerobitaille** [comment]
I've added more details about the source of the bug and a workaround at https://github.com/lerobitaille/tf-issue-36164-workaround. The memory leaks comes from the sampling of the `op_seed` in the function `tensorflow/python/framework/random_seed.py:get_seed` [here](https://github.com/tensorflow/tensorflow/blob/e5bf8de410005de06a7ff5393fafdf832ef1d4ad/tensorflow/python/framework/random_seed.py#L39).

**Comment by foxik** [comment]
I believe this may be caused by caching which `convert_to_eager_tensor` performs. Notably look at https://github.com/tensorflow/tensorflow/blob/7072568ed6b735e347fb87bc84a2b83daf806e3f/tensorflow/python/framework/constant_op.py#L68-L72 which mentions that some values can be cached.

In the C++ code, https://github.com/tensorflow/tensorflow/blob/7072568ed6b735e347fb87bc84a2b83daf806e3f/tensorflow/python/eager/pywrap_tensor.cc#L307-L313 performs the caching -- currently for Python scalars only.

**Comment by Saduf2019** [comment]
@lerobitaille 
Could you please let us know if this is still an issue in tf 2.7

**Comment by gerardcarbo** [comment]
I've just tested with a production model and it is still an issue in tf 2.7. It seems to be related with the tf.data.TFRecordDataset, as the memory load increase seems to happen while shuffling the dataset. The LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libtcmalloc_minimal.so.4 hack still does the work. Tested in linux kernel 5.4.0-91-generic with tf 2.7.0

**Comment by Venkat6871** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
