### ISSUE TITLE
tensorflow 1.15.1 produces V2 style pip with V2 enabled by default

### ISSUE THREAD

**Issue by vkuzmin-uber** [tensorflow/tensorflow#36179]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
MacOS
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
Macbook Pro
- TensorFlow installed from (source or binary):
source
- TensorFlow version:
1.15
- Python version:
2.7
- Installed using virtualenv? pip? conda?:
pip
- Bazel version (if compiling from source):
bazel-0.26.1
- GCC/Compiler version (if compiling from source):
clang
- CUDA/cuDNN version:
No
- GPU model and memory:
No

**Describe the problem**

I am building tensorflow 1.15 wheel with MKL support from sources, branch r1.15. After I installed wheel "pip install tensorflow-1.15.1-cp27-cp27m-macosx_10_14_x86_64.whl", I see no backward compatibility.

```
keras.backend.get_session()
AttributeError: 'module' object has no attribute 'get_session'
```

I suspect that the following diff https://github.com/tensorflow/tensorflow/commit/e686d9c0bafce7749a7410aa2c0304c30e498f1d disabled V1 style pip.

As result package I produces is not behaving as official 1.15 package.

is it expected?

**Provide the exact sequence of commands / steps that you executed before running into the problem**

bazel build --local_ram_resources=2048 --config=mkl -c opt --copt=-mavx --copt=-mavx2 --copt=-mfma //tensorflow/tools/pip_package:build_pip_package

Note that I don't use --config=v1 because branch itself is 1.15.

Then build a wheel 

bazel-bin/tensorflow/tools/pip_package/build_pip_package ~/tf_wheel 

it produces tensorflow-1.15.1-cp27-cp27m-macosx_10_14_x86_64.whl
After I install it, v1 code doesn't work and I see that V2 is enabled:

python
Python 2.7.16 (default, Sep  2 2019, 11:59:44)
[GCC 4.2.1 Compatible Apple LLVM 10.0.1 (clang-1001.0.46.4)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from tensorflow.python import tf2
>>> print(tf2.enabled())
True

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

pip show tensorflow
Name: tensorflow
Version: 1.15.1
Summary: TensorFlow is an open source machine learning framework for everyone.
Home-page: https://www.tensorflow.org/
Author: Google Inc.
Author-email: packages@tensorflow.org
License: Apache 2.0
Location: /Users/vkuzmin/gocode/src/code.uber.internal/data/michelangelo-deeplearning-inference/env/lib/python2.7/site-packages
Requires: keras-preprocessing, functools32, tensorflow-estimator, wheel, six, keras-applications, astor, tensorboard, wrapt, opt-einsum, termcolor, grpcio, mock, numpy, absl-py, gast, protobuf, backports.weakref, enum34, google-pasta
Required-by:

**Comment by vkuzmin-uber** [comment]
I guess that I need to checkout:

commit 590d6eef7e91a6a7392c8ffffb7b58f2e0c8bc6b (tag: v1.15.0)
Merge: 07bf6634f6 b27ac431aa
Author: Goldie Gadde <ggadde@google.com>
Date:   Mon Oct 14 14:08:43 2019 -0700

    Merge pull request #31861 from tensorflow-jenkins/relnotes-1.15.0rc0-16184

    Update release notes for TensorFlow 1.15.0

and build. But it would be great to have 1.15.1 compatible with 1.15.0 too.

**Comment by patzm** [comment]
And I think that the whole `contrib` module got removed conveniently!

**Comment by patzm** [comment]
See https://github.com/tensorflow/tensorflow/compare/v1.15.0...v1.15.1#diff-bb845bf0c867fef59b6527c0946799f9

**Comment by mihaimaruseac** [comment]
There are multiple changes here:

1. First, you need to build with `--config=v1`, even though you are on the `r1.15` branch. Default bazel config is to use `--config=v2` by default
2. We removed `contrib` and can no longer build it
3. We removed support for python 2 as it is dead.

**Comment by vkuzmin-uber** [comment]
>And I think that the whole contrib module got removed conveniently!
There are multiple changes here:

> First, you need to build with --config=v1, even though you are on the r1.15 branch. Default bazel config is to use --config=v2 by default
> We removed contrib and can no longer build it
>We removed support for python 2 as it is dead.

I'd expect that 1.15.1 is compatible with 1.15.0 and has only critical fixes./patches

Can you confirm that this Issue (no v1 style, no compatibility with 1.15.0) is a problem/bug and should be fixed? 

I think it should be a high priority, because I see 1.15.1 was officially released today, and branch has tag 1.15.1. Because if somebody upgrade to 1.15.1 that will happen for sure, with all the changes above - technically 1.15.1 is broken.

**Comment by mihaimaruseac** [comment]
Please ignore release of today, we removed it and will regenerate.

We will make `--config=v1` be the default for the branch and bring this back to be compatible with 1.15.0.

**Comment by mihaimaruseac** [comment]
`r1.15` head should be fixed now. It will take a while until we can produce the pip though

**Comment by patzm** [comment]
Can you also push the docker image for that?

**Comment by mihaimaruseac** [comment]
We never pushed a new docker image for patch releases. The image should be the same as for the main release.

**Comment by patzm** [comment]
Hm, someone seems to have done it after all: https://hub.docker.com/layers/tensorflow/tensorflow/1.15.2-gpu/images/sha256-da7b6c8a63bdafa77864e7e874664acfe939fdc140cb99940610c34b8c461cd0
Thanks to [@angersson](https://hub.docker.com/u/angersson)!

**Comment by mihaimaruseac** [comment]
Yes, I was wrong and we needed an upgrade.

I think we can close this now.

**Comment by patzm** [comment]
Yes thank you :+1:
