### ISSUE TITLE
gcc: error: unrecognized command line option '-fno-canonical-system-headers'

### ISSUE THREAD

**Issue by duanLH** [tensorflow/tensorflow#3618]
when I run : 
bazel build -c opt --config=cuda //tensorflow/cc:tutorials_example_trainer --verbose_failures
 then the output is 

duan@duan:~/tensorflow$ bazel build -c opt --config=cuda //tensorflow/cc:tutorials_example_trainer --verbose_failures
WARNING: /home/duan/.cache/bazel/_bazel_duan/9f3780f2ce96d65830e33f06d4dd8a47/external/protobuf/WORKSPACE:1: Workspace name in /home/duan/.cache/bazel/_bazel_duan/9f3780f2ce96d65830e33f06d4dd8a47/external/protobuf/WORKSPACE (@__main__) does not match the name given in the repository's definition (@protobuf); this will cause a build error in future versions.
WARNING: /home/duan/.cache/bazel/_bazel_duan/9f3780f2ce96d65830e33f06d4dd8a47/external/highwayhash/WORKSPACE:1: Workspace name in /home/duan/.cache/bazel/_bazel_duan/9f3780f2ce96d65830e33f06d4dd8a47/external/highwayhash/WORKSPACE (@__main__) does not match the name given in the repository's definition (@highwayhash); this will cause a build error in future versions.
WARNING: /home/duan/.cache/bazel/_bazel_duan/9f3780f2ce96d65830e33f06d4dd8a47/external/re2/WORKSPACE:1: Workspace name in /home/duan/.cache/bazel/_bazel_duan/9f3780f2ce96d65830e33f06d4dd8a47/external/re2/WORKSPACE (@__main__) does not match the name given in the repository's definition (@re2); this will cause a build error in future versions.
INFO: Found 1 target...
ERROR: /home/duan/.cache/bazel/_bazel_duan/9f3780f2ce96d65830e33f06d4dd8a47/external/protobuf/BUILD:111:1: C++ compilation of rule '@protobuf//:protobuf' failed: crosstool_wrapper_driver_is_not_gcc failed: error executing command 
  (cd /home/duan/.cache/bazel/_bazel_duan/9f3780f2ce96d65830e33f06d4dd8a47/execroot/tensorflow && \
  exec env - \
    PATH=/home/duan/bin:/usr/local/cuda-8.0/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/duan/.bazel/bin \
  third_party/gpus/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc -U_FORTIFY_SOURCE '-D_FORTIFY_SOURCE=1' -fstack-protector -fPIE -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 -DNDEBUG -ffunction-sections -fdata-sections -g0 '-std=c++11' '-frandom-seed=bazel-out/host/bin/external/protobuf/_objs/protobuf/external/protobuf/src/google/protobuf/message.o' -iquote external/protobuf -iquote bazel-out/host/genfiles/external/protobuf -iquote external/bazel_tools -iquote bazel-out/host/genfiles/external/bazel_tools -isystem external/protobuf/src -isystem bazel-out/host/genfiles/external/protobuf/src -isystem external/bazel_tools/tools/cpp/gcc3 -DHAVE_PTHREAD -Wall -Wwrite-strings -Woverloaded-virtual -Wno-sign-compare '-Wno-error=unused-function' -no-canonical-prefixes -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -fno-canonical-system-headers -MD -MF bazel-out/host/bin/external/protobuf/_objs/protobuf/external/protobuf/src/google/protobuf/message.d -c external/protobuf/src/google/protobuf/message.cc -o bazel-out/host/bin/external/protobuf/_objs/protobuf/external/protobuf/src/google/protobuf/message.o): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
gcc: error: unrecognized command line option '-fno-canonical-system-headers'
Target //tensorflow/cc:tutorials_example_trainer failed to build
INFO: Elapsed time: 0.784s, Critical Path: 0.14s

**Comment by poxvoculi** [comment]
This sounds like a bazel issue, rather than TensorFlow.  Please ask your question at https://github.com/bazelbuild/bazel/issues

**Comment by Anida-qin** [comment]
I come with the same problem. Have you solved already?
