### ISSUE TITLE
Functions removed from tensorflow namespace between 1.15.0 and 1.15.1

### ISSUE THREAD

**Issue by chriselion** [tensorflow/tensorflow#36188]
I'm not sure if this was intended behavior, but if so it wasn't documented in the 1.15.1 release notes. I first hit this for `tf.set_random_seed()`, but it even effects the sample code for getting the version.

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): no
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): macOS 10.14.6
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: n/a
- TensorFlow installed from (source or binary): pip (binary wheel)
- TensorFlow version (use command below): `v1.15.0-85-gfdb85890df 1.15.1`
- Python version:` Python 3.7.3 (default, Mar 27 2019, 09:23:15)  [Clang 10.0.1 (clang-1001.0.46.3)]`
- Bazel version (if compiling from source): n/a
- GCC/Compiler version (if compiling from source): n/a
- CUDA/cuDNN version: n/a
- GPU model and memory: n/a

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
Methods/variables such as tensorflow.set_random_seed and tensorflow.VERSION were present in tensorflow 1.15.0 but are removed in 1.15.1

**Describe the expected behavior**
The interface should be identical between 1.15.0 and 1.15.1.

**Code to reproduce the issue**
```shell
# Works as expected
$ pip install -q tensorflow==1.15.0
$ python -c "import tensorflow as tf; tf.set_random_seed(42)"
# Same command fails on 1.15.1
$ pip install -q tensorflow==1.15.1
$ python -c "import tensorflow as tf; tf.set_random_seed(42)"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: module 'tensorflow' has no attribute 'set_random_seed'
```
Using the provided sample code to get the tensorflow version:
```shell
$ pip install -q tensorflow==1.15.0
$ python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"
v1.15.0-rc3-22-g590d6eef7e 1.15.0

# TF 1.0 interface fails
$ pip install -q tensorflow==1.15.1
$ python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: module 'tensorflow' has no attribute 'GIT_VERSION'

# TF 2.0 interface succeeds
$ python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"
v1.15.0-85-gfdb85890df 1.15.1
```

**Comment by chriselion** [comment]
I've worked around this in my code by using `tensorflow.compat.v1` instead, but I wouldn't expect such a major change to happen in a bugfix release.

**Comment by chriselion** [comment]
Sounds like this might be the same root cause as https://github.com/tensorflow/tensorflow/issues/36179 ?

**Comment by mihaimaruseac** [comment]
It is the same root cause. Sorry about that.

**Comment by chriselion** [comment]
No problem, thanks for confirming.
