### ISSUE TITLE
./build_aarch64_lib.sh fails in densify.cc

### ISSUE THREAD

**Issue by aselva-eb** [tensorflow/tensorflow#36184]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version:
- Python version:
- Installed using virtualenv? pip? conda?:
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Describe the problem**
Unable to build the  TensorFlow Lite static library for ARM64  using the master branch of the repo. It fails during compilation (logs added at the bottom)

**Provide the exact sequence of commands / steps that you executed before running into the problem**

Using the following instructions to build tensorflow lite for arm64
https://www.tensorflow.org/lite/guide/build_arm64

**Any other info / logs**

`aarch64-linux-gnu-g++ -O3 -DNDEBUG -fPIC  --std=c++11 -march=armv8-a -funsafe-math-optimizations -ftree-vectorize -fPIC -I. -I/root/tensorflow/tensorflow/lite/tools/make/../../../../../ -I/root/tensorflow/tensorflow/lite/tools/make/../../../../../../ -I/root/tensorflow/tensorflow/lite/tools/make/downloads/ -I/root/tensorflow/tensorflow/lite/tools/make/downloads/eigen -I/root/tensorflow/tensorflow/lite/tools/make/downloads/absl -I/root/tensorflow/tensorflow/lite/tools/make/downloads/gemmlowp -I/root/tensorflow/tensorflow/lite/tools/make/downloads/neon_2_sse -I/root/tensorflow/tensorflow/lite/tools/make/downloads/farmhash/src -I/root/tensorflow/tensorflow/lite/tools/make/downloads/flatbuffers/include -I/root/tensorflow/tensorflow/lite/tools/make/downloads/fp16/include -I -I/usr/local/include \
-o /root/tensorflow/tensorflow/lite/tools/make/gen/aarch64_armv8-a/bin/minimal /root/tensorflow/tensorflow/lite/tools/make/gen/aarch64_armv8-a/obj/tensorflow/lite/examples/minimal/minimal.o \
 /root/tensorflow/tensorflow/lite/tools/make/gen/aarch64_armv8-a/lib/libtensorflow-lite.a -Wl,--no-export-dynamic -Wl,--exclude-libs,ALL -Wl,--gc-sections -Wl,--as-needed -lrt -lstdc++ -lpthread -lm -ldl
/root/tensorflow/tensorflow/lite/tools/make/gen/aarch64_armv8-a/lib/libtensorflow-lite.a(densify.o): In function `tflite::ops::builtin::densify::Eval(TfLiteContext*, TfLiteNode*)':
densify.cc:(.text+0x378): undefined reference to `tflite::optimize::sparsity::FormatConverter<signed char>::FormatConverter(std::vector<int, std::allocator<int> > const&, TfLiteSparsity const&)'
densify.cc:(.text+0x384): undefined reference to `tflite::optimize::sparsity::FormatConverter<signed char>::SparseToDense(signed char const*)'
densify.cc:(.text+0x5f0): undefined reference to `tflite::optimize::sparsity::FormatConverter<float>::FormatConverter(std::vector<int, std::allocator<int> > const&, TfLiteSparsity const&)'
densify.cc:(.text+0x5fc): undefined reference to `tflite::optimize::sparsity::FormatConverter<float>::SparseToDense(float const*)'
collect2: error: ld returned 1 exit status
tensorflow/lite/tools/make/Makefile:286: recipe for target '/root/tensorflow/tensorflow/lite/tools/make/gen/aarch64_armv8-a/bin/minimal' failed
make: *** [/root/tensorflow/tensorflow/lite/tools/make/gen/aarch64_armv8-a/bin/minimal] Error 1
make: *** Waiting for unfinished jobs....
make: Leaving directory '/root/tensorflow'`

**Comment by ruapotato** [comment]
I'm getting something similar on the Librem5/PureOS
```
root@pureos:/home/purism/voice_cmd/tensorflow# ./tensorflow/lite/tools/make/build_aarch64_lib.sh
...
aarch64-linux-gnu-g++ -O3 -DNDEBUG -fPIC  --std=c++11 -march=armv8-a -funsafe-math-optimizations -ftree-vectorize -fPIC -I. -I/home/purism/voice_cmd/tensorflow/tensorflow/lite/tools/make/../../../../../ -I/home/purism/voice_cmd/tensorflow/tensorflow/lite/tools/make/../../../../../../ -I/home/purism/voice_cmd/tensorflow/tensorflow/lite/tools/make/downloads/ -I/home/purism/voice_cmd/tensorflow/tensorflow/lite/tools/make/downloads/eigen -I/home/purism/voice_cmd/tensorflow/tensorflow/lite/tools/make/downloads/absl -I/home/purism/voice_cmd/tensorflow/tensorflow/lite/tools/make/downloads/gemmlowp -I/home/purism/voice_cmd/tensorflow/tensorflow/lite/tools/make/downloads/neon_2_sse -I/home/purism/voice_cmd/tensorflow/tensorflow/lite/tools/make/downloads/farmhash/src -I/home/purism/voice_cmd/tensorflow/tensorflow/lite/tools/make/downloads/flatbuffers/include -I/home/purism/voice_cmd/tensorflow/tensorflow/lite/tools/make/downloads/fp16/include -I -I/usr/local/include \
-o /home/purism/voice_cmd/tensorflow/tensorflow/lite/tools/make/gen/aarch64_armv8-a/bin/minimal /home/purism/voice_cmd/tensorflow/tensorflow/lite/tools/make/gen/aarch64_armv8-a/obj/tensorflow/lite/examples/minimal/minimal.o \
 /home/purism/voice_cmd/tensorflow/tensorflow/lite/tools/make/gen/aarch64_armv8-a/lib/libtensorflow-lite.a -Wl,--no-export-dynamic -Wl,--exclude-libs,ALL -Wl,--gc-sections -Wl,--as-needed -lrt -lstdc++ -lpthread -lm -ldl
/usr/bin/ld: /home/purism/voice_cmd/tensorflow/tensorflow/lite/tools/make/gen/aarch64_armv8-a/lib/libtensorflow-lite.a(densify.o): in function `tflite::ops::builtin::densify::Eval(TfLiteContext*, TfLiteNode*)':
densify.cc:(.text+0x348): undefined reference to `tflite::optimize::sparsity::FormatConverter<signed char>::FormatConverter(std::vector<int, std::allocator<int> > const&, TfLiteSparsity const&)'
/usr/bin/ld: densify.cc:(.text+0x354): undefined reference to `tflite::optimize::sparsity::FormatConverter<signed char>::SparseToDense(signed char const*)'
/usr/bin/ld: densify.cc:(.text+0x6c0): undefined reference to `tflite::optimize::sparsity::FormatConverter<float>::FormatConverter(std::vector<int, std::allocator<int> > const&, TfLiteSparsity const&)'
/usr/bin/ld: densify.cc:(.text+0x6cc): undefined reference to `tflite::optimize::sparsity::FormatConverter<float>::SparseToDense(float const*)'
collect2: error: ld returned 1 exit status
make: *** [tensorflow/lite/tools/make/Makefile:287: /home/purism/voice_cmd/tensorflow/tensorflow/lite/tools/make/gen/aarch64_armv8-a/bin/minimal] Error 1
make: *** Waiting for unfinished jobs....
make: Leaving directory '/home/purism/voice_cmd/tensorflow'
```

**Comment by terryheo** [comment]
Confirmed. Working on this.

**Comment by aselva-eb** [comment]
Thank you. In the mean time for anyone else struggling with this issue, I was able to backtrack to an older commit of the repo:
fc7bce9b4ada6ef123b899ed88889923c9fafae6
