### ISSUE TITLE
ModuleNotFoundError: No module named 'tensorflow_estimator.contrib'

### ISSUE THREAD

**Issue by monocongo** [tensorflow/tensorflow#36193]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04
- TensorFlow installed from (source or binary):
I have installed tensorflow into my conda environment via `pip install tensorflow`
It shows as version 2.1.0 when I list the installed version, but when I import tensorflow within a Python interpreter I see version 1.15.0-rc1
```
$ conda list tensorflow
# packages in environment at /home/james/miniconda3/envs/deeplab:
#
# Name                    Version                   Build  Channel
tensorflow                2.1.0                    pypi_0    pypi
tensorflow-estimator      2.1.0                    pypi_0    pypi

$ python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"
v1.15.0-rc1-42-g5adb433 1.15.0-rc2
```
- TensorFlow version (use command below): I am not sure, based on the above.
- Python version: Python 3.7.6

**Describe the current behavior**
I am trying to run the [DeepLab example](https://github.com/tensorflow/models/blob/master/research/deeplab/g3doc/pascal.md) using this command:
```
$ python deeplab/train.py \
    --logtostderr \
    --training_number_of_steps=30000 \
    --train_split="train" \
    --model_variant="xception_65" \
    --atrous_rates=6 \
    --atrous_rates=12 \
    --atrous_rates=18 \
    --output_stride=16 \
    --decoder_output_stride=4 \
    --train_crop_size="513,513" \
    --train_batch_size=1 \
    --dataset="basins" \
    --tf_initial_checkpoint=/home/james/deeplab/pretrained/x65-b2u1s2p-d48-2-3x256-sc-cr300k_init.ckpt.data-00000-of-00001 \
    --train_logdir=./deeplab/datasets/basins/exp/train_on_train_set/train \
    --dataset_dir=./deeplab/datasets/basins
```
I get the following output/error:
```
Traceback (most recent call last):
  File "deeplab/train.py", line 26, in <module>
    from tensorflow.contrib import quantize as contrib_quantize
  File "/home/james/.local/lib/python3.7/site-packages/tensorflow/__init__.py", line 50, in __getattr__
    module = self._load()
  File "/home/james/.local/lib/python3.7/site-packages/tensorflow/__init__.py", line 44, in _load
    module = _importlib.import_module(self.__name__)
  File "/home/james/miniconda3/envs/deeplab/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/james/.local/lib/python3.7/site-packages/tensorflow_core/contrib/__init__.py", line 48, in <module>
    from tensorflow.contrib import estimator
  File "/home/james/.local/lib/python3.7/site-packages/tensorflow_core/contrib/estimator/__init__.py", line 30, in <module>
    from tensorflow_estimator.contrib import estimator
ModuleNotFoundError: No module named 'tensorflow_estimator.contrib'
```

**Describe the expected behavior**
I am hoping that the model will train as advertised.

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.
```
$ python -c 'import tensorflow as tf; tf.contrib.summary'
```

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by ashutosh1919** [comment]
@monocongo, I understood your problem. I have found out [this past issue](https://github.com/tensorflow/tensorflow/issues/23163) in which somebody else had the same problem. But with the below solution, it worked fine. 

Try this after installing tensorflow : 
```sh
$ pip install -U tensorflow_estimator
```
Thanks to [this](https://github.com/tensorflow/tensorflow/issues/23163#issuecomment-449767938).

**Comment by monocongo** [comment]
Thanks, @ashutosh1919 . I actually saw this before posting and tried the suggestions there to no avail. For example:
```
$ pip install -U tensorflow_estimator
Requirement already up-to-date: tensorflow_estimator in /home/james/miniconda3/envs/deeplab/lib/python3.7/site-packages (2.1.0)
```

**Comment by ashutosh1919** [comment]
> Thanks, @ashutosh1919 . I actually saw this before posting and tried the suggestions there to no avail. For example:
> 
> ```
> $ pip install -U tensorflow_estimator
> Requirement already up-to-date: tensorflow_estimator in /home/james/miniconda3/envs/deeplab/lib/python3.7/site-packages (2.1.0)
> ```

try [this one](https://github.com/tensorflow/tensorflow/issues/23163#issuecomment-509178978). (Reinstallation may help)

**Comment by monocongo** [comment]
@ashutosh1919  That did the trick. Thanks so much for your help!

**Comment by ashutosh1919** [comment]
> @ashutosh1919 That did the trick. Thanks so much for your help!

@monocongo , You're most welcome.

**Comment by Monkey1GIt** [comment]
I also have the same problem when I'm running Tensorflow model object detection API in Win10, Python3.7, tensorflow 1.15. I try `pip install -U tensorflow_estimator` as @ashutosh1919 suggested, but it didn't work. I solve the problem for these steps:
1. `pip list` 
2. make sure your pip install packages like this:
![Snipaste_2020-02-20_15-22-49](https://user-images.githubusercontent.com/43908098/74911323-51a4be00-53f7-11ea-8c47-d9848760218e.png)

**Comment by ashutosh1919** [comment]
@Monkey1GIt , 
`pip install -U tensorflow_estimator` didn't help to @monocongo  too. What helped him is [this one](https://github.com/tensorflow/tensorflow/issues/23163#issuecomment-509178978). The reinstallation of the same helps. Please just change the version correctly as per your requirements.

**Comment by daryl-user** [comment]
Hi, for those who still have problems, here's my experience:
Ensure that you are importing tensorflow_estimator.contrib via the correct path. I realized my path to TensorFlow and path to tensorflow_estimator were different, whereby even though I did have tensorflow_estimator.contrib, my system path went the wrong way. Here's how to check:

import tensorflow_estimator
print(tensorflow_estimator.__file__) 

If you realize the path given is incorrect, then do the following:
import sys
sys.path.remove('insert_your_incorrect_path') 

Now, python will not scan the incorrect path and should be forced to look for tensorflow_estimator in the correct path. 

I'm a beginner, so if this mistake looks stupid, I'm sorry :(

**Comment by mihaimaruseac** [comment]
The solution is to `pip list`, identify all tensorflow ecosystem packages that are *NOT* on 1.15 and reinstall those to 1.15.

`contrib` only exists in 1.15; installing any component at a later version will create issues.

For example, in https://github.com/tensorflow/tensorflow/issues/36193#issuecomment-588692406 you also need to uninstall `tensorflow-gpu-estimator`

**Comment by Maryammhsnv** [comment]
How we can Uninstall tensorflow-estimator and install the compatible version?
First I had tf 2.1 but I was forced to downgrade to tf 1.15 and now I get this error with 
tf estimator since it's still 2.1. Could you please help me?

**Comment by Maryammhsnv** [comment]
when I use pip install 'tensorflow-estimator<1.15.0rc0,>=1.14.0rc0' --force-reinstall
I get the following error.
The system cannot find the file specified.

**Comment by mihaimaruseac** [comment]
@Maryammhsnv `pip uninstall` or simply delete the files in `site-packages`. You can also create a new virtual environment. These are not issues related to TensorFlow, so let's not derail discussion.

**Comment by mesmerli** [comment]
Mine is based on TensorFlow 2.0.
The following changes works for me.

$ vi /home/xxxx/.local/lib/python3.6/site-packages/tensorflow_core/contrib/estimator/__init__.py 
.....
 30 from tensorflow_estimator import estimator
 31 #from tensorflow_estimator.contrib import estimator
....
 40 import tensorflow_core.contrib.estimator.python
 41 #import tensorflow.contrib.estimator.python
.....
 47 #from tensorflow_estimator.contrib.estimator import *
 48 from tensorflow.python.util.all_util import remove_undocumented

=====================

By the way, such incompatibility wastes many people's time. 
Are there no ways to maintain such path issues before the release?
In addition, the support team could support that in a better manner.

**Comment by mihaimaruseac** [comment]
We don't really support `--config=v1` on the after 2.0 world.
