### ISSUE TITLE
Copyright years in the files

### ISSUE THREAD

**Issue by generationzcode** [tensorflow/tensorflow#36200]
This template is for miscellaneous issues not covered by the other issue categories.

For questions on how to work with TensorFlow, or support for problems that are not verified bugs in TensorFlow, please go to [StackOverflow](https://stackoverflow.com/questions/tagged/tensorflow).

If you are reporting a vulnerability, please use the [dedicated reporting process](https://github.com/tensorflow/tensorflow/blob/master/SECURITY.md).

For high-level discussions about TensorFlow, please post to discuss@tensorflow.org, for questions about the development or internal workings of TensorFlow, or if you would like to know how to contribute to TensorFlow, please post to developers@tensorflow.org.

Umm, a lot of the files have copyright 2015 (or some other year) shouldn't they be 2020?
I dont really know whether this is right or wrong... I'm just posting what I saw in the files

**Comment by Matoran** [comment]
Hi, that is not how it works. You can find a lot of ressources with a simple search like `copyright year`.  One good explanation: https://stackoverflow.com/questions/2390230/do-copyright-dates-need-to-be-updated

**Comment by mihaimaruseac** [comment]
Closing as it is not really an issue. Plus, @Matoran provided a reasoning

**Comment by generationzcode** [comment]
thanks!
