### ISSUE TITLE
unable to use TimeseriesGenerator with fit_generator

### ISSUE THREAD

**Issue by Matoran** [tensorflow/tensorflow#36203]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Mint 19.3 Tricia
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): binary from pip
- TensorFlow version (use command below): v2.1.0-rc2-17-ge5bf8de 2.1.0
- Python version: Python 3.6.9
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 10.1
- GPU model and memory: GeForce GTX 970 4GB

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
`fit_generator`or `fit` can't handle a `TimeSeriesGenerator`
**Describe the expected behavior**
Should be handled
**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.
```python
# if we uncomment this line and comment the next one no more problems 
# import keras # version 2.3.1
from tensorflow import keras # version 2.2.4-tf
import numpy as np
from keras.preprocessing.sequence import TimeseriesGenerator
print(keras.__version__)
# define dataset
series = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
# define generator
n_input = 2
generator = TimeseriesGenerator(series, series, length=n_input, batch_size=8)

model = keras.Sequential([
    keras.layers.Dense(1, activation='relu', input_dim=2),
    keras.layers.Dense(1)
])

model.compile(optimizer='adam', loss='sparse_categorical_crossentropy')

model.fit_generator(generator, steps_per_epoch=1, epochs=10)
```
**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-18-603f0c2b45d6> in <module>
     17 model.compile(optimizer='adam', loss='sparse_categorical_crossentropy')
     18 
---> 19 model.fit_generator(generator, steps_per_epoch=1, epochs=10)

~/master/.venv/lib/python3.6/site-packages/tensorflow_core/python/util/deprecation.py in new_func(*args, **kwargs)
    322               'in a future version' if date is None else ('after %s' % date),
    323               instructions)
--> 324       return func(*args, **kwargs)
    325     return tf_decorator.make_decorator(
    326         func, new_func, 'deprecated',

~/master/.venv/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training.py in fit_generator(self, generator, steps_per_epoch, epochs, verbose, callbacks, validation_data, validation_steps, validation_freq, class_weight, max_queue_size, workers, use_multiprocessing, shuffle, initial_epoch)
   1304         use_multiprocessing=use_multiprocessing,
   1305         shuffle=shuffle,
-> 1306         initial_epoch=initial_epoch)
   1307 
   1308   @deprecation.deprecated(

~/master/.venv/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training.py in fit(self, x, y, batch_size, epochs, verbose, callbacks, validation_split, validation_data, shuffle, class_weight, sample_weight, initial_epoch, steps_per_epoch, validation_steps, validation_freq, max_queue_size, workers, use_multiprocessing, **kwargs)
    817         max_queue_size=max_queue_size,
    818         workers=workers,
--> 819         use_multiprocessing=use_multiprocessing)
    820 
    821   def evaluate(self,

~/master/.venv/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training_v2.py in fit(self, model, x, y, batch_size, epochs, verbose, callbacks, validation_split, validation_data, shuffle, class_weight, sample_weight, initial_epoch, steps_per_epoch, validation_steps, validation_freq, max_queue_size, workers, use_multiprocessing, **kwargs)
    233           max_queue_size=max_queue_size,
    234           workers=workers,
--> 235           use_multiprocessing=use_multiprocessing)
    236 
    237       total_samples = _get_total_number_of_samples(training_data_adapter)

~/master/.venv/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training_v2.py in _process_training_inputs(model, x, y, batch_size, epochs, sample_weights, class_weights, steps_per_epoch, validation_split, validation_data, validation_steps, shuffle, distribution_strategy, max_queue_size, workers, use_multiprocessing)
    531                      'at same time.')
    532 
--> 533   adapter_cls = data_adapter.select_data_adapter(x, y)
    534 
    535   # Handle validation_split, we want to split the data and get the training

~/master/.venv/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/data_adapter.py in select_data_adapter(x, y)
    996         "Failed to find data adapter that can handle "
    997         "input: {}, {}".format(
--> 998             _type_name(x), _type_name(y)))
    999   elif len(adapter_cls) > 1:
   1000     raise RuntimeError(

ValueError: Failed to find data adapter that can handle input: <class 'keras.preprocessing.sequence.TimeseriesGenerator'>, <class 'NoneType'>
```
If you need more logs just ask :).

**Comment by gadagashwini** [comment]
Was able to reproduce the issue with Tf 2.1.
Please find the gist [here](https://colab.research.google.com/gist/gadagashwini/b4ffb529c9f547b739dcb41b4a6cfe73/untitled358.ipynb). Thanks!

**Comment by gowthamkpr** [comment]
@Matoran I used a different code to test TimeseriesGenerator with fit_generator. Heres my [gist](https://colab.sandbox.google.com/gist/gowthamkpr/994a11657986b250976f2ec252abe1e0/untitled284.ipynb)

I am not running into any error using tf-nightly. Please take a look at it.

You can also find the code that I used [here](https://github.com/Tony607/Keras_TimeseriesGenerator). Thanks!

**Comment by Matoran** [comment]
@gowthamkpr next time I should test tf-nightly before opening an issue :p. Thanks
