### ISSUE TITLE
Report "model_pruner failed: Invalid argument: Invalid input graph." when i call C++ API

### ISSUE THREAD

**Issue by jkkj1630** [tensorflow/tensorflow#36217]
model format ".pb"
python are success to predict, input dim is {1,512},code like this:

sess = tf.Session()
graph = tf.get_default_graph()
with tf.gfile.FastGFile('./model_tags.pb','rb') as f:
	graph_def = tf.GraphDef()
	graph_def.ParseFromString(f.read())
	sess.graph.as_default()
	g_in = tf.import_graph_def(graph_def)
	tensor_input = sess.graph.get_tensor_by_name('import/input_1:0')
	tensor_output = sess.graph.get_tensor_by_name('import/time_distributed_1/Reshape_1:0')
	predictions = sess.run(tensor_output, {tensor_input: np.expand_dims(str_word_list_np, axis=0)})

when i call c++ api,code:

    tensorflow::Session *m_pTFSes;
    tensorflow::GraphDef m_grBiLSTM;
    tensorflow::Status status = tensorflow::NewSession(tensorflow::SessionOptions(), &m_pTFSes);
    if (!status.ok())
    {
        std::cout << status.ToString() << "\n";
        return false;
    }
    status = tensorflow::ReadBinaryProto(tensorflow::Env::Default(), "model_tags.pb", &m_grBiLSTM);
    if (!status.ok())
    {
        std::cout << status.ToString() << "\n";
        return false;
    }
    status = m_pTFSes->Create(m_grBiLSTM);
    if (!status.ok())
    {
        std::cout << status.ToString() << "\n";
        return false;
    }
    tensorflow::Tensor tInput(tensorflow::DT_INT32, tensorflow::TensorShape({ 1, 512 }));
    int*pSeq = tInput.flat<int>().data();
    std::vector<std::string> vecLetters;
    SplitString(strText, vecLetters);
    for(int i = 0;i < 512;i++)
    {
        if(i < vecLetters.size())
        {
            pSeq[i] = m_umLetters[vecLetters[i]];
        }
        else
        {
            pSeq[i] = 0;
        }
    }
    std::vector<std::pair<std::string, tensorflow::Tensor>> inSeq;
    inSeq.push_back(std::make_pair("import/input_1:0", tInput));
    std::vector<tensorflow::Tensor> outSeq;
    m_pTFSes->Run(inSeq, {"import/time_distributed_1/Reshape_1:0"}, {}, &outSeq);

that report 
2020-01-26 04:16:36.014125: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:562] model_pruner failed: Invalid argument: Invalid input graph.
2020-01-26 04:16:36.525743: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:562] model_pruner failed: Invalid argument: Invalid input graph.

**Comment by mihaimaruseac** [comment]
Please properly format all code blocks using ` ``` ` and also fill in the issue template.

**Comment by gadagashwini** [comment]
@jkkj1630, Please fill the issue [Template](https://github.com/tensorflow/tensorflow/issues/new/choose).

**Comment by mihaimaruseac** [comment]
@jkkj1630 when closing the issue, please also update if it was user error or how you fixed the issue. This will allow others encountering the same problem to get to a fix faster.

**Comment by bazako** [comment]
@jkkj1630 you can post your solution to fix the issue?
