### ISSUE TITLE
external/pybind11\include/pybind11/pybind11.h(139): error C2783: “std::tuple<pybind11::detail::type_caster<pybind11::handle,void>>::tuple(void) noexcept(<expr>)”: 未能为“__formal”推导 模板 参数

### ISSUE THREAD

**Issue by ZTZ-99** [tensorflow/tensorflow#36229]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):Windows 10 1903
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary):source
- TensorFlow version:1.15.0
- Python version: Python 3.6.8rc1
- Installed using virtualenv? pip? conda?: N/A
- Bazel version (if compiling from source):0.25.0
- GCC/Compiler version (if compiling from source):VS2017 MSVC 14.16.27023
- CUDA/cuDNN version:10.2/7.0
- GPU model and memory: GTX1070 8.0GB

**Describe the problem**
使用bazel编译TensorFlow时提示 
external/pybind11\include/pybind11/pybind11.h(139): error C2783: “std::tuple<pybind11::detail::type_caster<pybind11::handle,void>>::tuple(void) noexcept(<expr>)”: 未能为“__formal”推导 模板 参数

**Provide the exact sequence of commands / steps that you executed before running into the problem**

按照https://www.tensorflow.org/install/source_windows?hl=zh-cn#cpu配置

**Any other info / logs**

注意: 包含文件:   F:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.16.27023\include\sstream
external/pybind11\include/pybind11/pybind11.h(139): error C2783: “std::tuple<pybind11::detail::type_caster<pybind11::handle,void>>::tuple(void) noexcept(<expr>)”: 未能为“__formal”推导 模板 参数
F:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.16.27023\include\tuple(429): note: 参见“std::tuple<pybind11::detail::type_caster<pybind11::handle,void>>::tuple”的声明
external/pybind11\include/pybind11/pybind11.h(73): note: 参见对正在编译的函数 模板 实例化“void pybind11::cpp_function::initialize<_Ty,R,pybind11::handle,pybind11::is_method>(Func &&,Return (__cdecl *)(pybind11::handle),const pybind11::is_method &)”的引用
        with
        [
            _Ty=pybind11::detail::enum_base::init::<lambda_46073d681fcd766eb481a3d0374dc63b>,
            R=pybind11::str,
            Func=pybind11::detail::enum_base::init::<lambda_46073d681fcd766eb481a3d0374dc63b>,
            Return=pybind11::str
        ]
external/pybind11\include/pybind11/pybind11.h(1416): note: 参见对正在编译的函数 模板 实例化“pybind11::cpp_function::cpp_function<pybind11::detail::enum_base::init::<lambda_46073d681fcd766eb481a3d0374dc63b>,pybind11::is_method,void>(Func &&,const pybind11::is_method &)”的引用
        with
        [
            Func=pybind11::detail::enum_base::init::<lambda_46073d681fcd766eb481a3d0374dc63b>
        ]
c:\users\reshiram\_bazel_reshiram\qnykyiqk\execroot\org_tensorflow\external\pybind11\include\pybind11\cast.h(1556): note: 参见对正在编译的 类 模板 实例化 "pybind11::detail::descr<8>" 的引用
c:\users\reshiram\_bazel_reshiram\qnykyiqk\execroot\org_tensorflow\external\pybind11\include\pybind11\cast.h(1554): note: 参见对正在编译的 类 模板 实例化 "pybind11::detail::descr<5>" 的引用
c:\users\reshiram\_bazel_reshiram\qnykyiqk\execroot\org_tensorflow\external\pybind11\include\pybind11\cast.h(1109): note: 参见对正在编译的 类 模板 实例化 "pybind11::detail::descr<7>" 的引用
external/pybind11\include/pybind11/pybind11.h(139): error C2783: “std::tuple<pybind11::detail::type_caster<pybind11::object,void>,pybind11::detail::type_caster<pybind11::object,void>>::tuple(void) noexcept(<expr>)”: 未能为“__formal”推导 模板 参数
F:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.16.27023\include\tuple(429): note: 参见“std::tuple<pybind11::detail::type_caster<pybind11::object,void>,pybind11::detail::type_caster<pybind11::object,void>>::tuple”的声明
external/pybind11\include/pybind11/pybind11.h(73): note: 参见对正在编译的函数 模板 实例化“void pybind11::cpp_function::initialize<_Ty,R,pybind11::object,pybind11::object,pybind11::is_method>(Func &&,Return (__cdecl *)(pybind11::object,pybind11::object),const pybind11::is_method &)”的引用
        with
        [
            _Ty=pybind11::detail::enum_base::init::<lambda_ea06563a4979ca80a55a8ff1d879382b>,
            R=bool,
            Func=pybind11::detail::enum_base::init::<lambda_ea06563a4979ca80a55a8ff1d879382b>,
            Return=bool
        ]
external/pybind11\include/pybind11/pybind11.h(1474): note: 参见对正在编译的函数 模板 实例化“pybind11::cpp_function::cpp_function<pybind11::detail::enum_base::init::<lambda_ea06563a4979ca80a55a8ff1d879382b>,pybind11::is_method,void>(Func &&,const pybind11::is_method &)”的引用
        with
        [
            Func=pybind11::detail::enum_base::init::<lambda_ea06563a4979ca80a55a8ff1d879382b>
        ]
external/pybind11\include/pybind11/pybind11.h(139): error C2783: “std::tuple<pybind11::detail::type_caster<pybind11::object,void>>::tuple(void) noexcept(<expr>)”: 未能为“__formal”推导 模板 参数
F:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.16.27023\include\tuple(429): note: 参见“std::tuple<pybind11::detail::type_caster<pybind11::object,void>>::tuple”的声明
external/pybind11\include/pybind11/pybind11.h(73): note: 参见对正在编译的函数 模板 实例化“void pybind11::cpp_function::initialize<_Ty,R,pybind11::object,pybind11::is_method>(Func &&,Return (__cdecl *)(pybind11::object),const pybind11::is_method &)”的引用
        with
        [
            _Ty=pybind11::detail::enum_base::init::<lambda_909c581f503d5f259cf84551105b4f30>,
            R=pybind11::int_,
            Func=pybind11::detail::enum_base::init::<lambda_909c581f503d5f259cf84551105b4f30>,
            Return=pybind11::int_
        ]
external/pybind11\include/pybind11/pybind11.h(1507): note: 参见对正在编译的函数 模板 实例化“pybind11::cpp_function::cpp_function<pybind11::detail::enum_base::init::<lambda_909c581f503d5f259cf84551105b4f30>,pybind11::is_method,void>(Func &&,const pybind11::is_method &)”的引用
        with
        [
            Func=pybind11::detail::enum_base::init::<lambda_909c581f503d5f259cf84551105b4f30>
        ]
Target //tensorflow/tools/pip_package:build_pip_package failed to build
INFO: Elapsed time: 767.769s, Critical Path: 62.28s
INFO: 2518 processes: 2518 local.
FAILED: Build did NOT complete successfully

**Comment by ravikyram** [comment]
@ZTZ-99 

Make sure[ long paths are enabled ](https://superuser.com/questions/1119883/windows-10-enable-ntfs-long-paths-policy-option-missing)on Windows.Thanks!

**Comment by ZTZ-99** [comment]
我修改 long paths 的设置为enable后，旧错误没有再出现，但是出现了新的错误

注意: 包含文件:   bazel-out/x64_windows-py2-opt/bin\tensorflow/compiler/mlir/lite/ir/tfl_ops.h.inc
.\tensorflow/compiler/mlir/lite/quantization/quantization_traits.h(98): error C2976: “mlir::OpTrait::TFL::QuantizationSpecTraitBase”: 模板 参数太少
.\tensorflow/compiler/mlir/lite/quantization/quantization_traits.h(33): note: 参见“mlir::OpTrait::TFL::QuantizationSpecTraitBase”的声明
external/local_config_mlir/include\mlir/IR/OpDefinition.h(875): note: 参见对正在编译的 类 模板 实例化 "mlir::OpTrait::TFL::AccumulatorUniformScale<2,0,1>::Impl<ConcreteType>" 的引用
        with
        [
            ConcreteType=mlir::TFL::Conv2DOp
        ]
bazel-out/x64_windows-py2-opt/bin\tensorflow/compiler/mlir/lite/ir/tfl_ops.h.inc(456): note: 参见对正在编译的 类 模板 实例化 "mlir::Op<mlir::TFL::Conv2DOp,mlir::OpTrait::OneResult,mlir::OpTrait::HasNoSideEffect,mlir::OpTrait::TFL::AccumulatorUniformScale<2,0,1>::Impl,mlir::OpTrait::NOperands<3>::Impl>" 的引用
.\tensorflow/compiler/mlir/lite/quantization/quantization_traits.h(98): error C2955: “mlir::OpTrait::TFL::QuantizationSpecTraitBase”: 使用 类 模板 需要 模板 参数列表
.\tensorflow/compiler/mlir/lite/quantization/quantization_traits.h(33): note: 参见“mlir::OpTrait::TFL::QuantizationSpecTraitBase”的声明
.\tensorflow/compiler/mlir/lite/ir/tfl_traits.h(39): error C2976: “mlir::OpTrait::TraitBase”: 模板 参数太少
external/local_config_mlir/include\mlir/IR/OpDefinition.h(372): note: 参见“mlir::OpTrait::TraitBase”的声明
external/local_config_mlir/include\mlir/IR/OpDefinition.h(875): note: 参见对正在编译的 类 模板 实例化 "mlir::OpTrait::TFL::StatefulOperands<18,19>::Impl<ConcreteType>" 的引用
        with
        [
            ConcreteType=mlir::TFL::LSTMOp
        ]
bazel-out/x64_windows-py2-opt/bin\tensorflow/compiler/mlir/lite/ir/tfl_ops.h.inc(1148): note: 参见对正在编译的 类 模板 实例化 "mlir::Op<mlir::TFL::LSTMOp,mlir::OpTrait::OneResult,mlir::OpTrait::TFL::StatefulOperands<18,19>::Impl,mlir::OpTrait::NOperands<24>::Impl>" 的引用
.\tensorflow/compiler/mlir/lite/ir/tfl_traits.h(39): error C2955: “mlir::OpTrait::TraitBase”: 使用 类 模板 需要 模板 参数列表
external/local_config_mlir/include\mlir/IR/OpDefinition.h(372): note: 参见“mlir::OpTrait::TraitBase”的声明
注意: 包含文件:  external/local_config_mlir/include\mlir/Dialect/StandardOps/Ops.h
注意: 包含文件:   bazel-out/x64_windows-py2-opt/bin/external/local_config_mlir/include\mlir/Dialect/StandardOps/Ops.h.inc
注意: 包含文件:  external/local_config_mlir/include\mlir/IR/Matchers.h
注意: 包含文件:  external/local_config_mlir/include\mlir/IR/OpImplementation.h
注意: 包含文件:   external/llvm/include\llvm/Support/SMLoc.h
注意: 包含文件:    F:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.16.27023\include\cassert
注意: 包含文件:     F:\Windows Kits\10\include\10.0.18362.0\ucrt\assert.h
注意: 包含文件:   external/llvm/include\llvm/Support/raw_ostream.h
注意: 包含文件:    F:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.16.27023\include\cassert
注意: 包含文件:     F:\Windows Kits\10\include\10.0.18362.0\ucrt\assert.h
注意: 包含文件:  external/local_config_mlir/include\mlir/IR/PatternMatch.h
注意: 包含文件:  external/local_config_mlir/include\mlir/IR/TypeUtilities.h
注意: 包含文件:  .\tensorflow/compiler/mlir/tensorflow/ir/tf_types.h
注意: 包含文件:   .\tensorflow/compiler/mlir/tensorflow/ir/tf_types.def
注意: 包含文件:   .\tensorflow/compiler/mlir/tensorflow/ir/tf_types.def
注意: 包含文件:  bazel-out/x64_windows-py2-opt/bin\tensorflow/compiler/mlir/lite/ir/tfl_ops.cc.inc
注意: 包含文件:  bazel-out/x64_windows-py2-opt/bin\tensorflow/compiler/mlir/lite/ir/tfl_ops.cc.inc
Target //tensorflow/tools/pip_package:build_pip_package failed to build
INFO: Elapsed time: 3304.075s, Critical Path: 622.61s
INFO: 2350 processes: 2350 local.
FAILED: Build did NOT complete successfully

**Comment by ZTZ-99** [comment]
我切换到了r1.12版本，并打开long paths配置后，编译过程可以顺利完成了，但是在最后生成结果时报告：
ERROR: C:/tensorflow/tensorflow/BUILD:533:1: Executing genrule //tensorflow:tf_python_api_gen_v1 failed (Exit 127): bash.exe failed: error executing command
  cd C:/users/reshiram/_bazel_reshiram/xv6zejqw/execroot/org_tensorflow
  SET CUDA_TOOLKIT_PATH=F:/CUDA10.2
    SET CUDNN_INSTALL_PATH=F:/CUDA10.2
    SET PATH=F:\msys64\usr\bin;F:\msys64\bin;F:\CUDA10.2\bin;F:\CUDA10.2\libnvvp;D:\Program Files (x86)\NetSarang\Xshell 6\;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;F:\Python27;F:\Program Files\CMake\bin;C:\Program Files\NVIDIA Corporation\Nsight Compute 2019.5.0\;F:\CUDA10.2\lib\x64;F:\Python27\Scripts;F:\OpenCV4.2.0\opencv\lib\install\x64\vc16\bin;F:\OpenCV4.2.0\opencv\build\bin;F:\CUDA10.2\include;F:\Python36\Scripts;F:\Python36;F:\Program Files\Git\cmd;F:\ROS\swigwin-4.0.1;F:\ROS\bazel;F:\msys64\usr\bin;F:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.16.27023\include;C:\Users\Reshiram\AppData\Local\Microsoft\WindowsApps
    SET PYTHON_BIN_PATH=F:/Python36/python3.exe
    SET PYTHON_LIB_PATH=F:/Python36/lib/site-packages
    SET TF_CUDA_COMPUTE_CAPABILITIES=6.1
    SET TF_NEED_CUDA=1
    SET TF_NEED_OPENCL_SYCL=0
    SET TF_NEED_ROCM=0
  F:/msys64/usr/bin/bash.exe -c source external/bazel_tools/tools/genrule/genrule-setup.sh; bazel-out/x64_windows-opt/bin/tensorflow/create_tensorflow.python_api_1.exe --root_init_template=tensorflow/api_template.__init__.py --apidir=bazel-out/x64_windows-opt/genfiles/tensorflow_api/v1/ --apiname=tensorflow --apiversion=1 --package=tensorflow.python --output_package=tensorflow._api.v1 bazel-out/x64_windows-opt/genfiles/tensorflow/_api/v1/__init__.py bazel-out/x64_windows-opt/genfiles/tensorflow/_api/v1/app/__init__.py bazel-out/x64_windows-opt/genfiles/tensorflow/_api/v1/bitwise/__init__.py bazel-out/x64_windows-opt/genfiles/tensorflow/_api/v1/compat/__init__.py bazel-out/x64_windows-opt/genfiles/tensorflow/_api/v1/data/__init__.py bazel-out/x64_windows-opt/genfiles/tensorflow/_api/v1/data/experimental/__init__.py bazel-out/x64_windows-opt/genfiles/tensorflow/_api/v1/debugging/__init__.py bazel-out/x64_windows-opt/genfiles/tensorflow/_api/v1/distributions/__init__.py bazel-out/x64_windows-opt/genfiles/tensorflow/_api/v1/dtypes/__init__.py bazel-out/x64_windows-opt/genfiles/tensorflow/_api/v1/errors/__init__.py bazel-out/x64_windows-opt/genfiles/tensorflow/_api/v1/feature_column/__init__.py bazel-out/x64_windows-opt/genfiles/tensorflow/_api/v1/gfile/__init__.py bazel-out/x64_windows-opt/genfiles/tensorflow/_api/v1/graph_util/__init__.py bazel-out/x64_windows-opt/genfiles/tensorflow/_api/v1/image/__init__.py bazel-out/x64_windows-opt/genfiles/tensorflow/_api/v1/io/__init__.py bazel-out/x64_windows-opt/genfiles/tensorflow/_api/v1/initializers/__init__.py bazel-out/x64_windows-opt/genfiles/tensorflow/_api/v1/keras/__init__.py bazel-out/x64_windows-opt/genfiles/tensorflow/_api/v1/keras/activations/__init__.py bazel-out/x64_windows-opt/genfiles/tensorflow/_api/v1/keras/applications/__init__.py bazel-out/x64_windows-opt/genfiles/tensorflow/_api/v1/keras/applications/densenet/__init__.py bazel-out/x64_windows-opt/genfiles/tensorflow/_api/v1/keras/applications/inception_resnet_v2/__init__.py bazel-out/x64_windows-opt/genfiles/tensorflow/_api/v1/keras/applications/inception_v3/__init__.py bazel-out/x64_windows-opt/genfiles/tensorflow/_api/v1/keras/applications/mobilenet/__init__.py bazel-out/x64_windows-opt/genfiles/tensorflow/_api/v1/keras/applications/mobilenet_v2/__init__.py bazel-out/x64_windows-opt/genfiles/tensorflow/_api/v1/keras/applications/nasnet/__init__.py bazel-out/x64_windows-opt/genfiles/tensorflow/_api/v1/keras/applications/resnet50/__init__.py bazel-out/x64_windows-opt/genfiles/tensorflow/_api/v1/keras/applications/vgg16/__init__.py bazel-out/x64_windows-opt/genfiles/tensorflow/_api/v1/keras/applications/vgg19/__init__.py bazel-out/x64_windows-opt/genfiles/tensorflow/_api/v1/keras/applications/xception/__init__.py bazel-out/x64_windows-opt/genfiles/tensorflow/_api/v1/keras/backend/__init__.py bazel-out/x64_windows-opt/genfiles/tensorflow/_api/v1/keras/callbacks/__init__.py bazel-out/x64_windows-opt/genfiles/tensorflow/_api/v1/keras/constraints/__init__.py bazel-out/x64_windows-opt/genfiles/tensorflow/_api/v1/keras/datasets/__init__.py bazel-out/x64_windows-opt/genfiles/tensorflow/_api/v1/keras/datasets/boston_housing/__init__.py bazel-out/x64_windows-opt/genfiles/tensorflow/_api/v1/keras/datasets/cifar10/__init__.py bazel-out/x64_windows-opt/genfiles/tensorflow/_api/v1/keras/datasets/cifar100/__init__.py bazel-out/x64_windows-opt/genfiles/tensorflow/_api/v1/keras/datasets/fashion_mnist/__init__.py bazel-out/x64_windows-opt/genfiles/tensorflow/_api/v1/keras/datasets/imdb/__init__.py bazel-out/x64_windows-opt/genfiles/tensorflow/_api/v1/keras/datasets/mnist/__init__.py bazel-out/x64_windows-opt/genfiles/tensorflow/_api/v1/keras/datasets/reuters/__init__.py bazel-out/x64_windows-opt/genfiles/tensorflow/_api/v1/keras/estimator/__init__.py bazel-out/x64_windows-opt/genfiles/tensorflow/_api/v1/keras/initializers/__init__.p/_api/v1/keras/metrics/__init__.py bazel-out/x64_windows-opt/genfiles/tensorflow/_api/v1/keras/models/__init__.py bazel-out/x64_windows-opt/genfiles/tensorflow/_api/v1/keras/optimizers/__init__.py bazel-out/x64_windows-opt/genfiles/tensorflow/_api/v1/keras/preprocessing/__init__.py bazel-out/x64_windows-opt/genfiles/tensorflow/_api/v1/keras/preprocessing/image/__init__.py bazel-out/x64_windows-opt/genfiles/keras/regularizers/__init__.py bazel-out/x64_windows-opt/genfiles/tensorflow/_api/v1/keras/utils/__init__.py bazel-out/x64_windows-opt/genfiles/tensorflow/_api/v1/keras/wrappers/__init__.py bazel-out/x64_windows-opt/genfiles/tensorflow/_api/v1/keras/wrappers/scikit_learn/__init__.py bazel-out/x64_windows-opt/genfiles/tensorflow/_api/v1/layers/__init__.py bazel-out/x64_windows-opt/genfiles/tensorflow/_api/v1/linalg/__init__.py bazel-out/x64_windows-opt/genfiles/tensorflow/_api/v1/logging/__init__.py bazel-out/x64_windows-opt/genfiles/tensorflow/_api/v1/losses/__init__.py bazel-out/x64_windows-opt/genfiles/tensorflow/_api/v1/manip/__init__.py bazel-out/x64_windows-opt/genfiles/tensorflow/_api/v1/math/__init__.py bazel-out/x64_windows-opt/genfiles/tensorflow/_api/v1/metrics/__init__.py bazel-out/x64_windows-opt/genfiles/tensorflow/_api/v1/nn/__init__.py bazel-out/x64_windows-opt/genfiles/tensorflow/_api/v1/nn/rnn_cell/__init__.py bazel-out/x64_windows-opt/genfiles/tensorflow/_api/v1/profiler/__init__.py bazel-out/x64_windows-opt/genfiles/tensorflow/_api/v1/python_io/__init__.py bazel-out/x64_windows-opt/genfiles/tensorflow/_api/v1/quantization/__init__.py bazel-out/x64_windows-opt/genfiles/tensorflow/_api/v1/random/__init__.py bazel-out/x64_windows-opt/genfiles/tensorflow/_api/v1/resource_loader/__init__.py bazel-out/x64_windows-opt/genfiles/tensorflow/_api/v1/strings/__init__.py bazel-out/x64_windows-opt/genfiles/tensorflow/_api/v1/saved_model/__init__.py bazel-out/x64_windows-opt/genfiles/tensorflow/_api/v1/saved_model/builder/__init__.py bazel-out/x64_windows-opt/genfiles/tensorflow/_api/v1/saved_model/constants/__init__.py bazel-out/x64_windows-opt/genfiles/tensorflow/_api/v1/saved_model/loader/__init__.py bazel-out/x64_windows-opt/genfiles/tensorflow/_api/v1/saved_model/main_op/__init__.py bazel-out/x64_windows-opt/genfiles/tensorflow/_api/v1/saved_model/signature_constants/__init__.py bazel-out/x64_windows-opt/genfiles/tensorflow/_api/v1/saved_model/signature_def_utils/__init__.py bazel-out/x64_windows-opt/genfiles/tensorflow/_api/v1/saved_model/tag_constants/__init__.py bazel-out/x64_windows-opt/genfiles/tensorflow/_api/v1/saved_model/utils/__init__.py bazel-out/x64_windows-opt/genfiles/tensorflow/_api/v1/sets/__init__.py bazel-out/x64_windows-opt/genfiles/tensorflow/_api/v1/sparse/__init__.py bazel-out/x64_windows-opt/genfiles/tensorflow/_api/v1/spectral/__init__.py bazel-out/x64_windows-opt/genfiles/tensorflow/_api/v1/summary/__init__.py bazel-out/x64_windows-opt/genfiles/tensorflow/_api/v1/sysconfig/__init__.py bazel-out/x64_windows-opt/genfiles/tensorflow/_api/v1/test/__init__.py bazel-out/x64_windows-opt/genfiles/tensorflow/_api/v1/train/__init__.py bazel-out/x64_windows-opt/genfiles/tensorflow/_api/v1/train/queue_runner/__init__.py bazel-out/x64_windows-opt/genfiles/tensorflow/_api/v1/user_ops/__init__.py
2020-01-29 19:18:49.719983: F tensorflow/python/lib/core/bfloat16.cc:675] Check failed: PyBfloat16_Type.tp_base != nullptr
Target //tensorflow/tools/pip_package:build_pip_package failed to build
INFO: Elapsed time: 19.691s, Critical Path: 7.35s
INFO: 0 processes.
FAILED: Build did NOT complete successfully
提示无法进入目录，这个目录确实存在并且MSYS2使用cd指令可以直接进入，我不知道这是什么问题导致的，而且在这之前已经正确生成了一些编译结果。

**Comment by kumariko** [comment]
@ZTZ-99 We are checking to see if you still need help on this issue, as you are using an older version of tensorflow(1.x) which is officially considered as end of life. We recommend that you upgrade to 2.6 which is latest stable version of TF and let us know if the issue still persists in newer versions. Thanks!
