### ISSUE TITLE
How is data laid out in TfLiteTensor.data.uint8[]?

### ISSUE THREAD

**Issue by thelinuxmaniac** [tensorflow/tensorflow#36226]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux 4.19.0-6-amd64 #1 SMP Debian 4.19.67-2+deb10u2 (2019-11-11) x86_64 GNU/Linux
- TensorFlow installed from (source or binary):  source at https://github.com/tensorflow/tensorflow/archive/v2.1.0.tar.gz
- TensorFlow version (or github SHA if from source): 2.1.0

I am loading a MobileNet V2 in tensorflow-lite and then getting a reference to a tensor with index `4` as follows:
```
TfLiteTensor *avgpool_input = interpreter->tensor(4);
```
The dimension of this tensor is: `avgpool_input->dims->data = [1 7 7 1280]`. I know that the data of this tensor is stored in `avgpool_input.data.uint8[]`. I do not know how the 4-D tensor data is laid out in this flat array. I looked into the `tensorflow/lite/c/c_api_internal.h` file but I could not find any documentation about the layout of data. Can someone please help me understand the layout of data or point me out to relevant parts of the source code?

**Comment by thelinuxmaniac** [comment]
I am trying to guess the layout using the code below:
```
for(uint32_t k=0; k<1280; ++k) {
    uint32_t sum = 0;
    for(uint32_t i=0; i<7; ++i) {
        for(uint32_t j=0; j<7; ++j) {
            sum += avgpool_input->data.uint8[k*1280 + i*7 + j];
        }
    }
    uint32_t avgpool_output_k = sum / 49;
}
```
If this were the data layout, my calculations should match the output of the average pool layer. But this does not match.

**Comment by talumbau** [comment]
Hi,

I think you are right that we don't have great documentation here. The layout of the tensor data is such that the values in the dimension of highest index "change fastest" as you iterate through the data. So, with typical 4D tensors in MobileNet models labeled as [batch, filter height, filter width, channels], you step through the channel dimension as you iterate through the data. You can see this in the code if you look at the AveragePool reference implementation in TF Lite:

https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/kernels/internal/reference/pooling.h#L95-L128

There you can see that we iterate over channel in the innermost loop. The batch dimension is the outermost for loop.

You can also investigate the tensors as numpy arrays. I believe you are referring to the MobileNet V2 quantized model available for download here:

https://storage.googleapis.com/download.tensorflow.org/models/tflite_11_05_08/mobilenet_v2_1.0_224_quant.tgz

After unzipping/untaring you can load the model like this:

```
import tensorflow as tf
from tensorflow.lite.python.interpreter import Interpreter
interp = Interpreter("./mobilenet_v2_1.0_224_quant.tflite")
```

One of the weights tensors is at index 19

```
tensor = interp.get_tensor(19)
In [106]: tensor.shape                                                                                                                             
Out[106]: (1, 3, 3, 96)

In [107]: tensor[0,0,0,0:5]                                                                                                                        
Out[107]: array([ 96, 124, 112, 120, 114], dtype=uint8)
```

So those are the first five values of the tensor in the channel dimension. Now we can look at the raw data in memory (as hex values) and convert it back to ints. Here I will list out the first 10 hex values and convert them back to ints:

```
In [108] memview = tensor.data.hex()

In [109]: [int('0x' + memview[i:i+2], 16) for i in range(0,10,2)]                                                                                  
Out[109]: [96, 124, 112, 120, 114]
```

So we confirmed that the raw memory layout is as expected. A good tip, in general, is to check out the reference implementations for each op. You can see how the math is done, but also get an idea of how the data is laid out. For example, if you look at the quantized Average Pool, you can see that it's a bit more complex than what you have. We have to worry about rounding/clamping.

**Comment by thelinuxmaniac** [comment]
I am grateful for you support in improving my understanding of the code. Thank you.
