### ISSUE TITLE
TF-Lite example label Image w shared library

### ISSUE THREAD

**Issue by peter197321** [tensorflow/tensorflow#36221]
I have built tf-lite with shared `libtensorflowlite.so` library, I  am looking for help to get compiled label_image example using that shared library. 
Basically to separate projects from the tf framework.
How do I set a shared library to use with label image example?

**Comment by gadagashwini** [comment]
@peter197321, Please fill the issue [template](https://github.com/tensorflow/tensorflow/issues/new/choose). Thanks!
