### ISSUE TITLE
tensorflow java GPU compute capabilties 6.0 instead of 3.7

### ISSUE THREAD

**Issue by callicles** [tensorflow/tensorflow#36228]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu Linux 18.06
- TensorFlow installed from (source or binary): binary
- TensorFlow version: 1.13.0, 1.13.1, 1.13.2, 1.14.0, 1.15.0
- Python version: 3.6
- Installed using virtualenv? pip? conda?: Nope
- CUDA/cuDNN version: 10.1
- GPU model and memory: K80

**Describe the problem**
I am loading a model in a Java Server using the Java API to do inference. The inference is working but not running on the GPU. I get an error message provided below.

We have been using the python version of the same tensorflow release on the same GPU (K80) without an issue. This is only a problem with the java driver. 

I believe the culprit is this line:
https://github.com/tensorflow/tensorflow/blob/aa50d2b624c7e8d56b4b1644c4ccf489d8e8c55c/tensorflow/tools/ci_build/presubmit/ubuntu_16/gpu_py36_full/build.sh#L41-L44

The comment seems to indicate that this env variable is not used. I don't really understand the setup but it looks like the Java build is picking it up.

No other build seems to be requiring compute 6.0, everything is set to 3.7 (K80) which would make sense since K80 are probably the cheapest GPUs available on cloud.

https://github.com/tensorflow/tensorflow/blob/9590c4c32dd4346ea5c35673336f5912c6072bf2/tensorflow/tools/ci_build/xla/linux/gpu/run_py3.sh#L31

https://github.com/tensorflow/tensorflow/blob/938c08e5e612c5a581262e409cda08db61b25d25/tensorflow/tools/ci_build/Dockerfile.gpu.ppc64le#L28

[Search of all  TF_CUDA_COMPUTE_CAPABILITIES in the Repo](https://github.com/tensorflow/tensorflow/search?q=TF_CUDA_COMPUTE_CAPABILITIES&unscoped_q=TF_CUDA_COMPUTE_CAPABILITIES)

**Provide the exact sequence of commands / steps that you executed before running into the problem**
Use the Java Driver on GPU.

**Any other info / logs**
```
 2020-01-25 23:17:43.458562: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1717] Ignoring visible gpu device (device: 0, name: Tesla K80, pci bus id: 0000:00:04.0, compute capability: 3.7) with Cuda compute capability 3.7. The min │
│ imum required Cuda capability is 6.0.                                                                                                                                                                                                      │
│ 2020-01-25 23:17:43.519712: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1181] Device interconnect StreamExecutor with strength 1 edge matrix:                                                                                       │
│ 2020-01-25 23:17:43.519748: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1187]      0                                                                                                                                                │
│ 2020-01-25 23:17:43.519762: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1200] 0:   N
```

CI Logs that contain compute restriction:
https://source.cloud.google.com/results/invocations/37ab790b-7136-4d77-a415-f03b9909e3b2/targets/tensorflow%2Fgithub%2Fubuntu_16%2Fgpu_py36_full%2Fcontinuous/log

**Comment by sanjoy** [comment]
> I believe the culprit is this line:
> https://github.com/tensorflow/tensorflow/blob/aa50d2b624c7e8d56b4b1644c4ccf489d8e8c55c/tensorflow/tools/ci_build/presubmit/ubuntu_16/gpu_py36_full/build.sh#L41-L44
> 
> The comment seems to indicate that this env variable is not used. I don't really understand the setup but it looks like the Java build is picking it up.

How did you triage the problem to that line?  Is it because that's the only place that uses 6.0 as a compute capability?  If so, that might be a red herring.

IIUC the TF JNI GPU packages are uploaded here https://storage.googleapis.com/tensorflow-nightly/github/tensorflow/lib_package/libtensorflow_jni-gpu-linux-x86_64.tar.gz.

@gunan Do you know how these JNI packages are built and uploaded?

**Comment by gunan** [comment]
The person who used to build these has left the team. So I do not know who owns them now.
@goldiegadde any ideas?

**Comment by carlosuc3m** [comment]
Has there been any update on this issue? I have encountered the same problem.
Regards,
Carlos

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.
