### ISSUE TITLE
Could we have conv2d_transpose for C++?

### ISSUE THREAD

**Issue by tensyq** [tensorflow/tensorflow#36222]
**System information**
- TensorFlow version : 2.1

In python we have conv2d_transpose to upsample. Could we have something similar for the C++ api inaddition to ResizeBilinear, ResizeNearestNeighbor and ResizeBicubic and ResizeArea?

**Comment by shashank3110** [comment]
As an alternative to Conv2DTranspose you could also  use Upsample + conv2D for achieving deconvolution/learnable upsampling .

**Comment by gadagashwini** [comment]
@tensyq, Please fill the issue [Template](https://github.com/tensorflow/tensorflow/issues/new/choose). Thanks!

**Comment by tensyq** [comment]
**System information**
- TensorFlow version (you are using): 2.1
- Are you willing to contribute it (Yes/No): No
**Describe the feature and the current behavior/state.**
**Will this change the current api? How?**
Possibly similar to conv2d with padding
I am trying to implement upsampling + convolution in tensorflow c++ like this:
....
```
 Scope scope_conv3 = t_root.NewSubScope("Conv3_layer");
     in_channels = out_channels;
     out_channels = 16;
     auto pool3 = AddConvolutionLayer("C1", scope_conv3, in_channels, out_channels, filter_side, pool2);
     int new_side_3 = ceil((float)new_side_2 / 2);

auto upsample_1 = ResizeBilinear(i_root.WithOpName("upsample_1"), pool3, Const(i_root, {new_side_2, new_side_2}));
     Scope scope_conv_4 = t_root.NewSubScope("Convolution4_layer");
```

where AddConvolutionLayer does something like this:
```
     auto conv = Conv2D(scope.WithOpName("Convolution"), input, weights_variables["W"+idx], {1, 1, 1, 1}, "SAME");
     auto bias = BiasAdd(scope.WithOpName("Bias"), conv, bias_variables["Bias"+idx]);
     auto relu = Relu(scope.WithOpName("Relu"), bias);
     return MaxPool(scope.WithOpName("Pooling"), relu, {1, 2, 2, 1}, {1, 2, 2, 1}, "SAME");
```

The error I get is:
`Non-OK-status: t_session->Run(ops_to_run, nullptr) status: Invalid argument: Node 'Convolution4_layer/Conv': Unknown input node 'upsample_1'`

If instead conv2d_transpose was provided I would be able to do exactly what I did with Conv2D which I think is fine without knowing what went wrong with ResizeBilinear plus  I do not need to worry about the different ways of resizing.
