### ISSUE TITLE
download_and_extract URL DIR download_dependencies.sh

### ISSUE THREAD

**Issue by peter197321** [tensorflow/tensorflow#36225]
I follow [the build for arm64](https://www.tensorflow.org/lite/guide/build_arm64) and try  to execute `download_dependencies.sh` script but end up with issue:

```
~/work/tensorflow$ ./tensorflow/lite/tools/make/download_dependencies.sh
./tensorflow/lite/tools/make/download_dependencies.sh: line 59: 1: Usage: download_and_extract URL DIR
```

Anybody can advise on this issue?

**Comment by gadagashwini** [comment]
@peter197321, Can you please fill the [Template](https://github.com/tensorflow/tensorflow/issues/new/choose) to analyze the issue. Thanks!
