### ISSUE TITLE
AutoGraph issue

### ISSUE THREAD

**Issue by ashwin17083** [tensorflow/tensorflow#36238]
**System information**
- OS Platform and Distribution : CentOS Linux release 7.7.1908 (Core) 
- TensorFlow version: 1.15.0-dev20190718
- Python version: 3.4
 
I am trying to save a custom built LSTM model.
The issue arises when saving the lstm model as:
final_model.save("complete_model",save_format='tf'), whereas it is doesn't throw an error upon saving it as final_model.save("complete_model.h5"). 

I tried to downgrade gast to version 0.2.2 as suggested by ticket**(TF2.0 AutoGraph issue
#32377)** but still doesn't work.
The error message is as follows:

W0127 16:22:09.873542 140113418938176 ag_logging.py:146] Entity <function Function._initialize_uninitialized_variables..initialize_variables at 0x7f6de43a8048> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, export AUTOGRAPH_VERBOSITY=10) and attach the full output. Cause: No module named 'tensorflow_core.estimator'
W0127 16:22:09.882860 140113418938176 ag_logging.py:146] Entity <function _wrap_call_and_conditional_losses..call_and_return_conditional_losses at 0x7f6de41e8048> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, export AUTOGRAPH_VERBOSITY=10) and attach the full output. Cause: No module named 'tensorflow_core.estimator'
W0127 16:22:09.911009 140113418938176 save.py:129] Skipping full serialization of object <tensorflow.python.keras.layers.recurrent.LSTM object at 0x7f6e00539f60>, because an error occurred while tracing layer functions. Error message: in converted code:
relative to /usr/local/lib/python3.4/site-packages/tensorflow_core/python/keras:

saving/saved_model/save.py:535 call_and_return_conditional_losses
    return layer_call(inputs, training=training), layer.get_losses_for(inputs)
layers/recurrent.py:2535 call
    inputs, mask=mask, training=training, initial_state=initial_state)
layers/recurrent.py:745 call
    zero_output_for_mask=self.zero_output_for_mask)
backend.py:3794 rnn
    input_time_zero, tuple(initial_states) + tuple(constants))
layers/recurrent.py:730 step
    output, new_states = self.cell.call(inputs, states, **kwargs)

TypeError: wrapped_call() takes 1 positional argument but 2 were given
W0127 16:22:09.916115 140113418938176 ag_logging.py:146] Entity <function _wrap_call_and_conditional_losses..call_and_return_conditional_losses at 0x7f6de41e8488> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, export AUTOGRAPH_VERBOSITY=10) and attach the full output. Cause: No module named 'tensorflow_core.estimator'
W0127 16:22:09.943473 140113418938176 save.py:129] Skipping full serialization of object <tensorflow.python.keras.engine.training.Model object at 0x7f6dff6e65c0>, because an error occurred while tracing layer functions. Error message: in converted code:
relative to /usr/local/lib/python3.4/site-packages/tensorflow_core/python/keras:

saving/saved_model/save.py:535 call_and_return_conditional_losses
    return layer_call(inputs, training=training), layer.get_losses_for(inputs)
engine/network.py:737 call
    return self._run_internal_graph(inputs, training=training, mask=mask)
engine/network.py:879 _run_internal_graph
    output_tensors = layer(computed_tensors, **kwargs)
layers/recurrent.py:621 __call__
    return super(RNN, self).__call__(inputs, **kwargs)
engine/base_layer.py:713 __call__
    outputs = call_fn(inputs, *args, **kwargs)
layers/recurrent.py:2535 call
    inputs, mask=mask, training=training, initial_state=initial_state)
layers/recurrent.py:745 call
    zero_output_for_mask=self.zero_output_for_mask)
backend.py:3794 rnn
    input_time_zero, tuple(initial_states) + tuple(constants))
layers/recurrent.py:730 step
    output, new_states = self.cell.call(inputs, states, **kwargs)

TypeError: wrapped_call() takes 1 positional argument but 2 were given
2020-01-27 16:22:09.957051: W tensorflow/python/util/util.cc:288] Sets are not currently considered sequences, but this may change in the future, so consider avoiding using them.
W0127 16:22:09.982703 140113418938176 ag_logging.py:146] Entity <function Layer._handle_weight_regularization.._loss_for_variable at 0x7f6e017b6d90> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, export AUTOGRAPH_VERBOSITY=10) and attach the full output. Cause: No module named 'tensorflow_core.estimator'
W0127 16:22:09.992292 140113418938176 ag_logging.py:146] Entity <function Function._initialize_uninitialized_variables..initialize_variables at 0x7f6de43a8400> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, export AUTOGRAPH_VERBOSITY=10) and attach the full output. Cause: No module named 'tensorflow_core.estimator

**Comment by gadagashwini** [comment]
@ashwin17083, Can you provide the standalone code replicate the reported issue. Thanks!

**Comment by ashwin17083** [comment]
Please find the attached zip folder.
compliation command: python3 PAKLSTMRepValCommented.py
[lstm.zip](https://github.com/tensorflow/tensorflow/files/4127786/lstm.zip)

**Comment by gadagashwini** [comment]
@ashwin17083, Will it be possible to provide the simple standalone code to analyze the issue. Thanks!

**Comment by ashwin17083** [comment]
@gadagashwini: Hi,
I have attached a modified code which includes a simple model description,training and saving.
The issue occurs in line number 26 when trying to save the model in TensorFlow SavedModel format.
The same model could be saved in .h5 format as in line number 25.
[PAKLSTMRepValCommented.txt](https://github.com/tensorflow/tensorflow/files/4153207/PAKLSTMRepValCommented.txt)
Thanks!

**Comment by gadagashwini** [comment]
@ashwin17083, I tried on colab and on Linux system it is working as expected no error. Please find the gist [here](https://colab.research.google.com/gist/gadagashwini/3cb8a2d5006ae9da0ff9775c8bc481af/untitled377.ipynb). Can you try with gast==0.2.2 again and check. Create virtual env and install Tensorflow with gast version 0.2.2.  Thanks!

**Comment by ashwin17083** [comment]
Hi @gadagashwini, I tried it on conda 4.8.0 and it worked. 👍 
Really appreciate your help
