### ISSUE TITLE
Issue on download_and_extract URL DIR download_dependencies.sh

### ISSUE THREAD

**Issue by peter197321** [tensorflow/tensorflow#36249]
I follow [the build for arm64](https://www.tensorflow.org/lite/guide/build_arm64) and try  to execute `download_dependencies.sh` script but end up with issue:

```
~/work/tensorflow$ ./tensorflow/lite/tools/make/download_dependencies.sh
./tensorflow/lite/tools/make/download_dependencies.sh: line 59: 1: Usage: download_and_extract URL DIR
```

How it can be fixed?

**Comment by lgeiger** [comment]
I think this was fixed in 0071950c073eb78e8935ad680f557e11f52b76a0 and 0438fe668efd9c3e3c3d4692f0c4af4f1dff6395, though it is not release in TensorFlow 2.1

**Comment by thelinuxmaniac** [comment]
duplicate issue https://github.com/tensorflow/tensorflow/issues/36199 contains a fix.

**Comment by gadagashwini** [comment]
@peter197321, Were you able to resolve this issue. Thanks!

**Comment by gadagashwini** [comment]
@peter197321, Any update!

**Comment by terryheo** [comment]
It's fixed now.
https://github.com/tensorflow/tensorflow/commit/f270180a6caa8693f2b2888ac7e6b8e69c4feaa8
