### ISSUE TITLE
Hessian-vector product raises exception about Fetch argument

### ISSUE THREAD

**Issue by nkoep** [tensorflow/tensorflow#36246]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Arch Linux
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: n/a
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): v1.15.0-rc3-22-g590d6ee 1.15.0
- Python version: Python 3.7.6
- Bazel version (if compiling from source): n/a
- GCC/Compiler version (if compiling from source): n/a
- CUDA/cuDNN version: n/a
- GPU model and memory: n/a

**Describe the current behavior**
Trying to compute the Hessian-vector product of a graph with a linear dependence on a tensor produces a `TypeError` exception:
```raw
TypeError: Fetch argument None has invalid type <class 'NoneType'>` exception.
```

**Code to reproduce the issue**
```python
import itertools
import os

import numpy.random as rnd
import tensorflow as tf
from tensorflow.python.ops.gradients_impl import _hessian_vector_product

os.environ["TF_CPP_MIN_LOG_LEVEL"] = "3"


def main():
    n = 10

    x = tf.Variable(tf.zeros(n, dtype=tf.float64), name="x")
    y = tf.Variable(tf.zeros(n, dtype=tf.float64), name="y")
    z = tf.Variable(tf.zeros(n, dtype=tf.float64), name="z")
    function = tf.reduce_sum(x ** 2 + y + z ** 3)

    arguments = (x, y, z)
    zeros = [tf.zeros_like(argument) for argument in arguments]
    hessian = _hessian_vector_product(function, arguments, zeros)

    x, y, z = [rnd.randn(n) for _ in range(3)]
    u, v, w = [rnd.randn(n) for _ in range(3)]

    feed_dict = {
        key: value
        for key, value in zip(itertools.chain(arguments, zeros),
                              (x, y, z, u, v, w))
    }
    with tf.Session() as session:
        hessian_vector_product = session.run(hessian, feed_dict)

    print(hessian_vector_product)


if __name__ == "__main__":
    main()
```

**Comment by nkoep** [comment]
I did some more digging and realized it was due to the default behavior of `tf.gradients`, which replaces unconnected gradients with None. The straightforward fix is to copy the implementation of `_hessian_vector_product` and pass `unconnected_gradients=tf.UnconnectedGradients.ZERO` to any `tf.gradients` calls.

**Comment by gadagashwini** [comment]
Was able to reproduce the issue with Tf 1.15 on colab.
Please find the gist [here](https://colab.research.google.com/gist/gadagashwini/e149f31541c4106708a8c850761a39c3/untitled362.ipynb). Thanks!

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.
