### ISSUE TITLE
TF-Lite example label Image w shared library

### ISSUE THREAD

**Issue by peter197321** [tensorflow/tensorflow#36248]
Please update `label_image` example to be compilable using a shared library.
It means to use a shared library with `label_image` example.

**Comment by jdduke** [comment]
Can you be a bit more explicit? Do you mean you'd like for the example to use one of the shared library targets (either the C or C++ one), rather than statically linking everything into the final binary?

**Comment by Saduf2019** [comment]
@peter197321 Could you please respond to the above comment, so we could help you resolve the issue.
