### ISSUE TITLE
Malformatted doc page for SGD optimizer

### ISSUE THREAD

**Issue by renatobellotti** [tensorflow/tensorflow#36245]
## URL(s) with the issue:

https://www.tensorflow.org/api_docs/python/tf/keras/optimizers/SGD#apply_gradients

### Clear description

The formatting in the "References" section is wrong; there is a ``nesterov = True,`` that has nothing to do with the reference.

**Comment by rohanreddych** [comment]
"http://jmlr.org/proceedings/papers/v28/sutskever13.pdf"
is this the only thing that should be present?

**Comment by renatobellotti** [comment]
I don't know, I just realised that there is something wrong with the formatting.

**Comment by jvishnuvardhan** [comment]
@renatobellotti I agree there is some formatting required in this page. But, can you please explain what do you meant by "that has nothing to do with the reference"?. I think the reference explain about the importance of `nesterov`. Thanks!

**Comment by renatobellotti** [comment]
@jvishnuvardhan I haven't read the reference, I just saw that this piece of code was no reference, and I couldn't find where it belongs to, so I assumed it should not be in the reference box.

Sorry for my ambiguous formulation.

**Comment by jvishnuvardhan** [comment]
Closing this issue as it was resolved. Thanks!
