### ISSUE TITLE
TF 2.1 Keras: Cached datasets use 40% more memory than in TF 2.0

### ISSUE THREAD

**Issue by lgeiger** [tensorflow/tensorflow#36240]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.1.0
- Python version: 3.7.6
- CUDA/cuDNN version: 10.1 / 7.6.5.32
- GPU model and memory: NVIDIA V100

**Describe the current behavior**

When running training with cached repeated datasets in Keras, TensorFlow 2.1 (and `tf-nightly==2.2.0.dev20200124`) use 40-50% more memory than TensorFlow 2.0.

E.g. a large cached dataset like [ImageNet](https://www.tensorflow.org/datasets/catalog/imagenet2012) will require **~230 GB** of memory where as in TensorFlow 2.0 the same code only required **155 GB**. This is a 75 GB increase in memory usage which makes it hard to cache large datasets in memory.

```python
import math
import tensorflow as tf
from tensorflow import keras
import tensorflow_datasets as tfds


batch_size = 1024

dataset, info = tfds.load(
    "imagenet2012:5.0.*",
    decoders={"image": tfds.decode.SkipDecoding()},
    split="train",
    with_info=True,
)

val_dataset = tfds.load(
    "imagenet2012:5.0.*",
    decoders={"image": tfds.decode.SkipDecoding()},
    split="validation",
)

steps_per_epoch = math.ceil(info.splits["train"].num_examples / batch_size)
val_steps = math.ceil(info.splits["validation"].num_examples / batch_size)


def _decode_and_center_crop(image_bytes):
    """Crops to center of image with padding then scales image_size."""
    shape = tf.image.extract_jpeg_shape(image_bytes)
    image_height = shape[0]
    image_width = shape[1]
    image_size = 224

    padded_center_crop_size = tf.cast(
        (
            (image_size / (image_size + 32))
            * tf.cast(tf.minimum(image_height, image_width), tf.float32)
        ),
        tf.int32,
    )

    offset_height = ((image_height - padded_center_crop_size) + 1) // 2
    offset_width = ((image_width - padded_center_crop_size) + 1) // 2
    crop_window = tf.stack(
        [offset_height, offset_width, padded_center_crop_size, padded_center_crop_size]
    )
    image = tf.image.decode_and_crop_jpeg(image_bytes, crop_window, channels=3)
    image = tf.compat.v1.image.resize_bicubic([image], [image_size, image_size])[0]
    return image


def preprocessing(data):
    return tf.cast(_decode_and_center_crop(data["image"]), tf.float32), data["label"]


dataset = (
    dataset.cache()
    .shuffle(10 * batch_size)
    .repeat()
    .map(preprocessing, num_parallel_calls=tf.data.experimental.AUTOTUNE)
    .batch(batch_size)
    .prefetch(1)
)

val_dataset = (
    val_dataset.cache()
    .repeat()
    .map(preprocessing, num_parallel_calls=tf.data.experimental.AUTOTUNE)
    .batch(batch_size)
    .prefetch(1)
)

model = keras.models.Sequential(
    [
        keras.layers.GlobalMaxPool2D(input_shape=(224, 224, 3)),
        keras.layers.Dense(1000, activation="softmax",),
    ]
)

model.compile(
    optimizer="adam",
    loss="sparse_categorical_crossentropy",
    metrics=["accuracy", "sparse_top_k_categorical_accuracy"],
)

model.fit(
    dataset,
    epochs=5,
    steps_per_epoch=steps_per_epoch,
    validation_data=val_dataset,
    validation_steps=val_steps,
)
```

**Describe the expected behavior**
No increased memory requirements when switching from TensorFlow 2.0 to 2.1

**Other info / logs**

This issue doesn't appear when not using a validation dataset:
```python
model.fit(dataset, epochs=5, steps_per_epoch=steps_per_epoch)
```

The issues also doesn't appear if the dataset is not repeated. However then we would run into #36126 which logs error messages after each epoch:
```python
dataset = (
    dataset.cache()
    .shuffle(10 * batch_size)
    .map(preprocessing, num_parallel_calls=tf.data.experimental.AUTOTUNE)
    .batch(batch_size)
    .prefetch(1)
)

val_dataset = (
    val_dataset.cache()
    .map(preprocessing, num_parallel_calls=tf.data.experimental.AUTOTUNE)
    .batch(batch_size)
    .prefetch(1)
)

model = keras.models.Sequential(
    [
        keras.layers.GlobalMaxPool2D(input_shape=(224, 224, 3)),
        keras.layers.Dense(1000, activation="softmax",),
    ]
)

model.compile(
    optimizer="adam",
    loss="sparse_categorical_crossentropy",
    metrics=["accuracy", "sparse_top_k_categorical_accuracy"],
)

model.fit(dataset, epochs=5, validation_data=val_dataset)
```

Judging from the observations above it looks like the iteration of the validation dataset is broken inside Keras, so it doesn't show up when the dataset iterator is recreated when used without `steps_per_epoch`.

What is the recommended way of using `tf.data.Datasets` with Keras models?

**Comment by byronyi** [comment]
I am using TF 2.0/2.1/2.2 nightly for regular benchmarking ImageNet models and I did not find this issue loading data from disks. Btw I have not used tensorflow datasets; maybe it is better for you to raise the question there.

**Comment by lgeiger** [comment]
@byronyi This issue only appears when caching the dataset using `.cache()`, have you tried it with caching? Also I am reading the data from `GCS` which might change the story a bit.

**Comment by jsimsa** [comment]
@lgeiger can you reproduce the issue when you store a copy of ImageNet locally?

**Comment by lgeiger** [comment]
> @lgeiger can you reproduce the issue when you store a copy of ImageNet locally?

I currently don't have a good way to test this. Though the experiment can be reproduced with a smaller dataset like [`oxford_flowers102`](https://www.tensorflow.org/datasets/catalog/oxford_flowers102), though there the memory difference is harder to see.

**Comment by lgeiger** [comment]
I tried to reproduce the issue with MNIST by caching on disk and didn't see any difference between TensorFlow versions. It looks like this issue only appears when caching in memory.

**Comment by jsimsa** [comment]
Thank you @lgeiger. What I was suggesting is that you copy the data to your local file system and then run your program caching data in memory. I am trying to rule out that this is not due to reading from `GCS` (and it will also be easier to reproduce if it can be run locally).

**Comment by lgeiger** [comment]
> Thank you @lgeiger. What I was suggesting is that you copy the data to your local file system and then run your program caching data in memory. I am trying to rule out that this is not due to reading from GCS (and it will also be easier to reproduce if it can be run locally).

I just verified that I can reproduce this also when reading the data locally.

Since this only happens when when running validation, I suspect that this might be a problem on the keras side.

**Comment by lgeiger** [comment]
This can also be reproduced on `tf-nightly-2.2.0.dev20200205`. It looks like the memory only exceeds the normal requirements once the second epoch starts.

**Comment by jsimsa** [comment]
Thank you for the follow up, I am going to ask the Keras team to investigate.

@karmel this looks like Keras regression between TF 2.0 and TF 2.1.

**Comment by lgeiger** [comment]
@yhliang2018 @karmel @jsimsa Any updates on this?

**Comment by byronyi** [comment]
@lgeiger I took a closer look and also suspect that the same issue occur in our environment. I am still investigating...will keep you posted.

**Comment by lgeiger** [comment]
Just for reference, #36126 doesn't show up in `tf-nightly==2.2.0.dev20200218` anymore so one can workaround this issue by not repeating the dataset.

**Comment by lgeiger** [comment]
@byronyi @yhliang2018 Any updates on this?

**Comment by byronyi** [comment]
It seems to be fixed by #37877, which is included in 2.2.0-rc3. Would you mind to try again?

**Comment by lgeiger** [comment]
I was testing this earlier today with rc3 and without repeating the dataset as mentioned in https://github.com/tensorflow/tensorflow/issues/36240#issuecomment-588180783 and it ran out of memory for larger batch sizes. This is already better that 2.1 which crashed irrespective of the batch size, but there is still something going wrong compared to TensorFlow 2.0.0. I'll properly test it later today and will report back to see if I can find a workaround. For now it seams that 2.2 still has a lot higher memory usages than 2.0.

**Comment by byronyi** [comment]
One of my colleagues reported similar issues that the memory consumption increases after each epoch, and it might be due to creating a new validation dataset for each evaluation.

I never tested caching validation data before. Would you mind not to cache the validation dataset and see if you could reproduce the issue?

**Comment by lgeiger** [comment]
@byronyi Thanks for the fast response. I am debugging as we speek, and indeed I can observe that the memory usage increases every epoch. It is not as severe as it was in 2.1, but still very noticable. I am testing this currently without repeating the dataset. Even when caching both training and validation datasets the memory usage increases during validation and drops sharply once the next epoch starts. This suggests that indeed the validation set is regenerated each time but unfortunately the memory usage doesn't fully drop to the original value and therfore builds up each epoch. This means even if the validation dataset is cached the cache is disposed every epoch which makes caching the validation dataset pointless. When not caching the validation set it seems that memory usage seems stable, but I need to run it for longer to be sure.

One more concerning observation I made (which would block us upgrading from 2.0 to 2.2) is that XLA in our case requires 1.5 - 2x the GPU memory as it did in 2.0. This means I need to halve the batch size in order to be able to run on 4-GPUs with XLA, which makes XLA essentially unusable. The training code works without a problem when XLA is disabled though. Is there already an issue where this is tracked?

**Comment by lgeiger** [comment]
> It seems to be fixed by #37877, which is included in 2.2.0-rc3. Would you mind to try again?

It seems the original issue has been fixed, but unfortunately I am now running out of GPU memory when using larger batch sizes which for some reason doesn't only happens when using `steps_per_epoch`.

**Comment by yhliang2018** [comment]
Thanks for reporting this. @tomerk is looking into the memory issue, and may help on this.

**Comment by lgeiger** [comment]
> One of my colleagues reported similar issues that the memory consumption increases after each epoch, and it might be due to creating a new validation dataset for each evaluation. See here for some details: #33340 (comment)

@byronyi I can reproduce this issue when caching is enabled for the validation dataset. It looks like this is an issue with the [thread pool dataset](https://github.com/tensorflow/tensorflow/blob/8e0eecc8e396f8c1859b1b3954a89a41da8b5b45/tensorflow/python/data/ops/dataset_ops.py#L360-L362).
TensorFlow Datasets sets [`experimental_threading.private_threadpool_size = 16` by default](https://github.com/tensorflow/datasets/blob/8277548d5bdbc264a50d84ef702adc15bee8d4ae/tensorflow_datasets/core/tfrecords_reader.py#L62) which leads to an increase in memory consumption after each epoch for me. Disabling this option keeps the memory usage stable.

I can write down a more structured summary of the various issues tomorrow.

**Comment by yhliang2018** [comment]
Hi @lgeiger, do you mind to open a new issue with the thread pool dataset? So tf.data team can take a closer look at it. If you can provide a minimal repro example and some detailed summaries you already have, that will be very helpful to us! 

At the same time, can we close this issue as it's already fixed? Thanks!

**Comment by lgeiger** [comment]
Thanks for the help!

I still have some issues with the datasets, but it is likely that they are not related to the original description of the issue anymore. I will run a few more tests and will try to provide a structured description in a new issue tomorrow. I hope we can get this fixed soon.

**Comment by lgeiger** [comment]
For reference I opened a new issue at #38617 explaining the behaviour.
