### ISSUE TITLE
iOS CameraExample KVO mismatching keys

### ISSUE THREAD

**Issue by jesseseales** [tensorflow/tensorflow#3625]
I got a KVO error when switching views and noticed: 

In CameraExampleViewController.mm, `setupAVCapture`uses

```
[stillImageOutput
     addObserver:self
     forKeyPath:@"capturingStillImage"
     options:NSKeyValueObservingOptionNew
     context:(void *)(AVCaptureStillImageIsCapturingStillImageContext)];
```

while `teardownAVCapture` uses

```
[stillImageOutput removeObserver:self forKeyPath:@"isCapturingStillImage"];
```

 `forKeyPath:@"capturingStillImage"` and `forKeyPath:@"isCapturingStillImage"` do not match.

**Comment by poxvoculi** [comment]
@petewarden can you take a look at this?

**Comment by aselle** [comment]
@jesseseales, is this still an issue for you?

**Comment by girving** [comment]
Closing due to lack of response.
