### ISSUE TITLE
Dropout problem in tensorflow 1.14

### ISSUE THREAD

**Issue by shahriar49** [tensorflow/tensorflow#36254]
**System information**
- OS Platform and Distribution: Windows 10 on two different PCs
- TensorFlow installed from (source or binary): Binary
- TensorFlow version (use command below): 1.12 on one system and 1.14 on another system
- Python version: 3.6.5
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: 9.0 (for tf1.12) and 10.0 (for tf1.14)
- GPU model and memory: Nvidia GTX 1080 Ti (for tf1.12) and RTX 2080 Ti (for tf1.14)

**Describe the current behavior**
I defined a simple one-layer LSTM network with a dropout layer. The code is below and the input is a sequence of shape (105, 15), grouped into 1024 samples per batch.

```
def keras_model(input_shape):
    from tensorflow.keras.layers import Input, CuDNNLSTM, Dense, Dropout

    inputs = Input(shape=input_shape)
    x = CuDNNLSTM(64, return_sequences=False)(inputs)
    x = Dropout(0.1)(x)
    outputs = Dense(NC, activation='softmax')(x)

    return tf.keras.Model(inputs, outputs)
```

 It worked under tf1.12 but it is not working under tf1.14 and I get below log:

```
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
input_1 (InputLayer)         [(None, None, 15)]        0
_________________________________________________________________
cu_dnnlstm (CuDNNLSTM)       (None, 64)                20736
_________________________________________________________________
dropout (Dropout)            (None, 64)                0
_________________________________________________________________
dense (Dense)                (None, 7)                 455
=================================================================
Total params: 21,191
Trainable params: 21,191
Non-trainable params: 0
_________________________________________________________________

Epoch 1/1000
Traceback (most recent call last):
  File "run_rnn2.py", line 653, in <module>
    doWork(a)
  File "run_rnn2.py", line 502, in doWork
    validation_steps=val_steps, verbose=verbose, callbacks=CB)
  File "D:\shahriar\tf1.14_py3.6.5\lib\site-packages\tensorflow\python\keras\engine\training.py", line 780, in fit
    steps_name='steps_per_epoch')
  File "D:\shahriar\tf1.14_py3.6.5\lib\site-packages\tensorflow\python\keras\engine\training_arrays.py", line 274, in model_iteration
    batch_outs = f(actual_inputs)
  File "D:\shahriar\tf1.14_py3.6.5\lib\site-packages\tensorflow\python\keras\backend.py", line 3292, in __call__
    run_metadata=self.run_metadata)
  File "D:\shahriar\tf1.14_py3.6.5\lib\site-packages\tensorflow\python\client\session.py", line 1458, in __call__
    run_metadata_ptr)
tensorflow.python.framework.errors_impl.InvalidArgumentError: 2 root error(s) found.
  (0) Invalid argument: The second input must be a scalar, but it has shape [1024]
         [[{{node dropout/cond/Switch}}]]
         [[metrics/acc/Identity/_89]]
  (1) Invalid argument: The second input must be a scalar, but it has shape [1024]
         [[{{node dropout/cond/Switch}}]]
0 successful operations.
0 derived errors ignored.
```

What can be the reason?
I can not upgrade my tensorflow to another version. I need to have tf1.14 work with the same code as tf1.12 under python 3.6.5.

**Comment by ravikyram** [comment]
@shahriar49 
Looks like code is incomplete. Can you please provide complete code snippet to reproduce the issue in our environment. It helps us in localizing the issue faster. Thanks!

**Comment by shahriar49** [comment]
@ravikyram 
The whole code is lengthy and I didn't think it helps that much, and it is run on some proprietary data that I can not share. Isn't there any clue that somebody can get from the error log that I got? I expect experts to be able to spot the problem easily.

**Comment by ymodak** [comment]
We may not be able to provide solution to your problem without inspecting the minimal code repro.
If you can help us with a toy example which works in 1 TF version and fails in another we will be happy to assist.  Thanks!

**Comment by shahriar49** [comment]
@ymodak 
I found the problem and realized that it was because of passing sample weights in addition to samples and targets in the training dataset. It is still a question for me why tensorflow 1.12 and 1.14 act differently in this case, but it is understandable.
