### ISSUE TITLE
GradientTape does not track intermediate variables inside a tf.function

### ISSUE THREAD

**Issue by xmax1** [tensorflow/tensorflow#36255]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
Ubuntu 18.04
- TensorFlow installed from (source or binary): 
Binary
- TensorFlow version (use command below):
2.2.0-dev20200123
- Python version:
3.7.3
- CUDA/cuDNN version: 10.1 / 
#define CUDNN_MAJOR 7
#define CUDNN_MINOR 6
#define CUDNN_PATCHLEVEL 4
- GPU model and memory:
```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 440.33.01    Driver Version: 440.33.01    CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Quadro P3200        On   | 00000000:01:00.0 Off |                  N/A |
| N/A   54C    P3    24W /  N/A |   5911MiB /  6078MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0      1326      G   /usr/lib/xorg/Xorg                           282MiB |
|    0      2272      G   kwin_x11                                      53MiB |
|    0      2279      G   /usr/bin/krunner                             105MiB |
|    0      2281      G   /usr/bin/plasmashell                          96MiB |
|    0      3136      C   ...ilso4/anaconda3/envs/fermi21/bin/python  5363MiB |
|    0      4764      G   ...pycharm-community-2019.3.1/jbr/bin/java     2MiB |
+-----------------------------------------------------------------------------+
```

**Describe the current behavior**
Can't compute derivatives of output wrt intermediate variables created inside a tf.function wrapped function. 

If tf.function wrapper is removed the function behaves as expected.

**Describe the expected behavior**
Can compute these derivatives. 

**Code to reproduce the issue**
```
import tensorflow as tf
print(tf.__version__)

y = tf.Variable(2.)
z = tf.Variable(3.)
x = tf.random.normal((1,))

@tf.function # remove this to function
def call(x, y, z):
    a = x * y
    b = a * z
    return a, b

with tf.GradientTape(True) as g:
    g.watch(x)
    a, b = call(x, y, z)

gx, ga =  g.gradient(b, [x, a])
print(ga)
print(gx)
```

**Other info / logs**
2.2.0-dev20200123
None
tf.Tensor([6.], shape=(1,), dtype=float32)

**Comment by amahendrakar** [comment]
Was able to reproduce the issue. Please find the Gist [here](https://colab.sandbox.google.com/gist/amahendrakar/5702221d4122ecf0ff681e032cb61657/36255.ipynb). Thanks!

**Comment by maxiwelian** [comment]
Any word on how to deal with this? Seems like the intermediate vars are untracked is there an easy workaround?

**Comment by mdanatg** [comment]
Technically, you need to watch `b` if you intend to take gradients with respect to it. As it is now, the code only works without tf.function by accident. A different equation that doesn't entirely depend on `x` would give you bad results.

A workaround is to move the gradient tape inside the function so that you can watch `b`:

```
import tensorflow as tf

y = tf.Variable(2.)
z = tf.Variable(3.)
x = tf.random.normal((1,))

@tf.function
def call(x, y, z):
    with tf.GradientTape(True) as g:
        g.watch(x)
        a = x * y
        g.watch(a)
        b = a * z
    gx, ga = g.gradient(b, [x, a])
    return gx, ga

gx, ga = call(x, y, z)
print(ga)
print(gx)
```

The tape should probably raise an error instead of silently returning None.
@allenlavoie
