### ISSUE TITLE
TF 2.1 libtensorflow library does not build under Windows

### ISSUE THREAD

**Issue by josdewitte** [tensorflow/tensorflow#36252]
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
Windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
None
- TensorFlow installed from (source or binary):
Source
- TensorFlow version:
master or 2.1 labeled version
- Python version:
3.6.8
- Installed using virtualenv? pip? conda?:
Partially Pip as specified in manual at 
- Bazel version (if compiling from source):
bazel 1.2.1
- GCC/Compiler version (if compiling from source):
MSVC 2017 or MSVC 2019
- CUDA/cuDNN version:
None
- GPU model and memory:
None

libtensorflow does not build. Tried 2.1 version and current (27 jan 2020) master version

Used
bazel build --define=no_tensorflow_py_deps=true --config opt //tensorflow/tools/lib_package:libtensorflow

Used either set BAZEL_VS= {{ path to VS2019 }} or {{ path to VS2017 }}

Error is always:

ERROR: /tensorflow/tensorflow/core/framework/BUILD:575:1: C++ compilation of rule '//tensorflow/core/framework:bfloat16' failed (Exit 2)
\org_tensorflow\external\eigen_archive\unsupported\eigen\cxx11\src/Tensor/TensorBlock.h(1028): error C2061: syntax error: identifier 'Kind'
\org_tensorflow\external\eigen_archive\unsupported\eigen\cxx11\src/Tensor/TensorBlock.h(1134): note: see reference to class template instantiation 'Eigen::internal::StridedLinearBufferCopy<Scalar,IndexType>' being compiled
\org_tensorflow\external\eigen_archive\unsupported\eigen\cxx11\src/Tensor/TensorBlock.h(1037): error C2061: syntax error: identifier 'Kind'

It seems related to the Eigen library header file(s) missing in includes ?

**Comment by josdewitte** [comment]
See also related issue https://github.com/tensorflow/tensorflow/issues/36064

**Comment by gunan** [comment]
@goldiegadde @mihaimaruseac did we see a similar issue in 2.1 branch?
On master, my builds seem to be healthy.

**Comment by mihaimaruseac** [comment]
I don't remember having this issue at the time.

**Comment by josdewitte** [comment]
Dear all, the issue persists; I am using 
[https://github.com/sitting-duck/stuff/tree/master/ai/tensorflow/build_tensorflow_1.14_source_for_Windows](url) as the steps for creating a build on windows, since there is no good documentation. If you have a better description of steps needed; please provide them.

**Comment by josdewitte** [comment]
Any update?

**Comment by cliffwoolley** [comment]
@pkanwar23

**Comment by josdewitte** [comment]
Any update?

**Comment by gunan** [comment]
I am sorry, I have been knee deep in another task lately, and have not been able to respond.
I will try to look into this tomorrow.

**Comment by Dave-Stein** [comment]
[Latest reasons](https://github.com/tensorflow/tensorflow/issues/39905#issuecomment-641588284) why nothing happens for last 6 months for Windows DLL for TF2.0, TF2.1 and TF2.2

**Comment by Dave-Stein** [comment]
We need to invite more discussion on the future of WINDOW support for tensorflow.  6 months with no progress but challenges. **Google needs to hire those WHO CLIAM HERE are able to address these challenges IMMEDIATELY.**

**Comment by Dave-Stein** [comment]
The latest commit to address this problem is to get more Windows developers to spend MORE TIME trying [new Bazel  (from 2.0 to 3.0)](https://github.com/tensorflow/tensorflow/commit/b4b83222d470afbf0b83d12b0824c0f056235655)

**Comment by Saduf2019** [comment]
@josdewitte 
Can you please try on the latest stable version 2.4.1 and let us know if this is still an issue.
