### ISSUE TITLE
ModuleNotFoundError: No module named 'tensorflow.contrib'

### ISSUE THREAD

**Issue by KoizumiNao** [tensorflow/tensorflow#36269]
Hi. Can anyone help me with this existing problem?

This is the error.
2020-01-28 02:46:01.200715: E tensorflow/core/platform/hadoop/hadoop_file_system.cc:132] HadoopFileSystem load error: libhdfs.so: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "train.py", line 48, in <module>
    from tensorflow.contrib import framework as contrib_framework
**ModuleNotFoundError: No module named 'tensorflow.contrib'**

It is from train.py in Tensorflow:
**from tensorflow.contrib import framework as contrib_framework** line 48

Tensorflow Version: 1.14.0
Python3 Version: 3.7.3

I am currently coding in Raspberry Pi.

**Comment by Saduf2019** [comment]
Could you please provide us with simple standalone code to reproduce the issue in our environment, Thanks

**Comment by KoizumiNao** [comment]
I tried to train data using this line in the terminal:
**python3 train.py --logtostderr --train_dir=training/ --pipeline_config_path=training/faster_rcnn_inception_v2_pets.config**

**Comment by mradlmaier** [comment]
Same problem but on local machine: 
**python train.py --logtostderr --train_dir=training/ --pipeline_config_path=training/ssd_inception_v2_coco.config**

**Comment by Saduf2019** [comment]
@KoizumiNao  Please refer to this work around [#31350](https://github.com/tensorflow/tensorflow/issues/31350#issuecomment-520958043). And let us know if the issue still exist.

**Comment by KoizumiNao** [comment]
I found the solution. I installed **1.13.1** of TensorFlow instead. And I tried to run by python3. There's a lot of depreciation warnings. Thank you for the solution, sir.
