### ISSUE TITLE
contrib/makefile:  error: conflicting return type

### ISSUE THREAD

**Issue by antogerva** [tensorflow/tensorflow#3626]
### Environment info
OS:   I'm running on Docker with an Ubuntu 14.04.4 LTS x86_64 (gcc/g++ version is 4.8.4)
No CUDA or cuDNN installed

installed from source

1. The commit hash (`git rev-parse HEAD`)
$ git rev-parse HEAD
27eeb441bad8bcaa1bcba42a4b4ee49fb50ea0d3
(note: I also tried with branch  r0.9 and  r0.10 with the same issue about conflicting return type)

### Steps to reproduce
	$ mkdir /opt/tensor-build/
	$ cd /opt/tensor-build/
	$ git clone https://github.com/tensorflow/tensorflow
	$ cd tensorflow
	$ ./tensorflow/contrib/makefile/download_dependencies.sh
	$ sudo apt-get install autoconf automake libtool curl make g++ unzip
	$ pushd .
	$ cd tensorflow/contrib/makefile/downloads/protobuf
	$ ./autogen.sh
	$ ./configure
	$ make
	$ make check
	$ sudo make install
	$ sudo ldconfig # refresh shared library cache
	$ popd

So far, no issue, then:

	$ make -f tensorflow/contrib/makefile/Makefile
	PROTOC = "protoc"
	CC_PREFIX = ""
	protoc  tensorflow/core/util/test_log.proto --cpp_out /opt/tensor-build/tensorflow/tensorflow/contrib/makefile/gen/proto/
	protoc  tensorflow/core/util/saved_tensor_slice.proto --cpp_out /opt/tensor-build/tensorflow/tensorflow/contrib/makefile/gen/proto/
	protoc  tensorflow/core/util/memmapped_file_system.proto --cpp_out /opt/tensor-build/tensorflow/tensorflow/contrib/makefile/gen/proto/
	protoc  tensorflow/core/util/event.proto --cpp_out /opt/tensor-build/tensorflow/tensorflow/contrib/makefile/gen/proto/
	protoc  tensorflow/core/protobuf/tensorflow_server.proto --cpp_out /opt/tensor-build/tensorflow/tensorflow/contrib/makefile/gen/proto/
	protoc  tensorflow/core/protobuf/saver.proto --cpp_out /opt/tensor-build/tensorflow/tensorflow/contrib/makefile/gen/proto/
	protoc  tensorflow/core/protobuf/queue_runner.proto --cpp_out /opt/tensor-build/tensorflow/tensorflow/contrib/makefile/gen/proto/
	protoc  tensorflow/core/protobuf/named_tensor.proto --cpp_out /opt/tensor-build/tensorflow/tensorflow/contrib/makefile/gen/proto/
	protoc  tensorflow/core/protobuf/meta_graph.proto --cpp_out /opt/tensor-build/tensorflow/tensorflow/contrib/makefile/gen/proto/
	protoc  tensorflow/core/protobuf/config.proto --cpp_out /opt/tensor-build/tensorflow/tensorflow/contrib/makefile/gen/proto/
	protoc  tensorflow/core/lib/core/error_codes.proto --cpp_out /opt/tensor-build/tensorflow/tensorflow/contrib/makefile/gen/proto/
	protoc  tensorflow/core/framework/versions.proto --cpp_out /opt/tensor-build/tensorflow/tensorflow/contrib/makefile/gen/proto/
	protoc  tensorflow/core/framework/variable.proto --cpp_out /opt/tensor-build/tensorflow/tensorflow/contrib/makefile/gen/proto/
	protoc  tensorflow/core/framework/types.proto --cpp_out /opt/tensor-build/tensorflow/tensorflow/contrib/makefile/gen/proto/
	protoc  tensorflow/core/framework/tensor_slice.proto --cpp_out /opt/tensor-build/tensorflow/tensorflow/contrib/makefile/gen/proto/
	protoc  tensorflow/core/framework/tensor_shape.proto --cpp_out /opt/tensor-build/tensorflow/tensorflow/contrib/makefile/gen/proto/
	protoc  tensorflow/core/framework/tensor_description.proto --cpp_out /opt/tensor-build/tensorflow/tensorflow/contrib/makefile/gen/proto/
	protoc  tensorflow/core/framework/tensor.proto --cpp_out /opt/tensor-build/tensorflow/tensorflow/contrib/makefile/gen/proto/
	protoc  tensorflow/core/framework/summary.proto --cpp_out /opt/tensor-build/tensorflow/tensorflow/contrib/makefile/gen/proto/
	protoc  tensorflow/core/framework/step_stats.proto --cpp_out /opt/tensor-build/tensorflow/tensorflow/contrib/makefile/gen/proto/
	protoc  tensorflow/core/framework/op_def.proto --cpp_out /opt/tensor-build/tensorflow/tensorflow/contrib/makefile/gen/proto/
	protoc  tensorflow/core/framework/log_memory.proto --cpp_out /opt/tensor-build/tensorflow/tensorflow/contrib/makefile/gen/proto/
	protoc  tensorflow/core/framework/kernel_def.proto --cpp_out /opt/tensor-build/tensorflow/tensorflow/contrib/makefile/gen/proto/
	protoc  tensorflow/core/framework/graph.proto --cpp_out /opt/tensor-build/tensorflow/tensorflow/contrib/makefile/gen/proto/
	protoc  tensorflow/core/framework/function.proto --cpp_out /opt/tensor-build/tensorflow/tensorflow/contrib/makefile/gen/proto/
	protoc  tensorflow/core/framework/device_attributes.proto --cpp_out /opt/tensor-build/tensorflow/tensorflow/contrib/makefile/gen/proto/
	protoc  tensorflow/core/framework/cost_graph.proto --cpp_out /opt/tensor-build/tensorflow/tensorflow/contrib/makefile/gen/proto/
	protoc  tensorflow/core/framework/attr_value.proto --cpp_out /opt/tensor-build/tensorflow/tensorflow/contrib/makefile/gen/proto/
	protoc  tensorflow/core/framework/allocation_description.proto --cpp_out /opt/tensor-build/tensorflow/tensorflow/contrib/makefile/gen/proto/
	protoc  tensorflow/core/example/feature.proto --cpp_out /opt/tensor-build/tensorflow/tensorflow/contrib/makefile/gen/proto/
	protoc  tensorflow/core/example/example.proto --cpp_out /opt/tensor-build/tensorflow/tensorflow/contrib/makefile/gen/proto/
	protoc  tensorflow/core/util/test_log.proto --cpp_out /opt/tensor-build/tensorflow/tensorflow/contrib/makefile/gen/host_obj/
	protoc  tensorflow/core/util/saved_tensor_slice.proto --cpp_out /opt/tensor-build/tensorflow/tensorflow/contrib/makefile/gen/host_obj/
	protoc  tensorflow/core/util/memmapped_file_system.proto --cpp_out /opt/tensor-build/tensorflow/tensorflow/contrib/makefile/gen/host_obj/
	protoc  tensorflow/core/util/event.proto --cpp_out /opt/tensor-build/tensorflow/tensorflow/contrib/makefile/gen/host_obj/
	protoc  tensorflow/core/protobuf/tensorflow_server.proto --cpp_out /opt/tensor-build/tensorflow/tensorflow/contrib/makefile/gen/host_obj/
	protoc  tensorflow/core/protobuf/saver.proto --cpp_out /opt/tensor-build/tensorflow/tensorflow/contrib/makefile/gen/host_obj/
	protoc  tensorflow/core/protobuf/queue_runner.proto --cpp_out /opt/tensor-build/tensorflow/tensorflow/contrib/makefile/gen/host_obj/
	protoc  tensorflow/core/protobuf/named_tensor.proto --cpp_out /opt/tensor-build/tensorflow/tensorflow/contrib/makefile/gen/host_obj/
	protoc  tensorflow/core/protobuf/meta_graph.proto --cpp_out /opt/tensor-build/tensorflow/tensorflow/contrib/makefile/gen/host_obj/
	protoc  tensorflow/core/protobuf/config.proto --cpp_out /opt/tensor-build/tensorflow/tensorflow/contrib/makefile/gen/host_obj/
	protoc  tensorflow/core/lib/core/error_codes.proto --cpp_out /opt/tensor-build/tensorflow/tensorflow/contrib/makefile/gen/host_obj/
	protoc  tensorflow/core/framework/versions.proto --cpp_out /opt/tensor-build/tensorflow/tensorflow/contrib/makefile/gen/host_obj/
	protoc  tensorflow/core/framework/variable.proto --cpp_out /opt/tensor-build/tensorflow/tensorflow/contrib/makefile/gen/host_obj/
	protoc  tensorflow/core/framework/types.proto --cpp_out /opt/tensor-build/tensorflow/tensorflow/contrib/makefile/gen/host_obj/
	protoc  tensorflow/core/framework/tensor_slice.proto --cpp_out /opt/tensor-build/tensorflow/tensorflow/contrib/makefile/gen/host_obj/
	protoc  tensorflow/core/framework/tensor_shape.proto --cpp_out /opt/tensor-build/tensorflow/tensorflow/contrib/makefile/gen/host_obj/
	protoc  tensorflow/core/framework/tensor_description.proto --cpp_out /opt/tensor-build/tensorflow/tensorflow/contrib/makefile/gen/host_obj/
	protoc  tensorflow/core/framework/tensor.proto --cpp_out /opt/tensor-build/tensorflow/tensorflow/contrib/makefile/gen/host_obj/
	protoc  tensorflow/core/framework/summary.proto --cpp_out /opt/tensor-build/tensorflow/tensorflow/contrib/makefile/gen/host_obj/
	protoc  tensorflow/core/framework/step_stats.proto --cpp_out /opt/tensor-build/tensorflow/tensorflow/contrib/makefile/gen/host_obj/
	protoc  tensorflow/core/framework/op_def.proto --cpp_out /opt/tensor-build/tensorflow/tensorflow/contrib/makefile/gen/host_obj/
	protoc  tensorflow/core/framework/log_memory.proto --cpp_out /opt/tensor-build/tensorflow/tensorflow/contrib/makefile/gen/host_obj/
	protoc  tensorflow/core/framework/kernel_def.proto --cpp_out /opt/tensor-build/tensorflow/tensorflow/contrib/makefile/gen/host_obj/
	protoc  tensorflow/core/framework/graph.proto --cpp_out /opt/tensor-build/tensorflow/tensorflow/contrib/makefile/gen/host_obj/
	protoc  tensorflow/core/framework/function.proto --cpp_out /opt/tensor-build/tensorflow/tensorflow/contrib/makefile/gen/host_obj/
	protoc  tensorflow/core/framework/device_attributes.proto --cpp_out /opt/tensor-build/tensorflow/tensorflow/contrib/makefile/gen/host_obj/
	protoc  tensorflow/core/framework/cost_graph.proto --cpp_out /opt/tensor-build/tensorflow/tensorflow/contrib/makefile/gen/host_obj/
	protoc  tensorflow/core/framework/attr_value.proto --cpp_out /opt/tensor-build/tensorflow/tensorflow/contrib/makefile/gen/host_obj/
	protoc  tensorflow/core/framework/allocation_description.proto --cpp_out /opt/tensor-build/tensorflow/tensorflow/contrib/makefile/gen/host_obj/
	protoc  tensorflow/core/example/feature.proto --cpp_out /opt/tensor-build/tensorflow/tensorflow/contrib/makefile/gen/host_obj/
	protoc  tensorflow/core/example/example.proto --cpp_out /opt/tensor-build/tensorflow/tensorflow/contrib/makefile/gen/host_obj/
	gcc --std=c++11 -I. -I/opt/tensor-build/tensorflow/tensorflow/contrib/makefile/downloads/ -I/opt/tensor-build/tensorflow/tensorflow/contrib/makefile/download
	s/eigen-eigen-b4fa9622b809 -I/opt/tensor-build/tensorflow/tensorflow/contrib/makefile/gen/host_obj/ -I/usr/local/include -c tensorflow/tools/proto_text/gen_p
	roto_text_functions_lib.cc -o /opt/tensor-build/tensorflow/tensorflow/contrib/makefile/gen/host_obj/tensorflow/tools/proto_text/gen_proto_text_functions_lib.
	o
	gcc --std=c++11 -I. -I/opt/tensor-build/tensorflow/tensorflow/contrib/makefile/downloads/ -I/opt/tensor-build/tensorflow/tensorflow/contrib/makefile/download
	s/eigen-eigen-b4fa9622b809 -I/opt/tensor-build/tensorflow/tensorflow/contrib/makefile/gen/host_obj/ -I/usr/local/include -c tensorflow/tools/proto_text/gen_p
	roto_text_functions.cc -o /opt/tensor-build/tensorflow/tensorflow/contrib/makefile/gen/host_obj/tensorflow/tools/proto_text/gen_proto_text_functions.o
	gcc --std=c++11 -I. -I/opt/tensor-build/tensorflow/tensorflow/contrib/makefile/downloads/ -I/opt/tensor-build/tensorflow/tensorflow/contrib/makefile/download
	s/eigen-eigen-b4fa9622b809 -I/opt/tensor-build/tensorflow/tensorflow/contrib/makefile/gen/host_obj/ -I/usr/local/include -c tensorflow/core/platform/tracing.
	cc -o /opt/tensor-build/tensorflow/tensorflow/contrib/makefile/gen/host_obj/tensorflow/core/platform/tracing.o
	gcc --std=c++11 -I. -I/opt/tensor-build/tensorflow/tensorflow/contrib/makefile/downloads/ -I/opt/tensor-build/tensorflow/tensorflow/contrib/makefile/download
	s/eigen-eigen-b4fa9622b809 -I/opt/tensor-build/tensorflow/tensorflow/contrib/makefile/gen/host_obj/ -I/usr/local/include -c tensorflow/core/platform/tensor_c
	oding.cc -o /opt/tensor-build/tensorflow/tensorflow/contrib/makefile/gen/host_obj/tensorflow/core/platform/tensor_coding.o
	gcc --std=c++11 -I. -I/opt/tensor-build/tensorflow/tensorflow/contrib/makefile/downloads/ -I/opt/tensor-build/tensorflow/tensorflow/contrib/makefile/download
	s/eigen-eigen-b4fa9622b809 -I/opt/tensor-build/tensorflow/tensorflow/contrib/makefile/gen/host_obj/ -I/usr/local/include -c tensorflow/core/platform/protobuf
	_util.cc -o /opt/tensor-build/tensorflow/tensorflow/contrib/makefile/gen/host_obj/tensorflow/core/platform/protobuf_util.o
	gcc --std=c++11 -I. -I/opt/tensor-build/tensorflow/tensorflow/contrib/makefile/downloads/ -I/opt/tensor-build/tensorflow/tensorflow/contrib/makefile/download
	s/eigen-eigen-b4fa9622b809 -I/opt/tensor-build/tensorflow/tensorflow/contrib/makefile/gen/host_obj/ -I/usr/local/include -c tensorflow/core/platform/posix/po
	six_file_system.cc -o /opt/tensor-build/tensorflow/tensorflow/contrib/makefile/gen/host_obj/tensorflow/core/platform/posix/posix_file_system.o
	gcc --std=c++11 -I. -I/opt/tensor-build/tensorflow/tensorflow/contrib/makefile/downloads/ -I/opt/tensor-build/tensorflow/tensorflow/contrib/makefile/download
	s/eigen-eigen-b4fa9622b809 -I/opt/tensor-build/tensorflow/tensorflow/contrib/makefile/gen/host_obj/ -I/usr/local/include -c tensorflow/core/platform/posix/po
	rt.cc -o /opt/tensor-build/tensorflow/tensorflow/contrib/makefile/gen/host_obj/tensorflow/core/platform/posix/port.o
	gcc --std=c++11 -I. -I/opt/tensor-build/tensorflow/tensorflow/contrib/makefile/downloads/ -I/opt/tensor-build/tensorflow/tensorflow/contrib/makefile/download
	s/eigen-eigen-b4fa9622b809 -I/opt/tensor-build/tensorflow/tensorflow/contrib/makefile/gen/host_obj/ -I/usr/local/include -c tensorflow/core/platform/posix/en
	v.cc -o /opt/tensor-build/tensorflow/tensorflow/contrib/makefile/gen/host_obj/tensorflow/core/platform/posix/env.o
	gcc --std=c++11 -I. -I/opt/tensor-build/tensorflow/tensorflow/contrib/makefile/downloads/ -I/opt/tensor-build/tensorflow/tensorflow/contrib/makefile/download
	s/eigen-eigen-b4fa9622b809 -I/opt/tensor-build/tensorflow/tensorflow/contrib/makefile/gen/host_obj/ -I/usr/local/include -c tensorflow/core/platform/load_lib
	rary.cc -o /opt/tensor-build/tensorflow/tensorflow/contrib/makefile/gen/host_obj/tensorflow/core/platform/load_library.o
	gcc --std=c++11 -I. -I/opt/tensor-build/tensorflow/tensorflow/contrib/makefile/downloads/ -I/opt/tensor-build/tensorflow/tensorflow/contrib/makefile/download
	s/eigen-eigen-b4fa9622b809 -I/opt/tensor-build/tensorflow/tensorflow/contrib/makefile/gen/host_obj/ -I/usr/local/include -c tensorflow/core/platform/file_sys
	tem.cc -o /opt/tensor-build/tensorflow/tensorflow/contrib/makefile/gen/host_obj/tensorflow/core/platform/file_system.o
	gcc --std=c++11 -I. -I/opt/tensor-build/tensorflow/tensorflow/contrib/makefile/downloads/ -I/opt/tensor-build/tensorflow/tensorflow/contrib/makefile/download
	s/eigen-eigen-b4fa9622b809 -I/opt/tensor-build/tensorflow/tensorflow/contrib/makefile/gen/host_obj/ -I/usr/local/include -c tensorflow/core/platform/env.cc -
	o /opt/tensor-build/tensorflow/tensorflow/contrib/makefile/gen/host_obj/tensorflow/core/platform/env.o
	tensorflow/core/platform/env.cc:304:9: error: conflicting return type specified for 'virtual tensorflow::int64 tensorflow::{anonymous}::FileStream::ByteCount
	() const'
	   int64 ByteCount() const override { return pos_; }
	         ^
	In file included from ./tensorflow/core/platform/default/protobuf.h:26:0,
	                 from ./tensorflow/core/platform/protobuf.h:31,
	                 from ./tensorflow/core/platform/file_system.h:28,
	                 from ./tensorflow/core/platform/env.h:27,
	                 from tensorflow/core/platform/env.cc:23:
	/usr/include/google/protobuf/io/zero_copy_stream.h:172:17: error:   overriding 'virtual google::protobuf::int64 google::protobuf::io::ZeroCopyInputStream::By
	teCount() const'
	   virtual int64 ByteCount() const = 0;
	                 ^
	make: *** [/opt/tensor-build/tensorflow/tensorflow/contrib/makefile/gen/host_obj/tensorflow/core/platform/env.o] Error 1

**Comment by mrry** [comment]
I think this recent change to `protobuf` might be causing the problem: https://github.com/google/protobuf/commit/a17367f44a3b592993d2ac5c074ed58fb0ce784c. (I noticed the same issue when attempting to build TensorFlow with the 3.0.0 release.) A stop-gap solution would be to change [`download_dependencies.sh`](https://github.com/tensorflow/tensorflow/blob/27eeb441bad8bcaa1bcba42a4b4ee49fb50ea0d3/tensorflow/contrib/makefile/download_dependencies.sh#L41) so that it uses a known-good version of `protobuf`. For example, something like the following should work:

```bash
git clone https://github.com/google/protobuf.git ${DOWNLOADS_DIR}/protobuf
pushd ${DOWNLOADS_DIR}/protobuf
git checkout d5fb408ddc281ffcadeb08699e65bb694656d0bd  # hash for 3.0.0-beta-2
popd
```

**Comment by antogerva** [comment]
Thanks, look like the hash d5fb408ddc281ffcadeb08699e65bb694656d0bd works well for protobuf and now I've been able to compile Tensorflow.
