### ISSUE TITLE
Support tf.SparseTensor and tf.RaggedTensor in tf.py_function

### ISSUE THREAD

**Issue by VitaliKaiser** [tensorflow/tensorflow#36278]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using): tensorflow==2.1.0
- Are you willing to contribute it (Yes/No): Yes

**Describe the feature and the current behavior/state.**
`tf.py_function` executes eagerly and therefore does support to mix python and TF functions.
Creating instances of  tf.SparseTensor and tf.RaggedTensor is not a problem.
But if there are in the return statement tf.pyfunction crashes, because I assume its expecting a tf.Tensor.

Example:

````
def eager_py_ragged(arg1_eager):

    return tf.RaggedTensor.from_tensor(arg1_eager, dtype=tf.int32)

arg1_const = tf.constant(1, dtype=tf.int32)

tf.py_function(eager_py_sparse, [arg1_const], [tf.int32])
# tf.python.framework.errors_impl.InvalidArgumentError:
# ValueError: Attempt to convert a value (<tensorflow.python.framework.sparse_tensor.SparseTensor object at X)
# with an unsupported type (<class 'tensorflow.python.framework.sparse_tensor.SparseTensor'>) to a Tensor.
````

**Will this change the current api? How?**
I dont think so.
**Who will benefit with this feature?**
People building their `tf.data` pipeline with `tf.pyfunction`.
**Any Other info.**
I will create more `tf.py_function` related stories. Since this are distinct features from my POV, there multiple feature requests. I hope this is ok.

**Comment by Leslie-Fang** [comment]
@VitaliKaiser  Create a PR to convert the sparse tensor and ragged tensor into the uniform tensor

**Comment by atyshka** [comment]
Updates on this?

**Comment by edloper** [comment]
In https://github.com/tensorflow/tensorflow/issues/27679#issuecomment-522578000, I showed how py_function could be extended to handle composite tensor inputs and outputs (and other nested structures, like dicts, tuples, lists, etc).  If you have bandwidth to work on a PR that adds that to TensorFlow (with tests etc.), then it would be very welcome; otherwise, you could just use the `new_py_function` that I defined there, which wraps `tf.py_function`.

**Comment by yehDilBeparwah** [comment]
Definitely still not working @google-ml-butler

**Comment by sjtusmartboy** [comment]
Please reopen it. Tensorflow should  support it

**Comment by Cospel** [comment]
Hi, can you please reopen it...

Right now I need to convert polygons (in coco format) as ragged tensors to binary masks:

```python
 def decode(self, image_id, file_name, labels, bboxes, seg_masks):
     image = self._load_image({"file_name": file_name})

     h, w = tf.cast(tf.shape(image)[0], tf.float32), tf.cast(tf.shape(image)[1], tf.float32)
     bboxes /= tf.stack([h, w, h, w])

     seg_masks = tf_py_segmentations(seg_masks, h, w)
     return image, labels, bboxes, seg_masks, image_id

def get_segmentations(segments, h, w):
    seg_masks = []
    for segmentations in segments:
        mask = np.zeros((BASE_SEG_MASK_SIZE, BASE_SEG_MASK_SIZE, 1))
        for segmentation in segmentations:
            points = np.asarray([[int((x/w) * BASE_SEG_MASK_SIZE), int((y/h) * BASE_SEG_MASK_SIZE)] for x, y in zip(segmentation[::2], list(reversed(segmentation[::-2])))])
            cv2.fillPoly(mask, [points], color=(1,1,1))
        seg_masks.append(mask)#.astype(np.float32).tolist())
    return np.asarray(seg_masks, dtype=np.float32)


@tf.function
def tf_py_segmentations(segmentations, h, w):
    segmentations = segmentations.shape
    segmentations = tf.py_function(get_segmentations, [segmentations, h, w], [tf.float32])
    segmentations.set_shape((None,BASE_SEG_MASK_SIZE, BASE_SEG_MASK_SIZE, 1))
    return segmentations

```

However I get this error:

    TypeError: Tensors in list passed to 'input' of 'EagerPyFunc' Op have types [<NOT CONVERTIBLE TO TENSOR>, float32, float32] that are invalid. Tensors: [TensorShape([None, None]), <tf.Tensor 'h:0' shape=() dtype=float32>, <tf.Tensor 'w:0' shape=() dtype=float32>]
