### ISSUE TITLE
Build on MacOS for Select Operators TFLite error

### ISSUE THREAD

**Issue by rangsaritv** [tensorflow/tensorflow#36275]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): MacOS 10.14.5
- TensorFlow installed from (source or binary): installed from source
- TensorFlow version (use command below):  v2.0.1
- Python version: 3.5.2
- Bazel version (if compiling from source):  0.26.1
- GCC/Compiler version (if compiling from source):  Apple clang version 11.0.0 (clang-1100.0.33.17)

**Describe the current behavior**

When build by using  _tensorflow/contrib/makefile/build_all_ios_with_tflite.sh_ the following error occur:

...
tensorflow/lite/minimal_logging_android.cc:18:10: fatal error: 'android/log.h' file not found
#include <android/log.h>
         ^~~~~~~~~~~~~~~
1 error generated.
make: *** [/Users/jay/Documents/tensorflow2/tensorflow/contrib/makefile/gen/obj/ios_ARM64/tensorflow/lite/minimal_logging_android.o] Error 1
....
**Describe the expected behavior**

The build is completed and generates files, libtensorflow-lite.a, libprotobuf.a, nsync.a, for using in XCode.

**Code to reproduce the issue**

- run ./configure 
-- setup WORKSPACE 
-- choose 'build TensorFlow with iOS support'
- run tensorflow/contrib/makefile/build_all_ios_with_tflite.sh

the result of setting up Android WORKSPACE in .tf_configure.bazelrc  is

...
build --action_env ANDROID_NDK_HOME="/Users/jay/Library/Android/sdk/ndk/17.2.4988734"
build --action_env ANDROID_NDK_API_LEVEL="21"
build --action_env ANDROID_BUILD_TOOLS_VERSION="29.0.2"
build --action_env ANDROID_SDK_API_LEVEL="27"
build --action_env ANDROID_SDK_HOME="/Users/jay/Library/Android/sdk"
...

**Comment by jdduke** [comment]
Over to @yyoon to help.

**Comment by terryheo** [comment]
@rangsaritv The contribute directory is removed since r2.1 release.
Also there is an official way of building iOS TFLite using bazel.
https://www.tensorflow.org/lite/guide/build_ios

Before going though, you need to install some Python packages.
https://www.tensorflow.org/install/source

**Comment by rangsaritv** [comment]
@terryheo Thank you very much for your help. :)
