### ISSUE TITLE
Dimension is expanded for Keras scalar input in eager mode

### ISSUE THREAD

**Issue by PavelKovalets** [tensorflow/tensorflow#36279]
**System information**
- Have I written custom code: **YES**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): **Windows 10**
- TensorFlow installed from (source or binary): **pip**
- TensorFlow version (use command below): **v2.1.0-rc2-17-ge5bf8de410 2.1.0**
- Python version: **Python 3.7.3**
- CUDA/cuDNN version: **CUDA v10.1 / cuDNN 7.6.4** 
- GPU model and memory: **NVIDIA GeForce GTX 1060 with Max-Q Design 6 GB**

**Describe the current behavior**

If input layer for keras model is scalar and model is executing eagerly `model.compile(run_eagerly=True)` then

- The shape of the input tensor is expanded up to 1 dimension (`TensorShape([16, 1])` instead of `TensorShape([16])` including the batch dimension if batch size is 16.
- Warning is shown `WARNING:tensorflow:Model was constructed with shape Tensor("the_input:0", shape=(16,), dtype=float32) for input (16,), but it was re-called on a Tensor with incompatible shape (16, 1).`

If `run_eagerly=False` then the shape is as expected.

This is pretty critical in our case because we use scalar input for `label_length` argument of [tf.nn.ctc_loss](https://www.tensorflow.org/api_docs/python/tf/nn/ctc_loss) which requires tensor of shape `[batch_size]` and fails with really vague error if shape is `[batch_size,1]`

**Describe the expected behavior**
The shape should be kept as specified - `TensorShape([16])` - and no warning is shown.

**Code to reproduce the issue**

```python
import tensorflow as tf
import numpy as np
import sys


batch_size = 16
input_batch = np.ones((batch_size,)).astype(np.float32)


class TestSequence(tf.keras.utils.Sequence):
    def __len__(self):
        return 1

    def __getitem__(self, idx):
        return input_batch, input_batch

# Dummy layer to show the tensor shape
class PrintLayer(tf.keras.layers.Layer):
    def call(self, inputs):
        tf.print(inputs.shape, output_stream=sys.stderr)
        return inputs


# The result is the same if shape=() is used to specify scalar input
input_layer = tf.keras.layers.Input(
    name='the_input', batch_shape=(batch_size,), dtype='float32')
x = PrintLayer()(input_layer)
output_layer = tf.keras.layers.ReLU()(x)
model = tf.keras.models.Model(inputs=[input_layer], outputs=[output_layer])

# If run_eagerly=False then the shapes are correct
model.compile(loss='mse', run_eagerly=True)

model.fit(TestSequence(), epochs=3)
```
**Other info / logs**

I've tracked the source of this change up to the following line (callstack below)

```
standardize_single_array, training_utils.py:454
<listcomp>, training_utils.py:529
standardize_input_data, training_utils.py:529
_standardize_tensors, training.py:2410
_standardize_user_data, training.py:2383
train_on_batch, training_v2_utils.py:416
wrapper, api.py:258
_call_for_each_replica, distribute_lib.py:2164
call_for_each_replica, distribute_lib.py:1819
experimental_run_v2, distribute_lib.py:763
distributed_function, training_v2_utils.py:85
execution_function, training_v2_utils.py:98
run_one_epoch, training_v2.py:128
fit, training_v2.py:342
fit, training.py:819
```

Seems like the expected shapes are not passed if the eager mode is on (see [this line](https://github.com/tensorflow/tensorflow/blob/v2.1.0/tensorflow/python/keras/engine/training.py#L2391)) and hence the error.

Here is a [link to gist in colab](https://gist.github.com/PavelKovalets/2e0bb75fe234d355773f291dd8c4bdb3).

**Comment by Saduf2019** [comment]
i am able to replicate the issue, please find the [gist](https://colab.research.google.com/gist/Saduf2019/f954acee0b06d7b1dbdaabc751ea69a0/untitled11.ipynb) here.

**Comment by gowthamkpr** [comment]
This is expected behavior in both Tensorflow Keras and Keras and is being clearly mentioned [here](https://github.com/keras-team/keras/issues/12058#issuecomment-455453006).

**Comment by PavelKovalets** [comment]
@gowthamkpr as for me it is quite strange that the behaviour differs when eager is turned on and off. So if the expected behaviour is to always expand dims of a scalar input, why the shape is not changed if I run it with `run_eagerly=False` - it is `TensorShape([16])`? Shouldn't it be consistent?

And by the way does it mean that it is not possible to have scalar input? If so (which is at least seems like an artificial limitation), then maybe it should be mentioned somewhere in documentation and in the [related issue](https://github.com/tensorflow/tensorflow/issues/14384).

**Comment by omalleyt12** [comment]
@PavelKovalets Thanks for the issue! This is fixed in the latest nightly `pip install -U tf-nightly`
