### ISSUE TITLE
Go API performance concerns with NewTensor & Value

### ISSUE THREAD

**Issue by philpearl** [tensorflow/tensorflow#36288]
The Go NewTensor call will unnecessarly incur a large number of allocations (e.g. >20,000 for a 100x100x100 tensor). There are similar issues with .Value. It's possible to work around the issue by using ReadTensor and WriteTensorTo.

I'm basically wondering if a PR to fix this would stand a chance of being accepted? If there's a chance I might have a go. The 'best' fix would likely use unsafe - would the maintainers be squeamish about that?

**Comment by ravikyram** [comment]
@philpearl 
Can you please elaborate the context. Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version. 

Please, provide code snippet to reproduce the issue. Thanks!

**Comment by philpearl** [comment]
```go
func BenchmarkNewTensor(b *testing.B) {
	vec := make([][][]float32, 100)
	for i := range vec {
		vec[i] = make([][]float32, 100)
		for j := range vec[i] {
			vec[i][j] = make([]float32, 100)
		}
	}
	b.ReportAllocs()
	b.RunParallel(func(pb *testing.PB) {
		for pb.Next() {
			tf.NewTensor(vec)
		}
	})
}
```

```
goos: darwin
goarch: amd64
pkg: github.com/philpearl/blog/content/post
BenchmarkNewTensor-16    	     394	   2864453 ns/op	 4491643 B/op	   20033 allocs/op
PASS
ok  	github.com/philpearl/blog/content/post	1.660s
Success: Benchmarks passed.
```

Almost all of these allocations are unnecessary.

I'm more wondering if you'd be interested in a contribution to improve this than looking for a fix - we're sidestepping by using ReadTensor.

**Comment by ravikyram** [comment]
@philpearl 

Can you please let us know which version of TensorFlow you are facing the issue. Thanks!

**Comment by philpearl** [comment]
tensorflow 1.13, but I believe the issue is also present in 1.15 and v2

**Comment by jhseu** [comment]
Definitely open to taking fixes for this. I'm having trouble understanding the proposed fix, though. The allocations here are user-side. Are you proposing constructing the tensor and then allowing the user to directly write to it?

**Comment by philpearl** [comment]
In my benchmarks the allocations are downstream of encodeTensor. 50% are within binary.Write and 50% are converting the value to an interface inorder to call binary.Write

<img width="424" alt="image" src="https://user-images.githubusercontent.com/456668/74087579-aa826700-4a85-11ea-9140-c5f03ecdf74d.png">

The proposed fix is to avoid binary.Write and to copy the contents of the final slice directly into the C tensor.

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.
