### ISSUE TITLE
keras freezing at last step in the first epoch

### ISSUE THREAD

**Issue by divyag11** [tensorflow/tensorflow#36287]
My model is using tf 2.0 and tf.keras 2.2.4 . When I train the model, it freezes at the last step of the first epoch. I am using :
 history = model.fit(
     train_dataset,
   epochs=EPOCHS,
    steps_per_epoch=train_steps,
    validation_data=valid_dataset,
   validation_steps=valid_steps,
 )
the train_dataset and valid_dataset is of type: <class 'tensorflow.python.data.ops.dataset_ops.DatasetV1Adapter'>
PLEASE LOOK INTO THE MATTER.

**Comment by yzhuang** [comment]
This is likely the same issue as https://github.com/keras-team/keras/issues/8595

When I ran into it, I noticed that if I don't supply `validation_data`, it didn't freeze.  When I supplied `validation_data`, it frozen on the last step in first epoch.

**Comment by Saduf2019** [comment]
@divyag11  Could you please provide us with simple standalone code to reproduce the issue in our environment, Thanks

**Comment by divyag11** [comment]
> @divyag11 Could you please provide us with simple standalone code to reproduce the issue in our environment, Thanks

yes sure:
could you let me know your email address,so that i send you the coalb notebook?

**Comment by divyag11** [comment]
please let me know what is the issue so that it stops at the last step in the first epoch.thanks

**Comment by divyag11** [comment]
@jvishnuvardhan, did you find what was the cause for the issue of freezing at the last step of 1st epoch?

**Comment by divyag11** [comment]
> This is likely the same issue as [keras-team/keras#8595](https://github.com/keras-team/keras/issues/8595)
> 
> When I ran into it, I noticed that if I don't supply `validation_data`, it didn't freeze. When I supplied `validation_data`, it frozen on the last step in first epoch.
could you come up with the reason, why it happened

**Comment by divyag11** [comment]
> > This is likely the same issue as [keras-team/keras#8595](https://github.com/keras-team/keras/issues/8595)
> > When I ran into it, I noticed that if I don't supply `validation_data`, it didn't freeze. When I supplied `validation_data`, it frozen on the last step in first epoch.


> > could you come up with the reason, why it happened

**Comment by jvishnuvardhan** [comment]
@divyag11 I could reproduce the issue with `tf-nightly`. I updated your colab to make it run. [Here](https://colab.research.google.com/gist/jvishnuvardhan/19a0e237eb539c621d9872982f378085/test.ipynb) is the updated gist for our reference. Thanks!

**Comment by alextp** [comment]
@omalleyt12 do you know what's going on here?

**Comment by omalleyt12** [comment]
@alextp Yep discussed this in triage, we think it's either an issue with how the validation dataset is constructed or assumptions we are making about the validation dataset size. 

@jvishnuvardhan is working on a minimal repro

**Comment by jvishnuvardhan** [comment]
@divyag11 I looked into the your data and code. I think something is wrong with the construction of validation dataset. In the code when I used `final_dataset` for training as well as validation(replacing `valid_dataset` with `final_dataset`), everything works as expected  Can you please check `valid_dataset`? Thanks!

**Comment by divyag11** [comment]
okay,got your point.actually what i understood is since i am calling from genertors two times,with 2 different generator functions,and according to my understanding,the 1st generator is caching and producing the trainig batches ,while the 2 nd batch is not .Is it that we can use only 1 genertor for get_form_genertor in tf?

**Comment by jvishnuvardhan** [comment]
@divyag11 You could use two generators, one for training and one for validation. As I mentioned in my last response, I think something is wrong with the construction of validation dataset. I tried to use your validation dataset for training without any validation(without providing `validation_data` and `validation_steps` as shown below), and the code runs forever. Which means, i think there is something wrong with the construction of validation dataset.

```
history = model.fit(
    valid_dataset,
    epochs=EPOCHS,
    steps_per_epoch=valid_steps
) 
```

You could run my gist and check it yourself. Before running my gist, just upload your `data.zip` file to your google drive. Thanks!

**Comment by jvishnuvardhan** [comment]
@divyag11 Is this resolved or still an issue? Please close the issue if it was already resolved. Thanks!

**Comment by divyag11** [comment]
yes the issue is resolved

**Comment by jvishnuvardhan** [comment]
@divyag11 Thanks for the confirmation. I am closing this issue as it was resolved. Thanks!
