### ISSUE TITLE
unsupported operand type(s) for *: 'int' and 'NoneType' in training_v2

### ISSUE THREAD

**Issue by Flamefire** [tensorflow/tensorflow#36281]
**System information**
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below): 2.1.0

Running a simple evaluation of a Lenet Model with MNIST dataset (from TFDS) with a large batch size (e.g. due to using many workers) leads to 

```
tensorflow.python.framework.errors_impl.OutOfRangeError: 2 root error(s) found.
  (0) Out of range:  End of sequence
	 [[node IteratorGetNext_2 (defined at git/tensorflow_tests/train_distributed.py:212) ]]
	 [[metrics/accuracy/div_no_nan/allreduce_1/CollectiveReduce/_70]]
  (1) Out of range:  End of sequence
	 [[node IteratorGetNext_2 (defined at git/tensorflow_tests/train_distributed.py:212) ]]
```

and

```
File "/scratch/ws/s3248973-EasyBuild/easybuild-haswell/software/TensorFlow/2.1.0-fosscuda-2019b-Python-3.7.4/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training_v2.py", line 152, in run_one_epoch
    total_epochs * steps_per_epoch))
TypeError: unsupported operand type(s) for *: 'int' and 'NoneType'
```

The bug is pretty obvious in https://github.com/tensorflow/tensorflow/blob/7b0cfadc895d74aec99875a23ed296506c98e88c/tensorflow/python/keras/engine/training_v2.py#L152 where `steps_per_epoch` is used although it can be (and is) None, see also https://github.com/tensorflow/tensorflow/blob/7b0cfadc895d74aec99875a23ed296506c98e88c/tensorflow/python/keras/engine/training_v2.py#L135

**Comment by Saduf2019** [comment]
@Flamefire Could you please provide us with simple standalone code to reproduce the issue in our environment, Thanks.

**Comment by Flamefire** [comment]
I'm having trouble reproducing this with a reduced sample. What I did was using the MultiWorkerMirroredStrategy with a simple MNIST test and 2 nodes. For some reason the dataset was not able to produce a single batch and raised OutOfRangeError which lead to the above linked handling code. As the step is still zero the 2nd branch (see link above) is taken and steps_per_epoch is used without checking it for None (which it still is)

I see if I can come up with some sample code which is small enough but the issue is obvious from reading the code.

**Comment by gthb** [comment]
FYI I saw this same failure, but in my case the cause was that I was running with a very small dataset (puny laptop testing...), such that the validation dataset (which I was creating as just the last 10% of the overall set) did not fill a full batch (and I was discarding the remainder, so probably feeding an empty validation set). @Flamefire you mentioned “with a large batch size” — might this be your situation as well?

**Comment by Flamefire** [comment]
@gthb I guess so, yes. But there still is a bug in the code as a value which can be None is used expecting it to be not None.

**Comment by alimhanif** [comment]
I guess you are using TF 2.1

I upgrade to version V2.2.0.rc3. It solved the problem! (This version is not using `training_v2` anymore, btw)

Thanks!

**Comment by hamzarabi3** [comment]
It happened to me while trying to convert tf.data.Dataset elements :
`for (image, label) in train_ds.take(3):`
    `print(f'{image.numpy().shape} and {label.numpy().shape}')`
strangely, I restarted the kernel and the error just disappeared.

**Comment by Flamefire** [comment]
Reviewing the code for v2.3.0-rc0 I conclude that this was fixed
