### ISSUE TITLE
Problems in "Implement the gradient in Python" docs

### ISSUE THREAD

**Issue by harpone** [tensorflow/tensorflow#3629]
Referring to the docs [here](https://www.tensorflow.org/versions/r0.10/how_tos/adding_an_op/index.html#implement-the-gradient-in-python)

First of all, the chain rule is completely wrong. Also the `ZeroOut` example is not a very good one IMO... would be much better to give e.g. a simple derivative of a polynomial or something. Just a FYI.

EDIT: I'd like to emphasize that the chain rule is *embarrasingly* wrong...

**Comment by girving** [comment]
@harpone It's only embarrassingly wrong if one is irrationally embarrassed by making mistakes!

**Comment by girving** [comment]
@harpone Do clarify: by "embarrassingly wrong" all you mean is that it should be "dL/dx = dL/dy dy/dx" to avoid implying that "d/dy" is differentiating "dy/dx"?

**Comment by harpone** [comment]
Yup, exactly! Was a bit tired yesterday so maybe I overreacted a bit though :)

Anyway, for example the abs + it's gradient would probably make for a better example?

**Comment by harpone** [comment]
Oops actually maybe `abs` is not a good example, see (this)[https://github.com/tensorflow/tensorflow/issues/3647] (possible) bug.

**Comment by girving** [comment]
@harpone Are you happy with this chain rule fix?  https://github.com/girving/tensorflow/commit/05e7bc317317cc868710db2762acaab87b8c17a4

**Comment by harpone** [comment]
Sure, that's much better!

**Comment by girving** [comment]
So the PR to fix the chain rule mention is https://github.com/tensorflow/tensorflow/pull/3650.  As for the example, @harpone: do you want to personally fix it?  It's a nontrivial amount of work for a marginal gain, since the goal of the tutorial is to teach people how to use the API, not to teach them calculus.

**Comment by harpone** [comment]
I'm afraid I don't have the time right now, but I may submit a PR related
on another thing (log abs det gradient etc.) some time in the future, so I
could also do this in the same PR? No promises however, it could take a
while...

**Comment by girving** [comment]
@harpone That sounds like it should be a separate PR.  I'll close this one for now.
