### ISSUE TITLE
I need to connect my uvc camera with the object detection application (android).

### ISSUE THREAD

**Issue by cp0418** [tensorflow/tensorflow#36297]
Could someone tell me how to config or where I should config?

**Comment by amahendrakar** [comment]
@cp0418,
Could you please check out the object detection guide for mobile devices from this [link](https://www.tensorflow.org/lite/models/object_detection/overview). Thanks!

**Comment by amahendrakar** [comment]
Any updates regarding this issue? Thanks!

**Comment by amahendrakar** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Comment by mahamatnoumai** [comment]
> @cp0418,
> Could you please check out the object detection guide for mobile devices from this [link](https://www.tensorflow.org/lite/models/object_detection/overview). Thanks!

@amahendrakar the link u shared doesn't correspond to the questions. currently, TensorFlow demo object detection app uses Camera2 API to get a frame from the app. Hence, he is asking if it's possible to use uvc libraries to get the frame fed into the object detection model.
