### ISSUE TITLE
Decouple RaggedStructure from RaggedTensor

### ISSUE THREAD

**Issue by jackd** [tensorflow/tensorflow#36293]
**System information**
- TensorFlow version (you are using): 2
- Are you willing to contribute it (Yes/No): Yes

**Describe the feature and the current behavior/state.**
I've been doing a lot of work with `RaggedTensor`s since their introduction, and one thing that irks me is that a lot of the methods (`row_lengths`, `row_starts`, `value_rowids` etc) work entirely on their row structure, and independently of the values. The memoization features of the `RaggedTensor` class is very convenient, but those memoized values aren't shared between `RaggedTensor`s that share the same row structure but have different values. As an example

```python
x = tf.RaggedTensor.from_row_splits(tf.range(5), [0, 2, 5])
y = 2 * x
print(x.row_splits is y.row_splits)              # True
print(x.row_lengths() is y.row_lengths())  # False
```
A separate `RaggedStructure` class which handles memoization has two main benefits:

1. Easier memoization across different `RaggedTensor`s
2. Simpler interface to structure manipulation functions without `value`s

**Will this change the current api? How?**
This could be done with no changes to the current API. However, minimal changes - like changing the existing `tf.RaggedTensor.__init__` method, which isn't meant to be used externally anyway - might make things simpler, and exposing a new property (`ragged_structure`) would be helpful in many cases. I would suggest something like the following.

```python
class RaggedTensor(CompositeTensor):
  # changed constructor, publicly usable.
  def __init__(self, values, ragged_structure):
    self._values = values
    self._ragged_structure = ragged_structure
    # error checks
    ...

  # added property
  @property
  def ragged_structure(self):
    return self._ragged_structure 
  
  # redirect row_lengths, row_starts, value_rowids etc. to structure
  def row_lengths(self):
    return self.ragged_structure.row_lengths()

  def with_values(self, values):
    return RaggedTensor(values, self.ragged_structure)

# new class
class RaggedStructure(CompositeTensor):
  def __init__(self, row_splits, cached_row_lengths=None, cached_value_rowids=None, cached_nrows=None, internal=False):
    # most of current tf.RaggedTensor.__init__
    ...

  @classmethod
  def from_row_lengths(cls, row_lengths):
    # most of current tf.RaggedTensor.from_row_lengths
    ...

  # cache here
  def row_lengths(self, row_lengths):
    if self._cached_row_lengths is None:
      ...
    return self._cached_row_lengths
```

**Comment by jackd** [comment]
@edloper thoughts? Happy to contribute PR if it's something that would be considered.

**Comment by jackd** [comment]
Having investigated the existing `RaggedTensor` implementation further I've realized the only caching that occurs is when cached values are calculated in the factory constructor. Is there any particular reason for that?

**Comment by edloper** [comment]
1. We are currently working on doing something very similar to what you suggest, motivated by the fact that row partitioning needs to be shared in StructuredTensors.  In particular, we're adding a `RowPartitioning` class that wraps the `row_splits`, `row_lengths`, etc. tensors together.

2. We tried to add lazy caching of the alternative row-partitioning tensors, but had to roll it back because it breaks some assumptions made by tf.cond.  Here's [a test](https://github.com/tensorflow/tensorflow/commit/479e54cb5c7b3581ee871fe66bbed13e0c93f886) we added that fails if we cache the row_lengths lazily.

**Comment by jackd** [comment]
Oo, I like `RowPartitioning` as a name better (though is the noun not `RowPartition`? Now that I think about it, does it have anything to do with rows? Isn't it just a `Partition`? Maybe that's too abstract...). Does that mean TF is looking at other sparse formats (CSR / CSC)?

I'm happy to close this issue if there's work being done on it - but is there any way to track progress on that? Rename this issue and use it that way?

**Comment by rmothukuru** [comment]
@jackd,
**`Row Partitioning`** seems to be implemented for [Ragged Tensors](https://www.tensorflow.org/guide/ragged_tensor). Can you please refer the [Documentation Guide](https://www.tensorflow.org/guide/ragged_tensor), [API Documentation](https://www.tensorflow.org/api_docs/python/tf/RaggedTensor) for **`Ragged Tensors`** and the [Documentation of tf.io.RaggedFeature](https://www.tensorflow.org/api_docs/python/tf/io/RaggedFeature?authuser=3&skip_cache=true&hl=ko) and let us know if your **`feature`** has been implemented? Thanks!

**Comment by jackd** [comment]
Not remotely - yes, it's implemented in ragged tensors, but this issue is about decoupling that implementation from everything else in ragged tensors. I've moved over to [jax](https://github.com/google/jax) so not bothered.
