### ISSUE TITLE
TensorRT native segment lookup error in calibration mode

### ISSUE THREAD

**Issue by tfeher** [tensorflow/tensorflow#36304]
**System information**
- Have I written custom code: yes
- OS Platform and Distribution: Linux Ubuntu 18.04 (docker)
- TensorFlow installed from source
- TensorFlow version: 2.1.0 
- Python version: 3.6.9
- Bazel version: 1.2.1
- GCC/Compiler version : 7.4.0
- CUDA/cuDNN version: 10.2 / 7.6.5
- TensorRT version 7.0
- GPU model and memory: NVIDIA TESLA V100-SXM2-16GB

**Describe the current behavior**

Under specific conditions, there is an error with the native segment lookup for TRTEngineOp. It can happen that we load a native segment that belongs to another graph. In most cases this leads to an error (when the input data is not comptible with the foreign native segment). In an unlucky case, when the input data is compatible, then we have incorrect results.

**Background**

TRTEngineOp falls back to execute the native TensorFlow segment in certain cases:
- there is an error in creating the engine, or with its input data
- during calibration https://github.com/tensorflow/tensorflow/blob/e72c2e601aac87faade051d5ca234a2a9b301b2a/tensorflow/compiler/tf2tensorrt/kernels/trt_engine_op.cc#L381
- during optimization profile creation [PR #36080] https://github.com/pooyadavoodi/tensorflow/blob/3ae92a3d220a8d84f2d7885423254aabae6bb99d/tensorflow/compiler/tf2tensorrt/kernels/trt_engine_op.cc#L535

The error can occur in the last two case. 

The native segment is added to the graph here https://github.com/tensorflow/tensorflow/blob/e72c2e601aac87faade051d5ca234a2a9b301b2a/tensorflow/compiler/tf2tensorrt/convert/convert_graph.cc#L530-L552
and later it is looked up using its name in https://github.com/tensorflow/tensorflow/blob/e72c2e601aac87faade051d5ca234a2a9b301b2a/tensorflow/compiler/tf2tensorrt/kernels/trt_engine_op.cc#L247
For example, in each converted graph TRTEnginoOp_0 has a corresponding native segment TRTEngineOp_0_native_segment.

**Describe the expected behavior**

The expected behavior is to load the correct native segment, the one which corresponds to the TRTEngineOp being executed.

During normal execution the graph of the previous test should be garbage collected, so it cannot happen that we load an incorrect native segment.

We suspect that manipulating the graph during calibration (or build mode) introduces a circular reference that cause the garbage collector to not delete the graph. It is still not clear how does this native segment appear in subsequent tests' graph. The graph is owned by the converter, therefore each test is supposed to have a separate graph.

**Code to reproduce the issue**
To reproduce this error, we need to use either
- calibration (in the current master branch) https://github.com/tensorflow/tensorflow/blob/4152ed672ee107fc52f815443bc4601999f42ded/tensorflow/python/compiler/tensorrt/trt_convert.py#L1067-L1087 or
- build mode with profiles (as proposed in PR #36080) https://github.com/pooyadavoodi/tensorflow/blob/3ae92a3d220a8d84f2d7885423254aabae6bb99d/tensorflow/python/compiler/tensorrt/trt_convert.py#L1102-L1168

The problem is illustrated in the branch https://github.com/tfeher/tensorflow/tree/native_segment_bug This branch extends the test coverage of tf_trt_integration tests by [enabling calibration test](https://github.com/tfeher/tensorflow/commit/3c0d9e8da189bc8dc4e3020204e3080f5fa0d227) in V2 mode. The calibration needs to execute the native segment. 

A simple test file is prepared to reproduce the problem:
https://github.com/tfeher/tensorflow/blob/native_segment_bug/tensorflow/python/compiler/tensorrt/test/native_segment_test.py

The test file defines two tests: AddTest and MulTest, the first one takes one tensor as input, the second takes two tensors. If we call the tests individually, then they work:
```
python tensorflow/python/compiler/tensorrt/test/native_segment_test.py AddTest # works
python tensorflow/python/compiler/tensorrt/test/native_segment_test.py MulTest # works
```
When we try to execute both test then it fails:
```
python tensorflow/python/compiler/tensorrt/test/native_segment_test.py
...
ERROR: testTfTrtV2_OfflineConversion_DynamicEngine_INT8_UseCalibration (__main__.MulTest)
testTfTrtV2_OfflineConversion_DynamicEngine_INT8_UseCalibration (__main__.MulTest)
...
tensorflow.python.framework.errors_impl.InvalidArgumentError:  Expects 1 arguments, but 2 is provided
         [[node TRTEngineOp_0 (defined at /usr/lib/python3.6/unittest/case.py:605) ]] [Op:__inference_pruned_2770]
```
The `InvalidArgumentError` apperas, because AddTest's native segment was loaded instead of MulTest's native segment. This can be confirmed if we add a printout 
`VLOG(2) << SummarizeGraphDef(segment_graph_def_)` to TRTEngineOp's constructor.

The error can manifest different ways (but it is always caused by executing the native segment of a different graph):
- Segfault
- Out or range error
- Mismatched value if the foreign native segment is compatible with the input data. An example for that: https://github.com/tfeher/tensorflow/blob/native_segment_bug/tensorflow/python/compiler/tensorrt/test/native_segment_test2.py
- error due to incorrect data type

Tagging @pooyadavoodi @bixia1 and @aaroey

**Comment by bixia1** [comment]
Are you sure that https://github.com/tfeher/tensorflow/blob/native_segment_bug/tensorflow/python/compiler/tensorrt/test/native_segment_test2.py can be used to reproduce the problem?

If that is the case, I expect that removing AddTest from the file the test should pass. 

But I got this error:
ValueError: Fetch argument 'output_0:0' cannot be interpreted as a Tensor. ("The name 'output_0:0' refers to a Tensor which does not exist. The operation, 'output_0', does not exist in the graph.")

I think this is because the test has a problem, in GraphFn.  I fixed GraphDef as follows, and added AddTest back, the test pass.
  def GraphFn(self, inp1):
    """Create a graph containing single segment."""
    dtype = inp1.dtype
    val = inp1 * inp1
    abs = math_ops.abs(val)
    return array_ops.identity(abs, name="output_0")

**Comment by tfeher** [comment]
Thanks @bixia1 for looking into the problem!

I have not seen the output_0 error, I think I was disabling v1 test, where the output name is used. Thanks for catching this. As you have suggested I have [updated the native segments test](https://github.com/tfeher/tensorflow/commit/167007c77ea63b39da1a2913e32731130205fe9e).

I have also added the [printout statement for segment_graph_def](https://github.com/tfeher/tensorflow/commit/8c54af06fcd3d352263c4a397880c5f097e7a0fa) to the TRTEngineOp. Additionally I have[ disabled](https://github.com/tfeher/tensorflow/commit/9d0ff1740ca40a88ed3d8c00d496933d04050e52) all the non relevant tests.

After these modifications, the tests run succesfully if I invoke them using bazel:
```
bazel test --test_env=TF_CPP_VMODULE=trt_engine_op=2,convert_graph=7 -c opt --config=cuda --cxxopt="-D_GLIBCXX_USE_CXX11_ABI=0" --noincompatible_do_not_split_linking_cmdline --local_test_jobs=1 //tensorflow/python/compiler/tensorrt:native_segment_test
```

But if I call the python test directly, I still receive the same errors that I describe above. Here is how to run the tests with debug printouts enabled:

`TF_CPP_VMODULE=trt_engine_op=2,convert_graph=7 python tensorflow/python/compiler/tensorrt/test/native_segment_test2.py`

The relevant lines which from the output:
```
[ RUN      ] MulTest.testTfTrtV2_OfflineConversion_DynamicEngine_INT8_UseCalibration
....
2020-01-30 12:22:46.623723: I tensorflow/compiler/tf2tensorrt/convert/convert_graph.cc:638] Number of TensorRT candidate segments: 1
2020-01-30 12:22:46.623778: I tensorflow/compiler/tf2tensorrt/convert/convert_graph.cc:137] Node Func/PartitionedCall/input/_0 neither have requested device nor assigned device
2020-01-30 12:22:46.623818: I tensorflow/compiler/tf2tensorrt/convert/convert_graph.cc:200] Input edge = input_0:0
2020-01-30 12:22:46.623826: I tensorflow/compiler/tf2tensorrt/convert/convert_graph.cc:137] Node PartitionedCall/mul neither have requested device nor assigned device
2020-01-30 12:22:46.623848: I tensorflow/compiler/tf2tensorrt/convert/convert_graph.cc:137] Node PartitionedCall/Abs neither have requested device nor assigned device
2020-01-30 12:22:46.623854: I tensorflow/compiler/tf2tensorrt/convert/convert_graph.cc:137] Node PartitionedCall/output_0 neither have requested device nor assigned device
2020-01-30 12:22:46.623877: I tensorflow/compiler/tf2tensorrt/convert/convert_graph.cc:137] Node PartitionedCall/Identity neither have requested device nor assigned device
2020-01-30 12:22:46.623883: I tensorflow/compiler/tf2tensorrt/convert/convert_graph.cc:137] Node Func/PartitionedCall/output/_1 neither have requested device nor assigned device
2020-01-30 12:22:46.623929: I tensorflow/compiler/tf2tensorrt/convert/convert_graph.cc:232] Output edge = Func/PartitionedCall/output/_1:0
2020-01-30 12:22:46.623980: I tensorflow/compiler/tf2tensorrt/convert/convert_graph.cc:254] Converted TensorRT candidate segment 'TRTEngineOp_0' to a GraphDef
2020-01-30 12:22:46.623992: I tensorflow/compiler/tf2tensorrt/convert/convert_graph.cc:97] Found TF GPU 0 at cuda device 0
2020-01-30 12:22:46.624118: I tensorflow/compiler/tf2tensorrt/convert/convert_graph.cc:545] TRTEngineOp_0 Function_Def 
2020-01-30 12:22:46.624531: I tensorflow/compiler/tf2tensorrt/convert/convert_graph.cc:546] signature {
  name: "TRTEngineOp_0_native_segment"
  input_arg {
    name: "tensorrtinputph_0"
    type: DT_FLOAT
  }
  output_arg {
    name: "tensorrtoutputph_0"
    type: DT_FLOAT
  }
}
node_def {
  name: "Func/PartitionedCall/input/_0"
  op: "Identity"
  input: "tensorrtinputph_0"
  attr {
    key: "T"
    value {
      type: DT_FLOAT
    }
  }
  experimental_debug_info {
    original_node_names: "Func/PartitionedCall/input/_0"
  }
}
node_def {
  name: "PartitionedCall/mul"
  op: "Mul"
  input: "Func/PartitionedCall/input/_0:output:0"
  input: "Func/PartitionedCall/input/_0:output:0"
  attr {
    key: "T"
    value {
      type: DT_FLOAT
    }
  }
  experimental_debug_info {
    original_node_names: "PartitionedCall/mul"
  }
}
...

2020-01-30 12:22:46.624634: I tensorflow/compiler/tf2tensorrt/convert/convert_graph.cc:548] Adding funcdef TRTEngineOp_0_native_segment to graphlib
...

2020-01-30 12:22:46.641959: I tensorflow/compiler/tf2tensorrt/kernels/trt_engine_op.cc:284] versions = producer: 175;
{{node TensorRTInputPH_0}} = _Arg[T=DT_FLOAT, index=0]();
{{node Func/PartitionedCall/input/_0}} = Identity[T=DT_FLOAT](TensorRTInputPH_0);
{{node PartitionedCall/add}} = AddV2[T=DT_FLOAT](Func/PartitionedCall/input/_0, Func/PartitionedCall/input/_0);
{{node PartitionedCall/Abs}} = Abs[T=DT_FLOAT](PartitionedCall/add);
{{node PartitionedCall/output_0}} = Identity[T=DT_FLOAT](PartitionedCall/Abs);
{{node PartitionedCall/Identity}} = Identity[T=DT_FLOAT](PartitionedCall/output_0);
{{node Func/PartitionedCall/output/_1}} = Identity[T=DT_FLOAT](PartitionedCall/Identity);
{{node TensorRTOutputPH_0}} = _Retval[T=DT_FLOAT, index=0](Func/PartitionedCall/output/_1);
...
FAIL: testTfTrtV2_OfflineConversion_DynamicEngine_INT8_UseCalibration (__main__.MulTest)
testTfTrtV2_OfflineConversion_DynamicEngine_INT8_UseCalibration (__main__.MulTest)
...
AssertionError: 
Not equal to tolerance rtol=0.01, atol=0.01
Mismatched value: a is different from b. 
not close where = (array([0]), array([0]), array([0]), array([0]))
not close lhs = [0.8641861]
not close rhs = [1.8592322]
not close dif = [0.9950461]
not close tol = [0.02859232]
dtype = float32, shape = (1, 1, 1, 1)
Mismatch: 100%
Max absolute difference: 0.9950461
Max relative difference: 0.53519195
 x: array([[[[0.864186]]]], dtype=float32)
 y: array([[[[1.859232]]]], dtype=float32)
```
Printouts from 'convert_graph.cc:137' show that the correct subgraph (with mul op) was converted. 
The log from line convert_graph.cc:546 shows that the correct native segment was added to the graph. While later, the message from trt_engine_op.cc:284 shows that the incorrect native segment (with add op) is loaded during calibration.

I would expect that the test would work even if I run it without bazel. Any idea why is it not the case?

**Comment by bixia1** [comment]
Can you tell me the detail on how you get the binary "python" as in "TF_CPP_VMODULE=trt_engine_op=2,convert_graph=7 python tensorflow/python/compiler/tensorrt/test/native_segment_test2.py"?

**Comment by tfeher** [comment]
I compiled tf inside our docker container `nvcr.io/nvidia/tensorflow:20.01-tf2-py3`, and I use the python binary from the container, if that answers your question.

**Comment by sushreebarsa** [comment]
@tfeher  Could you please try on latest stable version of tf 2.5 or 2.4.1 and let us know if this is still an issue.Thanks!
