### ISSUE TITLE
test that the full precision model runs on the CPU and GPU, but it takes 800ms to initialize on the GPU, but it only takes a few milliseconds to initialize on the CPU, how should I optimize

### ISSUE THREAD

**Issue by rzyangKyle** [tensorflow/tensorflow#36309]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using):
- Are you willing to contribute it (Yes/No):

**Describe the feature and the current behavior/state.**

**Will this change the current api? How?**

**Who will benefit with this feature?**

**Any Other info.**

**Comment by amahendrakar** [comment]
@rzyangKyle,
In order to expedite the trouble-shooting process, could you please provide the complete code to reproduce the issue reported here and also the TensorFlow version you are using. Thanks!

**Comment by rzyangKyle** [comment]
> @rzyangKyle,
> In order to expedite the trouble-shooting process, could you please provide the complete code to reproduce the issue reported here and also the TensorFlow version you are using. Thanks!

I use mobilenetv2 float model run cpu and gpu by benchmark, you can try it

**Comment by rzyangKyle** [comment]
> @rzyangKyle,
> In order to expedite the trouble-shooting process, could you please provide the complete code to reproduce the issue reported here and also the TensorFlow version you are using. Thanks!

tf2.0

**Comment by amahendrakar** [comment]
@rzyangKyle,
I have tried to reproduce the issue with [GPU](https://colab.sandbox.google.com/gist/amahendrakar/e7fb2047a9ad5aeadef9918461e07a14/36309_gpu.ipynb) and [CPU](https://colab.sandbox.google.com/gist/amahendrakar/d0a4bc51ea01c88ef9f5a3e650247f67/36309_cpu.ipynb) but could not find much difference in the initialization time. Could you please take a look at the Gist. Thanks!

**Comment by rzyangKyle** [comment]
> @rzyangKyle,
> I have tried to reproduce the issue with [GPU](https://colab.sandbox.google.com/gist/amahendrakar/e7fb2047a9ad5aeadef9918461e07a14/36309_gpu.ipynb) and [CPU](https://colab.sandbox.google.com/gist/amahendrakar/d0a4bc51ea01c88ef9f5a3e650247f67/36309_cpu.ipynb) but could not find much difference in the initialization time. Could you please take a look at the Gist. Thanks!

I use tflite version is 2.0.

**Comment by karimnosseir** [comment]
@rzyangKyle Can you share a sample code that shows the error using latest TF release or nightly

Thanks
