### ISSUE TITLE
Incorrect Error TypeError: padded_batch() missing 1 required positional argument: 'padded_shapes'

### ISSUE THREAD

**Issue by rakeshmothukuru1** [tensorflow/tensorflow#36308]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: Yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:  Error is not OS specific. Can be reproduced in Google Colab.
- **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device**: N/A
- **TensorFlow installed from (source or binary)**: N/A
- **TensorFlow version (use command below)**: %tensorflow_version 2.x
- **Python version**: 3.6
- **Bazel version (if compiling from source)**: N/A
- **GCC/Compiler version (if compiling from source)**: N/A
- **CUDA/cuDNN version**: N/A
- **GPU model and memory**: N/A
- **Exact command to reproduce**: Please find this [Github Gist](https://colab.research.google.com/gist/rmothukuru/505e7dfe61f9e236c8fc4b77e434b8aa/word_embeddings.ipynb#scrollTo=7SN5USFEIIK3)

### Describe the problem
As per the Source Code of [Padded_Batch](https://github.com/tensorflow/tensorflow/blob/c4ec9389364cb8d1bff451ab8baf55d25cabdd1f/tensorflow/python/data/ops/dataset_ops.py#L1375-L1379), only the Argument, `batch_size` is Mandatory and remaining arguments are Optional. But as per the code in [this Tutorial](https://www.tensorflow.org/tutorials/text/word_embeddings#learning_embeddings_from_scratch), if we don't pass the second argument, `padded_shapes = ([None],())` it is resulting in the below error,
`TypeError: padded_batch() missing 1 required positional argument: 'padded_shapes'`

Error Log: 
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-9-a8afa0f91afc> in <module>()
----> 1 train_batches = train_data.shuffle(1000).padded_batch(10)
      2 test_batches = test_data.shuffle(1000).padded_batch(10)
      3 
      4 #Error will be resolved if we uncomment below 3 lines and comment above 2 lines
      5 

TypeError: padded_batch() missing 1 required positional argument: 'padded_shapes'

**Expected Behavior:** Since the argument, `padded_shapes` is an Optional Argument, it shouldn't result in error even when we pass only the argument, `batch_size`

**Comment by ymodak** [comment]
`padded_batch` method requires two arguments. 
See   https://github.com/tensorflow/tensorflow/blob/cf7fcf164c9846502b21cebb7d3d5ccf6cb626e8/tensorflow/python/data/ops/dataset_ops.py#L1383
https://www.tensorflow.org/api_docs/python/tf/data/Dataset#padded_batch

**Comment by rakeshmothukuru1** [comment]
Ok.. I might have verified that in the previous version.

But the documentation in your 2nd Link, https://www.tensorflow.org/api_docs/python/tf/data/Dataset#padded_batch
Shows only 1 Mandatory Parameter, 

```
padded_batch(
    batch_size,
    padded_shapes=None,
    padding_values=None,
    drop_remainder=False
)
```

**Comment by ymodak** [comment]
![image](https://user-images.githubusercontent.com/42785357/73479052-0cd3bd00-434c-11ea-84d5-fc7b77c2b7be.png)
![image](https://user-images.githubusercontent.com/42785357/73479082-1a894280-434c-11ea-91c2-11d811096a6a.png)

**Comment by rakeshmothukuru1** [comment]
Got it Thanks!

**Comment by NielsRogge** [comment]
Got the same error. Can you please update the documentation of this [tutorial](https://www.tensorflow.org/tutorials/keras/text_classification). Weird thing is, this runs on TF 2.2, but not on 2.1 because of the additional required argument.

**Comment by Jarmos-san** [comment]
@NielsRogge the documentation of the [official tutorial](https://www.tensorflow.org/tutorials/keras/text_classification) you mentioned does specify to use the latest `nightly` version of TensorFlow, hence I don't think there's any need to update it.

![image](https://user-images.githubusercontent.com/31373860/77064051-bb1ee900-6a04-11ea-885a-69241f5930b4.png)

Anyone following the tutorial line-by-line, shouldn't come across that trivial `TypeError`.
