### ISSUE TITLE
installation of CUDA documentation

### ISSUE THREAD

**Issue by Jordy-VL** [tensorflow/tensorflow#36318]
Hi, 

Two important lines are missing from the suggested CUDA >=10 installation scripts: 

```
sudo add-apt-repository ppa:graphics-drivers/ppa
sudo add-apt-repository "deb http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64/ /"
```

**Comment by ravikyram** [comment]
@Jordy-VL 

Please, follow the below steps to install CUDA 10. Thanks!

wget https://developer.nvidia.com/compute/cuda/10.0/Prod/local_installers/cuda-repo-ubuntu1804-10-0-local-10.0.130-410.48_1.0-1_amd64

sudo dpkg -i cuda-repo-ubuntu1804-10-0-local-10.0.130-410.48_1.0-1_amd64
sudo apt-key add /var/cuda-repo-<version>/7fa2af80.pub
sudo apt-get update
sudo apt-get install cuda

**Comment by ashutosh1919** [comment]
@Jordy-VL , Please take a look at [this documentation](https://github.com/ashutosh1919/FaceGenerationStyleGAN/blob/master/CUDA_INSTALLATION_INSTRUCTIONS.md). Hope it helps.

**Comment by ravikyram** [comment]
@Jordy-VL 

Any update on this issue please. Thanks!

**Comment by Jordy-VL** [comment]
Hi, 
I was succesful in installing CUDA. I was more referring to the buggy installation instructions on https://www.tensorflow.org/install/gpu#install_cuda_with_apt. 
These should be updated to account for adding the apt source explicitly, otherwise the package will not be updated when running "apt-get update".
