### ISSUE TITLE
OpenBLASS for efficient Matrix multiplications?

### ISSUE THREAD

**Issue by vikramdattu** [tensorflow/tensorflow#36329]
**System information**
- TensorFlow version (you are using): TFLite micro (on ESP32)
- Are you willing to contribute it (Yes/No): Yes

**Describe the feature and the current behaviour/state.**

The major CPU intensive function here are Convolution functions! Which are nothing but Large Matrix multiplications.
For Face detection example on ESP32, I have seen that it is the major contributor at more than 50% of total CPU eaten by example.

[OpenBLASS](https://github.com/xianyi/OpenBLAS) is open implementation of [BLASS](http://www.netlib.org/blas/) library which is optimised version of large Matrix multiplications which takes into account Cache availability of system etc.

Are there any plans to use this in TensorFlow?

**Will this change the current api? How?**

Need to explore this, but it should most likely not affect existing APIs but shall change the implementations of few functions.

**Who will benefit with this feature?**

All the platforms for which OpenBLASS is optimized to including x86 platforms, ARM, MIPS etc.

**Any Other info.**

Links:
http://www.netlib.org/blas/
https://github.com/xianyi/OpenBLAS

**Comment by wangtz** [comment]
Hi Vikram,

Adding optimization path to TFLM is more than welcomed! I'm not familiar with OpenBLASS myself, a few questions:

- Does it requires dynamic memory allocation?
- What's the size for  statically linked library?
- What are the hardware supported by OpenBLASS? I guess ESP32?

Thanks,

**Comment by kitepro** [comment]
Doesnt tensorflow already uses BLAS for dot products?

**Comment by rmothukuru** [comment]
@vikramdattu,
Sorry for the delayed response. Currently, most of the operations are handled by [cuDNN, cuBLAS, cuFFT, etc..](https://github.com/tensorflow/tensorflow/search?l=Markdown&q=cublas). Can you please let us know how **`OpenBLASS`** is efficient over them? Thanks!

**Comment by vikramdattu** [comment]
I think it's okay to close the issue.
Code already is using some neat tricks, especially platform specific optimizations.
