### ISSUE TITLE
This part of code on `self.save_weights_only` is not necessary

### ISSUE THREAD

**Issue by Ordgod** [tensorflow/tensorflow#36323]
In [tensorflow/tensorflow/python/keras/callbacks.py ](https://github.com/tensorflow/tensorflow/blob/r2.1/tensorflow/python/keras/callbacks.py#L813-L1166), this part of code on `self.save_weights_only` is not necessary:
```
    # Use name matching rather than `isinstance` to avoid circular dependencies.
    if (not self.save_weights_only and
        not model._is_graph_network and  # pylint: disable=protected-access
        model.__class__.__name__ != 'Sequential'):
      self.save_weights_only = True
```
Because when the argument `save_weights_only` is `True`, no matter what the model._is_graph_network is and no matter what model.__class__.__name__ is 'Sequential' or not,  `self.save_weights_only` will always be `True`.

I am not sure if I am right. So, if you disagree with me, please explain it detaily.

**Comment by rmothukuru** [comment]
@Ordgod,
Code says even though `save_weights_only = False`, but if `model._is_graph_network = False` and if it `not a Sequential Model`, then **only Weights will be Saved**.

If I understand the Code and your explanation correctly, Code demonstrates the Case of  `save_weights_only = False` and your explanation is about `save_weights_only = True`. 

Please correct me if I am wrong. Thanks!

**Comment by rmothukuru** [comment]
@Ordgod,
Can you please respond to the above comment. Thanks!

**Comment by rmothukuru** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
