### ISSUE TITLE
 How to replace a layer of a compiled Keras' model 

### ISSUE THREAD

**Issue by JoaoLages** [tensorflow/tensorflow#36320]
I'm in tensorflow 1.14
How can I replace a layer in a Keras model? My new layer has a different output size so set_weights doesn't work.

**Comment by Saduf2019** [comment]
@JoaoLages  Please provide details about what platform you are using (operating system, architecture) Also, did you compile from source or install a binary?

Make sure you also include the exact command[code] if possible to produce the output included in your test case. If you are unclear what to include see the issue template displayed in [the Github new issue template](https://github.com/tensorflow/tensorflow/issues/new/choose).

We ask for this in the issue submission template, because it is really difficult to help without that information. Thanks!

**Comment by JoaoLages** [comment]
I'm running it on Ubuntu 18.04.1 LTS. Just regularly intalled with `pip  install tensorflow==1.14`

What I am doing now is:
```
aux_trainable.load_weights(pretrained_weights_path)

        assert len(aux_model.get_weights()) == len(self.model.get_weights()), \
            "unexpected different number of layers between new model and pretrained model"

        new_weights = [
            x if x.shape == y.shape else y  # change every weight besides the output layer, which has a different shape
            for x, y in zip(aux_model.get_weights(), self.model.get_weights())
        ]
        self.model.set_weights(new_weights)
```

**Comment by Saduf2019** [comment]
@JoaoLages code provided is not sufficient to replicate the issue faced by you, please provide complete code so we could help you.

**Comment by JoaoLages** [comment]
`from keras.models import Sequential
from keras.layers import Dense, Activation

model = Sequential([
    Dense(32, input_shape=(784,)),
    Activation('relu'),
    Dense(10),
    Activation('softmax'),
])
model.save_weights('weights.hdf5')
new_model = Sequential([
    Dense(32, input_shape=(784,)),
    Activation('relu'),
    Dense(5),
    Activation('softmax'),
])
new_model.load_weights('weights.hdf5')
`

This yields an error: `ValueError: Dimension 1 in both shapes must be equal, but are 5 and 10. Shapes are [32,5] and [32,10]. for 'Assign_2' (op: 'Assign') with input shapes: [32,5], [32,10].`

It could easily just load the weights that had the same shape. **I know** that an alternative would be to name all the layers the same, besides the last one. But it isnt in my case

**Comment by gowthamkpr** [comment]
I think this [issue](https://stackoverflow.com/questions/43714713/modify-keras-model-after-training) would be very helpful in your case.

You can first add a layer and save the weights of all the layers using the code below
`temp_weights = [layer.get_weights() for layer in model.layers]` and then load the individual layer weights into your model and train it again.

**Comment by JoaoLages** [comment]
@gowthamkpr exactly. but that's the problem. I need to load the weights one by one and match them. very unpractical when I could just load the weights and disregard the ones that dont match in length (same as we disregard with different names)

**Comment by gowthamkpr** [comment]
@JoaoLages This is the default behavior of tensorflow.

**Comment by jvishnuvardhan** [comment]
@JoaoLages I think for your use-case, the only way to achieve what you want is by 

`new_model.load_weights('weights.hdf5', skip_mismatch=True, by_name=True)`

Please take a look at the gist [here](https://colab.research.google.com/gist/jvishnuvardhan/8361406a71273b4c703d16b727180f55/untitled.ipynb). Good thing with this approach is it is clearly warns the user which layers have mismatch as shown below.

> WARNING:tensorflow:Skipping loading of weights for layer Dense2 due to mismatch in shape ((32, 5) vs (32, 10)).
> WARNING:tensorflow:Skipping loading of weights for layer Dense2 due to mismatch in shape ((5,) vs (10,)).


Please note that if we load weights even when there is a mismatch, it could adversely affect other TF users. Thanks!

**Comment by jvishnuvardhan** [comment]
Closing this as this issue was resolved with the above comment. Please feel free to reopen if I am mistaken. Thanks!
