### ISSUE TITLE
Not finding cuda library for jobs that do NOT require GPU

### ISSUE THREAD

**Issue by brando90** [tensorflow/tensorflow#3632]
I am having this error when I use the slurm (http://slurm.schedmd.com/) workload manager. When I run some tensorflow python scripts, sometimes it results in an error (attached). It seems that it can't find cuda library installed but I am running scripts that do **not** require GPUs.  Therefore, I find it very confusing why cuda would be an issue at all. Why is cuda installation an issue if I don't need it?

----

Operating System:   CentOS Linux release 7.2.1511

Installed version of CUDA and cuDNN (calling ls -l /usr/lib/libcuda.so.352.63): 
-rwxr-xr-x 1 root root 14272428 Dec 15  2015 /usr/lib/libcuda.so.352.63

If installed from binary pip package, provide:
tensorflow (0.9.0)

2. The output from `python -c "import tensorflow; print(tensorflow.__version__)"`. running this seems to produce different results from the error I expected. what it outputs:
```
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:102] Couldn't open CUDA library libcudnn.so. LD_LIBRARY_PATH: /cm/shared/openmind/cuda/7.5/lib64:/cm/shared/openmind/cuda/7.5/lib
I tensorflow/stream_executor/cuda/cuda_dnn.cc:2092] Unable to load cuDNN DSO
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcuda.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcurand.so locally
````
 the error I expected:

```
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:102] Couldn't open CUDA library libcudnn.so. LD_LIBRARY_PATH: /cm/shared/openmind/cuda/7.5/lib64:/cm/shared/openmind/cuda/7.5/lib
I tensorflow/stream_executor/cuda/cuda_dnn.cc:2092] Unable to load cuDNN DSO
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcuda.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcurand.so locally
E tensorflow/stream_executor/cuda/cuda_driver.cc:491] failed call to cuInit: CUDA_ERROR_NO_DEVICE
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:153] retrieving CUDA diagnostic information for host: node047
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:160] hostname: node047
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:185] libcuda reported version is: Not found: was unable to find libcuda.so DSO loaded into this program
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:347] driver version file contents: """NVRM version: NVIDIA UNIX x86_64 Kernel Module  352.63  Sat Nov  7 21:25:42 PST 2015
GCC version:  gcc version 4.8.5 20150623 (Red Hat 4.8.5-4) (GCC)
"""
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:189] kernel reported version is: 352.63.0
I tensorflow/core/common_runtime/gpu/gpu_init.cc:81] No GPU devices available on machine.
```

### Steps to reproduce
1. run the sbatch command in slurm and dispatch about 1000 jobs running an idential tensorflow script. Returns that error.

### What have you tried?
1. I've tried logging into the node directly throwing the error and run tensorflow jobs but it seems when I do that there are no errors.

### Logs or other output that would be helpful
(If logs are large, please upload as attachment).

```
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:102] Couldn't open CUDA library libcudnn.so. LD_LIBRARY_PATH: /cm/shared/openmind/cuda/7.5/lib64:/cm/shared/openmind/cuda/7.5/lib
I tensorflow/stream_executor/cuda/cuda_dnn.cc:2092] Unable to load cuDNN DSO
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcuda.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcurand.so locally
E tensorflow/stream_executor/cuda/cuda_driver.cc:491] failed call to cuInit: CUDA_ERROR_NO_DEVICE
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:153] retrieving CUDA diagnostic information for host: node047
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:160] hostname: node047
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:185] libcuda reported version is: Not found: was unable to find libcuda.so DSO loaded into this program
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:347] driver version file contents: """NVRM version: NVIDIA UNIX x86_64 Kernel Module  352.63  Sat Nov  7 21:25:42 PST 2015
GCC version:  gcc version 4.8.5 20150623 (Red Hat 4.8.5-4) (GCC)
"""
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:189] kernel reported version is: 352.63.0
I tensorflow/core/common_runtime/gpu/gpu_init.cc:81] No GPU devices available on machine.
```

**Comment by yaroslavvb** [comment]
TensorFlow has separate builds for CPU and GPU binaries (http://ci.tensorflow.org/view/Nightly/) You seem to be running a GPU build on a machine that has no GPUs, hence the warning. However, it should still work regardless, this message is purely informational.

**Comment by brando90** [comment]
@yaroslavvb however, the observed behavior is that the job just stalls and does not move on. Is there some way to go around this? I never requested it to run on GPUs in the first place so its confusing that its doing this.

**Comment by yaroslavvb** [comment]
Job stalling is unrelated to the message. GPU initialization happens when TensorFlow library is loaded, regardless of whether you actually need GPU or not.

**Comment by brando90** [comment]
I also made a stackoverflow question for it: http://stackoverflow.com/questions/38727375/why-do-jobs-in-slurm-freeze-indefinitely-when-they-are-tensorflow-scripts and currently put a bounty of 100 on it. 

I'd love to be able to solve this and why its stalling. Not sure if its tensorflow or the computers/nodes themselves.

**Comment by brando90** [comment]
Just to add more information to the discussion, in slurm one can explicitly say to assign jobs to nodes with GPU's. I've observed that the apparent "stalling" only happens when jobs are sent to machine that are suppose to be CPU only. 

If the machine is artificially restricted to only use CPU but tensorflow detects GPUs, can tensorflow accidentally get stuck?

**Comment by brando90** [comment]
Is there anything I can do to help get this resolved? Thanks! :)

**Comment by yaroslavvb** [comment]
@brando90 I've added some suggestions on the stackoverflow thread (remove queues, add session timeouts, use cpu-only binary, try to match env to reproduce locally, isolate exactly which line gets stuck). From the description it's not clear that there's anything wrong with tensorflow

**Comment by vrv** [comment]
It's possible there's a bug with the nvidia driver -- I've seen reports of people updating their driver and solving some issues like these.  In particular, TF shouldn't be doing anything with your GPUs after trying to initialize them if you never use them.  I'm going to close this for now unless there's more evidence that there's something in TF we're doing wrong (we can't really reproduce this, so you'd have to do some debugging to help us out, not sure what other help we can offer).

**Comment by brando90** [comment]
I was checkpointing my tensorflow models and once I stopped doing that the stalling issue stopped (for the moment). Not sure if that was it but it might be some way locking works with tensorflow interferes with slurm.
