### ISSUE TITLE
not supported in the pynq board from xilinx

### ISSUE THREAD

**Issue by vishwas1234567** [tensorflow/tensorflow#36338]
![image](https://user-images.githubusercontent.com/48592314/73463266-f9a00c00-43a2-11ea-80cf-628d6dbe1a69.png)

**Comment by gadagashwini** [comment]
@vishwas1234567, Follow the steps mentioned [here](https://www.tensorflow.org/lite/guide/python).`
 pip3 install https://dl.google.com/coral/python/tflite_runtime-2.1.0-cp35-cp35m-linux_aarch64.whl`.
Thanks!

**Comment by gadagashwini** [comment]
@vishwas1234567, Is this still an issue

**Comment by gadagashwini** [comment]
@vishwas1234567, Closing since it is resolved. Please feel free to open if still issue persists. Thanks
