### ISSUE TITLE
Keras Layer With Trainable=False Flag Creates Variables With Trainable=True

### ISSUE THREAD

**Issue by decodyng** [tensorflow/tensorflow#36349]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): 
System Version: macOS 10.15.2 (19C57)
Kernel Version: Darwin 19.2.0
- TensorFlow installed from (source or binary): binary (pip)
- TensorFlow version (use command below): v1.15.0-rc3-22-g590d6eef7e 1.15.0
- Python version: 3.7.0 

**Describe the current behavior**
When I create a Keras model using layerwise structure in tf.keras.Model, and set one or more of the layers to `trainable=False`, this results in a situation where the keras model believes those variables/parameters to be non-trainable (and reports them as such in `model.non_trainable_variables` and `model.summary`) but doesn't set the actual `trainable` flag on the created Tensorflow variables to be False. This can lead to unintuitive behavior if other systems are reasonably expecting `var_obj.trainable` to correspond with the model's actual trainable variables. 

**Describe the expected behavior**
When a layer is set to `trainable=False`, Tensorflow variables associated with that layer also have the trainable flag set to False 

**Code to reproduce the issue**
```import tensorflow as tf
inputs = tf.keras.layers.Input(shape=(10,))
hiddens = tf.keras.layers.Dense(15,  trainable=True, name="trainable_layer")(inputs)
output = tf.keras.layers.Dense(5, trainable=False, name="nontrainable_layer")(hiddens)
model = tf.keras.Model(inputs, output)
model.compile(optimizer='rmsprop', loss='categorical_crossentropy')
print(f"Model trainable variables: {model.trainable_variables}")
print(f"Model non-trainable variables: {model.non_trainable_variables}")
print(f"Trainable flags on model non-trainable variables: {[v.trainable for v in model.non_trainable_variables]}")
```

**Comment by Saduf2019** [comment]
@decodyng  Could you please confirm if the issue still persist in the nightly version [gist](https://colab.research.google.com/gist/Saduf2019/d9046bbe32eadb99b4319ee9d9c712aa/36349.ipynb) shared

**Comment by decodyng** [comment]
@Saduf2019 I'm not sure if you intended me to independently try to install and check for the bug on the nightly version, but in the linked notebook, it does appear that variables in the `non_trainable_variables` set are still having their `trainable` flag incorrectly set to True.
