### ISSUE TITLE
TypeError: '>' not supported between instances of 'Nonetype' and 'float'

### ISSUE THREAD

**Issue by Krishnarohith10** [tensorflow/tensorflow#36358]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**  
- OS Platform and Distribution: Windows 10 1909  
- TensorFlow version: 2.1.0  
- Python version: 3.6.10  
- CUDA/cuDNN version: 10.1/7.6.5  
- GPU model and memory: GTX 1660Ti 6GB/32GB  

        import tensorflow as tf
        ACCURACY_THRESHOLD = 0.95

        class myCallback(tf.keras.callbacks.Callback):
	    def on_epoch_end(self, epoch, logs={}):
	        if(logs.get('acc') > ACCURACY_THRESHOLD):
		    print("\nReached %2.2f%% accuracy, so stopping training!!" %(ACCURACY_THRESHOLD*100))
		    self.model.stop_training = True

        callbacks = myCallback()

        mnist = tf.keras.datasets.fashion_mnist
        (x_train, y_train),(x_test, y_test) = mnist.load_data()
        # Scale data
        x_train, x_test = x_train / 255.0, x_test / 255.0

        model = tf.keras.models.Sequential([
        tf.keras.layers.Flatten(input_shape=(28, 28)),
        tf.keras.layers.Dense(512, activation=tf.nn.relu),
        tf.keras.layers.Dense(10, activation=tf.nn.softmax)
        ])

        model.compile(optimizer='adam', \
				loss='sparse_categorical_crossentropy', \
				metrics=['accuracy'])

        model.fit(x_train, y_train, epochs=20, callbacks=[callbacks])  

when I ran this algorithm I got error saying this:

![1](https://user-images.githubusercontent.com/44919399/73509681-fbe78200-4405-11ea-9dde-c9fe07b1f9da.jpg)

Briefly it says that logs.get('acc') is Nonetype and 0.99 is float so, '>' this cannot compare. How to solve it?

**Comment by amahendrakar** [comment]
@Krishnarohith10,
Replace `if(logs.get('acc') > ACCURACY_THRESHOLD):` with `if(logs.get('accuracy') > ACCURACY_THRESHOLD):` in your code and it should work.

Was able to resolve the issue. Please find the Gist [here](https://colab.research.google.com/gist/amahendrakar/cc1d75ca9f89f5b910daef7846bcf068/36358.ipynb#scrollTo=1KcZMQr7fNZp&line=10&uniqifier=1).

**Comment by Krishnarohith10** [comment]
@amahendrakar 
Thank You. That Worked.

**Comment by syyam** [comment]
I am still getting this error "TypeError: '>' not supported between instances of 'NoneType' and 'float'"

**Comment by syyam** [comment]
> @amahendrakar
> Thank You. That Worked.



> I am still getting this error "TypeError: '>' not supported between instances of 'NoneType' and 'float'"

Never mind, using 'acc' worked for me. Maybe I am using an older version

**Comment by cnaseeb** [comment]
Make sure you are using acc instead of accuracy. And otherwise, at least be consistent. Check your version of the tensorflow and use the corresponding term accordingly. It worked for me in that way.

**Comment by theswanand** [comment]
`if(logs.get('acc') > ACCURACY_THRESHOLD)` worked for me

**Comment by psych0man** [comment]
Weird if(log.get('acc') > ACCURACY_THRESHOLD) worked for me too

**Comment by rchouhan170590** [comment]
if(logs.get('accuracy') > ACCURACY_THRESHOLD) work for me

**Comment by ashwinbalaji0811** [comment]
`if(logs.get('acc') > ACCURACY_THRESHOLD)` worked for me. very weird though

**Comment by tanzimJUCSE** [comment]
if(logs.get('acc') > ACCURACY_THRESHOLD) didn't work for me. What should i do?

**Comment by sanjnasiboo24** [comment]
if(logs.get('acc') > ACCURACY_THRESHOLD) didn't work for me. What should i do?

**Comment by prntcena** [comment]
mine was giving error for `log.get('accuracy')` but when I changes it to` logs.get('acc')`, it worked

**Comment by vishnunaiir** [comment]
This depends on what name you use to store your accuracy variable. IF its stored as 'acc' use log.get('acc') else if you stored accuracy to "accuracy" use log.get('accuracy').  If you stored on some other variable, use it so. 
Cheers m8

**Comment by amanmishra086** [comment]
mine was giving error for log.get('accuracy') but when I changes it to logs.get('acc'), it worked

**Comment by ankitgupta04** [comment]
if(logs.get('acc') or if(logs.get('accuracy') 
depend on what you stored     return history.epoch, history.history['acc'][-1]

**Comment by Geekgineer** [comment]
Below worked for ```tf 2.2.0```
```py
    class endCallback(tf.keras.callbacks.Callback):
        def on_epoch_end(self, epoch, logs={}):
            if(logs.get('acc')>0.998):
                print("\nReached 99.8% accuracy so cancelling training!")
                self.model.stop_training = True
```

**Comment by ricardopss** [comment]
I had the same problem... Just tried here: both 'acc' and 'accuracy' works... I depends on what metrics have you specified on the compile():

`
model.compile(loss='binary_crossentropy',
               optimizer='adam',
               metrics=['acc'])
`  
or 
`
model.compile(loss='binary_crossentropy',
               optimizer='adam',
               metrics=['accuracy'])
`

**Comment by rgdeekshith** [comment]
For Tensorflow version equal to `1.14`, `if(logs.get('acc') > ACCURACY_THRESHOLD)` is working. replacing `accuracy` with `acc` in version 1.14 was successful.

**Comment by jasman0209** [comment]
> I had the same problem... Just tried here: both 'acc' and 'accuracy' works... I depends on what metrics have you specified on the compile():
> 
> `model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['acc'])`
> or
> `model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])`

I dont think that depends on metrics,
I defined metrics['accuracy'] but logs.get('acc') worked for me.
I guess it has to be tried and tested for which one works

**Comment by fat-tire** [comment]
Yeah this seems to be a bug in google's Computer Visiion example at Computer vision example → [https://colab.research.google.com/github/lmoroney/mlday-tokyo/blob/master/Lab2-Computer-Vision.ipynb](https://colab.research.google.com/github/lmoroney/mlday-tokyo/blob/master/Lab2-Computer-Vision.ipynb)

**Comment by rgdeekshith** [comment]
> > I had the same problem... Just tried here: both 'acc' and 'accuracy' works... I depends on what metrics have you specified on the compile():
> > `model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['acc'])`
> > or
> > `model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])`
> 
> I dont think that depends on metrics,
> I defined metrics['accuracy'] but logs.get('acc') worked for me.
> I guess it has to be tried and tested for which one works

Even I thought like that and I tried many times and the only time I succeeded was putting `acc`. May be for higher versions, this might not occur!

**Comment by rgdeekshith** [comment]
> Yeah this seems to be a bug in google's Computer Vision example → https://colab.research.google.com/github/lmoroney/mlday-tokyo/blob/master/Lab2-Computer-Vision.ipynb

I haven't tried in colab, I used jupyter notebook!

**Comment by yonwu** [comment]
Hi, 

The call back should be coded in a line with model setting up with metrics. they should be the same, both 'acc' or both 'accuracy'.

model.compile(optimizer = RMSprop(lr=0.0001), 
              loss = 'binary_crossentropy',  
              metrics = ['**acc**'])  

class myCallback(tf.keras.callbacks.Callback):
    def on_epoch_end(self, epoch, logs={}):
        if(logs.get('**acc**')>0.97):
            print("\nReached 97.0% accuracy so cancelling training!")
            self.model.stop_training = True

**Comment by Yoshibansal** [comment]
Try using try-except:-

class myCallback(tf.keras.callbacks.Callback):
  def on_epoch_end(self, epoch, logs = {}):
    try:
      if(logs.get('acc')>ACCURACY_THRESHOLD):
        print("\nReached")
        self.model.stop_training = True
    except:
      if(logs.get('accuracy')>ACCURACY_THRESHOLD):
        print("Reached!!!")
        self.model.stop_training = True

**Comment by koushikroy** [comment]
I'm doing the coursera TensorFlow course. And one of it's Exercise this problem occurred. In my local machine I ran with 'accuracy' and it worked but in coursera jupyter notebook 'acc' worked.

**Comment by leena-bhooshan** [comment]
> _Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template_
> 
> **System information**
> 
> * OS Platform and Distribution: Windows 10 1909
> * TensorFlow version: 2.1.0
> * Python version: 3.6.10
> * CUDA/cuDNN version: 10.1/7.6.5
> * GPU model and memory: GTX 1660Ti 6GB/32GB
>   ```
>     import tensorflow as tf
>     ACCURACY_THRESHOLD = 0.95
>   
>     class myCallback(tf.keras.callbacks.Callback):
>     def on_epoch_end(self, epoch, logs={}):
>         if(logs.get('acc') > ACCURACY_THRESHOLD):
>         print("\nReached %2.2f%% accuracy, so stopping training!!" %(ACCURACY_THRESHOLD*100))
>         self.model.stop_training = True
>   
>     callbacks = myCallback()
>   
>     mnist = tf.keras.datasets.fashion_mnist
>     (x_train, y_train),(x_test, y_test) = mnist.load_data()
>     # Scale data
>     x_train, x_test = x_train / 255.0, x_test / 255.0
>   
>     model = tf.keras.models.Sequential([
>     tf.keras.layers.Flatten(input_shape=(28, 28)),
>     tf.keras.layers.Dense(512, activation=tf.nn.relu),
>     tf.keras.layers.Dense(10, activation=tf.nn.softmax)
>     ])
>   
>     model.compile(optimizer='adam', \
>     		loss='sparse_categorical_crossentropy', \
>     		metrics=['accuracy'])
>   
>     model.fit(x_train, y_train, epochs=20, callbacks=[callbacks])  
>   ```
> 
> when I ran this algorithm I got error saying this:
> 
> ![1](https://user-images.githubusercontent.com/44919399/73509681-fbe78200-4405-11ea-9dde-c9fe07b1f9da.jpg)
> 
> Briefly it says that logs.get('acc') is Nonetype and 0.99 is float so, '>' this cannot compare. How to solve it?

Just print logs by using:   print(logs) inside on_epoch_end() method and see whether accuracy is stored as "accuracy" or "acc". Then evaluate accuracy accordingly.

**Comment by leena-bhooshan** [comment]
This is due to versioning. Just print(logs) inside on_epoch_end() method, you will get to know which one to choose.

**Comment by vivamoto** [comment]
In Coursera "Introduction to TensorFlow for Artificial Intelligence, Machine Learning, and Deep Learning" course, use `logs.get('acc')` instead of `logs.get('accuracy')`, otherwise you'll get the error **Can't compile the student's code. '>' not supported between instances of 'NoneType' and 'float'**

Also, replace 'accuracy' by 'acc' in other parts of the code.

**Comment by EdenZhou051** [comment]
> mine was giving error for `log.get('accuracy')` but when I changes it to` logs.get('acc')`, it worked

Me too! Amazing...

**Comment by HariPrakash1996** [comment]
Yes it worked thank you

**Comment by vritansh** [comment]
If we print -> print(logs) we get an array showing the exact keys for my case it was as : 
{'loss': 0.25769969047009944, 'acc': 0.92646664} ,  
Both options worked for me as below: 
1. logs.get('acc') 
2. float(logs.get('acc'))

**Comment by Mohamed-Aziz-Ben-Nessir** [comment]
for me changing to 'acc' worked : if(logs.get('acc')>0.99)

**Comment by Rohan-0707** [comment]
def mysig(x):
    if x.MA20 < x.MA30 < x.MA60:
        return -1
    elif x.MA20 > x.MA30 > x.MA60:
        return +1
    else:
        return 0

----------------------------------------------------------------------------------------------------------------------------

    if x.MA20 < x.MA30 < x.MA60:
       ^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: '<' not supported between instances of 'float' and 'NoneType'
