### ISSUE TITLE
Different behavior tf.keras and Keras for `stateful=True` 

### ISSUE THREAD

**Issue by gerwin3** [tensorflow/tensorflow#36363]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): All platforms (tested on Ubuntu 18.04 and macOS)
- TensorFlow installed from (source or binary): pip
- TensorFlow version (use command below): 2.1
- Python version: 3.8

**Describe the current behavior**
The original Keras API specifies that, when an LSTM is set `stateful=True`, it's batch size *must* be known beforehand (by specifying `batch_shape`). The same is true for `tf.keras`, but it adds another hidden requirement that was not there in the original Keras: tf.keras requires that the full input shape (including batch size) is known. If one of the dimensions is `None`, it emits the "If a RNN is stateful, it needs to know its batch size." error.

**Describe the expected behavior**
As with the Keras API, it should be allowed to have `None` dimensions besides the `batch_size`.

**Code to reproduce the issue**
Keras:

```
from keras.models import Model
from keras.layers import Input, LSTM, Reshape

def model():
    input_layer = Input(batch_shape=(1, None))
    reshape_layer = Reshape((1, 100))(input_layer)
    lstm_layer = LSTM(units=100, stateful=True)(reshape_layer)
    return Model(inputs=input_layer, outputs=lstm_layer)

model = model()

# Code runs perfectly fine.
```

tf.keras:

```
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Input, LSTM, Reshape

def model():
    input_layer = Input(batch_shape=(1, None))
    reshape_layer = Reshape((1, 100))(input_layer)
    lstm_layer = LSTM(units=100, stateful=True)(reshape_layer)
    return Model(inputs=input_layer, outputs=lstm_layer)

model = model()

"""
ValueError: If a RNN is stateful, it needs to know its batch size. Specify the batch size of your input tensors: 
- If using a Sequential model, specify the batch size by passing a `batch_input_shape` argument to your first layer.
- If using the functional API, specify the batch size by passing a `batch_shape` argument to your Input layer.
"""

```

There are some very legitimate use cases for allowing non-batch dimensions to be unknown! This change in functionality prevents me from migrating a (variable) multi-stream CNN model from Keras to tf.kensor.

**Comment by amahendrakar** [comment]
Works as intended with [Keras](https://colab.sandbox.google.com/gist/amahendrakar/c4643b7f631003b9747ace2b26e417ee/36363_keras.ipynb), was able to reproduce the error with [tf.Keras](https://colab.sandbox.google.com/gist/amahendrakar/47bf7a1917dabc817d805b659090c3c6/36363_tf-keras.ipynb). Please find the attached Gist. Thanks!

**Comment by rushabh-v** [comment]
I want to take this up.
I'll be opening a PR soon I think.

**Comment by jvishnuvardhan** [comment]
@gerwin3 I think shape information is missing. As a result shape inference is not working and throwing this error. A workaround is to simply use `set_shape` as shown below.

```
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Input, LSTM, Reshape

def model():
    input_layer = Input(batch_shape=(1, None))
    reshape_layer = Reshape((1, 100))(input_layer)
    reshape_layer.set_shape((1,1,100))
    lstm_layer = LSTM(units=100, stateful=True)(reshape_layer)
    
    return Model(inputs=input_layer, outputs=lstm_layer)

model = model()
```

**Comment by jvishnuvardhan** [comment]
@gerwin3 Can you please check my last comment?  Thanks!

**Comment by gerwin3** [comment]
@jvishnuvardhan 

Your solution gets rid of the error message, but does not fix the underlying problem. Old Keras allowed for non-batch dimensions to be unknown (by setting them to `None`), even when using an RNN. The work-around you provided wouldn't really work if, for example, you have a variable dimension that can change in size depending on the input. (Or maybe it would if you were to invoke `set_shape` with each iteration?)

I'm not sure if that feature of Keras was actually documented, but the current implementation of `tf.keras` is definitely incompatible with the original behavior of Keras.

**Comment by qlzh727** [comment]
Thanks for reporting the issue. 

I think the root cause is from the reshape layer in the code provided. If you check the shape of the reshape layer output, it is (None, 1, 100), where the batch dim is None, and it cause the LSTM layer to fail the validation.

Please check the docstring of the reshape layer in https://www.tensorflow.org/api_docs/python/tf/keras/layers/Reshape

**Comment by qlzh727** [comment]
Btw, I don't think there is any change wrt to the reshape layer. The original keras docstring also gives the example where the batch dim is None. Could u print out the reshape_layer.shape for both example and see what's the value there?

**Comment by qlzh727** [comment]
Humm, I think somehow the input_shape got by the lstm layer in keras is [1, 1, 100], which is not same as the shape of the reshape layer output. It might be some subtle diff in the keras sequential model that cause this difference. I need to check more details.

**Comment by qlzh727** [comment]
I think the root cause is that we don't call layer.comput_output_shape anymore for the default model building, and only call it for dynamic model. This cause the result of the reshape layer to lose the static shape information (batch dim), and cause the LSTM layer to error out. 

Will send a fix very soon.

**Comment by q-55555** [comment]
@gerwin3

Does the commit 40218a7 "Set static shape information for reshape layer." fix the bug ? 
Because on my side, I still have the same problem you described after having integrated the fix.

**Comment by gerwin3** [comment]
The issue persists. I tested on `tf-nightly 2.2.0.dev20200418`.

**Comment by q-55555** [comment]
@gerwin3 ok, so it confirms the problem.

@tensorflow-copybara, @qlzh727, is the commit 40218a7 "Set static shape information for reshape layer." supposed to fix the issue ?

**Comment by qlzh727** [comment]
Sorry, the issue is not fixed yet since my change kept getting rollback because of internal breakages. I will try to submit the fix soon.

**Comment by q-55555** [comment]
Hi @qlzh727 
Do you know if you will have time to fix the issue soon ?
That would be really great ;-)

**Comment by qlzh727** [comment]
This should now be fixed.
