### ISSUE TITLE
tf.function using higher GPU memory than normal python function

### ISSUE THREAD

**Issue by abhigoyal2210** [tensorflow/tensorflow#36361]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 16.04.5
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.1.0
- Python version: (3, 5, 2, 'final', 0)
- CUDA/cuDNN version: 10.0
- GPU model and memory: Tesla V100-PCIE-16GB

**Describe the current behavior**
I am running a simple LSTM model inside a function decorated with tf.function but it's consuming much higher GPU memory (around 8700MB) as compared to a function which isn't decorated with tf.function (which consumes around 2600MB).

**Describe the expected behavior**
Both methods should consume similar amount of GPU memory.

**Code to reproduce the issue**
```
import sys
import tensorflow as tf
tf.debugging.set_log_device_placement(True)

#GPU growth code
gpus = tf.config.experimental.list_physical_devices('GPU')
if gpus:
  try:
    # Currently, memory growth needs to be the same across GPUs
    for gpu in gpus:
      tf.config.experimental.set_memory_growth(gpu, True)
    logical_gpus = tf.config.experimental.list_logical_devices('GPU')
    print(len(gpus), "Physical GPUs,", len(logical_gpus), "Logical GPUs")
  except RuntimeError as e:
    # Memory growth must be set before GPUs have been initialized
    print(e)

#---------------PARAMS------------
batch_size = 32
max_out_len = 200
num_hidden = 400
num_classes = 73
max_time_steps = 900
num_features = 240
#---------------------------------

class Model(tf.keras.Model):
    def __init__(self):
        super(Model, self).__init__()

        self.forward_cell = [
            tf.keras.layers.LSTMCell(num_hidden, kernel_initializer='glorot_uniform')]
        self.state = tf.keras.layers.RNN(self.forward_cell, time_major=False, return_sequences=True)
        self.dense = tf.keras.layers.Dense(num_classes, use_bias=True, kernel_initializer=tf.initializers.TruncatedNormal(mean=0, stddev=0.1))

    def call(self, inputs):
        x, seq_len = inputs
        mask = tf.sequence_mask(seq_len, maxlen=max_time_steps)
        state = self.state(inputs=x, mask=mask)
        logits = self.dense(state)
        return logits

x = tf.random.normal(shape=(2, batch_size, max_time_steps, num_features))
seq_len = tf.constant([[5]*batch_size,[7]*batch_size])
y_i = [tf.constant(sum([[[i,0],[i,1],[i,2]] for i in range(batch_size)], [])),tf.constant(sum([[[i,0],[i,2],[i,4]] for i in range(batch_size)], []))]
y_v = [tf.constant([1,2,4]*batch_size),tf.constant([5,1,2]*batch_size)]
v = [tf.constant([1,0]*(batch_size//2)),tf.constant([0,1]*(batch_size//2))]
def fn():
    for i in range(2):
        yield x[i], seq_len[i], y_i[i], y_v[i], v[i]

def loss(logits, s, yi, yv):
    y = tf.SparseTensor(yi, yv, tf.TensorShape([batch_size, max_out_len]))
    return tf.cast(tf.sparse.reduce_sum(y, axis=-1), tf.float32) - tf.reduce_sum(logits, axis=[-1, -2])


with tf.device('/cpu:0'):
    model = Model()
    model.build([(batch_size, max_time_steps, num_features), (batch_size,)])
    dataset = tf.data.Dataset.from_generator(fn, output_types=(tf.float32, tf.int32, tf.int64, tf.int32, tf.float32))

def run_eager(x, s, yi, yv, v):
    with tf.device('/gpu:0'):
        with tf.GradientTape() as tape:
            logits = model([x, s])
            losses = tf.reduce_sum(loss(logits, s, yi, yv))
        grads = tape.gradient(losses, model.trainable_variables)

    # ToDo: call optimizer.apply_gradients

    return losses

if len(sys.argv) > 1 and sys.argv[1] == 'func':
    run = tf.function(run_eager)
else:
    run = run_eager

with tf.device('/cpu:0'):
    it = iter(dataset)
    l = run(*next(it))

print(l)
```

**Comment by ravikyram** [comment]
@abhigoyal2210 
I have tried on colab with TF version 2.1 and i am not able to see GPU memory usage with and without decorating tf.function . Please find the gist [here](https://colab.research.google.com/gist/ravikyram/62470c7593576abb4ec738c53cc4a76d/untitled614.ipynb). Thanks!

**Comment by abhigoyal2210** [comment]
By the time !nvidia-smi runs on colab, the code is already executed completely. Below are screenshot of GPU usage monitored in parallel using nvtop (GPU ID: 0).

Without tf.function decoration:
<img width="827" alt="Screenshot 2020-01-31 at 4 00 47 PM" src="https://user-images.githubusercontent.com/53578184/73532745-57843080-4443-11ea-9bf9-bd1da3c82798.png">
<img width="822" alt="Screenshot 2020-01-31 at 4 00 59 PM" src="https://user-images.githubusercontent.com/53578184/73532750-5a7f2100-4443-11ea-8317-c55e99adddd6.png">

With tf.function decoration:
<img width="823" alt="Screenshot 2020-01-31 at 4 01 26 PM" src="https://user-images.githubusercontent.com/53578184/73532763-61a62f00-4443-11ea-942e-145fb1c58a7a.png">
<img width="823" alt="Screenshot 2020-01-31 at 4 01 36 PM" src="https://user-images.githubusercontent.com/53578184/73532766-62d75c00-4443-11ea-98e9-070fcbe64ab0.png">

**Comment by abhigoyal2210** [comment]
Even on collab, after you run the code, you can see occupied GPU memory. Below are the screenshots.

Without tf.function decoration (2445MiB):
<img width="722" alt="Screenshot 2020-01-31 at 4 13 31 PM" src="https://user-images.githubusercontent.com/53578184/73533423-c9a94500-4444-11ea-9ceb-55aa78ddffca.png">

With tf.function decoration (8589MiB):
<img width="706" alt="Screenshot 2020-01-31 at 4 12 51 PM" src="https://user-images.githubusercontent.com/53578184/73533440-db8ae800-4444-11ea-8eb8-acd5e900c2cb.png">

**Comment by mdanatg** [comment]
@kkimdev @sanjoy for more insight about the differences of peak memory use.

The difference is not entirely surprising because tf.function and Python function execute things in different ways.

**Comment by abhigoyal2210** [comment]
Yes, they do but I found 3.5 times increase surprising. Also, If stacked tf.keras.layers.RNN (with LSTMCell) is replaced by tf.keras.layers.LSTM, this memory blow-up doesn't happen. On the contrary lesser memory is consumed (which might not be surprising as LSTM() would use CuDNN kernel). See the screenshot below.

GPU usage when tf.function is used and RNN(LSTMCell) as replaced by LSTM().
<img width="827" alt="Screenshot 2020-02-04 at 9 35 08 PM" src="https://user-images.githubusercontent.com/53578184/73762451-3b132b80-4796-11ea-8ec3-7245a3a5ba74.png">

**Comment by sanjoy** [comment]
Interesting find!

Can you check forcing the TF to use a smaller amount of memory (using [`set_local_device_configuration`](https://www.tensorflow.org/api_docs/python/tf/config/set_logical_device_configuration)) runs fine (i.e. without OOM) with `tf.function`?

`tf.function` uses the graph executor which (grossly simplifying) picks some execution order consistent with the data flow in the graph and this total order could be different enough from the eager execution order to explain the difference in memory usage.  However, the TF allocator has a [mechanism](https://github.com/tensorflow/tensorflow/blob/3fcf6424ae5fe0d2f062b222c2ba4467c0350c1e/tensorflow/core/common_runtime/bfc_allocator.cc#L213) to (again, oversimplifying) "pick" a different total order to avoid an OOM.

**Comment by abhigoyal2210** [comment]
Yes, it works fine when I set memory limit to 4500 or higher and gives OOM otherwise.

**Comment by Saduf2019** [comment]
@abhigoyal2210 
Could you please let us know if this is still an issue on tf 2.7 as per the above update, please confirm if this is still an issue.
