### ISSUE TITLE
You tried to call `count_params` on embedding, but the layer isn't built. You can build it manually via: `embedding.build(batch_input_shape)`.

### ISSUE THREAD

**Issue by Goofy-G** [tensorflow/tensorflow#36368]
when i run model.summary(), this issue occures.

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):windows 10 64bit
- TensorFlow installed from (source or binary):pip install tensorflow (cpu-version)
- TensorFlow version (use command below):tensorflow 2.0
- Python version:python 3.6

**Code to reproduce the issue**
import tensorflow as tf
from tagger.crf import crf_decode, crf_log_likelihood

k = tf.keras

class TaggerModel(k.Model):
    def __init__(self, config,  *args, **kwargs):
        super(TaggerModel, self).__init__(args, kwargs)
        self.embedding_layer = k.layers.Embedding(input_dim=config.vocab_size, output_dim=config.embedding_size)
        forward_layer = k.layers.LSTM(units=config.num_units, return_sequences=True, activation="sigmoid")
        backward_layer = k.layers.LSTM(units=config.num_units, return_sequences=True, activation="sigmoid",
                                       go_backwards=True)
        self.bidirectional_layer = k.layers.Bidirectional(
            layer=forward_layer, backward_layer=backward_layer, merge_mode="concat"
        )
        self.dropout_layer = k.layers.Dropout(rate=config.dropout)
        self.dense_layer = k.layers.Dense(units=config.num_tags)
        self.transition = tf.Variable(
            initial_value=tf.random.truncated_normal(shape=[config.num_tags, config.num_tags]), name="transition",
            trainable=True)

    @tf.function
    def call(self, inputs, training=None, mask=None):
        source, length = inputs

        # embedding
        embeddings = self.embedding_layer(source)

        # bidirectional
        out = self.bidirectional_layer(embeddings)
        out = self.dropout_layer(out)
        potentials = self.dense_layer(out)

        # crf
        logits, score = crf_decode(potentials=potentials, transition_params=self.transition, sequence_length=length)

        return logits

model = TaggerModel(config)
model.compile(optimizer=config.optimizer, loss=tf.losses.binary_crossentropy, metrics={tf.metrics.Accuracy()})
model.build(input_shape=((None, None), (None,)))
model.summary()

**Comment by amahendrakar** [comment]
@Goofy-G,
I tried to reproduce the issue, but I am facing an error stating `ModuleNotFoundError: No module named 'tagger'`. You can find the Gist of it [here](https://colab.sandbox.google.com/gist/amahendrakar/c3b83278aed679baccf3a0818d6cc7f6/36368.ipynb).

Seems like you are using custom python modules. In order to expedite the trouble-shooting process, could you please provide the complete code to reproduce the issue reported here including the custom modules. Thanks!

**Comment by Goofy-G** [comment]
Hi
  ！pip install tensorflow_addons==0.6， and then use from tensorflow_addons.text.crf import crf_decode, crf_log_likelihood instead of from tagger.crf import crf_decode, crf_log_likelihood

**Comment by amahendrakar** [comment]
@Goofy-G,
I was able to run the above code without any issues. Please find the Gist [here](https://colab.sandbox.google.com/gist/amahendrakar/65f11e4f2af377bc024817606b50afba/36368_2.ipynb). Thanks!

**Comment by Goofy-G** [comment]
Hi
   I am using tensorflow 2.0.0, not 2.1.0. And When I upgraded tensorflow to 2.1.0, it occured that I couldn't import tf. This is about another issue.
  I run the completed code , 
`
import tensorflow as tf

k = tf.keras


class TaggerModel(k.Model):
    def init(self, *args, **kwargs):
        super(TaggerModel, self).init(args, kwargs)
        # self.config = config
        self.embedding_layer = k.layers.Embedding(input_dim=2300, output_dim=128)
        forward_layer = k.layers.LSTM(units=128, return_sequences=True, activation="sigmoid")
        backward_layer = k.layers.LSTM(units=128, return_sequences=True, activation="sigmoid",
                                       go_backwards=True)
        self.bidirectional_layer = k.layers.Bidirectional(
            layer=forward_layer, backward_layer=backward_layer, merge_mode="concat"
        )
        self.dropout_layer = k.layers.Dropout(rate=0.5)
        self.dense_layer = k.layers.Dense(units=50)
        # self.transition = tf.Variable(
        # initial_value=tf.random.truncated_normal(shape=[config.num_tags, config.num_tags]), name="transition",
        # trainable=True)

    @tf.function(input_signature=(
    tf.TensorSpec(shape=[None, None], dtype=tf.int64), tf.TensorSpec(shape=[None, ], dtype=tf.int32)))
    def call(self, inputs, training=None, mask=None):
        source, length = inputs

        # embedding
        embeddings = self.embedding_layer(source)

        # bidirectional
        out = self.bidirectional_layer(embeddings)
        out = self.dropout_layer(out)
        potentials = self.dense_layer(out)

        # # crf
        # logits, score = crf_decode(potentials=potentials, transition_params=self.transition, sequence_length=length)
        # output = tf.one_hot(logits, depth=self.config.num_tags, dtype=tf.float32)
        output = potentials
        return output

model = TaggerModel()
model.compile(optimizer="adam", loss=tf.losses.sparse_categorical_crossentropy, metrics=[])
dataset = tf.data.Dataset.from_tensor_slices(tf.random.truncated_normal(shape=(20, 100)))
dataset = dataset.map(lambda src: ((tf.cast(src, dtype=tf.int64), tf.size(src))))
model.fit(x=dataset, validation_data=dataset)
model.summary()
tf.saved_model.save(model, "mydir")
`
and I got crash:

> Traceback (most recent call last):
  File "D:\Library\VirtualEnv\DeepLearning\lib\site-packages\tensorflow_core\python\keras\engine\base_layer.py", line 842, in __call__
    outputs = call_fn(cast_inputs, *args, **kwargs)
  File "D:\Library\VirtualEnv\DeepLearning\lib\site-packages\tensorflow_core\python\eager\def_function.py", line 457, in __call__
    result = self._call(*args, **kwds)
  File "D:\Library\VirtualEnv\DeepLearning\lib\site-packages\tensorflow_core\python\eager\def_function.py", line 503, in _call
    self._initialize(args, kwds, add_initializers_to=initializer_map)
  File "D:\Library\VirtualEnv\DeepLearning\lib\site-packages\tensorflow_core\python\eager\def_function.py", line 408, in _initialize
    *args, **kwds))
  File "D:\Library\VirtualEnv\DeepLearning\lib\site-packages\tensorflow_core\python\eager\function.py", line 1848, in _get_concrete_function_internal_garbage_collected
    graph_function, _, _ = self._maybe_define_function(args, kwargs)
  File "D:\Library\VirtualEnv\DeepLearning\lib\site-packages\tensorflow_core\python\eager\function.py", line 2150, in _maybe_define_function
    graph_function = self._create_graph_function(args, kwargs)
  File "D:\Library\VirtualEnv\DeepLearning\lib\site-packages\tensorflow_core\python\eager\function.py", line 2041, in _create_graph_function
    capture_by_value=self._capture_by_value),
  File "D:\Library\VirtualEnv\DeepLearning\lib\site-packages\tensorflow_core\python\framework\func_graph.py", line 915, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "D:\Library\VirtualEnv\DeepLearning\lib\site-packages\tensorflow_core\python\eager\def_function.py", line 358, in wrapped_fn
    return weak_wrapped_fn().__wrapped__(*args, **kwds)
  File "D:\Library\VirtualEnv\DeepLearning\lib\site-packages\tensorflow_core\python\eager\function.py", line 2658, in bound_method_wrapper
    return wrapped_fn(*args, **kwargs)
  File "D:\Library\VirtualEnv\DeepLearning\lib\site-packages\tensorflow_core\python\framework\func_graph.py", line 905, in wrapper
    raise e.ag_error_metadata.to_exception(e)
tensorflow.python.framework.errors_impl.OperatorNotAllowedInGraphError: in converted code:

    E:\Python\Work\TestTensorflow\TestTagger1\tests\common_test.py:26 call  *
        source, length = inputs
    D:\Library\VirtualEnv\DeepLearning\lib\site-packages\tensorflow_core\python\framework\ops.py:547 __iter__
        self._disallow_iteration()
    D:\Library\VirtualEnv\DeepLearning\lib\site-packages\tensorflow_core\python\framework\ops.py:540 _disallow_iteration
        self._disallow_when_autograph_enabled("iterating over `tf.Tensor`")
    D:\Library\VirtualEnv\DeepLearning\lib\site-packages\tensorflow_core\python\framework\ops.py:518 _disallow_when_autograph_enabled
        " decorating it directly with @tf.function.".format(task))

    OperatorNotAllowedInGraphError: iterating over `tf.Tensor` is not allowed: AutoGraph did not convert this function. Try decorating it directly with @tf.function.


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Library\Python\lib\unittest\case.py", line 59, in testPartExecutor
    yield
  File "D:\Library\Python\lib\unittest\case.py", line 605, in run
    testMethod()
  File "E:\Python\Work\TestTensorflow\TestTagger1\tests\common_test.py", line 52, in test_model
    model.fit(x=dataset, validation_data=dataset)
  File "D:\Library\VirtualEnv\DeepLearning\lib\site-packages\tensorflow_core\python\keras\engine\training.py", line 728, in fit
    use_multiprocessing=use_multiprocessing)
  File "D:\Library\VirtualEnv\DeepLearning\lib\site-packages\tensorflow_core\python\keras\engine\training_v2.py", line 224, in fit
    distribution_strategy=strategy)
  File "D:\Library\VirtualEnv\DeepLearning\lib\site-packages\tensorflow_core\python\keras\engine\training_v2.py", line 547, in _process_training_inputs
    use_multiprocessing=use_multiprocessing)
  File "D:\Library\VirtualEnv\DeepLearning\lib\site-packages\tensorflow_core\python\keras\engine\training_v2.py", line 594, in _process_inputs
    steps=steps)
  File "D:\Library\VirtualEnv\DeepLearning\lib\site-packages\tensorflow_core\python\keras\engine\training.py", line 2419, in _standardize_user_data
    all_inputs, y_input, dict_inputs = self._build_model_with_inputs(x, y)
  File "D:\Library\VirtualEnv\DeepLearning\lib\site-packages\tensorflow_core\python\keras\engine\training.py", line 2622, in _build_model_with_inputs
    self._set_inputs(cast_inputs)
  File "D:\Library\VirtualEnv\DeepLearning\lib\site-packages\tensorflow_core\python\keras\engine\training.py", line 2709, in _set_inputs
    outputs = self(inputs, **kwargs)
  File "D:\Library\VirtualEnv\DeepLearning\lib\site-packages\tensorflow_core\python\keras\engine\base_layer.py", line 854, in __call__
    str(e) + '\n"""')
TypeError: You are attempting to use Python control flow in a layer that was not declared to be dynamic. Pass `dynamic=True` to the class constructor.
Encountered error:
"""
in converted code:

    E:\Python\Work\TestTensorflow\TestTagger1\tests\common_test.py:26 call  *
        source, length = inputs
    D:\Library\VirtualEnv\DeepLearning\lib\site-packages\tensorflow_core\python\framework\ops.py:547 __iter__
        self._disallow_iteration()
    D:\Library\VirtualEnv\DeepLearning\lib\site-packages\tensorflow_core\python\framework\ops.py:540 _disallow_iteration
        self._disallow_when_autograph_enabled("iterating over `tf.Tensor`")
    D:\Library\VirtualEnv\DeepLearning\lib\site-packages\tensorflow_core\python\framework\ops.py:518 _disallow_when_autograph_enabled
        " decorating it directly with @tf.function.".format(task))

    OperatorNotAllowedInGraphError: iterating over `tf.Tensor` is not allowed: AutoGraph did not convert this function. Try decorating it directly with @tf.function.

**Comment by amahendrakar** [comment]
Was able to reproduce the issue. Please find the Gist [here](https://colab.sandbox.google.com/gist/amahendrakar/ef609db8a8327eb0608d08156da9c6d0/36368_2-0.ipynb). Thanks!

**Comment by jvishnuvardhan** [comment]
@Goofy-G Error is from `model.fit`. I have a question. Why the target tensor is empty as in `dataset = dataset.map(lambda src: ((tf.cast(src, dtype=tf.int64), tf.size(src))))`. Please check the [gist here](https://colab.sandbox.google.com/gist/jvishnuvardhan/1cc461b8d8086e0a3f48c178542edfcb/36368_2-0.ipynb). Thanks!

**Comment by Goofy-G** [comment]
HI,
   This is my mistake, I forget generating target data, the dataset should be `dataset = dataset.map(
            lambda src: ((tf.cast(src, dtype=tf.int64), tf.size(src)), tf.cast(src, dtype=tf.int64)))`. However, it doesn't influence to the issue what happened.

**Comment by mdanatg** [comment]
@omalleyt12 

The error in the gist indicates that `inputs` is not a 2-element tuple as you'd expect, but instead a single Tensor. When you try to expand that, Python tries to iterate over that Tensor which gives you the error message. Not sure where that single Tensor is coming from, but you can see it by adding a print statement:

```
  def call(self, inputs, training=None, mask=None):
        print(inputs)
        ...
  # Output: Tensor("inputs:0", shape=(None, None), dtype=int64)
```

@Goofy-G Keras expects your dataset to be batched, so you should call `dataset = dataset.batch(1)` even if you work with single examples.

But even after I added the batching, it seems that the second tensor is still not being passed to the model, which I think is a bug.

**Comment by mdanatg** [comment]
BTW, I couldn't see the original `count_oarams` in any of the error any more.

**Comment by Goofy-G** [comment]
Hi
   Thanks for your reply. The original crash occured when `I run model.summary()` instead of `model.fit()`. Firstly, I used to build model with `keras.Model(input, output)`, there is no crash happen, and then I transfer it to `model.call()`.
   Furthermore, I am failed to use `tf.saved_model.save()` to export serving model in tf 2.0. But I use `tf.keras.experimental.export_saved_model()` to export model, it's okay. What 's the deference about two.

**Comment by jvishnuvardhan** [comment]
@Goofy-G I assume original issue was resolved. If you face any issues when saving model, please open a new issue. I think it will be easy for other users who are facing similar issue in saving model. Thanks!

If the original issue was resolved, close this issue and open a new issue on saving model. Thanks!

**Comment by ravikyram** [comment]
@Goofy-G 

Any update on this issue please. Thanks!

**Comment by Goofy-G** [comment]
HI
  I got it, thanks bro

**Comment by Goofy-G** [comment]
Hi
   I got it, thanks bro.
