### ISSUE TITLE
regarding hosting of .h5 model using tfserving

### ISSUE THREAD

**Issue by divyag11** [tensorflow/tensorflow#36374]
hi, can I host .h5 model through tf serving, or it just supports .tfsavedformat models for hosting. please let me know if I can host it , and if you can suggest me an article for the support

**Comment by divyag11** [comment]
please reply

**Comment by oanush** [comment]
@divyag11 ,
Hi this issue looks like is related to tf-serving, can you please open new issue in [serving](https://github.com/tensorflow/serving/issues/new) repo?Thanks!
