### ISSUE TITLE
Callbacks should be able to access the training and validation data

### ISSUE THREAD

**Issue by nbro** [tensorflow/tensorflow#36376]
**System information**
- TensorFlow version (you are using): 2.1
- Are you willing to contribute it (Yes/No): Maybe

**Describe the feature and the current behavior/state.**

Currently, AFAIK, there's no direct way of accessing the training and validation data used for the mini-batch in the `on_batch_end` or `on_batch_begin` methods (in `tf.keras`).  Of course, this feature can be very useful, for example, if you want to debug the training data used for each training or validation mini-batches or, for example, if you want to compute other metrics on the specific batch of data used to update the parameters at each training step. Apparently, it was once possible to access the validation data inside the callback class, but this is no more available (not sure why!). See https://github.com/tensorflow/tensorflow/issues/36375. The training data for the mini-batch was never available, AFAIK.

I have seen people trying to access the training and validation data (used in the current mini-batch/step) in the callbacks, and the solutions are simply disgustingly verbose, inflexible, etc. (see https://stackoverflow.com/q/47079111/3924118). 

Why don't you provide this feature? This is clearly a useful feature (e.g. [this SO question](https://stackoverflow.com/q/53489352/3924118) shows that this feature would be appreciated). See also https://stackoverflow.com/q/47676248/3924118.

**Will this change the current api? How?**

Probably.

**Who will benefit with this feature?**

Everyone.

**Comment by jvishnuvardhan** [comment]
@nbro Sorry for the late response. Are you still interested in contributing? If yes, please feel free to open a PR in  [keras-team/keras repo.](https://github.com/keras-team/keras/issues) repository.

Please note that Keras development moved to keras-team/keras repository to focus on only keras. Thanks!
