### ISSUE TITLE
TensorFlow master build failing:  error: 'Packet4f' does not name a type

### ISSUE THREAD

**Issue by Nayana-ibm** [tensorflow/tensorflow#3639]
I am trying to build TensorFlow master on big endian architecture and I am facing build issues related to EIGEN_VECTORIZE_SSE2 as mentioned below:

```
In file included from tensorflow/core/kernels/sparse_matmul_op.cc:20:0:
./tensorflow/core/kernels/sparse_matmul_op.h:46:26: error: 'Packet4f' does not name a type
 EIGEN_DEVICE_FUNC inline Packet4f pexpand_bf16_l(const Packet4f& from) {

./tensorflow/core/kernels/sparse_matmul_op.h:59:26: error: 'Packet4f' does not name a type
 EIGEN_DEVICE_FUNC inline Packet4f pexpand_bf16_u(const Packet4f& from) {

./tensorflow/core/kernels/sparse_matmul_op.h:117:21: error: 'Packet4f' does not name a type
 EIGEN_STRONG_INLINE Packet4f pload4bf16<Packet4f>(const float* from) {

./tensorflow/core/kernels/sparse_matmul_op.h:128:21: error: 'Packet4f' does not name a type
 EIGEN_STRONG_INLINE Packet4f pload2bf16<Packet4f>(const float* from) {

```

Looks like this issue is caused due to a recent commit [fix build for PPC](https://github.com/tensorflow/tensorflow/pull/2911/commits/a1de95f38b442b0534f1f8871bc5cb16390725ae)
This commit includes fix for PPC however its breaking build for other non SSE platform. 

### Environment info
Operating System: **Ubuntu/Red Hat**

Installed version of CUDA and cuDNN: **Not installed**

The output from `python -c "import tensorflow; print(tensorflow.__version__)"`.  **master** 

If installed from source, provide 

1. The commit hash (`git rev-parse HEAD`)   [98d63de](https://github.com/tensorflow/tensorflow/commit/98d63de3bb2bab7c9a81f83c8ca864741399300c)  
2. The output of `bazel version`  **0.3.0**

### Steps to reproduce
1. bazel build -c opt //tensorflow/tools/pip_package:build_pip_package

### What have you tried?
1. Could build tensorflow master by removing condition for ` #ifndef EIGEN_VECTORIZE_SSE2 ` from tensorflow/core/kernels/sparse_matmul_op.h file.

**Comment by benoitsteiner** [comment]
A fix is on its way. I'm hoping to get it merged by tomorrow.
