### ISSUE TITLE
file_io.get_matching_files indefinitely hangs

### ISSUE THREAD

**Issue by prashastk** [tensorflow/tensorflow#36394]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): GCP cloud shell
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): Comes pre-installed in  GCP cloud shell
- TensorFlow version (use command below): TF 2.1
- Python version: 3.7.3
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

**Describe the current behavior**
file_io.get_matching_files indefinitely hangs

**Describe the expected behavior**
file_io.get_matching_files should not hang!

**Code to reproduce the issue**
Note the `//` in the first command
```
gsutil cp README-cloudshell.txt gs://<some_bucket>/test//bug.txt
gsutil cp README-cloudshell.txt gs://<some_bucket>/test/bug.txt
```
This creates a weird `/` folder under the test folder

Now open python
```
from tensorflow.python.lib.io import file_io
file_io.get_matching_files('gs://<some_bucket>/test/bug.txt')
```
This will hang. 
Delete the `/` folder and this would work fine.

One of our training jobs hung because TF somehow created a `/` folder in model output directory!

**Comment by mihaimaruseac** [comment]
Apologies for the long delay. This should be fixed in the next nightly and the next release.
