### ISSUE TITLE
Labels missing on TensorFlow Lite example after applying custom model.

### ISSUE THREAD

**Issue by karapapas** [tensorflow/tensorflow#36402]
I'm using Teachable Machine for an image classification problem.

I have exported the model produced by Teachable Machine in FLOAT format.

I strictly followed the instruction about placing the labels.txt and model on the right folder and also about making changes on ClassifierQuantizedMobileNet and activity_camera.xml

Yet still the labels and the percentage of confidence won't show up as they do in the example.
How to fix that?

![Screenshot_2020-02-01-12-34-07-431_org tensorflow lite examples classification](https://user-images.githubusercontent.com/24626324/73590854-26156e80-44f0-11ea-92bd-f5a09a9324fc.jpg)

**Comment by gadagashwini** [comment]
@karapapas, Please fill the [template](https://github.com/tensorflow/tensorflow/issues/new/choose) to analyze the reported issue.

**Comment by srjoglekar246** [comment]
"Classifier**Quantized**MobileNet"

"Teachable Machine in **FLOAT** format."

Maybe because the model(float) is not compatible with the classifier (quantized)?

**Comment by gadagashwini** [comment]
@karapapas, Did you check @srjoglekar246's comment.

**Comment by gadagashwini** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
