### ISSUE TITLE
dll loading failed in tensorflow

### ISSUE THREAD

**Issue by sidharth1805** [tensorflow/tensorflow#36401]
raise ImportError(msg)

ImportError: Traceback (most recent call last):
  File "C:\Users\sidha\Anaconda3\lib\site-packages\tensorflow_core\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\sidha\Anaconda3\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\sidha\Anaconda3\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Users\sidha\Anaconda3\lib\imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\sidha\Anaconda3\lib\imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: The specified module could not be found.

**Comment by sidharth1805** [comment]
python 3.7

**Comment by av8ramit** [comment]
What version of TensorFlow is this happening on? If this is in nightly do you mind seeing if it is possible to repro in the latest official release?

**Comment by av8ramit** [comment]
Please fill out the template in the future so we are able to better assist you. Looks like [this comment](https://github.com/tensorflow/tensorflow/issues/36167#issuecomment-577886156) can help and is related? We are updating documentation very soon.

**Comment by bmzhao** [comment]
Hi @sidharth1805, 

Did you install the Microsoft Visual C++ Redistributable for Visual Studio 2015, 2017, and 2019?

According to the docs at https://www.tensorflow.org/install/pip,

> Install the Microsoft Visual C++ Redistributable for Visual Studio 2015, 2017, and 2019. Starting with the TensorFlow 2.1.0 version, the msvcp140_1.dll file is required from this package (which may not be provided from older redistributable packages). The redistributable comes with Visual Studio 2019 but can be installed separately:

> Go to the [Microsoft Visual C++ downloads](https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads),
Scroll down the page to the Visual Studio 2015, 2017 and 2019 section.
Download and install the Microsoft Visual C++ Redistributable for Visual Studio 2015, 2017 and 2019 for your platform.
Make sure [long paths](https://superuser.com/questions/1119883/windows-10-enable-ntfs-long-paths-policy-option-missing) are enabled on Windows.

> Install the [64-bit Python 3 release](https://www.python.org/downloads/windows/) for Windows (select pip as an optional feature).

Tensorflow 2.1.0 is compiled using MSVC 2019, which appears to require an additional DLL.

**Comment by sidharth1805** [comment]
thank you sorry for responding late installing installing microsoft visual c++ solved the issue
