### ISSUE TITLE
sample code of while_loop can't execute on tf nightly

### ISSUE THREAD

**Issue by breadbread1984** [tensorflow/tensorflow#36404]
I am using 2.2.0-dev20200129. I find that the sample code [here](https://tensorflow.google.cn/api_docs/python/tf/while_loop#example_2) cause the following error message

>TypeError: Cannot iterate over a scalar tensor.

on this version.

**Comment by amahendrakar** [comment]
Was able to reproduce the issue with TF 2.2.0.dev20200203. Please find the Gist [here](https://colab.sandbox.google.com/gist/amahendrakar/0a0ec487ea78c0204cf155ba96e02efc/36404.ipynb). Thanks!

**Comment by ymodak** [comment]
```python
i = tf.constant(0)
c = lambda i: tf.less(i, 10)
b = lambda i: (tf.add(i, 1), )  #pass body as a tuple
r = tf.while_loop(c, b, [i])
```
The above example works in tf-nightly version.
See https://www.tensorflow.org/api_docs/python/tf/while_loop?version=nightly#example

**Comment by breadbread1984** [comment]
OK, so the body has to be a tuple currently.
