### ISSUE TITLE
Regression: contrib.boosted_trees.estimator_batch modules are not available in 1.15.2

### ISSUE THREAD

**Issue by lostmsu** [tensorflow/tensorflow#36417]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): v1.15.0-92-g5d80e1e8e6 1.15.2
- Python version: 3.7.4
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
Many modules are simply missing from `tensorflow.contrib.boosted_trees`, including `estimator_batch` and `lib`
```
>>> import tensorflow.contrib.boosted_trees.estimator_batch
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'tensorflow.contrib.boosted_trees.estimator_batch'
```
 

**Describe the expected behavior**
`import tensorflow.contrib.boosted_trees.estimator_batch` should succeed.

**Code to reproduce the issue**
`import tensorflow.contrib.boosted_trees.estimator_batch`

**Other info / logs**
Looks like a regression since 1.15.0

**Comment by oanush** [comment]
Issue replicating for latest [tf-1.15.2](https://colab.research.google.com/gist/oanush/a0cdd4f4bc54c60486bf7c1128d2385b/36417.ipynb),Thanks!
