### ISSUE TITLE
tf 2.1 do not support bazel 0.26?

### ISSUE THREAD

**Issue by njzjz** [tensorflow/tensorflow#36415]
## URL(s) with the issue:

https://www.tensorflow.org/install/source?hl=en

### Clear description

It's said that tensorflow 2.1.0 is built by bazel 0.26.1, but when I use bazel 0.26.1 to build, I get the following error:
```
Please upgrade your bazel installation to version 0.27.1 or higher to build TensorFlow!
```

So, what is the correct bazel version?

**Comment by mihaimaruseac** [comment]
I think there is a mistake in the documentation page. Will send an update for that.

In any case, the true version is the one mentioned in `./configure`, giving you the above error. Starting past week, `master` has Bazelisk set up so you won't have to manually install Bazel anymore, if building from master.

**Comment by ahtik** [comment]
Worth mentioning that if you plan to use Ubuntu to build TF 2.1 with TensorRT then you might have to still tweak the 2.1 source to allow bazel 0.26.1 as 0.27.1 seems to fail... (See https://github.com/tensorflow/tensorflow/issues/35115#issuecomment-580860705 for details).

Without TensorRT it wouldn't matter, 0.27.1 will be fine.

**Comment by njzjz** [comment]
Thank you for everyone! I can close this issue now.
