### ISSUE TITLE
tflite conversion

### ISSUE THREAD

**Issue by dimridd** [tensorflow/tensorflow#36412]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 18.04):
- TensorFlow installed from (pip3 install tensorflow==1.13.1):
- TensorFlow version (1.13.1):

**Provide the text output from tflite_convert**

```
Some of the operators in the model are not supported by the standard TensorFlow Lite runtime. If those are native TensorFlow operators, you might be able to use the extended runtime by passing --enable_select_tf_ops, or by setting target_ops=TFLITE_BUILTINS,SELECT_TF_OPS when calling tf.lite.TFLiteConverter(). Otherwise, if you have a custom implementation for them you can disable this error with --allow_custom_ops, or by setting allow_custom_ops=True when calling tf.lite.TFLiteConverter(). Here is a list of builtin operators you are using: CAST, MEAN, PACK. Here is a list of operators for which you will need custom implementations: DecisionTreeResourceHandleOp, TreeSize.
```

Also, please include a link to a GraphDef or the model if possible.

**Any other info / logs**

Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by amahendrakar** [comment]
@dimridd,
In order to expedite the trouble-shooting process, could you please provide the complete code to reproduce the issue reported here. Thanks!

**Comment by srjoglekar246** [comment]
These don't seem to be popular TF ops. You might need to implement TFLite [custom ops](https://www.tensorflow.org/lite/guide/ops_custom) to perform their behavior. 

Also look at our [general advice in the FAQ](https://www.tensorflow.org/lite/guide/faq#why_doesnt_my_model_convert) to handle unsupported ops.

Thanks!
