### ISSUE TITLE
Tensorflow2.0 checkpoint restore error

### ISSUE THREAD

**Issue by Panshangka** [tensorflow/tensorflow#36420]
Here is an error message:
`Exception ignored in: <bound method _CheckpointRestoreCoordinatorDeleter.__del__ of <tensorflow.python.training.tracking.util._CheckpointRestoreCoordinatorDeleter object at 0x0000014FDDC7CFD0>>
Traceback (most recent call last):
  File "C:\Users\17551\Miniconda3\lib\site-packages\tensorflow_core\python\training\tracking\util.py", line 140, in __del__    
TypeError: 'NoneType' object is not callable`

I'm using tensorflow-gpu 2.0, windows10, I imported the following libraries:
    from tensorflow.keras.preprocessing.text import text_to_word_sequence
    import tensorflow as tf

This is the code piece of how I restore the checkpoint:
    `checkpoint_dir = gConfig['model_data']
    seq2seqModel.checkpoint.restore(tf.train.latest_checkpoint(checkpoint_dir))`

**Comment by mihaimaruseac** [comment]
Please fill in the issue template, please use ` ``` ` around code blocks and errors, please make sure you search for duplicates of your issue, in case there is already some solution available.

**Comment by gadagashwini** [comment]
@Panshangka, Please provide the information asked in the Template to analyze the issue.

**Comment by Panshangka** [comment]
Thanks, it's solved. I'll close the issue

**Comment by ZXisSpider** [comment]
I met the same problem as you do, can you tell me how you solved the problem?

**Comment by klauspa** [comment]
> I met the same problem as you do, can you tell me how you solved the problem?

It's long time ago and I forget. Maybe you can post the code I'll see if I can help

**Comment by ZXisSpider** [comment]
`if __name__ == '__main__':`
    `model = TransE()`
    `checkpoint = tf.train.Checkpoint(my_model = model)`
    `checkpoint.restore(tf.train.latest_checkpoint('./checkpoint1'))`
    `test_case = [5, 6, 7]`
    `a, b = model.evaluate(test_case)`
    `print (a, b)`

And the output went like 
`
tf.Tensor([11028  7542  2595 ...  9127 14509     6], shape=(14951,), dtype=int32) tf.Tensor([ 6383  5011  5887 ...  3105 12434     5], shape=(14951,), dtype=int32)`
`Exception ignored in: <bound method _CheckpointRestoreCoordinatorDeleter.__del__ of <tensorflow.python.training.tracking.util._CheckpointRestoreCoordinatorDeleter object at 0x7f47d1dc2d30>>`
`
Traceback (most recent call last):
  File "/home/zhx/Paper/CL-KG/venv/lib/python3.6/site-packages/tensorflow_core/python/training/tracking/util.py", line 140, in __del__
`
`TypeError: 'NoneType' object is not callable`

**Comment by klauspa** [comment]
> tf.train.Checkpoint
I can't really help, but you can probably change the way of save and restore,  [checkpoint](https://www.tensorflow.org/api_docs/python/tf/train/CheckpointManager) manager maybe helpful. 
And double check the checkpoint the directory

**Comment by ZXisSpider** [comment]
Thank you all the same




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "klauspa"<notifications@github.com&gt;; 
发送时间: 2020年4月26日(星期天) 晚上6:23
收件人: "tensorflow/tensorflow"<tensorflow@noreply.github.com&gt;; 
抄送: "zz"<347862932@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [tensorflow/tensorflow] Tensorflow2.0 checkpoint restore error (#36420)





  
tf.train.Checkpoint
 I can't really help, but you can probably change the way of save and restore,  checkpoint manager maybe helpful.
 And double check the checkpoint the directory

**Comment by unrivalle** [comment]
I am facing the same issue can any one guide me?

**Comment by unrivalle** [comment]
# Testing the model performances.

import matplotlib
import matplotlib.pyplot as plt

import io
import os
import scipy.misc
import numpy as np
from six import BytesIO
from PIL import Image, ImageDraw, ImageFont

import tensorflow as tf

from object_detection.utils import label_map_util
from object_detection.utils import config_util
from object_detection.utils import visualization_utils as viz_utils
from object_detection.builders import model_builder

#%matplotlib inline


def load_image_into_numpy_array(path):
  img_data = tf.io.gfile.GFile(path, 'rb').read()
  image = Image.open(BytesIO(img_data))
  (im_width, im_height) = image.size
  return np.array(image.getdata()).reshape(
      (im_height, im_width, 3)).astype(np.uint8)


#recover our saved model
pipeline_config = './exported/pipeline.config'   
#generally you want to put the last ckpt from training in here
model_dir = './train_output/ckpt-1'   
configs = config_util.get_configs_from_pipeline_file(pipeline_config)
model_config = configs['model']
detection_model = model_builder.build(model_config=model_config, is_training=False)
# Restore checkpoint
ckpt = tf.compat.v2.train.Checkpoint(model=detection_model)
ckpt.restore(os.path.join('./train_output/ckpt-2'))

def get_model_detection_function(model):
  """Get a tf.function for detection."""

  @tf.function
  def detect_fn(image):
    """Detect objects in image."""

    image, shapes = model.preprocess(image)
    prediction_dict = model.predict(image, shapes)
    detections = model.postprocess(prediction_dict, shapes)

    return detections, prediction_dict, tf.reshape(shapes, [-1])

  return detect_fn

detect_fn = get_model_detection_function(detection_model)
#map labels for inference decoding
label_map_path = configs['eval_input_config'].label_map_path
label_map = label_map_util.load_labelmap(label_map_path)
print(label_map)
