### ISSUE TITLE
Allocation of 10616832 exceeds 10% of system memory.

### ISSUE THREAD

**Issue by KoizumiNao** [tensorflow/tensorflow#36429]
Hi. I'm currently having some problems after running the Object_detection.py like:

2020-02-01 11:57:36.437688: W tensorflow/core/framework/cpu_allocator_impl.cc:81] Allocation of 10616832 exceeds 10% of system memory.
Killed

My device is **Raspberry Pi 3 B+**.
Tensorflow Version: **1.14.0**
Python Version: **Python 3.7.3**
GPU: **128**
Currently using: **faster_rcnn_inception_v2_coco_2018_01_28**

Can anyone help me with this? I appreciate any response that can fix this problem.

**Comment by jvishnuvardhan** [comment]
@KoizumiNao This looks like a support issue. GitHub is mainly for Bugs and performance related issues. Your model might be big and cannot fit into the memory. Please post in stackoverflow and provide more details on your hardware. We will resolve it there. Thanks!

This is not Build/Installation or Bug/Performance issue. Please post this kind of support questions at [Stackoverflow](https://stackoverflow.com/questions/tagged/tensorflow). There is a big community to support and learn from your questions. GitHub is mainly for addressing bugs in installation and performance. Thanks!
