### ISSUE TITLE
HadoopFileSystem load error

### ISSUE THREAD

**Issue by baqwas** [tensorflow/tensorflow#36427]
this is a build/installation issue.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
```
$ cat /proc/cpuinfo
processor	: 0
model name	: ARMv6-compatible processor rev 7 (v6l)
BogoMIPS	: 697.95
Features	: half thumb fastmult vfp edsp java tls 
CPU implementer	: 0x41
CPU architecture: 7
CPU variant	: 0x0
CPU part	: 0xb76
CPU revision	: 7

Hardware	: BCM2835
Revision	: 0010
Serial		: 00000000
Model		: Raspberry Pi Model B Plus Rev 1.2
$ 
```

```
$ uname -a
Linux raspbari1 4.19.97+ #1293 Wed Jan 22 17:05:40 GMT 2020 armv6l GNU/Linux
```
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
n/a

- TensorFlow installed from (source or binary):
- TensorFlow version:
```
Installing collected packages: tensorflow-estimator, protobuf, h5py, keras-applications, astor, termcolor, cachetools, pyasn1, rsa, pyasn1-modules, google-auth, google-auth-oauthlib, absl-py, grpcio, markdown, tensorboard, gast, google-pasta, opt-einsum, wrapt, keras-preprocessing, tensorflow
Successfully installed absl-py-0.9.0 astor-0.8.1 cachetools-4.0.0 gast-0.2.2 google-auth-1.11.0 google-auth-oauthlib-0.4.1 google-pasta-0.1.8 grpcio-1.26.0 h5py-2.10.0 keras-applications-1.0.8 keras-preprocessing-1.1.0 markdown-3.1.1 opt-einsum-3.1.0 protobuf-3.11.2 pyasn1-0.4.8 pyasn1-modules-0.2.8 rsa-4.0 tensorboard-2.0.2 tensorflow-1.14.0 tensorflow-estimator-1.14.0 termcolor-1.1.0 wrapt-1.11.2

```
- Python version:
```
Python 3.7.3 (default, Apr  3 2019, 05:39:12) 
[GCC 8.2.0] on linux

```
- Installed using virtualenv? pip? conda?:
`python3 -m pip install tensorflow`

- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
n/a
- GPU model and memory:
n/a

**Describe the problem**
`2020-02-02 15:11:00.880396: E tensorflow/core/platform/hadoop/hadoop_file_system.cc:132] HadoopFileSystem load error: libhdfs.so: cannot open shared object file: No such file or directory`

**Provide the exact sequence of commands / steps that you executed before running into the problem**
```
$ python3
Python 3.7.3 (default, Apr  3 2019, 05:39:12) 
[GCC 8.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow
```

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by mihaimaruseac** [comment]
Duplicates #36141, hence closing. Please make sure in the future to search for similar issues.

**Comment by baqwas** [comment]
I don't have any explicit need for Hadoop. Does your package need Hadoop _libraries_? If so please update your documentation accordingly.

Kind regards.
