### ISSUE TITLE
performance issue when using the function tf.convert_to_tensor()

### ISSUE THREAD

**Issue by farotem** [tensorflow/tensorflow#36422]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
linux ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
NA
- TensorFlow installed from (source or binary):
binary, loaded from tensorflow docker
- TensorFlow version (use command below):
v2.1.0-rc2-17-ge5bf8de 2.1.0
- Python version:
3.6.9
- Bazel version (if compiling from source):
NA
- GCC/Compiler version (if compiling from source):
NA
- CUDA/cuDNN version:
CUDA 10.1
- GPU model and memory:
v100 32 GB
You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
I'm suspecting a CPU performance issue when converting a numpy array to tensor.
The duration of the function increased significantly (factor ~4) depends on the data size but not linear and also with large jitters.

Inspecting deeply into number of elements as a graph, we observed jitters and better performance, for some data sizes and bad performance for other data sizes, any ideas why there are large jitters? 

Note: we need to understand in a manner of milliseconds for near real-time application.  
attached:

- graph of convert_to_tensor depends for 1,000,000 - 60,000,000 elements 
- graph of convert_to_tensor depends for 1,000,000 - 7,000,000 elements (deeper scope)

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

```
import numpy as np
import tensorflow as tf
import time

for j in range(100):
    input_data = np.float32(np.random.rand(1125000 + j * 500000))
    start = time.time()
    converted_data = tf.convert_to_tensor(input_data, dtype=np.float32)
    stop = time.time()
    print("convert of", 1125000 + j * 500000, "took [ms]: ", 1000 * (stop - start))



for j in range(100):
    input_data = np.float32(np.random.rand(1125000 + j * 50000))
    start = time.time()
    converted_data = tf.convert_to_tensor(input_data, dtype=np.float32)
    stop = time.time()
    print("convert of", 1125000 + j * 50000, "took [ms]: ", 1000 * (stop - start))
```

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

![convert_to_tf_graph_1E06_6E07](https://user-images.githubusercontent.com/27951762/73609337-394e3a00-45d5-11ea-8f1e-aaeaa7c71f22.PNG)
![convert_to_tf_graph_1E06_7E06](https://user-images.githubusercontent.com/27951762/73609338-39e6d080-45d5-11ea-95eb-feb1039a71f6.PNG)

**Comment by Saduf2019** [comment]
i am able to replicate the issue, please find the [gist](https://colab.research.google.com/gist/Saduf2019/a3e9ffb27effa829b30fe9f53c8a985c/36422.ipynb) here.

**Comment by ccrusius** [comment]
I don't think this is a TensorFlow problem: if you replace your `tf.convert_to_tensor` calls with copies of the `np.random.rand` calls above, you'll see that the Numpy calls also take more and more time. So even without TensorFlow involved, you get the same behavior. Example:

```python
  for j in range(50):
    start = time.time()
    input_data = np.float32(np.random.rand(1125000 + j * 500000))
    stop = time.time()
    print("convert of", 1125000 + j * 500000, "took [ms]: ", 1000 * (stop - start))
```

I'll close this as it seems "normal" Python behavior. Feel free to reopen if you find otherwise!

**Comment by ccrusius** [comment]
Note: sometimes I see the jitters there without TensorFlow code too. Internally, `convert_to_tensor` does not do much work when given Numpy arrays as in your example, so the variations you are seeing are likely due to Python internals.

**Comment by ccrusius** [comment]
Ah, one more note (sorry, I forgot about this one and it is actually the main point): the timing differences is due to Python internals, _but_ in TF `master` the problem does not exist anymore: `convert_to_tensor` takes around half a millisecond for any of the conversions in your example, so the "longer with larger inputs" behavior is not there anymore.
