### ISSUE TITLE
No session factory registered for the given session options

### ISSUE THREAD

**Issue by nicolastonon** [tensorflow/tensorflow#36433]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04.3 LTS
- TensorFlow installed from (source or binary): source
- TensorFlow version: v2.1.0
- Python version: 3.7.4
- Installed using virtualenv? pip? conda?: conda
- Bazel version (if compiling from source): 0.29.1
- GCC/Compiler version (if compiling from source): g++ 7.4.0

**Describe the problem**
I have built TF from source ([link](https://www.tensorflow.org/install/source)). I have trained a DNN in python, frozen it as a .pb file, and now I would like to load the model and perform the evaluation in m my C++ code ([Gist here](https://gist.github.com/nicolastonon/d03605315f00228ace0a3c2a2621feda)). 

However I get a segfault already when trying to create a session : 

```
2020-02-03 11:55:25.001775: E tensorflow/core/common_runtime/session.cc:89] Not found: No session factory registered for the given session options: {target: "" config: } Registered factories are {}.
error while creating session: Not found: No session factory registered for the given session options: {target: "" config: } Registered factories are {}.
```

There have been similar issues (e.g. #3308), for which the proposed solution is to add the `-Wl,--whole-archive` flag when linking the TF libraries ; however this does not seem to work for me.

Does anybody have an idea what I could be doing wrong ?

**Provide the exact sequence of commands / steps that you executed before running into the problem**
1) Build TF from source

2) Compile (successfully) a custom C++ code creating a Session, linking the TF libraries with the relevant option (e.g : `-L/home/ntonon/Documents/Programmes/tensorflow/bazel-bin/tensorflow -Wl,--whole-archive -Wl,--no-as-needed -ltensorflow_framework`)

3) Running the code gives the error cited above.

Thanks in advance.

**Comment by GaussRieman** [comment]
Hi, Have you solved this problem?

It has been troubling me for quite a long time until I add a header file in the source cpp in which the main function is compiled.

You can try to add "tensorflow/cc/client/client_session.h" in your entrance source file.

Though It has solved this problem, but I still don't know why.

**Comment by nicolastonon** [comment]
Hi, yes I managed to solve it, unfortunately I tried so many things I don't remember what helped.
I now link as such (probably an overkill): 
`LFLAGS+= -L/home/mypath/tensorflow/bazel-bin/tensorflow -Wl,--allow-multiple-definition -Wl,--whole-archive -ltensorflow_framework -Wl,--whole-archive -Wl,--no-as-needed -ltensorflow_cc #-lprotobuf`

I think what caused the issue for some reason was this : 
`session = tensorflow::createSession((tensorflow::GraphDef*) graphDef);`

which I replaced by manual calls to functions: 
`tensorflow::Status status;
tensorflow::SessionOptions sessionOptions;
status = NewSession(sessionOptions, &session);
status = session->Create(*graphDef);`

**Comment by li-zihang** [comment]
It took me quite a long time to debug this issue.
Finally I fixed it by using this `tensorflow_cc` library.

This is how to generate this lib:
```
bazel build --config=opt //tensorflow:libtensorflow_cc.so
```

Then pick it from `bazel-out` path to wherever you want to put in. For example, I put it in `/usr/local/lib/python3.10/dist-packages/tensorflow/`. 

Link this lib with `-ltensorflow_cc` in CMakeLists.


It makes me confused that `pip install tensorflow` cannot be used as C++ API creating session? Even ABI version fixed.

**Comment by WeiyanZh** [comment]
```pip install tensorflow``` can only generate ```libtensorflow_cc.so.2``` and ```libtensorflow_framework.so.2```. I found that when I use flags ``` -ltensorflow_cc```  and ``` -ltensorflow_framework``` , they are not found.

If the tensorflow is installed manuelly using ```bazel```, ```libtensorflow_cc.so``` and ```libtensorflow_framework.so``` will be generated in ```/tensorflow/bazel-bin/tensorflow/``` directory. Then linking wirh flags ``` -ltensorflow_cc```  and ``` -ltensorflow_framework``` does the trick.
