### ISSUE TITLE
regarding ckpt.meta file

### ISSUE THREAD

**Issue by divyag11** [tensorflow/tensorflow#36437]
hi,i am doing my finetuning in tf 2.1.Since i am using bert model for finetuning,it produces checkpoints, I have .index,.data but i didn'T GET .meta file in checkpoint folder,since i am finetuning in tf 2.1.
I need to run this mentioned down code in tensorflow verion 2,but this mentioned down code is presently in tf 1 version:(This code is basically for down sizing the model size by removing the trainable parameters)
```import tensorflow as tf
import os
#path that contains all 3 ckpt files of your fine-tuned model
path = './bert_output'
#path to output the new optimized model
output_path = os.path.join(path, 'optimized_model')
sess = tf.Session()
imported_meta = tf.train.import_meta_graph(os.path.join(path, 'model.ckpt-236962.meta')) #based on the steps of your fine-tuned model
imported_meta.restore(sess, os.path.join(path, 'model.ckpt-236962')) #based on the steps of your fine-tuned model
my_vars = []
for var in tf.all_variables():
    if 'adam_v' not in var.name and 'adam_m' not in var.name:
        my_vars.append(var)
saver = tf.train.Saver(my_vars)

**Comment by divyag11** [comment]
please reply

**Comment by gadagashwini** [comment]
@divyag11, Please take a look at [Tensorflow bert model](https://github.com/google-research/bert). Thanks

**Comment by divyag11** [comment]
ok

**Comment by gadagashwini** [comment]
@divyag11, Closing as it is resolved. Please feel free to open if still issue persists.Thanks

**Comment by aPeter1** [comment]
I've fine tuned a bunch of different networks at this point from the TF 2 Model zoo and none of them give me ckpt.meta files
