### ISSUE TITLE
Categorical encoding in `docs/csv.ipynb` returning inconsistent results.

### ISSUE THREAD

**Issue by laghaout** [tensorflow/tensorflow#36448]
## URL(s) with the issue:

https://www.tensorflow.org/tutorials/load_data/csv

which is available on GitHub at

https://github.com/tensorflow/docs/blob/master/site/en/tutorials/load_data/csv.ipynb

## Description of issue:

This is about the output of the last cell in the section _Categorical data_, namely the output of `print(categorical_layer(example_batch).numpy()[0])`. If we remove the index `[0]`, we're supposed to get the one-hot encoding of the categorical features, i.e., a 5-by-20 matrix, where 5 is the batch size and 20 is the total dimensionality of all categorical features.

If, for the sake of reproducibility, we also set `shuffle=False` in the call to `tf.data.experimental.make_csv_dataset()` at the very top of the notebook, the matrix we then get is:

```
[[0. 1. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 1. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 1. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 0.]]
```

This does not match up with the input categorical features for that batch, namely

```
sex: [b'male' b'female' b'female' b'female' b'male']
class: [b'Third' b'First' b'Third' b'First' b'Third']
deck: [b'unknown' b'C' b'unknown' b'C' b'unknown']
embark_town: [b'Southampton' b'Cherbourg' b'Southampton' b'Southampton' b'Queenstown']
alone: [b'n' b'n' b'y' b'n' b'y']
```

For example, `[b'male' b'female' b'female' b'female' b'male']` does not match up with the first two columns of the matrix.

**Comment by welbertrana** [comment]
Hi @laghaout,  the categorical features are plotted alphabetically.
When you print the `categorical_layer(example_batch)` you will get the alphabetically sorted one-hot encoding.

For this the first 2 columns is the 'alone' column, then next 3 columns is for 'Class' column, and so on.

Hope this helps you. :)

**Comment by gowthamkpr** [comment]
@laghaout please go through the above comment and let me know if it helps. Thanks!

**Comment by laghaout** [comment]
Yes, it's clear now, thanks.

If I were to give feedback to TF, however, I'd say that this sorting "under the hood" can be a source of confusion since the developers will normally have a certain ordering of their features in mind. Overwriting that ordering makes it difficult to read the stacked one-hot encodings or embeddings in general. If anything, it would be better to enforce that the user provides ordered dictionaries rather than doing this sorting behind the scenes.

**Comment by gowthamkpr** [comment]
Yes. I am closing this issue but you can go ahead and open a new issue related to docs.
