### ISSUE TITLE
TensorFlow lite on armv6 (Raspberry Zero) crashes wit SIGILL

### ISSUE THREAD

**Issue by bvarbanov** [tensorflow/tensorflow#36445]
sudo apt-get update
sudo apt-get install crossbuild-essential-armhf
git clone https://github.com/tensorflow/tensorflow.git
cd ./tensorflow
git checkout r2.0
./tensorflow/lite/tools/make/download_dependencies.sh

CC_PREFIX=arm-linux-gnueabihf- make -j 8 -f ./tensorflow/lite/tools/make/Makefile TARGET=rpi TARGET_ARCH=armv6l

Try running on Raspberry Pi Zero the example minimal - it crashes with Invalid Instruction
/tensorflow/tensorflow/lite/tools/make/gen/rpi_armv6l/bin/minimal

**Comment by terryheo** [comment]
Could you try it again with TARGET_ARCH=armv6 ?
According to tensorflow/lite/tools/make/targets/rpi_makefile.inc, "armv6l" won't work.

**Comment by bvarbanov** [comment]
In file included from tensorflow/lite/core/api/error_reporter.cc:15:0:
./tensorflow/lite/core/api/error_reporter.h: In destructor ‘virtual tflite::ErrorReporter::~ErrorReporter()’:
./tensorflow/lite/core/api/error_reporter.h:37:28: sorry, unimplemented: Thumb-1 hard-float VFP ABI
   virtual ~ErrorReporter() {}

**Comment by terryheo** [comment]
Are you seeing #36661 ? Please refer it.
It seems that SIGILL issue was gone.

**Comment by bvarbanov** [comment]
There must be additional setup because build fails with:
sorry, unimplemented: Thumb-1 hard-float VFP ABI
OS: Ubuntu 18.04 LTS

**Comment by terryheo** [comment]
I've tested both 2.0 branch and 2.1 but I can't find any build issue on cross build.

@bvarbanov did you try clean build?

CC_PREFIX=arm-linux-gnueabihf- make -j 8 -f ./tensorflow/lite/tools/make/Makefile TARGET=rpi TARGET_ARCH=armv6l clean
CC_PREFIX=arm-linux-gnueabihf- make -j 8 -f ./tensorflow/lite/tools/make/Makefile TARGET=rpi TARGET_ARCH=armv6l

**Comment by bvarbanov** [comment]
Try now with armv6 (no trailing l)

CC_PREFIX=arm-linux-gnueabihf- make -j 8 -f ./tensorflow/lite/tools/make/Makefile TARGET=rpi TARGET_ARCH=armv6

I get compile errors: 
/usr/arm-linux-gnueabihf/include/stdlib.h:361:1: sorry, unimplemented: Thumb-1 hard-float VFP ABI

**Comment by terryheo** [comment]
@bvarbanov you should use armv6l. What's the result of using armv6l?

**Comment by terryheo** [comment]
Oh i was wrong. You're right.
You should use armv6. Now I can reproduce the issue. Let me dig more.

**Comment by bvarbanov** [comment]
there is a tricky part with raspberry pi zero - the similar bug has been reported to WebRTC and abseil teams... Nobody has done anything so far about it - but it's a result of incorrectly generated floating point instructions...

I can reproduce some of the crashes using cross-compiled program like thins:
int main()
{
  long long a = 1;
  auto b = static_cast<double>(a); // <--- vmov instruction here goes boom
  return 0;
}

I have this crash also using cross-compiling with clang:

my toolchain cmake file has following options targeting raspberry zero (cpu arm1176jzf-s)

SET(triple "arm-linux-gnueabihf")
add_compile_options(-target ${triple})
add_compile_options(-march=armv6zk)
add_compile_options(-mfpu=vfp)
add_compile_options(-mcpu=arm1176jzf-s)
add_compile_options(-mfloat-abi=hard)
add_compile_options(-Wall)
add_compile_options(-fPIC)

**Comment by terryheo** [comment]
Could you try this?

https://github.com/terryheo/tensorflow/commit/9e4de36c24ecb84af1ac77cb9d6c46f5d885313b

**Comment by bvarbanov** [comment]
Build is fixed. On raspberry pi zero - resulting executable is still crashing 
  
pi@pi4:~/prob $ ls
benchmark_model  benchmark_model_performance_options  minimal
pi@pi4:~/prob $ ./minimal
Segmentation fault
pi@pi4:~/prob $ ./benchmark_model
Segmentation fault
pi@pi4:~/prob $ ./benchmark_model_performance_options
Illegal instruction
pi@pi4:~/prob $
pi@pi4:~/prob $ gdb -q ./minimal
Reading symbols from ./minimal...done.
(gdb) start
Temporary breakpoint 1 at 0x5a2c
Starting program: /home/pi/prob/minimal
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/arm-linux-gnueabihf/libthread_db.so.1".

Program received signal SIGSEGV, Segmentation fault.
0x004557f4 in std::pair<int, int> tflite::ops::builtin::tile::(anonymous namespace)::TileOneDimension<int, int>(TfLiteIntArray const&, int const*, int const*, int*, int) ()

**Comment by bvarbanov** [comment]
I have if fixed:

For rasbperry pi zero:
sudo apt-get install crossbuild-essential-armel

Modify the rpi_makefile.inc for rasbperry pi zero to have proper toolchain prefix:
TARGET_TOOLCHAIN_PREFIX := arm-linux-gnueabi-

**Comment by terryheo** [comment]
Thanks for the information. Let me fix the script.

**Comment by terryheo** [comment]
Fix was merged.
