### ISSUE TITLE
TensorShape dimensions size should be of type uint64, not int64

### ISSUE THREAD

**Issue by sdenel** [tensorflow/tensorflow#3645]
According to core/framework/tensor_shape.cc:171:
```cpp
void TensorShape::AddDim(int64 size) {
    CHECK_GE(size, 0);
```

TensorShape dimensions size can only be greater or equal to 0. **Thus, its type should be uint64_t.**

I even wonder if **size_t** would not be more appropriate.

**Comment by poxvoculi** [comment]
Use of this type is deliberate, and reflects Google coding guidelines.  Signed int types are to be preferred since overflow/underflow errors are more likely to be caught.  Loss of one bit of range is not of concern in this case.
