### ISSUE TITLE
Broken outbound links from index pages for older TF API

### ISSUE THREAD

**Issue by lichili233** [tensorflow/tensorflow#36452]
## URL(s) with the issue:

Numerous links of the older TF APIs, listing only a few index pages as examples here:

- Links under "Classes" and "Functions" within https://github.com/tensorflow/docs/blob/r1.11/site/en/api_docs/python/tf.md
- Links under "Classes" and "Functions" within https://github.com/tensorflow/docs/blob/r1.11/site/en/api_docs/python/tfdbg.md
- Links within https://github.com/tensorflow/docs/blob/r1.5/site/en/api_docs/python/index.md
- "JAVA" link within https://github.com/tensorflow/docs/blob/r1.7/site/en/api_docs/index.md

## Description of issue (what needs changing):

A large amount of links on index pages (e.g. for functions and classes) are currently broken (404). This appears to affect only the older TF versions (multiple versions affected), whose index pages are Markdown files within Github repositories.

### Clear description

Outbound links from these indexing pages are currently broken. Some might be fixed by adding a .md after the current URL to point to the correct Markdown available in the repositories, but not all of them can be fixed through this way.

### Correct links

Is the link to the source code correct?
- Incorrect.

### Submit a pull request?

Are you planning to also submit a pull request to fix the issue?
- Currently no plan.

**Comment by ravikyram** [comment]
This issue persists in latest TF versions as well.Please, find below links as well.Thanks!

https://github.com/tensorflow/docs/blob/r1.15/site/en/api_docs/python/tf.md

https://github.com/tensorflow/docs/blob/r2.0/site/en/api_docs/python/tf.md

https://github.com/tensorflow/docs/blob/r1.15/site/en/api_docs/python/tfdbg.md

https://github.com/tensorflow/docs/blob/r2.0/site/en/api_docs/python/tfdbg.md

https://github.com/tensorflow/docs/blob/r1.15/site/en/api_docs/python/index.md

https://github.com/tensorflow/docs/blob/r2.0/site/en/api_docs/python/index.md

**Comment by MarkDaoust** [comment]
Acknowledged.

This is my fault. I'll make sure it doesn't happen going forward, but IDK how many of the old snap-shots I can fix.

**Comment by abhinavsp0730** [comment]
Hey, @MarkDaoust  I'll happy to work in this issue.

**Comment by mohantym** [comment]
Hi @lichili233 ! 1.x version are not supported any more. For the 2.x version , You can find working links here. 
[python/index.md](https://github.com/tensorflow/docs/blob/r2.0/site/en/api_docs/python/index.md)  (Updated till 2.0 )
[api_docs/index.md](https://github.com/tensorflow/docs/blob/r2.3/site/en/api_docs/index.md)  (Updated till 2.3)
[python/tf.md](https://github.com/tensorflow/docs/blob/r2.4/site/en/api_docs/python/tf.md) (updated till 2.4)

Could not find tfbdg.md in 2.x version. Thanks!
