### ISSUE TITLE
tensorflow.python.framework.errors_impl.InvalidArgumentError: input and filter must have same depth

### ISSUE THREAD

**Issue by Amit507017** [tensorflow/tensorflow#36455]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
- **HPC**:
- **TensorFlow installed from conda**:
- **TensorFlow version 1.15**:
- **Python version 3.6.10:
- **Bazel version (if compiling from source)**:
- **GCC/Compiler version (if compiling from source)**:
- **CUDA/cuDNN version**:
- **GPU model and memory**:
- **Exact command to reproduce**:

You can collect some of this information using our environment capture script:

https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh

You can obtain the TensorFlow version with:

```bash
python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"
```

### Describe the problem
Folloing is the model graph summary
![image](https://user-images.githubusercontent.com/13520957/73723907-711ac600-472a-11ea-8762-21a4787e2193.png)
And the error code is 
![image](https://user-images.githubusercontent.com/13520957/73723959-8b54a400-472a-11ea-96d0-38cd9e792ce3.png)

I assume that the layer 'block1_conv1' should automatically generate output with depth 64. 
However, from the error message it looks like it generates an output with depth 1 only. What is wrong here?

**Comment by gadagashwini** [comment]
@Amit507017, Please provide the minimal standalone code to replicate the reported issue. Thanks!

**Comment by gadagashwini** [comment]
@Amit507017, Could you provide the standalone code to analyze the issue. Thanks

**Comment by gadagashwini** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
