### ISSUE TITLE
even load work?

### ISSUE THREAD

**Issue by mulka** [tensorflow/tensorflow#36454]
## URL(s) with the issue:
https://www.tensorflow.org/guide/migrate#saved_models_compatibility

## Description of issue (what needs changing):
The sentence below is unclear in what it means. I think there might be an extra word.

"TensorFlow 2.0 saved_models even load work in TensorFlow 1.x if all the ops are supported."

**Comment by ymodak** [comment]
Thanks. This is fixed now.
