### ISSUE TITLE
tf.keras.Sequential ignores the outer name scope(s) when built proactively

### ISSUE THREAD

**Issue by aakhundov** [tensorflow/tensorflow#36463]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): macOS Catalina 10.15.2 (19C57)
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.1.0
- Python version: 3.6.5 (v3.6.5:f59c0932b4)

**Describe the current behavior**

When the `build` method of a `tf.keras.Sequential` instance is (explicitly) called within one (or several nested) `tf.name_scope` context manager(s), the variable (weight) names of the layers wrapped into the `Sequential` don't get the respective name scope prefixes.

**Describe the expected behavior**

After `build`ing a `Sequential`, all the `tf.name_scope`s surrounding the `build` call must be reflected as prefixes of the `Sequential`'s variable (weight) names. This is what currently happens in `tensorflow==1.15.2`.

**Code to reproduce the issue**

```python
import tensorflow as tf

seq = tf.keras.Sequential(layers=[
    tf.keras.layers.Dense(units=10, name="d1"),
    tf.keras.layers.Dense(units=20, name="d2"),
])

with tf.name_scope("a"):
    with tf.name_scope("b"):
        seq.build(input_shape=[32, 784])

for w in seq.weights:
    print(w.name)
```

the output with `tensorflow==2.1.0`:

```
d1/kernel:0
d1/bias:0
d2/kernel:0
d2/bias:0
```

the output with `tensorflow==1.15.2`:

```
a/b/d1/kernel:0
a/b/d1/bias:0
a/b/d2/kernel:0
a/b/d2/bias:0
```

**Comment by ravikyram** [comment]
I have tried on colab with TF version 2.1.0-rc2,2.2.0-dev20200204 and was able to reproduce the issue.Please, find the gist [here](https://colab.research.google.com/gist/ravikyram/de7f77d612ed52c22e0eb969c126e08c/untitled620.ipynb). Thanks!

**Comment by ymodak** [comment]
If you enable eager execution in TF 1.15.2 you will see that it prints same output at TF 2.1
```python
d1/kernel:0
d1/bias:0
d2/kernel:0
d2/bias:0
Reason being eager execution is enabled by default in TF 2.X.
https://github.com/tensorflow/tensorflow/blob/2.1/tensorflow/python/framework/ops.py#L6389
Scope name is added if not executing eagerly.

**Comment by aakhundov** [comment]
@ymodak Thank you for the answer.

I can confirm what you've written. I can also add that, even in TF 2.1, if the `build` call nested in a pair of `tf.name_scope` context managers happens within a `@tf.function`-decorated function,

```python
@tf.function
def func():
    with tf.name_scope("a"):
        with tf.name_scope("b"):
            seq.build(input_shape=[32, 784])

func()

for w in seq.weights:
    print(w.name)
```

 the names defined by the `tf.name_scope`s show up in the resulting variable (weight) names:

```
a/b/d1/kernel:0
a/b/d1/bias:0
a/b/d2/kernel:0
a/b/d2/bias:0
```

On the other hand, I cannot agree that it is normal that `Sequential` is ignoring the `tf.name_scope`s in the eager mode. For two reasons:

1. The [documentation](https://www.tensorflow.org/api_docs/python/tf/name_scope) of `tf.name_scope` doesn't say that doesn't  to work in the eager mode.

2. More importantly, an instance of `tf.keras.layers.Dense` built by explicitly calling its `built` method within one or more `tf.name_scope` context managers respects the outer name scopes. So the same code running in the eager mode, but with a `Dense` instead of a `Sequential`:

```python
import tensorflow as tf

d = tf.keras.layers.Dense(units=10, name="d1")

with tf.name_scope("a"):
    with tf.name_scope("b"):
        d.build(input_shape=[32, 784])

for w in d.weights:
    print(w.name)
```

produces the following output:

```
a/b/kernel:0
a/b/bias:0
```

The outer name scope-related behaviour of `Sequential` and `Dense` are not consistent in the eager mode, which makes me thinking that this is a problem of `Sequential` that may still be isolated and fixed.

**Comment by aakhundov** [comment]
Any update on this one?

**Comment by sachinprasadhs** [comment]
Was able to reproduce issue in Tf Nightly 2.6.0-dev20210524, please find the gist [here](https://colab.research.google.com/gist/sachinprasadhs/9410c27b705aef776028261d057c54ce/35650.ipynb). Thanks!

**Comment by sanatmpa1** [comment]
Able to reproduce the issue in TF nightly `2.7.0-dev20210923`. Please find the [gist here](https://colab.research.google.com/gist/sanatmpa1/4c8e40108fa4ff4c91ca38e38c8a7afe/35650.ipynb).

**Comment by tensorflowbutler** [comment]
Hi There,

 This is a stale issue. As you are using an older version of tensorflow, we are checking to see if you still need help on this issue. Please test the issue with the latest TensorFlow (TF2.7 and tf-nightly). If the issue still persists with the newer versions of TF, please feel free to open it in [keras-team/keras](https://github.com/keras-team/keras/issues) repository by providing details about the issue and a standalone code to reproduce the issue. Thanks! 

 Please note that Keras development has moved to a separate Keras-team/keras repository to focus entirely on only Keras. Thanks!
