### ISSUE TITLE
If-Condition with TF-Bools looses track of namescopes

### ISSUE THREAD

**Issue by demmerichs** [tensorflow/tensorflow#36464]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes (see below)
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: no
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): tested on tf-gpu v2.0.0 and tf v2.1.0 (CPU as I do not have CUDA 10.1 running)
- Python version: 3.6.7
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 10.1/7.4.2
- GPU model and memory: tested on Nvidia Quadro P2000

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
When inside a function with graph mode activated, using an `if` statement with a tensorflow bool leads possibly to a new namescope. I assume this, because the observation one can make is that `tf.summary`s inside this if condition are placed inside different name scopes depending on whether the condition is a python bool (so static w.r.t. to the tensorflow graph) or a tensorflow tensor (resulting in a dynamic `tf.cond` through autograph). This happens for both v2.0 and v2.1, afaict. Of course, in eager mode this problem is non-existent.

**Describe the expected behavior**
The final summary scope should be independent of whether a autographed condition was used or a statically compiled one. Attached is a minimal working example producing a tensorboard output show in the image. The two lines are produced by the same `tf.summary.scalar` line inside the `tf.name_scope('monitoring')`. In this case it would be easy enough to move the name_scope creation inside the if-scope, however my use cases do not allow this kind of workaround (summaries are written inside keras layer calls which add their own respective namescope).

**Code to reproduce the issue**
```python
import os.path as osp

import tensorflow as tf


@tf.function
def func_with_summaries(step, write_summary):
    with tf.name_scope("monitoring"):
        if write_summary:
            tf.summary.scalar("step", step, tf.cast(step, dtype=tf.int64))


brok_writer = tf.summary.create_file_writer(
    osp.join("/tmp", "summaries_conds_scopes", "broken")
)
writer = tf.summary.create_file_writer(
    osp.join("/tmp", "summaries_conds_scopes", "correct")
)
st = tf.Variable(0.0, name="step", dtype=tf.float32)
for i in range(10):
    st.assign(i)
    with writer.as_default():
        func_with_summaries(st, i % 3 == 0)
    with brok_writer.as_default():
        func_with_summaries(st, tf.constant(i) % 3 == 0)
```
**Other info / logs**
![image](https://user-images.githubusercontent.com/6333870/73756641-3172cf00-4768-11ea-9ec8-31f003c0c049.png)

**Comment by DavidS3141** [comment]
I just found a workaround, but it is extremely hacky and I hope the underlying issue will still be fixed in the future.

```diff
+with tf.name_scope("") as root_scope:
+    pass


 @tf.function
 def func_with_summaries(step, write_summary):
-    with tf.name_scope("monitoring"):
+    with tf.name_scope("monitoring") as scope:
         if write_summary:
+            with tf.name_scope(root_scope):
+                with tf.name_scope(scope):
                     tf.summary.scalar("step", step, tf.cast(step, dtype=tf.int64))
```

**Comment by jvishnuvardhan** [comment]
@demmerichs Looks like this was resolved. Can you please check the [gist here](https://colab.research.google.com/gist/jvishnuvardhan/2d3f8f5ea449a7032f265e08b67b5929/untitled.ipynb). I ran your code with `TF2.4rc3`. 

Can you please verify and close the issue if this was already resolved for you. Thanks!
