### ISSUE TITLE
Mismatch in gradient of 'abs' for complex values

### ISSUE THREAD

**Issue by harpone** [tensorflow/tensorflow#3647]
... in the `def abs(x, name=None):` [here](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/ops/math_ops.py)

The abs correctly returns complex abs if the input is complex, but the gradient always returns `math_ops.sign(x)`. There seems to be a `_ComplexAbsGrad` though, so maybe that should be used?

Anyone have time for this? Clearly it's not that urgent (how many people are using complex valued tensors anyway), but maybe it should at least be flagged in the code...

**Comment by girving** [comment]
The gradient registry is based on the names of C++ ops, not the names of Python functions.  The code is correct.
