### ISSUE TITLE
tf.keras.utils.get_file issue

### ISSUE THREAD

**Issue by wenjieji86** [tensorflow/tensorflow#36475]
I am using Google Colab with tensorflow and I was trying to download files from my google cloud storage. I was able to download the files to Colab but somehow they are corrupted because I can not read or view the files. Even if I after I downloaded them from Colab to my own PC, I still couldn't open/read the files. But if download them directly from Cloud Storage to my PC, they are fine. The files I am dealing with are .tif files (satellite images). Here' the code to download the files: 
`import tensorflow as tf
tf.keras.utils.get_file("/root/image.tif","https://storage.cloud.google.com/project/image.tif")`

**Comment by ravikyram** [comment]
I tried uploading tif image to colab locally,then i am able to read the file.However by following the above commands I am able to download the files from google cloud storage but cannot read/view tif files.Thanks!

**Comment by gowthamkpr** [comment]
@wenjieji86 Tensorflow does not support (decode) .tif images. Please take a look at the code [here](https://github.com/tensorflow/tensorflow/blob/cf7fcf164c9846502b21cebb7d3d5ccf6cb626e8/tensorflow/core/kernels/decode_image_op.cc#L36)

If you want to use TIFF images, you could use a library like PIL or Pillow which can read TIFF images and convert them into a numpy array to feed into TensorFlow.

Please take a look at this issue [here](https://stackoverflow.com/questions/44706220/retraining-inception-with-tiff-images) for alternate solutions. Thanks!

**Comment by wenjieji86** [comment]
@gowthamkpr  OK, thanks.
