### ISSUE TITLE
Error when executing model.predict or model.evaluate even though Loading is successful

### ISSUE THREAD

**Issue by rakeshmothukuru1** [tensorflow/tensorflow#36480]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Issue is not specific to OS. Could be reproduced in Google Colab
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): N/A
- TensorFlow version (use command below): 1.15
- Python version: Colab Version
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

**Describe the current behavior**: I have Saved a Model using the command, `cnn_model.save('CNN_MNIST_Sequential.h5')`. Now, when I loaded that Model using `tf.keras.models.load_model('CNN_MNIST_Sequential.h5')`, it is loading properly and is showing the Trained Parameters when I ran `model.summary()`. But when I ran the command, `cnn_model.evaluate(X_test_reshaped,  y_test, verbose=2)` or `cnn_model.predict(X_test_reshaped).shape`, it is resulting in the below error.

> ValueError: When using data tensors as input to a model, you should specify the `steps` argument.

Reason for the error (not quite sure though) might be that the Model which is Saved (CNN_MNIST_Sequential.h5), was executed with `steps_per_epoch` and `validation_steps` as shown below,

```
history = cnn_model.fit(x = X_train_reshaped,
                        y = y_train,
                        batch_size = 512,
                        epochs = 5,
                        verbose = 1, validation_data = (X_test_reshaped, y_test),
                        validation_steps = 10, steps_per_epoch=steps_per_epoch)
```

**Describe the expected behavior**: Commands, `model.evaluate` and `model.predict` should run without error, as the Model is Loading Succesfully

**Code to reproduce the issue**: Please find Gist of my [Golab Colab](https://colab.sandbox.google.com/gist/rmothukuru/8b1639919d9e9eee2c8e95978fea8fc4/cnn_mnist_sequential_restored.ipynb).

**Comment by rakeshmothukuru1** [comment]
Please find the Saved Model, CNN_MNIST_Sequential.h5, attached.

[CNN_MNIST_Sequential.h5.zip](https://github.com/tensorflow/tensorflow/files/4157457/CNN_MNIST_Sequential.h5.zip)

**Comment by gadagashwini** [comment]
@rakeshmothukuru1, Please change the model.evaluate as
```
# Evaluate the restored model
loss, acc = cnn_model.evaluate(X_test_reshaped,  y_test, verbose=2, steps=1)
print('Restored model, accuracy: {:5.2f}%'.format(100*acc))
```
Or make change in model.fit as steps_per_epoch =None
Please find the [gist](https://colab.sandbox.google.com/gist/gadagashwini/22f8fdb707a98f871bf48fe916f68332/cnn_mnist_sequential_restored.ipynb). Thanks!

**Comment by rakeshmothukuru1** [comment]
@gadagashwini,
Thank you for the workaround but it works only for `model.evaluate` and `model.predict` is still resulting in error. Is it like, we can't use `model.predict` on the Restored Model?

**Comment by gadagashwini** [comment]
@rakeshmothukuru1, 
/model.fit  /model.evaluate and /model.predict will be provided with same input data. If any mismatch in the input data, ValueError will occur. Since in the `model.fit` verbose is set to 1, `model.predict` also expects verbose otherwise verbose default will be `None` in all the cases. 
Change the model.predict as 
`print(cnn_model.predict(X_test_reshaped, verbose=1, steps=1)) `

Please find the attached [gist](https://colab.research.google.com/gist/gadagashwini/005eb329625355452097978aa93a9513/untitled378.ipynb). Thanks!

**Comment by gadagashwini** [comment]
@rakeshmothukuru1, Are you happy to close this issue since its resolved. Thanks!

**Comment by rakeshmothukuru1** [comment]
Yes @gadagashwini . Thanks you.
