### ISSUE TITLE
Trying to install pytorch-neat - No such file or directory setup.py

### ISSUE THREAD

**Issue by DemiTownson26** [tensorflow/tensorflow#36483]
I've attempted to install pytorch-neat from https://github.com/uber-research/PyTorch-NEAT.git.
I cloned the repo which is now in C:\Users\username\AppData\Local\Continuum\anaconda3\pkgs\PyTorch-NEAT and the following command 
pip install git+https://github.com/uber-research/PyTorch-NEAT.git
which is giving the following error
 ERROR: Command errored out with exit status 1:
     command: 'c:\users\townsond\appdata\local\continuum\anaconda3\envs\petchem_py36\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\townsond\\AppData\\Local\\Temp\\pip-req-build-0krj5_3e\\setup.py'"'"'; __file__='"'"'C:\\Users\\townsond\\AppData\\Local\\Temp\\pip-req-build-0krj5_3e\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\townsond\AppData\Local\Temp\pip-req-build-0krj5_3e\pip-egg-info'
         cwd: C:\Users\townsond\AppData\Local\Temp\pip-req-build-0krj5_3e\
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "c:\users\townsond\appdata\local\continuum\anaconda3\envs\petchem_py36\lib\tokenize.py", line 452, in open
        buffer = _builtin_open(filename, 'rb')
    FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\townsond\\AppData\\Local\\Temp\\pip-req-build-0krj5_3e\\setup.py'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

I can see pytorch-neat does not have a setup.py file and I'm unsure on how to proceed from here.
I'm using Python 3.6 and have upgraded both setuptools and pip, and tried pip3 install also.

Any help appreciated!

**Comment by DemiTownson26** [comment]
FWIW for now I can put the pytorch_neat file into my source and use it that way, but if there is a way of installing it I would like to know

**Comment by amahendrakar** [comment]
@DemiTownson26,
Looks like you are facing issues with PyTorch. Could you please confirm if this issue is related to TensorFlow? Thanks!

**Comment by amahendrakar** [comment]
Any updates regarding this issue? Thanks!
