### ISSUE TITLE
Hamburger menu no longer appears on mobile

### ISSUE THREAD

**Issue by davidzchen** [tensorflow/tensorflow#365]
I noticed that the hamburger menu no longer appears on mobile:

<img width="400" alt="screen shot 2015-11-26 at 9 20 26 pm" src="https://cloud.githubusercontent.com/assets/5283042/11434590/a97d28de-9483-11e5-9587-70a6a1b45e79.png">

**Comment by ebrevdo** [comment]
+ @craigcitro

**Comment by craigcitro** [comment]
@martinwicke probably knows more about the details here ...

**Comment by martinwicke** [comment]
We disabled the more involved navigation features on mobile to expedite moving to the new website.

**Comment by davidzchen** [comment]
Understood. I'll look forward to seeing the new website.

**Comment by martinwicke** [comment]
You are seeing the new website, which we launched without the hamburger menu in order to launch it quicker. :)

**Comment by girving** [comment]
@martinwicke: Do we have hamburgers again?

**Comment by martinwicke** [comment]
No. All we have is this issue and @danmane.

**Comment by martinwicke** [comment]
Will likely happen once we move doc systems again.

**Comment by michaelisard** [comment]
@martinwicke: Any update on this?

**Comment by martinwicke** [comment]
Will be dealt with in our move to new website infrastructure. We can close this as obsolete -- we won't work on this.
