### ISSUE TITLE
How to use prepare_for_training with model.fit

### ISSUE THREAD

**Issue by HadiSDev** [tensorflow/tensorflow#36507]
## URL(s) with the issue: 

https://www.tensorflow.org/tutorials/load_data/images

## Description of issue (what needs changing):

I have been spending a lot of time trying to figure out how I can use the batch map to train my model. Which method should I use model.fit, model.fit_generator or something else

**Comment by ravikyram** [comment]
@HadiSDev 

Can you go through this [link](https://www.tensorflow.org/tutorials/images/classification#data_preparation) and see if it helps you. Thanks!
