### ISSUE TITLE
ValueError when trying to speed up model by decorating tf.function

### ISSUE THREAD

**Issue by hgffly** [tensorflow/tensorflow#36504]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- TensorFlow installed from (source or binary): pip
- TensorFlow version (use command below): 2.1.0
- Python version:  3.6.7
- CUDA/cuDNN version:  7.6.5
- GPU model and memory:  GTX1660Ti , 6GB

**Describe the current behavior**

    Traceback (most recent call last):
    File "model_test.py", line 12, in <module>
        output = ModelTest(input_layer)
    File "/home/wilson/venv_tf2.0/lib/python3.6/site-packages/tensorflow_core/python/eager/def_function.py", line 568, in __call__
        result = self._call(*args, **kwds)
    File "/home/wilson/venv_tf2.0/lib/python3.6/site-packages/tensorflow_core/python/eager/def_function.py", line 632, in _call
        return self._stateless_fn(*args, **kwds)
    File "/home/wilson/venv_tf2.0/lib/python3.6/site-packages/tensorflow_core/python/eager/function.py", line 2362, in __call__
        graph_function, args, kwargs = self._maybe_define_function(args, kwargs)
    File "/home/wilson/venv_tf2.0/lib/python3.6/site-packages/tensorflow_core/python/eager/function.py", line 2703, in _maybe_define_function
        graph_function = self._create_graph_function(args, kwargs)
    File "/home/wilson/venv_tf2.0/lib/python3.6/site-packages/tensorflow_core/python/eager/function.py", line 2593, in _create_graph_function
        capture_by_value=self._capture_by_value),
    File "/home/wilson/venv_tf2.0/lib/python3.6/site-packages/tensorflow_core/python/framework/func_graph.py", line 978, in func_graph_from_py_func
        func_outputs = python_func(*func_args, **func_kwargs)
    File "/home/wilson/venv_tf2.0/lib/python3.6/site-packages/tensorflow_core/python/eager/def_function.py", line 439, in wrapped_fn
        return weak_wrapped_fn().__wrapped__(*args, **kwds)
    File "/home/wilson/venv_tf2.0/lib/python3.6/site-packages/tensorflow_core/python/framework/func_graph.py", line 968, in wrapper
        raise e.ag_error_metadata.to_exception(e)
    ValueError: in converted code:

        model_test.py:8 ModelTest  *
            x = tf.keras.layers.Dense(10)(x)
        /home/wilson/venv_tf2.0/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/base_layer.py:748 __call__
            self._maybe_build(inputs)
        /home/wilson/venv_tf2.0/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/base_layer.py:2116 _maybe_build
            self.build(input_shapes)
        /home/wilson/venv_tf2.0/lib/python3.6/site-packages/tensorflow_core/python/keras/layers/core.py:1113 build
            trainable=True)
        /home/wilson/venv_tf2.0/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/base_layer.py:446 add_weight
            caching_device=caching_device)
        /home/wilson/venv_tf2.0/lib/python3.6/site-packages/tensorflow_core/python/training/tracking/base.py:744 _add_variable_with_custom_getter
            **kwargs_for_getter)
        /home/wilson/venv_tf2.0/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/base_layer_utils.py:142 make_variable
            shape=variable_shape if variable_shape else None)
        /home/wilson/venv_tf2.0/lib/python3.6/site-packages/tensorflow_core/python/ops/variables.py:258 __call__
            return cls._variable_v1_call(*args, **kwargs)
        /home/wilson/venv_tf2.0/lib/python3.6/site-packages/tensorflow_core/python/ops/variables.py:219 _variable_v1_call
            shape=shape)
        /home/wilson/venv_tf2.0/lib/python3.6/site-packages/tensorflow_core/python/ops/variables.py:65 getter
            return captured_getter(captured_previous, **kwargs)
        /home/wilson/venv_tf2.0/lib/python3.6/site-packages/tensorflow_core/python/eager/def_function.py:502 invalid_creator_scope
            "tf.function-decorated function tried to create "

        ValueError: tf.function-decorated function tried to create variables on non-first call.

**Describe the expected behavior**

    print the inference results as below:
    tf.Tensor( [[ 1.5871892   1.028789    0.6445342  -1.9210143  -1.7477174   3.1219487
   1.8073429   2.62254    -0.01772228 -2.2654278 ]], shape=(1, 10), dtype=float32)

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

    import numpy as np
    import tensorflow as tf
    from tensorflow.keras.layers import Flatten, Dense
   
    @tf.function  # with this, it will raise error listed above
    def ModelTest(input_layer):
        x = Flatten()(input_layer)
        x = tf.keras.layers.Dense(10)(x)
        return x

    input_layer = tf.keras.layers.Input([32, 32, 3])
    output = ModelTest(input_layer)
    model = tf.keras.Model(input_layer, output)

    a = np.ones([1, 32, 32, 3])
    print(model(a))

I try to run YOLOv3 by TF2, but it's so slow compared to other framework, can be seen from the following table.
![image](https://user-images.githubusercontent.com/20164141/73921384-31a6d200-4902-11ea-9162-d6207f60b425.png)

So by a naive example, I just want to speed up the inference of the model by decorating ModelTest with tf.function, but it will raise error. How should I fix this error or are there other ways to speed up the model? Thanks

**Comment by ravikyram** [comment]
I have tried on colab with TF version 2.1, 2.2.0-dev20200206 and was able to reproduce the issue.Please, find the gist [here](https://colab.research.google.com/gist/ravikyram/6f460f8bbf48b3b697a5fec56f9a6a16/untitled625.ipynb). Thanks1

**Comment by mdanatg** [comment]
The error is raised because tf.function doesn't like it when you create variables inside it. In this case, the Keras layers are attempting to create variables so you should create those outside the tf.function.

On the other hand, I don't know if this is the recommended way of creating layers. @fchollet @omalleyt12 can give better advice there.

Also copying @karmel for the performance question.

Here are a couple of ways in which you can build your example model that I tested myself. In both cases, tf.function should be applied automatically:

Functional style:
```
input_layer = tf.keras.layers.Input([32, 32, 3])
model = tf.keras.models.Sequential(
    [input_layer, Flatten(), tf.keras.layers.Dense(10)])

a = np.ones([1, 32, 32, 3], dtype=np.float32)
print(model(a))
```

Object-oriented style:
```
class KerasModel(tf.keras.models.Model):

  def __init__(self):
    super(KerasModel, self).__init__()
    self.flatten = Flatten()
    self.dense = tf.keras.layers.Dense(10)

  def call(self, input_layer):
    x = input_layer
    x = self.flatten(x)
    x = self.dense(x)
    return x

model = KerasModel()

a = np.ones([1, 32, 32, 3], dtype=np.float32)
print(model(a))
```

You can also customize the way the code is optimized by adding `@tf.function` manually. For example the code below will use XLA (if available in your installation) which is usually faster:

```
class KerasModel(tf.keras.models.Model):

  def __init__(self):
    super(KerasModel, self).__init__()
    self.flatten = Flatten()
    self.dense = tf.keras.layers.Dense(10)

  @tf.function(experimental_compile=True)
  def call(self, input_layer):
    x = input_layer
    x = self.flatten(x)
    x = self.dense(x)
    return x

model = KerasModel()

a = np.ones([1, 32, 32, 3], dtype=np.float32)
print(model(a))
```

**Comment by omalleyt12** [comment]
Yes this is intended behavior. `tf.function` should not be used when constructing a Functional API Model. `tf.function` should only be used when running the actual training of the Model:

```
model = tf.keras.Model(inputs, outputs)

@tf.function
def train_step(x, y):
  y_pred = model(x)
  ...
```

**Comment by hgffly** [comment]
Sorry to ask one more question. Does tf.function apply to the model built by Keras Functional API automatically?


    import numpy as np
    import tensorflow as tf
    from tensorflow.keras.layers import Flatten, Dense

    @tf.function  # <= Is this decoration uncessary ? 
    def ModelTest(input_layer):
        x = Flatten()(input_layer)
        x = tf.keras.layers.Dense(10)(x)
        return x

    input_layer = tf.keras.layers.Input([32, 32, 3])
    output = ModelTest(input_layer)
    model = tf.keras.Model(input_layer, output)  # Does this model apply tf.function automatically?


I read a model from this tutorial page. Is this model already applied tf.function?
https://www.tensorflow.org/guide/keras/functional#all_models_are_callable_just_like_layers

**Comment by monicadsong** [comment]
No, I don't think that `tf.function` automatically applies to Keras layers, see the example using `tf.keras.layers.Conv2d` in https://www.tensorflow.org/guide/function#usage as well as the`SequentialModel` in https://www.tensorflow.org/guide/intro_to_graphs#seeing_the_speed_up. All the solutions above work, but if you want another way to apply  `tf.function` to `ModelTest`, you can decorate the `call` function like so:
```
class ModelTest(tf.keras.layers.Layer):

  def __init__(self):
    super(ModelTest, self).__init__()
    self.flatten = Flatten()
    self.dense = tf.keras.layers.Dense(10)

  @tf.function
  def call(self, input_layer):
    x = input_layer
    x = self.flatten(x)
    x = self.dense(x)
    return x

input_layer = tf.keras.layers.Input([32, 32, 3])
output_layer = ModelTest()(input_layer)
model = tf.keras.Model(input_layer, output_layer)
```
