### ISSUE TITLE
Cannot perform full-integer post-training quantization in converting to flite models

### ISSUE THREAD

**Issue by feranick** [tensorflow/tensorflow#36513]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Both
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): MacOS, Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: No
- TensorFlow installed from (source or binary): either
- TensorFlow version (use command below): 1.15.2
- Python version: 3
- Bazel version (if compiling from source): 0.26.1
- GCC/Compiler version (if compiling from source): - 
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

**Describe the current behavior**
The issue relates to full integer post-training quantization in tflite conversion. Following the same example in the [documentation](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/g3doc/performance/post_training_integer_quant.ipynb), but applied to my data have issues when I identify the input_data for the interpreter as float32 (below my data in R is in float32 already normalized between [0,10]):

`input_data = np.array(R, dtype=np.float32)`
`interpreter.set_tensor(input_details[0]['index'], input_data)`
 `interpreter.invoke()`

When then I call the TFLite converter (using `tf.compat.v1.lite.TFLiteConverter.from_keras_model_file` in TF2.x or `tf.lite.TFLiteConverter.from_keras_model_file` in TF1.x) again following from the documentation:

`converter.optimizations = [tf.lite.Optimize.OPTIMIZE_FOR_SIZE]`
    `converter.representative_dataset = representative_dataset_gen`
    `converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]`
    `converter.inference_input_type = tf.uint8`
    `converter.inference_output_type = tf.uint8`
    `tflite_quant_model = converter.convert()`

The post-quantized tflite is correctly created (and when compiled for the TPU, all ops are correctly assigned). However, when I run a prediction, I get the following error:
`ValueError: Cannot set tensor: Got value of type FLOAT32 but expected type UINT8 for input 16, name: conv2d_input`

Essentially, the `input_data = np.array(R, dtype=np.float32)`, needs to be set as uint8 for this to work. However, that breaks the model completely, as it casts all data between [0,1] into just zeros. 

To be clear, this does NOT happen when using TF2.x, by calling the converter with `tf.lite.TFLiteConverter.from_keras_model()`. Using the `input_data = np.array(R, dtype=np.float32)`, the post-training quantized tflite model is created and when used for predictions, it works as intended. However, when compiled, because I am using the `TFLiteConverterV2` , the quantization/dequantization ops are not assigned to the TPU, making it useless to deploy in embedded devices that require full integer quantization.

Any insight is greatly appreciated. Thanks in advance.

**Comment by feranick** [comment]
The same issue can be reproduces with a slightly modified [code in the documentation](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/g3doc/performance/post_training_integer_quant.ipynb). Please see the attachment (it's obviously python3 code, despite the txt extension to allow upload). 

When line 52 is uncommented and line 55 is commented the code works. 
When line 52 is commented and line 55 is uncommented, the code does not work and gives the same error message in the previous comment:

`ValueError: Cannot set tensor: Got value of type FLOAT32 but expected type UINT8 for input 11, name: reshape_input `

[test_issue_36513.txt](https://github.com/tensorflow/tensorflow/files/4165369/test_issue_36513.txt)

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.
