### ISSUE TITLE
Provide complete tutorial on how to use MultiWorkerMirroredStrategy

### ISSUE THREAD

**Issue by Flamefire** [tensorflow/tensorflow#36515]
## URL(s) with the issue:

https://www.tensorflow.org/tutorials/distribute/multi_worker_with_keras#train_the_model_with_multiworkermirroredstrategy

## Description of issue (what needs changing):

There is a large and often overlooked caveat: You need to pass `steps_per_epoch`. This leads to issues like https://github.com/tensorflow/tensorflow/issues/34821, https://github.com/tensorflow/tensorflow/issues/36153. It should be explained, how `steps_per_epoch` should be set. Searching the examples does not really help: `num_samples / batch_size` is sometimes rounded up and sometimes down. A clear guideline for Multi-Worker would be appreciated.

Also it is not described how loading the dataset should happen. Doing that in a Multi-Worker setting is tricky as the data needs to be downloaded exactly once. See https://github.com/tensorflow/datasets/issues/1302

Also the developers of `tensorflow_datasets` claim, that the auto-sharding done by TF won't work properly and suggest to use custom functions: https://github.com/tensorflow/datasets/issues/1302, https://github.com/tensorflow/datasets/issues/1426. It should be evaluated whether this is the case and where this has to be addressed.

Finally a description on how to run the evaluation is missing for completeness. This runs into another issue that by default files are sharded and e.g. MNIST only has 1 file for test data which makes TF fail. See also https://github.com/tensorflow/datasets/issues/1405

For the last point the solution is to use 

```
options = tf.data.Options()
options.experimental_distribute.auto_shard_policy = tf.data.experimental.AutoShardPolicy.DATA
train_datasets = train_datasets.with_options(options)
```
Which can be found by searching the docs. But it needs to be in the tutorial (and maybe even the default)

**Comment by nikitamaia** [comment]
Thank you for the feedback. For the first point, the third note in the [tutorial you linked to](https://www.tensorflow.org/tutorials/distribute/multi_worker_with_keras#train_the_model_with_multiworkermirroredstrategy) includes a description for how to set steps_per_epoch. Can you clarify what specifically is unclear about the explanation? Would like to understand if the explanation is unclear, or if an example is needed, or if you think this information should exist somewhere other than just the tutorial.

**Comment by Flamefire** [comment]
That third point does indeed help and seems to be new. It is quit good except of a few typos (e.g. `should be set to the size of the smallest *sharded* *devided*`)

My suggestion was that it is not fully clear how that value should be set when you are given a dataset with a size (# examples/batches). The example on the linked page uses a hard-coded value (which is IMO bad style [see magic numbers] especially for a tutorial) Now try to search the docs for `steps_per_epoch` like a user looking for help would do. He'd find code like `steps_per_epoch = np.ceil(image_data.samples/image_data.batch_size)`, `np.ceil(image_count/BATCH_SIZE)`, and `train_generator.samples // train_generator.batch_size` As you can see this is inconsistent without any given reason. So for a user it is hard to tell what the right way is.

I learnt through experimentation and parallel study of the docs that `MultiWorkerMirroredStrategy` doesn't work with trailing batches so the "round down" semantic of the last example is correct for this use case.

So 3 improvements here:
- Show `steps_per_epoch = train_generator.samples // train_generator.batch_size`-like code in the linked tutorial
- Explain the implications (e.g. with growing number of workers and batch sizes an increasing number of images from an epoch won't be handled) and why round-down (yes it is mentioned in the third point so that could be referenced)
- make the other examples consistent and explain why ceil/floor semantic is used

**Comment by saikumarchalla** [comment]
@Flamefire  closing the issue since  the documentation was updated. Please feel  free to re-open the issue  if necessary. Thanks!

**Comment by StephaneKazmierczak** [comment]
It seems like the explanation about steps_per_epoch was removed from the tutorial, now it is just some random hard coded values. I had lots of problems setting up steps_per_epoch for multi worker strategy in context of multi nodes as it also change the behavior of how the dataset is iterated over.
