### ISSUE TITLE
bfloat16 does not flush denormals (subnormal floats) to zero

### ISSUE THREAD

**Issue by N-Dekker** [tensorflow/tensorflow#36514]
[BFloat16: The secret to high performance on Cloud TPUs](https://cloud.google.com/blog/products/ai-machine-learning/bfloat16-the-secret-to-high-performance-on-cloud-tpus), Shibo Wang, Pankaj Kanwar (@pkanwar23 right?) , August 23, 2019, says:

> bfloat16 handles denormals differently from FP32: it flushes them to zero

I assume this implies that for a denormal 32-bit floating point, `denorm`, the expression `float{bfloat16{denorm}}` should be equal to zero.

The current implementation of `tensorflow::bfloat16` (master branch, revision bc28d49ce2659f846e03c13a64ebe83fc6fb8ff1) appears to behave differently. As can be observed by the following test:

    for (float denorm = std::numeric_limits<float>::denorm_min();
      denorm < std::numeric_limits<float>::min();
      denorm = std::nextafterf(denorm, 1.0f))
        ASSERT_EQ(float{ tensorflow::bfloat16{denorm} }, 0.0f);

This assertion fails on the current implementation, from [tensorflow/core/lib/bfloat16](https://github.com/tensorflow/tensorflow/tree/bc28d49ce2659f846e03c13a64ebe83fc6fb8ff1/tensorflow/core/lib/bfloat16)

Is that indeed a bug in `tensorflow::bfloat16`?

**Comment by N-Dekker** [comment]
Looks like this issue was addressed by @tensorflower-gardener, Mar 20, 2020, "Flush denormals to +/- 0 when converting float to bfloat16." https://github.com/tensorflow/tensorflow/commit/b04c4e0e4338924d5281626445594a900bd673a6 right?

**Comment by jvishnuvardhan** [comment]
@N-Dekker Yes, This was addressed on Mar 20. Can you please verify once and close the issue if this was resolved for you. Thanks!

**Comment by N-Dekker** [comment]
Just verified! This is indeed resolved! I'll close the issue!

FYI, I tried the [bfloat16.DenormalFloatsConvertToZero](https://github.com/biovault/biovault_bfloat16/blob/b145861475eb9cf7cff952475b98828c8435561a/biovault_bfloat16_test.cpp#L193) unit test that I wrote before for `biovault::bfloat16_t` on your `tensorflow::bfloat16` struct and it passed just fine now  👍  Thank you @jvishnuvardhan and @tensorflower-gardener

**Comment by N-Dekker** [comment]
For the record: This issue appears related to Eigen merge request "remove denormal flushing in fp32tobf16 for avx & avx512", https://gitlab.com/libeigen/eigen/-/merge_requests/580 by Gauri Deshpande (@gaurides)
