### ISSUE TITLE
No such package '@iron_list (Device or resource busy)

### ISSUE THREAD

**Issue by natalieparde** [tensorflow/tensorflow#3652]
### Environment info
**Operating System:** Ubuntu 12.04

**Installed from source:**
**Commit Hash:** c5f94b10bbb30e525fa3ca313e7ccb173040c90a
**Output of "bazel version":**
WARNING: Output base '/home/user1/.cache/bazel/_bazel_user1/d49ce44fa50589aa9a9d880466ef1baf' is on NFS. This may lead to surprising failures and undetermined behavior.
Build target: bazel-out/local-fastbuild/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Thu Jan 01 00:00:00 1970 (0)
Build timestamp: Thu Jan 01 00:00:00 1970 (0)
Build timestamp as int: 0

Note: Not sure why the actual version doesn't appear in the output, but it is 0.2.2b.

**### Steps to reproduce**
1. git clone https://github.com/tensorflow/tensorflow
2. Installed Bazel
3. Installed other dependencies
4. ./configure
5. /usr/bin/python
6. N
7. N (Note: After this, the configuration ended.)
8. bazel build -c opt //tensorflow/tools/pip_package:build_pip_package

**Error Message:**
ERROR: /home/user1/Documents/tensorflow/tensorflow/tensorboard/bower/BUILD:5:1: no such package '@iron_list//': /home/user1/.cache/bazel/_bazel_user1/d49ce44fa50589aa9a9d880466ef1baf/external/iron_list/.git/objects/pack/.nfs000000000189638500000904 (Device or resource busy) and referenced by '//tensorflow/tensorboard/bower:bower'.
ERROR: Analysis of target '//tensorflow/tools/pip_package:build_pip_package' failed; build aborted.

### What have you tried?
1. Downloaded the necessary files locally and linked to them in tensorflow/WORKSPACE, as well as in tensorflow/tensorflow/tensorboard/bower/BUILD, with no success (Note: This is my first time using bazel, so I may not have done this correctly.).
2. Googled the error; although many people seem to have bower-related errors with respect to downloading the files from GitHub, this seems to be a different type of error.
3. Reran the command many times.
4. Reinstalled nodejs, npm, and then bower on the computer and reran the command again.

### Logs or other output that would be helpful
**Full Log:**
> bazel build -c opt //tensorflow/tools/pip_package:build_pip_package
WARNING: Output base '/home/user1.cache/bazel/_bazel_user1/d49ce44fa50589aa9a9d880466ef1baf' is on NFS. This may lead to surprising failures and undetermined behavior.
WARNING: Sandboxed execution is not supported on your system and thus hermeticity of actions cannot be guaranteed. See http://bazel.io/docs/bazel-user-manual.html#sandboxing for more information. You can turn off this warning via --ignore_unsupported_sandboxing.
WARNING: /home/user1/Documents/tensorflow/util/python/BUILD:11:16: in includes attribute of cc_library rule //util/python:python_headers: 'python_include' resolves to 'util/python/python_include' not in 'third_party'. This will be an error in the future.
WARNING: /home/user1/.cache/bazel/_bazel_user1/d49ce44fa50589aa9a9d880466ef1baf/external/gemmlowp/BUILD:102:12: in hdrs attribute of cc_library rule @gemmlowp//:eight_bit_int_gemm: Artifact 'external/gemmlowp/public/bit_depth.h' is duplicated (through '@gemmlowp//:eight_bit_int_gemm_public_headers' and '@gemmlowp//:gemmlowp_headers').
WARNING: /home/user1/.cache/bazel/_bazel_user1/d49ce44fa50589aa9a9d880466ef1baf/external/gemmlowp/BUILD:102:12: in hdrs attribute of cc_library rule @gemmlowp//:eight_bit_int_gemm: Artifact 'external/gemmlowp/public/gemmlowp.h' is duplicated (through '@gemmlowp//:eight_bit_int_gemm_public_headers' and '@gemmlowp//:gemmlowp_headers').
WARNING: /home/user1/.cache/bazel/_bazel_user1/d49ce44fa50589aa9a9d880466ef1baf/external/gemmlowp/BUILD:102:12: in hdrs attribute of cc_library rule @gemmlowp//:eight_bit_int_gemm: Artifact 'external/gemmlowp/public/map.h' is duplicated (through '@gemmlowp//:eight_bit_int_gemm_public_headers' and '@gemmlowp//:gemmlowp_headers').
WARNING: /home/user1/.cache/bazel/_bazel_user1/d49ce44fa50589aa9a9d880466ef1baf/external/gemmlowp/BUILD:102:12: in hdrs attribute of cc_library rule @gemmlowp//:eight_bit_int_gemm: Artifact 'external/gemmlowp/public/output_stages.h' is duplicated (through '@gemmlowp//:eight_bit_int_gemm_public_headers' and '@gemmlowp//:gemmlowp_headers').
WARNING: /home/user1/.cache/bazel/_bazel_user1/d49ce44fa50589aa9a9d880466ef1baf/external/gemmlowp/BUILD:102:12: in hdrs attribute of cc_library rule @gemmlowp//:eight_bit_int_gemm: Artifact 'external/gemmlowp/profiling/instrumentation.h' is duplicated (through '@gemmlowp//:eight_bit_int_gemm_public_headers' and '@gemmlowp//:gemmlowp_headers').
WARNING: /home/user1/.cache/bazel/_bazel_user1/d49ce44fa50589aa9a9d880466ef1baf/external/gemmlowp/BUILD:102:12: in hdrs attribute of cc_library rule @gemmlowp//:eight_bit_int_gemm: Artifact 'external/gemmlowp/profiling/profiler.h' is duplicated (through '@gemmlowp//:eight_bit_int_gemm_public_headers' and '@gemmlowp//:gemmlowp_headers').
ERROR: /home/user1/Documents/tensorflow/tensorflow/tensorboard/bower/BUILD:5:1: no such package '@iron_list//': /home/user1/.cache/bazel/_bazel_user1/d49ce44fa50589aa9a9d880466ef1baf/external/iron_list/.git/objects/pack/.nfs000000000189638500000904 (Device or resource busy) and referenced by '//tensorflow/tensorboard/bower:bower'.
ERROR: Analysis of target '//tensorflow/tools/pip_package:build_pip_package' failed; build aborted.
INFO: Elapsed time: 0.374s

**Additional Information:**
The package name in the error message rotates between iron_list, iron_icon, and iron_icons each new time the command is run.

Not sure whether this is relevant, but I am able to run the following commands for syntaxnet:
git clone --recursive https://github.com/tensorflow/models.git
cd models/syntaxnet/tensorflow
./configure
cd ..
bazel test syntaxnet/... util/utf8/...

with all tests reported as being passed.  The only changes made to the included files in order to pass all tests successfully were to:
1. Download gmock-1.7.0.zip manually, run the command: "python -m SimpleHTTPServer 8000", and change line 79 of workspace.bzl to: "url = "http://localhost:8000/gmock-1.7.0.zip","
2. Change line 25 of models/syntaxnet/syntaxnet/parser_trainer_test.sh to: "BINDIR=$TEST_SRCDIR/$TEST_WORKSPACE/syntaxnet"

Please let me know if you require any other information!  Thanks in advance for your help.

-Natalie

**Comment by mrry** [comment]
This part of the log might have something to do with it:

> WARNING: Output base '/home/user1/.cache/bazel/_bazel_user1/d49ce44fa50589aa9a9d880466ef1baf' is on NFS. This may lead to surprising failures and undetermined behavior.

I think the appropriate resolution is to pass the flag `--output_base=/tmp/some/other/dir` (for example) to the `bazel build` command.

**Comment by natalieparde** [comment]
That worked!  Thank you so much for your help; I hadn't thought to just try changing the output base.

I appreciate your help!

**Comment by mrry** [comment]
Glad to hear it!
