### ISSUE TITLE
Tensorflow-gpu running issue: CUDA_UNKNOWN_ERROR

### ISSUE THREAD

**Issue by tawej** [tensorflow/tensorflow#36535]
With:

* Tensorflow-gpu 2.0.0
* Windows 10 environment
* NVIDIA GTX 1050 gpu
* cuda 10.0 and corresponding cudnn 7.6.5

I followed the official TF documentation for TF-gpu and I've tried to create and fit a simple CNN model (on a.py file, I've tried with a jupyter but the kernel always dies) but I got the following:

```
2020-02-06 23:57:14.420911: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_100.dll
2020-02-06 23:57:16.081396: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library nvcuda.dll
2020-02-06 23:57:16.861094: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties: 
name: GeForce GTX 1050 major: 6 minor: 1 memoryClockRate(GHz): 1.493
pciBusID: 0000:01:00.0
2020-02-06 23:57:16.861492: I tensorflow/stream_executor/platform/default/dlopen_checker_stub.cc:25] GPU libraries are statically linked, skip dlopen check.
2020-02-06 23:57:16.862290: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0
[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]
2020-02-06 23:58:14.322053: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
2020-02-06 23:58:14.324900: F tensorflow/stream_executor/lib/statusor.cc:34] Attempting to fetch value instead of handling error Internal: failed to get device attribute 13 for device 0: CUDA_ERROR_UNKNOWN: unknown error
```

**Comment by ravikyram** [comment]
@tawej 

Can you please go through the [issue](https://github.com/tensorflow/tensorflow/issues/19266#issuecomment-399686258) and see if it helps you. If those solutions doesn't work, could you uninstall and reinstall CUDA and cuDNN? Please let us know how it progresses. Also, try to uninstall and reinstall tensorflow-gpu and try following the instructions from [TensorFlow website.](https://www.tensorflow.org/install/source_windows#setup_for_windows)
Also, see 
See https://devtalk.nvidia.com/default/topic/749939/cuda-is-not-active-unless-i-run-it-with-sudo-privillages-/ . Thanks!

**Comment by tawej** [comment]
Hello @ravikyram 
The attached issue is for ubuntu system while mine is windows 10....
This said I tired to uninstall all and  reinstall but it seems to be persisting...

**Comment by tawej** [comment]
I've tried to install python 3.6.8 but still having the same error message. Would you recommend working with TF 2.1.0 and cuda 10.1 or not?

**Comment by jvishnuvardhan** [comment]
@tawej Did you install all compatible drivers as mentioned in TF website.

Version | Python version | Compiler | Build tools | cuDNN | CUDA
-- | -- | -- | -- | -- | --
tensorflow_gpu-2.0.0 | 3.5-3.7 | MSVC 2017 | Bazel 0.26.1 | 7.4 | 10

Can you please try some instructions mentioned in this [resolved issue](https://github.com/tensorflow/tensorflow/issues/26227) and [this issue](https://github.com/tensorflow/tensorflow/issues/26182). Also check [this resource](https://github.com/tensorflow/tensorflow/issues/26182#issuecomment-472674508). Windows10 has another issue limiting path length of a folder. Please check [this resource](https://github.com/tensorflow/tensorflow/issues/24705#issuecomment-456498716) for resolving that kind of problems.

Please let us know how it progresses. I would also suggest you to go ahead and install TF2.1 which is better than 2.0 interms of performance. Thanks!

**Comment by tawej** [comment]
Thanks I'll keep you updated

**Comment by tawej** [comment]
python 3.7.6
TF-gpu 2.1.0
cuda 10.1
cudnn 7.6.5 for cuda 10.1
MSVC 2017
It's working, at least with a tf basic mnist classification :)

**Comment by jvishnuvardhan** [comment]
@tawej I think it should work with other complex models also. I guess there might have been some issue with compatibility between different dependencies. Thanks!

I will close this issue as it was resolved. Feel free to reopen if the issue persists again. Thanks!

**Comment by karnn** [comment]
> 
> 
> python 3.7.6
> TF-gpu 2.1.0
> cuda 10.1
> cudnn 7.6.5 for cuda 10.1
> MSVC 2017
> It's working, at least with a tf basic mnist classification :)

Thank you for this. I had the same issue and I reinstalled everything from your list. When I tried again I had the exact same issue again. But once I restarted my laptop it all worked again

**Comment by tawej** [comment]
Great ! Adding environment variables requires restart ;)

**Comment by btschwertfeger** [comment]
Reinstalling or upgrading did not work for me, but I found out that somehow I messed up my CUDA drivers. I'm using Ubuntu 22.04 with an NVIDIA RTX 4070 TI Super and had to reinstall all those drivers and reboot.
