### ISSUE TITLE
Could not download data for "data = tensorflow_datasets.load('glue/mrpc')"

### ISSUE THREAD

**Issue by zysNLP** [tensorflow/tensorflow#36538]
This template is for miscellaneous issues not covered by the other issue categories.
There is nothing about this in stackflow, Thanks!

Since I execute "data = tensorflow_datasets.load('glue/mrpc')" for downloading data. It occurs:

ConnectionError: HTTPSConnectionPool(host='firebasestorage.googleapis.com', port=443): Max retries exceeded with url: /v0/b/mtl-sentence-representations.appspot.com/o/data%2Fmrpc_dev_ids.tsv?alt=media&token=ec5c0836-31d5-48f4-b431-7480817f1adc (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fa45008db38>: Failed to establish a new connection: [Errno 101] Network is unreachable',))

I am from China, so maybe I have a useless network for this.
Could you please tell me how to load this mprc data by offline? I have download them and keep files like "msr_paraphrase_train.txt" and I also turned them to tsv like:

Quality #1 ID #2 ID #1 String #2 String |  
-- | --
1 1355540 1355592 He said the foodservice pie business doesn 't fit the company 's long-term growth strategy . " The foodservice pie business does not fit our long-term growth strategy . |  
0 2029631 2029565 Magnarelli said Racicot hated the Iraqi regime and looked forward to using his long years of training in the war . His wife said he was " 100 percent behind George Bush " and looked forward to using his years of training in the war . |  

Thank you very much!

**Comment by gadagashwini** [comment]
@zysNLP, If it is text file, open the text using python as 
`file = open('msr_paraphrase_train.txt','r')`.
Thanks!

**Comment by zysNLP** [comment]
Thank you. Do you mean this "file = open("mspr.txt', 'r')" is equal to "data = tensorflow_datasets.load('glue/mrpc')"? So here "file" and "data" share the same type?

Excuse me for ask this sample question since I have not execute tensorflow_datasets successfully.

**Comment by gadagashwini** [comment]
@zysNLP, TensorFlow Datasets exposes the public research datasets as `tf.data.Datasets` for more read [here](https://blog.tensorflow.org/2019/02/introducing-tensorflow-datasets.html). 
file = open("mspr.txt', 'r'), this reads the content of text file later can be used as train and test dataset. Thanks!

**Comment by gadagashwini** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
