### ISSUE TITLE
load_weights problem in Tensorflow.keras.

### ISSUE THREAD

**Issue by houzeyu2683** [tensorflow/tensorflow#36537]
Environment
Win10
Conda python 3.7
tensorflow version is 2.0.0.

Using `ModelCheckpoint` and `save_weights_only=True` to save the weights of best model when training model. Using `model.to_json()` save the structure of model.

It's successful to loading model structure from json file, the `model.summary()` is work.
But the problem is when I use `model.load_weigths(weight_path)`, I get `<tensorflow.python.training.tracking.util.CheckpointLoadStatus at 0x2d871057cc8>
`. And the `summary()` is not work and I cannot use `model.predict` function in this return.

Load model structure from json is work. no problem.
![A](https://user-images.githubusercontent.com/42731603/74031411-668f5380-49ec-11ea-98ea-ec173d5b2f6f.PNG)

Load weights, this problem happen here.
![B](https://user-images.githubusercontent.com/42731603/74031416-6a22da80-49ec-11ea-9839-da8df2e2b891.PNG)

My weight folder, it from checkpoint and save weights only is true.
![C](https://user-images.githubusercontent.com/42731603/74031421-6bec9e00-49ec-11ea-92f2-680263d47f88.PNG)

**Comment by gadagashwini** [comment]
@houzeyu2683, Please provide the standalone code to replicate the issue. Thanks!

**Comment by houzeyu2683** [comment]
> @houzeyu2683, Please provide the standalone code to replicate the issue. Thanks!

Sorry, I make mistake, it work now, I will delete this comment later, thanks.

**Comment by gadagashwini** [comment]
Closing as it is resolved.
