### ISSUE TITLE
Allow datasets to provide the number of examples they contain

### ISSUE THREAD

**Issue by Flamefire** [tensorflow/tensorflow#36531]
**System information**
- TensorFlow version (you are using): 2.1.0
- Are you willing to contribute it (Yes/No): No

**Describe the feature and the current behavior/state.**

Currently there is no good way to get to the number of samples or batches contained by a dataset although the information is usually available.

What you can do: `sum(1 for _ in dataset)` but this might not do what one wants:
When the dataset is batched it will return the number of batches including the trailing one. `MultiWorkerMirroredStrategy` can't handle that.

Usually this information is already available, see e.g. https://github.com/tensorflow/datasets/issues/1403

**Will this change the current api? How?**

Add a member `num_examples` and/or an overload for `__len__`

**Who will benefit with this feature?**

- Everyone using `MultiWorkerMirroredStrategy`
- Everyone using `steps_per_epoch`
- TF itself as the number of samples/batches is known before executing the training loop avoid status reports like `10/Unknown`
- This would help to provide correct behavior in https://github.com/tensorflow/tensorflow/commit/6be131d0860559954c42685a87c63f16cebb2185#diff-f8dd40712ac721c1b363e1a1ec44c1a3R741-R747

**Any Other info.**

There is an experimental op `cardinality` which might be very related. However it often (always?) returns "Unknown". Tested with MNIST from TFDS.

**Comment by Conchylicultor** [comment]
For more context, TFDS cannot provides the `tf.data.Dataset` cardinality because it is not supported by `TFRecordDataset` and `interleave` op. If there was a way to manually overwrite the cardinality of a `tf.data.Dataset`, we forward this info to the `tf.data.Dataset`.

Related issue: https://github.com/tensorflow/datasets/issues/1456

**Comment by Conchylicultor** [comment]
Thanks to jsmira, this should be fixed in https://github.com/tensorflow/tensorflow/commit/d25235b1964991dd331de7edef6be4f2c74fd7a4 with `tf.data.experimental.assert_cardinality(123)`

```
.apply(tf.data.experimental.assert_cardinality(42))
ds = tf.data.TFRecordDataset("examples.tfrecord")
tf.data.experimental.cardinality(ds)  # tf.data.experimental.UNKNOWN_CARDINALITY

ds = ds.apply(tf.data.experimental.assert_cardinality(42))
tf.data.experimental.cardinality(ds).numpy()  # 42
```
