### ISSUE TITLE
Documentation error for tf.signal.frame 

### ISSUE THREAD

**Issue by jmsmdy** [tensorflow/tensorflow#36547]
## URL(s) with the issue:
https://github.com/tensorflow/tensorflow/blob/cf7fcf164c9846502b21cebb7d3d5ccf6cb626e8/tensorflow/python/ops/signal/shape_ops.py#L55-L199

Documentation:
https://www.tensorflow.org/api_docs/python/tf/signal/frame

## Description of issue (what needs changing):

In the following example, the count of frames generated with pad_end=False is incorrect
    
    # A batch size 3 tensor of 9152 audio samples.
    audio = tf.random.normal([3, 9152])

    # Compute overlapping frames of length 512 with a step of 180 (frames overlap
    # by 332 samples). By default, only 50 frames are generated since the last
    # 152 samples do not form a full frame.
    frames = tf.signal.frame(audio, 512, 180)
    frames.shape.assert_is_compatible_with([3, 50, 512])

In fact, only 49 frames are generated with pad_true=False (the default).

### Clear description

Suppose we are given a tensor x with x.shape[-1] == N, a frame_length == K, and a frame_step == k.

To compute tf.signal.frame(x, frame_length, frame_step) (here default axis=-1 and pad_end=False), we could equivalently stack along axis -2 the following list of slices:

    [x[..., 0:K],
     x[..., k:K+k],
     x[..., 2*k:K+2*k],
     x[..., 3*k:K+3*k],
     ...
     x[..., j*k:K+j*k]]

where j is the maximum integer such that K+j*k <= N.

We can compute that j = (N - K) // k, so the number of slices in this list is j+1 = 1 + (N - K) // k. 

In the example here, N = 9152, K=512, k=180, so:

    j+1 = 1 + (9152-512) // 180 = 1 + 8640 // 180 = 1+48 = 49

Thus in the example given, the return shape should be [3, 49, 512], not [3, 50, 512]. Attached is a screenshot showing that this is indeed the behavior of tf.signal.frame, so it is an error in the documentation not in the code.

![tf signal frame](https://user-images.githubusercontent.com/47697814/74045729-497e6480-499b-11ea-9107-12305554ee18.png)

### Submit a pull request?

I am planning to submit a pull request.

**Comment by Saduf2019** [comment]
@jmsmdy 
as there is a pr to monitor this issue, can we close this issue.

**Comment by ymodak** [comment]
Closing this issue since the associated PR has been merged. 
It's effective with [TF 2.3](https://github.com/tensorflow/tensorflow/blob/v2.3.0/tensorflow/python/ops/signal/shape_ops.py#L58-L216) documentation.
Thanks!
