### ISSUE TITLE
archive.openswitch.net ssl cert path fails when installing syntaxnet.

### ISSUE THREAD

**Issue by zeryx** [tensorflow/tensorflow#3654]
Hey guys,
We've been using your default bazel shell script, `https://github.com/bazelbuild/bazel/releases/download/0.2.2b/bazel-0.2.2b-installer-linux-x86_64.sh` for a while to create a syntaxnet docker image for internal use, and it's been working great. However recently (past couple of days) we've tried a rebuild that started failing with the following error message:

```
ERROR: /tmp/tensorflow/models/syntaxnet/tensorflow/tensorflow/workspace.bzl:84:3: no such package '@gmock_archive//': Error downloading from https://archive.open
switch.net/gmock-1.7.0.zip to /tmp/bazel/external/gmock_archive: Error downloading https://archive.openswitch.net/gmock-1.7.0.zip to /tmp/bazel/external/gmock_ar
chive/gmock-1.7.0.zip: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable t
o find valid certification path to requested target and referenced by '//external:gtest'.
```
From quick inspection, it looks like the ssl cert path failed for https://archive.openswitch.net within the bazel build operation, IE it might have a self-signed certificate.

This is a brand new bug for us with no changes to our image or infrastructure, which makes us think that it's related specifically to the external file hosting you guys have designated in the shell script.

Let me know if you need any other information to help
Thanks,
James

**Comment by moorea** [comment]
I am experiencing the same issue

**Comment by hotomski** [comment]
I have this problem as well..

**Comment by martinwicke** [comment]
Please re-file this issue to [tensorflow/models](github.com/tensorflow/models).

@calberti: We switched away from the openswitch.net mirror because it isn't well maintained, you can look at the corresponding entry in the tensorflow WORKSPACE file, adapting yours to be the same should fix this.

**Comment by hotomski** [comment]
Thanks! I copied this whole part : native.new_http_archive(
    name = "gmock_archive",
    url = "http://pkgs.fedoraproject.org/repo/pkgs/gmock/gmock-1.7.0.zip/073b984d8798ea1594f5e44d85b20d66/gmock-1.7.0.zip",
    sha256 = "26fcbb5925b74ad5fc8c26b0495dfc96353f4d553492eb97e85a8a6d2f43095b",
    build_file = path_prefix + "gmock.BUILD",
  )
from original tensorflow and it worked!

**Comment by jiriker** [comment]
@hotomski : Can you please provide more thorough description of where you copied the code? I am fighting with this issue for a while and cannot make it work.

**Comment by hotomski** [comment]
@jiriker : You should place the code in the models/syntaxnet/tensorflow/tensorflow/workspace.bzl
Find the section and just replace it with the new url to gmock-1.7.0.zip or copy paste the whole section as I did.

**Comment by jmhodges** [comment]
Btw, this seems to be because openswitch has put a Let's Encrypt CA certificate in place, but our JVM's don't trust the IdenTrust ("Digital Signature Trust Co.") signed issuer cert

**Comment by jmhodges** [comment]
Oh! I left out that we should update our JVMs to the latest JVM. I know for a fact that JDK 8u102 works correctly with Let's Encrypt certificates. I think there's earlier versions that do, as well.

**Comment by zeryx** [comment]
forked tensorflow as well as the models repo to solve this: 

**Tensorflow** - https://github.com/zeryx/tensorflow
**Models** - https://github.com/zeryx/models

I'll be actively maintaining & keeping everything in parity  until this is resolved internally.

@hotomski I used your fix btw

**Comment by hotomski** [comment]
@zeryx Great! ;)

**Comment by GarryLau** [comment]
It’s because you do not have the certification! Your company do not give certifications to the relactive websites in tensorflow/workspace.bzl. So ask the IT to certificate it!
