### ISSUE TITLE
tpu closed error 

### ISSUE THREAD

**Issue by bestpredicts** [tensorflow/tensorflow#36544]
when I run tpu on colab, I meet error 
Epoch 1/6
WARNING:tensorflow:Gradients do not exist for variables ['tf_bert_model/bert/pooler/dense/kernel:0', 'tf_bert_model/bert/pooler/dense/bias:0'] when minimizing the loss.
WARNING:tensorflow:Gradients do not exist for variables ['tf_bert_model/bert/pooler/dense/kernel:0', 'tf_bert_model/bert/pooler/dense/bias:0'] when minimizing the loss.
WARNING:tensorflow:Gradients do not exist for variables ['tf_bert_model/bert/pooler/dense/kernel:0', 'tf_bert_model/bert/pooler/dense/bias:0'] when minimizing the loss.
WARNING:tensorflow:Gradients do not exist for variables ['tf_bert_model/bert/pooler/dense/kernel:0', 'tf_bert_model/bert/pooler/dense/bias:0'] when minimizing the loss.
 1/25 [>.............................] - ETA: 28:10
---------------------------------------------------------------------------
UnavailableError                          Traceback (most recent call last)
<ipython-input-25-7386834902ba> in <module>()
     94 
     95 
---> 96         model.fit(train_dataset,epochs=6)
     97 
     98 

10 frames
/usr/local/lib/python3.6/dist-packages/six.py in raise_from(value, from_value)

UnavailableError: Socket closed
Additional GRPC error information:
{"created":"@1581089996.572389050","description":"Error received from peer","file":"external/grpc/src/core/lib/surface/call.cc","file_line":1039,"grpc_message":"Socket closed","grpc_status":14}

**Comment by bestpredicts** [comment]
some code  here `
 
        with strategy.scope():

            model = create_model_a(bert_trainabel=True)
            BATCH_SIZE = 10
            NUM_EPOCHS = 6
            learning_rate = 2e-5
            decay_steps, warmup_steps = calc_train_steps(
                len(df_train.iloc[train_idx]),
                batch_size=BATCH_SIZE,
                epochs=NUM_EPOCHS,
                )
            adamW_opt = AdamWarmup(decay_steps=decay_steps, warmup_steps=warmup_steps, lr=learning_rate, min_lr=0,)
            model.compile(loss=loss_func , optimizer=adamW_opt)

        model_weight = f'{model_path}/bert_fold{fold}.h5'

        # ieval = SpearmanRhoCallback(training_data=train_dataset, validation_data=valid_dataset,
        #                                         patience=1, model_name=model_weight ) 
        

        model.fit(train_dataset,epochs=6) `

**Comment by ravikyram** [comment]
@bestpredicts 

Please, let us know which TensorFlow version you are using?. Can you please provide us colab link or full code snippet with supporting files to reproduce the issue in our environment. It helps us in localizing the issue faster. Thanks!

**Comment by bestpredicts** [comment]
> @bestpredicts
> 
> Please, let us know which TensorFlow version you are using?. Can you please provide us colab link or full code snippet with supporting files to reproduce the issue in our environment. It helps us in localizing the issue faster. Thanks!

tf2.1

**Comment by ravikyram** [comment]
@bestpredicts 

Can you please help us with full code snippet to reproduce the issue in our environment. It helps us in localizing the issue faster.Thanks!

**Comment by ravikyram** [comment]
@bestpredicts 

Any update on this issue please. Thanks!

**Comment by bestpredicts** [comment]
> @bestpredicts
> 
> Any update on this issue please. Thanks!

sorry  for  reply delay ,  here is my code  the colab link  [code](https://colab.research.google.com/drive/1i9ZhGGv8KDv5-VISbwTdCwDqrhh-67pu#scrollTo=xBggqjKaHU9w)
