### ISSUE TITLE
ImportError: cannot import name 'feature_column_v2'

### ISSUE THREAD

**Issue by venkatamaguluri** [tensorflow/tensorflow#36543]
I found below issue when trying to import tensorflow-hub - have no clue with this issue and appreciate your help.

ImportError                               Traceback (most recent call last)
<ipython-input-8-9ecaff1b481d> in <module>()
      1 import tensorflow as tf
----> 2 import tensorflow_hub as hub

C:\Program Files\Anaconda3\envs\tensorflow_sessions\lib\site-packages\tensorflow_hub\__init__.py in <module>()
     27 # error message is thrown instead of an obscure error of missing
     28 # symbols at executing the imports.
---> 29 from tensorflow_hub.estimator import LatestModuleExporter
     30 from tensorflow_hub.estimator import register_module_for_export
     31 from tensorflow_hub.feature_column import image_embedding_column

C:\Program Files\Anaconda3\envs\tensorflow_sessions\lib\site-packages\tensorflow_hub\estimator.py in <module>()
     23 from absl import logging
     24 import tensorflow as tf
---> 25 from tensorflow_hub import tf_utils
     26 from tensorflow_hub import tf_v1
     27 

C:\Program Files\Anaconda3\envs\tensorflow_sessions\lib\site-packages\tensorflow_hub\tf_utils.py in <module>()
     31 # depending on TensorFlow internal implementation details.
     32 # pylint: disable=g-direct-tensorflow-import
---> 33 from tensorflow.python.feature_column import feature_column_v2
     34 # pylint: enable=g-direct-tensorflow-import

**Comment by amahendrakar** [comment]
@venkatamaguluri,
Looks like the issue you are facing is related to TF-Hub. Please raise a new issue for the TF-Hub repo from [this](https://github.com/tensorflow/hub/issues/new) link. Thanks!

**Comment by amahendrakar** [comment]
@venkatamaguluri,
Any updates regarding this issue? Thanks!

**Comment by venkatamaguluri** [comment]
I have submitted in HUB. Thanks - Venkata
