### ISSUE TITLE
Dynamically unrolled graphs ~7x slower than statically unrolled graphs within tf.function

### ISSUE THREAD

**Issue by mjlbach** [tensorflow/tensorflow#36557]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 16.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): wheel
- TensorFlow version (use command below): tf-nightly
- Python version: 3.7
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 7.x.x
- GPU model and memory: 4 x titan xp

**Describe the current behavior**

I have a snippet of code in my evaluation loop that unrolls a model's predictions. Graph is a dictionary which is updated by both the policy_model and dynamics_model. I call the recurrent loop in this pattern, once outside of the loop to ensure the tensors are set to the correct shape (necessary for tf.range) and then inside the loop to continue the unrolling:

```
    graph = dynamics_graph_constructor(model_inputs)
    graph = policy_model(graph)
    predicted_value = policy_normalization(graph)
    rollout_value = predicted_value
    graph = dynamics_model(graph)
    graph_updates = get_graph_delta(graph, 0)
    graph = update_graph(graph, model_inputs, graph_updates)

    for step in tf.range(agent_params["search_depth"]-1):
        graph = policy_model(graph)
        predicted_value = policy_normalization(graph)
        rollout_value += predicted_value
        graph = dynamics_model(graph)
         graph_updates = get_graph_delta(graph, 0)
        graph = update_graph(graph, model_inputs, graph_updatesl)
```

If I change tf.range to range, I see an approximately 7x speedup. Is this normal? This seems like a huge performance penalty when using tf.while loops, even when using autograph.

**Comment by amahendrakar** [comment]
@mjlbach,
In order to expedite the trouble-shooting process, could you please provide the complete code to reproduce the issue reported here. Thanks!

**Comment by mjlbach** [comment]
Closing, this was another issue similar to https://github.com/tensorflow/tensorflow/issues/27143, even though I was pretty sure it wasn't... Sometimes a static graph will seem faster when it's actually removing iterations in which the input doesn't change (had a bug in my recurrent code).
