### ISSUE TITLE
TF_CONFIG is used even though a ClusterResolver was passed

### ISSUE THREAD

**Issue by Flamefire** [tensorflow/tensorflow#36550]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Mint
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.1.0
- Python version: 3.7.4

**Describe the current behavior**

I'm using a MultiWorkerMirroredStrategy with a cluster_resolver to avoid having to define the (to me obscure) TF_CONFIG env variable. But even though TF_CONFIG is used: https://github.com/tensorflow/tensorflow/blob/925be1049d191f25aa41c26db03205935b2e8582/tensorflow/python/distribute/distribute_coordinator.py#L752

This leads to output like:
> WARNING:tensorflow:Skipped evaluation since `eval_fn` is not passed in.

Which can only happen when no cluster-spec was found: https://github.com/tensorflow/tensorflow/blob/925be1049d191f25aa41c26db03205935b2e8582/tensorflow/python/distribute/distribute_coordinator.py#L778-L787

**Describe the expected behavior**

There should be no need to define this env variable and it should not be used but everything should come from the cluster resolver

**Code to reproduce the issue**

https://www.tensorflow.org/tutorials/distribute/multi_worker_with_keras#train_the_model_with_multiworkermirroredstrategy but with SlurmClusterResolver

**Comment by anj-s** [comment]
This should be [fixed](32aeb9957ede5496aa76a2d9a0b7b202d76a24fc) now. Can you try with the latest nightly release to see if you are able to run without issues?

**Comment by Flamefire** [comment]
@anj-s This doesn't look correct. https://github.com/tensorflow/tensorflow/blob/32aeb9957ede5496aa76a2d9a0b7b202d76a24fc/tensorflow/python/distribute/distribute_coordinator.py#L756-L761 shows that the TF_CONFIG variable takes precedence over the cluster_resolver explicitly passed in. This means different parts of the code might use different information depending on whether they use the TF_CONFIG or the cluster_resolver.

IIRC the strategy (now) always has a cluster resolver and defaults to a resolver using TF_CONFIG. So why not always use the cluster resolver?

**Comment by anj-s** [comment]
@Flamefire Are you setting the TF_CONFIG and also passing a cluster resolver argument to the strategy? We generally expect users to either use TF_CONFIG or use a cluster resolver.

This codepath is used as an entry point for different use cases which is why we need this. For MultiWorkerMirroredStrategy we can default to the cluster resolver as the single source of truth but that is not the case for all use cases of this function. We will be refactoring this soon so hopefully things will look clearer in the coming months.

**Comment by Flamefire** [comment]
Currently (2.1.0) yes, because only using TF_CONFIG doesn't allow everything the resolver does, e.g. setting num_gpus.

> For MultiWorkerMirroredStrategy we can default to the cluster resolver as the single source of truth but that is not the case for all use cases of this function.

Wouldn't you agree, that if the strategy passed to this function has a cluster resolver, then it should be used?   
Additionally: Instead of having multiple sources of truth and multiple parsing of TF_CONFIG why not always get the cluster_resolver from the strategy and default to the TfConfigClusterResolver if none is set? This would make it consistent with MultiWorkerMirroredStrategy and avoids differences in parsing the TF_CONFIG variable.

BTW: What are the different use cases? What strategy would be valid here that does not have a cluster_resolver but requires setting TF_CONFIG? Wouldn't it make sense to require a strategy with a cluster_resolver?

**Comment by Flamefire** [comment]
FTR: This was only fully fixed in 2.3.0 with https://github.com/tensorflow/tensorflow/commit/32aeb9957ede5496aa76a2d9a0b7b202d76a24fc not in 2.2.0 as indicated here. Hence until 2.3.0 it is required to set TF_CONFIG **in addition** to the cluster_resolver
