### ISSUE TITLE
TFv1.15.0 run tf_cnn_benchmarks.py bug

### ISSUE THREAD

**Issue by xcwanAndy** [tensorflow/tensorflow#36552]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: No
- TensorFlow installed from (source or binary): From source
- TensorFlow version (use command below): v1.15.0
- Python version: Python 3.6.9
- Bazel version (if compiling from source): Bazel 0.26.1
- GCC/Compiler version (if compiling from source): gcc-7.4.0
- CUDA/cuDNN version: CUDA 10.0, cuDNN 7.4.1.5
- GPU model and memory: Tesla V100, 32510MB

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

`v1.15.0-0-g590d6eef7e 1.15.0`

**Describe the current behavior**
While running `python3 tf_cnn_benchmarks.py --num_gpus=1 --batch_size=32 --model=resnet50 --variable_update=parameter_server`, output error:
```
Traceback (most recent call last):
  File "tf_cnn_benchmarks.py", line 29, in <module>
    import benchmark_cnn
  File "/root/benchmarks/scripts/tf_cnn_benchmarks/benchmark_cnn.py", line 51, in <module>
    from models import model_config
  File "/root/benchmarks/scripts/tf_cnn_benchmarks/models/model_config.py", line 152, in <module>
    from tensorflow.contrib import slim  # pylint: disable=unused-import
  File "<frozen importlib._bootstrap>", line 1007, in _handle_fromlist
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/__init__.py", line 50, in __getattr__
    module = self._load()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/__init__.py", line 44, in _load
    module = _importlib.import_module(self.__name__)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/contrib/__init__.py", line 54, in <module>
    from tensorflow.contrib import image
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/contrib/image/__init__.py", line 55, in <module>
    from tensorflow.contrib.image.python.ops.dense_image_warp import dense_image_warp
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/contrib/image/__init__.py", line 57, in <module>
    from tensorflow.contrib.image.python.ops.distort_image_ops import adjust_hsv_in_yiq
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/contrib/image/python/ops/distort_image_ops.py", line 29, in <module>
    resource_loader.get_path_to_datafile('_distort_image_ops.so'))
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/contrib/util/loader.py", line 56, in load_op_library
    ret = load_library.load_op_library(path)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/load_library.py", line 61, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename)
tensorflow.python.framework.errors_impl.NotFoundError: /usr/local/lib/python3.6/dist-packages/tensorflow_core/contrib/image/python/ops/_distort_image_ops.so: undefined symbol: _ZN4absl5Mutex10ReaderLockEv
python3 tf_cnn_benchmarks.py --num_gpus=1 --batch_size=32 --model=resnet50   3.14s user 2.78s system 291% cpu 2.029 total
```

**Describe the expected behavior**
Successfully run the example code.

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.
Following the command below, `https://github.com/tensorflow/benchmarks/tree/master/scripts/tf_cnn_benchmarks#getting-started`

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by xcwanAndy** [comment]
I added "--config gdr --config verbs" while configuring tensorflow for future work. I wonder if it would result in this bug.

**Comment by gadagashwini** [comment]
@xcwanAndy, Can you provide the standalone code to replicate the reported issue. Thanks!

**Comment by gadagashwini** [comment]
@xcwanAndy, I tried on google colab, its working as expected.
Please take a look at gist [here](https://colab.research.google.com/gist/gadagashwini/ef1842af2c85528da53b45aa2574081f/untitled382.ipynb). Thanks!

**Comment by xcwanAndy** [comment]
> @xcwanAndy, Can you provide the standalone code to replicate the reported issue. Thanks!
@gadagashwini Thanks a lot for your reply. As I said, the test code is exactly the official code: [tf_cnn_benchmarks.py](https://github.com/tensorflow/benchmarks/tree/master/scripts/tf_cnn_benchmarks#getting-started)   under branch "cnn_tf_v1.15_compatible".

I think there should be something wrong when installing tensorflow from source in docker (however, the installation succeeds in the end).

I use bazel==0.26.1 for installation and have V100 GPU and  RDMA supports in network, ".tf_configure.bazelrc" is shown below:
```
build --action_env PYTHON_BIN_PATH="/usr/bin/python3"
build --action_env PYTHON_LIB_PATH="/usr/lib/python3/dist-packages"
build --python_path="/usr/bin/python3"
build:xla --define with_xla_support=true
build --config=xla
build --action_env CUDA_TOOLKIT_PATH="/usr/local/cuda"
build --action_env TF_CUDA_COMPUTE_CAPABILITIES="7.0,7.0"
build --action_env LD_LIBRARY_PATH="/usr/local/cudnn/lib64:/usr/local/cuda/lib64:/usr/local/lib:/usr/local/nvidia/lib:/usr/local/nvidia/lib64:/usr/local/nccl/lib:/usr/local/nvidia/lib:/usr/local/nvidia/lib64"
build --action_env GCC_HOST_COMPILER_PATH="/usr/bin/gcc"
build --config=cuda
build:opt --copt=-march=native
build:opt --copt=-Wno-sign-compare
build:opt --host_copt=-march=native
build:opt --define with_default_optimizations=true
build:v2 --define=tf_api_version=2
test --flaky_test_attempts=3
test --test_size_filters=small,medium
test --test_tag_filters=-benchmark-test,-no_oss,-oss_serial
test --build_tag_filters=-benchmark-test,-no_oss
test --test_tag_filters=-gpu
test --build_tag_filters=-gpu
build --action_env TF_CONFIGURE_IOS="0"
```

Thanks!

**Comment by gadagashwini** [comment]
@xcwanAndy, Is this still an issue?

**Comment by xcwanAndy** [comment]
@gadagashwini  Yes, I still cannot make it in my docker container.

**Comment by gowthamkpr** [comment]
@xcwanAndy Can you please try this with Tensorflow 1.14 docker image and let me know if it is working as expected. Thanks!

**Comment by gussmith** [comment]
@xcwanAndy I have the same issue, how did you solve it finally? You closed it, but you did not specify how it was finally solved. Thanks for your help.
