### ISSUE TITLE
Transpose op only supports 1D-4D input arrays

### ISSUE THREAD

**Issue by RobotIntelligence** [tensorflow/tensorflow#36555]
When I run tflite object detection on android demo, I got this problem:

java.lang.RuntimeException: java.lang.IllegalStateException: Internal error: Unexpected failure when preparing tensor allocations: tensorflow/contrib/lite/kernels/transpose.cc Transpose op only supports 1D-4D input arrays.Node number 148 (TRANSPOSE) failed to prepare.

Thanks

**Comment by butterfly-coder** [comment]
I've faced same problem. Is there any way to solve this issue?

**Comment by thaink** [comment]
The feature is on the way. I'll update when it get merged.

**Comment by zerollzeng** [comment]
met this problem with my tflite model too

**Comment by zerollzeng** [comment]
if anybody has this problem whiile running tflite in pc, this problem has been solve with commit 97b63ed8769d09a70a6617b067e63a12c7f8e071, install newest tf-nightly should fix this.

**Comment by thaink** [comment]
The issue should be fixed at the latest master now.

**Comment by beniroquai** [comment]
Is this already available in prebuilt nightlys for Android? 
Could I use nightlys in the ```build.gradle```-file:

```    implementation 'org.tensorflow:tensorflow-lite:+' ````

**Comment by beniroquai** [comment]
Seems ```implementation  'org.tensorflow:tensorflow-lite:0.0.0-nightly'/```did the trick :)
