### ISSUE TITLE
TensorFlow should support importing submodules, like a normal Python package

### ISSUE THREAD

**Issue by shoyer** [tensorflow/tensorflow#36556]
**System information**
- TensorFlow version (you are using): 2.x
- Are you willing to contribute it (Yes/No): No

**Describe the feature and the current behavior/state.**

TensorFlow 1.x supports importing submodules, e.g., `import tensorflow.io`

On TensorFlow 2.x this raises `ModuleNotFoundError: No module named 'tensorflow.io'`. Instead you have to import `tensorflow`, at which point the `io` module is directly available. This is both misleading and highly non-standard for Python.

If you not want to support direct importing of submodules, then perhaps they shouldn't be called modules in the online docs?
https://www.tensorflow.org/api_docs/python/tf/io

**Will this change the current api? How?** Yes, but it would be fully backwards compatible.

**Who will benefit with this feature?** Anyone who expects TensorFlow to work like a normal Python package.

**Comment by mihaimaruseac** [comment]
In general, in Python if you can do

```python
import foo
foo.bar.baz.foobar
```

that doesn't imply you can also do

```python
import foo.bar.baz as m
m.foobar
```

It is not just something in Python that TensorFlow breaks, it's just the way things work.

In fact, to separate public and private APIs it is actually better to not allow both types of imports.

**Comment by shoyer** [comment]
It's true that the former behavior does not strictly imply the later, but in practice it essentially always does for modules. If something is called the `foo.bar.baz` module, then it is expected for `import foo.bar.baz` to work. I cannot think of any exceptions to this rule, besides TensorFlow.

There are other ways to hide internal implementation details. For example, it is common to use undocumented private modules (name starting with `_`) for implementations, and expose only intentionally public functions/classes in documented APIs.

**Comment by mihaimaruseac** [comment]
I agree with you. There is work on simplifying this structure, see https://github.com/tensorflow/community/pull/182

**Comment by ymodak** [comment]
Closing this issue since we have other thread capturing this. Thanks!
