### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by KDDaddy01** [tensorflow/tensorflow#36566]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): 
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): source
- TensorFlow version: Latest as of 2/7/2020
- Python version: 3.7.4
- Installed using virtualenv? pip? conda?: Tried with pip did not work tried with virtualenv did not work
- Bazel version (if compiling from source): NA
- GCC/Compiler version (if compiling from source):NA
- CUDA/cuDNN version:nA
- GPU model and memory: Rtx 1070 16 Gig of ram

**Describe the problem**

**Provide the exact sequence of commands / steps that you executed before running into the problem**
pip install virtualenv 
pip3 install --user --upgrade tensorflow

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

ERROR: Could not find a version that satisfies the requirement tensorflow (from versions: none)
ERROR: No matching distribution found for tensorflow

**Comment by amahendrakar** [comment]
@KDDaddy01,
May I know which operating system you are using?

Could you please try the below commands and let us know if it works? Thanks! 
```
pip3 install --upgrade pip
pip3 install tensorflow
```

**Comment by amahendrakar** [comment]
@KDDaddy01,
Any updates regarding this issue? Thanks!

**Comment by amahendrakar** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
