### ISSUE TITLE
[CI] PR merging and CI checks are not completed in time.

### ISSUE THREAD

**Issue by leemgs** [tensorflow/tensorflow#36568]
> This template is for miscellaneous issues not covered by the other issue categories.
>
> For questions on how to work with TensorFlow, or support for problems that are not verified bugs in TensorFlow, please go to [StackOverflow](https://stackoverflow.com/questions/tagged/tensorflow).
>
> If you are reporting a vulnerability, please use the [dedicated reporting process](https://github.com/tensorflow/tensorflow/blob/master/SECURITY.md).
> 
> For high-level discussions about TensorFlow, please post to discuss@tensorflow.org, for questions about the development or internal workings of TensorFlow, or if you would like to know how to contribute to TensorFlow, please post to developers@tensorflow.org.
> 
> 

This issue is not on bugs of Tensorflow. So, I chose the "Issue: Other Issues" category. I want to talk about on (1) the merging time of the PR and (2) the execution time of the CI checks (3) the build task cost of CI facilities in order to provide the below goals. 
- Reducing the waiting time of the Tensorflow contributors
- Helping the reviewers in order that they can concentrate on the productive reviews on submitted PRs

I summarized three cases among the lots of working PRs as follows. 

- (1) PR https://github.com/tensorflow/tensorflow/pull/36523: About the merging time
   - When the reviewer **frankchn** of two reviewers approved the PR, The CI checks work. Then, all checks are passed. It seems that the PR is still not merged due to the 1 pending reviewer (**gunan**). In this case, what are the criteria to merge this PR as a final step?
   - Screenshot:
      ![image](https://user-images.githubusercontent.com/82404/74029403-f7b3f980-49ef-11ea-81cc-c57e2673b4e2.png)

- (2) PR https://github.com/tensorflow/tensorflow/pull/33524 : About the execution cost of CI checks
   - It's weird. When **omalleyt12** approved the PR 33524, the three checks are still keeping the "Waiting for status ...." after 2hour. Why do not CI checks start a task? Does the CI system require 2hour+ to check the PR status?
      - Ubuntu CPU Expected — Waiting for status to be reported  Required
      - Ubuntu Sanity Expected — Waiting for status to be reported Required
      - import/copybara Expected — Waiting for status to be reported
   - Screenshot: 
      ![image](https://user-images.githubusercontent.com/82404/74030714-1071de80-49f3-11ea-9861-415988076e32.png)

- (3) PR https://github.com/tensorflow/tensorflow/pull/36526: About CI cost for Tensorflow build task
   - It seems that the build cost of Tensorflow is too big by introducing JAVA-based Bazel. Why Tensorflow community still not use Cmake (or Meson) instead of Bazel? Is a reason is to be used for the Bazel-based Android software platform by default? When CI checks run the build test, What is the CI/CD software to run the Baze-based build scripts (e.g., Windows, Mac, Ubuntu)? Is this Kbuilder?
   - Screenshot:
   ![image](https://user-images.githubusercontent.com/82404/74078873-24f5bb80-4a73-11ea-8858-11fb1e9670a2.png)

I want someone to tell me on a reason and the CI/CI direction of the Tensorflow community in case of (1) and (2) above.

And, what is the CI software used to run [scripts](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/tools/ci_build/presubmit) if the submitted PRs are correct or not?  For example, Hudson, Jenkins, Travis-CI, Circle-CI, QuickBuild, SWARM-CI, Bamboo, Buildbot, Continuum, Cruise Control, easyCIS, FinalBuilder, Mojo, Gump, Parabuild, Pulse, Sin, Teamcity, Team Foundation, and Zed.

**Comment by rthadur** [comment]
#36527

**Comment by mihaimaruseac** [comment]
As mentioned in the other issue, this is not the place to discuss this and in any case this won't change.
