### ISSUE TITLE
TensorFlow2.0 keras.DenseFeatures can not deal with sparseTensor

### ISSUE THREAD

**Issue by caizd1994** [tensorflow/tensorflow#36577]
Hello, I find tf.keras.layers.DenseFeatures can not deal with SparseTensor, when using tensorflow 1.15: tf.feature_column.input_layer  without this problem

here is my problem code
```
fea['hisList'] = tf.io.VarLenFeature(tf.int64)
tmp = tf.feature_column.categorical_column_with_hash_bucket('hisList', 1000, dtype=tf.string)
emb = tf.feature_column.embedding_column(tmp , 12)
feature_layer = tf.keras.layers.DenseFeatures([emb])
```

when without using tf.keras.Input
```
    model = tf.keras.Sequential([
      feature_layer,
      tf.keras.layers.Dense(64, activation='relu'),
      tf.keras.layers.Dense(128, activation='relu'),
      tf.keras.layers.Dense(1, activation='sigmoid')
    ])
```
ValueError: All SparseTensor and RaggedTensor inputs must be explicitly declared using a keras.Input() with sparse=True or ragged=True. We found an undeclared input SparseTensor

when using tf.keras.Input
```
    Input = tf.keras.Input(shape=(32, ),sparse=True)
    model = tf.keras.Sequential([
      Input
      feature_layer,
      tf.keras.layers.Dense(64, activation='relu'),
      tf.keras.layers.Dense(128, activation='relu'),
      tf.keras.layers.Dense(1, activation='sigmoid')
    ])
```
ValueError: ('We expected a dictionary here. Instead we got: ', <tensorflow.python.framework.sparse_tensor.SparseTensor object at 0x00000210C00CCCF8>)

**Comment by gadagashwini** [comment]
@caizd1994, Thanks for reporting this issue. 
Could you provide the complete standalone code to analyze the reported issue. Thanks!

**Comment by gadagashwini** [comment]
@caizd1994, Please share the code snippet to replicate the issue. Thanks

**Comment by gadagashwini** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
