### ISSUE TITLE
0.10.0rc0: Contrib distributions crash when sampling "n" is scalar

### ISSUE THREAD

**Issue by jlowin** [tensorflow/tensorflow#3657]
GitHub issues are for bugs / installation problems / feature requests.  
For general support from the community, see [StackOverflow](https://stackoverflow.com/questions/tagged/tensorflow).
To make bugs and feature requests more easy to find and organize, we close issues that are deemed
out of scope for GitHub Issues and point people to StackOverflow.

For bugs or installation issues, please provide the following information.
The more information you provide, the more easily we will be able to offer
help and advice.

### Environment info
Operating System: 
macOS 10.11

Installed version of CUDA and cuDNN: 
7.5 / 4

If installed from binary pip package, provide:

1. Which pip package you installed. 
mac os / Python 3.5 / GPU / 0.10rc0

2. The output from `python -c "import tensorflow; print(tensorflow.__version__)"`.
0.10.0rc0

### Steps to reproduce
```python
import numpy as np
import tensorflow as tf
# this works
tf.contrib.distributions.MultivariateNormalDiag(np.ones(5), np.ones(5)).sample([1])
# crashes; scalar case is not handled
tf.contrib.distributions.MultivariateNormalDiag(np.ones(5), np.ones(5)).sample(1)
```

**Comment by poxvoculi** [comment]
@langmore Can you take a look?

**Comment by langmore** [comment]
This is a documentation issue.  `.sample()` expects a rank 1 Tensor (or something convertible to that) specifying a shape.  So the scalar case was not intended to be handled.  I'm fixing the docs now.

**Comment by langmore** [comment]
Doc change submitted.  Thanks for reporting this Jeremiah!

**Comment by jlowin** [comment]
Thanks @langmore, makes sense!
