### ISSUE TITLE
Windows 10 building from source: cl.exe failed: error executing command...

### ISSUE THREAD

**Issue by JesperLindberg** [tensorflow/tensorflow#36576]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10 64 bit
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): source
- TensorFlow version: r2.0
- Python version: 3.7.6 (tags/v3.7.6:43364a7ae0, Dec 19 2019, 00:42:30) [MSC v.1916 64 bit (AMD64)]
- Installed using virtualenv? pip? conda?: pip
- Bazel version (if compiling from source): 0.26.1
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: release 10.0, V10.0.130 / cudnn-10.0-windows10-x64-v7.6.5.32, Note that I am trying to compile without cuda support.
- GPU model and memory: GTX 1060 6GB

**Describe the problem**
I am trying to compile a C++ library on this current machine, I will later import the lib on a work machine.
I followed the guidelines on: https://www.tensorflow.org/install/source_windows

**Provide the exact sequence of commands / steps that you executed before running into the problem**
More specifically:
1: do the pip3 installs.
2: download bazel 0.26.1 as an .exe, put it in my path
3: install msys2, add to path and run: pacman -S git patch unzip
4: *I did NOT* download visual studio 2019 since it says on the tested build configs that MSVC 2017 (which I have) should be used for r2.0
5: git clone and git checkout r2.0
6: python ./configure using all default and n to all other
7: running bazel build //tensorflow:tensorflow_dll_import_lib as stated on: https://github.com/tensorflow/tensorflow/pull/24963

After about an hour I got the error posted further down.

**Any other info / logs**
```
tensorflow/core/kernels/unique_op.cc(240): note: see reference to class template instantiation 'tensorflow::UniqueOp<bool,tensorflow::int32>' being compiled
ERROR: C:/users/jesper/documents/tensorflow/tensorflow/core/grappler/optimizers/data/BUILD:712:1: C++ compilation of rule '//tensorflow/core/grappler/optimizers/data:rebatch' failed (Exit 2): cl.exe failed: error executing command
  cd C:/users/jesper/_bazel_jesper/mqwe2qxk/execroot/org_tensorflow
  SET INCLUDE=C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE;C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\INCLUDE;C:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\ucrt;C:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um;C:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\shared;C:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\um;C:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\winrt;
    SET PATH=C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\CommonExtensions\Microsoft\TestWindow;C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\amd64;C:\Windows\Microsoft.NET\Framework64\v4.0.30319;C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\VCPackages;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\Tools;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Team Tools\Performance Tools\x64;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Team Tools\Performance Tools;C:\Program Files (x86)\Windows Kits\10\bin\x64;C:\Program Files (x86)\Windows Kits\10\bin\x86;C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.6.1 Tools\x64\;;C:\Windows\system32
    SET PWD=/proc/self/cwd
    SET PYTHON_BIN_PATH=C:/Users/Jesper/AppData/Local/Programs/Python/Python37/python.exe
    SET PYTHON_LIB_PATH=C:/Users/Jesper/AppData/Local/Programs/Python/Python37/lib/site-packages
    SET RUNFILES_MANIFEST_ONLY=1
    SET TEMP=C:\Users\Jesper\AppData\Local\Temp
    SET TF2_BEHAVIOR=1
    SET TF_CONFIGURE_IOS=0
    SET TMP=C:\Users\Jesper\AppData\Local\Temp
  C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/amd64/cl.exe /nologo /DCOMPILER_MSVC /DNOMINMAX /D_WIN32_WINNT=0x0601 /D_CRT_SECURE_NO_DEPRECATE /D_CRT_SECURE_NO_WARNINGS /bigobj /Zm500 /EHsc /wd4351 /wd4291 /wd4250 /wd4996 /I. /Ibazel-out/x64_windows-opt/bin /Iexternal/com_google_absl /Ibazel-out/x64_windows-opt/bin/external/com_google_absl /Iexternal/eigen_archive /Ibazel-out/x64_windows-opt/bin/external/eigen_archive /Iexternal/local_config_sycl /Ibazel-out/x64_windows-opt/bin/external/local_config_sycl /Iexternal/nsync /Ibazel-out/x64_windows-opt/bin/external/nsync /Iexternal/gif_archive /Ibazel-out/x64_windows-opt/bin/external/gif_archive /Iexternal/jpeg /Ibazel-out/x64_windows-opt/bin/external/jpeg /Iexternal/com_google_protobuf /Ibazel-out/x64_windows-opt/bin/external/com_google_protobuf /Iexternal/com_googlesource_code_re2 /Ibazel-out/x64_windows-opt/bin/external/com_googlesource_code_re2 /Iexternal/farmhash_archive /Ibazel-out/x64_windows-opt/bin/external/farmhash_archive /Iexternal/fft2d /Ibazel-out/x64_windows-opt/bin/external/fft2d /Iexternal/highwayhash /Ibazel-out/x64_windows-opt/bin/external/highwayhash /Iexternal/zlib_archive /Ibazel-out/x64_windows-opt/bin/external/zlib_archive /Iexternal/double_conversion /Ibazel-out/x64_windows-opt/bin/external/double_conversion /Iexternal/snappy /Ibazel-out/x64_windows-opt/bin/external/snappy /Iexternal/eigen_archive /Ibazel-out/x64_windows-opt/bin/external/eigen_archive /Iexternal/nsync/public /Ibazel-out/x64_windows-opt/bin/external/nsync/public /Iexternal/gif_archive /Ibazel-out/x64_windows-opt/bin/external/gif_archive /Iexternal/gif_archive/windows /Ibazel-out/x64_windows-opt/bin/external/gif_archive/windows /Iexternal/com_google_protobuf/src /Ibazel-out/x64_windows-opt/bin/external/com_google_protobuf/src /Iexternal/farmhash_archive/src /Ibazel-out/x64_windows-opt/bin/external/farmhash_archive/src /Iexternal/zlib_archive /Ibazel-out/x64_windows-opt/bin/external/zlib_archive /Iexternal/double_conversion /Ibazel-out/x64_windows-opt/bin/external/double_conversion /D__CLANG_SUPPORT_DYN_ANNOTATION__ /DEIGEN_MPL2_ONLY /DEIGEN_MAX_ALIGN_BYTES=64 /DEIGEN_HAS_TYPE_TRAITS=0 /DTF_USE_SNAPPY /showIncludes /MD /O2 /Oy- /DNDEBUG /wd4117 -D__DATE__="redacted" -D__TIMESTAMP__="redacted" -D__TIME__="redacted" /Gy /Gw -w -w -DWIN32_LEAN_AND_MEAN -DNOGDI /Fobazel-out/x64_windows-opt/bin/tensorflow/core/grappler/optimizers/data/_objs/rebatch/rebatch.obj /c tensorflow/core/grappler/optimizers/data/rebatch.cc
Execution platform: @bazel_tools//platforms:host_platform
tensorflow/core/grappler/optimizers/data/rebatch.cc(66): fatal error C1001: An internal error has occurred in the compiler.
(compiler file 'msc1.cpp', line 1468)
 To work around this problem, try simplifying or changing the program near the locations listed above.
Please choose the Technical Support command on the Visual C++
 Help menu, or open the Technical Support help file for more information
Internal Compiler Error in C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\amd64\cl.exe.  You will be prompted to send an error report to Microsoft later.
INTERNAL COMPILER ERROR in 'C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\amd64\cl.exe'
    Please choose the Technical Support command on the Visual C++
    Help menu, or open the Technical Support help file for more information
Target //tensorflow:tensorflow_dll_import_lib failed to build
INFO: Elapsed time: 3372.778s, Critical Path: 1297.23s
INFO: 2289 processes: 2289 local.
FAILED: Build did NOT complete successfully
```

**Comment by ihuale** [comment]
tf version: 2.0.0
vs version: 2015,2017,2019(all tried)
configure: cuda yes, another no
build cmd: bazel build --config=opt --config=v2 //tensorflow:libtensorflow_cc.so
`same error as above`.

**Comment by JesperLindberg** [comment]
@ihuale https://github.com/guikarist/tensorflow-windows-build-script this script works if u follow the instructions fully, however its not the latest version of tf.

**Comment by ravikyram** [comment]
@JesperLindberg 

I can see Microsoft Visual Studio 14.0 in the error log. Can you please cross check you have installed MSVC 2017 . Thanks!

**Comment by ihuale** [comment]
@JesperLindberg thanks, but i use that script before, now i need tf>=2.0

**Comment by JesperLindberg** [comment]
@ravikyram I uninstalled everything that had to do with VS and installed VS 2017 again and it built successfully.
@ihuale I will try build 2.1 and use it in VS 2017, will get back to you if I find any success.

**Comment by ihuale** [comment]
@JesperLindberg ok, thanks，looking forward to your good news

**Comment by JesperLindberg** [comment]
@ihuale I switched to libtoch (pytorch) 1.4 instead. At least it windows supported and cmake makes it much easier than bazel.

**Comment by ihuale** [comment]
Sorry for replying so late, i just found one solution according this [solution](https://github.com/tensorflow/tensorflow/issues/31520#issuecomment-524584978 "issues"),  i just edit file like that, and use vs2019, bazel 0.24.1, cuda 10.1, at last, i build tensorflow_cc.dll(tensorflow 2.0.0 ) successed!
but there still are some error when i use  tensorflow_cc.lib, i got some lnk 2001 error, and then , follow this [ add symbol to def_file_filter.py.tpl](https://github.com/tensorflow/tensorflow/issues/30552#issuecomment-512348156 "issues"), i fixed some lnk 2001 error.
when i use savedmodel api on tensorflow_cc.dll, i just found `LoadSavedModel` dose not have `TF_EXPORT` macro, so add it.
The above steps at least worked for me...

**Comment by JesperLindberg** [comment]
@ihuale Thanks, however I am locked to vs 2017 since I am on a work computer with no admin rights.

**Comment by ihuale** [comment]
> @ihuale Thanks, however I am locked to vs 2017 since I am on a work computer with no admin rights.

i just tried vs2015, vs2017, vs2019 one by one, only vs2019 successed...

**Comment by JesperLindberg** [comment]
@ihuale Oh man.. Well I got libtorch working without any problems. Also their syntax is very close to their python syntax so I guess I will stick with pytorch. Thanks for the help though.
