### ISSUE TITLE
Software requirement may lack VC++ runtime

### ISSUE THREAD

**Issue by kuri-leo** [tensorflow/tensorflow#36588]
## URL(s) with the issue:

[Software requirements](https://www.tensorflow.org/install/gpu#software_requirements)

## Description of issue (what needs changing):

The requirement may lack the dependency of [Microsoft Visual C++ Redistributable for Visual Studio](https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads) runtime.

### Clear description

After installation, TF raises an error with `ImportError: DLL load failed: The specified module could not be found.`

Fixed after installing [Microsoft Visual C++ Redistributable for Visual Studio 2015, 2017 and 2019](https://aka.ms/vs/16/release/vc_redist.x64.exe) via [error page](https://www.tensorflow.org/install/errors) and issue https://github.com/tensorflow/tensorflow/issues/22794 & https://github.com/tensorflow/tensorflow/issues/22512

Wanna confirm whether Microsoft Visual C++ Redistributable for Visual Studio must be installed and its version. If true, please add this information to [software requirements](https://www.tensorflow.org/install/gpu#software_requirements).

### Submit a pull request?

If confirmation, I can PR to [tensorflow/docs](https://github.com/tensorflow/docs/blob/master/site/en/install/gpu.md).

---
PS.. here comes system info to trace that issue.
Hardware:
```
Processor: Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz (4 CPUs), ~2.9GHz
Memory: 16384MB RAM
Card name: NVIDIA GeForce 940MX
Manufacturer: NVIDIA
Chip type: GeForce 940MX
```
Software:
```
Operating System: Windows 10 Pro 64-bit (10.0, Build 18363) (18362.19h1_release.190318-1202) 
(conda)TensorFlow: 2.1.0 (install via pypi)
(conda)cudatoolkit: 10.1.243 (install via anaconda)
(conda)cudnn: 7.6.5 (install via anaconda)
Nvidia Driver Version: 441.87
```
It can be reproduced in `conda install` or `native install`.

Hope those info helps.

Thanks in advance! :-)

**Comment by kuri-leo** [comment]
Confirmed with [TF 2.1 release note](https://github.com/tensorflow/tensorflow/releases/tag/v2.1.0).

**Comment by gowthamkpr** [comment]
@kuri-leo I am closing this issue as the docs have already been updates as you can see [here](https://www.tensorflow.org/install/source_windows#install_visual_c_build_tools_2019). If I misinterpreted the issue, please open it again. Thanks!

**Comment by kuri-leo** [comment]
@gowthamkpr Oh, that is another point. It should be clarified that the issue occurs during install tf2.1 via pip directly, not from source code. So, I believe info should also be updated to [system-requirements](https://www.tensorflow.org/install/pip#system-requirements). Related PR is https://github.com/tensorflow/docs/pull/1453, and now it's ready to pull.
