### ISSUE TITLE
Building a static library for windows with visual studio.

### ISSUE THREAD

**Issue by JesperLindberg** [tensorflow/tensorflow#36590]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using): 2.1
- Are you willing to contribute it (Yes/No): yes (but not sure I can)

**Describe the feature and the current behavior/state.**
I want a feature to build a static library for C++ integrating on windows with visual studio. Or a static library that is available for download.

**Will this change the current api? How?**
No, it will not change the api.

**Who will benefit with this feature?**
Everyone who has a C++ project in visual studio and want to implement tensorflow.

**Any Other info.**
It would have been nice with a full guide to how to do it. This is something I could contribute with if we ever get the feature.

**Comment by Saduf2019** [comment]
@JesperLindberg 
Could you please verify on the latest version if this is still an issue.

**Comment by JesperLindberg** [comment]
@Saduf2019 I will close this as I no longer has anyway of checking this.
