### ISSUE TITLE
tf.keras GradientTape: get gradient with respect to input

### ISSUE THREAD

**Issue by dmus** [tensorflow/tensorflow#36596]
Tensorflow 2.1

I want to get the gradients with respect to the input instead of the gradient with respect to the trainable weights. I adjust the example from https://www.tensorflow.org/guide/keras/train_and_evaluate to

```
import tensorflow as tf
import numpy as np

physical_devices = tf.config.experimental.list_physical_devices('GPU')
assert len(physical_devices) > 0, 'Not enough GPU hardware devices available'
tf.config.experimental.set_memory_growth(physical_devices[0], True)

def loss_fun(y_true, y_pred):
    loss = tf.reduce_mean(tf.square(y_true - y_pred), axis=-1)
    return loss

# Create a dataset
x = np.random.rand(10, 180, 320, 3).astype(np.float32)
y = np.random.rand(10, 1).astype(np.float32)
dataset = tf.data.Dataset.from_tensor_slices((x, y)).batch(1)

# Create a model
base_model = tf.keras.applications.MobileNet(input_shape=(180, 320, 3), weights=None, include_top=False)
x = tf.keras.layers.GlobalAveragePooling2D()(base_model.output)
output = tf.keras.layers.Dense(1)(x)
model = tf.keras.models.Model(inputs=base_model.input, outputs=output)

for input, target in dataset:

    for iteration in range(400):
        with tf.GradientTape() as tape:
            # Run the forward pass of the layer.
            # The operations that the layer applies
            # to its inputs are going to be recorded
            # on the GradientTape.
            prediction = model(input, training=False)  # Logits for this minibatch

            # Compute the loss value for this minibatch.
            loss_value = loss_fun(target, prediction)

        # Use the gradient tape to automatically retrieve
        # the gradients of the trainable variables with respect to the loss.
        grads = tape.gradient(loss_value, model.inputs)
        print(grads)  # output: [None]
        # Run one step of gradient descent by updating
        # the value of the variables to minimize the loss.
        optimizer = tf.keras.optimizers.Adam(learning_rate=0.001)
        optimizer.apply_gradients(zip(grads, model.inputs))

        print('Iteration {}'.format(iteration))
```

However, this doesnot work, because grads = tape.gradient(loss_value, model.inputs) returns [None]. Is this intended behaviour or not? If yes, what is the recommended way to get the gradients with respect to the input?

**Comment by ravikyram** [comment]
@dmus 
I tried to reproduce the issue with TF-GPU  2.1.0 ,2.2.0-dev20200210 .It returns [None] and also I am seeing the error message `ValueError: No gradients provided for any variable: ['input_1:0'].Please, find the gist [here](https://colab.research.google.com/gist/ravikyram/a60963d39257237126a70cb305e73662/untitled632.ipynb). Is this the expected behavior?. Thanks!

**Comment by dmus** [comment]
@ravikyram Yes, this is the expected behaviour. It turns out this can be solved by converting the input explicitly to a tf.Variable and then use tape.watch() explicitly.

```
image = tf.Variable(input)
for iteration in range(400):
    with tf.GradientTape() as tape:
        tape.watch(image)
        # Run the forward pass of the layer.
        # The operations that the layer applies
        # to its inputs are going to be recorded
        # on the GradientTape.
        prediction = model(image, training=False)  # Logits for this minibatch

        # Compute the loss value for this minibatch.
        loss_value = loss_fun(target, prediction)

    # Use the gradient tape to automatically retrieve
    # the gradients of the trainable variables with respect to the loss.
    grads = tape.gradient(loss_value, image)
    #print(grads)  # output: [None]
    # Run one step of gradient descent by updating
    # the value of the variables to minimize the loss.
    optimizer = tf.keras.optimizers.Adam(learning_rate=0.001)
    optimizer.apply_gradients(zip([grads], [image]))

    print('Iteration {}'.format(iteration))
```

So I think this is intended behaviour and this issue can be closed.

**Comment by dmus** [comment]
As a workaround: I can get this example working when I convert the image to a tensor for computing the gradient and to a tf.Variable for updating. 

```
for input, target in dataset:
    image0 = tf.convert_to_tensor(input[0])
    image1 = tf.convert_to_tensor(input[1])

    image0_var = tf.Variable(image0)

    for iteration in range(400):
        with tf.GradientTape() as tape:
            tape.watch(image0)
            # Run the forward pass of the layer.
            # The operations that the layer applies
            # to its inputs are going to be recorded
            # on the GradientTape.
            # prediction = model(input, training=False)  # Logits for this minibatch
            prediction = model([input[0], input[1]])
            print('prediction: {}'.format(prediction))
            # Compute the loss value for this minibatch.
            # loss_value = loss_fun(target, prediction)

        # Use the gradient tape to automatically retrieve
        # the gradients of the trainable variables with respect to the loss.
        grads = tape.gradient(prediction, [input[0]])
        print(grads)  # output: [None]
        # Run one step of gradient descent by updating
        # the value of the variables to minimize the loss.

        optimizer = tf.keras.optimizers.Adam(learning_rate=0.001)
        optimizer.apply_gradients(zip(grads, [image0_var]))
        #optimizer.apply_gradients(zip(grads, model.trainable_weights))

        print('Iteration {}'.format(iteration))

```

**Comment by kphawkins** [comment]
I recently ran into this issue and was able to confirm that @dmus 's workaround seems to solve it for me (TF 2.1.0, stable, compiled from source, GPU).  Going to give my thoughts for the benefit of the next person to come across the issue of wanting to compute gradients with respect to inputs.

In my testing, I'm not sure if this is bug, but it feels unintuitive.  Suppose we have a Model `model` and Variable `v` and we execute  
```
with tf.GradientTape() as tape:
    tape.watch(model.input)
    model_vals = model(v)
```
The problem is that the call `tape.gradient(model_vals, model.variables)` generally works as expected to get the gradients with respect to the variables of the model, but `tape.gradient(model_vals, model.input)` does not work like one would expect.  The sources parameter of `GradentTape.gradient` seems to expect variables, but the attribute `model.input` is a symbolic Tensor.  For whatever reason, feeding this variable into either `tape.watch` or `tape.gradient` fails silently.  The default behavior of `tape.gradient` if it can't find a path of differentiation is for it to return `None`, so this is why this value is returned.

Thinking deeper about this, it seems unreasonable to assume that we can use `model.input` as the object to differentiate against because the same model can be used multiple times within the same `GradientTape` session.  If composed together (`model_vals = model(model(v))`), there would be multiple paths from the target to the input tensors, making the gradient ill-defined.

I think it would be nice for one of those methods to throw a warning if called in this way, considering that it's easy to conflate the idea of input with the variable fed into the input.  But perhaps this would be harder than it seems.

Below I have a simple example that illustrates what's happening.

```
import tensorflow as tf
import tensorflow.keras as keras
import tensorflow.keras.layers as layers

tf.random.set_seed(0)

model_in = keras.Input(shape=(2,))
model_d1 = layers.Dense(64, activation='relu')(model_in)
model_d2 = layers.Dense(64, activation='relu')(model_d1)
model_d3 = layers.Dense(1)(model_d2)
model = keras.Model(inputs=[model_in], outputs=[model_d3])
model.summary()

v = tf.Variable([[0.1, 0.2]], name='v_var')

####################################################
with tf.GradientTape() as tape:
    tape.watch(model.input)
    model_vals = model(v)
print(len(tape.watched_variables())) 
# 7      ( = (1 kernel + 1 bias) * (3 dense layers) + (1 v_var) )
print(model.input)
# Tensor("input_1:0", shape=(None, 2), dtype=float32)
model_grad = tape.gradient(model_vals, model.input)
print(model_grad)
# None
####################################################

####################################################
with tf.GradientTape(watch_accessed_variables=False) as tape:
    tape.watch(model.input)
    model_vals = model(v)
print(len(tape.watched_variables())) 
# 0      (model.input isn't a variable so it is ignored)
####################################################

####################################################
with tf.GradientTape(watch_accessed_variables=False) as tape:
    tape.watch(v)
    model_vals = model(v)
print(len(tape.watched_variables())) 
# 1
print(v)
# <tf.Variable 'v_var:0' shape=(1, 2) dtype=float32, numpy=array([[0.1, 0.2]], dtype=float32)>
model_grad = tape.gradient(model_vals, v)
print(model_grad)
# tf.Tensor([[-0.04392226 -0.06807809]], shape=(1, 2), dtype=float32)
####################################################
```

**Comment by UdiBhaskar** [comment]
any update on this? I am also not getting any gradients even after converting input as a Variable and watching that variable using tape.watch

**Comment by UdiBhaskar** [comment]
Got it. It is because of the Embedding layer. The gradient is not flowing through the embedding layer.

**Comment by tanzhenyu** [comment]
Can you get the gradient of the input by calling:
```
tape.gradient(loss, input)
```
instead of:
```
tape.gradient(model.input)
```
?

**Comment by ckyleda** [comment]
I have a similar issue trying to compute gradients with tf.gradients of the loss wrt the inputs. Just returns None in all cases.

Interestingly this works perfectly in older versions of tensorflow (< 2.0) - so they've broken something. This is an extremely annoying issue if trying to work within tf.keras's train functions, but from reading above it seems that even if you were to write your own this issue would persist.

Can't this behaviour be reverted to how it was pre-2.0, where you could calculate the gradients however you liked, without arbitrary restrictions?

**Comment by ptigas** [comment]
this simple example fails as well

```
import tensorflow as tf

(x_train, y_train), _ = tf.keras.datasets.mnist.load_data()
train_ds = tf.data.Dataset.from_tensor_slices((x_train, y_train)).batch(32)

model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128),
  tf.keras.layers.ReLU(),
  tf.keras.layers.Dense(10)
])
loss_object = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

images, labels = next(iter(train_ds))

with tf.GradientTape() as tape:
  tape.watch(model.output)
  predictions = model(image)
  loss = loss_object(labels, predictions)

grads = tape.gradient(loss, model.output)
print(grads)
```

**Comment by swaroop-nath** [comment]
@UdiBhaskar Did you find a work-around to make the gradient flow through the embedding layer?

**Comment by swaroop-nath** [comment]
I found a solution to my problem. For future references and in hope that it would help someone in a similar need as me - 

The error that I was committing - Converting the loss value and the predictions from the model to numpy array. **It is imperative that you don't convert them to numpy arrays at any point in time before computing the gradients.** In my case, I was using a custom loss function which converted the predicted values to numpy arrays for computations.

**Comment by sivaji123256** [comment]
> Got it. It is because of the Embedding layer. The gradient is not flowing through the embedding layer.

I am 

> I recently ran into this issue and was able to confirm that @dmus 's workaround seems to solve it for me (TF 2.1.0, stable, compiled from source, GPU). Going to give my thoughts for the benefit of the next person to come across the issue of wanting to compute gradients with respect to inputs.
> 
> In my testing, I'm not sure if this is bug, but it feels unintuitive. Suppose we have a Model `model` and Variable `v` and we execute
> 
> ```
> with tf.GradientTape() as tape:
>     tape.watch(model.input)
>     model_vals = model(v)
> ```
> 
> The problem is that the call `tape.gradient(model_vals, model.variables)` generally works as expected to get the gradients with respect to the variables of the model, but `tape.gradient(model_vals, model.input)` does not work like one would expect. The sources parameter of `GradentTape.gradient` seems to expect variables, but the attribute `model.input` is a symbolic Tensor. For whatever reason, feeding this variable into either `tape.watch` or `tape.gradient` fails silently. The default behavior of `tape.gradient` if it can't find a path of differentiation is for it to return `None`, so this is why this value is returned.
> 
> Thinking deeper about this, it seems unreasonable to assume that we can use `model.input` as the object to differentiate against because the same model can be used multiple times within the same `GradientTape` session. If composed together (`model_vals = model(model(v))`), there would be multiple paths from the target to the input tensors, making the gradient ill-defined.
> 
> I think it would be nice for one of those methods to throw a warning if called in this way, considering that it's easy to conflate the idea of input with the variable fed into the input. But perhaps this would be harder than it seems.
> 
> Below I have a simple example that illustrates what's happening.
> 
> ```
> import tensorflow as tf
> import tensorflow.keras as keras
> import tensorflow.keras.layers as layers
> 
> tf.random.set_seed(0)
> 
> model_in = keras.Input(shape=(2,))
> model_d1 = layers.Dense(64, activation='relu')(model_in)
> model_d2 = layers.Dense(64, activation='relu')(model_d1)
> model_d3 = layers.Dense(1)(model_d2)
> model = keras.Model(inputs=[model_in], outputs=[model_d3])
> model.summary()
> 
> v = tf.Variable([[0.1, 0.2]], name='v_var')
> 
> ####################################################
> with tf.GradientTape() as tape:
>     tape.watch(model.input)
>     model_vals = model(v)
> print(len(tape.watched_variables())) 
> # 7      ( = (1 kernel + 1 bias) * (3 dense layers) + (1 v_var) )
> print(model.input)
> # Tensor("input_1:0", shape=(None, 2), dtype=float32)
> model_grad = tape.gradient(model_vals, model.input)
> print(model_grad)
> # None
> ####################################################
> 
> ####################################################
> with tf.GradientTape(watch_accessed_variables=False) as tape:
>     tape.watch(model.input)
>     model_vals = model(v)
> print(len(tape.watched_variables())) 
> # 0      (model.input isn't a variable so it is ignored)
> ####################################################
> 
> ####################################################
> with tf.GradientTape(watch_accessed_variables=False) as tape:
>     tape.watch(v)
>     model_vals = model(v)
> print(len(tape.watched_variables())) 
> # 1
> print(v)
> # <tf.Variable 'v_var:0' shape=(1, 2) dtype=float32, numpy=array([[0.1, 0.2]], dtype=float32)>
> model_grad = tape.gradient(model_vals, v)
> print(model_grad)
> # tf.Tensor([[-0.04392226 -0.06807809]], shape=(1, 2), dtype=float32)
> ####################################################
> ```
@kphawkins 
I am trying to find out the gradient of the cross entropy loss and some custom loss functions with respect to the input image .
I followed the same procedure you mentioned ,still the gradient value returning None.Please go through the code  below.

from keras.applications.vgg19 import preprocess_input
from keras.applications.vgg19 import decode_predictions
from keras.preprocessing.image import img_to_array
from keras.preprocessing.image import load_img
model = vgg19.VGG19(weights="imagenet", include_top=True)
image = load_img('/content/dog.jpg', target_size=(224, 224))
image = img_to_array(image)
# reshape data for the model
image = image.reshape((1, image.shape[0], image.shape[1], image.shape[2]))
# prepare the image for the VGG model
image = preprocess_input(image)
yhat = model.predict(image)
#print(yhat)
label = decode_predictions(yhat)
label = label[0][0]
# print the classification
cross_entropy_loss=-(math.log(label[2]))
print(cross_entropy_loss)
# Cross_entropy loss returnining  0.035864354427793455
image=tf.convert_to_tensor(image)
cross_entropy_loss=tf.convert_to_tensor(cross_entropy_loss)
image=tf.Variable(image)
ce=tf.Variable(cross_entropy_loss)
with tf.GradientTape() as tape:
   tape.watch(image)
   loss=ce
   #print(loss)
print(len(tape.watched_variables()))
model_grad = tape.gradient(loss,image)
print(model_grad)
# It is returning  :
# 1
# None 
Is there any way to solve this issue?

**Comment by luvwinnie** [comment]
Does this being solved? I trying to implement a GradCAM which the model serve on tensorflow serving outputs a prediction and final_conv outputs, however i got None when use the tape.gradient, is it possible to compute the gradients which the model serving on the Tensorflow Serving/TritonInferenceServer?

**Comment by saddamhijazi** [comment]
> I found a solution to my problem. For future references and in hope that it would help someone in a similar need as me -
> 
> The error that I was committing - Converting the loss value and the predictions from the model to numpy array. **It is imperative that you don't convert them to numpy arrays at any point in time before computing the gradients.** In my case, I was using a custom loss function which converted the predicted values to numpy arrays for computations.

May I ask one question about the issue of converting the loss value and the predictions to numpy arrays. First, I would like to explain my problem, I have created a step function in which I pass one batch at a time of the data to my NN model. After applying the prediction I compute the jacobian of a part of the output and here I do get a non-null jacobian but when I compute the gradient of the loss w.r.t. the model trainable parameters I get none values.

I tried to print the predictions output values before applying the gradient on the loss function and I get this for the prediction output "pred"

tf.Tensor[... values...], shape=(10, 35), dtype=float64)

I tried to make sure that my prediction output is not in numpy array format, therefore I wrote this command after the prediction

`pred_T = tf.Variable(tf.convert_to_tensor(pred))`

when I print pred_T, I get this:

<tf.Variable 'Variable:0' shape=(10, 35) dtype=float64, numpy=
array([...values...])><dtype: 'float64'>

I don't understand why pred_T is still in numpy format !!

Of course the loss function is computed using pred or pred_T therefore it is important to make sure it is not in numpy format but I am not able to figure out the way of doing that. Does anybody has a solution for that.

In case this my step function code

`
def step(self,t,y):
        
        Nu = self.Nu
        Np = self.Np
        a_tf = y[:,0:Nu]
        b_tf = y[:,Nu:]
        x_in = tf.Variable(tf.convert_to_tensor(t))
        y_out = tf.Variable(tf.convert_to_tensor(y))
        with tf.GradientTape(persistent=True) as tape:
            pred = self.model(x_in)
            pred_T = tf.Variable(tf.convert_to_tensor(pred))
            a_pred = pred[:,0:Nu]
            b_pred = pred[:,Nu:]
        da_dt = tape.jacobian(a_pred,x_in) // gives non-null values
        loss = y_out-pred_T
        print(pred)
        print(pred_T)
        grads = tape.gradient(loss, self.model.trainable_variables) // gives NULL values
        print(grads)
        aDot = np.zeros((da_dt.shape[0], da_dt.shape[1]))
        for i in range(da_dt.shape[0]):
            aDot[i,:] = da_dt[i,:,i,0].numpy()
        aDot_T = tf.Variable(aDot)
        Prod_T = self.TensorProduct(a_pred,C)
        f_1 = tf.tensordot(M,tf.transpose(aDot_T),1) - nu * tf.tensordot(B,tf.transpose(a_pred),1) + \
        tf.transpose(Prod_T) + tf.tensordot(K,tf.transpose(b_pred),1) 
        f_2 = tf.tensordot(P,tf.transpose(a_pred),1)
        
        #loss = tf.reduce_sum(tf.square(a_tf - a_pred)) + \
        #            tf.reduce_sum(tf.square(b_tf - b_pred)) + \
        #            tf.reduce_sum(tf.square(tf.transpose(f_1))) + \
        #            tf.reduce_sum(tf.square(tf.transpose(f_2)))
        
        print("Q4")
        #loss_a = tf.square(a_tf - a_pred)
        #lossF1 = tf.square(tf.transpose(f_1))
        #print(loss_a.shape)
        #print(lossF1.shape)
        #print(tape.watched_variables())

        
        print("Q5")
        print(grads)

        self.loss = loss
        print("Q6")
        #print(self.model.trainable_variables)
        self.opt.apply_gradients(zip(grads, self.model.trainable_variables))
        print("Q7")

`
