### ISSUE TITLE
Heatmap function

### ISSUE THREAD

**Issue by generationzcode** [tensorflow/tensorflow#36592]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using):2.0(I use colab so the latest probably)
- Are you willing to contribute it (Yes/No):
Yes

**Describe the feature and the current behavior/state.**
Presently I have to write lots of code to create a heatmap for images. I would like to have a function that automatically generates one for you
**Will this change the current api? How?**
It will add another function to the API
**Who will benefit with this feature?**
Beginners at ML and others who don't want to write lots of code to do this
**Any Other info.**

**Comment by Saduf2019** [comment]
@generationzcode Could you please share your code snippet, or any use case where assistance with this new feature request is required.

**Comment by generationzcode** [comment]
https://colab.research.google.com/drive/1E6RZpXsQtRi9Sp4wOQ39mvKht3NMhX_F heres the code on colab. This was done in a google code in task

**Comment by bhack** [comment]
There are also a some others related features about heatmaps for keypoints/object detection tasks with heatmaps.
See https://github.com/tensorflow/addons/issues/1366 and https://github.com/tensorflow/addons/issues/1364

**Comment by bhack** [comment]
Instead If your scope it is limited to network interpretability check:
https://github.com/sicara/tf-explain
https://github.com/tensorflow/lucid

**Comment by rmothukuru** [comment]
@generationzcode,
Can you please refer the [Grad-CAM Algorithm](https://keras.io/examples/vision/grad_cam/#the-gradcam-algorithm) mentioned in the **`Keras Documentation`** and let us know if that is what you are looking for? Thanks!
