### ISSUE TITLE
Missing graph_vis_animation.gif image in http://www.tensorflow.org/how_tos/graph_viz/index.html

### ISSUE THREAD

**Issue by danbri** [tensorflow/tensorflow#366]
http://www.tensorflow.org/how_tos/graph_viz/index.html has a bad embedded image link:
 
    <p>
      <img src="./graph_vis_animation.gif" 
       alt="Visualization of a TensorFlow graph" 
      title="Visualization of a TensorFlow graph" />
    <em>Visualization of a TensorFlow graph.</em></p>

Nearby: https://github.com/tensorflow/tensorflow/tree/master/tensorflow/g3doc/how_tos/graph_viz (and https://tensorflow.googlesource.com/tensorflow/+/master/tensorflow/g3doc/how_tos/graph_viz/ ) are missing the file.

**Comment by craigcitro** [comment]
Fix should be up shortly!

**Comment by craigcitro** [comment]
... and we're fixed.
