### ISSUE TITLE
fft2d different results between tensorflow and numpy

### ISSUE THREAD

**Issue by why702** [tensorflow/tensorflow#36605]
Hi,

I have one question about the fft2d and fftshift. 
The following code shows the similar process (fft2d > fftshift > * filter(LPF) > ifftshift > ifft2d) with numpy and tensorflow.
However the result is mush different. And the result of tensorflow is so weird.
Could anyone help me figure out what's wrong in the code?
Thanks a lot.

`    
    img = cv2.imread("xxx.png")
    img = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY).astype(np.float32)
    width = img.shape[1]
    height = img.shape[0]

    filter = LPF_Butterworth(width, height, 33, 4)

    # use numpy fft2 ===========
    f = np.fft.fft2(img)
    f = np.fft.fftshift(f)
    f_l = f * filter
    f_l = np.fft.ifftshift(f_l)
    f_l = np.fft.ifft2(f_l)
    f_np = np.real(f_l)
    #===========================

    input_placeholder = tf.compat.v1.placeholder(tf.float32,
                                       shape=[height, width, 1],
                                       name='input')

    # use tensorflow fft2d ===========
    tf_filter = tf.convert_to_tensor(filter, dtype=tf.float32)
    tf_filter_comx = tf.expand_dims(tf.complex(tf_filter, tf.zeros(tf_filter.shape)),2)
    fft_org = tf.fft2d(tf.cast(input_placeholder, tf.complex64))
    fft_org = tf.signal.fftshift(fft_org, axes=[0,1])
    fft_filter = fft_org * tf_filter_comx
    fft_filter = tf.ifft2d(tf.signal.ifftshift(fft_filter, axes=[0,1]))
    fft_filter = tf.real(fft_filter)
    #================================

    sess = tf.Session(config=tf.ConfigProto(device_count={'GPU': 0}))
    sess.run(tf.global_variables_initializer())
    sess.run(tf.local_variables_initializer())

    with sess.as_default():
        feed_dict = {input_placeholder: np.expand_dims(img, axis=2)}
        f_tf = sess.run(fft_filter, feed_dict=feed_dict)

    f_np = cv2.normalize(f_np, None, 0, 255, cv2.NORM_MINMAX).astype(np.uint8)
    f_tf = cv2.normalize(f_tf, None, 0, 255, cv2.NORM_MINMAX).astype(np.uint8)
    cv2.imshow("numpy", f_np)
    cv2.imshow("tensorflow", f_tf)
    cv2.waitKey()
`
result: https://i.stack.imgur.com/0vLSd.png

[](https://i.stack.imgur.com/0vLSd.png)

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): win10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): pip
- TensorFlow version (use command below): 1.15
- Python version: 3.6
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 10.0
- GPU model and memory: 2080Ti 11G

**Comment by gadagashwini** [comment]
@why702, I tried replicating the issue but getting different error, looks like code is incomplete. Can you provide complete code. Please see the gist [here](https://colab.research.google.com/gist/gadagashwini/f257c390760219303aabf242c6f5299c/untitled383.ipynb). Thanks!

**Comment by why702** [comment]
Sorry, Here is my original code.
`
import numpy as np
import cv2
import math
import tensorflow as tf

def LPF_Butterworth(width, height, kRadius, kOrder):
    fltDst = np.empty([height, width])
    cx = width / 2
    cy = height / 2
    for row in range(height):
        for col in range(width):
            kDistance = math.sqrt((col - cx) ** 2 + (row - cy) ** 2)
            fltDst[row][col] = 1 / (1 + pow((kDistance / kRadius),
                                            (2 * kOrder)))
    return fltDst

if __name__ == '__main__':
    img = cv2.imread("xxx.png")
    img = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY).astype(np.float32)
    width = img.shape[1]
    height = img.shape[0]

    inch2mm = 25.4
    m_nDPI = 508
    szImage = (min(width, height) * inch2mm) / m_nDPI
    fcLow = int(szImage * 3 / 2)  # grown-ups
    filter = LPF_Butterworth(width, height, fcLow, 4)

    # use numpy fft2 ===========
    f = np.fft.fft2(img)
    f = np.fft.fftshift(f)
    f_l = f * filter
    f_l = np.fft.ifftshift(f_l)
    f_l = np.fft.ifft2(f_l)
    f_np = np.real(f_l)
    #===========================

    input_placeholder = tf.compat.v1.placeholder(tf.float32,
                                       shape=[height, width, 1],
                                       name='input')

    # use tensorflow fft2d ===========
    tf_filter = tf.convert_to_tensor(filter, dtype=tf.float32)
    tf_filter_comx = tf.expand_dims(tf.complex(tf_filter, tf.zeros(tf_filter.shape)),2)
    # fft_org = tf.fft2d(tf.cast(input_placeholder, tf.complex64))
    fft_org = tf.complex(input_placeholder, tf.zeros(input_placeholder.shape))
    fft_org = tf.fft2d(fft_org)
    fft_org = tf.signal.fftshift(fft_org, axes=[0,1])
    fft_filter = fft_org * tf_filter_comx
    fft_filter = tf.ifft2d(tf.signal.ifftshift(fft_filter, axes=[0,1]))
    fft_filter = tf.real(fft_filter)
    #================================

    sess = tf.Session(config=tf.ConfigProto(device_count={'GPU': 0}))
    sess.run(tf.global_variables_initializer())
    sess.run(tf.local_variables_initializer())

    with sess.as_default():
        feed_dict = {input_placeholder: np.expand_dims(img, axis=2)}
        f_tf = sess.run(fft_filter, feed_dict=feed_dict)

    f_np = cv2.normalize(f_np, None, 0, 255, cv2.NORM_MINMAX).astype(np.uint8)
    f_tf = cv2.normalize(f_tf, None, 0, 255, cv2.NORM_MINMAX).astype(np.uint8)
    cv2.imshow("numpy", f_np)
    cv2.imshow("tensorflow", f_tf)
    cv2.waitKey()
`

**Comment by gadagashwini** [comment]
Was able to replicate the issue with Tf1.15. 
Please find the gist [here](https://colab.sandbox.google.com/gist/gadagashwini/5b034e9985b110e692fbc4695ac70b35/untitled383.ipynb). Thanks!

**Comment by why702** [comment]
> Was able to replicate the issue with Tf1.15.
> Please find the gist [here](https://colab.sandbox.google.com/gist/gadagashwini/5b034e9985b110e692fbc4695ac70b35/untitled383.ipynb). Thanks!

Hi @jvishnuvardhan,
Is something wrong in my code?

**Comment by GerardWalsh** [comment]
I have been trying to implement the [Mosse ](https://www.cs.colostate.edu/~vision/publications/bolme_cvpr10.pdf) tracker in Tensorflow and have run into the same issue. Any updates?

**Comment by mdanatg** [comment]
[fft2d](https://www.tensorflow.org/api_docs/python/tf/signal/fft2d) operates on the innermost 2 dimensions. In your case, `input_placeholder` has shape `[width, height, 1]`, which is probably not what you want (it's also inconsistent with img). If I change the shape to `[width, height]` and remove the calls to `expand_dims` throughout, then the two images become visually indistinguishable.
