### ISSUE TITLE
ImportError:_pywrap_checkpoint_reader

### ISSUE THREAD

**Issue by TaeheeJeong** [tensorflow/tensorflow#36609]
When I tried to run freeze_graph.py, the following import Error comes out.

from tensorflow.python.training import py_checkpoint_reader
ImportError: cannot import name 'py_checkpoint_reader'
 
I found 'py_checkpoint_reader.py' file in tensorflow/python/training folder.
But inside of 'py_checkpoint_reader.py' file,

from tensorflow.python._pywrap_checkpoint_reader import CheckpointReader

I cannot find the file '_pywrap_checkpoint_reader.

**Comment by Saduf2019** [comment]
@TaeheeJeong Please provide the exact sequence of commands / steps that you executed before running into the problem along with the tensorflow version.

**Comment by TaeheeJeong** [comment]
inception_v3.pb and   inception_v3.ckpt are copied into this folder.
tf.__version__
'1.15.0'

commands:
tensorflow/tensorflow/python/tools$ python freeze_graph.py
--input_graph=inception_v3.pb --input_binary=true
--input_checkpoint=inception_v3.ckpt --output_graph=inception_v3_frozen.pb
--output_node_name=InceptionV3/Predictions/Reshape_1
Traceback (most recent call last):
  File "freeze_graph.py", line 58, in <module>
    from tensorflow.python.training import py_checkpoint_reader
ImportError: cannot import name 'py_checkpoint_reader'

**Comment by TaeheeJeong** [comment]
I just tried in tf.1.12.0. the same issue is existed.

**Comment by Saduf2019** [comment]
@TaeheeJeong Could you please share the code for "freeze_graph.py" so we could help you resolve the issue

**Comment by TaeheeJeong** [comment]
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/tools/freeze_graph.py




https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/training/py_checkpoint_reader.py

**Comment by Saduf2019** [comment]
@TaeheeJeong 
I have tried the same on nightly version and there is no issue, [gist](https://colab.sandbox.google.com/gist/Saduf2019/6d390784507dbb0c6c92f07fef842c88/latest.ipynb#scrollTo=sb7Mr-WqEWg8) for the same.
As there are dependencies you will have to clone Tensorflow as shown in the gist.

**Comment by TaeheeJeong** [comment]
I tried to run it on gist and got the same error.

[image: image.png]

**Comment by ymodak** [comment]
@TaeheeJeong You have check out r.15 branch since you are using TF 1.15
`!git clone -b r1.15 --single-branch https://github.com/tensorflow/tensorflow.git`
Or you may upgrade your TF version to 2.1 since the import
`from tensorflow.python.training import py_checkpoint_reader` was added then.
See https://github.com/tensorflow/tensorflow/commit/b66e4e833c5aacc31d0feaa629f2d064766a7a0b

**Comment by DhavalNiphade** [comment]
Hi,

I'm running TF version 1.15.2 and I still get the import error from the same place as @TaeheeJeong

Should I upgrade to TF 2.1 just to be able run `freeze_graph.py` ? Or is there a way to stay within 1.15.2 and still be able to use the script.

Thanks!

**Comment by hscient** [comment]
same error
