### ISSUE TITLE
cannot run on x86 emulator android example

### ISSUE THREAD

**Issue by abes975** [tensorflow/tensorflow#3660]
Linux Sabayon 4.3 on intel x86_64 platform 
- cannot build and run an apk for x86_64 cpu android emulator.
- bazel release 0.3.1-2016-08-02 (@8b4df1b)

I run this command in order to build the apk package that I would like to run on x86_64 emulator

bazel build --android_cpu=x86_64 //tensorflow/examples/android:tensorflow_demo

But in 
bazel-bin/tensorflow/examples/android/_dx/tensorflow_demo/native_symlinks/MANIFEST
I
 still see a link to an arm library...

I've  built the library for x86_64 with this

bazel build //tensorflow/examples/android:tensorflow_native_libs --crosstool_top=//external:android/crosstool --cpu=x86_64 --host_crosstool_top=@bazel_tools//tools/cpp:toolchain

I thought that specifying --android_cpu=x86_64 was enough to link the apk towards x86_64 native library

Kind regards.
Seba

**Comment by poxvoculi** [comment]
Assigned to @petewarden, but maybe @martinwicke would recommend following up with bazel project instead?

**Comment by drpngx** [comment]
We had many iterations on that code since Aug. Closing this. Feel free to open a new bug if the problem persists in recent versions.
