### ISSUE TITLE
unable to save the tensorflow hub model of universal lite with tensorflow 1.15

### ISSUE THREAD

**Issue by zayedrais** [tensorflow/tensorflow#36619]
I'm unable to save the model, after trained my data by using hub model of universal lite 2( https://tfhub.dev/google/universal-sentence-encoder-lite/2).

tensorflow== 1.15 tensorflow_hub=0.7.0 python =3.7.6 OS = Window 10 64 bit

** model local**

path ="C:/Users/771556/Downloads/ModelLiteUSE" #url ="https://tfhub.dev/google/universal-sentence-encoder-lite/2" liteModule = hub.Module(path)

input_placeholder = tf.sparse_placeholder(tf.int64, shape=[None, None]) encodings = liteModule( inputs=dict( values=input_placeholder.values, indices=input_placeholder.indices, dense_shape=input_placeholder.dense_shape))

with tf.Session() as sess: spm_path = sess.run(liteModule(signature="spm_path"))

sp = spm.SentencePieceProcessor() sp.Load(spm_path) print("SentencePiece model loaded at {}.".format(spm_path))

def process_to_IDs_in_sparse_format(sp, sentences): ids = [sp.EncodeAsIds(x) for x in sentences] max_len = max(len(x) for x in ids) dense_shape=(len(ids), max_len) values=[item for sublist in ids for item in sublist] indices=[[row,col] for row in range(len(ids)) for col in range(len(ids[row]))] return (values, indices, dense_shape)

def embed(input): values, indices, dense_shape = process_to_IDs_in_sparse_format(sp, input) # Reduce logging output. logging.set_verbosity(logging.ERROR) with tf.Session() as session: session.run([tf.global_variables_initializer(), tf.tables_initializer()]) message_embeddings = session.run( encodings, feed_dict={input_placeholder.values: values, input_placeholder.indices: indices, input_placeholder.dense_shape: dense_shape}) return message_embeddings **Training the data**

TrainModel= embed(file_data.text)

**Saving model**

tf.saved_model.save(TrainModel,'D:/liteTrainmodel')

**Error**
![Capture](https://user-images.githubusercontent.com/16205110/74142686-67f49200-4c1f-11ea-8b2f-07720ffc0f28.JPG)

**Comment by ravikyram** [comment]
@zayedrais 

Can you please provide the simple standalone code with proper indentation or colab link to reproduce the issue in our environment. It helps us in localizing the issue faster. Thanks!

**Comment by zayedrais** [comment]
> @ravikyram 

kindly find the colab url
https://colab.research.google.com/drive/1r7nPKTL4SWhkBvXQ3mr42iXm8cA17xJ0

**Comment by zayedrais** [comment]
@ravikyram 

kindly find the colab url
https://colab.research.google.com/drive/1r7nPKTL4SWhkBvXQ3mr42iXm8cA17xJ0

**Comment by gowthamkpr** [comment]
@zayedrais As per saving the train data, you cannot save it as there is no graph associated with it.
and that is the reason why `tf.saved_model.save(traindata,'/tmp/tfhub_modules')` throws an error.

Also looking at this code
 ```
exported.f = tf.function(
  lambda  x: exported.v * x)
```
`exported.v` comes from a different graph and hence the ValueError.
`ValueError: Tensor("Variable_4:0", shape=(3, 512), dtype=float32_ref) must be from the same graph as Tensor("saver_filename:0", shape=(), dtype=string)`

This is the expected behavior in Tensorflow. For faster response please post this question in stackoverflow as there is a wider community to respond. Thanks!
