### ISSUE TITLE
tensorflow GPU is not installed properly

### ISSUE THREAD

**Issue by Kaushikudaya** [tensorflow/tensorflow#36614]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: Laptop
- TensorFlow installed from (source or binary): source
- TensorFlow version: 2.1.0
- Python version:3.7.4
- Installed using virtualenv? pip? conda?: using pip
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: CUDA: 10.2 , cuDNN: 7.6.5
- GPU model and memory: GeForce GTX 1650 , 4GB GPU memory
- System Configuration: intel i7 processor, 1 TB memory, 8 GB RAM.

**Describe the problem**

**Provide the exact sequence of commands / steps that you executed before running into the problem**
Executed below code than the eror occured which is pasted in the file "tensorflow installation error":
"from tensorflow.examples.tutorials.mnist import input_data
mnist = input_data.read_data_sets("MNIST_data/", one_hot=True)"

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

[tensorflow installation error.txt](https://github.com/tensorflow/tensorflow/files/4179294/tensorflow.installation.error.txt)

**Comment by Saduf2019** [comment]
@Kaushikudaya 
Could you please check [this](https://github.com/tensorflow/tensorflow/issues/36167#issuecomment-577886156) comment on a similar issue and let us know if it helps. Thanks!

**Comment by ravikyram** [comment]
@Kaushikudaya 
What is make/model of your cpu?
I suspect your cpu model does not support AVX instructions sets.See [hardware requirements](https://www.tensorflow.org/install/pip?lang=python3#hardware-requirements)
Make sure to download the latest [microsoft visual c++ redistributable from here](https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads).
Make sure you update environment path for cuda(please refer this https://www.tensorflow.org/install/gpu#windows_setup ). Make sure if there is a library that is in a different location/not installed on your system that cannot be loaded.Also, please follow the instructions from Tensorflow website.
Please, check Your CPU/Python is on 32 bits?Please, refer #36167 and see if it helps you. Thanks!

**Comment by Kaushikudaya** [comment]
Hi Team,

That error was solved after updating the tensorflow to 2.0
but i am getting other error:
[image: image.png]


Please check

**Comment by Saduf2019** [comment]
@Kaushikudaya Please share complete executable code and the error **log** faced for us to replicate the issue and help

**Comment by Saduf2019** [comment]
@Kaushikudaya Could you please respond to the above comment

**Comment by Saduf2019** [comment]
@Kaushikudaya Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
