### ISSUE TITLE
tf.saved_model.save can not save a model containing DenseHashTable

### ISSUE THREAD

**Issue by doldre** [tensorflow/tensorflow#36615]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): colab
- TensorFlow installed from (source or binary): source 
- TensorFlow version (use command below):  tf-nightly(2.2.0.dev20200208)

**Describe the current behavior**
A keras model which contains DenseHashTable cannot be saved by tf.saved_model.save function.
Got a "RuntimeError: Attempting to capture an EagerTensor without building a function."

**Describe the expected behavior**
Save the model correctly.

**Code to reproduce the issue**
Here is the simplest situation.
```python
import tensorflow as tf

class Model(tf.keras.Model):

  def __init__(self):
    super(Model, self).__init__()
    self.table = tf.lookup.experimental.DenseHashTable(
        key_dtype=tf.int64,
        value_dtype=tf.int64,
        default_value=-1,
        empty_key=0,
        deleted_key=-1)

  @tf.function(input_signature=[tf.TensorSpec(shape=[None], dtype=tf.int64)])
  def call(self, input):
    return self.table.lookup(input)

m = Model()
tf.saved_model.save(m, '/tmp/test')
```

[Here](https://colab.research.google.com/drive/1ENfP-3vp1c7hoRQU-0egTngatcMMYsMp) is the code gist.

**Comment by Saduf2019** [comment]
i am able to replicate the issue, please find the gist [here](https://colab.research.google.com/gist/Saduf2019/d63cdb41d69ba7e65c91698ce15a0434/36615.ipynb).

**Comment by jvishnuvardhan** [comment]
@doldre As error mentioned model was not built. saving custom_objects (subclassed models, layers) require special attention when saving and loading. Please check more details on saving custom_objects [here](https://www.tensorflow.org/tutorials/keras/save_and_load#saving_custom_objects). Please check even more detailed description on [saving and loading of subclassed models](https://www.tensorflow.org/guide/keras/save_and_serialize#part_ii_saving_and_loading_of_subclassed_models). There is one important line mentioned in the second resource I shared here is `First of all, a subclassed model that has never been used cannot be saved.`

Please close the issue if this was resolved for you. Thanks!

**Comment by jvishnuvardhan** [comment]
When I tried m.summary(), it throws an error as follows. The error trace describes that model has not yet been built.

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-3-0db5d921a66f> in <module>()
----> 1 m.summary()

/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/network.py in summary(self, line_length, positions, print_fn)
   1348     """
   1349     if not self.built:
-> 1350       raise ValueError('This model has not yet been built. '
   1351                        'Build the model first by calling `build()` or calling '
   1352                        '`fit()` with some data, or specify '

ValueError: This model has not yet been built. Build the model first by calling `build()` or calling `fit()` with some data, or specify an `input_shape` argument in the first layer(s) for automatic build.
```

**Comment by doldre** [comment]
I tried to modify the code to below
```python
import tensorflow as tf

class Model(tf.keras.Model):

  def __init__(self):
    super(Model, self).__init__()
    self.table = tf.lookup.experimental.DenseHashTable(
        key_dtype=tf.int64,
        value_dtype=tf.int64,
        default_value=-1,
        empty_key=0,
        deleted_key=-1)

  @tf.function(input_signature=[tf.TensorSpec(shape=[None], dtype=tf.int64)])
  def call(self, input):
    return self.table.lookup(input)
  
  def insert(self, keys, values):
    return self.table.insert(keys, values)

m = Model()
m.insert([1,2,3,4], [4,3,2,1])
print(m([1,2,3,4]))
m.summary()
tf.saved_model.save(m, '/tmp/test') 
```
m.summary() worked, but another exception occured.
```
Tensor("model_16/StatefulPartitionedCall:0", shape=(4,), dtype=int64)
Model: "model_16"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
=================================================================
Total params: 0
Trainable params: 0
Non-trainable params: 0
_________________________________________________________________
WARNING:tensorflow:Skipping full serialization of Keras model <__main__.Model object at 0x7f8b139ef940>, because its inputs are not defined.
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-18-3c22b98a08cb> in <module>()
     23 print(m([1,2,3,4]))
     24 m.summary()
---> 25 tf.saved_model.save(m, '/tmp/test')

10 frames
/tensorflow-1.15.0/python3.6/tensorflow_core/python/framework/ops.py in _assert_same_graph(original_item, item)
   5912   if original_item.graph is not item.graph:
   5913     raise ValueError("%s must be from the same graph as %s." %
-> 5914                      (item, original_item))
   5915 
   5916 

ValueError: Tensor("MutableDenseHashTable_17:0", shape=(), dtype=resource) must be from the same graph as Tensor("serving_default_input:0", shape=(?,), dtype=int64).
```

**Comment by rmothukuru** [comment]
@doldre,
The error seems to be resolved in the **`Latest Version of Tensorflow (2.4.1)`**. Please find [the Gist](https://colab.research.google.com/gist/rmothukuru/d63ec7e7de7a272dabaeb511b272c047/36615.ipynb) of the **`Working Code`**. Thanks!

**Comment by doldre** [comment]
> @doldre,
> The error seems to be resolved in the **`Latest Version of Tensorflow (2.4.1)`**. Please find [the Gist](https://colab.research.google.com/gist/rmothukuru/d63ec7e7de7a272dabaeb511b272c047/36615.ipynb) of the **`Working Code`**. Thanks!

Yes, It is resolved!
