### ISSUE TITLE
cannot resolve external symbol __imp_TF_Version

### ISSUE THREAD

**Issue by ccl-private** [tensorflow/tensorflow#36613]
I dowload tensorflow c libs from: https://tensorflow.google.cn/install/lang_c.
when I try to use these libs with vs2019, it turn out an error message: cannot resolve external symbol __imp_TF_Version

**Comment by ccl-private** [comment]
The codes are from https://tensorflow.google.cn/install/lang_c too.
#include <stdio.h>
#include <tensorflow/c/c_api.h>

int main() {
	printf("Hello from TensorFlow C library version %s\n", TF_Version());
	return 0;
}

**Comment by gadagashwini** [comment]
@ccl-private, Provide the exact sequence of commands / steps that you executed before running into the problem. Thanks!

**Comment by gadagashwini** [comment]
@ccl-private, Any update?

**Comment by gadagashwini** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
