### ISSUE TITLE
Unimplemented: Cast string to float is not supported

### ISSUE THREAD

**Issue by Krishnarohith10** [tensorflow/tensorflow#36623]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10 1909
- TensorFlow version (use command below): 2.1.0-gpu-version
- Python version: 3.6.9
- CUDA/cuDNN version: 10.1.243/7.6.5
- GPU model and memory: GTX 1660 ti 6GB and 32GB (available 28GB)

**Describe the current behavior**
I am working on nlp-getting-started compitetion from kaggle and written code but when executing I'm getting this issue and it doesn't seems to go furthuer or it is not even showing error and exiting it is just showing this and waiting...
Here is the snap of the error
![1](https://user-images.githubusercontent.com/44919399/74157450-4eaf0e00-4c3e-11ea-8a26-7ea1947a5d5b.jpg)

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

import re
import nltk
import numpy as np
import pandas as pd
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.layers import Embedding, LSTM, Dense
from tensorflow.keras.preprocessing.sequence import pad_sequences

vocab_size = 10000
batch_size = 32
epochs = 4
max_len = 25

train_df = pd.read_csv('train.csv')
test_df = pd.read_csv('test.csv')

def clean_text(text):
    text = re.sub(r'https?://\S+|www\.\S+', '', text)
    text = re.sub(r'[^a-zA-Z]', ' ', text)
    text = text.lower()
    text = text.split()
    text = [word for word in text if not word in set(nltk.corpus.stopwords.words('english'))]
    text = ' '.join(text)
    return text

train_df['text'] = train_df['text'].apply(lambda x: clean_text(x))
x_train, y_train = train_df.iloc[:, 3].values, train_df.iloc[:, 4].values

tokenizer = Tokenizer(num_words=vocab_size)

tokenizer.fit_on_texts(x_train)
sequences = tokenizer.texts_to_sequences(x_train)
x_train_new = pad_sequences(sequences, maxlen=max_len)

model = Sequential()
model.add(Embedding(vocab_size, 128))
model.add(LSTM(128, dropout=0.2))
model.add(Dense(32, activation='relu'))
model.add(Dense(1, activation='sigmoid'))

model.compile(loss='binary_crossentropy', optimizer = 'RMSprop', metrics=['accuracy'])

model.fit(x_train, y_train, batch_size=batch_size, epochs=epochs, verbose = 1)

And also when I press ctrl+c then it gets this message
![2](https://user-images.githubusercontent.com/44919399/74158187-a13cfa00-4c3f-11ea-810b-694e53158c47.jpg)

Thanks in advance. Please help me find the error and correct it.

**Comment by Krishnarohith10** [comment]
Sorry this is the dumbest question I ever posted. The solution is this:

model.fit(x_train_new, y_train, batch_size=batch_size, epochs=epochs, verbose=1)

have you observed it. I didn't used padded sequence as input. I must use it and padded input is x_train_new not x_train. Ah! I hate Myself for this.

**Comment by neenaloysius** [comment]
> Sorry this is the dumbest question I ever posted. The solution is this:
> 
> model.fit(x_train_new, y_train, batch_size=batch_size, epochs=epochs, verbose=1)
> 
> have you observed it. I didn't used padded sequence as input. I must use it and padded input is x_train_new not x_train. Ah! I hate Myself for this.

Im also getting similar error. Is it like the training data sequence and the label sequence length in Y_train should be same?
UnimplementedError: 2 root error(s) found.
  (0) Unimplemented:  Cast string to float is not supported
	 [[node CTC-MODEL/Cast (defined at <ipython-input-17-1bb769e8dc7d>:2) ]]
  (1) Cancelled:  Function was cancelled before it was started

**Comment by Krishnarohith10** [comment]
For me, Y_train is not a sequence. If you have Y_train as a sequence, then also why would you get this error. Just apply tokenizer and pad_sequences to Y_train data too. That's should solve it. If it is not sequenced data, then you don't need to but carefully check or send me the required information to reproduce your code error.

**Comment by neenaloysius** [comment]
My input is Sign Video and the output is labels corresponding to the signs in the video. Eg.  label sequence could be COMING HOME FRIEND MY.  What Im trying to do is put all the required frames to a folder and read N (20) frames and the corresponding tokenized label sequence (max length is 12, so all are padded to make it 12) written to a txt file, at a time. My doubt is the input video has 20 frames. But the padded label sequence length is just 12. How this difference is handled in the code?? Do v need to do some extra formatting with the labels?? I have shared the colab file and dataset with you, check gmail, to reproduce the error.

**Comment by Krishnarohith10** [comment]
okay, I sorry I saw it late. But I will get to it. Maybe it takes some time, so be patient I will contact you if done.
