### ISSUE TITLE
GPU performance of TensorflowLite in C++

### ISSUE THREAD

**Issue by andreydung** [tensorflow/tensorflow#36620]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 16.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below): b44fb933866191b94bed36a80e2b1cfd94589d6d
- Python version: 2.7
- Bazel version (if compiling from source): bazel 2.0.0
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
I'm running TFLite using C++ api through JNI wrapper on Android. Two libraries are built: `libtensorflowlite.so` and `libtensorflowlite_gpu_gl.so` for GPU delegate. It's expected that GPU inference should be faster than CPU inference, as mentioned in https://www.tensorflow.org/lite/performance/benchmarks

**Describe the expected behavior**
We found that GPU delegate has the same performance as CPU, even though invoke() returns `kTfLiteOk`
```
interpreter->Invoke() != kTfLiteOk
```

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

```
void ImageAPI::loadModel(const std::string &model_path) {

    LOGD("initializing Image\n");

    model = tflite::FlatBufferModel::BuildFromFile(model_path.c_str());
    if(!model){
        LOGD("Failed loading model\n");
        printf("Failed to mmap model\n");
        exit(0);
    }

    LOGD("DONE Image\n");

    tflite::ops::builtin::BuiltinOpResolver resolver;
    tflite::InterpreterBuilder(*model, resolver)(&interpreter);

}

void ImageAPI::runImage(const unsigned char *rgb, unsigned char *Image) {

    if (use_gpu) {
        if (!delegate) {
            const TfLiteGpuDelegateOptions options = {
                    .metadata = NULL,
                    .compile_options = {
                            .precision_loss_allowed = 1,  // FP16
                            .preferred_gl_object_type = TFLITE_GL_OBJECT_TYPE_FASTEST
                    },
            };

            delegate = TfLiteGpuDelegateCreate(&options);
            if (interpreter->ModifyGraphWithDelegate(delegate) != kTfLiteOk) {
                exit(0);
            }
        }
    }

    interpreter->AllocateTensors();

    float *image_640 = interpreter->typed_input_tensor<float>(1);
    float *image_320 = interpreter->typed_input_tensor<float>(0);

    for (int i = 0; i < H_LARGE * W_LARGE * CHANNEL3; i++) {
        image_640[i] = rgb[i]/255.;
    }

    for (int i = 0; i < H_SMALL; i++) {
        for (int j = 0; j < W_SMALL; j++) {
            for (int c = 0; c < CHANNEL3; c++) {
                image_320[i * CHANNEL3 * W_SMALL + j * CHANNEL3 + c] = image_640[2 * i * CHANNEL3 * W_LARGE + 2 * j * CHANNEL3  + c];
            }
        }
    }

    if (interpreter->Invoke() != kTfLiteOk) return;

    float *output = interpreter->typed_output_tensor<float>(0);

    for (int i = 0; i < H_LARGE * W_LARGE * CHANNEL3; i++) {
        Image[i] = output[i]*255;
    }
}
```

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by andreydung** [comment]
I did some tracing with SnapDragon Profiler, and found that GPU are not used.

**Comment by terryheo** [comment]
GPU delegate only works on Android and iOS for now.
https://www.tensorflow.org/lite/performance/gpu_advanced

**Comment by andreydung** [comment]
@terryheo This is actually running on an Android phone (NDK r18b). We found that GPU latency is much slower than the one reported on benchmark tool.
