### ISSUE TITLE
Support deeplab v3 model on dsp delegate

### ISSUE THREAD

**Issue by dlaiup** [tensorflow/tensorflow#36629]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using): 1.15
- Are you willing to contribute it (Yes/No):

**Describe the feature and the current behavior/state.**
As tflite can support deeplabv3 on GPU with good performance as shown in:
https://www.tensorflow.org/lite/models/segmentation/overview

But when ran the deeplab v3 model on dsp delegate, found it's very slow and the logs showed the upsupported ops on dsp delegate. @karimnosseir , do you think it's possible to fully support deeplab v3 on dsp delegate:
Model file: https://github.com/tensorflow/tensorflow/files/4182220/deep_lab_v3_mv2.tflite.zip
Converted and quantized from http://download.tensorflow.org/models/deeplabv3_mnv2_dm05_pascal_trainaug_2018_10_01.tar.gz

Here are the logs:
INFO: Initialized TensorFlow Lite runtime.
INFO: Created TensorFlow Lite delegate for Hexagon.
INFO: Hexagon delegate: unsupported node index: 25.

INFO: Hexagon delegate: unsupported node index: 27.

INFO: Hexagon delegate: unsupported node index: 33.

INFO: Hexagon delegate: unsupported node index: 35.

INFO: Hexagon delegate: 32 nodes delegated out of 111 nodes.

INFO: Replacing 32 node(s) with delegate (TfLiteHexagonDelegate) node.

**Will this change the current api? How?** No.

**Who will benefit with this feature?** Developer who is using deeplab v3.

**Any Other info.**

**Comment by bhack** [comment]
https://developer.qualcomm.com/project/image-segmentation-using-deeplabv3

**Comment by karimnosseir** [comment]
Thanks for the request.
I think the main thing missing are SpacetoBatchND and BatchToSpaceND. We will look in adding them.

I am not sure what are your expectations, but just to let you know the model you attached when i ran on 
 Samsung S9 i see ~368ms when run on CPU (4 threads)

**Comment by dlaiup** [comment]
@karimnosseir , Thanks for the support, this model is an example, is it reasonable to expect 3X+ faster on DSP than CPU? Looking forward to trying it out once you can add the support of two missing Ops. Thanks.

**Comment by bhack** [comment]
@karimnosseir Are you sure? Check https://github.com/tensorflow/tensorflow/issues/29509

**Comment by karimnosseir** [comment]
@bhack The model attached by @dlaiup has the SpaceToBatch/BatchToSpace, and my reply is about it, i am assuming the conversion is done not using the new converter.
@dlaiup can you reconvert the model using the new converter and attach the model (set experimental_new_converter=True)

Thanks

**Comment by dlaiup** [comment]
@karimnosseir Sure, this is the new model with experimental_new_converter, please check if that's what you want?
https://github.com/tensorflow/tensorflow/files/4189351/deep_lab_v3_mv2_new.zip

**Comment by karimnosseir** [comment]
@dlaiup I think you set some config incorrectly, the model you are sending has all ops expecting float not uint8.

Can you double check please.

Thanks

**Comment by dlaiup** [comment]
@karimnosseir , Add the two tfllite deeplab_v3 models converted with and without experimental_new_converter:
1. Without experimental_new_converter:
https://github.com/tensorflow/tensorflow/files/4194569/deeplab_v3_quant.zip
2. With experimental_new_converter:
https://github.com/tensorflow/tensorflow/files/4194570/deeplab_v3_quant_new.zip

Please check if they are what you expected. Thanks.

**Comment by bhack** [comment]
@dialup Are you using the nightly version? See https://github.com/tensorflow/tensorflow/issues/29509#issuecomment-580451630

**Comment by dlaiup** [comment]
@bhack , I am using tensorflow 2.1.0 version.

**Comment by dlaiup** [comment]
@karimnosseir , using the correct convert configuration (up to ResizeBilinear_1 layer), the deeplab v3 model is running ok now. Will close this issue. Thanks.

**Comment by dlaiup** [comment]
@bhack Yes, the SpaceToBatchND-Conv2D-BatchToSpaceND can be converted to a single Conv2D, thanks.

**Comment by karimnosseir** [comment]
Glad it is working now.
Do you mind sharing the newly converted model

Thanks

**Comment by bhack** [comment]
@dlaiup There was some changes recently in resize bilinear handling. Check https://github.com/tensorflow/tensorflow/issues/33691.

**Comment by dlaiup** [comment]
@karimnosseir , Sure, here is the converted model. Thanks.
https://github.com/tensorflow/tensorflow/files/4199909/deeplab_v3_quant_new.zip

**Comment by dlaiup** [comment]
@dlaiup Thanks for pointing out. I think that change is mainly for CPU kernels.

**Comment by karimnosseir** [comment]
Thanks for sharing. The new is faster on CPU and can also be fully delegated on Hexagon DSP.
Just tried it ~2x faster than CPU when run on hexagon

**Comment by dlaiup** [comment]
@karimnosseir Yes, it can be fully deployed on DSP. Thanks for the support.
