### ISSUE TITLE
Able to disable auto-insert quantize de-quantize node to quantized model.

### ISSUE THREAD

**Issue by psunn** [tensorflow/tensorflow#36632]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- TensorFlow installed from (source or binary): binary
- TensorFlow version (or github SHA if from source): 1.15.2, 2.1.0

TFLiteConverter will automatically insert quantize and dequantize node to quantized model, so that input and output of the quantized model are float32. (check the code, and model example graph below)

```python
import tensorflow as tf
import numpy as np

def gen_calibration_dataset():
    for _ in range(10):
        yield [np.random.rand(1,2,2,2).astype(np.float32)]

def get_keras_model_conv():
    input_0 = tf.keras.layers.Input(shape=[2, 2, 2])
    conv_0 = tf.keras.layers.Conv2D(filters=2, kernel_size=(2, 2),
                                    activation=tf.nn.relu)(input_0)
    model = tf.keras.models.Model(inputs=[input_0], outputs=[conv_0])
    model.summary()
    return model

def gen_model():

    keras_model = get_keras_model_conv()
    converter = tf.lite.TFLiteConverter.from_keras_model(keras_model)
    converter.optimizations = [tf.lite.Optimize.DEFAULT]
    converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
    converter.representative_dataset = gen_calibration_dataset
    tflite_quant_model = converter.convert()
    open('test.tflite', 'wb').write(tflite_quant_model)

print("TF version: {}".format(tf.__version__))
gen_model()
```

![image](https://user-images.githubusercontent.com/55463253/74179096-ac3e5d00-4c34-11ea-8f92-6eb1015a1f16.png)

Is there any convenient way (through python api) to force the model input,output remain int8 (not auto insert quantize, dequantize node)? I didn't find official doc about this.
If not, is it reasonable to add such feature to TFLiteConverter?

**Comment by Burton2000** [comment]
TfLiteConverterV1 had this option (using inference input/output type attributes) but these seem to have been removed in TfLiteConverterV2?

**Comment by psunn** [comment]
we find on TFLiteConverter V1, we can still got fully quantized model.
check code and model graph below:
```python 
import tensorflow as tf
import numpy as np

def gen_calibration_dataset():
    for _ in range(10):
        yield [np.random.rand(1,2,2,2).astype(np.float32)]
def get_keras_model_conv():
    input_0 = tf.keras.layers.Input(shape=[2, 2, 2])
    conv_0 = tf.keras.layers.Conv2D(filters=2, kernel_size=(2, 2),
                                    activation=tf.nn.relu)(input_0)
    model = tf.keras.models.Model(inputs=[input_0], outputs=[conv_0])
    model.summary()
    return model
def gen_model():
    keras_model = get_keras_model_conv()
    keras_model.save('test_model.h5')
    converter = tf.compat.v1.lite.TFLiteConverter.from_keras_model_file('test_model.h5')
    converter.optimizations = [tf.lite.Optimize.DEFAULT]
    converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
    converter.inference_input_type = tf.int8
    converter.inference_output_type = tf.int8
    converter.representative_dataset = gen_calibration_dataset
    tflite_quant_model = converter.convert()
    open('test.tflite', 'wb').write(tflite_quant_model)
print("TF version: {}".format(tf.__version__))
gen_model()
```
![image](https://user-images.githubusercontent.com/55463253/74254238-149a4680-4ce8-11ea-8c7b-55526495596d.png)

**Comment by akarmi** [comment]
@suharshs, is this the intended behaviour of the TF2.x API? It seems it would be useful to retain the option of not having the model wrapped into Quantize/Dequantize nodes.

**Comment by liufengdb** [comment]
+1 on adding the `inference_input_type` and `inference_type` back in the v2 converter.

**Comment by psunn** [comment]
With latest TensorFlow, this works for INT8/UINT8 models:
`bazel run //tensorflow/lite/tools/optimize:modify_model_interface_main /path-to-semi-quantized-model/model.tflite /path-to-save-fully-quantized-model/model.tflite int8 int8`

**Comment by marksunpeng** [comment]
With latest TensorFlow, it works as:
```
...
converter.representative_dataset = representative_dataset_gen
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
converter.inference_input_type = tf.int8  # or tf.uint8
converter.inference_output_type = tf.int8  # or tf.uint8
```

check this:
https://www.tensorflow.org/lite/performance/post_training_quantization#integer_only
