### ISSUE TITLE
Error when using TensorArray and variables in nested loops

### ISSUE THREAD

**Issue by stilda** [tensorflow/tensorflow#3663]
Hi, I use r0.9 version but still have an error when use nested map_fn and a variable involved in calculations of inner function.

The error is 

tensorflow.python.framework.errors.InvalidArgumentError: Input 0 of node gradients/map/while/map/TensorArrayPack_grad/TensorArrayGrad/TensorArrayGrad was passed string from gradients/map/while/map/TensorArrayPack_grad/TensorArrayGrad/TensorArrayGrad/StackPop:0 incompatible with expected string_ref.

The code is

```
import tensorflow as tf

def inner_loop(t):
    def fn(n): return n + var # using var here leads to the error.
    return tf.map_fn(fn=fn, elems=t, parallel_iterations=1)

def outer_loop(input):
    def fn(n): return inner_loop(n) #if I would return inner_loop(n)+var here no errors appear.
    return tf.map_fn(fn=fn, elems=input, parallel_iterations=1)

with tf.Session() as sess:
    var = tf.Variable(tf.constant(1.0))
    input = tf.to_float(tf.convert_to_tensor([[1,2],[3,4],[5,6]]))
    res = outer_loop(input)
    optimizer = tf.train.AdamOptimizer(learning_rate=0.001)
    trainOperation = optimizer.minimize(tf.reduce_mean(tf.square(res)))
    sess.run(tf.initialize_all_variables())
    sess.run(trainOperation)
```

**Comment by thomasquintana** [comment]
+1 I'm having the same issue with the scan function.

**Comment by barimohsin** [comment]
+1. scan issues in nested condition throwing exception

**Comment by hhexiy** [comment]
+1. Same issue when using map_fn inside dynamic_rnn.

**Comment by hhexiy** [comment]
Update: the newest version fixed this issue. However, if parallel_iterations > 1, I got the following error:
W tensorflow/core/framework/op_kernel.cc:968] Invalid argument: TensorArray map/while/map/TensorArray_2_6@gradients: Could not read index 1 twice because it was cleared after a previous read (perhaps try setting clear_after_read = false?).
W tensorflow/core/framework/op_kernel.cc:968] Invalid argument: TensorArray map/while/map/TensorArray_2_2@gradients: Could not read index 0 twice because it was cleared after a previous read (perhaps try setting clear_after_read = false?).

**Comment by ebrevdo** [comment]
Can you give a short code snippet that allows us to replicate the problem?

**Comment by hhexiy** [comment]
The same snippet---I just changed parallel_iterations to 10.

```
import tensorflow as tf

def inner_loop(t):
    def fn(n): return n + var # using var here leads to the error.
    return tf.map_fn(fn=fn, elems=t, parallel_iterations=10)

def outer_loop(input):
    def fn(n): return inner_loop(n) #if I would return inner_loop(n)+var here no errors appear.
    return tf.map_fn(fn=fn, elems=input, parallel_iterations=10)

with tf.Session() as sess:
    var = tf.Variable(tf.constant(1.0))
    input = tf.to_float(tf.convert_to_tensor([[1,2],[3,4],[5,6]]))
    res = outer_loop(input)
    optimizer = tf.train.AdamOptimizer(learning_rate=0.001)
    trainOperation = optimizer.minimize(tf.reduce_mean(tf.square(res)))
    sess.run(tf.initialize_all_variables())
    sess.run(trainOperation)
```

**Comment by stilda** [comment]
@hhexiy, could you please tell the commit / branch where you found it working?

**Comment by yuanbyu** [comment]
Yes, this is probably a known bug. We are working on a fix.  In the meantime, for now could you please set `parallel_partitions` to 1 for the outer loop/map?

**Comment by hhexiy** [comment]
commit 647fb04b233f0476d46ce449125c7cc4087c8b81
Author: Tijmen Tieleman <tijmentieleman@gmail.com>
Date:   Thu Aug 18 14:27:05 2016 -0700

**Comment by yuanbyu** [comment]
A possible fix should be available in the next push.

**Comment by yuanbyu** [comment]
By the way, thank you so much for the simple test case!

**Comment by davidbuniat** [comment]
Hi, 

I am using rnn.row_rnn() with loop_fn which reads and writes a tensor_array of hidden states (e.g. I need more than one timestep memory) and I get the same error. Setting parallel_iterations =1 does not help me to move on. 

In case of creating a python queue (or simply an array of cell_states) in the loop and passing it as a loop_state will still everything work fine in a Tensor graph while computing the gradients and the rest?

**Comment by ebrevdo** [comment]
Davit, can you post the minimal failing example?  This has worked for us
fine.  You just have to ensure your updated TensorArray objects are fed
back to the loop as outputs and you never access these temporary
TensorArray objects outside the loop_fn.

**Comment by davidbuniat** [comment]
The problem arises when I take one state from loop_state and concat with current state. Sorry if its not the minimal I just wanted to give the whole context.

`            def loop_fn(time, cell_output, cell_state, loop_state):
                emit_output = cell_output  # == None for time == 0

                if loop_state == None:
                    loop_state = tf.TensorArray(dtype=tf.float32, size=args.width*args.height)
                    t = []
                    for i in xrange(args.width):
                        t.append(cell.zero_state(args.batch_size, tf.float32))
                    loop_state.unpack(t)

                if cell_state == None:
                    state = cell.zero_state(args.batch_size, tf.float32)
                else:  
                    state = tf.cond(tf.reduce_all((time+1)%args.width == tf.constant(0)), 
                        lambda: cell.zero_state(args.batch_size, tf.float32), 
                        lambda: cell_state, name=None)

                #State issues
                prev_state_x = tf.slice(state, [0, 0], [-1, output_size*4])
                prev_state_y = loop_state.read(time%args.width)
                prev_state_y = tf.slice(prev_state_y, [0, output_size*4], [-1, output_size*2])
                state = tf.concat(1,[prev_state_x, prev_state_y]) # <---- Problem

                next_cell_state = state

                elements_finished = (time >= sequence_length)
                finished = tf.reduce_all(elements_finished)
                next_input = tf.cond(
                    finished,
                    lambda: tf.zeros([args.batch_size, input_size], dtype=tf.float32),
                    lambda: inputs_ta.read(time))

                loop_state.write((time)%args.width, state)
                next_loop_state = loop_state

                return (elements_finished, next_input, next_cell_state,
                        emit_output, next_loop_state)

            outputs_ta, final_state, _ = rnn.raw_rnn(cell, loop_fn, parallel_iterations=1)
`

**Comment by ebrevdo** [comment]
We'll try to make a minimal unit test out of this and see what's going on.

**Comment by davidbuniat** [comment]
Great thanks! I am implementing Multidim RNNs  and if I can be helpful in anyway let me know.

**Comment by ebrevdo** [comment]
I tried writing a unit test that mixes state & loop_state like yours, but was not able to get it to fail.  Are you using a TF nightly build?

Also, this line:

```
state = tf.cond(tf.reduce_all((time+1)%args.width == tf.constant(0)), 
                        lambda: cell.zero_state(args.batch_size, tf.float32), 
                        lambda: cell_state, name=None)
```

what happens if you just set state = cell_state?

I'm still waiting for Yuan's improved debugging to be pushed to github, guess it's gonna be another day or so?  In the meantime we don't have very useful error messages.

**Comment by davidbuniat** [comment]
I moved to nightly build on docker. I tried to set state = cell_state as well, but no difference. If I write instead of `prev_state_y = tf.slice(prev_state_y, [0, output_size*4], [-1, output_size*2])` 
this 
`prev_state_y = tf.slice(state, [0, output_size*4], [-1, output_size*2])`
Then it works like a usual RNN without giving any error on reading or writing the loop_state TensorArray

**Comment by davidbuniat** [comment]
I simplified the case as much as I could 

```
            def loop_fn(time, cell_output, cell_state, loop_state):
                emit_output = cell_output
                if loop_state == None:
                    loop_state = tf.TensorArray(dtype=tf.float32, size=args.width*args.height)
                    for i in xrange(args.width):
                        loop_state.write(i, cell.zero_state(args.batch_size, tf.float32))

                elements_finished = (time >= sequence_length)
                next_input = inputs_ta.read(time)

                next_cell_state = loop_state.read(time)
                next_loop_state = loop_state
                return (elements_finished, next_input, next_cell_state,
                        emit_output, next_loop_state)
```
and this produces the following error

```
...
InvalidArgumentError (see above for traceback): TensorArray content_vgg/gridrnn_1/RNN/TensorArray_0: Could not read from TensorArray index 0 because it has not yet been written to.
	 [[Node: content_vgg/gridrnn_1/RNN/TensorArrayRead_1 = TensorArrayRead[_class=["loc:@content_vgg/gridrnn_1/RNN/TensorArray"], dtype=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"](content_vgg/gridrnn_1/RNN/TensorArray, content_vgg/gridrnn_1/RNN/Const, content_vgg/gridrnn_1/RNN/TensorArray/Const)]]

```

**Comment by davidbuniat** [comment]
Ok, problem is now resolved sorry for disturbance.  @ebrevdo I haven't noticed that TensorArray.write actually returns a new array so basically I was supposed to reassign loop_state on every write. Thank you very much.

**Comment by ebrevdo** [comment]
Ah OK.  yes i was about to say that :)  it's a structure that is as
functional as possible; if you don't use the return value it skips the
write.

**Comment by s4sarath** [comment]
@ebrevdo - Hi , is this a Issue in the following code , I am not able to find out , what i am doing wrong with this following snippet

`import tensorflow as tf
from tensorflow.python.ops import tensor_array_ops
import numpy as np

def body(time_var, attention_tracker):
    a = tf.random_uniform(shape=[2, 2], dtype=tf.int32, maxval=100)
    b = tf.constant(np.array([[1, 2], [3, 4]]), dtype=tf.int32)
    c = a + b
    attention_tracker.write(time_var, c)
    return time_var+1 ,  attention_tracker

def condition(time_var, attention_tracker):
    return time_var < 10

x = tf.Variable(tf.constant(0, shape=[2, 2]))
attention_tracker = tensor_array_ops.TensorArray(tf.float32, size=1, dynamic_size=True, infer_shape=False)

time = tf.constant(0)
time_new , attention_tracker_result = tf.while_loop(condition, body, [time, attention_tracker])

with tf.Session():
    tf.initialize_all_variables().run()
    
    print(attention_tracker_result.pack().eval())`

The error is InvalidArgumentError: TensorArray TensorArray: Could not read from TensorArray index 0 because it has not yet been written to.

**Comment by drpngx** [comment]
Closing this since it's based on old code. Feel free to open a new issue if the problem persists with new code.
