### ISSUE TITLE
Tensorflow lite NnApiDelegate crashes on Pixel 3a XL

### ISSUE THREAD

**Issue by helloworld1** [tensorflow/tensorflow#36645]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
Android
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
Arch Linux
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
Pixel 3A XL running on Android 10
- TensorFlow installed from (source or binary):
binary
- TensorFlow version (use command below):
2.1.0
- Python version:
3.7.0

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
Run tensorflow lite and specify the intepreter options with NnApiDelegete()
```
            val opts = Interpreter.Options()
            opts.setNumThreads(NUM_LITE_THREADS)
            opts.addDelegate(NnApiDelegate())
            return@use Interpreter(modelBuffer, opts)
```
**Describe the expected behavior**
The code runs fine on emulator

**Code to reproduce the issue**
Add NnApiDelegete and the code crashes on Pixel 3a XL

**Other info / logs**
```
020-02-10 21:38:54.173 18949-18999/org.liberty.android.nlplib_demo E/ExecutionBuilder: ANeuralNetworksExecution_setInputFromMemory: Setting with operand type that is not fully specified
    
    --------- beginning of crash
2020-02-10 21:38:54.182 18949-18949/org.liberty.android.nlplib_demo E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.liberty.android.nlplib_demo, PID: 18949
    java.lang.IllegalArgumentException: Internal error: Failed to run on the given Interpreter: NN API returned error ANEURALNETWORKS_BAD_DATA at line 3126 while associating NNAPI execution input with a memory object.
    
    Node number 2428 (TfLiteNnapiDelegate) failed to invoke.
    
        at org.tensorflow.lite.NativeInterpreterWrapper.run(Native Method)
        at org.tensorflow.lite.NativeInterpreterWrapper.run(NativeInterpreterWrapper.java:154)
        at org.tensorflow.lite.Interpreter.runForMultipleInputsOutputs(Interpreter.java:311)
        at org.liberty.android.nlplib.gpt2.GPT2Client$generate$1.invokeSuspend(GPT2Client.kt:70)
        at org.liberty.android.nlplib.gpt2.GPT2Client$generate$1.invoke(Unknown Source:10)
        at kotlinx.coroutines.flow.SafeFlow.collect(Builders.kt:53)
        at org.liberty.android.nlplib_demo.MainActivity$onCreate$4$1$1.invokeSuspend(MainActivity.kt:65)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:241)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:740)
```

**Comment by jdduke** [comment]
Thanks for the report, any chance you could attach the model, and/or a stripped version of the model? Feel free to PM me a link directly if there is any sensitivity, using my alias at google dot com.

**Comment by helloworld1** [comment]
The model is this:
https://s3.amazonaws.com/models.huggingface.co/bert/gpt2-64-fp16.tflite

The sample code is here: (Need to add `opts.addDelegate(NnApiDelegate())`
https://github.com/huggingface/tflite-android-transformers/blob/master/gpt2/src/main/java/co/huggingface/android_transformers/gpt2/ml/GPT2Client.kt#L136

**Comment by jdduke** [comment]
Thanks for the report. Out of curiosity, since it looks like you used the fp16 compression feature, does the original full float model work properly with NNAPI? Or do you have a link to the fp32 model?

**Comment by helloworld1** [comment]
I tried the original FP32 version https://s3.amazonaws.com/models.huggingface.co/bert/gpt2-64.tflite.
It was converted from this model: https://s3.amazonaws.com/models.huggingface.co/bert/gpt2-tf_model.h5

It still crashes with fp32 model.
```
2020-02-11 14:20:21.400 23855-23921/org.liberty.android.nlplib_demo E/Utils: The given inputs and outputs for operation MEAN are only supported in HAL version 1.1 and later (validating using HAL version 1.0)
2020-02-11 14:20:21.400 23855-23921/org.liberty.android.nlplib_demo E/ExecutionBuilder: NN_RET_CHECK failed (frameworks/ml/nn/common/OperationsUtils.cpp:61): The given inputs and outputs are only supported in HAL version 1.2 and later (validating using HAL version 1.0)
2020-02-11 14:20:21.400 23855-23921/org.liberty.android.nlplib_demo E/Utils: Validation failed for operation RSQRT
2020-02-11 14:20:21.400 23855-23921/org.liberty.android.nlplib_demo E/ExecutionBuilder: NN_RET_CHECK failed (frameworks/ml/nn/common/OperationsUtils.cpp:61): The given inputs and outputs are only supported in HAL version 1.1 and later (validating using HAL version 1.0)
2020-02-11 14:20:21.400 23855-23921/org.liberty.android.nlplib_demo E/ExecutionBuilder: NN_RET_CHECK failed (frameworks/ml/nn/common/operations/Broadcast.cpp:358): validateHalVersion(context, std::max(HalVersion::V1_0, opIntroducedAt)) 
2020-02-11 14:20:21.400 23855-23921/org.liberty.android.nlplib_demo E/Utils: Validation failed for operation SUB
2020-02-11 14:20:21.680 23855-23855/org.liberty.android.nlplib_demo E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.liberty.android.nlplib_demo, PID: 23855
    java.lang.IllegalArgumentException: Internal error: Failed to apply delegate: NN API returned error ANEURALNETWORKS_BAD_DATA at line 1068 while setting new operand value.
```

**Comment by miaowang14** [comment]
Could you post the logcat with "adb shell setprop debug.nn.vlog 1"? The verbose logging would helpful figuring out the root cause.

**Comment by helloworld1** [comment]
[log-with-debug-nn-vlog-1.log](https://github.com/tensorflow/tensorflow/files/4189969/log-with-debug-nn-vlog-1.log)

I have added the log file with debug on

**Comment by freedomtan** [comment]
@miaowang14 and @jdduke: in case you don't have time to take a look at it yet. I dug a bit into it. The
```
NN API returned error ANEURALNETWORKS_BAD_DATA at line 1068 while setting new operand value.
```
messages were caused by a scalar as the second operands of the Pow op,
```
{'name': 'tfgp_t2lm_head_model/transformer/h_._0/mlp/Pow', 'index': 360, 'shape': array([   1,   64, 3072], dtype=int32), 'shape_signature': array([   1,   64, 3072], dtype=int32), 'dtype': <class 'numpy.float32'>, 'quantization': (0.0, 0), 'quantization_parameters': {'scales': array([], dtype=float32), 'zero_points': array([], dtype=int32), 'quantized_dimension': 0}, 'sparsity_parameters': {}}
{'name': 'tfgp_t2lm_head_model/transformer/h_._0/mlp/Pow/y', 'index': 361, 'shape': array([], dtype=int32), 'shape_signature': array([], dtype=int32), 'dtype': <class 'numpy.float32'>, 'quantization': (0.0, 0), 'quantization_parameters': {'scales': array([], dtype=float32), 'zero_points': array([], dtype=int32), 'quantized_dimension': 0}, 'sparsity_parameters': {}}
```

I ran into similar problem when trying to pass [ALBERT](https://github.com/google-research/ALBERT) squad_v1 to NNAPI delegate.

**Comment by freedomtan** [comment]
@helloworld1 with my one-line patch, you should be able to delegate some ops of the model to NNAPI, but don't expect performance improvement yet. On Pixel 4, when I ran [TFLite Model Benchmark Tool](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/tools/benchmark) `./benchmark_model --graph=gpt2-64.tflite --use_nnapi=1 --allow_fp16=1`, I got
```
Number of nodes executed: 111
============================== Summary by node type ==============================
	             [Node type]	  [count]	  [avg ms]	    [avg %]	    [cdf %]	  [mem KB]	[times called]
	     TfLiteNnapiDelegate	       50	  3119.304	    99.837%	    99.837%	     0.000	       50
	      SQUARED_DIFFERENCE	       25	     4.177	     0.134%	    99.970%	     0.000	       25
	                    PACK	       36	     0.925	     0.030%	   100.000%	     0.000	       36

```

As you can see `SQUARED_DIFFERENCE` and `PACK` ops are not supported in NNAPI, the model/graph is divided into > 50 subgraphs and performance doesn't look good.

**Comment by helloworld1** [comment]
Thanks a lot @freedomtan I am going to try your patch out

**Comment by miaowang14** [comment]
Thanks a lot @freedomtan .

Also we are working on limiting the number of partitions when using NNAPI delegate, as it is never a good recipe for performance if we partition a graph into many small subgraphs.

Also, we are considering supporting SQUARED_DIFFERENCE with the ops already supported by NNAPI, e.g. MUL and SUB. Hopefully that could also help with models like this.

**Comment by helloworld1** [comment]
Yes, the patch works and prevent the crash. But the performance regressed by more than 50%.

**Comment by freedomtan** [comment]
@miaowang14 Glad to hear that. Yes, back and forth between CPU and accelerator because of tiny subgraphs doesn't sound right. Any plan for PACK? Converting PACK to RESHAPE + CONCATENATION should work.

**Comment by seagate2014** [comment]
@helloworld1 : Were you able to find some workaround for it ?

**Comment by mohantym** [comment]
Hi @helloworld1! Is this issue still valid in 2.8 version too? I see it has been resolved  from this [comment](https://github.com/tensorflow/tensorflow/issues/36645#issuecomment-595953641). Could you create a new issue to address the performance ?

**Comment by tbikash62** [comment]
Hello 

I'm trying to deploy EfficientDet-4 in the Google Pixel 6 

Using TensorFlow library. 

I'm getting below error using NNAPI. 

E/Manager: IDevice::prepareModel() error: hardware/interfaces/neuralnetworks/aidl/utils/src/Callbacks.cpp:41: model preparation failed with GENERAL_FAILURE
D/AndroidRuntime: Shutting down VM
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.teamviewer.libs.sceneview.sample, PID: 16254
    java.lang.RuntimeException: java.lang.IllegalArgumentException: Internal error: Failed to apply delegate: NN API returned error ANEURALNETWORKS_OP_FAILED at line 4483 while completing NNAPI compilation.

[efficientdet4 working.zip](https://github.com/tensorflow/tensorflow/files/8803485/efficientdet4.working.zip)

However works fine for the GPU & CPU deployments. 

Can you guide me. 

Attaching the model file.

**Comment by LozariaVinok** [comment]
> Hello
> 
> I'm trying to deploy EfficientDet-4 in the Google Pixel 6
> 
> Using TensorFlow library.
> 
> I'm getting below error using NNAPI.
> 
> E/Manager: IDevice::prepareModel() error: hardware/interfaces/neuralnetworks/aidl/utils/src/Callbacks.cpp:41: model preparation failed with GENERAL_FAILURE D/AndroidRuntime: Shutting down VM E/AndroidRuntime: FATAL EXCEPTION: main Process: com.teamviewer.libs.sceneview.sample, PID: 16254 java.lang.RuntimeException: java.lang.IllegalArgumentException: Internal error: Failed to apply delegate: NN API returned error ANEURALNETWORKS_OP_FAILED at line 4483 while completing NNAPI compilation.
> 
> [efficientdet4 working.zip](https://github.com/tensorflow/tensorflow/files/8803485/efficientdet4.working.zip)
> 
> However works fine for the GPU & CPU deployments.
> 
> Can you guide me.
> 
> Attaching the model file.

Hello @tbikash62 . I see this is a really old post, but have you managed to fix this issue?
