### ISSUE TITLE
keras.callbacks.Tensorboard cannot reduce loss and produces error

### ISSUE THREAD

**Issue by Feri73** [tensorflow/tensorflow#36646]
**System information**
- Have I written custom code: Yes
- OS Platform and Distribution: Windows 10
- TensorFlow installed from: binary
- TensorFlow version: 1.15.0
- Python version: 3.6.8
- CUDA/cuDNN version: No GPU

**Describe the current behavior**
When using keras.callbacks.Tensorboard as a callback for fitting a keras model, this error is raised:

`ValueError: can only convert an array of size 1 to a Python scalar`

**Code to reproduce the issue**
```
import tensorflow.keras as keras
import numpy as np

model = keras.Sequential()
model.add(keras.Input(shape=(), batch_size=5))
model.add(keras.layers.Activation('sigmoid'))
model.compile(loss=keras.losses.BinaryCrossentropy())
xs = np.random.normal(size=200)
ys = np.random.randint(0, 2, 200)
cb = keras.callbacks.TensorBoard('tmp')
model.fit(xs, ys, callbacks=[cb], batch_size=5)
```
The code above produces error. If TF 2.0 is used, OR if batch_size=1, the error is gone.

**Comment by gadagashwini** [comment]
@Feri73, Its working without any error, Please take a look at the colab gist [here](https://colab.sandbox.google.com/gist/gadagashwini/294b786c8b8e0de16fe4d91e95ad9278/untitled388.ipynb). Thanks!

**Comment by Feri73** [comment]
The gist uses tf 2.0!

gadagashwini <notifications@github.com> schrieb am Di., 11. Feb. 2020,
22:40:

**Comment by gadagashwini** [comment]
Was able to replicate the issue with Tf 1.15.
Please find the [gist](https://colab.sandbox.google.com/gist/gadagashwini/47dbfb8fc51b92a690ec2b5645c61c70/untitled390.ipynb). Thanks!

**Comment by rmothukuru** [comment]
@Feri73,
As the Tensorflow 1.x is not very active in production and as Tensorflow 2.x is predominantly used, can you please confirm if we can close this issue? Thanks!

**Comment by Feri73** [comment]
It's up to you if you want to ignore an existing bug :) I don't use tf 1.15 any more though.

**Comment by rmothukuru** [comment]
@Feri73,
Closing the issue in line with [this comment](https://github.com/tensorflow/tensorflow/issues/36646#issuecomment-730396618). Thanks!
