### ISSUE TITLE
IndexError: list index out of range when using tf.dataset and keras for autoencoder

### ISSUE THREAD

**Issue by jdchancellor** [tensorflow/tensorflow#36649]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10, anaconda, python 3.7.6
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): tensorflow 2.0.0 (using tensorflow gpu)
- Python version:3.7.6
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: cudnn -7.6.5 /  cuda - 10.0
- GPU model and memory: GeForce GTX 1050Ti, 4Gb of memory (anaconda sees 2996MB)

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`
unknown 2.0.0
**Describe the current behavior**
I'm trying to build an autoencoder using tensorflow keras using a sample of png files.   I've built a pipeline using the tensor flow dataset following closely to the tutorial provided here - https://www.tensorflow.org/guide/data#decoding_image_data_and_resizing_it .   I can see a tensor properly generated with the expected batch and shape.   The model also summarizes and compiles successfully, but when I do a model.fit to begin training, I get an error: IndexError: list index out of range. (full stack track below).  

**Describe the expected behavior**
Model should begin training.

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.
`import tensorflow as tf
PNG_ROOT = 'g:/data/video/'
data_dir = PNG_ROOT + "*/*"
list_ds = tf.data.Dataset.list_files(data_dir)

def decode_img(img):
  # convert the compressed string to a 3D uint8 tensor
  IMG_WIDTH = 360
  IMG_HEIGHT = 360
  img = tf.io.decode_png(img, channels=3)
  img = tf.image.resize_with_crop_or_pad(img, target_height=IMG_HEIGHT, target_width=IMG_WIDTH)  
  # Use `convert_image_dtype` to convert to floats in the [0,1] range.
  img = tf.image.convert_image_dtype(img, tf.float32) 
  return img

def process_path(file_path):
  img = tf.io.read_file(file_path)
  image_tensor = decode_img(img)  
  image_tensor = tf.reshape(image_tensor,(360,360,3))
  #return img, label
  return image_tensor

batch_size = 8
labeled_ds = list_ds.map(process_path)
labeled_ds = labeled_ds.batch(batch_size)
ds_train= labeled_ds.take(1000)
ds_validate = labeled_ds.take(50)

from tensorflow.keras.models import Model
from tensorflow.keras.layers import Conv2D, Input, MaxPooling2D, UpSampling2D
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.callbacks import EarlyStopping, ModelCheckpoint

#Build Model
input_feature = Input(batch_shape=(8,360,360,3))

x = Conv2D(512, (3,3), activation='relu', input_shape=(8,360,360,3), padding='same')(input_feature)
x = Conv2D(256, (3,3), activation='relu', padding='same')(x)
x = MaxPooling2D(pool_size=2, padding='same')(x)
x = Conv2D(128, (3,3), activation='relu', padding='same')(x)
x = Conv2D(64, (3,3), activation='relu', padding='same')(x)
encoded = MaxPooling2D(pool_size=2, padding='same')(x)

x = Conv2D(64, (3,3), activation='relu', padding='same')(encoded)
x = Conv2D(128, (3,3), activation='relu', padding='same')(x)
x = UpSampling2D((2))(x)
x = Conv2D(256, (3,3), activation='relu', padding='same')(x)
x = Conv2D(512, (3,3), activation='relu', padding='same')(x)
x = UpSampling2D((2))(x)
decoded = Conv2D(3, (3,3), activation='sigmoid', padding='same')(x)

autoencoder = Model(inputs=input_feature, outputs=decoded)
optimizer = tf.keras.optimizers.Adam()
autoencoder.compile(optimizer='adam', loss=tf.keras.losses.MeanSquaredError(), metrics=['accuracy'])
autoencoder.summary()

checkpoint = ModelCheckpoint("best_conv2d_png_v1.hdf5", monitor="val_loss", verbose = 1, save_best_only=True, mode='auto', save_freq=100)
history = autoencoder.fit(ds_train, epochs=5, callbacks=[checkpoint])
`

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

Epoch 1/5
      1/Unknown - 0s 143ms/step
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-150-e74e2479945a> in <module>
      1 #early_stopping = EarlyStopping(monitor='loss', min_delta=0, patience=10, verbose=5, mode='auto')
      2 checkpoint = ModelCheckpoint("best_conv2d_video_v1.hdf5", monitor="val_loss", verbose = 1, save_best_only=True, mode='auto', save_freq=100)
----> 3 history = autoencoder.fit(ds_train, epochs=5, callbacks=[checkpoint])

Z:\anaconda\envs\tf-gpu\lib\site-packages\tensorflow_core\python\keras\engine\training.py in fit(self, x, y, batch_size, epochs, verbose, callbacks, validation_split, validation_data, shuffle, class_weight, sample_weight, initial_epoch, steps_per_epoch, validation_steps, validation_freq, max_queue_size, workers, use_multiprocessing, **kwargs)
    726         max_queue_size=max_queue_size,
    727         workers=workers,
--> 728         use_multiprocessing=use_multiprocessing)
    729 
    730   def evaluate(self,

Z:\anaconda\envs\tf-gpu\lib\site-packages\tensorflow_core\python\keras\engine\training_v2.py in fit(self, model, x, y, batch_size, epochs, verbose, callbacks, validation_split, validation_data, shuffle, class_weight, sample_weight, initial_epoch, steps_per_epoch, validation_steps, validation_freq, **kwargs)
    322                 mode=ModeKeys.TRAIN,
    323                 training_context=training_context,
--> 324                 total_epochs=epochs)
    325             cbks.make_logs(model, epoch_logs, training_result, ModeKeys.TRAIN)
    326 

Z:\anaconda\envs\tf-gpu\lib\site-packages\tensorflow_core\python\keras\engine\training_v2.py in run_one_epoch(model, iterator, execution_function, dataset_size, batch_size, strategy, steps_per_epoch, num_samples, mode, training_context, total_epochs)
    121         step=step, mode=mode, size=current_batch_size) as batch_logs:
    122       try:
--> 123         batch_outs = execution_function(iterator)
    124       except (StopIteration, errors.OutOfRangeError):
    125         # TODO(kaftan): File bug about tf function and errors.OutOfRangeError?

Z:\anaconda\envs\tf-gpu\lib\site-packages\tensorflow_core\python\keras\engine\training_v2_utils.py in execution_function(input_fn)
     84     # `numpy` translates Tensors to values in Eager mode.
     85     return nest.map_structure(_non_none_constant_value,
---> 86                               distributed_function(input_fn))
     87 
     88   return execution_function

Z:\anaconda\envs\tf-gpu\lib\site-packages\tensorflow_core\python\eager\def_function.py in __call__(self, *args, **kwds)
    455 
    456     tracing_count = self._get_tracing_count()
--> 457     result = self._call(*args, **kwds)
    458     if tracing_count == self._get_tracing_count():
    459       self._call_counter.called_without_tracing()

Z:\anaconda\envs\tf-gpu\lib\site-packages\tensorflow_core\python\eager\def_function.py in _call(self, *args, **kwds)
    501       # This is the first call of __call__, so we have to initialize.
    502       initializer_map = object_identity.ObjectIdentityDictionary()
--> 503       self._initialize(args, kwds, add_initializers_to=initializer_map)
    504     finally:
    505       # At this point we know that the initialization is complete (or less

Z:\anaconda\envs\tf-gpu\lib\site-packages\tensorflow_core\python\eager\def_function.py in _initialize(self, args, kwds, add_initializers_to)
    406     self._concrete_stateful_fn = (
    407         self._stateful_fn._get_concrete_function_internal_garbage_collected(  # pylint: disable=protected-access
--> 408             *args, **kwds))
    409 
    410     def invalid_creator_scope(*unused_args, **unused_kwds):

Z:\anaconda\envs\tf-gpu\lib\site-packages\tensorflow_core\python\eager\function.py in _get_concrete_function_internal_garbage_collected(self, *args, **kwargs)
   1846     if self.input_signature:
   1847       args, kwargs = None, None
-> 1848     graph_function, _, _ = self._maybe_define_function(args, kwargs)
   1849     return graph_function
   1850 

Z:\anaconda\envs\tf-gpu\lib\site-packages\tensorflow_core\python\eager\function.py in _maybe_define_function(self, args, kwargs)
   2148         graph_function = self._function_cache.primary.get(cache_key, None)
   2149         if graph_function is None:
-> 2150           graph_function = self._create_graph_function(args, kwargs)
   2151           self._function_cache.primary[cache_key] = graph_function
   2152         return graph_function, args, kwargs

Z:\anaconda\envs\tf-gpu\lib\site-packages\tensorflow_core\python\eager\function.py in _create_graph_function(self, args, kwargs, override_flat_arg_shapes)
   2039             arg_names=arg_names,
   2040             override_flat_arg_shapes=override_flat_arg_shapes,
-> 2041             capture_by_value=self._capture_by_value),
   2042         self._function_attributes,
   2043         # Tell the ConcreteFunction to clean up its graph once it goes out of

Z:\anaconda\envs\tf-gpu\lib\site-packages\tensorflow_core\python\framework\func_graph.py in func_graph_from_py_func(name, python_func, args, kwargs, signature, func_graph, autograph, autograph_options, add_control_dependencies, arg_names, op_return_value, collections, capture_by_value, override_flat_arg_shapes)
    913                                           converted_func)
    914 
--> 915       func_outputs = python_func(*func_args, **func_kwargs)
    916 
    917       # invariant: `func_outputs` contains only Tensors, CompositeTensors,

Z:\anaconda\envs\tf-gpu\lib\site-packages\tensorflow_core\python\eager\def_function.py in wrapped_fn(*args, **kwds)
    356         # __wrapped__ allows AutoGraph to swap in a converted function. We give
    357         # the function a weak reference to itself to avoid a reference cycle.
--> 358         return weak_wrapped_fn().__wrapped__(*args, **kwds)
    359     weak_wrapped_fn = weakref.ref(wrapped_fn)
    360 

Z:\anaconda\envs\tf-gpu\lib\site-packages\tensorflow_core\python\keras\engine\training_v2_utils.py in distributed_function(input_iterator)
     71     strategy = distribution_strategy_context.get_strategy()
     72     outputs = strategy.experimental_run_v2(
---> 73         per_replica_function, args=(model, x, y, sample_weights))
     74     # Out of PerReplica outputs reduce or pick values to return.
     75     all_outputs = dist_utils.unwrap_output_dict(

Z:\anaconda\envs\tf-gpu\lib\site-packages\tensorflow_core\python\distribute\distribute_lib.py in experimental_run_v2(self, fn, args, kwargs)
    758       fn = autograph.tf_convert(fn, ag_ctx.control_status_ctx(),
    759                                 convert_by_default=False)
--> 760       return self._extended.call_for_each_replica(fn, args=args, kwargs=kwargs)
    761 
    762   def reduce(self, reduce_op, value, axis):

Z:\anaconda\envs\tf-gpu\lib\site-packages\tensorflow_core\python\distribute\distribute_lib.py in call_for_each_replica(self, fn, args, kwargs)
   1785       kwargs = {}
   1786     with self._container_strategy().scope():
-> 1787       return self._call_for_each_replica(fn, args, kwargs)
   1788 
   1789   def _call_for_each_replica(self, fn, args, kwargs):

Z:\anaconda\envs\tf-gpu\lib\site-packages\tensorflow_core\python\distribute\distribute_lib.py in _call_for_each_replica(self, fn, args, kwargs)
   2130         self._container_strategy(),
   2131         replica_id_in_sync_group=constant_op.constant(0, dtypes.int32)):
-> 2132       return fn(*args, **kwargs)
   2133 
   2134   def _reduce_to(self, reduce_op, value, destinations):

Z:\anaconda\envs\tf-gpu\lib\site-packages\tensorflow_core\python\autograph\impl\api.py in wrapper(*args, **kwargs)
    290   def wrapper(*args, **kwargs):
    291     with ag_ctx.ControlStatusCtx(status=ag_ctx.Status.DISABLED):
--> 292       return func(*args, **kwargs)
    293 
    294   if inspect.isfunction(func) or inspect.ismethod(func):

Z:\anaconda\envs\tf-gpu\lib\site-packages\tensorflow_core\python\keras\engine\training_v2_utils.py in train_on_batch(model, x, y, sample_weight, class_weight, reset_metrics)
    262       y,
    263       sample_weights=sample_weights,
--> 264       output_loss_metrics=model._output_loss_metrics)
    265 
    266   if reset_metrics:

Z:\anaconda\envs\tf-gpu\lib\site-packages\tensorflow_core\python\keras\engine\training_eager.py in train_on_batch(model, inputs, targets, sample_weights, output_loss_metrics)
    309           sample_weights=sample_weights,
    310           training=True,
--> 311           output_loss_metrics=output_loss_metrics))
    312   if not isinstance(outs, list):
    313     outs = [outs]

Z:\anaconda\envs\tf-gpu\lib\site-packages\tensorflow_core\python\keras\engine\training_eager.py in _process_single_batch(model, inputs, targets, output_loss_metrics, sample_weights, training)
    250               output_loss_metrics=output_loss_metrics,
    251               sample_weights=sample_weights,
--> 252               training=training))
    253       if total_loss is None:
    254         raise ValueError('The model cannot be run '

Z:\anaconda\envs\tf-gpu\lib\site-packages\tensorflow_core\python\keras\engine\training_eager.py in _model_loss(model, inputs, targets, output_loss_metrics, sample_weights, training)
    164 
    165         if hasattr(loss_fn, 'reduction'):
--> 166           per_sample_losses = loss_fn.call(targets[i], outs[i])
    167           weighted_losses = losses_utils.compute_weighted_loss(
    168               per_sample_losses,

IndexError: list index out of `range`

**Comment by ravikyram** [comment]
@jdchancellor 

Can you please provide colab link or simple standalone code with proper indentation and supporting files to reproduce the issue in our environment. It helps us in localizing the issue faster. Thanks!

**Comment by jdchancellor** [comment]
Thanks for the response.  I'll set up a colab and shoot over a link this
afternoon once I get back to my workstation.

Jon

**Comment by jdchancellor** [comment]
https://colab.research.google.com/drive/1PvEO3waUT1CN_b9MqusrG6CKfKVCd324#scrollTo=BjLA9JsMElSF


Has the stripped down code.   I enabled eager execution since colab is
running TF 1.15 vs 2.0

**Comment by gowthamkpr** [comment]
@jdchancellor  I think you are only specifying inputs not the model outputs. Please take a look this [comment](https://github.com/tensorflow/tensorflow/issues/21894#issuecomment-487746983).

**Comment by jdchancellor** [comment]
I tried this previously.  It appears that tensorflow knows it's an
autoencoder and a tfds dataset as duplicating the input for Y gives the
following error. (or is there some way I need to extract the x values from
the dataset at run time?)  Interestingly, I switched over to using
keras's ImageDataGenerator with flow_from_directory and was able to get the
model to start training (albeit less efficiently).  I got a similar error
there until I set the class_mode to 'input' and then everything worked
normally.  Does tfds have a similar class_mode that isn't apparent in the
documentation?

You passed a dataset or dataset iterator (<DatasetV1Adapter shapes: (?,
360, 360, 3), types: tf.float32>) as input `x` to your model. In that case,
you should not specify a target (`y`) argument, since the dataset or
dataset iterator generates both input data and target data. Received:
<DatasetV1Adapter shapes: (?, 360, 360, 3), types: tf.float32>

**Comment by jvishnuvardhan** [comment]
@jdchancellor Sorry for the late response. Is this still an issue for you? I tried running your colab but don't have access to your data. Can you please update the colab with any public data and share it? Thanks!
