### ISSUE TITLE
`tf.global_variables_initializer()` doesn't work sometimes

### ISSUE THREAD

**Issue by ParikhKadam** [tensorflow/tensorflow#36648]
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- TensorFlow version: 1.14.0
- Python version: 3.8

`tf.global_variables_initializer()` doesn't work sometimes.

```
import tensorflow as tf
init = tf.global_variables_initializer()
a = tf.Variable([1,2,3])
with tf.Session() as s:
    s.run(init)
    s.run(a)
```

The above code throws an error of uninitialized variable.

```
tensorflow.python.framework.errors_impl.FailedPreconditionError: Attempting to use uninitialized value Variable
	 [[{{node _retval_Variable_0_0}}]]
```

While the below code works fine:

```
a = tf.Variable([1,2,3])
with tf.Session() as s:
    s.run(tf.global_variables_initializer())
    s.run(a)
```

Output:
`array([1, 2, 3], dtype=int32)`

**Comment by LoSealL** [comment]
```python
a = tf.Variable([1,2,3])
init = tf.global_variables_initializer()
```

Call `tf.global_variables_initializer()` after all variables you want to init.

**Comment by ParikhKadam** [comment]
@LoSealL

Your solution works. Thank you..

But why is this necessary to call it after? I mean, it too just creates a node to execute and is independent of any other node in the graph, right?

**Comment by amahendrakar** [comment]
@ParikhKadam,
[This](https://stackoverflow.com/a/45047930) StackOverflow comment might answer your query.

**Comment by ParikhKadam** [comment]
Thank you @amahendrakar 

It is a lot helpful..
