### ISSUE TITLE
Throw an error when connecting inputs to weight-shared-embedding-layer more than 5 times.

### ISSUE THREAD

**Issue by tsuzukit** [tensorflow/tensorflow#36642]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Google Colaboratory with Ubuntu 18.04.3 LTS (Bionic Beaver)
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: No
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): v2.1.0-0-ge5bf8de410 2.1.0
- Python version: 3.6.9
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**

When inputs are connected to weight-shared-embedding-layer more than 5 times, tensorflow throws an error while training.

This behavior is not seen with below condition.
- connections to weight-shared-embedding-layer are less than 4
- using tensorflow version 1.15

**Describe the expected behavior**

Successfully train a model using weight-shared-embedding-layer connecting more than 5 inputs.

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

```
import tensorflow as tf
import tensorflow.keras.backend as K
import numpy as np

# changing this to 4 make train success
n_inputs = 5
dim_embedding = 10

inputs = []
for i in range(n_inputs):
  inputs.append(tf.keras.Input(shape=(1,), dtype='int32'))

embeds = []
shared_embed = tf.keras.layers.Embedding(n_input, dim_embedding)
for i in range(n_inputs):
  embed = shared_embed(inputs[i])
  flatten = tf.keras.layers.Flatten()(embed)
  embeds.append(flatten)

concat = tf.keras.layers.Concatenate(axis=1)(embeds)
output = tf.keras.layers.Dense(1)(concat)
model = tf.keras.Model(inputs=[inputs], outputs=[output])
model.summary()

model.compile(optimizer='adam', loss='mse')

# run
dummy_input = []
for i in range(n_shared_layers):
  dummy_input.append(np.random.randint(0, n_input, size=(1000, )))

dummy = np.arange(1000).reshape(1000, 1, 1)

model.fit(x=dummy_input, y=dummy, batch_size=32, epochs=1, verbose=1)
```

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

https://colab.research.google.com/drive/1NV_KXlKRv148H50SExVYdHkVCh9Acnp_?hl=ja#scrollTo=13C17fSiwhAC

**Comment by jvishnuvardhan** [comment]
@tsuzukit Can you please provide a standalone code to reproduce the issue? Thanks!

**Comment by tsuzukit** [comment]
@jvishnuvardhan 

As in original comment, I meant below as minimum standalone code to reproduce the issue.
If you run below in colab, you should be able to reproduce the issue. 
This is the colab I used. https://colab.research.google.com/drive/1NV_KXlKRv148H50SExVYdHkVCh9Acnp_?hl=ja#scrollTo=13C17fSiwhAC

```
import tensorflow as tf
import tensorflow.keras.backend as K
import numpy as np

# changing this to 4 make train success
n_inputs = 5
dim_embedding = 10

inputs = []
for i in range(n_inputs):
  inputs.append(tf.keras.Input(shape=(1,), dtype='int32'))

embeds = []
shared_embed = tf.keras.layers.Embedding(n_input, dim_embedding)
for i in range(n_inputs):
  embed = shared_embed(inputs[i])
  flatten = tf.keras.layers.Flatten()(embed)
  embeds.append(flatten)

concat = tf.keras.layers.Concatenate(axis=1)(embeds)
output = tf.keras.layers.Dense(1)(concat)
model = tf.keras.Model(inputs=[inputs], outputs=[output])
model.summary()

model.compile(optimizer='adam', loss='mse')

# run
dummy_input = []
for i in range(n_shared_layers):
  dummy_input.append(np.random.randint(0, n_input, size=(1000, )))

dummy = np.arange(1000).reshape(1000, 1, 1)

model.fit(x=dummy_input, y=dummy, batch_size=32, epochs=1, verbose=1)
```

Pls let me know if you need any other info!

**Comment by jvishnuvardhan** [comment]
@tsuzukit It is throwing the following error. Thanks!
```
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-6-6b24491b8648> in <module>()
      7 
      8 embeds = []
----> 9 shared_embed = tf.keras.layers.Embedding(n_input, dim_embedding)
     10 for i in range(n_inputs):
     11   embed = shared_embed(inputs[i])

NameError: name 'n_input' is not defined
```

**Comment by tsuzukit** [comment]
@jvishnuvardhan 

Ah, sorry there were typos in the code.
Again, below is complete runnable code along with Colaboratory link that I used.

```
import tensorflow as tf
import tensorflow.keras.backend as K
import numpy as np

# changing this to 4 make train success
n_inputs = 5
n_items = 1000
dim_embedding = 10

inputs = []
for i in range(n_inputs):
  inputs.append(tf.keras.Input(shape=(1,), dtype='int32'))

embeds = []
shared_embed = tf.keras.layers.Embedding(n_items, dim_embedding)
for i in range(n_inputs):
  embed = shared_embed(inputs[i])
  flatten = tf.keras.layers.Flatten()(embed)
  embeds.append(flatten)

concat = tf.keras.layers.Concatenate(axis=1)(embeds)
output = tf.keras.layers.Dense(1)(concat)
model = tf.keras.Model(inputs=[inputs], outputs=[output])
model.summary()

model.compile(optimizer='adam', loss='mse')

# run
dummy_inputs = []
for i in range(n_inputs):
  dummy_inputs.append(np.random.randint(0, n_inputs, size=(n_items, )))

dummy = np.arange(n_items).reshape(n_items, 1, 1)

model.fit(x=dummy_inputs, y=dummy, batch_size=32, epochs=1, verbose=1)
```

https://colab.research.google.com/drive/1NV_KXlKRv148H50SExVYdHkVCh9Acnp_?hl=ja#scrollTo=JuJ1C645yW3x

thanks!

**Comment by jvishnuvardhan** [comment]
Here is the complete error trace for our reference.

```
Train on 1000 samples
  32/1000 [..............................] - ETA: 5s
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
/tensorflow-2.1.0/python3.6/tensorflow_core/python/eager/backprop.py in _num_elements(grad)
    626   if isinstance(grad, ops.IndexedSlices):
--> 627     return functools.reduce(operator.mul, grad.values._shape_tuple(), 1)  # pylint: disable=protected-access
    628   raise ValueError("`grad` not a Tensor or IndexedSlices.")

TypeError: unsupported operand type(s) for *: 'int' and 'NoneType'

The above exception was the direct cause of the following exception:

SystemError                               Traceback (most recent call last)
23 frames
SystemError: <built-in function len> returned a result with an error set

The above exception was the direct cause of the following exception:

SystemError                               Traceback (most recent call last)
/tensorflow-2.1.0/python3.6/tensorflow_core/python/eager/imperative_grad.py in imperative_grad(tape, target, sources, output_gradients, sources_raw, unconnected_gradients)
     75       output_gradients,
     76       sources_raw,
---> 77       compat.as_str(unconnected_gradients.value))

SystemError: PyEval_EvalFrameEx returned a result with an error set
```

**Comment by JoshEZiegler** [comment]
To add some confusion, but maybe some debugging assistance: 
I'm also getting this error on v2.1.0-rc2-17-ge5bf8de410 in my personal code. But, I adapted some example code as an attempt to reproduce it and was unable to reproduce the error.

[Here](https://colab.research.google.com/gist/JoshEZiegler/317daa870ba923512887f5db9c9706de/functional.ipynb) is working embedding sharing code.

[Here](https://colab.research.google.com/drive/18qodVaGRJHlV0dXvIVGUQm6J5t35VeX5) is slightly changed code from above that doesn't work. 

I can't see a difference between these two, but perhaps the comparison could be helpful?

**Comment by JoshEZiegler** [comment]
After some more debugging it looks like this code will run if `dataset_size` modulo `batch_size` is zero. Hopefully that's helpful!

**Comment by jvishnuvardhan** [comment]
@tsuzukit Looks like this was resolved in recent `tf-nightly`. Can you please check the [gist here](https://colab.research.google.com/gist/jvishnuvardhan/d399e888688f963a5ce850103e8ef98d/tf_shared_layer.ipynb?hl=ja).

Please verify once and close the issue if this was resolved for you. Thanks!

**Comment by eduard-s** [comment]
Hi, I've got this error with this nightly build
`  File "/anaconda3/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py", line 108, in _method_wrapper
    return method(self, *args, **kwargs)
  File "/anaconda3/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py", line 1094, in fit
    epoch_logs = copy.copy(logs)
UnboundLocalError: local variable 'logs' referenced before assignment`

**Comment by tsuzukit** [comment]
Hi @jvishnuvardhan 

Thanks for letting me know.

I have tested [same code](https://colab.research.google.com/drive/1Ie1HgUz5jxsK5Nfbq8hU9YGykqWnRFN4?hl=ja#scrollTo=apd3gVJzyail) with `v2.2.0-0-g2b96f3662b 2.2.0` build.

 It worked just fine!
