### ISSUE TITLE
Custom layer weights all have the same name by default

### ISSUE THREAD

**Issue by zaccharieramzi** [tensorflow/tensorflow#36650]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 16.04 
- TensorFlow installed from (source or binary): no
- TensorFlow version (use command below): 2.1
- Python version: 3.6.7
- GPU model and memory: no GPU

**Describe the current behavior**
I am writing a custom layer and stumbled upon the following error: https://github.com/tensorflow/tensorflow/issues/27688. The comment [here](https://github.com/tensorflow/tensorflow/issues/27688#issuecomment-582829374) made me realize that this was probably due to the custom layer weights I was using and realized that in my custom layer the weights all have by default the same name.
But it's not only my custom layer, if I use the code example from the [documentation](https://www.tensorflow.org/guide/keras/custom_layers_and_models#best_practice_deferring_weight_creation_until_the_shape_of_the_inputs_is_known), I also notice that the weights all have the same name (this is why I answered no to the question of whether I had written custom code, because it fails also in the code provided).

**Describe the expected behavior**

To me it's more of a bug than a documentation issue because we expect the weights to have different names by default (increasing ids I mean). However, naming the weights indeed solves the problem.

**Code to reproduce the issue**

```python
import tensorflow as tf

class Linear(tf.keras.layers.Layer):

  def __init__(self, units=32):
    super(Linear, self).__init__()
    self.units = units

  def build(self, input_shape):
    self.w = self.add_weight(shape=(input_shape[-1], self.units),
                             initializer='random_normal',
                             trainable=True)
    self.b = self.add_weight(shape=(self.units,),
                             initializer='random_normal',
                             trainable=True)

  def call(self, inputs):
    return tf.matmul(inputs, self.w) + self.b

l = Linear(32)
l.build((128,))
print([w.name for w in l.weights])
```

**Other info / logs**
The code above gives:

```
['Variable:0', 'Variable:0']
```

This causes a problem when saving the model for example with the  `ModelCheckpoint` callback.

**Comment by gadagashwini** [comment]
Could able to replicate the reported issue with Tf2.1.
Please find the gist [here](https://colab.sandbox.google.com/gist/gadagashwini/a7bd20a199660b361c9eef47430f7e2a/untitled387.ipynb). Thanks!

**Comment by k-w-w** [comment]
Thanks for reporting this! This is one of the effects of moving into TF 2.X -- variable names are no longer uniqueified. This should be fixed in one of two places: either when the variables are created, or when the variables are saved out to HDF5. 

(This should only effect the HDF5 saving format. The `tf` format should still work)

**Comment by ymodak** [comment]
Passing the `name` argument in the `add_weight` should help override this behavior.

**Comment by richardwth** [comment]
> Thanks for reporting this! This is one of the effects of moving into TF 2.X -- variable names are no longer uniqueified. This should be fixed in one of two places in Keras: either generate unique names when the variables are created, or when the variables are saved out to HDF5.
> 
> (This should only effect the HDF5 saving format. The `tf` format should still work)

May I ask the rationale behind allowing repeated names for variables in TF 2.X?

**Comment by sachinprasadhs** [comment]
Was able to reproduce your issue in Tf Nightly 2.6.0-dev20210524 , please find the gist [here](https://colab.research.google.com/gist/sachinprasadhs/d42ea3780c5a3889f919092c3d4d404f/35650.ipynb).Thanks!

**Comment by sachinprasadhs** [comment]
You can solve it using `tf.name_scope` in your build for each weight initialization like mentioned below.

```
import tensorflow as tf

class Linear(tf.keras.layers.Layer):

  def __init__(self, units=32):
    super(Linear, self).__init__()
    self.units = units

  def build(self, input_shape):
    with tf.name_scope("first"):
      self.w = self.add_weight(shape=(input_shape[-1], self.units),
                             initializer='random_normal',
                             trainable=True)
    with tf.name_scope("second"):
      self.b = self.add_weight(shape=(self.units,),
                             initializer='random_normal',
                             trainable=True)

  def call(self, inputs):
    return tf.matmul(inputs, self.w) + self.b

l = Linear(32)
l.build((128,))
print([w.name for w in l.weights])
```

Output:
`['first/Variable:0', 'second/Variable:0']`

**Comment by zaccharieramzi** [comment]
@sachinprasadhs yes indeed, you can also solve it by setting the name in `add_weight`. But I just think that the default behaviour should be to increase the index in `'Variable:0'`, i.e. by default not authorize same name.

**Comment by sanatmpa1** [comment]
Issue still persists in `2.7.0-dev20210923`. Please take a look at the [gist here](https://colab.research.google.com/gist/sanatmpa1/f04bc96b4e7970ac200989132aeeb6d1/35650.ipynb). Thanks!

**Comment by tensorflowbutler** [comment]
Hi There,

 This is a stale issue. As you are using an older version of tensorflow, we are checking to see if you still need help on this issue. Please test the issue with the latest TensorFlow (TF2.7 and tf-nightly). If the issue still persists with the newer versions of TF, please feel free to open it in [keras-team/keras](https://github.com/keras-team/keras/issues) repository by providing details about the issue and a standalone code to reproduce the issue. Thanks! 

 Please note that Keras development has moved to a separate Keras-team/keras repository to focus entirely on only Keras. Thanks!
