### ISSUE TITLE
cannot generate visual studio solution file on Windows 7

### ISSUE THREAD

**Issue by chunfu-yang** [tensorflow/tensorflow#3665]
### Environment info
Operating System:
Windows 7

### What have you tried?
1.on Windows 7 follow https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/cmake/README.md
when try to generate visual  studio sln file, error occurred.

### Logs or other output that would be helpful
CMakeError.log

Determining if the include file pthread.h exists failed with the following output:
Change Dir: C:/tensorflow/tensorflow/contrib/cmake/build/solution/CMakeFiles/CMakeTmp

Run Build Command:"C:/Program Files (x86)/MSBuild/12.0/bin/MSBuild.exe" "cmTC_184bb.vcxproj" "/p:Configuration=Debug" "/p:VisualStudioVersion=12.0"
Microsoft (R) Build Engine version 12.0.40629.0

[Microsoft .NET Framework, version 4.0.30319.42000]

Copyright (C) Microsoft Corporation. All rights reserved.

Build started 8/5/2016 8:36:31 PM.

Project "C:\tensorflow\tensorflow\contrib\cmake\build\solution\CMakeFiles\CMakeTmp\cmTC_184bb.vcxproj" on node 1 (default targets).

PrepareForBuild:

  Creating directory "cmTC_184bb.dir\Debug\".

  Creating directory "C:\tensorflow\tensorflow\contrib\cmake\build\solution\CMakeFiles\CMakeTmp\Debug\".

  Creating directory "cmTC_184bb.dir\Debug\cmTC_184bb.tlog\".

InitializeBuildStatus:

  Creating "cmTC_184bb.dir\Debug\cmTC_184bb.tlog\unsuccessfulbuild" because "AlwaysCreate" was specified.

ClCompile:

  C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\bin\x86_amd64\CL.exe /c /Zi /W3 /WX- /Od /Ob0 /D WIN32 /D _WINDOWS /D _DEBUG /D "CMAKE_INTDIR=\"Debug\"" /D _MBCS /Gm- /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Fo"cmTC_184bb.dir\Debug\\" /Fd"cmTC_184bb.dir\Debug\vc120.pdb" /Gd /TC /errorReport:queue C:\tensorflow\tensorflow\contrib\cmake\build\solution\CMakeFiles\CMakeTmp\CheckIncludeFile.c

  Microsoft (R) C/C++ Optimizing Compiler Version 18.00.40629 for x64

  Copyright (C) Microsoft Corporation.  All rights reserved.

  

  cl /c /Zi /W3 /WX- /Od /Ob0 /D WIN32 /D _WINDOWS /D _DEBUG /D "CMAKE_INTDIR=\"Debug\"" /D _MBCS /Gm- /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Fo"cmTC_184bb.dir\Debug\\" /Fd"cmTC_184bb.dir\Debug\vc120.pdb" /Gd /TC /errorReport:queue C:\tensorflow\tensorflow\contrib\cmake\build\solution\CMakeFiles\CMakeTmp\CheckIncludeFile.c

  

  CheckIncludeFile.c

C:\tensorflow\tensorflow\contrib\cmake\build\solution\CMakeFiles\CMakeTmp\CheckIncludeFile.c(1): fatal error C1083: Cannot open include file: 'pthread.h': No such file or directory [C:\tensorflow\tensorflow\contrib\cmake\build\solution\CMakeFiles\CMakeTmp\cmTC_184bb.vcxproj]

Done Building Project "C:\tensorflow\tensorflow\contrib\cmake\build\solution\CMakeFiles\CMakeTmp\cmTC_184bb.vcxproj" (default targets) -- FAILED.

Build FAILED.

"C:\tensorflow\tensorflow\contrib\cmake\build\solution\CMakeFiles\CMakeTmp\cmTC_184bb.vcxproj" (default target) (1) ->

(ClCompile target) -> 

  C:\tensorflow\tensorflow\contrib\cmake\build\solution\CMakeFiles\CMakeTmp\CheckIncludeFile.c(1): fatal error C1083: Cannot open include file: 'pthread.h': No such file or directory [C:\tensorflow\tensorflow\contrib\cmake\build\solution\CMakeFiles\CMakeTmp\cmTC_184bb.vcxproj]

    0 Warning(s)

    1 Error(s)

Time Elapsed 00:00:00.36

**Comment by mrry** [comment]
The CMake build in `tensorflow/contrib/cmake/...` doesn't currently support Windows. We are working on adding this support (see issue #17).

For running on Windows at present, the [best options](http://stackoverflow.com/q/33616094) are using Docker or installing the Linux version on the Windows 10 Subsystem for Linux.

**Comment by thesby** [comment]
Is there any pre-build win10 tensorflow?
