### ISSUE TITLE
Profiler doesn't work correctly in tensorflow 2.1

### ISSUE THREAD

**Issue by ksabr** [tensorflow/tensorflow#36656]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): centos-release-7-6.1810.2.el7.centos.x86_64
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below): 2.1.0
- Python version: 3.7.4
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory: None

**Describe the current behavior**

The code below, taken from https://www.tensorflow.org/tensorboard/graphs, and used to profile a function call, seems to behave differently in tf 2.0 and tf 2.1. In 2.0, the memory and CPU usage can be inspected with `tensorboard`; in 2.1, they cannot as the radio buttons are grayed out. I am filing this as a tensorflow issue rather a tensorboard one since it seems to be independent of the tensorboard version. I also suspect it's due to the `tensorflow` pip package now including GPU support by default (the problem appears on a machine without a GPU).

```
# The function to be traced.
@tf.function
def my_func(x, y):
  # A simple hand-rolled layer.
  return tf.nn.relu(tf.matmul(x, y))

# Set up logging.
stamp = datetime.now().strftime("%Y%m%d-%H%M%S")
logdir = 'logs/func/%s' % stamp
writer = tf.summary.create_file_writer(logdir)

# Sample data for your function.
x = tf.random.uniform((3, 3))
y = tf.random.uniform((3, 3))

# Bracket the function call with
# tf.summary.trace_on() and tf.summary.trace_export().
tf.summary.trace_on(graph=True, profiler=True)
# Call only one tf.function when tracing.
z = my_func(x, y)
with writer.as_default():
  tf.summary.trace_export(
      name="my_func_trace",
      step=0,
      profiler_outdir=logdir)
```

**Describe the expected behavior**

It should be the behaviour found in tf 2.0.

**Other info / logs**

Screenshots of the two tensorboard displays are shown below. Of note, running the code with tf 2.1 shows the errors below, which do not appear with tf 2.0. I do not have a GPU on my machine, but would still expect the profiler to work.

```
(...)
2020-02-11 10:26:17.256467: I tensorflow/core/profiler/lib/profiler_session.cc:225] Profiler session started.
2020-02-11 10:26:17.256643: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcupti.so.10.1'; dlerror: libcupti.so.10.1: cannot open shared object file: No such file or directory
2020-02-11 10:26:17.256681: E tensorflow/core/profiler/internal/gpu/cupti_tracer.cc:1307] function cupti_interface_->Subscribe( &subscriber_, (CUpti_CallbackFunc)ApiCallback, this)failed with error CUPTI could not be loaded or symbol could not be found.
2020-02-11 10:26:17.256701: E tensorflow/core/profiler/internal/gpu/cupti_tracer.cc:1346] function cupti_interface_->ActivityRegisterCallbacks( AllocCuptiActivityBuffer, FreeCuptiActivityBuffer)failed with error CUPTI could not be loaded or symbol could not be found.
2020-02-11 10:26:17.393265: E tensorflow/core/profiler/internal/gpu/cupti_tracer.cc:1329] function cupti_interface_->EnableCallback( 0 , subscriber_, CUPTI_CB_DOMAIN_DRIVER_API, cbid)failed with error CUPTI could not be loaded or symbol could not be found.
2020-02-11 10:26:17.393327: I tensorflow/core/profiler/internal/gpu/device_tracer.cc:88]  GpuTracer has collected 0 callback api events and 0 activity events.
```
![tf20profile](https://user-images.githubusercontent.com/45923989/74228945-58c22280-4cb9-11ea-935b-c24d4945f1e4.png)
![tf21](https://user-images.githubusercontent.com/45923989/74228948-595ab900-4cb9-11ea-9609-3c04b6fbfb82.png)

**Comment by amahendrakar** [comment]
@ksabr,
I was able to run the code without any issues. Please find the Gist [here](https://colab.research.google.com/gist/amahendrakar/383565fa64dbb1602d3dccd2b00ce550/36656.ipynb). Thanks!

**Comment by foxik** [comment]
After some investigation, this feels more like a tensorboard graph plugin problem. Notably even with the above GPU errors (about CUPTI etc), the CPU profile is generated (it seems very similar to what `tensorflow-cpu` produces without any error) and it can be even viewed in the Profile tab (but not in Graph tab).

So my guess is maybe the TF 2.1 profile uses some new or different features which the Graph tab does not unserstand. And yes, profile generated by TF 2.0 is available both in Profile and Graph tab.

**Comment by amahendrakar** [comment]
@ksabr,
Any updates regarding this issue? Thanks!

**Comment by amahendrakar** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Comment by alexrobomind** [comment]
After encountering the same problem today, I dug around a bit in the internals. Tensorboard has an endpoint that decodes the run metadata section of the protocol buffer containing the event logs. When running this on the logs of the above notebook, once with 2.1.0 and 2.0.0, I get different outputs:

[run_metadata_v200.txt](https://github.com/tensorflow/tensorflow/files/4270483/run_metadata_v200.txt)
[run_metadata_v210.txt](https://github.com/tensorflow/tensorflow/files/4270484/run_metadata_v210.txt)

It appears that the step_stats field in the run_metadata log is not filled out in 2.1, but is in 2.0.

https://github.com/tensorflow/tensorboard/blob/799c5cf6ae1f5f8d78a09382689dcb9d0ec5f561/tensorboard/compat/proto/config.proto#L637-L640

**Comment by alexrobomind** [comment]
After digging deeper into the C++ code, it appears that between 2.0.0 and 2.1.0 the recording of this information was removed [in this commit](https://github.com/tensorflow/tensorflow/commit/0c9c859a7332c4d700ca131dd77944751d2feedc), so I don't think there is a "quick fix" for this.
