### ISSUE TITLE
Hello World example for STM32F746 make error

### ISSUE THREAD

**Issue by Nithraniel** [tensorflow/tensorflow#36657]
@tensorflow/micro

**System information**
- Host OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10 x64
- TensorFlow installed from (source or binary): pip
- Tensorflow version (commit SHA if source): 2.1.0
- Target platform (e.g. Arm Mbed OS, Arduino Nano 33 etc.): STM32F7

**Describe the problem**
I started following the guide here : https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/micro/examples/hello_world#deploy-to-STM32F746
which required me to download TensorFlow's sources (I installed it previously using pip), and my goal is to deploy it to STM32F746. Except that the first step : 
`make -f tensorflow/lite/micro/tools/make/Makefile TARGET=mbed TAGS="CMSIS disco_f746ng" generate_hello_world_mbed_project`
doesn't work and throws me an error saying that it tried to download gemmlowp for some reason and that tensorflow is not recognized as an internal command... I get that I'm not supposed to run tensorflow outside of python but I'm just running **make** here... Shouldn't have any link whatsoever.

**Please provide the exact sequence of commands/steps when you ran into the problem**

Used the first command from the "Deploy to STM32F746" guide `make -f tensorflow/lite/micro/tools/make/Makefile TARGET=mbed TAGS="CMSIS disco_f746ng" generate_hello_world_mbed_project`

Encountered first an error with unam -m tied to my OS or architecture, had to manually delete the makefile code regarding that and write it in stone; then I ran it again and got this :

```
make -f tensorflow/lite/micro/tools/make/Makefile TARGET=mbed TAGS="CMSIS disco_f746ng" generate_hello_world_mbed_project
tensorflow/lite/micro/tools/make/download_and_extract.sh "https://github.com/google/gemmlowp/archive/719139ce755a0f31cbf1c37f7f98adcc7fc9f425.zip" "7e8191b24853d75de2af87622ad293ba" tensorflow/lite/micro/tools/make/downloads/gemmlowp
'tensorflow' is not recognized as an internal or external command operable program or batch file
make: *** [tensorflow/lite/micro/tools/make/downloads/gemmlowp] Error 1
```

**Comment by amahendrakar** [comment]
@Nithraniel,
Is this still an issue?

Could you please update TensorFlow to the latest stable version v2.4.1 and check if you are facing the same error. Thanks!
