### ISSUE TITLE
TensorFlow 2.1 import 'DLL load failed error'

### ISSUE THREAD

**Issue by bduan007** [tensorflow/tensorflow#36665]
When I tried to import TensorFlow 2,1 in Anaconda environment after seeming successful installation using Aanacond Prompt, I got a 'DLL load failed error'. I tried several times from creating the virtual environment to installation tensorflow 2.1 again without success. The installation process went through fine without any error message. 

Strangely, the tensorflow 2.0 works fine but not tensorflow 2.1.  I am currently can run tensorflow 2.0 but would love to have 2.1 if I can find a fix for the 2.1 error.

Thanks for any help!

Bin
--------------------------------------------------------------------------------

name: Build/Installation Issue about: Use this template for build/installation
issues labels: 'type:build/install'

---

<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version:
- Python version:
- Installed using virtualenv? pip? conda?:
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Describe the problem**

**Provide the exact sequence of commands / steps that you executed before running into the problem**

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by mihaimaruseac** [comment]
You didn't fill the issue template at all.

Most likely you are on windows, in which case just searching for similar issues would have pointed you to other duplicated issues.

Closing as duplicate.

#36167 (comment)

#36167 #36151 #36138 #36054 #36045 #36020 #36003 #35988 #35903 #35880 #35865 #35805 #35789 #35773 #35772 #35767 #35766 #35749 #35721 #35618 #35204
