### ISSUE TITLE
Issue with tf.estimator.export.ServingInputReceiver()

### ISSUE THREAD

**Issue by psyyip** [tensorflow/tensorflow#36662]
**System information**
- I run my project on a Jupyter Notebook on GCP
- TensorFlow version: 1.15
- Python version: 3.5.3

**Describe the current behavior**
I followed every instruction to build a serving_input_receiver_fn(). Valliappa Lakshmanan provides his solution to me but it still does not work. I believe it is not the problem of the codes but some unknown issue.

**Describe the expected behavior**
I do not expect any error in creating and exporting this simple serving function. But when I run it, there are error messages. Despite the errors, I can still use the exported model for prediction.

**Code to reproduce the issue**
def serving_input_receiver_fn():
    inputs = {
        'job' : tf.compat.v1.placeholder(dtype = tf.string, shape = [None]),
        'marital' : tf.compat.v1.placeholder(dtype = tf.string, shape = [None]),
        ......
    }
    return tf.estimator.export.ServingInputReceiver(inputs, inputs)

**Other info / logs**
INFO:tensorflow:'serving_default' : Classification input must be a single string Tensor; got {'job': <tf.Tensor 'Placeholder:0' shape=(?,) dtype=string>, 'marital': <tf.Tensor 'Placeholder_1:0' shape=(?,) dtype=string>, ...
WARNING:tensorflow:Export includes no default signature!

**Comment by ravikyram** [comment]
@psyyip 

This issue is more suitable for TensorFlow Serving repo. Please post it on Serving repo from [here.](https://github.com/tensorflow/serving/issues) Thanks!

**Comment by psyyip** [comment]
moved to TensorFlow Serving repo
