### ISSUE TITLE
Pip package for tensorflow 2.1 for Raspberry Pi (python 3.7)

### ISSUE THREAD

**Issue by feranick** [tensorflow/tensorflow#36667]
Current versions of Raspbian use Python 3.7. Yet, the most updated pip packages (TF 2.1) provided by Google for the Raspberry pi are limited to python 3.5:

https://www.tensorflow.org/install/pip

Pypi provides much older versions of TF (1.14) for python 3.7.  

Please update the version provided by either google or Pypi

**Comment by DocGarbanzo** [comment]
As 2.2.0 is available, could you please also provide that for python 3.7? That would be great! Python 3.5 seems a bit outdated now.

**Comment by Saduf2019** [comment]
@feranick 
As we have 3.8/3.9 latest version, could you please verify if this is still an issue.Thanks!

**Comment by KopfKrieg** [comment]
Still an issue here. Stuck with Python 3.7 (Raspbian 10), need TF 2.x. Python 3.8/3.9 is unfortunately not an option.

**Comment by bhack** [comment]
You can build with Python 3.7 https://github.com/tensorflow/build/tree/master/raspberry_pi_builds#python-37

About pre-built official wheels is a sort of dup https://github.com/tensorflow/tensorflow/issues/29704#issuecomment-780021283 /cc @mihaimaruseac

**Comment by KopfKrieg** [comment]
> You can build with Python 3.7 https://github.com/tensorflow/build/tree/master/raspberry_pi_builds#python-37

Recently tried that, unfortunately the build-script uses the wrong NumPy version (NumPy 20.x for building, 19.x for running, which doesn't really work since it's considered as incompatible). Having official Tensorflow packages available for the RPi would entirely solve that problem for users.

**Comment by bhack** [comment]
If want to edit the title and use this ticket to track @KopfKrieg issues building with python 2.7 ok.

If you just want updated pre-packaged wheels palese upvote and comment https://github.com/tensorflow/tensorflow/issues/29704

**Comment by bhack** [comment]
P.s. as officially now is only support TF lite on Raspberry the official build guide is at https://www.tensorflow.org/lite/guide/build_arm
