### ISSUE TITLE
Add a raspberry pi docker image

### ISSUE THREAD

**Issue by fgervais** [tensorflow/tensorflow#36672]
**System information**
- TensorFlow version (you are using): 2.1.0
- Are you willing to contribute it (Yes/No): Yes

**Describe the feature and the current behavior/state.**

There is already a tensoflow docker image for amd64. I'd like to see if there is interest other than me to have the same for armv7.

I recently made one for tensorflow 2.1.0 here:

https://github.com/fgervais/docker-tensorflow/blob/master/Dockerfile

I think it would be nice to have an image like this published on the official docker hub repository.

Note that this image does not need to be built on an actual raspberry pi. I build mine on my x86_64 system using:

```
docker buildx build --platform linux/arm/v7 -t tensorflow:2.1.0-cp35 --load .
```

I'm guessing whatever CI system that builds the amd64 image could also build the armv7 image.

**Who will benefit with this feature?**

On the raspberry pi, the docker image is quite useful since a lot of pip wheels do not come in binary form and the cost of building, let say scipy, is quite high. Having the docker image ensures a plug-and-play experience.

What do you think? Would this integrate well in tensorflow?

**Comment by fgervais** [comment]
Just in case someone would want to use my image right now, run the following on the raspberry pi (tested only on the raspberry pi 4):

```
docker run --rm francoisgervais/tensorflow:2.1.0-cp35 bash

python3
import tensorflow as tf
print(tf.reduce_sum(tf.random.normal([1000, 1000])))
```

**Comment by HamzaRahmani** [comment]
Inside the dockerfile you use this in the first build stage.
`FROM debian@sha256:872b72a2b8487e4b91ae27855c7de1671635d3dc2cc0b89651103e55c74ed34a AS base`
After finding said image on [dockerhub](https://hub.docker.com/layers/arm32v7/debian/stretch/images/sha256-872b72a2b8487e4b91ae27855c7de1671635d3dc2cc0b89651103e55c74ed34a), only two lines are executed.
The first involved adding this file. What is this?
`ADD file:b7fc54d004d962f2cfb469a1aaa9e689e46dfa2554e0cf44c33981d688adc31b in / `

**Comment by fgervais** [comment]
@HamzaRahmani I base on the official debian:stretch docker image for arm32. The file add you refer to is added inside the official debian image. I don't have any info on how they generate their images.

**Comment by settle** [comment]
In case anyone is interested, I managed to build a devel-cpu docker images on my raspberry pi 4, see PR #39695 .  It's a good start for trying to natively build tensorflow on device.

**Comment by rmothukuru** [comment]
@fgervais,
Sorry for the delayed response. Can you please let us know if [this PR](https://github.com/tensorflow/tensorflow/pull/39695) has resolved your issue? Thanks!
