### ISSUE TITLE
tflite model visualize

### ISSUE THREAD

**Issue by lizhen2017** [tensorflow/tensorflow#36684]
python visualize.py
Traceback (most recent call last):
 File "visualize.py", line 30, in <module>
 from tensorflow.lite.python import schema_py_generated as schema_fb
ImportError: cannot import name schema_py_generated

Thanks for your help!

**Comment by ravikyram** [comment]
@lizhen2017 
Please, provide the exact sequence of commands / code that you executed before running into the problem. Thanks!

**Comment by terryheo** [comment]
Please use https://www.tensorflow.org/lite/guide/faq#how_do_i_inspect_a_tflite_file

**Comment by akanxit** [comment]
> Please use https://www.tensorflow.org/lite/guide/faq#how_do_i_inspect_a_tflite_file
As mentioned I tried:
bazel run //tensorflow/lite/tools:visualize model.tflite visualized_model.html
but it gave me an error: Linking of rule '@flatbuffers//:flatc' failed (Exit 1). PFA: screenshot
![tf_lite_visualization_issue](https://user-images.githubusercontent.com/28675926/75039059-da962500-54dd-11ea-80e4-694eb21d76ba.png)

**Comment by jimmy9389** [comment]
same problem, any process is there?
I checked the source codes of tensorflow but I cannot find schema_py_generated file under tensorfow.lite.python folder

**Comment by terryheo** [comment]
Did you follow https://www.tensorflow.org/install/source before using the visualizer?

**Comment by sujaybabruwad** [comment]
I get the error message:
AttributeError: module 'tensorflow.lite.python.schema_py_generated' has no attribute 'Model'
I have installed from source using docker.
Please help @terryheo

**Comment by terryheo** [comment]
@sujaybabruwad plz share commands you used.

**Comment by CRosero** [comment]
I'm also getting the same error 
`AttributeError: module 'tensorflow.lite.python.schema_py_generated' has no attribute 'Model'`
when attempting to run visualize.py on a .tflite model.

**Comment by terryheo** [comment]
This is the same issue with https://github.com/tensorflow/tensorflow/issues/41846 which is still under investigating.
