### ISSUE TITLE
Function String Keras Attention Layer contains error/typo

### ISSUE THREAD

**Issue by tmensink** [tensorflow/tensorflow#36695]
It is a documentation issue, but embedded in the code. This seems most appropriate issue template.

## URL(s) with the issue:
https://github.com/tensorflow/tensorflow/blob/v2.1.0/tensorflow/python/keras/layers/dense_attention.py#L187-L313

## Description of issue (what needs changing):
There is an error in the provided example (L236 - 276):

Here is a code example for using `Attention` in a CNN+Attention network:
  ```python
  value_input = tf.keras.Input(shape=(None,), dtype='int32')
  value_embeddings = token_embedding(query_input)
  ```

This last one should be ```value_embeddings = token_embedding(value_input)```

**Comment by joshz123** [comment]
This issue looks like it is resolved

**Comment by jvishnuvardhan** [comment]
@joshz123 Thanks. Yes, it was updated in the [`master`](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/keras/layers/dense_attention.py). 

As it was resolved, I am closing this issue. Thanks!
