### ISSUE TITLE
Update Docker instructions

### ISSUE THREAD

**Issue by flx42** [tensorflow/tensorflow#3669]
Docker is supported as a way of using TensorFlow:
https://www.tensorflow.org/versions/r0.10/get_started/os_setup.html#docker-installation

> We provide 4 Docker images:
> 
> ```
> gcr.io/tensorflow/tensorflow: TensorFlow CPU binary image.
> gcr.io/tensorflow/tensorflow:latest-devel: CPU Binary image plus source code.
> gcr.io/tensorflow/tensorflow:latest-gpu: TensorFlow GPU binary image.
> gcr.io/tensorflow/tensorflow:latest-devel-gpu: GPU Binary image plus source code.
> ```

However, all those Docker images are 0.8, more than 3000 commits behind. An eon for TF ;)

```
$ nvidia-docker run -it --rm gcr.io/tensorflow/tensorflow:latest-devel-gpu python -c 'import tensorflow as tf; print tf.__version__'
[...]
0.8.0
```

Just below, you also mention the following:

> We also have tags with latest replaced by a released version (e.g., 0.10.0rc0-gpu).

However, I couldn't make it work for 0.10.0rc0 or 0.9.0:

```
$ docker run -it --rm gcr.io/tensorflow/tensorflow:0.10.0rc0-gpu
Unable to find image 'gcr.io/tensorflow/tensorflow:0.10.0rc0-gpu' locally
Pulling repository gcr.io/tensorflow/tensorflow
docker: Tag 0.10.0rc0-gpu not found in repository gcr.io/tensorflow/tensorflow.

$ docker run -it --rm gcr.io/tensorflow/tensorflow:0.9.0-gpu
Unable to find image 'gcr.io/tensorflow/tensorflow:0.9.0-gpu' locally
Pulling repository gcr.io/tensorflow/tensorflow
docker: Tag 0.9.0-gpu not found in repository gcr.io/tensorflow/tensorflow.

$ docker run -it --rm gcr.io/tensorflow/tensorflow:0.8.0-gpu
[I 17:56:59.525 NotebookApp] Writing notebook server cookie secret to /root/.local/share/jupyter/runtime/notebook_cookie_secret
[... OK ...]
```

On GitHub, you have another set of [instructions](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/docker/README.md):

> We currently maintain three Docker container images:
> 
> ```
> gcr.io/tensorflow/tensorflow - TensorFlow with all dependencies - CPU only!
> 
> gcr.io/tensorflow/tensorflow:latest-gpu - TensorFlow with all dependencies and support for Nvidia Cuda
> ```
> 
> Note: We also publish the same containers into Docker Hub.

Same problem, `gcr.io/tensorflow/tensorflow:latest-gpu` is `0.8.0`
But in this case, the link to the DockerHub is useful. `latest` is still `0.8.0`:

```
$ nvidia-docker run -it --rm tensorflow/tensorflow:latest-devel-gpu python -c 'import tensorflow as tf; print tf.__version__'
0.8.0
```

But you do have version tags, and even nightly builds:

```
$ nvidia-docker run -it --rm tensorflow/tensorflow:0.9.0-devel-gpu python -c 'import tensorflow as tf; print tf.__version__'
0.9.0

$ nvidia-docker run -it --rm tensorflow/tensorflow:0.10.0rc0-devel-gpu python -c 'import tensorflow as tf; print tf.__version__'
0.10.0rc0

$ nvidia-docker run -it --rm tensorflow/tensorflow:nightly-devel-gpu python -c 'import tensorflow as tf; print tf.__version__'
0.10.0rc0
```

Can we fix `gcr.io`? Or the instructions?

Related:
https://github.com/tensorflow/tensorflow/issues/3482#issuecomment-235314786

cc @jendap @girving @thatguymike

**Comment by flx42** [comment]
Update: looks like `gcr.io` is fixed:
```
$ nvidia-docker run -it --rm gcr.io/tensorflow/tensorflow:latest-devel-gpu python -c 'import tensorflow as tf; print tf.__version__'
[...]
0.11.0rc0
```

And version tags are also available now on gcr.

**However**,  tag `latest` on DockerHub is still `0.8.0`.

**Comment by caisq** [comment]
The latest* tags should be up-to-date now. This should be the case for both images from Docker Hub (tensorflow/tensorflow) and gcr.io (gcr.io/tensorflow/tensorflow). 

Please re-open this issue if there are remaining issues.
