### ISSUE TITLE
UpSampling2D doesn't support bfloat16 in TF 2.1

### ISSUE THREAD

**Issue by LambertMark** [tensorflow/tensorflow#36696]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.1
- Python version: 3.7.6
- CUDA/cuDNN version: CUDA 10.1, cuDNN 7.6.5
- GPU model and memory: NVIDIA Titan V, 12 GB

**Describe the current behavior**
TypeError: Value passed to parameter 'images' has DataType bfloat16 not in list of allowed values: int8, uint8, int16, uint16, int32, int64, float16, float32, float64

**Describe the expected behavior**
bfloat16 should work with this layer

**Code to reproduce the issue**
```
import tensorflow as tf

tf.keras.mixed_precision.experimental.set_policy('mixed_bfloat16')

optimizer = tf.optimizers.SGD(learning_rate=0.1, momentum=0.9)

input=tf.keras.layers.Input(shape=(256, 256, 3))

x=tf.keras.layers.Conv2D(32,(3,3))(input)
x=tf.keras.layers.UpSampling2D()(x)

x=tf.keras.layers.Conv2D(32,(3,3))(x)
out=tf.keras.layers.Activation('sigmoid', dtype='float32')(x)

my_model = tf.keras.models.Model(inputs=input, outputs=out)

optimizer = tf.keras.optimizers.RMSprop()
my_model.compile(loss='binary_crossentropy', optimizer=optimizer)
```

**Other info / logs**

> line 10, in
> x=tf.keras.layers.UpSampling2D()(x)
> File "C:\Users\mdlambe1\AppData\Local\Continuum\anaconda3\envs\tf2\lib\site-packages\tensorflow_core\python\keras\engine\base_layer.py", line 773, in call
> outputs = call_fn(cast_inputs, *args, **kwargs)
> File "C:\Users\mdlambe1\AppData\Local\Continuum\anaconda3\envs\tf2\lib\site-packages\tensorflow_core\python\keras\layers\convolutional.py", line 2004, in call
> interpolation=self.interpolation)
> File "C:\Users\mdlambe1\AppData\Local\Continuum\anaconda3\envs\tf2\lib\site-packages\tensorflow_core\python\keras\backend.py", line 2782, in resize_images
> x, new_shape, method=image_ops.ResizeMethod.NEAREST_NEIGHBOR)
> File "C:\Users\mdlambe1\AppData\Local\Continuum\anaconda3\envs\tf2\lib\site-packages\tensorflow_core\python\ops\image_ops_impl.py", line 1357, in resize_images_v2
> skip_resize_if_same=False)
> File "C:\Users\mdlambe1\AppData\Local\Continuum\anaconda3\envs\tf2\lib\site-packages\tensorflow_core\python\ops\image_ops_impl.py", line 1133, in _resize_images_common
> images = resizer_fn(images, size)
> File "C:\Users\mdlambe1\AppData\Local\Continuum\anaconda3\envs\tf2\lib\site-packages\tensorflow_core\python\ops\image_ops_impl.py", line 1337, in resize_fn
> images_t, new_size, half_pixel_centers=True)
> File "C:\Users\mdlambe1\AppData\Local\Continuum\anaconda3\envs\tf2\lib\site-packages\tensorflow_core\python\ops\gen_image_ops.py", line 3419, in resize_nearest_neighbor
> name=name)
> File "C:\Users\mdlambe1\AppData\Local\Continuum\anaconda3\envs\tf2\lib\site-packages\tensorflow_core\python\framework\op_def_library.py", line 576, in _apply_op_helper
> param_name=input_name)
> File "C:\Users\mdlambe1\AppData\Local\Continuum\anaconda3\envs\tf2\lib\site-packages\tensorflow_core\python\framework\op_def_library.py", line 61, in _SatisfiesTypeConstraint
> ", ".join(dtypes.as_dtype(x).name for x in allowed_list)))
> TypeError: Value passed to parameter 'images' has DataType bfloat16 not in list of allowed values: int8, uint8, int16, uint16, int32, int64, float16, float32, float64
>

**Comment by jvishnuvardhan** [comment]
@LambertMark I can reproduce the issue. [Here](https://colab.sandbox.google.com/gist/jvishnuvardhan/2802ef0d49e7ebf66c5418375f8df6c2/tf36696.ipynb) is the colab for our reference. 

`tf.keras.layers.UpSampling2D` uses `tf.keras.backend.resize_images` that may not support `bfloat16`.  Let's find it. Thanks!

**Comment by pkanwar23** [comment]
This is fixed. You can try it with today's nightly build. Let me know if you still encounter any issues.
