### ISSUE TITLE
Gradient for tf.cholesky

### ISSUE THREAD

**Issue by RuiShu** [tensorflow/tensorflow#367]
It would be really nice to have a gradient operation for `tf.cholesky` similar to Theano's [CholeskyGrad](http://deeplearning.net/software/theano/library/tensor/slinalg.html#theano.tensor.slinalg.CholeskyGrad). 

I'll be seeing if I can implement the gradient using `tf.control_flow_ops.While` following the suggestion provided [here](http://stackoverflow.com/questions/33962959/cholesky-factor-differentiation-in-tensorflow), but if someone with C++ experience can implement the gradient directly in C++, that'd be great.

Thanks!

**Comment by vrv** [comment]
control_flow_ops.While is not part of the public API (hence there is no documentation about it) because it is still not ready to use externally yet.

**Comment by girving** [comment]
@yaroslavvb: Were you pondering linear algebra gradients?

**Comment by yaroslavvb** [comment]
Just curious, what is the use-case for differentiable Cholesky?

**Comment by RuiShu** [comment]
I'm interested in constructing a differentiable cost function for a Gaussian process (the log marginal likelihood) and wanted replace the matrix inversion with solving via Cholesky.

**Comment by rmlarsen** [comment]
matrix_inverse was recently changed so it will try to use Cholesky if the matrix is symmetric, in the interest of speed. However for the log determinant, I agree that a Cholesky gradient would be nice to have.

**Comment by cesarsalgado** [comment]
This new paper may be of interest: [Differentiation of the Cholesky decomposition](http://arxiv.org/abs/1602.07527)

**Comment by alexggmatthews** [comment]
Myself and James Hensman have implemented the method from the reference paper by Iain murray in TensorFlow on a fork: 

https://github.com/GPflow/tensorflow/blob/master/tensorflow/core/user_ops/chol_grad.cc

@vrv we're aware it isn't yet up to TensorFlow main repo standards but would you like to discuss getting it into the main repo.

**Comment by alexggmatthews** [comment]
Also we have a fair number of unit tests here:

https://github.com/GPflow/tensorflow/blob/master/tensorflow/python/kernel_tests/cholesky_grad_op_test.py

**Comment by alexggmatthews** [comment]
@rmlarsen Would you like to help?

**Comment by martinwicke** [comment]
The best way would be to make a pull request. That's the best way for us to see and comment on the changes. It's ok to mark the PR as [WIP] (see examples on our PR page).

**Comment by rmlarsen** [comment]
Hi Alex,

Sorry for the delayed response. I'd be happy to review your code and help
getting it integrated into the TensorFlow core.

Rasmus

**Comment by alexggmatthews** [comment]
OK thanks. I'll put in a pull request.

**Comment by rmlarsen** [comment]
FYI: Alex's excellent code in PR 1465 was merged today, so you should be able to use cholesky with gradients now. We still need to add support for batch_cholesky, so I'm leaving the bug open for now.

**Comment by c0g** [comment]
@alexggmatthews said to post here when I had something to show and to tag @rmlarsen and @yaroslavvb - hi guys!

I've been working on making a CUDA version of Alex's code. I now have the following ops implemented in [my fork](https://github.com/c0g/tensorflow/tree/master/tensorflow/core/user_ops):

- get_diag (get_diag*)
- tril (triangle*)
- cholesky (gpu_cholesky*)
- cholesky_grad (gpu_cholgrad*)

There is still a lot left to do, but the algorithms are all there and I believe they numerically match Alex's code. I will be adding python wrappers and tests over the coming days, as well as tidying up source files and trying to get it all to build with Bazel.

Meantime, I have a few questions (possibly to be discusses in a PR?):

### streams
Is it correct to call standard CUDA kernels and operations on the op's stream by launching with `context->eigen_device<Device>().stream()`?

### stream.ThenLaunch()
I think there is a way to launch kernels directly on a tensorflow stream - but there's not much information on TypedKernel or Kernel that I can find. Do I need to worry about this?

### cusolver:
I use cusolver for the cholesky op. This isn't yet wrapped in Stream.h so I'm linking/calling it raw. This adds a dependency on linking cusolver into the framework, and maybe wrapping it as you guys have wrapped cublas.

**Comment by harpone** [comment]
@RuiShu (and others): are you aware that `grad(logdet(A)) = transpose(inv(A))`? Unless it's actually faster to compute the grad of the cholesky decomp (and to the other operations), then IMO it might make sense to use the cholesky decomp in getting the *value* of the logdet and to use the inverse-transpose form for the gradient?

**Comment by harpone** [comment]
tf.cholesky works only for symmetric pos def matrices? Any plans to support non-symmetric matrices?

**Comment by RuiShu** [comment]
@harpone It's been a while since I've checked up on this issue. Generally, it'd be nice to not compute the inverse explicitly. Since I was primarily interested in logdets within the context of gaussian processes, there are ways of getting around it (such as something that ultimately requires something like the cholesky decomp in the backwards pass as well :P)

In any case, I was under the impression that Alex's contribution (as well as his work in GPFlow in general) has effectively solved the issue.

**Comment by alexmonroe87** [comment]
Are there any plans to make the tf.matrix_determinant() GPU op? Or is it possible to implement it using existing GPU ops?

**Comment by EverettYou** [comment]
If the matrix is not positive definite, how to implement logdet(A) and its gradient without calculating det(A) explicit? (Because det(A) itself can overflow easily.)

**Comment by harpone** [comment]
@EverettYou as for the numerical value, you could now use `s, u, v = tf.svd(M)`, where s is an array of the singular values (which are eigenvalues of M since M is square). Then log det(M) = log det(P S P^{-1}) = log det(S) = log(prod_i(s[i])) = sum_i log(s[i]), i.e. just take log of s and sum. Note that since M is not necessarily pos def, you'd actually need log *abs* det so just take the abs of s first. The gradient is the same, since log(-1) is a constant (imaginary number but a constant nevertheless).

I don't know about the status of the gradient... haven't thought about this in a while. You _could_ define the gradient by RegisterGradient as `grad(logdet(M)) = transpose(inv(M))`, but as @RuiShu mentioned, it would be nice to avoid taking the inverse, at least if the matrix is big...

**Comment by EverettYou** [comment]
Thanks for your answer. That is very useful!

Everett You
