### ISSUE TITLE
TFLite can't quantize op transpose_conv

### ISSUE THREAD

**Issue by psunn** [tensorflow/tensorflow#36707]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- TensorFlow installed from (source or binary): binary
- TensorFlow version (or github SHA if from source): 1.15.2, 2.1.0

Quantization doesn't support op: TRANSPOSE_CONV

```python 
import tensorflow as tf
import numpy as np

def gen_calibration_dataset():
    for _ in range(10):
        yield [np.random.rand(1,2,2,2).astype(np.float32)]

def get_keras_model_conv():
    input_0 = tf.keras.layers.Input(shape=[2, 2, 2])
    transpose_conv_1 = tf.keras.layers.Conv2DTranspose(filters=2, kernel_size=[2, 2],
                                                       use_bias=False, padding="same")(input_0)
    model = tf.keras.models.Model(inputs=[input_0], outputs=[transpose_conv_1])
    model.summary()
    return model

def gen_model():
    keras_model = get_keras_model_conv()
    keras_model.save('test_model.h5')
    converter = tf.compat.v1.lite.TFLiteConverter.from_keras_model_file('test_model.h5')
    converter.optimizations = [tf.lite.Optimize.DEFAULT]
    #converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_ACTIVATIONS_INT16_WEIGHTS_INT8]
    converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
    converter.inference_input_type = tf.int8
    converter.inference_output_type = tf.int8
    converter.representative_dataset = gen_calibration_dataset
    tflite_quant_model = converter.convert()
    open('test.tflite', 'wb').write(tflite_quant_model)

print("TF version: {}".format(tf.__version__))
gen_model()
```

error mesg:
> Traceback (most recent call last):
>   File "test_RICH.py", line 30, in <module>
>     gen_model()
>   File "test_RICH.py", line 26, in gen_model
>     tflite_quant_model = converter.convert()
>   File "/envs/tf-nightly/lib/python3.6/site-packages/tensorflow_core/lite/python/lite.py", line 469, in convert
>     self.experimental_new_quantizer)
>   File "/envs/tf-nightly/lib/python3.6/site-packages/tensorflow_core/lite/python/lite.py", line 243, in _calibrate_quantize_model
>     inference_output_type, allow_float, enable_mlir_quantizer)
>   File "/envs/tf-nightly/lib/python3.6/site-packages/tensorflow_core/lite/python/optimize/calibrator.py", line 81, in calibrate_and_quantize
>     enable_mlir_quantizer)
>   File "/envs/tf-nightly/lib/python3.6/site-packages/tensorflow_core/lite/python/optimize/tensorflow_lite_wrap_calibration_wrapper.py", line 115, in QuantizeModel
>     return _tensorflow_lite_wrap_calibration_wrapper.CalibrationWrapper_QuantizeModel(self, *args)
> RuntimeError: Quantization not yet supported for op: TRANSPOSE_CONV

**Comment by daverim** [comment]
This is working for me in nightly -- please try upgrading to tf-nightly==2.2.0.dev20200212 and running your test again.

**Comment by psunn** [comment]
> This is working for me in nightly -- please try upgrading to tf-nightly==2.2.0.dev20200212 and running your test again.

thanks for have a quick look. yes, works on tf-nightly, issue closed.

**Comment by anilsathyan7** [comment]
When i tried the above code (v1 or v2 lite converter) for a keras model, it adds a quantize layer at beginning and dequantize layer at the end(netron viewer). I even tried to do the same with a saved model version of the same keras model; but results are same. Also tried with nightly versions dev20200212 and dev20200216. Anybody else facing this issue and how can it be resolved?

Here is the code:
```
converter = tf.lite.TFLiteConverter.from_keras_model(reshape_model)
#converter.experimental_new_converter=True
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
converter.inference_input_type = tf.uint8
converter.inference_output_type = tf.uint8
converter.optimizations = [tf.lite.Optimize.DEFAULT]
converter.representative_dataset = representative_dataset_gen

tflite_quant_model = converter.convert()
open("/content/quant_model.tflite", "wb").write(tflite_quant_model)
```
It looks like we need to have a uint8 input and output for converting it for acclerators like coral TPU.
[pnet.h5.zip](https://github.com/tensorflow/tensorflow/files/4213498/pnet.h5.zip)

**Comment by mlinxiang** [comment]
i have the same error, as "Cannot set tensor: Got value of type UINT8 but expected type FLOAT32 for input 201, name: input_1 ", and the input type still float32 for mobilenetv2
[{'name': 'input_1', 'index': 201, 'shape': array([  1, 128, 128,   3], dtype=int32), 'shape_signature': array([], dtype=int32), 'dtype': <class 'numpy.float32'>, 'quantization': (0.0, 0), 'quantization_parameters': {'scales': array([], dtype=float32), 'zero_points': array([], dtype=int32), 'quantized_dimension': 0}, 'sparsity_parameters': {}}]

**Comment by anilsathyan7** [comment]
@mlinxiang  At which phase of conversion are you getting this error? Are your model inputs still float? If you view your model using a tool like netron, i suppose you will see both input and outputs as float. It may have added a quantize layer at beginning and a dequantize at the end  even though quantization was successful?

**Comment by mlinxiang** [comment]
just as you say, input output are float32, and follow with *quant is int8 which as expect need to be uint8.  i change input image to float the model run success, and result is right, but this tflite model can't run on my mtk platform which has an apu core which need all uint8 tflite model
![image](https://user-images.githubusercontent.com/6283983/75040457-a6c6f980-54f5-11ea-9732-0d5b43f4ed0f.png)

**Comment by anilsathyan7** [comment]
@mlinxiang I faced simialar problem with my model.  My input  images were actually normalized between -2.0 to +2.0 range (instead of 0.0 to 255.0)  during training. When i tried to convert it to full integer format with quantization, it resulted in a model (with tf2.0 nightly using v1 converter as shown in the code) similar to yours with quantize and dequantize layers at the ends. Accelerators may not support (i believe) these layers explicitly. I used **tf.int8 instead of tf.uint8** during **post-training quantization**(with representative dataset) according to the aforementioned code. Finally it got rid of these layers and new inputs were of type **int8**. I successfully converted to **coral edge tpu**  format and was able to run it without any issues so far. After adding appropriate normalization in code  it seems to give **correct results**.

**Comment by mlinxiang** [comment]
when i change code to follow everything is ok
**converter = tf.compat.v1.lite.TFLiteConverter.from_keras_model_file(keras_model_h5)**
    converter.optimizations = [tf.lite.Optimize.DEFAULT]
    converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
    converter.inference_input_type = tf.uint8
    converter.inference_output_type = tf.uint8
    converter.representative_dataset = rep_data_gen

    tflite_model = converter.convert()
    open(tflite_model_path, "wb").write(tflite_model)
![image](https://user-images.githubusercontent.com/6283983/75043009-52724880-54fa-11ea-903c-37ef74c53dd0.png)

**Comment by anilsathyan7** [comment]
But that's the same code @psunn has given in the issue right? Didn'tt you try that in the first place?Still is it running in the device?

**Comment by mlinxiang** [comment]
his type is as follow 
converter.inference_input_type = **tf.int8**
converter.inference_output_type = **tf.int8**

**Comment by anilsathyan7** [comment]
Interesting ...my case was just reverse. As per the official documentation it was **tf.uint8;** but it resulted in extra dequantize and quantize layers in my case and removed them when i changed it to **tf.int8**i.e there were not explicit quantize or dequantize layers in model when use tf.int8. May be it depends on value ranges of activation's of the original model !!!

By the way is it working as expected ? Does the device run the **dequantize** layer without error?

**Comment by mlinxiang** [comment]
compared the quant model and float model on my 3.3k test images, my model acc<keypoint heatmap predict distance> increase from float:3.1648   to  quant: 5.3375 pixel distance, most result are similar, but some blur or bad quality image result are really bad, float model is more balance. 
maybe quant-aware training is a better choice as my previous exps, but keras not support right now

**Comment by anilsathyan7** [comment]
Yes, post-training quantization seems to degrade the output quality, especially in scenarios where high pixel accuracies or precise boundaries are desired. Even int tf 1.x, quantization aware training support only limited convolutional architectures. But on the flip side it gives 40x speed-up, reduced power, memory etc. !!!
