### ISSUE TITLE
Update CUDA/cuDNN in Dockerfiles

### ISSUE THREAD

**Issue by flx42** [tensorflow/tensorflow#3670]
Currently, the Dockerfiles are using CUDA 7.5 and cuDNN v4:
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/docker/Dockerfile.devel-gpu#L1

Any chance of updating the Dockerfile to cuDNN v5 as a first step? It might be just a single-character fix :) cuDNN v5 is RC but stable AFAIK.

Ideally, it would be also useful for users with Pascal boards to also update to CUDA 8.0 as the next step (we now provide CUDA 8.0 RC on CentOS 7, ubuntu 14.04 and ubuntu 16.04). But I would understand if you prefer to wait until CUDA 8.0 is out of RC.

Related:
https://github.com/NVIDIA/nvidia-docker/pull/131

cc: @cbiffle @jendap @thatguymike

**Comment by flx42** [comment]
cuDNN v5 is now GA, so it should be safe to use.

**Comment by vrv** [comment]
(Indeed, we should switch to v5 ASAP).  Do you know when CUDA 8.0 is planned to exit RC?

**Comment by flx42** [comment]
The current estimate is September 12, but it might change.

**Comment by flx42** [comment]
Solved with 60bb54e3111daf5a57008c97db05a91a93101fd7, closing.
