### ISSUE TITLE
Why do we need to convert Keras model to tf-estimator in TF-2.0

### ISSUE THREAD

**Issue by pingsutw** [tensorflow/tensorflow#36706]
I want to upgrade my custom estimator model from tf1 to tf2, and I follow this link to upgrade

They recommend the use tf.keras.estimator.model_to_estimator

**TensorFlow-2.0 official doc**
> We recommend that you define your model using Keras, then use the tf.keras.estimator.model_to_estimator utility to turn your model into an estimator. The code below shows how to use this utility when creating and training an estimator.

In TF-1.x, in order to scale model to training on multiple workers, we convert Keras to tf-estimator.

But in TF-2.x, Keras already support distributed training well, so my question is

1. Why do we need to convert Keras to estimator in TF-2.0, dose any benefits?
2. Can we use low-level TF API (like tf.function()) to build custom estimator model ?

I can't find any example to build estimator model in TF-2.0 and without Keras.

**Comment by gowthamkpr** [comment]
> 1. Why do we need to convert Keras to estimator in TF-2.0, dose any benefits?

If you use infrastructure or other tooling that relies on Estimators, you can still build a Keras model and use model_to_estimator to convert the Keras model to an Estimator for use with downstream systems.

> 2. Can we use low-level TF API (like tf.function()) to build custom estimator model ?
As you can see [here](https://www.tensorflow.org/api_docs/python/tf/estimator/Estimator#eager_compatibility), Calling methods of Estimator will work while eager execution is enabled. However, the model_fn and input_fn is not executed eagerly, Estimator will switch to graph mode before calling all user-provided functions (incl. hooks), so their code has to be compatible with graph mode execution.
So using tf.function() here doesn't make sense.

Please correct me if you think I  have misinterpreted your question. Thanks!

**Comment by pingsutw** [comment]
@gowthamkpr Thanks for the reply. 
Instead of use Keras, I want to build a custom estimator model that build by low-level TF API.

**Comment by gowthamkpr** [comment]
You can follow the following[ tutorial](https://medium.com/tensorflow/how-to-write-a-custom-estimator-model-for-the-cloud-tpu-7d8bd9068c26) to write your custom estimator model.
If you have more questions please post them in stackoverflow as there is a bigger community to respond. Thanks!
