### ISSUE TITLE
MKL no longer works with tensorflow 1.15

### ISSUE THREAD

**Issue by pavanky** [tensorflow/tensorflow#36717]
------------------------

### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: NO

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Centos 7

- **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device**: N/A
- **TensorFlow installed from (source or binary)**: source
- **TensorFlow version (use command below)**: 1.15.2
- **Python version**: N/A
- **Bazel version (if compiling from source)**: 0.24.1
- **GCC/Compiler version (if compiling from source)**: gcc-6 (devtoolset-6 on centos 7)
- **CUDA/cuDNN version**: N/A
- **GPU model and memory**: N/A
- **Exact command to reproduce**:
```bash
 bazel build -c opt --copt=-msse4.2 --copt=-mavx \
       --copt=-O3 --config=mkl --linkopt -ldl \
       --copt=-march=x86-64 \
       //tensorflow/tools/pip_package:build_pip_package \
       //tensorflow/tools/lib_package:libtensorflow_jni \
       //tensorflow/tools/lib_package:libtensorflow \
       //tensorflow/tools/lib_package:libtensorflow_proto \
```

### Describe the problem
libtensorflow_framework.so build this way does not have any symbols from MKL. When trying to import tensorflow from ~~java~~ scala, it fails with symbol not found for `tensorflow::DisableMKL()`

The number of MKL symbols found in `libtensorflow_framework.so` for 1.15 are also significantly lower than those found in 1.14.

### Source code / logs

Code used to import tensorflow in scala

```scala
import org.tensorflow.Tensorflow
```
Note: We have to ensure `libiomp5.so` and `libmklml_intel.so` are available on library load path. 

The simplest solution we found was to load the libraries manually in order. The code snippet can be seen here:
https://gist.github.com/pavanky/ea6e71e3e7e52c013db844b715723be0
 

Error

```
libtensorflow_jni.so: undefined symbol: _ZN10tensorflow10DisableMKLEv
```

Looking at the number of symbols related to MKL:

```	
 $ nm -D org/tensorflow/native/linux-x86_64/libtensorflow_framework.so.1 | grep -i mkl | wc -l
1
 $ nm -D org/tensorflow/native/linux-x86_64/libtensorflow_jni.so | grep -i mkl | wc -l
9
 $ nm -D org/tensorflow/native/linux-x86_64/libtensorflow_framework.so.1 | grep -i mkl
0000000000e127b0 T _ZN10tensorflow12IsMklEnabledEv
```

For reference, 1.14 had a lot more

```
 $ nm -D org/tensorflow/native/linux-x86_64/libtensorflow_framework.so.1 | grep -i mkl | wc -l
11388
 $ nm -D org/tensorflow/native/linux-x86_64/libtensorflow_jni.so | grep -i mkl | wc -l
8
```

---------
MKL is also not available in the wheel built by the command mentioned above.

```python
>>> import tensorflow as tf
>>> tf.python.pywrap_tensorflow.IsMklEnabled()
False
```

**Comment by pavanky** [comment]
tried to build with this patch, all it did was get rid of the error. The performance regression tests we have in house indicate MKL is not being used (i.e. they are on par with no-mkl).

```
iff --git a/tensorflow/core/util/util.cc b/tensorflow/core/util/util.cc
index 489999d..5f93530 100644
--- a/tensorflow/core/util/util.cc
+++ b/tensorflow/core/util/util.cc
@@ -120,7 +120,7 @@ string SliceDebugString(const TensorShape& shape, const int64 flat) {
   return result;
 }
 
-#ifdef INTEL_MKL
+//#ifdef INTEL_MKL
 bool DisableMKL() {
   enum MklStatus { MKL_DEFAULT = 0, MKL_ON = 1, MKL_OFF = 2 };
   static MklStatus status = MKL_DEFAULT;
@@ -135,5 +135,5 @@ bool DisableMKL() {
   }
   return status == MKL_OFF ? true : false;
 }
-#endif  // INTEL_MKL
+//#endif  // INTEL_MKL
 }  // namespace tensorflow
diff --git a/tensorflow/core/util/util.h b/tensorflow/core/util/util.h
index 4aa47aa..c829707 100644
--- a/tensorflow/core/util/util.h
+++ b/tensorflow/core/util/util.h
@@ -57,9 +57,9 @@ string PrintMemory(const char* ptr, size_t n);
 string SliceDebugString(const TensorShape& shape, const int64 flat);
 
 // disable MKL in runtime
-#ifdef INTEL_MKL
+//#ifdef INTEL_MKL
 bool DisableMKL();
-#endif  // INTEL_MKL
+//#endif  // INTEL_MKL
 
 }  // namespace tensorflow
```

**Comment by penpornk** [comment]
@pavanky Could you please update the original post to provide the commands you used to import tensorflow from java as well? Thank you very much!

**Comment by Jianhui-Li** [comment]
@ashraf-bhuiyan @claynerobison

**Comment by pavanky** [comment]
@penpornk I update the original description with more information. We technically use scala and not java, but that shouldnt be too different.

**Comment by pavanky** [comment]
@penpornk Also verified from python (wheel) that MKL is not available.

**Comment by penpornk** [comment]
@pavanky Thank you very much for the additional details! 
I tried this on Ubuntu 16.04, gcc 5.4.0, and python2.7. (TF 1.15.2.) The issue didn't occur to me.
```
$ nm -D  ${TF_ROOT}/bazel-out/k8-opt/bin/tensorflow/libtensorflow_framework.so.1 | grep -i mkl | wc -l
15711
$ nm -D ${TF_ROOT}/bazel-out/k8-opt/bin/tensorflow/java/libtensorflow_jni.so | grep -i mkl | wc -l
9
$ nm -D ${TF_ROOT}/bazel-out/k8-opt/bin/tensorflow/java/libtensorflow_jni.so | grep -i mkl
                 U MKL_Comatcopy
                 U MKL_Domatcopy
                 U MKL_Somatcopy
                 U MKL_Zomatcopy
                 U _ZN10tensorflow10DisableMKLEv
0000000000000658 b _ZN6mkldnn4impl10mxcsr_saveE
0000000000000650 b _ZN6mkldnn4impl19global_scratchpad_t11scratchpad_E
0000000000000640 b _ZN6mkldnn4impl19global_scratchpad_t16reference_count_E
0000000000000648 b _ZN6mkldnn4impl19global_scratchpad_t5size_E
```
The pip wheel:
```
$ python2.7
>>> import tensorflow as tf
>>> tf.python.pywrap_tensorflow.IsMklEnabled()
True
```

I'll try CentOS 7 next.

**Comment by claynerobison** [comment]
@penpornk I'm checking this out now...

**Comment by penpornk** [comment]
@claynerobison Thank you very much!

**Comment by mihaimaruseac** [comment]
One additional question: are there changes in behavior between 1.15.0 and 1.15.2?

**Comment by pavanky** [comment]
@penpornk did you use the same build instructions or did you try something different?

**Comment by penpornk** [comment]
@pavanky Yes, I used the instruction you provided:
```
 bazel build -c opt --copt=-msse4.2 --copt=-mavx \
       --copt=-O3 --config=mkl --linkopt -ldl \
       --copt=-march=x86-64 \
       //tensorflow/tools/pip_package:build_pip_package \
       //tensorflow/tools/lib_package:libtensorflow_jni \
       //tensorflow/tools/lib_package:libtensorflow \
       //tensorflow/tools/lib_package:libtensorflow_proto
```

I tried building it on CentOS but got this JDK header error. (I'm using OpenJDK version 1.8.0_242, the same version I used for Ubuntu.) Any suggestions?
```
ERROR: <bazel_cache_directory>/1cd7327d9a236f0d3fa30a23be6b1071/external/bazel_tools/tools/jdk/BUILD:96:1: Executing genrule @bazel_tools//tools/jdk:gen_include/linux/jni_md.h failed (Exit 1)
cp: cannot stat 'external/local_jdk/include/linux/jni_md.h': No such file or directory
```

**Comment by pavanky** [comment]
@penpornk this is the setup I am using (minus the Twitter specific stuff): https://gist.github.com/pavanky/5a45b29ed3ca56b7e1c747b9c0c88503

I then run `make IMAGE_TYPE=cpu USE_MKL=1`

**Comment by preethivenkatesh** [comment]
I could reproduce the results of @penpornk on Centos 7 along with all other sw installs mentioned in the original thread. Additionally I used openJDK-devel-1.8.0. 
```
nm -D /home/centos/.cache/bazel/_bazel_centos/ee95bf24ea43f832d9db095baebc124d/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/java/libtensorflow_jni.so | grep -i mkl
                 U MKL_Comatcopy
                 U MKL_Domatcopy
                 U MKL_Somatcopy
                 U MKL_Zomatcopy
                 U _ZN10tensorflow10DisableMKLEv
00000000000005c0 b _ZN6mkldnn4impl10mxcsr_saveE
00000000000005b8 b _ZN6mkldnn4impl19global_scratchpad_t11scratchpad_E
00000000000005a8 b _ZN6mkldnn4impl19global_scratchpad_t16reference_count_E
00000000000005b0 b _ZN6mkldnn4impl19global_scratchpad_t5size_E
```

**Comment by jingxu10** [comment]
> One additional question: are there changes in behavior between 1.15.0 and 1.15.2?

@mihaimaruseac  There should be no new features or new functions. All amendments should be all about bug fixes or security issue fixes.

**Comment by pavanky** [comment]
@preethivenkatesh are you using the same bazel version? Can you also check for symbols in `libtensorflow_framework.so`

**Comment by pavanky** [comment]
@penpornk are you using the same version of bazel ? 0.24.1?

**Comment by preethivenkatesh** [comment]
@pavan,
[libtf_symbols.txt](https://github.com/tensorflow/tensorflow/files/4220398/libtf_symbols.txt)

**Comment by mihaimaruseac** [comment]
@jingxu10 Yes, I know that. But I'm asking because the build process changed between the 1.15.0 and 1.15.2 and wanted to make sure this issue is not because of that.

**Comment by claynerobison** [comment]
> @jingxu10 Yes, I know that. But I'm asking because the build process changed between the 1.15.0 and 1.15.2 and wanted to make sure this issue is not because of that.

Are the changes in the build process in the r1.15 branch?

**Comment by mihaimaruseac** [comment]
The build scripts are in the branch now. They weren't before we started the patch process release.

**Comment by TensorFlow-MKL** [comment]
so , does this mean you are able to build it with the latest r11.5?

**Comment by penpornk** [comment]
@pavanky Yes, I used bazel 0.24.1. I haven't had a chance to try your docker file yet, sorry!

Would love to know if you had problems with 1.15.0 too.

**Comment by penpornk** [comment]
@preethivenkatesh Would you mind trying @pavanky's dockerfile as well? Maybe the issue lies there.

**Comment by preethivenkatesh** [comment]
yeah I'll try to work on it today

**Comment by preethivenkatesh** [comment]
we are able to reproduce the issue in the dockerfile. we'll continue to troubleshoot

**Comment by penpornk** [comment]
Thank you for the update!

**Comment by pavanky** [comment]
@preethivenkatesh please let me know if I can do anything to help

**Comment by pavanky** [comment]
@preethivenkatesh any updates?

**Comment by ashahba** [comment]
@pavanky this was assigned to me now.
Stay tuned please and I keep you posted.
I was able to reproduce the issue using your `Dockerfile`.
One thing to keep in mind though both `Python2.7` and `CentOS 7` are considered unsupported configurations starting `TensorFlow v1.15` but I'm not going to make a final call on that just yet 🙂

**Comment by pavanky** [comment]
@ashahba python2 support has been dropped internally, if you can get reproduce with python3 that is OK as well.

**Comment by preethivenkatesh** [comment]
@ashahba Even I thought this issue could be because on 2.7, but I was able to reproduce this issue on py36 when I tired.

**Comment by ashahba** [comment]
Hi @pavanky and @preethivenkatesh I have put some docker and scripts together here to help you with building `TensorFlow with MKL` on `CentOS 7` here: https://github.com/ashahba/centos7-tf

I tried:
```
docker build --build-arg TF_BRANCH=v1.15.2 --build-arg PY_VER=3.6 --build-arg CONFIG_VER=v2 -f Dockerfile . -t centos-tf-3.6-v2
```
and the `bazel` options where reported as follows:
```
Writing build flags: build --cxxopt=-D_GLIBCXX_USE_CXX11_ABI=0 --copt=-O3 --copt=-Wformat --copt=-Wformat-security --copt=-fstack-protector --copt=-fPIC --copt=-fpic --linkopt=-znoexecstack --linkopt=-zrelro --linkopt=-znow --linkopt=-fstack-protector --copt=-mmmx --copt=-msse --copt=-msse2 --copt=-msse3 --copt=-mssse3 --copt=-msse4.1 --copt=-msse4.2 --copt=-mpopcnt --copt=-mavx --copt=-maes --copt=-mpclmul --config=mkl --config=v2
```

and of course the wheels correctly report `MKL` support:
```
python3
Python 3.6.8 (default, Aug  7 2019, 17:28:10) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-39)] on linux
Type "help", "copyright", "credits" or "license" for more information.

>>> import tensorflow_core as tf_core
>>> tf_core.python.pywrap_tensorflow.IsMklEnabled()
True
```
and also:
```
nm -D  /tensorflow_src/bazel-out/k8-opt/bin/tensorflow/libtensorflow_framework.so.1 | grep -i mkl | wc -l
15718
```

I tried this for both `Python 2.7` and `Python 3.6` and on both `v1.15.0` and `v1.15.2` as described in the repo and they all seem to work fine.

Also if you have new bazel flags or targets that need to be built, you can just modify the file `build_tf_whl.sh` around this line:
https://github.com/ashahba/centos7-tf/blob/master/build_tf_whl.sh#L46


Good luck and please let me know if that solves the issue you are seeing.

Thanks.

**Comment by ashahba** [comment]
One think to note, is that most of the work is just reusing scripts that are already in `TensorFlow` repo.

**Comment by penpornk** [comment]
@ashahba Thank you very much!

**Comment by pavanky** [comment]
@ashahab thanks trying!

**Comment by pavanky** [comment]
Thanks the new dockerfile works!
