### ISSUE TITLE
[TPU Colab] [TF2.1] Many issues only on TPU due to data types, batch sizes and memory (gist provided with explanations)

### ISSUE THREAD

**Issue by MichaelKarpe** [tensorflow/tensorflow#36718]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: Yes, see gists with code on Colab [not working on TPU](https://colab.research.google.com/drive/1yk4Emyzxju85gqflEii9FVuMD6VF5vta) and [working on GPU](https://colab.research.google.com/drive/1d4_RPQ2wHg6q4wr-J8VzjSi_DMTLRZDp).
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Google Colab
- **TensorFlow installed from (source or binary)**: `%tensorflow_version 2.x` command
- **TensorFlow version (use command below)**: `2.1.0`

### Describe the problem
All the issues are shown and described in the [gist provided](https://colab.research.google.com/drive/1yk4Emyzxju85gqflEii9FVuMD6VF5vta). Here is the list of the issues:
- Issue 1: Models fitted on TPU does not deal number of samples not divisible by batch size.
- Issue 1bis: With argument validation_split on TPU, issue 1 may occur with number of samples not divisible by batch size.
- Issue 2: List of supported dtypes on TPU is restrictive.
- Issue 2bis: Predict on TPU has the same dtype constraints than fit on TPU.
- Issue 3: Number of samples may cause error for prediction on TPU
- Issue 4: Batch size may cause error for prediction on TPU
- Issue 4bis: Warnings when predicting on TPU
- Issue 5: Trying to fit or predict on TPU a model on a supported dtype after having tried on a not supported dtype may raise an error.
- Issue 6: `UnavailableError: Socket closed` on TPU and related errors

### Source code / logs
[See Gist provided.](https://colab.research.google.com/drive/1yk4Emyzxju85gqflEii9FVuMD6VF5vta)

**Comment by frankchn** [comment]
Thanks for reporting the issues. 

The [batch size](https://cloud.google.com/tpu/docs/troubleshooting#batch-too-small) and [dtype](https://cloud.google.com/tpu/docs/troubleshooting#unsupported_data_type) limitations are known.

Practically speaking, the TPU systems have significant amounts of host memory, so converting INT8 to INT32 data types manually should not make it OOM unless the batch and data sizes are truly enormous.

Assigning the rest of to the current TPU oncall @hongjunChoi.

**Comment by hongjunChoi** [comment]
Hello Michael, 

Thank you for reporting. As for errors regarding sample size not being divisible by batch size, could you try converting numpy arrays to tf.data.Dataset?

Currently, partial batch size for final batch is supported for dataset inputs.

**Comment by MichaelKarpe** [comment]
Hi @hongjunChoi,

Sorry for the late reply, I have very little time these days to work on this. I tried with `tf.data.Dataset`, it looks like it's approximately working...

For example I can find a workaround for the `validation_split` parameter by using `validation_data` instead, however it seems the `model.predict` returns different predictions depending on the batch size (using `.batch()` on `tf.data.Dataset`).

I hadn't time to investigate but I'm quite surprised predictions may be the same for different samples of random generated data (however it also may be explained by the fact that the model is not really able to train...)

Please find a new gist [here](https://colab.research.google.com/drive/1IM3t4BF3iypclJ2fO9VCGg-6TdgORd-R) where I tried `tf.data.Dataset`, I hope it'll help you to investigate.

**Comment by hongjunChoi** [comment]
Hello Michael,

Apologies for the late update. We are currently looking into this issue (more specifically on different predict result values) and will update you once the bug is fixed. 

Thank you!

**Comment by nikitamaia** [comment]
Updating this thread as the bug of different predict results has been fixed.
