### ISSUE TITLE
name: Bug Issue about: why the performance of nnapi is much lower than cpu . labels: 'type:bug_template'

### ISSUE THREAD

**Issue by songxuemei** [tensorflow/tensorflow#36719]
#36088 # System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:no
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: android O
- **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device**: GLK-AL00,Mi 6,vivo NEX,MI 8 SE

### Describe the problem
I write  nnapidelegate in my Engine just like nnapidelegate in tensorflowlite. When i run the same model, the performance on devices GLK-AL00,Mi 6,vivo NEX,MI 8 SE is more than 200ms, on Pixel 2 XL is 25ms, on mi 9 ,SamSung G9700  is lower than 10ms. Who can tell me why the performance on GLK-AL00,Mi 6,vivo NEX,MI 8 SE is such lower than Pixel 2 XL.

**Comment by renjie-liu** [comment]
nnapi is implemented by OEM, it's possible the hardware vendors have not provided fast implementation yet.
