### ISSUE TITLE
TFRecordDataset causes seg fault with parallel reads and parallel map of an empty file list

### ISSUE THREAD

**Issue by andrewstanfordjason** [tensorflow/tensorflow#36727]
== check python ===================================================
python version: 3.7.4
python branch:
python build version: ('default', 'Sep 7 2019 18:27:02')
python compiler version: Clang 10.0.1 (clang-1001.0.46.4)
python implementation: CPython

== check os platform ===============================================
os: Darwin
os kernel version: Darwin Kernel Version 19.0.0: Wed Sep 25 20:18:50 PDT 2019; root:xnu-6153.11.262/RELEASE_X86_64
os release version: 19.0.0
os platform: Darwin-19.0.0-x86_64-i386-64bit
linux distribution: ('', '', '')
linux os distribution: ('', '', '')
mac version: ('10.15', ('', '', ''), 'x86_64')
uname: uname_result(system='Darwin', node='Andrews-MacBook.local', release='19.0.0', version='Darwin Kernel Version 19.0.0: Wed Sep 25 20:18:50 PDT 2019; root:xnu-6153.11.262/RELEASE_X86_64', machine='x86_64', processor='i386')
architecture: ('64bit', '')
machine: x86_64

== are we in docker =============================================
No

== compiler =====================================================
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun

== check pips ===================================================
numpy 1.17.4
protobuf 3.10.0
tensorflow 2.1.0
tensorflow-estimator 2.0.1

== check for virtualenv =========================================
True

== tensorflow import ============================================
tf.version.VERSION = 2.1.0
tf.version.GIT_VERSION = v2.0.0-rc2-26-g64c3d382ca
tf.version.COMPILER_VERSION = 4.2.1 Compatible Apple LLVM 10.0.0 (clang-1000.11.45.5)

== env ==========================================================
LD_LIBRARY_PATH is unset
DYLD_LIBRARY_PATH is unset

== nvidia-smi ===================================================
./tf_env_collect.sh: line 147: nvidia-smi: command not found

== cuda libs ===================================================

== tensorflow installed from info ==================
Name: tensorflow
Version: 2.1.0
Summary: TensorFlow is an open source machine learning framework for everyone.
Home-page: https://www.tensorflow.org/
Author-email: packages@tensorflow.org
License: Apache 2.0
Location: /Users/andrew/.local/share/virtualenvs/lib_andrew_scratch--yvJ8pLH/lib/python3.7/site-packages
Required-by:

== python version ==============================================
(major, minor, micro, releaselevel, serial)
(3, 7, 4, 'final', 0)

== bazel version ===============================================
Describe the current behavior
Segfault when next is called on the Itterable.

Describe the expected behavior
Crash/Error gracefully

Code to reproduce the issue

```
import tensorflow as tf

def _parse_function(example_proto):
    feature_description = {'features': tf.io.FixedLenFeature([], tf.string)}
    return tf.io.parse_single_example(example_proto, feature_description)

dataset = tf.data.TFRecordDataset([], num_parallel_reads = 2)
dataset = dataset.map(_parse_function, num_parallel_calls = tf.data.experimental.AUTOTUNE)

count = sum([1 for i in dataset])
```

I have reproduced this is Colab 
https://colab.research.google.com/drive/1C6sJ0BVjbK1h78LojPxp1DAuILJC_9e8

**Comment by Saduf2019** [comment]
@andrewstanfordjason I have executed the code shared by you on nightly and do not face any issues, please find the [gist](https://colab.sandbox.google.com/gist/Saduf2019/cf71b3aba378304db1bd1b7ef496bf10/36727.ipynb) for the same.

The colab link shared by you does not have any error.

**Comment by andrewstanfordjason** [comment]
Clearly this is not an issue in the nightly. Thanks
