### ISSUE TITLE
Github issue creation for bugs missing

### ISSUE THREAD

**Issue by phemmer** [tensorflow/tensorflow#36721]
Note that the option for bug reports is missing.

![image](https://user-images.githubusercontent.com/1826947/74403305-c9ba2500-4df4-11ea-8ec4-bc18da185557.png)

I suspect this is related to #36636 which was recently merged.

When I look at the [`00-bug-issue.md` file](https://raw.githubusercontent.com/tensorflow/tensorflow/master/.github/ISSUE_TEMPLATE/00-bug-issue.md), there is a space instead of a newline before `about:`. Don't know if this would cause it to go missing, but definitely seems not right.
![image](https://user-images.githubusercontent.com/1826947/74403503-6381d200-4df5-11ea-8d05-39f44b5c7ed8.png)

Others appear missing as well, such as the build/installation issue, & performance issue.

**Comment by mihaimaruseac** [comment]
Working on a fix
