### ISSUE TITLE
Allow TrtGraphConverterV2 to accept Frozen Graph input as well as saved_model

### ISSUE THREAD

**Issue by mankeyboy** [tensorflow/tensorflow#36723]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using):2.1
- Are you willing to contribute it (Yes/No):Yes

**Describe the feature and the current behavior/state.**
Currently, the trt API for tensorflow [here](https://github.com/tensorflow/tensorflow/blob/39cfd72c068a290cfff3fb5f61009ccc88ec0064/tensorflow/python/compiler/tensorrt/trt_convert.py#L1039) takes only a saved_model dir as input when it internally converts the saved_model to frozen graph before working on it. Before TF2.x, there was support for both in the form of either giving the saved_model directory or giving the frozen graph def. This change has caused codebases which used frozen_graph to break in functionality even after modifying the code to TF2.x supported APIs.
**Will this change the current api? How?**
This will modify the current API to support the previous TrtGraphConverter API
**Who will benefit with this feature?**
Anyone who has been using frozen_graph for converting using TensorRT inside Tensorflow.
**Any Other info.**

**Comment by aaroey** [comment]
@mankeyboy frozen graph is not supported by TF2.0. So instead could you build a SavedModel using your frozen graph, and then use the converter?

**Comment by mankeyboy** [comment]
@aaroey I've been able to convert a frozen graph to a saved_model but I'm somehow unable to get it to save the variables which is why I've been looking for the ability to be able to use the frozen graph directly like the previous APIs.

**Comment by Ekta246** [comment]
> @aaroey I've been able to convert a frozen graph to a saved_model but I'm somehow unable to get it to save the variables which is why I've been looking for the ability to be able to use the frozen graph directly like the previous APIs.

@mankeyboy Thanks for mentioning this issue! I would like to contribute too to TRTGraphconverterV2 accepting an input as frozen_graph.pb. It seems a lot of trouble while benchmarking/inferencing the model with the only TensoRT optimized savedmodel graph. Even if you have an input savedmodel with frozen_graph.pb , saved_model.pb and variables, the TRTGraphConverterV2 will only return an optimized TensorRT savedmodel(containing saved_model.pb and variables) as the API and the codebase of trt_convert.py does that.

Looking forward to contribute too

**Comment by Saduf2019** [comment]
@mankeyboy 

Please update if this is still an issue in later version of tf.
