### ISSUE TITLE
Getting SavedModel format from Checkpoint automatically

### ISSUE THREAD

**Issue by mankeyboy** [tensorflow/tensorflow#36720]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using):2.1.0
- Are you willing to contribute it (Yes/No):Yes

**Describe the feature and the current behavior/state.** None

**Will this change the current api? How?** Add a method to the savedModel API for getting savedModel from checkpoint directly. 

**Who will benefit with this feature?** Everyone who is facing trouble converting to a SavedModel from a checkpoint graph

**Any Other info.**
I've faced this challenge

**Comment by allenlavoie** [comment]
What do you mean by "checkpoint graph"? A GraphDef and a training checkpoint?

**Comment by mankeyboy** [comment]
@allenlavoie Yes, precisely. My feature request stems from this issues I've been facing in getting to a SavedModel given that I have a training checkpoint with all my weights, for eg: 
```
'ssd_inception_v2_coco':
    Model(
        'ssd_inception_v2_coco',
        'http://download.tensorflow.org/models/object_detection/ssd_inception_v2_coco_2018_01_28.tar.gz',
        'ssd_inception_v2_coco_2018_01_28',
    )
```

The challenge I've been facing is in getting from a training checkpoint and a GraphDef to a saved_model which is a wrapping around a frozen graph with signatures and a variables folder where it maintains the trained weights. 
Something of this form: https://gist.github.com/zhanwenchen/d628ef70e9f76525fd47d6213c30730d where I can just specify to the builder API my checkpoint and it can figure out what signatures to use or how to export based on the checkpoint.

**Comment by allenlavoie** [comment]
So the GraphDef here is already frozen?

**Comment by mankeyboy** [comment]
Can you explain what the difference would mean? I'm not sure what difference would occur from a frozen graph def or otherwise.

**Comment by allenlavoie** [comment]
If the GraphDef is frozen, it doesn't refer to a training checkpoint anymore. It just has one set of values for the variables hard-coded. Making a SavedModel from an un-frozen GraphDef that has pointers to variables plus a training checkpoint is easy, but making a SavedModel from a frozen GraphDef and a new training checkpoint isn't really feasible.

**Comment by mankeyboy** [comment]
No, my concern was more in the first direction. Let's say I have a training checkpoint and a frozen graph.pb file, getting to a Saved_model should be something that we should be able to allow directly. From what I've understood, I have to get the GraphDef from the frozen graph and then load the checkpoint. Once I'm here, I have to apply the right input and output placeholders and the signature and this is something that has to be chosen for this. That is what I want to provide. Can you provide some guidance to some docs for the relationship between a training checkpoint and a Saved_Model?

**Comment by allenlavoie** [comment]
Frozen GraphDefs don't really fit into SavedModels. Un-frozen GraphDefs reference a training checkpoint, which a SavedModel has.

For non-frozen GraphDefs you can load (into Python) and re-save as a SavedModel along with a training checkpoint. For frozen GraphDefs this won't work, and I don't know of any efforts in that direction.

**Comment by mankeyboy** [comment]
@allenlavoie Thanks for the clarification. What you're saying basically means that we have no way to get a trained Saved_model from a frozen GraphDef and a training checkpoint because the information about the graph is lost on freezing it. Would the only way around this be to get an untrained saved_model from the graph def and then retrain it to target accuracy?

**Comment by allenlavoie** [comment]
I'm sure you could extract the values of the constants in the GraphDef with Session.run and then assign them to variables, but that's a manual process. Retraining works too.
