### ISSUE TITLE
tf.split for unequal splits when num is odd and size_splits is not available

### ISSUE THREAD

**Issue by kamalravi** [tensorflow/tensorflow#36733]
**System information**
- TensorFlow version: 1.14.0

**Describe the feature and the current behavior/state.**
When I have a tensor of size say [99, 100, 100, 1] and want to split (batch size 99) it into 4 parts (because I have 4 GPUs). It can't be split with the existing function. I don't always know the batch size so I can't use size_splits as well.

**Comment by gadagashwini** [comment]
@kamalravi, Can you provide the sample code snippet to analyze the reported issue. Thanks!

**Comment by kamalravi** [comment]
`    def make_parallel(fn, num_gpus, **kwargs):
        
        in_splits = {}
        for k, v in kwargs.items():
            in_splits[k] = tf.split(v, num_gpus)`

where 
fn is the model
kwargs.items() are input ( [99, 100, 100, 1]) and output data ( [99, 100, 100, 1])
num_gpus is the number of available GPUs.

I want to split input and output almost evenly for each GPU. Thanks!

**Comment by gadagashwini** [comment]
@kamalravi, Did you use Distribution strategy to employ multiple GPUs. Please take a look at different ways to use multiple GPUs in this [doc](https://www.tensorflow.org/guide/distributed_training). Thanks!

**Comment by kamalravi** [comment]
Thanks for the suggestion! Closing the issue.
