### ISSUE TITLE
AttributeError: 'BatchGen' object has no attribute 'shape'

### ISSUE THREAD

**Issue by etetteh** [tensorflow/tensorflow#36734]
I am using TensorFlow version 1.15 for a project. I have converted a BioBert pre-trained model into a Keras layer following the code [here](https://towardsdatascience.com/fine-tuning-bert-with-keras-and-tf-module-ed24ea91cff2). However, when I run my code, I get the following error:

```
Traceback (most recent call last):
  File "/home/jupyter-belona/.conda/envs/mimic-proj/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/jupyter-belona/.conda/envs/mimic-proj/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/jupyter-belona/Untitled_Folder/deep-learning-clinical-forecast/mimic3newmodels/decompensation/main.py", line
152, in <module>
    verbose=args.verbose)
  File "/home/jupyter-belona/.conda/envs/mimic-proj/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/trainin
g.py", line 1296, in fit_generator
    steps_name='steps_per_epoch')
  File "/home/jupyter-belona/.conda/envs/mimic-proj/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/trainin
g_generator.py", line 144, in model_iteration
    shuffle=shuffle)
  File "/home/jupyter-belona/.conda/envs/mimic-proj/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/trainin
g_generator.py", line 477, in convert_to_generator_like
    **num_samples = int(nest.flatten(data)[0].shape[0])**
AttributeError: 'BatchGen' object has no attribute 'shape'
```
Please, how do I fix this error? I really need your help.

**Comment by Saduf2019** [comment]
@etetteh Could you please provide us with a simple stand alone code so we could replicate the issue faced by you.

**Comment by etetteh** [comment]
Please, the steps involve 
1. cloning this [repo](https://github.com/YerevaNN/mimic3-benchmarks)
2. creating the tf.Module Keras layer following this [colab file](https://colab.research.google.com/drive/1ofSfThTBlWjOx5dqXmdsIol-MdiqCyZC)
The model to use is:
```
from __future__ import print_function
from __future__ import absolute_import

import logging
from mimic3newmodels.biobert.biobertlayer import BioBertLayer

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.layers import Input
from tensorflow.keras.models import Model


log = logging.getLogger('tensorflow')
log.handlers = []


class Network(Model):

    def __init__(self, dim, task, num_classes=1, input_dim=76, **kwargs):

        self.dim = dim
        
        if task in ['decomp', 'ihm', 'ph']:
            final_activation = 'sigmoid'
        elif task in ['los']:
            if num_classes == 1:
                final_activation = 'relu'
            else:
                final_activation = 'softmax'
        else:
            raise ValueError("Wrong value for task")

        print("==> not used params in network class:", kwargs.keys())
        
        X = Input(shape=(None, input_dim), name='X')
        inputs = [X]
        
        encoder = BioBertLayer(bert_path="mimic3newmodels/biobert/bert-module/", seq_len=48, tune_embeddings=False,
                    pooling='cls', n_tune_layers=3, verbose=False)
                    
        pred = tf.keras.layers.Dense(num_classes, activation=final_activation)(encoder(inputs))
        outputs = [pred]

        super(Network, self).__init__(inputs=inputs, outputs=outputs)
	
    def say_name(self):
        return "{}.n{}".format('biobert_pubmed',
                                self.dim,
                                )

```

3. Download the dataset [here](https://drive.google.com/drive/folders/1KwXMENqypwDW5kQwRPa945ijUVta428v?usp=sharing)
4. run this line of code
`python -um mimic3newmodels.decompensation.main --network mimic3newmodels/biobert/biobert.py --dim 128 --timestep 1.0 --mode train --batch_size 8 --output_dir mimic3newmodels/decompensation/BIOBERT`

**Comment by Saduf2019** [comment]
@etetteh 
As per the code shared  imported layer is from "from mimic3newmodels.biobert.biobertlayer import BioBertLayer" , whereas the repository shared "https://github.com/YerevaNN/mimic3-benchmarks/tree/master/mimic3models" mimic3newmodels is not present in "mimic3-benchmarks".

Also please refer to this [link](https://github.com/keras-team/keras/issues/12586) if it helps resolve the issue.

**Comment by Saduf2019** [comment]
@etetteh 
Could  you please respond to the above comment.

**Comment by etetteh** [comment]
Please find the needed files here:
https://drive.google.com/drive/folders/1i_CGyn5vQ0WTs6KXjB6KMd6nvZ_vqxlo?usp=sharing

**Comment by Saduf2019** [comment]
@etetteh 
I am unable to access the link shared.

**Comment by Saduf2019** [comment]
@etetteh 
If possible can you please share a colab link of the same with us, we are unable to replicate with the information shared as it still shows same error as informed earlier.

**Comment by etetteh** [comment]
> @etetteh
> As per the code shared imported layer is from "from mimic3newmodels.biobert.biobertlayer import BioBertLayer" , whereas the repository shared "https://github.com/YerevaNN/mimic3-benchmarks/tree/master/mimic3models" mimic3newmodels is not present in "mimic3-benchmarks".
> 
> Also please refer to this [link](https://github.com/keras-team/keras/issues/12586) if it helps resolve the issue.

I don't have a colab file as I wasn't working in Colab. 
Please use this instead
`from mimic3models.biobert.biobertlayer import BioBertLayer"`

Please, check the subdirectories well and create __init__.py file if necessary. 
Create a folder inside the mimic3models called biobert and copy the files [here](https://drive.google.com/drive/folders/1i_CGyn5vQ0WTs6KXjB6KMd6nvZ_vqxlo?usp=sharing) 
inside it. Please, let me know if you need more info

**Comment by gowthamkpr** [comment]
@etetteh As this issue is not not related to build/install, bug/performance, feature request or doc related to issues please post this issue in stackoverflow as there is a wider community to respond. Thanks!

**Comment by Saduf2019** [comment]
@etetteh
please update as per above comment
