### ISSUE TITLE
Best Method To import Multiple Tensorflow Models in Inference

### ISSUE THREAD

**Issue by Abdelrahmanalii** [tensorflow/tensorflow#36746]
suppose i have 3 Models in Tensorflow each for a specific problem while inference with a web cam or in real time processing, my question is how can i import multiple models in one session with their frozen graph and labelpb files ? or what is the best method for doing running the 3 models at the same time ?

**Comment by jvishnuvardhan** [comment]
@Abdelrahmanalii you can create three different [graphs](https://www.tensorflow.org/api_docs/python/tf/Graph) and run them in one session. 
This is not Build/Installation or Bug/Performance issue. Please post this kind of support questions at [Stackoverflow](https://stackoverflow.com/questions/tagged/tensorflow). There is a big community to support and learn from your questions. GitHub is mainly for addressing bugs in installation and performance. Thanks!
