### ISSUE TITLE
Loading the in-memory loaded saved model 

### ISSUE THREAD

**Issue by harshithdwivedi** [tensorflow/tensorflow#36750]
Hi all,
Can someone tell me a way to load an in-memory loaded tensorflow model (a protobuf file) into Tensorflow?

For example, the current code I have is as follows: 
```
model_path = 'path/to/the/model/'
session = tf.Session(graph=tf.Graph())
tf.saved_model.loader.load(session, ['serve'], model_path)
```

However, instead of loading the model by providing its path, I would like to load a model by providing a bytebuffer of the loaded model file.

Can anyone tell me how I can do this? Thanks!

**Comment by gadagashwini** [comment]
@harshithdwivedi, Please find the [doc](https://www.tensorflow.org/tutorials/keras/save_and_load) for Tensorflow save and load model. Thanks!

**Comment by harshithdwivedi** [comment]
I can't find the answer to my issue in the doc that you linked @gadagashwini

**Comment by gowthamkpr** [comment]
@harshithdwivedi What version of tensorflow are you using?

**Comment by allenlavoie** [comment]
In 1.x we have import_graph_def: https://www.tensorflow.org/versions/r1.15/api_docs/python/tf/graph_util/import_graph_def

That doesn't work with variables, since we don't put variable values in protobufs. (Although you could load the variables yourself.)

In 2.x I'd just keep the SavedModel on an in-memory filesystem and use the file-based APIs.

**Comment by harshithdwivedi** [comment]
Hi @allenlavoie , that sounds like a good idea.
Can you point me towards any docs or code examples that let load the an in-memory model in 2.x?

Thanks again!

**Comment by allenlavoie** [comment]
I think `/run/shm/` is in-memory on most Linux systems. This works on my machine:

```
import tensorflow as tf

path = "/run/shm/saved_model/"

m = tf.Module()
m.v = tf.Variable(1.)
tf.saved_model.save(m, path)

imported = tf.saved_model.load(path)
assert imported.v == 1.
```

But on any operating system you should be able to configure one somehow, and once you do that you can just feed the path to TensorFlow.

**Comment by harshithdwivedi** [comment]
This is great, thanks!
I'll try it out and let you know.
cc: @aayusharora
