### ISSUE TITLE
Missing dependencies in image_classification android example for instrumented test ClassifierTest

### ISSUE THREAD

**Issue by amitDaMan** [tensorflow/tensorflow#36763]
**Describe the problem**

**Provide the exact sequence of commands / steps that you executed before running into the problem**

In the tensorflow lite image classification example for android; gradle dependencies for the instrumented test have to be added
 
https://github.com/tensorflow/examples/blob/master/lite/examples/image_classification/android/app/build.gradle

Fix:
needs to be added in the dependencies section: 

    androidTestImplementation 'androidx.test.ext:junit:1.1.1'
    androidTestImplementation 'com.android.support.test:rules:1.0.2'
    androidTestImplementation 'com.google.truth:truth:1.0.1'

**Comment by amitDaMan** [comment]
The fix is given...

**Comment by lintian06** [comment]
Thank you for your comment! We have fixed this. :-)

**Comment by xunkai55** [comment]
https://github.com/tensorflow/examples/commit/92a4dcd9e5db3cb6755f19d9d9450bb07b2f90b5

Thanks a lot for the feedback!
