### ISSUE TITLE
tf.config.list_physical_devices() does not show GPU

### ISSUE THREAD

**Issue by ManasRMohanty** [tensorflow/tensorflow#36776]
**System information** 
OS Platform and Distribution - Windows 10 home
TensorFlow installed using - pip install tensorflow-gpu
TensorFlow version - 2.1.0
Python version - 3.7.4
CUDA/cuDNN version - 10.1
GPU - NVIDIA GeForce GTX 1650

I can see the GPUs in my machine as shown below.
![image](https://user-images.githubusercontent.com/42920503/74582198-e4bc9e80-4f86-11ea-9626-70c844e87bdd.png)

I have installed, visual studio 2019 express, CUDA tool kit 10.1 with cuDNN. 

When I try to see all the physical devices detected by tensorflow, I can see only cpu is detcted.
![image](https://user-images.githubusercontent.com/42920503/74582236-5563bb00-4f87-11ea-9294-863b7a91e11f.png)

Kindly check the issue.

**Comment by ManasRMohanty** [comment]
@amahendrakar The type of this issue is not a bug.

**Comment by ManasRMohanty** [comment]
I can see the GPU after restarting my system.

**Comment by georgeparry12** [comment]
I have a similar issue. Tensorflow can see my GPU however when I run scrips it does not use it? I have been stuck on this for days, any help would be massively appreciated.

**Comment by ManasRMohanty** [comment]
@georgeparry12 I realized that pytorch, cuda and tensorflow all need to be compatible with each other for the above to work. 

Install pytorch using this - conda install pytorch torchvision cudatoolkit=10.1 -c pytorch, If your cuda toolkit is 10.1. Try restarting the system once and check.

**Comment by georgeparry12** [comment]
@ManasRMohanty thank you for this. I tried what you suggested but task manager still shows no activation on the GPU when I run the script? There are more details of the problem on this post-https://github.com/tensorflow/tensorflow/issues/37164 . 

I wonder if you have any more suggestions?
