### ISSUE TITLE
First example on the Tensor page results in an error

### ISSUE THREAD

**Issue by jraman** [tensorflow/tensorflow#36775]
## URL(s) with the issue:

https://www.tensorflow.org/api_docs/python/tf/Tensor

The page has the breadcrumbs `TensorFlow > API > TensorFlow Core v2.1.0 > Python`.

## Description of issue (what needs changing):

Running the first example on the [Tensor](https://www.tensorflow.org/api_docs/python/tf/Tensor) page results in an error.

### Clear description

Here is the outcome of running the first example.
``` py
>>> # Build a dataflow graph.
... c = tf.constant([[1.0, 2.0], [3.0, 4.0]])
>>> d = tf.constant([[1.0, 1.0], [0.0, 1.0]])
>>> e = tf.matmul(c, d)
>>> # Construct a `Session` to execute the graph.
... sess = tf.compat.v1.Session()
>>> # Execute the graph and store the value that `e` represents in `result`.
... result = sess.run(e)
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/usr/local/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 960, in run
    run_metadata_ptr)
  File "/usr/local/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1108, in _run
    raise RuntimeError('The Session graph is empty.  Add operations to the '
RuntimeError: The Session graph is empty.  Add operations to the graph before calling run().
```

I understand from [here](https://kodlogs.com/34085/runtimeerror-the-session-graph-is-empty-add-operations-to-the-graph-before-calling-run) that a session is no longer required in tf v2.

But the Tensor documentation starts off with multiple session references which appears to now be obsolete or not required.

**Comment by gadagashwini** [comment]
I could replicate the issue with Tf 2.1.

**Comment by jvishnuvardhan** [comment]
@jraman This was updates in the `tf-nightly`. Please check it [here](https://www.tensorflow.org/api_docs/python/tf/Tensor?version=nightly). 

By default, eager is enabled in `TF2.x`. If you want to run any op in graph then please disable the eager mode. If you still want to use a `tf.Session` then please add  `tf.compat.v1.disable_eager_execution()` at the start, before defining any operation. 

[Here](https://colab.sandbox.google.com/gist/jvishnuvardhan/41bba3681a9af7724ed235606f09cd7f/tf36775.ipynb) is the gist for your reference. Thanks!

I am closing this issue as it is resolved. Thanks!

**Comment by jraman** [comment]
@jvishnuvardhan, thank you for updating the document.  I was looking for documentation and not a way to use `tf.Session`.  The updated doc looks good to me.

Couple of questions/suggestions:
 1. It may be good to point out early in the document that there are two modes of execution: eager mode (the default) and graph mode.
 1. The updated document refers to Graph mode as legacy.  But, `tf.function` constructs a callable that executes a graph (`tf.Graph`).  Legacy to me connotes something that is out of practice, but I think that here the case is that graph mode is something that is very much in use, but occurs under the hood.  Right?
 1. The link to the Tensor guide does not work for me.  Looks like the link has extra characters.

Thanks!

**Comment by jvishnuvardhan** [comment]
@jraman Agree with you on (1) and (3). regarding (2), `legacy` term was used to denote that graph mode as in TF1.x is going to be out of practice and not supported in the future. A graph mode with `tf.function` in TF2.x is supported. 

Are you interested in creating a PR. If you are not interested, then I will create a PR. If you are interested to create PR, [here](https://www.tensorflow.org/guide/tensor) is the correct link for (3) . Thanks!

**Comment by jraman** [comment]
@jvishnuvardhan, thanks for getting back.  Sure, no worries, I'll create a PR.

I see what you mean by legacy--it's legacy in TF1, but not in TF2.  Since this is documentation for TF2, I think using legacy here may confusing since TF2 supports graph mode.  In any case, let me open a PR and maybe we can take it from there.

**Comment by jraman** [comment]
@jvishnuvardhan, please see [PR-36947](https://github.com/tensorflow/tensorflow/pull/36947).
