### ISSUE TITLE
TFLearn estimators not passing "save_summary_steps"

### ISSUE THREAD

**Issue by eric-czech** [tensorflow/tensorflow#3677]
I think this should be an easy fix (or it was to hack it in locally), but it looks like [supervisor.py:L560](https://github.com/tensorflow/tensorflow/blob/r0.10/tensorflow/contrib/learn/python/learn/estimators/estimator.py#L560) for release **r0.10** is calling ```graph_actions._supervised_train``` without passing the ```save_summary_steps``` parameter now configurable in RunConfig.

I was able to correct by adding ```supervisor_save_summaries_steps=self._config.save_summary_steps``` in the call to graph_actions._supervised_train and this worked as expected, with events showing in TensorBoard on a higher configured frequency than the default 100 steps.

**Comment by terrytangyuan** [comment]
@eric-czech Thanks for reporting! I have submitted a fix. Going forward you are welcome to submit a PR to fix it directly!
