### ISSUE TITLE
tensorflow-1.14 and tensorflow1.15, avx512f does no performance improvements than avx2

### ISSUE THREAD

**Issue by haolujun** [tensorflow/tensorflow#36783]
HI :
    I run a model use tensorflow-1.14 compiled with avx2, avx512f , and found that: avx512 does no performance improvements than avx2. The timeline of avx2 or avx512f were the same as below. MatMul is most expensive op.

Machine A:
avx512 CPU: Intel(R) Xeon(R) Silver 4110 CPU @ 2.10GHz
avx512 compile command: 
bazel build tensorflow:libtensorflow_cc.so -c opt --copt=-march=native --copt=-mfpmath=both  --copt=-mfma --copt=-mavx --copt=-mavx2 --copt=-mavx512f --copt=-mavx512cd --copt=-mavx512dq --copt=-mavx512bw --copt=-mavx512vl . 
gcc version: 7.3.0

Machine B:
avx2 CPU: Intel(R) Xeon(R) CPU E5-2620 v4 @ 2.10GHz
avx2 compile command:
bazel build tensorflow:libtensorflow_cc.so -c opt --copt=-march=native --copt=-mfpmath=both  --copt=-mfma --copt=-mavx --copt=-mavx2 
gcc version: 4.8.5
    
![image](https://user-images.githubusercontent.com/10751631/74588331-6d464800-5036-11ea-80dc-dd26b71e0f25.png)

**Comment by sai110594** [comment]
@haolujun In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thanks!

**Comment by haolujun** [comment]
I think MatMul is most expensive op, and most people say that avx512 can improve the float-mul operation than avx2 two times . But In my case, that not work.

**Comment by gunan** [comment]
@rmlarsen, who would be the best person to investigate this?

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.
