### ISSUE TITLE
New Feature:  Pascal, Cuda 8, Unified memory

### ISSUE THREAD

**Issue by deeplearning-ai-research** [tensorflow/tensorflow#3678]
Hi,

As Cuda 8 enables unified memory for Pascal GPU, combining CPU and GPU on the same address level, and enhancing the memory size available for GPU (with limited latency), using CPU RAM.

1) Is there a possibility to have larger than GPU ram NN+data (lower than CPU ram) for training in tensor flow ? (it would help reducing distributed computing/network latency) ?

ie, using the idea of  Oversubscribe GPU memory for large dataset/models.

here, CUDA API :  
http://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#um-simplifying

Example of 64GB allocation on GPU:

```
void foo() {
// Allocate 64 GB on GPU, using CPU RAM
char *data;
size_t size = 64*1024*1024*1024;
cudaMallocManaged(&data, size);
}
```

**Comment by zheng-xq** [comment]
UVM is implemented through page-fault between CPU and GPU. It makes GPU program easier to be adopted, but not necessarily as fast as possible. Without more investigation, we are not sure this is suitable for high-performance machine learning. Note that the typical bandwidth across PCIE is often about two orders of magnitude slower than accessing the GPU dram itself. 

If the model is indeed too large and cannot fit into GPU memory, it may make sense to load parts of the model in parallel, instead of relying the page faults in the kernels to page in the data.

**Comment by arita37** [comment]
Cuda 8 with Pascal has Nvlink which is 80Gb/sec, so Latency is very low between RAM.
It allows to create larger than GPU memory through single memory allocation,
At very low latency. Performance would be enhanced.

See the slides.

**Comment by zheng-xq** [comment]
My understanding was that 80GB/s was between devices. The CPU/GPU communication through PCIE used by UVM is only a small fraction of that. And they are both much smaller than the 720GB/s when GPU accessing its own memory.

This is an active research area, and we might still find a good use of UVM down the road. But the current belief is that it is better to page in/out memory with CPU in parallel, while the compute engine on GPU accesses its own memory in full speed. A good example is the "swap_memory" option in "tf.while_loop", which swaps the temporary memory created in the loop to the host, when the device memory is under pressure.

**Comment by yaroslavvb** [comment]
initial support added in github.com/tensorflow/tensorflow/commit/cd4f5840

**Comment by evolu8** [comment]
UVM support throughout would be of enormous benefit. I would be very keen to see this implemented. Having ideal training throughput is often less important than coping with large input and large model sizes which simply fail to fit on a card.

**Comment by byronyi** [comment]
Looks like another “we don’t need distributed transactions in Google so we choose to let users implement crappy/wrong versions of their own” for BigTable/MegaStore.

Now we have Spanner :)

**Comment by ranshadmi** [comment]
+1 for "UVM support throughout"!

**Comment by Orna123** [comment]
+1 for "UVM support throughout"!

**Comment by Orna123** [comment]
+1 for "UVM support throughout"!

**Comment by evolu8** [comment]
Any movement on this? 

Cheers

**Comment by tarlovsky** [comment]
Hey guys, any progress? Highly interested!

**Comment by smit-hinsu** [comment]
UVM support was added recently in https://github.com/tensorflow/tensorflow/commit/b1139814.

**Comment by denfromufa** [comment]
Unified memory in Power9/V100 avoids page faults and page migrations with NVLINK 2.0 connection:

http://on-demand.gputechconf.com/gtc/2018/presentation/s8430-everything-you-need-to-know-about-unified-memory.pdf

**Comment by donglinjy** [comment]
@smit-hinsu do you know how uvm can be used in Tensorflow 2.0?

**Comment by smit-hinsu** [comment]
@donglinjy I don't think uvm configuration is exposed in TF 2.0. Please file a separate feature request for that.

cc @aaroey @jaingaurav
