### ISSUE TITLE
  AttributeError: 'module' object has no attribute 'random_normal' 

### ISSUE THREAD

**Issue by LGDHS** [tensorflow/tensorflow#36787]
AttributeError                            Traceback (most recent call last)
<ipython-input-5-73592c5fe983> in <module>()
----> 1 W=tf.Variable(initial_value=tf.random_normal(shape=(1,4),mean=100,stddev=0.35),name="W")
      2 b=tf.Variable(tf.zeros([4]),name="b")

AttributeError: 'module' object has no attribute 'random_normal'

tf has no attribute 'random_normal' ?

**Comment by Saduf2019** [comment]
@LGDHS Please provide with executable stand alone code to replicate this issue in our environment along with the version on tensorflow been used.

**Comment by SivamPillai** [comment]
I believe the library now uses `tf.random.normal()` instead of the older `tf.random_normal()`. Please replace the function and see if that works. I am assuming you are using TF2.0. Sharing here as I was also once stuck with this error to later realize the problem!

HTH

**Comment by Saduf2019** [comment]
@LGDHS please confirm if the above comment helps

**Comment by eboily** [comment]
I confirm @SivamPillai 's  solution above. Replace the "`_`" with a "`.`".
```bash
$ python3 -c "import tensorflow as tf; print(tf.reduce_sum(tf.random.normal([1000, 1000])))"
tf.Tensor(-1584.1108, shape=(), dtype=float32)
```

**Comment by Saduf2019** [comment]
As the solution above helps, moving this issue to closed status.
