### ISSUE TITLE
Unable to package tensorflow with Py2App

### ISSUE THREAD

**Issue by harshithdwivedi** [tensorflow/tensorflow#36782]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): MacOS Catalina
- TensorFlow installed from (source or binary): Binary
- TensorFlow version: 2.1.0
- Python version: 3.7
- Installed using virtualenv? pip? conda?: Yes, installed in a virtualenv using pip
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

**Describe the problem**
On running an executable that was packaged using Py2App, the executable throws the following error: 

```
File "/Users/harshitdwivedi/Desktop/aftershootscripts/dist/aftershoot.app/Contents/Resources/aftershoot.py", line 4, in <module>
    import asexposure.ASExposure as Exposure
  File "asexposure/ASExposure.pyc", line 1, in <module>
  File "/Users/harshitdwivedi/Desktop/aftershootscripts/dist/aftershoot.app/Contents/Resources/lib/python3.7/tensorflow/__init__.py", line 98, in <module>
    from tensorflow_core import *
  File "/Users/harshitdwivedi/Desktop/aftershootscripts/dist/aftershoot.app/Contents/Resources/lib/python3.7/tensorflow_core/__init__.py", line 40, in <module>
    from tensorflow.python.tools import module_util as _module_util
ModuleNotFoundError: No module named 'tensorflow.python.tools'; 'tensorflow.python' is not a package
```
Upon looking into the line of code causing this issue, it looks like `tensorflow_core`'s `init.py` is trying to import `module_util` from `tensorflow.python.tools`. However, isnide my site-packages,  there's northing inside the package named `tensorflow`. Instead the package above `python.tools` exists inside `tensorflow_core`.

Here's a screenshot showcasing this: 

<img width="626" alt="Screenshot 2020-02-15 at 6 06 56 PM" src="https://user-images.githubusercontent.com/47669588/74587897-20567780-501e-11ea-9ff1-91b268c2a160.png">

As you can see here, python folder is inside tensorflow_core, but the init.py tries to refer it from tensorflow.
<img width="817" alt="Screenshot 2020-02-15 at 6 07 52 PM" src="https://user-images.githubusercontent.com/47669588/74587901-264c5880-501e-11ea-9814-63e8d9ded432.png">

Is this a known issue? And if so, is there a way to fix this?

**Comment by ymodak** [comment]
Apologies for the delay in response. Is this still an issue? You may refer this [thread](https://github.com/tensorflow/tensorflow/issues/34722)

**Comment by ymodak** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
