### ISSUE TITLE
a bug about tf.function

### ISSUE THREAD

**Issue by paokuwansui** [tensorflow/tensorflow#36794]
WARNING:tensorflow:AutoGraph could not transform <function converge_to_2 at 0x7f6e047dae50> and will run it as-is.
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: invalid value for "node": expected "ast.AST", got "<class 'NoneType'>"; to visit lists of nodes, use "visit_block" instead
WARNING: AutoGraph could not transform <function converge_to_2 at 0x7f6e047dae50> and will run it as-is.
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: invalid value for "node": expected "ast.AST", got "<class 'NoneType'>"; to visit lists of nodes, use "visit_block" instead
tf.Tensor(1.9999981, shape=(), dtype=float32)

**Comment by paokuwansui** [comment]
@tf.function
def converge_to_2(n_iters):
    total = tf.constant(0.)
    increment = tf.constant(1.)
    for _ in range(n_iters):
        total +=increment
        increment /= 2.0
    return total
print(converge_to_2(20))

**Comment by gadagashwini** [comment]
@paokuwansui, Check the `gast` version. Tensorflow 2.x supports gast ==0.2.2. Thanks!

**Comment by paokuwansui** [comment]
Thank you, but my gast == 0.2.2

docutils                   0.16    
entrypoints                0.3     
et-xmlfile                 1.0.1   
future                     0.18.2  
gast                       0.2.2   #-----------------------
google-auth                1.10.0  
google-auth-oauthlib       0.4.1   
google-pasta               0.1.7   
grpcio                     1.27.0  
h5py                       2.10.0  
html5lib                   1.0.1   
idna                       2.8

**Comment by gadagashwini** [comment]
@paokuwansui, Can you provide the complete code to replicate the reported issue. Thanks!

**Comment by gadagashwini** [comment]
@paokuwansui, Is this still an issue?

**Comment by paokuwansui** [comment]
import tensorflow as tf
@tf.function
def converge_to_2(n_iters):
    total = tf.constant(0.)
    increment = tf.constant(1.)
    for _ in range(n_iters):
        total +=increment
        increment /= 2.0
    return total
print(converge_to_2(20))

**Comment by paokuwansui** [comment]
> Is this still an issue?
Yes, this problem is still unresolved 
My system is manjaro
tensorflow == 2.1.0

Source code：
import tensorflow as tf
@tf.function
def converge_to_2(n_iters):
  total = tf.constant(0.)
  increment = tf.constant(1.)
  for _ in range(n_iters):
    total +=increment
    increment /= 2.0
  return total
print(converge_to_2(20))

**Comment by gadagashwini** [comment]
@paokuwansui, I tried on colab with Tf 2.1. Its working without any warnings.
Please take a look at gist [here](https://colab.sandbox.google.com/gist/gadagashwini/68db324a7685ee397abf70aa28b0ce7e/untitled421.ipynb). Thanks!

**Comment by gadagashwini** [comment]
@paokuwansui, Let us if still issue persists. Thanks!

**Comment by paokuwansui** [comment]
Yes, I hope I can provide you with more information

But i don't know what information to give you

[lzh@lzh-pc ~]$ python
Python 3.8.1 (default, Jan 22 2020, 06:38:00) 
[GCC 9.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
>>> @tf.function
... def a (n):
...     return n*2
... 
>>> a(10)
2020-03-13 19:09:06.982192: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE3 SSE4.1 SSE4.2 AVX AVX2 FMA
2020-03-13 19:09:07.030306: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 1800500000 Hz
2020-03-13 19:09:07.031321: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x55f35ef5d720 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-03-13 19:09:07.031349: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
WARNING:tensorflow:AutoGraph could not transform <function a at 0x7fe0080c50d0> and will run it as-is.
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: Unable to locate the source code of <function a at 0x7fe0080c50d0>. Note that functions defined in certain environments, like the interactive Python shell do not expose their source code. If that is the case, you should to define them in a .py source file. If you are certain the code is graph-compatible, wrap the call using @tf.autograph.do_not_convert. Original error: could not get source code
WARNING: AutoGraph could not transform <function a at 0x7fe0080c50d0> and will run it as-is.
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: Unable to locate the source code of <function a at 0x7fe0080c50d0>. Note that functions defined in certain environments, like the interactive Python shell do not expose their source code. If that is the case, you should to define them in a .py source file. If you are certain the code is graph-compatible, wrap the call using @tf.autograph.do_not_convert. Original error: could not get source code
<tf.Tensor: shape=(), dtype=int32, numpy=20>
>>> 




I use a laptop
The system is manjaro
CPU is i5 8550u
The graphics card is Max150

**Comment by gowthamkpr** [comment]
@paokuwansui You can safely ignore the warning log as its intended to debug logging in AutoGraph issues. Thanks !

**Comment by paokuwansui** [comment]
Thank you very much------------------ 原始邮件 ------------------
发件人: "gowthamkpr"<notifications@github.com>
发送时间: 2020年3月31日(星期二) 凌晨5:48
收件人: "tensorflow/tensorflow"<tensorflow@noreply.github.com>;
抄送: "paokuwansui"<1059773473@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [tensorflow/tensorflow] a bug about tf.function (#36794)




 
@paokuwansui You can safely ignore the warning log as its intended to debug logging in AutoGraph issues. Thanks !
 
&mdash;
