### ISSUE TITLE
Same input - different output

### ISSUE THREAD

**Issue by oeyvindds** [tensorflow/tensorflow#36793]
I have written a small code, and notice that I get a different result dependent on if I use Numpy or not. 

This code should give the same result for both df_dy and df_dy_p, but it does not. It does not matter if I change the order of the calculations. 

`from math import e
import numpy as np

def calc_sigma(y):
    return 1 / (1 + e**-y)

def get_derivative(x, y):
    with tf.GradientTape(persistent=True) as tape:
        tape.watch(x)
        sigma = cal_sigma(-y)
        f = (x + sigma) / np.power((x - y), 2)
        p = (x + sigma) / ((x -y)**2)
    print(x, y, f, p)
    df_dy = tape.gradient(f, x) 
    df_dy_p = tape.gradient(p, x)
    print(df_dy)
    print(df_dy_p)

x = tf.constant (1.)
y = tf.constant (-3.)
get_derivative(x, y)`

The output is:

tf.Tensor(1.0, shape=(), dtype=float32) tf.Tensor(-3.0, shape=(), dtype=float32) tf.Tensor(0.12203588, shape=(), dtype=float32) tf.Tensor(0.12203588, shape=(), dtype=float32)
tf.Tensor(0.0625, shape=(), dtype=float32)
tf.Tensor(0.0014820583, shape=(), dtype=float32)

As one can see, the input is the same, but the output differs.

**Comment by Saduf2019** [comment]
@oeyvindds please provide with simple stand alone code with all dependencies from the code for us to replicate in our environment, i was unable to replicate the code shared by you due to dependencies in the code.
Also please highlight the tensorflow version you are facing th eissue in.

**Comment by oeyvindds** [comment]
Hello.

Here is a complete code that runs fine on my machine (Anaconda Python) in an empty notebook:

`import tensorflow as tf
import numpy as np
from math import e

def calc_sigma(y):
    return 1 / (1 + e**-y)

def get_derivative(x, y):
    with tf.GradientTape(persistent=True) as tape:
        tape.watch(x)
        sigma = calc_sigma(-y)
        f = (x + sigma) / np.power((x - y), 2)
        p = (x + sigma) / ((x -y)**2)
    print('Variable x: {}'.format(x))
    print('Variable y: {}'.format(y))
    print('Input from f: {}'.format(f))
    print('Input from p: {}'.format(p))
    
    df_dy_p = tape.gradient(p, x)
    df_dy = tape.gradient(f, x) 
    
    print('Output from f: {}'.format(df_dy))
    print('Output from p: {}'.format(df_dy_p))

x = tf.constant (1.)
y = tf.constant (-3.)
get_derivative(x, y)`

tf.__version__ gives '2.1.0'

The code give the following output:

Variable x: 1.0
Variable y: -3.0
Input from f: 0.12203588336706161
Input from p: 0.12203588336706161
Output from f: 0.0625
Output from p: 0.0014820583164691925

**Comment by Saduf2019** [comment]
@oeyvindds please provide us with indented code that is executable and has all dependencies, code shared is not indented , dependencies are not shared.
you could share a gist of your code using colab.

**Comment by oeyvindds** [comment]
Here is the code indented:

```
from math import e
import numpy as np
import tensorflow as tf
print(tf.__version__)

def calc_sigma(y):
    return 1 / (1 + e**-y)

def get_derivative(x, y):
    with tf.GradientTape(persistent=True) as tape:
        tape.watch(x)
        sigma = calc_sigma(-y)
        f = (x + sigma) / np.power((x - y), 2)
        p = (x + sigma) / ((x -y)**2)
        
        print(x, y, f, p)
    df_dy = tape.gradient(f, x)
    df_dy_p = tape.gradient(p, x)
    print(df_dy)
    print(df_dy_p)

x = tf.constant (1.)
y = tf.constant (-3.)
get_derivative(x, y)
```
It gives this output:
```
2.1.0
tf.Tensor(1.0, shape=(), dtype=float32) tf.Tensor(-3.0, shape=(), dtype=float32) tf.Tensor(0.12203588, shape=(), dtype=float32) tf.Tensor(0.12203588, shape=(), dtype=float32)
tf.Tensor(0.0625, shape=(), dtype=float32)
tf.Tensor(0.0014820583, shape=(), dtype=float32)
```

**Comment by Saduf2019** [comment]
I am able to replicate this issue, please find the gist [here](https://colab.sandbox.google.com/gist/Saduf2019/e550000c42d48279ab15c62c12253e54/untitled53.ipynb)

**Comment by ashutosh1919** [comment]
@oeyvindds and @Saduf2019, The problem is because the f is evaluated by converting (x-y)^2 in numpy before computing gradient. So, in f, denominator `np.power((x-y),2)` is not a variable at the time of differentiation. Instead, it is a constant with value 16. 
Whereas, in p, `((x-y)**2)` is a tensor and it will be variable at the time of differentiation.

Look at below two codes which are tested and their outputs:

**Code 1 :**
```py
from math import e
import numpy as np
import tensorflow as tf

def calc_sigma(y):
    return 1 / (1 + e**-y)

def get_derivative(x, y):
    with tf.GradientTape(persistent=True) as tape:
        tape.watch(x)
        sigma = calc_sigma(-y)
        f = (x + sigma) / np.power((x - y), 2)
        p = (x + sigma) / ((x-y)**2).numpy()
        
    df_dy = tape.gradient(f, x)
    df_dy_p = tape.gradient(p, x)
    print(df_dy)
    print(df_dy_p)

x = tf.constant (1.)
y = tf.constant (-3.)
get_derivative(x, y)
```
**Output :**
```py
tf.Tensor(0.0625, shape=(), dtype=float32)
tf.Tensor(0.0625, shape=(), dtype=float32)
```

**Code 2:**
```py
from math import e
import numpy as np
import tensorflow as tf

def calc_sigma(y):
    return 1 / (1 + e**-y)

def get_derivative(x, y):
    with tf.GradientTape(persistent=True) as tape:
        tape.watch(x)
        sigma = calc_sigma(-y)
        f = (x + sigma) / tf.math.square(x - y)
        p = (x + sigma) / ((x-y)**2)
        
    df_dy = tape.gradient(f, x)
    df_dy_p = tape.gradient(p, x)
    print(df_dy)
    print(df_dy_p)

x = tf.constant (1.)
y = tf.constant (-3.)
get_derivative(x, y)
```
**Output :**
```py
tf.Tensor(0.0014820583, shape=(), dtype=float32)
tf.Tensor(0.0014820583, shape=(), dtype=float32)
```
