### ISSUE TITLE
Sampled decoding instead of argmax decoding in seq2seq (feature request for tf.choice)

### ISSUE THREAD

**Issue by sherjilozair** [tensorflow/tensorflow#368]
Currently, the seq2seq decoders only support argmax decoding. To enable sampled decoding, we would need a `tf.choice` function to replace `tf.argmax` in https://github.com/tensorflow/tensorflow/blob/master/tensorflow/models/rnn/seq2seq.py#L326

Any plans on implementing this? Can the desired functionality be achieved using other ways?

Theano's `choice` function: http://deeplearning.net/software/theano/library/tensor/raw_random.html
However, it would be preferable for `choice` to have the same interface as `argmax`.

**Comment by lukaszkaiser** [comment]
You're right, we should have an op like choice. Currently this is not easy to do, even though a similar functionality exists in candidate sampling ops (http://www.tensorflow.org/api_docs/python/nn.html#candidate-samplers). We are working on re-implementing candidate sampling in a cleaner way, and we'll take a look at adding a choice-like op when doing this.

**Comment by girving** [comment]
@lukaszkaiser, @gouwsmeister: Stephan said he doesn't have active plans to work on `tf.choice`, so we're happy to accept PRs if anyone else wants to add it.

**Comment by nikitakit** [comment]
If I understand correctly, `tf.multinomial` is general enough such that a `tf.choice` is not necessary to implement sampled decoding.

Here is a snippet of code from my current project, which I believe corresponds to "sampled decoding", as requested here.

```python
def sample_and_embed(choices, prev, i):
    """Loop_function that samples a symbol based on prev logits and embeds it."""
    prev_symbol = tf.multinomial(tf.nn.log_softmax(prev), 1)[:,0]
    choices.append(prev_symbol)
    return embedding_ops.embedding_lookup(embedding_table, prev_symbol)

with vs.variable_scope("decoder"):
    choices = []
    loop_function = lambda prev, i: sample_and_embed(choices, prev, i)
    outputs, states = seq2seq.rnn_decoder([start_token_value] + [None] * (SEQ_LENGTH-1),
                                initial_state,
                                cell,
                                loop_function = loop_function
                                                 )
    loop_function(outputs[-1], len(outputs)) # Select a value for the last token!
```

**Comment by girving** [comment]
@lukaszkaiser Does `tf.multinomial` obviate `tf.choice`?

**Comment by lukaszkaiser** [comment]
I think it does, thanks! With the example above, I think we can close this issue. Great thanks nikitakit!
