### ISSUE TITLE
DataLoss error on TFRecords - Randomly when accessing the dataset on S3 like storage

### ISSUE THREAD

**Issue by cheyang** [tensorflow/tensorflow#36802]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information** 
- OS Platform and Distribution (e.g.,Linux Ubuntu 16.04): CentOS Linux 7.7
- TensorFlow installed from (source or
binary): binary
- TensorFlow version (use command below): 1.14.0
- Python version: 3.6.8
- Bazel
- CUDA/cuDNN version: 410.79/V10.0.130
- GPU model and memory: V100 8 GPUs /16130MiB

**Describe the current behavior**

I'm running tensorflow benchmark ResNet50 on Fuse of cloud storage(Alibaba Cloud Storage: oss). It succeed many times, or failed at the beginning of training. And when it passed the beginning,  it never failed during the training. And the speed is also good.

 The workload is 4 V100 GPU instances and each has 8 GPUs: 32 GPUs in total. 

```
  (0) Data loss: corrupted record at 0
	 [[{{node MultiDeviceIteratorGetNextFromShard}}]]
	 [[RemoteCall]]
	 [[input_processing/IteratorGetNext]]
	 [[cluster_5_1/merge_oidx_1/_951]]
  (1) Data loss: corrupted record at 0
	 [[{{node MultiDeviceIteratorGetNextFromShard}}]]
	 [[RemoteCall]]
	 [[input_processing/IteratorGetNext]]
0 successful operations.
0 derived errors ignored.
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1356, in _do_call
    return fn(*args)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1341, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1429, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.DataLossError: 2 root error(s) found.
  (0) Data loss: corrupted record at 0
	 [[{{node MultiDeviceIteratorGetNextFromShard}}]]
	 [[RemoteCall]]
	 [[input_processing/IteratorGetNext]]
	 [[cluster_5_1/merge_oidx_1/_951]]
  (1) Data loss: corrupted record at 0
	 [[{{node MultiDeviceIteratorGetNextFromShard}}]]
	 [[RemoteCall]]
	 [[input_processing/IteratorGetNext]]
```

I can make sure the tfrecords are correct, because we have checked it one by one.
The logs of fuse and Cloud storage system doesn't have any hint.
Could your guys suggest what may cause this issue? Is there any latency requirement? Or could we set timeout in somewhere? Thanks very much for your help!

Here is the full log:
[test.log](https://github.com/tensorflow/tensorflow/files/4211351/test.log)

**Describe the expected behavior**

**Code to reproduce the issue** Provide a reproducible test case that is the
bare minimum necessary to generate the problem.

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by gowthamkpr** [comment]
Please take a look at this [issue](https://github.com/tensorflow/tensorflow/issues/13463) especially this [comment](https://github.com/tensorflow/tensorflow/issues/13463#issuecomment-456122189) and this [one](https://github.com/tensorflow/tensorflow/issues/13463#issuecomment-460947809) and let me know if it helps. Thanks!

**Comment by cheyang** [comment]
It doesn't really help. May I know what may cause this issue? It's my guess on the storage level. https://github.com/Alluxio/alluxio/issues/10929 Does it make sense?

**Comment by gowthamkpr** [comment]
@cheyang Please try using `tf.data.experimental.ignore_errors()` as fixed in this issue [here](https://github.com/tensorflow/tensorflow/issues/25700). This should help you work around Data loss error as shown [here](https://github.com/tensorflow/tensorflow/blob/00fad90125b18b80fe054de1055770cfb8fe4ba3/tensorflow/core/kernels/data/reader_dataset_ops.cc#L848) I cannot exactly point to the reason why its happening in your case.

@jsimsa Can you PTAL?

**Comment by cheyang** [comment]
I was trying to add some debug info in the fuse level, and found there are really zero bytes in some reads. Can this give you some ideas on this issue?

alluxio-fuse-c9qx2-alluxio-fuse.log:2020-03-14 12:20:12,531 ERROR AlluxioFuseFileSystem - read(file=/train/train-00847-of-01024,offset=103022136,size=456): all bytes zero
alluxio-fuse-c9qx2-alluxio-fuse.log:2020-03-14 12:20:39,752 ERROR AlluxioFuseFileSystem - read(file=/train/train-00586-of-01024,offset=144964184,size=1448): all bytes zero
alluxio-fuse-hrvzs-alluxio-fuse.log:2020-03-14 12:20:15,441 ERROR AlluxioFuseFileSystem - read(file=/train/train-00048-of-01024,offset=121632152,size=2664): all bytes zero
alluxio-fuse-hrvzs-alluxio-fuse.log:2020-03-14 12:20:41,876 ERROR AlluxioFuseFileSystem - read(file=/train/train-00489-of-01024,offset=13631032,size=456): all bytes zero
alluxio-fuse-qp4b4-alluxio-fuse.log:2020-03-14 12:20:40,514 ERROR AlluxioFuseFileSystem - read(file=/train/train-00271-of-01024,offset=1310264,size=456): all bytes zero
alluxio-fuse-qp4b4-alluxio-fuse.log:2020-03-14 12:20:41,806 ERROR AlluxioFuseFileSystem - read(file=/train/train-00487-of-01024,offset=10484232,size=1528): all bytes zero

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.
