### ISSUE TITLE
Gradient Support for Unique operator

### ISSUE THREAD

**Issue by Prasandhmcw** [tensorflow/tensorflow#36810]
I am trying to run a custom graph with only Unique op for a debugging.

`with tf.GradientTape() as g:
y = tf.unique(x)
dy_dx = g.gradient(y, x)`

The Forward pass runs fine, but getting this error during Backward pass:

> LookupError: gradient registry has no entry for: Unique

Gradient yet to be supported for Unique (or) there is no gradient for Unique ? Please help me understand why incase if its the second one.

**Comment by Saduf2019** [comment]
@Prasandhmcw please provide us with complete executable code and the tensorflow version to replicate the issue faced by you in our environment.

**Comment by Prasandhmcw** [comment]
File : (please rename to .py)

[unique.txt](https://github.com/tensorflow/tensorflow/files/4213491/unique.txt)

TF version : 
`>>> tf.__version__
'1.14.0'`

**Comment by Saduf2019** [comment]
i have replicated the code shared and issue persist, please find the gist [here](https://colab.sandbox.google.com/gist/Saduf2019/2299cbbb43b152bfdb731fc81e005086/36810.ipynb)

**Comment by Prasandhmcw** [comment]
@gowthamkpr the labels have been changed, does this mean Gradient for Unique is not yet supported ?

**Comment by gowthamkpr** [comment]
I think you have to register this op as mentioned [here](https://stackoverflow.com/questions/51777535/gradient-registry-has-no-entry-for-a-tensorflow-custom-op) @Prasandhmcw

**Comment by Prasandhmcw** [comment]
@gowthamkpr But this ain't a Custom Op. Its one of the TF's operator - https://www.tensorflow.org/api_docs/python/tf/unique

**Comment by ccrusius** [comment]
I don't belive there's a gradient, but re-assigning to Yong Tang for double-checking.

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.
