### ISSUE TITLE
Segmentation Fault When Importing Tensorflow

### ISSUE THREAD

**Issue by denru01** [tensorflow/tensorflow#3681]
GitHub issues are for bugs / installation problems / feature requests.  
For general support from the community, see [StackOverflow](https://stackoverflow.com/questions/tagged/tensorflow).
To make bugs and feature requests more easy to find and organize, we close issues that are deemed
out of scope for GitHub Issues and point people to StackOverflow.

For bugs or installation issues, please provide the following information.
The more information you provide, the more easily we will be able to offer
help and advice.
### Environment info

Operating System: CentOS 6.8/RedHat 6.8

Installed version of CUDA and cuDNN: 
(please attach the output of `ls -l /path/to/cuda/lib/libcud*`):
CUDA 7.5 + cuDNN v4

If installed from binary pip package, provide:
1. Which pip package you installed.
2. The output from `python -c "import tensorflow; print(tensorflow.__version__)"`.

If installed from source, provide 
1. The commit hash (`git rev-parse HEAD`)
2. The output of `bazel version`
### Steps to reproduce
1. Install tensorflow by using anaconda (conda command)
2. Install glibc "locally" and add the path /glibc-2.14/lib to LD_LIBRARY_PATH
3. Open python and use the command "import tensorflow as tf", and then you will get the message "Segmentation Fault". No other messages.
### What have you tried?
1. Use gdb to see what causes the segmentation fault.
### Logs or other output that would be helpful

gdb messages:
[New Thread 0x7f653bf9f700 (LWP 71825)]
[New Thread 0x7f653b59e700 (LWP 71826)]
[New Thread 0x7f6538b9d700 (LWP 71827)]
[New Thread 0x7f653619c700 (LWP 71828)]
[New Thread 0x7f653379b700 (LWP 71829)]
[New Thread 0x7f6530d9a700 (LWP 71830)]
[New Thread 0x7f652e399700 (LWP 71831)]
[New Thread 0x7f652b998700 (LWP 71832)]
[New Thread 0x7f6528f97700 (LWP 71833)]
[New Thread 0x7f6526596700 (LWP 71834)]
[New Thread 0x7f6523b95700 (LWP 71835)]
[New Thread 0x7f6521194700 (LWP 71836)]
[New Thread 0x7f651e793700 (LWP 71837)]
[New Thread 0x7f651bd92700 (LWP 71838)]
[New Thread 0x7f6519391700 (LWP 71839)]
[New Thread 0x7f6516990700 (LWP 71840)]
[New Thread 0x7f6513f8f700 (LWP 71841)]
[New Thread 0x7f651158e700 (LWP 71842)]
[New Thread 0x7f650eb8d700 (LWP 71843)]
[New Thread 0x7f650c18c700 (LWP 71844)]
[New Thread 0x7f650978b700 (LWP 71845)]
[New Thread 0x7f6506d8a700 (LWP 71846)]
[New Thread 0x7f6504389700 (LWP 71847)]
[New Thread 0x7f6501988700 (LWP 71848)]
[New Thread 0x7f64fef87700 (LWP 71849)]
[New Thread 0x7f64fc586700 (LWP 71850)]
[New Thread 0x7f64f9b85700 (LWP 71851)]
[New Thread 0x7f64f5184700 (LWP 71852)]
[New Thread 0x7f64f4783700 (LWP 71853)]
[New Thread 0x7f64f1d82700 (LWP 71854)]
[New Thread 0x7f64ef381700 (LWP 71855)]
[New Thread 0x7f64ec980700 (LWP 71856)]
[New Thread 0x7f64e9f7f700 (LWP 71857)]
[New Thread 0x7f64e757e700 (LWP 71858)]
[New Thread 0x7f64e4b7d700 (LWP 71859)]
[New Thread 0x7f64e217c700 (LWP 71860)]
[New Thread 0x7f64df77b700 (LWP 71861)]
[New Thread 0x7f64dcd7a700 (LWP 71862)]
[New Thread 0x7f64da379700 (LWP 71863)]
[New Thread 0x7f64d7978700 (LWP 71864)]
[New Thread 0x7f64d4f77700 (LWP 71865)]
[New Thread 0x7f64d2576700 (LWP 71866)]
[New Thread 0x7f64cfb75700 (LWP 71867)]
[New Thread 0x7f64cd174700 (LWP 71868)]
[New Thread 0x7f64ca773700 (LWP 71869)]
[New Thread 0x7f64c7d72700 (LWP 71870)]
[New Thread 0x7f64c5371700 (LWP 71871)]
[New Thread 0x7f64c2970700 (LWP 71872)]
[New Thread 0x7f64bff6f700 (LWP 71873)]
[New Thread 0x7f64bd56e700 (LWP 71874)]
[New Thread 0x7f64bab6d700 (LWP 71875)]
[New Thread 0x7f64b816c700 (LWP 71876)]
[New Thread 0x7f64b576b700 (LWP 71877)]
[New Thread 0x7f64b2d6a700 (LWP 71878)]
[New Thread 0x7f64b0369700 (LWP 71879)]

Program received signal SIGSEGV, Segmentation fault.
__pthread_init_static_tls (map=0x0) at allocatestack.c:1196
1196        init_one_static_tls (list_entry (runp, struct pthread, list), map);
from /home/abc/Libraries/glibc-2.14/install/lib/libpthread.so.0

Because they are clusters, it is hard (or nearly impossible in the near future) to upgrade the OSs. I also have no root privilege.
At first, I got an error telling that I don't have glibc_2.14.so because RedHat/CentOS 6.8 only comes with glibc 2.12. Therefore, I locally compiled the glibc and added it to LD_LIBRARY_PATH. After then, the glibc_2.14 error disappeared and was replaced by another error "Segmentation Fault" (no other messages). Something like this:
import tensorflow as tf
Segmentation Fault
(tensorflow) bash-4.1$

I tried to use gdb to see what causes this error, and it turns out it is "libpthread.so.0".

Any ideas?

Thanks.

**Comment by girving** [comment]
Unfortunately, this isn't enough information to help.  However, it sounds like you have dueling versions of glibc, and you're almost certainly going to need to compile your own version of TensorFlow to make this work.  Since we do not officially support CentOS, there's no guarantee that it will be solvable.

**Comment by xwhan** [comment]
I encountered this problem too. This problem can be solved in a different way.
[https://anaconda.org/jjhelmus/tensorflow](url)

**Comment by steelah1** [comment]
The above anaconda link is dead, and I'm getting the exact messages that denru01 is getting, ie "Segmentation Fault" with no other messages. I got that after "locally" installing glibc 2.14 and pointing LD_LIBRARY_PATH to it. Anything else I can try to get this to work on centos 6.8?

**Comment by xwhan** [comment]
Try this one [https://anaconda.org/jjhelmus/tensorflow](https://anaconda.org/jjhelmus/tensorflow)

**Comment by steelah1** [comment]
No luchk :-/, same result, even after uninstalling tensorflow

**Comment by itsmeolivia** [comment]
Automatically closing due to lack of recent activity. Since this issue is old at this point, please reopen the issue if it still occurs when tried with the latest version of Tensorflow. Thank you.
