### ISSUE TITLE
Keras fit generator - ValueError: Failed to find data adapter that can handle input

### ISSUE THREAD

**Issue by castilho25** [tensorflow/tensorflow#36819]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information** - Have I written custom code (as opposed to using a stock
example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g.,
Linux Ubuntu 16.04): Linux Ubuntu 18.04
- TensorFlow installed from (source or
binary): source
- TensorFlow version (use command below): 2.1.0
- Python version: 3.6
- Keras Version: 2.3.1

When i fit the model, it shows me this error:
`      Traceback (most recent call last):
  File "/home/castilho/PycharmProjects/Chargrid/Chargrid/main.py", line 201, in <module>
    target_path=target_path, prefix=prefix_splits, make_new_representation=False, train=True)
  File "/home/castilho/PycharmProjects/Chargrid/Chargrid/main.py", line 117, in main
    nn.train(representations_path=representations_path, target_path=target_path, training_filenames = data['train_imgs'], validation_filenames=data['val_imgs'])
  File "/home/castilho/PycharmProjects/Chargrid/Chargrid/neural_network.py", line 150, in train
    validation_steps=int(len(validation_filenames) // batch_size))
  File "/home/castilho/PycharmProjects/Chargrid/venv/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training.py", line 819, in fit
    use_multiprocessing=use_multiprocessing)
  File "/home/castilho/PycharmProjects/Chargrid/venv/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training_v2.py", line 235, in fit
    use_multiprocessing=use_multiprocessing)
  File "/home/castilho/PycharmProjects/Chargrid/venv/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training_v2.py", line 533, in _process_training_inputs
    adapter_cls = data_adapter.select_data_adapter(x, y)
  File "/home/castilho/PycharmProjects/Chargrid/venv/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/data_adapter.py", line 998, in select_data_adapter
    _type_name(x), _type_name(y)))
ValueError: Failed to find data adapter that can handle input: <class 'Chargrid.dataset_generator.RepresentationGenerator'>, <class 'NoneType'>

Process finished with exit code 1`

I think this a bug in Keras. Below, is a part of the code when i fit the model.
`       def train(self, representations_path: str, target_path: str, training_filenames: list, validation_filenames: list,
              batch_size: int = 7):
        
        train_generator = RepresentationGenerator(representation_path=representations_path, target_path=target_path,
                                                  filenames=training_filenames, batch_size=batch_size)
        val_generator = RepresentationGenerator(representation_path=representations_path, target_path=target_path,
                                                filenames=validation_filenames, batch_size=batch_size)
        self.model_semantic.fit(x=train_generator, batch_size=7,
                                steps_per_epoch=int(len(training_filenames) // batch_size),
                                epochs=10,
                                verbose=1,
                                validation_data=val_generator,
                                validation_steps=int(len(validation_filenames) // batch_size))
        return 0`

My class RepresentationGenerator is:

`from tensorflow_core.python.keras.utils.data_utils import Sequence

class RepresentationGenerator(Sequence):

    def __init__(self, representation_path, target_path, filenames, batch_size):
        self.filenames = np.array(filenames)
        self.batch_size = batch_size
        self.representation_path = representation_path
        self.target_path = target_path

    def __len__(self):
        return (np.ceil(len(self.filenames) / float(self.batch_size))).astype(np.int)

    def __getitem__(self, idx):
        files_to_batch = self.filenames[idx * self.batch_size: (idx + 1) * self.batch_size]
        batch_x, batch_y = [], []
        for file in files_to_batch:
            batch_x.append(np.load(self.representation_path + file + ".npy", allow_pickle=True))
            batch_y.append(np.load(self.target_path + file + ".npy", allow_pickle=True))

        return np.array(batch_x), np.array(batch_y)
`

When i fit the model with a generator, the variable Y assume as None and it shows the error above. How can i fix that?

**System information**  
- Have I written custom code (as opposed to using example directory):  Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):  Linux Ubuntu 18.04
- TensorFlow backend (yes / no):  Yes
- TensorFlow version:  2.1.0
- Keras version:  2.3.1
- Python version:  3.6
- GPU model and memory:  NVIDIA Corporation GP108M [GeForce MX250]

**Comment by ravikyram** [comment]
@castilho25 
Looks like code is incomplete. Request you to share colab link or simple standalone code to reproduce the issue in our environment. It helps in localizing the issue faster. Thanks!

**Comment by ravikyram** [comment]
@castilho25 

Any update on this issue please. Thanks!

**Comment by castilho25** [comment]
The problem was resolved.

I imported Sequence from
``from tensorflow_core.python.keras.utils.data_utils import Sequence`

and the Sequence class should be imported from
''from tensorflow.keras.utils import Sequence'

**Comment by stefan-falk** [comment]
@ravikyram I am having the same error with this code:

```python
import tensorflow as tf
from keras_preprocessing.sequence import pad_sequences
from tensorflow_core.python.keras import Input
from tensorflow_core.python.keras.layers import Flatten, Dense, Embedding, Conv2D, MaxPooling2D
import numpy as np
from tensorflow_core.python.keras.models import Model

EOS = 10


def train_generator(nb_samples):

    def train_generator_():

        count = 0
        for _ in range(nb_samples):
            count += 1
            nb_select = np.random.randint(2, 11)
            x = np.random.rand(nb_select)
            y = np.asarray(sorted(x))
            yield x, y

    return train_generator_


def main():
    max_input_length = 20
    vocab_size = 11
    embedding_size = 16

    inputs = Input(shape=(max_input_length, ))
    input_layer = Embedding(vocab_size, embedding_size, input_length=max_input_length)(inputs)
    input_layer = tf.expand_dims(input_layer, axis=-1)
    x = input_layer

    x = Conv2D(1, 1, strides=(2, 1))(x)
    x = MaxPooling2D(pool_size=2, strides=(2, 1))(x)
    x = Conv2D(1, 1, strides=(2, 1))(x)
    x = MaxPooling2D(pool_size=2, strides=(2, 1))(x)
    x = Flatten()(x)
    output = Dense(vocab_size, activation='softmax')(x)

    model = Model(inputs=[inputs], outputs=[output])
    model.compile(optimizer='adam', loss=['binary_crossentropy'])

    model.fit(train_generator(1000), batch_size=10, epochs=10)

    batch = pad_sequences([[0.3, 0.2, 0.1]], max_input_length, padding='post', value=0)
    preds = model.predict(batch)

    print(preds)
    print('All done.')


if __name__ == '__main__':
    main()
```

Shouldn't this work like this or am I misinterpreting the docs?
