### ISSUE TITLE
decode_wav_op.cc:55 : Invalid argument: Bad file size for WAV: Expected 16 or 18, but got 40

### ISSUE THREAD

**Issue by skeydan** [tensorflow/tensorflow#36823]
**System information** 

- Have I written custom code (as opposed to using a stock
example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Fedora 31
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
 - TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.1
- Python version: 3.7
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

**Describe the current behavior**

```
import tensorflow as tf

# from https://github.com/Athospd/wavesurfer/blob/master/data-raw/Glaucidium-minutissimum-22180.wav
file = tf.io.read_file("/tmp/Glaucidium-minutissimum-22180.wav")
tf.audio.decode_wav(file)
```

error:

```
2020-02-17 14:20:35.070542: W tensorflow/core/framework/op_kernel.cc:1675] OP_REQUIRES failed at decode_wav_op.cc:55 : Invalid argument: Bad file size for WAV: Expected 16 or 18, but got40
```

**Describe the expected behavior**

No error

**Code to reproduce the issue** 

See above.

**Other info / logs**

File is played without problems by e.g. `sox`.

File info:

```
Input File     : 'Glaucidium-minutissimum-22180.wav'
Channels       : 1
Sample Rate    : 16000
Precision      : 16-bit
Duration       : 00:00:46.29 = 740624 samples ~ 3471.68 CDDA sectors
File Size      : 1.48M
Bit Rate       : 256k
Sample Encoding: 16-bit Signed Integer PCM
```

Also, the number of samples dòes not seem to be the problem, as after a simple resampling 

```
sox Glaucidium-minutissimum-22180.wav -r 16000 o5.wav
```

the new output is decoded without error.

Source location is

https://github.com/tensorflow/tensorflow/blob/e4c9dedb31df127aa6f52050f70f0084fd3e4c93/tensorflow/core/lib/wav/wav_io.cc#L238

but it is not clear to me what exactly is going on, so it would be great if this could be investigated. Thanks!

**Comment by foxik** [comment]
The file is not a regular WAVE_FORMAT_PCM (this is currently the only one supported by TF), but instead an instance of WAVE_FORMAT_EXTENSIBLE https://docs.microsoft.com/en-us/windows/win32/api/mmreg/ns-mmreg-waveformatextensible ; see bytes 21 and 22 which contain `0xFFFE` instead of `0x0001`. Therefore, TensorFlow cannot handle it (but yes, the error message is suboptimal).

**Comment by skeydan** [comment]
Many thanks for clarifying!
