### ISSUE TITLE
Build from Source Failure (Ubuntu 18.04 CUDA/cuDNN 10.1/7.6.5 Py 3.6 no AVX)

### ISSUE THREAD

**Issue by Mazecreator** [tensorflow/tensorflow#36828]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
Ubuntu 18.04
- TensorFlow installed from (source or binary):
Source
- TensorFlow version:
GPU 2.1
- Python version:
3.6
- Installed using virtualenv? pip? conda?:
NA - PIP3
- Bazel version (if compiling from source):
0.29.1
- GCC/Compiler version (if compiling from source):
7.4.0
- CUDA/cuDNN version:
10.1/7.6.5
- GPU model and memory:
GTX 1080 / 8GB

**Describe the problem**
The build process fails with:
ERROR: /home/greg/tensorflow/tensorflow/core/kernels/BUILD:4843:1: output 'tensorflow/core/kernels/_objs/depth_space_ops_gpu/depthtospace_op_gpu.cu.pic.o' was not created
ERROR: /home/greg/tensorflow/tensorflow/core/kernels/BUILD:4843:1: not all outputs were created or valid
Target //tensorflow/tools/pip_package:build_pip_package failed to build
ERROR: /home/greg/tensorflow/tensorflow/python/tools/BUILD:311:1 not all outputs were created or valid
INFO: Elapsed time: 248.378s, Critical Path: 97.82s
INFO: 853 processes: 853 local.
FAILED: Build did NOT complete successfully

**Provide the exact sequence of commands / steps that you executed before running into the problem**
I have tried both of the following with similar results:
bazel build --config=cuda //tensorflow/tools/pip_package:build_pip_package
bazel build  //tensorflow/tools/pip_package:build_pip_package

**Any other info / logs**
No other errors show in logs, can upload more of a snippet if needed, but no other reference to 'depthtospace_op_gpu.cu.pic' found leading to the failure for any hints.

I tried running the docker install as we from the install page, trying to avoid all the setup:
https://www.tensorflow.org/install/source

I got this error from the docker system on the 2nd docker command:
docker run --runtime=nvidia -it -w /tensorflow -v $PWD:/mnt -e HOST_PERMS="$(id -u):$(id -g)" tensorflow/tensorflow:devel-gpu-py3 bash
docker: Error response from daemon: Unknown runtime specified nvidia.
See 'docker run --help'.

I have build TensorFlow from source in the past, build 2.0b6 (no GPU) shortly after it was released and have no problems with GPU compiling of TensorFlow 1.X versions.  I have an old server without AVX support so I can't use the pre-compiled PIPs and haven't found one for my configuration with 2.1 yet.

Thanks.

**Comment by Mazecreator** [comment]
I saw reference to Bazel 0.27 for TF 2.1 so loaded 0.27.2 and got similar results:
ERROR: /home/greg/tensorflow/tensorflow/core/kernels/BUILD:1257:1: output 'tensorflow/core/kernels/_objs/snapshot_op_gpu/snapshot_op_gpu.cu.pic.o' was not created
ERROR: /home/greg/tensorflow/tensorflow/core/kernels/BUILD:1257:1: not all outputs were created or valid
Target //tensorflow/tools/pip_package:build_pip_package failed to build
INFO: Elapsed time: 2186.132s, Critical Path: 166.24s
INFO: 12252 processes: 12252 local.
FAILED: Build did NOT complete successfully

I have enclosed most of the output.

[bazel0.27.2.txt](https://github.com/tensorflow/tensorflow/files/4219534/bazel0.27.2.txt)

**Comment by saikumarchalla** [comment]
@Mazecreator Please look into [this](https://github.com/tensorflow/tensorflow/issues/31926#issuecomment-527584855) and let  me know if  it helps you. Thanks!

**Comment by Mazecreator** [comment]
Thanks @saikumarchalla , I got the docker nvidia toolkit installed and the code is in the process of compiling.  I will let you know if this build passes/fails.  Also, the instructions on the install webpage didn't seem right, I had to change the command-line to get it to run the container and did a pull request with the change:
https://github.com/tensorflow/docs/pull/1469

**Comment by Mazecreator** [comment]
@saikumarchalla ,

Wow, the Docker solution was much easier once I got the Nvidia part installed!  Everything is working fine, no need to figure out the failure of compiling from source as this probably indicates some decency/compiler was not the exact version on my Ubuntu box.

All compiled successfully and PIP package installed and functional on that system.  Thank for the help!

**Comment by saikumarchalla** [comment]
Closing this issue as it was resolved.

**Comment by surak** [comment]
I have this issue

**Comment by amahendrakar** [comment]
> I have this issue

@surak,
Could you please submit a new issue from [this link](https://github.com/tensorflow/tensorflow/issues/new/choose) and fill in the template, so that we can track the issue there. Thanks!
