### ISSUE TITLE
Memory leak using generators with tf.data.experimental.AUTOTUNE

### ISSUE THREAD

**Issue by plooney** [tensorflow/tensorflow#36821]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information** - Have I written custom code (as opposed to using a stock
example script provided in TensorFlow): - OS Platform and Distribution (e.g.,
Linux Ubuntu 16.04): - Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if
the issue happens on mobile device: - TensorFlow installed from (source or
binary): - TensorFlow version (use command below): - Python version: - Bazel
version (if compiling from source): - GCC/Compiler version (if compiling from
source): - CUDA/cuDNN version: - GPU model and memory:

Windows 10
Tensorflow 2.0
RTX 2060

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**

Read images from a generator using "num_parallel_calls=AUTOTUNE" is eating all memory

**Describe the expected behavior**

Don't use up all memory

**Code to reproduce the issue** Provide a reproducible test case that is the
bare minimum necessary to generate the problem.

```
def my_generator(data_dir):
    def my_func():
        paths = pathlib.Path(data_dir).rglob('*.png')
        for path in paths:
            yield str(path)
    return my_func

def process_path_test(file_path):
    """Read a tensorflow image from a png file and return the
    image and filepath for writing out during test time"""
    img_file = tf.io.read_file(file_path)
    img = tf.io.decode_png(img_file, channels=1, dtype=tf.uint16)
    return img, file_path

def some_func(img, file_path):
    return img, file_path

p_dir = '//Some_path_to_images'
AUTOTUNE = tf.data.experimental.AUTOTUNE
test_imgs = tf.data.Dataset.from_generator(my_generator(p_dir), tf.string).map(process_path_test)
test_imgs = test_imgs.map(some_func, num_parallel_calls=AUTOTUNE)
my_iter = iter(test_imgs)
next(my_iter)
```

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by saikumarchalla** [comment]
@plooney  Could you please share colab link or simple standalone code with supporting files to reproduce the issue in our environment,it helps us localizing the issue faster.

**Comment by plooney** [comment]
```
import tensorflow as tf
import os 
import png
import numpy as np
import pathlib

physical_devices = tf.config.experimental.list_physical_devices('GPU')
assert len(physical_devices) > 0, "Not enough GPU hardware devices available"
tf.config.experimental.set_memory_growth(physical_devices[0], True)

data_dir = 'pngs'
if not os.path.isdir(data_dir): os.makedirs(data_dir)

def write_png(image_array, out_name):
    """Write out PNG images with dimensions IMG_WIDTH, IMG_HEIGHT.                                       
    Expects an UInt16 image array and output filename."""                                                
    with open(out_name, 'wb') as png_file:
        writer = png.Writer(256, 256, greyscale=True, bitdepth=16)                          
        writer.write(png_file, image_array[:, :])
        

def my_generator(data_dir):
    def my_func():
        paths = pathlib.Path(data_dir).rglob('*.png')
        for path in paths:
            if path.name.endswith('.png'):
                yield str(path)
    return my_func

def process_path_test(file_path):
    """Read a tensorflow image from a png file and return the
    image and filepath for writing out during test time"""
    img_file = tf.io.read_file(file_path)
    img = tf.io.decode_png(img_file, channels=1, dtype=tf.uint16)
    return img, file_path

def some_func(image, file_path):
    image = tf.image.resize(image, size = (256,256))
    image = tf.clip_by_value(image,-0.9999,0.9999)
    image = tf.math.atanh(image)
    #image = (ww/2)*image + wc
    image = image/3000
    return image, file_path

for i in range(0,1000):
    arr = (2**16 -1)*np.random.random([256,256])
    arr = arr.astype(np.uint16)
    write_png(arr, 'pngs/my_png_{}.png'.format(str(i)))

AUTOTUNE = tf.data.experimental.AUTOTUNE
test_imgs = tf.data.Dataset.from_generator(my_generator(data_dir), tf.string).map(process_path_test)
test_imgs = test_imgs.map(some_func, num_parallel_calls=AUTOTUNE).batch(1)
my_iter = iter(test_imgs)
next(my_iter)
```

**Comment by gowthamkpr** [comment]
@plooney What data are you using here. Please provide us the data and related colab notebook to reproduce this issue. Thanks!

**Comment by plooney** [comment]
@ gowthamkpr I have posted is a self contained example that reproduces the problem while generating dummy data. If you run it in jupyter it will demonstrate the memory leak.

**Comment by zaccharieramzi** [comment]
@plooney on colab I couldn't reproduce the issue, see [here](https://colab.research.google.com/drive/1RtZ8dvRZTA33Kl4kwt0ao_2pzx0hNpe8).

I was just monitoring the RAM use by eye.

Also one thing, why do you check for GPU use in this case ?

**Comment by plooney** [comment]
It was a workaround for using an RTX 2060 GPU that I needed. I consistently have the issue on my architecture.

**Comment by tilakrayal** [comment]
@plooney ,
I was able to run the code without any issues on TF v2.7.Please find the gist of it [here](
https://colab.research.google.com/gist/tilakrayal/d240e98d5ebe0e45101921d4b42df3ac/untitled142.ipynb).
