### ISSUE TITLE
Tensorflow Lite Build Problem - Specialization for Eigen::internal::scalar_logistic_op<float> Removed

### ISSUE THREAD

**Issue by dtsmith2001** [tensorflow/tensorflow#36837]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Lunux Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): source, branch r2.1
- TensorFlow version: 2.1.0
- Python version: 3.6
- Installed using virtualenv? pip? conda?: No
- Bazel version (if compiling from source): ./tensorflow/tools/ci_build/install/install_bazel.sh
- GCC/Compiler version (if compiling from source): arm-linux-gnueabihf-gcc (Ubuntu/Linaro 7.4.0-1ubuntu1~18.04.1) 7.4.0
- CUDA/cuDNN version:
- GPU model and memory:

**Describe the problem**

Cross-compiling Tensorflow Lite for Raspberry PI following published instructions.

Multiple failures to find `Eigen::internal::scalar_logistic_op`:

```In file included from tensorflow/lite/kernels/activations.cc:28:0:
./tensorflow/lite/kernels/internal/optimized/optimized_ops.h: In function 'void tflite::optimized_ops::LstmCell(const tflite::LstmCellParams&, const tflite::RuntimeShape&, const float*, const tflite::RuntimeShape&, const float*, const tflite::RuntimeShape&, const float*, const tflite::RuntimeShape&, const float*, const tflite::RuntimeShape&, const float*, const tflite::RuntimeShape&, float*, const tflite::RuntimeShape&, float*, const tflite::RuntimeShape&, float*, const tflite::RuntimeShape&, float*, tflite::CpuBackendContext*)':
./tensorflow/lite/kernels/internal/optimized/optimized_ops.h:2938:48: error: 'scalar_logistic_op' is not a member of 'Eigen::internal'
       input_gate_sm.unaryExpr(Eigen::internal::scalar_logistic_op<float>()) *
                                                ^~~~~~~~~~~~~~~~~~
```

**Provide the exact sequence of commands / steps that you executed before running into the problem**

```
git clone git@github.com:tensorflow/tensorflow.git
cd tensorflow && git checkout r2.1
./tensorflow/tools/ci_build/install/install_bazel.sh
./tensorflow/lite/tools/make/download_dependencies.sh
./tensorflow/lite/tools/make/build_rpi_lib.sh
```

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

Eigen has moved to GitLab. The release for 2.1.0 has an error in `download_dependencies.sh` - the BitBucket repository URL is not found since `curl` is called with `-s`. I cloned the repository and found this using `git log`:

```
commit 0f288e2ae6d343a978c4d5f6a951e20d7b69d96e
Author: Rasmus Munk Larsen <rmlarsen@google.com>
Date:   Mon Dec 2 17:00:58 2019 -0800

    Revert the specialization for scalar_logistic_op<float> introduced in:
    
    https://bitbucket.org/eigen/eigen/commits/5ce45e1849c9c8352266830f6f8e628f26b99a9a
    
    While providing a 50% speedup on Haswell+ processors, the large relative error outside [-18, 18] in this approximation causes problems, e.g., when computing gradients of activation functions like softplus in neural networks.
```

I tried other releases of Eigen with the same problem.

**Comment by dtsmith2001** [comment]
@gadagashwini how can I help?

**Comment by russellmcc** [comment]
To solve your immediate problem, the Tensorflow 2.1.0 release is pinned to Eigen sha 4e696901f873a2347f76d931cf2f701e31e15d05, so building with that will work.

I think it would be nice if the `download_dependencies.sh` script were fixed, though.

**Comment by dtsmith2001** [comment]
I did manage to fix the problem. I'll dig out the solution and see what I can do about submitting it.

I may just add a patch to this issue. Advice welcome.

**Comment by dtsmith2001** [comment]
[fix-eigen-archive-download-path.zip](https://github.com/tensorflow/tensorflow/files/4250361/fix-eigen-archive-download-path.zip)

I patched `download_dependencies.sh` locally and use that in our build process.

**Comment by sanatmpa1** [comment]
@dtsmith2001,

As you have managed to fix the problem. Would you mind submitting a PR for the same?
