### ISSUE TITLE
graph_transforms not found when running export_tflite_ssd_graph.py to convert ssd model

### ISSUE THREAD

**Issue by melloelout** [tensorflow/tensorflow#36835]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- TensorFlow installed from (source or binary): binary
- TensorFlow version (or github SHA if from source): 2.1.0

**Command used to run the converter or code if you’re using the Python API**
From issue #31015 I'm trying to run:

python ../models/research/object_detection/export_tflite_ssd_graph.py --pipeline_config_path pipeline.config --trained_checkpoint_prefix model.ckpt --output_directory my_frozen_graph --add_postprocessing_op True

The output is as follows:

Traceback (most recent call last):
  File "../models/research/object_detection/export_tflite_ssd_graph.py", line 96, in <module>
    from object_detection import export_tflite_ssd_graph_lib
  File "/home/mello/venv36/lib/python3.6/site-packages/object_detection/export_tflite_ssd_graph_lib.py", line 26, in <module>
    from tensorflow.tools.graph_transforms import TransformGraph
ModuleNotFoundError: No module named 'tensorflow.tools.graph_transforms'

The section in export_tflite_ssd_graph_lib.py where the error occurs:

import tensorflow as tf
from tensorflow.core.framework import attr_value_pb2
from tensorflow.core.framework import types_pb2
from tensorflow.core.protobuf import saver_pb2
from tensorflow.tools.graph_transforms import TransformGraph

I have tried binary install of tensorflow, both on ubuntu and on raspbian buster, have tried it with python 3.7 and 3.6, virtualenv or without.
Also have tried with tensorflow compiled using bazel.

Regardless, I alwas get that tensorflow.tools.graph_transforms are missing.

Model I'm using is ssd_mobilenet_v2_coco_2018_03_29

I don't believe it has the to do with the model, but probably with the tensorflow install (but not at all sure...)

Thanks for your help!

**Comment by melloelout** [comment]
It looks like:

from tensorflow.tools.graph_transforms import TransformGraph

works for tensorflow 1.15, but not for 2.0 or 2.1.

Is it possible to have this be part of the tensorflow 2.1 binary?

**Comment by ymodak** [comment]
You have to [build graph transform tool](https://github.com/tensorflow/tensorflow/issues/33352#issuecomment-556245567) for TF 2.X 
See https://github.com/tensorflow/tensorflow/issues/33352#issuecomment-556245567 to know more
