### ISSUE TITLE
DockerHub tag 2.1.0-py3 includes GPU support

### ISSUE THREAD

**Issue by deliahu** [tensorflow/tensorflow#36841]
**System information**

DockerHub: [tensorflow/tensorflow:2.1.0-py3](https://hub.docker.com/layers/tensorflow/tensorflow/2.1.0-py3/images/sha256-14ec674cefd622aa9d45f07485500da254acaf8adfef80bd0f279db03c735689?context=explore)

**Describe the problem**

This Docker image seems to have the pip `tensorflow` package installed, rather than the `tensorflow-cpu` package. As of version 2.1.0, the `tensorflow` package includes GPU support (see the first bullet point in the [changelog](https://github.com/tensorflow/tensorflow/releases/tag/v2.1.0)).

Since [tensorflow/tensorflow:2.1.0-gpu-py3](https://hub.docker.com/layers/tensorflow/tensorflow/2.1.0-gpu-py3/images/sha256-1010e051dde4a9b62532a80f4a9a619013eafc78491542d5ef5da796cc2697ae?context=explore) is also provided, it seems to me like [tensorflow/tensorflow:2.1.0-py3](https://hub.docker.com/layers/tensorflow/tensorflow/2.1.0-py3/images/sha256-14ec674cefd622aa9d45f07485500da254acaf8adfef80bd0f279db03c735689?context=explore) should not include GPU support. If you believe that it should, would it be possible to publish e.g. tensorflow/tensorflow:2.1.0-cpu-py3 to DockerHub?

**Additional context**

The reason I noticed this is because I started seeing these warnings when running on CPU: 

```
W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer.so.6'; dlerror: libnvinfer.so.6: cannot open shared object file: No such file or directory
W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer_plugin.so.6'; dlerror: libnvinfer_plugin.so.6: cannot open shared object file: No such file or directory
W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:30] Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
```

In addition to removing these warnings, having a cpu-only version would reduce the image size.

**Comment by deliahu** [comment]
@angerson @ravikyram I was just wondering if you had any updates regarding this, or an estimate for when it might be addressed

**Comment by angerson** [comment]
Thanks for the report. I can see why this is confusing, although (unless I'm mistaken) there are no actual errors, just warnings. It would be nice to use `tensorflow-cpu` instead, since it would improve the image size slightly, but I'm afraid I don't have the time to work on the cleanup right now because it's not a breakage.

You're welcome to update our Dockerfiles, however, and I'd be happy to review a PR to adjust which package gets installed. See [here](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/tools/dockerfiles) for instructions (and https://github.com/tensorflow/tensorflow/pull/36971 for a notable upcoming PR).

**Comment by deliahu** [comment]
@angerson thanks for your response.

Since it it seems to me like it would make sense to not include the GPU dependencies (since there is a `-gpu` set of images and also since that was the behavior prior to v2.1), do you think it would make sense to update [this line](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/dockerfiles/dockerfiles/cpu.Dockerfile#L55) to `ARG TF_PACKAGE=tensorflow-cpu`? My concern is that if this arg is not overwritten, and `TF_PACKAGE_VERSION` < 2.1, then the `pip install` will fail ([pypi](https://pypi.org/project/tensorflow-cpu/#history) only seems to have v1.15 and v2.1).

Alternatively, is it possible to update the script that generates the Dockerfiles to pass in `TF_PACKAGE=tensorflow-cpu` for versions >= 2.1?

**Comment by kumariko** [comment]
@deliahu Could you please let us know if you still need help on this ? We recommend that you upgrade to 2.6 which is latest stable version of TF and let us know if the issue still persists in newer versions. If it is resolved then please feel free to move this issue to close status ? Thanks!

**Comment by deliahu** [comment]
I no longer use this image, but after taking a quick look at the command and size of layer 10 in [tensorflow/tensorflow:2.6.0](https://hub.docker.com/layers/tensorflow/tensorflow/2.6.0/images/sha256-773d5ce09e4ce003db02740c6a372a8a9f43be2bac23544d8f452bfec5347c53?context=explore), yes, I do believe this has been resolved :+1:
