### ISSUE TITLE
TypeError: Tensor is unhashable if Tensor equality is enabled. Instead, use tensor.experimental_ref() as the key. in colab

### ISSUE THREAD

**Issue by neenaloysius** [tensorflow/tensorflow#36851]
When tryig to build the following model, I get error Tensor is unhashable (see figure)
input_data = Input(name='the_input', shape=(208, 224,224, 3), dtype=dtype)
 layer1 =        TimeDistributed(
            MobileNet(weights='imagenet',include_top=False))(input_data)
    
layer2 =  TimeDistributed(GlobalAveragePooling2D())(layer1)
##********************************* Create Bidirectional LSTM*************************************
for i in range(0, n_layers):
     x = Bidirectional(CuDNNLSTM(20, kernel_initializer=kernel_init_rnn, bias_initializer=bias_init_rnn,
                                        unit_forget_bias=True, return_sequences=True),
                              merge_mode='sum', name='CuDNN_bi_lstm'+str(i+1))(layer2)

x = TimeDistributed(Dense(units=20, kernel_initializer=kernel_init_dense, bias_initializer=bias_init_dense,
                              activation='relu'), name='fc_4')(x)
x = TimeDistributed(Dropout(dropout), name='dropout_4')(x)
    # Output layer with softmax
y_pred = TimeDistributed(Dense(units=30, kernel_initializer=kernel_init_dense,
                                   bias_initializer=bias_init_dense, activation='softmax'), name='softmax')(x)
Model(inputs=input_data, outputs=y_pred).summary()
![colab issue](https://user-images.githubusercontent.com/17008416/74722702-63ebf400-525f-11ea-804d-283b4016d6fe.JPG)

**Comment by gadagashwini** [comment]
@neenaloysius, Can you please provide complete code to reproduce the reported issue. Also provide the Tensorflow version. Thanks!

**Comment by neenaloysius** [comment]
#%tensorflow_version 2.x
import tensorflow as tf
from tensorflow.python.keras import Sequential
from tensorflow.python.keras.layers import LSTM, Bidirectional,Lambda
from tensorflow.python.keras.layers import Dense, TimeDistributed,Input,CuDNNLSTM
from tensorflow.python.keras.layers import Dropout, GlobalAveragePooling2D
from tensorflow.python.keras import optimizers
from tensorflow.keras.applications.mobilenet import MobileNet
from tensorflow.python.keras import backend as K
from keras.models import Model

# Input data type
dtype = 'float32'
n_layers=1
dropout=0.2
# Kernel and bias initializers for recurrent layer
kernel_init_rnn = 'glorot_uniform'
bias_init_rnn = 'random_normal'
# Kernel and bias initializers for fully connected dense layer
kernel_init_dense = 'random_normal'
bias_init_dense = 'random_normal'

# Kernel and bias initializers for convolution layers
kernel_init_conv = 'glorot_uniform'
bias_init_conv = 'random_normal'

##********************************* Create 3DCNN*************************************
## input layer
sample_shape = (208, 224,224, 3)

input_data = Input(name='the_input', shape=(208, 224,224, 3), dtype=dtype)
 
layer1 =        TimeDistributed(
            MobileNet(weights='imagenet',include_top=False))(input_data)
    
layer2 =  TimeDistributed(GlobalAveragePooling2D())(layer1)
##********************************* Create Bidirectional LSTM*************************************
for i in range(0, n_layers):
     x = Bidirectional(CuDNNLSTM(20, kernel_initializer=kernel_init_rnn, bias_initializer=bias_init_rnn,
                                        unit_forget_bias=True, return_sequences=True),
                              merge_mode='sum', name='CuDNN_bi_lstm'+str(i+1))(layer2)
 # 1 fully connected layer DNN ReLu with default 20% dropout
x = TimeDistributed(Dense(units=20, kernel_initializer=kernel_init_dense, bias_initializer=bias_init_dense,
                              activation='relu'), name='fc_4')(x)
x = TimeDistributed(Dropout(dropout), name='dropout_4')(x)

    # Output layer with softmax
y_pred = TimeDistributed(Dense(units=30, kernel_initializer=kernel_init_dense,
                                   bias_initializer=bias_init_dense, activation='softmax'), name='softmax')(x)

Model(inputs=input_data, outputs=y_pred).summary()

**Comment by gadagashwini** [comment]
Was able to replicate the issue with Tf 2.1.
Please find the gist [here](https://colab.sandbox.google.com/gist/gadagashwini/81dc9ecd6c0756e951d7f0e3ddc72d88/untitled396.ipynb). Thanks!

**Comment by razzOn2calculus** [comment]
Problem solved, it was mistake on importing libraries when using tensorflow 2.x , 
I was having error  **TypeError: Tensor is unhashable if Tensor equality is enabled. Instead, use tensor.experimental_ref() as the key.**

solution was:
using
`from tensorflow.keras.models import Model`
Instead of 
`from keras.models import Model
`

**Comment by razzOn2calculus** [comment]
Problem solved. In my case it was mistake on importing libraries when using tensorflow 2.x ,
I was having error

>  TypeError: Tensor is unhashable if Tensor equality is enabled. Instead, use tensor.experimental_ref() as the key.

solution was:
using
`from tensorflow.keras.models import Model
`Instead of
`from keras.models import Model`

**Comment by SudilHasitha** [comment]
from keras.applications.vgg16 import VGG16
from keras.applications.vgg16 import preprocess_input, decode_predictions
import numpy as np
import shap
import keras.backend as K
import json

# load pre-trained model and choose two images to explain
model2 = VGG16(weights='imagenet', include_top=True)
X,y = shap.datasets.imagenet50()
to_explain = X[[39,41]]

# load the ImageNet class names
url = "https://s3.amazonaws.com/deep-learning-models/image-models/imagenet_class_index.json"
fname = shap.datasets.cache(url)
with open(fname) as f:
    class_names = json.load(f)

# explain how the input to the 7th layer of the model explains the top two classes
def map2layer(x, layer):
    feed_dict = dict(zip([model2.layers[0].input], [preprocess_input(x.copy())]))
    return K.get_session().run(model2.layers[layer].input, feed_dict)
e = shap.GradientExplainer((model2.layers[7].input, model2.layers[-1].output), map2layer(preprocess_input(X.copy()), 7))
shap_values,indexes = e.shap_values(map2layer(to_explain, 7), ranked_outputs=2)

# get the names for the classes
index_names = np.vectorize(lambda x: class_names[str(x)][1])(indexes)

# plot the explanations
shap.image_plot(shap_values, to_explain, index_names)


![image](https://user-images.githubusercontent.com/39588932/120801799-45e2f980-c55f-11eb-89da-3c80f657ad48.png)

**Comment by anshky** [comment]
_

> I'm facing the same error, I resolved the error by importing these commands -

_ 

**import tensorflow.compat.v1.keras.backend as K
import tensorflow as tf
tf.compat.v1.disable_eager_execution()**

**Comment by anshky** [comment]
> from keras.applications.vgg16 import VGG16
> from keras.applications.vgg16 import preprocess_input, decode_predictions
> import numpy as np
> import shap
> import keras.backend as K
> import json
> 
> # load pre-trained model and choose two images to explain
> model2 = VGG16(weights='imagenet', include_top=True)
> X,y = shap.datasets.imagenet50()
> to_explain = X[[39,41]]
> 
> # load the ImageNet class names
> url = "https://s3.amazonaws.com/deep-learning-models/image-models/imagenet_class_index.json"
> fname = shap.datasets.cache(url)
> with open(fname) as f:
> class_names = json.load(f)
> 
> # explain how the input to the 7th layer of the model explains the top two classes
> def map2layer(x, layer):
> feed_dict = dict(zip([model2.layers[0].input], [preprocess_input(x.copy())]))
> return K.get_session().run(model2.layers[layer].input, feed_dict)
> e = shap.GradientExplainer((model2.layers[7].input, model2.layers[-1].output), map2layer(preprocess_input(X.copy()), 7))
> shap_values,indexes = e.shap_values(map2layer(to_explain, 7), ranked_outputs=2)
> 
> # get the names for the classes
> index_names = np.vectorize(lambda x: class_names[str(x)][1])(indexes)
> 
> # plot the explanations
> shap.image_plot(shap_values, to_explain, index_names)
> 
> ![image](https://user-images.githubusercontent.com/39588932/120801799-45e2f980-c55f-11eb-89da-3c80f657ad48.png)

It will work by this - 
```
import tensorflow.compat.v1.keras.backend as K
import tensorflow as tf
tf.compat.v1.disable_eager_execution()
```
