### ISSUE TITLE
Key error message doesn't print the new line in Estimator

### ISSUE THREAD

**Issue by pingsutw** [tensorflow/tensorflow#36857]
output in the concole:
```
KeyError: "The dictionary passed into features does not have the expected inputs keys defined in 
the keras model.\n\tExpected keys: {'input_1', 'input_2'}\n\tfeatures keys: {'feat_ids', 
'feat_vals'}\n\tDifference: {'input_1', 'feat_ids', 'feat_vals', 'input_2'}"
```
The link to the code snippet:
https://github.com/tensorflow/estimator/blob/6915557cef8bfc86f29f87e4467d601e4553b957/tensorflow_estimator/python/estimator/keras.py#L119-L129

The key error message doesn't print the new line, we should update it.
It's related to https://stackoverflow.com/questions/46892261/new-line-on-error-message-in-keyerror-python-3-3

**Comment by ravikyram** [comment]
@pingsutw 
Can you please let us know which TensorFlow version you are using?.Please, share the colab link or simple standalone code to reproduce the issue in our environment. It helps in localizing the issue faster. Thanks!

**Comment by pingsutw** [comment]
@ravikyram thanks for the reply
here is my colab [link] (https://colab.research.google.com/drive/1B_0Vbnk3EkNFfkKkmZK9gG8NbKxUqHxP) to reproduce problem
Actually it's keyErorr Exception bug, they don't support `\n` in the error message
you can see this [link](https://stackoverflow.com/questions/46892261/new-line-on-error-message-in-keyerror-python-3-3) for reference

**Comment by ashutosh1919** [comment]
@omalleyt12 , Please review PR [#51](https://github.com/tensorflow/estimator/pull/51) for this issue. Check if it is useful.
