### ISSUE TITLE
Unable to generate signed APK for project based on Android demo

### ISSUE THREAD

**Issue by cardshuffle** [tensorflow/tensorflow#3685]
I wrote a simple app based on the Android demo that I got running successfully on my own device for debugging, using Bazel, and I'm planning on releasing it, but generating a signed APK fails.

### Environment info
Operating System: Ubuntu 14.04 LTS 64-bit

Installed version of CUDA and cuDNN: none

If installed from source, provide 
1. The commit hash (`git rev-parse HEAD`): fc9162975e52978d3af38549b570cc3cc5f0ab66
2. The output of `bazel version`
```
Build label: 0.3.0
Build target: bazel-out/local-fastbuild/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Fri Jun 10 11:38:23 2016 (1465558703)
Build timestamp: 1465558703
Build timestamp as int: 1465558703
```

### Steps to reproduce
1. Follow instructions in #3444 up to setting up the Android Studio project
2. Run `./studio.sh` to open Android Studio
3. Open the Android demo as existing Android Studio project
4. (no prompt to configure appears)
5. Open "File/Project Structure"
6. If src and res aren't set as source and resource directories respectively, do so
7. Select "Generate Signed APK" under Build, fails

### What have you tried?
1. Found the apks built by Bazel and tried to upload them. They were rejected by the Play Store.
2. Originally, the "Generate Signed APK" option wasn't available, but was fixed by deleting the project, reinstalling Android Studio, and then copying the project back in from a backup.
3. Cleaning. No change.
4. Solutions for similar errors suggest modifying the build tools version in the Gradle file, but this project doesn't use Gradle...

### Logs or other output
```
Error:Android Dex: [android] Exception in thread "main" java.lang.UnsupportedClassVersionError: com/android/dx/command/dexer/Main : Unsupported major.minor version 52.0
Error:Android Dex: [android] at java.lang.ClassLoader.defineClass1(Native Method)
Error:Android Dex: [android] at java.lang.ClassLoader.defineClass(ClassLoader.java:803)
Error:Android Dex: [android] at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
Error:Android Dex: [android] at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
Error:Android Dex: [android] at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
Error:Android Dex: [android] at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
Error:Android Dex: [android] at java.security.AccessController.doPrivileged(Native Method)
Error:Android Dex: [android] at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
Error:Android Dex: [android] at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
Error:Android Dex: [android] at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
Error:Android Dex: [android] at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
Error:Android Dex: [android] at org.jetbrains.android.compiler.tools.AndroidDxRunner.loadDex(AndroidDxRunner.java:79)
Error:Android Dex: [android] at org.jetbrains.android.compiler.tools.AndroidDxRunner.runDex(AndroidDxRunner.java:136)
Error:Android Dex: [android] at org.jetbrains.android.compiler.tools.AndroidDxRunner.main(AndroidDxRunner.java:336)
```

**Comment by girving** [comment]
@petewarden Do you know if this is an issue on our end?

**Comment by cardshuffle** [comment]
Update: I've found an alternate way to generate a signed APK using Bazel ([see here](https://github.com/bazelbuild/bazel/issues/1613)). I haven't figured out the issue in this thread though.

**Comment by andrewharp** [comment]
@cardshuffle Have you managed to solve the issue? If not, http://stackoverflow.com/questions/35990995/com-android-dx-command-main-unsupported-major-minor-version-52-0 looks related. Maybe try updating your sdk settings as suggested there?

**Comment by cardshuffle** [comment]
I tried out the suggested solution, but I wasn't able to find the Build Tools Version setting mentioned, and since the demo doesn't use Gradle, there isn't a Gradle settings file to change the version in.

**Comment by andrewharp** [comment]
@cardshuffle I have a build.gradle file incoming that may help with this -- it will automate calling out to Bazel to build the native libs and then copy them into the appropriate directory. You can try editing the buildToolsVersion there once I get it checked in.

**Comment by andrewharp** [comment]
@cardshuffle build.gradle commited in in bd73f2e3b88ddd6a89d5ee08f83e65a29fdba8df. Hopefully this makes thigs a bit easier.

**Comment by andrewharp** [comment]
Closing; please reopen or create a new issue if the build.gradle approach gives you any problems.
