### ISSUE TITLE
Tensorflow 2.0.0 - DLL load failed - windows cpu

### ISSUE THREAD

**Issue by tessy1234** [tensorflow/tensorflow#36860]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10 64 bit
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:  n/a
- TensorFlow installed from (source or binary): binary
- TensorFlow version: 2.0.0
- Python version: 3.7.6
- Installed using virtualenv? pip? conda?:  pip and conda
- Bazel version (if compiling from source): n/a
- GCC/Compiler version (if compiling from source):  n/a
- CUDA/cuDNN version:  n/a
- GPU model and memory:  n/a

**Describe the problem**

Installation of TensorFlow 2.0.0 using pip was successful, but TensorFlow import failed.
On the contrary, installation of TensorFlow 2.0.0 using conda was successful and in addition TensorFlow import was successful.
**Why does conda env work fine but pip env don't?**

**Provide the exact sequence of commands / steps that you executed before running into the problem**
I created 2 conda environments: one for conda release and the other for pip release, both dedicated to tensorflow 2.0.0. 

1. tensorflow2_0_conda environment:
conda installation using
`conda install python=3.7 tensorflow=2.0`

2. tensorflow2_0_pip environment:
pip installation using
`conda install python=3.7`
`pip install tensorflow==2.0.0`

Both installations completed without any error.

Import test:
`python -c "import tensorflow as tf"`

ad 1) conda env works fine
ad 2) pip env failed with error message (detail see logs entry)
`ImportError: DLL load failed ...`

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

```
(tensorflow2_0_pip)>python -c "import tensorflow as tf"
Traceback (most recent call last):
  File "C:\Anaconda3\envs\tensorflow2_0_pip\lib\site-packages\tensorflow_core\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Anaconda3\envs\tensorflow2_0_pip\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Anaconda3\envs\tensorflow2_0_pip\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Anaconda3\envs\tensorflow2_0_pip\lib\imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Anaconda3\envs\tensorflow2_0_pip\lib\imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: A dynamic link library (DLL) initialization routine failed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Anaconda3\envs\tensorflow2_0_pip\lib\site-packages\tensorflow\__init__.py", line 98, in <module>
    from tensorflow_core import *
  File "C:\Anaconda3\envs\tensorflow2_0_pip\lib\site-packages\tensorflow_core\__init__.py", line 40, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "C:\Anaconda3\envs\tensorflow2_0_pip\lib\site-packages\tensorflow\__init__.py", line 50, in __getattr__
    module = self._load()
  File "C:\Anaconda3\envs\tensorflow2_0_pip\lib\site-packages\tensorflow\__init__.py", line 44, in _load
    module = _importlib.import_module(self.__name__)
  File "C:\Anaconda3\envs\tensorflow2_0_pip\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Anaconda3\envs\tensorflow2_0_pip\lib\site-packages\tensorflow_core\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Anaconda3\envs\tensorflow2_0_pip\lib\site-packages\tensorflow_core\python\pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "C:\Anaconda3\envs\tensorflow2_0_pip\lib\site-packages\tensorflow_core\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Anaconda3\envs\tensorflow2_0_pip\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Anaconda3\envs\tensorflow2_0_pip\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Anaconda3\envs\tensorflow2_0_pip\lib\imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Anaconda3\envs\tensorflow2_0_pip\lib\imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: A dynamic link library (DLL) initialization routine failed.


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

(tensorflow2_0_pip)>
```

**Comment by av8ramit** [comment]
Any chance this comment helps:

https://github.com/tensorflow/tensorflow/issues/36167#issuecomment-577886156

**Comment by ravikyram** [comment]
@tessy1234 

What is make/model of your cpu?
I suspect your cpu model does not support AVX instructions sets.See [hardware requirements](https://www.tensorflow.org/install/pip?lang=python3#hardware-requirements)
Make sure to download the [latest microsoft visual c++ redistributable from here](https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads).
.Also, please follow the instructions from to install from pip [Tensorflow website](https://www.tensorflow.org/install/pip).
Please, check Your CPU/Python is on 32 bits?Please, refer #36167 and see if it helps you. Thanks!

**Comment by tessy1234** [comment]
I am running Intel® Core™ i7-820QM Processor (8M Cache, 1.73 GHz).
Installed:

- Microsoft Visual C++ 2015-2019 Redistributable (x64) - 14.24.28127

- pip version 20.0.2

- Python 3.7.6 (default, Jan  8 2020, 20:23:39) [MSC v.1916 64 bit (AMD64)]

Open question: @av8ramit, @ravikyram
Is there a library that is in a different location/not installed on your system that cannot be loaded?

support: installed packages
conda list
```
# packages in environment at C:\Anaconda3\envs\tensorflow2_0_pip:
#
# Name                    Version                   Build  Channel
absl-py                   0.9.0                    pypi_0    pypi
astor                     0.8.1                    pypi_0    pypi
ca-certificates           2020.1.1                      0
cachetools                4.0.0                    pypi_0    pypi
certifi                   2019.11.28               py37_0
chardet                   3.0.4                    pypi_0    pypi
gast                      0.2.2                    pypi_0    pypi
google-auth               1.11.2                   pypi_0    pypi
google-auth-oauthlib      0.4.1                    pypi_0    pypi
google-pasta              0.1.8                    pypi_0    pypi
grpcio                    1.27.2                   pypi_0    pypi
h5py                      2.10.0                   pypi_0    pypi
idna                      2.8                      pypi_0    pypi
keras-applications        1.0.8                    pypi_0    pypi
keras-preprocessing       1.1.0                    pypi_0    pypi
markdown                  3.2.1                    pypi_0    pypi
numpy                     1.18.1                   pypi_0    pypi
oauthlib                  3.1.0                    pypi_0    pypi
openssl                   1.1.1d               he774522_4
opt-einsum                3.1.0                    pypi_0    pypi
pip                       20.0.2                   py37_1
pipdeptree                0.13.2                   pypi_0    pypi
protobuf                  3.11.3                   pypi_0    pypi
pyasn1                    0.4.8                    pypi_0    pypi
pyasn1-modules            0.2.8                    pypi_0    pypi
python                    3.7.6                h60c2a47_2
requests                  2.22.0                   pypi_0    pypi
requests-oauthlib         1.3.0                    pypi_0    pypi
rsa                       4.0                      pypi_0    pypi
setuptools                45.2.0                   py37_0
six                       1.14.0                   pypi_0    pypi
sqlite                    3.31.1               he774522_0
tensorboard               2.0.2                    pypi_0    pypi
tensorflow                2.0.0                    pypi_0    pypi
tensorflow-estimator      2.0.1                    pypi_0    pypi
termcolor                 1.1.0                    pypi_0    pypi
urllib3                   1.25.8                   pypi_0    pypi
vc                        14.1                 h0510ff6_4
vs2015_runtime            14.16.27012          hf0eaf9b_1
werkzeug                  1.0.0                    pypi_0    pypi
wheel                     0.34.2                   py37_0
wincertstore              0.2                      py37_0
wrapt                     1.11.2                   pypi_0    pypi
```

**Comment by tessy1234** [comment]
The dependency walker confirms that all DLLs could be loaded:

![image](https://user-images.githubusercontent.com/41914070/74852267-a0d9e880-533c-11ea-806f-bb695497408b.png)

**Comment by gunan** [comment]
the answer to your question, why does conda instlal load is successful but pip one was not:
Conda packages are built by conda community, and pip packages are the official ones built by us.
The reason pip package cannot start on your system is, packages in pypi require AVX instruction set.
Your CPU (i7 -820 QM) does not have this instruction set. Anaconda packages use MKL to be more compatible, and use older CPUs. The reason official TF builds do not use MKL in the binaries in pypi is, while providing compatibility, at graph level MKL is not as fast as non-mkl solutions for TF.

**Comment by tessy1234** [comment]
In your comment above you referred to [#36167 (comment)](https://github.com/tensorflow/tensorflow/issues/36167#issuecomment-577886156) and one requirement was that the cpu must support AVX instructions.

Here is a utility to check the AVX feature on the computer:
install cpufeature:
-------------------
pip install cpufeature 
[cpufeature](https://pypi.org/project/cpufeature/)

Prerequisite:
Install Microsoft Visual C++ Build Tools

1. Download Microsoft Visual C++ Build Tools from this link: https://visualstudio.microsoft.com/downloads/
and explicitly download from "Tools for Visual Studio 2019" -> "Build Tools for Visual Studio 2019"

2. Select: Workloads -> Desktop and Mobile -> C++ Build Tools, then for Individual Components, select only:

	MSVC v142 - VS 2019 C++ x64/x86 build tools
	Windows 10 SDK

check cpu AVX feature:
----------------------
python -c "import cpufeature; cpufeature.print_features()"
```
(base)>python -c "import cpufeature; cpufeature.print_features()"
=== CPU FEATURES ===
    VendorId                : GenuineIntel
    num_virtual_cores       : 8
    num_physical_cores      : 4
    num_threads_per_core    : 2
    cache_line_size         : 64
    cache_L1_size           : 32768
    cache_L2_size           : 262144
    cache_L3_size           : 8388608
    OS_x64                  : True
    OS_AVX                  : False
    OS_AVX512               : False
    MMX                     : True
    x64                     : True
    ABM                     : False
    RDRAND                  : False
    BMI1                    : False
    BMI2                    : False
    ADX                     : False
    PREFETCHWT1             : False
    MPX                     : False
    SSE                     : True
    SSE2                    : True
    SSE3                    : True
    SSSE3                   : True
    SSE4.1                  : True
    SSE4.2                  : True
    SSE4.a                  : False
    AES                     : False
    SHA                     : False
    AVX                     : False
    XOP                     : False
    FMA3                    : False
    FMA4                    : False
    AVX2                    : False
    AVX512f                 : False
    AVX512pf                : False
    AVX512er                : False
    AVX512cd                : False
    AVX512vl                : False
    AVX512bw                : False
    AVX512dq                : False
    AVX512ifma              : False
    AVX512vbmi              : False
(base)>
```
The query clearly states that my processor supports neither AVX nor AVX2.
Therefore the tensorflow pip package could not be installed.

**Comment by tessy1234** [comment]
If official TF would support both SSE- and AVX-prebuild-binaries that would be a great benefit for the whole TF community. 
I guess AVX-512 is not downward-compatible to AVX2 thus even AVX2-cpu may be soon out-of date.
Why not supporting SSE-prebuild-binaries in addition?

**Comment by tessy1234** [comment]
The interim solution for legacy & low-end CPU without AVX support is to install SSE-prebuild-binaries for tensorflow.
Go to [ tensorflow-windows-wheel](https://github.com/fo40225/tensorflow-windows-wheel) and follow instruction to install either tensorflow 2.0.0 or 2.1.0.

**Comment by tessy1234** [comment]
May you leave your opinion on my thought?

**Comment by gunan** [comment]
At the moment, pypi or pip doed not have a mechanism to deliver different packages based on CPU instruction sets.
One potential option is to create a package that has all three, and TF python code picks whichever it can use.
However, we are well over pypi package size limit, and we are not allowed to upload anything larger at the moment.

Therefore, it is infeasible for us to deliver what you recommended using pypi, without degrading user experience.
