### ISSUE TITLE
C++ API Usage :No such file or directory

### ISSUE THREAD

**Issue by Tondy** [tensorflow/tensorflow#3686]
Hello

I am trying to run the image recognition library but have the error below. 

I run :

wget https://storage.googleapis.com/download.tensorflow.org/models/inception_dec_2015.zip -O tensorflow/examples/label_image/data/inception_dec_2015.zip

Error 

tensorflow/examples/label_image/data/inception_dec_2015.zip: No such file or directory

**Comment by girving** [comment]
This sounds like an issue with how you are using wget, not an issue with tensorflow.  Maybe the directory doesn't exist?
