### ISSUE TITLE
saves everything: The optimizer configuration... it is not able to save TensorFlow optimizers

### ISSUE THREAD

**Issue by johngrabner** [tensorflow/tensorflow#36861]
## URL(s) with the issue: 
https://www.tensorflow.org/tutorials/keras/save_and_load

## Description of issue (what needs changing):

The first reference to "optimizer configuration" is unqualified.
The second reference to "optimizers" is kind of qualified with "(from tf.train)".
Does this mean, tf.keras.optimizer states are stored but not tf.optimizer or does this mean no optimizer states are stored?

full text as follows:

```
This technique saves everything:

- The weight values
- The model's configuration(architecture)
- The optimizer configuration

Keras saves models by inspecting the architecture. Currently, it is not able to save TensorFlow optimizers (from tf.train). When using those you will need to re-compile the model after loading, and you will lose the state of the optimizer.
```

**Comment by jvishnuvardhan** [comment]
@johngrabner Correct. tf.keras.optimizer (v2 optimizers) states are stored but not tf.optimizer (v1 optimizers) as they are not compatible with `checkpoints`. I am updating the tutorial. May be check tomorrow and let me know if anything is not clear to you. Thanks!

**Comment by ashutosh1919** [comment]
@jvishnuvardhan and @johngrabner , Please close this issue if above PR has included what you wanted.

**Comment by johngrabner** [comment]
thanks a lot.
