### ISSUE TITLE
Tflearn import error in Tensorflow 2.1: "ModuleNotFoundError: No module named 'tensorflow.contrib'"

### ISSUE THREAD

**Issue by KoustubhPhalak** [tensorflow/tensorflow#36878]
So, basically, I am trying to migrate the entire code to TF 2.1.0. However, it seems that **tensorflow.contrib** has been deprecated. Due to this, importing tflearn always throws an error of the missing module of tf.contrib. So, how am I supposed to implement this code without using tflearn?
```python
def get_vocab_processor(model_dir):
    vocab_path = os.path.join(model_dir, "..", "vocab")
    #vocab_processor = tf.contrib.learn.preprocessing.VocabularyProcessor.restore(vocab_path)
    #tflearn import error. tflearn support removed from Tensorflow 2.1.0
    import tflearn
    vocab_processor = tflearn.data_utils.VocabularyProcessor.restore(filename=vocab_path)
    return vocab_processor
```

And then, I use this method like this:
```python
def process(FLAGS, dataset):
    x_raw, y_test = data_helpers.load_data_labels(dataset)
    y_test = np.argmax(y_test, axis=1)

    vocab_processor = get_vocab_processor(FLAGS.model_dir)
    x_test = np.array(list(vocab_processor.transform(x_raw)))

    model_file = tf.train.latest_checkpoint(FLAGS.model_dir)
```
**Edit:**
**This is the error I get after execution:**
```
Traceback (most recent call last):
  File "c:\Users\koustubh.p\Downloads\multiple-signal-detection\multiple-signal-detection\churn_updated.py", line 179, in <module>
    process(FLAGS, dataset)
  File "c:\Users\koustubh.p\Downloads\multiple-signal-detection\multiple-signal-detection\churn_updated.py", line 110, in process
    vocab_processor = get_vocab_processor(FLAGS.model_dir)
  File "c:\Users\koustubh.p\Downloads\multiple-signal-detection\multiple-signal-detection\churn_updated.py", line 102, in get_vocab_processor
    import tflearn
  File "c:\Users\koustubh.p\Downloads\multiple-signal-detection\multiple-signal-detection\venv\lib\site-packages\tflearn\__init__.py", line 4, in <module>
    from . import config
  File "c:\Users\koustubh.p\Downloads\multiple-signal-detection\multiple-signal-detection\venv\lib\site-packages\tflearn\config.py", line 5, in <module>
    from .variables import variable
  File "c:\Users\koustubh.p\Downloads\multiple-signal-detection\multiple-signal-detection\venv\lib\site-packages\tflearn\variables.py", line 7, in <module>
    from tensorflow.contrib.framework.python.ops import add_arg_scope as contrib_add_arg_scope
ModuleNotFoundError: No module named 'tensorflow.contrib'
```

**Comment by ayushmankumar7** [comment]
tensorflow.contrib has been removed from tensorflow after 1.15

**Comment by x1489** [comment]
I encountered that error when I tried to run code based on TF 1.x using TF 2.1. As hinted by @ayushmankumar7, a potential resolution (which did fix the issue in my case) is to downgrade from 2.1, and you may need to iterate through a few releases (I tried TF 1.13.2 after 1.15, 1.14, and 1.13.1 did not resolve the issue).
Alternatively, you may want to consult the TF 1 to TF2 migration guide: https://www.tensorflow.org/guide/migrate

**Comment by jvishnuvardhan** [comment]
@KoustubhPhalak Agree with @ayushmankumar7. You could try installing `TF1.14` and use `tflearn`. I think this issue more close to `tflearn` repo. There is another [issue](https://github.com/tensorflow/tensorflow/issues/30794) that was closer to yours. 

I am closing this issue as it is more related to `tflearn' and can be resolved by installing `TF1.x` verison. Thanks!

**Comment by SaberHardy** [comment]
tensorflow.contrib is being removed in version 2.0, you therefore need version <= 1.14 to operate tflearn (this is a TFlearn issue, not a tensorflow one).

so in your case, I would consider moving to tensorflow and using the tf.keras , which provides the higher-level API tflearn

you have to solutions to solve this:
-1 move to tensorflow and keras
-2 uninstall tensorflow which you have and install  "  conda  or  pip  install tensorflow=1.14  ''

good luck

**Comment by KoustubhPhalak** [comment]
Yeah, will go ahead with TF 1.14

**Comment by Minakshee25** [comment]
I cannot install tensorflow ==1.14
command: pip install tensorflow==1.14
ERROR: Could not find a version that satisfies the requirement tensorflow==1.14 (from versions: 2.2.0rc1, 2.2.0rc2, 2.2.0rc3, 2.2.0rc4, 2.2.0)
ERROR: No matching distribution found for tensorflow==1.14

Need help

**Comment by windowsboy111** [comment]
The wheel files have been deleted
https://pypi.org/project/tensorflow/#files
![image](https://user-images.githubusercontent.com/48051237/88916694-1907eb00-d299-11ea-831c-55b7f7f7ca1b.png)
It does not exist anymore, which causes the following issue:
![image](https://user-images.githubusercontent.com/48051237/88916652-08f00b80-d299-11ea-9f56-b043e73f5280.png)
