### ISSUE TITLE
slice shape inference bug

### ISSUE THREAD

**Issue by raingo** [tensorflow/tensorflow#3687]
At current HEAD 32bd3d024f33e920a67a1081bc0ae0048350fdee with the following code,

```
A = tf.placeholder(tf.float32, [None, 10])
B = A[:5, :]
B.get_shape()
```
The first dimension of B is unknown, but should be known. I have to use the `tf.slice` function to get the shape back:

```
A = tf.placeholder(tf.float32, [None, 10])
B = tf.slice(A, [0,0], [5, -1])
B.get_shape()
```

**Comment by girving** [comment]
@aselle Sounds like `strided_slice`.

**Comment by aselle** [comment]
I assume you are expecting to get [5,None] from the inference.
In numpy style, if the slice range exceeds the original shape, it is clamped to the largest size possible.
This means that for tensors shaped 0, 1, 2, 3, 4 you will get tensors that are 0xNone, 1xNone, 2xNone, 3xNone, 4xNone. Only if the the placeholder is 5x10 or larger will you see a fixed value of 5.

**Comment by raingo** [comment]
@aselle you are right. Thanks.
