### ISSUE TITLE
whether the netwrok code is needed to run the prediction procedure

### ISSUE THREAD

**Issue by ardeal** [tensorflow/tensorflow#36871]
Hi,

I have the trained .pb model, and I would like to load it and then run the prediction procedure.

Is the network code needed to run the prediction?, or I only need the following code but don't need the network code?

```cpp
Model model("../ssd_inception/frozen_inference_graph.pb");
    auto outNames1 = new Tensor(model, "num_detections");
    auto outNames2 = new Tensor(model, "detection_scores");
    auto outNames3 = new Tensor(model, "detection_boxes");
    auto outNames4 = new Tensor(model, "detection_classes");

    auto inpName = new Tensor(model, "image_tensor");

    // Read image
    cv::Mat img, inp;
    img = cv::imread("../test.jpg", CV_LOAD_IMAGE_COLOR);

    int rows = img.rows;
    int cols = img.cols;

    cv::resize(img, inp, cv::Size(300, 300));
    cv::cvtColor(inp, inp, CV_BGR2RGB);

    // Put image in Tensor
    std::vector<uint8_t > img_data;
    img_data.assign(inp.data, inp.data + inp.total() * inp.channels());
    inpName->set_data(img_data, {1, 300, 300, 3});

    model.run(inpName, {outNames1, outNames2, outNames3, outNames4});

```

Thanks,
Ardeal

**Comment by gadagashwini** [comment]
@ardeal, Please provide the details about Tensorflow version and full error log. Thanks!

**Comment by ardeal** [comment]
@gadagashwini , I'm now using Tensorflow 1.14.0.
In my C++ code, I would like to load the weight model of YoloV3 downloaded from web site, and then write the C++ code to run prediction. 

My question is: 
whether I should write the network code in C++?

Thanks,
Ardeal

**Comment by ymodak** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.
 Thanks!
