### ISSUE TITLE
time of tensorflow1.14 built from source perfroms worse than tensorflow1.14 from pypi

### ISSUE THREAD

**Issue by allen-ash** [tensorflow/tensorflow#36874]
**System information**
- OS Platform and Distribution : Linux Ubuntu 16.04
- TensorFlow installed from: source
- TensorFlow version:1.14.0
- Python version:3.6.2
- Installed using :pip
- Bazel version: 0.25.2
- GCC/Compiler version: 5.4.0
- CPU: Intel Core i9-9900K

I want to speed up CPU inference on trained Mask R-CNN pb model.  So, I followed instructions on tensorflow webpage [here](https://www.tensorflow.org/install/source) and method from intel [here](https://software.intel.com/en-us/articles/intel-optimization-for-tensorflow-installation-guide#linux_B_S).  

**Here is .tf_configure.bazelrc after running ./configure**
- build --action_env PYTHON_BIN_PATH="/home/allen/miniconda3/envs/tf1_mkl/bin/python"
- build --action_env PYTHON_LIB_PATH="/home/allen/miniconda3/envs/tf1_mkl/lib/python3.6/site-packages"
- build --python_path="/home/allen/miniconda3/envs/tf1_mkl/bin/python"
- build:xla --define with_xla_support=true
- build --config=xla
- build --action_env TF_NEED_OPENCL_SYCL="0"
- build --action_env TF_NEED_ROCM="0"
- build --action_env TF_NEED_CUDA="0"
- build --action_env TF_DOWNLOAD_CLANG="0"
- build:opt --copt=-march=native
- build:opt --copt=-Wno-sign-compare
- build:opt --host_copt=-march=native
- build:opt --define with_default_optimizations=true
- build:v2 --define=tf_api_version=2
- test --flaky_test_attempts=3
- test --test_size_filters=small,medium
- test --test_tag_filters=-benchmark-test,-no_oss,-oss_serial
- test --build_tag_filters=-benchmark-test,-no_oss
- test --test_tag_filters=-gpu
- test --build_tag_filters=-gpu
- build --action_env TF_CONFIGURE_IOS="0"

**Here is my bazel build command:**
`bazel build --config=mkl --cxxopt=-D_GLIBCXX_USE_CXX11_ABI=0 --copt=-march=sandybridge --copt=-mtune=ivybridge --copt=-O3 //tensorflow/tools/pip_package:build_pip_package
`
**Next, I generated whl and installed successfully.**
But time of sess.run of Mask R-CNN is about 1s per image, which is worse than tf1.14 installed from pypi.
**Here is the output using tensorflow installed from source **

> WARNING:tensorflow:
> The TensorFlow contrib module will not be included in TensorFlow 2.0.
> For more information, please see:
>   * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
>   * https://github.com/tensorflow/addons
>   * https://github.com/tensorflow/io (for I/O related ops)
> If you depend on functionality not listed there, please file an issue.
> 
> WARNING:tensorflow:From time_compare.py:314: The name tf.app.run is deprecated. Please use tf.compat.v1.app.run instead.
> 
> WARNING:tensorflow:From time_compare.py:43: FastGFile.__init__ (from tensorflow.python.platform.gfile) is deprecated and will be removed in a future version.
> Instructions for updating:
> Use tf.gfile.GFile.
> W0219 12:14:37.498566 140296832321280 deprecation.py:323] From time_compare.py:43: FastGFile.__init__ (from tensorflow.python.platform.gfile) is deprecated and will be removed in a future version.
> Instructions for updating:
> Use tf.gfile.GFile.
> WARNING:tensorflow:From time_compare.py:44: The name tf.GraphDef is deprecated. Please use tf.compat.v1.GraphDef instead.
> 
> W0219 12:14:37.498702 140296832321280 module_wrapper.py:139] From time_compare.py:44: The name tf.GraphDef is deprecated. Please use tf.compat.v1.GraphDef instead.
> 
> Graph loaded.
> WARNING:tensorflow:From time_compare.py:50: The name tf.Session is deprecated. Please use tf.compat.v1.Session instead.
> 
> W0219 12:14:38.048038 140296832321280 module_wrapper.py:139] From time_compare.py:50: The name tf.Session is deprecated. Please use tf.compat.v1.Session instead.
> 
> 2020-02-19 12:14:38.048334: I tensorflow/core/platform/cpu_feature_guard.cc:145] This TensorFlow binary is optimized with Intel(R) MKL-DNN to use the following CPU instructions in performance critical operations:  AVX2 FMA
> To enable them in non-MKL-DNN operations, rebuild TensorFlow with the appropriate compiler flags.
> 2020-02-19 12:14:38.070567: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 3600000000 Hz
> 2020-02-19 12:14:38.071554: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x55ed8c786280 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
> 2020-02-19 12:14:38.071582: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
> 2020-02-19 12:14:38.072303: I tensorflow/core/common_runtime/process_util.cc:115] Creating new thread pool with default inter op setting: 2. Tune using inter_op_parallelism_threads for best performance.
> Image No.0 time cost:2.7566s/home/allen/ytzx/dataset/cwfp/v4/val2014/001002_r180_81445.jpg, time:2.756582736968994
> Image No.1 time cost:0.9806s/home/allen/ytzx/dataset/cwfp/v4/val2014/001006_r270_80042.jpg, average time:0.9805862903594971

**And here is inference output using tensorflow installed from pypi**

> WARNING:tensorflow:From time_compare.py:314: The name tf.app.run is deprecated. Please use tf.compat.v1.app.run instead.
> 
> WARNING:tensorflow:From time_compare.py:43: FastGFile.__init__ (from tensorflow.python.platform.gfile) is deprecated and will be removed in a future version.
> Instructions for updating:
> Use tf.gfile.GFile.
> W0219 12:15:57.491406 139925355824896 deprecation.py:323] From time_compare.py:43: FastGFile.__init__ (from tensorflow.python.platform.gfile) is deprecated and will be removed in a future version.
> Instructions for updating:
> Use tf.gfile.GFile.
> WARNING:tensorflow:From time_compare.py:44: The name tf.GraphDef is deprecated. Please use tf.compat.v1.GraphDef instead.
> 
> W0219 12:15:57.491531 139925355824896 deprecation_wrapper.py:119] From time_compare.py:44: The name tf.GraphDef is deprecated. Please use tf.compat.v1.GraphDef instead.
> 
> Graph loaded.
> WARNING:tensorflow:From time_compare.py:50: The name tf.Session is deprecated. Please use tf.compat.v1.Session instead.
> 
> W0219 12:15:58.086142 139925355824896 deprecation_wrapper.py:119] From time_compare.py:50: The name tf.Session is deprecated. Please use tf.compat.v1.Session instead.
> 
> 2020-02-19 12:15:58.086468: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
> 2020-02-19 12:15:58.110562: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 3600000000 Hz
> 2020-02-19 12:15:58.111640: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x56350f20bfb0 executing computations on platform Host. Devices:
> 2020-02-19 12:15:58.111652: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): <undefined>, <undefined>
> 2020-02-19 12:15:58.891970: W tensorflow/compiler/jit/mark_for_compilation_pass.cc:1412] (One-time warning): Not using XLA:CPU for cluster because envvar TF_XLA_FLAGS=--tf_xla_cpu_global_jit was not set.  If you want XLA:CPU, either set that envvar, or use experimental_jit_scope to enable XLA:CPU.  To confirm that XLA is active, pass --vmodule=xla_compilation_cache=1 (as a proper command-line flag, not via TF_XLA_FLAGS) or set the envvar XLA_FLAGS=--xla_hlo_profile.
> Image No.0 time cost:1.2104s/home/allen/ytzx/dataset/cwfp/v4/val2014/001002_r180_81445.jpg, time:1.2104294300079346
> Image No.1 time cost:0.376s/home/allen/ytzx/dataset/cwfp/v4/val2014/001006_r270_80042.jpg, average time:0.3759894371032715
> 
Any suggestions or thoughts would be appreciated.

**Comment by Saduf2019** [comment]
@allen-ash please note during the bazel build command: everything is done from scratch and the whl file is generated, which is not the case during pip installation, hence the time difference.

**Comment by allen-ash** [comment]
@Saduf2019 Thanks for your replay. Yes I understand that, I just want to know In which way from scratch can be optimizing time cost. 
Considering currently command is `bazel build --config=mkl --cxxopt=-D_GLIBCXX_USE_CXX11_ABI=0 --copt=-march=sandybridge --copt=-mtune=ivybridge --copt=-O3 //tensorflow/tools/pip_package:build_pip_package`  didn't perfrom well.

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.
