### ISSUE TITLE
Basic LSTM TFLite model created with new experimental converter results in model with incorrect output shape

### ISSUE THREAD

**Issue by bilalsoomro** [tensorflow/tensorflow#36879]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Google Colab
- TensorFlow installed from (source or binary): binary
- TensorFlow version (or github SHA if from source): 2.2.0-dev20200218

**Command used to run the converter or code if you’re using the Python API**

```
converter = tf.lite.TFLiteConverter.from_keras_model(model)
converter.experimental_new_converter = True
tflite_model = converter.convert()
open("mnist_lstm_f32.tflite", "wb").write(tflite_model)
```

**The output from the converter invocation**

```
Conversion is successful
```

**Failure details**
I am creating a basic MNIST classification model which includes a single LSTM layer. Using the new experimental converter option, the model can be converted to TFLite format successfully and inferring from the TFLite model using the Python Interpreter API gives correct results.

However, the model's output shape is just an empty array and running the model on Android required the output buffer size to be specified so the model crashes. I expect the output shape to be ```[1, 10]``` however that is not the case as shown below.
```
[{'name': 'Identity', 'index': 52, 'shape': array([], dtype=int32), 'shape_signature': array([], dtype=int32), 'dtype': <class 'numpy.float32'>, 'quantization': (0.0, 0), 'quantization_parameters': {'scales': array([], dtype=float32), 'zero_points': array([], dtype=int32), 'quantized_dimension': 0}, 'sparsity_parameters': {}}]
```

**Any other info / logs**
[Colab notebook](https://colab.research.google.com/drive/1X5B2O2aF9HlVX0GHl1IAASPqrz45ujff)

**Comment by jdduke** [comment]
@renjie-liu could you take a look?

**Comment by renjie-liu** [comment]
{'name': 'input', 'index': 0, 'shape': array([ 1, 28, 28], dtype=int32), 'shape_signature': array([-1, 28, 28], dtype=int32),

looks like it is because the recent change that we no longer hard code the batch size to be 1.

Hi Nupur, do you have any workaround for Keras model?

Thanks!

**Comment by jvishnuvardhan** [comment]
@bilalsoomro This was resolved in recent `tf-nightly`. When I use `tf-nightly` the code correctly output the output shape as [1, 10].  Please find the [gist here](https://colab.research.google.com/gist/jvishnuvardhan/5e9c836af6fe32405f7544f4652f98aa/mnist.ipynb).

### Previous output

`[{'name': 'Identity', 'index': 33, 'shape': array([], dtype=int32), 'shape_signature': array([], dtype=int32), 'dtype': <class 'numpy.float32'>, 'quantization': (0.0, 0), 'quantization_parameters': {'scales': array([], dtype=float32), 'zero_points': array([], dtype=int32), 'quantized_dimension': 0}, 'sparsity_parameters': {}}]`

### New output 

`[{'name': 'Identity', 'index': 37, 'shape': array([ 1, 10], dtype=int32), 'shape_signature': array([-1, 10], dtype=int32), 'dtype': <class 'numpy.float32'>, 'quantization': (0.0, 0), 'quantization_parameters': {'scales': array([], dtype=float32), 'zero_points': array([], dtype=int32), 'quantized_dimension': 0}, 'sparsity_parameters': {}}]`


I am closing the issue as this was resolved. Please feel free to reopen if the issue persists for you. Thanks!
