### ISSUE TITLE
ValueError: We need at least 1 word to plot a word cloud, got 0.

### ISSUE THREAD

**Issue by Jyothif** [tensorflow/tensorflow#36889]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information** - Have I written custom code (as opposed to using a stock
example script provided in TensorFlow): - OS Platform and Distribution (e.g.,
Linux Ubuntu 16.04): - Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if
the issue happens on mobile device: - TensorFlow installed from (source or
binary): - TensorFlow version (use command below): - Python version: - Bazel
version (if compiling from source): - GCC/Compiler version (if compiling from
source): - CUDA/cuDNN version: - GPU model and memory:

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**

**Describe the expected behavior**

**Code to reproduce the issue** Provide a reproducible test case that is the
bare minimum necessary to generate the problem.

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

normal_words =' '.join([text for text in combi['tidy_tweet'][combi['label'] == 0]]) 
wordcloud = WordCloud(width=800, height=500, random_state=21, max_font_size=110).generate(normal_words) 
plt.figure(figsize=(10, 7)) 
plt.imshow(wordcloud, interpolation="bilinear") 
plt.axis('off') 
plt.show()
ValueError: We need at least 1 word to plot a word cloud, got 0.

**Comment by ravikyram** [comment]
@Jyothif 

Looks like code is incomplete.Can you please share colab link or simple standalone code with supporting files to reproduce the issue in our environment. It helps us in localizing the issue faster.Thanks!

**Comment by Jyothif** [comment]
**here is the code**


import re
import nltk
import string
import warnings
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
pd.set_option("display.max_colwidth",200)
warnings.filterwarnings("ignore",category=DeprecationWarning)

train = pd.read_csv('train_E6oV3lV.csv')
test = pd.read_csv('test_tweets_anuFYb8.csv')
train.head()

train[train['label']==0].head(10)

train[train['label']==1].head(10)

length_train = train['tweet'].str.len()
length_test = test['tweet'].str.len()
plt.hist(length_train,bins = 20,label = "train_tweets")
plt.hist(length_test,bins = 20,label = "test_tweets")
plt.legend()
plt.show()

combi = train.append(test,ignore_index=True)
combi.shape

def remove_pattern(input_txt, pattern):
    r =re.findall(pattern, input_txt)
    for i in r:
        input_txt = re.sub(i,'',input_txt)
    return input_txt

combi['tidy_tweet'] = np.vectorize(remove_pattern)(combi['tweet'],"@\w*")
combi.head()

combi['tidy_tweet'] = combi['tidy_tweet'].str.replace("[^a-zA-Z#]", " ")
combi.head(10)

combi['tidy_tweet'] = combi['tidy_tweet'].apply(lambda x: ' '.join([w for w in x.split() if len(w)>3]))
combi.head()

tokenized_tweet = combi['tidy_tweet'].apply(lambda x: x.split()) #tokenizing
tokenized_tweet.head()

from nltk.stem.porter import *
stemmer = PorterStemmer()
tokenized_tweet = tokenized_tweet.apply(lambda x:[stemmer.stem(i) for i in x]) #stemming
for i in range(len(tokenized_tweet)):
    tokenized_tweet[i] = ' '.join(tokenized_tweet[i])
combi['tidy_tweet'] = tokenized_tweet

all_words = ' '.join([text for text in combi['tidy_tweet']]) 
from wordcloud import WordCloud
wordcloud = WordCloud().generate(all_words) 
plt.figure(figsize =(10,7))
plt.imshow(wordcloud, interpolation = "bilinear")
plt.axis('off')
plt.show()

I have attached code in my repository please check, if required.

**Comment by Jyothif** [comment]
@ravikyram  hey it is resolved...Thanks!

**Comment by Davisy** [comment]
> @ravikyram hey it is resolved...Thanks!

how did you resolve the problem?, I got the same problem

**Comment by michae1l** [comment]
please how did you solve it, having the same issue

**Comment by oscarfdzpata** [comment]
please how did you solve it, having the same issue

**Comment by lalitharode** [comment]
i am also suffering from the same problem (We need at least 1 word to plot a word cloud, got 0)
