### ISSUE TITLE
Is NonMaxSuppressionV4 supported？

### ISSUE THREAD

**Issue by GatzZ** [tensorflow/tensorflow#36882]
**System information**
- Linux Ubuntu 16.04
- TensorFlow 2.1.0

**Provide the text output from tflite_convert**
```
Here is a list of operators for which you will need custom implementations: NonMaxSuppressionV4.
```

**Code**
```
selected_indices_padded,  num_valid = tf.image.non_max_suppression(boxes=boxes_squeezed,
                                                  scores=scores,
                                                  max_output_size=20,
                                                  score_threshold=0.7,
                                                  iou_threshold=0.5,
                                                  pad_to_max_output_size=True,
                                                  )
```

According to https://www.tensorflow.org/lite/guide/ops_compatibility,  `NON_MAX_SUPPRESSION_V4` was already supported.
However,  when I use it to build my model and try to convert it into tflite, the error came out.

I tried a solution with `tf.lite.OpsSet.SELECT_TF_OPS`, and the error gone.
```
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS,
                                       tf.lite.OpsSet.SELECT_TF_OPS]
```

But I cannot run it properly with native TFLite intepreter... Another error showed as below:

```
RuntimeError: Regular TensorFlow ops are not supported by this interpreter. Make sure you apply/link the Flex delegate before inference.Node number 92 (FlexNonMaxSuppressionV4) failed to prepare.
```

**Comment by windmaple** [comment]
Use new MLIR converter:

converter.experimental_new_converter = True

**Comment by GatzZ** [comment]
> Use new MLIR converter:
> 
> converter.experimental_new_converter = True

It works. Thank you very much
