### ISSUE TITLE
Error when trying to run tensorboard --logdir=some_path

### ISSUE THREAD

**Issue by josefinb** [tensorflow/tensorflow#3688]
Hi,

I am using python 2.7 on Mac 10.11.4.

I get errors when I am trying to run tensorboard --logdir=path

where path is some path I have specified, i.e. 'visualizations'

It correctly creates the directory visualizations in my current working directory, but

if I run: tensorboard --logdir=path, I get:
SyntaxError: can't assign to operator

If I try: tensorboard --logdir=visualizations, I get:
SyntaxError: can't assign to operator

If I try: tensorboard --logdir=/visualizations/, I get:
SyntaxError: invalid syntax

Please help me! And I would really appreciate an explanation for this, as I am relatively new to all this.

Thanks a lot in advance!

**Comment by girving** [comment]
What are the full error messages?

**Comment by sarahedkins** [comment]
What was the solution to this? I'm facing the same issue.

**Comment by josefinb** [comment]
You need to run it in the terminal!

**Comment by leifulstrup** [comment]
inside jupiter....

%%sh
tensorboard --logdir=log_simple_graph # shell command

**Comment by rahulbhat44** [comment]
Run this :
tensorboard --logdir==training:your_log_dir --host=127.0.0.1 
and then open in chrome

**Comment by ralfmue** [comment]
Hi there, 
all worked fine for  me until I accidently double-clicked the "Reset Spyder Settings.py"...
I got the error messages described above, when trying to serve the Tensorboard directly through Spyder console.
Solution for me: run the tensorboard call directly from Anaconda Powershell.
