### ISSUE TITLE
How could I can add a new OS on the support on the "tested and supported" list?

### ISSUE THREAD

**Issue by Hui-Zhi** [tensorflow/tensorflow#36881]
## URL(s) with the issue:
https://www.tensorflow.org/install

## Description of issue (what needs changing):
Could someone instruct me how to add a new OS on the support on the "tested and supported" list, I would like to make some efforts for Opensuse and SLE. 

There might have some steps to make sure an OS is "tested and supported", right?

**Comment by ravikyram** [comment]
@Hui-Zhi 
Opensuse and SLE are Linux flavours. Can you please follow the instructios in [TensorFlow website](https://www.tensorflow.org/install/source) and see how it progresses. Thanks!

**Comment by Hui-Zhi** [comment]
Yes, you're right, I should not use new OS, thanks for figuring it out. And Ubuntu is also Linux flavors. On this website, it only have instructions for Ubuntu and Mac OS, what I am trying to do is adding Opensuse and SLE to the "tested and supported" list to give users more options, sure I believe the instructions for Opensuse and SLE is needed, and it's different from Ubuntu and Mac.

But what I am not sure is should I just add Opensuse and SLE to the website source code (instructions will also be updated), the make a pull request? Or there has some previous steps should be done? 

I don't even know if the community would like to accept this change.

**Comment by lamberta** [comment]
Hi @Hui-Zhi,

The tensorflow.org/install pages are for officially-supported install and build configs by the TensorFlow team. So we should not add new OSes here.

But organizing an "extended" support list sounds like it could fall under [SIG Build](https://www.tensorflow.org/community/forums). Maybe send a message to the [build@tensorflow.org list](https://groups.google.com/a/tensorflow.org/forum/#!forum/build)?

**Comment by gunan** [comment]
Our python packages are built according to the "manylkinux2010" standard.
So if you use the prebuilt packages from pypi, they should work on 90% of the linux distributions.
