### ISSUE TITLE
Unable to build r1.15 using gcc 4.8.5-39 because of -std=c++14 argument.

### ISSUE THREAD

**Issue by odinsbane** [tensorflow/tensorflow#36892]
The crux of this issue is **Does tensorflow r1.15 compile with gcc 4.8.5** when I check out r1.15, I cannot compile due to an invalid argument "-std=c++14" similar to #31760 but I do not understand the resolution from that. 

I am preparing to migrate to version 2.X so I tried to build r1.15. I get two errors. 

The first error is resolved in #28824

The second error I have not gotten around. Everthing seems to build fine then I get.

>ERROR: /home/username/.cache/bazel/_bazel_smithm3/6bda0689d89415301f8ee7c16fbd66e8/external/local_config_mlir/BUILD:418:1: C++ compilation of rule '@local_config_mlir//:Support' failed (Exit 1)  
>gcc: error: unrecognized command line option '-std=c++14'

**System information**
- Centos7
- checkout r1.15 and v1.15.1
- Python 3.8.1
- Bazel version 0.25.2
- GCC/Compiler version 4.8.5-039
- CUDA/cuDNN version 10.1/7
- GPU model and memory Nvidia 1080Ti

This appears to be caused by mlir requiring a newer version of gcc, since it requires `-std=c++14` and if you replace it with it with '-std=c++1y' you'lll get an error about `std::make_unique`

Is tensorflow r1.15 supposed to be compatible with gcc 4.8.5 (default on centos 7)?

 **Reproducing the problem.**

git clone https://github.com/tensorflow/tensorflow.git
cd tensorflow
git checkout r1.15
./configure
**Select default options + CUDA**
bazel build //tensorflow/tools/pip_package:build_pip_package

**Comment by Saduf2019** [comment]
@odinsbane tensorflow r1.15 is compatible with gcc 4.8.5 , you can check this link for [reference](https://www.tensorflow.org/install/source#tested_build_configurations).

please share entire error logs and steps follwed before you faced this issue.

**Comment by odinsbane** [comment]
I have included all of the steps, but Ill include all of the log output too. PART 1

    ~/local/Python3.8/bin/python3 -m venv tensorflow-build-env
    git clone https://github.com/tensorflow/tensorflow.git

> Cloning into 'tensorflow'...
> remote: Enumerating objects: 833165, done.
> remote: Total 833165 (delta 0), reused 0 (delta 0), pack-reused 833165
> Receiving objects: 100% (833165/833165), 483.03 MiB | 33.02 MiB/s, done.
> Resolving deltas: 100% (674581/674581), done.
> Checking out files: 100% (19594/19594), done.

    cd tensorflow
    git checkout r1.15

> Checking out files: 100% (11771/11771), done.
> Branch r1.15 set up to track remote branch r1.15 from origin.
> Switched to a new branch 'r1.15'

    . ../tensorflow-build-env/bin/activate
    pip install Keras-Preprocessing numpy six wheel

> Collecting Keras-Preprocessing
>   Using cached https://files.pythonhosted.org/packages/28/6a/8c1f62c37212d9fc441a7e26736df51ce6f0e38455816445471f10da4f0a/Keras_Preprocessing-1.1.0-py2.py3-none-any.whl
> Collecting numpy
>   Using cached https://files.pythonhosted.org/packages/41/38/b278d96baebc6a4818cfd9c0fb6f0e62013d5b87374bcf0f14a0e9b83ed5/numpy-1.18.1-cp38-cp38-manylinux1_x86_64.whl
> Collecting six
>   Using cached https://files.pythonhosted.org/packages/65/eb/1f97cb97bfc2390a276969c6fae16075da282f5058082d4cb10c6c5c1dba/six-1.14.0-py2.py3-none-any.whl
> Collecting wheel
>   Using cached https://files.pythonhosted.org/packages/8c/23/848298cccf8e40f5bbb59009b32848a4c38f4e7f3364297ab3c3e2e2cd14/wheel-0.34.2-py2.py3-none-any.whl
> Installing collected packages: numpy, six, Keras-Preprocessing, wheel
> Successfully installed Keras-Preprocessing-1.1.0 numpy-1.18.1 six-1.14.0 wheel-0.34.2
> WARNING: You are using pip version 19.2.3, however version 20.0.2 is available.
> You should consider upgrading via the 'pip install --upgrade pip' command.

    ./configure

> WARNING: --batch mode is deprecated. Please instead explicitly shut down your Bazel server using the command "bazel shutdown".
> You have bazel 0.25.2 installed.
> Please specify the location of python. [Default is /home/USERNAME/Desktop/tensorflow-issue/tensorflow-build-env/bin/python]: 
> 
> 
> Found possible Python library paths:
>   /home/USERNAME/Desktop/tensorflow-issue/tensorflow-build-env/lib/python3.8/site-packages
> Please input the desired Python library path to use.  Default is [/home/USERNAME/Desktop/tensorflow-issue/tensorflow-build-env/lib/python3.8/site-packages]
> 
> Do you wish to build TensorFlow with XLA JIT support? [Y/n]: 
> XLA JIT support will be enabled for TensorFlow.
> 
> Do you wish to build TensorFlow with OpenCL SYCL support? [y/N]: 
> No OpenCL SYCL support will be enabled for TensorFlow.
> 
> Do you wish to build TensorFlow with ROCm support? [y/N]: 
> No ROCm support will be enabled for TensorFlow.
> 
> Do you wish to build TensorFlow with CUDA support? [y/N]: y
> CUDA support will be enabled for TensorFlow.
> 
> Do you wish to build TensorFlow with TensorRT support? [y/N]: 
> No TensorRT support will be enabled for TensorFlow.
> 
> Found CUDA 10.1 in:
>     /usr/local/cuda/lib64
>     /usr/local/cuda/include
> Found cuDNN 7 in:
>     /usr/local/cuda/lib64
>     /usr/local/cuda/include
> 
> 
> Please specify a list of comma-separated CUDA compute capabilities you want to build with.
> You can find the compute capability of your device at: https://developer.nvidia.com/cuda-gpus.
> Please note that each additional compute capability significantly increases your build time and binary size, and that TensorFlow only supports compute capabilities >= 3.5 [Default is: 6.1,6.1]:

> Do you want to use clang as CUDA compiler? [y/N]: 
> nvcc will be used as CUDA compiler.
> 
> Please specify which gcc should be used by nvcc as the host compiler. [Default is /usr/bin/gcc]: 
> 
> 
> Do you wish to build TensorFlow with MPI support? [y/N]: 
> No MPI support will be enabled for TensorFlow.
> 
> Please specify optimization flags to use during compilation when bazel option "--config=opt" is specified [Default is -march=native -Wno-sign-compare]: 
> 
> 
> Would you like to interactively configure ./WORKSPACE for Android builds? [y/N]: 
> Not configuring the WORKSPACE for Android builds.
> 
> Preconfigured Bazel build configs. You can use any of the below by adding "--config=<>" to your build command. See .bazelrc for more details.
> 	--config=mkl         	# Build with MKL support.
> 	--config=monolithic  	# Config for mostly static monolithic build.
> 	--config=gdr         	# Build with GDR support.
> 	--config=verbs       	# Build with libverbs support.
> 	--config=ngraph      	# Build with Intel nGraph support.
> 	--config=numa        	# Build with NUMA support.
> 	--config=dynamic_kernels	# (Experimental) Build kernels into separate shared objects.
> 	--config=v2          	# Build TensorFlow 2.x instead of 1.x.
> Preconfigured Bazel build configs to DISABLE default on features:
> 	--config=noaws       	# Disable AWS S3 filesystem support.
> 	--config=nogcp       	# Disable GCP support.
> 	--config=nohdfs      	# Disable HDFS support.
> 	--config=noignite    	# Disable Apache Ignite support.
> 	--config=nokafka     	# Disable Apache Kafka support.
> 	--config=nonccl      	# Disable NVIDIA NCCL support.
> Configuration finished

    bazel build --config=opt --config=cuda //tensorflow/tools/pip_package:build_pip_package

Starting local Bazel server and connecting to it...
WARNING: The following configs were expanded more than once: [cuda, using_cuda]. For repeatable flags, repeats are counted twice and may lead to unexpected behavior.
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=1 --terminal_columns=160
INFO: Reading rc options for 'build' from /home/USERNAME/Desktop/tensorflow-issue/tensorflow/.bazelrc:
  'build' options: --apple_platform_type=macos --define framework_shared_object=true --define open_source_build=true --define=use_fast_cpp_protos=true --define=allow_oversize_protos=true --spawn_strategy=standalone -c opt --announce_rc --define=grpc_no_ares=true --define=PREFIX=/usr --define=LIBDIR=$(PREFIX)/lib --define=INCLUDEDIR=$(PREFIX)/include --copt=-w --config=v1
INFO: Reading rc options for 'build' from /home/USERNAME/Desktop/tensorflow-issue/tensorflow/.tf_configure.bazelrc:
  'build' options: --action_env PYTHON_BIN_PATH=/home/USERNAME/Desktop/tensorflow-issue/tensorflow-build-env/bin/python --action_env PYTHON_LIB_PATH=/home/USERNAME/Desktop/tensorflow-issue/tensorflow-build-env/lib/python3.8/site-packages --python_path=/home/USERNAME/Desktop/tensorflow-issue/tensorflow-build-env/bin/python --config=xla --action_env CUDA_TOOLKIT_PATH=/usr/local/cuda --action_env TF_CUDA_COMPUTE_CAPABILITIES=6.1,6.1 --action_env LD_LIBRARY_PATH=:/usr/local/cuda/lib64 --action_env GCC_HOST_COMPILER_PATH=/usr/bin/gcc --config=cuda --action_env TF_CONFIGURE_IOS=0
INFO: Found applicable config definition build:v1 in file /home/USERNAME/Desktop/tensorflow-issue/tensorflow/.bazelrc: --define=tf_api_version=1 --action_env=TF2_BEHAVIOR=0
INFO: Found applicable config definition build:xla in file /home/USERNAME/Desktop/tensorflow-issue/tensorflow/.bazelrc: --action_env=TF_ENABLE_XLA=1 --define=with_xla_support=true
INFO: Found applicable config definition build:xla in file /home/USERNAME/Desktop/tensorflow-issue/tensorflow/.tf_configure.bazelrc: --define with_xla_support=true
INFO: Found applicable config definition build:cuda in file /home/USERNAME/Desktop/tensorflow-issue/tensorflow/.bazelrc: --config=using_cuda --define=using_cuda_nvcc=true
INFO: Found applicable config definition build:using_cuda in file /home/USERNAME/Desktop/tensorflow-issue/tensorflow/.bazelrc: --define=using_cuda=true --action_env TF_NEED_CUDA=1 --crosstool_top=@local_config_cuda//crosstool:toolchain
INFO: Found applicable config definition build:opt in file /home/USERNAME/Desktop/tensorflow-issue/tensorflow/.tf_configure.bazelrc: --copt=-march=native --copt=-Wno-sign-compare --host_copt=-march=native --define with_default_optimizations=true
INFO: Found applicable config definition build:cuda in file /home/USERNAME/Desktop/tensorflow-issue/tensorflow/.bazelrc: --config=using_cuda --define=using_cuda_nvcc=true
INFO: Found applicable config definition build:using_cuda in file /home/USERNAME/Desktop/tensorflow-issue/tensorflow/.bazelrc: --define=using_cuda=true --action_env TF_NEED_CUDA=1 --crosstool_top=@local_config_cuda//crosstool:toolchain
INFO: An error occurred during the fetch of repository 'io_bazel_rules_docker'
INFO: Call stack for the definition of repository 'io_bazel_rules_docker':
 - /home/USERNAME/.cache/bazel/_bazel_USERNAME/5aa6c3674f37090388bbfbf0ef73a503/external/bazel_toolchains/repositories/repositories.bzl:37:9
 - /home/USERNAME/Desktop/tensorflow-issue/tensorflow/WORKSPACE:35:1
ERROR: error loading package '': Encountered error while reading extension file 'repositories/repositories.bzl': no such package '@io_bazel_rules_docker//repositories': Traceback (most recent call last):
	File "/home/USERNAME/.cache/bazel/_bazel_USERNAME/5aa6c3674f37090388bbfbf0ef73a503/external/bazel_tools/tools/build_defs/repo/git.bzl", line 234
		_clone_or_update(ctx)
	File "/home/USERNAME/.cache/bazel/_bazel_USERNAME/5aa6c3674f37090388bbfbf0ef73a503/external/bazel_tools/tools/build_defs/repo/git.bzl", line 74, in _clone_or_update
		fail(("error cloning %s:\n%s" % (ctx....)))
error cloning io_bazel_rules_docker:
+ cd /home/USERNAME/.cache/bazel/_bazel_USERNAME/5aa6c3674f37090388bbfbf0ef73a503/external
+ rm -rf /home/USERNAME/.cache/bazel/_bazel_USERNAME/5aa6c3674f37090388bbfbf0ef73a503/external/io_bazel_rules_docker /home/USERNAME/.cache/bazel/_bazel_USERNAME/5aa6c3674f37090388bbfbf0ef73a503/external/io_bazel_rules_docker
+ git clone '' https://github.com/bazelbuild/rules_docker.git /home/USERNAME/.cache/bazel/_bazel_USERNAME/5aa6c3674f37090388bbfbf0ef73a503/external/io_bazel_rules_docker
Too many arguments.

usage: git clone [options] [--] <repo> [<dir>]

    -v, --verbose         be more verbose
    -q, --quiet           be more quiet
    --progress            force progress reporting
    -n, --no-checkout     don't create a checkout
    --bare                create a bare repository
    --mirror              create a mirror repository (implies bare)
    -l, --local           to clone from a local repository
    --no-hardlinks        don't use local hardlinks, always copy
    -s, --shared          setup as shared repository
    --recursive           initialize submodules in the clone
    --recurse-submodules  initialize submodules in the clone
    --template <template-directory>
                          directory from which templates will be used
    --reference <repo>    reference repository
    -o, --origin <name>   use <name> instead of 'origin' to track upstream
    -b, --branch <branch>
                          checkout <branch> instead of the remote's HEAD
    -u, --upload-pack <path>
                          path to git-upload-pack on the remote
    --depth <depth>       create a shallow clone of that depth
    --single-branch       clone only one branch, HEAD or --branch
    --separate-git-dir <gitdir>
                          separate git dir from working tree
    -c, --config <key=value>
                          set config inside the new repository

+ git clone https://github.com/bazelbuild/rules_docker.git /home/USERNAME/.cache/bazel/_bazel_USERNAME/5aa6c3674f37090388bbfbf0ef73a503/external/io_bazel_rules_docker
+ git -C /home/USERNAME/.cache/bazel/_bazel_USERNAME/5aa6c3674f37090388bbfbf0ef73a503/external/io_bazel_rules_docker reset --hard 251f6a68b439744094faff800cd029798edf9faa
Unknown option: -C
usage: git [--version] [--help] [-c name=value]
           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]
           [-p|--paginate|--no-pager] [--no-replace-objects] [--bare]
           [--git-dir=<path>] [--work-tree=<path>] [--namespace=<name>]
           <command> [<args>]
+ git -C /home/USERNAME/.cache/bazel/_bazel_USERNAME/5aa6c3674f37090388bbfbf0ef73a503/external/io_bazel_rules_docker fetch '' origin 251f6a68b439744094faff800cd029798edf9faa:251f6a68b439744094faff800cd029798edf9faa
Unknown option: -C
usage: git [--version] [--help] [-c name=value]
           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]
           [-p|--paginate|--no-pager] [--no-replace-objects] [--bare]
           [--git-dir=<path>] [--work-tree=<path>] [--namespace=<name>]
           <command> [<args>]
+ git -C /home/USERNAME/.cache/bazel/_bazel_USERNAME/5aa6c3674f37090388bbfbf0ef73a503/external/io_bazel_rules_docker fetch origin 251f6a68b439744094faff800cd029798edf9faa:251f6a68b439744094faff800cd029798edf9faa
Unknown option: -C
usage: git [--version] [--help] [-c name=value]
           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]
           [-p|--paginate|--no-pager] [--no-replace-objects] [--bare]
           [--git-dir=<path>] [--work-tree=<path>] [--namespace=<name>]
           <command> [<args>]
ERROR: error loading package '': Encountered error while reading extension file 'repositories/repositories.bzl': no such package '@io_bazel_rules_docker//repositories': Traceback (most recent call last):
	File "/home/USERNAME/.cache/bazel/_bazel_USERNAME/5aa6c3674f37090388bbfbf0ef73a503/external/bazel_tools/tools/build_defs/repo/git.bzl", line 234
		_clone_or_update(ctx)
	File "/home/USERNAME/.cache/bazel/_bazel_USERNAME/5aa6c3674f37090388bbfbf0ef73a503/external/bazel_tools/tools/build_defs/repo/git.bzl", line 74, in _clone_or_update
		fail(("error cloning %s:\n%s" % (ctx....)))
error cloning io_bazel_rules_docker:
+ cd /home/USERNAME/.cache/bazel/_bazel_USERNAME/5aa6c3674f37090388bbfbf0ef73a503/external
+ rm -rf /home/USERNAME/.cache/bazel/_bazel_USERNAME/5aa6c3674f37090388bbfbf0ef73a503/external/io_bazel_rules_docker /home/USERNAME/.cache/bazel/_bazel_USERNAME/5aa6c3674f37090388bbfbf0ef73a503/external/io_bazel_rules_docker
+ git clone '' https://github.com/bazelbuild/rules_docker.git /home/USERNAME/.cache/bazel/_bazel_USERNAME/5aa6c3674f37090388bbfbf0ef73a503/external/io_bazel_rules_docker
Too many arguments.

usage: git clone [options] [--] <repo> [<dir>]

    -v, --verbose         be more verbose
    -q, --quiet           be more quiet
    --progress            force progress reporting
    -n, --no-checkout     don't create a checkout
    --bare                create a bare repository
    --mirror              create a mirror repository (implies bare)
    -l, --local           to clone from a local repository
    --no-hardlinks        don't use local hardlinks, always copy
    -s, --shared          setup as shared repository
    --recursive           initialize submodules in the clone
    --recurse-submodules  initialize submodules in the clone
    --template <template-directory>
                          directory from which templates will be used
    --reference <repo>    reference repository
    -o, --origin <name>   use <name> instead of 'origin' to track upstream
    -b, --branch <branch>
                          checkout <branch> instead of the remote's HEAD
    -u, --upload-pack <path>
                          path to git-upload-pack on the remote
    --depth <depth>       create a shallow clone of that depth
    --single-branch       clone only one branch, HEAD or --branch
    --separate-git-dir <gitdir>
                          separate git dir from working tree
    -c, --config <key=value>
                          set config inside the new repository

+ git clone https://github.com/bazelbuild/rules_docker.git /home/USERNAME/.cache/bazel/_bazel_USERNAME/5aa6c3674f37090388bbfbf0ef73a503/external/io_bazel_rules_docker
+ git -C /home/USERNAME/.cache/bazel/_bazel_USERNAME/5aa6c3674f37090388bbfbf0ef73a503/external/io_bazel_rules_docker reset --hard 251f6a68b439744094faff800cd029798edf9faa
Unknown option: -C
usage: git [--version] [--help] [-c name=value]
           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]
           [-p|--paginate|--no-pager] [--no-replace-objects] [--bare]
           [--git-dir=<path>] [--work-tree=<path>] [--namespace=<name>]
           <command> [<args>]
+ git -C /home/USERNAME/.cache/bazel/_bazel_USERNAME/5aa6c3674f37090388bbfbf0ef73a503/external/io_bazel_rules_docker fetch '' origin 251f6a68b439744094faff800cd029798edf9faa:251f6a68b439744094faff800cd029798edf9faa
Unknown option: -C
usage: git [--version] [--help] [-c name=value]
           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]
           [-p|--paginate|--no-pager] [--no-replace-objects] [--bare]
           [--git-dir=<path>] [--work-tree=<path>] [--namespace=<name>]
           <command> [<args>]
+ git -C /home/USERNAME/.cache/bazel/_bazel_USERNAME/5aa6c3674f37090388bbfbf0ef73a503/external/io_bazel_rules_docker fetch origin 251f6a68b439744094faff800cd029798edf9faa:251f6a68b439744094faff800cd029798edf9faa
Unknown option: -C
usage: git [--version] [--help] [-c name=value]
           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]
           [-p|--paginate|--no-pager] [--no-replace-objects] [--bare]
           [--git-dir=<path>] [--work-tree=<path>] [--namespace=<name>]
           <command> [<args>]
INFO: Elapsed time: 5.267s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)

**Comment by odinsbane** [comment]
PART 2: After modifying the WORKSPACE to include the following:
 
 
```
  # Download the rules_docker repository at release v0.14.1
  http_archive(
      name = "io_bazel_rules_docker",
      sha256 = "dc97fccceacd4c6be14e800b2a00693d5e8d07f69ee187babfd04a80a9f8e250",
      strip_prefix = "rules_docker-0.14.1",
      urls = ["https://github.com/bazelbuild/rules_docker/releases/download/v0.14.1/rules_docker-v0.14.1.tar.gz"],
 )

``` 
 Then the building gets started:
 
     vi WORKSPACE 
     bazel build --config=opt --config=cuda //tensorflow/tools/pip_package:build_pip_package

**Comment by odinsbane** [comment]
It makes it through over 20K jobs before failing. You can see from the log that it is using the -std=c++14, which is not supported in gcc 4.8.

Also, the reference you have provided doesn't say anything about tensorflow 1.15

[build-log.txt](https://github.com/tensorflow/tensorflow/files/4230238/build-log.txt)

**Comment by odinsbane** [comment]
It looks like mlir was made to require c++14 which is not compatible with gcc 4.8.

https://github.com/tensorflow/tensorflow/commits/r1.15/third_party/mlir/CMakeLists.txt

It sounds like there is a way to disable mlir, but I do not understand how.

**Comment by ashahba** [comment]
I ran into this one while working on this PR: https://github.com/tensorflow/ngraph-bridge/pull/456 and for now I'm sticking with `GCC 5.3` and newer.
I spend way too much time trying to figure out building with `GCC 4.8.5` and gave up for now 😒

**Comment by Saduf2019** [comment]
@odinsbane please let us know if above comment helps

**Comment by odinsbane** [comment]
@Saduf2019 it pretty much says that tensorflow 1.15 is not compatible with
gcc 4.8.5. I think the docs should be updated to reflect that. The tested
page, https://www.tensorflow.org/install/source#tested_build_configurations
that you referenced,  should have a tested tf 1.15 and say the accepted gcc
to use.

Centos7 still uses 4.8.5 by default, and it would be good to know either
stick with tf 1.14 or upgrade gcc for tf 1.15. I'm surprised tf 1.15 should
change the gcc requirement, since it appears to be a legacy version.

**Comment by odinsbane** [comment]
I think this is just a form of discouragement from using tensorflow 1.x. Compatibility has been broken, so one would need to use tensorflow 1.14, where they do not backport or provide fixes because it is outdated.

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.
