### ISSUE TITLE
Feature Request: Pickle an entire model.

### ISSUE THREAD

**Issue by NEGU93** [tensorflow/tensorflow#36897]
**System information** 
TensorFlow version 2.0.0

**Describe the current behavior**
This request follows the issue [#33204](https://github.com/tensorflow/tensorflow/issues/33283).
When trying to pickle a model to save its current state I get the error: `TypeError: can't pickle _thread._local objects`. Even when doing a low-level code and just trying to save keras layers it gets the same error message.

**Describe the expected behavior**
It would be nice to be able to save models with pickle.
Pickling the entire model object is easier than saving just the weights. Especially for complex models with multiple networks involved. It is very convenient as long as it does not introduce performance issues.

A potential current fix can be [this](https://github.com/tensorflow/tensorflow/issues/33283#issuecomment-561772070) for the moment.

**Code to reproduce the issue** 
The problem can be reproduced with this [gist](https://colab.research.google.com/gist/gadagashwini/079ecb24dcfb0130a41c4cc8f7a69aba/untitled209.ipynb).

**Comment by luozhouyang** [comment]
I think the recommend way to save a model is saving it in `Checkpoints` or `SavedModel` format.

[Traning checkpint](https://www.tensorflow.org/guide/checkpoint)

**Comment by NEGU93** [comment]
I agree it is the recommended way. In my particular case I did my own model using keras layers and that's why I said:

>  Even when doing a low-level code and just trying to save keras layers it gets the same error message.

So this way does not apply to my case and therefore I wanted to use pickle.

**Comment by kyleabeauchamp** [comment]
Another use case of being able to pickle is to support `KerasClassifier` objects, which may be useful for folks using sklearn pipelines or sklearn grid search capabilities.

**Comment by ryq99** [comment]
Since keras model can be pickled, if one could take some compromise and using tensorflow and keras together, here might be one of the roundabouts:

Situation: say we have a model built and trained with tensorflow, we want it to be pickled:
1. we get model weights 
      a. use `ModelCheckpoint(save_weigths_only=True)` to save model weights
      b. use `model.layer[i].get_weights()` to get the weights for each layer
2. build a duplicate model (model_keras) structure with keras not tf.keras
3. pass the model weights into model_keras 
      a. use `model_keras.load_weights()`
      b. ```
for i, layer in enumerate(model_keras.layers):
            weights = model.layer[i].get_weights()
            layer.set_weights(weights)
```

**Comment by saikumarchalla** [comment]
@NEGU93  Is it still an issue for you?. Please go ahead and close the issue if it was resolved already.Thanks!

**Comment by mihaimaruseac** [comment]
See https://github.com/tensorflow/community/pull/286

**Comment by rmothukuru** [comment]
@NEGU93,
Sorry for the delayed response. Can you please let us know if we can close this issue as the [associated PR](https://github.com/tensorflow/community/pull/286) has been merged? Thanks!

**Comment by NEGU93** [comment]
Yes sorry. You can choose it now.
