### ISSUE TITLE
How does the frozen model for speech recognition has been created?

### ISSUE THREAD

**Issue by vihari1729** [tensorflow/tensorflow#36890]
After following the steps train.py and freeze.py from "https://github.com/tensorflow/docs/blob/master/site/en/r1/tutorials/sequences/audio_recognition.md", The inputs of my frozen model(https://imgur.com/a/JtNVkHw) is quite different from the actual frozen model conv_actions_frozen.pb(https://imgur.com/a/KJXExbV). What changes should I make to get the original frozen model for speech recognition?. 
My Python version is 3.7.3 and Tensor flow version is 2.1.0

**Comment by vihari1729** [comment]
@erksch Kindly go through the question

**Comment by erksch** [comment]
Hey @vihari1729 
I will try to give a detailed walkthrough (if I remember :D).
I am a little bit occupied at the moment but will try to do it today or tomorrow.

**Comment by vihari1729** [comment]
> Hey @vihari1729
> I will try to give a detailed walkthrough (if I remember :D).
> I am a little bit occupied at the moment but will try to do it today or tomorrow.

@erksch Thanks for the reply. From the tutorial i suspect something need to change in freeze.py. Because in the [netron](https://lutzroeder.github.io/netron/) the structure of the model is changing after the creation of frozen(.pb) model.

**Comment by erksch** [comment]
I have the exact same differences in the models on the Netron view, but honestly, it works nonetheless in my case. Have you tried using the model anyway?

**Comment by erksch** [comment]
Those are the commands / code I use for freezing and converting to tflite which results in a working model that I can run on android.

Freezing:
```
python freeze.py \
--start_checkpoint=/path/to/checkpoint \
--output_file=/tmp/frozen_graph.pb \
--data_url='' \
--data_dir=<path to data> \
--wanted_words=<comma separated list of wanted words>
```
freeze.py from [here](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/examples/speech_commands/freeze.py).

Converting to tflite:
```python
converter = TFLiteConverter.from_frozen_graph(
    'path/to/frozen_graph.pb', 
    input_arrays=['decoded_sample_data', 'decoded_sample_data:1'], 
    output_arrays=['labels_softmax'])

converter.allow_custom_ops=True
model = converter.convert()
open('model.tflite', 'wb').write(model)
```

**Comment by vihari1729** [comment]
@erksch After following the steps my tflite model looks like [this](https://lutzroeder.github.io/netron/).When I am opening it in android studio by copying it into assets folder the app is getting crashed and not opening.

**Comment by erksch** [comment]
That's just a link to Netron. Can you post an imgur link? :)

**Comment by vihari1729** [comment]
@erksch Sorry for that.The frozen model which I [got](https://imgur.com/a/JtNVkHw), when converted to tflite model it looks like [this](https://imgur.com/a/uceoHlo), where as the Official frozen [model ](https://imgur.com/a/KJXExbV) when converted looks like [this](https://imgur.com/a/lWmxl9d).

Yeah, It is getting crashed whenever I am opening the app

**Comment by erksch** [comment]
I think I have the same models. So I guess it is to debug the android application. What are the errors in your logcat?

**Comment by vihari1729** [comment]
@erksch     I am getting this error in logcat while running tflite model in android studio

 java.lang.RuntimeException: Unable to start activity ComponentInfo{com.google.tflite.speechrecognition/com.google.tflite.speechrecognition.MainActivity}: java.lang.IllegalStateException: Internal error: Unexpected failure when preparing tensor allocations: Encountered unresolved custom op: AddV2.
    Node number 4 (AddV2) failed to prepare

**Comment by erksch** [comment]
Hmm okay, I checked my models and they have indeed no AddV2 nodes.
Actually it might be that that's because you are using tensorflow 2.1.0.
Maybe something was changed in that release regarding tflite conversion which breaks the compatibility with the android application. What version of tensorflow lite are you including in your build.gradle on app level? For me it's:

```
implementation 'org.tensorflow:tensorflow-lite:2.0.0'
```

**Comment by vihari1729** [comment]
@erksch First of all Thank you very much, Finally it is working.
But now i did training for 22 variables (12+ zero to nine numbers in the dataset) and freeze it and converted to tflite model.But now when i am running it in android studio, I am getting error like this:

2020-02-26 18:42:46.015 32272-32335/com.google.tflite.speechrecognition E/AndroidRuntime: FATAL EXCEPTION: Thread-3
    Process: com.google.tflite.speechrecognition, PID: 32272
    java.lang.RuntimeException: The results for recognition should contain 12 elements, but there are 22
        at com.google.tflite.speechrecognition.tflite.RecognizeCommands.processLatestResults(RecognizeCommands.kt:65)
        at com.google.tflite.speechrecognition.MainActivity.recognize(MainActivity.kt:287)
        at com.google.tflite.speechrecognition.MainActivity.access$recognize(MainActivity.kt:60)
        at com.google.tflite.speechrecognition.MainActivity$startRecognition$1.run(MainActivity.kt:241)
        at java.lang.Thread.run(Thread.java:764)

For this Do i need to do change anything manually in the MainActivity.kt code or somewhere?
Kindly Waiting for your response

**Comment by erksch** [comment]
There should be a file containing your labels. I think it is namend labels.txt or something in the assets folder of your android studio project. Make sure to add the labels you are using there. And maybe just search for the number 12 if its hard coded somewhere and replace it with 22.

**Comment by vihari1729** [comment]
@erksch I am using Kotlin code in android studio instead of java.I have given the labels.txt which has 22 labels in assets folder and. What i understood is i need to change the labels path both in speechInterpreter and MainActivity. But now the app is running and giving the same 10 labels font [page.](https://imgur.com/a/fNRcn9d), Though i trained with 22 labels.

PS : When i freeze the graph and test the audio files from validation.txt with the command label_wav.py,it is correctly recognising all the 20(+unkown and silence) labels. I also checked the tflite model and the output of labels_softmax showing the shape of the array(1,22)```

**Comment by erksch** [comment]
Great that you have it running!
Yeah now you have to start coding and developing your app :D I have no app ready for you that has a frontpage that is dynamic to the labels. Just try to understand how everthing works and make more fields for the rest of your labels.

**Comment by gowthamkpr** [comment]
Closing this issue as it has been resolved. Please add additional comments and we can open this issue again. Thanks!

**Comment by coolioxlr** [comment]
I follow the exact same step but when I convert to TFLite I got the following error. Any idea? Similar to this issue [https://stackoverflow.com/questions/59443695/different-model-on-speech-recognition](https://stackoverflow.com/questions/59443695/different-model-on-speech-recognition)
---------------------------------------------------------------------------
ConverterError                            Traceback (most recent call last)
<ipython-input-24-92cfb1ecefd4> in <module>()
      8 
      9 converter.allow_custom_ops=True
---> 10 model = converter.convert()
     11 open('models/model.tflite', 'wb').write(model)

2 frames
/usr/local/lib/python3.6/dist-packages/tensorflow/lite/python/convert.py in toco_convert_protos(model_flags_str, toco_flags_str, input_data_str, debug_info_str, enable_mlir_converter)
    225       stdout = _try_convert_to_unicode(stdout)
    226       stderr = _try_convert_to_unicode(stderr)
--> 227       raise ConverterError("See console for info.\n%s\n%s\n" % (stdout, stderr))
    228   finally:
    229     # Must manually cleanup files.

ConverterError: See console for info.
2020-05-09 01:29:04.994909: W tensorflow/compiler/mlir/lite/python/graphdef_to_tfl_flatbuffer.cc:89] Ignored output_format.
2020-05-09 01:29:04.994950: W tensorflow/compiler/mlir/lite/python/graphdef_to_tfl_flatbuffer.cc:95] Ignored drop_control_dependency.
Traceback (most recent call last):
  File "/usr/local/bin/toco_from_protos", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/tensorflow_core/lite/toco/python/toco_from_protos.py", line 93, in main
    app.run(main=execute, argv=[sys.argv[0]] + unparsed)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow_core/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/usr/local/lib/python2.7/dist-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/usr/local/lib/python2.7/dist-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow_core/lite/toco/python/toco_from_protos.py", line 56, in execute
    enable_mlir_converter)
Exception: Input arrays can only have op with single output. Node op:DecodeWav
