### ISSUE TITLE
MNIST Prediction

### ISSUE THREAD

**Issue by wackymaster** [tensorflow/tensorflow#3690]
I used the MNIST-EXPERT.py to create a model by adding this to the end:

`save_path = saver.save(sess, "model.ckpt")  `
`print ("Model saved in file: ", save_path)`

Now that I have saved a model, how do I give it a picture of handwriting so it can figure it out?

Thanks

**Comment by girving** [comment]
This should be asked on StackOverflow, since it is not an issue in TensorFlow requiring improvement.
