### ISSUE TITLE
tensorflow.python.ops.linalg.sparse.matmul crashes when inputs have different rank, but only if either is a CSRSparseMatrix

### ISSUE THREAD

**Issue by danielegrattarola** [tensorflow/tensorflow#36911]
**System information** 
- Have I written custom code: yes
- OS Platform and Distribution: Linux Ubuntu 16.04 
- TensorFlow installed from: binary
- TensorFlow version (use command below): v2.1.0-rc2-17-ge5bf8de 2.1.0
- Python version: 3.7.5
- CUDA/cuDNN version: 10.2/7.6.4
- GPU model and memory: Nvidia GeForce GTX 1050 4GB

**Describe the current behavior**
`tensorflow.python.ops.linalg.sparse.matmul` works for dense inputs of rank 2 and 3, or 3 and 2, but crashes if either of the inputs is a `CSRSparseMatrix`.

**Describe the expected behavior**
`tensorflow.python.ops.linalg.sparse.matmul` works for inputs of rank 2/3, or 3/2, and for any combination of dense/sparse inputs.

**Code to reproduce the issue**

```python
import numpy as np
from tensorflow.python.ops.linalg.sparse import sparse as tfsp

a = np.ones((3, 3))
b = np.ones((5, 3, 3))
a_sp = tfsp.CSRSparseMatrix(a)
b_sp = tfsp.CSRSparseMatrix(b)

# This works fine
output = tfsp.matmul(a, b)
print(output.shape)

# These crash
output_sp = tfsp.matmul(a_sp, b)
output_sp = tfsp.matmul(a, b_sp)
output_sp = tfsp.matmul(a_sp, b_sp)
```

**Other info / logs** 

If only one of the two inputs is sparse, the stack trace looks like this: 

```
2020-02-19 18:51:52.547579: W tensorflow/core/framework/op_kernel.cc:1655] OP_REQUIRES failed at mat_mul_op.cc:507 : Invalid argument: Ranks of a and b must match, saw: 0x7ffc085957fc vs. 3.
---------------------------------------------------------------------------
InvalidArgumentError                      Traceback (most recent call last)
<ipython-input-5-256f5bb49d4d> in <module>
----> 1 output_sp = tfsp.matmul(a_sp, b)

~/dev/tf2/lib/python3.7/site-packages/tensorflow_core/python/ops/linalg/sparse/sparse_csr_matrix_ops.py in matmul(a, b, transpose_a, transpose_b, adjoint_a, adjoint_b, name)
    220           transpose_b=transpose_b,
    221           adjoint_a=adjoint_a,
--> 222           adjoint_b=adjoint_b)
    223     else:
    224       # opA(A) . opB(B) = t(nopB(B) . nopA(A))

~/dev/tf2/lib/python3.7/site-packages/tensorflow_core/python/ops/linalg/sparse/gen_sparse_csr_matrix_ops.py in sparse_matrix_mat_mul(a, b, transpose_a, transpose_b, adjoint_a, adjoint_b, transpose_output, conjugate_output, name)
    480         raise
    481     except _core._NotOkStatusException as e:
--> 482       _ops.raise_from_not_ok_status(e, name)
    483   # Add nodes to the TensorFlow graph.
    484   if transpose_a is None:

~/dev/tf2/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py in raise_from_not_ok_status(e, name)
   6604   message = e.message + (" name: " + name if name is not None else "")
   6605   # pylint: disable=protected-access
-> 6606   six.raise_from(core._status_to_exception(e.code, message), None)
   6607   # pylint: enable=protected-access
   6608 

~/dev/tf2/lib/python3.7/site-packages/six.py in raise_from(value, from_value)

InvalidArgumentError: Ranks of a and b must match, saw: 0x7ffc085957fc vs. 3. [Op:SparseMatrixMatMul]

```

If both inputs are sparse:

```
---------------------------------------------------------------------------
InvalidArgumentError                      Traceback (most recent call last)
<ipython-input-4-9a25f9aa5868> in <module>
----> 1 output_sp = tfsp.matmul(a_sp, b_sp)

~/dev/tf2/lib/python3.7/site-packages/tensorflow_core/python/ops/linalg/sparse/sparse_csr_matrix_ops.py in matmul(a, b, transpose_a, transpose_b, adjoint_a, adjoint_b, name)
    204           adjoint_a=adjoint_a,
    205           adjoint_b=adjoint_b,
--> 206           type=a.dtype)
    207 
    208       # In eager mode, shape inference functions are not called, and the output

~/dev/tf2/lib/python3.7/site-packages/tensorflow_core/python/ops/linalg/sparse/gen_sparse_csr_matrix_ops.py in sparse_matrix_sparse_mat_mul(a, b, type, transpose_a, transpose_b, adjoint_a, adjoint_b, name)
   1281         raise
   1282     except _core._NotOkStatusException as e:
-> 1283       _ops.raise_from_not_ok_status(e, name)
   1284   # Add nodes to the TensorFlow graph.
   1285   type = _execute.make_type(type, "type")

~/dev/tf2/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py in raise_from_not_ok_status(e, name)
   6604   message = e.message + (" name: " + name if name is not None else "")
   6605   # pylint: disable=protected-access
-> 6606   six.raise_from(core._status_to_exception(e.code, message), None)
   6607   # pylint: enable=protected-access
   6608 

~/dev/tf2/lib/python3.7/site-packages/six.py in raise_from(value, from_value)

InvalidArgumentError: Inner product dimensions of A and B do not agree.  Shapes are: [3,3] vs. [5,3,3] [Op:SparseMatrixSparseMatMul]

```

**Comment by danielegrattarola** [comment]
The issue is related to `SparseMatrixMatMul` if only one of the inputs is sparse, and `SparseMatrixSparseMatMul` if both are sparse.
Looking at the code it seems that `tfsp.matmul` is basically a switch to decide which op to use, so maybe this should be changed as a feature request?
I opened it as a bug because the documentation does not specify any restrictions on the inputs.

**Comment by amahendrakar** [comment]
Was able to reproduce the issue with TF 2.1 and TF nightly. Please find the Gist [here](https://colab.sandbox.google.com/gist/amahendrakar/098f60ba73339d773791c538b7fdea14/36911.ipynb). Thanks!

**Comment by sachinprasadhs** [comment]
Was able to reproduce your issue in Tf Nightly 2.6.0-dev20210524, please find the gist [here](https://colab.research.google.com/gist/sachinprasadhs/f50c5417320b7e0d488fc084e14cd738/35650.ipynb). Thanks!

**Comment by Venkat6871** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
