### ISSUE TITLE
Using trademarked word "TensorFlow" in the name of a C# binding

### ISSUE THREAD

**Issue by lostmsu** [tensorflow/tensorflow#36918]
My company is developing a proprietary TensorFlow binding for .NET called [Gradient](https://losttech.software/gradient.html). We are considering to rename it to clearly indicate, that it is designed to work with TensorFlow: into `CompanyName.TensorFlow`. I could not find any information if it is OK to use `TensorFlow` as part of the name in such manner. We will correctly only refer to Google as the owner of the trademark as requested in the [Brand Guidelines](https://www.tensorflow.org/extras/tensorflow_brand_guidelines.pdf).

**Comment by ewilderj** [comment]
We'll get you an answer here. => @theadactyl

**Comment by ewilderj** [comment]
(OK there is a very annoying bug in the assignee UI, sorry for the noise)

**Comment by martinwicke** [comment]
What is the "CompanyName." part of the name here?

**Comment by ewilderj** [comment]
(I'm seeking advice on the answer to this, btw, sorry for the delay.)
cc/ @theadactyl

**Comment by lostmsu** [comment]
@martinwicke [Lost Tech](https://losttech.software/gradient.html). Based in Bellevue.

**Comment by ewilderj** [comment]
This usage is fine.  We ask for attribution in our brand guidelines, so please note that "TensorFlow is a trademark of Google LLC"  in your documentation.
