### ISSUE TITLE
how to install tensorflow in python 3.7.2 in 32 bit system

### ISSUE THREAD

**Issue by ravikanth076** [tensorflow/tensorflow#36923]
hi....
 im trying to install tensorflow and keras for my project execution. Im able to install keras. But im unable to install tensorflow. 
can any one please tell me?

**Comment by ravikyram** [comment]
@ravikanth076 

Can you please follow the instructions to install tensorflow from [here](https://www.tensorflow.org/install).Please, follow the instructions based on your OS and let us know how it progresses. Thanks!

**Comment by ravikanth076** [comment]
is there any other alternate  method to install Tensorflow? because i have this system only....
please help me..

**Comment by ravikanth076** [comment]
is there any alternate method to do this? because i have only this system...

**Comment by ravikyram** [comment]
@ravikanth076 
Please use colab to import tensorflow on 32 bit machine. Thanks!

**Comment by ravikyram** [comment]
I am closing the issue since the query is been answered. Thanks!
