### ISSUE TITLE
if GPU available, raise Exception "Cholesky decomposition was not successful. The input might not be valid" ,otherwise, in CPU mode, The Official Unittest is ok

### ISSUE THREAD

**Issue by gjpicker** [tensorflow/tensorflow#36928]
**System information** 
- Have I written custom code (as opposed to using a stock
example script provided in TensorFlow):  No
- OS Platform and Distribution (e.g.,
Linux Ubuntu 16.04): Linux Ubuntu 16.04
- TensorFlow installed from (source or
binary):  pip install tensorflow-gpu==1.15.0

[tf_env.txt](https://github.com/tensorflow/tensorflow/files/4230518/tf_env.txt)

```
python -c "import tensorflow as tf ;print (tf.__version__)"
1.15.0
```
```
python -c "import tensorflow as tf ;print ( tf.test.gpu_device_name())"  

 Found device 0 with properties: 
name: Tesla V100-SXM2-32GB major: 7 minor: 0 memoryClockRate(GHz): 1.53

Created TensorFlow device (/device:GPU:0 with 30555 MB memory) -> physical GPU (device: 0, name: Tesla V100-SXM2-32GB, pci bus id: 0000:8a:00.0, compute capability: 7.0)
```

**Describe the current behavior**
```
CUDA_VISIBLE_DEVICES=-1 python gmm_test.py  GMMTest.test_fit
ok!
```
```
CUDA_VISIBLE_DEVICES=0 python gmm_test.py  GMMTest.test_fit

error:Original stack trace for 'Cholesky': 
```

**Describe the expected behavior**
expect  The Official code([gem_test.py](https://github.com/tensorflow/tensorflow/blob/r1.15/tensorflow/contrib/factorization/python/ops/gmm_test.py)) should  pass  the Unit-test in GPU mode
```
CUDA_VISIBLE_DEVICES=0 python gmm_test.py  GMMTest.test_fit
ok!
```
**Standalone code to reproduce the issue** 
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.
```
wget https://raw.githubusercontent.com/tensorflow/tensorflow/r1.15/tensorflow/contrib/factorization/python/ops/gmm_test.py -O "gmm_test.py"

CUDA_VISIBLE_DEVICES=0 python gmm_test.py  GMMTest.test_fit

```

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.
[python_trace_err.log ](https://github.com/tensorflow/tensorflow/files/4230533/python_trace_err.log), which is python back_trace info

**Comment by jornbowrl** [comment]
+1 may this problem be focued

**Comment by agarwal-ashish** [comment]
FWIW, see https://github.com/GPflow/GPflow/issues/553 for similar discussion.

**Comment by gjpicker** [comment]
close ,as GPflow instead of

**Comment by gjpicker** [comment]
close ,as GPflow instead of
