### ISSUE TITLE
Bazel build cannot access private member.. windows

### ISSUE THREAD

**Issue by kitepro** [tensorflow/tensorflow#36931]
Im trying to build tensorflow from source on windows 10
I cant use pip install tensorflow coz i want to add user_ops in the build.
(Please let me know if that is possible any other way than source build)

------------------------------------------------------------------------

So I'm using these for build:
      Python = 3.7.6
      TF = Currently On Github (2/20/20)
      Bazel = 2.0.0
      MSVC = 14.15.26726 (VS 2017)
      Windows 10
      AMD Ryzen 1700
      CPU Build

During configuration, I selected:
      JIT = Yes
      ROCM = No
      CUDA = No
      Eigen overrides = No

------------------------------------------------------------------------

I get different errors every single time I run this build.
I did follow every single step on the https://www.tensorflow.org/install/source_windows#configure_the_build

Everytime, it says it cant access some private member from some class.
Here I got class ThreadPool, sometimes its TraceMe, sometimes something else I dont remember.
Its different everytime.
This is after 5-10min into build so the entire trace is huge.
I'll just put the ERROR part in here.

HELPPPPPPPPP........ I need user_ops....

```
**ERROR: D:/production/tensorflow-master/tensorflow/compiler/xla/BUILD:411:1: C++ compilation of rule '//tensorflow/compiler/xla:literal' failed (Exit 2)
external/com_google_absl\absl/meta/type_traits.h(121): error C2248: 'tensorflow::thread::ThreadPool::operator =': cannot access private member declared in class 'tensorflow::thread::ThreadPool'**

.\tensorflow/core/platform/threadpool.h(237): note: see declaration of 'tensorflow::thread::ThreadPool::operator ='
.\tensorflow/core/platform/threadpool.h(42): note: see declaration of 'tensorflow::thread::ThreadPool'
external/com_google_absl\absl/meta/type_traits.h(150): note: see reference to class template instantiation 'absl::type_traits_internal::is_detected<absl::type_traits_internal::IsCopyAssignableImpl,T>' being compiled
        with
        [
            T=tensorflow::thread::ThreadPool
        ]
external/com_google_absl\absl/meta/type_traits.h(430): note: see reference to class template instantiation 'absl::is_copy_assignable<T>' being compiled
        with
        [
            T=tensorflow::thread::ThreadPool
        ]

..
..
..

Target //tensorflow/tools/pip_package:build_pip_package failed to build
INFO: Elapsed time: 1058.548s, Critical Path: 969.86s
INFO: 2855 processes: 2855 local.
FAILED: Build did NOT complete successfully
```

**Comment by amahendrakar** [comment]
@kitepro,
Could you please try building TensorFlow using Bazel version 0.27.1.
Also, if you are using a virtual environment, please check if you have entered the correct Python path while configuring the build. Thanks!

**Comment by amahendrakar** [comment]
Any updates regarding this issue? Thanks!

**Comment by kitepro** [comment]
Oh I forgot...
I did try 0.27.1 didnt work.. same error..
I ended up installing fedora as a dual boot.. worked there..
Closing the issue I guess,
