### ISSUE TITLE
Simpler way to avoid the UserWarning: Converting sparse IndexedSlices

### ISSUE THREAD

**Issue by MayukhSobo** [tensorflow/tensorflow#36948]
I have a rnn network structure that looks like following

        cells = rnn.MultiRNNCell(
            [self._one_rnn_cell(l + 1) for l in range(self.layers)],
            state_is_tuple=True
        ) if self.layers > 1 else self._one_rnn_cell(1)

        out, _ = tf.nn.dynamic_rnn(cells, self.inputs,
                                   dtype=tf.float32, scope="DyRNN")
        out = tf.transpose(out, [1, 0, 2])
        num_time_steps = int(out.get_shape()[0])
        last_state = tf.gather(out, num_time_steps - 1, name="last_lstm_state")

Here while I am running the code, I am getting the following warning.

    UserWarning: Converting sparse IndexedSlices to a dense Tensor of unknown shape. This may consume a large amount of memory. "Converting sparse IndexedSlices to a dense Tensor of unknown shape. "

Now I understand why this error is coming. I tried out several ideas and the most common one is the following

How to deal with UserWarning: Converting sparse IndexedSlices to a dense Tensor of unknown shape

But the problem is this requires too many variable like

max_length time_steps seq_length n_dim partitions

this make the code very unreadable. I wanted to know if there is a simpler way I can avoid the problem.

Also if the sequence length remain same across all the batches, can I assume max_length == time_steps == seq_length ?

Please help, documentation is very less.

**Note:** I added this question in stackoverflow [here](https://stackoverflow.com/questions/60269407/simpler-way-to-avoid-the-userwarning-converting-sparse-indexedslices) but haven't received any replies yet.

**Comment by ravikyram** [comment]
@MayukhSobo 

Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version. 

Please provide the colab link or simple standalone code to reproduce the issue in our environment. It helps us in localizing the issue faster.Request you to fill [the Github new issue template](https://github.com/tensorflow/tensorflow/issues/new/choose). Thanks!

**Comment by MayukhSobo** [comment]
@ravikyram 

Please find the following information about the systems.

**System information** 

- OS Platform and Distribution: Ubuntu 18.04 LTS
- Tensorflow gpu was installed using conda 4.8.2
- Numpy version:     1.18.1  py37h4f9e942_0
- Numpy base:         1.18.1  py37hde5b4d6_1
- Python version: 3.7.5
- `print(tf.GIT_VERSION, tf.VERSION)` gives output as `v1.15.0-rc3-22-g590d6ee 1.15.0`


Here is the code snippet of the model. Due to some legal obligation, I can not share the complete code with you..

```python
def _one_rnn_cell(self, layer):
        """
        This create one RNN cell
        :param layer: Mention the layer number
        :return: LSTM cell with or without dropout
        """

        lstm_cell = rnn.LSTMCell(self.lstm_size,
                                 state_is_tuple=True,
                                 name=f'LSTMCell_layer_{layer}')
        kp = self.keep_prob
        if not self.training:
            print("Setting keep_prob = 1 for testing!!")
            kp = 1.0

        lstm_cell = rnn.DropoutWrapper(lstm_cell,
                                       output_keep_prob=kp)
        return lstm_cell
    def _get_all_placeholders(self):
        # self.learning_rate = tf.placeholder(tf.float32, None,
        #                                     name="learning_rate")
        self.inputs = tf.placeholder(tf.float32,
                                     [None, self.time_steps, self.input_size],
                                     name="inputs")
        self.targets = tf.placeholder(tf.float32, [None, self.input_size],
                                      name="targets")

    def _build_graph(self):
        # First get all the placeholders
        self._get_all_placeholders()

        # Second, create multiple LSTM cells for all the layers
        cells = rnn.MultiRNNCell(
            [self._one_rnn_cell(l + 1) for l in range(self.layers)],
            state_is_tuple=True
        ) if self.layers > 1 else self._one_rnn_cell(1)

        # Wrap the all the cells into an RNN
        # We shall use dynamic_rnn so that
        """
          1. All the cells for each time_steps in the graph 
            is not created while creating the RNN

          2. We can pass more/less than the sequence length.
        """

        # self.inputs = tf.transpose(self.inputs, perm=[1, 0, 2])
        out, states = tf.nn.dynamic_rnn(cells, self.inputs,
                                        dtype=tf.float32, scope="dynamic_rnn",
                                        time_major=False)

        # output[:, ts-1, :]
        # It returns the output of all the time_steps. However we need the
        # output only from the last time step.

        # We could have also wriiten self.time_steps - 1
        # but that would not have been generic.

        # Actual output => (batch_size, num_steps, lstm_size)
        # This converts => (num_steps, batch_size, lstm_size)
        # JUST LIKE THAT!!

        # all_timesteps = tf.reshape(out, [-1, self.lstm_size])
        # row_inds = tf.range(0, 16) * 30 + (30 - 1)
        # partitions = tf.reduce_sum(tf.one_hot(row_inds, tf.shape(all_timesteps)[0], dtype='int32'), 0)
        # last_timesteps = tf.dynamic_partition(all_timesteps, partitions, 2)  # (batch_size, n_dim)
        # last_state = last_timesteps[1]

        out = tf.transpose(out, [1, 0, 2])
        num_time_steps = int(out.get_shape()[0])
        last_state = tf.gather(out, num_time_steps - 1, name="last_lstm_state")

        # last_state = states.h

        # last_state = tf.unstack(outputs, axis=0)
        # last_state = last_state[-1]
        # last_state = tf.transpose(last_state, perm=[0, 1, 2])
        # Now that we've got the last_state, we can add it to a linear layer for Regression.

        with tf.name_scope('Linear'):
            W = LstmRNN._variable_on_device(
                name='l_w',
                shape=(self.lstm_size, self.input_size),
                initializer=tf.truncated_normal_initializer(),
                device=self.device
            )
            bias = LstmRNN._variable_on_device(
                name='l_b',
                shape=(self.input_size,),
                initializer=tf.constant_initializer(0.1),
                device=self.device
            )
            self.pred = tf.add(tf.matmul(last_state, W, name='Wx'),
                               bias, name='output')
```

The problem (UserWarning) apparently is coming from the following lines
```python 
        out = tf.transpose(out, [1, 0, 2])
        num_time_steps = int(out.get_shape()[0])
        last_state = tf.gather(out, num_time_steps - 1, name="last_lstm_state")
```

I can use `tf.dynamic_partition` but that makes the code a lot more unreadable and not easy to follow and more than that I need to pass the `batch_size` before hand which is also a little inconvenient.

I am currently not getting any warning if I write
```python 

last_state = states.h

```
But I am not sure what would happen if the sequence length is not equal to max_length. Is is a good idea to use ```states.h``` all the time?

**Comment by ymodak** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.
Thanks!
