### ISSUE TITLE
assertion "exponent <= 31" failed while executing interpreter->Invoke()

### ISSUE THREAD

**Issue by GlennWasAlreadyTaken** [tensorflow/tensorflow#36943]
@tensorflow/micro

**System information**
- Host OS Platform and Distribution: Windows 10
- TensorFlow installed from binary
- Tensorflow version: TF 2.0.0
- Target platform: M5Stack (ESP32)

**Description of the problem:**

I'm working on a CNN model that tries to detect a situation that occurs to patient with Parkinson disease. Based on accelerometers values, I try to detect the appearance of this situation with a CNN.
I trained a model with the Python version of TF, and I converted the model into a .tflite file that I'm using to put the model on a M5Stack microcontroller.

When I execute a basic program consisting in giving an input to my model on the microcontroller, this error is sent through the serial monitor:

> assertion "exponent <= 31" failed: file "lib\tfmicro/fixedpoint/fixedpoint.h", line 359, function: IntegerType gemmlowp::RoundingDivideByPOT(IntegerType, int) [with IntegerType = int]

It seems to happen when the "interpreter->Invoke()" part of the code is executed. 

**How I ran into the problem:**

The code in which I'm using the model on the microcontroller is based the the helloworld example. I'm simply just creating a sample user input, loading the model, and trying to invoke the interpreter on the sample data, but I get the "assertion failed" error.

I'm getting the error when the following part of the code is executed:
```cpp
if (interpreter->Invoke() != kTfLiteOk)
{
    M5.Lcd.println("There was an error invoking the interpreter!");
    return;
}
```
On this code, the message is not even printed, the "assertion failed" comes from the execution of *interpreter->Invoke()*.
This error makes my microcontroller reboot, again and again.

The repository https://github.com/GlennWasAlreadyTaken/CNN_M5Stack contains my whole project. 
In the cnn folder, you'll find the Python script I made for the training of the model and conversion to tflite file. You'll also find the weights (.h5), and the converted file (tflite) and the C array (.cc).
The M5StackCNN folder contains the code for the microcontroller, that should run the model. I use Platformio in order to deploy the program on the M5Stack.
You'll find the main code for the microcontroller in M5StackCNN/src/main.cpp.

Thank you in advance.

**Comment by GlennWasAlreadyTaken** [comment]
**Possible solution to the problem:**

I was helped by an engineer of the TFLite team. 
The problem may come from the model, which might be a hybrid model, not supported by TFLite.
One solution would be to make the model *Fully quantized*, which I tried. However, I'm still facing difficulties:

When converting the model to a tflite model, I was told to use the following converter optimization:
`converter.optimizations = [tf.lite.Optimize.TFLITE_BUILTINS_INT8]`

However, it seems like tf.lite.Optimize does not have any attribute named TFLITE_BUILTINS_INT8, as I'm getting an *AttributeError* when trying to use it.

I saw that tf.lit.OpsSet had an attribute named TFLITE_BUILTINS_INT8. Hence, I decided to remplace the line by `converter.optimizations = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]`, knowing that this was probably not the good solution, but I just wanted to try in case it could work (actually, I discovered that it didn't call the representative dataset function, so I'm pretty sure this is not the good solution). And actually, it produced a tflite file. I tried to test it but the .cc file I generated from it was to heavy for the microcontroller I'm using, so in order to test I would need to re-train the model (which can be long so I didn't try this).
In order to reduce the size file, I decided to add the optimization "OPTIMIZE_FOR_SIZE", thinking that it would help. However, I get another error in the script, which is the following:

> ValueError: Cannot set tensor: Got tensor of type *INT32* but expected type FLOAT32 for input 1, name: conv2d_18_input

It seems like this error appear when trying to use the representative dataset. By looking at my script, I remembered this line I wrote when collecting the sample data used in the representative dataset:

`# Cutting the line into array of values
str_values = line.split()
values = [[int(nb)] for nb in str_values]`

So, naturally, I changed the int cast to a float cast, thinking it would come from that. I get the exact same error, except for the element in bold:

> ValueError: Cannot set tensor: Got tensor of type NOTYPE but expected type FLOAT32 for input 1, name: conv2d_18_input 

The error seems very weird, as the only thing I changed was that cast in the collection of the sample values. Could it come from the fact that I didn't change it in the collection of the training data and validation data?

The generated .tflite and .cc files are available on my github repository (https://github.com/GlennWasAlreadyTaken/CNN_M5Stack, in cnn/ folder). The code trying to make a fully quantized conversion into tflite is also available, in the .ipynb file in the same folder.

**Comment by MeghnaNatraj** [comment]
I noticed that the inputs to the model are supplied as a list of arrays without any type.
Update this to:
`all_data = np.array(all_data, dtype=np.float32)`
Similarly update the validation and test datasets and try again.

----------------------------------------

The optimization which you used is correct: `converter.optimizations = [tf.lite.Optimize.TFLITE_BUILTINS_INT8]`. I was referring to this one when I said `TFLITE_BUILTINS_INT8` -- sorry for not specifying it in detail.

However, with further clarification from my team -- I've realized that it's best if you use
`converter.optimizations = [tf.lite.Optimize.DEFAULT]` and NOT `tf.lite.Optimize.TFLITE_BUILTINS_INT8`. Instead, optimize as follows: 

```
import tensorflow as tf

def representative_dataset_gen():
  for _ in range(num_calibration_steps):
    # Get sample input data as a numpy array in a method of your choosing.
    yield [input]

converter = tf.lite.TFLiteConverter.from_saved_model(saved_model_dir)
converter.optimizations = [tf.lite.Optimize.DEFAULT]
converter.representative_dataset = representative_dataset_gen
tflite_quant_model = converter.convert()
```

You **need** to provide a representative dataset to ensure that the model is quantized correctly.  On doing this, the model will have float inputs and outputs and rest of the model would be int8 quantized. As you're using TF2.0, use this model as is and pass float values to the model in your interpreter code as well (which I think you've already done)

**Comment by vdouet** [comment]
I seem to have the same problem when using optimizations. My issue #36914 seems to be related to this one.

**Comment by MeghnaNatraj** [comment]
@GlennWasAlreadyTaken seems like the issue could be with the Interpreter as another user (refer to the post above) is also facing this, apologies if so! I will get back to both these issues once I look into this further.

**Comment by GlennWasAlreadyTaken** [comment]
@MeghnaNatraj I made the changes you suggested, and I think I have managed to make the model quantized correctly, as I got a tflite file produced with no error. However, I'm facing another error while allocating the tensors to the memory pool in the microcontroller code:

> Didn't find op for builtin opcode 'DEPTHWISE_CONV_2D' version '3'
> 
> Failed to gt registration from op code  d
> 
> Guru Meditation Error: Core  1 panic'ed (LoadProhibited). Exception was unhandled.

By looking to the error, it also seems related to #36914 when trying to use a representative dataset.
I've updated my training script code and tflite model on my repository.

**Comment by MeghnaNatraj** [comment]
@GlennWasAlreadyTaken Thanks for the update! The correct way to fully integer quantize a model is given here: https://www.tensorflow.org/lite/performance/post_training_quantization#integer_only
```
# Convert a Tensorflow Model to a TFLite Fully Integer Quantized Model
import tensorflow as tf
converter = tf.lite.TFLiteConverter.from_saved_model(saved_model_dir)
converter.optimizations = [tf.lite.Optimize.DEFAULT]
def representative_dataset_gen():
  for _ in range(num_calibration_steps):
    # Get sample input data as a numpy array in a method of your choosing.
    yield [input]
converter.representative_dataset = representative_dataset_gen
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
converter.inference_input_type = tf.int8  # or tf.uint8
converter.inference_output_type = tf.int8  # or tf.uint8
tflite_quant_model = converter.convert()
```

The basic TFLite Micro example, i.e, the [hello world example](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/micro/examples/hello_world/) has been updated as well:

- [hello world training README](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/micro/examples/hello_world/train) 
- [hello world training using Google Colab](https://colab.sandbox.google.com/github/tensorflow/tensorflow/blob/master/tensorflow/lite/micro/examples/hello_world/train/train_hello_world_model.ipynb) The colab uses the updated post training quantization steps, so either resources should be a good point to refer back to.
