### ISSUE TITLE
ImportError after installing 2.1.0 on OSX Catalina 10.15.2 (From binary and source)

### ISSUE THREAD

**Issue by nicholascannon1** [tensorflow/tensorflow#36945]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Mac OSX Catalina 10.15.2
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): Binary AND source
- TensorFlow version: 2.1.0 (switched to branch r2.1.0)
- Python version: 3.7.6
- Installed using virtualenv? pip? conda?: pip (pip3 on my system)
- Bazel version (if compiling from source): 2.1.0
- GCC/Compiler version (if compiling from source): Apple clang version 11.0.0 (clang-1100.0.33.17)
- CUDA/cuDNN version:
- GPU model and memory: Intel UHD (using MacBookPro GPU not compatible)

**Describe the problem**
After successfully installing Tensorflow via pip or compiling Tensorflow from source, importing the Tensorflow2.1.0 package fails with the error below on OSX Catalina 10.15.2 (CPU = 2.6 GHz 6-Core Intel Core i7). Running `pip install tensorflow==2.0.0` works fine. I've tried installing `pywrap` with `pip3 install pywrap` but this does not fix the issue.

**Provide the exact sequence of commands / steps that you executed before running into the problem**
PIP instructions:
1. `pip3 install tensorflow` (Tried `--user`, `--upgrade` and installing with `pip` as well)
2. `python3`
3. `>>> import tensorflow as tf`

Compilation instructions:
1. `git clone https://github.com/tensorflow/tensorflow.git & cd tensorflow`
2. `git checkout branch_name r2.1.0`
3. `./configure` setting python version as `/usr/local/bin/python3` and everything else as defaults
4.  `bazel build //tensorflow/tools/pip_package:build_pip_package`
5. `./bazel-bin/tensorflow/tools/pip_package/build_pip_package /tmp/tensorflow_pkg`
6. `pip install /tmp/tensorflow_pkg/tensorflow-2.1.0-cp37-cp37m-macosx_10_15_x86_64.whl`
7. `python3`
8. `>>> import tensorflow`

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

ERROR PRODUCED:
```
>>> import tensorflow as tf
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/tensorflow/__init__.py", line 101, in <module>
    from tensorflow_core import *
  File "/usr/local/lib/python3.7/site-packages/tensorflow_core/__init__.py", line 40, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "/usr/local/lib/python3.7/site-packages/tensorflow/__init__.py", line 50, in __getattr__
    module = self._load()
  File "/usr/local/lib/python3.7/site-packages/tensorflow/__init__.py", line 44, in _load
    module = _importlib.import_module(self.__name__)
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/usr/local/lib/python3.7/site-packages/tensorflow_core/python/__init__.py", line 50, in <module>
    from tensorflow.python import _pywrap_utils
ImportError: dlopen(/usr/local/lib/python3.7/site-packages/tensorflow_core/python/_pywrap_utils.so, 2): Symbol not found: __ZN10tensorflow4swig10IsSequenceEP7_object
  Referenced from: /usr/local/lib/python3.7/site-packages/tensorflow_core/python/_pywrap_utils.so
  Expected in: flat namespace
 in /usr/local/lib/python3.7/site-packages/tensorflow_core/python/_pywrap_utils.so
```

**Comment by av8ramit** [comment]
This seems like a linking issue (potentially system specific). `_pywrap_utils.so` links to `pywrap_tensorflow_internal.so`. `__ZN10tensorflow4swig10IsSequenceEP7_object`'s implementation is defined in the `cpp_python_util` target in `pywrap_tensorflow_internal.so`. Just for reference here is how we build our binaries from source for MacOS: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/ci_build/release/macos/cpu_py37_full/nightly_release.sh#L41-L49

Is there any chance you can try the MacOS pip package for 2.1 and see if the issue still persists?

**Comment by av8ramit** [comment]
Unfortunately unable to reproduce on Catalina 10.15.3.

```
$ python3 --version
Python 3.7.6
$ clang --version
Apple clang version 11.0.0 (clang-1100.0.33.17)
Target: x86_64-apple-darwin19.3.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
$ python3
Python 3.7.6 (default, Feb 22 2020, 07:58:28) 
[Clang 11.0.0 (clang-1100.0.33.17)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
>>> tf.__version__
'2.1.0'
```

Is there by any chance a weird ENV variable that messes with the linker?

**Comment by nicholascannon1** [comment]
Checked my ENV vars and couldn't see anything weird or anything that could effect the linking process.

Looking at how you guys build binaries for MacOS, I didn't export `TF_NEED_CUDA=0` or `CC_OPT_FLAGS='-mavx'` and I ran configure with `./configure`.  I also noticed some differences with the bazel build command too:

Your build: `bazel build --config=opt --config=v2 tensorflow/tools/pip_package:build_pip_package`

My build: `bazel build --config=opt //tensorflow/tools/pip_package:build_pip_package`
(I followed the instructions [here](https://www.tensorflow.org/install/source) exactly)

Just installed `tf-nightly` via pip with `pip install tf-nightly` and still getting the same error as above.

**Comment by av8ramit** [comment]
I noticed you are not using a virtualenv and my test was done in a virtualenv. According to [this StackOverflow post](https://stackoverflow.com/questions/57806063/cannot-import-name-pywrap-utils-from-tensorflow-python) this error can manifest if tensorflow was not properly installed to system Python. Can you please try either uninstalling TensorFlow or reinstalling TensorFlow? An additional test is trying with a virtualenv.

I'm also looking into seeing if those shared objects need to be imported in `tensorflow/python/__init__.py` and seeing if removing them is an option for the future. Sorry for the inconvenience and thanks for your patience!

**Comment by nicholascannon1** [comment]
Ok I've had no luck using a virtual environment and have installed / uninstalled multiple times with the same error still occurring.

Steps used to install with virtual environment:
1. `python3 -m venv env`
2. `source env/bin/activate`
3. `pip install -U pip`
4. `pip install tensorflow`
5. `python`
6. `>>> import tensorflow`

Thanks for your help!

**Comment by av8ramit** [comment]
It turns out we do not need those imports anyways so I've removed them. Hopefully a `tf-nightly` package after tomorrow can help resolve this.

https://github.com/tensorflow/tensorflow/commit/edda1d191fa92ac0fd7462a1deede6bd8a563861

**Comment by nicholascannon1** [comment]
Awesome thanks so much, I'll try installing `tf-nightly` after tomorrow!

**Comment by amahendrakar** [comment]
@nicholascannon1,
Any updates regarding this issue? Thanks!

**Comment by afcarvalho1991** [comment]
I'm also facing this issue.
 - macOS Mojave 10.14.6
 - python3.5 (no virtual env)
 - TensorFlow 2.1.0

André.

**Comment by nicholascannon1** [comment]
Still getting pywrap `ImportError` installing `tf-nightly`.
```
>>> import tensorflow
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/tensorflow/__init__.py", line 41, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "/usr/local/lib/python3.7/site-packages/tensorflow/python/__init__.py", line 64, in <module>
    from tensorflow.python.framework.framework_lib import *  # pylint: disable=redefined-builtin
  File "/usr/local/lib/python3.7/site-packages/tensorflow/python/framework/framework_lib.py", line 25, in <module>
    from tensorflow.python.framework.ops import Graph
  File "/usr/local/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 43, in <module>
    from tensorflow.python import pywrap_tfe
  File "/usr/local/lib/python3.7/site-packages/tensorflow/python/pywrap_tfe.py", line 29, in <module>
    from tensorflow.python._pywrap_tfe import *
ImportError: dlopen(/usr/local/lib/python3.7/site-packages/tensorflow/python/_pywrap_tfe.so, 2): Symbol not found: _TFE_CancellationManagerIsCancelled
  Referenced from: /usr/local/lib/python3.7/site-packages/tensorflow/python/_pywrap_tfe.so
  Expected in: flat namespace
 in /usr/local/lib/python3.7/site-packages/tensorflow/python/_pywrap_tfe.so
```

**Comment by av8ramit** [comment]
Sorry again for the frustration. Unfortunately since I cannot repro this it's difficult for me to debug.

So this new error suggests the issue was not with the `__init__.py` file as so much it was with loading shared objects in general. It appears no matter what, whenever you load the shared object first it has an issue. 

I looked around and found [this guide](https://developer.apple.com/library/archive/documentation/DeveloperTools/Conceptual/DynamicLibraries/100-Articles/UsingDynamicLibraries.html) which claims that adding the directory where the shared objects live to the following environment variables will help the linker find them. Could you try adding the path where the .so files live to your `LD_LIBRARY_PATH`? It appears your path is `/usr/local/lib/python3.7/site-packages/tensorflow/python/`. Additionally the shared object that has the implementation of `_TFE_CancellationManagerIsCancelled` is `_pywrap_tensorflow_internal.so`. Can you verify that shared object is in the directory I mentioned previously?

Thanks again for your patience. Hopefully this will resolve this.

**Comment by nicholascannon1** [comment]
Ok so I added the folder to `LD_LIBRARY_PATH` using:

`export LD_LIBRARY_PATH=/usr/local/lib/python3.7/site-packages/tensorflow/python/:$LD_LIBRA    RY_PATH`

and tried both `tf-nightly` and the regular `tensorflow` (installing via pip). `tensorflow` had the same error as above (the original one) and `tf-nightly` had the same error message as my last comment.

Checking the folder `/usr/local/lib/python3.7/site-packages/tensorflow/python/` I can see `_pywrap_utils.so` and `_pywrap_tensorflow_internal.so`. I cannot see `_pywrap_tfe.so` which is mentioned in the previous error.

Here is a list of all the shared object files in the directory `/usr/local/lib/python3.7/site-packages/tensorflow/python/`:
```
_dtypes.so
_op_def_registry.so
_pywrap_bfloat16.so
_pywrap_checkpoint_reader.so
_pywrap_debug_events_writer.so
_pywrap_device_lib.so
_pywrap_events_writer.so
_pywrap_file_io.so
_pywrap_kernel_registry.so
_pywrap_mlir.so
_pywrap_py_exception_registry.so
_pywrap_py_func.so
_pywrap_python_op_gen.so
_pywrap_quantize_training.so
_pywrap_record_io.so
_pywrap_stacktrace_handler.so
_pywrap_stat_summarizer.so
_pywrap_tensorflow_internal.so
_pywrap_tf_cluster.so
_pywrap_tf_item.so
_pywrap_tf_optimizer.so
_pywrap_tf_session.so
_pywrap_tfcompile.so
_pywrap_tfe.so
_pywrap_tfprof.so
_pywrap_toco_api.so
_pywrap_transform_graph.so
_pywrap_util_port.so
_pywrap_utils.so
_tf_stack.so
```

**Comment by av8ramit** [comment]
Unrelated, I see `_pywrap_tfe.so` in your directory listing, so the file is there.

Unfortunately I'm out of potential solutions. :( I'll keep looking around for Mac shared library issues to see if something can work. 

I'll keep this bug open in the event someone else ran into this issue and resolved it. Sorry I was unable to help.

**Comment by nicholascannon1** [comment]
No worries, thanks for your help!

**Comment by nicholascannon1** [comment]
UPDATE
Still having issues with 2.2.0 on OSX Catalina 10.15.4 installing inside a virtualenv with python 3.7.7 via pip. Python has been installed via homebrew as well (not sure if I've mentioned that above).

I've also noticed I'm unable to run tensorboard as well, getting segmentation faults when running from command line. Could be unrelated though as it also seg faults with tensorflow version 2.0.1 which is the only tensorflow version that works on my machine.

Here is the output error when importing tensorflow (inside virtualenv):
```
>>> import tensorflow
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/Nicholas/Desktop/tf_test/env/lib/python3.7/site-packages/tensorflow/__init__.py", line 41, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "/Users/Nicholas/Desktop/tf_test/env/lib/python3.7/site-packages/tensorflow/python/__init__.py", line 64, in <module>
    from tensorflow.python.framework.framework_lib import *  # pylint: disable=redefined-builtin
  File "/Users/Nicholas/Desktop/tf_test/env/lib/python3.7/site-packages/tensorflow/python/framework/framework_lib.py", line 25, in <module>
    from tensorflow.python.framework.ops import Graph
  File "/Users/Nicholas/Desktop/tf_test/env/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 43, in <module>
    from tensorflow.python import pywrap_tfe
  File "/Users/Nicholas/Desktop/tf_test/env/lib/python3.7/site-packages/tensorflow/python/pywrap_tfe.py", line 29, in <module>
    from tensorflow.python._pywrap_tfe import *
ImportError: dlopen(/Users/Nicholas/Desktop/tf_test/env/lib/python3.7/site-packages/tensorflow/python/_pywrap_tfe.so, 2): Symbol not found: _TFE_CancellationManagerIsCancelled
  Referenced from: /Users/Nicholas/Desktop/tf_test/env/lib/python3.7/site-packages/tensorflow/python/_pywrap_tfe.so
  Expected in: flat namespace
 in /Users/Nicholas/Desktop/tf_test/env/lib/python3.7/site-packages/tensorflow/python/_pywrap_tfe.so
>>>
```

**Comment by av8ramit** [comment]
This might be a long shot, but is your Xcode up to date? I'm confident the issues is machine specific. I've tried to repro on 3 different MacOS devices from Catalina and Mojave. 

Between 2.0 and 2.1 we modified the way C++ code was exported to shared objects, and I guess there is an issue with `dlopen` for users that hit this particular issue.

Potential other solutions:
1. `$DYLD_LIBRARY_PATH` can be set to the path we tried earlier.
https://stackoverflow.com/questions/27281943/import-matplotlib-pyplot-gives-importerror-dlopen-library-not-loaded-libpn
2. The issue might be with homebrew? https://stackoverflow.com/questions/35989572/importerror-dlopen-symbol-not-found-pycodecinfo-getincrementaldecoder

**Comment by nicholascannon1** [comment]
SOLVED!
I was digging through my `.zshrc` file and noticed I had added an export when first upgrading to zsh that fixed vim from crashing. The export was `export DYLD_FORCE_FLAT_NAMESPACE=1`. After removing this export I was able to import Tensorflow successfully!!

So I guess if anyone is having the same issue check if you've been messing with the DYLD linker.

Thanks for the help @av8ramit

**Comment by o0stsou0o** [comment]
Hi Nicholas,

I am running OSX 10.11.6 El Capitan and trying to upgrade my tensorflow 2.0.0 to tensorflow 2.3.1.  

When I try pip3 installing tensorflow in a virtual environment, I can't even import tensorflow.   I have to conda install tensorflow.  And when I try upgrading to tensorflow 2.3.1 after conda installing I get the error if I try importing:

File "/Users/blah/anaconda3/envs/test2/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 64, in
from tensorflow.python._pywrap_tensorflow_internal import *
ImportError: dlopen(/Users/blah/anaconda3/envs/test2/lib/python3.7/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so, 6): Symbol not found: _SecKeyCopyExternalRepresentation
Referenced from: /Users/blah/anaconda3/envs/test2/lib/python3.7/site-packages/tensorflow/python/../libtensorflow_framework.2.dylib
Expected in: /System/Library/Frameworks/Security.framework/Versions/A/Security
in /Users/blah/anaconda3/envs/test2/lib/python3.7/site-packages/tensorflow/python/../libtensorflow_framework.2.dylib

During handling of the above exception, another exception occurred:

"Traceback (most recent call last):
File "", line 1, in
File "/Users/blah/anaconda3/envs/test2/lib/python3.7/site-packages/tensorflow/init.py", line 41, in
from tensorflow.python.tools import module_util as _module_util
File "/Users/blah/anaconda3/envs/test2/lib/python3.7/site-packages/tensorflow/python/init.py", line 40, in
from tensorflow.python.eager import context
File "/Users/blah/anaconda3/envs/test2/lib/python3.7/site-packages/tensorflow/python/eager/context.py", line 35, in
from tensorflow.python import pywrap_tfe
File "/Users/blah/anaconda3/envs/test2/lib/python3.7/site-packages/tensorflow/python/pywrap_tfe.py", line 28, in
from tensorflow.python import pywrap_tensorflow
File "/Users/blah/anaconda3/envs/test2/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 83, in
raise ImportError(msg)
ImportError: Traceback (most recent call last):
File "/Users/blah/anaconda3/envs/test2/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 64, in
from tensorflow.python._pywrap_tensorflow_internal import *
ImportError: dlopen(/Users/blah/anaconda3/envs/test2/lib/python3.7/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so, 6): Symbol not found: _SecKeyCopyExternalRepresentation
Referenced from: /Users/blah/anaconda3/envs/test2/lib/python3.7/site-packages/tensorflow/python/../libtensorflow_framework.2.dylib
Expected in: /System/Library/Frameworks/Security.framework/Versions/A/Security
in /Users/blah/anaconda3/envs/test2/lib/python3.7/site-packages/tensorflow/python/../libtensorflow_framework.2.dylib"

Would you have an idea of what I might be doing wrong?

> UPDATE
> Still having issues with 2.2.0 on OSX Catalina 10.15.4 installing inside a virtualenv with python 3.7.7 via pip. Python has been installed via homebrew as well (not sure if I've mentioned that above).
> 
> I've also noticed I'm unable to run tensorboard as well, getting segmentation faults when running from command line. Could be unrelated though as it also seg faults with tensorflow version 2.0.1 which is the only tensorflow version that works on my machine.
> 
> Here is the output error when importing tensorflow (inside virtualenv):
> 
> ```
> >>> import tensorflow
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/Users/Nicholas/Desktop/tf_test/env/lib/python3.7/site-packages/tensorflow/__init__.py", line 41, in <module>
>     from tensorflow.python.tools import module_util as _module_util
>   File "/Users/Nicholas/Desktop/tf_test/env/lib/python3.7/site-packages/tensorflow/python/__init__.py", line 64, in <module>
>     from tensorflow.python.framework.framework_lib import *  # pylint: disable=redefined-builtin
>   File "/Users/Nicholas/Desktop/tf_test/env/lib/python3.7/site-packages/tensorflow/python/framework/framework_lib.py", line 25, in <module>
>     from tensorflow.python.framework.ops import Graph
>   File "/Users/Nicholas/Desktop/tf_test/env/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 43, in <module>
>     from tensorflow.python import pywrap_tfe
>   File "/Users/Nicholas/Desktop/tf_test/env/lib/python3.7/site-packages/tensorflow/python/pywrap_tfe.py", line 29, in <module>
>     from tensorflow.python._pywrap_tfe import *
> ImportError: dlopen(/Users/Nicholas/Desktop/tf_test/env/lib/python3.7/site-packages/tensorflow/python/_pywrap_tfe.so, 2): Symbol not found: _TFE_CancellationManagerIsCancelled
>   Referenced from: /Users/Nicholas/Desktop/tf_test/env/lib/python3.7/site-packages/tensorflow/python/_pywrap_tfe.so
>   Expected in: flat namespace
>  in /Users/Nicholas/Desktop/tf_test/env/lib/python3.7/site-packages/tensorflow/python/_pywrap_tfe.so
> >>>
> ```



> _Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template_
> 
> **System information**
> 
> * OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Mac OSX Catalina 10.15.2
> * Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
> * TensorFlow installed from (source or binary): Binary AND source
> * TensorFlow version: 2.1.0 (switched to branch r2.1.0)
> * Python version: 3.7.6
> * Installed using virtualenv? pip? conda?: pip (pip3 on my system)
> * Bazel version (if compiling from source): 2.1.0
> * GCC/Compiler version (if compiling from source): Apple clang version 11.0.0 (clang-1100.0.33.17)
> * CUDA/cuDNN version:
> * GPU model and memory: Intel UHD (using MacBookPro GPU not compatible)
> 
> **Describe the problem**
> After successfully installing Tensorflow via pip or compiling Tensorflow from source, importing the Tensorflow2.1.0 package fails with the error below on OSX Catalina 10.15.2 (CPU = 2.6 GHz 6-Core Intel Core i7). Running `pip install tensorflow==2.0.0` works fine. I've tried installing `pywrap` with `pip3 install pywrap` but this does not fix the issue.
> 
> **Provide the exact sequence of commands / steps that you executed before running into the problem**
> PIP instructions:
> 
> 1. `pip3 install tensorflow` (Tried `--user`, `--upgrade` and installing with `pip` as well)
> 2. `python3`
> 3. `>>> import tensorflow as tf`
> 
> Compilation instructions:
> 
> 1. `git clone https://github.com/tensorflow/tensorflow.git & cd tensorflow`
> 2. `git checkout branch_name r2.1.0`
> 3. `./configure` setting python version as `/usr/local/bin/python3` and everything else as defaults
> 4. `bazel build //tensorflow/tools/pip_package:build_pip_package`
> 5. `./bazel-bin/tensorflow/tools/pip_package/build_pip_package /tmp/tensorflow_pkg`
> 6. `pip install /tmp/tensorflow_pkg/tensorflow-2.1.0-cp37-cp37m-macosx_10_15_x86_64.whl`
> 7. `python3`
> 8. `>>> import tensorflow`
> 
> **Any other info / logs**
> Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.
> 
> ERROR PRODUCED:
> 
> ```
> >>> import tensorflow as tf
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/usr/local/lib/python3.7/site-packages/tensorflow/__init__.py", line 101, in <module>
>     from tensorflow_core import *
>   File "/usr/local/lib/python3.7/site-packages/tensorflow_core/__init__.py", line 40, in <module>
>     from tensorflow.python.tools import module_util as _module_util
>   File "/usr/local/lib/python3.7/site-packages/tensorflow/__init__.py", line 50, in __getattr__
>     module = self._load()
>   File "/usr/local/lib/python3.7/site-packages/tensorflow/__init__.py", line 44, in _load
>     module = _importlib.import_module(self.__name__)
>   File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/importlib/__init__.py", line 127, in import_module
>     return _bootstrap._gcd_import(name[level:], package, level)
>   File "/usr/local/lib/python3.7/site-packages/tensorflow_core/python/__init__.py", line 50, in <module>
>     from tensorflow.python import _pywrap_utils
> ImportError: dlopen(/usr/local/lib/python3.7/site-packages/tensorflow_core/python/_pywrap_utils.so, 2): Symbol not found: __ZN10tensorflow4swig10IsSequenceEP7_object
>   Referenced from: /usr/local/lib/python3.7/site-packages/tensorflow_core/python/_pywrap_utils.so
>   Expected in: flat namespace
>  in /usr/local/lib/python3.7/site-packages/tensorflow_core/python/_pywrap_utils.so
> ```
