### ISSUE TITLE
How to use tensorflow2 keras model on java?

### ISSUE THREAD

**Issue by GerScau** [tensorflow/tensorflow#36950]
i use keras to build my model on tf2
in tf1, keras.backend.get_session(), then create .pb file for java calling
please show me the solution of tf2

**Comment by ashutosh1919** [comment]
try [this one](https://www.tensorflow.org/install/lang_java)

**Comment by GerScau** [comment]
> try [this one](https://www.tensorflow.org/install/lang_java)
thanks, it's tf1 java api demo, but i need some demo that tf2 model turn to tf1 model

**Comment by rthadur** [comment]
As mentioned in Note  [here](https://www.tensorflow.org/install/lang_java) : : There is no libtensorflow support for TensorFlow 2 yet. It is expected in a future release. tf2 is not supported yet

**Comment by GerScau** [comment]
> As mentioned in Note [here](https://www.tensorflow.org/install/lang_java) : : There is no libtensorflow support for TensorFlow 2 yet. It is expected in a future release. tf2 is not supported yet

got that, thank you
