### ISSUE TITLE
MultiWorkerMirroredStrategy failed to run after a few batches occasionally

### ISSUE THREAD

**Issue by 372046933** [tensorflow/tensorflow#36953]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information** 
- Have I written custom code (as opposed to using a stock
example script provided in TensorFlow): YES
- OS Platform and Distribution (e.g.,
Linux Ubuntu 16.04): TensorFlow 2.0 Ubuntu 18.04 official image
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if
the issue happens on mobile device: 
- TensorFlow installed from (source or
binary): - TensorFlow version (use command below): v2.0.0-rc2-26-g64c3d38
- Python version: - Bazel
version (if compiling from source): 3.6.8
- GCC/Compiler version (if compiling from
source): 
- CUDA/cuDNN version: - GPU model and memory: CUDA 10.1 16GB

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
``` W tensorflow/core/framework/op_kernel.cc:1622] OP_REQUIRES failed at collective_ops:234 : Aborted: The same RecvBuf (GrpcWorker) request was received twice.```
**Describe the expected behavior**
Should be able to train on each run.
**Standalone code to reproduce the issue** 
https://github.com/calmisential/TensorFlow2.0_ResNet
I modified some code to make it run with different distribute strategy.

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by 372046933** [comment]
I changed the collective OP for `MultiWorkerMirroredStrategy` from `tf.distribute.experimental.CollectiveCommunication.AUTO` to `tf.distribute.experimental.CollectiveCommunication.NCCL`. The problem exists. Before hangs, there is a WARN log from NCCL.
```
[0] external/nccl_archive/src/transport/net_socket.c:200 NCCL WARN NET/SOCKET : message truncated : receiving 1048576 bytes instead of 32768
[0] NCCL INFO bazel-out/k8-py2-opt/bin/external/nccl_archive/_virtual_includes/include_hdrs/net.h:34 -> 3
[0] NCCL INFO external/nccl_archive/src/transport/net.cc:533 -> 3
[0] NCCL INFO external/nccl_archive/src/transport.cc:163 -> 3 [Proxy Thread]
```

**Comment by 372046933** [comment]
This is different from https://github.com/tensorflow/tensorflow/issues/37112, which is caused by partial batch size.

**Comment by 372046933** [comment]
Probably, this a NCCL issue. PyTorch has the same issue as TF. See https://github.com/pytorch/pytorch/issues/17703. But the issue is closed on NCCL https://github.com/NVIDIA/nccl/issues/193

**Comment by jvishnuvardhan** [comment]
@372046933 Can you please try with the recent `tf-nightly` or `TF2.1` and let us know whether the issue persists or not. Thanks!

**Comment by 372046933** [comment]
I tried `TF2.1` and `tf-nightly` weeks ago. For `TF2.1` I got the same error. For `tf-nightly`, I cannot even iterate over imagenet data on HDFS, let alone the training.

**Comment by 372046933** [comment]
By the way, the more workers added, the more frequently `Aborting RingReduce with Aborted: ...` occurred. I can reproduce it on 9 or 10 workers. Usually training will abort within 5 hours.

**Comment by 372046933** [comment]
@jvishnuvardhan  I added `TF_CPP_VMODLE=grpc_state=2` to ENV, and got some output from GRPC.
Do we need to **back-off** before the first retry?
```
I ./tensorflow/core/distributed_runtime/grpc/grpc_state.h:127] /tensorflow.WorkerService/RecvBuf returned with non-ok status: Unavailable: Connection reset by peer Retries: 0 Max: 10
{"created":"@1583991368.216950699", "description":"Error received from peer", "file":"external/grpc/src/core/lib/surface/call.cc", "file_line":"1039", "grpc_message":"Connection reset by peer", "grpc_status":14}
I ./tensorflow/core/distributed_runtime/grpc/grpc_state.h:134] Retrying call for /tensorflow.WorkerService/RecvBufRetry: 1 of 10
```

**Comment by 372046933** [comment]
> I changed the collective OP for `MultiWorkerMirroredStrategy` from `tf.distribute.experimental.CollectiveCommunication.AUTO` to `tf.distribute.experimental.CollectiveCommunication.NCCL`. The problem exists. Before hangs, there is a WARN log from NCCL.
> 
> ```
> [0] external/nccl_archive/src/transport/net_socket.c:200 NCCL WARN NET/SOCKET : message truncated : receiving 1048576 bytes instead of 32768
> [0] NCCL INFO bazel-out/k8-py2-opt/bin/external/nccl_archive/_virtual_includes/include_hdrs/net.h:34 -> 3
> [0] NCCL INFO external/nccl_archive/src/transport/net.cc:533 -> 3
> [0] NCCL INFO external/nccl_archive/src/transport.cc:163 -> 3 [Proxy Thread]
> ```

https://github.com/NVIDIA/nccl/commit/6c61492eba5c25ac6ed1bf57de23c6a689aa75cc maybe fixed NCCL on `MultiWorkerMirroredStrategy`. To be verified

**Comment by jvishnuvardhan** [comment]
@372046933 After verification, feel free to close the issue if this was resolved for you. Thanks!

**Comment by 372046933** [comment]
@jvishnuvardhan If I turn off NCCL, multi worker training fails also. Maybe it's due to some bug in upper layer.

**Comment by sushreebarsa** [comment]
@372046933 It looks like you are using an older Version of Tensorflow. Many bugs have been fixed in the latest version. Could you please execute your code using Latest Version 2.4.1 or 2.5 and let us know if the issue still persists? Thanks!
