### ISSUE TITLE
TF-TRT execution context management for multiple threads / streams

### ISSUE THREAD

**Issue by tfeher** [tensorflow/tensorflow#36959]
This issue is created to discuss and possibly improve execution context management during TF-TRT inference. 

The TRT [best practices guide]() says: "A common pattern is incoming requests dispatched to a pool of waiting for worker threads. In this case, the pool of worker threads will each have one execution context and CUDA stream. Each thread will request work in its own stream as the work becomes available. Each thread will synchronize with its stream to wait for results without blocking other worker threads."

Note that we have a different pattern in TF-TRT. Let's consider the implicit batch case with  a single engine and a single execution context. For any given `TRTEngineOp` we keep a global execution context object in the resource manager. We guard the access to this `IExecutionContext` by a mutex until we prepare the buffers and equeue the inference job. But the mutex is released when we return from `ExecuteTRTEngine`, and the inference job might still be enqueued at that time when we release the mutex.

The TRT best practices guide says: to "Create a CUDA stream using cudaStreamCreate for each independent batch and an `IExecutionContext` for each independent batch." ~I would~ One should interpret this the following way: if we want to enque work on multiple GPU streams then each independent batch of work has to have a separate `IExecutionContext` object. Alternatively we can use a single stream with a single execution context.

So the current scheduling of TF-TRT inference would require that TRTEngineOp_0 puts all its work always on the same stream. This (while not efficient) would guarantee correctness. 

Is it guaranteed that the following call would always return the same stream for the given `TRTEngineOP` object?
https://github.com/tensorflow/tensorflow/blob/9b53275852f37fb1f48e22ed99237f1baef761c5/tensorflow/compiler/tf2tensorrt/kernels/trt_engine_op.cc#L416-L420

Tagging @bixia1

**Comment by bixia1** [comment]
From how class GPUDeviceContext manipulates its stream_ field, there should be a fixed stream associated with the field for a given GPUDeviceContext class object. Therefore, the above call for the same TRTEngineOp class object should always return the same stream. https://github.com/tensorflow/tensorflow/blob/a8ac8f901a3948a71510dedee258119ff4a77363/tensorflow/core/common_runtime/gpu_device_context.h#L82-L84

**Comment by tfeher** [comment]
Thanks @bixia1 for the answer. One more question: Assume that we have a GPUDeviceContext assigned to TRTEngineOp. Can this context object change during future inference calls, or it remain fixed once it is assigned?

**Comment by bixia1** [comment]
The GPUGeviceContext  comes from here
https://github.com/tensorflow/tensorflow/blob/aae5c218bea680b2c5ef581a4f215501ccd66b4e/tensorflow/core/common_runtime/gpu/gpu_device.cc#L479-L486

which is initialized here and can't be changed for the object
https://github.com/tensorflow/tensorflow/blob/aae5c218bea680b2c5ef581a4f215501ccd66b4e/tensorflow/core/common_runtime/gpu/gpu_device.cc#L359-L371

**Comment by tfeher** [comment]
Thanks Bixia. In general it looks like  that we have a single compute stream for a physical GPU. That ensures that the TRTEngineOp running on that GPU will have correct stream ordering. That was the main question discussed in this issue. 

It is a little bit confusing though that the gpu_device_context could be [overriden](https://github.com/tensorflow/tensorflow/blob/aae5c218bea680b2c5ef581a4f215501ccd66b4e/tensorflow/core/common_runtime/gpu/gpu_device.cc#L564).  I see that when executor [calls ComputeAsync](https://github.com/tensorflow/tensorflow/blob/a8ac8f901a3948a71510dedee258119ff4a77363/tensorflow/core/common_runtime/executor.cc#L1900), it passes the context through [params](https://github.com/tensorflow/tensorflow/blob/a8ac8f901a3948a71510dedee258119ff4a77363/tensorflow/core/common_runtime/executor.cc#L1762), that was initialized [here](https://github.com/tensorflow/tensorflow/blob/a8ac8f901a3948a71510dedee258119ff4a77363/tensorflow/core/common_runtime/executor.cc#L1603). Assuming no one has overwritten the default behavior in GPUDeviceBase which ensures a single stream,  we should be all good. 

The issue can be closed. I will refer this issue in the [docstring of execution_contexts](https://github.com/tensorflow/tensorflow/blob/aae5c218bea680b2c5ef581a4f215501ccd66b4e/tensorflow/compiler/tf2tensorrt/utils/trt_lru_cache.h#L153).
