### ISSUE TITLE
AttributeError: 'Tensor' object has no attribute 'numpy'

### ISSUE THREAD

**Issue by nscotto** [tensorflow/tensorflow#36979]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information** 
- Have I written custom code (as opposed to using a stock
example script provided in TensorFlow):  yes
- OS Platform and Distribution (e.g.,
Linux Ubuntu 16.04): Linux Fedora 31
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if
the issue happens on mobile device: no
- TensorFlow installed from (source or
binary): binary (anaconda)
- TensorFlow version (use command below): 2.1 
- Python version: 3.7
- Bazel version (if compiling from source): no
- GCC/Compiler version (if compiling from source): no
- CUDA/cuDNN version: 10.1
- GPU model and memory: nvidia 1050 ti

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
I can't call `numpy()` of `Tensor` arguments passed to the mapping function given to `tf.data.Dataset` even with `tf.executing_eagerly()` returning `True`:
```
AttributeError: 'Tensor' object has no attribute 'numpy'
```
**Describe the expected behavior**
I'd like to be able to access the `numpy()` property of arguments passed to a mapping function passed to `tf.data.Dataset.map`
**Standalone code to reproduce the issue** 
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.
```python
import tensorflow as tf

def transformer(x):
    x.numpy()
    return x

dataset = tf.data.Dataset.from_tensors([0,1,2])
dataset.map(transformer)
```

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by ashutosh1919** [comment]
@nscotto , You can convert tensor into numpy array using `tensor.numpy()`, But you can't do the same in case of `MapDataset`. In the example code you have given,  the `x` in the transformer function is `MapDataset` and not `Tensor`.
I have seen similar issue [#30035](https://github.com/tensorflow/tensorflow/issues/30035) and also you can refer to [this function](https://www.tensorflow.org/api_docs/python/tf/numpy_function?version=nightly) which I think will solve your problem. 
Also, if you have any doubts regarding `from_tensors` and `from_tensor_slices`, then please review the official docs [here](https://www.tensorflow.org/api_docs/python/tf/data/Dataset?version=nightly#from_tensor_slices). Also, take a look at these example which I recently Added through my PR #36989.

**Comment by ravikyram** [comment]
@nscotto 

Any update on this issue please. Thanks!

**Comment by nscotto** [comment]
Yes, ashutosh1919 is right, it's because `Dataset.map` passes `Tensor` instead of `EagerTensor`, thus I need to wrap my code inside a `tf.py_function` if I need to convert to numpy (and obviously reducing the performances).
As a suggestion I think the documentation could mention this in order to make Tensorflow more accessible for newcomers.

**Comment by ghosalsattam** [comment]
@ashutosh1919  @ravikyram @nscotto 
I am trying to address the problem by making a numpy() function in the Tensor class. But I am facing a problem. Can anyone tell me from which attribute of Tensor class I can find the data.

**Comment by ghosalsattam** [comment]
@ashutosh1919 I went through all the codes. From the codes it seems that internally the map() function iterates through all the tensors(for each function call). So what x sees from inside the function in map() is the single tensor passed to it at that very time. So using .numpy() inside the function called through map() is pointless.

**Comment by ashutosh1919** [comment]
@nscotto , @ravikyram and @ghosalsattam , I have raised PR #37853 to add an example on `tf.numpy_function` and how it is different from `tf.py_function`. Now, 2nd and 3rd point [here](https://www.tensorflow.org/api_docs/python/tf/data/Dataset?version=nightly#map) about `py_function` and `numpy_function` clearly explains the difference.  
Please give your suggestions if anything else is required.
