### ISSUE TITLE
Can't find docs on SSL support for distributed training

### ISSUE THREAD

**Issue by sarthfrey** [tensorflow/tensorflow#36973]
**Describe the current behavior**

I haven't be able to find documentation on if SSL is used during distributed training with `tf.distribute.Strategy` with gRPC.

**Describe the expected behavior**

I should be able to easily find this information in the documentation, and if it's supported, then I should easily be able to turn SSL on/off in distributed training for when I prefer security vs performance.

**Comment by guptapriya** [comment]
@haoyuz @dubey can one you comment on this? both for the collective ops used in distributed training, but also other types of communication in the runtime in TF2.

**Comment by dubey** [comment]
We [do not support](https://github.com/tensorflow/tensorflow/blob/1381fc8e15e22402417b98e3881dfd409998daea/tensorflow/core/distributed_runtime/rpc/grpc_server_lib.cc#L486) SSL credentials.
