### ISSUE TITLE
Tensorflow Lite Hexagon delegate support for QCOM XR1 - soc_id: 371

### ISSUE THREAD

**Issue by rz-dev** [tensorflow/tensorflow#36972]
QCOM XR1 (with soc_id:371) is in the same family as Snapdragon 710, Snapdragon 710 is in the list of the supported Socs:

Currently most Qualcomm SoCs are supported, including:

Snapdragon 835 (682 DSP)
Snapdragon 660/820/821 (680 DSP)
Snapdragon 710/845 (685 DSP)
Snapdragon 8150/855 (690 DSP)

we were wondering if XR1 could be added to this list as well, based on my understanding, the only change is to add the soc_id:371 to the supported list. We would be happy to help test/verify it if necessary. DSP acceleration is very important to our use cases, your help is greatly appreciated.

thanks for your support,
-richard

**Comment by karimnosseir** [comment]
Hi Richard,
Can you share more details on the SoC, i can't find reference on the details about the hexagon version used on this SoC.
Sadly, i don't have one of them to check and verify.
Thanks

**Comment by rz-dev** [comment]
Hi Karim,

QCOM XR1 (SXR1130) has the same DSP as Snapdragon 710/845, which is 685 DSP.
I can help test and verify.

thanks,
-richard

**Comment by karimnosseir** [comment]
Hi Richard,
That should mean it is a v65. I will enable soc_id:371 to v65/CDSP.
When the libhexagon_interface version is updated it should include this change.
Will update the issue here too when it is pushed 

Thanks

**Comment by rz-dev** [comment]
Hi Karim,

Yes, it's v65. thank you so much for the quick support.

-richard

**Comment by karimnosseir** [comment]
Hi Richard,

If you're building from bazel then you can try master branch now, it should be available.

Please try it and let me know if it works or not or if you have any issues.

Thanks

**Comment by rz-dev** [comment]
Hi Karim, 

just verified it's working now, will do more testing next. 
thanks again.

-richard
