### ISSUE TITLE
InternalError: Assigned device '/job:worker/replica:0/task:0/device:TPU:0' does not have registered OpKernel support for _Arg

### ISSUE THREAD

**Issue by bestpredicts** [tensorflow/tensorflow#36980]
when run bert tpu on colab get  error info  :  
InternalError: Assigned device '/job:worker/replica:0/task:0/device:TPU:0' does not have registered OpKernel support for _Arg

here is [my code on colab ](https://colab.research.google.com/drive/1i9ZhGGv8KDv5-VISbwTdCwDqrhh-67pu#scrollTo=xBggqjKaHU9w) You can reproduce this bug through my code

**Comment by gadagashwini** [comment]
Was able to reproduce the reported issue with Tf2.1.
Please find the gist [here](https://colab.sandbox.google.com/gist/gadagashwini/4e0b537e9fb6e58c85f46c71b88e2258/untitled403.ipynb). Thanks!

**Comment by simonsays1980** [comment]
Same problem for me. Did anyone succeed in solving this issue? Shutting off eager mode?

**Comment by rxsang** [comment]
Hi @bestpredicts and @simonsays1980,

You need to use 
`tf.config.experimental_connect_to_cluster(resolver)` API instead of
`tf.config.experimental_connect_to_host(resolver.master())`
See https://www.tensorflow.org/guide/tpu
