### ISSUE TITLE
Rising a memory on every step

### ISSUE THREAD

**Issue by open-v** [tensorflow/tensorflow#36988]
Hello. I used a MobileNet for Object detection and my model is training by following code:

```py
@tf.function
def train(model, dataset, epochs=50, lr=1e-5, checkpoints=None):
  optimizer = tf.keras.optimizers.Adam(lr=lr)
  for i in range(epochs):
    dataset = dataset.shuffle(1000)
    # training
    for images, boxes, labels in tqdm(dataset, desc='Epoch {} of {}'.format(i + 1, epochs)):
      with tf.GradientTape() as tape:
        localization, classification = model(images, training=True)
        smooth = losses.smooth_l1(boxes, localization)
        focal  = losses.focal(labels, classification)
        loss = smooth * 0.6 + focal * 0.4
      gradients = tape.gradient(loss, model.trainable_variables)
      optimizer.apply_gradients(zip(gradients, model.trainable_variables))
    if checkpoints:
      model.save_weights(checkpoints)
```
But my PC memory is rising on every step.
Can you help me to fix it?

**Comment by ayushmankumar7** [comment]
Maybe you are saving the weights after each epoch, that is rising the PC memory. 
Bring the  "model.save_weights(checkpoints)" outside the for loop.

**Comment by open-v** [comment]
When I not use tf.function. It is working okay.
```py
# @tf.function
def train(model, dataset, epochs=50, lr=1e-5, checkpoints=None):
  ...
```

**Comment by gadagashwini** [comment]
@open-v, Can you provide Tensorflow version and complete code to analyze the issue. Thanks!

**Comment by open-v** [comment]
My TensorFlow version is: 2.1.0.
[Link for wheel](https://drive.google.com/file/d/1Ur6kvaY96P3dLjo-gxqykO8CUh4gEyy8/view?usp=sharing)

**Comment by gadagashwini** [comment]
@open-v, Can you provide the instructions to execute the code. Thanks!

**Comment by gadagashwini** [comment]
@open-v, Can you update for the above comment.

**Comment by open-v** [comment]
Yes I updated, and I am using another way

**Comment by gadagashwini** [comment]
@open-v, The given [github repo](https://github.com/open-v/tf-retinanet) don't have clear instructions to execute the code. 
`Yes I updated, and I am using another way`
Just to verify, did you find solution. 

Thanks!

**Comment by gadagashwini** [comment]
@open-v, Can you update for the above comment. Thanks!

**Comment by gadagashwini** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
