### ISSUE TITLE
Shape issues in keras.metrics.sparse_top_k_categorical_accuracy with multiple dimensions

### ISSUE THREAD

**Issue by benbarsdell** [tensorflow/tensorflow#36985]
**System information** 
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 16.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): v1.12.1-24394-gc24d2f9 2.2.0-dev20200210
- Python version: 3.5.2
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

**Describe the current behavior**
**Describe the expected behavior**
**Standalone code to reproduce the issue** 
When there are multiple dimensions (e.g., for image data), the behavior of tf.metrics.sparse_top_k_categorical_accuracy and tf.metrics.top_k_categorical_accuracy differ from both each other and that of their categorical_crossentropy equivalents.

In particular, as of https://github.com/tensorflow/tensorflow/commit/ddca4b92b4eb4e187716b03f443362c904bdad7e (which was used to fix https://github.com/tensorflow/tensorflow/issues/33825), tf.metrics.sparse_top_k_categorical_accuracy flattens the extra dims (resulting in a different output shape compared to sparse_categorical_crossentropy), while tf.metrics.top_k_categorical_accuracy raises an error saying there must be only 2 dimensions. The docs don't say much about what should be expected.

The flattened shape also causes an error when passing weights to tf.keras.metrics.SparseTopKCategoricalAccuracy.

See minimal repro code here:
https://colab.research.google.com/drive/1DR7SSoj8cpo0Y35swz-dyOX4DCazidPe

**Comment by sachinprasadhs** [comment]
Was able to reproduce your issue in Tf Nightly 2.6.0-dev20210524, please find the gist [here](https://colab.research.google.com/gist/sachinprasadhs/7a14269ffd5bc8b10e0284f817533809/35650.ipynb). Thanks!

**Comment by Saduf2019** [comment]
The issue is still reproducible on tf 2.7, [nightly](https://colab.research.google.com/gist/Saduf2019/441a7724c4586d488007fff3f2be86e8/untitled638.ipynb) version

**Comment by tensorflowbutler** [comment]
Hi There,

 This is a stale issue. As you are using an older version of tensorflow, we are checking to see if you still need help on this issue. Please test the issue with the latest TensorFlow (TF2.7 and tf-nightly). If the issue still persists with the newer versions of TF, please feel free to open it in [keras-team/keras](https://github.com/keras-team/keras/issues) repository by providing details about the issue and a standalone code to reproduce the issue. Thanks! 

 Please note that Keras development has moved to a separate Keras-team/keras repository to focus entirely on only Keras. Thanks!
