### ISSUE TITLE
How to get integer batch size in Keras model.fit()

### ISSUE THREAD

**Issue by janosh** [tensorflow/tensorflow#36991]
I'm trying to use `model.fit()` on a `Sequential` model consisting of custom layers subclassing `tf.keras.layers.Layer`. Using `GradientTape` where I feed every batch in explicitly works fine (including in graph mode with `tf.function`). Trying to use the high-level Keras API for training,

```py
model.compile(loss=loss_fn, optimizer="adam")
model.fit(X_train, y_train)
```

I get a bunch of `ValueError: None values not supported.` for things like

```py
def call(self, x):
    ...
    epsilon = tf.random.normal(x.shape)  # reparametrization trick
    ...
```

since `x.shape[0]` is `None`. So the question is, how do I get an integer batch size when using `model.fit()`? I tried

```py
model.compile(loss=loss_fn, optimizer="adam")
model.fit(
    X_train, y_train, batch_size=64, steps_per_epoch=X_train.shape[0] // 64,
)
```

but that makes no difference. `x.shape[0]` remains `None` during graph creation.

**Comment by ghosalsattam** [comment]
Can you please try numpy.shape(X_train)[0]//64

**Comment by ghosalsattam** [comment]
Please let me know if it works.

**Comment by janosh** [comment]
@ghosalsattam Makes no difference.

**Comment by ghosalsattam** [comment]
Can you provide me the full code?

**Comment by janosh** [comment]
@ghosalsattam Sorry, the code should remain private for now. But the following stripped down example already exhibits the problem:

```py
import tensorflow as tf

class Foo(tf.keras.layers.Layer):
    def __init__(self):
        super().__init__()

    def call(self, x):
        return tf.random.normal(x.shape)

model = tf.keras.Sequential([Foo()])

model.compile()

model.fit(tf.random.normal([10,5]), tf.random.normal([10]))
```

**Comment by ghosalsattam** [comment]
It is difficult to say something if I don't have any information of x. But from the error it seems that in the function, the value of x passed does not match the x you intend to pass.  May be it is an array of None.

**Comment by amahendrakar** [comment]
@janosh,
I tried to run the above code snippet and am facing an error stating `    ValueError: Cannot convert a partially known TensorShape to a Tensor: (None, 5)`. You can find the gist of it [here](https://colab.sandbox.google.com/gist/saikumarchalla/641b725d245017106586ab46c03acdea/36991.ipynb).

Could you please confirm if you are facing the same error? Thanks!

**Comment by janosh** [comment]
@amahendrakar Yes, that's the error I'm getting as well.

**Comment by ghosalsattam** [comment]
@janosh 
Then you can try using batch size =1
I used the approach for a slightly different case and it worked there.
You can use the format of batch size used in predict().
for i in range(30,70):
	print(i)
	Pixels,img=detectCorner(path,i)
	if(len(Pixels)==0):
		continue
	Roi=findClusters(Pixels,img)
	print(Roi)
	crop = np.empty((40,32,32,1),dtype=int)
	for roi in range(len(Roi)):
		for j in range(30,70):
			ll=Roi[roi][0]
			ur=Roi[roi][1]
			print(ll,ur)
			img1=pronounce(data[:,:,j].T)
			#print(ll[0],ur[0])
			crop1=img1[ur[0]:ll[0],ll[1]:ur[1]]
			plt.imshow(crop1,'gray')
			#plt.show()
			crop1=cv2.resize(crop1,interpolation=cv2.INTER_CUBIC,dsize=(32,32))
			crop[j-30,]=np.expand_dims(crop1,axis=2)
			#print(np.shape(crop[roi]))
			#crop[roi]=np.expand_dims(crop[roi],axis=2)
		a=classifier.predict_classes(crop)#batch size=1


For details:
https://stackoverflow.com/questions/35289773/cannot-convert-a-partially-converted-tensor-in-tensorflow

**Comment by ghosalsattam** [comment]
Hope this helps.

**Comment by sixChar** [comment]
Use tf.shape(x) instead of x.shape. 

x.shape is the static shape of x and evaluates to (None,5).

tf.shape(x) on the other hand is the dynamic shape of x and is evaluated as the actual shape of x when training/predicting.

**Comment by janosh** [comment]
@sixChar Thanks, I tried that as well but it's not really a solution. The errors in my case are thrown by some nested functions that really only need to know the size of the first dimension of `x`. If I pass in `tf.shape(x)[0]` instead of `x.shape[0]`, nothing changes. I get the same errors saying `None values not supported.` for things like `tf.zeros(batch_size)` where `batch_size` was passed in as `tf.shape(x)[0]`.  I suspect that it might work if I pass in the whole tensor and only call tf.shape in the nested functions themselves. But I'd prefer not to do that since those functions don't need to know anything except `tf.shape(x)[0]`.

**Comment by sixChar** [comment]
Could you give an example of the kind of code that still causes the same error when using tf.shape(x)[0]?

**Comment by janosh** [comment]
@sixChar Oops, I take it all back. I tried producing a minimal example that errors with `tf.shape(x)`. Didn't manage though. So I went back to my actual code and tried to find out why I was still getting the error there. Turns out there was one place I had overlooked converting from `x.shape` to `tf.shape(x)`. To be fair, the graph code you get when debugging `model.fit(...)` is pretty near unreadable which is why I'd missed it. Sorry about the noise.

**Comment by janosh** [comment]
One final suggestion though: I think it would help if the [docs on `tf.shape`](https://www.tensorflow.org/api_docs/python/tf/shape?version=nightly) as well as the [Writing custom layers and models with Keras](https://www.tensorflow.org/guide/keras/custom_layers_and_models) guide had a note on this, i.e. that `tf.shape` should be used instead of `x.shape` when defining custom layers and models to avoid `None` errors.

**Comment by jvishnuvardhan** [comment]
@janosh Would you like to update docs through PR? Thanks!

**Comment by janosh** [comment]
@jvishnuvardhan PR submitted. Suggestions for improvement welcome.

**Comment by Al-Badri179** [comment]
> Can you provide me the full code?

I have this error: 
"ValueError: Calling `Model.fit` in graph mode is not supported when the `Model` instance was constructed with eager mode enabled. Please construct your `Model` instance in graph mode or call `Model.fit` with eager mode enabled."
When I tried to execute this code:

hist = model.fit(X_train, y_train, batch_size=16, epochs=num_epoch, verbose=1, validation_data=(X_test, y_test))

How can I exceed it?

**Comment by jvishnuvardhan** [comment]
@Al-Badri179 Can you please open a new issue with a simple standalone code to reproduce the issue? Thanks!

**Comment by Al-Badri179** [comment]
@jvishnuvardhan ok, sorry for inconvenience
