### ISSUE TITLE
inline compiler switch for __memcpy_inline?

### ISSUE THREAD

**Issue by patfla** [tensorflow/tensorflow#3699]
Trying to build tensorflow on Ubuntu 16.04 with cuda 7.5 and gcc 4.9.3.

```
INFO: From Compiling tensorflow/core/kernels/batchtospace_op_gpu.cu.cc:
nvcc warning : option '--relaxed-constexpr' has been deprecated and replaced by option '--expt-relaxed-constexpr'.
nvcc warning : option '--relaxed-constexpr' has been deprecated and replaced by option '--expt-relaxed-constexpr'.
/usr/include/string.h: In function 'void* __mempcpy_inline(void*, const void*, size_t)':
/usr/include/string.h:652:42: error: 'memcpy' was not declared in this scope
   return (char *) memcpy (__dest, __src, __n) + __n;
                                          ^
```

I think __memcpy_inline needs an inline compiler switch turned on but this is the first time I've used bazel, and just what where?

**Comment by girving** [comment]
@martinwicke Have you seen this before?

**Comment by martinwicke** [comment]
Never. I think switches would be in the crosstool, but it's weird we should need them (or rather, you should need some that we apparently don't). @damienmg any idea?

**Comment by patfla** [comment]
Sorry - "inline" ended up getting used in two contexts - in the code function name itself but I used it in the sense of: is adding __n to memcpy(a,b,n) valid in itself or does it need a special compiler switch?  Now that I think about it memcpy returns a pointer so this is just standard C pointer arithmetic in which case you don't need a complier switch.

If so then the question becomes: why is memcpy not declared in this scope?  Still this is not in the tensorflow codebase but rather /usr/include/string.h and so the problem is perhaps with my installation.  That said, the error pops up well into the build (at about [?] 1200 out of the 2500 files) which would see to indicate that for the most part my installation is working fine.  If there's a problem with one's installation one usually (note: usually) sees it right away.

**Comment by patfla** [comment]
As I iteratively re-execute the build for tutorials_example_trainer I find that the target at which it fails can change:

```
patfla@patfla-N550JV:~/code/tensorflow$ bazel build -c opt --config=cuda //tensorflow/cc:tutorials_example_trainer
.
INFO: Found 1 target...
INFO: From Compiling tensorflow/core/kernels/batchtospace_op_gpu.cu.cc:
nvcc warning : option '--relaxed-constexpr' has been deprecated and replaced by option '--expt-relaxed-constexpr'.
nvcc warning : option '--relaxed-constexpr' has been deprecated and replaced by option '--expt-relaxed-constexpr'.
/usr/include/string.h: In function 'void* __mempcpy_inline(void*, const void*, size_t)':
/usr/include/string.h:652:42: error: 'memcpy' was not declared in this scope
   return (char *) memcpy (__dest, __src, __n) + __n;
                                          ^
ERROR: /home/patfla/code/tensorflow/tensorflow/core/kernels/BUILD:1498:1: output 'tensorflow/core/kernels/_objs/batchtospace_op_gpu/tensorflow/core/kernels/batchtospace_op_gpu.cu.o' was not created.
ERROR: /home/patfla/code/tensorflow/tensorflow/core/kernels/BUILD:1498:1: not all outputs were created.
Target //tensorflow/cc:tutorials_example_trainer failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 43.125s, Critical Path: 36.73s
patfla@patfla-N550JV:~/code/tensorflow$ bazel build -c opt --config=cuda //tensorflow/cc:tutorials_example_trainer
INFO: Found 1 target...
INFO: From Compiling tensorflow/core/kernels/cwise_op_gpu_mod.cu.cc:
nvcc warning : option '--relaxed-constexpr' has been deprecated and replaced by option '--expt-relaxed-constexpr'.
nvcc warning : option '--relaxed-constexpr' has been deprecated and replaced by option '--expt-relaxed-constexpr'.
/usr/include/string.h: In function 'void* __mempcpy_inline(void*, const void*, size_t)':
/usr/include/string.h:652:42: error: 'memcpy' was not declared in this scope
   return (char *) memcpy (__dest, __src, __n) + __n;
                                          ^
ERROR: /home/patfla/code/tensorflow/tensorflow/core/kernels/BUILD:1089:1: output 'tensorflow/core/kernels/_objs/cwise_op_gpu/tensorflow/core/kernels/cwise_op_gpu_mod.cu.o' was not created.
ERROR: /home/patfla/code/tensorflow/tensorflow/core/kernels/BUILD:1089:1: not all outputs were created.
Target //tensorflow/cc:tutorials_example_trainer failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 36.292s, Critical Path: 35.57s
```
That makes me begin to question how bazel keeps state.

```
patfla@patfla-N550JV:~/code/tensorflow$ bazel dump --action_cache | wc -l
1164439
```

That's not a good indication (less state is usually better) and makes me wonder just what I'm investigating here.  Certainly not, neural net architectures.

Maybe a different version of bazel would help?

```
patfla@patfla-N550JV:~/code/tensorflow$ bazel version
Build target: bazel-out/local-fastbuild/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Thu Jan 01 00:00:00 1970 (0)
Build timestamp: Thu Jan 01 00:00:00 1970 (0)
Build timestamp as int: 0
patfla@patfla-N550JV:~/code/tensorflow$ grep -i bazel /var/log/dpkg.log
2016-08-07 19:47:13 install bazel:amd64 <none> 0.3.1
2016-08-07 19:47:13 status half-installed bazel:amd64 0.3.1
2016-08-07 19:47:13 status unpacked bazel:amd64 0.3.1
2016-08-07 19:47:13 status unpacked bazel:amd64 0.3.1
2016-08-07 19:47:13 configure bazel:amd64 0.3.1 <none>
2016-08-07 19:47:13 status unpacked bazel:amd64 0.3.1
2016-08-07 19:47:13 status half-configured bazel:amd64 0.3.1
2016-08-07 19:47:13 status installed bazel:amd64 0.3.1
patfla@patfla-N550JV:~/code/tensorflow$ 
```

I seem to be at bazel 0.3.1.

**Comment by flx42** [comment]
On 16.04, you should use CUDA 8.0 instead.

**Comment by patfla** [comment]
I tried that but backed out because something somewhere (don't remember exactly what) told me in effect: you can't get there from here.

Oh yes, it was probably because I didn't find an 8.0-compatible cudNN ...

```
https://developer.nvidia.com/rdp/cudnn-download


Download cuDNN v5.1 RC (June 19, 2016), for CUDA 8.0 RC

cuDNN 5.1 RC for CUDA 8RC will be available soon - please check back again.

```
Yes, that's what sent me back to 7.5.

Ah wait a min:

`Download cuDNN v5 (May 27, 2016), for CUDA 8.0 RC
`

Oh well, it doesn't hurt to go through these drills multiple times.

Thanks @flx42

**Comment by patfla** [comment]
Hmm - installed all of 8.0.  The build gets much further but then this:

```
patfla@patfla-N550JV:~/code/tensorflow$ bazel build -c opt --config=cuda //tensorflow/cc:tutorials_example_trainer 
INFO: Found 1 target...
ERROR: /home/patfla/code/tensorflow/tensorflow/cc/BUILD:199:1: Linking of rule '//tensorflow/cc:tutorials_example_trainer' failed: crosstool_wrapper_driver_is_not_gcc failed: error executing command third_party/gpus/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc -o bazel-out/local_linux-opt/bin/tensorflow/cc/tutorials_example_trainer ... (remaining 805 argument(s) skipped): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
```

crosstool_wrapper_driver_is_not_gcc failed

**Comment by yaroslavvb** [comment]
That's not an actual error, there's should be more info about the true
error from the child script.

There was similar configuration problem in the SO question below, solved by
doing `bazel clean`

http://stackoverflow.com/questions/38794497/tensorflow-bazel-0-3-0-build-cuda-8-0-gtx-1070-fails/38795005#comment64963046_38795005

**Comment by patfla** [comment]
bazel clean worked and I now have tensorflow-0.10.0rc0 installed and running.

How do I tell when bazel clean finishes?  I used bazel clean before; couldn't tell when it finished; and ended up wiping the tree and doing a git clone again.

**Comment by yaroslavvb** [comment]
You don't need to wait, bazel clean; bazel build should work

**Comment by girving** [comment]
Thanks @yaroslavvb for the pointer.  @damienmg Could you comment on whether there is a fixable bazel issue here (or in how we use bazel), or should we close?

**Comment by damienmg** [comment]
Sorry, just back from holidays. I don't see any current issues in Bazel, we did had some change in Bazel structure that caused some error on the cache and could have corrupted his cache.

The recommended clean solution is `bazel clean --expunge` to wipe out everything.

**Comment by girving** [comment]
Thanks @damienmg.  Closing for now.
