### ISSUE TITLE
convert_to_records.py don't write all values into .tfrecords file

### ISSUE THREAD

**Issue by AlexUnderMicrocontRoll** [tensorflow/tensorflow#370]
Hi,
at first i suppose there is a typing mistake in line 56 (dat.shape[0], num_examples) i think it should be (images.shape[0],num_examples). the second thing was that this code did'nt wrote me the depth values into .tfrecords file. I need to pass them as _bytes_feature(str(depth)) after that the value was written into .tfrecords file.

**Comment by vrv** [comment]
Thanks, we'll fix the typo.

The format of tfrecords is not a human-readable string: most likely the depth value is encoded as a field in a _binary_ serialized protocol buffer.

How are you trying to consume the output of tfrecords?

**Comment by AlexUnderMicrocontRoll** [comment]
I tried the fully connected reader example but it fails. I have string Labels so i have to change this code for string Labels. After that i tried to read the .tfrecords File with the read an decode function but with out success. Acctually I'am a little bit disapointed of tensorflow but i will try it again this weekend.

**Comment by vrv** [comment]
If you don't provide us enough information to help you (or why you are disappointed) we can't really help you.  Please feel free to re-open the bug when you have more information that we can use to help you with.
