### ISSUE TITLE
RuntimeError: Encountered unresolved custom op: TensorListFromTensor.Node number 892 (TensorListFromTensor) failed to prepare.

### ISSUE THREAD

**Issue by 2696120622** [tensorflow/tensorflow#37003]
System information

Google Colaboratory   
Tensorflow 2.1.0     

My tf_keras model can be converted to tf.lite successfully as follows.   
`
efficientdet_model= keras.models.load_model('inference_ckpts/ckpts_B1_image-size- 
640/mbconv_head_anchor-extend_1e-6/csv_10_0.7139_0.8459.h5',      
                                            custom_objects=custom_objects,     
                                            compile=False,    
                        )     

export_dir = "tf_save/ckpts_B1_image-size-640/mbconv_head_anchor-extend_1e-6/"     

tf.saved_model.save(efficientdet_model, export_dir)      

model_tfsave = tf.saved_model.load(export_dir)     

concrete_func = model_tfsave.signatures[tf.saved_model.DEFAULT_SERVING_SIGNATURE_DEF_KEY]
     
concrete_func.inputs[1].set_shape([None,511500,4])     

converter = tf.lite.TFLiteConverter.from_concrete_functions([concrete_func])     

converter.optimizations = [tf.lite.Optimize.OPTIMIZE_FOR_SIZE]     

converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS,tf.lite.OpsSet.SELECT_TF_OPS]
     
converter.allow_custom_ops=True     

tflite_model = converter.convert()     

open("inference_tflite/ckpts_B1_image-size-640/mbconv_head_anchor-extend_1e-6/csv_10_0.7139_0.8459.tflite", "wb").write(tflite_model)    

`

However, I encountered a RuntimeError  in inference when running "interpreter.allocate_tensors()" as the following.    
`
interpreter = tf.lite.Interpreter(model_path="inference_tflite/ckpts_B1_image-size-640/mbconv_head_anchor-extend_1e-6/csv_10_0.7139_0.8459.tflite")     

interpreter.allocate_tensors()    
`  
Error.    
`RuntimeError                              Traceback (most recent call last)
<ipython-input-23-e8f284b41149> in <module>()
----> 1 interpreter.allocate_tensors()

1 frames
/usr/local/lib/python3.6/dist-packages/tensorflow_core/lite/python/interpreter.py in allocate_tensors(self)
    245   def allocate_tensors(self):
    246     self._ensure_safe()
--> 247     return self._interpreter.AllocateTensors()
    248 
    249   def _safe_to_run(self):

/usr/local/lib/python3.6/dist-packages/tensorflow_core/lite/python/interpreter_wrapper/tensorflow_wrap_interpreter_wrapper.py in AllocateTensors(self)
    108 
    109     def AllocateTensors(self):
--> 110         return _tensorflow_wrap_interpreter_wrapper.InterpreterWrapper_AllocateTensors(self)
    111 
    112     def Invoke(self):    

RuntimeError: Encountered unresolved custom op: TensorListFromTensor.Node number 892 (TensorListFromTensor) failed to prepare.`    
    
What should I do for this error?

**Comment by Saduf2019** [comment]
@2696120622 please share simple standalone code[with all dependencies] for us to replicate the issue in our environment.

**Comment by 2696120622** [comment]
> @2696120622 please share simple standalone code[with all dependencies] for us to replicate the issue in our environment.
> 
> Also please check this [link](https://github.com/tensorflow/tensorflow/issues/35923) if it helps

I am working with tf 2.1. Code as follows.  
https://colab.research.google.com/drive/16Px4jCUWURdISjG5d3Fv5TVK448L15MO  
Thanks.

**Comment by Saduf2019** [comment]
@2696120622 Could you please provide access to the google drive or share the code directly so i could replicate it in our environment.

**Comment by 2696120622** [comment]
> @2696120622 Could you please provide access to the google drive or share the code directly so i could replicate it in our environment.
My code based on 
> https://github.com/xuannianz/EfficientDet and 
and
> https://github.com/KUASWoodyLIN/EfficientDet/tree/tf2.0.
How to provide access to my google dirve or share my code directly for you?

**Comment by Saduf2019** [comment]
@2696120622 please share your code gist through a colab.

**Comment by 2696120622** [comment]
> @2696120622 please share your code gist through a colab.

What's your e-mail?
I can send my shared link to your email.

**Comment by 2696120622** [comment]
> @2696120622 please share your code gist through a colab.
This is my google drive link. Thanks.

> https://drive.google.com/open?id=1aFTO2lO57pvu8noTCQfXax3PxYt1Axgq

**Comment by 2696120622** [comment]
> @2696120622 please share your code gist through a colab.
This is my google drive link. Thanks.

> https://drive.google.com/open?id=1aFTO2lO57pvu8noTCQfXax3PxYt1Axgq

**Comment by 2696120622** [comment]
@Saduf2019 Could you access my Google drive by above link and replicate my issue?

**Comment by Saduf2019** [comment]
@2696120622 
I have tried replicating the issue, there are too many dependencies,could you please provide with simple standalone code to replicate.

**Comment by 2696120622** [comment]
@Saduf2019 
Thanks a lot. Could you try this link again and download the folder.

> https://drive.google.com/open?id=15i6d9yJ-OAcPROiGEs-RWmG-v6KyQauK

Then,you can train one model with train_test.ipynb and convert it with convert_model_test.ipynb.
And, should I implement the custom op "TensorListFromTensor" by myself according to my issue?

**Comment by 2696120622** [comment]
@haozha111 
I have update my tf to 2.1. However, I still encountered the same error:

> https://github.com/tensorflow/tensorflow/issues/37003#issue-569633708

`RuntimeError: Encountered unresolved custom op: TensorListFromTensor.Node number 892 (TensorListFromTensor) failed to prepare`.
According` to your comment:
> https://github.com/tensorflow/tensorflow/issues/28485#issuecomment-574453673
Maybe I need the new MLIR-based TF Lite converter. How to get this new MLIR-based TF Lite converter?
My project is here.

> https://drive.google.com/open?id=15i6d9yJ-OAcPROiGEs-RWmG-v6KyQauK
You can train one model with train_test.ipynb and convert it with convert_model_test.ipynb.
Thanks a lot!

**Comment by tilakrayal** [comment]
@2696120622 ,
Is this still an issue?
Could you please try to test your code in  latest Tensorflow stable version v.2.8 and let us know if you are facing the same error. Thanks!
