### ISSUE TITLE
Proposal: Modify tf.math.reduce_variance so that it is compatible with ragged tensors

### ISSUE THREAD

**Issue by alexrobomind** [tensorflow/tensorflow#37000]
Sorry for filing this under "bug", but the "feature request" submission option didn't show up for me. Please correct this if possible (I copied the template by hand from the markdown file).

**System information**
- TensorFlow version (you are using): 2.1, but applies to master branch as of opening time
- Are you willing to contribute it (Yes/No): Yes

**Describe the feature and the current behavior/state.**

Currently the variance in the mentioned op is computed as E[(X - E[X])^2]:

https://github.com/tensorflow/tensorflow/blob/c71db95e184447c0008dc007a27d692cd5496d0e/tensorflow/python/ops/math_ops.py#L2112-L2114

Because that requires keepdims == True for the first mean reduction, this is not compatible with ragged tensors. An alternative formulation for the variance could however be E[X**2] - E[X]^2

```
 mean_of_square = reduce_mean(gen_math_ops.square(input_tensor), axis=axis, keepdims=keepdims) 
 square_of_mean = gen_math_ops.square(reduce_mean(input_tensor, axis=axis, keepdims=keepdims)) 
 return mean_of_square - square_of_mean
```

**Will this change the current api? How?**
This might have a reduced numerical stability for Var << Mean, but it could be used at least for ragged tensors in the keepdims == False case. Checking if the tensor is ragged and choosing the implementation based on that would guarantee API stability, but potentially increase maintenance burden later on.

**Who will benefit with this feature?**

Users who want to aggregate statistics over variable-length sequences encoded in ragged tensors.

**Any Other info.**

**Comment by edloper** [comment]
I think it should be possible to add support for keepdims == True to the ragged versions of reduce_xyz.

**Comment by PawelFaron** [comment]
Encountered the same problem with `reduce_std`, would be very useful if this was fixed.
