### ISSUE TITLE
Error with mkl flag

### ISSUE THREAD

**Issue by Expert73** [tensorflow/tensorflow#37015]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10 Pro 18363.657
- TensorFlow installed from (source or binary):  TF from git 2.1
- Python version: 3.8.1
- Installed using virtualenv? pip? conda?: no
- Bazel version (if compiling from source): 0.29
- CUDA/cuDNN version: 10.2/7.6.5
- GPU model and memory: GF 1070 ti
- CPU model: Intel® Core™ i7-9700K
- VS: 2019

**Describe the problem**
All settings as on the site https://www.tensorflow.org/install/source_windows?hl=ru
My command:
bazel build --config=mkl --config=opt --config=cuda --define=no_tensorflow_py_deps=true //tensorflow/tools/pip_package:build_pip_package

At the end of the build process I have the following error
ERROR: C:/tensorflow/tensorflow/python/keras/api/BUILD:115:1: Executing genrule //tensorflow/python/keras/api:keras_python_api_gen_compat_v1 failed (Exit 1)
Traceback (most recent call last):
  File "\\?\C:\Users\Build\AppData\Local\Temp\Bazel.runfiles_ykxci5xn\runfiles\org_tensorflow\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "\\?\C:\Users\Build\AppData\Local\Temp\Bazel.runfiles_ykxci5xn\runfiles\org_tensorflow\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "\\?\C:\Users\Build\AppData\Local\Temp\Bazel.runfiles_ykxci5xn\runfiles\org_tensorflow\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Python38\lib\imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Python38\lib\imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: DLL load failed while importing _pywrap_tensorflow_internal: ═х эрщфхэ єърчрээ√щ ьюфєы№.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "\\?\C:\Users\Build\AppData\Local\Temp\Bazel.runfiles_ykxci5xn\runfiles\org_tensorflow\tensorflow\python\tools\api\generator\create_python_api.py", line 27, in <module>
    from tensorflow.python.tools.api.generator import doc_srcs
  File "\\?\C:\Users\Build\AppData\Local\Temp\Bazel.runfiles_ykxci5xn\runfiles\org_tensorflow\tensorflow\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "\\?\C:\Users\Build\AppData\Local\Temp\Bazel.runfiles_ykxci5xn\runfiles\org_tensorflow\tensorflow\python\pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "\\?\C:\Users\Build\AppData\Local\Temp\Bazel.runfiles_ykxci5xn\runfiles\org_tensorflow\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "\\?\C:\Users\Build\AppData\Local\Temp\Bazel.runfiles_ykxci5xn\runfiles\org_tensorflow\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "\\?\C:\Users\Build\AppData\Local\Temp\Bazel.runfiles_ykxci5xn\runfiles\org_tensorflow\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Python38\lib\imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Python38\lib\imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: DLL load failed while importing _pywrap_tensorflow_internal: ═х эрщфхэ єърчрээ√щ ьюфєы№.

Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.
Target //tensorflow/tools/pip_package:build_pip_package failed to build
ERROR: C:/tensorflow/tensorflow/tools/pip_package/BUILD:223:1 Executing genrule //tensorflow/python/keras/api:keras_python_api_gen_compat_v1 failed (Exit 1)
INFO: Elapsed time: 11991.974s, Critical Path: 9750.03s
INFO: 6217 processes: 6217 local.
FAILED: Build did NOT complete successfully

Without the mkl option, the build completes successfully.
what could be the problem?

**Comment by Saduf2019** [comment]
@Expert73 
Could you please check this [link](https://github.com/tensorflow/tensorflow/issues/36167) and [link](https://github.com/tensorflow/tensorflow/issues/11326) on a similar issue and let us know if it helps. Thanks!

**Comment by Expert73** [comment]
All critical dll in path: cudnn64_7, mkl, msvcp140*. But I have an error.
without mkl in bild command all works super fine. But mkl does not allow you to complete the build.
ImportError: DLL load failed while importing _pywrap_tensorflow_internal
How do I understand which dll?

**Comment by Expert73** [comment]
I tried to build with Mkl on another computer (other hardware without GPU), another operating system (Windows 8.1) - still get the same error. If you look at the latest messages on the forum, several people have already encountered the mkl problem. Can someone authoritatively look at the problem?

**Comment by Expert73** [comment]
I will add that the build with the mkl flag before the error lasts from 6 to 8 hours. Build without this parameter takes 1 hour.
A lot of identical files with very long paths are created. For example, such paths with mkl*.dll I counted more than 10:


\\?\C:\tensorflow\output_dir\external\org_tensorflow\output_dir\external\org_tensorflow\output_dir\external\org_tensorflow\output_dir\external\org_tensorflow\output_dir\external\org_tensorflow\output_dir\external\org_tensorflow\output_dir\external\org_tensorflow\output_dir\external\org_tensorflow\output_dir\external\org_tensorflow\output_dir\external\org_tensorflow\output_dir\external\org_tensorflow\output_dir\external\org_tensorflow\output_dir\external\org_tensorflow\output_dir\external\org_tensorflow\output_dir\external\org_tensorflow\output_dir\external\org_tensorflow\output_dir\external\org_tensorflow\output_dir\external\org_tensorflow\output_dir\external\org_tensorflow\output_dir\external\org_tensorflow\output_dir\external\org_tensorflow\output_dir\external\org_tensorflow\output_dir\external\org_tensorflow\output_dir\external\org_tensorflow\output_dir\external\org_tensorflow\output_dir\external\org_tensorflow\output_dir\external\org_tensorflow\output_dir\external\org_tensorflow\output_dir\external\org_tensorflow\output_dir\execroot\org_tensorflow\output_dir\execroot\org_tensorflow\external\mkl_windows\lib

\\?\C:\tensorflow\output_dir\external\org_tensorflow\output_dir\external\org_tensorflow\output_dir\external\org_tensorflow\output_dir\external\org_tensorflow\output_dir\external\org_tensorflow\output_dir\external\org_tensorflow\output_dir\external\org_tensorflow\output_dir\external\org_tensorflow\output_dir\external\org_tensorflow\output_dir\external\org_tensorflow\output_dir\external\org_tensorflow\output_dir\external\org_tensorflow\output_dir\external\org_tensorflow\output_dir\external\org_tensorflow\output_dir\external\org_tensorflow\output_dir\external\org_tensorflow\output_dir\external\org_tensorflow\output_dir\external\org_tensorflow\output_dir\external\org_tensorflow\output_dir\external\org_tensorflow\output_dir\external\org_tensorflow\output_dir\external\org_tensorflow\output_dir\external\org_tensorflow\output_dir\external\org_tensorflow\output_dir\external\org_tensorflow\output_dir\external\org_tensorflow\output_dir\external\org_tensorflow\output_dir\external\org_tensorflow\output_dir\external\org_tensorflow\output_dir\external\org_tensorflow\output_dir\external\mkl_windows\lib

\\?\C:\tensorflow\output_dir\external\org_tensorflow\output_dir\external\org_tensorflow\output_dir\external\org_tensorflow\output_dir\external\org_tensorflow\output_dir\external\org_tensorflow\output_dir\external\org_tensorflow\output_dir\external\org_tensorflow\output_dir\external\org_tensorflow\output_dir\external\org_tensorflow\output_dir\external\org_tensorflow\output_dir\external\org_tensorflow\output_dir\external\org_tensorflow\output_dir\external\org_tensorflow\output_dir\external\org_tensorflow\output_dir\external\org_tensorflow\output_dir\external\org_tensorflow\output_dir\external\org_tensorflow\output_dir\external\org_tensorflow\output_dir\external\org_tensorflow\output_dir\external\org_tensorflow\output_dir\external\org_tensorflow\output_dir\external\org_tensorflow\output_dir\external\org_tensorflow\output_dir\external\org_tensorflow\output_dir\external\org_tensorflow\output_dir\external\org_tensorflow\output_dir\external\org_tensorflow\output_dir\external\org_tensorflow\output_dir\external\org_tensorflow\output_dir\external\org_tensorflow\output_dir\execroot\org_tensorflow\output_dir\external\mkl_windows\lib

**Comment by Expert73** [comment]
I also tried to install all the libraries from the INTEL® SOFTWARE DEVELOPMENT PRODUCTS series. The same error still occurs - it is specified in the first message. Long paths are also allowed in operating systems. But that doesn't help either.

**Comment by Expert73** [comment]
I even tried using mkl*.dll already compiled by myself and specified them in the TF_MKL_ROOT environment. An error still occurs.

**Comment by Expert73** [comment]
I tried to build with different parameters:
bazel build --config=mkl --config=opt --config=cuda --define=no_tensorflow_py_deps=true //tensorflow/tools/pip_package:build_pip_package

bazel build --config=mkl --config=opt  //tensorflow/tools/pip_package:build_pip_package

bazel build --config=mkl --config=opt --config=cuda //tensorflow/tools/pip_package:build_pip_package

bazel --output_base=output_dir build --config=mkl --config=opt --config=cuda //tensorflow/tools/pip_package:build_pip_package

I still get the same error.

**Comment by Expert73** [comment]
Can someone from Intel Corporation look at this problem?

**Comment by jingxu10** [comment]
Hi,
I'll take a look at this issue.

**Comment by Expert73** [comment]
The build of the software code was excellent for the release version 2.1. The problem was in Path. You can close the problem. Problem solved.

**Comment by CoderEasonLin** [comment]
> The build of the software code was excellent for the release version 2.1. The problem was in Path. You can close the problem. Problem solved.

Hi @Expert73, I just ran into the same error, may I know what is the problem in Path? and how to resolve it. Thanks a lot.
