### ISSUE TITLE
Tensorflow 2.1.0 :  TypeError: __new__() got an unexpected keyword argument 'serialized_options'

### ISSUE THREAD

**Issue by votesappteam** [tensorflow/tensorflow#37019]
I am facing an error while importing tensorflow-2.1.0 (CPU) with Python 3.6 in Ubuntu 18.
 protobuf Version: 3.11.3
Tried many solutions provided in the same Tensorflow GitHub issue pages..But none were useful. 
I dont have any NVIDIA, CUDA etc.. (I dont want to install them as i would like to go with CPU)

Following errors appeared.
---------------------------------
[Mon Feb 24 11:44:52.926212 2020] [wsgi:error] [pid 5520:tid 140127778391808] [remote 127.0.0.1:34372] mod_wsgi (pid=5520): Exception occurred processing WSGI script '/var/www/testnig/service.wsgi'.
[Mon Feb 24 11:44:52.927298 2020] [wsgi:error] [pid 5520:tid 140127778391808] [remote 127.0.0.1:34372] Traceback (most recent call last):
[Mon Feb 24 11:44:52.927347 2020] [wsgi:error] [pid 5520:tid 140127778391808] [remote 127.0.0.1:34372]   File "/var/www/testnig/service.wsgi", line 9, in <module>
[Mon Feb 24 11:44:52.927352 2020] [wsgi:error] [pid 5520:tid 140127778391808] [remote 127.0.0.1:34372]     from service import app as application
[Mon Feb 24 11:44:52.927358 2020] [wsgi:error] [pid 5520:tid 140127778391808] [remote 127.0.0.1:34372]   File "/var/www/testnig/service.py", line 11, in <module>
[Mon Feb 24 11:44:52.927362 2020] [wsgi:error] [pid 5520:tid 140127778391808] [remote 127.0.0.1:34372]     import classify
[Mon Feb 24 11:44:52.927367 2020] [wsgi:error] [pid 5520:tid 140127778391808] [remote 127.0.0.1:34372]   File "/var/www/testnig/classify.py", line 3, in <module>
[Mon Feb 24 11:44:52.927370 2020] [wsgi:error] [pid 5520:tid 140127778391808] [remote 127.0.0.1:34372]     import tensorflow as tf
[Mon Feb 24 11:44:52.927376 2020] [wsgi:error] [pid 5520:tid 140127778391808] [remote 127.0.0.1:34372]   File "/var/www/testnig/venv/lib/python3.6/site-packages/tensorflow/__init__.py", line 98, in <module>
[Mon Feb 24 11:44:52.927379 2020] [wsgi:error] [pid 5520:tid 140127778391808] [remote 127.0.0.1:34372]     from tensorflow_core import *
[Mon Feb 24 11:44:52.927384 2020] [wsgi:error] [pid 5520:tid 140127778391808] [remote 127.0.0.1:34372]   File "/var/www/testnig/venv/lib/python3.6/site-packages/tensorflow_core/__init__.py", line 42, in <module>
[Mon Feb 24 11:44:52.927388 2020] [wsgi:error] [pid 5520:tid 140127778391808] [remote 127.0.0.1:34372]     from . _api.v2 import audio
[Mon Feb 24 11:44:52.927393 2020] [wsgi:error] [pid 5520:tid 140127778391808] [remote 127.0.0.1:34372]   File "/var/www/testnig/venv/lib/python3.6/site-packages/tensorflow_core/_api/v2/audio/__init__.py", line 10, in <module>
[Mon Feb 24 11:44:52.927397 2020] [wsgi:error] [pid 5520:tid 140127778391808] [remote 127.0.0.1:34372]     from tensorflow.python.ops.gen_audio_ops import decode_wav
[Mon Feb 24 11:44:52.927402 2020] [wsgi:error] [pid 5520:tid 140127778391808] [remote 127.0.0.1:34372]   File "/var/www/testnig/venv/lib/python3.6/site-packages/tensorflow_core/python/ops/gen_audio_ops.py", line 11, in <module>
[Mon Feb 24 11:44:52.927406 2020] [wsgi:error] [pid 5520:tid 140127778391808] [remote 127.0.0.1:34372]     from tensorflow.python.eager import context as _context
[Mon Feb 24 11:44:52.927411 2020] [wsgi:error] [pid 5520:tid 140127778391808] [remote 127.0.0.1:34372]   File "/var/www/testnig/venv/lib/python3.6/site-packages/tensorflow_core/python/eager/context.py", line 29, in <module>
[Mon Feb 24 11:44:52.927414 2020] [wsgi:error] [pid 5520:tid 140127778391808] [remote 127.0.0.1:34372]     from tensorflow.core.protobuf import config_pb2
[Mon Feb 24 11:44:52.927420 2020] [wsgi:error] [pid 5520:tid 140127778391808] [remote 127.0.0.1:34372]   File "/var/www/testnig/venv/lib/python3.6/site-packages/tensorflow_core/core/protobuf/config_pb2.py", line 16, in <module>
[Mon Feb 24 11:44:52.927423 2020] [wsgi:error] [pid 5520:tid 140127778391808] [remote 127.0.0.1:34372]     from tensorflow.core.framework import cost_graph_pb2 as tensorflow_dot_core_dot_framework_dot_cost__graph__pb2
[Mon Feb 24 11:44:52.927436 2020] [wsgi:error] [pid 5520:tid 140127778391808] [remote 127.0.0.1:34372]   File "/var/www/testnig/venv/lib/python3.6/site-packages/tensorflow_core/core/framework/cost_graph_pb2.py", line 16, in <module>
[Mon Feb 24 11:44:52.927440 2020] [wsgi:error] [pid 5520:tid 140127778391808] [remote 127.0.0.1:34372]     from tensorflow.core.framework import tensor_shape_pb2 as tensorflow_dot_core_dot_framework_dot_tensor__shape__pb2
[Mon Feb 24 11:44:52.927445 2020] [wsgi:error] [pid 5520:tid 140127778391808] [remote 127.0.0.1:34372]   File "/var/www/testnig/venv/lib/python3.6/site-packages/tensorflow_core/core/framework/tensor_shape_pb2.py", line 23, in <module>
[Mon Feb 24 11:44:52.927449 2020] [wsgi:error] [pid 5520:tid 140127778391808] [remote 127.0.0.1:34372]     serialized_pb=_b('\\n,tensorflow/core/framework/tensor_shape.proto\\x12\\ntensorflow\\"z\\n\\x10TensorShapeProto\\x12-\\n\\x03\\x64im\\x18\\x02 \\x03(\\x0b\\x32 .tensorflow.TensorShapeProto.Dim\\x12\\x14\\n\\x0cunknown_rank\\x18\\x03 \\x01(\\x08\\x1a!\\n\\x03\\x44im\\x12\\x0c\\n\\x04size\\x18\\x01 \\x01(\\x03\\x12\\x0c\\n\\x04name\\x18\\x02 \\x01(\\tBq\\n\\x18org.tensorflow.frameworkB\\x11TensorShapeProtosP\\x01Z=github.com/tensorflow/tensorflow/tensorflow/go/core/framework\\xf8\\x01\\x01\\x62\\x06proto3')
[Mon Feb 24 11:44:52.927464 2020] [wsgi:error] [pid 5520:tid 140127778391808] [remote **127.0.0.1:34372] **TypeError: __new__() got an unexpected keyword argument *emphasized text*'serialized_options'****

Steps to reproduce : (I am using Apache2, Flask & python3 for NSFW detection). However following are the simplest ways to reproduce. 
 1. In Ubuntu 18, install python 3.6 and create a Virtualenv. Activate Virtualenv
 2. pip3 install tensorflow
 3. Clone or Download GIT --> github.com/minto5050/NSFW-detection 
4. python3 classify.py test_image.jpg

Please let me know if you need any other information

**Comment by Saduf2019** [comment]
@votesappteam 
please refer to this [link](https://github.com/tensorflow/models/issues/3995) related to protobuf, let us know if it helps resolve your issue.

**Comment by votesappteam** [comment]
@Saduf2019 
I have tried all of the solution you mentioned.
Please understand those were all Tensorflow version less than 2.
None of the solution helped.
Please help.

**Comment by Saduf2019** [comment]
@votesappteam 
I tried replicating the code shared by you and face a different error,please refer to [the gist](https://colab.sandbox.google.com/gist/Saduf2019/967ba100b6072abcfc5b11fdaff93f04/untitled62.ipynb) for the same

**Comment by votesappteam** [comment]
Hi Sadu,
The original code Github is not compatible with Tensorflow version 2.
Please replace code in classify.py with below:

import os, sys

import tensorflow as tf
#https://github.com/minto5050/NSFW-detection
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'
tf.config.optimizer.set_jit(True)

    # change this as you see fit
image_path = img

    # Read in the image_data
image_data = tf.io.gfile.GFile(image_path, 'rb').read()

    # Loads label file, strips off carriage return
label_lines = [line.rstrip() for line
                   in tf.io.gfile.GFile("retrained_labels.txt")]

    # Unpersists graph from file
with tf.io.gfile.GFile("retrained_graph.pb", 'rb') as f:
    graph_def = tf.compat.v1.GraphDef()
    graph_def.ParseFromString(f.read())
    tf.import_graph_def(graph_def, name='')

with tf.compat.v1.Session() as sess:
        # Feed the image_data as input to the graph and get first prediction
    softmax_tensor = sess.graph.get_tensor_by_name('final_result:0')

    predictions = sess.run(softmax_tensor, \
                               {'DecodeJpeg/contents:0': image_data})

        # Sort to show labels of first prediction in order of confidence
    top_k = predictions[0].argsort()[-len(predictions[0]):][::-1]
    scoreDict = []
    for node_id in top_k:
        human_string = label_lines[node_id]
        score = predictions[0][node_id]
        scoreDict.append(human_string+":"+str(score))
        print('%s (score = %.5f)' % (human_string, score))

**Comment by Saduf2019** [comment]
@votesappteam 
could you please provide us with simple standalone indented code to replicate your issue in our local or share a gist of the error, if possible in colab for us to analyse it.

**Comment by Saduf2019** [comment]
@votesappteam
could you please update as per above comment

**Comment by votesappteam** [comment]
I will respond

**Comment by Saduf2019** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Comment by Aicha-Maa** [comment]
I'm having the same issue with tensorflow version 2.3.1 is there any solution? 
Thank you in advance
