### ISSUE TITLE
tf-nightly not updated?

### ISSUE THREAD

**Issue by wuhy08** [tensorflow/tensorflow#37027]
Just curious, tf-nightly is PyPI is not updated since Feb. 19. What's going on? Can we expect the update any time soon?

Thank you!

**Comment by Saduf2019** [comment]
@wuhy08,
Not sure what caused the delay, although I see that the latest nightly for [2020/02/25](https://pypi.org/project/tf-nightly/2.2.0.dev20200225/) has been released 3 hours ago.

Please feel free to close the issue if this resolves your query. Thanks!

**Comment by wuhy08** [comment]
Thank you!
