### ISSUE TITLE
Shape information is lost with DepthwiseConv2D

### ISSUE THREAD

**Issue by jnd77** [tensorflow/tensorflow#37039]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information** 
- Have I written custom code (as opposed to using a stock
example script provided in TensorFlow): Yes 
- OS Platform and Distribution (e.g.,
Linux Ubuntu 16.04): Ubuntu 18.04
- TensorFlow installed from (source or
binary): source 
- TensorFlow version (use command below): 1.15 
- CUDA/cuDNN version: 10.2
- GPU model and memory: RTX 2060

**Describe the current behavior**

In some cases (use_bias=False, dilation_rate > 1, data_format='channels_first'), the shape information is lost after DepthwiseConv2D. 

**Describe the expected behavior**

It should behave the same way for channels_last and channels_first.
When running the code below, channels_last prints `shape=(?, ?, ?, 32)` and channels_first prints `shape=(?, ?, ?, ?)`. It should be `shape=(?, 32, ?, ?)`

**Standalone code to reproduce the issue** 

[Here for the gist](https://colab.research.google.com/gist/jnd77/84932ac25671f8b5b59acdcb2f0e5afd/untitled1.ipynb) 

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by gowthamkpr** [comment]
Was able to reproduce this issue with Tensorflow 2.0. Heres the [gist](https://colab.sandbox.google.com/gist/gowthamkpr/ac206fc5c714a86002377c7eb180a4fd/untitled1.ipynb).

**Comment by ymodak** [comment]
Executing the script on cpu gives the correct results:
```python
Tensor("depthwise_conv2d/Identity:0", shape=(None, None, None, 32), dtype=float32)
Tensor("depthwise_conv2d_1/Identity:0", shape=(None, 32, None, None), dtype=float32)
```

**Comment by tanzhenyu** [comment]
Thanks for the report! We wouldn't be able to make 1.x changes at this moment (or back-porting). This works find in tf-nightly, please check the below code:
```python
# Try first with channels_last
input_tensor = np.random.random((32, 12, 12, 32)).astype(np.float32)
input_tensor_shape = (None, None, None, 32)
depthwise_conv = tf.keras.layers.DepthwiseConv2D(kernel_size=(3, 3), data_format='channels_last',
                                                  dilation_rate=(2, 2), use_bias=False, input_shape=input_tensor_shape[1:])
print(depthwise_conv(input_tensor).shape)

# Then with channels_first
input_tensor = np.random.random((32, 32, 12, 12)).astype(np.float32)
input_tensor_shape = (None, 32, None, None)
depthwise_conv = tf.keras.layers.DepthwiseConv2D(kernel_size=(3, 3), data_format='channels_first',
                                                  dilation_rate=(2, 2), use_bias=False, input_shape=input_tensor_shape[1:])
print(depthwise_conv(input_tensor).shape)
```

```
(32, 8, 8, 32)
(32, 32, 8, 8)
```

**Comment by jnd77** [comment]
@tanzhenyu Thanks for looking at the ticket.
But your code runs in eager execution, so obviously the numpy array has a shape.
Please check the [gist](https://colab.sandbox.google.com/gist/gowthamkpr/ac206fc5c714a86002377c7eb180a4fd/untitled1.ipynb) @gowthamkpr pepared with TF 2 (and still fails with tf-nightly)

**Comment by tanzhenyu** [comment]
Looks like the issue comes from backend.depthwise_conv2d, using tf.transpose(x, (0, 3, 1, 2))

**Comment by jnd77** [comment]
@tanzhenyu @gadagashwini Possible to add the flag TF 2.2 so this ticket does not get forgotten ? Thanks a lot. :)

**Comment by lgeiger** [comment]
> Looks like the issue comes from backend.depthwise_conv2d, using tf.transpose(x, (0, 3, 1, 2))

@tanzhenyu Indeed the issue comes from `backend.depthwise_conv2d`, but I don't think is due to the transpose since the issues doesn't seem to appear when using `dilation_rate=1`.

**Comment by goldiegadde** [comment]
@jnd77 the issue seems to be resolved with the latest tf-nightly, here is a [gist](https://colab.research.google.com/gist/goldiegadde/3ab3465eb24bfb800861cd8990851235/github-issue-37039.ipynb)
Can you please take a look and close if this is indeed resolved ?

**Comment by jnd77** [comment]
Thanks @goldiegadde.
