### ISSUE TITLE
UnsatisfiedLinkError on nightly build of tensorflow-lite

### ISSUE THREAD

**Issue by landicefu** [tensorflow/tensorflow#37038]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information** 
- Mobile device: Android
- TensorFlow installed from: Gradle (jcenter)

**Describe the current behavior**
On sample project, we ran into UnsatisfiedLinkError "/lib/arm64/libtensorflowlite_gpu_jni.so" using nightly build. If we switch to 2.1.0 that doesn't have the problem.
On Android guide to tensorflow-lite it also suggest to use nightly build, and I don't think this is good for production builds.
https://www.tensorflow.org/lite/guide/android

**Describe the expected behavior**
Doesn't run into UnsatisfiedLinkError at runtime.

**Standalone code to reproduce the issue** 
Your sample project

**Comment by gorogaron** [comment]
I have the same problem, couldn't find any soultion yet.

**Comment by hungyanbin** [comment]
> I have the same problem, couldn't find any soultion yet. It comes up when I try to create a new GPU delegate.

You can just use "org.tensorflow:tensorflow-lite:2.1.0" and "org.tensorflow:tensorflow-lite-gpu:2.1.0", nightly build will break.

**Comment by jdduke** [comment]
Odd, I haven't been able to repro. Can you try [clearing your gradle cache](https://stackoverflow.com/questions/23025433/how-to-clear-gradle-cache) and rebulding? Also, what device are you using to test?

I successfully built and deployed using:
```
cd examples/lite/examples/image_classification/android
./gradlew cleanBuildCachce
./gradlew build
adb install -r -d  ./app/build/outputs/apk/debug/app-debug.apk
```

**Comment by jdduke** [comment]
Also note that the GPU and base TFLite dependencies must have matching versions, i.e.,
```
    implementation 'org.tensorflow:tensorflow-lite:0.0.0-nightly'
    implementation 'org.tensorflow:tensorflow-lite-gpu:0.0.0-nightly'
```
or
```
    implementation 'org.tensorflow:tensorflow-lite:2.1.0'
    implementation 'org.tensorflow:tensorflow-lite-gpu:2.1.0'
```

**Comment by freedomtan** [comment]
I guess this is the same as issue https://github.com/tensorflow/tensorflow/issues/37161. And it's addressed by PR https://github.com/tensorflow/tensorflow/pull/37033.

**Comment by terryheo** [comment]
https://github.com/tensorflow/tensorflow/pull/37033 was merged. Let us know if you still have the issue.

**Comment by gorogaron** [comment]
Thanks, the mentioned PR has solved the problem for me!
