### ISSUE TITLE
tf_sess.run takes 5 seconds

### ISSUE THREAD

**Issue by HebeVinny** [tensorflow/tensorflow#37036]
# tf_sess.run very slow 
tf_config = tf.ConfigProto()
tf_config.gpu_options.allow_growth = True
tf_sess = tf.Session(config=tf_config)
tf.import_graph_def(trt_graph, name='')

tf_input = tf_sess.graph.get_tensor_by_name(input_names[0] + ':0')
tf_scores = tf_sess.graph.get_tensor_by_name('detection_scores:0')
tf_boxes = tf_sess.graph.get_tensor_by_name('detection_boxes:0')
tf_classes = tf_sess.graph.get_tensor_by_name('detection_classes:0')
tf_num_detections = tf_sess.graph.get_tensor_by_name('num_detections:0')

tf_input.shape.as_list()

def detection(IMAGE_PATH):
    start_time = datetime.datetime.now()

    image = cv2.imread(IMAGE_PATH)
    image = cv2.resize(image, (300, 300))

    scores, boxes, classes, num_detections = tf_sess.run([tf_scores, tf_boxes, tf_classes, tf_num_detections], feed_dict={
    tf_input: image[None, ...]
})
    boxes = boxes[0]  # index by 0 to remove batch dimension
    scores = scores[0]
    classes = classes[0]
    num_detections = int(num_detections[0])

    #print(boxes)
    #print(scores)
    #print(classes)
    #print(num_detections)
    for num in range(num_detections):
       if classes[num]==1:
          print('person')
          #return 'person'
       if classes[num]==62:
          print('chair')
          #return 'chair'
       if classes[num] != 1 and classes[num] != 62 :
          print(classes[num])
    end_time = datetime.datetime.now()
    diff = (end_time - start_time)
    print(diff)

detection(IMAGE_PATH)

this code takes around 5 seconds.Could it be reduce in timing?

**Comment by gadagashwini** [comment]
@HebeVinny, Can you provide the complete standalone code and tensorflow version to analyze the reported issue.Thanks

**Comment by gadagashwini** [comment]
@HebeVinny, Please update for the above comment. Thanks

**Comment by gadagashwini** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
