### ISSUE TITLE
tf.contrib.learn.TensorFlowRNNRegressor: "inputs must be a list!"

### ISSUE THREAD

**Issue by zhedongzheng** [tensorflow/tensorflow#3703]
> import numpy as np
> from tensorflow.contrib.learn import TensorFlowRNNRegressor
> import tensorflow as tf
> X = [[1, 2, 3, 4, 5], [1, 2, 3, 4, 5], [1, 2, 3, 4, 5]]
> y = [1, 1, 1]
> regr = TensorFlowRNNRegressor(rnn_size=5)
> regr.fit(np.array(X), np.array(y))

**throws error:
Traceback (most recent call last):
  File "rnn_test.py", line 9, in <module>
    regr.fit(np.array(X), np.array(y))
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/contrib/learn/python/learn/estimators/base.py", line 160, in fit
    monitors=monitors)
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/contrib/learn/python/learn/estimators/estimator.py", line 449, in _train_model
    train_op, loss_op = self._get_train_ops(features, targets)
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/contrib/learn/python/learn/estimators/estimator.py", line 673, in _get_train_ops
    _, loss, train_op = self._call_model_fn(features, targets, ModeKeys.TRAIN)
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/contrib/learn/python/learn/estimators/estimator.py", line 656, in _call_model_fn
    features, targets, mode=mode)
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/contrib/learn/python/learn/estimators/base.py", line 369, in _model_fn
    predictions, loss = model_fn(features, targets)
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/contrib/learn/python/learn/estimators/rnn.py", line 205, in _model_fn
    self.initial_state)(X, y)
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/contrib/learn/python/learn/models.py", line 399, in rnn_estimator
    initial_state=initial_state)
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/ops/rnn.py", line 98, in rnn
    raise TypeError("inputs must be a list")
TypeError: inputs must be a list**

But no problem with DNNRegressor
Thank you in advance for your time

**Comment by girving** [comment]
The issue template asks for some information, including the version of TensorFlow, platform, etc.  Can you add this information?  TensorFlow at HEAD has a different error message, so it's possible something has been fixed (or changed) in the mean time.

**Comment by jayswinney** [comment]
I just reproduced this error using 0.8.0

Some system info:

CPython 3.4.4
IPython 4.1.2

compiler   : GCC 4.4.7 20120313 (Red Hat 4.4.7-1)
system     : Linux (Ubuntu 16.04)
release    : 4.4.0-31-generic
machine    : x86_64
processor  : x86_64
CPU cores  : 4
interpreter: 64bit

**Comment by girving** [comment]
@jayswinney 0.8.0 is two releases ago.  Could you try again with 0.10?

**Comment by jayswinney** [comment]
upgrading to '0.10.0rc0' gives a similar error to the original

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-7-8e0e5d002613> in <module>()
      2 y = [1, 1, 1]
      3 regr = TensorFlowRNNRegressor(rnn_size=5, num_layers=3)
----> 4 regr.fit(np.array(X), np.array(y))

/home/jay/.local/lib/python3.5/site-packages/tensorflow/contrib/learn/python/learn/estimators/base.py in fit(self, x, y, steps, monitors, logdir)
    164                       feed_fn=self._data_feeder.get_feed_dict_fn(),
    165                       steps=steps or self.steps,
--> 166                       monitors=monitors)
    167     return self
    168 

/home/jay/.local/lib/python3.5/site-packages/tensorflow/contrib/learn/python/learn/estimators/estimator.py in _train_model(self, input_fn, steps, feed_fn, init_op, init_feed_fn, init_fn, device_fn, monitors, log_every_steps, fail_on_nan_loss, max_steps)
    548       features, targets = input_fn()
    549       self._check_inputs(features, targets)
--> 550       train_op, loss_op = self._get_train_ops(features, targets)
    551 
    552       # Add default monitors.

/home/jay/.local/lib/python3.5/site-packages/tensorflow/contrib/learn/python/learn/estimators/estimator.py in _get_train_ops(self, features, targets)
    818       Tuple of train `Operation` and loss `Tensor`.
    819     """
--> 820     _, loss, train_op = self._call_model_fn(features, targets, ModeKeys.TRAIN)
    821     return train_op, loss
    822 

/home/jay/.local/lib/python3.5/site-packages/tensorflow/contrib/learn/python/learn/estimators/estimator.py in _call_model_fn(self, features, targets, mode)
    801         return self._model_fn(features, targets, mode=mode, params=self.params)
    802       else:
--> 803         return self._model_fn(features, targets, mode=mode)
    804     return self._model_fn(features, targets)
    805 

/home/jay/.local/lib/python3.5/site-packages/tensorflow/contrib/learn/python/learn/estimators/base.py in _model_fn(features, targets, mode)
    376       if self.class_weight is not None:
    377         constant_op.constant(self.class_weight, name='class_weight')
--> 378       predictions, loss = model_fn(features, targets)
    379       if isinstance(self.learning_rate, types.FunctionType):
    380         learning_rate = self.learning_rate(contrib_framework.get_global_step())

/home/jay/.local/lib/python3.5/site-packages/tensorflow/contrib/learn/python/learn/estimators/rnn.py in _model_fn(self, x, y)
    236                                 models.linear_regression, self.sequence_length,
    237                                 self.initial_state, self.attn_length,
--> 238                                 self.attn_size, self.attn_vec_size)(x, y)
    239 
    240   @property

/home/jay/.local/lib/python3.5/site-packages/tensorflow/contrib/learn/python/learn/models.py in rnn_estimator(x, y)
    410                            dtype=dtypes.float32,
    411                            sequence_length=sequence_length,
--> 412                            initial_state=initial_state)
    413     return target_predictor_fn(encoding, y)
    414 

/home/jay/.local/lib/python3.5/site-packages/tensorflow/python/ops/rnn.py in rnn(cell, inputs, initial_state, dtype, sequence_length, scope)
    128     raise TypeError("cell must be an instance of RNNCell")
    129   if not nest.is_sequence(inputs):
--> 130     raise TypeError("inputs must be a sequence")
    131   if not inputs:
    132     raise ValueError("inputs must not be empty")

TypeError: inputs must be a sequence
```

**Comment by girving** [comment]
So the error says an argument must be a sequence, but you're passing a numpy array.  What happens if you pass a sequence (such as a list)?

**Comment by jayswinney** [comment]
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-14-eeb41cd0423a> in <module>()
      2 y = [1, 1, 1]
      3 regr = TensorFlowRNNRegressor(rnn_size=5)
----> 4 regr.fit(tf.unpack(np.array(X), axis=1), tf.unpack(np.array(y), axis=0))

/home/jay/.local/lib/python3.5/site-packages/tensorflow/contrib/learn/python/learn/estimators/base.py in fit(self, x, y, steps, monitors, logdir)
    160       self._model_dir = logdir
    161     self._data_feeder = setup_train_data_feeder(
--> 162         x, y, n_classes=self.n_classes, batch_size=self.batch_size)
    163     self._train_model(input_fn=self._data_feeder.input_builder,
    164                       feed_fn=self._data_feeder.get_feed_dict_fn(),

/home/jay/.local/lib/python3.5/site-packages/tensorflow/contrib/learn/python/learn/learn_io/data_feeder.py in setup_train_data_feeder(x, y, n_classes, batch_size, shuffle, epochs)
    114     return StreamingDataFeeder(x, y, n_classes, batch_size)
    115   return data_feeder_cls(
--> 116       x, y, n_classes, batch_size, shuffle=shuffle, epochs=epochs)
    117 
    118 

/home/jay/.local/lib/python3.5/site-packages/tensorflow/contrib/learn/python/learn/learn_io/data_feeder.py in __init__(self, x, y, n_classes, batch_size, shuffle, random_state, epochs)
    236       output_dtype: dtype of output.
    237     """
--> 238     x_dtype = np.int64 if x.dtype == np.int64 else np.float32
    239     y_dtype = (
    240         np.int64 if n_classes is not None and n_classes > 1 else np.float32)

AttributeError: 'list' object has no attribute 'dtype'
```

**Comment by girving** [comment]
@martinwicke This is probably user error, but it at least seems like a bug that we don't autoconvert lists to numpy arrays here.

**Comment by martinwicke** [comment]
The TensorFlow* Estimator classes are deprecated. We don't have a direct replacement for it yet (we should soon). @ilblackdragon or @terrytangyuan may have advice in the meantime.

**Comment by jayswinney** [comment]
If anyone comes here looking for an RNN to run the above example, this is about the shortest script I could come up with:


```python
import numpy as np
import tensorflow as tf

EPOCHS = 10000
PRINT_STEP = 1000

data = np.array([[1, 2, 3, 4, 5], [ 2, 3, 4, 5, 6], [3, 4, 5, 6, 7]])
target = np.array([[6], [7], [8]])

x_ = tf.placeholder(tf.float32, [None, data.shape[1]])
y_ = tf.placeholder(tf.float32, [None, 1])

cell = tf.nn.rnn_cell.BasicRNNCell(num_units=data.shape[1])

outputs, states = tf.nn.rnn(cell, [x_], dtype=tf.float32)
outputs = outputs[-1]

W = tf.Variable(tf.random_normal([data.shape[1], 1]))     
b = tf.Variable(tf.random_normal([1]))

y = tf.matmul(outputs, W) + b

cost = tf.reduce_mean(tf.square(y - y_))
train_op = tf.train.RMSPropOptimizer(0.005, 0.2).minimize(cost)

with tf.Session() as sess:
    tf.initialize_all_variables().run()
    for i in range(EPOCHS):
        sess.run(train_op, feed_dict={x_:data, y_:target})
        if i % PRINT_STEP == 0:
            c = sess.run(cost, feed_dict={x_:data, y_:target})
            print('training cost:', c)
            
    response = sess.run(y, feed_dict={x_:data, y_:target})
    print(response)

```

run on version 0.10.0rc0

**Comment by glori0us** [comment]
I also across this problem. Could anyone tell me how to solve this ?

**Comment by pfaucon** [comment]
I've come across the problem as well, it looks like np.array's are not collections.Sequence's I tried implementing a hacky wrapper around list that also has a dtype argument but that didn't fix the problem either.  It looks to me (through code tracing) that for some reason a Tensor is being passed into is_sequence, and the tensor is not a sequence.  Therefore regardless of the input provided the method will fail (I'm trying to use tf.contrib.learn.TensorFlowRNNClassifier() -> .fit())

**Comment by pohsiang** [comment]
Is there any update for this issue? I've also across this problem as well.

**Comment by zhedongzheng** [comment]
Well I find that if you use tf.split() to split your array into a list of arrays, then actually it will work. So I guess a list of arrays is what the machine means "sequence".

**Comment by zhedongzheng** [comment]
```python
import numpy as np
from tensorflow.contrib.learn import TensorFlowRNNRegressor
import tensorflow as tf

def rnn_input_fn(x):
	return tf.split(1, 5, x)

X = [[1, 2, 3, 4, 5], [1, 2, 3, 4, 5], [1, 2, 3, 4, 5]]
y = [1, 1, 1]

X = np.array(list(X), dtype=np.int32)
y = np.array(list(y), dtype=np.int32)

regr = TensorFlowRNNRegressor(n_classes=2, rnn_size=10, input_op_fn=rnn_input_fn)
regr.fit(X, y)
```

This is how I make this example work.

**Comment by pfaucon** [comment]
you can get example code here, this is how I made it work (and figured out what the problem was) https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/learn/python/learn/estimators/rnn_test.py

The main thing to notice is that you MUST have an input_op_fn even though it is a python optional (the default operation currently does not work).

https://github.com/tensorflow/tensorflow/pull/4608

**Comment by martinwicke** [comment]
Note that I am in the process of deleting TensorFlow*Estimator, so I
wouldn't spend too much effort on it. It's been deprecated for a while --
please use Estimator directly.

**Comment by pfaucon** [comment]
when you say *Estimator do you mean *Regressor?

**Comment by terrytangyuan** [comment]
All subclasses of TensorFlowEstimator
