### ISSUE TITLE
The output of the Conv2D layer in backend TensorFlow is different from that in Theano and CNTK

### ISSUE THREAD

**Issue by Justobe** [tensorflow/tensorflow#37048]
## System Information

- CUDA Version 10.1.168
- Python==3.6.8
- numpy==1.14.6
- tensorflow-gpu==1.14.0
- theano==1.0.4
- cntk-gpu==2.7
- gcc== 5.4.0
- Linux version 4.15.0-52-generic

## Description

Hi, I encountered a problem when I used a variant of the AlexNet model for image classification task. The prediction result of backend TensorFlow is different from backend Theano and backend CNTK in  Keras. The input picture is sampled from the CIFAR10 DataSet. 

The outputs ( Top-1 prediction) of three backends are shown below（Prediction label id and  Probability ）:

**TensorFlow**: 2, 0.9999998807907104

**CNTK**:  6,1.0

**Theano**: 6,1.0

It seems that there is something wrong with Tensorflow. Then I put image into the model and recorded the ouputs of each layers to see how this happens. It seems that the outputs on CNTK and Theano are very close, but for Tensorflow, the outputs of a conv2d layer and all the layers after this layer are very different from CNTK and Theano.

The results are attached below.

Theano vs CNTK
![image-20200225181539716](https://user-images.githubusercontent.com/15032308/75246315-7d1a1500-580a-11ea-978e-93224948d974.png)

TensorFlow vs Theano

![image-20200225181451774](https://user-images.githubusercontent.com/15032308/75246369-94f19900-580a-11ea-871e-a401d652fbc4.png)

TensorFlow vs CNTK
![image-20200225181519926](https://user-images.githubusercontent.com/15032308/75246356-8efbb800-580a-11ea-9efe-a8c29708465f.png)

The delta column shows the discrepancy, which is calculated as:
![MAD](https://user-images.githubusercontent.com/15032308/75246389-9f139780-580a-11ea-8c41-ae22458272f7.png)

Based on the results, the deviation seems to be caused by conv2d of tensorflow backend.

## To Reproduce
The code of getting prediction result of each backend  is really simple. 

get_prediction.py :

```python
import os
import sys
import numpy as np
from PIL import Image
bk = sys.argv[1]
os.environ['KERAS_BACKEND'] = bk
os.environ["CUDA_DEVICE_ORDER"] = "PCI_BUS_ID"
os.environ["CUDA_VISIBLE_DEVICES"] = "0"

import keras
from keras import backend as K
print("Using backend :{}".format(K.backend()))


def custom_objects():

    def no_activation(x):
        return x

    def leakyrelu(x):
        import keras.backend as K
        return K.relu(x, alpha=0.01)

    objects = {}
    objects['no_activation'] = no_activation
    objects['leakyrelu'] = leakyrelu
    return objects


def image_resize(x, shape):
    x_return = []
    for x_test in x:
        tmp = np.copy(x_test)
        img = Image.fromarray(tmp.astype('uint8')).convert('RGB')
        img = img.resize(shape, Image.ANTIALIAS)
        x_return.append(np.array(img))
    return np.array(x_return)


base_model = keras.models.load_model("alexnet-cifar10_origin0-ARep4-ARep6-ARem1-LC6.h5",custom_objects=custom_objects())
adam = keras.optimizers.Adagrad(lr=0.01, epsilon=None, decay=0.0)
base_model.compile(loss='categorical_crossentropy', optimizer=adam, metrics=['accuracy'])


imagename = 'cifar10-1042.png'
img = Image.open(imagename)
img = img.resize((32,32), Image.ANTIALIAS)
x_test = np.array(img)
select_data = np.expand_dims(x_test, axis=0)

prediction = base_model.predict(select_data)
pred = np.argsort(prediction[0])
print(pred)
print(f"Prediction of {bk}: {pred[-1]},{prediction[0][pred[-1]]}")
```

You can run the script like this ():

> python get_prediction.py tensorflow

Change tensorflow to 'theano' and 'cntk'

I provide scripts to get outputs of the middle layers and calculate the difference:
[tensorflow-conv2d.zip](https://github.com/tensorflow/tensorflow/files/4256311/tensorflow-conv2d.zip)

The model used in scripts can be downloads from：https://send.firefox.com/download/c01db9a2b4773d8b/#ME176P7KQp4J6DmB46xBBg
Thanks in advance.

**Comment by amahendrakar** [comment]
@Justobe,
I am facing an error stating `ValueError: Unknown activation function:no_activation` while loading the given h5 file. Please find the Gist of it [here](https://colab.research.google.com/gist/amahendrakar/f3c6871c8d8a1bbc9e7b27321ab600eb/37048.ipynb). 

I am facing the same error while running it on the local environment too. Thanks!

**Comment by Justobe** [comment]
@amahendrakar  Thank you very much for your reply. I'm so sorry that I missed the definition of the no_activation function in custom_objects. I have updated the code of the custom_objects function in the issue and re-uploaded the attachment.  ^_^

**Comment by jvishnuvardhan** [comment]
@Justobe Sorry for the late response. Is this still an issue for you? Can you please share the *.h5 file and a standalone code to reproduce the issue? Thanks!

**Comment by Justobe** [comment]
@jvishnuvardhan Thanks for your reply! I re-run the scripts on tensorflow 1.15.3, and I found that the difference between tensorflow 1.15.3 and theano and cntk is still very large. I provided a new model and a new input to reproduce: [onedrive](https://1drv.ms/u/s!Aj6dGBsJFcs0jnjZ2WpjS42a-4cF?e=DWxP2y)

This is the picture in the cifar10 test set (No.119, starting from 0)
![cifar10-119](https://user-images.githubusercontent.com/15032308/83827120-190fc280-a710-11ea-8a95-3995a5d2574b.png)

It can be seen that the picture is a horse, and its label index is 7.

If I use the model and this picture in tensorflow, the output is 5. But the output of theano and cntk are both 7 (same as groundtruth)

You can use the following script to get the output of the three backends:
```
pip install keras==2.2.4

pip install tensorflow-gpu==1.14.0

pip install cntk-gpu==2.7

pip install theano==1.0.4

pip install pillow
```
> python get_prediction.py backend_name

Change backend_name to tensorflow, theano and cntk

Please let me know if you have any problems when you run the scripts. ^_^
Thanks in advance!

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.

**Comment by Justobe** [comment]
Hi~ @jvishnuvardhan @tensorflowbutler The problem seems to still exist on TensorFlow 2.2. The results of TensorFlow （tf1.x and tf2.x）are different from cntk and theano, but the results of cntk and theano are the same. I confirmed again that the script I provided in [ondedrive ](https://1drv.ms/u/s!Aj6dGBsJFcs0jnjZ2WpjS42a-4cF?e=DWxP2y)can help to reproduce this result.

Please let me know if you have any problems with the scripts. 
Thanks in advance!

**Comment by sushreebarsa** [comment]
@Justobe  Could you please try on latest stable version of tf 2.5 or 2.4.1 and let us know if this is still an issue.Thanks!
