### ISSUE TITLE
Feature suggestion: Ability to add copyright notice to saved model

### ISSUE THREAD

**Issue by juliangall** [tensorflow/tensorflow#37041]
A trained TensorFlow model can represent valuable intellectual property, and may sometimes be distributed as a saved model, rather than python code etc. Is there any way of including a copyright notice in a saved model file?

If this is not yet possible, perhaps a comments= argument could be added to model.save().

**Comment by tilakrayal** [comment]
@juliangall,
When creating a saved model in the github project , github will let you select the type of license from a drop-down listbox which is available. Then it will display that license type on your project's page, for all to see.

And if you are not sure what license to choose, it points you to https://choosealicense.com/ which explains everything and helps you make your choice.
https://github.com/cs3org/.github/blob/master/COPYRIGHT.md

Thank you!
