### ISSUE TITLE
Can't convert the model into ".tflite". I've tried every possible way from APIs to command lines. I tried to change layers as per tflite, but I couldn't understand the working and ended up with errors.

### ISSUE THREAD

**Issue by Kiranendra** [tensorflow/tensorflow#37052]
**System information**
- Google Colab
- TensorFlow: 1.15 

**Code link with dataset**
https://github.com/Kiranendra/Project

By trying different types of conversion like from saved model, from Keras model, freeze graphs, I am facing errors like with "input shape"( is none),  embedding layer. If I change the layer GRU to LSTM then input errors with the decoder output and it goes.

**Comment by ravikyram** [comment]
@Kiranendra 

Can you go through the [link](https://www.tensorflow.org/versions/r1.15/api_docs/python/tf/lite/TFLiteConverter) and see if it helps you in converting the model into TF lite .Thanks!

**Comment by Kiranendra** [comment]
Yes, I've already tried those methods. The model successfully saves. But, it doesn't convert to ".pb" or ".pbtxt" (no matter which way I try - python API or command line). I can't convert my model either with saving or without saving (not even into ".pb" or ".pbtxt"). 

Thank you.

**Comment by ravikyram** [comment]
@Kiranendra 

Can you please let us know what are the steps you followed for converting the model into TFLite.
Thanks!

**Comment by Kiranendra** [comment]
@ravikyram 

I followed the steps that were said to be followed, in the link:
https://www.tensorflow.org/versions/r1.15/api_docs/python/tf/lite/TFLiteConverter

As I am using "RNN" layers I also tried these steps, in the link:
https://www.tensorflow.org/lite/convert/rnn
I tried changing the layer (GRU) to the layers that were recommended by "TensorFlow" in the link above. Honestly, I am new to neural networks (You can call me as a beginner). So, I can't understand how to change the layers without actually disturbing the model. After, trying everything I figured out that the model saves in ".h5" format, but fails to convert to ".pb". 

Thank you.

**Comment by ymodak** [comment]
@Kiranendra Can you please try with tf-nightly and use experimental flag for converter?
See https://www.tensorflow.org/api_docs/python/tf/lite/TFLiteConverter

**Comment by Kiranendra** [comment]
@ymodak 
Yes. I've tried them.
1. If I use ".from_keras_model()" then, I am getting the error (when using **.convert()** ):
_"NotImplementedError: numpy() is only available when eager execution is enabled."_

If I enabled the eager execution then I will get the error at line no. 273 (in model.compile method) in the notebook, stating that _" with eager execution enabled target_tensors is not...."_ 
I had to disable v2 behavior also because I have used _"tf.placeholder"_

2. I can't use _".from_saved_model()"_: It says 
"_the SavedModel file does not exist at: /content/mymodel.pb/{saved_model.pbtxt|saved_model.pb}_"
I don't understand why it shows that even though I have the file.

If you don't mind can you please try to convert the model into _".tflite"_ on your side with my code and dataset [here](https://github.com/Kiranendra/Project) so that you can understand where the problem lies as I am a very much new to RNNs (and also machine learning). It won't take much time to train(the data set is small). Please !!!
Thank you.

**Comment by jvishnuvardhan** [comment]
@Kiranendra Can you please create a standalone code to reproduce the issue. I tried to create model but it throws an error in this line `data_dest.append(start_stop_tags(preprocess_text(line[1])))`. The error is as follows. Basically `line` was empty but we are trying to access line[1]. Thanks!

```
IndexError                                Traceback (most recent call last)
<ipython-input-10-3d0de97b644f> in <module>()
      6   line = lines.split('\t')[:2]
      7   data_src.append(preprocess_text(line[0]))
----> 8   data_dest.append(start_stop_tags(preprocess_text(line[1])))

IndexError: list index out of range
```

**Comment by Kiranendra** [comment]
I am using Google Colab. I've split the code and tested it. But, not really getting the error. Here is the output **snap** for one iteration.
-------------------
![image](https://user-images.githubusercontent.com/47424842/76050660-407ab600-5f8e-11ea-865e-f180aec51f4e.png)

**Comment by jvishnuvardhan** [comment]
@Kiranendra Can you please try running your entire colab. When I tried and print `data` after reading from the Gdrive, it prints as follows.

```
IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)
```

Looks like it is not reading for the above reason. I will try again with tensorflow on my local. Thanks!

**Comment by Kiranendra** [comment]
I've gone through everything again and didn't find any error. So, I made a new notebook and split the code into parts. Here is the ZIP file with the notebook and dataset.

[tflite_file_conversion.zip](https://github.com/tensorflow/tensorflow/files/4301726/tflite_file_conversion.zip)

I forgot to change the file paths(for dataset and checkpoint). As you said that you will try local, please change the file paths accordingly.

P.S: If you are saving the checkpoints in a folder then, make sure that the folder already exists. The model can't create a folder by itself to save the checkpoint files.
