### ISSUE TITLE
MultiWorkerMirroredStrategy OOM - Ubuntu 18.04 

### ISSUE THREAD

**Issue by maximsmol** [tensorflow/tensorflow#37057]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information** 
- Have I written custom code (as opposed to using a stock
example script provided in TensorFlow): **yes**
- OS Platform and Distribution (e.g.,
Linux Ubuntu 16.04): **Linux Ubuntu 18.04**
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if
the issue happens on mobile device: 
- TensorFlow installed from (source or
binary): **pip install tensorflow==2.1.0** - TensorFlow version (use command below): 
- Python version: **python=3.6.9** - Bazel
version (if compiling from source):
- GCC/Compiler version (if compiling from
source): 
- CUDA/cuDNN version: **10.2** - GPU model and memory: **NVIDIA T4 16GB (g4dn.xlarge) (REPRODUCABLE ON CPU)**

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
When training a trivial model with `MultiWorkerMirroredStrategy` over `cifar10` the memory consumption of all workers grows over time until eventually the system runs out of memory.

Memory consumption grows while `model.fit` is running.

I ran into this issue on the AWS Deep Learning AMI, but was also able to reproduce it with a manually configured AWS Ubuntu 18.04 AMI. Could not reproduce on a Mac laptop.

Note: A more complicated model will run out of memory a lot faster, the toy example I provide for reproduction was deliberately downscaled for simplicity, but takes a few minutes to double RAM consumption.

Cluster setup:
- 4 CPU workers (`CUDA_AVAILABLE_DEVICES=''`) on a **single** g4dn.xlarge instance (was able to reproduce with multiple instances, and with GPU training)
- Using `ray` to run the processes for convenience, not using any of its distributed features

**Describe the expected behavior**
Memory consumption is stable/the system does not run out of memory.

**Standalone code to reproduce the issue** 
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

https://gist.github.com/maximsmol/ac2aeb5582600cd8b3fc6952cfd040a1
^ the issue requires a multi-worker setup (ips+ports) so it's not possible to provide a notebook

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

The way I track the memory consumption is openning `top` and watch the RES RAM column for the workers. It very visibly grows.

**Comment by anj-s** [comment]
@maximsmol Does this OOM memory only happen for multiple workers? Do you see this behavior on a single machine as well?

**Comment by maximsmol** [comment]
I was able to reproduce this at the time with a single amazon instance running multiple python processes in a "distributed" cluster (everything on localhost). I am not exactly sure if a single python process (in a "cluster" made up of this single worker) would also OOM since it takes a while for memory consumption to grow significantly in such a configuration.

**Comment by sharmaannapurna** [comment]
This behavior happens for single machine as well. I ran my code which initially(for first two epochs) takes about 3 GB memory and afterwards takes up more and shows up OOM after epoch 15. I ran the code with both tf2.0 and tf2.1 on ubuntu18.04. The same code works well in windows10.

**Comment by ymodak** [comment]
Is this still an issue with latest version of TF 2.5?
