### ISSUE TITLE
tflite | interpreter->AllocateTensors() fails

### ISSUE THREAD

**Issue by Lotte1990** [tensorflow/tensorflow#37050]
**System information** 
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- TensorFlow installed from (source or binary): docker image (nightly)
- TensorFlow version (use command below): TensorFlow 2.2.0-dev20200218

**Describe the current behavior**
In Python (tf.lite.Interpreter), everything works as expected. In C++, however, interpreter->AllocateTensors() fails when using the attached model (see link to minimal example below). Absolutely no clue is given. No error. I have no idea why this happens. I'm not using any custom ops.

**Describe the expected behavior**
The C++ code should give the same result as the python code (tf.lite.Interpreter).

**Standalone code to reproduce the issue** 
[Can be found here](https://drive.google.com/open?id=1kKUP-bIizhWNtA8xt8X3DV1M7h8AJGD_)

**Comment by Lotte1990** [comment]
Update: I also exported the .tflite file with `converter.experimental_new_converter = True` but `interpreter->AllocateTensors()` still fails. Problem persists with the new converter. Link to minimal example with both .tflite exports: https://drive.google.com/open?id=13xqynDb8cEJCv45x73m0nUUmY_Vc06lP

**Comment by srjoglekar246** [comment]
`AllocateTensors` is succeeding fine, as far as I can tell.

`kTfLiteOk`, the returned value from `interpreter->AllocateTensors();` has the enum value of 0, because of which `!allocationStatus` returns True.
