### ISSUE TITLE
Distributed seq2seq model stuck at the session.run()

### ISSUE THREAD

**Issue by DjangoPeng** [tensorflow/tensorflow#3705]
I'm applying the distributed seq2seq model:
   1 ps
   2 workers
but stuck at the 
> sess.run(output_feed, input_feed) 
in the seq2seq_model.py, even though my params are very small(1 layers of 10 units)

my problem like the question on the below in stackoverflow:
(http://stackoverflow.com/questions/38319953/tensorflow-applying-syncreplicasoptimizer-to-seq2seq-model-with-buckets).

Tensorflow version: 0.9-GPU_Support

This is the log output:
> start running session
I tensorflow/core/common_runtime/gpu/pool_allocator.cc:244] PoolAllocator: After 7293 get requests, put_count=3583 evicted_count=1000 eviction_rate=0.279096 and unsatisfied allocation rate=0.659537
I tensorflow/core/common_runtime/gpu/pool_allocator.cc:256] Raising pool_size_limit_ from 100 to 110

And it seems like it's still running , the events file is updated as well:
> total 85560
drwxr-xr-x 2 dl dl     4096 Aug  9 16:04 .
drwxrwxr-x 9 dl dl     4096 Aug  9 15:59 ..
-rw-rw-r-- 1 dl dl      129 Aug  9 16:03 checkpoint
-rw-rw-r-- 1 dl dl 23232412 Aug  9 **16:09 events.out.tfevents.1470772996.dl129**
-rw-rw-r-- 1 dl dl 40464613 Aug  9 16:02 graph.pbtxt
-rw-rw-r-- 1 dl dl   645001 Aug  9 16:03 model.ckpt-0
-rw-rw-r-- 1 dl dl 23249486 Aug  9 16:04 model.ckpt-0.meta
dl@dl129:~/PJT/train_logs$ ll
total 85560
drwxr-xr-x 2 dl dl     4096 Aug  9 16:13 .
drwxrwxr-x 9 dl dl     4096 Aug  9 15:59 ..
-rw-rw-r-- 1 dl dl      129 Aug  9 16:13 checkpoint
-rw-rw-r-- 1 dl dl 23232512 Aug  9 **16:13 events.out.tfevents.1470772996.dl129**
-rw-rw-r-- 1 dl dl 40464613 Aug  9 16:02 graph.pbtxt
-rw-rw-r-- 1 dl dl   645001 Aug  9 16:13 model.ckpt-0
-rw-rw-r-- 1 dl dl 23249486 Aug  9 16:14 model.ckpt-0.meta
dl@dl129:~/PJT/train_logs$

**Comment by girving** [comment]
If the events file is being updated, it's unlikely that the code is hanging inside `session.run`.  Why do you think it is hanging there?

**Comment by DjangoPeng** [comment]
@girving Thx for your comment.
I find the Supervisor class, and it's __init__ is as below:
>  def __init__(self, graph=None, ready_op=USE_DEFAULT, is_chief=True,
               init_op=USE_DEFAULT, init_feed_dict=None,
               local_init_op=USE_DEFAULT, logdir=None,
               summary_op=USE_DEFAULT, saver=USE_DEFAULT,
               global_step=USE_DEFAULT, save_summaries_secs=120,
               save_model_secs=600, recovery_wait_secs=30, stop_grace_secs=120,
               checkpoint_basename="model.ckpt", session_manager=None,
               summary_writer=USE_DEFAULT, init_fn=None):

The parameter *save_model_secs* and *save_summaries_secs* are the time interval to save checkpoint file and event file separately. 
So I guess at least the sv is still running, but I'm not sure whether something wrong or waiting for data in the `session.run`

> 

>

**Comment by girving** [comment]
@DjangoPeng I don't understand how your comment is related to my question.  What is your evidence that it's hanging inside `sess.run()`?  It's possible I'm missing something obvious, but as is we don't have enough information to help.

**Comment by DjangoPeng** [comment]
@girving Ok，let me clear.
I add two `prints` between the `session.run`:
>   def step(self, session, encoder_inputs, decoder_inputs, target_weights,
           bucket_id, forward_only):

    # Check if the sizes match.
    encoder_size, decoder_size = self.buckets[bucket_id]
    if len(encoder_inputs) != encoder_size:
      raise ValueError("Encoder length must be equal to the one in bucket,"
                       " %d != %d." % (len(encoder_inputs), encoder_size))
    if len(decoder_inputs) != decoder_size:
      raise ValueError("Decoder length must be equal to the one in bucket,"
                       " %d != %d." % (len(decoder_inputs), decoder_size))
    if len(target_weights) != decoder_size:
      raise ValueError("Weights length must be equal to the one in bucket,"
                       " %d != %d." % (len(target_weights), decoder_size))

    # Input feed: encoder inputs, decoder inputs, target_weights, as provided.
    input_feed = {}
    for l in xrange(encoder_size):
      input_feed[self.encoder_inputs[l].name] = encoder_inputs[l]
    for l in xrange(decoder_size):
      input_feed[self.decoder_inputs[l].name] = decoder_inputs[l]
      input_feed[self.target_weights[l].name] = target_weights[l]

    # Since our targets are decoder inputs shifted by one, we need one more.
    last_target = self.decoder_inputs[decoder_size].name
    input_feed[last_target] = np.zeros([self.batch_size], dtype=np.int32)

    # Output feed: depends on whether we do a backward step or not.
    if not forward_only:
      output_feed = [self.updates[bucket_id],  # Update Op that does SGD.
                     self.gradient_norms[bucket_id],  # Gradient norm.
                     self.losses[bucket_id]]  # Loss for this batch.
    else:
      output_feed = [self.losses[bucket_id]]  # Loss for this batch.
      for l in xrange(decoder_size):  # Output logits.
        output_feed.append(self.outputs[bucket_id][l])

    print("------------------------------------------------------------------------------")
    print("------------------------------------------------------------------------------")

    print("start running session")
    outputs = session.run(output_feed, input_feed)
    print("finish running session")
    if not forward_only:
      return outputs[1], outputs[2], None  # Gradient norm, loss, no outputs.
    else:
      return None, outputs[0], outputs[1:]  # No gradient norm, loss, outputs.

And this is the standard ouput:
>   reading data line 100000
  reading data line 200000
finish reading data
ready to train
start training loop:0
start_time:1470835889.1598
------------------------------------------------------------------------------
------------------------------------------------------------------------------
start running session
I tensorflow/core/common_runtime/gpu/pool_allocator.cc:244] PoolAllocator: After 7061 get requests, put_count=3604 evicted_count=1000 eviction_rate=0.277469 and unsatisfied allocation rate=0.645376
I tensorflow/core/common_runtime/gpu/pool_allocator.cc:256] Raising pool_size_limit_ from 100 to 110

As you can see, the *finish running session* is not printed at the std.out, cause it's hanging inside the `sess.run()`.

**Comment by DjangoPeng** [comment]
```

   # Output feed: depends on whether we do a backward step or not.
if not forward_only:
  output_feed = [self.updates[bucket_id],  # Update Op that does SGD.
                 self.gradient_norms[bucket_id],  # Gradient norm.
                 self.losses[bucket_id]]  # Loss for this batch.
else:
  output_feed = [self.losses[bucket_id]]  # Loss for this batch.
  for l in xrange(decoder_size):  # Output logits.
    output_feed.append(self.outputs[bucket_id][l])

print("------------------------------------------------------------------------------")
print("------------------------------------------------------------------------------")

print("start running session")
outputs = session.run(output_feed, input_feed)
print("finish running session")
if not forward_only:
  return outputs[1], outputs[2], None  # Gradient norm, loss, no outputs.
else:
  return None, outputs[0], outputs[1:]  # No gradient norm, loss, outputs.
```

**Comment by DjangoPeng** [comment]
Now I add the `init_tokens_op` and `chief_queue_runner`.  It cause a AttributeError!
```
Traceback (most recent call last):
  File "rnn/translate/translate.py", line 378, in <module>
    tf.app.run()
  File "/home/dl/anaconda2/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 30, in run
    sys.exit(main(sys.argv))
  File "rnn/translate/translate.py", line 375, in main
    train()
  File "rnn/translate/translate.py", line 197, in train
    sv.start_queue_runners(sess, [model.chief_queue_runner])
  File "/home/dl/anaconda2/lib/python2.7/site-packages/tensorflow/python/training/supervisor.py", line 717, in start_queue_runners
    threads.extend(qr.create_threads(sess, coord=self._coord, daemon=True,
AttributeError: 'function' object has no attribute 'create_threads'
``` 
seq2seq_model.py:
```
    #part of __init__()
    params = tf.trainable_variables()
    if not forward_only:
      self.gradient_norms = []
      self.updates = []
      opt = tf.train.GradientDescentOptimizer(self.learning_rate)

      opt = tf.train.SyncReplicasOptimizer(
        opt,
        replicas_to_aggregate=num_workers,
        replica_id=task_id,
        total_num_replicas=num_workers)
        #variable_averages=self.exp_moving_averager,
        #variable_to_average=self.variable_to_average)
      

      for b in xrange(len(buckets)):
        gradients = tf.gradients(self.losses[b], params)
        clipped_gradients, norm = tf.clip_by_global_norm(gradients,
                                                         max_gradient_norm)
        self.gradient_norms.append(norm)
        self.updates.append(opt.apply_gradients(
	          zip(clipped_gradients, params), global_step=self.global_step))

      
    self.saver = tf.train.Saver(tf.all_variables())
    print("finish creating model")
    
  
    self.init_tokens_op = opt.get_init_tokens_op
    self.chief_queue_runner = opt.get_chief_queue_runner

```
translate.py:
```
def train():

  # set distributed configs
  ps_hosts = ["9.91.9.129:2222"]
  #worker_hosts = ["9.91.9.129:2223", "9.91.9.130:2223"]
  worker_hosts = ["9.91.9.130:2223"]

  cluster = tf.train.ClusterSpec({"ps":ps_hosts, "worker":worker_hosts})
  server = tf.train.Server(cluster,
                            job_name=FLAGS.job_name,
                            task_index=FLAGS.task_index)
  if FLAGS.job_name == "ps":
      server.join()
  elif FLAGS.job_name == "worker":
      # Worker server 
      is_chief = (FLAGS.task_index == 0)      
      #with tf.Graph().as_default():
      """core/common_runtime/simple_placer.cc:818 lines """
      with tf.device(tf.train.replica_device_setter(cluster=cluster,
        worker_device="/job:worker/task:%d" % FLAGS.task_index)):
      #with tf.device('/gpu:%d' % FLAGS.task_index):  

          
          # Create a variable scope "MT"
          #with tf.variable_scope("mt"):

          """Train a en->fr translation model using WMT data."""
          # Prepare WMT data.
          print("Preparing WMT data in %s" % FLAGS.data_dir)
          en_train, fr_train, en_dev, fr_dev, _, _ = data_utils.prepare_wmt_data(
              FLAGS.data_dir, FLAGS.en_vocab_size, FLAGS.fr_vocab_size)

          # Create model.
          print("Creating %d layers of %d units." % (FLAGS.num_layers, FLAGS.size))


          logdir = FLAGS.train_dir

          model = seq2seq_model.Seq2SeqModel(
                FLAGS.en_vocab_size, FLAGS.fr_vocab_size, _buckets,
                FLAGS.size, FLAGS.num_layers, FLAGS.max_gradient_norm, FLAGS.batch_size,
                FLAGS.learning_rate, FLAGS.learning_rate_decay_factor,
                forward_only=False, is_chief=is_chief, 
                num_workers=FLAGS.num_workers, task_id=FLAGS.task_index)



          init_op = tf.initialize_all_variables()
          summary_op = tf.merge_all_summaries()
          

          sv = tf.train.Supervisor(is_chief=is_chief,
                                  logdir=logdir,
                                  init_op=init_op,
                                  summary_op = None,
                                  saver=model.saver,
                                  save_model_secs=FLAGS.save_interval_secs,
                                  global_step=model.global_step)          



          sess_config = tf.ConfigProto(
              allow_soft_placement=True,
              log_device_placement=True)
              

          #sess = sv.prepare_or_wait_for_session(server.target)
          #with sv.prepare_or_wait_for_session(server.target, sess_config) as sess:
          with sv.managed_session(server.target, config=sess_config) as sess:
              
              if FLAGS.sync_replicas and is_chief:
                sv.start_queue_runners(sess, [model.chief_queue_runner])
                sess.run(model.init_tokens_op)
              
              
              if is_chief:
                ckpt = tf.train.get_checkpoint_state(logdir)
                if ckpt is not None:
                  print("ckpt.model_checkpoint_path=%s" % ckpt.model_checkpoint_path)
                if ckpt and tf.gfile.Exists(ckpt.model_checkpoint_path):
                  print("Reading model parameters from %s" % ckpt.model_checkpoint_path)
                  sess.run(init_op)
                  model.saver.restore(sess, ckpt.model_checkpoint_path)
                else:
                  print("Created model with fresh parameters.")
                  tf.gfile.MakeDirs(logdir)
                  sess.run(init_op)
                  
              
              # Read data into buckets and compute their sizes.
              print ("Reading development and training data (limit: %d)."
                     % FLAGS.max_train_data_size)
              dev_set = read_data(en_dev, fr_dev)
              train_set = read_data(en_train, fr_train, FLAGS.max_train_data_size)
              train_bucket_sizes = [len(train_set[b]) for b in xrange(len(_buckets))]
              train_total_size = float(sum(train_bucket_sizes))

              # A bucket scale is a list of increasing numbers from 0 to 1 that we'll use
              # to select a bucket. Length of [scale[i], scale[i+1]] is proportional to
              # the size if i-th training bucket, as used later.
              train_buckets_scale = [sum(train_bucket_sizes[:i + 1]) / train_total_size
                                     for i in xrange(len(train_bucket_sizes))]

              # This is the training loop.
              step_time, loss = 0.0, 0.0
              current_step = 0
              previous_losses = []
              next_summary_time = time.time() + FLAGS.save_summaryies_secs
              #with sess.as_default():
              print("ready to train")
              while not sv.should_stop() and current_step < FLAGS.max_step:
                print("start training loop:%d" % current_step)

                # Choose a bucket according to data distribution. We pick a random number
                # in [0, 1] and use the corresponding interval in train_buckets_scale.
                random_number_01 = np.random.random_sample()
                bucket_id = min([i for i in xrange(len(train_buckets_scale))
                                 if train_buckets_scale[i] > random_number_01])
                # Get a batch and make a step.
                start_time = time.time()
                print("start_time:%.4f" % start_time)

                encoder_inputs, decoder_inputs, target_weights = model.get_batch(
                    train_set, bucket_id)

                _, step_loss, _ = model.step(sess, encoder_inputs, decoder_inputs,
                                             target_weights, bucket_id, False)
                step_time += (time.time() - start_time) / FLAGS.steps_per_checkpoint
                loss += step_loss / FLAGS.steps_per_checkpoint
                current_step += 1
                
                print("current_step=%d" % current_step)
                

                # Once in a while, we save checkpoint, print statistics, and run evals.
                if current_step % FLAGS.steps_per_checkpoint == 0:
                  # Print statistics for the previous epoch.
                  perplexity = math.exp(loss) if loss < 300 else float('inf') 
                  print ("current step %d loss %.4f learning rate %.4f step-time %.2f "
                    "perplexity %.2f" % (current_step, loss, 
                                        model.learning_rate.eval(),
                                        step_time, perplexity))
                  # Decrease learning rate if no improvement was seen over last 3 times.
                  if len(previous_losses) > 2 and loss > max(previous_losses[-3:]):
                    print("learning_rate_decay_factor=%d" % FLAGS.learning_rate_decay_factor)
                    sess.run(model.learning_rate_decay_op)
                    #_, step = sess.run([model.train_op, model.global_step])

                  previous_losses.append(loss)
                  
                  if is_chief and next_summary_time < time.time():
                    # Save checkpoint and zero timer and loss.
                    checkpoint_path = os.path.join(FLAGS.train_dir, "translate.ckpt")
                    model.saver.save(sess, checkpoint_path, global_step=model.global_step)
                    next_summary_time += time.time()
                    # Run evals on development set and print their perplexity.
                  
                  """
                  if is_chief:
                    checkpoint_path = os.path.join(FLAGS.train_dir, "translate.ckpt")
                    model.saver.save(sess, checkpoint_path, global_step=model.global_step)
                  """
                  step_time, loss = 0.0, 0.0
                  for bucket_id in xrange(len(_buckets)):
                    if len(dev_set[bucket_id]) == 0:
                      print("  eval: empty bucket %d" % (bucket_id))
                      continue
                    encoder_inputs, decoder_inputs, target_weights = model.get_batch(
                        dev_set, bucket_id)
                    _, eval_loss, _ = model.step(sess, encoder_inputs, decoder_inputs,
                                                 target_weights, bucket_id, True)
                    eval_ppx = math.exp(eval_loss) if eval_loss < 300 else float('inf')
                    print("  eval: bucket %d perplexity %.2f" % (bucket_id, eval_ppx))
  
                    print("sys.stdout.flush()")
                    sys.stdout.flush()
                #print(not sv.should_stop())

          sv.stop()
          print("sv finished")
```

**Comment by girving** [comment]
I believe `sv.chief_queue_runner` is supposed to be set to a `QueueRunner`, not a function that returns a `QueueRunner`.  Try adding empty parentheses so that the function gets called.

**Comment by DjangoPeng** [comment]
@girving thx for you reply. Actually, I'm learning how to use the distributed by reading the `inception' code.
I don't know if it's necessary to use the `sv.chief_queue_runner`, because I find comments in the `supervisor.py' [here](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/training/supervisor.py#L693). While, the [distributed inception](https://github.com/tensorflow/models/blob/master/inception/inception/inception_distributed_train.py#L269) and [mnist_replica](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/dist_test/python/mnist_replica.py#L227) both use the `chief_queue_runner· and `init_tokens_op`.

**Comment by girving** [comment]
It looks like this is a question about how to use TensorFlow, not a Github issue, so I'm going to close this for now.  Questions about how to use TensorFlow are better asked on StackOverflow.  I'm happy to reopen if it turns out this is actually a bug.

**Comment by leido** [comment]
@DjangoPeng Did you find where your problem is? I have met similar problem and stuck for several days. Thanks very much.
