### ISSUE TITLE
Error: the tensor's graph is different from the session's graph

### ISSUE THREAD

**Issue by umerebryx** [tensorflow/tensorflow#3706]
I am using my previously trained models to generate deep dream images as decscribe in one of the [tutorials](https://render.githubusercontent.com/view/ipynb?commit=0685152a02f1fd4dbd711a023c1ccea5a8b8262b&enc_url=68747470733a2f2f7261772e67697468756275736572636f6e74656e742e636f6d2f74656e736f72666c6f772f74656e736f72666c6f772f303638353135326130326631666434646264373131613032336331636365613561386238323632622f74656e736f72666c6f772f6578616d706c65732f7475746f7269616c732f64656570647265616d2f64656570647265616d2e6970796e62&nwo=tensorflow%2Ftensorflow&path=tensorflow%2Fexamples%2Ftutorials%2Fdeepdream%2Fdeepdream.ipynb&repository_id=45717250#deepdream). But when I try to call the render_deepdream method I am getting below error:

> I tensorflow/core/common_runtime/gpu/gpu_init.cc:126] DMA: 0 
I tensorflow/core/common_runtime/gpu/gpu_init.cc:136] 0:   Y 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:806] Creating TensorFlow device (/gpu:0) -> (device: 0, name: Tesla K80, pci bus id: 0000:83:00.0)
Succesfully loaded model from /data/model_cache/model.ckpt-39 at step=39.
===============
(3648, 5472)
Traceback (most recent call last):
  File "imagenet_eval.py", line 46, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 30, in run
    sys.exit(main(sys.argv))
  File "imagenet_eval.py", line 42, in main
    inception_eval.evaluate(dataset)
  File "/home/ubuntu/experiment/models/inception/inception/inception_eval.py", line 192, in evaluate
    _eval_once(saver, summary_writer, top_1_op, top_5_op, summary_op)
  File "/home/ubuntu/experiment/models/inception/inception/inception_eval.py", line 156, in _eval_once
    render_deepdream(tf.square(T('inception_v3/mixed_8x8x2048b/concat',graph)), img0=img0, session=sess)
  File "/home/ubuntu/experiment/models/inception/inception/inception_eval.py", line 94, in render_deepdream
    lo = resize(img, np.int32(np.float32(hw)/octave_scale), session=session)
  File "/home/ubuntu/experiment/models/inception/inception/inception_eval.py", line 66, in wrapper
    return out.eval(dict(zip(placeholders, args)), session=kw.get('session'))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 555, in eval
    return _eval_using_default_session(self, feed_dict, self.graph, session)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 3495, in _eval_using_default_session
    raise ValueError("Cannot use the given session to evaluate tensor: "
ValueError: Cannot use the given session to evaluate tensor: the tensor's graph is different from the session's graph.

------------------------------------------------------------------

Below is the code that is causing the issue:

    def tffunc(*argtypes):
        '''Helper that transforms TF-graph generating function into a regular one.
        See "resize" function below.
        '''
        placeholders = list(map(tf.placeholder, argtypes))
        def wrap(f):
            out = f(*placeholders)
            def wrapper(*args, **kw):
                #from IPython import embed
                #embed()
                return out.eval(dict(zip(placeholders, args)), session=kw.get('session'))
            return wrapper
        return wrap

    def resize(img, size):
        img = tf.expand_dims(img, 0)
        return tf.image.resize_bilinear(img, size)[0,:,:,:]
    resize = tffunc(np.float32, np.int32)(resize)

This is the line causing issue: https://github.com/umerebryx/Inference/blob/master/inference_eval.py#L60
You can also view full code in above mentioned repo. Any help would be much appreciated as I am stuck at this for days now. Thanks in advance.

**Comment by girving** [comment]
Please use markdown to format code so it is easier to read (I edited your comment to do that just now).

**Comment by girving** [comment]
This is unlikely to be a bug in TensorFlow.  I would suggest printing out `session.graph`.  Presumably it will be different from `out.graph`.  This is probably fixable by passing `graph=something` when making the session, but further details should be asked about on StackOverflow, not here.
