### ISSUE TITLE
Slice of a tensor is created on CPU not GPU when dtype=tf.int16

### ISSUE THREAD

**Issue by NicMaq** [tensorflow/tensorflow#37065]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Google Colab
- **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device**: NA
- **TensorFlow installed from (source or binary)**: NA
- **TensorFlow version (use command below)**: version 2.x
- **Python version**: 3
- **Bazel version (if compiling from source)**: NA
- **GCC/Compiler version (if compiling from source)**: NA
- **CUDA/cuDNN version**: NA
- **GPU model and memory**: Google Colab GPU
- **Exact command to reproduce**: 
https://colab.research.google.com/drive/1gbVxZgaesqxOLuoF-D9yuwOahCNTDcEi

### Describe the problem
When slicing a tensor of dtype tf.int16 on GPU, the operation is created on CPU, not GPU. If the tensor is tf.int32, the operation is created on GPU.

### Source code / logs
https://colab.research.google.com/drive/1gbVxZgaesqxOLuoF-D9yuwOahCNTDcEi

**Comment by gowthamkpr** [comment]
@NicMaq Slicing operation on gpu does not supported int16  and this is the reason why the operation is not created on GPU.

**Comment by NicMaq** [comment]
Thank you for your reply. 

Maybe, I would suggest modifying the documentation of tf.slice as it indicates: input: A tensor. 

Thank you.
