### ISSUE TITLE
Documentation issue about tf.math.xlog1py (nightly-only APIs)

### ISSUE THREAD

**Issue by wookayin** [tensorflow/tensorflow#37078]
## URL(s) with the issue:

https://www.tensorflow.org/api_docs/python/tf/math/xlog1py

## Description of issue (what needs changing):

This documentation describes `tf.math.xlog1py`, shown as a part of "stable" version of TF 2.1 but I believe this API has not been released yet. `tf.math.xlog1py` is only available on nightly at this point, added in https://github.com/tensorflow/tensorflow/commit/19986377f2a3c560418f42f2323733564a7303eb (Jan 2020).

FYI: I ran into this issue as I was using `tfp-nightly` which depends on `tf-nightly` (module 'tensorflow_core._api.v2.math' has no attribute 'xlog1py').

The documentation should have not published under "TensorFlow Core v2.1.0". Why was it the case? If it was due to a mistake, could we improve on the process so we can have a "nightly" doc and a "stable" doc?

**Comment by jvishnuvardhan** [comment]
@wookayin Agree. This is not part of `TF2.1`. [Here](https://colab.sandbox.google.com/gist/jvishnuvardhan/6aa619234a38c34150e4b447d4037c66/untitled834.ipynb) is the gist for our reference. With `tf-nightly` it works as expected. But with the `TF2.1`, it throws the following error.

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-3-564ca226252b> in <module>()
----> 1 tf.math.xlog1py(0., 1.)

AttributeError: module 'tensorflow_core._api.v2.math' has no attribute 'xlog1py'
```

**Comment by MarkDaoust** [comment]
Hi, This is an artifact of how the nightly diff are generated.

Like here:

https://www.tensorflow.org/api_docs/python/tf/math/?version=nightly#for_example

This page has no left-nav, because it's only generated in nightly. 
We should make the whole thing green, or add a a sort of [NEW] banner so it's clear what the status is.

**Comment by wookayin** [comment]
Thanks -- I see. Yes, I agree that for the pages that should be only available in nightly more clear status needs to be displayed. (Please feel free to change the issue title to a more general one if you think appropriate)

What actually confused me is the header:

> TensorFlow > API > **TensorFlow Core v2.1.0** > Python

which sounds like it is a part of TF 2.1.0. FYI, I directly got to the page from google search results so wasn't aware of "See Stable" v.s. "See Nightly" modes (which is nice BTW).

So one of my suggestions is to have a different version name in this navigation banner (e.g., *TensorFlow Core Nightly*).

**Comment by yashk2810** [comment]
This should get fixed tomorrow. There will be a note at the top of the page saying that the API is only available in nightly.

**Comment by wookayin** [comment]
I see this is now fixed. Thank you for the support!

> Note: This API is new and only available intf-nightly.
![image](https://user-images.githubusercontent.com/1009873/75590304-e760ce80-5a31-11ea-8f33-b16930ffff81.png)

**Comment by yashk2810** [comment]
The space between `in` and `tf-nightly` should get fixed by tomorrow.
