### ISSUE TITLE
Documentation needs to upgrade to Python3

### ISSUE THREAD

**Issue by ayushmankumar7** [tensorflow/tensorflow#37075]
Thank you for submitting a TensorFlow documentation issue. Per our GitHub
policy, we only address code/doc bugs, performance issues, feature requests, and
build/installation issues on GitHub.

The TensorFlow docs are open source! To get involved, read the documentation
contributor guide: https://www.tensorflow.org/community/contribute/docs

## URL(s) with the issue: 
https://github.com/tensorflow/tensorflow/blob/master/README.md

## Description of issue (what needs changing):

SInce , PSF has officially stopped it's support for Python2, the documentation needs to be upgraded to Python3.
pip2 -> pip3 
### Correct links

Is the link to the source code correct?

### Parameters defined

Are all parameters defined and formatted correctly?

### Returns defined

Are return values defined?

### Raises listed and defined

Are the errors defined? For example,
https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/feature_column/categorical_column_with_vocabulary_file#raises

### Usage example

Is there a usage example?

See the API guide: https://www.tensorflow.org/community/contribute/docs_ref
on how to write testable usage examples.

### Request visuals, if applicable

Are there currently visuals? If not, will it clarify the content?

### Submit a pull request?
Yes, I'll
Are you planning to also submit a pull request to fix the issue? See the docs
contributor guide: https://www.tensorflow.org/community/contribute/docs,
docs API guide: https://www.tensorflow.org/community/contribute/docs_ref and the
docs style guide: https://www.tensorflow.org/community/contribute/docs_style

**Comment by Ir1d** [comment]
It seems this could be closes since #36817 is merged

**Comment by ayushmankumar7** [comment]
@Ir1d  I was told that many users use windows where pip3 is not required and python3 too. For them pip and python do the work so i closed my PR. If you suggest me to do the changes, i'll do it.

**Comment by Ir1d** [comment]
@aymericdamien oops, I thought the PR was merged. In my opinion there are many cases where python is default aliased to python3, so I think there's no need to explicitly speficy to use python3 instead of python..

**Comment by ayushmankumar7** [comment]
Yes. So you may consider closing this issue. Could you suggest me some issues to work on? I am a GSOC 2020 aspirant and looking forward to work with Tensorflow.

**Comment by Ir1d** [comment]
Sorry I can't help you. I'm also interested in GSOC 2020 and now wandering around in the issues.

**Comment by ymodak** [comment]
Closing this issue as per the threads discussion. Thanks!
