### ISSUE TITLE
Reintroduced Typo in tf.keras.layers.Attention docs example

### ISSUE THREAD

**Issue by ulf1** [tensorflow/tensorflow#37084]
## URL(s) with the issue:
https://www.tensorflow.org/api_docs/python/tf/keras/layers/Attention

## Description of issue (what needs changing):
Typo was reintroduced in v2.1
See https://github.com/tensorflow/tensorflow/issues/34809 

must be 

```
value_embeddings = token_embedding(value_input)
```

@rabitt

**Comment by ashutosh1919** [comment]
@ulf1 , It is exactly same as you are telling. See the nightly version of the doc [here](https://www.tensorflow.org/api_docs/python/tf/keras/layers/Attention?version=nightly)

**Comment by ulf1** [comment]
@ashutosh1919 Ok.
