### ISSUE TITLE
Tensorflow Lite Hexagon delegate support for QCOM SDM765G

### ISSUE THREAD

**Issue by huanyingjun** [tensorflow/tensorflow#37089]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information** 
- Have I written custom code (as opposed to using a stock
example script provided in TensorFlow): 
- OS Platform and Distribution (
Linux Ubuntu 16.04): 
- Mobile device (OPPO reno3 Pro) if
the issue happens on mobile device: 
- TensorFlow installed from (source or
binary): - TensorFlow version (use command below):  14417096dbebbaf46043972029f4bf721e5364cb
- Python version: - Bazel
version (if compiling from source):
- GCC/Compiler version (if compiling from
source): 
- CUDA/cuDNN version: - GPU model and memory:

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
Hello,
I am using tensorflow based on commit ID: 14417096dbebbaf46043972029f4bf721e5364cb
And I use tflite benchmark_model for testing (tensorflow/lite/tools/benchmark),
benchmark_model run failed when enable TFlite hexagon delegate on my phone.
hexagon delegate is not supportted on my phone.
Could you please help add this CPU in the supportted list?
below is my phone innfo:
```
#adb shell getprop ro.product.device
OP4A9D  

#adb shell getprop ro.board.platform
lito

CPU info :  Qualcomm Technologies, Inc SDM765G 5G
```

And from https://source.codeaurora.org/quic/hexagon_nn/nnlib, 
I see that the latest hexagon_nn version is 0x00021401, Could you please update libhexagon_nn_skel.so  to the latest version ?

thanks very much

**Comment by karimnosseir** [comment]
Hi,

Can you share more details about this SoC, which version it is using V65/66/something else ?
Do you know the soc id ? (you can run "adb shell cat /sys/devices/soc0/soc_id")

regarding the version, stay tuned on it's way :)
BTW, is there something you need that is specifically in the new version ?

Thanks

**Comment by huanyingjun** [comment]
hello,
I am not sure the hexagon version of this SoC,  it is Hexagon 696 DSP Processor, I think it is V66.
and the SoC id is 400
```
 $ cat /sys/devices/soc0/soc_id
400
```
you can find more info at https://www.qualcomm.com/media/documents/files/qualcomm-snapdragon-765-5g-mobile-platform-product-brief.pdf
 
  
 
about the libhexagon_nn_skel.so version question, I see that:
tensorflow/lite/experimental/delegates/hexagon/builders/concat_builder.cc: line 112
OP_Requantize_8to8 is added after concat,
```
   auto* requantize_op = graph_builder_->AddNode(GetTFLiteNodeID());
    requantize_op->SetOpType(OP_Requantize_8to8);
    requantize_op->AddInput(concat_out);
```
but I checked the latest version nnlib, https://source.codeaurora.org/quic/hexagon_nn/nnlib/tree/docs/ops.txt  line 778
```
QuantizedConcat_8:
    3n+1 inputs:
        0: Dimension (int32 scalar)
        1-n: Input data tensors (quint8 tensor)
        n+1-2n: Input min (float scalar)
        2n+1-3n: Input max (float scalar)
    3 outputs:
        0: Output data (quint8 tensor)
        1: Output min (float scalar)
        2: Output max (float scalar)
    The operation concatenate tensors. Currently we only support along the depth dimension. The 
        operation also requantizes values. 
    Dimension - Currently only depthwise concatenation (3) is supported.
```
**"The operation also requantizes values. "**
The OP_Requantize_8to8 is not needed after concat.
So, I guess maybe it is  libhexagon_nn_skel.so version issue.

**Comment by karimnosseir** [comment]
Thanks.
Will enable it - hopefully in the next couple of days will be available.

For the Requantize, no it is not related to the version. We still need the Requantize anyway.
Basically, we want to make sure that the data is quantized with the same scale as in the tflite output tensor of the concat op.
HTH

**Comment by karimnosseir** [comment]
New version is released which Should enable SDM765G and also includes version 1.14 
You will need to use the compatible libhexagon_nn_skel* (you can find them here
https://www.tensorflow.org/lite/performance/hexagon_delegate)

**Comment by huanyingjun** [comment]
@karimnosseir
I tried to download the libhexagon_nn_skel* from "https://storage.cloud.google.com/download.tensorflow.org/tflite/hexagon_nn_skel_v1.14.run",
but failed to download, shows
"Forbidden
Error 403"

Could you please help check this ?

**Comment by karimnosseir** [comment]
Can you try again 

Thanks

**Comment by huanyingjun** [comment]
It is ok.
Thank you very much
