### ISSUE TITLE
Misleading convert error when no concrete functions are given

### ISSUE THREAD

**Issue by PRDrum5** [tensorflow/tensorflow#37086]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 18.04):
- TensorFlow installed from source:
- TensorFlow version 2.1.0:

**Command used to run the converter or code if you’re using the Python API**
If possible, please share a link to Colab/Jupyter/any notebook.

```
converter = tf.lite.TFLiteConverter.from_saved_model(model_path)
tflite_model = converter.convert()
```

**The output from the converter invocation**

```
ValueError: This converter can only convert a single ConcreteFunction. Converting multiple functions is under development.
```

**Failure details**
When attempting to convert a model in which no ConcreteFunctions have been defined, the error message implies that there are multiple.

As someone new coming to TF and TFLite, I found this very confusing as to where my concrete functions were being defined. 

Inspecting the code from https://github.com/tensorflow/tensorflow/blob/v2.1.0/tensorflow/lite/python/lite.py in the ```convert``` method at line 417 the Value Error is thrown when anything but 1 concrete function is defined in the model (rightly so) but the error message implies that more than one have been defined.

```
if len(self._funcs) != 1:
      raise ValueError("This converter can only convert a single "
                       "ConcreteFunction. Converting multiple functions is "
                       "under development.")
```

**Comment by ravikyram** [comment]
@PRDrum5 

Can you please share the simple standalone code to reproduce the issue in our environment. It helps us in localizing the issue faster. Thanks!

**Comment by PRDrum5** [comment]
Sure

Here I've made a simple model but not defined the input_signature for the tf.function for the `__call__` of the model. In doing so there is **no**  concrete functions at all. But the error message which is returned implies that there are multiple and that this is the issue.

My suggestion is that the error thrown should be clear that in this scinario the user has not defined any concrete functions rather that suggesting that there exists more than one which is not the case.

```
import tensorflow as tf
from tensorflow.keras.layers import Dense


# Define very simple classification model
class Model(tf.Module):
    def __init__(self):
        super(Model, self).__init__()

        self.d1 = Dense(2, activation='relu')
        self.d2 = Dense(2, activation='softmax')
    
    @tf.function
    def __call__(self, x):
        print("Tracing the model")
        x = self.d1(x)
        return self.d2(x)

model = Model()

example_data = tf.constant([[1.0, 2.0]])
preds = model(example_data)
tf.print(preds)

# Save the model
tf.saved_model.save(model, './model_example')


# Load the saved model and convert to TFLite
converter = tf.lite.TFLiteConverter.from_saved_model('./model_example')
tflite_model = converter.convert()
open("converted_model.tflite", "wb").write(tflite_model)


```

**Comment by ravikyram** [comment]
I have tried on colab with TF version 2.1.0,2.2.0-dev20200227  and was able to reproduce the issue.Please, find the gist [here](https://colab.sandbox.google.com/gist/ravikyram/39a05cacd98c1c561c6c2b94f986db69/untitled683.ipynb). Thanks!

**Comment by jdduke** [comment]
@gargn for this case is it possible to provide the signature w/ the `from_saved_model` method? Or do they have to load the model and then explicitly call `from_concrete_functions`?
