### ISSUE TITLE
Can not access GPU when run python script with bazel

### ISSUE THREAD

**Issue by tobegit3hub** [tensorflow/tensorflow#3708]
When we're using TensorFlow serving to train our model, we have found that the program is not able to access all the GPUs in that machine. This can be 100% reproduced and we add the following code for testing.

```
from tensorflow.python.client import device_lib

def get_available_gpus():
    local_device_protos = device_lib.list_local_devices()
    return [x.name for x in local_device_protos if x.device_type == 'GPU']

print(get_available_gpus())
```

If we run the script with `python`, it prints all the GPUs normally. If we run with `bazel build` and `bazel run` for the same script, it prints the empty list.

### Environment info
Operating System: Ubuntu 14.04

Installed version of CUDA and cuDNN: 
CUDA 7.5 and cuDNN 4.0

If installed from binary pip package, provide:
TensorFlow 0.9.0

### Steps to reproduce
1. git clone https://github.com/tensorflow/tensorflow && cd tensorflow/
2. Add the code to print GPUs or placements of the operations in mnist_with_summaries.py
3. python tensorflow/examples/tutorials/mnist/mnist_with_summaries.py
And we can see all the GPUs in this server.
4. bazel build //tensorflow/examples/tutorials/mnist:mnist_with_summaries
5. bazel-bin/tensorflow/examples/tutorials/mnist/mnist_with_summaries
And it use CPU only and print nothing about GPUs.

**Comment by mrry** [comment]
I suspect the problem is that, when you run the result of `bazel build`, the resulting binary uses a newly-compiled version of TensorFlow that has whatever compilation options you specify in the build command. By default, `bazel` will build a CPU-only version, and you need to specify `--config=cuda` to get a GPU version.

Can you try the following commands instead?

```
$ bazel build --config=cuda //tensorflow/examples/tutorials/mnist:mnist_with_summaries
$ bazel-bin/tensorflow/examples/tutorials/mnist/mnist_with_summaries
```

**Comment by tobegit3hub** [comment]
Thanks @mrry . It works like exactly what you suspect and now the process is able to "see" the GPUs.

But I have another problem about the cuda compute capability version. I'm running this in AWS g2.8xlarge instance with NVIDIA K520 GPU which is cuda compute capability 3.0. I will try `TF_UNOFFICIAL_SETTING=1 ./configure` which may fix this.

![screen shot 2016-08-10 at 09 54 20](https://cloud.githubusercontent.com/assets/2715000/17539521/6cb405ac-5ee1-11e6-8c32-869cca5bf1d9.png)

**Comment by tobegit3hub** [comment]
After `TF_UNOFFICIAL_SETTING=1 ./configure` and setting the min compute capability as 3.0, it works like run `python` in my local environment. Not a bug of `bazel` or `TensorFlow`.

Thanks @mrry for detailed explaination and it would be better to add more documents about this.
