### ISSUE TITLE
Entity could not be transformed error

### ISSUE THREAD

**Issue by matthewp14** [tensorflow/tensorflow#37092]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information** 
- Have I written custom code - YES
- OS Platform and Distribution - Mac OS 10.15.2 Catalina
- TensorFlow installed from (source or
binary): - Conda
- Python version: - 3.6.7
Using CPU

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

Using Tensorflow 2.0.0

**Describe the current behavior**

I am trying to implement custom layers and I keep getting the following errors: 

WARNING:tensorflow:Entity <bound method BinaryConv2D.call of <binary_layers.BinaryConv2D object at 0x1ac37a9d50>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: 
WARNING: Entity <bound method BinaryConv2D.call of <binary_layers.BinaryConv2D object at 0x1ac37a9d50>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: 
WARNING:tensorflow:Entity <function streak at 0x1ac34def80> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: 
WARNING: Entity <function streak at 0x1ac34def80> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: 
WARNING:tensorflow:Entity <function Function._initialize_uninitialized_variables.<locals>.initialize_variables at 0x1ac8e150e0> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: 
WARNING: Entity <function Function._initialize_uninitialized_variables.<locals>.initialize_variables at 0x1ac8e150e0> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: 
Model: "model_8"

I dont care about the lambda layers as those should be non-trainable. However, I want the bin_conv2d to be trainable and it appears that something is preventing that but I cannot figure out why. I also dont understand the last warning of Entity function initialize_unitialized_variables is. Any help with this would be greatly appreciated.

To give an idea for what I'm trying to do, I generate a binary kernel in bin_conv2d and then element-wise multiply that by each input. I am wrapping everything in TimeDistributed as my inputs are videos and I want the outputs to be evaluated as such. The original implementation of bin_conv2d used the standard convolution and that compiled fine. It seems that once I changed it to be element-multiply it breaks down. The weird thing is that it seems that the binarize function is what breaks when I change the code even though I am not changing that at all.

Here is a link to my [gist](https://gist.github.com/matthewp14/dd77eea3464d39d49c618f4398723ce5)

**Describe the expected behavior**

**Standalone code to reproduce the issue** 
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

Here is the output when I set 

tf.autograph.set_verbosity(3, True)

INFO:tensorflow:Converted call: <bound method BinaryConv2D.call of <binary_layers.BinaryConv2D object at 0x1ac6957150>>
    args: (<tf.Tensor 'time_distributed_280/Reshape:0' shape=(60, 32, 32, 1) dtype=float32>,)
    kwargs: {}

Converted call: <bound method BinaryConv2D.call of <binary_layers.BinaryConv2D object at 0x1ac6957150>>
    args: (<tf.Tensor 'time_distributed_280/Reshape:0' shape=(60, 32, 32, 1) dtype=float32>,)
    kwargs: {}

INFO:tensorflow:Not whitelisted: <method-wrapper '__call__' of method object at 0x1ac5c17140>: default rule
Not whitelisted: <method-wrapper '__call__' of method object at 0x1ac5c17140>: default rule
INFO:tensorflow:Not whitelisted: <class 'binary_layers.BinaryConv2D'>: default rule
Not whitelisted: <class 'binary_layers.BinaryConv2D'>: default rule
INFO:tensorflow:Not whitelisted: <bound method BinaryConv2D.call of <binary_layers.BinaryConv2D object at 0x1ac6957150>>: default rule
Not whitelisted: <bound method BinaryConv2D.call of <binary_layers.BinaryConv2D object at 0x1ac6957150>>: default rule
INFO:tensorflow:Cache hit for entity <bound method BinaryConv2D.call of <binary_layers.BinaryConv2D object at 0x1ac6957150>> key <code object call at 0x1ac9f12030, file "/Users/matthew/Desktop/Desktop - Matthew’s MacBook Pro (74)/CUP-Net/src/binary_layers.py", line 158> subkey (<tensorflow.python.autograph.core.converter.ConversionOptions object at 0x1acb755dd0>, frozenset()): _ConvertedEntityFactoryInfo(tf__call in tmppbrtju_8)
Cache hit for entity <bound method BinaryConv2D.call of <binary_layers.BinaryConv2D object at 0x1ac6957150>> key <code object call at 0x1ac9f12030, file "/Users/matthew/Desktop/Desktop - Matthew’s MacBook Pro (74)/CUP-Net/src/binary_layers.py", line 158> subkey (<tensorflow.python.autograph.core.converter.ConversionOptions object at 0x1acb755dd0>, frozenset()): _ConvertedEntityFactoryInfo(tf__call in tmppbrtju_8)
INFO:tensorflow:Error transforming entity <bound method BinaryConv2D.call of <binary_layers.BinaryConv2D object at 0x1ac6957150>>
Traceback (most recent call last):
  File "/Users/matthew/opt/miniconda3/envs/engs89/lib/python3.7/site-packages/tensorflow_core/python/autograph/impl/api.py", line 506, in converted_call
    converted_f = conversion.convert(target_entity, program_ctx)
  File "/Users/matthew/opt/miniconda3/envs/engs89/lib/python3.7/site-packages/tensorflow_core/python/autograph/impl/conversion.py", line 324, in convert
    return _instantiate(entity, converted_entity_info, free_nonglobal_var_names)
  File "/Users/matthew/opt/miniconda3/envs/engs89/lib/python3.7/site-packages/tensorflow_core/python/autograph/impl/conversion.py", line 266, in _instantiate
    factory = converted_entity_info.get_factory()
  File "/Users/matthew/opt/miniconda3/envs/engs89/lib/python3.7/site-packages/tensorflow_core/python/autograph/impl/conversion.py", line 92, in get_factory
    assert self.module_name in sys.modules
AssertionError
Error transforming entity <bound method BinaryConv2D.call of <binary_layers.BinaryConv2D object at 0x1ac6957150>>
WARNING:tensorflow:Entity <bound method BinaryConv2D.call of <binary_layers.BinaryConv2D object at 0x1ac6957150>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: 
WARNING: Entity <bound method BinaryConv2D.call of <binary_layers.BinaryConv2D object at 0x1ac6957150>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: 
INFO:tensorflow:Converted call: <function streak at 0x1ac9e22320>
    args: (<tf.Tensor 'x:0' shape=(2, 30, 32, 32, 1) dtype=float32>,)
    kwargs: {}

Converted call: <function streak at 0x1ac9e22320>
    args: (<tf.Tensor 'x:0' shape=(2, 30, 32, 32, 1) dtype=float32>,)
    kwargs: {}

INFO:tensorflow:Cache hit for entity <function streak at 0x1ac9e22320> key <code object streak at 0x1ac9f12db0, file "/Users/matthew/Desktop/Desktop - Matthew’s MacBook Pro (74)/CUP-Net/src/lambda_layers.py", line 20> subkey (<tensorflow.python.autograph.core.converter.ConversionOptions object at 0x1acb837b50>, frozenset()): _ConvertedEntityFactoryInfo(tf__streak in tmpqw9832gt)
Cache hit for entity <function streak at 0x1ac9e22320> key <code object streak at 0x1ac9f12db0, file "/Users/matthew/Desktop/Desktop - Matthew’s MacBook Pro (74)/CUP-Net/src/lambda_layers.py", line 20> subkey (<tensorflow.python.autograph.core.converter.ConversionOptions object at 0x1acb837b50>, frozenset()): _ConvertedEntityFactoryInfo(tf__streak in tmpqw9832gt)
INFO:tensorflow:Error transforming entity <function streak at 0x1ac9e22320>
Traceback (most recent call last):
  File "/Users/matthew/opt/miniconda3/envs/engs89/lib/python3.7/site-packages/tensorflow_core/python/autograph/impl/api.py", line 506, in converted_call
    converted_f = conversion.convert(target_entity, program_ctx)
  File "/Users/matthew/opt/miniconda3/envs/engs89/lib/python3.7/site-packages/tensorflow_core/python/autograph/impl/conversion.py", line 324, in convert
    return _instantiate(entity, converted_entity_info, free_nonglobal_var_names)
  File "/Users/matthew/opt/miniconda3/envs/engs89/lib/python3.7/site-packages/tensorflow_core/python/autograph/impl/conversion.py", line 266, in _instantiate
    factory = converted_entity_info.get_factory()
  File "/Users/matthew/opt/miniconda3/envs/engs89/lib/python3.7/site-packages/tensorflow_core/python/autograph/impl/conversion.py", line 92, in get_factory
    assert self.module_name in sys.modules
AssertionError
Error transforming entity <function streak at 0x1ac9e22320>
WARNING:tensorflow:Entity <function streak at 0x1ac9e22320> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: 
WARNING: Entity <function streak at 0x1ac9e22320> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: 
Traceback (most recent call last):
  File "/Users/matthew/opt/miniconda3/envs/engs89/lib/python3.7/site-packages/tensorflow_core/python/autograph/impl/api.py", line 506, in converted_call
    converted_f = conversion.convert(target_entity, program_ctx)
  File "/Users/matthew/opt/miniconda3/envs/engs89/lib/python3.7/site-packages/tensorflow_core/python/autograph/impl/conversion.py", line 324, in convert
    return _instantiate(entity, converted_entity_info, free_nonglobal_var_names)
  File "/Users/matthew/opt/miniconda3/envs/engs89/lib/python3.7/site-packages/tensorflow_core/python/autograph/impl/conversion.py", line 266, in _instantiate
    factory = converted_entity_info.get_factory()
  File "/Users/matthew/opt/miniconda3/envs/engs89/lib/python3.7/site-packages/tensorflow_core/python/autograph/impl/conversion.py", line 92, in get_factory
    assert self.module_name in sys.modules
AssertionError
Traceback (most recent call last):
  File "/Users/matthew/opt/miniconda3/envs/engs89/lib/python3.7/site-packages/tensorflow_core/python/autograph/impl/api.py", line 506, in converted_call
    converted_f = conversion.convert(target_entity, program_ctx)
  File "/Users/matthew/opt/miniconda3/envs/engs89/lib/python3.7/site-packages/tensorflow_core/python/autograph/impl/conversion.py", line 324, in convert
    return _instantiate(entity, converted_entity_info, free_nonglobal_var_names)
  File "/Users/matthew/opt/miniconda3/envs/engs89/lib/python3.7/site-packages/tensorflow_core/python/autograph/impl/conversion.py", line 266, in _instantiate
    factory = converted_entity_info.get_factory()
  File "/Users/matthew/opt/miniconda3/envs/engs89/lib/python3.7/site-packages/tensorflow_core/python/autograph/impl/conversion.py", line 92, in get_factory
    assert self.module_name in sys.modules
AssertionError
INFO:tensorflow:Converted call: <function Function._initialize_uninitialized_variables.<locals>.initialize_variables at 0x1acd33c320>
    args: ()
    kwargs: {}

Converted call: <function Function._initialize_uninitialized_variables.<locals>.initialize_variables at 0x1acd33c320>
    args: ()
    kwargs: {}

INFO:tensorflow:Cache hit for entity <function Function._initialize_uninitialized_variables.<locals>.initialize_variables at 0x1acd33c320> key <code object initialize_variables at 0x14d357660, file "/Users/matthew/opt/miniconda3/envs/engs89/lib/python3.7/site-packages/tensorflow_core/python/eager/def_function.py", line 603> subkey (<tensorflow.python.autograph.core.converter.ConversionOptions object at 0x1acd3638d0>, frozenset({'initializer_map'})): _ConvertedEntityFactoryInfo(tf__initialize_variables in tmphhcwjhr8)
Cache hit for entity <function Function._initialize_uninitialized_variables.<locals>.initialize_variables at 0x1acd33c320> key <code object initialize_variables at 0x14d357660, file "/Users/matthew/opt/miniconda3/envs/engs89/lib/python3.7/site-packages/tensorflow_core/python/eager/def_function.py", line 603> subkey (<tensorflow.python.autograph.core.converter.ConversionOptions object at 0x1acd3638d0>, frozenset({'initializer_map'})): _ConvertedEntityFactoryInfo(tf__initialize_variables in tmphhcwjhr8)
INFO:tensorflow:Error transforming entity <function Function._initialize_uninitialized_variables.<locals>.initialize_variables at 0x1acd33c320>
Traceback (most recent call last):
  File "/Users/matthew/opt/miniconda3/envs/engs89/lib/python3.7/site-packages/tensorflow_core/python/autograph/impl/api.py", line 506, in converted_call
    converted_f = conversion.convert(target_entity, program_ctx)
  File "/Users/matthew/opt/miniconda3/envs/engs89/lib/python3.7/site-packages/tensorflow_core/python/autograph/impl/conversion.py", line 324, in convert
    return _instantiate(entity, converted_entity_info, free_nonglobal_var_names)
  File "/Users/matthew/opt/miniconda3/envs/engs89/lib/python3.7/site-packages/tensorflow_core/python/autograph/impl/conversion.py", line 266, in _instantiate
    factory = converted_entity_info.get_factory()
  File "/Users/matthew/opt/miniconda3/envs/engs89/lib/python3.7/site-packages/tensorflow_core/python/autograph/impl/conversion.py", line 92, in get_factory
    assert self.module_name in sys.modules
AssertionError
Error transforming entity <function Function._initialize_uninitialized_variables.<locals>.initialize_variables at 0x1acd33c320>
WARNING:tensorflow:Entity <function Function._initialize_uninitialized_variables.<locals>.initialize_variables at 0x1acd33c320> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: 
WARNING: Entity <function Function._initialize_uninitialized_variables.<locals>.initialize_variables at 0x1acd33c320> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: 
INFO:tensorflow:Converted call: <function streak at 0x1ac9e22320>
    args: (<tf.Tensor 'x:0' shape=(2, 30, 32, 32, 1) dtype=float32>,)
    kwargs: {}

Converted call: <function streak at 0x1ac9e22320>
    args: (<tf.Tensor 'x:0' shape=(2, 30, 32, 32, 1) dtype=float32>,)
    kwargs: {}

Traceback (most recent call last):
  File "/Users/matthew/opt/miniconda3/envs/engs89/lib/python3.7/site-packages/tensorflow_core/python/autograph/impl/api.py", line 506, in converted_call
    converted_f = conversion.convert(target_entity, program_ctx)
  File "/Users/matthew/opt/miniconda3/envs/engs89/lib/python3.7/site-packages/tensorflow_core/python/autograph/impl/conversion.py", line 324, in convert
    return _instantiate(entity, converted_entity_info, free_nonglobal_var_names)
  File "/Users/matthew/opt/miniconda3/envs/engs89/lib/python3.7/site-packages/tensorflow_core/python/autograph/impl/conversion.py", line 266, in _instantiate
    factory = converted_entity_info.get_factory()
  File "/Users/matthew/opt/miniconda3/envs/engs89/lib/python3.7/site-packages/tensorflow_core/python/autograph/impl/conversion.py", line 92, in get_factory
    assert self.module_name in sys.modules
AssertionError
Model: "model_9"
_____________________

INFO:tensorflow:Converted call: <function TensorLikeDataAdapter.__init__.<locals>.permutation at 0x1acd0b20e0>
    args: (<tf.Tensor 'args_0:0' shape=() dtype=int64>,)
    kwargs: {}

Converted call: <function TensorLikeDataAdapter.__init__.<locals>.permutation at 0x1acd0b20e0>
    args: (<tf.Tensor 'args_0:0' shape=() dtype=int64>,)
    kwargs: {}

INFO:tensorflow:Whitelisted: <function TensorLikeDataAdapter.__init__.<locals>.permutation at 0x1acd0b20e0>: DoNotConvert rule for tensorflow
Whitelisted: <function TensorLikeDataAdapter.__init__.<locals>.permutation at 0x1acd0b20e0>: DoNotConvert rule for tensorflow
INFO:tensorflow:Converted call: <function TensorLikeDataAdapter.__init__.<locals>.slice_batch_indices at 0x1acd0b2f80>
    args: (<tf.Tensor 'args_0:0' shape=(16,) dtype=int64>,)
    kwargs: {}

Converted call: <function TensorLikeDataAdapter.__init__.<locals>.slice_batch_indices at 0x1acd0b2f80>
    args: (<tf.Tensor 'args_0:0' shape=(16,) dtype=int64>,)
    kwargs: {}

INFO:tensorflow:Whitelisted: <function TensorLikeDataAdapter.__init__.<locals>.slice_batch_indices at 0x1acd0b2f80>: DoNotConvert rule for tensorflow
Whitelisted: <function TensorLikeDataAdapter.__init__.<locals>.slice_batch_indices at 0x1acd0b2f80>: DoNotConvert rule for tensorflow
INFO:tensorflow:Converted call: <function TensorLikeDataAdapter.__init__.<locals>.grab_batch at 0x1acd0b2440>
    args: (<tf.Tensor 'args_0:0' shape=(2,) dtype=int64>, (<tf.Tensor 'args_1:0' shape=(16, 30, 32, 32, 1) dtype=float32>, <tf.Tensor 'args_2:0' shape=(16, 30, 32, 32, 1) dtype=float32>))
    kwargs: {}

Converted call: <function TensorLikeDataAdapter.__init__.<locals>.grab_batch at 0x1acd0b2440>
    args: (<tf.Tensor 'args_0:0' shape=(2,) dtype=int64>, (<tf.Tensor 'args_1:0' shape=(16, 30, 32, 32, 1) dtype=float32>, <tf.Tensor 'args_2:0' shape=(16, 30, 32, 32, 1) dtype=float32>))
    kwargs: {}

INFO:tensorflow:Whitelisted: <function TensorLikeDataAdapter.__init__.<locals>.grab_batch at 0x1acd0b2440>: DoNotConvert rule for tensorflow
Whitelisted: <function TensorLikeDataAdapter.__init__.<locals>.grab_batch at 0x1acd0b2440>: DoNotConvert rule for tensorflow
Train on 16 samples
Epoch 1/10
WARNING:tensorflow:Gradients do not exist for variables ['time_distributed_280/kernel:0'] when minimizing the loss.
INFO:tensorflow:Converted call: <function Function._initialize_uninitialized_variables.<locals>.initialize_variables at 0x1acd133950>
    args: ()
    kwargs: {}

Converted call: <function Function._initialize_uninitialized_variables.<locals>.initialize_variables at 0x1acd133950>
    args: ()
    kwargs: {}

INFO:tensorflow:Cache hit for entity <function Function._initialize_uninitialized_variables.<locals>.initialize_variables at 0x1acd133950> key <code object initialize_variables at 0x14d357660, file "/Users/matthew/opt/miniconda3/envs/engs89/lib/python3.7/site-packages/tensorflow_core/python/eager/def_function.py", line 603> subkey (<tensorflow.python.autograph.core.converter.ConversionOptions object at 0x1ace7741d0>, frozenset({'initializer_map'})): _ConvertedEntityFactoryInfo(tf__initialize_variables in tmphhcwjhr8)
Cache hit for entity <function Function._initialize_uninitialized_variables.<locals>.initialize_variables at 0x1acd133950> key <code object initialize_variables at 0x14d357660, file "/Users/matthew/opt/miniconda3/envs/engs89/lib/python3.7/site-packages/tensorflow_core/python/eager/def_function.py", line 603> subkey (<tensorflow.python.autograph.core.converter.ConversionOptions object at 0x1ace7741d0>, frozenset({'initializer_map'})): _ConvertedEntityFactoryInfo(tf__initialize_variables in tmphhcwjhr8)
INFO:tensorflow:Error transforming entity <function Function._initialize_uninitialized_variables.<locals>.initialize_variables at 0x1acd133950>
Traceback (most recent call last):
  File "/Users/matthew/opt/miniconda3/envs/engs89/lib/python3.7/site-packages/tensorflow_core/python/autograph/impl/api.py", line 506, in converted_call
    converted_f = conversion.convert(target_entity, program_ctx)
  File "/Users/matthew/opt/miniconda3/envs/engs89/lib/python3.7/site-packages/tensorflow_core/python/autograph/impl/conversion.py", line 324, in convert
    return _instantiate(entity, converted_entity_info, free_nonglobal_var_names)
  File "/Users/matthew/opt/miniconda3/envs/engs89/lib/python3.7/site-packages/tensorflow_core/python/autograph/impl/conversion.py", line 266, in _instantiate
    factory = converted_entity_info.get_factory()
  File "/Users/matthew/opt/miniconda3/envs/engs89/lib/python3.7/site-packages/tensorflow_core/python/autograph/impl/conversion.py", line 92, in get_factory
    assert self.module_name in sys.modules
AssertionError
Error transforming entity <function Function._initialize_uninitialized_variables.<locals>.initialize_variables at 0x1acd133950>
WARNING:tensorflow:Entity <function Function._initialize_uninitialized_variables.<locals>.initialize_variables at 0x1acd133950> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: 
WARNING: Entity <function Function._initialize_uninitialized_variables.<locals>.initialize_variables at 0x1acd133950> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: 
Traceback (most recent call last):
  File "/Users/matthew/opt/miniconda3/envs/engs89/lib/python3.7/site-packages/tensorflow_core/python/autograph/impl/api.py", line 506, in converted_call
    converted_f = conversion.convert(target_entity, program_ctx)
  File "/Users/matthew/opt/miniconda3/envs/engs89/lib/python3.7/site-packages/tensorflow_core/python/autograph/impl/conversion.py", line 324, in convert
    return _instantiate(entity, converted_entity_info, free_nonglobal_var_names)
  File "/Users/matthew/opt/miniconda3/envs/engs89/lib/python3.7/site-packages/tensorflow_core/python/autograph/impl/conversion.py", line 266, in _instantiate
    factory = converted_entity_info.get_factory()
  File "/Users/matthew/opt/miniconda3/envs/engs89/lib/python3.7/site-packages/tensorflow_core/python/autograph/impl/conversion.py", line 92, in get_factory
    assert self.module_name in sys.modules
AssertionError
WARNING:tensorflow:Gradients do not exist for variables ['time_distributed_280/kernel:0'] when minimizing the loss.

**Comment by Saduf2019** [comment]
@matthewp14 
I do not find any gist, as mentioned by you.
Can you please try installing gast ( pip install gast==0.2.2), refer to [link](https://github.com/tensorflow/tensorflow/issues/32859) where the workaround is avaiable.
let us know if that helps.

**Comment by matthewp14** [comment]
@Saduf2019 thank you that did help with the initial warnings but I am still having the following problem. In this [gist](https://gist.github.com/matthewp14/dd77eea3464d39d49c618f4398723ce5) I can train the first model fine. However, when I add the two lambda layers in the second model it breaks and I am not sure why. I intended for there to be no trainable weights in the lambda layers but I dont understand why the model stops working as soon as I add those. it seems as though it stops tracking BinaryConv2D when I add those. If you could lend a hand with this that would be great. 

I added all the code that you need to run. To be clear, I redefined the lambda functions within the binary test file to product dummy validation data but the real functions are located within the lambda_layers.py file.

**Comment by Saduf2019** [comment]
@matthewp14 
Could you please confirm which tensor flow version should i replicate this issue.

**Comment by matthewp14** [comment]
@Saduf2019 i am using Tensorflow 2.0.0 installed using conda

**Comment by Saduf2019** [comment]
@matthewp14 
I ran the code shared by you and face a different error, please refer to this [link](https://colab.sandbox.google.com/gist/Saduf2019/2e75f9009b71f100a5e48179c590f813/37092.ipynb) for the same.

**Comment by matthewp14** [comment]
@Saduf2019 thats because you are not importing those modules. If you look at the gist that I linked in the previous comment, everything except for "binary_test.py" is a module and should be loaded as such. The only file to be executed is binary_test

**Comment by matthewp14** [comment]
@gowthamkpr I was able to figure this out and modify my code accordingly. I am closing this issue.
