### ISSUE TITLE
random_uniform for int32 broken on GPU

### ISSUE THREAD

**Issue by gaohuazuo** [tensorflow/tensorflow#3709]
`tf.random_uniform` with `dtype=tf.int32` always produces `106199773` on GPU.

```
In [3]: with tf.device('/cpu'): print(tf.random_uniform([], 0, 10, dtype=tf.int32).eval())
6

In [4]: with tf.device('/gpu'): print(tf.random_uniform([], 0, 10, dtype=tf.int32).eval())
1061997773
```

Environment:
CentOS 7
TensorFlow 0.9.0
GTX TITAN X
CUDA 7.5
NVIDIA 367.27

**Comment by gaohuazuo** [comment]
This is likely caused by conversion between float and int.

```
In [15]: tf.cast(0.0, 'int32').eval()
Out[15]: 1056964608
```

**Comment by girving** [comment]
That does seem like a bug, but it will be hard for us to reproduce since we don't have CentOS machines, and it doesn't seem to happen on what we do have.  Would you be up for investigating further?

**Comment by gaohuazuo** [comment]
Yes, I would like to.

**Comment by aselle** [comment]
Have you had a chance to do any more experiments, to try to isolate the problem?

**Comment by gaohuazuo** [comment]
A system reboot seems to fix the problem, for a few days. I will make more investigation the next time I have a chance.

**Comment by aselle** [comment]
Thanks for the update, let us know if you find anything else.
