### ISSUE TITLE
why is variable not partitioned by default in PS-based distributed training?

### ISSUE THREAD

**Issue by burgerkingeater** [tensorflow/tensorflow#37100]
Hello,
We found out when multiple PSes are used, there's always only one PS serving by default, and we need to explicitly set variable partitioning strategy(fix sized partitioner) to make use of every PS. Do we know why this is not the default behavior when PS is used?

**Comment by shuzhang1989** [comment]
I wonder why you are not trying out all-reducer architecture?

**Comment by gowthamkpr** [comment]
@burgerkingeater Did you try all-reducer architecture as mentioned above?

**Comment by gowthamkpr** [comment]
Closing this issue as it has been inactive for more than 15 days. Please add additional comments and we can open this issue again. Thanks!
