### ISSUE TITLE
Tensorflow 2.0 uncompatible with guinicorn

### ISSUE THREAD

**Issue by jccastrom** [tensorflow/tensorflow#37105]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information** 
- Have I written custom code
- OS Platform and Distribution (e.g.,Linux Ubuntu 18.04): 
- TensorFlow installed from binary
 - TensorFlow version 2.0: 
- Keras Version: tested with 2.3.1 and 2.3.0
- Python version: - 3.6.5
- CUDA/cuDNN version: - GPU model and memory:

**Describe the current behavior**

I have a feed-forward NN and I saved it as .h5 and I can make predictions, but when I set an endpoint using Flask and guinicorn and then I call my model for predictions I get the following message: 
AttributeError: 'gevent._local.local' object has no attribute 'value'

**Describe the expected behavior**
the expected behavior would be that when I made a request

curl -X POST ....
it returned the predictions for my request

**Comment by Saduf2019** [comment]
@jccastrom 
please share a simple stand alone code with all dependencies for us to replicate the issue faced.
Also please refer to this [link](https://stackoverflow.com/questions/58018009/attributeerror-gevent-local-local-object-has-no-attribute-value) for reference

**Comment by Saduf2019** [comment]
@jccastrom 
Could you please update on the above comment.
