### ISSUE TITLE
How to build Tflite-gpu to use GPU delegate, NNAPI delegate for devices like Hikey (AARCH64)

### ISSUE THREAD

**Issue by pranathibl** [tensorflow/tensorflow#37116]
I was trying to use label_image.cpp example in Tflite. I was unable to make use of delegate options in the example after setting gl_backend, useNNAPI , accel and old accel , hexagon etc.. delegate flags to true. 

Is GPU delegate only restricted to Android and Ios devices ?

If not how to build TFlite with gpu on other devices like host pc for simulation, Hikey(AArch64) and Raspberry Pi(armv7,rpi) ?

Is NNAPI & Hexagon delegate only restricted to Android and Ios devices ?
If not how to build TFlite with NNAPI on other devices like host pc for simulation, Hikey(AArch64) and Raspberry Pi(armv7,rpi) ?

Does devices having snapdragon soc's such as (835,660) which are running in Linux(development boards which dont have Android Os). If yes , how to build with the delegate and increase performance ?

I don't find any Makefile to build with these delegate options enabled. Could you provide steps to build (or) Makefile for making use of these delegate options?

**Comment by terryheo** [comment]
Currently GPU delegate only works on Android and iOS.
And NNAPI is only available on Android.
https://developer.android.com/ndk/guides/neuralnetworks

**Comment by ivelin** [comment]
Is there roadmap visibility when Raspberry Pi 4 GPU will be a supported TFLite GPU delegate?
