### ISSUE TITLE
AttributeError: module 'tensorboard.summary._tf.summary' has no attribute 'FileWriter'

### ISSUE THREAD

**Issue by ayushmankumar7** [tensorflow/tensorflow#37113]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information** 
- Have I written custom code (as opposed to using a stock
example script provided in TensorFlow): 
- OS Platform and Distribution (e.g.,
Linux Ubuntu 16.04):  Linux Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if
the issue happens on mobile device: 
- TensorFlow installed from (source or
binary): pip3
 - TensorFlow version (use command below): 2.1.0 
- Python version: - Bazel
version (if compiling from source):
- GCC/Compiler version (if compiling from
source): 
- CUDA/cuDNN version: - GPU model and memory:

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**

**Describe the expected behavior**

**Standalone code to reproduce the issue** 
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.
2020-02-27 10:37:08.494214: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
[       OK ] ModuleTest.testBuiltInName
[ RUN      ] ModuleTest.testCanLoadWithPkgutil
[       OK ] ModuleTest.testCanLoadWithPkgutil
[ RUN      ] ModuleTest.testCompatV2HasCompatV1
[       OK ] ModuleTest.testCompatV2HasCompatV1
[ RUN      ] ModuleTest.testDict
[       OK ] ModuleTest.testDict
[ RUN      ] ModuleTest.testDocString
[       OK ] ModuleTest.testDocString
[ RUN      ] ModuleTest.testName
[       OK ] ModuleTest.testName
[ RUN      ] ModuleTest.testSummaryMerged
[  FAILED  ] ModuleTest.testSummaryMerged
[ RUN      ] ModuleTest.test_session
[  SKIPPED ] ModuleTest.test_session
======================================================================
ERROR: testSummaryMerged (__main__.ModuleTest)
testSummaryMerged (__main__.ModuleTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "module_test.py", line 79, in testSummaryMerged
    tf.summary.FileWriter
AttributeError: module 'tensorboard.summary._tf.summary' has no attribute 'FileWriter'

----------------------------------------------------------------------
Ran 8 tests in 0.035s

**Comment by ayushmankumar7** [comment]
@Saduf2019  Please check the changes i made.

**Comment by Saduf2019** [comment]
@ayushmankumar7 
In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thanks!

Could you try "changing tf.summary.FileWriter() to tf.train.SummaryWriter()"
Also you may check #412 [link](https://github.com/eriklindernoren/PyTorch-YOLOv3/issues/327)

**Comment by ayushmankumar7** [comment]
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/api/tests/module_test.py
This is the link to the code snippet to reproduce the issue.

**Comment by ayushmankumar7** [comment]
@Saduf2019 
Changing tf.summar.FileWrite() to tf.train.SummaryWriter() gives the following error: 

Traceback (most recent call last):
  File "module_test.py", line 79, in testSummaryMerged
    tf.train.SummaryWriter()
AttributeError: module 'tensorflow_core._api.v2.train' has no attribute 'SummaryWriter'

**Comment by Saduf2019** [comment]
@ayushmankumar7 
please let us know if we could move this to closed status as it is monitored in #37223

**Comment by ayushmankumar7** [comment]
Yeah. It's not a problem.

**Comment by Saduf2019** [comment]
Moving this issue to closed status with confirmation that it will be monitored in #37233

**Comment by dan-r95** [comment]
In Google Colab, you can use the magic word ```%tensorflow_version 1.x``` to select tensorflow version 1.
