### ISSUE TITLE
Tflite build error on Android.

### ISSUE THREAD

**Issue by Artaches** [tensorflow/tensorflow#37110]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): 18
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: All of them
- TensorFlow installed from (source or binary): source
- TensorFlow version: r2.2-nightly
- Python version: 3.7.3
- Installed using virtualenv? pip? conda?:
- Bazel version (if compiling from source): 2.0.0
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Describe the problem**

I've built a arm64 .so from master (using commit: 001037c4692a09e453777a96a609251cb7c94fac) and I'm including `tensorflow/tensorflow/lite` headers into my Android project. However, I'm getting the following error when I attempt to build my android project: 
```
In file included from ...../distribution/include/tensorflow\tensorflow/lite/core/subgraph.h:27:

...../distribution/include/tensorflow\tensorflow/lite/delegates/nnapi/nnapi_delegate.h:23:10: fatal error: 'absl/types/optional.h' file not found

#include "absl/types/optional.h"

         ^~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
ninja: build stopped: subcommand failed.
```
Building the project using .so from r2.1 or earlier branches + using headers of the same version works fine.
Also if I attempt using .so build from master but use old headers from `r2.1`, the Android project builds but fails whenever using the tflite interpreter.

**Comment by terryheo** [comment]
Did you run lite/tools/make/download_dependencies.sh to download proper ABSL library?

**Comment by Artaches** [comment]
I've ran `./tensorflow/lite/tools/make/download_dependencies.sh` and it seemed to have completed downloading everything with no errors. However, after re-building the .so (using command `bazel build --cxxopt='-std=c++11' -c opt --config=android_arm64 //tensorflow/lite:libtensorflowlite.so`) I still get the same error when trying to build the Android project.

**Comment by terryheo** [comment]
Oh, you're using Bazel. So it's ok to build TFLite only in Tensorflow repo, right?
I think you need to copy some dependencies from tensorflow/workspace.bzl so the Bazel can download necessary files.

**Comment by Artaches** [comment]
@terryheo I'm not sure what your suggestion for me to try is. Could you please clarify what you'd like me to try with exact steps I need to do?

**Comment by terryheo** [comment]
Since this is a build issue of your custom repo, we can't support it further.
You need to check how Bazel downloads dependencies.

**Comment by tailsu** [comment]
Manually adding `tensorflow/lite/tools/make/downloads/absl` to the downstream project's include path fixes this error.

**Comment by Artaches** [comment]
I can confirm that adding `${TENSORFLOW_DIR}/tensorflow/lite/tools/make/downloads/absl` to `target_include_directories` in our cmake build file fixed it. Thanks @tailsu!

**Comment by AlexandreK38** [comment]
@Artaches did you just add `adsl` headers or code/library too? I added the headers to the includes as you but my Android project fails when running on `tflite::InterpreterBuilder(*model, resolver)(&interpreter);`
