### ISSUE TITLE
Custom training loop, iteration over Dataset hangs under MultiWorkerMirroredStrategy

### ISSUE THREAD

**Issue by 372046933** [tensorflow/tensorflow#37112]
**System information** 
- Have I written custom code (as opposed to using a stock
example script provided in TensorFlow):  Yes
- OS Platform and Distribution (e.g.,
Linux Ubuntu 16.04): TensorFlow 2.0.1 GPU official docker image
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if
the issue happens on mobile device: 
- TensorFlow installed from (source or
binary): - TensorFlow version (use command below): 2.0.1
- Python version: - Bazel 
version (if compiling from source):
- GCC/Compiler version (if compiling from
source): 
- CUDA/cuDNN version: - GPU model and memory: CUDA 10.1 V100 16G

**Describe the current behavior**
I use the following scheme to iterate over Dataset.
```
for epoch in range(FLAGS.epoch):
        for train_data in train_dataset:
           ...
```
Train stops at the last few batches of the first epoch. I found that documentation https://www.tensorflow.org/tutorials/distribute/multi_worker_with_keras  mentions only `keras.fit`
**Describe the expected behavior**
It should be explicitly mentioned, or produce some logs when running in such scenario.
Currently, before the hang, only one line is printed in log.
```
INFO:tensorflow:Collective batch_all_reduce: xxx all-reduces, num_workers = xxx
I0225 cross_device_ops.py:1107] Collective batch_all_reduce: xxx all-reduces, num_workers = xxx
```

**Standalone code to reproduce the issue** 
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by ravikyram** [comment]
@372046933 

Request you to share colab link or simple standalone code to reproduce the issue in our environment. It helps us in localizing the issue faster. Thanks!

**Comment by Flamefire** [comment]
This is just a documentation issue. The doc currently states (https://www.tensorflow.org/tutorials/distribute/multi_worker_with_keras)

> [...] MultiWorkerMirroredStrategy does not support last partial batch handling […]

But this isn't mentioned in the docu of `MultiWorkerMirroredStrategy`.

Of course it would be better to not have that limitation

**Comment by 372046933** [comment]
@Flamefire Sorry, my company forbid copy any data out. Only data in. Otherwise I have uploaded all the code.

**Comment by ravikyram** [comment]
@372046933 

Will it be possible to share the sample data so i can test it on the Tesnsorflow tutorials to reproduce the issue.Thanks!

**Comment by 372046933** [comment]
@ravikyram Sorry, can't either. In only, no out :(. The data is actually ImageNet in TFRecord format.  So I think you can build sample data with fixed size image.
