### ISSUE TITLE
How to save model by training steps using tf.keras.callbacks.ModelCheckpoint

### ISSUE THREAD

**Issue by luozhouyang** [tensorflow/tensorflow#37118]
My training data is very large, which means it have many training steps each epoch. I want to use `tf.keras.callbacks.ModelCheckpoint` to save a model every `100,000` steps, and save all these models in disk, not rewrite the model files when saving a new one. But I have no idea how to do this after i read the documentation. It seems that this callback is designed to save a model by epoch.

So, do i have to implement a custom callback to save the model by steps?

**Comment by Saduf2019** [comment]
@luozhouyang  
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged//tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.

**Comment by luozhouyang** [comment]
ok
