### ISSUE TITLE
representative_data_gen input order?

### ISSUE THREAD

**Issue by tigert1998** [tensorflow/tensorflow#37111]
In tflite post integer quantization, `converter.representative_dataset` is necessary.

However, the documentation never specifies the order of the fed inputs. Are they ordered by lexicographic order of the names, size of shapes or even random order? When multiple inputs are present, it is totally a guessing game.

**Comment by jvishnuvardhan** [comment]
@tigert1998 Are you interested in raising a PR to update the docs? Thanks!

**Comment by tigert1998** [comment]
No, since I don't know either.

**Comment by ashutosh1919** [comment]
@tigert1998 and @jvishnuvardhan , I have added line in doc corresponding to the necessity of `converter.representative_dataset`. You have also mentioned something about order of inputs. I don't understand that. Can you please elaborate so that I will also make changes corresponding to that in the doc if needed.

**Comment by tigert1998** [comment]
@ashutosh1919 
For instance, suppose that I generate a `saved_model` model with the following code:
```py
# inputs: List[Tensor]
# outputs: List[Tensor]

inputs_dic = {
    "input_{}".format(idx): i
    for idx, i in zip(range(len(inputs)), inputs)
}
outputs_dic = {
    "output_{}".format(idx): o
    for idx, o in zip(range(len(outputs)), outputs)
}
builder = tf.saved_model.builder.SavedModelBuilder(path)
sigs = {}
sigs[signature_constants.DEFAULT_SERVING_SIGNATURE_DEF_KEY] = \
    tf.saved_model.signature_def_utils.predict_signature_def(
    inputs_dic, outputs_dic
)
builder.add_meta_graph_and_variables(
    sess,
    [tag_constants.SERVING],
    signature_def_map=sigs
)
builder.save()
```

However, the fed inputs in `representative_data_gen` are not necessarily in the order of `input_0`, `input_1`, etc.

**Comment by ashutosh1919** [comment]
@tigert1998 , Can you please provide the link of the file in tensorflow where you have checked this code. I also want to take a look at it.

**Comment by DaviesX** [comment]
This has not been resolved yet. It seems like the order is arbitrary. The order even changes when loading the same saved model file. When there are multiple inputs of different shapes, the tflite converter is unusable.

**Comment by jvishnuvardhan** [comment]
@DaviesX Can you please open a new issue with a simple standalone code to reproduce the issue? As the current issue is older, it is better to open a new issue so that we can track and resolve the issue faster. Thanks!

**Comment by DaviesX** [comment]
@jvishnuvardhan  My issue actually has other causes besides having multiple inputs. This should go to a separate issue.
