### ISSUE TITLE
AttributeError: module 'tensorflow' has no attribute 'app' in tensorflow 2.1.0

### ISSUE THREAD

**Issue by Billy1900** [tensorflow/tensorflow#37128]
**System information** 
- OS Platform and Distribution (e.g.,
Linux Ubuntu 16.04): Windows 10
- TensorFlow installed from (source or
binary): source
- TensorFlow version (use command below): V2.1.0
- Python version: 3.7.6
- CUDA/cuDNN version: 10.1/7.6
- GPU model and memory: GTX 1050, 8G

**Describe the current behavior**
I write `FLAGS = tf.compat.v1.flags.FLAGS` in my file, but there is still an error,
`
 FLAGS = tf.compat.v1.app.flags.FLAGS
AttributeError: module 'tensorflow' has no attribute 'app'
`

**Comment by ayushmankumar7** [comment]
![Screenshot from 2020-02-27 23-25-58](https://user-images.githubusercontent.com/41910134/75471693-9365d380-59b8-11ea-8a1b-e90078a4ed5a.png)

I am using the same version.This Shouldn't happen.

Tensorflow didn't have any attribute 'app' ever, i guess.

**Comment by Billy1900** [comment]
yeah, if I type the same command in my prompt, it shows me the same results.
<code>
>>> tf.version.VERSION
'2.1.0'
>>> tf.compat.v1.flags.FLAGS
<tensorflow.python.platform.flags._FlagValuesWrapper object at 0x000001CC872DFF48>
</code>

but it did occur when I compile my file,  all the information is as following:
<code>
I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_101.dll
Traceback (most recent call last):
  File "C:\Users\PC\Desktop\gae-master\gae-upgrade\train.py", line 14, in <module>
    from gae.optimizer import OptimizerAE, OptimizerVAE
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
  File "D:\Anaconda\envs\tensorflow\lib\site-packages\gae-0.0.1-py3.7.egg\gae\optimizer.py", line 3, in <module>
    FLAGS = tf.compat.v1.flags.FLAGS
AttributeError: module 'tensorflow' has no attribute 'app'
</code>

**Comment by gadagashwini** [comment]
@Billy1900, Please take a look at similar issue [#34431(comment)](https://github.com/tensorflow/tensorflow/issues/34431#issuecomment-555836995) help you to resolve this issue. Thanks!

**Comment by gadagashwini** [comment]
@Billy1900, Was the above comment help you to resolve this issue?

**Comment by Billy1900** [comment]
> @Billy1900, Was the above comment help you to resolve this issue?

sort of, I have to use the previous version to run my code. but it is not what i truly want.

**Comment by gadagashwini** [comment]
@Billy1900, Did you try with `import tensorflow.compat.v1 as tf`?

**Comment by Billy1900** [comment]
> @Billy1900, Did you try with `import tensorflow.compat.v1 as tf`?

isn't it with the same meaning as `FLAGS = tf.compat.v1.flags.FLAGS` I wrote?

**Comment by ymodak** [comment]
`'tf.app` is removed from TF2. So using `compat.v1` is the only way. Thanks!
