### ISSUE TITLE
Conda install Tensorflow 2.1 with mkl (avx/avx2 support) not working

### ISSUE THREAD

**Issue by wangzhizhengduke** [tensorflow/tensorflow#37139]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- TensorFlow installed from (source or binary):  tensorflow 3.1 with mkl binary from Anaconda installation
- TensorFlow version: 3.1.0
- Python version: 3.7.6
- Installed using virtualenv? pip? conda?: conda
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: na
- GPU model and memory: na

I was using tensorflow 2.0 with mkl (avx/avx2 optimization) and has zero problem. I just upgraded to tf 2.1 using Anaconda. After upgrade, tf complains that "Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX AVX2".

To make sure I upgraded correctly. I uninstalled all tensorflow components, and then do a fresh install using command conda install tensorflow-mkl. The installation succeed but the problem persists.

when I run the same training script, I saw the performance is worse than the 2.0. So, I guess the avx2 is not used in 2.1

**Comment by gadagashwini** [comment]
@wangzhizhengduke, Can you provide the standalone complete code to analyze the issue. Thanks!

**Comment by gadagashwini** [comment]
@wangzhizhengduke, Can you provide more information to understand the issue better. Thanks!

**Comment by gadagashwini** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Comment by gmatalongthewatchtower** [comment]
I have tensorflow2.0 with mkl. Can you please help here? 

Here's the code:

```
import tensorflow as tf
from tensorflow import keras

input_A = keras.layers.Input(shape=[5], name="wide_input")
input_B = keras.layers.Input(shape=[6], name="deep_input")
hidden1 = keras.layers.Dense(30, activation="relu")(input_B)
hidden2 = keras.layers.Dense(30, activation="relu")(hidden1)
concat = keras.layers.concatenate([input_A, hidden2])
output = keras.layers.Dense(1, name="output")(concat)
model = keras.models.Model(inputs=[input_A, input_B], outputs=[output])

```

Here's the output:
```
2020-12-12 17:06:46.037846: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX AVX2
2020-12-12 17:06:46.040928: I tensorflow/core/common_runtime/process_util.cc:147] Creating new thread pool with default inter op setting: 2. Tune using inter_op_parallelism_threads for best performance.
```
Please let me know how I can assist in debugging this issue.

Here's the mkl check from https://software.intel.com/content/www/us/en/develop/articles/intel-optimization-for-tensorflow-installation-guide.html
Code:
```
major_version = int(tf.__version__.split(".")[0])
if major_version >= 2:
   from tensorflow.python import _pywrap_util_port
   print("MKL enabled:", _pywrap_util_port.IsMklEnabled())
else:
   print("MKL enabled:", tf.pywrap_tensorflow.IsMklEnabled()) 
```
Output:

`MKL enabled: True
`
