### ISSUE TITLE
NameError: name 'LSTM' is not defined 

### ISSUE THREAD

**Issue by rehanmahmood** [tensorflow/tensorflow#37137]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):  **MAC OS CATALINA**
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): **I'm pretty sure it is binary**
- TensorFlow version: **2.1.0**
- Python version: **3.7.6**
- Installed using virtualenv? pip? conda?: **pip3**
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: **10.2**
- GPU model and memory:  **Intel HD Graphics 4000 1536 MB** . Memory = **4 GB 1600 MHz DDR3**

**The problem**
I am attempting to build a LSTM model to process and predict datasets.  I have tensorflow installed on my mac and have keras installed.  I have also installed CUDA and some other sequential model libraries I heard would help, but my problem persists.  My program is returning the error

`Traceback (most recent call last):
  File "/Users/owner/Desktop/algo/predict.py", line 64, in <module>
    model.add(LSTM(50, return_sequences=True, input_shape=(x_train.shape[1], 1)))
NameError: name 'LSTM' is not defined`

My import statements look like this:

`import requests`
`import math`
`import numpy as np`
`import pandas as pd`
`import pandas_datareader as web`
`import tensorflow as tf`
`from tensorflow import keras`
`from tensorflow.keras import layers`
`from tensorflow.keras.models import Sequential, load_model`
`from sklearn.preprocessing import MinMaxScaler`
`from bs4 import BeautifulSoup`
`import matplotlib.pyplot as plt`
`from datetime import datetime, date`

and the code for the model looks like this:

`#Build LSTM MODEL`
`model = tf.keras.Sequential()`
`model.add(LSTM(50, return_sequences=True, input_shape=(x_train.shape[1], 1)))`
`model.add(LSTM(50, return_sequences=False))`
`model.add(Dense(25))`
`model.add(Dense(1))`
`model.compile(optimizer='adam', loss='mean_squared_error')`

I tried to look for an import statement that could import lstm from tensorflow
something like:
`from tensorflow.keras.models import LSTM`
But I could not find anything.

ThankYou,
RRR.

**Comment by ayushmankumar7** [comment]
It should be from tensorflow.keras.layers import LSTM

**Comment by ayushmankumar7** [comment]
After solving for LSTM, you'll  get the same error for Dense. 
Do something, use  layers.LSTM and layers.Dense instead of LSTM and DENSE directly cuz you have already imported "layers"

**Comment by amahendrakar** [comment]
@rehanmahmood,
Could you please add these two import statements in your code
```
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense
```
Please take a look at [this](https://colab.sandbox.google.com/gist/amahendrakar/0b12b11b100e169afc1bfd1a61cdcb78/37137.ipynb) gist as a reference. Thanks!

**Comment by rehanmahmood** [comment]
Yessir thank you.  However I am returning a completely different error now.  Could you please see this issue.

https://github.com/tensorflow/tensorflow/issues/37149

**Comment by jaketae** [comment]
I think it would be a good idea to close this issue given that you have opened a new issue that is being discussed in a separate thread!
