### ISSUE TITLE
Analysis of target '//tensorflow/tools/pip_package:build_pip_package' failed; build aborted: no such package '@png_archive//': Traceback (most recent call last):

### ISSUE THREAD

**Issue by shahansha-c** [tensorflow/tensorflow#37138]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):Windows 10
- TensorFlow installed from (source or binary): Source
- TensorFlow version:1.13
- Python version: 3.6.7
- Bazel version (if compiling from source):0.21.0
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:10.0
- GPU model and memory: Geforce GTX 1050/4gb

**when i try to build tensorflow from source with below command it arises errors**

`**bazel build --config=opt --config=cuda --define=no_tensorflow_py_deps=true //tensorflow/tools/pip_package:build_pip_package**
`

```
**C:\Tensorflow_build\tensorflow>bazel build --config=opt --config=cuda --define=no_tensorflow_py_deps=true //tensorflow/tools/pip_package:build_pip_package
WARNING: The following rc files are no longer being read, please transfer their contents or import their path into one of the standard rc files:
c:\tensorflow_build\tensorflow/.bazelrc
WARNING: The following configs were expanded more than once: [cuda]. For repeatable flags, repeats are counted twice and may lead to unexpected behavior.
WARNING: Option 'experimental_shortened_obj_file_path' is deprecated
INFO: Invocation ID: 72078163-23a3-48fa-bd94-3ebfaea84d8b
ERROR: Analysis of target '//tensorflow/tools/pip_package:build_pip_package' failed; build aborted: no such package '@png_archive//': Traceback (most recent call last):
        File "C:/tensorflow_build/tensorflow/third_party/repo.bzl", line 106
                _apply_patch(ctx, ctx.attr.patch_file)
        File "C:/tensorflow_build/tensorflow/third_party/repo.bzl", line 73, in _apply_patch
                _execute_and_check_ret_code(ctx, cmd)
        File "C:/tensorflow_build/tensorflow/third_party/repo.bzl", line 52, in _execute_and_check_ret_code
                fail("Non-zero return code({1}) when ...))
Non-zero return code(2) when executing 'C:\tools\msys64\usr\bin\bash.exe -l -c "patch" "-p1" "-d" ""C:/users/shahansha c/_bazel_shahansha c/6v547imx/external/png_archive"" "-i" "C:/tensorflow_build/tensorflow/third_party/png_fix_rpi.patch"':
Stdout:
Stderr: patch: **** Can't change to directory C:/users/shahansha : No such file or directory
INFO: Elapsed time: 6.859s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (5 packages loaded, 338 targets configured)
    Fetching @icu; fetching 5s
    Fetching @grpc; fetching 5s
    Fetching @eigen_archive; fetching 5s
    Fetching @boringssl; fetching 5s
    Fetching @png_archive; fetching 5s
    Fetching @curl; fetching 5s
    Fetching @swig; fetching 5s
    Fetching @nasm; fetching**
```

i have a space in my username :(
may be that is the problem But i dont know how to change it
is there any way to build tensorflow from source when there is a white space in user name (on the path)

**Comment by shahansha-c** [comment]
there is no reply :(

**Comment by ravikyram** [comment]
Just to verify did you follow the instuctions from [Tensorflow website](https://www.tensorflow.org/install/gpu#windows_setup) and followed the [tested build configurations](https://www.tensorflow.org/install/source_windows#gpu)..Make sure you update environment path for cuda. Provide the exact sequence of commands / steps that you executed before running into the problem.Thanks!

**Comment by shahansha-c** [comment]
followed the instruction from [Build from source on Windows](https://www.tensorflow.org/install/source_windows)

**Comment by shahansha-c** [comment]
i am trying to build the tensorflow from source to just convert my custom trained object detection ssd model to to tensorflow lite. is there any way to do that without building tensorflow from source?
i have already installed tensorflow by pip

**Comment by hmzsaeed** [comment]
I'm having the same issue. Did u find any solution?
