### ISSUE TITLE
Save and load model neural network

### ISSUE THREAD

**Issue by AlturRang** [tensorflow/tensorflow#37135]
Hi,
I am a beginner in neural network, I follow a tutorial (https://www.datacamp.com/community/tutorials/cnn-tensorflow-python) for create it.
[tuto.py.tar.gz](https://github.com/tensorflow/tensorflow/files/4262620/tuto.py.tar.gz)
-> It is my soft.

I add some lines to save a model of my network. I have ".meta" file.
My problem is, how I can use this model on an other soft for predict if I have shirt, coat, ... in my image.

**Comment by AlturRang** [comment]
Sorry, I forget something. I want to do load with low level tensorflow API. 
Because with keras I know how to do that

**Comment by gadagashwini** [comment]
@AlturRang, Please find the [Tensorflow doc](https://www.tensorflow.org/api_docs/python/tf/saved_model/load) for loading the saved model. Use tf.saved_mdel.load() function as 
`imported = tf.saved_model.load(path)` to load saved model .
Thanks!

**Comment by AlturRang** [comment]
@gadagashwini, Thanks for your quick answer. I try to use the function that you say. But I have a problem with:
path ='/home/cassip01/tuto_tensorflow/fashion_mnist'
loaded = tf.saved_model.load(path, None)
When I execute the soft I have this error:
Traceback (most recent call last):
  File "load.py", line 9, in <module>
    loaded = tf.saved_model.load(path, None)
  File "/home/cassip01/.local/lib/python3.5/site-packages/tensorflow_core/python/util/deprecation.py", line 324, in new_func
    return func(*args, **kwargs)
TypeError: load() missing 1 required positional argument: 'export_dir'
Do you have an idea what is the problem exactly?
Because I put 2 argument, the path for the model and the tags

**Comment by gadagashwini** [comment]
@AlturRang, Can you share the complete code to analyze the issue. Thanks!

**Comment by AlturRang** [comment]
[fashion_mnist.tar.gz](https://github.com/tensorflow/tensorflow/files/4274156/fashion_mnist.tar.gz)
In this folder you can see "tuto.py" for the training of the neural network and "load.py" is for load the neural network's model.
I use python 3.5 for execute python file

**Comment by gadagashwini** [comment]
@AlturRang, Can you share the Tensorflow version that you are using. Thanks!

**Comment by AlturRang** [comment]
I use tensorflow 1.15.0

**Comment by gadagashwini** [comment]
I was able to replicate the issue with Tf 1.15.
Please find the gist [here](https://colab.sandbox.google.com/gist/gadagashwini/63019ec8c97b8220b06605ccd5dec1b9/untitled433.ipynb). Thanks

**Comment by AlturRang** [comment]
Sorry I have very busy, so I can't answer early.
Ok, you have the same error like me but do you find an answer to fix it?

**Comment by gowthamkpr** [comment]
@AlturRang The issue is with saving the model here. The model is not being saved correctly. I would recommed to post this issue in satckoverflow as it is not a bug/performance, build/install, feature request related issue where there is a wider community to respond. Thanks!
