### ISSUE TITLE
Can I use asymmetrical images as input?

### ISSUE THREAD

**Issue by Tylersuard** [tensorflow/tensorflow#37143]
For instance, an image of 500x3000 pixels.

**Comment by amahendrakar** [comment]
@Tylersuard,
If you are pre-processing the images to resize all of them to fixed size then yes, you can use asymmetrical images as inputs while training.

For more information, you can check [this](https://www.tensorflow.org/tutorials/load_data/images#load_using_tfdata) example from Tensorflow, which uses images of different sizes for training.

**Comment by Tylersuard** [comment]
Thank you for your help!
