### ISSUE TITLE
convert_to_records meet a bug

### ISSUE THREAD

**Issue by dzhwinter** [tensorflow/tensorflow#3715]
When I run the convert_to_records in how_to demo, show me the message. 
I just trash the reshape parameter and meet other bugs, it seems simple to fix.

```
Traceback (most recent call last):
  File "convert_to_records.py", line 91, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 30, in run
    sys.exit(main(sys.argv))
  File "convert_to_records.py", line 82, in main
    reshape=False)
TypeError: read_data_sets() got an unexpected keyword argument 'reshape'
```

**Comment by girving** [comment]
We'll need more information:

1. Which tutorial code are you copying from?
2. Which `read_data_sets` function doesn't have a reshape argument?

The only tutorial which I see using a `reshape` argument calls a `read_data_sets` function that does take that argument.

**Comment by jambino** [comment]
I get the same error. I'm using the code found here:
https://github.com/tensorflow/tensorflow/blob/r0.10/tensorflow/examples/how_tos/reading_data/convert_to_records.py

**Comment by jambino** [comment]
I did some digging and it looks like for me, this might be related to the version of the code available from conda-forge. I checked the file:
~/tensorflow/lib/python3.5/site-packages/tensorflow/contrib/learn/python/learn/datasets/mnist.py 

Which is where that function comes from and indeed it does not have a reshape argument like the later version do. I'll try reinstalling with pip.

**Comment by vincentvanhoucke** [comment]
Closing as stale. Feel free to reopen if this is a relevant issue today.
