### ISSUE TITLE
Tensorflow 2 installation problem in windows 10

### ISSUE THREAD

**Issue by abhinabasaha** [tensorflow/tensorflow#37156]
(base) C:\Windows\system32>pip install tensorflow
Collecting tensorflow
  Using cached tensorflow-2.1.0-cp37-cp37m-win_amd64.whl (355.8 MB)
Requirement already satisfied: absl-py>=0.7.0 in c:\programdata\anaconda3\lib\site-packages (from tensorflow) (0.8.1)
Requirement already satisfied: tensorflow-estimator<2.2.0,>=2.1.0rc0 in c:\programdata\anaconda3\lib\site-packages (from tensorflow) (2.1.0)
Requirement already satisfied: keras-applications>=1.0.8 in c:\programdata\anaconda3\lib\site-packages (from tensorflow) (1.0.8)
Requirement already satisfied: tensorboard<2.2.0,>=2.1.0 in c:\programdata\anaconda3\lib\site-packages (from tensorflow) (2.1.0)
Requirement already satisfied: termcolor>=1.1.0 in c:\programdata\anaconda3\lib\site-packages (from tensorflow) (1.1.0)
Requirement already satisfied: wrapt>=1.11.1 in c:\programdata\anaconda3\lib\site-packages (from tensorflow) (1.11.2)
Requirement already satisfied: six>=1.12.0 in c:\programdata\anaconda3\lib\site-packages (from tensorflow) (1.14.0)
Requirement already satisfied: wheel>=0.26; python_version >= "3" in c:\programdata\anaconda3\lib\site-packages (from tensorflow) (0.34.2)
Requirement already satisfied: grpcio>=1.8.6 in c:\programdata\anaconda3\lib\site-packages (from tensorflow) (1.25.0)
Requirement already satisfied: numpy<2.0,>=1.16.0 in c:\programdata\anaconda3\lib\site-packages (from tensorflow) (1.18.1)
Requirement already satisfied: scipy==1.4.1; python_version >= "3" in c:\programdata\anaconda3\lib\site-packages (from tensorflow) (1.4.1)
Requirement already satisfied: gast==0.2.2 in c:\programdata\anaconda3\lib\site-packages (from tensorflow) (0.2.2)
Requirement already satisfied: google-pasta>=0.1.6 in c:\programdata\anaconda3\lib\site-packages (from tensorflow) (0.1.8)
Requirement already satisfied: protobuf>=3.8.0 in c:\programdata\anaconda3\lib\site-packages (from tensorflow) (3.11.1)
Requirement already satisfied: opt-einsum>=2.3.2 in c:\programdata\anaconda3\lib\site-packages (from tensorflow) (3.1.0)
Requirement already satisfied: astor>=0.6.0 in c:\programdata\anaconda3\lib\site-packages (from tensorflow) (0.8.1)
Requirement already satisfied: keras-preprocessing>=1.1.0 in c:\programdata\anaconda3\lib\site-packages (from tensorflow) (1.1.0)
Requirement already satisfied: h5py in c:\programdata\anaconda3\lib\site-packages (from keras-applications>=1.0.8->tensorflow) (2.10.0)
Requirement already satisfied: requests<3,>=2.21.0 in c:\programdata\anaconda3\lib\site-packages (from tensorboard<2.2.0,>=2.1.0->tensorflow) (2.22.0)
Requirement already satisfied: google-auth<2,>=1.6.3 in c:\programdata\anaconda3\lib\site-packages (from tensorboard<2.2.0,>=2.1.0->tensorflow) (1.9.0)
Requirement already satisfied: markdown>=2.6.8 in c:\programdata\anaconda3\lib\site-packages (from tensorboard<2.2.0,>=2.1.0->tensorflow) (3.2.1)
Requirement already satisfied: google-auth-oauthlib<0.5,>=0.4.1 in c:\programdata\anaconda3\lib\site-packages (from tensorboard<2.2.0,>=2.1.0->tensorflow) (0.4.1)
Requirement already satisfied: setuptools>=41.0.0 in c:\programdata\anaconda3\lib\site-packages (from tensorboard<2.2.0,>=2.1.0->tensorflow) (45.2.0.post20200210)
Requirement already satisfied: werkzeug>=0.11.15 in c:\programdata\anaconda3\lib\site-packages (from tensorboard<2.2.0,>=2.1.0->tensorflow) (1.0.0)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in c:\programdata\anaconda3\lib\site-packages (from requests<3,>=2.21.0->tensorboard<2.2.0,>=2.1.0->tensorflow) (1.25.8)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in c:\programdata\anaconda3\lib\site-packages (from requests<3,>=2.21.0->tensorboard<2.2.0,>=2.1.0->tensorflow) (3.0.4)
Requirement already satisfied: certifi>=2017.4.17 in c:\programdata\anaconda3\lib\site-packages (from requests<3,>=2.21.0->tensorboard<2.2.0,>=2.1.0->tensorflow) (2019.11.28)
Requirement already satisfied: idna<2.9,>=2.5 in c:\programdata\anaconda3\lib\site-packages (from requests<3,>=2.21.0->tensorboard<2.2.0,>=2.1.0->tensorflow) (2.8)
Requirement already satisfied: pyasn1-modules>=0.2.1 in c:\programdata\anaconda3\lib\site-packages (from google-auth<2,>=1.6.3->tensorboard<2.2.0,>=2.1.0->tensorflow) (0.2.7)
Requirement already satisfied: cachetools<3.2,>=2.0.0 in c:\programdata\anaconda3\lib\site-packages (from google-auth<2,>=1.6.3->tensorboard<2.2.0,>=2.1.0->tensorflow) (3.1.1)
Requirement already satisfied: rsa<4.1,>=3.1.4 in c:\programdata\anaconda3\lib\site-packages (from google-auth<2,>=1.6.3->tensorboard<2.2.0,>=2.1.0->tensorflow) (4.0)
Requirement already satisfied: requests-oauthlib>=0.7.0 in c:\programdata\anaconda3\lib\site-packages (from google-auth-oauthlib<0.5,>=0.4.1->tensorboard<2.2.0,>=2.1.0->tensorflow) (1.3.0)
Requirement already satisfied: pyasn1<0.5.0,>=0.4.6 in c:\programdata\anaconda3\lib\site-packages (from pyasn1-modules>=0.2.1->google-auth<2,>=1.6.3->tensorboard<2.2.0,>=2.1.0->tensorflow) (0.4.8)
Requirement already satisfied: oauthlib>=3.0.0 in c:\programdata\anaconda3\lib\site-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib<0.5,>=0.4.1->tensorboard<2.2.0,>=2.1.0->tensorflow) (3.1.0)
Installing collected packages: tensorflow
Successfully installed tensorflow-2.1.0

(base) C:\Windows\system32>python
Python 3.7.6 (default, Jan  8 2020, 20:23:39) [MSC v.1916 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow_core\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\ProgramData\Anaconda3\lib\imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "C:\ProgramData\Anaconda3\lib\imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\__init__.py", line 101, in <module>
    from tensorflow_core import *
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow_core\__init__.py", line 40, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\__init__.py", line 50, in __getattr__
    module = self._load()
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\__init__.py", line 44, in _load
    module = _importlib.import_module(self.__name__)
  File "C:\ProgramData\Anaconda3\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow_core\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow_core\python\pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow_core\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\ProgramData\Anaconda3\lib\imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "C:\ProgramData\Anaconda3\lib\imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: The specified module could not be found.

Failed to load the native TensorFlow runtime.

My System Configuration:
Acer Predator PHP315-51, Intel i5-8300H CPU @ 2.3GHz, 8gb RAM, Windows 10 64-bit, NVIDIA GeForce GTX 1050 Ti GPU.

**Comment by amahendrakar** [comment]
@abhinabasaha,

Could you please check [this](https://github.com/tensorflow/tensorflow/issues/36167#issuecomment-577886156) comment on a similar issue and let us know if it works? Thanks!

**Comment by abhinabasaha** [comment]
@amahendrakar thanks for your suggestion, and I have gone through those points earlier, but I have the MSVC 2019 redistributable installed, and my CPU/Python is on 64 bits, but I am not sure about "Your CPU does not support AVX2 instructions", and "There is a library that is in a different location/not installed on your system that cannot be loaded."

previuosly I tried to install tensorflow and keras and its subsequent packages by anaconda navigator, but the installation crashed everytime, then I tried to install it by conda, it got installed but the version was 1.x but not the latest 2.1, then tried with pip, it again got installed.

But now as I try to import it, The previous mentioned ( https://github.com/tensorflow/tensorflow/issues/37156#issue-572621424 ) error is shown.

I tried pip uninstall tensorflow, conda remove tensorflow, then reinstalled it 1st by conda, faced the same error, then installed with pip after removing the conda version, again faced the same error...!!

**Comment by abhinabasaha** [comment]
Solved the problem:

1. Uninstalled anaconda (manually had to delete some of its files from C:\Users\Programdata)
2. Reinstalled it.
3. Updated anaconda ( conda update anaconda) and anaconda navigator
4. I had previously installed cuda 10.2
4. Installed tensorflow (pip install tensorflow and pip install tensorflow-gpu)
5. Successfully imported tensorflow, but couldnot have gpu access, error 
       "Could not load dynamic library 'cudart64_101.dll'; dlerror: cudart64_101.dll not found "
6. Solved by following this instruction : https://stackoverflow.com/a/60024201

Now everything is set.
![image](https://user-images.githubusercontent.com/35966875/75848754-0d5aea00-5e09-11ea-90d9-4fcc8da3a9fb.png)
