### ISSUE TITLE
Saving and loading nested models fails

### ISSUE THREAD

**Issue by soyers** [tensorflow/tensorflow#37158]
**EDIT:** I adjusted the bug description the bug appears in a different place than I thought before.

**System information** 
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: -
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): unknown 2.1.0 (Installation from conda repository)
- Python version: 3.7.6
- Bazel version (if compiling from source): -
- GCC/Compiler version (if compiling from source): -
- CUDA/cuDNN version: -
- GPU model and memory: -

**Describe the current behavior**
I created a simple nested tensorflow.keras model with an input node and sequential model containing two convolutional layers:
```python
import tensorflow as tf
model_inside = tf.keras.models.Sequential([tf.keras.layers.Conv2D(16, 3, input_shape=(None,None,1)),
                                   tf.keras.layers.Conv2D(2, 1, activation='softmax')])

model_outside_input = tf.keras.Input(shape=(256, 256, 1))
model_outside = model_inside(model_outside_input)

model_outside = tf.keras.models.Model(inputs=model_outside_input, outputs=model_outside)
```
Saving this model to disk in SavedModel format and loading it again results in a `TypeError: list indices must be integers or slices, not NoneType`.
According to my observations this error only occurs with nested models.

**Describe the expected behavior**
I expect the loaded model to be exactly the same as before saving it and loading should not lead to an error.

**Standalone code to reproduce the issue** 
https://colab.research.google.com/drive/1Qu32g7WpH_mVtwEvRToueF_Q8SMNMlf3

**Comment by jvishnuvardhan** [comment]
@soyers I don't see any issue with `tf-nightly`. Please check the [gist here](https://colab.sandbox.google.com/gist/jvishnuvardhan/224c93836dc5265ad42d565b1897e528/tf-2-saving-nested-models-fails.ipynb). Thanks!

Please close the issue if the issue resolved for you. Thanks!

**Comment by jvishnuvardhan** [comment]
@soyers I ran your code as it is in `tf-nightly` and I don't see any issues. Recently, there were lot of improvements in saving the model. I think this issue was resolved by one of those recent changes. 

I am closing this issue as it was resolved. Feel free to reopen if this was not resolved for you. Thanks!
