### ISSUE TITLE
Problem with Himax HM01B0 camera on the Sparkfun Edge board

### ISSUE THREAD

**Issue by anferico** [tensorflow/tensorflow#37157]
@tensorflow/micro

**System information**
- Host OS Platform and Distribution: Linux Ubuntu 18.04
- TensorFlow installed from (source or binary): Cloned from source, but not installed
- TensorFlow version (commit SHA if source): 642708d2121976c8dbc0e8d0ae73fcf1cf027bd8
- Target platform: Sparkfun Edge

I'm trying to run an image classification model on a Sparkfun Edge, starting from the [person_detection](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/micro/examples/person_detection) example available in this repository. The logic for acquiring and resizing an image from the camera (Himax HM01B0) is included in `himax_driver/HM01B0_optimized.c`. For some reason, if I specify an image size greater than 102x102, the resulting image is padded with zeros in each of its four sides, yet the camera I'm using has a maximum pixel resolution of 320x320, as mentioned in the [official website](https://www.himax.com.tw/products/cmos-image-sensor/image-sensors/hm01b0/). 
Here's what I mean:

### 102x102 image:
![102x102](https://user-images.githubusercontent.com/30210403/75526152-86c19980-5a11-11ea-8bc6-47efdecaa7db.jpg)

### 320x320 image:
![320x320](https://user-images.githubusercontent.com/30210403/75526193-98a33c80-5a11-11ea-9b9f-171d4564e867.jpg)

**Please provide the exact sequence of commands/steps when you ran into the problem**
I simply passed `w=320`, `h=320` and `channels=1` to the function `hm01b0_blocking_read_oneframe_scaled` defined in `himax_driver/HM01B0_optimized.c`, printed each pixel value over the serial port and finally parsed such pixels with a Python script, displaying the resulting image.

**Comment by anferico** [comment]
Up

**Comment by suphoff** [comment]
While the sensor is 320x320 the selected output mode seems to be 320*240.
Additionally kStrideShift (used in hm01b0_blocking_read_oneframe_scaled) reduced the actually used pixels to 160/120 and causes underflow in offset_x and offset_y calculations.
Try setting kStrideShift to 0 and limit w to 320 and h to 240.

**Comment by anferico** [comment]
@suphoff Thanks, it worked! However, what do you mean that the selected output mode is 320*240? Is there anything I could do to change that to 320*320?

**Comment by suphoff** [comment]
@anferico : I believe you need to change the sHM01B0InitScript to get the desired resolution (link to camera manual with i2c register description should be on the sparkfun site)  and then adjust HM01B0_PIXEL_Y_NUM to the new Y resolution. Hope this helps - I did not like the camera SW/HW interface (no DMA) and never order it.

**Comment by mohantym** [comment]
Hi @anferico!
We are checking to see whether you still need help in this issue . Have you tried above [suggestion](https://github.com/tensorflow/tensorflow/issues/37157#issuecomment-640285359) yet? Please move this issue to [TF forum](https://discuss.tensorflow.org/) for further assistance. Thank you!
