### ISSUE TITLE
tensorflow has no attribute "assign_add"

### ISSUE THREAD

**Issue by aimanjavid** [tensorflow/tensorflow#37169]
i am using tensorflow-GPU 2.0.0 version . I caught a error that tensorflow has no attribute "assign_add". could anyone please help me please

**Comment by sixChar** [comment]
Try tf.compat.v1.assign_add

**Comment by ravikyram** [comment]
@aimanjavid 

Can you please go through the [link](https://www.tensorflow.org/api_docs/python/tf/compat/v1/assign_add) and see if it helps you. Thanks!

**Comment by aimanjavid** [comment]
thank you so much

**Comment by ravikyram** [comment]
@aimanjavid 

Please close this thread if it solves your question. Thanks!
