### ISSUE TITLE
TensorFlow 2.1.0 Not utilising GPU even though it can see it.  

### ISSUE THREAD

**Issue by georgeparry12** [tensorflow/tensorflow#37164]
TensorFlow does not utilise the GPU despite being able to see it. When I run a script, task manager does not show any activity on the GPU...

**Recently I have tried:**

Updated NVIDIA driver.

Uninstalled Tensorflow, python 3.7, cuDNN, CUDA, Visual Studio.

Installed Visual Studio.

Installed CUDA 10.1 [cuda_10.1.243_426.00_win10].

Installed cuDNN (and moved the .dll, .h, .lib files) [cudnn-10.1-windows10-x64-v7.6.5.32.zip]

Installed python [python-3.7.4-amd64.exe]

Installed Tensorflow (2.1.0) into a new environment and made a Kernel

**When I run ...**
import tensorflow as tf
tf.test.is_gpu_available(
    cuda_only=False, min_cuda_compute_capability=None
)
**… it returns** 
"true"

**when I run**
"from tensorflow.python.client import device_lib
print(device_lib.list_local_devices())"

**it returns**
 [name: "/device:CPU:0"
device_type: "CPU"
memory_limit: 268435456
locality {
}
incarnation: 3456819361691180826
, name: "/device:GPU:0"
device_type: "GPU"
memory_limit: 9105744200
locality {
  bus_id: 1
  links {
  }
}
incarnation: 18022178943584354069
physical_device_desc: "device: 0, name: GeForce RTX 2080 Ti, pci bus id: 0000:01:00.0, compute capability: 7.5"

However, when I run my script the task manager shows no activation on the GPU.

**Comment by ravikyram** [comment]
@georgeparry12 
Can you please follow the gpu usage guide [here](https://www.tensorflow.org/guide/gpu) and let us know whether it resolved your issue. Thanks!

**Comment by georgeparry12** [comment]
@ravikyram that link was useful, however, it's shown me I have a different problem. 

**When I run**
from __future__ import absolute_import, division, print_function, unicode_literals
import tensorflow as tf
print("Num GPUs Available: ", len(tf.config.experimental.list_physical_devices('GPU'))) 

**I get**
Num GPUs Available:  1

Despite the fact that TF show both under: 
"from tensorflow.python.client import device_lib
print(device_lib.list_local_devices())"

**Comment by ravikyram** [comment]
@georgeparry12 

Can you please go through the [link](https://www.tensorflow.org/guide/gpu#logging_device_placement) and see if it helps you.Please, add `tf.debugging.set_log_device_placement(True)` and execute piece of code as given in the link and verify.Thanks!

**Comment by ravikyram** [comment]
@georgeparry12 

Any update on this issue please. Thanks!

**Comment by ravikyram** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
