### ISSUE TITLE
[TF 2.1] BUG: set_seed with categorical in a conditional branch in graph mode.

### ISSUE THREAD

**Issue by SebastienKeroack** [tensorflow/tensorflow#37167]
**System information** 
- Have I written custom code (as opposed to using a stock
example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g.,
Linux Ubuntu 16.04): Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if
the issue happens on mobile device: 
- TensorFlow installed from (source or
binary): - TensorFlow version (use command below):  From source and binary using pip.
- Python version: - Bazel
version (if compiling from source): Python=3.6.9, Bazel=2.0.0
- GCC/Compiler version (if compiling from
source): 8.3.0
- CUDA/cuDNN version: - GPU model and memory:

**Describe the current behavior**
The example containing the bug always returns the first step in `tf.function` with `tf.cond` if we define a seed with `tf.random.set_seed`.
A= tf.Tensor([0 0 0 0 0 0 0 0 0 0 0 0], shape=(12,), dtype=int64)

**Describe the expected behavior**
A= tf.Tensor([0 1 1 0 0 1 1 1 1 0 1 1], shape=(12,), dtype=int64)
A= tf.Tensor([0 0 0 0 0 0 1 1 0 1 1 0], shape=(12,), dtype=int64)
...

**Standalone code to reproduce the issue** 
Bug sample:
```
import tensorflow as tf

tf.random.set_seed(0)

def f1():
    return(tf.random.categorical(tf.math.log([[0.5, 0.5]]), 1))

@tf.function
def body():
    Y = []
    for t in range(12):
        Y.append(
            tf.cond(tf.constant(True),
                    f1,
                    f1)
        )
    return(tf.squeeze(Y))

A = body()

print("A=", A)
# A= tf.Tensor([0 0 0 0 0 0 0 0 0 0 0 0], shape=(12,), dtype=int64)
```

1. Working sample:
```
import tensorflow as tf

def f1():
    return(tf.random.categorical(tf.math.log([[0.5, 0.5]]), 1))

@tf.function
def body():
    Y = []
    for t in range(12):
        Y.append(
            tf.cond(tf.constant(True),
                    f1,
                    f1)
        )
    return(tf.squeeze(Y))

A = body()

print("A=", A)
# A= tf.Tensor([0 1 1 0 0 1 1 1 1 0 1 1], shape=(12,), dtype=int64)
```

2. Working sample:
```
import tensorflow as tf

tf.random.set_seed(0)

def f1():
    return(tf.random.categorical(tf.math.log([[0.5, 0.5]]), 1))

@tf.function
def body():
    Y = []
    for t in range(12):
        ret_0 = f1()
        ret_1 = f1()
        
        Y.append(
            tf.cond(tf.constant(True),
                    lambda: ret_0,
                    lambda: ret_1)
        )
    return(tf.squeeze(Y))

A = body()

print("A=", A)
# A= tf.Tensor([0 0 0 0 0 0 1 1 0 1 1 0], shape=(12,), dtype=int64)
```

**Comment by gadagashwini** [comment]
I could replicate the issue with Tf 2.1.
Please find the gist [here](https://colab.sandbox.google.com/gist/gadagashwini/13114a2582e4e947b9baf7bea25d9358/untitled.ipynb). Thanks!

**Comment by gowthamkpr** [comment]
@SebastienKeroack Can you elaborate more in a detailed manner as I am having a hard time to understand what you are trying to convey. Thanks!

**Comment by SebastienKeroack** [comment]
The example containing the bug should work logically as example number 2. No?

**Comment by wangpengmit** [comment]
It's actually intended behavior. When set_seed has been called and f1 is traced, it picks an op seed (an attribute) for the random.categorical op. When f1 is called multiple times in `body` with tf.cond, f1 is inlined and the  random.categorical op is duplicated, all with the same op_seed attribute. So they'll give you the same random number.

In contrast, in Working Sample 2, although f1 is also called multiple times, it's not inlined and duplicated. Instead, it's just eagerly called many times during the tracing of `body`, leaving multiple random.categorical ops on the graph, and the eager context picks different op_seed attributes for them.

When set_seed is not called, as in Working Sample 1, the random.categorical ops get value (0,0) for their (graph_seed, op_seed) attributes, which is a special value telling the kernel to non-deterministically pick a seed at runtime.

This again shows how broken the old RNGs (and any stateful kernels) are.
