### ISSUE TITLE
Latest GPUDelegate from 'org.tensorflow:tensorflow-lite-gpu:0.0.0-nightly' crashes

### ISSUE THREAD

**Issue by bilalsoomro** [tensorflow/tensorflow#37161]
**System information** 
- Have I written custom code (as opposed to using a stock
example script provided in TensorFlow):  No
- OS Platform and Distribution (e.g.,
Linux Ubuntu 16.04): 
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if
the issue happens on mobile device: All devices
- TensorFlow installed from (source or
binary): binary
- TensorFlow version (use command below):  'org.tensorflow:tensorflow-lite-gpu:0.0.0-nightly'
- Python version: - Bazel
version (if compiling from source):
- GCC/Compiler version (if compiling from
source): 
- CUDA/cuDNN version: - GPU model and memory:

**Describe the current behavior**
Android app crashes when using GPUDelegate from the latest nightly build.

**Describe the expected behavior**
It shouldn't crash.

**Standalone code to reproduce the issue** 
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.
```
Process: com.test.app, PID: 16875
    java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "_ZTVN6tflite3gpu2cl12SpaceToDepthE" referenced by "/data/app/com.test.app-ujX5oxWg44XmBTPZMarXvQ==/base.apk!/lib/arm64-v8a/libtensorflowlite_gpu_jni.so"...
        at java.lang.Runtime.loadLibrary0(Runtime.java:1071)
        at java.lang.Runtime.loadLibrary0(Runtime.java:1007)
        at java.lang.System.loadLibrary(System.java:1667)
```

**Comment by freedomtan** [comment]
This should be addressed by https://github.com/tensorflow/tensorflow/pull/37033.

**Comment by gadagashwini** [comment]
@bilalsoomro, Can we close this issue, Since the associated PR has been merged. Thanks!

**Comment by bilalsoomro** [comment]
@gadagashwini Yep, thanks!
