### ISSUE TITLE
`encode_png` function should be exported from `tf.io` module

### ISSUE THREAD

**Issue by vijayphoenix** [tensorflow/tensorflow#37168]
## URL(s) with the issue:
https://www.tensorflow.org/api_docs/python/tf/image/encode_png

## Description of the issue (what needs changing):

Currently, all Image decoding and encoding functions are a part of the `tf.io` module but `encode_png` function is still a part of the `tf.image` module.

## Changes required

Change `tf.image.encode_png`  to `tf.io.encode_png`

### Submit a pull request?
I will be happy to help.

**Comment by Artistic18** [comment]
I want to work on this. Can you please guide me?
