### ISSUE TITLE
Seq2Seq - Place different LSTM layers on separate GPUs

### ISSUE THREAD

**Issue by siabar** [tensorflow/tensorflow#3716]
Dears 

Based on the discussion on https://github.com/tensorflow/tensorflow/issues/600, I would like to place different LSTM layers on separate GPUs to improve the accuracy and speed. 
Can someone help me?

With Best Wishes,
Siamak

**Comment by girving** [comment]
Please ask questions about how to use TensorFlow on StackOverflow, not as Github issues.
