### ISSUE TITLE
Why tensorflow creates gru/while in graph?

### ISSUE THREAD

**Issue by bzhong2** [tensorflow/tensorflow#37170]
I am trying to compute the flop of a GRU model for one step. I understand all results but not the gru/while. Why TensorFlow need to create gru/while in the graph doubling the computations? I also asked this question in StackOverflow (https://stackoverflow.com/questions/60453735/what-tensorflow-keras-will-create-gru-while-in-graph) but have not got any answer yet.

**Comment by gowthamkpr** [comment]
@bzhong2 We will try to answer this on stackovrflow itself. I am closing this issue for now as github is only meant for build/install, bug/performance, feature request or docs related issues. Thanks!
