### ISSUE TITLE
tf2.0 when use large input dims in tf.keras.layers.Embedding layer under eager mode, it turns to be very slow

### ISSUE THREAD

**Issue by nnnnwang** [tensorflow/tensorflow#37181]
<em>Please make sure that this is an issue related to performance of TensorFlow.
As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:performance_template</em>

**System information** 
- Have I written custom code (as opposed to using a stock
example script provided in TensorFlow):  yes
- OS Platform and Distribution (e.g.,
Linux Ubuntu 16.04):  centos7
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if
the issue happens on mobile device: 
- TensorFlow installed from (source or
binary): - TensorFlow version (use command below):  2.0.0
- Python version: - Bazel 
version (if compiling from source): 3.6.8
- GCC/Compiler version (if compiling from
source):  
- CUDA/cuDNN version: - GPU model and memory: CUDA10.0 tesla v100 16G

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
i set the input dims be 10,000,000 when I use tf.keras.layers.Embedding. Under the eager mode(default), mode.fit() is very slow. But when i disable the eager mode, the speed turns to be normal.
**Describe the expected behavior**
it should be no difference if i enable eager mode or not.
**Standalone code to reproduce the issue** 
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.
```
test_input = tf.ones((1000, 1), dtype=tf.int64)
label = tf.ones((1000, 1))
m_input = Input(shape=(1,))
dense = Embedding(5000000, 16,name='embed')(m_input)
dense = Dense(10)(dense)
dense = Dense(5)(dense)
output = Dense(1,'sigmoid')(Flatten()(dense))
model = Model(inputs=[m_input], outputs=[output])
model.compile("adam", loss='binary_crossentropy')
model.fit(test_input, label, steps_per_epoch=1000, epochs=1)
```
**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

```
when use eager mode, time cost is as follow

1/1000 [..............................] - ETA: 29:49 - loss: 0.7492
2/1000 [..............................] - ETA: 25:54 - loss: 0.7430
3/1000 [..............................] - ETA: 24:58 - loss: 0.7368
4/1000 [..............................] - ETA: 24:21 - loss: 0.7307

disable the eager mode using tf.compat.v1.disable_eager_execution()


 706/1000 [====================>.........] - ETA: 0s - loss: 0.0520
 765/1000 [=====================>........] - ETA: 0s - loss: 0.0484
 819/1000 [=======================>......] - ETA: 0s - loss: 0.0455
 870/1000 [=========================>....] - ETA: 0s - loss: 0.0430
 926/1000 [==========================>...] - ETA: 0s - loss: 0.0406
 984/1000 [============================>.] - ETA: 0s - loss: 0.0384
1000/1000 [==============================] - 2s 2ms/step - loss: 0.0379

```

**Comment by nnnnwang** [comment]
anyone can helps?

**Comment by amahendrakar** [comment]
Was able to reproduce the issue, noticed significant time difference with eager mode [enabled](https://colab.sandbox.google.com/gist/amahendrakar/c3d6a26fda1dd7ea937cf35b1b853292/37181.ipynb) and [disabled](https://colab.sandbox.google.com/gist/amahendrakar/b94900e29ea7509d41d4222f7a80e15d/37181-w-o-eager.ipynb). Got similar results with TF-nightly too. Please find the attached gist. Thanks!

**Comment by tanzhenyu** [comment]
@nnnnwang There has been quite some updates in 2.2 for eager performance, would you mind re-trying on the latest version and see if the issue goes away?

**Comment by rmothukuru** [comment]
I have executed your code in **`Tensorflow Version 2.5`** and could see not much difference in the **`performance`**, between [Eager](https://colab.research.google.com/gist/rmothukuru/c7e69db93fb36254a3c105baed596220/37181.ipynb) and [non-Eager](https://colab.research.google.com/gist/rmothukuru/9069bb355bf55e9db6b77fef08c48c58/37181-w-o-eager.ipynb) Execution.  Thanks!
