### ISSUE TITLE
tf.keras.callbacks.TensorBoard  type profiling support for straight Tensorflow

### ISSUE THREAD

**Issue by whatdhack** [tensorflow/tensorflow#37180]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using): 1.15
- Are you willing to contribute it (Yes/No):
No sure.

**Describe the feature and the current behavior/state.**

tf.keras.callbacks.TensorBoard has a nice and simple way to  do profiling and  throwing the result up on Tensorboard.  It would be great to have that easy feature also for plain TF (sess.run).  

In addition, I think  the following enhancements will be very useful. 
1.  Ability to aggregate a number of traces.
2.  Backport the range of batch ( instead of just one batch ) from 2.x to 1.5 ?
3.  Linking the  time line traces with graph in both direction, from profile to graph and vice-versa.
4.  The Op names in the graph and profile should exactly match. Currently they are not exactly same ( e.g. out_0/MatMul:_MklMatMul vs out_0/MatMul/(MatMul) ).
5. There seems to be a number of different ways to profile straight TF and Keras. The following are what I am able to  find (so far, not sure if there are more).  Clear, concise and comprehensive documentation will be good.
           - tf.RunOptions(trace_level=tf.RunOptions.FULL_TRACE) and tf.compat.v1.summary.FileWriter.add_run_metadata() .  Seems to be graph annotations and does not seem to capture Keras  backprop part.
           -  tf.RunOptions(trace_level=tf.RunOptions.FULL_TRACE) and timeline.Timeline() - seems to work with both TF and Keras. However generates  JSON and hence does not get displayed by Tensorbaord. 
           - tf.keras.callbacks.TensorBoard() - only works with Keras and captures only one batch out off all in the epoch. 

**Will this change the current api? How?**
N/A

**Who will benefit with this feature?**
Every user. 
**Any Other info.**

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.
