### ISSUE TITLE
Could not find any TF GPUs when I use trt_convert

### ISSUE THREAD

**Issue by kimchicanh** [tensorflow/tensorflow#37182]
I use:
OS: 16.04
cuda: 10.2
cudnn: 7
python:3.6
tensorflow-gpu:2.1
GPU: Titan V - 12GB
I convert model tensorflow to tensorRT:
`from tensorflow.python.compiler.tensorrt import trt_convert as trt`
`input_saved_model_dir = "./model_tensor/"`
`output_saved_model_dir = "./model_tensor_rt/"`
`converter = trt.TrtGraphConverterV2(input_saved_model_dir=input_saved_model_dir)`
`converter.convert()`
`converter.save(output_saved_model_dir)`

I still can inference model on tensorflow:
However I cannot convert to tensorRT: 

2020-02-29 17:19:35.901924: E tensorflow/compiler/tf2tensorrt/convert/convert_graph.cc:102]Could not find any TF GPUs

2020-02-29 17:19:35.901927: W tensorflow/compiler/tf2tensorrt/convert/convert_graph.cc:726] Can't identify the cuda device. Running on device 0 

2020-02-29 17:19:35.901958: I tensorflow/compiler/tf2tensorrt/convert/convert_graph.cc:737] Replaced segment 5 consisting of 4 nodes by 
StatefulPartitionedCall/X/Y/TRTEngineOp_5.

Thanks

**Comment by ravikyram** [comment]
@kimchicanh 

Can you please go through the [link](https://www.tensorflow.org/api_docs/python/tf/experimental/tensorrt/Converter) and see if it helps you. If it does not solve your issue, please share the simple standalone code with supporting files to
reproduce the issue in our environment. It helps us in localizing the issue faster. Thanks!

**Comment by kimchicanh** [comment]
@ravikyram Thanks you. I try your link but it still fail. I send you my model yolo tiny v3 and log file
[https://drive.google.com/drive/folders/1xR5FziDC4m8Lv-eTiNXUNvegOKmBhu_r?usp=sharing](url)

Thanks

**Comment by ravikyram** [comment]
@kimchicanh 

Will it be possible for you to check with CUDA 10.1 and see still you are facing the issue? Thanks!

**Comment by kimchicanh** [comment]
@ravikyram thanks, I just change to 10.1, and there are new log file, [link](https://drive.google.com/drive/folders/1xR5FziDC4m8Lv-eTiNXUNvegOKmBhu_r?usp=sharing)

**Comment by kimchicanh** [comment]
@ravikyram @ymodak Hi, Are there any solution???

**Comment by Saduf2019** [comment]
@kimchicanh 
Is this still an issue in the latest tf version as many bugs have been solved could you please confirm.
