### ISSUE TITLE
Remote monitoring of DL models

### ISSUE THREAD

**Issue by CleanPegasus** [tensorflow/tensorflow#37183]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using): 2.1.0
- Are you willing to contribute it (Yes/No): Yes

**Describe the feature and the current behavior/state.**
An app or a website that lets you remotely monitor your deep learning model's metrics. It can also notify you when your model has completed training or has crashed. I have worked on this before and I wish it could come inbuilt with Tensorflow. You can check out that project [here](https://github.com/CleanPegasus/TensorDash). 

**Will this change the current api? How?**
There will be a few miscellaneous codes added to the tensorflow library.

**Who will benefit with this feature?**
This will benefit the researchers who are training huge models. This will save them a lot of time.

**Any Other info.**

**Comment by CleanPegasus** [comment]
I would like to work on it as a G-SOC project.

**Comment by martinwicke** [comment]
How is this different from TensorBoard?

**Comment by CleanPegasus** [comment]
Tensorboar does lets you monitor your model through a remote server. It is quite complicated and mot many can afford a remote server. My friend and I worked on an app that makes it easy for remote monitoring and notifies you when your model has completed or crashed.
<br>
Something like this
![sample](https://user-images.githubusercontent.com/42714467/75746995-d2da4a00-5d41-11ea-9326-e8f0da37102b.jpeg)

It'll be easy for people to use this compared to a remote server since they get all the details in an app.

**Comment by martinwicke** [comment]
Great! It seems you have created all you need. What is this issue about?

**Comment by CleanPegasus** [comment]
I'm hoping to add this to tensorboard as my G-soc project. Is it possible?

**Comment by martinwicke** [comment]
You should file an issue at tensorflow/tensorboard.

Since you already have this up and running, it's not entirely clear to me
what "adding it to TensorBoard" would entail. But you can clarify there.

**Comment by CleanPegasus** [comment]
Thank you!
