### ISSUE TITLE
Default type for complex sparse tensor is complex128

### ISSUE THREAD

**Issue by zaccharieramzi** [tensorflow/tensorflow#37199]
**System information** 
- Have I written custom code (as opposed to using a stock
example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g.,
Linux Ubuntu 16.04): Linux Ubuntu 16.04
- TensorFlow installed from (source or
binary): - TensorFlow version (use command below): pip

**Describe the current behavior**
When I instantiate a complex sparse tensor, the default type is complex128, whereas with a float sparse tensor it is float32.

**Describe the expected behavior**
The default type for complex sparse tensor should probably be complex64, since we can't set the type in the tensor creation.

**Standalone code to reproduce the issue** 
```
a = tf.sparse.SparseTensor(indices=[[0, 0],], values=[1.+ 0j], dense_shape=[2, 2])
print(a.dtype)
```
This gives `tf.complex128`.

**Other info / logs** 
This can be circumvented using `numpy` to fix the type of the values but it isn't ideal imho.

**Comment by ravikyram** [comment]
@zaccharieramzi 
The default datatype for complex sparse tensor is `complex128` ,If you need to change complex data type you can typecast to other datatype and use it. For  Float  `dtype = float32` is default and for complex `dtype = complex128` is default Please, find the gist [here](https://colab.sandbox.google.com/gist/ravikyram/82d7e1aa86981ffb81d1a928a957e711/untitled694.ipynb). Thanks!

**Comment by zaccharieramzi** [comment]
Yes of course, there are many ways to circumvent this issue.
What I am saying is that it is an unexpected behaviour (in one case you have a double in the other not), and in that regard it should probably be changed.

**Comment by saxenasaurabh** [comment]
This is consistent with the behavior in numpy:

```
>>> np.array([1.+ 0j]).dtype
dtype('complex128')
```
