### ISSUE TITLE
Cant run exe file from convert tensorflow to exe

### ISSUE THREAD

**Issue by TOPMANZA** [tensorflow/tensorflow#37194]
i have problem for run exe file it been after i deploy script to exe i got application file and run it i got this message in command  i try many things try with command try with auto-py-to-exe it dont solve

![75507237-1b78c700-5a13-11ea-8705-92635f011c90](https://user-images.githubusercontent.com/49858640/75612200-f2ac1b00-5b53-11ea-981e-27aebdbddd33.png)

this time die T-T
Please help me
i use: Python 3.6.9 :: Anaconda, Inc
   tensorflow-gpu==1.9.0
   PyInstaller==4.0.dev0+a1f92c6a08
   Eel==0.11.0

**Comment by Hfusi0n** [comment]
That's a pyinstaller issue, not a tensorflow one...

**Comment by amahendrakar** [comment]
@TOPMANZA,
Could you please check @Hfusi0n's comment and let us know if it works? Thanks!

**Comment by TOPMANZA** [comment]
sorry i'm late and sorry for tag 
look like i have problem like https://github.com/pyinstaller/pyinstaller/issues/3709 
i cant find how to resolve this issue
last comment he tell OS changes right?

**Comment by amahendrakar** [comment]
@TOPMANZA,
Sorry for the delayed response. 

According to the [comment](https://github.com/pyinstaller/pyinstaller/issues/3709#issuecomment-593185502) you mentioned, the build platform should be greater than the running platform.
Eg. If you have built the exe file on Windows 7, you can run it on Windows 7 and above.

**Comment by Hfusi0n** [comment]
> @TOPMANZA,
> Sorry for the delayed response.
> 
> According to the [comment](https://github.com/pyinstaller/pyinstaller/issues/3709#issuecomment-593185502) you mentioned, the build platform should be greater than the running platform.
> Eg. If you have built the exe file on Windows 7, you can run it on Windows 7 and above.

Quoting Legorooj comment... 
You can try and use the hooks created in the PR from my comment. See if using those hook files can resolve your issues. 

> @Overdrivr win8>win7 will work; windows is the same platform. The other way round may not due to underlying OS changes.

**Comment by amahendrakar** [comment]
@TOPMANZA, 
Any updates regarding this issue? Thanks!

**Comment by amahendrakar** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
