### ISSUE TITLE
example_trainer c++ improvements

### ISSUE THREAD

**Issue by hartsantler** [tensorflow/tensorflow#372]
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/cc/tutorials/example_trainer.cc

First of all, why only one c++ tutorial?
Next, it would be nice to have a README in that folder that gives at least the bazel command to compile it, or at least a note at the top of the source code how to compile it.

`example_trainer.cc` shows off how to use multiple threads, but i would rather start with a single threaded version for a simple helloworld tutorial.

lines 43-46 ugly macros `TF_DEFINE_int32`, ... when i first saw this it is not clear why this is even required, or how it is used later on.

lines 155-159 the ugly macro injects `FLAGS_` prefix
`opts.num_concurrent_steps = tensorflow::example::FLAGS_num_concurrent_steps;`
the option settings could be just simple hard coded literals, there is no need to complicate the hello world with macro magic.

**Comment by vrv** [comment]
That tutorial isn't really a hello world example to begin with -- it is specifically to show multi-threaded training.  We don't have a C++ hello world example that's buildable, so maybe we'll add one soon.

**Comment by hartsantler** [comment]
while it remains the only example in the tutorials folder, it is the hello world by default.
it would have been better to have a proper hello world first, and then this multi-threaded example.

**Comment by suiyuan2009** [comment]
I'd like to implement some c++ example.

**Comment by girving** [comment]
@suiyuan2009 Unfortunately the C++ API hasn't stabilized yet, so I think we should still hold off on this one.

**Comment by aselle** [comment]
Closing due to lack of recent activity. Thanks!
