### ISSUE TITLE
android mask rcnn

### ISSUE THREAD

**Issue by hoangtubatu123** [tensorflow/tensorflow#37204]
Please provide the code get output mask r-cnn on android. Thanks

**Comment by gadagashwini** [comment]
@hoangtubatu123, Please take a look at [Tensorflow lite doc](https://www.tensorflow.org/lite/models/segmentation/overview). Thanks!

**Comment by gadagashwini** [comment]
@hoangtubatu123, Did you get a chance to go through the above given . Thanks

**Comment by gadagashwini** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Comment by pnarne16** [comment]
Can anybody provide a reference to implementing a custom mask rcnn model in Java?

Thanks in advance
