### ISSUE TITLE
No module named 'tensorflow.python.tools' in Visual Studio 2017 v15.9.20

### ISSUE THREAD

**Issue by ehennis** [tensorflow/tensorflow#37207]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information** 
- Have I written custom code (as opposed to using a stock
example script provided in TensorFlow):  No.
- OS Platform and Distribution (e.g.,
Linux Ubuntu 16.04): Windows 10 Pro
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if
the issue happens on mobile device: 
- TensorFlow installed from (source or
binary): Installed from pip
- TensorFlow version (use command below): v2.1.0-rc2-17-ge5bf8de410 2.1.0
- Python version: 3.7.4
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
Within Visual Studio 2017 I am unable to run a python file if I have 'import tensorflow as tf' in the code. If I run [python -c "import tensorflow as tf; print(tf.__version__);" it works
**Describe the expected behavior**
I should be able to run the file
**Standalone code to reproduce the issue** 
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.
Just have a .py file with "import tensorflow as tf" and run from within Visual Studio with the python package installed

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

I have python Visual Studio extension version 15.9.18254.1 installed

#34722 is very close to this issue. In that ticket they had a poorly named file. Not sure what VS is doing. This is most likely something within VS but not sure. Maybe an import?

#9778 mentions a Windows error but it is quite a few years old

**Comment by ehennis** [comment]
#36441 is also similar but the user just switched computers at work and solved his issue.

**Comment by ehennis** [comment]
Running the same file from the command line works just fine. It must have something to do with how visual studio is running the file.

**Comment by gadagashwini** [comment]
@ehennis Try running on any of the Python IDLE like Jupyter or spyder. Let us know how it progresses. Thanks

**Comment by ehennis** [comment]
I spun up a Juypter notebook and it ran without issues.

**Comment by gadagashwini** [comment]
@ehennis, Looks like running inside Visual studio 2017 missing some Tensorflow dependencies or it might installed outside the environment. 
Are you happy to close this issue. Thanks!

**Comment by ehennis** [comment]
I would rather not close it since I still can't use it within Visual Studio. Another odd thing is that even if I call it through a StartProcess class within Visual Studio it doesn't work. There must be something with VS running that is messing with paths and whatnot.

Is there anything else I can try and help debug it? If I can get some time (3 year old daughter is a bit much) I want to create a virtual environment and try that. I am not hopeful because I have tried different Anaconda environments and get the same errors.

**Comment by gadagashwini** [comment]
@ehennis, Try the following instructions to install Tensorflow in virtual environmnet.

```
#Install tensorflow using pip virtual env 
pip install virtualenv
virtualenv tf_2.1   # tf_2.1 is virtual env name
source tf_2.1/bin/activate
tf_2.1 $ pip install tensorflow==2.1
tf_2.1 $ python
>>import tensorflow as tf
>>tf.__version__
2.1.0
```

**Comment by gadagashwini** [comment]
@ehennis, is this still an issue?

**Comment by ehennis** [comment]
Sorry for the delay. My day job got crazy. Anyway, after creating the virtual environment and use that python.exe I was able to get my code working in Visual Studio.

Does that mean my normal install is back or is this just something with virtualenv?
