### ISSUE TITLE
Print out the user number in Tensorflow

### ISSUE THREAD

**Issue by ccu1tn** [tensorflow/tensorflow#37202]
Dear everyone; 

when users increase. I want to print out that user number and how to value the performance of Tensorflow?

Please give me some of your idea!
Many thank!

**Comment by amahendrakar** [comment]
@ccu1tn,
Can you elaborate your issue with code snippet or any use case. Thanks!

**Comment by amahendrakar** [comment]
Any updates regarding this issue? Thanks!

**Comment by amahendrakar** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
