### ISSUE TITLE
iOS Object Detection with Custom .tflite file: "Failed to allocate memory for input tensors."

### ISSUE THREAD

**Issue by MHX792** [tensorflow/tensorflow#37206]
I am trying to run the sample iOS with a custom .tflite file ([download](https://github.com/tensorflow/tensorflow/files/4271813/custom_tflite_file.zip)) where only one object exists.

When the app loads, it crashes with the error `Failed to create the interpreter with error: Failed to allocate memory for input tensors.`.

Here is a comparison of both .tflite files (left: original, right: custom): 
<img width="982" alt="attributes" src="https://user-images.githubusercontent.com/12123471/75626712-3477a880-5bca-11ea-9d23-a2d3c34029dd.png">

As shown in the image, input tensors exist. What is the reason for this error?

**Comment by yyoon** [comment]
Hi @MHX792. Which sample app were you trying to run? Can you provide a way to reproduce the error?
