### ISSUE TITLE
Official tutorial (Text classification with an RNN )code running error !!!

### ISSUE THREAD

**Issue by AITutorials** [tensorflow/tensorflow#37219]
In the official text tutorial of tensorflow: Text classification with an RNN (https://tensorflow.google.cn/tutorials/text/text_classification_rnn),
```
train_dataset = train_dataset.padded_batch(BATCH_SIZE)
test_dataset = test_dataset.padded_batch(BATCH_SIZE)
```
When I run the code there is an error:
```
    train_dataset = train_dataset.padded_batch(BATCH_SIZE)
TypeError: padded_batch() missing 1 required positional argument: 'padded_shapes'
```

My tensorflow version: 2.1.0rc2
My python version: 3.7

What should be the correct answer？

**Comment by amahendrakar** [comment]
@AITutorials,
I was able to run the code from the above tutorial without any issues. Please find the gist of it [here](https://colab.sandbox.google.com/gist/amahendrakar/1e109000a7657b71ed170b9862f381f6/37219.ipynb). Thanks!

**Comment by amahendrakar** [comment]
Any updates regarding this issue? Thanks!

**Comment by amahendrakar** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Comment by PratsBhatt** [comment]
You need tensorflow version 2.2.0 to make the code work. 
Since 2.2.0, the padded_shapes argument is not mandatory.

You can see a start marked note here https://tensorflow.google.cn/tutorials/text/text_classification_rnn

**Comment by mathslingo** [comment]
I have the same problem today.
