### ISSUE TITLE
Implement support for AV1 / AVIF for image files

### ISSUE THREAD

**Issue by Daniel451** [tensorflow/tensorflow#37217]
**System information**
- TensorFlow version (you are using): 2.1
- Are you willing to contribute it (Yes/No): Yes; but I have very limited time & have little experience with implementing codecs, thus I could only assist in testing.

**Describe the feature and the current behavior/state.**
In image processing there are scenarios, especially when you deal with higher resolution images, where compression artifacts actually deteriorates your model training sessions. This specifically applies to old image formats like GIF or JPEG. Storing data in, for example, BMP format however drastically increases disk space usage.

I propose the implementation of **AV1 / AVIF for image files**, i.e. adding AVIF format to `tf.io.decode_image`. **AVIF** is a **free, open source format**.

AV1 (see [AV1 wikipedia page](https://en.wikipedia.org/wiki/AV1)) is a next generation video (and image) codec. It is broadly supported by Google, Amazon, Apple, ARM, Cisco, Facebook, IBM, Intel Corporation, Microsoft, Mozilla, Netflix, Nvidia, Samsung Electronics, and others since AV1 is developed and supported by [AOMedia](https://en.wikipedia.org/wiki/Alliance_for_Open_Media), where these and other corporations are contributing to.

AOMedia's main goal is developing royalty-free video and image formats. Hence, long-term support can be expected. 

AVIF (see [AVIF wikipedia entry](https://en.wikipedia.org/wiki/AV1#AV1_Image_File_Format_(AVIF))) is the image file format of the AV1 codec. It has major benefits compared to older formats like JPEG or PNG -> lower file size while still maintaining a significantly better quality.

This [blog post by netflix](https://netflixtechblog.com/avif-for-next-generation-image-coding-b1d75675fe4) demonstrates that AVIF covers little to zero compression artifacts **and** having a lower file size compared to JPEG.

See AVIF defintion: https://aomediacodec.github.io/av1-avif/

**Will this change the current api? How?**
No, just an addition.

**Who will benefit with this feature?**
Everyone interested in image processing. Lower disk usage **and** little to zero compression artifacts benefit everyone in image processing, especially users with an interest for higher resolutions.

**Comment by novomesk** [comment]
I recommend to use https://github.com/AOMediaCodec/libavif
I use libavif in my software to open/save images in AVIF format.

**Comment by Daniel451** [comment]
@novomesk yes, I also already implemented some solutions with AOMedia's libavif repo.

However, TensorFlow should integrate this directly. If you bypass tf.dataset by loading the data yourself, you loose performance (and, in case you do not "re-invent the wheel" and implement buffering / pre-loading yourself, you will be limited to datasets that completely fit into your memory).

**Comment by yongtang** [comment]
@Daniel451 The AV1/AVIF image format falls into the scope of [tensorflow/io](https://github.com/tensorflow/io) which consists of images formats beyond default png/jpeg/gif. So AV1/AVIF is more suited in [tensorflow/io](https://github.com/tensorflow/io) package.

I have created an issue https://github.com/tensorflow/io/issues/882 there to track the progress.

**Comment by Daniel451** [comment]
@yongtang thanks! :)
