### ISSUE TITLE
TFLite Micro: SUB Op Support

### ISSUE THREAD

**Issue by iotwithit** [tensorflow/tensorflow#37215]
@tensorflow/micro

**System information**
- Host OS Platform and Distribution: Linux 5.5.5 Arch
- TensorFlow installed from: source
- Tensorflow version: 41c6bf7c6215bea9bfb9bf0a9b63f2084e6f3058
- Target platform: OpenMV CAM (STM32H7)

**Describe the problem**

Hello, I trained a simple dogs/cats classification model through transfer learning and then converted it to be run on the [OpenMV CAM](https://openmv.io/): [converted_model.mv1025128.tflite.zip](https://github.com/tensorflow/tensorflow/files/4272695/converted_model.mv1025128.tflite.zip).

It fails to load on the MCU inside the `InitializeRuntimeTensor` function when the SUB tensor is processed (you can see on [netron](https://lutzroeder.github.io/netron/) where SUB is needed).

I found out the SUB op is not supported on tf lite micro, but, since I am quite new to ML, I would like to know if there is a specific reason to this missing support, if it can be *easily* added or if you can suggest a workaround.

Thank you

**Comment by freddan80** [comment]
Hi,
There's a PR: https://github.com/tensorflow/tensorflow/pull/34894 by @giuseros, @njeffrie , I think it covers your need?
Cheers!
Fredrik

**Comment by iotwithit** [comment]
Thank you, it's definitely good to know!
One thing I noticed though is that the problem arises while the SUB tensor is initialized as if the model file is not parsed properly. I do not know if there is an issue with the FlatBuffer generated schema, but what I see is that the `flatbuffer_tensor.shape()` (`tensorflow/lite/micro/memory_helpers.cc:82`) call returns a NULL pointer when the SUB tensor is processed.
Should I open a different issue?

**Comment by freddan80** [comment]
@giuseros , do you have input on this?

**Comment by rmothukuru** [comment]
@iotwithit,
Sorry for the delayed response. **`SUB Operation`** seems to be added for [TF Lite Micro](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/micro/all_ops_resolver.cc). Can you please confirm the same so that we can close this issue? Thanks!
