### ISSUE TITLE
The DLL error in importing tensorflow.

### ISSUE THREAD

**Issue by Venus24kk** [tensorflow/tensorflow#37221]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- TensorFlow installed from (source or binary): tensorflow pypi
- TensorFlow version: 2.0.0
- Python version: 3.6.8 with updated pip==20.0.2
- Installed using: pip in virtualenv
- CUDA/cuDNN version: CUDA V10.0.130, cuDNN 7.4.1
- GPU model and memory: GeForce GTX 1660

**Describe the problem**
I got this error when importing TensorFlow.
ImportError: DLL load failed: A dynamic link library (DLL) initialization routine failed.

NVIDIA driver version is 432.00. I install CUDA 10 and configured cudnn 7.4.1. Also, installed Visual Studio 2017 buildtools. I tried to install from tf-1.12 to tf-2.0, all versions were failed. I checked previous issues about this error, but some guys resolved using conda. If so, couldn't I use pip installer with tensorflow?

**Comment by Venus24kk** [comment]
Hello,

Do you have any solution?

**Comment by Saduf2019** [comment]
@Venus24kk 
Just to verify did you follow the instructions to install from pip using [Tensorflow website](https://www.tensorflow.org/install/pip).Thanks

**Comment by Venus24kk** [comment]
Thank you for your message. I found my CPU doesn't support AVX instruction. When I install tensorflow-gpu, does it matter if CPU supports AVX instruction?

Regards,

**Comment by Saduf2019** [comment]
@Venus24kk 
Yes while you do pip install from windows,it does matter.

**Comment by mihaimaruseac** [comment]
Closing as duplicate.

https://github.com/tensorflow/tensorflow/issues/36167#issuecomment-577886156

#36167 #36151 #36138 #36054 #36045 #36020 #36003 #35988 #35903 #35880 #35865 #35805 #35789 #35773 #35772 #35767 #35766 #35749 #35721 #35618 #35204
