### ISSUE TITLE
inconsistent default parameters for adagrad optimizer

### ISSUE THREAD

**Issue by chstem** [tensorflow/tensorflow#37229]
**System information** 
TensorFlow 2.1.0 (tested on anaconda package and docker image)

**Describe the current behavior**

The default value for the `initial_accumulator_value` parameter of the Adagrad optimizer is different depending on whether it is passed as a string or as an instance of the optimizer class. This may lead to drastic differences in learning behavior, which is not apparent from the code.

**Describe the expected behavior**

Both variants should use the same default parameters. 

**Standalone code to reproduce the issue** 

```
import tensorflow as tf

model = tf.keras.models.Model()
model.compile(optimizer='adagrad')
model.optimizer.get_config()
# {'name': 'Adagrad', 'learning_rate': 0.001, 'decay': 0.0, 'initial_accumulator_value': 0.0, 'epsilon': 1e-07}

tf.keras.optimizers.Adagrad().get_config()
# {'name': 'Adagrad', 'learning_rate': 0.001, 'decay': 0.0, 'initial_accumulator_value': 0.1, 'epsilon': 1e-07}

```

**Comment by ravikyram** [comment]
I have tried on colab with TF version 2.1.0, 2.2.0-dev20200302  and was able to reproduce the issue.Please,find the gist [here](https://colab.sandbox.google.com/gist/ravikyram/9a5b708a520ef1b30feeabcd9fc6023a/untitled698.ipynb). Thanks!

**Comment by tanzhenyu** [comment]
This is fixed [here](https://github.com/tensorflow/tensorflow/commit/a90a1a863e250f607e1eb7118a99218b22e627cd)
