### ISSUE TITLE
RaggedTensor are converted to Tensors inside exported signature. 

### ISSUE THREAD

**Issue by stefanondisponibile** [tensorflow/tensorflow#37226]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): `no`
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): `Ubuntu 18.04`
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: `no`
- TensorFlow installed from (source or binary): `no`
- TensorFlow version (use command below): `2.0.1`
- Python version: `3.7.3`
- Bazel version (if compiling from source): `-`
- GCC/Compiler version (if compiling from source): `-`
- CUDA/cuDNN version: `-`
- GPU model and memory: `-`

**Describe the current behavior**
As [properly documented](https://www.tensorflow.org/api_docs/python/tf/function#args_2), it is currently possible to pass a possibly nested sequence of [`tf.TensorSpec`](https://www.tensorflow.org/api_docs/python/tf/TensorSpec) objects as a `tf.function` `input_signature` argument.

However, if one attempts to pass a `tf.RaggedTensorSpec` inside an `input_signature` sequence, everything still works, but the `RaggedTensorSpec` gets converted in its "dense" `values` + `row_splits` form.
 
**Describe the expected behavior**
I would expect that if one specifies a `tf.RaggedTensorSpec` element inside the `input_signature` sequence it should either be exported as a `tf.RaggedTensorSpec`, or raise an error.

Of course the firs option sounds more desiderable, since it's pretty common to have ragged input sequences. In this case `tf.RaggedTensorSpec` would be also lacking of a `name` argument, but this is easier to solve.

**Standalone code to reproduce the issue** 
[Colab Notebook](https://colab.research.google.com/drive/1mEXNfmIiEU9XNL7niKCC_LRccfW5ZDob)

```python
import tensorflow as tf

class SomeModule(tf.Module):

  @tf.function(input_signature=[
    tf.RaggedTensorSpec(shape=[None, None], dtype=tf.string)
  ])
  def return_ragged_inputs(self, inputs: tf.RaggedTensor):
    return inputs

ragged_inputs = tf.ragged.constant([["foo"], ["bar"], ["foo", "bar"]], dtype=tf.string)

some_module = SomeModule()
return_ragged_inputs_result = some_module.return_ragged_inputs(ragged_inputs)
print(f"ragged_inputs => {ragged_inputs}\n")
print("We can use the method with ragged inputs:")
print(f"return_ragged_inputs => {return_ragged_inputs_result}\n")
print("Saving some_module...")
tf.saved_model.save(some_module, export_dir="foobar")
some_module = tf.saved_model.load("foobar")
print(f"\nWe can pass and return ragged inputs even by saving and reloading the module, if we use it 'eagerly':")
print(some_module.return_ragged_inputs(ragged_inputs))
print("\nBut the graph signature tell us that our exported signature expects tf.Tensor values instead:")
exported_model_graph_inputs = some_module.signatures[tf.saved_model.DEFAULT_SERVING_SIGNATURE_DEF_KEY].inputs
exported_model_graph_outputs = some_module.signatures[tf.saved_model.DEFAULT_SERVING_SIGNATURE_DEF_KEY].outputs
print(f"Expected inputs  : {exported_model_graph_inputs}")
print(f"Expected outputs : {exported_model_graph_outputs}")
print("\nThis means we couldn't use the method as we would expect in (e.g.) TensorFlow Serving.")
```

**Other info / logs**
This issue follows up #37049 , as suggested by @gowthamkpr .

**Comment by gowthamkpr** [comment]
Was able to reproduce this error. Please find the gist [here](https://colab.sandbox.google.com/gist/gowthamkpr/7f902cdbefb2cf8788475dc76ac086cc/untitled32.ipynb).

**Comment by mdanatg** [comment]
I believe this is due to `RaggedTensor` not being a first-class type inside GraphDef - internally, it is represented as a [CompositeTensor](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/framework/composite_tensor.py#L31), which in turn is lowered to a list of `Tensor`, by `tf.nest.flatten(expand_composites=True)` when the function is compiled.

When loading a saved model, that lowering becomes visible.

As a workaround, you should be able to build inputs compatible with the loaded model by flattening the ragged tensor: `tf.nest.flatten(ragged_inputs, expand_composites=True)`.

I think we can eventually handle them correctly inside SavedModel, by placing the necessary type spec into the graph metadata and reconstructing it upon import, but I'll let @k-w-w and @edloper give more expert insights.

Nit: in the colab, did you mean the last two lines to be "exported", not "expected"?

**Comment by gowthamkpr** [comment]
So, @stefanondisponibile is expecting it to be a ragged tensor but its not the case as seen in the gist.

**Comment by stefanondisponibile** [comment]
@gowthamkpr yes, for what I've seen so far, and as explained by @mdanatg this difference between Ragged and normal Tensors pops up when the function gets converted to a Graph. I can't do it in Colab, but if you tried to load that servable with tf serving you would see you would have to pass two different dense Tensors in place of the Ragged Tensor.

@mdanatg thanks for the explanation! I am currently working around this by actually passing two dense Tensors at inference time, one with the values and the other with the splits, and building them up inside the function itself via tf.RaggedTensor.from_row_splits. So those last two lines were as "expected", since I was expecting to pass RaggedTensors to the served model, but I end up passing dense ones, building the RaggedTensor inside the function.

**Comment by edloper** [comment]
Loaded model `signatures` currently flatten any structured input into a flat list of tensors.  This is true for RaggedTensor, but also for nested structure, such as a dictionary of tensors.  E.g., if we define a module whose function takes and returns a dict of tensors, then the model signature inputs & outputs are currently flat lists of tensors:

```
class SomeModule(tf.Module):

  @tf.function(input_signature=[{'foo': tf.TensorSpec(None, tf.int32),
                                 'bar': tf.TensorSpec(None, tf.string)}
  ])
  def return_dict(self, inputs):
    return inputs

some_module = SomeModule()
tf.saved_model.save(some_module, export_dir="foobar2")
some_module = tf.saved_model.load("foobar2")
print(some_module.signatures[tf.saved_model.DEFAULT_SERVING_SIGNATURE_DEF_KEY].inputs)
# prints: [<tf.Tensor 'inputs:0' shape=<unknown> dtype=string>, <tf.Tensor 'inputs_1:0' shape=<unknown> dtype=int32>]
print( some_module.signatures[tf.saved_model.DEFAULT_SERVING_SIGNATURE_DEF_KEY].outputs)
# prints: [<tf.Tensor 'Identity:0' shape=<unknown> dtype=string>, <tf.Tensor 'Identity_1:0' shape=<unknown> dtype=int32>]
```

Hopefully we can improve on this, but the problem is a general issue with any structured inputs & outputs, and is not specific to ragged tensors.

**Comment by Saduf2019** [comment]
@stefanondisponibile
Please let us know if this is still an issue.

**Comment by stefanondisponibile** [comment]
Hey @Saduf2019 , sorry for not having replied yet! I would say that _yes_, this still is an issue, but as @edloper kindly explained is not specific to ragged tensors, moreover there are workarounds/better-ways for tackling this, so I'll close this specific issue. Thanks for you help!

**Comment by shlomi-schwartz** [comment]
I'm having a similar issue, my model input is a RaggedTensor (1000, None, None) connected to an LSTM layer. 
The model is working as expected and when calling predict I get the predictions.
```
input = tf.ragged.constant([[
                            [-0.9984272718429565, -0.9422321319580078, -0.27657580375671387, -3.185823678970337, -0.6360141634941101, -1.6579184532165527, -1.9000954627990723, -0.49169546365737915, -0.6758883595466614, -0.6677696704864502, -0.532067060470581], 
                            [-0.9984272718429565, -0.9421600103378296, 2.2048349380493164, -1.273996114730835, -0.6360141634941101, -1.5917999744415283, 0.6147914528846741, -0.49169546365737915, -0.6673409938812256, -0.6583622694015503, -0.5273991227149963], 
                            [-0.9984272718429565, -0.942145586013794, 2.48842453956604, -1.6836735010147095, -0.6360141634941101, -1.5785763263702393, -1.900200605392456, -0.49169546365737915, -0.6656315326690674, -0.6583622694015503, -0.5273991227149963]
]])
model.predict(input)

array([[0.5138151 , 0.3277698 , 0.26122513]], dtype=float32)
```
When saving the model the input is split into `args_0`and `args_0_1`.


```
MetaGraphDef with tag-set: 'serve' contains the following SignatureDefs:

signature_def['__saved_model_init_op']:
  The given SavedModel SignatureDef contains the following input(s):
  The given SavedModel SignatureDef contains the following output(s):
    outputs['__saved_model_init_op'] tensor_info:
        dtype: DT_INVALID
        shape: unknown_rank
        name: NoOp
  Method name is: 

signature_def['serving_default']:
  The given SavedModel SignatureDef contains the following input(s):
    inputs['args_0'] tensor_info:
        dtype: DT_FLOAT
        shape: (-1, 11)
        name: serving_default_args_0:0
    inputs['args_0_1'] tensor_info:
        dtype: DT_INT64
        shape: (-1)
        name: serving_default_args_0_1:0
  The given SavedModel SignatureDef contains the following output(s):
    outputs['dense_2'] tensor_info:
        dtype: DT_FLOAT
        shape: (-1, 3)
        name: StatefulPartitionedCall:0
  Method name is: tensorflow/serving/predict
WARNING: Logging before flag parsing goes to stderr.
W0124 13:38:49.266864 139946102503296 deprecation.py:506] From /usr/local/lib/python2.7/dist-packages/tensorflow_core/python/ops/resource_variable_ops.py:1786: calling __init__ (from tensorflow.python.ops.resource_variable_ops) with constraint is deprecated and will be removed in a future version.
Instructions for updating:
If using Keras pass *_constraint arguments to layers.

Defined Functions:
  Function Name: '__call__'
    Option #1
      Callable with:
        Argument #1
          DType: RaggedTensorSpec
          Value: RaggedTensorSpec(TensorShape([None, None, 11]), tf.float32, 1, tf.int64)
        Argument #2
          DType: bool
          Value: True
        Argument #3
          DType: NoneType
          Value: None
    Option #2
      Callable with:
        Argument #1
          DType: RaggedTensorSpec
          Value: RaggedTensorSpec(TensorShape([None, None, 11]), tf.float32, 1, tf.int64)
        Argument #2
          DType: bool
          Value: False
        Argument #3
          DType: NoneType
          Value: None

  Function Name: '_default_save_signature'
    Option #1
      Callable with:
        Argument #1
          DType: RaggedTensorSpec
          Value: RaggedTensorSpec(TensorShape([None, None, 11]), tf.float32, 1, tf.int64)

  Function Name: 'call_and_return_all_conditional_losses'
    Option #1
      Callable with:
        Argument #1
          DType: RaggedTensorSpec
          Value: RaggedTensorSpec(TensorShape([None, None, 11]), tf.float32, 1, tf.int64)
        Argument #2
          DType: bool
          Value: True
        Argument #3
          DType: NoneType
          Value: None
    Option #2
      Callable with:
        Argument #1
          DType: RaggedTensorSpec
          Value: RaggedTensorSpec(TensorShape([None, None, 11]), tf.float32, 1, tf.int64)
        Argument #2
          DType: bool
          Value: False
        Argument #3
          DType: NoneType
          Value: None
```
 I tried to use `tf.nest.flatten` as follows:


```
input = tf.ragged.constant([[
                            [-0.9984272718429565, -0.9422321319580078, -0.27657580375671387, -3.185823678970337, -0.6360141634941101, -1.6579184532165527, -1.9000954627990723, -0.49169546365737915, -0.6758883595466614, -0.6677696704864502, -0.532067060470581], 
                            [-0.9984272718429565, -0.9421600103378296, 2.2048349380493164, -1.273996114730835, -0.6360141634941101, -1.5917999744415283, 0.6147914528846741, -0.49169546365737915, -0.6673409938812256, -0.6583622694015503, -0.5273991227149963], 
                            [-0.9984272718429565, -0.942145586013794, 2.48842453956604, -1.6836735010147095, -0.6360141634941101, -1.5785763263702393, -1.900200605392456, -0.49169546365737915, -0.6656315326690674, -0.6583622694015503, -0.5273991227149963]
]])

inputs = tf.nest.flatten(input, expand_composites=True)
```


and got a list of 3 tensors:

```
[<tf.Tensor: shape=(33,), dtype=float32, numpy=
 array([-0.9984273 , -0.94223213, -0.2765758 , -3.1858237 , -0.63601416,
        -1.6579185 , -1.9000955 , -0.49169546, -0.67588836, -0.6677697 ,
        -0.53206706, -0.9984273 , -0.94216   ,  2.204835  , -1.2739961 ,
        -0.63601416, -1.5918    ,  0.61479145, -0.49169546, -0.667341  ,
        -0.65836227, -0.5273991 , -0.9984273 , -0.9421456 ,  2.4884245 ,
        -1.6836735 , -0.63601416, -1.5785763 , -1.9002006 , -0.49169546,
        -0.66563153, -0.65836227, -0.5273991 ], dtype=float32)>,
 <tf.Tensor: shape=(2,), dtype=int64, numpy=array([0, 3])>,
 <tf.Tensor: shape=(4,), dtype=int64, numpy=array([ 0, 11, 22, 33])>]
```

I tried calling tensorflow serving like so:
```
import json
import requests
headers = {"content-type": "application/json"}
data = json.dumps({"instances":[
                                  {
                                      "args_0":np.array(inputs[0]).tolist(),
                                      "args_0_1":np.array(inputs[2]).tolist()
                                  }
                               ]
                   })      

json_response = requests.post('http://localhost:8501/v1/models/fashion_model:predict', data=data, headers=headers)
predictions = json.loads(json_response.text)
```

But got the following error:
`{'error': 'Matrix size-incompatible: In[0]: [0,33], In[1]: [11,64]\n\t [[{{node sequential_1/first_lstm/lstm_cell/MatMul}}]]'}
`

What am I missing?
