### ISSUE TITLE
Build TF 1.8 from source on Windows not working

### ISSUE THREAD

**Issue by FB43** [tensorflow/tensorflow#37231]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 8.1 64
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): 1.8
- TensorFlow version: 1.8
- Python version: 3.6
- Installed using virtualenv? pip? conda?: pip & conda
- Bazel version (if compiling from source): 2.1.0
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 9.0 7.1
- GPU model and memory: NVIDIA GeForce GTX 760 compting capabilities 3.0 that's the reason why...

**Describe the problem** Hello, I've followed the instructions on this page: https://www.tensorflow.org/install/source_windows#gpu
And when I enter bazel build --config=v1 //tensorflow/tools/pip_package:build_pip_package

the result is: 
PS P:\anaconda3\tensorflow>
PS P:\anaconda3\tensorflow> bazel build --config=v1 //tensorflow/tools/pip_package:build_pip_package
WARNING: The following rc files are no longer being read, please transfer their contents or import their path into one o
f the standard rc files:
p:\anaconda3\tensorflow/tools/bazel.rc
WARNING: Ignoring JAVA_HOME, because it must point to a JDK, not a JRE.
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=0 --terminal_columns=120
INFO: Options provided by the client:
  'build' options: --python_path=p:/Anaconda3/python.exe
INFO: Reading rc options for 'build' from p:\anaconda3\tensorflow\bazel.rc:
  'build' options: --define framework_shared_object=true --define=use_fast_cpp_protos=true --define=allow_oversize_proto
s=true --define=grpc_no_ares=true --spawn_strategy=standalone --genrule_strategy=standalone -c opt
INFO: Reading rc options for 'build' from p:\anaconda3\tensorflow\.tf_configure.bazelrc:
  'build' options: --action_env PYTHON_BIN_PATH=p:/Anaconda3/python.exe --action_env PYTHON_LIB_PATH=p:/Anaconda3/lib/si
te-packages --force_python=py3 --host_force_python=py3 --python_path=p:/Anaconda3/python.exe --define with_xla_support=t
rue --define with_gdr_support=true --define with_verbs_support=true --action_env TF_NEED_OPENCL_SYCL=0 --action_env TF_N
EED_CUDA=1 --action_env CUDA_TOOLKIT_PATH=C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v9.1 --action_env TF_CUDA_V
ERSION=9.1 --action_env CUDNN_INSTALL_PATH=C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v9.1 --action_env TF_CUDNN
_VERSION=7 --action_env TF_CUDA_COMPUTE_CAPABILITIES=3.0 --action_env TF_CUDA_CLANG=0 --action_env CUDA_PATH=C:/Program
Files/NVIDIA GPU Computing Toolkit/CUDA/v9.1 --action_env CUDA_COMPUTE_CAPABILITIE=None --action_env NO_WHOLE_ARCHIVE_OP
TION=1 --config=win-cuda --define grpc_no_ares=true --copt=-DGEMMLOWP_ALLOW_SLOW_SCALAR_FALLBACK --host_copt=-DGEMMLOWP_
ALLOW_SLOW_SCALAR_FALLBACK --config monolithic --copt=-w --host_copt=-w --verbose_failures
INFO: Found applicable config definition build:win-cuda in file p:\anaconda3\tensorflow\bazel.rc: --define=using_cuda=tr
ue --define=using_cuda_nvcc=true
INFO: Found applicable config definition build:monolithic in file p:\anaconda3\tensorflow\bazel.rc: --define framework_s
hared_object=false
ERROR: Config value v1 is not defined in any .rc file
PS P:\anaconda3\tensorflow>

**Provide the exact sequence of commands / steps that you executed before running into the problem** bazel build --config=v1 //tensorflow/tools/pip_package:build_pip_package

Thanks for your help!
Best regards,
François

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by FB43** [comment]
@amahendrakar Hello, I've not read this doc enough, my bazel version was wrong. Now, I have the 0.10.0rc. Things are different but not better ...
Thanks for your help!
PS P:\anaconda3\tensorflow> bazel build --config=v1 //tensorflow/tools/pip_package:build_pip_package
WARNING: Config values are not defined in any .rc file: v1
Loading:
Loading: 0 packages loaded
ERROR: Skipping '//tensorflow/tools/pip_package:build_pip_package': error loading package 'tensorflow/tools/pip_package'
: Encountered error while reading extension file 'cuda/build_defs.bzl': no such package '@local_config_cuda//cuda': Trac
eback (most recent call last):
        File "P:/anaconda3/tensorflow/third_party/gpus/cuda_configure.bzl", line 1142
                _create_local_cuda_repository(repository_ctx)
        File "P:/anaconda3/tensorflow/third_party/gpus/cuda_configure.bzl", line 995, in _create_local_cuda_repository
                _get_cuda_config(repository_ctx)
        File "P:/anaconda3/tensorflow/third_party/gpus/cuda_configure.bzl", line 747, in _get_cuda_config
                _cuda_toolkit_path(repository_ctx)
        File "P:/anaconda3/tensorflow/third_party/gpus/cuda_configure.bzl", line 282, in _cuda_toolkit_path
                repository_ctx.path(cuda_toolkit_path).exists
Illegal char <:> at index 90: C:/users/francois/appdata/local/temp/_bazel_francois/wkog3ss7/external/local_config_cuda/C
:Program FilesNVIDIA GPU Computing ToolkitCUDAv9.0
WARNING: Target pattern parsing failed.
ERROR: error loading package 'tensorflow/tools/pip_package': Encountered error while reading extension file 'cuda/build_
defs.bzl': no such package '@local_config_cuda//cuda': Traceback (most recent call last):
        File "P:/anaconda3/tensorflow/third_party/gpus/cuda_configure.bzl", line 1142
                _create_local_cuda_repository(repository_ctx)
        File "P:/anaconda3/tensorflow/third_party/gpus/cuda_configure.bzl", line 995, in _create_local_cuda_repository
                _get_cuda_config(repository_ctx)
        File "P:/anaconda3/tensorflow/third_party/gpus/cuda_configure.bzl", line 747, in _get_cuda_config
                _cuda_toolkit_path(repository_ctx)
        File "P:/anaconda3/tensorflow/third_party/gpus/cuda_configure.bzl", line 282, in _cuda_toolkit_path
                repository_ctx.path(cuda_toolkit_path).exists
Illegal char <:> at index 90: C:/users/francois/appdata/local/temp/_bazel_francois/wkog3ss7/external/local_config_cuda/C
:Program FilesNVIDIA GPU Computing ToolkitCUDAv9.0
INFO: Elapsed time: 0,476s
FAILED: Build did NOT complete successfully (0 packages loaded)
PS P:\anaconda3\tensorflow> bazel version
Build label: 0.10.0rc1
Build target: bazel-out/x64_windows-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Sat Jun 5 11:32:18 +50010 (1516009433538)
Build timestamp: 1516009433538
Build timestamp as int: 1516009433538
PS P:\anaconda3\tensorflow>

**Comment by Saduf2019** [comment]
@FB43 
As per the configurations, please refer to [this link](https://www.tensorflow.org/install/source_windows#gpu) which shows you would have to use cmake instead of bazel, is here any specific reason to use 1.8, could you use a later version of tensorflow.

For your second error:
Could you please refer to [this link](https://stackoverflow.com/questions/45425199/bazel-build-error-with-tensorflow) and let us know if it helps.

**Comment by FB43** [comment]
@Saduf2019 hello, sorry, when I was working I often missed those things as many people. Now, I'm retired but nothing changes!
So, I have Python 3.6, Bazel 0.10.0, MSVC 2015 update 3 (2014), Cmake v3.6.3, GCC 4.8, MSYS2, Chocolatey, Anaconda3 (where I want to build TF). And other things, of course.
The reason why I want to install TF 1.8 is that my GPU has 3.0 computing capabilities.
I need it to run some functions of the Visions of Chaos software (free and interesting).
If an other version could run (or be recompiled) for 3.0, I'll take it, I just want the better version for my GPU (not the moment for changing it...).
Now, I have the tools, but I'm lost.
What to do now?
If you can help me a little bit more, it will be much appreciated.
Thanks for all.
Best regards,
François

**Comment by FB43** [comment]
@Saduf2019 Hello, I opened a new issue to get some advices for changing my GPU. I think the results would be better.
Thanks for all.
François

**Comment by Saduf2019** [comment]
@FB43 
Please confirm if we may move this issue to resolved, as the GPU change is monitored and this would be a duplicate issue.
