### ISSUE TITLE
Docs say that sigmoid is mapped to TfLite but the TfLite schema doesn't mention sigmoid

### ISSUE THREAD

**Issue by yurivict** [tensorflow/tensorflow#37238]
It lists ```tf.sigmoid``` as mappable to TfLite here: https://www.tensorflow.org/lite/guide/ops_compatibility

But the TfLite schema doesn't mention sigmoid: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/schema/schema.fbs

**Comment by karimnosseir** [comment]
It is referenced as Logistic in the schema
