### ISSUE TITLE
Blas GEMM launch failed

### ISSUE THREAD

**Issue by chris0914** [tensorflow/tensorflow#37233]
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04
- TensorFlow installed from (source or binary): source and pip
- TensorFlow version: 2.1.0
- Python version: 3.7.3
- Installed using virtualenv? pip? conda?: conda
- Bazel version (if compiling from source): 0.29.1
- GCC/Compiler version (if compiling from source): 7.4.0
- CUDA/cuDNN version: 10.1 / 7.6.4
- GPU model and memory: GTX 1080

On my setup any installation using CUDA 10.1 results in the given error:

    tensorflow.python.framework.errors_impl.InternalError:  Blas GEMM launch failed

I have the same installation on my own computer with a 2080ti, which runs just fine. Also using tensorflow-gpu==2.0.0 works fine. As some mentioned in stackoverflow  (https://stackoverflow.com/questions/58428466/tensorflow-blas-gemm-launch-failed-a-shape-2-128-b-shape-128-44-m-2-n) I just compiled from source with 10.0 and everything runs fine, too. Any ideas on how to compile with 10.1 and TF2.1?

Might be related to #36781

Reproducible with:

    import tensorflow as tf
    print(tf.matmul([[1., 2.],[3., 4.]], [[1., 2.],[3., 4.]]))

Thanks in advance!

**Comment by jelmd** [comment]
Check `apt-cache policy libcublas10`. Don't use 10.2.2.89-1 - it is not compatible!  So fix could be:
```
apt-get purge libcublas10 libcublas-dev
apt-get install libcublas10=10.2.1.243-1 libcublas-dev=10.2.1.243-1 cuda-libraries-10-1 cuda-libraries-dev-10-1
```
If you did not have installed the cuda-libraries-[dev-]10-1 meta packages, omit them.

**Comment by chris0914** [comment]
Thanks @jelmd, this resolves the issue!

**Comment by steermomo** [comment]
> Check `apt-cache policy libcublas10`. Don't use 10.2.2.89-1 - it is not compatible! So fix could be:
> 
> ```
> apt-get purge libcublas10 libcublas-dev
> apt-get install libcublas10=10.2.1.243-1 libcublas-dev=10.2.1.243-1 cuda-libraries-10-1 cuda-libraries-dev-10-1
> ```
> 
> If you did not have installed the cuda-libraries-[dev-]10-1 meta packages, omit them.

Thanks a lot, It works!!!😄
