### ISSUE TITLE
_pywrap_tensorflow module not found on OS X 10.11.6 after compiling and building a package

### ISSUE THREAD

**Issue by ojss** [tensorflow/tensorflow#3723]
I compiled tensorflow from the source with CUDA support. After installing the wheel I was greeted with an error(listed below). The compilation without CUDA support is successful.

I cant figure out what the problem is.

**All of this was done in a Virtualenv Python version: 2.7.12**
### Environment info

Operating System:
Mac OS X(10.11.6)
Installed version of CUDA and cuDNN: 
`-rwxr-xr-x  1 root  wheel   8.1K Jun 10 01:58 /usr/local/cuda/lib/libcuda.dylib*
lrwxr-xr-x  1 root  wheel    45B Sep 25  2015 /usr/local/cuda/lib/libcudadevrt.a@ -> /Developer/NVIDIA/CUDA-7.5/lib/libcudadevrt.a
lrwxr-xr-x  1 root  wheel    50B Sep 25  2015 /usr/local/cuda/lib/libcudart.7.5.dylib@ -> /Developer/NVIDIA/CUDA-7.5/lib/libcudart.7.5.dylib
lrwxr-xr-x  1 root  wheel    46B Sep 25  2015 /usr/local/cuda/lib/libcudart.dylib@ -> /Developer/NVIDIA/CUDA-7.5/lib/libcudart.dylib
lrwxr-xr-x  1 root  wheel    49B Sep 25  2015 /usr/local/cuda/lib/libcudart_static.a@ -> /Developer/NVIDIA/CUDA-7.5/lib/libcudart_static.a
lrwxr-xr-x  1 root  wheel    47B Aug  9 21:51 /usr/local/cuda/lib/libcudnn.5.dylib@ -> /Developer/NVIDIA/CUDA-7.5/lib/libcudnn.5.dylib
lrwxr-xr-x  1 root  wheel    45B Aug  9 21:51 /usr/local/cuda/lib/libcudnn.dylib@ -> /Developer/NVIDIA/CUDA-7.5/lib/libcudnn.dylib
lrwxr-xr-x  1 root  wheel    48B Aug  9 21:51 /usr/local/cuda/lib/libcudnn_static.a@ -> /Developer/NVIDIA/CUDA-7.5/lib/libcudnn_static.a`

If installed from source, provide 
1. 32bd3d024f33e920a67a1081bc0ae0048350fdee
2. The output of `bazel version`:
   `Build label: 0.3.1-homebrew
   Build target: bazel-out/local-fastbuild/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
   Build time: Thu Aug 4 09:58:27 2016 (1470304707)
   Build timestamp: 1470304707
   Build timestamp as int: 1470304707`
### Steps to reproduce
1. Configure with CUDA v7.5 and Cudnn v5.1 
2. Compile with CUDA support enabled.
3. Build pip package and then install.
### What have you tried?
1. Tried installing the binary, but I was then greeted with a different error. 
### Logs or other output that would be helpful

`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/ojas/.pyenv/versions/ve2/lib/python2.7/site-packages/tensorflow/__init__.py", line 23, in <module>
    from tensorflow.python import *
  File "/Users/ojas/.pyenv/versions/ve2/lib/python2.7/site-packages/tensorflow/python/__init__.py", line 48, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/Users/ojas/.pyenv/versions/ve2/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 21, in <module>
    _pywrap_tensorflow = swig_import_helper()
  File "/Users/ojas/.pyenv/versions/ve2/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 20, in swig_import_helper
    return importlib.import_module('_pywrap_tensorflow')
  File "/Users/ojas/.pyenv/versions/2.7.12/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named _pywrap_tensorflow`

**Comment by ashvsdata** [comment]
Can you try in a different shell? I hit this error when I am using bash. But, with fish shell I get a SEGMENTATION FAULT on Python

**Comment by ojss** [comment]
Tried that. Still the same error.

Another thing I did was installed the TF binary with GPU support. Tried importing in a different shell(fish).
Got this error:
`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/ojas/.pyenv/versions/ve2/lib/python2.7/site-packages/tensorflow/__init__.py", line 23, in <module>
    from tensorflow.python import *
  File "/Users/ojas/.pyenv/versions/ve2/lib/python2.7/site-packages/tensorflow/python/__init__.py", line 48, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/Users/ojas/.pyenv/versions/ve2/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 28, in <module>
    _pywrap_tensorflow = swig_import_helper()
  File "/Users/ojas/.pyenv/versions/ve2/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow', fp, pathname, description)
ImportError: dlopen(/Users/ojas/.pyenv/versions/ve2/lib/python2.7/site-packages/tensorflow/python/_pywrap_tensorflow.so, 10): Library not loaded: @rpath/libcudart.7.5.dylib
  Referenced from: /Users/ojas/.pyenv/versions/ve2/lib/python2.7/site-packages/tensorflow/python/_pywrap_tensorflow.so
  Reason: image not found`
Ojas Shirekar
+91 9820644375

**Comment by yaroslavvb** [comment]
The `libcudart.7.5.dylib not found` error happens when you don't set `DYLD_LIBRARY_PATH` correctly

**Comment by ojss** [comment]
I have set that correctly.
Verified by running deviceQuery, unless thats not the point of deviceQuery.

**Comment by yaroslavvb** [comment]
OK, I've actually had this same issue before, and it was fixed by disabling System Integrity Protection, here's the thread for some debugging tips -- https://github.com/tensorflow/tensorflow/pull/2557#issuecomment-224155895

**Comment by yaroslavvb** [comment]
You could run it under `sudo dtruss` to see where it's trying to look for the `dylib`. Also, I've had to disable SIP (system integrity protection) for it to work, although that had extra `dyld: warning` messages in error log

**Comment by ojss** [comment]
I shall try disabling SIP soon.
here is the exports:
`export CUDA_HOME=/usr/local/cuda
export DYLD_LIBRARY_PATH="$DYLD_LIBRARY_PATH:$CUDA_HOME/lib:/Developer/NVIDIA/CUDA-7.5/lib"
export DYLD_LIBRARY_PATH="$CUDA_HOME/lib:$DYLD_LIBRARY_PATH"
export PATH="$CUDA_HOME/bin:$PATH"
`

**Comment by ojss** [comment]
Okay I did what you said @yaroslavvb. Disabled SIP, now I get this:
`import tensorflow
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcublas.7.5.dylib locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcudnn.5.dylib locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcufft.7.5.dylib locally
Segmentation fault: 11`

**Comment by yaroslavvb** [comment]
Can you get a stack trace?
You should have a crash report file created in a file like below during
crash

~/Library/Logs/DiagnosticReports/Python_2016-07-21-144526_Yaroslavs-MacBook-Pro.crash
(Also viewable under User Diagnostic reports in Console App)


Also you get a stack trace for crashing script.py on Mac by running under
lldb, ie

lldb python
(lldb) r script.py
....
(lldb) up
...
(lldb) up

Optionally compile with "bazel build -c dbg --config=cuda" to get actual
line numbers in stack trace

**Comment by rieram** [comment]
Have you tried importing _pywrap_tensorflow.so in python directly? That will give you a good demarcation point between what could be the problem. It often gives you a better description of the problem.

**Comment by lxcid** [comment]
I did have the same issue. I believe this is cause by DYLD_LIBRARY_PATH not working in OS X El Capitan due to SIP.

https://github.com/oracle/node-oracledb/issues/231

I'm looking to workaround though.

**Comment by ojss** [comment]
@lxcid I disabled SIP now atleast the library loads and segfaults :/
@yaroslavvb here is the trace from lldb
`'(lldb) r test.py
Process 2728 launched: '/Users/ojas/.pyenv/versions/ve2/bin/python' (x86_64)
Process 2728 stopped
* thread #1: tid = 0x47b7, 0x0000000100009000 dyld`_dyld_start, stop reason = exec
    frame #0: 0x0000000100009000 dyld`_dyld_start
dyld`_dyld_start:
->  0x100009000 <+0>: popq   %rdi
    0x100009001 <+1>: pushq  $0x0
    0x100009003 <+3>: movq   %rsp, %rbp
    0x100009006 <+6>: andq   $-0x10, %rsp
(lldb) up
`

@yaroslavvb I will try recompiling it with your options soon.

**Comment by the13fools** [comment]
Woooo!  Thanks for this help everyone.

@ojss So I got to the same place as you.  The final thing I needed to do to do in order to get things working is to create a symbolic link: ln -sf /usr/local/cuda/lib/libcuda.dylib /usr/local/cuda/lib/libcuda.1.dylib

As referenced at the very bottom of the documentation: https://www.tensorflow.org/versions/r0.11/get_started/os_setup.html.

@yaroslavvb It would be nice to add a hint suggesting that SIP might need to be disabled to the documentation - took a whole morning of poking around and reinstalling things for me to find this thread.

**Comment by ojss** [comment]
@the13fools pretty sure I did that. Anyway I shall try it once again.

**Comment by ojss** [comment]
okay I updated CUDA and Cudnn and here is the stack trace from lldb

```
* thread #1: tid = 0x1d1246, 0x00007fffc1ebfb52 libsystem_c.dylib`strlen + 18, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x0)
    frame #0: 0x00007fffc1ebfb52 libsystem_c.dylib`strlen + 18
libsystem_c.dylib`strlen:
->  0x7fffc1ebfb52 <+18>: pcmpeqb (%rdi), %xmm0
    0x7fffc1ebfb56 <+22>: pmovmskb %xmm0, %esi
    0x7fffc1ebfb5a <+26>: andq   $0xf, %rcx
    0x7fffc1ebfb5e <+30>: orq    $-0x1, %rax
```

**Comment by ojss** [comment]
okay fixed it. Applied this:
```
export CUDA_HOME=/usr/local/cuda
export DYLD_LIBRARY_PATH="$CUDA_HOME/lib:$CUDA_HOME:$CUDA_HOME/extras/CUPTI/lib"
export LD_LIBRARY_PATH=$DYLD_LIBRARY_PATH
```

**instead of:**
```
export CUDA_HOME=/usr/local/cuda
export DYLD_LIBRARY_PATH="$DYLD_LIBRARY_PATH:$CUDA_HOME/lib"
export PATH="$CUDA_HOME/bin:$PATH"
```

and had to do this hack in #2910
