### ISSUE TITLE
Cloning models loaded from disk (SavedModel) fails

### ISSUE THREAD

**Issue by soyers** [tensorflow/tensorflow#37234]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information** 
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: -
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): v2.0.0-rc2-26-g64c3d382ca 2.0.0
- Python version: 3.7.6
- Bazel version (if compiling from source): -
- GCC/Compiler version (if compiling from source): -
- CUDA/cuDNN version: -
- GPU model and memory: -

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
When loading a simple Keras Sequential model with two Conv2D layers stored in SavedModel format from disk and applying the `tensorflow.keras.models.clone_model()` function, a `TypeError: ('Keyword argument not understood:', 'filters')` is thrown.

**Describe the expected behavior**
I expect the `tensorflow.keras.models.clone_model()` to return a clone of the provided model and not fail with an exception.

**Standalone code to reproduce the issue** 
https://colab.research.google.com/gist/soyers/23ec2b19cffd1e2170cbbf2db72aad6d/cloning-models-loaded-from-disk.ipynb

**Comment by amahendrakar** [comment]
@soyers,
I was able to reproduce the issue with [TF 2.0](https://colab.sandbox.google.com/gist/amahendrakar/0db9995e445fc5de96f71f4703d0d403/37234.ipynb) and TF 2.1. However, the issue seems to be fixed in [TF-nightly](https://colab.sandbox.google.com/gist/amahendrakar/e3fdab8e1499358e2acc50445a8cef78/37234-2-1.ipynb). Please check the attached gist. Thanks!

**Comment by soyers** [comment]
@amahendrakar Thank you very much for invastigating this issue! I am gald that the nightly version has already introduced a fix.
I just checked if TF 2.0.1 also contains the fix but it doesn't seem to. Will there be a patch version for TF 2.0 and TF 2.1 some time containig the fix?

**Comment by amahendrakar** [comment]
@soyers,
If the issue is fixed in the TF-nightly version, we can expect it in the next available stable release. Thanks!

**Comment by soyers** [comment]
Thanks for the information and for looking into this!
Closing this issue since the bug will be fixed in the next release.
