### ISSUE TITLE
tf.keras.experimental.WideDeepModel example has wrong input for constructor

### ISSUE THREAD

**Issue by tobillsung-doc** [tensorflow/tensorflow#37239]
The tutorial example for tf.keras.experimental.WideDeepModel instantiated the class with first input augment: dnn_model, and second augment: linear_model as shown in :
https://www.tensorflow.org/api_docs/python/tf/keras/experimental/WideDeepModel#example_4

However, the class should be instantiated by linear_model then dnn_model as shown in:
https://github.com/tensorflow/tensorflow/blob/v2.1.0/tensorflow/python/keras/premade/wide_deep.py#L72

Please update the tutorial example.

**Comment by jvishnuvardhan** [comment]
@tobillsung-doc Do you want to raise a PR to update the docs? Thanks!

**Comment by tobillsung-doc** [comment]
@jvishnuvardhan Yes, please. Thank you.
