### ISSUE TITLE
Impossible to install tensorflow on linux from PyPI with pip versions prior to 19

### ISSUE THREAD

**Issue by seddy** [tensorflow/tensorflow#37235]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04 (but affects any linux)
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:N/A
- TensorFlow installed from (source or binary): PyPI
- TensorFlow version: 1.15.2
- Python version: 3.6.10
- Installed using virtualenv? pip? conda?: pip version less than 19
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

**Describe the problem**

Tensorflow 1.15.2 only provides a `manylinux2010` build on [pypi](https://pypi.org/project/tensorflow/1.15.2/#files) and so can't be built with pip versions older than 19. This means it can't be installed it under certain circumstances where pip can't be upgraded; for example using a managed service such as GCP Composer.

This version of manylinux was made usable by pip in [version 19.0](https://pip.pypa.io/en/stable/news/#id209). As far as I'm aware though, pip still supports `manylinux1`, so I would assume it's reasonable to support this for older installs.

Would it be possible to provide a `manylinux1` build on PyPI to circumvent this issue please? I would rather not have to install a version below 1.15.2 as they have a [high severity security issue](https://github.com/advisories/GHSA-977j-xj7q-2jr9)

My assumption is that it's easy to provide this build given the previous minor version used `manylinux1`. Apologies if this is incorrect and there are good reasons not to support this; I couldn't find any relevant issues which addressed this problem so figured it worth raising.

**Provide the exact sequence of commands / steps that you executed before running into the problem**

Trivially reproducible on any linux within a virtualenv. With pip 18.1:

```
$ pip --version
pip 18.1 from /tmp/tensorflow/pip_18_1/lib/python3.6/site-packages/pip (python 3.6)
$ python --version
Python 3.6.10
$ pip install tensorflow==1.15.2
Collecting tensorflow==1.15.2
  Could not find a version that satisfies the requirement tensorflow==1.15.2 (from versions: 0.12.1, 1.0.0, 1.0.1, 1.1.0rc0, 1.1.0rc1, 1.1.0rc2, 1.1.0, 1.2.0rc0, 1.2.0rc1, 1.2.0rc2, 1.2.0, 1.2.1, 1.3.0rc0, 1.3.0rc1, 1.3.0rc2, 1.3.0, 1.4.0rc0, 1.4.0rc1, 1.4.0, 1.4.1, 1.5.0rc0, 1.5.0rc1, 1.5.0, 1.5.1, 1.6.0rc0, 1.6.0rc1, 1.6.0, 1.7.0rc0, 1.7.0rc1, 1.7.0, 1.7.1, 1.8.0rc0, 1.8.0rc1, 1.8.0, 1.9.0rc0, 1.9.0rc1, 1.9.0rc2, 1.9.0, 1.10.0rc0, 1.10.0rc1, 1.10.0, 1.10.1, 1.11.0rc0, 1.11.0rc1, 1.11.0rc2, 1.11.0, 1.12.0rc0, 1.12.0rc1, 1.12.0rc2, 1.12.0, 1.12.2, 1.12.3, 1.13.0rc0, 1.13.0rc1, 1.13.0rc2, 1.13.1, 1.13.2, 1.14.0rc0, 1.14.0rc1, 1.14.0, 2.0.0a0, 2.0.0b0, 2.0.0b1)
No matching distribution found for tensorflow==1.15.2
You are using pip version 18.1, however version 20.0.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

With version 19.0 (i.e. what I would expect):

```
$ pip --version
pip 19.0 from /tmp/tensorflow/pip_19_0/lib/python3.6/site-packages/pip (python 3.6)
$ python --version
Python 3.6.10
$ pip install tensorflow==1.15.2
Collecting tensorflow==1.15.2
  Using cached https://files.pythonhosted.org/packages/9a/d9/fd234c7bf68638423fb8e7f44af7fcfce3bcaf416b51e6d902391e47ec43/tensorflow-1.15.2-cp36-cp36m-manylinux2010_x86_64.whl
Collecting numpy<2.0,>=1.16.0 (from tensorflow==1.15.2)
  Downloading https://files.pythonhosted.org/packages/62/20/4d43e141b5bc426ba38274933ef8e76e85c7adea2c321ecf9ebf7421cedf/numpy-1.18.1-cp36-cp36m-manylinux1_x86_64.whl (20.1MB)
    100% |████████████████████████████████| 20.2MB 3.2MB/s 
Collecting six>=1.10.0 (from tensorflow==1.15.2)
  Using cached https://files.pythonhosted.org/packages/65/eb/1f97cb97bfc2390a276969c6fae16075da282f5058082d4cb10c6c5c1dba/six-1.14.0-py2.py3-none-any.whl
Collecting protobuf>=3.6.1 (from tensorflow==1.15.2)
  Using cached https://files.pythonhosted.org/packages/57/02/5432412c162989260fab61fa65e0a490c1872739eb91a659896e4d554b26/protobuf-3.11.3-cp36-cp36m-manylinux1_x86_64.whl
Collecting gast==0.2.2 (from tensorflow==1.15.2)
Collecting absl-py>=0.7.0 (from tensorflow==1.15.2)
Collecting termcolor>=1.1.0 (from tensorflow==1.15.2)
Requirement already satisfied: wheel>=0.26; python_version >= "3" in ./pip_19_0/lib/python3.6/site-packages (from tensorflow==1.15.2) (0.34.2)
Collecting astor>=0.6.0 (from tensorflow==1.15.2)
  Using cached https://files.pythonhosted.org/packages/c3/88/97eef84f48fa04fbd6750e62dcceafba6c63c81b7ac1420856c8dcc0a3f9/astor-0.8.1-py2.py3-none-any.whl
Collecting tensorboard<1.16.0,>=1.15.0 (from tensorflow==1.15.2)
  Using cached https://files.pythonhosted.org/packages/1e/e9/d3d747a97f7188f48aa5eda486907f3b345cd409f0a0850468ba867db246/tensorboard-1.15.0-py3-none-any.whl
Collecting opt-einsum>=2.3.2 (from tensorflow==1.15.2)
Collecting keras-preprocessing>=1.0.5 (from tensorflow==1.15.2)
  Using cached https://files.pythonhosted.org/packages/28/6a/8c1f62c37212d9fc441a7e26736df51ce6f0e38455816445471f10da4f0a/Keras_Preprocessing-1.1.0-py2.py3-none-any.whl
Collecting wrapt>=1.11.1 (from tensorflow==1.15.2)
Collecting grpcio>=1.8.6 (from tensorflow==1.15.2)
  Using cached https://files.pythonhosted.org/packages/28/df/1f8a284a5e5819ae07d50bd76996d6f7208afef7533e4896fa1c6445574f/grpcio-1.27.2-cp36-cp36m-manylinux2010_x86_64.whl
Collecting tensorflow-estimator==1.15.1 (from tensorflow==1.15.2)
  Using cached https://files.pythonhosted.org/packages/de/62/2ee9cd74c9fa2fa450877847ba560b260f5d0fb70ee0595203082dafcc9d/tensorflow_estimator-1.15.1-py2.py3-none-any.whl
Collecting google-pasta>=0.1.6 (from tensorflow==1.15.2)
  Using cached https://files.pythonhosted.org/packages/c3/fd/1e86bc4837cc9a3a5faf3db9b1854aa04ad35b5f381f9648fbe81a6f94e4/google_pasta-0.1.8-py3-none-any.whl
Collecting keras-applications>=1.0.8 (from tensorflow==1.15.2)
  Using cached https://files.pythonhosted.org/packages/71/e3/19762fdfc62877ae9102edf6342d71b28fbfd9dea3d2f96a882ce099b03f/Keras_Applications-1.0.8-py3-none-any.whl
Requirement already satisfied: setuptools in ./pip_19_0/lib/python3.6/site-packages (from protobuf>=3.6.1->tensorflow==1.15.2) (45.2.0)
Collecting werkzeug>=0.11.15 (from tensorboard<1.16.0,>=1.15.0->tensorflow==1.15.2)
  Using cached https://files.pythonhosted.org/packages/ba/a5/d6f8a6e71f15364d35678a4ec8a0186f980b3bd2545f40ad51dd26a87fb1/Werkzeug-1.0.0-py2.py3-none-any.whl
Collecting markdown>=2.6.8 (from tensorboard<1.16.0,>=1.15.0->tensorflow==1.15.2)
  Downloading https://files.pythonhosted.org/packages/ab/c4/ba46d44855e6eb1770a12edace5a165a0c6de13349f592b9036257f3c3d3/Markdown-3.2.1-py2.py3-none-any.whl (88kB)
    100% |████████████████████████████████| 92kB 7.9MB/s 
Collecting h5py (from keras-applications>=1.0.8->tensorflow==1.15.2)
  Using cached https://files.pythonhosted.org/packages/60/06/cafdd44889200e5438b897388f3075b52a8ef01f28a17366d91de0fa2d05/h5py-2.10.0-cp36-cp36m-manylinux1_x86_64.whl
Installing collected packages: numpy, six, protobuf, gast, absl-py, termcolor, astor, grpcio, werkzeug, markdown, tensorboard, opt-einsum, keras-preprocessing, wrapt, tensorflow-estimator, google-pasta, h5py, keras-applications, tensorflow
Successfully installed absl-py-0.9.0 astor-0.8.1 gast-0.2.2 google-pasta-0.1.8 grpcio-1.27.2 h5py-2.10.0 keras-applications-1.0.8 keras-preprocessing-1.1.0 markdown-3.2.1 numpy-1.18.1 opt-einsum-3.1.0 protobuf-3.11.3 six-1.14.0 tensorboard-1.15.0 tensorflow-1.15.2 tensorflow-estimator-1.15.1 termcolor-1.1.0 werkzeug-1.0.0 wrapt-1.12.0
You are using pip version 19.0, however version 20.0.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by Saduf2019** [comment]
@seddy 
Please upgrade pip to resolve the issue:
python -m pip install --upgrade pip setuptools

you may check these links for reference [Link1](https://forum.rasa.com/t/could-not-find-a-version-that-satisfies-the-requirement-tensorflow-1-15-0/21509) and [Link2](https://github.com/tensorflow/tensorflow/issues/34302)

**Comment by seddy** [comment]
Hi @Saduf2019, thanks for your response.

As per the description, I am aware of the fact this works with pip >= 19.0. The problem is there are environments where upgrading pip is not possible, so I'm requesting a package of tensorflow on PyPI built with `manylinux1` which would resolve this issue.

**Comment by av8ramit** [comment]
Hi @seddy unfortunately this is not realistically supportable. `manylinux1` packages require being built on a system or toolchain on [CentOS 5](https://www.python.org/dev/peps/pep-0513/#id40).

We did a lot of work to make packages `manylinux2010` compliant and that packaging protocol is already 10 years old. We are in talks with Python and the externally community on eventually adopting `manylinux2014`. 

Additionally we want to abide by pypi's packaging standards so we do not want to improperly tag a package just to make it available via an older pip version.

Sorry for the trouble. 

As an unofficial alternative I'm curious if downloading the whl and direct installing it or modifying the name might work.

**Comment by seddy** [comment]
Thanks @av8ramit, that makes total sense. I hadn't realised quite how out of date `manylinux1` was that it relied on CentOS 5 :scream_cat:. Not supporting that seems reasonable, as does avoiding improper tagging.

Thanks for the suggestion about trying direct installing; I'll bear that in mind when upgrading tensorflow becomes a priority for us, as I think we can get away without upgrading for a little while longer.

**Comment by av8ramit** [comment]
No problem @seddy I'm glad I could help. Good luck!

**Comment by thegautam** [comment]
@seddy @av8ramit are there any known gotchas for doing the renaming hack? What kind of tests can we do to make everything works?

**Comment by av8ramit** [comment]
There are no known gotchas to me, but I personally have not tried it myself.

**Comment by asottile** [comment]
@av8ramit note that the name "manylinux2010" does not imply it is a 10 year old specification -- it has only been in pip since [version 19.0](https://pip.pypa.io/en/stable/news/#id203) (2019-01-22).  the name "2010" is indicating the target machine on which it will be installed, essentially "this should work on any linux distribution released since 2010"

meaning that any pip older than ~a year ago will be unable to install this package

**Comment by mihaimaruseac** [comment]
@thegautam if you only change the tag part of the name there are no caveats. I have done it many times and it worked.

If you change the rest of the name then you also need to change internal contents (at least the name in severla places but this also causes some hashes to change)

**Comment by av8ramit** [comment]
@asottile the age of the specification was not what I was trying to say, I meant to say that it is based off of an OS that was already 10 years old, which is why it was difficult to comply with it. I've updated my comments if that helps.
