### ISSUE TITLE
Problem with segmentation my dataset  in DeepLab

### ISSUE THREAD

**Issue by rafaelmarconiramos** [tensorflow/tensorflow#37243]
I adapted the "build_convert" of the PASCAL Dataset to convert my dataset to execute the DeepLab, but all my segmentation tests generate a black image prediction. 

My dataset has images with 140x140 px. (see an example above:)

Original Image
![211789](https://user-images.githubusercontent.com/18166522/75722022-256f2400-5cb8-11ea-9308-0c7637d37cb5.png)

Original Mask
![211789_OriginalMask](https://user-images.githubusercontent.com/18166522/75721512-3d927380-5cb7-11ea-866d-1e16364d073b.png)

Converted Mask
![211789_ConvertedMask](https://user-images.githubusercontent.com/18166522/75721539-4b47f900-5cb7-11ea-9657-8644aa8eb335.png)

Prediction Image (complete black, all prediction pixels are background)
![211789_Prediction](https://user-images.githubusercontent.com/18166522/75721593-69155e00-5cb7-11ea-8580-61f163bf611c.png)

What am I doing wrong?
Could anybody help me with this problem?

Thanks

**Comment by gadagashwini** [comment]
@rafaelmarconiramos, Can you provide the complete standalone code to replicate the reported issue. Thanks

**Comment by rafaelmarconiramos** [comment]
My step-by-step:

1) Convert the segmentation masks

python ./remove_gt_colormap.py \
  --original_gt_folder="${SEG_FOLDER}" \
  --output_dir="${SEMANTIC_SEG_FOLDER}"
SEG_FOLDER -> the original mask images

2) Create the tfrecord files
(I reused the  PASCAL example)

python ./build_voc2012_data.py \
  --image_folder="${IMAGE_FOLDER}" \
  --semantic_segmentation_folder="${SEMANTIC_SEG_FOLDER}" \
  --list_folder="${LIST_FOLDER}" \
  --output_dir="${OUTPUT_DIR}"

3) To train

NUM_ITERATIONS=100
python "${WORK_DIR}"/train.py \
  --logtostderr \
  --train_split="val" \
  --model_variant="${modelo}" \
  --atrous_rates=12 --atrous_rates=24 --atrous_rates=36 --output_stride=8 \
  --decoder_output_stride=4 \
  --train_crop_size="513,513" \
  --train_batch_size=4 \
  --training_number_of_steps="${NUM_ITERATIONS}" \
  --train_logdir="${TRAIN_LOGDIR}" \
  --dataset_dir="${PASCAL_DATASET}"

4) to eval
python "${WORK_DIR}"/vis.py \
  --logtostderr \
  --vis_split="val" \
  --model_variant="${modelo}" \
  --atrous_rates=12 --atrous_rates=24 --atrous_rates=36 --output_stride=8 --decoder_output_stride=4 \
  --vis_crop_size="513,513" \
  --checkpoint_dir="${TRAIN_LOGDIR}" \
  --vis_logdir="${VIS_LOGDIR}" \
  --dataset_dir="${PASCAL_DATASET}" \
  --max_number_of_iterations=1

Thanks

**Comment by gowthamkpr** [comment]
@rafaelmarconiramos I am closing this issue as this is not related to bug/performance, build/install, feature request or doc related issues. Please post this issue in stackoverflow where there is a wider community to respond. Thanks!
