### ISSUE TITLE
How to deserialize from a dict with tf.keras.losses.get

### ISSUE THREAD

**Issue by jpatts** [tensorflow/tensorflow#37240]
## URL(s) with the issue:
https://www.tensorflow.org/api_docs/python/tf/keras/losses/get

## Description of issue (what needs changing):
Currently there is no documentation at all.
Its fairly straightforward to use by inputting a string denoting default class name:
ex:
```
identifier = "categorical_crossentropy"
tf.keras.losses.get(identifier)
```

However, I am having issues with dictionary objects:
ex:
```
identifier = {"class_name":"categorical_crossentropy","config":{"from_logits":True}}
tf.keras.losses.get(identifier)
```
Returns:
```
Traceback (most recent call last):
  File ".\main.py", line 85, in <module>
    loss = tf.keras.losses.get(jsn)
  File "C:\Users\jopatterson\Documents\autoprime-ml\env\lib\site-packages\tensorflow_core\python\keras\losses.py", line 1186, in get
    return deserialize(identifier)
  File "C:\Users\jopatterson\Documents\autoprime-ml\env\lib\site-packages\tensorflow_core\python\keras\losses.py", line 1175, in deserialize
    printable_module_name='loss function')
  File "C:\Users\jopatterson\Documents\autoprime-ml\env\lib\site-packages\tensorflow_core\python\keras\utils\generic_utils.py", line 315, in deserialize_keras_object
    return cls(**cls_config)
TypeError: categorical_crossentropy() missing 2 required positional arguments: 'y_true' and 'y_pred'
```
I believe it is failing because cls is the already initialized loss function, and it is passing cls_config as its input, rather than using them as parameters during initialization.

### Clear description

This is a very useful method for abstract implementations of loss objects.

### Correct links

This is where the issue is occuring, within the `deserialize_keras_object` function:
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/keras/utils/generic_utils.py#L382

### Parameters defined

There currently is no documentation for this, as `identifier` can be a string, dictionary or callable.

### Returns defined

Returns are not defined, but its fairly obvious it returns a loss function.

### Raises listed and defined

No.

### Usage example

No.

### Request visuals, if applicable

No.

### Submit a pull request?

I would do this if I had enough knowledge to do so. Unfortunately I only know how it works with `identifier` as a String.

**Comment by gadagashwini** [comment]
@jpatts, Documentation is available for tf-nightly version. Please take a look at doc [here](https://www.tensorflow.org/api_docs/python/tf/keras/losses/get?version=nightly) for more about `identifier` and `returns`. Thanks!

**Comment by jpatts** [comment]
@gadagashwini, I saw the nightly documentation after this post, however there is still no explanation for what a “loss configuration dictionary” is. That’s the larger problem for this. The way I tried to do it is the intuitive way, but it doesn’t work for the reasons I showed above, so I would like to know how it’s supposed to be used.

**Comment by lc0** [comment]
@jpatts would you mind to elaborate what exactly are you trying to do?

there are some examples how to serialize custom objects and functions 
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/keras/utils/generic_utils_test.py#L146

**Comment by jpatts** [comment]
@lc0 I gave an example at the top of this issue showing what I’m trying to do. To use a configuration dictionary, I need two mandatory JSON parameters, “class_name” and “config”. This can be seen in the code section I linked above. However, when I do this, the “class_name” is used for the initialization and “config” is used as function inputs. The “config” should be setting “class_name” parameter options during function initialization.

**Comment by jpatts** [comment]
This is the block of code where this is happening.
```
if isinstance(identifier, dict):
    # In this case we are dealing with a Keras config dictionary.
    config = identifier
    (cls, cls_config) = class_and_config_for_serialized_keras_object(
        config, module_objects, custom_objects, printable_module_name)

    if hasattr(cls, 'from_config'):
      arg_spec = tf_inspect.getfullargspec(cls.from_config)
      custom_objects = custom_objects or {}

      if 'custom_objects' in arg_spec.args:
        return cls.from_config(
            cls_config,
            custom_objects=dict(
                list(_GLOBAL_CUSTOM_OBJECTS.items()) +
                list(custom_objects.items())))
      with CustomObjectScope(custom_objects):
        return cls.from_config(cls_config)
    else:
      # Then `cls` may be a function returning a class.
      # in this case by convention `config` holds
      # the kwargs of the function.
      custom_objects = custom_objects or {}
      with CustomObjectScope(custom_objects):
        return cls(**cls_config)
```
The way I send the dictionary, I am being put down the "config holds the kwargs of the function" path. I think I want to be going down the "from_config" path, but don't know how to do so.

**Comment by jpatts** [comment]
[This](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/keras/losses.py#L148) is the "from_config" method for the loss class.
```
@classmethod
  def from_config(cls, config):
    """Instantiates a `Loss` from its config (output of `get_config()`).
    Args:
        config: Output of `get_config()`.
    Returns:
        A `Loss` instance.
    """
    return cls(**config)

  def get_config(self):
    """Returns the config dictionary for a `Loss` instance."""
    return {'reduction': self.reduction, 'name': self.name}
```
This is confusing, as `cls(**cls_config)` and `cls.from_config(cls_config)` end up being the same thing...

**Comment by jpatts** [comment]
Bump. I’m pretty sure that the issues I’m having are from the loss functions not actually having settable parameters. IE you can’t set “from_logits” during initialization, it needs to be set every time it is executed. So in this case, “config” is literally just calling the function with it’s supplied parameters. This makes me question why this is a feature...

**Comment by k-w-w** [comment]
I can explain why this doesn't work -- when you pass a dict, the class name should be the actual name of the class.  `categorical_crossentropy` is a function, and not a class. I think the documentation should be improved here. 

@pavithrasv  Should we modify `losses.get` to return partial functions, if the class name is the name of a function?

**Comment by jpatts** [comment]
Thank you very much for the clarification @k-w-w.
This returns a function:
```
loss = tf.keras.losses.get("categorical_crossentropy")
print(loss)

<function categorical_crossentropy at 0x000002886AFC7318>
```
And this returns the class.
```
jsn = {"class_name":"CategoricalCrossentropy", 
       "config": {
            "from_logits": True
        }
}
loss = tf.keras.losses.get(json)
print(loss)

<tensorflow.python.keras.losses.CategoricalCrossentropy object at 0x0000018D9E219CC8>
```
This solves my problem completely. I agree that the documentation should be updated, as this was very confusing.

**Comment by ashutosh1919** [comment]
@jpatts and @k-w-w , please take a look at PR #37538 and suggest more changes if needed. I have added descriptions and examples which will clarify all doubts regarding `tf.keras.losses.get`

**Comment by pavithrasv** [comment]
Thank you the response @k-w-w and the quick PR @ashutosh1919 .

@k-w-w Yes, we can look into returning partial functions if class name is the name of a function. From the top of my head i think `deserialize_keras_object` may need to be modified for that.
