### ISSUE TITLE
Does BatchMatMul is still not supported in TF1.15?

### ISSUE THREAD

**Issue by TianHongZXY** [tensorflow/tensorflow#37247]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):MacOS 10.14
- TensorFlow installed from (source or binary):
- TensorFlow version (or github SHA if from source):TF1.15

**The output from the converter invocation**

```
Some of the operators in the model are not supported by the standard TensorFlow Lite runtime. If those are native TensorFlow operators, you might be able to use the extended runtime by passing --enable_select_tf_ops, or by setting target_ops=TFLITE_BUILTINS,SELECT_TF_OPS when calling tf.lite.TFLiteConverter(). Otherwise, if you have a custom implementation for them you can disable this error with --allow_custom_ops, or by setting allow_custom_ops=True when calling tf.lite.TFLiteConverter(). Here is a list of builtin operators you are using: ADD, CAST, CONCATENATION, CONV_2D, DIV, EQUAL, EXPAND_DIMS, FILL, FLOOR_DIV, FULLY_CONNECTED, GATHER, LOGISTIC, MATRIX_DIAG, MEAN, MUL, PACK, POW, RESHAPE, SELECT, SHAPE, SLICE, SOFTMAX, SPLIT, SQUARED_DIFFERENCE, SQUEEZE, STRIDED_SLICE, SUB, TILE, TRANSPOSE. Here is a list of operators for which you will need custom implementations: BatchMatMul.
Traceback (most recent call last):
  File "/Users/tianhongzxy/Documents/sakt_tf1.15/venv_sakt_tf/bin/toco_from_protos", line 8, in <module>
    sys.exit(main())
  File "/Users/tianhongzxy/Documents/sakt_tf1.15/venv_sakt_tf/lib/python3.6/site-packages/tensorflow_core/lite/toco/python/toco_from_protos.py", line 89, in main
    app.run(main=execute, argv=[sys.argv[0]] + unparsed)
  File "/Users/tianhongzxy/Documents/sakt_tf1.15/venv_sakt_tf/lib/python3.6/site-packages/tensorflow_core/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/Users/tianhongzxy/Documents/sakt_tf1.15/venv_sakt_tf/lib/python3.6/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/Users/tianhongzxy/Documents/sakt_tf1.15/venv_sakt_tf/lib/python3.6/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "/Users/tianhongzxy/Documents/sakt_tf1.15/venv_sakt_tf/lib/python3.6/site-packages/tensorflow_core/lite/toco/python/toco_from_protos.py", line 52, in execute
    enable_mlir_converter)
Exception: We are continually in the process of adding support to TensorFlow Lite for more ops. It would be helpful if you could inform us of how this conversion went by opening a github issue at https://github.com/tensorflow/tensorflow/issues/new?template=40-tflite-op-request.md
 and pasting the following:

Some of the operators in the model are not supported by the standard TensorFlow Lite runtime. If those are native TensorFlow operators, you might be able to use the extended runtime by passing --enable_select_tf_ops, or by setting target_ops=TFLITE_BUILTINS,SELECT_TF_OPS when calling tf.lite.TFLiteConverter(). Otherwise, if you have a custom implementation for them you can disable this error with --allow_custom_ops, or by setting allow_custom_ops=True when calling tf.lite.TFLiteConverter(). Here is a list of builtin operators you are using: ADD, CAST, CONCATENATION, CONV_2D, DIV, EQUAL, EXPAND_DIMS, FILL, FLOOR_DIV, FULLY_CONNECTED, GATHER, LOGISTIC, MATRIX_DIAG, MEAN, MUL, PACK, POW, RESHAPE, SELECT, SHAPE, SLICE, SOFTMAX, SPLIT, SQUARED_DIFFERENCE, SQUEEZE, STRIDED_SLICE, SUB, TILE, TRANSPOSE. Here is a list of operators for which you will need custom implementations: BatchMatMul.

```

**Comment by Saduf2019** [comment]
@TianHongZXY 
Can you please share a standalone code to reproduce the issue. Did you try adding converter.allow_custom_ops = True to enable custom ops in the tf.lite? Thanks!

**Comment by TianHongZXY** [comment]
@Saduf2019 If I set converter.allow_custom_ops = True, the model can be converted, but converted model still can't be used because I didn't implement the custom_op BatchMatMul, but I found the supported ops includes BatchMatMul in `tensorflow/tensorflow/lite/delegates/flex/whitelisted_flex_ops.cc`

**Comment by TianHongZXY** [comment]
@Saduf2019  Here's the code you can reproduce the issue, if you set `converter.allow_custom_ops = True`, the tflite file can be converted successfully. When you `run test_infer_model` you may encounter `reshape op error`, you can solve this by switch to `tf-nightly` version. But the unimplemented op BatchMatMul is the problem I still can't solve yet.

**Comment by TianHongZXY** [comment]
https://colab.research.google.com/drive/1shJbg5iK7i6-F_eAJnexN9_Aj8PO9tAL

**Comment by Saduf2019** [comment]
@TianHongZXY 
please refer to this [issue](https://github.com/tensorflow/tensorflow/issues/35449#issuecomment-570318723) and let us know if it helps

**Comment by TianHongZXY** [comment]
@Saduf2019 I'm using the TF1.15 and my model can't be run with tf-nightly, so I found it not helpful and `converter.experimental_new_converter = True` doesn't work too.

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.
