### ISSUE TITLE
Source-compiled .whl package is much slower in training

### ISSUE THREAD

**Issue by gclouding** [tensorflow/tensorflow#3724]
Recently, from my experiment, I found that running inception model using the .whl file generated by myself is much slower than using .whl file downloaded directly from the $TF_BINARY_URL.

### Environment info
Operating System: ubuntu14.04
CUDA: cuda7.5
CUDNN: cudnn 5

I followed the instructions
./configure
bazel build -c opt --config=cuda //tensorflow/tools/pip_package:build_pip_package
bazel-bin/tensorflow/tools/pip_package/build_pip_package /tmp/tensorflow_pkg
And I got tensorflow-0.9.0-py2-none-any.whl to install using:
pip install /home/dl/bxl/tensorflow/tensorflow_pkg/tensorflow-0.9.0-py2-none-any.whl
 (the name of this .whl file is automatically generated )

Then I downloaded the inception model related files to train following the instructions:
cd ~/models/inception
bazel build inception/imagenet_train
bazel-bin/inception/imagenet_train --num_gpus=1 --batch_size=64 --train_dir=/tmp/imagenet_train --data_dir=/data1/ImageNet

From the information printed out, I found that the speed is 8.5 samples/sec. (In the first several lines printed out, it says：
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcublas.so.7.5 locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcudnn.so.5 locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcufft.so.7.5 locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcurand.so.7.5 locally,
from which I guess CUDA/CuDNN are automatically loaded)

However, if I replace the .whl file by that directly downloaded from the $TF_BINARY_URL provided in www.tensorflow.org ( tensorflow-0.9.0-cp27-none-linux_x86_64.whl, which uses CuDNN4 and cuda7.5), and reinstall it using pip, and restart a new process to train the inception model using the same code. 

I got that the training speed was 20.2 samples/sec, which is nearly 2.5x faster than my first training using the .whl package generated by myself. 

So it is very difficult to explain. Because I use CUDNN5, I expect my version is faster, but in fact, it is 2.5x slower....

Does anyone know why??

Thanks in advance.

**Comment by yaroslavvb** [comment]
You need to build with -c opt, ie
bazel build -c opt inception/imagenet_train

**Comment by girving** [comment]
To expand on Yaroslav's comment: you need to give options to bazel every time you run it.  If you run it twice with different options, it will discard anything built with the older options.

**Comment by gclouding** [comment]
I have tried this:
cd ~/models/inception
bazel build -c opt inception/imagenet_train
bazel-bin/inception/imagenet_train --num_gpus=1 --batch_size=64 --train_dir=/tmp/imagenet_train --data_dir=/data1/ImageNet

Unfortunately, the performance is still the same as my previous results.

**Comment by gclouding** [comment]
It seems that it is not the problem of "bazel build -c opt inception/imagenet_train", because I use the same build option with self-complied .whl package and the downloaded one.

**Comment by yaroslavvb** [comment]
Some debugging ideas:

1. Use strace to see which "_pywrap_tensorflow.so" each run is opening, and
check that their sizes are similar
2. Configure built-from-source version with CuDNN version 4.0 and see how
fast it is
3. Look at how the version is built in the "pip.sh" script
<https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/ci_build/builds/pip.sh>

**Comment by chhwang** [comment]
This is a known bug. #3603
