### ISSUE TITLE
LOW GPU HIGH CPU :(

### ISSUE THREAD

**Issue by najibghadri** [tensorflow/tensorflow#37263]
Hello!
I am using Tensorflow on Docker, Ubuntu.
I have tried many tensorflow docker versions, tried different drivers, tried everything.:

## Sys info
-  Linux 5.3.0-40-generic 18.04.1 Ubuntu x86_64
- Docker 19.03.6, nvdia-smi works, I have all packagages needed
- Tensorflow Docker versions I tried (in some of the the GPU didn't even get recognized..): 
  - latest-gpu-jupyter (Py2, this works okay, but low gpu usage)
  - latest-gpu-py3-jupyter (sometimes bugs out)
  - 2.0.1-gpu-py3-jupyter (sometimes bugs out regarding GPU too)
- NVIDIA-SMI: 440.59, GeForce MX150, 2002MiB

## So what I am trying to DO:
 I load the MINTS dataset and do a **nearest neighbor** algorithm on them. Pretty simple right, I just started using tenforflow, I would love it if it was eating 100% of my GPU not CPU (if that is even possible). This is my code concisely:

```
(Xtr, Ytr), (Xte, Yte) = keras.datasets.cifar10.load_data()
# I convert them to tensors
# I save the whole training set into Xtr (50 000 rows of 3072 int32) to later do the nearest neighbor with them
# Upon "prediction" I find the index of Xtr row with lowest L1 distance from X for each X test row (10000 rows of 3072 ints):
with tf.device('/gpu:0'):
    min_distances_index = tf.map_fn(self.reduce_distance, Xte)
# which calls this tf function:
    @tf.function
    def reduce_distance(self, X):
        # X is of shape (3072,1)
        return tf.math.argmin(tf.math.reduce_sum(tf.math.abs(tf.math.subtract(self.Xtr, X)), axis=1), output_type=tf.int32)
# Quite simple and readable I hope!
# Then when I have min distance indices I simply return the Y values from them
```
I use int32 beacause as you saw there is subtraction and then sum, so.. 

## Now
**This takes 30 minutes!**
And this is my system statistic during running:
From htop:
![image](https://user-images.githubusercontent.com/11639734/75797157-05ea0100-5d75-11ea-9c7b-66df992270ab.png)
nvidia-smi:
![image](https://user-images.githubusercontent.com/11639734/75797912-1e0e5000-5d76-11ea-9b23-245cd648f9d3.png)
Jumping between 0% and 20% but on average below 10%

Why? Is this normal? 
Thanks in advance.

**Comment by ravikyram** [comment]
@najibghadri 

Thanks for reporting the issue. Looks like code is incomplete. Request you to provide colab link or simple standalone code to reproduce the issue in our environment. It helps us in localizing the issue faster. Thanks!

**Comment by najibghadri** [comment]
https://colab.research.google.com/drive/1QyVMNO-paFJQ2Ie9zkIva0FA9wbxAYT2

**Comment by gowthamkpr** [comment]
@najibghadri I think this is because most int32 kernels are placed on host memory. You can refer to the comment [here](https://github.com/tensorflow/tensorflow/issues/33835#issuecomment-548661718).

**Comment by gowthamkpr** [comment]
Closing this issue as it has been inactive for a long time. Please add additional comments for us to open this issue again. Thanks!
