### ISSUE TITLE
Unable to remove model and release GPU memory

### ISSUE THREAD

**Issue by ahnjaewoo** [tensorflow/tensorflow#37289]
**System information** 
- Custom code
- Ubuntu 16.04
- TensorFlow installed from source (with pip)
- TensorFlow version v2.0.0
- Python version: 3.6
- CUDA 10.0
- TITAN XP

At first, I tried to load the pre-trained transformer-base model (A) and then add additional word embeddings (dynamic vocabulary) to it. However, it doesn't work (i.e., can't add values to `tf.Variable`)
Instead, I created another model (B) with the size of dynamic vocabulary and set its weights to _existing_ transformer model (A).
Then, I do not need _initial_ model (A), so I want to remove it and clear GPU memory.
I tried such commands but they didn't work as well.
```
# delete not model (B) but only model (A)
tf.keras.backend.clear_session()
del model
gc.collect()
```
According to #36465, I can either use multiprocessing functions... but then I have to remove both model (A) and model (B). So I just want more clear solution.
Thanks.

**Comment by ThomasRobertFr** [comment]
I recently looked at this issue of making tensorflow free GPU memory, from what I understood I does not seem like it's gonna be available anytime soon. So for now when tf allocates some GPU memory, it will not free it until the cuda session is closed, regardless of it being used to store objects or not.

You can close the whole cuda session using numba (e.g. https://github.com/tensorflow/tensorflow/issues/19731#issuecomment-423426372) but this is very hacky: it releases all the memory of the current process but no longer allows you to use the GPU with tf. 

The features you're looking for, i.e. garbage collection + ram freezing, is not available on tensorflow and I'm not sure you can do it in any other way. I don't have any "side" in the tf/pytorch war, I use both. If this feature is crutial to you and if it's possible to consider switching in your context, I just wanted to let you know that [this feature of accessing cuda garbage collection is available in pytorch](https://pytorch.org/docs/stable/cuda.html#torch.cuda.empty_cache) so it might be an option.

**Comment by ahnjaewoo** [comment]
Thanks for suggestion. (especially numba)
I decided to execute it as a sub-process with another python code.
I hope this problem to be resolved in TF society someday :) 

Thanks 👍
