### ISSUE TITLE
modify input shape from [?,?,?,3] to [1,640,640,3]

### ISSUE THREAD

**Issue by hnuhchen** [tensorflow/tensorflow#37285]
This template is for miscellaneous issues not covered by the other issue categories.

For questions on how to work with TensorFlow, or support for problems that are not verified bugs in TensorFlow, please go to [StackOverflow](https://stackoverflow.com/questions/tagged/tensorflow).

If you are reporting a vulnerability, please use the [dedicated reporting process](https://github.com/tensorflow/tensorflow/blob/master/SECURITY.md).

For high-level discussions about TensorFlow, please post to discuss@tensorflow.org, for questions about the development or internal workings of TensorFlow, or if you would like to know how to contribute to TensorFlow, please post to developers@tensorflow.org.

hello, everyone.

I am using tensorflow.contrib.graph_editor to modify my SSD model. In fact, my model has input shape [?,?,?,3], so many nodes in the graph may not have exact shapes, such as [?,?,?,32] and [?,?,?,64]. So i want to use 'swap_inputs' to swap a new node whose shape is [1,640,640,3] with the input node whose shape is [?,?,?,3]. So how could the change affect all the nodes in the graph whose shape are not exact?

**Comment by amahendrakar** [comment]
@hnuhchen,
If you are looking to change the input layer for your model you can check out [this](https://stackoverflow.com/a/49554465) StackOverflow comment on a similar issue.

Also, please fill in the issue template along with a minimal reproducible code in order to expedite the trouble-shooting process. 
Thanks!

**Comment by amahendrakar** [comment]
Any updates regarding this issue? Thanks!

**Comment by amahendrakar** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
