### ISSUE TITLE
TypeError: Saw an object that is an instance of a strict subclass of EagerTensor

### ISSUE THREAD

**Issue by stefan-falk** [tensorflow/tensorflow#37288]
I noticed that importing `from tensorflow_core.python.framework.ops import EagerTensor` is a problem when debugging Tensorflow in eager mode.

**System information** 
$ pip freeze | grep tensor
tensorboard==2.1.0
tensorflow==2.1.0
tensorflow-data-validation==0.21.2
tensorflow-datasets==2.0.0
tensorflow-estimator==2.1.0
tensorflow-metadata==0.21.1
tensorflow-serving-api==2.1.0
tensorflow-transform==0.21.0

**Describe the current behavior**
Importing `from tensorflow_core.python.framework.ops import EagerTensor` will throw

> TypeError: Saw an object that is an instance of a strict subclass of EagerTensor, which is not supported.  Item 0 is type: tensorflow.python.framework.ops.EagerTensor

when running the code example below.

**Describe the expected behavior**

No exception when importing `from tensorflow_core.python.framework.ops import EagerTensor` or at least an exception/error message which allows one to track down the issue more easily.

**Standalone code to reproduce the issue** 

```python
from tensorflow import keras
from tensorflow.keras import layers
# noinspection PyUnresolvedReferences
from tensorflow_core.python.framework.ops import EagerTensor


def main():
    model = keras.Sequential()
    model.add(layers.Embedding(1000, 64, input_length=10))

if __name__ == '__main__':
    main()
```

Please let me know if you need additional information.

**Comment by Saduf2019** [comment]
@stefan-falk 
I ahve replicated your code on mentioned tensorflow version 2.1 and do not face any issues, please refer to [this gist ](https://colab.sandbox.google.com/gist/Saduf2019/6bacad64a1e239009ed007e38377d794/37288.ipynb)for the same.

**Comment by stefan-falk** [comment]
Okay this is weird I am not seeing this error anymore either O_o.

I am using are remote debugger and maybe there was/is an issue with my dependencies. I am closing this issue. Thank you @Saduf2019 for taking a look at this!

**Comment by stefan-falk** [comment]
@Saduf2019 This is weird. I have this issue again. This time I cannot even reproduce it in a separate project. I must have to do something with the way I am importing Tensorflow components. I can't see what's causing this. Last time, I remember, I uninstalled Tensorflow via pip and reinstalled everything. 

But this time I am certain this comes from importing something I shouldn't ..

**Comment by stefan-falk** [comment]
@Saduf2019 Okay, it took me a while but I finally was able to track the error down by commenting out line by line and made a recursive search through my entire code and found the problem where I wasn't even thinking about.

I don't know if this is something that's intended.

For writing data shards, I have this helper function:

```python
from tensorflow_core.python.framework.ops import EagerTensor
# ...
def write_records(shard_filepath, records):
    with tf.io.TFRecordWriter(shard_filepath) as writer:
        for record in records:
            if isinstance(record, EagerTensor):
                record = record.numpy()
            writer.write(record)
````

Apparently it's not possible to import `from tensorflow_core.python.framework.ops import EagerTensor` without breaking things. My code from above should look like this:

```
from tensorflow import keras
from tensorflow.keras import layers
# noinspection PyUnresolvedReferences
from tensorflow_core.python.framework.ops import EagerTensor


def main():
    model = keras.Sequential()
    model.add(layers.Embedding(1000, 64, input_length=10))


if __name__ == '__main__':
    main()
```

I don't know if this intended or unavoidable but damn it was no fun to find the problem.

**Comment by ymodak** [comment]
@stefan-falk  Following import method should work,
```python
from tensorflow.python.framework.ops import EagerTensor
```
