### ISSUE TITLE
contrib.learn.DNNRegressor not compatible for e.g. GridSearchCV

### ISSUE THREAD

**Issue by jbwenisch** [tensorflow/tensorflow#3728]
Imho the new architecture of contrib.learn.DNNRegressor (compared to the old contrib.learn.TensorflowDNNRegressor) makes it impossible to properly use things like GridSearchCV from sklearn. To use GridSearchCV I have to pass all parameters to be tuned to the constructor. In the new architecture of DNNRegressor some parameters are passed to the fit-method which is quite untypical for sklearns architecture usually expecting only X and y as parameters of the fit-method. For example I can no longer tune steps and batch_size (now part of the fit-method) with GridSearchCV. I can only pass them as fixed fit_params. Or am I getting something wrong?

**Comment by girving** [comment]
@ilblackdragon Can you comment?

**Comment by lmsasu-siemens** [comment]
You can see the same issue detailed at http://stackoverflow.com/questions/38968249/cannot-run-tflearn-with-sklearns-gridsearchcv

**Comment by drpngx** [comment]
Looks like this was answered on stackoverflow.
