### ISSUE TITLE
[started] convert to records example in tutorial?

### ISSUE THREAD

**Issue by dzhwinter** [tensorflow/tensorflow#3729]
As far as i know, the started document only provide a example with mnist example, however, really confused about how tensorflow handle an sparse example.
when it comes to linear model, the libsvm format always be a popular format in research and industry. But how to convert libsvm format entries to tensorflow records? How will an entry represent in tensorflow? in column ways or in row ways?

e.g.
```
label, key:value, key:value, ....

```
whereas the key is index, value is the feature value in sparse format. 
Can anyone kindly to add such an example to tutorial ? Thanks

**Comment by girving** [comment]
I think these questions would be better on StackOverflow.  You're welcome to submit a tutorial yourself, but otherwise I'll close this issue for now, since Github issues are more for code bugs and feature requests.

**Comment by chenghuige** [comment]
@dzhwinter http://www.cnblogs.com/rocketfan/p/5765979.html 
This is an example of parsing libsvm format

**Comment by RayAndWind** [comment]
@chenghuige 
https://github.com/chenghuige/tensorflow-exp/tree/master/examples/tf-record/sparse  404 error
what's happen?
