### ISSUE TITLE
build ktrain model with tensorflow 2.1.0 kera version 2.3.1

### ISSUE THREAD

**Issue by CH0102NG** [tensorflow/tensorflow#37297]
I am trying to build a model with ktrain. Howver, I received the following errors:

```
import ktrain
from ktrain import text
```

> WARNING:tensorflow:From c:\users\chth\anaconda3\envs\kg\lib\site-packages\tensorflow_core\python\compat\v2_compat.py:88: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
> Instructions for updating:
> non-resource variables are not supported in the long term
> Using DISABLE_V2_BEHAVIOR with TensorFlow
> using Keras version: 2.2.4-tf

`model = text.sequence_tagger('bilstm-crf', preproc)
`
> pretrained word2vec word embeddings will be used with bilstm-crf
> Loading pretrained word vectors...this may take a few moments...
> Done.
> WARNING:tensorflow:From c:\users\chth\anaconda3\envs\kg\lib\site-packages\tensorflow_core\python\keras\initializers.py:119: calling RandomUniform.__init__ (from tensorflow.python.ops.init_ops) with dtype is deprecated and will be removed in a future version.
> Instructions for updating:
> Call initializer instance with the dtype argument instead of passing it to the constructor
> WARNING:tensorflow:From c:\users\chth\anaconda3\envs\kg\lib\site-packages\tensorflow_core\python\ops\resource_variable_ops.py:1635: calling BaseResourceVariable.__init__ (from tensorflow.python.ops.resource_variable_ops) with constraint is deprecated and will be removed in a future version.
> Instructions for updating:
> If using Keras pass *_constraint arguments to layers.
> WARNING:tensorflow:From c:\users\chth\anaconda3\envs\kg\lib\site-packages\tensorflow_core\python\ops\init_ops.py:97: calling GlorotUniform.__init__ (from tensorflow.python.ops.init_ops) with dtype is deprecated and will be removed in a future version.
> Instructions for updating:
> Call initializer instance with the dtype argument instead of passing it to the constructor
> WARNING:tensorflow:From c:\users\chth\anaconda3\envs\kg\lib\site-packages\tensorflow_core\python\ops\init_ops.py:97: calling Orthogonal.__init__ (from tensorflow.python.ops.init_ops) with dtype is deprecated and will be removed in a future version.
> Instructions for updating:
> Call initializer instance with the dtype argument instead of passing it to the constructor
> WARNING:tensorflow:From c:\users\chth\anaconda3\envs\kg\lib\site-packages\tensorflow_core\python\ops\init_ops.py:97: calling Zeros.__init__ (from tensorflow.python.ops.init_ops) with dtype is deprecated and will be removed in a future version.
> Instructions for updating:
> Call initializer instance with the dtype argument instead of passing it to the constructor
> WARNING:tensorflow:AutoGraph could not transform <bound method CRF.viterbi_decoding of <ktrain.text.ner.anago.layers.CRF object at 0x000002E483BAF508>> and will run it as-is.
> Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
> Cause: LIVE_VARS_IN
> WARNING: AutoGraph could not transform <bound method CRF.viterbi_decoding of <ktrain.text.ner.anago.layers.CRF object at 0x000002E483BAF508>> and will run it as-is.
> Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
> Cause: LIVE_VARS_IN

`learner.fit(1e-3, 1)`

> WARNING:tensorflow:From c:\users\chth\anaconda3\envs\kg\lib\site-packages\ktrain\core.py:1185: Model.fit_generator (from tensorflow.python.keras.engine.training) is deprecated and will be removed in a future version.
> Instructions for updating:
> Please use Model.fit, which supports generators.

**Comment by saikumarchalla** [comment]
@CH0102NG Can you please share colab link or simple standalone code to reproduce the issue in our environment,it helps us localizing the issue faster.Thanks!

**Comment by CH0102NG** [comment]
Hi, sorry I forgot to update. I have managed to resolve the issue by upgrading my ktrain to version 0.10.0 and shutting down another jupyter notebook that was also using cuda. Thanks so much for response:)

**Comment by saikumarchalla** [comment]
@CH0102NG  Closing this issue as it was resolved.Thanks!
