### ISSUE TITLE
My model has tow inputs. when I load SavedModel, how to use Concretefunction?

### ISSUE THREAD

**Issue by Stealers** [tensorflow/tensorflow#37291]
my model has tow inputs. when I load SavedModel, how to use Concretefunction?
model = tf.saved_model.load('./model_rec')
inference = model.signatures['serving_default']
I tried many ways, but all failed
e.g
outputs  = inference(tf.constant(image_batch,dtype=tf.float32),tf.constant(anchors_batch,dtype=tf.float32))
TypeError: Expected at most 0 positional arguments (and the rest keywords, of ['input_1', 'input_4']),

signature_def['serving_default']:
  The given SavedModel SignatureDef contains the following input(s):
    inputs['input_1'] tensor_info:
        dtype: DT_FLOAT
        shape: (-1, 512, 512, 3)
        name: serving_default_input_1:0
    inputs['input_4'] tensor_info:
        dtype: DT_FLOAT
        shape: (-1, -1, 4)
        name: serving_default_input_4:0

**Comment by amahendrakar** [comment]
@Stealers,
In order to expedite the trouble-shooting process, could you please provide the complete code to reproduce the issue reported here and also the TensorFlow version you are using. Thanks!

**Comment by Stealers** [comment]
@amahendrakar ,
my tensorflow version is 2.1,
model = tf.saved_model.load('./model_rec')
inference = model.signatures['serving_default']

my model has tow inputs, for one input, I can easily use the following code to inference. 
code:
img = processing_inp("img_test/11.jpg")
y_pred = inference(tf.constant(img,dtype=tf.float32))

for tow inputs, I don't know how to inference.

y_pred = inference(tf.constant(input_1,dtype=tf.float32), tf.constant(anchors_batch,dtype=tf.float32))#failed
y_pred = inference([tf.constant(input_2,dtype=tf.float32), tf.constant(anchors_batch,dtype=tf.float32)])#failed
.....

**Comment by Stealers** [comment]
y_pred = inference(input_1=tf.constant(image_batch,dtype=tf.float32), input_4=tf.constant(anchors_batch,dtype=tf.float32))#, tf.constant(anchors_batch,dtype=tf.float32)

I made it!
