### ISSUE TITLE
Low efficiency to do the Dequantize

### ISSUE THREAD

**Issue by Leslie-Fang** [tensorflow/tensorflow#37295]
<em>Please make sure that this is an issue related to performance of TensorFlow.
As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:performance_template</em>

**System information** 
- Have I written custom code (as opposed to using a stock
example script provided in TensorFlow): 
- OS Platform and Distribution (e.g.,
Linux Ubuntu 16.04):  Centos
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if
the issue happens on mobile device: 
- TensorFlow installed from (source or
binary): - TensorFlow version (use command below): 
- Python version: - Bazel
version (if compiling from source):
- GCC/Compiler version (if compiling from
source): 
- CUDA/cuDNN version: - GPU model and memory:

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
Refer to this code
https://github.com/tensorflow/tensorflow/blob/c653d96483ef94ff51dbcae752e6377411e7761f/tensorflow/core/kernels/dequantize_op.cc#L131-L135
Even the target output is fp32, the code still doing the cast operation in a single thread for loop.
When the input tensor is large, the efficiency is quite lower.

**Describe the expected behavior**
1. The output is fp32, we needn't to do the cast again.
2. The output is bfloat16, use multi-thread to do the cast.

**Standalone code to reproduce the issue** 
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by Saduf2019** [comment]
@Leslie-Fang 
please share the tensorflow version for us to replicate the issue faced by you, could you fill in the template it helps us resolve the issue faster, we would require a simple stand alone code with indentation and all dependencies for us to help you resolve.

**Comment by Leslie-Fang** [comment]
will submit a PR to improve the performance.
