### ISSUE TITLE
Wrong NVIDIA driver and CUDA libs versions installed when running GPU setup instructions.

### ISSUE THREAD

**Issue by julj** [tensorflow/tensorflow#37290]
On Ubuntu 18.04, when running the instructions given [here](https://www.tensorflow.org/install/gpu#ubuntu_1804_cuda_101) the driver version installed is 440 et the CUDA version is 10.2, while the recommended versions are, respectively, 430 and 10.1.

**Comment by gadagashwini** [comment]
@julj, As per the [doc](https://www.tensorflow.org/install/gpu#ubuntu_1804_cuda_101), it downloads `cuda-repo-ubuntu1804_10.1.243-1_amd64.deb` and nvidia-driver version as `sudo apt-get install --no-install-recommends nvidia-driver-430`. Can you try once and let us know. Thanks!

**Comment by julj** [comment]
I followed the instructions and got the wrong version installed in the end. I had to purge cuda* and nvidia and install everything manually (downloading the packages from NVIDIA).
