### ISSUE TITLE
Which NVIDIA GPU to buy for TF with Windows?

### ISSUE THREAD

**Issue by FB43** [tensorflow/tensorflow#37299]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 8.1 & 10 dual-boot
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): binary
- TensorFlow version: the =last one
- Python version:3.7
- Installed using virtualenv? pip? conda?:pip conda
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:10
- GPU model and memory: That's the question!

**Describe the problem**
Hello, I've tried since some days to use TF with my GPU GeForce GTX 760. It doesn't work because its computing capabilities are 3.0. 
I've even tried to recompile the 1.8 version unsuccessfully.
Well, I've decided to change it. 
The NVIDIA MSI GTX 1050 Ti 4GT OC - 4 Go seems to fit with the requisites but I can read it's not more available on their site.
Is it recommended anywhere?
I will mainly use TF for fractal art.
Below some infos of my PC.
Thanks for your help and patience.
Best regards,
François
Type de processeur	QuadCore Intel Core i5-4670K, 4200 MHz (42 x 100)
Nom de la carte mère	Asus Z87-A  (2 PCI, 2 PCI-E x1, 3 PCI-E x16, 4 DDR3 DIMM, Audio, Video, Gigabit LAN)  3.0 (Gen 3) slots https://www.asus.com/fr/Motherboards/Z87A/
DIMM1: G Skill RipjawsX F3-12800CL9-4GBXL	4 Go DDR3-1600 DDR3 SDRAM  (11-11-11-28 @ 800 MHz)  (10-10-10-27 @ 761 MHz)  (9-9-9-24 @ 685 MHz)  (8-8-8-22 @ 609 MHz)  (7-7-7-19 @ 533 MHz)  (6-6-6-16 @ 457 MHz)
Moniteur	Samsung SyncMaster S24F350  [24" LCD]  (H4ZM101320)

**Provide the exact sequence of commands / steps that you executed before running into the problem**

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by amahendrakar** [comment]
@FB43,
Any GPU which satisfies the hardware and software requirements listed [here](https://www.tensorflow.org/install/gpu#hardware_requirements) can be used to build the TensorFlow GPU package. 

You can also check out the tested build configurations for Windows from the official [documentation](https://www.tensorflow.org/install/source_windows#gpu). Thanks!

**Comment by FB43** [comment]
OK. The new GPU is on the list! Thanks for your help. François
