### ISSUE TITLE
Random numbers with None value in shape

### ISSUE THREAD

**Issue by bayerj** [tensorflow/tensorflow#373]
There are several use cases where the shape of random numbers is to be determined at runtime. E.g. for variational auto encoder or injection of noise into an MLPs units. As of now, this seems not possible in an elegant way with tensorflow:

    import tensorflow as tf
    x = tf.placeholder('float32', [None, 784])
    noised = x + tf.random_normal(x.get_shape())

The above throws [this traceback](https://gist.github.com/bayerj/12e6a80c36593173a489). I have to replace ``None`` above with a number known before runtime. But then I have to fix my batch size beforehand (to which the None corresponds) and need different expressions for each batch size.

**Comment by rafaljozefowicz** [comment]
TF.shape(x) should work instead.

**Comment by bayerj** [comment]
Thank you!

**Comment by guerrillacaptain** [comment]
like

**Comment by idofr** [comment]
Uh! that's actually really helpful :) thanks. Why is that?

**Comment by BBillot** [comment]
Sorry but this doesn't seem to be working with **TF2**, as placeholders don't exist anymore.

Using None to specify the shape doesn't work either, i.e,
```tf.random.normal((None, 784))```
gives
ValueError: Attempt to convert a value (None) with an unsupported type (<class 'NoneType'>) to a Tensor.

Any idea, apart from using tf.shape() on another tensor of the model to extract the batchsize ?

**Comment by JJKK1313** [comment]
Also having the same problem,
tf.shape() returns some wierd number for placeholder's shape.
```
    def call(self, inputs, training=True, **kwargs):
        print(inputs)
        print(tf.shape(inputs), inputs.shape)
```
gives me:
```
Tensor("Placeholder:0", shape=(None, 128, 128, 3), dtype=float32)
Tensor("RandomHSVPreprocessor/Shape:0", shape=(4,), dtype=int32) (None, 128, 128, 3)
```
