### ISSUE TITLE
Bug with callbacks in tf.keras model

### ISSUE THREAD

**Issue by CleanPegasus** [tensorflow/tensorflow#37306]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information** 
- Have I written custom code (as opposed to using a stock
example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g.,
Linux Ubuntu 16.04): Ubuntu 19.10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if
the issue happens on mobile device: N/A
- TensorFlow installed from (source or
binary): - TensorFlow version (use command below): pip install / tensorflow==2.0
- Python version: - Bazel
version (if compiling from source): 3.7.5
- GCC/Compiler version (if compiling from
source): N/A
- CUDA/cuDNN version: - GPU model and memory: n/A

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
When force stopping a model on training, all the callbacks(on_epoch_end, on_train_end) are called. This does not happen with a keras model.
**Describe the expected behavior**
The other callbacks, namely on_epoch_end and on_train_end aren't supposed to be called.

**Standalone code to reproduce the issue** 
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.
https://colab.research.google.com/drive/1Uu_LPSgdyXAyWubGAQDpbMq8BcUcXqUd

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by amahendrakar** [comment]
@CleanPegasus,
I was able to reproduce the issue with [TF2.1](https://colab.sandbox.google.com/gist/amahendrakar/ae4921f2d23cd2dfdf60524888168574/37306.ipynb), however the issue seems to be fixed in [TF-nightly](https://colab.sandbox.google.com/gist/amahendrakar/da264a2d14b1b6242ee67f663e5059fe/37306-tf-nightly.ipynb). With TF-nightly, I see that the functions `on_epoch_end` and `on_train_end` are not being called.
Please find the attached gist. Thanks!

**Comment by CleanPegasus** [comment]
Thanks for the help.
