### ISSUE TITLE
Crashing introduced when call kernel.matrix with latest nightly build of TF 2.2

### ISSUE THREAD

**Issue by oracle3001** [tensorflow/tensorflow#37300]
Cross Post from Tensorflow Probability (at request of admins)

https://github.com/tensorflow/probability/issues/829

**System information** 
- OS Platform and Distribution : Windows 10
- TensorFlow installed from : - Binary
TensorFlow version: 2.2 Nightly
- Python version: 3.7.6
- CUDA/cuDNN version: - 10.1
- GPU model and memory:  Nvidia 2070 Max_Q

Using TFP 0.10.0-dev20200304, I have a standard call to create a positive semi-definite kernel e.g.

```
import tensorflow as tf
import tensorflow_probability as tfp
import numpy as np

amplitude = 1.0
length_scale = 1.0
kernel = tfp.math.psd_kernels.ExponentiatedQuadratic(amplitude, length_scale)
t_x = tf.Variable(np.array([[0.0, 0.25]]), dtype=tf.float32)
t_y = tf.Variable(np.array([[0.5, 0.5]]), dtype=tf.float32)
kernel.matrix(t_x, t_y)
```

This works apparently fine with all versions of TF-GPU upto and including GPU 2.2.0-dev20200302.

However, if I upgraded to TF-GPU 2.2.0-dev20200303 and now it crashes the following message :
Process finished with exit code -1073740940 (0xC0000374)

Seems like some incompatibility has been introduced with last nights build.

**Comment by ravikyram** [comment]
@oracle3001 
Can you try running the code in latest -tf-nightly 2.2.0-dev20200304version? Issue seemed to be fixed, kindly find the [gist of colab ](https://colab.sandbox.google.com/gist/ravikyram/2fc4071083b91e0991695f16d4b8d11d/untitled704.ipynb)for the same.Thanks!

**Comment by oracle3001** [comment]
Yes, that has fixed the issue. Thank you.
