### ISSUE TITLE
tf-nightly-gpu 1.15.0.dev20190729 is not found

### ISSUE THREAD

**Issue by loricrotser** [tensorflow/tensorflow#37317]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Google Colabs
- TensorFlow version: 1.15.0.dev20190729

**Describe the problem**

The tf-nightly-gpu==1.15.0.dev20190729 build appears to be missing.  We are releasing our tutorials next week for the summit using this build as listed in google colabs, but we can no longer install. Errors are listed below.  

Example is here: 
https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/micro/examples/micro_speech/train_speech_model.ipynb

**Provide the exact sequence of commands / steps that you executed before running into the problem**

The command in the google colab is as follows: 
# Replace Colab's default TensorFlow install with a more recent
# build that contains the operations that are needed for training
!pip uninstall -y tensorflow tensorflow_estimator tensorboard
!pip install -q tf-estimator-nightly==1.14.0.dev2019072901 tf-nightly-gpu==1.15.0.dev20190729

Output is: 
ERROR: Could not find a version that satisfies the requirement tf-nightly-gpu==1.15.0.dev20190729 (from versions: 2.2.0.dev20200201, 2.2.0.dev20200202, 2.2.0.dev20200203, 2.2.0.dev20200204, 2.2.0.dev20200205, 2.2.0.dev20200206, 2.2.0.dev20200207, 2.2.0.dev20200208, 2.2.0.dev20200210, 2.2.0.dev20200211, 2.2.0.dev20200212, 2.2.0.dev20200215, 2.2.0.dev20200216, 2.2.0.dev20200217, 2.2.0.dev20200218, 2.2.0.dev20200226, 2.2.0.dev20200227, 2.2.0.dev20200228, 2.2.0.dev20200229, 2.2.0.dev20200301, 2.2.0.dev20200302, 2.2.0.dev20200303, 2.2.0.dev20200304)
ERROR: No matching distribution found for tf-nightly-gpu==1.15.0.dev20190729

**Any other info / logs**
Can we get this build restored please? We do need TensorFlow prior to 2.0 - there's a dependency deprecation in the model conversion at the end of this tutorial that has (to my knowledge) not been addressed yet and we're on somewhat of a time crunch with that summit next week. 

Let me know if you need any more information! Thank you!

**Comment by av8ramit** [comment]
Hi @loricrotser unfortunately due to [storage limits on pypi](https://pypi.org/stats/) and our whls taking up nearly 1TB of space we were forced to remove them from pypi.

However as a courtesy I've made the internal archive link public so you can download that particular whl [here](https://storage.googleapis.com/tensorflow-nightly/prod/tensorflow/release/ubuntu_16/gpu_py35_full/nightly_release/3/20190729-010338/github/tensorflow/pip_pkg/tf_nightly_gpu-1.15.0.dev20190729-cp35-cp35m-manylinux2010_x86_64.whl).

Unfortunately I cannot make it available on pypi due to circumstances out of my control. Please see https://github.com/pypa/pypi-support/issues/224 for additional details. Hope this helps!

**Comment by coolioxlr** [comment]
Any chance to make the archive whl in Python3.6 instead since Google collab hosted runtimes is running Python3.6

**Comment by mihaimaruseac** [comment]
For 3.6, try [this link](https://storage.googleapis.com/tensorflow-nightly/prod/tensorflow/release/ubuntu_16/gpu_py36_full/nightly_release/3/20190729-010338/github/tensorflow/pip_pkg/tf_nightly_gpu-1.15.0.dev20190729-cp36-cp36m-manylinux2010_x86_64.whl) (just changed py35 to py36 and cp35 to cp36 throughout the link)

**Comment by coolioxlr** [comment]
> For 3.6, try [this link](https://storage.googleapis.com/tensorflow-nightly/prod/tensorflow/release/ubuntu_16/gpu_py36_full/nightly_release/3/20190729-010338/github/tensorflow/pip_pkg/tf_nightly_gpu-1.15.0.dev20190729-cp36-cp36m-manylinux2010_x86_64.whl) (just changed py35 to py36 and cp35 to cp36 throughout the link)

@mihaimaruseac file does not exist.  Got the following error.
<Error>
<Code>NoSuchKey</Code>
<Message>The specified key does not exist.</Message>
<Details>
No such object: tensorflow-nightly/prod/tensorflow/release/ubuntu_16/gpu_py36_full/nightly_release/3/20190729-010338/github/tensorflow/pip_pkg/tf_nightly_gpu-1.15.0.dev20190729-cp36-cp36m-manylinux2010_x86_64.whl
</Details>
</Error>

**Comment by av8ramit** [comment]
Does [this link](https://storage.googleapis.com/tensorflow-nightly/prod/tensorflow/release/ubuntu_16/gpu_py36_full/nightly_release/5/20190729-010352/github/tensorflow/pip_pkg/tf_nightly_gpu-1.15.0.dev20190729-cp36-cp36m-manylinux2010_x86_64.whl) work?

**Comment by mihaimaruseac** [comment]
Apologies, should have checked the link before posting after just a lexical replacement. The link @av8ramit posted seems to work here (i.e., I can download it)

**Comment by ppwwyyxx** [comment]
Thanks for providing links to the nightly archives! With the hint I was able to locate more archives by
```
gsutil ls gs://tensorflow-nightly/prod/tensorflow/release/ubuntu_16/gpu_py37_full/nightly_release/ 
```
this helps me a lot with debugging.
