### ISSUE TITLE
TPU software version nightly-2.x now gone and other versions don't work

### ISSUE THREAD

**Issue by mathemakitten** [tensorflow/tensorflow#37318]
**System information**

Have I written custom code (as opposed to using a stock
example script provided in TensorFlow): Yes
OS Platform and Distribution (e.g.,
Linux Ubuntu 16.04): Debian GNU/Linux 9.11
Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if
the issue happens on mobile device: N/A
TensorFlow installed from (source or
binary): binary
TensorFlow version (use command below): 2.2.0.dev20200303
Python version: Python 3.7.6
Bazel version (if compiling from source): N/A
GCC/Compiler version (if compiling from
source): N/A
CUDA/cuDNN version: N/A
GPU model and memory: N/A

**Describe the problem**

As of about 12PM EST today it seems that "nightly-2.x" for the TPU software version is no longer available under "Create a Cloud TPU." Unfortunately, this is the only version of the software which worked for my training code, and now nothing works. 

I also tried version 2.1, and I get this error: 

```tensorflow.python.framework.errors_impl.NotFoundError: 'ParallelInterleaveDatasetV3' is neither a type of a primitive operation nor a name of a function registered in binary running on n-de18ad71-w-0. One possible root cause is the client and server binaries are not built with the same version. Please make sure the operation or function is registered in the binary running in this process. [Op:DeleteRandomSeedGenerator]```

To be clear, I'm calling .interleave() in tf.data, not parallel_interleave, but I suppose it's really running ParallelInterleaveDatasetV3 under the hood.

Can you let me know what version of the TPU software we should be using to have the same functionality as the old nightly-2.x?

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by gowthamkpr** [comment]
You should use this version of tensorflow as shown [here](https://github.com/tensorflow/tensorflow/tree/r2.2/tensorflow/core/ops/compat/ops_history_v1). Thanks!

**Comment by gowthamkpr** [comment]
@mathemakitten Did it resolve your issue?

**Comment by mathemakitten** [comment]
Hi! I wound up flipping the TPU version over to the new nightly and it seems to work, thanks!
