### ISSUE TITLE
0.10.0rc0: tf.pack uses the wrong negative axis

### ISSUE THREAD

**Issue by jlowin** [tensorflow/tensorflow#3731]
When supplied a negative axis, tf.pack() actually operates on `(axis - 1)`. For example, providing `axis=-1` operates on the second-to-last axis, not the last axis.

This code illustrates the issue:

```python
import tensorflow as tf
import numpy as np

# 10 tensors with shape 2, 3, 4, 5
x = [tf.convert_to_tensor(np.zeros((2, 3, 4, 5)))] * 10

# pack along last axis explicitly
tf.pack(x, 4).get_shape().as_list() # [2, 3, 4, 5, 10]

# pack along last axis with negative axis, doesn't work
tf.pack(x, -1).get_shape().as_list() # [2, 3, 4, 10, 5]

# this doesn't match the behavior of unpack(), so packing/unpacking 
# along the same negative axis fails
len(tf.unpack(tf.pack(x, axis=-1), axis=-1)) == 10 # False

```
### Environment info
Operating System: 
macOS 10.11

Installed version of CUDA and cuDNN: 
(please attach the output of `ls -l /path/to/cuda/lib/libcud*`): 
N/A

If installed from binary pip package, provide:

1. Which pip package you installed.
https://storage.googleapis.com/tensorflow/mac/cpu/tensorflow-0.10.0rc0-py3-none-any.whl
2. The output from `python -c "import tensorflow; print(tensorflow.__version__)"`.
0.10.0rc0

**Comment by girving** [comment]
This looks like a bug in shape inference, actually.  What happens if you evaluate the tensors?

**Comment by jlowin** [comment]
@girving Yep, I think you're right:
```python
In [163]: tf.pack(x, 4).eval().shape
Out[163]: (2, 3, 4, 5, 10)

In [164]: tf.pack(x, -1).eval().shape
Out[164]: (2, 3, 4, 5, 10)

In [165]: tf.pack(x, -1)
Out[165]: <tf.Tensor 'pack_105:0' shape=(2, 3, 4, 10, 5) dtype=float64>
```
And indeed, trying to `eval` the unpack/pack combination at the end of my snippet raises a shape mismatch  error.

**Comment by yaroslavvb** [comment]
Shape inference there
<https://github.com/tensorflow/tensorflow/blob/2a10e469d70827ede21c0bb5d0a46aac97404d4c/tensorflow/python/ops/array_ops.py#L772>
doesn't have special logic for negative axis
input_shape.insert(op.get_attr("axis"), len(op.inputs))

So if axis is "-1", it just does "shapelist.insert(-1, stuff)"
It should probably mirror the logic from the C++ implementation
GetAxisForPackAndUnpack
https://github.com/tensorflow/tensorflow/blob/2a10e469d70827ede21c0bb5d0a46aac97404d4c/tensorflow/core/ops/array_ops.cc#L30

**Comment by girving** [comment]
I'm in the process of locating the Github account of the axis attr's author.

On the other hand, @cwhipkey: Are we far enough along that Python shape inference routines can go away?

**Comment by cwhipkey** [comment]
On Wed, Aug 10, 2016 at 1:12 PM, Geoffrey Irving <notifications@github.com>
wrote:

> I'm in the process of locating the Github account of the axis attr's
> author.
>
> On the other hand, @cwhipkey <https://github.com/cwhipkey>: Are we far
> enough along that Python shape inference routines can go away?
>

I think we are still several weeks away from removing the python shape
inference ones.

(@vrv fyi)

**Comment by girving** [comment]
Looks like the author is on vacation, so I'll fix it.

**Comment by girving** [comment]
Fixed internally, should push out soon.

**Comment by girving** [comment]
@jlowin Thank you for reporting!

**Comment by jlowin** [comment]
@girving thanks for fixing!
