### ISSUE TITLE
partial_run, feed placeholder already been fed

### ISSUE THREAD

**Issue by zeis** [tensorflow/tensorflow#3732]
The following code gives this error: 'InvalidArgumentError: The feed Placeholder:0 had already been fed.' I'm not sure if it is expected behaviour. 

```
import tensorflow as tf

sess = tf.Session()

a = tf.placeholder(tf.float32)
b = tf.placeholder(tf.float32)
c = tf.placeholder(tf.float32)
r1 = tf.add(a, b)
r2 = tf.mul(a, c)
r3 = tf.sub(r1, r2)

h = sess.partial_run_setup([r1, r2, r3], [a, b, c])
res1 = sess.partial_run(h, r1, feed_dict={a: 1, b: 2})
res2 = sess.partial_run(h, r2, feed_dict={a: 2, c: 3})
res3 = sess.partial_run(h, r3)
```

I get the error both on version '0.9.0' and on a yesterday's GitHub snapshot.

**Comment by girving** [comment]
Please ask questions like this on StackOverflow.  In this case, the problem is caused by feeding the same placeholder twice, as the error message indicates.
