### ISSUE TITLE
Cannot break while iterating over tensorflow dataset created using `tf.data.Dataset.from_generator`

### ISSUE THREAD

**Issue by SpikingNeuron** [tensorflow/tensorflow#37324]
**System information** 
- Have I written custom code (as opposed to using a stock
example script provided in TensorFlow): 
Yes
- OS Platform and Distribution (e.g.,
Windows 10
- TensorFlow installed from 
binary
- Tensorflow Version:
2.1

**Describe the current behavior**
The `tensorflow` dataset created from the generator function cannot be used with `break` inside the for loop. On the other hand, the datasets created without a generator do break gracefully. The error `tf.errors.CancelledError` is raised because of cancellation i.e. there is a `break` statement inside for loop.

**Describe the expected behavior**
The tensorflow dataset created using from_generator should exit gracefully when we break the for loop.

**Standalone code to reproduce the issue** 

See the code below:
```python
import numpy as np
import tensorflow as tf


def gen():
    while True:
        yield np.zeros(10, dtype=np.int32)


ds_without_gen = tf.data.Dataset.from_tensor_slices(
    [np.zeros(10, dtype=np.int32)]
).repeat()

ds_from_gen = tf.data.Dataset.from_generator(
    generator=gen, output_types=np.int32
)


# this works normally with break statement
print(">>>>>>>>> ds_without_gen")
for r in ds_without_gen.as_numpy_iterator():
    print(r)
    break


# this does work but a error is thrown by tensorflow as below
#    W tensorflow/core/kernels/data/generator_dataset_op.cc:103]
#    Error occurred when finalizing GeneratorDataset iterator:
#    Cancelled: Operation was cancelled
print(">>>>>>>>> ds_from_gen")
for r in ds_from_gen.as_numpy_iterator():
    print(r)
    break

```

The output is:
```txt
2020-03-04 17:39:29.472521: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2020-03-04 17:39:32.463827: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'nvcuda.dll'; dlerror: nvcuda.dll not found
2020-03-04 17:39:32.464110: E tensorflow/stream_executor/cuda/cuda_driver.cc:351] failed call to cuInit: UNKNOWN ERROR (303)
2020-03-04 17:39:32.469124: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:169] retrieving CUDA diagnostic information for host: NXL23343
2020-03-04 17:39:32.469517: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:176] hostname: NXL23343
2020-03-04 17:39:32.469969: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
 ds_without_gen
[0 0 0 0 0 0 0 0 0 0]
 ds_from_gen
[0 0 0 0 0 0 0 0 0 0]
2020-03-04 17:39:32.528149: W tensorflow/core/kernels/data/generator_dataset_op.cc:103] Error occurred when finalizing GeneratorDataset iterator: Cancelled: Operation was cancelled
```

**Comment by amahendrakar** [comment]
@SpikingNeuron,
I tried to reproduce the issue but did not face any warnings and errors. Please find the Gist [here](https://colab.sandbox.google.com/gist/amahendrakar/af1ab144bf9ba0a7ce77b7f0c8967199/37324.ipynb). Thanks!

**Comment by SpikingNeuron** [comment]
@amahendrakar Please try in command prompt or terminal with local python installation. The jupyter-notebook might be changing the behavior of the debugger.

This is the error I get
```txt
W tensorflow/core/kernels/data/generator_dataset_op.cc:103] Error occurred when finalizing GeneratorDataset iterator: Cancelled: Operation was cancelled
```
I realized it is not an error but a warning. The message indicates it as error but the `W` tag at the start indicates that it is a warning.

I assume if I ignore the warning I will be safe. 

Is this warning a critical thing? Should I avoid using break??

**Comment by amahendrakar** [comment]
@SpikingNeuron,
Running it on a local machine gives the same output. Please find the screenshot attached to this message.
![37324 output](https://user-images.githubusercontent.com/57165142/76093385-e22df180-5fe6-11ea-8108-27e6d22d7f38.png)
 
Warnings are generally used to alerts programmers of future deprecation or obsolete methods. In this case, unless you face errors you can continue using break as it is just a warning.

**Comment by SpikingNeuron** [comment]
But I do get a warning. Now I have suppressed it.  Note that I am using binaries built for windows.

![image](https://user-images.githubusercontent.com/2289914/76101658-11d0ff80-5fcf-11ea-8b3d-7efd43dba4c6.png)

**Comment by SpikingNeuron** [comment]
Yes I noticed it late that it is warning as the message clearly says that it is an error but the start tag is `W`

**Comment by SpikingNeuron** [comment]
Yes I noticed it late that it is warning as the message clearly says that it is an error but the start tag is `W`
