### ISSUE TITLE
tf.ConfigProto() and tf.estimator.RunConfig  conflict

### ISSUE THREAD

**Issue by Ljl-Jdsk** [tensorflow/tensorflow#37325]
I want to use “tf.ConfigProto()” to set the GPU to grow dynamically, and I want to use “ tf.estimator.RunConfig ” to set the number of checkpoints.

config = tf.ConfigProto()
config.gpu_options.allow_growth = True

config = tf.estimator.RunConfig(keep_checkpoint_max = 10)
with tf.train.MonitoredTrainingSession(,,,config=config)
How can I achieve my goal with only one config？

extremely grateful !
Thanks!

**Comment by ravikyram** [comment]
Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version. 
Please, fill [the Github new issue template](https://github.com/tensorflow/tensorflow/issues/new/choose).

**Comment by Ljl-Jdsk** [comment]
TensorFlow version: 1.10
operating system: linux, centos7
architecture: multiple GPUs on a single machine, Use parameter server in the future

**Comment by ymodak** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.
 Thanks!
