### ISSUE TITLE
Broken Link Inside the Friction Log Google Doc

### ISSUE THREAD

**Issue by coreyching** [tensorflow/tensorflow#37327]
Thank you for submitting a TensorFlow documentation issue. Per our GitHub
policy, we only address code/doc bugs, performance issues, feature requests, and
build/installation issues on GitHub.

The TensorFlow docs are open source! To get involved, read the documentation
contributor guide: https://www.tensorflow.org/community/contribute/docs

## URL(s) with the issue / ## Description of issue (what needs changing):

Inside the Friction Log Document: https://docs.google.com/document/d/1HVG3t-mgGZKU4iMeguTWGejbnQ54qUTXwdCFkA5xHG0/edit

There is a broken link to the "Bug / Performance" template:
https://github.com/tensorflow/tensorflow/blob/master/.github/ISSUE_TEMPLATE/00-bug-performance-issue.md

### Correct links

I see there are two templates - 
**Performance:** https://github.com/tensorflow/tensorflow/issues/new?labels=type%3Aperformance&template=80-performance-issue.md

**Bug**: https://github.com/tensorflow/tensorflow/issues/new?labels=type%3Abug&template=00-bug-issue.md

The friction log should update these links in the google doc,

**Comment by Saduf2019** [comment]
@coreyching 
please share the source of this document, the link from tensorflow or github where this document is present.

**Comment by Saduf2019** [comment]
@coreyching 
please confirm if the source is from [this link](
https://github.com/tensorflow/community/blob/master/sigs/build/tensorflow-testing.md)

**Comment by Saduf2019** [comment]
@coreyching
please update on the above comment.

**Comment by Saduf2019** [comment]
@coreyching
As there is a pr to monitor your request, moving this issue to closed status
