### ISSUE TITLE
Count number of times `tf.function` is traced

### ISSUE THREAD

**Issue by ammirato** [tensorflow/tensorflow#37323]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using): 2.1
- Are you willing to contribute it (Yes/No): No

**Describe the feature and the current behavior/state.**
I would like to be able to check, inside a function wrapped by `tf.function`, when this function is being retraced. This is useful for testing my functions are compatible with `tf.function`, and will make use of the speed up (and not just make a new graph every time they are called).

An example, with the requested feature would be inserted in `REQUEST`:

```
import my_function
@pytest.mark.unit
@pytest.mark.parametrize('use_tf_function', [True, False])
def test_my_function(use_tf_function):

    def test(arg1, arg2):
        # REQUEST: Check to make sure this is not being retraced many times.
        return my_function(arg1, arg2)

    # Sometimes test in Eager mode for debugging, sometimes test in graph mode.
    test_func = test
    if use_tf_function:
        test_func = tf.function(test_func)

    #####Test 1
    arg1, arg2 = #some setup stuff
    test_func(arg1, arg2)  # create the graph (tracing happens).
    results = test_func(arg1, arg2)  # hopefully tracing does not happen a second time.
    assert results

    #####Test 2
    arg4, arg3 = #some setup stuff
    results = test_func(arg3, arg4)  # hopefully tracing does not happen again (if the inputs are tensors and the shapes do not change)
    assert results
```

**Will this change the current api? How?**
I'm not sure, maybe just add a function, maybe it already exists.

**Who will benefit with this feature?**
Anyone debugging. 

**Any Other info.**

**Comment by ammirato** [comment]
One thing I could do is check `test_func._call_counter.get_tracing_count()`, but I don't like the use of a variable with `_` starting the name.

**Comment by mdanatg** [comment]
Indeed, you should avoid using private fields - they may change at any moment.

The easiest and most robust way is to use a global Python counter, like so:

```
>>> trace_count = 0
>>> @tf.function
>>> def f(x):
...   global trace_count
...   trace_count += 1
...   # the rest of your code
>>> trace_count
0
>>> f(tf.constant(1))
>>> trace_count
1
>>> f(tf.constant(2))
>>> trace_count
1
>>> f(tf.constant([1, 2]))
>>> trace_count
2
```

**Comment by ammirato** [comment]
This only works for certain cases, and doesn't seem scalable to every function everywhere. I'd have to have a different global variable for each function. 

What if my function is writting in one file, and I wrap it in `tf.function` in another file? I can't use a global variable as descirbed above to test the trace count in the caller code, which is where I would like to test.

**Comment by mdanatg** [comment]
I missed that this was a feature request. Sounds reasonable to me.

**Comment by SSaishruthi** [comment]
Any suggestions on how this can be implemented? I would like to give a try if we have any pointers

**Comment by ammirato** [comment]
A simple solution would be to just add a public method to the `Function` class, that returns `self._call_counter.get_tracing_count()`.

 I'm not sure of the implications of this though. I'm sure there is a reason `_call_counter` is a private field, exposing its state might not be great.

**Comment by mdanatg** [comment]
Fields are kept private by default, and we only expose public methods if there is a need for one. This helps keep the API clean - once a method is made public, it's extremely difficult to remove it. So for now, I recommend naming the method/property with the `experimental_` prefix to control its adoption.

**Comment by qaishk** [comment]
I'd like to give this a shot. Can I submit a PR for this?

**Comment by SSaishruthi** [comment]
@ammirato @mdanatg Thanks. Will work on this.

**Comment by kulsoomzahra** [comment]
can i work on this? @ammirato

**Comment by kulsoomzahra** [comment]
can i work on this?@ammirato

**Comment by Ankuraxz** [comment]
@ammirato, can I work on this and submit a PR

**Comment by HH95** [comment]
How about a static variable in the function class?

**Comment by LGTcoder** [comment]
import my_function
@pytest.mark.unit
@pytest.mark.parametrize('use_tf_function', [True, False])
def test_my_function(use_tf_function):

    def test(arg1, arg2):
        # REQUEST: Check to make sure this is not being retraced many times.
        return my_function(arg1, arg2)

    # Sometimes test in Eager mode for debugging, sometimes test in graph mode.
    test_func = test
    if use_tf_function:
        test_func = tf.function(test_func)

    #####Test 1
    arg1, arg2 = #some setup stuff
    test_func(arg1, arg2)  # create the graph (tracing happens).
    results = test_func(arg1, arg2)  # hopefully tracing does not happen a second time.
    assert results

    #####Test 2
    arg4, arg3 = #some setup stuff
    results = test_func(arg3, arg4)  # hopefully tracing does not happen again (if the inputs are tensors and the shapes do not change)
    assert results
#is it right....?

**Comment by PratsBhatt** [comment]
Is this issue closed? or is it open for contributions? I see that the PR is closed. Thanks

**Comment by mihaimaruseac** [comment]
PR has been closed in unmerged state

**Comment by aicam** [comment]
If I got the issue correctly you want to save the state of your graph so you can use [lru cache](https://docs.python.org/3/library/functools.html#lru_cache), I tested both inside tensorflow library and only combination of @tf.function and @lru_cache in my main.py and both worked fine but actually i was testing a simple graph with one plus, I don't know the side effects

**Comment by LGTcoder** [comment]
if hv mentioned the right one......

**Comment by RishiDharshan** [comment]
HI I am new to the open source community ,
I would like to contribute to this project,
can anyone please point me to the right direction to contribute to this project

**Comment by RamBITS-AI** [comment]
> HI I am new to the open source community ,
> I would like to contribute to this project,
> can anyone please point me to the right direction to contribute to this project

I too am new... can anyone help by letting us know on how to pick issues to work on and start contributing? I mean can multiple people work on the same issue or does someone lock or book an issue to start work.

**Comment by gilad83** [comment]
Hi is this issue still open? I want to work on it.

**Comment by mdanatg** [comment]
Looks like there's a PR in progress.

**Comment by devratapuri** [comment]
I am new to this can anyone tell me from where to begin.

**Comment by sauraj12** [comment]
This is my first issue... I am working on it...if anyone got some information related to this issue please let me know

**Comment by imrahul361** [comment]
is anyone working on this issue? @mihaimaruseac @ammirato

**Comment by mihaimaruseac** [comment]
There is #43366

**Comment by yogeshpatnaik** [comment]
hi  i would like to work on the issue , can you  suggest me ways to get started

**Comment by Ilya-Sakharov** [comment]
Have you fixed the issue?

I think, you should try that public method to the Function class.

self._`call_counter.get_tracing_count()`

**Comment by mihaimaruseac** [comment]
#43366 landed, so this is fixed.
