### ISSUE TITLE
Compilation error:  reduction_ops_gpu_complex64.cu.pic.o' was not created

### ISSUE THREAD

**Issue by zhangwujun666** [tensorflow/tensorflow#37320]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):macOS 10.13.6
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): binary
- TensorFlow version:1.5
- Python version:3.6
- Installed using virtualenv? pip? conda?: conda
- Bazel version (if compiling from source):0.9
- GCC/Compiler version (if compiling from source):9.0
- CUDA/cuDNN version:9.2/7.2.1
- GPU model and memory:GTX1070

**Describe the problem**

```
ERROR: /Users/john/Downloads/tensorflow/tensorflow/core/kernels/BUILD:2709:1: output 'tensorflow/core/kernels/_objs/reduction_ops_gpu/tensorflow/core/kernels/reduction_ops_gpu_complex64.cu.pic.o' was not created
ERROR: /Users/john/Downloads/tensorflow/tensorflow/core/kernels/BUILD:2709:1: not all outputs were created or valid
Target //tensorflow/tools/pip_package:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 2120.730s, Critical Path: 166.64s
FAILED: Build did NOT complete successfully

```

**Provide the exact sequence of commands / steps that you executed before running into the problem**

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by Saduf2019** [comment]
@zhangwujun666 
Provide the exact sequence of commands / steps that you executed before running into the problem, could you please confirm if the tensorflow version is 1.15 or 1.5

**Comment by zhangwujun666** [comment]
Hi, there, I just followed this instruction to implement the installation:

> https://gist.github.com/geekcui/d0800d62e377e0103b1cc2b889ed1128

and the version of Tensorflow is following:
`git` clone https://github.com/tensorflow/tensorflow.git -b v1.5.0
After I did this command to build the file:
`bazel build --config=cuda --config=opt --action_env PATH --action_env LD_LIBRARY_PATH --action_env DYLD_LIBRARY_PATH //tensorflow/tools/pip_package:build_pip_package`

the Error shows:

```
ERROR: /Users/john/Downloads/tensorflow/tensorflow/core/kernels/BUILD:2709:1: output 'tensorflow/core/kernels/_objs/reduction_ops_gpu/tensorflow/core/kernels/reduction_ops_gpu_complex64.cu.pic.o' was not created
ERROR: /Users/john/Downloads/tensorflow/tensorflow/core/kernels/BUILD:2709:1: not all outputs were created or valid
Target //tensorflow/tools/pip_package:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 2120.730s, Critical Path: 166.64s
FAILED: Build did NOT complete successfully
```

**Comment by Saduf2019** [comment]
@zhangwujun666 
I see an old issue with similar pattern as it has the similar configuration as you have mentioned, could you please downgrade your CUDA version and try. please refer to [this link](https://github.com/tensorflow/tensorflow/issues/19646) and let us know if it helps.

**Comment by zhangwujun666** [comment]
Thanks!  works well for me !!
