### ISSUE TITLE
Tensorflow fails in building `GRU` models in some cases.

### ISSUE THREAD

**Issue by shiningrain** [tensorflow/tensorflow#37336]
**System information**  
- Have I written custom code (as opposed to using example directory):  
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):  Windows 10
- TensorFlow backend (yes / no):  yes
- TensorFlow version:  1.15.0
- Python version:  3.6.9
- CUDA/cuDNN version:  -
- GPU model and memory:  -

**Describe the current behavior**  

**When I directly build a model with layer `GRU`on Tensorflow, I get some variable multiplication errors**, as shown below (raised in `tensorflow_core\python\ops\resource_variable_ops.py line 1229`).  **The error reveals unsatisfactory implementation on Tensorflow in supporting variable multiplication.** 

  ```
<class 'RuntimeError'>, RuntimeError('Variable *= value not supported. Use var.assign(var * value) to modify the variable or var = var * value to get a new Tensor object.',), <traceback object at 0x00000240961ED908>),
  ```

**Similar issues also happen in `LSTM` and `SimpleRNN`**.  For detailed parameters of `GRU`, you can refer to the following code snippet.

## Key insights

The error indicates that **the variable multiplication with format `Variable *= value` is not well supported on TensorFlow. It should be extended to full mode to conduct multiplication.  This caused Tensorflow to be unable to build the model.** 

## Code to reproduce the issue

``` python
import numpy as np
import keras.layers as L
from keras.engine import Model, Input

## Using Tensorflow as Keras backend.
## Input dtype default is float32

#GRU kwargs
kwargs = {
	'units': 2,
  	'dropout': 0.20430343923336958,
  	'recurrent_dropout': 0.7597739154146002,
  	'implementation': 2,
    'reset_after': True,
    'use_bias': True,
    'return_sequences': False,
    'return_state': False,
    'go_backwards': False,
    'stateful': True,
    'unroll': False
}

# SimpleRNN kwargs
# kwargs = {
#		'units': 2,
#  	'dropout': 0.9030407578803185,
#  	'use_bias': True,
#  	'recurrent_dropout': 0.8988069898639027,
#  	'return_sequences': False,
#  	'return_state': False,
#  	'go_backwards': True,
#  	'stateful': True,
#  	'unroll': True
#}


input = (10 * np.random.random((2,10,8)))
layer = L.recurrent.GRU(**kwargs)
#layer = L.recurrent.SimpleRNN(**kwargs)
x = Input(batch_shape=input.shape)
y = layer(x)
bk_model = Model(x, y)
print('finish')
```

**Comment by gadagashwini** [comment]
@shiningrain, I tried replicating the reported issue. I didn't receive an error. Please take a look at the gist [here](https://colab.sandbox.google.com/gist/Saduf2019/6351f70f3c49499cd34265d487664bad/untitled419.ipynb). Thanks!

**Comment by shiningrain** [comment]
> @shiningrain, I tried replicating the reported issue. I didn't receive an error. Please take a look at the gist [here](https://colab.sandbox.google.com/gist/Saduf2019/6351f70f3c49499cd34265d487664bad/untitled419.ipynb). Thanks!

Hi! @gadagashwini 
Thank for your help!
I have read your code and it did run well in colab. But when I try to run the same code on my PC, the error I described above will still arise.(Shown in the following pictures.) This really confuses me.

![pic1](https://user-images.githubusercontent.com/46860123/75994629-3927be00-5f36-11ea-8df1-ff10d225b232.jpg)
![pic2](https://user-images.githubusercontent.com/46860123/75995739-d2a39f80-5f37-11ea-94dd-db4da4000a88.jpg)


The environment in the 1st picture:
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- Tensorflow backend (yes / no): yes
- Tensorflow version：1.15.0-cpu
- Keras version: 2.3.1
- Python version: 3.6.9

The environment in the 1st picture:
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu18.04
- Tensorflow backend (yes / no): yes
- Tensorflow version：1.14.0-GPU
- Keras version: 2.3.1
- Python version: 3.6.8
- CUDA/cuDNN version: Cuda 9.0
- GPU model and memory: TITAN V

Hope the above information can help with this problem.
Thanks again for your help!

**Comment by gadagashwini** [comment]
@shiningrain, Can you try with changing import statement as 
```
import numpy as np
import tensorflow.keras.layers as L
from tensorflow.keras import Model, Input
```
Let us know how it works. Thanks

**Comment by shiningrain** [comment]
> @shiningrain, Can you try with changing import statement as
> 
> ```
> import numpy as np
> import tensorflow.keras.layers as L
> from tensorflow.keras import Model, Input
> ```
> 
> Let us know how it works. Thanks

Thanks for your help!
I have changed the import statement and **it still raises the same error**, shown as the following picture.
![pic3](https://user-images.githubusercontent.com/46860123/76070093-ef3ee680-5fce-11ea-9801-23729218dd18.jpg)

**Comment by ymodak** [comment]
@shiningrain Can you try updating keras version ? The colab hosts Keras Version: 2.2.5

**Comment by shiningrain** [comment]
> @shiningrain Can you try updating keras version ? The colab hosts Keras Version: 2.2.5

Hello! 
Thanks for your help!.
The Keras version led to these errors is 2.3.1, which was also shown in my last comment.
![pic4](https://user-images.githubusercontent.com/46860123/76266044-306e1980-62a1-11ea-9791-e416ef4123cd.jpg)

I also tried Keras version 2.2.4 in the following pictures and the problem didn't seem to disappear 
![pic5](https://user-images.githubusercontent.com/46860123/76266140-7e831d00-62a1-11ea-8e59-358dec4b14e2.jpg)
![pic6](https://user-images.githubusercontent.com/46860123/76266144-804ce080-62a1-11ea-983c-456949be3f24.png)

Thank you again for your help.

**Comment by ymodak** [comment]
Can you please change your imports to `tensorflow.keras` rather than 'keras`?
```python
import numpy as np
import tensorflow as tf
import tensorflow.keras.layers as L
from tensorflow.keras import Model, Input
```

**Comment by shiningrain** [comment]
> Can you please change your imports to `tensorflow.keras` rather than `keras`?
> 
> ```python
> import numpy as np
> import tensorflow as tf
> import tensorflow.keras.layers as L
> from tensorflow.keras import Model, Input
> ```

Hello! Thanks for your help!
Your suggestion is the same as gadagashwini 's. I have tried this replacement and got a same error. You find it in the  previous comment in this page.

**Comment by qlzh727** [comment]
Hi @shiningrain, I wasn't able to reproduce the error as well. Even I could, we are not going to fix and create a new release for Tensorflow 1.15 since it is frozen.

I would suggest u to try the latest Tensorflow stable release or nightly and see if your code works or not. Feel free to reopen the issue if you still encounter the error with latest releases.
