### ISSUE TITLE
Improve the TFDS Getting Started Documentation 

### ISSUE THREAD

**Issue by coreyching** [tensorflow/tensorflow#37330]
## URL(s) with the issue:
https://www.tensorflow.org/datasets/overview

## Description of issue (what needs changing):

 😀I completed step 1 and  went to “https://www.tensorflow.org/datasets/overview” to get started with TFDS. I launched the code lab to continue with the overview. The code lab is a great option to easily run python and tensorflow! 

😑- I completed the first command to install tensorflow and tensorflow-datasets
![image](https://user-images.githubusercontent.com/6283150/75946296-9433b500-5e51-11ea-921e-f44a6fc1573e.png)

The download ran but it was not clear which version of tensorflow was downloaded. The reason I was confused and wanted to know which version was installed is the disclaimer above states version >=1.15 is required.
😑- In the second command, I received an error message after running the python script.
![image](https://user-images.githubusercontent.com/6283150/75946322-a44b9480-5e51-11ea-8874-51a4863093ae.png)

I was not clear if this was just a warning message, or an error due to my current tensorflow version. 

😀Step 2 was delightful!
![image](https://user-images.githubusercontent.com/6283150/75946336-aca3cf80-5e51-11ea-949a-0ca03348d768.png)

Adding in a disclaimer to include citations is great! 😑However, why is it after the download step? This seems out of place and disrupts the developer workflow. 

Next was step 3 to initiate eager execution.
😑Without a baseline on what EE is, I felt required to read the eager execution page before I could move forward. It’s frustrating when a developer guide links out to other documentation, or I feel compelled to read the other pages, because it causes disruption in grasping one concept at a time. This frustration can be a “drop off” point for developers trying to onboard Tensorflow.

![image](https://user-images.githubusercontent.com/6283150/75946528-35227000-5e52-11ea-9312-09405b8e3043.png)

Enable_V2_Behavior is the command run after asking the user to enable eager execution. Why is that? (After reading the eager execution documentation this was clear, but it took time to dig for this info).

😡Step 5 understanding what the tf “load” function does is frustrating.
![image](https://user-images.githubusercontent.com/6283150/75946560-44092280-5e52-11ea-85be-ded98f6365c3.png)

😡I’m strongly encouraged to read the official TensorFlow guide which is over 30 pages of material. I am 5 steps down this getting started guide, and then sent to another page that will reasonably take 4+ focused hours to additionally complete. This is very frustrating when I am trying to just get an overview of tensorflow datasets.

😀Step 5 does a great job here showing an example directly in relation to the above paragraph on versioning! I’m delighted and can move on without needing to read the hyperlink. 
![image](https://user-images.githubusercontent.com/6283150/75946588-54b99880-5e52-11ea-8e80-6ec1f06b684e.png)

😑Step 7 is confusing since it states we can achieve the same output using the DatasetBuilder, but when you run the test it only outputs the ds_train variable, as opposed to building the graph. 
![image](https://user-images.githubusercontent.com/6283150/75946599-5be0a680-5e52-11ea-9cfd-37520abadae3.png)

### What should happen?

I have organized answers to the above friction points in the following groupings:

**Tensorflow Installation**
To identify which version of Tensorflow I installed I ran a grep command in the code lab to output the following:

![image](https://user-images.githubusercontent.com/6283150/75946716-bd087a00-5e52-11ea-95d3-c13f68c33df9.png)

Having something like this ^ output during installation will help users know what is downloaded and executed in the install command. 

**Eager Execution**

A simple way to clarify what eager execution is to write a one sentence definition in the guide. For example:

“TensorFlow's eager execution is an imperative programming environment that evaluates operations immediately, without building graphs: operations return concrete values instead of constructing a computational graph to run later.”

This way I have a quick understanding and don’t feel compelled to read the linked page which is a very long document! :)
I liken this to applications having a tooltip in consumer facing applications. Adding in quick non intrusive explanations to Respect the User keep your users engaged and on the same page. 

Additionally, adding in the following message to define the command, “enable_v2_behavior”, would help clarify that Eager Execution is enabled by default tensorflow 2. 

![image](https://user-images.githubusercontent.com/6283150/75946725-c560b500-5e52-11ea-9229-96f8b71dc895.png)

**Linking to the official guide for Tensorflow Datasets**
![image](https://user-images.githubusercontent.com/6283150/75946747-d3163a80-5e52-11ea-820b-a43d13bbbe76.png)

We need to Respect the User, and provide simplicity when on boarding someone new to TFDS. They have invested time to make it down to the 5th step. If it is imperative the user get a baseline understanding of the Tensorflow API first, then we should put the disclaimer at the top of the overview to go read the guide first before continuing. 

If it is not necessary, then we should summarize the API guide into 3-5 concise pillars of information that is required for the user to understand the rest of the overview. When the user completes the overview, we can encourage them to go deeper and read the rest of the guide. Similarly, an analogy is when loading a website you respect the user by building a light-weight modern site. Performant sites lazy load in images when they are needed to improve performance and minimize how much data your user needs to download, we should apply the same principles to information.  

**DatasetBuilder**
When introducing in the DatasetBuilder we should place this information right after Step 5 (calling .load), to show the two ways to load in datasets side by side. This way the user does not need to scroll back up the documentation and read before Step 6 (plotting the dataset).

**Comment by lamberta** [comment]
This was semi-recently updated. Can you check again, please? https://www.tensorflow.org/datasets/overview

**Comment by lamberta** [comment]
Also, that doc lives here: https://github.com/tensorflow/datasets/blob/master/docs/overview.ipynb
You can send a pull request or issue to the tensorflow/datasets repo. Thanks

**Comment by ashutosh1919** [comment]
@coreyching  and @lamberta , I have raised PR [#1633](https://github.com/tensorflow/datasets/pull/1633) to resolve this issue. Please check PR and also suggest changes if needed.

**Comment by Conchylicultor** [comment]
Thanks again for all the valuable feedbacks. For reference, we've done a major update of the documentation introduction.
https://www.tensorflow.org/datasets/overview

I think it fixes many of the pain points highlighted here. Let us know if there are other things which should be fixed. We're also in the process of refactoring the other doc (adding a new dataset & split API)

**Comment by nikitamaia** [comment]
Closing this issue based on the above comments and changes to the datasets overview page.
