### ISSUE TITLE
TF2.1 cannot save model trained by distribution strategy while TF2.0 could do

### ISSUE THREAD

**Issue by JiayuanSternLi** [tensorflow/tensorflow#37342]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information** 
- Have I written custom code (as opposed to using a stock
example script provided in TensorFlow): 
Yes
- OS Platform and Distribution (e.g.,
Linux Ubuntu 16.04): 
Ubuntu 16.04

- TensorFlow installed from (source or
binary): - TensorFlow version (use command below): 
TF2.1 and TF2.0

- Python version: - Bazel
version (if compiling from source):
From source

- CUDA/cuDNN version: - GPU model and memory:
CUDA 10.1

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
The model trained under distribution strategy could not be saved in TF2.1 while it could be saved in TF2.0.

**Describe the expected behavior**

**Standalone code to reproduce the issue** 
The exapmle code I copy from another issue [issue ](https://github.com/tensorflow/tensorflow/issues/36477):
```python
import tensorflow as tf

def build_and_compile_model():
    
    input = tf.keras.Input((20,))
    x = tf.keras.layers.BatchNormalization()(input)
    y = tf.keras.layers.Dense(2)
    
    model = tf.keras.Model(inputs=input, outputs=y)
    
    model.compile(
        loss=tf.keras.losses.sparse_categorical_crossentropy,
        optimizer=tf.keras.optimizers.SGD(learning_rate=0.001),
        metrics=['accuracy'])
    
    return model

strategy = tf.distribute.MirroredStrategy()
with strategy.scope():
    model = build_and_compile_model()
model.save('test', save_format='tf')
```

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.
![image](https://user-images.githubusercontent.com/33815430/75964388-1c719300-5f02-11ea-900b-9d7372607abe.png)
#https://github.com/tensorflow/tensorflow/issues/36477

**Comment by amahendrakar** [comment]
@JiayuanSternLi,
Could you please check if it works with the latest nightly version and let us know if it works? Thanks!

**Comment by JiayuanSternLi** [comment]
> with the latest nightly version and let us know if it works? Thanks!

Yup, tf2.2 is good now
