### ISSUE TITLE
Giving `name` attributes to `Graph` and `Session`

### ISSUE THREAD

**Issue by samjabrahams** [tensorflow/tensorflow#3735]
I wanted to gauge thoughts on adding a string `name` attribute to `Graph` and `Session` objects. Currently, there's no programmatic way to identify specific Graphs or Sessions from a generic handle. 

There's no mechanism to ensure unique graph/session names (unless I'm mistaken), but it should still be beneficial even without guaranteeing unique names. In a larger system that may be tossing around multiple sessions and graphs, it would be good to have a way to know what graph is being handled (or what family of graphs, if multiple graphs have the same name). The uses for this could also be extended out to TensorBoard, exporting graphs/models, etc.

Perhaps it would be better off being called `tag`, but I went with `name` to keep it consistent with current code.

Good idea, terrible idea, somewhere in the middle?

**Comment by girving** [comment]
I would suggest storing a dictionary mapping names to graphs.  Adding name attributes to `Graph` or `Session` would be poor coding style.
