### ISSUE TITLE
TF-TRT is slower than native-TF with 512*512 image

### ISSUE THREAD

**Issue by lxl910915** [tensorflow/tensorflow#37352]
**System information** 
- Have I written custom code (as opposed to using a stock
example script provided in TensorFlow):  [EAST ](https://github.com/argman/EAST)model
- OS Platform and Distribution (e.g.,
Linux Ubuntu 16.04):  Ubuntu 16.04
- TensorFlow installed from (source or
binary): - TensorFlow version (use command below):  1.15.0
- Python version: - Bazel
version (if compiling from source): 0.24.1
- GCC/Compiler version (if compiling from
source): gcc-7.1
- CUDA/cuDNN version: 10.0/7.6.5
- GPU model and memory:Default mode, Tesla V100-sxm2-16gb GPU

**Describe the current behavior**
We test [EAST ](https://github.com/argman/EAST)model using TF-TRT and native-TF on GPU V100.
If image size is 256 * 256，for one inference TF-TRT takes 3ms and native-TF takes 4ms.
If image size is 512 * 512，for one inference TF-TRT takes 5ms and native-TF takes 4.5ms.
If image size is 1024 * 1024，for one inference TF-TRT takes 40ms and native-TF takes 25ms.

**Standalone code to reproduce the issue** 
We upload our [saved_model.pb](https://github.com/lxl910915/Test/blob/master/SavedModel-1024-1024.tar.gz).
Untar it to /tmp/SavedModel-1024-1024.
For running saved_model, the shell is CUDA_VISIBLE_DEVICES=0 python [east_sm.py](https://github.com/lxl910915/Test/blob/master/east_sm.py). One inference costs 25ms.
For running tf-trt, the shell is CUDA_VISIBLE_DEVICES=0 python [east_tftrt.py](https://github.com/lxl910915/Test/blob/master/east_tftrt.py). One inference costs 40ms.

Then, we use nvprof to prof tf-trt `CUDA_VISIBLE_DEVICES=0 nvprof python east_tftrt.py`, and we find that genericReformat::copyPackedKernel occupy 60% time.

```
==33264== NVTX result:
==33264== Warning: Found 198911 invalid range marker(s)
==33264==   Thread "<unnamed>" (id = 268433152)
==33264==     Domain "TensorRT"
==33264==       Range "<unnamed>"
            Type  Time(%)      Time     Calls       Avg       Min       Max  Name
          Range:  100.00%  1.57525s     72779  21.644us  7.3260us  850.74us  <unnamed>
 GPU activities:   58.34%  4.46830s     33826  132.10us  2.3030us  2.0179ms  void genericReformat::copyPackedKernel<float, float, bool=0, bool=1, genericReformat::IdentityCoordMapper<int=4>, int=4>(unsigned int, unsigned int, void const *, genericReformat::ArrayN<genericReformat::IdentityCoordMapper<int=4>>, genericReformat::ArrayNWithReducedDivisors<genericReformat::IdentityCoordMapper<int=4>>, genericReformat::ArrayN, int, int, int, float const *, void*, genericReformat::ArrayN, genericReformat::ArrayNWithReducedDivisors, genericReformat::ArrayNWithReducedDivisors, genericReformat::ArrayN, int, int, int, float const , int=4)
                   13.70%  1.04961s      5675  184.95us  53.311us  385.95us  trt_volta_scudnn_128x64_relu_interior_nn_v1
                    9.91%  759.32ms      4597  165.18us  55.007us  206.62us  trt_volta_scudnn_winograd_128x128_ldg1_ldg4_relu_tile148t_nt_v1
```
The detal log is [here](https://github.com/lxl910915/Test/blob/master/log.tftrt.op3).

We change minimum_segment_size value:
minimum_segment_size = 200, no TRTEngineop are generated, inference time is 32ms.
minimum_segment_size = 20, inference time is 32ms.
minimum_segment_size = 10, inference time is 40ms.
minimum_segment_size = 3, inference time is 47ms.

But copyPackedKernel takes 60% time in above cases. Then we prof the 256 * 256 image, copyPackedKernel only takes 20% times.
```
==30031== NVTX result:
==30031== Warning: Found 110489 invalid range marker(s)
==30031==   Thread "<unnamed>" (id = 3548374784)
==30031==     Domain "TensorRT"
==30031==       Range "<unnamed>"
            Type  Time(%)      Time     Calls       Avg       Min       Max  Name
          Range:  100.00%  1.62226s     54141  29.963us  7.5820us  880.76us  <unnamed>
 GPU activities:   25.34%  103.18ms      3008  34.301us  7.0400us  152.83us  void cudnn::detail::implicit_convolve_sgemm<float, float, int=1024, int=5, int=5, int=3, int=3, int=3, int=1, bool=1, bool=0, bool=1>(int, int, int, float const *, int, float*, cudnn::detail::implicit_convolve_sgemm<float, float, int=1024, int=5, int=5, int=3, int=3, int=3, int=1, bool=1, bool=0, bool=1>*, kernel_conv_params, int, float, float, int, float, float, int, int)
                   22.51%  91.647ms      2313  39.622us  10.560us  121.47us  trt_volta_scudnn_winograd_128x128_ldg1_ldg4_relu_tile148t_nt_v1
                   21.18%  86.217ms     22902  3.7640us  1.5360us  16.640us  void genericReformat::copyPackedKernel<float, float, bool=0, bool=1, genericReformat::IdentityCoordMapper<int=4>, int=4>(unsigned int, unsigned int, void const *, genericReformat::ArrayN<genericReformat::IdentityCoordMapper<int=4>>, genericReformat::ArrayNWithReducedDivisors<genericReformat::IdentityCoordMapper<int=4>>, genericReformat::ArrayN, int, int, int, float const *, void*, genericReformat::ArrayN, genericReformat::ArrayNWithReducedDivisors, genericReformat::ArrayNWithReducedDivisors, genericReformat::ArrayN, int, int, int, float const , int=4)
                    8.89%  36.172ms      2626  13.774us  8.4160us  19.840us  void fused::fusedConvolutionReluKernel<fused::SrcChwcPtr_FltTex_Reader<float, int=1, int=1, int=4, int=1>, fused::KpqkPtrWriter<float, int=1, int=1, int=1>, float, float, int=4, int=8, int=8, int=1, int=1, int=1, int=1>(fused::ConvolutionParams<floatSrcType, int=4, int=1Type>)
```

**Comment by edric1261234** [comment]
same issue!

**Comment by sanjoy** [comment]
CC @tfeher @bixia1 @DEKHTIARJonathan

**Comment by snowpeakz** [comment]
same issue +1

**Comment by lxl910915** [comment]
any ideas? @bixia1 @sanjoy

**Comment by bixia1** [comment]
This is the same as https://github.com/tensorflow/tensorrt/issues/183 and MattConley is working on it.

**Comment by srihari-humbarwadi** [comment]
same issue +1

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.
