### ISSUE TITLE
Raspberry Pi 3: ERROR: tensorflow-2.1.0-cp35-none-linux_armv7l.whl is not a supported wheel on this platform.

### ISSUE THREAD

**Issue by jepperaskdk** [tensorflow/tensorflow#37355]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Raspbian 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: Raspberry Pi 3 Model B+
- TensorFlow installed from (source or binary): binary (.whl): https://storage.googleapis.com/tensorflow/raspberrypi/tensorflow-2.1.0-cp35-none-linux_armv7l.whl
- TensorFlow version: 2.1.0
- Python version: 3.7.3
- Installed using virtualenv? pip? conda?: Tried pip in both venv and system wide.
- Bazel version (if compiling from source): 
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

```
pi@raspberrypi:~ $ python3.7 --version
Python 3.7.3
pi@raspberrypi:~ $ pip3.7 --version
pip 20.0.2 from /home/pi/.local/lib/python3.7/site-packages/pip (python 3.7)
pi@raspberrypi:~ $ lsb_release -a
No LSB modules are available.
Distributor ID:	Raspbian
Description:	Raspbian GNU/Linux 10 (buster)
Release:	10
Codename:	buster
```

**Describe the problem**
Attempting to install tensorflow for Raspberry Pi 3, using this guide: https://www.tensorflow.org/install/pip
My Raspberry Pi 3 with Raspbian 10 does not seem able to find or install tensorflow==2.1.0. It only finds 1.14.x.

I tried the various steps in the tutorial, and when attempting to install the RPI3 version found at this link: https://storage.googleapis.com/tensorflow/raspberrypi/tensorflow-2.1.0-cp35-none-linux_armv7l.whl
I get this error (same in venv):
```
pi@raspberrypi:~ $ pip3.7 install tensorflow-2.1.0-cp35-none-linux_armv7l.whl --user
ERROR: tensorflow-2.1.0-cp35-none-linux_armv7l.whl is not a supported wheel on this platform.
```
Attempting to install tensorflow defaults to 1.14:
```
pi@raspberrypi:~ $ pip3.7 install tensorflow --user
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting tensorflow
  Downloading https://www.piwheels.org/simple/tensorflow/tensorflow-1.14.0-cp37-none-linux_armv7l.whl (79.6 MB)
     |▉                               | 2.1 MB 1.5 MB/s eta 0:00:51^C
ERROR: Operation cancelled by user
```

**Comment by julianhu1979** [comment]
I tried on RaspberryOS arm64 version, it doesn't work neither.

**Comment by jw-fujibayashi** [comment]
Me, too. I can't install tensorflow2 to RapberryPi.

**Comment by Remiphilius** [comment]
Did you find a solution? I have a similar problem but on a Pi2b

**Comment by rjadr** [comment]
You're trying to install a build for python 3.5, but you have python 3.7. You can find updated builds [here](https://github.com/lhelontra/tensorflow-on-arm/releases). So run:
`pip3 install https://github.com/lhelontra/tensorflow-on-arm/releases/download/v2.4.0/tensorflow-2.4.0-cp37-none-linux_armv7l.whl`

**Comment by kumariko** [comment]
@jepperaskdk Many bugs have been fixed in the latest version of TF. Could you please try with Latest Version of TF2.6 and let us know if the issue still persists? please check comment: https://github.com/tensorflow/tensorflow/issues/37355#issuecomment-751334345 Thanks!

**Comment by AshweeniKulkarni21** [comment]
> You're trying to install a build for python 3.5, but you have python 3.7. You can find updated builds [here](https://github.com/lhelontra/tensorflow-on-arm/releases). So run: `pip3 install https://github.com/lhelontra/tensorflow-on-arm/releases/download/v2.4.0/tensorflow-2.4.0-cp37-none-linux_armv7l.whl`

thank you, it works for me
