### ISSUE TITLE
Cannot create interpreter: Op builtin_code out or range: 74. Are you using old TFLite binary with newer model?

### ISSUE THREAD

**Issue by LukeChow** [tensorflow/tensorflow#37359]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information** 
- Have I written custom code (as opposed to using a stock
example script provided in TensorFlow): 
Yes
- OS Platform and Distribution (e.g.,
Linux Ubuntu 16.04): 
macOS 10.14.4
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if
the issue happens on mobile device: 
vivo X9 (Android 7.1.2)
- TensorFlow installed from (source or
binary): - TensorFlow version (use command below): 
implementation 'org.tensorflow:tensorflow-lite:0.0.0-nightly'

**Describe the current behavior**

I converted a Keras model to tflite on Mac mini with Tensorflow 2.1.0 installed. But I got error when load the tflite model to Tensorflow lite Interpreter in AndroidStudio 3.5.3:
`Cannot create interpreter: Op builtin_code out or range: 74. Are you using old TFLite binary with newer model?Op builtin_code out or range: 82. Are you using old TFLite binary with newer model?Registration failed.`

**Describe the expected behavior**

It should work like loading mobilenet_v1_1.0_224.tflite from Google's example.
Someone help me please. Thanks a lot.

**Standalone code to reproduce the issue** 
Here is my Kotlin codes in AndroidStudio:
init {
        loadModelFile(MainActivity.mainActivity.assets, "converted_model.tflite")?.let {
            mInterpreter = Interpreter(it)
        }
}

private fun loadModelFile(assets: AssetManager, modelFilename: String): MappedByteBuffer? {
       val fileDescriptor = assets.openFd(modelFilename)
       val inputStream = FileInputStream(fileDescriptor.fileDescriptor)
       val fileChannel = inputStream.channel
        val startOffset = fileDescriptor.startOffset
        val declaredLength = fileDescriptor.declaredLength
        return fileChannel.map(FileChannel.MapMode.READ_ONLY, startOffset, declaredLength)
}

Here is converting codes for Keras model to tflite:

import tensorflow as tf
if __name__ == '__main__':
    model = tf.keras.models.load_model('speech_model251_e_0_step_45500.base.h5')
    converter = tf.lite.TFLiteConverter.from_keras_model(model)
    tflite_model = converter.convert()
    open("converted_model.tflite", "wb").write(tflite_model)

**Other info / logs** 
java.lang.IllegalArgumentException: Internal error: Cannot create interpreter: Op builtin_code out or range: 74. Are you using old TFLite binary with newer model?Op builtin_code out or range: 82. Are you using old TFLite binary with newer model?Registration failed.
        at org.tensorflow.lite.NativeInterpreterWrapper.createInterpreter(Native Method)
        at org.tensorflow.lite.NativeInterpreterWrapper.<init>(NativeInterpreterWrapper.java:73)
        at org.tensorflow.lite.NativeInterpreterWrapper.<init>(NativeInterpreterWrapper.java:52)
        at org.tensorflow.lite.Interpreter.<init>(Interpreter.java:114)

**Comment by LukeChow** [comment]
This model worked about 7 months ago on iOS APP with Xcode and cocoapods. I think maybe now Tensorflow lite is newer and my model is too old. If only I could use older TensorFlow Lite. But I can't, because it's always version 0.0.0-nightly.

**Comment by jvishnuvardhan** [comment]
@LukeChow 
1) Did you use TF1.x to create the model or `TF2.1`?
2) can you share the model and a standalone code? Thanks!

**Comment by jvishnuvardhan** [comment]
@LukeChow

Did you use TF1.x to create the model or TF2.1?
can you share the model and a standalone code? Thanks!

**Comment by LukeChow** [comment]
> @LukeChow
> 
> Did you use TF1.x to create the model or TF2.1?
> can you share the model and a standalone code? Thanks!

The model is created with TF1.x. I compiled Tensorflow Lite 1.x by myself. Loading model is work with it. But the output is not correct comparing to result in iOS which using the same model and same data. The Tensorflow Lite SDKs are both 1.x in iOS and Android (downloaded around August 2019).
——
iOS codes (result is as expected):
self.interpreter = [[TFLInterpreter alloc] initWithModelPath:modelPath error:&error];
[self.interpreter allocateTensorsWithError:&error];
self.inputTensor = [self.interpreter inputTensorAtIndex:0 error:&error];
self.outTensor = [self.interpreter outputTensorAtIndex:0 error:&error];
[self.inputTensor copyData:data error:&error];
 [self.interpreter invokeWithError:&error];
NSMutableData *resultData = [NSMutableData dataWithData: [self.outTensor dataWithError:&error]];
——
Android codes:
loadModelFile(MainActivity.mainActivity.assets, "converted_model.tflite")?.let {
mInterpreter = Interpreter(it)
}
val resultData = ByteArray(shape1 * shape2 * 4)
mInterpreter.run(ByteBuffer.wrap(data), ByteBuffer.wrap(resultData))

**Comment by jvishnuvardhan** [comment]
@LukeChow Can you Please share the model and a standalone code to reproduce the issue? Thanks!

**Comment by LukeChow** [comment]
> > @LukeChow
> > Did you use TF1.x to create the model or TF2.1?
> > can you share the model and a standalone code? Thanks!
> > @jvishnuvardhan
> 
> The model was created with TF1.x. I'm now using Tensorflow Lite 1.x compiled by myself. Loading model works with it. But the output is not correct comparing to result in iOS which using the same model and same data. The Tensorflow Lite SDKs are both 1.x in iOS and Android (downloaded around August 2019).
> ——
> iOS codes (result is as expected):
> self.interpreter = [[TFLInterpreter alloc] initWithModelPath:modelPath error:&error];
> [self.interpreter allocateTensorsWithError:&error];
> self.inputTensor = [self.interpreter inputTensorAtIndex:0 error:&error];
> self.outTensor = [self.interpreter outputTensorAtIndex:0 error:&error];
> [self.inputTensor copyData:data error:&error];
> [self.interpreter invokeWithError:&error];
> NSMutableData *resultData = [NSMutableData dataWithData: [self.outTensor dataWithError:&error]];
> ——
> Android codes:
> loadModelFile(MainActivity.mainActivity.assets, "converted_model.tflite")?.let {
> mInterpreter = Interpreter(it)
> }
> val resultData = ByteArray(shape1 * shape2 * 4)
> mInterpreter.run(ByteBuffer.wrap(data), ByteBuffer.wrap(resultData))

This is caused by other parts of the code. 😅
