### ISSUE TITLE
tf_upgrade_v2 fails to deal with set_session

### ISSUE THREAD

**Issue by PhanatosZou** [tensorflow/tensorflow#37366]
**System information**  
- Linux Ubuntu 16.04: 
- TensorFlow 2.0
- Python 3.6

I use `tf_upgrade_v2` to convert my script from TF1.14 to 2.0. But the converted script run into an error. 

```
Traceback (most recent call last):
  File "test_mspeech_origin.py", line 23, in <module>
    set_session(tf.compat.v1.Session(config=config))
  File "/usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py", line 400, in set_session
    '`set_session` is not available '
RuntimeError: `set_session` is not available when using TensorFlow 2.0.
```

Finally I changed the code manually to make it work.
```
sess = tf.compat.v1.Session(config)
tf.compat.v1.keras.backend.set_session(sess)
```

Is there anything going with `set_session` when use `tf_upgrade_v2`?

**Comment by Saduf2019** [comment]
@PhanatosZou 
We see that with respect to this issue there is existing discussion, please refer [to this](https://github.com/OlafenwaMoses/ImageAI/issues/372#issuecomment-539216312)

**Comment by Saduf2019** [comment]
Also please refer to [this link](https://github.com/OlafenwaMoses/ImageAI/issues/367#issuecomment-578531046) and let us know if it helps

**Comment by PhanatosZou** [comment]
@Saduf2019 Seems like a possible way to make it work is to downgrade to a lower version. Would it be fixed in TF2.0 or further versions?

**Comment by ymodak** [comment]
`set_session` is deprecated too with TF 2.X. So you have to use `compat.v1` for using it in TF2.
