### ISSUE TITLE
CMSIS-NN kernel is slower than C-reference kernel

### ISSUE THREAD

**Issue by ml-0** [tensorflow/tensorflow#37361]
@tensorflow/micro

**System information**
- Host OS Platform and Distribution: Linux Ubuntu 18.04 in WSH on Win10
- TensorFlow installed from (source or binary): source
- Tensorflow version: 4030aa1fe5bdd846301f379d1f1a0e58efbceae4
- Target platform: SparkFun Edge (Cortex M4F)

**Describe the problem**
Since commit 4030aa1fe5bdd846301f379d1f1a0e58efbceae4 the convolutional layers (conv, depthwise_conv) from the C-reference kernel are equally fast as the optimized CMSIS-NN kernel or even faster. Due to the 4x SIMD acceleration it is expected that the CMSIS-NN kernel significantly faster. The issue was NOT introduced by this commit, it just made the issue visible.
To my understanding the root cause is the compiler option '-fno-builtin'. Removing this option from the Makefile (e.g. for the SparkFun edge board in tensorflow/lite/micro/tools/make/targets/apollo3evb_makefile.inc) speeds up the CMSIS-NN kernel by factor of 3-6 while the reference kernel does not change.
Note: in order to let TFL micro use the CMSIS-NN kernel an int8 quantized model must be used. Otherwise, the TFL micro interpreter falls back to the reference kernel, anyway. Unfortunately, I was not able to find an int8 quantized model under tensorflow/lite/micro/examples

**Please provide the exact sequence of commands/steps when you ran into the problem**
1. Create a project <my_project> using an appropriate int8 quanized model. e.g. by copying the tensorflow/lite/micro/examples/hello_world example.
   Replace the model and input data by a model with convolutional layers and int8 quantization!
   
2. Instrument the call to the interpreter with some pin toggling, e.g.
  am_hal_gpio_output_set(38);
  TfLiteStatus invoke_status = interpreter->Invoke();
  am_hal_gpio_output_clear(38);

3. Build the project for the reference kernel, measure execution time:
make -f tensorflow/lite/micro/tools/make/Makefile clean
make -f tensorflow/lite/micro/tools/make/Makefile TARGET=sparkfun_edge <my_project>_bin
--> measure model execution time

4. Build the project for the CMSIS-NN kernel, measure execution time:
make -f tensorflow/lite/micro/tools/make/Makefile clean
make -f tensorflow/lite/micro/tools/make/Makefile TAGS=cmsis-nn TARGET=sparkfun_edge <my_project>_bin
--> measure model execution time

5. Remove '-fno-builtin' option from tensorflow/lite/micro/tools/make/targets/apollo3evb_makefile.inc
(delete the line, not just comment out)

6. Build the project for the reference kernel without '-fno-builtin', measure execution time:
make -f tensorflow/lite/micro/tools/make/Makefile clean
make -f tensorflow/lite/micro/tools/make/Makefile TARGET=sparkfun_edge <my_project>_bin
--> measure model execution time

7. Build the project for the CMSIS-NN kernel without '-fno-builtin', measure execution time:
make -f tensorflow/lite/micro/tools/make/Makefile clean
make -f tensorflow/lite/micro/tools/make/Makefile TAGS=cmsis-nn TARGET=sparkfun_edge <my_project>_bin
--> measure model execution time

The execution times from 4 is not (much) shorter than from 3, eventually it is even longer.
The execution times from 7 is 3-6x times shorter than from 6, which is the expected SIMD acceleration.

**Comment by ml-0** [comment]
I have attached an example project that includes a cifar10 example. The network consists of three convolutional layers. Place the example into the tensorflow/lite/micro/examples/ directory and execute the above listed steps for it:
make -f tensorflow/lite/micro/tools/make/Makefile TARGET=sparkfun_edge cifar10_bin
make -f tensorflow/lite/micro/tools/make/Makefile TAGS=cmsis-nn TARGET=sparkfun_edge cifar10_bin

The execution times show that the interpreter benefits from the CMSIS-NN kernel only if '-fno-builtin' is not specified:

14.05s: Reference Kernel, with '-fno-builtin'
13.13s: CMSIS-NN  Kernel, with '-fno-builtin'
14.01s: Reference Kernel, without '-fno-builtin'
 2.33s:  CMSIS-NN  Kernel, without '-fno-builtin'

[cifar10.zip](https://github.com/tensorflow/tensorflow/files/4297754/cifar10.zip)

**Comment by freddan80** [comment]
Hi @ml-0 ! '-fno-builtin' utilizes optimized implementations of e.g. memcpy and memset, which are heavily used by CMSIS-NN. This could be the reason why you see a difference. I assume you use GCC? Here's some more info:

https://gcc.gnu.org/onlinedocs/gcc/C-Dialect-Options.html

Thanks for showing interest in the CMSIS-NN lib!

**Comment by ml-0** [comment]
Hi @freddan80, thanks for your reply. I know that '-fno-builtin' can be used to add optimized versions of build-in functions. What would be the intention of using this option? I guess it is to speed-up the CMSIS-NN kernel, right? 
Unfortunately, what I observe is the opposite: with '-fno-builtin' specified the execution time of the CMSIS-NN kernel on the SparkFun Edge (and on my Cypress PSoC6 board) is the same as for (or even slower than) the reference kernel. Without '-fno-builtin' in the Makefile the CMSIS-NN kernel is up to 6x faster.
Do you have the chance to mesarure the execution time on an Cortex M4F device (e.g. SparkFun Edge) with and without this option? And to compare this with the reference kernel?

**Comment by freddan80** [comment]
Sorry for the confusion. I edit:ed my previous comment.
>  '-fno-builtin' **do not** utilize optimized implementations of e.g. memcpy and memset

**Comment by ml-0** [comment]
Hi @freddan80, I see that you have edited your previous post and inverted the "do not utilize". Does it mean that the built-in versions of memcpy and memset are faster and should be used? Then my question is: why is the option '-fno-builtin' specified in all Makefiles for Cortex M3 and M4 target (apollo3evb_makefile.inc, bluepill_makefile.inc, ecm3531_makefile.inc, stm32f4_makefile.inc). At least on my SparkFun Edge board it makes the performance of the CMSIS kernel lower than is could be. Shouldn't such 'officially supported' boards also demonstrate the benefit of CMSIS-NN?

**Comment by freddan80** [comment]
> Does it mean that the built-in versions of memcpy and memset are faster and should be used?

Yes, they are faster.

> Then my question is: why is the option '-fno-builtin' specified in all Makefiles for Cortex M3 and M4 target (apollo3evb_makefile.inc, bluepill_makefile.inc, ecm3531_makefile.inc, stm32f4_makefile.inc).

Interesting observation! We haven't used these target configs for benchmarking CMSIS-NN (using FPGA boards with ref systems)

> Shouldn't such 'officially supported' boards also demonstrate the benefit of CMSIS-NN?

Currently most usecases are based on unit8 models, for which we don't have much CMSIS-NN support. For that reason I guess this issue hasn't been spotted yet.

@MeghnaNatraj , do you know the background to why '-fno-builtin' is set in the target configs?

@ml-0 , thanks for spotting this!

**Comment by freddan80** [comment]
https://github.com/tensorflow/tensorflow/pull/37936

**Comment by MeghnaNatraj** [comment]
Marking this as resolved as #37936 is merged.

**Comment by felix-johnny** [comment]
For the record.. -ffreestanding is another option that enables -fno-builtin implicitly.
