### ISSUE TITLE
Element/Coefficient wise Mul  _MklMul

### ISSUE THREAD

**Issue by whatdhack** [tensorflow/tensorflow#37370]
Occasionally  see that for element/coefficient wise multiplication ( e.g.  scalar*tensor or tensor*tensor) that multiple types of operators are used  ( e.g. Mul and _MklMul) .  My questions are as follows,

1.  Is there any difference between Mul and _MklMul ? 
2. Why  for some Ops Mul is picked and for others _MklMul is picked ? 

Files referring to Ops/Kernels  are as follows:
https://github.com/tensorflow/tensorflow/blob/r1.15/tensorflow/core/ops/math_ops.cc
https://github.com/tensorflow/tensorflow/blob/r1.15/tensorflow/core/kernels/cwise_op_mul_1.cc
https://github.com/tensorflow/tensorflow/blob/r1.15/tensorflow/core/kernels/mkl_cwise_ops_common.cc

**Comment by NeoZhangJianyu** [comment]
@whatdhack 

Sorry, there is no track for a long time!
Do you still need the support for this issue?

**Comment by NeoZhangJianyu** [comment]
@whatdhack 

Do you still need to support for this issue?

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.
