### ISSUE TITLE
matplotlib.mlab has been removed, update code please

### ISSUE THREAD

**Issue by dynamor2019** [tensorflow/tensorflow#37379]
## URL(s) with the issue:

a link to the documentation entry
https://tensorflow.google.cn/tutorials/estimator/boosted_trees_model_understanding

## Description of issue (what needs changing):
A bug I found in "TensorFlow > Learn > TensorFlow Core > Tutorials > Gradient Boosted Trees: Model understanding" as below:

matplotlib.mlab has been removed @ version 3.1.0 "https://matplotlib.org/3.1.0/api/api_changes.html"
but the tutorials still uses _griddata_ class for plotting, i can not get the result follow this.

so would you mind adjust this for correct code? i am a beginner for tensorflow and python, so fix it by myself is difficult for me ,thanks

**Comment by jvishnuvardhan** [comment]
@dynamor2019 Thanks for filing this issue. Yes, we need to update the tutorial. We need to use `griddata` from `scipy`. So need to import like this `from scipy.interpolate import griddata`. Thanks!

**Comment by lamberta** [comment]
Thanks for the report. That file lives over here in the tensorflow/docs repo: https://github.com/tensorflow/docs/blob/master/site/en/tutorials/estimator/boosted_trees_model_understanding.ipynb
Please send a pull request 😀

**Comment by MarkDaoust** [comment]
+ @crawles

**Comment by ayushmankumar7** [comment]
Can I make a PR for this Issue ? @lamberta  @MarkDaoust

**Comment by jvishnuvardhan** [comment]
I am closing the issue as the related PR got merged. Please feel free to reopen if this was not resolved. Thanks!
