### ISSUE TITLE
Inconsistent device placement when using nondifferentiable_batch_function and GPU

### ISSUE THREAD

**Issue by damirtm** [tensorflow/tensorflow#37382]
**System information** 
- Have I written custom code (as opposed to using a stock
example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g.,
Linux Ubuntu 16.04): colab.research.google.com
- TensorFlow installed from (source or
binary): - 2.1.0 (latest)
- Python version: Google colab python 3
- CUDA/cuDNN version: Google colab GPU

I'm trying to test the possibility of using `nondifferentiable_batch_function` for inference. Specifically, I need to collect batches and execute them on GPU for better throughput. I'm aware that there are some other approaches (e.g. using tensorflow serving batching) but using a batching function within a graph could be beneficial for my current setup. While experimenting with different approaches I found out that device placement for operations wrapped by batch function could be highly inconsistent. I have managed to execute operations on GPU by wrapping concrete function into batch function and then save the model but other approaches didn't work:
```
signature = (tf.TensorSpec(shape=[None, 3], dtype=tf.float32, name="x"),)

@tf.function(input_signature=signature)
def run(x):
  with tf.device("/GPU:0"):
        return tf.nn.relu(tf.matmul(x, tf.random.uniform((3, 1))))

concrete_run = run.get_concrete_function()

@tf.nondifferentiable_batch_function(1, 6, 10)
def batch_run(x):
    return concrete_run(x)

class Model(tf.Module):
    @tf.function(input_signature=signature)
    def run(self, x):
        return batch_run(x)

model = Model()
x = tf.random.uniform((3, 3))

# MatMul and Relu are executed on CPU
model.run(x)

concrete_model_run = model.run.get_concrete_function()

# MatMul and Relu are executed on CPU
concrete_model_run(x)

tf.saved_model.save(model, "model", signatures={ "run": model.run })
model = tf.saved_model.load("model")

# MatMul and Relu are executed on GPU
model.signatures["run"](x=x)
```
Please find full test there https://colab.research.google.com/drive/1ZcIbnixdcQ2OSabEAlcf5SYYdkoRzYtu

I expected that the use of nondifferentiable_batch_function would be consistent despite the approach. A particular problem that I face right now is that saved model (with GPU placed ops) when loaded by tensorflow serving still executes operations on CPU and I believe that issues are connected.

**Comment by Saduf2019** [comment]
@dtim1985 
I have run the code shared by you but face a different error, please find the [gist here](https://colab.sandbox.google.com/gist/Saduf2019/670869059455d9c71e903810064ac2fe/37382.ipynb)

**Comment by dtim1985** [comment]
@Saduf2019 I clarified tf version number 2.X -> 2.1.0 - which is the current colab latest version. 
I don't have any errors even with tf-nightly when running the gist you privded and error itself `load() missing 2 required positional arguments: 'tags' and 'export_dir'` looks pretty odd as there is only one required parameter - and it is `export_dir`.
Unfortunately, I can't confirm the original issue for tf-nightly as tensorboard profiler does not work there and I can't easily check whether code is executed on GPU.

**Comment by mdanatg** [comment]
@rohan100jain cold you help triage this?

**Comment by Saduf2019** [comment]
@damirtm 
Could you please try on the latest version and let us know if this is still an issue.
